### ISSUE TITLE
Implement PerfMap generation in Crossgen2

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#44123]
As part of replacing Crossgen with Crossgen2, we need an equivalent of the Crossgen option /CreatePerfMap.

**Comment by trylek** [comment]
@davidwrighton / @janvorli - assuming I implement the PerfMap format, how do I go about testing it? I'm getting it's somehow related to PerfView and Linux, is the workflow described somewhere?

**Comment by trylek** [comment]
One thing that comes to mind in particular is the function signature formatting; are we required to replicate CoreCLR MethodDesc formatting?

**Comment by davidwrighton** [comment]
@trylek, you'll need to talk to @brianrob, and see what the implications are. You want to understand the interactions with the perfcollect script and perfview.

**Comment by trylek** [comment]
OK, so technically both Crossgen2 and R2RDump support generating perfmaps now (as of https://github.com/dotnet/runtime/pull/47019). I guess that the remaining bit needed to close this item is to actually validate that PerfMap works as expected. I performed a round of local testing of PDB generator using PerfView based on David's advice but I merged in the PerfMap generator based on just visual validation of the file format as there's currently no workflow in existence to actually exercise it. 

@brianrob, would you be willing to work with me on figuring out the plan for the next step i.e. switching perfcollect to *somehow use the Crossgen2 / R2RDump infrastructure* for generating R2R PerfMap files, validating the new diagnostic experience and ideally fixing this validation in terms of some diagnostic lab testing?

FYI @hoyosjs @agocke @tommcdon

**Comment by brianrob** [comment]
@trylek, definitely.  This is probably a relatively trivial change to perfcollect.  It's important for versions of perf that can't process jitdumps (this is the format that the Linux perf tool can consume to resolve non-ELF symbols), but this is becoming less and less common.

**Comment by trylek** [comment]
I believe that the remaining work on perfmap files is tracked by https://github.com/dotnet/sdk/issues/18813 and this issue can be closed.
