### ISSUE TITLE
API Proposal: Memory<byte> apis for MemoryStream

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#44140]
## Background and Motivation

Saw code in roslyn creating MemoryStream from underlying array of ImmutableArray.

https://github.com/dotnet/roslyn/blob/a6f654bb03596c2c3392bb16f082cc1615fac425/src/Compilers/CSharp/Test/Emit/Emit/CompilationEmitTests.cs#L921-L922

## Proposed API

```diff
namespace System.IO
{
    public class MemoryStream
    {
+        public MemoryStream(Memory<byte> memory);
+        public MemoryStream(ReadOnlyMemory<byte> memory);
+        public MemoryStream(Memory<byte> memory, bool writable);
+        public MemoryStream(Memory<byte> memory, bool writable, bool publicVisible);

        public bool TryGetBuffer(out ArraySegment<byte> buffer);
        // Use a different name to not break `out var`
+       public bool TryGetMemoryBuffer(out Memory<byte> buffer);
    }
}
```

## Usage Examples

``` C#
new MemoryStream(image1.AsMemory())
```

## Alternative Designs

A new class named `ReadOnlyMemoryStream`? The current `MemoryStream` is actually "array stream", but takes the name.

## Risks

Unlike span, memory is slower than array AFAIK. Delegating array implementation to `Memory` may cause performance regression.
`Memory` and `ReadOnlyMemory` may require 2 versions of fields, or some casting hacks.

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/22838

**Comment by huoyaoyuan** [comment]
Sure, that issue covers the scenario. It's a bit old and needs work, please don't forget it.
