### ISSUE TITLE
Sending email with SmtpClient with support for self-signed certificate.

### ISSUE THREAD

**Issue by ShreyasZare** [dotnet/runtime#44145]
SmtpClient class in .NET Framework allowed to accept self-signed certificate using the `ServicePointManager.ServerCertificateValidationCallback` which seems to not work with .NET Core. The stack trace in the exception tells that the .NET Core SmtpClient uses `SslStream` underneath which has its own `System.Net.Security.RemoteCertificateValidationCallback` in constructor to manage such a scenario but, this is not accessible via SmtpClient to the developer. This seems to be a breaking change for migrating app to .NET Core. 

Is there a way to achieve it in .NET Core? If not, is anything planned for such scenario?

**Comment by wfurt** [comment]
I did quick search and I did not see any easy way how to do that. As far as planning, SmtpClient is viewed as legacy and does not get much effort. I would recommend to use some other package. https://dotnetfoundation.org/projects has list of packages complementing basic .NET Core work. Perhaps MailKit from that list could be good fit.

**Comment by ShreyasZare** [comment]
Thanks for the response. There was some misdiagnosis of the issue and the `ServicePointManager.ServerCertificateValidationCallback` callback is confirmed to be working on both Windows and Linux on .NET Core 3.1.
