### ISSUE TITLE
Unable to build dotnet/runtime due to cmake error about MultiThreadedDebug

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44152]
I'm unable to build dotnet/runtime after sync'ing and trying to do a clean build:
```
  CMake Error in D:/repos/runtime/src/libraries/Native/Unix/System.Globalization.Native/CMakeLists.txt:
    MSVC_RUNTIME_LIBRARY value 'MultiThreadedDebug' not known for this ASM_MASM
    compiler.
```
Note I'm building on Windows; I don't know why it's trying to process a unix cmakelists.

@jkoritzinsky, I assume this is due to https://github.com/dotnet/runtime/pull/41897?

Do I need to somehow update my local configuration?

**Comment by jkoritzinsky** [comment]
Try cleaning your artifacts folder. In the meantime, I’ll investigate to see if I can repro locally.

**Comment by stephentoub** [comment]
I've done a full git clean -xdf.  No artifacts folder.

**Comment by jkoritzinsky** [comment]
I'm looking now.

**Comment by jkoritzinsky** [comment]
Which command are you using to build? (To make sure I'm checking the right execution sequence in CMake)

**Comment by jkoritzinsky** [comment]
This looks like it was a bug in CMake that was fixed in 3.16.4. I'll put out a PR with the fix ASAP (since our minimum on Windows is 3.15.5 and our recommended version is 3.16.0+).

**Comment by jkoritzinsky** [comment]
I have a fix in https://github.com/dotnet/runtime/pull/44155. Can you pull down my PR and try building locally?

**Comment by stephentoub** [comment]
Trying...

**Comment by stephentoub** [comment]
Build is still going, but it's gotten past where it was failing before, so that's a good sign.

**Comment by jkoritzinsky** [comment]
Once your build passes, I'm comfortable merging in #44155 before CI finishes to unblock people.

**Comment by stephentoub** [comment]
It finished successfully. Thanks.
