### ISSUE TITLE
mono_wasm_timezone_get_local_name() throws an unhandled exception

### ISSUE THREAD

**Issue by liorbalmas** [dotnet/runtime#44154]
mono_wasm_timezone_get_local_name throws an unhandled exception when failing to resolve timezone from OS

### To Reproduce
Not able to do so now ,as fixed the running server's timezone and didn't notice what it was before.
Point is Intl.DateTimeFormat().resolvedOptions().timeZone might return undefined in some cases and code should expect that.

### Exceptions (if any)
unhandled exception

### Further technical details
netstandard2.1

**Comment by mkArtakMSFT** [comment]
@lewing  FYI

**Comment by lewing** [comment]
@liorbalmas what version of blazor are you using? 

The net5.0 version wraps that code in a try/catch

https://github.com/dotnet/aspnetcore/blob/628ce6114bd426c80e57f637234fe94cf9b37c7d/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L425

**Comment by campersau** [comment]
`timeZone` could return `undefined`:

> timeZone
> The value provided for this property in the options argument; undefined (representing the runtime's default time zone) if none was provided. Warning: Applications should not rely on undefined being returned, as future versions may return a String value > identifying the runtime’s default time zone instead.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions

So the code should look like this:

```js
    let timeZone;
    try {
      timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    } catch { }
    MONO.mono_wasm_setenv("TZ", timeZone || "UTC");
```

**Comment by lewing** [comment]
@campersau ah good point I just read the exception bit.  I imagine this mostly impacts CI?

**Comment by campersau** [comment]
@lewing I think it just depends if the timezone is defined or not (see OP), not sure how CI servers are setup up. Does this also need to be fixed here?

https://github.com/dotnet/runtime/blob/ee74ce2a69d533287a60d97b6360412fbc14a14f/src/mono/wasm/runtime/driver.c#L930-L941

**Comment by lewing** [comment]
@campersau  that code needs a different fix, it isn't used in the blazor case though.  I meant it is typically CI that doesn't have a timezone set, that isn't a comment scenario for a browser in use.  The initial issue mentioned the server's timezone which sounded like CI.

**Comment by lewing** [comment]
The fixes for this have landed. Closing

**Comment by lewing** [comment]
@liorbalmas the 5.0.1 servicing release should include a fix for this
