### ISSUE TITLE
Blazor Wasm AssemblyLoadContext Unload not working as expected

### ISSUE THREAD

**Issue by andersson09** [dotnet/runtime#44153]
### Description

Hi, I am testing the AssemblyLoadContext Unload feature in Blazor wasm but it doesn't look like it is clearing any references. I have created a very basic test as follows:

**Console App (works as expected, ie. weakReference.IsAlive returns false)**

```
    public class AssemblyContainer : AssemblyLoadContext
    {
        public AssemblyContainer() : base(isCollectible: true)
        {
            
        }

        protected override Assembly Load(AssemblyName name)
        {
            return null;
        }
    }

    class Program
    {
        private static WeakReference weakReference;

        static void Main(string[] args)
        {
            Execute();

            for (int i = 0; weakReference.IsAlive && (i < 10); i++)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }

            Console.WriteLine("Cleared");
            Console.WriteLine(weakReference.IsAlive);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Execute()
        {
            var testObject = new AssemblyContainer();
            weakReference = new WeakReference(testObject);
        
            testObject.Unload();
        }
    }
```

**Blazor wasm (does not work as expected, i.e. weakReference.IsAlive returns true)**

```
<button type="button" class="btn btn-primary" @onclick="Run">
    Run
</button>

<button type="button" class="btn btn-primary" @onclick="CheckWeakReference">
    Check WeakReference
</button>

@code 
{   
    private static WeakReference weakReference;

    private static Run()
    {
        Execute();

        for (int i = 0; weakReference.IsAlive && (i < 10); i++)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }

        Console.WriteLine("Cleared");
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Execute()
    {
        var testObject = new AssemblyContainer();
        weakReference = new WeakReference(testObject);
    
        testObject.Unload();
    }

    private void CheckWeakReference()
    {
        Console.WriteLine(weakReference.IsAlive);
    }
}
```

If I comment out testObject.Unload() it will return false as expected.

Thank you

### Configuration

-Net5 Rc2
-Windows 10 Pro
-Wasm
-Chrome

**Comment by CoffeeFlux** [comment]
Assembly unloading is intentionally not functional in Mono for 5.0. The method will not error, but neither will it actually unload anything. This will hopefully be part of 6.0 instead, sorry.

**Comment by andersson09** [comment]
> Assembly unloading is intentionally not functional in Mono for 5.0. The method will not error, but neither will it actually unload anything. This will hopefully be part of 6.0 instead, sorry.

Yeah, but the program as a whole will eventually error with a memory exception since it cant unload any assemblies. Do you know of any work arounds in the meantime? 

Also with .net6 can I expect this fix to be part of a prerelease version or do I have to wait till Nov 2021?

Thank you

**Comment by CoffeeFlux** [comment]
This may show up in a preview release but I can't give you any time schedule. If your application relies on unloading to avoid running out of memory, you will have to adjust that behavior for Blazor in net5.

**Comment by lewing** [comment]
@CoffeeFlux is this a duplicate or should it be reopened with an appropriate milestone?

**Comment by CoffeeFlux** [comment]
@lewing duplicate, https://github.com/dotnet/runtime/issues/34072
