### ISSUE TITLE
[Mono][Perf] JIT Performance Regression, multiple benchmarks, 7 % to 909 % 

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#44166]
This is a master issue to track a performance regression effecting several benchmarks that seem related.

The date range suggests that the cause is one of the commits in this range: https://github.com/dotnet/runtime/compare/24d504315719eb55204925d25071371a5dfc073e...7664a9adb038397d6e595a681f9460c5bcbe2d3a of which, only https://github.com/dotnet/runtime/commit/c723f5e6cce5187034496d708902795ffddd02c1 is plausible.

These are the effected  benchmarks on their auto-filed issues:

  JIT 
[Perf -20%] PerfLabTests.LowLevelPerf.GenericClassGenericStaticField
https://github.com/DrewScoggins/performance-2/issues/2887 

[Perf -11%] PerfLabTests.LowLevelPerf.NewDelegateClassEmptyStaticFn 
https://github.com/DrewScoggins/performance-2/issues/2996  [Perf -18%] System.Threading.Tests.Perf_Lock.ReaderWriterLockSlimPerf 
https://github.com/DrewScoggins/performance-2/issues/2709

[Perf -27%] System.Xml.Linq.Perf_XDocument.Create 
https://github.com/DrewScoggins/performance-2/issues/2712

[Perf -9%] System.Tests.Perf_UInt16.ToString
https://github.com/DrewScoggins/performance-2/issues/2707

[Perf -13%] Burgers.Test0 
https://github.com/DrewScoggins/performance-2/issues/2995

[Perf -14%] System.Threading.Tasks.ValueTaskPerfTest.CreateAndAwait_FromYieldingAsyncMethod
https://github.com/DrewScoggins/performance-2/issues/2703

[Perf -10%] System.Numerics.Tests.Perf_VectorConvert.Convert_uint_float
https://github.com/DrewScoggins/performance-2/issues/2994

[Perf -12%] System.Threading.Channels.Tests.SpscUnboundedChannelPerfTests.PingPong
https://github.com/DrewScoggins/performance-2/issues/2993

[Perf -13%] Devirtualization.Boxing.InterfaceTypeCheckAndCall
https://github.com/DrewScoggins/performance-2/issues/2724

[Perf -12%] System.Threading.Tasks.Tests.Perf_AsyncMethods.SingleYieldMethodInvocation
https://github.com/DrewScoggins/performance-2/issues/2992

[Perf -9%] System.Tests.Perf_Array.ArrayAssign3D 
https://github.com/DrewScoggins/performance-2/issues/2991

https://github.com/DrewScoggins/performance-2/issues/2715
[Perf -32%] System.Tests.Perf_Object.ctor 

[Perf -7%] Benchstone.BenchF.BenchMk2.Test 
https://github.com/DrewScoggins/performance-2/issues/2990

[Perf -13%] System.Numerics.Tests.Perf_Vector3.SquareRootBenchmark
https://github.com/DrewScoggins/performance-2/issues/2989

https://github.com/DrewScoggins/performance-2/issues/2720
[Perf -15%] System.Threading.Channels.Tests.BoundedChannelPerfTests.PingPong

https://github.com/DrewScoggins/performance-2/issues/2706
[Perf -193%] System.Threading.Tests.Perf_Timer.ShortScheduleAndDisposeWithFiringTimers

https://github.com/DrewScoggins/performance-2/issues/2717
[Perf -9%] Benchstone.BenchF.Simpsn.Test

[Perf -6%] System.Memory.Constructors<String>.ReadOnlySpanImplicitCastFromArraySeg
https://github.com/DrewScoggins/performance-2/issues/2988  [Perf -809%] 

System.Threading.Tests.Perf_ThreadStatic.GetThreadStatic
https://github.com/DrewScoggins/performance-2/issues/2711  

[Perf -9%] System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Bytes https://github.com/DrewScoggins/performance-2/issues/2987

  [Perf -15%] Microsoft.Extensions.DependencyInjection.GetServiceIEnumerable.Transient https://github.com/DrewScoggins/performance-2/issues/2716

 [Perf -17%] System.Numerics.Tests.Perf_Vector4.SquareRootBenchmark https://github.com/DrewScoggins/performance-2/issues/2696  

[Perf -7%] System.Collections.Tests.Perf_BitArray (2) 
https://github.com/DrewScoggins/performance-2/issues/2700  Interprter:   https://github.com/DrewScoggins/performance-2/issues/2887 

[Perf -20%] PerfLabTests.LowLevelPerf.GenericClassGenericStaticField

**Comment by naricc** [comment]
@vargaz It looks like the change to building with cmake may be responsible for this regression, based on the dates.

**Comment by vargaz** [comment]
What platform is this ?

**Comment by naricc** [comment]
@vargaz ubuntu x64

**Comment by vargaz** [comment]
Can't reproduce this locally, a lot of these benchmarks are very simple, the first one is:
                for (int i = 0; i < n_iter; i++)
                    GenericClass<int>.aGenericStaticFieldT = 1;
which just gets compiled into a simple loop.

**Comment by vargaz** [comment]
Can somebody reproduce this locally ?

**Comment by naricc** [comment]
@vargaz What is the issue with reproducing it? You were not able to run the benchmarks, or you did and it didn't repro? System.Threading.Tests.Perf_Timer.ShortScheduleAndDisposeWithFiringTimers seems like the biggest difference, so it should be the easiest to see, if it is a real issue.

**Comment by naricc** [comment]
I am not sure what cause this, but it seems to have resolved itself.
