### ISSUE TITLE
System.Net.Quic needs a PNSE configuration for Browser

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44192]
Shared framework assemblies need to support all configurations and we are currently missing a configuration for Browser for System.Net.Quic.

Blocks https://github.com/dotnet/runtime/pull/38457

@scalablecory as this issue is blocking, would you mind working on it?

cc @jkoritzinsky @ericstj

**Comment by geoffkizer** [comment]
What does this entail?

**Comment by marek-safar** [comment]
We need PNSE version for Browser configuration. You can check e.g. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Ping/src/System.Net.Ping.csproj how it'd one

**Comment by ViktorHofer** [comment]
I will take care of this.

**Comment by geoffkizer** [comment]
Thanks @ViktorHofer
