### ISSUE TITLE
Make it easier to file issues for CI failures

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#44207]
There's been a push from the infrastructure team to open issues when we see flaky failures on CI, but currently relatively few people bother to do this. I tried to for a couple days, but it's relatively time-consuming if you want to open a detailed issue. It would be nice to have a script/tool to quickly pull the relevant links and failure logs from CI and give me a blurb I could paste into an issue with added commentary, so I don't have to spend a bunch of time chasing AzDO links to get the information I want.

**Comment by ViktorHofer** [comment]
Mission Control (MC) allowed you to do that in the past. I know that AzDO has something similar but I don't think it works with GH repos. @jaredpar is currently working on tooling that allows to query for error kinds but I'm unsure if this will help with the issue filing from an AzDO build perspective.

cc @dotnet/runtime-infrastructure

**Comment by akoeplinger** [comment]
GitHub supports query parameters for setting the issue title/body so I guess runfo could support that: https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by ViktorHofer** [comment]
Runfo already has that ability to create an issue but it entails that you first need to go to runfo and search for that issue. I think this should be easier, ie with an AzDO extension?

**Comment by akoeplinger** [comment]
I think what would be nice is if I could just paste the AzDO build link into runfo and it goes and grabs all the info and then allows me to file GH issue(s), so that I don't need to manually copy/paste failing test names, job names, build links etc.

**Comment by ViktorHofer** [comment]
runfo is open source ;)

cc @jaredpar

**Comment by jaredpar** [comment]
@akoeplinger 

I've thought about making it easier to file one off issues, issues which don't auto-track against new builds. I haven't thought of a good workflow though to enable here. 

For any given build you can already see a list of the tracked data. Essentially insert a build number in this link and you get a dump of all the timeline issues, test failures and issues already assigned to this build

https://runfo.azurewebsites.net/view/build/?Number=872211

From there though what would imagine the work flow being? I thought about having a "create GitHub Issue" button on the various search pages that copied tables to markdown (that's easy enough). That though means the issue would be non-tracking though hence risks going stale fast. Maybe thats' okay though.

**Comment by agocke** [comment]
This is now much better with Build Analysis
