### ISSUE TITLE
Test hang in derivatives of ConnectedStreamConformanceTests.ReadWrite_Success_Large

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#44219]
Multiple variants of `ReadWrite_Success_Large` seem to hang for:
- System.IO.Pipes: 
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44202-merge-48cab5614cff412b89/System.IO.Pipes.Tests/console.12bb341d.log?sv=2019-07-07&se=2020-11-24T10%3A28%3A57Z&sr=c&sp=rl&sig=G%2Fo9RFSCGrqX1QrTQjJ5w64H8JalPjohEl4SFcsUfbk%3D
- System.Net.Security: 
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44202-merge-48cab5614cff412b89/System.Net.Security.Tests/console.f64a4d19.log?sv=2019-07-07&se=2020-11-24T10%3A28%3A57Z&sr=c&sp=rl&sig=G%2Fo9RFSCGrqX1QrTQjJ5w64H8JalPjohEl4SFcsUfbk%3D
- `NetworkStream`:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44202-merge-705cd6d200ad41959c/System.Net.Sockets.Tests/console.e0769fa2.log?sv=2019-07-07&se=2020-11-23T18%3A40%3A33Z&sr=c&sp=rl&sig=SsVgIB%2BAl%2FU7inuCHZ2Vg%2BdFUiIuc3CCshSHcPBmfOw%3D
- System.IO.Compression:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-44202-merge-03a19939df064ce390/System.IO.Compression.Brotli.Tests/console.7851c28b.log?sv=2019-07-07&se=2020-11-24T10%3A29%3A00Z&sr=c&sp=rl&sig=L4fSJGOfBHi7WXpVeQfiOlf5k49k4JDOkUwaEfnS3DI%3D

Hits in #44202:

- https://dev.azure.com/dnceng/public/_build/results?buildId=874418&view=ms.vss-test-web.build-test-results-tab
- https://dev.azure.com/dnceng/public/_build/results?buildId=875289&view=ms.vss-test-web.build-test-results-tab

/cc @stephentoub (might be related to #44069?)

**Comment by stephentoub** [comment]
Closing as I expect this is fixed by https://github.com/dotnet/runtime/pull/44204.  Please re-open if it occurs again with changes that include that commit.
