### ISSUE TITLE
[Perf] Widespread regressions after threadpool change

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#44211]
After https://github.com/dotnet/runtime/pull/43841, we are seeing widespread (about 40 tests) regress. Some of these are threading tests, but some seem to have little to do with threading, like https://github.com/DrewScoggins/performance-2/issues/3177. Below I have a link to a query that is all of the regressions and a few improvements that are linked to this change. We are seeing this across Windows x64, x86 and Ubuntu x64, and I will be updating this issue as we get the Windows x86, and Ubuntu x64 regressions categorized.

[Regression Query - Windows x64](https://github.com/DrewScoggins/performance-2/issues?q=is%3Aopen+is%3Aissue+label%3A%22Windows+10.0.18362%22+label%3Arefs%2Fheads%2Fmaster+label%3ARegression+sort%3Aupdated-desc+label%3Ax64+label%3A%22Needs+Transfer%22+label%3A%22ThreadPool+Change%22)

[Improvement Query - Windows x64](https://github.com/DrewScoggins/performance-2/issues?q=is%3Aopen+is%3Aissue+label%3A%22Windows+10.0.18362%22+label%3Arefs%2Fheads%2Fmaster+label%3AImprovement+sort%3Aupdated-desc+label%3Ax64+label%3A%22Needs+Transfer%22+label%3A%22ThreadPool+Change%22+)

**Comment by kunalspathak** [comment]
cc: @kouvel , @mangod9

**Comment by mangod9** [comment]
Kount will take a look, this possibly might require to update the baselines since a startup hit might be causing some increase in per iteration times?

**Comment by kunalspathak** [comment]
> Kount will take a look, this possibly might require to update the baselines since a startup hit might be causing some increase in per iteration times?

@adamsitnik

**Comment by AndyAyersMS** [comment]
BDN tests should generally be pretty well-insulated from startup effects. We also considered that the change might impact BDN itself, but that seems unlikely.

As Drew noted, a number of the regressions are in tests that don't seem to have anything to do with threading; this is quite puzzling. We also see instructions retired increases, so these regressions don't seem to be code alignment artifacts. Could be data alignment, but the regressions have been pretty stable. So it seems to suggest there must have been some path length changes in code that's not exclusively threading related.

**Comment by kouvel** [comment]
Part of the problem appears to be slower stack walking on the thread pool thread when performing a GC. Even though most of these tests don't use the thread pool, tiered compilation currently uses the thread pool to do its background work, and thread pool thread when waiting for work would have managed frames with GC refs. I could switch tiering to not use the thread pool, I was thinking about that anyway as it would give more control to choosing much CPU time to use in a stretch for rejits just using sleeps and without adding contention to the thread pool queues.

**Comment by mangod9** [comment]
would it be possible to validate that theory of "stackwalking on the threadpool thread" causing the regression, but disabling the portable threadpool via config?

**Comment by kouvel** [comment]
Yes it's been verified like that on a few cases, and it looks like that would be the cause for most if not all of the tests, I just haven't verified it on all of them yet, that's pending

**Comment by kouvel** [comment]
Although verifying like that would not tell whether it's the same issue for all of the tests. Would need profiles for each test.

**Comment by mangod9** [comment]
yeah validating against a few tests is fine, all are not required. We can create a tracking item to switch tiering to not use the TP. In the interim is there a way to rebase the tests to the new "baseline" -- @DrewScoggins ?

**Comment by DrewScoggins** [comment]
I am not sure exactly what you mean. We can take the PR and run it through the perf lab and generate a report to see if we are seeing improvements across the tests that we saw regressions in before. Or we can just test it locally on a few tests then check it in and then generate reports from the lab to make sure we got everything back.

**Comment by mangod9** [comment]
I meant the fix would probably take some time to implement, so wondering if we can rebase the perf baseline, so it catches any further regressions which might happen on top on this.

**Comment by DrewScoggins** [comment]
Oh, I understand now. The system already does this. So if we see any further regressions in this test we would flag them as a regression and report them.

**Comment by sebastienros** [comment]
Just to add some data, most aspnet benchmarks are also down on windows with this change. Some also on linux but not as much.

![image](https://user-images.githubusercontent.com/1165805/101402722-fad67b00-3888-11eb-99cb-643bee573240.png)

**Comment by kouvel** [comment]
Filed a separate issue for the ASP.NET TE Windows perf issues, https://github.com/dotnet/runtime/issues/45716. I don't think it's the same cause as this one.

**Comment by kouvel** [comment]
The following seem to yield different results depending on JIT timing, may be due to other known issues like alignment of methods or loops, they're not related to https://github.com/dotnet/runtime/pull/43841. JIT timing can be fairly stable and following other changes it can change to different timing but still fairly stable, not considering them as regressions for now.
- https://github.com/DrewScoggins/performance-2/issues/3190 - [Perf -19%] System.Threading.Tasks.Tests.Perf_AsyncMethods (2)
- https://github.com/DrewScoggins/performance-2/issues/3194 - [Perf -6%] System.Collections.Concurrent.Count<Int32>.Queue_EnqueueCountDequeue

Keeping this issue for the issue of slower stack walking mentioned above, filed a separate issue (https://github.com/dotnet/runtime/issues/45885) for a few regressions that aren't caused by the slower stack walking.
