### ISSUE TITLE
IsAssignableFrom not working

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [dotnet/runtime#44222]
### Description

Following the steps to create a plugin architecture as shown in the [MS Docs](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support) and is failing to compare the implemented interface from the loaded assembly using:
```cs
foreach( var type in assembly.GetTypes() )
{
  var found = typeof( ICommand ).IsAssignableFrom( type );
  // found should be true but is not!
}
```

Whereas this works (as you would expect):
```cs
var found = typeof( ICommand ).IsAssignableFrom( typeof( HelloCommand ) )
```

So does this:
```cs
var myFilter = new TypeFilter( (c, o) => c.ToString() == o.ToString() );
var interfaces = type.FindInterfaces( myFilter, typeof( ICommand ) );
if( interfaces.Length > 0 )
{
  // found
}
```

Please see attached solution for example:
[PluginsTest.zip](https://github.com/dotnet/runtime/files/5484023/PluginsTest.zip)

### Configuration

Dotnet: .net 5.0.100-rc.2.20479.15
OS: Windows 10 Pro
Configuration: Any CPU (running on x64 laptop)

### Regression?

This doesn't seem to work with .netcore3.1 or 3.0 either in either Visual Studio 2019 or 2019 Preview 6

**Comment by am11** [comment]
The issue is that `ICommand` is loaded as different type. See https://github.com/dotnet/docs/issues/15811.
In your attached project, apply this patch to get the expected result:

```diff
--- a/HelloPlugin/HelloPlugin.csproj
+++ b/HelloPlugin/HelloPlugin.csproj

  <ItemGroup>
-    <ProjectReference Include="..\PluginBase\PluginBase.csproj" />
+    <ProjectReference Include="..\PluginBase\PluginBase.csproj" Private="false" ExcludeAssets="runtime" />
  </ItemGroup>
```

**Comment by SamuelJohnsonMedia** [comment]
@am11 that does not work for me no matter what I try

**Comment by am11** [comment]
It needs clean folder: delete all `bin` and `obj` directories (or extract the zip attachment in new place, apply the patch and build+run).

**Comment by SamuelJohnsonMedia** [comment]
Yes I have done all that multiple times

**Comment by am11** [comment]
My steps on Windows 10 are:

* Download .NET 5 RTM zip file for Windows from https://github.com/dotnet/installer#installers-and-binaries, and extract at `C:\Temp\dotnet5\`.
* Download your zip file and apply the aforementioned patch, along with:
  ```diff
  --- Program.cs
  +++Program.cs
          // Load commands from plugins.
          string[] pluginPaths = new string[]
          {
  -            "C:/Projects/Tests/PluginsTest/HelloPlugin/bin/Debug/net5.0/HelloPlugin.dll"
  +           "PluginsTest/HelloPlugin/bin/Debug/net5.0/HelloPlugin.dll"
          };
  ```
* Execute these in sequence:
  ```sh
  # PowerShell
  $ \temp\dotnet5\dotnet build
  $ \temp\dotnet5\dotnet run PluginsTest.csproj
  ```

outputs:

```
Loading commands from: C:\Temp\PluginsTest\HelloPlugin\bin\Debug\net5.0\HelloPlugin.dll
-- .\PluginsTest.csproj --
No such command is known.
```

which is different than what it produces without the `HelloPlugin.csproj` patch:

```
Loading commands from: C:\Temp\PluginsTest\HelloPlugin\bin\Debug\net5.0\HelloPlugin.dll
System.ApplicationException: Can't find any type which implements ICommand in HelloPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from C:\Temp\PluginsTest\HelloPlugin\bin\Debug\net5.0\HelloPlugin.dll.
Available types: HelloPlugin.HelloCommand
   at PluginsTest.Program.CreateCommands(Assembly assembly)+MoveNext() in C:\Temp\PluginsTest\Program.cs:line 107
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PluginsTest.Program.Main(String[] args) in C:\Temp\PluginsTest\Program.cs:line 29
```

**Comment by SamuelJohnsonMedia** [comment]
That looks like it hasnt worked; it should have output the commands available in the PlugIn and not `No such command is known`

**Comment by am11** [comment]
So we can't blame IsAssignableFrom API for this?

```c#
      foreach( Type type in assembly.GetTypes() )
      {
        if( typeof( ICommand ).IsAssignableFrom( type ) )
        {
          var result = Activator.CreateInstance( type ) as ICommand;
          if( result != null )
          {
            count++;
            yield return result;
          }
        }
      }

      if( count == 0 )
      {
        string availableTypes = string.Join( ",", assembly.GetTypes().Select( t => t.FullName ) );
        throw new ApplicationException(
            $"Can't find any type which implements ICommand in {assembly} from {assembly.Location}.\n" +
            $"Available types: {availableTypes}" );
      }
```

IsAssignableFrom seems to be working as expected.

**Comment by SamuelJohnsonMedia** [comment]
I delete the whole project and re-downloaded, applied your patch and then ran it through VS 2019 Preview and it worked:
```
Loading commands from: C:\Projects\Tests\PluginsTest\HelloPlugin\bin\Debug\net5.0\HelloPlugin.dll
Commands:
hello    - Displays hello message.
```
Feels a bit flakey, but thanks ... now to try and get this working in my actual project

**Comment by am11** [comment]
The code is written in a way that it looks for command in first argument, we need to publish it first, as opposed to running with `dotnet-run` (which passes first argument as project path):

```sh
$ \temp\dotnet5\dotnet publish
$ \temp\dotnet5\dotnet bin\Debug\net5.0\PluginsTest.dll hello
Loading commands from: C:\Temp\PluginsTest\HelloPlugin\bin\Debug\net5.0\HelloPlugin.dll
-- hello --
Hello !!!
```

**Comment by vitek-karas** [comment]
`dotnet run` doesn't take the project as a parameter on its own, instead it's an option, so `dotnet run Project.csproj` will treat `Project.csproj` as the first command line parameter for the app. If you want to specify the project to run that's done via `dotnet -p Project.csproj` in which case there will be no command line parameters passed to app. And so `dotnet run -p Project.csproj hello` will pass `hello` as the only command line parameter to the app.

**Comment by SamuelJohnsonMedia** [comment]
I think this can be closed now; thanks for everyones input and help.
