### ISSUE TITLE
IServiceProvider is disposed when it's used in transient class constructor

### ISSUE THREAD

**Issue by jasondaicoder** [dotnet/runtime#44233]
### IServiceProvider is disposed when it's used in transient class constructor

We have application which has tasks running at backend using IHostedService, some services are registered using Transient scope. We inject IServiceProvider into those Transient services via constructor to access some dependencies for some reason. However we have seen issues about "Cannot access a disposed object. Object name: 'IServiceProvider'.". It looks like someone else has reported this issue, so not sure if we have this tracked already.

https://github.com/dotnet/aspnetcore/issues/3076#issuecomment-469318552

### Configuration

.net core 3.1
macos

**Comment by davidfowl** [comment]
We need a repro of the issue you're experiencing

**Comment by safern** [comment]
GIven that we didn't get a repro I'm going to close this issue. Please feel free to re-open if you can provide any guidance on how to repro/investigate the issue.
