### ISSUE TITLE
CoreCLR missing resources needed for managed debugging on Windows

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#44232]
Looks like we dropped the `RCDATA` resource from coreclr.dll when we moved to using ninja as the build in #41897. This breaks managed debugging and minidump generation.

**Comment by hoyosjs** [comment]
@mikem8361 @dotnet/dotnet-diag

**Comment by RussKie** [comment]
Looks like it went out in https://github.com/dotnet/runtime build 20201102.4.

**Comment by hoyosjs** [comment]
Yeah, and it's a bit... involved. I narrowed it down to an issue in a script generated by cmake.
