### ISSUE TITLE
Is SSL Maximum Fragment Length Negotiation(RFC-6066) supported?

### ISSUE THREAD

**Issue by TailyFair** [dotnet/runtime#44241]
Hello,

I need to write TCP server with TLS for IoT devices. Devices cannot use default Maximum Fragment Length of 16kB, so Maximum Fragment Length Negotiation(RFC-6066) support is required.

https://tools.ietf.org/html/rfc6066#page-8
or 
RFC-8449 (Record Size Limit) https://tools.ietf.org/html/rfc8449

I fail to find if dotnet implementation of TLS supports this. Could anyone clarify if any of these 2 RFCs are supported?

**Comment by wfurt** [comment]
The SslSttream depends on OS implementation - Schannel and OPenSSL. There is no API to control it from .NET. 
In practise, I think you can do smaller writes and that will lead to smaller TLS frames.

**Comment by TailyFair** [comment]
Thank you for your answer! Could you please confirm that I understood this correctly?

So if I understand correctly, on windows SChannel will be used which according to wiki does not support MFLN and it won't ever be able.
On linux OpenSSL will be used. I currently plan to host on Ubuntu 16.04 which uses OpenSSL 1.0.2 (which does not support RFC6066). So all I need to do is to install newer OpenSSL 1.1.1 when MFLN was introduced and dotnet core application will use that implementation?

In current expermentation, smaller writes do not change the behavior and Fragment size eventually reaches 16kb. Writing 1kb packets stream will reach 16kb at some point. As I understand 1 TLS record can contain multiple TCP packets.

**Comment by wfurt** [comment]
yes, if 1.1.(1?) is available, it will be preferred. Note that 16.04 is close to end of support. Do you have some simple repro app?

**Comment by TailyFair** [comment]
Thank you for super fast response!
Currently I don't, I could provide example app tomorrow. 
We plan to use DotNetty https://github.com/Azure/DotNetty for our TCP server.

**Comment by wfurt** [comment]
I'm not familiar with that package @TailyFair.  I'm going to close it this as the question as answered.
