### ISSUE TITLE
Question: Why some of very common class or struct in .NET violates general naming conventions?

### ISSUE THREAD

**Issue by RamType0** [dotnet/runtime#44240]
[In Microsoft Docs](https://docs.microsoft.com/ja-jp/dotnet/standard/design-guidelines/general-naming-conventions), it is written that
> ❌ DO NOT use abbreviations or contractions as part of identifier names.
For example, use GetWindow rather than GetWin.

But some of very common class or struct in .NET violates this.
For example,
- `Int32` rather than `Integer32` or `Interger32Bit`
- `IntPtr` rather than `IntPointer` or `IntegerPointer`
- `Func<T>` rather than `Function<T>`

Why was that?

**Comment by gfoidl** [comment]
I can't speak about the history, but naming also has to consider readability (amont others).

`Int32` is easier to read than `Integer32Bit` and it's clear what is meant. Same for the other examples you've given.
`GetWin` on the other side depends on the context. In a game _Win_ could mean the amount of money, etc. you earn, or it could mean _Windows_. So to avoid this ambiguity don't use the abbreviated form.

**Comment by wfurt** [comment]
perhaps one of  @terrajobst @GrabYourPitchforks @jkotas @bartonjs can comment on.

**Comment by jkotas** [comment]
The design guidelines are evolving over time. Number of the older designs violate the design guidelines as they are written today, but they did not violate the guidelines when the design was created originally, and it was too late to change it once the design guideline was put in place.
