### ISSUE TITLE
Using /p:PublishTrimmed=true with ASP.NET core 3.1 and .net5 will cause SSL resolution issues in Windows

### ISSUE THREAD

**Issue by plooploops** [dotnet/runtime#44260]
When using the parameter /p:PublishTrimmed=true, it looks like dependencies that help with loading x509 certificates are not included.  Perhaps if there's additional detail on how to re-include these bits when using the /p:PublishTrimmed=true could be helpful (in this doc: https://docs.microsoft.com/en-us/dotnet/core/deploying/trim-self-contained).

This parameter works with Linux: https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile.alpine-x64-slim#L13.  We are able to build the sample, mount an openssl certificate, then ping the container in a browser.  Please see some of the additional notes from here: https://github.com/dotnet/AspNetCore.Docs/pull/20200/files

Similarly, we can get this to work in Windows, but only if we set /p:PublishTrimmed=false or we do not include the parameter.

However, this does not work, and has been tested with .aspnetcore 3.1 and .net5 if we try to use /p:PublishTrimmed=true on Windows.

If we try to build the Dockerfile from here: https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/Dockerfile.nanoserver-x64-slim#L13 and similarly mount an openssl certificate (.pfx w/password) and ping the container in a browser, this will **not work** with loading the certificate.

![image](https://user-images.githubusercontent.com/2498998/96512018-bc232d80-1214-11eb-99d4-dc51502ac92f.png)

This has also been tested with .net5: https://github.com/dotnet/dotnet-docker/blob/51fc85ec57e6c03167daa178355a262ac7786a86/samples/aspnetapp/Dockerfile.nanoserver-x64-slim and is also **not working.** with the same openssl certificate mounted w/password.

![image](https://user-images.githubusercontent.com/2498998/96512168-f1c81680-1214-11eb-96e0-872df77aa2a0.png)

**Comment by dsplaisted** [comment]
@jeffschwMSFT @agocke @swaroop-sridhar Is this an issue with trimming, or the default assemblies that are trimmed?

**Comment by plooploops** [comment]
@dsplaisted heads up, PR was merged for the docs: https://github.com/dotnet/docs/pull/21262.

**Comment by vitek-karas** [comment]
In .NET 6 this should either work or produce warnings. We've made lot of work to make the core framework warning free, but ASP.NET has not been part of that effort yet. So trimming ASP.NET apps is currently effectively unsupported.
