### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#44280]
Our internal Red Hat arm64 CI machine occasionally shows failures for this test:
```
     Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload [FAIL]
  [m[31;1m[m[37m      Assert.Equal() Failure
  [m[37m      Expected: Hello ASP.NET Core: a69df373c63847b29dbace68c5aee194
  [m[37m      Actual:   (null)
  [m[30;1m      Stack Trace:
  [m[37m        /root/runtime/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(206,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload()
```

Looking at what the test does, I guess multiple notifications may be triggered when the config file changes. Maybe at the first notification, the updated config file hasn't been completely written yet.

cc @omajid @RheaAyase

**Comment by maryamariyan** [comment]
Related to https://github.com/dotnet/runtime/issues/48696

Closing this one as dupe
