### ISSUE TITLE
dotnet-runtime-perf legs are running and failing on every PR

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44297]
e.g.
![image](https://user-images.githubusercontent.com/2642209/98251818-378c1b00-1f47-11eb-9bf1-16260737fc5f.png)
https://github.com/dotnet/runtime/pull/44282

cc: @ViktorHofer, @DrewScoggins

**Comment by am11** [comment]
I think it was unintentional https://github.com/dotnet/runtime/pull/44224#discussion_r517807946.
