### ISSUE TITLE
ValidationAttribute.SetResourceAccessorByPropertyLookup should throw better exception

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#44292]
Converting TODO-NULLABLE into the issue here since I'm not familiar with the area I'll leave it for area owner to decide if they want to close it or leave it. I'll remove the original comment in case it's decided this should be closed.

In ValidationAttribute.SetResourceAccessorByPropertyLookup (last line):

```csharp
_errorMessageResourceAccessor = () => (string)property.GetValue(null, null)!;
```

Is commented as `If the user-provided resource returns null, an ArgumentNullException is thrown - should probably throw a better exception`

**Comment by ajcvickers** [comment]
@roji Can you take a quick look at this along with the other nullable cleanup?

**Comment by roji** [comment]
This basically means that if the user sets up the validation attribute to point at a resource accessor, and the property returns null, attempts to format an error message will fail with ArgumentNullException. This is incorrect/unsupported usage by the user, so barring changing the exception to be slightly more informative I don't think there's anything to do.
