### ISSUE TITLE
Fix the link of api-review-process.md in CONTRIBUTING.md

### ISSUE THREAD

**Issue by LeaFrock** [dotnet/runtime#443]
![image](https://user-images.githubusercontent.com/20787265/69979532-6d6f9500-1569-11ea-9400-c48e8b558a9e.png)

**API Review Process** should be linked to `https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md` 
instead of  
`https://github.com/dotnet/runtime/blob/master/docs/project-docs/api-review-process.md`.

Now it shows a 404 page after clicking the link in CONTRIBUTING.md

**Comment by ViktorHofer** [comment]
Would you mind submitting a PR which fixes this? Thanks. cc @maryamariyan
