### ISSUE TITLE
A better way marshall structs multiple times

### ISSUE THREAD

**Issue by zabulus** [dotnet/runtime#4431]
For now reading structs from native memory works via `Marshal.PtrToStructure(intPtr, structType)`. AFAIU each call creates field offset map to know which memory bytes to copy to a new struct instance. If this code is called frequently, it becomes one of the hot paths in an application.
One of workarounds is to manually read field values from nativePtr via UnmanagedMemoryStream+BinaryReader or directly via pointer and field pre-evaluated offset.
A much better solution would be to create specialized struct marshaller that calculates field offset map, only once and creates instances and copies bytes from memory in its method. 
Something like this 

``` C#
var marshaller = Marshal.CreateStructureMarshaller(structType);
// somewhere in cycle for example
var struct = marshaller.PtrToStructure(intPtr);
```

**Comment by AaronRobinsonMSFT** [comment]
Closing as the suggestion is how we current implement marshalers. Additionally, the [source generators](https://github.com/dotnet/runtime/blob/master/docs/design/features/source-generator-pinvokes.md) proposal would allow further user defined optimizations.
