### ISSUE TITLE
Epic: Make sure .NET libraries are continuously improved

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#44314]
### Summary

We'll use this epic to collect bottom-up improvements coming from the engineering team.

### Dev features/work:

- [ ] #43849
- [x] #43957
- [x] #40359
- [x] #45318
- [x] #20004
- [x] #46850
- [x] ~#46849~
- [x] #45456
- [x] #42852
- [x] #47231
- [x] #47525
- [x] #51605
- [x] #36391
- [x] #36022
- [x] #27062

### These issues were not completed in .NET 6

- [ ] #44517
- [ ] #44512
- [ ] #44969
- [ ] #21362
- [ ] #44327
- [ ] #44655
- [ ] #44513
- [ ] #43544

**Comment by danmosemsft** [comment]
We'll be adding more proposed stories to the list above.

**Comment by GSPP** [comment]
I'll use this opportunity to bring these "grassroots" issues to attention:

* Add Enumerable.*By operators (DistinctBy, ExceptBy, IntersectBy, UnionBy, MinBy, MaxBy) https://github.com/dotnet/runtime/issues/27687
* Add common helper methods to the String class (Contains(StringComparison), Replace(StringComparison), Left, Truncate, TrimPrefix) #14831 
* New API: String.Truncate(int maxLength, string truncationSuffix) #31655

Some of these would inspire joy and love in the community.

**Comment by hez2010** [comment]
What about APIs in `System.Linq.Expressions`? They were still aligned to C# 3 and have been quite out-of-date today.

**Comment by jeffhandley** [comment]
#57209 was filed for items that will carry over to .NET 7.
