### ISSUE TITLE
Installer "Download artifacts for all platforms" step fails because of throttling

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44320]
Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=871527&view=logs&j=04b1677b-aa91-548a-e789-89c3d998d0f7&t=3a83d448-e04e-525a-dd07-7a2e77dd6fed

We know about this and we believe that with @jkoritzinsky's new shared framework SDK this will go away.

**Comment by MattGal** [comment]
@ViktorHofer can you provide more examples?  The linked build did indeed seem to report 2+ hours in Download Artifacts for all platforms, but that's because the MacOS agent machine died after that stage started and it took that long for AzDO to notice it.
