### ISSUE TITLE
System.Text.Json.JsonException with double quoted values

### ISSUE THREAD

**Issue by mmaderic** [dotnet/runtime#44325]
Hello,

Please consider writing this code, where we would like to de-serialize quoted values into dictionary. 
Second value contains double quoted value string.

`var dictionary = JsonSerializer.Deserialize<Dictionary<string, string>>("{\"first\":\"some_value\",\"second\":\"some \"value\"\"}");`

This will throw an exception:
`System.Text.Json.JsonException: ''v' is invalid after a value. Expected either ',', '}', or ']'. Path: $.second | LineNumber: 0 | BytePositionInLine: 38.'`

**Comment by layomia** [comment]
The JSON spec ([RFC 7159](https://tools.ietf.org/html/rfc7159#section-7)) allows quotation marks within JSON strings, but they must be properly escaped (`U+0022`). `JsonSerializer` and other types in `System.Text.Json` strictly respect this spec by default, and custom options to allow uenscaped quotation marks in JSON strings is not on the roadmap for System.Text.Json.

When deserializing (parsing with the underlying `Utf8JsonReader`) quotes found within strings are treated as the ending quotation mark, which causes an issue when parsing subsequent characters in the payload.

For your scenario, your input payload should be of the form:

`string json = @"{""first"":""some_value"",""second"":""some \u0022value\u0022""}";`

FWIW Newtonsoft.Json fails in the same way given your test case above: https://dotnetfiddle.net/0waPfi.
