### ISSUE TITLE
User Story: Developers need more flexibility for globalization settings to fulfil  their needs on the web

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44321]
# Description

TBA

# Tracking Items
- [x] Improve invariant mode to be more complete #43774
- [x] Experiment with icu4x usage for wasm #47875
- [ ] Reduce native ICU dependency by slicing or porting the necessary logic
- [ ] TimeZone information can be updated with apps re-deployment

**Comment by safern** [comment]
@tarekgh I would expect this to apply to Android/iOS/tvOS as well... should we change `arch-wasm` to another label?

**Comment by tarekgh** [comment]
I am ok either way with more proper labeling. I just marked the best I understood from the description.

**Comment by marek-safar** [comment]
@safern yes but I haven't decided if I'll just link here from different Epic
