### ISSUE TITLE
SMR DecodeSignature methods should have nullable ref on second parameter

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#44328]
The DecodeSignature method (here and perhaps on other classes) behave just fine with a null argument for the second parameter:

https://github.com/dotnet/runtime/blob/ae47aa26544227ef632598d91a798b8f83d56634/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/TypeSystem/MethodDefinition.cs#L66

There should be a `?` nullable ref annotation on this.

**Comment by MCCshreyas** [comment]
You mean `TGenericContext` should be `TGenericContext? ` and putting method under #nullable context?

**Comment by AArnott** [comment]
Yes. Except I think it already is under a nullable context because the C# compiler was telling me it's an error to pass null in. If there were no nullable context, the compiler wouldn't have told me that.

**Comment by MCCshreyas** [comment]
Ok. I will get that annotated and will open a PR!

**Comment by stephentoub** [comment]
> There should be a ? nullable ref annotation on this.

Why? If someone wants to pass null,  they should be using a nullable TGenericContext, no?

**Comment by AArnott** [comment]
Ah yes, that makes sense.
I just tested it in my caller of this API and it works fine. Please disregard.
