### ISSUE TITLE
Frequent reallocation of 128byte array in `Rune.cs`

### ISSUE THREAD

**Issue by jlennox** [dotnet/runtime#44338]
### Description

This was not noticed in a profiler or in program performance, but noticed while reading the code.

https://github.com/dotnet/runtime/blob/177d6f1a0bfdc853ae9ffeef4be99ff984c4f5dd/src/libraries/System.Private.CoreLib/src/System/Text/Rune.cs#L38-L48

I'm not sure if this was instead intended to be an `=` and not a `=>`? If not, would a `Lazy<Byte[]>` perhaps be better suited?

My main concern would be methods like `IsLetterOrDigit` and `IsWhiteSpace` are very likely to be called inside a loop over a large input set, for example, a source file, where you could call multiples of those methods on each byte of the file, resulting in a lot of redundant allocations.

A bit of a side note, since these are in the ASCII range, I wonder if this table shouldn't instead be generated using `char.IsWhiteSpace`, etc?

**Comment by jkotas** [comment]
This pattern does not allocate. C# compiler compiles this into returning a singleton read-only memory block.

We are using this pattern in many places.

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/ describes this in a bit more detail.

**Comment by jlennox** [comment]
Ah thank you! That's awesome.
