### ISSUE TITLE
Publish a single file app does not create a single file

### ISSUE THREAD

**Issue by JoeMarkov** [dotnet/runtime#44337]
**Version Used**: 
C:\Temp\HelloConsole>dotnet --version
5.0.100-rc.2.20479.15

**Steps to Reproduce**:

1. Creating a new dotnet console application  
2. Publish it as a single file using

dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true
or 
dotnet publish -r win10-x64 /p:PublishSingleFile=true

3. then I get these files created:

11/04/2020  02:54 PM    <DIR>          .
11/04/2020  02:54 PM    <DIR>          ..
09/25/2020  10:47 PM           747,912 clrcompression.dll
09/25/2020  10:46 PM         1,324,416 clrjit.dll
09/25/2020  10:47 PM         5,154,696 coreclr.dll
11/04/2020  02:54 PM        53,289,026 HelloConsole.exe
11/04/2020  02:50 PM             9,352 HelloConsole.pdb
09/25/2020  10:46 PM         1,042,792 mscordaccore.dll

**Expected Behavior**:

I would expect to only get one file.

**Actual Behavior**:

I get many files. So bit confused here....  Why I don't get a single file?. I get the same result when I publish from inside visual Studio as well.

**Comment by vitek-karas** [comment]
For .NET 5 this is the expected behavior - see the detailed design here: https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#user-experience

We're working on improving this for future releases - most of the work to get to one file even on Windows is tracked here: https://github.com/dotnet/runtime/issues/43071

**Comment by steveoh** [comment]
> As such, some extra files have to be included for native runtime components unless you specify `--self-contained false`.

Isn't this the default?

**Comment by vitek-karas** [comment]
@steveoh Unfortunately the behavior of dotnet CLI is a bit weird:
* If there's no `RuntimeIdentifier` specified (so the app is built as portable), then `--self-contained` is defaulted to `false`.
* It `RuntimeIdentifier` is specified (which is a requirement for single-file), then `--self-contained` is defaulted to `true`.

**Comment by agocke** [comment]
As of .NET 6 Preview 1, both Windows and Mac should now compile all the runtime binaries into a single-file, and publishing should produce a true single-file app.

Any native dependencies that the app itself brings in can be bundled and extracted using `IncludeNativeBinariesForSelfExtract`
