### ISSUE TITLE
JsonSerializer support for multi-dimensional arrays

### ISSUE THREAD

**Issue by CBrauer** [dotnet/runtime#44347]
I am getting an error in JasonSerializer.

I'm trying to convert my Windows Desktop App to .NET 5.0.  My old code to serialize  some data was declared deprecated.
My attempt to convert this code to a .NET 5.0 version gives me a runtime error;

My Visual Studio screen at run time is:
![image](https://user-images.githubusercontent.com/1317234/97608365-7c580500-19cf-11eb-843f-b012702ccebe.png)

I hope you can read  this screen capture..
Please tell me what I'm doing wrong.
Any help will be greatly appreciaed.
Charles

**Comment by mairaw** [comment]
@maryamariyan the not didn’t seem to run here. Not sure what do.

**Comment by huoyaoyuan** [comment]
As the exception message says, multi-dim array(`long[,]`) is not supported. You should either write a json converter for it (`JsonConverter<long[,]>`), or change the data to jagged array (`long[][]`).

**Comment by layomia** [comment]
> As the exception message says, multi-dim array(long[,]) is not supported. You should either write a json converter for it (JsonConverter<long[,]>), or change the data to jagged array (long[][]).

+1

See https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0 for guidance on how to write custom converters. Please let us know if you're successful with either of these workarounds.

This is not a regression from .NET 3.1, so will triage as future.

**Comment by CBrauer** [comment]
Thanks huoyaoyuan, your suggestion worked.   All the rest of the suggestions were a great disappointment to me.
Please close the issue.
