### ISSUE TITLE
Setting Console.Title in Hosted Windows Service Crashes App

### ISSUE THREAD

**Issue by alwilton** [dotnet/runtime#44348]
On a windows hosted app (running as a service) I have the following Program.cs code

```
public static void Main(string[] args)
        {
            // the following line throws an error when running as a service.
            //Console.Title = @"AppServices";

            Serilog.Debugging.SelfLog.Enable(Console.Out);
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", true, true)
                .Build();

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            Log.Debug("Logger Installed.");

            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Host terminated unexpectedly");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }
```
If I uncomment the Console.Title line the service will not start showing an application event error of 
`The process was terminated due to an unhandled exception. Exception Info: System.IO.IOException: The handle is invalid. at System.ConsolePal.set_Title(String value) at System.Console.set_Title(String value)`

As long as the line is commented the service runs without an issue.

Running this as a console app there is no issue either way.

**Comment by MCCshreyas** [comment]
Hi @alwilton,
In your csproj file in `<PropertyGroup>` tag, change `<OutputType>Exe</OutputType>`  to `<OutputType>WinExe</OutputType>`. 
Please let me know the outcome.

**Comment by alwilton** [comment]
I do not have a OutputType element in the csproj file. This is a .NET Core 3.1 Worker project. Here is what I have at the top of the csproj

```
<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>dotnet-AppServices-EBED377E-....</UserSecretsId>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
    <FileVersion>1.0.2.0</FileVersion>
    <Version>1.0.2</Version>
  </PropertyGroup>

  <ItemGroup>
    ...


```

**Comment by MCCshreyas** [comment]
Try putting Console.Title statement in try block after CreateHostBuilder statement!

**Comment by alwilton** [comment]
that hangs the program as well.

**Comment by danmosemsft** [comment]
@alwilton what behavior are you expecting? There is no console when you are running as a service.

**Comment by alwilton** [comment]
Yes, that is true. There is no console running as a service. However a very nice feature of the .NET Core Worker Application is you can run the very same EXE as a console program and that is were this problem lies. If you leave the line in of Console.Title = @"AppServices"; it will run as a console application just as expected. however that same EXE will not run as a service application. Taking that line out the EXE will run just fine as a console or a service application. I would expect that when running as a service application that line would be ignored, the same as writing to the console is ignored. That way I have the option to run the program either way. That is an option which I find very useful.

**Comment by danmosemsft** [comment]
There will always be some API that behave differently in a service or do not work. I don’t think we want to special case them so they appear to work. The IOException is telling you that it didn’t work: I would just catch it.

**Comment by eiriktsarpalis** [comment]
You could try guarding any calls to System.Console with a check to the [Environment.UserInteractive](https://docs.microsoft.com/en-us/dotnet/api/system.environment.userinteractive?redirectedfrom=MSDN&view=netcore-3.1#System_Environment_UserInteractive) property. It should return false for service contexts.

I don't think we should change the current behaviour of Console.Title, as that would probably be a breaking change.

**Comment by alwilton** [comment]
For both your comments - Fair enough.
