### ISSUE TITLE
dotnet ignores http proxy set via mono nuget.exe and can't build solution with mono nuget.exe

### ISSUE THREAD

**Issue by kobelobster** [dotnet/runtime#44346]
### Description

Okay, this will be a loooooooooooong description, because this is such a special use case (it seems)

I currently am building a pipeline on GitLab for our .NET projects which should

* Build the project
* Run the unit tests
* Deploy the image (Later...)

We also have a custom NuGet feed hosted at a SonaType Nexus instance on premise. All our services are behind a proxy and use a self-signed certificate.

So, basically, the steps we have to do in the pipeline are the following

* Create a pipeline, based on `mcr.microsoft.com/dotnet/core/sdk:3.1`
* Set the proxy environment variables
* Install the custom certificate
* Add & enable our custom NuGet feed sources
* Restore all packages
* Build the solution
* Run the unit tests

Since we will have many C# projects that will all have the same "issue" that they are using packages on a custom nuget feed, behind a proxy with a self signed certificate, my first action was to create a "base image" which

* Set the proxy environment variables
* Install the custom certificate

So this is the code I came up with

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Will be populated by CLI
ARG NUGET_USER_PASSWORD
ARG proxy

# SETTING PROXY
ENV http_proxy=${proxy}
ENV https_proxy=${proxy}
ENV HTTP_PROXY=${proxy}
ENV HTTPS_PROXY=${proxy}

# INSTALL DEPS & CERTS
RUN apt-get update && apt-get -yqq install ca-certificates mono-complete
RUN mkdir -p /usr/local/share/ca-certificates/cert.com
COPY .docker/cert.com.crt /usr/local/share/ca-certificates/cert.com/
RUN update-ca-certificates --fresh

# Install nuget
RUN wget -q https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
RUN mv nuget.exe /usr/local/bin/nuget.exe
```

You might already be wondering why I'm using `mono nuget.exe` and not `dotnet`. This is because there is NO way to set an http_proxy with `dotnet`, but only with the `nuget.exe` which requires `mono` because we are on Linux (because of the base image)

So then, the next step is to add & enable our custom NuGet feed sources

```
RUN mono /usr/local/bin/nuget.exe config -set http_proxy="${proxy}"
RUN mono /usr/local/bin/nuget.exe sources Add -Source "https://sonatype-nexus.ourdomain.com/repository/digital-de-ng-releases/" -Name "Digital DE Repository" -UserName "digital-de-nuget" -Password $NUGET_USER_PASSWORD -StorePasswordInClearText
RUN mono /usr/local/bin/nuget.exe sources Add -Source "https://sonatype-nexus.ourdomain.com/repository/nuget.org-proxy/" -Name "NuGet Proxy"
RUN mono /usr/local/bin/nuget.exe sources Enable -Name "Digital De Repository"
RUN mono /usr/local/bin/nuget.exe sources Enable -Name "NuGet Proxy"
```

------

So now, the base image is set. 

Now, I build another project, which is a "common" library which's purpose is to provide C# functionality used across many projects (such as specific interfaces, that can be used in multiple projects) and this project should also be deployed automatically to our custom feed, so I have this

```
## Image definitions
image: registry.ourdomain.com/cms/previouslycreatedimage:1.0.2

[...code].
  script:
    - dotnet pack -p:PackageVersion=${VERSION}
    - mono /usr/local/bin/nuget.exe push Common/bin/Debug/Common.${VERSION}.nupkg -Source https://sonatype-nexus.ourdomain.com/repository/digital-de-ng-releases
```

This works without any problems. The package is pushed to our custom nuget feed. In my **NEXT AND THIRD** project, I now want to use this COMMON package, which, on a local machine also works. But as soon as I push it to GitLab, where a new pipeline runs, it fails when tryting to restore the packages. 

* When I use `dotnet restore --configfile {configfileFromMono)`, it fails with an SSL exception, as if it wouldn't be using any http_proxy settings. To fix this, I tried...
  * Adding `- export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` and `- export SSL_CERT_DIR=/dev/null` -> No success
  * I also tried `DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0` -> No success

I also used `cat ~/.config/NuGet/NuGet.Config` and can see my `http_proxy` properly configured in there, so it is configured correctly. But anyway, since I was using `mono` for all my other commands, I thought, it makes sense to use `mono` in here as well, so I changed `dotnet restore` to `mono /usr/local/bin/nuget.exe restore`

but this is the output

```
 MSBuild auto-detection: using msbuild version '' from '/usr/bin'.
>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
MSBUILD: error MSBUILD0004: Too many project files specified
```
Because my project has a `Project.csproj` and a `Tests.csproj`. 

So what I would like to know is:

* Why does the `dotnet` command not accept the certificates whereas `mono` does it without problems?
* Why does the `dotnet` command appear not to use the proxy settings whereas `mono` does it without problems?
* Why can't the `nuget.exe` restore a solution with multiple projects whereas `dotnet` can without any problems?
* Why is there no possibility to tell `nuget.exe` to restore a solution for a specific project, so I could restore each project individually?

Tbh, I'm starting to lose my mind. Using the dotnet cli for gitlab images on linux is a pain. Only half of the staff works, everything needs workarounds. It's super tiring. It leads to wanting to use different languages. I thought Microsoft is all about open source and cross platform, however, the dotnet command (which is supposed to be cross platform) just doesn't work as a good replacement on Linux and it FORCES one to use mono as well....  I know, that this is a special case, but having a company proxy, self-signed certificates, custom nuget feed and wanting to use gitlab can't be a setup only used by me?

**Comment by huoyaoyuan** [comment]
Looks like that `dotnet` command doesn't invoke `nuget.exe`. For example, https://github.com/dotnet/sdk/blob/master/src/Cli/dotnet/NuGetForwardingApp.cs

**Comment by kobelobster** [comment]
@huoyaoyuan Which shouldn't be a problem, should it? I'm using `dotnet` on linux so it doesn't know about a `nuget.exe`. I'm using the `nuget.exe` only in combinatin with `mono`. And when both tools write into the same config, the `http_proxy` is ignored by `dotnet`, but I can't use `nuget.exe` to restore the solution, because of multiple projects.

**Comment by huoyaoyuan** [comment]
I have no experience about proxy on Linux. Just guessing the behavior.
Here may not be the correct repo of this issue. NuGet related tools are in dotnet/sdk and NuGet/Home.

**Comment by kobelobster** [comment]
@huoyaoyuan I can open an issue in `NuGet/Home` as well, however, right now I'm using the `dotnet` command which isn't working and which is why I opened the issue in here. I could open an issue in `NuGet/Home` stating that I can't use `nuget.exe` to build a solution with multiple projects.

I created another ticket in here: https://github.com/NuGet/Home/issues/10242

**Comment by huoyaoyuan** [comment]
> right now I'm using the `dotnet` command which isn't working and which is why I opened the issue in here.

The `dotnet` command lives in dotnet/sdk repo.

**Comment by kobelobster** [comment]
@huoyaoyuan - Alright. I'm opening an issue in there and will close this issue in here since it's out of scope.

**Comment by kobelobster** [comment]
The issues are now

* https://github.com/dotnet/sdk/issues/14456
* https://github.com/NuGet/Home/issues/10243
