### ISSUE TITLE
Inconsistent range check behavior of List<T>.LastIndexOf

### ISSUE THREAD

**Issue by sglienke** [dotnet/runtime#44353]
### Description

LastIndexOf has a different behavior about its range checking than IndexOf has.
See the following code:

```
var list = new List<int>();

// index out of bound by 1 but count = 0
list.IndexOf(42, 0, 0);     // -> no exception
list.LastIndexOf(42, 0, 0); // -> no exception

// index out of bound by 1 and count = 1
list.IndexOf(42, 0, 1);     // -> exception
list.LastIndexOf(42, 0, 1); // -> no exception, unexpected (1)

// index out of bound by 2 but count = 0
list.IndexOf(42, 1, 0);     // -> exception
list.LastIndexOf(42, 1, 0); // -> no exception, unexpected (2)

list.Add(42);

// index out of bound by 1 but count = 0
list.IndexOf(42, 0, 0);     // -> no exception
list.LastIndexOf(42, 0, 0); // -> no exception

// index out of bound by 1 but count = 0 
list.IndexOf(42, 1, 0);     // -> no exception
list.LastIndexOf(42, 1, 0); // -> exception, unexpected (3)
```

The range checking in IndexOf follows the principle index + count <= listsize which means index can be = size when count is 0.
LastIndexOf has two defects imo:
(1) and (2) are not raised because there is an "list is empty" check before the exception would be raised
(3) is raised because it does not allow index = listsize when count is 0

### Configuration

.NET 5

**Comment by eiriktsarpalis** [comment]
I think it's because [this check](https://github.com/dotnet/runtime/blob/03701ba6d2656c1fb52848744980c7b799aabccf/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L818) is incorrect. For example you have the following behaviour:
```csharp
var list = new List<int>(42, 42);

list.IndexOf(42, 0, 2); // succeeds with 0
list.LastIndexOf(42, 0, 2); // should succeed with 1, throws `System.ArgumentOutOfRangeException: Larger than collection size. (Parameter 'count')`
```
Really I think we could simplify the validation logic of this method by copying the behaviour found in [`IndexOf`](https://github.com/dotnet/runtime/blob/03701ba6d2656c1fb52848744980c7b799aabccf/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L651-L655).

**Comment by sglienke** [comment]
@eiriktsarpalis The exception in your code is indeed correct - the index being passed is the index it starts to search backwards, and starting at index 0 with a count of 2 is invalid.

**Comment by eiriktsarpalis** [comment]
You're right, I suppose I misunderstood the contract of LastIndexOf. I think we should ensure uniform behaviour in bounds checking for the two methods.

**Comment by jkotas** [comment]
The bounds checks in some of the IndexOf/LastIndexOf methods are more relaxed than what one would expect for backward compatibility. `string.LastIndexOf` has some of the same problems. Changing these corner cases to throw instead would be a breaking change. (IIRC, we have done fix like that in the past in one of these method and it was reverted.)

**Comment by eiriktsarpalis** [comment]
Thanks for the context @jkotas. If that's the case I'm going to close this.
