### ISSUE TITLE
Question: Mismatching type for variable when inside expression tree

### ISSUE THREAD

**Issue by smitpatel** [dotnet/runtime#44368]
Repro code
```C#
var flags = Enum.GetValues(typeof(DayOfWeek)).Cast<int>();

var a = new List<int>().AsQueryable().Select(e => flags);
Console.WriteLine((((a.Expression as MethodCallExpression)?.Arguments[1] as UnaryExpression)?.Operand as LambdaExpression)?.Body.Type);
Console.WriteLine(flags.GetType());
```
prints
```
System.Collections.Generic.IEnumerable`1[System.Int32]
System.DayOfWeek[]
```
Variable in intellisense shows `IEnumerable<int>` too.

**Comment by huoyaoyuan** [comment]
**You may have misunderstanding about types.**

Expression type and IntelliSense gives **variable type**, where `GetType()` gives **object type**.
https://github.com/dotnet/runtime/blob/6cfef20c1524b8d4c1495a652dfe9e898c5a486b/src/libraries/System.Linq/src/System/Linq/Cast.cs#L38-L40

`Cast` has a shortcut to return the original object if it fits. **Never rely on the returned implementation type from Linq**. If you do want a collection with given type, please append a `ToArray()` call.

**Comment by cston** [comment]
As @huoyaoyuan indicated, `Enumerable.Cast<TResult>()` returns the original argument if the argument can be used as `IEnumerable<TResult>` directly.

**Comment by cston** [comment]
Closing as resolved.
