### ISSUE TITLE
JIT: Optimize simple MUL/DIV arithmetic with GT_NEG

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#44375]
This is part 2 of #13837 to optimize multiplication and division arithmetic optimizations with GT_NEG.
Addition and subtraction have been completed in PR https://github.com/dotnet/runtime/pull/43921.

```csharp
int M5(int a) =>  -a / 10;  // optimize to  "a / -10"
int M6(int a) => -(a / 10); // optimize to  "a / -10"
int M7(int a) =>  -a * 10;  // optimize to  "a * -10"
int M8(int a) => -(a * 10); // optimize to  "a * -10"
```

category:cq
theme:basic-cq
skill-level:beginner
cost:small

**Comment by EgorBo** [comment]
A small note: `10` -> `-10` should not be done for IconHandle constant, see https://github.com/dotnet/runtime/pull/44266

**Comment by alexcovington** [comment]
@JulieLeeMSFT This seems like a good introductory issue to get familiar with the JIT, which I've been looking for. Would you be able to assign this to me?

**Comment by danmosemsft** [comment]
@alexcovington is this issue now completed? If so we can close it. 

perhaps there's another issue that's interesting among our codegen issues up for grabs: https://github.com/dotnet/runtime/issues?q=is%3Aopen+label%3Aup-for-grabs+label%3Aarea-CodeGen-coreclr+

**Comment by alexcovington** [comment]
@danmosemsft Yes, I believe this can be closed now that #45604 has been merged in.

And I'll gladly take a look through 😄. Feel free to ping me for AMD-specific or x64 issues (I saw the [amd-perf label](https://github.com/dotnet/runtime/labels/amd-perf) which I'm following).

**Comment by danmosemsft** [comment]
@alexcovington great, we would be excited to have more of your contributions in .NET 6.0. 
cc @BruceForstall in case he has specific interesting suggestions.

**Comment by JulieLeeMSFT** [comment]
@alexcovington thanks a lot for your contribution to JIT.
cc @sandreenko for any suggestions for alexcovington.
