### ISSUE TITLE
net5.0 TargetFramework issues with NuGet packages

### ISSUE THREAD

**Issue by akraines** [dotnet/runtime#44387]
![image](https://user-images.githubusercontent.com/15201927/98466604-3c67fd80-21d9-11eb-9788-ad8087689eb7.png)

"Install failed (project: DCMS, package: PCSModels v1.0.2)
                Package restore failed. Rolling back package changes for 'DCMS'.
                Package PCSModels 1.0.2 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package PCSModels 1.0.2 supports: net50 (.NETFramework,Version=v5.0)"

I get this error when trying to reference a nuget package I built with TargetFramework net5.0. We tried changing all the references to netcoreapp5.0 and it still didn't work. What is the correct moniker?
https://docs.microsoft.com/en-us/nuget/reference/target-frameworks doesn't mention either of the monikers, yet the documentation refers to it as net5.0 and the code should have worked with net5.0 without issues when used as per https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/#net-50-target-framework

**Comment by MCCshreyas** [comment]
What framework target that your project uses on which you are trying to install the package? Make sure your package target framework is like this `<TargetFramework>net5.0</TargetFramework>

**Comment by akraines** [comment]
Yes it was. I llooks like it was an issue with Rider 2020.2 - We downloaded 2020.3 EAP and it worked.

**Comment by MCCshreyas** [comment]
@akraines, Ohh that's great!

**Comment by MCCshreyas** [comment]
@akraines, Ohh that's great! 

You can consider closing this issue!
