### ISSUE TITLE
Codepage improvement for System.Text.Encoding.CodePages

### ISSUE THREAD

**Issue by GreenYun** [dotnet/runtime#44401]
### Description

For old Mac OS encodings, such as "x-mac-japanese", of range 0x0080~0x00FF should be mapped to Unicode characters as same as encoding "macintosh". This is just a practical usage as the old Macs will fallback to "Roman" (codepage name "macintosh") when the character not found in the current encoding.

### Configuration

* Which version of .NET is the code running on?
  .NET core 3.2, .NET 5.0

* What OS and version, and what distro if applicable?
  Windows 10

* What is the architecture (x64, x86, ARM, ARM64)?
  x64

* Do you know whether it is specific to that configuration?
  No.

* If you're using Blazor, which web browser(s) do you see this issue in?
 I'm not using Blazor.

### Other information

Test byte stream: (in hex)
`A9 20 A5 78 A5 5F`
Test encoding:
`x-mac-chinesetrad`
Expected Unicode string:
`© 台北`

Possible workarounds:
1. Do changes on data file `codepages.nlp; or
2. Write some codes for fallback encoding.

**Comment by tarekgh** [comment]
@GreenYun usually we don't change the encoding mapping for any encoding for app compatibility reason. You still have the option to create your own encoding using https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingprovider?view=netcore-3.1
