### ISSUE TITLE
Uri.GetLeftPart splits even for "#", should it not split just for "?" to get the left path away from query parameters

### ISSUE THREAD

**Issue by santhoshbomma9** [dotnet/runtime#44429]
### Description
Uri.GetLeftPart(UriPartial.Path)
Uri.GetLeftPart splits even for "#", should it not split just for "?" to get the path away from query parameters

https://github.com/microsoft/referencesource/blob/e56279724ddb2715ab3c18c47ecd3b78eb90d3c7/System/net/System/URI.cs#L1416

**Comment by wfurt** [comment]
cc: @MihaZupan

**Comment by MihaZupan** [comment]
Given a Uri like `https://host/path?foo=bar#fragment`, the `Path` compoenent is just `/path`.
For a Uri without a query, like `https://host/path#fragment`, the `Path` is still `/path`, not including the fragment.

`uri.GetLeftPart(UriPartial.Path)` is described as `The scheme, authority, and path segments of the URI.`
I believe the behavior here is correct, you will NOT get the fragment, regardless of the presence of a query string.

If you want to preserve the fragment and only remove the query, you can always append the fragment manually
`uri.GetLeftPart(UriPartial.Path) + uri.Fragment`.

For more fine-grained control, you can take a look at the `Uri.GetComponents` API.
