### ISSUE TITLE
User Story: Source generators are created to support native AOT

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#44430]
Source Generators are a new technology that was added to Roslyn in the .NET 5 timeframe, but we have not yet utilized them by creating generators to assist with runtime and framework features. We will work to define customer scenarios in more detail here with customer development.

Code that uses runtime reflection and reflection.emit causes issues for Native AOT. Source generators can be used to generate alternative code at build time that is static so can be compiled without requiring reflection. 

  - [ ] System.Text.Json serialization – code generators can work around the need for runtime reflection, and generate serializers for specific classes.
  - [ ] EventSource – event source uses reflection.emit to simplify creation of classes (manifests) for custom event sources – this can be changed to a build-time activity using source generators.

**Comment by samsp-msft** [comment]
Refactored from #43545

**Comment by samsp-msft** [comment]
Removing as there are applicable issues already for each of these that I have converted to epics.

**Comment by noon2a** [comment]
> Source Generators are a new technology that was added to Roslyn in the .NET 5 timeframe, but we have not yet utilized them by creating generators to assist with runtime and framework features. We will work to define customer scenarios in more detail here with customer development.
> 
> Code that uses runtime reflection and reflection.emit causes issues for Native AOT. Source generators can be used to generate alternative code at build time that is static so can be compiled without requiring reflection.
> 
> * [ ]  System.Text.Json serialization – code generators can work around the need for runtime reflection, and generate serializers for specific classes.
> * [ ]  EventSource – event source uses reflection.emit to simplify creation of classes (manifests) for custom event sources – this can be changed to a build-time activity using source generators.

**Comment by noon2a** [comment]
.
