### ISSUE TITLE
Test failure: System.IO.Pipes.Tests.AnonymousPipeTest_ServerIn_ClientOut.ReadWrite_Success_Large(mode: SyncArray, writeSize: 10485760, startWithFlush: False)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44448]
failed in job: [runtime-libraries-coreclr outerloop 20201109.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=879404&view=ms.vss-test-web.build-test-results-tab&runId=28133236&resultId=103367&paneView=debug)

net6.0-Linux-Release-x64-CoreCLR_release-Centos.7.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: Byte[] [23, 26, 249, 61, 213, ...]
Actual:   Byte[] [23, 26, 249, 61, 213, ...]


Stack trace
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 1763
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success_Large(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 1717
--- End of stack trace from previous location ---
~~~

**Comment by Jozkee** [comment]
cc @stephentoub, tried to repro this locally but the test is still running... any clue why this failed for the specified config?

**Comment by carlossanlop** [comment]
@Jozkee and I searched using Kusto for hits of this issue in the last 100 days and there is only one hit of this failure for this unit test:



JobId | Source | Type | Method | Result | WorkItemFriendlyName | Class
-- | -- | -- | -- | -- | -- | --
12074182 | ci/public/dotnet/runtime/refs/heads/master | test/functional/cli/outerloop/ | ReadWrite_Success_Large | Fail | System.IO.Pipes.Tests | System.IO.Pipes.Tests.AnonymousPipeTest_ServerIn_ClientOut
