### ISSUE TITLE
Remove allocation of thread abort exceptions and startup

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#44442]
As long as thread aborts is not a common scenario, we could save some allocations at start up by removing these:

https://github.com/dotnet/runtime/blob/1c1757c040e1735f8e608bc383bb73b3f5f98a38/src/coreclr/src/vm/appdomain.cpp#L1221-L1232

**Comment by VSadov** [comment]
cc: @stephentoub, @jkotas

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/runtime/pull/46455

**Comment by stephentoub** [comment]
Thanks.
