### ISSUE TITLE
I suggest a uniform name for c and .net. Easy for SEO, just like Java. 

### ISSUE THREAD

**Issue by maikebing** [dotnet/runtime#44463]
Now people have begun to use search engines, but also refer to some well-known sites recommended things. 
 Programming languages, too.
The tiobe website has influenced a lot of people!
https://www.tiobe.com/tiobe-index/ 

For example, java keywords are used to search for anything about it. 

But DotNET is different from Java,  people will search for C#  or .Net or VB.Net, or .Net Core !

There are many more languages, such as python, php, go!They all benefit from SEO!
This is a bold idea, if not practical, then please close.

**Comment by GrabYourPitchforks** [comment]
@richlander Seems like this might be up your alley? Does this belong in the core repo instead of the runtime repo?

**Comment by danmosemsft** [comment]
Thanks for the suggestion, but we're not going to change the names of C# or .NET. cc @mairaw for the SEO suggestion.

**Comment by mairaw** [comment]
Tagging our SEO expert @v-mepa but @danmosemsft is right, we won't change their names.

**Comment by v-mepa** [comment]
Nope will not recommend changing names at all.
