### ISSUE TITLE
Breaking change in ResourceSet class

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#44483]
This PR https://github.com/dotnet/runtime/pull/44104 introduces a breaking change that is only experienced at runtime.
`ResourceSet` implements `IEnumerable` and ASP.NET Core is using the contract.

At least there, but other tests break so it might not be isolated.
https://github.com/dotnet/aspnetcore/blob/master/src/Localization/Localization/src/Internal/ResourceManagerStringProvider.cs#L75

While we could react to this change, it doesn't seem that this change of behavior was intentional.

**Comment by jkotas** [comment]
Revert in https://github.com/dotnet/runtime/pull/44482

**Comment by marek-safar** [comment]
@sebastienros what is the failure?

**Comment by sebastienros** [comment]
I left all the details on the PR. To summarize `ResourceSet` implements `IEnumerable` but the returned elements are not of the same type. They were `DictionaryEntry` and now they are `KeyValuePair<>`.

**Comment by tarekgh** [comment]
@marek-safar here is @sebastienros comment regarding the failure https://github.com/dotnet/runtime/pull/44104#issuecomment-724926282

**Comment by marek-safar** [comment]
I see you are casting object to underlying type. That needs to be fixed on runtime side.

**Comment by tarekgh** [comment]
@marek-safar just to make sure you saw @jkotas PR reverting your change which broke this scenario https://github.com/dotnet/runtime/pull/44482

**Comment by marek-safar** [comment]
Yep, let's revert this to unblock them. I'll fix that in follow up PR (revert)
