### ISSUE TITLE
Question: What is our policy regarding API support of unaligned spans?

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#44497]
__Scenario:__ Let's say that somebody creates a `Span<T>` where the addresses are not properly aligned for type _T_. As far as I'm aware this can only be done via unsafe code (`new Span<T>(<unaligned ptr>)`) or unsafe-equivalent code (`MemoryMarshal.Cast` or `MemoryMarshal.CreateSpan(<ref to unaligned field>)`.

__Question:__ What guarantees should our in-box APIs make when such spans are provided as input?

For example, `MemoryExtensions.IndexOf` [contains special-cased logic](https://github.com/dotnet/runtime/blob/5f96636b63bea718bcfa1355e17cb36693ff8bca/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Char.cs#L221) to handle unaligned `ReadOnlySpan<char>` on all platforms, but it doesn't contain special logic for things like unaligned `ReadOnlySpan<float>`. Depending on the current architecture, such accesses could fault.

As another example, `UTF8Encoding.GetBytes(ReadOnlySpan<char>)` assumes that the input is always _char_-aligned, and it could fault or return nonsensical answers if given unaligned input, even on x86 processors.

Is our default stance that _all_ APIs which accept `Span<T>`, `ref T`, and similar should guard against misaligned addresses? Or that consumers must assume that misaligned spans do not work unless they API they're calling has been documented as allowing these?

**Comment by jkotas** [comment]
> MemoryExtensions.IndexOf contains special-cased logic to handle unaligned ReadOnlySpan<char>

IIRC, this was done to allow IndexOf to be repurposed as `wcslen`. APIs that take zero-terminated strings always handled misaligned pointers gracefully and we had tests that failed without it.

> consumers must assume that misaligned spans do not work unless they API they're calling has been documented as allowing these

Correct, pointers are assumed to be aligned according to the platform rules.

As usual, we may find that code out there depends on undocumented behaviors that we treat case-by-case.

**Comment by GrabYourPitchforks** [comment]
Thank you for the response. :)
If I see any other questions regarding this I'll redirect them to this thread.
