### ISSUE TITLE
Calling IPGlobalProperties.GetIPGlobalProperties().GetActiveUdpListeners() on Linux throws an System.OverflowException

### ISSUE THREAD

**Issue by Nickjgniklu** [dotnet/runtime#44500]
### Description
Calling IPGlobalProperties.GetIPGlobalProperties().GetActiveUdpListeners() on Ubuntu 18.04 WSL throws an System.OverflowException.

To reproduce this error.
1. Install Ubuntu 18.04 on windows using Windows Subsystem for Linux (WSL). 
2. Install Dotnet 3.1 by following the instructions for Ubuntu 18.04 at [https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu]( https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu) 
3. Clone the example bug repo `git clone https://github.com/Nickjgniklu/DotnetUdpListnerBugRepo.git` 
4. open the directory that example was cloned to and run it via `dotnet run` 

If you do not want to clone the program from https://github.com/Nickjgniklu/DotnetUdpListnerBugRepo.git here is a small example.
 ```
using System;
using System.Net.NetworkInformation;
using System.Net.Sockets;
namespace dotnetBug
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Will Call GetActiveUdpListeners()");
            try{
            var listeners =IPGlobalProperties.GetIPGlobalProperties().GetActiveUdpListeners();
            }catch (Exception e){
                Console.WriteLine("Failed while calling GetActiveUdpListeners()");
                Console.WriteLine(e);
                throw e;
            }

        }
    }
}
```
This is the output I am getting from the above script.
```
Will Call GetActiveUdpListeners()
Failed while calling GetActiveUdpListeners()
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveUdpListenersFromFiles(String udp4File, String udp6File)
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveUdpListeners()
   at dotnetBug.Program.Main(String[] args) in /home/nick/dotnetBug/Program.cs:line 12
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at dotnetBug.Program.Main(String[] args) in /home/nick/dotnetBug/Program.cs:line 16
```

### Configuration
dotnet version 3.1.402
Ubuntu 18.04 running on windows via WSL
Architecture x64
I am not sure if this is a WSL Ubuntu specific problem or if it affects more Linux configurations. 

### Regression?

Unsure

### Other information

I think the problem may be in this parsing function
[https://github.com/dotnet/runtime/blob/f6dc87f43df543bdc761ded7c578ecedc5b39668/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L32](https://github.com/dotnet/runtime/blob/f6dc87f43df543bdc761ded7c578ecedc5b39668/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L32)

**Comment by jkotas** [comment]
@wfurt

**Comment by wfurt** [comment]
I assume WSL means legacy v1, right @Nickjgniklu? (e.g. NOT WSL2) 
We have seen some odd behavior in the past as the kernel entries are not quite the same. 
Can you please post content of `/proc/net/udp` from your system?

**Comment by Nickjgniklu** [comment]
@wfurt I have confirmed that I am using WSL 1 based on the fact that my windows version is below 16299 [https://askubuntu.com/questions/1177729/wsl-am-i-running-version-1-or-version-2](https://askubuntu.com/questions/1177729/wsl-am-i-running-version-1-or-version-2).  `/proc/net/udp` exists but is empty. All the files in `/proc/net/` are empty. Is this a WSL 1 issue?

**Comment by wfurt** [comment]
perhaps. But I would think .NET should not throw and it should handle it more gracefully.
