### ISSUE TITLE
System.Linq.Except doesn't work correctly with source collection with duplicate elements.

### ISSUE THREAD

**Issue by mirasrael** [dotnet/runtime#44516]
I checked implementation and it seems it doesn't properly handles cases when input collection contains duplicate elements.
This test fails:
```csharp
namespace ConsoleApp1
{
    using System.Linq;
    using NUnit.Framework;

    public class ExceptTest
    {
        [Test]
        public void TestExcept()
        {
            var a = new[] { 'a', 'a', 'b', 'c' };
            Assert.That(a.Except(new[] { 'b' }), Is.EquivalentTo(new[] { 'a', 'a', 'c' }));
        }
    }
}
```

It happens because of ExceptIterator implementation:
```csharp
private static IEnumerable<TSource> ExceptIterator<TSource>(IEnumerable<TSource> first, IEnumerable<TSource> second, IEqualityComparer<TSource> comparer)
        {
            Set<TSource> set = new Set<TSource>(comparer);
            set.UnionWith(second);

            foreach (TSource element in first)
            {
                if (set.Add(element)) // <==============
                {
                    yield return element;
                }
            }
        }
```
It seems like it should be `!Contains` instead. It also uses extra memory for added source collection elements which seems unnecessary and ineffective especially when first collection is long.

**Comment by kevingosse** [comment]
That's actually by design: https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except?view=net-5.0

> The set difference of two sets is defined as the members of the first set that don't appear in the second set.
> This method returns those elements in first that don't appear in second. It doesn't return those elements in second that don't appear in first. **Only unique elements are returned.**

**Comment by mirasrael** [comment]
Ah, missed this. But this seems confusing. You didn't expect from enumerable to behave as Set. But closing issue, because it is by design...

**Comment by Clockwork-Muse** [comment]
@mirasrael - That's because the operations `Union`, `Intersect`, and `Except` are from the domain known as "set mathematics".  `IEnumerable` is somewhat irrelevant.
