### ISSUE TITLE
Trim out more System.Threading classes in Blazor sample

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#44528]
WebAssembly does not have proper threading, and so classes like ThreadPool are always single-threaded and offer no benefit. They appear to be used in libraries and are present even in the linked Corelib, but it should be possible to get them linked out and save some space. These classes hold a surprising amount of code, including things like `GCMemoryInfo` that aren't even in System.Threading.

**Comment by danmosemsft** [comment]
This might assume we don't do anything for https://github.com/dotnet/runtime/issues/43411

**Comment by CoffeeFlux** [comment]
cc: @eerhardt

**Comment by SamMonoRT** [comment]
@joperezr - is this work still planned for .NET6 ? If so, it would be ideal to get this in no later than Preview 7 cutoff

**Comment by ilonatommy** [comment]
@lambdageek, do you think this work is still valid when threading will become an optional feature?
