### ISSUE TITLE
Path.GetInvalidPathChars() doesn't include angle brackets

### ISSUE THREAD

**Issue by NiJeTi** [dotnet/runtime#44520]
As provided [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) paths in Windows cannot contain angle brackets (**<** and **>**).

But method `GetInvalidPathChars()` in `Path` class which returns array of prohibited characters, does not contain angle brackets.

![image](https://user-images.githubusercontent.com/5685857/98747108-e73e0e80-23c7-11eb-8c2e-03da8f87f929.png)

Also there is an [example](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars?view=net-5.0#examples) of using this method in the Microsoft Docs where angle brackets are also stated as invalid.

![image](https://user-images.githubusercontent.com/5685857/98747603-e3f75280-23c8-11eb-9434-4f6c586455f1.png)

I propose to change it to something like this:
![image](https://user-images.githubusercontent.com/5685857/98747728-2c167500-23c9-11eb-94bf-da0fd743c943.png)

**Comment by vcsjones** [comment]
`<` and `>` look like they were intentionally removed from GetInvalidPathChars here: https://github.com/dotnet/corefx/pull/8669 since they are valid wildcard characters.

**Comment by NiJeTi** [comment]
OK, thanks. Documentation confused me. The problem resolved.
