### ISSUE TITLE
Infrastructure - Rollout (December 2020)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44524]
# Overview

We use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the **first Monday of the month (12/7)**.

| Change |  Impact | Assignee |
| --- | --- | --- |
|  #44523 | Update the minimum and target version of the SDK to 5.0.100. | @ViktorHofer |
|  #44973 | Remove the nested 'src' folder from the CoreCLR part of the repository. | @trylek |
## Archive
- [November 2020](https://github.com/dotnet/runtime/issues/43351)
- [September 2020](https://github.com/dotnet/runtime/issues/39788)
- [July 2020](https://github.com/dotnet/runtime/issues/37706)
- [June 2020](https://github.com/dotnet/runtime/issues/35895)
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by danmosemsft** [comment]
I wonder if it might be useful to have a column for "why"? In this case, it's so that we are using the supported, GA SDK.

**Comment by ViktorHofer** [comment]
IMO the why should be part of the PRs description and this table should only list the changes but not go into too much detail. Otherwise the table will always lack behind the PRs details.

**Comment by marek-safar** [comment]
Why update to 5.0.100 and not 6.0 to start preparing for January preview?

**Comment by ViktorHofer** [comment]
> Why update to 5.0.100 and not 6.0 to start preparing for January preview?

5.0.100 is stable and we don't depend on any 6.0 features yet.

**Comment by ViktorHofer** [comment]
The rollout is completed.

**Comment by ViktorHofer** [comment]
We completed the rollout. Please read further.

As the intermediate “src” folder in src/coreclr/src/* was removed by the second change, PRs need to be updated to account for the conflicts. I posted a comment (via Octokit) in every PR with an explanation and instructions how to update the conflicting commits via a script. Here’s an example of the auto-generated comment: https://github.com/dotnet/runtime/pull/43360#issuecomment-740666865. In case your curious, please find the attached log file that lists the 64 PRs that need to be updated.

As controversial as the change might sound, this was a work item planned as part of the repository consolidation which unfortunately couldn’t be completed because of lack of time and differences in the source tree (e.g. runtime tests were still part of that src folder). We wanted to deliver this change to model the coreclr subtree more closely to the rest of the repository.

GitHub unfortunately fails to show history for moved files but a) there are Browser Extensions that enable that and b) “git log –follow” can be used locally. We faced a similar issue when we renamed the “mscorlib” folder to “System.Private.CoreLib” in the past but we believe that the benefit of the simplified repository tree is worth the churn long-term.

Please don’t hesitate to reach out to me in case you have questions about the change, the script or anything else.
