### ISSUE TITLE
Trimming Http in Blazor wasm

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#44534]
System.Net.Http is one of the largest libraries in the Blazor sample, taking up 53KB when compressed with Brotli. Most of this space is held in the headers, most of which are not likely to be used. We should investigate some sort of feature flag here to try and get rid of this even if the linker cannot guarantee it will be unused.

The size grew also when http2 and http3 support was added for SocketHttpHandler which is not used and excluded for Browser and still the various caches and static data are populated.

**Comment by stephentoub** [comment]
The vast majority of that code is around header validation, e.g. when you set HttpRequestHeaders.From on a message, it validating that it's a well-formed email address.  I think the flag here will basically need to be "I don't care about header validation at the HttpClient layer", at which point I'd expect a significant portion of the header logic could be trimmable away.

Alternatively, we could simply say that for the Blazor wasm build we don't layer on much special validation, and simply have a different implementation that effectively ifdefs away all of that code.  More specifically, much of it ends up being kept because of the parsers defined in the known headers here:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs
We would tweak that for the wasm build to just always use a generic parser, or something like that.

cc: @geoffkizer

**Comment by eerhardt** [comment]
@geoffkizer @wfurt @scalablecory @dotnet/ncl - anyone have any thoughts on the above? Would either of these approaches be acceptable in `browser-wasm` (and potentially mobile) builds?

**Comment by geoffkizer** [comment]
We can't rip out the header parsers/validators in general without removing strongly typed header properties as well, which I assume we don't want to do....

Is there a way to see details on what methods account for what space, etc?

**Comment by eerhardt** [comment]
> Is there a way to see details on what methods account for what space, etc?

You can use the following steps to trim a default Blazor WASM app:

1. Get the [latest 6.0 SDK](https://github.com/dotnet/installer#installers-and-binaries) and put it on your $PATH
2. Create a `HelloWorld` directory and `cd` into it
3. `dotnet new blazorwasm`
4. `dotnet publish -c Release`
5. Inspect the .dlls in `HelloWorld\bin\Release\net6.0\publish\wwwroot\_framework`. You'll see the `System.Net.Http.dll` is the 3rd largest after CoreLib and System.Text.Json. Currently around 136 KB. Typically I use ILSpy or similar to inspect what is left in the assembly.

When I do this, here is what is left:

![image](https://user-images.githubusercontent.com/8291187/113781897-fd41c800-96f6-11eb-8deb-8c19a0d976a5.png)

Analyze these classes and decide whether each is completely necessary in a `browser-wasm` app.

**Comment by geoffkizer** [comment]
The HPACK and QPACK stuff is HTTP2/3 specific and could be removed, though I expect there's some trickiness with the KnownHeaders stuff that makes this a bit painful.

I don't know what TaskToApm is used for; we could investigate this but I doubt it's much code.

As for the rest, I don't see much that can be removed, unfortunately.

**Comment by stephentoub** [comment]
> We can't rip out the header parsers/validators in general without removing strongly typed header properties as well, which I assume we don't want to do...

I was thinking we could consider weakening the validation. For example,  there's a ton of code purely to validate that From headers are properly formatted as email addresses.  Do we need all of that for wasm?

**Comment by geoffkizer** [comment]
> I was thinking we could consider weakening the validation. For example, there's a ton of code purely to validate that From headers are properly formatted as email addresses. Do we need all of that for wasm?

Maybe not.

To what extent do we care about behavioral differences here?

Alternatively, to what extent do we really care about validation of From headers even in non-wasm scenarios?

**Comment by stephentoub** [comment]
> Alternatively, to what extent do we really care about validation of From headers even in non-wasm scenarios?

Personally? Very little :wink:

Just for context, changing:
https://github.com/dotnet/runtime/blob/6578f257e3be2e2144a65769706e981961f0130c/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L50
to pass null as the parser, and deleting this line:
https://github.com/dotnet/runtime/blob/6578f257e3be2e2144a65769706e981961f0130c/src/libraries/System.Net.Http/src/System/Net/Http/Headers/GenericHeaderParser.cs#L21
shrinks the size of System.Net.Http.dll in the default blazor wasm template by 7K uncompressed and 2K compressed.

**Comment by eerhardt** [comment]
I opened #52572 for @stephentoub's proposal above, in case anyone is interested in taking a look.

After that idea and #52420, I'm not seeing much more than can be trimmed from `System.Net.Http`, unfortunately.

**Comment by eerhardt** [comment]
After #52420, #52681, and #52794, I believe all the trimmable code has been removed from System.Net.Http. Closing.
