### ISSUE TITLE
Browser compat: FileStream.Unix.cs referencing not supported API

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#44542]
`FlushWriteBufferForWriteByte()`, `FillReadBufferForReadByte()` methods of FileStream.Unix.cs referencing API not supported on browser

Please create an issue for this and link it from here. We have to fix it as the code does not work as-is

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#r521220506_

**Comment by adamsitnik** [comment]
In the new and default strategy for `FileStream` introduced in #55191 we don't use this API anymore, so I am going to close this issue.
