### ISSUE TITLE
Browser compat: Stream class using unsupported API

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#44543]
`BeginReadInternal(byte[] buffer, int offset, int count, AsyncCallback? callback, object? state, bool serializeAsynchronously, bool apm)` and `BeginWriteInternal(byte[] buffer, int offset, int count, AsyncCallback? callback, object? state, bool serializeAsynchronously, bool apm)` methods of Stream class are referencing `SemaphoreSlim.Wait()` not supported on browser

Please create an issue and link it, we have to block the API or fix it

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#r521222129_

**Comment by adamsitnik** [comment]
@marek-safar does it meet the 6.0 bar?
