### ISSUE TITLE
WebAssembly WebSockets multi-buffer sends don't work

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#44551]
Using 5.0 WebAssembly with WebSockets, multi part sends are not handled correctly.

Only the final send with `endOfMessage == true` is actually sent because the `writtenBuffer` variable is never used.
https://github.com/dotnet/runtime/blob/1923bba394c31bc2d4f62a948eac8dbe64339ab2/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/BrowserWebSockets/BrowserWebSocket.cs#L366

It would be nice to get this fixed for 5.0. I would have tried fixing it, but building WASM isn't super easy it seems.

@kjpou1 @marek-safar

**Comment by marek-safar** [comment]
Building should be as easy as typing in `./build.sh -os browser -arch wasm` in the root folder

**Comment by lewing** [comment]
This is unfortunate. The code gained extra buffering and broke functionally when it moved over from mono/mono

**Comment by BrennanConroy** [comment]
Fixed via https://github.com/dotnet/runtime/pull/44611
