### ISSUE TITLE
linker tests are currently broken on linux and osx

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#44559]
Running the linker tests on non-Windows platforms currently fails with:

```
/home/eerhardt/git/runtime/.dotnet/sdk/5.0.100-rc.2.20479.15/Microsoft.Common.CurrentVersion.targets(4814,5): error MSB3030: Could not copy the file "/home/eerhardt/git/runtime/artifacts/bin/trimmingTests/projects/Microsoft.Extensions.DependencyInjection.TrimmingTests/ActivatorUtilitiesTests/linux-x64/obj/Release/net6.0/linux-x64/apphost" because it was not found. [/home/eerhardt/git/runtime/artifacts/bin/trimmingTests/projects/Microsoft.Extensions.DependencyInjection.TrimmingTests/ActivatorUtilitiesTests/linux-x64/project.csproj]
```

The linker test project cannot be built because it can't find the `AppHostIntermediatePath` file. The file doesn't exist because it isn't being created by `_CreateAppHost`, since the `$(AppHostSourcePath)` property is empty.

Here is a binlog of the failure:

[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/5527116/msbuild.binlog.zip)

While investigating this break, it appears we have some incorrect code added into the linker targets files:

https://github.com/dotnet/runtime/blob/2db717954a3fd9ca5119143ccc633fef3dfa3bb8/eng/testing/linker/SupportFiles/Directory.Build.targets#L36-L53

This is incorrect because:

1. We need to be using the framework that we just built (i.e. what is in `artifacts`). These tests need to run on the current code changes, not what is in some pre-compiled version.
2. We shouldn't be hard-coding these versions into a random targets file. They need to be centralized, and kept up to date, if we do need them.

We should fix the linker-tests so they can be re-enabled in CI.

cc @joperezr @Anipik @ericstj

**Comment by ericstj** [comment]
@safern can you have a look at this?

**Comment by safern** [comment]
> @safern can you have a look at this?

Sure, I'll take a look.
