### ISSUE TITLE
JsonSerializer  string is null

### ISSUE THREAD

**Issue by zhanghm1** [dotnet/runtime#44575]
`    public class StringNullConverter : JsonConverter&lt;string&gt;
    {
        public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return reader.GetString();
        }

        public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value ?? "");// Do not enter when CodeIndex is null ? how should I do?
        }
    }
    internal class Program
    {
        private static void Main(string[] args)
        {
            var user = new UserDto()
            {
                Id = 1,
                Name = "xxxx",
                CodeIndex = null
            };

            var options = new JsonSerializerOptions();
            options.Converters.Add(new StringNullConverter());

            string json1 = JsonSerializer.Serialize(user, options);
            // I hope {"Id":1,"Name":"xxxx","CodeIndex":""}
            Console.WriteLine(json1);
        }
    }`
Do not enter when CodeIndex is null??? how should I do?

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/379003e0c1f9d3c059da0a411fc8766492c46431/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L76

You should override the `HandleNull` property of the `JsonConverter`.

**Comment by zhanghm1** [comment]
> https://github.com/dotnet/runtime/blob/379003e0c1f9d3c059da0a411fc8766492c46431/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L76
> 
> You should override the `HandleNull` property of the `JsonConverter`.

谢谢，我看到了这个是 .net 5 的属性， .net core 3.1可以怎么实现呢？

**Comment by huoyaoyuan** [comment]
3.1下可以手动安装5.0.0版本的nuget包

**Comment by layomia** [comment]
@zhanghm1 via Bing Translator, I understand that @huoyaoyuan suggested that you try the [System.Text.Json NuGet package](https://www.nuget.org/packages/System.Text.Json/5.0.0) so that you can use the `HandleNull` property on `JsonConverter<T>` to handle `null` values on serialization and deserialization. Please feel free to reopen this issue if there are still problems here.
