### ISSUE TITLE
Update MsQuic

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#44580]
The current System.Net.Quic is referencing https://github.com/microsoft/msquic/tree/dc2a6cf0dd12e273710843158b2f2e612360da0a (from July 2020). We need to update to the latest version of their API, which has mostly stabilized.

**Comment by huoyaoyuan** [comment]
Is it welcomed to update the interop to function pointers?

**Comment by scalablecory** [comment]
@huoyaoyuan this is already in progress; please avoid conflicting work!

**Comment by mclayton7** [comment]
Hi @scalablecory are you guys accepting any community contributions for System.Net.Quic? We're looking to use it for some experiments and would gladly help in any way we can.

**Comment by mclayton7** [comment]
@scalablecory  @jkotalik Since msquic has released the first officially supported version of [1.0.0](https://github.com/microsoft/msquic/releases/tag/v1.0.0-129524), would you guys accept any community PRs updating to 1.0.0?

**Comment by jkotalik** [comment]
@scalablecory @geoffkizer thoughts? I'd be fine with this, but want your confirmation.

**Comment by geoffkizer** [comment]
Community PRs are welcome, but please coordinate with @scalablecory to avoid duplication/conflicts/etc

**Comment by mclayton7** [comment]
Thanks @jkotalik and @geoffkizer! I've had some difficulties trying to get in contact with @scalablecory, do you guys have any ideas on how to coordinate with him?

**Comment by karelz** [comment]
@mclayton7 I will ping him ...

**Comment by scalablecory** [comment]
@mclayton7 I've already got this migration 90% done, but have had to jump on some other things before completing it. It just needs some bug fixes now.

Any interest in submitting a PR into my branch to help finish it? Otherwise, I expect I'll probably resume work on it in early February.

**Comment by mclayton7** [comment]
@scalablecory absolutely, where is your branch?

**Comment by ManickaP** [comment]
I'm taking over the task, I'll start with what @scalablecory has in https://github.com/scalablecory/runtime/tree/msquic-update.

**Comment by JamesNK** [comment]
Ping me once this is done. I'm going to improve ASP.NET Core's TLS integration - https://github.com/dotnet/aspnetcore/issues/30857 - and will wait until after msquic has been updated.
