### ISSUE TITLE
Integrate supports for ULID

### ISSUE THREAD

**Issue by juchom** [dotnet/runtime#44583]
Hi,

.Net core actually supports GUID for generating globally unique identifiers. This has some drawbacks because they are not index friendly.

I'm considering using ULID instead of GUID which seems to solve most of the issues GUID have.

Considering this specification: https://github.com/ulid/spec
And a .net implementation: https://github.com/RobThree/NUlid

Do you think that support for ULID be integrated in the framework, this would give a great signal that we can safely use it in the future?

**Comment by AaronRobinsonMSFT** [comment]
@juchom The use of Guids in .NET is almost entirely based on the historical relationship with COM. Within the runtime the use of these type Guids is minimal and the [`Type.GUID`](https://docs.microsoft.com/dotnet/api/system.type.guid) is an artifact of that history with COM. It is unlikely to be a desire on the runtime's part to integrate the ULID into .NET, but that doesn't mean it can't be driven by the community.

I would suggest converting this issue to be an "api-suggestion" and I can tag it appropriately.

**Comment by juchom** [comment]
Thanks for your reply, how do I convert this to an api-suggestion?

**Comment by Joe4evr** [comment]
Update your first post with a codeblock of what you think the API shape should look like (meaning only public members and no implementations). You can see an example of that done [here](https://github.com/dotnet/runtime/issues/41686#issuecomment-685061045).

**Comment by juchom** [comment]
After re-reading @AaronRobinsonMSFT answer, it doesn't make sense to have this in the runtime.

This kind of problem has to be tackle outside.
