### ISSUE TITLE
build failure: Failed to download or parse releases-index.json with error

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/runtime#44595]
The build fails on 
>Failed to download or parse releases-index.json with error: {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}

https://dev.azure.com/dnceng/internal/_build/results?buildId=883621&view=logs&j=4ed15cf7-56e9-525d-400c-02e7c9e4bdb5&t=2bad0049-a4da-5908-4276-ffad2dba9437

Perhaps it is network related issue, lets close it if it fot appear again

**Comment by aik-jahoda** [comment]
cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
@safern as asked offline, is it possible to retry that task if it failed in the yml?

**Comment by safern** [comment]
> @safern as asked offline, is it possible to retry that task if it failed in the yml?

I can't think of a way to do so other than running the task, don't fail it (there is a way to say don't fail or continue on error), then have a script that checks if the SDK is available and if not emit a variable, and then have the dotnet core task again after the script and condition it based on the variable to be true (which is emitted if the SDK is still missing) but that feels very cumbersome.

**Comment by ViktorHofer** [comment]
Unfortunately the build isn't accessible anymore and there's not enough data on what exactly failed. Hence closing.
