### ISSUE TITLE
Allow (de)serialization of abstract types with JsonSerializer when there is a JsonConverter for that type

### ISSUE THREAD

**Issue by LeroyK** [dotnet/runtime#446]
# Issue Title

Allow (de)serialization of abstract types with ``JsonSerializer`` when there is a ``JsonConverter`` for that type

# General

When you try to serialize or deserialize a type that is abstract, ``System.Text.Json.JsonSerializer`` currently throws a ``NotSupportedException`` with the message:

> Deserialization of reference types without parameterless constructor is not supported.

JsonSerializer should first check if the list of JsonConverters supports the abstract type and throw this exception only when there is no JsonConverter capable of converting the type.

We currently have a JsonConverter that supports polymorphism and because of this issue we cannot make the base type abstract.

# Additional info
.NET Core version: 3.0.1

**Comment by layomia** [comment]
I believe this issue was fixed for 3.1 in https://github.com/dotnet/corefx/pull/41523. Master/5.0 also has the fix.

Please can you try your scenario in 3.1 - https://github.com/dotnet/core/blob/master/release-notes/3.1/preview/3.1.0-preview3-install-instructions.md?

**Comment by ahsonkhan** [comment]
@LeroyK - I couldn't repro the issue you are seeing with deserializing abstract types (even on .NET Core 3.0). Can you please share a simplified repro where you are seeing the error?

```C#
class Program
{
    static void Main(string[] args)
    {
        var options = new JsonSerializerOptions();
        options.Converters.Add(new MyAbstractConverter());
        var b = JsonSerializer.Deserialize<Person>("{\"OfficeNumber\": \"12345\"}", options);
        Console.WriteLine(((Employee)b).OfficeNumber);
    }
}

public abstract class Person
{
    public string Name { get; set; }
}

public class Employee : Person
{
    public string OfficeNumber { get; set; }
}

public class MyAbstractConverter : JsonConverter<Person>
{
    public override Person Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        reader.Read();
        if (reader.TokenType == JsonTokenType.PropertyName && reader.ValueTextEquals("OfficeNumber"))
        {
            reader.Read();
            var emp = new Employee { OfficeNumber = reader.GetString() };
            reader.Read();
            return emp;
        }
        return null;
    }

    public override void Write(Utf8JsonWriter writer, Person value, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by LeroyK** [comment]
@ahsonkhan thanks for creating the above repro. I have found the issue: my converter had a check for abstract types and skipped all of them. Without that check it works flawlessly. Closing the issue.
