### ISSUE TITLE
Browser compat: System.Threading.Tasks.Parallel.Invoke(...) reference not supported API

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#44605]
`System.Threading.Tasks.Parallel.Invoke(...)` references `Task.WaitAll(tasks);` not supported in browser

This needs tracking issue

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#discussion_r521945787_

**Comment by marek-safar** [comment]
It's probably same as #43411
