### ISSUE TITLE
Future of System.IO.Pipes.AccessControl Package.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#44600]
We bought back this package here https://github.com/dotnet/runtime/pull/38177 to expose some apis.
This package has a dependency on the implementation assembly on System.IO.Pipes which is part of shared framework.

Currently to unblock https://github.com/dotnet/runtime/pull/44373 we harvested the 5.0 and added 6.0 tfm in the package.
Some other options here are 
- Deadend the package if dont meant to expose any apis cc @carlossanlop do u know if we intend to do that.
- Take a dependency on a net5.0 runtimepack and then adding a manual reference to system.io.pipes

cc @ViktorHofer @ericstj @safern

**Comment by ViktorHofer** [comment]
Unless we start producing targeting packs for previous .NETCoreApp versions I assume the latter option wouldn't work with source build. I believe we don't yet build anything else than `$(NetCoreAppCurrent)` in sourcebuild but it came up in the past.

**Comment by Anipik** [comment]
yeah sourcebuild was the reason @ericstj suggested to not do this, but we should expore some optons here to avoid harvesting

**Comment by ViktorHofer** [comment]
Yeah I agree with that we shouldn't use harvesting here as it would suggest to use it when an asset isn't buildable anymore.

**Comment by carlossanlop** [comment]
> _Deadend the package if dont meant to expose any apis cc @carlossanlop do u know if we intend to do that._

I recently added these APIs to System.IO.Pipes.AccessControl for 5.0: https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Pipes.AccessControl/ref/System.IO.Pipes.AccessControl.cs#L69-L77

Does that answer your question, @Anipik ?

**Comment by ViktorHofer** [comment]
@carlossanlop to rephrase the question, do we expect the package to be updated again in this release cycle?

**Comment by safern** [comment]
> @carlossanlop to rephrase the question, do we expect the package to be updated again in this release cycle?

To rephrase this, do we expect new APIs? Cause if there is a bug fix we can always do it in the release/5.0 branch, right?

**Comment by ViktorHofer** [comment]
Caution: 5.0 isn't LTS. Bugfixes could only be done in 5.0 for a year.

**Comment by carlossanlop** [comment]
Right now, we don't have any open issues or API proposals related to `System.IO.Pipes.AccessControl`.  And I think we have already ported all the essential Windows-specific APIs from .NET Framework, so I don't expect any new API proposals in this area.

If we ever have to fix bugs in the Windows-specific APIs, the actual source code is in `System.IO.Pipes`. For example:

- [runtime/src/libraries/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStreamAcl.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipes/src/System/IO/Pipes/AnonymousPipeServerStreamAcl.cs)

- [runtime/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStreamAcl.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStreamAcl.cs)

**Comment by ViktorHofer** [comment]
Thanks Carlos, that helps in the decision making process. Ideally we would not resort to any of these hacks but make the net5.0 asset buildable. I don't know what that would involve (API shifting?). @ericstj and I talked about this briefly.

**Comment by ericstj** [comment]
> Cause if there is a bug fix we can always do it in the release/5.0 branch, right?

> Caution: 5.0 isn't LTS. Bugfixes could only be done in 5.0 for a year.

What bug fix would we do?  I think this package only ships a reference assembly and a full facade.

**Comment by ViktorHofer** [comment]
> What bug fix would we do? I think this package only ships a reference assembly and a full facade.

I didn't know that, great. Sounds to me that removing the package should be considered.

**Comment by carlossanlop** [comment]
What does it mean to remove the package? If we do that, and someone wants to consume `System.IO.Pipes.AccessControl.NamedPipeServerStreamAcl.Create(...)`, how would they do that from now on?

**Comment by ViktorHofer** [comment]
We are about removing the infrastructure to produce a package for System.IO.Pipes.AccessControl in this repo's master branch, not removing the package from nuget.org.

**Comment by safern** [comment]
@ViktorHofer I believe this can be closed as it is covered by: https://github.com/dotnet/runtime/issues/47530 ?
