### ISSUE TITLE
[browser][MT] System.Threading.Tasks.Task.SpinThenBlockingWait(...) uses non supported API

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#44622]
Browser compat: System.Threading.Tasks.Task.SpinThenBlockingWait(...) references `ManualResetEventSlim.Wait(..)` not supported on browser

_we need browser-specific implementation. Please create an issue and link if from here. I'm curious how this works today, I guess we are lucky and hit SpinWait all the time_

@lewing

_Originally posted by @marek-safar in https://github.com/dotnet/runtime/pull/43363#discussion_r522485542_

**Comment by ilonatommy** [comment]
Where are we with working on this issue @kg? https://github.com/dotnet/runtime/issues/44543 and https://github.com/dotnet/runtime/issues/44544 sound like the same problem, so I will pin them here because fix might be similar.

**Comment by kg** [comment]
We haven't made much progress on this, I've been working on GC crashes.

**Comment by radekdoulik** [comment]
I think the `ManualResetEventSlim.Wait` is now supported in the MT version, #96215 fixed that.
