### ISSUE TITLE
.NET 5 fails to read the HOME key on ubuntu16.04

### ISSUE THREAD

**Issue by bagajjal** [dotnet/runtime#44621]
VTSequence for Home is ^[[1~.
bash is able to recognize this VTSequence. .NET fails to recognize the VTSequence.
TERM used is xterm.

I haven't tried the older versions of .NET. But I guess it exists on the older .NET versions as this is a fundamental issue.

Below screenshot captures all the details

![image](https://user-images.githubusercontent.com/23668037/99011786-b95ce500-2501-11eb-8ee6-adb1b7ee8b59.png)

**Comment by eiriktsarpalis** [comment]
I'm able to reproduce using PuTTY. Seeing the same thing with function keys F1-F4 (`^[[11~` - `^[[14~`), however F5-F12 (`^[[15~` - `^[[24~`) are mapped correctly. The Insert (`^[[2~`) and Delete (`^[[3~`) keys are also mapped correctly.

Note that other terminal emulators I tested (Windows terminal, xterm, gnome terminal) all map the Home key to `^[OH` which is interpreted correctly by `Console.ReadKey()`. Same is true for function keys.

As a side note, it looks like `Ctrl+Home` is broken in all terminals that I tested. Related to #802.

**Comment by danmosemsft** [comment]
Is this a regression from 3.1?

**Comment by eiriktsarpalis** [comment]
I don't believe it is, the same behaviour reproduces in 3.1 as well.

**Comment by danmosemsft** [comment]
OK, thanks just look on the lookout for regressions now we shipped (I'm adding the regression from last release label)
