### ISSUE TITLE
[Mono Android][Test] Runtime tests couldn't pass build for Android target

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#44642]
Required coreclr:
- src/tests/Interop/ICastable/Castable.csproj

Generated shell script has no corresponding assembly:
- src/tests/JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_SingleReturnSynchronized.ilproj
- src/tests/baseservices/threading/paramthreadstart/ThreadStartBool_1.csproj

Generated shell script and corresponding assembly have different names:
- src/tests/baseservices/TieredCompilation/BasicTestWithMcj.csproj

Runtime tests building and running instructions could be found [here](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/mono/testing.md)

**Comment by SamMonoRT** [comment]
can be consolidated with https://github.com/dotnet/runtime/issues/52782 ?

**Comment by fanyang-mono** [comment]
> can be consolidated with #52782 ?

Added this to Android x64 tracking issue.

**Comment by fanyang-mono** [comment]
Didn't have bandwidth to work on this in .NET7. Moving to milestone 8.0.0

**Comment by fanyang-mono** [comment]
Test related issue. Moving to 9.0.0

**Comment by vitek-karas** [comment]
@fanyang-mono  is it worth keeping this open? Doesn't seem like we'll get to this anytime soon.

**Comment by fanyang-mono** [comment]
@vitek-karas We probably could close it.
