### ISSUE TITLE
[Mono Android] Runtime tests used more memory than Android simulator allowed

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#44643]
### Description
The following tests use more memory than Android simulator allowed:

- GC/Features/HeapExpansion/bestfit-finalize/*
- GC/Regressions/v2.0-rtm/494226/494226/*
- GC/Scenarios/ServerModel/servermodel/*

### Configuration

Runtime tests building and running instructions could be found [here](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/mono/testing.md)

### Regression?

No. Android is a new target for runtime tests.

**Comment by lewing** [comment]
@SamMonoRT how is this wasm related?

**Comment by SamMonoRT** [comment]
> @SamMonoRT how is this wasm related?

It isn't -- my bad. Fan updated it.

**Comment by SamMonoRT** [comment]
Moving out to 7.0

**Comment by fanyang-mono** [comment]
> @fanyang-mono @naricc - is this still needed, given the Android lanes are stable now ?

The tests mentioned in this issue were disabled. Since we haven't done anything related, I believe the issue is still there. But it could be that those tests are not designed to run Android.

**Comment by SamMonoRT** [comment]
@premun  - Is the memory adjustable for simulators if indeed this is still an issue - If it isn't, @fanyang-mono we can just close this as is.

**Comment by premun** [comment]
I can see that we're giving the emulator 3072 MB and looking at the VMs there's not much room to grow. If this is important, we can always bring it up with our team and consider increasing the VM size but not sure how expensive that would be.

**Comment by SamMonoRT** [comment]
Thanks @premun -- This doesn't seem important enough at this point to influence any changes to VM size/configuration. Closing this issue. We will revisit disabled-test issues later and see if we can get similar coverage in other configs.
