### ISSUE TITLE
Mechanism to !report! exceptions thrown from native external library

### ISSUE THREAD

**Issue by Istox** [dotnet/runtime#44641]
Hi!

Apologies if this is not the correct place for this but i could really use some assistance on an issue. Ive reached the end of my skillset in being able to reasonably diagnose with the tooling available in netcore. 

I work for a company that hosts a netcore 3.1 web application on Windows Server 2019. Unfortunately we are in a position where we are still locked into using some problematic third-party libraries that are crashing around 10 times per day with a runtime exception which obviously causes our webapplication exit and restart and has knockon effects to the rest of our systems.

The particular runtime error information from the System logs server is the following:
**Application popup: Microsoft Visual C++ Runtime Library : Runtime Error!
Program: c:\windows\system32\inetsrv\w3wp.exe
R6025
- pure virtual function call**

The application logs on the server then reference our particular third party library was the source of the error. We have no access to the source code for this library and so my only opportunity of dealing with this is to somehow figure out the particular calls to this library that are causing the crash. I have tried absolutely every which way i know of using the tooling available in netcore3.1 to catch this error at the location where the external call is made but it seems that it is not possible to catch native errors in netcore3.1?

I have thoroughly read the various similar issues already posted on this github and i have found a lot of conflicting information on what can and cannot be done. Most of which reference exception interop on linux but not windows OR are older versions of netcore OR are dealing with CSE exceptions specifically. Purecall exception not being a CSE and considering we are running on windows not linux im left wondering what applies to my scenario and what doesnt.

So i tried everything including:
comPlus_legacyCorruptedStateExceptionsPolicy environment variable + https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/legacycorruptedstateexceptionspolicy-element which was reported as a workaround in another issue on here (can dig up if you want) but didnt work for me.

I completely understand why the decision was made to not allow programmers to catch native exceptions any longer and continue executing for stability reasons, but it seems that when you removed the functionality to catch these exceptions you also removed our only method of being able to easily report the state of the stack at the time they occur.

Is there anything i can do, or the netcore3.1 framework can provide (workaround or not) for catching/reporting in managed code at the time these native purecall errors occur? Or do you have any plans to implement such reporting functionality.

Sorry if im not understanding something or ive missed anything, as i have said end of my skillset, doing the best i can over here.

Regards and thanks!

**Comment by Istox** [comment]
to clarify, my intention is not to catch and do anything other than report and exit. Its the reporting part that is particularly important to me, NOT catching for the purpose of doing anything else

**Comment by jkotas** [comment]
> pure virtual function call

This is a fatal error in C++ runtime. The .NET runtime code is not involved in it nor can influence it at all.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-purecall-handler-set-purecall-handler (note that this is C++ runtime method, again nothing to do with .NET) allows you to customize the action taken on this fatal error. You can try to set this callback for the 3rd party library. It may not be possible if the 3rd party library statically links to the C++ runtime.

**Comment by KalleOlaviNiemitalo** [comment]
A memory dump from [Monitoring Silent Process Exit](https://docs.microsoft.com/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit) might reveal the call stack.
