### ISSUE TITLE
Build Android * Release AllSubsets_Mono_RuntimeTests Jobs are filling the disk on Android queues

### ISSUE THREAD

**Issue by MattGal** [dotnet/runtime#44653]
@akoeplinger / @steveisok  FYI.

Consider job "Build Android x64 Release AllSubsets_Mono_RuntimeTests" in [this build](https://dnceng.visualstudio.com/public/_build/results?buildId=884957&view=logs&j=b6f63eff-75cc-59ca-fdbf-d2121601a613&t=3f89b0b1-a79b-5dad-cfb9-522fb012a84f)

This Helix job:
```
 Sent Helix Job; see work items at /api/jobs/eae17619-7fc8-429c-8c7e-b778efb87c18/workitems?api-version=2019-06-17
  Waiting for completion of job eae17619-7fc8-429c-8c7e-b778efb87c18 on Ubuntu.1804.Amd64.Android.Open
  Job eae17619-7fc8-429c-8c7e-b778efb87c18 on Ubuntu.1804.Amd64.Android.Open is completed with 31 finished work items
```
... doesn't actually use Xharness.  (guessing some kind of MSBuild property shenanigans)

[Sample workitem log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-eae176197fc8429c8c/JIT.Stress/console.51d6140a.log?sv=2019-07-07&se=2020-12-03T02%3A16%3A58Z&sr=c&sp=rl&sig=kfLX0iNV0%2Ffv6BCJ9S56R9qKuxpNksF5domVt8Phneo%3D) (they all are like this)

- If this is not meant to be an xharness / "run on Android" work item, it should be sent to another queue; having two full Android Emulator VHDs already eats a lot of disk space and there is a plain ubuntu.1804.amd64.open queue.
- If this is meant to be an xharness work item, it will still likely need to be tweaked to not fill the disk entirely.

**Comment by akoeplinger** [comment]
This job _does_ use xharness but it's hidden inside of several wrapper layers due to the way the runtime tests work.

**Comment by MattGal** [comment]
Ah I stand corrected; Looking inside a [test result XML](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-2e460d9acc88463bb9/JIT.IL_Conformance/testResults.xml?sv=2019-07-07&se=2020-12-03T13%3A37%3A46Z&sr=c&sp=rl&sig=yQOwQR7gZnkwvGBAJMuvNoBeXXBZ0ADRBGwfom9zpqQ%3D) it seems this is just sticking XHarness inside the XUnit wrappers the regular CoreCLR style tests use.  Regardless, these tests are large and it may be worth the effort to run fewer tests per work item (the whole point of how Helix is built is that each one of these XUnit facts could have been a distinct work item)

If you determine there's no way to not fill the disk, we'll recover just do understand this slows things down a lot for everyone using the queue.

**Comment by MattGal** [comment]
Dug a little deeper, the problem seems to be that the Job lists are getting constructed poorly, resulting in [job lists where the correlation payloads are many, many APKs](https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-97938543-cfa7-4a3f-b6d3-1c72a3e70e0e5dd939edcb34d9187/job-list-d8e56aa1-25a0-454b-8745-2cfc1b666900.json?sv=2019-07-07&se=2020-12-03T13%3A46%3A42Z&sr=c&sp=rl&sig=Q%2FG11j0MGPhAK1yW7kHEjoHQlxQ5MpEqn438ko4kA1k%3D); these should be work item payloads.  @akoeplinger is going to look into the construction of the Helix payloads here.
