### ISSUE TITLE
DirectoryInfoWrapper throws DirectoryNotFoundException when directory is deleted during enumeration

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#44652]
### Description

Reported here https://github.com/dotnet/runtime/issues/44626
Discovered here https://github.com/dotnet/runtime/pull/41426#issuecomment-694985134

I thought I had rooted out this issue and solved it by reducing the timer period(and added an extra test to try and capture the issue), but now I suspect there is a codepath here that is creating the timer on a background thread even when the PFW is disposed.  So the polling timer is still going then we later delete the directory from under it. 

The delete is happening between these two lines, and causing the exception:
https://github.com/dotnet/runtime/blob/5c65d891f203618245184fa54397ced0a8ca806c/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Abstractions/DirectoryInfoWrapper.cs#L36-L38

We could just catch the exception here, since it's already trying to avoid it by checking Exists.  I was hoping to find a better fix to identify where to cancel the timer.  Perhaps we are canceling the timer but it was already running?

This should fix PollingFileProviderShouldntConsumeINotifyInstances to be less flaky.

**Comment by ericstj** [comment]
I believe this is indeed a race condition.  The Timer gets disposed by https://github.com/dotnet/runtime/blob/5c65d891f203618245184fa54397ced0a8ca806c/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs#L261 but nothing will stop a currently running timer callback when this happens.

The problem can occur if a directory is deleted after the exists check and before enumeration starts here: https://github.com/dotnet/runtime/blob/5c65d891f203618245184fa54397ced0a8ca806c/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/Abstractions/DirectoryInfoWrapper.cs#L36-L38

If the deletion happens during enumeration the enumeration will halt, but if it happens at the start an exception is thrown.  We can address this by handling the exception, since the existence check makes it clear that this should ignore missing directories.

**Comment by ericstj** [comment]
Here's a customer hit on this same race condition: https://stackoverflow.com/questions/54830949/omnisharp-not-functioning-properly-in-one-project-but-is-in-another

**Comment by stephentoub** [comment]
> but nothing will stop a currently running timer callback when this happens

I've not read the full description to know whether this is relevant,  but there are Timer.Dispose{Async} overloads that let you wait until all work associated with the timer has quiesced.

**Comment by ericstj** [comment]
I can safely say that it's part of the DirectoryInfoWrapper's contract to not throw on a missing directory regardless so I feel this is the right fix.

**Comment by ericstj** [comment]
> there are Timer.Dispose{Async} overloads that let you wait until all work associated with the timer has quiesced.

We'd need to add DisposeAsync to PhysicalFilesWatcher to support this, but that's not a bad idea.  I'll open an issue on it.

**Comment by stephentoub** [comment]
And/or use Timer.Dispose(WaitHandle).

**Comment by directhex** [comment]
Closing as resolved by https://github.com/dotnet/runtime/pull/44671
