### ISSUE TITLE
Browser WebSockets tests

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#44666]
We still don't have good functional tests for browser WebSockets in CI in inner or outer loops as evidenced by #44551 we need to resolve this now that we are unblocked on the xharness side.

- [x] Partial send {endOfMessage: false} `System.Net.WebSockets.Client.Tests.SendReceiveTest.SendReceive_PartialMessageDueToSmallReceiveBuffer_Success`
- [x] Text/Binary `System.Net.WebSockets.Client.Tests.ConnectTest.EchoBinaryMessage_Success, EchoTextMessage_Success`
- [x] Cancellation `System.Net.WebSockets.Client.Tests.CancelTest`
- [x] Abort `System.Net.WebSockets.Client.Tests.AbortTest`
- [x] SendAsync buffering/completion `System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest`

**Comment by kjpou1** [comment]
Looking into it

**Comment by pavelsavara** [comment]
@lewing I believe that the `System.Net.WebSockets.Client.Tests` functional tests with Xharness server now cover what is asked here.
The browser doesn't support all the `endOfMessage: false` scenarios, see https://github.com/dotnet/runtime/issues/46982.
