### ISSUE TITLE
StringComparer.OrdinalIgnoreCase does not ignore case for several Cyrillic letters when used with Dictionary 

### ISSUE THREAD

**Issue by vanashimko** [dotnet/runtime#44681]
### Description

`StringComparer.OrdinalIgnoreCase` does not ignore case for several (not all) Cyrillic **when used with Dictionary**: `new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)`. **It works fine when `StringComparer.OrdinalIgnoreCase` is used separately**. Seems to be it was introduced in #36252. It works for `а (0x430) - п (0x43f)`, and does not for `р (0x440) - ё (0x451)`.

### Steps to reproduce:
NUnit:
```csharp
public class Tests
{
    // Russian alphabet
    private const string Lower = "абвгдеёжзийклмнопрстуфхцчшщьыъэюя";
    private const string Higher = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯ";

    public static IEnumerable TestCases => Lower.Zip(Higher, (l, h) => new [] {l.ToString(), h.ToString()});
    
    [TestCaseSource(nameof(TestCases))]
    public void Dictionary(string lower, string higher)
    {
        var dictionary = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase) {[lower] = 1};
        Assert.AreEqual(dictionary[higher], 1);
    }
}
```
**Actual:**
```
🗸 Passed Dictionary("а","А") [6 ms]
🗸 Passed Dictionary("б","Б") [< 1 ms]
🗸 Passed Dictionary("в","В") [< 1 ms]
🗸 Passed Dictionary("г","Г") [< 1 ms]
🗸 Passed Dictionary("д","Д") [< 1 ms]
🗸 Passed Dictionary("е","Е") [< 1 ms]
x Failed Dictionary("ё","Ё") [8 ms]
🗸 Passed Dictionary("ж","Ж") [< 1 ms]
🗸 Passed Dictionary("з","З") [< 1 ms]
🗸 Passed Dictionary("и","И") [< 1 ms]
🗸 Passed Dictionary("й","Й") [< 1 ms]
🗸 Passed Dictionary("к","К") [< 1 ms]
🗸 Passed Dictionary("л","Л") [< 1 ms]
🗸 Passed Dictionary("м","М") [< 1 ms]
🗸 Passed Dictionary("н","Н") [< 1 ms]
🗸 Passed Dictionary("о","О") [< 1 ms]
🗸 Passed Dictionary("п","П") [< 1 ms]
x Failed Dictionary("р","Р") [< 1 ms]
x Failed Dictionary("с","С") [< 1 ms]
x Failed Dictionary("т","Т") [< 1 ms]
x Failed Dictionary("у","У") [< 1 ms]
x Failed Dictionary("ф","Ф") [< 1 ms]
x Failed Dictionary("х","Х") [< 1 ms]
x Failed Dictionary("ц","Ц") [< 1 ms]
x Failed Dictionary("ч","Ч") [< 1 ms]
x Failed Dictionary("ш","Ш") [< 1 ms]
x Failed Dictionary("щ","Щ") [< 1 ms]
x Failed Dictionary("ь","Ь") [< 1 ms]
x Failed Dictionary("ы","Ы") [< 1 ms]
x Failed Dictionary("ъ","Ъ") [< 1 ms]
x Failed Dictionary("э","Э") [< 1 ms]
x Failed Dictionary("ю","Ю") [< 1 ms]
x Failed Dictionary("я","Я") [< 1 ms]

Total tests: 33
     Passed: 16
     Failed: 17
```
**Expected:** all pass.

### Configuration

.NET 5.0.100, both Windows and Linux.

### Regression?

Yes, works fine on .NET Core 3.1.

**Comment by wzchua** [comment]
https://github.com/dotnet/runtime/blob/52d405e92db4eaaf7f3c52ac615d9cd4f5341315/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/RandomizedStringEqualityComparer.cs#L74-L121

Seems like there was some mix up with OrdinalIgnoreCaseComparer and RandomizedOrdinalIgnoreCaseComparer

**Comment by stephentoub** [comment]
cc: @GrabYourPitchforks

**Comment by EgorBo** [comment]
Simplified repro:
```csharp
bool equals = "Ф".Equals("ф", StringComparison.OrdinalIgnoreCase); // true

var d = new Dictionary<string, int>(
    StringComparer.OrdinalIgnoreCase) { ["ф"] = 42 };
int value = d["Ф"]; // KeyNotFound
```

**Comment by GrabYourPitchforks** [comment]
We should definitely consider this for 5.0.x servicing.

**Comment by wzchua** [comment]
@GrabYourPitchforks `OrdinalIgnoreCaseComparer : RandomizedStringEqualityComparer` is using the wrong hash function, right?
and RandomizedOrdinalIgnoreCaseComparer  doesn't seem to be used

**Comment by GrabYourPitchforks** [comment]
@wzchua The error is within an internal function in the string class. Egor's PR at https://github.com/dotnet/runtime/pull/44688 should resolve it.

**Comment by wzchua** [comment]
I guess I discovered a different issue. But the `OrdinalIgnoreCaseComparer : RandomizedStringEqualityComparer` uses `Marvin.ComputeHash32`.

**Comment by GrabYourPitchforks** [comment]
@wzchua Ah, I get it now. Yeah, I'll file a new issue for this.
