### ISSUE TITLE
ServiceController._waitForStatusSignal is never signaled nor disposed

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#44699]
### Description

The System.ServiceProcess.ServiceController._waitForStatusSignal field refers to a ManualResetEvent that is constructed and possibly waited for, but never signaled nor disposed. It just causes useless work for the garbage collector and the kernel.

Constructed:
<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L24>

Waited for:
<https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L907>

The field is private, and ServiceController is not a partial class, so there cannot be references in other files.

### Configuration

.NET v5.0.0-rtm.20519.4 on Windows, any architecture.

### Regression?

Not a regression from previous versions of .NET Core.

However, .NET Framework uses Thread.Sleep instead: <https://github.com/microsoft/referencesource/blob/f461f1986ca4027720656a0c77bede9963e20b7e/System.ServiceProcess/ServiceController.cs#L1272>

### Other information

I noticed this while looking at how <https://github.com/dotnet/runtime/issues/35284> could be implemented.

The useless ManualResetEvent was discussed in <https://github.com/dotnet/corefx/pull/627/files#r24084380> when it was first added in 2015. It was intended to be "scrapped soon".

**Comment by MCCshreyas** [comment]
Hi @KalleOlaviNiemitalo, Can I take this issue to get it fixed? 

cc @danmosemsft

**Comment by KalleOlaviNiemitalo** [comment]
No objections, @MCCshreyas. I don't intend to work on this myself.

**Comment by MCCshreyas** [comment]
OK @KalleOlaviNiemitalo. Waiting for @danmosemsft green signal for go ahead as he is the owner of this area I guess!

**Comment by danmosemsft** [comment]
I haven't looked at that code but if there is a bug we'd welcome a PR.

**Comment by MCCshreyas** [comment]
OK @danmosemsft, I will get this fixed as part of PR, and will post tests results as well!
