### ISSUE TITLE
🔥🔥🔥 CI down - Most jobs are failing with: "Failed to retrieve information about .. from remote source".

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#44700]
[Full log](https://dev.azure.com/dnceng/public/_build/results?buildId=887008&view=logs&j=7c52437f-2051-5ead-95de-b55e3296cb61&t=8db66bc6-175f-59c5-6a1e-742f332c2bdf):
```
##[error].dotnet/sdk/5.0.100-rc.2.20479.15/NuGet.RestoreEx.targets(19,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json.

```
[Example1](https://dev.azure.com/dnceng/public/_build/results?buildId=887005&view=results), [Example2](https://dev.azure.com/dnceng/public/_build/results?buildId=887008&view=results).

PTAL @dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
https://status.dev.azure.com/

Artifacts service is currently in a degraded state.

**Comment by ViktorHofer** [comment]
Mitigated: https://status.dev.azure.com/_event/214095865

**Comment by ViktorHofer** [comment]
Even though not actionable, still happening. Reopening.

**Comment by johnterickson** [comment]
We're seeing a huge increase in load on `NuGet xplat/5.6.0` from what looks like AWS IP address blocks.

**Comment by johnterickson** [comment]
We're adjusting our throttling thresholds to try to adjust to the load.  We're tightening limits on "anonymous per IP" requests and relaxing limits on a secondary "total anonymous". This means that random folks like https://twitter.com/diracdelta/status/1328126258295701504 won't be blocked from `restore` but CI will probably still see throttling.

**Comment by johnterickson** [comment]
https://dnceng.visualstudio.com/public/_build/results?buildId=887168&view=results is looking good so far 🤞

**Comment by ViktorHofer** [comment]
Closing as mitigated by the AzDO team.

**Comment by ViktorHofer** [comment]
Still happening.

**Comment by dougbu** [comment]
Are "failed to retrieve information about" and perhaps the message about failed NuGet index.json retrievals (not coming to me offhand) sufficiently specific to turn this into a live issue, allowing us to view whether the incidence is actually going down❔

**Comment by ViktorHofer** [comment]
Probably. We are in active discussion with the AzDO team though.
