### ISSUE TITLE
`build` fails with "Invalid restore input. Duplicate frameworks found: 'net6.0-windows7.0, net6.0, net6.0'"

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#44708]
### Repro

Run `build` without any arguments from the root of the repo according to the
https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md#concepts

### Actual result

```
  installer.tasks -> D:\runtime\artifacts\bin\installer.tasks\Debug\net461\installer.tasks.dll
  installer.tasks -> D:\runtime\artifacts\bin\installer.tasks\Debug\netstandard2.0\installer.tasks.dll
  Determining projects to restore...
D:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.RestoreEx.targets(19,5): error : Invalid restore input. Duplicate frameworks found: 'net6.0-windows7.0, net6.0, net6.0'. Input files: D:\runtime\src\libraries\Microsoft.Win32.Primitives\src\Microsoft.Win32.Primitives.csproj. [D:\runtime\Build.proj]
D:\runtime\.dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateFrameworks(PackageSpec spec, IEnumerable`1 files) [D:\runtime\Build.proj]
```

### Expected result

Builds successful. This is regression introduced in recent week or so.

**Comment by jkotas** [comment]
@jkoritzinsky I suspect that this was introduced by the sharedframework sdk changes.

**Comment by jkoritzinsky** [comment]
I don't think this is from the shared framework changes. That PR didn't touch the libraries infrastructure at all. This looks like something related to work that @Anipik has been doing.

**Comment by ViktorHofer** [comment]
I believe this is related to @Anipik's changes as he stopped stripping the platform from the target framework. @Anipik can you please take a look?

**Comment by Anipik** [comment]
I will take a look

**Comment by Anipik** [comment]
@jkotas is still reproing on ur machine ? because i tried build.cmd on the my machine and it works, can you provide some more info ?

**Comment by jkotas** [comment]
I am not able to reproduce this anymore. I guess it was caused triggered by AzDo availability problems. Another similar issue is #44710.
 
I will close this issue and open a new issue to improve diagnostic for networking issues hit during the build. As it stands, network issues hit during the build can lead to very arbitrary errors.
