### ISSUE TITLE
The extension method that can receive null after the? Sign is not executed

### ISSUE THREAD

**Issue by Vcc1** [dotnet/runtime#44717]
### Description
The extension method that can receive null after the? Sign is not executed
x()?.y().ExtensionMethod()
Expect extensionmethod to be executed

### Regression?

Any version

**Comment by Joe4evr** [comment]
This is expected, `?.` is defined to short-circuit and *not* evaluate the right-hand side of the expression if the left-hand side evaluates to `null`.

Also, this is not an issue with the runtime.

**Comment by Vcc1** [comment]
谢谢是我搞错了

**Comment by Vcc1** [comment]
> ### 描述
> 在 "？未执行符号
> x（）？y（）。扩展方法（）
> 预期将执行扩展方法
> 
> ### 配置
> ### 回归？
> 任何版本



> 这是预料之中的，定义为短路_，如果_左侧计算到 ，则不计算表达式的右侧。`?.``null`
> 
> 此外，这不是运行时的问题。

谢谢是我搞错了
