### ISSUE TITLE
MemberInfo.GetCustomAttribute() performance issue

### ISSUE THREAD

**Issue by ENikS** [dotnet/runtime#44713]
### Description

While trying to select a fastest method to retrieve custom attributes I've came across very peculiar result. I've setup 3 tests to benchmark available methods:

```c#
private PropertyInfo property = typeof(Access1).GetTypeInfo().GetProperty(nameof(Property));

[Import]
public int Property { get; set; }

[Benchmark]
public object GetCustomAttributesAll()
{
    return property.GetCustomAttributes(true);
}

[Benchmark]
public object GetCustomAttribute()
{
    return property.GetCustomAttribute(typeof(ImportAttribute), true);
}

[Benchmark]
public object GetCustomAttributesType()
{
    return property.GetCustomAttributes(typeof(ImportAttribute), true);
}
```

A simple property with just one attribute. 

Logically, `PropertyInfo.GetCustomAttribute(typeof(ImportAttribute), true);` should be the fastest. No array allocation is necessary to return the attribute, but to my surprise it is not the case. It is 4 (four) times slower than the other two methods!

```bash

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1198 (1909/November2018Update/19H2)
AMD Ryzen Threadripper 2970WX, 1 CPU, 48 logical and 24 physical cores
.NET Core SDK=5.0.100
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
  Job-OETPQV : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT

IterationCount=3  LaunchCount=1  WarmupCount=3

|                  Method |       Mean |     Error |   StdDev |
|------------------------ |-----------:|----------:|---------:|
|  GetCustomAttributesAll |   742.1 ns |  83.02 ns |  4.55 ns |
|      GetCustomAttribute | 3,724.1 ns | 201.08 ns | 11.02 ns |
| GetCustomAttributesType |   775.8 ns |  10.39 ns |  0.57 ns |

```

This timing does not make any sense and should be looked at.

**Comment by stephentoub** [comment]
This is what I see now on .NET 6:

|                  Method |        Job |  Runtime | Toolchain |     Mean |   Error |  StdDev | Ratio |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------------ |----------- |--------- |---------- |---------:|--------:|--------:|------:|-------:|-------:|-------:|----------:|
|  GetCustomAttributesAll | Job-XBYXUK | .NET 5.0 |    net5.0 | 429.1 ns | 1.04 ns | 0.87 ns |  1.00 | 0.0162 | 0.0000 | 0.0000 |     104 B |
|  GetCustomAttributesAll | Job-MPZUSE | .NET 6.0 |    net6.0 | 382.6 ns | 1.71 ns | 1.43 ns |  0.89 | 0.0162 | 0.0000 | 0.0000 |     104 B |
|                         |            |          |           |          |         |         |       |        |        |        |           |
|      GetCustomAttribute | Job-XBYXUK | .NET 5.0 |    net5.0 | 922.4 ns | 6.47 ns | 5.74 ns |  1.00 | 0.1049 | 0.0000 | 0.0000 |     664 B |
|      GetCustomAttribute | Job-MPZUSE | .NET 6.0 |    net6.0 | 504.1 ns | 0.64 ns | 0.53 ns |  0.55 | 0.0162 | 0.0000 | 0.0000 |     104 B |
|                         |            |          |           |          |         |         |       |        |        |        |           |
| GetCustomAttributesType | Job-XBYXUK | .NET 5.0 |    net5.0 | 468.2 ns | 1.98 ns | 1.75 ns |  1.00 | 0.0162 | 0.0000 | 0.0000 |     104 B |
| GetCustomAttributesType | Job-MPZUSE | .NET 6.0 |    net6.0 | 441.7 ns | 1.42 ns | 1.11 ns |  0.94 | 0.0162 | 0.0000 | 0.0000 |     104 B |

**Comment by ENikS** [comment]
It looks a lot more reasonable compared to my test. What intrigues me is why getting single attribute takes longer than getting them all. `GetCustomAttributesAll` supposedly allocates an array in addition to an attribute, but it is still faster than `GetCustomAttribute`.

**Comment by krwq** [comment]
[Triage] I'm moving this to 7.0 since this is non-essential. Some work has already be done. If anyone wants to contribute here we're still open for PRs.

**Comment by steveharter** [comment]
Closing; verified that 7.0 does not have the issue any longer.
```
|                  Method |     Mean |   Error |  StdDev |
|------------------------ |---------:|--------:|--------:|
|  GetCustomAttributesAll | 303.9 ns | 0.96 ns | 0.90 ns |
|      GetCustomAttribute | 327.8 ns | 1.30 ns | 1.15 ns |
| GetCustomAttributesType | 308.5 ns | 1.33 ns | 1.18 ns |
```

<details><summary>Repro using Benchmark.NET</summary>

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Reflection;

namespace ConsoleApp97
{
    internal class Program
    {
        static void Main()
        {
            BenchmarkRunner.Run<Access1>();
        }
    }


    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property | AttributeTargets.ReturnValue | AttributeTargets.Class | AttributeTargets.Struct)]
    public class ImportAttribute : Attribute
    {

    }

    public class Access1
    {
        private PropertyInfo property = typeof(Access1).GetTypeInfo().GetProperty(nameof(Property));

        [Import]
        public int Property { get; set; }

        [Benchmark]
        public object GetCustomAttributesAll()
        {
            return property.GetCustomAttributes(true);
        }

        [Benchmark]
        public object GetCustomAttribute()
        {
            return property.GetCustomAttribute(typeof(ImportAttribute), true);
        }

        [Benchmark]
        public object GetCustomAttributesType()
        {
            return property.GetCustomAttributes(typeof(ImportAttribute), true);
        }
    }
}
```
</details>
