### ISSUE TITLE
property in derived type gets lost when serializing when using keyword 'this', which behaves differently from NewtonJson

### ISSUE THREAD

**Issue by cwx521** [dotnet/runtime#44718]
@ericstj | @layomia @steveharter @jozkee
-- | --

see the test results

![image](https://user-images.githubusercontent.com/15984461/99222902-714e0300-281e-11eb-85fa-f29b02364ca6.png)
![image](https://user-images.githubusercontent.com/15984461/99223051-bbcf7f80-281e-11eb-9320-fa878893989c.png)

**Comment by Joe4evr** [comment]
#29937

**Comment by ColinM9991** [comment]
`this` isn't the issue here. It's the lack of support for polymorphic serialization, out of the box, in System.Text.Json that is the issue.

**Comment by layomia** [comment]
Dup of https://github.com/dotnet/runtime/issues/29937.
