### ISSUE TITLE
`build -s libs.pretest` fails on Linux

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#44710]
Repro:

Run `./build.sh  -s libs.pretest` on Linux

Result:
```
  Determining projects to restore...
/home/jkotas/runtime/.dotnet/sdk/5.0.100-rc.2.20479.15/NuGet.RestoreEx.targets(19,5): error : The result "" of evaluating the value "$(DotNetBuildTasksSharedFrameworkTaskFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  /home/jkotas/runtime/src/libraries/pretest.proj [/home/jkotas/runtime/Build.proj]
/home/jkotas/runtime/.dotnet/sdk/5.0.100-rc.2.20479.15/NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) [/home/jkotas/runtime/Build.proj]
```

**Comment by jkotas** [comment]
@jkoritzinsky Could you please route this?

**Comment by ViktorHofer** [comment]
@jkotas can you please share a binlog? I'm unsure how this could ever happen and I'm inclined to believe that this actually has to do with restore failing (because of an outage right now). A binlog should tell.

**Comment by jkotas** [comment]
You are probably right. I am not able to reproduce this anymore.

If it is the case, it seems like our scripts or something in msbuild or nuget is silently ignoring errors instead of propagating them up.

**Comment by ViktorHofer** [comment]
Likely nuget but hardly actionable without logs or repro steps.
