### ISSUE TITLE
API Proposal: Arithmetic and bit operation methods for byte, sbyte, short, and ushort

### ISSUE THREAD

**Issue by MineCake147E** [dotnet/runtime#44721]
## Background and Motivation

The C# language forces users to cast (U)Int16 and (S)Byte to (U)Int32 and divide, like:  
```C#
public static ushort Div(ushort value) => (ushort)(value / 19u);
```
We can rewrite it without casts like:
```C#
public static ushort Div2(ushort value)
{
    value /= 19;
    return value;
}
```
But, even if we use `/=` operator , the code casts into `int` first, and divides.
So, I suggest adding supports for Arithmetic and Bitwise operations for `ushort`, `short`, `byte`, and `sbyte` in someway.

## Proposed API

Adding operator overloads break existing codes hugely, so I considered implementing methods like:

```C#
namespace System.Numerics
{
    public static class ArithmeticOperations
    {
        public static short Add(short left, short right);
        public static ushort Add(ushort left, ushort right);
        public static byte Add(byte left, byte right);
        public static sbyte Add(sbyte left, sbyte right);
        public static short Subtract(short left, short right);
        public static ushort Subtract(ushort left, ushort right);
        public static byte Subtract(byte left, byte right);
        public static sbyte Subtract(sbyte left, sbyte right);
        public static short Multiply(short left, short right);
        public static ushort Multiply(ushort left, ushort right);
        public static byte Multiply(byte left, byte right);
        public static sbyte Multiply(sbyte left, sbyte right);
        public static short Divide(short left, short right);
        public static ushort Divide(ushort left, ushort right);
        public static byte Divide(byte left, byte right);
        public static sbyte Divide(sbyte left, sbyte right);
        public static short Modulo(short left, short right);
        public static ushort Modulo(ushort left, ushort right);
        public static byte Modulo(byte left, byte right);
        public static sbyte Modulo(sbyte left, sbyte right);
        public static short Negate(short left);
        public static ushort Negate(ushort left);
        public static byte Negate(byte left);
        public static sbyte Negate(sbyte left);
    }
    public static class BitOperations
    {
        public static short ShiftArithmeticRight(short left, int right);
        public static ushort ShiftRight(ushort left, int right);
        public static byte ShiftRight(byte left, int right);
        public static sbyte ShiftArithmeticRight(sbyte left, int right);
        public static short ShiftLeft(short left, int right);
        public static ushort ShiftLeft(ushort left, int right);
        public static byte ShiftLeft(byte left, int right);
        public static sbyte ShiftLeft(sbyte left, int right);
        public static short BitwiseNot(short left);
        public static ushort BitwiseNot(ushort left);
        public static byte BitwiseNot(byte left);
        public static sbyte BitwiseNot(sbyte left);
        public static short BitwiseOr(short left, short right);
        public static ushort BitwiseOr(ushort left, ushort right);
        public static byte BitwiseOr(byte left, byte right);
        public static sbyte BitwiseOr(sbyte left, sbyte right);
        public static short BitwiseAnd(short left, short right);
        public static ushort BitwiseAnd(ushort left, ushort right);
        public static byte BitwiseAnd(byte left, byte right);
        public static sbyte BitwiseAnd(sbyte left, sbyte right);
        public static short BitwiseXor(short left, short right);
        public static ushort BitwiseXor(ushort left, ushort right);
        public static byte BitwiseXor(byte left, byte right);
        public static sbyte BitwiseXor(sbyte left, sbyte right);
        //optional
        public static short RotateRight(short left, int right);
        public static ushort RotateRight(ushort left, int right);
        public static byte RotateRight(byte left, int right);
        public static sbyte RotateRight(sbyte left, int right);
        public static short RotateLeft(short left, int right);
        public static ushort RotateLeft(ushort left, int right);
        public static byte RotateLeft(byte left, int right);
        public static sbyte RotateLeft(sbyte left, int right);
    }
}
```
which the RyuJIT compiles to appropriate instructions that don't cast.

## Usage Examples

The first code can be written as follows:
```C#
public static ushort Div(ushort value) => ArithmeticOperations.Divide(value, (ushort)19);
```

## Alternative Designs

I also considered to implement operators for the 4 types, which is a huge breaking change on the C# language.

## Previous discussion

https://github.com/dotnet/csharplang/issues/2895 Proposal: Arithmetic and Bitwise operators for (U)Int16 and (S)Byte

**Comment by huoyaoyuan** [comment]
It's quite hard to do such a change.

> Adding operator overloads break existing codes hugely.

You did mention this. But, defining these as methods isn't useful, because they are even longer than operating as 32bit then casting.

There can be an opportunity to optimize the patterns though. Currently [JIT](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYRoG8aHunHjykDXAAtoGBgFkAFCLENsaIaKjjgASi49O1HrqYB2BjOUY1U7AwDUDdQG5N3AL4OGL+kwEMAlgDtxE0ilfcQVvPxsNHS0XXWJDC2tgeyinFzc+TwAbCB8Ac0k6KWy8+UVi/PUXbT0eOPkrG2TdZ2pHIA) generates suboptimal code for this.

Given that usages of 16-bit and 8-bit numbers are discouraged, I don't expect such APIs to be approved.

**Comment by EgorBo** [comment]
Is `(ushort)(value / 19u);` actually worse than `ArithmeticOperations.Div(value, 19)` ?

**Comment by MineCake147E** [comment]
> There can be an opportunity to optimize the patterns though. Currently [JIT](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYRoG8aHunHjykDXAAtoGBgFkAFCLENsaIaKjjgASi49O1HrqYB2BjOUY1U7AwDUDdQG5N3AL4OGL+kwEMAlgDtxE0ilfcQVvPxsNHS0XXWJDC2tgeyinFzc+TwAbCB8Ac0k6KWy8+UVi/PUXbT0eOPkrG2TdZ2pHIA) generates suboptimal code for this.

I changed my mind.  
Now I hope the RyuJIT does this optimization, instead of adding long APIs that I proposed.  
So, I'll close this issue.  

Should I post another issue for codegen-level optimizations?

**Comment by EgorBo** [comment]
> Should I post another issue for codegen-level optimizations?

Yes please
