### ISSUE TITLE
ngen.exe takes a long time to ngen several big executables - can it run in parallel?

### ISSUE THREAD

**Issue by informatorius** [dotnet/runtime#44724]
### Description
ngen.exe takes a long time to ngen several big executables - can it run in parallel?

### Configuration
Windows 10 .net framework 4.8

### Regression?
no

When I run ngen for several big executables then it takes a long time. I can only run ngen for one executable, then for the next and not in parallel because it locks. Most CPU idles during run. Would it be possible to make ngen run in parallel? Or give ngen a folder to run in and it make multithreading?

**Comment by jkotas** [comment]
You can use `/queue` argument for ngen.exe to queue compilation of all your assemblies, and then run `ngen eqi` to compile everything in the queue in parallel.

Note that this repo is not for reporting .NET Framework issues. .NET Framework issues should be reported via https://developercommunity.visualstudio.com/
