### ISSUE TITLE
Environment.GetEnvironmentVariables() called multiple times during MVC app startup

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#44733]
When starting up a plain `dotnet new mvc` app, `Environment.GetEnvironmentVariables()` is called three times, once from HostBuilder.BuildAppConfiguration(), once from HostBuilder.BuildHostConfiguration(), and once from Microsoft.AspNetCore.Host.GenericWebHostBuilder, resulting in the environment variables being parsed multiple times and in three times as many strings being created as is really needed:
![image](https://user-images.githubusercontent.com/2642209/99275030-01795180-27f9-11eb-9b97-c034f23b0e25.png)
At least the first two are both called from the same method, HostBuilder.Build:
https://github.com/dotnet/runtime/blob/162b33e19eb5a3434867541be691e1082039b130/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L119-L134
It'd be nice if the call could be made once and the results used for the various calls. (It's more challenging / problematic for Environment.GetEnvironmentVariables() to cache, but we could look at that, too, if necessary.)

Related to https://github.com/dotnet/runtime/issues/44598

**Comment by MCCshreyas** [comment]
Seems like for those methods Configuration is getting resolved each time and because of which environment variables are getting fetched. 
So Stephen, will it better to modify the source here or introduce a new API or overload to `GetEnvironmentVariables()`. 
```csharp
public static IDictionary GetEnvironmentVariables(EnvironmentVariableTarget target, bool fromCache)
{
  if(fromCache)
  {
    // Get it from cache
  }
   // otherwise go the long path and fetch variables again.

}

```
So in above if environment variables are not getting changed as often, like in this Host case, we can cache those values and provide it rather than fetching it every single time.

**Comment by stephentoub** [comment]
I don't think it makes sense to add a caching variant to Environment.GetEnvironmentVariables.

**Comment by MCCshreyas** [comment]
OK. Ok. @stephentoub

**Comment by benaadams** [comment]
In PR https://github.com/dotnet/runtime/pull/49856

**Comment by stephentoub** [comment]
Doesn't seem to be a good way to address this.  Closing.
