### ISSUE TITLE
Improve warning suppression precision for trim incompatible APIs

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#44735]
## Background and Motivation

Trim incompatible APIs should be annotated with `RequiresUnreferencedCodeAttribute` which in turn generates warnings when such API is called. The warning as currently implemented will always have code `IL2026` and only part of its message is derived from the arguments of `RequiresUnreferencedCodeAttribute`.

It is expected that `RequiresUnreferencedCodeAttribute` will be used to mark quite a few trim incompatible APIs in the framework as well as in first and third party libraries.

It's likely that some warnings generated by this attribute will be false positives in the context of an application. Such cases should be handled by suppressing the warning. It's very desirable to make such suppression as precise as possible, so that it only suppresses the one case which it's meant to, while allowing trimming analysis to raise similar warnings in close by code or when caused by future changes to the code.

This proposal is add optional value to `RequiresUnreferencedCodeAttribute` which would be used to categorize the attribute as belonging to a specific functionality (feature), and then propose a suppression mechanism which would be able to target a warning from specific functionality only.

## Proposed API

```diff
namespace System.Diagnostics.CodeAnalysis
{
    public sealed class RequiresUnreferencedCodeAttribute : Attribute
    {
        public string Message;
        public string? Url;

+        // Additional name of a functionality which can be used to more precisely target suppressions
+        public string? FeatureName;

        public RequiresUnreferencedCodeAttribute(string message) { }
    }
}
```

## Usage Examples

The `UnconditionalSuppressMessageAttribute` allows specifying scope down to the level of a single method body in which a given warning should be suppressed. If the user wants to suppress one specific occurrence of the warning there's currently no way to target one warning directly. This is imprecise and can lead to over-suppression.

The proposal is to add optional parameters to the `RequiresUnreferencedCodeAttribute` to make the one specific warning easier to target via suppression. On the suppression side, the `UnconditionalSuppressMessageAttribute.MessageId` would be used to make the suppression more precise (similarly to what [`SuppressMessageAttribute.MessageId`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.suppressmessageattribute.messageid?view=net-5.0) is used for).

```csharp
// Framework code
public class DataContractSerializer
{
    [RequiresUnreferencedCode("DataContractSerializer is not compatible with trimming and its usage may break in trimmed applications", FeatureName="DataContractSerializer")]
    void WriteObject(XmlWriter writer, object o)
    {
        // ...
    }
}

// User code
[UnconditionalSuppressMessage("Trim analysis", "IL2026",  MessageId="DataContractSerializer", Justification="Trivial case of serializing a simple string is not affected by trimming")]
void Main()
{
    // This will generate IL2026 because Assembly.GetTypes is annotated with RequiresUnreferencedCode
    var types = Assembly.GetExecutingAssembly().GetTypes();

    // This would also generate IL2026 because of the potential annotation shown, but the case of writing just
    // a simple string will always work, so it's OK to suppress it here.
    DataContractSerializer.WriteObject(_writer, "Hello");
}
```

### Naming

The above shown `FeatureName` does not feel right, but I could not come up with anything better.

### Allowing custom warning codes

The above proposal addresses the problem when using `UnconditionalSuppressMessageAttribute`, which can be done from code only. Warnings can also be suppressed in project via MSBuild properties or on the command line when building the application.

The only way to suppress warnings project-wide (or at build time via command line) is to specify exact warning code. In that case all warnings with that code will be suppressed. Since all occurrences of `RequiresUnreferencedCodeAttribute` produce the same warning code `IL2026` there's no way to selectively suppress these warnings about just one feature. Using the above example, there's no way to suppress all `DataContractSerializer` warnings using project or build-time settings.
Potential solution might be to allow customizing the warning code in the `RequiresUnreferencedCode` attribute - for example:

```csharp
[RequiresUnreferencedCode("DataContractSerializer is not compatible with trimming and its usage may break in trimmed applications", WarningCode="8001")]
public void WriteObject(XmlWriter writer, object o) { }
```

This would allow categorizing all `DataContractSerializer` warnings under the same code `IL8001`. Suppressing these warnings would work both using the `UnconditionalSuppressMessageAttribute` as well as project-wide or command-line settings.

The downside of this approach is that currently most of the existing tooling around warnings is geared toward numerical codes, and thus it's likely it would be used to specify a numerical code like above. Unfortunately numerical codes are very prone to accidental collisions (similar problem exists currently in Roslyn analyzer space where there's no standard way to pick warning numbers to avoid collisions).

That said project-wide suppression with feature-level precision is nowhere near as important as having the ability to precisely address targeted suppressions via attributes. The main purpose of precisely targeting suppressions is to allow analysis tools to detect potential problems in unrelated code. Ability to suppress a warning project-wide, even if scoped to a specific feature, helps only very little with that goal.

## Risks

None - the additional value would be optional, and the existing attribute and suppressions would continue to work.

**Comment by jkotas** [comment]
> The above shown FeatureName does not feel right

`MessageId` since it pairs with `UnconditionalSuppressMessageAttribute.MessageId` ?

**Comment by sbomer** [comment]
It seems (experimentally) that `SuppressMessageAttribute.MessageID` will match against any part of the warning text. Maybe we should copy this behavior with `UnconditionalSuppressMessageAttribute`, and not introduce an extra parameter to `RequiresUnreferencedCode`? I think the warning strings passed to `RequiresUnreferencedCode.Message` should contain some unambiguous identifier anyway.

**Comment by vitek-karas** [comment]
Closing this, as apparently Roslyn has no plans to support `MessageId` for normal analyzers (and we should match Roslyn behavior as closely as possible elsewhere to provide consistent experience). https://github.com/dotnet/roslyn-analyzers/issues/2865#issuecomment-534661905

The only problem here will be that if somebody uses pragmas to selectively suppress the warning in Roslyn, such suppression will not propagate to linker and it will issue the same warning again. But any type of global analysis tool will have this problem, so let's not try to solve it here.
