### ISSUE TITLE
NativeName on CurrentCulture is shorten on Blazor WebAssembly .NET 5.0

### ISSUE THREAD

**Issue by christianzingg** [dotnet/runtime#44739]
The following Code produces different output comparing Blazor WebAssembly 3.2.0 and 5.0.0:
```
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
var native = Thread.CurrentThread.CurrentCulture.NativeName;
Console.WriteLine(native);
```

Blazor WebAssembly 5.0.0 --> "en (US)"
Blazor WebAssembly 3.2.0 --> "English (United States)"

PS: On normal ASP-Web application running with .NET 5.0 the output is "English (United States)"

**Comment by safern** [comment]
cc: @lewing @EgorBo

**Comment by csharpfritz** [comment]
This is a regression in .NET 5 compared to all of the other .NET frameworks.  Please reconsider a patch to address this for our developers and users that don't speak English

**Comment by tarekgh** [comment]
CC @tqiu8

**Comment by lewing** [comment]
This is intensional to save space, we might possibly be able to get some of this data from the browser Intl api.  Moving to .NET 7

**Comment by csharpfritz** [comment]
I'm disappointed by the decision... but understand and will build a
work-around index that contains these values in their native language


Jeff

**Comment by lewing** [comment]
@csharpfritz I'm disappointed too but we've run out of time to solve this more generally for .NET6.

**Comment by csharpfritz** [comment]
Completely understood and I appreciate your position as we enter August


Jeff

**Comment by Jinjinov** [comment]
So, the .NET 7 ship has sailed on this issue. Can we expect this anytime soon? :)

**Comment by csharpfritz** [comment]
Can we just move this feature to an external library that is optionally included in WebAssembly deployments?

**Comment by ilonatommy** [comment]
It was not backported to 8.0 and it's available in `HybridGlobalization` mode that has its side-effects - [doc](https://github.com/dotnet/runtime/blob/65f6a080cabf4d019f0a9b16fa818d498a558e98/docs/design/features/globalization-hybrid-mode.md).
@lewing, should we backport it?
