### ISSUE TITLE
Add Stream.RequiresFlush property

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#44776]
# Proposed API:

```c#
class Stream
{
    public virtual bool RequiresFlush => true;
}
```

# Why?

For unbuffered streams such as `NetworkStream`, this will let a caller avoid calling `FlushAsync`, eliding an async state machine. See this sample:

```c#
ValueTask DoWrite(ReadOnlyMemory<byte> buffer)
{
    if(_stream.RequiresFlush)
    {
        return DoWriteSlow(_stream, buffer);
    }
    else
    {
        return _stream.WriteAsync(buffer);
    }

   static async ValueTask DoWriteSlow(Stream stream, ReadOnlyMemory<byte> buffer)
   {
       await stream.WriteAsync(buffer);
       await stream.FlushAsync();
   }
}
```

**Comment by stephentoub** [comment]
> this will let a caller avoid calling FlushAsync, eliding an async state machine

Do you have a real example?  Your example adds a virtual dispatch, and if no flushing is needed, FlushAsync can just return an already completed task; even if async/await is involved, it can still complete synchronously and without allocation.  You cited NetworkStream, but NetworkStream.FlushAsync is just implemented as:
```C#
return Task.CompletedTask;
```

**Comment by scalablecory** [comment]
The problem is specifically when `NetworkStream.WriteAsync` completes asynchronously. In this case, a continuation is needed... only to call a `FlushAsync` that will do nothing.

> Do you have a real example?

Yes. I ran into exactly the situation as my sample above. https://github.com/scalablecory/NetworkToolkit/blob/8a3a687cc9d2ac7160e71254392471e418ba8daf/NetworkToolkit/Http/Primitives/Http1Connection.cs#L450-L456

**Comment by stephentoub** [comment]
> I ran into exactly the situation as my sample above.

The linked code is discarding after the write successfully completes. As written that requires a state machine regardless of the flush, no?

**Comment by scalablecory** [comment]
> > I ran into exactly the situation as my sample above.
> 
> The linked code is discarding after the write successfully completes. As written that requires a state machine regardless of the flush, no?

No :D you can grab the buffer and then discard (which doesn't clear the buffer) before the write. It just makes for confusing code, so not doing it if it won't give a benefit here...

**Comment by stephentoub** [comment]
Right,  hence the "as written" ;-)

Is there any stream in the core libraries beyond  NetworkStream this would "help"? The rest that come to mind all buffer in some fashion. My understanding is QuicStream is going to as well.

(Purely from a naming perspective, it's also not clear what it means to require flushing. My initial interpretation of the name when I read the issue title was whether the stream had buffered data that needed to be flushed, which would result in driving the exact opposite behavior.)

If the concern is the allocation, I'd rather address that with https://github.com/dotnet/csharplang/blob/master/proposals/async-method-builders.md.

I want to make sure that any new virtual surface area on Stream really moves the needle.  I'm not convinced this does.

**Comment by GSPP** [comment]
`MemoryStream` would be unbuffered as well but flushing does nothing.

Some streams do not support flushing partial data at all. For example, some compression streams cannot "cut" their compressed output at arbitrary positions. It, therefore, seems to be a flawed notion that it is possible to reliable flush a general `Stream`.

Flushing surely is a useful concept, but it requires certain assumptions about the nature of a stream.

I wonder what real-world case stands behind the OPs request.

**Comment by stephentoub** [comment]
> MemoryStream would be unbuffered as well.

MemoryStream is entirely buffered :)  And writes always complete synchronously, so the concern around `await WriteAsync; await FlushAsync` producing another state machine doesn't manifest.

**Comment by scalablecory** [comment]
I look forward to your builder work, I agree that will be a more impactful solution.

Given this API would only solve a niche problem, and even then not make a big difference, I'll close this.
