### ISSUE TITLE
rethrown by the finalizer thread. (Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'.)

### ISSUE THREAD

**Issue by jinek** [dotnet/runtime#44770]
### Description

A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.) Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.

### Configuration

Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

### Other information

```
System.AggregateException:
System.ObjectDisposedException:
   at System.Net.Sockets.Socket.EndReceiveFrom (System.Net.Sockets, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Net.Sockets.UdpClient.EndReceive (System.Net.Sockets, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Net.Sockets.UdpClient+<>c.<ReceiveAsync>b__57_1 (System.Net.Sockets, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
```

**Comment by scalablecory** [comment]
This typically indicates you aren't awaiting the `Task` returned from `UdpClient.ReceiveAsync()`. If it's not that, can you please post some code? Thanks.

**Comment by stephentoub** [comment]
On top of what Cory cited, if this is actually crashing your program, it means you've changed away from the default behavior and opted in to unobserved task exceptions crashing.

(Also, note that UdpClient.ReceiveAsync isn't used anywhere in the core .NET libraries, so this would be coming from some code in your app or other libraries you're using.)

**Comment by jinek** [comment]
> This typically indicates you aren't awaiting the `Task` returned from `UdpClient.ReceiveAsync()`. If it's not that, can you please post some code? Thanks.

The stack trace points to UDP client, no my code in stack trace.

I've found the issue, my bad I think, sorry! I have looked at wrong container, the actual is:

```
Host (useful for support):
  Version: 3.0.3
  Commit:  c03f2fe626

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
Thus, seems this issue is related to 3.0 (not 3.1).

> On top of what Cory cited, if this is actually crashing your program, it means you've changed away from the default behavior and opted in to unobserved task exceptions crashing.
> 
> To Cory's point, it sounds like you have a UdpClient in your program, ReceiveAsync was called on it, and before that ReceiveAsync completed, the UdpClient was disposed of (or its underlying socket was disposed of), and no one paid attention to the result of the ReceiveAsync.
> 
> (Also, note that UdpClient.ReceiveAsync isn't used anywhere in the core .NET libraries, so this would be coming from some code in your app or other libraries you're using.)

The stack trace points to anonymous delegated which can be called only from ReceiveAsync method probably.
![image](https://user-images.githubusercontent.com/10516222/99342181-92990880-288b-11eb-9a65-072bb179770b.png)
But as I said, seems it is from 3.0: https://github.com/dotnet/runtime/commit/d1e7d7b3e776ee17d44f1010b186ff3558731e8d#diff-c73b3a5669ef94f4e8415a4f0fd4671a2635144b0f69dd535f6ede301e8e37d0L647

This way, for me the issue is not critical, I will just update to 3.1 (I will fix this issue description, please, feel free to close it).

**Comment by stephentoub** [comment]
> The stack trace points to anonymous method which can be called only from ReceiveAsync method probably.

The stack trace is an async callback. Someone called ReceiveAsync some time ago,  and this call stack is that operation asynchronously completing.

**Comment by jinek** [comment]
> The stack trace is an async callback. Someone called ReceiveAsync some time ago, and this call stack is that operation asynchronously completing with an exception.

Yeah, you are right, from the "return Task<UdpReceiveResult>.Factory.FromAsync(" it comes exactly pointing to anonymous method from second argument.
 
> Are you using UdpClient in your app? Are you calling ReceiveAsync?

No
![image](https://user-images.githubusercontent.com/10516222/99346669-74d0a100-2895-11eb-9819-fe555b43cc92.png)

But there are some few more libraries: NSWAG, MS Application Insights. Also few not related to networking.

At this point, I think I will override TaskScheduler to capture all tasks stack traces, so then i will match the TaskId which throws the exception.

**Comment by jinek** [comment]
@stephentoub I'm closing this issue for now. Once I have more input I would use this for reference.

**Comment by jinek** [comment]
@stephentoub @scalablecory 

Seems the issue is in **SqlClient** SNI. (but - below)
Could you please have a quick look on this: https://github.com/dotnet/SqlClient/blob/ac8bb3f9132e6c104dc3e307fe2d569daed0776f/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SSRP.cs#L168

Once timeout happened on **ReceiveAsync()).Wait(receiveTimeOutMs)** UdpClient gets disposed by **using**. Thus **UdpClient.EndReceive** gets executed in race with **Dispose()**, which leads to **ObjectDisposedException** which comes to **UnobservedTaskException** event (as nobody else waits for the task). 

Does my assumption look correct?

But I'm also opening this ticket to get attention on UdpClient and Socket.

From the perspective of the SSRP.cs author, does the code looks good?
UdpClient/Socket are claimed to be not thread-safe, is it correct?
If so, does it really nead sync code internally?
If no, how does the thread-unsafety go together with async/Task public methods? Should not Dispose wait for Async methods to finish?

Also, I've seen this check https://github.com/dotnet/runtime/blob/2f8959aa82e9c47b74aea2f3bce40ac918cbca69/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L4069 

>  // An interrupted UDP receive on Linux returns SocketError.Success and bytesTransferred zero.

Is this supposed to do anything in this issue's particular situation?

**Comment by stephentoub** [comment]
> Does my assumption look correct?

Yes,  if you use Task.Wait and the wait times out,  it will not "observe" any exception the task may later fault with. 

> does the code looks good or user of Wait(timeout) should be aware of the situation?

Ideally the code would hook up a continuation to the task after a failed wait rather than just letting the task go off into the ether, and that continuation would log the error or some such thing.  But plenty of code doesn't do that,  which is one reason UnobservedTaskException isn't fatal by default: it's an opportunity to see what errors are being ignored, potentially even using that such a global logging mechanism. So an error showing up there doesn't necessarily mean something is wrong or serve as cause for alarm; it may very well be the intention. 

> Should not Dispose wait for Async methods to finish?

No.  In fact,  on Socket,  Dispose is used explicitly as one way to interrupt all pending async operations.

**Comment by stephentoub** [comment]
Closing again as there's no issue here in dotnet/runtime. Thanks for the questions.

**Comment by jinek** [comment]
Thanks for the answers!

> No. In fact, on Socket, Dispose is used explicitly as one way to interrupt all pending async operations.

If so, should not it be OperationCancelledException instead of ObjectDisposedException? Because the description of ObjectDisposedException assumes that we are calling a method **after** dispose. Also SSRP.cs looks like it assumes cancellation of the socket.

> But plenty of code doesn't do that, which is one reason UnobservedTaskException isn't fatal by default: 

Well, even more often the code outside of tasks does not consider all possible states during execution. With that logic in mind all exceptions could be made non-fatal, whether reaching task finalizer or background thread or even entrypoint. Sure "fail fast" can not happen immediately for tasks, but neither it can do that anywhere else at runtime.

The idea of optimism in case of task finalizer is something I still sadly can not understand. 
May be there is already some topic or something I could just read or ask? 

> So an error showing up there doesn't necessarily mean something is wrong or serve as cause for alarm; it may very well be the intention.

I understand you are keeping in mind facts of rules just being violated, still the community more or less follows some conventions. 
The guideline is strict on how exceptions should be processed in case of task-based programming: https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap#exceptions
Additionally, TPL section specifically points to analogous with catching System.Exception: https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/exception-handling-task-parallel-library

Thus, it does not even matter whether an exception means error or no, it's supposed to be handled or re-thrown.
The answer "we are not compliant" is the answer, but I believe not in case of SqlClient.

**Comment by stephentoub** [comment]
> If so, should not it be TaskCancelledException instead of ObjectDisposedException?

No, the exception is correctly reflecting the fact that the object was disposed while it was in use.  It just happens that doing so also causes those operations to be torn down.
