### ISSUE TITLE
WinHttpHandler - HTTP/2 bidirectional streaming

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#44784]
WinHTTP has added support for HTTP/2 bidirectional streaming in modern versions of Windows.

Should add tests to verify it works with WinHttpHandler.

**Comment by karelz** [comment]
@JamesNK do you know how is it exposed from WinHttp?
Are there customers asking for this on .NET Core? Or on .NET Framework?

**Comment by karelz** [comment]
Based on @JamesNK analysis, this is not yet supported by WinHttp. Closing as it is not actionable.
We can reopen / create new one for consideration, once the support in the underlying WinHttp exists.

**Comment by JamesNK** [comment]
Support has been added to the underlying WinHttp component.
