### ISSUE TITLE
API proposal: control Process.FileName search path

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#44792]
## Background and Motivation

Allow to control what locations gets searched for `ProcessStartInfo.FileName` to improve:
- performance, because less locations are search
- security, because some locations can be undesired

## Proposed API

```cs
class ProcessStartInfo
{
    public FileNameSearchPath FileNameSearchPath { get; set; } = FileNameSearchPath.Default;
}
enum FileNameSearchPath
{
    Default,
    None, // FileName must be a rooted path.
    ApplicationDirectory,
    WorkingDirectory,
    EnvironmentPath
}
class Process
{
    public static Process Start(FileNameSearchPath path, string fileName);
    public static Process Start(FileNameSearchPath path, string fileName, string arguments);
    public static Process Start(FileNameSearchPath path, string fileName, IEnumerable<string> arguments);
}
```

`FileNameSearchPath` is proposed not to be a `Flags` enum because the user of this API should know where he wants to look for the file. Making it a `Flags` enum also raises the question of how the values should be ordered.

## Usage Examples

``` C#
var process = Process.Start(FileNameSearchPath.EnvironmentPath, "sleep", "100");
```

**Comment by eiriktsarpalis** [comment]
My impression is that users who are conscious about starting the incorrect files would probably just opt to using absolute paths. So perhaps it might be simpler if we added an option that requires absolute paths with search disabled?

**Comment by tmds** [comment]
> So perhaps it might be simpler if we added an option that requires absolute paths with search disabled?

When given an absolute path, no search is performed.

This is the resolution order:

https://github.com/dotnet/runtime/blob/65efefda7ccac49fc0b66b60d089ca67ac6e484a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L666-L672

Step 1 is the absolute path case.

Step 4 is a common case. It would be interesting to be able to skip 2 and 3 for performance, and security.

Implementing it yourself means users need to duplicate this logic:

https://github.com/dotnet/runtime/blob/65efefda7ccac49fc0b66b60d089ca67ac6e484a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L708-L731

**Comment by eiriktsarpalis** [comment]
> > So perhaps it might be simpler if we added an option that requires absolute paths with search disabled?
>
>When given an absolute path, no search is performed.

But perhaps we could introduce a mode that actively rejects relative paths. Alternatively we could make it only run steps 1 and 4. Exposing an enum feels like we might be overengineering, but that's just me.

**Comment by eiriktsarpalis** [comment]
Another concern is that I'm not sure this addition warrants adding three extra `Process.Start` overloads. Perhaps it makes more sense if we only expose this as a `ProcessStartInfo` property?

**Comment by tmds** [comment]
I'm going to close this, since no one showed an interested in this feature (besides me).
