### ISSUE TITLE
Enhance EmailAddressAttribute to allow empty strings to be treated as valid

### ISSUE THREAD

**Issue by IanKemp** [dotnet/runtime#44798]
## Background and Motivation

For some unfathomable reason, [`System.ComponentModel.DataAnnotations.EmailAddressAttribute`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs) treats empty strings as invalid email addresses (essentially, it also behaves as a `RequiredAttribute`). Since this behaviour was presumably defined way back in the mists of time, it has now become contractual, so cannot be changed.

This proposal modifies `EmailAddressAttribute` to allow its behaviour to be configured to treat empty strings as valid, i.e. exactly the same way it currently treats `null` strings. This is entirely opt-in, so no existing code will be affected.

You might say "why don't you just make your own custom email address validation attribute", and the answer is "because I need to return the same error messages that .NET surfaces, but those messages are defined in an `internal` class, so the only way to get them is via reflection, and that's way too much pain". I'd much rather prefer to extend `EmailAddressAttribute`, except the team refuses to unseal it due to [vague and unsubstantiated handwaves about performance](https://github.com/dotnet/runtime/issues/28011#issuecomment-495718374).

## Proposed API

```cs
namespace System.ComponentModel.DataAnnotations
{
    public enum EmailAddressValidationType
    {
        Default = 0,
        AllowEmpty = 1,
    }

    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
    public sealed class EmailAddressAttribute : DataTypeAttribute
    {
        private readonly EmailAddressValidationType _emailAddressValidationType = EmailAddressValidationType.Default;

        public EmailAddressAttribute() : base(DataType.EmailAddress)
        {
            DefaultErrorMessage = SR.EmailAddressAttribute_Invalid;
        }
        
        public EmailAddressAttribute(EmailAddressValidationType emailAddressValidationType) : this()
        {
            EmailAddressValidationType = emailAddressValidationType;
        }
        
        public override bool IsValid(object? value)
        {
            if (value == null)
            {
                return true;
            }

            if (!(value is string valueAsString))
            {
                return false;
            }

            if (_emailAddressValidationType == EmailAddressValidationType.AllowEmpty
                && value.Length == default)
            {
                return true;
            }

            // only return true if there is only 1 '@' character
            // and it is neither the first nor the last character
            var index = valueAsString.IndexOf('@');

            return
                index > 0 &&
                index != valueAsString.Length - 1 &&
                index == valueAsString.LastIndexOf('@');
        }
    }
}
```

## Usage Examples

```cs
public class MyPoco
{
    [EmailAddress]
    public string EmailAddressThatMayNotBeEmpty { get; set; }

    [EmailAddress(EmailAddressValidationType.AllowEmpty)]
    public string EmailAddressThatMayBeEmpty { get; set; }
}
```

## Alternative Designs

N/A

## Risks

Performance overhead due to the necessity of checking the `EmailAddressValidationType` every time the field/parameter/property the `EmailAddressAttribute` is applied to, is validated. Should be negligible.

**Comment by IanKemp** [comment]
Of course, it's also possible to do what `RequiredAttribute` does, and add an extra property to handle this case. But this is cleaner and more extensible, IMO.

**Comment by IanKemp** [comment]
Nobody?

**Comment by ajcvickers** [comment]
Note from triage: we are not going to change the default behavior of existing validation attributes because such changes are very likely to be breaking for some consumers. It's also problematic to change these behaviors because there is code out there that reads the annotations and reacts appropriately, rather than using the built-in validation. This code would then diverge from the behavior implemented in the attribute unless the consumer is updated, and many of the consumers are unlikely to ever be updated.

The bottom line here is that the validation attributes are what they are. It's old and not very good code. I would not recommend it going forward. At some point there probably needs to be a new validation library that is easier to evolve and maintain, but there are currently no concrete plans for this.
