### ISSUE TITLE
Move System.Threading.Event/Mutex/Semaphore support to managed code

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#44795]
These synchronization classes have little to do with the runtime and they can be implemented mostly in managed code as done in corert.

**Comment by CoffeeFlux** [comment]
Related: https://github.com/mono/mono/issues/8237
WaitSubsystem makes use of `EagerStaticClassConstruction`.

**Comment by marek-safar** [comment]
Could they be rewritten into something else or use C# module initializers instead?

**Comment by jkotas** [comment]
> WaitSubsystem makes use of EagerStaticClassConstruction.

It is because of the synchronization of static constructors depends on WaitSubsystem in CoreRT. I do not expect that you will have nor want to introduce this dependency in Mono.

It should be fine to just put the use of this attribute under `#if CORERT` ifdef.
