### ISSUE TITLE
coreclr build emits unnecessary "CI" logging output

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#448]
A build of coreclr using `src\coreclr\build.cmd` without using the "-ci" switch still generates a lot of diagnostic logging which should only be output in the CI builds, e.g.:
```
##vso[task.setvariable isSecret=False;variable=Artifacts;isOutput=True]F:\gh\runtime\artifacts
##vso[task.setvariable isSecret=False;variable=Artifacts.Toolset;isOutput=True]F:\gh\runtime\artifacts\toolset
##vso[task.setvariable isSecret=False;variable=Artifacts.Log;isOutput=True]F:\gh\runtime\artifacts\log\Debug
##vso[task.setvariable isSecret=False;variable=TEMP;isOutput=True]F:\gh\runtime\artifacts\tmp\Debug
##vso[task.setvariable isSecret=False;variable=TMP;isOutput=True]F:\gh\runtime\artifacts\tmp\Debug
##vso[task.prependpath]C:\Program Files\dotnet
##vso[task.setvariable isSecret=False;variable=DOTNET_MULTILEVEL_LOOKUP;isOutput=True]0
##vso[task.setvariable isSecret=False;variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE;isOutput=True]1
```

It seems likely this is due to the changes is https://github.com/dotnet/arcade/pull/4272

@chcosta @ViktorHofer @dotnet/runtime-infrastructure

**Comment by dagood** [comment]
This is tracked in dotnet/arcade with https://github.com/dotnet/arcade/issues/4443.

**Comment by ViktorHofer** [comment]
Closing as dupe.

**Comment by ViktorHofer** [comment]
This got fixed in the runtime repo with https://github.com/dotnet/runtime/commit/35f9b8d188098db49b18e3014a53d910b370503c.
