### ISSUE TITLE
Add API to read, set and ensure capacity of Stack<T> and Queue<T>

### ISSUE THREAD

**Issue by Enderlook** [dotnet/runtime#44801]
## Background and Motivation

Several dynamic collections offer APIs to check the capacity of their underlying arrays and offer ways to increase it if you know the necessary size ahead of time. For example `List<T>.Capacity`, `HashSet<T>.EnsureCapacity(int)` or `Dictionary<TKey, TValue>.EnsureCapacity(int)`.

This allows developers to reserve the necessary space of those collections before performing a heavy workload, and so reduce the number of times those collections must auto-resize, thus reducing GC pressure and CPU time.

However, not all the common collections offer these APIs.

## Proposed API

I propose to add the following methods:

```diff
namespace System.Collections.Generic
{
     public class Stack<T> {
+	 	public int EnsureCapacity(int capacity);
     }

     public class Queue<T>  {
+	 	public int EnsureCapacity(int capacity);
     }
}
```

## Usage Examples

``` C#
void FeedWork(T[] workload)
{
    // We know that each work item yields at least 3 results, so we can pre-resize for that
	int minCapacity = this.queue.Count + workload.Length * 3;
	this.queue.EnsureCapacity(minCapacity);

	for (T work in workload)
		for (U obj in GetResults(work))
			this.queue.Enqueue(obj);

	// I made this specific scenario to show that something like queue.EnqueueRange(IEnumerable<U>) wouldn't work here
}
```

## Risks

It increases the surface API.

**Comment by eiriktsarpalis** [comment]
Personally, I would prefer the alternative design that you propose for a couple of reasons:

* A setter that resizes buffers as a side-effect feels counterintuitive to me.
* `Capacity` is implementation detail; I don't see why we would need to expose it.

**Comment by eiriktsarpalis** [comment]
FWIW I just updated my [PriorityQueue API proposal](https://github.com/dotnet/runtime/issues/43957) to contain a `public void EnsureCapacity(int);` method.

**Comment by eiriktsarpalis** [comment]
Btw, it seems that the right signature is `int EnsureCapacity(int capacity);` (cf. https://github.com/dotnet/runtime/issues/43957#issuecomment-729727415). Would you be able to update the proposal to only include that design?

**Comment by Enderlook** [comment]
> Btw, it seems that the right signature is `int EnsureCapacity(int capacity);` (cf. [#43957 (comment)](https://github.com/dotnet/runtime/issues/43957#issuecomment-729727415)). Would you be able to update the proposal to only include that design?

I'm sorry, it's my first time proposing an API. What I'm supposed to do? Edit my initial post to use `int EnsureCapacity(int capacity);` instead of `int Capacity { get; set; }`?

**Comment by eiriktsarpalis** [comment]
> Edit my initial post to use int EnsureCapacity(int capacity); instead of int Capacity { get; set; }?

Yes please :-)

**Comment by Enderlook** [comment]
> > Edit my initial post to use int EnsureCapacity(int capacity); instead of int Capacity { get; set; }?
> 
> Yes please :-)

Done

**Comment by terrajobst** [comment]
* Looks good
* Let's also make the method on `List<T>` public

```C#
namespace System.Collections.Generic
{
    public partial class List<T>
    {
        public int EnsureCapacity(int capacity);
    }
    public partial class Stack<T>
    {
        public int EnsureCapacity(int capacity);
    }
    public partial class Queue<T>
    {
        public int EnsureCapacity(int capacity);
    }
}
```

**Comment by lateapexearlyspeed** [comment]
Hi @eiriktsarpalis, this was assigned to you but mark as up for grabs, so not sure can external guys pick to implement or not?

**Comment by eiriktsarpalis** [comment]
Hi @lateapexearlyspeed I had myself assigned during for API review purposes. Yes this would be open to external contributes, would you be interested in taking this? :-)

**Comment by lateapexearlyspeed** [comment]
@eiriktsarpalis Yes, I would try this, thanks :)
