### ISSUE TITLE
[Mono] Tracking runtime test failures on Mono interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#44810]
Runtime failures on Mono interpreter:
- [x] #38826 [Mono Interp] CoreCLR tests failed with Mono interpreter: Interop/NativeLibrary/API/NativeLibraryTests

(More issues to be added)

**Comment by SamMonoRT** [comment]
The associated tracking failure is fixed via https://github.com/dotnet/runtime/pull/41098. We also a newer Interpreter failure tracking issue with more details - https://github.com/dotnet/runtime/issues/54383
