### ISSUE TITLE
Bootstrapper dialog "Download .NET" improvement

### ISSUE THREAD

**Issue by AnakinSklavenwalker** [dotnet/runtime#44820]
Hey, 
not sure where exactly to put this or whether this has been reported already...

When trying to run a .NET 5 WPF application on a clean installed Windows 10 with no .NET installed, a bootstrapper dialog pops up and tells me to download .NET. While I generally appreciate this dialog it lacks to tell me which .NET runtime i need to download (x64 or x86). 

In my setup i have an WPF application with the following publish settings:
-  Config: `Release| Any CPU`
- Target framework: `net5.0-windows`
- Target runtime: `win-x86`
- Deployment mode: `framework-dependant`
- Produce single file: checked

As you can see, I targeted x86. However my guess is the following will happen in almost every case:  
1. A user seeing the bootstrapper dialog as it is now, will click the 'install now' button. 
2. A browser opens and the user can choose to download the runtime installer (x64 or x86).
3. **Because the user knows his Windows is running at x64, he will choose that option.** 
4. He installs the runtime and tries to run the application again.
5. The same bootstrap dialog appears again => User is frustrated 😢 

I could imagine the following solutions to this problem:
a) Update the dialog and tell the user which runtime exactly to download
b) The x64 runtime should be able to run apps which target x86

I could imagine that solution b) is probably not easy if ever possible to solve but from an end-user perspective i think it's the better option.

**Comment by Symbai** [comment]
Please post your feedback into the existing issue instead of creating a new one. And while you do, you might want to upvote it to show your interest #3816

**Comment by jeffschwMSFT** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/3816
