### ISSUE TITLE
MethodCallExpression.Update should be annotated to accept nullable object

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#44821]
[MethodCallExpression.Update](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/MethodCallExpression.cs#L62)'s `object` parameter is annotated as non-nullable; but it's perfectly legal for MethodCallExpression to have no object (this represents a static method call).

/cc @smitpatel @ajcvickers

**Comment by cston** [comment]
Also reported in https://github.com/dotnet/runtime/issues/43566.

**Comment by roji** [comment]
Thanks @cston, will close this as a dup.

**Comment by roji** [comment]
Or will let you do that since you just put it in the milestone.

**Comment by cston** [comment]
> will close this as a dup.

Let's leave this issue open for now since it is more specific.
