### ISSUE TITLE
System.Linq DefaultIfEmpty result is being analyzed as not nullable but can be null

### ISSUE THREAD

**Issue by jons-aura** [dotnet/runtime#44824]
**Version Used**: 
VS 16.8.1 project target framework .NET Standard 2.1

**Steps to Reproduce**:

1. 
```                IQueryable<ReturnType> collectionwithextradata = _dbContext.Table
                    .SelectMany(x => x.NavigationProperty.DefaultIfEmpty<>(), (x, y) =>
                    new ReturnType()
                    {
                        BaseProp1 = x.BaseProp1,
                        NavProp1 = y.NavProp1.ExtraDataProp,
                    });
```
2. No null possible warning is given about y.NavDrop1.ExtraDataProp and when hovering over y in the IDE it says it is "not null here"
3. If I add an explicit type annotation of <NavPropType?> to the DefaultIfEmpty I do get nullability warnings but I also get IDE0001 name can be simplified on the type annotation.

**Expected Behavior**:

DefaultIfEmpty values should be treated as potentially nullable

**Actual Behavior**:

DefaultIfEmpty values are treated as not null.

**Comment by stephentoub** [comment]
.NET Standard isn't annotated for nullable reference types at all (this isn't specific to LINQ).  Thus the whole framework surface area will be "oblivious".
cc: @terrajobst

**Comment by jons-aura** [comment]
@stephentoub Is it possible to update netstandard2.1 or is that a "frozen" target? If the latter and there's already a task to add annotations to whatever the next netstandard revision will be there's probably no point in leaving this open.

**Comment by stephentoub** [comment]
Will close as a dup of https://github.com/dotnet/standard/issues/1118. Thanks.
