### ISSUE TITLE
Reduce CoreCLR build times in the official build

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#44848]
As we look towards improving the official build times for the repo, CoreCLR has become the new long pole in the build.

Here's a few ideas that @ViktorHofer and I have come up with along with their likely time improvements. These would be **official build only** changes.

- [ ] Don't build the superpmi/mcs family of tools (Save 1-1.5 minutes)
- [x] Don't build the paltests (Save 2 minutes)
- [x] Don't build test hosts like CoreConsole (Save a few seconds). This does not include CoreRun since the diagnostics team still uses it
- [ ] Don't build crossgen (Save 4+ minutes). The product needs to support crossgen2 exclusively before we can do this.

**Comment by jkotas** [comment]
> Don't build test hosts like CoreConsole

This can be just deleted. I do not think anybody is using it.

**Comment by tommcdon** [comment]
@trylek @agocke

**Comment by ViktorHofer** [comment]
> Don't build test hosts like CoreConsole (Save a few seconds). This does not include CoreRun since the diagnostics team still uses it

Are we in dotnet/runtime still using CoreRun? dotnet/performance is a consumer of CoreRun but we might be able to switch to dotnet there.

**Comment by jkoritzinsky** [comment]
Yes, the runtime tests still use CoreRun.

**Comment by jkoritzinsky** [comment]
And the internal diagnostics tests still use CoreRun to my knowledge.

**Comment by ViktorHofer** [comment]
Is there any desire in getting them off CoreRun or is there value in using it over the dotnet host?

**Comment by jkoritzinsky** [comment]
@hoyosjs can chime in here about the CoreRun usage in the diagnostics tests. He knows better than I.

**Comment by trylek** [comment]
I guess we should keep in mind that, as according to the issue description this is planned to be an official build-only change, we're currently running no runtime tests as part of official builds so that I presume that corerun, if needed, is only needed for some cross-repo interactions. Please correct me if I'm wrong about these assumptions.

**Comment by ViktorHofer** [comment]
You are right that this issue focus mostly on official builds only. Still, I think it doesn't harm to ask these questions somewhere.

**Comment by hoyosjs** [comment]
There's no desire to run outside of corerun as far as I know. The dotnet host adds a bunch of complexity with the hostfxr and other nuanced behavior (multilevel lookup and akin). We usually want the core_root to just load dll's in it, and that's what corerun does.

**Comment by trylek** [comment]
@ViktorHofer - I'm certainly not complaining about clarifying these questions, I just wanted to point out that removing corerun from official builds should be possible even without resolving them.

**Comment by agocke** [comment]
I believe the initial work here has been completed. There might be small future improvements, but we will track those as needed.
