### ISSUE TITLE
TimeZoneInfo.GetSystemTimeZones produces unexpected results in Blazor WASM for .NET 5

### ISSUE THREAD

**Issue by andersme** [dotnet/runtime#44840]
### Describe the bug
When using TimeZoneInfo.GetSystemTimeZones method in Blazor WASM on .NET 5, I am getting a strange list returned.

![image](https://user-images.githubusercontent.com/5560275/99460962-1552af80-28ee-11eb-967a-ae6c9a71261a.png)

- The list is much shorter than I would expect, and appears to be missing many time zones. I even show, in my example, my current time zone, which is missing from the list.
- The display names are not very good and not something I would want to show an end user.

Is there any other method to return all available time zones that I am not aware of?

### To Reproduce
Use TimeZoneInfo.GetSystemTimeZones inside of a Blazor WASM page with .NET 5.

**Comment by lewing** [comment]
Some timezone information has been reduced or removed to save size in the deployed app. There are some options to resolve this but we'd be interested to know what use case you are trying to support?

**Comment by andersme** [comment]
I'm currently just trying to allow users to select a time zone for their company in my application I'm building. How can I get the full time zone information, if it's not enabled by default?

**Comment by rogihee** [comment]
See [https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization). 

Note that this will significantly increase your download size. I think there is still some work with sharding. 

I ran into the same issue, I just generate a list on the server and let the user pick from there in the edit form. For date time formats and utc offset, I keep a user model on a singleton service that updates the format for other services for displaying dates, user avatar menu etc.

**Comment by andersme** [comment]
> See [https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization). 
> 
> Note that this will significantly increase your download size. I think there is still some work with sharding. 
> 
> I ran into the same issue, I just generate a list on the server and let the user pick from there in the edit form. For date time formats and utc offset, I keep a user model on a singleton service that updates the format for other services for displaying dates, user avatar menu etc. This user model is updated after login.

Interestingly enough, I tried the documentation you referenced there, and it doesn't seem to fix the issue. Perhaps I'm doing something wrong.

It is really unfortunate that we have to roll our own time zone lists but I guess that's the only viable option here.

**Comment by lewing** [comment]
@tqiu8 can you take a look at this.  It seems like the list filtering is causing issues and we should possibly revisit that choice.

**Comment by tqiu8** [comment]
@lewing the list filtering is definitely limiting the system timezones; however for the problem of the display names I believe it's because the StandardName might've been used instead. I can disable the filtering.

**Comment by lewing** [comment]
@tqiu8 I suspect the name is coming from icu and has been removed there but please verify.  It's possible we can fix that part with the included data

**Comment by lewing** [comment]
@andersme finding the right size/feature/time balance is difficult but feedback is appreciated.

If it is of any help we can point you to the parts of the build process that construct this data.

**Comment by andersme** [comment]
@lewing I simply want the option to be able to get the complete list of time zones. I understand that this may cause additional load size, but that's okay.

**Comment by tqiu8** [comment]
The DisplayName problem is described in this issue: #16232

**Comment by flacodirt** [comment]
Here is the complete output from my client side logging using v5.0.2, it produced 14 time zones. The same test on server side produced 140 time zones.

```
foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
     _logger.LogInformation(z.Id);
```
1. America/Los_Angeles
1. America/St_Johns
1. America/Argentina/Catamarca
1. America/Sao_Paulo
1. UTC
1. Europe/London
1. Europe/Lisbon
1. Europe/Berlin
1. Africa/Tripoli
1. Africa/Nairobi
1. Europe/Moscow
1. Australia/Perth
1. Australia/Sydney
1. Pacific/Tongatapu

**Comment by mattjohnsonpint** [comment]
I believe this issue has been resolved for .NET 6 with #48931 and #50650

**Comment by nssidhu** [comment]
currentTimeZone = TimeZoneInfo.Local;
Even this is returning Incorrect Result ( I am in Chicago), but this returns 'America/Los_Angeles'.

So it means i will have to wait to .NET 6 is released, don't want to use Preview version as this is problem occurring in production, will use some other method to fix it. 
Looks like everything related to Timezone is broken in .NET 5

**Comment by mattjohnsonpint** [comment]
@nssidhu - That's a slightly different area than what this issue is about.  However, I assume you are still talking about Blazor WASM?  If so, `TimeZoneInfo.Local.Id` should be the same as would be given by `Intl.DateTimeFormat().resolvedOptions().timeZone` in JavaScript (which reflects your system time zone settings).  Please check and let us know if they differ.

Note, this part of .NET on WASM works the same way in .NET 5 and 6.  There's some minor refactoring between, but in both cases the time zone is read using the ECMAScript `Intl` API.

**Comment by nssidhu** [comment]
Confirming that both are giving the same value 'America/Los_Angeles'.
Next question why am getting incorrect value ? i expect to get CST- Chicago Time Zone

**Comment by nssidhu** [comment]
Hmm, currentTimeZone = TimeZoneInfo.Local; this turned out to be system time of the VM that code was running on.

**Comment by CoffeeFlux** [comment]
It seems like this is fixed for net6, so closing. If there's anything actionable left, let me know and I can reopen or create a new issue.
