### ISSUE TITLE
Remove assumption that Array has to implement all interfaces for MonoVM

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44859]
In Mono class setup we hardcode dependency on 3 interfaces which are rarely needed and could be removed if we didn't have runtime dependency.

We should fix the metadata loaded to not require the presence of

- System.Collections.Generic.IList`1
- System.Collections.Generic.IReadOnlyCollection`1
- System.Collections.Generic.IReadOnlyList`1

Or any of their individual methods

https://github.com/dotnet/runtime/blob/df4c719cd3cd82e0f00d755667ec8b5c3cc4d364/src/mono/mono/metadata/class-init.c#L3717-L3732

@lambdageek

**Comment by lambdageek** [comment]
@marek-safar just to make sure I understand.  What we want is something like:
* ILLinker runs and determines that, for example ``System.Collections.Generic.IList`1`` is not used anywhere and will be trimmed away
* App runs on a trimmed BCL and creates some array type
* Runtime tries to get ``System.Collections.Generic.IList`1`` sees that it's not present and silently doesn't implement the interface for the array

Is that right?

**Comment by marek-safar** [comment]
> Is that right?

Correct. We could treat all the interfaces Array's implement this way if it'd make the code simpler but the 3 above should certainly be made optional.

**Comment by marek-safar** [comment]
One thing I didn't cover is that it should also work with the interface members so it should be possible to run with for example empty `IReadOnlyCollection` interface. The case where someone casts the interface but dispatches over it.

**Comment by lambdageek** [comment]
@marek-safar Do we have a scenario that will exercise this?  Maybe a wasm sample with the right flags will run the linker aggressively enough?

**Comment by marek-safar** [comment]
It should kick in if your remove https://github.com/dotnet/runtime/blob/202f6e1deede57ad127445256cd1d5c2bbad136f/src/mono/netcore/System.Private.CoreLib/src/ILLink/ILLink.Descriptors.xml#L485-L489 (it would be nice to remove it as part of the PR)
