### ISSUE TITLE
New ReadOnlySpan constructor for SecureString

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#44873]
## Background and Motivation

In PowerShell project we sometimes create a `SecureString` from a string, e.g. in [SecureStringCommands](https://github.com/PowerShell/PowerShell/blob/9ca6be1d6343334f948b710ed6d01ddd9d442419/src/Microsoft.PowerShell.Security/security/SecureStringCommands.cs#L364-L365), by using the following pattern:

```csharp
SecureString ss = new SecureString();
foreach (char t in password)
    ss.AppendChar(t);
```

Unfortunately, it appears that every call to `AppendChar` results in an allocation, which I suppose we could avoid with the following unsafe code:

```csharp
SecureString ss;
fixed (char* pChars = &password.GetPinnableReference())
    ss = new SecureString(pChars, password.Length);
```

However the constructor `SecureString(char* value, int length)` creates a `ReadOnlySpan` to initialize from, so why not expose a constructor that takes a `ReadOnlySpan`?

## Proposed API

```diff
namespace System.Security
{
+    public SecureString(ReadOnlySpan<char> value) {
+        Initialize(value);
+    }
```

**Comment by stephentoub** [comment]
Thank you for the suggestion, but we aren't investing in SecureString and we don't want to increase its usage.  In fact, we're moving in the opposite direction: https://github.com/dotnet/designs/pull/147.  The example you highlight is a good example of why: it's populating a SecureString from a string, which obviates the benefit of SecureString in the first place.
