### ISSUE TITLE
Unable to create instance of `System.Drawing.Bitmap` on net5.0

### ISSUE THREAD

**Issue by duskembayev** [dotnet/runtime#44878]
My project is referencing nuget-package System.Drawing.Common (5.0.0) and targeting framework `net5.0`.
There are exception throws on creating an instance of `System.Drawing.Bitmap` type: `PlatformNotSupportedException`.

If I change TargetFramework to netcoreapp3.1 everything works properly.

**Comment by safern** [comment]
Thanks, @duskembayev for reporting. Let me try it out and I'll get back to the issue.

**Comment by safern** [comment]
@duskembayev I just tried this with the following sample code:

```cs
static void Main(string[] args)
{
   using Bitmap bm = new Bitmap(10, 10);
   bm.Save("foo.png", ImageFormat.Png);
}
```

and it worked just fine, it saved the .png correctly. This was on osx using System.Drawing.Common (5.0.0) and targeting `net5.0`.

Would you mind sharing a .zip with a minimal repro, and more information, like the OS, and steps to reproduce the bug?
