### ISSUE TITLE
Non-open source code in System.Security.Cryptogrphy.Algorithms

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#44884]
A copyright/license scanner just flagged this comment for me:

https://github.com/dotnet/runtime/blob/38259c83703dbf6df50c814f7504e7073b5ffaef/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/SHAHashProvider.Browser.cs#L124-L130

AFAIK, this runs counter to the "Free Redistribution" and/or "Source Code" principles of the [Open Source Definition](https://opensource.org/osd).

**Comment by omajid** [comment]
cc @leecow @dleeapho

**Comment by stephentoub** [comment]
cc: @richlander

**Comment by omajid** [comment]
Looks like it was introduced by https://github.com/dotnet/runtime/pull/40486.

cc @akoeplinger

**Comment by leecow** [comment]
So folks are clear on the urgency, this will block the .NET 5 release in RHEL.

**Comment by richlander** [comment]
We'll take a look.

**Comment by omajid** [comment]
I think #44982 fixed this. Is there anything else that needs to be done?

**Comment by bartonjs** [comment]
> I think #44982 fixed this. Is there anything else that needs to be done?

I don't see RSA's copyright statement anywhere in the current code base... and since you're the one who opened this (and I had the same question) I'm going to call it closed :)

**Comment by omajid** [comment]
@bartonjs I just realized that this affects 5.0 branch as well. Should I open a separate issue for that?

**Comment by akoeplinger** [comment]
Backport PR for release/5.0: https://github.com/dotnet/runtime/pull/47132
