### ISSUE TITLE
IDataRecord.GetBytes/GetChars should be annotated to allow a null buffer

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/runtime#44886]
The `buffer` parameter of `GetBytes`/`GetChars` should be annotated to allow null values. Currently in .NET 5.0.0 they are annotated to not allow null values (see https://github.com/dotnet/runtime/pull/38810/).

The documentation states:

> If you pass a buffer that is `null`, `GetChars` returns the length of the field in characters.

Source: https://docs.microsoft.com/en-us/dotnet/api/system.data.idatarecord.getchars?view=net-5.0#remarks

In SqlClient the implementation does indeed conform to the documentation: https://github.com/dotnet/SqlClient/blob/f0572f3e9990b391d6102911fe12223e748e117b/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlDataReader.cs#L1663

**Comment by stephentoub** [comment]
cc: @roji

**Comment by roji** [comment]
Yeah, this is an incorrect annotation. I've submitted #44938 to fix this; technically this is a breaking change in case someone has implemented IDataRecord directly (as opposed to via DbDataReader).

Listed this in #21202 for documentation.
