### ISSUE TITLE
RyuJIT call optimization and aggressive inlining with known generic types 

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#4489]
This probably will end up in the future releases wishlist, but it something that has been looking forward for a long time already.

Lets say that we have this code:

``` csharp
       public class Executer<T> where T : ICalls
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Execute(T instance)
            {
                instance.Execute();
            }
        }
```

And we have the following instances:

``` csharp
        private readonly Executer<ClassCalls> _classCalls = new Executer<ClassCalls>();
        private readonly Executer<ICalls> _interfaceCalls = new Executer<ICalls>();
        private readonly Executer<SealedClassCalls> _sealedCalls = new Executer<SealedClassCalls>();
```

Now we would expect that the call for _classCalls.Execute(x) would be different than for _interfaceCalls(x). Apparently that is not the case, the JIT stops at the first level even if have the complete information to emit highly optimized code for that call-site.

Now, supposed the implementation is:

``` csharp
        public class ClassCalls : ICalls
        {
            public static int i;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public void Execute()
            {
                i = 0;
                i++;
            }
        } 
```

There is no way that the JIT would inline that code, even if for all purposes it is safe to do so.

The scenario for this pattern is pretty common in high performance code where the calls are very small, in tight loops but must be able to handle more than a single type... An example is a BitVector with variants for MemoryMappedBitVector, UnsafeBitVector, LongBitVector and so on. Operations tend to be very small and executed in very tight loops.

 Today we either need a different codepath for each one, or pay the call tax.

category:cq
theme:inlining
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
At runtime there's no way for the jit to deduce the exact type of instance members at jit time; all the jit knows is that the type is one of the exact instantiations of the the shared type Executer`1.

If it turns out that the instance the member is always just one or a handful of types then via profiling the jit can discover which type is most likely and guess for that, and perform guarded devirtualization and subsequent inlining. This can be seen with the changes for class profiling linked above; eg 
```asm
; Assembly listing for method Runtime4489:UseSealedCalls():this
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; Tier-1 compilation
; optimized code
; optimized using profile data
; rsp based frame
; partially interruptible
; with IBC profile data, edge weights are valid, and fgCalledCount is 15122173
; invoked as altjit
; Final local variable assignments
;
;  V00 this         [V00,T00] (  4,  4   )     ref  ->  rcx         this class-hnd
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V02 tmp1         [V02,T02] (  2,  4   )     ref  ->  rcx         ld-addr-op class-hnd "Inlining Arg"
;  V03 tmp2         [V03,T01] (  3,  4   )     ref  ->  rcx         "guarded devirt this temp"
;* V04 tmp3         [V04    ] (  0,  0   )     ref  ->  zero-ref    class-hnd exact "guarded devirt this exact temp"
;  V05 tmp4         [V05,T03] (  2,  4   )     ref  ->  r11         class-hnd "Inlining Arg"
;
; Lcl frame size = 40

G_M52712_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
						;; bbWeight=1    PerfScore 0.25
G_M52712_IG02:              ;; offset=0004H
       4C8B5930             mov      r11, gword ptr [rcx+48]
       488B4918             mov      rcx, gword ptr [rcx+24]
       45391B               cmp      dword ptr [r11], r11d
       49BBE8C335C4F87F0000 mov      r11, 0x7FF8C435C3E8
       4C3919               cmp      qword ptr [rcx], r11
       7517                 jne      SHORT G_M52712_IG04
       48B9ACA232C4F87F0000 mov      rcx, 0x7FF8C432A2AC
       4533DB               xor      r11d, r11d
       448919               mov      dword ptr [rcx], r11d
       FF01                 inc      dword ptr [rcx]
						;; bbWeight=1    PerfScore 15.75
G_M52712_IG03:              ;; offset=0030H
       4883C428             add      rsp, 40
       C3                   ret      
						;; bbWeight=1    PerfScore 1.25
G_M52712_IG04:              ;; offset=0035H
       49BB580505C4F87F0000 mov      r11, 0x7FF8C4050558
       48B8580505C4F87F0000 mov      rax, 0x7FF8C4050558
       FF10                 call     qword ptr [rax]ICalls:Execute():this
       EBE3                 jmp      SHORT G_M52712_IG03
						;; bbWeight=0    PerfScore 0.00

```
In an AOT scenario without PGO, and if one can impose suitable restrictions (no reflection, etc) it might be possible for RTA or similar to deduce that only one type can possibly be assigned to the instance members.

Going to keep this open and in future, but once PGO is a bit further along may come back and close this one.

**Comment by AndyAyersMS** [comment]
Now that dynamic PGO is on by default, I think we can indeed close this.
