### ISSUE TITLE
Incorrect codegen with multiple returns of a field of a Nullable or struct type

### ISSUE THREAD

**Issue by sfoslund** [dotnet/runtime#44895]
---
**Issue moved from dotnet/sdk#14535**
- Please respond to @dale-personal.

---

_From @dale-personal on Friday, November 13, 2020 2:54:27 PM_

Here is a repo which reproduces the issue:

https://github.com/dale-personal/net5-issue

The code in question functions as expected for a number of iterations, then starts producing unexpected results.

**Comment by sfoslund** [comment]
---
**Issue moved from dotnet/sdk#14535**
- Please respond to @sfoslund.

---

_From @sfoslund on Wednesday, November 18, 2020 9:11:00 PM_

@dale-personal can you please give more detail on what the unexpected results are?

**Comment by sfoslund** [comment]
---
**Issue moved from dotnet/sdk#14535**
- Please respond to @dale-personal.

---

_From @dale-personal on Wednesday, November 18, 2020 9:25:14 PM_

Sure,  I've created a repo which reproduces the issue:
https://github.com/dale-personal/net5-issue/blob/main/test.cs

In the test provided, given enough loop iterations, the behavior of this line changes
if (_default != null && _default.Value.HasValue) return _default.Value.Value;

_default.Value.HasValue is false, while at the same time _default.Value.Value = "test"

**Comment by JulieLeeMSFT** [comment]
CC @briansull

**Comment by briansull** [comment]
Taking a look

**Comment by briansull** [comment]
I am testing a fix for this issue

**Comment by sandreenko** [comment]
Will the fix for this issue go into 5.0?

**Comment by briansull** [comment]
It could be ported to `release\5.0` if it meets the bar

**Comment by JulieLeeMSFT** [comment]
Bruce to check .NET 3.1 if the issue repos.

**Comment by briansull** [comment]
The test case passes using .NET 3.1

**Comment by briansull** [comment]
This is already fixed in 6.0 by #45134

**Comment by JulieLeeMSFT** [comment]
> This is already fixed in 6.0 by #45134

Good. Let's keep this open until .NET 5 fix is released in 5.0.3.

**Comment by briansull** [comment]
Fixed in 5.0.3 with #45989

**Comment by JulieLeeMSFT** [comment]
> This is already fixed in 6.0 by #45134

@briansull did you mean that this is fixed in 6.0 by #45284?
