### ISSUE TITLE
Investigate using server GC for the crossgen2 process

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#44890]
See https://github.com/dotnet/runtimelab/pull/365 where we saw 10% improvement in wallclock time of the native AOT compiler using one weird trick.

**Comment by mangod9** [comment]
Thanks for the FYI.. should be easy to test this.

**Comment by nattress** [comment]
Looks like we see about the same improvement for R2R compilation. I think it's worth adding to CG2 for sure. Results for a few assemblies of different sizes from the perf repo CG2 throughput tests:

**Crossgen2 with Workstation GC**

Crossgen2 Throughput - Single - System.Private.CoreLib
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |2968.150 ms    |2904.128 ms    |3019.267 ms
Loading Interval     |446.778 ms     |441.450 ms     |454.828 ms
Emitting Interval    |656.501 ms     |629.608 ms     |676.116 ms
Jit Interval         |1438.971 ms    |1407.522 ms    |1487.281 ms
Compilation Interval |2876.967 ms    |2809.552 ms    |2930.425 ms
Time on Thread       |12196.478 ms   |12009.356 ms   |12383.884 ms

Crossgen2 Throughput - Single - System.Private.Xml
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |2477.893 ms    |2449.258 ms    |2514.033 ms
Loading Interval     |410.115 ms     |406.687 ms     |416.254 ms
Emitting Interval    |602.758 ms     |582.144 ms     |626.338 ms
Jit Interval         |1074.002 ms    |1050.137 ms    |1094.699 ms
Compilation Interval |2389.227 ms    |2361.359 ms    |2425.159 ms
Time on Thread       |9667.185 ms    |9593.862 ms    |9793.893 ms

Crossgen2 Throughput - Single - System.Net.Sockets
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |678.295 ms     |674.031 ms     |683.135 ms
Loading Interval     |295.137 ms     |294.466 ms     |296.066 ms
Emitting Interval    |116.615 ms     |115.846 ms     |117.513 ms
Jit Interval         |101.722 ms     |100.027 ms     |103.569 ms
Compilation Interval |589.838 ms     |586.865 ms     |591.610 ms
Time on Thread       |1187.332 ms    |1168.075 ms    |1212.920 ms

-------------------------------------
**Crossgen2 with Server GC**

Crossgen2 Throughput - Single - System.Private.CoreLib
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |2485.138 ms    |2420.098 ms    |2587.462 ms
Loading Interval     |426.304 ms     |420.618 ms     |433.362 ms
Emitting Interval    |590.934 ms     |547.767 ms     |668.075 ms
Jit Interval         |1078.130 ms    |1033.550 ms    |1112.610 ms
Compilation Interval |2387.454 ms    |2323.458 ms    |2494.229 ms
Time on Thread       |12577.491 ms   |12251.630 ms   |12981.518 ms

Crossgen2 Throughput - Single - System.Private.Xml
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |2087.871 ms    |2057.396 ms    |2125.784 ms
Loading Interval     |394.931 ms     |393.586 ms     |395.844 ms
Emitting Interval    |531.136 ms     |502.894 ms     |598.221 ms
Jit Interval         |780.641 ms     |766.937 ms     |806.737 ms
Compilation Interval |1996.394 ms    |1966.269 ms    |2036.995 ms
Time on Thread       |9843.374 ms    |9536.159 ms    |10299.448 ms

Crossgen2 Throughput - Single - System.Net.Sockets
Metric               |Average        |Min            |Max
---------------------|---------------|---------------|---------------
Process Time         |657.773 ms     |654.946 ms     |660.216 ms
Loading Interval     |295.251 ms     |293.472 ms     |296.515 ms
Emitting Interval    |118.354 ms     |117.338 ms     |119.441 ms
Jit Interval         |82.739 ms      |82.017 ms      |83.945 ms
Compilation Interval |566.197 ms     |563.585 ms     |568.008 ms
Time on Thread       |1171.949 ms    |1143.426 ms    |1190.829 ms

**Comment by mangod9** [comment]
looks good, ship it :)
