### ISSUE TITLE
No assets are getting signed

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#44906]
No runtime dll is getting signed and no package is getting signed either. This includes the different variants of the DAC.

@jkoritzinsky @mmitche @dotnet/dotnet-diag

**Comment by hoyosjs** [comment]
For the DAC, it looks like `_DryRun` is getting set to true because `OfficialBuild` is not getting passed. @jkoritzinsky @ViktorHofer do we expect to not be signing other assets right now? PostBuild is still set to false

**Comment by jkoritzinsky** [comment]
Yes we expect to not be signing other assets at the moment. The DAC, DBI, and CrossOsDiag packages should be signed now. If those aren't being signed (which is what it sounds like) then we have a bug in the infra.
