### ISSUE TITLE
Publish and run a C# Net5.0 Console-app on Debian 10.5 (ARM 32bit)

### ISSUE THREAD

**Issue by GW-Lab** [dotnet/runtime#44900]
**Version Used**: 
16.9.1

**Steps to Reproduce**:

1. Create a Net5.0 c# console app (Release any-cpu)
2. Publish de console app to a folder (pameters: realease | Any CPU, Net5.0, self-contained, linux-arm, path...)
3. On the host (debian 10.5)  the console app is recognised as a **Shared-library**
4. The console app will not run/execute

**Expected Behavior**:
The console app will run/execte on debian 10.5 (32bit)

**Actual Behavior**:
The console app will not run/execte on debian 10.5 (32bit)

note:
If you try the same and target Net-core 3.1.9 instead of Net5.0 the console app is recognised as a **Executable** and wil run/execute without any problems

**Comment by am11** [comment]
> The console app will not run/execute

It will, please try it on target ARM system.

> On the host (debian 10.5) the console app is recognised as a **Shared-library**

If you are using `file(1)` to determine that, and version is < 5.33, then it shows output like:

```sh
bin/Release/net5.0/linux-arm/publish/myApp:
ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked ..
```
with v5.33 (or compile the latest v5.39: https://github.com/file/file/releases/tag/FILE5_39), then the libmagic that compiles alongside recognizes the PIE executable format correctly:

```sh
bin/Release/net5.0/linux-arm/publish/myApp:
ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked
```

This `myApp` just worked fine for me on Ubuntu arm32v7 system.

The reason is that, the native code configuration has been unified in 5.0 from three source repositories (coreclr, corefx and core-setup), and we compile all executable components with `position-independent executable` (PIE) flags, when supported by the compiler toolchain (and target platform).

**Comment by GW-Lab** [comment]
am11
i use the RaspberryPI (Debian 10.5 buster arm32bit) NOOBS version  3.5.0 and in de desktop GUI file properties  gives shared-library for the Net5 app and Executable for the Net core 3.1.9 app.

and the **Net5** app will **not** run.

**Comment by am11** [comment]
Maybe run the app from shell to make sure it is not the issue with older version of desktop GUI environment in use (which could be using `file(1)` v5.32 or lower)?

I ran this in host's shell:

```sh
$ dotnet new console -n myApp
$ dotnet publish -c Release --self-contained -r linux-arm myApp/
$ tar czf myApp.tar.gz myApp/bin/Release/net5.0/linux-arm/ publish/
```

then transferred `myApp.tar.gz` to arm system, and ran from shell:

```sh
$ tar xzf myApp.tar.gz
$ publish/myApp
```

If you try these steps with your RaspberryPI, does it print `Hello World!`?

**Comment by GW-Lab** [comment]
I will try -:)

**Comment by GW-Lab** [comment]
On the Host i have file(1) v5.35 and on the app it returns :

ConsoleApp1: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=5ab4a61bc9b8bb7807fe8012d2cd67adfddc8d73, stripped

ps thanks for helping me out.

**Comment by am11** [comment]
Host = machine where application was compiled (requires .NET SDK)
Target = machine where application will run (does not require the SDK)

so I guess our definitions mismatched. 🙂

**Comment by GW-Lab** [comment]
Version Used:
16.9.1

Steps to Reproduce: (on a Windows 10 machine)

Create a Net5.0 c# console app (Release any-cpu)
Publish de console app (with VS community 16.9.1 build/publish) to a folder (pameters: realease | Any CPU, Net5.0, self-contained, linux-arm, path...)
On the host (debian 10.5) the console app is recognised as a Shared-library
The console app will not run/execute

sorry for the confusion.

**Comment by am11** [comment]
Were you able to test the above steps from command line (without VS) and executed the app on RaspberryPI from shell (without GUI)?

**Comment by GW-Lab** [comment]
It prints Hello World!? -:)

**Comment by am11** [comment]
Thanks for trying it out. Then it is the problem with desktop file manager not able to execute modern (secure) binary by double-clicking it. You could try upgrading the desktop environment to see if the problem persists or, if feasible, switch to a different file manager that supports running the (pie executable) binaries that way.

**Comment by GW-Lab** [comment]
Than i have the question why is it that a Net core 3.1.9 app is running and a Net 5.0 is not.

**Comment by am11** [comment]
This is because netcoreapp3.1 apps are not PIE executables:

```sh
$ file --version
file-5.39
magic file from /usr/local/share/misc/magic

$ file /myApp/bin/Release/netcoreapp3.1/linux-arm/publish/myApp
/myApp/bin/Release/netcoreapp3.1/linux-arm/publish/myApp:
ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked ...
```
net5.0 apps are:
```sh
$ file /myApp/bin/Release/net5.0/linux-arm/publish/myApp
bin/Release/net5.0/linux-arm/publish/myApp:
ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked
```

**Comment by GW-Lab** [comment]
OK thanks for the help.
With this knowledge i tray to find a practical solution.
