### ISSUE TITLE
Remove the nested src folder in src/coreclr

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#44907]
Now that runtime tests are moved out of coreclr, removing the nested src folder should be fine? During consolidation we did the same for libraries, installer and mono.

cc @jkotas @dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
A potential candidate for Decembers batched infra rollout?

**Comment by trylek** [comment]
Well, it took me about two months to move the tests around. I suspect that promising the removal of the src folder from coreclr would just end up as a botched December infra rollout. I guess I'm going to use part of the "post-thanksgiving" period with reduced traffic by the end of the year to experiment with this and ideally come up with a January or February infra rollout in this direction.

**Comment by ViktorHofer** [comment]
Already completed in master.
