### ISSUE TITLE
Identify more places to apply [SupportedOSPlatform] and [UnsupportedOSPlatform] attributes for existing platforms

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#44916]
In .NET 5.0, we annotated APIs that were known to be [supported only on Windows](https://github.com/dotnet/designs/blob/main/accepted/2020/windows-specific-apis/windows-specific-apis.md), as well as APIs [unsupported on Browser](https://github.com/dotnet/designs/blob/main/accepted/2020/blazor-unsupported-apis/blazor-unsupported-apis.md). As we expand our platforms in .NET 6.0, we need to review our APIs to identify more places to apply the [`[SupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.supportedosplatformattribute) and [`[UnsupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute) attributes as needed for our existing platforms, allowing the [Platform Compatibility Analyzer](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer) to identify usage of these APIs on unsupported platforms.

This additional pass over applying attributes could result in annotating APIs that are either specific to or unsupported on Windows, Linux, and Browser.  We can partner with the WinRT team for annotating more Windows-specific APIs, and we can also apply attributes across the Microsoft.Extensions libraries if/where appropriate.

**Comment by jeffhandley** [comment]
For this, we can start by searching for `PlatformNotSupportedException` across the codebase (there are around 4000 instances), and then categorize the instances into different patterns. From there, we can decide the the action to take on each category. We could then assign out child issues of this story to all area owners that need to apply annotations within their areas.

**Comment by jeffhandley** [comment]
Here's a related issue that we need to take into account with this issue: https://github.com/dotnet/runtime/issues/49479

**Comment by buyaa-n** [comment]
> For this, we can start by searching for PlatformNotSupportedException across the codebase (there are around 4000 instances), and then categorize the instances into different patterns. From there, we can decide the action to take on each category. We could then assign out child issues of this story to all area owners that need to apply annotations within their areas.

As part of https://github.com/dotnet/runtime/issues/47228 analyzing `PlatformNotSupportedException` across the codebase is done and filed issues for each area, most of the issues have been resolved/annotated, very few moved to 7.0.

Not sure what else we planned to do further in 6.0 @jeffhandley @GrabYourPitchforks
