### ISSUE TITLE
Developers get warnings when they misuse [SupportedOSPlatform] or [UnsupportedOSPlatform] attributes

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#44914]
The Platform Compatibility Analyzer consumes [`[SupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.supportedosplatformattribute) and [`[UnsupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute) attributes to report diagnostics when APIs are referenced that are not supported on the targeted platforms. This analyzer and these attributes were introduced in .NET 5.0.

As our platforms expand in .NET 6.0, these attributes will need to be applied on many more APIs and in more complex scenarios.  To ensure the attributes are applied correctly, we need to create new diagnostics for missing or invalid attributes.

Here are some examples of when diagnostics should get raised:

* [x] Unknown or invalid platform names/versions dotnet/runtime#45851 and dotnet/roslyn-analyzers#4015
* [x] Conflicting attributes -- see the Inconsistent List section of the [Advanced Scenarios of Combining Attributes](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer#advanced-scenarios-for-combining-attributes) #43971

**Comment by danmosemsft** [comment]
This should not be P0 I think as we don't "control" that priority level.

**Comment by jeffhandley** [comment]
Thanks, @danmosemsft. At the time of creating this, @terrajobst and I were using zero-based priorities _within_ `Priority:1` issues to indicate that the parent `Priority:1` item is unsuccessful without its `Priority:0` children. But making this `Priority:1` will be cleaner for tracking.

**Comment by terrajobst** [comment]
Works for me :-)

> This should not be P0 I think as we don't "control" that priority level.

My understanding is that you can use that priority but you need to explain to our directors why the product can't ship without them.

**Comment by buyaa-n** [comment]
Consider warning for misuse of newly added `SupportedOSPlatformGuard and UnsupportedOSPlatformGuard` attributes

**Comment by jeffhandley** [comment]
I'm closing this based on the original scope. We can file new issues to further improve this experience if needed.
