### ISSUE TITLE
Apply [SupportedOSPlatform] and [UnsupportedOSPlatform] annotations for new platforms in dotnet/runtime

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#44912]
In .NET 6.0, we will be adding support for new platforms including iOS, Android, macOS, iPadOS, and tvOS.  As support for these platforms is enabled, we need to inform the [Platform Compatibility Analyzer](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer) of which APIs are specific to those platforms and which APIs are unsupported on them.

To accomplish this, we need to apply [`[SupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.supportedosplatformattribute) and [`[UnsupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute) attributes throughout the .NET Libraries for these platforms.

We also need to ensure the SDK infers the appropriate `<SupportedPlatform>` items for projects targeting these platforms. This behavior already exists for Blazor apps where `<SupportedPlatform Include="browser" />` is inferred.

**Comment by marek-safar** [comment]
Is platform TFM superset of SupportedOSPlatformAttribute or is the expectation to still use it for such libraries?

**Comment by jeffhandley** [comment]
Platform TFMs will result in automatic application of the `[assembly:SupportedOSPlatform]` attribute for the targeted platform. But we'll need to enable checking of our new platforms in the build, and we'll also need to apply attributes for any specific APIs that have platform dependencies.

**Comment by joperezr** [comment]
@buyaa-n @jeffhandley is this one done?

**Comment by jeffhandley** [comment]
[OperatingSystem.IsIOS API is problematic #53084](https://github.com/dotnet/runtime/issues/53084) is still open but it's being tracked individually, so we can close this out.
