### ISSUE TITLE
ChannelReader expose Count property but not support in SingleConsumerUnboundedChannel

### ISSUE THREAD

**Issue by Caskia** [dotnet/runtime#44928]
Why expose this two property (Count and CanCount) in  System.Theading.Channels.ChannelReader but not support in SingleConsumerUnboundedChannel?
``` csharp
/// <summary>Gets whether <see cref="Count"/> is available for use on this <see cref="ChannelReader{T}"/> instance.</summary>
public virtual bool CanCount => false;

/// <summary>Gets the current number of items available from this channel reader.</summary>
/// <exception cref="NotSupportedException">Counting is not supported on this instance.</exception> 
public virtual int Count => throw new NotSupportedException();
```

**Comment by stephentoub** [comment]
Because of this:
https://github.com/dotnet/runtime/blob/01c8d63ddf6338c0649bfe5ae50bb065ac219bc4/src/libraries/Common/src/System/Collections/Concurrent/SingleProducerConsumerQueue.cs#L219

**Comment by tarekgh** [comment]
@Caskia we are closing this issue per @stephentoub answer. feel free to send more questions if you have any.
