### ISSUE TITLE
Consume new PGO / IBC data from optimization repo

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#44925]
We saw a number of [recent perf regressions](https://github.com/DrewScoggins/performance-2/issues/3249) on windows that were traced back to stale PGO data for the runtime. 

This seems to have happened as a consequence of #41897, the change to enable builds via ninja; perhaps the reworking of the PCH or similar is the culprit.

You can see from release build logs that very few methods now get optimized for speed; eg:
```
;; before
2324 of 33506 (  6.94%) profiled functions will be compiled for speed
;; after
 194 of 33461 (  0.58%) profiled functions will be compiled for speed
```
Not clear if non-Windows builds are as impacted.

I wanted to raise this because (a) recent local builds might see unexpected perf regressions, particularly comparing vs 5.0 RTM; and (b) it is not clear when we might see new PGO data.

**Comment by AndyAyersMS** [comment]
Not sure of area label either, marking as infrastructure for now.

**Comment by jkoritzinsky** [comment]
We haven’t ingested new PGO data since early August so we’re running quite a bit behind (in comparison to when we would regularly ingest new data).

**Comment by AndyAyersMS** [comment]
@brianrob you mentioned offline there were some discussions on who was going to own collection of native PGO data. Who should I nag about resolving this?

**Comment by AndyAyersMS** [comment]
@jeffschwMSFT maybe you can update this with status on resolving native PGO updates?

**Comment by jeffschwMSFT** [comment]
I have asked @agocke to fold the upcoming work as part of our infrastructure initiative.  One of our first commitments is to produce an instrumented build that can then be profiled in our new system (which is tbd).

**Comment by agocke** [comment]
Still getting up to speed on how this works, but I hope to have a better idea by the end of the week

**Comment by agocke** [comment]
This should be fixed now. @DrewScoggins is there any way to look at some benchmarks and verify the results?

**Comment by DrewScoggins** [comment]
This should give some results on dotnet build, which is the main scenarios we run that should be effected. https://msit.powerbi.com/groups/9ae0c009-7b27-44c9-8360-4452ec48cef3/reports/80d74b6f-53f1-4b44-b355-2913714ee37d/ReportSectionb89e16b5be17519f1bb8

**Comment by agocke** [comment]
There was a big drop right after https://github.com/dotnet/runtime/pull/51360 was merged, so I think that's close enough to mark this one as resolved.
