### ISSUE TITLE
Developers need more flexibility to annotate their code for platform supported/unsupported scenarios to reduce issues warnings noise

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#44922]
The [Platform Compatibility Analyzer](https://docs.microsoft.com/dotnet/standard/analyzers/platform-compat-analyzer) was introduced in .NET 5.0, raising new diagnostics when APIs are referenced that are unsupported on targeted platforms. The analyzer relies on the [`[SupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.supportedosplatformattribute) and [`[UnsupportedOSPlatform]`](https://docs.microsoft.com/dotnet/api/system.runtime.versioning.unsupportedosplatformattribute) attributes, which can be applied to assemblies, types, and members.  These annotations only provide a mechanism for marking an API as entirely supported/unsupported--there is currently no way to annotate an API as partially or conditionally supported on a platform.

## Conditionally-Supported Platform Annotations
With a mechanism for marking an API as being conditionally supported/unsupported on a platform, we could improve annotations for APIs such as [`MemoryMappedFile.CreateNew()`](https://docs.microsoft.com/dotnet/api/system.io.memorymappedfiles.memorymappedfile.createnew), where calls with a named memory mapped file (that is, a non-null `mapName`) are supported on Windows operating systems only.

This could involve creating new attributes such as `[SupportedOSPlatformIfNull]`, `[SupportedOSPlatformIfNotNull]`, `[UnsupportedOSPlatformIfNull]`, and `[UnsupportedOSPlatformIfNotNull]`. Occurrences of conditional platform support should be researched to determine what types of conditions need to be modeled in such attributes.

<h2 id="platform-guard-assertion-annotations">Platform-Guard Assertion Annotations</h2>

The analyzer already recognizes platform guards using the methods on [`OperatingSystem`](https://docs.microsoft.com/dotnet/api/system.operatingsystem), such as [`OperatingSystem.IsWindows`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.iswindows) and [`OperatingSystem.IsWindowsVersionAtLeast`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.iswindowsversionatleast). However, the analyzer does not recognize other guard methods or even helper methods that assert platform guards. Expanding this support could involve creating new attributes that indicate that an API asserts platform checks the same way the APIs on `OperatingSystem` do, potentially even conditionally.  

One example is in `Thread`, there is an internal field for `IsThreadStartSupported` that indicates whether or not the current platform supports calls to `Thread.Start`, regardless of which platforms are targeted.  Annotations could allow this to be modeled for the analyzer to warn if `Threat.Start` is called without first checking the corresponding `IsThreadStartSupported` member.

Additionally, it's expected that projects will commonly create helper methods that wrap around the `OperatingSystem` calls and these are not currently recognized through the flow analysis in the analyzer. Helper methods that perform platform assertion could be annotated to inform the analyzer that invocation or specific return values indicate platform support.

- ~~Conditionally-Supported Platform Annotations~~ [_removed from scope_](https://github.com/dotnet/runtime/issues/44922#issuecomment-822868902)
- [x] Platform-Guard Assertion Annotations

**Comment by jeffhandley** [comment]
Related: #47593

**Comment by buyaa-n** [comment]
## Conditionally-Supported Platform Annotations

> This could involve creating new attributes such as [SupportedOSPlatformIfNull], [SupportedOSPlatformIfNotNull], [UnsupportedOSPlatformIfNull], and [UnsupportedOSPlatformIfNotNull]. 

Thanks, I think we can have more generalized attribute to support `null`, `not null`, or other values

From the conditional platform support occurrences I found from [Mark Windows-specific APIs](https://github.com/dotnet/designs/pull/138) design doc there is usually APIs are supported only on windows when a parameter is `not null`, some depend on enum value provided. 
```cs
[AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method | System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
public sealed class SupportedOSPlatformWhenAttribute : OSPlatformAttribute 
{
	public SupportedOSPlatformWhenAttribute (string platformName, string parameterName, enum value) : base(platformName) { }
}

[AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method |  System.AttributeTargets.Property, AllowMultiple = true, Inherited = false)]
public sealed class UnsupportedOSPlatformWhenAttribute : OSPlatformAttribute 
{
	public UnsupportedOSPlatformWhenAttribute (string platformName, string parameterName, string value) : base(platformName) { }
}}
```
#### Usage examples: 
All of the MemoryMappedFile .Create* overload are supported only on windows `mapName` is not null
```cs
[SupportedOSPlatformWhen("windows", "mapName", "notnull")] 
public static MemoryMappedFile CreateNew(string? mapName, long capacity) { throw null; }

void Sample ()
{
    var mmf =  MemoryMappedFile.CreateNew("testmap", 10000); // warns 
    var mmf2 = MemoryMappedFile.CreateNew(null, 10000); // not warn 
} 
```
`PipeStream.set_ReadMode(PipeTransmissionMode)` works only on Windows the value is `PipeTransmissionMode.Message`.
```cs 
public virtual PipeTransmissionMode ReadMode 
{
    get { ... }
    [SupportedOSPlatformWhen("windows", "value", "Message")]
    set { ... }
}

void Sample ()
{
    var pipeStream = new PipeStream(); 
    pipeStream.ReadMode  = PipeTransmissionMode.Message; // warn 
    pipeStream.ReadMode  = PipeTransmissionMode.Byte; // not warn 
} 
```
Note: `PipeTransmissionMode.Message` is already annotated with `[SupportedOSPlatform("windows")]`

**Comment by buyaa-n** [comment]
## Platform-Guard Assertion Annotations

> The analyzer already recognizes platform guards using the methods on [`OperatingSystem`](https://docs.microsoft.com/dotnet/api/system.operatingsystem), such as [`OperatingSystem.IsWindows`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.iswindows) and [`OperatingSystem.IsWindowsVersionAtLeast`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.iswindowsversionatleast). However, the analyzer does not recognize other guard methods or even helper methods that assert platform guards. Expanding this support could involve creating new attributes that indicate that an API asserts platform checks the same way the APIs on `OperatingSystem` do, potentially even conditionally.  
> 
> One example is in `Thread`, there is an internal field for `IsThreadStartSupported` that indicates whether or not the current platform supports calls to `Thread.Start`, regardless of which platforms are targeted.  Annotations could allow this to be modeled for the analyzer to warn if `Threat.Start` is called without first checking the corresponding `IsThreadStartSupported` member.
> 
> Additionally, it's expected that projects will commonly create helper methods that wrap around the `OperatingSystem` calls and these are not currently recognized through the flow analysis in the analyzer. Helper methods that perform platform assertion could be annotated to inform the analyzer that invocation or specific return values indicate platform support.

I think we do not need additional attributes for covering these, I propose to just add `[SupportedOSPlatform]` and `[UnsupportedOSPlatform]` attributes for those helper methods or Field/Propert/Enum. When the analyzer found them in the conditional statement it will evaluate its attribute to figure out what attribute it is guarding. 

Example: For `IsThreadStartSupported` field mentioned above:

```cs 
#if !TARGET_BROWSER
    [UnsupportedOSPlatform("browser")] // The analyzer would only evaluate an immediate attribute(s)
    internal const bool IsThreadStartSupported = true;
#endif

protected internal override void QueueTask(Task task)
{
    if (Thread.IsThreadStartSupported) // This will be evaluated same as `!OperatingSystem.IsBrowser()`
    {
        // Call unsupported on browser APIs safely
        new Thread(s_longRunningThreadWork)
        {
            IsBackground = true,
            Name = ".NET Long Running Task"
        }.UnsafeStart(task);
    }
}

**Comment by buyaa-n** [comment]
Notes from the last meeting:

1. For `Conditionally-Supported Platform Annotations` the attributes i proposed because there are not many cases detected for use, so we do not want to add another attribute if the number of cases is less than 20, instead we will hard code those APIs in the analyzer and special case. The number of cases I have seen until now is around 10-15, we can find more while resolving https://github.com/dotnet/runtime/issues/47228, so for now, i am leaving this scenario as blocked by https://github.com/dotnet/runtime/issues/47228
2. For `Platform-Guard Assertion Annotations` the idea sounds good, but we prefer to use different attributes for guards. I will create an issue for new attributes proposal

**Comment by jeffhandley** [comment]
Given the assessment @buyaa-n provided for "Conditionally-Supported Platform Attributes," I'm going to edit this story to remove that from scope. With the Platform-Guard attributes in place and in use, we can then mark this story as completed.
