### ISSUE TITLE
System.Text.Json may return null object with valid JSON.

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/runtime#44943]
### Description

I'm running the code in .NET 5.0.

```csharp

void Main()
{
	var repo = new Repository<Change>();
	BuildWebActionResultAsync(repo).Dump();
}

public static object BuildWebActionResultAsync<T>(Repository<T> repository)
{
	typeof(T).Name.Dump();

    string jsonForm = @"
	
	[
    {
        ""id"": ""00d0b10f-ad05-4202-9f26-efe5b8c6c3d4"",
        ""change"": {
            ""content"": ""1""
        },
        ""date"": ""2020-11-19T13:51:53.4299857Z""
    },
    {
        ""id"": ""4da84cbd-c118-42b7-ad6e-33a2aad8651e"",
        ""change"": {
            ""content"": ""2""
        },
        ""date"": ""2020-11-19T13:51:53.6131444Z""
    },
    {
        ""id"": ""17d11e34-805b-423a-8dd5-db4ff26ba982"",
        ""change"": {
            ""content"": ""3""
        },
        ""date"": ""2020-11-19T13:51:53.7766643Z""
    }
]

	";
    var formObject = JsonSerializer.Deserialize<List<Commit<T>>>(jsonForm);
    return formObject;
}
		
public class Repository<T>
{

}
		
public class Change
{
    public string Content { get; set; }
}
	
public class Commit<T>
{
    public string Id { get; set; } = Guid.NewGuid().ToString("D");
    public T Change { get; set; }
    public DateTime Date { get; set; } = DateTime.UtcNow;
}

```

While the output is:

![image](https://user-images.githubusercontent.com/19531547/99675540-4d0a5480-2ab2-11eb-9647-23df3b259dd7.png)

All change is null. The ID and the data is not from the string json source. While the count is correct.

### Configuration

* Which version of .NET is the code running on?

.NET 5.0

* What OS and version, and what distro if applicable?

Windows 10.  19042 

* What is the architecture (x64, x86, ARM, ARM64)?

x64

* Do you know whether it is specific to that configuration?

No.

### Regression?

I guess it's a bug with `System.Text.Json`. Because if I replace that with `Newtonsoft.Json`, the bug disappears.

### Other information

The same code with `Newtonsoft.Json` works fine.

**Comment by layomia** [comment]
Based on your input payload, you need to either specify a [camel case naming policy](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-5.0#System_Text_Json_JsonSerializerOptions_PropertyNamingPolicy) or [case insensitive property name matching](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamecaseinsensitive?view=net-5.0) on `JsonSerializerOptions`.
