### ISSUE TITLE
Regex.Split() with \G stops after first item

### ISSUE THREAD

**Issue by sharpjs** [dotnet/runtime#44957]
### Description

When the `\G` anchor is used in a `(?<=...)` construct, the `Regex.Split(string, string)` method stops splitting after the first item.

This bug is also exposed in PowerShell 7.1.0: https://github.com/PowerShell/PowerShell/issues/14112

### Example

```csharp
Regex.Split("aabbccdd", @"(?<=\G..)(?=..)")
```

Case | Result
:--|:--
Expected: | `{ "aa", "bb", "cc", "dd" }`
.NET 5.0 | `{ "aa", "bbccdd" }`
.NET Core 3.1 | `{ "aa", "bb", "cc", "dd" }`

### Reproduction

**To reproduce,** clone [sharpjs/Net50RegexSplitBug](https://github.com/sharpjs/Net50RegexSplitBug) and run tests.

![image](https://user-images.githubusercontent.com/708461/99709969-d5f2a300-2a54-11eb-96aa-763d242d9502.png)

### Configuration

.NET 5.0.100
Windows 20H2 (OS Build 19042.630) x64
Not specific to this configuration; easily reproducible using PowerShell 7.1.0 on Linux.

```none
docker run -it --rm mcr.microsoft.com/powershell:preview
```

```powershell
[regex]::Split("aabbccdd", "(?<=\G..)(?=..)")
```

### Regression?

Yes,  in .NET 5.0.100.

**Comment by stephentoub** [comment]
Thanks for the repro. This is a one-line fix. I'll put up a PR tonight.
