### ISSUE TITLE
System.Text.Json default values instead of actual values when deserializing.

### ISSUE THREAD

**Issue by MeydanOzeri** [dotnet/runtime#44966]
Im experiencing a weird bug when trying to Deserialize a json to objects with nested values in .net5.
It happens when my object has inside an object that has inside of it an object.
I have a record called Users, which has a property which is a record called ExternalUsers which has a property which is a record called Test.

When i try to deserialize this json in to the ExternalUsers property:
```json
{
	"id": "0175dccb-ceae-778a-af4d-6c13f89b3066",
	"username": "asd",
	"token": "asdasd",
	"test": {
		"id": "0175dccb-ceae-623f-a54d-cfa7504f5178",
		"testing": "asd",
		"number": null,
		"type": 1,
		"my_property": [1, 2, 3],
		"asa": [1, 2, 3],
		"bobo": ["asd", "asdasd"],
		"my_property2": ["asd", "asdasd"],
		"my_property3": [0, 1],
		"my_property4": {
			"test": 1,
			"newTest": [1, 2, 4],
			"lastTest": { "yay": 1, "anotherYay": 2 }
		},
		"my_property5": [0, 1]
	}
}
```

I get this result:
![text json](https://user-images.githubusercontent.com/39773818/99723699-30264f00-2abb-11eb-8049-ef356ac77646.png)

While in newtonsoft i get this result which is as expected:
![newtonsoft](https://user-images.githubusercontent.com/39773818/99723785-4e8c4a80-2abb-11eb-8c84-7a6be596dae7.png)

**Comment by benaadams** [comment]
`PropertyNamingPolicy`?
```csharp
var serializeOptions = new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
};
```
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#customize-individual-property-names

**Comment by layomia** [comment]
@MeydanOzeri, a couple options based on your sample payload:

- [provide a custom snake_case `JsonNamingPolicy`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializeroptions.propertynamingpolicy?view=net-5.0)
- [customize individual property names with `JsonPropertyNameAttribute`](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#customize-individual-property-names) as @benaadams pointed out.
