### ISSUE TITLE
ConcurrentDictionary.TryGetValue: volatile read of Node

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#44967]
In `ConcurrentDictionary.TryGetValue`, there is a `for` loop that searches the appropriate bucket for the `Node` corresponding to the supplied `key`:

https://github.com/dotnet/runtime/blob/3c5b4a663ac63c4d768cc780a9442fb4fa4bacb6/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L434

Above this code, there is a comment regarding the call to `Volatile.Read`:

https://github.com/dotnet/runtime/blob/3c5b4a663ac63c4d768cc780a9442fb4fa4bacb6/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L424-L425

This doesn't make sense to me: `Node` is a reference type, so reading the reference from `_tables._buckets` should be an atomic operation. If `Node` was a value type, I would understand, but as it is, I don't see what the `Volatile.Read` is doing to prevent reading fields of different instances.

**Comment by stephentoub** [comment]
I expect it's the same read introduction concerns as you asked about in https://github.com/dotnet/runtime/issues/43856.  If multiple reads of that same ref could be introduced, each could be of a different node if a concurrent write wrote to that same slot in the table.

**Comment by WizardBrony** [comment]
@stephentoub That makes sense. I wasn't thinking about the reference itself as being a value that could be read multiple times. Would that still be possible even if `GetBucket` returned a `Node` instead of a reference to a `Node`?

**Comment by stephentoub** [comment]
Technically, yes, but I don't think it would ever happen in practice.
