### ISSUE TITLE
Why don't `IQueryable<T>` implement `IAsyncEnumerable<T>` ?

### ISSUE THREAD

**Issue by Anduin2017** [dotnet/runtime#44961]
# Issue Title

Why don't `IQueryable<T>` implement `IAsyncEnumerable<T>` ?

# General

Since `IQueryable<T>` is an interface which represents something that you can query from and get data. For example: In EF-Core, you can use `IQueryable.ToListAsync()` to get all items from a database.

So usually, this interface is with IO operations. Also not very fast and shall be waited. But it implements interface: `IEnumerable`. Which I don't think is reasonable. For some developers may do something like this:

```csharp
            var allTopics = db.Topics
                .Where(t => t.SummitId == id);
            foreach (var topic in allTopics) // Not called ToList(). So he is iterating an IQueryable.
            {
                // do something.
                bigName += topic.Title;
            }
```

So I suggest to implement  `IQueryable<T>` with `IAsyncEnumerable<T>`. Or maybe better, create a new interface named: `IAsyncQueryable<T>` which tells developer: 

> This interface is slow to be iterated. Also might block the thread. Consider use await foreach.

Also, I can use `await foreach` to iterate the result from query to do some more advanced operations.

**Comment by huoyaoyuan** [comment]
Because `IAsyncEnumerable` is introduced latter.

Adding inherited interface is a strongly breaking change, and will never happen.

**Comment by Anduin2017** [comment]
> Because `IAsyncEnumerable` is introduced latter.
> 
> Adding inherited interface is a strongly breaking change, and will never happen.

Yes. So maybe creating another `IAsyncQueryable` is still possible.

**Comment by eiriktsarpalis** [comment]
EF Core already exposes an extention method for consuming queryables using [IAsyncEnumerable](https://github.com/dotnet/efcore/blob/e2606903a208db8f2373c3dbf4bfeaf098639345/src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs#L3245). Would this pattern not satisfy your requirements?

**Comment by Anduin2017** [comment]
Ah! Exactly what I need. Thanks!
