### ISSUE TITLE
VS breaks on System.Security.Cryptography.CryptographicException regardless it is excluded

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#44981]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/VS-breaks-on-SystemSecurityCryptograph/1262077?preview=true)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:15.7]
VS breaks on System.Security.Cryptography.CryptographicException that is not set for breaking in exception settings.

---
#### Feedback Bot on 11/19/2020, 06:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tarekgh** [comment]
@bartonjs the linked internal ticket of this community issue has a VS attached project to repro it. let me know if you cannot reach it.

**Comment by bartonjs** [comment]
I'm not sure why this got routed to dotnet/runtime.  It seems like a debugger problem in the break on exception filter.

If there's some specific code in dotnet/runtime that is aggravating the filter we could do something about it, but the current issue isn't actionable.  Given a lack of activity, I'm going to go ahead and close it.
