### ISSUE TITLE
Protect visual studio in CI for libraries

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#45007]
https://github.com/dotnet/runtime/pull/44998#issuecomment-731249748

cc @am11 @stephentoub @Anipik

**Comment by safern** [comment]
as part of this should we also rename the `runtime-live-build` to `runtime-dev-workflow` or something like that?

**Comment by Anipik** [comment]
> as part of this should we also rename the runtime-live-build to runtime-dev-workflow or something like that?

i think runtime-dev-workflow is much better, i didnt know the difference before this comment.

**Comment by ViktorHofer** [comment]
Hijacking this thread for a reach out to @am11. Would you mind contacting me via mail (you can find my mail address on my GH profile). Thanks

**Comment by am11** [comment]
@ViktorHofer, sure. I've sent an email.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/36139
