### ISSUE TITLE
AOT compiler for .NET/iOS not built with MONOTOUCH defined

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#45002]
### Description

The symptom is that an AOT-compiled iOS app can crash at runtime on device with:

> error: Ran out of trampolines of type 0 in '/private/var/containers/Bundle/Application/D21C45AD-25AB-4FD9-A08F-706A43A7974D/link all.app/System.Private.CoreLib.dll' (limit 4096). See http://docs.xamarin.com/ios/troubleshooting for instructions on how to fix this condition.

I diagnosed a bit, and the reason is that this line is never executed:

https://github.com/dotnet/runtime/blob/d85f060c86ae8f4e84ba46391fd3664fb903e1b4/src/mono/mono/mini/aot-compiler.c#L13778-L13780

which presumably happens because `MONOTOUCH` isn't defined.

I decompiled the AOT compiler shipped with .NET, and the one we currently use for Xamarin.iOS, and only the latter contains the line above.

.Mono for Xamarin.iOS: https://gist.github.com/rolfbjarne/8607804c44f873ebf6ef711e50f30134#file-foo-diff-L217-L223
.NET: https://gist.github.com/rolfbjarne/37cebf4f43296d9f51474944dd424650#file-foo-diff-L219-L224

This is the missing line: https://gist.github.com/rolfbjarne/8607804c44f873ebf6ef711e50f30134#file-foo-diff-L222

CC @akoeplinger

**Comment by imhameed** [comment]
This should be fixed; does this particular crash still happen? (I haven't personally gotten to the point where I've run an AOT-compiled app on-device, so it might take me a little while to create and test a repro.)

**Comment by rolfbjarne** [comment]
> This should be fixed; does this particular crash still happen?

I'll check once there are .NET packages with the fix.

**Comment by rolfbjarne** [comment]
This is fixed.
