### ISSUE TITLE
System.Diagnostics.Process.Kill(entireProcessTree: true) doesn't kill entire process tree on dotnet Debian images

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#45017]
### Description

When working on a fix for https://github.com/dotnet/aspnetcore/issues/27950, we attempted to use Process.Kill(true) to kill an entire process tree on Unix to fix our dependency on pgrep in dotnet-watch. However, when we tried to use that API, from what we can tell, only the parent process was killed.

I'm currently able to reproduce this behavior with dotnet watch, but here are the steps necessary to try reproing standalone

1. Create a .NET app which starts a process, which will also start a child process. This could be done through two .NET apps, one which starts the second app, which then calls some long running command line sleep 60.
2. Run the apps on the debian sdk image. An example command for doing this could look like:
```
docker run -it --rm --workdir /app -v ${PWD}/:/app mcr.microsoft.com/dotnet/sdk:5.0 dotnet run
```
3. Inside of the first app, call Process.Kill(true) to kill the entire process tree.
4. Check if both processes were killed.

Right now, I only see the parent being killed.

### Configuration

.NET 5, running on the mcr.microsoft.com/dotnet/sdk:5.0 image.

### Regression?

Not sure.

**Comment by eiriktsarpalis** [comment]
Out of curiosity, does the issue not reproduce on non-Debian distros? (e.g. when using the Ubuntu or Alpine images?)

**Comment by jkotalik** [comment]
This also reproduces on the Ubuntu and Alpine as well.

For context, this is what we were doing before to kill all child processes, which worked: https://github.com/dotnet/aspnetcore/blob/master/src/Shared/Process/ProcessExtensions.cs#L34

**Comment by adamsitnik** [comment]
Triage notes:

- it's a bug and should definitely be fixed for 6.0
- we need to check if it reproduces on docker only
- we need to check if it's a regression compared to 3.1 (this might affect backporting)

**Comment by adamsitnik** [comment]
I am unable to reproduce it on bare metal Ubuntu box (so it's most likely docker-related issue as @eiriktsarpalis has suggested today)

<details>

```cs
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace ProcessKIllTree
{
    class Program
    {
        static void Main(string[] args)
        {
            string currentExePath = Process.GetCurrentProcess().MainModule.FileName;
            int GetChildCount() => Process.GetProcessesByName(Path.GetFileName(currentExePath)).Count(p => p.Id != Process.GetCurrentProcess().Id);

            if (args.Length == 0)
            {
                var firstChild = Process.Start(currentExePath, "1");

                while (GetChildCount() != 2) { } // wait till both child processes are started

                firstChild.Kill(entireProcessTree: true);

                Console.WriteLine($"{GetChildCount()} remained alive.");
            }
            else if (int.TryParse(args[0], out int index))
            {
                if (index == 1) Process.Start(currentExePath, "2"); // the first child starts one more and that's it

                while (true) { } // make sure the child process never quits
            }
        }
    }
}
```

```cmd
dotnet publish -c Release --self-contained -r linux-x64 -f netcoreapp3.1
bin/Release/netcoreapp3.1/ProcessKIllTree
0 remained alive.
```

```cmd
dotnet publish -c Release --self-contained -r linux-x64 -f net5.0
bin/Release/net5.0/ProcessKIllTree
0 remained alive.
```

</details>

**Comment by jkotalik** [comment]
@adamsitnik are those logs inside of a docker-container or no?

> we need to check if it's a regression compared to 3.1 (this might affect backporting)

If this isn't a regression and you wouldn't backport to 3.1 or 5.0, we'd need to come up with a custom solution on our side for dotnet-watch. Have we identified where the bug is, s.t. we can start working on a custom solution?

**Comment by jkotalik** [comment]
As an update, the difference in reproing this happens changes when we run dotnet watch with and without a shell.

For example, the following command doesn't work:
`docker run -it --workdir /app -v ${PWD}/:/app mcr.microsoft.com/dotnet/sdk:5.0 dotnet watch --verbose run`

while this works:
`docker run -it --workdir /app -v ${PWD}/:/app mcr.microsoft.com/dotnet/sdk:5.0 /bin/sh -c "dotnet watch --verbose run"`

Wondering if there is some permission issue or environment variables that could be different when we run inside of a shell or not.

**Comment by danmosemsft** [comment]
cc @bgribaudo (who kindly implemented this originally) in case he has thoughts about that.

**Comment by eiriktsarpalis** [comment]
@adamsitnik I was unable to reproduce using your code on docker. Here is [the relevant infrastructure](https://github.com/eiriktsarpalis/process-kill-repro). So perhaps something is missing it. @jkotalik would you be able to help us here?

**Comment by jkotalik** [comment]
@eiriktsarpalis we setup a meeting tomorrow show the repro to Adam, I believe you were just forwarded the invitation 😄

**Comment by bgribaudo** [comment]
> cc @bgribaudo (who kindly implemented this originally) in case he has thoughts about that.

I don't, off the top of my head. I am curious what yesterday's repro meeting found.

**Comment by eiriktsarpalis** [comment]
When running the [reproducing repo](https://github.com/eiriktsarpalis/process-kill-repro) from an Ubuntu host I can occassionally reproduce the issue with the 5.0 sdk image:
```
$ make SDK_VERSION=5.0
/* docker build output */
docker run process-kill-repro
1 remained alive.
```
However I was never able to reproduce using the 3.1 image:
```
$ make SDK_VERSION=3.1
docker run process-kill-repro
0 remained alive.
```

**Comment by danmosemsft** [comment]
Presumably investigation here would mean adding some logging and then running until a repro happens.
