### ISSUE TITLE
Ensure the BCL supports hot reloading, especially around reflection

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#45023]
TBD

**Comment by danmosemsft** [comment]
@stephentoub is there more detail here? When we discussed it, the need for changes in the core libraries was hypothetical, perhaps we have more now?

cc @steveharter

**Comment by stephentoub** [comment]
I don't know what @terrajobst had in mind here. :smile:

The only thing I'm aware of in this space is potentially being able to invalidate various caches in the libraries when some kind of change is made, via some form of runtime callback, and reflection is ripe with caches that would qualify (e.g. if you add a value to an enum, it'd be nice if subsequent use of reflection to list enum names would include the new value).

**Comment by danmosemsft** [comment]
What would that look like -- an event one can subscribe to on AppDomain (that still seems to be the closest place to a location for global events) ?

**Comment by jkotas** [comment]
More important question is how would people write reliable and performant code with mutable reflection model. Programming against mutable object models is incredibly hard to do in reliable and performant way.

It is one of the reason why Edit&Continue does not expose the edits in the reflection APIs today.

**Comment by danmosemsft** [comment]
Perhaps @steveharter can help us in January to figure out whether there's anything here or this can be closed? I'd rather it not sit around without more clarity.

**Comment by jkotas** [comment]
We need end-to-end spec with details how the different hot reloading modes are going to work, where each of them ends and their implementation architecture.

This specific issue is a potential part of the EnC hot reloading mode. We need to draw a boundary around the limits of EnC reloading mode before we can tell what makes sense to do here.

FWIW, I expect that this issue is going to be cut because of https://github.com/dotnet/runtime/issues/45023#issuecomment-733290636.

**Comment by danmosemsft** [comment]
> We need end-to-end spec with details how the different hot reloading modes are going to work, where each of them ends and their implementation architecture.

@DamianEdwards @stephentoub is there a person who owns this spec?

**Comment by stephentoub** [comment]
> is there a person who owns this spec?

@LyalinDotCom

**Comment by LyalinDotCom** [comment]
Hi folks, 

@tmat and I would love to meet with all of you to discuss this. I will setup a quick chat and we can circle back here once we've talked.

**Comment by jeffhandley** [comment]
@terrajobst / @stephentoub - Did anything end up surfacing from the Libraries perspective on this that still needs to be addressed, or can this be closed?

**Comment by stephentoub** [comment]
Nothing beyond what I already did has surfaced as being needed.  As planned, we'll deal with additional clearing needs as one-offs as feedback dictates.

**Comment by terrajobst** [comment]
Makes sense. Thanks!
