### ISSUE TITLE
[mono] Remove framework-specific code and unnecessary MonoDomain usage

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#45034]
Actually making this change would require turning off the mirror and probably break a lot of the embedding API. It might be worth prototyping to see if that's worth the pain, depending on the resulting size and performance impact for wasm workloads. My guess is that it won't do much, but it's really hard to know and might add up.

cc: @lambdageek @vargaz

**Comment by naricc** [comment]
How do we plan to measure the performance? The microbenchmarks from dotnet/performance, or something else?

**Comment by CoffeeFlux** [comment]
I didn't have anything in mind; I'm mostly worried about the size. Microbenchmarks seem like a reasonable option, but I'm sure we can figure something out if we get this prototyped.

**Comment by lambdageek** [comment]
why would it break the embedding API? we coudl return some sentinel value to represent the single domain.  It would force us to make more of the external API `MONO_RT_EXTERNAL_ONLY`, but that's a benefit, really.

**Comment by CoffeeFlux** [comment]
Yeah, I guess we'd just need to patch up all the functions designed to read properties from it and probably just ignore it otherwise. I guess I should have said that it'd require significant embedding API changes.

**Comment by CoffeeFlux** [comment]
Initial prototyping on this is done, but it's dependent on stopping the mirror. Once that happens, I'll rebase, clean up, and PR this work.

**Comment by CoffeeFlux** [comment]
There's ongoing work to remove this as much as possible and use `MonoDomain` as a global namespace. I'll close this issue once I'm no longer submitting PRs to that end, but I'm not going to link them all back here.

**Comment by SamMonoRT** [comment]
We aren't going to add more changes here in the 6.0 timeframe. Moving this to 7.0.0

**Comment by lambdageek** [comment]
Although I was surprised by how much dead code we managed to prune off in 6.0, I think most of the low-hanging fruit is gone, and any further improvements will come from deeper architectural changes like https://github.com/dotnet/runtime/issues/50656 which doesn't seem like 6.0 timeframe work

**Comment by lewing** [comment]
@lambdageek this is quite stale now, is there any value in keeping it open?

**Comment by lambdageek** [comment]
Yea, as I mentioned a couple years ago https://github.com/dotnet/runtime/issues/45034#issuecomment-877279253 we've done the easy cleanups.  Also the usage of `MonoDomain` now is pretty much how we described it in the discussions - there's a singleton value that is used for MonoAPI queries, but otherwise we ignore it.
