### ISSUE TITLE
Using Microsoft.VisualStudio.TextTemplating in .Net Core

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#45048]
Is there a Plan to move TextTemplating to DotNet Core?

I've several programs wich internal use T4 Templates (at Runtime, not at Build Time) to allow customization. They've hosted the TextTemplating Engine inside. Is there a Plan to move that Lib's to Dotnet Core?

**Comment by jogibear9988** [comment]
Founds a fork wich could work: https://github.com/SubSonic-Core/SubSonic.Core.TextTemplating
see: https://github.com/mono/t4/issues/89

**Comment by jeffschwMSFT** [comment]
Glad you found a viable solution.  I am going to close this, but please let me know if there is more to the issue.

**Comment by jogibear9988** [comment]
I still want to know if Microsoft will switch it‘s Solution to NetCore?

**Comment by jogibear9988** [comment]
@jeffschwMSFT ???

**Comment by jeffschwMSFT** [comment]
Could you open a VS feedback ticket with the suggestion?  If you link the ticket to this issue I move it to the appropriate team.
