### ISSUE TITLE
Covariant Return crashes on runtime when there is additional abstract class in between not overriding the abstract method.

### ISSUE THREAD

**Issue by progala2** [dotnet/runtime#45053]
### Description

In net 5.0, windows 10x64, Visual Studio 2019 and C#9 the below code will not run and will produce the following error:

System.TypeLoadException: Return type in method 'Application.TB.GetA()' on type 'Application.TB' from assembly 'Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'Application.T`1[System.__Canon].GetA()'.

```csharp
    public abstract class T<TR>
    {
        public abstract TR GetA();
    }

    // This abstract causes the error - not overriding the base method cause the runtime to crash
    public abstract class TA : T<A> { }

    // This works
    // public abstract class TA : T<A>
    // {
    //  // Overriding in between fixes the problem
    //    public override A GetA() => new ();
    // }
    
     // Overriden here, in the grandson
    public class TB : TA
    {
        public override B GetA() => new ();
    }
    public class A { }

    public class B : A { }

public static class Program
{
        public static void Main(string[] args)
        {
            System.Console.WriteLine((new TB() as T<A>).GetA().GetType().FullName);
        }
}
```

### Regression?

Don't know. It is a new feature for C#.

### Other information

Works with Mono (thanks @lambdageek )

**Comment by lambdageek** [comment]
(works on mono - `(new TB() as T<A>).GetA().GetType().FullName` returns `B`))

**Comment by progala2** [comment]
> (works on mono - `(new TB() as T<A>).GetA().GetType().FullName` returns `B`))

Thanks, I updated the description with your discovery :)

**Comment by pentp** [comment]
@janvorli - This probably the same issues as #45037, but in reverse (concrete type overriding generic type)?

**Comment by janvorli** [comment]
This is unfortunately a new issue. With the latest fixes for covariant returns issues that will be released in 5.0.2, it fails with
```
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B (COR_E_BADIMAGEFORMAT))
   at Program.Main(String[] args)
```

**Comment by janvorli** [comment]
Fortunately, it was just a local issue, I have probably built debug runtime and tested the test with an old checked one. After rebuilding, the test above is passing. Closing this issue now as a dup of #45037.

**Comment by janvorli** [comment]
It turns out the issue wasn't fixed. There must have been some issue in my local process.
