### ISSUE TITLE
Update documentation fo Unix Platforms

### ISSUE THREAD

**Issue by janhenke** [dotnet/runtime#4506]
The documentation for building CoreCLR on Unix is outdated in some ways.
- Building CoreFX on Unix works now
- Building mscorlib on Unix works now (Linux instructions have been updated already, FreeBSD has not been updated)

It should also be considered if the instructions really should duplicate about building the managed assemblies. I think a reference to the corresponding instructions in the CoreFX repository are better (which would also avoid some of work here).

Last but not least, I think it would be a useful thing if we could merge the separate instructions for the different Unix platforms into one document. A lot of steps are more or less the same. It could work very well to have one document, which just outlines the differences between the platforms where needed. This would also reduce the maintenance burden regarding the documentation ;)

**Comment by kant2002** [comment]
@ViktorHofer isn't it already done and can be closed?

**Comment by ViktorHofer** [comment]
Yes this issue is quite outdated and should be closed. Thanks
