### ISSUE TITLE
Thread Assertion Failed on Apple Mac Mini M1.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#45073]
### Description

I get the following error when running a multithreaded program on Apples M1 chipset.

assertion failed [thread->context == nullptr]: found an existing record for a runtime thread
(Thread.cpp:266 register_runtime_mach_thread)

The program basically  signals the thread to do some work.

I do not get this error when running on other macs running on MacOS.

### Configuration

* Which version of .NET is the code running on? **.net 5.0 runtime**
* What OS and version, and what distro if applicable? **MacOS BigSur 11.0.1**
* What is the architecture (x64, x86, ARM, ARM64)? **ARM64 M1 chip.**
* Do you know whether it is specific to that configuration? **I believe it is.** 

### Other information

This is not easily reproduceable, as this does not happen on any other platform and the program could be running for days or minutes before the exception occurs and currently cannot use Visual studio debugging on this platform this is another bug report.

When the exception occurs the program is CPU bound. I cannot use control C to stop it. have to use the kill command.

I know this architecture is not supported but identifying it early so it can be addressed once it is supported. If required I can try a write a sample program that can cause this error to make it reoccur consistently.. Will take some time though.

**Comment by robtaylor** [comment]
I just hit this also, same configuration

**Comment by mangod9** [comment]
This was possibly due to some initial Rosetta issues (macos 11.3 has most of these resolved), if this still repros please reopen.

**Comment by TheSPST** [comment]
I am facing this in macOS 11.4

**Comment by speed2048** [comment]
I have not run into this issue since 11.3 but will keep trying to reproduce.
