### ISSUE TITLE
like #24694，Interlocked.CompareExchange/Exchange still missing for UIntPtr

### ISSUE THREAD

**Issue by bysdxt** [dotnet/runtime#45103]
## Background and Motivation

.net5 adds support for native int(nint and nuint), System.Threading.Interlocked should support them too

## Proposed API

```diff
namespace System.Threading
{
     public static class Interlocked {
+        public static extern UIntPtr CompareExchange(ref UIntPtr location1, UIntPtr value, UIntPtr comparand);
+        public static extern UIntPtr Exchange(ref UIntPtr location1, UIntPtr value);
     }
```

**Comment by GSPP** [comment]
This is the set of .NET 5.0 `Interlocked` methods:

![image](https://user-images.githubusercontent.com/12032350/101771514-5784a080-3aea-11eb-9ec0-6f3411decd12.png)

Maybe we should add `IntPtr` and `UIntPtr` overloads to `Add`, `Increment`, `Decrement`, `And` and `Or`.

Is `Interlocked.Read` still relevant or does `Volatile` cover that? If still relevant, adding `*Ptr` overloads there would make sense, too.

**Comment by hamarb123** [comment]
This should be higher priority now that there is the `nuint` keyword.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Threading
{
    public static class Interlocked
    {
        public static extern UIntPtr CompareExchange(ref UIntPtr location1, UIntPtr value, UIntPtr comparand);
        public static extern UIntPtr Exchange(ref UIntPtr location1, UIntPtr value);
    }
}
```
