### ISSUE TITLE
System.Text.Json.JsonSerializer.Deserialize<T>() Deserialize content contains “\r” report errors

### ISSUE THREAD

**Issue by dashenxian** [dotnet/runtime#45101]
### Description

When I use System.Text.Json.JsonSerializer.Deserialize() Deserialize string, if the string contains a "\r", an error is reported like this:System.Text.Json.JsonException:“'0x0D' is invalid within a JSON string. The string should be correctly escaped.
![image](https://user-images.githubusercontent.com/18696614/99927757-82989180-2d81-11eb-9044-0d6e0e384893.png)

### Configuration

os:windows 10

### Regression?

.NET Core version: 3.1/5.0

### Other information

```c#
void Main()
{
	var json="{\"content\":\"aaaa\rbbb\"}";
	var obj=JsonSerializer.Deserialize<Test>(json);//error
}
class Test{
	public string content { get; set; }
}
```

**Comment by GrabYourPitchforks** [comment]
I don't think this is a regression. As the exception text states, it is illegal for a JSON payload to contain a raw `[ 0D ]` byte in the middle of a literal string. Newlines must instead be escaped, for example as the byte sequence `[ 5C 72 ]`, which is a literal backslash character followed by a literal 'r' character. The JSON deserializer sees that the payload is ill-formed and fails the operation.

**Comment by dashenxian** [comment]
What should I do if I get such a string from a third party?Whether it can only be replace “\r” to "\\r" or switched back Newtonsoft.Json？

**Comment by Joe4evr** [comment]
Ideally, you should complain to your third party that they are sending malformed JSON payloads and the onus is on them to fix it.

**Comment by ycrumeyrolle** [comment]
> I don't think this is a regression. As the exception text states, it is illegal for a JSON payload to contain a raw `[ 0D ]` byte in the middle of a literal string. Carriage returns must instead be escaped, for example as the byte sequence `[ 5C 72 ]`, which is a literal backslash character followed by a literal 'r' character. The JSON deserializer sees that the payload is ill-formed and fails the operation.

This is correct, as defined here: https://tools.ietf.org/html/rfc8259#section-7
>    All Unicode characters may be placed within the
>    quotation marks, except for the characters that MUST be escaped:
>    quotation mark, reverse solidus, and the control characters (U+0000
>    through U+001F).

**Comment by layomia** [comment]
> What should I do if I get such a string from a third party?Whether it can only be replace “\r” to "\r" or switched back Newtonsoft.Json？

Supporting this would violate System.Text.Json's design principle of standards' compliance. It would be ideal for the third-party to fix the issue here. If that fails, switching back to Newtonsoft.Json is a good option if it satisfies your scenario.
