### ISSUE TITLE
Can't Inspect Static Class Variables in a Blazor Wasm App Using the Debugger

### ISSUE THREAD

**Issue by CincySteve** [dotnet/runtime#45104]
I am not able to inspect properties and fields in static classes using the VS Community 2019 v16.8.2 debugger with an AspNetCore 5.0 Blazor Wasm app running on Chrome 86.0.4240.198.  I have to assign them to local variables to be able to inspect the values.  I have a small repro app that will show the problem, but it seems any app with a static class containing public properties/fields will do.    

I think this might be related to [#42057](https://github.com/dotnet/runtime/pull/42057), which encompassed an issue I submitted ([#40245](https://github.com/dotnet/runtime/issues/40245)) plus one before that.

**Comment by mkArtakMSFT** [comment]
@lewing not sure whether this is a dupe of an existing issue or not.

**Comment by lewing** [comment]
@radical can you take a look

**Comment by CincySteve** [comment]
I'm hoping the 6.0.0 milestone (November, 2021) is only a preliminary target.  This problem is a big productivity drain, and one I was hoping would have been fixed in the 5.0.0 release that addressed what appears to have been similar problems ([#42057](https://github.com/dotnet/runtime/pull/42057)) as noted above.

**Comment by radical** [comment]
I should have a fix for this in a few weeks.

**Comment by CincySteve** [comment]
@radical That would be great.  I can't wait.

**Comment by radical** [comment]
@lewing Do we know if we should add any extra information to the response to allow the debugger to treat these as static members? I didn't see anything in CDP that might help. I'll surface them same as other members, for now.

**Comment by CincySteve** [comment]
Just upgraded VS to v16.8.4 and confirmed that I am still experiencing this issue.  Any news?

**Comment by radical** [comment]
@thaystg is this fixed with `main`?

**Comment by thaystg** [comment]
No.
