### ISSUE TITLE
Return IServiceCollection from TryAdd extensions

### ISSUE THREAD

**Issue by csharpsi** [dotnet/runtime#45114]
## Background and Motivation

By returning the instance of the `IServiceCollection` instead of `void` it would make it possible to chain service collection configuration using a fluent API. This is consistent with the non-try methods, such as `AddTransient` and `AddSingleton` etc.

## Proposed API

```diff
namespace Microsoft.Extensions.DependencyInjection.Extensions
{
    public static class ServiceCollectionDescriptorExtensions
    {
-        public static void TryAdd(this IServiceCollection collection, ServiceDescriptor descriptor)
+        public static IServiceCollection TryAdd(this IServiceCollection collection, ServiceDescriptor descriptor) 
         {
            if (collection == null)
            {
                throw new ArgumentNullException(nameof(collection));
            }

            if (descriptor == null)
            {
                throw new ArgumentNullException(nameof(descriptor));
            }

            if (!collection.Any(d => d.ServiceType == descriptor.ServiceType))
            {
                collection.Add(descriptor);
            }

+           return collection;
         }
    }
}
```
This would include all of the `TryAdd...` methods in the extensions.

## Usage Examples

```C#
public static class MyServiceCollectionExtensions
{
    public static IServiceCollection AddMyConfig(this IServiceCollection services) => services
        .TryAddTransient<MyTransientService>()
        .TryAddSingleton<IMySingleton, MySingleton>()
        .AddTransient<MyOtherTransientService>();
        // ... and so on
}
```

## Alternative Designs

N/A

## Risks

This is a breaking change to the API. However, because the existing API methods are `void` methods, I believe any code using these extensions would simply ignore the return type making the risk minimal.

**Comment by csharpsi** [comment]
I would be happy to add a PR for this if it's considered a good idea

**Comment by KalleOlaviNiemitalo** [comment]
This would be binary incompatible, throw `MissingMethodException` at run time if a caller was built against an version that returns `void` and is run against a version that returns `IServiceCollection`.

**Comment by csharpsi** [comment]
What circumstances make that a problem? My understanding of this being a NuGet package is that the version would be bumped, is that not correct? Maybe I've misunderstood something

**Comment by KalleOlaviNiemitalo** [comment]
Imagine an application uses a third-party library that references Microsoft.Extensions.DependencyInjection 5.0.0 (or any older version), where `TryAdd` returns `void`. Then, the application developer adds a reference to Microsoft.Extensions.DependencyInjection 6.0.0, where `TryAdd` returns `IServiceCollection`, but the third-party vendor does not publish a new version of the library. This causes the old library code to run against the new Microsoft.Extensions.DependencyInjection code, resulting in `MissingMethodException`.

**Comment by csharpsi** [comment]
That makes sense. I suppose this API could be introduced as a wrapper in a separate namespace, but then, is it really worth it?

**Comment by KalleOlaviNiemitalo** [comment]
If binary compatibility were not a problem, then the `TryAdd` methods could return `bool`, like in <https://github.com/dotnet/aspnetcore/blob/371a26f07b23ad77c636332c2dfc0cbd1d8137ba/src/Logging.AzureAppServices/src/AzureAppServicesLoggerFactoryExtensions.cs#L75-L80>.

**Comment by eerhardt** [comment]
Thanks for the suggestion. However, since this would be a binary breaking change we cannot implement it.
