### ISSUE TITLE
Unmanaged-managed call transition callback

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#45118]
## Proposed API

A callback when a flow comes back from unmanaged into managed code.

## Usage Examples

```cs
BackToManaged += (sender, args) => {
  Console.WriteLine($"Back from {args.StackTrace}");
};

BackToManagedInCurrentThread += (sender, args) => {
  Console.WriteLine($"Back from {args.StackTrace}");
};
```

The use case is working with COM objects where there are many entry points into managed code.
It allows to implement behavior similar to Thread.Abort but in a safe and controlled way.

## Alternative Designs

Probably can be done with ComWrappers or Source Generators.

**Comment by jkotas** [comment]
This callback would introduce major performance regression in unmanaged-managed interop overhead.

> It allows to implement behavior similar to Thread.Abort but in a safe and controlled way.

Can you describe what you would like to do with this?

**Comment by NN---** [comment]
Ok, probably not for all unmanaged-managed calls the callback should be called :)

The situation is the following.
Suppose you have COM object with several methods which sometimes hangs for much time.
Using Thread.Abort you could signal this thread to throw whenever it returns from the COM object.
.NET 5 doesn't have Thread.Abort, and it is impossible to do this automatically.
You can add a manual code after every COM object method call but it is too tedious compared to the approach with Thread.Abort.

Let's focus on this good usage and not other bad usages of Thread.Abort :)
Given some generic callback, it would be easy to implement the old behavior in a safe and a customizable way.

**Comment by jkotas** [comment]
Thank you. This sounds like a problem for source generators.

**Comment by AaronRobinsonMSFT** [comment]
Closing this issue in lieu of the feature request captured in https://github.com/dotnet/runtime/issues/66674.
