### ISSUE TITLE
Bug With BackgroundWorking Not Working With Web Assembly Using .net 5

### ISSUE THREAD

**Issue by musictopia2** [dotnet/runtime#45110]
If I use the System.ComponentModel.BackgroundWorker and call the RunWorkerAsync method, then the entire page is unresponsive.  This problem does not happen on any native apps including android, windows, etc. but only with web assembly.

Here is code that would always duplicate the problem.

The class using the Backgroundworker.

using System;
using System.ComponentModel;

public class CustomClass
    {
        private readonly BackgroundWorker _backs;
        public CustomClass()
        {
            _backs = new BackgroundWorker();
            _backs.WorkerSupportsCancellation = true;

            _backs.DoWork += Backs_DoWork;
            _backs.RunWorkerCompleted += Backs_RunWorkerCompleted;
        }
        private bool _processing;
        private bool _isPaused;
        private int _elapsed;
        private bool _didStart;
        private EnumStartStatus _startStatus;
        public void StartTimer()
        {
            if (_didStart == true)
            {
                throw new Exception("The timer has already started.  Must stop the timer first");
            }
            _elapsed = 0;
            if (_processing == true)
            {
                _startStatus = EnumStartStatus.Over;
                return;
            }
            _backs.RunWorkerAsync();
        }
        public void PauseTimer()
        {
            if (_isPaused == true)
            {
                return;
            }
            _isPaused = true;
            _backs.CancelAsync();
        }
        public void ContinueTimer()
        {
            _isPaused = false;
            _startStatus = EnumStartStatus.FromPause;
        }
        public void StopTimer()
        {
            _didStart = false;
            if (_processing == true)
            {
                _backs.CancelAsync();
            }
        }
        public float TimeElapsed => (float)_elapsed / 1000;
        private void Backs_DoWork(object? sender, DoWorkEventArgs e)
        {
            _processing = true;
            do
            {
                Console.WriteLine("Backs Doing Work");
                if (e.Cancel == true)
                {
                    _processing = false;
                    return;
                }
                System.Threading.Thread.Sleep(10);
                _elapsed += 10;
            }
            while (true);
        }
        private enum EnumStartStatus
        {
            None = 0,
            FromPause = 1,
            Over = 2
        }
        private void Backs_RunWorkerCompleted(object? sender, System.ComponentModel.RunWorkerCompletedEventArgs e)
        {
            if (_startStatus == EnumStartStatus.None)
                return;
            if (_startStatus == EnumStartStatus.Over)
                _elapsed = 0;
            _backs.RunWorkerAsync();
        }
    }

The component using the class

public partial class CustomComponent
    {
        private string _message = "Beginning";

        private CustomClass _customs = new CustomClass();
        private bool _didStart;
        private void StartTest()
        {
            _didStart = true;
            _message = "Started";
            _customs.StartTimer();
        }

        private void ContinueTest()
        {
            _message = "Continued";
        }
    }

@if (_didStart)
{
    <button @onclick="ContinueTest">Continue Test</button>
}
else
{
    <button @onclick="StartTest">Start Test</button>
}
<br />
@_message

After I click the start, then it hangs.  If backgroundworker is not supported in webassembly, then how can a person do timer based stuff in web assembly.

**Comment by musictopia2** [comment]
I think it should be put under the blazor tag.  Because this does have to do with blazor.  Especially web assembly.  Since I doubt that timer stuff should work server side.

**Comment by kjpou1** [comment]
It does not look like we support BackgroundWorker very well right now since we do not support threads.

The Backs_DoWork has a very tight loop that is executed synchronously and never gives cycles back to the main thread.

```
private void Backs_DoWork(object? sender, DoWorkEventArgs e)
    {
        _processing = true;
        do
        {
            Console.WriteLine("Backs Doing Work");
            if (e.Cancel == true)
            {
                _processing = false;
                return;
            }
            System.Threading.Thread.Sleep(10);
            _elapsed += 10;
        }
        while (true);
    }

```

**Comment by musictopia2** [comment]
Are there any good alternatives for this for timer based apps?  I even tried creating self written async code but it failed as well.
Did something like this

async void Run()
{
do
await Task.Delay(10)
loop
}

to allow something that would always run when needed.  Even this fails as well.

**Comment by kjpou1** [comment]
Wouldn't a simple [`Timer`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer?view=net-5.0) do?  Maybe I am misunderstanding what you are trying to accomplish here.

The below work in a non Blazor application:

```

        private static System.Threading.Timer? syncTimer;
        public static void StartTestSync()
        {
            syncTimer = new System.Threading.Timer(async (object? stateInfo) =>
            {
                Console.WriteLine("StartTestSync before delay");
                await Task.Delay(10);
                //StateHasChanged(); // MUST CALL StateHasChanged() BECAUSE THIS IS TRIGGERED BY A TIMER INSTEAD OF A USER EVENT
            }, new System.Threading.AutoResetEvent(false), 1000, 1000);
        }

        private static System.Threading.Timer? asyncTimer;
        public static Task<string> StartTestAsync()
        {
            //await Task.Delay(10);
            asyncTimer = new System.Threading.Timer(async (object? stateInfo) =>
            {
                Console.WriteLine($"StartTestAsync before delay {stateInfo}");
                await Task.Delay(10);
                //StateHasChanged(); // MUST CALL StateHasChanged() BECAUSE THIS IS TRIGGERED BY A TIMER INSTEAD OF A USER EVENT
            }, new System.Threading.AutoResetEvent(false), 1000, 1000);
            return Task.FromResult("StartTestAsync");
        }

        public static void StartTestTaskSync()
        {
            Task.Run(() => StartTaskAsync("StartTestTaskSync"));
        }

        private static System.Threading.Timer? taskAsyncTimer;
        public static async Task<string> StartTestTaskAsync()
        {
            return await Task.Run(() => StartTaskAsync("StartTestTaskAsync"));
        }

        static string StartTaskAsync(string origin)
        {
            taskAsyncTimer = new System.Threading.Timer(async (object? stateInfo) =>
            {
                Console.WriteLine($"{origin} before delay {stateInfo}");
                await Task.Delay(10);
                //StateHasChanged(); // MUST CALL StateHasChanged() BECAUSE THIS IS TRIGGERED BY A TIMER INSTEAD OF A USER EVENT
            }, new System.Threading.AutoResetEvent(false), 1000, 1000);
            return "StartTaskAsync";
        }



``` 


There is some documentation on the [Blazor lifecycle component initialization](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-5.0#component-initialization-methods).

I remember that there was something special for async and threads but not sure exactly.  Maybe it is the [OnInitializedAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.componentbase.oninitializedasync?view=aspnetcore-5.0)



\cc @mkArtakMSFT @pranavkm @javiercn

**Comment by pranavkm** [comment]
The sample @kjpou1 using Timer should be a fairly good replacement for `BackgroundWorker`. If all you need as async while loop, https://taurius.medium.com/blazor-building-a-timer-and-a-stopwatch-5aea682147aa has an example of doing something fairly similar.

**Comment by kjpou1** [comment]
I am going to go ahead and close this out.
