### ISSUE TITLE
Optimize storage for IcuLocaleData data

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#45129]
The massive string which is declared in https://github.com/dotnet/runtime/blob/e2099f62f1ee28241f857edaf0ef7420018d11d8/src/libraries/System.Private.CoreLib/src/System/Globalization/IcuLocaleData.cs#L32 is cost close to 10kb on the disc. It should be possible to optimize this to reduce the size as the data are in a very narrow range (low case ASCII only).

@eerhardt

**Comment by tarekgh** [comment]
@marek-safar I am not sure I follow your suggestion here. How you suggest to optimize that? do you suggest we compress it and expand it at runtime?

**Comment by krwq** [comment]
@tarekgh I think suggestion might be to use UTF-8 or partially ASCII rather than UTF-16, that should remove almost half of the bytes

**Comment by marek-safar** [comment]
> do you suggest we compress it and expand it at runtime

Yeah, story it more efficiently so we don't have a massive string in metadata and on a whole copy of it on the heap. Most apps will use a few lcid strings only anyway. There are numerous way how to do it one of them could be to replace `s_lcids`, `s_localeNamesIndices` arrays with something like

```csharp
static ReadOnlySpan<byte>values => new byte[] {
   // "az" or "az-cyrl" or "az-cyrl-az" 
   (byte)'a', (byte)'z', (byte)'-', (byte)'c', (byte)'y', (byte)'r', (byte)'l', (byte)'-', (byte)'a', (byte)'z', 
};

// LCID values don't match the real ones in this example
static readonly int[] s_lcids = new int[]
{
   // 16bit LCID | index into string values | string value length
   0x10 | 0 << 12 | 7 << 4, // az-cyrl
   0xbb | 0 << 12 | 2 << 4, // az
};
```

There is a dependency from `c_localeNames` but that could be improved as well
