### ISSUE TITLE
Fix the CopyNupkgAndChangeVersion task

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#45122]
CopyNupkgAndChangeVersion  task got removed in the https://github.com/dotnet/runtime/commits/master/tools-local/tasks/installer.task

we only use this task while producing stable version and is broken for the master branch.

cc @dagood @NikolaMilosavljevic @ViktorHofer @ericstj @joperezr

**Comment by NikolaMilosavljevic** [comment]
[Triage] @jkoritzinsky was this task removed with SharedFX refactoring?

**Comment by jkoritzinsky** [comment]
Yep this was removed.

**Comment by Anipik** [comment]
so do we no longer require this task while building stable packages ?

**Comment by jkoritzinsky** [comment]
We shouldn’t as far as I know. Where was this used for building stable packages?

**Comment by Anipik** [comment]
https://github.com/dotnet/runtime/blob/master/src/installer/tests/PrepareTestAssets/PrepareTestAssets.proj#L3 

here

**Comment by ViktorHofer** [comment]
Looks like a left-over that should be removed.

**Comment by jkoritzinsky** [comment]
Yes, that leftover should be removed. We never use that task now.
