### ISSUE TITLE
Blazor WASM .NET 5 TimeZoneInfo DaylightName values not correct

### ISSUE THREAD

**Issue by jgilm** [dotnet/runtime#45136]
### Description
Using Blazor WASM with .NET 5, the information in `TimeZoneInfo.DaylightName` is incorrect and appears to mirror the `TimeZoneInfo.StandardName`.

### Actual Behavior:
`TimeZoneInfo.DaylightName` is identical to `TimeZoneInfo.StandardName`.
For example using this code
```
                @foreach (var tz in TimeZoneInfo.GetSystemTimeZones().OrderBy(tz => tz.BaseUtcOffset))
                {
                    <tr>
                        <td>@tz.Id</td><td>@tz.DisplayName</td><td>@tz.StandardName</td>
                        <td>@tz.SupportsDaylightSavingTime</td><td>@tz.DaylightName</td>
                        <td>@tz.BaseUtcOffset</td>
                    </tr>
                }
```
produces

![image](https://user-images.githubusercontent.com/2531809/100036583-5565d680-2db5-11eb-93d0-972cd6a6c422.png)

### Expected Behavior:
`TimeZoneInfo.DaylightName` is different (and correct) for time zones that support daylight saving time. 
For example, in a .NET 5 console application the same values look like this:

![image](https://user-images.githubusercontent.com/2531809/100035921-08cdcb80-2db4-11eb-9427-f53d7dd90b7a.png)
Pacific Standard time in a .NET 5 console app shows that the `StandardName` is "Pacific Standard Time" and the `DaylightName` is "Pacific Daylight Time"

This may be partially related to https://github.com/dotnet/runtime/issues/44840

### Configuration

- NET 5
- Blazor WASM
- Windows 10
- Chrome 86
- Project settings looks like this:
```
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>
```

### Regression?

This is a regression from Blazor WASM 3.2, which produces this result
![image](https://user-images.githubusercontent.com/2531809/100037233-8c88b780-2db6-11eb-90b3-cbf116dd3056.png)

### Other information

- I realize the time zone source may have changed, but the DisplayName field seems clunky as well compared to the Blazor WASM 3.2 version.
- Along with https://github.com/dotnet/runtime/issues/44840. even with the project setting of `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` I can only get 14 time zones to display, and they are seemingly **random**.

**Comment by lewing** [comment]
@tqiu8 can you test the example on unix as well and make sure all the other issues are already tracked/resolved

**Comment by radical** [comment]
Just curious, do we have tests for this?

**Comment by safern** [comment]
> Just curious, do we have tests for this?

I just searched for that and it seems like we don't.

**Comment by lewing** [comment]
Looks like there is some crossover here with https://github.com/dotnet/runtime/issues/16232 ?

**Comment by tqiu8** [comment]
Yea it looks like the DaylightName and StandardName are the same in unix. Also the display name is basically of the format `(UTC+<diff>) StandardName` as well

**Comment by lewing** [comment]
I think we've found the issue with DaylightName and a fix is in progress.  The StandardName/DisplayName commonality is #16232
It is different from 3.2 because the core libraries have changed.

**Comment by tarekgh** [comment]
@lewing how did we use to get the display name in 3.2? did we carry the data back then?

**Comment by lewing** [comment]
@tarekgh I haven't verified the code but 3.2 Wasm used the mono/mono bcl with different timezone code which likely carried this data with it for compatibility with windows.  I can double check next week.
