### ISSUE TITLE
System.Management doesn't work on Windows versions without .NETFramework

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#45143]
[AB#1249431](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1249431)
### Description

System.Management requires wminet_utils.dll in order to perform must of it's functionality, however this component is missing on some SKUs / architectures of Windows which do not include .NETFramework (eg: ARM64, and others)
https://github.com/dotnet/runtime/blob/4486164506a56200e66cf4cd750fde6b54ab5abd/src/libraries/System.Management/src/System/Management/ManagementScope.cs#L308-L378

**Comment by ericstj** [comment]
Note that the original authors of this component recommend MMI as a replacement: https://github.com/dotnet/runtime/issues/24803#issuecomment-365008995

The latest version of this package does support ARM64:
https://www.nuget.org/packages/Microsoft.Management.Infrastructure/

@SteveL-MSFT do you know of anyone porting from System.Management to MMI: is it straight forward?

**Comment by danmosemsft** [comment]
> some SKUs / architectures of Windows which do not include .NETFramework (eg: ARM64, and others)

For non ARM64 - I assume you mean Windows Nano? I don't think we've gotten feedback on that gap so I guess ARM64 is the interesting case.

**Comment by danmoseley** [comment]
@ericstj should we close this, or at least it should move out of 6.0

**Comment by ericstj** [comment]
Agreed on moving to future.

**Comment by danmoseley** [comment]
I'm going to close this as there's no longer a partner ask and it's a legacy tech.
