### ISSUE TITLE
Unable to install 3.1.403 when 3.1.404 is already installed

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/runtime#45145]
I have multiple .NET Core SDK versions installed, including `3.1.404` (runtime `3.1.10`).
Because of a `global.json` dependency in a project I need to build, I now tried to install `3.1.403` (runtime `3.1.9`).

However, when executing the `dotnet-sdk-3.1.403-win-x64.exe` on my Windows machine, I am told that I already have a newer version installed and therefore cannot install this older one.

Since as far as I know, .NET Core installations are independent of each other, and I already have many older versions installed side-by-side to the `3.1.404` SDK, I consider it unexpected that I have to uninstall the `3.1.404` SDK, to then install the `3.1.403` SDK and finally the `3.1.404` SDK again.

Also, this process doesn't work. While uninstalling the `3.1.404` SDK, to then install the `3.1.403` SDK works as expected, installing the `3.1.404` SDK again after that removes the `3.1.403` SDK.

After uninstalling the `3.1.404` SDK and installing the `3.1.403` SDK:

```console
Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.107 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
```

After installing the `3.1.404` SDK (the `3.1.403` SDK is missing again):

```console
Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.107 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by huoyaoyuan** [comment]
> .NET Core installations are independent of each other

This should be for minor and sdk-feature-band versions.

**I think the reason for this behavior is the patch version override in installer since 3.0.** (e.g. installing 3.1.404 will remove 3.1.403 installation)

The suggested usage should be that unless for deterministic reproduction, you should always stay on latest patch level (`rollForward` in `global.json` should be at least `patch`). For determinism, using install script rather than installer should be better.

**Comment by lauxjpn** [comment]
> The suggested usage should be that unless for deterministic reproduction, you should always stay on latest patch level (`rollForward` in `global.json` should be at least `patch`). For determinism, using install script rather than installer should be better.

@huoyaoyuan I agree. However, deterministic reproduction is exactly what I am doing here (otherwise, I wouldn't really care).

I am also aware of a couple of workarounds (like extracting the SDK zip file to a local directory and using it from there).

But independent of that, installing the `3.1.404` SDK should not remove the `3.1.403` SDK.
And installing the `3.1.403` SDK after previously installing the `3.1.404` SDK should work as well.

**Comment by huoyaoyuan** [comment]
I have to say that this behavior is by-design. The msi installer treats patch update as a same package, not independent ones.

msi installer isn't the only way to install .NET Core components. While .NET Core is side-by-side, it doesn't mean that every related component will be side-by-side. (For example you can't install two stable versions of VS from the same channel)

**Comment by lauxjpn** [comment]
> For determinism, using install script rather than installer should be better.

@huoyaoyuan Alright, so using the install script is the way to go here then. Thanks!
