### ISSUE TITLE
Add IsIPv6UniqueLocal to IPAddress

### ISSUE THREAD

**Issue by huysentruitw** [dotnet/runtime#45148]
## Background and Motivation

The `IPAddress` class contains a property `IsIPv6SiteLocal`, but the IPv6 site local range has been deprecated since 2004.

Since October 2005, a new range has been reserved by IETF to denote "Unique Local Addresses" (ULA) for use within private networks. It would be nice if `IPAddress` also had a property that checks for this range.

See also https://en.wikipedia.org/wiki/Unique_local_address

## Proposed API

```csharp
namespace System.Net
{
    public class IPAddress
    {
        public bool IsIPv6UniqueLocal { get; }
    }
}
```

Where the property could be implemented as:

```csharp
public bool IsIPv6UniqueLocal
    => IsIPv6 && ((_numbers[0] & 0xFE00) == 0xFC00);
```

**Comment by Joe4evr** [comment]
For reference, the technical speclet for the proposal is:
```cs
namespace System.Net
{
    public partial class IPAdress
    {
        public bool IsIPv6UniqueLocalAddress { get; }
    }
}
```

**Comment by huysentruitw** [comment]
Yes, but IPAddress with double-d. Updated my original post.

**Comment by geoffkizer** [comment]
This seems like a good thing to do.

**Comment by karelz** [comment]
Triage: Sounds reasonable. Not a high priority, but we will take a PR once the API is formally approved in API review.
@huysentruitw are there other IPv6 properties we might consider exposing with this one?

**Comment by huysentruitw** [comment]
@karelz I'm not sure what the question is.

Regarding IPv6, we already have these properties:

| Property | Description
| --------- | ---
| IsIPv6LinkLocal | Gets whether the address is an IPv6 link local address.
| IsIPv6Multicast | Gets whether the address is an IPv6 multicast global address.
| IsIPv6SiteLocal | Gets whether the address is an IPv6 site local address.
| IsIPv6Teredo | Gets whether the address is an IPv6 Teredo address.

I think adding `IsIPv6UniqueLocalAddress` would make that list complete for now.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Net
{
    public partial class IPAddress
    {
        // Existing:
        // public bool IsIPv4MappedToIPv6 { get; }
        // public bool IsIPv6LinkLocal { get; }
        // public bool IsIPv6Multicast { get; }
        // public bool IsIPv6SiteLocal { get; }
        // public bool IsIPv6Teredo { get; }
        public bool IsIPv6UniqueLocalAddress { get; }
    }
}
```

**Comment by geoffkizer** [comment]
Note the approved name for this property is `IsIPv6UniqueLocal`, without "Address" on the end as originally proposed.
