### ISSUE TITLE
Test failure: System.Tests.GCExtendedTests.TryStartNoGCRegion_SOHSize

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45140]
failed in job: [runtime-libraries-coreclr outerloop 20201123.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=896312&view=ms.vss-test-web.build-test-results-tab&runId=28644460&resultId=104167&paneView=debug)

net6.0-OSX-Release-x64-CoreCLR_release-OSX.1013.Amd64.Open

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.InvalidOperationException: Allocated memory exceeds specified memory for NoGCRegion mode
   at System.GC.EndNoGCRegion() in /_/src/coreclr/src/System.Private.CoreLib/src/System/GC.cs:line 523
   at System.Tests.GCExtendedTests.<>c.<TryStartNoGCRegion_SOHSize>b__13_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 665

Child process:
  System.Runtime.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Void <TryStartNoGCRegion_SOHSize>b__13_0()
~~~

**Comment by Maoni0** [comment]
@cshung would you please take a look?

**Comment by cshung** [comment]
@v-haren Is there a dump for this test failure?

**Comment by v-haren** [comment]
There is no dump for this test failure yet. we are trying to get it.

**Comment by mangod9** [comment]
Closing since this doesnt appear to have a reproed in a while. Please create a new issue if it occurs on latest .net 6 buids.
