### ISSUE TITLE
Byte[] and IEnumerable<Byte> Serialize Differently

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#45147]
### Description
Run this code:
```
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO.Pipes;
using System.Linq;

namespace ConsoleApp16 {
    class Program {
        static void Main(string[] args) {

            var C = new {
                Data1 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 },
                Data2 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 }.ToList(),
                Data3 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 100 }.ToImmutableArray(),
                Data4 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 100 }.ToImmutableList(),
            };

            Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(C));
        }
    }
}
```
Data1 serializes into a Base64 encoded string (good!), Data2-4 serialize into an array of numbers (BAD!)

### Configuration
.NET 5.0 on Windows 10 x64

### Regression?
Not Sure

### Other information
I believe that all of the above should serialize to a base-64 encoded string.

**Comment by TonyValenti** [comment]
#area-Serialization 

@StephenMolloy 
@HongGit

**Comment by TonyValenti** [comment]
This also seems to have a very big impact on performance.

**Comment by huoyaoyuan** [comment]
This should be by design.
In practice, binary data are never accessed as `IEnumerable<byte>` because of the performance overhead. Thus, the base64 serializer is a special case.

**Comment by TonyValenti** [comment]
@huoyaoyuan I think that it is inconsistent that Byte[] serializes to Base64 but ImmutableArray<Byte> does not.

**Comment by scalablecory** [comment]
I don't think `IEnumerable<byte>` or `List<byte>` should be serialized as base64.

`ImmutableArray<byte>` does seem like a good candidate, though.

**Comment by layomia** [comment]
We likely won't make any changes here by default since that would be breaking. A custom converter can be written to get the desired semantics here. Closing since a change like this isn't on the roadmap for JSON for now (especially if it involves new API to opt-in). Can be revisited if proven to be blocking (i.e. a custom converter isn't a viable solution).
