### ISSUE TITLE
[Question] Custom the server name of SocketsHttpHandler

### ISSUE THREAD

**Issue by dylech30th** [dotnet/runtime#45144]
Since the `WinHttpHandler` has been abandoned in .NET 5(at least I cannot find `WinHttpHandler` anymore in `HttpClientHandler`'s source code)，the `SocketsHttpHandler ` seems becomes the only possible choice, but it has a default behavior that I cannot set the server name directly or disable it, it uses either the host of the request URI, or your specified Host header, my requirement is, I want to keep the URI host as server name (or use custom one) while I can specify the Host header

**Comment by ManickaP** [comment]
`WinHttpHandler` hasn't been abandoned completely, it's just been removed from the HttpClient dll, but it's still present in its own NuGet package: https://www.nuget.org/packagesSystem.Net.Http.WinHttpHandler/. You can still use it with .NET 5.

**Comment by dylech30th** [comment]
Do we have a way to satisfy what I want without WinHttpHandler? After all, I found that WinHttpHandler's debug message is quite Illegible compare to SocketsHttpHandler

**Comment by ManickaP** [comment]
Could you please post repro of what you're trying to achieve? Either your original `WinHttpHandler` one or what you got so far with `SocketsHttpHandler` and what you're exactly missing?

**Comment by dylech30th** [comment]
```cs
public class DelegatedHttpClientHandler : HttpClientHandler
    {
        private readonly bool directConnect;
        private readonly IHttpRequestInterceptor? interceptor;

        public DelegatedHttpClientHandler(IHttpRequestInterceptor? interceptor = null, bool directConnect = true)
        {
            this.directConnect = directConnect;
            this.interceptor = interceptor;
            ServerCertificateCustomValidationCallback = DangerousAcceptAnyServerCertificateValidator;
            SslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12;
        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            interceptor?.Intercept(request);

            if (directConnect)
            {
                var host = request.RequestUri?.DnsSafeHost;
                var isSslSession = request.RequestUri?.ToString().StartsWith("https://");

                request.RequestUri = new Uri($"{(isSslSession is true ? "https://" : "http://")}{Dns.GetSourceIpAddresses()[0]}{request.RequestUri?.PathAndQuery}");
                request.Headers.Host = host;
            }

            return await base.SendAsync(request, cancellationToken);
        }
    }
```
where `IHttpRequestInterceptor` is a custom interface given by the following definition:
```cs
public interface IHttpRequestInterceptor
    {
        void Intercept(HttpRequestMessage message);
    }
```

and I need to prevent the server name to be the same as the Host header(in other words, the real hostname)

**Comment by scalablecory** [comment]
`SocketsHttpHandler` has no way to specify SNI separate from the URI and Host header. Can you give any info on what scenarios you would use this in?

**Comment by samsosa** [comment]
I use this:
```cs
string? SocketsHttpHandler.SslOptions.TargetHost
```

**Comment by dylech30th** [comment]
> `SocketsHttpHandler` has no way to specify SNI separate from the URI and Host header.
> 
> Can you give any info on what scenarios you would use this in? This isn't clear to me from your example.

Well, this scenario is rather special, I need to access IP directly to bypass the firewall (the firewall detects it through both URI host and server name) but I need to specify the Host header to tell the server which host am I trying to access, but I don't want to let the hostname appears in the server name because its sent by cleartext which will makes it being sniffed by the firewall

**Comment by dylech30th** [comment]
> I use this:
> 
> ```cs
> string? SocketsHttpHandler.SslOptions.TargetHost
> ```

seems that it's only used by certificate validation according to the documentation, and my requirement is to find a way to set the server name during client hello

**Comment by samsosa** [comment]
I've never really checked this, but I believe it successfully influences the SNI in my case.

It is also noticed in the source code of the Runtime accordingly:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L270-L271

**Comment by dylech30th** [comment]
Through `SetupHandlerChain::SetupHandlerChain` we can found that a request process depends on `HttpConnectionPoolManager`
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L453-L471
and the requests are processed by `HttpConnectionPoolManager::SendAsync` in `HttpAuthenticatedConnectonHandler`:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpAuthenticatedConnectionHandler.cs#L18-L21
which invokes `HttpConnectionPoolManager::SendAsyncCore`
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L360-L366
and step into its body, it is clearly that `HttpConnectionPoolManager::SendAsyncCore` calls `HttpConnectionPoolManager::GetConnectionKey` to get a `HttpConnectionKey` and pass it to a `HttpConnectionPool`, then invoke `HttpConnectionPool::SendAsync`:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L316-L352
It is noticed that the `key.SslHostName` is passed into `HttpConnectionPool::ctor`, and if we look future into `GetConnectionKey`, there is a snippet about how to acquire the `SslHostName`:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L265-L278
which precisely implies what was aforementioned "it uses either the host of the request URI, or your specified Host header", we can find its application here:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L213-L249
`HttpConnectionPool` constructs several `SslOptions` using our `sslHostName` and `ConstructSslOptions`, and the later one is what your example points to:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L264-L288
According to my tracking steps above, I think change `SslOptions.TargetHost` won't work because no matter what value you set to it, it will always be modified at last in `ConstructSslOptions`

**Comment by samsosa** [comment]
Yup, indeed. The `TargetHost` setting seems to be completely ignored.

**Comment by samsosa** [comment]
I would say that this could be a bug.

Because `SslStream.AuthenticateAsClientAsync(targetHost: String.Empty);` switches off the SNI.

Accordingly there should be the distinction:

````cs
SocketsHttpHandler.SslOptions.TargetHost = null;  // Like now, from Host-Header or from Url-Host
SocketsHttpHandler.SslOptions.TargetHost = String.Empty;  // Disable SNI
SocketsHttpHandler.SslOptions.TargetHost = "SomeDnsOrIpEndPoint";  // Set the SslStream targetHost to SocketsHttpHandler.SslOptions.TargetHost
````

**Comment by dylech30th** [comment]
> I would say that this could be a bug.
> 
> Because `SslStream.AuthenticateAsClientAsync(targetHost: String.Empty);` switches off the SNI.
> 
> Accordingly there should be the distinction:
> 
> ````cs
> SocketsHttpHandler.SslOptions.TargetHost = null;  // Like now, from Host-Header or from Url-Host
> SocketsHttpHandler.SslOptions.TargetHost = String.Empty;  // Disable SNI
> SocketsHttpHandler.SslOptions.TargetHost = "SomeDnsOrIpEndPoint";  // Set the SslStream targetHost to SocketsHttpHandler.SslOptions.TargetHost
> ````

It seems like they just completely prevented this in higher abstraction layers such as `SocketsHttpHandler`, I think this might cause two problems: 1. If I have such a requirement like this seems I must implement the underlying by myself which would be complicated and it's somehow unworthy to write a network layer just for a little functionality(not to mention that it should be easy, just add a if branch to check if the  `TargetHost` is already present). 2. There would be a semantic issue because `TargetHost` is said to be used for certificate validating in docs but if you specify it in `SocketsHttpHandler` it might not work as you want because its assignment is completely ignored

**Comment by dylech30th** [comment]
> I would say that this could be a bug.
> Because `SslStream.AuthenticateAsClientAsync(targetHost: String.Empty);` switches off the SNI.
> Accordingly there should be the distinction:
> ```cs
> SocketsHttpHandler.SslOptions.TargetHost = null;  // Like now, from Host-Header or from Url-Host
> SocketsHttpHandler.SslOptions.TargetHost = String.Empty;  // Disable SNI
> SocketsHttpHandler.SslOptions.TargetHost = "SomeDnsOrIpEndPoint";  // Set the SslStream targetHost to SocketsHttpHandler.SslOptions.TargetHost
> ```

It seems like they just completely prevented this in higher abstraction layers such as `SocketsHttpHandler`, I think this might cause two problems: 1. If I have such a requirement like this seems I must implement the underlying by myself which would be complicated and it's somehow unworthy to write a network layer just for a little functionality(not to mention that it should be easy, just add an `if` branch to check if the `TargetHost` is already present). 2. There would be a semantic issue because `TargetHost` is said to be used for certificate validating in docs and **it does give us a set accessor** but if you specify it in `SocketsHttpHandler` it might not work as you want because its assignment is completely ignored

**Comment by samsosa** [comment]
I think the Dotnet team just forgot to include it here:
https://github.com/dotnet/runtime/blob/fdc6472bd1de22b3fe67e232ca86d0593d0b7ce7/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L265-L278

**Comment by karelz** [comment]
Triage: @wfurt to look at it and provide recommendation. We may need more info on the use case.

**Comment by huoyaoyuan** [comment]
The use case is non-standard that the server refuses SNI.
This maybe somehow unsafe. The client hardcodes the server ip and fingerprint. It doesn't ask for DNS.

This can be useful in some internal network.

**Comment by dylech30th** [comment]
The current workaround is rather more unsafe, I have to hook into runtime libraries and modify the runtime behaviors such as return value. IMO this should be considered as a design fault

**Comment by wfurt** [comment]
I think the SocketHttpHandler was never intended for tricks like this. This is conceptually similar to https://github.com/dotnet/runtime/issues/29149 where once in a while somebody wants to do something special. 

The caveat here is that the SslOptions is set on handler and the TargetHost needs to be set for each server. So you would effectively need to create new handler for each site you need to visit - pattern we try to discourage when possible as that is very inefficient . Or at least serialize access if you choose to mutate the options. That may not be concern for the special needs. 

Conceptually, this can be also fixed with  #46849. (so as #29149)


If you are desperate @dylech30th , for 5.0 you can construct `http://a.b.c.d/' URL and use [ConnectCallback](SocketsHttpHandler.ConnectCallback) to return SslStream. That would avoid all the TLS logic in HttpClient and give you complete control.

**Comment by huoyaoyuan** [comment]
@wfurt Thanks for your suggestion. I've built a working sample!

```csharp
    class DirectConnectHandler : HttpMessageHandler
    {
        private readonly HttpMessageInvoker _handler = new(new SocketsHttpHandler
        {
            ConnectCallback = async (context, ct) =>
            {
                var ip = CustomizeIP(context.DnsEndPoint.Host); // Get IP here

                var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
                await socket.ConnectAsync(IPAddress.Parse(ip), 443, cancellationToken: ct);
                var networkStream = new NetworkStream(socket, true);
                var sslStream = new SslStream(networkStream, false,
                    delegate { return true; });

                await sslStream.AuthenticateAsClientAsync(""); // whatever you want, "" means no SNI
                return sslStream;
            }
        });

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            _handler.Dispose();
        }

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            string? newUri = request.RequestUri!.ToString().Replace("https", "http", StringComparison.Ordinal);
            request.RequestUri = new(newUri);
            return _handler.SendAsync(request, cancellationToken);
        }
    }
```

**Comment by wfurt** [comment]
good to know @huoyaoyuan.  #46849 is still coming to 6.0 but now you don't have to wait for it :) It may give you more elegant solution at some point.

**Comment by karelz** [comment]
Triage: There is workaround and #42455 should solve this in 6.0. Closing this one as answered.
