### ISSUE TITLE
.NET Core/5 IConfiguration does not work on Raspberry Pi 4 4GB

### ISSUE THREAD

**Issue by Flaminel** [dotnet/runtime#45157]
I've had multiple apps installed on my ```32 bit Raspbian``` for the past 11 months or so with no problems to run them at all. Recently, I wanted to experiment with MongoDB and I needed a ```64 bit OS``` version to get the latest build, so I decided to go with ```Ubuntu Desktop 20.10 x64``` with ```ARM64``` architecture. After installing Ubuntu, I tried starting one of my apps to see if all is well and it is not. At first, I thought it was a problem with ```.NET 5``` (I migrated the app just to see if it works), but the problem persisted with ```.NET Core 3.1``` as well, although it worked just fine before the OS switch.

The problems is that ```IConfiguration``` does not have values for the ```appsettings.json``` files. ```IConfiguration``` contains ```appsettings.json``` and ```appsettings.Production.json``` as providers, the providers contain the sections that I have defined, the sections contain the defined keys, but there are only ```null``` values on all of them.

I am unable to run the ```32 bit version of dotnet``` on Ubuntu, so I cannot really pinpoint where the problem is coming from. Does anyone know why it might do that?

To be noted that I've also tried running another ```.NET Core``` app that I used to host on Raspbian, which is not developed by me, and I get the same results. Everything breaks because the configuration is broken.
Also, I have tried both the latest SDK and the latest Runtime binaries having the same results.
Also no2, it works just fine on my ```Windows 10 x64``` machine where I'm developing the apps. It seems like there is a problem with the ```ARM64``` binaries.

Startup.cs:
```
public class Startup
{
    public IConfiguration Configuration { get; }

    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public void ConfigureServices(IServiceCollection services)
    {
        MySettings settings = Configuration.GetSection("MyApp").Get<MySettings>();
    }
}
```
appsettings.json:
```
{
    "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "AllowedHosts": "*",
    "MyApp": {
        "Tokens": [
            "myAppToken1"
        ]
    }
}
```

**Comment by Flaminel** [comment]
After further investigation, multiple OS changes and going back to ```Raspberry OS x32```, I found out that the problem is still there no matter the OS. I don't know if I'm doing something wrong, but I've tried with both the SDK and runtime. By tinkering with a publish profile on one of my app I managed to get the configuration to work, although all my NuGet packages (the ones which are developed by me) that I am using in the app still can't read the configuration. After deleting the publish profile and all the built files and just building in ```Release```, the app could still read the configuration (the NuGet packages still couldn't). I am scratching my head from all sides because I do not remember doing any additional steps to make .NET apps work on my Raspberry, other than downloading de SDK/runtime.

**Comment by davidfowl** [comment]
Most likely suspect is the wrong base path.

**Comment by Flaminel** [comment]
> 
> 
> Most likely suspect is the wrong base path.

Could you please elaborate?

**Comment by davidfowl** [comment]
There's an extension method on IConfigurationRoot called GetDebugView(https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationrootextensions.getdebugview?view=dotnet-plat-ext-5.0) that dumps all configuration values and where they were read from (which provider). It might prove useful for debugging here. 

How are you sure the configuration is being read from the right place?

**Comment by Flaminel** [comment]
If I remember correctly, I wrote some debugging code that was was writing to the console information from the IConfiguration object injected in the Startup class and, although the values were null, the keys that I've defined in appsettings.json were present.

I've been at this for some days now and it seems that you were right. It was something about the base path. The main problem was that I did not define the ```WorkingDirectory``` variable in the App.service file as I did before installing Ubuntu on my Raspberry. I tested this with an app and it's working when the variable is set, and not working when it's not.

The App.service file should look like this:
```
[Unit]
Description=App

[Service]
WorkingDirectory=/var/www/App/
ExecStart=dotnet /var/www/App/App.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=App
Environment=ASPNETCORE_URLS="http://localhost:5000"

[Install]
WantedBy=multi-user.target
```

Thank you for getting me on the right tracks, @davidfowl !
