### ISSUE TITLE
UWP cannot iterate resources

### ISSUE THREAD

**Issue by solocle** [dotnet/runtime#45151]
### Description

Cannot iterate ResourceMap - The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)

### Configuration

* Which version of .NET is the code running on? Microsoft.NET.CoreFramework.Debug.2.2_2.2.28529.0_x64__8wekyb3d8bbwe
* What OS and version, and what distro if applicable? Windows 10 v1909
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No
* If you're using Blazor, which web browser(s) do you see this issue in? N/A

### Regression?

Unknown

### Other information

Exception thrown: 'System.Exception' in System.Private.CoreLib.dll
The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)

Function:
```
Private Shared Function ReadLanguageFromApplicationResources(LanguageTag As String) As Dictionary(Of String, Tuple(Of String, String))

        Dim ResourceMap = ResourceManager.Current.MainResourceMap.GetSubtree("Resources")
        If ResourceMap Is Nothing Then
            Return Nothing
        End If

        Dim ResourceContext = New ResourceContext With {
            .Languages = {LanguageTag}
        }

        Dim IdToTranslation = New Dictionary(Of String, Tuple(Of String, String))
        Try
            For Each pair In ResourceMap
                Dim value = pair.Value.Resolve(ResourceContext).ValueAsString
                IdToTranslation.TryAdd(pair.Key, New Tuple(Of String, String)(value, ""))
            Next '<--- Exception is thrown here after two iterations
        Catch e As Exception
        End Try

        Return IdToTranslation

    End Function
```

**Comment by tarekgh** [comment]
The repro code is just calling WinRT APIs and throwing from that. I changed the label to the interop as the issue more about how we are interoping with WinRT.

**Comment by AaronRobinsonMSFT** [comment]
@tommcdon This appears to be a UWP specific scenario. What are your thoughts here? We should validate C#/WinRT supports this scenario but I am inclined to say this doesn't meet the bar of the built-in WinRT support in older scenarios.

**Comment by tommcdon** [comment]
Unfortunately right now we have other competing priorities and so this will not be fixed in the current release under development.  While we would like to fix each and every bug that is reported to us we do not have the time to fix all of them.  We will re-evaluate fixing this in a future version.

**Comment by AaronRobinsonMSFT** [comment]
After discussing the scope of impact of the issue and current direction of WinRT API support, I am going to close this issue. The future direction of WinRT and .NET can be found in the [C#/WinRT repo](https://github.com/microsoft/CsWinRT).
