### ISSUE TITLE
Why is double type rounded different in .NET Framework/.NET Core 2.1 compared to .NET Core3.1/.NET 5?

### ISSUE THREAD

**Issue by pergardebrink** [dotnet/runtime#45160]
When a double is multiplied (in this example by 100), it is rounded differently on .NET Framework 4.8/.NET Core 2.1, compared to .NET Core 3.1/.NET 5. Is this change intentional and the way it is supposed to be?

csproj to reproduce:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;netcoreapp2.1;netcoreapp3.1;net5.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```
Program.cs
```
double value = 0.567;
Console.WriteLine(value);
value = value * 100;
Console.WriteLine(value);
```

```
C:\dev\rounded>dotnet run --framework net48
0,567
56,7

C:\dev\rounded>dotnet run --framework netcoreapp2.1
0,567
56,7

C:\dev\rounded>dotnet run --framework netcoreapp3.1
0,567
56,699999999999996

C:\dev\rounded>dotnet run --framework net5.0
0,567
56,699999999999996
```

### Configuration
* .NET Framework 4.8, .NET Core 2.1, .NET Core 3.1, .NET 5
* Windows 10 (x64)

**Comment by jkotas** [comment]
This is documented in https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#floating-point-formatting-and-parsing-behavior-changed and explained in detail in https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by pergardebrink** [comment]
Ah, thank you very much for the clarification! I realize I should have tried to look in the list of breaking changes somewhere between 2.1 and 3.1 before posting the issue!
