### ISSUE TITLE
ResourceManager.GetString(resourceKey);  Compiler Error: CS0120  

### ISSUE THREAD

**Issue by iweixubin** [dotnet/runtime#45161]
area-Extensions-Primitives

I download net5 source code
I create a new solution
add Microsoft.Extensions.Primitives.csproj to new solution
https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/SR.cs

``` cs
        internal static string GetResourceString(string resourceKey, string? defaultString = null)
        {
            if (UsingResourceKeys())
            {
                return defaultString ?? resourceKey;
            }

            string? resourceString = null;
            try
            {
                resourceString =
#if SYSTEM_PRIVATE_CORELIB
                    InternalGetResourceString(resourceKey);
#else
                    ResourceManager.GetString(resourceKey);// Compiler Error: CS0120
#endif
            }
            catch (MissingManifestResourceException) { }

            if (defaultString != null && resourceKey.Equals(resourceString))
            {
                return defaultString;
            }

            return resourceString!; // only null if missing resources
        }
```
public class ResourceManager{
public virtual string GetString(string name);
}

how can i fix it?

**Comment by iweixubin** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

area-Extensions-Primitives

**Comment by huoyaoyuan** [comment]
> I create a new solution
add Microsoft.Extensions.Primitives.csproj to new solution

Never do this. The BCL source uses complex project references.

The **supported way** to browse it source is open through the `build.cmd` script, for example, `.\build.cmd -vs Microsoft.Extensions.Primitives`.

For current time point, double-clicking `src\libraries\Microsoft.Extensions.Primitives\Microsoft.Extensions.Primitives.sln` is also OK.

**Comment by iweixubin** [comment]
> > I create a new solution
> > add Microsoft.Extensions.Primitives.csproj to new solution
> 
> Never do this. The BCL source uses complex project references.
> 
> The **supported way** to browse it source is open through the `build.cmd` script, for example, `.\build.cmd -vs Microsoft.Extensions.Primitives`.
> 
> For current time point, double-clicking `src\libraries\Microsoft.Extensions.Primitives\Microsoft.Extensions.Primitives.sln` is also OK.
> 
> I'm not sure whether it's OK for first time. The script will also download and restore necessary arcade SDK.

I don't want to it dependent on sdk
I put the source code in a new solution and add them by “Add - Project Reference”
then I can read source code F12，F12，F12 ...  run debug F11，F11，F11...
write some comment let me to understand

sdk is not good for me，it can't  F12，F12，F12 ... F11，F11，F11...
can't write  comment !!!

I've done this before, when source code was v3.1


```cs
public class ResourceManager{
public virtual string GetString(string name); // it is not static method,how Compiler it
}
```

**Comment by huoyaoyuan** [comment]
Using Chinese to clarify what I mean.

> put the source code in a new solution

这里的源代码不是这么工作的；“源代码”不仅仅是一个project，整个dotnet/runtime是一个整体

> I've done this before, when source code was v3.1

3.1时代，Microsoft.Extensions是按照第三方（“常规”）库的模式来构建的；
5.0时代，挪入dotnet/runtime之后，必须采用特殊的构建方式；因为此处是用来构建标准库的，所以必须采用特殊的工作流程

> then I can read source code F12，F12，F12 ... run debug F11，F11，F11...

我个人的建议：
先执行一遍build.cmd（`build libraries`），完成特殊构建；
然后将你要调试的入口加入到现有的sln，而不是创建新的sln
不要移动文件夹位置，否则会破坏`Directory.Build.props`中的属性

**Comment by iweixubin** [comment]
@huoyaoyuan 

在 3.1 的时候就看过别人说怎么阅读和调试 asp.net 源码，也试了，但不是都是我想要的方式
所以我绕了一圈去学习 MSBuild 是怎么使用的，还有 Directory.Build.props 怎么配置
才把 Microsoft.Extensions 和 Asp.Net 整合成一个 solution，
这样阅读和调试代码真的是一气呵成~

现在不说整合代码的事情，
`ResourceManager.GetString(resourceKey); ` 是违法 C# 语法的啊，
通过什么配置让编译器绕了过去呢？

**Comment by huoyaoyuan** [comment]
最稳定的调试源代码方法应该是使用SourceLink，在VS的调试->窗口->模块里找到对应的模块可以手动加载符号

> `ResourceManager.GetString(resourceKey); ` 是违法 C# 语法的啊

strings.resx文件在编译后，会生成一个`SR.g.cs`，其中有这样的成员：
```csharp
    internal static partial class SR
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(FxResources.Microsoft.Extensions.Primitives.SR)));
```

类型名和成员名相同，所以看起来就像在调用静态方法一样

所以你需要的是让resx被包括进生成中，在VS属性浏览器里可以找到关键词`MSBuild:_GenerateResxSource`，搜索一下吧

**Comment by huoyaoyuan** [comment]
The actual area should be area-Infrastructure. He has question about building it after custom modification of the source.

**Comment by eerhardt** [comment]
@ViktorHofer - any tips on how to use the `.csproj` files in a separate solution? I don't know how to set up our build system to allow the projects to be used this way.

**Comment by ViktorHofer** [comment]
What do you mean by using the csproj files in a separate solution? sln files are only sugar in dotnet/runtime and aren't exercised in CI afaik.

**Comment by ViktorHofer** [comment]
Maybe you can provide an example of what you meant?
