### ISSUE TITLE
Inbox package trimming not happening on net6.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#45163]
Looks like our package index is missing some entries for 6.0.0.0 assemblies.

https://github.com/dotnet/runtime/blob/2e8c4c78d5dc628afd94053a008ab203e648a2b9/src/libraries/pkg/baseline/packageIndex.json#L6627-L6630

This is causing unnecessary PackageReferences to be included in nuspecs when libraries use any shared-framework overlapping packages (EG: System.Text.Json, Immutable, etc).

See https://github.com/dotnet/sdk/pull/14574#issuecomment-733151414

**Comment by ericstj** [comment]
We could catch this in package-testing.  For any package that overlaps with the shared framework, make sure that we don't see a package-reference to that package when on the latest TFM.

**Comment by ViktorHofer** [comment]
Closing as we don't trim inbox dependencies anymore (when matching versions) with PackageReferences.
