### ISSUE TITLE
system net IPAddress parses ipv6 with port but fails to parse ipv4

### ISSUE THREAD

**Issue by dzmitry-lahoda** [dotnet/runtime#45194]
## Background and Motivation

IPAddress parses ip6 with ports, but fails same for ip4. I think both kinds should work.

I do not think this is bug (because yes - ip:port is not ip). But because ipv6:port is parsed with ip, may be ipv4 should too.

## Proposed API

```c#
var noException = IPAddress.Parse("127.0.0.1:42")
Assert.True(IPAddress.TryParse("127.0.0.1:42", out var _));
```

## Risks

Somebody expected parse with port to fail always.

**Comment by wfurt** [comment]
what is your example for IPv6?

**Comment by karelz** [comment]
IPv6 address is parsed also when port is included -- e.g. `[::1]:8080`. The port is ignored. To parse port, one should use `IPEndPoint`.
Tested on .NET 5 and .NET Framework 4.7.2.

IMO it would be nice to ignore the port in IPv4 as well, but given there is `IPEndPoint` and that this is first report in 20+ years, it is not priority.

**Comment by karelz** [comment]
Triage: `Parse` methods should parse entire string, not just part -- they do not have option to expose how many characters they parsed. As such, we believe the IPv4 behavior to fail with presence of port is correct.
Fixing IPv6 would a breaking change. Given that the value is low, we don't plan to fix it, unless there is more evidence that it won't break too many customers and that it would be really beneficial.
