### ISSUE TITLE
Windows developers get warnings when call APIs that aren't available on the OS version they want to target

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#45192]
We already have the analyzer, but this work captures ensuring the CsWinRT definitions of the Windows SDK are using the platform compatibility annotations (as opposed to Windows proprietary ones).

https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md#attributes

- [x] Change SupportedOSPlatformAttribute warning https://github.com/dotnet/runtime/issues/47593

**Comment by danmoseley** [comment]
@buyaa-n @terrajobst anything left to do here? If not please close this.

**Comment by terrajobst** [comment]
I think we can close this. @buyaa-n @jeffhandley?

**Comment by buyaa-n** [comment]
Yes, by https://github.com/dotnet/runtime/issues/47593#issuecomment-876805112 it can be closed
