### ISSUE TITLE
Blazor WebAssembly .net 5 TimeZoneInfo.GetSystemTimeZones() not returning full list

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#45195]
I am using Blazor WebAssembly .net 5.
timeZones = TimeZoneInfo.GetSystemTimeZones();
return 14 zone only
How do i get the full list ?

**Comment by mkArtakMSFT** [comment]
@lewing  FYI

**Comment by kjpou1** [comment]
This looks to be a duplicate of https://github.com/dotnet/runtime/issues/44840.  This is being tracked there.
