### ISSUE TITLE
Need to expose a way to handle SIGTTIN/SIGTTOU

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#452]
[AB#1240696](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1240696)
For PowerShell, you can start a sub-process that owns the console.  In `gdb`, I can see that `SIGTTIN` is being sent to `pwsh`, but there is currently no way for `pwsh` to handle this signal indicating it doesn't own the console and should stop reading from it.  This eventually results in a crash in pwsh as it tries to use the Console APIs and gets an unhandled exception.

**Comment by stephentoub** [comment]
Have you tried using https://www.nuget.org/packages/Mono.Posix.NETStandard?

**Comment by eiriktsarpalis** [comment]
FWIW `Mono.Posix` does seem to [support handling signals](https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/Mono.Posix/Mono.Posix/Syscall.cs#L349-L352).

**Comment by jeffhandley** [comment]
@SteveL-MSFT Could you let us know if using `Mono.Posix` would be acceptable for you to take a dependency on and if it would meet your needs. For now at least, we won't plan to pursue adding this functionality.
