### ISSUE TITLE
Optimize the Skip() method for Utf8JsonReader

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#45200]
## Background and Motivation
We have a use case of the `Utf8JsonReader` that read the 1st level of depth of the JSON and does not care, at first glance, of the sub levels. we are using the `Skip()` method for avoiding to read useless JSON members. Most of the time is consumed by the `Read()` (end implicitly by `ConsumeNextTokenOrRollback()` and `ConsumeValue()`).
The proposal is to rewrite the `Skip()` method by avoiding to use the `Read()` method. 

The `Skip()` method only require the properties `CurrentDepth` & `TokenType` up to date. 

## Proposed API
No change.

## Usage Examples
N/A

## Alternative Designs
Implement a `SkipWithoutValidation()` method that do the job.

## Risks
More code to maintains. 
The behaviour may change if the JSON is incorrect, because most of the optimisations would be to jump to the closing bracket/brace without validating the skipped data.

**Comment by layomia** [comment]
Can you provide a sample implementation and/or numbers to show what optimizations you have in mind?

**Comment by ycrumeyrolle** [comment]
In term of performance when parsing a JSON:
The JSON to parse:
```JSON
{
  "iss": "https://idp.example.com/",
  "jti": "756E69717565206964656E746966696572",
  "iat": 1594824782,
  "aud": "636C69656E745F6964",
  "txn": "meN8paRMSS",
  "toe": 1508184845,
  "events": {
    "https://schemas.openid.net/secevent/risc/event-type/account-enabled": {
      "subject": {
        "subject_type": "account",
        "uri": "acct:john.doe%40example.com@service.com"
      },
      "device": {
        "subject_type": "user_agent",
        "user_agent": "Mozilla",
        "ip_address": "192.168.0.2",
        "ip_port": 8765
      }
    }
  }
}
```
The member "events" is skipped.
![image](https://user-images.githubusercontent.com/1958836/100738005-42668e00-33d5-11eb-8160-79effe7d6506.png)
The [`SkipObject()`](https://github.com/uruk-project/Jwt/blob/54fa8a6ba0be76549bf8ece54363267f599b7703/src/JsonWebToken/Reader/Utf8JsonReaderHelper.cs#L27) method is equivalent to the original method `Skip()`. It tooks 58% of the time to just skip to the next object.

Currently I have not concrete clue on the optimization implementation, but I assume that the `Read()` is currently doing a lot of work that is not required for skipping to the next object/array.
