### ISSUE TITLE
Double bounds checks in List<T>

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#45206]
```csharp
int First(List<int> list) => list[0];
```
Codegen:
```asm
G_M49643_IG01:
       sub      rsp, 40
G_M49643_IG02:
       cmp      dword ptr [rdx+16], 0
       jbe      SHORT G_M49643_IG05
G_M49643_IG03:
       mov      rax, gword ptr [rdx+8]
       cmp      dword ptr [rax+8], 0
       jbe      SHORT G_M49643_IG06 ;; <-- redundant check
       mov      eax, dword ptr [rax+16]
G_M49643_IG04:
       add      rsp, 40
       ret      
G_M49643_IG05:
       call     System.ThrowHelper:ThrowArgumentOutOfRange_IndexException()
       int3     
G_M49643_IG06:
       call     CORINFO_HELP_RNGCHKFAIL ;; <-- redundant check
       int3     
; Total bytes of code: 40
```

Obviously it happens because JIT doesn't know that `_size` is always less (or equal) than `_items.Length`. I wonder if we can improve it. (see https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L148)
Same happens for indexer's setter:
```csharp
myList[i] = 42
```
Also, redundant bounds checks are generated even when we simply iterate the list:
```csharp
void Loop(List<int> list)
{
    foreach (var item in list) // same for "for"
    {
        // two bounds checks each iteration!
    }
}
```
IMO, `List` is a quite popular data structure so it worth optimizing them out.

**Comment by jkotas** [comment]
> Obviously it happens because JIT doesn't know that _size is always less (or equal) than _items.Length

This condition can be violated by using List incorrectly from multiple-threads. 

Our general standard is that race-conditions in safe user code shall not lead to buffer overruns inside the BCL.

**Comment by EgorBo** [comment]
> > Obviously it happens because JIT doesn't know that _size is always less (or equal) than _items.Length
> 
> This condition can be violated by using List incorrectly from multiple-threads.
> 
> Our general standard is that race-conditions in safe user code shall not lead to buffer overruns inside the BCL.

The bound check could look like this then:
```csharp
if ((uint)index >= Math.Min(_size, items.Length) /*CMOV*/) ThrowHelper....
return items[index]; // no bounds checks here.
```

**Comment by jkotas** [comment]
Also, it is not clear whether it would actually save anything meaningful. You are replacing two well-predicted independent conditional jumps that can execute in parallel with data-dependent conditional jump that has to be executed serially.

**Comment by GrabYourPitchforks** [comment]
One possible area of improvement in `List<T>` is to use an invariant array as the backing store. This would elide variance checks on write. Really only useful for `List<IMyInterface>` or `List<AbstractBaseClass>`, but this might be common enough to be worth pursuing.

**Comment by EgorBo** [comment]
> Also, it is not clear whether it would actually save anything meaningful. You are replacing two well-predicted independent conditional jumps that can execute in parallel with data-dependent conditional jump that has to be executed serially.

Makes sense, third option: redirect the default bounds check to the existing one, like this:

```
G_M49643_IG01:
       sub      rsp, 40
G_M49643_IG02:
       cmp      dword ptr [rdx+16], 0
       jbe      SHORT G_M49643_IG05
G_M49643_IG03:
       mov      rax, gword ptr [rdx+8]
       cmp      dword ptr [rax+8], 0
       jbe      SHORT G_M49643_IG05
       mov      eax, dword ptr [rax+16]
G_M49643_IG04:
       add      rsp, 40
       ret      
G_M49643_IG05:
       call     System.ThrowHelper:ThrowArgumentOutOfRange_IndexException()
       int3    
; Total bytes of code: 40
```

**Comment by jkotas** [comment]
We should not need to have a special attribute for this. The JIT should be produce this code if you do the bounds check manually like this:
```
                // Following trick can reduce the range check by one
                T[] items = _items;
                if ((uint)index >= (uint)_size || (uint)index >= items.Length)
                {
                    ThrowHelper.ThrowArgumentOutOfRange_IndexException();
                }
                return items[index];
```

**Comment by jkotas** [comment]
> invariant array as the backing store

Explored in #45206

**Comment by GrabYourPitchforks** [comment]
Explored, but not rejected. It was met with an exasperated sigh. 😉

**Comment by JulieLeeMSFT** [comment]
CC @briansull

**Comment by briansull** [comment]
I will take a look

**Comment by briansull** [comment]
This looks like expected behavior

**Comment by EgorBo** [comment]
@briansull feel free to close it if you think there is nothing we can do here (it looks so)

**Comment by briansull** [comment]
Expected behavior
