### ISSUE TITLE
Consider source generator for AsnXml

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#45210]
Currently the way the the Asn.xml.cs files are generated [uses an XSLT transformation][xslt] in an MSBuild task to convert the XML files to generated C#. It might be beneficial to use a C# source generator instead. This would provide a better developer experience 1. Because currently I believe the XSLT transformation requires "Desktop" MSBuild (or mono), and does not work with the `dotnet msbuild` MSBuild and 2. in places like Visual Studio the developer experience is a lot better.

[xslt]: https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Security/Cryptography/Asn1/asn.xslt

**Comment by bartonjs** [comment]
Yeah, it's something that was on my think-about/TODO list.  FWIW, I think that MSBuild might have recently added the XsltTransform to their .NET (Core) version, so it might be that the targets file can be updated to remove the disparity.

One of the things that has been great about the current model is that the source files show up on source.dot.net; that's something I'd like to keep true under any change.  I don't know that we have any examples of using it in dotnet/runtime yet to see how that manifests.

**Comment by vcsjones** [comment]
> FWIW, I think that MSBuild might have recently added the XsltTransform to their .NET (Core) version

I think you're right.. let me see if I can get that working as a simpler first step.

**Comment by am11** [comment]
It is possible to persist the generated code .cs file. Say `MyGenerator.csproj` is referenced by `MyLibrary.csproj`, which in turned is referenced by `MyExecutableApp.csproj`. In this setup, if we add the following property in `MyLibrary.csproj`:
```csproj
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>
```
then the generated code will persist under `MyLibrary/obj/$(Configuration)/net5.0/generated/` by default. The output location can be controlled by yet another property in the same (MyLibrary) project:
```csproj
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>.\my_generator_dir</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
```

**Comment by vcsjones** [comment]
Since the major issue for this has been solved (needing Desktop MSBuild) and this is considerable work for little benefit, I am going to close this.
