### ISSUE TITLE
JsonExtensionData doesn't use registered Converters when deserializing

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/runtime#45211]
When deserializing an object into:

```csharp
[JsonExtensionData]
public IDictionary<string, object> Extensions { get; set; }
```

The values are coming in as JsonElement's instead of as their inferred objects. I'm using the `ObjectToInferredTypesConverter` that's provided here https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#deserialize-inferred-types-to-object-properties

But that's apparently not being called.

**Comment by layomia** [comment]
@clairernovotny, why did you close this issue? It seems like a reasonable request (honor custom converter for `System.Object` or `JsonElement`), if there's a strong reason or blocked scenario.

**Comment by clairernovotny** [comment]
I closed it because it was a user error -- it actually does already work, I had been using a different instance of the settings without the converter registered where I saw the issue.
