### ISSUE TITLE
Proposal: ability to get a delegate* from a DynamicMethod

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#45232]
## Background and Motivation

With function pointers being introduced in C# 9, they seem to be a good candidate for speeding up code paths involving delegates for dynamic code, for developers willing to take the time to sift through the extra complexity there. There are a number of issues right now when using the `DynamicMethod` class to create a custom delegate. Consider this:

```csharp
DynamicMethod method = new DynamicMethod("Test", typeof(int), new[] { typeof(int) });
ILGenerator il = method.GetILGenerator();

il.Emit(OpCodes.Ldarg_0);
il.Emit(OpCodes.Ldc_I4_1);
il.Emit(OpCodes.Add);
il.Emit(OpCodes.Ret);

Func<int, int> func = method.CreateDelegate<Func<int, int>>();

// Use the delegate here
```

There are two main issues here:

- You have to allocate a `Delegate`. This can of course be amortized if the function will be used for long, but still.
- Invoking a `Delegate` is relatively slow. Even more so for delegates wrapping a static method, as `Delegate.Invoke` is specifically optimize to favor performance for instance methods first (which I guess is also why the C# compiler rewrites static lambda expressions as static singleton instance delegates instead of static ones).

There seems to be no way right now (except for hacking `DynamicMethod.GetMethodDescriptor` via reflection) to get a managed function pointer to a dynamic method, to be able to invoke it more quickly compared to going through a delegate.

## Proposed API

This proposal is about adding a new API to `DynamicMethod` that would allow users to get a function pointer to it:

```csharp
namespace System.Reflection.Emit
{
    public sealed class DynamicMethod
    {
        public IntPtr GetFunctionPointer();
    }
}
```

**NOTE:** developers would have the responsibility of keeping the source `DynamicMethod` instance alive, eg. by storing it in a field or something similar, as long as the function pointer is in use. For instance, a simple way to do this would be for users to just define a small struct keeping the `DynamicMethod` instance and the function pointer, and then to use the function pointer to invoke the method to benefit from the faster `calli` performance, while having the other field to keep the method alive.

## Usage Examples

Re-purposing the example from above:

```csharp
DynamicMethod method = new DynamicMethod("Test", typeof(int), new[] { typeof(int) });
ILGenerator il = method.GetILGenerator();

// IL emit...

delegate*<int, int> func = (delegate*<int, int>)method.GetFunctionPointer();

// No delegate allocation needed. Use the function pointer
// freely, just with the caveat of keeping the method alive.
```

## Alternative Designs

There is an existing `RuntimeMethodHandle.GetFunctionPointer()` API, but the `MethodHandle` property for `DynamicMethod` always throws, so it's not usable. The commetn right above the exception in CoreCLR says the following:

> we cannot return a MethodHandle because we cannot track it via GC so this method is off limits

So an alternative (and probably easier to implement?) solution could be to just implement this method for `DynamicMethod` as well, with additional documentation making it explicit that consumers of this API would have to manually keep the method alive.

## Benchmarks

Run a quick benchmark earlier with the reflection hack on `DynamicMethod.GetMethodDescriptor` to get a function pointer to a `DynamicMethod` instance, and to compare performance between invoking a delegate for that dynamic method versus just invoking the function pointer obtained this way. The function pointer approach seems to be over 20% faster than the delegate:

|   Method |     Mean |    Error |   StdDev | Ratio |
|--------- |---------:|---------:|---------:|------:|
| Delegate | 21.40 us | 0.099 us | 0.092 us |  1.00 |
|    **Fnptr** | **16.57 us** | 0.048 us | 0.045 us |  **0.77** |

## Risks

Dynamic methods are already a niche API, even more so for function pointers on top of that, so the risk seems to be very limited considering one would expect developers working with these APIs to be quite familiar with these sort of details. The proposed API is also extremely narrow in scope, so introducing this will likely not impact existing developers.

**Comment by GrabYourPitchforks** [comment]
To your two main issues:

> You have to allocate a Delegate.

The cost of compiling the DynamicMethod absolutely dwarfs the cost of allocating the delegate instance. I don't see real savings here.

> Invoking a Delegate is relatively slow. Even more so for delegates wrapping a static method

Invoking a delegate is usually very fast. In the cases where there's a shuffle thunk (a delegate pointing to a static method), there's an indirection to a stub that performs parameter swapping, but we're talking only a few extra instructions. If you have examples of perf degradation beyond this shuffle thunk we should take a look at it.

Regardless, the shuffle think itself can be avoided by adding a sacrificial "object unused" parameter at the beginning of your `DynamicMethod`, then creating an "instance" delegate bound to nullptr as the first parameter. No shuffle thunk will be emitted, and invoking the delegate should result in _exactly identical_ codegen as using a calli to your dynamic method.

**Comment by Sergio0694** [comment]
Hey Levi, thank you for the quick reply and for all the extra info, I appreciate it 😊

> The cost of compiling the DynamicMethod absolutely dwarfs the cost of allocating the delegate instance.

100% agree on the negligible delegate allocation, that was really a super minor detail and I probably shouldn't have even mentioned that at all for better clarity. This issue was really just about the sustained speed of just invoking the delegate/fnptr.

> Invoking a delegate is usually very fast. In the cases where there's a shuffle thunk (a delegate pointing to a static method), there's an indirection to a stub that performs parameter swapping, but we're talking only a few extra instructions.

Right, I didn't remember exactly what it was about static methods being a bit slower to invoke, that makes perfect sense. That trick with the unused object to fake an instance method is really cool, I'll definitely make use of that going forward. I re-run my simple benchmark here to see the different of doing that and whether it reached feature parity with the function pointer version.

<details>
  <summary><b>Benchmark source (click to expand):</b></summary>
<br/>

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Benchmark>();

[DisassemblyDiagnoser]
public unsafe class Benchmark
{
    private Func<int, int> d;
    private Func<int, int> d2;
    private delegate*<int, int> f;

    [GlobalSetup]
    public void Setup()
    {
        // Standard delegate
        DynamicMethod method = new DynamicMethod("Test1", typeof(int), new[] { typeof(int) });
        ILGenerator il = method.GetILGenerator();

        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Add);
        il.Emit(OpCodes.Ret);

        this.d = method.CreateDelegate<Func<int, int>>();

        // Function pointer
        var handle = (RuntimeMethodHandle)typeof(DynamicMethod).GetMethod("GetMethodDescriptor", BindingFlags.Instance | BindingFlags.NonPublic).Invoke(method, null);

        this.f = (delegate*<int, int>)handle.GetFunctionPointer();

        // Instance delegate trick
        method = new DynamicMethod("Test2", typeof(int), new[] { typeof(object), typeof(int) });
        il = method.GetILGenerator();

        il.Emit(OpCodes.Ldarg_1);
        il.Emit(OpCodes.Ldc_I4_1);
        il.Emit(OpCodes.Add);
        il.Emit(OpCodes.Ret);

        this.d2 = method.CreateDelegate<Func<int, int>>(null);
    }

    [Benchmark(Baseline = true)]
    public int Delegate1()
    {
        var d = this.d;

        int result = 0;

        for (int i = 0; i < 10_000; i++)
        {
            result += d(i);
        }

        return result;
    }

    [Benchmark]
    public int Delegate2()
    {
        var d = this.d2;

        int result = 0;

        for (int i = 0; i < 10_000; i++)
        {
            result += d(i);
        }

        return result;
    }

    [Benchmark]
    public int Fnptr()
    {
        var f = this.f;

        int result = 0;

        for (int i = 0; i < 10_000; i++)
        {
            result += f(i);
        }

        return result;
    }
}
```
</details>

And I got the following results:

|   Method |     Mean |    Error |   StdDev | Ratio | Code Size |
|--------- |---------:|---------:|---------:|------:|----------:|
|   Static | 23.79 us | 0.073 us | 0.057 us |  1.00 |      49 B |
| Instance | 18.95 us | 0.083 us | 0.074 us |  0.80 |      49 B |
|    Fnptr | 16.57 us | 0.095 us | 0.088 us |  0.70 |      41 B |

The unused object already brought a 20% performance improvement, which is great, so I'll just switch to this approach in my project. Out of curiosity though and just to understand this better, why is the function pointer version still a bit faster still?

According to the disassembly diagnoser I'm getting this:

<details>
    <summary><b>Instance delegate asm (click to expand)</b>:</summary>

### .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
```assembly
; Benchmark.Delegate2()
       push      rdi
       push      rsi
       push      rbx
       sub       rsp,20
       mov       rsi,[rcx+10]
       xor       edi,edi
       xor       ebx,ebx
M00_L00:
       mov       rax,rsi
       mov       rcx,[rax+8]
       mov       edx,ebx
       call      qword ptr [rax+18]
       add       edi,eax
       inc       ebx
       cmp       ebx,2710
       jl        short M00_L00
       mov       eax,edi
       add       rsp,20
       pop       rbx
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 49
```
</details>

<details>
    <summary><b>Function pointer asm (click to expand)</b>:</summary>

## .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT
```assembly
; Benchmark.Fnptr()
       push      rdi
       push      rsi
       push      rbx
       sub       rsp,20
       mov       rsi,[rcx+18]
       xor       edi,edi
       xor       ebx,ebx
M00_L00:
       mov       ecx,ebx
       call      rsi
       add       edi,eax
       inc       ebx
       cmp       ebx,2710
       jl        short M00_L00
       mov       eax,edi
       add       rsp,20
       pop       rbx
       pop       rsi
       pop       rdi
       ret
; Total bytes of code 41
```
</details>

They seem pretty much identical except for the one with the delegate doing two additional `mov`-s, one of which with a memory read (I mean that `mov rcx,[rax+8]`) before the `call`, which I assume over those 10k iterations are what's causing that slight performance penalty over the function pointer version? I'd love to understand what is happening here and why the codegen is still slightly different in this case, just to learn more about how the runtime is handling things in this case.

Thanks again for your time!

**Comment by GrabYourPitchforks** [comment]
Just for fun, try calling an overload of the `DynamicMethod` ctor that allows you to specify _restrictedSkipVisibility = true_ as an argument. I suspect it'll benchmark a bit better, since due to an implementation detail of the runtime the method will be eagerly JITted _before_ the delegate is returned to you. Might end up resulting in the delegate pointing directly to the codegen rather than to the pre-JIT stub.

**Comment by omariom** [comment]
What will be preventing Dynamic Method from being GCed?

**Comment by Sergio0694** [comment]
Well what can I say except **WHAT?!** 😳

|         Method |     Mean |    Error |   StdDev | Ratio |
|--------------- |---------:|---------:|---------:|------:|
|         Static | 21.36 us | 0.129 us | 0.121 us |  1.00 |
|       Instance | 19.00 us | 0.120 us | 0.112 us |  0.89 |
|          Fnptr | 16.57 us | 0.075 us | 0.070 us |  0.78 |
| **SkipVisibility** | **11.88 us** | 0.057 us | 0.053 us |  **0.56** |

I'll take it! 😄
I had no idea this was a thing, this is just brilliant! Thanks Levi!

**Comment by gfoidl** [comment]
> this is just brilliant!

and also

> due to an implementation detail of the runtime

So it may change over time.

(Just to point it out).

**Comment by ionoy** [comment]
Maybe I'm missing something here, but without function pointer API, we always need to know the delegate type during the invocation, right? What if the delegate type is unknown and we can't construct it with `Func/Action` because of `ref/out` parameters? The ability to use `calli` would be very useful here.

**Comment by GrabYourPitchforks** [comment]
How do you intend on using calli if you don't know the method signature?

**Comment by ionoy** [comment]
I have parameter types but don't have a delegate type. There is `DelegateHelpers.MakeDelegateType`, but I would rather not use it if there is a way to get rid of the delegate altogether.
