### ISSUE TITLE
Use Math.DivRem instead of / % in BigInteger if dividend and divisor are trivial

### ISSUE THREAD

**Issue by KvanTTT** [dotnet/runtime#45230]
### Description

Currently, the following [code](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs#L746-L747) is used:

```cs
remainder = dividend._sign % divisor._sign;
return dividend._sign / divisor._sign;
```

I suggest using the system [`Math.DivRem`](https://docs.microsoft.com/en-us/dotnet/api/system.math.divrem?view=net-5.0). It's a bit faster because it uses only a single division, multiplication, and subtraction instead of two divisions:

```cs
int quotient = Math.DivRem(dividend._sign, divisor._sign, out int intRemainder);
remainder = intRemainder;
return quotient;
```

Moreover, in theory, it can use intrinsics.

**Comment by tannergooding** [comment]
Happy to take a PR for this, the fix is simple and straightforward.

If you wait for <https://github.com/dotnet/runtime/pull/45074>, there will also be new tuple based overloads which would simplify the logic a bit more.

**Comment by pgovind** [comment]
This would be a simple fix and wouldn't need a review. @KvanTTT , I'm happy to review the PR for this if you put one up?

**Comment by KvanTTT** [comment]
Yes, I'm going to suggest a PR. Also, I'm searching for other places of such optimization.

**Comment by SingleAccretion** [comment]
@KvanTTT I have an analyzer that can answer Roslyn queries about runtime's code (and several other repos, actually). If you're familiar with Roslyn, you could write a function with the following signature: `bool Matches(SyntaxNode node, SemanticNode node)` and I could run it for you.

**Comment by KvanTTT** [comment]
> If you wait for #45074, there will also be new tuple based overloads which would simplify the logic a bit more.

Yes, I think it makes sense to wait for that.

**Comment by tannergooding** [comment]
The new tuple based overloads are in so I've marked this `up-for-grabs`. Just comment and let us know if you want to pick this up.

**Comment by KvanTTT** [comment]
Yes, I want to pick this up.

**Comment by drieseng** [comment]
@KvanTTT This one can be closed, right?
