### ISSUE TITLE
SSL Handshake failed with OpenSSL (1.1.1) on Ubuntu 18.04 using HttpClient and net5.0

### ISSUE THREAD

**Issue by rmbolger** [dotnet/runtime#45244]
### Description

Fair warning, I'm not really a .NET developer and this issue only really affects me in the context of the latest PowerShell 7.1 release which is built against .NET 5.0. I submitted the issue there first (powershell/powershell#14253) and they told me to come here.

I'm having SSL handshake problems with HttpClient when connecting to our internal Infoblox API from an Ubuntu 18.04 server with OpenSSL 1.1.1. Infoblox is running the latest version of the appliance's OS, NIOS 8.5.1, but I suspect the TLS ciphers it is capable of using are considered old by today's standards which might be the root of the problem (details on this further down). Connecting to other internal websites that use more modern TLS settings has no problems.

Here's a sample app that can demonstrate the issue.

```csharp
using System;
using System.Net.Http;

namespace sslhandshake
{
    class Program
    {
        static void Main(string[] args)
        {
            var uri = args[0];

            Console.WriteLine("GET {0}", uri);
            using (var client = new HttpClient())
            {
                var response = client.GetAsync(uri).GetAwaiter().GetResult();
                Console.WriteLine("status code {0}", response.StatusCode);
            }
        }
    }
}
```

When the project file specifies TargetFramework `net5.0`, I get the following output when connecting to the unauthenticated documentation endpoint for the Infoblox grid master.

```none
GET https://gridmaster.test/wapidoc/
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at sslhandshake.Program.Main(String[] args) in /home/rmbolger/sslhandshake5.0/Program.cs:line 15
```

### Configuration

The underlying OS is a fully patched x64 Ubuntu 18.04.5 LTS server. The relevant installed packages include:

-  openssl 1.1.1-1ubuntu2.1~18.04.6
- dotnet-sdk-3.1 3.1.404-1
- dotnet-sdk-5.0 5.0.100-1
- powershell 7.1.0-1.ubuntu.18.04 (or 7.0.3-1.ubuntu.18.04 when testing the old version)

### Regression?

The same sample code works without error when TargetFramework is `netcoreapp3.1` which as far as I'm aware is what PowerShell 7.0 was built against. Here is the output.

```none
GET https://gridmaster.test/wapidoc/
status code OK
```

### Other information

Infoblox doesn't allow root access to the appliance's operating system or webserver to give exact versions on things there. But the managed CLI does allow some ability to tweak TLS protocol versions and ciphers. These are the current values. TLSv1.3 is not an option and I previously disabled TLSv1.0 and TLSv1.1. The ciphers in the list are all that is available.

```none
> show ssl_tls_protocols
TLSv1.2
> show ssl_tls_ciphers
  1. TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 enabled
  2. TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 enabled
  3. TLS_DHE_RSA_WITH_AES_128_CBC_SHA    enabled
  4. TLS_DHE_RSA_WITH_AES_256_CBC_SHA    enabled
  5. TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 enabled
  6. TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 enabled
  7. TLS_RSA_WITH_AES_128_GCM_SHA256     enabled
  8. TLS_RSA_WITH_AES_128_CBC_SHA        enabled
  9. TLS_RSA_WITH_AES_128_CBC_SHA256     enabled
 10. TLS_RSA_WITH_3DES_EDE_CBC_SHA       enabled
 11. TLS_RSA_WITH_AES_256_GCM_SHA384     enabled
 12. TLS_RSA_WITH_AES_256_CBC_SHA        enabled
 13. TLS_RSA_WITH_AES_256_CBC_SHA256     enabled
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA    disabled
     TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA    disabled
     TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA    disabled
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA    disabled
     TLS_RSA_WITH_RC4_128_SHA            disabled
     TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 disabled
     TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 disabled
     TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 disabled
     TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 disabled
```

**Comment by wfurt** [comment]
Look at chatter at #44191 @rmbolger. Some legacy ciphers are retired by default in .NET 5 but there is way how to enable them either via CipherSuitePolicy or by adjusting OS configuration.

**Comment by rmbolger** [comment]
Thanks, @wfurt. That thread lead me to the official breaking changes doc for what happened with TLS stuff between .NET 3.1 and 5.0.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux

For anyone who doesn't want to read through the other thread, the summary is this. .NET 5.0 will respect `CipherString` settings (among others) in the OS's `/etc/ssl/openssl.cnf` file. But if the settings aren't specified (which is the default in Ubuntu 18.04), .NET 5.0 defaults to a very restrictive/secure/modern default set of ciphers whereas .NET 3.1 defaults to a very loose/compatible set of ciphers. So if you are connecting to services that aren't capable of modern ciphers, you need to configure the OS's config to allow one or more of the ciphers your service *does* support. The other option is a code level change in your app that deals with `CipherSuitePolicy` and `SslStream` objects. But since my issue is with PowerShell, I don't have control of the code. So my only option is the OS config change.

In my particular case, I decided to use the [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org/) on the "Intermediate" configuration setting as a guide for what ciphers to allow while remaining compatible, but still as secure as possible. And I added the following to my `/etc/ssl/openssl.cnf` file right before the `[ new_oids ]` section.

```none
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
CipherString = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
```

The last two in the list match ciphers that are available from the Infoblox appliance. When re-testing both my .NET sample app and PowerShell's web cmdlets, neither throw an error anymore.

**Comment by wfurt** [comment]
thanks for good post @rmbolger. I'm glad you got it working.
