### ISSUE TITLE
Alternate sort cultureinfos compare strings as if they were created with the default sort lcid

### ISSUE THREAD

**Issue by igandrews** [dotnet/runtime#45252]
# General

It seems like while one can create a cultureinfo with a lcid representing an alternate sort, the resulting cultureinfo compares the same as the default sort. This works correctly in DNF and even in .net core 3.1 and earlier - it seems broken in .net 5.

`new CultureInfo(0x30404).CompareInfo.Compare("巴斯克語", "土耳其語", CompareOptions.IgnoreCase)`

If you execute the above with DNF or .Net Core 3.1, you will get -1. If you do the same with .net 5 you get 1. Actually lots of its state is the same as if you had created it with the default sort (0x0404 in this case) - the LCID is 0x404, the CompareInfo LCID and Version, etc.

**Comment by tarekgh** [comment]
@igandrews we encourage users to move away from using LCID's and stick with the culture names instead. Using LCID can cause many issues and the direction is to deprecate this functionality. Could you please tell more about your scenario and why you are using LCID's?

**Comment by igandrews** [comment]
Some cultures support alternate sort orders.  See [Alternate sort orders](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-5.0#AlternateSort) and [Sort order identifiers](https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/Intl/sort-order-identifiers.md) for more info if you're not familiar with this. I need to create a CultureInfo for the alternate sort order for specific cultures so I can do sorting of strings based on that alternate sort order. We were doing this and it was working prior to .net 5 and now we have a regression in our product because this isn't working. So how would I accomplish the same with .net 5?

**Comment by tarekgh** [comment]
@igandrews in .NET 5.0 we have switched to use ICU instead of Win32 NLS. But you can still achieve getting the alternate sort order by appending the collation name to the culture name. collation names like `phonebook, pinyin, traditional, stroke, direct, posix`. 

for example you can create `es-ES_traditional` for traditional sort that culture. `zh-CN_stroke` for Chinese stroke order and so on.

You still have the option to revert back to old behavior using NLS, please consult the doc https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu

**Comment by igandrews** [comment]
Thx. Using the LCID 0x30404 does actually indicate an appended collation suffix (_pronun in that case) so it seems like the LCID is recognized in that respect. Anyway I tried "zh-TW_pronun" and while that does create the culture (almost identical to when i use the lcid) it appears to have the same result - a sort order different than what I expected. I can confirm that if I force the app to use NLS it works as it did before but our products are libraries used by developers in their apps so forcing NLS isn't an option. I don't have enough info on my end to tell you where the bug is (in the ICU data or the .net runtime's usage of that info or somewhere else) but there does seem to be a bug here somewhere. I mean another example I can show where its incorrect is `new CultureInfo("de-DE_phoneb").CompareInfo.Compare("ä", "ad", CompareOptions.None)`. With NLS that returns 1 because ä is equivalent to "ae" and so it should be after the "ad" but with the ICU it returns -1 (which is what I would expect of the default sort culture but maybe that's a coincidence). I mean if you switch "ad" with "ae" it should return 0 (as it does with NLS) but returns -1 still.

**Comment by tarekgh** [comment]
@igandrews ICU collation is defined by Unicode so the behavior you are seeing is how it is defined by the standard. You may play with the CompareOptions adding like ignore symbols and ignore non space that may affect the result. But in general it is expected to have different sorting behavior between NLS and ICU. I want to mention is ICU is the future direction and I would suggest you start switching using that if there is no hard requirements to stick with NLS behavior. So, there is no bugs here more than just it is a change in the behavior.
