### ISSUE TITLE
Allow to change BaseIntermediateOutputPath 

### ISSUE THREAD

**Issue by transis2** [dotnet/runtime#45266]
## Background and Motivation

I'm comming from .Net 4.7 and one missing feature is the possibility to change BaseIntermediateOutputPath

I would like to change also OutputPath to write binary files in ram disk during debug.

It speed up build time, increase the durability of SSD and also avoid lots of "trash" in project sub folders.

```
    <OutputPath>R:\MyProject\bin\Debug\</OutputPath>
    <IntermediateOutputPath>R:\MyProject\Temp\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>R:\MyProject\Base\</BaseIntermediateOutputPath>
```

It would be nice if you make that work again with .net 5.

A perfect solution would be an checkbox option to compile temporary files in memory.

**Comment by huoyaoyuan** [comment]
Where are you setting it? I can always use it from .NET Core 3.1.

I set it in `Directory.Build.props`. Maybe there are difference from msbuild ordering.

**Comment by transis2** [comment]
I'm setting it in .csproj
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>R:\MyProject\bin\Debug\</OutputPath>
    <IntermediateOutputPath>R:\MyProject\Temp\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>R:\MyProject\Base\</BaseIntermediateOutputPath>
  </PropertyGroup>
```

**Comment by transis2** [comment]
@huoyaoyuan  It works! Thanks

This is the solution:

1. Create a new file in the root of your repo called Directory.Build.props.

2. Add the following XML to the file.
```
<Project>
 <PropertyGroup>
    <IntermediateOutputPath>R:\YourProject\Temp\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>R:\YourProject\Base\</BaseIntermediateOutputPath>
 </PropertyGroup>
</Project>
```

**Comment by huoyaoyuan** [comment]
When setting `BaseIntermediateOutputPath`, the SDK will set `IntermediateOutputPath` for you. Don't set it again.

**Comment by transis2** [comment]
> When setting `BaseIntermediateOutputPath`, the SDK will set `IntermediateOutputPath` for you. Don't set it again.

@huoyaoyuan Good to know
