### ISSUE TITLE
Blazor WASM / Browser WASM format as currency shows "AUD" instead of "$"

### ISSUE THREAD

**Issue by richardhauer** [dotnet/runtime#45262]
I have a net5 Blazor app and we are using Globalization to help with currency and date formatting.

Since upgrading to net 5 (from 3.1) numbers formatted with "C" are displaying "AUD" instead of "$" (I am in Australia obviously).
We set the thread culture during the bootstrapping of the app with:

````
CultureInfo.DefaultThreadCurrentCulture   = CultureInfo.CreateSpecificCulture( "en-au" );
CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.CreateSpecificCulture( "en-au" );
````
Here's a screen shot:  https://i.imgur.com/G2uhovG.png

I'm not really sure where to go from here; looks to be a bug with the formatters?
Interestingly this does not affect all locale's equally.
India and Philippines, for example, are displaying the correct symbols.

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by crackalak** [comment]
I have also come across this issue, we are using en-GB culture and getting 'GBP' in place of '£' when formatting.

**Comment by EgorBo** [comment]
I'm taking a look, https://github.com/dotnet/icu/blob/maint/maint-67/icu-filters/curr-root.txt is out of date 🙁

**Comment by crackalak** [comment]
After adding `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` to the project file, currency formatting works correctly for en-GB.

Perhaps https://docs.microsoft.com/en-gb/aspnet/core/migration/31-to-50?view=aspnetcore-5.0&tabs=visual-studio needs to be updated? As previously, this worked fine with 3.1

**Comment by richardhauer** [comment]
@crackalak  I do have that set, but still experiencing this odd issue.

**Comment by crackalak** [comment]
@richardhauer yes, I was able to replicate your issue with AUD

**Comment by kjpou1** [comment]
I am also able to replicate this outside of Blazor.

```
            CultureInfo us = new CultureInfo("en-US");
            CultureInfo au = new CultureInfo("en-AU");
            CultureInfo gb = new CultureInfo("en-GB");
            CultureInfo fr = new CultureInfo("fr-FR");

            Console.Out.WriteLine(us.NumberFormat.CurrencySymbol); // $
            Console.Out.WriteLine(gb.NumberFormat.CurrencySymbol); // £
            Console.Out.WriteLine(fr.NumberFormat.CurrencySymbol); // €
            Console.Out.WriteLine(au.NumberFormat.CurrencySymbol); // $

            CultureInfo.DefaultThreadCurrentCulture   = CultureInfo.CreateSpecificCulture( "en-AU" );
            Console.WriteLine($"currency 10 {10.ToString("C")}");


```

```
$
£
€
AUD
currency 10 AUD10.00
```

**Comment by richardhauer** [comment]
@kjpou1 That's interesting; in my unit tests (netcore5) it works as expected and only fails in the blazor app.

**Comment by richard-grant-codepro** [comment]
Same issue here with en-NZ. Getting 'NZD' instead of '$'

**Comment by fingers10** [comment]
Same issue here with en-IN. Getting 'INR' instead of '₹' in Blazor WebAssembly

**Comment by braidenstiller** [comment]
Any chance this will make it in 6.0 or is this scoped for 7.0?

**Comment by rkone** [comment]
This is still an issue in 6.0 final.  en-CA is returning CAD for the currency symbol. 👎

**Comment by danmoseley** [comment]
@lewing

**Comment by ilonatommy** [comment]
List of currencies from https://github.com/dotnet/icu/blob/dotnet/main/icu-filters/icudt_EFIGS.json that differs in behavior from net 7 Console App.
[consoleAppVsBlazorWasm.txt](https://github.com/dotnet/runtime/files/9064118/consoleAppVsBlazorWasm.txt)

**Comment by vpekarek** [comment]
Have the same problem with the Czech localization "cs-CZ". WASM render **CZK 1,250.50** instead of **1 250, 50Kč**

**Comment by ilonatommy** [comment]
For `cs-CZ`, `en-CA`, `en-IN` and other locales that are listed in the [file](https://github.com/ilonatommy/icu/blob/dotnet/main/icu-filters/curr-root.txt), adding:
 `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>` should fix it.
