### ISSUE TITLE
Service descriptors for IServiceScopeFactory.CreateScope

### ISSUE THREAD

**Issue by zahirtezcan-bugs** [dotnet/runtime#45278]
## Background and Motivation
This is about DependencyInjection library. We are trying to use the library for Desktop applications and we have a need for creating/providing services in a context. This is somewhat different than using scoped services. What we need is "singleton-within-specific-scope" lifetime or pseuodo-lifetime.

For example, consider the following service scope hierarchy
```
- Root
    - ScopeA (IFoo -> AlphaFoo)
        - ScopeB
        - ScopeC
    - ScopeX (IFoo -> ZetaFoo)
        - ScopeY
        - ScopeZ
```

In this imaginary world, we create a scope under root (ScopeA) and define that `IFoo` is implemented by `AlphaFoo`. So, within ScopeA and child scopes B and C we observe `IFoo` as implemented by `AlphaFoo`. We may create another scope under root (ScopeX) and define that `IFoo` is implemented by `ZetaFoo`. Then, within ScopeX and child scopes Y and Z we observe `IFoo` as implemented by `ZetaFoo`. Therefore, with scoped service descriptors we can define multiple domains (or hierarchical containers).

This is possible only if we can provide `ServiceDescriptor`s to `CreateScope` function. We can either provide descriptors manually or just give a `IServiceCollection`. Collection seems more natural because almost all of the cases use `IServiceCollection` for dependency registration.

## Proposed API

Scoped services are defined as optional for ease of use and backward compatibility.

```diff
namespace Microsoft.Extensions.DependencyInjection
{
    public static class ServiceProviderServiceExtensions
    {
-    public static Microsoft.Extensions.DependencyInjection.IServiceScope CreateScope (this IServiceProvider provider);
+    public static Microsoft.Extensions.DependencyInjection.IServiceScope CreateScope (this IServiceProvider provider, IServiceCollection scopedServices = null);
    }

    public interface IServiceScopeFactory
    {
-       Microsoft.Extensions.DependencyInjection.IServiceScope CreateScope();
+       Microsoft.Extensions.DependencyInjection.IServiceScope CreateScope(IServiceCollection scopedServices = null);
    }
}
```

## Usage Examples

``` C#
IServiceCollection domainRegistry = ...
domainRegistry.AddSingleton<IFoo, AlphaFoo>();
using (var scope = services.CreateScope(domainRegistry))
{
    var fooCalculator = scope.ServiceProvider.GetRequiredService<IFooCalculator>();
    //IFooCalculator uses IFoo, which is implemented by AlphaFoo in this scope
    fooCalculator.Calculate();
}
//-----------------------------------------------------------------
using (var scope = services.CreateScope())
{
    //It is an error if IFooCalculator uses IFoo as a dependent service in this scope
    var fooCalculator = scope.ServiceProvider.GetRequiredService<IFooCalculator>();
    ...
}
//-----------------------------------------------------------------
IServiceCollection domainRegistry = ...
domainRegistry.AddSingleton<IFoo, ZetaFoo>();
using (var scopex = services.CreateScope(domainRegistry))
{
    var fooInstance = scopex.ServiceProvider.GetRequiredService<IFoo>();

    using (var scopey = scopex.ServiceProvider.CreateScope())
    {
        var fooCalculator = scopey.ServiceProvider.GetRequiredService<IFooCalculator>();
        //IFooCalculator uses IFoo, which is the same instance as fooInstance in this scope
        fooCalculator.Calculate();
    }
}

```

## Alternative Designs
We can define name for a scope `CreateScope(name)` and register scoped service with a scope name `AddScoped(name, ...)` for filtering. Therefore, the named scope create an instance but other scopes only refer to their parent scopes for an instance at the time of resolution.

## Risks
Processing service descriptors may take some time and the user should opt-in with this knowledge.

**Comment by davidfowl** [comment]
This sounds like child containers. In general, we don't add features like this to the base container and recommend that you use another DI container implementation that supports these advanced features. It's specifically a non-goal to make the default container full featured as it is an abstraction that other containers implement.

**Comment by zahirtezcan-bugs** [comment]
I hafe almost no idea how you did implement the library. What I thought is the services are held in the root as key-information pairs. When needed, because of scopes, there should be a resolution mechanism to find requested service definition and then initialize at the correct level. In this design service definitions are resident at root level, but resolutions are resident at each scope. If this is correct, what I needed can be implemented via "pre-defined service resolution" at the scope without modification of the root, container or resolution mechanisms.

If I am mistaken about my imagination of the design, then feel free to ignore the request. Also, I appreciate that it is a good thing to keep the implementation light/fast and prevent the library to become a feature-bloat.

**Comment by maryamariyan** [comment]
Closing issue based on reasoning explained in https://github.com/dotnet/runtime/issues/45278#issuecomment-734839029
