### ISSUE TITLE
Socket.SendFile on *nix has serialization issue with pre/post-buffers

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#45274]
Cf. https://github.com/dotnet/runtime/pull/45132#issuecomment-733462372

@geoffkizer states

> we have an issue with the Unix impl of SendFile today, since there's no serialization here. If you do a concurrent Send, then that send could slip in between one of the parts of the SendFile and you won't get the expected results.

The [current implementation](https://github.com/dotnet/runtime/blob/0262b49a470bff6353fc91e87aec18b2c13c9e69/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Unix.cs#L198-L277) performs three independent sends

* send the preBuffer
* send the file
* send the postBuffer

that aren't protected from any concurrent send.

**Comment by antonfirsov** [comment]
I suppose #44422 is related. If we decide to wrap `Send` by a lock on Unix, we can extend the solution to cover `SendFile`.

**Comment by karelz** [comment]
Triage: It makes sense to merge it with the issue #44422 as they are closely related. @antonfirsov please update it.
I will close this one as duplicate

**Comment by karelz** [comment]
Duplicate of #44422
