### ISSUE TITLE
R2RDump GCInfo parsing crashes on CG2-compiled System.Private.CoreLib

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#45287]
Platform: Windows
Architecture: x64

Using "--disasm --gc" on SPC crashes when parsing GC info for <code>void System.Exception+DispatchState..ctor(byte[], object[], string, UIntPtr, byte[])</code> on this assert:

https://github.com/dotnet/runtime/blob/b79e4d3cd24f76dd1bcb722f589327c827e66632/src/coreclr/src/tools/aot/ILCompiler.Reflection.ReadyToRun/Amd64/GcInfo.cs#L197

/cc @dotnet/crossgen-contrib

**Comment by trylek** [comment]
In fact about 65 assemblies are failing with the GCInfo parsing bug so it's quite prevalent, about one quarter of the total number of assemblies being compiled (254):

<pre>
FSharp.Core.dll.naked.r2r.log
ILCompiler.Reflection.ReadyToRun.dll.naked.r2r.log
Microsoft.CSharp.dll.naked.r2r.log
Microsoft.Diagnostics.NETCore.Client.dll.naked.r2r.log
Microsoft.Diagnostics.Tracing.TraceEvent.dll.naked.r2r.log
Microsoft.Extensions.DependencyInjection.dll.naked.r2r.log
Microsoft.Extensions.DependencyModel.dll.naked.r2r.log
Microsoft.Extensions.FileSystemGlobbing.dll.naked.r2r.log
Microsoft.Extensions.Http.dll.naked.r2r.log
Microsoft.Extensions.Logging.Abstractions.dll.naked.r2r.log
Microsoft.Extensions.Logging.dll.naked.r2r.log
Microsoft.Extensions.Logging.EventSource.dll.naked.r2r.log
Microsoft.Extensions.Options.dll.naked.r2r.log
Microsoft.Extensions.Primitives.dll.naked.r2r.log
Newtonsoft.Json.dll.naked.r2r.log
System.CodeDom.dll.naked.r2r.log
System.Collections.Concurrent.dll.naked.r2r.log
System.Collections.dll.naked.r2r.log
System.Collections.Immutable.dll.naked.r2r.log
System.ComponentModel.Composition.dll.naked.r2r.log
System.Composition.Hosting.dll.naked.r2r.log
System.Configuration.ConfigurationManager.dll.naked.r2r.log
System.Data.Common.dll.naked.r2r.log
System.Diagnostics.DiagnosticSource.dll.naked.r2r.log
System.Diagnostics.EventLog.dll.naked.r2r.log
System.DirectoryServices.dll.naked.r2r.log
System.DirectoryServices.Protocols.dll.naked.r2r.log
System.Drawing.Primitives.dll.naked.r2r.log
System.Formats.Cbor.dll.naked.r2r.log
System.IO.FileSystem.dll.naked.r2r.log
System.IO.MemoryMappedFiles.dll.naked.r2r.log
System.IO.Pipelines.dll.naked.r2r.log
System.Linq.dll.naked.r2r.log
System.Linq.Expressions.dll.naked.r2r.log
System.Linq.Parallel.dll.naked.r2r.log
System.Memory.dll.naked.r2r.log
System.Net.Connections.dll.naked.r2r.log
System.Net.Http.dll.naked.r2r.log
System.Net.Http.WinHttpHandler.dll.naked.r2r.log
System.Net.HttpListener.dll.naked.r2r.log
System.Net.Mail.dll.naked.r2r.log
System.Net.Ping.dll.naked.r2r.log
System.Net.Primitives.dll.naked.r2r.log
System.Net.Requests.dll.naked.r2r.log
System.Net.Security.dll.naked.r2r.log
System.Net.WebHeaderCollection.dll.naked.r2r.log
System.Private.CoreLib.dll.naked.r2r.log
System.Private.DataContractSerialization.dll.naked.r2r.log
System.Private.Xml.dll.naked.r2r.log
System.Reflection.Metadata.dll.naked.r2r.log
System.Reflection.MetadataLoadContext.dll.naked.r2r.log
System.Runtime.Serialization.Formatters.dll.naked.r2r.log
System.Security.AccessControl.dll.naked.r2r.log
System.Security.Cryptography.Algorithms.dll.naked.r2r.log
System.Security.Cryptography.Cng.dll.naked.r2r.log
System.Security.Cryptography.Pkcs.dll.naked.r2r.log
System.Security.Cryptography.X509Certificates.dll.naked.r2r.log
System.Security.Permissions.dll.naked.r2r.log
System.ServiceModel.Syndication.dll.naked.r2r.log
System.Text.Json.dll.naked.r2r.log
System.Text.RegularExpressions.dll.naked.r2r.log
System.Threading.dll.naked.r2r.log
System.Threading.Tasks.Dataflow.dll.naked.r2r.log
System.Threading.Tasks.Parallel.dll.naked.r2r.log
System.Transactions.Local.dll.naked.r2r.log
</pre>

**Comment by trylek** [comment]
@cshung - How hard would it be to improve your R2RDump test to make it catch these bugs? I.o.w., running it over all framework assemblies and forcing evaluation of the GC info.

**Comment by trylek** [comment]
@AntonLapounov / @janvorli - I think you're the only ones who worked on finer details of the R2RDump GCinfo recently, would one of you have cycles to look into this? Otherwise let's discuss next Wednesday who will take this; investigating the marshalling bug was pain by itself and having the underlying tooling crashing left and right makes everything slower and more annoying.

**Comment by janvorli** [comment]
The assert was actually added by @AntonLapounov recent change #44682, so it sounds like it would be the best if he took the first look.

**Comment by AntonLapounov** [comment]
You may try commenting that `Assert` out.

**Comment by cshung** [comment]
I believe the right thing to do for this bug is simply to remove the assert. Below I summarize my findings to support the conclusion.

Here is the decoded GCInfo if we ignored the assert.

```
GC info:
    Version: 2
    CodeLength: 76
    ReturnKind: RT_Scalar
    ValidRangeStart: 0
    ValidRangeEnd: 0
    Wants Report Only Leaf: False
    Size of parameter area: 0x0
    NumSafePoints: 0
    NumInterruptibleRanges: 0
    SafePointOffsets:
    InterruptibleRanges:
    SlotTable:
        NumSlots(1) = NumRegisters(0) + NumStackSlots(0) + NumUntracked(1)
        GcSlots:
            GC_SLOT_UNTRACKED GC_SP_REL+0x48
    Size: 5 bytes
```

and here is the JITDump when the method was compiled:

```
*************** In gcInfoBlockHdrSave()
Set code length to 76.
Set ReturnKind to Scalar.
Set Outgoing stack arg area size to 0.
Stack slot id for offset 72 (0x48) (sp) (untracked) = 0.
Defining 0 call sites:
```

They seem to agree, meaning the decoder is doing the right thing.

Debugging the GCInfo generation, here are a few findings:

The method is not fully interruptible.
```
?? this->compiler->codeGen->m_cgInterruptible
false
```

Frame pointer is not used:
```
0:000> ?? this->compiler->codeGen->m_cgFramePointerUsed
class PhasedVar<bool>
   +0x000 m_value          : 0
   +0x001 m_initialized    : 1
   +0x002 m_writePhase     : 0
```

With these findings, the comment in R2RDump seems wrong. The code seems to imply if the method has a slot and does not have a safe point, then it is fully interruptible. But the debugging is telling us otherwise, that the method is not fully interruptible. It does have a slot, and I also confirmed that `numCallSites` in `clrjit!GcInfoEncoder::Build` is 0, meaning there is are no safe points.

https://github.com/dotnet/runtime/blob/76b52a55b6d6110744180c9915a5645f7a93c848/src/coreclr/src/gcinfo/gcinfoencoder.cpp#L1218

That leaves us with an interesting question though. If the method cannot be interrupted at all (it isn't fully interruptible, and there is no safe point), then what's the point of having a slot?

**Comment by AntonLapounov** [comment]
I agree with that analysis. Let's remove the assert and then we could do an experiment on not producing GC info for those methods.
