### ISSUE TITLE
HTTP2: Optimize huffman encoding static table initialization

### ISSUE THREAD

**Issue by rokonec** [dotnet/runtime#45297]
Currently [huffman encoding static table](https://github.com/dotnet/runtime/blob/7171407822a9a94b6ac12aca652851e74f3b604d/src/libraries/Common/src/System/Net/Http/aspnetcore/Http2/Hpack/Huffman.cs#L13) is compiled into ~5,5K IL bytes which is JITed into ~9.5K of ASM code.

[Sharplab prove](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgZgAIS6BhOgbyrs684AcpsAbgEMMMOrCEATCADtcATzoAKAK7YZGOpEkw0ddZuDYMAGRgyA5hgAWASgDaAXToB9c9vUWAKkOC4xALx0MjAA7spqGloQOnoGdEam5lZ2ThzcXOyUGTnKAAzApEXFRS5FeRWVLpU1edW1FXqkNLZo6blcSgUlJWU9paR55VUNjXTELW3ZHZ3d/aR9/YsldRWDNXrEAByt7TNdhfPLvfOrQ+tj27vTM/mHS/MLp9UXlZs7U7ecB4/HxX+DF5DDbjD57Do/I6/Z7nWrva5fO7QqH9VbFEFXT5fSEPFE9OqvN6ghHYua48nAwGjPKbFAk244noAp54156Gh5en7MlM5H4sprDFgm7c+681nogWE+FYhk8k4S/4rdbszmy0V88X8wbDS7CxGMhXklZ9Boy8G5Q1KxWA8ps4nqiHy63GyXooVcp1io1ak0rImYi05K0DG0LanmkVezU+3qVe2BqOW52h13/QUex3J70u32xokcz3ZmO5uOwgP60k51N59OEmkOoMZEMstOlSmZpvcFvM3vlitF4Mp1u19vuvWD5vD3vQ0aRg3TksDDMTrND6sj2NK4GdpPrpeb7e6huJhfADsjUb1BrXuF0JCT7sps436m3kGDR+zato19XiN0J+a5ThuUq1O+l5moBxBft8i7rBcEEVEhDbNLBdwdusKHYQBD7AU+3qQeBb4AZWcqgTuNQ4XOgGkOhIYEv+TFQUBXbfs8x7ISRNGsXuIH4kM1F/lBZEakc/Zccxd5FPR8rAkJxE0aJXqUoh3HCXeeFsXB546sMClUbhsm6YSBlESCWl8QR6mKRpIIAKzGTUalSYZNGOfh37xm5dnmUSHnaRhwxYTZPmaU5dp+ZJvljJZZ6wvpoVRQ2cVVucrxmdF4WeTp6U7plL7ZYFBzpS5MWFRZEX+gVKF6Kl5F6WVtnNSCADsxn4u2rnJXoynFhKyW1YBAVWex3VZWFlU5UiUISQVTQwdNPZJRNRK8WeyKURVPWAZMxXdM5q1HdtsUdXlVLjSdDbtUtB3VStV16Dd+2FKVF3lUNz2jTpnFXfNdBfRtrzvS1O2A1WuohZdn0dRc5Q1QB4MNQhg0PU9sOCiDk1gxj5YIzRSNiWs8MPTDt2HFt+NQYT0Y6oKVN3jT/UXgzbUY3pf1owD7NNdjx3o+Tdp06zRJM/ujXHf9Yv8Y1WOowTsOmaTiOK95ItjNLBHulDH0q4LAnqw2fXiwhcuS3rL2ouG0OkYr4r9v9aH622nM8QAnHbRqg/zu2e7mfOPYBdKC955uXXVfs1sLXOkCN8XE/L5V6HHEPxjr3uB/VoormHSd0CnDU54bEfk5jicZ8nZ0s8rNFZ9GCe5xX95V+6xfN6Xc011BBdiXTjcBwLluRWbrvU2dSs27X48Zm3dfFheo9N3P67E7z5cOdPiWT1By8yxzi8D9zIfHrPEW6+H+dn5Rbc9/XkUHztu9a0LI9S3bAdv87KNt5r7HounH8LbfRmkLB+Ptf4/UVP3Nat9+oPG3tJOiX8fT5RjsHIeFI14+ydhg0ch5QxQVPBDG0aIJ6ELVLgrcY4VxDWIItShpYSbjkDsQChwCewcQvqwyO+Dwymx9nQnhfY+4CPoew+CSxMKiKEbOYKLC9riNAr8VSO1BHIMYcue+tCFFAzbE8BKI9Ng6OIXoqUuptEyNmv/eRlj4H3RohMWxWpVK0PQYog8ZjJQAUceoqOLo8beLcbovBiwEquKcXGCWLCxHBKoSyPOPiGF+NTHlcJvjeGmjVt44xyNTGQwETk3uITIaGPGIU2meSUYFIifDZhLCkFJIyRJaJNSCEdgsek4RVTaExJMcU/hNjOmbVSdk1prZSppMaV06+3jem5NHASe+9TWmMUpt4thsSNF8P3j0sZLwT6zL2UswZUzNrf1GUM1EyxD5kCOXTABAZylwJCedaRlzJH+hae830Nygl9KoYs8ctCGnuLDPs1uhzvkKhUR005KIHYXLhZIrhILNnJOtjQ7xqL/lbIFAkuZRS4nXgyliu5CUTmgryYdL5SL7YQocU8k2/TSoUrRfgxiZC7zcKhduTFDiCUVOKWnN5tKThF0haK/xNzGV7yFdXflRyG40spf0uGrKcXouOKop+f9KlAq2pcHVkCXZmJuRsjV7L6ico/B7Hly48rKrZTOOR6r5lEpESKlV7r/6lOILApl3qgX1hPEakBqrzG/U2KGjhA1BLeOjRIvM5xMkYggWGwNQtQmprudrIEXKE1KNZPGSZXrcXKltA4/1sqAV5sPqQW1kquoIocdit1Zb/T6MIQWjxqIWFppjWmSS0pxj9sTfmQSkbxjdrBb22tAZR2FuNPTQJeyc7LLtdbERwKc2RVodOvVu6DUhp3dChMxtq3tvupxTYC6e0G2DTek9WEPUnlvSQlNqjzVts1R2jFXK/nfstcc2hX7CW4qVeuxt+jukStLZq1eqjW1gfg/WbdG6s0kwZYqrdsGnWyICQq9D5a/0Yirc/A96U8VcrI7q8NqCHEAeQxk5UcaGMnvkg+qdOaZlYaIyxj9hqn3IUncQN9B69J7vY9Q/NQnAVcrE+Gu0tCFMZqU2ux9fHlRzsuCpy9/99nyafSk3ceGoGdsM5p/TL6NNQb+BO+sNm4PMc6lm+dRm+1SfMxifdinGFjELE2AAvgAbm4HsPYtAGAoDoAAWSULYNgexAtUEC0AA=)

It might be beneficial to somehow optimize above.

**Comment by rokonec** [comment]
My idea is to create ReadonlySpan<byte> containing source data from which the encoding table will be initialized.
```C#
private static ReadOnlySpan<byte> s_encodingTableData => new byte[257*5]
{
            0b11111111, 0b11000000, 0b00000000, 0b00000000, 13,
            0b11111111, 0b11111111, 0b10110000, 0b00000000, 23,
            ....
}

private static readonly (uint code, int bitLength)[] s_encodingTable = GenerateEncodingTable();

private static (uint code, int bitLength)[] GenerateEncodingTable()
{
    // TODO: build if from s_encodingTableData bytes by converting 4 bytes into 'uint code' and 5th into 'int bitLength'
}

**Comment by scalablecory** [comment]
@rokonec would you like to take this one?

**Comment by scalablecory** [comment]
The strategy outlined looks good to me.

**Comment by stephentoub** [comment]
I'd suggest just starting with a 'uint[[' and a 'ReadOnlySpan<byte>', and then upgrading the former to a 'ReadOnlySpan<uint>' once  https://github.com/dotnet/runtime/issues/24961 is implemented, hopefully later this release.
cc: @VSadov, @jaredpar

**Comment by rokonec** [comment]
@scalablecory I'd like to take this one If I could. Please assign me to it if you feel its OK.

**Comment by rokonec** [comment]
@stephentoub I was thinking about something like this: https://sharplab.io/#gist:c13c371e129cb662d20d6c2d3ab0f312
No usafe needed. Is this fragile against endianness?

**Comment by stephentoub** [comment]
You can do that, but you're now incurring lots of additional bounds checks and division and the like.
```C#
[Benchmark]
public (uint code, int bitLength)[] Create1()
{
    var data = s_encodingTableData;
    var table = new (uint code, int bitLength)[data.Length / 5];

    for (int i = 0; i < s_encodingTableData.Length;)
    {
        table[i / 5] = ((uint)((data[i++] << 24) | (data[i++] << 16) | (data[i++] << 8) | data[i++]), data[i++]);
    }

    return table;
}

[Benchmark]
public (uint code, int bitLength)[] Create2()
{
    var uintData = s_encodingTableUintData;
    var byteData = EncodingTableByteData;
    var table = new (uint code, int bitLength)[uintData.Length];

    for (int i = 0; i < uintData.Length; i++)
    {
        table[i] = (uintData[i], byteData[i]);
    }

    return table;
}
```

|  Method |     Mean |   Error |  StdDev |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|-------- |---------:|--------:|--------:|-------:|-------:|------:|----------:|
| Create1 | 258.2 ns | 1.21 ns | 1.01 ns | 0.1054 |      - |     - |     664 B |
| Create2 | 103.6 ns | 1.00 ns | 0.83 ns | 0.1057 | 0.0002 |     - |     664 B |

That said, in retrospect this probably doesn't matter, since this code is ever going to be invoked only once.  And with the uint[] approach, there will also be the initial cost to allocate and blit the contents of the array, but that would go away with #24961 .  

That's all to say, what you proposed seems fine for now, but I do think we should change it when #24961 arrives.

**Comment by rokonec** [comment]
As for now, encoding table is only needed to generate decoding table - only once and in unit tests. 

Maybe we can consider to skip that table building and just use those two arrays (uint[] and ReadOnlySpan<byte>) directly from generate decoding table. If we decide to support huffman encoding in our HTTP2 clients later, we can optimize for it at that time.

**Comment by rokonec** [comment]
I'll create PR with latest @stephentoub recommendation:
```
uint code = s_encodingTableCodes[octet];
int bitLength = EncodingTableBitLengths[octet];
```
We can iterate on it in the PR as those are really elementary changes.

**Comment by stephentoub** [comment]
Great.  Thanks.

**Comment by rokonec** [comment]
PR https://github.com/dotnet/runtime/pull/45303

**Comment by geoffkizer** [comment]
Linked PR was merged, closing.

Please reopen/refile if there is something else to look at here.
