### ISSUE TITLE
RyuJIT: Partial Inline of CORINFO_HELP_ISINSTANCEOFCLASS

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#45295]
```csharp
List<int> AsList(IEnumerable<int> e) => e as List<int>;
```
Codegen for `AsList`:
```asm
G_M25716_IG01:
       sub      rsp, 40

G_M25716_IG02:
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_ISINSTANCEOFCLASS
       nop      

G_M25716_IG03:
       add      rsp, 40
       ret    
```
I wonder if it makes sense to inline these two checks (at least in very hot blocks) https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs#L258-L259 (as far as I understand it's already done for `CORINFO_HELP_CHKCASTCLASS_SPECIAL`)

If I interpret the results correctly in most cases those two checks are enough so we can avoid "call" overhead.
![image](https://user-images.githubusercontent.com/523221/100516458-0c3acb80-3195-11eb-8117-6513ef8f9210.png)

/cc @jkotas @VSadov

**Comment by jkotas** [comment]
You would need to collect data to see the distribution between the fast path and slow path in a typical app (e.g. you can use ASP.NET template as proxy) to tell whether this is worthwhile optimization.

IIRC, this was looked at in .NET Framework days. The data at that time suggested that the slow path is taken a lot more frequently for `isinst` compared to `chkcast`.

**Comment by EgorBo** [comment]
@jkotas the screenshot above is a snapshot for `crossgen2` compiling SPC.dll

But I also collected metrics for a simple `ASP.NET Core Web API` self-contained app. I decided to just add fields to `CastHelper.IsInstanceOfClass` like this:
```csharp
        private static long s_isNull;
        private static long s_sameType;
        private static long s_other;

        [DebuggerHidden]
        [StackTraceHidden]
        [DebuggerStepThrough]
        private static object? IsInstanceOfClass(void* toTypeHnd, object? obj)
        {
            if (obj == null)
            {
                Interlocked.Increment(ref s_isNull);
                return null;
            }

            if (RuntimeHelpers.GetMethodTable(obj) == toTypeHnd)
            {
                Interlocked.Increment(ref s_sameType);
                return obj;
            }
            Interlocked.Increment(ref s_other);
            ....
```
And then query them via reflection from my app's web api Controller, here are the numbers:
```
isNull=258, sameType=13003, other=1001
```
but looks like `other` is growing a bit faster when I randomly send requests to my app.

**Comment by EgorBo** [comment]
Numbers for a quite heavy Avalonia UI app:
```
isNull=43935 sameType=239801 sameParentType=340210 other=340210 
```

**Comment by EgorBo** [comment]
Ok, going to close it.

Perhaps, it also makes sense to profile `IsInstanceOfInterface` and re-order interfaces on built-in types. e.g. make `IEnumerable<char>` the first in the order for `String` etc.

**Comment by VSadov** [comment]
> re-order interfaces on built-in types. e.g. make IEnumerable<char> the first in the order for String etc.

This was suggested before, but the conclusion was that it is not worth it. One example here: https://github.com/dotnet/runtime/issues/33260

In my observation the order of compares for the first few interfaces makes some difference but not a lot. My theory is that these entries typically end up on the same cache line and compares are relatively cheap next to reading that memory. There is also a possibility that a speculative cpu may do more than one compare at once, but I am less sure about that. 

On the other hand reordering of interface lists is a bit of a churn. 
It also may be observable in some subtle cases (i.e. reflection, overload resolution). These are extreme corner cases, but there is still some risk which must be justified by the benefits.
