### ISSUE TITLE
Add LoggerMessage.Define overload to disable IsEnabled check

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#45290]
## Background and Motivation

`LoggerMessage.Define` allows skipping various overheads in logging (parsing the template etc) and returns delegate that performs logging and includes a check if that logging category is enabled before performing the call to log. In some cases it's important that check be moved higher up the stack to avoid transformation of parameters before calling log, for e.g.

```C#
public class Connection
{
    private string _connectionId;
    public string ConnectionId => _connectionId ??= GenerateConnectionId();
}

public static class Log
{
    private static readonly Action<ILogger, string, Exception> _connectionStart =
        LoggerMessage.Define<string>(
            LogLevel.Debug,
            new EventId(1, "ConnectionStarted"),
            "Connection {ConnectionId} started");

    public static void ConnectionStarted(ILogger logger, Connection connection)
    {
          _connectionStart(logger, connection.ConnectionId, null);
    }
}
```

The above logic ends up eagerly allocating the `ConnectionId` even when the log level isn't enabled. The code could be changed to this:

```diff
public static void ConnectionStarted(ILogger logger, Connection connection)
{
+    if (logger.IsEnabled(LogLevel.Debug))
+    {
        _connectionStart(logger, connection.ConnectionId, null);
+    }
}
```

It would end up checking if the category is enabled multiple times when the category is on.

## Proposed API

```diff
namespace Microsoft.Extensions.Logging
{
    public static class LoggerMessage
    {
+        public static Action<ILogger, T1...T6, Exception> Define<T1...T6>(LogLevel logLevel, EventId eventId, string formatString, bool skipEnabledCheck);
    }
```

The ... are overloads T1 to T6 (or more).

## Usage Examples

```C#
public class Connection
{
    private string _connectionId;
    public string ConnectionId => _connectionId ??= GenerateConnectionId();
}

public static class Log
{
    private static readonly Action<ILogger, string, Exception> _connectionStart =
        LoggerMessage.Define<string>(
            LogLevel.Debug,
            new EventId(1, "ConnectionStarted"),
            "Connection {ConnectionId} started",
            skipEnabledCheck: true);

    public static void ConnectionStarted(ILogger logger, Connection connection)
    {
        if (logger.IsEnabled(LogLevel.Debug))
        {
            _connectionStart(logger, connection.ConnectionId, null);
        }
    }
}
```

## Risks

None.

**Comment by bartonjs** [comment]
Looks good as proposed.

```C#
namespace Microsoft.Extensions.Logging
{
    public static class LoggerMessage
    {
+        public static Action<ILogger, T1...T6, Exception> Define<T1...T6>(LogLevel logLevel, EventId eventId, string formatString, bool skipEnabledCheck);
    }
}
```

**Comment by gfoidl** [comment]
@bartonjs did you copy the wrong overloads? These are already here: https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerMessage.cs#L151 (except the nullability on Exception) and miss the proposed argument `skipEnabledCheck`.

What about the overload that doesn't take any `T1...T6`? https://github.com/dotnet/runtime/blob/5078dd61a81c88dbdd131a77b8148b4dee3803fa/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerMessage.cs#L130

**Comment by KalleOlaviNiemitalo** [comment]
> PS: I have a [PR ready](https://github.com/dotnet/runtime/compare/master...gfoidl:loggermessage-skipEnabledCheck?expand=1), just need to submit it when the new overloads are confirmed.

Renaming "master" to "main" in <https://github.com/dotnet/runtime/issues/48357> broke the link. <https://github.com/dotnet/runtime/compare/main...gfoidl:loggermessage-skipEnabledCheck?expand=1> works instead.

You added `skipEnabledCheck` checks inside each lambda expression. This could cause a minor slowdown in every logging call but I don't know whether it will be measurable. If a benchmark shows that it is indeed slower, then an alternative would be to do the check outside the lambda expression:

```C#
            if (skipEnabledCheck)
            {
                return (logger, exception) => { /* just call logger.Log and not logger.IsEnabled */ };
            }
            else
            {
                return (logger, exception) => { /* call logger.IsEnabled and logger.Log */ };
            }
```

That would be more work for the JIT compiler, though.

**Comment by davidfowl** [comment]
I would prefer if it returned a different lambda without the check. @KalleOlaviNiemitalo are you going to submite a PR?

**Comment by KalleOlaviNiemitalo** [comment]
No, I do not intend to make a PR.

**Comment by gfoidl** [comment]
But I can take the suggestion from @KalleOlaviNiemitalo and incorporate them into my changes.

**Comment by gfoidl** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/31332 so that these new API can be used for ASP.NET Core too.
