### ISSUE TITLE
Roll forward LatestMajor needs a max version setting

### ISSUE THREAD

**Issue by rseanhall** [dotnet/runtime#45306]
WiX has an application, [Heat](https://github.com/wixtoolset/Harvesters), that dynamically loads `Microsoft.Build.dll` and `Microsoft.Build.Framework.dll`. I recently had to update the roll forward policy to `LatestMajor` (https://github.com/wixtoolset/Tools/pull/56) so it could continue to support running on 2.1 while also be able to load MSBuild 16.8 assemblies, which were compiled for `net5.0`.

With the existence of both the `Major` and `LatestMajor` policies, it seems that at some point in the future an app could be broken if it rolls forward too far. Let's say this happens to my app in .NET 6. I want the ability to compile it once for [2.1, 6.0) and then again for [6.0, infinity). As far as I know, the only way to get the latest runtime in [2.1, 6.0) is to write a custom host which is not something I want to do for this. I want something like a `MaxRollForwardVersion` setting so I can specify that it shouldn't be rolled forward to 6.0 but can be rolled forward to any version of 5.x.

**Comment by vitek-karas** [comment]
Basically this exact request is already part of this epic: https://github.com/dotnet/runtime/issues/43332

Specifically this part:
> Support version ranges when specifying framework references and SDK versions

My current thinking is to support basically the same syntax which NuGet supports for versions - but in the `.runtimeconfig.json`
The roll forward policy would still apply - it would determine which exact version to pick from that range.
It's not that different from the current behavior, the only difference is that currently the upper bound is determined by look at the available versions on the machine. With the version range the upper bound would the minimum of the one specified in the config and what's available on the machine.

**Comment by vitek-karas** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/43332.
