### ISSUE TITLE
JIT should optimize away the cast that occurs after Array.Clone

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#45302]
The typical way to clone an array is to use `Array.Clone`, which returns an _object_ that needs to be cast back to the original array type.

```cs
string[] originalArray = GetArray();
string[] clonedArray = (string[])originalArray.Clone();
```

After the call to `Clone`, the JIT emits a call to the `ChkCastAny` helper to ensure that the cast is legitimate.

```cs
public static object[] M(object[] o) {
    return (Object[])o.Clone();
}
```
```asm
M(System.Object[])
    L0000: sub rsp, 0x28
    L0004: mov eax, [rcx]
    L0006: call 0x00007ffb1bc0e0c0  ;  Array.Clone()
    L000b: mov rdx, rax
    L000e: mov rcx, 0x7ffabc1af762  ;  type handle for object[]
    L0018: call 0x00007ffb1bc16750  ;  ChkCastAny
    L001d: nop
    L001e: add rsp, 0x28
    L0022: ret
```

There is an opportunity for improvement here. If the target of the `Array.Clone` call is known by the JIT to be a local of type _T_, and if the return value of `Clone` is immediately cast to _T_ or type _U_ (where _reinterpret\_cast\<U\>(T)_ is legal), then the JIT should no-op the cast. In the sample above, that means labels _L000b_ - _L001d_ would disappear.

Some examples:

```cs
string[] stringArray;
string[] clone1 = (string[])stringArray.Clone(); // JIT should elide check
object[] clone2 = (object[])stringArray.Clone(); // JIT should elide check

object[] objectArray;
string[] clone3 = (string[])objectArray.Clone(); // check should take place, could succeed or fail at runtime
object[] clone4 = (object[])objectArray.Clone(); // JIT should elide check

int[] intArray;
int[] clone5 = (int[])intArray.Clone(); // JIT should elide check
uint[] clone6 = (uint[])intArray.Clone(); // JIT should elide check
object[] clone7 = (object[])intArray.Clone(); // check should take place and will fail at runtime
```

**Comment by sharwell** [comment]
Can we not use covariant return types here, to make the return type of `string[].Clone` be `string[]` instead of just `object`?

**Comment by benaadams** [comment]
> Can we not use covariant return types here,

`Array` is a bit of a funny type and doesn't have any generic instance methods to change the return type on?

**Comment by EgorBo** [comment]
I think it should be easy to fix in JIT, given a tree:
```
\--*  CALL help ref    HELPER.CORINFO_HELP_CHKCASTARRAY
   +--*  CNS_INT(h) long   0xd1ffab1e class
   \--*  CALL      ref    System.Object.MemberwiseClone  ;;; should be marked as [Intrinsic]
      \--*  LCL_VAR   ref    V00 arg0
```
drop the helper if arg0's type and that CNS_INT handle return `TypeCompareState::Must` via `info.compCompHnd->compareTypesForCast` (if it doesn't give up on arrays)

**Comment by EgorBo** [comment]
Possible fix: https://github.com/EgorBo/runtime-1/commit/aa3dcd54b684acfc9274b5e6beccea629ab3fd91

**Comment by GrabYourPitchforks** [comment]
Why would the intrinsic annotation be on _MemberwiseClone_? I realize _Array.Copy_ is just a dumb wrapper around it, so I guess inlining has already taken place at this point?
