### ISSUE TITLE
NumberFormatInfo differs between operating systems

### ISSUE THREAD

**Issue by mgnsm** [dotnet/runtime#45308]
Why does `new CultureInfo("en-US", false).NumberFormat` returns `2` on Windows but `3` on Linux (tested on Ubuntu 18.04)?

This is not mentioned in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.numberdecimalseparator) which says that `123456789.ToString("N", new CultureInfo( "en-US", false ).NumberFormat)` produces 123,456,789.00. 

On Linux it produces 123,456,789.00**0** which is not expected.

**dotnet --version**
3.1.404

**Comment by EgorBo** [comment]
Duplicates https://github.com/dotnet/runtime/issues/44587

**Comment by danmosemsft** [comment]
@mgnsm please try 5.0 - you should see Windows now has Linux result.

**Comment by tarekgh** [comment]
@mgnsm .NET uses the underlying OS for globalization support. in .NET Core up to and including version 3.1 when running on Windows, we use Win32 NLS APIs for that. On Linux we use ICU library for that. So it is expected to see some differences when running on different OS's. In .NET 5.0 we have started to use ICU on Windows too and that should show more consistency when running on different OS. 

The doc is just showing example how to call it and not trying to say this is the behavior you should expect all the time. Note that the globalization data can change at any time and it will be better not assuming this will not happen. If you want to guarantee the behavior either use the Invariant culture or use fixed format (e.g. `N2` for instance). 

I am closing this issue but feel free to send any question you have and we'll be happy to help with. Thanks!
