### ISSUE TITLE
System.Runtime.InteropServices.IEnumSTATDATA has a wrong IID

### ISSUE THREAD

**Issue by smourier** [dotnet/runtime#45316]
IEnumSTATDATA is currently defined in runtime/src/libraries/System.Runtime.InteropServices/src/System/Runtime/InteropServices/ComTypes/IEnumSTATDATA.cs as 

**00000103-0000-0000-C000-000000000046**

	namespace System.Runtime.InteropServices.ComTypes
	{
		/// <summary>
		/// The IEnumSTATDATA interface is used to enumerate through an array of
		/// STATDATA structures, which contain advisory connection information for
		/// a data object. IEnumSTATDATA has the same methods as all enumerator
		/// interfaces: Next, Skip, Reset, and Clone.
		/// </summary>
		[ComImport]
		[Guid("00000103-0000-0000-C000-000000000046")]
		[InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
		public interface IEnumSTATDATA
		{
			...
		}
	}

While Windows SDK's ObjIdl.h defines is as

**00000105-0000-0000-C000-000000000046**
	
    MIDL_INTERFACE("00000105-0000-0000-C000-000000000046")
    IEnumSTATDATA : public IUnknown
    {
    	...
    }

For information, 00000103-0000-0000-C000-000000000046 is IID_IEnumFORMATETC, not IID_IEnumSTATDATA.

I think this bug is here for a long time.

**Comment by elinor-fung** [comment]
Wow. Yeah, I think this has been wrong for a long time. Good catch.
