### ISSUE TITLE
HTTP/3 and HttpVersionPolicy.RequestVersionOrHigher

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#45319]
I was able to successfully make a HTTP/3 call using HttpClient by following the instructions at https://github.com/dotnet/runtimelab/tree/feature/System.Net.Experimental.MsQuic

However when I changed the request to use RequestVersionOrHigher + HTTP/2, the protocol used was HTTP/2.

```cs
new HttpRequestMessage
{
    Version = new Version(2, 0),
    VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
}
```

**Comment by scalablecory** [comment]
To perform an upgrade, the remote server needs to give an `Alt-Svc: h3-29=":443"` header (if HTTP/3 is listening at port 443). HTTP/3 will then be used for the next request.

It's possible this was broken though; I remember we added version policies without testing the changes to Alt-Svc code.

**Comment by JamesNK** [comment]
I'm running the example in runtimelab. I just modified the client to make two calls (it sounds like the first will be made with HTTP/2)

```cs
class Program
{
    static async Task Main(string[] args)
    {
        AppContext.SetSwitch("System.Net.SocketsHttpHandler.Http3DraftSupport", isEnabled: true);

        using HttpClient client = new HttpClient();
        await SendRequest(client).ConfigureAwait(false);
        await SendRequest(client).ConfigureAwait(false);
    }

    private static async Task SendRequest(HttpClient client)
    {
        using HttpRequestMessage message = new HttpRequestMessage
        {
            Method = HttpMethod.Get,
            RequestUri = new Uri("https://localhost:5557/"),
            Version = new Version(2, 0),
            VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
        };
        using HttpResponseMessage response = await client.SendAsync(message).ConfigureAwait(false);

        Console.WriteLine($"Response received using HTTP/{response.Version.Major}.{response.Version.Minor}");
    }
}
```

The issue could be with Kestrel not correctly returning the header.

What have you been using to debug HTTP/3? I use Wireshark with HTTP/2, but I've always used h2c. Is it right that unencrypted HTTP/3 is not an option?

**Comment by scalablecory** [comment]
>The issue could be with Kestrel not correctly returning the header. What have you been using to debug HTTP/3?

You should see the Alt-Svc header come across on the first `HttpResponseMessage` in this case. Debugging has all been via debugger.

> Is it right that unencrypted HTTP/3 is not an option?

Correct, there's no h3c this time around :(.

**Comment by ManickaP** [comment]
Do we have some guidelines how to decrypt TLS encrypted captures when using `HttpClient`? 
We have this issue: https://github.com/dotnet/runtime/issues/37915, but that's all I know of...

**Comment by wfurt** [comment]
Using h2c (or similar) is probably your best option. SslStream can dump buffers via tracing but that is not really convenient for binary protocols. Alternatively if you can manipulate (or overcome) trust, you can play man-in-the-middle and do packet captures on decrypted traffic.

**Comment by JamesNK** [comment]
> To perform an upgrade, the remote server needs to give an `Alt-Svc: h3-29=":443"` header (if HTTP/3 is listening at port 443). HTTP/3 will then be used for the next request.
> 
> It's possible this was broken though; I remember we added version policies without testing the changes to Alt-Svc code.

I think the problem is Kestrel is sending back `h3-25` instead of `h3-29`.

**Comment by karelz** [comment]
Triage: Looks like problem in Kestrel. Closing. Should be addressed once Kestrel is on newer version of h3 in AltSvc
The concern if the scenario works at all will be addressed (aka tested) as part of HTTP/3 effort in .NET 6.
