### ISSUE TITLE
IdnMapping fails on certain domains

### ISSUE THREAD

**Issue by Genbox** [dotnet/runtime#45323]
### Description

IdnMapping fails on the following domains:
```
xn--z9e.com
xn------nzeacbub3cugodj0yjat88.blog.ir
xn--bia2yab-7z6c.blog.ir
xn--blackmoda-f674c.ir
xn--ropirt0df0g-ob9gz268v.ml
xn--mstockstter4-q8a.tk
xn------------4kaeaaaaaaaaaa.tk
xn--pqk.to
xn--9ba.xn--node
xn--vs-k13aa37fya6d3ca4a6l8g8e0a7he3643k5fhz9owi6ghxecs9g9wvf.xn--node
```

They are in PunyCode format. Each works just fine in Edge 87.0.664.47

Example code that throws an exception:
```csharp
new IdnMapping().GetUnicode("xn--z9e.com");
```

They are expected to work since it works in browsers just fine.

### Configuration

* Running on .NET 5.0.100
* Windows 10 Enterprise 10.0.19042

**Comment by tarekgh** [comment]
Looking at 
```C#
new IdnMapping().GetUnicode("xn--z9e.com");
```

I am seeing the failure is valid according to the Unicode specs https://unicode.org/reports/tr46/#Validity_Criteria. The puny code `z9e` would be mapped to the Unicode character 

```
1886 $ ᢆ MONGOLIAN LETTER ALI GALI THREE BALUDA
``` 

which is a combined mark. and the spec validation says the following:

```
5. The label must not begin with a combining mark, that is: General_Category=Mark.
```

So I believe the browser behavior (and NLS behavior too) is wrong.

**Comment by tarekgh** [comment]
@Genbox I am closing this issue as I think I already answered your question. Feel free to send any more questions if you have any and we'll be happy to help with.
