### ISSUE TITLE
Allow System.Net.WebUtility.UrlEncode to use %20 instead of + to encode spaces

### ISSUE THREAD

**Issue by aaronfranke** [dotnet/runtime#45328]
https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urlencode

## Background and Motivation

https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

In a nutshell, `+` in a URL is ambiguous, it can be interpreted as either a space (unambiguously encoded as `%20`), or a literal `+` (unambiguously encoded as `%2B`), so it's best avoided. C# already uses `%2B` for encoding a literal `+`, but encodes spaces as `+`. If we change the `UrlEncode` to use `%20` (or make it an option), this ambiguity disappears.

It would be fairly trivial to use `UrlEncode(something).Replace("+", "%20")`, but I think we should endorse the "correct" usage.

## Proposed API

```cs
// namespace System.Net
// public static class WebUtility

public static string UrlEncode(string value);
public static byte[] UrlEncodeToBytes(byte[] value, int offset, int count);
```

Replace the above APIs with one of the following three options (the names of the arguments can be changed etc):

```cs
public static string UrlEncode(string value, bool spacesArePluses = false);
public static byte[] UrlEncodeToBytes(byte[] value, int offset, int count, bool spacesArePluses = false);
```

OR:

```cs
public static string UrlEncode(string value, bool spacesArePluses = true);
public static byte[] UrlEncodeToBytes(byte[] value, int offset, int count, bool spacesArePluses = true);
```

OR: The API is the same, but the behavior is changed so that it always encodes spaces as `%20`.

If we make `%20` the default option, even though it would result in a different string, compatibility is still preserved, since it decodes to the same URL with `UrlDecode`.  The `UrlDecode` method does not need to be changed at all with this proposal.

## Usage Examples

With the below line of code, it outputs `Godot+Engine%3A%27docs%2Byou%27` with the current behavior, but the proposal is to allow changing the output to `Godot%20Engine%3A%27docs%2Byou%27` somehow.

```cs
Console.WriteLine(System.Net.WebUtility.UrlEncode("Godot Engine:'docs+you'"));
```

The round-trip behavior does not change with or without this proposal. The below code will output `Godot Engine:'docs+you'` with the current behavior and with this proposal.

```cs
Console.WriteLine(System.Net.WebUtility.UrlDecode(System.Net.WebUtility.UrlEncode("Godot Engine:'docs+you'")));
```

## Alternative Designs

There are several alternative designs for this API. I think there should probably be an option to allow users to pick between `+` and `%20`. Which one is default is up for debate, `+` would keep the current output exactly the same, and `%20` would behave properly everywhere that `+` does, but would technically give different strings. Another debate is whether this should be an option at all, it might make sense to always have spaces encoded as `%20` because it's unambiguous everywhere.

## Risks

This does softly break compatibility in that you technically get a different string when encoding, but both of the encoded values are identical valid URLs when decoded.

**Comment by MihaZupan** [comment]
If you are looking at encoding/decoding strings for use in Uri queries, you should always be using `Uri.EscapeDataString` and `Uri.UnescapeDataString`.

```c#
Uri.EscapeDataString("Godot Engine:'docs+you'")
// Godot%20Engine%3A%27docs%2Byou%27
```

Uri does what I believe you are asking WebUtility to do in this proposal.

While I dislike the use of + for spaces because of its ambiguity, it is a known behavior of WebUtility. There is no real justification to change it at this point, considering `Uri` does the 'right thing' here.

**Comment by MihaZupan** [comment]
Thank you for the detailed description of the issue. I am closing the proposal as I believe the scenario is already addressed with existing Uri APIs.
We should consider guiding people away from `WebUtility` with docs/deprecations like we did with `EscapeUriString` for 5.0.

Feel free to reopen it if there is some behavioral/API limitation preventing you from using Uri in these cases.

**Comment by aaronfranke** [comment]
@MihaZupan That's a good idea, I would appreciate linking to better replacements in the documentation, and maybe also add a deprecation warning in the code.
