### ISSUE TITLE
Feature request: alpine 32bit support

### ISSUE THREAD

**Issue by tigerinus** [dotnet/runtime#45343]
# Issue Title

It would be nice to include alpine 32bit support.

# General

Was working on an IoT project. It's a 32bit arm device running Alpine. Had to switch to JDK since there isn't a DotNet build for this environment. Would be nice to see Alpine 32bit support in future so I can build projects in DotNet.

**Comment by danmosemsft** [comment]
@janvorli

**Comment by janvorli** [comment]
The Alpine ARM32 support was added in .NET 5.0 for the runtime, but it came close before the final release and I've missed porting the necessary change in  aspnetcore to 5.0.  This should be fixed in the upcoming 5.0.1 service release.

**Comment by krwq** [comment]
@janvorli has the port happened? Can this be closed now?

**Comment by janvorli** [comment]
Yes, Alpine arm 32 bit is supported in .NET 5.0 and 6.
