### ISSUE TITLE
Test failure: System.Globalization.Tests.DateTimeFormatInfoMiscTests.JapaneseAbbreviatedEnglishEraNamesTest

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45348]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902316&view=ms.vss-test-web.build-test-results-tab&runId=28813622&resultId=113191&paneView=debug

net6.0-windows-Release-x86-CoreCLR_checked-jitstressregs0x10-Windows.10.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: 1
Actual:   5

Stack trace
   at System.Globalization.Tests.DateTimeFormatInfoMiscTests.JapaneseAbbreviatedEnglishEraNamesTest() in /_/src/libraries/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoTests.cs:line 195
~~~

**Comment by tarekgh** [comment]
I believe this is related to Crossgen2 which is reverted by #45320. closing this one and we can reactivate if we see the issue agian.
