### ISSUE TITLE
Test failure: System.Globalization.Tests.DateTimeFormatInfoMiscTests.TestFirstYearOfJapaneseEra

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45349]

**Comment by v-haren** [comment]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902316&view=ms.vss-test-web.build-test-results-tab&runId=28813622&resultId=113194&paneView=debug

net6.0-windows-Release-x86-CoreCLR_checked-jitstressregs0x10-Windows.10.Amd64.Open


Error message
~~~
Parsing '平成 元年 01月 08日' result should match if '明治 122年 01月 08日' has Gan-nen symbol
Expected: True
Actual:   False

Stack trace
   at System.Globalization.Tests.DateTimeFormatInfoMiscTests.TestFirstYearOfJapaneseEra() in /_/src/libraries/System.Globalization/tests/DateTimeFormatInfo/DateTimeFormatInfoTests.cs:line 183
~~~

**Comment by tarekgh** [comment]
I believe this is related to Crossgen2 which is reverted by #45320. closing this one and we can reactivate if we see the issue agian.
