### ISSUE TITLE
Remove dependence on .NET 5 feeds

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#45359]
The dependence on dotnet5* feeds in builds of this repo may be somewhat contributing to feed throttling. NuGet is very aggressive about requesting info about packages, and essentially hits all input feeds in parallel.

Runtime may be able to mitigate this somewhat by upgrading input dependencies still on the .NET 5 feeds to be 6.0*, then removing those feeds.

**Comment by mmitche** [comment]
@ViktorHofer

**Comment by ViktorHofer** [comment]
will re-start working on it in https://github.com/dotnet/runtime/pull/41620

**Comment by ViktorHofer** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/41593
