### ISSUE TITLE
Using Covariant returns for RuntimeType crashes during crossgen

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#45356]
This PR https://github.com/dotnet/runtime/pull/45355 crashes in crossgen

Using WinDebug it crashed on this line

https://github.com/dotnet/runtime/blob/29e9b5b7fd95231d9cd9d3ae351404e63cbb6d5a/src/coreclr/src/vm/array.cpp#L290

Due to `g_pArrayClass` being a null ptr

https://github.com/dotnet/runtime/blob/29e9b5b7fd95231d9cd9d3ae351404e63cbb6d5a/src/coreclr/src/vm/array.cpp#L270-L271

/cc @janvorli

**Comment by janvorli** [comment]
@benaadams it seems that the fix here is simple. With the change below, I was able to successfully build runtime:
```diff
diff --git a/src/coreclr/src/vm/appdomain.cpp b/src/coreclr/src/vm/appdomain.cpp
index f703b4214ce..87cc347fe10 100644
--- a/src/coreclr/src/vm/appdomain.cpp
+++ b/src/coreclr/src/vm/appdomain.cpp
@@ -1448,13 +1448,13 @@ void SystemDomain::LoadBaseSystemClasses()
     g_pEnumClass = CoreLibBinder::GetClass(CLASS__ENUM);
     _ASSERTE(!g_pEnumClass->IsValueType());

+    // Load Array class
+    g_pArrayClass = CoreLibBinder::GetClass(CLASS__ARRAY);
+
     // Load System.RuntimeType
     g_pRuntimeTypeClass = CoreLibBinder::GetClass(CLASS__CLASS);
     _ASSERTE(g_pRuntimeTypeClass->IsFullyLoaded());

-    // Load Array class
-    g_pArrayClass = CoreLibBinder::GetClass(CLASS__ARRAY);
-
     // Calling a method on IList<T> for an array requires redirection to a method on
     // the SZArrayHelper class. Retrieving such methods means calling
     // GetActualImplementationForArrayGenericIListMethod, which calls FetchMethod for
```

**Comment by janvorli** [comment]
I am running coreclr tests with your change and this fix to verify everything is fine.

**Comment by benaadams** [comment]
Is a suggestion some of the types might get linked out https://github.com/dotnet/runtime/pull/45355#discussion_r532596787; which would be a different reason if the tests fail :)

**Comment by janvorli** [comment]
So unfortunately the fix doesn't work at runtime. Attempt to run anything crashes. I need to figure out why.

**Comment by benaadams** [comment]
Might be ILLink step removing too many things?

**Comment by benaadams** [comment]
Jit diff now works with your fix https://github.com/dotnet/runtime/issues/45356#issuecomment-735831848 🙂

Which I was trying to use to evaluate if covariant returns made much difference, and indeed it looks to allow devirtualization:

![image](https://user-images.githubusercontent.com/1142958/100635510-82bc0280-3328-11eb-8d4d-3733b3a43d0f.png)

**Comment by janvorli** [comment]
@benaadams I have a fix, it required just a bit more involved reordering of stuff in the SystemDomain::LoadBaseSystemClasses. With that, all the pri1 coreclr tests pass with your change.

**Comment by benaadams** [comment]
Thank you 😁

**Comment by janvorli** [comment]
The crossgen is dead now, replaced by crossgen2 completely, closing the issue.
