### ISSUE TITLE
Configuring Blazor Trimmer in Library

### ISSUE THREAD

**Issue by frankabbruzzese** [dotnet/runtime#45353]
### 
I am writing a Blazor Library, say **B**  that uses other libraries I can't access, say **C**.  Now I need to prevent some dependencies of **C** is trimmed (a whole assembly). However, it appears that `TrimmerRootAssembly`, and `TrimmerRootDescriptor` work only in the application main project say **A**.

I don't want to force the users of my library **B** to configure the trimmer just to make my library **B** works properly. I have not enough knowledge of the code of **C** to use attributes like the `DynamicDependency` attribute

### Describe the solution you'd like
`TrimmerRootAssembly`, and `TrimmerRootDescriptor` work also in library projects, and not only in the main project.

**Comment by vitek-karas** [comment]
How does the app reference B or C - is it a ProjectReference or PackageReference?

This is generally a way how MSBuild works - settings for a project are local to that project. So in this case you would need to influence the project of the app. NuGet packages can do that by including targets or props files which will be included into the app's project.

There's a discussion on this exact topic in this design doc: https://github.com/mono/linker/pull/1647

**Comment by frankabbruzzese** [comment]
@vitek-karas ,
No, everything takes place via package references, because **A**, **B**, and **C** have different owners. I am the owner of **B** and I don't want **A** takes care of **C** that is a dependency of mine.

I need that when the whole **A** application is trimmed some assemblies that are dependencies of **C** are included, but I have no access to **C**. Moreover, I need this is automatic, without any declaration made in  **A** (I don't want to bother the users of my libraries with my dependencies).

I imagine that declarations in a project can only affect the project being processed, that is why previous Blazor versions supported embedding a `LinkerConfig.xml` file as a resource in **B**, that contained all specifications of what methods type or what assemblies to include. Now a file with the same syntax can only be specified in the main **A**, and specifically in its project file with:
 ```
<ItemGroup>
    <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
 </ItemGroup>
```
Why the above xml file NOW cannot be include also as a resource in library files, anymore?

**Comment by vitek-karas** [comment]
As far as I can tell the `LinkerConfig.xml` is basically "linker descriptor" file - see the [data format](https://github.com/mono/linker/blob/master/docs/data-formats.md#descriptor-format).

I've never heard of it being called "LinkerConfig.xml" though - interesting (I learned about this today). In any case embedded descriptors are definitely supported. The embedded file should be called `ILLink.Descriptors.xml` and use the format mentioned above.

In general we try to not use linker descriptors because they unconditionally include the specified thing - but it's equivalent to `TrimmerRootDescriptor`. If you know about the dependencies on a deeper level you can use `DynamicDependencyAttribute` in the affected code. If you're interested in the topic of trimming libraries and possible future - take a look at https://github.com/dotnet/designs/pull/169.

**Comment by eerhardt** [comment]
@frankabbruzzese - by default, the only assemblies that are trimmed in a Blazor application are:

* System.*.dll
* Microsoft.Extensions.*.dll
* Microsoft.AspNet.Core.*.dll

Is your **"C"** assembly above one of those assemblies? If not, it shouldn't be a candidate for trimming (by default) in a Blazor application. So I'm curious to understand why it would be trimmed.

**Comment by frankabbruzzese** [comment]
@vitek-karas ,

> I've never heard of it being called "LinkerConfig.xml" though - interesting (I learned about this today)

It is in 3.1 documentation for Blazor WebAssembly, [here](https://docs.microsoft.com/en-US/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1#add-an-xml-linker-configuration-file-to-a-library). Maybe, its file name is not necessarily that, since they put constraints on its logical name being the same as the library.



`TrimmerRootDescriptor` works only in the main application project file, while the resource file should work also in library projects. Is this the case for `ILLink.Descriptors.xml`? Does it work also when included in library projects?

The optimal solution is the author of `C` uses the DynamicDependencyAttribute himself. Probably, this will happen .... but in the meantime, I need to publish my library :)

@eerhardt ,
No, `C` is always included, of course, the problem is with the dependencies of `C` that have the `System.*.dll` format and are invoked with reflections: types are not included, so `C` crashes, causing the methods of `B` to crash, too.

**Comment by eerhardt** [comment]
@frankabbruzzese - is there anyway you can provide concrete information (ex. exception call stacks, etc)? If there is a problem in linking certain System.* assemblies, we’d like to get them fixed.

**Comment by vitek-karas** [comment]
Linker descriptor should work in any assembly which will end up in the application (if the entire assembly is removed, then its descriptor is ignored).

**Comment by frankabbruzzese** [comment]
@vitek-karas ,
You are right embedded resources continue working and in the past version, so I am solved my issue and I am going to close this issue. However, there is a documentation issue: any mention of the possibility to use embedded XML files disappeared from the documentation. So maybe, it would be better to open a new issue for the documentation repository, in some other place (not clear to me "where", since trimming is in part documented on MSDN and in part on GitHub). I understand that embedded resources are not the optimal choice, but it might be needed, at least till the whole ecosystem will adapt to the usage of dependency attributes.

@eerhardt ,
Below the error I got:
![Errore](https://user-images.githubusercontent.com/614976/101238751-8a8df500-36e2-11eb-823a-721fb3c11dc7.PNG)

What is interesting about this error is that it doesn't mention a specific type, as it is typical of errors due to trimming, but the whole `System.Runtime` library. 
I don't know exactly the whole processing performed by the trimmer but I know the content of `System.Runtime`: it just forwards common types to other dlls. So, it appears that the linker tries to completely shortcut `System.Runtime`, by replacing the type references. Therefore, when `System.Runtime` is invoked via reflection the whole library is missing. 

I suspect that also using dependency attributes might not solve the problem when one specifies "System.Runtime" in the attribute if the trimmer tries to shortcut "System.Runtime".
