### ISSUE TITLE
Enum JsonConverter allows invalid ints in non-flags input

### ISSUE THREAD

**Issue by onionhammer** [dotnet/runtime#45362]
This code makes use of Unsafe.As to give API users a false sense of security with their enum inputs. If your code expects the JSON converter to error if it receives an int out of range of your enum, you are mistaken, it will instead pass on an invalid enum.

https://github.com/dotnet/runtime/blob/839ad29b16a8baf7b1470f13d7faa0ce941769b3/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L75

For non-flags attribute Enums, it would be relatively trivial to check against a hashed set of valid values before executing the unsafe conversion; i.e.

```C#
        T SaferConvert<K>(ref K value)
            where K : struct
        {
            if (!_hasFlags && !_validCache.ContainsKey(value.GetHashCode()))
                throw new JsonException("Unable to parse input value: " + value);

            return Unsafe.As<K, T>(ref value);
        }
```

**Comment by GrabYourPitchforks** [comment]
In .NET, all values of the backing integral type are also valid values of the enum. For instance, the expression `(StringComparison)(-1)` is perfectly sage and legal C#. It's generally up to the consumer / business logic to validate that incoming values are within some allowed range, same as if the app were allowing an _int_ as input.

**Comment by onionhammer** [comment]
@GrabYourPitchforks so then by that logic the converter should not error if there is an invalid string, it should just return a wacky undefined value?

**Comment by GrabYourPitchforks** [comment]
You mean the equivalent of `(StringComparison)"Hello!"`? That's not legal C# and wouldn't compile. Unless I misunderstood your question.

**Comment by onionhammer** [comment]
No, I'm not talking about C# enums broadly, I'm talking about the JsonConverter. 

Currently, you get inconsistent behavior from the JsonConverter when you use an out of range string vs. an out of range integer. Your original reply was essentially restating the problem that I raised in my post; the problem is ALL ints will be valid as far as C# enums are concerned, but, arguably, the JsonConverter should handle that and error if the int is undefined by the enum the same way a string value would.

**Comment by onionhammer** [comment]
Perhaps this is the wrong level of the stack? Perhaps the modelbinding of ASP.NET core is at fault?

**Comment by GrabYourPitchforks** [comment]
> "an int out of range of your enum"

> "if the int is undefined by the enum"

I think this is where the misunderstanding lies. There's no such thing as an undefined / out of range int when it comes to an enum. An enum is best thought of as "an integer where certain values happen to have friendly names". There are ~4bn legal ints, so there are ~4bn legal values for any int-backed enum.

If you have .NET code which consumes an enum, you need to make sure the incoming value is within the range _you expect_. Similarly, an int can be negative, but your business logic might only accept ints in the range 1 ~ 100. That's on the business logic layer to validate.

That being said, you could imagine a JSON converter which says "I only allow values with a defined friendly name, not arbitrary integers." But now you're talking about something that includes business logic-specific policy as a part of conversion, which is generally outside the scope of serializers. This is validation that would need to be duplicated in your business logic layer.

**Comment by GrabYourPitchforks** [comment]
> At the end of the day, though, does anybody want the (SomeEnum)-1 value in their database? If not, how do we prevent it?

How do you currently prevent somebody from sticking the value -1 in the "ItemQuantity" column? Use that same mechanism, whether it's a model binding attribute, an explicit check in the code, a sproc, or something else.

**Comment by Clockwork-Muse** [comment]
> At the end of the day, though, does anybody want the (SomeEnum)-1 value in their database? If not, how do we prevent it?

.... As an additional take on this, consider:

 - I've generally seen JSON APIs use _text_ values for enums, to make it more readable.
 - Your database should absolutely have a constraint on that column, probably a FK to another table.  Otherwise you're just waiting for some database fixup script to slam in the wrong value.

**Comment by onionhammer** [comment]
It seems like you guys prefer the easy/natural path to lead straight to a built-in foot-gun. I prefer the easy/natural path to lead to some handrails. If I dotnet new up a new web project, which allows ints for an enum, you expect beginners to know they have to manually loop through the valid values of an enum with reflection and crossreference it to return a badrequest?

**Comment by onionhammer** [comment]
Closing this issue, since actually it looks like it is caught by default in .net5 webapi validation, I've had only tested on up to 3.1 so far

**Comment by layomia** [comment]
FWIW - dup of https://github.com/dotnet/runtime/issues/42093.
