### ISSUE TITLE
Move zic invocation into dotnet/runtime-assets

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#45368]
So we don't need to run it on each dotnet/runtime build.

---

Old description:
```
src/mono/wasm/wasm.proj(69,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) zic -d "/__w/1/s/artifacts/obj/wasm/timezones" "/__w/1/s/.packages/system.runtime.timezonedata/5.0.0-beta.20505.2/contentFiles/any/any/data/backward" returned exit code 1
```

https://dev.azure.com/dnceng/public/_build/results?buildId=903002&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4

cc @akoeplinger

**Comment by akoeplinger** [comment]
@tqiu8 can you please work on moving the timezone files generation to dotnet/runtime-assets so we don't need to run it on each build in dotnet/runtime?

**Comment by ViktorHofer** [comment]
Does zic have a more verbose log level? That would be great to have enabled.

**Comment by ViktorHofer** [comment]
Just found out with @akoeplinger offline, the error was a wrong test data package being used in my PR. We might still want to use this issue to track moving zic.

**Comment by akoeplinger** [comment]
yeah there's a `-v` flag to enable verbose logging in zic
