### ISSUE TITLE
Add Project Reference in Visual Studio 2019

### ISSUE THREAD

**Issue by clockwiseq** [dotnet/runtime#45361]
### Description

I'm 99% sure I'm submitting this in the wrong repo, but I'll let you guys decide where it needs to go.  Since the latest update to VS2019 and using .NET 5 in my projects, when I attempt to perform the quick action in VS to add project reference, it just stalls:

![image](https://user-images.githubusercontent.com/6662538/100631539-71a3cf00-32f1-11eb-9d4c-6f7939e550ff.png)

**Comment by hoyosjs** [comment]
@davkean @drewnoakes My guess is this is more likely to go in dotnet/project-system? I can't transfer over there.

**Comment by drewnoakes** [comment]
I believe the dialog is owned by dotnet/roslyn, though it's hard to know why the delay occurs by just looking at a screenshot. The problem could be in dotnet/project-system, or in the internal CPS subsystem, or anywhere else for that matter.

@clockwiseq can you use the "report a problem" feature in VS which will capture a trace and other diagnostic information to assist in diagnosing and correctly routing this problem?

https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

**Comment by clockwiseq** [comment]
Yes, I will do that.
