### ISSUE TITLE
Establish and document assembly versioning policy for servicing in 5.0

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#45369]
Please close on the discussion started here: https://github.com/dotnet/runtime/pull/44877/files#r529830336

To make a serviceable ref-pack for ASP.NET we cannot increment any of the reference assemblies which make their way into the ASP.NET shared framework.

These make it ASP.NET via standalone packages, and transport packages.

The only places we must increment the assembly version are for assets which apply to .NETFramework.  Also, we cannot increment a .NETStandard asset if that same asset is shipped for .NETCoreApp (anywhere) and not incremented.

cc @dougbu

**Comment by ericstj** [comment]
It may be sufficient to only increment the `.NETFramework` assembly versions, since I believe @joperezr added validation to ensure we always ship a `.NETFramework` applicable asset.

One thing we could consider is to define a property called ServicingAssemblyVersion and always set it, but then have the build decide when to apply it (to avoid contributors getting a condition wrong).

**Comment by ViktorHofer** [comment]
@Anipik is this already done?
