### ISSUE TITLE
ExcludeFromCodeCoverage ignored on async methods

### ISSUE THREAD

**Issue by dpuckett** [dotnet/runtime#45374]
This is likely related to [this issue](https://github.com/dotnet/core/issues/4361) but is another area not being addressed/mentioned

A method marked as async returning any Task/Task<> is ignored by the ExcludeFromCodeCoverage attribute.

I'm working with Xamarin and some libs such as Xamarin.Essentials and AzureCrossPushNotification, the internals of which do not need to be tested by myself. So I have abstracted the exact use of these into separate wrapper classes and try to exclude from test coverage.

However it seems that with the methods marked "async", they're still included in test coverage. 
Removing async/await the method is instantly excluded from coverage correctly.

Not Excluded:
```c#
public class CrossAzurePushNotificationWrapper : ICrossAzurePushNotificationWrapper
{
    [ExcludeFromCodeCoverage]
    public async Task RegisterAsync(string[] tags)
    {
        await CrossAzurePushNotification.Current.RegisterAsync(tags);
    }
}
```

Excluded:

```c#
public class CrossAzurePushNotificationWrapper : ICrossAzurePushNotificationWrapper
{
    [ExcludeFromCodeCoverage]
    public void RegisterAsync(string[] tags)
    {
        CrossAzurePushNotification.Current.RegisterAsync(tags);
    }
}
```

### Configuration
Tool: System.Diagnostics.CodeAnalysis ExcludeFromCodeCoverageAttribute  / Test Explorer

**Comment by stephentoub** [comment]
> The System.Diagnostics code lives in dotnet/runtime. I'll transfer the issue over there.

dotnet/runtime isn't the right place, either.  The attribute lives in dotnet/runtime, but code coverage tools do not: this attribute is just a marker that any code coverage tool can use to determine whether the author of that method wants it excluded, and how such a tool reacts to the attribute is up to the attribute.  This would end up being an issue for whatever code coverage tool is being used.

What tool are you using for code coverage?

**Comment by dpuckett** [comment]
I am using the code coverage tool built in to Visual Studio 2019

**Comment by stephentoub** [comment]
In that case, I think you want to open this in https://github.com/microsoft/vstest instead.  Thanks.

**Comment by hoyosjs** [comment]
Closing this in favor of https://github.com/microsoft/vstest/issues/2658
