### ISSUE TITLE
SequenceReader contains invalid volatile memory access patterns

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#45379]
See code:

https://github.com/dotnet/runtime/blob/c8a97ff77957202323b64b8513f363366010343f/src/libraries/System.Memory/src/System/Buffers/SequenceReader.cs#L97-L108

Accesses to the *_length* field are not guaranteed atomic on 32-bit platforms without going through the _Volatile_ or _Interlocked_ APIs. While the write is protected by such a guard, the read is not. This could result in the *_length* backing field being torn and the *Length* property returning an incorrect value on 32-bit platforms.

**Comment by GrabYourPitchforks** [comment]
A possible fix:

* On all platforms, use _Volatile_ for both reads and writes. (On 32-bit platforms, this results in an interlocked operation.) **OR**

* On 64-bit platforms, don't use _Volatile_. On 32-bit platforms, while reading, perform a volatile read of the high 32 bits first, then a non-volatile read of the low 32 bits. If the result is negative, write the low 32 bits first, then perform a volatile write of the high 32 bits. This will not result in an interlocked operation.

**Comment by gfoidl** [comment]
SequenceReader is a `ref struct`, so stack-only. Is atomicity a problem here? Also is visibility (volatile) a concern?

https://github.com/dotnet/runtime/blob/c8a97ff77957202323b64b8513f363366010343f/src/libraries/System.Memory/src/System/Buffers/SequenceReader.cs#L11

**Comment by GrabYourPitchforks** [comment]
> SequenceReader is a ref struct, so stack-only. Is atomicity a problem here? Also is visibility (volatile) a concern?

Good point. I'm trying to remember why it's a ref struct since it doesn't contain any byref fields. If it's intended to be a ref struct, then yeah, we can kill all of the volatile goop.

**Comment by gfoidl** [comment]
> trying to remember why it's a ref struct

From https://github.com/dotnet/runtime/issues/27522

> SequenceReader can't be used in async methods

So it's intentional to prevent this?!

**Comment by benaadams** [comment]
> I'm trying to remember why it's a ref struct since it doesn't contain any byref fields

Except this one 😉

```csharp
public ReadOnlySpan<T> CurrentSpan { readonly get; private set; }
```

**Comment by GrabYourPitchforks** [comment]
Aaaargh. I hate that it's buried with other properties and isn't grouped with the fields at the top of the file.

**Comment by GrabYourPitchforks** [comment]
Then it sounds like @gfoidl's suggestion is the best one. Find places in `SequenceReader<T>` that try to be thread-safe (are there others aside from this?) and remove the unneeded thread safety aspects.

**Comment by gfoidl** [comment]
@GrabYourPitchforks are you working on this? Otherwise I can have a look.

**Comment by GrabYourPitchforks** [comment]
I wouldn't change the layout of the file as part of this PR. Just lamenting generally. 😞

**Comment by gfoidl** [comment]
This was the only occurance --> https://github.com/dotnet/runtime/pull/45437 (hope it's an easy review 😉).

**Comment by GrabYourPitchforks** [comment]
Thanks @gfoidl and @adamsitnik for handling this! :)
