### ISSUE TITLE
Support Managed Threadpool Diagnostics

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#45384]
The goal is to maintain parity with existing diagnostics for the native thread pool.  Currently the concrete work for this item is:

- [ ] Make NativeRuntimeEventSource.cs as a general way of sending runtime events from managed side, as opposed to what it is now
- [x] Make sure the events being fired from the managed ThreadPool is being fired correctly.
- [ ] Fix EventListener deadlock that can occur as part of enabling managed threadpool events through EventListener 
- [ ] Make sure EventListeners can subscribe to managed threadpool events
- [ ] Test LTTng events can still get fired from managed threadpool under the Microsoft-Windows-DotNETRuntime provider

**Comment by sywhang** [comment]
https://github.com/dotnet/runtime/pull/45666 fixed an issue where the managed threadpool was firing several verbose threadpool events whenever *any* event is enabled.
