### ISSUE TITLE
wrong error messages in DeleteFile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45398]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/wrong-error-messages-in-DeleteFile/1146912)._

---
<p>Function Microsoft.VisualBasic.FileIO.FileSystem.DeleteFile has wrong error messages if it is used to delete file to the recycle bin. If any IOException occurs, then exception message is nonsense. For example it throws exception &quot;This function is not supported on this system.&quot; if current user does not have permissions. If a network path is invalid, it throws exception &quot;The system call level is not correct.&quot;. I think the problem is that it internally calls Win32 API function SHFileOperation which has some special error numbers.</p>

---
#### Feedback Bot on 8/12/2020, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/20/2020, 01:42 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Dada Huo [MSFT] on 11/25/2020, 00:01 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ?<br>
If so, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you can provide a screenshot of this issue.</p>
<p>We look forward to hearing from you!</p>

#### Petr Laštovička on 11/30/2020, 03:52 AM: 

<p>I have installed the latest Visual Studio and .Net 5.<br>
This is a sample C# 9 project:</p>
<pre><code><span class="hljs-keyword">using</span> Microsoft.VisualBasic.FileIO;
<span class="hljs-keyword">using</span> System;
<span class="hljs-keyword">using</span> System.Windows.Forms;

<span class="hljs-keyword">try</span>
{
  FileSystem.DeleteFile(@<span class="hljs-string">"C:\Windows\System32\kernel32.dll"</span>, UIOption.OnlyErrorDialogs, RecycleOption.SendToRecycleBin);
}
<span class="hljs-keyword">catch</span> (Exception ex)
{
  MessageBox.Show(ex.Message);
}
</code></pre>
<p>I would expect error that access is denied. But it shows message “This function is not supported on this system.”</p>

---
### Original Solutions
(no solutions)

**Comment by danmoseley** [comment]
Indeed, here
https://github.com/dotnet/runtime/blob/06060cde583c57820bd6578171c352c5e635b000/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/FileIO/FileSystem.vb#L1722

it is treating these special codes as Win32 codes, which as explained here are in some cases different
https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shfileoperationw#return-value

The docs also say the codes may change and are only for debugging. The correct fix here is probably to map a few eg DE_ACCESSDENIEDSRC ->ERROR_ACCESS_DENIED, DE_INVALIDFILES->ERROR_FILE_NOT_FOUND and pass to ThrowWinIOError, and just throw a new IOException with a genreic message and the code for everything else.
