### ISSUE TITLE
[Discuss]  non-null ref-types 

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/runtime#4540]
The C# and VB.net language teams are investigating options of enabling non-null reference types.
It seems that there is a barrier to this, the CLR, or the Type-System doesn't support it.
Let's see if the is anything we can to fix it.

**General Ideas**
The following general ideas and concepts have been proposed.
- null-ability tracking.
- allow `default(T)` be overridden.
- add a new "default value" to the base-class object or (`class type`)
  - static type extension method for enable a **default** for sealed types.  
    `string! default(this static string )`

``` c#
nonnull class foo
{
  must override static foo! default {}
}
```
- optional parameters extended to support other things that just constants.

``` c#
foo( baz! x => baz!.Default ){ }
```
- Atomic-Like constructors and initialisers.
  Some how make construction and initialisation _out of phase_ doesn't exist yet until it has be fully constructed and initialised. Then it would _instantaneously_ be useable.

``` vb
 dim x As New Foo with {.bar = 1, .baz = "Hello World!" }
 '   |--------------------------------------------------| atomic     /v  sync locked
```

**Comment by mangod9** [comment]
Closing since this hasnt been touched in 5 years.
