### ISSUE TITLE
 The original target frameworks value must match the aliases while restore

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#45400]
```
Error occurred while restoring NuGet packages: Invalid restore input. Original target frameworks: netcoreapp3.0-windows;netstandard2.1, aliases: netcoreapp3.0;netstandard2.1.
```
The projects which have just one cross platform old configuration would throw this error instead of duplicate restore error.
https://github.com/NuGet/NuGet.Client/blob/508808ef8ed761179d4c214551e9505d005e5aac/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/SpecValidationUtility.cs#L228

I was not able to track on the reason why where they value for aliases is diverging for the original tfms.
we donot need to strip the platforms in this scenario and not stripping the platform fixes this issue for us.

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
> we donot need to strip the platforms in this scenario and not stripping the platform fixes this issue for us.

I believe not stripping the suffix would make NuGet treats the suffix as the `TargetFrameworkProfile` for anything older than net5.0.

> I was not able to track on the reason why where they value for aliases is diverging for the original tfms.

I think we should understand why the stripping isn't respected... Sounds to me like this regressed recently.

**Comment by Anipik** [comment]
> I think we should understand why the stripping isn't respected... Sounds to me like this regressed recently.

no it was hidden behind the invalid restore earlier because that duplicate check is before this one. I saw this while moving to the new platform feature. (But it got fixed for most of the projects when we stopped stripping)

**Comment by ViktorHofer** [comment]
Why was the duplicate check throwing for configurations that didn't had duplicates? In your example there aren't any duplicates: `netcoreapp3.0-windows;netstandard2.1`

**Comment by Anipik** [comment]
This is a new project we are trying to add.

**Comment by ViktorHofer** [comment]
@Anipik what should we do about this issue? Is this something that is still happening? @danmoseley do you remember in which project you hits error when using VS?

**Comment by ViktorHofer** [comment]
@Anipik will verify if this is still happening for System.Runtime.

**Comment by ViktorHofer** [comment]
Closing as we don't do any tfm stripping anymore (which was the underlying reason for the error).
