### ISSUE TITLE
How to find branch or tag for release/3.1

### ISSUE THREAD

**Issue by yanhua1012** [dotnet/runtime#45403]
I want to checkout source code for release 3.1. There isn't any branch or tag with release 3.1 exists. 
Does it exist in other repository? How can I find it, thanks.

**Comment by benaadams** [comment]
3.1 was before the merge to `runtime` so are coreclr https://github.com/dotnet/coreclr/tree/release/3.1 and corefx https://github.com/dotnet/corefx/tree/release/3.1

**Comment by yanhua1012** [comment]
> 3.1 was before the merge to `dotnet/runtime` so are `dotnet/coreclr` https://github.com/dotnet/coreclr/tree/release/3.1 and `dotnet/corefx` https://github.com/dotnet/corefx/tree/release/3.1
Thanks for your reply.
