### ISSUE TITLE
API to change a delegate's type to a signature-compatible different delegate type

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/runtime#45408]
## Background and Motivation
Inspired by a pair of comments between @GrabYourPitchforks and @jkotas at https://github.com/dotnet/runtime/issues/4556#issuecomment-736172061
> Say that I have a `Predicate<string>`, but I need a `Func<string, bool>`. There's one kinda-hokey workaround right now:
> 
> ```cs
> Predicate<string> del1 = GetDelegate();
> Func<string, bool> del2 = del1.Invoke; // points to Predicate<string>.Invoke's MethodDesc
> ```
> 
> But this isn't ideal since it's a hidden recursive operation: every invocation incurs an extra indirection.

Since Jan said this should be a separate API, here we are.

## Proposed API
```cs
namespace System
{
    public abstract partial class Delegate
    {
        [return: NotNullIfNotNull("del")]
        public static TDelegate? ChangeType<TDelegate>(Delegate? del) where TDelegate : Delegate;
    }
}
```
This method is Null-in-Null-out. Exception behavior may be as follows:
* `T` is an incompatible delegate type (`InvalidCastException`?)

## Usage Examples
```cs
Predicate<string> del1 = GetDelegate();
Func<string, bool> del2 = Delegate.ChangeType<Func<string, bool>>(del1); // points to whatever MethodDesc del1 pointed to
```

## Alternative Designs

¯\\\_(ツ)_/¯

## Risks

None that I can think of.

## History

* Removed Try-pattern methods
* Removed non-generic method

**Comment by jkotas** [comment]
> But this isn't ideal since it's a hidden recursive operation: every invocation incurs an extra indirection.

You can avoid the extra indirection by deconstructing the delegate, e.g. something like:

```
Func<string, bool> del2 = del1.Method?.CreateDelegate<Func<string, bool>>(del1.Target) ?? del1.Invoke;
```

This fragment avoids the indirection for the simple single-cast delegates only. It is possible to extend this to handle multi-cast delegates too, but the relative benefit for multi-cast delegates is much less (multi-cast delegates pay for indirection that is much more expensive than the indirection via Invoke method). Same holds for special delegate types like marshaled function pointers.

The assumption behind this API is that the runtime can do the retype in signficantly cheaper way than the above fragment.

This API has to do a signature match that is an relatively expensive operation. Even though the API does not have MethodInfo in its signature, it would be in the same performance category as other reflection APIs that operate on MethodInfo.

**Comment by jkotas** [comment]
>  Stretch goal: Try-pattern methods

I do not see a good reason for having Try-pattern methods for this. There are no Try-pattern that deal with creation of delegates today.

The only method that is needed for the scenario described in the motivation is the non-Try generic overload.

**Comment by huoyaoyuan** [comment]
I remember that:
```csharp
Predicate<int> p = XXX;
Func<int, bool> func = new Func<int, bool>(p);
```
would success.

**Comment by GrabYourPitchforks** [comment]
@huoyaoyuan Good eye. That results in identical codegen to the `Func<int, bool> func = p.Invoke;` case: a delegate wrapping a delegate.

A naïve implementation of the proposed `ChangeType` API could special-case unicast invocations and transfer the method handle + target object into the new delegate instance, per Jan's suggestion, and multicast / unmanaged / ARM64 stub invocations could be implemented as delegate-wrapping-delegate for simplicity. That at least gets the API out the door. It also allows us to optimize the latter cases in a future release without needing to go through API review again.

**Comment by Joe4evr** [comment]
> I do not see a good reason for having Try-pattern methods for this. There are no Try-pattern methods that deal with creation of delegates today.
> 
> The only method that is needed for the scenario described in the motivation is the non-Try generic overload.

Alright, updated the OP.

**Comment by jkotas** [comment]
The expensive part of this API implementation is the signature match check to prove that the retyping is type safe.

I am wondering whether it would be better to have a `static T Optimize(T del) where T: Delegate` method that takes a delegate and restructures it for maximum performance. It can remove the extra delegate to delegate indirections discussed here, inline shufle thunks in future, etc.

**Comment by steveharter** [comment]
Should this be in the `area-TypeSystem-coreclr` instead of reflection?

**Comment by buyaa-n** [comment]
As this has a workaround @jkotas [mentioned here](https://github.com/dotnet/runtime/issues/45408#issuecomment-736530266) and the proposed API has to do a relatively expensive signature match, we don't think this API could be more performant than the existing workaround, therefore closing the proposal. @Joe4evr, @GrabYourPitchforks  feel free to reopen if you have a different opinion
