### ISSUE TITLE
Encoding.GetEncodings() returns Unicode only

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [dotnet/runtime#45413]
### Description

With .NET Framework `Encoding.GetEncodings()` returns a long list of all known encodings (Unicode and others). With .NET Core this changed to unicode only.

This should be solved by doing the following:

```cs
Encoding.RegisterProvider( CodePagesEncodingProvider.Instance );
```

Now e.g. `Encoding.GetEncoding(1252)` works, but `Encoding.GetEncodings()` does not contain it.

I would expect it to return all encodings I can retrieve by `Encoding::GetEncoding`.

### Configuration

* .NET Core 3.1
* Windows 10
* x64

### Regression?

* This worked in .NET Framework and should workd as described in the documentation of `CodePagesEncodingProvider`

**Comment by tarekgh** [comment]
This is done in .NET 5.0. Please try to upgrade to 5.0 to get this feature. Thanks for your report.

**Comment by georg-eckert-zeiss** [comment]
So its not a bug but intended?

**Comment by georg-eckert-zeiss** [comment]
Alright. Found it in the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings?view=net-5.0). Thanks.
