### ISSUE TITLE
DevPath doesn't work on .NET Framework 4

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#45414]
There's no problem on .NET Framework 2.0, but it doesn't work on .NET Framework 4
My environment is .NET Framework 4.8, DevPath doesn't work on all .NET Framework 4.x or some specific versions?
If .NET no longer support DevPath, is there any way instead?

**Comment by jkotas** [comment]
Try the steps described in: https://stackoverflow.com/questions/4099255/support-for-devpath-in-net-4-0

This repo is not a good place to log issues for .NET Framework. The best place to log feedback for .NET Framework is https://developercommunity.visualstudio.com/ .

**Comment by CreateAndInject** [comment]
@jkotas Your steps doesn't work and it's inrelative with .NET 4 (It's mean .NET 2 has the same steps)
I have said it works on .Net 2.0, so I know the steps.
