### ISSUE TITLE
Installing Android .apk fails on some machines/devices

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#45428]
E.g. DNCENGWIN-005 and DNCENGWIN-033 in the windows.10.amd64.android.open queue currently hit an issue where installing any .apk hits this error:

```
Performing Streamed Install
adb: failed to install System.DirectoryServices.Protocols.Tests.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE: Scanning Failed.: Package System.DirectoryServices.Protocols.Tests.apk could not be assigned a valid UID]'
```

**Comment by MattGal** [comment]
I'm going to try to address this as part of the "surge".

**Comment by ericstj** [comment]
I'm seeing this in a ton of PRs, does immediate action need to be taken?
```
[10:23:52] dbug: Executing command: 'C:\h\w\AEAA09A9\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.20576.3\runtimes\any\native\adb\windows\adb.exe -s 014AY1RPX0 install "C:\h\w\AEAA09A9\w\A30D08BF\e\Microsoft.Extensions.Configuration.EnvironmentVariables.Tests.apk"'
[10:23:55] fail: Error:
                 Exit code: 1
                 Standard Output:
                 Performing Streamed Install
                 
                 Standard Error:
                 Performing Streamed Install
                 
                 
[10:23:55] crit: Install failure: Test command cannot continue
XHarness exit code: 78
```

**Comment by akoeplinger** [comment]
@ericstj if this is a PR that ran in the last ~24hours then it probably ran on DNCENGWIN-005 which hit the issue. We disabled that machine in Helix so it shouldn't be hit anymore right now.

**Comment by ericstj** [comment]
Yeah, I noticed in about 6 different PRs I sampled that ran in the last 16 hours or so.  Good to know that this has been mitigated.  Thanks @akoeplinger and @MattGal

**Comment by MattGal** [comment]
https://github.com/dotnet/xharness/pull/388/files

**Comment by akoeplinger** [comment]
The xharness bump landed with https://github.com/dotnet/runtime/pull/45476  and I verified the fix is working (https://github.com/dotnet/xharness/issues/354#issuecomment-737286521).
