### ISSUE TITLE
AssemblyName::ToString throws System.IO.FileLoadException

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#45420]
Compile and Run

```c#
using System;
using System.Reflection;

public class C {
    public static void Main()
    {
        AssemblyName assemblyName = new AssemblyName ("test");
        assemblyName.Name = "";
        var str = assemblyName.ToString ();
    }
}
```

It fails with odd `System.IO.FileLoadException: Could not load the specified file` exception from ToString method. It would make more sense to throw ArgumentException when `Name` property is set.

```
Unhandled exception. System.IO.FileLoadException: Could not load the specified file.
   at System.Reflection.AssemblyNameFormatter.ComputeDisplayName(String name, Version version, String cultureName, Byte[] pkt, AssemblyNameFlags flags, AssemblyContentType contentType)
   at System.Reflection.AssemblyName.get_FullName()
   at System.Reflection.AssemblyName.ToString()
```

**Comment by BartoszKlonowski** [comment]
I would like to handle this.
@steveharter Please assign me to this issue so I can work on this issue.

**Comment by jkotas** [comment]
@BartoszKlonowski It is all yours.

I think it would be better to return empty string in this case. It is generally a good idea to not throw from `ToString()` under normal circumstances.

E.g. `new AssemblyName().ToString()` returns empty string without throwing too.
