### ISSUE TITLE
Casting negative double to uint does not seem to meet the specification, and works inconsistently across platforms

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#45429]
If I'm not missing anything, the following code should throw `System.OverflowException` according to the [Explicit numeric conversions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#explicit-numeric-conversions) section of the C# language specification:

```C#
double a = -1;
uint b = (uint)a;
Console.WriteLine(b);
```

Instead, it will print `uint.MaxValue` on x86.
On Arm64, it seems to return `0` based on my understanding of #45249. I don't have a local repro, but the problem seems to be with the following code on CI:
https://github.com/dotnet/runtime/blob/301056d6ff8f5ac0dea7fe07a8b450754ad846cb/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs#L1010-L1011

When we are casting `Timeout.InfiniteTimeSpan.TotalMilliseconds == -1.0` to `uint` the conversion seems to result in `0` on Arm64, while (also incorreclty) returning -1 on x86.

**Comment by antonfirsov** [comment]
I forgot that default context is unchecked so it's fine, need more sleep.

**Comment by EgorBo** [comment]
If it's `0` on Arm64 then it's a bug 🤔

**Comment by antonfirsov** [comment]
According to the C# spec the unchecked case goes as following:
- If the value of the operand is NaN or infinite, the result of the conversion is an unspecified value of the destination type.
- Otherwise, the source operand is rounded towards zero to the nearest integral value. If this integral value is within the range of the destination type then this value is the result of the conversion.
- Otherwise, the result of the conversion is an unspecified value of the destination type.

I'm wondering how do we handle the "unspecified value" cases. Is it our equivalent of C++ UB?
