### ISSUE TITLE
Developers can safely trim their apps which use System.Text.Json to reduce the size of their apps

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#45441]
There's an ongoing effort (https://github.com/dotnet/runtime/issues/1568) to use the C# source generator feature to improve start-up performance and reduce private bytes usage during JSON serialization. This same effort can help the linker trim more of System.Text.Json.dll, when used in an application, than it can today. This should reduce the total app size and is important for standalone apps and Blazor client.

## Work
- [ ] JSON serialization source generator https://github.com/dotnet/runtime/issues/45448

**Comment by danmosemsft** [comment]
@layomia I changed this from Proposed to In progress. Hopefully that's correct. It's certainly committed.

**Comment by layomia** [comment]
@danmoseley - yup it's in progress, and we've started to get some numbers on potential size savings due to having source generation for JSON.

Now that we can generate code that statically references metadata on input object graphs, we can, based on a prototype linker feature switch (e.g. [this snippet](https://github.com/layomia/JsonSourceGenPerf/blob/main/SizeOpts/ConsoleAfter/ConsoleAfter.csproj#L15)):
- Trim out unused converters since we know which types need to be serialized (https://github.com/dotnet/runtimelab/pull/427)
- Trim out reflection based code-paths that generate  (https://github.com/dotnet/runtimelab/pull/659)

#### Size savings
This gives us some size savings, based on a simple console app.

Before: https://github.com/layomia/JsonSourceGenPerf/tree/main/SizeOpts/ConsoleBefore

After: https://github.com/layomia/JsonSourceGenPerf/tree/main/SizeOpts/ConsoleAfter

| | **Pre-trimmed STJ.dll (KB)** | **Trimmed STJ.dll (KB)** | **Pre-trimmed App (MB)** | **Trimmed App (MB)** | **Pre-trimmed Application .dll (KB)** | **Trimmed Application .dll (KB)** |
| --- | --- | --- | --- | --- | --- | --- |
| **.NET 6 - S.T.J (Before)** | 866 (crossgen&#39;d) | 251 | 63.5 | 17.5 | 5 | 5 |
| **.NET 6 - S.T.J (After)** | 349 | 173 | 63.0 | 17.2 | 7 | 7 |

##### Summary
- 78K savings to STJ dll size
- 300K savings to app size

---

The major scenario we care about for size is Blazor applications. @tannergooding is helping take measurements and perform analysis for Blazor using the source generator.

**Comment by layomia** [comment]
With the JSON source generator checked in, we can consider this work done. Please see ["Try the new System.Text.Json source generator"](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/) for an end-to-end overview of how the generator works and its benefits.
