### ISSUE TITLE
API Boolean ToLowerCaseString

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#45450]
## Background and Motivation

`true`, `false` are common data values for boolean; however `Boolean.ToString()` returns title case values `True`, `False`; nessistating an extension or other method that converts e.g. `value ? "true" : "false"` or additional lowercasing `value.ToString().ToLower()` which allocates.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```csharp
public partial readonly struct Boolean 
{
    public string ToLowerCaseString();
}
```

## Alternative Designs

Extension method; though don't think this adds anything.
```csharp
public static class BooleanExtensions
{
    public static string ToLowerCaseString(this bool value) => value ? "true" : "false";
}
```

**Comment by LeaFrock** [comment]
Would it be better to use(or add) a overload `ToString(string format)`? Just as same as `Guid` like `guid.ToString("N")`, or `DateTime` like `date.ToString("yyyy-MM-dd")`. 
So you can not only use `isTrue.ToString("L")` instead to get "true", but also use `isTrue.ToString("U")` to get "TRUE". 
It can be completely compatible to old version of api, and keep more choice for the future, with just a requirement of doc to inform that.

**Comment by am11** [comment]
This also came up in the context of JSON, #42502, where `True` and `False` values are mostly undesirable.

**Comment by stephentoub** [comment]
_If_ we wanted to add support for this, would it be more consistent to do it via format strings / a `ToString(string)` overload rather than new named methods?
