### ISSUE TITLE
Remove dependency on USE_ZLIB from browser wasm build

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#45454]
This special flag causes the emscripten toolchain to download and build a .zip version of zlib from https://github.com/emscripten-ports/zlib which unnecessarily introduces a network dependency into the build.

We already have a zlib implementation in mono that we can use.

Note that zlib is used both inside of mono and System.Native, we need to make sure only one copy of zlib makes it into the dotnet.wasm.

Three parts to this:
- [ ] Remove duplicated zlib files in the build tree
- [ ] Use one of the checked-in zlib copies for wasm rather than one downloaded at build time
- [ ] Make it possible to link out zlib if System.Compression is unused and runtime is in release (maybe split into separate library? depends on https://github.com/dotnet/runtime/issues/48225)

**Comment by danmosemsft** [comment]
We should at some point reduce the two zlibs in our tree to a single copy. Looks like they're identical versions, but the libraries one has some extra files.

**Comment by danmosemsft** [comment]
For my own reference, here's what we have in the repo currently:

src\libraries\Native\Windows\System.IO.Compression.Native\zlib
from https://github.com/madler/zlib/releases/tag/v1.2.11 (latest - Jan 2017)
Used for Arm and Arm64.

src\mono\mono\zlib
same code as above. I think this is not used in this repo. It is used by by S.IO.C in mono/mono 

src\libraries\Native\Windows\System.IO.Compression.Native\zlib-intel 
from https://github.com/jtkukunas/zlib/tree/v1.2.11.1_jtkv6.3  (latest - April 2019)
Used for x64/x86

**Comment by akoeplinger** [comment]
> src\mono\mono\zlib
> same code as above. I think this is not used in this repo.

This _is_ used by the mono in this repo on platforms that don't ship a system zlib like WASM or Win32.

**Comment by CoffeeFlux** [comment]
Now that the mirror is off, it should be safe to get rid of the Mono-specific copy of zlib, assuming it's identical to the one in libraries. However, like @akoeplinger mentioned, we do it need for some platforms so we can't get rid of both copies altogether. This is somewhat separate from getting rid of `USE_ZLIB` for the wasm build though.

**Comment by CoffeeFlux** [comment]
The `USE_ZLIB` flag is no longer set as of https://github.com/dotnet/runtime/pull/48881, so closing. Will open a separate issue about linking out zlib.

We also still have duplication in the build tree, but it's not particularly urgent.
