### ISSUE TITLE
TcpKeepalive_InfiniteTimeSpan_TranslatesToUInt32MaxValue fails in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#45483]
```
Assert.Equal() Failure\r\nExpected: 4294967295\r\nActual:   0
   at System.Net.Http.WinHttpHandlerUnitTests.WinHttpHandlerTest.TcpKeepalive_InfiniteTimeSpan_TranslatesToUInt32MaxValue() in /_/src/libraries/System.Net.Http.WinHttpHandler/tests/UnitTests/WinHttpHandlerTest.cs:line 160
```

https://dnceng.visualstudio.com/public/_build/results?buildId=905703&view=ms.vss-test-web.build-test-results-tab&runId=28903150&resultId=135589&paneView=debug

Configuration: net6.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open

cc @dotnet/ncl

**Comment by ilyas1974** [comment]
https://github.com/dotnet/core-eng/issues/11511 was created for dnceng to address this issue.

**Comment by CarnaViire** [comment]
I guess this issue is a duplicate of https://github.com/dotnet/runtime/issues/45249

**Comment by ViktorHofer** [comment]
jep, closing as dupe of https://github.com/dotnet/runtime/issues/45249

**Comment by antonfirsov** [comment]
Yeah, will be fixed by #45249.

@ViktorHofer note that the job `Libraries Test Run release coreclr windows arm64 Release` seems to be executed for `refs/heads/master` only and not for PR-s. This prevented us to notice the bug in advance. Any recommendations to handle this in general/in future?

**Comment by antonfirsov** [comment]
& does this mean that no libraries tests are executed on ARM64 for individual PR-s?

**Comment by ViktorHofer** [comment]
> & does this mean that no libraries tests are executed on ARM64 for individual PR-s?

Right, as we don't have enough hardware to run them on every PR.

> This prevented us to notice the bug in advance. Any recommendations to handle this in general/in future?

We do have a vendor who is supposed to file test failures from rolling builds. cc @danmosemsft
