### ISSUE TITLE
Microbenchmark System.Threading.Tests.Perf_Interlocked.*_int is more than 100% slower on Wasm vs. desktop interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#45493]
Relavant microbenchmarks:
- System.Threading.Tests.Perf_Interlocked.Decrement_int (150% slower)
- System.Threading.Tests.Perf_Interlocked.CompareExchange_int (149% slower)
- System.Threading.Tests.Perf_Interlocked.Add_int (143% slower)
- System.Threading.Tests.Perf_Interlocked.Exchange_int (129% slower)
- System.Threading.Tests.Perf_Interlocked.Increment_int (122% slower)

[Repro Instructions for running benchmarks locally](https://gist.github.com/naricc/efdc186951a912507550509b21fb992b  )

[Results page when reported.](https://pvscmdupload.blob.core.windows.net/reports/08_26_2020/report_Daily_ca=x64_cb=refs-heads-master_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2020-08-26.html#Regressions  )

[Automated runs](https://pvscmdupload.blob.core.windows.net/index/index/index.html)

**Comment by SamMonoRT** [comment]
Based on recent runs : https://pvscmdupload.blob.core.windows.net/reports/06_09_2021/report_Daily_ca=x64_cb=refs-heads-main_co=Ubuntu1804_cr=dotnetruntime_cc=CompliationMode=wasm-RunKind=micro_Baseline_bc=CompliationMode=tiered-LLVM=false-MonoAOT=false-MonoInterpreter=true-RunKind=micro_mono_2021-06-09.html

The Perf_interlocked.*INT ones are all withing 15-37% slower. We will not on more targeted improvements here, and focus more on slower benchmarks from aot-wasm runs (coming soon). Closing this issue
