### ISSUE TITLE
Hitting Classic PDB format is not supported on CoreCLR. while using 6.0 version of the ILASM package

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#45492]
Darc updated the ilasm package version to 6.0 and we started hitting this 

```
EXEC : warning : Classic PDB format is not supported on CoreCLR. [C:\git\runtime3\src\libraries\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj]
```
is this expected  ? 

@dotnet/runtime-infrastructure

**Comment by safern** [comment]
Maybe something changed in arcade? I saw we hit this on the arcade update, right?

**Comment by ericstj** [comment]
Hmm, I'd expect us to be using portable PDBs (as opposed to classic) everywhere now.

**Comment by ViktorHofer** [comment]
I might be wrong but could this be connected to @ericstj's change where he stopped producing the old pdb format in libraries?

**Comment by ericstj** [comment]
I changed it the other way.  That warning indicates that the build is asking ILAsm to produce classic PDB which is not what we want.

**Comment by ericstj** [comment]
So here is where the ILSDK maps `DebugType` property to commandline args to ILAsm, perhaps that needs some work?
https://github.com/dotnet/runtime/blob/b9de3d04a0921199f24faee9d34a875044ecfe96/src/coreclr/src/.nuget/Microsoft.NET.Sdk.IL/targets/Microsoft.NET.Sdk.IL.targets#L131-L133

**Comment by akoeplinger** [comment]
See the discussion in https://github.com/dotnet/runtime/pull/45387#issuecomment-736916247

**Comment by radical** [comment]
Seeing this in some builds:
https://dev.azure.com/dnceng/public/_build/results?buildId=905221&view=results (PR #45451)
https://dev.azure.com/dnceng/public/_build/results?buildId=907315&view=results (PR #45387)

**Comment by safern** [comment]
@radical PR #45451 I don't think it hit this error, it actually hit a networking issue on the Browser leg and the other is a test failure. 

PR #45387 is the PR that is updating the version of `ILASM` causing this, so I'm going to remove `blocking-clean-ci` as this is an issue on the `ILASM` version that we're updating to, but not manifesting on all PRs, just the PR trying to update that version.

**Comment by jkotas** [comment]
This warning is not useful. I think we should get rid of this warning and always emit the portable PDBs.
