### ISSUE TITLE
dump command line to repro a crossgen2 failure with singlemethodname, singlemethodtype

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#45507]
Crossgen2 has `--singlemethodtypename, --singlemethodname` that allow to set just one method to compile. It is useful for debugging, but it is tricky to find the method type name for a failure that you see in CI/local run.
It would be nice to have an optional/default verbose message that says which methodtypename and methodname you need to set for a replay.

PTAL @davidwrighton, @trylek, @nattress

**Comment by MichalStrehovsky** [comment]
The Native AOT compiler has this - it's pretty simple:

https://github.com/dotnet/runtimelab/blob/d0a37893a67c125f9b0cd8671846ff7d867df241/src/coreclr/src/tools/aot/ILCompiler/Program.cs#L853-L867

**Comment by nattress** [comment]
We already have this in Crossgen2 when built in debug configuration. We can define `DEBUG` for the Checked flavors of CG2 so we see this info in the CI since we don't test runtime with actual Debug legs.

**Comment by MichalStrehovsky** [comment]
>  We can define DEBUG for the Checked flavors of CG2 so we see this info in the CI since we don't test runtime with actual Debug legs.

That should be the case since November 27th: #43017

**Comment by trylek** [comment]
@sandreenko, have you been able to verify if the current state of affairs fixes your issue i.o.w. whether you now see checked Crossgen2 produce sufficient repro information with regard to --singleXXX parameters? Please let me know if this item can be closed and / or whether you have suggestions for further improvement around the CG2 command-line syntax, documentation and such.

**Comment by sandreenko** [comment]
@trylek yes, that works great now, used it yesterday, thanks!

**Comment by trylek** [comment]
Great, thanks for confirming that we can close this item for now.
