### ISSUE TITLE
Consider skipping generating GCInfo for uninterruptible methods.

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#45508]
During the investigation of https://github.com/dotnet/runtime/issues/45287, I figured there are some methods that are neither fully interruptible nor having any safe points. Such a method will not be interrupted for GC and therefore there should be no need to provide GCInfo for it. We might be able to save some space if we do not generate GCInfo for them.

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
Not sure if this is feasible. Seems likely that the GCInfo conveys other information that the runtime depends on.

**Comment by BruceForstall** [comment]
Besides what @AndyAyersMS says here, it what case is a method neither fully interruptible nor has any safe points? I thought we had to be one or the other. Maybe a function without a call or loop?

**Comment by JulieLeeMSFT** [comment]
> it what case is a method neither fully interruptible nor has any safe points? I thought we had to be one or the other. Maybe a function without a call or loop?

@cshung, could you please answer this question?

**Comment by AndyAyersMS** [comment]
@cshung do you have an idea how much space the GC info for the methods above requires?

There is other info conveyed in the gc info aside from the safe points and slots. This extra info includes things that are accessed during stackwalks or during EH, like the offsets of the generic context and the stack security cookie.

We'd need to verify that none of the other gc info fields the jit produces can ever be touched by the runtime. I'm not entirely sure how to do that.

Given the relatively small number of methods above, and the fact that w/o any slot reporting the overall gc info size for a method is likely pretty small, this doesn't seem to be an opportunity worth pursuing.

**Comment by AndyAyersMS** [comment]
@cshung any objection to closing this?

**Comment by cshung** [comment]
> @cshung any objection to closing this?

Nope, let's close this.
