### ISSUE TITLE
Installer test failures in PR build do not fail the build

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#45515]
If one of the tests fail in the installer build job, it is treated as a warning instead of failing the build. The build is marked partially succeeded and the checks in the PR show up as successful.

Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=906193&view=results

Possibly related to the `continueOnError` changes in #45178?

cc @dotnet/runtime-infrastructure @agocke @vitek-karas

**Comment by hoyosjs** [comment]
@elinor-fung thanks, @safern is in the process of fixing it and it was indeed that change (yml string vs bool shennanigans).
