### ISSUE TITLE
FrameworkHiveSelection_GlobalHiveWithBetterMatch failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#45510]
https://dev.azure.com/dnceng/public/_build/results?buildId=906108&view=ms.vss-test-web.build-test-results-tab&runId=28912544&resultId=100177&paneView=debug

Configuration: Installer-coreclr-windows_x86-Debug

```
Expected command to pass but it did not."\r\nFile Name: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\dotnet.exe\r\nArguments: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll\r\nExit Code: -532462766\r\nStdOut:\r\n\r\nStdErr:\r\nTracing enabled @ Wed Dec  2 19:54:41 2020 GMT\r\n--- Invoked dotnet [version: 6.0.0-ci, commit hash: 63247336f41751582d12423fe6852bd73dd0f09f] main = {\r\nF:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\dotnet.exe\r\nF:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll\r\n}\r\nReading fx resolver directory=[F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\host\fxr]\r\nConsidering fxr version=[6.0.0-ci]...\r\nDetected latest fxr version=[F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\host\fxr\6.0.0-ci]...\r\nResolved fxr [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\host\fxr\6.0.0-ci\hostfxr.dll]...\r\nLoaded library from F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\host\fxr\6.0.0-ci\hostfxr.dll\r\nInvoking fx resolver [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\host\fxr\6.0.0-ci\hostfxr.dll] hostfxr_main_startupinfo\r\nHost path: [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\dotnet.exe]\r\nDotnet path: [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\]\r\nApp path: [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\dotnet.dll]\r\nTracing enabled @ Wed Dec  2 19:54:41 2020 GMT\r\n--- Invoked hostfxr_main_startupinfo [commit hash: 63247336f41751582d12423fe6852bd73dd0f09f]\r\nChecking if CoreCLR path exists=[F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\coreclr.dll]\r\n--- Executing in muxer mode...\r\nUsing the provided arguments to determine the application to execute.\r\nUsing dotnet root path [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive\]\r\nApp runtimeconfig.json from [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.dll]\r\nRuntime config is cfg=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json dev=F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.dev.json\r\nAttempting to read runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json\r\nAttempting to read dev runtime config: F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.dev.json\r\nRuntime config [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\FrameworkReferenceApp\FrameworkReferenceApp.runtimeconfig.json] is valid=[1]\r\n--- The specified framework 'Microsoft.NETCore.App', version '5.0.0', apply_patches=1, version_compatibility_range=minor is compatible with the previously referenced version '5.0.0'.\r\n--- Resolving FX directory, name 'Microsoft.NETCore.App' version '5.0.0'\r\nDOTNET_MULTILEVEL_LOOKUP is set to 1\r\nMultilevel lookup is true\r\nSearching FX directory in [F:\workspace\_work\1\s\artifacts\tests\Debug\ha\frameworkResolution\0\MainHive]\r\nAttempting FX roll forward star
```

Stacktrace:
```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.Pass() in /_/src/installer/tests/TestUtils/Assertions/CommandResultAssertions.cs:line 30
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.FrameworkResolutionCommandResultExtensions.ShouldHaveResolvedFramework(CommandResult result, String resolvedFrameworkName, String resolvedFrameworkVersion) in /_/src/installer/tests/HostActivation.Tests/FrameworkResolution/FrameworkResolutionCommandResultExtensions.cs:line 18
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.MultipleHives.FrameworkHiveSelection_GlobalHiveWithBetterMatch() in /_/src/installer/tests/HostActivation.Tests/FrameworkResolution/MultipleHives.cs:line 32
```

cc @vitek-karas (?)

Runfo Tracking Issue: [frameworkhiveselection_globalhivewithbettermatch](https://runfo.azurewebsites.net/tracking/issue/108)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[915520](https://dev.azure.com/dnceng/public/_build/results?buildId=915520)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45887](https://github.com/dotnet/runtime/pull/45887)|Installer-coreclr-Windows_NT_x86-Debug|
|[915520](https://dev.azure.com/dnceng/public/_build/results?buildId=915520)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45887](https://github.com/dotnet/runtime/pull/45887)|Installer-coreclr-Windows_NT_x64-Release|
|[915185](https://dev.azure.com/dnceng/public/_build/results?buildId=915185)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45876](https://github.com/dotnet/runtime/pull/45876)|Installer-coreclr-Windows_NT_x86-Debug|
|[915185](https://dev.azure.com/dnceng/public/_build/results?buildId=915185)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45876](https://github.com/dotnet/runtime/pull/45876)|Installer-coreclr-Windows_NT_x64-Release|
|[914933](https://dev.azure.com/dnceng/public/_build/results?buildId=914933)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45873](https://github.com/dotnet/runtime/pull/45873)|Installer-coreclr-Windows_NT_x86-Debug|
|[914933](https://dev.azure.com/dnceng/public/_build/results?buildId=914933)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45873](https://github.com/dotnet/runtime/pull/45873)|Installer-coreclr-Windows_NT_x64-Release|
|[914667](https://dev.azure.com/dnceng/public/_build/results?buildId=914667)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x86-Release|
|[914667](https://dev.azure.com/dnceng/public/_build/results?buildId=914667)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x64-Release|
|[914649](https://dev.azure.com/dnceng/public/_build/results?buildId=914649)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45809](https://github.com/dotnet/runtime/pull/45809)|Installer-coreclr-Windows_NT_x86-Debug|
|[914649](https://dev.azure.com/dnceng/public/_build/results?buildId=914649)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45809](https://github.com/dotnet/runtime/pull/45809)|Installer-coreclr-Windows_NT_x64-Release|
|[913489](https://dev.azure.com/dnceng/public/_build/results?buildId=913489)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x86-Debug|
|[913489](https://dev.azure.com/dnceng/public/_build/results?buildId=913489)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x64-Release|
|[913448](https://dev.azure.com/dnceng/public/_build/results?buildId=913448)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45809](https://github.com/dotnet/runtime/pull/45809)|Installer-coreclr-Windows_NT_x86-Debug|
|[913448](https://dev.azure.com/dnceng/public/_build/results?buildId=913448)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45809](https://github.com/dotnet/runtime/pull/45809)|Installer-coreclr-Windows_NT_x64-Release|
|[913190](https://dev.azure.com/dnceng/public/_build/results?buildId=913190)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x86-Release|
|[913190](https://dev.azure.com/dnceng/public/_build/results?buildId=913190)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x64-Release|
|[913175](https://dev.azure.com/dnceng/public/_build/results?buildId=913175)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x86-Debug|
|[913175](https://dev.azure.com/dnceng/public/_build/results?buildId=913175)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x64-Release|
|[913175](https://dev.azure.com/dnceng/public/_build/results?buildId=913175)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x86-Debug|
|[913175](https://dev.azure.com/dnceng/public/_build/results?buildId=913175)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45799](https://github.com/dotnet/runtime/pull/45799)|Installer-coreclr-Windows_NT_x64-Release|
|[913046](https://dev.azure.com/dnceng/public/_build/results?buildId=913046)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x86-Release|
|[913046](https://dev.azure.com/dnceng/public/_build/results?buildId=913046)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x64-Release|
|[912808](https://dev.azure.com/dnceng/public/_build/results?buildId=912808)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x86-Release|
|[912808](https://dev.azure.com/dnceng/public/_build/results?buildId=912808)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x64-Release|
|[912279](https://dev.azure.com/dnceng/public/_build/results?buildId=912279)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45757](https://github.com/dotnet/runtime/pull/45757)|Installer-coreclr-Windows_NT_x86-Debug|
|[912279](https://dev.azure.com/dnceng/public/_build/results?buildId=912279)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45757](https://github.com/dotnet/runtime/pull/45757)|Installer-coreclr-Windows_NT_x64-Release|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x86-Debug|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x64-Release|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x86-Debug|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x64-Release|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x86-Debug|
|[911641](https://dev.azure.com/dnceng/public/_build/results?buildId=911641)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45729](https://github.com/dotnet/runtime/pull/45729)|Installer-coreclr-Windows_NT_x64-Release|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x86-Debug|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x64-Release|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x86-Debug|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x64-Release|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x86-Debug|
|[909381](https://dev.azure.com/dnceng/public/_build/results?buildId=909381)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45622](https://github.com/dotnet/runtime/pull/45622)|Installer-coreclr-Windows_NT_x64-Release|
|[909033](https://dev.azure.com/dnceng/public/_build/results?buildId=909033)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42886](https://github.com/dotnet/runtime/pull/42886)|Installer-coreclr-Windows_NT_x86-Debug|
|[909033](https://dev.azure.com/dnceng/public/_build/results?buildId=909033)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42886](https://github.com/dotnet/runtime/pull/42886)|Installer-coreclr-Windows_NT_x64-Release|
|[907820](https://dev.azure.com/dnceng/public/_build/results?buildId=907820)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x86-Release|
|[907820](https://dev.azure.com/dnceng/public/_build/results?buildId=907820)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-Windows_NT_x64-Release|
|[906440](https://dev.azure.com/dnceng/public/_build/results?buildId=906440)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45506](https://github.com/dotnet/runtime/pull/45506)|Installer-coreclr-windows_x86-Debug|
|[906440](https://dev.azure.com/dnceng/public/_build/results?buildId=906440)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45506](https://github.com/dotnet/runtime/pull/45506)|Installer-coreclr-windows_x64-Release|
|[906409](https://dev.azure.com/dnceng/public/_build/results?buildId=906409)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Installer-coreclr-windows_x86-Release|
|[906399](https://dev.azure.com/dnceng/public/_build/results?buildId=906399)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45505](https://github.com/dotnet/runtime/pull/45505)|Installer-coreclr-windows_x86-Debug|
|[906399](https://dev.azure.com/dnceng/public/_build/results?buildId=906399)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45505](https://github.com/dotnet/runtime/pull/45505)|Installer-coreclr-windows_x64-Release|
|[906374](https://dev.azure.com/dnceng/public/_build/results?buildId=906374)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45504](https://github.com/dotnet/runtime/pull/45504)|Installer-coreclr-windows_x86-Debug|
|[906370](https://dev.azure.com/dnceng/public/_build/results?buildId=906370)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45502](https://github.com/dotnet/runtime/pull/45502)|Installer-coreclr-windows_x86-Debug|
|[906336](https://dev.azure.com/dnceng/public/_build/results?buildId=906336)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44751](https://github.com/dotnet/runtime/pull/44751)|Installer-coreclr-windows_x86-Debug|
|[906327](https://dev.azure.com/dnceng/public/_build/results?buildId=906327)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45275](https://github.com/dotnet/runtime/pull/45275)|Installer-coreclr-windows_x86-Debug|
|[906291](https://dev.azure.com/dnceng/public/_build/results?buildId=906291)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45498](https://github.com/dotnet/runtime/pull/45498)|Installer-coreclr-windows_x86-Debug|
|[906216](https://dev.azure.com/dnceng/public/_build/results?buildId=906216)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45392](https://github.com/dotnet/runtime/pull/45392)|Installer-coreclr-windows_x64-Release|
|[906206](https://dev.azure.com/dnceng/public/_build/results?buildId=906206)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45116](https://github.com/dotnet/runtime/pull/45116)|Installer-coreclr-windows_x86-Debug|
|[906206](https://dev.azure.com/dnceng/public/_build/results?buildId=906206)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45116](https://github.com/dotnet/runtime/pull/45116)|Installer-coreclr-windows_x64-Release|
|[906193](https://dev.azure.com/dnceng/public/_build/results?buildId=906193)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45495](https://github.com/dotnet/runtime/pull/45495)|Installer-coreclr-windows_x86-Debug|
|[906188](https://dev.azure.com/dnceng/public/_build/results?buildId=906188)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45494](https://github.com/dotnet/runtime/pull/45494)|Installer-coreclr-windows_x86-Debug|
|[906173](https://dev.azure.com/dnceng/public/_build/results?buildId=906173)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44505](https://github.com/dotnet/runtime/pull/44505)|Installer-coreclr-windows_x86-Debug|
|[906154](https://dev.azure.com/dnceng/public/_build/results?buildId=906154)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 44932](https://github.com/dotnet/runtime/pull/44932)|Installer-coreclr-windows_x86-Debug|
|[906152](https://dev.azure.com/dnceng/public/_build/results?buildId=906152)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45490](https://github.com/dotnet/runtime/pull/45490)|Installer-coreclr-windows_x64-Release|
|[906152](https://dev.azure.com/dnceng/public/_build/results?buildId=906152)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45490](https://github.com/dotnet/runtime/pull/45490)|Installer-coreclr-windows_x86-Debug|
|[906146](https://dev.azure.com/dnceng/public/_build/results?buildId=906146)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45134](https://github.com/dotnet/runtime/pull/45134)|Installer-coreclr-windows_x86-Debug|
|[906146](https://dev.azure.com/dnceng/public/_build/results?buildId=906146)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45134](https://github.com/dotnet/runtime/pull/45134)|Installer-coreclr-windows_x64-Release|
|[906133](https://dev.azure.com/dnceng/public/_build/results?buildId=906133)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 39294](https://github.com/dotnet/runtime/pull/39294)|Installer-coreclr-windows_x86-Debug|
|[906133](https://dev.azure.com/dnceng/public/_build/results?buildId=906133)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 39294](https://github.com/dotnet/runtime/pull/39294)|Installer-coreclr-windows_x64-Release|
|[906108](https://dev.azure.com/dnceng/public/_build/results?buildId=906108)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45480](https://github.com/dotnet/runtime/pull/45480)|Installer-coreclr-windows_x86-Debug|
|[906104](https://dev.azure.com/dnceng/public/_build/results?buildId=906104)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45480](https://github.com/dotnet/runtime/pull/45480)|Installer-coreclr-windows_x64-Release|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|5|16|35|

**Comment by ViktorHofer** [comment]
@agocke the test started to fail just recently, so presumably a regression? this is killing our pass rate, should we disable the test meanwhile?

**Comment by elinor-fung** [comment]
This should be fixed by #45500

**Comment by ViktorHofer** [comment]
Closing and will reopen if I see other hits. Thanks

**Comment by janvorli** [comment]
It has failed again today on my PR for Windows x86 and x64:
https://dev.azure.com/dnceng/public/_build/results?buildId=914933&view=ms.vss-test-web.build-test-results-tab&runId=29117690&resultId=100238&paneView=history

**Comment by janvorli** [comment]
Ah, my PR is on the release/5.0 branch and the port of the fix obviously isn't there yet. So please disregard the comment above.
