### ISSUE TITLE
[tvOS] System.Net.Security depends on non-existant System.Net.Security.Native

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#45535]
There's no GSS support on tvOS and hence System.Net.Security.Native is not built on the platform (
https://github.com/dotnet/runtime/blob/3c39a5d3b8310d9adcb906718cf985d3e40122da/src/libraries/Native/Unix/CMakeLists.txt#L224). The managed code still references the library though which causes problem when trying to link on the platform. I assume it should throw PNSE instead.

**Comment by steveisok** [comment]
Yes, we'll need to throw PNSE.

**Comment by MaximLipnin** [comment]
Am I right that the whole [Interop.NetSecurityNative.cs](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Common/src/Interop/Unix/System.Net.Security.Native/Interop.NetSecurityNative.cs) should throw PNSE?

**Comment by filipnavara** [comment]
It would be the whole directory containing that file. However, it probably makes more sense to avoid using that code altogether and just make a version of `NegotiateStreamPal` (and `ContextFlagsAdapterPal` and `Capability.Security.Unix.cs`) that throws PNSE early on.

**Comment by MaximLipnin** [comment]
It's addressed in #51861.
