### ISSUE TITLE
[Question] Microsoft.Extensions.Configuration F# type handling

### ISSUE THREAD

**Issue by En3Tho** [dotnet/runtime#45539]
I have a config type which has a specifig F# option type. I'm using out of the box json configuration provider. The problem is that this option type doesn't have a parameterless constructor and it seems like there is no way to add any custom options to JsonConfigurationProvider or Configuration infrastructure.
The way I see is that they should behave more or less the same as the standard JsonSerialization/Deserialization. You get a provider, configure serializer, DI runtume asks for a type at certain json path, serializer then builds the type.
I'm I totally wrong here? Is there any way to add custom behaviour for specific types?

**Comment by maryamariyan** [comment]
@En3Tho do you have a small repro code to help illustrate the issue here?
