### ISSUE TITLE
FileSystemWatcher running in dockerized application does not report changes in docker volumes

### ISSUE THREAD

**Issue by misterbit-pro** [dotnet/runtime#45533]
Hello,

I have tried my best to find some help related to my issue on the internet, but neither works for me or is not supported on linux.

The problem is I have ah .net5 console application running in a docker container that conatins a FileSystemWachter, wich watches a dir, wich is mounted using docker volumes to a dir on my debian server machine. When I am adding a file to the dir on the host machine, its also added to mounted point in the conatiner, but .net does not raise any events. When i create a file in the container enviroment, the event fires without any problems.

Is this a bug or what can I do to get the FileWatcher working?

I'm using the offical mcr.microsoft.com/dotnet/runtime:5.0 as base image.

Thanks for looking into my issue

**Comment by carlossanlop** [comment]
I suspect it's expected that no OS notifications are triggered in the docker container when a file is added from the server host. Seems to happen even with other tools, not just with FileSystemWatcher ([example](https://stackoverflow.com/questions/56247919/file-system-events-not-triggered-in-docker-container-when-files-in-mounted-volum)). It could also be a bug in Docker.

**Comment by misterbit-pro** [comment]
I think I got it working with using the user command when starting up the container. Before that I was running the container as root. Now it works
