### ISSUE TITLE
Installer Build failed with fatal error C1007 on windows arm64

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#45532]
```
LINK : fatal error C1007: unrecognized flag '-NoRTTI' in 'p2' [F:\workspace\_work\1\s\artifacts\obj\win-arm64.Debug\corehost\cli\apphost\static\singlefilehost.vcxproj]
  LINK : fatal error LNK1257: code generation failed [F:\workspace\_work\1\s\artifacts\obj\win-arm64.Debug\corehost\cli\apphost\static\singlefilehost.vcxproj]
    Building Custom Rule F:/workspace/_work/1/s/src/installer/corehost/cli/test_fx_ver/CMakeLists.txt
    test_fx_ver.cpp
    trace.cpp
    utils.cpp
    fx_ver.cpp
    pal.windows.cpp
    longfile.windows.cpp
    test_fx_ver.vcxproj -> F:\workspace\_work\1\s\artifacts\obj\win-arm64.Debug\corehost\cli\test_fx_ver\Debug\test_fx_ver.exe
  Failed to generate native component build project!
F:\workspace\_work\1\s\src\installer\corehost\corehost.proj(107,5): error MSB3073: The command "F:\workspace\_work\1\s\src\installer\corehost\build.cmd Debug arm64 apphostver 6.0.0-ci hostver 6.0.0-ci fxrver 6.0.0-ci policyver 6.0.0-ci commit a986e2633bd2af462e174249df0c305dfc60eb1f rid win-arm64 portable incremental-native-build rootdir F:\workspace\_work\1\s\ coreclrartifacts F:\workspace\_work\1\s\artifacts\transport\coreclr\ nativelibsartifacts F:\workspace\_work\1\s\artifacts\/bin/native/net6.0-windows-Release-arm64 runtimeflavor coreclr runtimeconfiguration release" exited with code 1.
##[error]src\installer\corehost\corehost.proj(107,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "F:\workspace\_work\1\s\src\installer\corehost\build.cmd Debug arm64 apphostver 6.0.0-ci hostver 6.0.0-ci fxrver 6.0.0-ci policyver 6.0.0-ci commit a986e2633bd2af462e174249df0c305dfc60eb1f rid win-arm64 portable incremental-native-build rootdir F:\workspace\_work\1\s\ coreclrartifacts F:\workspace\_work\1\s\artifacts\transport\coreclr\ nativelibsartifacts F:\workspace\_work\1\s\artifacts\/bin/native/net6.0-windows-Release-arm64 runtimeflavor coreclr runtimeconfiguration release" exited with code 1.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=906703&view=logs&j=f5132c4d-221c-5bab-9451-fb5746c80054&t=47a75d49-32a8-5499-0783-e9566010a717

cc: @agocke

**Comment by agocke** [comment]
@mateoatr Could you take a look at this?

**Comment by elinor-fung** [comment]
Hit this failure on arm as well: https://dev.azure.com/dnceng/public/_build/results?buildId=906291&view=logs&j=09f284fa-cf28-5239-7389-ddb0e9bf3d9f&t=24127001-2e3b-5c7c-4511-3b857ce69995

Maybe related to the version of VS installed? The arm64 failure in the description and the arm failure I hit are both on 16.7.3. The [arm build](https://dev.azure.com/dnceng/public/_build/results?buildId=906703&view=logs&j=09f284fa-cf28-5239-7389-ddb0e9bf3d9f&t=24127001-2e3b-5c7c-4511-3b857ce69995) and the [arm64 build](https://dev.azure.com/dnceng/public/_build/results?buildId=906291&view=logs&j=f5132c4d-221c-5bab-9451-fb5746c80054&t=47a75d49-32a8-5499-0783-e9566010a717) from those runs were on 16.8.0 and succeeded.

**Comment by safern** [comment]
Hmm, I wonder why our machines would have a different version of VS. I would expect all machines on the build pool to have the same version. @ilyas1974 could you help look at why is that?

**Comment by ilyas1974** [comment]
Taking at look at what happened.

**Comment by ilyas1974** [comment]
It appears that the system this build was run on was provisioned before the rollout of 16.8 and did not get removed from the queue until later in the day. We have spun up an issue - https://github.com/dotnet/core-eng/issues/11573 - to address this type of behavior in the future.

**Comment by riarenas** [comment]
I haven't seen this since then and the linked issue seems like a good follow-up for this situation.. We can reopen if it happens again.
