### ISSUE TITLE
[Wasm][AOT] error when compiling: Assertion runtime/src/mono/mono/mini/aot-compiler.c:3563

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#45548]
### Description

When building an application with profiled AOT, the following compiler error appears:

```
Assertion runtime/src/mono/mono/mini/aot-compiler.c:3563
```

[Location](https://github.com/dotnet/runtime/blob/c6e5ef17d1e35800d7090872859cb408fe0f6e61/src/mono/mono/mini/aot-compiler.c#L3563)

Repro yet unknown.

### Configuration

CommitID: c6e5ef17d1e35800d7090872859cb408fe0f6e61

### Regression?

No

**Comment by vargaz** [comment]
No need for a repro.
