### ISSUE TITLE
Unable to load shared library 'System.Net.Security.Native' or one of its dependencies. .net5 after adding RSA

### ISSUE THREAD

**Issue by murugaratham** [dotnet/runtime#45543]
### Description

We have a custom base dotnet image based off alpine 3.12.1 and recently added some crypto capabilities

### base Dockerfile
```yml
FROM alpine:3.12.1

#install libs, reference: https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine
RUN apk add --no-cache \
    zlib libstdc++ libgcc \
    icu-libs krb5-libs libintl \
    libssl1.1 icu bash \
    krb5 openrc busybox-initscripts curl ca-certificates

...
ENV ASPNETCORE_ENVIRONMENT=docker
```
### Project dockerfile
```
COPY . .
RUN dotnet restore -v=m -r linux-musl-x64 "redacted.sln"

COPY . .
WORKDIR /redacted.Api
RUN dotnet publish -v=m -c Release -r linux-musl-x64 -o /app --nologo --no-restore --self-contained true -p:PublishSingleFile=true

```

```
services.AddSingleton<RsaSecurityKey>(provider => {
    RSA rsa = RSA.Create();
    rsa.ImportSubjectPublicKeyInfo(source: Convert.FromBase64String(jwtOptions.PublicKey), bytesRead: out int _);
    return new RsaSecurityKey(rsa);
});
```

### Configuration

* Which version of .NET is the code running on? .net 5
* What OS and version, and what distro if applicable? alpine3.12.1 (docker) on RHEL
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Other information
```
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

ClientConnectionId:9a017d19-2b8a-4deb-b434-5a3bfae4c47f

Microsoft.Data.SqlClient.SqlException (0x80131904): **Unable to load shared library 'System.Net.Security.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libSystem.Net.Security.Native: No such file or directory**
```

**Comment by vcsjones** [comment]
To troubleshoot a bit, does the issue still reproduce if you do not publish as a single file and self contained? i.e. remove `--self-contained true -p:PublishSingleFile=true` from your build command?

**Comment by murugaratham** [comment]
i am able to run successfully by just setting to --self-contained true

**Comment by vcsjones** [comment]
Seems then that the issue is related to `-p:PublishSingleFile=true`.

@vitek-karas might you know how to best proceed?

**Comment by jkotas** [comment]
`Microsoft.Data.SqlClient` pinvokes into `System.Net.Security.Native`. `System.Net.Security.Native` has different shape in single file.

`System.Net.Security.Native` is internal implementation detail that `Microsoft.Data.SqlClient` is not supposed to depend on.  

This is a problem to fix in `Microsoft.Data.SqlClient`. The PInvokes into `System.Net.Security.Native` from `Microsoft.Data.SqlClient` needs to be cleaned up and replaced with public APIs.

**Comment by murugaratham** [comment]
Only other change i did was added healthchecks package, [HealthChecks.SqlServer](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/25129ba4303e7cc610c11437316de850e3a50d6a/src/HealthChecks.SqlServer/SqlServerHealthCheck.cs#L1).

**Comment by vcsjones** [comment]
> Only other change i did was added healthchecks package, HealthChecks.SqlServer.

That makes more sense given the error that you saw. I don't believe the use of `RSA` was the cause of the issue you saw. Rather, when you included that package, it has a dependency on Microsoft.Data.SqlClient, and that package as Jan pointed out appears to not support single file.

The code using `RSA.Create` and importing a SPKI should work.

**Comment by murugaratham** [comment]
So will `Microsoft.Data.SqlClient` be patched to support single file publish?

**Comment by cheenamalhotra** [comment]
https://github.com/dotnet/SqlClient/issues/303 is tracking activity to remove dependency on internal shims.

**Comment by Paul-Schroeder** [comment]
I am not sure exactly how I landed on this page, but the answer here helped me resolve an issue that cost me pretty much a full development day. I'll post my info in case it helps someone else searching for answers.  I am developing a Windows service application using .NET Core 5.0 and a BackgroundService / IHostedService class. The error I was getting seemed to stem from SeriLog logging with a Serilog.Sinks.MSSqlServer sink, but everything worked during development / local testing.

The error I received in the error log was simply:

> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'logger')

For a long time, I thought the issue was a configuration issue with SeriLog, but it turns out the problem was my use of the "PublishSingleFile=true" option combined with the issue in this post.

This **does not** work when combined with SeriLog's MSSqlServer sink:
`dotnet publish -r win-x64 -c Release -o c:\Publish\win-service\<projectdir> /p:PublishSingleFile=true`

This **DOES** work:
`dotnet publish -r win-x64 -c Release -o c:\Publish\win-service\<projectdir> /p:SelfContained=True /p:PublishProtocol=FileSystem`

I believe the reason it seems like a SeriLog issue is because that is the first time the application attempts to use SQL Server as it logs a startup message. Hope this helps someone else save some time!

**Comment by cheenamalhotra** [comment]
Closing as this is being tracked in dotnet/SqlClient#303
