### ISSUE TITLE
ConcurrentQueue<T>.Peek()  causes preservedForObservation = true _FOREVER_

### ISSUE THREAD

**Issue by rclabo** [dotnet/runtime#45546]
### Description

In my use of ConcurrentQueue I need to call Peek before ever TryDequeue.  I noticed that my website was experiencing memory leaks due to this use.  After studying the source code at https://github.com/dotnet/coreclr/blob/v3.1.10/src/System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueue.cs  and https://github.com/dotnet/coreclr/blob/v3.1.10/src/System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueueSegment.cs  it seems fairly clear why the memory leak  is happening.  

Calling `ConcurrentQueue<T>.TryPeek(out result)` in turn calls `ConcurrentQueueSegment<T>.TryPeek(out result, resultUsed:true)`. This method then sets an internal flag `_preservedForObservation = true` which preserves the information in the segment to prevent a torn read.  This all makes sense.  However, as best I can tell, `_preservedForObservation` is never set to false for this segment ever again.  In fact,  `_preservedForObservation` is  a private internal bool and there is no code anywhere in the `ConcurrentQueueSegment` class that ever sets `_preservedForObservation` to false other then the fact that it starts off false based on the default initialization.  So once set to true it remains true for this segment _forever_ as best I can tell.

It's would seem that once the Peek method has finished executing `_preservedForObservation`  should get set back to false.  Or at least at some point in the future it should get set back to false.

`ConcurrentQueue<T>.TryDequeue(out result)` calls `ConcurrentQueueSegment<T>.TryDequeue(out result)` which does not release it's internal reference to the Dequeued object if `_preservedForObservation` is true.  

So the net net of this is that if TryPeek is ever called on ConcurrentQueue to peek at a queued object, that object will continue being referenced by ConcurrentQueue later **even after it's "Dequeued"**.  Hence the memory leak.  

It seems that the fix would at some point set `_preservedForObservation` to false for the internal segment holding that object. 

### Configuration

Asp.Net 5, Windows 10 x64

### Regression?

I suspect this issue has existed for sometime and is not new to .Net 5.

**Comment by Clockwork-Muse** [comment]
Outside of fixing this, for my own edification, what's the reason for calling `TryPeek`?  Given the consideration for race conditions, I've always just dequeued stuff (not even bothering with `IsEmpty` either).

**Comment by benaadams** [comment]
Frozen segments get thrown away once everything is dequeued from them? (and nothing can be enqueued to them)
https://github.com/dotnet/coreclr/blob/d989459717cbce34262060c4b8b949185033e379/src/System.Private.CoreLib/shared/System/Collections/Concurrent/ConcurrentQueue.cs#L720-L728

**Comment by rclabo** [comment]
@Clockwork-Muse In this particular case, I'm queuing up work that needs to be done and the thread that is responsible for processing the queue needs to peek on the next item in the queue and do some other system checks to see it's now able to process that item.  If not it will wait awhile and repeat.  Once it determines that it is now able to process the peeked item (based on other system conditions) it will process it and dequeue it.  In this use case there are multiple threads queueing items but only one thread responsible for processing/dequeuing items.

@benaadams That explains why I didn't see any code setting `_preservedForObservation` to false but it's still not a great situation.  So for example.  The initial CurrentQueueSegment can hold 32 queued items.  If an item is queued and peeked and then dequeued, the `ConcurrentQueue` by way of the `ConcurrentQueueSegment` will hang onto a referenced to that dequeued item until 31 more items are queued and dequeued.  And this picture gets worse once a new `CurrentQueueSegment` is added since it's going to be twice as large, and the next segment will be twice as large as that.  If the objects being queued are large this makes for a very unfortunate situation where references to these dequeued objects are held much longer than one would expect.

**Comment by stephentoub** [comment]
This is by design, with ConcurrentQueue optimizing for enqueue and dequeue while also supporting concurrent peeking / enumerating albeit with an impact on allocation.  Enqueues into the same segment need to avoid overwriting a cell that may be needed for an in-progress peek or enumeration, and thus once such a concurrent read-but-don't-remove is issued against a segment, that segment is frozen to prevent such erroneous overwrites.  If you have a better solution that doesn't negatively impact the generally more important case of enqueue/dequeue performance, please share, but it's not a bug or regression.

**Comment by Clockwork-Muse** [comment]
> I'm queuing up work that needs to be done and the thread that is responsible for processing the queue needs to peek on the next item in the queue and do some other system checks to see it's now able to process that item.

... check the status of the system before pulling things off the queue?  Or check if a member variable is still set before pulling off the next one?

**Comment by rclabo** [comment]
@Clockwork-Muse In my case the code responsible for processing a queued item needs to do a peek to learn some info about the item, then checks other information available in the system to see if all the info needed to process the item is available yet.  If it is it will process it and dequeue it, if the other info is not available yet it will leave the item in the queue and later go through the evaluation process again, doing this until it has what it needs to fully process the item and dequeue it.

@stephentoub I wasn't meaning to be critical.  I respect your knowledge and authority on this highly complicated subject matter.  It may well be that there is no better way to provide Peek ability into the queue while supporting non blocking concurrent enqueues and dequeues.  Walking through the code makes it clear that concurrent queue support is a hard problem, and it brings back memories for me of late nights years ago doing my Data Structures and Algorithms homework in college.  There is nothing easy about concurrency.  I did come up with a work around today which is to wrap my large class in a class of one property that holds the item I need to queue.  This way, once I peek and eventually dequeue the wrapped item, I can then null out it's item property and that will immediately release the memory of that larger object.  So the slow release of the references held by the queue in Peek scenarios are only tie up  tiny object instead of the big ones.  I think this is a sufficient work around for my use case.  I wanted to file this issue because the need for doing this felt like it was caused by an underlying bug in the class but I now see that this is by design and a result of dealing with the challenges of concurrency.  And while in my use there is only one thread that ever peeks or dequeues the class must deal with the harder case of many threads performing those operations.  So feel free to close this report and know that I'm grateful for the hard work you put into the class and that you make the source code publicly available which allowed me to devise my work around.

**Comment by stephentoub** [comment]
No problem at all.  I was just pointing out that this was an explicit design tradeoff, to optimize one very common operation at the expense of another much less common (in general).  If someone has a good idea for how to have our cake and eat it,  too, great.

**Comment by benaadams** [comment]
If dequeue is slow(ish); as you have to peek and check conditions on whether it can be processed first; that suggests enqueue is slow(ish); otherwise you'll end up with a large backlog?

If so then you could use a `lock` over a regular `Queue<T>` for `Enqueue`, `TryPeek` and `TryDequeue`; then you wouldn't have the secondary issues with frozen segments?

**Comment by Clockwork-Muse** [comment]
Yeah, I'm with @benaadams here, you're setting yourself up for a large backlog.

You haven't given us enough to go on, but there's a few possibilities:
 - If the extra info is part of a process also started by the same producer thread, have it hold off on submitting to the queue until it verifies that the extra info is (or should be) done.
 - If the extra info comes from multiple processes, or may involve "constant" data, pull the item off, and check it.  If it's done, great.  Otherwise, stick it in a collection for processing the next time.

**Comment by rclabo** [comment]
@benaadams I've been pondering that as well.  I've wondered if that might be the better route but there is something sexy about knowing that I can always enqueue without needing to lock.  :-)  Ultimately I need to run some performance testing on my use case and see and I may switch to using lock with a Queue<T>.

@Clockwork-Muse In my use case periodically there is a 2-3 second delay from the time the item is enqueued to the time I have the system info I need to process that queued items.  Often I can process the item immediately after it's queued because additional info is not needed.  So likely worst case is that the queue needs act as a 3 second buffer of work items.  It's unclear how many items that could be but for the foreseeable future it's probably well under 3000 items for a 3 second period. And in my case the most important thing is that I can quickly enqueue work items as they arrive.  

I think I have enough understanding of the possibilities now to push forward with one or more solutions.
