### ISSUE TITLE
The certificate data cannot be read with the provided password, the password may be incorrect with .NET 5.0

### ISSUE THREAD

**Issue by odinnou** [dotnet/runtime#45569]
Hello, I am trying to migrate my application which integrates "Identity Server 4" from .NET Core 3.1 to .NET 5.0 and I'm in front of a big problem, the exactly same line crash in .NET 5.0, the "opening" of a certificate.pfx (properties **Build action** : Embedded resource & **Copy to output** : copy always). The exact same line works in .NET 3.1

### Minimal working example. 

```csharp
var certif = new X509Certificate2(appSettings.CertificateFile, appSettings.CertificatePassword);
```

Obviously, I tried with hard coded values to check it was not a settings issue

### Relevant parts of the log file

```
System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: A certificate referenced a private key which was already referenced, or could not be loaded.
```

### Migration steps 

```
update my .csproj from 
<TargetFramework>netcoreapp3.1</TargetFramework>
to
<TargetFramework>net5.0</TargetFramework>
```

```
update my dockerfile from 
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.9-alpine3.12 AS base
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

to
 
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
```

Does anyone have this problem?
Previously, I created an issue on the Idsrv4 repository, to know if another have got this problem, and @blowdart  suggested me to create an issue on dotnet repository, so I'm here : 

The question : https://github.com/IdentityServer/IdentityServer4/issues/5057

Thanks in advance
Kind regards, Rémi

**Comment by vcsjones** [comment]
This appears to be a duplicate of https://github.com/dotnet/runtime/issues/44535.

There is a work around posted in that issue.

**Comment by odinnou** [comment]
Thanks @vcsjones  sorry for duplicate

**Comment by vcsjones** [comment]
@odinnou no worries, please feel free to discuss in that issue if you are unable to apply the work around or it does not appear to work for you.

**Comment by odinnou** [comment]
Hello @vcsjones  thank you, the workaround works for me!
