### ISSUE TITLE
Strange behavior when using PostAsJsonAsync / JsonContent

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/runtime#45587]
### Description

When posting json to server using `JsonContent` or `HttpClient.PostAsJsonAsync`, it's received as null in the server side, unless we call `jsonContent.ReadAsStringAsync` which will then arrive normally in the server!

Please refer to [this](https://github.com/weitzhandler/JsonIssueRepro) repro project and refer to the failing tests.

**Comment by Clockwork-Muse** [comment]
Link 404s

**Comment by weitzhandler** [comment]
I must have posted it as private by accident, anyway, it's public now.

**Comment by wzchua** [comment]
`PostAsJsonAsync` would serialize `T`.

you're meant to use it like 
```C#
var response = await client.PostAsync(Endpoint, weatherForecast);
```

**Comment by wzchua** [comment]
ok, it is not working because Content-Length isn't set.
This is due to `Microsoft.AspNetCore.OData.Formatter.ODataInputFormatter`
```C#
if (contentHeaders == null || contentHeaders.ContentLength == null)
{
     return Task.FromResult(InputFormatterResult.Success(defaultValue));
}
```

**Comment by weitzhandler** [comment]
So when we're posting JSON, are posting it as a stream, no, right? Maybe might be a good idea to include the length?

**Comment by layomia** [comment]
@weitzhandler, does the comment from @wzchua resolve this issue, i.e. can this issue be closed?

cc @Jozkee

**Comment by green4don** [comment]
I have not had a single case where the **'PostAsJsonAsync'** extension works in .Net 5, at the exact same place where the code works in .Net 4.8 Framework.  The server returns a 406 error and my php never sees the request.

The only solution I found was very similar - I moved to the **'PostAsync'** method but using a **'StringContent'** object. This works fine and does not require the 'ReadAsStringAsync' fudge step required by the **'JsonContent'**. 

**_var stringContent = new StringContent(bbz.Json(), Encoding.UTF8, "application/json");_**

That's a bit of overkill, but works fine every time.

All my record objects support a Json() method which is just "JsonSerializer.Serialize(this);"

I also cycle in-and-out of the GetAsync (GetByteArrayAsync, GetStringAsync, GetFromJsonAsync, GetAsync, SendAsync) not working, but throwing a fatal error that is not caught in any try/catch block. Currently working in my latest test class, so no idea about what is changing.

These extensions would be wonderful if they worked.

**Comment by green4don** [comment]
Looking at the source code, this extension is implemented generally as two statements; the **JsonContent** is created and then the **PostAsync** method is called. 

            _JsonContent content = JsonContent.Create(value, mediaType: null, options);
            return client.PostAsync(requestUri, content, cancellationToken);

            JsonContent<TValue> content = new(value, jsonTypeInfo);
            return client.PostAsync(requestUri, content, cancellationToken);_

I have not tried the version which uses a **JsonTypeInfo<TValue>** so I might explore that. 

Using the StringContent/PostAsync works, the JsonContent/PostAsync does not.

**Comment by wzchua** [comment]
You can't set the content length when you send out the response as a stream. This is done to avoid loading the whole serialized data in memory.
If your service can't work with streamed data, it would use less memory to serialize into byte[] and use ByteArrayContent + setting the correct contenttype as opposed to using StringContent

Back to the issue reported:
AspNetCoreOData has removed the length check and should work with streaming
https://github.com/OData/AspNetCoreOData/commit/679309e8abe31b98db9153e91de63acbf52a5c98

**Comment by green4don** [comment]
I really appreciate getting a cogent response.

Not having "the content length when you send out the response as a stream" seems reasonable. 

Being unsure as to what you mean by "your service" not working with streamed data (sorry, I think you mean the server which is a simple shared Bluehost Unix server) I'll leave that for another day.

"Serialize into byte[] ... " using less memory is quite possible, though I doubt very much less memory. Probably this whole UTF8 byte array internal structure stuff and not having to convert back and forth.

So, I've tested that and definitely need to "set the correct contenttype" or I get a 406 error.

        var bytesContent = new ByteArrayContent(bbz.ToBytes());
        bytesContent.Headers.Add("Content-Type", "application/json; charset=utf-8"); 
        var response = await Client.PostAsync(requestUri, bytesContent);

This works, code is about the same as StringContent, just reordered a bit.

**Comment by wzchua** [comment]
It's at least 1x memory, since string in dotnet is utf16 which has to be converted to utf8.

Ideally you would fix the server to accept streaming data.

**Comment by eiriktsarpalis** [comment]
Unless there is anything else to answer here, I'm going to close the issue. Feel free to reopen if you feel this warrants further conversation.
