### ISSUE TITLE
error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found

### ISSUE THREAD

**Issue by mayadav1** [dotnet/runtime#45582]
Description:

I faced below error while building runtime 👍 

/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error : Unable to find package Microsoft.DotNet.Arcade.Sdk with version (= 6.0.0-beta.20601.2)
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 1150 version(s) in dotnet-eng [ Nearest version: 6.0.0-beta.20530.2 ]
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 178 version(s) in dotnet-tools [ Nearest version: 5.0.0-beta.19558.13 ]
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 2 version(s) in dotnet5-transport [ Nearest version: 5.0.0-beta.20364.3 ]
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 0 version(s) in nuget.org
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 0 version(s) in dotnet5
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 0 version(s) in dotnet6-transport
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error :   - Found 0 version(s) in dotnet6
/home/amd/manoj/project2/runtime/artifacts/toolset/restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
Build failed (exit code '1').

This also appears when build.sh clean.

OS:
Ubuntu 18.04.1 LTS

dotnet version:
5.0.100

PLease help me over it.

**Comment by hoyosjs** [comment]
I checked and the precise version is available on the dotnet-eng feed. If you have an artifacts directory, can you please try removing it? And can you try clearing your nuget cache by running `./dotnet.sh nuget locals http-cache --clear` from the root of the repo?

**Comment by t-mustafin** [comment]
> I checked and the precise version is available on the dotnet-eng feed. If you have an artifacts directory, can you please try removing it? And can you try clearing your nuget cache by running `./dotnet.sh nuget locals http-cache --clear` from the root of the repo?

Thanks, I got same issue and it woks for me.

**Comment by ViktorHofer** [comment]
Closing as resolved.
