### ISSUE TITLE
System.Net.Security.SslStream.AuthenticateAsClient failed on Ubuntu 20.04 and .NET 5

### ISSUE THREAD

**Issue by huiren-jiang** [dotnet/runtime#45581]
Hi,

After we ported all of our projects from dotnet3.1 to dotnet5, the client side code began to fail on Ubuntu 20.04. Below is the detail of the exception when we invoke System.Net.Security.SslStream.AuthenticateAsClient,

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available
TestCleanup method Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrTestSuite.BaseTestCleanup threw exception. System.InvalidOperationException: System.InvalidOperationException: the received thread does not initialize..
```

Also I checked the network capture, the first TLS packet sent by client is alert instead of handshake(clienthello).

Could anyone help with it, thanks!

**Comment by wfurt** [comment]
Does you server support TLS1.2? .NET 5.0 has some of the weak ciphers disabled by default. Look at notes in #45244

**Comment by huiren-jiang** [comment]
Got it, I think this should be why dotnet5 failed the same environment.

Thanks for your information!
