### ISSUE TITLE
Regex.Escape doesn't escape the monkey character @

### ISSUE THREAD

**Issue by mladenb** [dotnet/runtime#45589]
Not sure if this is a bug or a feature, but in case of a doubt I believe it's best to submit a bug report, anyway.

So, Regex.Escape method (or more precisely RegexParser.Escape) doesn't escape the monkey character (@). Should this be escaped as well? 

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs

**Comment by danmosemsft** [comment]
Hi @mladenb this method is intended to expire only characters that have particular meaning in .NET regexes. This is so you can take the result and use it as a literal component in your own regex and it will be treated like the original string. If it escaped @ this would not work.
