### ISSUE TITLE
[wasm] Debugger unable to show value

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#45595]
I try to provide more description,
because this problem occures when we want to see value of variable from type of a class on other assembly of solution, based on a class from thrid party!!!

Class A => On assembly Model.dll
Class B => On third party assembly, referenced to Model.dll
Class C => a property of class A. type C defined on third party
Class D => has property of type A,
```csharp
public class A : B
{
    public C property1 {get;set;}

   public A()
 {
     property1  = new property1();
 }

}
```
Usage of Class A on class D on assembly Views.dll

```csharp
public class D
{
    public A property2 {get;set;}

private void TestFunctionForBreakPoint()
{
   this.Property2 = new A();
  var A =  A.Property1;
}

}
```

set breakpoint on var A = A.property1 and value of this property not shown.

I try to create sample project for you
BR

Based off @ehsangfl's comment in https://github.com/mono/mono/issues/19942#issuecomment-738850158 .

**Comment by radical** [comment]
@ehsangfl could you also share what version of .net, and VS you are using?

**Comment by ehsangfl** [comment]
@radical Sorry for delay.
this problem is exists from dotnet core 3.1, until 5.0.1
and visual studio  16.8 and before

**Comment by lewing** [comment]
@thaystg I think this is fixed in 6.0?

**Comment by thaystg** [comment]
I'll test it! :)

**Comment by thaystg** [comment]
But I think so!
