### ISSUE TITLE
Nullable Anotation of XmlDocument.XmlResolver seems to incorrect

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/runtime#45594]
### Description

XmlDocument.XmlResolver is not anotated as nullable. But the [documation](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument.xmlresolver?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Xml.XmlDocument.XmlResolver);k(DevLang-csharp)%26rd%3Dtrue&view=net-5.0) mentionds setting it to `null`

> # Exceptions
> **XmlException**
>This property is set to `null` and an external DTD or entity is encountered.

I intentional set this property to `null`, to raise the above exception. Upgrading to .Net 5 then showed an error here.

I hope this is the correct repo to report this. 

### Configuration

.Net5.0-windows on Visual Studio 16.8.2

**Comment by buyaa-n** [comment]
@LokiMidgard  thank you for reporting, it seems you are right, looks it can be null cc @krwq @Jozkee

**Comment by krwq** [comment]
@LokiMidgard you're right, do you want to send a PR with a fix?

**Comment by LokiMidgard** [comment]
@krwq I have created a PR. But it was only adding the questionmark to the property.

The Property itself handled nullable already correct (I think). The Property also missing an getter but have an method to access the field which was already nullable, so nothing to change there.
