### ISSUE TITLE
Missing argument validation on 'LoggerFactory.AddProvider'

### ISSUE THREAD

**Issue by julealgon** [dotnet/runtime#45599]
### Description

`Microsoft.Extensions.Logging.LoggerFactory` implements `ILoggerFactory` with a `AddProvider(ILoggerProvider)` method. However, it does not perform any argument validation on `provider`, meaning it will consider `null` as a "valid" provider and add it to the collection of providers internally.

Some operations inside the class will unnecessarily throw `NullReferenceException`s due to this behavior, like the `Dispose` method, which will capture these exceptions and do nothing.

One would expect that `null` providers are not accepted and the method should throw a `ArgumentNullException`.

### Configuration

Net 5.0
Microsoft.Extensions.Logging latest (v5.0.0)

### Other information

Here is where it loads up the `provider`:

https://github.com/dotnet/runtime/blob/fae35941e16310d815460475810f069578e6e774/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L148-L157

https://github.com/dotnet/runtime/blob/fae35941e16310d815460475810f069578e6e774/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L174-L180

And here an example where exceptions will be generated and caught:

https://github.com/dotnet/runtime/blob/fae35941e16310d815460475810f069578e6e774/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L254-L264

I'm not sure if this could cause further problems downstream when using the loggers from the factory.

**Comment by maryamariyan** [comment]
I think it would make sense to ArgumentNullException for this case. 

To your point, as part of the effort to enable nullable annotations for extensions libraries (tracked [here](https://github.com/dotnet/runtime/issues/43605)), we just recently annotated Logging.Abstractions, and that means ILoggerFactory implemented under Logging.Abstractions would expect to take a nullable ILoggerProvider for `ILoggerFactory.AddProvider(ILoggerProvider)`.

When we enable nullable annotations for Microsoft.Extensions.Logging, we'd take this into account there as well.

**Comment by julealgon** [comment]
> So I think, throwing ArgumentNullException would be beneficial for when nullable annotations are not enabled.

I think this is ill-advised @maryamariyan : `ArgumentNullExceptions` should be thrown even in the case that correct nullable annotations are in place. 

This is because as of right now, there is no runtime validation leveraging nullable annotations, so if consumers pass a `null` value, one would still see the same issues. Also keep in mind that people having nullable reference types disabled and also freely pass `null` into these methods without any warnings without using the `!` operator.

I do hope to see C# and the runtime move into full-on runtime validation of these nullable constraints at some point, and then we could remove the manual argument validation from everywhere.

**Comment by Michael3161010** [comment]
I am looking for a good first issue to pick up, does anyone have an issue if I do that ?

**Comment by maryamariyan** [comment]
> I am looking for a good first issue to pick up, does anyone have an issue if I do that ?

Seems like there is a PR for this now. @Michael3161010 you could perhaps pick another one from [here](https://github.com/dotnet/runtime/labels/up-for-grabs) and comment on the one you picked stating you picked it and would be creating a PR for it.

**Comment by maryamariyan** [comment]
Thanks for the pointer @julealgon. We should throw even if nullable annotations are enabled, since the consuming library may not have nullable enabled. Also, e.g. `Foo(null!)` could get past compiler, and then in runtime with this fix we'd receive an ArgumentNullException which is better than the previous NRE.

cc: @safern
