### ISSUE TITLE
Improve in-proc consumption story of runtime metrics

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#45590]
[AB#1244363](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244363)
Since .NET Core 3.0 we've been adding many DiagnosticCounters to the runtime as well as the BCL to track some key metrics. These metrics can easily be consumed by `dotnet-counters` or with ETW/EventPipe out-of-proc.

In-proc-consumption of these metrics is not very easy/efficient. Using `EventListener` to consume these metrics is non-intuitive and is also expensive due to the way EventListeners are implemented. 

It's also not straightforward to get the metrics themselves by plumbing them through EventCounters -> EventSource -> EventListeners.

This issue tracks all the work that needs to happen to make in-proc consumption of runtime (and core libraries) metrics easier and more efficient.

Related issues: 
- https://github.com/dotnet/runtime/issues/36571
-  https://github.com/dotnet/runtime/issues/43610

**Comment by josalem** [comment]
closed via #55046
