### ISSUE TITLE
Decouple 'ILoggerFactory' and 'ILoggerProvider' from 'IDisposable'

### ISSUE THREAD

**Issue by julealgon** [dotnet/runtime#45602]
## Background and Motivation

Currently, `ILoggerFactory` and `ILoggerProvider` from `Microsoft.Extensions.Logging.Abstractions` also implements `IDisposable`. This forces every implementation to _also_ have to implement disposal semantics, even if they are not applicable (i.e. there are no resources that need disposal).

I believe this is a poor decision for a couple reasons:
1. it is a violation of the dependency inversion principle, since needing disposal is an implementation detail, while the `ILoggerFactory` is an abstraction. The interface cannot sensibly know that every implementation will need disposal to force this into every implementer
2. it substantially complicates the design of implementors who do not need disposal, in particular those that are not sealed classes. e.g. `LoggerFactoryDecorator`, an abstract decorator class that needs to implement the full disposable pattern due to this
3. The responsibility of disposing is with the creator of the instance, which knows its type. there is no need to have the interface itself being `IDisposable` since the factory concrete class will be disposed in a `using` block or by a dependency injection container automatically

## Proposed API

I propose the `IDisposable` implementation be moved, from `ILoggerFactory` and `ILoggerProvider` in the `Abstractions` package, to their concrete implementations in `Microsoft.Extensions.Logging`.

For example (`ILoggerFactory`):

```diff
namespace Microsoft.Extensions.Logging
{
-    public interface ILoggerFactory : IDisposable {
+    public interface ILoggerFactory {
}
```

```diff
namespace Microsoft.Extensions.Logging
{
-    public class LoggerFactory : ILoggerFactory {
+    public class LoggerFactory : ILoggerFactory, IDisposable {
}
```

## Risks

I'm aware that a change such as this would potentially cause breaking changes to consumers (i.e. logging library authors mostly), and thus should be handled on major versions only with a heads-up notice of some sort.

Other than that, I don't immediately see other issues with it.

**Comment by mayorovp** [comment]
```csharp
public virtual void Dispose() {}
```

Why this line called "too complex full disposable pattern"?

**Comment by julealgon** [comment]
> Why this line called "too complex full disposable pattern"?

@mayorovp  Not sure where I said that. What you provided is not the correct/full implementation of `IDisposable` for unsealed classes. Please see here: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1063

Since you downvoted the item, I assume you disagree with the other points. Would you be willing to elaborate why? Do you not consider disposable an implementation detail, or that the creator of the instance should be responsible for disposal?

**Comment by FiniteReality** [comment]
If you're implementing a forwarding type like a decorator, your Dispose implementation can literally just be:
```cs
public void Dispose()
{
    (forwardedInstance as IDisposable).Dispose();
}
```
As far as I'm aware, that is the correct way to do it.

The disposable pattern is made up of parts which you pick and choose based on the scenario; there is no "every IDisposable implementation must do these things", like implementing `protected virtual` Dispose methods, since 90% of the time your classes won't be sub-classed anyway. And as a general rule anyway, you should be preferring composition over inheritance, since that encapsulates more implementation details than inheritance does.

**Comment by mayorovp** [comment]
@julealgon disposability cannot be just "implementation detail". As interface user, i must know about Dispose requirement to use object correctly. Thats why `Stream` implements `IDisposable`, thats why `IEnumerator` extends `IDisposable`, thats why `ILoggerFactory` extends `IDisposable`.

---

About full disposable pattern. This pattern became obsolete in .NET Framework 2.0, when safe handles appeared. I don't know why someone implemented CA1063 rule, but you can safely disable it and use one-line empty Dispose if you want.

**Comment by julealgon** [comment]
@mayorovp 
> As interface user, i must know about Dispose requirement to use object correctly

I'm not sure I follow you there. Why do you need to know that `ILoggerFactory` is disposable if you are only dealing with its interface? Surely if you created it, you'd know which concrete type you used and would properly be able to dispose it, however if you only get a reference to the interface you wouldn't know whether or not it would need disposal, nor would you be responsible for disposing it since you didn't create it.

Can you elaborate why you'd need `ILoggerFactory` to implement `IDisposable`?

> About full disposable pattern. This pattern became obsolete in .NET Framework 2.0, when safe handles appeared. I don't know why someone implemented CA1063 rule, but you can safely disable it and use one-line empty Dispose if you want.

Would you mind providing some documentation around this obsolescence? This is the first time I'm hearing this, and this rule is active in the latest .Net 5 analyzers, so it seems weird that it was made obsolete.

**Comment by stephentoub** [comment]
This would be a huge breaking change and is not something we can entertain. Thanks.
