### ISSUE TITLE
[mono] Implement and document PINVOKE_OVERRIDE

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#45607]
See https://github.com/dotnet/runtime/pull/44505 for a more detailed description and the CoreCLR implementation.

Some embedders will probably be happy to migrate to this once it exists.

**Comment by jkotas** [comment]
Is this callback sufficient replacement for the `__Internal` scenarios? (#7267)

**Comment by CoffeeFlux** [comment]
I don't think so. We've long had the _ability_ to recreate `__Internal` loading via existing functionality, and this doesn't really change that. As I see it, `__Internal` requests are mostly about convenience for an extremely common desire with embedding, so that developers don't have to copy paste the same snippet (be it using this callback or existing managed callbacks) into all their embedding projects.

**Comment by kg** [comment]
Should this be closed yet? We implemented it, but the PR that closed this doesn't add documentation.

**Comment by CoffeeFlux** [comment]
I assumed documentation will be handled on the CoreCLR side (where it was initially implemented). This issue was purely for the Mono-specific implementation. If there's a documentation gap, we should probably just open a separate issue rather than using this one to track that.
