### ISSUE TITLE
OrdinalIgnoreCase could be faster when one of the args is a const ASCII string

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#45613]
It's a quite popular case when we compare a string against some predefined one using `Ordinal/OrdinalIgnoreCase` case (I found plenty of cases in dotnet/aspnetcore and dotnet/runtime repos). E.g. patterns like:
```csharp
* string.Equals(str, "cns", StringComparison.OrdinalIgnoreCase); // or just Ordinal

* str.Equals("cns", StringComparison.OrdinalIgnoreCase); // or just Ordinal

* StringComparer.OrdinalIgnoreCase.Equals(str, "cns"); // or just Ordinal
```
So Roslyn/ILLink/JIT (perhaps, it should be JIT to handle more cases after inlining + Roslyn/ILLink know nothing about target arch) could optimize such comparisons by inlining a more optimized check, e.g. here is what we can do for small strings (1-4 chars) keeping in mind that strings are 8-bytes aligned (for simplicity I only cared about AMD64 arch):
```csharp
[Benchmark(Baseline = true)]
[Arguments("true")]
[Arguments("TRUE")]
public bool StringEquals(string str)
{
    return string.Equals(str, "True", StringComparison.OrdinalIgnoreCase);
}

[Benchmark]
[Arguments("true")]
[Arguments("TRUE")]
public bool Inlined(string str)
{
    return object.ReferenceEquals(str, "True") || 
           (str.Length == 4 &&

            // string's content fits into 64bit register, the following code looks awful
            // but it's a simple 'or + cmp' in the codegen
            (Unsafe.ReadUnaligned<ulong>(ref Unsafe.As<char, byte>(
                   ref MemoryMarshal.GetReference(str.AsSpan()))) | 0x0020002000200020 /*'to upper' since the const arg doesn't contain anything but [a..Z]*/) == 0x65007500720074);
}
```
```
|       Method |  str |      Mean |     Error |    StdDev | Ratio |
|------------- |----- |----------:|----------:|----------:|------:|
| StringEquals | TRUE | 4.1723 ns | 0.0023 ns | 0.0020 ns |  1.00 |
|      Inlined | TRUE | 0.3416 ns | 0.0024 ns | 0.0022 ns |  0.08 |
|              |      |           |           |           |       |
| StringEquals | true | 4.1718 ns | 0.0023 ns | 0.0021 ns |  1.00 |
|      Inlined | true | 0.3406 ns | 0.0019 ns | 0.0016 ns |  0.08 |
```
We also can inline SIMD stuff for longer strings, e.g. here I check that an http header is `"Proxy-Authenticate"`  (18 chars) using two AVX2 vectors: https://gist.github.com/EgorBo/c8e8490ddd6f9a0d5b72c413ddd81d44
```
|           Method |         headerName |      Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |------------------- |----------:|----------:|----------:|------:|------:|------:|------:|----------:|
|     StringEqauls | PROXY-AUTHENTICATE | 10.296 ns | 0.0087 ns | 0.0078 ns |  1.00 |     - |     - |     - |         - |
| StringEqauls_AVX | PROXY-AUTHENTICATE |  2.560 ns | 0.0042 ns | 0.0038 ns |  0.25 |     - |     - |     - |         - |
|                  |                    |           |           |           |       |       |       |       |           |
|     StringEqauls | proxy-authenticate | 10.298 ns | 0.0078 ns | 0.0065 ns |  1.00 |     - |     - |     - |         - |
| StringEqauls_AVX | proxy-authenticate |  2.563 ns | 0.0071 ns | 0.0066 ns |  0.25 |     - |     - |     - |         - |
```
when the input string is let's say 30 bytes the results are even better:
```
|           Method |           headerName |      Mean |     Error |    StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |--------------------- |----------:|----------:|----------:|------:|------:|------:|------:|----------:|
|     StringEqauls | PROXY(...)WORLD [30] | 15.396 ns | 0.0141 ns | 0.0117 ns |  1.00 |     - |     - |     - |         - |
| StringEqauls_AVX | PROXY(...)WORLD [30] |  2.558 ns | 0.0010 ns | 0.0008 ns |  0.17 |     - |     - |     - |         - |
|                  |                      |           |           |           |       |       |       |       |           |
|     StringEqauls | proxy(...)World [30] | 14.997 ns | 0.0089 ns | 0.0079 ns |  1.00 |     - |     - |     - |         - |
| StringEqauls_AVX | proxy(...)World [30] |  2.550 ns | 0.0038 ns | 0.0030 ns |  0.17 |     - |     - |     - |         - |
```
So for [0..32] chars (string.Length) we can emit an inlined super-fast comparison:
[0..4]: using a single 64bit GP register
[5..8]: using two 64bit GP registers
[9..16]: using two 128bit vectors
[17..32]: using two 256bit vectors
[33...]: leave as is.

/cc @GrabYourPitchforks @benaadams @jkotas @stephentoub

**Comment by Szer** [comment]
It could be very beneficial for headers parsing in web servers.

**Comment by GrabYourPitchforks** [comment]
Somewhat related to https://github.com/dotnet/runtime/issues/11484. If the JIT has knowledge that one of the parameters is constant, it can tell us to go down a separate code path, or it can even redirect the call to a different method.

**Comment by EgorBo** [comment]
@GrabYourPitchforks Nice idea, reminds me this LLVM intrinsic: https://llvm.org/docs/LangRef.html#llvm-is-constant-intrinsic

Thanks to https://github.com/dotnet/runtime/pull/37226 and https://github.com/dotnet/runtime/pull/1378 the following code is computed as a const! 🎉 
```csharp
public ulong Test() => ConstStringTo64BitInt("True");

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static ulong ConstStringTo64BitInt(string str)
{
    ulong v = 0;
    if (str.Length == 4) v |= ((ulong)str[3] << 48);
    if (str.Length >= 3) v |= ((ulong)str[2] << 32);
    if (str.Length >= 2) v |= ((ulong)str[1] << 16);
    if (str.Length >= 1) v |= ((ulong)str[0]);
    if (str.Length == 0) return 0;
    return v;
}
```
Codegen for `Test`:
```asm
       48B85400720075006500 mov      rax, 0x65007500720054
       C3                   ret
```

**Comment by EgorBo** [comment]
`bool JitHelpers.IsConstAsciiString(string)` prototype: https://github.com/EgorBo/runtime-1/commit/86ca1306f9089acc16dd9711680864e395627a54

**Comment by jkotas** [comment]
There are many APIs that can be replaced with more efficient call-site specific equivalent when the input is in a particular shape. Would source generators be better way to handle that? It would be much more powerful solution than IsConstAsciiString.

**Comment by Szer** [comment]
> Would source generators be better way to handle that? It would be much more powerful solution than IsConstAsciiString

Does it mean that optimized path in language agnostic BCL could only be used in C#?

**Comment by EgorBo** [comment]
I think at least for the 
```csharp
string.Equals(str, "cns", StringComparison.OrdinalIgnoreCase); // Also, for just `Ordinal`
```
for `str.Length <= 4` (or `2` in case of 32bit) small strings we can introduce the optimization directly in the JIT, it shouldn't be difficult to implement - a couple of `GT_QMARK` and indirect loads` for `string.Equals` intrinsic. We can also rely on PGO and don't do it in the cold blocks. But I'd honestly also implement if for longer strings using SSE/AVX, it shouldn't be a lot of code as well.

**Comment by EgorBo** [comment]
Prototype for ^ in JIT:  https://github.com/EgorBo/runtime-1/commit/58833624cd3ae5bee2fa9b3ef0a0e1efaa2f0302

**Comment by jkotas** [comment]
> It could be very beneficial for headers parsing in web servers.

Could you please share links to the webserver code where you think this would be very beneficial?

> Prototype

I think it make sense to start with the simpler memcpy-like and memcmp-like cases before going to more esoteric cases like globalization.

Also, we need to maintain parity between string and Spans (the same optimization has to be implemented for both). We have been promoting Spans as the high performance solution. We do not want to be in situation where strings have extra optimizations that are missing for Spans.

**Comment by Szer** [comment]
> Could you please share links to the webserver code where you think this would be very beneficial?

I'm working in Azure Gateway team (reverse proxy for everything in Azure), our header parsing code taking 3.5% CPU time.
Code looks like this (header names were removed):
```csharp

        public bool CheckHeader(string headerName, bool logAllHeaders)
        {
            if (headerName == null)
            {
                return false;
            }

            if (logAllHeaders)
            {
                return !headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
            }
            else
            {
                bool shouldIgnore = Egor.ShouldIgnore(headerName);
                return !shouldIgnore && headerName.StartsWith("foo", StringComparison.OrdinalIgnoreCase);
            }
        }

        private static bool ShouldIgnore(string headerName)
        {
            switch (headerName.Length)
            {
                case 13:
                    return headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
                case 17:
                    return headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
                case 22:
                    return
                        headerName.Equals("foo", StringComparison.OrdinalIgnoreCase) ||
                        headerName.Equals("foo", StringComparison.OrdinalIgnoreCase) ||
                        headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
                case 25:
                    return headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
                case 28:
                    return headerName.Equals("foo", StringComparison.OrdinalIgnoreCase);
                default:
                    return false;
            }
        }
```

I'm pretty sure ASP Net team also will be pleased to optimize header parsing.
(Example 1)[https://github.com/dotnet/runtime/blob/dc0e11d2e681659fc20feebf4c092082e75706af/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L411]

(Example2)[https://github.com/dotnet/aspnetcore/blob/77fe36f069c89381caba274784902ff0f248fe57/src/Servers/Kestrel/shared/KnownHeaders.cs]

**Comment by Tornhoof** [comment]
> There are many APIs that can be replaced with more efficient call-site specific equivalent when the input is in a particular shape.  Would source generators be better way to handle that? It would be much more powerful solution than IsConstAsciiString.

The first customer of such a source-gen could be System.Text.Json's property matching, I use pretty much the same approach (without avx and only ordinal comparison, not case-insensitive) in SpanJson and up to ~32 bytes it's a lot faster than string.Equals.

**Comment by jkotas** [comment]
Yep, this can make naively written parsers better. There are other tricks that high-performance parsers use as the ASP.NET example shows and that this won't handle. I doubt that ASP.NET will want to replace their fine-tuned parser even if this optimization gets implemented.

**Comment by gfoidl** [comment]
...and a lot of fast parsers operate with utf-8 or ascii bytes and try to avoid creating strings as much as possible.

Maybe also consider Equals with ROS<byte> in this (general) deliberation.

**Comment by EgorBo** [comment]
@jkotas 

> I think it make sense to start with the simpler memcpy-like and memcmp-like cases before going to more esoteric cases like globalization.

I'm not sure I follow, can you please post an example of these memcpy/memcmp usages?

My idea was to optimize cases when we compare a string against some predefined one in the most convenient way. E.g. even a simple search shows many cases in dotnet/runtime:
![image](https://user-images.githubusercontent.com/523221/101265564-83a1c980-3758-11eb-9bd1-7ce50dbe255d.png)
and it doesn't even cover cases when the constant string is a named constant.

I agree it'd be nice to also handle `ReadOnlySpan` as well but it's more complicated to implement because of that `const string -> to Span` conversion in the middle, it definitely won't be a single statement in the import phase.

**Comment by jkotas** [comment]
> I'm not sure I follow, can you please post an example of these memcpy/memcmp usages?

memcpy/memcmp primitives are exposed via number of different methods: CopyTo, TryCopyTo, Equals, SequenceEquals, StartsWith, ... .

Example for memcpy: 

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Boolean.cs#L102

This would be more naturaly written as `"True".AsSpan().CopyTo(destination)` and compiled into a sigle instruction that writes all 8 bytes in one shot.

Example for memcmp:

https://github.com/dotnet/runtime/blob/f9a8abc8a5d9981e25f898181e734dc77c7e15e4/src/libraries/System.Net.Http/src/System/Net/Http/Headers/AltSvcHeaderParser.cs#L144

> My idea was to optimize cases when we compare a string against some predefined one in the most convenient way

I agree with the idea of enabling people to write natural. I would add that the optimizations in this space need to work well with our other best practices for writing high-performance code, that means Spans. Optimizations that only kick in for code that is likely slow for other reason (e.g. allocates a lot of strings) won't move the needle.

**Comment by EgorBo** [comment]
@jkotas Thanks for the examples!
Looks like thse StartsWith/EndsWith/SequenceCompareTo methods for Spans have `AggressiveInlining` on them and all three use `SpanHelpers.SequenceEqual` under the hood so in theory it should be beneficial to try to intrinsify it for const args. The problem that even this simple method:
```csharp
static bool Test(ReadOnlySpan<char> span)
{
    return span.StartsWith("test");
}
```
Emits a freaking forest of GenTree 😢 https://gist.github.com/EgorBo/7dd7537b8a8cb4341b47bc9499f60e7a
(26 basic-blocks!)

So the only way is to intrinsify each of them separately I guess. Or rely on that source-gen approach.

**Comment by jkotas** [comment]
Or apply the optimization later in the pipeline once this forest of GenTrees gets simplified.

**Comment by EgorBo** [comment]
> Or apply the optimization later in the pipeline once this forest of GenTrees gets simplified.

Still contains a lot of temps - https://gist.github.com/EgorBo/c6eb8edd8de19934506a3a9f3c859f46
Ideally this code:
```csharp
ref char p = ref MemoryMarshal.GetReference("hello".AsSpan()); // after inlining
```
should be optimized into just
```csharp
ref char p = ref "hello"._firstChar;
```

Perhaps, spans should have some special operators in JIT's IR or something like that

**Comment by EgorBo** [comment]
Ah, I didn't notice it was assigned

**Comment by sandreenko** [comment]
> Ah, I didn't notice it was assigned

Don't worry, my task was just to do a further triage, I have not started the implementation :-)
