### ISSUE TITLE
Missing VS pre-req leads to non-obvious build error

### ISSUE THREAD

**Issue by bwadswor** [dotnet/runtime#45610]
*Initial cost estimate*: 2 days
*Initial contacts*: @trylek, @ViktorHofer 

### Description

Would be nice if missing dependencies were flagged clearly in the build.

### Steps to Repro
1. starting with a clean machine, install all the pre-reqs except for VS2019.  (i just failed to install it...)

> https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md clearly lists VS as a pre-req.
2. clone
3. build.cmd
4. observe error, and scratch head trying to figure out why it didn't work cleanly..

### Fragment of Output from build
  Restore was successful.
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  System.Private.CoreLib -> D:\CoreCLR6\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll
  DIALib -> D:\CoreCLR6\runtime\artifacts\bin\DIALib\Debug\DIALib.dll
D:\CoreCLR6\runtime\.dotnet\sdk\5.0.100\Microsoft.Common.CurrentVersion.targets(4818,5): error MSB3030: Could not copy the file "D:\DIA SDK\bin\amd64\msdia140.dll" because it was not found. [D:\CoreCLR6\runtime\src\coreclr\src\ToolBox\SOS\DacTableGen\DacTableGen.csproj]

### Hopeful
It'd be nice if this dependency (and frankly all dependencies) were nicely flagged as missing during build.

I've listed this one here as I hit it... and now others will quickly find this via issue search and know what to do...

I dont really expect that we spend much effort fixing this.. but if someone wanted to take a few moments that also wouldn't be bad....

**Comment by tommcdon** [comment]
@trylek

**Comment by ViktorHofer** [comment]
Most of the discussion about this happened in https://github.com/dotnet/runtime/pull/39052. I think we can close this as a dup of the original issue the PR is trying to fix.
