### ISSUE TITLE
Support Dev inner loop improvements in CoreCLR VM

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#45629]
Contributes to dotnet/core/issues/5511

## Overview

Our goal is to provide a consistent dev inner loop experience in .NET Core across all platforms, architectures, and workloads.  Today, code edits can be made at runtime and applied to running processes using [ReJIT](https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/davbr-blog-archive/ReJIT%20-%20The%20Basics.md) and [Edit and Continue ](https://docs.microsoft.com/en-us/visualstudio/debugger/edit-and-continue?view=vs-2019).  The typical dev inner loop involves making code edit changes, building, debugging, then making new edits.  Edit and Continue can apply code edits while the debugger is attached and given that it conforms to a set of constraints (defined [here](https://github.com/dotnet/roslyn/blob/master/docs/wiki/EnC-Supported-Edits.md/)).  Our desire is to improve the inner loop and by allowing code edits to applied at runtime and support multiple platforms/architectures.  Ideally this work will involve using the same/similar API's being used for [Mono Method Body Replacement](https://github.com/dotnet/runtime/issues/44806).

**Comment by srxqds** [comment]
will mono support it in jit mode?

**Comment by tommcdon** [comment]
> will mono support it in jit mode?

Please see https://github.com/dotnet/runtime/issues/44806 for the mono hot reload work

**Comment by tommcdon** [comment]
Hot Reload is now enabled on .NET Core and Mono, closing
