### ISSUE TITLE
PropertyGrid: different order for Font properties

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#45631]
* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Have you experienced this same bug with .NET Framework?: Yes/No

**Problem description:**

![image](https://user-images.githubusercontent.com/4403806/59329728-f207f600-8d32-11e9-81f3-80cd6c2ae893.png)

**Expected behavior:**

The order should be the same as in .NET Fx

**Minimal repro:**

* build and launch WinFormsControlsClassicTests and WinformsControlsTest
* click `FontNameEditor` button in both and align opened windows side-by-side
* expand any of `Font` properties

**Comment by safern** [comment]
Since this has been the behavior since we ported drawing to .NET Core, I think it makes sense to fix it on 6.0

**Comment by RussKie** [comment]
I'm happy to give it a go, and get my hands dirty with the runtime :)
