### ISSUE TITLE
NotImplementedException when creating Bitmap with CMYK color space [System.Drawing.Common][.Net Core][Linux]

### ISSUE THREAD

**Issue by AsposeAG** [dotnet/runtime#45645]
When we create System.Drawing.Bitmap with CMYK PixelFormat it throws exception.

```charp
public const PixelFormat Format32bppCMYK = (PixelFormat)0x200F;
Bitmap cmykBmp = new Bitmap(rgbBmp.Width, rgbBmp.Height, Format32bppCMYK);
```

> Exception has occurred: CLR/System.NotImplementedException
> An unhandled exception of type 'System.NotImplementedException' occurred in System.Drawing.Common.dll: 'Not implemented.'
>    at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)

System Info:
Kubuntu 20.04
.Net Core 3.1
System.Drawing.Common 5.0

Example project:
[CMYKBug.zip](https://github.com/dotnet/runtime/files/5648455/CMYKBug.zip)

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
