### ISSUE TITLE
Zero data loaded from EMF file [System.Drawing.Common][.Net Core][Linux]

### ISSUE THREAD

**Issue by AsposeAG** [dotnet/runtime#45647]
EMF File loaded from disk contains zero data.

```charp
static string folder = @"d:\save\rec";

static void LoadMetaFromStream()
{
    using (FileStream fstr = new FileStream(Path.Combine(folder, "metareal.emf"), FileMode.Open))
    using (Image img = Image.FromStream(fstr))
    {
        using (Bitmap bmp = new Bitmap(300, 300, PixelFormat.Format32bppArgb))
        {
            using (Graphics graph = Graphics.FromImage(bmp))
            {
                graph.Clear(Color.White);
                graph.DrawImage(img, 0, 0);
            }
            bmp.Save(Path.Combine(folder, "metastrloaded.png"), ImageFormat.Png);
        }
    }
}

static void LoadMetaFromFile()
{
    using (Image img = Image.FromFile(Path.Combine(folder, "metareal.emf")))
    {
        using (Bitmap bmp = new Bitmap(300, 300, PixelFormat.Format32bppArgb))
        {
            using (Graphics graph = Graphics.FromImage(bmp))
            {
                graph.Clear(Color.White);
                graph.DrawImage(img, 0, 0);
            }
            bmp.Save(Path.Combine(folder, "metafileloaded.png"), ImageFormat.Png);
        }
    }
}
```

System Info:
Kubuntu 20.04
.Net Core 3.1
System.Drawing.Common 5.0

Example project:
[EmfBug.zip](https://github.com/dotnet/runtime/files/5648459/EmfBug.zip)
[metareal.zip](https://github.com/dotnet/runtime/files/5648460/metareal.zip)

**Comment by danmosemsft** [comment]
@AsposeAG which OS is this? The title says Linux, but the code above has a Windows path.

**Comment by AsposeAG** [comment]
> @AsposeAG which OS is this? The title says Linux, but the code above has a Windows path.

Kubuntu 20.04

The code is tested on Windows and Linux. On Windows, everything works well, on Linux (with replacing folder path) loaded file doesn't have any data.
It is related with this issue https://github.com/dotnet/runtime/issues/45646
I tried to load created on windows file metareal.emf.

**Comment by danmosemsft** [comment]
@AsposeAG do you have time to debug a little bit? It is probably an issue with https://github.com/mono/libgdiplus.

Also, is this a new project you are working on? If so, would it be an option to use another library than System.Drawing? It is legacy really only intended for porting existing code. There are better options like skiasharp and imagesharp.

**Comment by AsposeAG** [comment]
> @AsposeAG do you have time to debug a little bit? It is probably an issue with https://github.com/mono/libgdiplus.
> 
> Also, is this a new project you are working on? If so, would it be an option to use another library than System.Drawing? It is legacy really only intended for porting existing code. There are better options like skiasharp and imagesharp.

Yes I know that is it issue of libgdiplus, these function just are not implemented there. But System.Drawing.Common is based on libgdiplus and, I think, Microsoft is responsible for both libraries.
https://github.com/mono/libgdiplus/blob/master/src/graphics-metafile.c

We use System.Drawing.Common for  Aspose.BarCode and some other projects. It is not critical bug, but project behavior is slightly different on Windows and Linux/OSX.

And we used skiasharp before, but drawing sometimes is different from System.Drawing libraries (.Net and System.Drawing.Common).

But it is still System.Drawing.Common bug. Maybe it will be better to rewrite all libgdiplus functions on pure .Net for *nix systems? It will solve most of problems for plenty of users.

**Comment by safern** [comment]
Thanks @AsposeAG I definitely feel the pain that customers are feeling because of these differences and limited functionality on Unix. We need to figure out what to do, at the moment, may I suggest trying out ImageSharp as well as an alternative to SkiaSharp if that didn't meet what you needed?

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
