### ISSUE TITLE
Provide HttpClient name to HttpClientHandler middleware

### ISSUE THREAD

**Issue by sandersaares** [dotnet/runtime#45653]
For purposes of logging/metrics, I want my HTTP message handler middleware to know which HttpClient registration it is being called from. For example:

```csharp
services.AddHttpClient("foo", client =>
{
    client.DefaultRequestHeaders.Add("x", "y");

}).UseRequestLoggingMiddleware();
```

Where `UseRequestLoggingMiddleware()` adds some custom middleware I use. In this middleware I want to write log entries that reference the string "foo" provided when the HttpClient was registered.

However, I am unable to find any way to lookup the HttpClient name "foo" when in the middleware. Please add support for passing this identifier to the middleware.

**Comment by scalablecory** [comment]
@CarnaViire

**Comment by CarnaViire** [comment]
Is the function `UseRequestLoggingMiddleware` something you implement yourself? `IHttpClientBuilder` that is passed to it contains the name of the registration. So upon registration inside `UseRequestLoggingMiddleware` you can access it and pass to whatever you are registering.
Here is an example of our own extension method accessing `builder.Name`
https://github.com/dotnet/runtime/blob/d43b00abe0043e26eb59f9d01e02fbcee820e0c9/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L458-L472

**Comment by sandersaares** [comment]
Thank you for the explanation @CarnaViire! Looks like my use case is satisfied by this and we can close the issue.
