### ISSUE TITLE
Task Delay(int millisecondsDelay, CancellationToken cancellationToken, bool throwException)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#45650]
## Background and Motivation
When doing a ```Task.Delay``` I often want to cancel the delay due to another operation completing successfully.  When canceling the timeout, it causes an exception to be thrown which results in unnecessary messages in the debug view.  We have the philosophy that exceptions are bad and should be infrequent but cancelling a timeout is actually good and should happen often.

It would be nice if the ```Task.Delay``` methods that accept a cancellation token also accept a ```throwExceptionWhenCanceled``` which, when set to false, causes the Task.Delay to return as normal without throwing the ```OperationCancelledException```.

## Proposed API
```
Task Delay(int millisecondsDelay, CancellationToken cancellationToken, bool throwExceptionWhenCanceled) {
}

Task Delay(TimeSpan Delay, CancellationToken cancellationToken, bool throwExceptionWhenCanceled) {
}
Task Delay(CancellationToken cancellationToken, bool throwExceptionWhenCanceled) {
}


```

## Usage Examples
```
  await Task.Delay(5000, token, false);
```

## Alternative Designs
Today we use methods like this:
```
        public static async Task DelayAsync(TimeSpan Duration, CancellationToken Token = default) {

            try {
                if (Duration.TotalMilliseconds > Int32.MaxValue) {
                    Duration = Timeout.InfiniteTimeSpan;
                }

                if (Duration == Timeout.InfiniteTimeSpan || Duration > TimeSpan.Zero) {

                    await Task.Delay(Duration, Token)
                        .DefaultAwait()
                        ;
                }

            } catch (Exception ex) {
                ex.Ignore();
            }
        }
```

To make a safer Task.Delay, but it still results in an exception being thrown.  It would be nice if no exception would occur at all.

## Risks
None that I can think of.

**Comment by stephentoub** [comment]
Wanting to suppress exception throws isn't specific to Task.Delay. I'd rather see such a desire addressed by the ability to await a task without throwing,  i.e. https://github.com/dotnet/runtime/issues/22144. cc: @eiriktsarpalis

**Comment by carlossanlop** [comment]
Triage:
We think we should close this issue in favor of the more general solution: https://github.com/dotnet/runtime/issues/22144.
