### ISSUE TITLE
[WASM] AOT compilation on Windows

### ISSUE THREAD

**Issue by ivan-prodanov** [dotnet/runtime#45657]
I couldn't find where cross-platform support for the AOT tooling is tracked.

As far as I know AOT compilation for wasm apps is available on linux only right now (e.g what the Uno guys are doing). @danroth27 confirmed [here](https://github.com/dotnet/aspnetcore/issues/5466#issuecomment-736129759) that the plan for 6.0 is the tooling for AOT to work cross-platform. 

What's the current status on this?

**Comment by akoeplinger** [comment]
It is tracked as part of https://github.com/dotnet/runtime/issues/44316#issue-737134453 under "Workload pack for AOT cross compilers (Windows and macOS)"

Some of the foundational pieces to enable this will land with https://github.com/dotnet/runtime/pull/45545.
