### ISSUE TITLE
Facade assemblies contain dead SR strings

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#45665]
Eg., System.CodeDom.dll is a pure facade. It should be ~12KB but we build into it SR.cs which adds another 4KB.

If GenFacades ends up with an empty assembly, we should not include SR.cs.

**Comment by jkotas** [comment]
Duplicate of #28888 ?

**Comment by stephentoub** [comment]
Why doesn't SR get trimmed out by the line if it's not used? Does this issue only apply to assemblies on which we don't run the linker? Or does something end preventing the linker from removing it?

**Comment by danmosemsft** [comment]
Yes, it's a duplicate. Closing

> Why doesn't SR get trimmed out by the linker if it's not used? 

I don't know the answer - I guess we don't trim these ? cc @eerhardt

**Comment by eerhardt** [comment]
System.CodeDom is not in NetCoreApp (I.e. the shared framework) so we don’t trim it during the build.

**Comment by stephentoub** [comment]
> so we don’t trim it during the build

Any reason we don't just run the linker on every assembly we build,  regardless of whether it's in netcoreapp or not?

**Comment by danmosemsft** [comment]
@eerhardt for the question above.

**Comment by eerhardt** [comment]
> Any reason we don't just run the linker on every assembly we build, regardless of whether it's in netcoreapp or not?

Here was @ericstj's answer when he initially added this functionality in the 2.0 timeframe:

https://github.com/dotnet/corefx/pull/17825#commitcomment-29425831

**Comment by ericstj** [comment]
Copying here for better conversation: 
> It was a scoping decision back when we first added it. Folks weren't willing to test the output of things that weren't going in the shared framework (eg: UAP assemblies, packages that would be used by desktop, etc) so we constrained it to only the shared framework. Folks were confident that we had better test coverage of the shared framework since that's what we were shipping at the time. We could broaden that scope but we'd probably want to make sure such a change had decent test coverage + auditing of the new assemblies it touched across all their supported frameworks.

This still applies, we don't test all package configurations.  I think the linker is much more stable now and we could enable it.  I think when doing so we'd want to audit what it does to non-tested configurations.  That could be done with Assembly diffing.  If the changes the linker made matched those made to the netcoreapp build we could be reasonably confident that the netcoreapp build would remain a good proxy for the downlevel builds.  If we noticed any significant differences we could do targeted testing / investigation to ensure we have correct linker configurations for those configurations.  This will also enable the linker on completely OOB assemblies where it never ran before (CodeDom, System.Management, MEF, etc) and where we haven't invested in test coverage.  We'd want to do some manual diffing of these to validate that removals are safe, potentially adding test coverage to touch impacted codepaths.

Do folks think this effort is worth the cost?

**Comment by ViktorHofer** [comment]
Could we please move this discussion into a separate issue? Asking as the community can't participate in it as the issue is locked.

**Comment by ericstj** [comment]
Sure, opened here: https://github.com/dotnet/runtime/issues/47424
