### ISSUE TITLE
NET 5.0 NumberFormatInfo.NumberDecimalDigits change for en-US, en-GB, de-DE, fr-FR and other cultures

### ISSUE THREAD

**Issue by jasmh** [dotnet/runtime#45695]
The following code

`new System.Globalization.CultureInfo("en-US").NumberFormat.NumberDecimalDigits`

returns these results:

in .NET Core 3.1: 
2

in .NET 5:
3

It happens for en-GB, de-DE, fr-FR and probably many other cultures. For example, the value for hr-HR or InvariantCulture remains 2.

Is this by design? If so, why and what's the reasoning?

A lot of people are relying on those cultures behaving the same for years (since .NET 1.0 if I can recall correctly) and returning the same result for e.g. `someNumber.ToString("f")`. IMHO this is a huge break in backward compatibility.

**Comment by tarekgh** [comment]
@jasmh thanks for your question. Please have a look at the comment https://github.com/dotnet/runtime/issues/45308#issuecomment-735438395 which explain the change. also, you may consult the doc https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu for more info and how you can get the old behavior if you want which we don't recommend to do that if there is no strong reason to do that, the new behavior is what Unicode standard defined and would be good to stick with the standard.

feel free to send any more questions if you have any.

**Comment by jasmh** [comment]
Then how come it's different for en vs hr? 

In the ICU source code, if you check these:

https://github.com/unicode-org/icu/blob/master/icu4c/source/data/locales/en.txt
https://github.com/unicode-org/icu/blob/master/icu4c/source/data/locales/hr.txt

decimalFormat pattern is the same and has 3 digits by default.

**Comment by tarekgh** [comment]
@jasmh 

I am not sure of your question here, but if you run the code:

```C#
            Console.WriteLine($"en-US: {CultureInfo.GetCultureInfo("en-US").NumberFormat.NumberDecimalDigits}");
            Console.WriteLine($"en: {CultureInfo.GetCultureInfo("en").NumberFormat.NumberDecimalDigits}");
            Console.WriteLine($"ar: {CultureInfo.GetCultureInfo("ar").NumberFormat.NumberDecimalDigits}");
            Console.WriteLine($"hr: {CultureInfo.GetCultureInfo("hr").NumberFormat.NumberDecimalDigits}");
```

it produce the output 

```

en-US: 3
en: 3
ar: 3
hr: 3

```

Which matches the ICU data you pointed at and there is no difference.
