### ISSUE TITLE
comhost writes garbage data into default description entry in registry

### ISSUE THREAD

**Issue by nbelyh** [dotnet/runtime#45721]
Looks like there is a typo because of which comhost stub writes garbage data to the win32 default class registry key.

### Description

When registering comhost, you get garbage data in the default class entry. This causes other problems, this one for example:
https://github.com/wixtoolset/issues/issues/6275

### Configuration

.NET 5
Windows 10
x86

### Regression?

Not sure.

### Other information

The problem seems to be here:

https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/comhost/comhost.cpp#L263-L274

```cpp
    res = ::RegSetValueExW(
    regKey.get(),
    nullptr,
    0,
    REG_SZ,
    reinterpret_cast<const BYTE*>(entry.type.c_str()),
    static_cast<DWORD>(sizeof(entry.type.size() + 1) * sizeof(entry.type[0])));
```

Shouldn't it be this without 'sizeof', otherwise you always get 8??

```cpp
    reinterpret_cast<const BYTE*>(entry.type.c_str()),
    static_cast<DWORD>((entry.type.size() + 1) * sizeof(entry.type[0])));
```

**Comment by rseanhall** [comment]
Looks like that problem is duplicated later on at https://github.com/dotnet/runtime/blob/15460311833f161bbe90b61ef94a8f339178840b/src/installer/corehost/cli/comhost/comhost.cpp#L349 as well.

/cc @AaronRobinsonMSFT

**Comment by nbelyh** [comment]
Looks like this. 🤦 Should I make a PR?

**Comment by AaronRobinsonMSFT** [comment]
Bah. This is horrible. Will get a fix ASAP and I think we can justify servicing .NET 5.0 for this as well.

Thanks for reporting it.
