### ISSUE TITLE
CookieContainer.SetCookies "Path" parameter validation is case sensitive

### ISSUE THREAD

**Issue by dmitry007** [dotnet/runtime#45725]
CookieContainer.SetCookies "Path" parameter validation is case sensitive

HTTP paths are not case sensitive, therefore path validation should not be case sensitive either

var cookieContainer = new System.Net.CookieContainer();
cookieContainer.SetCookies(new System.Uri("http://localhost/sdata"), "name=value; path=/SData");

from https://github.com/dotnet/corefx/blob/master/src/System.Net.Primitives/src/System/Net/Cookie.cs#L513

 // Check current path (implicit/explicit) against given URI.
                if (!path.StartsWith(CookieParser.CheckQuoted(m_path)))

**Comment by wfurt** [comment]
URI it self has case sensitive Path AFAIK so I'm not sure why Cookies should be different. 
cc: @MihaZupan for more thoughts.

**Comment by MihaZupan** [comment]
> HTTP paths are not case sensitive

Paths are case-sensitive*.
Some applications may just sometimes consider them as case-insensitive.

For example if you change the `runtime` portion of this page's Uri to `RUNTIME`, you will be brought to the same page.
If you instead change the casing of `issues`, you will be met by a 404.

The scheme/host of a URI are case-insensitive.

*Percent-encoded data is considered case-insensitive (`%5A` should be treated the same as `%5a`)

[More URI-specific info](https://tools.ietf.org/html/rfc3986#section-6.2.2)

**Comment by dmitry007** [comment]
IIS is certainly NOT case sensitive when i comes to sites. 
No browser that I know of would reject a cookie that uses a "wrong" casing in the "Path" parameter.

**Comment by antonfirsov** [comment]
> No browser that I know of would reject a cookie that uses a "wrong" casing in the "Path" parameter.

Are you sure? Do you have any examples or other kind of proof?

Here is a chat I had with Chrome's dev console under a dummy website at `https://localhost:44326/lol/baz`:

![image](https://user-images.githubusercontent.com/6835152/101514814-fb9d0900-397d-11eb-914b-87784d29dc29.png)

This is the content of Application/Storage/Cookies in the very end:

![image](https://user-images.githubusercontent.com/6835152/101515229-69e1cb80-397e-11eb-824e-1f9c758c6b65.png)

**Comment by wfurt** [comment]
Implementations can choose to ignore casing - like IIS where file path is traditionally case insensitive e.g. foo.html and FOO.HTML would be the same. That is not true in general case.

**Comment by dmitry007** [comment]
Looks like you guys are right - both FF and Chrome are case sensitive with the Path attribute.

**Comment by wfurt** [comment]
I don't know if it would make any sense to make it configurable (new API) but for now I'll close this as it works as it should.
