### ISSUE TITLE
[Question] Background types preloader

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#45748]
Hello.

On Tizen startup time is critical and our perf analysis shows that type loader takes 1/3 of overall startup time on .NET 5 and 6 with r2r images. Currently, this area is not covered with any optimizations, and one approach could be https://github.com/dotnet/runtime/issues/45066. 

There is an alternative approach. I've prepared prototype of types profiler and background types preloader, which can gather and save profile with all loaded types during one launch, and then load types from this profile in background thread during application start on the other launch. Such profile contains only information about loaded types, not actual MethodTables. 

This approach allows to prepare types prior to the moment when they are going to be required and, thus, save time. In profile types are identified by their unique ids, TypeDef tokens, dll name, etc. With one background thread we see **11%-14% startup time improvement** with this approach on Tizen Xamarin apps on armel on dotnet/runtime 6.0 with r2r ni images. 

Some details on prototype:

1. Profile for each type load is saved at exit from ClassLoader::DoIncrementalLoad and ClassLoader::LoadTypeHandleForTypeKey (to handle higher level loads, which are not processed in DoIncrementalLoad). This way types will appear in profile in the same way (type, load level) they get out of DoIncrementalLoad/LoadTypeHandleForTypeKey. In some cases types will be somewhat reversed when this profile is loaded  (e.g. when one type implicitly leads to load of the other one, dependee type will already be loaded since it appears in profile first). Nevertheless, this doesn't seem to lead to any problems, since ClassLoader will just find already existing TypeHandle.

Examples of profile records:
- for non-generic ELEMENT_TYPE_CLASS: unique typeid, TypeDef token, load level, dll path
- for generic ELEMENT_TYPE_CLASS: uniqued typeid, TypeDef token, load level, dll path, unique typeids of all generic args
- for ELEMENT_TYPE_ARRAY and ELEMENT_TYPE_SZARRAY: unique typeid, load level, unique typeid of parameter, rank
- etc.

2. In coreclr_execute_assembly additional background thread is created, which loads specified profile and loads different types using next functions:
  a) ClassLoader::LoadGenericInstantiationThrowing for generics (ELEMENT_TYPE_CLASS)
  b) ClassLoader::LoadTypeDefThrowing for typical generic instantiations and non-generic types (ELEMENT_TYPE_CLASS)
  c) ClassLoader::LoadArrayTypeThrowing for arrays (ELEMENT_TYPE_ARRAY, ELEMENT_TYPE_SZARRAY)
  d) ClassLoader::LoadPointerOrByrefTypeThrowing for pointer types (ELEMENT_TYPE_PTR, ELEMENT_TYPE_BYREF)
  e) ClassLoader::LoadNativeValueTypeThrowing for native value types (ELEMENT_TYPE_VALUETYPE)
  
Additionally, formal parameters of typical generic instantiations are handled in a special way, so that types, which depend on them, can also be loaded.
  
What is your opinion on this approach? 
Also, could you, please, suggest, whether it is better to reuse MulticoreJit profile format or ibc pgo profile format for this?

cc @alpencolt @jkotas

**Comment by jkotas** [comment]
Can this be added to multicore JIT (e.g. use the same background thread as multicore JIT, same file as multicore JIT, etc.)?

**Comment by jkotas** [comment]
Maybe we can get almost the same benefit by letting multicore JIT to prepare the R2R code. It won't cover type loads from e.g. reflection, but those should be small fraction of all types loaded.

**Comment by gbalykov** [comment]
Answering your first question, yes, MulticoreJit and approach described here share some logic parts and initially I was going to implement production version of this reusing some part of MulticoreJit infrastructure. So, I'll continue with this approach, thanks.

Regarding your second suggestion, JIT will indeed also load all related types, however, there are some differences. Approach described here is somewhat orthogonal to any jitting time optimizations and will work with or without r2r ni images in the same way: loading all types, which will eventually be loaded. Hypothetically it can even work with additional MulticoreJit thread if required.

MulticoreJit, on the other side, behaves differently with and without ni images. When there are no ni images, all required methods will be saved to MulticoreJit profile and then will be jitted in background thread (thus, loading all required types). However, on embedded devices this approach can drain battery fast and uses too much CPU. So, it is much better to have some code stored on disk in ni images. With ni images many methods may still remain in tier0 (r2r code), thus, MulticoreJit won't save them to profile, won't jit them during next launch and won't load related types. This way only some subset of types will be loaded, reducing possible startup time improvement. Also, ideally we would like to have as little methods jitted in runtime during startup as possible, and MulticoreJit profile in such case will also be small. 

Additionally, simple type loads are lighter than jitting and seem to work better on devices with small amount of cpus.

In overall, types have to be loaded regardless of any approach to jitting time reduction. So, this approach seems to be better that plain MulticoreJit in our scenario.

**Comment by jkotas** [comment]
> With ni images many methods may still remain in tier0 (r2r code), thus, MulticoreJit won't save them to profile, won't jit them during next launch and won't load related types.

I believe that this behavior can be fixed. It is what I meant by "by letting multicore JIT to prepare the R2R code". It would just run the fixups for the R2R code that trigger most of the type loads.

**Comment by gbalykov** [comment]
> trigger most of the type loads

- During profiling MulticoreJit will additionally save info on all methods loaded from r2r image to profile (with some flag to not actually rejit them)
- During loading MulticoreJit will trigger type loads for methods from profile, which do not require jitting (and will trigger jit for other methods from profile, same as previously)

Did I understand you correctly?

Basically, the difference between approaches is in data that is saved (methods vs types). Thanks for the suggestion. I'll need some time to investigate this approach and check perf difference with the approach described above.

**Comment by jkotas** [comment]
Yes, that's the idea.

**Comment by gbalykov** [comment]
There are some problems with MultiCoreJit approach. 

1. Currently generic methods are saved/loaded-jitted in a completely different way than other methods (non-generic and canon instantiations). This includes saving them in separate section in MultiCoreJit profile, and then loading them only after all other methods are loaded. This doesn't preserve original load order of methods and, thus, will reduce effect of background type preload, the main idea of which is to load types prior to their usage. For example, on my prototype I see almost 2 times difference in startup time reduction when background thread deals with unneeded extra types (e.g. ones that are already loaded), i.e. is unable to load some types prior to their usage. In order to fix this, generics implementation in MultiCoreJit and, probably, other methods implementation has to be changed to preserve methods order.

2. Non-generic methods and canon instantiations in the same adjacent group are loaded-jitted in reverse order, which also doesn't preserve original order. But this behavior can be configurable, for example, using env variable, so not a big problem.

3. Methods loading-jitting itself doesn't preserve type load order. For example, when two consequent methods from MultiCoreJit profile require almost the same types, the second method will try to load already loaded types. This should be fast, yet, when there are many such methods, it would significantly reduce startup time reduction in comparison to plain type preloading, because plain types profile won't have the same type records twice. 

What do you think?

**Comment by jkotas** [comment]
> Currently generic methods are saved/loaded-jitted in a completely different way than other methods

It would be nice to fix this inefficiency for regular background JIT as well.

>  the second method will try to load already loaded types. This should be fast, yet, when there are many such methods, it would significantly reduce startup time reduction

Where do you see the extra time spent? I would expect that going over redundant type fixups is really fast (it is basically just a null check on the fixup entry).

**Comment by gbalykov** [comment]
> Where do you see the extra time spent?

This can be related to inefficiencies due to profile parsing in my prototype, so that each type record load takes too much time. If this is true, then already loaded type dependencies of methods stored in MultiCoreJit profile should be fast. I'll investigate this.

In order to check how methods loading approach would behave, implementation of generics and other methods needs to be modified first, so this will also take some time.

**Comment by jkotas** [comment]
Fixed by # #52595
