### ISSUE TITLE
CngKey.IsMachineKey is always false

### ISSUE THREAD

**Issue by bb-froggy** [dotnet/runtime#45759]
I have a CngKey object that refers to a machine-wide key on the Microsoft Platform Crypto Provider. However, the property IsMachineKey is false, where it should be true.

This issue occurs in .NET 4.8 and .NET Core 3.1 as well as .NET 5.0

I inspected System.Core for .NET 4.8 and .NET Core 3.1 and found that the property IsMachineKey checks whether the native property "Key Type" has the flag 0x20 set. The Microsoft documentation on NCRYPT_KEY_TYPE_PROPERTY says that it is 1 and not 0x20 (https://docs.microsoft.com/en-us/windows/win32/seccng/key-storage-property-identifiers). However, it also refers to the identifier NCRYPT_MACHINE_KEY_FLAG and claims it is 1, but it is indeed defined as 0x20 in ncrypt.h. In other places where NCRYPT_MACHINE_KEY_FLAG is used, 0x20 is the correct value; even for the property "Key Type" when the key is in the Microsoft Software Key Storage Provider instead of the Microsoft Platform Crypto Provider, the returned value is 0x20.

I am unsure as to whether this is a bug in the CNG documentation, in the Microsoft Platform Crypto Provider, in .NET or in all of them ;-).

Here is the minimal reproduction code: https://github.com/glueckkanja-pki/MachineKeyError/blob/master/Program.cs

BTW, this also effectively prevents the extension method CopyWithPrivateKey from working, as shown here: https://stackoverflow.com/questions/51522330/c-sharp-import-certificate-and-key-pfx-into-cng-ksp

**Comment by GrabYourPitchforks** [comment]
What happens if you close the newly-created key handle, then use `CngKey.Open` to reopen it? Is the _IsMachineKey_ flag properly set then? That is, is the incorrect behavior only observable when the key handle has been returned directly from `CngKey.Create`?

**Comment by vcsjones** [comment]
@GrabYourPitchforks This looks like a quirk of the "Microsoft Platform Crypto Provider". I can't reproduce it with the Software Key Storage Provider.

This prints False / False. Flip it to use `CngProvider.MicrosoftSoftwareKeyStorageProvider` and it prints True / True.

```c#
// Needs to run elevated.

using System;
using System.Security.Cryptography;

const string KeyName = "BananaKeys";
var provider = new CngProvider("Microsoft Platform Crypto Provider");

var key = CngKey.Create(
    CngAlgorithm.Rsa,
    KeyName,
    new() {
        KeyCreationOptions = CngKeyCreationOptions.MachineKey | CngKeyCreationOptions.OverwriteExistingKey,
        Provider = provider
    });

Console.WriteLine(key.IsMachineKey);

key.Dispose();

key = CngKey.Open(KeyName, provider, CngKeyOpenOptions.MachineKey);
Console.WriteLine(key.IsMachineKey);
```

**Comment by bb-froggy** [comment]
As vcsjones said, it is independent of whether the key is newly created or opened. It is because the Software Key Storage Provider returns "Key Type" 0x20 for a machine key, while the Platform Crypto Provider returns 1. Add this code to your example to see the difference:
```
CngProperty propMT = key.GetProperty("Key Type", CngPropertyOptions.None);
byte[] baMT = propMT.GetValue();
Console.WriteLine(baMT[0]);
```

Both 1 and 0x20 are kind of correct according to this documentation: https://docs.microsoft.com/en-us/windows/win32/seccng/key-storage-property-identifiers
The documentation says the property should be 1, but also says it is NCRYPT_MACHINE_KEY_FLAG, which is usually 0x20. So, the documentation is ambiguous and different KSPs seem to have interpreted it differently.

**Comment by bb-froggy** [comment]
And my reverse engineering tool says that IsMachineKey is implemented like this, so there is a direct connection:
```c#
public bool IsMachineKey
{
	[SecurityCritical]
	get
	{
		int propertyAsDWord = NCryptNative.GetPropertyAsDWord(this.m_keyHandle, "Key Type", CngPropertyOptions.None);
		return (propertyAsDWord & 32) == 32;
	}
}
```

**Comment by GrabYourPitchforks** [comment]
You don't need to reverse engineer it. The Full Framework sources are public. :)

https://referencesource.microsoft.com/#System.Core/System/Security/Cryptography/CngKey.cs,7f09f891a334d2f3

**Comment by bb-froggy** [comment]
What about we accept 0x20 as well as 0x01 in IsMachineKey? 

We could add MachineKeyAlternative to the enum CngKeyTypes and check for both values in IsMachineKey, like this:

```C#
        public bool IsMachineKey {
            [SecuritySafeCritical]
            get {
                Contract.Assert(m_keyHandle != null);
                int type = NCryptNative.GetPropertyAsDWord(m_keyHandle,
                                                           NCryptNative.KeyPropertyName.KeyType,
                                                           CngPropertyOptions.None);
 
                return ((CngKeyTypes)type & CngKeyTypes.MachineKey) == CngKeyTypes.MachineKey ||
                           ((CngKeyTypes)type & CngKeyTypes.MachineKeyAlternative) == CngKeyTypes.MachineKeyAlternative;
            }
        }
```

Both return values seem to exist in KSPs that ship with Windows, so we should accept both. Both values are unambiguous, too, as KeyType is used for nothing else currently.

Eventually, the KSP teams should also sort out whether 1 or 0x20 is the right value. I don't know whom to report this, though.

**Comment by GrabYourPitchforks** [comment]
I'll follow up with the crypto team and see what they recommend.

**Comment by Joe4evr** [comment]
> ```cs
> return ((CngKeyTypes)type & CngKeyTypes.MachineKey) == CngKeyTypes.MachineKey ||
>     ((CngKeyTypes)type & CngKeyTypes.MachineKeyAlternative) == CngKeyTypes.MachineKeyAlternative;
> ```

I feel like there should be a bit-twiddle that can do this in "one" operation (instead of `||`), but that bridge can be crossed after this is approved. 🙃

**Comment by GrabYourPitchforks** [comment]
IMO we shouldn't blindly accept both values unless the OS's crypto team tells us to do so. A less invasive change would be to switch on the KSP and select the appropriate mask based on the KSP. But will wait to see what the OS team recommends.

**Comment by bartonjs** [comment]
The latest I saw on this Windows claims that "it's fixed"... which I think means the platform KSP should be returning 0x20 / NCRYPT_MACHINE_KEY_FLAG now.  (And long enough ago that anyone not specifically on (e.g.) TH1-LTS should already have it)

Anyone care to verify?

**Comment by vcsjones** [comment]
It does seem fixed on Windows 11 (22000.194). Using my [repro above](https://github.com/dotnet/runtime/issues/45759#issuecomment-740789348), the output is now `True` + `True` instead of `False` + `False`.

**Comment by GrabYourPitchforks** [comment]
Given the recent OS updates, I'm tempted to resolve this issue as "external" and not try to work around it in vNext, especially since we aren't going to patch 4.8 / 3.1 / 5.0 / 6.0. I'd rather keep consistency within the frameworks than try to play whack-a-mole working around OS bugs.

Thoughts?

**Comment by bartonjs** [comment]
Sounds good to me
