### ISSUE TITLE
Cannot build runtime repo on Windows with ninja

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#45763]
Clean clone of the runtime repo, Windows 10, latest VS dogfood, running `build.cmd -ninja` from root:

```console
cl : Command line error D8016 : '/std:c++latest' and '/std:c11' command-line options are incompatible
cl : Command line warning D9025 : overriding '/TP' with '/TC'
```

while building `src/coreclr/pal/src/libunwind`

**Comment by jkotas** [comment]
cc @jkoritzinsky

**Comment by tommcdon** [comment]
@agocke @trylek

**Comment by trylek** [comment]
If this is due to some recent changes in the C++ compiler installed with the new VS, @janvorli may need to take a look to figure out the proper way to adjust the cmake files to be backward-compatible.

**Comment by agocke** [comment]
Reading the docs here, can we just disable `stdc` for `libunwind`? Since it specifies C++latest I assume it doesn't care about the C compatibility version

**Comment by agocke** [comment]
Well that seemed to work, but it looks like there's something wrong with the DAC: I get the error `The application to execute does not exist: 'C:/Users/andy/Code/runtime/artifacts/bin/coreclr/Linux.x64.Debug/DacTableGen/DacTableGen.dll'`

It looks like it's trying to consume a Linux DAC even though this is building on Windows. Do we build a cross dac by default?

**Comment by tommcdon** [comment]
> It looks like it's trying to consume a Linux DAC even though this is building on Windows. Do we build a cross dac by default?

+ @sdmaclea

**Comment by sdmaclea** [comment]
Yes this looks like it is due to building the linux cross dac for Windows.  I'll take a look.

**Comment by vitek-karas** [comment]
This is still not fully fixed for me - on latest master it fails with:
```console
     'C:/ProgramData/chocolatey/bin/ninja.exe' '-C' 'F:/dotnet/runtime2/artifacts/obj/native/net6.0-windows-Debug-x64' '-t' 'cleandead'

    failed with:

ninja : error : build.ninja:945: multiple rules generate System.IO.Compression.Native/System.IO.Compression.Native.lib [-w dupbuild=err] [F:\dotnet\runtime2\src\libraries\Native\build-native.proj]
```

**Comment by jkoritzinsky** [comment]
cc: @VSadov since he most recently changed how we build System.IO.Compression.Native

**Comment by VSadov** [comment]
The library was renamed on windows. It used to be `clrcompression` and now it is `System.IO.Compression.Native` - same as on Unix. That was basically the change.
I wonder if this could be related to the rename somehow?

**Comment by akoeplinger** [comment]
The System.IO.Compression.Native.lib issue was apparently fixed by https://github.com/dotnet/runtime/commit/5761dd49339911241209c1ffd61105a94edb6df1

**Comment by vitek-karas** [comment]
Now fails with a different error:
```console
 -- Build files have been written to: F:/dotnet/runtime2/artifacts/obj/native/net6.0-windows-Debug-x64
  [1/94] Building C object System.IO.Compression.Native\CMakeFiles\System.IO.Compression.Native.dir\F_\dotnet\runtime2\src\libraries\Native\AnyOS\brotli\common\context.c.obj
cl : Command line error D9025: overriding '/W0' with '/W3' [F:\dotnet\runtime2\src\libraries\Native\build-native.proj]
cl : Command line error D9025: overriding '/MDd' with '/MTd' [F:\dotnet\runtime2\src\libraries\Native\build-native.proj]
```

**Comment by akoeplinger** [comment]
Yeah I see the same here.
