### ISSUE TITLE
Add API to find MethodInfo on instantiated generic type from generic type definition

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#45771]
## Background and Motivation

Trying to invoke a method on a generic Type through reflection is not easy. The caller needs to find the method on the instantiated type in order to invoke it. Typically finding the method is done through `type.GetMethod("foo")`, which doesn't have a great performance characteristic.

Making such code trim-compatible is even harder because the ILLinker doesn't know exactly which method you are trying to find, since the Type is dynamic.

For example, trying to dynamically get the `Result` of a `Task<TResult>` object today is done with the following code:

https://github.com/dotnet/runtime/blob/7b90eac0175de4034572b57a42384a858a09d139/src/libraries/System.Private.Runtime.InteropServices.JavaScript/src/System/Runtime/InteropServices/JavaScript/Runtime.cs#L345-L354

Instead, we should have a method on `Type` that returns the invokable MethodInfo given the MethodInfo on the generic type definition.

## Proposed API

```diff
namespace System
{
    public class Type
    {
+        /// <summary>
+        /// Searches for the constructed generic member that matches the specified generic member definition.
+        /// </summary>
+        /// <param name="member">
+        /// The <see cref="MemberInfo"/> representing the generic definition of the member.
+        /// </param>
+        /// <returns>An object representing the member on the current constructed generic type that matches the specified generic definition, if found; otherwise, null.</returns>
+        public virtual MemberInfo? GetMemberFromGenericMemberDefinition(MemberInfo member);
    }
}
```

Note: The proposed name matches the existing API on MemberInfo [`bool HasSameMetadataDefinitionAs(MemberInfo other)`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.hassamemetadatadefinitionas)

## Usage Examples

The above example of getting the `Result` of a `Task<TResult>` object would then look like the following, which would be trim-compatible.

``` C#
class Runtime
{
    private static readonly MethodInfo s_getResultMethodInfo = typeof(Task<>).GetMethod("get_Result");

    public void Complete(Task task)
    {
        object? result; 
        Type task_type = task.GetType(); 
        if (task_type == typeof(Task)) 
        { 
            result = System.Array.Empty<object>(); 
        } 
        else 
        { 
            result = task_type.GetMemberWithSameMetadataDefinition(s_getResultMethodInfo)?.Invoke(task, System.Array.Empty<object>()); 
        } 
    }
}
```

See https://github.com/dotnet/runtime/pull/45727#discussion_r538179473 for the original suggestion for this API.

cc @MichalStrehovsky @GrabYourPitchforks @steveharter

**Comment by eerhardt** [comment]
@GrabYourPitchforks @steveharter - any thoughts on this API? We've now hit 2 places where this would be useful while annotating the dotnet/runtime libraries. Would you be opposed to moving this forward?

**Comment by steveharter** [comment]
This makes sense. A prototype and perf numbers would be a next step.

We could tighten the semantics to avoid confusion and ensure it is only applicable to obtain a member on a closed generic from an open generic, and not a closed to another closed, and not to address any sort of polymorphic\virtual method lookup:

```diff
namespace System
{
    public class Type
    {
        //<summary>Searches for the member that matches the specified generic member definition. This is faster than a name-based lookup.</summary>
+       public virtual MemberInfo? GetMemberFromGenericMemberDefinition(MemberInfo member);
    }
}
```

**Comment by eerhardt** [comment]
Here's another +1 for this method. In System.Linq.Expressions, we are getting the ConstructorInfo for `Nullable<T>`:

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/ILGen.cs#L827-L828

If we had this method, we could do this safely by statically referring to the ``Nullable`1`` open generic constructor. And then calling `typeTo.GetMemberFromGenericMemberDefinition(openGenericCtor)` to get the actual closed generic type's ctor.

**Comment by eerhardt** [comment]
I spent some time yesterday prototyping this API:

https://github.com/eerhardt/runtime/commit/88383857a6c253318f1014df39f74d613263f6ce

I'm not finding a super fast way to look up a member based on an existing member. From what I see `RuntimeType` in CoreCLR caches its members based on name (which makes sense, since most of the time people look up members based on name). Using a simple benchmark to test the scenario, I'm able to get the perf pretty close, but I guess I was hoping for parity (or better). Maybe the perf doesn't matter as much as long as it is close, since this will only be used in a few places listed above.

```C#
    [MemoryDiagnoser]
    public class GetMemberBenchmark
    {
        private static Type closedNullableType = typeof(Nullable<int>);
        private static MethodInfo openNullableGetValue = typeof(Nullable<>).GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public);

        [Benchmark]
        public MethodInfo OldWay()
        {
            return closedNullableType.GetMethod("get_Value", BindingFlags.Instance | BindingFlags.Public)!;
        }

        [Benchmark]
        public MethodInfo NewWay()
        {
            return (MethodInfo)closedNullableType.GetMemberFromGenericMemberDefinition(openNullableGetValue);
        }
    }
````

| Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|---------:|---------:|------:|------:|------:|----------:|
| OldWay | 38.25 ns | 0.044 ns | 0.034 ns |     - |     - |     - |         - |
| NewWay | 47.79 ns | 0.168 ns | 0.157 ns |     - |     - |     - |         - |

@steveharter @GrabYourPitchforks - any thoughts on the above?

**Comment by MichalStrehovsky** [comment]
Thank you for looking into this!

We'll probably see bigger differences when `GetMethod` is called with a list of parameter types because that one needs to compare signatures, but `GetMemberWithSameMetadataDefinition` can just keep doing the same work it's doing right now. We would also probably see better results with types that have many methods because `GetMemberWithSameMetadataDefinition` doesn't suffer from the "I need to throw `AmbiguousMatchException`". The benchmark you chose is probably least favorable for the proposed method :).

I wonder if we could make it fast enough for your case by just inlining what `HasSameMetadataDefinitionAs` is going to do:

https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/System.Private.CoreLib/src/System/Reflection/MemberInfo.Internal.cs#L10-L26

We can check whether the token and module of the owning type is the same once, and then just keep comparing tokens in the hot loop - it should remove a bunch of unnecessary work.

**Comment by eerhardt** [comment]
Another instance in System.Linq.Expressions. See : https://github.com/dotnet/runtime/pull/47803#discussion_r569704695.

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.Expressions.cs#L183-L186

**Comment by MichalStrehovsky** [comment]
@eerhardt Any opinion on also marking this blocking? It feels like we're going to inflict the suppression/dynamicdependency pains on the ecosystem if we don't add the API so this would be really nice to have.

**Comment by eerhardt** [comment]
I was holding off to "make room" for other features that are critical to get into Preview4 (which this missed by now since the snap is tomorrow).

If this doesn't come up in review in the next 2 weeks, I can mark it blocking. Would that be OK? It is really borderline for me as there are work-arounds right now (even though they aren't great).

**Comment by MichalStrehovsky** [comment]
Yup, I just want to make sure this can make it into 6.0 - this pattern looks common enough that people could hit this and I don't like having to tell customers to do suppressions. Incorrect suppressions can jeopardize the "app works fine after trimming if there's no warnings" experience and it's hard to get suppressions right. I want trimming to be a reliable experience.

**Comment by GrabYourPitchforks** [comment]
Unless the immediate experience is really poor, I'd hold off on marking it _blocking_. It's already near the top of [the backlog](https://apireview.net/backlog) since the backlog is ordered by milestone. But if you think it risks slipping and you're feeling some anxiety, definitely feel free to override and mark it blocking!

**Comment by eerhardt** [comment]
> I just want to make sure this can make it into 6.0 

I will make sure it makes 6.0.

**Comment by bartonjs** [comment]
* We feel that the name "GetMemberWithSameMetadataDefinitionAs" does a very good job of explaining that it's the same as HasSameMetadataDefinitionAs, but from a different perspective.

```C#
namespace System
{
    partial class Type
    {
        public virtual MemberInfo? GetMemberWithSameMetadataDefinitionAs(MemberInfo member);
    }
}
```
