### ISSUE TITLE
Deaklocks with "task based asynchronous pattern (TBAP)"

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45787]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/415866/deaklocks-with-task-based-asynchronous-pattern-tba.html)._

---
<p>Hello All,</p><p>One of the Achilles Heels of using Tasks is the notorious deadlock situation.  There are more than enough blogs on how to avoid it, but no one seems to understand how to identify (or explain how to identify) the cause of a deadlock.  There are new tools with VS 2017 such as the &quot;Tasks&quot; and &quot;Parallel Stack&quot; tools, but they fail to put a fine point on the offending tasks that are blocking each other.  </p><p>What we need is for VS to clearly:</p><ol><li>identify the dependency relationship between all tasks (if any).  Or identify tasks that are parented or deny child.  It would also be helpful if a metric could be identified that shows how many &quot;Attach&quot; request where denied by a &quot;Deny Child&quot; task for troubleshooting.</li><li>expose the number of &quot;WaitingForActivation&quot; tasks vs the max task threshold of tasks that can be created.  It should also abstract the details of the threshold such as when the tasks are based on the default ThreadPool TaskScheduler.</li><li>expose the time each thread entered into a &quot;waiting&quot; status so that we might be able to sort on this information.</li></ol><p>The above is just a few ideas that can greatly help us solve this commonly misunderstood issue. Better tool support in this area will help us identify issues we itroduced as well as issues created by third party vendors.  </p>

---
#### Jane Wu [MSFT] on 12/26/2018, 06:57 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>
#### Feedback Bot on 11/25/2019, 02:27 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### RiveraR on 11/25/2019, 07:23 PM: 

<p>I have another suggestion. If relationship information could be dumped to a file, than we could run a PowerShell script to pinpoint the root causes.  </p>

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
This request is about tooling in Visual Studio; there's little that can be done about such things in this repo.  If new tooling is to be exposed in Visual Studio and the information required for that tooling isn't surfaced, then specific requests could be made on the runtime to expose the relevant information.

> expose the number of "WaitingForActivation" tasks vs the max task threshold of tasks that can be created

There isn't a "max threshold" for tasks that can be created.  With 20/20 hindsight, WaitingForActivation was a poor choice of name for that enum value, but any task created as a promise starts life in this state, e.g. `new TaskCompletionSource()` creates a Task in the WaitingForActivation state, and you can have as many of those as memory will hold; at that point the Task is just a data structure.

> expose the time each thread entered into a "waiting" status so that we might be able to sort on this information

Events generated by the operating system already expose transitions in thread state.  It's how tools like the Concurrency Visualizer (https://marketplace.visualstudio.com/items?itemName=Diagnostics.DiagnosticsConcurrencyVisualizer2019) show swimlanes for threads and when they're blocked vs running.

> If relationship information could be dumped to a file, than we could run a PowerShell script to pinpoint the root causes.

As for relationship between tasks, causality is already traceable using the events that the task infrastructure generates.  It's how tools like PerfView and Visual Studio stitch together asynchronous call chains and the like.

**Comment by svick** [comment]
@stephentoub 

> With 20/20 hindsight, WaitingForActivation was a poor choice of name for that enum value, but any task created as a promise starts life in this state

Would it make sense to add an "alias" for that value with a better name? E.g.:

```c#
enum TaskStatus
{
    Initial,
    WaitingForActivation = Initial
}
```

I think this wouldn't be a breaking change, since all code that uses `WaitingForActivation` would continue to work, but you would see the new name in the debugger and other places. Or would changing it now be too confusing?
