### ISSUE TITLE
Crashes very often when running NUnit tests from Visual Studio for Mac

### ISSUE THREAD

**Issue by usr-sse2** [dotnet/runtime#45784]
### Description

Very often .NET 5 crashes when running NUnit unit tests from Visual Studio for Mac. .NET Core 3.1 is stable.

### Configuration

.NET version: 5.0.100
OS: macOS Big Sur 11.0.1 (20B29)
Arch: x64
Didn’t test on other machines

### Regression?

Yes, worked on 3.1.

### Other information

One of my tests deliberately tries to recurse with stack probing until an `InsufficientExecutionStackException` happens. I don’t know if it is the cause.
[dotnet_2020-12-08-235057_MacBook-Pro.log](https://github.com/dotnet/runtime/files/5661923/dotnet_2020-12-08-235057_MacBook-Pro.log)

**Comment by usr-sse2** [comment]
Another crash log, this time with segmentation fault
[dotnet_2020-12-09-192740_MacBook-Pro.log](https://github.com/dotnet/runtime/files/5667289/dotnet_2020-12-09-192740_MacBook-Pro.log)

**Comment by mangod9** [comment]
@usr-sse2 do you have repro? You might have to increase the stack size based on how deep the recursion is. 

cc: @janvorli

**Comment by janvorli** [comment]
In both cases, it crashed in SQLLite3, here is the top of the stack:
Case 1:
```
Thread 31 Crashed:
0   libsystem_kernel.dylib        	0x00007fff202f2462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff20320610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20273720 abort + 120
3   libsystem_malloc.dylib        	0x00007fff20154430 malloc_vreport + 548
4   libsystem_malloc.dylib        	0x00007fff20168702 malloc_zone_error + 183
5   libe_sqlite3.dylib            	0x000000010a538c91 sqlite3DbFree + 145
6   libe_sqlite3.dylib            	0x000000010a538b25 sqlite3VdbeClearObject + 485
7   libe_sqlite3.dylib            	0x000000010a54152c sqlite3_finalize + 108
8   ???                           	0x00000001145cac0f 0 + 4636584975
9   ???                           	0x00000001145cab29 0 + 4636584745
```
Case 2:
```
Thread 34 Crashed:
0   libsystem_pthread.dylib       	0x00007fff20309d9b pthread_mutex_lock + 4
1   libe_sqlite3.dylib            	0x000000010ee574ea sqlite3_finalize + 42
2   ???                           	0x0000000114d2abaf 0 + 4644318127
3   ???                           	0x0000000114d2aa89 0 + 4644317833
4   ???                           	0x0000000114d251e5 0 + 4644295141
```

So it seems like a problem with SQLite or some managed wrapper of it. In the first case, the error was `malloc: Non-aligned pointer 0x7fc4bcddb250 being freed (2)`.  The second crashed also down the call chain of `sqlite3_finalize`. My wild guess would be that the `sqlite3_finalize` was called with a wrong pointer argument - maybe missing pinning of data that the pointer points to or something like that.

**Comment by usr-sse2** [comment]
I’m currently using Microsoft.Data.Sqlite 2.1.0. I’ll update to 5.0.1 and test.

**Comment by mangod9** [comment]
Closing since this doesnt appear to a runtime issue.
