### ISSUE TITLE
Support HFA(float) stack passing.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#45780]
According to C++ tests (build natively on the target machine), HFA(float) requires a 4-byte alignment that contradicts with a standard 8-byte alignment for all structs on arm64. 

So when passing `Vector3 a, Vector3 b` on the stack they take 24 bytes, when on default arm64 it would take 32.
However, for a struct `Vector3int {int x; int y; int z; }` I see normal 8-byte alignment, so 2 of them are taking 32 bytes on the stack.

This behavior is not explicitly described in Apple docs ([Writing ARM64 Code for Apple Platforms](https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms)), so it would be nice to get a confirmation that it is expected.

The issue requires 3 things:

- [ ] Distinguish HFA(float) from `struct` when create argInfo and putArgs;

- [ ] Fix code in morph args (`fgInitArgInfo`) and codegen (`genPutArgStk`) that uses the assumption that SIMD12 arguments can be always propagated as SIMD16.

- [x] If we have to support non-rounded putArgs for arm64 apple it could be beneficial for other platforms to use as well, because now we create temporary copies

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by sdmaclea** [comment]
These are the failing tests for this issue
```
JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.sh
JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.sh
JIT/HardwareIntrinsics/General/Vector256/Vector256_r/Vector256_r.sh
JIT/HardwareIntrinsics/General/Vector256/Vector256_ro/Vector256_ro.sh
JIT/jit64/hfa/main/testA/hfa_nf2A_d/hfa_nf2A_d.sh
JIT/jit64/hfa/main/testA/hfa_nf2A_r/hfa_nf2A_r.sh
JIT/jit64/hfa/main/testA/hfa_sf2A_d/hfa_sf2A_d.sh
JIT/jit64/hfa/main/testA/hfa_sf2A_r/hfa_sf2A_r.sh
JIT/jit64/hfa/main/testB/hfa_nf2B_d/hfa_nf2B_d.sh
JIT/jit64/hfa/main/testB/hfa_nf2B_r/hfa_nf2B_r.sh
JIT/jit64/hfa/main/testB/hfa_sf2B_d/hfa_sf2B_d.sh
JIT/jit64/hfa/main/testB/hfa_sf2B_r/hfa_sf2B_r.sh
JIT/jit64/hfa/main/testC/hfa_nf2C_d/hfa_nf2C_d.sh
JIT/jit64/hfa/main/testC/hfa_nf2C_r/hfa_nf2C_r.sh
JIT/jit64/hfa/main/testC/hfa_sf2C_d/hfa_sf2C_d.sh
JIT/jit64/hfa/main/testC/hfa_sf2C_r/hfa_sf2C_r.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_d/hfa_nd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nd2G_r/hfa_nd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_d/hfa_nf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf2G_r/hfa_nf2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_d/hfa_sd2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sd2G_r/hfa_sd2G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_d/hfa_sf2G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf2G_r/hfa_sf2G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_d/hfa_nf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf0G_r/hfa_nf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_d/hfa_nf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_nf1G_r/hfa_nf1G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_d/hfa_sf0G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf0G_r/hfa_sf0G_r.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_d/hfa_sf1G_d.sh
JIT/jit64/hfa/main/testG/hfa_sf1G_r/hfa_sf1G_r.sh
JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
JIT/SIMD/Vector3Interop_ro/Vector3Interop_ro.sh
```
