### ISSUE TITLE
Http negotiate auth on macOS not working with SocketsHttpHandler

### ISSUE THREAD

**Issue by laceous** [dotnet/runtime#45785]
### Description

Http negotiate auth with default credentials fails on macOS Catalina 10.15.7 when using SocketsHttpHandler.

If I set UseSocketsHttpHandler=false with .NET Core 3.1 then it works. However, .NET 5 has removed this option, and it continues to fail with this version.

### Repro Steps

* Sign-in to Mac
* Sign-in to work VPN
* Enterprise Connect shows that I'm logged in
* Run `klist` in the terminal to check that everything's been initialized properly
* Run sample code below

### Sample Code

```c#
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace test
{
    class Program
    {
        static async Task Main(string[] args)
        {
            //AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);

            string url = "https://<domain>/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices&pullStatus=0";
            string urlLeftPart = new Uri(url).GetLeftPart(UriPartial.Authority);
            HttpClientHandler handler = new HttpClientHandler()
            {
                Credentials = new CredentialCache
                {
                    { new Uri(urlLeftPart), "Negotiate", CredentialCache.DefaultNetworkCredentials }
                }
            };
            HttpClient httpClient = new HttpClient(handler, true);
            httpClient.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0");
            try
            {
                HttpResponseMessage response = await httpClient.GetAsync(url);
                Console.WriteLine((int)response.StatusCode + " " + response.StatusCode.ToString());
                //Console.WriteLine(await response.Content.ReadAsStringAsync());
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
    }
}
```

Note: I've removed part of the URL since this only works if you're on a particular network.

This code works on Windows 10 (last tested w/ .NET Core 3.0), but fails on Mac unless I set UseSocketsHttpHandler=false.

### Errors

Running this code on Mac will produce one of these responses:

```
System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error -  An unsupported mechanism was requested.
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at test.Program.Main(String[] args) in /path/to/test/Program.cs:line 27
```

or

```
400 BadRequest
```

**Comment by wfurt** [comment]
Do you know if the Negotiate proposes NTLM, Kerberos or something else? 
Does it work if you do not use default credentials?

**Comment by laceous** [comment]
So a quick Google search tells me that
* `Authorization: Negotiate YII...` is Kerberos
* `Authorization: Negotiate TlR...` is NTLM

UseSocketsHttpHandler=false appears to be using Kerberos

It also seems to always use the Kerberos identity that `klist` shows me. For example, I can use all of these and I get the same login behavior:

```
CredentialCache.DefaultNetworkCredentials
new NetworkCredential("test", "test", "test")
new NetworkCredential()
```

It seems to ignore any user/pass/domain data here, which actually works for my needs.

SocketsHttpHandler's Authorization header doesn't match the data I see for Kerberos or NTLM, so I'm not sure what it's doing. Also, any combination of NetworkCredential objects I've tried doesn't seem to work.

**Comment by wfurt** [comment]
ok, that is good for triage. Did your macOS joined domain or how is the Kerberos ticket created? I did login as well (and run vpn) but the `klist` does not show anything. 
Is there chance you can try it with 5.0? There were some fixies in this area and even if nothing stands out as suspect, it would be good to confirm this is still happening with current version . We will probably need to reproduce to diagnose it further.

**Comment by laceous** [comment]
I have an app called Enterprise Connect that monitors the current network and integrates with active directory. When it notices it's on my work network it grabs a kerberos ticket.

**Comment by aik-jahoda** [comment]
I verified the authentication agains Sharepoint and it works as expected.

I have created ticket in Ticket Viewer and I'm able to reach the page with default credentials.

Can you please provide more info or create repro steps independent on Enterprise Connect?

**Comment by laceous** [comment]
Here's some more debugging info from my Mac (using `CredentialCache.DefaultNetworkCredentials`)

* net core 3.1
  * sockets handler
    * i've seen two behaviors
      1. client requests `IdpInitiatedSignOn.aspx`
      2. server sends 302 to `wia` (along with a couple URL params/cookies)
      3. client requests `wia`
      4. server responds back with 401 and `WWW-Authenticate: Negotiate` and `WWW-Authenticate: NTLM`
      5. client code errors with `System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error -  An unsupported mechanism was requested.`
    * or
      1. client requests `IdpInitiatedSignOn.aspx`
      2. server sends 302 to `wia` (along with a couple URL params/cookies)
      3. client requests `wia`
      4. server responds back with 401 and `WWW-Authenticate: Negotiate` and `WWW-Authenticate: NTLM`
      5. client requests `wia` with `Authorization: Negotiate YEg...`
      6. server responds back with 401 and `WWW-Authenticate: Negotiate oYI...`
      7. client requests `wia` with `Authorization: Negotiate oYI...`
      8. server responds back with 400
  * curl handler
    1. client requests `IdpInitiatedSignOn.aspx` with `Authorization: Negotiate YII...` (kerberos) header
    2. server sends 302 to `wia` (along with a couple URL params/cookies)
    3. client requests `wia` with `Authorization: Negotiate YII...` (kerberos) header
    4. server responds back with 200, and indicates it knows who i am
* net 5
  * sockets handler
    * i've seen the same two behaviors from 3.1

I don't want Enterprise Connect to become the sticking point. I assume other setups would run kinit manually, or have a script, etc. In my case, before connecting to VPN (and Enterprise Connect) `klist` shows

`klist: krb5_cc_get_principal: No credentials cache file found`

Once I connect then `klist` will show

```
Credentials cache: API:XXXX
        Principal: XXXX

  Issued                Expires               Principal
Jan  8 17:32:21 2021  Jan  9 03:32:21 2021  krbtgt/XXXX
Jan  8 17:32:21 2021  Jan  9 03:32:21 2021  ldap/XXXX
```

The principal name matches my username and curl handler's negotiate auth seems to take advantage of it. Is there some way to get sockets handler to pass through this kerberos info via negotiate auth? Maybe some value besides `CredentialCache.DefaultNetworkCredentials`?

**Comment by aik-jahoda** [comment]
The pre-authentication in sockets handler is supported only form 'BASIC' auth. This is why you see difference in headers in curl and SocketsHttpHandler. However the 401 response should be processed with new request with `Negotiate` `WWW-Authenticate` header. 

Is the issue reproducible on different mac machine?

I can't reproduce it locally, it would be helpful if you can collect more logs as in the following example: https://github.com/aik-jahoda/45785-auth/ . It produces 2 files:
 * test.pcap - capture trafic in plain text
 * log.txt - collection all information from .net telemetry

Feel free to send the files directly to me if you are concern about sensitive data.

**Comment by wfurt** [comment]
Perhaps also try to reproduce it with Ticket View @laceous as that is standard part of OS so it would be easier to investigate and compare notes,

**Comment by laceous** [comment]
For reference, this was where I found that `YII` was Kerberos
* https://stackoverflow.com/questions/5597573/how-to-find-if-ntlm-or-kerberos-is-used-from-www-authenticate-negotiate-header

The only two working examples where I've seen this working are
* my code above using curl handler
* and some python code that was also sending through a preemptive kerberos auth header

This mentions that `oY` is spnego (seen in the sockets handler trace above)
* https://stackoverflow.com/questions/24454777/windows-authentication-kerberos-or-ntlm-negotiate-oyico

It may be that the server I'm trying to connect to only supports the `YII` style header.

I didn't set preauth=true. I'm assuming that was a quirk of the curl handler.

I'll take a look at the linked code.

----

Also FYI, Enterprise Connect appears to be an Apple pro-services developed product
* https://www.reddit.com/r/macsysadmin/comments/5gn3ky/apple_enterprise_connect_who_uses_it/
* https://www.jamf.com/jamf-nation/discussions/17757/about-enterprise-connect

**Comment by wfurt** [comment]
The `preauth` is not relevant here. SocketsHttpHandler will do nothing there for Negotiate/Kerberos. Could you do packet captures for working & not working case with [Wireshark](https://www.wireshark.org/#download) and either post them here or send them to my GH email. 

I think it is critical for us to reproduce this so we can investigate. It is not easy for us to try it with EC. That is main reason why I asked you for the test @laceous. It may not give different answer but at least we would be on some setup. I hope it make sone sense.  

Reading this again, the '400 BadRequest' is certainly suspicious. It would be great of you can capture that. I could see that the authentication may not work but it should not throw or fail like this. There may be something unique in your environment.

**Comment by wfurt** [comment]
It looks like our new VPN creates ticket now,
```
Shining:projects furt$ klist
Credentials cache: API:2865B132-9DF8-4B16-88A4-4B856C97D583
        Principal: wfurt@CORP.MICROSOFT.COM
```
and accessing protected URL works as expected - tested with IIS
```
result=StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Accept-Ranges: bytes
  ETag: "528e858b81cd51:0"
  Server: Microsoft-IIS/10.0
  WWW-Authenticate: Negotiate oRQwEqADCgEAoQsGCSqGSIb3EgECAg==
  Persistent-Auth: true
  Date: Sat, 15 Jan 2022 00:28:23 GMT
  Content-Type: text/html
  Last-Modified: Thu, 06 Jun 2019 22:34:41 GMT
  Content-Length: 10
}
```

tested on 11.6 with .NET 6. 

At this point, I don't see reason to keep this open as it is not actionable. 
If it still does not work for you @laceous, send me full logs and capture to my GH email.
