### ISSUE TITLE
Rotate Circular Shift With Carry for bitwise operations

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45795]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1149575/rotate-circular-shift-with-carry-for-bitwise-opera.html)._

---
<p>Hello please provide,</p><p>Rotate Circular Shift With Carry for bitwise operations, it is needed for developers.</p> <p>*Thanks*</p>

---
#### Dada Huo [MSFT] on 8/14/2020, 00:56 AM: 

<p>Hello, Bitwise Operations is all Projects or specific projects? If it is a specific, which project(C# conosle, C++ , <a target='_blank' href="http://asp.net">asp.net</a>, web),It would be very helpful if you could provide some screenshots or other related attachments.</p>

#### Touraj Ostovari on 8/14/2020, 06:20 AM: 

<p>C# Console</p>

#### Touraj Ostovari on 8/15/2020, 05:13 AM: 

(private comment, text removed)

**Comment by TourajOstovari** [comment]
we want have Circular binary shift on .Net 5

**Comment by tannergooding** [comment]
We already expose `BitOperations.RotateLeft` and `BitOperations.RotateRight`. Could you please clarify if you are looking for something additional?

**Comment by TourajOstovari** [comment]
Yes, sir I saw it.
but we should be able give bitarray to the method's arguments and method do Rotate Circular shift to the bitarray, while pointed method is earning number not a bitarray.
if you be able develop fast and extension method like for bitarray would be great.
Thanks for your reply sir.
I am happy for having bitarray because I am doing cryptography tasks too.
(I want to give method mine bitarray and times should rotate it)

**Comment by tannergooding** [comment]
Just to confirm, you are saying you want `RotateLeft` and `RotateRight` methods for `System.Collections.BitArray`?

**Comment by TourajOstovari** [comment]
Yes sir.
I want to do  have rotate circular shift for the bitarray.
Please add some comments to other shift methods of bitarray.
I do not know what is it doing?! I am pointing already available right and left shifts for the bitarray collection that what they are doing! Are they logical bit shift array?!

**Comment by TourajOstovari** [comment]
When would you add this feature to bitarray?

**Comment by tannergooding** [comment]
The API review process is detailed here: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

Before I can mark the issue ready for API review someone will need to write up the proper proposal following the template given in the docs above (https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md). I can then mark this (or the new issue) as `api-ready-for-review`.

**Comment by TourajOstovari** [comment]
is there anything on my side to do?
how may I help to see process faster is done!?

**Comment by tannergooding** [comment]
> how may I help to see process faster is done!?

You could write up a proposal detailing the exact APIs you'd like to see exposed (using the template given above). Otherwise, it will go on the general backlog for myself or some other interested party to eventually create the proposal.

**Comment by TourajOstovari** [comment]
https://github.com/dotnet/runtime/issues/46668
check the link, thanks...
I need it please provide it as soon as possible with high performance because I want use it in my cryptography, I wrote same code but works heavy.
Thanks a lot man.

**Comment by TourajOstovari** [comment]
https://github.com/dotnet/runtime/issues/46669

**Comment by tannergooding** [comment]
> I need it please provide it as soon as possible

It would be available in .NET 6 at the earliest. If you need functionality earlier, you should be able to emulate it using something like:
```
public static BitArray RotateLeft(this BitArray value, int offset)
{
    var tmp = new BitArray(value);
    return value.ShiftLeft(offset).Or(tmp.ShiftRight(tmp.Length - offset));
}
```

Noting that I've not validated the correctness of this, just providing an example that should likely work given how rotations are typically implemented.
Also noting that this involves an allocation and a copy, which will only be elidable by a built-in implementation.

**Comment by tannergooding** [comment]
I'm going to close this in favor of tracking #46669 since there is nothing else that can be done in this issue.
