### ISSUE TITLE
Prime Number Generator

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45793]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1155829/prime-number-generator.html)._

---
<p>Hello, it is better to have a class in C# .Net Core and Framework that generates Prime Numbers also it takes range of numbers for generating prime numbers...</p> <p></p><p>*Thanks * </p>

---
#### Feedback Bot on 8/20/2020, 01:37 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by GrabYourPitchforks** [comment]
TBH I don't see much benefit to this proposal. If you want to generate small-ish prime numbers, a sieve routine would work just fine. If you want to generate extremely large prime numbers (e.g., for cryptography), there are efficient algorithms for accomplishing this. In either case, the correct manner of choosing prime numbers is really dependent on the target scenario, and in all cases there are existing libraries or techniques available for pulling this off.

**Comment by pgovind** [comment]
+1 on what @GrabYourPitchforks says. I don't think that usage of a prime number generator is common enough to be part of the BCL. IMO, this issue can be closed, but I'll let @tannergooding have the last word.

**Comment by tannergooding** [comment]
I agree. I think this is something that can be handled by a 3rd party library/package.
