### ISSUE TITLE
Keeping security protocol in a public static variable

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45792]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Keeping-security-protocol-in-a-public-st/1266734)._

---
<p>If you use a WebClient and connect to a https address, you might sometimes get an exception that you could not establish a SSL/TLS secure channel. Sometimes however, you succeed.</p><p>The sad truth is that if you use this web client in a web application thread, there is a global variable that in some cases could happen to contain the corrrect value and that is why you succceed. It will then have the right content from an earlier thread execution.</p><p>The name of that variable is ServicePointManager.SecurityProtocol.</p><p>I had a case where I had to set it:</p><p>ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;</p><p>before I create try to connect with the web client.</p><p>Security is a hard topic even without magic and variables that lives across thread executions are magical.</p><p>How thread secure is this variable by the way?</p><p> Please Microsoft, redesign this so that the ServicePointManager.SecurityProtocol variable is ignored. (Everyone wants the most recent/secure protocol anyway).</p><p>Thanks in advance! /Anders</p>

---
#### Feedback Bot on 11/23/2020, 10:43 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by wfurt** [comment]
ServicePointManager is really irrelevant for .NET Core. You should use  SslProtocols.None to let OS to pick best possible option. 

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls

**Comment by karelz** [comment]
Triage: As mentioned above, our recommendation is in the linked article, and everyone should use `SslProtocols.None`
