### ISSUE TITLE
Introduce a new method to Task class

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45791]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/978741/introduce-a-new-method-to-task-class.html)._

---
It would be so useful to have a method in the Task class that would allow us to repeat an Action every interval.
Maybe an extenstion to Task.Delay which accepts some options and even an Action/Func that would be called repeatedly.

---
#### Feedback Bot on 4/7/2020, 03:05 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by tarekgh** [comment]
Please open a new issue with the complete proposal. You may consult the doc https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md for how you can create such proposal. Thanks.

**Comment by stephentoub** [comment]
As described, I'm also not sure how this differs from `new Timer(...)`, which does support invoking a delegate after a specified period of time and then on some specified interval after that.
