### ISSUE TITLE
BigInteger class, missing function sqrt

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45798]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/833537/biginteger-klasse-fehlende-funktion-sqrt.html)._

---
Unfortunately, the BigInteger class contained in System.Numerics does not contain a root-pulling function (sqrt).
Is there a reason for the missing function?

I created a class that provides this feature.

The class provides 2 functions:

Public Function sqrt(number As BigInteger) As BigInteger 
Public Function sqrt(number As BigInteger, ByRef rest As BigInteger) As BigInteger

The implementation uses the Heron method.

Runtime tests have shown the following values (Intel I5-8400 CPU, 2.8 GHz)

Numbers up to 1,000 digits: x 0.1 ms
Numbers up to 10,000 digits: .3 ms
Numbers up to 100,000 digits: x 300 ms
Numbers up to 500,000 digits: x 8 sec.

Above that, the values are rising sharply.

Are you interested in the source code (Visual Basic or C) ?
Is it conceivable to be included in the BigInteger class?

---
#### Feedback Bot on 11/26/2019, 01:53 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.
#### werner.rams on 12/2/2019, 00:21 PM: 

Bei dem Wert Zahlen bis 10.000 Ziffern muss es lauten:<br>Zahlen bis 10.000 Ziffern: &lt;3 ms<br>Sorry f&#252;r den Tippfehler.<br>Hier mal das Ergebnis eines Laufzeittests:<br><br>Zeitmessungen (Laufzeit) : Anzziffern: 10, 100, 1000, 10000 - 200000 in 10000-er Schritten<br>                                                       <br>Z10       , Anz:          1 , Zeit :           0,154 ms<br>Z100      , Anz:          1 , Zeit :           0,032 ms<br>Z1000     , Anz:          1 , Zeit :           0,091 ms<br>Z10000    , Anz:          1 , Zeit :           3,480 ms<br>Z20000    , Anz:          1 , Zeit :          12,526 ms<br>Z30000    , Anz:          1 , Zeit :          27,411 ms<br>Z40000    , Anz:          1 , Zeit :          48,282 ms<br>Z50000    , Anz:          1 , Zeit :          75,664 ms<br>Z60000    , Anz:          1 , Zeit :         108,839 ms<br>Z70000    , Anz:          1 , Zeit :         147,642 ms<br>Z80000    , Anz:          1 , Zeit :         192,057 ms<br>Z90000    , Anz:          1 , Zeit :         242,333 ms<br>Z100000   , Anz:          1 , Zeit :         299,765 ms<br>Z110000   , Anz:          1 , Zeit :         369,929 ms<br>Z120000   , Anz:          1 , Zeit :         448,703 ms<br>Z130000   , Anz:          1 , Zeit :         528,018 ms<br>Z140000   , Anz:          1 , Zeit :         609,487 ms<br>Z150000   , Anz:          1 , Zeit :         705,594 ms<br>Z160000   , Anz:          1 , Zeit :         810,917 ms<br>Z170000   , Anz:          1 , Zeit :         910,101 ms<br>Z180000   , Anz:          1 , Zeit :       1.013,581 ms<br>Z190000   , Anz:          1 , Zeit :       1.136,734 ms<br>Z200000   , Anz:          1 , Zeit :       1.255,283 ms<br>                                                       <br>                                                       <br>Ende der Pruefung, bitte Taste druecken

**Comment by svick** [comment]
How does square root make sense for `BigInteger`, when the result is inherently not an integer?

**Comment by GSPP** [comment]
> root-pulling function

I can tell that you are German 😄

**Comment by pgovind** [comment]
+1 on @svick's question. What are you trying to do with the result of your `sqrt`? 
What do you expect the return type to be? 

To get a more substantive discussion here, it might be worth putting up a draft API and an example of it's usage :)

**Comment by verelpode** [comment]
> How does square root make sense for BigInteger, when the result is inherently not an integer?

I don't know what the original poster wanted it for, but I can say that sometimes integer versions of square root are useful.  To pick one random example, here is a way of determining whether a number is a prime number, with the help with an integer version of square root: 

```cs
bool IsPrimeNumberSlow(uint candidate)
{
	uint limit = IntegerSquareRoot(candidate);
	for (uint divisor = 3; divisor <= limit; divisor += 2)
	{
		if ((candidate % divisor) == 0) return false;
	}
	return true;
}

uint IntegerSquareRoot(uint x)
{
	// ... Wurzeln ausreissen, und so weiter ...
}
```

I'm not saying it's common.  Admittedly it might be rare.  I'm just saying at least *sometimes* it is useful, but I don't know how often.

**Comment by AraHaan** [comment]
hmm interesting an int sqrt 🤔 but how is it useful for everyone using .NET over providing their own sqrt?
