### ISSUE TITLE
Update TcpListener/TcpClient to accept any EndPoint in the constructor.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45796]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/875092/update-tcplistenertcpclient-to-accept-any-endpoint.html)._

---
Currently TcpListener requires an IP Endpoint, a Port or a Port and an Address in the constructor; similarly for TcpClient

Now with .Net Core 3.1 (maybe earlier) there exists UnixDomainSocketEndpoints.  When I write Unix Domain Sockets in C++ it works minus the minor setup differences exactly like a TCP connection.  I am making a variant of a working C# Tcp Client/Server that uses Unix Domain Sockets.  If the constructors accepted any endpoint then I could pass in UnixDomainEndpoints and be done.

---
#### Feedback Bot on 1/6/2020, 00:47 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by karelz** [comment]
Triage: Abstraction would be ok, but it does not seem to fit `TcpListener`/`TcpClient` classes.
Workaround is to use `Socket` and `NetworkStream` directly, which is about the same amount of code a dev using the abstraction would have to write anyway. Closing as low benefit.
