### ISSUE TITLE
Unicode Regular Expression for Japanese characters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45805]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/795335/unicode-regular-expression-for-japanese-characters.html)._

---
Under Unicode standard, notations like \p{Hiragana}, \p{Katakana}, \p{Han} and \p{Latin} are defined.  But, under .NET, these notations are not allowed to use in System.Text.RegularExpressions.  I'd like you to adopt the standard notations sooner. For your information,

\p{Han] is equivalent of the pattern "[\u3402-\uFA6D]+"
\p{Hiragana} is of "[\u3041-\u30A0]"
and \p{Katakana} is of "[\u30A0-\u31FF]"
As for \p{Latin}, please examine the code range at your side.

With best regards,
Yosuke

---
#### Feedback Bot on 10/28/2019, 01:29 AM: 

Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by danmosemsft** [comment]
Our list is apparently[ "based on Unicode 4.0 and Perl 5.6" ](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#supported-named-blocks)

[This ](https://perldoc.perl.org/perluniprops) seems to be the latest Perl list - it's pretty large and also includes many constructs we don't attempt to support such as `\p{Block: ...` But `\p{Katakana}` etc are there. Question is, if we added some, what would be the list?

**Comment by svick** [comment]
@danmosemsft As far as I can tell, the Unicode spec for that is [here](https://www.unicode.org/reports/tr18/#Categories).

**Comment by danmosemsft** [comment]
Thanks. Probably the next step is for someone interested in this to propose a list of additions based on some authoritative source such as that.

The specific additions alone seem reasonable, although I don't believe they would qualify for servicing.NET Framework, which is what the reporter is using.

**Comment by pgovind** [comment]
1. I see `IsHiragana` and `IsKatakana` in our list of supported name block [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#supported-named-blocks).
2.  I also see basic Latin, supplement Latin and Extended Latin listed as supported named blocks.
3. I don't think we support `Han` though. 

This is a great issue for someone to contribute to the regex library. IIRC, all we need to do to add support for new char classes is to add the appropriate line in the s_propTable [here](https://source.dot.net/#System.Text.RegularExpressions/System/Text/RegularExpressions/RegexCharClass.cs,143) and add unit tests to test the new range! I wouldn't mind if each addition came as a new PR.

**Comment by danmoseley** [comment]
Closing in favor of #57038 as there is more discussion there.
