### ISSUE TITLE
System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success long running on Mono

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#45810]
```
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 898 of 1327 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 12)
    System.Net.Sockets.Tests.UdpClientTest.Finalize_NoExceptionsThrown [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.Net.Sockets.Tests.DisposedSocket.NonDisposedSocket_SafeHandlesCollected [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Supported_Success [SKIP]
      Condition(s) not met: "SupportsRawSockets"
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:02:12
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:04:13
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:06:14
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:08:15
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:10:16
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:12:17
   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.DualModeBeginAccept.BeginAcceptV4BoundToAnyV4_Success', Elapsed: 00:14:18
```

Hit on: https://github.com/dotnet/runtime/pull/45802
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45802-merge-761c5bb4146544a9aa/System.Net.Sockets.Tests/console.0d8feb58.log?sv=2019-07-07&se=2020-12-29T00%3A18%3A01Z&sr=c&sp=rl&sig=hSdOsA1wGfBtq0CeRNf93Z36yIUT3XBRYh6x6u3m5Qw%3D

**Comment by safern** [comment]
Disabling on: https://github.com/dotnet/runtime/pull/45811

**Comment by karelz** [comment]
@marek-safar who can help to triage this issue?

**Comment by marek-safar** [comment]
There are no details about the error (the log is gone) to see if it could be MonoVM related or not.

**Comment by antonfirsov** [comment]
Looks like listening on `0.0.0.0` doesn't result in a successful connection despite the connection attempt on `127.0.0.1`. To me it seems like a configuration issue specific to a CI machine.

**Comment by wfurt** [comment]
I'm wondering if we should add some time boxing so it does not hang and enable it again to get more data.

**Comment by antonfirsov** [comment]
> I'm wondering if we should add some time boxing so it does not hang and enable it again to get more data.

Makes sense to me, not a big fan of aggressive test disabling.

**Comment by antonfirsov** [comment]
I re-enabled this 17 days ago, and I don't see any timeouts or hangs since then on Kusto. Closing for now, we can open an new issue if a timeout or hang happens again.
