### ISSUE TITLE
Add analyzer: Interlocked.Exchange when return value unused

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/runtime#45826]
Today I came across a property setter which was implemented as:

```c#
set
{
    Interlocked.Exchange(ref this.someField, value);
}
```

I cannot think of a valid reason to use `Exchange` in this scenario, or in any scenario where the return value is unused.

My understanding is that this could be more simply written as `Volatile.Write`.

Perhaps an analyzer could flag usages such as this.

**Comment by gfoidl** [comment]
The `Volatile.Write` produces a "half fence", that guarantees 
>  If a read or write appears before this method in the code, the processor cannot move it after this method. [source](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile.write?view=net-5.0)

But it's allowed to move it before. Thus the `Interlocked.Exchange` must be used to prevent this, as it produces a "full fence", that prevents reads and writes to be reordered in respect to the exchange (write).

It's about visibility.

(That some methods of Volatile.Write use Interlocked.Exchange internally is a implementation detail).

**Comment by stephentoub** [comment]
Right, Interlocked.Exchange is often used for its full memory barrier semantics.  We wouldn't want to add an analyzer warning against its use in this manner.
