### ISSUE TITLE
SimpleConsole logger provider doesn't use IncludeScopes from Configuration

### ISSUE THREAD

**Issue by PavelStefanov** [dotnet/runtime#45830]
### Description
Hi!

I use default host builder for workers and web apps, and before .NET 5.0 I always use usual Console logger provider for logging in console and I can configure it via configuration, eg I set `"Logging:Console:IncludeScopes"` as true and it works well. 
But in .NET 5.0 I started use SimpleConsole logger and it has `IncludeScopes` property in `SimpleConsoleFormatterOptions` and if I set it in true it'll works well as usual, but when I try to configure it via configuration it doesn't work, SimpleConsole just ignores that setting from configuration.

My code example:

``` csharp
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace SimpleConsole
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureLogging(loggerBuilder =>
                {
                    loggerBuilder
                        .ClearProviders()
                        .AddSimpleConsole();
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }

    public class Worker : BackgroundService
    {
        private readonly ILogger<Worker> _logger;

        public Worker(ILogger<Worker> logger)
        {
            _logger = logger;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                using (var scope = _logger.BeginScope(new
                {
                    Id = 1
                }))
                {
                    _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                    await Task.Delay(1000, stoppingToken);
                }
            }
        }
    }
}
```

if I add `.AddSimpleConsole(o => o.IncludeScopes = true)` I'll get next output

```
info: SimpleConsole.Worker[0]
      => { Id = 1 }
      Worker running at: 12/09/2020 13:43:06 +03:00
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Projects\Tests\SimpleConsole
info: SimpleConsole.Worker[0]
      => { Id = 1 }
      Worker running at: 12/09/2020 13:43:08 +03:00
```

You can see there are scopes.
But if I try use configuration instead and add
```
.ConfigureHostConfiguration(configurationBuilder =>
{
    configurationBuilder.AddInMemoryCollection(new Dictionary<string, string>
    {
        //  Just try any name of provider
        {"Logging:SimpleConsole:IncludeScopes", "true"},
        {"Logging:Console:IncludeScopes", "true"},
        {"Logging:Simple:IncludeScopes", "true"},
    });
})
```
I'll get next one

```
info: SimpleConsole.Worker[0]
      Worker running at: 12/09/2020 13:46:04 +03:00
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Projects\Tests\SimpleConsole
info: SimpleConsole.Worker[0]
      Worker running at: 12/09/2020 13:46:05 +03:00
info: SimpleConsole.Worker[0]
      Worker running at: 12/09/2020 13:46:06 +03:00
```

As you can see there aren't scopes.

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Regression?

I think yes

**Comment by maryamariyan** [comment]
> when I try to configure it via configuration it doesn't work, SimpleConsole just ignores that setting from configuration.

Here's a link to doc on the deprecations and description of what's new: https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter

As shown in the docs, in configuration you need to add IncludeScopes under FormatterOptions, e.g.:

```json
    "Console": {
      "FormatterName": "simple",
      "FormatterOptions": {
        "TimestampFormat": "[HH:mm:ss] "
      }
    },
```

**Comment by PavelStefanov** [comment]
Oh, thanks!
Sorry I was not attentive, this breaking change is also there https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0
