### ISSUE TITLE
JIT/HardwareIntrinsics/X86/* crossgen2 test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#45852]
Lots of failures across all platforms of JIT/HardwareIntrinsics/X86/* tests, in crossgen2 test jobs:

https://dev.azure.com/dnceng/public/_build/results?buildId=912046&view=ms.vss-test-web.build-test-results-tab

https://dev.azure.com/dnceng/public/_build/results?buildId=912047&view=ms.vss-test-web.build-test-results-tab

Possibly related to https://github.com/dotnet/runtime/pull/45662?

@jkotas @dotnet/crossgen-contrib

**Comment by BruceForstall** [comment]
cc @tannergooding

**Comment by jkotas** [comment]
I am taking a look
