### ISSUE TITLE
X86 R2RDump cannot load coredistools on x64 machine

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#45857]
OS: Windows
Architecture: x86

The managed R2RDump project needs to be tweaked so that, in x86-targeting build, its PE header forces 32-bit execution. Today it's run under the x64 runtime on an x64 machine and subsequently it cannot load the x86-targeting coredistools.dll with the error

<pre>
d:\git\runtime>artifacts\bin\coreclr\windows.x86.Release\R2RDump\r2rdump.exe --header --disasm --gc --sc --in artifacts\bin\coreclr\windows.x86.Release\System.Private.CoreLib.dll --out d:\triage\SPC-new-raw.r2r
Error: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at R2RDump.CoreDisTools.InitBufferedDisasm(TargetArch Target)
   at R2RDump.CoreDisTools.GetDisasm(Machine machine) in D:\git\runtime\src\coreclr\src\tools\r2rdump\CoreDisTools.cs:line 81
   at R2RDump.R2RDump.Run() in D:\git\runtime\src\coreclr\src\tools\r2rdump\R2RDump.cs:line 581
</pre>

@dotnet/crossgen-contrib

**Comment by MichalStrehovsky** [comment]
I think deleting this line would make it a x86 executable on x86 builds:

https://github.com/dotnet/runtime/blob/8e29c00ac515e6ada57722dc2cb981c2fa977266/src/coreclr/tools/r2rdump/R2RDump.csproj#L8

**Comment by trylek** [comment]
Thanks Michal for the suggestion; I tried that out but no E2E success so far:

1) When compiled with the project change you suggested, <code>r2rdump.dll</code> can no longer be run through the <code>dotnet.cmd</code> script. This is probably expected as the default dotnet host installed on an x64 machine is 64-bit and fails to run the 32-bit assembly. Running <code>r2rdump.exe</code> works fine.

2) Requesting disassembly on x86 fails due to a workaround that Zach put in long ago, https://github.com/dotnet/runtime/blob/bb71a7412668d857adc0a2486bddf5494a4466bc/src/coreclr/tools/r2rdump/R2RDump.cs#L545.

3) When I removed Zach's check and finally managed to load the coredistools library into the x86-hosted r2rdump app, it indeed crashed again just as Zach described in the issue. @echesakovMSFT, do you happen to know if there's any test coverage for x86-hosted coredistools? I mean, if it's known not to work we probably needn't bother; but it may be also something else like a bug in the PInvoke declarations (wrong calling conventions or some such that matters less for x64 than for x86) for calls into the native library. Also adding @janvorli as the general low-level runtime expert to chime in.

Thanks

Tomas

**Comment by echesakovMSFT** [comment]
> @echesakovMSFT, do you happen to know if there's any test coverage for x86-hosted coredistools?

We don't test coredistools separately. However, we use both x86-hosted and x64-hosted coredistools for running GCStress. 
Also when I worked on moving coredistools to dotnet/jitutils I tested them with SuperPMI asmdiffs on win-x86 (see https://github.com/dotnet/jitutils/issues/290). So, at least, functionality related to disassembling seems to be working fine.

**Comment by trylek** [comment]
Thanks Egor for your immediate response, that confirms my suspicion that the bug is most likely on our side. Have you got any idea where I or JanV could take a look at the native C++ declarations of the native API so that we can double-check correctness of the PInvoke declarations? I see this as the most likely culprit.

**Comment by echesakovMSFT** [comment]
Sure, the declarations are define in the following [file](https://github.com/dotnet/runtime/blob/master/src/coreclr/inc/coredistools.h)
[This one](https://github.com/dotnet/jitutils/blob/master/src/coredistools/coredistools.h) is in jitutils and should match the one in runtime.

**Comment by trylek** [comment]
Thanks Egor but I'm still not there ;-). When I look at <code>coredistools.dll</code> with a PE dumper, I see the following exports:

<pre>
  Ordinal   Entry Point   Name
        1   0x000151C0    ClearOutputBuffer
        2   0x000151F0    DisasmInstruction
        3   0x000152D0    DumpCodeBlock
        4   0x00015300    DumpDiffBlocks
        5   0x00015460    DumpInstruction
        6   0x00015540    FinishDiff
        7   0x00015570    FinishDisasm
        8   0x000155A0    GetOutputBuffer
        9   0x000155E0    InitBufferedDiffer
       10   0x000155F0    InitBufferedDisasm
       11   0x00015600    InitDisasm
       12   0x00015610    NearDiffCodeBlocks
       13   0x00015780    NewDiffer
       14   0x000159B0    NewDisasm
</pre>

These correspond to the native API references via PInvokes from https://github.com/dotnet/runtime/blob/bb71a7412668d857adc0a2486bddf5494a4466bc/src/coreclr/tools/r2rdump/CoreDisTools.cs#L27 - but I cannot find most of these methods in the header file you pointed out. I guess I can imagine we're only using a limited subset of the native header, is there something like a "coredistools repo" where we could find all the dllexport declarations?

**Comment by janvorli** [comment]
Is it possible that the coredistools.dll is compiled  on x86 with stdcall calling convention and dllimport by default uses cdeclor vice versa?

**Comment by echesakovMSFT** [comment]
> is there something like a "coredistools repo" where we could find all the dllexport declarations?

Yes, all the coredistools files are here https://github.com/dotnet/jitutils/tree/master/src/coredistools

**Comment by janvorli** [comment]
I think I was right - all the methods are declared with cdecl in the coredistools repo and the default for dllimport on Windows for x86 is stdcall
