### ISSUE TITLE
Debug Source in Visual Studio **Mac** 2019

### ISSUE THREAD

**Issue by jdobrzanski** [dotnet/runtime#45867]
Note - this is for **Mac**. (Visual Studio 2019)

I am attempting to step into Asp .Net Web App code while debugging my web application but the function is called without stepping into it.  The project is using Microsoft.NetCore.App 3.1.8 and Microsoft.AspNetCore.App 3.1.8.

I have enabled `"Step into external code"` in the IDE preferences.  Not sure what else I need to do.

Note, on application start up the application logs print warnings such as:
`Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.8/System.Private.CoreLib.dll'. Cannot find or open the PDB file.`

I can find no instructions on finding/installing the pdb files for .net core for mac for visual studio, nor am I sure whether I need to run the symbols server and how.

Not sure what else you'll need from me to work this issue out but I can provide.

**Comment by marcpopMSFT** [comment]
I think VS for Mac tracks issues through developer community but moving to the runtime first in case it's an issue with their public debug source/symbols.

**Comment by tommcdon** [comment]
@mikem8361 potential symbol indexing issue on 3.1.8
cc @sdmaclea @hoyosjs

**Comment by hoyosjs** [comment]
I can't tell why. I just tried I can get the symbols for said runtime under the key `system.private.corelib.pdb/eb0677935c3f4219aef13ab117c20649FFFFFFFF/system.private.corelib.pdb`. I might continue taking a look as it's pretty similar to #45649

**Comment by sdmaclea** [comment]
I was also having trouble with what appeared to be symbol server timeouts being reported as symbol not found.  I wondered at the time whether there were times when the symbol server got overloaded.  Perhaps near a release?

**Comment by mikem8361** [comment]
@jdobrzanski are you still having this issue?  It may have been a transient symbol server problem?
