### ISSUE TITLE
HttpWebRequest.GetRequestStream returned stream does not send data immediately in .NET Core

### ISSUE THREAD

**Issue by manureini** [dotnet/runtime#45871]
I try to upload a large file with HttpWebRequest in .NET Core or .NET 5, but a "IOException: Stream was too long." is thrown.

The request is not send immediately and is somehow buffered.

repro:
https://stackoverflow.com/questions/61383052/httpwebrequest-getrequeststream-returned-stream-does-not-send-data-immediately-i

**Comment by wfurt** [comment]
How big is the file? Do you have simple app to outline the code you use?

**Comment by manureini** [comment]
The file is around 8GB. I was able to use the HttpClient insted HttpWebRequest to workaround this issue

**Comment by wfurt** [comment]
That is good to know. This feels like we have `int` somewhere and that wraps around.

**Comment by stephentoub** [comment]
I expect this is the same issue as https://github.com/dotnet/runtime/issues/18632 (albeit for GetRequestStream instead of GetRequestStreamAsync).

**Comment by manureini** [comment]
Yes could be a similar issue.
I'm able to workaround this with the HttpClient.
Thanks to the guy who helped on Stackoverflow ;)

**Comment by karelz** [comment]
Duplicate of #18632
