### ISSUE TITLE
Ping.exe timeout is not 5000 ms

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#45888]
Ping class mentions default Ping.exe timeout but it is not the same as in the code:

https://github.com/dotnet/runtime/blob/c80e10046f792c2533d78e5a52fbc5ff0f07563e/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/Ping.cs#L15
`        private const int DefaultTimeout = 5000;       // 5 seconds: same as ping.exe on Windows.`

Ping.exe documentation
```Specifies the amount of time, in milliseconds, to wait for the echo Reply message corresponding to a given echo Request message. If the echo Reply message is not received within the time-out, the "Request timed out" error message is displayed. The default time-out is 4000 (4 seconds).```

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping

**Comment by wfurt** [comment]
the default could probably change between releases. What do you suggest here @NN--- ?

**Comment by NN---** [comment]
I suggest to document the default timeout for Ping and remove misleading comment.

**Comment by karelz** [comment]
Triage: Let's update the docs. We would take comment update PR if you are interested @NN--- (we should check it is correct on all Windows versions), otherwise it does not seem to be important enough to track, closing.
