### ISSUE TITLE
string Equals StringComparison.OrdinalIgnoreCase bug with @ and ` characters

### ISSUE THREAD

**Issue by matroberts** [dotnet/runtime#45889]
### Description

            var atsymbol = "@a";
            var backtick = "`a";

            // returns false as expected
            Console.WriteLine($"Is {atsymbol} equal to {backtick}: {atsymbol.Equals(backtick, StringComparison.OrdinalIgnoreCase)}"); 
            // returns true which is very wrong
            Console.WriteLine($"Is {backtick} equal to {atsymbol}: {backtick.Equals(atsymbol, StringComparison.OrdinalIgnoreCase)}"); 
### Configuration

* Which version of .NET is the code running on? 
** Visual Studio Project says: <TargetFramework>netcoreapp3.1</TargetFramework>
** dotnet --version = 3.1.401
* What OS and version, and what distro if applicable? windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No

**Comment by EgorBo** [comment]
Works as expected on .NET 4.x

/cc @GrabYourPitchforks

**Comment by EgorBo** [comment]
The problem seems in `UInt32OrdinalIgnoreCaseAscii` e.g.:

UInt32OrdinalIgnoreCaseAscii('@', '`'); // false
UInt32OrdinalIgnoreCaseAscii('`', '@'); // true

**Comment by GrabYourPitchforks** [comment]
The check below correctly flags "backtick isn't an \[A-Za-z\] character", but need to investigate further why this isn't forcing an exact bitwise equality check later in the method.

https://github.com/dotnet/runtime/blob/53c16198a8417e87e62c9df7c5e2e2602f9aa01d/src/libraries/System.Private.CoreLib/src/System/Text/Unicode/Utf16Utility.cs#L156-L157

**Comment by danmosemsft** [comment]
2.1 is fine; 3.1 and later are not.

**Comment by GrabYourPitchforks** [comment]
Found the issue, trying to figure out how to fix it without harming perf, given how absurdly hot this code path is.

**Comment by GrabYourPitchforks** [comment]
Assuming _valA_ is the long tail of the operation...

Current codegen:

```asm
xor valB, valA
lea tmp, [valA + CONST]
or valA, CONST
add valA, CONST
or valA, tmp  ; dependency on tmp (may stall)
shr valA, 2
or valA, CONST
test valA, valB  ; dependency on valB
```

With proposed fix (still under test):

```asm
xor valB, valA
shl valB, 2  ; parallelize with arithmetic operations below
add valA, CONST
or valA, CONST
add valA, CONST
or valA, CONST
test valA, valB  ; dependency on valB
```

This should end up being a bit more efficient due to a shorter chain on _valA_ and the lack of a possibly-stalling dependency on _tmp_. In fact, _tmp_ is gone entirely, which should also make the register allocator happier.

Still need to unit test + perf test.

**Comment by danmosemsft** [comment]
Fixing the bug _and_ making it faster - nice!

**Comment by danmosemsft** [comment]
Servicing candidate?

**Comment by GrabYourPitchforks** [comment]
Yeah, definitely a servicing candidate. I'll prep the 3.1 servicing email next week since there's no rush.

**Comment by danmosemsft** [comment]
Yeah 5.0 too. Sounds good.

**Comment by GrabYourPitchforks** [comment]
Reopening to track backporting.

**Comment by danmosemsft** [comment]
removing 'servicing consider' as that goes on PRs

**Comment by GrabYourPitchforks** [comment]
This was backported to 3.1 via https://github.com/dotnet/coreclr/pull/28118. Closing since I believe this servicing event is resolved.
