### ISSUE TITLE
Documentation for Microsoft.Extensions.Logging is incorrect/outdated

### ISSUE THREAD

**Issue by pgrawehr** [dotnet/runtime#45897]
An overview documentation for this module is at https://docs.microsoft.com/en-us/dotnet/core/extensions/logging. The detailed API reference starts here: https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.logging?view=dotnet-plat-ext-5.0.

However, I was having a hard time understanding how to actually use the interfaces from this module (as well as Microsoft.Extensions.Logging.Abstractions), because the documentation doesn't match the implementation. Two examples I found:

- https://docs.microsoft.com/en-us/dotnet/core/extensions/logging#non-host-console-app The example given in the "Non-Host console app" can't be used, the class `LoggerFactory` does not have a static `Create()` method (in fact, it has no static methods at all). The correct way seems to be something like this:
```
using var loggerFactory = new LoggerFactory();
loggerFactory.AddProvider(new ConsoleLoggerProvider((s, level) => true, false));

// Statically register our factory. Note that this must be done before instantiation of any class that wants to use logging.
LogDispatcher.LoggerFactory = loggerFactory;
```
(This works, but I'm not sure it's how it's intended to be used)

- `ConsoleLoggerProvider` has two ctors, according to the documentation, they take instances of `IOptionsMonitor`: https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.logging.console.consoleloggerprovider?view=dotnet-plat-ext-5.0. In fact, the ctors take a completelly different set of parameters.

I'm sure I'm using the latest version, 5.0.0, for which the documentation should be made.

CC @maryamariyan

**Comment by maryamariyan** [comment]
> the class LoggerFactory does not have a static Create() method (in fact, it has no static methods at all). 

LoggerFactory has a static Create() method shown below:

https://github.com/dotnet/runtime/blob/3bcee54244c3e58d0435d8a09cd149cd9ae9a438/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs#L92

I believe the sample in the documentation should work.

**Comment by pgrawehr** [comment]
My bad. Due to an incorrect package source configuration, I got the correct version of `Microsoft.Extensions.Logging.Abstractions` but only saw a completelly outdated version of `Microsoft.Extensions.Logging`. Now after updating, the methods are as they should be.
