### ISSUE TITLE
ilasm hitting segmentation fault when emitting portable PDBs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#45908]
ilasm is hitting a segfault during processing of System.Runtime.CompilerServices.Unsafe.ilproj in https://github.com/dotnet/runtime/pull/45387/#issuecomment-740747446

This is blocking the dependency update to the new version.

**Comment by akoeplinger** [comment]
@jkotas could you please help us find out who can take a look at this? :)

**Comment by jkotas** [comment]
@briansull Could you please take a look?

cc @JulieLeeMSFT

**Comment by briansull** [comment]
@jkotas - I am not sure that I will have time to investigate this before I take my end of year vacation.
Might want to have a backup plan.

**Comment by jkotas** [comment]
> Might want to have a backup plan.

I have pushed a workaround into #45387

The situation that triggers the crash is a local variable without explicit name.
