### ISSUE TITLE
.net 5.0 seems to be wrong in detecting zero-terminzted string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45912]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/net-50-seems-to-be-wrong-in-detecting-/1283401)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.7]
The following code:

```
     class Program
     {
         static void Main(string[] args)
         {
             const string s = "abc";
             const string sz = "abc\0";
    
void Report(string str) 
                 => Console.WriteLine($"\"{str}\" ({str. Length}), zero-terminated: {str. EndsWith("\0")}");
    
Report(s);
             Report(sz);
         }
     }

```
gives the following output for target framework .net 5.0:

"abc" (3), zero-terminated: True
"abc" (4), zero-terminated: True

For target framework .netcoreapp3.1 the code outputs the following lines:

"abc" (3), zero-terminated: False
"abc" (4), zero-terminated: True

As for me, .net core 3.1 behavior looks correct and .net 5.0 does not.

---
#### Feedback Bot on 12/9/2020, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by danmosemsft** [comment]
@safern, the repro goes away if I set `DOTNET_SYSTEM_GLOBALIZATION_USENLS=1`

Did we discuss this case already?

**Comment by GrabYourPitchforks** [comment]
This behavior is by design. `EndsWith(string)` is linguistic (culture-aware), and the null character has zero weight under ICU. Caller almost certainly meant to perform an ordinal comparison via `EndsWith(char)` or `EndsWith(..., StringComparison.Ordinal)`.

**Comment by safern** [comment]
Thanks, @GrabYourPitchforks you beat me to it.

**Comment by tarekgh** [comment]
@GrabYourPitchforks is right. For such operation ordinal comparison has to be used. Also why need to use EndsWith at all? why not just testing ```str[str.Length - 1] == `\0' ```?

**Comment by GrabYourPitchforks** [comment]
To be fair, EndsWith is more readable. And it works with empty strings. :)

**Comment by tarekgh** [comment]
> To be fair, EndsWith is more readable. And it works with empty strings. :)

That is a good point. but do you consider the empty string is null terminated or not? for such user scenarios, it should be true I guess.
