### ISSUE TITLE
http_proxy and https_proxy not recognised on Linux

### ISSUE THREAD

**Issue by jfwrightuk** [dotnet/runtime#45919]
Hi, I'm using .NET Core 3.1 and System.ServiceModel.Http 4.8.0 to connect to an existing SOAP web service behind a proxy using a BasicHttpsBinding with UseDefaultWebProxy set to true.

On Windows, I can set HTTPS_PROXY to an address and this is picked up by the binding's default web proxy.

On Linux, I've tried setting HTTPS_PROXY and HTTP_PROXY and lower-case equivalents and none of these are picked up by the default web proxy.

Is this a misunderstanding of how things are meant to work, or is it a bug?  Many thanks for any insight you can provide.  I see various threads on this issue but they all relate to older versions of .NET Core or WCF.

**Comment by HongGit** [comment]
This is related with HttpClientHandler behavior, move to runtime.

**Comment by stephentoub** [comment]
@honggit, HttpClientHandler does respect HTTP_PROXY and HTTPS_PROXY:
https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.Unix.cs
Without a repro shared, it's not clear to me this is an issue with HttpClientHandler vs WCF.

What does UseDefaultWebProxy do in WCF?

@jfwrightuk, can you share a minimal repro?

**Comment by jfwrightuk** [comment]
Apologies, this turned out to be due to a combination of my misunderstanding about the executables generated by .NET Core and running those executables on WSL (Ubuntu).  I'm still not 100% clear about what works in what circumstances but I don't think this is a bug at all.  Running the .dll definitely picks up the HTTPS_PROXY environment variable.

**Comment by wfurt** [comment]
If the destination is same (e.g. one proxy)  I would recommend to use `all_proxy=....`
to keep it simple. http_proxy is lower-case only for reasons explained [here](https://ec.haxx.se/usingcurl/usingcurl-proxies).
