### ISSUE TITLE
[Mono][Wasm] Pin V8 version for performance runs

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#45915]
Currently, automated performance runs for wasm use the latest version of the v8 javascript engine provided by jsvu. This can make it difficult to determine weather a regression/improvement is attributable to changes in mono or to differences in v8.  Pinning can solve this problem.

We need to decide what cadence to update the version, and how to do that (github action that opens a PR?). To frequently can produce weird artifacts in performance runs, but is too infrequently unrealistic? 

We also want to report the version number in the issues.

@DrewScoggins  @lewing

**Comment by lewing** [comment]
The most important part here is being able distinguish between a runtime change and a pure v8 bump so as long as the automation creates a separate commit I'm happy.  I'm also fine with new prs for each new version if that is preferable. Is the v8 version set by dotnet/runtime or dotnet/performance for the perf runs?

**Comment by DrewScoggins** [comment]
Which version should I pin to?

**Comment by SamMonoRT** [comment]
@naricc @DrewScoggins - do we still need to address this for .NET6 ?

**Comment by naricc** [comment]
I believe this can safely be moved to .Net 7; it should be done eventually, but isn't going to change anything in the immediate term.

**Comment by lewing** [comment]
can we get an update on the state of this and what the plan is?
