### ISSUE TITLE
I've found the culprit for the secondary issue. This one is a Rosetta 2 issue too. I have reported it to Apple.

### ISSUE THREAD

**Issue by typno8-nEbtos-hibmik** [dotnet/runtime#45953]
I've found the culprit for the secondary issue. This one is a Rosetta 2 issue too. I have reported it to Apple.

__Originally posted by @janvorli in https://github.com/dotnet/runtime/issues/44958#issuecomment-743091812__

**Comment by janvorli** [comment]
@typno8-nEbtos-hibmik I'm not sure why have you created this issue. I am closing it as the original issue is tracking the debugging issue.

**Comment by PathogenDavid** [comment]
@janvorli It's a spam bot: https://github.com/dotnet-foundation/announcements/issues/8
