### ISSUE TITLE
How to build .NET runtime without SDK or how to build .NET SDK without .NET runtime?

### ISSUE THREAD

**Issue by Maniues** [dotnet/runtime#45957]
Hello
Is it possible to compile .NET Runtime without .NET SDK?
If not, is it possible to compile .NET SDK without .NET Runtime?
If not, what are my options to build these packages to be 100% free under the MIT license (or another free license)? (Binary packages from dotnet are proprietary licensed)

**Comment by jkotas** [comment]
Compiling .NET SDK requires .NET Runtime, and vice versa.

.NET runtime distributions for non-Windows operating systems are 100% MIT.

.NET runtime distribution for Windows contains several additional closed source components. The details are described in https://github.com/dotnet/core/blob/master/license-information-windows.md.

**Comment by Maniues** [comment]
So how did Microsoft compile the first version of the .NET Runtime / .NET SDK?
Why are Windows versions not 100% open-source (MIT)?

**Comment by jkotas** [comment]
> So how did Microsoft compile the first version of the .NET Runtime / .NET SDK?

The same way as most other language environment are bootstrapped: by writing throw-away C# compiler in C, and then switching to C# compiler written in C#. This is standard technique used for compiler development, for example see  https://docs.google.com/document/d/1P3BLR31VA8cvLJLfMibSuTdwTuF7WWLux71CYD0eeD8/preview?pli=1 

> Why are Windows versions not 100% open-source (MIT)?

These components are proprietary Windows-specific technologies that are included in the binary distribution for better compatibility for .NET Framework. It was not feasible to open source them under MIT license for number of reasons.

**Comment by danmosemsft** [comment]
Also see https://github.com/dotnet/source-build

**Comment by Maniues** [comment]
> > So how did Microsoft compile the first version of the .NET Runtime / .NET SDK?
> 
> The same way as most other language environment are bootstrapped: by writing throw-away C# compiler in C, and then switching to C# compiler written in C#. This is standard technique used for compiler development, for example see https://docs.google.com/document/d/1P3BLR31VA8cvLJLfMibSuTdwTuF7WWLux71CYD0eeD8/preview?pli=1
I understand. And in this case, could Microsoft just use the .NET Framework and Roslyn to build .NET Core and above?
