### ISSUE TITLE
Implementation of Regex.TryMatch()

### ISSUE THREAD

**Issue by marktanner1331** [dotnet/runtime#45959]
## Background and Motivation
It is common practice in code that uses regex to first check the match is successful before using it's value. 
This can be done via `Regex.IsMatch`:

```c#
if (Regex.IsMatch("I have 1 apple", "\\d+"))
{
    Match match = Regex.Match("I have 1 apple", "\\d+");
    Console.WriteLine("You have {0} apple", match.Value);
}
```

However this causes the regex to be run twice. It can be mitigated by performing the match, and then checking if it is successful:
```c#
Match match = Regex.Match("I have 1 apple", "\\d+");
if(match.Success)
{
    Console.WriteLine("You have {0} apple", match.Value);
}
```

However I suggest it would be more elegant to combine these two steps into a single method.

## Proposed API
```c#
namespace System.Text.RegularExpressions
{
    public static bool TryMatch(string input, string pattern, out Match match);
}
```

## Usage Examples
```c#
if(Regex.TryMatch("I have 1 apple", "\\d+", out Match match))
{
    Console.WriteLine("You have {0} apple", match.Value);
}
```

## Alternative Designs
I did consider creating it as an overload of `IsMatch` but decided against it, as `IsMatch` already has a number of overloads, and `TryMatch` is more consistent with other methods, such as `Int.TryParse`.

## Risks
None that I know of

## Implementation
If accepted, I would like to implement this feature.

**Comment by danmosemsft** [comment]
Thanks for the suggestion. In my view, the pattern of checking for success is not hard to write and quite readable. I am not sure a new API would add enough value (new API increases cognitive load so it has to bring enough value).

Incidentally the Try prefix is intended for avoiding exceptions in hot code paths, like parsing: it would surprise developers to use it for another purpose.

**Comment by centreboard** [comment]
C# 9 does now allow a similar idea to the `TryMatch`
``` csharp
if (Regex.Match("I have 1 apple", "\\d+") is {Success: true} match) 
{
    Console.WriteLine("You have {0} apple", match.Value);
}
```

**Comment by pgovind** [comment]
I agree with @danmosemsft here. IMO the `Try*` pattern is for avoiding exceptions. For ex: When a `TryParse` method returns false, I expect that the input was probably bad. However, if a `TryMatch` method returned false, that doesn't imply anything about the input. Also, as @centreboard points out, you can do pattern matching with C# 9.  This greatly reduces the value of a `TryMatch` API and would never get past API review. I'm going to close this issue. If you would really like to reduce the number of calls in your code base, I think this would make a good candidate for an analyzer!
