### ISSUE TITLE
Ninja build on Windows generates obj files into a wrong directory subtree

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#45955]
I have found that on Windows build with ninja generates obj files into artifacts\nmakeobj\windows.x64.Debug instead of artifacts\obj\coreclr\windows.x64.Checked\src. I think that should be changed to match the unix / non-ninja folder structure.

**Comment by janvorli** [comment]
cc: @jkoritzinsky

**Comment by ViktorHofer** [comment]
@jkoritzinsky can you please take a look at this one?

**Comment by jkoritzinsky** [comment]
I'll take a look when I have some free cycles.
