### ISSUE TITLE
Document DllImport probing

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/runtime#4596]
This was brought up in dotnet/coreclr#1780 by @OtherCrashOverride

We should add some documentation about the locations and names we attempt on each platform when probing for modules (and in what order) to the Book of the Runtime. This will be useful information for both coreclr developers and library developers.

**Comment by vitek-karas** [comment]
Part of the probing mechanism is documented here: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/loading-unmanaged

**Comment by deeprobin** [comment]
I think this should then be applied to the new `LibraryImportAttribute` as well.

/cc @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
>I think this should then be applied to the new LibraryImportAttribute as well.

@deeprobin Can you elaborate on this? The `LibraryImportAttribute` defers to `DllImport` for library loading. The source generator has no influence over loading or export discovery. The original design doc describing this can be found [here](https://github.com/dotnet/runtime/blob/main/docs/design/features/source-generator-pinvokes.md).

**Comment by deeprobin** [comment]
> Can you elaborate on this? The `LibraryImportAttribute` defers to `DllImport` for library loading. The source generator has no influence over loading or export discovery. The original design doc describing this can be found [here](https://github.com/dotnet/runtime/blob/main/docs/design/features/source-generator-pinvokes.md).

I was only interested in the fact that we can create some kind of documentation for the LibraryImportGenerator.

But this seems to exist already.
