### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Maniues** [dotnet/runtime#45967]
Edit: I have built Runtime but in artifacts folder my architecture is missing, only bin folder with all compiled components. How can I fix it?

Old version:
I have a problem compiling CoreCLR on Linux (Linux Mint 64-bit). There is one error and two messages (Sorry for the translation from my language):
```
-- Configuring incomplete, errors occurred!
  See also "/home/mdev/Desktop/runtime/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeOutput.log".
  See also "/home/mdev/Desktop/runtime/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeError.log".
  /home/mdev/Desktop/runtime/src/coreclr
  Executing cmake --build "/home/mdev/Desktop/runtime/artifacts/obj/coreclr/Linux.x64.Checked" --target install -- -j 4
  make: *** There are no rules to execute the object 'install'. Stop.
  Failed to build "CoreCLR component".
/home/mdev/Desktop/runtime/src/coreclr/runtime.proj(38,5): error MSB3073: Command „"/home/mdev/Desktop/runtime/src/coreclr/build-runtime.sh" -x64 -checked -os Linux” has been finished with error code 2.

Compilation WAS NOT SUCCESSFUL.

/home/mdev/Desktop/runtime/src/coreclr/runtime.proj(38,5): error MSB3073: Command „"/home/mdev/Desktop/runtime/src/coreclr/build-runtime.sh" -x64 -checked -os Linux” has been finished with error code 2.
    Warnings: 0
    Errors: 1
```
https://pastebin.com/tZ6rFDqC This is the output of build.sh. How do I install these packages not found?

**Comment by hoyosjs** [comment]
Can you check the file "/home/mdev/Desktop/runtime/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeError.log"

**Comment by Maniues** [comment]
> 
> 
> Can you check the file "/home/mdev/Desktop/runtime/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeError.log"

Hi
I have built Runtime but in artifacts folder my architecture is missing, only bin folder with all compiled components. How can I fix it?

**Comment by janvorli** [comment]
@Maniues can you please share the command line you have used and the complete output of the build.sh? The one that you've shared is just the configuration part of cmake.

**Comment by Maniues** [comment]
New issue with log: https://github.com/dotnet/runtime/issues/47153
