### ISSUE TITLE
TypeBuilder::GetConstructor and GetField type checks are in the wrong order

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#45988]
There are 3 static methods on TypeBuilder to get an instantiated generic MemberInfo given a generic definition:

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.getconstructor
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.getfield
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.getmethod

The issue is, the first 2 method (GetConstructor and GetField) have their checks in the wrong order, resulting in dead code. For example:

https://github.com/dotnet/runtime/blob/53c16198a8417e87e62c9df7c5e2e2602f9aa01d/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.cs#L105-L110

The first check says "if the type isn't a TypeBuilderInstantiation, throw". Then the next check is checking if the type is a `TypeBuilder`. Both `TypeBuilder` and `TypeBuilderInstantiation` are sealed types that inherit from `TypeInfo`. So if the type isn't a `TypeBuilderInstantiation`, an exception is thrown, and the check for `type is TypeBuilder` is dead code.

I thought I could just remove the dead code from these two methods, but looking at the last one: `TypeBuilder::GetMethod`:

https://github.com/dotnet/runtime/blob/53c16198a8417e87e62c9df7c5e2e2602f9aa01d/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.cs#L86-L93

This has the checks flipped, which makes more sense. If the type passed in `IsGenericTypeDefinition` (which can only be true if it is a `TypeBuilder`), then it calls `MakeGenericType`, which will return a `TypeBuilderInstantiation`.

My assumption is the `GetConstructor` and `GetField` methods were supposed to be written this way, but it was a mistake. I looked back in internal source history, and it appears all 3 of these methods were written this way when the feature was first developed.

If the code is truly not necessary, we should just delete the dead code. But I think the checks should be flipped to match the `GetMethod` method.

Note: we should also add unit tests for this scenario when fixing this bug.

**Comment by BartoszKlonowski** [comment]
@eerhardt I would like to handle this issue, so please assign me to this item.
CC: @steveharter @krwq

**Comment by krwq** [comment]
@BartoszKlonowski still planning to fix this?

**Comment by steveharter** [comment]
@eerhardt please move to v7 unless this the [PR](https://github.com/dotnet/runtime/pull/53645) picked up ASAP.

**Comment by eerhardt** [comment]
There's no need for this to be fixed in 6.0.
