### ISSUE TITLE
Double registration of "Microsoft-Windows-DotNETRuntime" causes startup issues on Windows

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#46007]
Both `PortableThreadPoolEventSource` and `NativeRuntimeEventSource` register etw with "Microsoft-Windows-DotNETRuntime" which causes a callback from Etw on the second registration (`NativeRuntimeEventSource`) triggering a manifest request whether or not the events are on, which then cascades to further work etc

![image](https://user-images.githubusercontent.com/1142958/101955887-8a1bbf80-3bf6-11eb-8e7d-277d18a44ef9.png)

**Comment by benaadams** [comment]
Correction, doesn't seem to be this that is causing the callback from Etw, still haven't worked out what it is

**Comment by Wraith2** [comment]
Runtime startup issues though, not windows startup issues right?

**Comment by benaadams** [comment]
Runtime on Windows 😅

Is Etw registration so shouldn't effect other platforms

**Comment by tommcdon** [comment]
@sywhang

**Comment by benaadams** [comment]
This I think is solved

**Comment by sywhang** [comment]
For context the double-registration was happening due to the temporary hack we had for emitting events from the portable threadpool. That hack was removed in Preview 2.
