### ISSUE TITLE
Reusable, waitable IValueTaskSource implementation.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/runtime#46006]
## Summary

Using reusable ValueTask and caching it, I got some performance improvements. I removed the methods such as verifying Version in ManualResetValueTaskSourceCore and made them reusable after Reset. I used a ring buffer to store it in concurrency scenarios and got some performance improvements, so I wondered if I could recommend it to aspnetcore.

Sorry for quick bump,  is  there a similar official plan?

## Motivation and goals

So far, I haven't found a way to reuse Task. In those performance-sensitive scenarios, we can improve performance by avoiding the creation of a large number of TaskComplatoinSource instances.

## In scope

 - Scenarios where tasks need to be created frequently.
 - Low allocation scenarios are required.

## Out of scope

No

## Risks / unknowns

I'm not sure! I ran successfully in 100W tasks with a single link, but I didn't have many tests to prove that it had any security risks.

## Other  

If my description is not appropriate, please contact me.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by davidfowl** [comment]
> so I wondered if I could recommend it to aspnetcore.

I'm a bit unclear as to what exactly you're recommending.

**Comment by NMSAzulX** [comment]
@davidfowl Is the scene of high-frequency use of TaskCompletionSource. I wanted to post in Runtime before, but I think ASP.NETCORE may use it more often. My English is not good.

**Comment by NMSAzulX** [comment]
@tarekgh @davidfowl 

In more detail, I am writing a client about Redis. If the Set () method is called concurrently, it will merge the bytes and send them out. Each caller will get a TaskCompletionSource to wait for the result. The client will accept a merged result, split and parse it, and get the TaskCompetionSource from the queue and call the SetResult method.

So this scenario will create a lot of TaskCompletionSource,. I made the above optimizations for this scenario.

**Comment by davidfowl** [comment]
Sounds fine but I dunno what that has to do with asp.net core. Where would we use this type?

**Comment by NMSAzulX** [comment]
I see the source code ResettableBooleanCompletionSource similar to this.

**Comment by NMSAzulX** [comment]
ASP.NETCORE is too big, I will look for more similar scenarios, although I may make mistakes.

**Comment by NMSAzulX** [comment]
@davidfowl @tarekgh 

Hi everyone, I'm sorry to open this ISSUE rashly.  I recently tracked the [ValueTask](https://github.com/2881099/FreeRedis/tree/master/experimental/console_netcore31_newsocket/Scheduler/Task) I changed. I rewrote the ManualResetValueTaskSourceCore (mrvs) class. And use a [ring buffer](https://github.com/2881099/FreeRedis/blob/master/experimental/console_netcore31_newsocket/Client/Utils/CircleTaskBuffer4.cs) to store ValueTask (mrvs). Every time I reuse valuetask, I call mrvs.Reset to reset the state of the valuetask. I got the wrong result, and it can't wait synchronously. I think I broke its structure. I can only use new TaskCompletionSource to implement my function now. I'm sorry to have wasted your time.

**Comment by stephentoub** [comment]
ManualResetValueTaskSourceCore was shipped in order to make it easier for developers to create their own IValueTaskSource implementation.  Most implementations have something special they want to do, such as reusing some other object as the IValueTaskSource, or automatically resetting the instance when awaited, or some such thing, which is why we've not shipped a ManualResetValueTaskSource that just wraps the MRVTSC and delegates from the interface methods (e.g. https://github.com/dotnet/runtime/blob/master/src/libraries/Common/tests/System/Threading/Tasks/Sources/ManualResetValueTaskSource.cs).
