### ISSUE TITLE
Usage of "deprecated" TFM?

### ISSUE THREAD

**Issue by ovebastiansen** [dotnet/runtime#46001]
Hi,

Just a question from a guy starting to look at the code here. Why are for instance the logging library still targeting net461, as well as a lot of netstandard2.0 usage? I thought that from now on it was only net5.0 and net6.0?

Right now that means a lot of versions that needs to be built to get the Microsoft.Extensions.Logging sln to build

**Comment by gfoidl** [comment]
> I thought that from now on it was only net5.0 and net6.0?

Yep, .NET will move forward with .NET 5, .NET 6, etc.

But the types from `Microsoft.Extensions`-namespace can be used by other targets like .NET Standard 2.0 too. And as there will be updates to these types / packages they have to be built.

**Comment by ovebastiansen** [comment]
Ah, I thought 5.0.0 versions was going to drop support for the other runtimes. Just another misunderstanding of net5 vs 5.0 of the libraries ;)

//Ove

On my phone
________________________________
