### ISSUE TITLE
[WASM] How to read from SharedArrayBuffer?

### ISSUE THREAD

**Issue by ivan-prodanov** [dotnet/runtime#46016]
Context: My react app is accessing a large dataset from a worker using a SharedArrayBuffer. I'd like to process the SharedArrayBuffer in C# with minimal overhead. I have a hard time converting the SharedArrayBuffer to a Span in C#.
Here's what I tried:

```C#
public static int TestSum(SharedArrayBuffer sharedArrayBuffer)
{
    Int32Array array = new Int32Array(sharedArrayBuffer);
    Span<int> nativeArray = array; // error                        
    
    int sum = 0;
    for (int i = 0; i < nativeArray.Length; i++)
    {
        sum += nativeArray[i];
    }

    return sum;
}
```

This unfortunately fails with "Object '...' is not a typed array" in js_typed_array_to_array. 

Here's the function from dotnet.js:
```js
js_typed_array_to_array : function (js_obj) {
	if (!!(js_obj.buffer instanceof ArrayBuffer && js_obj.BYTES_PER_ELEMENT)) 
	{
		var arrayType = js_obj[Symbol.for("wasm type")];
		var heapBytes = this.js_typedarray_to_heap(js_obj);
		var bufferArray = this.mono_typed_array_new(heapBytes.byteOffset, js_obj.length, js_obj.BYTES_PER_ELEMENT, arrayType);
		Module._free(heapBytes.byteOffset);
		return bufferArray;
	}
	else {
		throw new Error("Object '" + js_obj + "' is not a typed array");
	} 
```

I was able to workaround this by changing
```js
if (!!(js_obj.buffer instanceof ArrayBuffer && js_obj.BYTES_PER_ELEMENT)) 
```
to
```js
if (!!(js_obj.buffer instanceof (ArrayBuffer, SharedArrayBuffer) && js_obj.BYTES_PER_ELEMENT)) 
```

Now the code executes with no errors, however there's a copying operation being done in **mono_typed_array_new**. Doesn't that make the whole idea behind using a SharedArrayBuffer in order to avoid copying useless?

Is this the proper way to process a SharedArrayBuffer? Is there a way to process it without copying the data?

**Comment by kjpou1** [comment]
@ivan-prodanov this is still not possible as per the WebAssembly design open issue: https://github.com/WebAssembly/design/issues/1162.  This is also for shared buffers.

You might be able to use the heap itself and design something that will fit your needs.  There is issues with holding onto memory addresses and should not be done long term.  Emscripten during memory allocation can issue warning about the memory buffer being released and no longer accessible.  Error maybe encountered: Attempting to access detached ArrayBuffer in WASM after memory growth.

There is some old code here that attempts to use memory pointers.  It is for strings but the concepts are the same:  

https://github.com/kjpou1/Mono.Wasm.Samples/tree/master/WasmString

The [Program.cs](https://github.com/kjpou1/Mono.Wasm.Samples/blob/master/WasmString/Program.cs) still interacts with javascript via memory pointers being passed back and forth.  The [Index.html](https://github.com/kjpou1/Mono.Wasm.Samples/blob/master/WasmString/index.html) file has the javascript routines.  This is old code written against the mono repo and older version of bindings but the concepts are still the same.

Thank you for reporting the issue you ran into.  We will take a look at it and get a fix out as soon as possible.

**Comment by kjpou1** [comment]
I am going to close this as there is nothing we can do about this issue.  Issue https://github.com/dotnet/runtime/issues/46624 was opened to track the bug that was reported along with description.
