### ISSUE TITLE
Windows Defender Firewall Issue With .NET 5 App For Program Based Rule

### ISSUE THREAD

**Issue by ShreyasZare** [dotnet/runtime#46012]
### Description

.NET 5 app fails to respond to TCP/UDP port its listening on when using Windows Defender Firewall with a rule based on the application path. Creating new rule with specific TCP or UDP protocol and port number however works as expected.

This issue creates problem for automatically adding firewall rule for the app when its not known what port the app will be using or if the app is configured to run on different port that is not the default/known port when the app starts.

### Configuration

- The code is running on .NET 5.0.0 Windows Desktop Runtime
- Tested on Windows Server 2019 Datacenter.

### Regression?

- The current app that I have which is built for .NET Framework 4.8 works well with the application path based firewall rule which it adds automatically. 

- The same app which was ported to .NET 5 adds application based firewall rule automatically, exactly like the .NET 4.8 app but, the firewall rule seems to not work at all. It works well if firewall rule for specific TCP/UDP port is created.

### Other information

- I have checked the process Id of the .NET 5 app that is running using `netstat` command and then have matched with the process that is running using Task Manager and thus its the same EXE in the firewall rule path that is running that has the socket open.

**Comment by NikolaMilosavljevic** [comment]
[Triage] This is not a setup issue. It seems to be related to an API used to set Firewall rules.

**Comment by karelz** [comment]
@ShreyasZare are you able to reproduce it with HelloWorld-style minimal repro? On both .NET 5 (as not working) and .NET Framework 4.8 (as working)?
Can you please post such sample here, with the exact Windows Defender Firewall rule, so that others can try to reproduce? ... that will rule out mistakes and machine-specific settings.

**Comment by ShreyasZare** [comment]
@karelz : Thanks for the response. I tried again with a small UDP console app compiled in .NET 4.8 and .NET 5. I could not get both of them to work with Firewall rule that uses program path. I could only make it work with a port based rule. Closing this issue now. I will reopen when I am able to reproduce this again.
