### ISSUE TITLE
Linux CI legs failing due to an infrastructure failure

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#46025]
The error is: `##[error]The request: 9937528 was abandoned due to an infrastructure failure. Notification of assignment to an agent was never received.`

For example: https://github.com/dotnet/runtime/pull/46019

**Comment by jkotas** [comment]
@dotnet/dncenghot Could you please take a look?

**Comment by MattGal** [comment]
> @dotnet/dncenghot Could you please take a look?

Yup, I'm investigating.  Curious why this is hot... is it 100% repro?

**Comment by jkotas** [comment]
It was 100% repro for a while yesterday. It does not seem to repro anymore.

**Comment by MattGal** [comment]
@jkotas there were two things going on here:

- There were only 14 distinct machines for this queue during this time in `buildpool.ubuntu.1604.amd64.open` ... I would guess either Azure or the scaler had trouble in this time range (it's not happening right now, I'm looking for any interesting logs).  @AlitzelMendez  / @ulisesh  FYI.

- As a result, the builds sat in queue for > 90 minutes, after which point this will always happen.  Tracked via this issue  : https://github.com/dotnet/core-eng/issues/10136 but unless AzDO actually does this work (have been asking for this for around a year now) any build that sits in queue for 90 minutes will be impacted.

**Comment by MattGal** [comment]
@jkotas ah yes, it was a scaler outage (https://github.com/dotnet/core-eng/issues/11667)

**Comment by jkotas** [comment]
Thanks for taking a look.
