### ISSUE TITLE
IEnumerable.Count() performance

### ISSUE THREAD

**Issue by zsybupt** [dotnet/runtime#46036]
### Description

IEnumerable<T>.Count() in System.Linq is optimized for ICollection type, should it has a fast path for IReadOnlyCollection to achieve better performace, too ?
https://github.com/dotnet/runtime/blob/010a5654555be3dacf624c8a16897dfc4cff8f76/src/libraries/System.Linq/src/System/Linq/Count.cs#L11

If it is an improvement, I can provide a pull request for this. :smile:

Thanks

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/issues/42254

**Comment by eiriktsarpalis** [comment]
Closing as duplicate #42254.
