### ISSUE TITLE
System.IO.Compression.Brotli: `BrotliStream` incorrectly compresses an empty stream

### ISSUE THREAD

**Issue by Taritsyn** [dotnet/runtime#46040]
### Description

Compressing an empty memory stream by using the `BrotliStream`:

```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace TestBrotli
{
    class Program
    {
        static void Main(string[] args)
        {
            var memoryStream = new MemoryStream();

            var compressionStream = new BrotliStream(memoryStream, CompressionLevel.Optimal);
            compressionStream.Dispose();

            byte[] outputBytes = memoryStream.ToArray();
            memoryStream.Dispose();

            string output = Encoding.UTF8.GetString(outputBytes);

            Console.WriteLine("Result of compression: '{0}'", output);
        }
    }
}
```

Gives an incorrect result:

```
Result of compression: ';'
```

In other words, instead of an empty string, we get a semicolon.

If use a `GZipStream` or `DeflateStream` classes instead of a `BrotliStream` class, then result will be correct:

```
Result of compression: ''
```

### Configuration

* .NET 5.0.1 and .NET Core 3.1.10
* Windows 10 20H2 (OS Build 19042.685)
* x64

### Regression

I have been observing the consequences of this error for a very long time (since .NET Core 3.1 release), but only today I realized that problem is caused by the Brotli compression.

**Comment by Taritsyn** [comment]
Most likely, semicolon put in the output stream during calling the `Dispose` or `DisposeAsync` method of `BrotliStream` class.

**Comment by danmosemsft** [comment]
@Taritsyn thank you for reporting this. Are you interested in debugging a little further?

**Comment by vcsjones** [comment]
I think this is expected. Google's [test suite][2] indicates that a zero-length input results in a one-byte output. Further, the [RFC states][1] that a compressed stream has at least one meta-block.

Further, using the `brotli` command line tool, I can reproduce the behavior. 

```shell
echo -n -e '' | brotli -d | wc -c # prints corrupt input

echo -n -e '\x3b' | brotli -d | wc -c # prints zero (wc -c gets the length of stdin)
```

[1]: https://tools.ietf.org/html/rfc7932#section-9.2
[2]: https://github.com/google/brotli/blob/master/tests/testdata/empty.compressed.00

**Comment by Taritsyn** [comment]
> I think this is expected.

The main problem is that if we postpone calling of the `Dispose` method, then result will be correct. For example, the following code:

```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Text;

namespace TestBrotli
{
    class Program
    {
        static void Main(string[] args)
        {
            var memoryStream = new MemoryStream();
            var compressionStream = new BrotliStream(memoryStream, CompressionLevel.Optimal);
            byte[] outputBytes = memoryStream.ToArray();

            compressionStream.Dispose();
            memoryStream.Dispose();

            string output = Encoding.UTF8.GetString(outputBytes);

            Console.WriteLine("Result of compression: '{0}'", output);
        }
    }
}
```

Gives an correct result:

```
Result of compression: ''
```

In this case, result does not depends on the peculiarities of compression algorithm implementation, but depends on moment when the `Dispose` method was called. When using the `GZipStream` and `DeflateStream` classes, we always get the same result.

In my case, code using the `BrotliStream` class is not so simple. A semicolon that puts to the output stream suppresses error messages when an exception occurs in my ASP.NET Core middleware (see the [“V2.8.2 blank page , can not working with comment in inline style html”](https://github.com/Taritsyn/WebMarkupMin/issues/106) issue).

Instead of a page with detailed error message:

![webmarkupmin-full-error-messge](https://user-images.githubusercontent.com/251859/102118446-c21e3f00-3e50-11eb-9f46-740fb2fc5b88.png)

I get a blank page with a semicolon:

![webmarkupmin-blank-page](https://user-images.githubusercontent.com/251859/102118534-e24dfe00-3e50-11eb-984b-5088462ba9d1.png)

**Comment by carlossanlop** [comment]
Triage:

Seems to be expected behavior, as pointed out by @vcsjones .

@Taritsyn the second example does not repro what you described because you need to call `Dispose` to flush the buffer:
https://github.com/dotnet/runtime/blob/3d200308e1c9eb8daabd0498d7a2ee02635452b1/src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/BrotliStream.cs#L59
