### ISSUE TITLE
Add implementations of System.Linq.Enumerable.Sum(this IEnumerable<X> source) for uint, ulong and potentially more types

### ISSUE THREAD

**Issue by AlFasGD** [dotnet/runtime#46042]
## Background and Motivation

There are several implementations to calculate the sum of the values within an `IEnumerable<T>`, but not all types are covered. Specifically, the currently implemented types are `int`, `long`, `float`, `double`, `decimal`, and their nullable variants. I believe that this should be extended to also support ~~at least~~ `uint` and `ulong`~~, if not for `byte`, `sbyte`, `short` and `ushort`~~.

In some cases, the unsignedness could be an issue when summing the values.

## Proposed API

```diff
 namespace System.Linq
 {
     public static partial class Enumerable
     {
         public static int Sum(this IEnumerable<int> source);
         public static int? Sum(this IEnumerable<int?> source);
+        public static uint Sum(this IEnumerable<uint> source);
+        public static uint? Sum(this IEnumerable<uint?> source);
         public static long Sum(this IEnumerable<long> source);
         public static long? Sum(this IEnumerable<long?> source);
+        public static ulong Sum(this IEnumerable<ulong> source);
+        public static ulong? Sum(this IEnumerable<ulong?> source);
         public static float Sum(this IEnumerable<float> source);
         public static float? Sum(this IEnumerable<float?> source);
         public static double Sum(this IEnumerable<double> source);
         public static double? Sum(this IEnumerable<double?> source);
         public static decimal Sum(this IEnumerable<decimal> source);
         public static decimal? Sum(this IEnumerable<decimal?> source);

         // Other overloads for selectors omitted for brevity
     }
 }
```

## Usage Examples

With the proposed change, the following code sample
``` C#
ulong PrivateCollectionSum => (ulong)somePrivateCollection.Sum(value => (long)value);
```
could become
``` C#
ulong PrivateCollectionSum => somePrivateCollection.Sum();
```

## Risks

Our sanity from having copy-pasted significant amounts of ungeneralizable code.

**Comment by eiriktsarpalis** [comment]
A `Sum()` overload over bytes or shorts is extremely likely to suffer from arithmetic overflow. In rare cases I can see how `ulong` might be useful but for other unsigned types probably not as much.

**Comment by AlFasGD** [comment]
> A `Sum()` overload over bytes or shorts is extremely likely to suffer from arithmetic overflow.
That was my thought as well, better leave them out.

> In rare cases I can see how `ulong` might be useful but for other unsigned types probably not as much.
It is true that those types are not used everyday, but if the functions work, the only thing that could prevent those overloads from being justifiably added is the statement below.

> Given the costs of adding new functions to LINQ, I don't think we could justify making any of these additions.
What's the cost of adding more functions to LINQ?

**Comment by eiriktsarpalis** [comment]
> What's the cost of adding more functions to LINQ?

Shared framework size primarily.

**Comment by AlFasGD** [comment]
Does adding 8 more functions to LINQ increase shared framework size by that much? I don't really know what the effects for that could be, so I'm just leaving this proposal open here.

**Comment by eiriktsarpalis** [comment]
It's just that we receive many requests for LINQ enhancements. Given the extensible nature of the library (missing overloads can be added as extension methods or even published as nuget packages), we generally err towards requiring evidence that the proposal provides value to many users (e.g. issue popularity, addition is not a one-liner etc.)

**Comment by eiriktsarpalis** [comment]
I'm going to close this issue for now. Thank you for contributing the proposal.
