### ISSUE TITLE
System.Diagnostics.Process.WorkingSet64 is static value in .Net Core 3.1

### ISSUE THREAD

**Issue by kalaskarsanket** [dotnet/runtime#46050]
---
**Issue moved from microsoft/dotnet#1277**
- Please respond to @ChristianKern97.

---

_From @ChristianKern97 on Tuesday, December 8, 2020 12:36:59 PM_

I'm using the WorkingSet64 endpoint to measure the RAM usage of multiple processes with my application, this worked fine, but for some reason it stopped working as it should and it only returns a static value, which is different for different processes but it is not updating. 
I only get this issue on Windows 10 with the newest updates. On my Windows Server 2019 everything works just fine. I tried using a PerformanceCounter instead but it had the same behaviour.
Another thing i tried is using .NET 5.0 but the same behaviour there.

My best guess is it has something to do with a recent Windows 10 update, but i have no clue.

**Comment by danmosemsft** [comment]
@ChristianKern97 are you remembering to call `Refresh()` on your process object? WorkingSet64 and other similar properties will not update otherwise.

Example here:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.workingset64?view=net-5.0

**Comment by svick** [comment]
@danmosemsft The example does call `Refresh()`, but the documentation does not mention it otherwise and it even talks about "the **current** size of working set". Shouldn't that be changed? (Though that would be a dotnet-api-docs issue, not a dotnet/runtime issue.)

**Comment by ChristianKern97** [comment]
Ok i did not call `Refresh()` and that is likely causing the issue.

The other thing is, that the `PerformanceCounter.NextValue()` also produces the same behaviour, if run on Windows 10, but works on Windows Server 2019.

**Comment by eiriktsarpalis** [comment]
@ChristianKern97 would you be able to provide a minimal repro of the behaviour? I tried running the following using `netcoreapp3.1` and couldn't detect anything out of the ordinary:

```csharp
static void Main()
{
    var proc = Process.GetCurrentProcess();
    var list = new List<byte[]>();

    while (true)
    {
        list.Add(new byte[1024]);
        Thread.Sleep(1000);
        proc.Refresh();
        Console.WriteLine(proc.WorkingSet64);
    }
}
```

**Comment by ChristianKern97** [comment]
Ok i have tried writing a minimal example. I used a Java process, because that is what i actually use in the real application.

``` CS
static void Main(string[] args)
{
    Process process = new Process();
    ProcessStartInfo startInfo = new ProcessStartInfo
    {
        UseShellExecute = false,
        FileName = "java",
        WorkingDirectory = @"C:\Users\chris\AppData\Roaming\Fork\Server(1)",
        Arguments = "-Xmx" + 2048 + "m -jar server.jar",
        WindowStyle = ProcessWindowStyle.Hidden,
        CreateNoWindow = true
    };
    process.StartInfo = startInfo;
    process.Start();
    while (!process.HasExited)
    {
        try
        {
            process.Refresh();
            Console.WriteLine(process.WorkingSet64 / (1024d * 1024d));
            Thread.Sleep(1000);
        }
        catch
        {
            break;
        }
    }
}
```

The output is a static value around 7 (MB) but the TaskManager, aswell as the windows created by the java process tell something else.

![grafik](https://user-images.githubusercontent.com/28393606/102234495-a159f600-3ef1-11eb-8793-7a1a1efd93fb.png)

**Comment by eiriktsarpalis** [comment]
We would need more information about the child process. I tried emulating your repro using the following code but still couldn't see anything out of the ordinary:
```csharp
static void Main(string[] args)
{
    if (args.Length > 0)
    {
        Console.Title = "Child Process";
        var currentProc = Process.GetCurrentProcess();
        var list = new List<byte[]>();
        while (true)
        {
            list.Add(new byte[1024]);
            Thread.Sleep(1000);
            currentProc.Refresh();
            Console.WriteLine(currentProc.WorkingSet64);
        }
    }
    else
    {
        Console.Title = "Parent Process";
        string currentExePath = Process.GetCurrentProcess().MainModule.FileName;
        var childProc = new Process()
        {
            StartInfo = new ProcessStartInfo(currentExePath, "--as-child")
            {
                UseShellExecute = true,
                WindowStyle = ProcessWindowStyle.Normal
            },
        };

        childProc.Start();

        while (!childProc.HasExited)
        {
            Thread.Sleep(1000);
            childProc.Refresh();
            Console.WriteLine(childProc.WorkingSet64);
        }
    }
}
```

cc @adamsitnik

**Comment by janvorli** [comment]
What if JAVA always created a child process to execute the code? In such case, the working set extracted in .NET would naturally not reflect the state of the process executing the JAVA code, but just the working set of the launcher.

**Comment by ChristianKern97** [comment]
@janvorli is actually right. I can't believe i didn't think of that.

Apperently Java 15 is handling it differently to java 8 and 11 which is weird but now i atleast know the problem. Thank you very much for helping me out everyone here!

**Comment by adamsitnik** [comment]
Since there is no bug I've just sent a PR to improve the docs based on @svick feedback: https://github.com/dotnet/dotnet-api-docs/pull/5174
