### ISSUE TITLE
EventLoggerFactoryExtensions seems to disregard filters

### ISSUE THREAD

**Issue by chucker** [dotnet/runtime#46064]
### Description

I have an ASP.NET Core app targeting `.net5.0-windows`. In my `Program.cs`, I call `ConfigureLogging` to customize the providers:

```csharp
webBuilder.ConfigureLogging((context, builder) =>
{
    builder.AddConfiguration(context.Configuration.GetSection("Logging"));

    builder.ClearProviders();
    builder.AddDebug();
    builder.AddEventLog(new Microsoft.Extensions.Logging.EventLog.EventLogSettings
    {
        SourceName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name
    });
});
```

In my `appsettings.Development.json`, I set the default log level to debug:

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

And finally, in a simple controller action, I do some logging:

```csharp
public IActionResult TestLogging()
{
    _Logger.LogInformation("Information");
    _Logger.LogWarning("Warning");
    _Logger.LogError("Error");

    return Ok();
}
```

At this point, I would assume:

* all those log messages should pass the minimum log level in the app settings,
* all of them should get picked up by both providers (Debug and EventLog)

However, while the VS's Output window does in fact show three log messages, the Windows event log only contains the latter two log messages; its minimum level appears to be `Warning`, _not_ `Debug`.

Indeed, if I change `appsettings.Development.json` to set the default level to `Error`, the Output window now only shows the error log message (as expected), but the event log _still_ shows both the warning and the error log messages.

I've tried explicitly setting the filter to pass all messages, and even that seems to have no effect:

```csharp
builder.AddEventLog(new Microsoft.Extensions.Logging.EventLog.EventLogSettings
{
    Filter = (category, level) => true,
    SourceName = System.Reflection.Assembly.GetExecutingAssembly().GetName().Name
});
```

### Expected behavior

The EventLog logger provider should behave just like the other logger providers (unless explicitly told otherwise). It should default to just taking the global minimum log level settings.

### Actual behavior

The EventLog logger provider seems to have its own filtering, and I can't seem to customize it.

### Configuration

<details>
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

### Regression?

Haven't checked, sorry.

### Other information

Even if I explicitly set `Filter` to `null` in `EventLogSettings`, the `Filter` propery in `logger._logger.MessageLoggers` is _not_ set to null. However, that might just reflect the default setting.

**Comment by danielklecha** [comment]
According to [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0#windows-eventlog) event log ignore default settings:
> The EventLog provider sends log output to the Windows Event Log. Unlike the other providers, the EventLog provider does not inherit the default non-provider settings. If EventLog log settings aren't specified, they default to LogLevel.Warning.
Configuration should be similar to this:
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventLog": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  }
}
```

**Comment by maryamariyan** [comment]
closing as per comment in https://github.com/dotnet/runtime/issues/46064#issuecomment-1092700983
