### ISSUE TITLE
StringLength attribute to limit length of strings inside an array

### ISSUE THREAD

**Issue by JulienM28** [dotnet/runtime#46072]
Hello,

Is it possible to make StringLength attribute validating length inside an array, just like that:

```csharp
[StringLength(256)]
public string[] Roles { get; set; }
```

Thanks.

**Comment by ajcvickers** [comment]
@JulienM28 Can you explain more what you mean by "inside an array?"

**Comment by JulienM28** [comment]
Sorry my english isn't good.

I have a string array and I want to validate that each string of the array matches the Stringlength requirement.

We made a custom validator for that :

```csharp
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public sealed class StringEnumerableItemMaxLengthAttribute : ValidationAttribute
    {
        public StringEnumerableItemMaxLengthAttribute(int maxLength)
        {
            MaxLength = maxLength;
        }

        public int MaxLength { get; }

        public override bool IsValid(object value)
        {
            if (!(value is IEnumerable<string> items)) return false;
            foreach (string item in items)
            {
                if (item.Length > MaxLength) return false;
            }
            return true;
        }
    }
```

It makes the job, but if the original StringLength attribute could validate stringlength of arrays, i t could be nice.

I hope it's more understandable this time.

Thanks.

**Comment by ajcvickers** [comment]
@JulienM28 Thanks for the suggestion, but the value here seems low so it's not something we plan to implement.
