### ISSUE TITLE
System.Memory package doesn't have CompilerServices.Unsafe dependency in .NETCoreApp 2.1

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#46082]
### Scenario

Have a class library:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.5.4" />
  </ItemGroup>
</Project>
```

```C#
using System;
using System.Runtime.CompilerServices;

namespace ClassLibrary8
{
    public class Class1
    {
        public static void PrintMessage()
        {
            Console.WriteLine(Unsafe.SizeOf<int>());
        }
    }
}
```

And a `netcoreapp2.1` program that references the class library and calls the method in it:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary8\ClassLibrary8.csproj" />
  </ItemGroup>
</Project>
```

```C#
using ClassLibrary8;

namespace NetCore21a
{
    class Program
    {
        static void Main(string[] args)
        {
            Class1.PrintMessage();
        }
    }
}
```

### Expected results

The program should execute correctly

### Actual results

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at ClassLibrary8.Class1.PrintMessage()
   at NetCore21a.Program.Main(String[] args) in C:\Users\eerhardt\source\repos\NetCore21a\Program.cs:line 10

C:\Program Files\dotnet\dotnet.exe (process 28248) exited with code -532462766.
Press any key to close this window . . .
```

### Notes

The issue appears to be that for `netstandard2.0`, `System.Memory` declares a dependency on `System.Runtime.CompilerServices.Unsafe`, and so any netstandard library using `System.Memory` gets the dependency transitively.

However, when a netcoreapp2.1 app references the library, it doesn't get the `System.Runtime.CompilerServices.Unsafe` dependency because System.Memory doesn't have any dependencies for 2.1:

![image](https://user-images.githubusercontent.com/8291187/102256951-af981a00-3ed1-11eb-846c-dbaedd213d3b.png)

And `CompilerServices.Unsafe` is not in the shared framework in .NET Core 2.1. Thus the assembly can't be found and it throws an exception.

This is the underlying issue that is being worked around in the ML.NET samples here: https://github.com/dotnet/machinelearning-samples/pull/870#discussion_r540966485

cc @joperezr @ericstj

**Comment by carlossanlop** [comment]
Ping @ericstj @joperezr can you please help with this issue?

**Comment by joperezr** [comment]
We know what is happening here, in fact I have already chatted about this with @eerhardt before he logged the issue. We don't have a very good solution for now, other than a) asking consuming libraries to manually reference unsafe as well (which would be hard to do) or b) to service System.Memory package and add the dependency for netcoreapp2.1 as well but that wouldn't be easy either since we don't build the package any longer so we would have to service it from an old release branch. For now, I would suggest to keep this issue open and use it as a ref-count, and if enough people are impacted by it we can then make a case for servicing it.

**Comment by ericstj** [comment]
Similar issue with JSON here: https://github.com/dotnet/runtime/issues/45560

**Comment by ericstj** [comment]
We have no plans to service System.Memory to fix this at the moment.  Workaround is to add a direct reference to System.Runtime.CompilerServices.Unsafe if your library uses it.
