### ISSUE TITLE
Assertion failed '!"Spill candidate has no assignedInterval recentRefPosition"' in 'System.Numerics.Tests.Vector2Tests:Vector2LerpTest7():this' during 'LSRA build intervals'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#46086]
https://dev.azure.com/dnceng/public/_build/results?buildId=921374&view=ms.vss-test-web.build-test-results-tab&runId=29267922&paneView=debug&resultId=173687

net6.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs0x80
net6.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs3

System.Numerics.Vectors.Tests

```
Assert failure(PID 26 [0x0000001a], Thread: 41 [0x0029]): Assertion failed '!"Spill candidate has no assignedInterval recentRefPosition"' in 'System.Numerics.Tests.Vector2Tests:Vector2LerpTest7():this' during 'LSRA build intervals' (IL size 71)

    File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 3496
    Image: /root/helix/work/correlation/dotnet
```

category:correctness
theme:register-allocator
skill-level:expert
cost:small

**Comment by BruceForstall** [comment]
@kunalspathak

**Comment by BruceForstall** [comment]
Also 

https://dev.azure.com/dnceng/public/_build/results?buildId=921368&view=ms.vss-test-web.build-test-results-tab&runId=29267344&resultId=174420&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

net6.0-Linux-Release-arm-CoreCLR_checked-jitstressregs0x80

System.Numerics.Vectors.Tests

**Comment by kunalspathak** [comment]
Is there a theme or label for register allocator related issues?

**Comment by BruceForstall** [comment]
There's a JIT-specific theme, e.g. you could add this to the end of the first comment:

category:correctness
theme:register-allocator
skill-level:expert
cost:small

see https://github.com/dotnet/runtime/issues/858

**Comment by kunalspathak** [comment]
I was able to repro this locally using altjit. Will start investigating.
