### ISSUE TITLE
.net core socket timeout in docker / linux

### ISSUE THREAD

**Issue by Ditriksss** [dotnet/runtime#46098]
Hello,
I've encountered with Socket problem on linux / docket. I've created entry at stackoverflow with my problem but after discuss with other developers, my issue seems to be more complicated. It is link where  I described my problem. ->https://stackoverflow.com/questions/65284251/net-core-socket-timeout-in-docker-linux

Problem occur only on linux / docker. There is no any issue / timeout on windows environment. I tested that in my local windows system. 
After about 4-5 minutes from connect to broadcaster and client, socket connected to client (in my case client is every ffmpeg) cannot send request what cause that socker responsible for download data from broadcaster can't do his work as well, something like one socket stop work other socket. I set Task.Delay to 1000ms and put together in Task.WhenAny task responsible for execute request and Task.Delay.
There is wondering that time when socket stop is always close to 4-5 minutes and at the docket stats network input is about 90-100 mb.

Thanks for every help!
Regards.

**Comment by wfurt** [comment]
Did you try to packet capture @Ditriksss ? The `SendAsync` will not complete if TCP shrinks windows to 0 (Wireshark should flag that) and when you fill up kernel socket buffers.

**Comment by karelz** [comment]
Triage: No response, closing. Feel free to reopen when there is more info available to make it actionable. Thanks!

**Comment by Ditriksss** [comment]
Hi @wfurt , sorry for delay. I checked packet capture by _tcpdump_. It looks like you wrote. After sent and read some number of data ,linux kernel dropped packets. 
I can't fnd any information about how to reset or clear buffer to be able to start listen. Additional I think that in my case, increasing buffer size is not appriopriate. I need way to restore buffer to beggining state or move connection to other socket.

**Comment by wfurt** [comment]
can you craft some simplified repro? Since you logic is somewhat complicated with extra synchronization, I'm wondering if there is issue somewhere in that logic. You can also use `strace` to see what kernel callas are being made and what status they return - to be sure before assuming kernel is dropping packets. You can also check firewall rules and possibly try to disable all or at least anything what may be related to rate limiting. 

cc @tmds for any other hints how to debug.

**Comment by Ditriksss** [comment]
Hello, I discovered what is wrong in my app. The problem is with ffmpeg program version I use. On windows I have correct version which doens't cause any problem. In docker image I have different version of this program. And in this version i have problem with connection after some times. It make something weird. There is no problem with .net. Thanks for replies and helping! 
Regards
