### ISSUE TITLE
Simple "build.cmd" from the repo root on Windows x64 fails with errors

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#46090]
## Repro:

Run simple "build.cmd" from the repo root on Windows x64 per https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md#concepts

## Expected result:

Build succeeds

## Actual result:

```
  CMake Error at CMakeLists.txt:636 (file):
    file STRINGS file "D://_version.h" cannot be read.


  CMake Error at CMakeLists.txt:637 (string):
    string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
    command.


  CMake Error at CMakeLists.txt:643 (file):
    file STRINGS file "D://runtime_version.h" cannot be read.


  CMake Error at CMakeLists.txt:644 (file):
    file STRINGS file "D://runtime_version.h" cannot be read.


  CMake Error at CMakeLists.txt:645 (file):
    file STRINGS file "D://runtime_version.h" cannot be read.


  CMake Error at CMakeLists.txt:646 (string):
    string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
    command.


  CMake Error at CMakeLists.txt:647 (string):
    string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
    command.


  CMake Error at CMakeLists.txt:648 (string):
    string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
    command.


  -- Skip building native EventPipe library test runner.
  -- Configuring incomplete, errors occurred!
  See also "D://CMakeFiles/CMakeOutput.log".
  See also "D://CMakeFiles/CMakeError.log".
D:\runtime\src\mono\mono.proj(331,5): error MSB3073: The command "set __repoRoot="D:\runtime\" && call "D:\runtime\eng\native\init-compiler-and-cmake.cmd" x64 &&  cmake -DCMAKE_INSTALL_PREFIX=D:\runtime\artifacts\obj\mono/windows.x64.Debug/out -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Debug -A x64 -DCMAKE_C_FLAGS="-DWIN32 -DWIN32_LEAN_AND_MEAN -DWIN64 -D_DEBUG -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32_THREADS -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -D_WIN32_IE=0x0501 -D_UNICODE -DUNICODE -DFD_SETSIZE=1024 -DNVALGRIND " -DCMAKE_CXX_FLAGS="-DWIN32 -DWIN32_LEAN_AND_MEAN -DWIN64 -D_DEBUG -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32_THREADS -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -D_WIN32_IE=0x0501 -D_UNICODE -DUNICODE -DFD_SETSIZE=1024 -DNVALGRIND " D:\runtime\src\mono\" exited with code 1.

Build FAILED.
```

**Comment by lambdageek** [comment]
There's something going on with paths with drive letters, maybe?
`"D://_version.h"` vs `D:\runtime\src\mono\mono.proj`

/cc @akoeplinger

**Comment by akoeplinger** [comment]
Hm this is weird since it suggests `CMAKE_CURRENT_BINARY_DIR` is set to `D:/` but it should be set to the build directory in artifacts/obj.

I'll need to create a D: partition on my Windows VM to try it out tomorrow.

@jkotas how are you launching the build.cmd? from cmd.exe/PS/Windows Terminal and are you launching it with the working directory in D:\runtime ?

**Comment by jkotas** [comment]
I am launching the build from "Visual Studio 2019 Developer Command Prompt", with working directory set to `d:\runtime`

**Comment by jkotas** [comment]
In case that it is relevant:
```
D:\>cmake --version
cmake version 3.16.0-rc1
```

**Comment by jkotas** [comment]
The problem repros with cmake version 3.19.1 too

**Comment by lambdageek** [comment]
@akoeplinger Trying something https://github.com/dotnet/runtime/pull/46145 - my guess is that cmake didn't like a mix of `\` and `/` in a single path for some reason.

**Comment by akoeplinger** [comment]
That can't hurt but I just tried reproducing it on my Windows VM and it works fine there...

**Comment by jkotas** [comment]
> #46145 

I have tried this change. It does not fix the problem.

**Comment by jkotas** [comment]
I have traced it down to the problems with current directory when invoking cmake. Here is the build command: `set __repoRoot="D:\runtime\" && call "D:\runtime\eng\native\init-compiler-and-cmake.cmd" x64 &&  cmake -DCMAKE_INSTALL_PREFIX ... D:\runtime\src\mono\`

The current directory when this command is starting is `D:\runtime\artifacts\obj\mono\windows.x64.Debug\`, but 
`init-compiler-and-cmake.cmd` changes the current directory to `D:\` and that's a problem.

Fails:
```
set __repoRoot="D:\runtime\"
call "D:\runtime\eng\native\init-compiler-and-cmake.cmd" x64
cmake -DCMAKE_INSTALL_PREFIX ... D:\runtime\src\mono\
```

Works:
```
set __repoRoot="D:\runtime\"
call "D:\runtime\eng\native\init-compiler-and-cmake.cmd" x64
cd D:\runtime\artifacts\obj\mono\windows.x64.Debug\
cmake -DCMAKE_INSTALL_PREFIX ... D:\runtime\src\mono\
```
