### ISSUE TITLE
Move remaining extensions packages to runtime repo.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#46091]
Packages still being built in extensions repo

- [x]   Microsoft.Extensions.Caching.SqlServer
- [x]   Microsoft.Extensions.Caching.StackExchangeRedis
- [x]   Microsoft.Extensions.Configuration.NewtonsoftJson
- [x]   Microsoft.Extensions.Hosting.Systemd
- [x]   Microsoft.Extensions.Hosting.WindowsServices
- [x]   Microsoft.Extensions.Http.Polly

Some of these will be moved to aspnetcore and we should move rest of them to runtime. It will help us reduce servicing cost and cost for maintaining an extra repo.

cc @ericstj

**Comment by ericstj** [comment]
cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Only the hosting and configuration packages remain in extensions. The others have already been moved.

**Comment by Anipik** [comment]
@ericstj should we move the remaining packages to runtime ?

**Comment by ericstj** [comment]
Yes, let’s do this as part of 6.0.

**Comment by eerhardt** [comment]
> Microsoft.Extensions.Configuration.NewtonsoftJson

Do we want to take a dependency on NewtonsoftJson in the `dotnet/runtime` repo?

The Hosting ones seem fine to me, since they don't have external dependencies.

**Comment by maryamariyan** [comment]
Would Microsoft.Extensions.Logging.Analyzers need to be shipped as part of runtime repo or stays in extensions? (reported issue: https://github.com/dotnet/extensions/issues/3434)?

**Comment by eerhardt** [comment]
> Would Microsoft.Extensions.Logging.Analyzers need to be shipped as part of runtime repo

If we are going to productize it, I would assume we would put it with the rest of our analyzers we build for the dotnet/runtime, which I believe are in https://github.com/dotnet/roslyn-analyzers/. (Just my opinion/thoughts)

**Comment by davidfowl** [comment]
Yes please
