### ISSUE TITLE
System.Reflection setting static fields of pointer types silently fails

### ISSUE THREAD

**Issue by acaly** [dotnet/runtime#46118]
### Description

```c#
public unsafe class TestClass
{
    public static IntPtr Field1;
    public static int* Field2;
    public static float Field3;
}

public static void Main()
{
    IntPtr value = (IntPtr)1;
    typeof(TestClass).GetField("Field1").SetValue(null, value); //Success.
    typeof(TestClass).GetField("Field2").SetValue(null, value); //Silently fail. <===
    typeof(TestClass).GetField("Field3").SetValue(null, value); //Throw ArgumentException.
}
```

The above code cannot set value for Field2. The SetValue call returns without the field being changed. Note that this only happens for static fields. Instance fields can be properly set.

### Configuration

Windows 10 Professional 19041
Visual Studio 16.8.2
.NET Core 5
Compiled with AnyCPU, x86-preferred off. Other options give same result.

### Regression

Same behavior when running on NET Core 3.1.

**Comment by DaZombieKiller** [comment]
I've experienced this under Mono too. I had to resort to special casing pointers with a `DynamicMethod` to set the field as an `IntPtr`:

```cs
static Action<T> CreateStaticSetter<T>(FieldInfo field)
{
    var method = new DynamicMethod(string.Empty, null, new[] { typeof(T) }, true);
    var il     = method.GetILGenerator();

    il.Emit(OpCodes.Ldarg_0);
    il.Emit(OpCodes.Stsfld, field);
    il.Emit(OpCodes.Ret);

    return (Action<T>)method.CreateDelegate(typeof(Action<T>));
}
```
```cs
CreateStaticSetter<IntPtr>(field).Invoke(new IntPtr(address));
```

**Comment by krwq** [comment]
Hey @acaly @DaZombieKiller 

This works correctly for me:

```csharp
using System;

namespace ConsoleApp21
{
    public unsafe class TestClass
    {
        public static IntPtr Field1;
        public static int* Field2;
        public static float Field3;
    }
    class Program
    {
        static void Main(string[] args)
        {
            IntPtr ptr = new IntPtr(3);
            unsafe
            {
                typeof(TestClass).GetField("Field2").SetValue(null, (nint)ptr);
                Console.WriteLine((int)TestClass.Field2); // prints 3
            }
        }
    }
}
```

would that be acceptable solution for you?

**Comment by acaly** [comment]
@krwq Thank you for the reply. I tried the code again. As you said, it works as expected. 

I think I was trying to read the result from VS immediate window, which would give you zero even the console writes 3. It might not be the problem from reflection, because directly assigning the value would also fail from showing up in VS. I am sorry for not checking carefully.

**Comment by krwq** [comment]
no problem @acaly. Do you think issue can be closed now or do you expect the follow up work here?

**Comment by acaly** [comment]
I think this could probably be closed now. Thanks!
