### ISSUE TITLE
HttpListenerContext::AcceptWebSocketAsync should have a nullable annotation for the subProtocol

### ISSUE THREAD

**Issue by euantorano** [dotnet/runtime#46123]
## Background and Motivation

The method [`AcceptWebSocketAsync`](https://github.com/dotnet/runtime/blob/86224fd11c943ebe111c602358f8b8d3c3fb7494/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerContext.cs#L36) on the `HttpListenerContext` class currently takes a `string subProtocol`. When using `#nullable enable`, the compiler warns about passing null to this parameter, but doing so is totally valid behaviour and indicates no sub-protocol should be used.

Note that passing an empty string (`string.Empty`) is **not** valid and causes an exception to be thrown during validation.

The code eventually gets in to [`HttpWebSocket::ValidateOptions()`](https://github.com/dotnet/runtime/blob/86224fd11c943ebe111c602358f8b8d3c3fb7494/src/libraries/System.Net.HttpListener/src/System/Net/WebSockets/HttpWebSocket.cs#L79) which has an explicit check for `subProtocol` begin null, but the parameter is also not marked as nullable there.

Note that currently to ignore the compiler warning you can call the method as follwos:

```C#
await ctx.AcceptWebSocketAsync(null!);
```

## Proposed API

**UPDATE** by @antonfirsov: included all 4 overloads.

```diff
public class HttpListenerContext
{
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment<byte> internalBuffer);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment<byte> internalBuffer);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, TimeSpan keepAliveInterval);
+    public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, TimeSpan keepAliveInterval);
}
```

_Note: There are several overloads of this method, and it ends up calling these overloads and other methods to validate options - these will also need alterations._

## Usage Examples

``` C#
WebSocketContext webSocketCtx = await httpContext.AcceptWebSocketAsync(null);
```

## Alternative Designs

N/A

## Risks

N/A

**Comment by antonfirsov** [comment]
I think this is an overlook we should fix. Note that the repro code in #45934 also uses `context.AcceptWebSocketAsync(null!)` to overcome this problem.

**Comment by karelz** [comment]
Triage: This is simple, we should just do it, though it is not pressing. @antonfirsov can you please send quick email to API review, then mark it up-for-grabs and easy? Thanks!

**Comment by euantorano** [comment]
I made a start at some of the changes for this [in my branch](https://github.com/euantorano/runtime/commit/3d1bcace7e1e05be70dc66228a9162b033893c5c), but haven't tested it or anything. It should show the kind of changes needed as far as I can tell, though jumping between projects and solution does make life difficult.

**Comment by karelz** [comment]
@euantorano looks good to me (I think you are missing ref changes).
If you can help us identify all the public API changes needed, that would be great. I assume it will be just the 4 overloads:
https://github.com/dotnet/runtime/blob/8c48ae89ef229c293d233f0e30d755df81d564e5/src/libraries/System.Net.HttpListener/ref/System.Net.HttpListener.cs#L48-L51

**Comment by euantorano** [comment]
> @euantorano looks good to me (I think you are missing ref changes).
> If you can help us identify all the public API changes needed, that would be great. I assume it will be just the 4 overloads:
> https://github.com/dotnet/runtime/blob/8c48ae89ef229c293d233f0e30d755df81d564e5/src/libraries/System.Net.HttpListener/ref/System.Net.HttpListener.cs#L48-L51

Ah, yes I hadn't noticed/realised about the refs! Yes, I think it will just be the 4 overloads, but I'll double check.

**Comment by antonfirsov** [comment]
I don't see more `subProtocol` parameters in System.Net.HttpListener classes, so updated the proposal to include the 4 overloads above, and sent an email to the API review committee.

@euantorano if you think there are more, please let us know so we can react.

**Comment by terrajobst** [comment]
As discussed over email, this makes sense.
