### ISSUE TITLE
[Task/ValueTask] Perf regression on Net 5 vs NetCore 3.1

### ISSUE THREAD

**Issue by En3Tho** [dotnet/runtime#46130]
While I was observing benchmarks of Ply (library focused on fast task support for F#) I noticed regression in Net 5 vs NetCore 3.1:

F# part of benchmark + runner code : https://github.com/crowded/ply/blob/master/Benchmarks/Benchmarks.fs
C# part of benchmark: https://github.com/crowded/ply/blob/master/Benchmarks/CS/Benchmarks.cs

I modified project with BDN v. 12.1 nuget, edited global json to allow forward to Net 5 and also added 
[<SimpleJob(RuntimeMoniker.NetCoreApp50, targetCount = 15)>]
[<SimpleJob(RuntimeMoniker.NetCoreApp31, targetCount = 15)>]
attributes to TaskBuildersBenchmark class

It seems like there is stable regression compared to NetCore 3.1. Here are results:

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.685 (2004/?/20H1)
AMD Ryzen 7 3700X, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100
  [Host]     : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT DEBUG
  Job-HCTHOY : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT
  Job-KMEWHC : .NET Core 5.0.0 (CoreCLR 5.0.20.51904, CoreFX 5.0.20.51904), X64 RyuJIT

IterationCount=15 

GC stats (same every run) :
|                  Method |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |----------:|------:|------:|----------:|
|                     Ply | 3571.4286 |     - |     - |  28.62 MB |
| 'TaskBuilder.fs v2.1.0' | 3571.4286 |     - |     - |  28.62 MB |
|        'C# Async Await' | 1125.0000 |     - |     - |   9.54 MB |

Run 1

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-RBVRXD | .NET Core 3.1 | 83.61 ms | 0.627 ms | 0.587 ms |  1.17 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-RBVRXD | .NET Core 3.1 | 82.28 ms | 0.864 ms | 0.808 ms |  1.15 |    0.02 |
|        'C# Async Await' | Job-RBVRXD | .NET Core 3.1 | 71.52 ms | 1.307 ms | 1.223 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-AGATUI | .NET Core 5.0 | 83.39 ms | 1.360 ms | 1.272 ms |  1.05 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-AGATUI | .NET Core 5.0 | 86.14 ms | 1.530 ms | 1.431 ms |  1.08 |    0.03 |
|        'C# Async Await' | Job-AGATUI | .NET Core 5.0 | 79.63 ms | 1.159 ms | 1.085 ms |  1.00 |    0.00 |

Run 2

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-BZNDSX | .NET Core 3.1 | 84.73 ms | 0.807 ms | 0.715 ms |  1.15 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-BZNDSX | .NET Core 3.1 | 85.42 ms | 0.915 ms | 0.856 ms |  1.16 |    0.02 |
|        'C# Async Await' | Job-BZNDSX | .NET Core 3.1 | 73.63 ms | 1.293 ms | 1.210 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-BZSUIO | .NET Core 5.0 | 89.03 ms | 0.924 ms | 0.864 ms |  1.19 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-BZSUIO | .NET Core 5.0 | 86.88 ms | 0.995 ms | 0.931 ms |  1.16 |    0.02 |
|        'C# Async Await' | Job-BZSUIO | .NET Core 5.0 | 74.95 ms | 1.235 ms | 1.156 ms |  1.00 |    0.00 |

Run 3

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-ZCXIWA | .NET Core 3.1 | 84.95 ms | 0.743 ms | 0.659 ms |  1.15 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-ZCXIWA | .NET Core 3.1 | 85.60 ms | 1.300 ms | 1.216 ms |  1.16 |    0.04 |
|        'C# Async Await' | Job-ZCXIWA | .NET Core 3.1 | 73.69 ms | 1.767 ms | 1.652 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-RVHZOV | .NET Core 5.0 | 86.60 ms | 0.688 ms | 0.644 ms |  1.16 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-RVHZOV | .NET Core 5.0 | 84.60 ms | 0.985 ms | 0.921 ms |  1.13 |    0.03 |
|        'C# Async Await' | Job-RVHZOV | .NET Core 5.0 | 74.60 ms | 1.747 ms | 1.634 ms |  1.00 |    0.00 |

Run 4

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-RVREQO | .NET Core 3.1 | 84.05 ms | 0.686 ms | 0.608 ms |  1.16 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-RVREQO | .NET Core 3.1 | 82.04 ms | 1.069 ms | 1.000 ms |  1.13 |    0.02 |
|        'C# Async Await' | Job-RVREQO | .NET Core 3.1 | 72.50 ms | 1.042 ms | 0.975 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-LXSQQD | .NET Core 5.0 | 85.32 ms | 0.876 ms | 0.819 ms |  1.12 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-LXSQQD | .NET Core 5.0 | 83.48 ms | 0.594 ms | 0.556 ms |  1.10 |    0.02 |
|        'C# Async Await' | Job-LXSQQD | .NET Core 5.0 | 76.04 ms | 1.182 ms | 1.106 ms |  1.00 |    0.00 |

Run 5

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-HCTHOY | .NET Core 3.1 | 82.38 ms | 0.573 ms | 0.536 ms |  1.16 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-HCTHOY | .NET Core 3.1 | 84.08 ms | 1.001 ms | 0.887 ms |  1.18 |    0.03 |
|        'C# Async Await' | Job-HCTHOY | .NET Core 3.1 | 71.32 ms | 1.642 ms | 1.536 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-KMEWHC | .NET Core 5.0 | 89.35 ms | 0.736 ms | 0.652 ms |  1.15 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-KMEWHC | .NET Core 5.0 | 86.54 ms | 1.167 ms | 1.092 ms |  1.12 |    0.02 |
|        'C# Async Await' | Job-KMEWHC | .NET Core 5.0 | 77.53 ms | 1.412 ms | 1.321 ms |  1.00 |    0.00 |

**Comment by En3Tho** [comment]
Update with Net 5.0.1 results. There are 2 outliers, so i've made more runs. But general picture is the same: Net 5 is slower most of the time.

un 1

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-WSTSNG | .NET Core 3.1 | 81.62 ms | 0.922 ms | 0.817 ms |  1.08 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-WSTSNG | .NET Core 3.1 | 85.19 ms | 0.576 ms | 0.511 ms |  1.12 |    0.04 |
|        'C# Async Await' | Job-WSTSNG | .NET Core 3.1 | 75.80 ms | 2.530 ms | 2.243 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-EKORSW | .NET Core 5.0 | 86.67 ms | 0.701 ms | 0.621 ms |  1.22 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-EKORSW | .NET Core 5.0 | 86.55 ms | 0.768 ms | 0.718 ms |  1.22 |    0.02 |
|        'C# Async Await' | Job-EKORSW | .NET Core 5.0 | 70.77 ms | 1.105 ms | 1.034 ms |  1.00 |    0.00 |

Run 2

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-LXBFOX | .NET Core 3.1 | 81.62 ms | 0.931 ms | 0.871 ms |  1.18 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-LXBFOX | .NET Core 3.1 | 81.38 ms | 0.651 ms | 0.609 ms |  1.18 |    0.03 |
|        'C# Async Await' | Job-LXBFOX | .NET Core 3.1 | 69.17 ms | 1.542 ms | 1.442 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-UZRTDB | .NET Core 5.0 | 82.35 ms | 0.760 ms | 0.711 ms |  1.17 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-UZRTDB | .NET Core 5.0 | 87.30 ms | 0.927 ms | 0.822 ms |  1.24 |    0.03 |
|        'C# Async Await' | Job-UZRTDB | .NET Core 5.0 | 70.41 ms | 1.732 ms | 1.620 ms |  1.00 |    0.00 |

Run 3

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-TWTTAK | .NET Core 3.1 | 82.95 ms | 0.797 ms | 0.745 ms |  1.23 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-TWTTAK | .NET Core 3.1 | 87.15 ms | 0.510 ms | 0.477 ms |  1.29 |    0.03 |
|        'C# Async Await' | Job-TWTTAK | .NET Core 3.1 | 67.38 ms | 1.483 ms | 1.387 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-FYLTJI | .NET Core 5.0 | 86.47 ms | 0.968 ms | 0.808 ms |  1.24 |    0.01 |
| 'TaskBuilder.fs v2.1.0' | Job-FYLTJI | .NET Core 5.0 | 87.46 ms | 0.631 ms | 0.591 ms |  1.25 |    0.01 |
|        'C# Async Await' | Job-FYLTJI | .NET Core 5.0 | 69.78 ms | 0.839 ms | 0.785 ms |  1.00 |    0.00 |

Run 4

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-JOTMAC | .NET Core 3.1 | 85.42 ms | 0.671 ms | 0.628 ms |  1.28 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-JOTMAC | .NET Core 3.1 | 86.79 ms | 0.694 ms | 0.615 ms |  1.30 |    0.02 |
|        'C# Async Await' | Job-JOTMAC | .NET Core 3.1 | 66.70 ms | 1.108 ms | 1.037 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-OWAVGV | .NET Core 5.0 | 87.11 ms | 1.009 ms | 0.944 ms |  1.18 |    0.04 |
| 'TaskBuilder.fs v2.1.0' | Job-OWAVGV | .NET Core 5.0 | 89.83 ms | 0.527 ms | 0.493 ms |  1.21 |    0.04 |
|        'C# Async Await' | Job-OWAVGV | .NET Core 5.0 | 74.17 ms | 2.289 ms | 2.141 ms |  1.00 |    0.00 |

Run 5

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-BDSNHU | .NET Core 3.1 | 86.52 ms | 0.747 ms | 0.699 ms |  1.24 |    0.04 |
| 'TaskBuilder.fs v2.1.0' | Job-BDSNHU | .NET Core 3.1 | 85.16 ms | 0.825 ms | 0.731 ms |  1.22 |    0.04 |
|        'C# Async Await' | Job-BDSNHU | .NET Core 3.1 | 69.83 ms | 2.115 ms | 1.978 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-HWHQWQ | .NET Core 5.0 | 81.59 ms | 0.446 ms | 0.417 ms |  1.15 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-HWHQWQ | .NET Core 5.0 | 84.79 ms | 0.704 ms | 0.659 ms |  1.19 |    0.02 |
|        'C# Async Await' | Job-HWHQWQ | .NET Core 5.0 | 71.16 ms | 1.314 ms | 1.230 ms |  1.00 |    0.00 |

Run 6

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|
|                     Ply | Job-HOZZQR | .NET Core 3.1 | 85.34 ms | 0.812 ms | 0.720 ms |  1.23 |    0.03 |
| 'TaskBuilder.fs v2.1.0' | Job-HOZZQR | .NET Core 3.1 | 86.08 ms | 0.903 ms | 0.845 ms |  1.24 |    0.03 |
|        'C# Async Await' | Job-HOZZQR | .NET Core 3.1 | 69.26 ms | 1.645 ms | 1.539 ms |  1.00 |    0.00 |
|                         |            |               |          |          |          |       |         |
|                     Ply | Job-IRKJAZ | .NET Core 5.0 | 89.79 ms | 0.679 ms | 0.635 ms |  1.25 |    0.02 |
| 'TaskBuilder.fs v2.1.0' | Job-IRKJAZ | .NET Core 5.0 | 86.73 ms | 0.920 ms | 0.861 ms |  1.21 |    0.02 |
|        'C# Async Await' | Job-IRKJAZ | .NET Core 5.0 | 71.87 ms | 1.338 ms | 1.186 ms |  1.00 |    0.00 |

Run 7

|                  Method |        Job |       Runtime |     Mean |    Error |   StdDev | Ratio | RatioSD |     Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------ |----------- |-------------- |---------:|---------:|---------:|------:|--------:|----------:|------:|------:|----------:|
|                     Ply | Job-SDATYR | .NET Core 3.1 | 83.20 ms | 0.779 ms | 0.729 ms |  1.22 |    0.02 | 3571.4286 |     - |     - |  28.62 MB |
| 'TaskBuilder.fs v2.1.0' | Job-SDATYR | .NET Core 3.1 | 85.39 ms | 0.649 ms | 0.607 ms |  1.25 |    0.02 | 3571.4286 |     - |     - |  28.62 MB |
|        'C# Async Await' | Job-SDATYR | .NET Core 3.1 | 68.06 ms | 1.039 ms | 0.921 ms |  1.00 |    0.00 | 1125.0000 |     - |     - |   9.54 MB |
|                         |            |               |          |          |          |       |         |           |       |       |           |
|                     Ply | Job-CRWZDJ | .NET Core 5.0 | 86.87 ms | 0.720 ms | 0.674 ms |  1.20 |    0.03 | 3500.0000 |     - |     - |  28.62 MB |
| 'TaskBuilder.fs v2.1.0' | Job-CRWZDJ | .NET Core 5.0 | 84.37 ms | 0.799 ms | 0.747 ms |  1.16 |    0.03 | 3571.4286 |     - |     - |  28.62 MB |
|        'C# Async Await' | Job-CRWZDJ | .NET Core 5.0 | 72.48 ms | 1.775 ms | 1.660 ms |  1.00 |    0.00 | 1125.0000 |     - |     - |   9.54 MB |

**Comment by adamsitnik** [comment]
cc @stephentoub

**Comment by adamsitnik** [comment]
@stephentoub is this something that we are aware of?

**Comment by stephentoub** [comment]
I just tried the repro, comparing .NET Core 3.1 to .NET 7.  I updated the fsproj/csproj to have `<TargetFrameworks>netcoreapp3.1;net7.0</TargetFrameworks>`, updated the BenchmarkDotNet PackageReferences to use version 0.13.4, deleting the global.json, and deleted the SimpleJob attributes, and then I ran the benchmarks with:
```
dotnet run -c Release -f netcoreapp3.1 --runtimes netcoreapp3.1 net7.0
```

If there was a regression, it's gone now:

|                  Method |       Runtime |     Mean |    Error |   StdDev | Ratio |
|------------------------ |-------------- |---------:|---------:|---------:|------:|
|                     Ply | .NET Core 3.1 | 71.56 ms | 0.926 ms | 0.866 ms |  1.12 |
|                     Ply |      .NET 7.0 | 58.68 ms | 0.571 ms | 0.507 ms |  0.92 |
| 'TaskBuilder.fs v2.1.0' | .NET Core 3.1 | 71.29 ms | 0.576 ms | 0.481 ms |  1.11 |
| 'TaskBuilder.fs v2.1.0' |      .NET 7.0 | 58.58 ms | 0.396 ms | 0.371 ms |  0.92 |
|        'C# Async Await' | .NET Core 3.1 | 64.02 ms | 0.706 ms | 0.660 ms |  1.00 |
|        'C# Async Await' |      .NET 7.0 | 48.26 ms | 0.319 ms | 0.299 ms |  0.75 |

Closing. Thanks.
