### ISSUE TITLE
there seems to be a way to accelerate GC of objects with finalizer

### ISSUE THREAD

**Issue by ygc369** [dotnet/runtime#4613]
When GC of generation 1 or 2 finishes, all garbage objects with finalizer should be moved to heap zone of generation 0. Thus, these objects would be collected next generation 0 GC after their finalizers are called.

**Comment by ygc369** [comment]
@vancem 
I think that the current behavior is close to a bug, because it delays the reuse of freed memory for no reason. What I proposed should be considered as a way to fix the "bug", not an optimazation.

**Comment by ygc369** [comment]
@Maoni0 
How do you think about this idea?

**Comment by VSadov** [comment]
Here is how finalization works at the high level:
- in addition to regular reachability, finalized objects are rooted for finalization purpose.
- When that root is the last one, the object is added to finalization queue.
- After finalizer runs the finalization root is severed.
- If the object is no longer reachable, the next GC will make its space available to new allocations.

There are two metrics that could be improved in the whole scenario - how soon the finalizer runs and how soon the originally occupied space is reclaimed.

Neither of these metrics can be helped by copying the finalized object to Gen0 region.

**Comment by VSadov** [comment]
I do not see how this can work. An example or a prototype could be helpful. 
As-is this is not an actioanable issue.

**Comment by ygc369** [comment]
@VSadov 

> There are two metrics that could be improved in the whole scenario - how soon the finalizer runs and how soon the originally occupied space is reclaimed.
Neither of these metrics can be helped by copying the finalized object to Gen0 region.

"how soon the originally occupied space is reclaimed"---- I think this metric can be helped by copying the finalized object to Gen0 region, because Gen0 GC always happens before Gen1 or Gen2 GCs.

**Comment by VSadov** [comment]
I think a confusing part is that there is no such thing as "moving" an object. What is possible is to "copy" to a new location and redirect all the references.
To find the references you need to scan the heap. That is too expensive to do for one object.

GC performs such scan for all objects up to a given generation. That makes the cost much lower per-object, but does not make it lower in a whole.

As you see - one way or another a GC (or equivalent amount of work) needs to happen to ensure that the original location is no longer referenced and can be reclaimed/collected.

**Comment by ygc369** [comment]
@VSadov 

> To find the references you need to scan the heap. That is too expensive to do for one object.

No, there is no need to scan the heap. Please reread my description:

> When GC of generation 1 or 2 finishes, all garbage objects with finalizer should be moved to heap zone of generation 0. 

And look at your previous comment:

> When that root is the last one, the object is added to finalization queue.

It means that all objects in finalization queue has no other roots, so there is no need to scan the heap to find their references. It is safe to move(or copy) these objects to Gen0 directly. (As these objects might revive after their finalizer is called, the movement need to happen before finalizer runs, I think the movement should happen during GC's compacting period.)

**Comment by VSadov** [comment]
Being not rooted does not imply not being referenced. An object in finalization can and often is still referenced by other objects in the finalization queue or by objects referenced by them indirectly. Any of these objects may become rooted again.
