### ISSUE TITLE
Mono Functional Tests Follow Up 

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46155]
This is a follow up issue to address @safern's comments in:

https://github.com/dotnet/runtime/pull/45768#issuecomment-746758470

https://github.com/dotnet/runtime/blob/93e767bd18975bf33d64177f6849c12d7505d206/eng/testing/tests.targets#L51-L52

**Comment by safern** [comment]
Ha it seems like @radical and you reacted at the same time: https://github.com/dotnet/runtime/issues/46156#issuecomment-746806707

**Comment by steveisok** [comment]
His is better :-)
