### ISSUE TITLE
renable/fix /Loader/classloader/generics/Variance/Methods 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#46161]
https://github.com/dotnet/runtime/blob/03e4f5e36410203a7ebab55ac177c166406ea1fe/src/tests/issues.targets#L83 references https://github.com/dotnet/runtime/issues/3893 that was closed a long time ago (and looks unrelated to these tests).

The tests are failing now on windows x64:
```
 "D:\Sergey\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe" Method002.dll
Test Failed at location: Test001 @ count 1
Test Failed at location: Test002 @ count 2
Test Failed at location: Test003 @ count 3
Test Failed at location: Test004 @ count 4
Test Failed at location: Test005 @ count 5
Test Failed at location: Test006 @ count 6
Test Failed at location: Test101 @ count 7
Test Failed at location: Test102 @ count 8
Test Failed at location: Test103 @ count 9
Test Failed at location: Test104 @ count 10
Test Failed at location: Test105 @ count 11
Test Failed at location: Test106 @ count 12
Total test cases: 12  Failed test cases: 12
```
they should get an updated issue or be fixed and reenabled.

**Comment by sandreenko** [comment]
Are these AssemblyLoader tests? PTAL @agocke @vitek-karas

**Comment by agocke** [comment]
It looks like the issue number for these was incorrectly changed in https://github.com/dotnet/runtime/pull/32236. The tag for #84 looked correct. Also, sounds like these are VM tests, not loader.

**Comment by sandreenko** [comment]
Ah, so the issue number was already from the new repo when we replaced old coreClr issue number with the new Runtime issues.
I will update the number, thanks @agocke
