### ISSUE TITLE
Shift Types for Bitarray

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#46169]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1220576/shift-types-for-bitarray.html)._

---
<p>Hello, please add more shift types for binary collection of Bitarray like circular shift and many other shift types that are available in internet.</p> <p>Thanks.</p>

---
#### Touraj Ostovari on 10/14/2020, 01:47 PM: 

<p>I mean from shift types is shift operations types.</p>

#### Feedback Bot on 10/15/2020, 02:45 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

#### Touraj Ostovari on 11/12/2020, 09:58 AM: 

<p>Hello, please add more shift tasks to bitarray and guide developers what they are doing and which type of shift they are.</p>

**Comment by TourajOstovari** [comment]
Rotate able bit array
for example when one bit from right side moves to left side should be last bit of array replaced in first column, this circular bit array moving should remain again and again while user calls the method.
I have one idea at the moment in my mind now.

**Comment by eiriktsarpalis** [comment]
Hi @TourajOstovari, would you be able to file an issue follow the [api review process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md)? Basically we'd need a list of the new proposed APIs as well as a few code samples.

**Comment by TourajOstovari** [comment]
check here please
https://github.com/dotnet/runtime/issues/46669#issuecomment-756089799

**Comment by eiriktsarpalis** [comment]
Thanks, closing in favor of that issue.
