### ISSUE TITLE
ANSI escape sequences (Console) don't work correctly in Linux Terminals starting with .NET 5.0

### ISSUE THREAD

**Issue by kpreisser** [dotnet/runtime#46165]
### Description

Hi, we discovered an issue with .NET 5.0.1 (probably also 5.0.0), where [virtual terminal/ANSI escape sequences](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences) that are written to the Console don't seem to work correctly in Linux terminal emulators like the Gnome Terminal (at least in Ubuntu 18.04 and 20.04 x64) and LXTerminal (Raspbian). This doesn't occur when using .NET Core 3.1.10.

To reproduce:
- Create a new project with `dotnet new console`.
- Edit `Program.cs` to contain the following code:
```cs
using System;

class Program
{
    static void Main(string[] args)
    {
        string s =
            "\x1b[35;43mXY\x1b[0m\n" + 
            "-----------------------------------------------------------\n" +
            "-----------------------------------------------------------\n" +
            "-----------------------------------------------------------\n" +
            "-----------------------------------------------------------\n" +
            "\x1b[35;43mXY\x1b[0m\n";

        Console.Out.Write(s);
    }
}
```
- Run the program with `dotnet run` in the Gnome Terminal.

**Expected output** (like when running with .NET Core 3.1.10):
![grafik](https://user-images.githubusercontent.com/13289184/102400092-ba41d480-3fe1-11eb-8ee1-8fb1167735fd.png)

**Actual output** (running with .NET 5.0.1):
![grafik](https://user-images.githubusercontent.com/13289184/102400177-d5acdf80-3fe1-11eb-8d2e-c5e1075f8a5e.png)

The issue seems to be related how the bytes are split when writing them to the console (as by default `Console.Out` uses a `StreamWriter` with a 256 char buffer).
For example, when you directly write a whole byte array in one go to the stream returned by `Console.OpenStandardOutput()`, the terminal sequences are interpreted correctly:
```c#
    static void Main(string[] args)
    {
        string s = "AB\x1b[35;43mXY\x1b[0m\n";
        var bytes = Encoding.UTF8.GetBytes(s);

        using var stream = Console.OpenStandardOutput();
        stream.Write(bytes);
    }
```
![grafik](https://user-images.githubusercontent.com/13289184/102400711-9e8afe00-3fe2-11eb-9f96-3389e68ee585.png)

But when you split the bytes in the middle of the escape sequence, the terminal seems to stop interpreting the sequence at the split position (whereas on .NET Core 3.1 the output is the same as above):
```cs
    static void Main(string[] args)
    {
        string s = "AB\x1b[35;43mXY\x1b[0m\n";
        var bytes = Encoding.UTF8.GetBytes(s);

        using var stream = Console.OpenStandardOutput();
        int splitPos = 5;
        stream.Write(bytes.AsSpan()[..splitPos]);
        stream.Write(bytes.AsSpan()[splitPos..]);
    }
```
![grafik](https://user-images.githubusercontent.com/13289184/102400838-bcf0f980-3fe2-11eb-85ce-06be8774eada.png)

Interestingly, this issue only seems to occur for the first split. When writing again split byte arrays (that are split in the terminal sequence), it works correctly.

**Edit:** This issue can also be reproduced on other terminals, e.g. when running Ubuntu on WSL:
![grafik](https://user-images.githubusercontent.com/13289184/102534539-3520f300-40a7-11eb-8c48-eeb7f3f63ce7.png)

### Configuration

* .NET SDK 5.0.101
* OS: Ubuntu 20.04 LTS, x64
* Using the Gnome Terminal app

### Regression?

Yes, this worked correctly in .NET Core 3.1.10.

### Workaround

<del>Use a writer that doesn't split a string into multiple byte spans, so that escape sequences are always written in a single write call to the underlying console stream.</del>

**Edit:** Calling `GC.KeepAlive(Console.WindowWidth);` (within a `try`-`catch`) before writing anything to the console should be sufficient to work-around the issue (see post below).

Thank you!

**Comment by kpreisser** [comment]
From looking at the code, I think this may be caused by [`ConsolePal.EnsureInitializedCore`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L920). which seems to be called once **after** the first byte span is written to stdout (which wasn't the case in .NET Core 3.1):

The `UnixConsoleStream` retrieved by `Console.Out` calls [`ConsolePal.Write`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1230), which calls [`UpdatedCachedCursorPosition`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1281) after a write succeeded:
https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1267-L1274

That function in turn calls [`ConsolePal.GetWindowSize`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L367) and maybe [`ConsolePal.TryGetCachedCursorPosition`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L289),  which both call [`ConsolePal.CheckTerminalSettingsInvalidated`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1350). That one calls [`EnsureConsoleInitialized`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L911) in .NET 5.0 which was introduced with **#41317**:
https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L1350-L1353

When called for the first time, this then calls [`EnsureInitializedCore`](https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L920) which (I guess) may write something to the terminal, thus corrupting the previously written start of an escape sequence.

This function bails out early when stdin has been redirected:
https://github.com/dotnet/runtime/blob/1e747e32fc3b0b16cdf40871b48a5d37fd5803e3/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L920-L927

When I therefore run the test program again and redirect stdin, the escape sequence actually works correctly:
![grafik](https://user-images.githubusercontent.com/13289184/102549090-db76f380-40bb-11eb-9a12-35cb353fc5c2.png)

**Comment by eiriktsarpalis** [comment]
Thanks for the analysis @kpreisser. I can confirm that reverting #41317 makes the issue go away. We should definitely fix this and probaby also service for 5.0. @tmds is there anything preventing us from calling `EnsureConsoleInitialized` on initialization of `UnixConsoleStream` objects?

**Comment by tmds** [comment]
> is there anything preventing us from calling EnsureConsoleInitialized on initialization of UnixConsoleStream objects?

The sequence that scrambles up the user output is written by `SetKeypadXmit`. We need to make sure `EnsureConsoleInitialized` gets called before the user starts writing. Initialization of `UnixConsoleStream` is a good place.

**Comment by tmds** [comment]
```cs
 private static void CheckTerminalSettingsInvalidated() 
 { 
     // Register for signals that invalidate cached values. 
     EnsureConsoleInitialized(); 
```

This is calling `EnsureConsoleInitialized` too late. We need to remove it (and maybe replace it with a `Debug.Assert(s_initialized)`).

**Comment by tmds** [comment]
@eiriktsarpalis I look into writing a fix if you want.

**Comment by eiriktsarpalis** [comment]
Would be happy to provide as well. Just to confirm, would inserting an `EnsureConsoleInitialized()` at the beginning of the `ConsolePal.Write` (or perhaps the UnixConsoleStream constructor) suffice? Or is there any reason why we wouldn't want to initialize it that early?

**Comment by tmds** [comment]
You can see what is written by the app by using `strace -f -e write`. For the Program from above this is:
```
[pid  4594] write(19, "\33[35;43mXY\33[0m\n-----------------------------------------------------------\n-----------------------------------------------------------\n-----------------------------------------------------------\n-----------------------------------------------------------\n\33", 256) = 256
strace: Process 4613 attached
[pid  4594] write(1, "\33[?1h\33=", 7)  = 7
[pid  4594] write(19, "[35;43mXY\33[0m\n", 14) = 14
```

You can see the string getting split by the `SetKeypadXmit` write in `EnsureConsoleInitialized`.

> would inserting an EnsureConsoleInitialized() at the beginning of the ConsolePal.Write (or perhaps the UnixConsoleStream constructor) suffice?

Yes.

> Or is there any reason why we wouldn't want to initialize it that early?

I think we try to minimize any configuration done to the terminal to avoid potential side-effects.
One major side effect is resetting the terminal at exit, I removed it for .NET 6 in https://github.com/dotnet/runtime/commit/d6887d4aeec045aa4d708463abdfb6e071660dc8.

**Comment by tmds** [comment]
@eiriktsarpalis based on what you said, I think you will create a PR for this, which I will review?
If we backport this, maybe we should consider including https://github.com/dotnet/runtime/commit/d6887d4aeec045aa4d708463abdfb6e071660dc8 also.
I think the issue is triggered by the user writing ansi escape sequences themselves. It is a specific use-case. The `ConsoleLogger` from `Microsoft.Extensions.Logging` does this also, so it may be affected as well.

**Comment by eiriktsarpalis** [comment]
Yes, will do today. Apologies, was distracted by other issues.

**Comment by tmds** [comment]
No worries, I just wanted to check. You can look at it further when you have time.
