### ISSUE TITLE
[Mono][Wasm] Performance Regression 78 % on CreateInstanceGeneric	

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#46170]
This looks like it may have been caused by this change: https://github.com/dotnet/runtime/commit/804d730d2fd8a57dbe9c0a3118800b1288993ecd

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [88680a4c00bdb9b00a9b83691536d53cfbe840fa](https://github.com/dotnet/runtime/commit/88680a4c00bdb9b00a9b83691536d53cfbe840fa)
Compare | [be0efd358453d2dbea7821caa328352c25012c2a](https://github.com/dotnet/runtime/commit/be0efd358453d2dbea7821caa328352c25012c2a)

### Regressions in System.Reflection.Activator<EmptyClass>

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CreateInstanceGeneric](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Reflection.Activator(EmptyClass).CreateInstanceGeneric.html>) | 930.16 ns | 1.64 μs | 1.76 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Reflection.Activator(EmptyClass)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Activator(EmptyClass).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Reflection.Activator<EmptyClass>*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4dec4741-1997-4d90-ac82-b6d7161f093ac78f28de08f401fa4/7a463628-51cd-4284-8632-41054f60b654.zip?sv=2019-07-07&se=2020-12-26T15%3A47%3A58Z&sr=c&sp=rl&sig=L9%2FWe4TdrwDiFXqCsW%2FF7r6z7bkAfva4nu7PIoRx3hU%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4cd77183-20a2-4be0-a22f-e1dd4c3622bdda4d183104e4837b3/3b43d0c9-cf5a-432d-a6b5-6085902ac5ce.zip?sv=2019-07-07&se=2020-12-27T05%3A11%3A51Z&sr=c&sp=rl&sig=eKu9DKlMIsMt0sHJxDdw%2BniJJp2uWDrjhX%2F8vWHCMzg%3D>)

#### System.Reflection.Activator<EmptyClass>.CreateInstanceGeneric

```log
[ 821.732 ;  864.320) | @@@
[ 864.320 ;  910.863) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 910.863 ;  958.209) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 958.209 ; 1006.314) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1006.314 ; 1060.152) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1060.152 ; 1108.056) | @@@@@@@@@@@@@@@@@@@@@@@@@
[1108.056 ; 1148.807) | @@@@@@
[1148.807 ; 1197.742) | @
[1197.742 ; 1245.087) | 
[1245.087 ; 1292.432) | 
[1292.432 ; 1339.777) | 
[1339.777 ; 1387.122) | 
[1387.122 ; 1434.467) | 
[1434.467 ; 1481.813) | 
[1481.813 ; 1533.110) | 
[1533.110 ; 1577.035) | @@@@
[1577.035 ; 1624.380) | @@@@@@@
[1624.380 ; 1685.056) | @@
[1685.056 ; 1732.401) | 
[1732.401 ; 1774.503) | 
[1774.503 ; 1821.848) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [88680a4c00bdb9b00a9b83691536d53cfbe840fa](https://github.com/dotnet/runtime/commit/88680a4c00bdb9b00a9b83691536d53cfbe840fa)
Compare | [be0efd358453d2dbea7821caa328352c25012c2a](https://github.com/dotnet/runtime/commit/be0efd358453d2dbea7821caa328352c25012c2a)

### Regressions in System.Reflection.Activator<EmptyStruct>

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CreateInstanceGeneric](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Reflection.Activator(EmptyStruct).CreateInstanceGeneric.html>) | 836.36 ns | 1.50 μs | 1.80 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Reflection.Activator(EmptyStruct)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro/System.Reflection.Activator(EmptyStruct).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Reflection.Activator<EmptyStruct>*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4dec4741-1997-4d90-ac82-b6d7161f093ac78f28de08f401fa4/7a463628-51cd-4284-8632-41054f60b654.zip?sv=2019-07-07&se=2020-12-26T15%3A47%3A58Z&sr=c&sp=rl&sig=L9%2FWe4TdrwDiFXqCsW%2FF7r6z7bkAfva4nu7PIoRx3hU%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4cd77183-20a2-4be0-a22f-e1dd4c3622bdda4d183104e4837b3/3b43d0c9-cf5a-432d-a6b5-6085902ac5ce.zip?sv=2019-07-07&se=2020-12-27T05%3A11%3A51Z&sr=c&sp=rl&sig=eKu9DKlMIsMt0sHJxDdw%2BniJJp2uWDrjhX%2F8vWHCMzg%3D>)

#### System.Reflection.Activator<EmptyStruct>.CreateInstanceGeneric

```log
[ 776.637 ;  804.583) | @@@@
[ 804.583 ;  844.418) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 844.418 ;  884.019) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 884.019 ;  922.623) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 922.623 ;  959.204) | @@@@@@@
[ 959.204 ;  998.805) | 
[ 998.805 ; 1038.407) | 
[1038.407 ; 1078.008) | 
[1078.008 ; 1117.609) | 
[1117.609 ; 1157.210) | 
[1157.210 ; 1196.811) | 
[1196.811 ; 1236.413) | 
[1236.413 ; 1276.014) | 
[1276.014 ; 1315.615) | 
[1315.615 ; 1355.216) | 
[1355.216 ; 1394.817) | 
[1394.817 ; 1414.144) | 
[1414.144 ; 1453.745) | @@@@@@
[1453.745 ; 1505.760) | @@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by lewing** [comment]
@kg any thoughts

**Comment by jkotas** [comment]
#46173 has fix for this regression. It reverts the code flow on Mono to what it was before 804d730.

**Comment by lambdageek** [comment]
Our implementation of the  `this` check https://github.com/dotnet/runtime/blob/10381a2cdc33860f0dc649b24cbb703d23b9ea33/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs#L1684-L1697 does quite a lot of expensive-ish things.  I think `ContainsGenericParameters` does a lot of reflection.

**Comment by kg** [comment]
That whole method seems like it should only run once.
