### ISSUE TITLE
Automate the servicing process of packages

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#46178]
Currently the developers have to add the versioning changes on the top of their change for the packages.
These changes include incrementing the package version, assembly version, package index changes & finally enabling to build the packages.
The goal here is to automate all the steps. The developer should be able to set single property and rest should be automated.

- [ ] package version 
- [ ] Assembly version
- [ ] Enabling build

- Package version:- we can get the latest stable version from the packageIndex and increment that before the pack task.
- Assembly Version:- It contains 2 steps, first part is to determine if we need to update the assembly version and second version is to update it for what tfms.
We need to update the assembly version for all assets if the assembly targets netfx. We can update the assembly version for all tfms if the assembly is not part of any ref pack otherwise we will need to update only for netfx. (TBD on implementation)
- Enabling Build:- Running the build on pkgproj if a certain ship property is set.

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
> We need to update the assembly version for all assets if the assembly targets netfx. We can update the assembly version for all tfms if the assembly is not part of any ref pack otherwise we will need to update only for netfx. (TBD on implementation)

How would you know that a certain assembly is part of the shared framework for previous releases? Should we just up `.NETFramework` and `.NETStandard` ones to make this consistent?

> Running the build on pkgproj if a certain ship property is set.

We already have couple of such properties [defined by Arcade](https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#isshipping-isshippingassembly-isshippingpackage-isshippingvsix-bool). Could we reuse those or do we need a new one?

**Comment by ViktorHofer** [comment]
> Package version:- we can get the latest stable version from the packageIndex and increment that before the pack task

Is the goal of your packaging infra work to keep the packageIndex or to get rid of it? How would we get the latest stable version without the index? I'm unsure if setting the PackageVersion should be an explicit action...
