### ISSUE TITLE
Reverse P/Invokes should notify profiler when transitioning between unmanaged and managed

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#46177]
Today, the runtime notifies the profiler when an unmanaged<->managed transition happens in the following scenarios:

- P/Invokes on all platforms
- COM->CLR calls on Windows
- CLR->COM calls on Windows
- Reverse P/Invokes on Windows x86 only

We should either notify the profiler about transitions for all Reverse P/Invokes or none (probably all).

cc: @noahfalk @AaronRobinsonMSFT

**Comment by davmason** [comment]
Thanks for reporting this, if you have any other context could we capture that? Do you know why we only notify on x86 for reverse pinvokes? Is it due to IL stubs not being on x86?

**Comment by jkoritzinsky** [comment]
On x86 we use a dynamically emitted assembly stub that wraps the IL stub. That assembly stub is what emits the profiler notifications. On other platforms we just use the IL stubs, so nothing is calling the profiler.

**Comment by jkotas** [comment]
I assume that you mean `UnmanagedCallersOnly` methods. Is that right?

Marshaled delegates that are sometimes also called reverse PInvoke should be fine.

**Comment by jkoritzinsky** [comment]
From what I could tell both delegate reverse pinvoke and UnmanagedCallersOnly reverse pinvoke are the same for this case.

**Comment by jkotas** [comment]
FWIW, `DirectStubLinker::EmitProfilerBeginTransitionCallback` is supposed to handle the delegate reverse pinvoke case.

**Comment by jkoritzinsky** [comment]
Fixed by #46238
