### ISSUE TITLE
[Question] How to set the entry assembly in .Net 5.0

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/runtime#46191]
In .Net Framework, I was able to set the entry assembly using the following code:
```
AppDomainManager manager = new AppDomainManager();
FieldInfo entryAssemblyfield = manager.GetType().GetField("m_entryAssembly", BindingFlags.Instance | BindingFlags.NonPublic);
entryAssemblyfield.SetValue(manager, assembly);

AppDomain domain = AppDomain.CurrentDomain;
FieldInfo domainManagerField = domain.GetType().GetField("_domainManager", BindingFlags.Instance | BindingFlags.NonPublic);
domainManagerField.SetValue(domain, manager);
```

In .Net 5.0, I can't find a way to set the entry assembly. It is quite useful because I have a dependency on an assembly that uses `Assembly.GetEntryAssembly()` and I was able to change what it returned.

I hope that there is a solution because it is a major blocker for me to migrate to .Net 5.0 from .Net Framework 4.8.

Thank you.

**Comment by vitek-karas** [comment]
The code you used on .NET Framework relied on private reflection over framework types. Basically it relies on knowing internal details of .NET Framework implementation. The implementation in .NET Core is different, so the fact that it doesn't work anymore is not surprising. Also - private reflection over framework assemblies is generally not supported - we want to be able to change the implementation without worrying about breaking applications due to things like renames or refactorings.

So the real solution would have to be a public API to implement such functionality. Feel free to [propose the API](https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md&title=).

**Comment by ThomasGoulet73** [comment]
My question was not really about having a supported and public API to set the entry assembly. What I want to do is probably an edge case and I don't think it would be a good public API. I'd be perfectly comfortable doing something not officially supported like I did with the reflection on private field.

Thank you.

**Comment by vitek-karas** [comment]
I don't think it's actually possible in .NET Core - without changes to the runtime/corelib. The only place where the entry assembly is set is here: https://github.com/dotnet/runtime/blob/262d44875080ff7421b314f7c6f580a92e471701/src/coreclr/vm/assembly.cpp#L1644

The value is stored in native and calling `Assembly.GetEntryAssembly` will call into native to get it.

I don't see a way to intercept this without runtime changes.

**Comment by am11** [comment]
I think best approach would be to ask the dependency library author to make `GetEntryAssembly()` usage optional for your use-case. However, if it is not possible, there is a way with compiler services to replace methods during run-time, [for example](https://stackoverflow.com/a/36415711/863980).

<details>
  <summary>Code</summary>

assumed third-party classlib code:
```c#
// project file: somelib.csproj

using System;
using System.Reflection;
public class SomeClass
{
    public void Work() => Console.WriteLine(Assembly.GetEntryAssembly());
}
```

your executable project (myexe.cpsoj):
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="../somelib/bin/Release/net5.0/somelib.dll" />
  </ItemGroup>
</Project>
```

```c#
using System;
using System.Reflection;
using System.Runtime.CompilerServices;

class Program
{
    static void Main()
    {
        var someClass = new SomeClass();
        Console.Write("Before:"); someClass.Work();
        ReplaceGetEntryAssembly();
        Console.Write("After: "); someClass.Work();
    }

    private Assembly MyGetEntryAssembly() => typeof(System.Text.Json.JsonSerializer).Assembly;

    private static unsafe void ReplaceGetEntryAssembly()
    {
        MethodInfo methodToReplace = typeof(Assembly).GetMethod("GetEntryAssembly", BindingFlags.Instance | BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);
        MethodInfo methodToInject = typeof(Program).GetMethod("MyGetEntryAssembly", BindingFlags.Instance | BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);

        RuntimeHelpers.PrepareMethod(methodToReplace.MethodHandle);
        RuntimeHelpers.PrepareMethod(methodToInject.MethodHandle);

        long* inj = (long*)methodToInject.MethodHandle.Value.ToPointer() + 1;
        long* tar = (long*)methodToReplace.MethodHandle.Value.ToPointer() + 1;

        byte* injInst = (byte*)*inj;
        byte* tarInst = (byte*)*tar;

        int* injSrc = (int*)(injInst + 1);
        int* tarSrc = (int*)(tarInst + 1);

        *tarSrc = (((int)injInst + 5) + *injSrc) - ((int)tarInst + 5);
    }
}
```
</details>

.NET5 on macOS x64 with both; Debug and Release, prints:

```
Before: myexe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
After: System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
```

**Comment by jkotas** [comment]
> However, if it is not possible, there is a way with compiler services to replace methods during run-time, for example.

This hack is even less supported than private reflection

**Comment by agocke** [comment]
Closing this out as we are unlikely to change anything here

**Comment by am11** [comment]
@jkotas, it was in response to OP's " I'd be perfectly comfortable doing something not officially supported like I did with the reflection on private field"

**Comment by davidfowl** [comment]
Hack level over 9000
