### ISSUE TITLE
Math.Round() doesn't work correctly for some values

### ISSUE THREAD

**Issue by gerakul** [dotnet/runtime#46203]
Math.Round() doesn't work correctly on some values with option MidpointRounding.ToZero.
Example:
```
        static void Main(string[] args)
        {
            double value = 1.009;
            int precision = 3;
            double roundedValue = Math.Round(value, precision, MidpointRounding.ToZero);

            Console.WriteLine($"Rounded value is {roundedValue} but expected to be {value}");
        }
```
In the code above expected roundedValue should be 1.009 but it returns 1.008. The same error with
value = 1.0009; precision = 4;
value = 1.00009; precision = 5;
value = 1.000009; precision = 6;

Tested in the console application netcoreapp3.1 and net5.0

**Comment by Clockwork-Muse** [comment]
```csharp
double value = 1.009;
```

.. you think the value is actually `1.009`, but it's not.  Doubles are not power-of-10 (ie, `1009X10^-3`), but power-of-two.  Doing something like:

```
// Prints out "1.0089999999999999"
Console.WriteLine(1.009.ToString("G17"));
```
... reveals that the value is less than the literal `1.009`

**Comment by danmosemsft** [comment]
Right, I was about to write the same thing. Put another way
```c#
            Console.WriteLine("{0:X16}", BitConverter.DoubleToInt64Bits(1.009d));
            Console.WriteLine("{0:X16}", BitConverter.DoubleToInt64Bits(1.0089999999999999d));
```
prints
```
3FF024DD2F1A9FBE
3FF024DD2F1A9FBE
```

The rounding is performed by multiplying by 1E3 then truncating then dividing by 1E3. This essentially gives 1008.999999 then truncates to 1008 then results in 1.008.

What are you trying to achieve? If you need complete precision you may want to use the Decimal type instead.

**Comment by gerakul** [comment]
I ran into this while working with some legacy code. I just thought it was not what you'd expect to see truncating the number 1.009 to the precision 3. Decimal type works of course. 
Thank you for the explanation, closing then.

**Comment by danmosemsft** [comment]
Thanks for the report though @gerakul . 

And shameless plug - we welcome contributions if you are interested in anything else.

https://github.com/dotnet/runtime/labels/easy
https://github.com/dotnet/runtime/labels/up-for-grabs
https://github.com/dotnet/runtime/blob/master/CONTRIBUTING.md
