### ISSUE TITLE
HttpClient not logging failure when request pipeline interrupted

### ISSUE THREAD

**Issue by christopheblin** [dotnet/runtime#46216]
### Description

When using .NET core, you have a really nice abstraction to intercept HTTP "events" as very well described in https://www.stevejgordon.co.uk/httpclientfactory-asp-net-core-logging for ex.

However, when you use that, you face a problem when the target host is not available : the inner code of HttpClient throws a SocketException or IOException and the logger is never called, so some events like RequestPipelineEnd are never triggered.

In my personal case, what I'd like to do is logging a single message for each HTTP request.
This is not possible with the current default implementation ...
However, you also have the problem if you do not customize the filter (i.e in the logs, you see a "Start processing HTTP request" but never anything else)

There should be a new event like "RequestFailure" that allows the logging infrastructure to catch this situation and to log something useful by default.

### Configuration

I'm using .NET Core 3.1, but I do not think it is relevant only to this version

**Comment by CarnaViire** [comment]
There's new telemetry for networking implemented in .NET 5, you may read about it and find examples in the article here https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#telemetry
The complete list of events is [here](https://github.com/dotnet/runtime/issues/37428#issuecomment-674597327), which also contains `RequestAborted` for request failures that you've mentioned.
Will that help?

**Comment by christopheblin** [comment]
Unfortunately, I am not able to test .Net 5 before some months... 


From what I read in the blog, it seems that it will be possible to log requestpipelineend and requestaborted, so it should solve my issue...

**Comment by karelz** [comment]
OK, closing as answered / addressed then. If you find evidence there are still more things missing, please file a new issue. Thanks!
