### ISSUE TITLE
SSL Handshake failed on linux 

### ISSUE THREAD

**Issue by Pt4r** [dotnet/runtime#46212]
### Description
I'm running a Core 3.1 application in a linux CentOS 7 server which connects to an external SSL-secured API.

The app is running as expected on several Windows development machines but when i run it on an Ubuntu wsl ( openssl v 1.1.1f ) or the CentOS 7 server ( openssl v 1.0.7k ) i get the error SSL Handshake failed, wrong signature.
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---> Interop+Crypto+OpenSslCryptographicException: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
--- End of inner exception stack trace ---
at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
--- End of inner exception stack trace ---
```

When i used ssldump and Wireshack to inspect the packets sent through the wire i saw that the server responds with ACK RST.

### Reproduction Steps

Create a new Core 3.1 Console app with the following simple code

```C#
using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var credentials = new
            {
                Username = "test",
                Password = "12345"
            };
            var credentials2 = new
            {
                Username = "test",
                Password = "12345"
            };
            var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (httpRequestMessage, certificate, chain, sslPolicyErrors) => true
            };
            using (var http = new HttpClient(handler))
            {
                http.BaseAddress = new Uri("https://www.mapfreassistancetracker.com");
                try
                {
                    var jsonRequest = "{ \"company\": \"this wont work\" }";
                    var httpRequest = new HttpRequestMessage(HttpMethod.Post, "/");
                    httpRequest.Content = new StringContent(jsonRequest, Encoding.UTF8, "application/json");
                    // Assign basic auth header based on client code
                    httpRequest.Headers.Authorization = new BasicAuthenticationHeaderValue(credentials.Username,credentials.Password);
                    var response = await http.SendAsync(httpRequest);
                    if (response.IsSuccessStatusCode) {
                        Console.WriteLine("worked");
                    }
                    Console.WriteLine(await response.Content.ReadAsStringAsync());
                    
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                }
            }

            Console.ReadLine();
        }
    }
}
```

Because of the test data, the response we expect to get back would be something like
```
{"errorData":[{"status":"INTERNAL_SERVER_ERROR","errorCode":9223372036854775807,"errorMessage":"fatal.error.message","detailErrorInfo":"Could not read JSON: No data info in request body; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: No data info in request body","bindingErrors":null,"resultType":"BLOCKER_ERROR","errorType":"BLOCKER_ERROR"}]}
```

### Configuration

* What OS and version, and what distro if applicable?
CentOS 7 with openssl 1.0.7k
* Do you know whether it is specific to that configuration?
Was only successful on openssl 1.1.1g

dotnet --info on CentOS server
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
### Other information

This issue is similar but not the same with #30667 

The only workarounds i've found so far are to:
* Update openssl to v 1.1.1g - _but this is not possible in CentOS 7 since it is not supported and we have to update to CentOS 8 https://pkgs.org/download/openssl._
* Set CipherString = DEFAULT@SECLEVEL=1 in the /etc/ssl/openssl.cnf config file - _but this doesnt seem to work as mentioned here https://github.com/openssl/openssl/issues/7126#issuecomment-542315974._
* Install side-by-side openssl v 1.1.1g and use the environment variable CLR_OPENSSL_VERSION_OVERRIDE to pick a specific version when calling this endpoint - _this hasn't been tested._

Also, this is the SSL Report by SSLlabs https://www.ssllabs.com/ssltest/analyze.html?d=www.mapfreassistancetracker.com, please see the Windows Certification Paths #3

**Comment by wfurt** [comment]
can you post the packet captures and either share URL for the server or at least post results from SSL scanner like https://www.ssllabs.com/ssltest/index.html @Pt4r? 
While this describes the issue well, it is really not actionable without more info. 

From the description it seems like the server did not like either the supported protocols or cipher list. Running scanner and seeing ClientHello should give some answers. 
Also, can you connect to the server with `openssl s_client -connect ip:port` ? 

As some background, .NET will use  /etc/ssl/openssl.cnf only in 5.0 and OpenSSL 1.1.0 and above.

cc: @tmds to see if there is recommended packaging solution for Centos 7.

**Comment by wfurt** [comment]
I did miss the URL in repro code @Pt4r. I will take a look. The site still supports weak ciphers so even OpenSSL 1.0 should be ok IMHO.

**Comment by wfurt** [comment]
can you use? 
```
https://centos.pkgs.org/7/epel-x86_64/openssl11-libs-1.1.1g-1.el7.x86_64.rpm.html
```
This is what my Centos7 system had. I removed that, and your repro still works for me with OpenSSL 1.0 (and without BasicAuthenticationHeaderValue) 
```
[root@cent repro]# strace -o trace.txt -f -e trace=file /tmp/repro/bin/Debug/netcoreapp3.1/linux-x64/publish/repro
worked
{}

[root@cent repro]# grep libcrypto trace.txt
1510  open("/lib64/libcrypto.so.10", O_RDONLY|O_CLOEXEC) = 43
[root@cent repro]# rpm -qf /lib64/libcrypto.so.10
openssl-libs-1.0.2k-19.el7.x86_64
```

so it seems like this is somehow specific you your setup...?

**Comment by Pt4r** [comment]
@wfurt thank you for troubleshooting this issue!

After testing again in a clean environment this console app seems to work on our Centos system too but the actual app which does exactly the same thing (using HttpClient with HttpMessageHandler) didn't. 

What eventually made it work was the following:
1. Update to openssl 1.1.1g (CentOS 7 didn't seem to mind)
2. Create symlink from the local installation of openssl (/usr/local/bin/openss) to the CentOS bin folder (/usr/bin). This seemed to make the nginx service running our app recognize the 1.1.1g openssl and successfully completed the SSL Handshake.

The problem seemed to be that the installation of the 1.1.1g openssl was placed at the /usr/local/bin folder which was not accessible from the nginx user running our app as a service.
