### ISSUE TITLE
Convert JsonElment to Object of Type

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#46234]
## Background and Motivation

I've json wich is parsed in backend, but only after the first parse I know the type of some of the parameters wich are Propertys of Type "object" in my class.

So after the first parse I walk through the result, and change the types of the JsonElments

at the moment it could be solved like this:

                                        var bufferWriter = new ArrayBufferWriter<byte>();
                                        using (var writer = new Utf8JsonWriter(bufferWriter))
                                        {
                                            je.WriteTo(writer);
                                        }

                                        JsonSerializer.Deserialize(bufferWriter.WrittenSpan, parameterInfo.ParameterType);

but this is inperformant, cause I need to create a string, parse it again to create the object.

## Proposed API

JsonSerializer.Deserialize should also work with a JsonElement

## Additional

The JsonElment should have a Value Property wich returns the "Value" as the correctType

**Comment by jogibear9988** [comment]
maybe dup of https://github.com/dotnet/runtime/issues/40393

**Comment by layomia** [comment]
Dup of https://github.com/dotnet/runtime/issues/40393.
