### ISSUE TITLE
Event source should have a good trimming experience

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#46231]
## Goals

- [x] Event source should not produce warnings by default
- [X] ~Event source should only produce actionable warnings if tracing is enabled~
- [X] Event source is annotated and doesn't produce interior warnings

## Work

- [x] Finish event source feature switch
 - [X] ~If diagnostic tracing is attached, produce diagnostic about tracing being disabled~

**Comment by eerhardt** [comment]
> Event source should not produce warnings by default

This work should take care of the 2nd row in https://github.com/dotnet/runtime/issues/45623: `System.Private.CoreLib - EventSource`.

**Comment by agocke** [comment]
We think EventSource types in the framework are now trim-compatible, and the appropriate warnings are produced for other EventSource providers. There's no more trimming work planned at the moment.
