### ISSUE TITLE
SemanticVersion parsing fails for versions with build metadata but not prerelease tag. ie 1.0.0+asdf

### ISSUE THREAD

**Issue by majaeger** [dotnet/runtime#46230]
### Description

SemanticVersion parsing fails for versions with build metadata but not prerelease tag. ie 1.0.0+asdf
Repro:
(From powershell core)
[semver]::Parse('5.1.0+asdf')
MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
Expected:
Major: 5
Minor: 1
Patch: 0
Prerelease:
BuildLabel: asdf

From the semver spec: https://semver.org/#spec-item-10
Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch **or** pre-release version.

### Configuration

All

### Regression?

Appears broken from introduction of SemanticVersion API support for semver v2

**Comment by jkotas** [comment]
`semver` package lives in https://github.com/maxhauser/semver. Could you please open this issue in there instead?
