### ISSUE TITLE
NTLM Authentication not working in .NET Core on Mac

### ISSUE THREAD

**Issue by JeroenBer** [dotnet/runtime#46247]
### Description

I Found that NTLM is not working correctly for .NET Core on Mac. To reproduce this I created a web page on Azure protected by NTLM and wrote some unit tests to validate the NTLM behavior. It is working correctly in all scenario's on .NET Core on Windows but for .NET Core on Mac it doesn't work correctly in a lot of scenario's:

## Test results
|Platform|Use NetworkCredentials|Use CredentialCache|
|-|-|-|
|Windows .NET Core 2.1|Success|Success|
|Windows .NET Core 3.1|Success|Success|
|Windows .NET Core 5.0|Success|Success|
|Mac .NET Core 2.1|FAIL|Success|
|Mac .NET Core 3.1|FAIL|Success|
|Mac .NET Core 5.0|FAIL|FAIL|

The tests can be found in this public github project: https://github.com/JeroenBer/testntlm

### Configuration

Run the .NET Core NTLM tests on Windows 10 (x64) from Visual Studio 2019 and they will all Succeed.
Run the same .NET Core tests in Visual Studio on Mac and they will partly fail (or fully on .NET Core 5.0)

### Other information

I did not try the tests on Linux but they might also fail there.

**Comment by JeroenBer** [comment]
area-System.Net.Http
@Dotnet-GitSync-Bot

**Comment by wfurt** [comment]
NTLM on macOS never worked AFAIK - see #887. It is interesting you report it working as well it is interesting to see change in 5. For 2.1 we used curl directly so the implementation come with it.

**Comment by JeroenBer** [comment]
Yes it certainly works on Mac .NET Core (2/3) if you add the following line:

```
 AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```

The main reason for posting this because we liked to get this fixed in .NET Core since Xamarin is also going to be part of .NET Core 6. And NTLM is also a problem in Xamarin Android/iOS/Mac, there is a workaround there using the old MonoWebRequestHandler but I think this should be solved in .NET Core so it will be fixed once and for all. Is there any way to get this on the roadmap for .NET Core to have proper NTLM support on all platforms ?

**Comment by karelz** [comment]
Android/Xamarin solution is tracked separately in #32680

**Comment by karelz** [comment]
Closing this issue in favor of #887 and #32680
