### ISSUE TITLE
Why .NET Core Source Code need a lot of “#if !CORECLR static #endif” on method?

### ISSUE THREAD

**Issue by shps951023** [dotnet/runtime#46246]
E.g: Github [dotnet/runtime/String.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/String.cs) source code
```C#
        private
#if !CORECLR
        static
#endif
        string Ctor(char[]? value)
        {
            if (value == null || value.Length == 0)
                return Empty;

            string result = FastAllocateString(value.Length);

            Buffer.Memmove(
                elementCount: (uint)result.Length, // derefing Length now allows JIT to prove 'result' not null below
                destination: ref result._firstChar,
                source: ref MemoryMarshal.GetArrayDataReference(value));

            return result;
        }
```

![](https://i.imgur.com/iunWvQZ.png)
![](https://i.stack.imgur.com/iVTBb.png)

It seems to work pretty well without adding this, and the maintenance cost will become higher.  
Is it for performance reasons?

**Comment by benaadams** [comment]
That file is in the `/libraries/` Is shared between Mono, CoreClr and CoreRT; as the majority of the method is identical other than the `static` I assume it's less maintenance just to `#if` the `static` rather than duplicate the code

**Comment by jkotas** [comment]
It would be nice to fix the CoreCLR convention for string constructors so that this ifdef is not necessary. The convention used on other runtimes is a tiny bit more efficient (avoids unnecessary dummy `this` pointer).

**Comment by shps951023** [comment]
@benaadams @jkotas
thanks !
