### ISSUE TITLE
string.Join with ReadOnlySpan values parameter

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#46255]
## Background and Motivation

Using ```string.Join``` to concatenate a given slice or a larger string array. Let's say we would batch items of a larger string array, and concatenate that given batch with string join operation. The ```(ReadOnly)Span<string>``` with slicing seems a good fit for the job, but ```string.Join``` does have an overload that accepts a span, so we would need to call ToArray() on it or maintain a start index.

## Proposed API

```csharp
public partial class String
{
    // ...
    public static string Join(char separator, ReadOnlySpan<string?> values);

    public static string Join(string? separator, ReadOnlySpan<string?> values);
}
```

Today there in an existing overload respectively: 

```public static string Join(char separator, string?[] value, int startIndex, int count)```
 
but that means we need to maintain startIndex inside a loop, instead of just taking the next slice of the remaining, to achieve the same. (See the example below.)

## Usage Examples

```csharp
const int batchSize = 3;

void Sample(ReadOnlySpan<string> data)
{
    while (data.Length > batchSize)
    {
        Console.WriteLine(string.Join(',', data.Slice(0, batchSize)));
        data = data.Slice(batchSize);
    }
    Console.WriteLine(string.Join(',', data));
}
```
## Further Considerations

Current ```string``` class implementation does already have a ```string.JoinCore``` method with signature of ```ReadOnlySpan<string?> values```, but the visibility is private: https://source.dot.net/#System.Private.CoreLib/String.Manipulation.cs,db8c8e8f4424e39d

This proposal is not suggesting to make JoinCore public, but to provide an overload on the ```string.Join```.

**Comment by huoyaoyuan** [comment]
The benifit should be very limited, because the allocation overhead of string collection is smaller than string itself. Moreover, you cannot do `stackalloc string[10]`.

The really benificial option should be `ReadOnlySpan<ReadOnlySpan<char>>` which is not supported by CLR now.

**Comment by ladeak** [comment]
When you have less access on the original 'large array' as in the **Usage Examples** from above, your option with string.Join is to call ```ToArray()``` and maintain a startIndex to actually do the join, or as an alternative use ```StringBuilder``` and manually join the string parts.
Performance wise it would not be a big win (given the alternative), however, the suggested API would give a relatively clean and readable way to express the desired outcome.

**Comment by ladeak** [comment]
@danmosemsft, are there any further questions or clarifications I shall add to the proposal?

**Comment by danmosemsft** [comment]
@ladeak I defer to @bartonjs and @joperezr who currently own this area. I expect @bartonjs has feedback as he's on the API review team.

**Comment by bartonjs** [comment]
I agree that the scenarios seem fairly limited (I can't think of a time when I've ever had a `ReadOnlySpan<string>`), but once you do have one you do have to do heroics to get back out.  (For just part of an array the Enumerable.Skip/Enumerable.Take methods to call the `IEnumerable<string>` overloads is sufficient).

I can't think of anything to change in the API, so marking it as ready for review.

**Comment by terrajobst** [comment]
* Since one can't stackalloc spans with reference types the value of this API feels low and the existing overload with `IEnumerable<T>` supports Linq-style slicing
* We may want to revisit this based on where the language is going, but for now let's not add this API.

```C#
namespace System
{
    public partial class String
    {
        public static string Join(char separator, ReadOnlySpan<string?> values);
        public static string Join(string? separator, ReadOnlySpan<string?> values);
    }
}
```

**Comment by GrabYourPitchforks** [comment]
You could use the existing `MemoryExtensions.Overlaps` routine to get the offset at which a `ROS<T>` occurs within a `T[]`. For instance:

```cs
string[] arr; // = some backing array
ReadOnlySpan<string> slice; // = arbitrary slice of arr

bool overlaps = arr.AsSpan().Overlaps(slice, out int offset);
Debug.Assert(overlaps); // slice must be contained within arr

string joined = string.Join(", ", arr, offset, slice.Length);
```

This could be useful if you've lost track of _offset_ as a standalone value and only have the original array and the array slice to work with.

**Comment by ladeak** [comment]
That seems a reasonable suggestion, thank you.
