### ISSUE TITLE
XmlSerializer fails to serialize/deserialize records

### ISSUE THREAD

**Issue by Gigas002** [dotnet/runtime#46251]
`System.Xml.Serialization.XmlSerializer` can't serialize/deserialize records. Don't know if it's made on purpose and I didn't get it, or it's a bug. No exception is thrown. Code sample to reproduce:

`Person` record:
```cs
    [Serializable]
    public record Person
    {
        public string Name { get; }

        public int Age { get; }

        public Person() { }

        public Person(string name, int age) => (Name, Age) = (name, age);
    }
```

Usage:
```cs
    internal static class Program
    {
        private static void Main()
        {
            const string xmlPath = "persons.xml";
            Person person = new("Tom", 29);
            XmlSerializer serializer = new(typeof(Person));

            FileStream wfs = File.OpenWrite(xmlPath);
            serializer.Serialize(wfs, person);
            wfs.Dispose();

            using FileStream rfs = File.OpenRead(xmlPath);
            Person newPerson = serializer.Deserialize(rfs) as Person;

            Console.WriteLine($"Name: {newPerson?.Name}, Age: {newPerson?.Age}");
        }
    }
```

### Configuration

Running on .NET 5.0.1, Win10 19042.685 x64.

**Comment by GrabYourPitchforks** [comment]
@danmosemsft @HongGit @StephenMolloy What's the policy on supporting new language constructs with older serializers like _XmlSerializer_? Do we have an official statement either committing to future support or saying that these older serializers are feature-complete?

**Comment by danmosemsft** [comment]
That's for @HongGit @StephenMolloy to answer. They may draw a distinction between changes they would accept from the community, and changes they expect to be able to fund this year.

**Comment by Joe4evr** [comment]
@Gigas002 I believe `XmlSerializer` skips serializing properties that have no setter method. You should declare the properties to be `{ get; init; }` if you want this to work

**Comment by Gigas002** [comment]
@Joe4evr ah, my bad, totally forgot about it. It's really working this way. Thanks for pointing this out!
