### ISSUE TITLE
SignedXml SafeCanonicalizationMethods behaves like static property

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#46256]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SignedXml-SafeCanonicalizationMethods-be/1288011)._

---
<p>.NET 4.8, net core 3.1, net core 5.0</p><p>SafeCanonicalizationMethods property behaves like static property - adding new transform in one SignedXml instance also adds it in all other instances.</p> <p>The example below creates 2 signedXml and add 3 transforms in each. As a result 6 total transforms were added in both instances.</p> <pre>var transforms = new string[] { &quot;https://first&quot;, &quot;https://second&quot;, &quot;https://third&quot; };

var signedXml1 = new SignedXml();
            var signedXml2 = new SignedXml();
            var initial = signedXml1.SafeCanonicalizationMethods.Count;
            Console.WriteLine(&quot;Before:SignedXml1.SafeCanonicalizationMethods.Count: {0}&quot;, signedXml1.SafeCanonicalizationMethods.Count);
            Console.WriteLine(&quot;Before:SignedXml1.SafeCanonicalizationMethods.Count: {0}&quot;, signedXml2.SafeCanonicalizationMethods.Count);

var i = 1;
            foreach (var t in transforms)
            {
                signedXml1.SafeCanonicalizationMethods.Add(t);
                signedXml2.SafeCanonicalizationMethods.Add(t);

Console.WriteLine($&quot;Iteration {i}:SignedXml1.SafeCanonicalizationMethods.Count: {signedXml1.SafeCanonicalizationMethods.Count}&quot;);
                Console.WriteLine($&quot;Iteration {i}:SignedXml2.SafeCanonicalizationMethods.Count: {signedXml2.SafeCanonicalizationMethods.Count}&quot;);
            }

Console.WriteLine($&quot;After {transforms. Length} iterations SignedXml1.SafeCanonicalizationMethods.Count expected: {initial + transforms. Length}, actual {signedXml1.SafeCanonicalizationMethods.Count}&quot;);
            Console.WriteLine($&quot;After {transforms. Length} iterations SignedXml2.SafeCanonicalizationMethods.Count expected: {initial + transforms. Length}, actual {signedXml2.SafeCanonicalizationMethods.Count}&quot;);
</pre><p>The problem here is &quot;private void Initialize(XmlElement element)&quot; method in SignedXml:</p><pre>    private void Initialize(XmlElement element)
    {
      this.m_containingDocument = element == null ? (XmlDocument) null : element. OwnerDocument;
      this.m_context = element;
      this.m_signature = new Signature();
      this.m_signature. SignedXml = this;
      this.m_signature. SignedInfo = new SignedInfo();
      this.m_signingKey = (AsymmetricAlgorithm) null;

// bug here!
      this.m_safeCanonicalizationMethods = new Collection&lt;string&gt;(SignedXml.KnownCanonicalizationMethods);
    }
</pre><p>It looks like the expected behavior is to create a copy of the static list &quot;KnownCanonicalizationMethods&quot; using &quot;Collection&lt;T&gt;&quot; constructor. At the same time, the constructor documentation says<br><br>&quot;Initializes a new instance of the Collection&lt;T&gt; class as a wrapper for the specified list.&quot; <br>https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.-ctor?view=net-5.0</p><p><br>As a result, &quot;m_safeCanonicalizationMethods&quot; is only a wrapper, not a copy of &quot;KnownCanonicalizationMethods&quot;. So changing &quot;SafeCanonicalizationMethods&quot; in one instance changes it for all instances of SignedXml.</p>

---
#### Feedback Bot on 12/15/2020, 10:21 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vcsjones** [comment]
@bartonjs @krwq this seems easy enough to fix, and I'm happy to do so, but I seem to recall some hesitation "fixing" things in the S.S.C.Xml namespace since it is unlikely they will get fixed in Framework, and this is not a regression from Framework.

**Comment by bartonjs** [comment]
Hm. I feel like we already fixed this in Framework.  Maybe we noticed it and decided it was too risky to fix.

**Comment by vcsjones** [comment]
> I feel like we already fixed this in Framework

The behavior is definitely there on Framework 4.8 for me:

```csharp
using System;
using System.Security.Cryptography.Xml;

var xml1 = new SignedXml();
var xml2 = new SignedXml();

Console.WriteLine(xml1.SafeCanonicalizationMethods.Count); // Prints 4

xml2.SafeCanonicalizationMethods.Add("http://example.org/sha0");

Console.WriteLine(xml1.SafeCanonicalizationMethods.Count); // Prints 5
```

**Comment by vcsjones** [comment]
Suppose I could have just looked at the source...

https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/signedxml.cs,135

**Comment by bartonjs** [comment]
Huh.  The change must have gotten rejected. If we didn't update the docs for the property then we should.  (Behaves like a static, except it isn't thread-safe)

I don't think we should take a change here both because we're not investing in SignedXml and because changing this for .NET (nee Core) would make for a very complex set of reasoning for a .NET Standard consumer (and .NET Standard / port-to-core is the reason we have the types available in core).  Care to dissent, @GrabYourPitchforks?
