### ISSUE TITLE
Use Portable TimerQueue when using Portable ThreadPool

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#46266]
We should use the portable timer queue when the portable thread pool has been selected. As for some of the benefits:
- The managed timer queue doesn't need to allocate when being scheduled to the thread pool since it implements IThreadPoolWorkItem
- It simplifies the native/managed interaction between the thread pool and timer queue. Today if you switch to the portable thread pool, the native timer queue needs to schedule work onto it (https://github.com/dotnet/runtime/blob/7e44a6a596208c0038010f1ade1623bc22f889dd/src/coreclr/vm/win32threadpool.cpp#L4831-L4843)
- The other benefits from moving to managed code (easier to maintain, same code on all platforms, etc)

I've spoke to @kouvel about this in passing so filing something just to track it.

**Comment by kouvel** [comment]
Should be possible to do after https://github.com/dotnet/runtime/pull/45901, then it also wouldn't need to be conditioned on whether the portable thread pool is enabled

**Comment by davidfowl** [comment]
Timer related allocations (UnmanagedThreadPoolWorkItem)

![image](https://user-images.githubusercontent.com/95136/109395565-dddaa280-78e1-11eb-8c35-721622f7bbab.png)

Removal of the QCall.

```diff
WebApplication40.dll!WebApplication40.DelayAwaiter.UnsafeOnCompleted.AnonymousMethod__8_0(object state) Line 78	C#
System.Private.CoreLib.dll!System.Threading.TimerQueueTimer..cctor.AnonymousMethod__23_0(object state)	Unknown
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
System.Private.CoreLib.dll!System.Threading.TimerQueueTimer.CallCallback(bool isThreadPool)	Unknown
System.Private.CoreLib.dll!System.Threading.TimerQueueTimer.Fire(bool isThreadPool)	Unknown
System.Private.CoreLib.dll!System.Threading.TimerQueue.FireNextTimers()	Unknown
-System.Private.CoreLib.dll!System.Threading.TimerQueue.AppDomainTimerCallback(int id)	Unknown
-[Native to Managed Transition]	
-[Managed to Native Transition]	
-System.Private.CoreLib.dll!System.Threading.UnmanagedThreadPoolWorkItem.System.Threading.IThreadPoolWorkItem.Execute()	Unknown
System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
System.Private.CoreLib.dll!System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()	Unknown
System.Private.CoreLib.dll!System.Threading.Thread.StartCallback()	Unknown
```

**Comment by davidfowl** [comment]
@kouvel @mangod9  is this still on deck for 6?

**Comment by kouvel** [comment]
Could probably be done as a bug fix, will see. It looks like the queuing in the native code above uses recycled memory that would likely amortize the allocations for creating/queuing a new work item.

**Comment by davidfowl** [comment]
Honestly I'm not *that* worried about the allocations, I just like the idea of all of the managed code pieces being used together. It's not critical for .NET 6 but I would like to see us make more progress on the timers and IO thread pool in .NET 7

**Comment by jkotas** [comment]
This should wait till .NET 7.

**Comment by davidfowl** [comment]
@kouvel I think this it the last piece of the puzzle for managed threadpool porting.

**Comment by kouvel** [comment]
I would also like to get this into 7.0, as it would allow deleting all of the native implementation and simplifying at some point thereafter.
