### ISSUE TITLE
Test failure: Assertion failed 'isValidGeneralDatasize(size)' in 'structinreg.Program3:Main1():int' during 'Generate code' 

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46278]
failed in job: [ runtime-coreclr jitstressregs 20201220.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=927859&view=ms.vss-test-web.build-test-results-tab&runId=29415406&resultId=106548&paneView=debug)

failed tests:
JIT/Directed/StructABI/StructABI/StructABI.sh
JIT/Methodical/structs/systemvbringup/structinregs/structinregs.sh
JIT\\Methodical\\structs\\systemvbringup\\structinregs\\structinregs.cmd

CoreCLR Linux arm64 Checked jitstressregs3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

Error message
~~~
Assert failure(PID 332 [0x0000014c], Thread: 332 [0x014c]): Assertion failed 'isValidGeneralDatasize(size)' in 'structinreg.Program3:Main1():int' during 'Generate code' (IL size 4687)

    File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 7689
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa9e92edc)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa9e92edc)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa9e87fa4)
/root/helix/work/workitem/JIT/Methodical/structs/systemvbringup/structinregs/structinregs.sh: line 365:   332 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/structs/systemvbringup/structinregs/structinregs.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun structinregs.dll ''
From Program0:test1!
test1 Result: 3
From Program0:test2!
test2 Result: 3
From Program0:test3!
test3 Result: 7
From Program0:test4!
test4 Result: 11
From Test5 members: 10 11 12 33
From Test5: Res 33
test5 Result: 42
From Test6 members: 21 22
From Test6: Res 43
test6 Result: 57
From Test7 members: 21 22
From Test7: Res 43
test7Result: 57
Foo2:Foo2:Foo2!!!
t13Res: 333
test13 Result: 333
t14 Res: 444
test14 Result: 444
t10 Res: True, 7
test10 Result: 15
t11 Res: 78, 87
test11 Result: 165
t12Res: 101
test12 Result: 101
test1: 36
test1 Result: 36
test2: 19
test2 Result: 19
test3: structinreg.Foo2 structinreg.Foo2 structinreg.Foo2 structinreg.Foo2
test3 Result: 10
test4 Res: 300
test4 Result: 300
test5 Res: 10
test5 Result: 10
t7 Res: 130
test7 Result: 130
t15 Res: 136
test15 Result: 136
test1Res: 36
test1 Result: 36
test2Res: 19
test2 Result: 19
test3Res: System.Object System.Object System.Object System.Object
test3 Result: 164711009
test4Res: 3
test4 Result: 300
test5Res: 36
Gathering state for process 332 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.332.dmp
Written 60289024 bytes (14719 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Methodical/structs/systemvbringup/structinregs/structinregs.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._structs_systemvbringup_structinregs_structinregs_._structs_systemvbringup_structinregs_structinregs_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs:line 192753
~~~

**Comment by danmosemsft** [comment]
Seeing this in several libraries test runs eg

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-b8cf6e2d38404d118e/System.Data.Common.Tests/console.7206dea5.log?sv=2019-07-07&se=2021-01-09T09%3A36%3A59Z&sr=c&sp=rl&sig=MkILPVp8NprJRceIMdE6C%2BQ6NlFVwRQj6zAenWHbfUg%3D

  Discovering: System.Data.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Data.Common.Tests (found 1811 of 1813 test cases)
  Starting:    System.Data.Common.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 133 [0x00000085], Thread: 148 [0x0094]): Assertion failed 'isValidGeneralDatasize(size)' in 'System.Data.Common.SqlConvert:ChangeType2(System.Object,int,System.Type,System.IFormatProvider):System.Object' during 'Generate code' (IL size 1305)

    File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 7689
    Image: /root/helix/work/correlation/dotnet

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f8d3eafa4)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f8d3f5edc)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f8d3f5edc)
Gathering state for process 133 dotnet
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.133.dmp
Written 161939456 bytes (39536 pages) to core file

**Comment by sandreenko** [comment]
Fixed by https://github.com/dotnet/runtime/pull/46345
