### ISSUE TITLE
Git clone time and space requirements

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#46275]
It would be helpful to newcomers (i.e. me) to include some rough idea about how much disk space the repo requires and how long approx. it takes to clone the repo over several possible connections types (e.g. DSL, Cable). I am on a DSL connection and the clone is about 5% done after about 5 minutes, I have a huge disk but it would help if I knew for sure that I had the space.

Thanks

**Comment by Rattenkrieg** [comment]
> I have a huge disk but it would help if I knew for sure that I had the space.

```
❯ du -sh .git
470M	.git
```

This is directory with binaries (there are few others but this is the biggest one) after I've build runtime+libs under release+debug config and tests under release config:
```
❯ du -sh ./artifacts
 12G	./artifacts
```

Today I've manually deleted ./artifacts on my windows machine and it was about 25 gigs.

**Comment by Korporal** [comment]
It'll likely take about 90 minutes for me then (almost done) over DSL via Century Link (I live in a county island in East Arizona - no cable or fiber services).

**Comment by Korporal** [comment]
> > I have a huge disk but it would help if I knew for sure that I had the space.
> 
> ```
> ❯ du -sh .git
> 470M	.git
> ```
> 
> This is directory with binaries (there are few others but this is the biggest one) after I've build runtime+libs under release+debug config and tests under release config:
> 
> ```
> ❯ du -sh ./artifacts
>  12G	./artifacts
> ```
> 
> Today I've manually deleted ./artifacts on my windows machine and it was about 25 gigs.
> 
> > how long approx. it takes to clone the repo over several possible connections types (e.g. DSL, Cable).
> 
> I have GPON and it takes ~10 mins for me to clone the repo. It feels like the bottleneck is on Github's side.

OK thanks, I have like 1.5 Terabytes free so I'm OK it seems !

**Comment by Korporal** [comment]
OK she's cloned - now I need to setup the tools etc to build the thing...

Thanks

**Comment by am11** [comment]
> consumed just under 1.5 GB

Yup, the archive file out of master branch (with no version history) https://github.com/dotnet/runtime/archive/master.zip is currently 109M which decompresses to 968M. I usually do a shallow clone without any version history (just a top revision of intended branch) in the CI-like (throw-away) environments:
```sh
# clone a single branch called master with history truncated to depth 1
$ git clone --single-branch --depth 1 --branch master https://github.com/dotnet/runtime
$ du -sh runtime
1.1G	runtime
```

**Comment by ViktorHofer** [comment]
> It would be helpful to newcomers (i.e. me) to include some rough idea about how much disk space the repo requires

Do you think it would help to indicate minimum disk requirements in our documentation? We welcome contributions, feel free to send a PR :)
