### ISSUE TITLE
The nuget library did not list all required libraries

### ISSUE THREAD

**Issue by chucklu** [dotnet/runtime#46284]
https://www.nuget.org/packages/Microsoft.IdentityModel.JsonWebTokens/6.8.0

> 
>     .NETFramework 4.5
>         Microsoft.IdentityModel.Tokens (>= 6.8.0)
>     .NETFramework 4.6.1
>         Microsoft.IdentityModel.Tokens (>= 6.8.0)
>     .NETStandard 2.0
>         Microsoft.IdentityModel.Tokens (>= 6.8.0)
> 

packages\Microsoft.IdentityModel.JsonWebTokens.6.8.0\lib\net45\Microsoft.IdentityModel.JsonWebTokens.dll
packages\Microsoft.IdentityModel.JsonWebTokens.6.8.0\lib\net461\Microsoft.IdentityModel.JsonWebTokens.dll
packages\Microsoft.IdentityModel.JsonWebTokens.6.8.0\lib\netstandard2.0\Microsoft.IdentityModel.JsonWebTokens.dll

The above three version net45, net461 and .net standard 2.0 verison of Microsoft.IdentityModel.JsonWebTokens both required another nuget library Microsoft.IdentityModel.Logging when you check the references of Microsoft.IdentityModel.JsonWebTokens through dnSpy.
Microsoft.IdentityModel.Logging should be list as dependency of Microsoft.IdentityModel.JsonWebTokens. (Although Microsoft.IdentityModel.Tokens requires Microsoft.IdentityModel.Logging)

@joperezr  @iSazonov  Maybe similar problem like https://github.com/dotnet/runtime/issues/46182? something wrong with the tool used in Microsoft

**Comment by iSazonov** [comment]
Doesn't nuget site always display only the top level of dependencies?

**Comment by eerhardt** [comment]
The Microsoft.IdentityModel.JsonWebTokens isn't built from the dotnet/runtime repo. According to nuget.org, the source repository for this package is: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet.

**Comment by eerhardt** [comment]
Moving to `area-Infrastructure-libraries` to match https://github.com/dotnet/runtime/issues/46182

**Comment by ViktorHofer** [comment]
As Eric said, this issue doesn't belong to dotnet/runtime and should be moved.

**Comment by chucklu** [comment]
@iSazonov both  Microsoft.IdentityModel.Logging and Microsoft.IdentityModel.Tokens are top level dependencies. Anyway I will file a new issue in correct repository https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet .
