### ISSUE TITLE
SqlGuid change storage from byte[] to individual fields or Guid

### ISSUE THREAD

**Issue by bjornbouetsmith** [dotnet/runtime#46291]
### Description

The internals of SqlGuid could be improved by storing the individual fields of the Guid instead of storing them as a byte array.

This will improve memory allocation when reading a lot of Guids out from the database, since a new byte array is constructed for each guid.

Storing each field in exacly the same way as Guid does would improve this. Alternatively it would also be a good solution to store a Guid directly, so that SqlGuid would not be dependent on the internals of Guid - and memory would be the same as storing the individual fields. 

If would of course impact NULL fields, since they would now take up 16 bytes+bool instead of just a bool and a null reference (4 or 8 bytes) depending on platform.

An entirely different solution could be to create a new struct SqlUniqueId - which could be implemented without dependency on a byte array and then would start its life in the https://github.com/dotnet/SqlClient repository

**Comment by ajcvickers** [comment]
The internals of these types must remain binary-compatible with the types used in the hosted CLR inside SQL Server. Therefore, we cannot change this representation.
