### ISSUE TITLE
Build broken on debian buster (master 60c6086aa70731432205449c1b6336dfa36b4ea0 )

### ISSUE THREAD

**Issue by joshudson** [dotnet/runtime#46301]
/home/joshua/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.20616.18/targets/sharedfx.targets(268,5): error : The following files are missing entries in the templated manifest: [/home/joshua/netcore/runtime-dmove/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/joshua/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.20616.18/targets/sharedfx.targets(268,5): error : SOS_README.md. Add these file names with extensions to the 'PlatformManifestFileEntry' item group for the runtime pack and corresponding ref pack to include them in the platform manifest. [/home/joshua/netcore/runtime-dmove/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]

I merged master into my outstanding PR and the build failed in a clearly unrelated location to what I was working on; ergo the master build is broken. I went ahead and pushed the merge so anybody can verify that it's clearly not my branch.

master is currently 60c6086aa70731432205449c1b6336dfa36b4ea0

**Comment by NikolaMilosavljevic** [comment]
[Triage] @joshudson have you tried with a fresh clone? We've refactored some projects recently. Meanwhile @NikolaMilosavljevic please check if this is reproing in official builds.

**Comment by joshudson** [comment]
Ok I'm weirded out by this. `git clean -fq` doesn't fix the tree but a fresh clone does.

**Comment by NikolaMilosavljevic** [comment]
> Ok I'm weirded out by this. `git clean -fq` doesn't fix the tree but a fresh clone does.

Nice - glad you're unblocked now, closing this issue.

BTW, I usually do 'git clean -xdf', which keeps tracked files, but removes everything else.
