### ISSUE TITLE
Code quality analysis - GenerateAssemblyInfo causes erroneous CA1416 warnings

### ISSUE THREAD

**Issue by EatonZ** [dotnet/runtime#46305]
**Version Used**: 
.NET 5.0.1
VS 16.8.3

**Steps to Reproduce**:

1. Download [this sample barebones .NET 5 project](https://github.com/dotnet/roslyn/files/5719003/CA1416-Repro.zip).
2. Open the project in Visual Studio and observe in Program.cs the CA1416 warning on the registry code.
3. Edit the csproj file to remove GenerateAssemblyInfo.
4. Save/reload the project, and notice how CA1416 is gone.

**Expected Behavior**:
The warning should never occur since TargetFramework net5.0-windows is specified correctly.

**Actual Behavior**:
The warning is shown when it should not be.

I felt this was the best repo to open this in since the new code quality analysis is a Roslyn feature. Please transfer if there is a more appropriate repo.🙂

**Comment by EatonZ** [comment]
@buyaa-n Ok, then what is the best way to make the warnings go away exactly?

**Comment by buyaa-n** [comment]
> @buyaa-n Ok, then what is the best way to make the warnings go away exactly?

Do not remove GenerateAssemblyInfo in the csproj file, generated AssemblyInfo.cs will have the target info which is consumed by the analyzer

**Comment by EatonZ** [comment]
@buyaa-n I am not removing it though. It's only when it is present that the warnings persist. If removed, the project won't compile because it won't use my customized AssemblyInfo.cs file. Let me know if there's something I should add to it?

**Comment by buyaa-n** [comment]
Ah then you can add `[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows")]` attribute in your custom AssemblyInfo.cs file or add the attribute in one of your CS code within the project

**Comment by EatonZ** [comment]
@buyaa-n That did the trick - thanks!
Since this is by design, I'll go ahead and close this.
