### ISSUE TITLE
Mark UnsafeQueueNativeOverlapped as windows only 

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#46300]
`ThreadPool.BindHandle` is marked as `[SupportedOSPlatform("windows")]` but not `ThreadPool.UnsafeQueueNativeOverlapped`.

**Comment by mangod9** [comment]
@davidfowl assume this was found during code review and isn't causing any issues on non-windows?

**Comment by davidfowl** [comment]
It was just something I noticed while using the APIs.
