### ISSUE TITLE
GetHostAddressesAsync on Arm64

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#46314]
### Description

The same code, on the arm64 environment, get address by host name, sometimes the duration is about 5006ms, sometimes it is about 3ms, but on x64 environment, the duration is very stable, about 4ms

```
[InProcess]
    public class DnsBenchmark
    {
        [Benchmark]
        public Task<IPAddress[]> GetHostAddressesAsync() => Dns.GetHostAddressesAsync("microsoft.com");
    }

    public class Program
    {
        public static async Task Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<DnsBenchmark>();

            while (true)
            {
                var stopWatch = Stopwatch.StartNew();
                var ipAddresses = await Dns.GetHostAddressesAsync("microsoft.com");
                stopWatch.Stop();
                foreach (var item in ipAddresses)
                {
                    Console.WriteLine($"Get Address By Dns:{item},Duration:{stopWatch.ElapsedMilliseconds}ms");
                }

                await Task.Delay(1000);
            }
        }
    }

```

#### Debian  Arm64 

``` ini

BenchmarkDotNet=v0.12.1, OS=debian 10 (container)
Unknown processor
.NET Core SDK=5.0.101
  [Host] : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), Arm64 RyuJIT
Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|                Method |     Mean |   Error |  StdDev |
|---------------------- |---------:|--------:|--------:|
| GetHostAddressesAsync | 6.671 ms | 0.5831 ms | 1.692 ms |

Get Address By Dns:40.113.200.201,Duration:5006ms
Get Address By Dns:40.112.72.205,Duration:5006ms
Get Address By Dns:40.76.4.15,Duration:5006ms
Get Address By Dns:104.215.148.63,Duration:5006ms
Get Address By Dns:13.77.161.179,Duration:5006ms

#### Debian  X64

``` ini

BenchmarkDotNet=v0.12.1, OS=debian 10 (container)
Intel Xeon CPU E5-2620 0 2.00GHz, 2 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.101
  [Host] : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X64 RyuJIT
Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|                Method |     Mean |     Error |    StdDev |
|---------------------- |---------:|----------:|----------:|
| GetHostAddressesAsync | 1.817 ms | 0.0234 ms | 0.0207 ms |

Get Address By Dns:40.112.72.205,Duration:4ms
Get Address By Dns:104.215.148.63,Duration:4ms
Get Address By Dns:40.76.4.15,Duration:4ms
Get Address By Dns:13.77.161.179,Duration:4ms
Get Address By Dns:40.113.200.201,Duration:4ms

#### Windows X64

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.101
  [Host] : .NET Core 5.0.1 (CoreCLR 5.0.120.57516, CoreFX 5.0.120.57516), X86 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

```
|                Method |     Mean |   Error |  StdDev |
|---------------------- |---------:|--------:|--------:|
| GetHostAddressesAsync | 156.7 μs | 2.31 μs | 3.66 μs |

Get Address By Dns:13.77.161.179,Duration:1ms
Get Address By Dns:40.76.4.15,Duration:1ms
Get Address By Dns:104.215.148.63,Duration:1ms
Get Address By Dns:40.113.200.201,Duration:1ms
Get Address By Dns:40.112.72.205,Duration:1ms

**Comment by wfurt** [comment]
did you try to do packet capture and watch the DNS exchange @Varorbc? Do you have both machines ion the same network and talking to the same DNS server?

**Comment by Varorbc** [comment]
@wfurt  I don't know how to packet capture on container. If you want to tell me, I can provide the corresponding data.Thank you

Our two machines are in different networks, but they all use public DNS. Even if I define a domain name in the host file and then get the address, there is still a delay.

**Comment by wfurt** [comment]
Is your other machine also container? We have seen some issues in the past with containers and there are different ways to set it up.  You can check `/etc/resolv.conf`  and see if that points to docker or your public server. 
As far as packet capture, you can do it in the container if started with the `--privileged` option. Alternatively, you should be able to capture on your host and use `docker0` interface. 
All the long times feel like some kind of 5s timeout. RES_TIMEOUT is 5s AFAIK. 
In general, .NET simple defers the resolution to OS. You can also try to write simple test and call `getaddrinfo()` directly to see if the variations comes from your environment or if they are caused by .NET it self.

**Comment by Varorbc** [comment]
@wfurt Thank you very much for your help

The problem may be caused by k8s on arm
