### ISSUE TITLE
Utf8JsonReader failing mysteriously / Debugger showing faulty code flow

### ISSUE THREAD

**Issue by MeFisto94** [dotnet/runtime#46324]
Apologizes if this is more an issue on my side and/or if this is the wrong repo, but I never encountered such an issue so it's worth getting some eyes on it.

### Description
TLDR is: Stepping into the debugger takes switch-cases it shouldn't take:
![grafik](https://user-images.githubusercontent.com/12577813/102896728-2059ac00-4467-11eb-95dc-2aace3eb22f6.png)

Not only should it skip this switch completely, but this Read() also fails, which it shouldn't, because it doesn't if I manually call Read() before invocation.
For reference: https://github.com/dotnet/runtime/blob/c1a21a031925ce6261fadcfed26e098ab1bf46a6/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L150-L160

The context is that I was calling `JsonSerializer.Deserialize<T>(ref reader, options);` after having extracted the property name (custom object deserializer).
```csharp
while (reader.TokenType != JsonTokenType.EndObject)
            {
                try
                {
                    if (reader.TokenType != JsonTokenType.PropertyName)
                    {
                        throw new JsonException("Not a Property");
                    }

                    string key = reader.GetString();
                    // Skip the propertyName
                    if (!reader.Read())
                    {
                        Console.WriteLine("Read error");
                    }
                
                     JsonSerializer.Deserialize<MyT>(ref reader, options);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
                
            }
```

### Configuration
.net core framework 3.1 on Windows 10 64bit.
It happens across all three Debug Targets (Any CPU, x86, x64).

### Regression?
I cannot give any Regression Information, but since System.Text.Json is new to 3.0(?) there isn't much regression range available anyway.

### Other information
The only thing that may or may not be odd here, is that it jumps from Line 136 (`ReadOnlySequence<byte> valueSequence = default`) directly into the case branch. It does not stop at the switch statement.

I wonder if this is a case where source and binary differ, but all I did was allowing VS 2019 to download the Source for this when stepping into the code.

**Comment by svick** [comment]
I think what you're seeing is just an artifact of debugging a Release build. In Release mode, the runtime focuses on making the code fast, not on making debugging easy, so you'll sometimes see that the debugger highlights a line that is not actually executed.

**Comment by layomia** [comment]
This is likely what @svick said. Please try debugging with a `Debug` configuration and let us know if you still have issues here.
