### ISSUE TITLE
DateTime.TryParse with IFormatProvider does not work correct in Blazor WASM

### ISSUE THREAD

**Issue by MarcelWolterbeek** [dotnet/runtime#46327]
DateTime.TryParse seems to work incorrect in Blazor WASM.

When I run the code example below in Blazor, I get this incorrect result:
    **01-03-2008 - dateResult:  3-01-2008**

When I run the same code in a console app, I get the correct result:
    **01-03-2008 - dateResult:  1-03-2008**

```cs
var dateString = "01-03-2008";
var culture = CultureInfo.CreateSpecificCulture("nl-NL");
var styles = DateTimeStyles.AllowWhiteSpaces | DateTimeStyles.AssumeLocal | DateTimeStyles.NoCurrentDateDefault;
if (DateTime.TryParse(dateString, culture, styles, out var dateResult))
    Console.WriteLine($"{dateString} - dateResult: {dateResult: d-MM-yyyy}");
else
    Console.WriteLine($"FAILED: {dateString}");
```

**Comment by mkArtakMSFT** [comment]
@lewing  FYI

**Comment by safern** [comment]
cc: @EgorBo @kg

**Comment by svick** [comment]
[The article on globalization in Blazor says:](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0)

> By default, Blazor WebAssembly carries minimal globalization resources required to display values, such as dates and currency, in the user's culture. Applications that must support dynamically changing the culture should configure `BlazorWebAssemblyLoadAllGlobalizationData` in the project file:
>
> ```xml
> <PropertyGroup>
>   <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
> </PropertyGroup>
> ```

Have you tried setting this option?

**Comment by MarcelWolterbeek** [comment]
@svick thanks, problem is solved when setting
```
<PropertyGroup>
  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
</PropertyGroup>
```
I would have expected a System.NotSupportedException instead of just ignoring the FormatProvider/culture in the DateTime.TryParse.

**Comment by lewing** [comment]
Yeah, this fails in a confusing way.  It's parsing with the wrong culture which ends up reversing the day and month. I think CreateSpecificCulture should fail when it isn't available.
