### ISSUE TITLE
[Proposal]: WebRequest support for data URIs

### ISSUE THREAD

**Issue by RonAmihai** [dotnet/runtime#46322]
# WebRequest support for data URIs

## Summary
Add support for WebClient / WebRequest to "fetch" data from data URIs. 

Data URI for demonstration: 
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAEI0lEQVR4nO3czXWqQBjG8ZSQEiwhJWQHk03sIJ4zeNy6E9zEDiwhJaQESrAES7AE7sKPe82NgDgv73z8F88WGZ7fgWEAn5qmeSLpRn0HCAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAuWc/fXrT3IZSo74DrlNZ8VdZstPcjlKjvgPPyC9MAIEEAl/IBkB6Aq/IBkBaA/8oHQDoAfi0fAGkAuFk+AOIH0Fo+AOIG0Fk+AOIF0Kt8AMQJoHf5AIgPwF3lAyAuAHeXD4B4AAwqHwBxABhcPgDCB/BQ+QAIG8DD5QMgXABOygdAmACclQ+A8AA4LR8AYQFwXj4AwgEgUv516vNLoiubvWofbB8Tc/m/prT5rirMtrJm+vnx/qxdgHaSKv8WiLIwy9Uim2iXkQQAn8oHw8gAfC7/l9TreTbTLigaAIGV/zfW7CtrNrHOFyi/Z8oiP8QIgfITh0D5D0AoC7PULtBbADGXfwXB5ruQP0d3vsHPj/fnVMr/kW2IlwWB8vOdB2VwNhgbQOrlX0EIaG5A+VIIrPkK4ZJA+aII8p3vy8qUL42gyA8+zwse3kCiM/5oEDjZCAj6xceHS842BIIwETjdGAj6IvDncuB8gyDojk9zApGNgqAfAh9uEcU2DIIeCGy+014sEt04CPok/44WAAh6RvFDllF+BATd0fpwZbQfAkFHrNlrzAdG/TEQdGX8+cCoPwaCHrFmGjUAELSnLPLDmJcCFQAg6Mw2egDCCOrKmk1lzaYqTP0zZZEfPCi5NWMtFasCEENwx331ev72srLZ63qezY5g8m9PXnKpkwAggsDRwsp6/vaynmezqjBbDRRjrA2oly+CQHBlrbJmOhoIa/bJAHCKYKSl1dUim5SFWUpikH6BRL10EQQKa+urRTY5TTz3IZ0F1AsXQaD8L2Gny0QdwllAvWwRBJ78TdxqkU0cXdbq5AA8hMATAC4hSN0RqB8cEQSeAbhAsNnr0EtDac1XkgAGIfAUwDnreTYbshop8Q6h+sEQQeA5gKY5flZXFfn3XWcBga+O1Q+ECIIAAJxTWTPtfTYQuCVUPwAiCAIC0DTnSWK/xSTXD4nUBy+CIDAA51SF2Y49GVQftAiCQAE0zXGC2D4PyA8A6EIQMICmOd4uts4LHL42pj5YEQSBA2ia46PoFgTO3hhSH6gIgggAtCJweDegPkgRBJEAaEPg6m5AfYAiCCICcAuBq0Uh9cGJIIgMwA0ENQBaDpb2Pkjk9J7B5SwAgATz7zqBi0fE6gMi98flXEd9MGQognzn4mNS9YGQYTm9hLoHQMJxsSSsPgiiG/UdIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgTgD8AYDaKb/QJwuKAAAAAElFTkSuQmCC
```

That actually means just to extract the data out of the URI (separating the URI's prefix from the data).

## Motivation
[motivation]: #motivation

Adding this support for WebRequest / WebClient would actually make them to support most URI types.
(without a need to explicitly check for the URI scheme before fetching / extracting).

## Detailed design
[design]: #detailed-design

This feature requires mostly 3 things:

1.  Implementing `DataWebRequest` class 
2. Implementing `DataWebRequestCreator` over `IWebRequestCreate`
3. Adding a `DataWebRequestCreator` to `WebRequest.PrefixList`, alongside the other creators (HTTP / FTP / file path).

The conversion from URI to data is very straightforward, for example (focused on base64 images, but can be applied to any kind of data):
```c#
var base64Data = Regex.Match(uri, @"data:image/(?<type>.+?),(?<data>.+)").Groups["data"].Value;
var binData = Convert.FromBase64String(base64Data);
```

## Temporary Solution
Until such built in support is added, one can implement & register it's own data web request creator using [WebRequest.RegisterPrefix](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.registerprefix?view=net-5.0)

**Comment by svick** [comment]
Note that [`WebRequest` is not recommended to be used in new code](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest?view=net-5.0#remarks). And since there is a fairly easy workaround (use `WebRequest.RegisterPrefix`, as you mentioned), I don't think this proposal has a high chance of being accepted.

**Comment by RonAmihai** [comment]
> Note that [`WebRequest` is not recommended to be used in new code](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest?view=net-5.0#remarks). And since there is a fairly easy workaround (use `WebRequest.RegisterPrefix`, as you mentioned), I don't think this proposal has a high chance of being accepted.

`HttpClient`, which is suggested as the modern approach, simply doesn't support URI protocols other than http... 

`WebRequest` does support http, ftp and file. 

(And honestly, I think the documentation should point that out in this note... Without marking `WebClient` as "deprecated" / "unnecessary")

I get that most of the URI cases are http, but I've seen many microservices use cases which should handle many types of different remote/local URIs, including data URIs.

Having an abstract module like `WebClient` to fetch an URI source without parsing the URI itself is helpful.

Using `WebRequest.RegisterPrefix` is not a complex workaround, but supporting most of the data MIME types would require a little bit of work. 

It's not the most glorious feature out there, but it is also not the most redundant nor complex. I think it should be considered.

**Comment by karelz** [comment]
FYI: `WebClient` is already obsoleted in 6.0 (master branch): #33125 ... we closely missed the window to make it happen in 5.0

Given that these APIs are obsolete, there is simple RegEx workaround and this is not widely-used feature, I recommend to close it as Won't Fix.
