### ISSUE TITLE
File.CreateShortcut as part of the .NET library

### ISSUE THREAD

**Issue by osamakawish** [dotnet/runtime#46335]
## Background and Motivation

I want to simplify the process of creating file shortcuts. 

## Proposed API

A `File.CreateShortcut(string filepath, string shortcutPath)` or a `FileInfo.CreateShortcut(string shortcutPath)` should be sufficient.

## Usage Examples

Well, it would be useful for much the same reasons creating file shortcuts would be useful. I just want to clean up the process and simplify the code for it by making it part of the .NET library.

The usage I'm using it for is to store user input files (via an OpenFiledialog) into the AppData directory for my application. Creating and storing file shortcuts is simply cleaner than storing their information in a `.txt` file.

## Alternative Designs

Already proposed two distinct designs, one two store it in `FileInfo`, and another as a static method in `File`. Having both would obviously be ideal, and left to the developer's preference.

## Risks

I'd reckon the risks for this will be no different than the risks for creating file shortcuts. I'm not sure of any additional risks it might cause.

**Comment by FiniteReality** [comment]
What kind of "shortcut" do you mean?
- The explorer.exe kind, which is basically a special file which tells Explorer to look elsewhere?
- A symbolic link, which tells the filesystem to look elsewhere?
- A hard link, which is "another name" for a file/directory?

This API is fairly limited in what it can do, and is also extremely vague in what it actually does, particularly across multiple platforms. A better API would be something like #24271 which is clear in what it does and how it'll work across multiple platforms

**Comment by ygra** [comment]
Isn't this a Windows-only concept and thus perhaps a bit misplaced in a cross-platform framework? Personally I feel that's something that's probably better served by a NuGet package.

Also keep in mind that shortcuts are not _file_ shortcuts per se, they're shortcuts to shell namespace objects, and thus may require even more of a Windows-specific API.

**Comment by osamakawish** [comment]
@FiniteReality I meant a .lnk file, but I think that #24271 covers what I want, if I understand symbolic links clearly.

@ygra As for whether or not it's Window's, I'm not sure. But I did assume when I posted this that file shortcuts are generally not a Windows only concept, mostly because of how "essential" they seemed.
