### ISSUE TITLE
Disabling `UseRandomizedStringHashAlgorithm` in custom CLR hosting

### ISSUE THREAD

**Issue by duskembayev** [dotnet/runtime#46339]
We are using custom CLR hosting in a security restricted process.
After migrating from .NETCore 3.* to .NET 5 runtime, we started catching an error about `BCrypt.dll` (access denied).
Exception occurs on `String.GetHashCode()` method invoke.

Most probably this exception occurs because `UseRandomizedStringHashAlgorithm` flag is enabled by default in .NET 5 runtime.
1. Can anyone confirm or deny this assumption?
2. How I can disable this flag in our custom CLR hosting (our solution is based on [official sample](https://github.com/dotnet/samples/tree/master/core/hosting/HostWithCoreClrHost))?

**Comment by GrabYourPitchforks** [comment]
String hash code randomization is force-enabled in .NET Core (all versions) with no way to disable it. I'm surprised you're only just now seeing errors, though. We've relied on bcrypt.dll as our CSPRNG for several versions. Did anything else change on the machine recently? Was bcrypt.dll already loaded into the process when you were using netcore3, so the switch to net5 perhaps changed an order of operations away from what was previously tested?

**Comment by duskembayev** [comment]
After investigation, I found that we changed some internal algorithm within migration to .net5.0 and same exception occurs in previous clr versions too.
I'm going to investigate BCrypt loading deeper.
Is this library part of Windows or .NET runtime?

**Comment by GrabYourPitchforks** [comment]
bcrypt.dll comes as part of the Windows OS since Vista / Server 2008 ([more info](https://docs.microsoft.com/windows/win32/seccng/cng-portal)).

**Comment by duskembayev** [comment]
Finally, I found the solution: load `bcrypt.dll` before security restrictions apply.
Thanks a lot for your help!
