### ISSUE TITLE
JitStress: Vector3Interop_r fails on arm64 windows 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#46347]
https://dev.azure.com/dnceng/public/_build/results?buildId=928195&view=ms.vss-test-web.build-test-results-tab&runId=29424818&paneView=debug&resultId=109554

It was reenabled in https://github.com/dotnet/runtime/pull/46162

**Comment by sandreenko** [comment]
disabled in #46350

**Comment by echesakovMSFT** [comment]
The test is no repro either in the CI or locally.
