### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46352]
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=929390&view=ms.vss-test-web.build-test-results-tab&runId=29452414&resultId=101161&paneView=debug

failed tests:
System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows
System.Diagnostics.Tests.ProcessTests.MainWindowHandle_GetWithGui_ShouldRefresh_Windows

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Assert.NotEqual() Failure
Expected: Not ""
Actual:   ""

Stack trace
   at System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1619
~~~

**Comment by danmosemsft** [comment]
@adamsitnik these fail consistently on Server Core. They need to be disabled on this OS, for reasons explained in https://github.com/dotnet/runtime/pull/44972


https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1QTUsDQQy9C%2f6H0JPCSrc9CitUinWFCrYLeyxxJ%2b1Md3emJBmK4I93%2boF66KEQSPKS93hJRaILktipwO3NN%2bwtMcGc1AYDRQGDOTpfO2%2fCvnLa0WpGWju1s%2bhWSxtiZxa0ZhK7Oi3JAAJf5r%2biN9cIHGxsg%2fPQJqBw3hNDHbgtlXqB4H%2bb0vyz%2fOK8E0sGngowqKSup7txPs4fRuMUkD%2fmh7i%2fpP4WPo%2fCKZfmT%2fKZ0Tf2eAXTWoaW0MiwR1Hio8sdhy01CktFVjIZTCOjuuCz8wcy%2bIgU6R17OkAiuElFWm%2fairFJ9YQ3sSevkkH1taMzYdI5TMg0NC1xhZvTcPQDO5zKfq0BAAA%3d&web=0
```
TestResults 
| where Method == "MainWindowTitle_GetWithGui_ShouldRefresh_Windows" or Method == "MainWindowHandle_GetWithGui_ShouldRefresh_Windows"
| join kind=inner WorkItems on WorkItemId 
| where Finished >= datetime(2020-12-12 0:00:00)
| join kind=inner Jobs on JobId
| where Branch == "refs/heads/master"
| project Started, Duration, Method, QueueName, Message, StackTrace, Arguments, Type, QueueAlias, DockerTag, Type1
```

**Comment by danmosemsft** [comment]
BTW, in MainWindowTitle_GetWithGui_ShouldRefresh_Windows() is `Assert.Equal(string.Empty, process.MainWindowTitle);` racing with Notepad setting the title? As far as I can see when it's retrieved the first time it reads the live value. Seems that line ought to be removed.

**Comment by adamsitnik** [comment]
@danmosemsft thanks for keeping an eye on it and sharing the Kusto Query! I've sent #46387 with a fix.

For some reason, all the `System.Diagnostics.Process` tests belong to `System.Diagnostics.Tests` namespace which contains more than just the `Process` tests. Would it be acceptable to move the Process tests to the  `System.Diagnostics.Process.Tests` namespace? (cc @eiriktsarpalis)

It would allow be for easier filtering of the failed tests. And perhaps help a little the labeling bot?

**Comment by danmosemsft** [comment]
I have no opinion.
