### ISSUE TITLE
please specify nugets in another tab for .net 5 and unity..It wiill be an ide trembling feature I think

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#46358]
please specify nuget in another tab for .net 5 and unity..It wiill be an ide trembling feature I think

**Comment by jkotas** [comment]
This repo is for core runtime and libraries only. It is not a good place to file suggestions for improving IDEs. I assume that you mean Visual Studio. The best place to file Visual Studio improvements is at https://developercommunity.visualstudio.com/
