### ISSUE TITLE
[please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much]: [All in one Project] [please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much]: [All in one Project] 

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#46354]
[please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much]: [All in one Project]

**Comment by jkotas** [comment]
Yes, this is part of .NET platform unification that we plan to finish in .NET 6.
