### ISSUE TITLE
[please implement this feature in mobile development specially in android and ios along with other .net platform..If possible use interpreter support to implement them]: [Microsoft.CSharp]

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#46353]
[please implement this feature in mobile development specially in android and ios along with other .net platform..If possible use interpreter support to implement them]: [Microsoft.CSharp]

**Comment by jkotas** [comment]
Microsoft.CSharp is supported on iOS and Android.

If there is a something that does not work for you, please create a new issue with detailed steps to reproduce the problem.
