### ISSUE TITLE
[please introduce shared code for tizen ios android windows linux mac cloud and almost all supported platform in a single project as soon as you can..I like it very much]: [All in one Project] 

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#46355]

**Comment by huoyaoyuan** [comment]
This was planned for .NET 5 and delayed to .NET 6.
For now, you can already use `MSBuild.Sdk.Extras`.

**Comment by Barshan-Mandal** [comment]
But no mobile support is here...only desktop support

**Comment by huoyaoyuan** [comment]
Mobile support is Xamarin. Xamarin has been a separated project. The consolidation of Xamarin is planned for .NET 6.

**Comment by Barshan-Mandal** [comment]
Will the consolidation of Xamarin  will include tizen ,macos, ios ,android,watchos,tvos, windows,asp.net and linux etc with some other platform ?????

**Comment by huoyaoyuan** [comment]
I'm not sure what you are asking for.
For sharing library code, there is .NET standard and multi-targeting project.
For extending application support, every platform differs a lot, so you can hardly share application, especially the entry code. All those platforms are supported with their own project type.

**Comment by jkotas** [comment]
Duplicate of #46354
