### ISSUE TITLE
Proposal: System.Text.Json serialization/deserialization of value tuples from/to JSON array

### ISSUE THREAD

**Issue by zspitz** [dotnet/runtime#46364]
The original proposal issue for serialization of value tuples (#29045) was closed with as a duplicate of #876 -- once public fields are serialized, it is possible to serialize and deserialize value tuples using the field names: `Item1`, `Item2` etc.

However, I would argue that these field names don't add any information, and it would be preferable to produce a JSON array for the value tuple, and allow deserialization of JSON arrays into value tuples of the same arity.

In theory, the same should also apply to old-style `System.Tuple`.

**Comment by Happypig375** [comment]
For the time being, https://github.com/arogozine/TupleAsJsonArray should suffice.

**Comment by zspitz** [comment]
@Happypig375 Or [this](https://github.com/zspitz/PandocFilters/blob/main/PandocFilters/Converters.cs#L79).

**Comment by layomia** [comment]
The existing behavior for (de)serializing `ValueTuple<...>` and `Tuple<...>` types is what most .NET developers expect when handling JSON:

```cs
using System;
using System.Text.Json;
using Newtonsoft.Json;

using JsonSerializer = System.Text.Json.JsonSerializer;

namespace quickcheck
{
    class Program
    {
        static void Main(string[] args)
        {
            ValueTuple<int, string> val = (0, "0");

            JsonSerializerOptions options = new() { IncludeFields = true };

            string serialized = JsonSerializer.Serialize(val, options);
            Console.WriteLine(serialized); // {"Item1":0,"Item2":"0"}
            Console.WriteLine(serialized == JsonConvert.SerializeObject(val)); // true

            val = JsonSerializer.Deserialize<ValueTuple<int, string>>(serialized, options);
            Console.WriteLine(val.Item1); // 0
            Console.WriteLine(val.Item2); // 0
        }
    }
}
```

This feature request can easily be done with a custom converter and is not on the roadmap for System.Text.Json. On first glance, the `TupleAsJsonArray` project seems to be providing this functionality (using System.Text.Json) accurately, e.g:

https://github.com/arogozine/TupleAsJsonArray/blob/ebcaa66375e1b9b9cb9e012c57e58d2b734b41d7/TupleAsJsonArray/Converters/TupleConverter.cs#L37-L75
