### ISSUE TITLE
Question: How to deserialize JSON where .NET type depends on a JSON property value?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/runtime#46360]
Hi,

I have a JSON string that I want to deserialize. The JSON string contains `filters` property and its value depends on `filterType`:

```json
{
  "filterType": "Price", // `filterType` is always present, other properties depend on this value
  "priceMinimum": 10,
  "priceMaximum": 100
}
```

```json
{
  "filterType": "Volume",
  "minQuantity": 0.005,
  "maxQuantity": 77
}
```

Example:

```json
{
  // ...
  "filters": [
    {
      "filterType": "Price",
      "priceMinimum": 10,
      "priceMaximum": 100
    },
    {
      "filterType": "Volume",
      "minQuantity": 0.005,
      "maxQuantity": 77
    }
  ],
  // ...
}
```

I would like to deserialize the JSON above to an object where `filters` would deserialize based on `filterType` to a proper .NET object (i.e. `PriceFilter` with `priceMinimum` and `priceMaximum` properties, similarly for `VolumeFilter`)

Can I do that easily in .NET 5? Do I have to write a custom converter for this?

**Comment by huoyaoyuan** [comment]
This is #30083
There is no built-in support for this now.

**Comment by MartyIX** [comment]
Thank you! I couldn't find it.
