### ISSUE TITLE
Developers can get the most out of profiling their iOS or Android device using dotnet-counters

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46373]
As an Android/IOS game developer, I want to measure managed memory usage, GC stats (pause times + Gen 0 / Gen 1 (Frequency/Size), and custom EventCounters for a running game so that I can identify performance issues impacting game performance.

- [x] A tracing session using dotnet-counters can be started
- [x] Developer can monitor GC Heap Size, GC LOH Size every second for a running application on device.
- [x] GC pause times, GC frequency, and GC size (gen1/gen2) can be monitored every second
- [x] Custom counters can be monitored every second
- [x] Results of the diagnostics session can be exported to a json|csv formatted file that can be imported into tools for post analyzing.
- [x] dotnet-counters can terminate a tracing session but keep the application running on device
- [x] Developer can relaunch dotnet-counters and run a new tracing session on same device for same running application.
- [x] All tools can be gracefully shut down when the application terminates
- [x] Developer can temporary lose network communication between device/application and dotnet-counters. If possible, the tracing session should be resumed.

**Comment by lambdageek** [comment]
I think this is done. @lateralusX please re-open if there's any work that you remains for this user story for .net 6
