### ISSUE TITLE
Discussion: [StringLength(123)] is misleading

### ISSUE THREAD

**Issue by chucker** [dotnet/runtime#46376]
## Background and Motivation

Given a specification like:

>pid (Passport ID) - a nine-digit number, including leading zeroes.

One might be tempted to implement that in C# like so:

    [StringLength(9)]
    public string? PassportId { get; private set; }

On the surface, that looks correct, but it's not: that `9` argument doesn't mean _exact_ string length, but rather _maximum_ string length. This validation rule is too lenient.

The IntelliSense comments, of course, do make that clear, but I missed them at the time. I could also make it _super_-clear to the hypothetical future reader (probably also me, having forgotten all about this):

    [StringLength(maximumLength: 9, MinimumLength = 9)]
    public string? PassportId { get; private set; }

But I don't like this default behavior. It seems bug-prone. (And why is _maximum_ the default? What if I want just the _minimum_?)

## Suggestion

So, I propose that maximumLength be demoted from a positional parameter to a property, requiring API consumers to specify whether they really want maximum, minimum, or both.

**Comment by LeaFrock** [comment]
Relatively speaking, it's more possible(or common) for web apps to limit the max length of *string* which at least prevents request attacks with  large body.
As you actually want to limit a number, I think it's better to use `Int32` and `RangeAttribute` like below,

```C#
[Range(100000000,999999999)]
public int PassportId { get; private set; }
```

Or, if you have to use `String`, trying to limit the number range by the string length, but don't like the current way, you may need to apply for a API prospal like this,

```diff
public StringLengthAttribute(int maximumLength);
+ public StringLengthAttribute(int minimumLength, int maximumLength);
```

So you can write codes like the following,

```C#
[StringLength(9,9)]
public string? PassportId { get; private set; }
```

That won't make a break change and simplify the way you use. It won't let you feel bug-prone, right?

>What if I want just the minimum?

Use [MinLengthAttribute](https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/MinLengthAttribute.cs). Also, you can find `MaxLengthAttribute`, too.

**Comment by Joe4evr** [comment]
> ```cs
> [Range(100000000,999999999)]
> public int PassportId { get; private set; }
> ```

Just FYI, that's going to fail for IDs starting with a `0`, since the spec clearly states "including leading zeroes".

One alternative I can think of for this case would be:
> ```cs
> [RegularExpression("[0-9]{9}")]
> public string? PassportId { get; private set; }
> ```

**Comment by chucker** [comment]
>Relatively speaking, it's more possible(or common) for web apps to limit the max length of string which at least prevents request attacks with large body.

Hm. I don't know to what extent the `Annotation` namespace is intended to also mitigate security issues, especially since such code will typically run on the server (stuff like Blazor WASM notwithstanding).

>As you actually want to limit a number, I think it's better to use Int32 and RangeAttribute like below,

As @Joe4evr says, that wouldn't technically be a correct solution — if it were, I would indeed have just used `int` and `Range(1, 999_999_999)`!

>That won't make a break change and simplify the way you use. It won't let you feel bug-prone, right?

I'm aware this would be a breaking change, and I had almost decided against filing because of that.

But, I don't see how your additional constructor helps. It still feels rather arbitrary that, in the overload I incorrectly chose, the parameter refers to _maximum_ length rather than _minimum_ or (as I had had intuited, wrongly), _exact_ length.

>One alternative I can think of for this case would be:

Yup, regex is another approach I could've taken.

Again, this isn't about lack of alternatives — my problem is clearly solvable — and more about how, intuitively, people expect the available attributes to behave.

**Comment by ajcvickers** [comment]
Notes from triage: this is not something we are going to change. We considered your argument, but we're not convinced by it, and making breaking changes here would not be acceptable anyway.

**Comment by chucker** [comment]
> making breaking changes here would not be acceptable anyway

Yeah, that’s fair. Thanks for the response!
