### ISSUE TITLE
is there any trick to detect method execute dead cycle?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#46380]
we embeded mono, how can we detect some method execute dead cycle?

``` c#
void test()
{
    for(int index=0;index<1;index++)
    {
        index--;
    }
}
````

**Comment by Clockwork-Muse** [comment]
In this specific case, _maybe_.

In the general case, **no**.  This is known as the [halting problem](https://en.wikipedia.org/wiki/Halting_problem).

**Comment by lambdageek** [comment]
There's no Mono API to analyze .NET IL like this.  In general it's not the responsibility of the runtime to try to understand what the code is doing.
