### ISSUE TITLE
Previously all are good, normal operation, because upgrade .net5, the standard library 2.0 changed to 2.1 after the problem

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#46395]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/之前都是好的，正常运行，因为升级net5，把标准库20改成了21后，出现问/1286285)._

---
[severity:I'm unable to use this version]
System.TypeLoadException。
  Message=VTable setup of type Plugin.Bluetooth.BluetoothDevice failed。
Previously all are good, normal operation, because upgrade .net5, the standard library 2.0 changed to 2.1 after the problem

---
#### Feedback Bot on 12/13/2020, 06:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by danmosemsft** [comment]
Hello, is it possible to make a self-contained repro that you can put on Github somewhere? It is not possible to investigate without more info.

**Comment by joperezr** [comment]
Still no comments from the user that initially logged this through VS Feedback either here nor on the original VS Feedback post. I will go ahead and close this one for now, but feel free to reopen if you have a repro project or more info so that we can investigate.
