### ISSUE TITLE
MemoryExtensions.Scatter and MemoryExtension.Gather

### ISSUE THREAD

**Issue by hannni** [dotnet/runtime#46396]
## Background and Motivation
Two of the basic memory access patterns are [scatter](https://en.wikipedia.org/wiki/Memory_access_pattern#Scatter) and [gather](https://en.wikipedia.org/wiki/Memory_access_pattern#Gather). Memory cells are not accessed one after another like with sequential memory access, but are loaded from another memory area by a list of indices in the case of gather and are stored to another area by a list of indices in the case of scatter.

Gathering is a common memory access pattern, e.g. when using the [Struct of Array pattern](https://en.wikipedia.org/wiki/AoS_and_SoA#Structure_of_Arrays) (also know als [column store](https://en.wikipedia.org/wiki/Column-oriented_DBMS) in databases.

.NET has support for AVX2-intrinsics for gather and scatter, but you have to work with pointers and implement different code-paths for different architectures yourself.

## Proposed API

```diff
namespace System.Collections.Generic
{
    public static class MemoryExtensions 
    {
 +        public static void Scatter<T>(this ReadOnlySpan<T> values, ReadOnlySpan<int> indices, Span<T> target) { throw null; }
 +        public static void Gather<T>(this Span<T> values, ReadOnlySpan<int> indices, ReadOnlySpan<T> source) { throw null; }
    }
```

## Usage Examples

``` C#
public static char[] characters = new char[]
{
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
};

public static string Decode(int[] coded)
{
    return String.Create(
        coded.Length,
        coded,
        (charbuffer, indices) => charbuffer.Gather(indices, characters));
}
```

## Alternative Designs

 - Adding gather and scatter methods for `Vector<T>` would be a more lower-level alternative. However that would be a bad abstraction for systems without SIMD-support for gather and scatter.
 - Additionally having a method for combined gather scatter.

## Risks

The `Scatter` and `Gather` methods copy memory. Users might use it in cases where a copy might not be necessary.
`MemoryExtensions` might become bloated with too many speciality functions.

**Comment by KalleOlaviNiemitalo** [comment]
Can these be implemented in the runtime more efficiently than the same kind of loop you could implement in the application? It seems to me it would be difficult for the implementation to take advantage of SIMD intrinsics.

**Comment by GrabYourPitchforks** [comment]
I agree with @KalleOlaviNiemitalo's observations. Hardware-accelerated scatter / gather operations tend to have tight constraints placed on them. If we made a general-purpose API, we wouldn't place these same constraints. Developers wouldn't be able to reason about the perf characteristics of these methods, so we'd end up with people who cared continuing to use the intrinsic APIs rather than the `MemoryExtensions` alternatives.

Your idea of adding these operations to `Vector<T>` doesn't seem that bad, IMO. Wanting to normalize behavior across x86 + ARM archs might throw a wrench into it. Would need folks with more SIMD knowledge to take a closer look at that.

**Comment by GrabYourPitchforks** [comment]
I've repathed this to _System.Numerics_ because even though this question deals with `MemoryExtensions`, the depth of knowledge here really sits with the numerics team.

**Comment by FiniteReality** [comment]
Having something like this on `Vector<T>` would be hugely advantageous for me, who wants to write vectorised code but has little understanding of each SIMD instruction set and which CPUs they are available on. (For example, I discovered the hard way that Ryzen doesn't implement AVX512... D'oh :sweat_smile:)

Importantly, I'd be using this to implement audio processing algorithms in a fast and efficient manner, using scatter/gather operations to interleave and de-interleave audio channels as most audio formats interleave audio samples for each channel.

**Comment by tannergooding** [comment]
What is the expectation for platforms that do not support scatter/gather?

For example, `scatter` is only supported on `AVX-512+` and `gather` is only supported in a limited capacity on `AVX2+`, so would this simply do a set of sequential stores/loads for those platforms and would assume they are non-sequential?
