### ISSUE TITLE
System.Drawing.Common FromStream crash `Out of memory.` when image is invalid (Linux)

### ISSUE THREAD

**Issue by Socolin** [dotnet/runtime#46405]
When using `System.Drawing.Image.FromStream` with a stream that is not an image, it crash the whole application with `Out Of Memory`

### Repro

```
using System.IO;
using System.Linq;
using System.Text;

namespace ReproBugMicrosoft
{
    internal class Program
    {
        private static void Main()
        {
            System.Drawing.Image.FromStream(CreateInvalidImage());
        }

        private static Stream CreateInvalidImage()
        {
            var jpegPrefix = new byte[] {0xFF, 0xD8, 0xFF};
            var invalidImageData = Encoding.ASCII.GetBytes("Invalid format");
            var data = jpegPrefix.Concat(invalidImageData).ToArray();
            return new MemoryStream(data);
        }
    }
}
```

### csproj
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="System.Drawing.Common" Version="5.0.0" />
	</ItemGroup>

</Project>
```
### Output

```
** (process:1391934): WARNING **: 23:27:33.036: jpeg error: 70 Unsupported marker type 0x49

Out of memory.
```
### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by am11** [comment]
With surrounding try-catch in your `Main` method, the stack trace looks like this:

```
 System.OutOfMemoryException: Out of memory.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromStream(Stream stream)
   at ReproBugMicrosoft.Program.Main() in /gh-46405/Program.cs:line 13
```
the exception is originating from:
https://github.com/dotnet/runtime/blob/dada1303ec3367e194144974d049eead8c9d11d1/src/libraries/System.Drawing.Common/src/System/Drawing/Gdiplus.cs#L113-L114
although these exceptions are not [documented](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.fromstream#System_Drawing_Image_FromStream_System_IO_Stream_).

**Comment by safern** [comment]
Thanks, @am11. I believe this is the correct/expected behavior from our side as that is what libgdiplus is returning us from our call to: https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/jpegcodec.c#L664

I believe the only action as @am11 pointed out here is to update the documentation to include the exception. 

@Socolin where you expecting something different?

**Comment by Socolin** [comment]
> Thanks, @am11. I believe this is the correct/expected behavior from our side as that is what libgdiplus is returning us from our call to: https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/jpegcodec.c#L664
> 
> I believe the only action as @am11 pointed out here is to update the documentation to include the exception.
> 
> @Socolin where you expecting something different?

I was expecting to be able to fully parse an image from a stream without having to write it on a disk.

Without this feature (and the 2 other bug I've post ~ at the same time) I'm going to switch to another library.

**Comment by safern** [comment]
> I was expecting to be able to fully parse an image from a stream without having to write it on a disk.

I see... you should be able to as long the image is valid as `libgdiplus` checks for validity of images when loading an image either from a file or a stream. 

> Without this feature (and the 2 other bug I've post ~ at the same time) I'm going to switch to another library.

Sounds good. Note that we added `Unix` support using `libgdiplus` for compat only and since we don't maintain `libgdiplus` we can't promise a release cadence or bug fixing that is on pair with `System.Drawing.Common`. So in the docs we've added this as a note https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=dotnet-plat-ext-5.0#remarks and we recommend a couple of libraries that work well. 

Thanks for opening the issues 😄
