### ISSUE TITLE
[Dependency injection] Clarify confusing registration of a class against multiple interfaces 

### ISSUE THREAD

**Issue by Kamil-Zakiev** [dotnet/runtime#46409]
Hello! I've just encountered a non obvious behaviour of the DI-container: it creates a new instance of a class for each interface it implements. Check the test below which fails:
```csharp
[Fact]
internal void Should_ReturnTheSameInstance_When_ResolvedByDifferentInterfaces()
{
    var services = new ServiceCollection();

    services.AddSingleton<IBar1, Foo>();
    services.AddSingleton<IBar2, Foo>();

    var sp = services.BuildServiceProvider();
    
    Assert.Same(sp.GetRequiredService<IBar1>(), sp.GetRequiredService<IBar2>());
}

private sealed class Foo : IBar1, IBar2
{

}

private interface IBar1
{
}

private interface IBar2
{
}
```

Could you please clarify why it's working that way? 

If it's by design, please clarify the reasoning behind that non intuitive implementation, I'm really interested in that

**Comment by maryamariyan** [comment]
This is by design. The API 
```
public static IServiceCollection AddSingleton<TService, TImplementation>(this IServiceCollection services)
```

guarantees to give a unique instance of TService, it does not restrict uniqueness on TImplementation.
