### ISSUE TITLE
GetHashCode is returning different values for the same string content

### ISSUE THREAD

**Issue by ClimberBear** [dotnet/runtime#46406]
### Description

I'm using the GetHashCode method, on string class, to get unique values (more or less) over long content strings (in fact, urls).

This has been working fine a lot of time, but after upgrade to Net5 (version 5.0.1) it is returning differente values for the same string.

My code is really simple. I get an URL inside a string, and I get the hash. It can be summarized like this:

```
string? topicContent="https://www.cnmv.es/Portal/AlDia/Comunicaciones-Publicas.aspx/../verDoc.axd?t={3bdc10bf-5d57-4d57-8739-56670b927184}";
topicReference = "CNM-CMN-" + String.Format("{0:X8}", topicContent.GetHashCode());

```

Every time I execute, I get different results
For example, from debug output
topicContent	"https://www.cnmv.es/Portal/AlDia/Comunicaciones-Publicas.aspx/../verDoc.axd?t={3bdc10bf-5d57-4d57-8739-56670b927184}"	string
topicContent.GetHashCode()	-704561628	int
String.Format("{0:X8}", topicContent.GetHashCode())	"D6013E24"	string

```
topicContent	"https://www.cnmv.es/Portal/AlDia/Comunicaciones-Publicas.aspx/../verDoc.axd?t={3bdc10bf-5d57-4d57-8739-56670b927184}"	string
topicContent.GetHashCode()	2096317002	int
String.Format("{0:X8}", topicContent.GetHashCode())	"7CF3424A"	string
"https://www.cnmv.es/Portal/AlDia/Comunicaciones-Publicas.aspx/../verDoc.axd?t={3bdc10bf-5d57-4d57-8739-56670b927184}".GetHashCode()	2096317002	int
```

Screenshoot (same as previous)
![image](https://user-images.githubusercontent.com/23073263/103150404-25bf3b00-4774-11eb-98ee-9e90c8124398.png)

As you can see, I have tried directly from string content (to be totally sure I was checking same string), with same behaviour (different hash code every try)

### Configuration
Notice that my tests are from Visual Studio for Mac, version 8.8.4 build 30, and I run the code in debug mode. Also, I have added the option <nullable>enable</nullable> to the project.
I have tested from Visual Studio, and also publishing the code in Release mode, with same behaviour.

This is my project
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ReleaseVersion>0.3</ReleaseVersion>
    <UserSecretsId>68b88483-0ab0-44e3-819a-675052608fba</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\Spider\bin\Debug</OutputPath>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\Spider\bin\Release</OutputPath>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Services\" />
    <Folder Include="SqlScripts\" />
    <Folder Include="Services\Sources\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="appsettings.Debug.json" />
    <None Remove="appsettings.Release.json" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings %28copia%29.Debug.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Migrations\20191028092524_Version_0_0.Designer.cs" />
    <Compile Remove="Migrations\20191028092524_Version_0_0.cs" />
    <Compile Remove="Migrations\LegalDbContextModelSnapshot.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.Debug.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.Release.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="itext7" Version="7.1.13" />
  </ItemGroup>
</Project>

````

### Regression?

Yes. 
Working fine in previous releases Net Core 3.1

### Workaround

Following the comment from @theolivenbaum, I have created 2 extension methods

````
namespace Common.Tools {
	public static class PersistentHashCodeExtension {
		private static HashAlgorithm algorithm = SHA256.Create();

		public static int GetPersistentHashCode(this string str) {
			byte[] hash256;
			int hash = 0;

			hash256 = algorithm.ComputeHash(Encoding.UTF8.GetBytes(str));
			for (int i = 0; i < hash256.Length; i+=4) {
				hash ^= BitConverter.ToInt32(hash256, i);
			}

			return hash;
		}

		public static string GetPersistentHashString(this string str) {
			return String.Format("{0:X8}", GetPersistentHashCode(str));
		}
	}
}
`````

**Comment by theolivenbaum** [comment]
This is by design to avoid collision attacks on consumers of the GetHashCode method (such as dictionary or hashset classes). If you want to get a persistent unique identifier from a string, you'll need to roll out your own hash code - here's an example on how to do it: https://stackoverflow.com/a/6839784

**Comment by ClimberBear** [comment]
> This is by design to avoid collision attacks on consumers of the GetHashCode method (such as dictionary or hashset classes). If you want to get a persistent unique identifier from a string, you'll need to roll out your own hash code - here's an example on how to do it: https://stackoverflow.com/a/6839784

Do not agree:
From DOC in: 
https://docs.microsoft.com/en-US/dotnet/api/system.string.gethashcode?view=net-5.0#System_String_GetHashCode_System_ReadOnlySpan_System_Char__System_StringComparison_

"If two string objects are equal, the GetHashCode method returns identical values. However, there is not a unique hash code value for each unique string value. Different strings can return the same hash code."

So, somebody has changed the behaviour!!! The returned code has to be the same for the same strings. It can change if you change runtime version or implementation, but for the same runtime, has to be the same. It a bug clearly.

**Comment by theolivenbaum** [comment]
If you keep reading the doc link, there's an explanation of this:

```
Remarks
The behavior of GetHashCode is dependent on its implementation, which might change from one version of the common language runtime to another. A reason why this might happen is to improve the performance of GetHashCode.

 Important

If two string objects are equal, the GetHashCode method returns identical values. However, there is not a unique hash code value for each unique string value. Different strings can return the same hash code.

The hash code itself is not guaranteed to be stable. Hash codes for identical strings can differ across .NET implementations, across .NET versions, and across .NET platforms (such as 32-bit and 64-bit) for a single version of .NET. In some cases, they can even differ by application domain. This implies that two subsequent runs of the same program may return different hash codes.

As a result, hash codes should never be used outside of the application domain in which they were created, they should never be used as key fields in a collection, and they should never be persisted.

Finally, don't use the hash code instead of a value returned by a cryptographic hashing function if you need a cryptographically strong hash. For cryptographic hashes, use a class derived from the System.Security.Cryptography.HashAlgorithm or System.Security.Cryptography.KeyedHashAlgorithm class.

For more information about hash codes, see Object.GetHashCode.
```

**Comment by ClimberBear** [comment]
> If you keep reading the doc link, there's an explanation of this:
> 
Thanks, you are right!!

But this is not change the fact that the behaviour has changed in upgrade. This reminds me the classical joke: "What is a feature? A bug correctly documented". And it seems to be case here. Anycase, I close the bug, and thanks a lot your help.

**Comment by theolivenbaum** [comment]
I think this has been changed sometime ago already, but obviously depends on which version of the runtime you run against. I remember reading it on this blog post - also with a really good explanation of the issue: https://andrewlock.net/why-is-string-gethashcode-different-each-time-i-run-my-program-in-net-core/

**Comment by ClimberBear** [comment]
> I think this has been changed sometime ago already, but obviously depends on which version of the runtime you run against. I remember reading it on this blog post - also with a really good explanation of the issue: https://andrewlock.net/why-is-string-gethashcode-different-each-time-i-run-my-program-in-net-core/

Thanks again! Google failed to me this time. I did a search about this topic (I imagined that this will happen a lot of people around the world, specifically to old people like me coming from Java), but I did not find it.
