### ISSUE TITLE
Consider replacing IntrinsicAttribute with SpecialNameAttribute

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#46424]
We currently use `IntrinsicAttribute` to indicate that a name has a special meaning to the runtime/codegen and should be looked at. This matches what the ECMA-335 `specialname`/`rtspecialname` is for - these are dedicated bits in the IL metadata that are set for e.g. the `.ctor` method.

Roslyn respects `SpecialNameAttribute` and emits the `specialname` bit in the IL stream for it (i.e. it's a pseudocustom attribute in the sense that no custom attribute is emitted, just a bit is flipped in the metadata). Technically, we want `rtspecialname` but there's no facility in Roslyn to do that that I know of.

So we could use `SpecialNameAttribute` instead of `IntrinsicAttribute`.

```csharp
[SpecialName]
public struct Foo
{
    [SpecialName]
    public int Field;

    [SpecialName]
    public void GetFixed() { }
}
```

Gets emitted as:

```
.class public sequential ansi sealed beforefieldinit specialname Foo
       extends [System.Runtime]System.ValueType
{
    .field public specialname int32 Field

    .method public hidebysig specialname instance void 
            GetFixed() cil managed
    {
      // Code size       2 (0x2)
      .maxstack  8
      IL_0000:  nop
      IL_0001:  ret
    } // end of method Foo::GetFixed
} // end of class Foo
```

Benefits are twofold:

* Tiny runtime improvement. No need to walk custom attribute lists for methods/types when loading them within the VM.
* Tiny size improvement - no longer need to carry a custom attribute entry and a blob for each intrinsic method/type. No longer need to carry the type itself.

Cc @jkotas @GrabYourPitchforks @marek-safar for opinion

I'm putting this in the Future milestone unless there's excitement to do this. AFAIK we only use `IntrinsicAttribute` within the VM so we will be able to remove support for `[Intrinsic]` fully.

**Comment by EgorBo** [comment]
BTW, Mono doesn't use `[Intrinsic]` (afair, for the reason you described - fetching a custom attribute is slower than running a bunch of `!strcmp(...)` especially with binary search).

Can we ask Roslyn to emit `specialname` for `[Intrinsic]` as well?

**Comment by MichalStrehovsky** [comment]
> Can we ask Roslyn to emit `specialname` for `[Intrinsic]` as well?

Is there any advantage in doing that besides "it saves us from having to do `'s/Intrinsic/SpecialName/g'` within CoreLib sources"?

**Comment by EgorBo** [comment]
> > Can we ask Roslyn to emit `specialname` for `[Intrinsic]` as well?
> 
> Is there any advantage in doing that besides "it saves us from having to do `'s/Intrinsic/SpecialName/g'` within CoreLib sources"?

Not really, just not sure `[SpecialName]` name is as self-documenting as `[Intrinsic]` 🙂

**Comment by jkotas** [comment]
Property getters and setters get the special name bit by default. How would that work?

**Comment by MichalStrehovsky** [comment]
> Property getters and setters get the special name bit by default. How would that work?

Hm, wonder how much noise we would get with that.

I guess then we need a `RTSpecialNameAttribute` then. We would still get a conflict with `.ctor` and `.cctor` but those checks already happen in many places anyway and those are the places that could disambiguate.

That makes all of this more involved.

**Comment by Joe4evr** [comment]
> I guess then we need a `RTSpecialNameAttribute` then. We would still get a conflict with `.ctor` and `.cctor` 

Would it cause an actual problem if the bit is being set more than once?

**Comment by MichalStrehovsky** [comment]
The runtime/JIT needs to `strcmp` the name with a bunch of known names if the bit is set, so we don't want it to be set on too many irrelevant things. rtspecialname is specifically for situations when the name is relevant to the runtime and needs to be looked at. Searching for `IsMdRTSpecialName` in the CLR codebase finds all such places.

**Comment by MichalStrehovsky** [comment]
We have about 600 things annotated with `[Intrinsic]` in the CoreLib. With 12 bytes per custom attribute table entry + 4 bytes for the data blob, the potential size saving is about 10 kB. The runtime saving (not having to `strcmp` a bunch of attributes just to see the method/type is not interesting but check a bit instead) is harder to estimate so I'm not going to bother.

**Comment by marek-safar** [comment]
> Technically, we want rtspecialname but there's no facility in Roslyn to do that that I know of.

We always run illink during libraries build and we could use it to do the transformation of [Intrinsic] to `RTSpecialNameAttribute`.

> the potential size saving is about 10 kB

It's probably less as that would mean none of the methods is trimmed but even 5k would be nice to save.

**Comment by KalleOlaviNiemitalo** [comment]
> With 12 bytes per custom attribute table entry + 4 bytes for the data blob

You would not get any savings from the data blob. It is already deduplicated in each module and shared by all `[Intrinsic]` CustomAttribute rows and other attributes besides.
