### ISSUE TITLE
SmtpClient UseDefaultCredentials different behavior between netcore3.1 and net5.0

### ISSUE THREAD

**Issue by DaveSenn** [dotnet/runtime#46430]
### Description

We used the following code to send E-Mails using SmtpClient:

```c#
using System;
using System.Net;
using System.Net.Mail;
using System.Text;

namespace MailTest
{
    internal class Program
    {
        private static void Main( String[] args )
        {
            Console.WriteLine( "Starting..." );

            const String host = "";
            const Int32 port = 25;
            const String userName = "";
            const String password = "";
            const Boolean ssl = false;
            const String from = "";
            const String to = "";
            
            var credentials = new NetworkCredential( userName, password );

            var mail = new MailMessage( new MailAddress( from ), new MailAddress( to ) )
            {
                Subject = "Test Mail",
                SubjectEncoding = Encoding.UTF8,
                Body = "Test from code",
                BodyEncoding = Encoding.UTF8,
                IsBodyHtml = false,
                Priority = MailPriority.Normal
            };

            var smtpClient = new SmtpClient
            {
                Host = host,
                Port = port,
                UseDefaultCredentials = credentials != null, // Worked with .netcore3.1 ...but does not work anymore with .net5.0
                Credentials = credentials!,
                EnableSsl = ssl,
                Timeout = 5000,
                DeliveryMethod = SmtpDeliveryMethod.Network
            };

            try
            {
                smtpClient.Send( mail );
                Console.WriteLine( "Sent..." );
            }
            catch ( Exception ex )
            {
                Console.WriteLine( ex );
            }

            Console.WriteLine( "Done..." );
            Console.ReadLine();
        }
    }
}
```

I know the commented line with `UseDefaultCredentials = credentials != null` is wrong.
But this somehow works with netcore3.1. After changing the target framework to net5.0 this stopped working. If we change the line to `UseDefaultCredentials = credentials == null` it works again.

I know its a bug in our code. But the behaviour between netcore3.1 and net5.0 changed. Maybe this is documented somewhere but i couldn’t find anything. Maybe this would be worth documenting somewhere.

### Configuration

* .NET 5.0 (5.0.101)
* Win 10 20H2
* x64
* Same "problem" exists on different machines e.g. WInServer 2016

### Regression?

"Regression" from netcore3.1 to net5.0

**Comment by wfurt** [comment]
It seems like with 3.1, even if I pass in `UseDefaultCredentials = true`, printing smtpClient.UseDefaultCredentials, still shows `false`.

It seems like 3.1 had some automatic logic to determine this by comparing references. 
for 5.0 it uses what ever is passed in since https://github.com/dotnet/corefx/pull/41271

**Comment by karelz** [comment]
Agreed, looks like a technical breaking change due to fixed bug. I don't think it makes sense to document it unless we see more people running into it and be surprised.

**Comment by karelz** [comment]
Closing as addressed.
