### ISSUE TITLE
Count json

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#46446]
Hi,

Why there is no way to count the result like this:

```
PINData data = JsonSerializer.Deserialize<PINData>(result);
LabelCount.Text = data.Count;

```

**Comment by huoyaoyuan** [comment]
It's depends on the structure of your json. If it's a json array, you can deserialize it in `SomeData[]`, and count the array.

**Comment by layomia** [comment]
I don't understand the problem being described. If you still have issues here, please provide a full repro.
