### ISSUE TITLE
Unexpected CamelCase formatting in System.Text.Json

### ISSUE THREAD

**Issue by Ilchert** [dotnet/runtime#46445]
### Description
Unexpected formatting for dictionary keys using `System.Text.Json`.

Expected value `some_3`.
Actual value `somE_3`.

```C#
var o = new JsonSerializerOptions()
{
     DictionaryKeyPolicy = JsonNamingPolicy.CamelCase
};
var data = new Dictionary<string, object> { { "SOME_3", "" } };
var text = JsonSerializer.Serialize(data, o); // {"somE_3":""}
```

### Configuration

* Which version of .NET is the code running on? NET5.0.101
* What OS and version, and what distro if applicable? Win10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No

### Regression?
Previously the value had not changed.

**Comment by huoyaoyuan** [comment]
Are you using ASP.NET? This is a known change in ASP.NET Core 5.0.

**Comment by Ilchert** [comment]
@huoyaoyuan yes, aspnet. Could you provide a description of this change?

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/docs/issues/21067

**Comment by Ilchert** [comment]
@huoyaoyuan, thanks for the link, but my issue about upper case of char `E` in `SOME_3 -> somE_3` transformation, not about quoted numbers.

**Comment by huoyaoyuan** [comment]
The camel case handler does not have well-defind behavior for all capitalized. You should use an option to not convert the name at all. It there already such option?

**Comment by layomia** [comment]
Preliminary note that `System.Text.Json` has the same behavior as Newtonsoft.Json here - https://dotnetfiddle.net/ViFFmX.

We'll likely not do any work here (given it would be a non-trivial breaking change), unless something related spills out of the feature work for snake_case support (https://github.com/dotnet/runtime/issues/782) in an effort to have a central algorithm between snake case, camel case, and any feature casing policies.

The work around here is to implement a custom [`JsonNamingPolicy`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonnamingpolicy?view=net-5.0)  which uses [`JsonNamingPolicy.CamelCase`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonnamingpolicy.camelcase?view=net-5.0#System_Text_Json_JsonNamingPolicy_CamelCase) as the main logic, but handles edge-cases such as you've described above.
