### ISSUE TITLE
deserialization of empty string to nullable value fails using System.Text.Json.Serialization

### ISSUE THREAD

**Issue by Itsamirmasoud** [dotnet/runtime#46448]
### Description

* Please share a clear and concise description of the problem.

today I came across an issue that seems to be related to System.Text.Json.Serialization. I am posting an empty string via axios to my API, the posted empty string property in JSON object is mapped to a nullable property in a C# class. as explained in [#37913](https://github.com/dotnet/runtime/issues/37913) , the deserializer should map the empty string to null value. but it is throwing an exception like so : 

`The JSON value could not be converted to System.Nullable`1[System.Byte]. Path:`

* Include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small repo to clone, with steps to run it.

so i prepared a test case and i think there is indeed a bug here somewhere, here is the test :

Sample class : 
```
public class SampleModel
{
        public byte? Value { get; set; }
}
```
test is simple, i want to Deserialize an JSON object into corresponding C# class : 

I ran the test under following conditions and option 

```
var options = new JsonSerializerOptions();
options.NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString;

var body = @"{""Value"":""""}";
var model = JsonSerializer.Deserialize<SampleModel>(body, options);
==>  throws exception


var body1= @"{""Value"":1}";
var model1 = JsonSerializer.Deserialize<SampleModel>(body1, options);
  == > model1 = 1
          no exception, value deserialized correctly
```

now with `PropertyNamingPolicy`  set to `CamelCase` : 
```
var options = new JsonSerializerOptions();
options.NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString;
options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;

var body = @"{""value"":""""}";
var model = JsonSerializer.Deserialize<SampleModel>(body, options);
==>  throws exception

var body1= @"{""value"":1}";
var model1 = JsonSerializer.Deserialize<SampleModel>(body1, options);
 == > model1 = 1
          no exception, value deserialized correctly
```

* What behavior are you seeing, and what behavior would you expect?

current behavior : an exception is thrown when deserilizing empty string to nullable property.
 expected behavior : the empty string deserilize into null value when property is nullable

### Configuration

* Which version of .NET is the code running on? .Net 5
* What OS and version, and what distro if applicable? Windows 10 Pro

**Comment by huoyaoyuan** [comment]
This is the desired behaviour. Json does have `null`. The correspondint json should be `{"value": null}`.

Using empty string is strictly violating the schema. Such malform can be handled by a common converter (like quoted numbers), but not the basic deserializer.
