### ISSUE TITLE
System.Drawing.DrawString not respecting FontStyle.Bold on Mac or Linux

### ISSUE THREAD

**Issue by vjpudelski** [dotnet/runtime#46468]
### Description

When trying to draw text on a bitmap the text appears with the same font weight regardless of using FontStyle.Bold. I have a reference to the System.Drawing.Common package and have installed the necessary dependencies. I have tested this on both linux and macOS and both present the issue while Windows appears as expected. This is also true for FontStyle.Italic.

### Sample Code

      using (var newImage = new Bitmap(300, 300))
      {
        using (var graphics = Graphics.FromImage(newImage))
        {
          graphics.DrawString("Hello World", new Font("Arial", 16, FontStyle.Bold), Brushes.Blue, 10, 10);
          graphics.DrawString("Hello World", new Font("Arial", 16, FontStyle.Regular), Brushes.Blue, 10, 50);
        }

        newImage.Save("mypng.png", ImageFormat.Png);
      }

**Comment by am11** [comment]
libgdiplus [package on Ubuntu](https://packages.ubuntu.com/bionic/libs/libgdiplus) is an ancient five years old version [4.2](https://github.com/mono/libgdiplus/releases/tag/4.2).

The one from brew is recent (v6.0.5) but they are missing `  depends_on "pango"`: https://github.com/Homebrew/homebrew-core/blob/19711e622bf573cba0d2c8f9f8275a097c8c3e80/Formula/mono-libgdiplus.rb#L17-L31, so it builds without proper text renderer library, pango.

Current solution is to compile libgdiplus from source on these platforms, with pango prerequisite: https://github.com/mono/libgdiplus/tree/9efff6a9ed1c3286362270b704dcdcf7a2670d54#requirements

![mypng](https://user-images.githubusercontent.com/3840695/103452871-b0f08180-4cdc-11eb-8202-b0b0523bf26b.png)

**Comment by safern** [comment]
Thanks, @am11. Closing since this is a libgdiplus issue.
