### ISSUE TITLE
NativeLibrary documentation: Cache result of System.Runtime.InteropServices.DllImportResolver 

### ISSUE THREAD

**Issue by badcel** [dotnet/runtime#46463]
I found the discussion about updating the docs regarding `NativeLibrary` in https://github.com/dotnet/runtime/issues/41180#issuecomment-678568362. As i did not want to hijack the discussion I open this issue to improve the documentation on `NativeLibrary`.

@jkotas I just wanted to raise the question if it is valid to cache the `IntPtr` to an assembly in the given resolver of `SetDllImportResolver (System.Reflection.Assembly assembly, System.Runtime.InteropServices.DllImportResolver resolver);`?

I think this could be an important information in the docs because it is very tempting to cache the found `IntPtr` of `NativeLibrary.TryLoad` but it is not clear from the documentation if this is valid in all cases.

Sample code:

```C#
private static IntPtr DllImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
{
    if (cache.TryGetValue(libraryName, out var cachedLibHandle))
        return cachedLibHandle;

   if (NativeLibrary.TryLoad(GetOsDependentLibraryName(libraryName), assembly, DllImportSearchPath.LegacyBehavior, out var libHandle))
   {
        cache[libraryName] = libHandle;
        return libHandle;
   }

    return IntPtr.Zero;
}
```

**Comment by jkotas** [comment]
It is ok to cache this pointer, as long as your code does not call `NativeLibrary.Free` on it. The runtime itself does not do any lifetime management with `DllImportResolver`, it assumes that your code will keep the library loaded long enough.

> DllImportSearchPath.LegacyBehavior

Is there a good reason that you ignoring the requested `searchPath` and hardcoding `DllImportSearchPath.LegacyBehavior` behavior instead? I think the typical pattern would be to pass the requested searchPath through.

**Comment by badcel** [comment]
Thank you for your feedback and help. As this could result in some performance gain it would be great seeing it documented.

Regarding the `DllImportSearchPath.LegacyBehavior` we actually never had taken over the value from the delegate as there are some [examples](https://developers.redhat.com/blog/2019/09/06/interacting-with-native-libraries-in-net-core-3-0/) suggesting otherwise. I try to contact the author. We will test if your suggested change is working for us on all platforms. Thank you very much!
