### ISSUE TITLE
Add APIs to make nint & nuint match Int32 and Int64

### ISSUE THREAD

**Issue by Cyl18** [dotnet/runtime#46467]
## Background and Motivation

Almost all numeric types have `Parse` and `TryParse` ReadOnlySpan<char> overload, I think it's good for `nint` to have them too.
Edit: `int` also has `TryFormat` method which contains `ReadOnlySpan<char>` parameter, so I added `TryFormat`.

## Proposed API

```diff
namespace System
{
    public class IntPtr {
+        public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null) { }
+        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out IntPtr result) { }
+        public static bool TryParse(ReadOnlySpan<char> s, out IntPtr result) { }
+        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null) { }
     }
}
```

```diff
namespace System
{
    public class UIntPtr {
+        public static UIntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null) { }
+        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out UIntPtr result) { }
+        public static bool TryParse(ReadOnlySpan<char> s, out UIntPtr result) { }
+        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null) { }
     }
}
```
Update 2021.1.6: Change `Parse` and `TryParse` to match Int32 and Int64's signature and add `TryFormat`.
Update 2021.1.12: Add nuint

## Risks

---
I'm happy to PR this myself if this API is approved :)

**Comment by stephentoub** [comment]
To match what's on Int32 and Int64, instead of:
```C#
public static IntPtr Parse(ReadOnlySpan<char> s) { }
public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) { }
```
I think we'd want:
```C#
public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null)
```

**Comment by Cyl18** [comment]
> To match what's on Int32 and Int64, instead of:
> 
> ```cs
> public static IntPtr Parse(ReadOnlySpan<char> s) { }
> public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider) { }
> ```
> 
> I think we'd want:
> 
> ```cs
> public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null)
> ```

I agree with you

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System
{
    public class IntPtr
    {
        public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null);
        public static bool TryParse(ReadOnlySpan<char> s, out IntPtr result);
        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out IntPtr result);
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null);
    }
    public partial class UIntPtr
    {
        public static UIntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null);
        public static bool TryParse(ReadOnlySpan<char> s, out UIntPtr result);
        public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out UIntPtr result);
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null);
     }
}
```

**Comment by Cyl18** [comment]
> * Looks good as proposed
> 
> ```cs
> namespace System
> {
>     public class IntPtr
>     {
>         public static IntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null);
>         public static bool TryParse(ReadOnlySpan<char> s, out IntPtr result);
>         public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out IntPtr result);
>         public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null);
>     }
>     public partial class UIntPtr
>     {
>         public static UIntPtr Parse(ReadOnlySpan<char> s, NumberStyles style = NumberStyles.Integer, IFormatProvider? provider = null);
>         public static bool TryParse(ReadOnlySpan<char> s, out UIntPtr result);
>         public static bool TryParse(ReadOnlySpan<char> s, NumberStyles style, IFormatProvider? provider, out UIntPtr result);
>         public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null);
>      }
> }
> ```


Who will impl this? Can I try to PR this myself? :)

**Comment by tannergooding** [comment]
> Can I try to PR this myself? :)

Definitely. I tend to mark most of the `area-System.Numerics` issues as `up-for-grabs` once approved and then anyone is free to comment that they'd like to pick it up 😄 

I'm happy to answer any questions if you have them and let me know if you get stuck.

**Comment by Cyl18** [comment]
@tannergooding I noticed that `TryFormat` was already being implemented, so the proposal might need to be changed
![image](https://user-images.githubusercontent.com/14993992/106186671-8dd3c780-61df-11eb-94bd-5e717d3cb5b7.png)

**Comment by tannergooding** [comment]
It's implemented, but internal explicitly done and therefore private since `ISpanFormattable` is `internal`

The API should just become `public bool TryFormat`, as is done for `Int32` and others

**Comment by Cyl18** [comment]
> It's implemented, but internal explicitly done and therefore private since `ISpanFormattable` is `internal`
> 
> The API should just become `public bool TryFormat`, as is done for `Int32` and others

(Int32)
![Int32](https://user-images.githubusercontent.com/14993992/106188206-a218c400-61e1-11eb-8352-66587697eab6.png)
(Change)
![image](https://user-images.githubusercontent.com/14993992/106188338-d1c7cc00-61e1-11eb-8a19-b81573fbc8d5.png)

Is it okay to just add a `public` to `TryFormat`? It's like what in `Int32`
