### ISSUE TITLE
DateTime.Parse ISO 8601 allowing extra arbitrary character at the end of the date

### ISSUE THREAD

**Issue by TheGeneral-dev** [dotnet/runtime#46477]
When parsing an ISO 8601 DateTime the parser allows 1 single extra arbitrary character 

The following dates are all parsed correctly 

2020-5-7T09:37:00.0000000-07:00

2020-5-7T09:37:00.0000000-07:00x

2020-5-7T09:37:00.0000000-07:00@

In summary 

1. When parsing in `ParseISO8601` it grabs the correct *timezone* information `-07:00` in `ParseTimeZone`
2. This leaves the `str` with 1 last index
3. It then checks for `str.Match('#')` which *prefix increments* the index (which I believe is the fault). 
4. At this point it assumes the parsing is complete in subsequent checks due to the index being at the end of string

This seems to be a problem in 

````
//
// Parse the ISO8601 format string found during Parse();
//
//
private static bool ParseISO8601(ref DateTimeRawInfo raw, ref __DTString str, DateTimeStyles styles, ref DateTimeResult result) {
````

In particular, when given a valid *ISO 8601* `DateTime`,  `ParseTimeZone` will return the correct timezone, and at this point  `str` has 1 valid index left (the arbitrary character)

It then checks for a _hash_ with `str.Match('#')` 

````
   ...
   str.SkipWhiteSpaces();
   if (str.Match('#'))
   {
      if (!VerifyValidPunctuation(ref str))
      {
         result.SetFailure(ParseFailureKind.Format, "Format_BadDateTime", null);
         return false;
      }
      str.SkipWhiteSpaces();
   }
   if (str.Match('\0'))
   {
      if (!VerifyValidPunctuation(ref str))
      {
         result.SetFailure(ParseFailureKind.Format, "Format_BadDateTime", null);
         return false;
      }
   }
   if (str.GetNext())
   {
      // If this is true, there were non-white space characters remaining in the DateTime
      result.SetFailure(ParseFailureKind.Format, "Format_BadDateTime", null);
      return false;
   }
}
````

Since `Match` _prefix increments_ the index and compares it with the valid length, the check fails, however the string is still incremented. 

````
internal bool Match(char ch)
{
   if (++Index >= len)
   {
      return (false);
   }
   if (Value[Index] == ch)
   {
      m_current = ch;
      return (true);
   }
   Index--;
   return (false);
}
````

The result of this allows the date to pass the next 2 checks on  `str.Match('\0')` and `str.GetNext()` without causing an error. 

What it seems like its designed to do, is check the _**current**_ character for _hash_, then _null termination_, then fail if there is anything else left.

Note : this is not a problem with 2 arbitrary characters, as the index is decremented back to the original and the checks perform as expected.

**Comment by lateapexearlyspeed** [comment]
Hi @tarekgh Based on issue description, I just try to have a look and change the related code, seems changing DTString.Match() cannot fix issue but the description of DTString.Match make me notice [here](https://github.com/dotnet/runtime/blob/21baf31b19ebdc79ee400e44c212b983add00501/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeParse.cs#L3000) . I traced code and found when method ParseTimeZone return true, it did not set back Index so that after ParseTimeZone return, the index points to that arbitrary character already. After changing code to set index to char before arbitrary character, seems my added test for issue can pass and all tests in DateTimeTests can pass also.

If that thought is ok, will raise a PR for that, thanks !

**Comment by tarekgh** [comment]
@lateapexearlyspeed thanks a lot for willing to help with that. I agree with your analysis and suggestion here. in short, just inserting `str.Index--;` at the line 
https://github.com/dotnet/runtime/blob/21baf31b19ebdc79ee400e44c212b983add00501/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeParse.cs#L3005 would make it work I guess.

**Comment by lateapexearlyspeed** [comment]
@tarekgh Yes, and thanks for confirmation, I will raise PR later :)
