### ISSUE TITLE
Missing .NET 5 Desktop Runtime installers for ARM64

### ISSUE THREAD

**Issue by worproject** [dotnet/runtime#46470]
There are no ARM64 installers for the .NET 5 Desktop Runtime on the downloads page: https://dotnet.microsoft.com/download/dotnet/5.0

Previous RC builds have links for that.

**Comment by jkotas** [comment]
Windows Desktop components were not ready for prime time in .NET 5. See https://devblogs.microsoft.com/dotnet/announcing-net-5-0/#windows-arm64 for details.

**Comment by jkotas** [comment]
You can follow https://github.com/dotnet/installer/issues/8905 for updates.

**Comment by worproject** [comment]
Thanks!
