### ISSUE TITLE
ConcurrentBag<T> does not implement ICollection<T>

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#46473]
Can you please add this interface?

**Comment by Symbai** [comment]
Can you please tell us why?

**Comment by TonyValenti** [comment]
I have a number of extension methods that I work with to simplify adding things to ```ICollection<T>```'s.  Because it doesn't implement the ICollection<T> interface, I can't use them.

**Comment by huoyaoyuan** [comment]
I would say no. All the concurrent collections don't implement standard mutable collection interfaces.

You should not use concurrent collections like non-concurrent ones. If you want interface, please use `IProducerConsumerCollection<T>`.

**Comment by TonyValenti** [comment]
Why not though?  it seems to me that any Generic Collection should be a ... Generic ICollection.  I would expect implementing the interface to be an extremely small amount of work that would bring the Concurrent generic collections parity with their non-concurrent counterparts.

Plus - they already implement ICollection.

**Comment by huoyaoyuan** [comment]
> Plus - they already implement ICollection.

This looks to be very **intentional**. Non-generic `ICollection` doesn't provide `Add` and `Remove`.

After peeking it's API interface, it cannot implement `ICollection<T>` at all, because there's no `Remove(T item)` method.

**Comment by TonyValenti** [comment]
Isn't that essentially what the ```TryTake``` method is?

**Comment by huoyaoyuan** [comment]
No. Look at there signatures.

Generally, only `ConcurrentDictionary<T>` supports the operation of *finding certain element*. It's necessary for `Contains` and `Remove`.

**Comment by huoyaoyuan** [comment]
Additional words for you:

Concurrent collections are different from non-concurrent ones under a lock. They drop other operations to speed up certain operations under different threads.

`Add` is the operation that's not dropped. But, adding/removing interface is still a too heavy change. The interfaces are also "heavy" because it requires more operations.

The future approach should be roles/shapes.

**Comment by eiriktsarpalis** [comment]
> > Plus - they already implement ICollection.
>
> This looks to be very intentional. Non-generic ICollection doesn't provide Add and Remove.

That's correct and FWIW the concern doesn't exclusively apply to concurrent collections. There are many `System.Collections.Generic` collections that do not implement `ICollection<T>`, for instance `Queue<T>` and `Stack<T>`.

**Comment by eiriktsarpalis** [comment]
`ICollection<T>` has methods like `Contains` and `Remove` that are not supported in `ConcurrentBag<T>`. Similar to other generic collections, I don't think that this one should implement `ICollection<T>`.
