### ISSUE TITLE
GC question: Will object allocated on SOH migrate to LOH?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#46482]
I try to have a test on memory leak sample.

I had a `static ConcurrentBag` variable, and I'll add an item to the bag on every method call, and I found it was allocated in LOH, 

I think it should allocated to gen-0 on SOH firstly, promoted to gen-1 and then gen-2, is there something I missed?

So I wondering that will a object allocated on SOH migrate to LOH? If yes, when'll this happen?

The code I used for test is like follows:

``` csharp
private static readonly ConcurrentBag<long> Bags = new ConcurrentBag<long>();

[HttpGet]
public IActionResult MemoryLeak()
{
    Bags.Add(DateTime.UtcNow.Ticks);
    return Ok();
}
```

The runtime metrics I captured is as follows:

![image](https://user-images.githubusercontent.com/7604648/103403941-ee45f980-4b8c-11eb-9a7b-51a55570f84c.png)

Thanks.

**Comment by ANahr** [comment]
Most collection types use some kinds of array internally. And as soon as you have put enough elements into it it will have to reallocate a larger array.
Large arrays are always directly allocated in LOH.

**Comment by WeihanLi** [comment]
Got it, thanks @ANahr , happy new year.
