### ISSUE TITLE
Is there some way that I can limit the process cpu usage?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#46483]
Sometimes we wanna have resource limit for our application

For memory limit we could use the runtime GC settings <https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#heap-limit> to limit GC memory usage.

Is there some runtime config like this could be used for CPU limit?

**Comment by huoyaoyuan** [comment]
You can set a memory limit for CLR because memory is "scheduled" by CLR (GC allocator).
For CPU usage, it could only be an OS feature, because CPU is scheduled by the OS. CLR effectively takes all CPU resource from OS.

**Comment by mangod9** [comment]
If its possible to host your app within a container, you could use core based restrictions to limit cpu usage per container.

**Comment by fbrosseau** [comment]
Either containers, or if you want to stay with regular processes only, Job Objects would do the trick. (JOBOBJECT_CPU_RATE_CONTROL_INFORMATION  etc).

**Comment by WeihanLi** [comment]
Thanks for the information, and yes I wanna run it directly on my os(windows and linux) not container environment, happy new year @huoyaoyuan @mangod9 @fbrosseau

**Comment by mangod9** [comment]
Closing for now, please reopen if you need any further info.
