### ISSUE TITLE
Libraries tests timing out on (Alpine.312.Arm32.Open)Ubuntu.1804.ArmArch.Open

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#46484]
https://dev.azure.com/dnceng/public/_build/results?buildId=934800&view=logs&jobId=62876419-b96e-5483-94d3-b47175c1afe7&j=62876419-b96e-5483-94d3-b47175c1afe7&t=69034341-3a68-59aa-c247-b3e7d2608abb took longer than 2h30min and timed out. We could increase the the timeout and/or investigate the pool's health.

cc @MattGal @dotnet/runtime-infrastructure

**Comment by MattGal** [comment]
Definitely something weird here; that job's technically not finished yet.  I am making an investigation and will reply back.

**Comment by MattGal** [comment]
This is an interesting one.  It happened around 2020-12-31 00:28:27 UTC.  The job details from Helix API indicates we had an error sending the work to service bus and only sent the first batch of 50 items (so the remaining 190 could never finish). However, our logging got lost and Service Bus didn't report any errors itself in this time, so I've opened up two issues about my investigation:

[Helix JobEnqueueFailure needs to be understood by Arcade Helix SDK and cause fast failure](https://github.com/dotnet/arcade/issues/6733)
[Helix API's logging is not connected to Application Insights](https://github.com/dotnet/core-eng/issues/11791)

Unless this starts happening repeatedly (which would actually be helpful for investigation given we don't know the unhandled exception thrown) I don't think there's much use for having a runtime issue open IMO.

**Comment by safern** [comment]
Let's leave it open for a little while with the `blocking-clean-ci` label to raise visibility and see if we get any other hits before closing it here in dotnet/runtime as having an issue here helps discoverability.

**Comment by ViktorHofer** [comment]
Closing as we are moving onto alpine 3.13 and 3.14 for testing.
