### ISSUE TITLE
JsonConstrutor different behavior between Newtonsoft.Json and System.Text.Json

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#46480]
### Description

```cs
    public class Q
    {
        [JsonConstructor]
        public Q(int? x)
        {
            if (x is null) throw new Exception();
            X = x.Value;
        }
        
        public int X { get; }
    }
```

Given string:
```cs
var str = JsonSerializer.Deserialize<Q>("{\"X\":123}" ");
```

It is deserialized fine with Newtonsoft, but not with System.Text.
The reason is that constructor parameter type is `int?` while the property has type of `int`.
Newtonsoft doesn't validate it, giving an option to do anything in the constructor.

There are possible workarounds but they are not as simple as the original code:

Make property private and add a public non nullable: 
```cs
    public class Q
    {
        [JsonConstructor]
        public Q(int? x)
        {
            if (x is null) throw new Exception();
            X = x.Value;
        }

        public int? X { get; }

        [JsonIgnore]
        public int NonNullableX => X!.Value;
    }
```

Annotate nullable as non nullable, however it requires explicit call to `Value`.:

```cs
    public class Q
    {
        [JsonConstructor]
        public Q(int? x)
        {
            if (x is null) throw new Exception();
            X = x.Value;
        }

        [DisallowNull][NotNull]
        public int? X { get; }
    }
```

### Regression?

Not a regression.

**Comment by Clockwork-Muse** [comment]
Um, if you throw an exception like that, why not just make the constructor take a non-nullable?

**Comment by NN---** [comment]
It is a general question.
The argument validation can be more complicated than this.

**Comment by layomia** [comment]
Dup of https://github.com/dotnet/runtime/issues/44428/.
