### ISSUE TITLE
Set <GeneratePackage /> on projects that should produce packages during servicing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#46485]
https://github.com/dotnet/runtime/commit/752c927cf26a3c57190d46b3635de52cc49b203e added the ability to service packages incrementally and consistently throughout the repo. We use the term "service incrementally" when we only publish packages that changed during a servicing release.

For any package that should by default be generated during servicing, the `<GeneratePackage Condition="'$(PreReleaseVersionLabel)' == 'servicing'">true</GeneratePackage>` property should be set.
The condition isn't strictly required but it would allow to differentiate between "runtimelab" and "runtime in servicing mode". If we think it would make sense to have a separate property just for servicing (to avoid the condition) we could introduce a `<GeneratePackageForServicing />` property which would influence the `<GeneratePackage />` property (in Directory.Build.targets).  That said, I don't think it's worth it.

TODO: I need to document the new `<GeneratePackage />` property.

@anipik do we have libraries packages that should always be generated?
@jkoritzinsky should the sfx packages always be generated? what about the host packages?
@trylek @jkoritzinsky as coreclr set `<IsShipping />` to false in release/5.0 for servicing, I assume that none of the coreclr packages should be shipped during servicing by default?
@akoeplinger I assume there aren't any mono packages that should be shipped by default in servicing?

**Comment by jkoritzinsky** [comment]
The shared framework projects use the ProjectServicingConfiguration items to configure when to build a project in servicing.

**Comment by ViktorHofer** [comment]
@jkoritzinsky thanks, I will make sure that the newly added infra doesn't apply to sfxprojs then. Do you know about the host packages. Do we always ship them in servicing releases?

**Comment by jkoritzinsky** [comment]
To my knowledge we ship them in servicing releases. I didn't add any code to make us not ship them in servicing.

**Comment by ViktorHofer** [comment]
@safern is there a way to identify if the build is a runtimelab build? I currently have this placeholder in code which obviously doesn't work: https://github.com/dotnet/runtime/blob/d77092decb2bbd7bc94cd548af925d801a032e9e/Directory.Build.props#L242

**Comment by safern** [comment]
> <GeneratePackage Condition="'$(PreReleaseVersionLabel)' == 'servicing'">true</GeneratePackage>

What would happen when we are producing a servicing stable release (i.e no prerelease label is inclduded). 

> @safern is there a way to identify if the build is a runtimelab build? I currently have this placeholder in code which obviously doesn't work:

I was thinking about this the other day, the problem is that runtimelab is based off `dotnet/runtime`. So we have the `runtime-master` branch in runtimelab which is mirrored automatically when a commit goes into `dotnet/runtime`. That means that any new experiment, would be created from that branch and the `RepositoryName` property would be set to `runtime`. https://github.com/dotnet/runtime/blob/71d1aadddb3d8b6328d29ff0b772a6e51e666eda/Directory.Build.props#L219

What we could do is add a requirement in the `CreateExperiment.md` docs that people creating new experiments update that property to `runtimelab`? 

Another option is using the AzDo environment variable for the repository name, but that wouldn't work on a local dev build.

**Comment by ViktorHofer** [comment]
> What we could do is add a requirement in the CreateExperiment.md docs that people creating new experiments update that property to runtimelab?

I think that sounds reasonable as other parts that rely on `<GitHubRepositoryName />` wouldn't work either already today. Let's add that as a requirement to the Markdown file. Can you take care of that and I'll update the condition to use that property?

**Comment by safern** [comment]
> Can you please take care of that for runtimelab?

Sure.

> Do we also need to update the existing branches?

Yeah, I'll put up a PR to all branches to take care of that.

**Comment by akoeplinger** [comment]
@ViktorHofer which packages are we talking about here? runtime packs? or OOB nugets?

**Comment by ViktorHofer** [comment]
All packages that we produce in dotnet/runtime except .sfxprojs (shared framework packages) which come with their own servicing infra.

**Comment by akoeplinger** [comment]
Ok then yeah to answer to your question:
> @akoeplinger I assume there aren't any mono packages that should be shipped by default in servicing?

We need to ship the runtime packs for Browser/iOS/tvOS in servicing, as well as possibly packages like BrowserDebugHost and BrowserDebugProxy in servicing if they have bug fixes.

There's also the s390x work ongoing in dotnet/runtimelab and we'll need a way to still create packages there (not in CI though).

**Comment by ViktorHofer** [comment]
Closing as this was replaced with `GeneratePackageOnBuild` and is currently only set for src/libraries.
