### ISSUE TITLE
Test_EventSource_EtwManifestGenerationRollover failed in CI

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#46518]
net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open
https://dev.azure.com/dnceng/public/_build/results?buildId=936179&view=ms.vss-test-web.build-test-results-tab&runId=29613832&resultId=177187&paneView=debug
```
BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover

Error message
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Child exception:
  Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGenerationRollover>b__6_0() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 100
```

This particular failure also happened on https://github.com/dotnet/runtime/pull/46238 on windows.10.amd64.open.rt 

@sywhang looks like this is your test?

**Comment by danmosemsft** [comment]
https://github.com/dotnet/runtime/pull/46493

**Comment by sywhang** [comment]
Took a quick look at this and it seems like it's a product issue -- let me investigate and report back.
