### ISSUE TITLE
Half to Double/Float conversion is broken for subnormal values

### ISSUE THREAD

**Issue by ecorm** [dotnet/runtime#46515]
### Description

`Half` numbers with binary values between 0x0200 and 0x03FF are converted to approximately half their value when cast to `Single` and `Double`. 0x03FF corresponds to the largest positive subnormal number.

```c#
// largest subnormal, binary 0x03ff
Half h1 = (Half)0.000060975552;
Console.WriteLine("0x{0:X4}", h1.GetHashCode());
// Prints 3.0487776E-05, which is off by a factor of two
Console.WriteLine("{0:R}", (Single)h1);

// binary 0x0200
Half h2 = (Half)3.05E-05;
Console.WriteLine("0x{0:X4}", h2.GetHashCode());
// Prints 1.5258789E-05, which is off by a factor of two
Console.WriteLine("{0:R}", (Single)h2);

// binary 0x01FF
Half h3 = (Half)3.046E-05;
Console.WriteLine("0x{0:X4}", h3.GetHashCode());
// Prints 3.0457973E-05, which seems about right
Console.WriteLine("{0:R}", (Single)h3);

// binary 0x0400
Half h4 = (Half)6.104E-05;
Console.WriteLine("0x{0:X4}", h4.GetHashCode());
// Prints 6.1035156E-05, which seems about right
Console.WriteLine("{0:R}", (Single)h4);
```

### Configuration

.NET version: 5.0.101
OS: Linux 5.4.0-45-generic
Distro: Linux Mint 20
Architecture: x86_64

**Comment by ecorm** [comment]
There are only 65536 possible `Half` values. They should be all tested exhaustively. Is there a published unit test for `Half` that I could check out?

**Comment by EgorBo** [comment]
BTW, @tannergooding are there any plans on adding `vcvtps2ph/vcvtph2ps` for half->float/float->half` conversions?
I guess it should be an API proposal to add `Fp16` set of intrinsics?

**Comment by danmosemsft** [comment]
> @ecorm 

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/System/HalfTests.cs

(I just browsed for file names beginning with "Half")

Improvements welcome.

**Comment by ecorm** [comment]
@danmosemsft Thanks!

I managed to get the dotnet runtime test suite running and am in the process of adding `ExplicitConversion_x` test vectors for the normal/subnormal corner cases.

I figured out how to run only the `HalfTests`, but it's still pretty slow. Is there a way to get the test suite to run any faster? It seems to spend a lot of time setting things up. It takes around 30 seconds per run for me, which tests my patience when I'm doing trial and error stuff. :-)

I'll take a quick look at the `Half` conversion logic, but it'll likely remain beyond my understanding with the limited amount of time I can spend on this.

**Comment by ecorm** [comment]
Submitted PR that adds subnormal corner cases to unit test: https://github.com/dotnet/runtime/pull/46523

Note the eight commented-out lines that fail under `ExplicitConversion_ToSingle_TestData` and `ExplicitConversion_ToDouble_TestData`.

**Comment by danmosemsft** [comment]
> It takes around 30 seconds per run for me, 

I usually run tests on the command line and in the console it prints instructions for how to run the tests "directly" which is faster.

**Comment by pgovind** [comment]
Thanks for the tag @jeffhandley. I just approved #46536 to fix this issue.

**Comment by jeffhandley** [comment]
#46536 looks good to me too. @tannergooding called my attention to this asking if this would meet the servicing bar; I think it will.

**Comment by jeffhandley** [comment]
Thanks for reporting this and contributing the tests, @ecorm!
