### ISSUE TITLE
"The process '/usr/bin/dotnet' failed with exit code 249"... what does that exit code mean or how can I figure it out?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/runtime#46524]
I found this list of exit codes https://github.com/dotnet/runtime/blob/master/docs/design/features/host-error-codes.md  but it doesnt go up to 249.

**Comment by vitek-karas** [comment]
The `dotnet` executable is just a runner - it will exit with whatever exit code the managed application it runs returns from its Main. For example, if I have a console app `MagicalNumber` which has main like this:
```C#
static int Main()
{
    return 42;
}
```

And then run it:
```console
dotnet MagicalNumber.dll
```

That command will produce exit code `42`.

So the answer to your question depends on what managed application was it running? What is the command line which started this `dotnet`?

**Comment by StingyJack** [comment]
I actually dont remember for sure =/

I dont run `dotnet` commands for anything so it was probably VS2019 starting up some tool or utility like service fabric and trying to connect to an event collector and failing or something.  My VS activitylog stopped logging anything on 12/31, but I've been using it since then. Nothing in the event logs either, and thats enough traveling down this rabbit hole for me.

At least now I know what to look for now and will whip out ILSpy if necessary. Are there any rules or guidelines on exit codes for programs other than "0 = success, everything else is probably a failure"?

**Comment by vitek-karas** [comment]
Shells typically recognize `0` as success and everything else as failure. But I've also seen some cases where anything `>=0` is considered a success and anything `<0` is considered a failure. There are definitely no hard rules around this I'm aware of.
