### ISSUE TITLE
JsonSerializer throw an InvalidCastException when serializing an array of item with a custom converter

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#46522]
### Description

JsonSerializer throw an InvalidCastException when serialization a collection of items. The class has a custom JsonConverter that matches one of the interface implemented by the class.

Serializing an `SampleRepro[]` (`SampleRepro` implements the interface) throw an InvalidCastException.

````xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
````

````c#
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ConsoleApp25
{
    class Program
    {
        static void Main()
        {
            // OK
            Console.WriteLine(JsonSerializer.Serialize(new SampleRepro()));

            // Exception
            Console.WriteLine(JsonSerializer.Serialize(new SampleRepro[] { new SampleRepro() }));
        }
    }

    public interface IRepro<T>
    {
        T Value { get; }
    }

    [JsonConverter(typeof(ReproJsonConverter))]
    public class SampleRepro : IRepro<object>
    {
        public object Value => "";
    }

    public sealed class ReproJsonConverter : JsonConverter<IRepro<object>>
    {
        public override bool CanConvert(Type typeToConvert)
        {
            return typeof(IRepro<object>).IsAssignableFrom(typeToConvert);
        }

        public override IRepro<object> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => throw new NotSupportedException();

        public override void Write(Utf8JsonWriter writer, IRepro<object> value, JsonSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNullValue();
            }
            else
            {
                JsonSerializer.Serialize(writer, value.Value, options);
            }
        }
    }
}
````

````
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'ConsoleApp25.ReproJsonConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[ConsoleApp25.SampleRepro]'.
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.GetElementConverter(WriteStack& state)
   at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at ConsoleApp25.Program.Main() in C:\Users\mezia\source\repos\ConsoleApp25\ConsoleApp25\Program.cs:line 16
````

### Configuration

.NET 5.0.1

### Regression?

This is new code, I haven't tested with previous versions of System.Text.Json

### Other information

I managed to make it work using a `JsonConverterFactory` but I'm not sure this is needed or just a temporary workaround.

**Comment by huoyaoyuan** [comment]
The exception message tells the problem: you must use `JsonConverter<SampleRepro>`, not `JsonConverter<IRepro<object>>`.

A `JsonConverter<T>` must be associated with a concrete type. Only `JsonConverterFactory` can be used for a family of types.

**Comment by meziantou** [comment]
The way S.T.Json handle converters seems inconsistent:

- When serializing a single value, it works with `JsonConverter<IRepro<object>>`. => According to your comment, this shouldn't be the case?
- When serializing a collection, it throws an `InvalidCastException`. As a user, this exception seems like a bug in S.T.Json.
- When serializing a single value with a non-compatible converter (CanConvert returns false), it throws an explicit exception "System.InvalidOperationException: The converter specified on 'ConsoleApp25.SampleRepro' is not compatible with the type 'ConsoleApp25.SampleRepro'." => This seems perfectly valid.

Maybe S.T.Json should throw an `InvalidOperationException` in this case instead of an `InvalidCastException` to make it clear that the converter is not the right way to go. But this is inconsistent with the first case that works.

**Comment by huoyaoyuan** [comment]
> * When serializing a single value, it works with `JsonConverter<IRepro<object>>`.

It surprises me. I'd expect it not to work.

**Comment by meziantou** [comment]
> It surprises me. I'd expect it not to work.

You can run the code from the issue and check the result of the first serialization `Console.WriteLine(JsonSerializer.Serialize(new SampleRepro()));`. It seems to correctly calls the converter.

**Comment by eiriktsarpalis** [comment]
If anything, it is likely accidental that the first line happens to work. At the same time, the exception thrown in the second line is not very user friendly. We should consider adding checks that detect incompatible converter types early on and surface a relevant error message.

**Comment by eiriktsarpalis** [comment]
This is related to #55135.

**Comment by eiriktsarpalis** [comment]
See https://github.com/dotnet/runtime/issues/55135#issuecomment-889433874 for analysis of the issue and proposals on how to address this in the future.
