### ISSUE TITLE
varchar type not accepted

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#46545]
Hi,

I have a varchar field in my database and I am storing mobile number starting with leading zero

in my JSON I am using:

`public string mobile { get; set; }
`
but it is assuming the field is int and throwing an error failing to convert int to string

**Comment by danmosemsft** [comment]
Hello @jrahma unfortunately there isn't enough information here to help you. What data access API are you using? How are you integrating JSON with it?

What is the callstack of the exception?

A minimal repro, or something close, that you can paste in here would be helpful.

**Comment by danmosemsft** [comment]
Just guessing at the label for now.

**Comment by Clockwork-Muse** [comment]
Maybe it's trying to read the string as a number?

What are your Json serialization options, particularly [number handling.](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonnumberhandling?view=net-5.0).  Note there is specifically an option to treat string fields as numbers if they're "parseable"

**Comment by jrahma** [comment]
I am using the System.Text.Json

**Comment by danmosemsft** [comment]
@jrahma again, this is not actionable without more information. Can you please share a minimal example of code that reproduces your problem? And answer @Clockwork-Muse 's question?

**Comment by jrahma** [comment]
@danmosemsft what I mean is I have a mobile field which has values starting with zero like 0521112233, 0544466777, 072538766, etc and I want to be a varchar type on the database not int.

When I read the data into my app using System.Text.Json and with:

public string mobile { get; set; }

it will throw a int to string conversion error although my field type is not an int but the values are.

so the question is why is it considering 0521112233 as an int when I want it be string as per:

public string mobile { get; set; }

and then the same problem for the bit field which is 0 and 1 and I want it as true an false in my app, it will through an error if I try:

public bool is_admin { get; set; }

so I have to do a JsoonIgnore for every field which does not make sense.

**Comment by svick** [comment]
@jrahma What does the JSON contain? E.g. is it something like `"mobile": "0521112233"` or `"mobile": 0521112233` (note the missing quotes).

Also, can you change what JSON is produced by the database, or is that outside of your control? E.g. the expected way to represent boolean values in JSON is `false` and `true`, not `0` and `1`, which would explain why you're getting errors on those. Can you make the database produce sensible JSON (with strings for strings and booleans for booleans), or do you need to make System.Text.Json understand your problematic JSON?

**Comment by jrahma** [comment]
This is my output:

[{"user_id":1001,"user_uuid":"xxxxx-xxxxx-xxx-xxxx-xxxx","auth_token":"xxxxxx-xxxx-xxxx-xxxx-xxxxxx","first_name":"Jassim","second_name":"hmmm","third_name":"hmmmm","fourth_name":"hmmmm","last_name":"Rahma","email_address":"email@domain.com","date_of_birth":"1985-09-27","mobile":512345678,"communication_language":"EN","title_name":"Mr.","is_admin":0,"is_active":1,"is_member":1,"is_board_member":1,"is_founder":1,"first_time_signin":1,"is_investor":0,"is_startup":0,"birthday":2709}]

**Comment by Clockwork-Muse** [comment]
Your `mobile` field is an actual number field, not a 0-prepended string of digits.  You could be running into problems because the value has more digits than the type can handle (phone numbers in the US have 10 digits, which are more than an `int` can handle)

This isn't sufficient for us to reproduce an issue, though.  We need:
 - the input
 - the smallest piece of code that causes the error
 - the stack trace of the error

**Comment by jrahma** [comment]
the problem is, for example the user_id is an autoincrement int field but when I use:

echo json_encode($jsonData);

it will turn it into "string" so I will need to do:

public string user_id { get; set; }

not:

public int user_id { get; set; }

the same thing applies to all field including mobile

**Comment by jrahma** [comment]
so to get the user_id and other field as int I am using 

echo json_encode($jsonData, JSON_NUMERIC_CHECK);

but that is now causing the mobile (which is a string field in my database) to be converted to int and losing the leading zero

I am not having this problem when using the Newtonsoft's JSON

**Comment by Clockwork-Muse** [comment]
... that's not enough of a description.  We need actual runnable code to be able to tell what's happening.  For one thing, `echo` is not a syntax element in C#, which potentially makes that not relevant.

**Comment by danmosemsft** [comment]
@jrahma please reduce the problem down to a simple standalone program -- eg., create a new C# .NET Core console app in Visual Studio, and paste in code to get a repro, ideally with no dependencies, then simplify it, and paste the result here.

**Comment by GSPP** [comment]
@jrahma please note, that this issue tracker is not for solving programming problems. This issue tracker is for tracking the development of .NET. This means that bugs and feature requests should be posted here.

It sounds like stackoverflow.com would be a great fit for your request.
