### ISSUE TITLE
JIT: implement forward substitution

### ISSUE THREAD

**Issue by gafter** [dotnet/runtime#4655]
This is moved from https://github.com/dotnet/roslyn/issues/6542

Commenting out the first two lines of this for loop and uncommenting the third results in a 42% speedup:

```
int count = 0;
for (uint i = 0; i < 1000000000; ++i) {
    var isMultipleOf16 = i % 16 == 0;
    count += isMultipleOf16 ? 1 : 0;
    //count += i % 16 == 0 ? 1 : 0;
}
```

Behind the timing is vastly different assembly code: 13 vs. 7 instructions in the loop. The platform is Windows 7 running .NET 4.0 x64. Code optimization is enabled, and the test app was run outside VS2010.

[Repro project](https://github.com/breyed/PerfTest)
[StackOverflow question on this topic](http://stackoverflow.com/q/10369421/145173)

/cc @breyed

Note that this issue has also been demonstrated in VS2015.

category:cq
theme:forward-substitution
skill-level:expert
cost:extra-large

**Comment by BruceForstall** [comment]
@AndyAyersMS Can we close this and just keep https://github.com/dotnet/runtime/issues/6973?

**Comment by AndyAyersMS** [comment]
This one has more cross-links, so if we close it, maybe we should enumerate the related issues in the survivor?

**Comment by BruceForstall** [comment]
> This one has more cross-links, so if we close it, maybe we should enumerate the related issues in the survivor?

I generally assume that someone addressing such a big work item will look at the linked items, even if closed.
