### ISSUE TITLE
Exception.StackTrace missing the peek level in C#

### ISSUE THREAD

**Issue by isolin** [dotnet/runtime#46570]
After holidays I started to notice strange inconsistent behavior when an exception gets thrown in C#, that is within the `catch` block. When I append 'Exception.StackTrace' to a `string`, also when I evaluate it in the debug console, it skips the line where it occurred. The first line that gets reported is one level above in the stack. However, when I hover with the mouse over the variable containing the exception, the string correctly starts with the actual position of the error followed by the rest of the stack.

Such incorrect behavior makes debugging very difficult, since the placement of breakpoints gets very inaccurate. I am not aware of changing anything that would result in such output and I also do not remember noticing this ever before. Since yesterday I experience this problem at each exception that gets caught.

Mouse hover in the editor (correct string):
```
at SomeClass.SomeRoutine(UInt32 someArgument, String someOtherArg) in /home/user/Project/SomeFile.cs:line 407\n
at OtherClass.Method[T](T shape, Boolean ignoreDeforms) in /home/user/Project/OtherFile.cs:line 660\n
at OtherClass.OtherMethod[T](List`1 entities, Boolean ignoreDeforms, String prefix) in /home/user/Project/OtherFile.cs:line 647\n ...
```

Exception.StackTrace missing the stack peek (incorrect string):
```
at OtherClass.Method[T](T shape, Boolean ignoreDeforms) in /home/user/Project/OtherFile.cs:line 660\n
at OtherClass.OtherMethod[T](List`1 entities, Boolean ignoreDeforms, String prefix) in /home/user/Project/OtherFile.cs:line 647\n ...
```
I am using VS Code and .NET Core:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.404
 Commit:    470f6754b3

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.404/

Host (useful for support):
  Version: 3.1.10
  Commit:  1721e39439

.NET Core SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by benaadams** [comment]
Do you have `[MethodImpl(MethodImplOptions.AggressiveInlining)]` on `SomeClass.SomeRoutine`?

**Comment by isolin** [comment]
True, I do. I use it often for short helper methods, but never encountered this issue before. Was there any recent change related to this, or did I just miss that it always worked like that?

**Comment by jkotas** [comment]
It always worked like that.

**Comment by benaadams** [comment]
> Was there any recent change related to this, or did I just miss that it always worked like that?

If the method inlines it has never shown up in the stacktrace; there was a change so any method marked as `AggressiveInlining` also doesn't show up in the stacktrace; this was for tiered compilation as Tier0 doesn't do any inlines at all; so to maintain some coherence between Tier0 and Tier1 any method marked as `AggressiveInlining` is dropped from the stacktace `.ToString()`

**Comment by isolin** [comment]
Hm ok, I see.  Somehow I thought the inlining happes only in release, but that is now obviously not the case.

Is there a better way to see the aggressively inlined methods in the stack trace than decorating them like this?

```
#if !DEBUG
[MethodImpl(MethodImplOptions.AggressiveInlining)]
#endif
```

**Comment by benaadams** [comment]
Define
```csharp
namespace System.Runtime.CompilerServices
{
    internal class InliningPolicy
    {
#if DEBUG
        public const MethodImplOptions InlineAtRelease = MethodImplOptions.NoInlining;
#else
        public const MethodImplOptions InlineAtRelease = MethodImplOptions.AggressiveInlining;
#endif
    }
}
```

Then you can use
```csharp
class SomeClass
{
    [MethodImpl(InliningPolicy.InlineAtRelease)]
    void SomeRoutine() { }
}
```

**Comment by isolin** [comment]
Nice, thank you! +1:
