### ISSUE TITLE
The CultureInfo named "/" might stall the dotnet process on macOS/Linux

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#46577]
### Description

Running the following code completely stalls the dotnet process:
```csharp
using System;
using System.Globalization;

var cultureInfo = CultureInfo.GetCultureInfo("/");
Console.WriteLine($"cultureInfo.Name = '{cultureInfo.Name}'");
Console.WriteLine($"cultureInfo.NativeName = '{cultureInfo.NativeName}'");
Console.WriteLine("DONE");
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

The line `cultureInfo.Name = '/'` is printed but the line `cultureInfo.NativeName = …` is never written to the console and the process is stalled. When breaking in the debugger we can see the following stack trace:

```
[Native frame]
CultureData.IcuGetLocaleInfo()
CultureData.GetLocaleInfoCore()
CultureData.get_NativeLanguageName()
CultureData.get_NativeName()
CultureInfo.get_NativeName()
```

The native frame corresponds to the call to [Interop.Globalization.GetLocaleInfoString](https://github.com/dotnet/runtime/blob/v5.0.1/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Icu.cs#L71):
```csharp
bool result = Interop.Globalization.GetLocaleInfoString(localeName, (uint)type, buffer, ICU_ULOC_KEYWORD_AND_VALUES_CAPACITY);
```

### Configuration

* Which version of .NET is the code running on?
5.0.1
* What OS and version, and what distro if applicable?
macOS 10.15.6
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
It's probably specific to ICU-based configuration, i.e macOS and Linux.

### Other information

On Windows, the culture `/` is not supported, a `CultureNotFoundException` is thrown. Since [.NET 5.0 and later versions use ICU libraries for globalization functionality](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) I was surprised that the behaviour differs between macOS and Windows when accessing the culture named `/`.

**Comment by am11** [comment]
SOS' dumpstack suggests that is it stuck in libicucore's `ures_getByKeyWithFallback` function:

```gdb
(lldb) dumpstack
OS Thread Id: 0x7005f8 (1)
TEB information is not available so a stack size of 0xFFFF is assumed
Current frame: libsystem_platform.dylib!_platform_strchr
Child-SP         RetAddr          Caller, Callee
00007FFEEFBFDAC0 00007fff6851ed96 libicucore.A.dylib!___lldb_unnamed_symbol1129$$libicucore.A.dylib + 0xb1, calling libicucore.A.dylib!strchr
00007FFEEFBFDB20 00007fff6844c4d5 libicucore.A.dylib!ures_getByKeyWithFallback + 0x2da, calling libicucore.A.dylib!___lldb_unnamed_symbol1129$$libicucore.A.dylib
00007FFEEFBFDC00 00007fff6844c6e8 libicucore.A.dylib!ures_getStringByKeyWithFallback + 0x78, calling libicucore.A.dylib!ures_getByKeyWithFallback
00007FFEEFBFDC10 00007fff6844c3be libicucore.A.dylib!ures_getByKeyWithFallback + 0x1c3, calling libicucore.A.dylib!___lldb_unnamed_symbol1090$$libicucore.A.dylib
00007FFEEFBFDD10 00007fff6844aef0 libicucore.A.dylib!uloc_getTableStringWithFallback + 0x1d2, calling libicucore.A.dylib!ures_getStringByKeyWithFallback
00007FFEEFBFDFC0 00007fff684a8b80 libicucore.A.dylib!___lldb_unnamed_symbol144$$libicucore.A.dylib + 0x71, calling libicucore.A.dylib!uloc_getTableStringWithFallback
00007FFEEFBFE020 00007fff6844acd3 libicucore.A.dylib!uloc_getDisplayLanguage + 0xb4, calling libicucore.A.dylib!___lldb_unnamed_symbol144$$libicucore.A.dylib
00007FFEEFBFE040 00007fff6844ac8f libicucore.A.dylib!uloc_getDisplayLanguage + 0x70, calling libicucore.A.dylib!uloc_getLanguage
00007FFEEFBFE060 0000000102834629 libcoreclr.dylib!LeaveCriticalSection + 0x19, calling libcoreclr.dylib!pthread_getspecific
00007FFEEFBFE0C0 0000000102904bf5 libcoreclr.dylib!MethodDesc::GetOrCreatePrecode() + 0x3a5, calling libcoreclr.dylib!Precode::GetMethodDesc(int)
00007FFEEFBFE0D0 00000001028d7fd3 libcoreclr.dylib!HashMap::LookupValue(unsigned long, unsigned long) + 0x43
00007FFEEFBFE100 00000001028d7474 libcoreclr.dylib!HashMap::InsertValue(unsigned long, unsigned long) + 0x24
00007FFEEFBFE110 0000000102834629 libcoreclr.dylib!LeaveCriticalSection + 0x19, calling libcoreclr.dylib!pthread_getspecific
00007FFEEFBFE130 00000001028a10ae libcoreclr.dylib!CrstBase::Leave() + 0xe, calling libcoreclr.dylib!LeaveCriticalSection
00007FFEEFBFE150 00000001029746e9 libcoreclr.dylib!ReadyToRunInfo::SetMethodDescForEntryPointInNativeImage(unsigned long, MethodDesc*) + 0x69, calling libcoreclr.dylib!CrstBase::Leave()
00007FFEEFBFE190 00007fff68507dea libicucore.A.dylib!___lldb_unnamed_symbol951$$libicucore.A.dylib + 0xc6, calling libicucore.A.dylib!uprv_asciitolower
00007FFEEFBFE200 00007fff6844a57c libicucore.A.dylib!uloc_getLanguage + 0x44, calling libicucore.A.dylib!___lldb_unnamed_symbol951$$libicucore.A.dylib
00007FFEEFBFE230 0000000102c311d2 libcoreclr.dylib!GetLocale + 0x112
00007FFEEFBFE310 0000000102c32bae libcoreclr.dylib!GlobalizationNative_GetLocaleInfoString + 0x78e
00007FFEEFBFE340 000000010289241d libcoreclr.dylib!CodeVersionManager::PublishVersionableCodeIfNecessary(MethodDesc*, CallerGCMode, bool*, bool*) + 0x65d, calling libcoreclr.dylib!TieredCompilationManager::HandleCallCountingForFirstCall(MethodDesc*)
00007FFEEFBFE360 0000000102907119 libcoreclr.dylib!MethodDesc::WalkValueTypeParameters(MethodTable*, void (*)(Module*, unsigned int, Module*, unsigned int, SigParser const*, SigTypeContext*, void*), void*) + 0x389, calling libcoreclr.dylib!SigParser::SkipExactlyOne()
00007FFEEFBFE370 0000000102924d5d libcoreclr.dylib!Precode::GetMethodDesc(int) + 0x5d, calling libcoreclr.dylib!FixupPrecode::GetMethodDesc()
00007FFEEFBFE390 0000000102904ca9 libcoreclr.dylib!MethodDesc::GetTemporaryEntryPoint() + 0x79, calling libcoreclr.dylib!Precode::GetMethodDesc(int)
00007FFEEFBFE3D0 0000000102925f19 libcoreclr.dylib!MethodDesc::DoBackpatch(MethodTable*, MethodTable*, int) + 0x719, calling libcoreclr.dylib!CrstBase::CrstAndForbidSuspendForDebuggerHolder::~CrstAndForbidSuspendForDebuggerHolder()
00007FFEEFBFE4A0 00000001190b2164 (MethodDesc 000000011978c0f0 + 0x74 Interop+Globalization.GetLocaleInfoString(System.String, UInt32, Char*, Int32))
00007FFEEFBFE4D8 00000001190b2152 (MethodDesc 000000011978c0f0 + 0x62 Interop+Globalization.GetLocaleInfoString(System.String, UInt32, Char*, Int32)), calling libcoreclr.dylib!JIT_PInvokeBegin
00007FFEEFBFE4F0 0000000102821f1d libcoreclr.dylib!SetLastError + 0xd, calling libcoreclr.dylib!__error
00007FFEEFBFE560 00000001191a04b5 (MethodDesc 000000011978b2b8 + 0x95 System.Globalization.CultureData.IcuGetLocaleInfo(System.String, LocaleStringData)), calling 0000000119676f40 (stub for Interop+Globalization.GetLocaleInfoString(System.String, UInt32, Char*, Int32))
00007FFEEFBFE5B0 0000000102b3203b libcoreclr.dylib!ThePreStub + 0x5c, calling libcoreclr.dylib!PreStubWorker
00007FFEEFBFE660 00000001191a0233 (MethodDesc 000000011978b228 + 0x33 System.Globalization.CultureData.GetLocaleInfoCore(LocaleStringData)), calling 0000000119980c80
00007FFEEFBFE680 000000011919e63e (MethodDesc 000000011978aaa0 + 0x1e System.Globalization.CultureData.get_NativeLanguageName()), calling 0000000119980c68
00007FFEEFBFE6A0 000000011919e351 (MethodDesc 000000011978a9f8 + 0x41 System.Globalization.CultureData.get_NativeName()), calling 0000000118d12fea
00007FFEEFBFE6D0 00000001191a1ddd (MethodDesc 0000000119787338 + 0xd System.Globalization.CultureInfo.get_NativeName()), calling 0000000118d12fea
00007FFEEFBFE6E0 0000000119676288 (MethodDesc 0000000119714ec0 + 0xc8 Program.Main())
```

**Comment by am11** [comment]
Debugged it a bit on Ubuntu, I think the upstream fix is to add an `else` case at https://github.com/unicode-org/icu/blob/a84fdd0e903fb20acd93ed186a0da4c0c071a0e6/icu4c/source/common/uresbund.cpp#L1911

```diff
                            } else {
                              break;
                            }
                        }
+                       else if (res == RES_BOGUS) {
+                         break;
+                       }
                    } while(*myPath); /* Continue until the whole path is consumed */
```
because in `res_findResource`, we are hitting this condition https://github.com/unicode-org/icu/blob/a84fdd0e903fb20acd93ed186a0da4c0c071a0e6/icu4c/source/common/uresdata.cpp#L948 as value of `RES_PATH_SEPARATOR` happen to be `/` and `*path` is not altering/advancing which caller is expecting, hence the infinite loop.

For runtime, I think a workaround could be to prevent `GetLocale` from calling `uloc_getLanguage` when value of `localeNameTemp` is `/` https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L78

cc @jefgen

**Comment by tarekgh** [comment]
@am11 thanks for the investigation. 

> For runtime, I think a workaround could be to prevent GetLocale from calling uloc_getLanguage when value of localeNameTemp is /

I think we can in the loop https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L49 check for `/` and fail the call if it is there. `/` is not allowed character in the locale names. Here is the the BCP47 specs https://tools.ietf.org/html/bcp47.

will you submit a PR? please let me know so I can do it if you are busy to do it.

@jefgen could you please track this from your side to fix it in the ICU?

We may consider servicing the fix to 5.0 release.

**Comment by am11** [comment]
@tarekgh, I can try to add a test case and early bail for 0x2F. Will submit a PR shortly.

**Comment by 0xced** [comment]
I framed this issue around the locale named `/` because I thought it was an interesting corner case but maybe the real question is: should .NET create `CultureInfo` with _invalid_ names? The CultureInfo documentation [(Culture names and identifiers)](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo#culture-names-and-identifiers) states:

> The CultureInfo class specifies a unique name for each culture, based on RFC 4646. The **name is a combination of an ISO 639 two-letter lowercase culture code** associated with a language and an ISO 3166 two-letter uppercase subculture code associated with a country or region. In addition, for apps that target .NET Framework 4 or later and are running under Windows 10 or later, culture names that correspond to **valid BCP-47 language tags** are supported.

As such, `/` or basically any other single ASCII character is **not** valid and a `CultureNotFoundException` should probably be thrown instead of returning a bogus `CultureInfo` instance. This is by the way what happens on Windows.

The blog post [announcing .NET 5](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/#support-for-icu-on-windows) said:

> We use the ICU library for Unicode and globalization support, previously only on Linux and macOS. We are now using this same library on Windows 10. This change makes the behavior of globalization APIs such as culture-specific string comparison **consistent between Windows 10, macOS, and Linux**. We also use ICU with Blazor WebAssembly.

I think it would be natural that the behaviour of creating `CultureInfo` instances also be consistent across all supported platforms, especially for bogus culture names.

**Comment by am11** [comment]
On Windows, it seems that icu4c is already patched (I couldn't find any special handling on runtime side). I tested with ICU's master branch on linux and macOS, and the problem persists. BTW the fix is ready, and it does throw `CultureNotFoundException` with this handling.

> should .NET create CultureInfo with invalid names?

runtime passes the input to ICU, which decides whether the name is valid or invalid. This corner case `/` has surfaced a bug in ICU. Normally ICU returns an error code, which turns into `CultureNotFoundException`.

**Comment by tarekgh** [comment]
@0xced I don't think the framework create any cultures with bogus names. What we do is we pass the user input locale name to ICU and ICU validate this name should fail with any bogus name. The `/` is special case here because ICU used this character as resource separator as @am11 indicated in his analysis.

**Comment by tarekgh** [comment]
> On Windows, it seems that icu4c is already patched (I couldn't find any special handling on runtime side).

Yup, I tried that too and we are successfully throwing `CultureNotFoundException` exception.

**Comment by 0xced** [comment]
> I don't think the framework create any cultures with bogus names.

Let me be more explicit about what I meant. On Windows, calling `CultureInfo.GetCulture(name)` throws `CultureNotFoundException` for any string with a single ASCII character, e.g. `CultureInfo.GetCulture("{")` and `CultureInfo.GetCulture("x")` both throw `CultureNotFoundException`. On macOS, a `CultureInfo` with name `{` and `x` are respectively returned.

I think `CultureInfo.GetCulture("{")` should also throw `CultureNotFoundException` on macOS. That's what I called a culture with a bogus name and I don't think it makes sense to have a culture named `{`. Anyway `{` is not even valid according to [BCP 47](https://tools.ietf.org/html/bcp47).

I don't know why `CultureNotFoundException` is thrown on Windows but not macOS when both are using ICU under the hood. Probably because macOS and Windows don't have the same version of ICU and/or ICU is packaged differently?

**Comment by am11** [comment]
Actually it hangs with any name that starts with `/`, e.g. `/foo`, but does not hang when `/` is in the middle or end of multi-character input. Also, `{foo` should probably throw the same exception if the strict validation is performed consistently cross-platform, ideally by ICU, or by the runtime.

**Comment by 0xced** [comment]
Well, that's the problem, `{foo` and many other bogus culture names don't throw any exception on macOS. Maybe I should open another issue about that?

**Comment by jefgen** [comment]
> @jefgen could you please track this from your side to fix it in the ICU?

Thanks for tagging me on this issue!

FWIW, I can reproduce this issue on Windows as well when calling into ICU directly with the following:

```C++
    UErrorCode status = U_ZERO_ERROR;
    const char* localeNameTemp = "/"; // RES_PATH_SEPARATOR
    char language[ULOC_LANG_CAPACITY];
    uloc_getDisplayLanguage(localeNameTemp, localeNameTemp, NULL, 0, &status);
```

Note that I actually can't repro this issue when calling `uloc_getLanguage` on either Windows or Linux. Rather, it only occurs when calling `uloc_getDisplayLanguage`, which I think matches the stack-trace in the comment here: https://github.com/dotnet/runtime/issues/46577#issuecomment-754677300

As for the `CultureNotFoundException` that is being thrown by .NET on Windows -- it must be coming from some other code path. Perhaps there is more validation being done on Windows? I'm not really sure though.

I filed a bug for tracking on the ICU side here: https://unicode-org.atlassian.net/browse/ICU-21449
As it seems like it should be giving an error back, rather than getting stuck in an infinite loop.
I will add more details to the bug later after doing some more testing later.

**Comment by tarekgh** [comment]
I found out when running on Windows we do the call https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Windows.cs#L51 which does validate the culture name and we throw after that. This is why we couldn't repro the issues on Windows. But looks to me ICU still have the problem that is allow using locale names that are not conforming to BCP47 as indicated by 0xced replies.

**Comment by am11** [comment]
@jefgen, I applied that patch (https://github.com/dotnet/runtime/issues/46577#issuecomment-754807183) on linux, compiled libicuuc.so and tested the app with `LD_LIBRARY_PATH=/projects/icu/icu4c-build/lib dotnet gh-46577.dll`, it worked without the hang.

@tarekgh, would it make sense to skip `GetLocaleInfoEx` call when ICU is selected on Windows? That will make the user-experience consistent across platforms. We can then pursue ICU's lack of BCP47 compliance in case of `uloc_getDisplayLanguage` separately.

**Comment by tarekgh** [comment]
> would it make sense to skip GetLocaleInfoEx call when ICU is selected on Windows?

I think we can do that if we ensure ICU behavior. Currently this call is used to normalize the culture name. So we need to ensure this is still happening in NLS cases and also we want ensure ICU is normalizing the names properly which looks it does.

**Comment by jefgen** [comment]
> @jefgen, I applied that patch ([#46577 (comment)](https://github.com/dotnet/runtime/issues/46577#issuecomment-754807183)) on linux, compiled libicuuc.so and tested the app with `LD_LIBRARY_PATH=/projects/icu/icu4c-build/lib dotnet gh-46577.dll`, it worked without the hang.

Thanks for testing out the change! I also tried the change out in ICU, and all the existing ICU tests pass with the change.

> We can then pursue ICU's lack of BCP47 compliance in case of `uloc_getDisplayLanguage` separately.

Well one thing though is that ICU doesn't always use BCP47 names, as it also supports "ICU format locale IDs", which can contain things like "@", which BCP47 doesn't allow. (For example: `th_TH@calendar=buddhist`).

However, looking at the ICU User Guide page here: https://unicode-org.github.io/icu/userguide/locale/#canonicalization

> ICU works with ICU format locale IDs. These are strings that obey the following character set and syntax restrictions:
> 1. The only permitted characters are ASCII letters, hyphen (‘-‘), underscore (‘_’), at-sign (‘@’), equals sign (‘=’), and semicolon (‘;’).

I'm wondering if perhaps the input locale IDs should have some basic validation done on them before doing anything else.

Perhaps input locale with any "invalid" characters should be rejected outright -- I added this to the ICU bug, so it could be discussed there more.

**Comment by tarekgh** [comment]
> Perhaps input locale with any "invalid" characters should be rejected outright -- I added this to the ICU bug, so it could be discussed there more.

It is not a valid characters but some things need to be validated. e.g. names like the following would be invalid: `x`, `_`, `-`, `en-`,...etc.

**Comment by tarekgh** [comment]
I am reopening this to track the locale name validation issue so we'll be complete with the solution.

**Comment by safern** [comment]
@tarekgh we also need to port the workaround to avoid the hang when locale == "/" on Unix, right?

**Comment by tarekgh** [comment]
@safern would be good to check with the tactics first to see if this meet the bar. As you know this behavior existed since net core 1. but I am inclining to port it to the servicing. 
Can you help with that? please let me know if you are busy so I can do it myself.

**Comment by safern** [comment]
> Can you help with that? please let me know if you are busy so I can do it myself.

Yeah I can help with that.

**Comment by am11** [comment]
> Well one thing though is that ICU doesn't always use BCP47 names, as it also supports "ICU format locale IDs", which can contain things like "@", which BCP47 doesn't allow. (For example: `th_TH@calendar=buddhist`).

@tarekgh, @jeffbog, should we also support union of allowed characters by BCP47 and "ICU format locale IDs", or should the validation in .NET runtime strictly follow BCP47?

**Comment by am11** [comment]
> to avoid the hang when locale == "/" on Unix to 5.0

@safern, the hang is basically for each locale.StartsWith("/"). e.g. `GetCultureInfo("/foo")` also keeps that ICU do-while loop spinning forever.

**Comment by danmosemsft** [comment]
With respect to servicing, they will need to understand whether this is blocking customers, whether it has widespread impact and whether it happens in real apps as opposed to a synthetic situation.

**Comment by tarekgh** [comment]
> should we also support union of allowed characters by BCP47 and "ICU format locale IDs", or should the validation in .NET runtime strictly follow BCP47?

Internally we have the field _sRealName which should have the pure BCP47 name.

https://github.com/dotnet/runtime/blob/cc1198a1de867915ef0c604e4426e708c0b9c9b2/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Unix.cs#L68

This is what we can validate.

**Comment by am11** [comment]
> This is what we can validate against the BCP47 specs.

I am writing a BCP47 validator (in managed code) with these assumptions:
1. we cannot use regex in System.Private.CoreLib, so we need to write it in iterative manner (preserving spec terminology in private method names to keep correlation with the spec).
2. when `GetCultureInfo()`, `new CultureInfo(string)` or other ctors are called, perform an upfront validation and throw CNFE.

Is this a correct approach? (although I have kept it as primitive as possible but) How worry should we be about the performance impact?

**Comment by tarekgh** [comment]
@am11 that sounds good to me. We just want to ensure we iterate one time on the name and doing all needed operations (e.g. validation and any translation we are currently doing). In other word, we need to look at 

https://github.com/dotnet/runtime/blob/cc1198a1de867915ef0c604e4426e708c0b9c9b2/src/libraries/System.Private.CoreLib/src/System/Globalization/CultureData.Unix.cs#L16

and 

https://github.com/dotnet/runtime/blob/cc1198a1de867915ef0c604e4426e708c0b9c9b2/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L30

and try to encapsulate the work in one place if possible. I agree we can do the work in the managed side in the `InitCultureDataCore` method.

Thanks again for helping with that.

**Comment by am11** [comment]
> We just want to ensure we iterate one time on the name

If we implement the complete spec, I think it is not possible to do it in O(1). This part:

```
  langtag       = language
                 ["-" script]
                 ["-" region]
                 *("-" variant)
                 *("-" extension)
                 ["-" privateuse]
```

alone is allowing multiple sub-parts (variant, extension) to repeat indefinitely. The DFA of this spec is quite jumpy https://gist.github.com/am11/39cd2e855468bb787edd6cb20da71460.

If we want to implement only a portion of this spec to keep it O(1) scan of input, unfortunately I cannot determine which rules from the spec we can safely skip in the context of `InitCultureDataCore()`.

**Comment by tarekgh** [comment]
@am11 let's do basic validation for now which should cover the majority of invalid cases. Something like what we had in the Full Framework https://referencesource.microsoft.com/#mscorlib/system/globalization/cultureinfo.cs,666

**Comment by tarekgh** [comment]
I forgot to say to validate the culture length too.

**Comment by am11** [comment]
The spec on a high-level is:

```c#
static bool IsValid(ReadOnlySpan<char> subject) =>
    IsGrandfathered(subject) | IsLangTag(subject) | IsPrivateUse(subject);
```

then each of those constituents have sub-sub parts having their own length requirements and repetition count (some parts can also repeat N times; where N is called out by spec, others can repeat indefinitely).

`IsGrandfathered(s)` consists of `IsIrregular(s)` then `IsRegular(s)`. The very first rule of `IsIrregular(s)` is a hard-coded `en-GB-oed`, which will be violated by:

> Cannot have `-` or `_ `followed by `-` or '_'

**Comment by tarekgh** [comment]
@am11 I meant by this rule is you are not allowed to have `--` or `__` or `_-` or `-_`.  does this violate the rule?

**Comment by 0xced** [comment]
> others can repeat indefinitely

I don't think they can repeat indefinitely, the maximum length for a locale is `ULOC_FULLNAME_CAPACITY` which is [157 bytes](https://github.com/dotnet/runtime/blob/f6754aec0c9f2fee6be86b009c618520ee6f1357/src/libraries/Native/Unix/System.Globalization.Native/pal_locale.c#L36) (including the terminating NULL and all keywords). So you could check for that length upfront.

**Comment by am11** [comment]
No it does not, I mixed it up. It is not allowed by BCP47 spec either (_ is not allowed either).

**Comment by am11** [comment]
> I don't think they can repeat indefinitely

I meant in terms of Big-O complexity, they can repeat and we need to start over for next possible (subsequent) pattern.

**Comment by am11** [comment]
For example `hy-Latn-IT-arevela` is valid based on Appendix A, our implementation and some reference implementations, but `hy-Latn-IT-arevelafoo`  is invalid (due to the length requirement of this particular segment in Language-Script-Region-Variant), but we are returning true (due to performance considerations).

**Comment by tarekgh** [comment]
@am11 

> For example hy-Latn-IT-arevela is valid based on Appendix A, our implementation and some reference implementations, but hy-Latn-IT-arevelafoo is invalid (due to the length requirement of this particular segment in Language-Script-Region-Variant), but we are returning true (due to performance considerations).

That is fine.
