### ISSUE TITLE
Add Tags and Baggage to LogScope using ActivityTrackingOptions

### ISSUE THREAD

**Issue by msallin** [dotnet/runtime#46571]
## Background and Motivation

Since .NET 5 the `LoggerFactoryScopeProvider` can be configured using the `ActivityTrackingOptions`, to add the SpanId, TraceId, ParentId, TraceStateString and TraceFlags to the scope. The SpanId, TraceId and ParentId are added by default when using `Host.CreateDefaultBuilder()`.

In our use case, we implement a own `ConsoleFormatter` which writes the log lines as key-value-pairs, to be able to easy search them with Splunk. We want to add the SpandId, TraceId, ParentId and all items from baggage and tags to each log line.
`2021-55-05 08:01:01.075 level=INFO eventName=RequestFinished eventId=2 sourceContext="Microsoft.AspNetCoreHosting.Diagnostics" message="Request finished HTTP/1.1 GET http://localhost/ - - - 200- - 101.8717ms" ElapsedMilliseconds="101.8717" StatusCode="200" ContentType="" ContentLength="" Protocol="HTTP/1.1" Method="GET" Scheme="http" Host="localhost" PathBase="" Path="/" QueryString="" SpanId="976b6fa436d88a4e" TraceId="a23f2582c9522c42bce68662015ed2f1" ParentId="0000000000000000" RequestId="0HM5HAUAVSI9J" RequestPath="/"`

*added some more text to the proposal code by @tarekgh*

## Proposed API

```diff
using System;

namespace Microsoft.Extensions.Logging
{
    [Flags]
    public enum ActivityTrackingOptions
    {
        None        = 0x0000,
        SpanId      = 0x0001,
        TraceId     = 0x0002,
        ParentId    = 0x0004,
        TraceState  = 0x0008,
        TraceFlags  = 0x0010,

+       Tags        = 0x0020,
+       Baggage     = 0x0040,
    }
}
```

## Usage Examples

``` diff
namespace Microsoft.Extensions.Hosting
{
    public static class Host
    {
        public static IHostBuilder CreateDefaultBuilder(string[] args)
        {
            var builder = new HostBuilder();
 
            builder.UseContentRoot(Directory.GetCurrentDirectory());

            builder.ConfigureAppConfiguration((hostingContext, config) =>
            {
                //...
            })
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                logging.AddConsole();

                logging.Configure(options =>
                {
                    options.ActivityTrackingOptions = ActivityTrackingOptions.SpanId
                                                        | ActivityTrackingOptions.TraceId
                                                        | ActivityTrackingOptions.ParentId
+                                                        | ActivityTrackingOptions.Baggage
+                                                        | ActivityTrackingOptions.Tags;
                });
 
            })

            return builder;
        }
    }
}
```

## Alternative Designs

- Make it possible to subclass `LoggerFactoryScopeProvider` and add the behavior this way.
- Use another Enum because `ActivityTrackingOptions` currently represents only parts of the W3C spec

## Risks

No risks.

**Comment by msallin** [comment]
area label: area-Extensions-Logging

**Comment by msallin** [comment]
Releated issues:

- https://github.com/dotnet/runtime/issues/35209
- https://github.com/dotnet/runtime/issues/34305

**Comment by msallin** [comment]
CC: @tarekgh @shirhatti

**Comment by tarekgh** [comment]
@msallin 

Tags now are string-object pairs and not string-string. What you suggest in formatting the tags? just call `ToString` on the value? or need to provide formatter for that?

CC @noahfalk @maryamariyan

**Comment by tarekgh** [comment]
CC @davidfowl

**Comment by msallin** [comment]
In our use case we attach only strings as tags. Thus, its fine to just use `ToString`. Using a formatter would be useful if one adds objects which one does not have control. Else one could still overwrite `ToString` .

**Comment by tarekgh** [comment]
@davidfowl @shirhatti the proposal looks reasonable to me. Do you have any concern bout it before we move forward?

**Comment by davidfowl** [comment]
As long as it's not on by default, looks good.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace Microsoft.Extensions.Logging
{
    public partial enum ActivityTrackingOptions
    {
        Tags        = 0x0020,
        Baggage     = 0x0040,
    }
}
```

**Comment by msallin** [comment]
I would love to contribute this tiny part to .NET
Let me know when/if you are ready to accept a PR.

**Comment by tarekgh** [comment]
@msallin go ahead and submit the PR and tag me there. Thanks for willing to help with that.

**Comment by tarekgh** [comment]
@msallin please let me know if you need any help or have any question. Thanks!

**Comment by tarekgh** [comment]
Fixed by https://github.com/dotnet/runtime/pull/48722
