### ISSUE TITLE
System.Memory (5.0.0)

### ISSUE THREAD

**Issue by JeffAshton** [dotnet/runtime#46583]
Are there plans to release a 5.0.0 version of [System.Memory](https://www.nuget.org/packages/System.Memory/) which depends on the 5.0.0 version of [System.Runtime.CompilerServices.Unsafe](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/)?

Packages like [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/) are inherently depending on 2 different major versions of the `System.Runtime.CompilerServices.Unsafe` package.

```
System.Diagnostics.DiagnosticSource (5.0.0)
  -> System.Memory (4.5.4)
      -> System.Runtime.CompilerServices.Unsafe (4.5.3)
  -> System.Runtime.CompilerServices.Unsafe (5.0.0)
```

**Comment by carlossanlop** [comment]
@ericstj @safern would you mind helping answer this question?

**Comment by ericstj** [comment]
cc @ViktorHofer 
The package is no longer built since the 2.1 release.  It's a non-goal to rev the entire package graph when components update.  The reality of using NuGet packages on .NETFramework is that you need bindingRedirects to address these types of issues.
