### ISSUE TITLE
The purpose of EmailAddressAttribute?

### ISSUE THREAD

**Issue by msmolka** [dotnet/runtime#46580]
For security reasons regex validation was removed from this attribute. So it is now not doing any reasonable validation. It can cause big misleading when users annotate their models with this attribute to makes sure valid email address is provided and then be hit by email provider/smtp/imap senders that invalid email address was provided.

I know for backward compatibility it is required, but shouldn't it at least be marked as obsolete since in most cases not working. It does not validate anything. Simple space inside email added by mistake, passes validation. 

I can understand more strict validation than RFC allowance, but validation that can easy pass and cause automation places not work is in my opinion bad practice. On entry user can fix email address, later when it will fail in use, it cannot be fixed.

As a side note class is sealed so I even cannot override it to include my own validation. So to make Email validation works I need to create my totally own attribute.

**Comment by Joe4evr** [comment]
See: https://github.com/dotnet/runtime/issues/45670#issuecomment-739934920
And about the attribute types being sealed: https://github.com/dotnet/runtime/issues/14735

**Comment by msmolka** [comment]
I understand, that validate address that won't be rejected by email server is "not possible" but:
I would at least expect that email address validated by EmailAddressAttribute is not throwing FormatException in `System.Net.Mail.MailAddressParser` class. I would expect that code is consistent against whole .NET. So validated by one part can be accepted by other part of framework. 

And as I said this code accepts "john. do@example. com" which will throw `System.FormatException` in `System.Net.Mai` namespace

**Comment by ajcvickers** [comment]
Closing as duplicate of #45670. As stated there, the current implementation is by design and not something we plan to change.
