### ISSUE TITLE
X.509 chain building throws on macOS with policy constraint violations

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#46585]
Another chain status we aren't handling for macOS is a "PolicyConstraints", or when a certificate chain violates the policy as defined in 2.5.29.36.

Found this one by looking for it, it is not new in Big Sur or started running in to it.

Need to research how Windows / Linux react to this situation.

**Comment by vcsjones** [comment]
OpenSSL won't do anything unless we specify `X509_V_FLAG_POLICY_CHECK`. Depending on what Windows does:

1. If Windows also enforces policy checks, then:
    1.  make macOS report it as Windows does
    2. Enable it for OpenSSL
2. If Windows does not enforce it, then:
    1. Ignore it for macOS

**Comment by vcsjones** [comment]
Meh. Windows breaks down policy violations to `NoIssuanceChainPolicy`, `InvalidPolicyConstraints`, etc depending on the scenario.

**Comment by bartonjs** [comment]
On Linux we should be getting it from https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/CertificatePolicy.cs

Assuming, of course, that the class works correctly it seems like it'd be easy enough to add it to the Apple pipeline (if it isn't there already) and ignore the native code.

**Comment by vcsjones** [comment]
@bartonjs Hm, I was looking more at the internal chain building mechanisms, not the managed one. Windows and macOS both enforce policy constraints in the presence of a 2.5.29.36 extension when requireExplicitPolicy is violated.

> On Linux we should be getting it from

If Linux is meant to be checking policy enforcement today, that does not seem to be the case.

Adding `X509_V_FLAG_POLICY_CHECK` to here gets policy checking similarly to Windows / macOS:

https://github.com/dotnet/runtime/blob/d448461805e68566a33611acccf7589dad73976a/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_x509.c#L233

**Comment by bartonjs** [comment]
> Adding X509_V_FLAG_POLICY_CHECK to here gets policy checking similarly to Windows / macOS:

Hm. I feel like there was a reason I couldn't or didn't use that in the past, but instead wrote the CertificatePolicy class.  Maybe it wasn't available on 0.9.8 (which was in support at the time)?  Or maybe it was like macOS and didn't give the codes separated the Windows way.

Or maybe I'm only thinking about what happens when there's a value specified in ChainPolicy.ApplicationPolicy or ChainPolicy.CertificatePolicy, and this is about chain consistency, and we just want to use the flag.

So nice that we have a framework for writing tests for these things now :smile:.

**Comment by vcsjones** [comment]
> Or maybe I'm only thinking about what happens when there's a value specified in ChainPolicy.ApplicationPolicy or ChainPolicy.CertificatePolicy, and this is about chain consistency, and we just want to use the flag.

This seems the most plausible.

> So nice that we have a framework for writing tests for these things now.

Indeed. The dynamic chain and revocation tests are extremely helpful.

**Comment by vcsjones** [comment]
> Adding X509_V_FLAG_POLICY_CHECK to here gets policy checking similarly to Windows / macOS

Hm. It appears I was mistaken exactly as to what this flag does. Policy checking in OpenSSL and Windows appears to be rather different from how it is done in Windows and MacOS.
