### ISSUE TITLE
Task.Delay: CancellationToken registration leak

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#46603]
`DelayPromise` is the implementation class for `Task.Delay`. Its constructor handles a race condition such that the underlying `TimerQueueTimer` still gets cleaned up if its callback fires before the backing field is written:

https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5433-L5476

`DelayPromiseWithCancellation` derives from `DelayPromise` and implements cancellation support:

https://github.com/dotnet/runtime/blob/5f984ae83f0c474e03d7e42a4cec8ab08bba4e8d/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L5478-L5505

Note that `DelayPromiseWithCancellation`'s constructor does not handle any race conditions. This means that if the race condition mentioned above occurs such that its overridden `Cleanup` implementation gets called before its constructor runs, the constructor will still call `token.UnsafeRegister`, and thus the registration will leak.

I believe the fix would be to simply check for the race condition after the registration the same way as `DelayPromise` and manually unregister the callback:

```c#
if (IsCompleted)
    _registration.Dispose();
```

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
Yeah, this is a bug.  It's thankfully not particularly impactful because it's really unlikely the timer would fire between the time the timer is created and the time it registers with the token, and then even if it does, in most cases the token is ephemeral so any leak would be short lived.  But we should still fix it for 6.0.
