### ISSUE TITLE
Analyzer proposal: ThreadStatic on a non-static field

### ISSUE THREAD

**Issue by svick** [dotnet/runtime#46626]
As [documented](https://docs.microsoft.com/en-us/dotnet/api/system.threadstaticattribute?view=net-5.0#remarks) (and implied by its name), the `[ThreadStatic]` attribute only works if it's applied on a `static` field.

But if you accidentally apply it on an instance field, there is no warning or any other indication that the code is incorrect. I think there should be.

The message could also mention `ThreadLocal<T>`, which is effectively the equivalent of `[ThreadStatic]` that also works on instance fields.

**Comment by huoyaoyuan** [comment]
The documentation also mentioned initial values. It should also be handled. The analyzer could be "Use ThreadLocal correctly".

**Comment by stephentoub** [comment]
We should have a Warning level diagnostic for applying [ThreadStatic] to instance fields.  A fixer should offer to make it static, and potentially an option to switch it to be a `ThreadLocal<T>`, though that's more involved.

We should have an Info level diagnostic for providing an initial value for a [ThreadStatic] field.

**Comment by terrajobst** [comment]
* Looks good as proposed by @stephentoub
    - We should have a Warning level diagnostic for applying `[ThreadStatic]` to instance fields. A fixer should offer to make it static, and potentially an option to switch it to be a `ThreadLocal<T>`, though that's more involved.
    - We should have an Info level diagnostic for providing an initial value for a `[ThreadStatic]` field.
* Should be in the Reliability category

**Comment by deeprobin** [comment]
Is there a special case how to deal with `readonly static`s?
