### ISSUE TITLE
SortedSet.Remove is incorrectly annotated to require a non-null parameter

### ISSUE THREAD

**Issue by jyrkive** [dotnet/runtime#46620]
### Description

Calling `SortedSet.Remove()` with a nullable parameter triggers warning CS8604: "Possible null reference argument for parameter 'item' in 'bool SortedSet<Scenario>.Remove(Scenario item)'"

The method is explicitly documented to accept `null` for reference types: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.remove?view=net-5.0#System_Collections_Generic_SortedSet_1_Remove__0_

> `item` can be `null` for reference types.

Short example code to reproduce the problem (needs to be compiled with non-nullable reference types enabled):

```cs
using System.Collections.Generic;

class Scenario {}

void Method()
{
    var scenarioQueue = new SortedSet<Scenario>();
    Scenario? scenario = null;
    scenarioQueue.Remove(scenario);
}
```

### Configuration

.NET 5
Visual Studio 2019 v16.8.3
Windows 10 20H2
x64

### Other information

Easy to work around by just using the dammit operator: `scenarioQueue.Remove(scenario!)`

**Comment by En3Tho** [comment]
The fact that it doesn't blow up with null as parameter does not mean it expects one. Nullable reference types are needed to show intention. And here it means "give me an adequate non-null value I can execute my main logic with".

**Comment by jyrkive** [comment]
If nothing else, ability to pass `null` to the Remove method is convenient. My actual use case is a method that takes the minimum element, removes it from the set and returns it. The idea is to use SortedSet as a priority queue that automatically removes duplicates.

```cs
private Scenario? GetNextScenario()
{
    Scenario? scenario = m_scenarioQueue.Min;
    m_scenarioQueue.Remove(scenario);
    return scenario;
}
```

I could obviously have a null check here, but attempting to remove `null` from a set is a no-op anyway.

**Comment by huoyaoyuan** [comment]
All `Remove` of collection types is marked so. Perhaps we can accept null on all `ICollection<T>.Remove`.

**Comment by huoyaoyuan** [comment]
> The method is explicitly documented to accept `null` for reference types:

In fact, the documentation is some sort out of date. It was written far before NRT, and meant "`T` can be nullable".

**Comment by stephentoub** [comment]
> It was written far before NRT, and meant "T can be nullable".

Right.  The intention here is that if you want to be able to pass null, then you should use a nullable T.  If you choose to use a non-nullable T, then you're saying nulls aren't valid in your domain.

The same category of issue was discussed in https://github.com/dotnet/runtime/issues/1775#issuecomment-580041421, and the decision was to leave it as-is; we should do so here as well.

Thanks.

**Comment by jyrkive** [comment]
I see. In that case I think the `SortedSet.Remove()` documentation should be updated to say "`item` can be `null` for **nullable** reference types" to make the intention more clear.

Do issues about documentation updates also go to this repo?

**Comment by stephentoub** [comment]
Thanks.  You can open issues or even submit PRs at https://github.com/dotnet/dotnet-api-docs.

**Comment by jyrkive** [comment]
Alright, I filed dotnet/dotnet-api-docs#5205. Thanks!
