### ISSUE TITLE
Framework-dependent executable on .NET 5 prompts users to download .NET Core Runtime instead

### ISSUE THREAD

**Issue by AbstractQbit** [dotnet/runtime#46628]
This dialog box
https://github.com/dotnet/runtime/blob/b0de92b9e1459bbb3653c820e2d3cb311d656f5f/src/installer/corehost/cli/apphost/apphost.windows.cpp#L116
redirects users to https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=5.0.1&gui=true, but it opens a page with .NET Core 3.1 downloads. This causes some confusion among non tech-savvy users, as they install what they were prompted to but the app still throws an error.

This is probably an issue with the site, but since idk where else to open this issue, opening it here.

**Comment by jkotas** [comment]
@mairaw Is it possible to fix the website to show the correct page with downloads for this URL?

**Comment by vitek-karas** [comment]
Related to https://github.com/dotnet/runtime/issues/36765.

The website issue tracking at least parts of this is here: https://github.com/dotnet/website/issues/1958 (private repo).

**Comment by AbstractQbit** [comment]
Just checked, the link redirects to a .NET 5 download page now, thanks!
