### ISSUE TITLE
Feature request: Helper for implementing IValueTaskSource which supports CancellationToken

### ISSUE THREAD

**Issue by RamType0** [dotnet/runtime#46632]
## Background and Motivation
IMHO, we could hardly implement pooled IValueTaskSource which supports CancellationToken.

First of all,

- We usually uses CancellationToken.Register for scheduling cancellation callback.
- We could not know CancellationTokenRegistration.Dispose actually suppressed calling back previously registered delegate.
we can use CancellationTokenRegistration.Unregister to know whether is was canceled,but it is only available in .NET Core 3.0 or later. Not available in the latest UWP or Unity which IValueTaskSource and ManualResetValueTaskSourceCore is available.
- The end timing of executing cancellation callback could be later than IValueTaskSource.GetResult has been called.(When its cancelled from other threads)

Then, imagine the case

1. The task has been started with CancellationToken which can be cancelled.
2. The task has been completed at almost same time the passed CancellationToken cancelled from other threads.

The case 1 is very common. We want to avoid failing to pool task in case 1.

The case 2 is very rare, but could be happen after case 1 happened. And we could hardly pooling task in this situation. 
Failing to pool task in case 2 is seems to be acceptable, but we could not know whether the case 2 actually happened or just case 1 happened, in the platform other than .NET Core3.0 or later.

We already have IValueTaskSource implementation helper, ManualResetValueTaskSourceCore.
But it doesn't have feature for preventing cancellation callback execution after its reset.

I couldn't figure out the solution which doesn't requires CancellationTokenRegistration.Unregister.

If you have any good implementation, it should be documented in Microsoft Docs of IValueTaskSource, or integrated with ManualResetValueTaskSourceCore.

If you have no solution for this, the risk should be documented in Microsoft Docs of IValueTaskSource.

Currently, we will easily make this mistake with ManualResetValueTaskSourceCore even with .NET Core 3.0 or later.

**Comment by stephentoub** [comment]
> The end timing of executing cancellation callback could be later than IValueTaskSource.GetResult has been called.(When its cancelled from other threads)

I'm not understanding the concern.  CancellationTokenRegistration.Dispose guarantees that, upon its return, the callback has either already completed running or will never run.  Dispose will not return while the callback is currently executing (unless it's being called from the callback itself, which isn't relevant to your scenario).

Whatever code you have that's registering with the CancellationToken just needs to Dispose of that registration prior to reusing the instance.

**Comment by RamType0** [comment]
> > The end timing of executing cancellation callback could be later than IValueTaskSource.GetResult has been called.(When its cancelled from other threads)
> 
> I'm not understanding the concern. CancellationTokenRegistration.Dispose guarantees that, upon its return, the callback has either already completed running or will never run. Dispose will not return while the callback is currently executing (unless it's being called from the callback itself, which isn't relevant to your scenario).

Oh, really?
That's sounds great!
[But it seems to be not documented.](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokenregistration.dispose?view=net-5.0#System_Threading_CancellationTokenRegistration_Dispose)

**Comment by stephentoub** [comment]
Yes, the docs could be improved; please feel free to open an issue or submit a PR to the docs repo: https://github.com/dotnet/dotnet-api-docs.  Note that there is a comment to this regard on DisposeAsync: https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokenregistration.disposeasync?view=net-5.0#remarks.

Thanks.

**Comment by RamType0** [comment]
This could be not something that I should ask you,but I want to know.
Is it a specification of CLI?(Also guaranteed in Unity mono or .NET Framework4.0?)

**Comment by stephentoub** [comment]
It should be the case for any implementation (and has been that way since it was originally introduced in .NET Framework).  It's a critical aspect of the design.
