### ISSUE TITLE
ShiftLeftLogical doesn't seem to work for variable shift

### ISSUE THREAD

**Issue by bencyoung** [dotnet/runtime#46630]
You can do this simply in the VS interactive window but I'm seeing it in a .NET 5 project as well:

I think both of the below should do the same thing?

```
Avx.ShiftLeftLogical(Vector128.Create(1), Vector128.Create(1))  => <0, 0, 0, 0> | System.Runtime.Intrinsics.Vector128<int>
Avx.ShiftLeftLogical(Vector128.Create(1), 1) => <2, 2, 2, 2> | System.Runtime.Intrinsics.Vector128<int>
```

am I doing something silly here?

**Comment by tannergooding** [comment]
In this case, `Sse2.ShiftLeftLogical` (which is what your call resolves to) maps to `PSLLD` which operates as:

*imm8 operand*
```
DEST[127:0] <- LOGICAL_LEFT_SHIFT_DWORDS(SRC1, imm8)
DEST[MAXVL-1:128] <- 0
```

*xmm/memory operand*
```
DEST[127:0] <- LOGICAL_LEFT_SHIFT_DWORDS(SRC1, SRC2)
DEST[MAXVL-1:128] <- 0
```

where:
```
LOGICAL_LEFT_SHIFT_DWORDS(SRC, COUNT_SRC)
    COUNT <- COUNT_SRC[63:0];
    IF (COUNT > 31)
    THEN
        DEST[127:0] <- 00000000000000000000000000000000H
    ELSE
        DEST[31:0] <- ZeroExtend(SRC[31:0] << COUNT);
        (* Repeat shift operation for 2nd through 3rd words *)
        DEST[127:96] <- ZeroExtend(SRC[127:96] << COUNT);
    FI;
```

Since `Vector128.Create(1)` will have the lower 64-bits be `0x0000000100000001` which is greater than 31, it produces 0.
You would need either use `Vector128.Create(1, 0, 0, 0)` or use `Avx2.ShiftLeftLogicalVariable` if you wanted to have different shift amount per-element.

**Comment by bencyoung** [comment]
Thanks, that's great. Lots of fun writing an AVX accelerated version of exp and other trigonometric functions.

**Comment by bencyoung** [comment]
@tannergooding Is efficiency of these tracked elsewhere? I notice the generate assembly is not ideal...

I have a sequence like 

```
                var u5 = Fma.MultiplyAdd(u4, s, Vector256.Create(2.4801587159235472998791e-05));
                var u6 = Fma.MultiplyAdd(u5, s, Vector256.Create(0.000198412698960509205564975));
                var u7 = Fma.MultiplyAdd(u6, s, Vector256.Create(0.00138888888889774492207962));
                var u8 = Fma.MultiplyAdd(u7, s, Vector256.Create(0.00833333333331652721664984));
```

(I did the chained locals as I noticed it stopped a memory read for every operation), but I still get a memory access for each when I think it could just all be registers:

```
00007FFF18EED429  vfmadd213pd ymm0,ymm1,ymmword ptr [Runner.ExpOp.Perform(System.Runtime.Intrinsics.Vector256`1<Double>)+04E0h (07FFF18EED820h)]  
00007FFF18EED432  vmovupd     ymm1,ymmword ptr [rbp-70h]  
00007FFF18EED437  vfmadd213pd ymm0,ymm1,ymmword ptr [Runner.ExpOp.Perform(System.Runtime.Intrinsics.Vector256`1<Double>)+0520h (07FFF18EED860h)]  
00007FFF18EED440  vmovupd     ymm1,ymmword ptr [rbp-70h]  
00007FFF18EED445  vfmadd213pd ymm0,ymm1,ymmword ptr [Runner.ExpOp.Perform(System.Runtime.Intrinsics.Vector256`1<Double>)+0560h (07FFF18EED8A0h)]  
00007FFF18EED44E  vmovupd     ymm1,ymmword ptr [rbp-70h]  
00007FFF18EED453  vfmadd213pd ymm0,ymm1,ymmword ptr [Runner.ExpOp.Perform(System.Runtime.Intrinsics.Vector256`1<Double>)+05A0h (07FFF18EED8E0h)]  
00007FFF18EED45C  vmovupd     ymm1,ymmword ptr [rbp-70h]  
00007FFF18EED461  vfmadd213pd ymm0,ymm1,ymmword ptr [Runner.ExpOp.Perform(System.Runtime.Intrinsics.Vector256`1<Double>)+05E0h (07FFF18EED920h)] 
```

I don't think there's a need for all the "vmovupd" in this?

**Comment by bencyoung** [comment]
(Note it's still 3.5x faster than the manual loop, but I'm trying to push it)

**Comment by tannergooding** [comment]
> Is efficiency of these tracked elsewhere? I notice the generate assembly is not ideal...

If you could open a small repro for specific codegen inefficiencies that would be great (particularly if a small repro can be found) 😄 

Someone can then take a look at the JIT dump for said repro to identiy why `s` is continuously reloaded here.
