### ISSUE TITLE
[Wasm] Stand up AOT CI Leg

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#46633]
Since we were able to get System.Buffers to succeed, let's add a new CI leg to see how the rest of the suites hold up.

I would recommend starting the work out as a draft PR as there will likely be many hiccups.

**Comment by SamMonoRT** [comment]
@mdh1418 - didn't we address this already, can we close the issue ?

**Comment by steveisok** [comment]
Yes, this can be closed.
