### ISSUE TITLE
Unix Domain Sockets - SocketException "An address incompatible with the requested protocol was used." is thrown

### ISSUE THREAD

**Issue by amsoedal** [dotnet/runtime#46648]
# Issue Title

Unix Domain Sockets - SocketException "An address incompatible with the requested protocol was used." is thrown

# General

Hi, our product (a .NET Core 3.1 app which runs locally on the users' workstations) has been using Unix Domain Sockets without any issues for some time now.  We instantiate the socket like so: 

```
            _socket = new System.Net.Sockets.Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified)
            {
                SendBufferSize = Constants.EndpointManager.SocketBufferSize,
                ReceiveBufferSize = Constants.EndpointManager.SocketBufferSize
            };
```

However, one of our customers is unable to run our product on Windows and consistently reproduces this exception: 

"ClassName":"System.Net.Sockets.SocketException","Message":"**An address incompatible with the requested protocol was used.**","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)\r\n

I'm currently gathering more information from them about their system, but is this a known issue? Are there any unix domain socket conventions we're missing? Thank you in advance!

**Comment by stephentoub** [comment]
> However, one of our customers is unable to run our product on Windows and consistently reproduces this exception

Do you know what version of Windows they're using?  Might it be earlier than Windows 10 version 1803 (10.0.17134)?

**Comment by amsoedal** [comment]
@dagood thanks for transferring this! :) 

@stephentoub These are the details regarding their system: https://user-images.githubusercontent.com/63369949/103228098-4af8a880-4930-11eb-951e-8b48fc570445.png

Looks like you're right, they are running 10.0.15063. Should I ask them to upgrade?

**Comment by stephentoub** [comment]
> Looks like you're right, they are running 10.0.15063. Should I ask them to upgrade?

Yes, Windows only supports Unix Domain Sockets as of the version I cited. The error you're seeing is coming from the operating system because it doesn't support that address family.

Good luck.
