### ISSUE TITLE
GC Hole in System.Private.Uri.Functional.Tests Linux-musl arm64 test run

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#46642]
Dump with instructions at https://dev.azure.com/dnceng/public/_build/results?buildId=939436&view=ms.vss-test-web.build-test-results-tab&runId=29691932&resultId=175272&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

Seen in https://github.com/dotnet/runtime/pull/46550

**Comment by JulieLeeMSFT** [comment]
@echesakovMSFT PTAL.

**Comment by echesakovMSFT** [comment]
I will take a look and see if I can repro the issue locally

**Comment by echesakovMSFT** [comment]
I tried to repro the failure and left the test running on a machine for last night - no failures after a hundred attempts.

Closing.
