### ISSUE TITLE
BroadcastBlock<T>.AsObservable() result has non-deterministic behavior based on race condition

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#46677]
### Description

I use a `BroadcastBlock<T>` in order to ensure every client receives the latest message, regardless of when a the block is linked to a given client. This works great.

But when those clients are added via the `IObservable<T>` that is returned from the `ISourceBlock<T>.AsObservable()` extension method, a race condition causes new observers to not receive any value at all.

### Configuration

This repros on net472 as well as netcoreapp3.1

### Regression?

I do not know. Using dataflow blocks directly has always worked great for us. This is my first time really trying to use the `AsObservable()` extension method this way.

### Repro

```cs
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;

class Program
{
    static async Task Main(string[] args)
    {
        var bb = new BroadcastBlock<int>(v => v);
        bb.Post(3);
        var observable = bb.AsObservable();

        AddObserver(observable);
        AddObserver(observable);

        // THIS IS THE CRUX OF IT. Try commenting or uncommenting it.
        // On my machine, expected == actual without this delay
        // but with the delay, expected == 4 while actual == 2.
        //await Task.Delay(1000);

        AddObserver(observable);
        AddObserver(observable);

        await Task.Delay(1000);

        Console.WriteLine($"Expected: {observerCounter}");
        Console.WriteLine($"Actual:   {observedCounter}");
    }

    static int observerCounter;
    internal static int observedCounter;

    static void AddObserver(IObservable<int> o) => o.Subscribe(new Observer(++observerCounter));
}

class Observer : IObserver<int>
{
    private readonly int num;

    internal Observer(int num)
    {
        this.num = num;
    }

    public void OnCompleted() => throw new NotImplementedException();

    public void OnError(Exception error) => throw new NotImplementedException();

    public void OnNext(int value)
    {
        Interlocked.Increment(ref Program.observedCounter);
        Console.WriteLine($"Observer {num} received {value}.");
    }
}
```

With this project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Dataflow" Version="5.0.0" />
  </ItemGroup>
</Project>

```

**Comment by AArnott** [comment]
@stephentoub This seems like one you would be interested in.

**Comment by stephentoub** [comment]
The observable is the only target of the broadcast, so it's just "broadcasting" to a single target, which really means it's just forwarding the items along.  The observable isn't itself caching every item its seen; it forwards every item along to any observer registered at the time.  So in your example, any observers registered by the time the broadcast's queued work item forwards the item to the observable will receive it, but any registered later won't because the item is long gone.

**Comment by AArnott** [comment]
I guess that makes sense. Should we have a `BroadcastBlock<T>`-specific observable that retains the original block's behavior? We could do this with an `AsObservable()` instance method on `BroadcastBlock<T>` or even as another extension method but applied to the concrete type so the compiler prefers it.

Here is the workaround I came up with that has the behavior I'm looking for, in case anyone is interested:

```cs
private class BroadcastObservable<T> : IObservable<T>
{
    private readonly BroadcastBlock<T> sourceBlock = new(v => v);

    internal T? Value => this.sourceBlock.TryReceive(out T? value) ? value : default;

    public IDisposable Subscribe(IObserver<T> observer)
    {
        var actionBlock = new ActionBlock<T>(observer.OnNext);
        actionBlock.Completion.ContinueWith(
            static (t, s) =>
            {
                var observer = (IObserver<T>)s!;
                if (t.Exception is object)
                {
                    observer.OnError(t.Exception);
                }
                else
                {
                    observer.OnCompleted();
                }
            },
            observer,
            TaskScheduler.Default).Forget();
        return this.sourceBlock.LinkTo(actionBlock, new DataflowLinkOptions { PropagateCompletion = true });
    }

    internal void Post(T value) => this.sourceBlock.Post(value);
}
```
