### ISSUE TITLE
Range based Foreach loop idiom

### ISSUE THREAD

**Issue by GinoMan** [dotnet/runtime#46679]
## Summary

Currently, any attempt to obtain all the numbers of a numeric range require the usage of the for loop. This isn't bad per se, but sometimes it can be quite verbose when you just want all the integers between 0 and an ending number, or 0 and an ending number with a certain skipping (every n-th value) or you want to start at a different starting value. In other languages, such as Python, this can be accomplished with slicing or by using the "Range()" function. But C# still only uses the base for loop. This wouldn't be so bad except that Generic Collections likewise do not have a way to set a default length, just a default capacity so you can't foreach over the empty collection expecting default values, so first you have to call List<T>.Add(default); that number of times so that the List has the exact size you want to start with if you need to start with that in the first place, and the only way to do that is in a regular, verbose for loop, but what if there was a better way?

## Background and Motivation

Recently I've found myself needing to get a range of integers, usually from 0 to n, in order to build up a list or deal with an entire array. To the point that I've begun including a set of extension methods in my projects and a using statement at the top that brings certain static methods into the global namespace. 

While my use case specifically pertains to how I'm storing assets in unity through the inspector's GUI as a table, but to the code as a list, isn't as relevant as to how often any given C# programmer needs to write the same thing over and over again:

```csharp
for (int i = 0; i < n; i++) { ... }
```

contrast this with Python's range based for loop which lets you do:

```python
for i in Range(n):
    ...
```

This is quite a common pattern, so much so that Python has a System level method to handle it. But C# does not have anything similar. Additionally in most languages, if you set a numeric value in the constructor of a List or Vector, it automatically creates that many entries such that you can do

```csharp
List<T> list = new List<T>(10);
foreach (var i in list) // runs 10 times making i a reference to the list element that can then be assigned
{ ... }
```

But C# doesn't have that construct either. Instead the int parameter of List<T>'s Ctor simply pre-allocates an internal capacity of that size such that when you call the Add function several times, as long as you do so less than the number given in the Ctor, it won't trigger a memory allocation and in larger Lists will have performance benefits.

So how can we solve these problems?

## Proposed API

I propose a static method that can be accessed from a short named class (which I'm not sure what exactly it should be called yet but in my own code I have it in a static class called Help and then at the top of my file have `using static Help;`) that will yield return an IEnumerable of those integers for use in a foreach loop. 

Ideally this static method would be something accessible in all other methods directly. This would mean that the name would not have to be qualified. Instead one could simply call "Range()" in the for loop and obtain the exact range of integers requested. Additionally, I propose an IList<T> method that pre-fills the IList with a certain or default values 

```diff
namespace System.Collections.Generic
{
	public interface IList<T>
	...
+	public IEnumerable<T> Fill (int numberOfValues, T value = default)
	...
}

namespace System
{
// I recognize that the code below is not technically valid since it's not in a class,
// but that's because I'm not sure what class it would belong in
// but also I'm not as concerned about this since the intention is for this to be available
// in any method of any class.
+    public static IEnumerable<T> Range (int start, int end, int step = 1)

+    public static IEnumerable<T> Range (int end, int step = 1)

}
```

## Usage Examples

What these changes would mean is that a user of the framework would be able to get a numeric list very easily by just setting the start, end, and skip

``` csharp
List<int> numberList = Range(0, 100); // get a list of every number from 0 to 99
```

```csharp
// iterate over an array numerically without having to write a long for loop
int [] list = new int[100];
foreach (int i in Range(100))
{
	list[i] = ...; // assign a different value to each element of the array
}
```

But wait! I need only even numbers!

```csharp
// Even numbers only!
int [] list = new int[50];
foreach (int i in Range(100, 2)
{
	list [ i / 2 ] = i + 2; // generates the array [2, 4, 6, 8, 10, ...]
}
```

Another good usage that I had in mind was this:

```csharp
List<SomeClass> myList = new List<SomeClass>();
foreach (var _ in Range(150))
{
	myList.Add(default);
}
```

This last case is where the Fill function comes in. Why need to write a loop at all?

```csharp
List<SomeClass> myList = new List<SomeClass>();
myList.Fill(150);
```

Oh but we don't want them to be null? not a problem!

```csharp
List<SomeClass> myList = new List<SomeClass>();
myList.Fill (150, new SomeClass());
```

## Alternative Designs

Originally I thought of making these extension methods to "List" but I felt that didn't make as much sense. It was also limiting since List<T> is not the only numeric array. In soliciting feedback about this and similar features, I was informed that "GetEnumerator" could be added to the Range class through an extension method that would allow for the syntax...

```csharp
foreach (var i in 0..100) { ... }
```

I really really like this syntax but decided not to put it in the proposal section since at least one, what I think is a Microsoft employee, on the C# Discord suggested that this might be a bit hard to read for a new programmer approaching code that uses it if they're not familiar with other languages like Python or Ruby that allow you to do such things. A fair point. I disagree but I still took his advice and only mention it here as another design I looked into. I can't think of any technical reason that one couldn't implement it and if the sponsor of this issue agrees with me, I'd love to add it to the proposal.

## Risks

As mentioned before, I cannot think of anything that might be risky about it except for one thing. For programmers familiar with other languages, especially Python, will find the name "Range()" and even the usage, quite familiar. There is one difference, however, between Python's Range() and the Range() I'm proposing, which is that in Python, the second parameter to "Range()" actually indicates a length, not the ending value. I always found this counter-intuitive since more often I had an ending value in mind rather than a length from the starting value that the resultant Enumerable needed to be. This is why I instead treat it as the ending value, rather than a length from the given start.

However, C# already has a Range type, as opposed to a method. This might therefore cause some confusion among experienced programmers new to the feature. Especially if they look at a newer programmer's code using the feature leading them to assume that the code is just wrongly written. However this doesn't technically conflict since Range() will only ever be called either as a method, or as a constructor preceded by the "new" keyword:

```csharp
// a use of my proposed function
List<int> oddNumbers = Range(...);
// verses the built in Range type
Range myRange = new Range(...);
```

Still there is a small risk of the name conflict being confusing. I'm open to suggestions for a better name but I feel that "Range" describes it perfectly as of right now.

As to the "Fill" function, there really isn't anything like it or any conflicts that I can think of. However I recognize that this wouldn't apply to Dictionary<> for example. Perhaps it should be specifically part of the List and Array classes? Hard for me to say. 

## Current Implementation

Currently, as described above, I have a set of static methods in a helper class, called "Help" that provides these methods to me without the need to amend the API, but to me, it seems like such a simple quality of life feature that I can't see any good reason for it not to be included with .NET:

```csharp
using static Help;

public static class Help
{
	public static IEnumerable<int> Range(int start, int end, int step = 1)
	{
		for (int i = start; i < end; i += step) yield return i;
	}
	public static IEnumerable<int> Range(int end, int step = 1)
	{
		for (int i = 0; i < end; i += step) yield return i;
	}
	public static IList<T> Fill<T>(this IList<T> list, int numberOfElements)
	{
		foreach (var _ in Range(numberOfElements)) { list.Add(default); }
		return list; // I chose this so that methods could be chained to it. 
	}
}
```

**Comment by huoyaoyuan** [comment]
There is already a `Range` api without stepping:
`System.Linq.Enumerable.Range(int start, int count) -> IEnumerable<int>`.
So adding an overload for stepping makes sense.

For continuous range, integration with C# range can be achieved by an extension `Slice` method.

**Comment by huoyaoyuan** [comment]
The `Fill` method can be achieved in other way:
```csharp
list.AddRange(Enumerable.Repeat(value, number));
```

**Comment by Clockwork-Muse** [comment]
> There is already a `Range` api without stepping:
> `System.Linq.Enumerable.Range(int start, int count) -> IEnumerable<int>`.
> So adding an overload for stepping makes sense.

With stepping:
```csharp
System.Linq.Enumerable.Range(int start, int count).Select(e => e * step)
```

**Comment by Dewera** [comment]
Linq solves all of these issues

```c#
var numberList = Enumerable.Range(0, 100).ToList();

var list = Enumerable.Range(0, 100).Select(x => ...).ToList();

var evenNumbers = Enumerable.Range(0, 100).Where(x => x % 2 == 0).ToList();

List<SomeClass> filledList = Enumerable.Repeat(default, 150).ToList();

var nonNulFilledList = Enumerable.Repeat(default, 150).ToList();
```
> foreach (int i in Range(100))

Seems like unnecessary allocations to save a few characters but if you really want this syntax you can just do

```c#
foreach (var i in Enumerable.Range(0, 100))
{
    ...
}
```

**Comment by GinoMan** [comment]
> 
> 
> There is already a `Range` api without stepping:
> `System.Linq.Enumerable.Range(int start, int count) -> IEnumerable<int>`.
> So adding an overload for stepping makes sense.
> 
> For continuous range, integration with C# range can be achieved by an extension `Slice` method.

That seems quite verbose however. Especially compared to for (int i = 0; i < n; i++) { }

**Comment by GinoMan** [comment]
> 
> 
> The `Fill` method can be achieved in other way:
> 
> ```cs
> list.AddRange(Enumerable.Repeat(value, number));
> ```

Thank you for posting this. That is quite useful. I still think it might be worthwhile to add a "Fill" method if for no other reason than discoverability and concision.

**Comment by Clockwork-Muse** [comment]
> > There is already a `Range` api without stepping:
> > `System.Linq.Enumerable.Range(int start, int count) -> IEnumerable<int>`.
> > So adding an overload for stepping makes sense.
> > For continuous range, integration with C# range can be achieved by an extension `Slice` method.
> 
> That seems quite verbose however. Especially compared to for (int i = 0; i < n; i++) { }
> 
> or in the case of the helper class I wrote: foreach (int i in Range(...)) { }

```csharp
using System;

// You want this line to make things shorter
using static System.Linq.Enumerable;

public class Program
{
	public static void Main()
	{
		foreach (var i in Range(0, 6))
		{
			Console.WriteLine(i);
		}	
	}
}
```

**Comment by GinoMan** [comment]
> 
> ```cs
> using System;
> 
> // You want this line to make things shorter
> using static System.Linq.Enumerable;
> 
> public class Program
> {
> 	public static void Main()
> 	{
> 		foreach (var i in Range(0, 6))
> 		{
> 			Console.WriteLine(i);
> 		}	
> 	}
> }
> ```

Yes, I recognize I could use the same trick to shorten it, but that still in my mind fails discoverability. Understand that I searched for a way to do this online several times over the years and am only just now learning about it from this very thread. That says something to me. 

That said, point taken.

**Comment by eiriktsarpalis** [comment]
@GinoMan By the sound of it `Enumerable.Range` and `Enumerable.Repeat` more or less address your problem? We're missing a `Range` overload that accepts a `step` argument (which for example can be found in F#).

**Comment by GinoMan** [comment]
Yes. Unfortunately I never found these because they were in a completely different library I never would have thought to check. This admittedly forces me to change my advocacy from "This doesn't exist" to "This is so hard to find that unless you know where to look you won't find it, therefore there should be a way to access the functionality elsewhere". Even if that means it's basically just a wrapper for the functionality in Linq in System.Collections or System.Collections.Generic. 

But if the community disagrees then I will close the issue.

**Comment by En3Tho** [comment]
Fill does not really fit in IEnumerable domain because it 'filling' assumes writing, not reading. Foreach In Range(100) basically means Foreach in Take(100). So maybe it's better to have Take overload having new inner 'skip' arg. Like Take(100, 3) means take an element, skip 3, take another... Until 100 elements are taken. Or something like that

**Comment by svick** [comment]
@GinoMan Why do you think duplicating existing functionality in a different namespace will help discoverability? Especially since you admit you're not sure what class these methods belong to.

**Comment by GinoMan** [comment]
En3Tho: It depends on whether I'm correct or not that the functionality for that could be implemented simply by adding GetEnumerator to the Range type. If so, then there would only be a need to create that method. Skipping isn't as important to me as getting a range of integers with which to work with. Skipping is just a nice addon you can have to a single Range() method. 

Filling to me makes sense for at least List<>, and I could think of other ideas for other types (like Dict<K, V>.Fill(List<K>) // fills keys and sets all the associated values to "default". 

svick: I was stating that the first place I looked for how to set the Count of a list was in the intellisense for List<T>. scrolling down nothing jumped out at me as a way to succinctly make it so it was a list of some number of empty (default) values.

**Comment by Clockwork-Muse** [comment]
> Filling to me makes sense for at least List<>, and I could think of other ideas for other types (like Dict<K, V>.Fill(List) // fills keys and sets all the associated values to "default".

```csharp
using System;

// Repeat is in here too.
using static System.Linq.Enumerable;

public class Program
{
	public static void Main()
	{
		var d = new whatever();
		var n = new List<whatever>(Repeat(d, count));
		// Or with a pre-existing list
		someList.AddRange(Repeat(d, count));
	}
}
```

This is in Linq, which is probably one of the better-known "general" libraries in the BCL.  Although it's probably used less in games due to performance considerations.

> I was stating that the first place I looked for how to set the Count of a list was in the intellisense for List. scrolling down nothing jumped out at me as a way to succinctly make it so it was a list of some number of empty (default) values. My specific use case was Unity since in Unity's editor, you have to create entries in the list either manually in the inspector or in code using a tag which then gives you whatever number of objects, except if there's already objects there, then it will clear them out to create them. If you use "Add" then it will double the number of objects unless you "Clear()". I mitigated that myself in the method by checking if it was null, and then if it had the correct number of elements and only in those resetting the count.

You can set the _capacity_ of a list, but for a reference type this probably isn't going to reserve the memory for the objects themselves (in Unity, and for sure not in the normal runtime).

That aside, there has to be some other way to do what you want, because the steps you're describing are pretty brittle.

**Comment by GinoMan** [comment]
The tag part is you have to tag the method to basically "run this whenever this is started by anything". The problem is that that might be just picking a different object and then going back to it, or opening it in the editor, or (insert circumstance here that causes the code to re-instantiate). I agree that some things Unity does is fragile. Heck, you can't even check if a given object is null or not and expect it to work. You have to use the overridden bool cast operator to do it:

```csharp
if (someObject is null) someObject.doSomething(); // still might throw NRE because of the magical way these objects work
if (someObject) someObject.doSomething(); // won't throw, someObject returns false even if it's instantiated but not valid
```

But that's not the only time in my C# career where I've wanted to pre-fill a List<T>.

**Comment by Clockwork-Muse** [comment]
... it sounds like you've stuck this initialization in `OnEnable()`, but it possibly should have gone in `Start()` or `Awake()`.

**Comment by GinoMan** [comment]
Actually....

```csharp
[OnInspectorInit]
private void InitData() { ... }
```

**Comment by NN---** [comment]
@GinoMan You can add GetEnumerator for Range and get an expected syntax:

```cs
internal class Program
{
    public static void Main()
    {
        foreach (var x in 1..10) Console.WriteLine(x);
    }
}

public static class RangeExtensions
{
    public static IEnumerator<int> GetEnumerator(this Range range)
    {
        return new Enumerator(range);
    }

    public struct Enumerator : IEnumerator<int>
    {
        private readonly int _start;
        private readonly int _end;

        public Enumerator(Range range)
        {
            _start = Current = range.Start.Value - 1;
            _end = range.End.Value;
        }

        public bool MoveNext()
        {
            if (Current != _end)
            {
                Current++;
                return true;
            }

            return false;
        }

        public void Reset()
        {
            Current = _start;
        }

        public int Current { get; private set; }

        object IEnumerator.Current => Current;

        public void Dispose()
        {
        }
    }
}
```

**Comment by eiriktsarpalis** [comment]
> Yes. Unfortunately I never found these because they were in a completely different library I never would have thought to check. This admittedly forces me to change my advocacy from "This doesn't exist" to "This is so hard to find that unless you know where to look you won't find it, therefore there should be a way to access the functionality elsewhere". Even if that means it's basically just a wrapper for the functionality in Linq in System.Collections or System.Collections.Generic.

The namespace confusion is understandable, and it probably stems from the fact that these components were not all designed in one iteration (LINQ came out much later than generics). At this point though I don't think we could justify introducing wrappers for the sake of improving consistency. That being said, my impression is that `Enumerable.Range` is a fairly well-known to Linq users. When I googled `"ienumerable sequence of numbers"` the first 5 results all pointed to `Enumerable.Range`.

I'm going to close the issue but feel free to reopen if you feel that there are potential approaches that need to be discussed. Thank you for your contribution.

**Comment by eiriktsarpalis** [comment]
@NN--- Nice! Note that you can eliminate boxing of your enumerator by having your `GetEnumerator` method return `Enumerator` instead of the interface type.

**Comment by NN---** [comment]
@eiriktsarpalis Yes. It just was an example :)

**Comment by stephentoub** [comment]
For reference, note that in the past we've considered multiple times adding such an IEnumerable/GetEnumerator implementation, but each time decided against it, in part because Range often represents ranges that only have meaning in another context.  Consider `1..^1`, which means to go from the [1] element in the collection to the [Count - 1] element in the collection... without context to supply that "Count", it's meaningless and not enumerable.
