### ISSUE TITLE
System.Text.Json.JsonSerializer.DeserializeObject doesn't deserialize object when class with default value 

### ISSUE THREAD

**Issue by ryank-private** [dotnet/runtime#46694]
System.Text.Json.JsonSerializer.DeserializeObject doesn't work as the same for classes with default values.

It will ignore values from json input text and just keep default value of class, whereas Newtonsoft's deserialize object passes on values it can find from json correctly.

Environment: .NET 5 with VS2019 from Windows 10 x64, and Newtonsoft's package version I used in this test is 12.0.3.

```
public class JsonStrData
{
  public string StrData { get; set; }
}

public class JsonStrDataWithDefault
{
  public string StrData = null;
}

```
has different results. Both of these classes has StrData to be null in definition, but behaves differently.

Following code produces 

```
string jsonTest = "{\"StrData\": \"test\"}";


var jsonObj_SystemTextJson = JsonSerializer.Deserialize<JsonStrData>(jsonTest);
var jsonObj_SystemTextJson_NoDefault = JsonSerializer.Deserialize<JsonStrDataWithDefault>(jsonTest);

			

var jsonObj_NewtonsoftJson = Newtonsoft.Json.JsonConvert.DeserializeObject<JsonStrData>(jsonTest);
var jsonObj_NewtonsoftJson_NoDefault = Newtonsoft.Json.JsonConvert.DeserializeObject<JsonStrDataWithDefault>(jsonTest);

Console.WriteLine("System.Text.Json Results (get set, default string)");
Console.WriteLine("jsonObj_SystemTextJson.StrData: " + jsonObj_SystemTextJson.StrData);
Console.WriteLine("jsonObj_SystemTextJson_WithDefault.StrData: " + jsonObj_SystemTextJson_NoDefault.StrData);

Console.WriteLine();
Console.WriteLine("jsonObj_NewtonsoftJson.StrData: " + jsonObj_NewtonsoftJson.StrData);
Console.WriteLine("jsonObj_NewtonsoftJson_WithDefault.StrData: " + jsonObj_NewtonsoftJson_NoDefault.StrData);
```

different results.

System.Text.Json Results (get set, default string)
jsonObj_SystemTextJson.StrData: test
jsonObj_SystemTextJson_WithDefault.StrData:

jsonObj_NewtonsoftJson.StrData: test
jsonObj_NewtonsoftJson_WithDefault.StrData: test

You can just clone [this repo](https://github.com/ryank-private/CSharp_JsonTest) to run it.

**Comment by Symbai** [comment]
This is not a bug. `StrData` needs a public or private setter. If private setter it needs a `JsonInclude` attribute.

**Comment by layomia** [comment]
Given,

```cs
public class JsonStrDataWithDefault
{
    public string StrData = null;
}
```

`StrData` is a field. In System.Text.Json, fields are not included for serialization and deserialization by default. To have the field included,

- set `JsonSerializerOptions.IncludeFields` to true and pass an instance to the serializer OR
- place the `[JsonInclude]` attribute on `StrData` field.

See https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#public-and-non-public-fields for more info.
