### ISSUE TITLE
ARM64 JIT. Volatile read vs Volatile.Read

### ISSUE THREAD

**Issue by omariom** [dotnet/runtime#46703]
When disasming the following two methods with @EgorBo's [Disasmo](https://marketplace.visualstudio.com/items?itemName=EgorBogatov.Disasmo) and clrjit_win_arm64_x64.dll as the AltJit
I see that for normal volatile read of a field JIT uses **dmb** instruction.  But for Voltile.Read calls it generates **ldar**.
Theoretically ldar should be more efficient than dmb. Then why is the difference?

```C#
class Program
{
    static void Main() { }

    private int field;
    private volatile int vField;

    public int VolatileField() => vField;

    public int VolatileRead() => Volatile.Read(ref field);
}
```

```ASM
; Method VolatileArm64.Program:VolatileField():int:this
G_M1744_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
						;; bbWeight=1    PerfScore 1.50

G_M1744_IG02:
            ldr     w0, [x0,#12]
            dmb     ishld         ;; <<<< barrier
						;; bbWeight=1    PerfScore 13.00

G_M1744_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
						;; bbWeight=1    PerfScore 2.00
; Total bytes of code: 24
```

```ASM
; Method VolatileArm64.Program:VolatileRead():int:this
G_M42048_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
						;; bbWeight=1    PerfScore 1.50

G_M42048_IG02:
            add     x0, x0, #8
            ldar    w0, [x0]  ;; <<<< load-acquire
						;; bbWeight=1    PerfScore 3.50

G_M42048_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
						;; bbWeight=1    PerfScore 2.00
; Total bytes of code: 24

```

**Comment by EgorBo** [comment]
[Here is where](https://github.com/dotnet/runtime/blob/533a807b74c3b9258bb5355eb94c7fb48918f4b9/src/coreclr/jit/codegenarmarch.cpp#L1924) that `dmb` is emitted

It didn't go [this path](https://github.com/dotnet/runtime/blob/533a807b74c3b9258bb5355eb94c7fb48918f4b9/src/coreclr/jit/codegenarmarch.cpp#L1909) because addr is not in a reg yet (`addrIsInReg == false`).

**Comment by EgorBo** [comment]
@omariom btw, do you by any chance have a benchmark to prove the suggested improvement actually improves performance and worth fixing in the JIT?

**Comment by omariom** [comment]
I ran simple reading benchmarks on my Raspberry Pi 4 and then more realistic SPSC queue prototype.
In both cases Volatile.Read version were a bit slower.
But I need to check what code is generated for the Pi's CPU.  haven't checked yet how to do it.

**Comment by EgorBo** [comment]
> In both cases Volatile.Read version were a bit slower.

Are you saying that full memory barrier is more efficient basically?

**Comment by omariom** [comment]
Yes 👀

**Comment by briansull** [comment]
If there is no improvement, then no change is needed and this issue can be closed.

**Comment by omariom** [comment]
Agreed
