### ISSUE TITLE
Profiling API arm64 support

### ISSUE THREAD

**Issue by DerrickMartinez** [dotnet/runtime#46707]
We're in the process of moving 100% to arm64. Looks like we need to confirm arm64 support for the profiling API. Where does it currently stand?

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Hi @DerrickMartinez,

Profiling is fully supported for Linux and Windows on arm64 as of .Net 5.0. Everything but ELT hooks is supported in 3.1, and releases prior to 3.1 are untested by Microsoft. Let me know if you have any other questions.

**Comment by tommcdon** [comment]
Marked as a doc issue to track updating our docs.microsoft.com documentation stating that linux/windows arm64 ELT is supported
