### ISSUE TITLE
wasm AOT library test failure - memory access out of bounds

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46700]
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.

- [ ] `console.error: RuntimeError: memory access out of bounds`
`Microsoft.CSharp.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.CSharp.Tests/console.4c613a0b.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Runtime.Extensions.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Runtime.Extensions.Tests/console.9dd9462c.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Text.Json.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Text.Json.Tests/console.d49e0255.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Threading.Tasks.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Threading.Tasks.Tests/console.768eed5c.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.ObjectModel.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ObjectModel.Tests/console.a16e96d9.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Linq.Queryable.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Linq.Queryable.Tests/console.d80d259d.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.ComponentModel.TypeConverter.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ComponentModel.TypeConverter.Tests/console.30f4aaee.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Collections.Immutable.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Collections.Immutable.Tests/console.4b616a10.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.CodeDom.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.CodeDom.Tests/console.be596cd4.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Reflection.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Reflection.Tests/console.9bbb82ab.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Collections.Specialized.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Collections.Specialized.Tests/console.c051c5d6.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

Repro:
Check out changes in
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.
`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by vargaz** [comment]
That method has a filter clause:
            catch (FormatException) when (parameter.ParameterType == typeof(DateTime))

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
