### ISSUE TITLE
wasm AOT library test failure - Attempting to JIT compile method

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46708]
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.

- [ ] `System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) object object:lambda_method`
`System.Linq.Tests`
`System.Xml.XmlSerializer.ReflectionOnly.Tests`
`System.Linq.Queryable.Tests`
`Microsoft.Extensions.DependencyInjection.Tests`
`System.Composition.Tests`
`System.ComponentModel.TypeConverter.Tests`
`System.ComponentModel.Composition.Registration.Tests`
`System.Composition.Convention.Tests`
`System.Composition.TypedParts.Tests`
`Microsoft.Extensions.Http.Tests`
`System.Composition.Hosting.Tests`

- [ ] ``System.ExecutionEngineException : Attempting to JIT compile method '(wrapper dynamic-method) object Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder:ResolveService (Microsoft.Extensions.DependencyInjection.ServiceLookup.ILEmitResolverBuilder/ILEmitResolverBuilderRuntimeContext,Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.``
`Microsoft.Extensions.DependencyInjection.Tests`

- [ ] `System.ExecutionEngineException : Attempting to JIT compile method`
`Microsoft.CSharp.Tests`
`System.Reflection.Emit.ILGeneration.Tests`
`System.Reflection.Emit.Tests`
`System.Reflection.Metadata.Tests`
`System.Runtime.InteropServices.Tests`
`System.Text.Json.Tests`
`System.Numerics.Vectors.Tests`
`System.Runtime.Serialization.Json.Tests`
`System.Threading.Channels.Tests`
`System.ServiceModel.Syndication.Tests`
`System.Reflection.DispatchProxy.Tests`
`System.Net.Http.Json.Functional.Tests`
`System.Reflection.Emit.Lightweight.Tests`
`System.Drawing.Primitives.Tests`
`System.Memory.Tests`
`System.Memory.Data.Tests`
`System.Net.Http.Json.Unit.Tests`
`System.Net.WebSockets.Tests`

Repro:
Check out changes in
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by lewing** [comment]
These look like System.Reflection.Emit
