### ISSUE TITLE
Bounds checks are not elided for loops iterating in reverse.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#46701]
Just noting that I looked through the existing bounds checks issues and couldn't find out related to reverse iteration.

Take the following simple method:
```charp
public static void M(Span<byte> buffer)
{
    for (int i = buffer.Length - 1; i >= 0; i--)
    {
        buffer[i] = (byte)'0';
    }
}
```

Given that the indexer is signed, starts as less than buffer.Length, and must always be greater than or equal to zero, it will always be in bounds of `buffer`. However, the JIT currently still emits bounds checks for this scenario.
This was found while looking at codegen for https://github.com/dotnet/runtime/pull/38696#discussion_r553534635 in an attempt to reduce `unsafe` code in the number formatting logic.

**Comment by tannergooding** [comment]
sharplab.io for .NET 5: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aGnHjykmKBgFkAFAGUADtgB2AHmABPDDAB8DYAFcAZtphQAlFw7Hu26A1EBLGRgZWGAXg069UAHQAZGDIDmGAAsGOAZyAG57BlVnAAYIqzg4I2pubk4U1O4tXX0AbSsAXSdLJRUDAHIY8rDTBgBfYwbqOqA==

```asm
    L0000: sub rsp, 0x28
    L0004: mov rax, [rcx]
    L0007: mov edx, [rcx+8]
    L000a: lea ecx, [rdx-1]
    L000d: test ecx, ecx
    L000f: jl short L0023
    L0011: cmp ecx, edx
    L0013: jae short L0028
    L0015: movsxd r8, ecx
    L0018: mov byte ptr [rax+r8], 0x30
    L001d: dec ecx
    L001f: test ecx, ecx
    L0021: jge short L0011
    L0023: add rsp, 0x28
    L0027: ret
    L0028: call 0x00007ff9731fc590
    L002d: int3
```

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/issues/9505

**Comment by tannergooding** [comment]
👍, I completely missed it 😄
