### ISSUE TITLE
BrotliStream ReadByte/WriteByte are not in the ref file

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#46712]
I discovered today that the methods `BrotliStream.ReadByte` and `BrotliStream.WriteByte` have an [override implementation in source](https://github.com/dotnet/corefx/pull/30135), but they are not declared in [the ref file](https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.IO.Compression.Brotli/ref/System.IO.Compression.Brotli.cs#L29-L59).

One consequence of this is that these two APIs [do not show up in MS Docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.brotlistream.read?view=net-5.0) because they are not being part of the ref assemblies we feed in to the Docs system.

Another consequence is that when the user tries to use intellisense to autocomplete `ReadByte`, the API that shows up in the dialog is the one that belongs to `Stream`, showing documentation we have for that API.

Fortunately, a quick test reveals that we do end up calling the hidden `BrotliStream.ReadByte` overriden method.

The two methods were added in [this PR](url), which did not include them to the ref file.

@stephentoub Was there a reason for not adding them to the ref file or was it just an oversight?
@ericstj If we add them today to the ref file, are there any negative consequences we should anticipate?

**Comment by stephentoub** [comment]
BrotliStream is sealed, which means there's no functional impact on overrides not being in the ref (if a type could derive from it,  then the ref missing the overrides could impact behavior when the derived type calls to `base.`).

Neither consequence you highlight concerns me.  The docs for the base virtual are correct for the derived type,  and it's fine that IntelliSense shows the data for the base. 

That said,  there's also not that much downside to adding them.

**Comment by carlossanlop** [comment]
Thank you for the explanation, @stephentoub. I'll send a PR to add them to the ref file, since it seems it's relatively safe.
