### ISSUE TITLE
Identify and categorize Xamarin linker warnings

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#46732]
Warnings for: HelloAndroid.csproj
AndroidLinkMode: SdkOnly
Repo: https://github.com/dotnet/net6-mobile-samples
Total number of initial warnings: 73
Total number of current warnings: 32

Linker output
[XamarinLinkerExecution.log](https://github.com/dotnet/runtime/files/6053689/XamarinLinkerExecution.log)

Warnings by assembly (order on assembly appearance)

Assembly | Cost | Total warnings | Wrn | #| Wrn | #| Wrn | #| Wrn | #
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Java.Interop | XL | 23 | IL2057 | 7 | IL2070 | 4 | IL2072 | 4 | IL2026 | 3
Java.Interop (Continued) | -- | -- | IL2075 | 2 | IL2055 | 1 | IL2067 | 1 | IL2060 | 1
Android.Runtime | XL | 9 | IL2057 | 2 | IL2026 | 2 | IL2075 | 2 | IL2070 | 1
Android.Runtime (Continued) | -- | -- | IL2072 | 1 | IL2067 | 1 |   |   |   |  
~~System.Linq.Expressions~~ | ~~XL~~ | ~~30~~ | ~~IL2070~~ | ~~14~~ | ~~IL2075~~ | ~~13~~ | ~~IL2060~~ | ~~1~~ | ~~IL2045~~ | ~~1~~
~~System.Dynamic.Utils~~ | ~~L~~ | ~~4~~ | ~~IL2070~~ | ~~2~~ | ~~IL2075~~ | ~~2~~ |   |   |   |  
~~System.Reflection.Emit~~ | -- | ~~2~~ | ~~IL2074~~ | ~~1~~ | ~~IL2060~~ | ~~1~~ |   |   |   |  
~~System.Diagnostics~~ | -- | ~~1~~ | ~~IL2075~~ | ~~1~~ |   |   |   |   |   |  
~~System.Security.Cryptography~~ | -- | ~~2~~ | ~~IL2080~~ | ~~1~~ | ~~IL2077~~ | ~~1~~ |   |   |   | 

Warnings breakdown by id  (Largest on top)

Warning | Start | Current Count
-- | -- | --
IL2070 | 22 | 5
IL2075 | 20 | 4
IL2057 | 10 | 9
IL2026 | 6 | 5
IL2072 | 5 | 5
IL2060 | 3 | 1
IL2080 | 2 | 0
IL2045 | 1 | 0
IL2055 | 1 | 1
IL2067 | 1 | 2
IL2074 | 1 | 0
IL2077 | 1 | 0

**Comment by tlakollo** [comment]
Warnings by assemblies (By assembly appearance)

Assembly | Cost | Total warnings | Wrn | Count | Wrn | Count | Wrn | Count | Wrn | Count
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Java.Interop | XL | 24 | IL2057 | 7 | IL2070 | 5 | IL2072 | 4 | IL2026 | 3
Java.Interop (Cont.) | XL | 24 | IL2075 | 2 | IL2055 | 1 | IL2067 | 1 | IL2060 | 1
Android.Runtime | XL | 10 | IL2057 | 3 | IL2026 | 3 | IL2075 | 2 | IL2070 | 1
Android.Runtime (Cont.) | XL | 10 | IL2072 | 1 |   |   |   |   |   |  
System.Linq.Expressions | XL | 30 | IL2070 | 14 | IL2075 | 13 | IL2060 | 1 | IL2045 | 1
System.Dynamic.Utils | L | 4 | IL2070 | 2 | IL2075 | 2 |   |   |   |  
System.Reflection.Emit | -- | 2 | IL2074 | 1 | IL2060 | 1 |   |   |   |  
System.Diagnostics | -- | 1 | IL2075 | 1 |   |   |   |   |   |  
System.Security.Cryptography | -- | 2 | IL2080 | 1 | IL2077 | 1 |   |   |   | 

Warnings breakdown by id  (Largest on top)

Warning | Count
-- | --
IL2070 | 22
IL2075 | 20
IL2057 | 10
IL2026 | 6
IL2072 | 5
IL2060 | 3
IL2080 | 2
IL2045 | 1
IL2055 | 1
IL2067 | 1
IL2074 | 1
IL2077 | 1

**Comment by tlakollo** [comment]
Here is the architecture document that explains why Java.Interop uses System.Linq.Expressions and probably System.Dynamic.Utils too
https://github.com/xamarin/java.interop/blob/b991bb869c022616f53e4c3a324a01d77e6e4a2b/Documentation/Architecture.md
And here is the custom step in that keeps System.Linq.Expressions
https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/PreserveLinqExpressions.cs

**Comment by tlakollo** [comment]
System.Reflection.Emit warnings have an UnconditionalSupressMessage introduced with https://github.com/dotnet/runtime/pull/45723 but is not included in the samples sdk: dotnet-sdk-6.0.100-alpha.1.20562.2-win-x64.exe

**Comment by eerhardt** [comment]
@tlakollo - is the SDK you are using that old that my recent fixes aren’t in the runtime pack being used there?
Both of those changes were committed over a month ago.

**Comment by tlakollo** [comment]
The version 6.0.100-alpha.1.20562.2 means that is from Nov 12th 2020, and also the readme file has his latest update on dec 2nd. So yes, is older than the changes.

**Comment by tlakollo** [comment]
Updating with the latest visible warnings after port to https://github.com/dotnet/net6-mobile-samples

**Comment by agocke** [comment]
Closing this as warnings from the FX appear to be resolved now.
