### ISSUE TITLE
String.StartsWith/EndsWith/IndexOf/LastIndexOf ignoring null characters on Unix

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#4673]
For example, this:

``` C#
Console.WriteLine("abcte\0\0\0\0\0st".EndsWith("test"));
```

prints out true.

**Comment by safern** [comment]
There are still some tests disabled against this issue (with coreclr URL). 
https://github.com/dotnet/runtime/blob/50bd5ba4ea38e293d71b6f96c3b8c10b907bdb57/src/libraries/Common/tests/Tests/System/StringTests.cs#L1682
