### ISSUE TITLE
wasm AOT library test failure - System.Xml.RW.XmlReader.Tests

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46755]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Xml.RW.XmlReader.Tests.csproj` fails with 
```
Not found: Data at the root level is invalid
In value:  Xml_MessageWithErrorPosition, Xml_InvalidRootData, 1, 1

Not found: Invalid character in the given encoding
In value:  Xml_MessageWithErrorPosition, Xml_InvalidCharInThisEncoding, 1, 6

Not found: Name cannot begin with the
In value:  Xml_MessageWithErrorPosition, Xml_BadStartNameChar, 1, 2
```
[system_xml_rw_xmlreader_fail.txt](https://github.com/dotnet/runtime/files/5788803/system_xml_rw_xmlreader_fail.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Private.Xml/tests/XmlReader/Tests/System.Xml.RW.XmlReader.Tests.csproj`

**Comment by SamMonoRT** [comment]
@radical - are these still failing and/or tracked via your uber PR ?

**Comment by radical** [comment]
All the wasm aot test issues are labeled with `wasm-aot-test`. This, and others were filed before that, and can be closed.
