### ISSUE TITLE
PKCS12_parse:mac verify failure

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/runtime#46753]
i updated my application from 2.2 to 3.1 and facing the following error.It was working perfectly in 2.2 with docker
`'error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure'`

it was working fine with 2.2 but now facing an error in development mode. i run the following command to generate the dev certificate

```
dotnet dev-certs https -ep %APPDATA%\ASP.NET\Https\TT.Core.Portal.Web.AzureHybrid.pfx -p password
dotnet dev-certs https --trust
dotnet user-secrets -p TT.Core.Portal.Web.AzureHybrid.csproj set "Kestrel:Certificates:Development:Password" "password"
```

**program.cs** 
```     public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel(options =>
                             {
                                 bool.TryParse(Environment.GetEnvironmentVariable("IsDockerDeployment"), out bool isDockerDeployment);
                                 if (isDockerDeployment)
                                 {
                                     options.Listen(new IPEndPoint(IPAddress.Any, 443), listenOptions =>
                                     {
                                         var configuration = (IConfiguration)options.ApplicationServices.GetService(typeof(IConfiguration));
                                         var certPassword = Environment.GetEnvironmentVariable("ASPNETCORE_Kestrel__Certificates__Development__Password");
                                         var certPath = Environment.GetEnvironmentVariable("ASPNETCORE_Kestrel__Certificates__Development__Path");
                                         Console.WriteLine(certPassword);
                                         Console.WriteLine(certPath);

                                         var certificate = new X509Certificate2(certPath, certPassword);
                                         Console.WriteLine("Certificate provided");
                                         var httpsConnectionAdapterOptions = new HttpsConnectionAdapterOptions()
                                         {
                                             ClientCertificateMode = ClientCertificateMode.NoCertificate,
                                             SslProtocols = System.Security.Authentication.SslProtocols.Tls12,
                                             ServerCertificate = certificate,
                                         };
                                         listenOptions.UseHttps(httpsConnectionAdapterOptions);
                                     });
                                 }
                             });
                    ////webBuilder.UseIIS();
                    webBuilder.UseStartup<Startup>();
                });
```

i also declared both environment varibale **ASPNETCORE_Kestrel__Certificates__Development__Password** &&  **ASPNETCORE_Kestrel__Certificates__Development__Path** in the docker compose file.
Please help me to solve this issue

**Comment by bartonjs** [comment]
That error comes out of OpenSSL, and just means that the password is incorrect.  But since easy answers aren't working I'll be a bit more verbose, maybe we're in the 0.5% case here.

What that error /really/ means is that when the password was used as input to the MAC KDF the resulting key + the file contents did not verify against the embedded MAC value.  The almost always case is that the password is not the same as when the file was generated (either "the password is incorrect" or "this isn't the file you think it is").  The 0.5% case is that the file has become corrupted.

If it works with 3.1 when you're using a release configuration but fails when using a debug configuration that suggests that something in the configuration layout is wrong.

* Your debug configuration has the wrong password (is there maybe an accidental space at the end?)
* Your debug configuration has the wrong (outdated, perhaps?) file
* Your debug configuration is corrupting the file on copy
* (Or, perhaps, something I can't envision as being relevant is relevant :smile:)

If I've misunderstood the state and all that is known is that a 2.x release configuration worked and a 3.1 debug configuration doesn't, then please try 3.1 release to close down variables.

**Comment by bilalmalik777** [comment]
Hi @bartonjs, today I came back to the office from leaves that is why I did not respond to you. I deleted the pfx file and regenerated the file still facing the same error, also double-checked the password and debug configuration. What is the meaning of the last line? ` please try 3.1 release to close down variables.`

**Comment by vcsjones** [comment]
@bilalmalik777 

> regenerated the file still facing the same error

If you can generate a test PFX file that reproduces the error, where you can open in in 2.1 successfully but not 3.1, and share it with us here and the password for it, that can help us figure this out.

> What is the meaning of the last line? please try 3.1 release to close down variables.

I believe @bartonjs was asking if you can reproduce the issue in a Debug build and a Release build to make sure the right environment variables. Does it fail for both or just one?

**Comment by bilalmalik777** [comment]
it only get fail in debug mode on my machine, but over the release system it is working fine
password is "bfe4e20f-bcb4-4e95-9c76-9b7bfce2f35e", please find attach file of cert.
[TT.Core.Api.zip](https://github.com/dotnet/runtime/files/5853725/TT.Core.Api.zip)

**Comment by vcsjones** [comment]
Release / Debug should not make an impact when loading a PFX file, but, just to be sure, I tried using a simpler program to reproduce the issue:

```csharp
using static System.Console;
using System;
using System.Security.Cryptography.X509Certificates;

#if RELEASE
WriteLine("Release");
#elif DEBUG
WriteLine("Debug");
#endif

try
{
    using X509Certificate2 cert = new("TT.Core.Api.pfx", "bfe4e20f-bcb4-4e95-9c76-9b7bfce2f35e");
    WriteLine(cert.Subject);
}
catch (Exception e)
{
    WriteLine("failed: " + e.Message);
}
```

I am unable to load this PFX/PKCS12 using the password for all combinations of netcoreapp3.1 and netcoreapp2.2.

```
/code/personal/scratch > dotnet run --framework netcoreapp2.2 -c release
Release
failed: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
 /code/personal/scratch > dotnet run --framework netcoreapp2.2 -c debug  
Debug
failed: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
 /code/personal/scratch > dotnet run --framework netcoreapp3.1 -c release
Release
failed: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
 /code/personal/scratch > dotnet run --framework netcoreapp3.1 -c debug  
Debug
failed: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
```

It seems the password and the file do not match up for all versions of .NET Core.

**Comment by bartonjs** [comment]
Since

* There hasn't been any activity on the issue in a long time
* The error code is coming out of OpenSSL's PKCS12_parse
* We stopped using PKCS12_parse with .NET 5 (wrote our own PFX loader)
* We weren't able to reproduce the error

I'm going to close the issue.
