### ISSUE TITLE
Sequential field offsets differ between .NET Core 3.1 and .NET 5.0 when inheriting from an empty class

### ISSUE THREAD

**Issue by quilan1** [dotnet/runtime#46750]
### Description

In .NET 5.0, when inheriting from an empty class (no fields), the offsets of the child class now seem as if they have a zero-valued 1 byte sized hidden field packed at the beginning (zero offset). This behavior differs from .NET Core 3.1 and affects marshaling across unmanaged code.

Reproduction Code:

```
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential)]
class Empty { }

[StructLayout(LayoutKind.Sequential)]
class Test : Empty {
    public Int32 field0;
}

class Program {
    static void Main(string[] args) {
        PrintObj(new Test());
    }

    static void PrintObj<T>(T obj) {
        var tType = typeof(T);
        Console.WriteLine($"Class: {tType.Name}, Size: {Marshal.SizeOf(obj)} bytes");
        foreach (var field in tType.GetFields()) {
            var name = field.Name;
            Console.WriteLine($"Offset {Marshal.OffsetOf(tType, name):X2}: {name}");
        }
    }
}
```

When run with the `netcoreapp3.1` or `netcoreapp2.1` framework, this yields:

> Class: Test, Size: 4 bytes
> Offset 0: field0

Running with `net5.0` yields:

> Class: Test, Size: 8 bytes
> Offset 04: field0

### Configuration

* **Which version of .NET is the code running on?** Tested with .NET Core 2.1, 3.1 and .NET 5.0
* **What OS and version, and what distro if applicable?** Tested on Windows 10, multiple machines w/ different OS builds
* **What is the architecture (x64, x86, ARM, ARM64)?** x64
* **Do you know whether it is specific to that configuration?** I do not.

### Regression?

This is a regression from at least .NET Core 3.1. Also tested with .NET Core 2.1, which yields the same (expected) behavior as 3.1.

**Comment by jkotas** [comment]
cc @jkoritzinsky

**Comment by andrew-boyarshin** [comment]
#46663?

**Comment by quilan1** [comment]
Ahh yes, this looks to be the same issue as #46643. I'll close this, as it's a duplicate.
