### ISSUE TITLE
wasm AOT library test failure - SystemSecurityCryptographyEncoding_PlatformNotSupported

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46762]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Security.Cryptography.Encoding/tests/System.Security.Cryptography.Encoding.Tests.csproj` fails with 
```
System.PlatformNotSupportedException : SystemSecurityCryptographyEncoding_PlatformNotSupported
```
[system_security_cryptography_encoding_fail.txt](https://github.com/dotnet/runtime/files/5788921/system_security_cryptography_encoding_fail.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Security.Cryptography.Encoding/tests/System.Security.Cryptography.Encoding.Tests.csproj`

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
