### ISSUE TITLE
[wasm] `EnableAggressiveTrimming` causing failing tests - `System.Diagnostics.Tests.ActivityTest`

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46768]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Diagnostics.DiagnosticSource/tests/TestWithConfigSwitches/System.Diagnostics.DiagnosticSource.Switches.Tests.csproj` fails with 
```
  fail: [FAIL] System.Diagnostics.Tests.ActivityTests.ActivityIdNonHierarchicalOverflow
  info: Assert.InRange() Failure
  info: Range:  (55 - 56)
  info: Actual: 27
  info:
  fail: [FAIL] System.Diagnostics.Tests.ActivityTests.IdFormat_ZeroTraceIdAndSpanIdWithHierarchicalFormat
  info: Assert.Equal() Failure
  info: Expected: Hierarchical
  info: Actual:   W3C
  info:
  fail: [FAIL] System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalIsDefault
  info: Assert.Equal() Failure
  info: Expected: Hierarchical
  info: Actual:   W3C
  info:
  fail: [FAIL] System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent
  info: System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.
  info:
  info: Finished:    System.Diagnostics.DiagnosticSource.Switches.Tests.dll
```
[System_diagnostics_diagnosticsource_switches_fail.txt](https://github.com/dotnet/runtime/files/5789199/System_diagnostics_diagnosticsource_switches_fail.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Diagnostics.DiagnosticSource/tests/TestWithConfigSwitches/System.Diagnostics.DiagnosticSource.Switches.Tests.csproj`

**Comment by radical** [comment]
`[FAIL] System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent`
- this needs to be disabled with `IsThreadingSupported` (https://github.com/dotnet/runtime/pull/46875)

Others I can reproduce with `/p:EnableAggressiveTrimming=true`, and no AOT compilation.
