### ISSUE TITLE
wasm AOT library test failure - function signature mismatch

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46761]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.ValueTuple/tests/System.ValueTuple.Tests.csproj` fails with 
```
  info: JS exception: RuntimeError: function signature mismatch
  info: RuntimeError: function signature mismatch
```
[system_valuetuple_fail.txt](https://github.com/dotnet/runtime/files/5788913/system_valuetuple_fail.txt)

Repro:
Check out changes in
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.ValueTuple/tests/System.ValueTuple.Tests.csproj`

**Comment by vargaz** [comment]
Can't reproduce this with master anymore.
