### ISSUE TITLE
wasm AOT library test failure - unreachable

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46766]
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Runtime.CompilerServices.Unsafe/tests/System.Runtime.CompilerServices.Unsafe.Tests.csproj` fails with 
```
  info: JS exception: RuntimeError: unreachable
  info: RuntimeError: unreachable
```
[system_runtime_compilerservices_unsafe_fail.txt](https://github.com/dotnet/runtime/files/5789139/system_runtime_compilerservices_unsafe_fail.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Runtime.CompilerServices.Unsafe/tests/System.Runtime.CompilerServices.Unsafe.Tests.csproj`

**Comment by vargaz** [comment]
These tests fail:
            Assert.Throws<NullReferenceException>(() => Unsafe.NullRef<int>() = 42);
            Assert.Throws<NullReferenceException>(() => Unsafe.NullRef<int>());

The first one is fixed by the referenced PR. Not sure why the second should work, the anon method is converted to the following IL:
      IL_0000:  call       !!0& [System.Runtime.CompilerServices.Unsafe]System.Runtime.CompilerServices.Unsafe::NullRef<int32>()
      IL_0005:  pop
which shouldn't cause a nullref imho.

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
