### ISSUE TITLE
System.Security.Cryptography.Native.Openssl should not load OpenSSL eagerly on macOS

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#46771]
OpenSSL is optional on macOS - it's needed only for AES-GCM/CCM encryption. 

However we have  `__attribute__((constructor)) static void InitializeOpenSSLShim()` which aborts if OpenSSL is not found.
As a result, when `System.Security.Cryptography.Native.Openssl` is statically linked in a single-file scenario, _every_ app will probe for OpenSSL and fail if not found.

We need to either delay-load on first use or invoke initialization explicitly from managed code.

**Comment by am11** [comment]
Related #46076.

> delay-load on first use

like libgdiplus https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs#L29
would be great!

**Comment by EgorBo** [comment]
BTW, can we use https://developer.apple.com/documentation/cryptokit on mac? it should support AES-GCM/CCM so we can drop this OpenSSL requirement completely on macOS.
cc @bartonjs

**Comment by bartonjs** [comment]
> BTW, can we use https://developer.apple.com/documentation/cryptokit on mac? ... ObjC

My understanding is that CryptoKit only has Swift bindings, no Objective C bindings.  I found references to being able to call into "Swift-only" things from Objective C using some sort of Xcode-generated header, but nothing talking about how to do it outside of Xcode or what the calling conventions would look like for instance functions.

If someone can figure out how to call it from the Apple crypto shim, then sure!

**Comment by bartonjs** [comment]
> InitializeAppleCryptoSslShim

That function is in System.Security.Cryptography.Native.Apple, which doesn't link to OpenSSL.

On macOS both shims can be used.  System.Security.Cryptography.Native.Apple is the only one used in the majority of programs that need any crypto.  System.Security.Cryptography.Native.OpenSsl gets loaded when the AesGcm or AesCcm types are used, or any of the types whose name explicitly ends in "OpenSsl", (e.g. RSAOpenSsl).  I don't really expect that anyone is using the *OpenSsl types from macOS, we might be able to drop support for them (from macOS) in 6 if we have reasons.

**Comment by VSadov** [comment]
Right - the problem is not `InitializeAppleCryptoSslShim`, it is the `InitializeOpenSSLShim`

Both have `__attribute__((constructor))`, so I got confused. Initially I thought both functions cause the trouble.
Only `InitializeOpenSSLShim` aborts if the library is not found.

**Comment by VSadov** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/46640
