### ISSUE TITLE
AllowPartiallyTrustedCallers on Microsoft.Bcl.HashCode for 4.6.1

### ISSUE THREAD

**Issue by lbargaoanu** [dotnet/runtime#46782]

**Comment by eiriktsarpalis** [comment]
According to [this issue](https://github.com/dotnet/runtime/issues/30709) the particular packages have been deprecated for net5.0. I'm not sure whether this is the kind of fix that might justify servicing 3.1 cc @danmosemsft

**Comment by lbargaoanu** [comment]
I can always copy paste the code in my project :) Just thought maybe there is a better way.

**Comment by ericstj** [comment]
Can you explain why you need to set APTCA?  In general we don't recommend the use of partial trust at all any more and none of the new .NET libraries bother with security attributes.  cc @joperezr @bartonjs

**Comment by lbargaoanu** [comment]
It's an old library that targets 4.6.1 and .Net Standard (AutoMapper). We already have APTCA. So if we want to use Bcl.HashCode, it would be nice if it had APTCA. Otherwise I think we would need to add attributes everywhere we use it. APTCA is the only one we have now.
