### ISSUE TITLE
[NET 5.0] GDI resource leak in Graphics.DrawIcon method

### ISSUE THREAD

**Issue by ymalich** [dotnet/runtime#46789]
* .NET Core Version: 
NET 5.0.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Hello, 
I've encountered the GDI resource leak in my WinForms application after I targeted it to NET 5.0.
I've found in debugger the leak is in the method Graphics.DrawIcon.
After maximum GDI objects count is reached, the application crashes with System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
I use the method Graphics.DrawIcon in DataGridView.CellPainting, therefore my users get the GDI+ exception very soon, as they scroll my DataGridView.

**Expected behavior:**
There is no memory/GDI resource leak if the application is targeted to NET Core 3.1 or net472. 

**Minimal repro:**
I've added the file with solution WindowsFormsApp1GdiLeak.zip, which you can use to reproduce the bug easily.
1. Open Windows Task Manager
2. Go to Details Tab
3. Open context menu on Headers an click Select columns
4. Add "GDI objects" column
5. Open solution WindowsFormsAppWeb1.sln
6. Set the break point on the loop 
for (int i = 0; i < 5000; i++)
            {
                g.DrawIcon(icon, 100, 100); // GDI leak here
            }
7. Run the application and check GDI objects in Task Manager before and after the loop.
8. Re-target the project to NET Core 3.1, run again and check GDI objects again.

[WindowsFormsApp1GdiLeak.zip](https://github.com/dotnet/winforms/files/5791375/WindowsFormsApp1GdiLeak.zip)

**Comment by safern** [comment]
Re-opening to track the 5.0.x port.

**Comment by safern** [comment]
This is already fixed.
