### ISSUE TITLE
[HTTP/3] Add tests - HttpVersionPolicy.RequestVersionOrHigher does not work

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#46797]
I was able to successfully make a HTTP/3 call using HttpClient by following the instructions at https://github.com/dotnet/runtimelab/tree/feature/System.Net.Experimental.MsQuic

However when I changed the request to use RequestVersionOrHigher + HTTP/2, the protocol used was HTTP/2.

```cs
new HttpRequestMessage
{
    Version = new Version(2, 0),
    VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
}
```

---

**UPDATE:** Upgrading appears to be working from tests in ASP.NET Core. Tests should be added to runtime.

**Comment by JamesNK** [comment]
This is still an issue after Kestrel has been updated to return h3-29 in 6.0 daily builds.

**Comment by karelz** [comment]
Triage: We didn't test this scenario, so we should look into it in 6.0.

**Comment by karelz** [comment]
Seems to be addressed now.
