### ISSUE TITLE
where is  PackageDigitalSignatureManager in .net 5

### ISSUE THREAD

**Issue by cnkker** [dotnet/runtime#46799]
where is  PackageDigitalSignatureManager in .net 5

https://docs.microsoft.com/en-us/dotnet/api/system.io.packaging.packagedigitalsignaturemanager?view=net-5.0

![20210111162745](https://user-images.githubusercontent.com/6811256/104159248-fa05ab80-5429-11eb-93bf-217c8a45d0a0.png)

**Comment by huoyaoyuan** [comment]
It's in WindowsBase, which is a WPF component. It requires `<UseWPF>true</UseWPF>` in project file.
