### ISSUE TITLE
Implement proper interop to PInvoke for structs contataining an object ref

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/runtime#4679]
Currently on Windows the CLR uses a VARIANT type to pass the object ref to the native PInvoke.
For non Windows systems it throws a TypeInitializationException.

After discussing with interop team a work is underway to either throw UnsupportedException or to properly marshal the obj ref.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky We throw `NotSupportedException` right? I think this issue can finally be closed.

**Comment by jkoritzinsky** [comment]
I believe we throw a MarshalDirectiveException, but I need to check.

**Comment by jkotas** [comment]
We throw `System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #1': Invalid managed/unmanaged type combination (Marshaling to and from COM VARIANTs isn't supported).`. I do not see anything to fix here.
