### ISSUE TITLE
File not released when exception occurs in Package.Open

### ISSUE THREAD

**Issue by igitur** [dotnet/runtime#46791]
### Description

When I try to call `Package.Open` on an invalid package (file attached), the file lock is not released. The subsequent `File.Move` throws an `IOException`: `The process cannot access the file because it is being used by another process`

```c#
using System.IO;
using System.IO.Packaging;

internal class Program
{
    private static void Main(string[] args)
    {
        try
        {
            using var package = Package.Open("PdfWithFakeExtension.xlsx", FileMode.Open, FileAccess.Read, FileShare.Read);
        }
        catch
        {
            // Swallow exception
        }

        File.Move("PdfWithFakeExtension.xlsx", @"C:\temp\PdfWithFakeExtension.xlsx");
    }
}

```
### Configuration

* Which version of .NET is the code running on?
`netcore3.1`

* What OS and version, and what distro if applicable?
`System.IO.Packaging` version 5.0.0
* What is the architecture (x64, x86, ARM, ARM64)?
`AnyCPU`

### Regression?

Yes, I think this is a regression. Using a `net472` build and using `WindowsBase` instead of the `System.IO.Packaging` NuGet package, the file is released, so I don't experience this problem.

### Other information

[PdfWithFakeExtension.xlsx](https://github.com/dotnet/runtime/files/5792595/PdfWithFakeExtension.xlsx)

**Comment by huoyaoyuan** [comment]
> * Which version of .NET is the code running on?
>   `netstandard2.1`

This doesn't refer to the target framework of the library containing this, but the entry executable. Should be .NET Core 3.x or .NET 5. netstandard isn't runnable.

**Comment by igitur** [comment]
> > * Which version of .NET is the code running on?
> >   `netstandard2.1`
> 
> This doesn't refer to the target framework of the library containing this, but the entry executable. Should be .NET Core 3.x or .NET 5. netstandard isn't runnable.

Updated to `netcore3.1`

**Comment by AaronRobinsonMSFT** [comment]
@danmosemsft @ericstj @stephentoub Unsure how to tag this.

**Comment by danmosemsft** [comment]
In .NET Framework the stream is closed on exception here
https://referencesource.microsoft.com/#WindowsBase/Base/MS/Internal/IO/Zip/ZipArchive.cs,109

The .NET Core code seems to have a different heritage as it is rather different, and it does not close the stream here
https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/ZipPackage.cs,283

If the object had been successfully created, it would have closed the stream in Dispose().

**Comment by danmosemsft** [comment]
As a workaround @igitur you could of course create your own FileStream around the path, and hand Package.Open that stream.

**Comment by HalHaynes** [comment]
> As a workaround @igitur you could of course create your own FileStream around the path, and hand Package.Open that stream.

I wondered whether that would work. (I'm the person on behalf of whom @igitur raised the issue here.) But although that would allow me always to unlock the file, might that just shift the problem to the FileStream, leaving it undisposed and creating a leak?

**Comment by danmosemsft** [comment]
@HalHaynes 

>  In other words, is this problem also present in the constructor that takes a stream argument as well as in the one that takes a file path argument?

I don't think so. That code flow is
https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/Package.cs,905
to
https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/ZipPackage.cs,348
the true in `zipArchive = new ZipArchive(s, zipArchiveMode, true, Text.Encoding.UTF8);` is a boolean `leaveOpen`. It indicates that ZipArchive should not close the stream when disposed.

As for ZipPackage, it sets a boolean `_shouldCloseContainerStream` here
https://source.dot.net/#System.IO.Packaging/System/IO/Packaging/ZipPackage.cs,368
which in turn means that it will not close the stream when disposed.

I think in general it is unusual for an API to close a stream it is passed. I would think that is normally the responsibility of the caller, who may have other things they wish to do with the stream.

LMK if you hit a problem.

**Comment by danmosemsft** [comment]
Note that this fix would be for .NET 6 to release in November. With a reasonable workaround, I don't believe this would meet the bar to service older versions.

BTW welcome to our repo @HalHaynes

**Comment by HalHaynes** [comment]
Thanks! I tried the work-around and it was successful.
