### ISSUE TITLE
System.Text.Json: .NET 5.0 perf regression serializing nested object

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#46795]
### Description

That simple program...

```csharp
		public static int Main()
		{
			TestClass test = new TestClass
			{
				Data = new Dictionary<string, string>
				{
					["Key1"] = "Hello world",
					["Key2"] = null
				}
			};

			for (int i = 0; i < 100000; i++)
			{
				JsonSerializer.Serialize(test);
			}

			return 0;
		}

		internal class TestClass
		{
			public IDictionary<string, string> Data { get; set; }
		}
```

* Shows these allocations on .NET Core 3.1:

![image](https://user-images.githubusercontent.com/28367120/104135386-eb919400-5344-11eb-84e4-0c9d64dd3aaa.png)

* Shows these allocations on .NET 5:

![image](https://user-images.githubusercontent.com/28367120/104135397-ffd59100-5344-11eb-80fe-256232fe9273.png)

### Configuration

Running this on Windows x64.

### Analysis

The code has changed a lot between releases so I didn't want to attempt a fix without guidance. What I could find...

* Current code does this state push anytime the type being written is an object:

https://github.com/dotnet/runtime/blob/af1e7ee4678d2322a53efce43bc3b6ee16b7f715/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L374

* The 3.1 code has a conditional for that state push:

https://github.com/dotnet/corefx/blob/aae1eab04d154a198c0e254ca003277f5079e484/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.HandleObject.cs#L149-L160

/cc @steveharter @layomia

**Comment by steveharter** [comment]
In 3.x, "object" and "dictionary" each had their own variables in the "stack" types, so a "push" wasn't necessary in this particular example. [Here's the check](https://github.com/dotnet/corefx/blob/aae1eab04d154a198c0e254ca003277f5079e484/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.HandleObject.cs#L116-L117) that says that.

In 5.0, all object and collection types are now treated the same and each get their own stack frame, so this is an expected regression based on that. However, it is possible to add additional state and prevent the "push" for first-level collections as in 3.0 if it was decided this "small object" scenario is important.

However, 5.0 has faster performance once more elements are added. Modifying the original test above slightly:
```cs
for (int i = 1; i <= 1000; i *= 10)
{
	TestClass test = new TestClass()
	{
		Data = new Dictionary<string, string>()
	};

	for (int j = 0; j < i * 2; j += 2)
	{
		test.Data["Key" + j.ToString()] = "Hello world";
		test.Data["Key" + (j + 1).ToString()] = null;
	}

	var sw = new Stopwatch();
	sw.Start();

	for (int k = 0; k < 100000; k++)
	{
		JsonSerializer.Serialize(test);
	}
	sw.Stop();

	Console.WriteLine($"Elements:{i * 2} time:{sw.ElapsedMilliseconds}");
}
```
results in:
```
3.1 results:
Elements:2 time:136
Elements:20 time:396
Elements:200 time:2700
Elements:2000 time:27618

5.0 results:
Elements:2 time:151
Elements:20 time:299
Elements:200 time:1656
Elements:2000 time:16877
```

The point where 5.0 becomes faster is around 6 elements. Once you get to 200 elements, 5.0 is ~1.6x faster.

**Comment by CodeBlanch** [comment]
@steveharter For a little context, what I'm working on here is a logger that writes messages out as JSON. In this case, many many tiny dictionaries for the state attached to the message. Also tiny collections for the scopes, if used.

**Comment by steveharter** [comment]
I think a reasonable approach to improving perf here (for small objects and collections where such smallish optimizations will show up) is to remove the List\array creation for WriteStack\ReadStack and instead have each WriteStackFrame\ReadStackFrame have a reference to the previous frame (and perhaps the next frame). So the WriteStack\ReadStack references the current frame (like today) but not a List\array.

Also these structs could also be changed to `ref structs` and leverage the new C# capability for a `ref struct` to have a field to another `ref struct`.

**Comment by eiriktsarpalis** [comment]
Seems like this is by-design behavior and we can close the issue?

**Comment by CodeBlanch** [comment]
@eiriktsarpalis Not sure. The way I read @steveharter's explanation, it was an unintended regression for one case while trying to improve another. The idea for the fix using a pointer instead of a list allocation also sounds generally like a good improvement.
