### ISSUE TITLE
Fix the disabled tests in the System V struct passing tests when Issue #2075 is resolved

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/runtime#4680]
Once the issue dotnet/runtime#4679 is resolved enable the commented out tests in System V bringup tests in JIT/Methodical/structs and make them test the right thing.

category:correctness
theme:testing
skill-level:beginner
cost:small

**Comment by jkoritzinsky** [comment]
Closing as https://github.com/dotnet/runtime/issues/4679 was also closed

**Comment by ericstj** [comment]
Reactivating to delete this test:

https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/tests/JIT/Methodical/structs/systemvbringup/structpinvoketests.cs#L171-L175
