### ISSUE TITLE
[wasm] Enable tests on Safari

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#46813]
Based on @lewing's suggest in https://github.com/dotnet/runtime/pull/46784#pullrequestreview-565523088

**Comment by radical** [comment]
What do we need to do for this?

**Comment by radical** [comment]
xharness part: https://github.com/dotnet/xharness/pull/411

**Comment by kjpou1** [comment]
Closed by https://github.com/dotnet/xharness/pull/411
