### ISSUE TITLE
Double.Parse rounding bug when there are trailing zeroes in the input string

### ISSUE THREAD

**Issue by jfd16** [dotnet/runtime#46827]
### Description
Code to reproduce:
```csharp
using System;

class Program {
    public static void Main(string[] args) {
        Console.WriteLine("{0:R}", double.Parse("9007199254740997"));
        Console.WriteLine("{0:R}", double.Parse("900719925474099.7e+1"));
        Console.WriteLine("{0:R}", double.Parse("9007199254740997.0"));
        Console.WriteLine("{0:R}", double.Parse("90071992547409970e-1"));
    }
}
```

Actual output:
```
9007199254740996
9007199254740996
9007199254740998
9007199254740998
```
Expected: All four outputs should be the same. (9007199254740996 if rounding to even)
### Configuration

* Which version of .NET is the code running on? .NET 5
* What OS and version, and what distro if applicable? Windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No

**Comment by pgovind** [comment]
Looks like a bug. I'll investigate this as I work on https://github.com/dotnet/runtime/issues/46874 next week!

**Comment by pgovind** [comment]
Yup, reproduced it locally. Will look into this further this week
