### ISSUE TITLE
Expose SafeHandle method for flipping handle / file descriptor inheritability

### ISSUE THREAD

**Issue by webczat** [dotnet/runtime#46832]
Hi,
Was curious about implementation of systemd support in aspnetcore/kestrel, as in support for socket activation, so read sources and did some experiments.
I noticed you are, likely intentionally, not using systemd api to get file descriptors, but directly reading underlying environment variables described in respective manpages.
However there seems to be one thing you are not doing there that libsystemd is, that is, when it is known how many file descriptors are passed, `sd_listen_fds` sets close on exec (`O_CLOEXEC) on each of them to prevent them being inherited across execve.
Because it is not done, all listener sockets passed by systemd will leak to executed child programs, and SafeSocketHandle and Socket constructors also don't do it for preexisting handles. I know that is not the case for any socket created directly by kestrel, because all sockets created without a preexisting handle have inheritance disabled.
I've tested that I am right by trying to check fd info for the respective systemd-passed fd (number 3), and it indeed has no cloexec set. And sockets that are directly created do have it set, from what I can tell.
Not fully sure if it is something for this repo, or if the socket constructor (or SafeSocketHandle constructor) should deal with this instead.

**Comment by shirhatti** [comment]
@wfurt Is this something the runtime should set in FileHandle Socket ctor?

**Comment by stephentoub** [comment]
>  Is this something the runtime should set in FileHandle Socket ctor?

I don't think so.  In such a case we're being given an already created / already configured handle and told to work with it.  We're in no position to say that the creator didn't intend for it to be inherited.

**Comment by shirhatti** [comment]
Then maybe we make it configurable? There's no managed API to prevent the socket from being leaked to child processes right now

**Comment by stephentoub** [comment]
This socket fd isn't being created by System.Net.Sockets.Socket, and such CLOEXEC functionality has little to do with a ctor that wraps a Socket around an existing descriptor.  It doesn't make sense to me to put such control there. The onus here is on the code creating the fd... there's no built-in managed API to create a systemd socket,  either,  but code is still doing it. 

If the goal is,  rather,  to expose a new method somewhere that makes an arbitrary SafeHandle non inheritable (e.g. wrapping fcntl on Linux and SetHandleInformation on Windows), that's a reasonable discussion to have.

**Comment by shirhatti** [comment]
> If the goal is, rather, to expose a new method somewhere that makes an arbitrary SafeHandle non inheritable (e.g. wrapping fcntl on Linux and SetHandleInformation on Windows), that's a reasonable discussion to have.

I like the suggestion. The original issue could solved by Kestrel calling this API that wraps fcntl.

@halter73 👀

**Comment by wfurt** [comment]
if this comes in as existing handle,. Socket code does just enough to make it usable with Socket API. Even that is sometimes difficult and since do now know much about the socket, I don't think we should make arbitarry changes to it. 
The interaction with systemd seems like a special case and perhaps should be handled via helper method. Note, that this is not atomic so the descriptor can still leak if child is forked before the call is made.

**Comment by tmds** [comment]
> However there seems to be one thing you are not doing there that libsystemd is, 

Because it isn't causing issues for anyone, I think we we don't need to go out of our way to behave the same as `sd_listen_fds`.

**Comment by webczat** [comment]
> > However there seems to be one thing you are not doing there that libsystemd is,
> 
> Because it isn't causing issues for anyone, I think we we don't need to go out of our way to behave the same as `sd_listen_fds`.

Seems to be a time bomb. I believe there were bugs related to close on exec not set on some systems causing socket leaks in case where aspnetcore app runs a new process and then exits, for example. Here we have a possible socket leak related to listening sockets when they are handed over from systemd for exactly same reason.

**Comment by tmds** [comment]
Yes, without close on exec there can be child processes keeping handles alive.
In this case, we can count on systemd to kill all child processes.

**Comment by webczat** [comment]
first, isn't it a security issue that child processes can tinker with our listening socket? what can they actually do with it? I am really not sure about the answer, and it is definitely unexpected behavior from child process point of view.
Usually wouldn't break them, except it's another fd counting towards max fd limit, not like one listening socket is much, so that's another side of it.
Second, I believe you can actually make systemd not autokill child processes and consider service stopped only after all of them die.
Third, better to be consistent. Sockets created any other way are already marked cloexec, and this was important enough before to fix the cases where it was not happening, although I believe it affected connection sockets, not listening sockets. Not sure how to find the relevant issue, even though I was reading it before reporting this one/verifying cloexec not being set.
Fourth, it actually seems to be a recommendation in systemd, as in the manpage of sd_listen_fds not only describes the function but also describes in detail what it is doing, and the setting cloexec on inherited fds does make a lot of sense.

**Comment by tmds** [comment]
I don't mind if you (or someone else) wants to set the close-on-exec flag in kestrel to mimic `sd_listen_fds` behavior.

**Comment by webczat** [comment]
and indeed, it would make sense I believe. the thing is, someone decided to move it here :) my first idea was this could be done by kestrel, especially that this is something needed for linux and linux only, only for systemd, and the needed constants are generic (as in not arch specific) so it can be safely dllimported. The other idea here was to have an api that allows enabling/disabling handle inheritance.

**Comment by karelz** [comment]
Triage: This is not specific to sockets. We should expose API on `SafeHandle` instead - general one.

**Comment by tmds** [comment]
@shirhatti opened https://github.com/dotnet/aspnetcore/issues/30079 to fix it for the systemd use-case in Kestrel using DllImport.

I also think we can close this.

**Comment by tannergooding** [comment]
Closing this based on the above feedback
