### ISSUE TITLE
is there any zero-copy sockets api in .net ?

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#46848]
base on this article https://zhuanlan.zhihu.com/p/78869158 ,  it said that Kafka use those 0-copy tech to support height performance.

### non-0-copy:
```
[disk]------->[os cache] ------>[user buffer] -----> [socket buffer (os cache)] ------> ( network card)
       copy               copy                  copy                         copy
```
### 0-copy
```
[disk] ------> [os cache]  ---->  [  user  symbol ] ------>  [os cache symbol]  ----->( network card)
        copy            no-copy                  no-copy                      copy
```

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/7ffe282af85c6d5ab3f98e6959df39aec9d5ed0f/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Windows.cs#L395-423
https://github.com/dotnet/runtime/blob/7ffe282af85c6d5ab3f98e6959df39aec9d5ed0f/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Unix.cs#L198-237

For `Socket.SendFile`, current implementation does load file into application buffer.
It's an opportunity to optimize on OS supporting such operations. However, it requires OS support for many exact scenarios.

Generally, .NET prefer usability for common API. No "guaranteed high performance" APIs for IO.
Optimizations can be done when not changing API surface. For example, `Socket.SendFile` carries enough information for optimization.
It's more important to let common application framework, for example static file middleware in ASP.NET, calling the optimized path.

**Comment by gfoidl** [comment]
> For `Socket.SendFile`, current implementation does load file into application buffer.

The FileStream gets opened and the handle for that stream is passed to the underlying OS-API.
So the filecontent isn't loaded (by .NET) into an application buffer. It depends on the OS.

For Unix this goes down to [sendfile](https://man7.org/linux/man-pages/man2/sendfile.2.html).
For Windows this goes down to [TransmitFile](https://docs.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile).

**Comment by huoyaoyuan** [comment]
Well, I didn't mention the call to `SocketPal.SendFile`. So it is already optimized.
Other APIs can be optimized by similar pattern.

**Comment by John0King** [comment]
@huoyaoyuan  @gfoidl @jkotas   I'm wonder does this tech can only be use with `Socket` ?  

from what I know,  the `symbol`  passed by os cache layer to user code layer  is like `Stream pointer` or much simple like `IntPtr`,   and I think it can be use like from  file to file copy (not sure that OS support it or not) and  network to file copy.

I mean,  can we have a type of this?  

```C#
var  fileSymbol  file1 = new StreamReadSymbol("C:\file1.mp4");  // or `TransferChannel`

var  file2Symbol file2 = new StreamWriteSymbol("C:\file2.cache");

//  read the file1
FileStream fs = file1.GetStream(); //  user layer read

// direct copy

file2.Write(file1)


// user case

Stream.CopyToAsync()
```

**Comment by wfurt** [comment]
While most of the linked article is not  quite readable, "sendfile" string seems to appear and the question seems to be answered. 

I'm not sure if you are trying to duplicate files, but I don't think there is good portable way how to do that AFAIK. not even considering cross-volume copy.

**Comment by huoyaoyuan** [comment]
@John0King you should be referencing file handles.
As @gfoidl explained, creating a FileStream just opens the handle from OS. It won't load the file's content until you start to read it.

> and this allow us mock the behavior when the os not support

You shouldn't. This should be handled by the platform, namely `ConsolePal`.
