### ISSUE TITLE
Developers can control TLS establishment in SocketsHttpHandler via a callback

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#46849]
- [ ] Enable SocketsHttpHandler.ConnectCallback to negotiate TLS - #42455

**Comment by geoffkizer** [comment]
The title here is a bit confusing. 

Do we want to enable a new callback to control TLS establishment? This seems reasonable and is pretty straightforward, something like SocketsHttpHandler.EstablishTlsCallback.

Or do we want to do something more complicated, that allows TLS "pre-negotiation" -- by which I assume we are pre-establishing TLS connections?

Or something else?

**Comment by karelz** [comment]
@geoffkizer it is user story for #42455 -- happy to change wording if you have better suggestion.
The goal is to allow developers to do custom TLS negotiation themselves for API like ConnectCallback

**Comment by geoffkizer** [comment]
I edited the title, feel free to edit further.

**Comment by wfurt** [comment]
Would we expect that the EstablishTlsCallback be given Stream and it would return SslStream @geoffkizer? And would that be on top of ConnectCallback or would it be mutually exclusive e.g. call one or the other based on the URI schema?

**Comment by karelz** [comment]
We decided to favor LLHTTP over this enhancement in 6.0. Closing this issue, the underlying real work is now in Future.
