### ISSUE TITLE
Wrong nullable annotations on XElement constructor

### ISSUE THREAD

**Issue by mbashov** [dotnet/runtime#46854]
[`System.Xml.Linq.XElement(XName, object[])`](https://github.com/dotnet/runtime/blob/v5.0.1/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs#L95) should allow `object?[]` or maybe even `object?[]?` as the second parameter. The constructor passes the argument to the method [`AddContentSkipNotify`](https://github.com/dotnet/runtime/blob/v5.0.1/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XContainer.cs#L468), which seems to work with nulls in the array by ignoring them.

**Comment by stephentoub** [comment]
Thanks.  This is a dup of https://github.com/dotnet/runtime/issues/43416, and it's been fixed in master.
https://github.com/dotnet/runtime/blob/129c8ca06935da5fe52afd3faf682d98b522485a/src/libraries/System.Private.Xml.Linq/src/System/Xml/Linq/XElement.cs#L95
