### ISSUE TITLE
Improved Logical Shift for BitArray Collection

### ISSUE THREAD

**Issue by TourajOstovari** [dotnet/runtime#46871]
## Background and Motivation

Hello, I want while doing Logical Shift via BitArray collection, enter ‘1’ instead ‘0’.
Can you help me?
Actually while I am using LeftShift or RightShift, enter number of counts and which bit should enter? like ‘0’ or ‘1’.
Current default value of logical shift is ‘0’ bit.
Thanks.

## Proposed API

```diff
namespace System.Collections.BitArray
{
    public class BitArray {
+ public void LeftShift(bool value, int count);
+ public void RightShift(bool value, int count);
     }
}
```

## Usage Examples

``` C#
BitArray Array = new BitArray(1024,true);
Array.LeftShift(false,20);
Array.RightShift(true,120);
```

## Risks

No risks

**Comment by eiriktsarpalis** [comment]
Presumably related to #46669. I've never heard of a shift operation where you get to pick the value of inserted bits, logical shifts by definition always insert zeroes. @tannergooding could know if this exists and what it might be called.

**Comment by danmosemsft** [comment]
@TourajOstovari what are you trying to achieve - why do you need this? We have to figure for any API whether it is broadly useful.

**Comment by TourajOstovari** [comment]
I need it for cryptography and self padding mode and makes my function none linear in details too

**Comment by danmosemsft** [comment]
> makes my function none linear in details too

Could you clarify?

Also, could you give more info about "cryptography and self padding mode" ? Amongst other things, we need to determine how broadly useful such a new API is. Each new API has a cost.

cc @bartonjs

**Comment by TourajOstovari** [comment]
Look my friend when you are doing shift logical with zero digit while you want xor it with new binary digit so your xored digit would repeat and appear exactly and while your logical shift is 1 binary digit, your xored result would be minus and a little hard to solve puzzle and helps for more none linear result ( helps for more security )
My first block's padd is digit one but while I want compressing data ( for short form ) to make hash so I need logical shift too for making blocks one way.
