### ISSUE TITLE
Big and Custom Matrix self defined dimensions

### ISSUE THREAD

**Issue by TourajOstovari** [dotnet/runtime#46872]
## Background and Motivation

Hello, it could be better to have self defined matrix’s dimensions that contains numbers as Char ,HEX, Byte, Binary for cryptography.
for example it can hold values and user can do rotate shift on rows and columns.
also a method that is doing logical shift on current matrix and asks the value that user wants to enter while doing logical shift for example enter ‘FF’ and number of times while calling logical shift method (And which rows or columns should be shift as rotate or logical)
current classes of Matrix with System.numeric namespace is limited and only user can define 3x3 and 4x4 matrix.
it could be perfect doing XOR, AND … with matrix and define to apply (Binary operation be done) on columns or rows of target matrix, for example I have a matrix that each rows would be XOR with columns of target matrix or columns of current matrix would be XOR with rows of target matrix that user should choose it actually is self defined.

## Proposed API

```diff
namespace System.Numeric
{
+    public class Matrix {
+    ctor(int x, int y)
             {     }
+    ctor(int x, int y, int z) {  }
+    public XOR, AND, OR, NOT operations(target Matrix) {}
+    public Matrix GetRow(int index) { }
+    public  Matrix GetColum(int index) {  }
+    and many many other needed methods for cryptography
     }
```

## Risks

No risk.

**Comment by huoyaoyuan** [comment]
Are you looking for [MathDotNet](https://numerics.mathdotnet.com/) ?
Matrix here are focusing on hardware accelerating.

**Comment by TourajOstovari** [comment]
> Are you looking for [MathDotNet](https://numerics.mathdotnet.com/) ?
> Matrix here are focusing on hardware accelerating.

Something like that but mostly suitable for cryptography like AES cryptosystem based on Matrix
Imagine it is doing same operations like BitArray but extended features for encryption or hash.

**Comment by huoyaoyuan** [comment]
As I know cryptography algorithms like AES operate on plain bytes. They don't care about the structure of matrix.
Doing those based on selecting each row or column is extremely inefficient and potentially insecure.

**Comment by TourajOstovari** [comment]
> As I know cryptography algorithms like AES operate on plain bytes. They don't care about the structure of matrix.
> Doing those based on selecting each row or column is extremely inefficient and potentially insecure.

AES is filling data inside matrix like structure that is why we need matrix like structure that contains byte hex binary and char as data.
AES is not more secure with new quantum computers and we need build bigger matrix and bigger key sizes.

**Comment by TourajOstovari** [comment]
As we need bigger structure for hash functions that output is bigger than 256 bits

**Comment by TourajOstovari** [comment]
As we need bigger structure for hash functions that output is bigger than 256 bits.
Are you a MSF developer or cryptographier?
What you want to say with these bullshits?

**Comment by tannergooding** [comment]
Please be mindful of the code of conduct (https://dotnetfoundation.org/about/code-of-conduct) - CC. @terrajobst

Cryptography scenarios in .NET tend to be very specialized and are often relegated to the underlying OS. @GrabYourPitchforks and @bartonjs are the owners/experts for the System.Security area and can likely provide more input.

**Comment by TourajOstovari** [comment]
Excuse me, what is your mean about more inputs?
We need build owns encryption functions but needed matrix like structure for building stronger encryption that quantum computers can not break them also bigger structure like matrix...
MSF is alive by MSF developers so I do not know why you want prevent from doing this job...
I can develop this library but I would say to everyone some lazy staffs are working and they are running from working...

**Comment by tannergooding** [comment]
This is a complex proposal that needs a lot more design work and likely fits in better with the `System.Numerics.Tensor` space that is being explored.

Going to close this for now as we have existing issues/types under Tensors.
