### ISSUE TITLE
DateTimeOffset Json Deserialization Inconsistent Across Time Zones

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#46879]
### Description
When deserializing dates using System.Text.Json, the dates should be deserialized consistently regardless of the timezone of the deserializer's computer.

### Issue
When a TimeZone is not present in the JSON, it is assumed to the the local time zone.  This is incorrect.  It should be assumed to be GMT.  This causes inconsistent results when processing data, and, in some cases, crashes that only occur based on the deserializer's timezone.

### Resolution
When deserializing DateTimeOffsets, if no timezone is present, it should be assumed to be GMT.

### Examples showing inconsistent results:
```
using System;
using System.Threading;

namespace ConsoleApp25 {

    class TestClass {
        public DateTimeOffset Date { get; set; }
    }

    class Program {


        static void Test(string value) {
            try {
                Console.WriteLine("Testing " + value);
                var Data = new {
                    Date = value
                };

                var Text = System.Text.Json.JsonSerializer.Serialize(Data);
                var Data2 = System.Text.Json.JsonSerializer.Deserialize<TestClass>(Text);
                Console.WriteLine("  Passed: " + Data2?.Date);

            } catch (Exception e) {
                Console.WriteLine("  Failed: " + e.Message);
            }

            Console.WriteLine();
        }


        static void Main(string[] args) {

            //fails:
            Test("0001-01-01");  // This passes when PC time zone is set to Z or to anything west of Z (-xx:yy) and fails east of Z (+xx:yy)
            Test("0001-01-01T00:00:00");  // This passes when PC time zone is set to Z or to anything west of Z (-xx:yy) and fails east of Z (+xx:yy)
            Test("0001-01-01T00:00:00+01:00"); 

            //passes:
            Test("0001-01-01T01:01:01Z");
            Test("0001-01-01T01:01:01-01:00");
            Test("0001-01-01T01:01:01+01:00");

        }
    }
}

```

**Comment by mattjohnsonpint** [comment]
ISO 8601 requires that a date and time without an offset be interpreted as local time.  Interpreting it as UTC would be incorrect.

The way to not have inconsistency when dealing with such data is to choose a data type that more closely matches.  Instead of deserializing `"0001-01-01T00:00:00"` to a `DateTimeOffset`, one should deserialize it to a `DateTime` and expect that its `Kind` property will be `DateTimeKind.Unspecified`.

**Comment by eiriktsarpalis** [comment]
This is by design behavior, also mirrored by the implementations of Json.NET and `DateTimeOffset.Parse`.
