### ISSUE TITLE
Add feature switch for ComponentActivator.GetFunctionPointer

### ISSUE THREAD

**Issue by rseanhall** [dotnet/runtime#46880]
See https://github.com/dotnet/sdk/issues/15272. Applications that are started by a custom native host should not be required to add this code in order to be trimmable:

> [DynamicDependency("GetFunctionPointer(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)", "Internal.Runtime.InteropServices.ComponentActivator", "System.Private.CoreLib")]

The other methods in that class do not need a feature switch because they currently do not support self-contained applications.

**Comment by jeffschwMSFT** [comment]
@eerhardt

**Comment by rseanhall** [comment]
Actually, is a feature switch the right answer here? Other feature switches seem to be for situations where the linker needs help in order to trim something, but the problem here is that it's trimming too much.

It seems like there needs to be a new attribute that gets put on a method that is called through `GetFunctionPointer` so that the linker knows not to trim:
1. that method and
1. the delegate for that method and
1. `Internal.Runtime.InteropServices.ComponentActivator.GetFunctionPointer`

**Comment by vitek-karas** [comment]
@rseanhall good point - keeping just the `ComponentActivator` is not enough... the called method has to be kept as well.
The delegate is probably something the method would have to add itself since there's no way the tooling can figure out which delegate to pair with the method. But that should be easy enough to do with `DynamicDependency`.

Right now I think the easiest solution is probably to use `ILLink.Descriptors.xml` - can be embedded into the assembly itself. And root the method and the delegate. It can also root the `ComponentActivator` for now.

**Comment by rseanhall** [comment]
I would expect to be able to specify the delegate in the attribute. Is this attribute likely to be implemented in .NET 6?

**Comment by vitek-karas** [comment]
Right now I would say it's unlikely for .NET 6. There's a workaround - which is not exactly pretty, but it's not complicated either. And this is a relatively niche scenario (not counting that trimming is still experimental for lot of other reasons, not just this one).

**Comment by MichalStrehovsky** [comment]
I don't think we would want to encourage a direction where users need to specify attributes on things they want to preserve and if they forget to specify the attribute, it will lead to "interesting" failure modes at runtime (things might work, or they may not, for seemingly random reasons that change as unrelated parts of the codebase change).

Eventually, if we would like to make trimming _and_ native hosting a supported combination, I would think that the potential way forward would be:

* Introduce an attribute one needs to place on methods accessed from the native code that illink would understand.
* Provide a way to generate strongly typed headers/code in the native language to call the attributed methods

This would ensure that everything that is accessed from native code was accounted for during illink. The raw hosting APIs that take strings with names would be in the "here be dragons" territory. The golden path would be to use the generated strongly typed header (that uses the raw hosting API in the background, but was generated from a descriptor illink can reason about).

**Comment by rseanhall** [comment]
@MichalStrehovsky If we must generate strongly typed headers/code in the native language to proceed, then we might as well close this issue. I can't imagine anyone having the time to invest in that. In my case, WiX precompiles the native host and the end user provides the managed application. The generated code would be thrown away. My current thought is for WiX to provide a source generator that will key off our own custom attribute to generate the method that is called by native code.

I have two pain points with the current behavior:

1. I don't see any way to root a method without `ILLink.descriptors.xml`. I don't think there's any way to merge `ILLink.descriptors.xml` files, so if the user had their own it wouldn't be possible for the source generator to root its method.
1. As I said in the OP, `ComponentActivator.GetFunctionPointer` is an implementation detail of the runtime. I don't want to have to update the source generator if that gets moved somewhere else.

> not counting that trimming is still experimental

Is it still going to be considered experimental in .NET 6? It looked like you guys have planned to spend a lot of time improving it.

**Comment by vitek-karas** [comment]
> Is it still going to be considered experimental in .NET 6? It looked like you guys have planned to spend a lot of time improving it.

We do invest in that area - I can't comment on what the eventual state for the feature will be (I don't know) - I do know that we won't have solved all the hard problems in that area by the time .NET 6 ships.

And there will likely be large differences based on the scenario.

If you build the managed app (or has some control over it) you can pass additional XMLs on the command line. If not and you plan to have source generator, you can inject module constructor to "Root" the necessary code. It's not as clean as having an attribute, but it should work.

I tend to agree with @MichalStrehovsky that the only truly "safe" solution would be to add an attribute and the runtime would have to require that attribute to use the method (regardless of trimming). And we would probably still have to limit to methods which don't use any annotations...

**Comment by rseanhall** [comment]
Is this what you meant? Will that actually preserve the delegate? I don't think of that as a member of the class.

```
public static class NativeHost
{
    [ModuleInitializer]
    [DynamicDependency("GetFunctionPointer(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr)", "Internal.Runtime.InteropServices.ComponentActivator", "System.Private.CoreLib")]
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(NativeHost))]
    public static void noop() { }

    public static int CustomEntryPoint(IntPtr a, IntPtr b) { return 0; }

    public delegate int CustomEntryPointDelegate(IntPtr a, IntPtr b);
}
```

**Comment by vitek-karas** [comment]
Yes - that should work. Delegates are basically nested types  (C# syntax is different, but in IL metadata they're just types).
Just to make sure this works (and keeps on working) I'm adding tests for these in the linker: https://github.com/mono/linker/pull/1766

**Comment by LakshanF** [comment]
This is possible now with `_EnableConsumingManagedCodeFromNativeHosting `(see https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md)

**Comment by rseanhall** [comment]
This appears to have been implemented in https://github.com/dotnet/runtime/pull/52109. Which .NET 6 preview will have this?

**Comment by LakshanF** [comment]
Yes, preview 6 should have this support.
