### ISSUE TITLE
X509Certificate.CreateFromCertFile("symbolic link") fails with an internal exception

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#46891]
### Description

X509Certificate.CreateFromCertFile("symbolic link") fails with an internal exception

the link is valid and refers to a .cer file that can be loaded if its own path is provided rather than the symbolic link path

### Configuration

All .NET versions

### Regression?

No

### Other information

Exception:
Internal.Cryptography.CryptoThrowHelper.WindowsCryptographicException
  HResult=0x80004005
  Message=Unspecified error
  Source=System.Security.Cryptography.X509Certificates
  StackTrace:
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)

Workaround: call OpenSSL libraries instead

We hit this in production. It got right past us in dev.

**Comment by vcsjones** [comment]
This looks like it could be considered a duplicate of https://github.com/dotnet/runtime/issues/27826.

The linked issue uses `X509Certificate2`'s constructor, not `CreateFromCertFile`, but all `CreateFromCertFile` does is delegate to the constructor, anyway.

https://github.com/dotnet/runtime/blob/01ee94b1ec76089eccea5097692d6f1d30997c60/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L202-L204

**Comment by jhudsoncedaron** [comment]
lol that's a dupe alright
