### ISSUE TITLE
Coding style violation in ServiceController.cs

### ISSUE THREAD

**Issue by nxtn** [dotnet/runtime#46902]
#44014 changed the whole file to use two spaces of indentation.

**Comment by danmosemsft** [comment]
@nxtn @MCCshreyas if that's the case do either of you want to offer a PR? Thanks for spotting. I thought we would catch this kind of thing in stylecop during build. Perhaps a rule is disabled.

**Comment by MCCshreyas** [comment]
Ohh, I did not get any warning for this! Umm.
I will get that fixed this weekend! If it's urgent I won't mind if someone else fix it!

**Comment by MCCshreyas** [comment]
@danmosemsft isn't there any editorconfig for all libraries to enforce the rules!?

**Comment by nxtn** [comment]
There is a global [.editorconfig](https://github.com/dotnet/runtime/blob/master/.editorconfig) but it's not used during build.

**Comment by MCCshreyas** [comment]
I don't think VS is reading that editorconfig, otherwise I would get warning about inconsistent spacing!

**Comment by MCCshreyas** [comment]
@danmosemsft is there any way we can check does editorconfig is working with VS or not? So that to avoid issues like spacing in future?

**Comment by danmosemsft** [comment]
We use StyleCop as well -- eg., building a project yesterday it complained that I didn't have a space in `,//` ... perhaps it doesn't enforce 4 spaces yet.

**Comment by danmoseley** [comment]
@MCCshreyas will you have a chance to get to this? Presumably it's a quick one.

**Comment by MCCshreyas** [comment]
Sorry @danmosemsft, I didn't got much time from some past weekends to get this fixed! 😑

Thanks @nxtn for getting this fixed! 👍

**Comment by danmoseley** [comment]
No problem @MCCshreyas and thanks @nxtn ... do we know why it didn't break the build and what it would take to make it do so in future?

**Comment by MCCshreyas** [comment]
@danmoseley and also I am wondering why I didn't got any warning in Visual Studio about the same!?
