### ISSUE TITLE
Potential synchronization issue in String.Create

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#46911]
Strings can be created using the `Create` method. Callers can pass a delegate which mutates string contents in place.

https://github.com/dotnet/runtime/blob/e464963969971f8f1968bdf27248669d624ce29e/src/libraries/System.Private.CoreLib/src/System/String.cs#L363-L378

When reviewing this code it appears to me that there is a potential synchronization issue: Due to memory reordering, the newly created string could be published to other threads before the contents are published. This could lead other threads to observe the contents of strings as changing. This violates a fundamental invariant of the runtime.

This issue could cause the following assertion to fire:

```
static string s; // Initialized on another thread using String.Create

//...

string sLocalCopy = s;
Debug.Assert(sLocalCopy[0] == sLocalCopy[0]); // Might be false
```

**Comment by huoyaoyuan** [comment]
> could be published to other threads before the contents are published

How can it?

The initialization action delegate and publication should happen on the same thread.

In your sample, I think you should get NullReferenceException.

**Comment by GSPP** [comment]
That example is not meant to be executable. Imaging initialization happening in an infinite loop and reading done on another thread in an infinite loop as well catching NREs.

Memory reads and writes can be reordered. This means that the string can exist before the memory writes for the contents become visible to other threads. Nothing in the .NET memory model appears to prevent this in this case.

**Comment by huoyaoyuan** [comment]
String content must be accessed indirectly from the reference.

Your case sounds to be applicable to any constructors. Like this:

```csharp
class C
{
    public int X;
    public C(int x)
    {
        X = x + 1; // <-- 1
    }
}

var c = new C(42); // <-- 2
```

It must be guaranteed that the assignment 2 happens after 1, or constructors can be easily broken.

**Comment by GSPP** [comment]
Yes, this applies to any constructor. A constructor confers no special thread-safety properties AFAIK.

**Comment by stephentoub** [comment]
This is no different from any other object creation. The code publishing the instance to be visible to another thread needs to ensure the proper memory barriers are in place.  It's in no way specific to this one ctor or type, so I don't understand what this issue is.

**Comment by GSPP** [comment]
It is not specific to this particular construction but I wonder if it would not be considered undermining a very fundamental guarantee of .NET that strings are immutable values. I don't think many people realize that strings can effectively change their value *using no unsafe code*. It was new to me.

Well, apparently that is not considered an issue. I thought it would be good to report it.

**Comment by jkotas** [comment]
The runtime issues barriers on weaker memory architectures when publishing object references, so this is not a real problem.

If the runtime did not issue barriers when publishing object references, it would cause problems for more than just the strings. For example, `obj.GetType()` would be unreliable.

**Comment by GSPP** [comment]
@jkotas Thanks for explaining this.
