### ISSUE TITLE
CoreCLR build-runtime.cmd script error

### ISSUE THREAD

**Issue by SamirKharchi** [dotnet/runtime#46918]
Running <pre>build.cmd -rc Release</pre> always fails because of a variable formatting error in:
https://github.com/dotnet/runtime/blob/699f49a2fc6be23d45a653c675a44b3647e6d8fd/src/coreclr/build-runtime.cmd#L680

Error message:
`File *.dll not found`
`BUILD: Error: Failed to copy the Universal CRT to the artifacts directory.`

The fix is to specify the directory variable correctly as <pre>xcopy /Y/I/E/D/F %__UCRTDir%*.dll "%__BinDir%\Redist\ucrt\DLLs\%__BuildArch%"</pre> otherwise the xcopy command cannot resolve the directory path correctly.

**Comment by SamirKharchi** [comment]
It seems this is a faulty issue as delayed expansion is used. With that in mind, the build runs smoothly. This issue can be removed.

**Comment by SamirKharchi** [comment]
Hmm, due to delayed expansion I thought I had to run the command as an administrator in order to fix the issue but I still get the following error: 
`File *.dll not found
  BUILD: Error: Failed to copy the Universal CRT to the artifacts directory.
E:\sources\dotnet\runtime\src\coreclr\runtime.proj(42,5): error MSB3073: Der Befehl ""E:\sources\dotnet\runtime\src\coreclr\build-runtime.cmd" -x64 -release -enforcepgo" wurde mit dem Code 4 beendet.`

When I fix the build script as suggested in my initial issue message, it builds fine locally. However, when creating a PR with the according fix, the azure build checks for windows (several configurations) fail with this exact same error. However, I am on windows 64bit, Win Version 10.0.19042 Build 19042

Is this a consistency issue? This is a bit confusing.

**Comment by janvorli** [comment]
Can you please try to add 
```bat
echo "UCRT file mask=!__UCRTDir!*.dll"
```
right before the xcopy to see what path it tries to use
and then try it with your change and see how it differs?

You'll need to run 
```bat
src\coreclr\build-runtime.cmd -x64 -release
```
When running it as part of the build.cmd, the message above gets eaten somehow.

**Comment by janvorli** [comment]
This is what it prints on my Windows dev box:
```
UCRT Path=C:\Program Files (x86)\Windows Kits\10\Redist\10.0.19041.0\ucrt\DLLs\x64\*.dll
```
If I change the delayed expansion (!!) to %%, then it prints this:
```
UCRT Path=*.dll
```

**Comment by ViktorHofer** [comment]
Closing as likely the required Windows SDK to build CoreCLR hasn't been installed correctly. Requirements are documented in https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md.
