### ISSUE TITLE
System.Net.Quic is not trimmed on mobile platforms

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#46915]
System.Net.Quic is not supported except on Windows but still cannot be trimmed because it's initialized aggressively via static constructors even on platforms that don't support it like iOS or android. Initialization chain is like

```
	  at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi:.ctor
	  at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi:.cctor
	  at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider:get_IsSupported
	  at System.Net.Http.HttpConnectionPool:.ctor
	  at System.Net.Http.HttpConnectionPoolManager:SendAsyncCore
	  at System.Net.Http.HttpConnectionPoolManager:SendAsync
	  at System.Net.Http.HttpConnectionHandler:SendAsync
```

There is `IsSupported` property but it does not conform to the recommended [Feature switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md) setup so it cannot be used either.

@eerhardt @karelz

**Comment by geoffkizer** [comment]
What needs to happen to fix this?

Note, S.N.Quic is also supported on Linux and eventually on MacOS as well.

**Comment by eerhardt** [comment]
> What needs to happen to fix this?

I think the initial thinking is to change `MsQuicImplementationProvider:get_IsSupported` to conform to a [feature-switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md). See other implementations for reference like

* [EventSource.IsSupported](https://github.com/dotnet/runtime/pull/38129)
* [EnableUnsafeBinaryFormatterSerialization](https://github.com/dotnet/runtime/pull/38963)

The idea being that vertical app models that want to disable/trim certain features can set these feature switches in their MSBuild Sdk files. So here Xamarin can set `System.Net.Quic.IsSupported=false` and all the Quic implementation will get trimmed away by the linker in a Xamarin app.

**Comment by geoffkizer** [comment]
The `MsQuicImplementationProvider:get_IsSupported` API isn't intended to ship; it's just a temporary measure while we have multiple providers that we are developing/testing with.

I suspect what we want is something like a single `public static bool IsSupported` on some top-level QUIC class (maybe QuicConnection? not sure).

**Comment by marek-safar** [comment]
> I suspect what we want is something like a single public static bool IsSupported on some top-level QUIC class 

Ideally, the code would be pulled only when needed. For example when http version is set to 3 or higher. If that's not possible then we resort to static property like that but that has a tax on developers to know about it. We could also PNSE the code on the platforms where the code won't be supported anytime soon (e.g. Browsers).

> Note, S.N.Quic is also supported on Linux and eventually on MacOS as well.

These are only a few platforms we support.

**Comment by geoffkizer** [comment]
>> Note, S.N.Quic is also supported on Linux and eventually on MacOS as well.

> These are only a few platforms we support.

I mentioned that because the original issue description above said

> System.Net.Quic is not supported except on Windows

**Comment by geoffkizer** [comment]
> Ideally, the code would be pulled only when needed. For example when http version is set to 3 or higher. 

This makes sense. We are only calling into System.Net.Quic from the HttpConnectionPool ctr in order to check whether it's supported or not. We can easily defer this check.

**Comment by SamMonoRT** [comment]
@eerhardt - trying to find the right owner for this. Is that someone on your team ?

**Comment by marek-safar** [comment]
I changed System.Net.Quick to be PNSE assembly so this should no longer be a concern for mobile
