### ISSUE TITLE
System.DirectoryServices.AccountManagement is not supported on this platform. - on Windows

### ISSUE THREAD

**Issue by Benjiinator** [dotnet/runtime#46921]
I am under the impression that System.DirectoryServices.AccountManagement should work on Windows on .Net 5.0.

I get ```System.DirectoryServices.AccountManagement is not supported on this platform.``` on a windows server 2019.
I am using ```Microsoft.Windows.Compatibility 5.0.1``` package which contains ```System.DirectoryServices.AccountManagement 5.0.0```

Is ```System.DirectoryServices.AccountManagement``` not inteded to work with a setup like this?

**Comment by LiorBanai** [comment]
I was working with Worker Service and got the same error on windows when using dotnet publish command line. I rebuilt the project and it worked again. I think it did partial publish to Target folder which cause this issue.

Maybe it is the same for you?

**Comment by Benjiinator** [comment]
@LiorBanai After republishing everything i still get the error - thanks for the reply though.

**Comment by danmosemsft** [comment]
This error means that the package containing S.DS.AM was directly or indirectly restored into a project that targeted .NET Standard 2.0 rather than a concrete runtime such as .NET Framework or .NET Core.

What publish command line are you using? 
What <TargetFramework[s]> values do you have in your csproj and any csproj's it depends on?

cc @joperezr

**Comment by joperezr** [comment]
If you could share the repro project we could take a look and figure out what is wrong, but as @danmosemsft suggests I believe that there is some weird reference happening here from application to package.

**Comment by Benjiinator** [comment]
@danmoseley and @joperezr i resolved the issue after setting the TargetFramework[s] in my solution to Net5.0.
Thanks for the help.
