### ISSUE TITLE
The sample code did not get the expected results

### ISSUE THREAD

**Issue by lx4556332** [dotnet/runtime#46922]
Hello, I didn't get the right result according to the example code.
URL : https://docs.microsoft.com/zh-cn/dotnet/api/system.security.cryptography.frombase64transform.-ctor?redirectedfrom=MSDN&view=netcore-2.2#System_Security_Cryptography_FromBase64Transform__ctor_System_Security_Cryptography_FromBase64TransformMode_
Error details：Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
method：DecodeFromFile(string inFileName, string outFileName)
Error line：   int bytesWritten = myTransform.TransformBlock(myInputBytes, i, 4/*myTransform.InputBlockSize*/, myOutputBytes, 0);

**Comment by vcsjones** [comment]
This looks related to, or a duplicate of #30993. As said in the issue:

>  the only workaround that I can think of for 2.1 is to pre-filter whitespace out of your input before letting the FromBase64Transform process it. The probably easier answer is to upgrade to 3.1 [or newer], since the bug is fixed in that release.

It would seem that your base64 input has whitespace or new lines in it. Is this the case for your input?

As also mentioned, the easiest solution is to use a version of the framework with the issue fixed.

**Comment by lx4556332** [comment]
The current version is 2.2 ,My Base64 input has no spaces. "helloword" The result is “aGVsbG93b3Jk”，Is there a solution for version 2.2?We can't upgrade right now。

> 这看起来与[＃30993](https://github.com/dotnet/runtime/issues/30993)相关，或与[＃30993](https://github.com/dotnet/runtime/issues/30993)复制。如问题所述：
> 
> > 我能想到的2.1的唯一解决方法是，在让FromBase64Transform处理它之前，先从您的输入中过滤掉空格。可能更简单的答案是升级到3.1 [或更高版本]，因为该版本已修复了该错误。
> 
> 看来您的base64输入中包含空格或换行符。您的输入是否如此？
> 
> 如前所述，最简单的解决方案是使用已修复问题的.NET版本。

**Comment by vcsjones** [comment]
> My Base64 input has no spaces

Can you provide a sample base64 input that reproduces the problem?

2.2 is no longer supported, but perhaps I can determine a work around.

**Comment by lx4556332** [comment]
`
            string appPath = (System.IO.Directory.GetCurrentDirectory());
            var sourceFile = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "pwd.txt");
            var targetFile = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "code.enc");
            var outFileName = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "roundtrip.txt");
            DecodeFromFile(targetFile, outFileName);

        public static void DecodeFromFile(string inFileName, string outFileName)
        {
            using (FromBase64Transform myTransform = new FromBase64Transform(FromBase64TransformMode.IgnoreWhiteSpaces))
            {

                byte[] myOutputBytes = new byte[myTransform.OutputBlockSize];

                //Open the input and output files.
                using (FileStream myInputFile = new FileStream(inFileName, FileMode.Open, FileAccess.Read))
                {
                    using (FileStream myOutputFile = new FileStream(outFileName, FileMode.Create, FileAccess.Write))
                    {

                        //Retrieve the file contents into a byte array. 
                        byte[] myInputBytes = new byte[myInputFile.Length];
                        myInputFile.Read(myInputBytes, 0, myInputBytes.Length);

                        //Transform the data in chunks the size of InputBlockSize. 
                        int i = 0;
                        while (myInputBytes.Length - i > 4/*myTransform.InputBlockSize*/)
                        {
                            int bytesWritten = myTransform.TransformBlock(myInputBytes, i, 4/*myTransform.InputBlockSize*/, myOutputBytes, 0);
                            i += 4/*myTransform.InputBlockSize*/;
                            myOutputFile.Write(myOutputBytes, 0, bytesWritten);
                        }

                        //Transform the final block of data.
                        myOutputBytes = myTransform.TransformFinalBlock(myInputBytes, i, myInputBytes.Length - i);
                        myOutputFile.Write(myOutputBytes, 0, myOutputBytes.Length);

                        //Free up any used resources.
                        myTransform.Clear();
                    }
                }
            }
        }
`
file code.enc The content is "aGVsbG93b3Jk"
The above code will report an error in version 2.2 and below.

**Comment by danmosemsft** [comment]
@lx4556332 I believe we need the sample inputs (nothing confidential of course)

Also could you please use triple back ticks to format your code to make it a bit easier to read? This has an example  
https://guides.github.com/features/mastering-markdown/

**Comment by vcsjones** [comment]
@danmosemsft 

> file code.enc The content is "aGVsbG93b3Jk"

I think we / I have everything now, just haven't had a minute to look, but will soon.

**Comment by vcsjones** [comment]
The issue with 2.2 is the way that it handles the buffer size calculation when given the input array is larger than expected. Even though you are specifying an offset and length, it is not handled correctly in 2.2.

As a work around, if you copy the input data to an array that is at most the size of the data being transformed, I believe it will work. Perhaps something like this:

```csharp
static void DecodeFromFile(string inFileName, string outFileName)
{
    using (FromBase64Transform myTransform = new FromBase64Transform(FromBase64TransformMode.IgnoreWhiteSpaces))
    {
        const int ReadSize = 4;
        byte[] myOutputBytes = new byte[myTransform.OutputBlockSize];
        byte[] inputBuffer = new byte[ReadSize];

        //Open the input and output files.
        using (FileStream myInputFile = new FileStream(inFileName, FileMode.Open, FileAccess.Read))
        {
            using (FileStream myOutputFile = new FileStream(outFileName, FileMode.Create, FileAccess.Write))
            {

                //Retrieve the file contents into a byte array. 
                byte[] myInputBytes = new byte[myInputFile.Length];

                myInputFile.Read(myInputBytes, 0, myInputBytes.Length);

                //Transform the data in chunks the size of InputBlockSize. 
                int i = 0;
                while (myInputBytes.Length - i > ReadSize/*myTransform.InputBlockSize*/)
                {
                    System.Buffer.BlockCopy(myInputBytes, i, inputBuffer, 0, ReadSize);
                    int bytesWritten = myTransform.TransformBlock(inputBuffer, 0, inputBuffer.Length, myOutputBytes, 0);
                    i += 4/*myTransform.InputBlockSize*/;
                    myOutputFile.Write(myOutputBytes, 0, bytesWritten);
                }

                //Transform the final block of data.
                System.Buffer.BlockCopy(myInputBytes, i, inputBuffer, 0, myInputBytes.Length - i);
                myOutputBytes = myTransform.TransformFinalBlock(inputBuffer, 0, myInputBytes.Length - i);
                myOutputFile.Write(myOutputBytes, 0, myOutputBytes.Length);

                //Free up any used resources.
                myTransform.Clear();
            }
        }
    }
}
```

The best solution is to upgrade to .NET Core 3.1 or newer. Then the code can be as simple as:

```csharp
static void DecodeFromFile(string inFileName, string outFileName)
{
    using (FromBase64Transform myTransform = new FromBase64Transform(FromBase64TransformMode.IgnoreWhiteSpaces))
    using (FileStream myInputFile = new FileStream(inFileName, FileMode.Open, FileAccess.Read))
    using (FileStream myOutputFile = new FileStream(outFileName, FileMode.Create, FileAccess.Write))
    using (CryptoStream cryptoStream = new CryptoStream(myInputFile, myTransform, CryptoStreamMode.Read))
    {
        cryptoStream.CopyTo(myOutputFile);
    }
}
```

**Comment by lx4556332** [comment]
谢谢你的解答，它工作了
