### ISSUE TITLE
Obsolete the Rijndael and RijndaelManaged classes

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#46930]
## Background and Motivation

.NET Framework added support for the Rijndael algorithm before (a restricted set of it) it got officially accepted as the winner of the contest to become AES.  When .NET Framework added a new Aes class the RijndaelManaged class already had a fair amount of use, and Aes wasn't available everywhere (since it was only implemented using system crypto libraries).

For .NET (nee Core), we no longer have the managed implementation of Rijndael, and the RijndaelManaged class just wraps an instance of Aes.  Rijndael and RijndaelManaged were brought to Core as part of the .NET Core/Standard 2.0 API alignment wave.

Since the .NET (nee Core) RijndaelManaged doesn't support "full Rijndael" there's no reason to use it in new code.

## Proposed API

```diff
namespace System.Security.Cryptography.Algorithms
{
+   [Obsolete(someID)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public partial class Rijndael
    {
    }

+   [Obsolete(someID)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public partial class RijndaelManaged
    {
    }
}
```

**Comment by vcsjones** [comment]
Perhaps relevant to the discussion: these types are already EditorBrowsableState.Never.

**Comment by bartonjs** [comment]
> Perhaps relevant to the discussion: these types are already EditorBrowsableState.Never.

Good point.  Updated the proposal to show that.

**Comment by bartonjs** [comment]
Looks good as proposed.

```C#
namespace System.Security.Cryptography.Algorithms
{
+   [Obsolete(someID)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public partial class Rijndael
    {
    }

+   [Obsolete(someID)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public partial class RijndaelManaged
    {
    }
}
```
