### ISSUE TITLE
Core 5.0: target musl arm32v7

### ISSUE THREAD

**Issue by fugkco** [dotnet/runtime#46954]
Hello, I'm trying to compile an application and trying to target musl platforms, but getting errors. After some research, it seems to me like [it's not currently supported](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md#L32). Is this a correct assumption?

To clarify, when running `dotnet publish -p:Version=1.0.0 -p:PublishTrimmed=true -c Release -f net5.0 --self-contained -r linux-musl-x64 -o /output/jackett src/Jackett.Server`, it runs fine on amd64. When changing the architecture to arm, it's not clear to me what the runtime arg should be, however, I tried setting it to `linux-musl-arm`, `linux-musl-arm32`, and some other variables. I also tried `-p:RuntimeOS=linux-musl` combined with `-r linux-arm`, still no luck.

Assuming this is indeed currently not supported, and considering musl is supported for amd64, and arm64 (assuming my previous assumption and link is correct), is this something you would consider adding?

**Comment by NikolaMilosavljevic** [comment]
[Triage] @dleeapho , @jamshedd can you please clarify scope of 6.0 package work?

**Comment by fugkco** [comment]
@NikolaMilosavljevic @dleeapho @jamshedd sorry to bother, but just to confirm, is this going to be fixed in the 6.0 package? If so, is there an ETA for 6.0 stable?

**Comment by alexrp** [comment]
@fugkco can you clarify what the issue is?

It seems to work fine for me (both with `net5.0 and `net6.0`):

```console
$ dotnet publish -r linux-musl-arm -p:PublishTrimmed=true -c Release
Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\alex\source\repos\tests\testapp\testapp.csproj (in 5,99 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  testapp -> C:\Users\alex\source\repos\tests\testapp\bin\Release\net6.0\linux-musl-arm\testapp.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  testapp -> C:\Users\alex\source\repos\tests\testapp\bin\Release\net6.0\linux-musl-arm\publish\

$ file bin/Release/net6.0/linux-musl-arm/publish/testapp
bin/Release/net6.0/linux-musl-arm/publish/testapp: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-armhf.so.1, BuildID[sha1]=444d1083d87c196fe0a75fabf3a788a1ce443796, stripped
```

**Comment by NikolaMilosavljevic** [comment]
> @fugkco can you clarify what the issue is?
> 
> It seems to work fine for me (both with `net5.0` and `net6.0`):
> 
> ```
> $ dotnet publish -r linux-musl-arm -p:PublishTrimmed=true -c Release
> Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   Restored C:\Users\alex\source\repos\tests\testapp\testapp.csproj (in 5,99 sec).
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   testapp -> C:\Users\alex\source\repos\tests\testapp\bin\Release\net6.0\linux-musl-arm\testapp.dll
>   Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
>   testapp -> C:\Users\alex\source\repos\tests\testapp\bin\Release\net6.0\linux-musl-arm\publish\
> 
> $ file bin/Release/net6.0/linux-musl-arm/publish/testapp
> bin/Release/net6.0/linux-musl-arm/publish/testapp: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-armhf.so.1, BuildID[sha1]=444d1083d87c196fe0a75fabf3a788a1ce443796, stripped
> ```

[Triage] @fugkco this should be working now. If you still see any issues, please reopen.

**Comment by fugkco** [comment]
Humm, it's too long ago to remember what the original issue was. I just built the exact same Dockerfile and it worked fine with `net5.0`. Thanks all.
