### ISSUE TITLE
Start dogfooding .NET 6 SDK/runtime in CI?

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#46960]
I was looking at global.json to see whether we were using a version of SDK which included a specific Apple Silicon fix.  I noticed we are still building with the .NET 5 SDK.  

We should move to .NET 6 SDK before we release .NET 6 preview1 IMHO.

@dotnet/runtime-infrastructure

**Comment by jkoritzinsky** [comment]
Generally, we only bump the SDK we use in dotnet/runtime when we need a new feature for our build since moving to a dogfooding build causes slightly worse developer experience. So far we haven't needed that, so we haven't started dogfooding.

**Comment by sdmaclea** [comment]
It is an interesting tradeoff "developer experience" vs test coverage.  Building against the dogfood runtime & SDK provides a lot of great coverage.  It helps us find issues earlier.

Maybe we could have rolling dogfood builds?  Best of both worlds?

**Comment by sdmaclea** [comment]
Maybe a dogfooding PR (subscription) which never gets merged?

I may create a PR for a recent .NET 6 SDK/runtime just to see if it work for other platforms (before seeing if it works on macos-arm64)

**Comment by ViktorHofer** [comment]
> Maybe a dogfooding PR (subscription) which never gets merged?

Yes, we talked about dogfooding new SDK builds regularly but not via checking into the master branch but via scheduled builds (ie rolling and official ones).

> since moving to a dogfooding build causes slightly worse developer experience.

Reliability is yet another factor that plays into the decision of sticking with a publicly released 5.0 SDK as long as possible.

**Comment by ViktorHofer** [comment]
cc @Anipik for the continuous SDK dogfooding.

**Comment by ViktorHofer** [comment]
Will be fixed with https://github.com/dotnet/runtime/pull/48462.

**Comment by sdmaclea** [comment]
Closing in favor of #48462
