### ISSUE TITLE
CoClass doesn't mix well with default interface implementations

### ISSUE THREAD

**Issue by R2D221** [dotnet/runtime#46993]
### Description

While this is most likely not the intended use of ComImport/CoClass, I still think this finding is interesting and I wanted to report it.

If you declare a normal class with an interface, and link them with the ComImport and CoClass attributes, it all works as expected.

```csharp
void Main()
{
	var one = new IntWrapper(1);
	var two = new IntWrapper(2);
}

[ComImport]
[Guid("679211c8-0252-410f-a832-8992c674d91b")]
[CoClass(typeof(IntWrapperImpl))]
public interface IntWrapper
{
	int Value { get; }
}

public class IntWrapperImpl : IntWrapper
{
	public IntWrapperImpl(int value) => Value = value;

	public int Value { get; }
}
```

But as soon as you add a default interface method, running the code gives you a ReflectionTypeLoadException.

```csharp
void Main()
{
	var one = new IntWrapper(1);
	var two = new IntWrapper(2);
	
	// We use the interface method here
	var three = one.Plus(two);
}

[ComImport]
[Guid("679211c8-0252-410f-a832-8992c674d91b")]
[CoClass(typeof(IntWrapperImpl))]
public interface IntWrapper
{
	int Value { get; }
	
	// We add an interface method with a default implementation
	IntWrapper Plus(IntWrapper that) =>
		new IntWrapper(this.Value + that.Value);
}

public class IntWrapperImpl : IntWrapper
{
	public IntWrapperImpl(int value) => Value = value;

	public int Value { get; }
}
```

The exception is as follows:
> ReflectionTypeLoadException: Unable to load one or more of the requested types.
> Could not load type 'IntWrapper' from assembly 'LINQPadQuery, Version=1.0.0.1744, Culture=neutral, PublicKeyToken=null' because the method 'Plus' has no implementation (no RVA).
> Could not load type 'IntWrapper' from assembly 'LINQPadQuery, Version=1.0.0.1744, Culture=neutral, PublicKeyToken=null' because the method 'Plus' has no implementation (no RVA).

Now, I don't know if this exception is expected. I understand that the class doesn't have a definition for the Plus method, but at the same time, it should be able to use the one defined in the interface just fine.

### Configuration

* .NET 5.0.1
* Roslyn Version: 3.8.0-5.20562.2
* LinqPad 6.11.11 to test the snippets
* Windows 10 Pro 20H2 (19042.746)

### Regression?

There's no regression here since default interface implementations are fairly recent.

### Other information

This is purely for experimentation. I'm not working on anything that depends on this. Still, I don't see any obvious reason why this should be failing.

**Comment by AaronRobinsonMSFT** [comment]
Default interface methods and CoClasses and other scenarios involving COM are not compatible. This is by-design.
