### ISSUE TITLE
Volatile.Write doesn't prevent reordering as documented

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#46995]
The documentation for [Volatile.Write](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile.write?view=net-5.0) specifies that:

> On systems that require it, inserts a memory barrier that prevents the processor from reordering memory operations as follows: If a read or write appears before this method in the code, the processor cannot move it after this method.

However, using Sharplabs ([see code](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcAMACOSB0AKgBYBOApmACYCWAdgOYDc66cAzLgtgMLoDe6bMOz1g2APpgANJIBGLNCOwA3APYAbMMBobyouuIkqZklQtZKRHXABZsAOTUAFUmuDkAxjrV0AFACU2EIiglbKwlLYALzYAByKESIScjHYAJyJIgC+lso2cPYAaprauuQA6qQ0HoHB4dhhScIlWjp6+FU15H4UAGaSpnEBWUmtZR1dtf3ysukjIcK5aIu4nIXY4+3kRWCkEIGrTc1RsQmryilpmavLqwX2ALLkUGqkAJ4AQnvV5KSHDWOSVO8VGERIFGo+Gerw+31Iv3+Cwal1SsRuDWW2SAA)), the following code:

```c#
Volatile.Write(ref _a, 8);
Volatile.Write(ref _b, 9);
```

... generates the following assembly (default x64, Release):

```asm
lea rax, [rcx+8]
mov dword ptr [rax], 8
add rcx, 0xc
mov dword ptr [rcx], 9
```

There doesn't seem to be any memory barrier preventing `_b` from being assigned before `_a`.

For comparison:

```c#
 _a = 8;
Thread.MemoryBarrier();
_b = 9;
```

... generates the following:

```asm
mov dword ptr [rcx+8], 8
lock or dword ptr [rsp], 0
mov dword ptr [rcx+0xc], 9
```

Note that [the general notes on the Volatile class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile?view=net-5.0) don't mention memory barriers or reordering - only docs on Volatile.Read and Volatile.Write.

If this is indeed incorrect documentation, I can submit a fix.

/cc @damageboy

**Comment by roji** [comment]
After writing this I learned that x86 has strong guarantees around store specifically (e.g. [details](https://stackoverflow.com/questions/50307693/does-an-x86-cpu-reorder-instructions)), so I'm guessing everything may fine and that Volatile.Write only emits memory barriers e.g. on ARM (thanks @NinoFloris). Will leave this open for someone to confirm and close.

**Comment by stephentoub** [comment]
> Will leave this open for someone to confirm and close.

Correct.
