### ISSUE TITLE
Redirecting StdOut and StdErr results in unexpected behaviour in Linux console apps

### ISSUE THREAD

**Issue by robeving** [dotnet/runtime#46991]
### Description

Redirecting both STDOUT and STDERR using the Process class results in unexpected behaviour.

I have a very simple .NET5 Linux program (same behaviour on Core 3.1) which runs Nano and waits for it to terminate. If I redirect only one output stream then this code works as expected. Nano loads and I can interact exactly how I would if it was launched via Bash.

If I redirect stderr and stdout a number of unexpected things happen:
- The nano window does not fill the entire terminal screen
- Escape sequences appear on screen (^X as an example)
- I can use the menus but I have to press the escape sequence then hit enter

It seems that there is some corruption or change in behaviour in handling the STDOUT and STDERR streams BUT only when both are redirected.

This is an example program that shows the correct behaviour I would expect. In this example only STDOUT is redirected and is immediately echoed to screen by copying to stream to Console.Out. Note that no other streams are redirected.

```
static async Task Main(string[] args)
{
    var proc = new Process();
    proc.StartInfo.UseShellExecute = false;
    proc.StartInfo.FileName = "/bin/nano";
    proc.StartInfo.Arguments = "hello";
    proc.StartInfo.CreateNoWindow = true;
    proc.StartInfo.RedirectStandardError = false;
    proc.StartInfo.RedirectStandardOutput = true; // only redirect stdout
    proc.StartInfo.RedirectStandardInput = false;

    proc.Start();

    var t1 = proc.StandardOutput.BaseStream.CopyToAsync(Console.OpenStandardOutput());
    proc.WaitForExit();
    await t1;
}
```
This is an example of incorrect handling. Note that here both STDOUT and STDERR are redirected. Only one stream is actually copied for the sake of a small test case.

```
static async Task Main(string[] args)
{
    var proc = new Process();
    proc.StartInfo.UseShellExecute = false;
    proc.StartInfo.FileName = "/bin/nano";
    proc.StartInfo.Arguments = "hello";
    proc.StartInfo.CreateNoWindow = true;
    proc.StartInfo.RedirectStandardError = true; // redirecting both out streams
    proc.StartInfo.RedirectStandardOutput = true; // redirecting both out streams
    proc.StartInfo.RedirectStandardInput = false;

    proc.Start();

    var t1 = proc.StandardOutput.BaseStream.CopyToAsync(Console.OpenStandardOutput());

    proc.WaitForExit();

    await t1;
}
```

Nano creates no STDERR as seen by `nano 2>> stderr.txt` so I'm not convinced the content of these streams is actually important here.

### Configuration

- X64 Linux Ubuntu 18.04 WSL1
- X64 Linux Ubuntu 18.04 WSL2
- X64 Linux Ubuntu 20.04 WSL2

### Regression?

Same behaviour on Core 3.1

**Comment by robeving** [comment]
area-System.Diagnostics.Process for people with write-permissions

**Comment by eiriktsarpalis** [comment]
I can reproduce the issue. On my machine it also seems like console dimensions are being misreported:
![image](https://user-images.githubusercontent.com/2813363/104726593-c6799880-572b-11eb-8810-1e4d1b395485.png)
However once I replace the editor with `vim`:
```diff
-        proc.StartInfo.FileName = "/bin/nano";
+        proc.StartInfo.FileName = "/usr/bin/vim";
```
I see no issues and control sequences work as expected. I wonder if there might be an issue specific to the nano implementation that results in this behaviour. I think it would help if you could provide a minimal console app that replaces nano and clearly demonstrates the problem. cc @adamsitnik

**Comment by tmds** [comment]
> Redirecting both STDOUT and STDERR using the Process class results in unexpected behaviour.

`nano` uses these file descriptors to access the terminal.

By redirecting them, you're replacing the terminal with a `pipe`(/`socket`) to the point where `nano` can no longer access the terminal.

You shouldn't redirect when running interactive applications.

**Comment by robeving** [comment]
I couldn't come up with a test case that exactly matches the nano problems but I can repo something similar.

Your C

```
#include <sys/ioctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/vt.h>

int main(void)
{
  struct winsize w;
  ioctl(0, TIOCGWINSZ, &w);
  fprintf(stdout, "O) lines %d\n", w.ws_row);
  fprintf(stdout, "O) columns %d\n", w.ws_col);

  fprintf(stderr, "E) lines %d\n", w.ws_row);
  fprintf(stderr, "E) columns %d\n", w.ws_col);

  struct vt_stat dummy;

  /* Check whether we're running on a Linux console. */
  int on_a_vt = (ioctl(0, VT_GETSTATE, &dummy) == 0);
  fprintf(stdout, "ONVT =  %d\n", on_a_vt);

  char buf[1];

  int counter = 1;
  while(read(STDIN_FILENO, buf, sizeof(buf))>0)
  {
    printf("ReadKey 0x%08x count=%d\n", buf[0], counter++);
  }
}
```

Your C#

```
        static async Task Main(string[] args)
        {
            var proc = new Process();
            proc.StartInfo.UseShellExecute = false;
            proc.StartInfo.FileName = "/mnt/c/repos/CSShell/CSShell/bin/Debug/net5.0/a.out";
            proc.StartInfo.CreateNoWindow = true;
            proc.StartInfo.RedirectStandardError = true;
            proc.StartInfo.RedirectStandardOutput = true;
            proc.StartInfo.RedirectStandardInput = false;

            proc.Start();

            var t1 = proc.StandardOutput.BaseStream.CopyToAsync(Console.OpenStandardOutput());
            var t2 = proc.StandardError.BaseStream.CopyToAsync(Console.OpenStandardError());

            proc.WaitForExit();

            await t1;
            await t2;
        }
```

I'm expected identical output and behaviour here. Notable as STDIN hasn't been redirected.

In an interactive Linux terminal (i'm using Windows Terminal / WSL2 / Ubuntu 18.04) run the compiled C code above. I get the following in my terminal.
```
O) lines 47
O) columns 146
E) lines 47
E) columns 146
ONVT =  0
<I type in 'hello' it is echoed back, hit enter>
ReadKey 0x00000068 count=1
ReadKey 0x00000065 count=2
ReadKey 0x0000006c count=3
ReadKey 0x0000006c count=4
ReadKey 0x0000006f count=5
ReadKey 0x0000000a count=6
```

Now running the C# that's going to run the program (same terminal env). 
```
E) lines 47
E) columns 146
<I type in 'hello' it is echoed back, hit enter>
```
Problems with C#, no STDOUT.

If you remove the reading of STDIN from the test C app then you do get STDERR and STDOUT when the C# is run. But STDIN isn't redirected...
```
  char buf[1];

  int counter = 1;
  while(read(STDIN_FILENO, buf, sizeof(buf))>0)
  {
    printf("ReadKey 0x%08x count=%d\n", buf[0], counter++);
  }
```

**Comment by tmds** [comment]
Not redirecting avoids issues where the application uses the file descriptors for terminal functions.

It depends on the application itself how hard it tries to get hold of the terminal.
So some applications may work better when redirected than others.
The general rule is: don't redirect when running interactive applications.

I don't think there is an issue here on .NET side.

If that makes sense, can you close the issue?

**Comment by robeving** [comment]
This makes sense. I do wonder if it might be worth uplifting the documentation to state the above.

**Comment by tmds** [comment]
It surprised me that you were redirecting streams for an interactive application.
I don't have a strong opinion about whether the docs should mention it.

**Comment by robeving** [comment]
I wanted to MitM the stream to be able to provide overlay functionality. Redirecting the output to a descriptor I control, altering it, and then providing it back to the terminal. Screen/Tmux already do this via a PTY IIRC.

**Comment by tmds** [comment]
I think you need some of these: https://man7.org/linux/man-pages/man3/forkpty.3.html. You can try use them through `DllImport` and see if you can get it to work.

**Comment by tmds** [comment]
I think this can be closed.
