### ISSUE TITLE
IOptions<T> should support record types

### ISSUE THREAD

**Issue by ddrinka** [dotnet/runtime#46998]
With PR [#2169](https://github.com/dotnet/extensions/pull/2169) in place, there is no longer a compiler restriction on using records with `IOptions<T>`.  However the [default OptionsFactory implementation](https://github.com/dotnet/runtime/blob/54953538be9e7e20eccc90b271edfd01210cf6a8/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs) still requires a parameterless constructor.

We should be able to use fully-defaulted records with the IOptions pattern.  The following builds but throws:
```csharp
record MyConfiguration(string value = "default");
MyConstructor(IOptions<MyConfiguration> configuration) { }
```

**Comment by Clockwork-Muse** [comment]
Duplicate #46996

**Comment by ddrinka** [comment]
Apologies for the duplicate.  I received a 500 error from GitHub for the first submission.  Closing this duplicate.
