### ISSUE TITLE
Corrupt binlogs recorded on Linux using GZipStream

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/runtime#47024]
We have received a couple of binlogs from @tmds in this issue:
https://github.com/dotnet/runtime/issues/45755

They were recorded on Linux and there's something about the environment that makes them unreadable on Windows. We tried to open the binlogs with the exception:

![image](https://user-images.githubusercontent.com/7412651/102330933-740d5680-3f8a-11eb-99c4-2c89716815ef.png)

We've asked to record a small binlog from a tiny project, and that one was fine. However the large binlogs didn't open. 

The binlog is just a binary stream archived with GZipStream. Here's the code to read a binlog:
https://source.dot.net/#Microsoft.Build/Logging/BinaryLogger/BinaryLogReplayEventSource.cs,35

**Comment by KirillOsenkov** [comment]
Ping me for the internal link to the binlogs

**Comment by stephentoub** [comment]
> Here's the code to read a binlog

What about the writing side?

**Comment by KirillOsenkov** [comment]
The binlog writing logic is here:
https://github.com/dotnet/msbuild/blob/a2c42ce9fc8d6fbd4a8cd600073803b8687c9341/src/Build/Logging/BinaryLogger/BinaryLogger.cs#L139

I haven't seen this binlog corruption before, it fails immediately when trying to read the first buffer from the stream:
![image](https://user-images.githubusercontent.com/679326/102393265-f7c84280-3f8c-11eb-9212-9f18f026a8c5.png)

I don't have the expertise to dig deeper unfortunately. This is where the binlog creation logic lives in MSBuild:
https://source.dot.net/#Microsoft.Build/Logging/BinaryLogger/BinaryLogger.cs,139

**Comment by tmds** [comment]
> We've asked to record a small binlog from a tiny project, and that one was fine.

@KirillOsenkov The one I sent in December was generated using the dotnet sdk that was downloaded by `build.sh` at `runtime/.dotnet`.
Last week I figured out the issues I have (https://github.com/dotnet/runtime/issues/45755) are due to the globally installed sdk on my system being used by the runtime build.
Maybe a small binlog from that sdk will also fail. I'm sending you one by mail.

**Comment by KirillOsenkov** [comment]
Binlogs uploaded by Tom are on corpnet at:
kirillo2\public\Bugs\runtime47024

**Comment by tmds** [comment]
@KirillOsenkov how can I check whether a binlog has this issue?

I'm trying by using the `BinaryLogReplayEventSource` referenced in the top level comment.
```cs
static void Main(string[] args)
{
    var replay = new BinaryLogReplayEventSource();
    replay.Replay(args[0]);
}
```
When I run it on my machine (Fedora) for the binlogs I've sent you, it doesn't throw.

These are the MD5 hashes of the files I ran it against:
```
$ md5sum *.binlog
b065c5095fbddece1b709052ae604df9  msbuild2.binlog
815c60686f56565ef19edbff63b42d8d  msbuild3.binlog
cf38e8b22da26e7e52d383ecc26b997e  msbuild4.binlog
3aee6b8692095b1d308162e1431a0a4d  msbuild5.binlog
446ead3c68bd454f5414b7b048163be5  msbuild.binlog
```

**Comment by KirillOsenkov** [comment]
If you have Windows you can use https://msbuildlog.com, and it has an online viewer too (https://live.msbuildlog.com)

**Comment by tmds** [comment]
Does `BinaryLogReplayEventSource.Replay` crash for you with these files?
Is there something I can run on Linux?

**Comment by KirillOsenkov** [comment]
BinaryLogReplayEventSource is a good thing to try, it doesn't work for me for your large files. The fact that it works for you is interesting. We'll need the compression experts to take a deeper look here, I'm out of my depth :)

**Comment by tmds** [comment]
@jeffhandley @carlossanlop @ericstj it looks like the gzip (msbuild log) files I provided to @KirillOsenkov can not be opened on Windows, but they can be opened on Linux. Can one of you take a look? Kirill has uploaded the files to `kirillo2\public\Bugs\runtime47024`.

**Comment by tmds** [comment]
This looks like a product issue with `GZipStream`. Can you take a look?

**Comment by ericstj** [comment]
Cc @adamsitnik @carlossanlop @Jozkee 

@tmds can you share the repro code sample that is working on Linux but not windows?

**Comment by KirillOsenkov** [comment]
You can play back a binlog using `msbuild /bl mybinlog.binlog` (read more at https://msbuildlog.com)

And here's some sample code to just read the file stream:
https://github.com/dotnet/runtime/issues/39233#issuecomment-741501137

https://github.com/dotnet/runtime/files/5663327/testGzipStream.zip

Would be curious to see if this way of reading the GZipStream would work for the binlogs you have or not.

**Comment by ericstj** [comment]
I took a look at this and found it failing here: https://github.com/dotnet/runtime/blob/99f3f55697b09e4a03a17e0a62f18d174cd4c285/src/libraries/Native/Windows/System.IO.Compression.Native/zlib/inflate.c#L681

If I compare that to a good log, it should start with the GZip header (0x8b1f).
https://github.com/dotnet/runtime/blob/99f3f55697b09e4a03a17e0a62f18d174cd4c285/src/libraries/Native/Windows/System.IO.Compression.Native/zlib/inflate.c#L664

Now if I crack open these logs in a hex editor I'm seeing they seem to have a bunch of raw text at the start of the log.  Indeed these do not appear to be compressed at all.  @KirillOsenkov can you try reading these as if they weren't wrapped in a GZipStream and see if that works?  That seems to be the format.

**Comment by KirillOsenkov** [comment]
@ericstj haha, indeed, without GZipStream these open mostly fine (although it did break towards the end of the file where BuildEventArgs had a nonsensical BuildRequestId (large negative number). But at least it read a decent chunk of the file before that:
![image](https://user-images.githubusercontent.com/679326/106537081-7a11b500-64ae-11eb-8e50-8bfa86e1aab9.png)

This is how the GZipStream is created:
https://github.com/dotnet/msbuild/blob/f98579d50f8b08c4efe13ca07327e3e5222b50f8/src/Build/Logging/BinaryLogger/BinaryLogger.cs#L139

Is `CompressionLevel.Optimal` not supported on Linux? Or what is going on here? And why would there be invalid data far into the stream?

**Comment by KirillOsenkov** [comment]
Update: linux.binlog opened just fine without GZipStream, but linux3.binlog had that issue I mentioned above. I'll call it a fluke (or maybe the file didn't download fully).

It's super strange that small binlogs recorded by Tom are fine, but the huge ones aren't wrapped in a GZipStream at all.

**Comment by ericstj** [comment]
My best guess at what's happening here is that something in the transport from Tom's machine is stripping the GZip compression from those files.  Perhaps the method he used to get them off/transport them?

In general we produce binlogs from linux all the time and don't have trouble reading them.  If we have some repro of GZipStream producing this payload directly we could investigate it.  Right now there seem to be too many variables/unknowns here to treat this as a bug.

If @tmds wants to try a repro again, I'd recommend examining the first two bytes of the binlog before having it leave the machine.  It should be 0x81bf.  If it isn't then debug why GzipStream is writing non-Gzip'ed content.

**Comment by tmds** [comment]
Thanks @ericstj for the analysis.

I moved the binaries of my machine via ssh straight to the apache webserver. I don't think anything down that path could have stripped the compression.

Unfortunately, I can no longer reproduce the issue at this point. It may have to do with the global sdk on my system now being 5.0.102 and no longer being used by a dotnet/runtime build.

I won't go back to an older sdk in an attempt to reproduce this problem. You can close the issue.

**Comment by ericstj** [comment]
> straight to the apache webserver

That’s exactly the thing I was imagining.  Perhaps something in HTTP pipeline was doing this?  Could even be in whatever tool/browser @KirillOsenkov used to download.

If you still have the files on your web server can you check the first two bytes?

**Comment by KirillOsenkov** [comment]
I think we can close this as it's likely not a bug in the framework.
