### ISSUE TITLE
coreclr education

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/runtime#4703]
The “Book of the Runtime” provides a good high level overview of various aspects but is insufficient to get up to speed for those who are new to this layer and want to contribute exposing native o/s api’s or debug existing interops. 

.NET community needs a more practical code review (preferably 2 – 3 debugging videos) starting by explaining the flow and data-structures (managed and C++) involved in the following scenarios:

Managed to native / Native to managed plumbing (P/Invoke internals)
Native to Managed Thread transitions.

Garbage collection might be interesting further on.. but not high priority.

**Comment by danmosemsft** [comment]
I think this would be a good idea, but nobody has picked it up and I don't think it is that helpful to keep this issue open. Perhaps we will get interest in future.
