### ISSUE TITLE
Reesult of ToString("C") is incomatible in Blazor WebAssembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#47068]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Reesult-of-ToStringC-is-incomatible-/1305101)._

---
In ja-JP culture of .NET F/W and . NET5 in desktop, 123.ToString("C") is "\123", but in Blazor WebAssembly, 123.ToString("C") is "￥123".

System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("ja-JP");
        Console.WriteLine(123.ToString("C"));

---
#### Feedback Bot on 1/10/2021, 07:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lewing FYI.

**Comment by tarekgh** [comment]
> In ja-JP culture of .NET F/W and . NET5 in desktop, 123.ToString("C") is "\123", but in Blazor WebAssembly, 123.ToString("C") is "￥123".

I assume this is flipped statement. I am seeing .NET 5.0 is successfully returning `￥123` which is the expected result.

**Comment by lewing** [comment]
@tarekgh yeah I assume it was just reversed in the explanation.

This looks like is is probably an example of loading in a specific culture that doesn't exist in the default icu data. I think following the instructions at Request for guidance on connect feedback should fix it.

@tqiu8 can you add this to the work you're doing to fail when trying to load an unsupported culture.
