### ISSUE TITLE
meet #25901, Vector2<-->PointF implicit conversion .

### ISSUE THREAD

**Issue by ohsorry** [dotnet/runtime#47066]
## Background and Motivation
No c# native support, have to write this:
```c#
 public static class NumericExtension
    {
        public static PointF ToPointF(this ref Vector2 vector2)
        {
            return new PointF(vector2.X, vector2.Y);
        }

        public static Vector2 ToVector2(this ref PointF pointF)
        {
            return new Vector2(pointF.X, pointF.Y);
        }

       blah blah...

    }

```

## Risks
no risks.

**Comment by tannergooding** [comment]
CC. @safern as this also impacts System.Drawing.

I think the major downside to this proposal is that it couples S.N.Vectors and S.Drawing in a way that is likely undesirable.

**Comment by ohsorry** [comment]
I am writing sort of a game, the physics engine library uses vector/matrix for computation.
while I think I should use `Point/PointF` and `Size/SizeF` to declare my drawing interface for GDI+/DirectX/OpenGL/Vulkan。

**Comment by ohsorry** [comment]
Well, I think I don't really need GDI+ actually. :smile:  I replaced all my interface declarations with vector2, and things became simple!
I will close this issue, you guys can reopen it if it is necessary.
