### ISSUE TITLE
Is it possible to discover if pdb is full or portable using MetadataReader?

### ISSUE THREAD

**Issue by eddynaka** [dotnet/runtime#47079]
Hi,

I would like to check if is possible to know if a pdb is full or portable using MetadataReader.

For example, if the pdb is full, I can see that that are flags that does not show correctly. But, if the pdb is portable i can see everything correctly. So, I would need some way to distinguish between a full vs portable pdb.

Thank you.

**Comment by krwq** [comment]
Would using https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/DebugDirectory/DebugDirectoryEntry.cs#L35-L40 with a local copy of https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/PortablePdb/PortablePdbVersions.cs
I'm seeing couple of places in the code comparing that with `< PortablePdbVersions.MinFormatVersion`.
It might be worth to look at the implementation of the specific API you want to use and see what it does.
