### ISSUE TITLE
Why we need Type.op_Equality?

### ISSUE THREAD

**Issue by CreateAndInject** [dotnet/runtime#47090]
On .NET 2.0, if we compare two types by `==`, it will call `object.Equals`, but from .NET 4.0, it will call `Type.op_Equality`.
So, why we need `Type.op_Equality`? Is one type can have two instances?
This blocks us from using `C#9 Record Types` on .NET 2.0 (CS0656)

**Comment by svick** [comment]
I don't know why this change was made, but [C# 9 is only officially supported on .Net 5](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version?WT.mc_id=DOP-MVP-5002735), so I doubt you're going to get much help with trying to make it work on something as ancient as .Net Framework 2.0.

**Comment by CreateAndInject** [comment]
@svick We can use `<LangVersion>latest</LangVersion>` to support C#9 on .NET Framework 2.0-4.8.
And we can add following code to support init-only setter
```
namespace System.Runtime.CompilerServices
{
    class IsExternalInit { }
}
```

But `Type.op_Equality` blocks us from using `C#9 Record Types` on .NET 2.0 (CS0656), so I want to know, why we need this method? Is the result different from `object.Equals`?

**Comment by SingleAccretion** [comment]
> On .NET 2.0, if we compare two types by `==`, it will call `object.Equals`

Hmm, that's interesting. It doesn't call `object.ReferenceEquals`, but specifically `object.Equals`?

**Comment by huoyaoyuan** [comment]
> Hmm, that's interesting. It doesn't call `object.ReferenceEquals`, but specifically `object.Equals`?

It should call `object.op_Equality`, which calls `ReferenceEquals`. `object.Equals` isn't called.

**Comment by SingleAccretion** [comment]
Right, that was my suspicion as well. Because that and https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types would explain this.

**Comment by CreateAndInject** [comment]
I test it: .NET 2.0 use `ceq` which is equal to `ReferenceEquals`

**Comment by CreateAndInject** [comment]
@SingleAccretion I had read [this article](https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types), but today I didn't remember it. I agree with you : this should be the reason.
