### ISSUE TITLE
[Documentation] Thread safe methods of HttpClient

### ISSUE THREAD

**Issue by SommerEngineering** [dotnet/runtime#47107]
If I have analyzed the code of `HttpClient` correctly (cf. [code](https://github.com/dotnet/runtime/blob/fc3f6f1a053cc8dcfc1d384be205be7d9045afa5/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L555)), then the method `PatchAsync` (and all its variants) is/are also thread-safe. However, the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#remarks) only lists the following methods as thread-safe:

- CancelPendingRequests
- DeleteAsync
- GetAsync
- GetByteArrayAsync
- GetStreamAsync
- GetStringAsync
- PostAsync
- PutAsync
- SendAsync

Did I miss some aspect in the code or is my analysis correct? Just in case I'm right, can you update the documentation? Thanks.

**Comment by karelz** [comment]
Thanks @SommerEngineering for the report! I agree that it is missing. Are you interested in putting up PR with the change in docs? https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml

**Comment by SommerEngineering** [comment]
Thanks for the response, @karelz. Sure, I can add this. This is my first PR for the dotnet foundation. Is there anything I need to keep in mind or can I create a PR like for any other Github project?

**Comment by karelz** [comment]
@SommerEngineering just follow the api-docs repo steps, it will take care of everything.
For small changes, there shouldn't be anything else you need to do to my best knowledge.

Thanks for your contribution!
