### ISSUE TITLE
Arithmetic overflow in CryptoStream with very large reads

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#47136]
I noticed an issue while eyeballing code in `CryptoStream`, where attempting to perform very large reads can result in an arithmetic overflow if the input block size is greater than the output block size:

https://github.com/dotnet/runtime/blob/3946369dd6e42cc59e09651ce3e9d09751d44131/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/CryptoStream.cs#L329-L334

Say in the case of `FromBase64Transform`, it will divide the length by 3, then multiple by 4.

Simple repo:

```csharp
[Fact]
public static void EnormousRead()
{
    const int MaxLength = 0x60000000;
    const int MaxRaw = 0x5FFFFFD3;

    byte[] buffer = new byte[MaxRaw];
    byte[] output = new byte[MaxLength];

    buffer.AsSpan().Fill((byte)'A');

    using var stream = new MemoryStream(buffer);
    using var transform = new FromBase64Transform();
    using var cs = new CryptoStream(stream, transform, CryptoStreamMode.Read);
    cs.Read(output, 0, output.Length);
}
```

Granted this is probably not a typical way to use a stream.

As it is, the repro above will fail with:

```plain
Error Message:
   System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'minimumLength')
  Stack Trace:
     at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength) in /code/personal/dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs:line 87
```

**Comment by GSPP** [comment]
I like this bug. This is the same method I used to break `StringBuilder` and log issues on this bug tracker 😄

**Comment by bartonjs** [comment]
While this code passes on .NET Framework (and takes a small forever to run) it fails with OverflowException (negative value in `new byte[int]`) instead of ArgumentException (negative value to ArrayPool.Rent) with the improvements we've made to the structure of FromBase64Transform (setting Multiple to true and InputBlockSize to 4).

I'll poke at it a little bit, but since this isn't a functionality regression it's a little less urgent.

**Comment by vcsjones** [comment]
Personally I would not mind if this did not work. I just dislike the unchecked arithmetic overflow. I would be fine if this were fixed by some `checked` contexts / operations. Perhaps as a first step.

My only real concern is that it might be a more severe impact later if some surrounding code were to change, say, stackallocing a negative size.

**Comment by bartonjs** [comment]
::nod:: making the operation be checked might be the way to go (essentially, exception preserving), though bounding things at Array.MaxLength seems to work.  I'd probably need to do more validation with bounding to make sure that it's not doing weird stuff on a secondary edge case... so maybe "easier to test" is the way to go.
