### ISSUE TITLE
The repo fails to build when git source control information isn't available

### ISSUE THREAD

**Issue by Maniues** [dotnet/runtime#47130]
Command: "./build.sh" on root
I didn't use https://github.com/dotnet/source-build

Log (copied from Bash): pastebin.com/6MEtHDcq

**Comment by danmosemsft** [comment]
```
/root/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory '/home/osboxes/Desktop/runtime-5.0.2/tools-local/tasks/installer.tasks'. [/home/osboxes/Desktop/runtime-5.0.2/tools-local/tasks/installer.tasks/installer.tasks.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory '/home/osboxes/Desktop/runtime-5.0.2/tools-local/tasks/installer.tasks'. [/home/osboxes/Desktop/runtime-5.0.2/tools-local/tasks/installer.tasks/installer.tasks.csproj]
/root/.nuget/packages/microsoft.sourcelink.common/1.1.0-beta-20206-02/build/Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [/home/osboxes/Desktop/runtime-5.0.2/tools-local/tasks/installer.tasks/installer.tasks.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory '/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/src/System.Private.CoreLib'. [/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/src/System.Private.CoreLib/System.Private.CoreLib.csproj]
/root/.nuget/packages/microsoft.build.tasks.git/1.1.0-beta-20206-02/build/Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory '/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/src/System.Private.CoreLib'. [/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/src/System.Private.CoreLib/System.Private.CoreLib.csproj]
/root/.nuget/packages/microsoft.sourcelink.common/1.1.0-beta-20206-02/build/Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/src/System.Private.CoreLib/System.Private.CoreLib.csproj]
/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/runtime.proj(32,5): error MSB3073: The command ""/home/osboxes/Desktop/runtime-5.0.2/src/coreclr/build-runtime.sh" -x64 -debug -os Linux" exited with code 1.
    0 Warning(s)
    7 Error(s)
```

**Comment by danmosemsft** [comment]
This is with a clean clone (git clean -fdx) of recent master?

**Comment by ViktorHofer** [comment]
I assume you didn't check the repo out via git or deleted the .git folder afterwards?

**Comment by Maniues** [comment]
Thanks. I used release download. I build it, but I have problem with binaries: https://github.com/dotnet/runtime/issues/47153

**Comment by ViktorHofer** [comment]
The repository should still work without a .git folder in the working directory. We need to repro if this scenario is indeed broken. Reopening.

**Comment by ViktorHofer** [comment]
cc @trylek @jkoritzinsky

**Comment by ViktorHofer** [comment]
Reprod locally by checking out the repo and deleteing the ".git" folder. Here's what I get:

```
  C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\eng'. [C:\git\runtime6\eng\empty.csproj]
  C:\Users\vihofer\.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21062.10\tools\Version.targets(53,5): error : SourceRevisionId is not set, which means the SourceLink targets are not included in the build. Those are needed to produce a correct sha for our build outputs. [C:\git\runtime6\eng\empty.csproj]
  Build failed with exit code 1. Check errors above.
  See log: "C:\git\runtime6\src\coreclr\..\..\artifacts\log\Debug\GenerateVersionHeaders_windows__x64__Debug.binlog"
  BUILD: Error: Failed to generate version headers.
C:\git\runtime6\src\coreclr\runtime.proj(42,5): error MSB3073: The command ""C:\git\runtime6\src\coreclr\build-runtime.cmd" -x64 -debug" exited with code 1.

Build FAILED.

C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\tasks\installer.tasks'. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\tasks\installer.tasks'. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\tasks\installer.tasks'. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\tasks\installer.tasks'. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [C:\git\runtime6\src\tasks\installer.tasks\installer.tasks.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\System.Private.CoreLib'. [C:\git\runtime6\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\System.Private.CoreLib'. [C:\git\runtime6\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [C:\git\runtime6\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\ToolBox\SOS\DIALib'. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DIALib\DIALib.ilproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\ToolBox\SOS\DIALib'. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DIALib\DIALib.ilproj]
C:\Users\vihofer\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DIALib\DIALib.ilproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(24,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\ToolBox\SOS\DacTableGen'. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DacTableGen\DacTableGen.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.build.tasks.git\1.1.0-beta-20206-02\build\Microsoft.Build.Tasks.Git.targets(47,5): error : Unable to locate repository with working directory that contains directory 'C:\git\runtime6\src\coreclr\ToolBox\SOS\DacTableGen'. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DacTableGen\DacTableGen.csproj]
C:\Users\vihofer\.nuget\packages\microsoft.sourcelink.common\1.1.0-beta-20206-02\build\Microsoft.SourceLink.Common.targets(52,5): error : Source control information is not available - the generated source link is empty. [C:\git\runtime6\src\coreclr\ToolBox\SOS\DacTableGen\DacTableGen.csproj]
C:\git\runtime6\src\coreclr\runtime.proj(42,5): error MSB3073: The command ""C:\git\runtime6\src\coreclr\build-runtime.cmd" -x64 -debug" exited with code 1.
```

Apparently coreclr intentionally fails the build (in empty.csproj) if source control information isn't available. I'm unsure why this is the case. @tmat is it intentional that when referencing the source link packages that the build for managed project fails like in the logs above? I assume we are doing something wrong in coreclr.

**Comment by tmat** [comment]
Yes, that's intentional. Without `.git` directory we can't produce correct Source Link info. I think it's a warning though, so the build must be using warnaserror.

**Comment by ViktorHofer** [comment]
Thanks Tomas. @danmosemsft just to be absolute sure about expectations, we do want the repository to be buildable without git, right?

**Comment by danmosemsft** [comment]
@ViktorHofer I have no opinion, is there a scenario where it's important? @Maniues where did you download the sources from?

I assume official source build is not affected by this as I assume it's still done in a (larger) git repo.

**Comment by ViktorHofer** [comment]
Based on the broad support of git I'm not overly concerned but as a principle we always tried to not depend on source control features directly in the build. The warning log level makes sense IMO as it impacts the produced binaries but it shouldn't fail the build.

Yes, this is purely a discussion about whether we should support building without git initialized locally.

**Comment by danmosemsft** [comment]
I guess the one thing I was wondering was whether we had a link to download a tarball of the sources for this repo, as many OSS projects have. If so maybe folks would expect that actually builds. That's why I'm wondering where @Maniues got it.

**Comment by ViktorHofer** [comment]
I assume from https://github.com/dotnet/runtime/archive/master.zip

**Comment by vcsjones** [comment]
This has been a reoccurring issue (#37325, #33668, #33139, #28632), in case that helps with a decision on how to proceed. 

> I assume from https://github.com/dotnet/runtime/archive/master.zip

Yes, and there is a very visible interface to get there, it's not exactly a hidden URL to make downloads. 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/361677/105077451-87fd1a00-5a5a-11eb-8013-c20556158b81.png">

**Comment by danmosemsft** [comment]
Adding @dleeapho since he thinks about source-build all up.

@ViktorHofer do you know why you saw errors that @tmat logged as warnings? Perhaps that is enough to just make it work (although there remains the question of how we'd avoid breaking it in future)

**Comment by ViktorHofer** [comment]
> @ViktorHofer do you know why you saw errors that @tmat logged as warnings? Perhaps that is enough to just make it work 

The warnings fail the build cause they're promoted to errors by default (when using msbuild's `TreatWarningsAsError` feature, which dotnet/runtime does). I need to check if there's a way to not promote _some_ warnings with msbuild.

> although there remains the question of how we'd avoid breaking it in future

That should be doable with i.e. a nightly scheduled build that downloads the master branch and builds the repo.

For me, the most important part of this discussion is if we care about this scenario and it sounds like we do.

**Comment by tmat** [comment]
The warnings are important mostly on CI build. If ContinuousIntegrationBuild is true then they should definitely be errors. In local builds, Source Link is not that important to have enabled. On the other hand it's desirable to minimize differences between CI build and local build so that issues can be found early on and are easy to diagnose locally.

**Comment by Maniues** [comment]
> 
> 
> @ViktorHofer I have no opinion, is there a scenario where it's important? @Maniues where did you download the sources from?
>
I downloaded it from https://github.com/dotnet/runtime/releases/tag/v5.0.2
In my opinion, it's not good, when the building process requires a .git directory, because old versions are unavailable to build. Is there any resolution to bypass these errors?

**Comment by ViktorHofer** [comment]
> In my opinion, it's not good, when the building process requires a .git directory, because old versions are unavailable to build. Is there any resolution to bypass these errors?

I agree with that. I don't have a resolution ready but as a workaround you could pass in `/p:TreatWarningsAsErrors=false` when invoking `build.cmd` or `build.sh` to stop promoting warnings as errors.

**Comment by ViktorHofer** [comment]
@tmat I tend towards setting `MSBuildWarningsAsMessages` to true but unfortunately the warning doesn't pass in a `Code` attribute in the Warn task which would associate it with a warning code. What's your recommendation on this?

**Comment by vcsjones** [comment]
> because old versions are unavailable to build. Is there any resolution to bypass these errors?

If you want the path of least friction for now, you can use git:

1. `git clone https://github.com/dotnet/runtime.git`
2. `cd runtime`
3. `git checkout tags/v5.0.2`
4. build..

**Comment by tmat** [comment]
@ViktorHofer Feel free to file bug on dotnet/sourcelink to request warnings to have code associated. Another issue to consider the warning to be reported only when `ContinuousIntegrationBuild` is true.

**Comment by Maniues** [comment]
> 
> 
> > In my opinion, it's not good, when the building process requires a .git directory, because old versions are unavailable to build. Is there any resolution to bypass these errors?
> 
> I agree with that. I don't have a resolution ready but as a workaround you could pass in `/p:TreatWarningsAsErrors=false` when invoking `build.cmd` or `build.sh` to stop promoting warnings to errors.

@ViktorHofer What `/p:TreatWarningsAsErrors=false` is doing? I ran `./build.sh -c Release /p:TreatWarningsAsErrors=false` and I got the same error about .git directory

**Comment by ViktorHofer** [comment]
Yeah I just noticed that in Arcade an error is thrown unconditionally instead of a warning: https://github.com/dotnet/arcade/blob/ee0a6a7d9acc6f5886ae214b935f3e3d989235e4/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets#L53. Means my workaround won't work and @vcsjones one is probably the only way to around it until we can support this scenario completely.

**Comment by Maniues** [comment]
@ViktorHofer Is coreclr modification necessary to fix it? Are you going to work on it to fix it, or as @tmat mentioned it is on purpose and no steps will be taken?

**Comment by ViktorHofer** [comment]
> Are you going to work on it to fix it

Apparently it's not just coreclr but also the native part of libraries which would have failed later. I submitted https://github.com/dotnet/arcade/pull/6821 which should fix this in Arcade which then needs a follow-up PR in this repo. Will keep this issue updated.

**Comment by danmosemsft** [comment]
Should some of our PR validation builds blow away the.git folder to protect this?

**Comment by ViktorHofer** [comment]
Sure that's an option as well. I thought about nightly protection but I prefer your proposal.
