### ISSUE TITLE
对于单接口多实现使用心得（For single interface multiple implementation use experience）

### ISSUE THREAD

**Issue by cockroach888** [dotnet/runtime#47148]
对于单接口多实现使用心得（For single interface multiple implementation use experience）

根据相关资料查阅，以及个人研究后，总结出以下四种使用方式（希望能有所帮助）：

源码链接： 
https://github.com/cockroach888/GSA.StarTrek.dotNetFoundationTouch

Microsoft.Extensions.DependencyInjection

一、 单接口多实现使用场景
namespace GenericHost4Lib01.Sample2Interface
{
    /// <summary>
    /// 奥特曼接口
    /// </summary>
    public interface IUltraman
    {
        /// <summary>
        /// 名称
        /// </summary>
        string Name { get; }
        /// <summary>
        /// 文本
        /// </summary>
        string Text { get; }
    }
}

1） 为各实现建立独立继承接口
1. 创建继承接口
namespace GenericHost4Lib01.Sample2Interface
{
    /// <summary>
    /// 阿古茹奥特曼接口
    /// </summary>
    public interface IUltramanAgul : IUltraman
    {
    }
}

……

namespace GenericHost4Lib01.Sample2Interface
{
    /// <summary>
    /// 迪迦奥特曼接口
    /// </summary>
    public interface IUltramanTiga : IUltraman
    {
    }
}

2. 实现继承接口
using GenericHost4Lib01.Sample2Interface;

namespace GenericHost4Lib01.Sample2Indirect
{
    /// <summary>
    /// 阿古茹奥特曼
    /// </summary>
    public class UltramanAgul : IUltramanAgul
    {
        /// <summary>
        /// 唯一编号
        /// </summary>
        public string UniqueId => "Ultraman Agul";
        /// <summary>
        /// 名称
        /// </summary>
        public string Name => "Ultraman Agul";
        /// <summary>
        /// 文本
        /// </summary>
        public string Text => "阿古茹奥特曼";
    }
}

……

using GenericHost4Lib01.Sample2Interface;

namespace GenericHost4Lib01.Sample2Indirect
{
    /// <summary>
    /// 迪迦奥特曼
    /// </summary>
    public class UltramanTiga : IUltramanTiga
    {
        /// <summary>
        /// 唯一编号
        /// </summary>
        public string UniqueId => "Ultraman Tiga";
        /// <summary>
        /// 名称
        /// </summary>
        public string Name => "Ultraman Tiga";
        /// <summary>
        /// 文本
        /// </summary>
        public string Text => "迪迦奥特曼";
    }
}

3. 服务注册
.ConfigureServices((hostContext, services) =>
{
   // 接口引用 IUltraman 顶层接口，创建独立接口与实现对应。
   services.AddSingleton<Sample2Interface.IUltramanAgul, Sample2Indirect.UltramanAgul>();
   services.AddSingleton<Sample2Interface.IUltramanDyna, Sample2Indirect.UltramanDyna>();
   services.AddSingleton<Sample2Interface.IUltramanGaia, Sample2Indirect.UltramanGaia>();
   services.AddSingleton<Sample2Interface.IUltramanMax, Sample2Indirect.UltramanMax>();
   services.AddSingleton<Sample2Interface.IUltramanMebius, Sample2Indirect.UltramanMebius>();
   services.AddSingleton<Sample2Interface.IUltramanTiga, Sample2Indirect.UltramanTiga>();
})

4. 使用依赖注入服务
private Sample2Interface.IUltraman _agulService;

public MainForm(Sample2Interface.IUltramanAgul agul)
{
	_agulService = agul;

	InitializeComponent();
}

5. 使用 IServiceProvider 服务
private IServiceProvider _services;

public MainForm(IServiceProvider services)
{
	_services = services;
	var agul = services.GetService<Sample2Interface.IUltramanAgul>();

	InitializeComponent();
}

2） 继承带唯一编号接口
6. 增加唯一编号接口
namespace GenericHost4Lib01
{
    /// <summary>
    /// 单接口多实现获取指定实现接口
    /// </summary>
    public interface IUniqueOfMultipleImplementations
    {
        /// <summary>
        /// 唯一编号
        /// </summary>
        string UniqueId { get; }
    }
}

7. 继承唯一编号接口
namespace GenericHost4Lib01.Sample2Interface
{
    /// <summary>
    /// 奥特曼接口
    /// </summary>
    public interface IUltraman : IUniqueOfMultipleImplementations
    {
        /// <summary>
        /// 名称
        /// </summary>
        string Name { get; }
        /// <summary>
        /// 文本
        /// </summary>
        string Text { get; }
    }
}

8. 增加服务扩展方法
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace GenericHost4Lib01
{
    public static class UniqueOfMultipleImplementationsExtensions
    {
        /// <summary>
        /// Get unique service of type <typeparamref name="T"/> from the <see cref="IServiceProvider"/>.
        /// </summary>
        /// <typeparam name="T">The type of service object to get.</typeparam>
        /// <param name="provider">The <see cref="IServiceProvider"/> to retrieve the service object from.</param>
        /// <param name="uniqueId">The Unique Id.</param>
        /// <returns>A service object of type <typeparamref name="T"/> or null if there is no such service.</returns>
        public static T GetService<T>(this IServiceProvider provider, string uniqueId)
        {
            if (provider == null)
            {
                throw new ArgumentNullException(nameof(provider));
            }

            var implementations = provider.GetServices<T>();

            if (implementations == null || implementations.Count() <= 0)
            {
                throw new InvalidOperationException($"No service for type '{nameof(T)}' has been registered.");
            }

            foreach (var item in implementations)
            {
                if (item is IUniqueOfMultipleImplementations result && result.UniqueId == uniqueId)
                {
                    return item;
                }
            }
            return default(T);
        }
    }
}

9. 接口实现
using GenericHost4Lib01.Sample2Interface;

namespace GenericHost4Lib01.Sample2Direct
{
    /// <summary>
    /// 阿古茹奥特曼
    /// </summary>
    public class UltramanAgul : IUltramanAgul
    {
        /// <summary>
        /// 唯一编号
        /// </summary>
        public string UniqueId => "Ultraman Agul";
        /// <summary>
        /// 名称
        /// </summary>
        public string Name => "Ultraman Agul";
        /// <summary>
        /// 文本
        /// </summary>
        public string Text => "阿古茹奥特曼";
    }
}

……

using GenericHost4Lib01.Sample2Interface;

namespace GenericHost4Lib01.Sample2Direct
{
    /// <summary>
    /// 迪迦奥特曼
    /// </summary>
    public class UltramanTiga : IUltramanTiga
    {
        /// <summary>
        /// 唯一编号
        /// </summary>
        public string UniqueId => "Ultraman Tiga";
        /// <summary>
        /// 名称
        /// </summary>
        public string Name => "Ultraman Tiga";
        /// <summary>
        /// 文本
        /// </summary>
        public string Text => "迪迦奥特曼";
    }
}

10. 服务注册
.ConfigureServices((hostContext, services) =>
{
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanAgul>();
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanDyna>();
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanGaia>();
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanMax>();
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanMebius>();
   services.AddSingleton<Sample2Interface.IUltraman, Sample2Direct.UltramanTiga>();
})

11. 使用 IServiceProvider 服务
private IServiceProvider _services;

public MainForm(IServiceProvider services)
{
	_services = services;

	InitializeComponent();
}

private IUltraman GetServiceOfUniqueId(string uniqueId)
{
	return _services.GetService<IUltraman>(uniqueId);
}

3） 增加接口与具体实现扩展
/// <summary>
/// Get unique service of type <typeparamref name="TService"/> from the <see cref="IServiceProvider"/>.
/// </summary>
/// <typeparam name="TService">The type of service object to get.</typeparam>
/// <typeparam name="TImplementation">The type of the implementation to use.</typeparam>
/// <param name="provider">The <see cref="IServiceProvider"/> to retrieve the service object from.</param>
/// <returns>A service object of type <typeparamref name="TService"/> or null if there is no such service.</returns>
public static TService GetService<TService, TImplementation>(this IServiceProvider provider)
{
	if (provider == null)
	{
		throw new ArgumentNullException(nameof(provider));
	}

	var implementations = provider.GetServices<TService>();

	if (implementations == null || implementations.Count() <= 0)
	{
		throw new InvalidOperationException($"No service for type '{nameof(TService)}' has been registered.");
	}

	return implementations.FirstOrDefault(t => t.GetType() == typeof(TImplementation));
}

4） 增加临时性关键字服务
1. 添加临时性服务
.ConfigureServices((hostContext, services) =>
{
   // 统一接口实现，增加临时性获取服务。
   services.AddSingleton<Sample2Direct.UltramanAgul>();
   services.AddSingleton<Sample2Direct.UltramanDyna>();
   services.AddSingleton<Sample2Direct.UltramanGaia>();
   services.AddSingleton<Sample2Direct.UltramanMax>();
   services.AddSingleton<Sample2Direct.UltramanMebius>();
   services.AddSingleton<Sample2Direct.UltramanTiga>();

   services.AddTransient<Func<string, Sample2Interface.IUltraman>>(serviceProvider => key =>
   {
	   switch (key)
	   {
		   case "Agul":
			   return serviceProvider.GetService<Sample2Direct.UltramanAgul>();
		   case "Dyna":
			   return serviceProvider.GetService<Sample2Direct.UltramanDyna>();
		   case "Gaia":
			   return serviceProvider.GetService<Sample2Direct.UltramanGaia>();
		   case "Max":
			   return serviceProvider.GetService<Sample2Direct.UltramanMax>();
		   case "Mebius":
			   return serviceProvider.GetService<Sample2Direct.UltramanMebius>();
		   case "Tiga":
			   return serviceProvider.GetService<Sample2Direct.UltramanTiga>();
		   default:
			   return default(Sample2Interface.IUltraman);
	   }
   });
})

2. 使用依赖注入服务
private Sample2Interface.IUltraman _ultraman;

public MainForm(Func<string, Sample2Interface.IUltraman> services)
{
	_ultraman = services("Agul");

	InitializeComponent();
}

3. 使用 IServiceProvider 服务
private Sample2Interface.IUltraman _ultraman;

public MainForm(IServiceProvider services)
{
	_ultraman = services.GetRequiredService<Func<string, Sample2Interface.IUltraman>>()("Agul");

	InitializeComponent();
}

**Comment by huoyaoyuan** [comment]
Hello, you may create this issue at wrong position. Here is for discussion about bugs and improvement of .NET, and the topics should be non-trivial.

你好，这个issue更适合你自己的repo，而不是这里。这里是用来讨论.NET本身的bug和改进的，话题应当有深度。

**Comment by danmosemsft** [comment]
closing as above.
