### ISSUE TITLE
CoreCLR fails to initialize, spits out 0x80004005

### ISSUE THREAD

**Issue by ldub** [dotnet/runtime#47143]
The full description of the repro is here: https://github.com/actions/runner/issues/918

When running the CoreCLR-based app with `COMPlus_EnableDiagnostics=0 COREHOST_TRACE=1`, it still fails to start, and the trace doesn't provide any actionable info: https://gist.github.com/ldub/05807068a8f0cc9cc3793b511b0c78ba#file-zz-coreclr-issue-log

Could the tracing be improved? Are there any other diagnostics which would help? Because other people have seen this on read-only filesystems in docker, it appears likely that CoreCLR is attempting to write to something in the `/nix/` directory which is read-only, so it seems possible that `COMPlus_EnableDiagnostics=0` is not working.

Related to: 
* https://github.com/dotnet/runtime/issues/9336
* https://github.com/dotnet/docs/issues/10217
* https://github.com/actions/runner/issues/918

**Comment by danmosemsft** [comment]
Would `strace` help suggest whether/what problematic write it is trying to do?

**Comment by danmosemsft** [comment]
The host mostly uses fine grained error codes so most likely the failure is inside coreclr proper, inside `coreclr_initialize`. A debugger is probably required.

**Comment by ldub** [comment]
I've added the output of `strace -E COMPlus_EnableDiagnostics=0 ./result/run.sh` to my gist: https://gist.github.com/ldub/8c89ea32d8824c9969abcebd2e71ff6f#file-zz-strace-log

**Comment by janvorli** [comment]
@ldub can you please try it with just simple .NET core hello world? Btw, the strace that you've captured was not for the .NET process but for the shell, you'd need to add `-f` parameter to strace to let it follow child process forks and dump info from those.

Does `dotnet new console` fail with the same error? If it does, can you please try the same thing with .NET 5.0? .NET 5.0 has more fine-grained error codes if the failure happens during the PAL layer initialization, which is the most frequent place when things fail like this.
Can you please share which Linux distro you are running it on and if you are running it inside a docker container or directly in a VM / on a physical hardware?

**Comment by ldub** [comment]
Hey @janvorli , sorry for the delay here! We are using NixOS on an AWS VM (i'm testing on a t3.xlarge, if it matters). `dotnet new console` works fine:

```
$ nix-shell -p coreclr -p dotnet-sdk

[nix-shell:~]$ mkdir dn-hello-world

[nix-shell:~]$ cd dn-hello-world/

[nix-shell:~/dn-hello-world]$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/lev/dn-hello-world/dn-hello-world.csproj...
  Restore completed in 212.84 ms for /home/lev/dn-hello-world/dn-hello-world.csproj.

Restore succeeded.


[nix-shell:~/dn-hello-world]$ dotnet build
Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 72.84 ms for /home/lev/dn-hello-world/dn-hello-world.csproj.
  dn-hello-world -> /home/lev/dn-hello-world/bin/Debug/netcoreapp2.1/dn-hello-world.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.34

[nix-shell:~/dn-hello-world]$ dotnet run
Hello World!

[nix-shell:~/dn-hello-world]$
```

**Comment by ldub** [comment]
Also, thanks a lot in advance for looking at this issue!

I have also published the output of `strace` with the `-f` option: https://gist.github.com/ldub/05807068a8f0cc9cc3793b511b0c78ba#file-zz-strace-log

And, for context, `/nix` is indeed a readonly filesystem on NixOS, which seems likely to be part of the reason why our issue is happening. I would also be happy to provide you with a temporary NixOS instance and some interactive Nix help if you were willing to help us investigate this!

**Comment by matthewbauer** [comment]
So the 0x80004005 error can happen for a lot of reasons, but in this case it looks like `strip -S` from Nixpkgs is being running on the dotnet binaries and messing them up. In Nixpkgs, everythnig in $out/bin/* is stripped automatically. Adding `dontStrip = true` to stdenv.mkDerivation avoids doing this.

This appears to be a regression in `strip -S`, because strip from GNU binutils 2.31.1 doesn't do this, but 2.34 does.

**Comment by janvorli** [comment]
@matthewbauer do I understand it properly that if you don't do the stripping using the new version of strip, then the issue reported here doesn't occur?

**Comment by matthewbauer** [comment]
> @matthewbauer do I understand it properly that if you don't do the stripping using the new version of strip, then the issue reported here doesn't occur?

Yes

**Comment by vitek-karas** [comment]
Given https://github.com/dotnet/runtime/issues/47143#issuecomment-774168402 seems to indicate that this is a problem external to .NET. Please feel free to reopen the issue if that's not the case.
