### ISSUE TITLE
Analyzer proposal: Warn on missing CONTRACTS_FULL when using contracts

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#47157]
Using attributes from `System.Diagnostics.Contracts` requires `CONTRACTS_FULL` to be defined. IMO it worth a warning when `CONTRACTS_FULL` is missing, as the developer may mistakenly assume that the attribute will be correctly tracked by analysis tools (e.g. CA1806 which warns on Pure methods).

FYI @mavasani @Evangelink

**Comment by stephentoub** [comment]
If you define CONTRACTS_FULL and use almost any of the asserts from System.Diagnostics.Contract, the app will blow up unless you're also using the rewrite. Just adding an analyzer for this will lead people down the wrong path.  The S.D.Contracts system is largely defunct and is not being invested in.

**Comment by Youssef1313** [comment]
@stephentoub Thanks for clarification. The scenario for which I opened this issue was a user applying `Pure` to instruct CA1806 to warn for unused return values. He was missing `CONTRACTS_FULL`, and reported a false negative against roslyn-analyzers (https://github.com/dotnet/roslyn-analyzers/issues/4657). So I thought such an analyzer can help catching this scenario.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/34098#issuecomment-604439020

**Comment by Youssef1313** [comment]
@stephentoub Should CA1806 drop support for `System.Diagnostics.Contracts.PureAttribute` then, and wait for a new runtime attribute?

**Comment by stephentoub** [comment]
> Should CA1806 drop support for System.Diagnostics.Contracts.PureAttribute then, and wait for a new runtime attribute?

If someone is relying on CA1806 looking at [Pure], I'm not sure it's worth breaking them.  But I don't want to encourage further use of [Pure].
