### ISSUE TITLE
Obsolete Socket.UseOnlyOverlappedIO

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#47163]
## Background and Motivation

This property it is only meaningful on .NET Framework where it functions as a socket-level switch between IOCP and Win32 event based overlapped IO. 

.NET (Core) Windows sockets are entirely IOCP-based, and the concept of "overlapped IO" does not exist on other platforms, therefore the property contains empty logic, and there is no chance we will ever implement it. To avoid confusion, I suggest to obsolete and hide it it together with the related flag in `SocketInformationOptions`.

## Proposed API

```diff
public class Socket
{
+   [Obsolete]
+   [EditorBrowsable(EditorBrowsableState.Never)]
    public bool UseOnlyOverlappedIO { get; set; }
}

public enum SocketInformationOptions
{
    NonBlocking = 1,
    Connected = 2,
    Listening = 4,
+   [Obsolete]
+   [EditorBrowsable(EditorBrowsableState.Never)]
    UseOnlyOverlappedIO = 8,
}

```

## Risks

Breaking `/warnaserror` builds when porting to .NET 6. (Which may actually prevent runtime failures.)

**Comment by Wraith2** [comment]
Is it also worth marking it as non browsable?

**Comment by antonfirsov** [comment]
> Is it also worth marking it as non browsable?

In my opinion - yes, so updated the proposal.

**Comment by karelz** [comment]
Triage: We agree, it is no-op on .NET Core, let's obsolete it.

**Comment by terrajobst** [comment]
* Looks good
* It feels over-engineered to add a diagnostic ID to this obsoletion

```C#
namespace System.Net.Sockets
{
    public class Socket
    {
        [Obsolete]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool UseOnlyOverlappedIO { get; set; }
    }
    public enum SocketInformationOptions
    {
        NonBlocking = 1,
        Connected = 2,
        Listening = 4,
        [Obsolete]
        [EditorBrowsable(EditorBrowsableState.Never)]
        UseOnlyOverlappedIO = 8,
    }
}
```
