### ISSUE TITLE
TechEmpower performance regression: plaintextPlatform-mono-llvm-jit and plaintextPlatform-mono-llvm-aot

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#47187]
5% regression was introduced by https://github.com/dotnet/runtime/commit/c31d8ae49bcf8abfe3518c51bc2ba677a1e3aaf9

Before this change the default on linux was preemptive (which was implicitly changed during the autoconf->cmake switch) and after this change it's hybrid.

<img width="1382" alt="Screen Shot 2021-01-19 at 9 39 14 AM" src="https://user-images.githubusercontent.com/52458914/105083203-98b18e00-5a62-11eb-8530-1ae94e766132.png">

**Comment by fanyang-mono** [comment]
@lambdageek prefers to use hybrid as the default.
@CoffeeFlux suggested to explicitly use preemptive for TechEmpower benchmarks.

**Comment by naricc** [comment]
It looks like we have several regressions in the microbenchmark runs due to the same change (line to auto generated issue): https://github.com/DrewScoggins/performance-2/issues/3793

**Comment by naricc** [comment]
This one too, I think: https://github.com/dotnet/runtime/compare/059b17eeaa4ef8c30501518b418565ccd804bd7e...69582a15e9b2954041d3a3b536fd8ff4a09842ef

**Comment by naricc** [comment]
Also some of these: https://github.com/DrewScoggins/performance-2/issues/3794

**Comment by fanyang-mono** [comment]
preemptive modes has been added to TE runs for mono via https://github.com/aspnet/Benchmarks/pull/1639. Closing this issue now.
<img width="1316" alt="Screen Shot 2021-03-04 at 3 20 41 PM" src="https://user-images.githubusercontent.com/52458914/110025711-be86af80-7cfd-11eb-8f4b-fbb010f982f1.png">

**Comment by fanyang-mono** [comment]
No more further actions.
