### ISSUE TITLE
Analyzer proposal: Use String.Contains(char) instead of String.Contains(String)

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#47180]
**Suggested category:** Performance
**Suggested default severity:** Suggestion
**Fix is breaking or non-breaking:** Non-breaking

### Cause

This rule locates calls to `Contains(String)` when the string consists of a single `char`, and suggests using `Contains(char)` instead

### Rule description

When `Contains(String)` is used with a single `char`, the call can be safely substituted with `Contains(char)`.

### Additional context

dotnet/runtime#24068
dotnet/coreclr#15740
dotnet/runtime#36310

**Comment by mavasani** [comment]
Tagging @carlossanlop @buyaa-n - .NET API analyzer suggestion.

**Comment by carlossanlop** [comment]
Seems pretty straightforward. There was a [previous effort](https://github.com/dotnet/coreclr/pull/15740) to manually replace instances of `String.Contains(string)` with `String.Contains(char)`, so an analyzer should automatically find any new instances for us from now on.

Suggested severity: Warning
Suggested category: Performance
Suggested milestone: Future (but we welcome contributions for 6.0)
Analyzer size: Small
Fixer size: Small


Should cover all overloads, and only where a literal is passed as argument:

```cs
string str = "whatever";
string find = "a";

// Yes
str.Contains("a");
str.Contains("a", StringComparison.InvariantCultureIgnoreCase);

// No
str.Contains(find);
str.Contains(find, StringComparison.InvariantCultureIgnoreCase);
```

**Comment by GrabYourPitchforks** [comment]
This as proposed is not a breaking change, but we need to take care if we extend this analyzer to other methods (`IndexOf`, etc.). Switching from string to char in those methods is an observable behavioral change.

**Comment by terrajobst** [comment]
* Makes sense
* Is this the only overload that we should do this for?

**Comment by MeikTranel** [comment]
@carlossanlop i'd like to help with this one 🙋‍♂️

**Comment by buyaa-n** [comment]
> i'd like to help with this one 🙋‍♂️

@MeikTranel thanks, assigned to you

**Comment by MeikTranel** [comment]
@buyaa-n i have a question regarding the description - how detailed is the description expected to be? Because there's two very different reasons this analyzer is needed:

1. A user had existing code where `string.Contains(string)` was invoked because they were aware that `string.Contains(char)` used to fall back to `System.Linq.Enumerable.Contains(this string, char)` incurring a very steep performance hog and hence went on to use the string overload.
2. A user wrote code during a time where `String.Contains(char)` was available, but was unaware of the slight performance benefits of using it over `String.Contains(string)`.

My question is - if the description describes why the change is suggested - we should probably tell `User 1.` "It's ok we fixed this you may now use this" and the `User 2.` "Hey, you might want to check the char overload because its slightly faster".

The latter explanation would most certainly fit both cases, but i can totally see an experienced user calling foul and suppressing it because they remember doing an investigation regarding the `str.Contains('a')` performance issue.

**Comment by buyaa-n** [comment]
For me the 2nd message sounds good enough for both cases, could also include the offered overload `String.Contains(char)`, so that `User 1` could realize that this will not fall back to `System.Linq.Enumerable.Contains(this string, char)`.

 We might also want to check if the `String.Contains(char)` overload exist before suggesting that

**Comment by MeikTranel** [comment]
I'm pretty much done except two remaining tasks:

- handling the short circuit when the `String.Contains(char[, StringComparison])` isnt available
- cleanup and finalizing resource strings etc.

hoping to finish this by this weekend... just one quick question:

How do we handle analyzer tests that are only reasonable on certain frameworks?

![image](https://user-images.githubusercontent.com/6466560/108775214-159fbe00-7561-11eb-994b-6af8000da4eb.png)

The obvious solution would be to just remove them from the compiled test assembly by using `#if NETCOREAPP` but i want to take the temperature if thats cool with the team first 🤣

**Comment by buyaa-n** [comment]
> How do we handle analyzer tests that are only reasonable on certain frameworks?

You can specify `ReferenceAssemblies.NetCore.NetCoreApp30` in the test, not sure which NetCoreApp version you should use. Example: 
https://github.com/dotnet/roslyn-analyzers/blob/1ead3c96987ec6200209ab602529b9bab573833d/src/NetAnalyzers/UnitTests/Microsoft.NetFramework.Analyzers/DoNotUseInsecureDtdProcessingDoNotUseSetInnerXmlTests.cs#L21

Anyway, after you add the "handling the short circuit when the `String.Contains(char[, StringComparison])` isn't available" you don't need to worry about that right? Actually might better to keep the test as is to show that it is bailing out when the char overload is not available

**Comment by MeikTranel** [comment]
The draft PR is now up and mostly ready to pass things back to the team - one last requirements question remains tho...
@carlossanlop suggested that the default severity should be `Warning` - testing against the suggested repositories it occured to me that maybe this should be an `Info` level diagnostic. 
This is probably not the first time y'all encountered this basically what happens alot is that there would be a multitargeted project across the latest dotnet release like `net5.0` as well as some form of `netstandard2.0` or even `net47` for those still supporting full framework usage. 
I'm not sure about the market coverage today, but if roslyn, roslyn-analyzers and runtime are anything to go by then consumers will probably constantly be faced with the issue that only dotnet beyond `netcoreapp3.1` and `netstandard2.1` has the overloads and the more popular `netstandard2.0` doesnt. And now we either have to use compiler defines, severity configs or `SuppressWarning` statements to work around the fact that only some of the TFMs support it.

**Comment by carlossanlop** [comment]
@MeikTranel can you share the error output you get if you turn on this analyzer in the runtime repo and then build it?

To test your analyzer in runtime:

- Clone dotnet/runtime
- Edit this file: https://github.com/dotnet/runtime/blob/1bf0610e30dff8b3fb1328a2a8772e738d73157a/eng/CodeAnalysis.ruleset#L10
- Add a row with your RuleId
- Go to `C:\Users\<your_usename>\.nuget\packages\microsoft.codeanalysis.netanalyzers\<latest_version>\analyzers\dotnet\cs` backup the original DLLs you find there, then copy and paste the ones you generated when building your roslyn-analyzers branch with your new analyzer.
- Build runtime with `.\build.cmd clr+libs`
- Share the list of errors you get so we get an idea of how noisy it is.

We should keep in mind this analyzer may improve the runtime performance if we fix all the suggested instances, so a warning severity makes sense.

**Comment by mavasani** [comment]
> We should keep in mind this analyzer may improve the runtime performance if we fix all the suggested instances, so a warning severity makes sense.

@carlossanlop I thought the initial bar for analyzers to be warnings by default was that they need to flag critical functional issues. Performance improvement analyzers should not be warnings by default. Has this stance changed recently? Can you confirm in the dotnet/runtime triage meeting?

**Comment by buyaa-n** [comment]
> basically what happens alot is that there would be a multitargeted project across the latest dotnet release like net5.0 as well as some form of netstandard2.0 or even net47 for those still supporting full framework usage.
> I'm not sure about the market coverage today, but if roslyn, roslyn-analyzers and runtime are anything to go by then consumers will probably constantly be faced with the issue that only dotnet beyond netcoreapp3.1 and netstandard2.1 has the overloads and the more popular netstandard2.0 doesnt. And now we either have to use compiler defines, severity configs or SuppressWarning statements to work around the fact that only some of the TFMs support it.

@MeikTranel isn't the analyzer bail out when the overload not exist? If it does then i wouldn't expect it to warn or make noise for lower versions

**Comment by MeikTranel** [comment]
>isn't the analyzer bail out when the overload not exist?

Yes and that works as you expected but when a single project builds against two TFMs where one offers the overload and the other doesn't, you're left with a fixer that'll immediately generate a build error for the older target framework.

This is a general issue with analyzers that remind of better alternatives that were only  introduced in later successions of the frameworks.

**Comment by buyaa-n** [comment]
Oh sorry, I misunderstood, that makes sense now i see the original description had `Suggested default severity: Suggestion` but in our triage, we made it `Suggested severity: Warning` i guess we did that because was not expecting a false positives. And looks like we didn't talk about severity in the API review meeting. By accounting for the false positives in the multitargeted environment i agree with change the severity into `Info` level. 

For the failures in runtime repo, i am not sure if we want to `ifdef` those multitargeted builds, but it would be helpful if you could attach the list or warnings found
cc @terrajobst @bartonjs @stephentoub

**Comment by mavasani** [comment]
>  in our triage, we made it Suggested severity: Warning i guess we did that because was not expecting a false positives.

IMO, analyzers reporting performance issues should never be a warning by default in the .NET SDK, even if we expect no false positives. Only critical functional or security issues should be candidate for being warnings by default.

**Comment by stephentoub** [comment]
This should not be a warning.

**Comment by buyaa-n** [comment]
> IMO, analyzers reporting performance issues should never be a warning by default in the .NET SDK, even if we expect no false positives. Only critical functional or security issues should be candidate for being warnings by default.

@mavasani that makes sense to me, i will keep that in mind while triaging

**Comment by buyaa-n** [comment]
@stephentoub do we want to fix the warnings found in runtime? Sounds like we need to do `ifdef` for multitargeted builds

**Comment by MeikTranel** [comment]
I have the fixes ready for runtime locally - it's just one that would actually surface for consumers and another one in testing/infrastructure code. It's pretty late in Germany so I hope y'all can live with me opening up the PR tomorrow 😊

**Comment by buyaa-n** [comment]
Thanks, @MeikTranel, sounds good, i don't think we need an issue with that, you can reference this issue in your PR

**Comment by stephentoub** [comment]
This was implemented as CA1847. Thanks!

**Comment by xtqqczze** [comment]
Fixed by https://github.com/dotnet/roslyn-analyzers/pull/4908.
