### ISSUE TITLE
Support immutable types in Microsoft.Extensions

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#47191]
This issue tracks support for using c# records in Microsoft.Extensions.

# Work Items

- [ ] [Explore options immutability](https://github.com/dotnet/runtime/issues/43359)
- [x] [Support immutable types with configuration binding](https://github.com/dotnet/runtime/issues/43662)

**Comment by SteveDunn** [comment]
@maryamariyan / @davidfowl - there's an open PR for https://github.com/dotnet/runtime/issues/43662

**Comment by eerhardt** [comment]
Half of this feature was completed in .NET 7. We will consider the rest in a future release. Moving this issue out of the 7.0 milestone.

**Comment by davidfowl** [comment]
😢

**Comment by maryamariyan** [comment]
Closing this one as redundant since there's only one issue left here and that is marked 8.0 already.
