### ISSUE TITLE
JsonSerializer.SerializeAsync throws TypeLoadException after migrating from 3.1 to 5.0

### ISSUE THREAD

**Issue by Marusyk** [dotnet/runtime#47199]
### Description

There is the following generic code
```
public async Task Add(object data)
{
	await using var stream = new MemoryStream();
	await JsonSerializer.SerializeAsync(stream, data, data.GetType());
}
```
in some place, it called like `await Add(new AnalyticData("messageType", "Number", eventData.EnqueuedTime.UtcDateTime, eventData.Body.Span));`
where `AnalyticData` is
```
public class AnalyticData
{
	public AnalyticData(string eventType, string number, DateTime dateTime, ReadOnlySpan<byte> payload)
	{
		EventType = eventType;
		Number = number;
		Size = payload.Length;
		DateTime = dateTime;
		Payload = Convert.ToBase64String(payload);
	}

	public string EventType { get; }
	public int Size { get; }
	public DateTime DateTime { get; }
	public string Number { get; }
	public string Payload { get; }
}
```

It used to work fine with `<TargetFramework>netcoreapp3.1</TargetFramework>`. After upgrading to `<TargetFramework>net5.0</TargetFramework>` I got the error at `await JsonSerializer.SerializeAsync(stream, data, data.GetType());`

> System.TypeLoadException: The generic type 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5' was used with an invalid instantiation in assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
>    at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
>    at System.RuntimeTypeHandle.Instantiate(Type[] inst)
>    at System.RuntimeType.MakeGenericType(Type[] instantiation)
>    at System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
>    at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
>    at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
>    at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
>    at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
>    at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
>    at System.Text.Json.JsonSerializer.WriteAsyncCore[TValue](Stream utf8Json, TValue value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)

### Regression?

Definitely yes! The same code works well in netcoreapp3.1

### Update
The issue is gone when I add the constructor to the AnalyticData
```
public AnalyticData()
{
}
```
it works only with a public constructor. 
Could anyone explain what's changed?

**Comment by huoyaoyuan** [comment]
It may be caused by internal implementation detail change.
If the constructor is called using reflection emit directly, it will success. However, if any generic type is used to store parameter information, it will fail.

ref structs isn't truly compatible for reflection and generic-ful usage. I'd suggest you to replace with `ReadOnlyMemory` in constructor.
