### ISSUE TITLE
Socket.Disconnect only allows async connect after disconnect

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#47206]
We have code that explicitly fails a sync Connect attempt on a socket that has previously been disconnected. See here: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L830

From reading the MSDN docs on DisconnectEx, I don't see this limitation described there. So it's not clear that this is a Windows limitation. 

If there's a good reason to have this limitation, we should document it. If not, we should just remove the limitation.

**Comment by karelz** [comment]
Triage: @scalablecory remembers that there was some weird behavior in the space.
No customers complaining (disconnecting is rather advanced anyway and people would do async anyway), not worth the effort, closing.
