### ISSUE TITLE
X509Chain status NotSignatureValid on Linux

### ISSUE THREAD

**Issue by henriko2018** [dotnet/runtime#47215]
### Description

I have some code that verifies PKCS#7 signatures. The signing certificate is issued by a self-signed certificate that is not trusted by default, but that is OK - my code handles that, and it works fine on my development machine, which is running Windows 10. The problem is that we're using Docker and Kubernetes with Linux containers for test and production, and it doesn't work there. I have reproduced the problem with a console app with the following code:

	// Signature:
	var signature = System.IO.File.ReadAllText("Signature.txt");
	var signedCms = new SignedCms();
	signedCms.Decode(Convert.FromBase64String(signature));
	signedCms.CheckSignature(true); // Cannot use false here because .NET does not trust a root cert that is not in the OS trusted root store.
	var signingCert = signedCms.SignerInfos[0].Certificate;
	//Console.WriteLine("Signing certificate:");
	//Console.WriteLine(signingCert);

	// Root cert:
	var certString = System.IO.File.ReadAllText("TrustedRoot.crt");
	var trustedRootCert = new X509Certificate2(Convert.FromBase64String(certString));
	//Console.WriteLine("Trusted root:");
	//Console.WriteLine(trustedRootCert);

	// Build certificate chain and check status:
	var chain = new X509Chain();
	chain.ChainPolicy.ExtraStore.Add(trustedRootCert);
	chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
	Console.WriteLine("Chain status:");
	Console.WriteLine(chain.Build(signingCert));
	foreach (var chainStatus in chain.ChainStatus)
		Console.WriteLine(chainStatus.Status);

On Windows, this outputs:

    Chain status:
    False
    UntrustedRoot

As said, that is OK, since I have other means to check for root trust (comparing chain element certificate with a hard-coded one). But on my WSL Ubuntu (18.04), the output is:

    Chain status:
    False
    NotSignatureValid
    UntrustedRoot

Notice "NotSignatureValid". This means my code doesn't work, because I cannot ignore this error. 

This is with .NET Core 3.1 and 5.0. Trying the same with 2.1 outputs:

    Chain status:
    False
    UntrustedRoot

just like on Windows, and the reason for that must be changes between .NET Core 2 and 3. I found a similar issue here: #31569

Is there a way to work around this? I tried adding the root certificate to the trusted CA list, but didn't get rid of the NotSignatureValid status.

I actually created a complete repro with instructions: https://github.com/henriko2018/VerificationIssue

**Comment by vcsjones** [comment]
It looks like openssl thinks the signature on the root certificate is invalid. To reproduce from the command line:

```shell
openssl verify -CAfile TrustedRoot.pem -check_ss_sig cert.pem
```

Where `TrustedRoot.pem` is the PEM encoding of your root certificate and `cert.pem` is the PEM encoded certificate from your CMS signature.

```
C = SE, O = Nordea Bank AB (publ), CN = Nordea Test Ticket CA 03
error 7 at 0 depth lookup: certificate signature failure
error TrustedRoot.pem: verification failed
139684717614400:error:04091068:rsa routines:int_rsa_verify:bad signature:../crypto/rsa/rsa_sign.c:220:
139684717614400:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:../crypto/asn1/a_verify.c:170
```

Without `-check_ss_sig` it does not reproduce, but that flag is set that flag here:

https://github.com/dotnet/runtime/blob/d76ede7639db0af0f87836c4aaa7670aa4653e7f/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_x509.c#L233

**Comment by vcsjones** [comment]
It seems that Windows also checks the signature on self-signed certificates, so it makes sense that `X509_V_FLAG_CHECK_SS_SIGNATURE` is set when building the chain with openssl. It's curious though that Windows does not perceive the certificate to be invalid as well.

@bartonjs does anything jump out at you here?

**Comment by bartonjs** [comment]
> @bartonjs does anything jump out at you here?

Nope.  I just checked the signature of the self-signed cert by hand, and it looks right to me.  Do we know which level gets the NotSignatureValid?  Maybe I'm looking at the wrong one.

**Comment by vcsjones** [comment]
>  Do we know which level gets the NotSignatureValid? Maybe I'm looking at the wrong one.

The root. Quick bash paste:

```shell
cat <<- "CERT" > /tmp/root.pem
-----BEGIN CERTIFICATE-----
MIIFTzCCAzegAwIBAgICJ74wDQYJKoZIhvcNAQELBQAwUDELMAkGA1UEBhMCU0Ux
HjAcBgNVBAoTFU5vcmRlYSBCYW5rIEFCIChwdWJsKTEhMB8GA1UEAxMYTm9yZGVh
IFRlc3QgVGlja2V0IENBIDAzMB4XDTE1MDExMzEyMjE1OFoXDTI1MDExMzEyMjE1
OFowUDELMAkGA1UEBhMCU0UxHjAcBgNVBAoTFU5vcmRlYSBCYW5rIEFCIChwdWJs
KTEhMB8GA1UEAxMYTm9yZGVhIFRlc3QgVGlja2V0IENBIDAzMIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEA0Dl5Kvgs9RshZnslpDYtN0uCX+1AqCzRrWs8
yCBL0K5YFygE6thP8jyMZne4PU397/49MioiaDFt1H601oArCriFVzkDRoxDfSS0
hE2N2C97+p9drNNpgEdYUWy/Cvpofp1cMLKyeJPpypffcy8CsKlcCIUu9RK3MPGZ
JhgdJVN8UxHV7XQ+VifjDyDnajREbc6ct2APxXMWwtGK678KMtnDHGu+x8ALWDFB
EBQ2VFPyrSomJxCA5Ufoa+ATQpvwLKszHn3EHEIzdXmdO8GLlY4F+7StuLzGRCNy
3fmChDiVWSYONk8TUvEbuQpdqGRZuxO8J3ioqllC76fTOfKaNZ1uCwFvnE+hrHs6
s/5Jr0rrF8ElWipHebyJwFkxA7Ugq/fuYDTr3UsgUh1ZzEAlSvVMgohANVQWwRWX
R2Itp4dyJN6ATRqycYDbAVgVs8VFELAAhGeHJw5z2t2RmOxAV8AuTRf0Um5WxV/9
jzoefFUrJ2fWJaguuAh9BttoAnDNr9/7KdUgB4aMI21ThVGBq9AjWWPIAT4BZ8UG
E0fH48Q57HePH+VE1EUPmtxBvCgNPbD6cngGiaUStdO0abRap41bJfQFsVgTdiGR
gcpvH0l87dUZaXRLfj9EY/3thwUxp890hBNtVTHNY+2TpFmYTesSbjsbnlZx17PU
bztkZ7ECAwEAAaMzMDEwDwYDVR0TAQH/BAUwAwEB/zARBgNVHQ4ECgQIQCbpVlpk
VyAwCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4ICAQCGxPMiTzdqAFHCm3ad
yrtqiXat13EX10XjsQkNDoP0a+T7O33Zh+xq4UkDApKw21+JE+cMsEHOkY8LsQKS
QZzU/j5I+a6iRDNWGxeuJ8AwjvIc79YrBPV94+gJVTiUbM8HZCZg288bOg/tfwIj
m6b9iTNzizJoay/IRx5X9f8KcrKgNRBfkutGAui/5ISjPUOfDsYp4C87ehJP19M7
bxXZ8xyjG3Vh9NsQtlEu3I02rI9DSBlb9l+jxu/EFSlRcjn9lDjzUnnbPAIRmxWJ
m1Y7/3QgRfMlzChqqulGm64VKrdZeZtm9x/twCwg4X2cb6/kvG90EtowIVk7iiyv
xC/7mswVJ/xsvdc+v8znXlfhR06cgcCTiD9Rr+A9X3Kq+2+D8HHtEnTgdJG2IMZK
Xo9Gl+BTzMZVoXS+mq8K1By/WV4lip//qbCpYtSL4Mq8wUiqsJseT2Cm2wLvXnej
uwqUh564uFu/yTF5BQV15T55Jf1ey0AAyGBAGY+asEESbGGlF9CO2SV4jmKNJLzL
XwbL3+yOgkLON5biBcjmwCfociy9buNf/6XMHFyrvetwO9dtXVPiiEYvlBytczF3
dzLJ1FqihMq7XOefe+EMHXaSprx44KgMiTzBFrDFrFRA7eh39YHIdpqBtUwFFUD8
wky/q+BTXjKVIY1Usb0rHh0zDA==
-----END CERTIFICATE-----
CERT
openssl verify -CAfile /tmp/root.pem -check_ss_sig /tmp/root.pem
rm /tmp/root.pem
```

**Comment by bartonjs** [comment]
Weird.  `ModPow(certifiate.signature.value, certificate.subjectPublicKeyInfo.exponent, certificate.subjectPublicKeyInfo.modulus)` produces

```
00 01 FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF 00 30 
2F 30 0B 06 09 60 86 48 01 65 03 04 02 01 04 20 
2C 8C BC AB CD B6 E7 B9 2F 30 77 E2 A9 30 61 AB 
70 A4 BA 69 22 35 52 A7 52 D9 BA FA F3 FC D2 E9 
```

And `SHA256(certificate.tbsCertificate)` looks like `2c8cbcabcdb6e7b92f3077e2a93061ab70a4ba69223552a752d9bafaf3fcd2e9` to me.  The only possible thing that I see is that maybe OpenSSL doesn't accept `{ OID(2.16.840.1.101.3.4.2.1) }` (instead of `{ OID(2.16.840.1.101.3.4.2.1), NULL }`) as the RSA+SHA-256 digest identifier (though RFC4055 says both ways MUST be supported and RFC8017 says that one SHOULD leave out the NULL).

It'll probably take walking through the OpenSSL calculations in a debugger to see what went wrong.

**Comment by vcsjones** [comment]
> The only possible thing that I see is that maybe OpenSSL doesn't accept { OID(2.16.840.1.101.3.4.2.1) } (instead of { OID(2.16.840.1.101.3.4.2.1), NULL }) 

@bartonjs that appears to be it. It's this check here this is failing:

https://github.com/openssl/openssl/blob/36eadf1f84daa965041cce410b4ff32cbda4ef08/crypto/rsa/rsa_sign.c#L218-L222

Running this certificate under the debugger, `encoded_len` is 51 and `decrypt_len` 49. If we dump the `decrypt_buf` and `encoded` variables:

```
memory read -s1 decrypt_buf -c 49
0x55555564bf00: 30 2f 30 0b 06 09 60 86 48 01 65 03 04 02 01 04  0/0...`.H.e.....
0x55555564bf10: 20 2c 8c bc ab cd b6 e7 b9 2f 30 77 e2 a9 30 61   ,......./0w..0a
0x55555564bf20: ab 70 a4 ba 69 22 35 52 a7 52 d9 ba fa f3 fc d2  .p..i"5R.R......
0x55555564bf30: e9                                               .
memory read -s1 encoded -c 51
0x55555564bd80: 30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05  010...`.H.e.....
0x55555564bd90: 00 04 20 2c 8c bc ab cd b6 e7 b9 2f 30 77 e2 a9  .. ,......./0w..
0x55555564bda0: 30 61 ab 70 a4 ba 69 22 35 52 a7 52 d9 ba fa f3  0a.p..i"5R.R....
0x55555564bdb0: fc d2 e9   
```

The difference being the ASN.1 NULL in the SEQUENCE.

**Comment by henriko2018** [comment]
Thank you for your efforts. I suppose we cannot (in the short term) fix this by modifying OpenSSL. Do I have to ask the customer to use another root certificate, or do you have another suggestion?
