### ISSUE TITLE
System.Net.Dns class does not have overloads with CancellationToken

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#47222]
Looking at `System.Net.Dns` class I see methods with _Async_ suffix, but none of the methods have overload that takes `CancellationToken`. Is this expected?

**Comment by antonfirsov** [comment]
Not in .NET 5 unfortunately. #33420 added the overloads from #939, the new methods will be available in .NET 6.

**Comment by cincuranet** [comment]
Thanks. Apparently my search-fu failed me.

**Comment by karelz** [comment]
Duplicate of #939
