### ISSUE TITLE
[Question] Simulating network failures, and not webserver failures.

### ISSUE THREAD

**Issue by VisualBean** [dotnet/runtime#47224]
Usually I find myself wanting to mock HttpClient integrations, through HttpMessageHandler.
But how do I simulate connection issues?

I've found that all of these classes are internal to the framework, which doesn't seem to leave me a lot of choice to be able to simulate Connection Reset, Connection Refused and similar more or less transient issues that comes from the network stack, and not the webserver itself.

Any ideas, hints or otherwise feedback would be greatly appreciated.
Mainly my idea came from wanting to unit test the resilliency of my services.

**Comment by antonfirsov** [comment]
If you are on .NET 5, I think you can utilize [ConnectCallback](https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#socketshttphandler-extension-points) for this.

To emulate a connection failure, you can throw an appropriate `SocketException` right in the callback, to emulate `ConnectionReset` or similar, you can fake `NetworkStream`, [and throw `IOException`](https://github.com/dotnet/runtime/blob/82a2cdae4f829dd38a793b528629a98574774455/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs#L680) from reads/writes.

**Comment by karelz** [comment]
Triage: Seems to be answered above. Closing.

Alternative ideas:
- Create custom handler that throws these exceptions
- Simulate errors on OS level - firewall injecting failures (e.g. on MacOS standard firewall does it, some app on Windows)
