### ISSUE TITLE
Blazor Component RuntimeBinderException with dynamic and null

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#47226]
The following two Blazor Components
```razor
@* App.razor *@
<Test Value="null"></Test>
@* Test.razor *@
<div>@Value</div>
@code
{
    [Parameter] public dynamic Value { get; set; }
}
```
Result in immediate `RuntimeBinderException`:
```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddAttribute(int, string, System.Func<Microsoft.AspNetCore.Components.UIEventArgs,System.Threading.Tasks.Task>)' and 'Microsoft.AspNetCore.Components.RenderTree.RenderTreeBuilder.AddAttribute(int, string, string)'
   at CallSite.Target(Closure , CallSite , RenderTreeBuilder , Int32 , String , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   at BlazorServerPreview6.App.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__5_0(RenderTreeBuilder builder)
[…]

```

**Comment by Pete107** [comment]
I ran into this issue quite a bit before noticing what was actually wrong.

I had been using Radzen Data Grids and their bind-Value expects a dynamic object.
When the collection being bound is Empty and you attempt to set the bind-Value's object to an object in the empty collection it'll produce this error.

I also raised this issue up with Radzen them selves as it wasn't an issue in their earlier releases. (I'm using 3.2.1)

**Comment by LukeTOBrien** [comment]
Hello,

Just want to mention here that I am encountering the same issue.  
I am creating a generic maintenance form for database tables, on the client-side my objects are dynamic (ExpandoObject) and on the server-side I am using [DynamicLinq](https://dynamic-linq.net/).  
The solution all works well apart from nullable fields due to this issue.

Will this issue be resolved in .NET 6?

**Comment by artemiusgreat** [comment]
One more use case and a workaround. In my case, I wanted to generate table that has `Columns` and `Items` as parameters. To render each line in the table I would do. 

```
@foreach (var item in Items)
{
  @foreach (var column in Columns)
  {
    <td>item[column]</td>
  }
}

@code 
{
    [Parameter] public IEnumerable<string> Columns { get; set; }
    [Parameter] public IEnumerable<dynamic> Items { get; set; }
}
```

If `column` property doesn't exist in `item` and `item[column]` returns `NULL`, it will raise an ambiguous runtime bind exception.
The workaround is to always convert template values to `string` before rendering them in template. 

```
@foreach (var item in Items)
{
  @foreach (var column in Columns)
  {
    <td>@GetValue(item, column)</td>
  }
}

@code 
{
    [Parameter] public IEnumerable<string> Columns { get; set; }
    [Parameter] public IEnumerable<dynamic> Items { get; set; }

    private string GetValue() 
    {
        return $"{ item[column] }"; // This works fine
    }
}
```

Original author's code could be modified the same way. 

```
@* App.razor *@
<Test Value="ConvertToStr(null)"></Test>
@* Test.razor *@
<div>@Value</div>
@code
{
    [Parameter] public dynamic Value { get; set; }

    private string ConvertToStr(dynamic value) 
    {
        return $"{ value }";
    }
}
```

**Comment by cston** [comment]
From the examples above, it looks like the runtime binder is reporting that a call such as `AddAttribute(1, "", (dynamic)null)` is ambiguous between:
`AddAttribute(int, string, MulticastDelegate)` and
`AddAttribute(int, string, string)`.

That ambiguity is expected. A similar ambiguity would be reported at compile-time for a call to `AddAttribute(1, "", null)` that didn't involve `dynamic`.

**Comment by cston** [comment]
Closing as "by design". Please re-open if I've misunderstood the underlying issue.
