### ISSUE TITLE
System.Numerics work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#47244]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

During .NET 7, we will continue work on the Generic Math feature set, which is tracked in its own epic (#63548). Additionally, we will invest in quality, enhancements and new APIs, plus performance improvements. This is an ambitious set of work, so it's likely that several of the items below will be pushed out beyond .NET 7.

### Quality

- [x] #65633 
- [x] #64463
- [x] #17296

### Enhancements / New APIs

- [x] #63801
- [x] #58853
- [x] #60882

### Performance

- [x] #60293
- [x] #56931

## Backlog (roughly in priority order)
- [ ] #50939
- [ ] #57413
- [ ] #1643
- [ ] #13712
- [ ] #19874
- [ ] #24174
- [ ] #25868
- [ ] #48615
- [ ] #41454

**Comment by danmosemsft** [comment]
Seems like a great User Story?

**Comment by jeffhandley** [comment]
Yep; thanks. I meant to apply the label; thanks for recognizing it was missing. Done.
