### ISSUE TITLE
CustomMarshalers - EnumeratorToEnumVariantMarshaler

### ISSUE THREAD

**Issue by maddinthegreat** [dotnet/runtime#47243]
Hi,

is there a replacement for **EnumeratorToEnumVariantMarshaler** in NET5 ?

Regards
Martin

**Comment by AaronRobinsonMSFT** [comment]
@maddinthegreat This class does exist in .NET 5, but was converted into a private type. It is at present only used by the internal marshalers. Is this API needed for some manual marshalling scenario? Any details to help us determine how important this is are welcome.

/cc @elinor-fung

**Comment by maddinthegreat** [comment]
Hi,

it's needed for i.e.:
`    [Guid("644EFD52-CCF9-486C-97A2-39F352570B30")]
    [ComImport]
    public interface INetFwAuthorizedApplications : IEnumerable
    {
        [DispId(1)]
        int Count
        {
            [DispId(1)]
            [MethodImpl(MethodImplOptions.InternalCall)]
            get;
        }

        [DispId(2)]
        [MethodImpl(MethodImplOptions.InternalCall)]
        void Add([MarshalAs(UnmanagedType.Interface)] [In]
            INetFwAuthorizedApplication app);

        [DispId(3)]
        [MethodImpl(MethodImplOptions.InternalCall)]
        void Remove([MarshalAs(UnmanagedType.BStr)] [In] string imageFileName);

        [DispId(4)]
        [MethodImpl(MethodImplOptions.InternalCall)]
        [return: MarshalAs(UnmanagedType.Interface)]
        INetFwAuthorizedApplication Item([MarshalAs(UnmanagedType.BStr)] [In] string imageFileName);

        [DispId(-4)]
        [MethodImpl(MethodImplOptions.InternalCall)]
        [return: MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(EnumeratorToEnumVariantMarshaler))]
        new IEnumerator GetEnumerator();
    }`

Firewall interfaces of Windows.

Regards
Martin

**Comment by jkoritzinsky** [comment]
You can use the `MarshalType` field on the `MarshalAs` class to specify the full type name as a string instead of using `typeof()`. This is what tools like TlbImp use to reference this marshaller in particular.

**Comment by AaronRobinsonMSFT** [comment]
@maddinthegreat I think @jkoritzinsky's suggestion is actually what I would recommend as well. I appreciate this is a breaking change and we can revisit this is we hear more from the community but for right now that is how I would resolve the issue. Please let us know if you have any concerns here.
