### ISSUE TITLE
Superpmi asmdiff is slow for windows arm64

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#47240]
```
python repo\src\coreclr\scripts\superpmi.py asmdiffs -target_arch arm64 -base_jit_path base_path\clrjit_win_arm64_x64.dll -diff_j
it_path diff_path\clrjit_win_arm64_x64.dll -jit_name clrjit_win_arm64_x64.dll
```

This takes a long time to complete (it completes successfully). In my run, I didn't see any other issue like https://github.com/dotnet/jitutils/issues/309, but need to figure out why it is slow.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
How is it slow? Did you compare the time versus a non-cross-compiler run, for example? (The comparison may be imperfect since the arm64 MCH will be different from the x64 MCH.) You should try running under perfview and see if anything pops.

**Comment by kunalspathak** [comment]
It is  3 mins 16 secs vs. 1 min 52 secs for libraries.pmi collection. I didn't get chance to inspect it under Perfview.

![image](https://user-images.githubusercontent.com/12488060/105238512-77fc3d80-5b21-11eb-8d8f-198ddeaf372d.png)

**Comment by BruceForstall** [comment]
It would be worthwhile investigating. Some possibilities:
1. The arm64 targeting JIT is slower
2. The arm64 collection is bigger
3. SuperPMI for arm64 targeting has unexpected overhead.

**Comment by kunalspathak** [comment]
> 2. The arm64 collection is bigger

Both are around same size.

**Comment by kunalspathak** [comment]
I don't see it is slow anymore. It might be that my machine was in bad state.

```ps

❯ Measure-Command { python src\coreclr\scripts\superpmi.py asmdiffs -base_jit_path E:\lsra\refactor\base\clrjit_win_arm64_x64.dll -diff_jit_path E:\lsra\refactor\ref4\clrjit_win_arm64_x64.dll -target_arch arm64 -f libraries.pmi }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 55
Milliseconds      : 941
Ticks             : 559418577
TotalDays         : 0.000647475204861111
TotalHours        : 0.0155394049166667
TotalMinutes      : 0.932364295
TotalSeconds      : 55.9418577
TotalMilliseconds : 55941.8577


❯ Measure-Command { python src\coreclr\scripts\superpmi.py asmdiffs -base_jit_path E:\lsra\refactor\base\clrjit_win_x64_x64.dll -diff_jit_path E:\lsra\refactor\ref4\clrjit_win_x64_x64.dll -target_arch x64 -f libraries.pmi }


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 57
Milliseconds      : 150
Ticks             : 571501219
TotalDays         : 0.000661459744212963
TotalHours        : 0.0158750338611111
TotalMinutes      : 0.952502031666667
TotalSeconds      : 57.1501219
TotalMilliseconds : 57150.1219
