### ISSUE TITLE
ServiceDescriptor doesn't implement Equals/GetHashCode so ServiceCollection.Contains fails

### ISSUE THREAD

**Issue by Shazwazza** [dotnet/runtime#47262]
### Description

If you want to check if the ServiceCollection contains a certain descriptor, you cannot check if that descriptor based on it's sub types have been already added. Contains only works for the exact instance object. This might be by design but I've listed the steps to reproduce and work around below. 

### Configuration

netcore 3.1+

### Other information

This can be replicated just like this:

```cs
public interface IMyService 
{	
}
public class MyService : IMyService 
{
}

var services = new ServiceCollection();
var descriptor1 = new ServiceDescriptor(typeof(IMyService), typeof(MyService), ServiceLifetime.Transient);
var descriptor2 = new ServiceDescriptor(typeof(IMyService), typeof(MyService), ServiceLifetime.Transient);
services.Add(descriptor1);
services.Contains(descriptor1).Dump(); // True
services.Contains(descriptor2).Dump(); // False
```

`descriptor2` above is exactly the same but fails. 

This can be worked around by creating a derived ServiceDescriptor like

```cs
public class UniqueServiceDescriptor : ServiceDescriptor, IEquatable<UniqueServiceDescriptor>
{
	public UniqueServiceDescriptor(Type serviceType, Type implementationType, ServiceLifetime lifetime)
		: base(serviceType, implementationType, lifetime)
	{
	}

	public override bool Equals(object obj) => Equals(obj as UniqueServiceDescriptor);
	public bool Equals(UniqueServiceDescriptor other) => other != null && Lifetime == other.Lifetime && EqualityComparer<Type>.Default.Equals(ServiceType, other.ServiceType) && EqualityComparer<Type>.Default.Equals(ImplementationType, other.ImplementationType) && EqualityComparer<object>.Default.Equals(ImplementationInstance, other.ImplementationInstance) && EqualityComparer<Func<IServiceProvider, object>>.Default.Equals(ImplementationFactory, other.ImplementationFactory);

	public override int GetHashCode()
	{
		int hashCode = 493849952;
		hashCode = hashCode * -1521134295 + Lifetime.GetHashCode();
		hashCode = hashCode * -1521134295 + EqualityComparer<Type>.Default.GetHashCode(ServiceType);
		hashCode = hashCode * -1521134295 + EqualityComparer<Type>.Default.GetHashCode(ImplementationType);
		hashCode = hashCode * -1521134295 + EqualityComparer<object>.Default.GetHashCode(ImplementationInstance);
		hashCode = hashCode * -1521134295 + EqualityComparer<Func<IServiceProvider, object>>.Default.GetHashCode(ImplementationFactory);
		return hashCode;
	}
}
```

and then the result works

```cs
var services = new ServiceCollection();
var descriptor1 = new UniqueServiceDescriptor(typeof(IMyService), typeof(MyService), ServiceLifetime.Transient);
var descriptor2 = new UniqueServiceDescriptor(typeof(IMyService), typeof(MyService), ServiceLifetime.Transient);
services.Add(descriptor1);
services.Contains(descriptor1).Dump(); // True
services.Contains(descriptor2).Dump(); // True
```

**Comment by GrabYourPitchforks** [comment]
Note to area owners: this gets complicated quickly when we start dealing with the `ServiceDescriptor(Type, object, ServiceLifetime)` and `ServiceDescriptor(Type, Func<...>, ServiceLifetime)` ctors. Once you enter the realm of comparing two objects or two functions for equality, you start introducing opinions into the system. For example: is `new ServiceDescriptor(..., typeof(MyType), ...)` equal to `new ServiceDescriptor(..., new MyType(), ...)` if _MyType_ instances are intended to be treated as singletons?

**Comment by Shazwazza** [comment]
Yep thought there was most likely some complications here. I suppose for my use case and maybe for others, the option to have a custom service descriptor like the above `UniqueServiceDescriptor` works fine.

**Comment by eerhardt** [comment]
There are different meanings for "equals" for a ServiceDescriptor. For example, our `TryAdd` method only checks for `ServiceType` being equal:

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/Extensions/ServiceCollectionDescriptorExtensions.cs#L73-L95

I don't think we want to add Equals/GetHashCode to ServiceDescriptor for this reason. The caller needs to decide what they mean when they check for equality.

**Comment by maryamariyan** [comment]
Closing as won't fix
