### ISSUE TITLE
runtime.native.System.IO.Ports v5.0.0 release version nuget package depends on pre-release versions of other packages

### ISSUE THREAD

**Issue by sokolovsa** [dotnet/runtime#47268]
Release version of runtime.native.System.IO.Ports (5.0.0) depends on following packages:
        runtime.linux-arm.runtime.native.System.IO.Ports (>= 5.0.0-rtm.20519.4)
        runtime.linux-arm64.runtime.native.System.IO.Ports (>= 5.0.0-rtm.20519.4)
        runtime.linux-x64.runtime.native.System.IO.Ports (>= 5.0.0-rtm.20519.4)
        runtime.osx-x64.runtime.native.System.IO.Ports (>= 5.0.0-rtm.20519.4)

Those are prerelease versions. 
So nuget.exe fails to install System.IO.Ports with specific target framework unless -PreRelease is specified.
Example:
This fails:
`NuGet.exe install System.IO.Ports -Version 5.0.0 -outputdirectory ioports -Framework net5.0 -Verbosity detailed`

But this succeeds:
`NuGet.exe install System.IO.Ports -Version 5.0.0 -outputdirectory ioports -Framework net5.0 -Verbosity detailed -PreRelease`

Release versions of nuget packages should not have prerelease dependencies. Please fix.

**Comment by hoyosjs** [comment]
@ViktorHofer not sure if stabilization has to do with this.

**Comment by ViktorHofer** [comment]
cc @Anipik

**Comment by safern** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
@Anipik it looks like a bug in how we're building stable packages for System.IO.Ports.  The process didn't result in stable versions for the runtime-specific packages.

https://www.nuget.org/packages/runtime.native.System.IO.Ports/5.0.0
![image](https://user-images.githubusercontent.com/8918108/106519225-d6b1a780-648f-11eb-9efe-8294a3d0501a.png)

We should service for this and also fix whatever in our release process is missing stabilization for these RID-specific packages.

**Comment by Anipik** [comment]
yes i will take a look and fix this

**Comment by Anipik** [comment]
@sokolovsa can you please the error and machine configuration bcoz i am not able to repro the bug.

**Comment by ViktorHofer** [comment]
@Anipik should this issue be closed now?

**Comment by Anipik** [comment]
the fix is in but the it will be shipped with 5.0.4

**Comment by ViktorHofer** [comment]
If it's already merged then let's close the issue.
