### ISSUE TITLE
[Proposal] BigInteger API for counting and enumerating digits

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#47265]
## Background and Motivation

The current `BigInteger` API makes it difficult to do certain operations efficiently, namely those that require counting digits or enumerating over a small number of digits in a large value, which `BigInteger` can do much more effectively given its internal state.

In order to iterate over digits you currently have to do `ToString()`, which is brutally slow if you only end up needing a handful of digits on a very large value. My `BigDecimal` implementation needs to normalize internal state into a `BigInteger Mantissa` field which contains no trailing zeros and an `int Exponent` field. To do this, it needs to count the number of trailing zeros in the input `BigInteger` value and then divide by an appropriate power of 10.

Counting the number of digits in a `BigInteger` likewise currently requires a rather inefficient approach:

```cs
private static int GetDigitCount(BigInteger value)
{
    value = BigInteger.Abs(value);

    if (value.IsZero || value.IsOne)
        return 1;

    int digits = (int)Math.Ceiling(BigInteger.Log10(value));

    if (value == BigInteger.Pow(10, digits))
        digits++;

    return digits;
}
```

With its internal state, `BigInteger` could very easily provide a much more efficient method to do this which would not require iterating over the whole value. Counting the number of digits in the `BigInteger` is used quite heavily across my `BigDecimal` codebase to support a number of common operations.

## Proposed API

```diff
namespace System.Numerics.BigInteger
{
    public struct BigInteger
    {
+        public int DigitCount { get; }
+        public IEnumerable<int> EnumerateDigits(bool mostSignificantFirst = true);
     }
}
```

## Usage Examples

**Count trailing zeros:**

```cs
BigInteger bigInt;
int numTrailingZeros = 0;

foreach (int digit in bigInt.EnumerateDigits(mostSignificantFirst: false))
{
    if (digit != 0)
        break;

    numTrailingZeros++;
}
```

I think the `DigitCount` property is self-explanatory.

## Risks

None.

**Comment by huoyaoyuan** [comment]
Getting decimal digits count of `BigInteger` is non-trivial because it's stored in hexadecimal. Iterating decimal digits cannot be efficient enough.

There also cannot be a `bool mostSignificantFirst` because the optimal implementation will differ very much.
Further more, using `IEnumerale` has cost and may be even slower than string.

The really optimal way should be a new `BigDecimal` that stores data in [BCD](https://en.wikipedia.org/wiki/Binary-coded_decimal).

**Comment by mikernet** [comment]
> Getting decimal digits count of BigInteger is non-trivial because it's stored in hexadecimal.

Hmmm...shucks. Might not be have a better time complexity than the Log10 approach then, but it would still be a big improvement. Given the cost, a `CountDigits()` method might be better.

> Further more, using IEnumerale has cost and may be even slower than string.

I know it has a cost, but `BigInteger.ToString()` on a value containing 100 or 1,000 or 1,000,000 digits just to get a handful of trailing zeros costs a lot more.

> There also cannot be a bool mostSignificantFirst because the optimal implementation will differ very much

Not sure what you mean. It would return a different optimal `IEnumerable` implementation based on the value of that parameter.

**Comment by huoyaoyuan** [comment]
> I know it has a cost, but `BigInteger.ToString()` on a value containing 100 or 1,000 or 1,000,000 digits just to count a handful of trailing zeros costs a lot more.

Hex-Dec conversion requires divide and substract. It must maintain it's own copy of intermediate numbers. It's just 2-3 times smaller than the string.
Iterating `IEnumerable` is several times more costful than inspecting array.

You can try to implement such method on `byte[]`, and benchmark it with `ToString`. The result may surprise us.

**Comment by mikernet** [comment]
I think we are talking past each other here. Creating a new string with 1,000,000 elements and then iterating over 5 of them is a lot slower than just iterating 5 elements on an IEnumerable. That string also needs every element to be converted to digits so whatever logic is needed to return individual digits is also needed for doing ToString().

**Comment by Clockwork-Muse** [comment]
>> The really optimal way should be a new BigDecimal that stores data in BCD.
>
>That's probably true, though I've spent way too long on this already and probably don't have time to implement that from scratch, haha, I leverage a ton of `BigInteger` functionality. That would be a good distant future optimization though.

... I would assume there are existing implementations of a `BigDecimal` type (and there certainly are in other languages).  Note that BCD is wasteful of space, and - barring hardware support - not as performant.  If you actually need _digits_ (as opposed to just operating on the numbers) BCD might be harder to beat.  Otherwise, you might have more luck looking at a generalized Q number format (`decimal` is an example of one with a fixed size, I think - although you could maybe expand it).

**Comment by mikernet** [comment]
>  I would assume there are existing implementations of a BigDecimal type

Not sure what you mean. Sure, there are some, and all of them use `BigInteger` and suffer from the same issues. We also have requirements that these other implementations don't provide and have significantly improved on their performance characteristics, which is important in our usage scenario.

**Comment by tannergooding** [comment]
What's the benefit of `DigitCount` over `ILog10(value.GetBitLength() / 8)` or even just `(long)BigInteger.Log10(value)`? They should represent the same information and so an extension method exposing `DigitCount` would be trivial to add.
* Noting we don't expose `ILog10` today, but it is fairly trivial itself could be exposed as a more general purpose API: http://graphics.stanford.edu/~seander/bithacks.html#IntegerLog10

As for `EnumerateDigits`, I wonder if that is the "right" API to expose? That is, we have `TryWriteBytes` today which allows you to get a little-endian or big-endian representation of the value in two's complement form and so functionally you can "enumerate digits" today without going through `ToString`. The major "downside" to this approach is that it may require an additional allocation, which may be large, while the `BigInteger` itself is a `readonly struct` and so you don't really need to worry about mutations or such. So, perhaps, it would be better to have a general way to enumerate the underlying two's complement representation of the `BigInteger` so it isn't strictly tied to enumerating individual decimal digits....

**Comment by tannergooding** [comment]
Going to close this as it has open questions that haven't received any answer. Please feel free to reopen or open a new issue/discussion once as appropriate.

**Comment by mikernet** [comment]
Hey Tanner, I believe we discussed this further over at the discord and answered some of these questions. I should have noted them down in this issue, but I'm still very much interested in optimizing this, you said you needed to think about it more.

This is the fastest reliable way I could determine for counting digits: https://github.com/Singulink/Singulink.Numerics.BigIntegerExtensions/blob/c52f81023f9bc3cfffc00ac2357a4b643caf9858/Source/Singulink.Numerics.BigIntegerExtensions/BigIntegerExtensions.cs#L16

It requires both a Log10 and a Pow10 operation but only needs to happen during `ToString()` and division operations on my BigDecimal implementation, so it's not a huge deal, and as you said I can just implement ILog10 to make this faster. If there's already an implementation in .NET then it would be nice to expose that if possible, but I've found Log10 performance is shockingly good for very large values (it somehow magically manages almost constant performance after a certain size of BigInteger) and I've optimized Pow10 ops with a cache.

The big perf killer right now is having to call `ToString()` in the constructor each time a new BigDecimal is constructed just to cut off trailing zeros, of which there is usually only a small number: https://github.com/Singulink/Singulink.Numerics.BigDecimal/blob/cbe331750a898a44f8a1f5261f22370a61086349/Source/Singulink.Numerics.BigDecimal/BigDecimal.cs#L136

I think this is the bit you wanted to think about more. I'm open to any option that will allow me to do this more efficiently than processing 1000 digits just to see if a few are zeros most of the time.

**Comment by mikernet** [comment]
I'm guessing going through `TryWriteBytes()` would potentially be much faster than `ToString()` but I haven't figured out how to implement counting trailing base10 digits based on what that returns yet.

**Comment by mikernet** [comment]
Oh wait, no, I don't believe `ILog` will work. As per our discord discussion:
@mikernet 
>I'm trying to understand how `ILog10(value.GetBitLength() / 8)`, i.e. the Log10 of the byte length of the 2's complement representation, is somehow equivalent to `Log10(value)` and my brain ain't getting there for some reason
> How could that possibly work? Or am I missing something here?

@tannergooding 
> I think I'm just spouting things without thinking, that won't quite work

**Comment by mikernet** [comment]
Can we reopen this issue?

**Comment by mikernet** [comment]
Thanks for the idea to use `GetBitLength()` @tannergooding, I got `CountDigits()` optimized pretty damn well, new super fast constant time algorithm:

```cs
private static readonly double exponentConvert = Math.Log(2) / Math.Log(10);

public int CountDigits(BigInteger value)
{    
    long numBits = value.GetBitLength();
    
    int base10Digits = (int)(numBits * exponentConvert);
    var reference = BigIntegerPow10.Get(base10Digits);
       
    if (value >= reference)
        base10Digits++;
        
    return base10Digits;
}
```

So I think all that is left is the trailing zero issue.
