### ISSUE TITLE
.NET Regex and Subroutine/Recursion support

### ISSUE THREAD

**Issue by sunkin351** [dotnet/runtime#47263]
I came across the fact that .NET currently doesn't support regex recursion or subroutines and was confused as to why.
Is there a reason .NET's Regex engine doesn't support this?

(Note: Going off the fact that Framework doesn't support them. Have not checked if .NET 5 supports them. I'll close this immediately if it does.)

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/34269

**Comment by sunkin351** [comment]
I beg to differ, unless I'm not understanding what he means by "predefined"... Which may be the case.

**Comment by stephentoub** [comment]
The "pre" is just "previously". That's the term other languages like Perl use to describe creating modular regular expressions snippets that can then be used in other regular expressions.
https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions#Subroutines

**Comment by sunkin351** [comment]
Alright, I guess the main diff here then is I'm asking why its not supported already and he's asking for it to be implemented.

**Comment by stephentoub** [comment]
> I'm asking why its not supported already

Simply because it wasn't implemented when Regex was first added to .NET long ago, and there have been very few requests for it since.

**Comment by sunkin351** [comment]
Good to know.
