### ISSUE TITLE
Why use ldarga instead ldarg for stfld when arg is value type ?

### ISSUE THREAD

**Issue by RevensofT** [dotnet/runtime#47273]
If I remember correctly it use to be just `ldarg`, doesn't it ? while `ldfld` still use `ldarg` for value type so why `stfld` change or why not `ldfld` change too ?

**Comment by huoyaoyuan** [comment]
`stfld` mutates the value type. The operation must be performed on the original space, so `ldarga` is used. `ldarg` is creating a copy of the value type.

**Comment by RevensofT** [comment]
@huoyaoyuan Thanks for answer, 
I assume it should be fine if I use ldarga value type with ldfld or do I must use ldarg only ?

**Comment by RevensofT** [comment]
@huoyaoyuan Thank you once again, 
I usually `ildasm` and write il code directly there and `ilasm` back to dll, however it always loss summary and remark even I set `/res`.
