### ISSUE TITLE
[Mono][Interpreter] Performance Regression System.Threading.Tests.Perf_Timer.ScheduleManyThenDisposeMany 200 % Regression

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#47279]
This appears to have been caused by this change: https://github.com/dotnet/runtime/commit/ce4c7251bcdf5774a54861303afdb0a81ddbd29e

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [699d3d6a1dc2455697111e46ede08b398416851e](https://github.com/dotnet/runtime/commit/699d3d6a1dc2455697111e46ede08b398416851e)
Compare | [4515a7ac8be6930d0367dd7e5a411289ddcf4a7c](https://github.com/dotnet/runtime/commit/4515a7ac8be6930d0367dd7e5a411289ddcf4a7c)

### Regressions in System.Threading.Tests.Perf_Timer

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[ScheduleManyThenDisposeMany](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Threading.Tests.Perf_Timer.ScheduleManyThenDisposeMany.html>) | 878.12 ms | 1.87 secs | 2.13 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_19_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Threading.Tests.Perf_Timer_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_19_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Threading.Tests.Perf_Timer.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Threading.Tests.Perf_Timer*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9197df09-a37e-4fc4-9177-ea2af782e33d4bac21f5aef42709c/c4fe1c1d-f3c5-460a-8947-a926199dac6d.zip?sv=2019-07-07&se=2021-02-12T00%3A55%3A21Z&sr=c&sp=rl&sig=sWe%2BFAGNC2R3L77zZ3e28tovH5SUEL5a9FktzpNcgls%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d2e6bf54-4d20-4aab-8549-4a42434a4833bcae7c430bf4b9e83/3b99dc4e-26b7-4639-ab0f-9f483d90203f.zip?sv=2019-07-07&se=2021-02-12T13%3A58%3A10Z&sr=c&sp=rl&sig=6prbuKZpBgB6oR1B%2BwA%2BY7PqU4xdljBVd6%2BDTo7k6HQ%3D>)

#### System.Threading.Tests.Perf_Timer.ScheduleManyThenDisposeMany

```log
[ 783392931.245 ;  941395064.221) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 941395064.221 ; 1099397197.197) | 
[1099397197.197 ; 1257399330.173) | 
[1257399330.173 ; 1415401463.149) | 
[1415401463.149 ; 1573403596.124) | 
[1573403596.124 ; 1731405729.100) | 
[1731405729.100 ; 1928099231.736) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by SamMonoRT** [comment]
@naricc - Based on recent runs is this still relevant and actionable ? Please close if not.

**Comment by naricc** [comment]
I was trying to check the recent runs, but I can't find this benchmark on the interpreter page https://pvscmdupload.blob.core.windows.net/index/index/index.html#

@DrewScoggins Is this benchmark still running?

**Comment by DrewScoggins** [comment]
So, it would not appear there unless there was a new regression or it was a test that had a particular category other than Runtime or Library, as for those we show even unchanged values. You can however find this test history using the history index, and a link to the test is here, https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04_LLVM%3dfalse_MonoAOT%3dfalse_MonoInterpreter%3dfalse_RunKind%3dmicro_mono%2fSystem.Threading.Tests.Perf_Timer.ScheduleManyThenDisposeMany.html. From looking at the graph however, this was not a regression, or if it was it was already fixed.

![image](https://user-images.githubusercontent.com/9439069/123758654-019ffc00-d874-11eb-92f7-80eee6b38183.png)

**Comment by SamMonoRT** [comment]
@naricc - Closing based on comments above, wasn't a regression or if it was, it was fixed.
