### ISSUE TITLE
Long running test: IPInfoTest_IPv4Loopback_ProperAddress

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#47288]
Sample Build: https://dev.azure.com/dnceng/public/_build/results?buildId=957982&view=ms.vss-test-web.build-test-results-tab&runId=30205190&resultId=183559&paneView=attachments

`IPInfoTest_IPv4Loopback_ProperAddress` often runs long enough to end up timing out the workitem and failing builds.

cc: @dotnet/runtime-infrastructure

**Comment by karelz** [comment]
@hoyosjs do you know how often it fails? Is it mostly Linux arm? Or other architectures?
@wfurt looked at history and didn't see anything alarming.

Note: Should pop up in our CI monitoring when we look at hangs/timeouts -- we do not do that regularly (only ad-hoc).

**Comment by hoyosjs** [comment]
I have noticed it a few times when I opened this, but I don't have any more samples right now. I'll keep it in mind to report if I see again..

**Comment by MihaZupan** [comment]
There are no failures in Kusto history - closing as not actionable.

**Comment by wfurt** [comment]
What is your query @MihaZupan? When test hangs than the test run will be killed and there will not be test entry...

**Comment by MihaZupan** [comment]
I looked at [test failures](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA22QMU/DQAyF9/4Kk6lFKRNrhiAYgqAKNHt1vTPJtY0d2Q5VJX4811RQBm6yzu/zs1+Dau+o48F09gXHDgWhOQ0Iak5Mj9E6yNYnNezvVmjZDNJzFOACwU0BWe1Ur435K1rHAYrUqeqKPrhJHpuq/rx/YR62zu83tfCAUoYgmFBggf+h0vskKA+HC2ARdbPiJxEWzRZp4R1Hgn2kUEQiFJg/81bh5xBim19J8EzmIilkMpLFHpfpyDZSmy0SMgjv0NtSkFyPkAZNORRTHAtgOn9VYfZ3+NuII67O8uvslIFwDNN6IapF8ga3s18DWJ+TxZDD4yjOIlM+WeQpA1XXpiIp/L4R51P9II58l0Mp7dgjmX4D3GAeCbIBAAA=) and [timed out workitems](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA3WQQW7CQAxF9zmFlU0SCXqBKtuqLEBqicSymjKuMCSeyOMoGsTha1ATsqmX9vez/29RYQxy2Sh2EWronKKQa+mK5WHqZzcYTygIe3U6mKyGoqEOw6BFBlaOPbwJIfs27VyHENWJxpH0BPk+RYO87FBzA/USznhUmOAbX71mDUb9xDi0+rzVpP5/znT0SQFiKGcnlWHOwVoXYl8TM8qsjRB4sWjKIN7m3+nuTxT9Cj4GHPDuZPHx39BC+gliOX15y0othnJeK7xfb7frZFVUC8rq4Wa2xkHLh71jYHXEEfID8btqn1e/sdfQEpEBAAA=) (old query I found in CI health report OneNote) and did not see failures in `NetworkInformation`.

Happy to reopen if it's still failing and I just didn't pick up on it.

**Comment by karelz** [comment]
@antonfirsov's idea was to add timeouts to the tests, so we can detect it in future ... can we perhaps proactively add them? That will tell us better than to wait for someone to report it.
