### ISSUE TITLE
System.Security.Cryptography.Tests crashing on OSX CoreCLR x64

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#47289]
Couple builds:
- [SIGSEGV](https://dev.azure.com/dnceng/public/_build/results?buildId=959707&view=ms.vss-test-web.build-test-results-tab&runId=30245358&resultId=182932&paneView=attachments)
- [SIGABRT](https://dev.azure.com/dnceng/public/_build/results?buildId=959545&view=ms.vss-test-web.build-test-results-tab&runId=30241188&resultId=182895&paneView=attachments)

The dumps don't seem to be very are not very usable as they seem to be ELF dumps (managed state only) and . I am also not convinced this is caused by something in Security, but it's the only place I've seen it.

**Comment by filipnavara** [comment]
Not sure if it's related but I have tests on my library that crash around 90% on the time in DSA code on macOS 11. I meant to file an issue for it...but if it happens that these dumps point to DSA code I may have a more reliable repro.

**Comment by vcsjones** [comment]
Interesting remark in the build logs:

```
Warning: unable to build chain to self-signed root for signer "(null)"libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
./RunTests.sh: line 162: 83403 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile 
```

**Comment by danmosemsft** [comment]
Console log: 'System.Security.Cryptography.Csp.Tests' from job cb8a6e9c-a33c-4f6e-9297-3f9eabb33c2e workitem 0ab00111-7773-4421-b1b3-e829ab3d763a (osx.1015.amd64.open) executed on machine dci-macpro-10.local
Console log: 'System.Security.Cryptography.X509Certificates.Tests' from job ce0bac83-b977-40ab-b7c8-635d1b4d0c8f workitem 941688f7-aa51-4f3b-ad8e-d8bab419d6df (osx.1013.amd64.open) executed on machine dci-mac-build-085.local

**Comment by danmosemsft** [comment]
>  they seem to be ELF dumps (managed state only)

These are created by the OS, surely they have native state? How can we get more useful dumps?

**Comment by vcsjones** [comment]
I have a pretty good idea _what_ happened at this point, not _how_ yet. I'm going to spin up a 10.13 VM and stress the tests to see if I can repro locally (run in a loop, try exhausting memory, etc.) I can't repro on 11.1 yet.

**Comment by hoyosjs** [comment]
> > they seem to be ELF dumps (managed state only)
> 
> These are created by the OS, surely they have native state? How can we get more useful dumps?

Are these system dumps? Or are these dumps from createdump? Createdump ones (the ones that dotnet-dump can read on macOS) don't have native state that's easily usable. We'd need a native debugger on OSX that can read the ELF format. LLDB has one, but it didn't work very well last time I checked.

**Comment by danmosemsft** [comment]
We aren't using vstest yet in this repo, so the only dumps we get are ones from the system.

**Comment by hoyosjs** [comment]
Weird. I don't know why I couldn't open. If it's a dump by the system it's possible it doesn't have all the managed state, but it should open under lldb.

**Comment by bartonjs** [comment]
> I'm going to spin up a 10.13 VM and stress the tests to see if I can repro locally (run in a loop,

@vcsjones I'm assuming nothing interesting came from your investigation?  I'm prepared to close this as some sort of transient runtime bug based on a lack of it coming up recently.

**Comment by vcsjones** [comment]
@bartonjs Hmmm I recall looking at this but don't have any notes from my dive in to this. I don't think I was ever able to reproduce it.

Since CI exercises the code way more often than I can, despite my best efforts to hoard computers, I would say I would not have any better luck reproducing it.

**Comment by bartonjs** [comment]
Closing based on it seeming to have ceased happening.
