### ISSUE TITLE
Failure in Regressions/coreclr/GitHub_35000/test35000/test35000.sh

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#47294]
There was exposed by https://github.com/dotnet/runtime/pull/46665, the test is failing with:
```
((srcStackByteOffset % TARGET_POINTER_SIZE) == 0) && "NYI: does not support shuffling of such args"
```
added here https://github.com/dotnet/runtime/pull/46665#discussion_r560612750

the test is creating a delegate with types:
```
this, int, int, int, int, int, int, int, int, object g
```
and then call a method declared as:
```
this int a, int b, int c, int d, int e, int f, int g, int h
```
so the first 8 arguments are passed in registers and we are left with:
```
int, int
```
vs
```
int, obj
```
on the stack.
and offset for the second argument is different: 4 for int, 8 for obj and we can't generate a move for it nowadays.

**Comment by sandreenko** [comment]
PTAL @janvorli @sdmaclea @mangod9 not sure if it worth our immediate attention but we probably should discuss a long-term solution.

**Comment by sandreenko** [comment]
cc @jkoritzinsky

**Comment by mangod9** [comment]
hmm.. interesting. What is the behavior currently, does it fail to invoke the delegate, or crash when h is accessed?

**Comment by janvorli** [comment]
This likely won't be trivial to fix. The whole shuffle thunk generator logic relies on the fact that the entries being shuffled between stack and register slots are of the same size. We've had couple of hard to diagnose bugs there caused by incorrect ordering of the moves. I've ended up rewriting the code completely.

**Comment by sandreenko** [comment]
> hmm.. interesting. What is the behavior currently, does it fail to invoke the delegate, or crash when h is accessed?

so before the VM changes were merged the test was working correctly because VM was using not-apple ABI and allocation both arguments at 8 offsets. We could write a test where the target is a C++ method so it would fail without VM changes. In this case it would be wrong execution because the target method would read garbage instead of the real argument value.

**Comment by mangod9** [comment]
is there anyway to detect and fail gracefully than possibly corrupting state?

**Comment by sandreenko** [comment]
So it is detected here:
https://github.com/dotnet/runtime/blob/311de302de8ac21837e98eb359595e733af38c83/src/coreclr/vm/comdelegate.cpp#L281
and here:
https://github.com/dotnet/runtime/blob/311de302de8ac21837e98eb359595e733af38c83/src/coreclr/vm/comdelegate.cpp#L294

do we have a throwing mechanism for VM?

**Comment by janvorli** [comment]
It should be a fail-fast, there is no way to recover from such a situation. And we need to fix it, any user code can hit this depending on arguments to delegates. Please note that even though the file is called comdelegate.cpp, it is used for all delegates.

**Comment by sdmaclea** [comment]
These tests also now failing with the same assert

```
JIT/Stress/ABI/pinvokes_d/pinvokes_d.sh
JIT/Stress/ABI/pinvokes_do/pinvokes_do.sh
```

**Comment by sdmaclea** [comment]
These tests are disabled

https://github.com/dotnet/runtime/blob/c32007158a0b6c356c7f0e25d2d8571ff37d029f/src/tests/issues.targets#L722-L731

**Comment by sdmaclea** [comment]
@mangod9 This is one other Apple Silicon functional issue.

**Comment by mangod9** [comment]
Ok, thanks. Looks like its already included in "ToDo" on the project dashboard.
