### ISSUE TITLE
Add overload for Stopwatch constructor so it can be started immediately

### ISSUE THREAD

**Issue by maxima120** [dotnet/runtime#47291]
## Background and Motivation

In my experience there are 90% Stopwatch instantiation cases where it is followed with Start method immediately. What a waste of key pressing..

## Proposed API

Stopwatch(bool startnow)

## Usage Examples

`var sw = new Stopwatch(true);`

instead of

```
var sw = new Stopwatch();
sw.Start();   
```

**Comment by danmosemsft** [comment]
@maxima120 we already have this -- [Stopwatch.StartNew()](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch.startnew?view=net-5.0).

Thanks for the suggestion though.
