### ISSUE TITLE
Microsoft.Extensions.Logging - won't read SourceName/LogName properties from appsettings file

### ISSUE THREAD

**Issue by slavenl** [dotnet/runtime#47303]
Hi,

I have problem with reading SourceName and LogName from appsettings file. 

If I add configuration manually 

```c#
         return Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostingContext, logging) =>
                   {
                        logging.ClearProviders();                        
                        logging.AddConsole();
                    //    logging.AddEventLog();

                        logging.AddEventLog(options =>
                        {

                            options.SourceName = "D-574E-Reports.DataTransfer.WorkerService";``
                            options.LogName = "D-574E-Reports.DataTransfer";

                        });
                    })

```
logging to EventLog works OK. 

BUT if I add configuration via "appsetings.Development.json" file:
```json
 "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "EventLog": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.Hosting.Lifetime": "Information"
      },
      "LogName": "D-574E-Reports.DataTransfer",
      "SourceName": "D-574E-Reports.DataTransfer.WorkerService"
    },
    "Console": {
      "IncludeScopes": true
    }
  },
```
-> event log stay empty, and my ILogger object doesn't contain above settings regards LogName/SourceName.

As I wrote above, goal is to read SourceName and LogName from configuration. 
As i read somewhere it should work automatically by HostBuilder: 
```c#
logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));       
```
BUT it doesn't.

**Comment by ericstj** [comment]
@slaveln wrote
> As i read somewhere it should work automatically by HostBuilder: logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
BUT it doesn't.

@brandondahler wrote
> adding the following code into your ConfigureServices function should make it read the EventLogSettings from the configuration file as you're expected.
> `LoggerProviderOptions.RegisterProviderOptions<EventLogSettings, EventLogLoggerProvider>(services)`
> I'll defer to members of @aspnet as to whether this should be added to the default behavior or not.

I would imagine that we should be both consistent between our logging implementations and the implementation should match the documentation.  Let's check that.

**Comment by ericstj** [comment]
It looks like console does this here


Which was added by @pakrym here: https://github.com/aspnet/Logging/commit/e94b64f96b425190b027f5d956db34bcb529bf8c

**Comment by pakrym** [comment]
I don't remember why exactly this was not added for all the providers (It's entirely possible that I've missed it when doing the work). Seems reasonable that every provider that has options would need them registered.

**Comment by maryamariyan** [comment]
Seems like the fix for this one is to add `LoggerProviderOptions.RegisterProviderOptions` to [EventLoggerFactoryExtensions.AddEventLog](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.EventLog/src/EventLoggerFactoryExtensions.cs). 

We could evaluate if we want to add it to other logging providers as the need comes up.

**Comment by davidfowl** [comment]
I'm pretty sure it was because the code tries to create the source if it isn't there and that requires admin permissions. If you did however already pre-install￼ it though we should support it.

PS: there's not a great way to see when calls to log are failing other than catching them some other way at runtime

**Comment by maryamariyan** [comment]
Closing issue because there is an easy workaround and also as per comment https://github.com/dotnet/runtime/issues/47303#issuecomment-809283460 it seems like behavior was intentional.
