### ISSUE TITLE
JSON Console Logger shouldn't require logging scopes to implement IReadOnlyCollection<KeyValuePair<string, object>>

### ISSUE THREAD

**Issue by shirhatti** [dotnet/runtime#47315]
Initially posted in https://github.com/dotnet/diagnostics/pull/1905

> @maryamariyan Do you know why the JSON logger requires IReadOnlyCollection<KeyValuePair<string, object>> for scope data? Looking at other [loggers](https://github.com/NLog/NLog.Extensions.Logging/blob/master/src/NLog.Extensions.Logging/Logging/NLogLogger.cs#L67), they are perfectly content with IEnumerable<KeyValuePair<string, object>>? If this wasn't intentional, we should fix this in the logger.

https://github.com/dotnet/runtime/blob/f9a8abc8a5d9981e25f898181e734dc77c7e15e4/src/libraries/Microsoft.Extensions.Logging.Console/src/JsonConsoleFormatter.cs#L112

**Comment by wiktork** [comment]
Related to https://github.com/dotnet/runtime/issues/33486

**Comment by ericstj** [comment]
This looks like a simple bug to fix.  The usage here doesn't require IReadOnlyCollection.

**Comment by daveMueller** [comment]
Hi, I haven't contributed to this repo before, but I would like to start. Can I give it a try?

**Comment by maryamariyan** [comment]
@daveMueller sure.
