### ISSUE TITLE
Fix Build Failures if there are no packages produced in the release branch

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#47318]
In the servicing branches we disable building of packages in libraries subset. Our Publishing and zipping infra depends on atleast one package being produced.
We hit this in 3.1 and 5.0
We should permanently fix this for 6.0

Blueprint Fix https://github.com/dotnet/runtime/pull/45117

cc @safern @ericstj @ViktorHofer

**Comment by safern** [comment]
Adjusted the milestone to 6.0.0 as this is fixed in 5.0.0, but we should port the fixes to master and adjust accordingly so that we bulletproof for the future without having to spend time to do this again every time we start a new servicing branch.

**Comment by ViktorHofer** [comment]
Ideally we would continue to produce packages in the servicing branches but just not upload the ones that haven't changed. This allows to guarantee that all packages are still packable even after years and after several dependency (i.e. dependent updates) and tooling updates.

Also another thing to consider is that we might even switch to GitHub CI at some point and away from AzDO (just a wild guess) and based on what happened with corefx's release/2.1 branch during the switch from Jenkins to AzDO, we might only run a subset of pipelines that are running today. Just something to consider.
