### ISSUE TITLE
Add support to AzDO and Support testing changes in mirror

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#47328]
### Description

This could help test some set of changes that can only be done with internal infrastructure. For this:

- [ ] Audit different YMLs. There's a bunch of steps that need to be excluded on internal, and some that are conditioned on not being public and not PR, we might just need to turn that to just not public. 
- [ ] Add internal queues for Helix, add creator, and helix token needed for this. 
- [ ] Work with dnceng as a bunch of these queues have reduced capacity that won't scale to runtime's requirements.
- [ ] Ensure branches have an appropriate policy pointing to a new build def - the PR definition in internal. Replicate this per branch that needs to support this.

**Comment by ViktorHofer** [comment]
cc @dotnet/runtime-infrastructure

**Comment by ViktorHofer** [comment]
We definitely need this feature to service 6.0 efficiently. Hence adding blocking-release label and moving to 6.0.

**Comment by joperezr** [comment]
@ViktorHofer I'm trying to find places where I can help with 6.0 issues, do you have this one assigned to anybody? Is there anything I can help out with this one?

**Comment by hoyosjs** [comment]
@joperezr  This one is not yet assigned. I thing a good start is we have a ton of places that do evaluations in yaml of the sort of (if not in internal and not a PR). We need to change it so that steps that are build-like are able to run on internal PRs for security patches. Right now PRs don't validate even builds. That'd be a huge step forward.

**Comment by ViktorHofer** [comment]
What Juan said. Would be great if you could pick this one up. The deadline for this task is a soft one as it doesn't impact the initial release but the following servicing releases.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/65603 addressed this for main and we have a backport for release/6.0 here: https://github.com/dotnet/runtime/pull/65526

**Comment by akoeplinger** [comment]
This seems to be implemented now, we have PR support in internal AzDO.
