### ISSUE TITLE
Developers can run .NET libraries inside Node.js

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#47336]
Node.js sports V8 engine which means it can run WebAssembly code. In the recent Node.js v15.6.0 version initial WASI support was added to further support WASM.

Developers which would like to run .NET code inside Node.js would use publish for wasm target. This will probably mean adding a new RID in form of `node-wasm` or `wasi-wasm`.

Related issues
- [x] #41861

**Comment by lewing** [comment]
node-wasm, wasi is very different.  What are we using untriaged to mean here?

**Comment by danmosemsft** [comment]
@lewing this story needs an epic parent.

**Comment by marek-safar** [comment]
@danmosemsft it has Future milestone

**Comment by jaykrell** [comment]
Is this really node-specific, or just wasi?

**Comment by Daniel-Genkin** [comment]
I am working on adding NodeJS support. I would appreciate your feedback
PR: #54640

**Comment by andersson09** [comment]
> I am working on adding NodeJS support. I would appreciate your feedback PR: #54640

Is this PR supporting WASI?

**Comment by lewing** [comment]
> > I am working on adding NodeJS support. I would appreciate your feedback PR: #54640
> 
> Is this PR supporting WASI?

No, wasi support has different complications.  We don't have firm plans to support it yet but we're doing some exploratory work.

**Comment by andersson09** [comment]
Cool and are you exploring compiling mono to wasi or just aot or both?

**Comment by pavelsavara** [comment]
> +1 on this request from Excel Online. We have a scenario where we would like to run .NET libraries from a Node.js microservice.

@orengor do you need wasm runtime or JS <->dotnet-x64 interop would be actually better?
