### ISSUE TITLE
Accepting on an IPv6Only listener creates a DualMode socket on Mac

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#47335]
```C#
using Socket listener = new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp);
listener.Bind(new IPEndPoint(IPAddress.IPv6Loopback, 0));
listener.Listen(10);

using Socket client = new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp);
client.Bind(new IPEndPoint(IPAddress.IPv6Loopback, 0));

_ = client.ConnectAsync(listener.LocalEndPoint);

using Socket server = listener.Accept();

Console.WriteLine($"listener: {listener.DualMode} | client: {client.DualMode} | server:{server.DualMode}");
```

The code above will print `listener: False | client: False | server:False` on Linux and Windows, but `listener: False | client: False | server:True` on Mac.
Since we don't do anything special in our code, I assume the OS is creating an `IPV6_V6ONLY == 0` accept socket despite the listener being `IPV6_V6ONLY == 1`.

We may want to alter the socket option in our PAL for consistency.

**Comment by antonfirsov** [comment]
What's most weird that the flag seems to be readable, but an attempt to write it leads to EINVAL.

**Comment by wfurt** [comment]
AFAIK there is guarantee that socket setting would be inherited after Accept(). It seems like you cannot set the property once the socket is bound. You can see that :
```c# 
using Socket client = new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp);
client.Bind(new IPEndPoint(IPAddress.IPv6Loopback, 0));
client.DualMode = false;
```
will throw but
```c#
using Socket client = new Socket(AddressFamily.InterNetworkV6, SocketType.Stream, ProtocolType.Tcp);
client.Bind(new IPEndPoint(IPAddress.IPv6Loopback, 0));

```

**Comment by antonfirsov** [comment]
In that case there's no way we can workaround this, I guess.

There's only one situation where this could lead to an issue:
when `ReceiveMessageFrom` is being used with the (TCP) accept socket with IPv6, it will fail [`CheckDualModeReceiveSupport`](https://github.com/dotnet/runtime/blob/a473a9c4b2d5545d8d7ce2269727a633eb90a2c4/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L32).

Since `ReceiveMessageFrom` is intended to be used with UDP, this shouldn't be an issue in real life, considering there is no good fix, we may probably close the issue as *wontfix*.

**Comment by karelz** [comment]
Triage: Looks like we can't do anything about it, it is a weird corner case. Won't Fix.
