### ISSUE TITLE
EqualityComparer<T> does not implement IEqualityComparer.GetHashCode() correctly

### ISSUE THREAD

**Issue by skrysmanski** [dotnet/runtime#47367]
Consider this code:

```c#
IEqualityComparer comparer = EqualityComparer<string>.Default;

var hashCode = comparer.GetHashCode(null!); // hashCode is 0
```

The [documentation of `IEqualityComparer.GetHashCode()`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.iequalitycomparer.gethashcode?view=net-5.0) (the non-generic version) states:

> Exceptions
> ArgumentNullException
> The type of obj is a reference type and obj is null.

I would *interpret* this as: 

> If `GetHashCode(null)` is called, an `ArgumentNullException` should be thrown.

However, instead `0` is returned.

The implementation for this behavior is here: 

https://github.com/dotnet/runtime/blob/6cf1b8ec012d52880d46fa4773f60ed52ddc9f3d/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.cs#L21

So, in my opinion there's a discrepancy between the documentation and the implementation.

Since changing the behavior of `EqualityComparer<T>.GetHashCode()` would be a breaking change, I see two options:

1. Change the documentation of `IEqualityComparer.GetHashCode()` to say that implementations *may* throw an `ArgumentNullException` if `obj` is `null`.
1. Add some comment to `EqualityComparer.GetHashCode()` stating that the implementation does *not* implement `IEqualityComparer` correctly but the implementation can't be changed for compatibility reasons.

Note: I've found #25584 which basically states the opposite. `StringComparer` should return `0` - like `EqualityComparer` does.

**Comment by stephentoub** [comment]
The docs are trying to say that exception _may_ be thrown in such a case, but it doesn't have to be. Many comparers don't,  but some do,  so consumers need to be prepared for it to.

**Comment by IllidanS4** [comment]
I don't think it is a good practice to use the exceptions thrown from `GetHashCode` to check if a value is `null` in the first place. Exceptions in the docs are permissive, not restrictive, i.e. *if* an exception is thrown, it is for one of the specified reasons. After all, a method should try to fulfill its contract as best as it could and only use exceptions as the last resort.

**Comment by GrabYourPitchforks** [comment]
I agree with @stephentoub's interpretation of this. Per discussion at https://github.com/dotnet/runtime/issues/25584, several callers take a dependency on the fact that `EqualityComparer<T>.Default.GetHashCode(null)` returns __0__.

**Comment by skrysmanski** [comment]
@stephentoub 

> The docs are trying to say that exception may be thrown in such a case, but it doesn't have to be. 

I don't see a "may" in the description of the exception. So, I guess it then comes down to one question: **Are documented exceptions in `interface`s (in the .NET documentation) part of the contract or not?**

You're saying they're not and I always thought they were.

For example, the [documentation of `IDictionary<TKey, TValue>.Item[TKey]`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2.item?view=net-5.0#System_Collections_Generic_IDictionary_2_Item__0_) contains this exception description:

> KeyNotFoundException
> The property is retrieved and key is not found.

On the other hand, the [documentation for its non-generic counterpart](https://docs.microsoft.com/en-us/dotnet/api/system.collections.idictionary.item?view=net-5.0#System_Collections_IDictionary_Item_System_Object_) does not mention this exception. Instead the documentation says that `null` will be returned in this case.

And .NET's implementations of these two interface behave exactly like this. In fact, `Dictionary<TKey, TValue>` "changes" its behavior depending on whether `IDictionary<TKey, TValue>.Item[TKey]` or `IDictionary.Item[object]` is being used:

```c#
Dictionary<string, string> genericDict = new();
IDictionary nonGenericDict = genericDict;

var x = genericDict["xyz"]; // throws "KeyNotFoundException"
var y = nonGenericDict["xyz"]; // is: null
```

So to me it would seem that at least the author of `Dictionary<TKey, TValue>` thought that the exceptions are part of the contract.

In any case, I would suggest to just change the documentation to make it clearer that the exception is optional and maybe that a return value of 0 might be chosen instead.

**Comment by skrysmanski** [comment]
> I agree with @stephentoub's interpretation of this. Per discussion at #25584, several callers take a dependency on the fact that `EqualityComparer<T>.Default.GetHashCode(null)` returns **0**.

I never said you should change the implementation. Also, `EqualityComparer<T>.Default.GetHashCode(null)` uses `IEqualityComparer<T>.GetHashCode` but I was talking about `IEqualityComparer.GetHashCode`.

**Comment by eiriktsarpalis** [comment]
> For example, the documentation of IDictionary<TKey, TValue>.Item[TKey] contains this exception description ...

Note that your example does not refute the interpretation of an exception that _may_ be thrown, it is merely pointing out one canonical implementation does throw. While throwing exception types that do not match the interface documentation probably do violate its contract, it is not clear to me that the same can be said about not throwing at all. This is certainly true in the case of Java, which uses checked exceptions. The following code compiles:
```java
public interface Foo
{
    int get() throws FileNotFoundException;
}

public class Bar implements Foo
{
    public int get()
    {
        return 42;
    }
}
```

**Comment by eiriktsarpalis** [comment]
Closing since changing the null handling behaviour of `EqualityComparer<string>.Default` would be a breaking change.
