### ISSUE TITLE
ParallelForEachAsyncTests failing on Linux Arm

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#47360]
See: https://runfo.azurewebsites.net/search/tests/?bq=definition%3Aruntime++started%3A%7E15&tq=name%3AParallelForEachAsyncTests

cc: @stephentoub 

It's hit quite a few rolling builds. Should I disable the suite while we investigate?

**Comment by stephentoub** [comment]
> It's hit quite a few rolling builds. Should I disable the suite while we investigate?

For the ones failing with "Index was outside the bounds of the array", I looked at a few via the "see" link above, and in cases where these tests failed, I see _tons_ of other tests failing as well, as if the build is simply broken in bad ways (like locks not being respected), e.g.
https://runfo.azurewebsites.net/view/build/?number=956683
I don't think that has anything to do with these tests in particular.

For the ones about a cancellation exception being not being thrown when it's expected, that's a bug.  I'll fix it.
