### ISSUE TITLE
Cannot deserialize dictionary correctly

### ISSUE THREAD

**Issue by whuanle** [dotnet/runtime#47365]
json string:
```
tags = "{\"sampler.param\":\"true\"}"
```
Json:
```json
{
	"sampler.param": "true"
}
```

Code：
```csharp
var dic = JsonSerializer.Deserialize<Dictionary<string, object>>(tags);
```
result:
```
{[sampler.param, ValueKind = String : "true"]}
```
![image](https://user-images.githubusercontent.com/2189761/105571694-26f08180-5d8d-11eb-9664-9963b9abb8dd.png)

Use Newtonsoft.Json:
```csharp
               var dic =  = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(tags);
```
Result:
```
{[sampler.param, true]}
```
![image](https://user-images.githubusercontent.com/2189761/105571722-51dad580-5d8d-11eb-84c3-8c7e2168670e.png)

**Comment by whuanle** [comment]
source demo:
```
http.status_code=200
error=true
```

**Comment by huoyaoyuan** [comment]
`System.Text.Json` always use `JsonElement` when you specify the deserialized type to object. There's nothing involved with dictionary:
`JsonSerailizer.Deserialize<object>("true")`

**Comment by slavanap** [comment]
```
public class MyDictionary {
        [JsonExtensionData]
        public Dictionary<string, object> ExtensionData { get; set; }
}

var dic = JsonSerializer.Deserialize<MyDictionary>(tags).ExtensionData;
```
@whuanle

**Comment by layomia** [comment]
As @huoyaoyuan mentioned, System.Text.Json does not guess what CLR type to create when JSON data maps to a `typeof(object)` property/field, root instance, or collection element. A `JsonElement` instance is created in those cases.

See this [doc](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#deserialization-of-object-properties) for more info and for a workaround of you want `Newtonsoft.Json`-like behavior here.
