### ISSUE TITLE
Crossgen2 produced by x86 runtime build crashes compilation due to the absence of "jitinterface_x64"

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#47388]
Current code in

https://github.com/dotnet/runtime/blob/2f1def8c556403ca85d1de50609492fef664b638/src/coreclr/tools/Common/JitInterface/JitConfigProvider.cs#L64

locates jitinterface (naturally) based on current execution architecture. This however means that Crossgen2, which still claims / pretends to be technically AnyCPU, fails loading jitinterface_x64 when run under an x64 .NET host after having been built with "-a x86". I believe this posits a pair of questions that need resolving:

1) Should we provide Crossgen2 with both jitinterface_x64 and jitinterface_x86 in an x86 build with the rationale that the library choice depends on the runtime CPU and .NET host bitness? We would need to do the same for JIT and pull off some naming trick for DiaSymReader.

2) Should we mark Crossgen2 EXE / DLL as architecture-specific? I suspect that parts of Crossgen2 already are architecture specific, at the very least DiaSymReader build is architecture-specific even though it's kind of a niche scenario, not every user of Crossgen2 needs PerfView (in particular, this is a no-concern on Unix). Marking CG2 as arch-specific means we'll no longer be able to run "dotnet Crossgen2.dll" in the runtime repo unless we introduce provisions for 32-bit dotnet host.

/cc @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
@AntonLapounov is this still an issue?

**Comment by AntonLapounov** [comment]
This issue is specific to how we build Crossgen2 in the Runtime repo and it does not affect the user story. @trylek, have you planned to do any changes for .NET 6 or should we move to future release?

**Comment by trylek** [comment]
I agree this shouldn't affect external customers and it should be safe to move to .NET 7. As part of .NET 7 planning we can discuss whether this functionality is actually needed or whether it's safe to close the issue as just a quirk specific to our internal processes even though these types of quirks typically make life harder for internal developers and complicate their ramp-up in this area.

**Comment by davidwrighton** [comment]
This is just a quirk of our internal engineering. Its a bit annoying at times, but changing this is likely to be fairly costly for basically no benefit to anybody other than folks doing their initial rampup.
