### ISSUE TITLE
DateTime Issue

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#47387]
Hi,

Referring to this Q&A:

[https://docs.microsoft.com/en-us/answers/questions/243103/error-converting-to-datetime.html?childToView=243087#answer-243087](https://docs.microsoft.com/en-us/answers/questions/243103/error-converting-to-datetime.html?childToView=243087#answer-243087)

I hope Microsoft will consider getting the DateTime without having a Converter because if you need a converter then why you specify the DateTime in the class and if you need to specify the DateTime in the class why you need a Converter.

Thanks,
Jassim

**Comment by slavanap** [comment]
@jrahma, not all APIs use ISO date&time format. Registering default converter would break other converters for that type.

If you are annoyed by adding converters with commands for every serialization operation, I'd recommend you to try attributes:
```
public class Document  {
    [JsonConverter(typeof(JsonDateConverter))]
    public DateTime EffectiveDate { get; set; }
}
```

**Comment by Clockwork-Muse** [comment]
.... to be more clear, the date/time being returned by the API you're calling isn't returning a valid ISO-formatted date-time value: it's missing `'T'` between the date and time portions.

```
// Currently is
[{"time_to_activate":"2020-01-24 10:30:00"}]
// Should be
[{"time_to_activate":"2020-01-24T10:30:00"}]
```
If you can get the supplier of the API to correct this behavior, you won't need a converter.  The examples on the linked page of the accepted answer show that to be the case.

<hr />

Is this an area we should relax the parse just slightly, to not require the `'T'`?  I'll note that `DateTime.Parse(...)` itself does not require the character by default

**Comment by jrahma** [comment]
> [JsonConverter(typeof(JsonDateConverter))]

I tried dit but getting this error:

**Error CS0246: The type or namespace name 'JsonDateConverter' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Angels)**

Here is the code:

```
class MyProfileData
{
    public int user_id { get; set; }
    public string first_name { get; set; }
    public string last_name { get; set; }
    [JsonConverter(typeof(JsonDateConverter))]
    public DateTime date_of_birth { get; set; }
    public string country_name { get; set; }
    public string email_address { get; set; }

    public string user_image
    {
        get
        {
            return string.Format("https://www.mydomain.com/gallery/photos/{0}.png", user_id);
        }
    }
}

```

**Comment by slavanap** [comment]
Add this class, @jrahma 

```
    public class JsonDateConverter : JsonConverter<DateTime> {
        public override DateTime Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
            ToDateTime(reader.GetString());
        public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options) =>
            writer.WriteStringValue(ToString(value));

        const string Format = "yyyy-MM-dd";
        public static DateTime ToDateTime(string s) =>
            DateTime.ParseExact(s, Format, CultureInfo.InvariantCulture);
        public static string ToString(DateTime value) {
            if (value != value.Date)
                throw new ArgumentException("Invalid date contains non-zero time of the day", nameof(value));
            return value.ToString(Format, CultureInfo.InvariantCulture);
        }
    }

```

**Comment by slavanap** [comment]
And next time please define your own. Microsoft has a lot of docs regarding JsonConverterAttribute

**Comment by layomia** [comment]
As @slavanap mentioned, converters can be used to provide custom logic for various DateTime(Offset) formats. Please see https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support for more info.
