### ISSUE TITLE
Question about the garbage collector and instance fields

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#47386]
```c#
private static C _strongReference = new C();

class C
{
    private LargeObject _field = new LargeObject();
}
```

From what I know about the garbage collector, the object referred to by `_strongReference` will never be collected as long as `_strongReference` doesn't change, regardless of whether or not any other code references `_strongReference` (please correct me if I'm wrong). However, the `LargeObject` referred to by `_field` is only ever referenced in the field initializer of `C`. Does that allow the object referred to by `_strongReference._field` to be eligible for garbage collection even though `_strongReference` is not?

**Comment by stephentoub** [comment]
> Does that allow the object referred to by _strongReference._field to be eligible for garbage collection even though _strongReference is not?

No
