### ISSUE TITLE
build coreclr v3.1.11 failed

### ISSUE THREAD

**Issue by kssoftwangwg** [dotnet/runtime#47383]
### Description

I cloned the CoreCLR source code,and try to compile . By reading windows-instructions.md build this.  But it failed, **_Please help me resolve these errors_ thanks very much **. 
git clone https://github.com/dotnet/coreclr.git, and git checkout v3.1.11. Because https://github.com/dotnet/runtime.git repo not have coreclr v3.1.11 tag.

These are errorlogs:

```
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrdata_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\corpub_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrinternal_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\xcordebug_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\corprof_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\mscorsvc_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\xclrdata_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\cordebug_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrprivbinding_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\corsym_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\sospriv_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrprivhosting_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrprivappxhosting_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
    17C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: 生成“已定义”的宏扩展具有未定义的行为 (编译源文件 C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\idls_out\clrprivruntimebinders_i.c) [C:\coreclr\coreclr\bin\obj\Windows_NT.x64.Debug\src\inc\corguids.vcxproj]
```

(1).windows os version:
![图片](https://user-images.githubusercontent.com/21151911/105632035-2e4a8480-5e8c-11eb-9478-765ea079f450.png)
(2).vs2019 configuration:
![图片](https://user-images.githubusercontent.com/21151911/105632066-5803ab80-5e8c-11eb-9cd3-cb90b0e04b13.png)
(3).vs2019 version:
![图片](https://user-images.githubusercontent.com/21151911/105632076-69e54e80-5e8c-11eb-8538-fdf00f17eecb.png)
(4).py version:
![图片](https://user-images.githubusercontent.com/21151911/105632097-8bded100-5e8c-11eb-9206-3e9a88bad67a.png)
(5).cmake verison:
![图片](https://user-images.githubusercontent.com/21151911/105632107-97ca9300-5e8c-11eb-99fb-b7d696fcfe07.png)
(6).global.json:
```json
{
  "tools": {
    "dotnet": "3.1.100"
  },
  "native-tools": {
    "cmake": "3.19.3",
    "python": "3.9.1"
  },
  "msbuild-sdks": {
    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.20113.5",
    "Microsoft.DotNet.Helix.Sdk": "2.0.0-beta.20113.5",
    "Microsoft.Build.NoTargets": "1.0.53",
    "Microsoft.Build.Traversal": "2.0.2"
  }
}
```

**Comment by kssoftwangwg** [comment]
@janvorli  Thank you very much for reply message, I executed the build command again. and submitted the complete console output to: https://gist.github.com/kssoftwangwg/fb3b60d11809258b89cd01d3bc946524.  These errors are like windows 10 sdk  winbase.h head file throw out ? or  coreclr "src\inc\idls_out\c source files" thow out? thow error code: C2220, warning code: C5105.

**Comment by janvorli** [comment]
@kssoftwangwg the build output seems to be missing a lot of things I can see when I build it locally. Can you please try to run a clean build? Just do `git clean -xdf` in the root folder of the repo and then run `build.cmd` without any arguments. The log should have some details on which Visual C++ it found etc. You may want to change the screen buffer size in the properties of your command prompt from which you run the build to make sure that the complete output is still there after the build fails.
![image](https://user-images.githubusercontent.com/10758568/106148628-8e397780-6179-11eb-920b-236a54030f31.png)

**Comment by kssoftwangwg** [comment]
@janvorli  At your request, I tried compiling again.  
(1).  in the root folder exec clean -xdf;
![image](https://user-images.githubusercontent.com/21151911/106273936-6bd55600-626e-11eb-8b2f-c7790f72d3f0.png)
(2). and exec .\build.cmd without any arguments on windowsPowerShell:
![image](https://user-images.githubusercontent.com/21151911/106274173-cf5f8380-626e-11eb-8469-6ce17b8a301d.png)
Complete console output file on: https://gist.github.com/kssoftwangwg/fb3b60d11809258b89cd01d3bc946524. filename is: gistfile2.txt

**Comment by janvorli** [comment]
@kssoftwangwg I can see that the Windows SDK file WinBase.h really has the problem that the compiler complains about. I am not sure why it doesn't have the same problem on my local box. I can see a slightly newer Windows SDK is being used, but it has the same issue there. 

You can fix the problem by disabling the warning that it complains about. Can you please try to add 
`/wd5105` to the list of disabled warnings at the following line?
https://github.com/dotnet/coreclr/blob/v3.1.11/configurecompiler.cmake#L579

**Comment by kssoftwangwg** [comment]
@janvorli  Thank you very much for reply message, in configurecompiler.cmake file added /wd5105  disabled warnings , exec build.cmd after，restore src build.proj （）  a new error has occurred，Like the errors you listed the other day:

**console section log:**
已用时间 00:02:28.06
BUILD: Commencing build of System.Private.CoreLib for Windows_NT.x64.Debug
Installing dotnet using Arcade...
running: powershell -NoProfile -ExecutionPolicy unrestricted -Command ". C:\coreclr\coreclr\eng\configure-toolset.ps1; . C:\coreclr\coreclr\eng\common\tools.ps1; InitializeBuildTool"

Name                           Value
----                           -----
Path                           C:\coreclr\coreclr\.dotnet\dotnet.exe
Command                        msbuild
Tool                           dotnet
Framework                      netcoreapp2.1


Running: dotnet restore /nologo /verbosity:minimal /clp:Summary /nodeReuse:false          /p:PortableBuild=true /maxcpucount /p:IncludeRestoreOnlyProjects=true /p:ArcadeBuild=true          C:\coreclr\coreclr\src\build.proj          /flp:Verbosity=normal;LogFile="C:\coreclr\coreclr\bin\Logs\System.Private.CoreLib_Windows_NT__x64__Debug.log" /flp1:WarningsOnly;LogFile="C:\coreclr\coreclr\bin\Logs\System.Private.CoreLib_Windows_NT__x64__Debug.wrn" /flp2:ErrorsOnly;LogFile="C:\coreclr\coreclr\bin\Logs\System.Private.CoreLib_Windows_NT__x64__Debug.err" /p:__BuildOS=Windows_NT /p:__BuildType=Debug /p:__BuildArch=x64 /p:RestoreDuringBuild=true   /p:BuildManagedTools=true
  C:\coreclr\coreclr\src\build.proj 的还原在 54.13 ms 内完成。
  C:\coreclr\coreclr\src\tools\runincontext\runincontext.csproj 的还原在 5.07 sec 内完成。
  C:\coreclr\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj 的还原在 12.68 sec 内完成。
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : warning NU1603: R2RDump 依赖于 System.CommandLine (>= 0.1.0-e160119-1)，但找不到 System.CommandLine 0.1.0-e160119-1。 已解决 System.CommandLine 0.3.0-alpha.20054.1 的近似最佳匹配。  [C:\coreclr\coreclr\src\build.proj]
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : error NU1102: 找不到版本为 (>= 1.0.1-prerelease-00005) 的包 Microsoft.NETCore.CoreDisTools [C:\coreclr\coreclr\src\build.proj]
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : error NU1102:   - 在 dotnet-core 中找到 1 个版本[ 最接近版本: 1.0.1-prerelease-00001 ] [C:\coreclr\coreclr\src\build.proj]
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : error NU1102:   - 在 nuget.org 中找到 0 个版本 [C:\coreclr\coreclr\src\build.proj]
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : error NU1102:   - 在 myget.org dotnet-core 中找到 0 个版本 [C:\coreclr\coreclr\src\build.proj]
C:\coreclr\coreclr\src\tools\r2rdump\R2RDump.csproj : error NU1102:   - 在 dotnet-coreclr 中找到 0 个版本 [C:\coreclr\coreclr\src\build.proj]

The complete console output: https://gist.github.com/kssoftwangwg/fb3b60d11809258b89cd01d3bc946524 filename is: gistfile2.txt

**Comment by hoyosjs** [comment]
This failure in the build is related to described in https://github.com/dotnet/runtime/issues/46987; closing as a duplicate.
