### ISSUE TITLE
X509ChainPolicy.CustomTrustStore appears to be readonly in .NET 5

### ISSUE THREAD

**Issue by zeus82** [dotnet/runtime#47392]
I'm trying to validate certificates generated from a self signed 'Root CA', and I came across this discussion, however when I try to set `CustomTrustStore` its readonly.  Am I missing something?

> Is X509VerificationFlags.AllowUnknownCertificateAuthority means that we accept a CA that isn't in the chain at all ?

AllowUnknownCertificateAuthority means the validation state ignores an incomplete chain (X509ChainStatusFlags.PartialChain) or a chain that completed with an untrusted root (X509ChainStatusFlags.UntrustedRoot).

> I'm trying to have code that can validate a certificate chain where the CA cert is self signed

We've added a feature for this in .NET 5.

```C#
Console.WriteLine("Signed + Authority = " + Validate(signedBy, new X509ChainPolicy() {
                RevocationMode = X509RevocationMode.NoCheck,
                VerificationTime = DateTime.Now,
                CustomTrustStore = { authority },
                TrustMode = X509ChainTrustMode.CustomRootTrust,
            }));
```

_Originally posted by @bartonjs in https://github.com/dotnet/runtime/issues/39283#issuecomment-658280486_

**Comment by vcsjones** [comment]
The property of the collection is read-only, but the collection itself is not. You should be able to use `CustomTrustStore.Add`, `AddRange`, `Remove`, `Clear`, etc.

**Comment by zeus82** [comment]
lol - I think that can be classified as an ID-10-T issue.

Thanks for your help!
