### ISSUE TITLE
COM references not released in dotnet 5

### ISSUE THREAD

**Issue by justin-michel-boeing** [dotnet/runtime#47409]
https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo

We're beginning a project to replace some Java Excel integration with dotnet, and I hoped to use dotnet 5. 
I was able to get the above demo working, but only after editing the csproj to change Microsoft.Office.Core version to 2.7 and Microsoft.Office.Interop.Excel to 1.8 (We only have Office 2013 at the moment).

What I notice is that each time I run the trivial app it spawns another instance of Excel.exe which I then have to kill with Task Manager. I confirmed that the problem still exists by commenting out everything inside the try/catch except "excel = new Excel.Application", and that the problem "solved" by adding Marshal.ReleaseComObject(excel) to the end. 

Does dotnet 5 no longer register Finalizers for all the implicitly created COM references?

I confirmed that the same code works when using dotnet sdk 4.8. 

Btw, additionally to mimic our existing usage, we need Marshal.GetActiveObject() so that we can attach to the user's open Excel and import/export from sheets they have open. Is there any plan to add GetActiveObject back in to Marshal for dotnet 5+?

**Comment by AaronRobinsonMSFT** [comment]
>Does dotnet 5 no longer register Finalizers for all the implicitly created COM references?

This does still happen but not during process shutdown.

>Is there any plan to add GetActiveObject back in to Marshal for dotnet 5+?

No. This was discussed at https://github.com/dotnet/runtime/issues/37617.

**Comment by justin-michel-boeing** [comment]
I did try to GC.Collect() + GC.WaitForPendingFinalizers(), and that never released the Excel.Application either. 

Is there some other way to ensure that our application releases all COM references? 

It looks to me like the only safe thing to do with dotnet 5 is write explicit Dispose wrappers to deal with this, and structure the code as if it were C++. We're replacing some ancient Java code with C#, and the old code spends 50% of its runtime in Java Finalizers. So it's not necessarily a bad thing if C# avoids finalizers completely. I just want to know the best way to deal with this, and there is a lot of misinformation out there.
