### ISSUE TITLE
Blazor Async Main and Top-Level Statements Seems to Have Issues

### ISSUE THREAD

**Issue by JasonBock** [dotnet/runtime#47404]
### Describe the bug
If I use top-level statements for a Blazor WebAssembly application, the application seems to work, but I get an unhandled exception warning.

### To Reproduce
I was getting this issue when I was updating code I use for demos to .NET 5.0, which is [here](https://github.com/JasonBock/BlazingTheWeb). For a simple reproduction, do this:

* Create a new Blazor WebAssembly application targeting .NET 5.0 with no authorization, no HTTPS configuration, etc.
* Don't change anything in the code. Just run the app, and the standard Blazor app template should show up in the browser.
* Now, change the code in `Program.cs` to this:

```
using BlazorApp1;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Net.Http;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

await builder.Build().RunAsync();
```
Note that this will force you to update the first line in `App.razor` to reference another type in the project, something like this:
```
<Router AppAssembly="@typeof(App).Assembly" PreferExactMatches="@true">
```
### Exceptions (if any)
Now, when you run the app, it should still work, but you should see the yellow bar at the bottom saying "An unhandled error has occurred. Reload".

The console contains this exception information:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1  ---> System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at <Program>$.<Main>(String[] args)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    --- End of inner exception stack trace ---
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint(String assemblyName, String[] args)
d.printErr @ blazor.webassembly.js:1
```

**Comment by lewing** [comment]
So the issue here is that the normally the compiler generates a synchronous `<Main>` that calls wait on the async `Main`, and the workaround that we use to avoid the .Wait call is to look up the unmangled version and call it directly.  In the case of  Top-Level programs it appears the compiler generates a `<Main>` that calls a generated `<Main>$`.  For the immediate future we can add another case to the lookup logic that can handle this difference.

Since AspNetCore uses it own version of this lookup there will need to be a fix there as well.

**Comment by javiercn** [comment]
@lewing thanks for the quick turnaround!

I'm not exactly sure we need to do anything in the ASP.NET Core side ourselves. I don't think we use a custom `driver.c` anymore, but it'll be easy to test if we need to do anything else once we get an updated runtime on the repo.

**Comment by craigajohnson** [comment]
@lewing @javiercn this is great! Along these same lines, it would also be extremely useful if Blazor could --also-- probe for an async Task method with an attribute e.g., [WebAssemblyEntryPoint]. This would be useful as a decoupling device. Of course if no attributed method exists it can just fall back.

**Comment by craigajohnson** [comment]
Something like this perhaps? https://gist.github.com/craigajohnson/48685062bbace2a1fc89a497a7869428
