### ISSUE TITLE
[Breaking change] `Environment.ProcessorCount` on Windows takes processor affinity into account

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#47427]
When the process is affinitized on startup, the behavior of `Environment.ProcessorCount` currently differs between Windows and Linux. On Linux, the property returns the number of processors available according to the affinity mask. On Windows, the property returns the number of processors configured in the system and ignores the affinity mask. The property is often used to determine the amount of parallelism to use in the process, and it has been observed that not limiting the property's value based on affinitization can lead to worse performance.

On Linux, CPU resource limits placed through cgroups also affect the value returned by the property, as we have found through trial-and-error that returning the restricted number of processors from this property is the most appropriate behavior that makes most callers work well.

### Goal

- Have `Environment.ProcessorCount` return a value that represents an appropriate level of parallelism that may be used in the process based on affinitization and CPU resource limits
- Have the property return a consistent value in comparable relevant configuration between Windows and Linux

### Behavior before change

On a machine with 8 logical processors:
- When the process is affinitized to 1 logical processor:
  - Windows: `Environment.ProcessorCount == 8`
  - Linux: `Environment.ProcessorCount == 1`
- When CPU resources for the process are limited to the equivalent of 1 logical processor:
  - Windows: `Environment.ProcessorCount == 8`
  - Linux: `Environment.ProcessorCount == 1`

### Behavior after https://github.com/dotnet/runtime/pull/45943

- When the process is affinitized to 1 logical processor:
  - Windows: `Environment.ProcessorCount == 1`
  - Linux: `Environment.ProcessorCount == 1`
- When CPU resources for the process are limited to the equivalent of 1 logical processor:
  - Windows: `Environment.ProcessorCount == 8`
  - Linux: `Environment.ProcessorCount == 1`

### Behavior after other such issues are fixed (no PR yet)

- When the process is affinitized to 1 logical processor:
  - Windows: `Environment.ProcessorCount == 1`
  - Linux: `Environment.ProcessorCount == 1`
- When CPU resources for the process are limited to the equivalent of 1 logical processor:
  - Windows: `Environment.ProcessorCount == 1`
  - Linux: `Environment.ProcessorCount == 1`

### Versions affected

.NET 6

### Potential breaks on Windows and workarounds

- Code that uses `Environment.ProcessorCount` and scales down parallelism based on other app or system configuration (including potentially the process' affinity mask) may end up using lower parallelism than intended
  - Workaround may be to update the application's parallelism scaling
- Code that expects `Environment.ProcessorCount` to return the configured logical processor count may have unexpected results. For example code that verifies that the process is not started affinitized by comparing the affinitized processor count to `Environment.ProcessorCount` would fail to detect affinitized startup because the comparison would be equal. Or the process may intend to display the total processor count.
  - Workaround may be to pinvoke to get the total processor count. May not be ideal. Providing full information in other APIs would need discussion to determine what to provide, for example, number of processors configured in the system, number of processors that are online/offline, number of processors the process is affinitized to, CPU quota limits, etc.
- Code that happens to perform worse when the value returned by `Environment.ProcessorCount` is limited by affinitization or CPU resource limits
  - If these become common, it may be necessary to provide a workaround, such as to provide a way to configure what `Environment.ProcessorCount` would return, or to provide other APIs

Currently, a config option is not provided to revert the behavior. The difference in behavior between Windows and Linux existed in .NET 5 and below, where Linux has not offered a config option to provide the total processor count, so there hasn't been a workaround for the above issues on Linux so far.

### Non-breaking

- The thread pool already took affinitization into account in the default parallelization it uses on Windows, when the process is not configured to use multiple CPU groups (the default). In .NET 6 thread pool worker thread management was migrated to managed code and uses `Environment.ProcessorCount`, so after https://github.com/dotnet/runtime/pull/45943 thread pool worker thread parallelization in .NET 6 would be the same as before in that scenario.

**Comment by kouvel** [comment]
CC @dotnet/compat

**Comment by CoffeeFlux** [comment]
Do you know if we need to fix this on the Mono side as well?

**Comment by kouvel** [comment]
It looks like Mono already uses `sched_getaffinity`, and notes some other interesting points:
https://github.com/dotnet/runtime/blob/9f8aab73d93156933ae65a476204bf62c02f6537/src/mono/mono/utils/mono-proclib.c#L754-L864

**Comment by richlander** [comment]
This change seems intuitive to me and aligns with past feedback we've been given.

I wonder if we should add an `Environment.MachineProcessorCount` or something similar this release that always reported the max machine value. We've talked about it. Doing this would only make sense to me if we used that property from at least one place in the product

**Comment by kouvel** [comment]
Doc issue: https://github.com/dotnet/docs/issues/24246
