### ISSUE TITLE
Hard to clean up string returned by CallUtils::GetMethodFullName

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#47432]
A static analyzer flagged this code as not releasing resources:

https://github.com/dotnet/runtime/blob/5415849b2f793b7208789ee9b0f4a1c468edd3b1/src/coreclr/ToolBox/superpmi/superpmi-shared/methodcontext.cpp#L6422

It calls `CallUtils::GetMethodFullName` but doesn't free the returned resources.

I took a quick look at `CallUtils::GetMethodFullName` and it seems like it can return a number of values:

https://github.com/dotnet/runtime/blob/5415849b2f793b7208789ee9b0f4a1c468edd3b1/src/coreclr/ToolBox/superpmi/superpmi-shared/callutils.cpp#L264-L273

https://github.com/dotnet/runtime/blob/9f8aab73d93156933ae65a476204bf62c02f6537/src/coreclr/ToolBox/superpmi/superpmi-shared/callutils.cpp#L337

It can return a pointer to a constant string allocated statically. Or it can return a pointer to a dynamically-allocated array. This makes it harder for the references to be cleaned up correctly.

**Comment by JulieLeeMSFT** [comment]
CC @BruceForstall for SPMI tooling related issue.

**Comment by BruceForstall** [comment]
We haven't paid any attention to eliminating memory leaks in SPMI yet.
