### ISSUE TITLE
Increase timeout for CoreCLR Product Build windows arm64 release leg

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/runtime#47436]
Signing is taking slightly longer than anticipated, for example, in this build:
https://dev.azure.com/dnceng/internal/_build/results?buildId=951766

If slightly more time had been allocated for the build, it would have succeed.

**Comment by hoyosjs** [comment]
I've already increased the timeouts after this instance. Thanks @ChadNedzlek
