### ISSUE TITLE
Variadic-like Version Math.Max and Math.Min Method

### ISSUE THREAD

**Issue by Jimmy-Hu** [dotnet/runtime#47456]
## Background and Motivation

`Max` methods with two parameters (`public static byte Max(byte val1, byte val2);`, `public static decimal Max(decimal val1, decimal val2);`, `public static double Max(double val1, double val2);`...) are included in `System.Math` class. Also, `Min` methods with two parameters (`public static byte Min(byte val1, byte val2);`, `public static decimal Min(decimal val1, decimal val2);`, `public static double Min(double val1, double val2);`...) are included in `System.Math` class. In this API proposal, I am trying to propose a series of variadic-like version Math.Max method and a series of variadic-like version Math.Min method with more than two parameters.

## Proposed API

```diff
namespace System
{
    public static class Math
    {
+    public static byte Max(params byte[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static decimal Max(params decimal[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static double Max(params double[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static short Max(params short[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static int Max(params int[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static long Max(params long[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static sbyte Max(params sbyte[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static float Max(params float[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static ushort Max(params ushort[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static uint Max(params uint[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    
+    public static ulong Max(params ulong[] values)
+    {
+    	return System.Linq.Enumerable.Max(values);
+    }
+    public static byte Min(params byte[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static decimal Min(params decimal[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static double Min(params double[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static short Min(params short[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static int Min(params int[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static long Min(params long[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static sbyte Min(params sbyte[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static float Min(params float[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static ushort Min(params ushort[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static uint Min(params uint[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
+    
+    public static ulong Min(params ulong[] values)
+    {
+    	return System.Linq.Enumerable.Min(values);
+    }
    }
}
```

## Usage Examples

The calculation of maximum / minimum of a group of numbers (more than two) can be done easily as below.

``` C#
Console.WriteLine(Math.Max(3, 5, 8));
Console.WriteLine(Math.Max(3, 5, 8, 10));
Console.WriteLine(Math.Max(3, 5, 8, 10, 12));
Console.WriteLine(Math.Min(3, 5, 8));
Console.WriteLine(Math.Min(3, 5, 8, 10));
Console.WriteLine(Math.Min(3, 5, 8, 10, 12));
```

**Comment by tannergooding** [comment]
What's the benefit of this over just using the LINQ versions?

**Comment by Jimmy-Hu** [comment]
@tannergooding Thank you for the comments. If I want to find maximum / minimum of numbers, the first thing comes up in my mind is to seek methods in System.Math class. Although the implementation detail of these APIs is totally based on the LINQ versions, I think the benefit of this design is to make `Math.Max` / `Math.Min` more generic no matter using in two or more numbers cases.

**Comment by SingleAccretion** [comment]
The problem with this design is that it is low performance (due to the `params` array allocation, among other things). This is fine for LINQ because it is also a low-performance (relatively speaking of course) library, but questionable for the `Math` class, which historically has been tuned for best throughput and memory usage.

I think it would be best to wait for language features like `params Span<T>` before introducing these overloads.

**Comment by tannergooding** [comment]
Closing as I don't believe these are APIs that should be added to System.Math today.

We have alternatives, such as in Linq, that do provide the desired functionality and rolling your own API here is fairly trivial.
