### ISSUE TITLE
Add support for host startup hooks to Mono

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#47462]
The dotnet core host supports [host startup hooks](https://github.com/dotnet/runtime/blob/master/docs/design/features/host-startup-hook.md) to inject assemblies to run before the main method.

We should implement support for this in Mono.

---

However for some use cases, such as mobile workloads, it is not enough to add runtime support - we will also need workload integration to bundle the startup hook assemblies into the mobile apps.  At that point it may make sense to use a more static approach - instead of inspecting an environment variable and doing method lookup using reflection, just execute the hooks directly from the mobile embedders before the runtime starts (or pass a less dynamic structure to the runtime to execute the methods on the embedders' behalf).

Also need to investigate if in general we need to give the embedders a way to identify the right time to run the startup hooks (for example after some managed code executes to set up the Android or ios environment).

Additionally if the startup hooks need any special permissions beyond what the app needs, the workloads need to be involved.

---

In scenarios where MonoVM may be substituted for CoreCLR (ie console apps) we should implement the startup hook support as spec'd.

**Comment by lambdageek** [comment]
For reference, CoreCLR calls the startup hooks from https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/vm/assembly.cpp#L1646

And the class [`StartupHookProvider`](https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/System.Private.CoreLib/src/System/StartupHookProvider.cs) looks like it can be shared between both runtimes.

**Comment by lambdageek** [comment]
Because of embedders, (who must call `mono_jit_init_version`, but not necessarily `mono_runtime_exec_main`) we should actually run the startup hooks near the end of `mono_init_internal` (after the domain and the base types have been installed), rather than at the beginning of `mono_runtime_exec_main`.

Also I'm assuming that the startup hooks are primarily about setting up the managed environment.  If they need to do Android or iOS API calls, running them near the end of `mono_jit_init_version` might be too early - the mobile embedders may need to do some initialization from their managed entrypoints before the startup hooks can do their work.  In that case we may need to provide some managed callback or event that the embedders can invoke when they're prepared to run the startup hooks.

**Comment by vitek-karas** [comment]
In CoreCLR startup hooks only run when `coreclr_execute_assembly` is used. The other ways to run code from native hosting (`coreclr_create_delegate`) do not trigger the startup hooks.

**Comment by lambdageek** [comment]
@SamMonoRT We can probably add the runtime support, but:
1. I'm not aware of an end to end scenario where we have a use case for startup hooks on mobile.
2. We would also need to do updates to the SDKs to bundle the startup hooks on mobile

It might make sense to add the support for desktop only so that, for example, s390x can use startup hooks to more closedly match coreclr behavior on their platform.

**Comment by SamMonoRT** [comment]
Moving to 8.0.0

**Comment by lambdageek** [comment]
We may want this early in net8 to support Ctrl-F5 hot reload on mobile

**Comment by lambdageek** [comment]
Looks like the "how to get code on the device" problem is understood by @mcumming and @jonathanpeppers, so the runtime should just do our bits (look for the var, do an assembly load request)
