### ISSUE TITLE
PgoManager::ReadPgoData doesn't close file on error?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#47485]
There's a `FILE*` obtained from `_wfopen(...)` in  `PgoManager::ReadPgoData`, but it's not closed if there's an error in `fgets` or `sscanf_s`:

https://github.com/dotnet/runtime/blob/1c0ca4a47acfcfdb397f039816f74a03c09cd76e/src/coreclr/vm/pgo.cpp#L303-L323

In fact, reading the entire method, it doesn't look like this `FILE*` is closed anywhere at all. Is this a bug or am I missing something obvious?

**Comment by mangod9** [comment]
cc @davidwrighton
