### ISSUE TITLE
Possible memory leak in ClrDataMethodDefinition::NewFromModule

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#47493]
This method allocates data with `new` but doesn't `delete` it:

https://github.com/dotnet/runtime/blob/14589b12abdfa1727f14f5d61ac5c682d4504c0a/src/coreclr/debug/daccess/task.cpp#L3672-L3690

The values are copied over through assignment into `*methDef` or `*pubMethDef`, but `def` is never `delete`d.

**Comment by hoyosjs** [comment]
These pointers usually are surfaced for dump collection to the caller of the COM api. These object that's returned is add-refed and when the caller calls release on the returned object, the object will clean after itself.
