### ISSUE TITLE
.NET Core new JSON DeSerializer dont work with extra properties

### ISSUE THREAD

**Issue by radenkozec** [dotnet/runtime#475]
In JSON.NET when we sent object with extra properties from JavaScript app in body of requests deserializer just ignored extra properties.
New deserializer don't work and deserialize null if model does not match 100% which is wrong.
We use ES6/ES7 and we don't need to have all models match 100% like in TypeScript.

Any workaround?

**Comment by radenkozec** [comment]
My error in code delete this.

**Comment by ahsonkhan** [comment]
> My error in code delete this.

@radenkozec - out of curiosity, what was the error you fixed? I want to understand it, particularly for the benefit of others who might hit the same issue you did.

> deserializer just ignored extra properties.

If you have extra properties in the payload and need to roundtrip them, you could use the `JsonExtensionData` attribute to annotate an "overflow" dictionary.

> New deserializer don't work and deserialize null if model does not match 100% which is wrong.

Was there a naming policy or casing mismatch issue?

**Comment by radenkozec** [comment]
This was not extra properties problem.
I was sending "5" in JSON instead of 5 for integer property. JSON.NET probably fixed these conversion issues however I fixed my errors in code. I don't prefer these kind of "auto-fixing" because it will affect performance. So on your side you don't need to do anything
