### ISSUE TITLE
MailAddress.TryCreate(String, MailAddress) throws exception

### ISSUE THREAD

**Issue by hbjorgo** [dotnet/runtime#47515]
### Description

System.Net.Mail.MailAddress.TryCreate(String, MailAddress) throws exception, but it shouldn't.

```MailAddress.TryCreate(null, out var email);```
throws
System.ArgumentNullException: 'Value cannot be null. (Parameter 'address')'

```MailAddress.TryCreate("", out var email);```
throws
System.ArgumentException: 'The parameter 'address' cannot be an empty string. (Parameter 'address')'

I expect it to behave similar to `Int32.TryParse(string, int)` and  return false, not throw an exception.

Example program:
```c#
using System.Net.Mail;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            MailAddress.TryCreate(null, out var email);
        }
    }
}
```

### Configuration

Tested in Visual Studio 2019 16.8.4, running as a .Net 5.0 Console application on Windows 10 x64.

```
Installed SDKs:
5.0.102 [C:\Program Files\dotnet\sdk]

Installed runtimes:
Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Regression?

This method was introduced in .Net 5.0.

### Other information

My workaround:
```c#
string input = null;
if (!string.IsNullOrWhiteSpace(input) && MailAddress.TryCreate(input, out var email))
{
    // Valid email in here
}
```

**Comment by ManickaP** [comment]
It makes sense to me. We're already passing in a flag saying whether to throw or not during parsing:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Mail/src/System/Net/Mail/MailAddress.cs#L120
Yet we ignore it for nulls and empty string check.

@karelz Is stopping throwing exception for null and empty string a breaking change?

**Comment by ManickaP** [comment]
Also @MarcoRossignoli do you by any chance remember why we throw for null/empty even though it's a `Try` version of the method?

**Comment by MarcoRossignoli** [comment]
Makes sense also to me, that checks should be moved only in ctor or use the flag. 
We didn't discuss that IIRW.

**Comment by karelz** [comment]
It is a new method, so I would consider it honest bug and only a technical breaking change.
Callers have to check for false anyway, so there is very little chance it would break anyone. No need to document it as breaking change IMO.

**Comment by karelz** [comment]
This should be easy to do -- @hbjorgo are you interested in putting up PR with a fix?

**Comment by hbjorgo** [comment]
I don't have all the prerequisites for building this set up. Thank you for asking - maybe next time!
