### ISSUE TITLE
[browser] Uncaught Error: System.Delegate.DynamicInvoke method can not be resolved.

### ISSUE THREAD

**Issue by kjpou1** [dotnet/runtime#47516]
When building an app using `<PublishTrimmed>true</PublishTrimmed>` the linker is linking out `System.Delegate.DynamicInvoke`

```
Uncaught Error: System.Delegate.DynamicInvoke method can not be resolved.
    at Object.invoke_delegate (dotnet.js:9519)
    at WebSocket.<anonymous> (dotnet.js:8531)
```

**Comment by ssanderlin** [comment]
@kjpou1 Would it be possible to get this cherry-picked into the 5.x branch for release in 5.0.4? I've been running into this exact issue when working with WASM and ASP.NET Core SignalR even without PublishTrimmed enabled, but I am thus far unable to repro using 6.0.100-preview.1.21103.13.
