### ISSUE TITLE
System.Text.Json should support IgnoreDataMemberAttribute or equivalent

### ISSUE THREAD

**Issue by edwinloubser** [dotnet/runtime#47514]
Currently the only supported way to ignore individual properties is by decorating properties with the JsonIgnore attribute. But this means that libraries needs to take a dependency on System.Text.Json which is undesirable. I wish for my libraries to indicate which properties need not be serialized in a serialization library agnostic way. IgnoreDataMemberAttribute seems to be supported by most (all?) serialization libraries and it seems odd that System.Text.Json does not.

**Comment by layomia** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/29975.
