### ISSUE TITLE
+1 For compiler safety. How does it make sense to make an API available that is guaranteed to be the wrong thing to use? The ideal experience is for `BeginInvoke` not to exist on core.

### ISSUE THREAD

**Issue by zhyy2008z** [dotnet/runtime#47510]
+1 For compiler safety. How does it make sense to make an API available that is guaranteed to be the wrong thing to use? The ideal experience is for `BeginInvoke` not to exist on core.

_Originally posted by @jnm2 in https://github.com/dotnet/runtime/issues/16312#issuecomment-193357722_

**Comment by jnm2** [comment]
My self 5 years ago has even less tact than my current self, apparently. 🙄

**Comment by stephentoub** [comment]
The C# compiler synthesizes a BeginInvoke method when you use the `delegate` keyword.  Are you proposing it not?  If so, this is an issue for dotnet/roslyn or dotnet/csharplang.

https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxASwDYB8ACAmARgFgAoHAZgAIATODOAcwnkpwBZKAxAe24AoAlAG4gA===

**Comment by zhyy2008z** [comment]
Ok, I will propose a new issue for dotnet/roslyn.
