### ISSUE TITLE
Consider to support negative time in ToFileTime, or some equivalent

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#47523]
https://github.com/microsoft/microsoft-ui-xaml/issues/3889

CsWinRT uses [ToFileTime](https://github.com/microsoft/CsWinRT/blob/5351b4bab3148715969529d358e07f864f43ac8d/src/WinRT.Runtime/Projections/SystemTypes.cs#L65) to marshal `DateTimeOffset`. It throws on negative value.

The behavior is different from old runtime with direct WinRT support, which correctly marshals negative values.

[WinRT doc](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.DateTime) says negative values are valid, but hints that negative values are invalid for FILETIME.

Please decide at which side to handle the negative case.

**Comment by AaronRobinsonMSFT** [comment]
@huoyaoyuan This should be moved to the [C#/WinRT](https://github.com/microsoft/CsWinRT/) repository.
