### ISSUE TITLE
Swedish locale, NumberFormat.NegativeSign from ICU ignores parseLenient data from CLDR

### ISSUE THREAD

**Issue by tedpar** [dotnet/runtime#47524]
### Description

Since .Net 5.0 in combination with Win10 May 2019 Update (build 18362) and later, ICU instead of NLS is used as source for locale data if I understand it correctly.

This causes issues with the negative sign using a Swedish locale, which then gets changed from Unicode 'Hyphen-Minus' to 'Minus Sign'. This actually does look good until you realize that you don't have 'Minus Sign' on a swedish keyboard, you only have 'Hyphen-Minus'. Users of our applications can therefore never enter negative numbers in any application since this change.

This would not be a problem if .Net 5.0 or the ICU library on windows respected the '[parseLenient](https://unicode-org.atlassian.net/browse/CLDR-10779?jql=text%20~%20%22sv%20minus%20sign%22)' data array that is associated with this from CLDR, as this includes the 'Hyphen-Minus'. However a strict equality seems to be used instead and 'Hyphen-Minus' can no longer be used to describe a negative number. 

Can this be fixed in the .Net runtime, or is this an underlying issue with the ICU library on Windows?

Related issue: #44678
Related issue: #40922

### Configuration
Win10 May 2019 Update (build 18362) and later.
with .Net 5.0 or later

### Workaround
Force usage of NLS instead of ICU
`<ItemGroup>`
`    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />`
`</ItemGroup>`

**Comment by tarekgh** [comment]
@tedpar I'll take more deeper look and get back to you. Thanks for reporting the issue.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/40922

**Comment by tedpar** [comment]
> #40922

Thanks, yes, that issue you referenced mentions the same underlying problem, however that issue only deals with this by allowing overriding the default value of NumberFormat.NegativeSign. The proper fix would be to adhere to CLDR parseLenient data, which allows multiple characters to be used as negative sign when parsing from text to numbers.

**Comment by tarekgh** [comment]
@tedpar I linked the issue as it is related. I am not claiming it is the exact same issue. 

> The proper fix would be to adhere to CLDR parseLenient data,

That would be risky breaking change. Even ICU when parsing numbers making this as opt-in behavior to allow lenient parsing. But I think we can have some middle ground here which we can find out if the culture using any of the alternative minus sign we'll allow the hyphen U+002D for such locale. I believe this will address all concerns here.
