### ISSUE TITLE
Replace harvested package assets with live built configurations

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#47530]
The runtime repository currently produces 98 packages from libraries and 25 of those contain prebuilts (assets which are not built in the master/main branch anymore). Such prebuilt assets are redistributed into packages via a mechanism called “harvesting”. Without going into detail, the harvesting infrastructure downloads the latest available assets of the “current band” and places them into a specified subfolder inside the package.

In contrast to simplification of the build graph, harvesting has numerous downsides:
-	Increased cost of servicing as code fixes need to be applied in the repository’s branch in which the code lives, which is not necessarily the same place where the package is produced and shipped from.
-	Dependency between servicing releases, especially during MSRCs which forces schedules to be aligned.
-	Source link and newer compiler features (IL size reduction / optimization) are not applicable to harvested assets which causes NuGet Package Explorer to list the whole package as unhealthy.
-	Package validation costs
-	Fat packages
-	Harvesting build validation causes builds to fail in PRs every time new assets are shipped to indicate that harvesting defines should be updated.
-	Maintenance of code bases which are not tested anymore.

Based on these disadvantages, we would like to remove harvesting in dotnet/runtime entirely and only ship what is being built live.

## Implementation
For the following libraries, build configurations need to be added and/or harvesting configurations in the pkgproj need to be removed.

- [x] Microsoft.Extensions.DependencyModel: https://github.com/dotnet/runtime/pull/51582
- [x] Microsoft.Win32.Registry: https://github.com/dotnet/runtime/pull/51894
- [x] Microsoft.Win32.Registry.AccessControl: https://github.com/dotnet/runtime/pull/51689
- [x] System.ComponentModel.Annotations: https://github.com/dotnet/runtime/pull/51891
- [x] System.Composition.AttributedModel: https://github.com/dotnet/runtime/pull/51617
- [x] System.Composition.Convention: https://github.com/dotnet/runtime/pull/51617
- [x] System.Composition.Hosting: https://github.com/dotnet/runtime/pull/51617
- [x] System.Composition.Runtime: https://github.com/dotnet/runtime/pull/51617
- [x] System.Composition.TypedParts: https://github.com/dotnet/runtime/pull/51617
- [x] System.Drawing.Common: https://github.com/dotnet/runtime/pull/51934
- [x] System.IO.FileSystem.AccessControl: https://github.com/dotnet/runtime/pull/51689
- [x] System.IO.Pipelines: https://github.com/dotnet/runtime/pull/51689
- [x] System.IO.Pipes.AccessControl: https://github.com/dotnet/runtime/pull/52294
- [x] System.Net.Http.WinHttpHandler: https://github.com/dotnet/runtime/pull/51689
- [x] System.Reflection.Context: https://github.com/dotnet/runtime/pull/51689
- [x] System.Security.AccessControl: https://github.com/dotnet/runtime/pull/51894
- [x] System.Security.Cryptography.Cng: https://github.com/dotnet/runtime/pull/51853
- [x] System.Security.Cryptography.OpenSsl: https://github.com/dotnet/runtime/pull/51854
- [x] System.Security.Cryptography.Pkcs: https://github.com/dotnet/runtime/pull/52045
- [x] System.Security.Cryptography.ProtectedData: https://github.com/dotnet/runtime/pull/51872
- [x] System.Security.Principal.Windows: https://github.com/dotnet/runtime/pull/51894
- [x] System.ServiceProcess.ServiceController: https://github.com/dotnet/runtime/pull/51689
- [x] System.Text.Encoding.CodePages: https://github.com/dotnet/runtime/pull/51894
- [x] System.Text.Encodings.Web: https://github.com/dotnet/runtime/pull/51689
- [x] System.Threading.AccessControl: https://github.com/dotnet/runtime/pull/51689

**Add a build warning wherever functionality would regress.**

cc @danmosemsft @ericstj @terrajobst @tommcdon

**Comment by danmoseley** [comment]
Are there any updates to the plan (since this was opened) that we need to share here?

**Comment by ViktorHofer** [comment]
Only minor adjustments, two configurations which are dropped instead of brought back. I'm in regular sync with @terrajobst about this. The always up-to-date list is the Excel that I will share offline with you again.

**Comment by danmoseley** [comment]
@ViktorHofer I don't have concerns that I'm not up to date. I just wanted to make sure that community was up to date, presumably here or possibly in some linked design.

**Comment by ViktorHofer** [comment]
Replied offline.

**Comment by ViktorHofer** [comment]
Closing as the tracked work is completed.
