### ISSUE TITLE
aot methods in *.ni.dll

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#47537]
I have collected R2RDump of native R2R images for armel and x64 architectures, and we got couple of questons about that dumps.

1.  Armel R2R image for `System.Private.CoreLib.dll` contain a lot of `*X86*` intrinsic methods. For exmple:
```diff
-bool System.Runtime.Intrinsics.X86.Avx.TestC(System.Runtime.Intrinsics.Vector128`1<double>, System.Runtime.Intrinsics.Vector128`1<double>)
-bool System.Runtime.Intrinsics.X86.Avx.TestC(System.Runtime.Intrinsics.Vector128`1<float>, System.Runtime.Intrinsics.Vector128`1<float>)
-bool System.Runtime.Intrinsics.X86.Avx.TestC(System.Runtime.Intrinsics.Vector256`1<byte>, System.Runtime.Intrinsics.Vector256`1<byte>)
-bool System.Runtime.Intrinsics.X86.Avx.TestC(System.Runtime.Intrinsics.Vector256`1<double>, System.Runtime.Intrinsics.Vector256`1<double>)
```
In opposite x64 R2R image contain some `*Arm*` methods:
```diff
+uint System.Runtime.Intrinsics.Arm.Crc32.ComputeCrc32C(uint, byte)
+uint System.Runtime.Intrinsics.Arm.Crc32.ComputeCrc32C(uint, uint)
+uint System.Runtime.Intrinsics.Arm.Crc32.ComputeCrc32C(uint, ushort)
```
We assume that crosggen2 inlines native asm intrinsics into caller R2R code, and inserts calls to foreign architecture `*.Intrinsics.*` methods, so `System.Private.CoreLib.dll` R2R image should contain foreign architecture  `*.intrinsecs.*` methods. Is our assumption correct?
[System.Private.CoreLib.ni.dll.out.diff gist](https://gist.github.com/t-mustafin/effd4e6b509b5bd3d95712655743f1fb#file-system-private-corelib-ni-dll-out-diff)

2. Plenty of `*SpanHelpers*` methods presents in diff-files. For some cases we could guess, it represents different pointer size, for example in `System.Net.Sockets.ni.dll`:
```diff
--- armel/System.Net.Sockets.ni.dll.out 2021-01-25 22:39:41.637004000 +0300
+++ x64/System.Net.Sockets.ni.dll.out   2021-01-25 22:50:41.781004000 +0300
-int System.SpanHelpers.IndexOf<int>(ref int, int, int)
-int System.SpanHelpers.LastIndexOf<int>(ref int, int, int)
+int System.SpanHelpers.IndexOf<long>(ref long, long, int)
+int System.SpanHelpers.LastIndexOf<long>(ref long, long, int)
```
But some differences is not clear for us. For example `System.Private.CoreLib.ni.dll` for x64 has, but for armel does not have method:
```diff
+bool System.SpanHelpers.SequenceEqual(ref byte, ref byte, UIntPtr)
```
Is it a bug of crossgen2 for armel?

3. x64 R2R images contains more ``System.Collections.Concurrent.ConcurrentDictionary`2+Tables`` methods than armel, in `ILCompiler.ReadyToRun.ni.dll`:
```diff
+void System.Collections.Concurrent.ConcurrentDictionary`2+Tables<__Canon,bool>..ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node<!0,!1>[], object[], int[])
+void System.Collections.Concurrent.ConcurrentDictionary`2+Tables<__Canon,__Canon>..ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node<!0,!1>[], object[], int[])
+void System.Collections.Concurrent.ConcurrentDictionary`2+Tables<__Canon,ILCompiler.DependencyAnalysis.ReadyToRun.ModuleToken>..ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node<!0,!1>[], object[], int[])
+void System.Collections.Concurrent.ConcurrentDictionary`2+Tables<__Canon,ILCompiler.ReadyToRunCompilationModuleGroupBase+CompilationUnitSet>..ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node<!0,!1>[], object[], int[])
```
Should all that methods be precompiled by crossgen2 for armel too?
[ILCompiler.ReadyToRun.ni.dll.diff gist](https://gist.github.com/t-mustafin/effd4e6b509b5bd3d95712655743f1fb#file-ilcompiler-readytorun-ni-dll-out-diff)

Archive with diffs [aot_methods.tar.gz](https://github.com/dotnet/runtime/files/5882604/aot_methods.tar.gz)
cc @jkotas @alpencolt @gbalykov @y-yamshchikov

**Comment by jkotas** [comment]
> Armel R2R image for System.Private.CoreLib.dll contain a lot of *X86* intrinsic methods.

The intrinsic for other than the target architectures are ordinary methods from the compiler point of view. You assumption is correct.

>  System.SpanHelpers.SequenceEqual(ref byte, ref byte, UIntPtr)

If this method is missing, it means that it failed to compile. You should see an exception thrown during compilation of this method and go from there. You can use `-singlemethod...` command line switches to trigger compilation of just the method you are interested in.

cc @dotnet/crossgen-contrib

**Comment by alpencolt** [comment]
@jkotas what do think about constructors, e.g. ```System.Collections.Concurrent.ConcurrentDictionary`2+Tables<__Canon,bool>..ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node<!0,!1>[], object[], int[])```?
As I remember they were not be AOT compiled before.

**Comment by jkotas** [comment]
I do not know what may be causing the difference for constructors.

**Comment by t-mustafin** [comment]
@jkotas, thank you for response.

Method  `System.SpanHelpers.SequenceEqual(ref byte, ref byte, UIntPtr)` is become precompiled with #46069. Crossgen2 precompiled methods in SPC added by that pull request https://gist.github.com/t-mustafin/0720c0829328925095f29c29eaecff72.

**Comment by t-mustafin** [comment]
Aot for armel inlines functions `Tables:.ctor`:
```
[2 IL=0342 TR=000139 06000102] [profitable inline] Tables:.ctor(System.Collections.Concurrent.ConcurrentDictionary`2+Node[System.__Canon, ILCompiler.DependencyAnalysis.ReadyToRun.ModuleToken][],System.Object[],System.Int32[]):this
```
[ILCompiler.ReadyToRun.ngendump.zip](https://github.com/dotnet/runtime/files/5985213/ILCompiler.ReadyToRun.ngendump.zip)
