### ISSUE TITLE
SocketOptionName.ReuseUnicastPort seems to be useless

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#47531]
`SocketOptionName.ReuseUnicastPort` maps to `SO_REUSE_UNICASTPORT` on Windows to enable ephemeral port reuse for outbound connections. 

From [winsock documentation](https://docs.microsoft.com/en-us/windows/win32/winsock/sol-socket-socket-options):

> When set, allow ephemeral port reuse for Winsock API connection functions which require an explicit bind, such as ConnectEx. Note that connection functions with an implicit bind (such as connect without an explicit bind) have this option set by default.

If my understanding is correct, this would enable port reuse when using `ConnectEx` without an explicit bind. The problem is that we always do an explicit bind in asynchronous connect code (the one that uses ConnectEx), regardless of the option value

https://github.com/dotnet/runtime/blob/e9695b8e7840c37390ca58b821cfbeab178d1cc6/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3114

, which renders the option useless if I'm not mistaken.

**Comment by davidni** [comment]
This issue imposes significant scalability constraints on applications such as [YARP](https://github.com/microsoft/reverse-proxy) connecting to thousands of destinations at a time.

We observed that a .NET Core 3.1 process was unable to exceed 16k TCPv4 connections (which matches the number of ephemeral ports we had configured). From that point onwards, new connection attempts fail with [WSAENOBUFS (10055)](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)

Fixing this E2E may require changes on `SocketsHttpHandler` to also benefit from the improvements discussed on this issue.

**Comment by antonfirsov** [comment]
> Fixing this E2E may require changes on SocketsHttpHandler to also benefit from the improvements discussed on this issue.

With .NET 5, you can use [ConnectCallback](https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#socketshttphandler-extension-points) to configure the sockets used to establish the connection, so fixing `Socket.ConnectAsync` should be sufficient to overcome the `SocketsHttpHandler` scalability issues.

Such a fix could be trivial IMO, with enough justification it could be even considered to be backported into a .NET 5 patch release.

**Comment by geoffkizer** [comment]
> The problem is that we always do an explicit bind in asynchronous connect code (the one that uses ConnectEx), regardless of the option value ... which renders the option useless if I'm not mistaken.

I'm confused... I thought the point of this options was that it *enables* the port reuse for cases like ours, where we are using ConnectEx and doing an explicit bind. Am I misunderstanding you?

**Comment by antonfirsov** [comment]
Ok maybe I'm misunderstanding this. I thought this works as following:

1. `ConnectEx` requires an explicit bind normally, and won't work without it
2. Enabling `SO_REUSE_UNICASTPORT` somehow lifts this limitation, so calling `ConnectEx` with an unbound socket will implicitly bind it to a port in the reuse range
3. Doing an explicit bind before `ConnectEx` is sabotaging this, so the socket binds to a normal ephemeral port without reuse in the end

Do I get any of the above points wrong?

**Comment by geoffkizer** [comment]
My understanding is that SO_REUSE_UNICASTPORT doesn't actually lift the limitation that ConnectEx requires an explicit bind. It just changes it so that when you do an explicit bind to port 0, you will now get port reuse -- and the port won't actually be assigned until ConnectEx is called. I could be wrong though.

**Comment by antonfirsov** [comment]
Ok, closing this since it's most likely a misunderstanding on my side.
