### ISSUE TITLE
The "CreateAppHost" task failed unexpectedly.

### ISSUE THREAD

**Issue by sdudnic** [dotnet/runtime#47548]
I have built a web project in VS 2019, worked a lot witout problems on that (Asp.Net Core 5.0) Web App and suddenly it started to appear an error on that Web Project:

Error	MSB4018	

> The "CreateAppHost" task failed unexpectedly.
> Microsoft.NET.HostModel.HResultException: 800703EE
>    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__UpdateResources|1()
>    at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func)
>    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom)
>    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
>    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyApp.Web	C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	460	
> 

Following configuration

> Microsoft Visual Studio Enterprise 2019
> Version 16.8.4
> VisualStudio.16.Release/16.8.4+30907.101
> Microsoft .NET Framework
> Version 4.8.03752
> 
> Installed Version: Enterprise
> 
> Visual C++ 2019   00435-60000-00000-AA366
> Microsoft Visual C++ 2019
> 
> ASP.NET and Web Tools 2019   16.8.557.25636
> ASP.NET and Web Tools 2019
> 
> ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   16.8.557.25636
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools   16.8.557.25636
> Azure Functions and Web Jobs Tools
> 
> C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> IntelliCode Extension   1.0
> IntelliCode Visual Studio Extension Detailed Info
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1
> 
> Microsoft Continuous Delivery Tools for Visual Studio   0.4
> Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager   2.1.113+g422d40002e.RR
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio Tools for Containers   1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> NuGet Package Manager   5.8.1
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> Office Developer Tools for Visual Studio   16.0.30502.00
> Microsoft Office Developer Tools for Visual Studio
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Snapshot Debugging Extension   1.0
> Snapshot Debugging Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   16.0.62012.31170
> Microsoft SQL Server Data Tools
> 
> SQL Server Reporting Services   15.0.19124.0
> Microsoft SQL Server Reporting Services Designers 
> Version 15.0.19124.0
> 
> TypeScript Tools   16.0.21016.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
> Microsoft Visual F# Tools
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Container Tools Extensions   1.0
> View, manage, and diagnose containers within Visual Studio.
> 
> Visual Studio Tools for Containers   1.0
> Visual Studio Tools for Containers
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.

It prevents the solution to build. I restarted VS under admin, didn't help.

**Comment by sdudnic** [comment]
the issue disappeared as it appeared, unexpectedly, but after few hours, rebuilds, computer restarts, ".vs" folder removal, even Visual Studio repairing and reinstalling, and I am even no sure if it would not disappear without so much efforts and nerves...

**Comment by danmosemsft** [comment]
ERROR_FILE_INVALID. I wonder whether https://github.com/dotnet/runtime/pull/32347 is relevant, and if so, was present

**Comment by vitek-karas** [comment]
This could be possibly some other process holding onto the file in question. We've seen some anti-viruses do really weird things. That's why the retries were added, but apparently it doesn't work always. If you happen to hit it again:
* What anti-virus do you use? Is it enabled on the folder with the application you're building?
* Try to delete `bin` and `obj` folders of the application you're building - and rebuild.

**Comment by sdudnic** [comment]
The Eset antivirus detected in the

myapp\obj\debug\.net5.0\apphost.exe 

a "danger" and blocked it for an unknown reason. The compilation was impossible.
