### ISSUE TITLE
superpmi: add dotnet/performance benchmark collection

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#47544]
Add an automated AzDO SuperPMi collection of the dotnet/performance benchmarks (a "run" collection, not just a PMI or crossgen collection).

This would be useful when investigating JIT changes to see how they affect the benchmarks.

category:eng-sys
theme:super-pmi
skill-level:beginner
cost:small

**Comment by BruceForstall** [comment]
fyi @kunalspathak @AndyAyersMS

**Comment by kunalspathak** [comment]
This is on my list. As discussed with @BruceForstall  offline, we need to think how we can make `superpmi collect` command take a script that contains `dotnet` CLI. As per `superpmi.py collect -h`, it says:

```
  collection_command    Command to run SuperPMI collect over. Note that there cannot be any dotnet CLI commands invoked inside this command, as they will fail due to
                        the shim JIT being set.
```

So we need to defer the setting of `COMPlus_` variables until we run the actual benchmark code.

The command to run all the benchmarks once during collection would be:

```
dotnet artifacts\MicroBenchmarks.dll --iterationCount 1 --warmupCount 0 --invocationCount 1 --unrollFactor 1 --strategy ColdStart
```

**Comment by BruceForstall** [comment]
> we need to think how we can make superpmi collect command take a script that contains dotnet CLI

I think the main issue is that when we set the `COMPlus_JitName` variable to the collection shim, then any runtime that recognizes that variable will try to load the specified shim in the same directory as its clr/coreclr.dll. This also includes some .NET Framework runtimes, or .NET Core runtimes in various directories where we haven't placed the shim. Also, the shim is bound to the particular JIT-EE GUID, so even if found, not all CLR apps can load/run it.

Possibly we should introduce a new variable that only is read by .NET 6+. And, introduce a mechanism to be more resilient to load failures, and more targeted about which runtime instances should load it.

**Comment by kunalspathak** [comment]
Fixed by https://github.com/dotnet/runtime/pull/47900
