### ISSUE TITLE
superpmi: add coreclr test run collection

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#47543]
We currently collect crossgen2/PMI of tests in AzDO superpmi collection automation. We should also collect run of coreclr tests.

category:eng-sys
theme:super-pmi
skill-level:beginner
cost:small
impact:large

**Comment by BruceForstall** [comment]
"run" collection of coreclr tests is done.

Remaining work is "run" collection of libraries tests.

**Comment by BruceForstall** [comment]
Converted this to an issue for coreclr tests only. Track libraries tests with https://github.com/dotnet/runtime/issues/79017

**Comment by JulieLeeMSFT** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74961.
