### ISSUE TITLE
crossgen2 crashes open a pop-up window

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#47552]
When crossgen2 crashes, I see a pop-up window:

```
Title: .NET Host
Text:
.NET Host has stopped working

A problem cause the program to stop working correctly.
Windows will close the program and notify you if a solution is
available.
Buttons: Debug, Close program
```

This unfortunately requires user input and stops further progress in scripted runs.

I would expect the default failure behavior would be to NOT use a pop-up window, but instead output a message and return an error code.

Repro:

I'm trying to SuperPMI collect a crossgen2 compilation of all libraries in Core_Root (win x64 Checked):
```
py c:\gh\runtime2\src\coreclr\scripts\superpmi.py collect --crossgen2 -output_mch_path c:\win-x64-cg2.mch -assemblies c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root
```

A small repro:
```
c:\gh\runtime2\.dotnet\dotnet.exe c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\crossgen2\crossgen2.dll  --codegenopt:EnableExtraSuperPmiQueries=1 @c:\bugs\spmicollect4\x.rsp
```
x.rsp:
```
c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\R2RDump\ILCompiler.Reflection.ReadyToRun.dll
-o:c:\bugs\spmicollect4\cg2-temp\crossgen2_c__gh_runtime2_artifacts_tests_coreclr_windows_x64_Checked_Tests_Core_Root_R2RDump_ILCompiler_Reflection_ReadyToRun_dll.out.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\System.*.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\Microsoft.*.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\mscorlib.dll
-r:c:\gh\runtime2\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\netstandard.dll
```

The crash seems to be due to the `--codegenopt:EnableExtraSuperPmiQueries=1` option.

**Comment by BruceForstall** [comment]
@dotnet/crossgen-contrib

**Comment by BruceForstall** [comment]
I opened an issue for the cause of the crash: https://github.com/dotnet/runtime/issues/47554

**Comment by MichalStrehovsky** [comment]
Isn't that the Windows Error Reporting dialog box? If I'm reading crossgen1 sources right, it was just swallowing all exceptions so it would never go unhandled into WER. I wonder how we got any Watson telemetry for crashes in the wild with that setup.

Machines that run automation typically have

```
REGEDIT4

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting]
"DontShowUI"="1"
```

In their registry to stop these popups.

**Comment by BruceForstall** [comment]
I don't want to (and in many cases probably can't) touch the registry on machines where this is running. Could we add a command-line switch that would swallow all exceptions and return error codes instead?

**Comment by trylek** [comment]
Hmm, can you please help me understand what is the expected follow-up here other than generally getting rid of Crossgen2 crashes? We probably don't want to block out WER, from what I recall machines used for unattended test runs have always been using <code>DontShowUI=1</code> as Michal mentions as test executions can also easily crash with WER fatal error dialogs for multiple reasons.

**Comment by BruceForstall** [comment]
My expectation is that under no circumstances should crossgen2 throw up a dialog box (that will block automated processing). This was true for crossgen1. This could _potentially_ be under some kind of environment variable switch, but setting the registry is not acceptable.

**Comment by davidwrighton** [comment]
@BruceForstall have you seen more cases where this is a problem? Its been several years, and while it might be worthwhile to think about fixing this sort of issue, I'd rather not lose the watson behavior on customer machines, which is arguably more important than testing in our local environment (especially if we've lived well enough for the last 2 years)

**Comment by BruceForstall** [comment]
> @BruceForstall have you seen more cases where this is a problem? Its been several years, and while it might be worthwhile to think about fixing this sort of issue, I'd rather not lose the watson behavior on customer machines, which is arguably more important than testing in our local environment (especially if we've lived well enough for the last 2 years)

I can't recall seeing any problems here recently, so maybe we can close this?

**Comment by BruceForstall** [comment]
It's possible this is impacting our superpmi crossgen2 collections recently: https://github.com/dotnet/runtime/issues/88423

**Comment by MichalStrehovsky** [comment]
> It's possible this is impacting our superpmi crossgen2 collections recently: #88423

It's not the WER dialog that was in the top issue. This is the debug assertion failed dialog.

It can be disabled with _CrtSetReportMode. Given everything is using UCRT, I think you could call this API in superpmi-shim-collector initialization and disable this process wide.
