### ISSUE TITLE
Add strict validation to System.IO.Compression.GZipStream

### ISSUE THREAD

**Issue by mfkl** [dotnet/runtime#47563]
## EDIT: 

This turned out to be handled as a bug rather than an API proposal, see https://github.com/dotnet/runtime/issues/47563#issuecomment-966078285 for details.

# Original description:

## Background and Motivation

The `System.IO.Compression.GZipStream` implemention over zlib does not currently do strict native error reporting. 

See https://stackoverflow.com/questions/9456563/gzipstream-doesnt-detect-corrupt-data-even-crc32-passes for more info.

Other zlib managed implementation or bindings over the native API do report issues on corrupt data.

## Proposed API

Add a new `GZipStream` contructor overload.

```diff
namespace System.IO.Compression.cs
{
+            public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen, bool strictValidation) { }
}
```

## Usage Examples

``` C#
new GZipStream(decomStream, CompressionMode.Decompress, false, strictValidation: true)
```

https://github.com/dotnet/runtime/pull/47560

## Alternative Designs

There may better ways to expose this optional behavior. Ideas are welcome.

## Risks

Since this is explicitly opt-in, and that the current behavior is not changed, I don't expect any breaking changes or behavior with existing code calling into this API.

**Comment by adamsitnik** [comment]
Triage: we like this idea, but we should most probably add `ctor` for the other enum too

```diff
    public partial class GZipStream : System.IO.Stream
    {
        public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, bool leaveOpen)
+       public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, bool leaveOpen, bool strictValidation)
        public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen)
+       public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen, bool strictValidation)
```

and verify if other compression methods allow for such validation and extend them as well

**Comment by adamsitnik** [comment]
@mfkl is there any chance that you could research if other compression methods allow for such validation? In such a case, we should add overloads to other ctors too. Once we get there, we are going to mark the issue as ready for review, go through API Design Review, get the API accepted (with possible modifications of the proposal), and then re-open your PR.

**Comment by Wraith2** [comment]
Failing to report errors in the data and producing incorrect output seems more like a bug to be fixed then a new feature request. Shouldn't the default be to produce correct data?

**Comment by mfkl** [comment]
> is there any chance that you could research if other compression methods allow for such validation?

I can have a look.

> Shouldn't the default be to produce correct data?

I considered this, but since I don't know the impact on existing users I decided to go the API route. Happy to revisit.

Another thing to consider from the comment on this line
https://github.com/dotnet/runtime/blob/42bc286e441f250843cd9edb67e25129436f13a5/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Deflater.cs#L250-L251

Is throwing on _all_ buffer errors the correct behavior? I'd think so.

**Comment by mfkl** [comment]
I've tried enabling strict validation by default (e.g. throwing on all BufErrors) to check for potential regressions in tests, and it fails half the 600+ compression test suite. 

Additionally, [the docs](https://zlib.net/manual.html) makes me think that _maybe_ throwing on every BufErrors may not be the correct approach:

> inflate() returns Z_OK if some progress has been made (more input processed or more output produced), Z_STREAM_END if the end of the compressed data has been reached and all uncompressed output has been produced, Z_NEED_DICT if a preset dictionary is needed at this point, Z_DATA_ERROR if the input data was corrupted (input stream not conforming to the zlib format or incorrect check value, in which case strm->msg points to a string with a more specific error), Z_STREAM_ERROR if the stream structure was inconsistent (for example next_in or next_out was Z_NULL, or the state was inadvertently written over by the application), Z_MEM_ERROR if there was not enough memory, Z_BUF_ERROR if no progress was possible or if there was not enough room in the output buffer when Z_FINISH is used. Note that Z_BUF_ERROR is not fatal, and inflate() can be called again with more input and more output space to continue decompressing

> deflate() returns Z_OK if some progress has been made (more input processed or more output produced), Z_STREAM_END if all input has been consumed and all output has been produced (only when flush is set to Z_FINISH), Z_STREAM_ERROR if the stream state was inconsistent (for example if next_in or next_out was Z_NULL or the state was inadvertently written over by the application), or Z_BUF_ERROR if no progress is possible (for example avail_in or avail_out was zero). Note that Z_BUF_ERROR is not fatal, and deflate() can be called again with more input and more output space to continue compressing. 

As for other compression methods, I had a look at Brotli which has a similar enum value for corrupted data
```
/** Decoding error, e.g. corrupted input or memory allocation problem. */
  BROTLI_DECODER_RESULT_ERROR = 0,
```

which is correctly handled on the C# side currently (similarly to what I had done for zlib):
```
int brotliResult = Interop.Brotli.BrotliDecoderDecompressStream(_state, ref availableInput, &inBytes, ref availableOutput, &outBytes, out _);
if (brotliResult == 0) // Error
{
     return OperationStatus.InvalidData;
}
```

**Comment by danmosemsft** [comment]
Presumably the goal is to flag inputs that will decompress incorrectly and not flag those that will decompress correctly in all major decompression tools. So at a minimum zero of the test bed should fail the checks because we know they decompress correctly. (Unless we can find another tools that cannot.)

**Comment by mfkl** [comment]
> So at a minimum zero of the test bed should fail the checks because we know they decompress correctly. 

I agree. The test is only failing because I throw on every buf error, which is likely wrong. 

But my point is that if you check for the buf error result with no other code change (like this https://github.com/mfkl/runtime/commit/b2e4595eaf8453c2652868a72a6b319ebd678901), it seems that it is returned in half of the current tests (even if decompression is done correctly).

**Comment by mfkl** [comment]
I'm still looking into when (and when not) to throw, as buf errors should really be ignored in some cases.

Relevant https://github.com/nodejs/node/commit/0fc0902c21c9c9ed180e575f34b9b39366d57685#diff-55807528c167d8a7fc7f345ce23dc5c5e4d4e2635caaf21b90f6153044b4aa39

**Comment by mfkl** [comment]
So, going the `BufError` route to implement this stricter validation was a mistake. From my investigations, it is impossible to rely on `BufError` to implement any kind of correct stricter validation logic (though this error is returned every time in my specific test case, and at least once in half of the existing test suite).

I've been looking at how `ICSharpCode` manages to find the discrepancies in the stream with my test case and the stack traces look like:

```
ICSharpCode throws because EOF in header

   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputBuffer.ReadLeByte()
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.ReadHeader()
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination) 

   and Unexpected EOF

   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Fill()
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)

   and then message	"EOS reading GZIP footer"

   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.ReadFooter()
   at ICSharpCode.SharpZipLib.GZip.GZipInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
```

The code that throws most often is coming from this check

```
protected void Fill()
{
    // Protect against redundant calls
    if (inputBuffer.Available <= 0)
    {
        inputBuffer.Fill();
        if (inputBuffer.Available <= 0)
        {
            throw new SharpZipBaseException("Unexpected EOF");
        }
    }
    inputBuffer.SetInflaterInput(inf);
}
```

My best guess is the System.IO.Compression.GZipStream binding needs something similar.

**Comment by mfkl** [comment]
```diff
public void CopyFromSourceToDestination()
{
    try
    {
        Debug.Assert(_deflateStream._inflater != null);
        // Flush any existing data in the inflater to the destination stream.
        while (!_deflateStream._inflater.Finished())
        {
            int bytesRead = _deflateStream._inflater.Inflate(_arrayPoolBuffer, 0, _arrayPoolBuffer.Length);
            if (bytesRead > 0)
            {
                _destination.Write(_arrayPoolBuffer, 0, bytesRead);
            }
            else if (_deflateStream._inflater.NeedsInput() && bytesRead == 0)
            {
+                if (_destination is MemoryStream ms && ms.Capacity == 0)
+                {
+                   throw new Exception();
+                }
                // only break if we read 0 and ran out of input, if input is still available it may be another GZip payload
                break;
            }
        }

        // Now, use the source stream's CopyToAsync to push directly to our inflater via this helper stream
        _deflateStream._stream.CopyTo(this, _arrayPoolBuffer.Length);
    }
    finally
    {
        ArrayPool<byte>.Shared.Return(_arrayPoolBuffer);
        _arrayPoolBuffer = null!;
    }
}
```

Attempting to replicate similar SharpZipLib's behavior with this code. Only fails 5% of the test suite now.

Currently failing tests are (working on it):
`CopyToAsync_AllDataCopied`
`ConcatenatedEmptyGzipStreams`
`ManyConcatenatedGzipStreams`
Some in `zip_InvalidParametersAndStrangeFiles`

Anyone has an opinion on this approach?

**Comment by mfkl** [comment]
> Shouldn't the default be to produce correct data?

After more investigation, I can add more context and info to answer your question @Wraith2

So, yes, in theory the default behavior should be to produce correct data and be strict about it, however I identified some situations in which it is sadly not possible to make the difference between "weird or rare but valid data" and "corrupted data". Zlib does not help much in that regard if the CRC is not hit.

This is an example:
https://github.com/dotnet/corefx/pull/41190 
https://github.com/dotnet/runtime/issues/30731

The same code path is hit in concatenated streams (valid) and with corrupted streams (not valid) in CopyStream, and we want to give the users the choice to configure the behavior, I think. 
My change above https://github.com/dotnet/runtime/issues/47563#issuecomment-806471431 helps with reducing the number of failing tests, but I couldn't find a way to satisfy them all while retaining the "throw on invalid data" improvement. I don't think that's possible with zlib currently.

You can find my rebased, up to date changes here https://github.com/dotnet/runtime/compare/main...mfkl:gzip-validation7

**Comment by mfkl** [comment]
ping

**Comment by mfkl** [comment]
Turns out using the `BufError` approach was probably not a good idea, it is tricky to get error handling right with it, as the native lib returns it for both informational and critical cases.

So with the help of @marcin-krystianc, we found another approach, which does not break any existing test, requires no API changes _and_ still fixes the issue.

Test: https://github.com/mfkl/runtime/commit/9dcff066b99c6b9d4a43e200eba3241ea241274c
Fix: https://github.com/mfkl/runtime/commit/abe6408cb59608d474e01d09796358f36bb4ba3a

What do you think? /cc @adamsitnik

**Comment by danmoseley** [comment]
cc @carlossanlop

**Comment by Jozkee** [comment]
Fixed by https://github.com/dotnet/runtime/issues/47563.

**Comment by mfkl** [comment]
So, some context here.

This issue has been acknowledged. Initially, the solution was proposed as an API proposal (see first comment of this issue), but after some discussion, we decided to enable the strict validation checks by default. This work was merged in the main branch with https://github.com/dotnet/runtime/pull/61768.

In .NET 7 preview builds, we realized in https://github.com/dotnet/runtime/issues/72726, that though technically correct, these checks are a little too strict for many real-world usage scenarios. The changes were reverted in https://github.com/dotnet/runtime/pull/72742.

Which brings us back here, to the API proposal.

# Original description:

## Background and Motivation

The `System.IO.Compression.GZipStream` implemention over zlib lacks strict decompression checks. 

Other zlib managed implementation or bindings over the native API do report issues on corrupt data during decompression. Having the feature as an opt-in is the best option.

## Proposed API

Add a new `GZipStream` contructor overload.

```diff
namespace System.IO.Compression.cs
{
+       public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, bool leaveOpen, bool strictValidation)
+       public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen, bool strictValidation)
}
```

## Usage Examples

``` C#
new GZipStream(decomStream, CompressionMode.Decompress, false, strictValidation: true)
```

## Alternative Designs

Stricter checks as a default behavior is not a viable option, as we have tried and seen already.

## Risks

Since this is explicitly opt-in, and that the current behavior is not changed, I don't expect any breaking changes or behavior with existing code calling into this API. 
It would be a good idea to document the fact that it may break real-world, seemingly fine scenarios in which streams may be technically invalid (e.g. stream isn't closed, server doesn't send finishing sequence).

/cc @Jozkee

**Comment by stephentoub** [comment]
> public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionMode mode, bool leaveOpen, bool strictValidation)

Does it need to be specified at construction, or is is possible to query a property after reading to eof to see whether it had the correct footer?

> public GZipStream(System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, bool leaveOpen, bool strictValidation)

Isn't the proposed validation only about decompression? This ctor is only for compression.

**Comment by mfkl** [comment]
> Does it need to be specified at construction, or is is possible to query a property after reading to eof to see whether it had the correct footer?

I guess enabling strict checks does not have to decided only at construction time indeed. Did you have something like this in mind?

```diff
namespace System.IO.Compression
{
    public partial class DeflateStream : System.IO.Stream
    {
+       public bool HasValidFooter { get; }
    }
    public partial class GZipStream : System.IO.Stream
    {
+       public bool HasValidFooter { get; }
    }
}
```

Though the throw behavior more closely matches other libs (like SharpZibLib). Maybe

```diff
namespace System.IO.Compression
{
    public partial class DeflateStream : System.IO.Stream
    {
+       public bool ThrowOnInvalidFooter { get; }
    }
    public partial class GZipStream : System.IO.Stream
    {
+       public bool ThrowOnInvalidFooter { get; }
    }
}
```

This would be specific to `BrotliStream` and `GZipStream`.

> Isn't the proposed validation only about decompression? This ctor is only for compression.

Indeed, I edited my comment.

**Comment by marcin-krystianc** [comment]
Another option to consider is to make this an opt-out feature and use [AppContext](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext) to allow users to opt out from strict validation. AppContext makes it easy to opt-out of the strict behaviour for the entire application with a single `AppContext.SetSwitch ("....DisableStrictValidation", true)` call. The main benefit would be that all users get stricter behaviour automatically (which in my opinion it is very desired) but in cases when it is necessary we provide an easy way to opt out.

**Comment by stephentoub** [comment]
> Another option to consider is to make this an opt-out feature and use [AppContext](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext) to allow users to opt out from strict validation.

We already know this breaks real-world use. I do not see the ROI for making such a change.

**Comment by marcin-krystianc** [comment]
> > Another option to consider is to make this an opt-out feature and use [AppContext](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext) to allow users to opt out from strict validation.
> 
> We already know this breaks real-world use. I do not see the ROI for making such a change.

In our company we had issues with truncated data streams, especially with large files on network shares. Because of that we need to use other libraries that do strict validation. None of the alternatives are as fast as System.IO.compression so we would prefer using it if it supported strict validation.  The opt-in is good enough for us, but my personal opinion  is that opt-out is even better.

**Comment by mfkl** [comment]
> The opt-in is good enough for us, but my personal opinion is that opt-out is even better.

If it breaks too many people for apps that are currently working fine, I agree with @stephentoub that an opt-out is not worth doing.

Using `AppContext.SetSwitch` for this as an opt-in is not something I had considered though, and it could be a good fit. It'd allow both
- keeping the public APIs unchanged for these 2 Stream subtypes,
- and allowing to switch the feature on/off without needing to create a new instance (unlike the additional constructor parameter initially suggested).

**Comment by mfkl** [comment]
Does anyone have an opinion regarding the 3 API proposals suggested above?

**Comment by Jozkee** [comment]
IMO the AppContext switch + Environment Variable combo is a good fit for enabling strict validation. Here's an example of how we use it in `Console`:
https://github.com/dotnet/runtime/blob/2ed931d06a662eb416e363f2dde798729eae4c25/src/libraries/Common/src/System/Console/ConsoleUtils.cs#L68-L77

**Comment by mfkl** [comment]
Does anyone has any objections or can I start working on that implementation?

**Comment by Jozkee** [comment]
@mfkl I think you can start working on a PR.
