### ISSUE TITLE
 Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket' from System.Net.Sockets.Tests.ReceiveFrom*.ClosedDuringOperation_Throws_ObjectDisposedExceptionOrSocketException

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#47561]
net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open
https://dev.azure.com/dnceng/public/_build/results?buildId=969030&view=ms.vss-test-web.build-test-results-tab&runId=30459202&paneView=debug

System.Net.Sockets.Tests.ReceiveFrom_SyncForceNonBlocking.ClosedDuringOperation_Throws_ObjectDisposedExceptionOrSocketException(closeOrDispose: True)
```
{ "HelixJobId": "3ea51fa5-fda3-4c43-8a92-d69d605fd83e", "HelixWorkItemName": "System.Net.Sockets.Tests" }


Error message
Assert.Throws() Failure\r\nExpected: typeof(System.Net.Sockets.SocketException)\r\nActual:   typeof(System.ObjectDisposedException): Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'.\r\n---- System.ObjectDisposedException : Cannot access a disposed object.\r\nObject name: 'System.Net.Sockets.Socket'.


Stack trace
   at System.Net.Sockets.Socket.ThrowObjectDisposedException() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4158
   at System.Net.Sockets.Socket.ThrowIfDisposed() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4153
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 1610
   at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass7_0.<ReceiveFromAsync>b__0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs:line 69
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 303
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2363
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.ThrowObjectDisposedException() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4158
   at System.Net.Sockets.Socket.ThrowIfDisposed() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4153
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 1610
   at System.Net.Sockets.Tests.SocketHelperArraySync.<>c__DisplayClass7_0.<ReceiveFromAsync>b__0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SocketTestHelper.cs:line 69
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 303
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2363
--- End of stack trace from previous location ---
```

Runfo Tracking Issue: [system.net.sockets.tests.receivemessagefrom* throwing ObjectDisposedExceptions](https://runfo.azurewebsites.net/tracking/issue/128)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[969479](https://dev.azure.com/dnceng/public/_build/results?buildId=969479)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open|
|[969470](https://dev.azure.com/dnceng/public/_build/results?buildId=969470)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47572](https://github.com/dotnet/runtime/pull/47572)|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open|
|[969470](https://dev.azure.com/dnceng/public/_build/results?buildId=969470)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47572](https://github.com/dotnet/runtime/pull/47572)|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open|
|[969431](https://dev.azure.com/dnceng/public/_build/results?buildId=969431)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47167](https://github.com/dotnet/runtime/pull/47167)|net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504|
|[969431](https://dev.azure.com/dnceng/public/_build/results?buildId=969431)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47167](https://github.com/dotnet/runtime/pull/47167)|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open|
|[969431](https://dev.azure.com/dnceng/public/_build/results?buildId=969431)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47167](https://github.com/dotnet/runtime/pull/47167)|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open|
|[969404](https://dev.azure.com/dnceng/public/_build/results?buildId=969404)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open|
|[969404](https://dev.azure.com/dnceng/public/_build/results?buildId=969404)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open|
|[969357](https://dev.azure.com/dnceng/public/_build/results?buildId=969357)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 46602](https://github.com/dotnet/runtime/pull/46602)|net6.0-Linux-Debug-x64-Mono_release-RedHat.7.Amd64.Open|
|[969288](https://dev.azure.com/dnceng/public/_build/results?buildId=969288)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open|
|[969288](https://dev.azure.com/dnceng/public/_build/results?buildId=969288)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open|
|[969288](https://dev.azure.com/dnceng/public/_build/results?buildId=969288)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open|
|[969213](https://dev.azure.com/dnceng/public/_build/results?buildId=969213)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47511](https://github.com/dotnet/runtime/pull/47511)|net6.0-Linux-Debug-x64-Mono_release-(Debian.10.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-bfcd90a-20200121150006|
|[969213](https://dev.azure.com/dnceng/public/_build/results?buildId=969213)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47511](https://github.com/dotnet/runtime/pull/47511)|net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504|
|[969211](https://dev.azure.com/dnceng/public/_build/results?buildId=969211)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_release-Debian.9.Amd64.Open|
|[969211](https://dev.azure.com/dnceng/public/_build/results?buildId=969211)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open|
|[969154](https://dev.azure.com/dnceng/public/_build/results?buildId=969154)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47560](https://github.com/dotnet/runtime/pull/47560)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7|
|[969030](https://dev.azure.com/dnceng/public/_build/results?buildId=969030)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47511](https://github.com/dotnet/runtime/pull/47511)|net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open|
|[968977](https://dev.azure.com/dnceng/public/_build/results?buildId=968977)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47539](https://github.com/dotnet/runtime/pull/47539)|net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504|
|[968801](https://dev.azure.com/dnceng/public/_build/results?buildId=968801)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47316](https://github.com/dotnet/runtime/pull/47316)|net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504|
|[968785](https://dev.azure.com/dnceng/public/_build/results?buildId=968785)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45479](https://github.com/dotnet/runtime/pull/45479)|net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open|
|[968785](https://dev.azure.com/dnceng/public/_build/results?buildId=968785)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45479](https://github.com/dotnet/runtime/pull/45479)|net6.0-windows-Debug-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open|
|[968785](https://dev.azure.com/dnceng/public/_build/results?buildId=968785)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 45479](https://github.com/dotnet/runtime/pull/45479)|net6.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open|
|[968596](https://dev.azure.com/dnceng/public/_build/results?buildId=968596)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47526](https://github.com/dotnet/runtime/pull/47526)|net6.0-Linux-Debug-x64-CoreCLR_release-(Debian.10.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-bfcd90a-20200121150006|
|[968596](https://dev.azure.com/dnceng/public/_build/results?buildId=968596)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47526](https://github.com/dotnet/runtime/pull/47526)|net6.0-Linux-Debug-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open|
|[968596](https://dev.azure.com/dnceng/public/_build/results?buildId=968596)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47526](https://github.com/dotnet/runtime/pull/47526)|net6.0-windows-Debug-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504|
|[968555](https://dev.azure.com/dnceng/public/_build/results?buildId=968555)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47539](https://github.com/dotnet/runtime/pull/47539)|net6.0-windows-Debug-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open|
|[968083](https://dev.azure.com/dnceng/public/_build/results?buildId=968083)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47174](https://github.com/dotnet/runtime/pull/47174)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-30-helix-20200512010621-4f8cef7|
|[968073](https://dev.azure.com/dnceng/public/_build/results?buildId=968073)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47459](https://github.com/dotnet/runtime/pull/47459)|net6.0-Linux-Debug-x64-CoreCLR_release-RedHat.7.Amd64.Open|
|[968029](https://dev.azure.com/dnceng/public/_build/results?buildId=968029)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 47521](https://github.com/dotnet/runtime/pull/47521)|net6.0-Linux-Debug-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200602002622-e06dc59|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|11|18|

**Comment by hoyosjs** [comment]
Looks like these tests were added with #47229, going to disable failing tests to unblock CI.

**Comment by karelz** [comment]
@antonfirsov can you please confirm if it is test regression introduced by your PR?

**Comment by hoyosjs** [comment]
Somehow the tests seem not to have run in said PR, so I am confused as to what happened...

**Comment by antonfirsov** [comment]
Yes, this is either a test bug introduced by my PR, or a product bug (exception type depends on timing factors).

**Comment by antonfirsov** [comment]
The latter case would explain missing it in my original PR despite of several runs.
Looking into it.

**Comment by hoyosjs** [comment]
@antonfirsov It's weird, for example [testResults.xml](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47229-merge-309958e4171a44ac8a/System.Net.Sockets.Tests/testResults.xml?sv=2019-07-07&se=2021-02-16T11%3A49%3A34Z&sr=c&sp=rl&sig=j7f0LqMHNs5eHQgYFNryMMFc9BLOb1wvD%2B8foW7TbG0%3D) for your PR's debian x64 leg doesn't show the tests being run

**Comment by antonfirsov** [comment]
@hoyosjs that particular xml seems to belong to an outerloop run. Here's an innerloop log from OSX where the test passed:
https://helix.dot.net/api/jobs/e73e2d4a-3040-442a-a551-ce9db1803b44/workitems/System.Net.WebSockets.Tests?api-version=2019-06-17

**Comment by danmosemsft** [comment]
@jaredpar how did runfo know to attach to this bug - magic? or someone manually connects it ?

**Comment by hoyosjs** [comment]
I made it a tracking issue after investigating some elevated failures.
