### ISSUE TITLE
Self contained publish on Linux contains .a static libraries

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#47564]
I find the following `.a` static libraries are included in the publish folder of a self-contained application on Linux.
I searched in dotnet/runtime issues and found #3447 which was fixed by #41966, and accoring to the conversations in #41966, the fix was [backported to 5.0-rc2](https://github.com/dotnet/runtime/pull/41966#issuecomment-689106226).

However, I observed those `.a` files when building with the latest .NET 5 SDK `5.0.102`.
Did that fix really get backported to .NET 5?

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-----          12/12/2020    03:04        3671090 libSystem.IO.Compression.Native.a
-----          12/12/2020    03:04         426726 libSystem.Native.a
-----          12/12/2020    03:04          36752 libSystem.Net.Security.Native.a
-----          12/12/2020    03:04         997210 libSystem.Security.Cryptography.Native.OpenSsl.a
```

**Comment by vitek-karas** [comment]
@jkoritzinsky It seems with your big refactor of installer builds this has regressed. I must admit I don't understand how runtime packs are produced anymore, but for example this list contains the `.a` files, even though I don't see a reason for them to be included either in runtime packs or installers.
https://github.com/dotnet/runtime/blob/f2fb259686a6634e79a575e2777a03d2427d53d8/src/installer/pkg/sfx/Microsoft.NETCore.App/Directory.Build.props#L26-L45

**Comment by jkoritzinsky** [comment]
My big refactor wasn't in .NET 5.0 so it couldn't be the cause of this issue.

That list has entries for them since it needs to have entries for every file we've shipped in the runtime packages for .NET Core, and we used to ship them.
