### ISSUE TITLE
Crossgen2 package is unsigned and contains incorrect .deps.json file

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#47570]
`Microsoft.NETCore.App.Crossgen2.*` packages regressed between builds `6.0.0-alpha.1.20562.6` and `6.0.0-alpha.1.20563.11`:
- The package itself is no longer signed.
- Most executable files within the package are no longer signed.
- The contents of `crossgen2.deps.json` file is no longer correct. Trying to run `crossgen2.exe` gives `Could not resolve CoreCLR path` error.

I think it was caused by #38457.

**Comment by jkoritzinsky** [comment]
The package and it's contents are expected to be unsigned ever since we switched to post-build signing. I'll investigate the failure to run.

**Comment by jkoritzinsky** [comment]
Fix is in https://github.com/dotnet/arcade/pull/6869.

Once it's merged, we can either push through an update manually to dotnet/runtime or wait for the next Arcade rollout (which should be tomorrow)

**Comment by AntonLapounov** [comment]
@jkoritzinsky Thanks a lot for the explanation and the quick fix. I will verify the package after the next Arcade update.
