### ISSUE TITLE
Directory.Exists and File.Exists annotated parameter with [NotNullWhen(true)]

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#47573]
## Background and Motivation

Found when annotating roslyn. These methods should never return `true` for null.

## Proposed API

```diff
namespace System.IO
{
    public static class Directory {
-        public static bool Exists(string? path);
+        public static bool Exists([NotNullWhen(true)] string? path);
    }
    public static class File {
-        public static bool Exists(string? path);
+        public static bool Exists([NotNullWhen(true)] string? path);
    }
}
```

## Usage Examples

``` C#
string? path = ...
if (Directory.Exists(path))
{
    var subDirectories = Directory.GetDirectories(path); // no warning
}
```

## Alternative Designs

None.

## Risks

I couldn't imagine how they can return `true` for null.

**Comment by stephentoub** [comment]
Adding `[NotNullWhen(true)]` to these is fine.  If the path is null, they return false.

**Comment by huoyaoyuan** [comment]
Does this require API review?

**Comment by stephentoub** [comment]
No.  It's just a bug in the annotation not reflecting the existing documented semantics of the method.
