### ISSUE TITLE
Missing EINTR handling on macOS for opendir/readdir/closedir syscalls

### ISSUE THREAD

**Issue by Therzok** [dotnet/runtime#47584]
### Description

It seems that under certain conditions, the `opendir`, `readdir`, `closedir` can set `errno` to `EINTR`.

These 3 syscalls are the only ones I can see not handling EINTR: https://github.com/dotnet/runtime/blob/e98fb61d8b4bb6687ccddead861d8b140751647b/src/libraries/Native/Unix/System.Native/pal_io.c#L474

Note: it is not documented in the man pages, but it seems to be a problem in practice.

### Configuration

Mono 2020-02, macOS, x64. Not specific to this.

### Regression?

Only started happening with macOS Big Sur.

### Other information

See [this gist](https://gist.github.com/rmarinho/29070bb92c688f9ee1f6df55faaa1c73) for an exception being bubbled on mono which is using the same source as dotnet/runtime.

**Comment by danmosemsft** [comment]
`closedir` does document `EINTR` at least here https://www.man7.org/linux/man-pages/man3/closedir.3p.html. Not sure about the others.

**Comment by Therzok** [comment]
`opendir` is the one being called in the exception stack trace linked above, so I think it's fair to consider it set.

**Comment by danmosemsft** [comment]
@janvorli any thoghts here? I guess worst case, it is unnecessary code. My only thought (waves hands) that if EINTR is actually a bug here, then who knows if it would just continue to return EINTR, and we would hang.

**Comment by janvorli** [comment]
It seems that opendir can return EINTR on macOS as far as I can tell from https://opensource.apple.com/source/Libc/Libc-1439.40.11/gen/FreeBSD/opendir.c.auto.html. It internally calls fstatfs which can return EINTR according to its documentation. 
As for closedir, it calls regular `close` on a handle, thus the behavior of `close` controls the error code. There is an interesting discussion on EINTR and close and it seems that it should be ignored. See https://sourceware.org/bugzilla/show_bug.cgi?id=14627.
Regarding the readdir, it is not clear to me whether it can return EINTR or not.

Overall, it seems to me it would be safe to handle it at opendir / readdir and eat it at closedir.

**Comment by danmosemsft** [comment]
Thanks @janvorli . @Therzok would you like to offer a PR?

**Comment by Therzok** [comment]
@janvorli I dug a bit into the macos source code and the , and via: `getdirentries64` -> `getdirentriescommon` -> `vnode_getwithref` -> `vnode_getiocount` -> `msleep` -> `_sleep` we got a possible EINTR
