### ISSUE TITLE
Expose a global switch to disable IPV6 to overcome DualMode socket issues in environments that do not support IPV6

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#47583]
BCL as well as [external libraries](https://github.com/dotnet/runtime/pull/45614#issuecomment-739310008) tend to shift towards dual-stack sockets in their networking code. This conforms to best practices defined in [RFC1933](https://tools.ietf.org/html/rfc1933), but can lead to issues when connections are established through VPN tunnels which do not support IPv6 and/or dual-stack properly.

A custom ConnectCallback can help in HttpClient use cases where users have direct control over their HttpClient instances (#47267), but in cases where the Socket connections are carried out by an external component, users may get blocked (#45462).

This cases are rare, but the fix is simple, and easy to communicate (see #45893), therefore we should consider implementing it in .NET 6.

**Comment by karelz** [comment]
Would it make sense to generalize it to global switch to disable either IPv4 or IPv6?

**Comment by geoffkizer** [comment]
> Would it make sense to generalize it to global switch to disable either IPv4 or IPv6?

I doubt it. I haven't heard any issues re IPv4. 

Even if we wanted to do this, I think it would be a separate switch.

**Comment by karelz** [comment]
Triage: We cannot do today IPv6 only, so let's add DisableIPv6 switch.

**Comment by karelz** [comment]
Another case in #52287
