### ISSUE TITLE
Change SupportedOSPlatformAttribute warning

### ISSUE THREAD

**Issue by angelazhangmsft** [dotnet/runtime#47593]
### Description

Windows projects OS version as SupportedOSPlatformAttribute, and the version number is computed by the minimum OS that supports that contract. When an API isn’t guaranteed to be there, a warning message (see below) points people towards authoring a version check, which is undesirable for WinRT. We should **change this warning message** to point people towards [ApiInformation](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.ApiInformation?view=winrt-19041) checks.

Example: If I call this code in a .NET 5 console app with `SupportedOSPlatformVersion` of 10.0.17763.0:

```csharp
Console.WriteLine("IsDolbyVisionSupported: " + displayMonitor.IsDolbyVisionSupportedInHdrMode);
```

The following warning shows: 

Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Warning	CA1416	This call site is reachable on: 'Windows' 10.0.17763.0 and later. 'DisplayMonitor.IsDolbyVisionSupportedInHdrMode.get' is only supported on: 'Windows' 10.0.19041.0 and later.	Net5ConsoleApp	C:\Users\angzhang\source\repos\Net5ConsoleApp\Net5ConsoleApp\Program.cs	23	IntelliSense	Active	Microsoft.CodeAnalysis.NetAnalyzers

### Alternative

Alternatively, CsWinRT could remove the projection for this attribute and use the to-be-designed analyzer/attribute for contract checks.

**Comment by terrajobst** [comment]
@jeffhandley @buyaa-n

**Comment by buyaa-n** [comment]
@angelazhangmsft how could we know when it should point towards ApiInformation check? Are those APIs (or containing type/assembly) decorated with any distinguishing attribute?

**Comment by buyaa-n** [comment]
Seems we can use [ContractVersionAttribute](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.contractversionattribute.-ctor?view=winrt-19041) is that right?

**Comment by jeffhandley** [comment]
@terrajobst / @angelazhangmsft If I recall correctly on this, we concluded that this change was not necessary; is that correct?

**Comment by angelazhangmsft** [comment]
Yes the current plan is to go the route of the alternative suggestion (CsWinRT could remove the projection for this attribute and use the to-be-designed analyzer/attribute for contract checks.)

**Comment by terrajobst** [comment]
Yes. The conclusion was that CsWinRT should stop projecting their version information as `SupportedOSPlatformAttribute` and the instead provide their own analyzer.

**Comment by jeffhandley** [comment]
Thank you both!
