### ISSUE TITLE
PipeOptions overrides default

### ISSUE THREAD

**Issue by marco6** [dotnet/runtime#476]
In the [description ](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipeoptions.-ctor?view=dotnet-plat-ext-3.0) of the options available for a Pipe (from System.IO.Pipelines) I can read:

> pauseWriterThreshold
> 
> The number of bytes in the Pipe before FlushAsync(CancellationToken) starts blocking. A negative value prevents FlushAsync(CancellationToken) from ever blocking, **effectively making the number of bytes in the Pipe unlimited**.
> 

But this is not reflected in the [code](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeOptions.cs#L38): the real behavior is an exception or a default value. Given the value is read-only, there is no way to actually set this property as depicted.

**Comment by carlossanlop** [comment]
We documented this a few weeks ago. @halter73 since you helped review these, would you mind chiming in to help clarify @marco6 's question?

I found [the comment](https://github.com/dotnet/dotnet-api-docs/pull/3494#discussion_r346601831) 
in that documentation PR where we discussed this parameter.

**Comment by halter73** [comment]
@marco6 is right, I forgot we used `-1` to indicate the default PauseWriterThreshold should be used. The docs should read as follows.

> pauseWriterThreshold
> 
> The number of bytes in the Pipe before FlushAsync(CancellationToken) starts blocking. A value of zero prevents FlushAsync(CancellationToken) from ever blocking, **effectively making the number of bytes in the Pipe unlimited**.
> 

If you want to apply backpressure immediately, you can use a value of 1, but that probably goes without mentioning.

**Comment by carlossanlop** [comment]
I submitted a fix for this @halter73: https://github.com/dotnet/dotnet-api-docs/pull/4491

Thanks for reporting @marco6

I'm reopening so it gets autoclosed when the PR is merged.
