### ISSUE TITLE
Configure an await to propagate all errors by throwing an AggregateException

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#47605]
Let's throw another marginally useful idea for configuring `await`s.

## Background and Motivation

The `await` operator currently propagates only the first of the exceptions stored in a `Task` object. This is convenient in the vast majority of cases, because most asynchronous APIs by design will never complete with more than one errors. There is a handful of APIs though that do propagate multiple exceptions quite normally, and most of this information is lost when these APIs are `await`ed in the standard way. Although it is possible for a programmer to observe and handle all errors in this case, the workaround needed is slightly cumbersome and error prone.

## Proposed API

A new value `ThrowAggregateException` for the `AwaitBehavior` enum, which serves as a parameter for the `ConfigureAwait` method. This is an extension of the #47525 proposal.

```C#
namespace System.Threading.Tasks
{
    [Flags]
    public enum AwaitBehavior
    {
        //...
        ThrowAggregateException = 0x8, // Instead of throwing only the first exception
    }
}
```

## Usage Examples

This configuration could be used when awaiting the `Task.WhenAll` method, the upcoming [`Parallel.ForEachAsync`](https://github.com/dotnet/runtime/pull/46943) method, and the `Completion` property of the TPL Dataflow blocks:

```C#
try
{
    await Task.WhenAll(tasks).ConfigureAwait(AwaitBehavior.ThrowAggregateException);
}
catch (AggregateException aex)
{
    aex.Handle(ex => { /* ... */ });
}
```

The current workaround is to store the task in a variable before awaiting it, and in case of
exception to query the task's `Exception` property:

```C#
var whenAllTask = Task.WhenAll(tasks);
try
{
    await whenAllTask;
}
catch (Exception ex)
{
    if (whenAllTask.IsFaulted)
    {
        whenAllTask.Exception.Handle(ex => { /* ... */ });
    }
    else
    {
        // handle ex, which is certainly an OperationCanceledException
    }
}
```

## Alternative Designs

An extension method [`WithAggregateException`](https://stackoverflow.com/questions/18314961/i-want-await-to-throw-aggregateexception-not-just-the-first-exception) has been suggested in a StackOverflow question:

```C#
public static async Task WithAggregateException(this Task source)
{
    try
    {
        await source.ConfigureAwait(false);
    }
    catch
    {
        if (source.Exception == null) throw;
        ExceptionDispatchInfo.Capture(source.Exception).Throw();
    }
}
```

## Risks

None that I can think of.

**Comment by tarekgh** [comment]
CC @stephentoub

**Comment by stephentoub** [comment]
There are certainly cases where it'd be helpful, but they're in the vast minority, and it wouldn't really save much code. We're talking about the difference between:
```C#
await t.ConfigureAwait(AwaitBehavior.ThrowAggregateException);
```
and
```C#
await t.ConfigureAwait(AwaitBehavior.NoThrow);
t.Wait();
```
Given the infrequency with which this would be needed and the trivial ability to get the behavior with one more line, it doesn't seem warranted to pay the costs of building it in.

**Comment by theodorzoulias** [comment]
> ```cs
> await t.ConfigureAwait(AwaitBehavior.NoThrow);
> t.Wait();
> ```

Thanks for this workaround, it is good enough for me. The `AwaitBehavior.NoThrow` opens new possibilities for solving old problems. I'm closing this up.

**Comment by Kryptos-FR** [comment]
@stephentoub will the code above work with `ValueTask`? I thought that awaiting more than once could be an issue.

Or does it mean we need to first convert it to a Task? Where is it better to do it?

```csharp
// before the first await
Task<T> t = MethodAsync().AsTask();
await t.ConfigureAwait(AwaitBehavior.NoThrow);
t.Wait();

// just before Wait()
ValueTask<T> t = MethodAsync();
await t.ConfigureAwait(AwaitBehavior.NoThrow);
t.AsTask().Wait();
```

**Comment by stephentoub** [comment]
> will the code above work with ValueTask?

Technically, yes (with `.GetAwaiter().GetResult()` instead of `.Wait()`).  We'll need to come up with a good way to more specifically describe what's allowed.  You can only hook up one continuation (`.GetAwaiter().{Unsafe}OnCompleted`) and only use `GetResult()` once; `NoThrow` will do the former but not the latter, so it's ok to then do the latter once after.

**Comment by noseratio** [comment]
Hey @theodorzoulias, long time no no talk! :)
I was dealing with this problem too, I agree sometimes it's desirable to `await` without unwrapping of `AggregateException`. I think I've come with an handy extension method for that, [`WithAggregatedExceptions`](https://stackoverflow.com/questions/12007781/why-doesnt-await-on-task-whenall-throw-an-aggregateexception/62607500#62607500:~:text=A%20solution).

**Comment by theodorzoulias** [comment]
Hi @noseratio! Thanks for pinging. I've seen [your answer](https://stackoverflow.com/questions/12007781/why-doesnt-await-on-task-whenall-throw-an-aggregateexception/62607500#62607500), and I've upvoted it a long time ago. It's a great solution, but Stephen Toub's approach is hard to beat!

```C#
public static async Task WithAggregateException(this Task source)
{
    try { await source.ConfigureAwait(false); } catch { source.Wait(); }
}
```

**Comment by noseratio** [comment]
> It's a great solution, but Stephen Toub's approach is hard to beat!
> 

Stephen's approach is simple and nice, I agree. The extension approach might be of interest to those who don't want to introduce another local variable for a `Task`, while also taking advantage of `ex.Flatten()`.

**Comment by theodorzoulias** [comment]
@noseratio as you pointed out [elsewhere](https://stackoverflow.com/questions/12007781/why-doesnt-await-on-task-whenall-throw-an-aggregateexception/62607500#comment117041811_62607500), the `WithAggregateException` method posted in [my previous comment](https://github.com/dotnet/runtime/issues/47605#issuecomment-778827371) does not handle the case of a canceled task nicely. It propagates a task that transitions to a `Faulted` state instead of being `Canceled`, and holds an `AggregateException` with an inner `OperationCanceledException`. Which is rather awkward.

Below is an improved version of this method, that hopefully works as expected.

```C#
public static async Task WithAggregateException(this Task source)
{
    try { await source.ConfigureAwait(false); }
    catch (OperationCanceledException) when (source.IsCanceled) { throw; }
    catch { source.Wait(); }
}
```

**Comment by noseratio** [comment]
@theodorzoulias this snippet is rather elegant but there's still one thing. In general, I'm not a fan of using `ConfigureAwait(false)` in extension methods.

E.g., if `source` is a promise-like task which will be completed via `TaskCompletionSource.SetResult` on a thread with a synchronization context (e.g., a UI thread), there may be [some redundant context switching](https://stackoverflow.com/questions/28410046/revisiting-task-configureawaitcontinueoncapturedcontext-false), introduced by this tiny `WithAggregateException` method. 

I know many would disagree, but these days, [I prefer to not use `ConfigureAwait` at all](https://dev.to/noseratio/why-i-no-longer-use-configureawait-false-3pne) 🙂

**Comment by theodorzoulias** [comment]
> I'm not a fan of using `ConfigureAwait(false)` in extension methods.

@noseratio that's a controversial opinion! Anyway, in the future we'll have more incentives to use the `ConfigureAwait` method, because it will be enhanced with some cool new options (#47525). Like the `SuppressExceptions` option, that should be handy quite often.

**Comment by noseratio** [comment]
> @noseratio that's a controversial opinion! Anyway, in the future we'll have more incentives to use the `ConfigureAwait` method, because it will be enhanced with some cool new options (#47525).

I like that proposal about `ConfigureAwait` enhancements, it looks interesting! But I'm also glad I've embraced the use of `await TaskScheduler.Default.SwitchTo()` explicitly where I might be concerned about `ConfigureAwait`, at least about its synchronization context-related side-effects :)
