### ISSUE TITLE
Really need an object.ToString(IFormatProvider) to hunt down code quality issues

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#47606]
## Background and Motivation

Today I had to track down yet another corruption issue where the root cause was using `object.ToString()` on something that turned out to be a decimal, and it threw an unexpected comma that broke the text serialization format (comma was the list separator and the programmer assumed only things that started as strings needed to be escaped). By this point this single issue has drawn more of my time than everything, including the deadlocks due to hidden sync-over-async and refusal to crash when out of memory (we've had discussions on this--for some reason it won't crash if the global exception handler can't be invoked because memory is gone but if you try to simulate it it will).

I've held off so far because the compiler has to be smart about this one or break everybody's source code, but the one I just encountered was in a particularly bad place

## Proposed API

````
namespace System {
    public partial class Object {
        public virtual string ToString(System.Globalization.IFormatProvider? provider) => ToString();
    }
    public partial class Int32 {
        public override string ToString(System.Globalization.IFormatProvider? provider) { /* same as before */ };
    }
    /* Continues for all other builtin classes that provide ToString(IFormatProvider) */
    public partial Nullable<T> : ValueType {
        public override string ToString(System.Globalization.IFormatProvider? provider) => HasValue ? GetValueOrDefault() .ToString(provider) : "";
    }
}
````

My intention is to use an IL level analyzer to ruthlessly hunt down and remove any calls to `object.ToString()`, `int.ToString()` and all related cases on my own codebase. Manually setting CurrentCulture or InvariantCulture should provide reasonable ensurance against any more of these making it past code review, if just having to type it out doesn't succeed on its own. Right now I can't because calls have to exist.

## Alternative Solutions

I considered if this can be done with an interface or not. It can't, because among other things `Nullable<T>` can't take interfaces and I found a surprising number of places where we depend on `Nullable<T>.ToString()` not throwing. (Thus, if the underlying JIT issue was fixed to let it take interfaces it still wouldn't fix anything at all because `null.ToString()` throws.)

## Risks

This won't break any ABI, but it will break source code unless the C# compiler is enhanced to impute either `new` or `overrides` onto such cases. `new` would match the ABI while `overrides` would work as one would expect.

**Comment by GrabYourPitchforks** [comment]
Can't this be done with an extension method?

```cs
static class MyExtensions
{
    // plus whatever overloads are needed for Nullable<T>, etc.
    public static string ToString(this object @this, IFormatProvider provider)
    {
        return (@this is IFormattable fmt) ? fmt.ToString(null, provider) : this?.ToString();
    }
}
```

That would avoid adding globalization-related concepts to the base _object_ type, which in turn would require the entirety of the .NET ecosystem to have to consider those concepts when creating any new types.

**Comment by jhudsoncedaron** [comment]
@GrabYourPitchforks : We're in the case of the entirety of the .NET ecosystem has to consider it _now_ because int.ToString() cares.

If the technical hurdle involving putting an interface on Nullable could be overcome, an interface on object with a default implementation would work.

**Comment by GrabYourPitchforks** [comment]
> We're in the case of the entirety of the .NET ecosystem has to consider it now because int.ToString() cares.

If your app cares about this, consider enabling the existing [CA1305](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1305) analyzer rule in your projects. This will produce a compiler warning (or error, depending on your configuration) when calling `ToString()` if a `ToString(..., IFormatProvider)` overload exists. It would detect calls to `int.ToString()` and respond "hey, did you instead mean `int.ToString(string, IFormatProvider)`?"

You'd of course need to update any call sites to be bound to the correct overload. But your proposal already involved introducing new APIs, which would have involved changing callers anyway. This analyzer rule also doesn't detect third-party code that might call `int.ToString()` against your wishes, but the API proposal wouldn't have solved that issue for you, either.
