### ISSUE TITLE
GPLv2 licensed file in source code

### ISSUE THREAD

**Issue by wojteo** [dotnet/runtime#47628]
In the repository there is file logic.cs which is licensed on GPLv2 (runtime/src/mono/mono/benchmark/logic.cs). 

Doesn't that pose legal complications to anyone distributing this library? Does this file end up in the final dlls ?

**Comment by stephentoub** [comment]
cc: @richlander, @marek-safar

**Comment by marek-safar** [comment]
I think we can delete the file. It was probably mirrored unnecessary.

/cc @akoeplinger

**Comment by akoeplinger** [comment]
It's at least mentioned in the third party notices file: https://github.com/dotnet/runtime/blob/master/src/mono/mono/benchmark/THIRD-PARTY-NOTICES.TXT#L44-L63

But I agree, the whole mono/benchmark folder isn't used at all in this repo so we can delete it.
