### ISSUE TITLE
iOS: AOT compiler emits a reference to mini_llvmonly_pop_lmf

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#47635]
### Description

I'm trying the AOT compiler for iOS as shipped as `Microsoft.NetCore.App.Runtime.AOT.{host-rid}.Cross.{target-rid}` packages, and there seems to be a difference: the AOT-compiled code will have a reference to `mini_llvmonly_pop_lmf`, which doesn't exist, so linking the AOT output into the final library will fail:

```
ld: warning: object file (/Users/rolf/work/maccore/dotnet-tools/xamarin-macios/tests/dotnet/packages/microsoft.netcore.app.runtime.ios-arm64/6.0.0-alpha.1.21063.13/runtimes/ios-arm64/native/libmonosgen-2.0.a(gshell.c.o)) was built for newer iOS version (8.0) than being linked (7.0)
Undefined symbols for architecture arm64:
"_mini_llvmonly_pop_lmf", referenced from:
   wrapper_managed_to_native_object___icall_wrapper_mini_llvmonly_pop_lmf_intptr in System.Private.CoreLib.dll.o
ld: symbol(s) not found for architecture arm64
```

I'm attaching a test case:

* Download 
[aottest-05a4fa4.zip](https://github.com/dotnet/runtime/files/5894966/aottest-05a4fa4.zip)
* Open test.sh and change AOT_OLD and AOT_NEW to point to your local versions of the AOT compilers in question.
* Run ./test.sh:

```
[...]
+ echo Old:
Old:
+ nm old-output/System.Private.CoreLib.o
+ grep mini_llvmonly_pop_lmf
+ true
+ echo New:
New:
+ nm new-output/System.Private.CoreLib.o
+ grep mini_llvmonly_pop_lmf
                 U _mini_llvmonly_pop_lmf
000000000049f800 t wrapper_managed_to_native_object___icall_wrapper_mini_llvmonly_pop_lmf_intptr
```

This shows that the new AOT compiler emits `mini_llvmonly_pop_lmf`, while the old one doesn't.

CC @steveisok

**Comment by steveisok** [comment]
@vargaz Can you take a look?

**Comment by vargaz** [comment]
This looks like some kind of mismatch, the function is defined in the runtime in llvmonly-runtime.c.

**Comment by SamMonoRT** [comment]
@imhameed follow up with @vargaz and take this over please

**Comment by vargaz** [comment]
Does this still happen ?

**Comment by rolfbjarne** [comment]
No, this doesn't seem to happen anymore.
