### ISSUE TITLE
<MonoAOTCompiler/> MSBuild task does not work when used as <PackageReference/>

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#47630]
### Description

If I have a project such as:

```xml
<Project Sdk="Microsoft.Build.NoTargets/2.0.17">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Runtime.MonoAOTCompiler.Task" Version="6.0.0-preview.1.21072.5" IncludeAssets="build" />
  </ItemGroup>
  <UsingTask TaskName="MonoAOTCompiler" AssemblyFile="$(MonoAOTCompilerTaskAssemblyPath)" />
  <Target Name="Build">
    <!-- NOTE: just trying to get to the point the task is called -->
    <MonoAOTCompiler />
  </Target>
</Project>
```
(You could also use `Microsoft.NET.Sdk` if you prefer)

With the `nuget.config`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Building fails with:

```
error MSB4022: The result "" of evaluating the value "$(MonoAOTCompilerTaskAssemblyPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.
```

Log: [msbuild.zip](https://github.com/dotnet/runtime/files/5894423/msbuild.zip)

### Configuration

On Windows 10:
```
> dotnet --version
6.0.100-alpha.1.21064.27
```

### Regression?

No

### Other information

I think the idea of using `$(MonoAOTCompilerTaskAssemblyPath)` with `<PackageReference/>` and `<UsingTask/>` might be flawed. I think `<UsingTask/>` will be evaluated before `$(MonoAOTCompilerTaskAssemblyPath)` is set.

Let me know if I missed something, it seems like I'm using it as the doc suggests:

https://github.com/dotnet/runtime/blob/5fc66480fe47ff8f4b2620901e2d33177af2dd4c/src/mono/netcore/nuget/Microsoft.NET.Runtime.MonoAOTCompiler.Task/README.md

We got this to work in the upcoming Android workload by installing this package as a [workload pack](https://github.com/xamarin/xamarin-android/pull/5539). So we aren't blocked on this, thanks!

**Comment by SamMonoRT** [comment]
@steveisok - is this fixed via recent efforts ?

**Comment by steveisok** [comment]
Checking...  this may be something else

**Comment by mdh1418** [comment]
@jonathanpeppers Thanks for the catch! The docs were initially written with the intent that the import would be within `dotnet/runtime` where the variable `MonoAOTCompilerTaskAssemblyPath` is initialized https://github.com/dotnet/runtime/blob/8698d0f34506695f38824b5573b8e75bcc80684f/Directory.Build.props#L84. I am guessing that the error is encountered in a different environment that is not `dotnet/runtime`, leading to the empty string value.

I believe instead, a package reference and using task such as 
https://github.com/dotnet/samples/blob/52bd55feabf0ba695a8ae786d50ad52354078a40/core/mono-samples/Android/AndroidSampleApp.csproj#L14
https://github.com/dotnet/samples/blob/52bd55feabf0ba695a8ae786d50ad52354078a40/core/mono-samples/Android/AndroidSampleApp.csproj#L36
*should* work.

I'll update the docs accordingly, but if that works for your case, then this issue can be closed :)

**Comment by jonathanpeppers** [comment]
We are using this package from a .NET workload instead of a NuGet package, so we don't have an issue here.

When I filed this, I noticed the documented example doesn't work as described. If that's still the case, I'd just keep this open until the docs are updated, thanks!
