### ISSUE TITLE
System.Linq.Expressions simulating Nullable.GetValueOrDefault should use GetUninitializedObject instead of Activator.CreateInstance

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#47647]
See the conversation [here](https://github.com/dotnet/runtime/pull/47585/files#r566671066).

This code in SLE:

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/TypeOperations.cs#L155-L160

has the possibility of behaving incorrectly if/when https://github.com/dotnet/csharplang/issues/99 is implemented in the future. If the value type has a parameterless constructor present in IL, `Activator.CreateInstance` would run that parameterless constructor. Which means the value you get back from `Nullable<T>.GetValueOrDefault()` could be different if run through this code than if you actually called `Nullable<T>.GetValueOrDefault()` on a "null" value.

We should instead change this to use `GetUninitializedObject` which wouldn't run the parameterless constructor. (And of course add a test for this.)

**Comment by GrabYourPitchforks** [comment]
See also the table I put in the description of https://github.com/dotnet/runtime/issues/45397. It gives a few other scenarios where LINQ instantiates objects incorrectly.

**Comment by eerhardt** [comment]
If this call isn't changed to `GetUninitializedObject`, we need to revisit the suppression being added here:

https://github.com/dotnet/runtime/pull/47585/files/07c0fc14fbab9b092a2270083bd933cbee8b2248#r567222530

**Comment by eerhardt** [comment]
Closing in favor of #45397. There are a handful of scenarios that need fixing here, it doesn't make sense to track each scenario in a separate issue.
