### ISSUE TITLE
ToString formatted output incorrect on net5.0

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/runtime#47670]
This code:
````
            Console.WriteLine("{0}", 30000.ToString("N", new CultureInfo("de-DE")));
````
Produces different output when compiled netcoreapp3.1 and net5.0, note: 3 decimal places in net5.0 and 2 decimal places in netcoreapp3.1
Net5.0
````
30.000,000
````
netcoreapp3.1
````
30.000,00
````

**Comment by tannergooding** [comment]
I'm fairly certain this is by design and due to standardizing on ICU

CC. @tarekgh, @GrabYourPitchforks

**Comment by tannergooding** [comment]
See also https://github.com/dotnet/runtime/issues/44587

**Comment by KevinRansom** [comment]
@tannergooding , thanks for the info I will update our tests accordingly.
