### ISSUE TITLE
Method Optimization in Debug Code

### ISSUE THREAD

**Issue by hopperpl** [dotnet/runtime#47675]
I often run into the situation that I debug an application to figure out some lacking behavior that was missed during design. That's why we have debuggers.

Debugging and RELEASE usually don't fit well together, but applications often have critical paths that extremely slow down with DEBUG code. With DEBUG/RELEASE I'm just referring to the code optimization settings in the project for simplicity.

Of course there are 2 steps of optimization; the IL code optimizing in the compiler, and then the JIT code optimizing in the runtime. We already have means to hint the compiler/JIT to optimize some functions with the MethodImplOptions enum, but that only works with RELEASE code. There is no way to my knowledge, to mark a function to be optimized in DEBUG. (Of course inlining such functions cannot work -- let's put that aside)

-----

At the moment I have 3 scenarios to address this:

1. build as RELEASE and mark a few functions as MethodImplOptions.NoOptimization 👎💥💥💥 

    problem: it simply doesn't work with the debugger; the method code is (via disassembly) not optimized, but Visual Studio gets confused a lot, fails single-step often, msvcmon loves to crash -- all not Runtime related, but Visual Studio just can't handle it... the Visual Studio Team makes assumption that when one function has debug information available, then everything else has too (unchecked) ... but it hasn't, so all crashes... it's just unusable and I can't make that Team to fix it or even address it.

2. build as DEBUG and mark  a few functions as MethodImplOptions.AggressiveOptimization 👎

    problem: it's ignored

3. build as 2 modules one DEBUG and the other RELEASE 👍👎

    that actually works, but it is really complicated to mix the code into 2 sub-projects and keep it separated. Visual Studio enjoys getting confused with 2 projects and the same code base, IntelliSense mixes up suggestions... in short, it works, but it is highly frustrating to keep the development environment calm and under control.

-----

Now, I'm trying to address scenario (2). From my understanding, it shouldn't be complicated to enable partial method optimization in the C# compiler based on attributes. 

And it also shouldn't be complicated to have the JIT compiler optimize such functions during execution. In my understanding, everything is already available, there is just no way to trigger functions to get optimized while the default optimization is off. Of course, inter-method optimizations are not possible (or overly complicated) -- but that is not needed. 

-----

**Now, this is Runtime, not Compiler. I want to address Runtime first. So my questions to the JIT developers are:**

1. is the JIT capable of partial (method subset) optimization? or am I misguided and there are "two" JITs for DEBUG and RELEASE (I'm not referring to tier compilation -- that's different)
2. is it in theory possible, to have everything marked as dont-optimize by default, but mark a subset as optimize?
3. how does the JIT determine if a method shall be optimized? (attributes, flags, meta-data, debugger-trigger)
4. are there already plans to fine-tune optimizations?

**Comment by jkotas** [comment]
> build as RELEASE and mark a few functions as MethodImplOptions.NoOptimization 
> it's just unusable and I can't make that Team to fix it or even address it

Could you please share links to the bug reports that describe the problems you are hitting?
