### ISSUE TITLE
Checking if a generic collection without constraints contains null item

### ISSUE THREAD

**Issue by anreton** [dotnet/runtime#47681]
Scenario:
- There is a generic class without any constraints: value type and reference type is valid.
- There is ctor with a generic collection parameter.
- Zero, false, "", etc is valid item of the collection. 
- But null item is invalid.

Question:
Is there a more performance way to check null item in the generic collection?

E.g.

```csharp
public sealed class Foo<T>
{
	public Foo(IEnumerable<T> values)
	{
		if (values is null)
		{
			throw new ArgumentNullException(nameof(values));
		}

		var valuesSet = values.ToHashSet();

		if (valuesSet.Count == 0)
		{
			throw new ArgumentException("Sequence is empty.", nameof(values));
		}

		//Error CS1503  Argument 1: cannot convert from '<null>' to 'T'
		//if (valuesSet.Contains(null)) 
		//{
		//	throw new ArgumentException("Sequence contains null.", nameof(values));
		//}

		//No errors, just false on each value if T is non-nullable.
		if (valuesSet.Any(value => value is null))
		{
			throw new ArgumentException("Sequence contains null.", nameof(values));
		}

		this.Values = valuesSet;
	}

	public IReadOnlySet<T> Values { get; }
}
```

**Comment by huoyaoyuan** [comment]
```csharp
if (!typeof(T).IsValueType && values.Contains(default(T)))
{

}
```

You can use `default`, and guard for reference time. The guard will become a JIT time constant.
If you want also to cover nullable value type, you can use `Nullable.GetUnderlyingType(typeof(T)) != null`.

**Comment by anreton** [comment]
@huoyaoyuan, an interesting solution. Thanks for the advice.
