### ISSUE TITLE
How relevant is CPU_HAS_FP_SUPPORT?

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#47708]
I see there is a little bit of code that switches on this define here and there:
```
importer.cpp:12698:#if !CPU_HAS_FP_SUPPORT
lclvars.cpp:3584:#if CPU_HAS_FP_SUPPORT
lsra.cpp:1526:#if CPU_HAS_FP_SUPPORT
morph.cpp:12498:#if !CPU_HAS_FP_SUPPORT
morph.cpp:15497:#if !CPU_HAS_FP_SUPPORT
scopeinfo.cpp:380:#if !CPU_HAS_FP_SUPPORT
scopeinfo.cpp:414:#if CPU_HAS_FP_SUPPORT
```
Is that actually all that's needed to support porting to CPUs without FP support?
What is the purpose of this define?

FWIW, it is set to `1` for all currently supported targets.

**Comment by JulieLeeMSFT** [comment]
CC @BruceForstall if he can answer this.

**Comment by BruceForstall** [comment]
It's almost certain that this support has bit-rotted, and we should just remove the ifdefs. cc @briansull

**Comment by briansull** [comment]
I would also agree that we should just remove these ifdefs

**Comment by JulieLeeMSFT** [comment]
@briansull Is this .NET 6 scope?

**Comment by briansull** [comment]
@JulieLeeMSFT Yes, We can remove this ifdef for .Net 6.0 as we only have targets that have native FP support.
Previously, before .NET Core, we had some targets that uses FP emulation,
