### ISSUE TITLE
HttpClientHandler hangs on simple request with SocketsHttpHandler

### ISSUE THREAD

**Issue by SteveNorwood** [dotnet/runtime#47706]
### Bug Description
The HttpClientHandler appears to hang when not using WinHttpHandler in certain situations. The change described in the [HttpClientHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler?view=net-5.0#remarks) documentation shows that for .NET Core 2.1 and later, the code no longer uses WinHttpHandler, and the code has moved to SocketsHttpHandler. I understand there is a workaround in using WinHttpHandler, but the request seems extremely simple and forces me to use a Windows machine. I have not been able to test this on any other OS yet.

I originally created [this](https://stackoverflow.com/questions/65920772/c-sharp-httpclient-not-handling-304-307-redirects) StackOverflow post as I wasn't sure what was causing this issue. Hostel pointed me towards HttpClientHandler and it does appear to be an issue here and the change in .NET Core 2.1.

### To Reproduce
```c#
var httpClient = new HttpClient();
httpClient.Timeout = TimeSpan.FromSeconds(10);

var response = await httpClient.GetAsync("https://www.tesco.com/favicon.ico");
```

If you create a new Console Application in Visual Studio that is .NET Core 2.1 or later, the last line will hang. This only seems to hang on certain URLs, but for 99% of cases this code will work without any hanging or exceptions. These are the versions I have tested this on and whether is works or not:

| .NET Version | Success |
| ------------- | ------------- |
| .NET Framework 4.8 | Works |
| .NET Core 1.0 | Works |
| .NET Core 1.1 | Works |
| .NET Core 2.0 | Works |
| .NET Core 2.1 | Does not work |
| .NET Core 2.2 | Does not work |
| .NET Core 3.0 | Does not work |
| .NET Core 3.1 | Does not work |
| .NET 5 | Does not work |

### Exceptions
When the code times out (assuming no infinite timeout), a `SocketException: The I/O operation has been aborted because of either a thread exit or an application request.` is thrown within a TaskCanceledException and an IOException.

### Further technical details
This was on Visual Studio Professional Version 16.8.4

`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  1.1.13 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.520 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by davidfowl** [comment]
I can reproduce this.

**Comment by stephentoub** [comment]
I can check when I'm at my computer,  but it's most likely the server rejecting/ignoring the request because it wants some header the client isn't sending by default,  like an Accept header of some variety.

**Comment by davidfowl** [comment]
Here's the code I tried. It's really weird:

```C#
var handler = new SocketsHttpHandler
{
    PlaintextStreamFilter = (context, token) =>
    {
        return ValueTask.FromResult<Stream>(new LoggingStream(context.PlaintextStream));
    }
};
var httpClient = new HttpClient(handler);
// httpClient.Timeout = TimeSpan.FromSeconds(10);

var response = await httpClient.GetAsync("https://www.tesco.com/favicon.ico");
```

The logging stream just prints out the messages read and written and it never gets the HTTP/1.1 response. It's likely a TLS problem not an HttpClient problem.

```
WriteAsync[50]
47 45 54 20 2F 66 61 76  69 63 6F 6E 2E 69 63 6F   GET /fav icon.ico
20 48 54 54 50 2F 31 2E  31 0D 0A 48 6F 73 74 3A    HTTP/1. 1..Host:
20 77 77 77 2E 74 65 73  63 6F 2E 63 6F 6D 0D 0A    www.tes co.com..
0D 0A                                              ..
```

The `ReadAsync` call never returns from `SslStream`.

**Comment by stephentoub** [comment]
It looks like the server is only allowing HTTP/2.  When I add:
```C#
httpClient.DefaultRequestVersion = HttpVersion.Version20;
```
the repro works fine.

**Comment by stephentoub** [comment]
> so there's probably some other combination of inputs with 1.1 it accepts.

Yeah, for example what I suggested in my initial reply.  If I stick with 1.1 but add this:
```C#
httpClient.DefaultRequestHeaders.Add("Accept", "image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8");
```
the repro also works.

So, basically, this is the server being picky about what requests look like.

**Comment by davidfowl** [comment]
What kinda server hangs when it doesn't get an accept header 😱 ?

**Comment by SteveNorwood** [comment]
I've got a couple of troublesome URLs and @stephentoub your suggestions seem to fix it. I've put Accept */* which fixes it and HTTP/2 does the same.

Does .NET Framework 4.8/.NET Core 2 automatically put the correct headers onto the call? As I assume they are not defaulting to HTTP/2. Just a little confused as to why it breaks at .NET Core 2.1

**Comment by stephentoub** [comment]
> Does .NET Framework 4.8/.NET Core 2 automatically put the correct headers onto the call?

I believe both .NET Framework 4.8 and WinHttpHandler are adding a `Connection: Keep-Alive` header, which is not necessary for HTTP/1.1, but that also appears to make this particular server happy.
```C#
c.DefaultRequestHeaders.Add("Connection", "Keep-Alive");
```

**Comment by SteveNorwood** [comment]
Yeah, can confirm that this server and a couple of others seem to be set up incredibly strangely. Got a friend to try running some of this on Python too and they aren't getting anywhere with it either. 

Thanks for looking into this, I wasn't aware the culprit servers would just hang without specific requirements being met. There isn't much that can be done if it's not responding, as the timeout is doing what it does best. 

Thanks again @stephentoub and @davidfowl, I'll close this now as it's not a .NET issue.
