### ISSUE TITLE
[release/5.0] Backport Fix for Issue 46529 incorrect 64-bit shift result with cast to int

### ISSUE THREAD

**Issue by briansull** [dotnet/runtime#47724]
### Incorrect behavior a 64-bit long with shift of 32 or more combined with a cast to int 

The JIT generates incorrect code for this code pattern:

`(int) (X << C)`

where C >= 32 and
and  X is anything with a potential side-effect and is 64-bit integer type

## Customer Impact

Reported by customer who was migrating to .Net Core from the Desktop runtime.

## Regression?

This is a regression that was introduced in the .Net 3.X timeframe by 
https://github.com/dotnet/coreclr/pull/19899

## Testing

SuperPMI, new unit test, CLR outerloop,  asm diffs.

## Risk

Low

**Comment by briansull** [comment]
Related issue #46529

**Comment by briansull** [comment]
@sandreenko PTAL

**Comment by briansull** [comment]
@JulieLeeMSFT

**Comment by briansull** [comment]
Posted the fix for [release/3.1]
https://github.com/dotnet/coreclr/pull/28146

**Comment by JulieLeeMSFT** [comment]
Closing since both 5.0 and 3.1 fixes got merged.
