### ISSUE TITLE
Graphics.DrawImageUnscaled(Bitmap, new Point(0, 0)) causes weird artifacts on Linux

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/runtime#47720]
I am working on a graphics-heavy project that has moved to running on Linux containers. For the most part things have worked ok. However, there is a heavy reliance on System.Drawing for some aspects, which is now using the System.Drawing.Common library to maintain the same behavior. One of the endpoints does essentially the following:

```csharp
using var output = new Bitmap(256, 256);
using(var g = Graphics.FromImage(output))
{
  using Stream stream = LoadInitialImage();
  using var bmp1 = new Bitmap(stream);
  g.DrawImageUnscaled(bmp1, new Point(0, 0,));

  using var stream2 = LoadSecondImage();
  using var bmp2 = new Bitmap(stream2);
  g.DrawImageUnscaled(bmp2, new Point(0, 0));
}
```

When run on Windows (.NET 5), the image appears as expected:

![image](https://user-images.githubusercontent.com/583206/106508953-d27e8d80-6481-11eb-8e0c-0fa5509387cd.png)

If run on Linux (.NET 5) via container it will sometimes work, and then sometimes create something similar to the following:

![image](https://user-images.githubusercontent.com/583206/106508497-4ff5ce00-6481-11eb-9eb7-d3af203c1145.png)

Happy to provide more details and can get you the images for the actual writing if that would be helpful.

**Comment by huoyaoyuan** [comment]
Related: https://github.com/dotnet/runtime/issues/47122#issuecomment-770056183

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
