### ISSUE TITLE
System.String.Concat(object, object, object, object)

### ISSUE THREAD

**Issue by Happypig375** [dotnet/runtime#47746]
## Background and Motivation

While porting code from .NET Framework to .NET 5.0, one reflection use throws an exception due to `System.String.Concat(object, object, object, object)` not being found. `System.String.Concat(string, string, string, string)` is there. Why is this overload missing? 

## Proposed API

```diff
namespace System {
    class String {
+       public static string Concat(object arg0, object arg1, object arg2, object arg3);
    }
}
```

## Usage Examples

```C#
string.Concat(new object(), new object(), new object(), new object()); // Does not allocate an array, helps memory and performance
```

## Alternative Designs

Nope.

## Risks

Nope.

**Comment by huoyaoyuan** [comment]
The overload was always present since .NET Core 1.0 and .NET Standard 1.0.
Your reflection code may get confused and failed to find the method. Recheck it.

**Comment by Happypig375** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=net-5.0
Not there.

https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=netframework-4.8
Present.

**Comment by huoyaoyuan** [comment]
Sorry. I jumped to the false link.

Since you are using reflection, changing to `Join(object[])` shouldn't harm much.

**Comment by Happypig375** [comment]
Yes, but adding this overload also shouldn't harm much. It fits the theme of reducing allocations and improving performance.

**Comment by svick** [comment]
Note that [the .Net Framework method](https://referencesource.microsoft.com/#mscorlib/system/string.cs,83140cb97d1a8514) is a weird beast:

Its actual signature is `public static String Concat(Object arg0, Object arg1, Object arg2, Object arg3, __arglist)`, where `__arglist` is the undocumented and almost never used keyword for functions with variable number of parameters.

This also means that the C# code `string.Concat(new object(), new object(), new object(), new object())` on .Net Framework does *not* call this overload. For that, you need `string.Concat(new object(), new object(), new object(), new object(), __arglist())` (possibly with non-zero number of arguments inside the `__arglist`).

Also, the implementation just allocates an array for the arguments and then delegates the actual execution to `Concat(object[])`. So calling this overload does more work than calling the array overload.

I'm not sure what this means for adding a similar overload to .Net 6.

**Comment by stephentoub** [comment]
Right, as @svick said, there is no overload:
```C#
public static string Concat(object arg0, object arg1, object arg2, object arg3);
```
in .NET, neither in .NET Framework nor .NET Core.  Both have:
```C#
public static string Concat(params object[] args)
```
and then .NET Framework also has:
```C#
public static String Concat(Object arg0, Object arg1, Object arg2, Object arg3, __arglist) 
```
To call that, you'd have to write code like:
```C#
string.Concat("this ", "is ", "a ", "test ", __arglist("hello ", "world"))
```
and then under the covers that's just going to turn around, allocate an object[], and call the previously cited Concat(params object[]) overload.

As effectively no one uses that overload, and it requires using an undocumented C# keyword "__arglist", there are no plans to add it to .NET 6.  Note that the required supporting infrastructure doesn't even exist in .NET Standard (https://github.com/dotnet/standard/commit/52651e78ac329c56fb59cebf5b24174f25acb070).

The docs here are misleading and should ideally be fixed.
https://docs.microsoft.com/en-us/dotnet/api/system.string.concat?view=netframework-4.8#System_String_Concat_System_Object_System_Object_System_Object_System_Object_
There is no such overload, and the example for the overload actually uses the Concat(string, string, string, string) overload.  There is at least a note at the bottom of the discussion:
"This method is marked with the vararg keyword, which means that it supports a variable number of parameters. The method can be called from Visual C++, but it cannot be called from C# or Visual Basic code. The C# and Visual Basic compilers resolve calls to Concat(Object, Object, Object, Object) as calls to Concat(Object[])."
