### ISSUE TITLE
Using NativeDigits and DigitSubstitution in formatting numbers

### ISSUE THREAD

**Issue by arfilon** [dotnet/runtime#47749]
Hello

I am considering emplement `NumberFormatInfo.DigitSubstitution` property.  since the remark section in (https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo.digitsubstitution?view=net-5.0)
says
**The DigitSubstitution property is reserved for future use. Currently, it is not used in either parsing or formatting operations for the current NumberFormatInfo object.**

I found that limitation during my work on formating some dates to Arabic, I found that the Arabic Numbers Already exist in the dot net.

 ```
           decimal value = -123456.789M;

            var defaultResult = value.ToString();
            var info =new System.Globalization.CultureInfo("ar-JO");
            var format = info.NumberFormat;
            format.DigitSubstitution = System.Globalization.DigitShapes.NativeNational;
            format.NegativeSign = "x";
            var expectedResult = 
                format.NegativeSign 
                + string.Concat(format.NativeDigits[1..7]) 
                + format.NumberDecimalSeparator 
                + string.Concat(format.NativeDigits[7..10]);



            System.Threading.Thread.CurrentThread.CurrentCulture = info;
            var actualResult = value.ToString();
        
```
![image](https://user-images.githubusercontent.com/11093690/106585248-cb25b580-654f-11eb-9912-bc2ccad99245.png)

as you can see the `actualResult` contains the correct `NegativeSign` Property and `NumberDecimalSeparator` Property, but not `NativeDigits`.

I believe many changes have to be done on Number.Formatting.cs ( https://github.com/dotnet/runtime/blob/69f260eff523bc16c8a95c232e4816b3a1764e88/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs )

and maybe some change needed in other places.
`System.Globalization.DigitShapes` have 3 items
`NativeNational`, `None` and `Context`, the first one need some work, but the last one may be challenging.

this issue to discuss this change, and figuring out what I do not know about this. before I get started.

thanks for the Input.

**Comment by tarekgh** [comment]
.NET doesn't support formatting or parsing none ASCII digits. Although, this is reasonable feature to add but it is not a priority to support it from now considering the other features work we are doing in the next releases. 

I would suggest you can support that yourself without the need of the change in the .NET. You can write a simple code use the regular formatting code and then manually replace the produced digits to the native digit shapes. This shouldn't be difficult to do. You can do the same for parsing, before parsing replace the native digits to the ASCII digits and then parse. Let me know if you need help with that. 

By that I am closing this issue and we can revisit that in the future as needed. Thanks for reporting the issue. Feel free to send any more questions and we'll be happy to help with.

**Comment by arfilon** [comment]
Thanks for offering help on this.
we already did the necessary workaround.

What I propose is permission to help in actually implementing this for future releases.

But unfortunately, I have to wait until non-ASCII formatting to be added to the roadmap.

And what the point of not supporting non-ASCII, is that for runtime compatibility cross environments and operating systems or just for low priority?

Thanks

**Comment by tarekgh** [comment]
> And what the point of not supporting non-ASCII, is that for runtime compatibility cross environments and operating systems or just for low priority?

A couple of reasons, first is the perf. we are trying to make formatting or parsing well performed because these used in most popular scenarios. Second, this feature was not getting any demand behind it. we saw most of the users are satisfied with using Ascii numbers.

Usually I see this as a feature that anyone can provide in the Nuget packages and not necessary needed to be part of the core. I would recommend to try this step by creating a new Nuget package for a library doing that and then try to measure the demand on such library. If we see enough demand, we can consider that in the core. 

Thanks again and let's keep in touch for any news come up related to this issue.
