### ISSUE TITLE
System.Darwing.Common Icon tests failures on Mono on Windows.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#47759]
System.Drawing.Tests.IconTests have a number of tests that hit this code path:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs#L647

This code depends on COM support and currently Mono on Windows have not enabled COM support (inline with other Mono netcore platforms). This triggers a rather subtle problem that can cause crash depending on what registers has been used up to this point.

Mono will not do anything specific with the signature:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Drawing.Common/src/System/Drawing/Icon.Windows.cs#L901

and that method has 4 parameters:

https://docs.microsoft.com/en-us/windows/win32/api/olectl/nf-olectl-olecreatepictureindirect

so OleCreatePictureIndirect expects parameters in rcx,rdx,r8 and r9 inline with Windows x64 ABI, but since above dllimport is not handled differently on Mono compared to other dllimports, it will assume 3 parameters and that returned interface will be placed in rax, and that will, depending on content in r9 cause random crashes or undefined behaviour.

IconTests that hits this code path will be disabled with this issue as its active issue.

**Comment by jkotas** [comment]
Should Mono throw when it encounters unsupported type in the PInvoke signatures? It is what CoreCLR does on non-Windows.

**Comment by lateralusX** [comment]
Yes, I believe that is something we should probably investigate doing, one thing I was a little curious around is how CoreClr handles that signature, is there some logic that will detect that the return in this case is actually the forth parameter of the underlying method so the interop can do the right thing or is that an effect of PreserveSig=false? Reading docs on PreserveSig it only says it will handle HRESULT and raise exception on failure, and that the method will return void, https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.preservesig?view=net-5.0#remarks, couldn't find anything saying that the return value of the signature will be appended as an ref parameter to underlying call. Don't believe Mono implement PreserveSig at all, and certainly not using that behaviour.

**Comment by jkotas** [comment]
>  is there some logic that will detect that the return in this case is actually the forth parameter of the underlying method so the interop can do the right thing or is that an effect of PreserveSig=false?

It is effect of `PreserveSig=false`. `PreserveSig=false` changes the unmanaged return type to HRESULT and moves the managed return type into an extra unmanaged `out` argument.

**Comment by lateralusX** [comment]
OK, that was what I suspected, then I believe this hits several underlying issues on Mono, first COM is not enabled/supported, and second, Mono doesn't implement the PreserveSig attribute, so above signature will not be adjusted. Is that behaviour of `PreserveSig=false` documented?

**Comment by jkotas** [comment]
Submitted the documentation fix in https://github.com/dotnet/dotnet-api-docs/pull/5303/

**Comment by JeremyKuhne** [comment]
System.Drawing.Common has moved to WinForms.
