### ISSUE TITLE
Consolidate AOT pipeline tasks

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#47756]
It'd be useful to consolidate all Mono AOT related tasks into 1 tool which can run all Mono AOT related work on published input at once. The tool should be able to run them all in parallel as no changes to input files are expected by it. The tool should be wrapped into the configurable task and run after IL linker and before AOT compiler.

We could include all of the following "micro-tasks" and load input assemblies only once.

- IL bodies remover
- pinvoke generator
- icalls generator
- exception filters rewriter

**Comment by lewing** [comment]
Per follow up discussions I think this is better accomplished (especially given the blazor workload requests) with pipeline Targets that are functionally equivalent.  We need to define well known inputs and outputs that on the runtime side that produce functional builds across AOT targets.

**Comment by SamMonoRT** [comment]
@marek-safar @lewing - I don't believe this is strict requirement for 6.0. Can this be moved to 7.0.0 ?

**Comment by SamMonoRT** [comment]
Moving this to 7.0.0

@steveisok - fyi
