### ISSUE TITLE
Questions about System.Diagnostics.Process

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#47764]
Does `System.Diagnostics.Process` have any thread-safe guarantees, or should I assume all members are not thread-safe? Additionally, is calling `Process.Kill` multiple times for the same `Process` safe, or is it only safe to call it once?

**Comment by stephentoub** [comment]
> Does System.Diagnostics.Process have any thread-safe guarantees, or should I assume all members are not thread-safe?

No and yes.  There is some locking in the implementation, but that's to ensure that a consumer's single-threaded access doesn't collide in a bad way with asynchronous callbacks from the implementation.  Only one thread at a time should access a Process object.

> is calling Process.Kill multiple times for the same Process safe

You can call it multiple times.
