### ISSUE TITLE
Support PInvokeStackImbalance MDA for 64-bit platforms

### ISSUE THREAD

**Issue by debruyckere** [dotnet/runtime#47761]
The "PInvokeStackImbalance" Managed Debugging Assistant (MDA) is apparently only supported for 32-bit:
  https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/pinvokestackimbalance-mda

Please consider adding 64-bit support.

**Comment by jkotas** [comment]
The stack imbalance problem is specific to 32-bit x86 calling convention. It does not exist nor it is possible to detect it on other architectures.
