### ISSUE TITLE
Generate asmparse.c using a standard bison/yacc

### ISSUE THREAD

**Issue by kyulee1** [dotnet/runtime#4776]
asmparse.c (for ilasm) is currently prebuilt using an internal version of yacc. 
This also caused many compilations warnings on x-platforms.

**Comment by john-h-k** [comment]
> btyacc can generate an asmparse.cpp that compiles without any other intervention on the grammar or to the other files (as shown in https://github.com/ranma42/coreclr/commit/3dcf6dfd4e18eafbbf0419ee2154ac5427595cbd)

I tried using btyacc, and while it does compile, it doesn't successfully parse a lot of valid IL. It seems there are some differences in the internal tool's grammar interpretation

**Comment by hez2010** [comment]
Any update? I'm trying to do some changes on asmparse.y but immediately hit this issue, because I don't have the Microsoft VCBU Internal YACC to generate asmparse.cpp.

**Comment by TIHan** [comment]
It is a big problem that an internal tool has to be used to generate asmparse.cpp as it means the IL grammar cannot be updated without the help from someone within Microsoft.

@john-h-k perhaps you could share how you integrated `btyacc` - it may only require a few tweaks to the grammar or `btyacc` itself to have it successfully parse, though it is hard to say.

**Comment by Frassle** [comment]
It is _very_ old, but this is a commit from 4 years ago (when this was still coreclr) in my fork to try replacing asmparse.cpp with one built from btyacc, maybe it'll help: https://github.com/Frassle/coreclr/commit/3bb775c1ffbf8371c512237b90e6e8b8796be701

**Comment by john-h-k** [comment]
@TIHan my approach was just some small tweaks to the attempt by @ranma42 [here](https://github.com/ranma42/coreclr/commit/3dcf6dfd4e18eafbbf0419ee2154ac5427595cbd)

**Comment by hez2010** [comment]
mono has a managed implementation of ilasm, maybe we can switch to the managed one and compile it with NativeAOT?

**Comment by kant2002** [comment]
I see some strange thing when try to generate asmparse.cpp using btyacc. 
![image](https://github.com/dotnet/runtime/assets/4257079/bec20c81-68c6-4d5a-8e04-0e49d7602c3f)

This looks a lot like missing changes in Y file. Where
Somewhere in grammar was declared GENCONSTRAINT_ but never made it to git. 
That change was done by @AaronRobinsonMSFT in https://github.com/dotnet/runtime/commit/6be799e5a637545a631ebdee0b4c3e3681ef3bb3

maybe that’s artifact of internal tooling? Can somebody clarify

**Comment by AaronRobinsonMSFT** [comment]
The change in question was more about `BYREFLIKE_`, which seems to remain. I made a few changes and tried several things during development, but don't recall `GENCONSTRAINT_`. I would see if the previous version had it and if not, assume it was simply an artifact of local development that didn't make the cut. The important change in that commit is `BYREFLIKE_`.
