### ISSUE TITLE
Apply DictionaryKeyPolicy to enum keys (and other primitive key types?)

### ISSUE THREAD

**Issue by trueromanus** [dotnet/runtime#47765]
### Description

Example for reproducing issue:
```csharp
    public enum ETestEnum {
        TestValue1 = 1,
        TestValue2 = 2
    };

    public class Info
    {
        public Dictionary<ETestEnum, int> Queue { get; set; }
    }

    public void Main(string[] args) {
            string jsonString = JsonSerializer.Serialize(new Info
            {
                Queue = new Dictionary<ETestEnum, int> { [ETestEnum.TestValue1] = 1 },
            }, new JsonSerializerOptions {
                PropertyNameCaseInsensitive = true,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
                Converters = {
                    new JsonStringEnumConverter(JsonNamingPolicy.CamelCase)
                }
            } );
    }
```
jsonString in result: {"queue":{"**T**estValue1":1}}
jsonString in expected result: {"queue":{"**t**estValue1":1}}

Key name in dictionary not in camel case.  
  
I investigated little bit and find out that **DictionaryKeyPolicy** and **Converters** (in my case JsonStringEnumConverter(JsonNamingPolicy.CamelCase)) don't executing while serialization process.

### Configuration

* Which version of .NET is the code running on? net 5.0.102
* What OS and version, and what distro if applicable? Windows 10 2004
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I don't think so.

### Regression?

I don't know because used Newtonsoft.Json.

**Comment by eiriktsarpalis** [comment]
That seems like a bug to me. @layomia thoughts?

**Comment by layomia** [comment]
cc @Jozkee 

When we designed the feature to support non-string primitives as dictionary keys https://github.com/dotnet/runtime/pull/32676, we elected to keep applying `DictionaryKeyPolicy` to only string keys, as it wasn't clear whether doing so for other types with JSON string representations (`enum`s, `Guid`s, `DateTime` etc.) is a first-class scenario (https://github.com/dotnet/runtime/pull/32909#discussion_r386662860). It's good to see some feedback around this. Enums seem like a reasonable type to apply the policy to. I'm curious what thoughts are around which other types to include.

**Comment by SkiFoD** [comment]
@layomia I made a quick research. In my opinion `enum `is the only type to include.

**Comment by MaceWindu** [comment]
@layomia 

> I'm curious what thoughts are around which other types to include.

E.g. we use `Guid` for dictionary key and with Json.net it was serialized using Guid converter (we use `.ToString("N")` in converter), but `System.Text.Json` just call `ToString` on guid value.

**Comment by yuretz** [comment]
Even if you decide that `DictionaryKeyPolicy` doesn't apply to enum dictionary keys, `JsonStringEnumConverter` with naming policy set to `JsonNamingPolicy.CamelCase` and added to `JsonSerializerOptions.Converters` __shall be used__  for serialization anyway, and it is currently not the case, which is wrong.

**Comment by layomia** [comment]
> but System.Text.Json just call ToString on guid value.

I think this issue is not about what format we write data types with, but about whether to apply the dictionary naming policy to instances of those types when they are dictionary keys. It doesn't seem meaningful to apply something like camelCase policy (as a concrete example) to a guid.

> JsonStringEnumConverter with naming policy set to JsonNamingPolicy.CamelCase and added to JsonSerializerOptions.Converters shall be used for serialization anyway, and it is currently not the case, which is wrong.

From the example from @eiriktsarpalis above, the policy is being applied to the dictionary value as expected.

---

I do think it makes sense to apply the policy to enum keys. It would be a breaking change to do this however, but it might be worth it since the workaround of having a custom converter for the parent dictionary could be cumbersome.

**Comment by layomia** [comment]
Marking this as up-for-grabs. The task is to apply DictionaryKeyPolicy to enum keys on serialization.  I can help with any questions.

**Comment by SkiFoD** [comment]
@layomia Hey, I would like to work on this one.

**Comment by layomia** [comment]
We have an open PR to fix this https://github.com/dotnet/runtime/pull/54429, but it won't block the release if we don't get this functionality in. I'll mark as .NET 7.

**Comment by layomia** [comment]
Fixed by https://github.com/dotnet/runtime/pull/54429.
