### ISSUE TITLE
NetworkInterface.Speed broken on Linux

### ISSUE THREAD

**Issue by chrishamm** [dotnet/runtime#47777]
I am trying to use [NetworkInterface.Speed](https://docs.microsoft.com/de-de/dotnet/api/system.net.networkinformation.networkinterface.speed?view=net-5.0) with .NET 5 on a Raspberry Pi (Raspbian 32-bit). I'm glad it no longer throws an exception like in previous .NET Core versions but it doesn't seem to be working yet for WiFi devices. It always returns 0 for WiFi adapters.

I haven't yet checked if Linux-x64 is affected, too, but I can still do that if it helps.

**Comment by wfurt** [comment]
What `ethtool  -i wlan0` (and ethernet) gives you?

**Comment by chrishamm** [comment]
For WiFi:
```
driver: brcmfmac
version: 7.45.206
firmware-version: 01-88ee44ea
expansion-rom-version:
bus-info: mmc1:0001:1
supports-statistics: no
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

And Ethernet:
```
driver: bcmgenet
version: v2.0
firmware-version:
expansion-rom-version:
bus-info:
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

**Comment by wfurt** [comment]
oops. cut & paste error. can you please run the ethtool _without_ the `-i` flag? That should show speed reported by the driver.

**Comment by chrishamm** [comment]
Ahh thanks for pointing me to `ethtool`, it looks like `ip link` fooled me. It turns out my router had throttled the Ethernet connections to 100MBit so the value was actually correct. I've updated my initial comment.

`ethtool` fails to retrieve further details from the WiFi adapter:

```
Settings for wlan0:
No data available
```

**Comment by wfurt** [comment]
yah. if the driver does not report speed, there is no good way for .NET to know. You can try to ping the community and check if there is perhaps updated driver. 
As last resort, you can try to check `/sys/devices/virtual/net/wlan0/speed`. Doing file IO is not great, but we may consider it if the API call fail.

**Comment by chrishamm** [comment]
Unfortunately that file doesn't exit. I already need to use file IO to get the WiFi signal level from `/proc/net/wireless` but it doesn't provide the current bitrate either. Perhaps it's worth to check out the iwconfig/wavemon sources and to check how they read the network speeds/signals.

**Comment by wfurt** [comment]
it would be best to fix the driver IMHO. I'm going to close this for now as there is not actionable plan and Ethernet works ok.
