### ISSUE TITLE
DoNotDirectlyAwaitATask: Don't report when using JoinableTaskFactory

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#47776]
Yes, it would cover `JoinableTaskFactory.Run` and `JoinableTaskFactory.RunAsync`, plus it would cover cases where the `await` comes after one of these:

```
await JTF.SwitchToMainThreadAsync();
```

```
await TaskScheduler.Default;
```

_Originally posted by @sharwell in https://github.com/dotnet/roslyn/pull/48263#discussion_r499091723_

**Comment by sharwell** [comment]
Also @AArnott

**Comment by AArnott** [comment]
Detecting when JTF applies generally enough to be reliable would be impossible. Further, there are projects that may have a mix of this requirement.
For better predictability, I would suggest we *not* deliver this feature, and instead recommend users configure the severity of this rule to off when in a project where this check is not desirable.

**Comment by stephentoub** [comment]
I consider @AArnott the authority here when it comes to JTF, so I'm going to close this.  Thanks, though!
