### ISSUE TITLE
secp256k1 curve does not wok on MacOS

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#47770]
I am using the secp256k1 curve and it woking fine on Windows & Linux. 
On MacOS, there is an exception: 
```
  Error Message:
    System.PlatformNotSupportedException : The specified curve '1.3.132.0.10' or its parameters are not valid for this platform.
  Stack Trace:
     at System.Security.Cryptography.EccSecurityTransforms.GenerateKey(ECCurve curve)
     at System.Security.Cryptography.ECDsa.ECDsaImplementation.ECDsaSecurityTransforms.GenerateKey(ECCurve curve)
   at System.Security.Cryptography.ECDsa.Create(ECCurve curve)
``` 
The code used, also available on [GitHub](https://github.com/ycrumeyrolle/secp256k1_macos_issue):
``` 
  var crv = ECCurve.CreateFromValue("1.3.132.0.10");
  using ECDsa ecdsa = ECDsa.Create(crv);
```

Is it related to https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography ?

**Comment by vcsjones** [comment]
> On MacOS, there is an exception

MacOS does not support Koblitz secp256k1. Currently, only nistP256 (also known as secP256r1), nistP384, and nistP521 are supported. My most current understanding of the issue is that the macOS platform does not support this ECDSA curve.

**Comment by ycrumeyrolle** [comment]
OK, I misread the documentation at https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#ecdsa 
Thanks!


Elliptic Curve | Windows 10 | Windows 7 - 8.1 | Linux | macOS
-- | -- | -- | -- | --
NIST P-256 (secp256r1) | ✔️ | ✔️ | ✔️ | ✔️
NIST P-384 (secp384r1) | ✔️ | ✔️ | ✔️ | ✔️
NIST P-521 (secp521r1) | ✔️ | ✔️ | ✔️ | ✔️
Brainpool curves (as named curves) | ✔️ | ❌ | ⚠️1 | ❌
Other named curves | ⚠️2 | ❌ | ⚠️1 | ❌
Explicit curves | ✔️ | ❌ | ✔️ | ❌
Export or import as explicit | ✔️ | ❌3 | ✔️ | ❌3
