### ISSUE TITLE
Add a factory method for KeyValuePair utilizing type inference

### ISSUE THREAD

**Issue by kbilsted** [dotnet/runtime#4779]
The `Tuple.Create()` is a generic factory method that works by type inference making it much slicker to create tuples than using the `Tuple<,>`-constructor.

I propose a similar implementation pattern for the KeyValuePair<,> type. Hence something a long the lines of

```
public static class KeyValuePair
{
    public static KeyValuePair<TKey, TValue> Create<TKey, TValue>(TKey key, TValue value)
    {
         return new KeyValuePair<TKey, TValue>(key, value);
    }
}
```

**Comment by joperezr** [comment]
In order to consider this we need an actual Api Proposal so we can move it forward.

**Comment by kbilsted** [comment]
@joperezr  thanks for getting back. 

What is it you need more than the above explanation? Do I need to fill out a template? The code above is the whole code to include

**Comment by joperezr** [comment]
first of all sorry it took so long to look at this, it got missed somehow. Usually ApiProposals have the following template: https://github.com/dotnet/runtime/blob/master/.github/ISSUE_TEMPLATE/02_api_proposal.md.

Here is a good set of steps we have with good examples of how a good API proposal looks like as well as what is the general process of it: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md#steps

Let me know if you have any questions around it.

**Comment by GrabYourPitchforks** [comment]
Is this obviated by the C# [target typed new feature](https://devblogs.microsoft.com/dotnet/welcome-to-c-9-0/#target-typed-new-expressions)?

```cs
using System.Collections.Generic;

public class C {
    public static KeyValuePair<string, int> M() {
        return new("hello", 42);
    }
}
```

**Comment by stephentoub** [comment]
This API already exists:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair.create?view=net-5.0
