### ISSUE TITLE
.NET 5: Suggestion: Improve some aspects of mixed (Native + .NET) solutions 

### ISSUE THREAD

**Issue by DynConcepts** [dotnet/runtime#47815]

**Comment by DynConcepts** [comment]
The first example would be handling of missing NATIVE DLL's. Right now there is no indication of the missing file name in the exception message in .NET 4.7 0 yet the information is likely available as Native applications do display it (I am presuming the low level Native code is the same and that it is the handling of the exception that differs....

There is a major about of mixed code in existance, and much of my company's work (ever increasing %) is about solutiions in this area.

**Comment by DynConcepts** [comment]
Could not find "best" area label... I think "area-Interop-coreclr" would be appropriate, but could not figure out how to add it post issue creation.

**Comment by AaronRobinsonMSFT** [comment]
@DynConcepts Can you elaborate on your issues a bit more. I'm not clear as to why the suggestion is as the title is a bit vague.

**Comment by AaronRobinsonMSFT** [comment]
Closing due to lack of information.
