### ISSUE TITLE
Odd behaviour calling HttpWebRequest multiple times

### ISSUE THREAD

**Issue by maxima120** [dotnet/runtime#47824]
I need to understand whether it's a bug or a feature.

I send 3 HttpWebRequest from .net 5.0.2 console app to the same host in this fashion:

- get /fake.file (receive 404 as expected)
- sleep 500ms
- get /good.file
- sleep 500ms
- get /good.file 

First takes 600ms, second takes 300ms and third 50ms.

I understand first stalls on jit and WebException handling. That's fine. 

However I cannot reconcile the rest. 

When I look with profiler 2nd request calls name resolve method and 3rd doesn't which accounts for around 250ms difference. 

So I figured the dns name resolution is cached for a little while (I think for around 10sec at least).

Seems reasonable. 

My question here is - why doesn't 2nd request pick up dns cache from 1st request? They both are made to the same host well inside 10sec tolerance interval? 

It's not some sort of quirky exercise. I actually have a task to get a Web resource which doesn't exist until last second. And I want to warm up the app which retrieves it - both jit/optimisation and dns cache. 

Need an expert advice please 
![image](https://user-images.githubusercontent.com/10121753/105645909-f7c93580-5e9c-11eb-9386-c4e5ea16f56b.png)

*P.S. I also tried this `ServicePointManager.DnsRefreshTimeout = 30000;` and it didnt help.*

**P.P.S. The host is behind Amazon Cloud Front - could it affect dns caching behaviour?**

**Comment by karelz** [comment]
@maxima120 are you able to reproduce it on local environment? Or does it happen only behind Amazon Cloud Front?
If you can reproduce it also locally, please post a repro that anyone can run and debug.

You can try to minimize the repro by calling directly `System.Net.Dns.GetHostAddresses`. If that shows the same characteristics, then it is OS specific DNS caching behavior we cannot influence from our networking stack. If that's the case, you may try to resolve DNS manually, or warm up DNS resolution separately in specific environments based on their guidance.

**Comment by maxima120** [comment]
its the other way around. This happens on any machine but when i try to access specific websites (not only amazon but also akamai and perhaps more - in these 2 cases I cannot use direct IP address for http/https request - they return 302 instead. if i call it by dns name it works - there are multiple redirections it seems, including jumping from http to https and back to http for example - my networking knowledge cant cope with it).

**Comment by wfurt** [comment]
note that if you use IP address in URI, you should set `Host` header in the request @maxima120.
