### ISSUE TITLE
dotnet-sdk-3.1 installation fails on SLES 12: cpio: read failed - No such file or directory

### ISSUE THREAD

**Issue by shunlir** [dotnet/runtime#47822]
md5sum /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-runtime-3.1.11-x64.rpm 
97d0a60f4d2fa5d999aca68068d6ea66  /var/cache/zypp/packages/packages-microsoft-com-prod/dotnet-runtime-3.1.11-x64.rpm

zypper install dotnet-sdk-3.1
Refreshing service 'SUSE_Linux_Enterprise_Server_12_SP5_x86_64'.
Refreshing service 'SUSE_Linux_Enterprise_Software_Development_Kit_12_SP5_x86_64'.
Refreshing service 'container-suseconnect-zypp'.
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 3 NEW packages are going to be installed:
  aspnetcore-runtime-3.1 dotnet-runtime-3.1 dotnet-sdk-3.1

The following 3 packages have no support information from their vendor:
  aspnetcore-runtime-3.1 dotnet-runtime-3.1 dotnet-sdk-3.1

3 new packages to install.
Overall download size: 799.9 KiB. Already cached: 17.5 MiB. After the operation, additional 273.9 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package dotnet-runtime-3.1-3.1.11-1.x86_64                                                                                                 (1/3), 799.9 KiB ( 72.8 MiB unpacked)
Retrieving: dotnet-runtime-3.1.11-x64.rpm .............................................................................................................................[done (447.6 KiB/s)]
In cache aspnetcore-runtime-3.1.11-x64.rpm                                                                                                            (2/3),   7.5 MiB ( 17.0 MiB unpacked)
In cache dotnet-sdk-3.1.405-x64.rpm                                                                                                                   (3/3),  10.0 MiB (184.1 MiB unpacked)

Checking for file conflicts: ........................................................................................................................................................[done]
(1/3) Installing: dotnet-runtime-3.1-3.1.11-1.x86_64 ...............................................................................................................................[error]
Installation of dotnet-runtime-3.1-3.1.11-1.x86_64 failed:
**Error: Subprocess failed. Error: RPM failed: error: unpacking of archive failed on file /usr/share/dotnet/shared/Microsoft.NETCore.App/3.1.11/Microsoft.VisualBasic.Core.dll;60003c3b: cpio: read failed - No such file or directory**
error: dotnet-runtime-3.1-3.1.11-1.x86_64: install failed

**PS**: dotnet-sdk-5.0 installation succeeded in the same environment.

**Comment by NikolaMilosavljevic** [comment]
@shunlir can you try the following command and share the output - it will help us determine if there is a potentially bad mirror?

```wget https://packages.microsoft.com/sles/12/prod/dotnet-runtime-3.1.11-x64.rpm```

Here's what I get on my machine:

```
--2021-02-11 18:02:08--  https://packages.microsoft.com/sles/12/prod/dotnet-runtime-3.1.11-x64.rpm
Resolving packages.microsoft.com (packages.microsoft.com)... 13.93.224.173
Connecting to packages.microsoft.com (packages.microsoft.com)|13.93.224.173|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30074114 (29M) [application/x-redhat-package-manager]
Saving to: 'dotnet-runtime-3.1.11-x64.rpm'

100%[=================================================================================>] 30,074,114  8.53MB/s   in 3.6s

2021-02-11 18:02:12 (8.03 MB/s) - 'dotnet-runtime-3.1.11-x64.rpm' saved [30074114/30074114]
```

**Comment by NikolaMilosavljevic** [comment]
[Triage] we could not reproduce this issue. Let us know if this is still reproing for you and provide the info about mirror IP using the command shared above.
