### ISSUE TITLE
JIT and JIT.Directed tests timeout/hang on Android arm64 devices

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#47850]
This started recently, all of the runs in the last 24 hours of these two workitems timed out.

The JIT and JIT.Directed are the most common ones but there are also occasional timeouts of other runtime tests.

Example Kusto query:
```
WorkItems
| where QueueName == "windows.10.amd64.android.open" and Queued >= ago(3d) and not(FriendlyName startswith "System" or FriendlyName startswith "Microsoft" or FriendlyName startswith "Common")
| summarize BadExit=countif(Status == "BadExit"), Fail=countif(Status == "Fail"), Pass=countif(Status == "Pass"), Timeout=countif(Status == "Timeout") by FriendlyName
| order by Timeout desc
```

![image](https://user-images.githubusercontent.com/1376924/106906843-df0f1a00-66fd-11eb-93a1-6969e5836e85.png)

**Comment by SamMonoRT** [comment]
@fanyang-mono - can you investigate :  Hopefully this isn't an actual regression, and also hoping it is not an unwanted effect of the changes done by fixing https://github.com/dotnet/xharness/issues/397 ?
