### ISSUE TITLE
Experiment with icu4x usage for wasm

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#47875]
[icu4x](https://github.com/unicode-org/icu4x) is an ICU implementation targeting WebAssembly that is intended to be modular and flexible. There is a chance that it could offer size or performance benefits over icu4c, and as the library matures experimenting with using it could be valuable.

Before attempting to implement this in full, we would need to:
- [ ] Identify whether the ICU APIs we call right now are implemented in icu4x or what the gap is (list of functions we use [here](https://github.com/dotnet/runtime/blob/master/src/libraries/Native/Unix/System.Globalization.Native/pal_icushim_internal.h#L56))
- [x] Call into a Rust library from Mono wasm

Also of note: icu4x is _not_ targeting full `no_std` compatibility for now, see https://github.com/unicode-org/icu4x/issues/77

**Comment by lambdageek** [comment]
Since https://github.com/unicode-org/icu4x/pull/911 icu4x builds with `no_std`.  Also they recently hit 1.0.0-beta1 https://crates.io/crates/icu/1.0.0-beta1

It's worth revisiting this

**Comment by tarekgh** [comment]
@Lambdageek yes, it is worth trying in the next cycle.

**Comment by naricc** [comment]
I plan to take a look at this in the November time frame.

**Comment by SamMonoRT** [comment]
We are going to consider this as a future project. Closing this issue.
