### ISSUE TITLE
[Wasm][AOT] Interlocked.CompareExchange: not enough values (0 < 1) on stack at 0000

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#47887]
### Description

Failure running the console sample app.

### Repro
- `~/runtime/src/mono/wasm$ make provision-wasm; make build-all`
- edit `src/mono/netcore/sample/wasm/console/Makefile` to add `override MSBUILD_ARGS+=/p:RunAOTCompilation=true /p:AOTProfilePath=$(PROFILE_PATH) /bl`
- copy `profile.aot` to the console folder (https://github.com/jeromelaban/Wasm.Samples/blob/abde54c5b70aa44a68208aeaea12fceee02c7643/Bug47334/Bug47334/aot.profile)
- run `make clean; make PROFILE_PATH=``pwd``/aot.profile`
- run `make run`

The following error happens:
```
~/runtime/src/mono/netcore/sample/wasm/console$ make run
cd bin/Release/AppBundle && ~/.jsvu/v8 --expose_wasm runtime.js --  --run Wasm.Console.Sample.dll
Arguments: --run,Wasm.Console.Sample.dll
console.debug: MONO_WASM: Initializing mono runtime
console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
Initializing.....
/home/jay/runtime/src/mono/mono/mini/interp/transform.c:4623 <disabled>
/home/jay/runtime/src/mono/mono/mini/interp/transform.c:4623 <disabled>
JS exception: RuntimeError: memory access out of bounds
RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[8175]:0x15636a
    at <anonymous>:wasm-function[8095]:0x1518a5
    at <anonymous>:wasm-function[10653]:0x1ad76d
    at <anonymous>:wasm-function[1768]:0x35358
    at <anonymous>:wasm-function[5763]:0xe1d63
    at <anonymous>:wasm-function[2260]:0x47002
    at <anonymous>:wasm-function[366]:0xbc48
    at <anonymous>:wasm-function[8156]:0x1559ad
    at <anonymous>:wasm-function[6032]:0xf6702
    at invoke_iiiii (dotnet.js:1:246630)
../wasm.mk:30: recipe for target 'run-console' failed
```

### Configuration

Linux or macOS

Commit fabaed296fd1b75b89fcfb5808a539d551da4b95

### Regression?

yes

**Comment by BrzVlad** [comment]
Maybe I'm doing something wrong but it doesn't crash for me

**Comment by jeromelaban** [comment]
@BrzVlad are you seeing the text "hello world" world showing up ?

**Comment by BrzVlad** [comment]
Scratch that. I somehow was ending in interp only mode. After I recompiled more carefully, I can reproduce.

**Comment by BrzVlad** [comment]
This doesn't look like interp related issue. The crash happens because interp is executing a method with invalid IL (which has a single ret, I'm guessing the linker removed the code).  However, the compiled code for Main cannot be found in dotnet.wasm either.

**Comment by jeromelaban** [comment]
I've re-validated with 9195df699fe25d2e752c2bc350c16dc199f02f7a, the runtime error is still valid.

**Comment by jeromelaban** [comment]
@BrzVlad the error does not happen anymore when disabling the linker with :

```
<WasmStripAOTAssemblies>false</WasmStripAOTAssemblies>
```

It's likely to not happen during CI because setting `ArchiveTests` disables the linker:
https://github.com/dotnet/runtime/blob/2e36f1b3a81a2d43d0c0d3597a7ead1bcda35a27/src/mono/wasm/build/WasmApp.targets#L115

**Comment by lewing** [comment]
mono-cil-strip is different from il linking and is not at all safe to use in AotInterp mode right now.  We're planning to work on a replacement but do not combine WasmStripAOTAssemblies with AOTMode.AotInterp right now.

**Comment by jeromelaban** [comment]
This issue was fixed by https://github.com/dotnet/runtime/pull/48184
