### ISSUE TITLE
API Proposal: More performant overloads for Graphics.GetContextInfo

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#47880]
## Background and Motivation

`Graphics.GetContextInfo` exists to allow WinForms to apply cumulative Graphics transform translation and clipping to the underlying HDC so that rendering via GDI has similar output. This method currently returns an `object` array of `[ Region, Matrix ]`.  (Note that the `Matrix` is the current `Transform` with _only_ the cumulative offset applied.)

This API is called many times during rendering of WinForms applications. Avoiding the array allocation would make a _significant_ difference in rendering allocations. A **much** greater allocation reduction would be obtained if `Graphics` tracked if the `.Clip` and `.Transform` setters are ever accessed to allow an early out in the method logic.

WinForms also don't always need both values. System.Drawing can't calculate the clipping region without the offset, but it can calculate the offset without the `Region`. Making the `Region` optional will save significant overhead.

In .NET 5.0 we added a lot of logic to WinForms to try and track and avoid getting this data. Tracking the "dirty" state in System.Drawing covers far more scenarios and allows significantly simpler code in WinForms.

## Proposed API

```diff
namespace System.Drawing
{
    public sealed class Graphics
    {
         public object GetContextInfo();
+        public void GetContextInfo(out PointF offset);
+        public void GetContextInfo(out PointF offset, out Region clip);
    }
}
```

- `out Region clip` would return `null` when `Clip` and `Transform` have never been set.
- `out Region clip` would return `null` if the cumulative region ends up `.IsInfinite()` (meaningless)
- `out Point offset` will return an empty (default) `PointF` when `Transform` has never been set.
- existing `GetContextInfo` behavior won't change for compat

## Usage Examples

The existing method is used in WinForms [here](https://github.com/dotnet/winforms/blob/2178e7a66ed27332202659c3ea86649dc4578c3d/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs#L149).

## Risks

If we missed a case where early out is inappropriate we'd have to adjust for that, but that is an internal detail.

## More Details

- GDI+ "layers" its clip and transform on top of the underlying GDI HDC. So a newly created Graphics object always has an infinite clip and identity matrix.
- Restriction to translation in the Matrix is probably due to lack of Win9x support for rotation (not positive).

cc: @RussKie @merriemcgaw

**Comment by safern** [comment]
We've previously discussed this offline and makes sense, the current `GetContextInfo` is pretty expensive.

**Comment by tannergooding** [comment]
Is returning via `out` preferred to returning a `value tuple` here?

**Comment by safern** [comment]
> Is returning via out preferred to returning a value tuple here?

You mean an `out value tuple`? We wouldn't be able to add a parameter-less overload that returns a `value tuple` as that conflicts with the existing override.

**Comment by tannergooding** [comment]
> You mean an out value tuple? We wouldn't be able to add a parameter-less overload that returns a value tuple as that conflicts with the existing override.

Right, although I imagine we could also something like:
* have a different overload
* have something like `T GetContextInfo<T>() where T : struct` and then specialize based on what info we need
* have explicit `Point GetContextOffset` and `Region GetContextClip`

I think the most interesting thing here is that `GetContextInfo` returned `object` so that we could have public surface area while also having that info be "opaque".
Having these new methods means that the context info is no longer opaque and so it might be worth exposing that info slightly differently or via a proper struct if we expect it might change in the future.

**Comment by safern** [comment]
I think I like that idea better and might be more extensible.

@JeremyKuhne thoughts?

**Comment by JeremyKuhne** [comment]
I updated the proposal from `Point` to `PointF` as that is what is currently returned (whoops).

The `Region` depends on calculating the offset so having separate methods would defeat the performance need here when we need both (which is often).

I'm unclear about the value of being open-ended as `GraphicsContext` only has these two properties (PointF and Region). I suspect the likelihood of ever adding anything else to this is pretty small. We _might_ want to expose the internal "changed" flags to allow for optimizing getting _only_ the current `Clip` and `Transform` by having a flag here? That said, a quick look through the WinForms runtime I don't see where we'd leverage that currently.

**Comment by JeremyKuhne** [comment]
Tagging #47940  as it is somewhat related.

**Comment by terrajobst** [comment]
* The existing `GetContextInfo()` is hidden from IntelliSense. We should mark it as `[Obsolete]` and point people to the new APIs, at the off chance that someone is using the old one.
* Otherwise, looks good.

```C#
namespace System.Drawing
{
    public sealed class Graphics
    {
        [Obsolete("Use one of the other overloads.")]
        public object GetContextInfo();
        public void GetContextInfo(out PointF offset);
        public void GetContextInfo(out PointF offset, out Region clip);
    }
}
```

**Comment by stephentoub** [comment]
Should this issue be closed now?

**Comment by safern** [comment]
Yeah. Thanks, @stephentoub
