### ISSUE TITLE
[Debugger] ICorDebugGCReferenceEnum is inconsistent

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/runtime#47896]
### Description

Repro:
For a dump file (`\\vsdbgqa\dumps\gaurav\good\Lock contention pattern.dmp`), enumerate GC roots through ICorDebugGCReferenceEnum, twice (after the first completes, create another ICorDebugGCReferenceEnum and repeat the process). 

### Expected:
Successive runs of the same API on a dump should return same results.

### Observed:
The number of roots returned the first time doesn't match the successive attempts.

### Configuration

.NET Framework 4.5+, .NET Core, all arch

### Regression?

Not a regression.

### Other information

I'm fairly sure this is due to https://github.com/dotnet/runtime/issues/47895, no workaround that I could find.

**Comment by tommcdon** [comment]
Tracking this issue via #47895
