### ISSUE TITLE
Auto click event in specific coordinate

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#47908]
How to create an cross platform auto click event at specific coordinate like Mouse/Touch.Click(float x,float y,clicktype ggg)??????
Please implement the function in .net 5

**Comment by huoyaoyuan** [comment]
.NET BCL doesn't have any logic/concept of mouse.
This is considerably easy to implement anywhere, but there's no suitable location in first party code for it.

**Comment by Barshan-Mandal** [comment]
But please add this api  in .net bcl

**Comment by huoyaoyuan** [comment]
No way. Although it is called "easy", it's involving much more things than you may think.
For example, on Windows, you must specify a receiver window when sending mouse events to other program. This will require knowledge of "window" first.

BCL isn't **for this**. It's "cross-platform", but it's not for any thing that has definition on more than one platform. "Mouse click" is a very high-level concept in overall programming.

**Comment by krwq** [comment]
@Barshan-Mandal BCL is not a place for utilities like this. Also there are problems like: how would this work when there is no UI? I'm closing this as "won't fix"
