### ISSUE TITLE
Very slow startup of dotnet app in linux container (> 3 seconds)

### ISSUE THREAD

**Issue by RalfMengwasser-ITEM** [dotnet/runtime#47902]
I have a simple .NET5 app that I have compiled into a docker container.

The app is published as linux-x64, Release, net5.0.

Then put into this container:

FROM mcr.microsoft.com/dotnet/runtime:5.0

(I also tried the SDK container, but it doesnt improve the performance.)

The container is running under Kubernetes in Azure (but I also have the same problem running in local linux docker).

The pod is run under a pretty fast VM, so I dont expect that to have an influence on performance. There also is no limit on the pod.

I now go into the pod and start my app with:

dotnet app.dll

And it takes more than 3 seconds to execute the first line of the program, which is:

static int Main(string[] args)
{
    Console.WriteLine("Hello world!");
}

If I just execute the dotnet command (by typing 'dotnet') by itself, its instantly executed.

If I execute the same app under windows, its also instantly executed.

I also disabled all telemetry.

So how can it be THAT slow?

Its literally stopping the app from being any useful, because it is supposed to be run once per second. Which of course is impossible if it needs 3 seconds to even start up.

I mean, I must be doing something incredibly wrong, because even a full compile is faster that that startup time.

The whole apps execution time should be <5ms, how can it go up to >3000ms to even start? Thats beyond what I ever believed possible.

Please help. ;)

**Comment by mangod9** [comment]
Hi @RalfMengwasser-ITEM, does the issue reproduce with a simple "dotnet new console" app, or is it specific to something within your app.

**Comment by mangod9** [comment]
adding @billwert @sebastienros as fyi.

**Comment by sebastienros** [comment]
Can you record a trace using dotnet-trace? It can launch the application by itself in order to measure what's happening from startup.
Can you share the application with us otherwise?

**Comment by RalfMengwasser-ITEM** [comment]
This IS now the complete program:

static int Main(string[] args)
{
Console.WriteLine("Hello world!");
}

There isnt anything to trace. We are talking about the startup... the time from hitting enter in the console until the code executes.

**Comment by RalfMengwasser-ITEM** [comment]
I now have the same problem running an app under an ARM MCU.

I think the general problem is that the startup of dotnet takes way too many ressources.

I tried the "dotnet new console" and the command itself took a few seconds of time on a normal desktop linux machine, but it took ~30 seconds in a container and on the MCU I actually thought it crashed and stopped it after a while. On next try it took ~60 seconds.

So what I see happening... if the CPU (and maybe RAM) is rather low on the system, the time to start rises up exponentially, not in a linear fashion.

Seriously, there shouldnt ANYTHING be done on start of dotnet that doesnt DEFINITELY have to be done. Cut all the crap... telemetry, other useless stuff. The startup time is very important.

**Comment by sebastienros** [comment]
> This IS now the complete program

Sorry, didn't realize.

@richlander You have some experience of dotnet in Docker and MCUs, do you experience the same startup times?

@RalfMengwasser-ITEM to be specific, can you share the Azure VM size and image type you are using. Also what specific MCU in case @richlander has used the same one already? I will test on Azure to confirm what you are experiencing at least, and if I see the same thing take the traces to understand where the time is spent.

**Comment by RalfMengwasser-ITEM** [comment]
The MCU is ATSAMA5D27. 500 MHz.

The container was on an Azure :

Standard_D4_v4 | 4core | 16gb

The container itself was not restricted, and there wasnt really much load on that VM overall.

The only thing thats a bit fishy about the OS of the MCU that it runs on is the following messages on start:

# dotnet app.dll
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)
dotnet: /lib/libstdc++.so.6: no version information available (required by dotnet)

**Comment by mangod9** [comment]
So just to clarify you are seeing the slow startup on a normal docker container running on a Standard_D4 VM within Azure, with no specific constraints on the container itself?

**Comment by mangod9** [comment]
Hi @RalfMengwasser-ITEM, are you still observing the slow startup on 5.0? We havent seen any such delays in our regular perf validation.

**Comment by mangod9** [comment]
Closing the issue for now, please reactivate if the behavior persists for certain scenarios.
