### ISSUE TITLE
Question about using StructLayoutAttribute.Pack on reference types

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#47907]
Does `StructLayoutAttribute.Pack` have any effect on the alignment of the fields of a `class` in managed memory? I haven't been able to come up with an example where I can actually observe a difference between setting and not setting `Pack`. If there actually is a difference, I would appreciate advice on how to see it in managed memory.

**Comment by WizardBrony** [comment]
@jkotas I have continued experimenting with my example and I realized that the reason I was not seeing the results I was expecting was because the allocated managed memory for reference types (including `class`es and boxed `struct`s) is padded to the next pointer-size boundary. So I guess now knowing that, my follow-up question would be what is the rationale for padding `class`es and boxed `struct`s to the next pointer-size but not arrays? Also please let me know if you would like me to open a separate issue to cover this question instead.

**Comment by jkotas** [comment]
> why is TryGetRawMetadata an extension?

I guess it is some combination of:
- Assembly is abstract base-class. Adding virtual instance methods to it that only work for the runtime-provided Assemblies and throw otherwise is less than ideal.
- Rarely used API, for advanced users only. Having it will System.Reflection.Metadata will hide it for ordinary reflection users.
- It helped with .NET Standard 1.x era API and contract versioning gymnastics
The first two reasons are still valid.

**Comment by jkotas** [comment]
Could you please share the examples you are experimenting with, the behavior you are observing, and the behavior that you would expect?

**Comment by WizardBrony** [comment]
I just have some test code that instantiates some `class`es and `struct`s with different fields and `StructLayout`s, then I'm launching it and examining the managed heap with SOS. I guess I don't have any expected behavior. At this point all I'm wondering is what the rationale is for pointer-size padding `class`es and boxed `struct`s and not arrays. I have been searching many places including The BotR and just can't find any explanation.

**Comment by jkotas** [comment]
There are number of reasons why you may see padding.

For example, `class MyInt { int x; }` is padded to `MIN_OBJECT_SIZE` on GC heap to ensure that it can be always replaced by the special free object once it becomes garbage. It is necessary to [keep the GC heap crawlable at all times](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/garbage-collection.md#design-of-allocator).

Does this match the kind of padding you are seeing?

**Comment by WizardBrony** [comment]
@jkotas Not really. Here's an example on my 64-bit machine:

```c#
class MyClass { private byte b; }
```

On the managed heap, the size of the object created when instantiating this `class` is 24 bytes:

8 bytes (Object Header)
8 bytes (Method Table Ptr)
1 byte (b)
**7 bytes (padding)**

Because I'm on a 64-bit machine, the runtime is padding the object by 7 bytes to get the total size on an 8-byte boundary. To demonstrate this, I can change from a `byte` to a `long`:

```c#
class MyClass { private long l; }
```

and the size of the resulting object on the managed heap is still 24 bytes:

8 bytes (Object Header)
8 bytes (Method Table Ptr)
8 bytes (l)
**0 bytes (padding)**

And then if I add one more byte:

```c#
class MyClass { private long l; private byte b; }
```

 it gets bumped up to the next pointer-size boundary, which is 32 bytes:

8 bytes (Object Header)
8 bytes (Method Table Ptr)
8 bytes (l)
1 byte (b)
**7 bytes (padding)**

I see similar behavior for a boxed `struct`. However, for an array of `struct`s, there doesn't appear to be any padding. For instance, in the following example `myArray` references an array on the managed heap that is (according to SOS) **25 bytes**:

```c#
struct MyStruct { private byte b; }
var myArray = new MyStruct[1] {new MyStruct()};
```

Adding a single byte to the `struct` results in an array that is also a single byte larger:

```c#
struct MyStruct { private byte b; private byte b2; }
var myArray = new MyStruct[1] {new MyStruct()};
```

**26 bytes**, which implies no padding is being performed, and that the array object is not on a pointer-size boundary. Considering this array is also a managed reference type, I'm wondering what the rationale is for pointer-size padding `class`es and boxed `struct`s but not arrays.

**Comment by jkotas** [comment]
> references an array on the managed heap that is (according to SOS) 25 bytes:

The space for arrays on GCHeap is padded to pointer size as well. The padding for arrays happens via different path than for objects and it is why SOS reports one but not the other; the result is the same in both cases.

The padding is required to have start of the object aligned at pointer boundary. This is required for both correctness (misaligned memory access would not be always atomic) and performance (misaligned memory access would be slower).

**Comment by WizardBrony** [comment]
> The space for arrays on GCHeap is padded to pointer size as well. The padding for arrays happens via different path than for objects and it is why SOS reports one but not the other; the result is the same in both cases.

@jkotas Thank you very much for explaining that. I will trust that arrays are padded as well even though SOS says otherwise.

I actually have one more question related to the original issue topic. The documentation for `StructLayoutAttribute.Pack` states the following:

> The fields of a type instance are aligned by using the following rules:
> ...
> - Each field must align with fields of its own size (1, 2, 4, 8, etc., bytes) or the alignment of the type, whichever is smaller.... For example, even if the largest field in a type is a 64-bit (8-byte) integer or the Pack field is set to 8, Byte fields align on 1-byte boundaries, Int16 fields align on 2-byte boundaries, and Int32 fields align on 4-byte boundaries.

[StructLayoutAttribute.Pack Field](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=net-5.0#remarks)

Is this referring to the rules for _default_ alignment, or are these the overall rules for _valid_ alignment? For example, if for whatever reason I have:

```c#
[StructLayout(LayoutKind.Explicit)]
class MyClass
{
    [FieldOffset(3)]
    public int I1;
    [FieldOffset(7)]
    public int I2;
}
```

even though I can:

```c#
var myClass = new MyClass {I1 = 0, I2 = -1};
Assert.AreEqual(0, myClass.I1);
Assert.AreEqual(-1, myClass.I2);
```

is this technically undefined behavior, or is the alignment valid and just not what the runtime would do by default?

**Comment by jkotas** [comment]
You example is valid non-portable code. It may not work correctly on platforms that require strict alignment or on platforms with different endianness.

**Comment by WizardBrony** [comment]
@jkotas That makes perfect sense. One last question for now. What exactly does `StructLayoutAttribute.Pack` do when using `LayoutKind.Explicit`? For instance in my last example:

```c#
[StructLayout(LayoutKind.Explicit, Pack = 1)]
class MyClass
{
    [FieldOffset(3)]
    public int I1;
    [FieldOffset(7)]
    public int I2;
}
```

Does setting `Pack` actually do anything to the layout, the way the memory is accessed, or anything else at runtime?

**Comment by jkotas** [comment]
Right, `Pack` should not have any affect in combination with `LayoutKind.Explicit`.

**Comment by WizardBrony** [comment]
@jkotas Thank you so much for clarifying that. If that's the case, do you know what this statement in the documentation for `StructLayoutAttribute.Pack` could be referring to, or is the documentation just wrong?

> The Pack field controls the alignment of a type's fields in memory. It affects both LayoutKind.Sequential and LayoutKind.Explicit.

[StructLayoutAttribute.Pack Field](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=net-5.0#remarks)

**Comment by jkotas** [comment]
I do not know.

**Comment by WizardBrony** [comment]
@jkotas Thank you very much for your time.
