### ISSUE TITLE
Annotate APIs throwing PNSE on Android

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#47911]
All public APIs that throw PNSE needs to be annotated with System.Runtime.Versioning.UnsupportedOSPlatformAttribute.

**Comment by MaximLipnin** [comment]
This is a list of the library tests (thanks to @mdh1418) which fail with PNSE on Android:
```
System.Net.NetworkInformation.Functional.Tests
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_NotListening
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)

System.Net.Primitives.Functional.Tests
System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: Packet)
System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: ControllerAreaNetwork)

System.Console.Tests
CancelKeyPressTests.CanAddAndRemoveHandler
ReadAndWrite.OutputEncodingPreamble
ReadAndWrite.ReadAndReadLine
ReadAndWrite.OutputEncoding
SetIn.SetInReadLine
SetIn.SetInThrowsOnNull
Color.RoundtrippingColor
Color.RedirectedOutputDoesNotUseAnsiSequences
Color.InvalidColors
ConsoleEncoding.TestEncoding(inputString: \"This string has non ascii characters Î±ÃŸÎ“Ï€Î£ÏƒÂµ\")
ConsoleEncoding.TestEncoding(inputString: \"\\xd800\")
ConsoleEncoding.TestEncoding(inputString: \"This is Ascii string\")
ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)
ConsoleEncoding.TestEncoding(inputString: \"This is string have surrogates ğ€€\")
ConsoleEncoding.TestValidEncodings
SyncTextReader.ReadAsync
SyncTextReader.ReadBlockAsync
SyncTextReader.ReadLineAsync
SyncTextReader.Read
SyncTextReader.ReadToEnd
SyncTextReader.ReadBlock
SyncTextReader.Peek
SyncTextReader.ReadToEndAsync
TimeOut.OpenStandardXXX_ReadTimeOut
TimeOut.OpenStandardXXX_WriteTimeOut
TimeOut.OpenStandardXXX_CanTimeOut
ThreadSafety.SetStandardXXXCanBeCalledConcurrently
ThreadSafety.ReadMayBeCalledConcurrently
ThreadSafety.OpenStandardXXXCanBeCalledConcurrently
WindowAndCursorProps.GetCursorPosition_Invoke_ReturnsExpected
WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: False)
WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: True)
WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
WindowAndCursorProps.LargestWindowHeight_UnixGet_ReturnsExpected
WindowAndCursorProps.WindowHeight_GetUnix_Success
WindowAndCursorProps.WindowWidth_GetUnix_Success
WindowAndCursorProps.BufferWidth_GetUnix_ReturnsWindowWidth
WindowAndCursorProps.SetCursorPosition_Invoke_Success
WindowAndCursorProps.CursorSize_GetUnix_ReturnsExpected
WindowAndCursorProps.LargestWindowWidth_UnixGet_ReturnsExpected
WindowAndCursorProps.BufferHeight_GetUnix_ReturnsWindowHeight
WindowAndCursorProps.CursorTop_Set_GetReturnsExpected
WindowAndCursorProps.CursorLeft_Set_GetReturnsExpected
```
It can be helpful for annotating the unsupported APIs.

**Comment by marek-safar** [comment]
The list looks reasonable perhaps except `SocketAddressTest.ToString_UnsupportedFamily_Throws`. I think ToString in general should never throw so that might need general fix.

**Comment by MaximLipnin** [comment]
If we don't have any other issue where the PNSE-throwing APIs are listed, then this issue can be closed as resolved.

**Comment by MaximLipnin** [comment]
> This is a list of the library tests (thanks to @mdh1418) which fail with PNSE on Android:
> 
> ```
> System.Net.NetworkInformation.Functional.Tests
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: 127.0.0.1)
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_Succeed(address: ::1)
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_AccessAllMethods_NoErrors
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpActiveConnections_NotListening
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: 127.0.0.1)
> System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_TcpListeners_Succeed(address: ::1)
> 
> System.Net.Primitives.Functional.Tests
> System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: Packet)
> System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: ControllerAreaNetwork)
> 
> System.Console.Tests
> CancelKeyPressTests.CanAddAndRemoveHandler
> ReadAndWrite.OutputEncodingPreamble
> ReadAndWrite.ReadAndReadLine
> ReadAndWrite.OutputEncoding
> SetIn.SetInReadLine
> SetIn.SetInThrowsOnNull
> Color.RoundtrippingColor
> Color.RedirectedOutputDoesNotUseAnsiSequences
> Color.InvalidColors
> ConsoleEncoding.TestEncoding(inputString: \"This string has non ascii characters Î±ÃŸÎ“Ï€Î£ÏƒÂµ\")
> ConsoleEncoding.TestEncoding(inputString: \"\\xd800\")
> ConsoleEncoding.TestEncoding(inputString: \"This is Ascii string\")
> ConsoleEncoding.TestEncoding(inputString: \"This string has invalid surrogates \\xd800\\xd800\\xd\"...)
> ConsoleEncoding.TestEncoding(inputString: \"This is string have surrogates ğ�€€\")
> ConsoleEncoding.TestValidEncodings
> SyncTextReader.ReadAsync
> SyncTextReader.ReadBlockAsync
> SyncTextReader.ReadLineAsync
> SyncTextReader.Read
> SyncTextReader.ReadToEnd
> SyncTextReader.ReadBlock
> SyncTextReader.Peek
> SyncTextReader.ReadToEndAsync
> TimeOut.OpenStandardXXX_ReadTimeOut
> TimeOut.OpenStandardXXX_WriteTimeOut
> TimeOut.OpenStandardXXX_CanTimeOut
> ThreadSafety.SetStandardXXXCanBeCalledConcurrently
> ThreadSafety.ReadMayBeCalledConcurrently
> ThreadSafety.OpenStandardXXXCanBeCalledConcurrently
> WindowAndCursorProps.GetCursorPosition_Invoke_ReturnsExpected
> WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: False)
> WindowAndCursorProps.CursorVisible_SetUnixRedirected_Nop(value: True)
> WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
> WindowAndCursorProps.CursorTop_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
> WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: 32768)
> WindowAndCursorProps.CursorLeft_SetInvalid_ThrowsArgumentOutOfRangeException(value: -1)
> WindowAndCursorProps.LargestWindowHeight_UnixGet_ReturnsExpected
> WindowAndCursorProps.WindowHeight_GetUnix_Success
> WindowAndCursorProps.WindowWidth_GetUnix_Success
> WindowAndCursorProps.BufferWidth_GetUnix_ReturnsWindowWidth
> WindowAndCursorProps.SetCursorPosition_Invoke_Success
> WindowAndCursorProps.CursorSize_GetUnix_ReturnsExpected
> WindowAndCursorProps.LargestWindowWidth_UnixGet_ReturnsExpected
> WindowAndCursorProps.BufferHeight_GetUnix_ReturnsWindowHeight
> WindowAndCursorProps.CursorTop_Set_GetReturnsExpected
> WindowAndCursorProps.CursorLeft_Set_GetReturnsExpected
> ```
> 
> It can be helpful for annotating the unsupported APIs.

All the respective APIs were processed so I'm closing this issue as resolved.
