### ISSUE TITLE
BigInteger tests fail under certain culture settings on Windows

### ISSUE THREAD

**Issue by jfd16** [dotnet/runtime#47929]
### Description
Steps to reproduce:
1. Set the current culture digit grouping to `123,456,789` using the Region settings in Windows Control Panel.
2. Run the tests in `System.Runtime.Numerics` with `/p:Outerloop=true` and verify that the tests pass.
3. Change the digit grouping to `123456789`.
4. Run the tests again. This time the tests should fail (with an unexpected `FormatException`).

This happens because the `GenerateGroups` function ([here](https://github.com/dotnet/runtime/blob/df2b4f2a4d796684cd4b448a8fca5224c443daf3/src/libraries/System.Runtime.Numerics/tests/BigInteger/parse.cs#L723)) is generating empty strings to pass to `BigInteger.Parse` when `CultureInfo.CurrentCulture.NumberFormat.NumberGroupSizes` is `{0}`.

### Configuration

* Which version of .NET is the code running on? 6.0
* What OS and version, and what distro if applicable? Windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No

**Comment by tannergooding** [comment]
CC. @tarekgh, @GrabYourPitchforks; is this possibly ICU related?

**Comment by GrabYourPitchforks** [comment]
I don't think it's a globalization or ICU thing. In OP's case, they have a culture where `NumberGroupSizes` is the array `new int[] { 0 }`, and the unit test function they linked to is generating invalid test case inputs when it encounters this condition. Seems like the fix would be entirely within _System.Runtime.Numerics.Tests_ rather than any shipping runtime or library code.

**Comment by tarekgh** [comment]
Yup, I agree with @GrabYourPitchforks analysis. This is a test issue. Actually the digit grouping setting was read by the user overrides and not from ICU at all.

**Comment by tannergooding** [comment]
Going to mark this as a bug and up-for-grabs then since I can reproduce.
