### ISSUE TITLE
Potential deadlock using System.Diagnostics.Process

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#47947]
I noticed the following `lock` statements in `System.Diagnostics.Process`:

https://github.com/dotnet/runtime/blob/525c43ea5581640c7100dc3c9fba4e21e6c87d3a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L781-L784
https://github.com/dotnet/runtime/blob/525c43ea5581640c7100dc3c9fba4e21e6c87d3a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L845
https://github.com/dotnet/runtime/blob/525c43ea5581640c7100dc3c9fba4e21e6c87d3a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1105-L1109
https://github.com/dotnet/runtime/blob/525c43ea5581640c7100dc3c9fba4e21e6c87d3a/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L1318

Couldn't locking on `this` cause issues? For instance:

```c#
[TestMethod]
public void ProcessDeadlockExample()
{
    var process = new Process
    {
        StartInfo = new ProcessStartInfo
        {
            FileName = "cmd",
            Arguments = "/C echo Hello world",
            UseShellExecute = false,
            CreateNoWindow = true
        },

        EnableRaisingEvents = true
    };

    var mre = new ManualResetEvent(false);

    process.Exited += (e, o) => mre.Set();

    // SomePrivateLockField = process;

    lock (process) // Blocks Exited from firing, resulting in a...
    {
        process.Start();

        mre.WaitOne(); // ... deadlock.
    }
}
```

Now obviously this is a rather contrived example, but regardless, I was just wondering what the rationale was for internally locking a public type like `Process`.

**Comment by stephentoub** [comment]
Whoever wrote this initially wasn't considering that use. And at this point it's a potentially dangerous breaking change to change it,  in case someone was actually relying on that lock for synchronizing with Process' work.  This may sound contrived,  but we've had to revert such changes elsewhere,  e.g. when we changed Console to no lock on the Out object itself,  only to find that a lot of folks were living on that same object to ensure atomicity of console operations,  e.g. setting a color, writing, resetting the color.

**Comment by WizardBrony** [comment]
@stephentoub Thanks for the insight. I was just curious if there was some intentional reason it was originally written like that that I wasn't thinking of. If it's still like that today for the sake of preventing a breaking change, I totally get it.
