### ISSUE TITLE
Elegant way to get executing exe path rather than dll path in Windows .NET 5 WPF when debugging

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#47953]
I have a .NET 5 WPF application project. Is there a way to get self path compatible with `debugging` and `publish as single file application`?

`Environment.GetCommandLineArgs()` give me `C:\xxx\app.dll`. The `C:\xxx\app.exe` beside the dll, the following code doesn't seem to be reliable.

```cs
var selfPath = Environment.GetCommandLineArgs().First();
if (selfPath.EndsWith(".dll"))
    selfPath = Regex.Replace(selfPath, @".dll$", ".exe");
```

**Comment by huoyaoyuan** [comment]
Probably no. The application isn't necessarily loaded by the generated `exe`. It can be called by `dotnet.exe` with absence of `app.exe`.

**Comment by vitek-karas** [comment]
In the general case @huoyaoyuan is right, but if you would always use the `app.exe` (which is recommended for UI apps as it has the icon and manifest an other potentially important native resources), then you can get that by using

```C#
string selfPath = Process.GetCurrentProcess().MainModule.FileName;
```

**Comment by GF-Huang** [comment]
> In the general case @huoyaoyuan is right, but if you would always use the `app.exe` (which is recommended for UI apps as it has the icon and manifest an other potentially important native resources), then you can get that by using
> 
> ```cs
> string selfPath = Process.GetCurrentProcess().MainModule.FileName;
> ```

Also works for publish as single file application?

**Comment by vitek-karas** [comment]
Yes - that should work for both single-file and non-single-file `app.exe` cases.

**Comment by GF-Huang** [comment]
Great, thank you.

**Comment by stephentoub** [comment]
For reference, Environment.ProcessPath has also been added for .NET 6.
https://github.com/dotnet/runtime/pull/42768
