### ISSUE TITLE
crossgen errors for use of Vector<T> without IsHardwareAccelerated guard

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#47964]
In https://github.com/dotnet/runtimelab/pull/645 we got error
```
2021-02-06T02:17:42.8985553Z ##[error].dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Error compiling /__w/1/s/artifacts/bin/pkg/net6.0/runtime/Linux-Release-x64/System.Text.RegularExpressions.dll: Target-dependent SIMD vector types may not be used with ngen.
```
where `Vector<T>` was being used. System.Text.Json doesn't cause this error, my guess is because it is guarded with `Vector.IsHardwareAccelerated`

If crossgen can't assume that SIMD instructions are available, apparently it should still generate valid code for `Vector<T>` use.

It also seems to me that crossgen errors should not contain the term `ngen`.
  153:     IDS_EE_SIMD_NGEN_DISALLOWED             "Target-dependent SIMD vector types may not be used with ngen."
  156:     IDS_EE_HWINTRINSIC_NGEN_DISALLOWED      "Hardware intrinsics may not be used with ngen."

**Comment by mangod9** [comment]
Moving this to crossgen2, would be good to validate if we see the same issue there.

**Comment by tannergooding** [comment]
SIMD Intrinsics and Hardware Intrinsics used in S.P.Corelib must be appropriately guarded because it has special rules within crossgen.

For example [ContainsNonAsciiByte](https://source.dot.net/#System.Private.CoreLib/ASCIIUtility.cs,f6c2731b625e940e) is only called from a code path where `AdvSimd.Arm64.IsSupported` was already checked, but we need the additional check anyways so the crossgen output is even nicer:
```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ContainsNonAsciiByte(Vector128<byte> value)
        {
            if (!AdvSimd.Arm64.IsSupported)
            {
                throw new PlatformNotSupportedException();
            }
            value = AdvSimd.Arm64.MaxPairwise(value, value);
            return (value.AsUInt64().ToScalar() & 0x8080808080808080) != 0;
        }
```

CC. @davidwrighton

**Comment by davidwrighton** [comment]
Crossgen2 simplifies the rules here.

For System.Private.CoreLib, the requirement is that code must be correct if the IsSupported check is not taken even when it could be taken.

For non-S.P.C code, code should just work. However, at the moment, it will default to abandoning compilation. We may fix that in the next release.
