### ISSUE TITLE
System.Runtime.Intrinsics.X86 got replaced?

### ISSUE THREAD

**Issue by eddynaka** [dotnet/runtime#47963]
Hi,

I was using `System.Runtime.Intrinsics.X86` from myget source but it looks like it does not exist there anymore. Then, I saw that we have a new package in the nuget.org called `System.Runtime.Intrinsics.Experimental`.

I tried to use it, but I saw that the static method `StaticCast` from `Sse` got removed.

So, I would like to know what can I use to replace that.

Below you can find a snippet:

```csharp
// Shuffle to get the right bytes in each integer
vector1 = Sse.StaticCast<sbyte, int>(Ssse3.Shuffle(Sse.StaticCast<int, sbyte>(vector1), shuffle1));
vector2 = Sse.StaticCast<sbyte, int>(Ssse3.Shuffle(Sse.StaticCast<int, sbyte>(vector2), shuffle2));
```

Thank you!

**Comment by eddynaka** [comment]
I found the replacement.

vect.AsSbyte() or vice-versa.

Thank you! :)

**Comment by GrabYourPitchforks** [comment]
The MyGet feed is no longer maintained, and the _System.Runtime.Intrinsics.Experimental_ package is prerelease. Please use the normal _System.Runtime.Intrinsics_ assembly which comes as part of the SDK.
