### ISSUE TITLE
How to GetLastError in C# dotnet core linux when OutOfMemoryException in Thread.Start

### ISSUE THREAD

**Issue by xiongrenyi** [dotnet/runtime#47986]
This is not an issue but just for understanding purpose. The OutOfMemoryException happened when we created lots of threads by mistake on dotnet core 64bit linux c# application. We kind of ruled out the the possibility of OOM on linux side by successfully creating even more threads in C directly and in Java as well. We fixed our mistake already but want to understand what really caused Thread.Start to fail. Looks like dotnet throws OOM if it fails to create native thread due to any error and logs the error in SetLastError? If the understanding is correct, then the question is how we GetLastError in dotnet core linux to get the real cause; if not, please feel free to ignore.

We looked at below code and some other related ones assuming it's the right place:
https://github.com/dotnet/coreclr/blob/master/src/vm/comsynchronizable.cpp
https://github.com/dotnet/coreclr/blob/master/src/pal/src/thread/thread.cpp

**Comment by mangod9** [comment]
Hey @xiongrenyi , are you asking how you could handle and log why an OOM occurred in the app?

**Comment by jkotas** [comment]
> what really caused Thread.Start to fail.

It was most likely the `pthread_create` API.

If you would like to know for sure, you can use `strace` to get a log of all syscalls and their results.
