### ISSUE TITLE
Module Initializer for platforms other than .NET 5

### ISSUE THREAD

**Issue by RamType0** [dotnet/runtime#47987]
AFIK , the function of module initializer is implemented by many runtime far times ago, but it was not exposed to C#.
Today, it was exposed to C# through System.Runtime.CompilerServices.ModuleInitializerAttribute, which is only available in .NET 5.
Are there plan for module initializer support for old platforms?

**Comment by ufcpp** [comment]
just works.
https://github.com/ufcpp/UfcppSample/tree/master/Demo/2021/ModuleInitializerNet48/ConsoleApp1

**Comment by huoyaoyuan** [comment]
It is a pure compiler feature for C#. You can [define the attreibute yourself](https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4AEBMBGAsAKHQAYACdbAOgCUBXAOzkQFsBTCgYQHsmAHFFgE4BlQQDdEAYxYBnANwECdAIatpPJVLKVaDZmy69+wsZJkEA3gRLWSiBoOXIymEgFlOAExrIWASTqIjErIiABeggCCcHACiMA0cCwkICRRMXEJLOYAvgS5+AToAMzOJOwklvg2JADa7l4+/oGIwWGCALpWNsVaEGRQbgAUAJQVXdb52UA=).
