### ISSUE TITLE
[Wasm][AOT] methods performing stack crawling fail under profiled AOT

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#47996]
### Description

Running an application which uses any of the methods belo fails to work properly when this method is specified in the AOT profile:

```
ManifestBasedResourceGroveler.InternalGetSatelliteAssembly
System.Reflection.Assembly.GetExecutingAssembly
System.RuntimeType.GetType
System.RuntimeTypeHandle.internal_from_name
System.RuntimeTypeHandle.GetTypeByName
System.Type.GetType
System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath
System.Runtime.Loader.AssemblyLoadContext.InternalLoadFile
System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName
System.Reflection.Assembly.Load
System.Reflection.Assembly.InternalLoad
System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly
System.Reflection.RuntimeAssembly.InternalLoad
```

It is expected as these methods uses stack walking to determine the executing assembly.

### Workaround

Exclude `System.Reflection.Assembly.GetExecutingAssembly` and the other listed methods from the AOT profile.

### Configuration

bb650672df2da1c7666e20d3abf713d050a954ca

### Regression?

No

**Comment by lewing** [comment]
calling this closed given that uno ci is green, @jeromelaban feel free to reopen if this is an error
