### ISSUE TITLE
Why the channels's write and read use same obj to lock?

### ISSUE THREAD

**Issue by BenLampson** [dotnet/runtime#47997]
![image](https://user-images.githubusercontent.com/15414750/107243587-1e27cd00-6a68-11eb-8539-4c9a5384df1e.png)
![image](https://user-images.githubusercontent.com/15414750/107243609-22ec8100-6a68-11eb-842e-4d006d0e246e.png)
![image](https://user-images.githubusercontent.com/15414750/107243622-25e77180-6a68-11eb-8f19-5d64ffc3ab18.png)
Here has a little question.
If the "Writer" with a while loop to write the data [with 100 thread].
The "Read" will never be got data from channels.
But since it can be defined separately, shouldn't it support such a scenario?
Now the situation is, even if I use it fullmode:wait The reader can't get the data!

**Comment by stephentoub** [comment]
Because the reader and writer are sharing the same data structures (e.g. the queue) and need to synchronize with each other.

**Comment by BenLampson** [comment]
Maybe we can watch the Reader and Writer to decied how many consumer or writer here???
In this version I think there so many user can write the code like below:
```
public async  void X()
{
await _channel.write.WriteAsync();
}
```

```
public async  void X()
{
while(true){
await _channel.Reader.ReadAsync();
.. do something.
}
}
```

**Comment by BenLampson** [comment]
Or we can use the data struct **like** double link(just example)? 
To provider the Writer and Reader use different obj to lock?
Case when the data in "queue" has many items, the reader and writer can visit his data in the same time.

**Comment by stephentoub** [comment]
What problem are you trying to solve? Can you please share a runnable repro of the problem?

**Comment by BenLampson** [comment]
> What problem are you trying to solve? Can you please share a runnable repro of the problem?

Here has a simple demo to show what happened in my project.
I use the CORE 3.1 5 there has the same question.
[Runnable repro](https://github.com/BenLampson/Channel-lock-question)

**Comment by BenLampson** [comment]
There are a lot of scenarios that have this problem.
Like the:
1. Use the channel to realization the log lib.
2. When the MQ server has much more message and uses the channel to realization the signal read client proxy.
3. Some job queue. 
4. etc.

**Comment by BenLampson** [comment]
There's some info to show: how did I find this problem.
I try to use the channel to realization the log lib, when our app has some bug in the code, we found the memory growth is too fast, but there has no trace log here.
When I test the performance to channel instance, I found this question.
I try to use the channel to solve the queue, but it brings another question to me.

**Comment by stephentoub** [comment]
> Runnable repro

That has little to do with the synchronization employed in the channel.  The first version of send code is using Task.Run, queuing 100 of them.  That saturates the thread pool with workers that are writing to the channel.  You separately have a thread that you intend to read from that channel, but the moment it "await"s, that thread is going to end, and the continuation of the loop is going to be posted to execute in the thread pool.  That work item won't be able to run, because it'll be stuck behind all of the work items you queued to write.  It doesn't repro with your 2nd and 3rd version of sending because for those your writers aren't on thread pool threads, and so the reader's continuation gets processed by the thread pool immediately.

**Comment by BenLampson** [comment]
Thx your reply! And I try to understand what you write.

I think we have the same answer to this question right now.
My point is: in the real project the case 1 is a common phenomenon.
If the [channel] has this question here can we give the program some tips or other info to skip this thing?

Or maybe we can create the channel's work thread pool to another one to help the user to skip this question?
Cause no matter how to use or realization channel's instance, he must the task or thread to push the data to cache or queue.
Maybe there needs a method: Write<T>(T data)?

And channel manage a worker thread to push data to queue?

**Comment by stephentoub** [comment]
I'm trying to understand the question you're asking...

The issue in the repro is not related to the implementation of the channel.

Are you saying your concern is that the channel type lacks synchronous methods?  We have no plans to add synchronous methods to it.  If you really want to block, you can use `.AsTask().GetAwaiter().GetResult()` on the `ValueTask` instance returned from the `ReadAsync` / `WriteAsync` methods.

**Comment by BenLampson** [comment]
1. Are you saying your concern is that the channel type lacks synchronous methods
       No,
1. the question you're asking...
       You already answer my question, Thx!


All the messages here just my proposal.

1. Why has synchronous concern?
     Cause if the channel doesn't change the way he realizes it, how we can know: we must use another thread pool to call the write method? Can we add the tip to Channel's API doc? In my point, I think the user need not know the API's source code or API's working principle. 
    And there has some scene below (And I'm sure it happened everywhere): 
Someone uses the channel to realization  current-limiting or SLB or socket operation lib, and I use his lib to send the message, 
I think the code below is working.
![image](https://user-images.githubusercontent.com/15414750/108662710-da25d500-7509-11eb-924f-2003bbbab734.png)
But not, You must write the delay or sleep to here.
![image](https://user-images.githubusercontent.com/15414750/108662763-f88bd080-7509-11eb-9f60-52f1d2664f8e.png)
It needs too much knowledge of developers, but developers try to use 'channel ' to reduce the ideological pressure. I'm sure that the developers use the 'Channel' cause he didn't want to pay attention to the thread.
But this is not the case with the current version.


And thx your reply here!

**Comment by BenLampson** [comment]
My project is an app trace lib.
I can't limit users to how to use my lib.
I am faced with a choice: to be in a safe queue.
Or, before pushing to channel, push to another thing and let that thing push to channel.
Cause my project's target is to find the app's bug, but currently, the bug is my project.

**Comment by davidfowl** [comment]
Why are you writing to the channel in a tight loop? Is the channel bounded? Who is the consumer? What should happen if the producer outruns the consumer? 

I would start by answering some of those questions and it might help guide to a better solution.

**Comment by BenLampson** [comment]
> Why are you writing to the channel in a tight loop? Is the channel bounded? Who is the consumer? What should happen if the producer outruns the consumer?
> 
> I would start by answering some of those questions and it might help guide to a better solution.

OK, I will write what happened in real project.

**Comment by BenLampson** [comment]
Dead loop is just an extreme state. If I have enough threads, in fact, my service is enough to cause system crash in a second.
The root cause of all this is that the channel can not be consumed. Even if the customer stops sending after 1s, my library will cause the user's memory explosion within 1s, and I have nothing to do about it.

It's not the deliberate code to write while loop, just a little mistake.
But it happened in the scene like below:
I write the method trace lib, the server-side is GRPC.
The client-size is .NET 5 class library.
One custom uses my lib to trace his project.
Under normal circumstances, everything is OK. However, when the user's consumption, that is, the number of clients or needs to push to server's message increases sharply.
The user's client's code is the task asynchronous model, which basically forms a tight loop scenario. At this time, my message can't be pushed at all.
My project just the lib, I can't limit users on how to push the message or use the long-running tasks to invoke my "SendMessage" method.
I can even accept slower efficiency, but I can't accept blocking. As a public library, if the user doesn't sleep when invoking my method, then I will be locked. Even if I do any sleeping in my function, it can't be solved. This problem is left to the user.
This is why I can't accept channel.
Because I can't use ethics to constrain how users use my library.
This is a very embarrassing situation. If this problem does not occur, then my project will be accurately positioned as follows: the customer has opened too many threads and loops, and I will issue a warning to prevent the system from crashing.

**Comment by BenLampson** [comment]
> Why are you writing to the channel in a tight loop? Is the channel bounded? Who is the consumer? What should happen if the producer outruns the consumer?
> 
> I would start by answering some of those questions and it might help guide to a better solution.

Simply put, forget the loop, and suppose this action lasts for one second.
More than 1GB of memory used by my lib, and the channel has a lot of items.

**Comment by davidfowl** [comment]
By> Dead loop is just an extreme state. If I have enough threads, in fact, my service is enough to cause system crash in a second.

That's not how a well behaved system would be written through. You need to throttle somewhere. You can't have the producer out pace the producer and vice versa. You can use a bounded channel to or you can throttle manually.

> The root cause of all this is that the channel can not be consumed. Even if the customer stops sending after 1s, my library will cause the user's memory explosion within 1s, and I have nothing to do about it.

You can, see the above. Apply back pressure to the caller and it'll be fine.

> I can even accept slower efficiency, but I can't accept blocking. As a public library, if the user doesn't sleep when invoking my method, then I will be locked. Even if I do any sleeping in my function, it can't be solved. This problem is left to the user.


If the API you exposed is a blocking one then channel is the wrong API. You might need a blocking collection to stop the caller from writing if it's full.


Sounds like you need to decide what to do when the reader is out paced by the writer. You have 3 options, block, drop items, or throw.

**Comment by BenLampson** [comment]
>That's not how a well behaved system would be written through. You need to throttle somewhere. You can't have the producer out pace the producer and vice versa. You can use a bounded channel to or you can throttle manually.

It's the first way to try to solve this question, but it not work. Even I use the bounded channel, still unable to read data (You can use my demo code to test this case). Currently the Channel *Needs* client to control(release thread pool worker) the push operation(Or lib owner like me).

![image](https://user-images.githubusercontent.com/15414750/108806936-06ab2100-75de-11eb-99b8-0218387f4be2.png)

 
>If the API you exposed is a blocking one then channel is the wrong API. You might need a blocking collection to stop the caller from writing if it's full.

Yep, I want to expose the async method, the demo you see is the 3rd version in my project, we try so many ways to handle this question.

Thank you for your suggestion. My current practice is to open several channels for an internal instance-level distribution because our library can't accept lost messages, which can solve this problem at present.
Thx!

**Comment by BenLampson** [comment]
But I want this thing handled by the channel API.
When the reader and writer are single, why channel still need to lock all queues?
Or, in another point, 'Channel' why needs the lock to push the item to his double-ended queue(full queue lock)? Channel needs the ordered message? He has not and needs not order, select, or continuity memory space, right?
Currently the channel's option: single consumer and single producer, no matter which one or both of them, the channel's strategy was always locking(and he lock full Deque<T>), it doesn't make sense. Cause there haven't modified and remove from 
There has little point in the demo, when I first time to use Channel, I think: when I use "Single write with Single reader"  mode, while when I use other thread pool to read data(Before I raised this issue, I thought about thread pool), the channel can read and write data as the same time, that's why I open this issue.
There's a little question? Why when I use another thread pool to read, I can't read the message's reason is: the write thread pool is full?
Why do I still think it's the failure of the common lock?
``` C#
lock (parent.SyncObj)
```
One of the biggest question marks in my mind, which I have never understood in this issue, is that it is clearly a "double end queue", one reads from the beginning and the other inserts to the end. Why does it lock full queue instance every time I insert an item.

**Comment by BenLampson** [comment]
> Apply back pressure to the caller and it'll be fine
I think in my project, the channel is "Sources of stress" cause no matter how many servers I opened the reader can't read messages, all data blocked in channels instance.

**Comment by davidfowl** [comment]
> There's a little question? Why when I use another thread pool to read, I can't read the message's reason is: the write thread pool is full?
Why do I still think it's the failure of the common lock?

This lock isn't the problem.

> Why does it lock full queue instance every time I insert an item.

That was already answered above.

> I think in my project, the channel is "Sources of stress" cause no matter how many servers I opened the reader can't read messages, all data blocked in channels instance.

You have 100 threads burning CPU trying to write to the same channel with no backpressure. How many cores do you have? How do you expect the reader to get scheduled if you're using up all of the threads?

**Comment by BenLampson** [comment]
Thx for your reply~

> > There's a little question? Why when I use another thread pool to read, I can't read the message's reason is: the write thread pool is full?
> > Why do I still think it's the failure of the common lock?
> 
> This lock isn't the problem.
> 
> > Why does it lock full queue instance every time I insert an item.
> 
> That was already answered above.
> 
> > I think in my project, the channel is "Sources of stress" cause no matter how many servers I opened the reader can't read messages, all data blocked in channels instance.
> 
> You have 100 threads burning CPU trying to write to the same channel with no backpressure. How many cores do you have? How do you expect the reader to get scheduled if you're using up all of the threads writing?
