### ISSUE TITLE
Consider adding TaskCompletionSource.SetFromTask(Task)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#47998]
EDITED by @stephentoub on 1/21/2023:
- I added Try methods.
```diff
namespace System.Collections.Threading.Tasks
{
    public class TaskCompletionSource
    {
+        public void SetFromTask(Task task);
+        public bool TrySetFromTask(Task task);
    }

    public class TaskCompletionSource<T>
    {
+        public void SetFromTask(Task<T> task);
+        public bool TrySetFromTask(Task<T> task);
    }
}
```

These methods require that the task argument has already completed and transfer the result/exception/cancellation state over to the TCS's Task.

## Background and Motivation

A common operation when writing async code is to execute code that returns a task and complete. This usually involves creating a `TaskCompletionSource` to represent the operation, then executing the operation that returns a task at point in the future, then setting the result on completion to either failed, cancelled or success.

## Proposed API

```diff
namespace System.Collections.Threading.Tasks
{
    public class TaskCompletionSource
    {
+       public void SetFromTask(Task task);
    }

    public class TaskCompletionSource<T>
    {
+       public void SetFromTask(Task<T> task);
    }
}
```

## Usage Examples

```C#
public class Connection
{
    private TaskCompletionSource _tcs = new();
    private CancealltionTokenSource _cts = new();

    public Task Run()
    {
        ThreadPool.QueueUserWorkItem(_ => Start());
        return _tcs.Task;
    }
    
    public void Start()
    {
        tcs.SetFromTask(NetworkHelper.StartConnectionAsync(_cts));
    }
    // ...
}
```

This is a common pattern when you need to kick off an async operation and can't directly wait the operation inline.

## Alternative Designs

Do this manually.

```C#
public static class TaskCompletionSourceExtensions
{
    public void SetFromTask(this TaskCompletionSource  task, Task task)
    {
        async Task Continue()
        {
            try
            {
                await task;
                tcs.TrySetResult();
            }
            catch (OperationCancelledException ex)
            {
               tcs.TrySetCancelled(ex.Cancelled);
            }
            catch (Exception ex)
            {
               tcs.TrySetException(ex);
            }
        }
        _ = Continue();
    }
}
```

## Risks

None.

**Comment by stephentoub** [comment]
We've considered such a thing in the past, e.g. tcs.SetFromTask(task).  But we frequently found that there was a better way of writing it.  For example, in your usage example:
```C#
public class Connection
{
    private TaskCompletionSource _tcs = new();
    private CancealltionTokenSource _cts = new();

    public Task Run()
    {
        ThreadPool.QueueUserWorkItem(_ => Start());
        return _tcs.Task;
    }
    
    public void Start()
    {
        NetworkHelper.StartConnectionAsync(_cts).ContinueWith(tcs);
    }
    // ...
}
```
passing the tcs into StartConnectionAsync and having it complete it.
```C#
public class Connection
{
    private TaskCompletionSource _tcs = new();
    private CancealltionTokenSource _cts = new();

    public Task Run()
    {
        ThreadPool.QueueUserWorkItem(_ => Start());
        return _tcs.Task;
    }
    
    public void Start()
    {
        NetworkHelper.StartConnectionAsync(_tcs, _cts);
    }
    // ...
}
```
or if StartConnectionAsync actually returned a Task (since I know how much you love async void methods), just using Task.Run:
```C#
public class Connection
{
    private CancealltionTokenSource _cts = new();

    public Task Run() => Task.Run(() => Start());
    
    public Task Start() => NetworkHelper.StartConnectionAsync(_cts);
    // ...
}
```
which does such transfer automatically.

**Comment by davidfowl** [comment]
- I have a delegate that I can't change the signature of, so I can't pass the all the way down.
- Task.Run doesn't work for me because I need to get rid of the ExecutionContext. I'm using my new favorite method `UnsafeQueueUserWorkItem`.

**Comment by stephentoub** [comment]
> Task.Run doesn't work for me because I need to get rid of the ExecutionContext

You can of course use SuppressFlow.  Yes, it's more code, but such a SetFromTask would need to be used enough to make it worthwhile.

Are you using UnsafeQueueUserWorkItem purely for the ExecutionContext behavior?  Or do you actually need to queue the invocation of the async operation for some reason?

This still seems to me to be too niche to warrant exposing.  The sole place we have such a SetFromTask method is in the implementation of Task.Run itself.

How many places would you actually use this?

**Comment by davidfowl** [comment]
> Are you using UnsafeQueueUserWorkItem purely for the ExecutionContext behavior? Or do you actually need to queue the invocation of the async operation for some reason?

I need both behaviors.

> This still seems to me to be too niche to warrant exposing. The sole place we have such a SetFromTask method is in the implementation of Task.Run itself.

Yea, it's not a big deal. I wrote a helper but I remembered that I also wrote a helper when we did the original SignalR (https://github.com/SignalR/SignalR/blob/75126981cd165fb57db4e38e9379e651fec1ecdf/src/Microsoft.AspNet.SignalR.Core/TaskAsyncHelper.cs#L315)

> How many places would you actually use this?

I'll look around. I don't think it's critical at the moment, I filed this because it came up again.

**Comment by theodorzoulias** [comment]
@davidfowl an existing alternative of the proposed API is to use a cold nested task and the [`Unwrap`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskextensions.unwrap) method. The `Unwrap` resembles the `TaskCompletionSource.SetFromTask`, in that it returns a proxy of the inner task. The completion status of the inner task is propagated through the proxy.

```C#
public class Connection
{
    private Task<Task> _taskTask;
    private CancellationTokenSource _cts = new();

    public Connection()
    {
        _taskTask = new Task<Task>(() => NetworkHelper.StartConnectionAsync(_cts));
    }

    public Task Run()
    {
        ThreadPool.QueueUserWorkItem(_ => _taskTask.RunSynchronously(TaskScheduler.Default));
        return _taskTask.Unwrap();
    }
    // ...
}
```

**Comment by davidfowl** [comment]
Man I forgot about Unwrap m. Async/await made me forget past trauma.

**Comment by davidfowl** [comment]
Do cold tasks capture the execution context?

**Comment by theodorzoulias** [comment]
> Do cold tasks capture the execution context?

I wish I knew that!

**Comment by stephentoub** [comment]
Yes. ExecutionContext is captured in Task's ctor.

**Comment by carlossanlop** [comment]
@davidfowl based on the answers, do you still believe we should continue pursuing this idea, or can we go ahead and close the issue?

**Comment by davidfowl** [comment]
Future will do for now

**Comment by SergeyTeplyakov** [comment]
I was working recently on 3 different projects at Microsoft - BuildXL, a distributed cache and AnyBuild. And I needed `SetFromTask` in all of them.

Of course, this is an example of selection bias, but I really think it would be helpful to have the API @davidfowl proposed.

**Comment by stephentoub** [comment]
> I added Try methods

I added these when I forgot that this proposal was building in the continuation into the operation. They make zero sense in that case. I also think that the SetFromTask name doesn't convey what it's actually being done here... my intuition is that it's just transferring the completion state of an existing task, just as eg SetResult is storing some existing result, in which case Try would make sense. And I don't think we can add the Try that means one thing and the non-Try that means something else. It's also not clear to me what the behavior of these methods would be if someone calls SetFromTask, then separately completes the TCS, and then the task passed to SetFromTask completes.

**Comment by davidfowl** [comment]
>It's also not clear to me what the behavior of these methods would be if someone calls SetFromTask, then separately completes the TCS, and then the task passed to SetFromTask completes.

This is a good question. I think the normal behavior applies. The first one to call Try* wins. Maybe that means we need to change the name and also handle what happens if you call SetFromTask multiple times on different tasks ?

**Comment by stephentoub** [comment]
I think it'd be much cleaner if {Try}SetFromTask was simply about transferring the state of an already-completed task over to a TCS.  If you wanted that to happen when the task completes (and you weren't otherwise already registering a continuation with it for other reasons), you'd hook up a continuation explicitly, e.g. rather than:
```C#
tcs.SetFromTask(task);
```
that would implicitly add a continuation to `task` in this proposal, you'd instead do:
```C#
task.ContinueWith(tcs.SetFromTask);
```
or:
```C#
await task.NoThrow();
tcs.SetFromTask(task);
```
Yes, they're more complicated to use, but they also address the issue of what to do if the TCS is completed before a previously SetFromTask'd task completes, and it leaves the semantics of SetFromTask being effectively the same as the existing SetResult/Exception/Canceled.  You get to be very explicit about what to do if you lose a race condition to complete the TCS, you get to manually control the continuation and can then do things like cancel it or do additional work as part of the continuation, etc.

**Comment by bartonjs** [comment]
* The `task` parameters were renamed to `completedTask` to help indicate that the parameter must always be in a `task.IsCompleted == true` state.

```C#
namespace System.Collections.Threading.Tasks
{
    public partial class TaskCompletionSource
    {
        public void SetFromTask(Task completedTask);
        public bool TrySetFromTask(Task completedTask);
    }

    public partial class TaskCompletionSource<T>
    {
        public void SetFromTask(Task<T> completedTask);
        public bool TrySetFromTask(Task<T> completedTask);
    }
}
