### ISSUE TITLE
Extra save in generated code for comparison

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#47992]
### Description

I created a simple test on SharpLab site and very wonder why result code saves compare result:

https://sharplab.io/#v2:C4LghgzgtgNAJiA1AHwAICYCMBYAUKgZgAIMiBhIgbzyNrtoEsA7YIuIgXiMwG4a7CJACxEAsgAoAlFX71aZAPZMICgDYBTAHQB1AE4Ng68XEl9ccugwBmRY5y7pJsudXMW5cRIjPuPXn+4Avs70ispqWnoGRiYBtMG4gUA=

```c#
    L0029: mov ecx, [ebp-4]
    L002c: cmp dword ptr [ecx+4], 2
    L0030: sete cl
    L0033: movzx ecx, cl
    L0036: mov [ebp-8], ecx
    L0039: cmp dword ptr [ebp-8], 0
    L003d: je short L004d
```

Is it expected or a bug? Looks like a performance issue too.

**Comment by Joe4evr** [comment]
Seems likely because you're looking at Debug ASM, so the compare result is saved for inspection. Switch to Release and nothing of the ASM in your post remains.

**Comment by iSazonov** [comment]
Ah, yes :-) Thanks!
