### ISSUE TITLE
MacOS-arm64 native crossgen2 build missing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48001]
When building coreclr on Apple Silicon crossgen2 is created for `x86_x64` instead of `arm64`.  The native one is missing.

- This is likely blocked on using a .NET 6 preview to build. See #47245
- This is likely related to failures in these ready2run tests
   - readytorun/multifolder/multifolder/multifolder.sh
   - readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.sh
   - readytorun/crossgen2/crossgen2smoke/crossgen2smoke.sh

**Comment by mangod9** [comment]
cc @AntonLapounov

**Comment by sdmaclea** [comment]
These tests are disabled for this issue.

https://github.com/dotnet/runtime/blob/c32007158a0b6c356c7f0e25d2d8571ff37d029f/src/tests/issues.targets#L739-L748

**Comment by mangod9** [comment]
Believe this should be fixed.
