### ISSUE TITLE
JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b309576\b309576 - JIT assert in CG2 composite mode

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#48008]
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=982814&view=ms.vss-test-web.build-test-results-tab&runId=30799084&resultId=101992&paneView=debug

Platform: all

Error message:

<pre>
Assertion failed '(varDsc->lvType != TYP_UNDEF) && (varDsc->lvType != TYP_VOID) && (varDsc->lvType != TYP_UNKNOWN)' in 'FullProof:Test():int' during 'Mark local vars' (IL size 1446)
</pre>

/cc @dotnet/crossgen-contrib @dotnet/jit-contrib 
@sandreenko - would there be a chance for you or someone from the JIT team to take a first look?

**Comment by sandreenko** [comment]
most likely it is a duplicate of https://github.com/dotnet/runtime/issues/48008, but let's keep it open until I confirm it.

**Comment by trylek** [comment]
@sandreenko - sorry about nitpicking, it looks like you accidentally mentioned this very issue as the duplicate, could you please reference the true "other" issue here for clarity?

**Comment by sandreenko** [comment]
Yes, my bad, the real issue is https://github.com/dotnet/runtime/issues/47308

**Comment by sandreenko** [comment]
Closed as dup.

**Comment by sandreenko** [comment]
I was able to repro the issue without crossgen2, but could not check if it affect 5.0 or not.
