### ISSUE TITLE
WebHeaderCollection can't handle HTTP/2 psuedo headers

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#48009]
### Description
CoreWCF reads the headers from the aspnetcore HttpContext.Request.Headers property and populates an instance of WebHeaderCollection (to support equivalent of existing WCF api). There are 4 pseudo headers as part of the HTTP/2 spec which start with a colon. These are `:method`, `:scheme`, `:authority`, and `:path`. When trying to add any of these headers to a WebHeaderCollection, it throws an exception as they are invalid HTTP/1.1 headers. Other than these 4 headers, all other headers follow the HTTP/1.1 protocol.   
WebHeaderCollection isn't protocol specific so should support adding of these 4 headers.

### Configuration
Any .NET/.NET Core version

### Regression?
No. This is a request to update WebHeaderCollection for the newer HTTP/2 protocol.

### Other information
Other classes are updated as newer protocol versions are released, for example SslStream for TLS1.3 so this should

**Comment by ManickaP** [comment]
Triage: @mconnew could you tell us what's the reason to support these? We're leaning towards not fixing this so we'd like to know your reason.

**Comment by mconnew** [comment]
I have worked around the issue so opening the issue was as much to help those who follow as it was to get a change. CoreWCF implements a message property on our Message object which exposes some underlying HTTP protocol information. Things like method, request uri, and headers which is exposed as an instance of WebHeaderCollection. CoreWCF reads the headers from the ASP.NET Core property HttpContext.Request.Headers which is an instance of Microsoft.AspNetCore.Http.IHeaderDictionary. CoreWCF had a simple loop to read the header name/value pairs and populate a WebHeaderCollection with them. The problem is these 4 HTTP/2 headers can't be populated into a WebHeaderCollection. I did the simple fix of checking if the header name starts with a colon and skipping it.  
So the question whether to fix this is a philosophical one, should WebHeaderCollection support HTTP/2 headers or only HTTP/1.1 or early headers? If the latter, then a documentation update should probably happen to clarify it only supports HTTP/1.1 or earlier headers.

**Comment by scalablecory** [comment]
> So the question whether to fix this is a philosophical one, should WebHeaderCollection support HTTP/2 headers or only HTTP/1.1 or early headers? If the latter, then a documentation update should probably happen to clarify it only supports HTTP/1.1 or earlier headers.

They don't belong in this collection -- pseudo-headers are an underlying protocol version detail and not part of semantic HTTP. The spec is explicit here saying "Pseudo-header fields are not HTTP header fields". Supporting this would get people into trouble trying to blindly pass these values to some other HTTP code.

There's another question of: is this class owned by `HttpWebRequest`? If so, then they doubly do not belong here -- the values are exposed more appropriately elsewhere.

If we did choose to accept this change, then I'd want to implement it so that if `HttpWebRequest` ever saw one of these, it would throw. I don't think there's any choice re: one overwriting the other or in what to do if you pass a pseudo-header to HTTP/1 that wouldn't trip someone up, so the best thing we could do is throw.

>  CoreWCF reads the headers from the ASP.NET Core property HttpContext.Request.Headers

This is interesting. @Tratcher @ManickaP what happens in YARP when forwarding HTTP/2?

**Comment by ManickaP** [comment]
The headers get skipped:
https://github.com/microsoft/reverse-proxy/blob/main/src/ReverseProxy/Service/Proxy/HttpTransformer.cs#L49-L53
```C#
// Filter out HTTP/2 pseudo headers like ":method" and ":path", those go into other fields.
if (headerName.Length > 0 && headerName[0] == ':')
{
    continue;
}
```

Which is pretty much the same thing WCFCore does now:
https://github.com/CoreWCF/CoreWCF/blob/main/src/CoreWCF.Http/src/CoreWCF/Channels/HttpContextExtensions.cs
```C#
if (header.Key.StartsWith(":")) // HTTP/2 pseudo header, skip as they appear on other properties of HttpRequest
    continue;
```

[RFC](https://tools.ietf.org/html/rfc7540#section-8.1.2.1) is pretty specific about them as well:
> Pseudo-header fields are not HTTP header fields.

In the light of this, I don't think we should take this change.

**Comment by karelz** [comment]
Triage: Given that it goes against RFC and it would cause complications mentioned above, we won't fix it. Closing.

@Tratcher @halter73 @davidfowl do you know why ASP.NET exposes the pseudo-headers?

**Comment by davidfowl** [comment]
This feels like something we should filter TBH

**Comment by Tratcher** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/30417.
