### ISSUE TITLE
Libraries System.Security.Cryptography.Native/pal_ssl.c fails to build on CentOS 7 with PortableBuild=false

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#48010]
When I build like this:
* `./build.sh -c Release --subset libs.native /p:PortableBuild=false`
* in `mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-f39df28-20191023143754`
* on 44f8f0faee42367bdd39277d8295f6e914ad7f4a (recent `master`)

I get these build errors:

```
  Executing cmake --build "/work/artifacts/obj/native/net6.0-Linux-Release-x64" --target install -- -j 8
  [  0%] Built target System.IO.Compression.Native_exports
  [  1%] Built target System.IO.Ports.Native-Static
  [  4%] Built target System.IO.Ports.Native
  [ 17%] Built target System.Native-Static
  [ 33%] Built target System.Globalization.Native-Static
  [ 38%] Built target System.Native
  [ 44%] Built target System.Globalization.Native
  [ 45%] Built target System.Net.Security.Native-Static
  [ 47%] Built target System.Net.Security.Native
  [ 65%] Built target System.IO.Compression.Native-Static
  [ 66%] Building C object System.Security.Cryptography.Native/CMakeFiles/objlib.dir/pal_ssl.c.o
  [ 84%] Built target System.IO.Compression.Native
/work/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c(94,10): error G69804242: implicit declaration of function 'SSL_CTX_config' is invalid in C99 [-Werror,-Wimplicit-function-declaration] [/work/src/libraries/Native/build-native.proj]
      if (!SSL_CTX_config(ctx, "system_default"))
           ^
  Failed to build "native libraries component".
/work/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_ssl.c(60,20): error GB4859E72: code will never be executed [-Werror,-Wunreachable-code] [/work/src/libraries/Native/build-native.proj]
      SSL_CTX* ctx = SSL_CTX_new(TLS_method());
                     ^~~~~~~~~~~
  2 errors generated.
  gmake[2]: *** [System.Security.Cryptography.Native/CMakeFiles/objlib.dir/pal_ssl.c.o] Error 1
  gmake[1]: *** [System.Security.Cryptography.Native/CMakeFiles/objlib.dir/all] Error 2
  gmake: *** [all] Error 2
/work/src/libraries/Native/build-native.proj(40,5): error MSB3073: The command ""/work/src/libraries/Native/build-native.sh" x64 Release outconfig net6.0-Linux-Release-x64 -os Linux -portablebuild=false " exited with code 2.

Build FAILED.
```

The same build command works if I revert this commit: https://github.com/dotnet/runtime/commit/464010d9d0241bbdcbfbda25b32e78991ddf6093 (https://github.com/dotnet/runtime/pull/42812)

It looks like that commit did a few things:
* Moves the usage of `SSL_CTX_config` from inside an `ifdef` to outside of it
* Adds a `return;` into the middle of the function (probably triggers the `code will never be executed` error)

@tmds @bartonjs @omajid does this sound like the right explanation, or do you think something else might be going wrong in my build?

**Comment by dagood** [comment]
I've submitted the revert commit as PR https://github.com/dotnet/runtime/pull/48013.

(I ran into this while developing the arcade-powered source-build CI that would catch this kind of thing, funnily enough. 😄)

**Comment by bartonjs** [comment]
Hmm.  Looking again today, I'm not seeing why the change was needed, @tmds.  I have a comment that calls out Fedora/RHEL/CentOS, but there doesn't seem to be special casing for those...

```C
#ifdef NEED_OPENSSL_1_1

// Portable, plus non-portable OpenSSL 1.1

#ifdef FEATURE_DISTRO_AGNOSTIC_SSL

// Nested if, only applies to portable.
// If we found SSL_state, we're 1.0, bail out.

#endif

// We're 1.1, either portable or non-portable.
// all the runtime logic.

#else

// non-portable 1.0
// Probably only Fedora/RHEL/CentOS... but this is the same as the portable-found-1.0 behavior

#endif
```

The RHEL-like builds didn't get special cased for the 1.1 behavior, so maybe I just left a misleading comment?

**Comment by bartonjs** [comment]
This is fixed now, right?

**Comment by dagood** [comment]
I believe https://github.com/dotnet/runtime/pull/48013 and https://github.com/dotnet/runtime/pull/48076 took care of it.
