### ISSUE TITLE
Mono add support for System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute

### ISSUE THREAD

**Issue by Clancey** [dotnet/runtime#48012]
When you compile an assembly with the Attribute `[assembly: IgnoresAccessChecksTo("OtherAssembly")]` You can reference internals to the specified OtherAssembly. This works in CoreCLR, but fails in MonoVM.

**Comment by lambdageek** [comment]
`IgnoresAccessChecksToAttribute` is not part of the BCL. It's an implementation detail on CoreCLR.

That said it does seem like it would be useful to bypass method access checks in some scenarios.

**Comment by lambdageek** [comment]
It seems like `IgnoresAccessChecksToAttribute` is meant to be used for some SRE scenarios, but in fact it works with normal compiled assemblies too.

**Comment by lambdageek** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/47989 which has some runtime tests that are currently disabled on Mono.
