### ISSUE TITLE
The required library libhostfxr.so could not be found.

### ISSUE THREAD

**Issue by huangchinlin** [dotnet/runtime#48029]
I've created a worker(cli: dotnet new worker) project in ubuntu 20.04 which run on a raspberry pi, but get error when start the service via systemd.

the error message is:  A fatal error occurred. The required library libhostfxr.so could not be found.

I have installed the dotnet sdk and runtime, but the situation is the same.

---------------
dotnet --info
---------------
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-arm64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

------
ENV:
------
```
DOTNET_ROOT=/usr/local/share/dotnet
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/share/dotnet
```
------
Program.cs
------
```
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSystemd()
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddHostedService<Worker>();
                });
    }
```

Please advise the solution for this. Thanks.

**Comment by vitek-karas** [comment]
I assume it works if you run it from shell, right?

Would it be possible to collect a host trace? Before starting the process set env. variables:
```console
COREHOST_TRACE=1
COREHOST_TRACEFILE=/tmp/host_trace.txt
```

It should produce the `/tmp/host_trace.txt`, which should include more information about the failure. Note that this file contains some env. variable values, and directory/file names from the machine, so only share it if you're OK with sharing that information.

At the very least it should contain the path where it was looking for `hostfxr`.

I would also expect to see more in the error message. It should either say where it was look (in the error message itself), or there should be more lines to the error message with things like `If this is a self-contained application, that library should exist in` and so on.

Is this a framework dependent or self-contained application?

**Comment by huangchinlin** [comment]
> I assume it works if you run it from shell, right?
> 
> Would it be possible to collect a host trace? Before starting the process set env. variables:
> 
> ```
> COREHOST_TRACE=1
> COREHOST_TRACEFILE=/tmp/host_trace.txt
> ```
> 
> It should produce the `/tmp/host_trace.txt`, which should include more information about the failure. Note that this file contains some env. variable values, and directory/file names from the machine, so only share it if you're OK with sharing that information.
> 
> At the very least it should contain the path where it was looking for `hostfxr`.
> 
> I would also expect to see more in the error message. It should either say where it was look (in the error message itself), or there should be more lines to the error message with things like `If this is a self-contained application, that library should exist in` and so on.
> 
> Is this a framework dependent or self-contained application?

Thanks for reply, Vitek-karas. 
My app is framework dependent, and can run it well from the shell.

I have built again the environment, and also install SDK which version is 5.0.103 thru dotnet-install.sh.
The sample worker app can run very well from both shell and systemd.

The difference to last environment is install the dotnet sdk by apt or dotnet-install.sh, in last environment, I used apt to install sdk. I think it is root cause to this situation because raspberry pi is arm64 architecture, the correct way to install sdk and runtime is thru dotnet-install.sh.
