### ISSUE TITLE
ReferenceHandler.Preserve cannot handle structs boxed in object

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#48032]
### Description

When a struct is boxed in `object`, ReferenceHandler.Preserve is unable to handle correctly the instance and serialization goes into infinite loop.

We probably need to detect if `Preserve` is set and add additional object preservation logic to the call-site before `object` looks for the runtime type and redirects to the converter for it (before `TryWriteAsObject`).

```cs
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ConsoleApp8
{
    class Program
    {
        static void Main(string[] args)
        {
            IValueNode root = new ValueNode();
            root.Next = root;

            var options = new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.Preserve };

            string json = JsonSerializer.Serialize<object>(root, options);
            Console.WriteLine(json);
        }
    }

    struct ValueNode : IValueNode
    {
        public object Next { get; set; }
    }

    interface IValueNode 
    { 
        public object Next { get; set; }
    }
}
```

### Regression?

No

**Comment by layomia** [comment]
Triage - since this  is not a regression in 6.0 and an edge case, let's tackle this in 7.0.

**Comment by layomia** [comment]
Since this manifests as an infinite loop, let's try to tackle it in .NET 6.
