### ISSUE TITLE
Path.GetFileName Returns empty string for folders or files in the root of the UNC Path

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#48039]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/PathGetFileName-Returns-empty-string-fo/1291165)._

---
\[severity:It's more difficult to complete my work\] I noticed a problem in .NET 5 with the Path.GetFileName function. Looking at the source for this it appears to have been changed to using ReadOnlySpan's compared to the much simplier previous implementation. The problem is related to UNC paths where the folder or file that is being attempted to be extracted from the path will return "" if the folder or file is in the root of the UNC path. For example: `"\\\\127.0.0.1\\Test.txt" or "\\\\127.0.0.1\\Test Folder" both return ""` however... `"\\\\127.0.0.1\\Test\\Test.txt"` and `"\\\\127.0.0.1\\Test\\Test` Folder" return "Test.txt" and "Test Folder" respectively. If I was to have a guess, i'd say the problem lies somewhere in the GetPathRoot function that is used within GetFileName(ReadOnlySpanpath) as the remainder of the implementation looks to be the same. I have worked around the issue by replacing `"\\" with "\"` within the path prior to extracting the filename\\folder name, which seems to work ie For escaped string dir = `"\\\\127.0.0.1\\Test" var newDir = dir.Replace(@"\\", @"\")` results in `"\\127.0.0.1\\Test"` and `GetFileName(newDir)` produces the result "Test" Not sure what the problem is with the UNC paths and id imagine the new behaviour is not intentional.

---
#### Mila Zhou[MSFT] on 12/18/2020, 00:49 AM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen? It would be very helpful if you could provide some screenshots of this problem.</p>
<p>We look forward to hearing from you!</p>

#### Lachlan Anderson on 1/10/2021, 08:46 PM: 

<p>I have attached a c# console application to demonstrate what I am trying to say, please compile and run the file and refer to below for my assessment of the results.</p>
<p>You will note the tests in line 3.0 and 4.0 will return an empty string for a UNC path, whereas tests 3.1 and 4.1 with the equivalent path relative to the system itself (such as C:) will return the folder or filename correctly.</p>
<p>Prior to migrating to .NET 5 both scenarios returned the results shown in 3.1 and 4.1 and the implementation has changed since .NET 4.8 which has likely caused the problem.</p>
<p>Cheers,</p>
<p><a target='_blank' href="https://aka.ms/dc/file?name=B54cd7c8bcf1847f39b784e430b9d16cf637459370705797601_Program.cs&amp;tid=54cd7c8bcf1847f39b784e430b9d16cf637459370705797601">Program.cs</a></p>

#### Feedback Bot on 12/29/2020, 06:58 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Feedback Bot on 1/10/2021, 11:11 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Fiona Niu[MSFT] on 2/7/2021, 09:52 PM: 

<p>Thanks for providing the information. But we’re unable to open and download your attached program.cs file. Could you please share a sample project or application with us that consistently reproduces the issue along with the steps taken to cause the problem to occur. Once you have your sample project, please reply back to me with it attached. Any feedback would be welcome.</p>
<p>We look forward to hearing from you!</p>

#### Lachlan Anderson on 2/8/2021, 04:56 PM: 

<p>Hi, I have uploaded an example solution to the following github since I can no longer open that .cs file on here either.</p>
<p><a target='_blank' href="https://github.com/M26666/Path.GetFileNameExampleApp">https://github.com/M26666/Path.GetFileNameExampleApp</a></p>
<p>The console app will step through a number of tests each scenario for both a system path such as “C:\Some Folder\Some File” compared to a UNC path.</p>
<p>What you will notice is, any folder or file one level up from the root of the UNC path (the “\\”), will return an empty string. However the equivalent test on a system path will pass as expected. Prior to migrating to .NET 5 this behaviour was not observed for UNC paths.</p>

#### Fiona Niu[MSFT] on 2/8/2021, 05:48 PM: 

<p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

---
### Original Solutions
(no solutions)

**Comment by carlossanlop** [comment]
This is not a bug. This was an intentional breaking change introduced in .NET Core so we could handle UNC paths correctly.

An UNC path root consists of `servername + share`, where `servername` is the first segment after the double backlash and before the first single slash, and `share` is the first folder after the first single slash. The official MS Docs article describing UNC paths confirms this: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dfsc/149a3039-98ce-491a-9268-2f5ddef08192

The behavior you're seeing is because the provided path either does not have a `filename` after the `servername + share` root, or because the root does not have two segments.

The `GetFileName` code in .NET Core internally calls `GetPathRoot`, which in the case of a UNC path, returns `servername + share` as the root.

Here's a small code snippet that verifies the behavior of `GetPathRoot` and `GetFileName`. I tested it in .NET Framework 4.8 and in .NET 5.0. The correct output is what .NET 5.0 is returning:

```cs
using System;
using System.IO;

namespace MyNamespace
{
    public class MyClass
    {

        static void Main()
        {
            string[] roots = new[]                  // .NET 5.0           | .NET Framework 4.8
            {
                @\\127.0.0.1,                     // [\\127.0.0.1]      | [\\127.0.0.1]
                @\\127.0.0.1\,                    // [\\127.0.0.1\]     | [\\127.0.0.1\]
                @\\127.0.0.1\path,                // [\\127.0.0.1\path] | [\\127.0.0.1\path]
                @\\127.0.0.1\path\,               // [\\127.0.0.1\path] | [\\127.0.0.1\path]
                @\\127.0.0.1\path\path,           // [\\127.0.0.1\path] | [\\127.0.0.1\path]
                @\\127.0.0.1\path\path\,          // [\\127.0.0.1\path] | [\\127.0.0.1\path]
            };

            foreach (string root in roots)
            {
                string result = Path.GetPathRoot(root);
                Console.WriteLine($"[{root}] => [{result}]");
            }


            string[] paths = new[]                 // .NET 5.0          | .NET Framework 4.8
            {
                @\\127.0.0.1\folder,                // []               | [folder]
                @\\127.0.0.1\folder\,               // []               | []
                @\\127.0.0.1\folder\my file.txt,    // [my file.txt]    | [my file.txt]
                @\\127.0.0.1\file.txt,              // []               | [file.txt]
                @\\127.0.0.1\my file.txt,           // []               | [my file.txt]
                @\\127.0.0.1\my folder,             // []               | [my folder]
                @\\127.0.0.1\my folder\,            // []               | []
                @\\127.0.0.1\my folder\file.txt,    // [file.txt]       | [file.txt]
                @"C:\folder",                       // [folder]         | [folder]
                @"C:\folder\",                      // []               | []
                @"C:\my folder",                    // [my folder]      | [my folder]
                @"C:\my folder\",                   // []               | []
                @"C:\folder\file.txt",              // [file.txt]       | [file.txt]
                @"C:\folder\my file.txt",           // [my file.txt]    | [my file.txt]
                @"C:\my folder\file.txt",           // [file.txt]       | [file.txt]
                @"C:\my folder\my file.txt"         // [my file.txt]    | [my file.txt]
            };

            foreach (string path in paths)
            {
                string result = Path.GetFileName(path);
                Console.WriteLine($"[{path}] => [{result}]");
            }

            Console.WriteLine("Press enter to exit.");
            Console.ReadLine();
        }
    }
}

```
