### ISSUE TITLE
dotnet.timezones.blat file size has increased 34% since net5.0

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#48061]
1. publish a `net5.0` Blazor WASM app. Inspect the `bin\Release\net5.0\publish\wwwroot\_framework\dotnet.timezones.blat.br` file size. It should be around `66 KB`.
2. publish a `net6.0` Blazor WASM app using the latest runtime. Inspect the `bin\Release\net5.0\publish\wwwroot\_framework\dotnet.timezones.blat.br` file size. It is `90 KB`.

We should verify if this size increase is expected, and it is warranted.

We should be able to trim a decent amount of data out of this file. The way the IANA timezone database works is that it contains every base time offset transition from the beginning of time, until about 2038. We should investigate if we can only include daylight savings transitions between certain dates. For example, we could only include transitions from `1970` - `DateTime.Now + 10 years`. This should trim a lot of transitions that are not going to be used.

Another (probably bad) idea would be to use the Windows time zone data instead. This data is less accurate, but is definitely smaller.

You can see the regression at https://aka.ms/dotnetperfstatus

![image](https://user-images.githubusercontent.com/8291187/107398650-73de9280-6ac5-11eb-85e7-67819928fbc7.png)

cc @tqiu8

**Comment by CoffeeFlux** [comment]
cc: @tqiu8

**Comment by Clockwork-Muse** [comment]
> The way the IANA timezone database works is that it contains every base time offset transition from the beginning of time, until about 2038.

The [IANA tzdb contains a list of transition _changes_](https://en.wikipedia.org/wiki/Tz_database#Example_zone_and_rule_lines), not the transitions themselves.  Any future rules are likely within 1-2 years, since nobody plans to change their DST rules (or offsets) 38 years in advance.  There might be precompiled versions of the offsets for each year, but since they usually retain the rules they can always get the data for the future years.

> Another (probably bad) idea would be to use the Windows time zone data instead. This data is less accurate, but is definitely smaller.

It's mostly smaller because it's already trimmed (ignoring the accuracy issues).

> We should verify if this size increase is expected, and it is warranted.

... Outside of any encoding changes, my first guess is that it moved from a partial database to the full database.

Although the database is updated multiple times a year, this is generally only one or two timezones each time, about 120 bytes per entry.

**Comment by tqiu8** [comment]
Think there's an option for this in `zic` that will limit based on timestamp range.

**Comment by eerhardt** [comment]
Thanks for the link, @tqiu8. Looks like another option is to use `-b slim`:

```
-b bloat
              Output backward-compatibility data as specified by bloat.
              If bloat is fat, generate additional data entries that
              work around potential bugs or incompatibilities in older
              software, such as software that mishandles the 64-bit
              generated data.  If bloat is slim, keep the output files
              small; this can help check for the bugs and
              incompatibilities.  Although the default is currently fat,
              this is intended to change in future zic versions, as
              software that mishandles the 64-bit data typically
              mishandles timestamps after the year 2038 anyway.  Also
              see the -r option for another way to shrink output size.
```

**Comment by tqiu8** [comment]
`-b slim` is looking promising in initial results

**Comment by akoeplinger** [comment]
@tqiu8 just curious, did anyone look at the `-r` option that the zic manpage mentions to further shrink the size?

**Comment by tqiu8** [comment]
Using `-r` in addition to `-b` option actually didn't decrease the size as much as `-b` alone and it also caused tests that go back to `01/01/0001` to fail.

**Comment by eerhardt** [comment]
Just to follow up here, this is the latest results from perf lab:

![image](https://user-images.githubusercontent.com/8291187/108128843-fdb4cf80-7072-11eb-842b-ec278bedafdd.png)

Nice work here @tqiu8!
