### ISSUE TITLE
[Apple Silicon] Issue with VS for Mac and Side By Side arm64/x64 runtime installs

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#48068]
**Setup:**
Mac OS: Big Sur(11.2) - Apple M1 chip
VSFM:8.9 Preview (8.9 build 1582)
3.1.406(runtime:3.1.12) & 5.0.103(runtime:5.0.3)
.NET 6 arm64: 6.0.100-preview.1.21103.13(runtime 6.0.0-preview.1.21102.12)

**Steps to reproduce:**
1.Create a project with TFM 5.0 or 3.1 on VSFM or Cli
2.Run this project

**Expected result:**
This project will run success

**Actual result:**
Run failed with "Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3/libhostpolicy.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3/libhostpolicy.dylib: mach-o, but wrong architecture
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.3]"
![image](https://user-images.githubusercontent.com/1578239/107326882-28d57700-6ae7-11eb-9a40-eb28e09d4f41.png)

**Note:**
1.For test project on VSM,project will always keep running

VSFM-info:
=== Visual Studio Enterprise 2019 for Mac (Preview) ===

Version 8.9 Preview (8.9 build 1582)
Installation UUID: d6adba47-7cfd-43b6-b2f0-580b51383850
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.9.0-4.21104.8+2fc92d84e746c3aab75f0930278ea6675cd5bb5c

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.1.21103.13/Sdks
SDK Versions:
	6.0.100-preview.1.21103.13
	5.0.103
	3.1.406
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.1.21102.12
	5.0.3
	3.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.406

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

A valid Xcode installation was not found at the configured location: '/Library/Developer/CommandLineTools'

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin Designer ===

Version: 16.9.0.309
Hash: 9a5259fb5
Branch: remotes/origin/9a5259fb55e54a445c145ab5ea29c04a418deed2
Build date: 2021-02-04 09:34:28 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.21
Hash: 57e40ba
Branch: remotes/origin/main
Build date: 2021-01-08 01:57:14 UTC

=== Android Device Manager ===

Version: 16.9.0.14
Hash: 0fdccda
Branch: remotes/origin/main
Build date: 2021-01-08 01:57:36 UTC

=== Build Information ===

Release ID: 809001582
Git revision: b0620b767dbf9f79bbacc2053ae155a66f147e04
Build date: 2021-02-04 12:13:43-05
Build branch: release-8.9
Xamarin extensions: b0620b767dbf9f79bbacc2053ae155a66f147e04

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:06:51 PST 2021
    root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

**Comment by jeffschwMSFT** [comment]
@NicoleWang001 looks like you have a mix of X64 (which runs emulated) and Arm64 installed on this machine.  We are currently investigating how to have these co-exist.  In the short term to try out .NET 6 Arm64 you will need to uninstall the X64 versions.  Is that possible?

@vitek-karas @sdmaclea

**Comment by smoothdeveloper** [comment]
Moving older versions from `/usr/local/share/dotnet/shared/Microsoft.NETCore.App/` fixes hitting this error from programs that binds to older runtimes in my case.

Is that the recommended work around?

**Comment by jeffschwMSFT** [comment]
@smoothdeveloper we are actively designing a durable solution.  Feel free to join the discussion at https://github.com/dotnet/sdk/issues/16896.

**Comment by tarunparmar** [comment]
I installed the 6.0.0 Arm64 preview ([link](https://dotnet.microsoft.com/download/dotnet/6.0) ) and then modified .csproj by updating 5.0 to 6.0 and the error went away. 

`<TargetFramework>net6.0</TargetFramework>`

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/installer/issues/11164
