### ISSUE TITLE
NetworkInterface.IsReceiveOnly throws on osx

### ISSUE THREAD

**Issue by haraldsteinlechner** [dotnet/runtime#48062]
Stumbled on this when carelessly serializing NetworkInterface instances. On mac, this throws an excpetion:
`The information requested is unavailable on the current platform. The unsupported member type is located on type 'System.Boolean'. Path: $.args.fingerprint.nics.nic.IsReceiveOnly.` whereas it works on windows and linux.

### Description

* https://github.com/dotnet/runtime/blob/eec1e2518ebafadaa08dce19098150bd1e8f2130/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/BsdNetworkInterface.cs#L161 clearly throws this exception, as opposed to
* https://github.com/dotnet/runtime/blob/eec1e2518ebafadaa08dce19098150bd1e8f2130/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L161 which simply returns false

### Configuration

* net5.0, on big sur 11.2

### Regression?

unknown

### Other information

not clear if this a bug or intended. at least strange linux handles it differently, also this is not handled in the documentation: `This property is not valid on computers running operating systems earlier than Windows XP.` (https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.isreceiveonly?view=net-5.0)

Thanks for looking  into it, bests 
harald

**Comment by wfurt** [comment]
It was like that since early beginning (e.g. OsxNetworkInterface.cs) I changed Linux while refactoring the code in https://github.com/dotnet/corefx/pull/41490. Since the concept does not really exist on Unix, I feel that `false` is reasonable since the interface is NOT `ReceiveOnly`. I think we should make it consistent and we can update documentation as well.

**Comment by karelz** [comment]
Triage: We are supportive.
@haraldsteinlechner do you want to put up a PR?

**Comment by haraldsteinlechner** [comment]
yes, will prepare it..

**Comment by jaymin93** [comment]
> It was like that since early beginning (e.g. OsxNetworkInterface.cs) I changed Linux while refactoring the code in [dotnet/corefx#41490](https://github.com/dotnet/corefx/pull/41490). Since the concept does not really exist on Unix, I feel that `false` is reasonable since the interface is NOT `ReceiveOnly`. I think we should make it consistent and we can update documentation as well.

so i need to return false from the get is that correct  also for documentation what should i do to make changes?

**Comment by karelz** [comment]
@jaymin93 thanks for your PR! I don't think there are docs changes needed.

**Comment by jaymin93** [comment]
@karelz so this changes are only needed for the fixing the issue  ?
