### ISSUE TITLE
Question about garbage collection in async Main

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#48073]
I was reading a blog post about [keeping async methods alive](https://devblogs.microsoft.com/pfxteam/keeping-async-methods-alive/) and it made me think about how this could apply to `async Main`. Say I have

```c#
static async Task Main()
{
    var c = new C();
    await c.NeverReturnsAsync();
}
```

Is it possible that at some point, since `c` isn't rooted, the GC could decide that it and any work it's doing (including any `async` continuations that are also not rooted) is eligible for garbage collection?

**Comment by stephentoub** [comment]
What would it matter for your example?

**Comment by WizardBrony** [comment]
@stephentoub That's a fair question. I assume your point being if `NeverReturnsAsync` isn't actually doing anything what does it matter. The scenario I was thinking of in my head was `NeverReturnsAsync` infinitely looping and `await`ing something that isn't rooted, which in my example scenario was a local variable (versus `static` field) `HttpListener` variable. But after thinking more about it, even though the field `HttpListener` isn't rooted, its `async` operations are probably somehow rooted by `http.sys`, correct?

**Comment by stephentoub** [comment]
> its async operations are probably somehow rooted by http.sys, correct?

They have to be, or else those async operations are buggy.  If I have a method like:
```C#
var tcs = new TaskCompletionSource();
... // scheduler some operation that will eventually call tcs.SetResult();
return tcs.Task;
```
the underlying asynchronous operation needs to be able to call tcs.SetResult, which means it needs to have a rooted reference to tcs; if it doesn't, it's buggy.  And then any async continuations off of that returned task (e.g. someone awaiting it) is kept alive as a result.  And so on.

**Comment by WizardBrony** [comment]
@stephentoub Makes perfect sense. Thanks a lot.
