### ISSUE TITLE
[MONO][PERF] 28-32% Pefromance Regression in System.Tests.Perf_Random

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#48087]
This seems to have been caused by this change: https://github.com/dotnet/runtime/commit/5ee25aa5fee9c08dc34c962023ec75956edd3194

Below is an automated report.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [8c76312b621e2cdb22ca0ee603c5b0e1919134a2](https://github.com/dotnet/runtime/commit/8c76312b621e2cdb22ca0ee603c5b0e1919134a2)
Compare | [f80b0575d44ccdc85a18c8dc2dbdcd29f7788d0b](https://github.com/dotnet/runtime/commit/f80b0575d44ccdc85a18c8dc2dbdcd29f7788d0b)

### Regressions in System.Tests.Perf_Random

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Next_int_int](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_int_int.html>) | 11.43 ns | 15.06 ns | 1.32 | | |
[Next_int](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.Next_int.html>) | 11.26 ns | 14.68 ns | 1.30 | | |
[NextDouble](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Tests.Perf_Random.NextDouble.html>) | 10.50 ns | 13.45 ns | 1.28 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Tests.Perf_Random_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Tests.Perf_Random_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Tests.Perf_Random_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Tests.Perf_Random.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Random*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-f2044faf-d6c1-4660-b3fe-4cb94290af02fbe782738754cdeb9/0537b65f-5b15-4c17-a8c3-303e83436fb6.zip?sv=2019-07-07&se=2021-02-19T22%3A28%3A22Z&sr=c&sp=rl&sig=WCzIaF1gSfgjiX9UGSiRHaT%2FJPgMWaSkuISchvGO414%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-a5376f79-b3b9-4b87-b07f-025496022953a8626340bfc4910a9/a600e664-486c-4f9d-8596-21153f0d1154.zip?sv=2019-07-07&se=2021-02-20T09%3A46%3A26Z&sr=c&sp=rl&sig=WuprmCVfPKHTJ%2BFMkvKdHVi%2FO77Lb2nk7SZGV4ZClBI%3D>)

#### System.Tests.Perf_Random.Next_int_int

```log
[ 9.932 ; 10.246) | @@@@@@@@@
[10.246 ; 10.648) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10.648 ; 11.052) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11.052 ; 11.369) | @@@@@@@@@
[11.369 ; 11.770) | @@@@@@@@@@@@@@@@@@@@@@
[11.770 ; 12.220) | @@@@@@@@@
[12.220 ; 12.611) | @@
[12.611 ; 12.981) | 
[12.981 ; 13.382) | @
[13.382 ; 13.783) | 
[13.783 ; 14.184) | 
[14.184 ; 14.620) | 
[14.620 ; 15.021) | @@@@@@@@@@@@@@@@
[15.021 ; 15.648) | @@@@@@@@
```
#### System.Tests.Perf_Random.Next_int

```log
[ 9.120 ;  9.587) | @@@@
[ 9.587 ; 10.040) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10.040 ; 10.598) | @@@@@@@@@@@@@@@@@@@@@
[10.598 ; 11.042) | @@
[11.042 ; 11.495) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11.495 ; 12.031) | @
[12.031 ; 12.485) | @@@
[12.485 ; 13.019) | 
[13.019 ; 13.472) | @
[13.472 ; 13.926) | 
[13.926 ; 14.551) | 
[14.551 ; 15.071) | @@@@@@@@@@@@@@@@@@@@
[15.071 ; 15.569) | @@@
```
#### System.Tests.Perf_Random.NextDouble

```log
[ 8.940 ;  9.346) | @@@@@@@@
[ 9.346 ;  9.758) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.758 ; 10.088) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10.088 ; 10.386) | @
[10.386 ; 10.807) | @@@@@@@@@@@@@
[10.807 ; 11.219) | @@@@@@@@@@@@@@@@@
[11.219 ; 11.723) | @@
[11.723 ; 12.347) | 
[12.347 ; 12.759) | @
[12.759 ; 13.171) | 
[13.171 ; 13.723) | @@@@@@@@@@@@@
[13.723 ; 14.267) | @@@@@@@@@
[14.267 ; 14.835) | @
[14.835 ; 15.402) | @
[15.402 ; 15.813) | 
[15.813 ; 16.122) | 
[16.122 ; 16.534) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [8c76312b621e2cdb22ca0ee603c5b0e1919134a2](https://github.com/dotnet/runtime/commit/8c76312b621e2cdb22ca0ee603c5b0e1919134a2)
Compare | [f80b0575d44ccdc85a18c8dc2dbdcd29f7788d0b](https://github.com/dotnet/runtime/commit/f80b0575d44ccdc85a18c8dc2dbdcd29f7788d0b)

### Regressions in PerfLabTests.BlockCopyPerf

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CallBlockCopy](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/PerfLabTests.BlockCopyPerf.CallBlockCopy(numElements%3a%2010).html>) | 9.18 ns | 10.88 ns | 1.19 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/PerfLabTests.BlockCopyPerf_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/PerfLabTests.BlockCopyPerf.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'PerfLabTests.BlockCopyPerf*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-f2044faf-d6c1-4660-b3fe-4cb94290af02fbe782738754cdeb9/0537b65f-5b15-4c17-a8c3-303e83436fb6.zip?sv=2019-07-07&se=2021-02-19T22%3A28%3A22Z&sr=c&sp=rl&sig=WCzIaF1gSfgjiX9UGSiRHaT%2FJPgMWaSkuISchvGO414%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-a5376f79-b3b9-4b87-b07f-025496022953a8626340bfc4910a9/a600e664-486c-4f9d-8596-21153f0d1154.zip?sv=2019-07-07&se=2021-02-20T09%3A46%3A26Z&sr=c&sp=rl&sig=WuprmCVfPKHTJ%2BFMkvKdHVi%2FO77Lb2nk7SZGV4ZClBI%3D>)

#### PerfLabTests.BlockCopyPerf.CallBlockCopy(numElements: 10)

```log
[ 8.333 ;  8.667) | @@@@@@@@@@@@@@@@@@@@@@@@
[ 8.667 ;  9.018) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.018 ;  9.304) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.304 ;  9.598) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.598 ;  9.988) | @@@@@@@@@@@@@@@
[ 9.988 ; 10.360) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10.360 ; 10.595) | 
[10.595 ; 11.003) | @@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment]
This is the same as https://github.com/dotnet/runtime/issues/47870.

**Comment by stephentoub** [comment]
Essentially, yes, these got slower, but you should see corresponding big improvements in the "unseeded" variants of these tests.  Basically, if you created a Random with a specific seed, the methods get a bit slower as there's one more virtual indirection in the call path.  But if you created a Random without a specific seed (which is how they're actually created in the majority of production scenarios), operations get much faster, some upwards of 30x.

**Comment by naricc** [comment]
@stephentoub Makes sense to me. Closing this one out.
