### ISSUE TITLE
[Release/3.1] MemoryCacheTest.Trim  failing in the release/3.1 

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#48095]
```
:\h\w\9F560893\w\B745096D\e>"C:\h\w\9F560893\p\dotnet.exe" exec --runtimeconfig System.Runtime.Caching.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Caching.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Runtime.Caching.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Caching.Tests (found 30 of 40 test cases)
  Starting:    System.Runtime.Caching.Tests (parallel test collections = on, max threads = 46)
    MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim [FAIL]
      Assert.Equal() Failure
      Expected: 23
      Actual:   22
      Stack Trace:
        /_/src/System.Runtime.Caching/tests/System.Runtime.Caching/MemoryCacheTest.cs(991,0): at MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim()
  Finished:    System.Runtime.Caching.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Caching.Tests  Total: 30, Errors: 0, Failed: 1, Skipped: 0, Time: 4.633s
----- end Tue 02/09/2021 21:13:13.89 ----- exit code 1 ----------------------------------------------------------
 Tue 02/09/2021-21:13:13.89
```

Failure pr https://github.com/dotnet/corefx/pull/43029

**Comment by danmoseley** [comment]
This test seems very stable. There are no subsequent records of it failing. Going back at least to June, there has been only one failure outside of a PR of a test in this class, and it wasn't this one.


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Result == "Fail"
| where Type == "MonoTests.System.Runtime.Caching.MemoryCacheTest"
//| where Branch !startswith "refs/pull"
| project 
    Method,
    Branch,
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,
  Duration,
Build = tostring(parse_json(Properties).BuildNumber) //,  Console_log = Message,   StackTrace  //WorkItemFriendlyName, Method//bin(Finished, 1d)
```
Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI1TUW%2faQAx%2br9T%2f4OUJJJaUaZr2wqQWxsYk2g6i9TE6EkMOEl%2fkuyxD4sfPlwCj26T2KbH9fbY%2f2xejdQu0deHs9dUBtkYT7DRlI02EDE%2bGdzOHpQVDZ2OW%2fQ%2f6zaxalHw9IIoO0OTICFNN2uaYwacRkGl6b4fvbrK%2bT9HFu%2fIwGkEwVboIPPcY%2bl5jjfeqxDbaSDHT2HB4EyouP7z%2f%2bTE0FVIAhl9AdrjLpmCOLjdZi45lBg%2b0dIrdk3b5LW9snKM4TBVIK5L9AjxlU37N0hk5ZFJF8gXdZJws0NVM9vOvClOHWQAQRX%2bTGsqSH6rQWfv3DyOKDP8ZSryvOilzQ8Y3aMPl3srww0VNTpcYjlWaa9qEcywN772FHvdM5R0rSnN4Y70224g4CBjXNqrqwg%2f6ABWbrTQA11cAp6EMOqMjt8ajrrDQJB2BM9ax1O1Vii0mW2uo98gyX3YabT%2bc4Fr27bQhv43%2bM3oyNrTWm5qVj78iWXqJ73I9LIV33nbrumXR%2bHIyJTDtRGzNx778vIToZz1sHd0pDk4X2%2fomx%2fJi3NW6yF5RqcXd1%2bUKuS97HQCIcGsKTAqzEf4crVUbFD%2fI1aW7mFWK%2fmROL2zKGikr9q3E41aiaKWpd24Nhv4NgSzuNyI8u0TDAwAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1TUW%2faQAx%2br9T%2f4OUJJJaUaZr2wqQWxsYk2g6i9TE6EkMOEl%2fkuyxD4sfPlwCj26T2KbH9fbY%2f2xejdQu0deHs9dUBtkYT7DRlI02EDE%2bGdzOHpQVDZ2OW%2fQ%2f6zaxalHw9IIoO0OTICFNN2uaYwacRkGl6b4fvbrK%2bT9HFu%2fIwGkEwVboIPPcY%2bl5jjfeqxDbaSDHT2HB4EyouP7z%2f%2bTE0FVIAhl9AdrjLpmCOLjdZi45lBg%2b0dIrdk3b5LW9snKM4TBVIK5L9AjxlU37N0hk5ZFJF8gXdZJws0NVM9vOvClOHWQAQRX%2bTGsqSH6rQWfv3DyOKDP8ZSryvOilzQ8Y3aMPl3srww0VNTpcYjlWaa9qEcywN772FHvdM5R0rSnN4Y70224g4CBjXNqrqwg%2f6ABWbrTQA11cAp6EMOqMjt8ajrrDQJB2BM9ax1O1Vii0mW2uo98gyX3YabT%2bc4Fr27bQhv43%2bM3oyNrTWm5qVj78iWXqJ73I9LIV33nbrumXR%2bHIyJTDtRGzNx778vIToZz1sHd0pDk4X2%2fomx%2fJi3NW6yF5RqcXd1%2bUKuS97HQCIcGsKTAqzEf4crVUbFD%2fI1aW7mFWK%2fmROL2zKGikr9q3E41aiaKWpd24Nhv4NgSzuNyI8u0TDAwAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI1TUW%2faQAx%2br9T%2f4OUJJJaUaZr2wqQWxsYk2g6i9TE6EkMOEl%2fkuyxD4sfPlwCj26T2KbH9fbY%2f2xejdQu0deHs9dUBtkYT7DRlI02EDE%2bGdzOHpQVDZ2OW%2fQ%2f6zaxalHw9IIoO0OTICFNN2uaYwacRkGl6b4fvbrK%2bT9HFu%2fIwGkEwVboIPPcY%2bl5jjfeqxDbaSDHT2HB4EyouP7z%2f%2bTE0FVIAhl9AdrjLpmCOLjdZi45lBg%2b0dIrdk3b5LW9snKM4TBVIK5L9AjxlU37N0hk5ZFJF8gXdZJws0NVM9vOvClOHWQAQRX%2bTGsqSH6rQWfv3DyOKDP8ZSryvOilzQ8Y3aMPl3srww0VNTpcYjlWaa9qEcywN772FHvdM5R0rSnN4Y70224g4CBjXNqrqwg%2f6ABWbrTQA11cAp6EMOqMjt8ajrrDQJB2BM9ax1O1Vii0mW2uo98gyX3YabT%2bc4Fr27bQhv43%2bM3oyNrTWm5qVj78iWXqJ73I9LIV33nbrumXR%2bHIyJTDtRGzNx778vIToZz1sHd0pDk4X2%2fomx%2fJi3NW6yF5RqcXd1%2bUKuS97HQCIcGsKTAqzEf4crVUbFD%2fI1aW7mFWK%2fmROL2zKGikr9q3E41aiaKWpd24Nhv4NgSzuNyI8u0TDAwAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1TUW%2faQAx%2br9T%2f4OUJJJaUaZr2wqQWxsYk2g6i9TE6EkMOEl%2fkuyxD4sfPlwCj26T2KbH9fbY%2f2xejdQu0deHs9dUBtkYT7DRlI02EDE%2bGdzOHpQVDZ2OW%2fQ%2f6zaxalHw9IIoO0OTICFNN2uaYwacRkGl6b4fvbrK%2bT9HFu%2fIwGkEwVboIPPcY%2bl5jjfeqxDbaSDHT2HB4EyouP7z%2f%2bTE0FVIAhl9AdrjLpmCOLjdZi45lBg%2b0dIrdk3b5LW9snKM4TBVIK5L9AjxlU37N0hk5ZFJF8gXdZJws0NVM9vOvClOHWQAQRX%2bTGsqSH6rQWfv3DyOKDP8ZSryvOilzQ8Y3aMPl3srww0VNTpcYjlWaa9qEcywN772FHvdM5R0rSnN4Y70224g4CBjXNqrqwg%2f6ABWbrTQA11cAp6EMOqMjt8ajrrDQJB2BM9ax1O1Vii0mW2uo98gyX3YabT%2bc4Fr27bQhv43%2bM3oyNrTWm5qVj78iWXqJ73I9LIV33nbrumXR%2bHIyJTDtRGzNx778vIToZz1sHd0pDk4X2%2fomx%2fJi3NW6yF5RqcXd1%2bUKuS97HQCIcGsKTAqzEf4crVUbFD%2fI1aW7mFWK%2fmROL2zKGikr9q3E41aiaKWpd24Nhv4NgSzuNyI8u0TDAwAA&saw=1)
|Method|Branch|Pipeline|Pipeline_Configuration|OS|Arch|Test|Result|Finished|Duration|Build|
|---|---|---|---|---|---|---|---|---|---|---|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime-staging|release|windows.10.amd64.server20h1.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:25:39.6290000|0.327|20210611.24|
|GetValues|refs/pull/54062/merge|runtime-staging|release|windows.10.amd64.server20h1.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:25:39.6290000|0.01|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime-staging|release|windows.10.amd64.server20h1.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:25:39.6290000|0.327|20210611.24|
|GetValues|refs/pull/54062/merge|runtime-staging|release|windows.10.amd64.server20h1.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:25:39.6290000|0.01|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:46:21.6170000|0.006|20210611.24|
|GetValues|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:46:21.6170000|0.003|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:47:20.1860000|0.01|20210611.24|
|GetValues|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:47:20.1860000|0.006|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:48:15.9240000|0.013|20210611.24|
|GetValues|refs/pull/54062/merge|runtime|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:48:15.9240000|0.004|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime-staging|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:58:06.3730000|0.02|20210611.24|
|GetValues|refs/pull/54062/merge|runtime-staging|Release|ubuntu.1804.amd64.open.rt|wasm|test/functional/cli/innerloop/|Fail|2021-06-11 13:58:06.3730000|0.013|20210611.24|
|AddOrGetExisting_CacheItem_CacheItemPolicy|refs/pull/54062/merge|runtime-staging|Release|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-06-11 14:06:12.7930000|0.003|20210611.24|
|GetValues|refs/pull/54062/merge|runtime-staging|Release|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-06-11 14:06:12.7930000|0|20210611.24|
|TestExpiredGetValues|refs/heads/main|runtime-staging|Release|osx.1100.arm64.open|arm64|test/functional/cli/innerloop/|Fail|2021-06-30 13:07:47.2540000|0.104|20210630.20|


@StephenMolloy I'm going to close on that basis.
