### ISSUE TITLE
Use WinRT API in netstandard2.0 library referenced by .NET 5.0 with IsOSPlatform check

### ISSUE THREAD

**Issue by chrfin** [dotnet/runtime#48102]
This is a cross-post with [https://stackoverflow.com/questions/66137060](https://stackoverflow.com/questions/66137060)

We are in the process of updating our `netcoreapp3.1` libraries and programs to `net5.0`. These libraries are referencing one `netstandard2.0` library which uses WinRT if supported via a NuGet reference to `Microsoft.Windows.SDK.Contracts`.    
This is checked via `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)`.  
If I now use this library from `net5.0` and execute the part using WinRT I get the following exception (executed on Win 10 20H2 with .NET 5.0.2):

> System.PlatformNotSupportedException: Operation is not supported on this platform. (0x80131539)

If I read up on the breaking changes for `net5.0` I get that this package is no longer needed/supported and to use WinRT you should target e.g. `net5.0-windows10.0.17763.0`. But I would like to keep the library platform-agnostic as `netstandard2.0` and keep using the `IsOSPlatform`\-switch, as other parts of the library are also used on Linux or using `net471`.  

**How can I make this work with `net5.0` as we did with `netcoreapp3.1`?**

**Comment by huoyaoyuan** [comment]
Try the new net5.0 package `Microsoft.Windows.SDK.Net`?

**Comment by chrfin** [comment]
@huoyaoyuan Thanks for the tip, but I can only find `Microsoft.Windows.SDK.NET.Ref` and that is a `net5.0` package...

**Comment by reflectronic** [comment]
You are supposed to multitarget your library and use `#if NET5_0`. I think they have intentionally moved away from using runtime OS checks, because it is pretty easy to make a mistake and get a broken library that way.

**Comment by AaronRobinsonMSFT** [comment]
@chrfin Thanks for the question. The [C#/WinRT tool](https://github.com/microsoft/CsWinRT) is indeed the way forward for WinRT support and your understanding of what to use is correct. As far a solution here, I would agree with @reflectronic's recommendation in this case. There may be another path forward but you would need to validate this with the C#/WinRT team. The C#/WinRT tool does support a .netstandard2.0 scenario so it may be possible to try another approach.
