### ISSUE TITLE
Mac Catalyst: Need dllmap support

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#48110]
This is the same as #44242, just for Mac Catalyst, we need support for dllmaps.

Currently calling `mono_dllmap_insert` asserts:

```
    frame #8: 0x000000010004bd37 MyCatalystApp`mono_assertion_message_unreachable(file=<unavailable>, line=<unavailable>) at goutput.c:234:2 [opt]
    frame #9: 0x0000000100116255 MyCatalystApp`mono_dllmap_insert(assembly=<unavailable>, dll=<unavailable>, func=<unavailable>, tdll=<unavailable>, tfunc=<unavailable>) at native-library.c:278:2 [opt]
```

/cc @akoeplinger

**Comment by CoffeeFlux** [comment]
Any chance I can convince you to migrate to using `PINVOKE_OVERRIDE` instead?

**Comment by CoffeeFlux** [comment]
This issue is also a variant of https://github.com/dotnet/runtime/issues/43204

In both cases, using `PINVOKE_OVERRIDE` instead seems like the best solution.

**Comment by rolfbjarne** [comment]
I can have a look and see if `PINVOKE_OVERRIDE` works for us.

**Comment by rolfbjarne** [comment]
Using `PINVOKE_OVERRIDE` seems to work, so I'm closing this.
