### ISSUE TITLE
[Wasm][AOT] using Nullable<T> forces the interpreter use in profiled AOT

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#48126]
### Description

Using Profiled AOT, the following code is run using with the intepreter:
```
int? GetMyNullable()
{
	for (int i = 0; i < 1000000; i++)
	{
	}

	return null;
}
```
Seemingly caused by the use of `int?`.

![image](https://user-images.githubusercontent.com/5839577/107575587-0d896b00-6bbe-11eb-85df-4fde4d638961.png)

Repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug48126/Bug48126

### Configuration

bb650672df2da1c7666e20d3abf713d050a954ca

### Regression?

No

**Comment by vargaz** [comment]
Can't reproduce this with master anymore.

**Comment by marek-safar** [comment]
@jeromelaban can you still observer the slowdown?

**Comment by jeromelaban** [comment]
It's not using the interpreter any more, thanks! I'll close the issue.
