### ISSUE TITLE
System.Text.Json.Serialization.JsonIgnoreAttribute Not functioning as expected

### ISSUE THREAD

**Issue by TheJaysH** [dotnet/runtime#48158]
Hi,

Apologies if this is not in the correct format.

I have started to use `System.Text.Json` and its going great so far! However I have ran into somewhat of a roadblock when dealing with a nullable property. My initial intent was to use a private setter for the property, this gives me the ability to throw a custom exception should the user try and access the property. The reason behind this is that the property is only populated under a particular condition. (The goal is to point the user to a link/docs on how to initialize the property)

```csharp
private Log[] _Logs { get; set; }

[JsonInclude]
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
[JsonPropertyName("logs")]        
public Log[] Logs 
{ 
    get 
    {
        if (null != _Logs) return _Logs;
        throw new PropertyNotInitilizedException(typeof(Log[]), "logs");
    }
    private set
    {
        _Logs = value;
    }
}
```

This was working great until I tried to serialize the object like so
```csharp
public string ToJsonString(bool prettyPrint = false)
{
    var serializerOptions = new JsonSerializerOptions()
    {
        WriteIndented = prettyPrint,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault

    };

    return JsonSerializer.Serialize(this, serializerOptions);
}
```
What I assume is happening here is the serializer is having to use the getter on the property to see if its `null`, thus throwing the exception. 

**Am I wrong to assume that serializer should ignore exceptions in this case?** If so any advice on how to handle this would be welcomed. 

Thanks 😁

**Comment by TheJaysH** [comment]
I have a hacky workaround, so if you see this as a resolution please close the issue.

I'm using a private property `IsSerializing` to define its state, if `true` it will return `null` as expected. 

```csharp
[JsonInclude]
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
[JsonPropertyName("logs")]
public Log[] Logs
{
    get
    {
        if (IsSerializing || null != _Logs) return _Logs;
        throw new UptimeRobotPropertyNotInitilizedException(typeof(Log[]), "logs");
    }
    private set
    {
        _Logs = value;
    }
}

public string ToJsonString(bool prettyPrint = false)
{
    IsSerializing = true;
    var serializerOptions = new JsonSerializerOptions()
    {
        WriteIndented = prettyPrint,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };
    var json = JsonSerializer.Serialize(this, serializerOptions);
    IsSerializing = false;
    return json;
}
```

**Comment by eiriktsarpalis** [comment]
> Am I wrong to assume that serializer should ignore exceptions in this case?

Sadly, yes. As a general design principle libraries should not eat user exceptions since it often obscures potential bugs in the code. I don't think it is possible to reconcile the requirement of both throwing if null and ignoring serialization if null.

Out of curiosity, what motivates you to throw an exception if the property is not initialized? Clearly it is a valid state if you are looking to serialize it. Personally I would simply slap a nullable annotation to the property and remove any checks from the getter.

**Comment by TheJaysH** [comment]
@eiriktsarpalis Thanks for getting back to me. The reason for the exception is so that the users is informed why the property is null should they try to access it. Since the property is only populated if they provide the API with extra parameters. (This is a third party API so changing this is not possible) 

```
PropertyNotInitilizedException: To initialize this property please provide the relevant logs parameters. see: https://example.com?foo=bar
```
But now you mention it I see why the serializer ignoring exceptions would be a terrible idea. 

I am aware of nullable, but have yet to use it. unless you mean `public Thing? thing { get; }`  the `?` in which case I have used it for primitive types such as int, DateTime etc. However I believe all reference types (classes) are nullable by default? 

Though i could be wrong. 

Thanks again for getting back to me 👍

**Comment by eiriktsarpalis** [comment]
> I am aware of nullable, but have yet to use it. unless you mean public Thing? thing { get; } the ? in which case I have used it for primitive types such as int, DateTime etc. However I believe all reference types (classes) are nullable by default?

That's right, however since C# 8 it is possible to declare nullable and non-nullable reference types. It's a compile-time feature that provides useful warnings if it thinks you are trying to dereference a null value. See https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references for more info.
