### ISSUE TITLE
[WASM][AOT] Generic methods are 5000x slower than non-generic methods using profiled AOT

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#48163]
### Description

Repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug48163/Bug48163

Consider the following code:

```csharp
	[MethodImpl(MethodImplOptions.NoInlining)]
	static int TestGeneric<T>(T value, int other)
	{
		for (int i = 0; i < innerCount; i++)
		{
			other += i;
		}

		return other;
	}

	[MethodImpl(MethodImplOptions.NoInlining)]
	static int TestNormal(int value, int other)
	{
		for (int i = 0; i < innerCount; i++)
		{
			other += i;
		}

		return other;
	}
```

The generic method is executing 5000x slower than the normal method (~5s vs. ~1ms), even when the profile recorded it.

When using Full AOT, this same generic method is running at the same speed than the normal method.

Additionally, with a similar benchmark, using `Dictionary<,>`:
- 1M `Dictionary<int,int>.TryGetValue()` Mixed: 00:00:00.0385150, FullAOT: 00:00:00.0347
- 1M `Dictionary<string,string>.TryGetValue()` Mixed: 00:00:00.04405, FullAOT: 00:00:00.0090600

### Configuration

bb650672df2da1c7666e20d3abf713d050a954ca

### Regression?

No.

**Comment by jeromelaban** [comment]
The reason the generic method is not AOTed comes from this line:
https://github.com/dotnet/runtime/blob/629ad508bf386fcbfd684a636d5e2e1146f84066/src/mono/mono/mini/aot-compiler.c#L12784

Where no assemblies are loaded during the profile parsing, making resolutions here fail:
https://github.com/dotnet/runtime/blob/629ad508bf386fcbfd684a636d5e2e1146f84066/src/mono/mono/mini/aot-compiler.c#L12748

**Comment by antonfirsov** [comment]
I think this is critical to enable any computation-intensive library code to run with reasonable performance.

For example people keep trying image processing with ImageSharp in the browser, I think it would be important to make that experience at least not terrible. ImageSharp relies heavily on generics, and I assume there are other libraries which also do so.

**Comment by jeromelaban** [comment]
After investigating the issue a bit deeper, doing the following loads the assemblies and the profile gets loaded further:

```c
if (acfg->aot_opts.image_files) {
	GList *l;
	MonoAssembly *assembly;
	printf("Loading additional image files\n");

	for (l = acfg->aot_opts.image_files; l; l = l->next) {
		printf("Loading additional assembly: %s\n", (char*)l->data);
		assembly = mono_domain_assembly_open_internal (mono_domain_get (), mono_domain_default_alc (mono_domain_get ()), (char*)l->data);

		if(!strcmp(ass->aname.name, assembly->aname.name)) {
			printf("Skip loading additional main assembly: %s\n", (char*)l->data);
			continue;
		}

		if(assembly){
			printf("Loaded additional assembly: %s\n", (char*)l->data);
			acfg->loaded_assemblies = g_slist_append (acfg->loaded_assemblies, assembly);
		}
		else{
			printf("Not loaded additional assembly: %s\n", (char*)l->data);
		}
	}
}
else {
	printf("No additional image files\n");
}
```

then changing `resolve_profile_data` to search in `acfg->loaded_assemblies`:

```c
GSList *loaded_asm = acfg->loaded_assemblies;
printf ("acfg assemblies: %p\n", loaded_asm);
for (; loaded_asm; loaded_asm = loaded_asm->next) {
	MonoAssembly *ass = loaded_asm->data;

	if (!strcmp (ass->aname.name, idata->name)) {
		idata->image = ass->image;
		break;
	}
}
```

but even though loading the makes the resolution go further, deduping goes in the way and generic methods get excluded here:

https://github.com/dotnet/runtime/blob/d5ab93c4a8e45da2dab8924c2165000bf78f84e6/src/mono/mono/mini/aot-compiler.c#L4243

**Comment by lewing** [comment]
Just for clarity, does this result apply with no profile?

**Comment by jeromelaban** [comment]
Without a profile, the generic methods are AOTed properly, and the performance for both generic and non-generic method is similar.

**Comment by vargaz** [comment]
This should be fixed now. The fix might cause issues to surface in other places.
