### ISSUE TITLE
MetadataReader.GetMethodDefinition throws `BadImageFormatException` -- should potentially return null on failure?

### ISSUE THREAD

**Issue by nschuessler** [dotnet/runtime#48167]
**Version Used**: 

5.0.0.0

**Steps to Reproduce**:
Open a PDB file created by roslyn C# compiler 3.8 using the following code.

```csharp
 var stream = File.Open(pdbFileName, FileMode.Open, FileAccess.Read, FileShare.Read); // Open the pdb as a stream
_provider = MetadataReaderProvider.FromPortablePdbStream(stream);
_metaData = _provider.GetMetadataReader();

foreach (MethodDebugInformationHandle handle in _metaData.MethodDebugInformation)
{
         if (handle.IsNil) continue;

         MethodDebugInformation entry = _metaData.GetMethodDebugInformation(handle);

         MethodDefinitionHandle methodDefinitionHandle = entry.GetStateMachineKickoffMethod();
         if (!methodDefinitionHandle.IsNil)
         {
            MethodDefinition methodDefinition = _metaData.GetMethodDefinition(methodDefinitionHandle);

            string methodName = string.Empty;

            if (!methodDefinition.Name.IsNil)  // ***** BadImageFormatException ***
           {
               methodName = _metaData.GetString(methodDefinition.Name);
           }
}
```

**Expected Behavior**:

If all the IsNil checks pass, even though there is no method information in the PDB I should have a way to check if `methodDefinition` is valid.  `if (methodDefinition != default(MethodDefinition)` doesn't work "Operator != cannot be applied to parameter of type `MethodDefinition` and `MethodDefinition`.

**Actual Behavior**:

Using any property on `methodDefinition` yields `BadImageFormatExeption`

Maybe `GetMethodDefinition` should return `MethodDefinition?` ?

**Comment by krwq** [comment]
@nschuessler to move this forward, are you perhaps interested in figuring out why is BadImageFormatException happening? It seems to me you should never get that for a valid DLL+PDB

**Comment by nschuessler** [comment]
I actually only opened the PDB file, which doesn't have method information in it. My workaround was to use `icsharpcompiler.decompiler` for now.

I have a few fires going I have to put out at the moment so responses may be slow.

**Comment by krwq** [comment]
@nschuessler I'm not super familiar with the PDB format/APIs to answer but I know that method definitions are definitely in the DLL (they technically could be in both places but my rough guess is that you need to read it from DLL, if icsharpcompiler can read it from just PDB then I assume PDB has enough information - it could be automatically opening DLL though).

**Comment by nschuessler** [comment]
Yeah, I've concluded that the only place we reliably have a matching PDB with the binary is right after the build completes, I will extract information during the build. Then the data can be pulled from DLL or PDB it won't matter.

**Comment by krwq** [comment]
@nschuessler do you think there is anything to fix on our side for this issue or can this be closed?

**Comment by nschuessler** [comment]
I was hoping that this:

```
   if (!methodDefinitionHandle.IsNil)
         {
            MethodDefinition methodDefinition = _metaData.GetMethodDefinition(methodDefinitionHandle);
```
Would never return anything invalid.

`IsNil` should be true if there is no methodDefinition or we should be able to check `MethodDefinition` for null before we get `BadImageFormatException`.

Thus either change in `IsNil` or `GetMethodDefinition` returns `MethodDefinition?`

**Comment by nschuessler** [comment]
It looks like returning `MethodDefinition?` would be a disruptive change.

But `MethodDefinition` properties Name, ... could return handles that have `IsNil` true.
