### ISSUE TITLE
Unable to load a .net core Assembly

### ISSUE THREAD

**Issue by Dharshanbs** [dotnet/runtime#48162]
Hi Team,
I had recently upgraded one of the projects from .net core 2.2 to 3.1, there has been a issue loading one of the assembly ,please help me to fix the issue.The error message details are as follows .

Could not load type 'Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by vitek-karas** [comment]
That assembly is in .NET Core 3.1.11 or higher - the latest release is 3.1.12. Can you try to install that release to see if it works?https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by Dharshanbs** [comment]
Ok sure will try and let you know.

**Comment by Dharshanbs** [comment]
I have tried as suggested above, getting the similar error,here is the
detailed error message.

Could not load type
'Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper' from
assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.12.0, Culture=neutral,
PublicKeyToken=adb9793829ddae60'.
System.TypeLoadException: Could not load type
'Microsoft.AspNetCore.Mvc.ModelBinding.Internal.ModelBindingHelper' from
assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.1.12.0, Culture=neutral,
PublicKeyToken=adb9793829ddae60'.
   at
Kendo.Mvc.Extensions.ValueProviderResultExtensions.ConvertValueTo(ValueProviderResult
result, Type type)
   at
Kendo.Mvc.UI.DataSourceRequestModelBinder.TryGetValue[T](ModelMetadata
modelMetadata, IValueProvider valueProvider, String modelName, String key,
Action`1 action)
   at
Kendo.Mvc.UI.DataSourceRequestModelBinder.CreateDataSourceRequest(ModelMetadata
modelMetadata, IValueProvider valueProvider, String modelName)
   at
Kendo.Mvc.UI.DataSourceRequestModelBinder.BindModelAsync(ModelBindingContext
bindingContext)
   at
Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext
bindingContext)
   at
Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext
actionContext, IModelBinder modelBinder, IValueProvider valueProvider,
ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at
Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker
invoker, Task lastTask, State next, Scope scope, Object state, Boolean
isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed
context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&
next, Scope& scope, Object& state, Boolean& isCompleted)
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker
invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext
httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext
httpContext)
   at
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware
middleware, HttpContext context, Task task)

**Comment by vitek-karas** [comment]
What is the version of Kendo.Mvc you're using (I can't find a version which would end up with the callstack shown here).

**Comment by Dharshanbs** [comment]
Sure, here it is 2018.1.503

**Comment by vitek-karas** [comment]
From all I can tell, the type `ModelBindingHelper` was "removed" from ASP.NET Core in 3.0 - it was from an "Internal" namespace and in 3.0 it was actually made internal: https://github.com/dotnet/aspnetcore/commit/8d66f104f7f2ca42ee8b21f75b0e2b3e1abe2e00

My guess is that you will need to upgrade the version of `Kendo.Mvc` to something newer which can work with ASP.NET Core 3.0 or higher.

**Comment by Dharshanbs** [comment]
Thank you very much for the insights, I'll check it out. I have also tried
upgrading the kendo UI to latest version but it was a trial version(2021)
it worked well.

**Comment by vitek-karas** [comment]
Since it works with the latest, I'm closing this issue as there's very likely nothing problematic from runtime's point of view.
