### ISSUE TITLE
[.NET6] Runtime should validate managed assembly's target architecture before loading it

### ISSUE THREAD

**Issue by grendello** [dotnet/runtime#48165]
Context: https://github.com/xamarin/xamarin-android/issues/5611
Context: https://gist.github.com/dellis1972/0651545c4d965b2d0db612d773506535#file-crash-log-L151

With the introduction of architecture-specific managed assemblies (e.g. `System.Private.CoreLib.dll`), the VM/runtime must have a way to validate whether the assembly's target architecture matches the application's architecture.
The Xamarin.Android issue linked above arose from the fact that our new FastDev mistakenly deployed `System.Private.CoreLib.dll` compiled for x86 to the device running an `arm64` application. This happened because instead
of putting said assembly in an architecture-specific subdirectory it copied the assembly to the top-level directory from which Xamarin.Android loads the assemblies. FastDev would copy the assemblies in the order of RIDs and it
happened that `x86` followed `arm64`, thus overwriting the correct version of `System.Private.CoreLib.dll`. Farther on, when the app was initializing, the `x86` version of `System.Private.CoreLib.dll` was loaded into an `arm64`
process, causing the following segfault:

```
02-10 14:43:21.581 32343 32343 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffffac717758 in tid 32343 (t6.helloandroid), pid 32343 (t6.helloandroid)
02-10 14:43:21.609 32370 32370 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
02-10 14:43:21.609   875   875 I tombstoned: received crash request for pid 32343
02-10 14:43:21.611 32370 32370 I crash_dump64: performing dump of process 32343 (target tid = 32343)
02-10 14:43:21.619 32370 32370 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-10 14:43:21.619 32370 32370 F DEBUG   : Build fingerprint: 'google/redfin/redfin:11/RQ1A.210105.003/7005429:user/release-keys'
02-10 14:43:21.619 32370 32370 F DEBUG   : Revision: 'MP1.0'
02-10 14:43:21.619 32370 32370 F DEBUG   : ABI: 'arm64'
02-10 14:43:21.619 32370 32370 F DEBUG   : Timestamp: 2021-02-10 14:43:21-0600
02-10 14:43:21.619 32370 32370 F DEBUG   : pid: 32343, tid: 32343, name: t6.helloandroid  >>> com.microsoft.net6.helloandroid <<<
02-10 14:43:21.619 32370 32370 F DEBUG   : uid: 10271
02-10 14:43:21.619 32370 32370 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xffffffffac717758
02-10 14:43:21.619 32370 32370 F DEBUG   :     x0  0000007142801890  x1  00000071428018a0  x2  00000071428018a0  x3  0000007190cbc340
02-10 14:43:21.619 32370 32370 F DEBUG   :     x4  0000000000000010  x5  b4000072fc892d76  x6  000000000000000a  x7  000000000000000a
02-10 14:43:21.619 32370 32370 F DEBUG   :     x8  0000007190cbc608  x9  00000071432d6000  x10 0000000000007e57  x11 0000000000007e57
02-10 14:43:21.619 32370 32370 F DEBUG   :     x12 000000005212d1e7  x13 952c000000058106  x14 0000000000000000  x15 00000071430d4b48
02-10 14:43:21.619 32370 32370 F DEBUG   :     x16 00000071432bf400  x17 0000000000000000  x18 000000744262e000  x19 0000007fcff637e0
02-10 14:43:21.619 32370 32370 F DEBUG   :     x20 0000007fcff63a20  x21 0000007fcff63810  x22 b40000729c77b5d0  x23 0000007fcff639d8
02-10 14:43:21.619 32370 32370 F DEBUG   :     x24 b40000732c80eb30  x25 ffffffffac717758  x26 0000007190cbc340  x27 b4000071fc77c370
02-10 14:43:21.619 32370 32370 F DEBUG   :     x28 0000007441d96000  x29 0000007fcff63700
02-10 14:43:21.619 32370 32370 F DEBUG   :     lr  0000007190cbc698  sp  0000007fcff63700  pc  0000007190cbc378  pst 0000000060001000
02-10 14:43:21.686  1622  6500 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
02-10 14:43:21.686  1012  1193 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
02-10 14:43:21.687   934  1866 D audio_hw_waves: ma_set_source_metadata_l: All tracks was removed from app_type(69936) device_type(2)
02-10 14:43:21.709 32370 32370 F DEBUG   : backtrace:
02-10 14:43:21.709 32370 32370 F DEBUG   :       #00 pc 000000000000d378  <anonymous:7190caf000>
```

dotnet/mono runtime should fail gracefully (throw a managed exception for instance) when an attempt to do the above is made.

**Comment by lambdageek** [comment]
I realize this is an issue about Mono, but I'm wondering if there is a mechanism in .NET for this (that CoreCLR uses).

Also... would we want to match the RID that the runtime is targeting with the RID that the particular System.Private.CoreLib instance is targeting?   So presumably `ios-arm64` and `android-arm64` CoreLibs shouldn't be confused either.

**Comment by CoffeeFlux** [comment]
cc: @vitek-karas

**Comment by lambdageek** [comment]
Would something similar to mono's UUID "version" check (that compares some build strings in the runtime and corelib) be good enough as an additional diagnostic? That is, check the UUID, but also check that the RID baked into the runtime and SPC match. Or does this need to be solved for assemblies in general?

**Comment by akoeplinger** [comment]
Yeah I think we need something embedded like mono's version check, the assemblies themselves target `AnyCPU` e.g. for `arm64`.  I like the idea of using the RID for this.

**Comment by vitek-karas** [comment]
Not sure if this is Mono specific or not. On CoreCLR side there's no validation of this. There's actually no information in the assembly itself. Maybe there's something in R2R headers if R2R is available, but if it's pure IL, there's nothing (ignoring the PE header, which can only express x86/x64/ia64, so it's legacy and useless really).

Generally in .NET Core this information is carried externally. NuGet packages have it in the metadata/directory structure, apps produced by the SDK have this in their `.deps.json` (produced from the NuGet's metadata), frameworks have it in their `.deps.json` in a way as well (runtime packs are effectively NuGets in this regard - they are identified by name). The host uses the `.deps.json` to resolve this at runtime if necessary.

There are many examples of NuGet packages which carry platform specific pure IL assemblies, and if a Windows-only assembly would be used on Linux, it would probably fail in random ways (probably not SEGFAULT, but definitely nothing pretty).

**Comment by akoeplinger** [comment]
My initial thinking was this would only be used for our own assemblies or even just System.Private.CoreLib since as Vitek said there's no good way to do this for all assemblies. Essentially having a failsafe with a nice assertion message instead of randomly crashing because the managed code used a wrong memory layout for some structs accessed by the runtime.

I'm a bit torn on whether it's worth it given that the only cases where this can happen is if the tooling has a bug :)

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by SamMonoRT** [comment]
@akoeplinger - we didn't work on this, and your last comment makes me think we can close this as is, unless we want to move to 8.0 and design a better solution to handle tooling issues. Please close or move to 8.0.0 as appropriate.

**Comment by akoeplinger** [comment]
I don't think this has enough value to be worth it TBH, it can only happen with tooling bugs and when it happens it's not that hard to figure it out and we also haven't seen another instance of this in the 18 months since this bug was filed.
