### ISSUE TITLE
Single-file distribution creates world-writable folder at /var/tmp/.net

### ISSUE THREAD

**Issue by vtbassmatt** [dotnet/runtime#48174]
### Description

:wave: I help out on the [Git Credential Manager Core](https://github.com/microsoft/git-credential-manager-core), which is a .NET Core application. A customer [reported the following](https://github.com/microsoft/Git-Credential-Manager-Core/issues/247) to us, which I believe is an implementation detail of single-file distribution and not something we can address ourselves:
> \[The app\] creates `/var/tmp/.net` as a world-writable directory, without adding the sticky bit.  This is flagged as a vulnerability by scanners such as Qualys or the CIS Benchmark.
>
>Given that the directory is owned by the calling user, there seems to be no reason to place it in `/var/tmp` or to make it world writable, but at the very least it should have the sticky bit to reduce the risk of symlink attacks and the like.

### Configuration

This is .NET Core 3.1.6 on Ubuntu 18.04.

**Comment by NN---** [comment]
Did you try setting env var DOTNET_BUNDLE_EXTRACT_BASE_DIR ?
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet

Another option is to use .NET 5.0 which doesn’t extract any file.

**Comment by vtbassmatt** [comment]
We plan to move the app to .NET 5 when we have some cycles, so I'm glad to know that will fix it for good.

The env var seems like an OK workaround if someone is hard blocked by this, so I'll pass that along. (In case it wasn't clear - we are a Microsoft/GitHub team shipping a .NET app. It was one of our customers, not us, who first raised the problem, and we don't have a means to set environment variables on behalf of each customer.)

**Comment by NN---** [comment]
Since https://github.com/microsoft/Git-Credential-Manager-Core/pull/288 is merged, should it be closed ?

**Comment by vtbassmatt** [comment]
Yes, it doesn't seem like this will see any traction on down-level .NET, and we're unblocked with our move to 5.0. (Thanks for that, btw, @NN--- ). Closing.
