### ISSUE TITLE
Intellisense verbiage for DateDiff in VB.Net

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#48177]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Intellisense-verbiage-for-DateDiff-in-VB/1326008)._

---
The DateDiff function in VB.Net takes two dates: date1 and date2.  The Intellisense help for those two parameters is not helpful, however.  It simply tells you that you're putting in the first or second value, which is already obvious from the name.  What we need to know is that date1 will be subtracted from date2 instead of the other way around.

I've been using Visual Basic professionally since version 3 and, in all that time, I still get those two dates reversed!  The only way to figure out which way it will go is to either try it or hit F1 and scroll down a couple of pages.  Even the example in the help is done in such a way that you can't tell which is which!

I know VB.Net is no longer a priority but please, give us some help text that's helpful!

---
#### Feedback Bot on 7/19/2019, 00:19 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vatsalya Agrawal [MSFT] on 7/19/2019, 09:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/23/2019, 03:31 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/24/2019, 03:54 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/8/2019, 02:22 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 2/1/2021, 00:37 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by danmoseley** [comment]
@carlossanlop where does intellisense for this come from? I assume not from sources.

**Comment by cston** [comment]
It looks like the documentation is in dotnet-api-docs (see [DateAndTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/Microsoft.VisualBasic/DateAndTime.xml#L314)).

**Comment by danmoseley** [comment]
Created a PR. For future reference, changes like this can be made directly in the browser. Just click the pencil button in the top right of the topic.

At some point, we'll likely make the .vb code the source of docs, but for now it's obviously in dotnet-api-docs.
