### ISSUE TITLE
Can't find release tags v3.1.12 and v2.1.25 for corefx repository

### ISSUE THREAD

**Issue by klementi** [dotnet/runtime#48186]
According to https://devblogs.microsoft.com/dotnet/net-february-2021/ there are two new NET Core releases
3.1.12 and 2.1.25

However we can't find release tags v3.1.12 and v2.1.25 for corefx repository
https://github.com/dotnet/corefx/tags

Can you confirm that we should use the previous tags (v3.1.11 and v2.1.24) to build the latest releases?

**Comment by dagood** [comment]
There are new commits for 3.1.12 and 2.1.25. I've reached out (internally) to @Anipik and @rbhanda to help fix up the tags. Thanks for letting us know.

**Comment by rbhanda** [comment]
Hello, Thanks a lot for letting us know about the missing tags. We have pushed the tags to https://github.com/dotnet/corefx/tags

**Comment by klementi** [comment]
I believe you have missed v2.1.25-dependencies tag...

**Comment by rbhanda** [comment]
@Anipik Can you help us here for  v2.1.25-dependencies tag?

**Comment by klementi** [comment]
also, FYI, there is a related issue we stumbled upon with newly tagged corefx v3.1.12 project https://github.com/dotnet/runtime/issues/48210

**Comment by Anipik** [comment]
closing this one as all the tags are up now
