### ISSUE TITLE
Why there is not a SHA224 built-in .NET?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#48188]

**Comment by vcsjones** [comment]
In .NET Core and .NET 5, all of the cryptographic primitives are implemented by the underlying platform. [Windows CNG][cng] in particular does not support SHA224, or other "truncated with different initialization values" like SHA512/256. This means it cannot be supported on Windows with the current design.

[cng]: https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal

**Comment by AraHaan** [comment]
> 
> 
> In .NET Core and .NET 5, all of the cryptographic primitives are implemented by the underlying platform. [Windows CNG](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal) in particular does not support SHA224, or other "truncated with different initialization values" like SHA512/256. This means it cannot be supported on Windows with the current design.

While Windows CNG does not, Crypto++ does support some of those too. Perhaps they can bring it in using p/invokes to dll version of crypto++.

**Comment by vcsjones** [comment]
> Perhaps they can bring it in using p/invokes to the dll version of crypto++.

With the current state of affairs, I don't believe bringing in a 3rd party library is an option, even something like OpenSSL's libcrypto.

My current understanding is that shipping implementations of cryptographic primitives is off the table, since it impacts some things like serviceability, security, and compliance, to name a few.

**Comment by danmoseley** [comment]
This is presumably something a community owned library can add, without changes in the platform.
