### ISSUE TITLE
Blazor Webassembly StackFrame()

### ISSUE THREAD

**Issue by fabianoliver** [dotnet/runtime#48185]
### Describe the bug
StackFrame() doesn't appear to work / finds no relevant stack infos.

### To Reproduce
```
public class Program
{
    static string Test() => new StackFrame(1)?.ToString();
    public static string Hello = Test();

    public static async Task Main(string[] args)
    {
        Console.WriteLine(Hello); // prints: ﻿<unknown method> at <unknown offset> in file:line:column <filename unknown>:0:0
       // ... rest of the default blazor startup, ommitted for brevity
    }
}
```

### Exceptions (if any)
Output above is <unknown method> at <unknown offset> in file:line:column <filename unknown>:0:0.
Expected output (e.g. as from a non-blazor application) would be something along the lines of ﻿.cctor at offset 39 in file:line:column <filename unknown>:0:0

### Further technical details
- Blazor webassembly, NET 5.0, same behaviour on 3.1
- VS 2019
- Setting PublishTrimmed seems to have no effect one way or the other

**Comment by danmoseley** [comment]
We don't have  label `area-System.Diagnostics-mono` but we do have one for `area-System.Diagnostics-coreclr`?

**Comment by BrzVlad** [comment]
This works fine in the console sample. @lewing Any idea what might be going on when running from Visual Studio ?

**Comment by lewing** [comment]
I wasn't able to reproduce this with a simple test either.  Will investigate more.

**Comment by BrzVlad** [comment]
Wasn't able to reproduce with browser/console sample. Tried again with VS, net5.0 release, and I'm getting correct method/offset information.
