### ISSUE TITLE
System.Text.Json deserialization broken for DateTime, Guid, and enum

### ISSUE THREAD

**Issue by Matthewsre** [dotnet/runtime#48202]
### Description

I was having problems recently with the Cosmos 3 SDK deserializing my models correctly and figured it was a but in their library. 

I was just switching some code I have to System.Text.Json and was running into the same issue.

DateTime, Guid, and Enum are all not being deserialized correctly.

Here is a simple XUnit test to repro:

```
using System;
using System.Text.Json;
using Xunit;

namespace Example.Tests
{
    public class UnitTest1
    {
        [Fact]
        public void GuidsAndDateTimesNotSerialized()
        {
            var post = new Post {
                AuthorId = Guid.NewGuid(),
                Created = DateTime.UtcNow,
                Title = "test title",
                Path = "test-title",
                PostStatus = PostStatus.Published,
                Description = "this is a test",

            };
            var json = JsonSerializer.Serialize(post);
            var result = JsonSerializer.Deserialize<Post>(json);

            Assert.Equal(post.Created, result.Created);
            Assert.Equal(post.AuthorId, result.AuthorId);
            Assert.Equal(post.PostStatus, result.PostStatus);
        }
    }

    public class Post
    {
        public Guid AuthorId { get; internal set; }
        public string Title { get; set; }
        public string Path { get; set; }
        public string Description { get; set; }
        public PostStatus PostStatus { get; internal set; }
        public DateTime Created { get; internal set; }
    }

    public enum PostStatus
    {
        Draft,
        Published
    }
}
```

### Configuration

Here is the .csproj info for the test

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
        <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I also tried referencing the packages for System.Text.Json 4.7.2, 5.0.0, and 5.0.1

Was able to also repro with net3.1

Running in Visual Studio on a Surface Book 2

Microsoft Visual Studio Community 2019 Preview
Version 16.9.0 Preview 4.0

**Comment by Matthewsre** [comment]
Removing issue, forgot I had the internal set on the model for GET vs POST being displayed with/without the properties on swagger.

**Comment by layomia** [comment]
@Matthewsre how did you resolve this issue?

**Comment by Clockwork-Muse** [comment]
@layomia 
> Removing issue, forgot I had the internal set on the

... presumably OP just removed `internal`, since that would cause default properties for any type.

**Comment by Matthewsre** [comment]
> @layomia
> 
> > Removing issue, forgot I had the internal set on the
> 
> ... presumably OP just removed `internal`, since that would cause default properties for any type.

@layomia ,

That is exactly how I solved the serialization problem.

**Comment by layomia** [comment]
Thanks. Just wanted to mention that another way is to place `[JsonInclude]` on the property - https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-5.0.
