### ISSUE TITLE
6.0 - System.Text.Json.JsonSerializer.Deserialize System.Net.DnsEndPoint System.NotSupportedException

### ISSUE THREAD

**Issue by vindicatorr** [dotnet/runtime#48205]
### Description

System.Text.Json.JsonSerializer.Deserialize for System.Net.DnsEndPoint results in: "Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'System.Net.DnsEndPoint'..."

### Configuration

* Which version of .NET is the code running on? 6.0.100-preview.1.21107.2
* What OS and version, and what distro if applicable? Arch Linux
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I don't believe so.
* If you're using Blazor, which web browser(s) do you see this issue in? N/A

### Regression?
I don't believe so: https://github.com/dotnet/runtime/issues/29895

### Other information

I thought I read it was supposed to work in 5.0, but I was already using that.
When I saw it was marked as "Done" for 6.0 (https://github.com/dotnet/runtime/issues/29895#event-3150463795), I installed that, but it's still an issue.
It at least serialized the object:
```
{"PDnsEndPoint":{"Host":"hostName","AddressFamily":0,"Port":0},"POther0":null,"POther1":null}
```

**Comment by eiriktsarpalis** [comment]
I believe the standard approach for serializing a class you don't own is to define a `JsonConverter`. cc @layomia to comment on whether it is possible to specify deserialization constructors for class we don't own.

**Comment by vindicatorr** [comment]
That's a great feature. I just made use of it and like it. https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0

**Comment by layomia** [comment]
Later in .NET 6.0 when we expose the internal serialization metadata classes as part of the JSON code gen work - https://github.com/dotnet/runtime/issues/34456 - users will be able to specify the deserialization constructor to use for any type (including non-owned types), without `JsonConstructorAttrbute`.
