### ISSUE TITLE
dotnet-diagnostic sockets dont close after application exit

### ISSUE THREAD

**Issue by ekzoor** [dotnet/runtime#48214]
.NET Core version: 3.1, target - linux-x64

When I launch my app, it opens 8 unix sockets:
![sockets](https://user-images.githubusercontent.com/26752123/107753748-907f0280-6d31-11eb-8a20-3aed89468e31.png)
Then application exits with Envirnoment.Exit(0); and sockets left opened until I close terminal window.
If I restart my app without closing terminal window, I get 8 more opened sockets. With every restart I get +8 opened sockets, after a while I get maximum opened sockets in system and all other application crashes.

Hundreds of open sockets - 
[sockets.txt](https://github.com/dotnet/runtime/files/5970891/sockets.txt)

**Comment by karelz** [comment]
@ekzoor do you get the same behavior from HelloWorld app? (that will tell us if it depends on what you do in your app)
What if you open custom Socket yourself? (that will tell us if it is specific to dotnet-diagnostic)

Will the sockets expire and close eventually? (perhaps in a few minutes?)

**Comment by antonfirsov** [comment]
Seems very similar to #13194. (Hope I applied correct labels.)

**Comment by antonfirsov** [comment]
If I understand the discussion under that issue correctly, this has been fixed in .NET 5, ported to 3.0, but it's not unclear if the fix is also available in 3.1.

@ekzoor any chance you try your app on .NET 5?

**Comment by ekzoor** [comment]
> @ekzoor do you get the same behavior from HelloWorld app? (that will tell us if it depends on what you do in your app)
> What if you open custom Socket yourself? (that will tell us if it is specific to dotnet-diagnostic)
Sockets close correctly on HelloWorld app, I created mini app which can reproduce issue and i can share it if needed. (Its contains only sleep and process.start)
> Will the sockets expire and close eventually? (perhaps in a few minutes?)
No, they only close if i close the terminal window

**Comment by antonfirsov** [comment]
>  I created mini app which can reproduce issue and i can share it if needed. 

Please do it would be very helpful!

/cc @sywhang

**Comment by ekzoor** [comment]
> If I understand the discussion under that issue correctly, this has been fixed in .NET 5, ported to 3.0, but it's not unclear if the fix is also available in 3.1.
> 
> @ekzoor any chance you try your app on .NET 5?

I saw the #13194. The described problem is solved in NetCore 3.1 files in /tmp/ are deleted correctly.
Ill try .NET 5 today

**Comment by sywhang** [comment]
Thanks for reporting this -- I'd be happy to take a look if you can share the repro.

**Comment by ekzoor** [comment]
Source for reproduce:
```
using System;
using System.Diagnostics;
using System.IO;
using System.Text;

namespace SocketSpam
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            System.Threading.Thread.Sleep(15 * 1000);
            Restart();
        }

        private static void Restart()
        {
            Console.WriteLine("Restarting util");
            string curr_dir = Directory.GetCurrentDirectory();
            Process Proc = Process.Start(curr_dir + "/restart.sh");
            Proc.WaitForExit(30 * 1000);
            Console.WriteLine("Close old copy");
            System.Environment.Exit(0);
        }
    }
}
```
restart.sh
```
#!/bin/bash
cd /mnt/C/Test
sleep 30s
./SocketSpam
```

In restart.sh you should edit 2nd line to cd to your workdir

**Comment by ekzoor** [comment]
Tested Net5.0 it has the same behavior

**Comment by sywhang** [comment]
@ekzoor Thanks for the repro. Unfortunately I'm unable to repro this issue on my Ubuntu-18.04 machine.. Looking at your original issue it seems like you're running on WSL. Is your environment WSL? If so, is this on WSL2 or WSL1?

**Comment by ekzoor** [comment]
@sywhang I use an unusual unix system called Astra Linux, its based on Debian (Linux core 4.15.3-1).
I tested on my VM with Ubuntu 18.04 and for it you need modify restart.sh like:
```
#!/bin/bash
cd /mnt/C/Test
sleep 30s
nohup ./SocketSpam
```

**Comment by sywhang** [comment]
@ekzoor `nohup` will prevent any SIGHUPs to be sent to the runtime, which is why it's preventing the socket to be closed. We register a signal handler for SIGHUP/SIGINT that will close these sockets upon exit without fatal exceptions (i.e. SIGABRT) and I'm not sure there's anything the runtime can do anything about if you're spawning up processes without the capability for them to receive SIGHUP. 

Does Astra Linux by spawn child processes using nohup by default? If you're ok with not having debugging/tracing capabilities, you can prevent these sockets from show up by setting the environment variable "COMPlus_EnableDiagnostics" to 0.

**Comment by ekzoor** [comment]
@sywhang Thanks for the explanation, it looks like I have to change the restart method.
I close issue because this is not a bug.
