### ISSUE TITLE
Add arm64-ios & arm64-tvos runtime packs for simulator and produce new runtime packs

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#48216]
We need a different build for ios simulator running on M1 machines. It has the same arch as 64 bits iOS bit the native assets cannot be shared. This is something that Apple might change in the future though.

I'd suggest deriving it from the existing ios-arm64 RID.

/cc @rolfbjarne

**Comment by directhex** [comment]
To confirm my understanding of the issue:

* Currently, ios-x64 means "Simulator" and ios-arm64 means "Device"
* But on M1, the Simulator is arm64
* The Simulator and Device runtimes differ in ways other than the CPU architecture, so we need both ios-arm64-device and ios-arm64-simulator configurations

Should we also rename ios-x64 to unify with whatever ios-arm64-simulator ends up looking like? I know there's not a huge likelihood of ios-x64-device being a thing that exists

**Comment by steveisok** [comment]
Your understanding is my understanding.  

I think having ios-arch-simulator packs makes a lot of sense.  So, yes, I would support an x64 rename.

**Comment by marek-safar** [comment]
I agree we should not suffix with -device and that it should be the shorter rid. I'm thinking about 

`ios-x64-sim`
`ios-arm64-sim`

This also means we need to change existing RIDs

**Comment by directhex** [comment]
Looking at it, the precedent we have for sub-variants is Alpine Linux, i.e. `linux-x64` -> `linux-musl-x64`. As far as the build system goes, it's easier to declare "ios-sim is a variant of ios" than "x64-sim is a variant of x64"

**Comment by steveisok** [comment]
If I understand the RID structure correctly, I think that shouldn't hurt us either way.

**Comment by directhex** [comment]
Does this discussion also apply to tvOS?

**Comment by marek-safar** [comment]
> Does this discussion also apply to tvOS?

Yes

**Comment by directhex** [comment]
Related: https://github.com/dotnet/llvm-project/pull/99

**Comment by directhex** [comment]
One more question: am I eliminating RIDs which we won't produce any more from the graph, like ios-x64? Or should it still exist as a RID, merely no longer a thing we build?

**Comment by marek-safar** [comment]
Considering we didn't ship anything for these rid I'd be fine with that but please make this separate PR and we can double-check during the review.
