### ISSUE TITLE
Move ILLink.LinkAttributes.xml to a shared location

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#48217]
We should move src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml to a shared location and make various attribute removal conditional on feature switches that SDKs (or end users) can opt into.

The list currently has things in it that are known to cause behavioral differences in XmlSerializer (ObsoleteAttribute) or Entity Framework (the nullable annotations cruft). While this is likely fine for WASM, broken Entity Framework will likely be unacceptable for Xamarin.

Without feature switches, the workarounds for someone wanting to keep the stripped attributes are pretty laborious.

**Comment by eerhardt** [comment]
@MichalStrehovsky - do you have an idea for what the feature switches would be named? How granular do you think the switches should be? A switch per attribute feels too granular, and a switch for the whole thing feels too big.

**Comment by MichalStrehovsky** [comment]
One natural grouping would be all the nullable junk. That covers like half of the list.

I would maybe create categories for those that have reasonable payoff and the rest can be WASM only, no-feature-switch, where ~50 bytes is a meaningful saving (e.g. it doesn't feel like stripping ObsoleteAttribute could produce meaningful savings).

**Comment by marek-safar** [comment]
As a note, Xamarin is way more aggressive than Blazor today with attributes removal. Leaving attributes like Obsolete out the list is very likely not going to work because they have hundreds/thousands of them used and we'd need to mitigate that differently.

**Comment by MichalStrehovsky** [comment]
In that case it should probably go into one of those that should be under a feature switch.

In either case whether the stripping should happen should probably be decided by the SDK and not by CoreLib as it is done right now. It doesn't feel right to have e.g. XmlSerializer behave differently in the same MAUI app depending on whether you target Android (that uses Mono's corelib) vs Windows desktop (that would use CoreCLR's corelib).

**Comment by marek-safar** [comment]
@eerhardt it should be done for net6 release
