### ISSUE TITLE
NET CoreFX v3.1.12 release failed to build due to the usage of internal NuGet feed

### ISSUE THREAD

**Issue by klementi** [dotnet/runtime#48210]
We are trying to build https://github.com/dotnet/corefx/releases/tag/v3.1.12 by running
./build.sh --configuration Release --os Linux

Build is failing with following errors

```
Build FAILED.

/build/corefx/Directory.Build.props(89,3): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/darc-int-dotnet-corefx-43e382ec/nuget/v3/index.json.
/build/corefx/Directory.Build.props(90,3): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/darc-int-dotnet-corefx-43e382ec/nuget/v3/index.json.
/build/corefx/Directory.Build.props(90,3): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/internal/_packaging/darc-int-dotnet-corefx-43e382ec/nuget/v3/index.json.
    0 Warning(s)
    3 Error(s)
```
It appeared that the feed https://pkgs.dev.azure.com/dnceng/internal/_packaging/darc-int-dotnet-corefx-43e382ec/nuget/v3/index.json is internal and requires authentication

usage of this feed was introduced by commit 50a99d5d3c6e68aecf70627897c0d862a92fc283 by Santiago Fernandez Madero safern@microsoft.com

Please advise on our next steps to build the project locally

**Comment by ViktorHofer** [comment]
cc @Anipik @mmitche

**Comment by klementi** [comment]
Any update on this issue?

**Comment by mmitche** [comment]
This feed (not managed by Maestro) https://github.com/dotnet/corefx/blob/50a99d5d3c6e68aecf70627897c0d862a92fc283/NuGet.config#L18 was added for this release. You should be able to remove it and build without issue. This was an oversight on our part (it should have a "disabledPackageSources" entry for it.

**Comment by ViktorHofer** [comment]
Closing as fixed.
