### ISSUE TITLE
Avoid bundling unnecessary functionality in the wasm published output

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#48225]
Some candidates:
- [x] MBR
- [x] EventPipe
- [ ] Zlib

Specifics are still being figured out.

**Comment by lambdageek** [comment]
We're looking at various approaches. It won't necessarily be a separate workload pack.

**Comment by lewing** [comment]
zlib is used by the runtime for embedded pdbs so any solution here would need to handle that.

**Comment by CoffeeFlux** [comment]
I believe we came to the conclusion that we might be willing to give that up for published apps if it results in a substantial size reduction.

**Comment by CoffeeFlux** [comment]
Components tracking issue: https://github.com/dotnet/runtime/issues/50862

**Comment by lewing** [comment]
This was resolved with the debugger component split
