### ISSUE TITLE
X509Certificates RevocationTests EmptyAiaResponseIsIgnored failed in CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#48223]
Failed in https://github.com/dotnet/runtime/pull/48172

See the logs at:

https://dev.azure.com/dnceng/public/_build/results?buildId=990212&view=logs&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b&l=87

https://helix.dot.net/api/2019-06-17/jobs/a2f2a3ff-ffb5-4e99-a88a-4206c9773925/workitems/System.Security.Cryptography.X509Certificates.Tests/console

```
C:\h\w\BDE40989\w\B2150995\e>"C:\h\w\BDE40989\p\dotnet.exe" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 614 of 667 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 2)
    System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.EmptyAiaResponseIsIgnored [FAIL]
      expected partial chain
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/RevocationTests/AiaTests.cs(40,0): at System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.EmptyAiaResponseIsIgnored()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.X509Certificates.Tests  Total: 1086, Errors: 0, Failed: 1, Skipped: 0, Time: 12.552s
```

**Comment by vcsjones** [comment]
Hit this with the new assertion to get better output. [Output]:

```
 System.Security.Cryptography.X509Certificates.Tests.RevocationTests.AiaTests.EmptyAiaResponseIsIgnored [FAIL]
      expected partial chain flags, got NotSignatureValid, UntrustedRoot
      Expected: True
      Actual:   False
```

Which is... interesting. I will dig in.

[Output]: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48107-merge-b2df4b8fda03419db5/System.Security.Cryptography.X509Certificates.Tests/console.8603011e.log?sv=2019-07-07&se=2021-03-08T18%3A40%3A27Z&sr=c&sp=rl&sig=l2MmVVhHu93qlEB9RLg%2F%2Fj%2Fe%2BZyahviAy%2BzwwIxhliM%3D

**Comment by vcsjones** [comment]
`PartialChain` makes way more sense as a flag but I can see `NotSignatureValid | UntrustedRoot` also making some sense if you treat the leaf like an anchor - it isn't self signed (`NotSignatureValid`) and it's also untrusted (`UntrustedRoot`). What doesn't make sense is the inconsistent result.

I think we can try using two intermediates, and add the first to the extra store and let the second one come from a failed AIA will help it consistently stay in `PartialChain` since at least part of the chain has been formed.
