### ISSUE TITLE
Add API to allow forcing creation of a Activity using ActivitySource (rather than relying on ActivityListener)

### ISSUE THREAD

**Issue by shirhatti** [dotnet/runtime#48237]
## Background and Motivation

Forcing creation of an Activity will allow existing codebases (e.g., aspnetcore) to migrate to using `ActivitySource` to create `Activity`s while still preserving compat with existing DiagnosticListeners.

## Proposed API

```diff
namespace System.Diagnostics.DiagnosticSource
{
  public sealed class ActivitySource
  {
+   public System.Diagnostics.Activity? StartActivity (string name,
+                                                      System.Diagnostics.ActivityKind kind,
+                                                      string parentId,
+                                                      bool forceCreation,
+                                                      System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string,object?>>? tags = default,
+                                                      System.Collections.Generic.IEnumerable<System.Diagnostics.ActivityLink>? links = default,
+                                                      DateTimeOffset startTime = default);
  }
}
```

## Usage Examples

https://github.com/dotnet/aspnetcore/pull/30089

## Alternative Designs

The alternative design to achieve compat with DiagnosticListener was to create a dummy ActivityListener. However, the decision to sample/or not sample can change frequently (on a per request-basis), making it expensive to mutate the `Sample`/`SampleUsingParentId` delegate in a thread-safe.

## Risks

When used incorrectly, forcing creation of an `Activity` could be a potentially expensive/high-allocation operation.

**Comment by tarekgh** [comment]
Properly we should combine the request here with the one in https://github.com/dotnet/runtime/issues/43853 in a single proposal.

**Comment by tarekgh** [comment]
@shirhatti if you are satisfied with the workaround proposed by @noahfalk, can we close this request? just for the record here is some high level idea how to force the Activity creation:

```C#
	Activity activity = null;
    if (activitySource.HasListeners())
    {
        activity = activitySource.StartActivity(...);
    }
    if (activity == null)
    {
        activity = new Activity(...);
        ...
        activity.Start();
    }
```

Please let me know if have any question.

**Comment by mjeanrichard** [comment]
Just for reference, this is basically the solution for my question over here https://github.com/dotnet/runtime/issues/45843

**Comment by shirhatti** [comment]
As mentioned in the other thread, Activities created using new Activity() don't have `ActivityKind` and `ActivitySource` correctly populated.

As a consequence, a diagnostic listener subscriber will see different behavior based on whether there is another `ActivityListener` in the process. I'm not a fan of having unrelated subscribers cause side-effects.

That being said, I could be convinced if both you and @noahfalk agree that these minor behavior differences are acceptable

**Comment by shirhatti** [comment]
Closing since I have been convinced otherwise 😄
