### ISSUE TITLE
Are there any support materials for a convenient .NET compilation with build.sh?

### ISSUE THREAD

**Issue by Maniues** [dotnet/runtime#48240]
Some time ago I was compiling .NET 5.0 and using only ./build.sh or ./build.sh -c Release the compilation was successful. However, there was no information about building .DEB / .RPM packages anywhere. I got the information I needed when submitting https://github.com/dotnet/runtime/issues/47153 and the build was successful.
I was looking for documentation or tutorials on compiling .NET at least 5.0 to be able to adapt the compile commands to my needs, but did not find it.

Are there any plans to do documentation on building new .NET versions?
I heard there is a private repository / place to describe the .NET infrastructure. Is it possible to share it? Why is it private?

.NET is based on Mono and Mono has a Makefile. Why didn't you decide to make a Makefile for .NET Runtime, SDK etc?

**Comment by wfurt** [comment]
Did you look at https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries ? And other docs there? Feel free to put up PR with improvements. 
Lot of code come from .NET Framework and was based on msbuild. I don't think there is compelling reason to rewrite it.

I also suggest you take a look at https://github.com/dotnet/source-build if you are interested in building everything.

**Comment by Maniues** [comment]
@wfurt I looked for these files, but I'm looking for instructions for packaging all packages in deb/rpm files. 
In my previous issue report I asked for packaging and I received these command for .NET 5.0 and new .NET 6.0: "./build.sh -c Release -subset packs+packs.installers -p:BuildDebPackage=true"
and for .NET 5.0: "./build.sh -c Release -subset installers /p:BuildLinuxPackages=true"
I think there are a lot of switches for these commands. Where I can find documentation for packaging .NET?

**Comment by ViktorHofer** [comment]
cc @NikolaMilosavljevic (@jkoritzinsky) for packaging docs

**Comment by joperezr** [comment]
FWIW this is what I see that we are calling in our builds:
- For debs
`./build.sh --subset clr+libs+host+packs+packs.installers /p:BuildDebPackage=true /p:Configuration=Release /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:RuntimeFlavor=coreclr`

- For rpms
`./build.sh --subset clr+libs+host+packs+packs.installers /p:BuildRpmPackage=true /p:Configuration=Release /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:RuntimeFlavor=coreclr`

ping @NikolaMilosavljevic @jkoritzinsky do we have this documented anywhere?

**Comment by NikolaMilosavljevic** [comment]
> FWIW this is what I see that we are calling in our builds:
> 
> * For debs
>   `./build.sh --subset clr+libs+host+packs+packs.installers /p:BuildDebPackage=true /p:Configuration=Release /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:RuntimeFlavor=coreclr`
> * For rpms
>   `./build.sh --subset clr+libs+host+packs+packs.installers /p:BuildRpmPackage=true /p:Configuration=Release /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:RuntimeFlavor=coreclr`
> 
> ping @NikolaMilosavljevic @jkoritzinsky do we have this documented anywhere?

Packaging commands have evolved since 3.1 and again in 6.0, due to refactoring of build infrastructure. Old commands in core-setup repo are not applicable anymore, and it seems that some parts of documentation was missing or wasn't ported.

@joperezr feel free to send PR to add those commands to our Dev documentation: https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md.

We have few issues tracking improvements in packaging on Dev machines, i.e.: https://github.com/dotnet/runtime/issues/32304

**Comment by NikolaMilosavljevic** [comment]
[Triage] Assigning to create documentation. We are open to collaborate.

**Comment by Maniues** [comment]
Thanks for fixing this problem. It is important to me that all possible switches and all possible options for them are described.
Because it's easy to guess what /p: TargetOS means and choose the appropriate option. However, there are other things not so obvious. And when using the "/ p:" switches (for example "/ p: TargetOS = [OS]) and when" - [switch] "(for example" -c Release ")

**Comment by NikolaMilosavljevic** [comment]
> Thanks for fixing this problem. It is important to me that all possible switches and all possible options for them are described.
> Because it's easy to guess what /p: TargetOS means and choose the appropriate option. However, there are other things not so obvious. And when using the "/ p:" switches (for example "/ p: TargetOS = [OS]) and when" - [switch] "(for example" -c Release ")

Most of those switches and properties are applicable to binary builds as well as packaging. Documentation for packaging will describe only packaging specific properties and switches - there are only few of them.

**Comment by Maniues** [comment]
Will the documentation cover .NET 5.0 and .NET 6.0, or just one of them?

**Comment by NikolaMilosavljevic** [comment]
[Triage] Various .NET repos provide specific instruction for building binaries and installers. There might be areas that aren't fully documented, which is something we might address in the future. It's not feasible to document every build or configuration switch.
