### ISSUE TITLE
[Android] Updating from Xamarin.Forms 4.8 to 5.0 crashes in .NET 6

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#48242]
### Description

Clone these samples using the `xamarin.forms5-repro` branch, and install the relevant bits in the `README.md`:

https://github.com/dotnet/net6-mobile-samples/tree/xamarin.forms5-repro

Build & run the app on an Android device or emulator:

    > dotnet build HelloForms -t:Run

Crashes with:

    --------- beginning of crash
    02-12 14:24:26.507 11286 11286 E AndroidRuntime: FATAL EXCEPTION: main
    02-12 14:24:26.507 11286 11286 E AndroidRuntime: Process: com.microsoft.net6.helloforms, PID: 11286
    02-12 14:24:26.507 11286 11286 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.RendererPool:_freeRenderers' (0) due to: Could not resolve type with token 01000289 from typeref (expected class 'System.Collections.Generic.Stack`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Stack`1 member:(null)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetPackager(VisualElementPackager packager)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetElement(Page element)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(VisualElement element)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild(Page page, Boolean layout)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal(Page newRoot)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage(Page newRoot)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage(Page page)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage()
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication(Application application)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at HelloForms.Droid.MainActivity.OnCreate(Bundle savedInstanceState)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at crc6454ad0c421ff6d919.MainActivity.n_onCreate(Native Method)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at crc6454ad0c421ff6d919.MainActivity.onCreate(MainActivity.java:37)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8000)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7984)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    02-12 14:24:26.507 11286 11286 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    02-12 14:24:26.508 11286 11286 I monodroid-assembly: open_from_update_dir: trying to open assembly: /data/user/0/com.microsoft.net6.helloforms/files/.__override__/System.Console.dll
    02-12 14:24:26.509 11286 11286 I monodroid-assembly: open_from_update_dir: loaded assembly: 0xb40000722c7f7b20
    02-12 14:24:26.511 11286 11286 I MonoDroid: UNHANDLED EXCEPTION:
    02-12 14:24:26.519 11286 11286 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
    02-12 14:24:26.519 11286 11286 I MonoDroid:
    02-12 14:24:26.519 11286 11286 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
    02-12 14:24:26.519 11286 11286 I MonoDroid: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.RendererPool:_freeRenderers' (0) due to: Could not resolve type with token 01000289 from typeref (expected class 'System.Collections.Generic.Stack`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Stack`1 member:(null)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetPackager(VisualElementPackager packager)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetElement(Page element)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(VisualElement element)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild(Page page, Boolean layout)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal(Page newRoot)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage(Page newRoot)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage(Page page)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage()
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication(Application application)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at HelloForms.Droid.MainActivity.OnCreate(Bundle savedInstanceState)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at crc6454ad0c421ff6d919.MainActivity.n_onCreate(Native Method)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at crc6454ad0c421ff6d919.MainActivity.onCreate(MainActivity.java:37)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8000)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7984)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7660)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    02-12 14:24:26.519 11286 11286 I MonoDroid:
    02-12 14:24:26.519 11286 11286 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
    02-12 14:24:26.519 11286 11286 I MonoDroid: android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.RendererPool:_freeRenderers' (0) due to: Could not resolve type with token 01000289 from typeref (expected class 'System.Collections.Generic.Stack`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Stack`1 member:(null)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementPackager.Load()
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetPackager(VisualElementPackager packager)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetElement(Page element)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[[Xamarin.Forms.Page, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(VisualElement element)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.AddChild(Page page, Boolean layout)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPageInternal(Page newRoot)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.AppCompat.Platform.SetPage(Page newRoot)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage(Page page)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage()
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication(Application application)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at HelloForms.Droid.MainActivity.OnCreate(Bundle savedInstanceState)
    02-12 14:24:26.519 11286 11286 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at crc6454ad0c421ff6d919.MainActivity.n_onCreate(Native Method)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at crc6454ad0c421ff6d919.MainActivity.onCreate(MainActivity.java:37)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8000)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:7984)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7660)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    02-12 14:24:26.519 11286 11286 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
    02-12 14:24:26.519 11286 11286 I MonoDroid:
    02-12 14:24:26.522  1622 11330 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
    02-12 14:24:26.522  1622  7388 W ActivityTaskManager:   Force finishing activity com.microsoft.net6.helloforms/crc6454ad0c421ff6d919.MainActivity

### Configuration

.NET 6.0.100-preview.1.21103.13
HostOS: Windows
Device: Google Pixel 5 with Android 11

### Regression?

No

### Other information

The stack trace seems to be happening in this type:

https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/RendererPool.cs#L9

This `Xamarin.Forms.Platform.Android` assembly is built for Xamarin.Android, not targeting .NET 6. This seems like a compatibility problem for assemblies built against Mono and running on .NET 6.

If I used Xamarin.Forms 4.8.x, it somehow works although the code seems the same:

https://github.com/xamarin/Xamarin.Forms/blob/4.8.0/Xamarin.Forms.Platform.Android/RendererPool.cs#L9

/cc @akoeplinger

**Comment by akoeplinger** [comment]
This is because in Xamarin/Mono we had the System.Collections.Generic.Stack<T> type in mscorlib.dll, but .NET Framework had it in System.dll hence the existing typeforwarder only exists there.

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/48258 fixes this, I can launch the HelloForms app with it.
