### ISSUE TITLE
Self-contained app crashes when placed in a path with backslashes in Unix

### ISSUE THREAD

**Issue by mateoatr** [dotnet/runtime#48259]
Publishing a self-contained application in a path with a back slash in it causes the app to crash with `Failed to create CoreCLR, HRESULT: 0x80004005`. 

A minimal repro:
```
dotnet new console -o foo
cd foo
dotnet publish -o a\\\\b -r linux-x64
cd a\\\\b
./foo
```

**Comment by agocke** [comment]
Update issue: this looks like a problem with the runtime when placed in a folder with backslashes

**Comment by elinor-fung** [comment]
This is the same as https://github.com/dotnet/runtime/issues/75387 which has more information - closing against that.
