### ISSUE TITLE
How to implement dependency injection through the generic host of Microsoft.Extensions.Hosting in wpf? 

### ISSUE THREAD

**Issue by Summpot** [dotnet/runtime#48290]
Not under normal circumstances by constructing an `IServiceCollection` in `Application.OnStartup()` to achieve dependency injection, I want to set the project property `EnableDefaultApplicationDefinition` to false (this can prevent a Main method from being generated in App.g.cs), and then write my own Main method using GenericHost to implement dependency injection.
After all, it is dependency injection. I naturally want to set the App as a singleton service.
However, I don’t know how to call `Application.Run()` when using `Microsoft.Extensions.DependencyInjection` and `Microsoft.Extensions.Hosting`.
My current code is as follows.
``` csharp
namespace MyApp
{
    using System;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;

    class Program
    {
        [STAThread]
        public static void Main()
        {
            Host.CreateDefaultBuilder()
                .ConfigureServices(ConfigureServices)
                .Build()
                .Run();
                
        }

        private static void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<MainWindow>();
            services.AddSingleton<App>();
        }
    }

    class ServiceProviderFactory : IServiceProviderFactory<IServiceCollection>
    {
        private readonly ServiceProviderOptions _options;
        public ServiceProviderFactory() : this(new ServiceProviderOptions())
        {

        }
        public ServiceProviderFactory(ServiceProviderOptions options)
        {
            if (options == null)
            {
                throw new ArgumentNullException(nameof(options));
            }

            _options = options;
        }
        public IServiceCollection CreateBuilder(IServiceCollection services)
        {
            return services;
        }

        public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)
        {
            var provider = containerBuilder.BuildServiceProvider(_options);
            var app = provider.GetService<App>();
            app.InitializeComponent();
            app.Run();
            return provider;
        }
    }
}

```
This does not work, `Application.Run()` will not return, what should I do?
Thank you very much.

**Comment by tibel** [comment]
I think dotnet/wpf#499 has the information you are looking for.

**Comment by Summpot** [comment]
> I think [dotnet/wpf#499](https://github.com/dotnet/wpf/issues/499) has the information you are looking for.

Before I created this issue, I have read it, and there is really nothing I need.
