### ISSUE TITLE
PerformanceCounter Exception When Invoked for Current Process

### ISSUE THREAD

**Issue by stonstad** [dotnet/runtime#48292]
### Description

PerformanceCounter with category "Processor" and counter "% Processor Time"  fails when instance is specified by process name.

```
var counter = PerformanceCounter("Processor", "% Processor Time", Process.GetCurrentProcess().ProcessName);
counter.NextValue();
```

### Configuration

.NET 5.0.2
Windows 10 Professional 20H2 19042.746

### Regression?

Regression from .NET Framework 4.x

### Other information

System.InvalidOperationException: 'Instance 'ProcessName' does not exist in the specified Category.'

**Comment by stonstad** [comment]
Thank you.

**Comment by danmoseley** [comment]
No problem I’m just sorry I didn’t reply in Feb 🙂
