### ISSUE TITLE
Channel<T> allocates on .NET Core/5 when the ValueTask is completed before OnCompleted is called

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#48293]
In the default case when there's no task scheduler, we can use UnsafeQueueUserWorkItem to schedule the continuation instead of QueueUserWorkItem. See https://github.com/dotnet/runtime/blob/b3d7d670f56bc5f6055e33c5621cb44ca14890ca/src/libraries/System.Threading.Channels/src/System/Threading/Channels/AsyncOperation.cs#L272, which results in a call to QUWI https://github.com/dotnet/runtime/blob/b3d7d670f56bc5f6055e33c5621cb44ca14890ca/src/libraries/System.Threading.Channels/src/System/Threading/Channels/AsyncOperation.netcoreapp.cs#L14.

This will allow us to take advantage of the logic in the thread pool that short circuits if the delegate is a known one https://github.com/dotnet/runtime/blob/b3d7d670f56bc5f6055e33c5621cb44ca14890ca/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPool.cs#L1230 and should be zero alloc in the 90% case where there's no scheduler.

This showed up in a profile I was looking at and expecting 0 allocations at steady state:

|Type|Allocations|Bytes|Average Size \(Bytes\)|
|-|-|-|-|
| - System.Threading.QueueUserWorkItemCallbackDefaultContext\<System.Object\>|176|5,632|32|

![image](https://user-images.githubusercontent.com/95136/107920803-62144980-6f22-11eb-863d-6d8e65b8bbb0.png)

**Comment by stephentoub** [comment]
> We'd probably want to revisit a few places if it's actually frequent.

Actually,  we already do this in at least one of the other places i was thinking of.  I'll just change it here,  too.

Still interested in the answers to my questions,  though.

**Comment by davidfowl** [comment]
It is very rare it seems .0.0025% of the time it allocates 😄

**Comment by stephentoub** [comment]
Thanks.  I'll still change it,  but, phew :-)
