### ISSUE TITLE
MarshalUtils.IsBlittable does not handle pointers correctly

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#483]
MarshalUtils.IsBlittable incorrectly returns `false` for structures with pointers. See https://github.com/dotnet/corert/pull/7901#issuecomment-561166649 for details.

**Comment by fadimounir** [comment]
I was looking into a similar issue. We’ll need to be careful with pointer fields to the struct itself, or any struct leading to infinite recursions

**Comment by MichalStrehovsky** [comment]
Do we need to worry about it if we fix https://github.com/dotnet/coreclr/issues/27800 and simply delete that code path?
