### ISSUE TITLE
ImmutableDictionary.ContainsKey compute hashcode even it is an empty dictionary

### ISSUE THREAD

**Issue by lifengl** [dotnet/runtime#48309]
ImmutableDictionary.ContainsKey compute hashcode of the searching value even it is an empty dictionary. For a string dictionary, computing hash code costs time.

It should be a minor change to skip the entire logic for this special case.

**Comment by GrabYourPitchforks** [comment]
This is technically a behavioral change, as hash code calculation might (but really isn't supposed to) have observable side effects.

**Comment by En3Tho** [comment]
As @stephentoub usually points out, adding such check will speed up only one case (when dictionary is empty) while slowing the main use case (when dictionary is not empty). Why would you pay the cost of checking count for every operation after you've put an item there? Especially when you know it's not empty.

**Comment by eiriktsarpalis** [comment]
Do you have a use care where the current behaviour results in noticeable performance issues? We'd probably need some sort of benchmark (that looks up dictionaries of various sizes) to measure any potential improvements (or degradations) that such a change might bring.

Note that there are many lookup methods that use `SortedInt32KeyNode<T>` under the hood, so if we do decide to make such a change we should do it everywhere for consistency.
