### ISSUE TITLE
API Proposal: MemoryExtensions.SequenceEqual with IComparer<T>

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#48304]
## Background and Motivation

We currently have MemoryExtensions.SequenceEqual overloads that work with spans, but they constrain `T : IEquatable<T>`:
```C#
public static bool SequenceEqual<T>(this System.ReadOnlySpan<T> span, System.ReadOnlySpan<T> other) where T : System.IEquatable<T> { throw null; }
public static bool SequenceEqual<T>(this System.Span<T> span, System.ReadOnlySpan<T> other) where T : System.IEquatable<T> { throw null; }
```
This means there's no built-in support for using `IEqualityComparer<T>`.  It also means APIs like `Enumerable.SequenceEqual` that are unconstrained aren't able to delegate to this in general when provided with array inputs.

## Proposed API

```C#
public static class MemoryExtensions
{
    public static bool SequenceEqual<T>(this System.ReadOnlySpan<T> span, System.ReadOnlySpan<T> other, IEqualityComparer<T>? comparer);
    public static bool SequenceEqual<T>(this System.Span<T> span, System.ReadOnlySpan<T> other, IEqualityComparer<T>? comparer);
    ...
}
```
We could also consider doing the same thing for SequenceCompareTo, taking the existing overloads and adding new ones that remove the constraint and accept a nullable `IComparer<T>`.

The implementations would delegate to the existing implementations if comparer is null and T is found to be `IEquatable<T>` (maybe just for value types).  Otherwise, they'd loop through the spans comparing each element.

## Usage Examples

For example, we would change `Enumerable.SequenceEqual` to do:
```C#
if (first is TSource[] firstArray && second is TSource[] secondArray)
{
    return ((ReadOnlySequence<TSource>)firstArray).SequenceEqual(secondArray, comparer);
}

**Comment by benaadams** [comment]
Would it need a `IEqualityComparer<T>? comparer = null` to be used as your example? (which doesn't specify the comparer)

**Comment by stephentoub** [comment]
> to be used as your example? (which doesn't specify the comparer)

My example does pass a comparer... ?

**Comment by benaadams** [comment]
> My example does pass a comparer... ?

😅 So it does

**Comment by terrajobst** [comment]
* Makes sense
* We could drop the constraint on the existing APIs and do the right thing internally, but we can do that later
    - Or we could mark the comparer default to `null`, which means the caller will either use the existing one when it is equatable and use the new one when it's not.

```C#
namespace System
{
    public static class MemoryExtensions
    {
        // Existing
        // public static bool SequenceEqual<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> other) where T : IEquatable<T>;
        // public static bool SequenceEqual<T>(this Span<T> span, ReadOnlySpan<T> other) where T : System.IEquatable<T>;
        public static bool SequenceEqual<T>(this ReadOnlySpan<T> span, ReadOnlySpan<T> other, IEqualityComparer<T>? comparer = null);
        public static bool SequenceEqual<T>(this Span<T> span, ReadOnlySpan<T> other, IEqualityComparer<T>? comparer = null);
    }
}
```
