### ISSUE TITLE
Disallow usage of `$(NetCoreAppCurrent)` in projects that don't exclude such configuration and generate a package

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48311]
With 6.0 Preview 1 there were a few packages that unintentionally contain a `net6.0` configuration:
- https://github.com/dotnet/runtime/issues/48307
- https://github.com/dotnet/runtime/issues/48306
- https://github.com/dotnet/runtime/issues/48248

Reason for that is that these packages use the `$(NetCoreAppCurrent)` msbuild property which maps to .NETCoreApp version which is currently in development (i.e. net6.0) instead of a fixed version which doesn't automatically rev forward.

What makes it tricky to prohibit the usage of `$(NetCoreAppCurrent)` in packages that don't exclude it and generate package is that this would need to happen before msbuild evaluation, as the `$(NetCoreAppCurrent)` token gets replaced with the property value.

cc @Anipik @ericstj

**Comment by safern** [comment]
Something to consider here is that sometimes we need to use a new API or feature in some of these packages that is only available in `NetcoreAppCurrent`. So there are releases where we need to include an asset for `NetcoreAppCurrent` in the package. So we need a way to either turn off that error or prevent those packages from being blocked in shipping an asset for `NetcoreAppCurrent`.

**Comment by ViktorHofer** [comment]
> So there are releases where we need to include an asset for NetcoreAppCurrent in the package.

Absolutely. I'm talking about disallowing the use of the literal `$(NetCoreAppCurrent)` string in favor of the inlined value, i.e. `net6.0`.

I believe this could be part of the package validation by reading the project file and searching for `$(NetCoreAppCurrent)`. Pseudo code:

```
<Target Name="WarnForVersionlessTfm" BeforeTargets="Pack" Condition="'$(IsPackable)' == 'true'">
  <PropertyGroup>
    <_ProjectFileContent>$([System.IO.File]::ReadAllText('$(MSBuildThisProjectFile)'))</ProjectFileContent>
  </PropertyGroup>
  <Warn Message="The replacement token '$(NetCoreAppCurrent)' must not be used in a project that generates a package which doesn't exclude such configuration via the `<ExcludeCurrentNetCoreAppFromPackage />` property." Condition="'$(ExcludeCurrentNetCoreAppFromPackage)' != 'true' and $(ProjectFileContent.Contains('%24(NetCoreAppCurrent)'))" />
</Target>
```

It would be better to use a regex search here to only look at the content inside the `<TargetFramework(s) />` string.

**Comment by ViktorHofer** [comment]
Closing as we now intentionally include `$(NetCoreAppCurrent)` assets in our packages.
