### ISSUE TITLE
Amend the commit message

### ISSUE THREAD

**Issue by pgolebiowski** [dotnet/runtime#48314]
I'd like to amend the commit message for https://github.com/dotnet/runtime/commit/826aa4f7844fd3d48784025ec6d47010867baab4, because currently it has squashed commit messages from 50 commits. The desired message is just:

```
Add PriorityQueue to System.Collections.Generic (#43957)

This commit adds a new data structure, priority queue.

Fixes #43957
```

**Comment by pgolebiowski** [comment]
@eiriktsarpalis could you give a hand? 😄

**Comment by CoffeeFlux** [comment]
We can't amend the commit after it's pushed to master, sorry. The squashed commit message is fine, no need to worry about it :)
