### ISSUE TITLE
Documentation references MemoryExtensions.Read{T} that do not appear to exist

### ISSUE THREAD

**Issue by bjornharrtell** [dotnet/runtime#48320]
https://github.com/dotnet/runtime/blob/56d0eb94ec83473d99c1050072a224da327bc02a/src/libraries/System.Private.CoreLib/src/System/Buffers/Binary/Reader.cs#L13

**Comment by GrabYourPitchforks** [comment]
Comment intended to reference `MemoryMarshal.Read` (API was renamed before release). But IMO we should delete this line from the comment since documentation for a safe API shouldn't be driving people toward an unsafe API.
