### ISSUE TITLE
Ancient Greek Pamphylian Digamma Is Considered Equal To Ancient Greek Yot

### ISSUE THREAD

**Issue by zedseven** [dotnet/runtime#48321]
### Description
The ancient Greek characters for Pamphylian Digamma (`ͷ` `U+0377`) and Yot (`ϳ` `U+03F3`) are considered equal by a `StringComparer` using the Greek culture (`el-GR`). From my (non-native, amateur) perspective, this seems incorrect and I can't find any information in the Unicode spec or historically that would suggest they are equal.

This issue affects dictionaries created using said `StringComparer`, as they treat it as the same key (this is how I found the issue in the first place).

Code snippet:
```csharp
string compStr = "αβγδεζηθικλμνξοπρρστυφχψωϝͷϙϟϡͳϻϹϳ";
StringComparer comparer = StringComparer.Create(CultureInfo.GetCultureInfo("el-GR"), true);
for(int i = 0; i < compStr.Length; i++)
	Console.WriteLine(compStr[i].ToString() + " " + comparer.Compare(compStr[i].ToString(), "ϳ"));
```
Output:
```
α -1
β -1
γ -1
δ -1
ε -1
ζ -1
η -1
θ -1
ι -1
κ -1
λ -1
μ -1
ν -1
ξ -1
ο -1
π -1
ρ -1
ρ -1
σ -1
τ -1
υ -1
φ -1
χ -1
ψ -1
ω -1
ϝ -1
ͷ 0  <-- This, as far as I can tell, should not be the case
ϙ 1
ϟ 1
ϡ 1
ͳ 1
ϻ -1
Ϲ -1
ϳ 0  <-- This is expected (same character bit-for-bit)
```
Live example: https://dotnetfiddle.net/8c0HJU

### Configuration
Issue exists on .NET Core 3.1 and .NET Framework 4.7.2. Does not seem to exist on .NET 5.

### Regression?
I don't believe so, though the fact that this seems to no longer exist on .NET 5 suggests an issue exists in either the older .NET releases, or .NET 5.

### Other information
Additional resources that lead me to believe they have no reason to be equated:
http://opoudjis.net/unicode/yot.html
https://unicode.org/charts/nameslist/n_0370.html

**Comment by tarekgh** [comment]
@zedseven .NET get the collation behavior for string comparisons from the underlying platform. If using .NET Framework or using .NET Core up to and including version 3.1, and running on Windows OS, we'll use the `Windows NLS APIs` for globalization and that is the behavior you are seeing. If using .NET 5.0 (or using .NET Core any version and running on Linux), we'll use the `ICU` library for the globalization and that is where you see the correct behavior. 

Unfortunately, .NET don't have much control on that as the behavior is coming from Windows. You may consider reporting that to Windows through Windows 10 Feedback Hub. but I would recommend you try upgrading to .NET 5.0 so you'll get the desired behavior.

I am closing the issue but feel free to send any question and we'll be happy to help with. Thanks for your report.
