### ISSUE TITLE
Remove installer's GetLatestCommit target in favor of Arcade infrastructure

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48338]
Installer's `GetLatestCommit` target is used to build the corehost and to publish assets. That custom target should be replaceable by what Arcade already offers (version.targets): https://github.com/dotnet/runtime/blob/75c0b990ce249d6c37adfa4037ef3ba5b280085c/src/installer/Directory.Build.targets#L140-L151

cc @dotnet/runtime-infrastructure

**Comment by am11** [comment]
@ViktorHofer, @vitek-karas, regarding the version-like properties in `GetProductVersions` target, do we have a use-case these days where, e.g. `AppHostVersion` and `HostPolicyVersion` have different values during the build of runtime repo (locally or in public/private CI leg, including maintenance branches)? If not, I think we can define one additional property (say `DotnetProductVersion`) in `eng/Versions.props` to replace the entire `GetProductVersions` target (most of the properties in this target are unused anyway; `RuntimePackageVersion`, `RuntimePackageRelease` and so on).

**Comment by ViktorHofer** [comment]
@jkoritzinsky knows more about these properties than me. Also see the discussion in https://github.com/dotnet/runtime/issues/48341.

**Comment by am11** [comment]
Ops, should have used the correct [keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (if memory serves, `Addresses` used to be one of them but not anymore).
