### ISSUE TITLE
Document wasm relinking functionality

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#48349]
Once https://github.com/dotnet/runtime/issues/43689 is resolved we should be able to relink a project for even greater size reductions savings, most notably linking out ICU. We should document this and probably stand up a test.

- [ ] public properties, items
- [ ] default settings

**Comment by marek-safar** [comment]
I don't think this should be only documented but automatically included in the release build config

**Comment by CoffeeFlux** [comment]
Automatically including it seems nice from a size perspective but it would require fetching emscripten on customer machines, no? Either way, it would be really nice to get a successful ICU-less build on my machine for size estimation purposes sooner rather than later.

**Comment by CoffeeFlux** [comment]
Need to issue warning when emscripten is not present and use a system install by default.

**Comment by lewing** [comment]
We should do a final review of the default configuration settings for this too.
