### ISSUE TITLE
[ARM64/x64]Running "Dotnet --info" failed if install SDK 6.0-osx-arm64 at first and then install x64 VSM.

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#48343]
**Affected Mac:**
Mac OS: Big Sur(11.2) - Apple M1 chip
VSFM:8.9 Preview (8.9 build 1582)
3.1.406(runtime:3.1.12) & 5.0.103(runtime:5.0.3)
.NET 6 arm64: 6.0.100-preview.1.21103.13(runtime 6.0.0-preview.1.21102.12)

**Steps to reproduce:**
	1. Install dotnet-sdk-6.0.100-preview.1.21103.13-osx-arm64
	2. Run "Dotnet --info" 
	3. Install VSM8.9 Preview(8.9 build 1582)
        4. Run "Dotnet --info"

**Expected result:**
Twice "Dotnet --info" can Running success

**Actual result:** 
The second “Dotnet --info” running failed whit err
![image](https://user-images.githubusercontent.com/1578239/107326752-edd34380-6ae6-11eb-8b92-83a0b69164a1.png)

**Note:** 
1.re-install dotnet-sdk-6.0.100-preview.1.21103.13-osx-arm64,run "Dotnet --info" will success

**VSFM-info:**
e2em1@e2eM1s-Mac-mini ~ % dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.405 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jeffschwMSFT** [comment]
Seems related to https://github.com/dotnet/runtime/issues/48389

**Comment by sdmaclea** [comment]
This is the issue with not supporting side by side arm64 & x64 installs.

/cc @vitek-karas @richlander

**Comment by vitek-karas** [comment]
The host work has been done (host now supports arm64/x64 side-by-side), but this also needs installer changes so that the architectures are layed out into the right location.

**Comment by richlander** [comment]
Yup. This scenario is dependent on this design/project: https://github.com/dotnet/designs/pull/217

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/installer/issues/11164
