### ISSUE TITLE
[wasm] Estimate ICU data size savings when only shipping English

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#48355]
It should be possible to modify https://github.com/dotnet/icu/tree/maint/maint-67/icu-filters and generate the data file for only English instead of EFIGS to see how much space we save.

To generate the file, you need to build the full repo, and then you can rebuild the data files after adjusting the filter with `make -f icu.mk data-icudt TARGET_OS=browser TARGET_ARCHITECTURE=wasm`.

**Comment by CoffeeFlux** [comment]
If the size savings looks worthwhile, we can adjust this issue to split up the files further.

**Comment by CoffeeFlux** [comment]
Full EFIGS:
```
-rw-r--r--  1 ryan  staff   602096 Feb 23 16:42 icudt_EFIGS.dat
```

`en_US` only:
```
-rw-r--r--  1 ryan  staff   495072 Feb 23 16:55 icudt_EFIGS.dat
```

This is uncompressed. I'm not sure this is significant enough of a win post-compression to justify the extra effort, but cc: @eerhardt

**Comment by CoffeeFlux** [comment]
Also, for reference, all English locales:
```
-rw-r--r--  1 ryan  staff   549520 Feb 23 19:25 icudt_EFIGS.dat
```

**Comment by lewing** [comment]
Compressed sizes?

**Comment by CoffeeFlux** [comment]
That one is harder to check without knowing the exact Brotli settings we use - do you know where I can find those?

**Comment by CoffeeFlux** [comment]
By default, we use quality 11.

Full EFIGS:
```
-rw-r--r--  1 ryan  staff   148657 Feb 26 17:56 icudt_EFIGS.dat.br
```

All English locales:
```
-rw-r--r--  1 ryan  staff   138302 Feb 23 19:25 icudt_EFIGS.dat.br
```

en_US only:
```
-rw-r--r--  1 ryan  staff   130624 Feb 26 17:49 icudt_EFIGS.dat.br
```

So shipping only en_US instead of EFIGS saves about 18k. All English locales is around 10k.

**Comment by CoffeeFlux** [comment]
@lewing do you think this is worth splitting up further, or is the savings here not worth the added complexity? I'd prefer to defer that judgement to you since I don't have a good idea of the complexity this would add on the Blazor end.

**Comment by CoffeeFlux** [comment]
This is probably only worth it if we are able to split the locale-specific data from the more generic data required.
