### ISSUE TITLE
RSA.ImportParameters terminates Win32 service application at reboot

### ISSUE THREAD

**Issue by candritzky** [dotnet/runtime#48352]
### Description

We have an ASP.NET Core 3.1 application that is running as a Win32 service (`IHostBuilder.UseWindowsService`) using the Local System account. The Win32 service is configured to start automatically at system startup.

Our application calls `RSA.Create` followed by `RSA.ImportParameters` within the `Startup.ConfigureServices` startup code using a properly configured `RSAParameters` instance.

The `ImportParameters` call causes the application to terminate silently when it is started by the Windows SCM (Service Control Manager) at system startup, i. e. after reboot. No (managed) exception is thrown from the `ImportParameters` call. As a result the Windows SCM logs an error to the Windows event log after the default service startup timeout (30 seconds) expired.

When our service is started manually (after interactive login) using services.msc, everything works as expected.

This happens only on a few machines, not on others. I currently have a reproducible environment using Windows Server 2012 R2 in an Azure hosted VM (4 processors, 16 GB RAM). Here it is 100% reproducible.

### Configuration

.NET Core 3.1.9, self-contained win-x64 app (dotnet publish -r win-x64).
Already tried .NET Core 3.1.12, but it doesn't fix the problem.
Running on Windows Server 2012 R2 (x64) (Azure hosted VM).

### Other information

Here is the problematic code. Issue can be reproduced by placing this code at the beginning of the `Program.Main` method.

``` csharp
var rsa = RSA.Create();
var parameters = new RSAParameters
{
    Modulus = ...,
    Exponent = ...
};
try
{
    rsa.ImportParameters(parameters);
    // doesn't come here
}
catch (Exception ex)
{
    // doesn't come here either because the process just silently terminates
}
```

Other things we've tried without success:
- Compiled using .NET Core 3.1.12 (see also above) instead of 3.1.9.
- Configured the Win32 service to use delayed auto start.

**Comment by vcsjones** [comment]
> No (managed) exception is thrown from the ImportParameters call.

Is anything else in the event viewer that may be relevant leading up to the crash? Possible event sources may be the "Crypto-CNG" or "Crypto-NCrypt" event sources, or an "Application Error" with the application's fault info.

> Already tried .NET Core 3.1.12, but it doesn't fix the problem.

Is it possible for you to try on 5.0, just to help gather more information?

**Comment by candritzky** [comment]
> Is anything else in the event viewer that may be relevant leading up to the crash? Possible event sources may be the "Crypto-CNG" or "Crypto-NCrypt" event sources, or an "Application Error" with the application's fault info.

No, sorry, no "Crypto-CNG" or "Crypto-NCrypt" events, no "ApplicationError" with the application's fault info, no errors (despite the service timeout error after 30 seconds), nothing else that looks helpful.

> Is it possible for you to try on 5.0, just to help gather more information?

Yes, this is possible. Tried with .NET 5.0.3 (System.Security.Cryptography.*.dll file version 5.0.321.7212). Same problem here.

**Comment by vcsjones** [comment]
@candritzky okay, thanks! I will attempt to reproduce. Just to double check:

```
var parameters = new RSAParameters
{
    Modulus = ...,
    Exponent = ...
}
```

I take it that you are importing `RSAParameters` that have _only_ `Modulus` and `Exponent`, i.e. a public key? Not a private key?

**Comment by candritzky** [comment]
@vcsjones Yes, correct, it's public key and only Modulus and Exponent are set.

**Comment by candritzky** [comment]
@vcsjones Here are example parameters, maybe it helps:

``` csharp
Modulus = Convert.FromBase64String("86zSCDt97y+MvEzrEa9UagoTDjOnpYL6SviWz3sur9vCfFjYAgClF4xZl6dd4XpXbpXKgJyB8MuhSz7WMBJiBSBzYL20OVySZeHYseMT4spmYk8F4cBOhCDv7JOSlUVU+HNO12W6w+dyeyKsyExpDmbWCUnzwu0MCc6eW+qh/wFr5e90vzA5CsE11o9X6sypy4ZNc3RjwD4zfmB5SXGOfmWqkemCPhkOKaBj7H7OUF2EAzY90zhjvStRzY0Cw3khJJRn6miJwv9VBCeqlvIgbJHQhFHGijvpz6MM/30tkrhB9kEn14iljPJ9wOJ5qqQMzsUihmlRrBmGGPuUYgiMxw=="),
Exponent = Convert.FromBase64String("AQAB")
```

These are the public key parameters of a public/private key pair that was generated using a .NET Framework 4.5 application.

**Comment by candritzky** [comment]
I can reproduce this in a Windows Server 2012 R2 VM (x64) running on a Windows 10 (x64) host in Hyper-V.

New observation/correction: The process doesn't crash, it just hangs on the ImportParameters call for 30 seconds until it is killed by the Windows SCM.

**Comment by candritzky** [comment]
Issue happens only on Windows Server 2012 R2, not on Windows Server 2016.

**Comment by SteveSyfuhs** [comment]
Certain crypto calls cannot be made from service start. See this arbitrarily picked reference: https://docs.microsoft.com/en-us/windows/win32/api/ncrypt/nf-ncrypt-ncryptopenkey#remarks

> A service must not call this function from its StartService Function. If a service calls this function from its StartService function, a deadlock can occur, and the service may stop responding.

Given that you say 

> Our application calls RSA.Create followed by RSA.ImportParameters within the Startup.ConfigureServices startup code using a properly configured RSAParameters instance.

I'd wager this is what you're hitting. You should consider moving the code into a non-startup path.

**Comment by bartonjs** [comment]
Wow, nice sleuthing, @SteveSyfuhs.

**Comment by candritzky** [comment]
@SteveSyfuhs Thanks man. We are running exactly into this deadlock problem.

We'll fix our code to defer the call to the crypto APIs until really needed, so that is is out of the startup path.
