### ISSUE TITLE
Default branch has been renamed to main

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48357]
**Part of March's batched infrastructure rollout: https://github.com/dotnet/runtime/issues/48168**

On March 1st 2021 (Monday) we're going to rename the default branch in this repository to `main`. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172). Expect the process to begin around 8AM UTC.

**Comment by ViktorHofer** [comment]
Will leave this issue open to make the change _very_ visible. See also the following on the repo home page
![image](https://user-images.githubusercontent.com/6431421/105438083-2fbf4700-5c17-11eb-87ec-904a35e55df6.png)

**Comment by Nirmal4G** [comment]
Alternative solution #49017 without changing your local setup; that is, if you have a more complicated setup (_like mine_)

**Comment by ViktorHofer** [comment]
Inlined content from https://github.com/dotnet/runtime/issues/49017 into this discussion.

@Nirmal4G wrote:

> For all those who can't pull `master`, it has renamed to `main`.
To preserve refspec to patches and branches, just changing the `heads/master` to `heads/main` should work.

```diff
[remote "origin"]
	url = https://github.com/dotnet/runtime
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/main:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/main
```

> Putting this out there, if anyone else facing similar issue with git.

**Comment by ViktorHofer** [comment]
Closing.
