### ISSUE TITLE
Change runtime annotations/suppressions after linker change

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#48367]
### Description

- After changes in https://github.com/mono/linker/pull/1829 we need to remove the suppressions for warnings this change resolves.
- Type.GetMembers uses the annotation [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)], this annotation keeps more stuff than what GetMembers should keep (GetMembers should not keep interfaces nor members inside a nested type).

**Comment by eerhardt** [comment]
Should be able to fix this as well:

https://github.com/dotnet/runtime/blob/0026a202ab4087d237f6be8824dff322d3a7d6be/src/libraries/Common/src/System/Drawing/ColorTable.cs#L23-L26
