### ISSUE TITLE
[Apple Silicon] unclear that published binaries need to be signed

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#48387]
**Setup:**
Mac OS: Big Sur(11.2) - Apple M1 chip
.NET 6 arm64: 6.0.100-preview.1.21103.13(runtime 6.0.0-preview.1.21102.12)

**Steps to reproduce:**
1.Create a project with TFM 6.0
2.Publish it with rid "osx.11.0-arm64"
3. Try to run the executable file in the publish directory

**Expected result:**
The executable file in the publish directory will be  run success

**Actual result:**
zsh: killed" occurred when run the executable file in the publish directory
![image](https://user-images.githubusercontent.com/1578239/107451245-d85f2780-6b81-11eb-9460-fd2f124e35c2.png)

**Dotnet --info**
![image](https://user-images.githubusercontent.com/1578239/107451315-fd539a80-6b81-11eb-8fb6-0222c7d61ed5.png)

**Comment by vitek-karas** [comment]
@sdmaclea can you please take a look - the target RID is osx-arm64

**Comment by sdmaclea** [comment]
Big Sur requires executables to be signed to be run.  `dotnet publish -r osx-arm64` will produce unsigned binaries.  You will need to sign the published binary before it will run (Unless you are running with Apple SIP disabled and in developer mode).

You can sign the binaries with the Apple `codesign` tool.  A simple adhoc signature would be sufficient for you to test.  `codesign -s - <path-to-sign>`.  

We will need to document this somewhere.  It is possible we should have the `dotnet publish` notify the user of the need to sign the apphost.

This probably needs to be transferred back to the SDK if we want to change publish behavior.

/cc @richlander

**Comment by jeffschwMSFT** [comment]
Adding @KathleenDollard.  I was not aware that Big Sur M1 requires output compiled in the dev inner loop to be signed.  Do we need to change our sdk to make this happen by default?

cc @marcpopMSFT

**Comment by sdmaclea** [comment]
We are discussing signing in dotnet/designs#182

**Comment by agocke** [comment]
This should be resolved for publishing on Mac. Other platforms won't sign, but Mac will automatically.

**Comment by k15tfu** [comment]
@agocke Hi! Could you please link the PR resolving this?

**Comment by agocke** [comment]
This should have been resolved by https://github.com/dotnet/runtime/pull/53913
