### ISSUE TITLE
Microsoft.Extensions.DependencyInjection.Abstractions library embeds trimming attributes

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#48399]
which breaks their trimming. They are public API and should not be [embedded](https://github.com/dotnet/runtime/blob/6f93c0b826e5824408e16bcdab749cb006e54af3/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/Microsoft.Extensions.DependencyInjection.Abstractions.csproj#L12-L14) in netcore builds as we do [elsewhere](https://github.com/dotnet/runtime/blob/6f93c0b826e5824408e16bcdab749cb006e54af3/src/libraries/Microsoft.Extensions.DependencyInjection/src/Microsoft.Extensions.DependencyInjection.csproj#L29-L33).

**Comment by ViktorHofer** [comment]
> They are public API

They are exposed on net5.0 and above only right? I think libraries like DI only embed them on configurations where the API isn't available like netstandard or netcoreapp2/3.x.

**Comment by marek-safar** [comment]
> I think libraries like DI only embed them on configurations where the API isn't available like netstandard or netcoreapp2/3.x.

That's not the case for Microsoft.Extensions.DependencyInjection.Abstractions

**Comment by ViktorHofer** [comment]
DI.Abstractions doesn't have a .NETCoreApp configuration?

**Comment by marek-safar** [comment]
no, check the source code link in the description

**Comment by ViktorHofer** [comment]
Right, but my point is that DI.Abstractions doesn't have a [.NETCoreApp configuration](https://github.com/dotnet/runtime/blob/6f93c0b826e5824408e16bcdab749cb006e54af3/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/Microsoft.Extensions.DependencyInjection.Abstractions.csproj#L4) which means those APIs aren't exposed and need to be embedded.

**Comment by eerhardt** [comment]
> which breaks their trimming.

@marek-safar - can you explain how this breaks their trimming? The original intention of these attributes is that the linker finds them by name, so any assembly can declare the attribute as long as it has the right namespace + name + shape.

@ViktorHofer is right that DI.Abstractions doesn't build for .NET Core. It only builds for netstandard2.0 and net461. We have quite a few assemblies like this in `dotnet/runtime`, and we are adding more - for example https://github.com/dotnet/runtime/pull/48318#discussion_r577186125 is discussing dropping the .NET Core build for `Microsoft.Extensions.DependencyInjection` as well since it is unnecessary.

**Comment by marek-safar** [comment]
> can you explain how this breaks their trimming

We have them pinned for removal under SPC because they are public API. See
https://github.com/dotnet/runtime/blob/master/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L24

**Comment by eerhardt** [comment]
We will need to fix the ILLink.LinkAttributes.xml file to tell the linker to remove these attributes from any assembly.

https://github.com/dotnet/runtime/blob/ada53f0c05efd882e29e8f225a483521f08e3caa/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L18

Just like we do for:

https://github.com/dotnet/runtime/blob/ada53f0c05efd882e29e8f225a483521f08e3caa/src/mono/System.Private.CoreLib/src/ILLink/ILLink.LinkAttributes.xml#L145-L156

These attributes are allowed to be in any assembly. It doesn't make sense to make every library to build for net5.0+ just so it can reference the attributes from corelib.

cc @vitek-karas
