### ISSUE TITLE
Possible miscompile in loop inside try/finally

### ISSUE THREAD

**Issue by james-hunt-ra** [dotnet/runtime#48394]
### Description

The function F, below, returns 1 when run in Release mode on .NET 5 on x64 Win 10.

It is expected to return 0 - which it does indeed return in both Debug configuration, and also under .NET Core 3.1.

```csharp
using System;

namespace Miscompile
{
    class Program
    {       
        static void Main()
        {
            int result = F();
            if (result == 0)
            {
                Console.WriteLine("OK");
            }
            else
            {
                Console.WriteLine($"FAILED! result = {result}");
            }
        }

        // When compiled in Release mode, this function returns 1 under .NET 5
        // Expect it to return 0, which is the case under .NET Core 3.1
        private static int F()
        {
            bool x = false;            
            int c = 0;

            try
            {
                while (true)
                {
                    // It appears this assignment is erroneously removed or hoisted out of loop?
                    c = 0;

                    if (!x)
                    {
                        c++;
                        x = true;
                    }
                    else
                    {
                        return c;
                    }

                    // Uncommenting the below fixes issue, even if the assignment
                    // to c at loop start is commented out
                    // c = 0;
                }
            }
            finally
            {
                // finally block appears necessary to 
                // reproduce the error
                // Commenting out the finally block, the if expression,
                // or even just the WriteLine statement fixes the problem
                if (c != 0)
                {
                    Console.WriteLine("c not zero");
                }
            }
        }        
    }
}
```

### Configuration

.NET Version: .NET 5
OS: Windows 10
Arch: x64

Does not occur on .NET Core 3.1 or below.
Does not occur in Debug builds.
Not tested on other architectures or operating systems.

### Regression?

Yes - worked in .NET 3.1 and before.

### Other information

Workarounds - see the comments in code above. There are two minor alterations that stop it miscompiling.

**Comment by EgorBo** [comment]
A bit simplified repro:
```csharp
    private static void Foo2()
    {
        bool x = false;
        int c = 0;

        try
        {
            while (true)
            {
                c = 0;

                if (!x)
                {
                    c = c + 100;
                    x = true;
                }
                else
                {
                    return;
                }
            }
        }
        finally
        {
            Console.WriteLine(c);
        }
    }
```
Here is the asm diff https://www.diffchecker.com/yYXyTBgm 
Left: SSA-phase is disabled, Right: SSA is enabled (by default)

Left one produces the expected output.
(I also disabled finally-cloning for both to make asm less verbose)

/cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Seems like it could be the new in 5.0 optimization that removes redundant zero inits (#36918, and subsequent PRs like #37786, #38314).

**Comment by AndyAyersMS** [comment]
The redundant zero init opt is checking `lvLiveInOutOfHndlr` but only after possibly optimizing away a store.

Wonder if the last bool in this clause was meant to be `&&`? cc @erozenfeld 

https://github.com/dotnet/runtime/blob/9195df699fe25d2e752c2bc350c16dc199f02f7a/src/coreclr/jit/optimizer.cpp#L9475-L9478

**Comment by erozenfeld** [comment]
We should never remove zero inits that are in a loop so these lines should be:

```
if (!bbInALoop)
{
    if (BitVecOps::IsMember(&bitVecTraits, zeroInitLocals, lclNum) || 
        (lclDsc->lvIsStructField && 
         BitVecOps::IsMember(&bitVecTraits, zeroInitLocals, lclDsc->lvParentLcl)) || 
        (!lclDsc->lvTracked && !fgVarNeedsExplicitZeroInit(lclNum, bbInALoop, bbIsReturn))) 
```

**Comment by AndyAyersMS** [comment]
Thanks Eugene... let me see what this does.

**Comment by AndyAyersMS** [comment]
Seeing a fair number of diffs.

Will take a while to sort which of these are fixes and which of these are us now being too cautious, and to assess how much of the original opt is now undone.

**Comment by AndyAyersMS** [comment]
@EgorBo is going to follow up here.

**Comment by erozenfeld** [comment]
Slightly less conservative check is:

```
if (!bbInALoop || bbIsReturn)
{
    if (BitVecOps::IsMember(&bitVecTraits, zeroInitLocals, lclNum) || 
        (lclDsc->lvIsStructField && 
         BitVecOps::IsMember(&bitVecTraits, zeroInitLocals, lclDsc->lvParentLcl)) || 
        (!lclDsc->lvTracked && !fgVarNeedsExplicitZeroInit(lclNum, bbInALoop, bbIsReturn))) 
```
similar to what we do in `fgVarNeedsExplicitZeroInit`

**Comment by erozenfeld** [comment]
@EgorBo ping me if you have questions about the algorithm

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/48810 (5.0) and https://github.com/dotnet/runtime/pull/48571 (main)
