### ISSUE TITLE
Add property JsonNamingPolicy.ConvertName() overload with Type parameter

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/runtime#48396]
## Background and Motivation

During migration from `Newtonsoft.Json` we discovered following unsupported scenario.

We had special naming policy for properties of specific types. In our case we were adding type-specific prefix to property names of some types (they are complex types with custom converters) which were used by consumer (javascript app in our case) to apply deserialization logic based on property prefix.

Problem with System.Text.Json is that `JsonNamingPolicy.ConvertName` method accepts only property name.
I suggest to add additional overload with `Type` parameter (all call sites already have type information for it).

Only workaround I found is manually annotate all affected properties with `JsonPropertyName` attribute, which is quite unpleasant way to fix it :disappointed: 

## Proposed API

```diff
namespace System.Text.Json
{
    public abstract class JsonNamingPolicy {
+        public virtual string ConvertName(string name, Type type);
    }
}
```
Proposed method implementation (should be called instead of current `ConvertName` by consumers):
```cs
public virtual string ConvertName(string name, Type type) => ConvertName(name);
```

## Usage Examples

``` C#
public class MyCustomNamingPolicy  : JsonNamingPolicy
{
    public override string ConvertName(string name, Type type)
    {
        var name = ConvertName(name);
        // or
        //var name = JsonNamingPolicy.CamelCase.ConvertName(name);
        return type == typeof(PerfixedType) : "prefix_" + name : name;
    }

    public override string ConvertName(string name) => JsonNamingPolicy.CamelCase.ConvertName(name);
}

```

## Alternative Designs

I think it is most straightforward one. And much-much cleaner than implementation we used with `Newtonsoft.Json`.

## Risks

None? Minor performance hit on extra call with extra parameter shouldn't be a problem as results of property name generation are cached and reused.

**Comment by eiriktsarpalis** [comment]
I'm not very familiar with the Json.NET feature, but wouldn't there also need to be a corresponding construct for deserialization?

**Comment by MaceWindu** [comment]
This proposal is about richer context for json property name generation logic. Don't think it has anything with de/serialization.

**Comment by eiriktsarpalis** [comment]
Out of curiosity, how were you able to achieve the same result in Json.NET? At quick glance the equivalent construct seems to be the [`NamingStrategy`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_NamingStrategy.htm) class, which doesn't seem to accept a `Type` parameter either.

**Comment by MaceWindu** [comment]
1. we used class, derived from [CamelCasePropertyNamesContractResolver](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_CamelCasePropertyNamesContractResolver.htm) and override `CreateProperties` method
2. also for model binding from request (asp.net mvc app) we were customizing [System.Web.Mvc.DefaultModelBinder](https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Mvc/DefaultModelBinder.cs) using BindProperty method override...

**Comment by layomia** [comment]
In .NET 6 we are providing an `IContractResolver`-like mechanism to configure type and [property metadata](https://github.com/dotnet/runtimelab/blob/3e2a5bfc04115b1acc138770cc7b86a512183121/src/libraries/System.Text.Json/ref/System.Text.Json.cs#L771), as part of the JSON source gen work (https://github.com/dotnet/runtime/issues/31257, https://github.com/dotnet/runtime/issues/45448). You'll be able to configure property metadata as you described above:

> we used class, derived from CamelCasePropertyNamesContractResolver and override CreateProperties method
