### ISSUE TITLE
Assertion failed 'call->gtControlExpr == nullptr' in 'System.Text.Json.JsonParameterInfo`1[Nullable`1]

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#48403]
Seeing below failures in libraries-jitstressregs on Linux arm64/Windows arm64/Linux x64. It got introduced in https://github.com/dotnet/runtime/pull/47808

```
Assert failure(PID 135 [0x00000087], Thread: 147 [0x0093]): Assertion failed 'call->gtControlExpr == nullptr' in 'System.Text.Json.JsonParameterInfo`1[Nullable`1][System.Nullable`1[System.UInt64]]:Initialize(System.Type,System.Reflection.ParameterInfo,System.Text.Json.JsonPropertyInfo,System.Text.Json.JsonSerializerOptions):this' during 'Morph - Global' (IL size 101)

    File: /__w/1/s/src/coreclr/jit/morph.cpp Line: 9192
    Image: /root/helix/work/correlation/dotnet
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47307-head-5275d70d52b544f981/System.Text.Json.Tests/console.ebed8485.log?sv=2019-07-07&se=2021-03-09T08%3A58%3A31Z&sr=c&sp=rl&sig=fuZORDqaA2Hwbji7AAwR%2B%2FwqptUnkEdVbpom5xH94xs%3D

**Comment by kunalspathak** [comment]
@briansull , @dotnet/jit-contrib

**Comment by briansull** [comment]
I will investigate
