### ISSUE TITLE
DateTimeOffset.TryParse fails on .Net 5 with Globalization while it works on all other releases

### ISSUE THREAD

**Issue by atakane** [dotnet/runtime#48401]
### Description

While working on culture-based DateTime parsing, .NET 5 acts totally different than the previous ones, including Core 3.x, Rosyln 3.8, and 4.7.2. For all previous releases, the output is always the same, while 5.0.102 returns false.

```
using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		CultureInfo cultureInfo = CultureInfo.GetCultureInfo("ru");
		
		DateTimeOffset dt;
        bool parseSuccess = DateTimeOffset.TryParse("Ср, 17 фев 2021 15:03:25 +0300", cultureInfo.DateTimeFormat, DateTimeStyles.None, out dt);
		Console.WriteLine(dt.UtcDateTime);
	}
}
```

The expected output is: ```2/17/2021 12:03:25 PM```
.NET 5 (on Windows, Linux (ubuntu), and macOS) returns ```01/01/0001 00:00:00```

### Configuration

version .NET 5.0.102
OS: macOS, Windows 10, Linux (ubuntu)
Architecture: x64

### Regression?

It works on all previous releases of .NET Core, and .NET Framework, including Core 3.x, Rosyln 3.8, and 4.7.2.

### Other 

On https://github.com/dotnet/runtime/issues/1681, one of the collaborators says month names, etc. are all delegated to the host OS by design.  Based on that, I made a quick test and used ```февр.``` instead of ```фев``` for the month name so it becomes  ```Ср, 17 февр. 2021 15:03:25 +0300```. This time .NEt 5 compiler parsed the date as expected. Apparently .NET 5 doesn't like some of the short names on some cultures.

Since I'm using (and trying to fix the DateTime parsing for) [FeedReader](https://github.com/codehollow/FeedReader) project to process RSS feeds in more than 10 different languages, It's impossible to make such conversions for each culture if that's the case.

**Comment by MichalPetryka** [comment]
Probably related to .Net 5 using ICU on Windows. Could you check if parsing works when you force NLS with a runtime switch? https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#nls

**Comment by atakane** [comment]
> I'd say it's related to .Net 5 using ICU on Windows. Could you check if parsing works when you force NLS with a runtime switch? https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#nls

Isn't ICU related to Windows apps? It's failing on all operating systems including Windows. So, I think it should be something else. (I'll give it a try though on Windows)

**Comment by MichalPetryka** [comment]
> > I'd say it's related to .Net 5 using ICU on Windows. Could you check if parsing works when you force NLS with a runtime switch? https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#nls
> 
> Isn't ICU related to Windows apps? It's failing on all operating systems, including Windows. So, I think it should be something else. (I'll give it a try, though on Windows)

ICU was always used for other platforms, .NET 5 moved from NLS to ICU to provide the same behavior everywhere.

**Comment by atakane** [comment]
@MichalPetryka I see the point here. If I force NLS, it works on Windows environments. Upgrading to .NET 5 changes behaviors on Windows systems. 

However, in my case, the behavior (parsing DateTime) has been changed for the other platforms as well. According to the documentation (and to you also), ICU has always been used for Linux, macOS, and Dockerized versions, therefore upgrading a codebase from .Net Core 3.x to .Net 5.x should not change the DateTime parsing methodology as they always been using ICU, right? 

The same code works on Linux, macOS, and Dockerized environments (like -alpine) if I use Core 3.x which uses ICU on those platforms, and fails on the same platforms for .NET 5 which also uses ICU.

**Comment by tarekgh** [comment]
@atakane

> The same code works on Linux, macOS, and Dockerized environments (like -alpine) if I use Core 3.x which uses ICU on those platforms, and fails on the same platforms for .NET 5 which also uses ICU.

I am not sure if this is fully true. the same code you have I just ran it on `Ubuntu 20.04` (with .NET 5.0 or net core 3.1 too) and it is failing the same way if you run it on Windows when using .NET 5.0.

To summarize, the parse failure you are seeing is because now we are using ICU which is using the CLDR (Unicode Standard) data. This data is using abbreviated month names for Russia which is different than what we used to have on Windows (when using NLS). 
If you are seeing the same code not failing on some Linux runs with 3.1, the only explanation is you have old ICU version which is not updated with the CLDR data. You may try to print the abbreviated month names on such platforms and look if you are getting the names with the dots. Also, if you install the .NET 5.0 side by side with net core 3.1 on such platforms, you should see the exact behavior. If not, please share some more details about your running environment and we'll be happy to help.

**Comment by tarekgh** [comment]
@atakane I am closing this issue but feel free to respond back if you have any question or need help with anything and we can reopen the issue if needed. Thanks for your report.

**Comment by atakane** [comment]
> @atakane I am closing this issue but feel free to respond back if you have any question or need help with anything and we can reopen the issue if needed. Thanks for your report.

@tarekgh Thank you for the explanation. You're right, apparently, the platforms I used seem hosted on Win rather than Linux. After your detailed explanation, I created 3 different Docker containers for 3.1, 5.0, and 6.0-preview and they all gave the exact same parsing error.

While the issue is clear, the problem is still hanging there for me to solve. In general RSS 2.0 feeds don't conform to the RFC 822, and there is no option to force NLS on Docker containers on Linux. What do you suggest?

**Comment by tarekgh** [comment]
> In general RSS 2.0 feeds don't conform to the RFC 822, and there is no option to force NLS on Docker containers on Linux. What do you suggest?

You can try to create DateTimeFormatInfo object and override the abbreviated month names there with the names you get from NLS. Something like:

```C#
        CultureInfo cultureInfo = new CultureInfo("ru");
        cultureInfo.DateTimeFormat.AbbreviatedMonthNames = new string[] { "янв", "фев", "мар", "апр", "май", "июн", "июл", "авг", "сен", "окт", "ноя", "дек", "" };
        DateTimeOffset dt;
        bool parseSuccess = DateTimeOffset.TryParse("Ср, 17 фев 2021 15:03:25 +0300", cultureInfo.DateTimeFormat, DateTimeStyles.None, out dt);
        Console.WriteLine($"Parsed: {parseSuccess} Result: {dt.UtcDateTime}");
```

**Comment by atakane** [comment]
Thanks, that makes sense! I'll give it a try. Now, let me figure out other 10 languages :)
