### ISSUE TITLE
Alpine images for 3.1

### ISSUE THREAD

**Issue by chlsmith** [dotnet/runtime#48405]
Why is the 3.1 runtime image still stuck on Alpine 3.12?   3.13 has been available for approximately a month.

**Comment by danmoseley** [comment]
@MichaelSimons  should this be in your repo, could you transfer?

**Comment by MichaelSimons** [comment]
The main issue tracking the work to add support for Alpine 3.13 for 2.1 and 3.1 is https://github.com/dotnet/core/issues/5687.  https://github.com/dotnet/dotnet-docker/issues/2530 is the specific issue tracking Docker images.

>Why is the 3.1 runtime image still stuck on Alpine 3.12? 3.13 has been available for approximately a month.
I apologize for the slowness in adoption.  It has taken longer than we would like.
