### ISSUE TITLE
.RemoveAt(Index)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#48415]
## Background and Motivation
Sometimes you want to remove items based on their position from the end.

## Proposed API
```MyList.RemoveAt(^1)```

## Usage Examples
```MyList.RemoveAt(^1)```

## Alternative Designs
```MyList.RemoveAt(MyList.Count - 1)```

## Risks
None.

**Comment by eiriktsarpalis** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/321. Feel free to continue the conversation in the other issue.
