### ISSUE TITLE
projectUrl elements in nuspec now showing git:// prefixed url for Microsoft.NETCore.App.*

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#48421]
This blocks pushes to nuget.org. The projectUrl appears to have been changed over from https://dot.net, aspnetcore.net, etc. and is now showing a git:// prefixed cloning url instead. This blocks any nuget.org push because that is not viewed as a valid project url.

**Comment by danmoseley** [comment]
@ViktorHofer

**Comment by ViktorHofer** [comment]
Probably regressed with some of the packaging property consolidation changes. Just assigned myself and will fix before we branch off for P2.

**Comment by leecow** [comment]
Thanks, Viktor. Do we have any reasonable options for validating the nuspec so that this type of issue can be caught before we attempt to push packages?

**Comment by ViktorHofer** [comment]
> Do we have any reasonable options for validating the nuspec so that this type of issue can be caught before we attempt to push packages?

Apparently `dotnet verify` only checks a package's signature. @nkolev92 does nuget offer validation of the nuspec, in this case the ProjectUrl?

**Comment by nkolev92** [comment]
That wouldn't get validated by the client at this point. 
In this particular situation, NuGet would validate that the content is a Uri but not much more than that.
