### ISSUE TITLE
HttpClient.DefaultProxy .net core 3.1 doesn't on Linux ubuntu 16.4 kubernetes container

### ISSUE THREAD

**Issue by YurongHe** [dotnet/runtime#48434]
### Description

Have http_proxy, https_proxy env configured in Linux ubuntu 16.4 Kubernetes container. 
Using HttpClient.DefaultProxy, the calls doesn't go through proxy server.

code:                         
HttpClient httpClient = new HttpClient();
HttpResponseMessage result = httpClient.GetAsync(new Uri("https://google.com")).GetAwaiter().GetResult();

But if I use httpClientHandler to set WebProxy with the same env variable setting running in the process. I can see the call go through the proxy server.

HttpClientHandler Code:
proxy = new WebProxy(new Uri(httpProxy), shouldByPassProxyOnLocal, byPassList);
HttpClientHandler httpClientHandler = new HttpClientHandler
{
          Proxy = proxy,
};

 return new HttpClient(handler: httpClientHandler, disposeHandler: true);

Is there any known issue for .netcore 3.1 on Linux container?

**Comment by wfurt** [comment]
what do you set exactly @YurongHe ?

**Comment by YurongHe** [comment]
> what do you set exactly @YurongHe ?

export http_proxy=52.152.145.65:3128
export https_proxy=52.152.145.65:3128
exprot no_proxy=localhost, 127.0.0.1

**Comment by wfurt** [comment]
use 
```
export http_proxy=http://52.152.145.65:3128
export https_proxy=http://52.152.145.65:3128
```
or simple `export all_proxy=http://52.152.145.65:3128`

**Comment by YurongHe** [comment]
> use
> 
> ```
> export http_proxy=http://52.152.145.65:3128
> export https_proxy=http://52.152.145.65:3128
> ```
> 
> or simple `export all_proxy=http://52.152.145.65:3128`

I will try it without setting no_proxy and see if it works.

**Comment by YurongHe** [comment]
> > use
> > ```
> > export http_proxy=http://52.152.145.65:3128
> > export https_proxy=http://52.152.145.65:3128
> > ```
> > 
> > 
> > or simple `export all_proxy=http://52.152.145.65:3128`
> 
> I will try it without setting no_proxy and see if it works.

Then how do we skip internal traffic?

**Comment by wfurt** [comment]
no_proxy is unrelated IMHO. You can still use it.

**Comment by YurongHe** [comment]
> no_proxy is unrelated IMHO. You can still use it.

I have tried setting:
controller@control-fbxpx:/$ export | grep http
declare -x http_proxy="http://52.152.145.65:3128"
declare -x https_proxy="https://52.152.145.65:3128"

still doesn't use them. The call didn't go through proxy server. 

I would like confirm this works on Ubuntu 16.4 kubernetes container?

**Comment by wfurt** [comment]
I see no reason why this would not work. You can post the container and/or verify in your app that the variables are set inside the container. The `https_proxy` value  is not right. the URI for the cache value has protocol to the proxy and that should be HTTP even for HTTPS e.g. this will use plain HTTP and CONNECT verb to the proxy for your HTTPS destinations. the `all_proxy` may be  less confusing in that regard.

**Comment by YurongHe** [comment]
> I see no reason why this would not work. You can post the container and/or verify in your app that the variables are set inside the container. The `https_proxy` value is not right. the URI for the cache value has protocol to the proxy and that should be HTTP even for HTTPS e.g. this will use plain HTTP and CONNECT verb to the proxy for your HTTPS destinations. the `all_proxy` may be less confusing in that regard.

Thanks for your help. I tried stand alone .netcore app in kubernetes container, which works properly. I think the problem is on our side backend code. I will close it and do more investigation on our side.

Regards,
