### ISSUE TITLE
Failure to restore 2.1.808 SDK dependency

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#48443]
we have a 2.1.808 SDK dependency because of a partner plugin. There has been couple of failures while restoring the sdk.

We should either try to get rid of this dependency. In the mean time we should try to mitigate the failure by manual retry in .yml or some other method.

cc @dotnet/runtime-infrastructure

**Comment by mletterle** [comment]
Is the dependency being restored via the [dotnet-coreclr feed](https://dotnetfeed.blob.core.windows.net/dotnet-coreclr/index.json ) ? I've begun to see intermittent failures restoring from that feed that hasn't been an issue in the past.

**Comment by ViktorHofer** [comment]
No, that feed isn't used anymore in dotnet/runtime.

**Comment by ViktorHofer** [comment]
@Anipik it's the ESRP task that requires the 2.x SDK to be installed. @MattGal can you help us get in touch with the ESRP team so that we don't need to install that SDK anymore?

From my offline conversation with one of the ESRP PMs from which I haven't heard back unfortunately:

> So we currently hit transient network when using the ESRP task when downloading a 2.1 dotnet SDK. We would like to avoid that dependency at all and just use the already downloaded 5.0/6.0 SDK. Unfortunately ESRP currently parses some output and only works with a 2.1 SDK. We believe that actually isn't great and blocks using newer SDK via roll forward. Another option and actually the preferred one would be to distribute the ESRP task as self-contained to lift the requirement on an installed SDK completely.

**Comment by ViktorHofer** [comment]
Filed a core-eng issue: https://github.com/dotnet/core-eng/issues/12597

**Comment by jkoritzinsky** [comment]
We havent hit issues with this in a bit and we've since updated the ESRP client and it uses a newer SDK version.
