### ISSUE TITLE
Add platform native long support to runtime

### ISSUE THREAD

**Issue by OtherCrashOverride** [dotnet/runtime#4844]
Currently, C# `long` maps to `System.Int64` in the runtime.  However, the `native long` may be 32bit or 64bit depending on platform.  We need a new type that transitions from 32bit to 64bit as appropriate for the platform in much the same way as `IntPtr` does.  This issue is present when you compile a C/C++ project on 64bit platforms and need to perform interop.

Windows is a LLP platform.
Windows 32bit: native long = 32bits
Windows 64bit: native long = 32bits

Linux is a LP platform.
Linux 32bit: native long = 32bits;
Linux 64bit: native long = 64bits;

For clarity, `IntPtr` is ALWAYS 32bit on 32bit platforms and ALWAYS 64bit on 64bit platforms.  The `native long` may be 32bit or 64bit depending on the 64bit platform in use.  This is related to dotnet/runtime#4216.  The goal is to make the p/invoke signature match without rewriting the import for each target platform (windows/linux).

I have searched the issues and did not find this as a duplicate.  However, if it is, please feel free to mark it as such and close it.

**Comment by jkotas** [comment]
Duplicate of #27530

**Comment by DeafMan1983** [comment]
Nice idea - You know I have ported from Java Native Access to C# but not complete implements for C#. Thank you for trick with Type GetFieldType() with int and long. But what is about Pointer and PointerType for C# under Dotnet.  Thanks
