### ISSUE TITLE
Make IMemoryCache fully generic to avoid boxing

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#48455]
I was surprised to see that IMemoryCache is a non-generic API, meaning that both keys and values box if they're value types, leading to unnecessary allocations. This showed up when profiling EF Core, where we took care to have a value type key.

/cc @ajcvickers

**Comment by maryamariyan** [comment]
Related to https://github.com/dotnet/runtime/issues/48567

cc: @adamsitnik

**Comment by adamsitnik** [comment]
Since #48567 includes this proposal and some other good ideas I am going to close it as a duplicate.
