### ISSUE TITLE
OSX build instructions update

### ISSUE THREAD

**Issue by StrongRef** [dotnet/runtime#4845]
I have found some issues while building coreclr on OSX.
There are a couple of open issues already:
https://github.com/dotnet/coreclr/issues/2357 (fatal error: 'unixasmmacros.inc')
https://github.com/dotnet/coreclr/issues/2054 (OSX build fails with latest CMAKE 3.4 release)

They describe issues with _CMake 3.4_, _ulimit_ and _MONO_THREADS_PER_CPU_.

I'm using CMake 3.1.3 and have also found an issue with _ICU_.

While building mscorlib:

```
LOADLoadLibrary.1659: dlopen() failed; dlerror says
'dlopen(/[...]/coreclr/bin/obj/OSX.x64.Debug/ToolRuntime/System.Globalization.Native.dylib, 1): 
Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.55.dylib
```

Resulting in: `coreclr_initialize failed - status: 0x80131500`

```
error MSB3073: The command [...] PLATFORM_UNIX" -keepTempFiles+" exited with code 255.
```

`brew install icu4c` install 56.1 but it seems as the build expects 55.x.
`brew search icu4c` does not provide any other versions.
`brew search cmake`does not provide version 3.3.2 (3.1.3 is the latest, except from 3.4)

_ulimit_ is already documented and _MONO_THREADS_PER_CPU_ is already present in `build.sh`

**Comment by jkoritzinsky** [comment]
This issue is from 2015 and our infra has change significantly multiple times since then. Closing this issue for now since our current docs are up to date. If there's still documentation issues, I'd suggest opening a new issue since that will be more visible.
