### ISSUE TITLE
Incomplete writes on Unix

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#48479]
## Background and Motivation

Windows behavior of sockets is to have every `send` call complete once the entire buffer has been sent.

We chose to emulate this in our Unix pals, but this creates some sub-optimal behaviors in the case where send() must be called more than once.

- We may have buffered more data in the mean time, and would prefer to include that in the subsequent writes. Not having this results in excessive I/Os.
- When using `TCP_NODELAY`, this can result in using more packets than necessary -- if we do e.g. 1) initial send, 2) small packet send to emulate Windows, 3) small packet send additional buffered data. -- if the PAL instead didn't have this behavior, we might be able to merge 2 and 3 into a single packet.

I think we could probably change default behavior here, but in case we really want to maintain compat (I believe this behavior is undocumented), I'd propose an API like:

```c#
class Socket
{
    public int SendSome(ReadOnlySpan<byte> buffer, SocketFlags socketFlags = SocketFlags.None);
    public ValueTask<int> SendSomeAsync(ReadOnlyMemory<byte> buffer, SocketFlags socketFlags = SocketFlags.None, CancellationToken cancellationToken = default);
}
```

We would also want to add some new `Stream` APIs to abstract this -- tracked in #48826.

CC @antonfirsov @geoffkizer

**Comment by geoffkizer** [comment]
I don't think we could change the default behavior here; that seems like a significant breaking change.

But we could add a flag as proposed.

**Comment by karelz** [comment]
Triage: We agree that someone somewhere depends on the behavior.
- Suspicion: ASP.NET relies on this.
- 
Perf improvements expected in high-volume data sending scenarios. Ideally get some benchmark to understand the win. If significant, then figure out how to expose it (opt-in/opt-out/always-on).

**Comment by wfurt** [comment]
no real demand for it. closing for now.
