### ISSUE TITLE
Test ilproj files do not support dependencies via project.json

### ISSUE THREAD

**Issue by richardlford** [dotnet/runtime#4848]
When an il test has a dependency, there is no way to get the
required nuget package loaded as the current IL.targets
file does not support processing of project.json files.

A workaround is to add the dependency any of the JIT/config/**/project.json files. 
This will cause the required assemblies to be copied to the CORE_ROOT
directory, provided there is at least one csproj test that uses that project.json file.

**Comment by jkoritzinsky** [comment]
We don't use project.json any more, so I'm going to close this.
