### ISSUE TITLE
 Directory.GetFiles does not work using a WEBDAV-Share

### ISSUE THREAD

**Issue by rainmang** [dotnet/runtime#48484]
The following code works perfect in .Net 4.8 but not when using Net V5.0.3 or the current first preview of Net 6:
Drive letter z: represents the network drive connected to a WEBDav-Share, which works perfect for all standard Windows apps.

Please have a look at the complete code: 
```c#
using System;
using System.IO;

namespace ConsFindFilesNet_4_5_6
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine(@"App started");
            var files = Directory.GetFiles(@"z:\Root", "*.*", SearchOption.AllDirectories);
            Console.WriteLine($@"Files detected: {files.Length}");
            Console.Write(">>> ");
            Console.ReadLine();
        }
    }
}
```

**Comment by danmoseley** [comment]
@rainmang I edited your comment to format the code with triple ticks: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by danmoseley** [comment]
cc @JeremyKuhne in case he might be aware why this may have worked on .NET Framework but not in the new file enumeration code.

**Comment by rainmang** [comment]
@danmoseley Tanks a lot for your hint regarding the code formating.

**Comment by rainmang** [comment]
I have now tested the code with 3 different WEBDav Providers, same problem with all providers.

The problem also exists 
when you use "DirectoryInfo(<folder>).EnumerateFiles("*.*", SearchOption.AllDirectories) 
instead of Directory.GetFiles(<folder>, "*.*", SearchOption.AllDirectories).

In all cases you can easily use the functions in .Net 4.x and  see all files in Windows Explorer

**Comment by danmoseley** [comment]
https://github.com/dotnet/corefx/commit/66ada723c1b0ae9062a0e7b0b28862014b985019 was likely the change

If you install 2.0 from here https://dotnet.microsoft.com/download/dotnet (out of support) I'm guessing it works?

**Comment by rainmang** [comment]
Unfortunately it is not working with any version of .Net Core 2.0 ... 3.1, .Net 5.0, Net 6.0

**Comment by danmoseley** [comment]
That is interesting. Could you just double check which yo'ure running on, by adding `Console.WriteLine(Assembly.GetAssembly(typeof(string)).Location);` to your test app ? Just to be certain it's actually running on 2.0. You should see something like `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.xxx\System.Private.CoreLib.dll`

**Comment by rainmang** [comment]
I have attached a zip-file with screenshots for more details.
Short Version:
.Net Core 2.0 --> 2.1.25
.Net Core 2.1 --> 2.1.25
.Net Core 2.2 --> 2.2.8
.Net Core 3.0 --> 3.1.9
.Net Core 3.1 --> 3.1.9
.Net 5            --> 5.0.2
.Net 6            --> 6.0.0-preview.1.21102.12
.Net 4.8         --> 4.0.30319

The source code is also attached in the zip file.

Only on the screenshot of Net 4.8 you can see the number of files detected. The number is shown twice als both functions to list the files are now being used. In all other versions the app stops responding after the first call to get the files.
[Screenshots.zip](https://github.com/dotnet/runtime/files/6012946/Screenshots.zip)

**Comment by danmoseley** [comment]
Your 2.0 case is actually running on 2.1 bits. I expect if you tried 1.0 or 1.1 bits it would pass. 

Are you interested in doing some investigation with the debugger?

**Comment by rainmang** [comment]
Yes it is working using 1.0 / 1.1.
Of course I am interested in doing some inverstigations with the debugger  to help solve the problem...

**Comment by danmoseley** [comment]
Let us know what you find out. The change linked above may help you doing good places for breakpoints.
