### ISSUE TITLE
Mono crash "Opcode 'popcnt64' missing from machine description file."

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#48490]
Not sure if this happens on master.  I got it by building https://github.com/lambdageek/runtime/tree/weird-crash with `build.sh -s mono+libs -rc Debug -c Release /p:MonoMetadataUpdate=true` on OSX amd64 and then running `dotnet.sh build /p:Configuration=Release /t:Test` in the `src/libraries/System.Runtime.Loader/tests` test project.

Full stack trace https://gist.github.com/lambdageek/cf23e43f5159d6ac76f07cff20568a1c
It looks like the runtime is JITing `XoshiroImpl.Next` from https://github.com/dotnet/runtime/blob/9f193c9377f3aec90c5037c64dafe06f3615139b/src/libraries/System.Private.CoreLib/src/System/Random.Xoshiro256StarStarImpl.cs#L92

That code is relatively new (about a month old) from https://github.com/dotnet/runtime/commit/5ee25aa5fee9c08dc34c962023ec75956edd3194

So it might be exercising the PopCount intrinsic in a new way

**Comment by lambdageek** [comment]
Doesn't seem to be happening anymore after a reboot.

**Comment by SamMonoRT** [comment]
@lambdageek - Is this still an issue or can be closed ?
