### ISSUE TITLE
Method not found: 'IntPtr System.Threading.WaitHandle.get_Handle()'.

### ISSUE THREAD

**Issue by richardlford** [dotnet/runtime#4850]
Got this message:

```
Unhandled Exception: System.MissingMethodException: 
Method not found: 'IntPtr System.Threading.WaitHandle.get_Handle()'.
```

for this test on a debug win64 test job:

```
JIT\Directed\pinvoke\preemptive_cooperative\preemptive_cooperative.cmd
```

I'm not sure whether this test is portable or not. For now I'm adding the
test but excluding it.

category:correctness
theme:testing
skill-level:beginner
cost:small

**Comment by marcusturewicz** [comment]
This file doesn't seem to exist anymore so can this issue be closed?
