### ISSUE TITLE
Assertion failed 'gtOper == GT_CNS_INT' in 'System.Numerics.Tests.BitOperationsTests:BitOps_PopCount_Constant()' during 'Importation'

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#48504]
Seeing lot of `runtime-coreclr libraries-jitstressregs` failures in Linux arm and Windows x86 . It started happening between 1/21 and 1/24.

Run from 1/21: https://dev.azure.com/dnceng/public/_build/results?buildId=961156&view=results
Run from 1/24: https://dev.azure.com/dnceng/public/_build/results?buildId=963693&view=results

The only related change that went in was https://github.com/dotnet/runtime/pull/47133

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
@SingleAccretion

**Comment by SingleAccretion** [comment]
I will take a look.
