### ISSUE TITLE
tvOS: Mono runtime for device is missing bitcode

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#48508]
Trying to link with libmonosgen-2.0.dylib from the tvOS runtime pack yields:

> ld: '/Users/rolf/work/maccore/coreclr/xamarin-macios/builds/downloads/microsoft.netcore.app.runtime.tvos-arm64/6.0.0-preview.1.21102.12/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/rolf/work/maccore/coreclr/xamarin-macios/builds/downloads/microsoft.netcore.app.runtime.tvos-arm64/6.0.0-preview.1.21102.12/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib'

This is also evident in the size difference between the runtime pack and the old mono archive:

```
$ ls -la builds/downloads/microsoft.netcore.app.runtime.*/6.0.0-preview.1.21102.12/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib
-rwxr--r--  1 rolf  staff  4307416 Feb  3 03:54 builds/downloads/microsoft.netcore.app.runtime.tvos-arm64/6.0.0-preview.1.21102.12/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib

$ ls -la builds/downloads/ios-release-Darwin-5e9cb6d1c1de430965312927d5aed7fcb27bfa73/ios-libs/tvos/libmonosgen-2.0.dylib     
-rwxr-xr-x  1 rolf  staff  29800456 Feb 19 11:43 builds/downloads/ios-release-Darwin-5e9cb6d1c1de430965312927d5aed7fcb27bfa73/ios-libs/tvos/libmonosgen-2.0.dylib
```

**Comment by rolfbjarne** [comment]
CC @akoeplinger @steveisok

**Comment by akoeplinger** [comment]
@rolfbjarne is this a tvOS specific requirement? from what I can see we're doing pretty much the same on iOS/tvOS.

**Comment by rolfbjarne** [comment]
@akoeplinger yes, this is specific to tvOS, we don't need bitcode on any other platform (except for watchOS, but that's not on the roadmap right now).

**Comment by spouliot** [comment]
This is blocking us from enabling globalization (ICU) on tvOS.

see https://github.com/dotnet/runtime/issues/50912

**Comment by filipnavara** [comment]
This should do for the bitcode in the libs+mono (doesn't enable the `--with-bitcode` option as in Mono's configure, just the ios.mk build flags): https://github.com/dotnet/runtime/commit/bf954499cda2fca0502e67f21f1ad14895a4a463

Unfortunately the ICU build itself is not built with bitcode and that has to be done first.

**Comment by filipnavara** [comment]
Now that ICU build is fixed and consumed I submitted #51220 to generate bitcode for the Mono runtime and native libraries. Once/if that gets accepted and the packages are bumped on Xamarin side this needs to be removed:

https://github.com/xamarin/xamarin-macios/blob/312ab983a134cca50091873b5f936b099757d209/runtime/Makefile#L670-L672
https://github.com/xamarin/xamarin-macios/blob/312ab983a134cca50091873b5f936b099757d209/runtime/monovm-bridge.m#L205-L210
https://github.com/xamarin/xamarin-macios/blob/312ab983a134cca50091873b5f936b099757d209/runtime/monovm-bridge.m#L215

**Comment by akoeplinger** [comment]
@filipnavara do you think there's anything left for us to do here, or just follow-up on the XI side?

**Comment by filipnavara** [comment]
@akoeplinger I am honestly not sure. The MonoVM build may not work exactly like the `--with-bitcode` configure option did in classic Mono. I tried to test the end-to-end scenario to ensure that all the necessary bits are present but I stopped short of actually running the code on a device. On the reverse side the runtime may contain unnecessary bits which are never used in llvmonly mode.

**Comment by akoeplinger** [comment]
Opened https://github.com/dotnet/runtime/pull/51241, I think we can close this here and open new issues if needed.

**Comment by spouliot** [comment]
The current package points to https://github.com/dotnet/runtime/commit/3ffaab9b6f90c8f5169cf529035d209b060b1d83 which does not include "Add additional compiler flags for tvOS (#51241)"

```
l builds//downloads/microsoft.netcore.app.runtime.mono.tvos-arm64/6.0.0-preview.4.21213.3/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib
-rwxr--r--  1 poupou  staff  7108720 13 Apr 09:02 builds//downloads/microsoft.netcore.app.runtime.mono.tvos-arm64/6.0.0-preview.4.21213.3/runtimes/tvos-arm64/native/libmonosgen-2.0.dylib
```

I'll check back next week to see if we can re-enable this. Thanks!

**Comment by filipnavara** [comment]
I will double check the output but I think it should be linking against `libmonosgen-2.0.a` (static library), shouldn't it?

**Comment by filipnavara** [comment]
Version 6.0.0-preview.4.21215.1 does contain it for both .a and .dylib. The PR https://github.com/xamarin/xamarin-macios/pull/11175 should bump way beyond that.

**Comment by spouliot** [comment]
We need both `.a` and `.dylib`

The latter is important to build a framework (still todo for dotnet) so we can share the runtime between the app and the extensions (which also exists, even if less common, in tvOS).

**Comment by spouliot** [comment]
> The PR xamarin/xamarin-macios#11175 should bump way beyond that.

afaict  the dotnet/runtime specific changes ([quick script generated](https://gist.github.com/spouliot/2709ab5fe8e73f73c2f2e6a2e5a9d874)) for PR #11175 are

https://github.com/dotnet/runtime/compare/0f64b267ac0552f07b06f18103581b880c8c53c6...5d0817a2136b84580a78fea5bfbe9910098bed2b

and this does not have the tvOS changes (so I'm not too worried about my current results)

**Comment by spouliot** [comment]
The current dotnet/installer has the missing commits

https://github.com/dotnet/runtime/compare/5d0817a2136b84580a78fea5bfbe9910098bed2b...3ffaab9b6f90c8f5169cf529035d209b060b1d83

Maestro has not (yet) updated the PR but doing a local build with the following diff worked (or at least it build)
https://gist.github.com/spouliot/78aabb8c09a6127da2e5b8ee0a7a0123
