### ISSUE TITLE
[Perf -6%] Regression in System.Text.Encodings.Web.Tests.Perf_Encoders

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#48519]
### Run Information

Architecture | x86
-- | --
OS | Windows 10.0.18362
Baseline | [86835b839ca255c6c157beebda665f562e4def26](https://github.com/dotnet/runtime/commit/86835b839ca255c6c157beebda665f562e4def26)
Compare | [80b3a3f03f2a4f022b7d3a9ca35bfbc60a3bf965](https://github.com/dotnet/runtime/commit/80b3a3f03f2a4f022b7d3a9ca35bfbc60a3bf965)

### Regressions in System.Text.Encodings.Web.Tests.Perf_Encoders

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[EncodeUtf16](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows 10.0.18362/System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16(arguments%3a%20UnsafeRelaxed%2chello%20%22there%22%2c16).html>) | 82.27 ns | 86.92 ns | 1.06 | 879.8472625460963 | 917.9081902745216 | 1.043258562421715 | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-226250cbffa54b2d83/Collect%20System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16/artifacts/BenchmarkDotNet.Artifacts/System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16%28arguments_%20UnsafeRelaxed%2Chello%20_there_%2C16%29-20210216-022446.etl?sv=2019-07-07&se=2021-05-17T10%3A22%3A19Z&sr=c&sp=rl&sig=sDEz%2BEByLETqfMZbkdnb8uZj%2BJSUEPdA3hduAxCJsrE%3D) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-664a617a2470482b9a/Collect%20System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16/artifacts/BenchmarkDotNet.Artifacts/System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16%28arguments_%20UnsafeRelaxed%2Chello%20_there_%2C16%29-20210216-022329.etl?sv=2019-07-07&se=2021-05-17T10%3A22%3A20Z&sr=c&sp=rl&sig=QTBEqFifhk03tBWDUVwbDYq9GIzkh5LfvG4oD706aCM%3D)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_16_2021/refs/heads/master_x86_Windows%2010.0.18362_Regression/System.Text.Encodings.Web.Tests.Perf_Encoders_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_16_2021/refs/heads/master_x86_Windows%2010.0.18362_Regression/System.Text.Encodings.Web.Tests.Perf_Encoders.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Encodings.Web.Tests.Perf_Encoders*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-b04367f9-0a40-464c-95c3-312ec378f432f0ade693f814113b6/1e6b178e-0757-49b5-a63a-3d29d18b3644.zip?sv=2019-07-07&se=2021-03-14T15%3A10%3A05Z&sr=c&sp=rl&sig=R4QgvqxpEV9wS4Cq%2B8T73Rp%2BtLT79Ofc0RjVvuGRUKc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-dd7a6d03-bf52-42f3-a5a8-11eb264ffe17a16ce7ec13b47dcac/ecdfbc03-b5a1-4bce-aadd-55bfb5a59559.zip?sv=2019-07-07&se=2021-03-15T00%3A11%3A33Z&sr=c&sp=rl&sig=SMHuGedcO7my8Ab3OuxXAMiTZLJ1qbAwebMEH59NyQA%3D>)

#### System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16(arguments: UnsafeRelaxed,hello "there",16)

```log
[79.590 ; 81.230) | @@@@@@@@@@@@@@@@@@
[81.230 ; 84.049) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[84.049 ; 86.751) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[86.751 ; 89.664) | @@@@@@@@@@@@@@@@@@@@@
[89.664 ; 93.595) | @@@@@@@
```
### Baseline Jit Disasm

```assembly
; System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16(EncoderArguments)
       mov       ecx,edx
       cmp       [ecx],ecx
       call      System.Text.Encodings.Web.Tests.Perf_Encoders+EncoderArguments.EncodeUtf16()
       ret
; Total bytes of code 10
```
```assembly
; System.Text.Encodings.Web.Tests.Perf_Encoders+EncoderArguments.EncodeUtf16()
       push      ebp
       mov       ebp,esp
       push      edi
       push      esi
       push      ebx
       sub       esp,8
       xor       eax,eax
       mov       [ebp+0FFF0],eax
       mov       [ebp+0FFEC],eax
       mov       eax,[ecx+8]
       mov       edx,[ecx+0C]
       test      edx,edx
       jne       short M01_L00
       xor       edx,edx
       xor       esi,esi
       jmp       short M01_L01
M01_L00:
       lea       esi,[edx+8]
       mov       edx,[edx+4]
       xchg      edx,esi
M01_L01:
       mov       ecx,[ecx+10]
       test      ecx,ecx
       jne       short M01_L02
       xor       edi,edi
       xor       ebx,ebx
       jmp       short M01_L03
M01_L02:
       lea       edi,[ecx+8]
       mov       ebx,[ecx+4]
M01_L03:
       push      esi
       push      edx
       push      ebx
       push      edi
       lea       edx,[ebp+0FFEC]
       push      edx
       push      1
       lea       edx,[ebp+0FFF0]
       mov       ecx,eax
       mov       eax,[eax]
       mov       eax,[eax+2C]
       call      dword ptr [eax+10]
       lea       esp,[ebp+0FFF4]
       pop       ebx
       pop       esi
       pop       edi
       pop       ebp
       ret
; Total bytes of code 91
```

### Compare Jit Disasm

```assembly
; System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf16(EncoderArguments)
       mov       ecx,edx
       cmp       [ecx],ecx
       call      System.Text.Encodings.Web.Tests.Perf_Encoders+EncoderArguments.EncodeUtf16()
       ret
; Total bytes of code 10
```
```assembly
; System.Text.Encodings.Web.Tests.Perf_Encoders+EncoderArguments.EncodeUtf16()
       push      ebp
       mov       ebp,esp
       push      edi
       push      esi
       push      ebx
       sub       esp,8
       xor       eax,eax
       mov       [ebp+0FFF0],eax
       mov       [ebp+0FFEC],eax
       mov       eax,[ecx+8]
       mov       edx,[ecx+0C]
       test      edx,edx
       jne       short M01_L00
       xor       edx,edx
       xor       esi,esi
       jmp       short M01_L01
M01_L00:
       lea       esi,[edx+8]
       mov       edx,[edx+4]
       xchg      edx,esi
M01_L01:
       mov       ecx,[ecx+10]
       test      ecx,ecx
       jne       short M01_L02
       xor       edi,edi
       xor       ebx,ebx
       jmp       short M01_L03
M01_L02:
       lea       edi,[ecx+8]
       mov       ebx,[ecx+4]
M01_L03:
       push      esi
       push      edx
       push      ebx
       push      edi
       lea       edx,[ebp+0FFEC]
       push      edx
       push      1
       lea       edx,[ebp+0FFF0]
       mov       ecx,eax
       mov       eax,[eax]
       mov       eax,[eax+2C]
       call      dword ptr [eax+10]
       lea       esp,[ebp+0FFF4]
       pop       ebx
       pop       esi
       pop       edi
       pop       ebp
       ret
; Total bytes of code 91
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
This seems related to https://github.com/dotnet/runtime/pull/48181

**Comment by danmoseley** [comment]
@eerhardt

**Comment by danmoseley** [comment]
If this is an inevitable consequence of removing the unsafe code, maybe it's acceptable., cc @GrabYourPitchforks since it's relating to unsafe code and encoding :)

**Comment by JulieLeeMSFT** [comment]
As Dan said, it is text encoding related. I wonder if we need to change the codegen label to something else.

**Comment by GrabYourPitchforks** [comment]
Been investigating potential perf optimizations recently for this code. Self-assigning since it falls under the same umbrella.

Regardless, I think the PR that introduced this was good for a whole slew of reasons, including memory and footprint savings.

**Comment by danmoseley** [comment]
Fixed area label.
