### ISSUE TITLE
Add Mono.osx-arm64 runtime pack and produce new runtime pack

### ISSUE THREAD

**Issue by dalexsoto** [dotnet/runtime#48531]
We need a `Microsoft.NETCore.App.Runtime.Mono.osx-arm64 ` runtime pack for M1 machines. It seems that we already have one for `Microsoft.NETCore.App.Runtime.maccatalyst-arm64` so it should be a quite easy one to add.

/cc @rolfbjarne

**Comment by akoeplinger** [comment]
This is available as https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.NETCore.App.Runtime.Mono.osx-arm64&protocolType=NuGet&version=6.0.0-preview.3.21123.15 now
