### ISSUE TITLE
Validate .net 5 PRs are in C port of EventPipe

### ISSUE THREAD

**Issue by josalem** [dotnet/runtime#48538]
We've found a few discrepancies between the old C++ implementation of EventPipe and the new C implementation.  We'll create a list of missing or malformed patches here.

> currently researching, so the lists below are incomplete

Potentially missed PRs:
* #39807
* ~#37375~ (this one just isn't recorded in #36820)
* ~#38297~ (doesn't matter because the TRY_CATCH loop is gone in C port)
* #40888
* ~#40556~ (this one just isn't recorded in #36820)

CC @tommcdon @sywhang @noahfalk @lateralusX

**Comment by sywhang** [comment]
Part of the issue is that some of the PRs are ported but have errors in them. John and I'll be following up with PRs to address the discrepancies we find along the way.

**Comment by lateralusX** [comment]
Some of the DiagnosticServer PR's might not be in the list since the port was un-going meaning that changes was already included in snapshot where port started, like #39807 and #40888, but if you look in the EventPipe C library you will find the ported changes done in the above PR's.

**Comment by sywhang** [comment]
@josalem Over the weekend I went through all the changes to EventPipe and it looks like there is either a matching change or there doesn't have to be a corresponding change because it doesn't exist in the C port anymore (like the try-catch one).

**Comment by josalem** [comment]
Closing per @sywhang's comment.
