### ISSUE TITLE
Suggestion: CREATE a ". net core" world

### ISSUE THREAD

**Issue by snikeguo** [dotnet/runtime#48545]
Can you make a specification similar to Java me8 (like the previous   . net compact framework).

I think there will be someone to implement this specification.

Web:.net core
desktop:.net core
phone: mono
linux/embedded Linux:.net core /mono
embedded MCU (usually IOT device is MCU) :  .net core compact
all devices are using. net core technology, especially IOT devices, the market is very large.

https://www.oracle.com/java/technologies/javame-embedded/javame-embedded-getstarted.html
https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/0e118yae(v=vs.90)

**Comment by huoyaoyuan** [comment]
Mono mini should be sufficient for such scenario. It is size opt and used for wasm now, if I'm understanding correctly.

**Comment by danmoseley** [comment]
@jkotas this is a request for .NET for microcontrollers. Is there any existing guidance we can refer this poster to?

**Comment by KalleOlaviNiemitalo** [comment]
There used to be .NET Micro Framework but it looks dead now. Its Wikipedia page mentions [.NET nanoFramework](https://www.nanoframework.net) and [TinyCLR OS](https://docs.ghielectronics.com/software/tinyclr/intro.html) as replacements. I don't know whether either of those has a _specification_ intended for others to implement, though.

**Comment by snikeguo** [comment]
@KalleOlaviNiemitalo  .net nanoframework and TinyCLR OS is not a "specification " . The " .NET CORE COMPACT " should be a document.

**Comment by jkotas** [comment]
https://github.com/nanoframework is active project. It joined .NET Foundation recently: https://www.nanoframework.net/net-nanoframework-has-joined-the-net-foundation/.

What is the problem that you expect would be solved by having a specification for ".NET CORE COMPACT"? What is the value that it would add over nanoframework documentation?

Note that we have abandoned efforts to create specifications like .NET Standard that are independent on implementations. .NET Standard 2.0 has been useful for .NET Framework to .NET Core migration, but we do not see much value in specifications like that going forward.

**Comment by snikeguo** [comment]
@jkotas  like this:
https://jcp.org/aboutJava/communityprocess/final/jsr360/index.html
![image](https://user-images.githubusercontent.com/20830435/108632114-36f0a380-74a8-11eb-987d-f969b9dfccb4.png)
this document specifies the all APIs for CLDC devices.(and so on...)

**Comment by jkotas** [comment]
What is the problem that you expect would be solved by having a specification for ".NET CORE COMPACT"? What is the value that it would add over nanoframework documentation?

**Comment by snikeguo** [comment]
I am porting coreclr to MCU (thumb2 instruction), but coreclr is too large, so I think there should be a specification to guide us to porting the NECESSARY parts. I don't know which parts can be cropped.
I am now porting the PAL layer code to the MCU.

**Comment by jkotas** [comment]
I think you should look at what nanoframework cropped. They have done the hard work of figuring out what to keep and what to strip for microcontrollers.

Just curious - what is the microcontroller that you are targeting? CoreCLR app footprint (even once you strip what is not necessary) is going to be in 10s MB range. Is it going to fit into your microcontroller?

**Comment by snikeguo** [comment]
i know nanoframework，it has no JIT.and it doesn't use NATIVE multithread of RTOS. All C # threads run in one thread of the CLR engine.so the nanoframework is too slow and not feasible.

In China, there is a company that has transplanted Hotspot JVM to MCU. It runs in JIT mode and can also use RTOS native multithread (that is:    java code: thread t = new thread (...) = = = > JVM will create an RTOS native thread)

The chip used by this company is ： NXP： i.MX rt1052/1062/.....  ST: STM32F7/H7/F4  （These chips all support external SDRAM chip and XIP ）

**Comment by snikeguo** [comment]
But the company's code is not open source

**Comment by danmoseley** [comment]
I looked at STM32F7 (eg) and it says it supports "Up to 2 Mbytes of embedded Flash memory" and "Up to 512 Kbytes of universal data memory" .. would you require everything fit in there? Or do I misread and it's further extensible?

**Comment by snikeguo** [comment]
External SDRAM can run program. and SDRAM is very cheap (64MB about $0.8~1). 
stm32f7 has I -cache /d - cache

**Comment by snikeguo** [comment]
![image](https://user-images.githubusercontent.com/20830435/108649278-fde01f80-74f7-11eb-8adb-2d434385e76d.png)

**Comment by snikeguo** [comment]
https://www.st.com/content/ccc/resource/technical/document/application_note/group0/d8/39/10/2f/ee/c9/4b/19/DM00514974/files/DM00514974.pdf/jcr:content/translations/en.DM00514974.pdf

**Comment by joperezr** [comment]
Maybe I missed it, but I don't think you have answered @jkotas question here:

> Just curious - what is the microcontroller that you are targeting? CoreCLR app footprint (even once you strip what is not necessary) is going to be in 10s MB range. Is it going to fit into your microcontroller?

We have recently been working on linker features as well as features on the .net libraries to make the app size smaller as when deployed it will only have the things that your application will need at runtime.

**Comment by snikeguo** [comment]
@joperezr  The microcontroller I am referring to is: a microcontroller without MMU .The microcontroller I am referring to is: a microcontroller without MMU.
For example STM32F7 / RT1052
These microcontrollers can run programs in external NOR Flash or external SDRAM. 
If CoreCLR.hex wants to run in SDRAM, then BootLoader needs to move CoreCLR.hex to SDRAM. 
![image](https://user-images.githubusercontent.com/20830435/111441790-a0c83a00-8742-11eb-8734-4a4411029a64.png)
