### ISSUE TITLE
Update build and install instructions

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#4854]
There are multiples sets of instructions. They don't seem like the ones we should have as we approach RTM.

Here are the experiences that I think we should make easy:
1. Build the world! Build the runtime (CoreCLR or CoreRT), CoreFX, the language compiler (Roslyn or F#) and CLI from source. If using CoreRT, also build the native compiler (CoreRT or LLILC) from source. Ideally, this is an aggregate doc. Each repo provides good instructions on how to build and an uber document links them together with clarifying instructions where you have to do something different to "build the world".
2. Build just the runtime. Rely on NuGet for CoreFX. Using CLI should be optional. This should be documented in the CoreCLR and CoreRT repos, since the instructions will be different.
3. Build CoreFX (in part or whole.) Rely on NuGet for the runtime. Using CLI should be optional. This should be documented in the CoreFX repo.
4. Download the world! Get pre-build binaries for everything. This is the mainline CLI experience and should be documented on the CLI repo.

You should have a working dev environment. That's something that has been missing. You should be able to compile apps and run unit tests. You should be able to use VS Code as an editor.  There should be no Mono dependency or packages.config.

We now have CLI as a good driver. That's a major step forward. I am guessing that there are folks that will want an experience more low-level than CLI. We should determine if this is the case to ensure that there are instructions for their use case.

What else do we need good instructions for?

There is also a q of which documents are advertised in the root README.md:
- The DNX docs should all be removed from the Documentation directory. 
- The DNX references in the front-page README.me should be replaced with new documents.
- The "Build from source" docs should be the ones mentioned above. The "Get Binaries" links should reference docs in the CLI repo.
dotnet/coreclr#2386 satisfies some of this. I wanted to raise this issue in a wholistic way so that we can define what we all want. Just jumping over to CLI as an extension of the compiler doesn't quite seem right.

/cc @ellismg, @blackdwarf, @kangaroo

**Comment by jkoritzinsky** [comment]
@richlander it looks like this issue is from back in the DNX days. Should we keep this issue open?
