### ISSUE TITLE
Crash dump file incomplete call stack in asynchronous code

### ISSUE THREAD

**Issue by TristanPct** [dotnet/runtime#48572]
### Description

I have built and publish a console app using .NET 5 and I try to debug it using the crash dump file generated on a user computer (Windows).

Loading the dump file in Visual Studio I'm not able to have the complete call stack if the exception is thrown in a async method.

### Configuration

- .NET 5
- Windows 10 x64

### Reproduction

I made a [simple repo](https://github.com/TristanPct/NetCoreDumpDemo) with 2 console apps (sync and async) to reproduce this issue.

1. Enable full crash dump with RegEdit:
	1. Go to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`
	2. Add a new `32 bits DWORD` value named `DumpType`
	3. Set `DumpType` value to `2` (Full dump)
1. Run `.\publish.cmd` to build *AsyncConsoleApp* and *SyncConsoleApp* in release mode with debug info (targeting win-x64)
1. Run `.\SyncConsoleApp\bin\Release\net5.0\publish\SyncConsoleApp.exe`
1. Run `.\AsyncConsoleApp\bin\Release\net5.0\publish\AsyncConsoleApp.exe`
1. Dump files are generated in `%localappdata%\CrashDumps`
1. Open dump files with Visual Studio 2019 and run *Debug with Managed Only*

With *SyncConsoleApp* you will see the full call trace, the C# source code and the exception in `SyncConsoleApp\Program.cs`.

With *AsyncConsoleApp* you will see a partial call stack, and trying to access `AsyncConsoleApp!AsyncConsoleApp.Program.<Main>(string[] args)` stack frame will give you a `Source Not Available` error.  
The final exception will be in `System.Private.CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() Line 56`

### Questions

Is it a known behavior?

Did I misconfigured my project or my debugger?

**Comment by hoyosjs** [comment]
I'll try to take a look at this next week.

**Comment by hoyosjs** [comment]
Although, reading through the repro, do you mean you don't see `InnerMethod` in your callstack? That'd be the correct behavior. the `Main` method awaits on the Task that got kicked off in the threadpool, and then the stack gets stitched so that it looks like `InnerInnerMethod` -> `Main`. At that point the exception is observed by the code that results from doing await on `Main`, the `InnerMethod` is gone.

**Comment by TristanPct** [comment]
When I launch `AsyncConsoleApp`, the crash callstack in the console is:
```
Unhandled exception. System.Exception: Async test exception
   at AsyncConsoleApp.Program.InnerInnerMethod()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AsyncConsoleApp.Program.Main(String[] args)
   at AsyncConsoleApp.Program.<Main>(String[] args)
```

I have the starting point (`Main`) and the faulty method (`InnerInnerMethod`), but yes, `InnerMethod` call is "lost".

But when I open the generated `.dmp` file, the callstack is:

```
 	[Managed to Native Transition]	
>	System.Private.CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() Line 56	C#
 	System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) Line 173	C#
 	System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) Line 150	C#
 	System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.GetResult() Line 105	C#
 	[Waiting on Async Operation, double-click or press enter to view Async Call Stacks]	
 	AsyncConsoleApp!AsyncConsoleApp.Program.<Main>(string[] args)	Unknown
```

I only have the starting method (`Main` with missing info) and no info about the faulty method.

**Comment by hoyosjs** [comment]
This is also expected. So in VS (and SOS and dotnet-dump) you'll see this when you request the stack:
```
> clrstack
OS Thread Id: 0xef0 (2)
        Child SP               IP Call Site
0000008A9BF7E808 00007ffc0c72c6a4 [HelperMethodFrame: 0000008a9bf7e808]
0000008A9BF7E900 00007FFB7D9371D1 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
0000008A9BF7E930 00007FFB7D96C565 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
0000008A9BF7E970 00007FFB7D96C4A7 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
0000008A9BF7E9A0 00007FFB7D96C42C System.Runtime.CompilerServices.TaskAwaiter.GetResult()
0000008A9BF7E9D0 00007FFB2DB561F8 AsyncConsoleApp.Program.<Main>(System.String[])
```

If I do `!pe` in SOS or dotnet-dump, or type `$exception` in the immediate window of VS you'll see: 
```
> pe
Exception object: 000001fac1d4d480
Exception type:   System.Exception
Message:          Async test exception
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    0000008A9C9FF1D0 00007FFB2DB590B4 AsyncThrowBug!AsyncConsoleApp.Program.InnerInnerMethod()+0x64
    0000008A9C9FF210 00007FFB7D8FA09E System.Private.CoreLib!System.Threading.Tasks.Task.InnerInvoke()+0x1e
    0000008A9C9FF240 00007FFB7D8FFC01 System.Private.CoreLib!System.Threading.Tasks.Task+<>c.<.cctor>b__277_0(System.Object)+0x11
    0000008A9C9FF270 00007FFB7D8E5462 System.Private.CoreLib!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x42
    0000008A9C9FF240 00007FFB7D9371D1 System.Private.CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x21
    0000008A9C9FF270 00007FFB7D8E549F System.Private.CoreLib!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x7f
    0000008A9C9FF2C0 00007FFB7D8F9EDB System.Private.CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)+0x1cb
    0000008A9C9FEDC0 00007FFB7D9371D1 System.Private.CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x21
    0000008A9C9FEDF0 00007FFB7D96C565 System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0xb5
    0000008A9C9FEE30 00007FFB7D96C4A7 System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x47
    0000008A9C9FEE60 00007FFB7D96C42C System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.GetResult()+0x1c
    0000008A9C9FEE90 00007FFB2DB5727A AsyncThrowBug!AsyncConsoleApp.Program+<Main>d__0.MoveNext()+0x10a
    0000008A9BF7E900 00007FFB7D9371D1 System.Private.CoreLib!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()+0x21
    0000008A9BF7E930 00007FFB7D96C565 System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)+0xb5
    0000008A9BF7E970 00007FFB7D96C4A7 System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)+0x47
    0000008A9BF7E9A0 00007FFB7D96C42C System.Private.CoreLib!System.Runtime.CompilerServices.TaskAwaiter.GetResult()+0x1c
    0000008A9BF7E9D0 00007FFB2DB561F8 AsyncThrowBug!AsyncConsoleApp.Program.<Main>(System.String[])+0x58
```

When you add the call that InnerMethod through await from Main, it will synchronously execute that method until something blocks or yields or returns. In this case, `Task.Run` will return a task representing the execution of a work item that gets queued into the ThreadPool - InnerInnerMethod here - on a separate thread. Then you get that task in main task in Main, and the `await` operator (Or rather, the code the Roslyn compiler generates for it) most likely it will see that it's completed, get the result there using [`GetResult`](https://source.dot.net/#System.Private.CoreLib/TaskAwaiter.cs,102). From there you can see how it unwraps the stored exception and throws it again. The problem is this is happening in a completely different thread, so you'll see the stack where the exception gets unwrapped. To see the internal exception you'd need to look at the exception object that is rethrown. The stack from where it was thrown can't be reproduced to have the usual debugging experience. Likely that thread is already doing other work and all the context there has been lost.
