### ISSUE TITLE
[crossgen2] Lazy string optimization

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#48580]
crossgen1 avoided emitting string fixups for strings used on exception throwing paths. crossgen2 is missing this optimization. 

Note that this optimization produces a bit larger code, but saves time during startup by avoid string constant allocations.

See https://github.com/dotnet/runtime/pull/47183 for more context.

**Comment by davidwrighton** [comment]
This feature was cut from 6.0.0 due to lack of evidence on improvements to startup/working set. We should perform the analysis of the value of this optimization in 7.0

**Comment by davidwrighton** [comment]
This year I spent significant time investigating startup performance, and the impact of realizing string literals was never even visible in the startup measurements at all. I'm going to close this as not interesting to invest in, especially given the data that adding them will increase file size.
