### ISSUE TITLE
Convert.FromBase64String has error

### ISSUE THREAD

**Issue by gwhzh21** [dotnet/runtime#48581]
The following code does not throw in .NET Core 3.1 and .NET Core 5 :
 var s = "DyOR8sx8HltO35Paz61IjpegVVKm+gyx8x4vQteVfG5HgFxgYAYj/AFfshKbORfF+gXLsX4qw9iYO=";
            Convert.FromBase64String(s);

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

 var s = "DyOR8sx8HltO35Paz61IjpegVVKm+gyx8x4vQteVfG5HgFxgYAYj/AFfshKbORfF+gXLsX4qw9iY";
            Convert.FromBase64String(s);
ok

client post image use base64,sometime throw error,

how to fix.

**Comment by stephentoub** [comment]
> The following code does not throw in .NET Core 3.1 and .NET Core 5

It does throw, on .NET Core 3.1 and .NET 5 and .NET Framework 4.8:
```
> dotnet run -c Release -f net48

Unhandled Exception: System.FormatException: Invalid length for a Base-64 char array or string.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at tmpapp.Program.Main(String[] args)

> dotnet run -c Release -f net5.0
Unhandled exception. System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at tmpapp.Program.Main(String[] args)

> dotnet run -c Release -f netcoreapp3.1
Unhandled exception. System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at tmpapp.Program.Main(String[] args)
```

It's not valid Base64 data.

Can you elaborate on the concern?

**Comment by gwhzh21** [comment]
Customers upload pictures based on base64 format.
Convert.FromBase64String(inputimagestring);

 ,throw The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

Progressive decoding.
per line length  = 76
but one line is 77
like this
"DyOR8sx8HltO35Paz61IjpegVVKm+gyx8x4vQteVfG5HgFxgYAYj/AFfshKbORfF+gXLsX4qw9iYO"
then 

Remove the ending O character

"DyOR8sx8HltO35Paz61IjpegVVKm+gyx8x4vQteVfG5HgFxgYAYj/AFfshKbORfF+gXLsX4qw9iY"
Convert.FromBase64String(inputimagestring); is ok.

but Padding=character

"DyOR8sx8HltO35Paz61IjpegVVKm+gyx8x4vQteVfG5HgFxgYAYj/AFfshKbORfF+gXLsX4qw9iYO="

Convert.FromBase64String(inputimagestring); 

throw The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

how can fix it?

**Comment by stephentoub** [comment]
> how can fix it?

FromBase64String will throw an exception if it's provided with invalid Base64 data... that's why it's throwing.

You can see the same thing in a site like https://www.base64code.com/, where it reports failure in the same cases Convert.FromBase64String is throwing.

You'd fix it by ensuring you're giving it legal Base64 data.

**Comment by gwhzh21** [comment]
i
I understand, because my image data is in base64 format, it should be processed separately. Can not be used directly
Convert.FromBase64String()
