### ISSUE TITLE
Feature request: A way to point CoreCLR to a custom CoreLib

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#48587]
My understanding from reading `AssemblyBinder::BindToSystem` and doing some trivial testing is that the only practical way to get CoreCLR to use a custom `System.Private.CoreLib.dll` today is to publish an app in single-file mode. In all other build modes, modifying the .NET installation seems to be necessary.

In an ideal world, I'd love it if CoreCLR would try to load CoreLib from the application directory before trying the system directory. But since that would probably break something, somewhere, a good enough alternative would be a configuration knob along the lines of:

```
$ COMPlus_CoreLibPath=./System.Private.CoreLib.dll dotnet app.dll
```

(My use case is one where multiple child processes started from a parent process should use a stripped down CoreLib/BCL with a relatively tiny/altered API surface. CoreCLR's method of loading CoreLib is the only obstacle I haven't been able to get past thus far.)

**Comment by jkotas** [comment]
This would be a very fragile configuration switch. coreclr.dll/.so and System.Private.CoreLib are tightly coupled, and mismatch between the two often results in very hard to diagnose crashes.

How are you going to guarantee that your custom CoreLib stays in sync with coreclr e.g. in the presence of security servicing updates of the shared runtime?

**Comment by alexrp** [comment]
It would of course be my responsibility to keep my custom CoreLib in sync with the runtime being used. I would certainly tie my project to an exact LTS runtime version (i.e. `<RollForward>disable</RollForward>`) so that users don't end up trying to run it with a runtime it's not compatible with. I could then fairly easily adjust my CoreLib each time I switch to a newer runtime version.

I definitely agree that it's a fragile option. I don't imagine the average user is ever going to want to use this, and making the feature in some way harder/more deliberate to access would be fine with me also, so long as it doesn't require compiling and distributing my own runtime. Fundamentally, all I really need is to be able to tell a child process which CoreLib to load; it doesn't really matter if I have to do some weird combination of setting several environment variables and passing command line options just to say "yes, I really do know what I'm doing".

By the way, in my particular use case, I have very tight control over what the child processes can do, so it's fairly easy to tell if they exit due to a native crash, unhandled exception, or normally. If it's a native crash, I can explicitly tell the user to file a bug against my project first, rather than going to dotnet/runtime.

**Comment by jkotas** [comment]
I think you should have your own copy of the whole runtime to do this instead of trying to mix and match. You can set `DOTNET_ROOT` environment variable to allow your copy of the runtime to be discovered.

**Comment by alexrp** [comment]
I thought a bit about how that might work and arrived at the following:

For each `$rid` I care about:

1. Download the exact needed version of `Microsoft.NETCore.App.Runtime.$(rid)` as part of my build.
2. Zip up `runtimes/$(rid)/native/*` as `$(rid).zip`.
3. Add my custom `System.Private.CoreLib.dll` to `$(rid).zip`.
4. Embed `$(rid).zip` as a resource in my application.
    * For RID-specific releases (distributed on GItHub), only embed the specific `$(rid).zip` needed.
    * For the `PackAsTool` case, embed every `$(rid).zip` that might be needed.

Then, when running my application, I read and extract the embedded `$(actual_runtime_rid).zip` somewhere sensible on the user's machine and use that minimal runtime to run the child processes.

This all seems fairly workable, except for one issue: I think I would still need the `dotnet` command to actually execute a child process with the minimal bundled runtime (`dotnet path/to/child.dll` with the minimal runtime sitting next to `child.dll`). This is fine for the `PackAsTool` case, but not so much for the RID-specific release case as I can't be sure the user will have a full .NET SDK (containing the `dotnet` CLI) installed.

My understanding is that I could solve this by embedding `dotnet` and `host/fxr/$version/*` along with the minimal runtime for each RID, but I'm not sure how I would obtain it. Perhaps I would have to instead download the full SDK during my build and extract it from there? Or is there some way to avoid the need for `dotnet` altogether?

Any thoughts on all of this?

**Comment by SingleAccretion** [comment]
One option you could consider is using `corerun` as the host instead of `dotnet`.

**Comment by alexrp** [comment]
`corerun` seems ideal indeed, but there's still the problem of actually obtaining binaries of it for every RID I care about. Seems like I would have to cross-compile multiple versions of it from source which would be quite an undertaking whenever I upgrade from one .NET version to another. At that point, grabbing `dotnet` out of official SDK archives would probably be easier...

**Comment by SingleAccretion** [comment]
I know that `corerun` is produced as part of the CI builds that run on every PR, but not much beyond that.

**Comment by jkotas** [comment]
`corerun` is non-shipping host, only used for testing and as a sample.

**Comment by alexrp** [comment]
After a bit more investigation, it seems like the most reasonable thing to do at build time is to download the runtime packages that e.g. `dotnet-install --dry-run --runtime dotnet -v $(version) --runtime-id $(rid)` would. Those contain CoreCLR and the `dotnet` CLI. They still contain some 'bloat' in the form of the BCL (that I can just filter out when extracting) but it's still a big improvement over having to download the full SDK for each RID.

**Comment by alexrp** [comment]
I'm going to prototype the approach described above. I'm fairly confident it'll work, so I'll go ahead and close this for now. Thanks for the suggestions.
