### ISSUE TITLE
```ImmutableList<T>.GetRange``` should accept a ```Range```

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#48592]
## Background and Motivation
It would be nice to be able to use range syntax with ```ImmutableList<T>```

## Usage Examples
```
MyImmutableList.GetRange(1..^1);
MyImmutableList[1..^1];
```

## Risks
None

**Comment by eiriktsarpalis** [comment]
Related to #321.

**Comment by eiriktsarpalis** [comment]
In the interest of improving the chances of this feature being considered in the future, would it be possible to update the OP so that the [API proposal](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md#steps) template is followed?
