### ISSUE TITLE
HostWriter fails to copy version resource on non-Windows platforms

### ISSUE THREAD

**Issue by szilvaa** [dotnet/runtime#486]
I'm building a Win64 executable on Linux. It works very well except that the resulting executable has no version info. It tracked this down to HostWriter class in this repo. In particular [this line](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs#L79). The code only copies resource on Windows.
Steps to repro:
1. Create .net core console app targeting Win64.
2. Make sure that your project file has `<Version>` attribute.
2. Build the app on Linux.
Expected result: the resulting exe has version resource. (In fact it does have this when you build on Windows)
Actual result: no version resource in the resulting exe.

**Comment by vitek-karas** [comment]
This currently a known limitation.
@sbomer - do we have a master issue tracking this? (or should we use this one).

**Comment by sbomer** [comment]
@vitek-karas Let's use this to track it.

With the current resource updater, I think we should at least be outputting a warning in this case. It looks like https://github.com/dotnet/sdk/pull/3447/files#diff-0a0bced361e8a4b1eeaaa2c34a320a68R47 restricted the apphost customization warning to GUI apps. @wli3 was there a particular reason for this, and do you think it's worth logging a warning for console apps too?

**Comment by swaroop-sridhar** [comment]
This problem will be fixed once https://github.com/dotnet/runtime/issues/3828 is completed.

**Comment by swaroop-sridhar** [comment]
Dup of #3828
