### ISSUE TITLE
`Int.Parse("3.00")` throws an error

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#48604]
I introduced this inadvertently in https://github.com/dotnet/runtime/pull/47666/.

47666 also broke round-tripping of decimal->string. 

The bug occurs because of this line:

number.DigitsCount = digEnd - numberOfTrailingZeros;
digEnd is 1 and numberOfTrailingZeros = 2, so we end up with -1. The correct value here should be number.DigitsCount = 1. I'll consider a careful fix for this locally and put a PR up.

Currently, this bug only affects Int.Parse calls with an input that has trailing zeros => 1.0, 1.00, 1.000, 1.0000 etc are broken

**Comment by stephentoub** [comment]
`int.Parse("3.00")` is supposed to throw an exception.  Can you elaborate on the bug?

**Comment by tannergooding** [comment]
> int.Parse("3.00") is supposed to throw an exception. Can you elaborate on the bug?

It's specifically `int.Parse("3.00", NumberStyles.Number)` which has worked going back to .NET Framework 2.0 (at least)

**Comment by stephentoub** [comment]
> NumberStyles.Number

Ah, ok.

**Comment by pgovind** [comment]
> Can you elaborate on the bug?

Ah sorry, I should've been more clear. 

`int i = Int32.Parse("3.00", NumberStyles.Number, CultureInfo.InvariantCulture);` throws an exception on the current bits (but works on .NET 5, so this is a regression). Interestingly,

``` csharp
bool foo = int.TryParse("3.00".AsSpan(0, "3.00".Length), out int result);
Console.WriteLine($"foo = {foo}, result = {result}");
```
returns `foo = false`.

**Comment by tannergooding** [comment]
> Interestingly

This is because `int.Parse` defaults to `NumberStyles.Integer` which prohibits things like a decimal point.
