### ISSUE TITLE
Global block list details

### ISSUE THREAD

**Issue by arekam** [dotnet/runtime#48616]
Hi, 

where can I find global block list details for each .Net version? I understand that list changes from version to version. Particular problem I have is the serialization of the Base64 strings. By default the plus `+` sign is being escaped with the `\u002B`. Adding [UnicodeRanges.BasicLatin](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)) to allowed ranges does not help. The only way I can get `+` not escaped is by using `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` which is not the safe way as explained in documentation.

Thanks,
Arek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfcc376-0c18-5aab-f6b8-b2c6ef282acc
* Version Independent ID: 79bcd93d-81f8-5f02-3958-d364606265cd
* Content: [How to customize character encoding with System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-character-encoding#feedback)
* Content Source: [docs/standard/serialization/system-text-json-character-encoding.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-character-encoding.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by GrabYourPitchforks** [comment]
@arekam By "serialization of base64 strings", do you mean through _System.Text.Json_? I think as an optimization _System.Text.Json_ will bypass the default encoders when it's serializing a byte array as base64, but @layomia would be able to drill into this more.

**Comment by arekam** [comment]
@GrabYourPitchforks Yes, I'm using the _System.Text.Json_. And you're right -  the byte array serialization skips encoders, so  passing  _JsonSerializerOptions_ is not needed. 

Example:
```
byte[] file_bytes = File.ReadAllBytes(binaryfile_path);
string file_string_base64 = Convert.ToBase64String(file_bytes);

var jsonSerializerOptions = new JsonSerializerOptions
{
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
};

//Works as expected 
var tmp = JsonSerializer.Serialize(file_bytes); 

// Replaces + with \u002B
tmp = JsonSerializer.Serialize(file_string_base64); 

// Keeps + 
tmp = JsonSerializer.Serialize(file_string_base64, jsonSerializerOptions);
```
