### ISSUE TITLE
ConvertToStrongType methods for converting System.Array to Array of Specific Type

### ISSUE THREAD

**Issue by Jimmy-Hu** [dotnet/runtime#48635]
## Background and Motivation

The element type of `System.Array` is weakly typed. The purpose of `ConvertToStrongType` methods are to convert `System.Array` object into array of specific type (such as `int[]`).

## Proposed API

The experimental implementation of the proposed API is as below.

```diff
namespace System
{
    public abstract class Array : ICollection, IEnumerable, IList, IStructuralComparable, IStructuralEquatable, ICloneable
    {
+       public static T[] ConvertToStrongType<T>(Array input)
+       {
+           Type elementType = input.GetType().GetElementType();
+           if (input.Rank != 1)
+           {
+               throw new System.InvalidOperationException("Only one-dimensional array allowed");
+           }
+       
+           if (!elementType.Equals(typeof(T)))
+           {
+               throw new System.InvalidOperationException("Wrong type");
+           }
+       
+           var output = new T[input.GetLength(0)];
+           for (int i = 0; i < input.GetLength(0); i++)
+           {
+               output[i] = (T)input.GetValue(i);
+           }
+           return output;
+       }
    }
}
```

## Usage Examples

```C#
//    One Dimensional Array with int element convert to int[]
var array1 = Array.CreateInstance(typeof(int), 10);
for (int i = 0; i < array1.Length; i++)
{
    array1.SetValue(3, i);
}

var intArray1 = Array.ConvertToStrongType<int>(array1);
for (int i = 0; i < intArray1.Length; i++)
{
    Console.WriteLine(intArray1[i]);
}

//    One Dimensional Array with double element convert to double[]
var array2 = Array.CreateInstance(typeof(double), 10);
for (int i = 0; i < array2.Length; i++)
{
    array2.SetValue(3.1, i);
}

var doubleArray1 = Array.ConvertToStrongType<double>(array2);
for (int i = 0; i < doubleArray1.Length; i++)
{
    Console.WriteLine(doubleArray1[i]);
}
```

The expected outout of the above example:

```
3
3
3
3
3
3
3
3
3
3
3.1
3.1
3.1
3.1
3.1
3.1
3.1
3.1
3.1
3.1
```

## Reference

- [ArrayDowncasters Implementation for Downcasting from System.Array to Array of Specific Type in C#](https://codereview.stackexchange.com/q/256221/231235)

- [Declaring an array type](https://stackoverflow.com/q/14980393/6667035)

**Comment by Jimmy-Hu** [comment]
> 
> 
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

I think that the area is area-System.Runtime.

**Comment by jkotas** [comment]
Converting System.Array into array of specific type is typically done using cast operator. 

```
Array weaklyTyped = ...;
int[] stronglyTyped = (int[])weaklyTyped;
```

Why is that no enough?

**Comment by Jimmy-Hu** [comment]
@jkotas Thank you for the comments. I see. Cast operator can also work and the effect is the same as the proposed method. I originally thought that `System.Array` may perform cast method to do this thing, but I didn't find that.

**Comment by jkotas** [comment]
Is this fine to close this API proposal then since it is redundant?

**Comment by Jimmy-Hu** [comment]
Yes, happy to close.
