### ISSUE TITLE
dotnet run --project fails for .NET Core apps while in different working directory

### ISSUE THREAD

**Issue by luckerby** [dotnet/runtime#48645]
I'm trying to run a .NET Core project (target framework= `netcoreapp3.1`) from a different working directory than where the .csproj file is located. However this results in the error below:
```
C:\Users\mihai.albert>dotnet run --project c:\Users\mihai.albert\Desktop\MyProject\MyProject.csproj
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\mihai.albert\appsettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MyProject.Program.Main() in c:\Users\mihai.albert\Desktop\MyProject\Program.cs:line 12
   at MyProject.Program.<Main>()
```

Changing the working directory to the folder where the .csproj file is located, and running `dotnet run` results in the app starting successfully.

This only seems to affect .NET Core projects, not ASP.NET Core ones, which leads me to believe it's not by design.

I've encountered the issue with both the 3.11 and the 3.12 runtime.

Host machine details below:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by maryamariyan** [comment]
@luckerby could you please share a minimal repro code as well?

**Comment by luckerby** [comment]
@maryamariyan One simple Console project can be used, and inside the `Main` method just add `Console.WriteLine(Directory.GetCurrentDirectory())`. When running using `dotnet run --project <path_to_.csproj>`, it seems that the working directory isn't changed to the output folder (e.g. `\bin\Debug\netcoreapp31` for a Debug configuration). The application run as such will have its working directory set to the local path from there the `dotnet run --project <path_to_.csproj>` was ran.
So if the code inside that project happens to need access to a file that's stored within the output folder, and tries to get to it using `Directory.GetCurrentDirectory()` it will fail.

After closer inspection at the code that generated the exception from the stack trace in my initial post, it turns out an `appsettings.json` was referenced, which was copied to the output folder as instructed in the .csproj file:
```
	<ItemGroup>
		<EmbeddedResource Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
	</ItemGroup>
```
The code in that project tries to open the `appsettings.json` file by looking for it in the current directory, which will obviously fail when running the `dotnet run --project` command from anywhere else than the output folder, as described above.
This behavior is opposed from what Visual Studio does when starting the project, namely changing the working dir to the output folder. Here is the difference between starting a sample console app using "dotnet run --project" from a different directory (left) and using Visual Studio to start the app (right):

![image](https://user-images.githubusercontent.com/31319583/112736498-e0b9c900-8f5b-11eb-9b62-2380946bb716.png)

**Comment by maryamariyan** [comment]
@luckerby so based on this explanation, the FileNotFoundException is getting thrown as expected since `Directory.GetCurrentDirectory()` is not returning the same thing in the two different cases you described right?

So is the issue more about the behavior of `Directory.GetCurrentDirectory()` when running `dotnet run --project`?

**Comment by luckerby** [comment]
@maryamariyan I would say the problem is that the current directory of the process itself is not set to the path supplied when running `dotnet run --project`, as opposed to what Visual Studio does. This is captured in the last image in my previous post. `Directory.GetCurrentDirectory` simply returns the current directory as "seen" by the process itself.

I'm not sure if this is by design, or merely something that needs to be corrected by the .NET team. For my problem, there's a [simple workaround](https://stackoverflow.com/a/15653938/5853218) that involves going after the location of the assembly itself. But I imagine there are scenarios where this wouldn't work that nice.

**Comment by eerhardt** [comment]
> I would say the problem is that the current directory of the process itself is not set to the path supplied when running dotnet run --project, as opposed to what Visual Studio does.

This is by design. See the discussion in this issue for why `dotnet run` behaves this way:

https://github.com/dotnet/sdk/issues/7011#issuecomment-256531057

You can opt in to the behavior you want in your project by setting:

```xml
  <PropertyGroup>
    <RunWorkingDirectory>$(OutDir)</RunWorkingDirectory>
  </PropertyGroup>
```
