### ISSUE TITLE
Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48658]
https://dev.azure.com/dnceng/public/_build/results?buildId=1007936&view=ms.vss-test-web.build-test-results-tab&runId=31443624&paneView=debug

Configuration: `net6.0-Linux-Debug-x64-CoreCLR_checked-Ubuntu.1804.Amd64.Open`

```
Assert.Equal() Failure\nExpected: 3\nActual:   0
   at Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe() in /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs:line 652
```

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr libraries-jitstress 20210406.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1073847&view=ms.vss-test-web.build-test-results-tab&runId=32969484&resultId=102824&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
 -Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe
```

**Error message:**
```
Assert.Equal() Failure
Expected: 14
Actual:   17


Stack trace
   at Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe() in /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs:line 652
```

**Comment by radical** [comment]
This looks similar too:
```
    Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe [FAIL]
      Assert.Equal() Failure
      Expected: 7
      Actual:   0
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs(652,0): at Microsoft.Extensions.Caching.Memory.MemoryCacheSetAndRemoveTests.AddAndReplaceEntries_AreThreadSafe()
```

Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-d71a076ddbd148d08f/Microsoft.Extensions.Caching.Memory.Tests/console.5fe33e96.log?sv=2019-07-07&se=2021-05-11T04%3A25%3A06Z&sr=c&sp=rl&sig=5P3jI3UjXYHK2W0za5T%2BLQdxg65ZrjbzbDcD5npOmhs%3D

https://dev.azure.com/dnceng/public/_build/results?buildId=1099089&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/50270
