### ISSUE TITLE
[Big Sur] open() vs SA_RESTART

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#48663]
It [appears](https://news.ycombinator.com/item?id=25967594) that on MacOS Big Sur, `open` can sometimes return `EINTR` if it is interrupted by a signal even if the signal has a handler installed with `SA_RESTART`.

* MonoVM thread suspend/resume sometimes (when using posix instead of Mach) will use suspend/resume signals with the `SA_RESTART` flags. (although this is not the default - we prefer to use Mach suspend/resume operations)
* The System.Native PAL installs some signal handlers with `SA_RESTART`

We should make sure that all our calls to `open` handle `EINTR`.

---

To be clear, I haven't seen this cause a problem for .NET that can be clearly attributed to this issue.  Until we catch it in a repro, this is just a placeholder issue - unless we want to be proactive about mitigating.

---

(This is affecting other software too.  `git`, for example.  It has affected some runtime engineers - `git clone --progress https://github.com/dotnet/runtime` will sometimes fail with `interrupted system call` errors and leave the working tree in an unusable state.  The workaround is to call `git clone --quiet`  (note that `--progress` is the default))

---

The issue seems to be exacerbated by some antivirus software, even if "real time protection" is turned off.

**Comment by akoeplinger** [comment]
Maybe related to https://github.com/dotnet/runtime/issues/47584 ?

**Comment by lewing** [comment]
Here is the workaround going into git https://lore.kernel.org/git/YDXZY8XFRayiM1If@coredump.intra.peff.net/

**Comment by akoeplinger** [comment]
Nice. I wonder if we should at least file a radar with Apple?

**Comment by mangod9** [comment]
Hi @lambdageek, is this a mono specific tracking issue?

**Comment by lambdageek** [comment]
@mangod9 No.  It's a potential issue for CoreCLR, Mono and the System.Native librareis interop code.  All calls to `open` in dotnet/runtime should be audited.

**Comment by janvorli** [comment]
I think it would not hurt to wrap all calls to open in a loop checking for EINTR. I'll make a PR for the non-mono parts.
