### ISSUE TITLE
List<T>.Reverse calls non-generic Array.Reverse leading to boxing of value types.

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#48682]
https://github.com/dotnet/runtime/issues/23456 was erroneously closed, the code in List<T>.Reverse was never updated and continues to call the non-generic version of Array.Reverse. 

https://github.com/dotnet/runtime/blob/998126cf1284274c2b7d85107a7f7742737c7a65/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L992

**Comment by stephentoub** [comment]
That line is calling the generic overload:
```C#
public static void Reverse<T>(T[] array, int index, int length)
```
Why do you think it's calling the non-generic?

**Comment by geeknoid** [comment]
You're fast! I was just coming back to close this since I realize the right thing is happening.
