### ISSUE TITLE
A finalizer is run for an object that was not constructed and should not have been allocated

### ISSUE THREAD

**Issue by rationull** [dotnet/runtime#4871]
I'm logging this here because it seems most likely to be a bug in JIT compilation or optimization. If you conclude that this should instead be posted against a component in Microsoft Connect then please comment as such and I will resubmit there.

I have a C++/CLI function that contains a function call followed by an object allocation (an instance of a class implemented in C# in a separate assembly). In some cases, the function call is (by design) interrupted by an exception, which should preempt the object allocation. (Exception thrown out of BuildContent() in the provided code, such that the ViewerWindow instance should not be allocated).

When I run a Release build without a debugger attached, and execute this case, then when garbage collection runs a ViewerWindow finalizer runs despite the fact that no ViewerWindow should have been created, and no ViewerWindow constructor has run. I can verify that that the finalizer ran and the constructor did not via trace output in the finalizer and constructor. Running attached to the debugger (or running a Debug build) does not exhibit this behavior.

If I attach a debugger after the exception is thrown, I can obtain an assembly dump of the affected function in the state that produces the extra finalizer call. Note that the disassembly visibly differs based on whether the debugger was attached at process launch or whether I attached the debugger after the exception that should interrupt the function.

Unfortunately I have not yet been able to construct a minimal repro project, and I cannot provide full context from my repro case since it's part of a large proprietary application. However, I have created some sanitized dumps of the affected function in various states of compilation, and stored them in a github repo: https://github.com/rationull/JITFinalizerProblem

Hopefully this can provide enough of a clue as to what might be going on. The repo includes dumps of the original code, generated MSIL code from a Release build, and disassemblies from the debugger for both the repro and no-repro cases. See README.md in that repo for details.

Please let me know if there's any other information I can glean from my own repro that will help in the absence of a shareable project.

category:correctness
theme:importer
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment]
@AndyAyersMS What should we do with this bug? Should it get a .NET Core 5 milestone, for example?

**Comment by AndyAyersMS** [comment]
Nobody's ever found a fix that did not have outsized code size impact for what is a very rare case.

Worth another look, I suppose.

**Comment by AndyAyersMS** [comment]
Since this has been the behavior for effectively forever, seems hard to make a case that we must fix it now. Am going to take another run at it once we're past .NET 5, though.

**Comment by AndyAyersMS** [comment]
> Nobody's ever found a fix that did not have outsized code size impact for what is a very rare case.
> Since this has been the behavior for effectively forever, seems hard to make a case that we must fix it now.

Nothing has really changed. While this behavior is surprising it has not lead any actual user inconvenience that I'm aware of.

However, I said I'd take another look after .Net 5, so I suppose that's what I'll do....

**Comment by pharring** [comment]
^^ there was some user inconvenience for me: The I time spent tracking down bizarre behavior in a component of mine, convincing myself that the only explanation was a compiler bug, distilling a repro case and writing it up here. Then I had to come up with a workaround for the original codebase. In my case, the class with the finalizer was holding a native resource (a process snapshot) so it was imperative to get construction, disposal and finalization correct. The workaround, of course, had to be copiously commented lest someone later decided it was unnecessary.

**Comment by AndyAyersMS** [comment]
@pharring maybe you can send me more details (offline, if needs be)? This problem should only arise for objects that were default initialized (as the constructor never gets called) -- so it seems odd that such an instance could actually be holding a native resource.

**Comment by AndyAyersMS** [comment]
Hmm, I may have actually found a viable fix... will perhaps put up a PR tomorrow after doing a bit more analysis on its impact.
