### ISSUE TITLE
Support Asyncify for Blazor scenarios

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#48713]
[Asyncify](https://emscripten.org/docs/porting/asyncify.html) permits making an existing synchronous API utilize a JavaScript/WASM asynchronous based API.

An example of the Julia runtime adding support - https://github.com/julialang/julia/pull/32532.

See https://github.com/dotnet/runtime/issues/37669

/cc @steveisok @lewing @marek-safar

**Comment by lewing** [comment]
For background https://kripken.github.io/blog/wasm/2019/07/16/asyncify.html covers the benefits and limitations.  The limitations there are hard to avoid in the current runtime but we should expand on the reasoning here.

**Comment by lewing** [comment]
The limitations around this approach in the browser scenario make it unsuitable for a general sync over Promise solution.
