### ISSUE TITLE
System.Private.CoreLib.xml is missing from the ref folders

### ISSUE THREAD

**Issue by gpetrou** [dotnet/runtime#48726]
I assume that this is related to the installation, if not please move it to the appropriate repository.

Check the contents of the dotnet ref folders such as:
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\5.0.0\ref\net5.0

Other XML files are present and can be used to extract documentation.
System.Private.CoreLib.xml is missing and therefore we cannot parse the file to extract the documentation.
Check https://github.com/dotnet/runtime/discussions/48264 for more information.

**Comment by ViktorHofer** [comment]
> Is there another property that will return System.Runtime for the StringBuilder perhaps?

The official API docs tell you in which assembly an API is exposed. I.e. for StringBuilder it's "System.Runtime": https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder?view=net-5.0.

Does that answer your question?

**Comment by gpetrou** [comment]
Hmm, not sure I understand this recommendation.
If you do for example:
Console.WriteLine((new StringBuilder()).GetType().Assembly.GetName());
you get something like:
System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
What do you need to use to get System.Runtime?
Please note, I am not specifically interested in StringBuilder. I am just using it as an example.
To dynamically extract the documentation for a type, I just use type.Assembly etc... to get the assembly name and find the corresponding XML file.

**Comment by ViktorHofer** [comment]
> If you use the StringBuilder Type Assembly property, you will see that it returns the System.Private.CoreLib. Therefore we would look for System.Private.CoreLib.xml. Something similar happens with .NET Framework and mscorlib, but in that case there is an XML file. Is there another property that will return System.Runtime for the StringBuilder perhaps?

This is by design as not all types live in the same assembly identity as they are exposed. A type might be exposed by System.Runtime.dll (and documented in System.Runtime.xml) but actually lives in System.Private.CoreLib. System.Runtime's implementation assembly contains a type forward that routes callers to the CoreLib assembly.
