### ISSUE TITLE
Consider updating to macosx-version-min=10.14

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48721]
The minimum supported macOS version is now 10.14.  10.13 was dropped from Apple support 12/2020 and is officially unsupported for .NET 6.0.  https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0-supported-os.md

Consider updating code to target 10.14 as a minimum x64 version.

https://github.com/dotnet/runtime/blob/0cbfb7459ba8e8f094b57ab0403726112c786a79/eng/native/configurecompiler.cmake#L417

Possibly other places are affected too.

It is not clear what the immediate value of this would be.  However, new APIs become available as we move to new OS releases. This may enable optimizations/simplifications. It also allows new code to be written using newer os APIs

**Comment by vcsjones** [comment]
> It is not clear what the immediate value of this would be. However, new APIs become available as we move to new OS releases. This may enable optimizations/simplifications. 

This would be helpful in the native shims for System.Security.Crypgraphy.Native.Apple. There are several APIs that Apple has deprecated starting in 10.14 (for example, `SecTrustEvaluate`).

Bumping the minimum macOS version would allow us to target some new APIs and remove the use of deprecated ones.

**Comment by akoeplinger** [comment]
> Bumping the minimum macOS version would allow us to use the new APIs and remove the use of deprecated ones.

We'll probably need to keep them at least under an #ifdef since we still need to support iOS 10+.

**Comment by frenzibyte** [comment]
Just to note, this has since been updated to 10.14 in https://github.com/dotnet/runtime/commit/4dd867ff43fab74972d1f58a8003a71296d3ca4c, and in .NET 6 the limit looks to be increased to 10.15 (according to the [`supported-os.md`](https://github.com/dotnet/runtime/commit/4dd867ff43fab74972d1f58a8003a71296d3ca4c) document).
