### ISSUE TITLE
Re-enable tracing/eventpipe/eventsvalidation/ThreadPool test after investigating failure with zapDisable

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48727]
`tracing/eventpipe/eventsvalidation/ThreadPool` is failing on multiple platforms with zapdisable.

See https://dev.azure.com/dnceng/public/_build/results?buildId=1010016&view=results

/cc @BruceForstall @dotnet/dotnet-diag

**Comment by sywhang** [comment]
will take a look now

**Comment by sdmaclea** [comment]
Looks like it is also failing in. outerloop.

**Comment by briansull** [comment]
Any update on this outerloop blocker?

**Comment by sdmaclea** [comment]
I disabled the test for Apple Silicon in #48777.  If we don't have a fix, we should just disable this test on all platforms.

**Comment by sywhang** [comment]
The test was disabled via #48860 on all legs -- I'll come back to investigating this later.

**Comment by noahfalk** [comment]
Fixed in #56680
