### ISSUE TITLE
UseWindowsService doesn't work correctly with single file executables

### ISSUE THREAD

**Issue by Talha-B** [dotnet/runtime#48730]
I'm experiencing the exact problem described in the opening post of this [issue](https://github.com/dotnet/runtime/issues/36065), where I've got a worker service that has been published as a self contained exe and setup to run as a windows service and the application is unable to read the config file.

According to the last post, it has been resolved in .net 5.0 with AppContext.BaseDirectory being set to the path of the exe but that does not appear to be the case. I'm targeting 5.0 yet when logging out the value of AppContext.BaseDirectory, I get the temp folder: 
C:\WINDOWS\TEMP\.net\MyWorkerService\qz4dywo4.4hl\

**Comment by Talha-B** [comment]
I was able to make it work as expected when doing the publish using the following variation:

`dotnet publish -r win-x64 -p:PublishSingleFile=true -o c:\worker -p:DebugType=None`

In place of the following, which manifests the behaviour mentioned in this ticket:

`dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o c:\worker -p:DebugType=None`

**Comment by jkotas** [comment]
Do you need the `IncludeAllContentForSelfExtract` option to publish your app? 

IncludeAllContentForSelfExtract simulates how single-file worked in .NET Core 3.1 and it has number of known issues. It is best to avoid it if possible.

**Comment by Talha-B** [comment]
Thanks
