### ISSUE TITLE
Add API to make configuring the HostOptions easier

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#48743]
## Background and Motivation

Right now there's no syntax sugar for configuring the host options. For example configuring the shutdown timeout looks like this:

```C#
using var host = new HostBuilder()
    .ConfigureServices(servies =>
    {
        servies.Configure<HostOptions>(o =>
        {
            o.ShutdownTimeout = TimeSpan.FromMinutes(10);
        });
    })
    .Build();

host.Run();
```

We should have a simpler way to configure host settings so they are more discoverable.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace Microsoft.Extensions.Hosting
{
    public static class HostingHostBuilderExtensions
    {
+        public static IHostBuilder ConfigureHostOptions(this IHostBuilder hostBuilder, Action<HostOptions> configure);
    }
}
```

## Usage Examples

``` C#
using var host = new HostBuilder()
    .ConfigureHostOptions(o =>
    {
        o.ShutdownTimeout = TimeSpan.FromMinutes(10);
    })
    .Build();

host.Run();
```

## Alternative Designs

More first class support for options like ShutdownTimeout:

```C#
using var host = new HostBuilder()
    .UseShutdownTimeout(TimeSpan.FromMinutes(10))
    .Build();

host.Run();
```

The only downside is that we'd need methods for every top level option (like the new one here https://github.com/dotnet/runtime/issues/43637)

## Risks

None.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace Microsoft.Extensions.Hosting
{
    public static class HostingHostBuilderExtensions
    {
        public static IHostBuilder ConfigureHostOptions(this IHostBuilder hostBuilder, Action<HostOptions> configure);
    }
}
```

**Comment by maryamariyan** [comment]
This is a follow up request to add a second overload:

```c#
namespace Microsoft.Extensions.Hosting
{
    public static class HostingHostBuilderExtensions
    {
+        public static IHostBuilder ConfigureHostOptions(this IHostBuilder hostBuilder, Action<HostBuilderContext, HostOptions> configure);
        public static IHostBuilder ConfigureHostOptions(this IHostBuilder hostBuilder, Action<HostOptions> configure);
    }
}
```


**Reason 1:**

There is precedence on `HostingHostBuilderExtensions.ConfigureLogging` with the following two overloads:

https://github.com/dotnet/runtime/blob/689c4927f3e51a8a688a707066c21e5b47d17419/src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.cs#L42-L43

(also with HostingHostBuilderExtensions.UseDefaultServiceProvider):
https://github.com/dotnet/runtime/blob/eceb5c8951ca3e5902a6eecdd594f82916ff4762/src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.cs#L50-L51

**Reason 2:**
Both two new `ConfigureHostOptions` APIs proposed end up calling into `ConfigureServices`:

https://github.com/dotnet/runtime/blob/8a31e66a86ec2e8be53d0b0798ced68b9f410be3/src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.cs#L34

which could take a delegate with `HostBuilderContext`

---

This discussion is currently blocking PR https://github.com/dotnet/runtime/pull/49502#discussion_r596466330

**Comment by davidfowl** [comment]
I hope this doesn't need to go to API review again 🤩
