### ISSUE TITLE
[Apple M1 Rosetta 2] Running 2.1 project failed if .NET 5.0 & .NET Core 3.1 is installed also

### ISSUE THREAD

**Issue by Jepson112** [dotnet/runtime#48745]
**Setup:**
Mac OS: Big Sur(11.2.1) - Apple M1 chip
VS for Mac: 8.9 preview ( build 1643)
SDK 5.0.104(runtime 5.0.4)+3.1.407(runtime 3.1.13)+runtime 2.1.26

**Steps to reproduce:**
1.Install SDK 5.0.104(x64) + SDK 3.1.407(x64) +Runtime 2.1.26 
2.Create a new project on VS/Terminal
3. Run this project

**Expected result:**
.Net core 2.1 project run success

**Actual result:**
.Net core 2.1 project run failed and report “dotnet quit unexpectedly”  
![image](https://user-images.githubusercontent.com/61412494/109119984-588bac80-7780-11eb-8f5f-b8c48de5b2d2.png)

Dotnet --info
![image](https://user-images.githubusercontent.com/61412494/109120027-66d9c880-7780-11eb-859c-9e62e4c09d9f.png)

**Note:**
1.Only Install SDK 2.1.814(runtime 2.1.26) this issue not report
2.Restart VSFM & Terminal this issue still report ,But Restart Mac OS this issue not report again.

**Problem details:**
Process:               dotnet [3868]
Path:                  /usr/local/share/dotnet/dotnet
Identifier:            dotnet
Version:               0
Code Type:             X86-64 (Translated)
Parent Process:        vsdbg [3867]
Responsible:           VisualStudio [3730]
User ID:               501

Date/Time:             2021-02-24 16:11:20.813 +0800
OS Version:            macOS 11.2.1 (20D75)
Report Version:        12
Anonymous UUID:        43FF3D1A-FC00-8616-FEE0-5CB50F47998D

Sleep/Wake UUID:       6CB0BA6E-3269-4D75-A0A8-6F4830CDF874

Time Awake Since Boot: 21000 seconds
Time Since Wake:       19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x0000000108e1e000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2

kernel messages:

VM Regions Near 0x108e1e000:
    Rosetta Generic             108e1d000-108e1e000    [    4K] rw-/rwx SM=PRV  
--> mapped file                 108e1e000-108f05000    [  924K] r-x/rwx SM=COW  Object_id=26737b8d
    mapped file                 108f05000-108f07000    [    8K] rw-/rwx SM=COW  Object_id=26737b8d

Application Specific Information:
dyld: in dlopen()
/usr/local/share/dotnet/shared/Microsoft.NETCore.App/2.1.26/libhostpolicy.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x0000000200af84f0 ImageLoaderMachO::crashIfInvalidCodeSignature() + 88
1   dyld                          	0x0000000200aff84d ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, encryption_info_command const*, ImageLoader::LinkContext const&) + 349
2   dyld                          	0x0000000200af8320 ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) + 158
3   dyld                          	0x0000000200ae1eeb dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) + 781
4   dyld                          	0x0000000200aeaa64 dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 1419
5   dyld                          	0x0000000200aea477 dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 185
6   dyld                          	0x0000000200aea1f2 dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 1434
7   dyld                          	0x0000000200ae9845 dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 186
8   dyld                          	0x0000000200ae1a4e dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, unsigned int&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) + 487
9   dyld                          	0x0000000200ae15d2 dyld::load(char const*, dyld::LoadContext const&, unsigned int&) + 185
10  dyld                          	0x0000000200aef4ab dlopen_internal + 419
11  libdyld.dylib                 	0x00007fff20362fc0 dlopen_internal(char const*, int, void*) + 177
12  libdyld.dylib                 	0x00007fff2035186e dlopen + 28
13  libhostfxr.dylib              	0x0000000108d342e6 pal::load_library(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, void**) + 38
14  libhostfxr.dylib              	0x0000000108d2ca6c hostpolicy_resolver::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void**, hostpolicy_contract_t&) + 236
15  libhostfxr.dylib              	0x0000000108d3f864 fx_muxer_t::handle_exec_host_command(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, host_startup_info_t const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unordered_map<known_options, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, known_options_hash, std::__1::equal_to<known_options>, std::__1::allocator<std::__1::pair<known_options const, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > > const&, int, char const**, int, host_mode_t, char*, int, int*) + 996
16  libhostfxr.dylib              	0x0000000108d3ead3 fx_muxer_t::execute(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int, char const**, host_startup_info_t const&, char*, int, int*) + 611
17  libhostfxr.dylib              	0x0000000108d3c47a hostfxr_main_startupinfo + 138
18  dotnet                        	0x00000001009fb402 0x1009ef000 + 50178
19  dotnet                        	0x00000001009fb9f5 0x1009ef000 + 51701
20  libdyld.dylib                 	0x00007fff20361621 start + 1

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	0x00007ffdffd72238 0x7ffdffd70000 + 8760
1   runtime                       	0x00007ffdffd7c354 0x7ffdffd70000 + 50004
2   runtime                       	0x00007ffdffd7d1f8 0x7ffdffd70000 + 53752

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000108e1e000  rbx: 0x0000000000000000  rcx: 0x0000000000000020  rdx: 0x00000003055da800
  rdi: 0x00007fe665e04930  rsi: 0x0000000000000000  rbp: 0x00000003055da210  rsp: 0x00000003055da200
   r8: 0x0000000000000005   r9: 0x00000000000e9000  r10: 0x0000000000040012  r11: 0x0000000000003fff
  r12: 0x0000000200b82298  r13: 0x00007fe665e04930  r14: 0x00007fe665e04930  r15: 0x0000000000000000
  rip: <unavailable>  rfl: 0x0000000000000202

Binary Images:
       0x1009ef000 -        0x100a10fff +dotnet (0) <4248F50F-A2CE-3E86-91EB-595682366DA3> /usr/local/share/dotnet/dotnet
       0x108d2b000 -        0x108d72fff +libhostfxr.dylib (0) <633BD33B-7662-3546-8CA3-22D028308D7A> /usr/local/share/dotnet/host/fxr/5.0.4/libhostfxr.dylib
       0x200ade000 -        0x200b79fff  dyld (832.7.3) <0D4EA85F-7E30-338B-9215-314A5A5539B6> /usr/lib/dyld
    0x7ffdffd70000 -     0x7ffdffde3fff +runtime (203.30) <C98E75A6-BDC8-3D5C-B95B-6422005E96D8> /Library/Apple/*/runtime
    0x7fff2007a000 -     0x7fff2007bfff  libsystem_blocks.dylib (78) <E644CAA0-65B7-36E4-8041-520F3301F3DB> /usr/lib/system/libsystem_blocks.dylib
    0x7fff2007c000 -     0x7fff200b1fff  libxpc.dylib (2038.80.3) <70F26262-01AA-3CEC-9FAD-2701D24096F0> /usr/lib/system/libxpc.dylib
    0x7fff200b2000 -     0x7fff200c9fff  libsystem_trace.dylib (1277.80.2) <87FEF600-48D9-31C9-B8FC-D5249B2AE95D> /usr/lib/system/libsystem_trace.dylib
    0x7fff200ca000 -     0x7fff20169fff  libcorecrypto.dylib (1000.80.5) <1EB11CFB-ABD7-36DD-97C7-C112A6601416> /usr/lib/system/libcorecrypto.dylib
    0x7fff2016a000 -     0x7fff20196fff  libsystem_malloc.dylib (317.40.8) <A498D1EF-E43D-310C-84E8-9C0AADA0C475> /usr/lib/system/libsystem_malloc.dylib
    0x7fff20197000 -     0x7fff201dbfff  libdispatch.dylib (1271.40.12) <AD988EEA-1A2F-3404-9A6E-390FC2504223> /usr/lib/system/libdispatch.dylib
    0x7fff201dc000 -     0x7fff20215fff  libobjc.A.dylib (818.2) <0F399805-A533-3DC9-A951-1D3DF1442BD9> /usr/lib/libobjc.A.dylib
    0x7fff20216000 -     0x7fff20218fff  libsystem_featureflags.dylib (28.60.1) <9CECB43A-094E-3CA9-B730-24DEA1A6DE05> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff20219000 -     0x7fff202a1fff  libsystem_c.dylib (1439.40.11) <4AF71812-4099-3E96-B271-1F259491A2B2> /usr/lib/system/libsystem_c.dylib
    0x7fff202a2000 -     0x7fff202f7fff  libc++.1.dylib (904.4) <B217D905-4F9C-3DE0-8844-88FAA3C2C851> /usr/lib/libc++.1.dylib
    0x7fff202f8000 -     0x7fff20310fff  libc++abi.dylib (904.4) <3C9FE530-3CD2-3A64-8A36-70816AEBDF0D> /usr/lib/libc++abi.dylib
    0x7fff20311000 -     0x7fff2033ffff  libsystem_kernel.dylib (7195.81.3) <AB413518-ECDE-3F04-A61C-278D3CF43076> /usr/lib/system/libsystem_kernel.dylib
    0x7fff20340000 -     0x7fff2034bfff  libsystem_pthread.dylib (454.80.2) <B989DF6C-ADFE-3AF9-9C91-07D2521F9E47> /usr/lib/system/libsystem_pthread.dylib
    0x7fff2034c000 -     0x7fff20386fff  libdyld.dylib (832.7.3) <4641E48F-75B5-3CC7-8263-47BF79F15394> /usr/lib/system/libdyld.dylib
    0x7fff20387000 -     0x7fff20390fff  libsystem_platform.dylib (254.80.2) <1C3E1A0A-92A8-3CDE-B622-8940B43A5DF2> /usr/lib/system/libsystem_platform.dylib
    0x7fff20391000 -     0x7fff203bcfff  libsystem_info.dylib (542.40.3) <0C96CFE8-71F5-3335-8423-581BC3DE5846> /usr/lib/system/libsystem_info.dylib
    0x7fff226e0000 -     0x7fff226e9fff  libsystem_darwin.dylib (1439.40.11) <E016D8F7-C87F-36F8-B8A0-6A61B8E4BACB> /usr/lib/system/libsystem_darwin.dylib
    0x7fff22afb000 -     0x7fff22b06fff  libsystem_notify.dylib (279.40.4) <B2BF20C7-448A-3FBD-A2F5-AB7618D173F6> /usr/lib/system/libsystem_notify.dylib
    0x7fff24a57000 -     0x7fff24a65fff  libsystem_networkextension.dylib (1295.80.3) <5213D866-7D0E-3FD9-8E1A-03C0E39CEC44> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24ac3000 -     0x7fff24ad9fff  libsystem_asl.dylib (385) <5B48071E-85EB-33B0-AE9B-127AEB398AEC> /usr/lib/system/libsystem_asl.dylib
    0x7fff261f1000 -     0x7fff261f8fff  libsystem_symptoms.dylib (1431.40.36) <BC85B46C-02EE-31FF-861D-F0DE01E8F6CF> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff28523000 -     0x7fff28533fff  libsystem_containermanager.dylib (318.80.2) <6F08275F-B912-3D8E-9D74-4845158AE4F3> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff29237000 -     0x7fff2923afff  libsystem_configuration.dylib (1109.60.2) <4917D824-4DE8-32CC-9ED2-1FBF371FEB9F> /usr/lib/system/libsystem_configuration.dylib
    0x7fff2923b000 -     0x7fff2923ffff  libsystem_sandbox.dylib (1441.60.4) <5F7F3DD1-4B38-310C-AA8F-19FF1B0F5276> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff29e4a000 -     0x7fff29e4cfff  libquarantine.dylib (119.40.2) <40D35D75-524B-3DA6-8159-E7E0FA66F5BC> /usr/lib/system/libquarantine.dylib
    0x7fff2a3cd000 -     0x7fff2a3d1fff  libsystem_coreservices.dylib (127) <529A0663-A936-309C-9318-1B04B7F70658> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a5e8000 -     0x7fff2a633fff  libsystem_m.dylib (3186.40.2) <7BE9BAE3-ADED-35DD-B920-34F590BAB507> /usr/lib/system/libsystem_m.dylib
    0x7fff2a635000 -     0x7fff2a63afff  libmacho.dylib (973.4) <C2584BC4-497B-3170-ADDF-21B8E10B4DFD> /usr/lib/system/libmacho.dylib
    0x7fff2a657000 -     0x7fff2a662fff  libcommonCrypto.dylib (60178.40.2) <822A29CE-BF54-35AD-BB15-8FAECB800C7D> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a663000 -     0x7fff2a66dfff  libunwind.dylib (200.10) <1D0A4B4A-4370-3548-8DC1-42A7B4BD45D3> /usr/lib/system/libunwind.dylib
    0x7fff2a66e000 -     0x7fff2a675fff  liboah.dylib (203.30) <44C477D9-013F-3A6D-A9FE-68A89214E6A5> /usr/lib/liboah.dylib
    0x7fff2a676000 -     0x7fff2a680fff  libcopyfile.dylib (173.40.2) <39DBE613-135B-3AFE-A6AF-7898A37F70C2> /usr/lib/system/libcopyfile.dylib
    0x7fff2a681000 -     0x7fff2a688fff  libcompiler_rt.dylib (102.2) <62EE1D14-5ED7-3CEC-81C0-9C93833641F1> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a689000 -     0x7fff2a68bfff  libsystem_collections.dylib (1439.40.11) <C53D5E0C-0C4F-3B35-A24B-E0D7101A3F95> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a68c000 -     0x7fff2a68efff  libsystem_secinit.dylib (87.60.1) <E05E35BC-1BAB-365B-8BEE-D774189EFD3B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a68f000 -     0x7fff2a691fff  libremovefile.dylib (49.40.3) <5CC12A16-82CB-32F0-9040-72CFC88A48DF> /usr/lib/system/libremovefile.dylib
    0x7fff2a692000 -     0x7fff2a692fff  libkeymgr.dylib (31) <803F6AED-99D5-3CCF-B0FA-361BCF14C8C0> /usr/lib/system/libkeymgr.dylib
    0x7fff2a693000 -     0x7fff2a69afff  libsystem_dnssd.dylib (1310.80.1) <E0A0CAB3-6779-3C83-AC67-046CFE69F9C2> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a69b000 -     0x7fff2a6a0fff  libcache.dylib (83) <1A98B064-8FED-39CF-BB2E-5BDA1EF5B65A> /usr/lib/system/libcache.dylib
    0x7fff2a6a1000 -     0x7fff2a6a2fff  libSystem.B.dylib (1292.60.1) <83503CE0-32B1-36DB-A4F0-3CC6B7BCF50A> /usr/lib/libSystem.B.dylib
    0x7fff2dc36000 -     0x7fff2dc36fff  liblaunch.dylib (2038.80.3) <C7C51322-8491-3B78-9CFA-2B4753662BCF> /usr/lib/system/liblaunch.dylib
    0x7fff300ea000 -     0x7fff300eafff  libsystem_product_info_filter.dylib (8.40.1) <20310EE6-2C3F-361A-9ECA-4223AFC03B65> /usr/lib/system/libsystem_product_info_filter.dylib

Translated Code Information:
  tmp0: 0x0000000200af84f0 tmp1: 0x0000000200af84f0 tmp2: 0x0000000200c23d90

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 11999
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=512.2M resident=0K(0%) swapped_out_or_unallocated=512.2M(100%)
Writable regions: Total=304.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=304.3M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            35.1M       13 
MALLOC guard page                   96K        4 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
Rosetta Arena                     2048K        1 
Rosetta Generic                    592K      145 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       7548K        3 
__DATA                             449K       47 
__DATA_CONST                       243K       33 
__DATA_DIRTY                        58K       21 
__LINKEDIT                       506.5M        7 
__OBJC_RO                         60.5M        1 
__OBJC_RW                         2449K        2 
__TEXT                            5900K       46 
mapped file                        4.1G       81 
shared memory                       16K        1 
unshared pmap                     3056K        2 
===========                     =======  ======= 
TOTAL                              5.0G      417 
TOTAL, minus reserved VM space     4.9G      417 

Model: Macmini9,1, BootROM 6723.81.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Dec 31 2020 21:39:03 version 18.20.222.20.7.8.104 FWID 01-1b2645bc
Bluetooth: Version 8.0.3d9, 3 services, 25 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: USB 3.0 Bus
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: USB OPTICAL MOUSE
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Comment by vitek-karas** [comment]
@sdmaclea is this a problem with signing of really old (2.1) runtimes?

**Comment by sdmaclea** [comment]
Yes it looks like the 2.1 libhostpolicy is getting killed for code signing issues.  

It is not clear why it only happens with the newer dotnet/hostfxr.  Perhaps it is because the newer dotnet has more entitlements?

/cc @janvorli

**Comment by sdmaclea** [comment]
> But Restart Mac OS this issue not report again.

This could have been a MacOS Big Sur issue.  There was a problem at one time where the signature checking of binaries would fail unless the directory was deleted and recreated.  

You might want to try Big Sur 11.3 Beta 3 or the actual release when it is available.

**Comment by agocke** [comment]
Closing, as it looks like this has been resolved.
