### ISSUE TITLE
Add new rule for detecting implementations of GetHashCode that uses mutable data

### ISSUE THREAD

**Issue by bjornhellander** [dotnet/runtime#48769]
### Describe the problem you are trying to solve

GetHashCode is typically implemented when having a collection of objects and the collection is implemented as a hash table. If some members of those objects can be changed and those members are used in GetHashCode(), then unpredictable things will happen if the object is modified after adding it to a collection. Informing developers of this potential problem would be a good thing.

Applies equally to object.GetHashCode() and IEqualityComparer<T>.GetHashCode(T)

### Describe suggestions on how to achieve the rule

Check implementations of GetHashCode() to see that they don't reference any members that are mutable, i.e. non-readonly fields, properties with setters, etc. Maybe hard to do really well, like if the implementation loops through items in member collections, but should be easy to make a "conservative" rule that catches basic cases like the ones below.

### Additional context

Example 1:
```c#
    public class Class1
    {
        public int X { get; set; }

        public override int GetHashCode()
        {
            return X.GetHashCode(); // Potentially bad
        }
    }
```

Example 2:
```c#
    public class Class2
    {
        public int X { get; set; }
    }

    public class Class2Comparer : IEqualityComparer<Class2>
    {
        public bool Equals(Class2 x, Class2 y)
        {
            return false; // Not relevant in this example
        }

        public int GetHashCode(Class2 obj)
        {
            return obj.X.GetHashCode(); // Potentially bad
        }
    }
```

**Comment by mavasani** [comment]
@carlossanlop @buyaa-n for helping drive triage - its an API specific analyzer feature request.

**Comment by eiriktsarpalis** [comment]
Hi @buyaa-n, should I move this to the Future milestone?

**Comment by buyaa-n** [comment]
Yes it can be in future milestone, I will update

**Comment by carlossanlop** [comment]
@buyaa-n and I thought about some flaggable and non-flaggable cases. The main difficulty would be to _avoid_ false positives, which would mean _not flagging_ cases that are too complex for an analyzer to analyze.

Thoughts? Any feedback? Is it still worth it creating this analyzer?

## Flag

A field.
```cs
class MyClass
{
    public int C;

    public override int GetHashCode()
    {
        return C.GetHashCode();
    }
}
```
A property with body-less getter and setter.
```cs       
class MyClass
{
    public int X { get; set; }

    public override int GetHashCode()
    {
        return X.GetHashCode();
    }
}
```

## Do not flag

Readonly field.
```cs
class MyClass
{
    public readonly int C;

    public MyClass()
    {
            C = Something();
    }

    public override int GetHashCode()
    {
        return C.GetHashCode();
    }
}
```

Property with only a body-less getter.
```cs
class MyClass
{
    public int X { get; }

    public MyClass()
    {
            X = Something();
    }

    public override int GetHashCode()
    {
        return X.GetHashCode();
    }
}
```


```cs
class MyClass
{
    public int X { get; }

    public MyClass()
    {
        X = Something();
    }

    public override int GetHashCode()
    {
        int y = X * 2;
        return y.GetHashCode();
    }
}
```

A property with a getter, and the getter has a body, is too complicated to analyze, so we will assume it's mutable.
```cs
class MyClass
{
    public int X
    {
        get
        {
                return Something();
        }
    }

    public override int GetHashCode()
    {
        return X.GetHashCode();
    }
}
```

If methods are involved, we don't flag, because it would be too complex.
```cs
class MyClass
{
    public int X { get; }

    public MyClass()
    {
        X = Something();
    }

    public int MyMethod()
    {
        return X;
    }

    public override int GetHashCode()
    {
        return MyMethod().GetHashCode();
    }
}
```
Even if the method returns an immutable value, it would be too complex to analyze, so we don't flag.
```cs
class MyClass
{
    public readonly int C;

    public MyClass()
    {
        C = Something();
    }

    public int X
    {
        get
        {
            return Foo();
        }
    }

    private int Foo()
    {
        return C;
    }

    public override int GetHashCode()
    {
        return X.GetHashCode();
    }
}
```

**Comment by bjornhellander** [comment]
@carlossanlop I have an implementation of this in another repository. Matches your cases above pretty well as far as I can see. I can provide a pull request if that would help reasoning about if this is a good idea for you or not, but I would need some pointers as to where in the repository it would go.

**Comment by Youssef1313** [comment]
@bjornhellander If this analyzer rule is accepted, it would go in [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) repository.

**Comment by bjornhellander** [comment]
That's where I posted the issue originally, but it was moved here :grin:

**Comment by Youssef1313** [comment]
@bjornhellander The move here is correct. Analyzers related to .NET APIs are first discussed and approved by the .NET runtime team (in dotnet/runtime repo). Then, after they're approved, are implemented in dotnet/roslyn-analyzers.

**Comment by bjornhellander** [comment]
I see. Alright 👍

**Comment by danmoseley** [comment]
> so we will assume it's mutable.

Wouldn't that be a false positive? I would think we only want to flag cases we are certain about.

**Comment by danmoseley** [comment]
This analyzer could lead developers to introduce bugs. For example in the "public int C;" or similar cases above, removing C from the hash code calculation in favor of the base GetHashCode() implementation would introduce a bug, if two of these objects with the same C are supposed to compare as equal. The right fix in that case might be to make the field private, or implement some kind of freeze pattern, if the app only modifies this field when the object is not in a collection.

**Comment by bjornhellander** [comment]
> > so we will assume it's mutable.
> 
> Wouldn't that be a false positive? I would think we only want to flag cases we are certain about.

I agree with you on this. I apparently didn't read that part of @carlossanlop's suggestion well enough. How about if it only triggers on properties when it is an auto property with a setter? Slightly less trivial cases could potentially be added later on.

**Comment by bjornhellander** [comment]
Regarding the risk of leading developers to change code in unwanted ways, I would think that depends a great deal on the actual wording. So prefer something like "make accessed members immutable" instead of "do not access mutable members".

**Comment by danmoseley** [comment]
Do we have data suggesting how often this pattern leads to real world bugs? As with any analyzer presumably we have to weigh that against cognitive load and the possibility of fixing it by creating another bug - @stephentoub do you have a sense?

**Comment by stephentoub** [comment]
Someone motivated could gather some data, but my gut is that most interesting cases that should be flagged would fall into the "this is too difficult to analyze properly while still minimizing false positives" category.  Related, there's a whole set of cases where GetHashCode is relatively expensive and so lazily computes and stores the hash code... the field it's reading/writing as part of that lazy-init is mutable by definition, and so the analyzer would need to also successfully rule those out, again to avoid false positives.  The motivation for the rule is sound and I agree if it could be done well (few false positives and few false negatives) it'd be ok to add, but I suspect it'd be hard to strike that right balance to the point where we'd be comfortable doing so.

**Comment by bjornhellander** [comment]
I hadn't even thought about implementations that cache the calculated hash code. If the requirement is both few false positives and few false negatives, then I don't think this is likely to get implemented.

I think it's a little bit sad though, since I belive that most implementations are trivial, but I understand if you want these analyzers to be accurate, since they have so widespread use. Personally, I would be happy to suppress diagnostics once in a while, or even turn an analyzer off completely if it didn't suit the project I am working in, if the analyzer would help me find potential bugs just occasionally. But again, I understand if you expect more from this specific package. Feel free to close this if you want.

**Comment by bjornhellander** [comment]
Closing
