### ISSUE TITLE
dotnet publish: rosetta error: ThreadContext::suspend failed -308

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#48760]
Hi!

I faced with the following error when dotnet publish --self-contained app on macOS Big Sur 11.2:
```
rosetta error: ThreadContext::suspend failed -308
```

Is it a known problem?

.NET SDK 5.0.103 x64

Linked issues: https://github.com/dotnet/runtime/issues/44897

**Comment by sdmaclea** [comment]
I have not seen this issue before.  Thanks for reporting it.

Apple has been fixing Rosetta 2 issues for .NET.  It is nice for us to be able to track these issues, but it is also important to provide feedback to Apple.

**Comment by mangod9** [comment]
hi @k15tfu, Apple has fixed a bunch of issues in 11.3. If this still fails for you please reopen so we could investigate.
