### ISSUE TITLE
Error building debug-pal's ds-ipc-posix.c with older cmake

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#48764]
I am having trouble building dotnet/runtime `master` branch (`8483e9edc809c6d9799600d062abca8ab6c61e46`) using an older CMake (`cmake version 3.6.2`) on RHEL 7:

```
Building CXX object debug/debug-pal/CMakeFiles/debug-pal_obj.dir/runtime/src/native/eventpipe/ds-ipc-posix.c.o
cd runtime/artifacts/obj/coreclr/Linux.x64.Release/debug/debug-pal && clang++-10   -DDISABLE_CONTRACTS -DFEATURE_CORECLR -DFEATURE_PERFTRACING -DFEATURE_PERFTRACING_STANDALONE_PAL -DHOST_64BIT -DHOST_AMD64 -DHOST_UNIX -DNDEBUG -DPAL_IMPLEMENTATION -DPAL_STDCPP_COMPAT -DTARGET_64BIT -DTARGET_AMD64 -DTARGET_LINUX -DTARGET_UNIX -DURTBLDENV_FRIENDLY=Retail -D_POSIX_C_SOURCE=200809L -Iruntime/src/coreclr/debug/debug-pal/../inc -Iruntime/src/coreclr/debug/debug-pal/../../pal/inc -Iruntime/src/native/eventpipe  -O2 -DNDEBUG -fPIC   -O3 -g -Wall -Wno-null-conversion -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -Werror -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-tautological-compare -Wimplicit-fallthrough -Wno-invalid-offsetof -ferror-limit=4096 -Wno-unused-private-field -Wno-microsoft -Wno-constant-logical-operand -Wno-pragma-pack -Wno-unknown-warning-option -Wno-incompatible-ms-struct -fsigned-char -fvisibility=hidden -std=gnu++11 -o CMakeFiles/debug-pal_obj.dir/runtime/src/native/eventpipe/ds-ipc-posix.c.o -c runtime/src/native/eventpipe/ds-ipc-posix.c
clang-10: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]                                             
gmake[2]: Leaving directory `runtime/artifacts/obj/coreclr/Linux.x64.Release'  
```

The command line here does not use the `-xc++` flag set here:

https://github.com/dotnet/runtime/blob/8483e9edc809c6d9799600d062abca8ab6c61e46/src/coreclr/debug/debug-pal/CMakeLists.txt#L39-L41

This makes me suspect that this is being caused by an older version of CMake.

I am *not* seeing this error on any other platform, all of which have newer cmake versions.

Is there a workaround for this possible? Or is runtime implicitly requiring a newer version of cmake now?

cc @dleeapho @tmds

**Comment by omajid** [comment]
Looking at my build history, this error seems to have started happening just after https://github.com/dotnet/runtime/pull/47665/ (at least the same day) was merged, which makes sense, because that's when `ds-ipc-posix.c` was added to the default build.

**Comment by omajid** [comment]
Disabling warnings makes the build work.

**Comment by tommcdon** [comment]
@lateralusX @josalem @hoyosjs

**Comment by hoyosjs** [comment]
Yes, this is indeed an issue on the CMake file that were added as part of the shared EP. The version of CMake used by source-build for RHEL can't use PROPERTIES COMPILE_OPTIONS afaik. You need to use 
```
add_compile_options(-xc++)
```

**Comment by hoyosjs** [comment]
I am also not 100% sure about `PROPERTIES LANGUAGE CXX`

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/linux-requirements.md#toolchain-setup, says we need CMake 3.14.5 or newer.

`PROPERTIES LANGUAGE CXX` should be available since v3.0, https://cmake.org/cmake/help/v3.0/prop_sf/LANGUAGE.html
`PROPERTIES COMPILE_OPTIONS CXX` compile option was added in v3.11, https://cmake.org/cmake/help/v3.11/prop_sf/COMPILE_OPTIONS.html

**Comment by lateralusX** [comment]
add_compile_options(-xc++) could probably be used on older cmake versions, but it will then be applied to potentially more sources then expected.

The same semantics is also used for EventPipe Sources https://github.com/dotnet/runtime/blob/6885777ebbd906bb4e2a306635bb028004764eaa/src/coreclr/vm/eventing/eventpipe/CMakeLists.txt#L68, but doesn't seem you hit that issue, maybe you don't build with `FEATURE_PERFTRACING` ?

**Comment by lateralusX** [comment]
Guess we potentially could add:

```
if (CMAKE_VERSION VERSION_GREATER 3.11 OR CMAKE_VERSION VERSION_EQUAL 3.11)
    set_source_files_properties(${EVENTPIPE_PAL_SOURCES} PROPERTIES COMPILE_OPTIONS -xc++) 
else(CMAKE_VERSION VERSION_GREATER 3.11 OR CMAKE_VERSION VERSION_EQUAL 3.11)
    add_compile_options(-xc++)
endif()
```

**Comment by lateralusX** [comment]
Will fix this, running a test with above fix on CMake 3.6.2 using our CentOS 7 (build for RHEL 7)docker image https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/linux-instructions.md#docker-images, our docker images all run on later CMake versions so needed to make a manual downgrade to 3.6.2.

**Comment by lateralusX** [comment]
Successfully build using that docker image and CMake 3.6.2.

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/pull/48809

**Comment by omajid** [comment]
Thanks for fixing this so quickly!
