### ISSUE TITLE
[NET5] PerformanceCounter and invalid culture identifier exception

### ISSUE THREAD

**Issue by jhdscript** [dotnet/runtime#48771]
Hello,

I try to use PerformanceCounter in a FW 5 project. So i install this dependancy: https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/5.0.1

But when i try to use it with  new PerformanceCounter(category,counter,instance) i have issues with culture and culture identifier

I m under Windows 10 :-)

If someone can help me I appreciate that.

Regards

**Comment by danmoseley** [comment]
@jhdscript can you give more info -- what are you trying to do? can you share a snippet of code?
also, does this repro with .NET Framework?

**Comment by danmoseley** [comment]
No reply. Closing.
