### ISSUE TITLE
Apple Silicon eventsourceerror failure in jitstress2 CI

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#48786]
From https://dev.azure.com/dnceng/public/_build/results?buildId=1011906&view=ms.vss-test-web.build-test-results-tab&runId=31539994&resultId=109445&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
    tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh [FAIL]
      
      Assert failure(PID 11272 [0x00002c08], Thread: 304052 [0x4a3b4]): Assertion failed 'expectedPrevTree == nullptr || tree->gtPrev == expectedPrevTree' in 'System.Diagnostics.Tracing.EventSource:WriteStringToAllListeners(System.String,System.String):this' during 'Determine first cold block' (IL size 164)
      
          File: /Users/runner/work/1/s/src/coreclr/jit/fgdiagnostic.cpp Line: 2769
          Image: /private/tmp/helix/working/AE2809B4/p/corerun
```

category:correctness
theme:block-opts
skill-level:expert
cost:medium
impact:small

**Comment by hoyosjs** [comment]
As far as I can tell, this is the jit asserting in `fgDebugCheckNodeLinks` saying the statement's tree list is not really consistent.

**Comment by sandreenko** [comment]
`optOptimizeLayout` calls `fgReorderBlocks` that calls `fgOptimizeBranch` that calls `gtPrepareCost` and swaps tree order under JitStress without updating gtNext/gtPrev.
It is interesting that it is arm64 apple specific, can't be reproduced with an altjit.

**Comment by sandreenko** [comment]
The issue is stress-only, we understand why it happens, it won't fail once we enable crossgen2 for arm64 apple so I am pushing it to the future until we have more time for a proper fix for this stress mode.

**Comment by sdmaclea** [comment]
This test is disabled due to this issue.

https://github.com/dotnet/runtime/blob/c32007158a0b6c356c7f0e25d2d8571ff37d029f/src/tests/issues.targets#L736-L738

**Comment by sdmaclea** [comment]
@sandreenko Based on your comment, it sounds like this test can be reenabled now that crossgen2 is enabled.  Do you agree?

**Comment by sandreenko** [comment]
> @sandreenko Based on your comment, it sounds like this test can be reenabled now that crossgen2 is enabled. Do you agree?

Yes, could you please point me to the PR when Crossgen2 was enabled? Do we compile the same methods as we compile on arm64 linux?

If yes then probably https://github.com/dotnet/runtime/issues/53321 should be closed (and the test reenabled) as well, also I have not merged https://github.com/dotnet/runtime/pull/47221/files to fix https://github.com/dotnet/runtime/issues/46456, did somebody else fix it or it is not working with crossgen2?

**Comment by sdmaclea** [comment]
I was basing my comment on @mangod9's e-mail saying crossgen support was removed in favor of crossgen2.  

Perhaps @mangod9 or @AntonLapounov can answer your crossgen2 question about the PR to enable crossgen2 better.

**Comment by davmason** [comment]
Crossgen2 was enabled in the same PR that excluded crossgen: https://github.com/dotnet/runtime/pull/53458

**Comment by sdmaclea** [comment]
I don't think #46456 has been fixed.

**Comment by mangod9** [comment]
just a clarification that crossgen2 has been used to compile Fx libraries for a couple of months now, my PR removed crossgen from building and switched some R2R pipelines to start using crossgen2 instead.

**Comment by EgorBo** [comment]
Seems like the test is not longer disabled and is fixed via https://github.com/dotnet/runtime/pull/86180
