### ISSUE TITLE
Activity ParentId Does Not Format flags

### ISSUE THREAD

**Issue by mwasplund** [dotnet/runtime#48781]
### Description
When using the SetParentId overload that takes in the individual traceId, spanId and flags the ActivityTraceFlags get set correctly. However when calling the lazy ParentId getter the format is hard coded to return no flags ("-00"). Why is this format logic ignoring the ActivityTraceFlags when the Id getter does do the correct formatting? 

https://github.com/dotnet/runtime/blob/970d347a1b06951692cfecc1cc12a500158708b1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L539

https://github.com/dotnet/runtime/blob/970d347a1b06951692cfecc1cc12a500158708b1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L223

https://github.com/dotnet/runtime/blob/970d347a1b06951692cfecc1cc12a500158708b1/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L197

**Comment by tarekgh** [comment]
@noahfalk, do you know the answer to the raised question?

**Comment by noahfalk** [comment]
This looks like an oversight (a bug) to me.

**Comment by tarekgh** [comment]
> This looks like an oversight (a bug) to me.

If we fix it, do you see any issue? I mean like a compat risk?

**Comment by tarekgh** [comment]
@noahfalk I'll go ahead and fix this. let me know if you'll have any concern. of course, you'll get a code review request from me :-)
