### ISSUE TITLE
Memory Mapped files access control classes missing in dotnet core

### ISSUE THREAD

**Issue by ChrisUnityArto** [dotnet/runtime#48793]
Hi!

This Issue https://github.com/dotnet/runtime/issues/941
And this PR https://github.com/dotnet/runtime/pull/465
were both closed because no users had requested the ability to set access rules on memory mapped files.

I'm a user, and I'm requesting it now please.

So is this team : https://stackoverflow.com/questions/57085421/sharing-of-global-in-memory-memory-mapped-file

This is a requirement for me as my team have got some bug reports that our existing code which uses MemoryMapped files CreateNew() method is reporting a file not found error on some user's machines.

The fix suggested here which looks like it would work for us 
https://stackoverflow.com/questions/20363839/opening-a-memory-mapped-file-causes-filenotfoundexception-when-deployed-in-iis

requires dotnet 4 (or 5) but our software is built on dotnet core 3.1.
Would it be possible to add this feature, which it seems some of your dotnet engineers already have an implementation of, please?
@JeremyKuhne @carlossanlop 

Or could anyone suggest a workaround if not?

Cheers,
Chris

**Comment by reejk** [comment]
I ran into the same problem and found a hacky workaround using the `MutexSecurity` api from `System.Threading.AccessControl` (`Mutex` and `MemoryMappedFile` are both kernel objects).

```cs
static void AllowReadWriteAccessToMemoryMappedFile(MemoryMappedFile memoryMappedFile)
{
   const int FILE_MAP_WRITE = 0x0002;
   const int FILE_MAP_READ = 0x0004;

   using var mutex = new Mutex();
   mutex.SafeWaitHandle.Close();
   mutex.SafeWaitHandle = new SafeWaitHandle(memoryMappedFile.SafeMemoryMappedFileHandle.DangerousGetHandle(), false);

   var security = mutex.GetAccessControl();
   security.AddAccessRule(new MutexAccessRule(new SecurityIdentifier(WellKnownSidType.InteractiveSid, null),
      (MutexRights)(FILE_MAP_WRITE | FILE_MAP_READ), AccessControlType.Allow));
   mutex.SetAccessControl(security);
}
```

Tested on .NET 6 and Windows 11

**Comment by ChrisUnityArto** [comment]
Thanks Reejk. Good to know!

Unfortunately the product I was working on has been discontinued and I'm working on something else... !

The version of dotnet we were on is quite old now too so I will close this.
