### ISSUE TITLE
[API Proposal + Bug] Make IListProvider public

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#48805]
## Background and Motivation

I have some collections (specifically weak value collections) where it would be nice to have them implement `ICollection<T>`, but I am extremely hesitant to do that since weak collections are inherently "concurrent" (in the sense that values can be collected by the GC at any time) and thus the very commonly used `ToArray()` and `ToList()` enumerable extension methods have a high probability of returning a collection that is too large and contains some `null` values at the end if my collection implements `ICollection<T>` ([see here](https://github.com/dotnet/runtime/blob/0ac80c3354461936ec153a6d858d927dc4473d29/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L25) for notes on a similar issue with `ConcurrentDictionary`). If I could implement `IListProvider` then I could provide a safe alternative that always returns the correct size array/list when the enumerable extension methods are called.

An additional benefit to making `IListProvider` public would come from being able to make collections like `ConcurrentDictionary` which live in a different assembly than `IListProvider` implement that interface so that the issue noted above could be mitigated and `EnumerableExtensions.ToArray()/ToList()` would be safe to call on it.

**Update:**

It appears that any LINQ methods that use `Buffer` (due to the call on [this line](https://github.com/dotnet/runtime/blob/da801fcf2a97803a5997132c08ba3f646395a5a2/src/libraries/System.Linq/src/System/Linq/Buffer.cs#L38)) like `OrderBy()` are also currently unsafe to use on a `ConcurrentDictionary` and would become unsafe if the weak collections implemented `ICollection<T>`. That's a ***really*** sneaky non-deterministic and very difficult to trace intermittent heisenbug that only shows up in high load situations waiting to happen. It also violates the principle of least surprise given that `ConcurrentDictionary` is safe to enumerate. I certainly did not know that this was an issue - I need to go back and review all my code now. 

This proposal could fix that glaring problem.

## Proposed API

Make `IListProvider` public.

## Risks

None that I can think of.

**Comment by mikernet** [comment]
It appears that any LINQ methods [that use `Buffer`](https://github.com/dotnet/runtime/blob/da801fcf2a97803a5997132c08ba3f646395a5a2/src/libraries/System.Linq/src/System/Linq/Buffer.cs) (i.e. `OrderBy()`) are also currently unsafe to use on a `ConcurrentDictionary` and would become unsafe if the weak collections implemented `ICollection<T>`. This would fix that problem.

**Comment by mikernet** [comment]
If a type says it is safe to enumerate over, LINQ methods need to be safe to call on it. Any "hidden detail" internal optimizations that LINQ methods do should not create bugs. There at least needs to be a mechanism that collection types can use like the `IListProvider` interface that provides a way for those optimizations to work safely or some attribute like `[NoLinqCollectionOptimizations]` to disable those optimizations...anything less is pure insanity IMO.

**Comment by Pzixel** [comment]
Could you provide some code sample with problem you're having right now? I know you have written about "weak collections" and "inherently unsafe" but it's just words. I feel you but it's not quite comprehensive what are you talking about. 

Simple snippet could solve this and show the exact problem and exact value of your proposal.

**Comment by mikernet** [comment]
To be honest I'm more concerned about the `ConcurrentDictionary` issue now, but sorry, let me explain "weak collections" because that probably could have used a better explanation. 

Weak collections are collections that store values with `WeakReference<T>` so those values can be collected at any time. The enumerator for those collections skips over those values so the collection fundamentally suffers from the same issue as `ConcurrentDictionary` when used with LINQ - the `Count` can change at any time and thus the same `Count` / `CopyTo` synchronization problem [mentioned here] https://github.com/dotnet/runtime/blob/0ac80c3354461936ec153a6d858d927dc4473d29/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L25) also applies to the weak collections.

**Comment by Pzixel** [comment]
Right, as I said i've got the idea but still need some concrete example to play with. Please, show some code snippet do demonstrate the problem

**Comment by mikernet** [comment]
The problem is in the BCL. For exampe, `concurrentDictionary.OrderBy(x => x.Value.Something)` is unsafe because of the issue mentioned there. Having the dictionary implement `IListProvider` would solve the issue.

What else do you need to know? Not sure how I can explain that any better, the issue is explained in the code there.

**Comment by Pzixel** [comment]
Could you provide a code snippet to demonstrate `concurrentDictionary.OrderBy(x => x.Value.Something)` is unsafe? I don't see anything unsafe about it

**Comment by mikernet** [comment]
It's a 1 in a million operation concurrency race condition that is documented in the link. As per the link above:

> If the collection size concurrently changes between the array allocation and the CopyTo, we could end up either getting an exception from overrunning the array (if the size went up) or we could end up not filling as many items as 'count' suggests (if the size went down).  This is only an issue for concurrent collections that implement ICollection<T>, which as of .NET 4.6 is just ConcurrentDictionary<TKey, TValue>.

The example is simply concurrently adding objects to the `ConcurrentDictionary` while calling any LINQ operation that uses `Buffer`, such as `ToList()`.

**Comment by Pzixel** [comment]
Well that's correct yet I don't see it as a bug, it's just how multithreading works. You're making an unsynchronized access to shared state and get into some troubles. And this is indeed why `ConcurrentDictionary` doesn't implement interface which is not supposed to work with any kind of multithreading.

**Comment by mikernet** [comment]
Enumerating the dictionary is thread safe, thus calling LINQ methods on it should be thread safe. If it didn't use the `Collection<T>` optimization then it would be thread-safe to call LINQ methods on the `ConcurrentDictionary`. 

The `IListProvider` is already there, it would be incredibly simple to implement its 2 methods on `ConcurrentDictionary` and enable it to be thread safe, so its not "just how multithreading works". Likewise, my collection could work safely with LINQ methods if that interface was exposed.

**Comment by Pzixel** [comment]
Why `ConcurrentDictionary` is special here? LINQ is just not supposed to work in multithreaded environment. Look at this snippet

```cs
void Main()
{
	var list = new List<int>();
	var semaphor = new SemaphoreSlim(1);
	var tasks = Enumerable.Range(1, 100).Select(async i =>
	{
		try
		{	        
			await semaphor.WaitAsync();
			await Task.Delay(1);
			list.Add(i);
		}
		finally
		{
			semaphor.Release();
		}
	});
	
	var items = list.OrderBy(x => x);
	Task.Run (() => Task.WaitAll(tasks.ToArray()));
	
	while (list.Count < 100) {
		items.ToArray().Dump();
	}
}
```

On my machine it eventually fails with `ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')`

You're just not supposed to alter sequence while LINQ is performing a query on it.

**Comment by mikernet** [comment]
> On my machine it eventually fails with ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')

Yes, exactly.

> You're just not supposed to alter sequence while LINQ is performing a query on it.

`ConcurrentDictionary` specifically states it is safe to use the enumerator while reading and writing to it, and that can be achieved by the simple proposed fix above. I don't get why you seem to actively want it to not be thread safe when it can be (and according to the docs should be under enumeration).

The issue isn't with LINQ methods on IEnumerable being unsafe - LINQ is thread safe if the enumerator is thread safe. The issue is that it uses a non-thread-safe `ICollection<T>` optimization internally. It is simple enough to expose `IListProvider` so that concurrent collections can properly implement that in a thread-safe manner, as `ConcurrentDictionary` currently does with its `ToList` and `ToArray` methods, because `IListProvider` is used instead of the `ICollection<T>` optimization if the IEnumerable implements it.

There are literally no downsides to this.

**Comment by Pzixel** [comment]
> The issue isn't with LINQ methods on IEnumerable being unsafe - LINQ is thread safe if the enumerator is thread safe. The issue is that it uses a non-thread-safe ICollection<T> optimization internally. It is simple enough to expose IListProvider so that concurrent collections can properly implement that in a thread-safe manner, as ConcurrentDictionary currently does with its ToList and ToArray methods, because IListProvider is used instead of the ICollection<T> optimization if the IEnumerable implements it.

`List` already implements `IListProvider ` in thread safe manner yet it's not enough to maintain consistency. You need to take a `lock` between count and materialization and this is something you cannot do with interface like `IListProvider`.

**Comment by mikernet** [comment]
Obviously you have to take a lock with `List` - its enumerator is not thread safe. `ConcurrentDictionary` has a thread safe enumerator and thread-safe `ToList` and `ToArray` implementations to satisfy the `IListProvider` implementation it would need to be fully thread safe.

What I have suggested will 100% make ConcurrentDictionary thread-safe with LINQ. I don't know what else to tell you. Try it and see.

**Comment by Pzixel** [comment]
There is no problems with `GetEnumerator`, the problem LINQ is not using **just** GetEnumerator. 

> What I have suggested will 100% make ConcurrentDictionary thread-safe with LINQ. I don't know what else to tell you. Try it and see.

As I said before show the snipped. I have written one for you that shows the problem, show how public IListProvider solves it. Just copy-paste some LINQ method implementation, write your own IListProvider and show it works.

**Comment by mikernet** [comment]
The only problem with using LINQ methods on `ConcurrentDictionary` is that this happens:

```cs
            if (source is ICollection<T> ic)
            {
                int count = ic.Count;
                if (count != 0)
                {
                    // Allocate an array of the desired size, then copy the elements into it. Note that this has the same
                    // issue regarding concurrency as other existing collections like List<T>. If the collection size
                    // concurrently changes between the array allocation and the CopyTo, we could end up either getting an
                    // exception from overrunning the array (if the size went up) or we could end up not filling as many
                    // items as 'count' suggests (if the size went down).  This is only an issue for concurrent collections
                    // that implement ICollection<T>, which as of .NET 4.6 is just ConcurrentDictionary<TKey, TValue>.
                    T[] arr = new T[count];
                    ic.CopyTo(arr, 0);
                    length = count;
                    return arr;
                }
            }
            ```
            
If that didn't happen, and the returned list/array was properly created under proper synchronization, it would work fine. [That's what ConcurrentDictionay.ToArray()` does](https://github.com/dotnet/runtime/blob/0ac80c3354461936ec153a6d858d927dc4473d29/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L721).

So if you simply put ` : IListProvider` on the `ConcurrentDictionary` definition, it will map the `IListProvider`'s `ToArray()` method to its properly synchronized `ToArray` implementations instead of the code above.

**Comment by Pzixel** [comment]
But you still won't be able to use it because `IListProvider`s are explicitely enumerated in LINQ source like here: https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Linq/src/System/Linq/Where.cs#L36

Even if you write your own `WhereConcurrentDictionaryIterator : IIListProvider`  LINQ won't use it becasue it knows nothing about it

**Comment by stephentoub** [comment]
We're not going to make IListProvider public.  It's an internal implementation detail of LINQ that's very fluid in its implementation, with its shrinking or extending it at will,  or even ignoring it in some builds. If there's an issue with LINQ special-casing ICollections that may concurrently change in size,  that needs to be fixed in LINQ by allowing for that possibility,  not by exposing internal implementation details.  Presumably the same concurrency issue you call out exists in .NET Framework as well,  where there is no IListProvider.

**Comment by mikernet** [comment]
Nothing in that code you linked to has anything to do with `ConcurrentDictionary<>` or collections that implement `ICollection<>`. That code tests if it is a `List<>`, which neither of those are, and returns a specialized enumerator for that.

`Where()` doesn't need to know anything about the `Count` so this is a non-issue for `Where`, you don't need to implement a `WhereConcurrentDictionaryIterator`, it would be pointless. `Where` is safe to call on `ConcurrentDictionary` because it doesn't use the problematic `ICollection<>` optimization for converting the collection to a list or array.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/14502. Thanks.

**Comment by Pzixel** [comment]
Thanks for replying. This is an answer I was expecting: https://github.com/dotnet/runtime/issues/14502#issuecomment-175241529

**Comment by mikernet** [comment]
There are multiple issues raised here, I don't think this quite deserves to be closed yet...

If you aren't going to expose `IListProvider` then there should be a simple way for a collection that implements `ICollection<>` to opt-out of `ICollection<>.Count`-based optimizations and just fall back to plain `IEnumerable<>` behavior for LINQ.

If you look at this project: https://github.com/Singulink/Singulink.Collections.Weak

I currently only implement `IReadOnlyCollection<>` because of this issue. Is there a potential option I'm missing? Is there any way to guarantee the GC does not run between the `Count` call and the `CopyTo` call nor during the `CopyTo` call? If so I could make that work, but if GC at that time I can't ensure items in the collection aren't collected before the `CopyTo` operation finishes.

**Comment by mikernet** [comment]
Also, I really think "don't use LINQ with `ConcurrentDictionary` should be much better documented in multiple places in the docs.

**Comment by stephentoub** [comment]
> There are multiple issues raised here

The core issue is that concurrently mutating collections while they're being consumed by anything that checks for ICollection to presize is prone to race conditions. I closed this as a dup because that's exactly what #14502 is about. What is the other issue?

**Comment by mikernet** [comment]
Now that default interface methods are a thing, there could always be a `ToArray()` DIM added to `ICollection<T>` which defaults to the behavior LINQ does, but allows collections to override it. Then you wouldn't need to special case collections and third-party collections can be happy too.

> What is the other issue?

Well, the discussion also includes a different case than just `ConcurrentDictionary`, namely my collections which aren't concurrent in the same way and I can't just take locks to get around the issue like you can with a `ConcurrentDictionary`.

Regardless, it seems like an awful shame that LINQ can't be used on CD when there are solutions that could fix this relatively easily. It's rather odd to have a collection that can be `foreach`ed safely but using LINQ can make it spontaneously explode because of leaky internal implementation details.

**Comment by mikernet** [comment]
Part of the reason the other issue seems to have been closed without resolution is because there wasn't a good option for adding `ToArray()` to `ICollection<>` since it would be a breaking change. With DIMs being here, that's no longer the case and seems like a prime example of where it would be useful.

**Comment by stephentoub** [comment]
> Now that default interface methods are a thing, there could always be a ToArray() DIM added to ICollection<T> which defaults to the behavior LINQ does, but allows collections to override it.

Please feel free to open an issue proposing that.

> Then you wouldn't need to special case collections and third-party collections can be happy too.

_If_ we wanted to address this,  it wouldn't be by special-casing concrete collections.

**Comment by mikernet** [comment]
> If we wanted to address this, it wouldn't be by special-casing concrete collections.
I just said that because it was mentioned in the other issue.

> Please feel free to open an issue proposing that.

I may do that. That said, this issue still has the outstanding topic of what I can do about the weak collections implementing `ICollection<>`

**Comment by stephentoub** [comment]
> That said, this issue still has the outstanding topic of what I can do about the weak collections implementing ICollection<>

You're asking that enumeration see an atomic view,  so in your collection's enumerator you can do:
GetEnumerator() => YourThreadSafeToArray().GetEnumerator()

**Comment by mikernet** [comment]
My enumerator is safe. The issue is that `GetEnumerator()` does not get called if my collection implements `ICollection<T>` because of the `Count/CopyTo()` optimization issue. I also asked this question above:
>  Is there any way to guarantee the GC does not run between the Count call and the CopyTo call nor during the CopyTo call? If so I could make that work

The only issue is a GC collection happening that removes items from the collection.

**Comment by stephentoub** [comment]
> The only issue is a GC collection happening that removes items from the collection.

Why is that an issue? Implementations (well beyond LINQ, List, etc.) check the count and then do a copy.  Adding to a ConcurrentDictionary could be a problem, but I don't see why removing from a ConcurrentDictionary would be a problem.

**Comment by mikernet** [comment]
It's a problem because the array/list would contain a bunch of default values at the end of it that aren't actually in the collection.

**Comment by stephentoub** [comment]
> It's a problem because the array/list would contain a bunch of default values at the end of it that aren't actually in the collection.

That means your CopyTo is copying the full list rather than what it knows to be the current count? That sounds broken.

**Comment by mikernet** [comment]
No, it goes like this:

```cs
var array = new[collection.Count];
// GC runs here on weak collection, or an item is removed from the ConcurrentDictionary
collection.CopyTo(array); // weak collection / ConcurrentDictionary have less items so array now has a bunch of default values at the end.
```

**Comment by mikernet** [comment]
So ideally, I would like to ensure the GC does not run where the `// GC runs here` line is, but I have a feeling that isn't possible.

**Comment by Pzixel** [comment]
Empty elements are still elements and still have to be copied.

**Comment by stephentoub** [comment]
Oh, you meant the resulting array,  not the array/list in your collections implementation. I thought you were saying stale values from your collection were being copied,  which is what I was commenting on at broken.  Yes,  you could end up with default values at the end.

**Comment by mikernet** [comment]
I don't know what you are saying @Pzixel.

**Comment by Pzixel** [comment]
GC doesn't remove anything, it's not how it works. It only make some `WeakRef` have null `Target` but that's it. And I don't see why they shouldn't be copied via `CopyTo` method - it's just bunch of regular structures.

**Comment by mikernet** [comment]
Because the enumerator in my collections do not return collected items, it skips over them. I know how the GC works 😋

**Comment by mikernet** [comment]
I think I'm just going to go with `IWeakCollection` / `IReadOnlyWeakCollection` interfaces for now and the user can just `ToList()` the weak collection or whatnot if they need to pass it to something expecting an `ICollection`, probably safer that way anyway for interoperating with other code that depends on particular `ICollection` behavior.

I still think that `ConcurrentDictionary` with LINQ should be fixed though, it just seems like the only sensible thing to do given that it has a thread-safe enumerator. I'll probably open up another issue for that with the `ICollection<T>.ToArray()` DIM idea as per your suggestion.
