### ISSUE TITLE
Add support for .NET 6 run-time configuration settings for mobile targets

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#48811]
.NET Core support setting application configuration using various mechanisms as described at https://docs.microsoft.com/en-us/dotnet/core/run-time-config/. Such settings need to be correctly propagated to [AppContext](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext) class as well as to internal runtime variables for mobile applications.

**Comment by lambdageek** [comment]
@SamMonoRT @fanyang-mono this is a dupe of https://github.com/dotnet/runtime/issues/49237, right?

**Comment by SamMonoRT** [comment]
> @SamMonoRT @fanyang-mono this is a dupe of #49237, right?

Yes, it is a dupe and that one has more detailed information/tracking. Can close this out.

**Comment by fanyang-mono** [comment]
This feature has been tracked by https://github.com/dotnet/runtime/issues/49237
