### ISSUE TITLE
CoreClr JIT.Directed work item failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#48820]
https://dev.azure.com/dnceng/public/_build/results?buildId=1013481&view=ms.vss-test-web.build-test-results-tab&runId=31577492&resultId=102817&paneView=attachments

Configuration: `CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open`

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48808-merge-0d769ddfc6e6415c98/JIT.Directed/console.f079786f.log?sv=2019-07-07&se=2021-03-18T13%3A25%3A55Z&sr=c&sp=rl&sig=NtuNZIRCHMAKSbmOzDfiqmfTwdCskLdNE1iQwJKfGqk%3D

```
D:\h\w\B09908FA\w\A19F0910\e>dotnet D:\h\w\B09908FA\p\xunit\xunit.console.dll JIT\Directed\JIT.Directed.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Directed 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 5.0.0)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Comment by echesakovMSFT** [comment]
Also observed with different work item during https://dev.azure.com/dnceng/public/_build/results?buildId=1014188 

https://helix.dot.net/api/2019-06-17/jobs/fdc3b790-33f7-481e-a981-a0b527ecedf3/workitems/JIT.HardwareIntrinsics/console
```
D:\h\w\B2C309DA\w\A26B08C8\e>dotnet D:\h\w\B2C309DA\p\xunit\xunit.console.dll JIT\HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 5.0.0)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

Both work items were running on DDARM64-181 so I would guess that there an issue with this particular machine 
cc @MattGal

**Comment by echesakovMSFT** [comment]
One more datapoint here - https://dev.azure.com/dnceng/public/_build/results?buildId=1013993

Same machine - JIT.jit64.hfa
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48835-merge-f3482fd732c2402083/JIT.jit64.hfa/console.3ce9d093.log?sv=2019-07-07&se=2021-03-18T20%3A00%3A47Z&sr=c&sp=rl&sig=YNFkQdnOvxwZa%2FSejrXH1BFzw7dq4%2F1cmpRKARbI7sI%3D

**Comment by echesakovMSFT** [comment]
Opened https://github.com/dotnet/core-eng/issues/12343

**Comment by echesakovMSFT** [comment]
This should be resolved by now (https://github.com/dotnet/core-eng/issues/12343#issuecomment-786952638)
