### ISSUE TITLE
Rename IServicesCollection

### ISSUE THREAD

**Issue by TofuBug** [dotnet/runtime#48840]
## Background and Motivation

`IServiceCollection `seems to me to act more like the `IBuilders ` `ILoggingBuilder`, `IHostBuilder `etc

You can't even easily access the existing "Services" added unless you use GetEnumerator() where as on the other end when an IHost is completely built you have a direct property to the Services added

## Proposed API

Change the name to 

IServicesBuilder

Leave everything else the same

## Usage Examples

hostBuilder.ConfigureServices(servicesBuilder => servicesBuilder.AddLogging())

## Alternative Designs

I guess you could change all the Builders to something like

`IHostSettingsCollection ` or `ILoggingSettingsCollection`

## Risks

I would hope just people who are used to this being the odd one out in the whole `IHostBuilder `stack of building up an `IHost ` forgetting its a proper builder as opposed to an arbitrary collection.

**Comment by davidfowl** [comment]
No we're not going to rename it, it's a massive breaking change for little value.

**Comment by TofuBug** [comment]
> No we're not going to rename it, it's a massive breaking change for little value. Though, I agree with you, if we could go back we'd probably rename it.

While I respect your position its not like the language hasn't created alternatives to inconsistently named classes, methods etc in the past leaving the old one available for a time to let people adjust and eventually deprecating it. That's happend many many many times since .NET 1.0 dropped.

It's really no skin off my back I'm just pointing out the inconsistency of its naming convention around all the other similarly behaving interfaces.

**Comment by davidfowl** [comment]
I appreciate it but its unrealistic at this point. I have lots of namespaces I'd like to rename as well but its extremely hard to justify breaking changes like this.
