### ISSUE TITLE
[wasm] AOT app build breaks with `InvariantGlobalization=true`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#48847]
To reproduce with master:

1. add `<InvariantGlobalization>true</InvariantGlobalization>` to `src/mono/sample/wasm/console/Wasm.Console.Sample.csproj`,
2. build `make clean build AOT=1`

This fails with:

```
Task "RunWithEmSdkEnv" (TaskId:119)
Task Parameter:Command=emcc --profiling-funcs -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s USE_ZLIB=1  -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_createPath', 'FS_createDataFile', 'cwrap', 'setValue', 'getValue', 'UTF8
Task Parameter:EmSdkPath=/Users/radical/dev/r3/src/mono/wasm/emsdk (TaskId:119)
Using Command: bash -c 'source /Users/radical/dev/r3/src/mono/wasm/emsdk/emsdk_env.sh > /dev/null 2>&1 && emcc --profiling-funcs -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s USE_ZLIB=1  -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['c
bash -c 'source /Users/radical/dev/r3/src/mono/wasm/emsdk/emsdk_env.sh > /dev/null 2>&1 && emcc --profiling-funcs -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=1 -s USE_ZLIB=1  -s FORCE_FILESYSTEM=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'FS_crea

error: undefined symbol: u_errorName (referenced by top-level compiled C/C++ code) (TaskId:119)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols (TaskId:119)
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0` (TaskId:119)
warning: _u_errorName may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library (TaskId:119)
error: undefined symbol: udata_setCommonData (referenced by top-level compiled C/C++ code) (TaskId:119)
warning: _udata_setCommonData may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library (TaskId:119)
Error: Aborting compilation due to previous errors (TaskId:119)

emcc: error: '/Users/radical/dev/r3/src/mono/wasm/emsdk/node/12.18.1_64bit/bin/node /Users/radical/dev/r3/src/mono/wasm/emsdk/upstream/emscripten/src/compiler.js /var/folders/7c/zpmy8k_d4d1grky_s154kk640000gp/T/tmpmw4p7957.txt' failed (1) (TaskId:119
```

This seems to be caused by https://github.com/dotnet/runtime/commit/3473d30d76a 
```
Make sure pal_icushim_static.c is linked in even if no symbols are us…
…ed from it, so the EMSCRIPTEN_KEEPALIVE functions in it are actually kept.
```

It works before this commit, and breaks with it.

/cc @vargaz @lewing

**Comment by steveisok** [comment]
If I run the Invariant tests locally with `EnableAggressiveTrimming=true` and `RunAOTCompilation=true`, I hit:

```
 error: undefined symbol: u_errorName (referenced by top-level compiled C/C++ code)
  warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
  warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
  warning: _u_errorName may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
  error: undefined symbol: u_getVersion (referenced by top-level compiled C/C++ code)
  warning: _u_getVersion may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
  error: undefined symbol: udata_setCommonData (referenced by top-level compiled C/C++ code)
  warning: _udata_setCommonData may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
  ```

**Comment by vargaz** [comment]
This is because src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs calls
Interop.GetICUVersion () which causes references to icu functions.

**Comment by steveisok** [comment]
> This is because src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs calls
> 
> Interop.GetICUVersion () which causes references to icu functions.
> 
> 

Yup, that appears to be it.  If I removed that method the tests pass.

**Comment by lewing** [comment]
Sound like aggressive trimming isn't preserving PlatformDetection members correctly when they are only accessed from the attribute?  That might explain several problems.

**Comment by lewing** [comment]
This isn't related to PlatformDetection, @radical was able to reproduce it in the console sample with native linking turned on.

**Comment by steveisok** [comment]
Interesting.  For the invariant tests, I was able to pass if I completely removed the reflection from `GetICUVersion`

**Comment by lewing** [comment]
> Interesting. For the invariant tests, I was able to pass if I completely removed the reflection from `GetICUVersion`

This is exactly why #49492 is needed, it isn't safe to completely condition on InvariantMode.  Assuming that the platform check was properly retained, pinvoke-table.h would root  GlobalizationNative_GetICUVersion and everything would function properly.  Without #49492 you end up with missing symbols.
