### ISSUE TITLE
Investigate why StackFrameHelperTest Trimming test fails on mono

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#48849]
PR https://github.com/dotnet/runtime/pull/48429 added the browser-wasm leg to our Trimming tests and this was the first time that our trimming tests would run against the mono runtime. One of the findings when analyzing the results was that the test [StackFrameHelperTest](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime/tests/TrimmingTests/StackFrameHelperTest.cs) was failing due to the fact that it wasn't able to retrieve the line information from a newly created StackTrace object. The test was disabled on that same PR due to the fact that the test's intention was actually to validate that a linker annotation was preserving the right methods in order for line information to be retrieved correctly, and this annotation was specific to coreclr's runtime, so it didn't make sense to run it on Mono. That said, we should take a look and see why line information isn't able to be retrieved when running on Mono in case this is not a known issue or by design.

**Comment by joperezr** [comment]
FYI: @marek-safar

**Comment by dakersnar** [comment]
Is this the correct area label for this issue?

**Comment by tommcdon** [comment]
This is an older issue, and we have had no known customer issues raised because of it.  Closing until we have more feedback.
