### ISSUE TITLE
Clean up TrimmingTests infrastructure

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#48848]
There are a few things in our TrimmingTests that could be cleaned up.

https://github.com/dotnet/runtime/blob/121b732e8b17470fd1cb7df26c32bfce415f966e/eng/testing/linker/project.csproj.template#L12-L22

Also, once we have an SDK with https://github.com/dotnet/sdk/pull/16094 (which I believe will be a 6.0-preview3 sdk), we can remove:

https://github.com/dotnet/runtime/blob/121b732e8b17470fd1cb7df26c32bfce415f966e/eng/testing/linker/SupportFiles/Directory.Build.targets#L20-L30

And just generate `IsTrimmable=true` assembly metadata on the console apps, which will ensure they are fully trimmed.

cc @joperezr

**Comment by ViktorHofer** [comment]
Moving to issues to area-Meta as it this isn't actionable by the infra team.
