### ISSUE TITLE
Marshal.GetExceptionCode() and Marshal.GetExceptionPointers() does not return exception data when awaited within a finally block

### ISSUE THREAD

**Issue by jerryk414** [dotnet/runtime#48845]
### Description

When using `Marshal.GetExceptionCode()` and `Marshal.GetExceptionPointers()` from within a finally block that contains an `await` statement, the methods return values indicating that no exception has occurred - even if one has.

Reproducing this is very easy:

```csharp
public async Task SomeMethod()
{
   try
   {
      throw new Exception();
   }
   finally
   {
      var exceptionCode = Marshal.GetExceptionCode();
      var exceptionPtr = Marshal.GetExceptionPointers();

      // Notice - if you comment out the line below, the exceptionCode and exceptionPtr will now be
      // the expected values.  If left, those values will basically be empty
      await Task.CompletedTask;
   }
}
```

### Configuration

- netcoreapp3.1
- Windows 10
- x64

### Regression?
N/A

### Other information
This is such a strange issue.. i have a feeling it's due to the internal implementations of await, within finally blocks specifically.  Is there a workaround?

**Comment by jkotas** [comment]
This is expected behavior. These two methods are [exposed for compiler support of SEH only](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptioncode?view=net-5.0). 

>  it's due to the internal implementations of await, within finally blocks specifically. 

Correct.

> Is there a workaround?

There is no workaround.

**Comment by jerryk414** [comment]
@jkotas I've seen a variety of tickets related to these two methods, all basically centered around the purpose of adding support for transactional disposables, where the disposable has knowledge of exceptions.

That was why i looked into this - i'm just going with a manually implemented try/catch/finally handler, but i would have loved the syntactical sugar of a using block.

Are there any plans to _ever_ release an IDisposable/IAsyncDisposable implementation that is provided with exception information upon disposing?

**Comment by jkotas** [comment]
These two methods are very specific to interop with SEH on Windows. You cannot get the managed exception in flight through them. I do not see how they can help with implementation of transactional disposables.

**Comment by jkotas** [comment]
> variety of tickets related to these two methods, all basically centered around the lack of support for transactional disposables

Could you please share links to those tickets?

**Comment by jerryk414** [comment]
@jkotas

They would help by allowing you to close a transaction upon the disposing of the disposable.  So if you want to do collection of actions that occurs as a single transaction and you only want to push the transaction forward if no exceptions have occurred, that would be a use case.

See below:

```csharp
public async Task SomeExample()
{
    await using (ITransaction transaction = _someProvider.GetTransaction())
    {
        Foo bar1 = new Foo();
        transaction.Push(bar1);

        Foo bar2 = new Foo();
        transaction.Push(bar2);

        // If an exception occurs, we want the transaction to ignore *everything*, otherwise
        // We want to transaction to complete and everything to be committed upon the closing of the transaction (once diposed)
        SomeExceptionOccursHere();

        Foo bar3 = new Foo();
        transaction.Push(bar3);
    }
}
```

The best discussions on this have been here:
https://github.com/dotnet/csharplang/discussions/216
https://github.com/dotnet/csharplang/discussions/3025

Here are two other discussions i've found - there are plenty more out there:
https://stackoverflow.com/questions/220234/intercepting-an-exception-inside-idisposable-dispose
https://stackoverflow.com/questions/2830073/detecting-a-dispose-from-an-exception-inside-using-block
