### ISSUE TITLE
Losing information when logging arrays in structured logging

### ISSUE THREAD

**Issue by pergardebrink** [dotnet/runtime#48873]
### Description
When logging with ILogger and providing an array for a named variable in structured logging, the Microsoft extensions seems to automatically convert the array to a concatenated string. This is fine for the formatted message, but the state with all the properties will not get the array representation. 

```
var listOfNumbers = new[] { 1, 2, 3, 4, 5 };
_logger.LogInformation("The list of numbers are {Numbers}", listOfNumbers);
```
Produces:
```
The list of numbers are 1, 2, 3, 4, 5
```
But the state passed on to the logging provider also have the array as a concatenated string instead of the array 
```
Key = "Numbers"
Value = "1, 2, 3, 4, 5"
```
### Configuration
Tried on .NET Core 3.1 and .NET 5 with Microsoft.Extensions.Logging 3.1.10 and 5.0.0 and have NLog as a logging provider (although NLog is not involved in the issue)

### Regression?
Seems to have been the same in current and previous version

### Other information
If this is intentional and no intention to change it, Is there a way to get the raw state as it was passed to the logger? The reason is that I want to pass this on to Datadog that can consume structured logging where arrays like this can be processed further when I get the "raw" form.

I see that the code here https://github.com/dotnet/runtime/blob/df2b4f2a4d796684cd4b448a8fca5224c443daf3/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L204 is what is converting the array to a comma separated string (and replacing the current value), but is there any way I can get the raw value down to the logging provider?

**Comment by pergardebrink** [comment]
I see now that my issue looks like a duplicate of https://github.com/dotnet/runtime/issues/36025

**Comment by maryamariyan** [comment]
closing as duplicate
