### ISSUE TITLE
Implement Edit and Continue on other platforms

### ISSUE THREAD

**Issue by SparkyTD** [dotnet/runtime#48887]
Since the new .NET versions seems to focus on cross-platform support, I find it very surprising that such an important feature has not been implemented yet on platforms other than Windows. For many developers, including me, this is unfortunately a deal-breaker. We are being forced to either go back to Windows, develop our apps in a VM or just give up on E&C.

On behalf of all C# programmers on linux, I am asking you to add this feature, because it will make our lives a lot easier.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/12409. Thanks.
