### ISSUE TITLE
crossgen2 SuperPMI collections failing due to unimplemented APIs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#48888]
After https://github.com/dotnet/runtime/pull/48534, crossgen2 collections stopped working due to unimplemented JIT-EE interface methods in crossgen2. See more details in the discussion in https://github.com/dotnet/runtime/pull/48578.

**Comment by davidwrighton** [comment]
To my knowledge, this works now.

**Comment by BruceForstall** [comment]
> To my knowledge, this works now.

@davidwrighton I believe that's not true. The JIT still doesn't call these APIs under crossgen due to this issue:

https://github.com/dotnet/runtime/blob/a8926ba6ecadb259694e09650225d9094081a7df/src/coreclr/jit/compiler.cpp#L5592-L5598

And https://github.com/dotnet/runtime/pull/48578 is still open
