### ISSUE TITLE
The same request, the same settings. Httpclient in NETCORE is better than framework slow

### ISSUE THREAD

**Issue by xgbzsc** [dotnet/runtime#48896]
The same request, the same settings. Httpclient in NETCORE is better than framework slow

 var httpClientHandler = new HttpClientHandler();
            httpClientHandler.MaxConnectionsPerServer = 512;//very important!!
          
                httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, error) => true;
           
            var httpClient = new HttpClient(httpClientHandler);
            httpClient.DefaultRequestHeaders.Connection.Add("keep-alive");
            httpClient.DefaultRequestHeaders.ExpectContinue = false;
            for (int i = 0; i < 100; i++)
            {
                Stopwatch tongdaoWatch2 = new Stopwatch();
                tongdaoWatch2.Start();
                var requestUri = "https://v.juhe.cn/verifybankcard4/query?key=&bankcard=&realname=&idcard=&mobile=";
                var httpResponseMessage = await httpClient.GetAsync(requestUri);
                tongdaoWatch2.Stop(); ;
                Console.WriteLine("renrenid验证耗时:" + tongdaoWatch2.ElapsedMilliseconds);
            }

**Comment by xgbzsc** [comment]
How long can there be a reply? The project is waiting to go online。This is very important

**Comment by davidfowl** [comment]
If you have a paid support contract, you can call Microsoft support. Other than that, it'll be when somebody wakes up and triages the issue. 

You can load the symbols from the framework and step into the code if you're blocked. It might give you some clues. Maybe it's something to do with that website specifically.

**Comment by jcotton42** [comment]
Since you're making an issue about performance you should include some numbers to back up what you've found. You'll want to take a look at [BenchmarkDotNet](https://benchmarkdotnet.org/), it will help you get consistent numbers you can share here.

**Comment by stephentoub** [comment]
FWIW, I tried your repro on both .NET Framework 4.8 and .NET 5.0.  On the former I got an average time of 347ms, and on the latter I got an average time of 337ms.  I'm not seeing anything problematic.

**Comment by xgbzsc** [comment]
Run directly in visual studio,It may have something to do with visual studio。There is no problem opening the application directly in the folder。The way visual studio works at different runtime may be different。

**Comment by xgbzsc** [comment]
> FWIW，我在。NET框架4.8和。NET 5.0上都尝试过您的重新编程。前者的平均时间为347ms，后者的平均时间为337ms。我没有看到任何问题。

Run directly in visual studio,It may have something to do with visual studio。There is no problem opening the application directly in the folder。The way visual studio works at different runtime may be different。

**Comment by xgbzsc** [comment]
> FWIW, I tried your repro on both .NET Framework 4.8 and .NET 5.0. On the former I got an average time of 347ms, and on the latter I got an average time of 337ms. I'm not seeing anything problematic.

Run directly in visual studio,It may have something to do with visual studio。There is no problem opening the application directly in the folder。The way visual studio works at different runtime may be different。

**Comment by codeex** [comment]
Run independently, Dont in vs ！

**Comment by xgbzsc** [comment]
> Run independently, Dont in vs ！

Thank you very much，I've never seen such a big difference in framework before。

**Comment by stephentoub** [comment]
Closing, as there isn't a runtime concern here. Thanks.
