### ISSUE TITLE
Support Uniform Device API

### ISSUE THREAD

**Issue by furesoft** [dotnet/runtime#48898]
## Background and Motivation

There are many different libraries to communicate with bluetooth, audio output, microphone etc. It is really hard for cross platfrom applications to choose the right one, because one library is used for one platform.

## Proposed API
```
bool Device.IsAvailable<TDevice>() where TDevice : IDevice
TDevice GetDevice<TDevice>() where TDevice : IDevice
IDevice:
     void Open()
     void Close()
     Stream GetOutputStream()
     Stream GetInputStream();
```

## Usage Examples

``` C#
if(Device.IsAvailable<SpeakerDevice>()) {
     var speaker = Device.GetDevice<SpeakerDevice>();
     var speakerStrm = speaker.GetOutputStream();

     //write audio to speakerStrm
    //...     
}
```
## Device Ideas
BluetoothDevice
SpeakerDevice
MicrophoneDevice
HIDDevice

## Risks

It is hard work to implement all Devies on all supported platforms. But there should be no breaking changes

**Comment by john-h-k** [comment]
This isn't a full API proposal. You need to include IDevice

**Comment by furesoft** [comment]
> This isn't a full API proposal. You need to include IDevice

that was a mistake

**Comment by john-h-k** [comment]
It still isn't. Is your entire API proposal these 2 methods? If so, why do they need to exist? There need to at least be a few devices included in the initial proposal 😄

**Comment by john-h-k** [comment]
Equally, if these devices do exist - why do we need this API? Why can a consumer not just do

```cs

if (BluetoothDevice.IsSupported)
{
    var bluetooh = new BluetoothDveice();
}
```

**Comment by furesoft** [comment]
thats a point, so we only need the device implementations

**Comment by huoyaoyuan** [comment]
The kind of devices are numerous, but BCL isn't making concept of any of them. It should be suitable for a layer beyond BCL.
