### ISSUE TITLE
Support for Alternative Services

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#489]
This is for implementing [RFC 7838](https://tools.ietf.org/html/rfc7838) -- the Alt-Svc header/frame.

Alt-Svc enables moving requests from one server to another, possibly over a different protocol. Alt-Svc enables two key scenarios:

The first scenario is centered around load balancing. If a server detects it is overloaded, it can advertise alternate servers it would like the client to use instead. This can be particularly impactful in HTTP/2 and HTTP/3 which tend to have a single long-term connection which can make load balancing challenging.

The second scenario is HTTP/3 discovery. Without prior knowledge of HTTP/3 support, the standard method of establishing a connection is to first use HTTP/1 or HTTP/2, and the server provides an Alt-Svc for HTTP/3.

## Implementation plan

This will add support for Alt-Svc in both header form and in HTTP/2 frame form. This will come in two PRs: first, the general Alt-Svc change that works with only HTTP/1 and HTTP/2 (with a clear path to adding HTTP/3), addressing the load balancing scenario. Second, adding HTTP/3 support.

Alt-Svc can contain multiple alternative authorities, given in order of priority. HttpClient will scan this list and pick the first eligible entry. To be eligible, an authority must use a supported protocol and not cause a transition between plaintext and secure. Note: Alt-Svc allows the client to e.g. try the first entry, then try the 2nd entry if the first fails -- this is being left as a future enhancement as there is not enough data yet on how this feature will be used, though I can see a server advertising "try H3 first, then try H2 if that doesn't work".

HttpClient will prioritize steady state latency: rather than blocking future requests on establishing an Alt-Svc connection, it will open a connection in the background and continue to use the existing connections until the new connection is successfully established. Once the new connection is established, the old connection will be closed as soon as all outstanding requests are completed. If a connection fails, the failure will be cached for some period of time to prevent constant retries on every request. Authorities can direct you to further alternates, ask you to stop using alternates all together, or timeout via the Max Age parameter. Each case of this will cause such a transition to take place.

Alternate servers *should* be able to handle all requests for the origin server, regardless of URL path/etc., however the requests can fail with code 421 to indicate that the authority was incapable of handling the request. HttpClient will handle this by transitioning away from the alternate authority and back to the original authority, marking that alternate as unreliable to prevent further use for some period of time, and retrying the request (421 means the request was not processed, so idempotency is not a concern).

When a secure connection is being used, SNI must be given for the original URL (origin), not the new server (authority). The authority must then in turn present a certificate that is valid for the origin.

### Open questions

Configurability -- do we make this configurable (I say YES) and what is the default (I say ENABLED)? Do we have a min-version and max-version so that the user can prevent downgrading from e.g. H2 to H1 even when the server requests it?

Establishing a connection in the background means additional resource usage that might negatively impact customers who are making a single request and then disposing of the handler. A tradeoff might be to wait for the next request after the Alt-Svc is seen to start establishing the new connection.

CC @dotnet/http3

**Comment by Tratcher** [comment]
> This will come in two PRs: first, the general Alt-Svc change that works with only HTTP/1 and HTTP/2 (with a clear path to adding HTTP/3), addressing the load balancing scenario. Second, adding HTTP/3 support.

Do we actually need to implement the load balancing scenario? It sounds more complicated than the H3 discovery scenario that we actually do need.

Put another way, if you were to scope this to only the H3 discovery scenario, would you do it differently and/or would it be significantly less work? E.g. only attempt to follow alt-service redirects for h3, and only if not already on h3?

> Configurability -- do we make this configurable (I say YES) and what is the default (I say ENABLED)? Do we have a min-version and max-version so that the user can prevent downgrading from e.g. H2 to H1 even when the server requests it?

This is a general HttpClient question we've been discussing. Right now the request version is treated as a max version that allows graceful downgrades. This should be discussed in its own issue, I don't think alt-service would have a separate configuration for this.

On another note, would you update the request url field to reflect the redirection similar to how a 301 redirect does?

**Comment by davidsh** [comment]
>On another note, would you update the request url field to reflect the redirection similar to how a 301 redirect does?

I think that would be useful here. I.e. update `HttpRequestMessage.RequestUri`.

**Comment by scalablecory** [comment]
> Do we actually need to implement the load balancing scenario? It sounds more complicated than the H3 discovery scenario that we actually do need.
> 
> Put another way, if you were to scope this to only the H3 discovery scenario, would you do it differently and/or would it be significantly less work? E.g. only attempt to follow alt-service redirects for h3, and only if not already on h3?

It's better thought of as a single solution that happens to work for both load balancing and H3, while not being specifically designed for either in particular. Those are just the two main scenarios we'll benefit in by having it, not two separate parts of a spec.

It's very different from H2C upgrade. There's very little else we can shave off by targeting only H3 upgrade while still being a good citizen re: RFC compliance.

> would you update the request url field to reflect the redirection similar to how a 301 redirect does?

The RFC is explicit about not doing this here -- it directs implementations to avoid presenting the alternate service as "something different" and states that Alt-Svc is not to be thought of as a redirect: the origin (url) is not changing, only the authority (server) which serves it.

**Comment by pentp** [comment]
The load balancing scenario is actually quite important for microservices. Currently it often makes sense to use HTTP/1.1 because H2 (and H3) clients don't support gracefully draining connections from specific service instances and H2 additionally has TCP head-of-line blocking issues.

**Comment by scalablecory** [comment]
@pentp do you have some examples of where Alt-Svc is being used for load balancing of APIs today?

**Comment by pentp** [comment]
No, what I mean is that lack of such load balancing support is forcing us to use HTTP/1.1 and I hope this Alt-Svc support here paves the way for H2 and H3 use in microservices.

**Comment by pentp** [comment]
Does closing this mean that there will be no Alt-Svc support for load balancing?
