### ISSUE TITLE
SuperPMI collection broken

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#48919]
https://dev.azure.com/dnceng/internal/_build/results?buildId=1015876&view=results

Error:
```
'CoreclrArguments' object has no attribute 'jitoption'
```

This is due to: https://github.com/dotnet/runtime/pull/48738

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Looks like `jitoption` needs to be a common option.
