### ISSUE TITLE
[MONO] Add AOT compiler to desktop runtime pack

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#48927]
The runtime pack should include the mono-sgen binary for use as an AOT compiler; this simplifies a lot of testing and benchmarking tasks. It might also be useful for developers who want to test any AOT stuff with out using an iOS/Android simulator.

**Comment by lewing** [comment]
I think the plan is to move to using the AOT compiler nugets to pull in the compiler, and remove the included one?

**Comment by lewing** [comment]
cc @steveisok

**Comment by steveisok** [comment]
@naricc I responded to you earlier w/o thinking and skipped a few important details.  The pattern for our AOT compilers moving forward is to not be bundled inside the runtime pack, but within their own nuget package.  At the end of the day, it'll be similar and I don't think generating an osx mono-aot-cross binary is going to be that big of a thing.

You would add something like `<BuildMonoAOTCrossCompiler Condition="'$(TargetsOSX)' == 'true'">true</BuildMonoAOTCrossCompiler>` below https://github.com/dotnet/runtime/blob/e4a981c1effca9110a15096ccc9ccb052b1abc3f/src/mono/mono.proj#L39 .  That may get you most of the way.  Then, I think it's about modifying the installer from there.  @directhex would be the best person to ping.

**Comment by naricc** [comment]
So, mono-sgen is already the non-cross AOT compiler, and we already build it right? Should I close out this issue then?

**Comment by steveisok** [comment]
We build it, but do not bundle it.  If we want to use it outside of runtime, then we should package it like the mobile ones.

**Comment by naricc** [comment]
Package it like the mobiles ones means put mono-sgen in its own nuget then?

**Comment by steveisok** [comment]
Presumably.  I'd like to think it's as simple as that. 

/cc @akoeplinger

**Comment by SamMonoRT** [comment]
@naricc @akoeplinger - is this going to be possible by Preview 7 cutoff ?

**Comment by naricc** [comment]
I don't think it is hard to do, but I have never actually done this kind of work before, so it's hard for me to give an accurate estimate. If we want to prioritize it, I don't see why it wouldn't be possible though.

**Comment by SamMonoRT** [comment]
This is a nice to have feature. Moving to 7.0, not required for 6.0.0

**Comment by naricc** [comment]
This is a useful feature, but not something we have been able to prioritize.

**Comment by kotlarmilos** [comment]
@akoeplinger Is this a requirement for .NET 8, or can it be postponed after RC1/RC2?

**Comment by kotlarmilos** [comment]
Closing this issue due to low impact and high effort.
