### ISSUE TITLE
Move unsupported non Windows tests from tests/testsFailingOutsideWindows.txt to tests/testsUnsupportedOutsideWindows.txt 

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/runtime#4895]
In the tests/testsFailingOutsideWindows.txt  most of the failing tests are non-supported tests on non Windows platforms. Most if the failures are in tests using the varargs calls (not supported on non-Windows) or trying to load kernel32.dll/user32.dll and/or other native dlls not presen on non Windows platforms.

**Comment by AaronRobinsonMSFT** [comment]
These files are no longer used.
