### ISSUE TITLE
System.Runtime.Intrinsics: Backport MS Docs documentation to triple slash

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#48971]
We are working on a [new documentation process plan](https://github.com/dotnet/runtime/issues/44969#issuecomment-788536998), in which the main objective is to make triple slash comments the source of truth for documentation, instead of MS Docs: We want developers/maintainers to have an easier time maintaining the documentation for their APIs.

You can use the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to automate the backport process: Run the tool targeting the assembly, then submit a PR with the changes.

You can find detailed instructions for the backporting process [here](https://github.com/carlossanlop/DocsPortingTool/blob/master/BackportInstructions.md).

Area owners are free to decide if they want to address this in 6.0 or in Future.

**Comment by tannergooding** [comment]
The docs here look to already be inline as they were seeded from the /// in the first place
