### ISSUE TITLE
System.IO.Pipelines: Backport MS Docs documentation to triple slash

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#48995]
We are working on a [new documentation process plan](https://github.com/dotnet/runtime/issues/44969#issuecomment-788536998), in which the main objective is to make triple slash comments the source of truth for documentation, instead of MS Docs: We want developers/maintainers to have an easier time maintaining the documentation for their APIs.

You can use the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to automate the backport process: Run the tool targeting the assembly, then submit a PR with the changes.

You can find detailed instructions for the backporting process [here](https://github.com/carlossanlop/DocsPortingTool/blob/master/BackportInstructions.md).

Area owners are free to decide if they want to address this in 6.0 or in Future.

**Comment by BrennanConroy** [comment]
@ericstj Would it be possible to piggy-back off someone on your team who may be doing this in other areas?

**Comment by ericstj** [comment]
@carlossanlop and @safern are driving this effort.  I believe the process is well documented and makes things significantly better for documenting the libraries.  I believe it's important for area owners to be involved in reviewing the results for validity.

**Comment by ericstj** [comment]
I went ahead and gave it a try to dogfood the process.  Have a look at the PR. https://github.com/dotnet/runtime/pull/49118
