### ISSUE TITLE
System.Net: Backport MS Docs documentation to triple slash

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#48992]
We are working on a [new documentation process plan](https://github.com/dotnet/runtime/issues/44969#issuecomment-788536998), in which the main objective is to make triple slash comments the source of truth for documentation, instead of MS Docs: We want developers/maintainers to have an easier time maintaining the documentation for their APIs.

You can use the [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) to automate the backport process: Run the tool targeting the assembly, then submit a PR with the changes.

You can find detailed instructions for the backporting process [here](https://github.com/carlossanlop/DocsPortingTool/blob/master/BackportInstructions.md).

Area owners are free to decide if they want to address this in 6.0 or in Future.

**Comment by carlossanlop** [comment]
@dotnet/ncl I am assuming we can track the documentation backport for all the Networking areas with just one greater `area-System.Net` issue, but if you prefer to open individual ones for `Http`, `Quic`, `Security`, `Sockets`, `Extensions-Http*`, feel free to do so.

Also, the DocsPortingTool is capable of porting documentation for only a specific namespace. That could be helpful if you want to backport documentation just for one specific set of APIs, and submit smaller PRs to make reviewing easier. Let me know if you have questions about that.

**Comment by ManickaP** [comment]
Triage: we should at least start with one assembly and see how much work it is. Good candidates are the assemblies that will get new APIs: Http, Quic; or small ones: Primitives.
