### ISSUE TITLE
Long running test hang: System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#490]
`System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext` hangs randomly on `OSX.1013.Amd64.Open-x64:Release`:

```
  Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Mail.Functional.Tests (found 135 of 136 test cases)
  Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 4)
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:02:00
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:04:01
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:06:02
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:08:03
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:10:04
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:12:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:14:07
```

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190518.8/workItem/System.Net.Mail.Functional.Tests/wilogs

@stephentoub maybe `SmtpClient.SendMailAsync` happens before the `TcpListener.AcceptTcpClient` (SmtpServer) blocking call?

**Comment by danmosemsft** [comment]
cc @stephentoub

**Comment by ViktorHofer** [comment]
Yes, the VSTest runner allows that.

**Comment by ViktorHofer** [comment]
Happened again: https://dnceng.visualstudio.com/public/_build/results?buildId=526104&view=ms.vss-test-web.build-test-results-tab&runId=16659244&resultId=179433&paneView=attachments

```
  Discovering: System.Net.Mail.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Mail.Functional.Tests (found 149 of 150 test cases)
  Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 2)
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:02:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:04:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:06:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:08:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:10:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:12:06
   System.Net.Mail.Functional.Tests: [Long Running Test] 'System.Net.Mail.Tests.SmtpClientTest.TestCredentialsCopyInAsyncContext', Elapsed: 00:14:06
```

cc @davidsh @wfurt

**Comment by danmoseley** [comment]
Another one  - net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open

this test is hanging like this about 5 times a month, every time on a debug runtime:

```kusto
WorkItems 
| where Started > now(-500d)  
| where FriendlyName == "System.Net.Mail.Functional.Tests"
//| where ExitCode == 139
| where Status == "Timeout"
| join kind= inner (
   Jobs  | where Started > now(-500d) | project  QueueName , JobId, Build, Type, Source, Properties 
) on JobId
| summarize count() by ExitCode, QueueName, Source, Started,//=format_datetime(bin(Started, 1d), 'MM-dd-yyyy'),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Finished,
  Build = tostring(parse_json(Properties).BuildNumber)
| order by Started asc
```

|ExitCode|QueueName|Source|Started|Pipeline|Pipeline_Configuration|OS|Arch|Finished|Build|count_|
|---|---|---|---|---|---|---|---|---|---|---|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/60376/merge|2021-10-14 14:14:56.0010000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-10-14 14:30:31.2030000|20211014.25|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/60786/merge|2021-10-22 22:12:01.5560000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-10-22 22:27:36.6840000|20211022.52|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/60877/merge|2021-10-27 14:52:06.3840000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-10-27 15:07:53.5430000|20211027.29|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/60914/merge|2021-11-14 02:16:09.5520000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-11-14 02:31:45.3600000|20211113.24|1|
|-3|ubuntu.1804.armarch.open|pr/public/dotnet/runtime/refs/pull/61759/merge|2021-11-19 00:13:19.4110000|runtime|Debug|ubuntu.1804.armarch.open|arm|2021-11-19 00:59:18.4310000|20211118.93|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62183/merge|2021-11-30 10:56:51.2890000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-11-30 11:12:28.2100000|20211130.4|1|
|-3|redhat.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/61669/merge|2021-11-30 11:54:25.6600000|runtime|Debug|redhat.7.amd64.open.rt|x64|2021-11-30 12:09:56.9420000|20211130.8|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62455/merge|2021-12-06 22:05:49.8690000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-12-06 22:21:25.3240000|20211206.64|1|
|-3|ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62509/merge|2021-12-08 00:18:26.4260000|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|2021-12-08 00:34:11.9420000|20211207.81|1|
|-3|windows.7.amd64.open.svc|pr/public/dotnet/runtime/refs/pull/62643/merge|2021-12-10 20:19:53.8170000|runtime|Debug|windows.7.amd64.open.svc|x86|2021-12-10 20:35:54.7460000|20211210.64|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62724/merge|2021-12-13 20:11:00.0140000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-12-13 20:26:46.4040000|20211213.46|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62779/merge|2021-12-15 19:45:39.0650000|runtime|Debug|windows.7.amd64.open.rt|x86|2021-12-15 20:01:14.5350000|20211215.32|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/63226/merge|2022-01-03 20:16:36.9940000|runtime|Debug|windows.7.amd64.open.rt|x86|2022-01-03 20:32:12.2710000|20220103.56|1|
|-3|windows.7.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/62995/merge|2022-01-10 20:40:23.2820000|runtime|Debug|windows.7.amd64.open.rt|x86|2022-01-10 20:55:58.6340000|20220110.35|1|
|999|osx.1014.amd64.open|pr/public/dotnet/runtime/refs/pull/62818/merge|2022-01-12 14:51:26.4000000|runtime|Debug|osx.1014.amd64.open|x64|2022-01-13 14:48:19.0520000|20220112.29|1|



https://github.com/dotnet/runtime/blame/main/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs#L363

**Comment by elinor-fung** [comment]
It looks like we are hitting timeouts on a release runtime too. Recent failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1612060&view=ms.vss-test-web.build-test-results-tab&runId=44893928&resultId=198053&paneView=debug

Modified version of @danmoseley's query to filter on `release_coreclr` runs and it shows a couple hits a month.
```kusto
WorkItems 
| where Started > now(-500d)  
| where FriendlyName == "System.Net.Mail.Functional.Tests"
| where Status == "Timeout"
| join kind= inner (
   Jobs  | where Started > now(-500d) | project  QueueName, JobId, Build, Type, Source, Properties 
) on JobId
| project
  ExitCode, QueueName, Started,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Finished,
  Source,
  Build = tostring(parse_json(Properties).BuildNumber)
| where PhaseName contains "release_coreclr"
| order by Started desc
```

|ExitCode|QueueName                             |Started                 |PhaseName                                              |Pipeline|OS                                    |Arch|Finished                |Source                                        |Build       |
|--------|--------------------------------------|------------------------|-------------------------------------------------------|--------|--------------------------------------|----|------------------------|----------------------------------------------|------------|
|-3      |windows.7.amd64.open.rt               |2022-02-14T21:38:48.14Z |libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.7.amd64.open.rt               |x86 |2022-02-14T21:54:23.244Z|ci/public/dotnet/runtime/refs/heads/main      |20220214.68 |
|-3      |windows.10.amd64.server19h1.es.open.rt|2022-02-04T19:42:04.066Z|libraries_test_run_release_coreclr_windows_x64_Debug   |runtime |windows.10.amd64.server19h1.es.open.rt|x64 |2022-02-04T19:57:35.634Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.10.amd64.serverrs5.open.rt    |2022-02-04T19:29:27.919Z|libraries_test_run_release_coreclr_windows_x64_Debug   |runtime |windows.10.amd64.serverrs5.open.rt    |x64 |2022-02-04T19:45:02.517Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |redhat.7.amd64.open.rt                |2022-02-04T19:28:13.866Z|libraries_test_run_release_coreclr_Linux_x64_Debug     |runtime |redhat.7.amd64.open.rt                |x64 |2022-02-04T19:43:45.002Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.7.amd64.open.rt               |2022-02-04T19:25:55.338Z|libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.7.amd64.open.rt               |x86 |2022-02-04T19:41:31.309Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.10.amd64.server19h1.es.open.rt|2022-02-04T19:24:16.847Z|libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.10.amd64.server19h1.es.open.rt|x86 |2022-02-04T19:39:48.006Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.81.amd64.open.rt              |2022-02-04T19:23:36.055Z|libraries_test_run_release_coreclr_windows_x64_Debug   |runtime |windows.81.amd64.open.rt              |x64 |2022-02-04T19:39:07.029Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |ubuntu.1604.amd64.open.rt             |2022-02-04T19:18:02.414Z|libraries_test_run_release_coreclr_Linux_x64_Debug     |runtime |ubuntu.1604.amd64.open.rt             |x64 |2022-02-04T19:33:47.468Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.11.amd64.clientpre.open       |2022-02-04T19:17:18.213Z|libraries_test_run_release_coreclr_windows_x64_Debug   |runtime |windows.11.amd64.clientpre.open       |x64 |2022-02-04T19:32:49.202Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |ubuntu.1804.amd64.open.rt             |2022-02-04T19:11:38.283Z|libraries_test_run_release_coreclr_Linux_musl_x64_Debug|runtime |ubuntu.1804.amd64.open.rt             |x64 |2022-02-04T19:27:22.933Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |ubuntu.1804.amd64.open.rt             |2022-02-04T19:06:57.809Z|libraries_test_run_release_coreclr_Linux_x64_Debug     |runtime |ubuntu.1804.amd64.open.rt             |x64 |2022-02-04T19:22:28.805Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |ubuntu.1804.amd64.open.rt             |2022-02-04T19:06:21.759Z|libraries_test_run_release_coreclr_Linux_x64_Debug     |runtime |ubuntu.1804.amd64.open.rt             |x64 |2022-02-04T19:22:17.103Z|pr/public/dotnet/runtime/refs/pull/62509/merge|20220204.49 |
|-3      |windows.7.amd64.open.rt               |2022-01-27T21:43:40.688Z|libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.7.amd64.open.rt               |x86 |2022-01-27T21:59:16.192Z|pr/public/dotnet/runtime/refs/pull/64397/merge|20220127.60 |
|-3      |windows.7.amd64.open.rt               |2022-01-21T08:28:59.374Z|libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.7.amd64.open.rt               |x86 |2022-01-21T08:44:35.318Z|pr/public/dotnet/runtime/refs/pull/63972/merge|20220120.144|
|-3      |windows.7.amd64.open.rt               |2022-01-20T16:13:42.146Z|libraries_test_run_release_coreclr_windows_x86_Release |runtime |windows.7.amd64.open.rt               |x86 |2022-01-20T16:29:17.461Z|pr/public/dotnet/runtime/refs/pull/64016/merge|20220120.32 |
|-3      |windows.7.amd64.open.rt               |2022-01-10T20:40:23.282Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2022-01-10T20:55:58.634Z|pr/public/dotnet/runtime/refs/pull/62995/merge|20220110.35 |
|-3      |windows.7.amd64.open.rt               |2022-01-03T20:16:36.994Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2022-01-03T20:32:12.271Z|pr/public/dotnet/runtime/refs/pull/63226/merge|20220103.56 |
|-3      |windows.7.amd64.open.rt               |2021-12-15T19:45:39.065Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-12-15T20:01:14.535Z|pr/public/dotnet/runtime/refs/pull/62779/merge|20211215.32 |
|-3      |windows.7.amd64.open.rt               |2021-12-13T20:11:00.014Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-12-13T20:26:46.404Z|pr/public/dotnet/runtime/refs/pull/62724/merge|20211213.46 |
|-3      |windows.7.amd64.open.svc              |2021-12-10T20:19:53.817Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.svc              |x86 |2021-12-10T20:35:54.746Z|pr/public/dotnet/runtime/refs/pull/62643/merge|20211210.64 |
|-3      |windows.7.amd64.open.rt               |2021-12-06T22:05:49.869Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-12-06T22:21:25.324Z|pr/public/dotnet/runtime/refs/pull/62455/merge|20211206.64 |
|-3      |windows.7.amd64.open.rt               |2021-11-30T10:56:51.289Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-11-30T11:12:28.21Z |pr/public/dotnet/runtime/refs/pull/62183/merge|20211130.4  |
|-3      |windows.7.amd64.open.rt               |2021-11-14T02:16:09.552Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-11-14T02:31:45.36Z |pr/public/dotnet/runtime/refs/pull/60914/merge|20211113.24 |
|-3      |windows.7.amd64.open.rt               |2021-10-27T14:52:06.384Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-10-27T15:07:53.543Z|pr/public/dotnet/runtime/refs/pull/60877/merge|20211027.29 |
|-3      |windows.7.amd64.open.rt               |2021-10-22T22:12:01.556Z|libraries_test_run_release_coreclr_windows_x86_Debug   |runtime |windows.7.amd64.open.rt               |x86 |2021-10-22T22:27:36.684Z|pr/public/dotnet/runtime/refs/pull/60786/merge|20211022.52 |

**Comment by eerhardt** [comment]
Another hit here:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75176-merge-d74b2d2bdf234482b8/System.Net.Mail.Functional.Tests/1/console.2530842b.log?helixlogtype=result

**Comment by rzikm** [comment]
No recent hits, not actionable at this moment, closing until issue resurfaces.
