### ISSUE TITLE
Microsoft.XmlSerializer.Generator is not setting the correct version number in build/publish

### ISSUE THREAD

**Issue by bneumann** [dotnet/runtime#49003]
### Description

I have a pretty basic project with some DTOs that should be serialized. I have set the project up according to the documentation on the [Microsoft.XmlSerializer.Generator page ](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator) ( see project file below).
I build everything with
```dotnet build -c Release ```

And after the build I see the output as:

![image](https://user-images.githubusercontent.com/2605131/109636873-60ff3100-7b4c-11eb-886f-415df7ccf56e.png)

I would expect that the Serializers DLL had the same version number as the rest of the build. But it doesn't. MAybe I overlooked something?

### Configuration
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>xxx.HxmlCurve</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.XmlSerializer.Generator" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.XmlSerializer.Generator" Version="5.0.0" />
  </ItemGroup>
</Project>
```

### Regression?

I have only tried it with the 5.0.0 version because from the issues I saw that the older ones had problems with netcode and netstandard.

### Other information

I could use another tool to imprint the version number in a post build process but I think it should actually be working like described.

**Comment by jeffreyrivor** [comment]
It looks like something similar to what happens in https://github.com/dotnet/sdk/blob/8beb651a5be4789848b545e8838e418d094a8000/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L176-L179 to generate the assembly info for the normal compile needs to have happen for the serialization library compilation.

It may be possible to work around this by manipulating part of the MSBuild process that is injected into the build by the tool. Maybe a target to trigger WriteCodeFragment with the assembly attributes to a file and then adding that as a source in the CSC response file https://github.com/dotnet/runtime/blob/b9b876ab510e98ac741f1c82f1cb4fb1cb21e3ef/src/libraries/Microsoft.XmlSerializer.Generator/pkg/build/Microsoft.XmlSerializer.Generator.targets#L23-L25 if additional CS files can be picked up there?

**Comment by HongGit** [comment]
This should have been fixed in .NET 6.0. 

Feel free to reactivate this if that is not the case.
