### ISSUE TITLE
Use LLVM for AOT in Android functional tests

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#49007]
With https://github.com/dotnet/runtime/pull/47167 we added AOT functional tests for Android, but it doesn't use LLVM to do the AOTing. This needs to be switched to AOT (see also `-no-integrated-as` workaround in src/tasks/AndroidAppBuilder/Templates/CMakeLists-android.txt)

**Comment by steveisok** [comment]
https://github.com/dotnet/runtime/pull/53643 made it happen
