### ISSUE TITLE
arm64 crossgen2 performance measurements

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#49013]
I have profiled crossgen2 on arm64 architecture with dotnet-trace and with perf, here is measurement results.
[dotnet_trace.zip](https://github.com/dotnet/runtime/files/6069834/dotnet_trace.zip) was collected by command:
```
./corerun /root/tasks/65_aot_profiling/diagnostics_v5.0.160202/dotnet-trace.dll collect --format Speedscope --output /root/trace.nettrace -- ./corerun ./crossgen2/crossgen2.ni.dll -r:./*.dll -r:./crossgen2/*.dll -O --inputbubble --compilebubblegenerics ./System.Private.CoreLib.dll --out ./System.Private.CoreLib.ni.__dll
```
[perf.zip](https://github.com/dotnet/runtime/files/6069839/perf.zip) was collected by command:
```
perf record -g -- ./corerun ./crossgen2/crossgen2.ni.dll -r:./*.dll -r:./crossgen2/*.dll -O --inputbubble --compilebubblegenerics ./System.Private.CoreLib.dll --out ./System.Private.CoreLib.ni.__dll
```

System dll's was precompiled by crossgen2 with `-O --inputbubble --compilebubblegenerics`.
Runtime  tag `v6.0.0-preview.1.21102.12`.

In accordance that measurements crossgen2 80% of time spends into unmanaged code, mostly inside `JitCompileMethod`. So crossgen2 more active uses JIT interfaces then crossgen. In comparison to crossgen, crossgen2 is slower compiler. At the same time crossgen2 compiles more methods then crossgen. How we could compare the performance of crossgen and crossgen2?

cc @jkotas @davidwrighton @alpencolt @gbalykov

**Comment by jkotas** [comment]
I would recommend measuring crossgen2 performance in the context of specific scenario.

As you have said, crossgen2 is to designed to precompile more. On the other hand, crossgen2 is designed to take advantage of all cores on the machine that make it faster in number of scenarios.

**Comment by davidwrighton** [comment]
We've reduced crossgen2 overhead substantially by moving to using our NativeAOT compilation tech. We still have somewhat higher cost per method generated, but at the wallclock time is now much more similar between the two compilers. At this point, we do not see any more value to comparing the compilation performance of crossgen and crossgen2.
