### ISSUE TITLE
How to preserve refspec to patches and branches after the repo renamed 'master' to 'main'

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/runtime#49017]
For all those who can't pull `master`, it has renamed to `main`.

To preserve refspec to patches and branches, just changing the `heads/master` to `heads/main` should work.

```diff
[remote "origin"]
	url = https://github.com/dotnet/runtime
-	fetch = +refs/heads/master:refs/remotes/origin/master
+	fetch = +refs/heads/main:refs/remotes/origin/master
	tagopt = --no-tags
[branch "master"]
	remote = origin
-	merge = refs/heads/master
+	merge = refs/heads/main
```

> Putting this out there, if anyone else facing similar issue with git.

**Comment by Nirmal4G** [comment]
Alternative to #48357. For those who **cannot** change the default branch for _obvious_ 😉 reasons.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/48357
