### ISSUE TITLE
Symbol and NetHosts Archives no longer produced 

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#49026]
Both the symbols zip and nethost zips stopped getting published after we moved to the SFX SDK. If these are still needed for something, we should bring them back and add them to the nightly table.

cc: @NikolaMilosavljevic @jkoritzinsky

**Comment by ViktorHofer** [comment]
Who would know what these are/were for? I don't anything about the nethost one and I presume the symbols one is just an aggregation of all symbols available to being downloaded for better debugging?

**Comment by NikolaMilosavljevic** [comment]
> Both the symbols zip and nethost zips stopped getting published after we moved to the SFX SDK. If these are still needed for something, we should bring them back and add them to the nightly table.
> 
> cc: @NikolaMilosavljevic @jkoritzinsky

Can you list all files that are not being produced anymore?

**Comment by ViktorHofer** [comment]
AFAIK we haven't received any complaints about this, hence moving to 7.0.

**Comment by MichaelSimons** [comment]
I hate to be the bearer of bad news but I think this issue is impacting source-build, see https://github.com/dotnet/source-build/issues/2403.  Is it possible to fix this in 6.0?

**Comment by jkoritzinsky** [comment]
@MichaelSimons I have a PR out for 7.0 and am pre-emptively backporting to 6.0. Can you review https://github.com/dotnet/runtime/pull/59842? I'll comment here with the 6.0 PR as soon as it's open.

**Comment by jkoritzinsky** [comment]
6.0 PR is open at https://github.com/dotnet/runtime/pull/59843
