### ISSUE TITLE
Coreclr v2.1.25-dependencies tag incorrectly

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#49035]
### Description

We are struggling building the .NET Core 2.1.25 based on the `v2.1.25-dependencies` tag of the **coreclr** repository. It looks like `v2.1.25-dependencies` was tagged in the wrong location. For example v2.1.25 contains **17,015** commits where as v2.1.25-dependencies contains **22,378**. I would only expect one or 2 commit differences for version number changes. 

What we are specifically breaking on is v2.1.25-dependencies has the removal of the SOS plugin and listed as a separate step we should build. We don't have that build infrastructure setup for that and it doesn't make sense in a patch let alone a `-dependencies` tag to have such a drastic change. This is seems like a mistake to have this change along the the other 5,000 commits in the dependencies tag.

Can we get some help understanding what happened with the v2.1.25-dependencies tag and possibly get set on the correct commit?

This is somewhat related to our previous issue but that was for corefx.
https://github.com/dotnet/runtime/issues/48186

@Anipik

### Regression?

It is a regression from building previous 2.1.X patches.

**Comment by dagood** [comment]
It looks like the commit tagged `v2.1.25-dependencies` is is the same as `v3.1.12`, https://github.com/dotnet/coreclr/commit/3c95aa2a7e0ca9d28447c2b8520ab333001e91d1. The checked-in version number here confirms it's actually 3.1.12: https://github.com/dotnet/coreclr/blob/3c95aa2a7e0ca9d28447c2b8520ab333001e91d1/eng/Versions.props#L5.

/cc @jamshedd FYI on tag status.

**Comment by rbhanda** [comment]
@Anipik can you help us here to correct these tags.

**Comment by Anipik** [comment]
@aik-jahoda can you take care of this ?  we need to make it similar to the 2.1.25 tag

**Comment by aik-jahoda** [comment]
It should be on correct commit now.
https://github.com/dotnet/coreclr/commits/v2.1.25-dependencies
@Anipik can you please review and close the issue? Basically it is on the came commit like v2.1.25.

**Comment by Anipik** [comment]
yep that looks good
