### ISSUE TITLE
Crossgen2 silently creates an empty R2R file when no input files are specified

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#49037]
When no input files are specified on Crossgen2 command line, CG2 pretends to work normally but doesn't actually compile anything, it just produces an empty R2R file. While this behavior may be useful in some corner scenarios, in most cases it rather amounts to silently ignoring malformed command line. We should display at least a warning in this corner case.

/cc @dotnet/crossgen-contrib

**Comment by trylek** [comment]
I believe it's still the case, it's however just an obscure corner case not regressing any real functionality so I think its priority is very low.

**Comment by ivdiazsa** [comment]
I think this may have been fixed at some point, unless I'm not doing the correct repro. This is the command line I'm using:

```sh
./crossgen2 --targetos:osx --targetarch:arm64 --reference:$COREROOT/*.dll --out:Empty.r2r.dll
```

`$COREROOT` here is just a temp environment variable I set to avoid typing the whole path to my _Core\_Root_. Running this command yields the following error:

```cs
Unhandled exception. Internal.CommandLine.CommandLineException: No input files specified
   at ILCompiler.Program.Run(String[] args) in /Users/ivdiazsa186/Development/runtime/src/coreclr/tools/aot/crossgen2/Program.cs:line 499
   at ILCompiler.Program.Main(String[] args) in /Users/ivdiazsa186/Development/runtime/src/coreclr/tools/aot/crossgen2/Program.cs:line 1159
Abort trap: 6
```

Tried it on Windows and the results were the same. Thought about removing the `--reference` flag as well but it didn't change the end result. Assuming this is the correct repro, I think this exception is a fairly reasonable way of failing. I would like to hear your thoughts @trylek, @mangod9.

**Comment by trylek** [comment]
Correct, I have just audited the source code and the check for zero input files was apparently added sometime last year, in fact according to *git blame* soon after I created this issue. I believe this can be safely closed as completed.
