### ISSUE TITLE
ThreadPool.MinThread need better default value

### ISSUE THREAD

**Issue by wsq003** [dotnet/runtime#49044]
Async programming became more and more popular, and threadpool starvation became a serious problem.

It is very difficult to do all things right as suggested https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md

Occasional cache expiration may easily cause threadpool starvation because “By default, the minimum number of threads is set to the number of processors on a system”. 

Threre is an easy way to prevent most occasional threadpool starvation
ThreadPool.SetMinThreads(5000, 50);

5000 may be a little too big, but I believe "the number of processors on a system" is too small in most cases.

My suggestion is set the default value of ThreadPool.MinThread to 100 times of "the number of processors on a system". Which means 200 for 2 core cpu, 800 for 8 core cpu.

Alternative suggestion is to optimize the algorithm for managing thread creation and destruction. But I think this may be difficult.

**Comment by En3Tho** [comment]
I think you should post some kind of example where this really improves performance. Or even few of then

**Comment by wsq003** [comment]
> 
> 
> I think you should post some kind of example where this really improves performance. Or even few of them.

bool cacheHit = false;

public async Task<string> GetUserName(Int64 userID)
{
	if (cacheHit)
	{
		return "cacheResult_Mike";
	}
	else
	{
		var name = await LoadDB(userID);
		return name;
	}
}

private async Task<string> LoadDB(long userID)
{
	//Sorry I forget to call the async function, so thread blocked here.
	//It works fine in test. And it even works find in benchmark because of cacheHit.
	//But in heavy load situation, when cache miss, every thread in threadpool will block here. Then application stunned.
	Thread.Sleep(100);

	return await Task.FromResult("Mike");
}

**Comment by mangod9** [comment]
@kouvel fyi.

**Comment by wsq003** [comment]
#52558 may significantly relief this threadpool starvation issue.

**Comment by wsq003** [comment]
#53471 contains many useful information.

**Comment by wsq003** [comment]
I believe #52558 had solved the problem concerned.
So this issue will be closed.
