### ISSUE TITLE
DI container should not capture transient IDisposables

### ISSUE THREAD

**Issue by d-vs** [dotnet/runtime#49049]
According to the below documentation, transient services that implement IDisposable will be captured by the DI container of Extensions.DependencyInjection.

https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposable-transient-services-captured-by-container

For me, this is not correct behaviour. By their nature, transient services should be created and discarded immediately by the container, with the proviso that user code should dispose of them, where necessary. This is a pretty serious limitation of this library, and my proposal will fix it, I believe.

**Comment by davidfowl** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/36461
