### ISSUE TITLE
Annotate DebuggerVisualizerAttribute to be linker safe

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#49055]
Annotate [DebuggerVisualizerAttribute](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebuggerVisualizerAttribute.cs) to be linker safe

@eerhardt

**Comment by eerhardt** [comment]
What does it mean for this attribute to be linker safe?

I assume at a minimum we will need to preserve public ctors. But what about public properties? What about interfaces the visualizer implements? Does VS check for any interfaces? Should we just mark the Type as preserve `All`?

cc @mikem8361

**Comment by marek-safar** [comment]
I think we should preserve everything as we did for DebuggerTypeProxyAttribute

**Comment by tommcdon** [comment]
@eerhardt I noticed that this issue is a few months old.  Just checking in to see if this is on track for .NET 6, or if this is something that can be moved out to .NET 7

**Comment by eerhardt** [comment]
I was planning on addressing it in the next week. I just have a few bugs assigned to me.
