### ISSUE TITLE
System.Linq.EmptyIfNull() API Proposal

### ISSUE THREAD

**Issue by megakid** [dotnet/runtime#49054]
## Background and Motivation

Quite often I end up wanting to be dismissive of null vs empty when using LINQ.   
E.g. when using `.Any()` I do not want it to throw when the `source` collection is null (see https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Linq/src/System/Linq/AnyAll.cs#L16).

I always see the existing `.DefaultIfEmpty()` [docs](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.defaultifempty?view=net-5.0) API but it falls short as this returns a single element Enumerable versus an empty one.

I therefore end up implementing this extension method throughout most of my codebases:

```
        [NotNull]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T>? source)
        {​​​​​​​
            return source ?? Enumerable.Empty<T>();
        }​​​​​​​
```

It seems fundamental enough to warrant a new method in the `System.Linq` namespace but is it too simple?  Happy to raise a PR here.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:

```diff
namespace System.Linq
{
    public static class Extensions {
+       public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T>? source);
    }
}
```

## Usage Examples

``` C#
    public int DoStuff(List<T>? list) 
    {
        if (!list.EmptyIfNull().Any()) 
        {
            // empty
            return 0;
        }
        return 1;
    }
```

## Risks

* Too simple to add to the runtime?

**Comment by eiriktsarpalis** [comment]
I would say that `??` is the language construct intended for this type of scenario, in your example:
```csharp
    public int DoStuff(List<T>? list) 
    {
        if (!(list ?? Enumerable.Empty<T>()).Any()) 
        {
            // empty
            return 0;
        }
        return 1;
    }
```
It's longer by a few characters, sure, but I don't see much value given the overhead of introducing yet another concept for dealing with the same problem. Like you said, it should be fairly trivial to incorporate such a method as an extension in your code.

**Comment by eiriktsarpalis** [comment]
I'm going to close this issue, thank you for contributing the proposal. Feel free to reopen if you feel that the conversation should be continued.
