### ISSUE TITLE
System.TestStructs ships with Micrososoft.Extensions.DependencyInjection.Specification.Tests but builds from test directory

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#49069]
https://github.com/dotnet/runtime/pull/48858 started shipping System.TestStructs.

Micrososoft.Extensions.DependencyInjection.Specification.Tests is shipped to be used by 3rd party implementers of Micrososoft.Extensions.DependencyInjection in order to test their implementations.  This was something done in dotnet/extensions, then dropped when we moved the source to dotnet/runtime, and brought back due to https://github.com/dotnet/runtime/issues/37108#issuecomment-635028185 cc @maryamariyan @JunTaoLuo

@eerhardt added tests to this test assembly in https://github.com/dotnet/runtime/commit/21ff47c4e8dc1d4ab7006c2112bb9e6594e66712 which require the System.TestStructs assembly in order to test how DI implementations handle structs with parameterless constructors.

@ViktorHofer brought up some questions after we merged the PR and some issues arose around wether we should be shipping System.TestStructs as it is, or if it should be moved somewhere to better indicate that its a test assembly.  For example https://github.com/dotnet/runtime/tree/main/src/libraries/Common/src or https://github.com/dotnet/runtime/tree/main/src/libraries/Common/tests.

We might also consider if we want to change the assembly name, public key token, or anything else about how we build this or other "shipping test assemblies".

This issue aims to gather concensus on these questions.  Those mentioned, please weigh in.

**Comment by eerhardt** [comment]
The test added in https://github.com/dotnet/runtime/commit/21ff47c4e8dc1d4ab7006c2112bb9e6594e66712 did find a behavioral difference in Unity DI container: https://github.com/unitycontainer/microsoft-dependency-injection/issues/87. So it seems like a valuable test.

Note that once the [C# feature](https://github.com/dotnet/csharplang/issues/99) comes in which allows parameterless constructors on structs, we can remove the dependency on the TestStructs assembly and just create one in the test assembly.

**Comment by ViktorHofer** [comment]
> Note that once the C# feature comes in which allows parameterless constructors on structs, we can remove the dependency on the TestStructs assembly and just create one in the test assembly.

Is that a NET6 deliverable? If yes then I'm fine to wait, otherwise I would prefer to address this issue sooner.

**Comment by eerhardt** [comment]
> Is that a NET6 deliverable? 

According to https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md#c-next, it is currently in progress.  @cston @jcouv @333fred could answer if parameterless struct constructors will make it for NET6.

**Comment by 333fred** [comment]
Chuck is working on them. I would expect that they should make it.

**Comment by ericstj** [comment]
@eerhardt in this case do you want to remove this test for now until we have the language feature.

**Comment by ViktorHofer** [comment]
Closing as mitigated with https://github.com/dotnet/runtime/commit/b0ba53a8f051079ac14726554fbb6aceeba2fe61.
