### ISSUE TITLE
[making hidden services for android and ios]: [Service for android , ios,linux,tizen and mac] 

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#49060]
How to make background services in android , ios,linux,tizen and mac

**Comment by huoyaoyuan** [comment]
For linux, Microsoft.Extensions.Hosting.Systemd provides some integrations.
For other OS, Xamarin may have provided corresponding app model.
There can't be a unification among OSes because they provide far different features.

**Comment by Barshan-Mandal** [comment]
But I need to make a form in xamarin...but i dont want to make it

**Comment by huoyaoyuan** [comment]
There may not be concept of "hidden background service" on mobile OS. A background task must belong to a foreground application.

**Comment by Barshan-Mandal** [comment]
Use interpreter instead

**Comment by danmoseley** [comment]
@Barshan-Mandal  could you please explain?

**Comment by Barshan-Mandal** [comment]
Alike windows processes.without the form of xamarin I want to make an application.That's all
