### ISSUE TITLE
net 6 Preview Target Android results in SSL error

### ISSUE THREAD

**Issue by Qowy** [dotnet/runtime#49076]
Hi
I was trying the .net 6 preview samples for android (HelloAndroid)

When I add a HttpClient and then request a https page I get the following exception at runtime.

`[Mono] DllImport unable to load library 'libSystem.Security.Cryptography.Native.OpenSsl'.`

**Comment by steveisok** [comment]
This won't be resolved until P3 where we'll default to using the native http handler.

**Comment by Qowy** [comment]
Ok, goot to know :) maybe it could be added to the known issues then?

**Comment by steveisok** [comment]
This should be resolved now.  Please re-open if you find otherwise.
