### ISSUE TITLE
Support PREJIT & FNV in Crossgen1

### ISSUE THREAD

**Issue by clamp03** [dotnet/runtime#49108]
For years, we used FNV to optimize app launch time in the embedded systems.
However, as I know, FNV is almost deprecated. I couldn't build and test FNV on .net6.
I tested other alternatives such as crossgen1's r2r or crossgen2. However, in our embedded systems, its launching time is 2x slower.
Actually, customers will not accept such performance degradation, so we cannot make products with .net6.
Until crossgen2 shows good performance like FNV, we'd like to use .net6 with FNV.

Internally, I fixed and made FNV work again the last year.
A big problem is that code is changing too fast. It is harder to keep the latest .net6 code with FNV.
If you don't mind, I want to push patches one by one like https://github.com/dotnet/runtime/pull/49052. ("update codes in PREJIT based on latest source codes" and "re-enable removed old codes")

Patch https://github.com/dotnet/runtime/pull/49052 is an instrumentation fix in FNV.

Thank you.

**Comment by clamp03** [comment]
An issue in #49052 is in R2R (crossgen1)  as well as FNV.
I tested on arm machine (RPi4) like below.
```
$ ./crossgen /Tuning /out A.dll IL/System.Private.CoreLib.dll  
Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-dev
Copyright (c) Microsoft Corporation.  All rights reserved.

Assert failure(PID 4549 [0x000011c5], Thread: 4549 [0x11c5]): Assertion failed 'block->bbCodeOffs == (IL_OFFSET)schema[firstSchemaIndex].ILOffset' in 'Microsoft.CodeAnalysis.EmbeddedAttribute:.ctor():this' during 'Profile instrumentation' (IL size 8)

    File: /dotnet/jobs/fnv/fixmpgo/src/coreclr/jit/fgprofile.cpp Line: 412
    Image: /home/dheon/fnv6/crossgen

Aborted
```
I checked firstSchemaIndex is -1 with a debugger.

**Comment by MichalStrehovsky** [comment]
Crossgen2 introduces a couple enhancements that will help with startup time:

* Composite ready to run compilation (couldn't find docs, but maps to the `--composite` argument of crossgen2). In this mode, the compiler composes multiple input assemblies together and also enables inlining between those assemblies. This leads to better code generations and limits file I/O at startup.
* Profile guided optimizations (`--mibc`, `--callchain-profile` command line arguments). These help laying out code in the assemblies better.

I expect as these options mature, they will help bringing the perf closer to what you saw with FNV.

**Comment by clamp03** [comment]
@MichalStrehovsky Right. There are many enhancements in crossgen2. And I think crossgen2 will be better than FNV soon.

Last month, I  tested with ```--composite```. It improves startup time, but it is still 2x slower. (I checked ```--mibc```, but it didn't work well. I will check ```--mibc``` and ```--callchain-profile``` again.)
Startup time of a simple sample app (org.tizen.example.Alarm)
- FNV: 520ms
- R2R CROSSGEN2: 1200ms
- R2R CROSSGEN2 (```--composite``` all DLL files "libraries and applications"): 1000ms

We cannot use current crossge2 for our product. I know you want to deprecate FNV as soon as possible.
I am sorry, however, if you don't mind, I hope FNV is kept until crossgen2 is mature.

**Comment by AndyAyersMS** [comment]
@clamp03 please try out #49154 for the jit side of things.

If you think you will need changes on the runtime side too, let's discuss.
