### ISSUE TITLE
[macOS 11] System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX fails on CoreCLR

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#49106]
See https://dev.azure.com/dnceng/public/_build/results?buildId=1021947

```console
----- start Wed Mar 3 17:37:13 PST 2021 =============== To repro directly: =====================================================
pushd .
/tmp/helix/working/C24F0A5F/p/dotnet exec --runtimeconfig System.Runtime.Extensions.Tests.runtimeconfig.json --depsfile System.Runtime.Extensions.Tests.deps.json xunit.console.dll System.Runtime.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================
/private/tmp/helix/working/C24F0A5F/w/B1000946/e /private/tmp/helix/working/C24F0A5F/w/B1000946/e
  Discovering: System.Runtime.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Extensions.Tests (found 895 of 964 test cases)
  Starting:    System.Runtime.Extensions.Tests (parallel test collections = on, max threads = 8)
    System.Tests.EnvironmentTests.GetFolderPath_UWP_NotEmpty [SKIP]
      Condition(s) not met: "IsWindows10Version1709OrGreater", "IsInAppContainer"
    System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX [FAIL]
      Assert.Contains() Failure
      Not found: 11.2
      In value:  osx.11.0-arm64
      Stack Trace:
        /_/src/libraries/System.Runtime.Extensions/tests/System/EnvironmentTests.cs(191,0): at System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX()
    System.Tests.EnvironmentTests.GetFolderPath_UWP_ExistAndAccessible [SKIP]
      Condition(s) not met: "IsWindows10Version1709OrGreater", "IsInAppContainer"
    System.Tests.EnvironmentTests.UserInteractive_WindowsNano [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
  Finished:    System.Runtime.Extensions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Extensions.Tests  Total: 7509, Errors: 0, Failed: 1, Skipped: 3, Time: 2.720s
/private/tmp/helix/working/C24F0A5F/w/B1000946/e
----- end Wed Mar 3 17:37:16 PST 2021 ----- exit code 1 ----------------------------------------------------------
```

**Comment by sdmaclea** [comment]
This is a macOS version to RID mapping issue. I am not sure where it goes.

Essentially, for macOS 11, the minor number is no longer a major OS release.  The current M1 silicon version is now 11.3.  The first version was 11.0.

@danmoseley @richlander @jankotas Do we know where this belongs?  Do we need to modify the RID graph?

**Comment by danmoseley** [comment]
@ericstj ?

**Comment by ericstj** [comment]
> the minor number is no longer a major OS release

I'm having a hard time parsing this.  Are we saying we no longer want to treat the minor version as targetable?  If that's the case then we need to change the host's code for computing the RID on OSX: https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/native/corehost/hostmisc/pal.unix.cpp#L535-L583
cc @vitek-karas @vsadov


If we do indeed want these versions to be targetable then we need to record them in the RID graph:
https://github.com/dotnet/runtime/blob/da580beb984f40516a408b8270e08d93daa0364e/src/libraries/Microsoft.NETCore.Platforms/src/runtimeGroups.props#L146

**Comment by jkotas** [comment]
I think we need both:
- Add the new macOS versions to the RID graph, to continue the established pattern and to make them targetable
- Fix the host code that computes RIDs in runtime/src/native/corehost/hostmisc/pal.unix.cpp

**Comment by sdmaclea** [comment]
So since 11.0 was released 11/2020, 11.1, 11.2, and 11.3 have been released.  As far as I know all of these are all known as macOS `Big Sur`.  They were treated as maintenance releases (Basic system update as opposed to an OS upgrade).  I suspect we do not need that resolution for targeting macOS versions.

**Comment by jkotas** [comment]
> So since 11.0 was released 11/2020, 11.1, 11.2, and 11.3 have been released. As far as I know all of these are all known as macOS Big Sur. They were treated as maintenance releases

Ah, ok. If Apple changed its versioning scheme for major releases, then we may just need to fix the `OSVersion_ValidVersion_OSX` test.

**Comment by ericstj** [comment]
@eerhardt recently touched this https://github.com/dotnet/runtime/commit/2d4acbde200dba78794d9baf8cc69c170267fde0 and added this test.

It would be nice if these agreed (RID and Environment.OSVersion) but we shouldn't force them if they are serving different purposes.  Why can't we make this API behave more like the Windows API where Enivronment.OSVersion is consistent with the RID but gives more information?

**Comment by jkotas** [comment]
`RuntimeInformation.RuntimeIdentifier` and `Environment.OSVersion` APIs return `osx.11.0-arm64` and `11.2` on macOS 11.2 today.

@ericstj What would you like to see it change to?

To make these consistent, I think we would need to change the RID for macOS 11.X to be just `osx-11`. Is it feasible to go back in time like that?

**Comment by sdmaclea** [comment]
FYI this was the message today on my Intel MacBook.

```
SOFTWARE UPDATE

macOS Big Sur 11.3 is available and will be installed later tonight
```

**Comment by ericstj** [comment]
I'm just expressing my opinion here, not really prescribing a solution, nor can I predict the future.  I would imagine that we'd want to OSVersion to provide as much information as possible (for example, through more significant digits/parts) while making it clear which RID it mapped to.  Has Apple made a comment about what their next targetable release will be called?  Will it be 12.0, or will it be 11.N?

**Comment by eerhardt** [comment]
cc @wfurt as well since he implemented the RID logic here: https://github.com/dotnet/runtime/pull/41176.

I think the `Environment.OSVersion.Version` is doing the right thing here, it is returning the version the OS says it is (see @sdmaclea's SOFTWARE UPDATE message above).

I think the RID is incorrect. It shouldn't be `osx.11.0` when running on an `11.2` OS. It shouldn't contain an incorrect minor version number. We should either:

* Keep including the minor version and make it correct, i.e. `osx.11.2`
     or
* Drop the minor version, just like we do for RHEL and other distros where the minor version doesn't dictate which assets to select.

**Comment by sdmaclea** [comment]
> Is it feasible to go back in time like that?

If it is not feasible ... we could make `11.0` as an anomaly/alias for `11`.

**Comment by wfurt** [comment]
It seems like we started with the 10.x while back. For RH/Centos we track only the major release because as assume (probably confirmed with RedHat) that the minor versions are compatible. That may be trickier for macOS as we have little knowledge and control. There is already watch for upcoming Linux distributions and perhaps we can use same process for macOS e.g. update the rid graph when new version is announced.  While that is somewhat pain, we can make it just work - as good(or bad) as Linux.

**Comment by sdmaclea** [comment]
For 10.x the x referred to a major OS release, `Sierra`, `High Sierra`, `Catalina`...

**Comment by ericstj** [comment]
Related to this is https://github.com/dotnet/runtime/issues/44120 https://github.com/dotnet/runtime/issues/44931

**Comment by akoeplinger** [comment]
> Has Apple made a comment about what their next targetable release will be called? Will it be 12.0, or will it be 11.N?

No and it's hard to predict, though there are indications that the next version will indeed be 12.x: https://www.macworld.com/article/342024/after-20-years-of-os-x-macos-11-might-be-gone-after-big-sur.html

We'll know for sure after WWDC which is in ~3 weeks.

**Comment by danmoseley** [comment]
@wfurt now macOS 12 is out is there any work here we need to do now?

**Comment by wfurt** [comment]
We should at least add new RID. I can probably get it running in VM and do smoke test runs.

**Comment by akoeplinger** [comment]
This is actually not arm64 specific, it happens on x64 too:

```
  System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX [FAIL]
        Assert.Contains() Failure
        Not found: 11.6
        In value:  osx.11.0-x64
```

**Comment by ericstj** [comment]
We should decide the value in this test and if its assertion is important.  It was specifically created by @eerhardt for OSX and making sure we update our RID or `Environment.OSVersion` when the OS updates.  From what @akoeplinger says it seems the test is no longer passing anywhere.

https://github.com/dotnet/runtime/commit/2d4acbde200dba78794d9baf8cc69c170267fde0 -- https://github.com/dotnet/runtime/issues/34977

**Comment by eerhardt** [comment]
I believe we made changes to the RID for macOS 12+ to drop the minor version in the RID calculation. We should update the test to reflect this behavior:

https://github.com/dotnet/runtime/pull/60494
