### ISSUE TITLE
[macOS-arm64] System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [FAIL] on CoreCLR

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#49111]
See https://dev.azure.com/dnceng/public/_build/results?buildId=1021947

```console
    System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6 [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Drawing.Common/tests/GdiplusTests.cs(13,0): at System.Drawing.Tests.GdiplusTests.IsAtLeastLibgdiplus6()
```

**Comment by safern** [comment]
This test would need to be disabled as I don't think libgdiplus is available for mac_arm64 yet. 

cc: @marek-safar @danmoseley

**Comment by danmoseley** [comment]
Interesting, I think we don't have good data on how much usage there is on Mac of System.Drawing. I suppose a possible action here is a timebox trying to get libgdiplus to build to get an idea of the work, but my guess is that this isn't high priority and can wait until we have more hardware (?).

**Comment by marek-safar** [comment]
The hardware is available so I don't think that should be the reason for a delay.

**Comment by sdmaclea** [comment]
@danmosely Where is the libgdiplus code that needs to be built for Apple Silicon?

**Comment by danmoseley** [comment]
@sdmaclea two 'e's in my tag (just so you find me 😃 )

It's here https://github.com/mono/libgdiplus

Context: this library is not actively maintained, yet we have a dependency on it. I know that is something that @safern is thinking about. So we don't have expertise in building it, but I think some exists on the Mono team. If you are willing to give it a quick try for Apple Silicon, I think that would be wonderful.

**Comment by sdmaclea** [comment]
I wrote up my experience building this here https://github.com/mono/libgdiplus/issues/696

**Comment by safern** [comment]
Given: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md we will not be fixing this. (Cleaning up the test and removing the active issue will be done once we nuke the Unix implementation).
