### ISSUE TITLE
We should enable CS1591 on projects that have migrated their docs

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#49120]
@carlossanlop @safern 

Once a project migrates its docs it should be a build error if docs are missing from a publicly visible member.  I just tried this and it's not flagging CS1591.

**Comment by safern** [comment]
Good catch. We will take care of this ASAP.

**Comment by carlossanlop** [comment]
@ericstj This could be addressed by manually adding:

`<GenerateDocumentationFile>true</GenerateDocumentationFile>`

to the first `PropertyGroup` in the *.csproj. Correct? [Example](https://github.com/dotnet/runtime/pull/48841/files)

The tool does not add it yet because I didn't find a way to edit the csproj via the Roslyn/MSBuild APIs. But I think I can just do it using System.Text.Xml.

**Comment by carlossanlop** [comment]
I just saw your comment in your PR: https://github.com/dotnet/runtime/pull/49118/files#r587730539

So `GenerateDocumentationFile` is not enough, that's what you discovered?

**Comment by safern** [comment]
I believe you can use MSBuild ProjectCollection to load a project and modify it but not sure: https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation.projectcollection.loadproject?view=msbuild-16-netcore#Microsoft_Build_Evaluation_ProjectCollection_LoadProject_System_String_

@ericstj should know, I believe he is done this before.

**Comment by ericstj** [comment]
`GenerateDocumentationFile` is different.  As far as I can tell the only thing this impacts is the defintion of the DocumentationFile property:
https://github.com/dotnet/sdk/blob/d6232ee12e6cb1b9f0c6fabdcb961f943e9d7c6e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.BeforeCommon.targets#L243-L256

Which may be irrelevant for our projects, since we define this ourselves:
https://github.com/dotnet/runtime/blob/664e232c51a5223ca41a6db5a02e824815c483ec/src/libraries/Directory.Build.targets#L24

I didn't *need* to define this property, I did it because the docs said I should. 

I'm not sure what we need to do to enable that code analysis rule.  It needs to be investigated.  Presumably whatever you find could be triggered off this property (or something similar) so you could only apply it to projects which were migrated.

To add a property to an MSBuild project you can use either the [Evaluation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.evaluation?view=msbuild-16-netcore) or [Construction](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.construction?view=msbuild-16-netcore) APIs.  Evaluation are easier to use but give you less control over where the property is written (since it's not a DOM, it's an OM)

**Comment by ViktorHofer** [comment]
This compiler warning is disabled by Arcade :(

https://github.com/dotnet/arcade/blob/d9405ccf3b5eba375b75ecbf38e3d2e090948e21/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L94

**Comment by danmoseley** [comment]
> This compiler warning is disabled in Arcade :(
> 
> https://github.com/dotnet/arcade/blob/d9405ccf3b5eba375b75ecbf38e3d2e090948e21/src/Microsoft.DotNet.Arcade.Sdk/tools/ProjectDefaults.props#L94

we can just do `<NoWarn>$(NoWarn.Replace('1591','')</NoWarn>` globally for ourselves?

**Comment by ViktorHofer** [comment]
Technically yes, but the regarding the bigger picture, Arcade is about providing the right defaults. IMO we should discuss if that setting still makes sense (it comes from roslyn's toolset repo).

**Comment by ericstj** [comment]
> I don't see this issue related to 7.0.0 in any way.

Moving this out to 8.0.0
