### ISSUE TITLE
System.Xml.XmlNode.SelectNodes return should not be nullable

### ISSUE THREAD

**Issue by MrTA2** [dotnet/runtime#49131]
### Description

No need for it to be nullable if it returns empty collection when no nodes found:
```cs
var xd = new XmlDocument();
Console.WriteLine(xd.SelectNodes("//test").Count); // output: 0 (not NullReferenceException)
```

### Configuration

.NET 5, any OS/architecture

### Regression?

N/A

**Comment by Tornhoof** [comment]
You might want to take a look at the source code:
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.Xml/src/System/Xml/Dom/XmlNode.cs#L71-L94
There are cases where the result can be null, see comments in the source.

**Comment by MrTA2** [comment]
> There are cases where the result can be null, see comments in the source.

OK I see, I would expect those cases to throw instead of returning null. I understand it would be a breaking change to start throwing instead of returning null at this point, but perhaps it makes sense? I imagine this is a very rare situation, and it's easy enough to add a static flag property which reverts back to returning null for backwards compatibility. The benefit would be that signature is non-nullable return which is appropriate in 99.99% of the cases.

**Comment by krwq** [comment]
@MrTA2 yes and no, I can imagine people calling this recursively which would be super annoying to have to handle each type separately. Perhaps the right answer might be to make this nullable when called on XNode but if you call it directly on XmlElement or so you'd get non-null, i.e.:

```csharp
partial class XmlElement
{
  // perhaps aggressive inlining so this is no-op
  public new XmlNodeList SelectNodes(string xpath)
  {
    return base.SelectNodes(xpath)!;
  }
}
```

I'm not sure if API review will be in favor of that. Would that be helpful assuming they agreed?

**Comment by MrTA2** [comment]
> @MrTA2 yes and no, I can imagine people calling this recursively which would be super annoying to have to handle each type separately. Perhaps the right answer might be to make this nullable when called on XNode but if you call it directly on XmlElement or so you'd get non-null, i.e.:
> 
> I'm not sure if API review will be in favor of that. Would that be helpful assuming they agreed?

Yes this makes sense, and please also add `XmlDocument.SelectNodes` because it inherits directly from `XmlNode`. Thank you!!

**Comment by krwq** [comment]
that would have to be added directly in the framework. I meant to add it in all places where it's not null, XmlElement was just an example

**Comment by krwq** [comment]
Honestly looking at this issue again, I don't believe it's worth to add these APIs just for the sake of nullability. Instead I'd recommend extension method:

```csharp
static class XmlNodeExtensions
{
    // use whatever name suits you
    public static XmlNodeList SelectNodes2(this XmlNode node, string xpath, XmlNamespaceManager? nsmgr = null)
    {
        if (nsmgr == null)
        {
            return node.SelectNodes(xpath) ?? new EmptyNodeList();
        }
        else
        {
            return node.SelectNodes(xpath, nsmgr) ?? new EmptyNodeList();
        }
    }

    private class EmptyNodeList : XmlNodeList
    {
        public override int Count => 0;

        public override IEnumerator GetEnumerator() => Array.Empty<XmlNode>().GetEnumerator();

        public override XmlNode? Item(int index) => null;
    }
}
```

**Comment by TahirAhmadov** [comment]
I hope you reconsider. This is becoming more and more of an issue where across multiple types and verticals in BCL, things are marked as returning nullable where it doesn't make much sense. This seriously hinders the usefulness of NRT as a feature. The purpose of it is, allow developers to clearly indicate what can and cannot be null; these nullable return methods blur that line. 

Yes I can create such extension methods, in fact, I have already created a few methods like that, but I don't quite understand why BCL has to have all these quirks with nullability.
