### ISSUE TITLE
Provide a way to reset an ArrayBufferWriter without clearing the underlying memory

### ISSUE THREAD

**Issue by john-h-k** [dotnet/runtime#49134]
## Background and Motivation

Currently there is no way to reset an `ArrayBufferWriter<T>` without zeroing the underlying memory, which can be expensive and an entirely unnecessary cost often.

## Proposed API

```diff
namespace System.Buffers
{
    public class ArrayBufferWriter<T> : IBufferWriter<T>
    {
+        public void Reset();
    }
}
```

## Usage Examples

When building short-lived buffers in high performance scenarios (for example, to generate command buffers to be sent over PCIE or network to control physical devices), being able to quickly reset the buffer writer is helpful, and zeroing is an unnecessary expense.

## Alternative Designs

It could alternatively be an overload of `Clear`:
```cs
public void Clear(bool zeroBackingArray);
```

## Risks

Types which contain references should probably still be cleared to allow collection.

**Comment by GrabYourPitchforks** [comment]
@tannergooding @pgovind any aversion to marking this ready for review? Seems like a straightforward enough proposal.

/cc @davidfowl in case you'd find it interesting in your projects.

**Comment by stephentoub** [comment]
I have to ask... do we even need a new API?  Could we instead just retcon the design:
https://github.com/stephentoub/runtime/commit/5a62634fabf4638590b270ad9e08e5fe391b345f
and say that "clearing" is just like `List<T>.Clear` semantics, which only zeros if it contains a reference?  And if we did that, does that cover enough ground that we could avoid the additional (potentially confusing) API?

**Comment by GrabYourPitchforks** [comment]
In theory this could be a behavioral break, where people clear an array writer, populate some sparse elements, then advance it again, assuming that all untouched elements will have a _default(T)_ value. Thinking back to https://github.com/dotnet/runtime/issues/30649. But this is slightly different than that issue, where here we'd not be populating the underlying array with arbitrary uninitialized data. The data would still be initialized by virtue of the fact that it was supplied by the previous caller.

So maybe the theoretical break isn't a huge concern? We could always make the change now since it's early preview and monitor feedback.

**Comment by geeknoid** [comment]
@stephentoub Yeah, the implementation of my Reset function in fact has:

        public void Reset()
        {
#if NETFW_OR_NETSTD2
            _buffer.AsSpan(0, WrittenCount).Clear();
#else
            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                _buffer.AsSpan(0, WrittenCount).Clear();
            }
#endif

            WrittenCount = 0;
        }

But given that Clear has been systematically setting the array to 0, it is definitely a breaking change to stop doing that for primitive types.

**Comment by geeknoid** [comment]
The difference with List<T>.Clear is that the unused portion of the array inside of List<T> is not visible to the user of the abstraction. The array underlying ArrayBufferWriter is visible to the outside world

**Comment by tannergooding** [comment]
@GrabYourPitchforks, I don't have an issue here. However, if we can retcon or overload the existing design like Stephen suggested, that would be better :smile:

**Comment by GrabYourPitchforks** [comment]
How about we mark this ready-for-review, bring it to API review, and discuss the compat concerns there regarding the behavioral change? Either collectively we can say "new API approved!" or "let's repurpose the existing API." Either way it's forward progress on this issue.
