### ISSUE TITLE
Microsoft.NET.Sdk.IL nuget packages is broken

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#49135]
The latest available version of the `Microsoft.NET.Sdk.IL` package on nuget.org is broken as it tries to resolve runtime ilasm/ildasm packages with a version of `6.0.0` which doesn't exist until we ship.

There are different options how to fix this:
- Generate the targets file which contains the hardcoded version dynamically and embed the product version in it. We do this in couple other places and it's fairly easy to implement.
- Change how the Sdk.IL meta package references dependencies. Today the SDK is resolved via the nuget sdk resolver in a first restore phase and then latter in the overall nuget restore phase the dependent RID specific IL package is downloaded as it's listed as a PackageReference by the IL SDK. There are alternatives to that which could be considered i.e. FrameworkPackages or merging the runtime packages which only contain the native ilasm/ildasm into the IL SDK meta package.

cc @trylek @hoyosjs @ericstj

**Comment by ViktorHofer** [comment]
TODO: Discuss if we wanna continue shipping the package on nuget.org.

**Comment by iskiselev** [comment]
This package is very useful for implementing low-level tests for profilers.

**Comment by JulieLeeMSFT** [comment]
CC @briansull PTAL.

**Comment by JulieLeeMSFT** [comment]
@Infra team, please decide on the best option between the two and implement it. JIT team does not have preference.
