### ISSUE TITLE
Crossgen2 crashes with sharing violation when trying to composite-compile into the input folder

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#49140]
Crossgen1 is often used to create the R2R image next to the input MSIL. That normally causes no problem at all as the output file has the <code>.ni.dll</code> extension. At some point in Crossgen2 development we decided not to use the ni extension so that we're tripping the fact that, if we're trying to composite compile a set of assemblies and put the output to the same folder where the input assemblies reside, the logic rewriting the component assemblies ends up trying to write to the same file it is reading, causing a sharing violation.

We either need to reinstate the .ni.dll extension or modify the logic to read each component, close the input file and only then produce the output file. In general the former is safer as rewriting files in place always has the potential idempotence problem (bugs in the rewriter may keep unused portions of the input file in the output) and is less safe in general - e.g. when the Crossgen2 app crashes on another thread while writing the output file, we'll end up with a partial invalid file that is neither the input MSIL nor the output R2R.

/cc @dotnet/crossgen-contrib 
/cc @brianrob

**Comment by davidwrighton** [comment]
Compiling a set of assemblies over top of itself is not supported. This is causing some issues for a few customers who have hand-written crossgen logic, but as its not a generally safe approach in the presence of multiple processes, etc, we should not attempt to make this work. (Also, reading the entire assembly input into memory is contrary to our goals of reducing memory use in crossgen2.)
