### ISSUE TITLE
[wasm][debugger] Properties in the watch window show "𝑓 <Property>" instead of the value of the property

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/runtime#49144]
### Describe the bug
Watch window does not show the value of properties for Blazor WASM projects, requiring you instead to navigate to and expand each property to see its value.

### To Reproduce
1. Create a new Blazor WASM project
2. Add a new .NET library project to the solution
3. Add the `Foo` class to the library with the code below
4. Add a reference to the .NET library project from the WASM project
5. Update the `FetchData.razor` page with the code below.
6. Add a breakpoint in the `Bar` property
7. Start debugging
8. Click on the "Fetch Data" link in the window
9. The program should break in the `Foo` class. Open the locals Window

### Expected Results
`this.Bar` will show the value `sample-data/weather.json`
![image](https://user-images.githubusercontent.com/612152/109882688-48744100-7c48-11eb-9122-44711ddab35e.png)
(Image shown is the locals window when the same value is viewed from a console project)

### Actual Results
`this.Bar` shows `𝑓 Bar() {}` and requires you to expand the property to view the value
![image](https://user-images.githubusercontent.com/612152/109882754-5e820180-7c48-11eb-98a3-105207891fd2.png)

#### Foo.cs
```csharp
using System;

namespace BlazorBugsLib
{
  public class Foo
  {
    public string Bar => "sample-data/weather.json";
    public string Lorem { get; set; } = "Safe";
    public string Ipsum { get; set; } = "Side";
    public Something What { get; } = new Something();
  }

  public class Something
  {
    public string Name { get; set; }
    public Something() => Name = "Name of something";
    public override string ToString() => Name;
  }
}
```

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>(new BlazorBugsLib.Foo().Bar);
  }
```

**Comment by lewing** [comment]
I'm fairly sure this is the expected behavior, you can expand the property manually.

cc @radical

**Comment by RobertBouillon** [comment]
> I'm fairly sure this is the expected behavior, you can expand the property manually.
> 
> cc @radical

Shouldn't the behavior of the watch window be the same, regardless of the runtime? 

I don't see the benefit to the change in behavior for WASM/Mono - it doesn't improve debugging, and I'd argue it makes the watch window less useful. 

It's been a pain point for me while debugging - when I need to inspect the value for 3 or 4 properties of an object, it's annoying to go into the watch window and expand the values each time.

**Comment by radical** [comment]
The reason for having it show up as a function that you have to expand was that property getters can have side effects, throw exceptions etc, so require an explicit action to invoke the getter. AFAIK, VS does some custom behavior by analyzing the code, @vargaz or @thaystg might know better. I wonder if the recent debugger changes would allow us to do something better, eventually.

`Ipsum`, `Lorem` are properties backed by fields, so we can directly read them, that's why they don't show up as functions.

As for the `ToString()` thing, I can take a look at that.

**Comment by RobertBouillon** [comment]
There is an option in Visual Studio to [disable implicit function calls](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?view=vs-2019#:~:text=Turns%20on%20automatic%20evaluation%20of%20properties%20and%20implicit%20function%20calls%20in%20variables%20windows%20and%20the%20QuickWatch%20dialog%20box.). I have implicit calls enabled in my options, so I would expect that to be the behavior unless I disable it.

> property getters can have side effects

Accessors are [expected to be free of side-effects](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties#:~:text=It%20is%20a%20bad%20programming%20style%20to%20change%20the%20state%20of%20the%20object%20by%20using%20the%20get%20accessor.). That's consistent with my experience - I've never had an accessor cause a side-effect. 

> so require an explicit action to invoke the getter

The current design language for the watch window is to provide a blue "refresh" button for values that require explicit invocation. Here is the same class in .NET Core with implicit function evaluation disabled in VS.
![image](https://user-images.githubusercontent.com/612152/110130026-926b3d00-7d96-11eb-9143-7541d80b70c0.png)

If this is a technical limitation of the WASM/Mono debugger, my hope is that we could keep an issue open so that it can be appropriately prioritized. If you're saying this is a design decision, I would like to politely object to the change. If function evaluation needs to be deferred, it should be consistent with how the Core/FW runtimes defer execution, which has additional functionality attached to it, such as [optionally forcing execution](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-csharp?view=vs-2019#:~:text=Force%20evaluation%20of%20an%20expression). The current WASM implementation also prevents access to the mutator from the watch window - from an API perspective, Properties should be functionally equivalent to fields, and that's how I'd expect them to be represented in a watch window.

**Comment by danmoseley** [comment]
> Accessors are expected to be free of side-effects. 

I don’t have context on this issue, but accessors can have side effects that are relevant to debugging, for example populating a cache, loading a type, etc.

**Comment by lewing** [comment]
@thaystg this falls into the VS settings set.  Please triage this along with the other settings and move it appropriately.

**Comment by gregsdennis** [comment]
Any traction on this?  Trying to get property values while debugging WASM is really annoying.

**Comment by radical** [comment]
@thaystg Should this be moved to 8.0?

**Comment by gregsdennis** [comment]
> Should this be moved to 8.0?

Does this need .net changes? I thought it was a VS issue.

**Comment by radical** [comment]
> > Should this be moved to 8.0?
> 
> Does this need .net changes? I thought it was a VS issue.

AFAIU, this is dependent on us getting a setting from VS, based on which we can decide the behavior. See https://github.com/dotnet/runtime/pull/71464 .

**Comment by thaystg** [comment]
As I discussed with Larry we would like to merge it on our side and hope to get the merge on VS side without any change.
I'll add the tests in the PR and we can merge both of them before RC1.

**Comment by thaystg** [comment]
I'll move it to 8.0 as we didn't get the approval for the vscode-js-debug extension.
The PR on vscode-js-debug side: https://github.com/microsoft/vscode-js-debug/pull/1323
The PR on our side: https://github.com/dotnet/runtime/pull/71464
