### ISSUE TITLE
Watch window does not execute ToString() on objects

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/runtime#49143]
### Describe the bug
The watch window doesn't execute the `ToString()` method in Blazor WASM, which is valuable in debugging to inspect identifying properties of an object without having to expand it, especially when the objects are members of a collection.

### To Reproduce
1. Create a new Blazor WASM project
2. Add a new .NET library project to the solution
3. Add the `Foo` and `Something` classes to the library with the code below
4. Add a reference to the .NET library project from the WASM project
5. Update the `FetchData.razor` page with the code below.
6. Add a breakpoint in the `Bar` property
7. Start debugging
8. Click on the "Fetch Data" link in the window
9. The program should break in the `Foo` class. Open the locals Window

### Expected Results
The `What` property shows the result of `ToString` (`Name of Something`)
![image](https://user-images.githubusercontent.com/612152/109882688-48744100-7c48-11eb-9122-44711ddab35e.png)
(Image shown is the locals window when the same value is viewed from a console project)

### Actual Results
The `What` property shows the name of the type (`BlazorBugsLib.Something`)
![image](https://user-images.githubusercontent.com/612152/109882754-5e820180-7c48-11eb-98a3-105207891fd2.png)

#### Foo.cs
```csharp
using System;

namespace BlazorBugsLib
{
  public class Foo
  {
    public string Bar => "sample-data/weather.json";
    public string Lorem { get; set; } = "Safe";
    public string Ipsum { get; set; } = "Side";
    public Something What { get; } = new Something();
  }

  public class Something
  {
    public string Name { get; set; }
    public Something() => Name = "Name of something";
    public override string ToString() => Name;
  }
}
```

#### FetchData.razor
```csharp
  protected override async Task OnInitializedAsync()
  {
    forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>(new BlazorBugsLib.Foo().Bar);
  }
```

**Comment by lewing** [comment]
cc @radical

**Comment by RobertBouillon** [comment]
I just realized I can't execute `ToString` at all, even explicitly. Is this related, or should I log a different issue?
![image](https://user-images.githubusercontent.com/612152/110510199-f496ab80-80d0-11eb-8c5b-9069dc55bc99.png)

**Comment by radical** [comment]
It doesn't support calling any methods yet (https://github.com/dotnet/runtime/issues/45596).

**Comment by thaystg** [comment]
It's working.
