### ISSUE TITLE
[Perf] Regression in Perf_FileStream

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#49156]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [d5ab93c4a8e45da2dab8924c2165000bf78f84e6](https://github.com/dotnet/runtime/commit/d5ab93c4a8e45da2dab8924c2165000bf78f84e6)
Compare | [cbb5b905d67a91ecf293c8807414b7791713b02d](https://github.com/dotnet/runtime/commit/cbb5b905d67a91ecf293c8807414b7791713b02d)

### Regressions in System.IO.Tests.Perf_FileStream

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[ReadByte](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.ReadByte(fileSize%3a%201024%2c%20options%3a%20None).html>) | 7.15 μs | 8.49 μs | 1.19 | | |
[ReadAsync](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.ReadAsync(fileSize%3a%201024%2c%20userBufferSize%3a%20512%2c%20options%3a%20None).html>) | 7.87 μs | 8.35 μs | 1.06 | | |
[OpenClose](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.OpenClose(fileSize%3a%201024%2c%20options%3a%20None).html>) | 2.87 μs | 3.28 μs | 1.15 | | |
[Read](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.Read(fileSize%3a%201024%2c%20userBufferSize%3a%20512%2c%20options%3a%20None).html>) | 4.44 μs | 4.86 μs | 1.10 | | |
[ReadAsync](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.ReadAsync(fileSize%3a%201024%2c%20userBufferSize%3a%204096%2c%20options%3a%20None).html>) | 5.92 μs | 6.30 μs | 1.06 | | |
[ReadAsync](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.ReadAsync(fileSize%3a%201024%2c%20userBufferSize%3a%20512%2c%20options%3a%20Asynchronous).html>) | 6.52 μs | 7.88 μs | 1.21 | | |
[ReadByte](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.Perf_FileStream.ReadByte(fileSize%3a%201024%2c%20options%3a%20Asynchronous).html>) | 6.96 μs | 8.79 μs | 1.26 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/System.IO.Tests.Perf_FileStream.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.IO.Tests.Perf_FileStream*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c4316b10-2827-43b2-9202-35fa92d411d5ffed5869d4a44c1ba/ef654eb0-792d-4711-818e-5a80f537f902.zip?sv=2019-07-07&se=2021-03-25T12%3A41%3A13Z&sr=c&sp=rl&sig=E6HssM1x15P5gf57MKTht1myb0QFeRVHnMd4t2Grk9E%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-8c0a29a3-6173-401c-90a7-05d753da88c040f6f78cbfa4d2694/dc286753-1aa7-4fd0-9c68-00e932cd1d18.zip?sv=2019-07-07&se=2021-03-26T23%3A12%3A39Z&sr=c&sp=rl&sig=8WZqU4fQUpUB4q6dUAUcuSV%2F7%2Fl7KX1dKinwRVY1vxg%3D>)

#### System.IO.Tests.Perf_FileStream.ReadByte(fileSize: 1024, options: None)

```log
[6826.607 ; 7055.656) | @@@@@@@@@@@@@@@@@@@@
[7055.656 ; 7272.377) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7272.377 ; 7544.007) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7544.007 ; 7788.644) | @@@@@@@@@@@@@@@@@@@@@@@@
[7788.644 ; 7956.825) | @@@@
[7956.825 ; 8115.204) | 
[8115.204 ; 8369.989) | @@@@@@@@@
[8369.989 ; 8586.710) | @@@@@@@@@@@@
[8586.710 ; 8835.881) | @@@
```
#### System.IO.Tests.Perf_FileStream.ReadAsync(fileSize: 1024, userBufferSize: 512, options: None)

```log
[7063.669 ; 7262.293) | @@@@@@@@
[7262.293 ; 7474.602) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7474.602 ; 7804.894) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7804.894 ; 7976.427) | @
[7976.427 ; 8188.736) | 
[8188.736 ; 8470.922) | @@@@@
[8470.922 ; 8683.231) | @@@@@@@@@@@@@@@@@
[8683.231 ; 8915.446) | @@@@
```
#### System.IO.Tests.Perf_FileStream.OpenClose(fileSize: 1024, options: None)

```log
[2783.082 ; 2841.874) | @@@@@
[2841.874 ; 2907.343) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[2907.343 ; 2977.449) | @@@@@@@@@@@@@@
[2977.449 ; 3085.689) | @@@@@@@@@@@@@
[3085.689 ; 3151.158) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3151.158 ; 3225.832) | @@@@@@@
[3225.832 ; 3374.205) | @@@@@@@@@
```
#### System.IO.Tests.Perf_FileStream.Read(fileSize: 1024, userBufferSize: 512, options: None)

```log
[3971.800 ; 4074.625) | @@
[4074.625 ; 4222.991) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[4222.991 ; 4382.773) | @@@@@@@
[4382.773 ; 4531.139) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[4531.139 ; 4635.424) | @@
[4635.424 ; 4795.866) | @
[4795.866 ; 4944.232) | @@@@@@@@@@@@@@@
[4944.232 ; 5087.227) | @
[5087.227 ; 5235.593) | @@@@@@@
[5235.593 ; 5343.453) | @
```
#### System.IO.Tests.Perf_FileStream.ReadAsync(fileSize: 1024, userBufferSize: 4096, options: None)

```log
[5706.751 ; 5865.598) | @@@@@@@@@@@
[5865.598 ; 6071.241) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[6071.241 ; 6200.468) | @@@@@
[6200.468 ; 6434.972) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[6434.972 ; 6698.726) | @@@@@@
```
#### System.IO.Tests.Perf_FileStream.ReadAsync(fileSize: 1024, userBufferSize: 512, options: Asynchronous)

```log
[6223.449 ; 6426.159) | @@@@
[6426.159 ; 6638.275) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[6638.275 ; 6788.627) | @@@@
[6788.627 ; 7000.743) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7000.743 ; 7144.171) | @@@
[7144.171 ; 7356.287) | 
[7356.287 ; 7530.518) | 
[7530.518 ; 7742.634) | @@@@@@@@@@@@@@
[7742.634 ; 8046.329) | @@@@@@@@@@@
```
#### System.IO.Tests.Perf_FileStream.ReadByte(fileSize: 1024, options: Asynchronous)

```log
[6899.512 ; 7152.184) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7152.184 ; 7436.475) | @@@@@@@@@@@@@@@@
[7436.475 ; 7689.147) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7689.147 ; 7955.746) | @@@@@@@@@@@@@@@@@@@@@@@
[7955.746 ; 8330.840) | @
[8330.840 ; 8583.512) | @@@@@@@@@@@@@@@@
[8583.512 ; 8833.601) | @@@@@@@@
[8833.601 ; 9057.500) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
Probably related to https://github.com/dotnet/runtime/pull/47128

**Comment by stephentoub** [comment]
cc: @adamsitnik

**Comment by DrewScoggins** [comment]
We are also seeing some wins from this change in BinaryWriter.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [d5ab93c4a8e45da2dab8924c2165000bf78f84e6](https://github.com/dotnet/runtime/commit/d5ab93c4a8e45da2dab8924c2165000bf78f84e6)
Compare | [cbb5b905d67a91ecf293c8807414b7791713b02d](https://github.com/dotnet/runtime/commit/cbb5b905d67a91ecf293c8807414b7791713b02d)


### Improvemnts in System.IO.Tests.BinaryWriterTests

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[WriteUInt32](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteUInt32.html>) | 25.92 ns | 1.75 ns | 0.07 | | |
[WriteUInt16](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteUInt16.html>) | 26.78 ns | 1.76 ns | 0.07 | | |
[WriteSingle](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteSingle.html>) | 26.01 ns | 2.04 ns | 0.08 | | |
[WriteNonAsciiChar](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteNonAsciiChar.html>) | 28.94 ns | 4.61 ns | 0.16 | | |
[WriteUInt64](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteUInt64.html>) | 25.80 ns | 1.76 ns | 0.07 | | |
[WriteAsciiChar](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteAsciiChar.html>) | 28.47 ns | 4.33 ns | 0.15 | | |
[WriteDouble](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.IO.Tests.BinaryWriterTests.WriteDouble.html>) | 25.52 ns | 2.04 ns | 0.08 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Improvement/System.IO.Tests.BinaryWriterTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.IO.Tests.BinaryWriterTests*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c4316b10-2827-43b2-9202-35fa92d411d5ffed5869d4a44c1ba/ef654eb0-792d-4711-818e-5a80f537f902.zip?sv=2019-07-07&se=2021-03-25T12%3A41%3A13Z&sr=c&sp=rl&sig=E6HssM1x15P5gf57MKTht1myb0QFeRVHnMd4t2Grk9E%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-8c0a29a3-6173-401c-90a7-05d753da88c040f6f78cbfa4d2694/dc286753-1aa7-4fd0-9c68-00e932cd1d18.zip?sv=2019-07-07&se=2021-03-26T23%3A12%3A39Z&sr=c&sp=rl&sig=8WZqU4fQUpUB4q6dUAUcuSV%2F7%2Fl7KX1dKinwRVY1vxg%3D>)

### Histogram
#### System.IO.Tests.BinaryWriterTests.WriteUInt32

```log
[-0.377 ;  3.990) | @@@@@@@@@@@@@@@@@@@@@@@@
[ 3.990 ;  8.244) | 
[ 8.244 ; 12.499) | 
[12.499 ; 16.753) | 
[16.753 ; 21.008) | 
[21.008 ; 25.465) | 
[25.465 ; 29.720) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.IO.Tests.BinaryWriterTests.WriteUInt16

```log
[-0.459 ;  3.953) | @@@@@@@@@@@@@@@@@@@@@@@@@
[ 3.953 ;  8.347) | 
[ 8.347 ; 12.742) | 
[12.742 ; 17.136) | 
[17.136 ; 21.530) | 
[21.530 ; 25.742) | 
[25.742 ; 30.136) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[30.136 ; 32.757) | @@
```
#### System.IO.Tests.BinaryWriterTests.WriteSingle

```log
[-0.317 ;  4.107) | @@@@@@@@@@@@@@@@@@@@@@@@@
[ 4.107 ;  8.384) | 
[ 8.384 ; 12.660) | 
[12.660 ; 16.937) | 
[16.937 ; 21.213) | 
[21.213 ; 25.404) | 
[25.404 ; 29.681) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29.681 ; 31.910) | @
```
#### System.IO.Tests.BinaryWriterTests.WriteNonAsciiChar

```log
[ 2.406 ;  6.934) | @@@@@@@@@@@@@@@@@@@@@@@@
[ 6.934 ; 11.229) | 
[11.229 ; 15.524) | 
[15.524 ; 19.819) | 
[19.819 ; 24.114) | 
[24.114 ; 28.112) | 
[28.112 ; 32.407) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[32.407 ; 36.890) | @@@
```
#### System.IO.Tests.BinaryWriterTests.WriteUInt64

```log
[-0.364 ;  4.011) | @@@@@@@@@@@@@@@@@@@@@@@@@
[ 4.011 ;  8.253) | 
[ 8.253 ; 12.495) | 
[12.495 ; 16.737) | 
[16.737 ; 20.980) | 
[20.980 ; 25.146) | 
[25.146 ; 29.388) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29.388 ; 32.433) | @@
```
#### System.IO.Tests.BinaryWriterTests.WriteAsciiChar

```log
[ 2.079 ;  6.435) | @@@@@@@@@@@@@@@@@@@@@@@@@
[ 6.435 ; 10.706) | 
[10.706 ; 14.976) | 
[14.976 ; 19.247) | 
[19.247 ; 23.518) | 
[23.518 ; 27.696) | 
[27.696 ; 31.967) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.IO.Tests.BinaryWriterTests.WriteDouble

```log
[-0.114 ;  4.203) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[ 4.203 ;  8.498) | 
[ 8.498 ; 12.793) | 
[12.793 ; 17.088) | 
[17.088 ; 21.383) | 
[21.383 ; 24.924) | 
[24.924 ; 29.219) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29.219 ; 33.601) | @@@@@
```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by adamsitnik** [comment]
This is very interesting as it seems to be `Unix` specific regression as Windows charts seem to no be affected:

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_Windows%2010.0.18362/System.IO.Tests.Perf_FileStream.ReadAsync(fileSize%3a%201024%2c%20userBufferSize%3a%20512%2c%20options%3a%20None).html
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_Windows%2010.0.18362/System.IO.Tests.Perf_FileStream.OpenClose(fileSize%3a%201024%2c%20options%3a%20None).html
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_Windows%2010.0.18362/System.IO.Tests.Perf_FileStream.OpenClose(fileSize%3a%201024%2c%20options%3a%20None).html

![obraz](https://user-images.githubusercontent.com/6011991/110099835-0ced8a00-7da2-11eb-9a7c-6518714a3726.png)

![obraz](https://user-images.githubusercontent.com/6011991/110099872-170f8880-7da2-11eb-90bf-13e0b3b1e7a7.png)

![obraz](https://user-images.githubusercontent.com/6011991/110099985-34445700-7da2-11eb-94d9-fd4ab2af9389.png)

@AndyAyersMS In #47128 I've basically introduced a new abstraction layer, so all the `FileStream` method calls are now including the overhead of an additional virtual method call (class, not interface). Is it possible that it's more expensive on Unix compared to Windows?

**Comment by adamsitnik** [comment]
> We are also seeing some wins from this change in BinaryWriter.

@GrabYourPitchforks

**Comment by AndyAyersMS** [comment]
> Is it possible that it's more expensive on Unix compared to Windows

The virtual call sequence is the same on both. 

There might be some other sources of call overhead. For instance if you are just forwarding struct args, there might be some extra shuffling about on Linux as the jit may not smoothly handle the way the Linux ABI requires structs to be passed in registers.

Would be good to look at some of the actual codegen.

**Comment by adamsitnik** [comment]
Overall we were able to solve most of the regressions and even turn most of them into improvements. 

<details>

|                 Method |  Runtime |  fileSize | userBufferSize |      options |             Mean | Ratio |   Allocated |
|----------------------- |--------- |---------- |--------------- |------------- |-----------------:|------:|------------:|
|                   Read | .NET 5.0 |      1024 |           1024 |         None |         5.176 μs |  1.00 |     4,280 B |
|                   Read | .NET 6.0 |      1024 |           1024 |         None |         5.903 μs |  1.14 |     4,336 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |      1024 |           1024 |         None |         9.314 μs |  1.00 |     4,665 B |
|              ReadAsync | .NET 6.0 |      1024 |           1024 |         None |         9.257 μs |  0.99 |     4,952 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 |      1024 |           1024 | Asynchronous |         7.987 μs |  1.00 |     4,520 B |
|                   Read | .NET 6.0 |      1024 |           1024 | Asynchronous |         5.884 μs |  0.74 |     4,336 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |      1024 |           1024 | Asynchronous |         9.196 μs |  1.00 |     4,706 B |
|              ReadAsync | .NET 6.0 |      1024 |           1024 | Asynchronous |         9.374 μs |  1.02 |     4,952 B |
|                        |          |           |                |              |                  |       |             |
|              OpenClose | .NET 5.0 |      1024 |              ? |         None |         3.395 μs |  1.00 |       160 B |
|              OpenClose | .NET 6.0 |      1024 |              ? |         None |         3.679 μs |  1.08 |       216 B |
|                        |          |           |                |              |                  |       |             |
|               ReadByte | .NET 5.0 |      1024 |              ? |         None |         9.223 μs |  1.00 |     4,280 B |
|               ReadByte | .NET 6.0 |      1024 |              ? |         None |         8.729 μs |  0.95 |     4,336 B |
|                        |          |           |                |              |                  |       |             |
|              OpenClose | .NET 5.0 |      1024 |              ? | Asynchronous |         3.505 μs |  1.00 |       280 B |
|              OpenClose | .NET 6.0 |      1024 |              ? | Asynchronous |         3.669 μs |  1.05 |       216 B |
|                        |          |           |                |              |                  |       |             |
|               ReadByte | .NET 5.0 |      1024 |              ? | Asynchronous |         9.302 μs |  1.00 |     4,400 B |
|               ReadByte | .NET 6.0 |      1024 |              ? | Asynchronous |         8.628 μs |  0.93 |     4,336 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 |   1048576 |            512 |         None |       247.484 μs |  1.00 |     4,280 B |
|                   Read | .NET 6.0 |   1048576 |            512 |         None |       250.115 μs |  1.01 |     4,337 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |   1048576 |            512 |         None |     3,550.898 μs |  1.00 |   233,997 B |
|              ReadAsync | .NET 6.0 |   1048576 |            512 |         None |       674.037 μs |  0.19 |     5,019 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 |   1048576 |            512 | Asynchronous |       935.502 μs |  1.00 |    35,194 B |
|                   Read | .NET 6.0 |   1048576 |            512 | Asynchronous |       247.268 μs |  0.26 |     4,337 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |   1048576 |            512 | Asynchronous |       744.525 μs |  1.00 |    35,369 B |
|              ReadAsync | .NET 6.0 |   1048576 |            512 | Asynchronous |       663.037 μs |  0.91 |     5,019 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 |   1048576 |           4096 |         None |       199.518 μs |  1.00 |       160 B |
|                   Read | .NET 6.0 |   1048576 |           4096 |         None |       193.003 μs |  0.97 |       217 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |   1048576 |           4096 |         None |       537.004 μs |  1.00 |    29,169 B |
|              ReadAsync | .NET 6.0 |   1048576 |           4096 |         None |       375.843 μs |  0.72 |       706 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 |   1048576 |           4096 | Asynchronous |       698.735 μs |  1.00 |    31,007 B |
|                   Read | .NET 6.0 |   1048576 |           4096 | Asynchronous |       197.665 μs |  0.28 |       217 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 |   1048576 |           4096 | Asynchronous |       499.676 μs |  1.00 |    31,249 B |
|              ReadAsync | .NET 6.0 |   1048576 |           4096 | Asynchronous |       398.217 μs |  0.81 |       706 B |
|                        |          |           |                |              |                  |       |             |
|       Read_NoBuffering | .NET 5.0 |   1048576 |          16384 |         None |        97.330 μs |  1.00 |       160 B |
|       Read_NoBuffering | .NET 6.0 |   1048576 |          16384 |         None |        94.391 μs |  0.97 |       152 B |
|                        |          |           |                |              |                  |       |             |
|  ReadAsync_NoBuffering | .NET 5.0 |   1048576 |          16384 |         None |       187.578 μs |  1.00 |     7,664 B |
|  ReadAsync_NoBuffering | .NET 6.0 |   1048576 |          16384 |         None |       154.951 μs |  0.83 |       553 B |
|                        |          |           |                |              |                  |       |             |
|       Read_NoBuffering | .NET 5.0 |   1048576 |          16384 | Asynchronous |       242.897 μs |  1.00 |     7,963 B |
|       Read_NoBuffering | .NET 6.0 |   1048576 |          16384 | Asynchronous |        94.803 μs |  0.39 |       152 B |
|                        |          |           |                |              |                  |       |             |
|  ReadAsync_NoBuffering | .NET 5.0 |   1048576 |          16384 | Asynchronous |       189.687 μs |  1.00 |     8,208 B |
|  ReadAsync_NoBuffering | .NET 6.0 |   1048576 |          16384 | Asynchronous |       158.541 μs |  0.84 |       553 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 | 104857600 |           4096 |         None |    25,135.499 μs |  1.00 |       192 B |
|                   Read | .NET 6.0 | 104857600 |           4096 |         None |    24,536.448 μs |  0.98 |       307 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 | 104857600 |           4096 |         None |    49,196.600 μs |  1.00 | 2,867,768 B |
|              ReadAsync | .NET 6.0 | 104857600 |           4096 |         None |    41,890.758 μs |  0.85 |     1,124 B |
|                        |          |           |                |              |                  |       |             |
|                   Read | .NET 5.0 | 104857600 |           4096 | Asynchronous |    73,430.245 μs |  1.00 | 3,072,558 B |
|                   Read | .NET 6.0 | 104857600 |           4096 | Asynchronous |    24,432.030 μs |  0.33 |       307 B |
|                        |          |           |                |              |                  |       |             |
|              ReadAsync | .NET 5.0 | 104857600 |           4096 | Asynchronous |    48,793.215 μs |  1.00 | 3,072,600 B |
|              ReadAsync | .NET 6.0 | 104857600 |           4096 | Asynchronous |    42,725.572 μs |  0.88 |     1,124 B |
|                        |          |           |                |              |                  |       |             |
|       Read_NoBuffering | .NET 5.0 | 104857600 |          16384 |         None |    14,831.359 μs |  1.00 |       178 B |
|       Read_NoBuffering | .NET 6.0 | 104857600 |          16384 |         None |    14,530.633 μs |  0.98 |       203 B |
|                        |          |           |                |              |                  |       |             |
|  ReadAsync_NoBuffering | .NET 5.0 | 104857600 |          16384 |         None |    23,819.030 μs |  1.00 |   717,354 B |
|  ReadAsync_NoBuffering | .NET 6.0 | 104857600 |          16384 |         None |    18,961.480 μs |  0.80 |       644 B |
|                        |          |           |                |              |                  |       |             |
|       Read_NoBuffering | .NET 5.0 | 104857600 |          16384 | Asynchronous |    29,551.924 μs |  1.00 |   769,481 B |
|       Read_NoBuffering | .NET 6.0 | 104857600 |          16384 | Asynchronous |    14,482.452 μs |  0.49 |       203 B |
|                        |          |           |                |              |                  |       |             |
|  ReadAsync_NoBuffering | .NET 5.0 | 104857600 |          16384 | Asynchronous |    21,595.085 μs |  1.00 |   768,557 B |
|  ReadAsync_NoBuffering | .NET 6.0 | 104857600 |          16384 | Asynchronous |    18,861.580 μs |  0.87 |       668 B |

</details>
