### ISSUE TITLE
CLR fails to return reference types inside return buffer when invoking this call with function pointers

### ISSUE THREAD

**Issue by aromaa** [dotnet/runtime#49159]
### Description
There seems to be an issue when returning reference types inside a return buffer when invoking managed instance methods with function pointers. This issue isn't present when the return buffer contains only value types. Also the method is able to return reference types when the return buffer isn't used.

The compiler doesn't permit creating a function pointer directly from instance methods but by getting the method pointer with reflection you can cast it to function pointer that can correctly represent this calls.

The following code crashes the CLR:
```csharp
using System;

namespace CLRTesting
{
	internal static unsafe class Program
	{
		private static readonly delegate*<Test, Tuple<string, int>> ReturnTupleFunctionPointer = (delegate*<Test, Tuple<string, int>>)typeof(Test).GetMethod(nameof(Test.ReturnTuple)).MethodHandle.GetFunctionPointer();
		private static readonly delegate*<Test, (int, int)> ReturnValueTupleFunctionPointer = (delegate*<Test, (int, int)>)typeof(Test).GetMethod(nameof(Test.ReturnValueTuple)).MethodHandle.GetFunctionPointer();
		private static readonly delegate*<Test, (string, int)> ReturnValueTupleWithRefFunctionPointer = (delegate*<Test, (string, int)>)typeof(Test).GetMethod(nameof(Test.ReturnValueTupleWithRef)).MethodHandle.GetFunctionPointer();

		private static void Main(string[] args)
		{
			Test testObject = new();

			Program.ReturnTuple(testObject);
			Program.ReturnValueTuple(testObject);
			Program.ReturnValueTupleWithRef(testObject);
		}

		private static void ReturnTuple(Test testObject) //Works just fine
		{
			Console.WriteLine(Program.ReturnTupleFunctionPointer(testObject));

			GC.Collect();
		}

		private static void ReturnValueTuple(Test testObject) //Works just fine
		{
			Console.WriteLine(Program.ReturnValueTupleFunctionPointer(testObject));

			GC.Collect();
		}

		private static void ReturnValueTupleWithRef(Test testObject) //Explodes
		{
			Console.WriteLine(Program.ReturnValueTupleWithRefFunctionPointer(testObject)); //Wrong result

			GC.Collect(); //Crash!
		}
	}

	internal sealed class Test
	{
		public Tuple<string, int> ReturnTuple()
		{
			return Tuple.Create(".NET", 3);
		}

		public (int value1, int value2) ReturnValueTuple()
		{
			return (0x3, 0x9);
		}
		
		public (string obj, int value) ReturnValueTupleWithRef()
		{
			return (".NET", 3);
		}
	}
}
```

### Configuration
Tested on 5.0.200 using Windows 10 x64

### Other information
When executing the sample you get the following output:
```
(.NET, 3)
(3, 9)
(, 0)
```

But the expected output would be:
```
(.NET, 3)
(3, 9)
(.NET, 3)
```

**Comment by jkotas** [comment]
C# function pointers can only point to static methods. 

Your repro makes the static delegate to point to instance method. It leads to calling convention mismatch and crash.

**Comment by jkotas** [comment]
This restriction is documented e.g. in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers

**Comment by jkotas** [comment]
> The compiler doesn't permit creating a function pointer directly from instance methods but by getting the method pointer with reflection you can cast it to function pointer that can correctly represent this calls.

Right, the compiler does not permit it for a good reason. It does always work. The exact situations where it does not work vary between platforms.

**Comment by aromaa** [comment]
> C# function pointers can only point to static methods.
> 
> Your repro makes the static delegate to point to instance method. It leads to calling convention mismatch and crash.

Ah. I see my mistake now. I first thought that the CLR is actually able to handle the instance call and figure out the correct way to call it (with return buffer or not) and the compiler restriction was just for other reasons (like design), but I was just getting lucky. I did a bit more testing and figured out what I was doing wrong.

The first case works because its able to return the reference in the register so return buffer isn't used. (This I already knew)

The second case works because its actually able to return the values in the register. (I though this case was using return buffer (its not), leaving me the idea that the CLR is able to figure it out) But by returning anything larger than 8 bytes it crashes as it has to use the return buffer.

The third case has to use return buffer. Because the CLR doesn't know this it was using the this parameter as the return buffer pointer, writing to the heap and crashing the GC. So by providing first the return buffer pointer and then the this pointer it should work.

@jkotas The Book of the Runtime doesn't seem to mention anything about ARM calling convention on the CLR ABI but does mention about x86, is there any differences? I'm not familiar with ARM at all so I can't really say much.

And the following code does work properly:
```csharp
namespace CLRTesting
{
	internal static unsafe class Program
	{
		private static readonly delegate*<void*, Test, (string, int)> ReturnValueTupleWithRefFunctionPointer = (delegate*<void*, Test, (string, int)>)typeof(Test).GetMethod(nameof(Test.ReturnValueTupleWithRef)).MethodHandle.GetFunctionPointer();

		private static void Main(string[] args)
		{
			Test testObject = new();
			
			Program.ReturnValueTupleWithRef(testObject);
		}

		private static void ReturnValueTupleWithRef(Test testObject)
		{
			Unsafe.SkipInit(out (string, int) returnBuffer);

			Program.ReturnValueTupleWithRefFunctionPointer(Unsafe.AsPointer(ref returnBuffer), testObject);

			Console.WriteLine(returnBuffer); //Correct result

			GC.Collect(); //No crash!
		}
	}

	internal sealed class Test
	{
		public (string obj, int value) ReturnValueTupleWithRef()
		{
			return (".NET", 3);
		}
	}
}
```

**Comment by jkotas** [comment]
The CoreCLR calling conventions are documented in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md . Note that the calling conventions are subject to change (we have changed them number of times over the years), and Mono runtime uses a different calling conventions.

**Comment by aromaa** [comment]
> The CoreCLR calling conventions are documented in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md . Note that the calling conventions are subject to change (we have changed them number of times over the years), and Mono runtime uses different calling conventions.

I was looking at that and unless I'm blind I can't really see any mentions about the ARM calling convention? Not that it really matters as I don't intend to run this on any other platforms than x86.

I'm very well aware that I'm pretty much doing something that you shouldn't at the first place and I'm expecting it to break between releases. Just doing something for fun and trying to see how much overhead I can cut out.

Also I can't recall but are there any JIT time constants about platforms? I could detect ARM by checking for the ARM specific intrinsic (like ArmBase.IsSupported) or make readonly static fields to switch which calling convention to use.

**Comment by jkotas** [comment]
> I was looking at that and unless I'm blind I can't really see any mentions about the ARM calling convention?

Look for:

    ARM: See Overview of ARM ABI Conventions".

    The CLR follows those basic conventions. This document only describes things that are CLR-specific, or exceptions from those documents.

> I can't recall but are there any JIT time constants about platforms?

Take a look at RuntimeInformation.ProcessArchitecture property.
