### ISSUE TITLE
[Perf] Regression in Perf_Decimal Parsing

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#49164]
### Run Information

Architecture | arm64
-- | --
OS | ubuntu 18.04
Baseline | [121b732e8b17470fd1cb7df26c32bfce415f966e](https://github.com/dotnet/runtime/commit/121b732e8b17470fd1cb7df26c32bfce415f966e)
Compare | [34c68c7edf6d61c8ff3d2631003ed86353415479](https://github.com/dotnet/runtime/commit/34c68c7edf6d61c8ff3d2631003ed86353415479)

### Regressions in System.Tests.Perf_Decimal

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Parse](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_arm64_ubuntu 18.04/System.Tests.Perf_Decimal.Parse(value%3a%20%22123456.789%22).html>) | 204.47 ns | 219.52 ns | 1.07 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_arm64_ubuntu%2018.04_Regression/System.Tests.Perf_Decimal_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_arm64_ubuntu%2018.04_Regression/System.Tests.Perf_Decimal.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Decimal*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-62715f89-8df5-42b3-a8c1-7c3ebdf3a1402ab17f54ef34d11b0/cd6ec7bd-ca7d-4af8-8747-df2be23f7780.zip?sv=2019-07-07&se=2021-03-28T21%3A17%3A21Z&sr=c&sp=rl&sig=cX9VUxdho%2BB3N6Gdl%2BIPe0SBIxmKz31s825N5RrtZxQ%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-8deaa320-1652-484e-8d36-513519cd20f09d4513a6f4549348a/4dd42ee7-e5b4-4738-ae09-a6f8f1d02ded.zip?sv=2019-07-07&se=2021-03-29T06%3A29%3A38Z&sr=c&sp=rl&sig=qkVPYA7igVh1VD1dzjO6YrFHPhBJBpPh9ssrCn1wnuo%3D>)

#### System.Tests.Perf_Decimal.Parse(value: "123456.789")

```log
[196.318 ; 203.796) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[203.796 ; 210.505) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[210.505 ; 216.226) | @@@@@@@@@@@@
[216.226 ; 225.128) | @@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | ubuntu 18.04
Baseline | [121b732e8b17470fd1cb7df26c32bfce415f966e](https://github.com/dotnet/runtime/commit/121b732e8b17470fd1cb7df26c32bfce415f966e)
Compare | [34c68c7edf6d61c8ff3d2631003ed86353415479](https://github.com/dotnet/runtime/commit/34c68c7edf6d61c8ff3d2631003ed86353415479)

### Regressions in System.Tests.Perf_Single

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Parse](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_arm64_ubuntu 18.04/System.Tests.Perf_Single.Parse(value%3a%20%2212345%22).html>) | 168.81 ns | 193.07 ns | 1.14 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_arm64_ubuntu%2018.04_Regression/System.Tests.Perf_Single_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_arm64_ubuntu%2018.04_Regression/System.Tests.Perf_Single.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Single*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-62715f89-8df5-42b3-a8c1-7c3ebdf3a1402ab17f54ef34d11b0/cd6ec7bd-ca7d-4af8-8747-df2be23f7780.zip?sv=2019-07-07&se=2021-03-28T21%3A17%3A21Z&sr=c&sp=rl&sig=cX9VUxdho%2BB3N6Gdl%2BIPe0SBIxmKz31s825N5RrtZxQ%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-8deaa320-1652-484e-8d36-513519cd20f09d4513a6f4549348a/4dd42ee7-e5b4-4738-ae09-a6f8f1d02ded.zip?sv=2019-07-07&se=2021-03-29T06%3A29%3A38Z&sr=c&sp=rl&sig=qkVPYA7igVh1VD1dzjO6YrFHPhBJBpPh9ssrCn1wnuo%3D>)

#### System.Tests.Perf_Single.Parse(value: "12345")

```log
[149.872 ; 155.818) | @@
[155.818 ; 159.684) | @@@
[159.684 ; 163.423) | @@@@@@@@@@@@@@@
[163.423 ; 169.396) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[169.396 ; 172.996) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[172.996 ; 177.678) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[177.678 ; 183.938) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[183.938 ; 187.788) | @@@@
[187.788 ; 194.175) | @@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x86
-- | --
OS | Windows 10.0.18362
Baseline | [afa7e276d8f87c8b73d09b833b6b4066700ffa12](https://github.com/dotnet/runtime/commit/afa7e276d8f87c8b73d09b833b6b4066700ffa12)
Compare | [9102b07d846d812963420f022ce55ee1cbdb3b17](https://github.com/dotnet/runtime/commit/9102b07d846d812963420f022ce55ee1cbdb3b17)

### Regressions in System.Tests.Perf_Decimal

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[TryParse](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x86_Windows 10.0.18362/System.Tests.Perf_Decimal.TryParse(value%3a%20%22123456.789%22).html>) | 129.33 ns | 136.55 ns | 1.06 | 1355.422983221852 | 1399.4650819036542 | 1.0324932506139992 | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-3821dd0284e24cfaba/Collect%20System.Tests.Perf_Decimal.TryParse/artifacts/BenchmarkDotNet.Artifacts/System.Tests.Perf_Decimal.TryParse%28value_%20_123456.789_%29-20210302-021619.etl?sv=2019-07-07&se=2021-05-31T10%3A12%3A52Z&sr=c&sp=rl&sig=gi09rzzIHPODkQtb%2Bp0CNlNSWJH5OaeGxVkO73bWcpo%3D) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-1d65f5a536d245058c/Collect%20System.Tests.Perf_Decimal.TryParse/artifacts/BenchmarkDotNet.Artifacts/System.Tests.Perf_Decimal.TryParse%28value_%20_123456.789_%29-20210302-021614.etl?sv=2019-07-07&se=2021-05-31T10%3A12%3A52Z&sr=c&sp=rl&sig=4mQsCqYtgksGXtldmnCqHmF1SsXgTZxgDv5bU6KDna0%3D)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x86_Windows%2010.0.18362_Regression/System.Tests.Perf_Decimal_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x86_Windows%2010.0.18362_Regression/System.Tests.Perf_Decimal.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Decimal*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-187f0ef3-43d4-4ba1-a316-27ac58fcb8bf22fd0b5719e40649d/5149bd69-2c38-4321-a890-8f68a8e97691.zip?sv=2019-07-07&se=2021-03-28T18%3A29%3A21Z&sr=c&sp=rl&sig=q4IXYggvwLhPtpiyKji6zvwKiq1H2cK%2FmRIhSkHdzic%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-a142a289-ff4b-4f16-83b4-edd8d894d0f77a65a2ef2d9482ea2/7c7ce25e-dc62-4940-8fb4-a9474ea425c7.zip?sv=2019-07-07&se=2021-03-29T03%3A33%3A06Z&sr=c&sp=rl&sig=ZJvYMMHl555sKNheBiwqyYPvSN9IG%2FrgRQMbBuUSG7c%3D>)

#### System.Tests.Perf_Decimal.TryParse(value: "123456.789")

```log
[117.728 ; 121.262) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[121.262 ; 124.149) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[124.149 ; 127.620) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[127.620 ; 132.130) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[132.130 ; 134.873) | @
[134.873 ; 137.783) | @@@@@@@@@@
[137.783 ; 141.221) | @@
[141.221 ; 146.443) | @
```
### Baseline Jit Disasm

```assembly
; System.Tests.Perf_Decimal.TryParse(System.String)
       push      ebp
       mov       ebp,esp
       sub       esp,10
       vzeroupper
       xor       eax,eax
       mov       [ebp+0FFF0],eax
       mov       [ebp+0FFF4],eax
       mov       [ebp+0FFF8],eax
       mov       [ebp+0FFFC],eax
       test      edx,edx
       jne       short M00_L00
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [ebp+0FFF0],xmm0
       xor       eax,eax
       jmp       short M00_L01
M00_L00:
       lea       eax,[edx+8]
       mov       edx,[edx+4]
       push      edx
       push      eax
       call      System.Globalization.NumberFormatInfo.get_CurrentInfo()
       mov       edx,eax
       lea       ecx,[ebp+0FFF0]
       push      ecx
       mov       ecx,6F
       call      System.Number.TryParseDecimal(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo, System.Decimal ByRef)
       test      eax,eax
       sete      al
       movzx     eax,al
M00_L01:
       mov       esp,ebp
       pop       ebp
       ret
; Total bytes of code 81
```
```assembly
; System.Globalization.NumberFormatInfo.get_CurrentInfo()
       push      ebp
       mov       ebp,esp
       push      esi
       call      System.Globalization.CultureInfo.get_CurrentCulture()
       mov       esi,eax
       cmp       byte ptr [esi+31],0
       jne       short M01_L00
       mov       eax,[esi+0C]
       test      eax,eax
       je        short M01_L00
       pop       esi
       pop       ebp
       ret
M01_L00:
       mov       ecx,offset MT_System.Globalization.NumberFormatInfo
       call      CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       mov       edx,eax
       mov       ecx,esi
       mov       eax,[esi]
       mov       eax,[eax+30]
       call      dword ptr [eax]
       mov       edx,eax
       test      edx,edx
       je        short M01_L01
       mov       ecx,offset MT_System.Globalization.NumberFormatInfo
       cmp       [edx],ecx
       je        short M01_L01
       mov       edx,eax
       call      CORINFO_HELP_CHKCASTCLASS_SPECIAL
       mov       edx,eax
M01_L01:
       mov       eax,edx
       pop       esi
       pop       ebp
       ret
; Total bytes of code 77
```
```assembly
; System.Number.TryParseDecimal(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo, System.Decimal ByRef)
       push      ebp
       mov       ebp,esp
       push      edi
       push      esi
       sub       esp,38
       vzeroupper
       vxorps    xmm4,xmm4,xmm4
       vmovdqu   xmmword ptr [ebp+0FFC0],xmm4
       xor       eax,eax
       mov       [ebp+0FFD0],eax
       mov       dword ptr [ebp+0FFF4],0E3CAA43
       mov       esi,[ebp+8]
       lea       eax,[ebp+0FFD4]
       mov       byte ptr [ebp+0FFCA],2
       lea       edi,[ebp+0FFCC]
       mov       [edi],eax
       mov       dword ptr [edi+4],1F
       lea       eax,[ebp+0FFCC]
       cmp       dword ptr [eax+4],0
       jbe       near ptr M02_L05
       mov       eax,[eax]
       mov       byte ptr [eax],0
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [esi],xmm0
       push      [ebp+10]
       push      [ebp+0C]
       push      edx
       lea       edx,[ebp+0FFC0]
       call      System.Number.TryStringToNumber(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo)
       test      eax,eax
       jne       short M02_L01
       mov       eax,1
       cmp       dword ptr [ebp+0FFF4],0E3CAA43
       je        short M02_L00
       call      CORINFO_HELP_FAIL_FAST
M02_L00:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L01:
       lea       ecx,[ebp+0FFC0]
       mov       edx,esi
       call      System.Number.TryNumberToDecimal(NumberBuffer ByRef, System.Decimal ByRef)
       test      eax,eax
       jne       short M02_L03
       mov       eax,2
       cmp       dword ptr [ebp+0FFF4],0E3CAA43
       je        short M02_L02
       call      CORINFO_HELP_FAIL_FAST
M02_L02:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L03:
       xor       eax,eax
       cmp       dword ptr [ebp+0FFF4],0E3CAA43
       je        short M02_L04
       call      CORINFO_HELP_FAIL_FAST
M02_L04:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L05:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 200
```

### Compare Jit Disasm

```assembly
; System.Tests.Perf_Decimal.TryParse(System.String)
       push      ebp
       mov       ebp,esp
       sub       esp,10
       vzeroupper
       xor       eax,eax
       mov       [ebp+0FFF0],eax
       mov       [ebp+0FFF4],eax
       mov       [ebp+0FFF8],eax
       mov       [ebp+0FFFC],eax
       test      edx,edx
       jne       short M00_L00
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [ebp+0FFF0],xmm0
       xor       eax,eax
       jmp       short M00_L01
M00_L00:
       lea       eax,[edx+8]
       mov       edx,[edx+4]
       push      edx
       push      eax
       call      System.Globalization.NumberFormatInfo.get_CurrentInfo()
       mov       edx,eax
       lea       ecx,[ebp+0FFF0]
       push      ecx
       mov       ecx,6F
       call      System.Number.TryParseDecimal(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo, System.Decimal ByRef)
       test      eax,eax
       sete      al
       movzx     eax,al
M00_L01:
       mov       esp,ebp
       pop       ebp
       ret
; Total bytes of code 81
```
```assembly
; System.Globalization.NumberFormatInfo.get_CurrentInfo()
       push      ebp
       mov       ebp,esp
       push      esi
       call      System.Globalization.CultureInfo.get_CurrentCulture()
       mov       esi,eax
       cmp       byte ptr [esi+31],0
       jne       short M01_L00
       mov       eax,[esi+0C]
       test      eax,eax
       je        short M01_L00
       pop       esi
       pop       ebp
       ret
M01_L00:
       mov       ecx,offset MT_System.Globalization.NumberFormatInfo
       call      CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       mov       edx,eax
       mov       ecx,esi
       mov       eax,[esi]
       mov       eax,[eax+30]
       call      dword ptr [eax]
       mov       edx,eax
       test      edx,edx
       je        short M01_L01
       mov       ecx,offset MT_System.Globalization.NumberFormatInfo
       cmp       [edx],ecx
       je        short M01_L01
       mov       edx,eax
       call      CORINFO_HELP_CHKCASTCLASS_SPECIAL
       mov       edx,eax
M01_L01:
       mov       eax,edx
       pop       esi
       pop       ebp
       ret
; Total bytes of code 77
```
```assembly
; System.Number.TryParseDecimal(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo, System.Decimal ByRef)
       push      ebp
       mov       ebp,esp
       push      edi
       push      esi
       sub       esp,38
       vzeroupper
       vxorps    xmm4,xmm4,xmm4
       vmovdqu   xmmword ptr [ebp+0FFC0],xmm4
       xor       eax,eax
       mov       [ebp+0FFD0],eax
       mov       dword ptr [ebp+0FFF4],0D7DEB560
       mov       esi,[ebp+8]
       lea       eax,[ebp+0FFD4]
       mov       byte ptr [ebp+0FFCA],2
       lea       edi,[ebp+0FFCC]
       mov       [edi],eax
       mov       dword ptr [edi+4],1F
       lea       eax,[ebp+0FFCC]
       cmp       dword ptr [eax+4],0
       jbe       near ptr M02_L05
       mov       eax,[eax]
       mov       byte ptr [eax],0
       vxorps    xmm0,xmm0,xmm0
       vmovdqu   xmmword ptr [esi],xmm0
       push      [ebp+10]
       push      [ebp+0C]
       push      edx
       lea       edx,[ebp+0FFC0]
       call      System.Number.TryStringToNumber(System.ReadOnlySpan`1<Char>, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo)
       test      eax,eax
       jne       short M02_L01
       mov       eax,1
       cmp       dword ptr [ebp+0FFF4],0D7DEB560
       je        short M02_L00
       call      CORINFO_HELP_FAIL_FAST
M02_L00:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L01:
       lea       ecx,[ebp+0FFC0]
       mov       edx,esi
       call      System.Number.TryNumberToDecimal(NumberBuffer ByRef, System.Decimal ByRef)
       test      eax,eax
       jne       short M02_L03
       mov       eax,2
       cmp       dword ptr [ebp+0FFF4],0D7DEB560
       je        short M02_L02
       call      CORINFO_HELP_FAIL_FAST
M02_L02:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L03:
       xor       eax,eax
       cmp       dword ptr [ebp+0FFF4],0D7DEB560
       je        short M02_L04
       call      CORINFO_HELP_FAIL_FAST
M02_L04:
       lea       esp,[ebp+0FFF8]
       pop       esi
       pop       edi
       pop       ebp
       ret       0C
M02_L05:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 200
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by AndyAyersMS** [comment]
@DrewScoggins did you pin down a likely commit?

**Comment by DrewScoggins** [comment]
Yeah, sorry. I just spaced on this one when I looked at the commits in the range. https://github.com/dotnet/runtime/pull/48608

**Comment by AndyAyersMS** [comment]
Ah, seems likely to be #48608. IIRC this is expected given the bug fix.

Going to re-label as System.Numerics.

**Comment by tannergooding** [comment]
This is "by design" and is a regression to ensure the returned result is correct.
