### ISSUE TITLE
 GC.GetTotalAllocatedBytes docs is unclear

### ISSUE THREAD

**Issue by mgnsm** [dotnet/runtime#49174]
The documentation on [GC.GetTotalAllocatedBytes(Boolean)](https://docs.microsoft.com/en-us/dotnet/api/system.gc.gettotalallocatedbytes) is a bit unclear on whether the returned value includes any *native* allocations.

[GC.GetAllocatedBytesForCurrentThread](https://docs.microsoft.com/en-us/dotnet/api/system.gc.getallocatedbytesforcurrentthread) is better documented:

>The GetAllocatedBytesForCurrentThread method returns the total number of bytes allocated on the _**managed**_ heap during the lifetime of a thread, not the total number of bytes that have survived garbage collection. _**The returned value also does not include any native allocations**_.

A clarification would suffice.

**Comment by Maoni0** [comment]
@gewarren could we please make a clarification for GC.GetTotalAllocatedBytes(Boolean) as we already do for GC.GetAllocatedBytesForCurrentThread? thanks!

**Comment by stephentoub** [comment]
> @gewarren could we please make a clarification for GC.GetTotalAllocatedBytes(Boolean) as we already do for GC.GetAllocatedBytesForCurrentThread? thanks!

@Maoni0, FYI, you can submit a PR with whatever improvements you'd like at https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/GC.xml#L1091-L1123.  Just click the little pencil on the upper right, edit, and submit a PR, all without leaving the comfort of the browser :smile:

**Comment by mangod9** [comment]
Thanks @stephentoub. I have created a PR to update it now.

**Comment by Maoni0** [comment]
it's indeed very easy 😀 I used your method to submit [another doc PR](https://github.com/dotnet/dotnet-api-docs/pull/6983), @stephentoub.

**Comment by stephentoub** [comment]
Excellent!  Thanks, @Maoni0.
