### ISSUE TITLE
[Mono] MonoAOTCompiler task does  not output shared object file extension (.dylib/.so/etc.) 

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#49179]
When AOTing use the MonoAOTCompiler task, the aot object files will have either a dll.o, dll-llvm.o, or a .s extension, depending on the OutputType parameter. However,  on desktop these are actually shared object files and should have the appropriate extension (.dylib or .so, depending on the platform), or else the runtime will not find and run the AOT'd code.

My proposal is to add another value the ObjectType enum, maybe "Shared", to control this.

**Comment by SamMonoRT** [comment]
@steveisok @directhex - Many changes related to aot object files went in over the last month. Does any of those address this issue and do we really need this for .NET6 ?

**Comment by steveisok** [comment]
We do need this for net6.  Android in particular has asked and is something @akoeplinger has been working on.

**Comment by SamMonoRT** [comment]
Assigning to @akoeplinger for easy tracking

**Comment by steveisok** [comment]
Fixed by https://github.com/dotnet/runtime/pull/55753
