### ISSUE TITLE
Precise liveness for LCL_FLD-s 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#49199]
For the following test:
```
 struct S
    {
        public int i1;
        public int i2;
        public int i3;
        public int i4;
        public int i5;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Test(S s)
    {}


    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int Main()
    {
        S s;//= new S();
        s.i1 = 1;
        s.i2 = 2;
        s.i3 = 3;
        s.i4 = 4;
        s.i5 = 5;
        Test(s);
        return 100;
    }
```
we will have `must-init` flag on 's' because our liveness (in `fgPerNodeLocalVarLiveness`) does not see
``` 
STORE fld1
STORE fld2
STORE fld3
STORE fld4
STORE fld5
```
as a full def, so JIT thinks that `s` value is used before defined:
```
BB01
use def in out
{V00}
{V00 V03}
{V00}
{}
Var=Reg beg of BB01: none
Var=Reg end of BB01: none
```
so "conservative" liveness prevents some optimizations, like mentioned zero-init elimination, dead store removals etc.
[dumpForIssue.txt](https://github.com/dotnet/runtime/files/6088603/dumpForIssue.txt)

I don't see a cheap solution, maybe mark "good" structs (no holes, overlaps, not address taken, not too many fields) with a new flag and track their liveness by fields using some "pseudo" numbers in `fgCurUseSet` instead of the parent lcl.

Marking as future unless we see benchmarks where it could improve CQ, cc @dotnet/jit-contrib 

category:cq
theme:liveness
skill-level:intermediate
cost:medium
impact:medium

**Comment by sandreenko** [comment]
@erozenfeld this is my analysis that we discussed for https://github.com/dotnet/runtime/pull/48797

**Comment by jakobbotsch** [comment]
I think physical promotion closes this gap.
