### ISSUE TITLE
[iOS] System.Net.Quic.Functional.Tests Crash

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#49191]
Really limited info at this point.  Here are the logs from a specific crash instance:

[Console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48606-merge-d9a5eaf1d048431cb7/System.Net.Quic.Functional.Tests/console.1c1fa890.log?sv=2019-07-07&se=2021-03-24T23%3A57%3A48Z&sr=c&sp=rl&sig=TohW47P%2FcBYrEO43U8hmxQfFFxK70eZvBMgXRtL5atw%3D
)

[Simulator.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48606-merge-d9a5eaf1d048431cb7/System.Net.Quic.Functional.Tests/run-ios-simulator-64.log?sv=2019-07-07&se=2021-03-24T23%3A57%3A48Z&sr=c&sp=rl&sig=TohW47P%2FcBYrEO43U8hmxQfFFxK70eZvBMgXRtL5atw%3D)

**Comment by marek-safar** [comment]
That's expected the asembly is PNSE

**Comment by rzikm** [comment]
As the attached info is no longer accessible, this issue is not actionable for us.
