### ISSUE TITLE
Clarify JsonDocument Dispose behaviour in regards to memory leaks

### ISSUE THREAD

**Issue by GeeWee** [dotnet/runtime#49207]
### Description

We recently had [a discussion](https://github.com/npgsql/efcore.pg/issues/1746#issuecomment-791398586) in the npgsql repository.  The discussion basically boils down to us not easily being able to determine:
- Will not disposing a JsonDocument properly lead to a memory leak?
- (And if yes, is is possible to copy a JsonDocument to avoid this somehow)

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument?view=net-5.0) is reasonably vague about this:
```
Failure to properly dispose this object will result in the memory not being returned to the pool, which will increase GC impact across various parts of the framework.
```
E.g. what does "increase GC impact mean" in practice?

I propose that the documentation explicitly states whether or not, that not-disposing the JsonDocument will lead to memory leaks.

**Comment by eiriktsarpalis** [comment]
If you can't call `.Dispose` on the JsonDocument, then calling `.Clone()` on the root element will return a deep clone that does not depend on pooled buffers. You'd still need to dispose the original instance:
```csharp 
using (jsonDoc)
{
   JsonElement clonedRoot = jsonDoc.RootElement.Clone();
   return clonedRoot;
}
```

**Comment by roji** [comment]
@eiriktsarpalis the question here was more about the consequences of not calling Dispose on the JsonDocument - the user is looking for confirmation whether that would purely be increased GC pressure (so purely a perf issue), or whether it would produce a leak which could eventually e.g. exhaust memory.

**Comment by eiriktsarpalis** [comment]
ArrayPool does not store references to buffers that have been rented out. As such there is no risk of memory leaks happening, in this context. I don't think we should explicitly state this in the docs /cc @steveharter.
