### ISSUE TITLE
Interpreter assertion on wasm in debug mode

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#49205]
To reproduce:
- Go to ``src/mono/sample/wasm/console``.
- Add         ``Math.Round (1.0, 5);`` to ``Main ()``.
- ``make CONFIG=Debug``
- ``make run CONFIG=Debug``

Actual result:
``
console.error: Math.Round: not enough values (0 < 1) on stack at 0032
console.error: RuntimeError: memory access out of bounds
console.error: RuntimeError: memory access out of bounds
    at interp_transform_call (<anonymous>:wasm-function[333]:0x421e8)
    at generate_code (<anonymous>:wasm-function[313]:0x354c8)
``
This is a regression which seems to be caused by 5bc40f582aeb452406f7c3aa0156df7d1c16221e.

It happens when trying to inline ``Math.CopySign`` into ``Math.Round``.

**Comment by BrzVlad** [comment]
The code of ConditionalSelectBitwise looks broken to me
```
.method public hidebysig static class System.Runtime.Intrinsics.Vector128`1<float32>
          ConditionalSelectBitwise(class System.Runtime.Intrinsics.Vector128`1<float32> selector,
                                   class System.Runtime.Intrinsics.Vector128`1<float32> ifTrue,
                                   class System.Runtime.Intrinsics.Vector128`1<float32> ifFalse) cil managed aggressiveinlining
  {
    // Code size       26 (0x1a)
    .maxstack  1
    .locals (bool V_0,
             object V_1,
             bool V_2)
    IL_0000:  nop
    IL_0001:  call       bool System.Runtime.Intrinsics.Arm.AdvSimd::get_IsSupported()
    IL_0006:  stloc.0
    IL_0007:  ldloc.0
    IL_0008:  brfalse.s  IL_000a

    IL_000a:  call       bool System.Runtime.Intrinsics.X86.Sse::get_IsSupported()
    IL_000f:  stloc.2
    IL_0010:  ldloc.2
    IL_0011:  brfalse.s  IL_0013

    IL_0013:  nop
    IL_0014:  newobj     instance void System.PlatformNotSupportedException::.ctor()
    IL_0019:  throw
  } // end of method VectorMath::ConditionalSelectBitwise
```

Somebody seems to trim code out of it. This method is not executing and we get to this broken code only because we are inlining, which didn't happen before my change.

**Comment by kg** [comment]
What's wrong with that IL? It's strange that it doesn't contain the actual 'does work' method body but it seems like valid IL that should compile

**Comment by BrzVlad** [comment]
the problem is that I'm stupid
