### ISSUE TITLE
JIT: Make JIT time constants from calls to Type methods and properties

### ISSUE THREAD

**Issue by omariom** [dotnet/runtime#4920]
If JIT could treat the calls like  `typeof(T).IsValueType`, `typeof(IInterface).IsAssingnableFrom(typeof(T))` etc. as JIT time constants that could allow us to write more performant generic code.

category:cq
theme:type-intrinsics
skill-level:intermediate
cost:large

**Comment by EgorBo** [comment]
I am closing this since `IsValueType` and `IsAssingnableFrom` are intrinsified long time ago, the rest can be enabled on demand (actually, I even had a branch where some of them were folded naturally without intrinsification - https://github.com/dotnet/runtime/pull/92562#issuecomment-1733233945)
