### ISSUE TITLE
SMTP client problem with .net 5.0

### ISSUE THREAD

**Issue by ingted** [dotnet/runtime#49200]
### Description

[https://github.com/dotnet/fsharp/issues/11186](https://github.com/dotnet/fsharp/issues/11186)
An application build with .net 4.8 works fine but throw 5.7.0 authentication required error with .net 5.0 

### Configuration

git clone https://github.com/ingted/dotnet5mail
Modify the address and gmail app password
Build it and execute with a "The server response was: 5.7.0 Authentication Required" error. (.net 5.0)
Build it and execute without any error. (.net 4.8)
Execute the code in Fsi.exe (.net 4.8), and the email would be successfully sent.
Execute the code in Fsi.exe (.net 5.0), and the email would be failed to send.

### Regression?

* Did this work in a previous build or release of .NET Core, or from .NET Framework? Yes. Successfully with .net 4.8

**Comment by ingted** [comment]
The label is wrong.
It should be about System.Net.Mail?!

**Comment by Tornhoof** [comment]
The recommended smtp client by now is mailkit, the integrated client is not enhanced anymore: https://github.com/jstedfast/MailKit
See e.g. https://github.com/dotnet/runtime/issues/46953#issuecomment-759825386

**Comment by wfurt** [comment]
I cannot make it work even with 4.8 @ingted. 
I was trying to get around 
```
Someone just used your password to try to sign in to your account from a non-Google app. Google blocked them, but you should check what happened. Review your account activity to make sure no one else has access.
```
but no luck so far. 

Looking at your code:  `smtp.UseDefaultCredentials=true` seems wrong. Is there reason why you do this and can you try it without it? 

BTW I assume you are running on Windows?

**Comment by ingted** [comment]
Yes, I am running on Windows. And 4.8 does work...

**Comment by karelz** [comment]
Triage: It is a regression, but with low impact -- this is likely specific to the server. It would be nice to understand why it is broken.

**Comment by ingted** [comment]
![image](https://user-images.githubusercontent.com/4289161/111661898-69dd4b80-884a-11eb-9637-fa05011d7ae4.png)
![image](https://user-images.githubusercontent.com/4289161/111662313-c50f3e00-884a-11eb-9c09-c7b827cf801e.png)
![image](https://user-images.githubusercontent.com/4289161/111662410-d9ebd180-884a-11eb-8293-c96001811cda.png)

**Comment by ingted** [comment]
Just like my screenshot, I only change the net5.0 to net48 in fsproj file.
Then the email could be sent successfully.
I can provide the app password if you want, please send me an email anibal.yeh@gmail.com or ingted@gmail.com
I will send you the app password.

**Comment by ingted** [comment]
PS. I use .net 5.0.4 now. (SDK 5.0.201)

**Comment by DaveSenn** [comment]
@ingted could it be a problem with UseDefaultCredentials? see: https://github.com/dotnet/runtime/issues/46430#event-4211001414

**Comment by wfurt** [comment]
Did you try to flip the `UseDefaultCredentials` @ingted. If so and if you still have issues send me the credentials to my GH email. I may be able to take closer look this week.

**Comment by ingted** [comment]
Wow!!!!! It does a magic work on .net 5.0!!! Cool...

**Comment by ingted** [comment]
(Double checked. when setting UseDefaultCredentials to false, the email is received. when true, an exception is thrown.)

**Comment by wfurt** [comment]
glad to hear as it was somewhat guess - going back to https://github.com/dotnet/corefx/pull/41271 and #46430
There is ambiguity if you provide explicit credentials as well as tell the SMTP to use the default instead.
(and the behavior changed over the time)
