### ISSUE TITLE
System.Memory is missing inbox redirect for Xamarin

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#49211]
System.Memory NuGet is missing inbox redirects for all Xamarin TFMs. This is causing problems like https://github.com/mono/mono/issues/20805 because the latest Xamarin available version is NS2.0 which is not compatible with NS2.1.

The solution is straight forward fix to add inbox redirect because Xamarin SDKs ships with inbox version of System.Memory.dll

**Comment by filipnavara** [comment]
Related: #25316 #26244

**Comment by filipnavara** [comment]
The last serviced version of the System.Memory OOB package seems to come from https://github.com/dotnet/corefx/blob/release/2.1/src/System.Memory/pkg/System.Memory.pkgproj. It would likely be necessary to update it on the ancient release/2.1 branch.

**Comment by ericstj** [comment]
@marek-safar I thought we had agreed that Xamarin needs to fix this because we rely on the behavior of framework winning over nuget packages (following conflict resolution rules) in many nuget packages: https://github.com/xamarin/xamarin-macios/issues/5687#issuecomment-573223744

**Comment by filipnavara** [comment]
I checked the facades and they seem to have [version 4.0.99.0] (https://github.com/mono/mono/blob/845fe83dd9c2b74c9feb5a2c2a40ffe28d0e6acf/mcs/class/Facades/System.Memory/AssemblyInfo.cs#L33-L35) which should be higher than what the NuGet provides. What am I missing? Would a repro/binlog help?

Our situation is that we have a library targeting netstandard2.1 that is consumed by xamarinmac2.0 application.

**Comment by ericstj** [comment]
In your build of the xamarinmac2.0 application you should have a look at this task:
https://github.com/dotnet/sdk/blob/446589256a6fc128d1adffe83551a727ebf7f234/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ConflictResolution.targets#L40

And how that's handling the facade assemblies.  cc @dsplaisted

**Comment by filipnavara** [comment]
Here's a small self-contained repro (app + netstandard2.0 library referencing the System.Memory package):
[Repro.zip](https://github.com/dotnet/runtime/files/6173487/Repro.zip)

**Comment by dsplaisted** [comment]
@filipnavara Can you share a [binlog](https://aka.ms/binlog) of building that project?

**Comment by filipnavara** [comment]
Sure, here you go:
[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/6173597/msbuild.binlog.zip)

**Comment by ericstj** [comment]
@dsplaisted and I had a look.  It seems that the Xamarin targeting packs don't include any information that indicate the framework contents to the ConflictResolution targets linked above.

On .NETCore that information is part of the PlatformManifest.xml file.  On .NETFramework that information comes from the FrameworkList.xml file.

Xamarin.Mac is providing the latter (/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/RedistList/FrameworkList.xml), but its content is empty:
```xml
<FileList Redist="Xamarin.Mac Base Class Libraries" Name="Xamarin.Mac" />
```

Can you try replacing this with a full framework list file and see if that works?  Here's a sample file that worked for me: 
https://gist.github.com/ericstj/a144e81a85d20358f1de9df91d9bfcf3

Here's some sample code for generating framework lists, if it helps: https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.SharedFramework.Sdk/src/CreateFrameworkListFile.cs

**Comment by filipnavara** [comment]
Thanks for pointing me in the right direction and what to look for.

I don't have a file named `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/RedistList/FrameworkList.xml` on my machine. There are few other ones:
```
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/msbuild/FrameworkList.xml
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current//lib/mono/4.5/RedistList/FrameworkList.xml
/Library/Frameworks/Mono.framework/External/xbuild-frameworks/Xamarin.Mac/v2.0/RedistList/FrameworkList.xml
```

Xamarin sources do have the FrameworkList.xml lists which include the System.Memory correctly so it may actually be an issue with deployment of the list to the correct location. I'll try to look into it in more detail tomorrow.

**Comment by GrabYourPitchforks** [comment]
@ericstj @dsplaisted Would it make sense to repath this to __area-setup__ or similar? I'm not sure who all needs to get their eyes on this, but I don't think the _System.Memory_ feature owners have the expertise for this.

**Comment by filipnavara** [comment]
I studied the build system a bit and it looks like this:
- `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/msbuild/FrameworkList.xml` should be the Xamarin.Mac 2.0 profile. It's generated from source [here](https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac-Mobile-FrameworkList.xml.in) and it lists `System.Memory` version 4.0.99.0 which should be higher than the System.Memory NuGet.
- `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/4.5/RedistList/FrameworkList.xml` is the full framework profile which mimics .NET Framework more closely. It doesn't have System.Memory inbox and it doesn't have the Span/Memory types in the reference assemblies either. It's generated from source [here](https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac-Full-FrameworkList.xml.in)

I cannot find in the binlog which one gets used and where the resolution takes place. The FrameworkList.xml files themselves seem to contain the correct information. There are even some unit tests specifically for System.Memory on Xamarin in different profiles but I don't think they check the assembly versions so they would not catch this issue. Looking at the history in the xamarin-macios repository there were multiple attempt to fix this in late 2019.

**Comment by filipnavara** [comment]
I looked at the implementation of ResolvePackageFileConflicts and how it looks up the FrameworkList.xml file.

Copying `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/msbuild/FrameworkList.xml` to `/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/RedistList/FrameworkList.xml` seems to fix the conflict resolution.

Now, who should I bother about the packaging of these files? I assume this comes from the Xamarin repository.

**Comment by ericstj** [comment]
Yeah, I don't know who builds these Xamarin targeting packs.  @rolfbjarne do you know?  FWIW it looks like this same problem might be present in other targeting packs, the linked issue had a report from Xamarin.IoS.

Are you sure Mono runtime doesn't also need a fix here?  Definitely conflict resolution should have won over here, but on .NETCore, even when an application  chooses to deploy a version of an assembly we have a runtime check (host actually) that determines which assembly to load.  This is necessary because some times an app might be built for an old framework where the app's copy of an assembly will win, but run on a newer framework where the framework's assembly should win.  Does that apply in this circumstance for Xamarin.Mac?

**Comment by filipnavara** [comment]
It's somewhat trivial to add the necessary symlinks here: https://github.com/xamarin/xamarin-macios/blob/c9d1760cfc6f7b14ef7bd9ebb615b2837fa5d6f0/msbuild/Makefile#L64 (and further down in the file for macOS, Mac Catalyst, etc.). Unless someone comes up with a good reason not to do it I'll submit a PR in the week.

(cc @radical. I vaguely remember you may have discussed this in one issue or another about 2-3 years ago; but it's too far back for me to track it down.)

**Comment by rolfbjarne** [comment]
> Yeah, I don't know who builds these Xamarin targeting packs. @rolfbjarne do you know?

Yes, this is done in xamarin/xamarin-macios.

> FWIW it looks like this same problem might be present in other targeting packs, the linked issue had a report from Xamarin.IoS.

@filipnavara for iOS we have `/Library/Frameworks/Mono.framework/External/xbuild-frameworks/Xamarin.iOS/v1.0/RedistList/FrameworkList.xml`, which seems to have the right System.Memory entry, but I guess the question is if that's the actual file that's getting loaded, or does it need to be somewhere else too?

> Are you sure Mono runtime doesn't also need a fix here? Definitely conflict resolution should have won over here, but on .NETCore, even when an application chooses to deploy a version of an assembly we have a runtime check (host actually) that determines which assembly to load. This is necessary because some times an app might be built for an old framework where the app's copy of an assembly will win, but run on a newer framework where the framework's assembly should win. Does that apply in this circumstance for Xamarin.Mac?

No, this does not apply, because in most cases everything is packaged into an .app, so it's not possible to "run on a newer framework". At runtime we'll use what's packaged in the app, which means this is a build-time only problem.

> Unless someone comes up with a good reason not to do it I'll submit a PR in the week.

That would be great!

**Comment by filipnavara** [comment]
> which seems to have the right System.Memory entry, but I guess the question is if that's the actual file that's getting loaded, or does it need to be somewhere else too?

It doesn't get loaded. I tried that. I believe at some point it was being loaded from that location but it certainly doesn't work anymore.

**Comment by ericstj** [comment]
> It doesn't get loaded. I tried that. I believe at some point it was being loaded from that location but it certainly doesn't work anymore.

`TargetFrameworkDirectory` is the property that controls this.  I noticed an interesting targets file in Xamarin projects which could be at play : \Library\Frameworks\Mono.framework\External\xbuild\Xamarin\Mac\Xamarin.Mac.TargetFrameworkFix.targets. 

Can we transfer this issue to another repo?   Should that be https://github.com/xamarin/xamarin-macios?

**Comment by filipnavara** [comment]
Hmm, that's an interesting find (https://github.com/xamarin/xamarin-macios/blob/main/msbuild/Xamarin.Mac.Tasks/Xamarin.Mac.TargetFrameworkFix.targets). I guess at this point the issue belongs to https://github.com/xamarin/xamarin-macios (but don't take my word for it) :D

**Comment by ericstj** [comment]
Can you or @rolfbjarne transfer? I don’t have write permission in that repository

**Comment by marek-safar** [comment]
The issue is being addressed by https://github.com/xamarin/xamarin-macios/pull/10928 on Xamarin.Mac side
