### ISSUE TITLE
wasm AOT library test failure - AOT Compilation failed for method

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#49219]
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.
More details can be found by looking for the suite names [here](https://helix.dot.net/api/jobs/763c687c-e148-4b1a-bbaf-26e248918da3/workitems?api-version=2019-06-17)

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method`

`System.Text.Json.Tests`
`Common.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Threading.CancellationTokenSource:ExecuteCallbackHandlers (bool)'.`

`System.Threading.Tasks.Parallel.Tests`
`System.IO.Pipelines.Tests`
`Microsoft.Extensions.Configuration.Functional.Tests`
`System.Threading.Tests`
`Microsoft.Extensions.Primitives.Tests`
`Microsoft.Extensions.Options.Tests`
`Microsoft.Extensions.Configuration.Tests`
`Microsoft.Extensions.Configuration.UserSecrets.Tests`
`System.Memory.Data.Tests`
`System.Threading.Channels.Tests`
`System.Net.Http.Json.Functional.Tests`
`Microsoft.Extensions.Configuration.Json.Tests`
`System.Collections.Concurrent.Tests`
`Microsoft.Extensions.Configuration.Ini.Tests`
`Microsoft.Extensions.Configuration.Xml.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'bool Microsoft.Extensions.Internal.ParameterDefaultValue:TryGetDefaultValue (System.Reflection.ParameterInfo,object&)'.`

`Microsoft.Extensions.DependencyInjection.Tests`
`Microsoft.Extensions.Logging.EventSource.Tests`
`Microsoft.Extensions.Logging.Testing.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'object Microsoft.Extensions.DependencyInjection.ActivatorUtilities/ConstructorMatcher:CreateInstance (System.IServiceProvider)'.`

`Microsoft.Extensions.DependencyInjection.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'System.Threading.Tasks.Task System.Net.Http.HttpContent:LoadIntoBufferAsync (long,System.Threading.CancellationToken)'.`

`Microsoft.Extensions.DependencyInjection.Tests`
`Microsoft.Extensions.Http.Tests`
`System.Net.Http.Unit.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Data.DataColumnCollection:BaseAdd (System.Data.DataColumn)'.`

`System.Data.DataSetExtensions.Tests`
`System.Data.Common.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Data.DataRow:set_Item (System.Data.DataColumn,object)'`

`System.Data.DataSetExtensions.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateFromFile`

`System.IO.MemoryMappedFiles.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Net.Http.HttpContent:CopyTo (System.IO.Stream,System.Net.TransportContext,System.Threading.CancellationToken)'.`

`System.Net.Http.Unit.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Net.Mime.ContentType:ParseValue ()'.`

`System.Net.Mail.Functional.Tests`

---
- [ ] `System.ExecutionEngineException : AOT Compilation failed for method 'void System.Numerics.Tests.divremTest:VerifyDivRemString (string)'.`

`System.Runtime.Numerics.Tests`

Repro:
Check out changes in 
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by lewing** [comment]
These appear to all be exception filter related and will only fail in LLVMOnly mode.

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
