### ISSUE TITLE
[mono] Intrinsics runtime tests failure: Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-llvm.c:1236

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#49217]
On llvmaot linux x64, these two tests failed to AOT:

- JIT/HardwareIntrinsics/General/Vector128/Vector128_r/Vector128_r.dll
- JIT/HardwareIntrinsics/General/Vector128/Vector128_ro/Vector128_ro.dll

```
%7 = shufflevector <8 x i8> %6, <8 x i8> undef, <8 x i32> zeroinitializer
i8

* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-llvm.c:1236
```

**Comment by imhameed** [comment]
Reenabled in https://github.com/dotnet/runtime/pull/53752.
