### ISSUE TITLE
Add AttributeTargets.Parameter to JsonIgnoreAttribute

### ISSUE THREAD

**Issue by Joshlo** [dotnet/runtime#49212]
Is it possible to add AttributeTargets.Parameter to JsonIgnoreAttribute.

So instead of 
`[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]`
it would be 
`[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]`

The reason is so that it would be possible to do the following:
`public record MyRecord ([JsonIgnore] string IgnoreThisProp);`

Rather than doing:
`public record MyRecord (string IngnoreThisProp)
{
    [JsonIgnore]
    public string IgnoreThisProp { get; set; } = IgnoreThisProp;
}`

Best regards
Kenneth

**Comment by Joe4evr** [comment]
You can use the `property` target specifier:
```cs
public record MyRecord ([property: JsonIgnore] string IgnoreThisProp);
```

**Comment by Joshlo** [comment]
Didn't know that.
Thx :)

**Comment by layomia** [comment]
The solution from @Joe4evr https://github.com/dotnet/runtime/issues/49212#issuecomment-791467177 is the workaround here:

> You can use the `property` target specifier:
> 
> ```cs
> public record MyRecord ([property: JsonIgnore] string IgnoreThisProp);
> ```
