### ISSUE TITLE
[wasm] Custom compression pass for wasm

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#49222]
This will require first rewriting the [ModuleSaw](https://github.com/kg/ModuleSaw) decoder in JS or C. By current estimates this gets us about 40k on dotnet.wasm with the interpreter-only config and even more with AOT. Writeup: https://github.com/WebAssembly/design/issues/1180

Interpreter:
```
  783,558 PM6.wasm.br
  742,510 PM6.msaw.br
```

AOT example:
```
10,142,245 calculator.wasm.br
 9,649,060 calculator.msaw.br
```

**Comment by kg** [comment]
> @kg, what's the status? Are we able to prepare it for dotnet 7?

Not implemented, and no
