### ISSUE TITLE
[wasm] Shrink data section in dotnet.wasm

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#49224]
This is surprisingly large in the uncompressed binary, especially with ICU linked in. It seems likely that getting rid of unnecessary strings, shrinking unused arrays, and deduplication efforts could potentially give us some wins post-compression, but we should try compressing a binary with the data section manually removed to see how much space it's taking up post-compression.

Invariant uncompressed:
```
13.1%   165Ki   NAN%       0    Data
```

ICU uncompressed:
```
23.0%   513Ki   NAN%       0    Data
```

**Comment by CoffeeFlux** [comment]
Related:
https://github.com/rustwasm/twiggy
https://github.com/rustwasm/wasm-snip
https://reviews.llvm.org/D46417
https://reviews.llvm.org/D42511

**Comment by ilonatommy** [comment]
Closing in favor of more general: https://github.com/dotnet/runtime/issues/60249 that aims in shrinking the whole `dotnet.wasm` size.
