### ISSUE TITLE
Crossgen2 still reports "CoreRT Ready-To-Run Compile" in the CompilerIdentifier R2R section

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#49231]
<pre>
Filename: D:\git\sdk_test\sdk\6.0.100-preview.3.21154.10\out\composite.dll
OS: Windows
Machine: Amd64
ImageBase: 0x180000000

======================== R2R Header =========================

Signature: 0x00525452 (RTR)
RelativeVirtualAddress: 0x00001048
Size: 124 bytes
MajorVersion: 0x0005
MinorVersion: 0x0002
Flags: 0x00000008
  - READYTORUN_FLAG_NonSharedPInvokeStubs

======================= R2R Sections ========================

9 sections

_______________________________________________

Type:  CompilerIdentifier (100)
RelativeVirtualAddress: 0x00383690
Size: 28 bytes
CoreRT Ready-To-Run Compile
</pre>

I guess we should change it to something like "Microsoft Crossgen2 optimizing native compiler". 

/cc @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
ah yes we should fix this. @richlander perhaps for better naming.

**Comment by jkotas** [comment]
> Microsoft Crossgen2 optimizing native compiler"

This string for old crossgen was like `CoreCLR 5.0.321.7212`. We should match this style - avoid unnecessary verbosity and include version. This string is meant to be used e.g. for identifying images compiled with a broken compiler. It is not meant to be a nice human readable verbose description

I would suggest: `crossgen2 6.0.42.42`

**Comment by ivdiazsa** [comment]
Hi @jkotas! I'm working on a fix for this issue and have a question. You mentioned we should print the actual Crossgen2 version. Where can I find it to add it to my fix? Thanks!

**Comment by MichalStrehovsky** [comment]
> Where can I find it to add it to my fix? Thanks!

`Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyFileVersionAttribute>().Version` should do the trick.
