### ISSUE TITLE
[Wasm][AOT] `Assert.True() failure`

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#49246]
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.

- [ ] `Assert.True() Failure`
`Microsoft.Extensions.Configuration.Json.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.Configuration.Json.Tests/console.de996091.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`Common.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Common.Tests/console.7a58fe46.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Xml.XmlSchemaSet.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Xml.XmlSchemaSet.Tests/console.db811c0b.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`Microsoft.Extensions.Configuration.Ini.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.Configuration.Ini.Tests/console.f5de7284.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`Microsoft.Extensions.Configuration.Xml.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.Configuration.Xml.Tests/console.fe066dce.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`Microsoft.Extensions.FileProviders.Composite.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.FileProviders.Composite.Tests/console.67b61af6.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Diagnostics.StackTrace.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Diagnostics.StackTrace.Tests/console.f7935cea.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

Repro:
Check out changes in 
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by lewing** [comment]
Microsoft.Extensions.Configuration.Json is failing because the resource isn't getting loaded from the Satellite assembly.  I haven't looked at the others yet but they are likely similar.

**Comment by radical** [comment]
> Microsoft.Extensions.Configuration.Json is failing because the resource isn't getting loaded from the Satellite assembly. I haven't looked at the others yet but they are likely similar.

Which satellite assemblies?

**Comment by radical** [comment]
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.
