### ISSUE TITLE
Ignore composite images in Crossgen2 inputs

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#49247]
When Crossgen2 is asked to compile a folder that's already been compiled with Crossgen2 in composite mode, the compilation fails because the compiler finds the composite DLL and claims it uses unsupported managed C++. Crossgen2 should be able to recognize previously produced composite files and just skip them as inputs similar to what it does for native DLLs.

/cc @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
assume there is a workaround for this, so moving to 7
