### ISSUE TITLE
SetCreationTime on Mac (continuation)

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#49258]
### Description

This is based off of my previous issue https://github.com/dotnet/runtime/issues/39132.
I found a method to make it work that doesn't use obj c apis as I was having issues with setting the attribute on symbolic links in my project using the obj c method, here's the api: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setattrlist.2.html.
I've used this code in my own project for a while now and it seems to work completely fine and I haven't had any issues with it.
I'm happy to share the code as a part of a PR.
It also doesn't require the workaround for setting the modification date to before the creation date that the old code needed from https://github.com/dotnet/runtime/issues/39132. You can also theoretically set the access time using `ATTR_CMN_ACCTIME` with this api, but I've not found any use in doing so in my code, so I didn't bother to implement it, and there was no issues with the current implementation of set last access time AFAIK on mac.
I'd be happy to attempt making a PR if @carlossanlop and/or @Jozkee are alright with it.
Also, I'm not sure if it'd work on an M1 mac as I do not have one, but I see no reason why it wouldn't.

**Comment by carlossanlop** [comment]
Hey @hamarb123 let's reopen the other issue to keep it simple and preserve all the context in one single place. I'll copy your description from this issue into a comment there.

**Comment by hamarb123** [comment]
@carlossanlop, I'm fine with that, but can you give me permissions.
Thanks.
![image](https://user-images.githubusercontent.com/25316035/110853015-31e47e80-8307-11eb-9396-d457defa3b02.png)

**Comment by carlossanlop** [comment]
@hamarb123 I removed the lock (seems to be a very new bot action). We can continue the conversation there.
