### ISSUE TITLE
WindowsDesktop and ASP.NET are not considered linkable frameworks

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#49252]
When trimming any WinForms, WPF, or ASP.NET, the whole framework is not linked because it is considered user code.

This may not be relevant if we do not support trimming these frameworks, but otherwise we should mark them as linkable as soon as we have fixed preliminary warnings.

**Comment by eerhardt** [comment]
We have a feature now that any library can add `[assembly:AssemblyMetadata("IsTrimmable", "True")]`, and when `TrimMode=link` that assembly will be trimmed.

See https://github.com/dotnet/runtime/pull/48428
https://github.com/mono/linker/blob/main/docs/design/trimmed-assemblies.md#assemblymetadataistrimmable-true.

I think this issue can be closed now in `dotnet/runtime`. It is possible for those libraries to "self-serve" here. No work is needed in dotnet/runtime.

**Comment by marek-safar** [comment]
Yep, there is not much left to do in runtime. It'd be better to open an issue in WinForms, WPF repos with links on how to make their SDK trimmable (that's what we did for other repos).

**Comment by eerhardt** [comment]
Closing as per above discussion.

**Comment by agocke** [comment]
Thanks, the guidance above looks good.
