### ISSUE TITLE
Nullable type is flagging warning when already checked with an extension method

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [dotnet/runtime#49268]
When `#nullable` is enabled, reference to a nullable type is flagging a warning even though it is surrounded by a condition which checks for null using an extension method.

If `#nullable` is disabled, or the extension method is not used, no warning is presented.

Examples:

If `#nullable` is enabled, `Console.WriteLine( valueCouldBeNull.Value );` is flagging a 'Type may be nullable' warning:

```
#nullable enable

using System;

public static class GuidExtension
{
    public static bool IsNullOrEmpty( this Guid? guid )
    {
      return !( guid.HasValue && guid.Value != Guid.Empty );
    }
}


public class C {
    public void M() {
      Guid? valueCouldBeNull = null;

      if( !valueCouldBeNull.IsNullOrEmpty() )
      {
        Console.WriteLine( valueCouldBeNull.Value );
      }
    }
}
```

If `#nullable` is disabled, `Console.WriteLine( valueCouldBeNull.Value );` is no longer flagged as warning:

```
using System;

public static class GuidExtension
{
    public static bool IsNullOrEmpty( this Guid? guid )
    {
      return !( guid.HasValue && guid.Value != Guid.Empty );
    }
}


public class C {
    public void M() {
      Guid? valueCouldBeNull = null;

      if( !valueCouldBeNull.IsNullOrEmpty() )
      {
        Console.WriteLine( valueCouldBeNull.Value );
      }
    }
}
```

If `#nullable` is enabled, and not using extension method, `Console.WriteLine( valueCouldBeNull.Value );` is no longer flagged as warning:

```
#nullable enable
using System;

public class C {
    public void M() {
      Guid? valueCouldBeNull = null;

      if( valueCouldBeNull.HasValue )
      {
        Console.WriteLine( valueCouldBeNull.Value );
      }
    }
}
```

### Configuration

.NET 5
Windows 10 Pro Version: 10.0.19041 Build 19041
Haven't tested other environments

**Comment by huoyaoyuan** [comment]
You should put `[NotNullWhen(false)]` on the parameter of the extension method parameter to indicate it will do the check, like `string.IsNullOrEmpry` does.
