### ISSUE TITLE
[Linux] System.Drawing.Common not working on Linux 

### ISSUE THREAD

**Issue by djthegr8** [dotnet/runtime#49275]
### Description
When using `System.Drawing.Common`, I am getting a DLL error with `user32.dll` as an import on Linux. 
### Configuration

* Which version of .NET is the code running on? `5.0.2`
* What OS and version, and what distro if applicable? `Ubuntu 20.04 Focal Fossa`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `No`
 

### Regression?

Not really, but it works in Windows
### Other information

![image](https://user-images.githubusercontent.com/44142719/110237019-88486a80-7f5f-11eb-8cda-4ea4cb5948e0.png)

**Comment by djthegr8** [comment]
Update: It only happens for some specific data, and works otherwise

**Comment by safern** [comment]
@djthegr8 thank you for the report. Would you mind sharing a simple repro so that I can test it out and see what is the issue?

**Comment by djthegr8** [comment]
Because it is current a part of a modestly large project, it would take some time to reproduce, will try to send it as soon as possible

**Comment by jkotas** [comment]
@safern The problem is pretty obvious by looking at the code. We have PInvokes of Windows `GetSystemMetrics` API in Unix binary. The problem is triggered when `FillPie` fails for some reason. You should be able to simulate it by changing `FillPie` to fail.

**Comment by djthegr8** [comment]
Besides, could I get a better error because I don't know why `FillPie` should fail

**Comment by djthegr8** [comment]
@safern correct me if I am wrong, but would the PR prevent this error and allow my code to run, or would it throw a different error.

**Comment by djthegr8** [comment]
@safern apologies for bothering you, but could you tell me how could I use the library with the PR? Thanks.
