### ISSUE TITLE
Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

### ISSUE THREAD

**Issue by tidusjar** [dotnet/runtime#49277]
### Describe the bug
Azure Devops Build pipelines are inconsistently failing with the following errors:
```
 Determining projects to restore...
/opt/hostedtoolcache/dotnet/sdk/5.0.200/NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [/home/vsts/work/1/s/src/Ombi/Ombi.csproj]
/opt/hostedtoolcache/dotnet/sdk/5.0.200/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/home/vsts/work/1/s/src/Ombi/Ombi.csproj]
/opt/hostedtoolcache/dotnet/sdk/5.0.200/NuGet.targets(131,5): error :   The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [/home/vsts/work/1/s/src/Ombi/Ombi.csproj]

```
After running for example: `dotnet publish /home/vsts/work/1/s/src/Ombi/Ombi.csproj -c Release -r linux-x64 -o /home/vsts/work/1/a/linux-x64 --self-contained true -p:PublishSingleFile=true`

This started happening on Thursday 03/04/2021 (MM/dd/YYYY)

### To Reproduce
I cannot reproduce locally, but you can see this in the failed tasks here: https://dev.azure.com/tidusjar/Ombi/_build/results?buildId=1147&view=results

### Further technical details
- ASP.NET Core version 5.0

**Comment by jkotas** [comment]
`dotnet.myget.org` feed was decommissioned. It was used by internal engineering system for building .NET product, or to ship previews in a few instances. 

Try to deleting this feed in your nuget.config and see whether everything you need is on nuget.org.

**Comment by tkstanczak** [comment]
Do you have any additional info? - this broke all our GitHub Actions builds and also got displayed on my local Rider build.
I cannot find the myget.org string in any configurations.

**Comment by tkstanczak** [comment]
Ignore, found it with grep but it looks like this will be a lot of lines to remove :)

**Comment by tidusjar** [comment]
I don't have a nudget.config in my solution. Everything is working fine, it's just the azure devops pipelines failing...

**Comment by jkotas** [comment]
What about this one? https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi/nuget.config

**Comment by tidusjar** [comment]
That's awkward. I thought I removed that. My bad

**Comment by Alkasai** [comment]
I just got the same issue trying to run this locally in .Net Interactive Notebook https://github.com/dotnet/interactive/blob/main/samples/ExtensionLab/ExtensionLab-SandDance.ipynb

**Comment by colombod** [comment]
To expand on @Alkasai issue the notebook is trying to restore from these two feeds

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by Alkasai** [comment]
Seems like I got it working.
My Notebook was opened in a workspace with an F# project.
After I deleted `paket-files\paket.restore.cached` it started working..
