### ISSUE TITLE
TypeInfo ImplementedInterfaces returned items doesn not match whats returned by typeof operator.

### ISSUE THREAD

**Issue by Vake93** [dotnet/runtime#49279]
### Description
In the code sample below why does the type returned by `TypeInfo ImplementedInterfaces` differ from the type returned by `typeof `operator should not they be the same? Furthermore the type returned by `TypeInfo ImplementedInterfaces` is missing information for properties like `FullName`  etc.

```C#
using System;
using System.Linq;
using System.Reflection;
using Xunit;

var a = typeof(IDocumentOpertation<>);
var x = typeof(IDocumentOpertation<>);
var y = typeof(DocumentOpertation<>);

var z = y.GetTypeInfo().ImplementedInterfaces.First();

Assert.Equal(a, x);
Assert.Equal(a, z);

public interface IDocument
{
    Guid Id { get; set; }

    bool Deleted { get; set; }

    DateTime Created { get; set; }

    DateTime Modified { get; set; }
}

public interface IDocumentOpertation<T> where T : IDocument
{
    T Find(Guid id);
}

public class DocumentOpertation<T> : IDocumentOpertation<T> where T : IDocument
{
    public T Find(Guid id)
    {
        throw new NotImplementedException();
    }
}
```

The problem I initial faced was in my ASP.NET 5 application I was Initializing the DI container based on the class attribute on the implementation class. For most cases if worked fine but when I added a generic class it failed with the following error: 

```
OneTimeSetUp: System.ArgumentException : Cannot instantiate implementation type 'TestServiceLibrary.GenericService.DocumentOpertation`1[T]' for service type 'TestServiceLibrary.GenericService.IDocumentOpertation`1[T]'.
```

I found the root cause to the above-mentioned issue.

### Configuration
.NET Version: 5.0.100
OS: Windows 10 x64

**Comment by jkotas** [comment]
Reflection APIs like `TypeInfo.ImplementedInterfaces` return instantiated generic types that have the generic type variables substituted by actual type. `typeof(IDocumentOpertation<>` in your example is uninstantiated generic type, also called generic type definition. Try calling `Type.GetGenericTypeDefinition` method to strip the instantiation before comparing the types. 

Also, note that one type can implement multiple generic interfaces instantiated over different arguments, e.g.

```csharp
using System;
using System.Collections.Generic;

foreach (var iface in typeof(G<>).GetInterfaces())
{
   Console.WriteLine(iface);
   Console.WriteLine(iface == typeof(I<>));
   Console.WriteLine(iface.GetGenericTypeDefinition() == typeof(I<>));
}

interface I<T>
{
}

class G<T> : I<T>, I<List<T>>
{
}
```

**Comment by Vake93** [comment]
Thanks alot for the explanation, `Type.GetGenericTypeDefinition` does the trick.
