### ISSUE TITLE
VS crashes after adding " character into razor pages

### ISSUE THREAD

**Issue by lleuppi** [dotnet/runtime#49298]
I am not quite sure where to put this, as it seems like an error with VS, razor and asp net core. Excuse me if i this is not the right place to ask such a question.

I wanted to add a " character into some razor method (Html.BeginForm()) and suddenly VS froze and crashed. To make sure it was because of this, i redid the process of adding an " 5 times in a row. It always crashed, and not even once saved the added ". I did a repair, reinstall and restart, after this i cannot open the solution anymore, since it always crashes ca. 5 seconds after opening.

Here are the logs of the Window Event Viewer:

Fault bucket 1709951279600082591, type 5
Event Name: CLR20r3
Response: Not available*
Cab Id: 0

Problem signature:
P1: devenv.exe
P2: 16.9.31025.194
P3: 60383af8
P4: Microsoft.AspNetCore.Razor.Language
P5: 6.0.21.7704
P6: a651d5ee
P7: d90
P8: 45
P9: System.ArgumentException
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBE0.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_devenv.exe_6afdd52e85282de37c195cf46f7b2a8fbf1b9d_bf800e8f_3c7bb783-8523-4956-9468-d87debe6a9f4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 
Report Status: 268439648
Hashed bucket: 
Cab Guid: 0

*This sentence was originaly written in german, as "Nicht verfügbar", but i translated it.

Information:
Visual Studio Community 2019, Version 16.9.0

The other two log files are attached as .txt.
[Application Error Event viewer.txt](https://github.com/dotnet/runtime/files/6101669/Application.Error.Event.viewer.txt)
[.NET Runtime Error Event viewer.txt](https://github.com/dotnet/runtime/files/6101676/default.NET.Runtime.Error.Event.viewer.txt)

Update: Added second file

**Comment by lleuppi** [comment]
So i did some google searches and stumbled upon the following: https://social.msdn.microsoft.com/Forums/vstudio/en-US/74bb54e1-a90a-4071-a75d-a50f3f936d4b/visual-studio-list-of-open-windows-is-stored-where?forum=visualstudiogeneral

It brought me to the idea to just remove the Index.cshtml  (the razor page that kept crashing everyting) references in the .suo file and then opening the solution again. This worked BUT only for a single file. After i opened the next razor file VS crashed again. I am beginning to suspect that actually the files themselves cause the crash.

**Comment by danmoseley** [comment]
@lleuppi thanks for the report. For Visual Studio crashes please report them with the Feedback tool build into VS. That will get them to the right VS team but also help gather diagnostics.
