### ISSUE TITLE
WindowsIdentity doesn't leverage SeTcbPrivilege privilege for impersonation

### ISSUE THREAD

**Issue by victorm1710** [dotnet/runtime#49292]
In .NET Framework 4.7 it is possible to impersonate a user without knowing his password with the following code:
```c#
using (var identity = new WindowsIdentity("test@testdomain.com"))  
{
    WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
    {
        SetupSQLConnection();
    });
}
```
This works if the identity which runs the .NET process has the SeTcbPrivilege privilege.

However in .NET Core the same code snippet doesn't work, because the constructor of WindowsIdentity doesn't temporary enable the SeTcbPrivilege privilege to leverage it for impersonation (which is different from the .NET Framework's implementation).
Also from the following .NET Core source code snippet, it seems like for .NET Core it's by design to not rely on SeTcbPrivilege (probably due to security concerns):
![image](https://user-images.githubusercontent.com/44471919/110303620-a370b400-800b-11eb-948c-6d2fecb104b1.png)

I'm currently working on moving an enterprise application from ASP.NET MVC 3 to ASP.NET Core. The application is running under a user which has been granted with the SeTcbPrivilege privilege. It uses the code equal to the code snippet above for setting up a connection with SQL Server using Windows authentication (by impersonating the user "test@testdomain.com", while the .NET process itself is running under a different Windows account).
Since in .NET Core's implementation the WindowsIdentity doesn't rely on SeTcbPrivilege for impersonation, the same impersonation code (equal to the code snippet above) doesn't work on .NET Core, resulting into the following error while trying to setup an SQL connection:
![image](https://user-images.githubusercontent.com/44471919/110318142-2ef34080-801e-11eb-8a83-c3d4ccec1edd.png)

I was able to fix the impersonation in .NET Core by using the following ugly hack (the idea was taken from the .NET Framework's implementation):
```c#
Type privilegeType = Type.GetType("System.Security.AccessControl.Privilege,System.Security.AccessControl");
object privilege = Activator.CreateInstance(privilegeType, "SeTcbPrivilege");

try
{
    privilegeType.GetMethod("Enable").Invoke(privilege, null);				
					
    using (var identity = new WindowsIdentity(args[0]))
    {
        WindowsIdentity.RunImpersonated(identity.AccessToken, () =>
        {
            SetupSQLConnection();
        });
    }
}
finally
{
    privilegeType.GetMethod("Revert").Invoke(privilege, null);
}
```

However this fix doesn't look like a correct long-term solution, so I have the following questions:
- Is it by design for .NET Core to not support impersonating a user by leveraging the tcb privilege?
- Is there a proper way to impersonate an Active Directory user in .NET Core without knowing his password and without having to run the .NET process under the "System" account?

**Comment by SteveSyfuhs** [comment]
> Is there a proper way to impersonate an Active Directory user in .NET Core without knowing his password and without having to run the .NET process under the "System" account?

This is fundamentally at odds with how Windows security works. If you want to impersonate without credentials you need to enable _constrained delegation for any protocol_. If you need constrained delegation you need TCB. If you need TCB you need to be running as SYSTEM or as a Windows service.

As such, the change made during the conversion to core was the right thing to do.

The correct way to solve this problem is to either run the process as a service, or since that's likely problematic, run a separate process as a service, that does the actual impersonation and then grants your process the right to use the impersonated access token.
