### ISSUE TITLE
RyuJIT's loop cloning optimization has questionable CQ

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/runtime#4929]
See CQ comments at the top of dotnet/runtime#4922.

category:cq
theme:loop-opt
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
@BruceForstall should this be moved to future? Or are the issues above mostly handled now?

**Comment by BruceForstall** [comment]
They're mostly handled, so I'll go ahead and close this.
