### ISSUE TITLE
Update documentation for multi-level shared framework lookup

### ISSUE THREAD

**Issue by maxwellb** [dotnet/runtime#493]
The design document titled [Multi-level SharedFX Lookup](../blob/HEAD/docs/design/features/multilevel-sharedfx-lookup.md) describes the runtime behavior for various versions of .NET Core and currently describes "Proposed changes for 3.0 (specifying multiple frameworks)".

With both 3.0 and now 3.1 LTS having been released, what is the currently adopted behavior?

**Comment by davidsh** [comment]
@ericstj

**Comment by ericstj** [comment]
@vitek-karas @steveharter I don't think think we take advantage of this in the tooling, but it does look like we support it in the host, per https://github.com/dotnet/core-setup/pull/4538.  Can one of you update the doc?
