### ISSUE TITLE
[Question] Need best practices in communicating user secrets within a development team

### ISSUE THREAD

**Issue by changhuixu** [dotnet/runtime#49306]
Using user secrets is a great way to protect settings during development. It works well for individuals, but not so well for a team.

Let's examine the following scenarios:

- Developer A adds a new secret to the project. When Developer B pulls the code, the system breaks without a friendly error message of missing a secret entry.
    In this case, what do you do to make sure a new entry in the user secrets are obvious to other developers in your team?
- The project is finalized and released. After several months or a year, a new developer joins the team and starts to work on a new feature. And soon, the new developer figures out the solution won't start, until realizing the need of user secrets.
    In this case, how do you help with onboarding new developers?
- You company upgrades your workstation. You are happy because you have a new machine with much better performance. However, all your user secrets are gone. For many projects, you have to remember what were in the user secrets and find all passwords to recreate them.
    In this case, how do you sync user secrets between machines?

We have struggles in our team in the scenarios above.
I hope you, my fellow developers, could share your experiences in syncing user secrets among dev machines and among developers.

Thank you.

**Comment by joperezr** [comment]
Thanks for logging the issue @changhuixu. To be honest I'm not so sure if the issue belongs here as there is nothing really that we can do in the framework to facilitate the scenarios you outlined above. My personal suggestion of what we have used in the past is [Azure Key Vault](https://azure.microsoft.com/en-us/services/key-vault/) which support most of the scenarios that you pointed out above and is compatible with C#. I would suggest for you to try that out, and if you see frictions or find issues or missing frictions, to log an issue on [their github repo](https://github.com/Azure/azure-sdk-for-net) to log issues for the missing features.

**Comment by joperezr** [comment]
Given there are not many action items from our side for this, I'll go ahead and close this issue for now but feel free to reopen if you have any follow up questions.
