### ISSUE TITLE
Where did the PR for ReadDouble and ReadSingle in BinaryPrimitives go?

### ISSUE THREAD

**Issue by RononDex** [dotnet/runtime#49325]
I was searching for an extension method to read Singles and Doubles using BinaryPrimitives and found this issue:
https://github.com/dotnet/runtime/issues/2365 which is solved in this PR which adds the functionality: https://github.com/dotnet/runtime/pull/6864

However the code somehow never made it into the main branch. Even though the PR was merged into the master branch on 04th February 2020.

I ended up copying the code from the PR in my project now.

**Comment by jkotas** [comment]
The code is in the main branch, e.g. here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Memory/ref/System.Memory.cs#L321

Note that you have to target NET 5+ to see these APIs. They are not available for older runtimes.

**Comment by RononDex** [comment]
I am using .net5.0 with a netstandard2.1 project.

However, the BinaryPrimitives class does not hold said methods.

**Comment by tannergooding** [comment]
`netstandard2.1` is not `net5.0`, they are different targets with different exposed API surface.
You will be able to access these methods from a project targeting `net5.0` or higher, not from `netstandard2.1` or any other target.

**Comment by RononDex** [comment]
Ah yes, my stupid brain thought netstandard is 5.0, confusing version numbering :)

just switched the library to net5.0 and now it works, thanks
