### ISSUE TITLE
On Redhat, dotnet location is not added to system path after installing .Net 6.0

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#49353]
Repro steps:
1. On redhat 7.9 or 8, install .NET 6 SDK(6.0.100-alpha.1.21058.2) from https://github.com/dotnet/installer
2. Run "dotnet --info" and observe

Expected Result
dotnet command works normally

Actual Result:
dotnet command not find due to dotnet location is not added to system path.
![image](https://user-images.githubusercontent.com/1578239/104001356-7c982c00-51da-11eb-9fac-38b89110068d.png)

**Comment by NikolaMilosavljevic** [comment]
[Triage] please investigate

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/runtime/pull/53705
