### ISSUE TITLE
New connections to EventPipe are impossible if at least one was stopped

### ISSUE THREAD

**Issue by valco1994** [dotnet/runtime#49363]
Currently,`IpcStream::DiagnosticsIpc::Close` is implemented in the following way:
```cpp
void IpcStream::DiagnosticsIpc::Close(bool isShutdown, ErrorCallback callback)
{
    if (_isClosed)
        return;
    _isClosed = true;

    if (_serverSocket != -1)
    {
        // only close the socket if not shutting down, let the OS handle it in that case
        if (!isShutdown && ::close(_serverSocket) == -1)
        {
            if (callback != nullptr)
                callback(strerror(errno), errno);
            _ASSERTE(!"Failed to close unix domain socket.");
        }

        // N.B. - it is safe to unlink the unix domain socket file while the server
        // is still alive:
        // "The usual UNIX close-behind semantics apply; the socket can be unlinked 
        // at any time and will be finally removed from the file system when the last 
        // reference to it is closed." - unix(7) man page
        Unlink(callback);
    }
}
```

Actually, the cited comment from [man page](https://man7.org/linux/man-pages/man7/unix.7.html) is very misleading - socket **file** will be removed from the filesystem immediately, but those who are already using it won't be affected. [Unlink documentation](https://linux.die.net/man/2/unlink) says following:
> unlink() deletes a name from the file system. [...] If the name referred to a socket, fifo or device the name for it is removed but processes that have the object open may continue to use it.

Because of this, when some EventPipe session is finished, the UNIX domain socket for this session is removed from the filesystem, so new connections can't be created.

Such behavior is very unexpected and inconvenient. It prohibits a lot of scenarios of using EvenPipe. I suppose that this was done by mistake because of misleading text about socket file unlinking in the documentation for UNIX domain sockets.

So, I propose to not unlink the socket file in `IpcStream::DiagnosticsIpc::Close`, but do it only once per process, when an application is being terminated or .NET runtime is being unloaded.

**Comment by josalem** [comment]
My recollection is that the server port _only_ gets closed (the code you have linked in your comment) on processes shutdown or in the event of catastrophic failure inside the diagnostic server. The Listen port is a generator for IpsStreams for each IPC command. Those streams will get closed on session/interaction end, but that doesn't unlink the server socket.

Are you observing this behavior anywhere? I'm not able to reproduce your described experience. I just created a session, ended it, started another, ended it, and the socket is still visible in the `$TMPDIR` directory.

**Comment by valco1994** [comment]
Hmm, strange enough...
Yes, I observed such behavior. I will recheck it tomorrow and write the results here.

**Comment by valco1994** [comment]
I have rechecked it and it's occurred to be my fault
Sorry for bothering
