### ISSUE TITLE
[3.1] Cancellation of Socket.ConnectAsync intermitently hangs

### ISSUE THREAD

**Issue by saurabhvats007** [dotnet/runtime#49360]
hello team,

please could you backport  PR #42919 (issue #42198) to dotnet/runtime 3.1, I am encountering this intermittent hang issue if cancellation occur at ConnectHelper.ConnectAsync in my api. This would fix my issue.

Thanks for your help
Saurabh

tag : area-System.Net.Sockets

**Comment by karelz** [comment]
@saurabhvats007 can you please post a call stack, so that we can verify it is indeed the same problem?
Can you tell us more about your application? How often do you hit it?

Would 5.0 backport be sufficient for you? Or are you restricted to 3.1? If yes, why?

**Comment by karelz** [comment]
Triage: No data, closing. Feel free to reopen once more data (as requested above) is available.
