### ISSUE TITLE
dotnet-sdk deps installing from Fedora 33 Updates repo instead of Microsoft repo

### ISSUE THREAD

**Issue by Water261** [dotnet/runtime#49379]
### Description

When installing dotnet-sdk-5.0, only the sdk itself is being installed from the Microsoft repo, everything else from Fedora 33 update repo. I've tried changing priorities of the repos but it still is falling back on Updates repo.

### Configuration

OS: Fedora 33, x86_64
Unsure to whether it is specific to my config

### Regression?

Just a fresh install doesn't work

### Other information

Only workaround I know of is to manually download of the rpm packages from the repo.

**Comment by NikolaMilosavljevic** [comment]
[Triage] This is a known issue being tracked with https://github.com/dotnet/runtime/issues/47500
