### ISSUE TITLE
(Poor) Unmanaged function pointer performance

### ISSUE THREAD

**Issue by mgnsm** [dotnet/runtime#49370]
The performance of using an unmanaged function pointer in C# 9.0 to call a native function seems to be surprisingly bad compared to using the new  `SuppressGCTransitionAttribute` that was introduced in .NET 5.0.

Consider the following sample benchmark where `some_method` is a just simple C++ method in `lib.dll` that basically returns an `int` and does nothing else:

    [MemoryDiagnoser]
    public unsafe class Sample
    {
        private const string DllName = "lib.dll";

        private static readonly delegate* unmanaged[Cdecl]<IntPtr, int> s_ptr;

        [DllImport(DllName, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl),
            SuppressGCTransition]
        private static extern int some_method(IntPtr p);

        static Sample()
        {
            IntPtr lib = NativeLibrary.Load(DllName);
            s_ptr = (delegate* unmanaged[Cdecl]<IntPtr, int>)NativeLibrary.GetExport(lib, nameof(some_method));
        }

        [Benchmark]
        public int UseFunctionPointer() => s_ptr(IntPtr.Zero);

        [Benchmark]
        public int UseDllImportAttribute() => some_method(IntPtr.Zero);
    }

This is the results I get on a 2.50GHz, 1 CPU, 4 logical and 2 physical cores Intel Core i7 machine running Windows 10 2004 with the .NET 5.0.200 SDK installed:

|                Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------- |---------:|----------:|----------:|------:|------:|------:|----------:|
|    UseFunctionPointer | 7.220 ns | 0.1842 ns | 0.1891 ns |     - |     - |     - |         - |
| UseDllImportAttribute | 2.591 ns | 0.0501 ns | 0.0418 ns |     - |     - |     - |         - |

Is the function pointer expected to be this slow or am I doing something wrong?

I understand from [this](https://github.com/dotnet/runtime/issues/38134) issue that you will be able to use a new calling convention type to get the best of both worlds, i.e. the flexibility of using a function pointer and the performance of suppressing GC transitions to get minimal runtime impact, in *.NET 6* but what's the fastest way to call native functions in .NET 5?

Is there any way to use a function pointer with the `SuppressGCTransitionAttribute` or do whatever the runtime does when a method is decorated with this attribute? Or is using function pointers pretty much useless from a performance perspective in .NET 5?

**Comment by SingleAccretion** [comment]
> Is the function pointer expected to be this slow or am I doing something wrong?

Yes, this is the expected and unavoidable overhead of the P/Invoke transition. Please note that using `SuppressGCTransition` trades reliability for performance, it not a simple "make it faster" switch.

> Is there any way to use a function pointer with the SuppressGCTransitionAttribute or do whatever the runtime does when a method is decorated with this attribute?

In .NET 5 - no, outside of unsafe (and unreliable) reliance on the native and managed calling conventions matching.

**Comment by jkotas** [comment]
This was fixed for .NET 6 by https://github.com/dotnet/runtime/issues/38134 that added  SuppressGCTransition annotations for function pointers. https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/DateTime.Windows.cs#L138 is an example how it is used.

As @SingleAccretion said, SuppressGCTransition is not a simple "make it faster" switch and it is really important to only use in the situations where it is safe.
