### ISSUE TITLE
libsystem.security.cryptography.native.openssl

### ISSUE THREAD

**Issue by touzas** [dotnet/runtime#49371]
This error ocurrs in a Android Application.

When i try to create a AesCryptoServiceProvider with the CreateDecryptor(key, iv) method i receibe this exception:
System.DllNotFoundException: 'libSystem.Security.Cryptography.Native.OpenSsl'

I try using the PCL package and receive same error.

It's necesary compile OpenSSL to android?

Thanks

**Comment by antonfirsov** [comment]
@touzas I think `AesCryptoServiceProvider` is not not supported on Xamarin.Android.

/cc @akoeplinger

**Comment by touzas** [comment]
@antonfirsov the nuget package https://www.nuget.org/packages/PCLCrypto/ is for android. 
i try this with dotnet 6

**Comment by steveisok** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/51274
