### ISSUE TITLE
After updating to 5.0.200-1 using package manager, it appears that no sdks are installed.

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [dotnet/runtime#49375]
OS: Fedora 33.

Last night I `dnf distro-sync`d my system as usual, and there was this .net sdk update to 5.0.200-1.

After that, `dotnet --list-sdks ` shows no results and my .net programs fail to compile.

More info: I've been using .net on this system before .net 5 and have installed all updates to .net without any similar problems.

Also, doing `sudo dnf install dotnet-sdk-5.0` does nothing, complaining: `Package dotnet-sdk-5.0-5.0.200-1.x86_64 is already installed.`

**Comment by dleeapho** [comment]
Moved to dotnet/runtime to investigate package issue.

**Comment by AlirezaHaghshenas** [comment]
@dleeapho Please note that this update does not remove the runtime (I think I've checked this). It removes the sdk.

**Comment by AlirezaHaghshenas** [comment]
Today I got new updates: `5.0.201` and with installing them, my problem is solved.

**Comment by NikolaMilosavljevic** [comment]
Main issue tracked in https://github.com/dotnet/runtime/issues/47500
