### ISSUE TITLE
Move dotnet-sdk snaps into the installer repo and dotnet-runtime snaps into servicing branches

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#49374]
Wondering why the [dotnet-sdk snaps](https://github.com/dotnet/runtime/tree/main/src/installer/snaps) live in dotnet/runtime and not in dotnet/sdk or dotnet/installer? Aside from that, I also see a lot of dotnet-runtime snaps that target servicing releases in the main branch. What's the reason for that?

cc @NikolaMilosavljevic @leecow @jkotas

**Comment by NikolaMilosavljevic** [comment]
> Wondering why the [dotnet-sdk snaps](https://github.com/dotnet/runtime/tree/main/src/installer/snaps) live in dotnet/runtime and not in dotnet/sdk or dotnet/installer? Aside from that, I also see a lot of dotnet-runtime snaps that target servicing releases in the main branch. What's the reason for that?
> 
> cc @NikolaMilosavljevic @leecow @jkotas

cc @rbhanda @leecow

**Comment by leecow** [comment]
I don't have any concerns reparenting these to more appropriate repos.

**Comment by ViktorHofer** [comment]
Who would be the best person to talk to about the dotnet-sdk snaps? I would like to understand where they belong (dotnet/installer vs dotnet/sdk) and how tools consume them to make sure that we don't break anything by moving them.

**Comment by ViktorHofer** [comment]
Submitted required PRs to move the snaps into their respective locations:
- [ ] Move dotnet-sdk snaps into dotnet/installer: https://github.com/dotnet/installer/pull/9975
- [ ] Remove dotnet-sdk and dotnet-runtime-1.x snaps from release/2.1: https://github.com/dotnet/core-setup/pull/9134
- [ ] Remove dotnet-sdk and dotnet-runtime-1.x/2.x snaps from release/3.1: https://github.com/dotnet/core-setup/pull/9133
- [ ] Remove dotnet-sdk and dotnet-runtime-2.x/3.x snaps from release/5.0: https://github.com/dotnet/runtime/pull/49698
- [ ] Remove dotnet-sdk and dotnet-runtime-2.x/3.x/5.x snaps from main: https://github.com/dotnet/runtime/pull/49697

**Comment by ViktorHofer** [comment]
Closing as done.
