### ISSUE TITLE
dotnet-ef doesn't work with dotnet-sdk snap

### ISSUE THREAD

**Issue by cubikca** [dotnet/runtime#49380]
1. Install dotnet-ef: `dotnet tool install -g dotnet-ef`
2. Run dotnet-ef `dotnet-ef`

Error is thrown complaining about missing ICU library. libicu66 is installed on Ubuntu 20.04.

Fix:
1. Remove snap `snap remove dotnet-sdk`
2. Install from Microsoft repo `apt install dotnet-sdk-5.0`
3. Reinstall dotnet-ef `dotnet tool uninstall -g dotnet-ef && dotnet tool install -g dotnet-ef`

Now works as expected.

**Comment by dleeapho** [comment]
Moved to dotnet/runtime to investigate as a snap issue.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
