### ISSUE TITLE
[wasm] GlobalizationMode.Invariant should not eat LoadICU errors on Browser

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49391]
See the discussion in

https://github.com/dotnet/runtime/issues/49073#issuecomment-793547670
https://github.com/dotnet/runtime/issues/49073#issuecomment-793916722
https://github.com/dotnet/runtime/issues/49073#issuecomment-794271924

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Unix.cs#L25-L37

On Browser, if `LoadICU()` fails, we should call `Environment.FailFast` just like any other platform. We shouldn't fallback to Invariant mode.

cc @lewing @EgorBo @tarekgh @safern

**Comment by marek-safar** [comment]
The message should be universal and make sense for all ICU combinations we support (this could mean to display a link only)
