### ISSUE TITLE
Missing v2.1.26-dependencies tag

### ISSUE THREAD

**Issue by normj** [dotnet/runtime#49419]
Trying to build the latest **2.1.26** patch and the coreclr and corefx are missing the `v2.1.26-dependencies` tag. Can we get this tag so we can the patch out quickly?

Sorry to be a nag but last month we lost a lot of time with the dependency tag being put on the wrong commit, https://github.com/dotnet/runtime/issues/49035, and this tag is frequently forgotten. Can we please get this tag automated?

**Comment by ViktorHofer** [comment]
@aik-jahoda @Anipik can you please take care of adding the missing branch?

**Comment by Anipik** [comment]
we have the dependencies prs up https://github.com/dotnet/corefx/pull/43049 so we are good to go to complete the dependency tags by EOD

**Comment by aik-jahoda** [comment]
The tags were created yesterday. Please reopen in case of any issues.
