### ISSUE TITLE
Change default Etw mode to EtwSelfDescribingEventFormat from EtwManifestEventFormat 

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#49410]
### Description

There is a startup cost from generating manifest data for Etw https://github.com/dotnet/runtime/pull/49362

![image](https://user-images.githubusercontent.com/1142958/110568563-1a609680-814b-11eb-9fe9-85cdf906c5ee.png)

However is trying to optimizing it a wasted effort when it is an older format?

e.g. Switching to EtwSelfDescribingEventFormat https://github.com/dotnet/runtime/pull/49409 by default removes these allocations entirely and it probably the format where the effort to optimize should be focused?

From https://github.com/dotnet/runtime/issues/27621#issuecomment-431236134

> ManifestBuilder functionality is largely a **back-compat artifact for correct interoperation with legacy win7 and win8 era ETW readers.** For any new usage he recommends customers create EventSource with the Self describing events. 

and https://github.com/dotnet/runtime/issues/27621#issuecomment-431393221

> If you wish to use complex types (that is something besides primitives, strings and DateTime), then you need to use the EtwSelfDescribingFormat flag when creating the EventSouce. This is very easy. In your TestEventSource class simpy add
>
> `private TestEventSource() : base(EventSourceSettings.EtwSelfDescribingEventFormat) { }`
>
> Things should work from there. We recommend people do this in general. **We would have made this the default, except is is a breaking change for people using EventSource in manifest based scenarios.**

The docs do also suggest Self Describing is preferred? https://docs.microsoft.com/en-us/windows/win32/tracelogging/trace-logging-about

> TraceLogging is the new Windows 10 event tracing for user-mode applications and kernel-mode drivers. TraceLogging is a format for self-describing Event Tracing for Windows (ETW). TraceLogging builds on Event Tracing for Windows (ETW) and provides a simplified way to instrument code.
>
> TraceLogging offers the simplicity of Windows software trace preprocessor (WPP) with the added benefit of being able to include structured data with events, the capability of correlating events, and all without requiring a separate instrumentation manifest XML file. Events are self-describing which means that a binary containing the instrumentation manifest does not need to be registered on the system in order to use the Trace Data Helper (TDH) APIs to decode and show events.
> ...
> TraceLogging builds upon ETW but introduces several important improvements:
>
> * Tracing an event is as simple as an API call.
> * Events are self-describing and do not require any additional binaries containing the compiled event manifest to interpret the event. All the metadata about the event is recorded in the event.
> * Activities inside a single process can be easily expressed through start and stop events.
> * TraceLogging is compatible with existing instrumentation support. The new ETW APIs continue to support the old providers. You can invest in the new ETW APIs for strategic scenarios while leaving your old instrumentation points as they are.
> * TraceLogging offers the same event tracing API for Windows 10, Xbox One, and Windows 10 Mobile.
> * TraceLogging APIs are accessible from C, C++, .NET, and Windows Runtime.

**Comment by KalleOlaviNiemitalo** [comment]
"breaking change for people using EventSource in manifest based scenarios" would mean software that writes events to Windows Event Log, as in <https://github.com/dotnet/runtime/issues/27002>.

**Comment by benaadams** [comment]
> would mean software that writes events to Windows Event Log

For Windows 7 and Server 2008 R2 or earlier; however for them mainstream support ended on January 13, 2015 and Extended support ended January 14, 2020. Does .NET 6.0; not released for another 8 months, need to maintain compat with them?

**Comment by KalleOlaviNiemitalo** [comment]
Doesn't Windows Event Log in Windows 10 still require the manifest-based format? IIRC, the self-describing format always uses channel 11 (so cannot distinguish between Admin and Operational channels) and assigns event IDs at run time (so you cannot define reliable triggers for the events).

**Comment by noahfalk** [comment]
@benaadams - I see this has gone quiet for a few months, were you still pursuing this? I got the impression you and @josalem were trying to pursue source generators instead so maybe this was moot?

**Comment by benaadams** [comment]
> @benaadams - I see this has gone quiet for a few months, were you still pursuing this? I got the impression you and @josalem were trying to pursue source generators instead so maybe this was moot?

Think it could possibility be breaking and source generators would reduce the cost; as would VS not listening to verbose events machine wide, which I think was a different issue
