### ISSUE TITLE
[RyuJIT] inline CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#49429]
Currently, for e.g. `typeof(int)` we emit something like this:
```asm
       mov      rcx, 0x7FF96C7D9BA0
       call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
```
Can we just emit a raw pointer to `m_hLoaderAllocatorObjectHandle` with a jit-time known offset based on the typehandle and get rid of that call? (for non-collectible/non-shared types).

In my current jit-diff dump (PMI) I see 5898 `call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPEHANDLE`

/cc @jkotas

**Comment by MichalStrehovsky** [comment]
If the RuntimeType hasn't been allocated yet, the JIT would still have to call the helper so that it gets created. Are you hoping to save size or improve speed?

**Comment by EgorBo** [comment]
> Are you hoping to save size or improve speed?

both! 🙂 

> We may want to look into changing string literals and RuntimeTypes to be allocated on Pinned Object heap (for non-collectible types at least) and emitting their addresses directly, without any indirections. The Pinned Object Heap is sort of similar to frozen objects in this regard.

Ah nice! Will try to prototype it this weekend to estimate impact.
