### ISSUE TITLE
QUIC: Validate SslServerAuthenticationOptions set on QuicListenerOptions

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#49423]
QuicListenerOptions has SslServerAuthenticationOptions property.

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListenerOptions.cs#L16

It looks like code that uses this property assumes that SslServerAuthenticationOptions.ServerCertificate is set.
* Need to validate that it is set.
* Need to consider what happens when other options are set like a certificate selector callback.

**Comment by ManickaP** [comment]
Triage: we should consider making it non-nullable if it needs to be set. Also decide what to do about the other properties, which is probably covered in https://github.com/dotnet/runtime/issues/32071.

**Comment by ManickaP** [comment]
Triage: this is nice to have, moving to 7.0

**Comment by JamesNK** [comment]
@Tratcher

**Comment by wfurt** [comment]
Note that MsQuicListener needs ALPN to event start. That may be fixed in future but that is current constraint.

**Comment by ManickaP** [comment]
We need the SslOptions, they shouldn't be nullable (API shape to discuss): https://github.com/dotnet/runtime/issues/49587#issuecomment-1032260212
We do validate/handle most of the options on the class, the missing are listed here: https://github.com/dotnet/runtime/issues/32071#issuecomment-1032264885

**Comment by karelz** [comment]
Triage: Current behavior is enforced to allow multiple protocols to be on same UDP port (HTTP and SMB on UDP 443). cc @nibanks
@JamesNK @Tratcher are you able to provide the ALPN upfront?

**Comment by JamesNK** [comment]
I believe Kestrel will always use `SslApplicationProtocol.Http3` as the ALPN.

**Comment by Tratcher** [comment]
I don't expect custom ALPN per SNI to be an issue until we get to HTTP/4 (maybe next year 😆).

**Comment by wfurt** [comment]
We have little bit more chat about this with @nibanks. The reason why msquic want ALPN upfront is to be able share the port with _independent_ applications. Something that does not work with TCP/TLS but it is possible with QUICK. 

 _maybe_ the flow would be to get _everything_ Kestrel may support upfront and then select specific HTTP version in the callback ...? (H3 only one for now)

**Comment by JamesNK** [comment]
Chris, have you ever seen people use SNI to configure a non-standard ALPN?

Hypothetical future scenario:
* A Kestrel port is configured to support HTTP/3 and future HTTP/4. Kestrel knows upfront that the only ALPN's it cares about for the port are `SslApplicationProtocol.Http3` and a future `SslApplicationProtocol.Http4`.
* Port is also configured to use `ServerOptionsSelectionCallback` to customize `SslServerAuthenticationOptions` based on server name. Based on the server name the callback returns auth options that have either HTTP/3 or HTTP/4 ALPN. If a different ALPN is configured in the callback then we throw an error.

Workable?

**Comment by Tratcher** [comment]
I've seen some apps that have conditionally enabled/disabled HTTP/2 per SNI by customizing the ALPN. That works fine with Kestrel. You can only use protocols kestrel knows about though.

> Hypothetical future scenario:
> 
> * A Kestrel port is configured to support HTTP/3 and future HTTP/4. Kestrel knows upfront that the only ALPN's it cares about for the port are `SslApplicationProtocol.Http3` and a future `SslApplicationProtocol.Http4`.
> * Port is also configured to use `ServerOptionsSelectionCallback` to customize `SslServerAuthenticationOptions` based on server name. Based on the server name the callback returns auth options that have HTTP/3 and/or HTTP/4 ALPN. If a different ALPN is configured in the callback then we throw an error saying an unexpected ALPN was provided.

Maybe? It's worth a try.

**Comment by ManickaP** [comment]
@nibanks when we open listener we need to provide list of ALPN to listen for, but we also set ALPN when we call `ConnectionSetConfiguration` when we accept the connection. What would happen if the ALPN list here changed? Let's say narrowed down?

**Comment by nibanks** [comment]
I _believe_ any change would be ignored. The ALPN has already been negotiated by the time you get the Listener callback.

**Comment by wfurt** [comment]
We still should be able to set the certificate, right @nibanks?  (e.g. the handshake is not fully finished)

**Comment by ManickaP** [comment]
Triage: open issue in msquic to be able to narrow down the ALPN selection when connection arrives. But we need to provide the full supported list when we start the listener.

**Comment by Tratcher** [comment]
To closely match the SslStream API, the second stage ALPN selection would still be a prioritized list rather than a single entry. S.N.Q or MsQuic would be responsible for the final selection.

**Comment by karelz** [comment]
Triage: This is about future proofing -- once we have more than 1 ALPN for HTTP over QUIC. Currently there is only one "h3".
Direct QUIC users will have to set ALPN upfront.

**Comment by ManickaP** [comment]
Triage: msquic issue has been fixed, we should add a test for this and call it done.
