### ISSUE TITLE
Interop.HostPolicy.corehost_resolve_component_dependencies can return duplicate paths

### ISSUE THREAD

**Issue by anhaehne** [dotnet/runtime#49425]
### Description

When instantiating an `AssemblyDependencyResolver` instance the method `Interop.HostPolicy.corehost_resolve_component_dependencies` can return duplicate entries causing a `System.ArgumentException` (Message: An item with the same key has already been added. Key: hhnl.PlugIn.Tests.TestPlugIn).

I've created a sample project to reproduce my issue. Steps:

1. Clone https://github.com/anhaehne/AssemblyDependencyResolver-argument-exeption
2. Rebuild Solution (Important! The project `hhnl.PlugIn.Tests.TestPlugIn` has no reference to `hhnl.PlugIn.Host`)
3. Run hhnl.PlugIn.Host

### Configuration

.net: .net 5
OS: Windows 10
ARCH: x64

### Regression?

Probably not. Also doesn't work on .net core 3.1

**Comment by anhaehne** [comment]
Thanks for the quick response. I can confirm that this is fixed in .NET 6 preview 1. 

Will this make its way back into .NET 5?

**Comment by vitek-karas** [comment]
As far as I know yours is the first requires to backport to 5...

@agocke @LakshanF What do you think - is it worth backporting to 5?

**Comment by agocke** [comment]
Are there any possible workarounds for the issue?

**Comment by vitek-karas** [comment]
The ones we've seen so far were all different casing. If the path specified in the parameter was the same just different case from the path on disk - this would happen. The workaround is simple, just make sure to use the same casing - it will work.

But this issue doesn't seem to be that problem - I haven't debugged this to be able tell specifically for this issue.

**Comment by agocke** [comment]
My inclination is that we shouldn't backport, since this behavior has been around since at least 3.1, but if there's some specific problem with no workaround then maybe it's worth another look

**Comment by anhaehne** [comment]
I can confirm that it was an issue with the path's casing. 
In my example the Project is call TestPlugin (lowercase i) but the path i supplied was TestPlugIn (uppercase i). 

Thank you all for your help.
