### ISSUE TITLE
Add back Reflection.Emit APIs from .NET Framework

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49452]
As a follow up to #46681 and #49319, I looked at the rest of the APIs that were missing from Reflection.Emit:

```
Compat issues with assembly System.Reflection.Emit:
MembersMustExist : Member 'public System.Reflection.Emit.ModuleBuilder System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(System.String, System.Boolean)' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Reflection.Module System.Reflection.Emit.ConstructorBuilder.GetModule()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.String System.Reflection.Emit.ConstructorBuilder.Signature.get()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Reflection.Module System.Reflection.Emit.MethodBuilder.GetModule()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.String System.Reflection.Emit.MethodBuilder.Signature.get()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Diagnostics.SymbolStore.ISymbolDocumentWriter System.Reflection.Emit.ModuleBuilder.DefineDocument(System.String, System.Guid, System.Guid, System.Guid)' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'protected System.ModuleHandle System.Reflection.Emit.ModuleBuilder.GetModuleHandleImpl()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Boolean System.Reflection.Emit.ModuleBuilder.IsTransient()' does not exist in the reference but it does exist in the implementation.
Total Issues: 8
```

The following APIs don't exist (and shouldn't) in .NET Core because we don't support saving the generated assembly to disk. (#15704)
* `AssemblyBuilder.DefineDynamicModule`
* `ModuleBuilder.DefineDocument`

The following API is because of an implementation detail, and doesn't need to be exposed since it has never been exposed:
* `ModuleBuilder.GetModuleHandleImpl` (See the [code comment](https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Reflection/Module.cs#L23) for an explanation)

That leaves the following APIs to be decided if we should bring them back:

* `Module ConstructorBuilder.GetModule`
* `Module MethodBuilder.GetModule`
* `string ConstructorBuilder.Signature`
* `string MethodBuilder.Signature`
* `bool ModuleBuilder.IsTransient`

1. The `Signature` properties seem pretty simple. They return a string represenation of the signature of the method.

2. The `GetModule()` methods are interesting because these types already have a `Module` property on them. Looking at the code, the `GetModule()` method and the `Module` property don't have the same code, but eventually return the same thing - the module of the type containing this Method.

3. I'm not exactly sure what `IsTransient` means, and the [MSDN doc](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.modulebuilder.istransient) doesn't give a good explanation.

> Returns a value that indicates whether this dynamic module is transient.

Looking at the code, on mono it [always returns `true`](https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/mono/System.Private.CoreLib/src/System/Reflection/Emit/ModuleBuilder.Mono.cs#L121-L124). On `coreclr`, it calls into the native runtime, and the only place I can see setting the flag, always sets it to `true` as well.

https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/coreclr/vm/assembly.cpp#L180

__________

So I guess after all that, the only API I'd recommend adding back is the `ConstructorBuilder.Signature` and `MethodBuilder.Signature` properties. I don't think we need to add the other missing APIs.

**Comment by jkotas** [comment]
Looks like the APIs on the list are public in the implementation, but missing in the ref file. I think we should just mark them private/internal in the implementation, or delete them if they are not actually used.

**Comment by buyaa-n** [comment]
> So I guess after all that, the only API I'd recommend adding back is the `ConstructorBuilder.Signature` and `MethodBuilder.Signature` properties. I don't think we need to add the other missing APIs.

@eerhardt are you OK with just removing the implementation of those APIs as @jkotas  [suggested ](https://github.com/dotnet/runtime/issues/49452#issuecomment-796235202) (I choose to remove them because I don't see they are actually used). Or do you still want to add an API proposal to add them in ref and go through API review?

**Comment by eerhardt** [comment]
I'm 100% fine with removing the implementation. If we made it this long without someone complaining, they must not be necessary. We can always add them in the future if someone does find a need for them.

**Comment by i3arnon** [comment]
I can take this if that's fine.
I made a PR removing the unused code.
I'm not sure how to generate the RefApiCompatBaseline though..

**Comment by krwq** [comment]
@i3arnon I believe you just need to remove this file https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Reflection.Emit/src/MatchingRefApiCompatBaseline.txt (or the entries you have fixed)

**Comment by KalleOlaviNiemitalo** [comment]
> I'm not exactly sure what IsTransient means

According to the [AssemblyBuilder.DefineDynamicModule](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.definedynamicmodule?view=netframework-4.8) docs, the methods that have a `string fileName` parameter define a persistable module, and the methods without this parameter define a transient module. [AssemblyBuilder.Save](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder.save?view=netframework-4.8) then "saves all non-transient dynamic modules".
