### ISSUE TITLE
Exception on IHostApplicationLifetime.StopApplication()

### ISSUE THREAD

**Issue by Leon99** [dotnet/runtime#49473]
_xxx type only implements IAsyncDisposable. Use DisposeAsync to dispose the container._ is thrown on calling `IHostApplicationLifetime.StopApplication()` if there's a service in the container that implements `IAsyncDisposable` but not `IDisposable`. Any ideas how to deal with it (other than calling `DisposeAsync().GetAwaiter().GetResult();` from `Dispose()`, which may lead to a deadlock)? I suspect having `IHostApplicationLifetime.StopApplicationAsync()` could help, but it doesn't exist.

**Comment by davidfowl** [comment]
Can you show the stack trace? Where are disposing the host from?

**Comment by Leon99** [comment]
```
This exception was originally thrown at this call stack:
    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
    Cli.CrawlService.StartAsync(System.Threading.CancellationToken) in CrawlService.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken)
    ...
    [Call Stack Truncated]
```

**Comment by davidfowl** [comment]
In the CrawlService, are you making a custom service scope and calling Dispose instead of DisposeAsync? Why?

**Comment by Leon99** [comment]
Hmm, looking at that stack - it's not exactly what I saw initially, I changed the code significantly since then but didn't save the stack trace (shame on me) and now I just tried to reproduce it. Initially, it was failing on StopApplication(), although it's on the last line in that method... Anyway, to answer your question - I don't call Dispose explicitly, but I do `using var scope = _serviceScopeFactory.CreateScope();` and then resolve the service from that scope.

**Comment by davidfowl** [comment]
Unfortunately, the workaround for this is a big ugly:

```C#
public static class ServiceScopeExtensions
{
    public static AsyncServiceScope CreateAsyncServiceScope(this IServiceProvider serviceProvider)
    {
        return new AsyncServiceScope(serviceProvider.CreateScope());
    }
}

public struct AsyncServiceScope : IServiceScope, IAsyncDisposable
{
    private readonly IServiceScope _serviceScope;

    public AsyncServiceScope(IServiceScope serviceScope)
    {
        _serviceScope = serviceScope;
    }

    public IServiceProvider ServiceProvider => _serviceScope.ServiceProvider;

    public void Dispose()
    {
        _serviceScope.Dispose();
    }

    public ValueTask DisposeAsync()
    {
        if (_serviceScope is IAsyncDisposable ad)
        {
            return ad.DisposeAsync();
        }
        _serviceScope.Dispose();
        return ValueTask.CompletedTask;
    }
}
```

Then you can change your code to do this:

```
await using var scope = _serviceProvider.CreateAsyncServiceScope();
```

**Comment by davidfowl** [comment]
See https://github.com/dotnet/runtime/issues/43970 for more information.

**Comment by davidfowl** [comment]
Closing this one
