### ISSUE TITLE
System.Drawing.Common targeting Unix framework is too broad

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#49479]
https://github.com/dotnet/runtime/blob/877a8df6716be6a7f98e95d17007619502c43b71/src/libraries/System.Drawing.Common/src/System.Drawing.Common.csproj#L8 targets Unix TFM but in reality, the assembly is supported only on few Unix platforms. 

The target needs to be updated to exclude all Unix-like platforms where the assembly is not supported or even better would be to retarget it for Linux and macOS only where it's only supported.

**Comment by safern** [comment]
Given that we annotated this assembly as `SupportedOSPlatform("Windows")` and that we are no longer supporting `System.Drawing.Common` on non-windows. I will close this issue as it is no longer applicable and once main becomes .NET 7, I will nuke the Unix implementation.
