### ISSUE TITLE
Remove unnecessary suppressions of IL2060 after trimmer intrinsic handling

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#49486]
https://github.com/mono/linker/pull/1880 introduces some basic intrinsic handling of `MakeGenericMethod` and trimmer will not warn with `IL2060` in the trivial cases.

We should remove the suppressions in the framework which are not needed anymore after this change.

**Comment by eerhardt** [comment]
Note that this is blocked on getting a new linker version in dotnet/runtime. And integrating the new version is blocked on https://github.com/mono/linker/issues/1887
