### ISSUE TITLE
Few broken links in markdown files

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#49490]
See https://github.com/Youssef1313/runtime/actions/runs/643550434

cc: @danmoseley Per previous discussion on having a GitHub Action that verifies links. There doesn't seem to be a markdownlint rule for it, so I made my own GH Action. Above is the results from the run. Let me know if it contains any false positives.

I don't know if you'll want to have the repo use this GH Action. You can either only fix the links, or both fix them and add the workflow.

**Comment by SimonCropp** [comment]
#50653 is merged, so this should be closed?
