### ISSUE TITLE
Adding default empty Save() to System.Xml.XmlDocument 

### ISSUE THREAD

**Issue by Lawrence-Williams** [dotnet/runtime#49510]
## Background and Motivation

To make it even easier to use the System.Xml.XmlDocument class it should be possible to call .Save() without parameters and for an XmlDocument object to remember the last file passed with a .Load(string filename) call since frequently calls to .Save(string filename) are simply saving the XML to the same file it was loaded from in the first place.

## Proposed API

https://github.com/dotnet/runtime/compare/main...Lawrence-Williams:XmlDocumentAddSaveToLoadedFile

```diff
namespace System.Xml
{
    public class XmlDocument : XmlNode
    {
+        private string _lastLoadedFile;

        public virtual void Load(string filename)
        {
+             _lastLoadedFile = filename;
        }

+        public virtual void Save()
+        {
+            Save(_lastLoadedFile);
+        }
    
```

## Usage Examples

``` C#
        XmlDocument myXmlDocument = new XmlDocument();
        myXmlDocument.Load("C:\myXmlPath.xml");
        myXmlDocument.SelectSingleNode("\myRoot\Name").InnerText = "My new name";
        myXmlDocument.Save();
```

## Risks

A user might call .Save() without having called .Load(string filename) with a file path causing an exception.

**Comment by krwq** [comment]
@Lawrence-Williams I strongly believe that APIs created for developers should be explicit and it should be very clear what they're doing - any kind of guessing what user wanted on the APIs is usually problematic long term. I.e. some apps might want to also create a backup file before saving, some other sync file elsewhere - now we start getting into space which might have many approaches to the solution and that's not responsibility of XML APIs. On top of that it would be inconsistent with other APIs which don't guess. IMO it's the UI's job to make user experience better and pick a right approach for particular job and not for back-end APIs to guess.

I'll close this issue as won't fix.
