### ISSUE TITLE
On MacOS, Object contains only the public half of a key pair. A private key must also be provided

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#49528]
### Description
On MacOS, we created a self-issued valid certificate with private key.
If we add the certificate into LocalMachine\My, trying to sign with this certificate by specifying store, the signing will fail for:  
`Object contains only the public half of a key pair. A private key must also be provided`
If we export the same certificate using X509ContentType.Pfx and specifying password, the signing will be successful.

Is this expected?
Is it caused by private key could not be accessed if it's in LocalMachine\My store? 
Any workaround could make it work? Thanks!

### Configuration

MacOS Mojave 10.14.6
dotnet SDK 5.0.200

**Comment by vcsjones** [comment]
> trying to sign with this certificate by specifying store

I'm not exactly clear what this means. Here is what I tried, and the private key is correctly associated with the certificate:

```csharp
using System;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

using RSA rsa = RSA.Create();
string cn = $"CN={Guid.NewGuid()}, L=AGH";
CertificateRequest req = new CertificateRequest(cn, rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
using X509Certificate2 cert = req.CreateSelfSigned(DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddDays(3.14));
using X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite | OpenFlags.OpenExistingOnly);

store.Add(cert);

X509Certificate2 certFromStore = store.Certificates.Find(X509FindType.FindBySubjectDistinguishedName, cn, false)[0];
Console.WriteLine(certFromStore.HasPrivateKey);
```

And Keychain indicates that the private key is associated with the certificate:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/361677/111088049-8fd9b780-84fb-11eb-9a5e-d7f25713f210.png">

**Comment by heng-liu** [comment]
Thanks for your reply!
I tried to add the self-issued certificate to trusted store on Mac, which is LocalMachine\My.
However, there is no API for adding certificate to LocalMachine\My.
So I tried to run the following command to add the cert to LocalMachine\My: (refer to https://ss64.com/osx/security-cert.html)
 `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain  <certFile>.`

But looks like the private key is stripped when I wrote the certificate to a file: (TrustedCert is the X509Certificate2 with private key)
File.WriteAllBytes(certFile.FullName, TrustedCert.RawData);
So later the signing failed for not being able to find the private key.

I tried to export the TrustedCert by using X509ContentType.Pfx, but the adding command failed for "`SecCertificateCreateFromData: Unknown format in import.`"

Sorry it looks it's off the topic for the original question, but may I know if there is any way to add the certificate file with private key to store LocalMachine\My by running command successfully?

**Comment by vcsjones** [comment]
> file with private key to store LocalMachine\My by running command successfully?

This can be done in two steps - I don't know how to do it in a single command (if it is possible).

First, import the PFX.

```
sudo security import ~/ca/certificate.pfx -k /Library/Keychains/System.keychain
```

This will import the certificate and private key. At this point though, the certificate is not trusted. Then, import it again using `add-trusted-cert` using just the public key.

```
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/ca/cert.pem
```

The keychain store will dedupe and mark the existing certificate (with the private key) as trusted.

**Comment by heng-liu** [comment]
Thanks @vcsjones! That's very helpful!
