### ISSUE TITLE
System.Numerics types missing copy constructors?

### ISSUE THREAD

**Issue by tamlin-mike** [dotnet/runtime#49536]
## Background and Motivation

While trying to convert an exising code base to use `System.Numerics.Vector3` I came across a truly baffling omission -- `Vector3` lacks a copy ctor.

## Proposed API

Copy constructor on all `System.Numerics` types.

## Usage Examples
``` C#
Vector3 a; // ..
Vector3 b = new Vector3(a); // imagine this is done in a generic function, so that actual src reads `b = new T(a);`
```
-->

## Alternative Designs

None.

## Risks

AFAICT: None.

**Comment by Joe4evr** [comment]
`Vector3` is a struct, so it always gets copied regardless, no special constructor necessary.
```cs
Vector3 b = a; //oh look, copied just like that
```

**Comment by tannergooding** [comment]
Joe4evr is correct, copy constructors are fairly non-standard in C#, particularly for value types because the default behavior is to copy on assignment.

You would really only need one if you needed to do some custom behavior on copy. However, since C# doesn't allow overriding the assignment operator like C/C++, this can make "correctness" difficult.

> // imagine this is done in a generic function, so that actual src reads `b = new T(a);`

There is no way to specify `new T(a)` is valid in generic code today, only `new T()` so this code would never be valid.

**Comment by tamlin-mike** [comment]
@Joe4evr It was the syntax I was looking for, to allow it to be used in generics. However, @tannergooding displays the door for writing such reusable (generic) code is well and firmly closed:

> There is no way to specify `new T(a)` is valid in generic code today, only `new T()`

**Comment by Joe4evr** [comment]
@tamlin-mike 
> It was the syntax I was looking for, to allow it to be used in generics.

That doesn't matter because generic methods (and types) are always recompiled for every different struct type argument that they are given, so assignment behavior is always preserved.

**Comment by tamlin-mike** [comment]
@Joe4evr I had hoped (even _expected_) to be able to use the same _syntax_ for object copying whether or not it was a `ValueType` or `Object`, disregarding the (significant) performance hit from using anything but the default ctor for structs.

The scenario leading me onto this path was while testing to migrate an existing code base to use `Numerics` types, and finding the need for some methods/functions to handle both the previously used vec3f (+quat and matrix, all of `Object` type) and the `Numerics` version.

But since it has been clearly displayed the language doesn't even support the _concept_ of generic programming in the (to me) expected way when structs are involved, it's obviously a futile task.

**Comment by tannergooding** [comment]
Templates and generics are two different features with different goals and requirements.

C# has distinct concepts of value types vs reference types and reference types are automatically tracked and managed by the GC. Value types are copied by value and there is no real concept of "ownership/move" semantics so there is little need for copy constructors to exist and just doing `x = y` will do the correct thing for almost all .NET code.

**Comment by tfenise** [comment]
Although `new T(a)` is not valid generic code, there is some (ugly) workaround. Define
```
interface ICopyable<T>
{
    void CopyTo(out T destination);
}
```

A type with trivial copy operation can be wrapped in a struct implementing `ICopyable<T>`:
```
struct MyFloat : ICopyable<MyFloat>
{
    float value;

    public void CopyTo(out MyFloat destination)
    {
        destination = this;
    }
}
```

A type with nontrivial copy operation:
```
struct MyFloats : ICopyable<MyFloats>
{
    float[] values;

    public void CopyTo(out MyFloats destination)
    {
        destination.values = (float[])values?.Clone();
    }
}
```

Then you can write:
```
T a = ...;
T b;
a.CopyTo(out b);
```
with generic constraint `where T : ICopyable<T>`.

Of course your generic codes are probably not just copying objects around. You can define `IAddable` `IMultiplyable` and use them similarly.
