### ISSUE TITLE
ComponentModel Category attribute with UseSystemResourceKeys is broken

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49554]
Publish and run the following application with and without UseSystemResourceKeys being set:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```

```C#
using System;
using System.ComponentModel;

namespace BugRepro
{
    class Program
    {
        static void Main()
        {
            Console.WriteLine(GetEnumCategory(AnEnum.Somthing));
        }
        
        public static string GetEnumCategory<T>(T enumValue)
            where T : struct, IConvertible
        {
            if (!typeof(T).IsEnum)
                return null;
            var enumCategory = enumValue.ToString();
            var fieldInfo = enumValue.GetType().GetField(enumValue.ToString());
            if (fieldInfo != null)
            {
                var attrs = fieldInfo.GetCustomAttributes(typeof(CategoryAttribute), false);
                if (attrs != null && attrs.Length > 0)
                {
                    enumCategory = ((CategoryAttribute)attrs[0]).Category;
                }
            }
            return enumCategory;
        }
    }

    public enum AnEnum
    {
        [Category("SomthingCat")]
        Somthing = 52,
    }
}
```

```
❯ dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimMode=link -p:UseSystemResourceKeys=false
❯ C:\DotNetTest\BugRepro\bin\Debug\net5.0\win-x64\publish\BugRepro.exe
SomthingCat

❯ dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimMode=link -p:UseSystemResourceKeys=true
❯ C:\DotNetTest\BugRepro\bin\Debug\net5.0\win-x64\publish\BugRepro.exe
PropertyCategorySomthingCat
```

_______________________

The reason this happens is because of this code:

https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/CategoryAttribute.cs#L170-L182

If `GetLocalizedString` returns `null`, `Category` just returns what was passed to the ctor. But if `GetLocalizedString` doesn't return `null`, it uses what came from `GetLocalizedString`. Which looks like:

https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.ComponentModel.Primitives/src/System/ComponentModel/CategoryAttribute.cs#L200

This is looking for resources in our assembly named `PropertyCategoryXXX` where `XXX` is the category name. For example:

https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.ComponentModel.Primitives/src/Resources/Strings.resx#L120-L125

One option is to turn `UseSystemResourceKeys` off for this assembly. Or we could try to change the code somehow to do something different when `UseSystemResourceKeys=true`.

**Comment by rogerge88** [comment]
We will follow your instruction and test it.  Thanks
