### ISSUE TITLE
SuperPMI doesn't capture exception code from crossgen2 thrown exception on Linux

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#49563]
On Linux, when SuperPMI collects a crossgen2 compile, and crossgen2 throws an exception across the JIT-EE interface for a call to `getCallInfo`, SuperPMI can't capture the thrown exception code. The following code in `interceptor_ICJI::getCallInfo()`, src\coreclr\ToolBox\superpmi\superpmi-shim-collector\icorjitinfo.cpp, wraps the call to crossgen2:
```
    PAL_TRY(Param*, pOuterParam, &param)
    {
        PAL_TRY(Param*, pParam, pOuterParam)
        {
            pParam->pThis->mc->cr->AddCall("getCallInfo");
            pParam->pThis->original_ICorJitInfo->getCallInfo(pParam->pResolvedToken, pParam->pConstrainedResolvedToken,
                                                             pParam->callerHandle, pParam->flags, pParam->pResult);
        }
        PAL_EXCEPT_FILTER(FilterSuperPMIExceptions_CaptureExceptionAndContinue)
        {
        }
        PAL_ENDTRY
    }
    PAL_FINALLY
    {
        this->mc->recGetCallInfo(pResolvedToken, pConstrainedResolvedToken, callerHandle, flags, pResult,
                                 param.exceptionCode);
    }
    PAL_ENDTRY
}
```

In my investigation, the `FilterSuperPMIExceptions_CaptureExceptionAndContinue` function is never called. However, the exception is caught, as the code in the `PAL_FINALLY` is executed.

To repro, remove the `#ifdef HOST_UNIX` workaround added in https://github.com/dotnet/runtime/pull/49531, then do a SuperPMI collection, e.g.:
```
# 1. build dotnet/runtime for Linux x64 Checked in the ~/gh/runtime directory, and create a Core_Root
# 2. clone dotnet/jitutils into ~/gh/jitutils and build it using "bootstrap.sh"
# run:
python3 ~/gh/runtime/src/coreclr/scripts/superpmi.py collect --crossgen2 -pmi_location ~/gh/jitutils/bin/pmi.dll -output_mch_path ~/linux.x64.checked.mch -arch x64 -build_type checked -assemblies ~/gh/runtime/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root
```

**Comment by sandreenko** [comment]
I saw a similar (same?) problem but I think it is not related to crossgen2, before #49045 when I tried to do a collection and there was an exception (like zero-dereferencing) the Linux just crashed instead of reporting and continue.

**Comment by janvorli** [comment]
I believe this is a C++ problem - the `PAL_SEHException` type compiled in JIT is internally not the same type as the `PAL_SEHException` type compiled in the runtime / other shared library. The type is defined in pal.h, so it gets compiled separately for each exe / shared library that references it. That would explain why it is not caught. There are some details on the issue here: https://gcc.gnu.org/wiki/Visibility.

**Comment by BruceForstall** [comment]
I haven't verified, but presumably when the JIT calls back to `getCallInfo` in crossgen2 directly, and crossgen2 throws an exception, the JIT can catch it, or we would have bigger problems. I presume the issue is presumably only when the call chain is JIT -> superpmi-shim-collector -> crossgen2, exception thrown by crossgen2.

It seems to be only related to filters? Maybe the JIT just catches all exceptions, so doesn't compare types? Or maybe there's an issue where the coreclr and JIT are linked to the same PAL, and superpmi-shim-collector is not, leading to a different understanding of `PAL_SEHException` identity?

**Comment by janvorli** [comment]
Ah, looking at the crossgen2 jitinterface, I can see it throws exceptions of type CorInfoExceptionClass that has nothing to do with PAL_SEHException. PAL emulation of exception filters can only work with PAL_SEHException exceptions (which emulate the Windows SEH exceptions).

**Comment by davidwrighton** [comment]
It has to do with the detail that only the SPMI exceptions are expected to be caught across the JIT-EE boundary like this. Pat Gavlin did some work years ago to remove the dependency for everything other than SPMI. I'm working on a fix now.
