### ISSUE TITLE
HTTP/3: Support SslServerAuthenticationOptions with QUIC

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#49574]
[SslServerAuthenticationOptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslserverauthenticationoptions?view=net-5.0) is the primary type for configuring HTTPS/TLS in Kestrel. It is designed for SslStream but most of the options can be mapped to QUIC.

The goal is to make setting a certificate for HTTP/3 to be like setting a certificate for other protocols.

Break down of its properties:

* [x] AllowRenegotiation. Not sure if this is supported in QUIC or not. Crypto settings can't change once started with QUIC. ~Alternatively, might map to [QUIC_SERVER_RESUMPTION_LEVEL](https://github.com/microsoft/msquic/blob/73bd4a7700b9d0c4f9570a46734eb9bf40f8448f/src/inc/msquic.h#L122)~.
* [x] ApplicationProtocols. Already using successfully.
* [x] CertificateRevocationCheckMode. No built in support. Can we implement manually with .NET APIs?
* [ ] ~CipherSuitesPolicy. Not currently supported.~ Tracked separately as #55378
* [ ] ClientCertificateRequired. [QUIC_CREDENTIAL_FLAG_REQUIRE_CLIENT_AUTHENTICATION](https://github.com/microsoft/msquic/blob/bc311296fa424c74d1a8177e7faceb3e2804d898/src/inc/msquic.h#L102).
* [x] EnabledSslProtocols. Not revelevent.
* [x] EncryptionPolicy. Not revelevent.
* [x] RemoteCertificateValidationCallback. [QUIC_CREDENTIAL_FLAG_INDICATE_CERTIFICATE_RECEIVED](https://github.com/microsoft/msquic/blob/bc311296fa424c74d1a8177e7faceb3e2804d898/src/inc/msquic.h#L100).
  * certificate - Passed as a platform sepecific certificate type.
  * chain - resolve from certificate?
  * sslPolicyErrors - figure this out ourselves?
* [x] ServerCertificate. Already used.
* [x] ServerCertificateContext. Not sure about this one.
* [ ] ~ServerCertificateSelectionCallback. Used for SNI. Already used as part of setting the server certificate with a listener connection. Relevent: https://github.com/microsoft/msquic/blob/73bd4a7700b9d0c4f9570a46734eb9bf40f8448f/src/inc/msquic.h#L753~ Extracted to #55421

System.Net.Quic currently has an out of date version of msquic. Current blocked on msquic update: https://github.com/dotnet/runtime/issues/44580

**Comment by JamesNK** [comment]
Moved to runtime. Changes will need to be made here in QUIC library.

@geoffkizer

**Comment by geoffkizer** [comment]
@wfurt Can you help with some of these?

**Comment by geoffkizer** [comment]
> CertificateRevocationCheckMode

What does msquic do currently? Just not check for revocation?

**Comment by wfurt** [comment]
Is the server certificate working on Linux @JamesNK? 

From the list:
- allow renegotiation: we should ignore and not applicable to TLS13. The resumption is whole different connect and and should not be mixed. 

For the revocation, we can most likely use X509Chain to do verification via custom callback. This is generally What we do now for SslStream. 

For the ServerCertificateContext aka custom trust we will need to check and probably make API changes. It will work on Windows as ServerCertificateContext puts intermediate certificates to the CA store. Validation may still be problematic. 

I think we should focus on marshaling certificates in & out and making that consistent across all platforms. 
I can take a look and perhaps we can reuse or mimic parts of X509Certificate2 PAL.

**Comment by JamesNK** [comment]
> Is the server certificate working on Linux @JamesNK?

I have been purely testing on Windows so I don't know about Linux. Other devs are using Linux so I assume it is working there.

**Comment by JamesNK** [comment]
> > CertificateRevocationCheckMode
> 
> What does msquic do currently? Just not check for revocation?

I'm not sure. It could also be the opposite: msquic only accepts non-revocated client certs.

**Comment by JamesNK** [comment]
@nibanks This is the list I put together after our meeting comparing TLS server configuration in .NET to msquic.

What is msquic behavior without a [CertificateRevocationCheckMode](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslserverauthenticationoptions.certificaterevocationcheckmode?view=net-5.0#System_Net_Security_SslServerAuthenticationOptions_CertificateRevocationCheckMode) property?

**Comment by ManickaP** [comment]
> Is the server certificate working on Linux @JamesNK James Newton-King FTE?

I'll answer that, no it isn't, we're using "tls_stub" msquic version to work around that ATM.

**Comment by wfurt** [comment]
The `ServerCertificateSelectionCallback` and `RemoteCertificateValidationCallback` should be fully functional now. We get certificate from MsQuic and we use X509Chain to construct the chain as well as to check validity including revocation. 

I'm wondering if it would make sense to trace remain tasks separately. I think it would be easier to track and argue about priority than large mega issue. For example, https://github.com/microsoft/msquic/pull/1430/ added support for Cipher selection but there are 3 max to choose from so it seems pretty marginal.

**Comment by ManickaP** [comment]
Meeting notes:
@wfurt will spawn new issues for the missing points and this issue will be closed.
@geoffkizer promised to look into QUIC spec whether it supports SNI based cert selection. If not, the last point is moot, if yes and msquic doesn't support it, we need to file an issue there and then follow up with our code.

**Comment by ManickaP** [comment]
**ClientCertificateRequired. QUIC_CREDENTIAL_FLAG_REQUIRE_CLIENT_AUTHENTICATION** is the last thing on the list, that hasn't been crossed out.
@wfurt what is the state of that? So that we can close this issue.

**Comment by wfurt** [comment]
That should be fixed with #54302 @ManickaP. The server part is OK but on client MsQuic does not support it on Linux and I'm going to open issue for tracking. It _should_ light up when read as the certificate handling is shared with server e.g. on Linux we should marshall the portable buffer instead of Windows certstore handle.

**Comment by wfurt** [comment]
https://github.com/microsoft/msquic/issues/1803 opened to track the Linux support in MsQuic

**Comment by ManickaP** [comment]
Closing then, all should be either resolved or tracked by one of:  #55378,  #55421 and https://github.com/microsoft/msquic/issues/1803
