### ISSUE TITLE
Dotnet Runtime 6.0.0-preview 2 issue macOS arm64 issue.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#49609]
I have the an application running correctly on a mac m1 machine with .NET runtime 5.0.3 x64 runtime installed.

Signal published file with Target framework: 5.0, Target runtime: osx-x64.

I installed  .NET Runtime 6.0.0-preview.2  Arm64 packaged and the tried running the  application and fails with the following errors.  

Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

I understand why this is happening but why doesn't the application start mechanism detect this issue and run  the correct runtime as the 5.0.3 runtime is still installed?

Another question is there a way I can run previews m1 with 5.0.x x-64 runtimes side by side?

As a side if I install the macOS 6.0.0 preview-2 x64 package the application executes correctly and has opened the 5.0.3 runtime dlls. So  the startup does detect which runtime to use.

Regards,
Bob

**Comment by vitek-karas** [comment]
Just to confirm - the application you're trying to run is framework dependent single-file, right? (the size of the app should be pretty small, less than 10MB typically, unless your app code is really big).
The above should not happen for self-contained single-file apps.

**Comment by vitek-karas** [comment]
@sdmaclea - this is basically another case which requires the universal `hostfxr` - I think it should work, we just need to test it.

**Comment by speed2048** [comment]
Yes it is Framework-dependent and size of application is 2 MB.

**Comment by vitek-karas** [comment]
We're working on the SxS support - some of that work is here: https://github.com/dotnet/runtime/pull/48541

If you want to try 6.0 while still having 5.0 installed, you can download the zip of 6.0 instead and install it into a custom location (just make a directory in your home for example). Running SDK/CLI commands is easy by simply explicitly running `dotnet` from that directory. If you want to run applications on it, you may need to set `DOTNET_ROOT` to point to that directory before running the app.

**Comment by sdmaclea** [comment]
Unfortunately the zips are not currently signed, so you may have to sign them yourself to get them to work on M1 Big Sur.

**Comment by robertsundstrom** [comment]
So side-by-side has not been prioritized? It still does not work in Preview 4.
That is a shame, because of all the people with M1 Macs who wants to try .NET 6, while still having the older, emulated versions installed.

The PR has been closed, btw. So that is why I assume this.

**Comment by vitek-karas** [comment]
https://github.com/dotnet/designs/pull/217

We're very much working on it, but it's a rather complex thing to solve.

**Comment by agocke** [comment]
This looks like a dup of https://github.com/dotnet/installer/issues/11164. The installers overwrite each other right now. Until this is fixed, working from separate targz folders should work.
