### ISSUE TITLE
HTTP/3: Hang after 100 requests on a connection

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#49617]
HttpClient + HTTP/3 appears to consistently hang when making the 101st HTTP/3 requests to the server. I've looked at client and server logs and I believe the issue is HttpClient never sends the 101st request. The app calls `HttpClient.SendAsync`, nothing is received by the server, and the app hangs.

I'm guessing there is a setting that limits the number of concurrent streams to the server and that number isn't being reset by the client when requests are complete. When the 101st request is made the client thinks it has 100 requests in progress and hangs forever.

**Comment by geoffkizer** [comment]
There are QUIC issues re stream limits that are causing this. @ManickaP @CarnaViire @scalablecory Can we link the relevant issues?

It would be nice to unblock this usage scenario even if we don't have a completely final design re stream limits. Not being able to issue more than 100 requests seems like a severe limitation, especially for perf/stress testing.

**Comment by scalablecory** [comment]
This is due to #32079 not being finished. Once it is, it should be wired up to this method that is currently never called:

https://github.com/dotnet/runtime/blob/a0fc08e883803c8a49fede58bd4d512590f59254/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs#L283-L304

**Comment by JamesNK** [comment]
> It would be nice to unblock this usage scenario even if we don't have a completely final design re stream limits. Not being able to issue more than 100 requests seems like a severe limitation, especially for perf/stress testing.

+1. This is blocking working on perf testing. Also I have HTTP/3 setup with the gRPC interop tests, some of which make more than 100 requests.

**Comment by ManickaP** [comment]
I'm aware of the priority here and I have this in my pipeline.
