### ISSUE TITLE
Http request content changed by httpclient

### ISSUE THREAD

**Issue by Guruumeditation** [dotnet/runtime#49643]
### Describe the bug

In a Blazor wasm application, I set the content of a http POST request content to "application/json" but when the client send it, it is wrongly send as "text/plain"

### To Reproduce

I made a simple solution with the problem.
The repo is : https://github.com/Guruumeditation/BlazorHttpIssue

Just launch the solution, it will launch a blazor client project and a web api.
You can click on the button to launch the http request
If you go to chrome dev tool you will see the request content is sent as "plain/text" when I set the content as "application/json"

### Further technical details
- ASP.NET Core version 5 or 6
- Visual Studio 2019 16.9.1 and Preview 16.10

SDK .NET (refl‚tant tous les fichiers global.json)ÿ:
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Environnement d'ex‚cutionÿ:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by lewing** [comment]
cc @pranavkm

**Comment by kjpou1** [comment]
Just as a quick response: If I remember correctly I have run into something like this before and it has something to do with how CORS vs No CORS works.  Also, there may even be differences with fetch implementations across browsers.

Fetch will only allow certain headers and content type set in each mode.  Not really something we can control and is part of browser.

**Comment by kjpou1** [comment]
Ah, here is some relevant information about CORS vs NOCors

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

- The only allowed values for the Content-Type header are:
application/x-www-form-urlencoded
multipart/form-data
text/plain

**Comment by kjpou1** [comment]
This also seems relevant and has a better discussion [Common no-cors misconceptions](https://evertpot.com/no-cors/).  Is this looking like your issue?

**Comment by kjpou1** [comment]
Yes, definitely sounds like `fetch` and `CORS` vs `no-cors` limitations

These are the main effects:

- Any request header except: Accept, Accept-Language, Content-Language, Content-Type will be silently stripped from the request.
- If Content-Type is something other than application/x-www-form-urlencoded, multipart/form-data or text/plain, the header is ignored and set to text/plain.
- If the HTTP request is anything other than GET, HEAD or POST, you will get an error.
You will not be able to read the response body, status or headers.

**Comment by kjpou1** [comment]
Run the API with the following or there will be errors:  `dotnet run --project TestBlazorHttp.Api/TestBlazorHttp.Api.csproj --urls=https://localhost:44310`

<img width="575" alt="image" src="https://user-images.githubusercontent.com/640466/111281207-f9adaa80-863c-11eb-8b68-a5a523769b75.png">

These types of errors are something that we can not catch as they are not passed up the chain.  In this case though it is because of the `no-cors` as the security protocol prohibits the reading of the `response body, status or headers`

**Comment by kjpou1** [comment]
without the `no-cors` setting we get the following:

<img width="1568" alt="image" src="https://user-images.githubusercontent.com/640466/111282104-ebac5980-863d-11eb-932d-b9ea04aafd1a.png">

With the preflight check and error:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/640466/111282193-054da100-863e-11eb-98c2-3157af5cd8d8.png">

**Comment by Guruumeditation** [comment]
OK, thanks. I will check that . Seems it is normal behavior then. I am coming from mobile dev, and not specialist in web dev so not aware of those subtle things :) 
Using Postman I can call the 3rd party api I want to use without all cors headers, so there must be a way to do it with blazor

**Comment by kjpou1** [comment]
Postman is a different program and does not rely on the browser Fetch API.  It is the browser security that you are running into.

**Comment by Guruumeditation** [comment]
OK, thanks a lot for the explanations. I'll close the issue as it is not a real one.
