### ISSUE TITLE
Absolute function with return sign

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#49654]
## Background and Motivation

Sometimes we want both absolute value and sign value to do calculation. So it would be convenient if we could get both value in the same operation

## Proposed API

```diff
namespace System
{
    public static class Math
    {
+       public static int Abs(int value,out int sign) => ;
+       public static long Abs(long value,out int sign) => ;
+       public static float Abs(float value,out int sign) => ;
+       public static double Abs(double value,out int sign) => ;
```

## Usage Examples

``` C#
public static float SignSqrt(float value)
{
    value = Math.Abs(value,out int sign);
    return sign * Math.Sqrt(value);
}
```

Additionally I wish to request that, please expose `ModF` and `SinCos` function. Ability to get many related value in one operation make code more compact and easier to do one line function in many situation

**Comment by tannergooding** [comment]
> Additionally I wish to request that, please expose ModF and SinCos function.

`SinCos` is already exposed and will ship in .NET 6. `ModF` needs its own proposal.

**Comment by Thaina** [comment]
@tannergooding Is there any reason it should consider not to be exposed?

**Comment by tannergooding** [comment]
> Sometimes we want both absolute value and sign value to do calculation

I'd expect it would be more efficient to do the following in all cases:
```csharp
public static float SignSqrt(float value)
{
    var absValue = Math.Abs(value);
    return Math.CopySign(Math.Sqrt(absValue), value);
}
```

Returning the sign here isn't the important bit, its copying the sign of one value to the sign of another and `Math.CopySign` will do this efficiently and without branching.

**Comment by Thaina** [comment]
@tannergooding That was for some easy example but I think to have `sign` value would be more flexible for other logic

```C#
public static (bool negative,int digit) CountDigit(int value)
{
    value = Math.Abs(value,out int sign);
    return (sign < 0,(int)Math.Log10(value));
}
```

**Comment by tannergooding** [comment]
I think I'd need to see more samples with real world usecases to justify this API.

There isn't any particular performance optimization or anything else that can be done here and so it is effectively just a wrapper for:
```csharp
var (abs, sign) = (Math.Abs(value), Math.Sign(value));
```

**Comment by Thaina** [comment]
@tannergooding It may seem little but

1 - It optimized by compare only one time
2 - It take value only one time into one line function

```C#
var l = Math.Abs(some.Deep.Property.Number.Value,out int ls);
if(Math.Abs(another.Deep.Property.Number.Value,out int rs) is var r && rs == ls)
    return (sameSign: true,diff: ls - rs); // return boolean sameSign

// do other things
```

**Comment by tannergooding** [comment]
Going to close this as I'd ideally like to see more support or usage scenarios.

As it is, I believe such a helper API can be trivially implemented if users really need this API.
