### ISSUE TITLE
Socket construct and address already in use behavior

### ISSUE THREAD

**Issue by pepone** [dotnet/runtime#49655]
The program bellow throws ` System.Net.Sockets.SocketException (48): Address already in use` as expected, if you replace  the call to  `new Socket(endpoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);`  by `new Socket(SocketType.Stream, ProtocolType.Tcp);` it no longer throws `Address already in use` on macOS on Windows the socket exception is thrown in both cases, haven't checked other OSs

```c#
using System;
using System.Net;
using System.Net.Sockets;

namespace socket_test
{
    class Program
    {
        public static Socket CreateSocket(string address, int port)
        {
            var endpoint = new IPEndPoint(IPAddress.Parse(address), port);
            var socket = new Socket(endpoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
            socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.NoDelay, 1);
            socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, 1);
            
            if (endpoint.AddressFamily == AddressFamily.InterNetworkV6)
            {
                socket.SetSocketOption(SocketOptionLevel.IPv6,
                                       SocketOptionName.IPv6Only,
                                       false);
                Console.WriteLine($"IPv6Only: {socket.GetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only)}");
            }
            socket.ExclusiveAddressUse = true;
            
            Console.WriteLine($"endpoint address: {endpoint.Address} port: {endpoint.Port}");
            socket.Bind(endpoint);
            socket.Listen();
            return socket;
        }
        
        static void Main(string[] args)
        {
            CreateSocket("::0", 12010);
            CreateSocket("0.0.0.0", 12010);
        }
    }
}
```

**Comment by tmds** [comment]
> it no longer throws Address already in use on macOS on Windows the socket exception is thrown in both cases, haven't checked other OSs

It throws on Linux also.

I guess on BSD this is a side-effect of setting `SO_REUSEADDR`:
https://github.com/dotnet/runtime/blob/ac5c33defa6a9983e85ce8bf0be352cb09f5b8eb/src/libraries/Native/Unix/System.Native/pal_networking.c#L1554-L1560

I think we need to set `SO_REUSEADDR` also on BSD to be able to bind during `TCP_WAIT`, so we need to accept the side effect.

**Comment by antonfirsov** [comment]
Just for clarity, the problem seems to be the following:
a dual stack socket "B", binding to an already used IPv4 address (bound to another dual-stack IPV4 socket "A") seems not to throw despite `SocketOptionName.ReuseAddress` being explicitly disabled via `ExclusiveAddressUse  = true`.

@pepone does this behavior cause any (real-life) problems for your use-case / application?

Also wondering: Does it change anything if  socket "A" is not dual mode?

**Comment by antonfirsov** [comment]
> I think we need to set SO_REUSEADDR also on BSD to be able to bind during TCP_WAIT

@tmds what is the reason we do this by default instead of letting users to opt-in via `SocketOptionName.ReuseAddress`?

To me it looks like it's practically impossible to opt-out for `SO_REUSEADDR` and the code that changes it in [`SystemNative_SetSockOpt`](https://github.com/dotnet/runtime/blob/ac5c33defa6a9983e85ce8bf0be352cb09f5b8eb/src/libraries/Native/Unix/System.Native/pal_networking.c#L2126-L2130) is ineffective in case of TCP.

**Comment by tmds** [comment]
> what is the reason prioritize enabling re-binding during TCP_WAIT (TIME_WAIT??) by default instead of letting users to opt-in via SocketOptionName.ReuseAddress?

Yes, TIME_WAIT. As explained by the comment, this is for Windows compatibility.

**Comment by pepone** [comment]
> does this behavior cause any (real-life) problems for your use-case / application?

Not really I can use the constructor that takes the address family parameter in my application and get the behavior I want.

> Also wondering: Does it change anything if socket "A" is not dual mode?

Yes, I think this only affects dual-mode sockets, binding twice to `::1` fails as expected with both constructors.

**Comment by tmds** [comment]
> Does it change anything if socket "A" is not dual mode?

It is about whether a more specific bound is allowed. A similar case is when you bind the same port on both `0.0.0.0` and `127.0.0.1` (or any other interface IP). The latter is considered a more specific bind.

I think we can close this.

**Comment by karelz** [comment]
Triage: Closing per suggestion above.
