### ISSUE TITLE
.NET 6 Preview 2 MacOS ARM64:  Unable to attach to CoreCLR. Unknown Error: 0x80131c3c

### ISSUE THREAD

**Issue by markus008** [dotnet/runtime#49665]
When I create new MVC app in .NET 6 Preview 2 in Visual Studio for Mac (Version 8.10 Preview (8.10 build 409)) I get this message as an output from debug. `Unable to attach to CoreCLR. Unknown Error: 0x80131c3c`.
Same problem I had with the stable build of Visual Studio for Mac (Version 8.9.1.34)

### Configuration
- macOS Big Sur 11.1
- Apple M1
- .NET 6 Preview 2 (6.0.100-preview.2.21155.3)
- Visual Studio for Mac (Version 8.10 Preview (8.10 build 409))

**Comment by sdmaclea** [comment]
We haven't shipped debugger support for Apple Silicon native with preview2. We are still working on deciding when to ship a beta

**Comment by sdmaclea** [comment]
We shipped native preview debugger support with preview4+.  VS Code debugger preview should be working.  

I am not sure how VS for MAC will need to be changed.  I suspect it won't work yet as it won't use the native debugger, but I am not sure yet. 

/cc @vitek-karas @AaronRobinsonMSFT @richlander @gregg-miskelly

**Comment by gregg-miskelly** [comment]
CC @mrward @slluis

**Comment by mrward** [comment]
VS Mac does not currently support using the native debugger. You should be able to use it with Rosetta if you have [macOS 11.2 or later](https://github.com/dotnet/runtime/issues/44958#issuecomment-772919940).

**Comment by tommcdon** [comment]
Closing this issue since .NET Core 6 preview 4+ supports Apple Silicon, and the .NET Core VS Code adapter has shipped with ARM64 support: https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.12
