### ISSUE TITLE
StartupHookProvider causing ILLink warnings in default blazor app

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49663]
Using the latest 6.0 SDK builds:

`dotnet new blazorwasm`
`dotnet publish -c Release -p:SuppressTrimAnalysisWarnings=false`

```
resource ILLink.Substitutions.xml in System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e : warning IL2008: Could not resolve type 'System.StartupHookProvider' [C:\DotNetTest\Net6Blazor\Net6Blazor.csproj]
```

Since `StartupHookProvider` doesn't exist in mono, we can't put its substitution in the 'shared' substitution file:

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.Shared.xml#L22-L24

cc @mateoatr

**Comment by vitek-karas** [comment]
@mateoatr  could you please move the descriptor part to the CoreCLR specific CoreLib descriptor?
