### ISSUE TITLE
NetEventSource is (copied) and instanced in many libs rather than once

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#49677]
Should there be a type forwards to the inbox so it only gets instantiated once?

Its a static usage e.g. `NetEventSource.Log.IsEnabled()`; 

However there are 13 copies embedded in libs (project src refs, presumably for OOB); so it gets instantiated many times:

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj#L55

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Http.WinHttpHandler/src/System.Net.Http.WinHttpHandler.csproj#L101-L102

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.HttpListener/src/System.Net.HttpListener.csproj#L59-L60

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Http/src/System.Net.Http.csproj#L119-L120

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Mail/src/System.Net.Mail.csproj#L61-L62

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.NameResolution/src/System.Net.NameResolution.csproj#L17-L18

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.NetworkInformation/src/System.Net.NetworkInformation.csproj#L55

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Ping/src/System.Net.Ping.csproj#L24-L25

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Primitives/src/System.Net.Primitives.csproj#L76-L77

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Quic/src/System.Net.Quic.csproj#L25

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Requests/src/System.Net.Requests.csproj#L54-L55

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Security/src/System.Net.Security.csproj#L56-L57

https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Sockets/src/System.Net.Sockets.csproj#L51-L52

![image](https://user-images.githubusercontent.com/1142958/111249168-2e047500-8603-11eb-8cea-c1c7f6d8dcae.png)

Rather than a single static; either type forwards or project ref for inbox?

**Comment by stephentoub** [comment]
The pattern was used to share some code between the networking event sources, but they all have their own unique names and guids and, in many cases, their own unique events.  These are also on the path to being removed entirely.  I don't see us investing in making them better.
https://github.com/dotnet/runtime/issues/38754

**Comment by benaadams** [comment]
That would also solve the issue 😉

**Comment by benaadams** [comment]
That would also solve the issue 😉 Are 13 unique `NetEventSource` currently from a rough count

**Comment by stephentoub** [comment]
> Are 13 unique NetEventSource currently from a rough count

FWIW, the fact that they're all named NetEventSource is misleading, though.  Each ends up including its own partial class that adds stuff, including the unique name and guid, e.g.
https://github.com/dotnet/runtime/blob/ec5d2eeade1ba4f203b2166c399056e124b4cfb8/src/libraries/System.Net.Http/src/System/Net/Http/NetEventSource.Http.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetEventSource.Sockets.cs

**Comment by stephentoub** [comment]
Let's close this as a dup of https://github.com/dotnet/runtime/issues/38754, unless there's something unique to this.

Thanks.

**Comment by benaadams** [comment]
Sure
