### ISSUE TITLE
Add `Empty` property to `BinaryData`

### ISSUE THREAD

**Issue by ellismg** [dotnet/runtime#49670]
## Background and Motivation

It would be nice if there was a singleton `Empty` property for `BinaryData`, which wraps an empty array. Without this, everyone who wants to return `BinaryData` needs to create the own static copy of an empty binary data, if they want to share this instance instead of allocating a new empty binary data each time.

## Proposed API

Please provide the specific public API signature diff that you are proposing. For example:
```diff
namespace System
{
    public class BinaryData {
+        public static BinaryData Empty { get; }
     }
} 
```

### Before

```C#
private static readonly s_EmptyBinaryData = new BinaryData(Array.Empty<byte>());

public BinaryData SomeMethodThatReturnsData() {
    if ( /* some check that sees if there's any data to return */) {
        return s_EmptyBinaryData;
    }
}
```

(or, even worse, since we allocate each time!)

```C#
public BinaryData SomeMethodThatReturnsData() {
    if ( /* some check that sees if there's any data to return */) {
        return new BinaryData(Array.Empty<byte>());
    }
}
```

### After

```C#
public BinaryData SomeMethodThatReturnsData() {
    if ( /* some check that sees if there's any data to return */) {
        return BinaryData.Empty;
    }
}
```

## Alternative Designs

We did not consider any alternate designs over a static get only property named `Empty`.

## Risks

None Identified.

**Comment by GrabYourPitchforks** [comment]
Fast-tracking this for review since it's from a partner team.

**Comment by GrabYourPitchforks** [comment]
It'd be nice to have an analyzer which detects `new T[0]`, `new BinaryData(new T[0])`, and similar and can rewrite them all to use the singleton empty APIs.

**Comment by terrajobst** [comment]
We already have an analyzer for the first item (https://github.com/dotnet/runtime/issues/43165#issuecomment-706222484). Would probably be easy to spot the second as well.

**Comment by terrajobst** [comment]
Also marked as blocking so it goes to the front of the queue

**Comment by Tornhoof** [comment]
May I suggest, if you change the type, to add a bit of documentation to: https://docs.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-5.0 or link https://docs.microsoft.com/en-us/dotnet/api/overview/azure/system.memory.data-readme?

I actually googled for BinaryData, as I was not aware of the type and the second link is hard to find (it shows up for system.memory.data, but not for binarydata), the second link is part of azure for developers for some reason.

**Comment by terrajobst** [comment]
* Looks good as proposed
* We can the analyzer/fixer suggestion from the existing analyzer but it should a get a new ID

```c#
namespace System
{
    public class BinaryData
    {
        public static BinaryData Empty { get; }
    }
}
```

**Comment by ellismg** [comment]
@terrajobst I assume it would be helpful to the team if I dusted off my fork and submitted a PR, since this is now approved?

**Comment by GrabYourPitchforks** [comment]
@ellismg have at it!
