### ISSUE TITLE
tutorial program gives no output

### ISSUE THREAD

**Issue by paolini** [dotnet/runtime#49687]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: linux

I have followed the tutorial as shown below. When executing `dotnet run` no output is given (not the expected "Hello World" nor any error). Only a 139 exit code.

```
[13:06:58]:~
> dotnet new console -o myApp
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on myApp/myApp.csproj...
  Determining projects to restore...
  Restored /home/emanuele/myApp/myApp.csproj (in 77 ms).
Restore succeeded.

[13:07:16]:~
> cd myApp
[13:07:33]:~/myApp
> dotnet run
[13:08:03]:~/myApp
> dotnet --version
5.0.200
[13:08:13]:~/myApp
> uname -a
Linux emanuele-XPS 5.4.0-66-generic dotnet/core#74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[13:10:59]:~/myApp
> which dotnet
/snap/bin/dotnet
[13:18:37]:~/myApp
> dotnet run
[13:18:46]:~/myApp
> echo $?
139
[15:37:14]:~/myApp
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

```

**Comment by DavidKarlas** [comment]
Moved to runtime since 139 indicates runtime SIGSEGV.

**Comment by vitek-karas** [comment]
Can you try running the app directly? Should be something like `./bin/Debug/net5.0/myApp`

If it fails the same way please try:
* `export COREHOST_TRACE=1`
* `export COREHOST_TRACEFILE=host.txt`
* run the app directly

This should produce `host.txt` in the current directory. Take a look near the end the file, you should see something like:
```console
CoreCLR path = ...
Loaded library from ... coreclr.so
..
Execute managed assembly exit code: ...
```

If you don't see this, it would be interesting to see the end of that file.

Note: the host.txt may contain information like environment variables, local paths, user name and so on - please make sure you're OK sharing it.

**Comment by paolini** [comment]
the file host.txt is not created:
```
[13:38:54]emanuele@emanuele-XPS:~/myApp
> export COREHOST_TRACE=1
[13:39:27]emanuele@emanuele-XPS:~/myApp
> export COREHOST_TRACEFILE=host.txt
[13:39:31]emanuele@emanuele-XPS:~/myApp
> ./bin/Debug/net5.0/myApp 
Segmentation fault (core dumped)
[13:39:34]emanuele@emanuele-XPS:~/myApp
> tail host.txt
tail: cannot open 'host.txt' for reading: No such file or directory
[13:39:41]emanuele@emanuele-XPS:~/myApp
> find . -name host.txt
[13:39:45]emanuele@emanuele-XPS:~/myApp
> find .
.
./obj
./obj/Debug
./obj/Debug/net5.0
./obj/Debug/net5.0/apphost
./obj/Debug/net5.0/myApp.csproj.CoreCompileInputs.cache
./obj/Debug/net5.0/myApp.csprojAssemblyReference.cache
./obj/Debug/net5.0/ref
./obj/Debug/net5.0/ref/myApp.dll
./obj/Debug/net5.0/.NETCoreApp,Version=v5.0.AssemblyAttributes.cs
./obj/Debug/net5.0/myApp.GeneratedMSBuildEditorConfig.editorconfig
./obj/Debug/net5.0/myApp.genruntimeconfig.cache
./obj/Debug/net5.0/myApp.AssemblyInfoInputs.cache
./obj/Debug/net5.0/myApp.csproj.FileListAbsolute.txt
./obj/Debug/net5.0/myApp.dll
./obj/Debug/net5.0/myApp.pdb
./obj/Debug/net5.0/myApp.assets.cache
./obj/Debug/net5.0/myApp.AssemblyInfo.cs
./obj/myApp.csproj.nuget.g.props
./obj/project.nuget.cache
./obj/myApp.csproj.nuget.g.targets
./obj/myApp.csproj.nuget.dgspec.json
./obj/project.assets.json
./Program.cs
./myApp.csproj
./bin
./bin/Debug
./bin/Debug/net5.0
./bin/Debug/net5.0/myApp.runtimeconfig.json
./bin/Debug/net5.0/myApp.deps.json
./bin/Debug/net5.0/myApp.runtimeconfig.dev.json
./bin/Debug/net5.0/myApp
./bin/Debug/net5.0/ref
./bin/Debug/net5.0/ref/myApp.dll
./bin/Debug/net5.0/myApp.dll
./bin/Debug/net5.0/myApp.pdb
[13:39:51]emanuele@emanuele-XPS:~/myApp
> set | grep COREHOST
COREHOST_TRACE=1
COREHOST_TRACEFILE=host.txt

```

**Comment by vitek-karas** [comment]
Hmm... can you try running:
`dotnet ./bin/Debug/net5.0/myApp.dll`

And one last thing (out of desperation) - can you try creating a folder and trying the whole process on a new application?

Would it be possible to share the dump? If you're OK with sharing it, can you please send it to vitek.karas at microsoft.com?

**Comment by paolini** [comment]
This is working:

```
[18:16:59]emanuele@emanuele-XPS:~/myApp
> dotnet ./bin/Debug/net5.0/myApp.dll
Hello World!

```

**Comment by ForNeVeR** [comment]
I was able to reproduce the same with .NET 5 SDK installed from Snap (according to [the docs](https://docs.microsoft.com/en-us/dotnet/core/install/linux-snap) – notably, .NET Core 3.1 SDK was by default there, so I had to install .NET 5 SDK via terminal).

Hello World program simply gives no output when started by `dotnet run`, but works if I start it via `dotnet ./bin/Debug/net5.0/myproj.dll`.

Notably, .NET 3.1 had another critical problem when installed from Snap, which has a similar workaround: #3792.

**Comment by ForNeVeR** [comment]
After reading https://github.com/dotnet/runtime/issues/3775#issuecomment-534263315, I was able to fix the issue locally.

I was starting a Hello World program from a directory `/tmp/myproj2`:
```
$ cd /tmp
$ dotnet new console -o myproj2
$ cd myproj2
$ dotnet run
<no output>
$
```

If I start it from a directory `/tmp/1/2/3/4/myproj2`, **then it works**!

**Comment by agocke** [comment]
Dup of https://github.com/dotnet/runtime/issues/49687
