### ISSUE TITLE
Upgrade to brotli version 1.0.9

### ISSUE THREAD

**Issue by deokershesh** [dotnet/runtime#49705]
Can I follow issue #35172 to upgrade brotli version to 1.0.9? I mean, make relevant changes what's done in #35172 for v1.0.7 to upgrade to v1.0.9?

**Comment by GrabYourPitchforks** [comment]
@deokershesh Issue 35172 appears unrelated to Brotli. Can you clarify your question?

**Comment by deokershesh** [comment]
There is need to upgrade our .NET Core Provider to Brotli version 1.0.8 or
later, which has some security fixes.

**Comment by deokershesh** [comment]
https://github.com/dotnet/corefx/pull/35172

Update brotli to v1.0.7

**Comment by deokershesh** [comment]
Any tips, suggestions?
