### ISSUE TITLE
Core-Setup builds do not work on dnceng internal instance

### ISSUE THREAD

**Issue by MattGal** [dotnet/runtime#49719]
Created on behalf of @ViktorHofer .  @safern  FYI; we may not want this to even work, but since Viktor brought it to me and it was a quick fix 
https://github.com/dotnet/core-setup/pull/9135

### Description

This seen in builds: https://dnceng.visualstudio.com/internal/_build/results?buildId=1041725&view=results (has never worked)

If this is not desirable, we should probably stop building this on every push of every branch (this is how the pipeline is currently configured)

**Comment by ViktorHofer** [comment]
> If this is not desirable, we should probably stop building this on every push of every branch

Thanks for the guidance. Just disabled the internal pipeline for 2.1 branches.
