### ISSUE TITLE
dotnet 6.0.0-preview.2.21154.6 on Apple Silicon M1 libhostfxr.dylib failed

### ISSUE THREAD

**Issue by matthewbluezyoncom** [dotnet/runtime#49712]
dotnet 6.0.0-preview.2.21154.6 seems to be broken.  Even a simple `dotnet --info` results in the following error

```
Failed to load Q, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

**Comment by vitek-karas** [comment]
Is this on Apple M1 hardware? Did you install multiple versions of the .NET?

**Comment by matthewbluezyoncom** [comment]
> Is this on Apple M1 hardware? Did you install multiple versions of the .NET?

Yes its on Apple M1 mbp.

Yes I have existing dotnet SDKs for v5 , v3 and v2

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.2
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /Users/matthew/temp/dotnet-temp/sdk/6.0.100-preview.2.21155.3/

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  2.1.300 [/Users/matthew/temp/dotnet-temp/sdk]
  2.1.301 [/Users/matthew/temp/dotnet-temp/sdk]
  2.2.104 [/Users/matthew/temp/dotnet-temp/sdk]
  2.2.106 [/Users/matthew/temp/dotnet-temp/sdk]
  3.1.200 [/Users/matthew/temp/dotnet-temp/sdk]
  3.1.402 [/Users/matthew/temp/dotnet-temp/sdk]
  3.1.407 [/Users/matthew/temp/dotnet-temp/sdk]
  5.0.102 [/Users/matthew/temp/dotnet-temp/sdk]
  5.0.201 [/Users/matthew/temp/dotnet-temp/sdk]
  6.0.100-preview.2.21155.3 [/Users/matthew/temp/dotnet-temp/sdk]
```

**Comment by vitek-karas** [comment]
And just out of curiosity - you installed 6 and after that one of the older ones, right?

Currently the 6 arm64 previews don't work with any other version on the machine. This is a known issue which we're actively working on.

@sdmaclea

**Comment by matthewbluezyoncom** [comment]
> And just out of curiosity - you installed 6 and after that one of the older ones, right?
> 
> Currently the 6 arm64 previews don't work with any other version on the machine. This is a known issue which we're actively working on.
> 
> @sdmaclea

No, I installed dotnet 6-prev-2 on top of the other SDKs as they were already on my M1 mbp

**Comment by vitek-karas** [comment]
Interesting - in that case I would expect slightly different error, but since this is just plain broken right now... it doesn't matter much.

**Comment by matthewbluezyoncom** [comment]
I have managed to get things working by removing all the older SDKs and reinstalling 6 prev-2 so it is the only SDK.

**Comment by vitek-karas** [comment]
Yes - that should work
