### ISSUE TITLE
Question: XHarness not getting updated

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#49714]
The last XHarness update was on Mar 4. Have the updates been paused for some reason?
/cc @premun

**Comment by premun** [comment]
I only lowered the frequency from EveryBuild to EveryDay for the XHarness subscription some time ago.

@radical there seems to be some problem: https://github.com/dotnet/runtime/pull/49540

**Comment by premun** [comment]
XHarness got bumped here successfully: #49745
