### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Private.CoreLib

### ISSUE THREAD

**Issue by AnRoya** [dotnet/runtime#49744]
I'm working with VS 2019, version 16.9.1 using .NET framework.
I ran my code today after it works fine yesterday, but today I received this exception:

    System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Private.CoreLib, 
    Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. 
    The system cannot find the file specified.'
It occurs when I'm creating a new class(that I wrote) 

I tried these solutions:

 1. Add System.Private.CoreLib.dll as a reference but it didn't help(I guess it's for .NET core)
 2. Change to an older version of my .NET framework (right now is 4.72.2) but it didn't help as well.
 3. This [link][1], but it's a different case.

Any help will be appreciated

Thank

  [1]: https://stackoverflow.com/questions/50010855/could-not-load-file-or-assembly-system-private-corelib

**Comment by vitek-karas** [comment]
Just to get this right: The app is targeting .NET Framework (4.7 or similar)?

Do you have references to NuGets which are for .NET Core only? (I would expect the build to fail with that, but maybe there's a whole somewhere).

Can you post the callstack of the failure?

**Comment by AnRoya** [comment]
> Just to get this right: The app is targeting .NET Framework (4.7 or similar)?
> 
> Do you have references to NuGets which are for .NET Core only? (I would expect the build to fail with that, but maybe there's a whole somewhere).
> 
> Can you post the callstack of the failure?

Yes, it's .NET Framework 4.7
I have no idea if I have a reference to NuGets which are .NET core. I do add some dll's from another project but that's it.

This is the call stack(it's the beginning of my program):
>	MT_SCR_Tester.exe!MT_SCR_Tester.MainWindow.MainWindow() Line 31	C#
 	MT_SCR_Tester.exe!MT_SCR_Tester.Program.Main() Line 19	C#


Thanks

**Comment by vitek-karas** [comment]
I honestly don't know what's going on... 

You can try to enable fusion logging - it might have more info about who asked for the assembly. Good guide is for example here: https://www.hanselman.com/blog/back-to-basics-using-fusion-log-viewer-to-debug-obscure-loader-errors

Can you try to create a repro project which you can share?

**Comment by AnRoya** [comment]
I can't share it with you because it contains some dll's which are not free to use,
I will check this fusion logging,

Thanks

**Comment by vitek-karas** [comment]
> I can't share it with you because it contains some dll's which are not free to use,

I understand, but maybe it would be possible to create a different project without those dlls and it still reproes the problem.

**Comment by AnRoya** [comment]
Ok, I will try to do it.
You can download it from my drive: [https://drive.google.com/file/d/1PS9ny3WBroeyPxrAeNQn1OgS0TnHRwuG/view?usp=sharing](url)

In testProject folder there is a folder called "MT_SCR_Tester" this is the project. there is a form called mainWindow which connects to a class that I wrote called MTSCR. In this class, I used external dll that I use it for the dto variable and I think that this dll is the problem

Thanks again for all your help

**Comment by AnRoya** [comment]
> Just to get this right: The app is targeting .NET Framework (4.7 or similar)?
> 
> Do you have references to NuGets which are for .NET Core only? (I would expect the build to fail with that, but maybe there's a whole somewhere).
> 
> Can you post the callstack of the failure?

I just saw it's .NET Core and these are the dependencies:
![image](https://user-images.githubusercontent.com/80811432/111463950-d8c28380-8728-11eb-9409-005ccbcec7e4.png)

**Comment by vitek-karas** [comment]
I see the `MPPGv4.Dtos` is a .NET Core assembly which has indirect dependency to `System.Private.CoreLib`.
Using .NET Core assemblies in .NET Framework app will simply not work - and I'm not aware of a way to make it work.
It's possible to do it the other way round - that is .NET Core app loading .NET Framework assembly, but it's not generally supported. It might work (and in lot of cases it does), but it also might not work.

**Comment by AnRoya** [comment]
OK, I will find another way to solve it.
Thank you very much
