### ISSUE TITLE
System.SizedReference is full of suspicious magic

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/runtime#4974]
`System.SizedReference` does something shady. Look at `Target` getter:

```
IntPtr temp = _handle; 
if (temp == IntPtr.Zero)
{
     return null;
}
Object o = GetTargetOfSizedRef(temp);
return (_handle == IntPtr.Zero) ? null : o;
```

Why does the last line read `_handle` again? If this is to prevent a race should some other thread change `_handle` then this is useless because that other thread could do the same between the second read and computing the return value. If this is to keep the object from being collected then `GC.KeepAlive(this)` should be used instead.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/9153.
