### ISSUE TITLE
SocketsHttpHandler.IsSupported returns true on unsupported platforms

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#49751]
`SocketsHttpHandler.IsSupported` [property](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SocketsHttpHandler.cs#L45) always returns true even on a platform where it's not supported (e.g browser).

**Comment by stephentoub** [comment]
When this is being fixed,  we should also fix the platform compat annotations. Code shouldn't get a warning accessing IsSupported itself on any platform,  but will today as the whole class is annotated.

**Comment by stephentoub** [comment]
Marek, is your comment based on testing or code inspection? I see this for browser:
https://github.com/dotnet/runtime/blob/ac5c33defa6a9983e85ce8bf0be352cb09f5b8eb/src/libraries/System.Net.Http/src/System/Net/Http/BrowserHttpHandler/SocketsHttpHandler.cs#L19

**Comment by marek-safar** [comment]
Yeah, my bad I checked only one implementation. I'm closing this one and open a new one about the annotation only.
