### ISSUE TITLE
SocketsHttpHandler.IsSupported is annotated as unsupported on browser

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#49755]
as it's a static [property](https://github.com/dotnet/runtime/blob/0b7bcf0f9c74a1833405d55a4f649e23d124d323/src/libraries/System.Net.Http/ref/System.Net.Http.cs#L355) that is intended to be used for probing it should not be annotated as [unsupported](https://github.com/dotnet/runtime/blob/0b7bcf0f9c74a1833405d55a4f649e23d124d323/src/libraries/System.Net.Http/ref/System.Net.Http.cs#L351).

**Comment by karelz** [comment]
@buyaa-n @jeffhandley would it make sense for analyzers to allow exclusion of `IsSupported` property?
The only alternative is to put the attribute on each member except the `IsSupported` -- which is kind of ugly.

**Comment by buyaa-n** [comment]
> The only alternative is to put the attribute on each member except the IsSupported -- which is kind of ugly.

Right, maybe we leave the class annotation and add the new `UnsupportedOSPlatformGuard("browser")` attribute for this property which then can be used as a guard plus I will make sure it would not warn for `UnsupportedOSPlatform("browser")` attribute of containing type

**Comment by karelz** [comment]
@buyaa-n did you manage to add the new attribute? Or is it as least still in plan for 6.0?

**Comment by karelz** [comment]
@buyaa-n ping? cc @jeffhandley

**Comment by buyaa-n** [comment]
> @buyaa-n did you manage to add the new attribute? Or is it as least still in plan for 6.0?

Yes the attribute is added and this is fixed, closing
https://github.com/dotnet/runtime/blob/4156116824c18be1cf1d29a42278b5586d16ffcf/src/libraries/System.Net.Http/ref/System.Net.Http.cs#L362-L363
