### ISSUE TITLE
Remove XmlIgnoreMemberAttribute references

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49761]
We have the following code in System.Private.Xml:

https://github.com/dotnet/runtime/blob/eac699cb4da48b0b5d46baa7b0f1d8154e5875d7/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlAttributes.cs#L75-L89

This is referencing a legacy .NET Framework internal attribute in mscorlib that no longer exists in `System.Private.CoreLib`:

https://referencesource.microsoft.com/#mscorlib/system/xmlignorememberattribute.cs,33ba544d60bd65ba,references

From my understanding of the .NET Framework code, this attribute existed so we could mark certain members of `AppDomainSetup` as "ignore" when serializing to XML.

However, `AppDomainSetup` is severally gutted on .NET Core and no longer contains those members. As such, the `System.XmlIgnoreMemberAttribute` was removed from `System.Private.CoreLib` (https://github.com/dotnet/coreclr/pull/10837), but this code remains in System.Private.Xml.

We should just remove this property all together.

cc @krwq @agocke

**Comment by krwq** [comment]
cc: @StephenMolloy @HongGit

**Comment by eerhardt** [comment]
I believe this was resolved by @agocke in #49682. Closing.
