### ISSUE TITLE
PGO VS redist packages are conflicting with non-PGO packages

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#49776]
The build produces VS.Redist packages and the PGO CI run doesn't give them special names, so when a PGO leg and non-PGO leg run in the official build, whichever package gets uploaded is a race.

We have no need for PGO VS redist packages, so we should just disable those packages from being created in the PGO run.

**Comment by jkoritzinsky** [comment]
Marking this as blocking since it's blocking WPF intake of dotnet/runtime.
