### ISSUE TITLE
Do forceCastToUInt32 and forceCastToFloat still serve a purpose?

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#49787]
The two functions in `compiler.hpp` are used sparsely (~20 uses between the two of them) throughout the Jit for performing the specified conversions. The comments on them, however, indicate they may be working around problems in compilers from over 15 years ago:
```C++
// Enforce float narrowing for buggy compilers (notably preWhidbey VC)
inline float forceCastToFloat(double d)
{
    Volatile<float> f = (float)d;
    return f;
}

// Enforce UInt32 narrowing for buggy compilers (notably Whidbey Beta 2 LKG)
inline UINT32 forceCastToUInt32(double d)
{
    Volatile<UINT32> u = (UINT32)d;
    return u;
}
```
I am thus wondering if those could be safely deleted and the normal C++ casts used instead.

Note that we may still want some casting indirection layer, for unified behavior across platforms. It is unclear to me if deleting these functions will make it harder to introduce this layer.

**Comment by EgorBo** [comment]
I wanted recently to add an edge case to one of those for MSVC 32 bit

![image](https://user-images.githubusercontent.com/523221/111619741-fa8a3c00-87f6-11eb-8623-c7c661b8e2a5.png)

**Comment by SingleAccretion** [comment]
Yes...

After thinking a bit more about this, this issue is just a subset of (and is blocked by) #47478. Closing as not actionable.
