### ISSUE TITLE
[wasm] Enable wasm relinking for Trimming tests running in `dotnet-linker-tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#49790]
We do wasm relinking in some cases by default now (eg. in Release config). This breaks in case of Trimming tests run under `dotnet-linker-tests`, because it cannot find `mono-aot-cross`. It needs this to essentially invoke:

`"$(MonoAotCrossCompilerPath)" --print-icall-table > "$(_WasmIntermediateOutputPath)runtime-icall-table.h"`

Wasm relinking has been disabled in this case, for now (https://github.com/dotnet/runtime/pull/49774). But this needs to be fixed.

**Comment by ilonatommy** [comment]
Have we made any progress here @radekdoulik?

**Comment by lewing** [comment]
Considering this resolved
