### ISSUE TITLE
Can not build the newest runtime library

### ISSUE THREAD

**Issue by BenLampson** [dotnet/runtime#49794]
![image](https://user-images.githubusercontent.com/15414750/111567345-c2c0cb80-87d9-11eb-8478-6098e9fb5ce1.png)

**Comment by huoyaoyuan** [comment]
It looks like a network issue that the install script can't install the preview SDK.

**Comment by BenLampson** [comment]
> It looks like a network issue that the install script can't install the preview SDK.

![image](https://user-images.githubusercontent.com/15414750/111602272-26fd8280-880e-11eb-8dfe-abcd34c9d5bb.png)
I already install .net 6, but not fix.

**Comment by huoyaoyuan** [comment]
The build script will download the exact version in tools. Your version mismatches.

**Comment by BenLampson** [comment]
> The build script will download the exact version in tools. Your version mismatches.

oops~ THX!
