### ISSUE TITLE
Unify File.Replace Unix and Windows exception throwing behavior

### ISSUE THREAD

**Issue by mikernet** [dotnet/runtime#49796]
### Description

```cs
using (File.Create("test.txt")) {}
Directory.CreateDirectory("test");
			
// Correct - throws IOExeption with message "Is a directory"
File.Replace("test.txt", "test", null);

// Incorrect = throws IOExeption with message "Not a directory"
File.Replace("test", "test.txt", null);
```

### Configuration

.NET 5 on Linux.

**Comment by tmds** [comment]
These errors come from [rename](https://man7.org/linux/man-pages/man2/rename.2.html).

```
// Incorrect = throws IOExeption with message "Not a directory"
File.Replace("test", "test.txt", null);
```

leads to

```
       ENOTDIR
              A component used as a directory in oldpath or newpath is
              not, in fact, a directory.  Or, oldpath is a directory,
              and newpath exists but is not a directory.
```

@mikernet what would be a more appropriate message?

**Comment by mikernet** [comment]
The issue is that it is a directory, not that it's not a directory, so the same error message should be showing up for both those cases, no?

**Comment by mikernet** [comment]
Oh wait...this is a bit of an odd inconsistency, but `File.Replace` on unix works on directories, but does not in windows.

**Comment by danmoseley** [comment]
Incidentally in pulling up this code I noticed we use the wrong path in this error message
https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs#L126
I'll see if I can fix that.

**Comment by mikernet** [comment]
Just edited my message above right after you posted yours with some more details.

**Comment by mikernet** [comment]
TBH the `UnauthorizedAccessException` that is thrown on windows with a very unhelpful error message when you try to do a file op on a dir path doesn't make any sense. I convert those into FileNotFound exceptions in my lib.

**Comment by danmoseley** [comment]
As an experiment I looked at the IOExceptions thrown and caught in many of the S.IO.FileSystem tests. Many of them do not contain the file paths. In some cases that can be fixed fairly easily. In some other cases, it's difficult to know which path the problem applied to (eg was access denied to source or destination).
This doesn't directly address the issue reported here, just noted.

**Comment by mikernet** [comment]
This method also has inconsistent behavior between Windows and Unix - on Windows, if the source and destination file are the same it throws an exception. On Unix it works fine and still copies the contents of the file to the backup file name.

**Comment by tmds** [comment]
Summarizing the inconsistencies reported by @mikernet:

- The method should fail when the source is a directory.
- The method should fail when source and destination are the same file.

These cases are described in the docs to throw `UnauthorizedAccessException` and `IOException` respectively.

**Comment by carlossanlop** [comment]
I renamed the issue to reflect the same objective as in the provided PR by @tmds
