### ISSUE TITLE
To strict "ref-to-escape" behaviour for `System.Runtime.CompilerServices.Unsafe.NullRef<T>()`

### ISSUE THREAD

**Issue by bernd5** [dotnet/runtime#49808]
## Background and Motivation

`System.Runtime.CompilerServices.Unsafe.NullRef<T>` allows developers to replace low-level, raw-pointer implementations to be replaced with simpler and safer "by ref" code.

The compiler / language tries to avoid typical bugs in the area of "by ref" variables and introduced therefore the "safe-to-escape" rules which are usually just fine.

The problem is now, that these rules apply to `System.Runtime.CompilerServices.Unsafe.NullRef<T>`, too. As a consequence a by null-ref initialized variable can't be ref assigned to a local variable, see: [spec - locals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.2/span-safety#locals).

See issue at [csharplang](https://github.com/dotnet/csharplang/discussions/4547).

To allow ref assigns to ref locals initialized with `NullRef<T>` I propose an API change that makes use of [method-invocation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.2/span-safety#method-invocation): 

> For each in parameter of the method, if there is a corresponding expression that is an lvalue, its ref-safe-to-escape, otherwise the nearest enclosing scope

## Proposed API

```diff
namespace System.Runtime.CompilerServices
{
    public static partial class Unsafe
    {
-    public static ref T NullRef<T>() { throw null; }
+    public static ref T NullRef<T>(in int paramForSafeToEscapeRules = 0) { throw null; }
    }
}
```

## Usage Examples
The usage would be not changed just extended to allow local ref assign.

## Alternative Designs
The safe-to escape rules could be extended so that they would look for an attribute to define the behaviour.

As a workaround users can implement their own "NullRef"-Function:
```CSharp
ref T GetNullRef<T>(in int dummy = default)  => ref System.Runtime.CompilerServices.Unsafe.NullRef<T>();
```

**Comment by bernd5** [comment]
To make the motivation more clear I add a small sample:

```CSharp
class NullRefSample {
	void SampleWithConditionalRef(int something){
		
		int a = 1;
		int b = 2;
		int c = 3;
		
		//very compilcated
		ref int local_to_adjust = ref (something == 1 ? ref a : ref (something == 2 ? ref b : ref c));
		
		local_to_adjust++;
		System.Console.WriteLine(local_to_adjust);
	}
	
	void SampleWithoutConditionalRef(int something){
		int a = 1;
		int b = 2;
		int c = 3;
		
		ref T NullRef<T>(in int d = default) => ref System.Runtime.CompilerServices.Unsafe.NullRef<T>();
		
		ref int local_to_adjust = ref NullRef<int>();//ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();	
		switch(something){
			case 1:
				local_to_adjust = ref a;
				break;
			case 2:
				local_to_adjust = ref b;
				break;
			case 3:
				local_to_adjust = ref c;
				break;
		}
		
		local_to_adjust++;
		System.Console.WriteLine(local_to_adjust);
	}
	
	
	/* DOES NOT WORK, BUT SHOULD
	
	void SampleWithoutConditionalRef(int something){
		int a = 1;
		int b = 2;
		int c = 3;
		
		ref int local_to_adjust =  ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();	
		switch(something){
			case 1:
				local_to_adjust = ref a;
				break;
			case 2:
				local_to_adjust = ref b;
				break;
			case 3:
				local_to_adjust = ref b;
				break;
		}
		
		local_to_adjust++;
		System.Console.WriteLine(local_to_adjust);
	}
	*/
}
```

**Comment by huoyaoyuan** [comment]
The language and compiler has no concept about what `NullRef` is. Changing the scope based on argument is neither possible nor practical.

For your sample, the better solution is to allow ref return for `switch` expression.

**Comment by bernd5** [comment]
Maybe the explanation is maybe not clear enough.

I want to write:
```CSharp
ref int i = ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();
int someData = 4711;
i = ref someData; //<--- Cannot ref-assign 'someData' to 'i' because 'someData' has a narrower escape scope than 'i'
```

With this "dummy in parameter" this error does not occur.

That means you can write today:
```CSharp
ref T GetNullRef<T>(in T dummy = default){
  return ref System.Runtime.CompilerServices.Unsafe.NullRef<T>();
}

ref int i = ref GetNullRef<int>();
int someData = 4711;
i = ref someData;
```

Maybe the safe to escape rules are in general to strict?
That the not used in parameter changes the code is weird :-) - but that is the way how it is defined today.

**Comment by benaadams** [comment]
> I want to write:
> 
> ```cs
> ref int i = ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();
> int someData = 4711;
> i = ref someData; //<--- Cannot ref-assign 'someData' to 'i' because 'someData' has a narrower escape scope than 'i'
> ```

That assignment would throw a `NullReferenceException` though?

**Comment by GrabYourPitchforks** [comment]
I really don't think we should be contorting the API shape to work around this edge case language restriction. There's a simple enough workaround:

```cs
int dummy = default;
ref int i = ref dummy;
i = ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();
```

Or (gives slightly better codegen):

```cs
int dummy = default;
ref int i = ref false ? ref dummy : ref System.Runtime.CompilerServices.Unsafe.NullRef<int>();
```
