### ISSUE TITLE
System.Text.Encoding.Default.GetString returns incomplete string

### ISSUE THREAD

**Issue by Mokashaa** [dotnet/runtime#49807]
### Description
I have a problem trying to get a string from a byte array using the System.Text.Encoding.Default.GetString() function . the problem is that the byte array contains some symbols as shown in the following picture 
![image](https://user-images.githubusercontent.com/36459281/111606199-a4f66500-87df-11eb-8475-e64c724be10f.png)
(this image contains part of the byte array after writing this byte array to a file)
so , the get string function returns a string that is not complete and only contains the part of the byte array before the appearance of this symbols 

I tried different encoding systems but the output still not complete .
Is there any possible solution for this problem so that the GetString Function returns the complete string corresponding to the given byte array ?
area-System.Text.Encoding

**Comment by Mokashaa** [comment]
@eiriktsarpalis @layomia

**Comment by filipnavara** [comment]
You are definitely mixing encodings. The data on the image look like UTF-16 decoded through single-byte encoding (and Encoding.Default is usually a single byte one or UTF-8).

**Comment by Mokashaa** [comment]
> You are definitely mixing encodings. The data on the image look like UTF-16 decoded through single-byte encoding (and Encoding.Default is usually a single byte one or UTF-8).

the byte array contains a lot of text that was encoded correctly like displayed below
![image](https://user-images.githubusercontent.com/36459281/111610333-e983ff80-87e3-11eb-8f97-564cb54a07db.png)
also as I said I tried different encoding systems including unicode but it didn't work

**Comment by eiriktsarpalis** [comment]
Hi @Mokashaa, could you share a minimal reproduction highlighting the issue?

**Comment by Mokashaa** [comment]
> Hi @Mokashaa, could you share a minimal reproduction highlighting the issue?

not sure this would help or not but the byte array I'm trying to get the string from is the output of parsing an rtf document ... so the complete byte array include rich text with this symbols in the middle so the getstring process terminates when dealing with this symbol 
![image](https://user-images.githubusercontent.com/36459281/111621122-45548580-87f0-11eb-8e80-d586f4f57726.png)
sorry but i'm not able share the original document

**Comment by jkotas** [comment]
>  the output of parsing an rtf document 

There is no one encoding that will just work for rtf documents. You need to create the right encoding based on what the rtf document says. https://en.wikipedia.org/wiki/Rich_Text_Format has some more details.

**Comment by Mokashaa** [comment]
> > the output of parsing an rtf document
> 
> There is no one encoding that will just work for rtf documents. You need to create the right encoding based on what the rtf document says. https://en.wikipedia.org/wiki/Rich_Text_Format has some more details.

I don't know whether the encoding is the problem or not but the byte array contain all the data required after parsing file including some NULL characters that makes the GetString don't complete it's functionality and the returned string is not complete and I think it must complete it's process till the end of the byte array not till finding a NULL

**Comment by tarekgh** [comment]
@Mokashaa you are addressing the parsing in wrong way. You cannot choose randomly any encoding and try to use for encoding such bytes. 

> I think it must complete it's process till the end of the byte array not till finding a NULL

although this is irrelevant to solving this problem as it wouldn't help anyway, but did you check the returned string length? the string could have nulls in the middle, but the length is greater than where the first null show up in the string.

**Comment by Mokashaa** [comment]
> @Mokashaa you are addressing the parsing in wrong way. You cannot choose randomly any encoding and try to use for encoding such bytes.

I agree with you but I don't have control on the parsing process and it's byte array output although I think it has mixed encoding

 

> although this is irrelevant to solving this problem as it wouldn't help anyway, but did you check the returned string length? the string could have nulls in the middle, but the length is greater than where the first null show up in the string.

I tried this and it worked . the string contains NULL characters  in the middle so it appears to be broken

**Comment by tarekgh** [comment]
> I tried this and it worked . the string contains NULL characters in the middle so it appears to be broken

Thanks for trying it. can we close this issue now as there is nothing need to be done from our side?

**Comment by tarekgh** [comment]
@Mokashaa I am closing the issue but feel free to send back any more questions you think we can help with. Thanks for your report!
