### ISSUE TITLE
CustomConstantAttribute doesn't work in Mono

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#49806]
See tests getting added in https://github.com/dotnet/runtime/pull/49767.

**Comment by SkiFoD** [comment]
I was curious what was wrong with Mono and I did some research.
I found that mono implementation doesn't have code trying to assign CustomConstantAttribute's value.

Mono: 
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeParameterInfo.cs#L125-L145
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeParameterInfo.cs#L194-L198

CoreClr:
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeParameterInfo.cs#L370-L382

**Comment by CoffeeFlux** [comment]
Looks like a straightforward fix; probably worth trying to get in if it doesn't prove too difficult.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by fanyang-mono** [comment]
Didn't have bandwidth to work on this in .NET7. Moving to milestone 8.0.0.
