### ISSUE TITLE
GitHub actions on MacOS failing since OPENSSL 1.0.2 removal

### ISSUE THREAD

**Issue by ycrumeyrolle** [dotnet/runtime#49827]
Related to https://github.com/actions/virtual-environments/issues/2089

I have an issue since the 14th December on my dotnet unit test workflow running on MacOS :
`The active test run was aborted. Reason: Test host process crashed : No usable version of libssl was found`
This occurs on netcoreapp3.1 with SDK 3.1.404.

`Current runner version: '2.275.1'
Operating System
  Mac OS X
  10.15.7
  19H15
Virtual Environment
  Environment: macos-10.15
  Version: 20201212.1`

**Comment by MartyIX** [comment]
@danmoseley Yann [wrote](https://github.com/dotnet/runtime/issues/49827#issuecomment-766415961) a very simple-looking project https://github.com/nohwnd/macOSTestIssue which shows the issue. Isn't it enough to debug the issue? I'm not sure you are aware of it, so I'm just making it clear.

I can try to print DYLD_PRINT_LIBRARIES later today. I'm not sure how to do that at the moment.

**Comment by danmoseley** [comment]
@MartyIX ah yes. Still, we often ask folks to help with the diagnostic steps, since that can help get to a resolution more quickly; it can take some time for an issue to get up to the top of an engineer's list to look at in more detail.

**Comment by MartyIX** [comment]
@danmoseley I have just did this: https://github.com/nohwnd/macOSTestIssue/runs/2141171721?check_suite_focus=true where I print `printenv`. I believe that with this information it's much better but it's very easy to add further debug operations (I have added a single commit in a few minutes so ...)

**Comment by danmoseley** [comment]
OK, thanks. I don't have expertise to go further so I'll leave this up to owns of this area now.

**Comment by bartonjs** [comment]
The "Display OpenSsl lib 2" variant is using the patch-specific path (1.1.1i) which is failing because the current version is 1.1.1j.  The first one worked, does everything pass if you get rid of the second version?

**Comment by MartyIX** [comment]
I can see "The active test run was aborted. Reason: Test host process crashed : No usable version of libssl was found" (https://github.com/nohwnd/macOSTestIssue/runs/2143008941?check_suite_focus=true) with commit https://github.com/nohwnd/macOSTestIssue/pull/3/commits/d6108995b4ef52d6ca001dd588634079693bcf71

**Comment by bartonjs** [comment]
To my understanding, things should be working.  But, I note that DYLD_FALLBACK_LIBRARY_PATH doesn't appear in the printenv dump, which seems like https://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1

I don't know if the run syntax allows for things like `DYLD_FALLBACK_LIBRARY_PATH=/usr/local/opt/openssl@1.1/lib dotnet test --no-build --verbosity normal` (or if that's subject to the same SIP problem); or if that type of invocation would work from a shell script.  (Anyone who uses macs on a regular basis is invited to chime in)

The "easiest" approach is whoever owns the machines behind that pool adding symlinks for the /usr/local/opt/openssl@1.1/lib/lib{ssl,crypto}.1.1.dylib files to /usr/local/lib, or something else already in the path.  But I have no idea who that is, or how hard it is to get them to make changes :smile:.

**Comment by vcsjones** [comment]
> adding symlinks for the 

In the mean time, this is something that can be done in the actions to unblock anyone running in to this. Here is an example of a setting up the symlinks prior to running actions.

https://github.com/vcsjones/dotnet-openssl-actions/commit/9ae6822da11e8038c07b5c6243f7334a9ceee07c 

And I was able to get an action run to run successfully.

https://github.com/vcsjones/dotnet-openssl-actions/actions/runs/690449698

**Comment by MartyIX** [comment]
Kevin's workaround works great for me. Thanks! 

Just for the sake of inspiration, this does the trick for me as I test on Ubuntu & macOS:

```csharp
name: .NET Core
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macOS-latest' ]

    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 10

    steps:
    - name: Setup OpenSSL (macOS)
      if: matrix.operatingSystem == 'macOS-latest'
      run: |
        ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/libssl.1.1.dylib
        ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/libcrypto.1.1.dylib
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
```

**Comment by ycrumeyrolle** [comment]
@vcsjones the symlinks is working! 👍  

@AlenaSviridenko @vcsjones @bartonjs  
Adding the symlink working fix, but I would expect a more integreted solution. 
Is it something that should be fixed in the dotnet SDK, or in the GitHub actions virtual environment? Or something that will not be fixed and should be the responsability of each user?

**Comment by bartonjs** [comment]
Given that the conversation has died down, and this is more about the GitHub Actions environment than .NET itself, I'm going to close the issue.

Hopefully all is quiet because things just work nicely in GitHub Actions.  If not, at least we have a workaround (thanks, @vcsjones!)
