### ISSUE TITLE
[wasm] Blazor+aot using workloads breaks with `TypeInitializationException`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#49829]
I tried this on a Mac:

1. Follow the steps in https://gist.github.com/pranavkm/1ca9eca9605ebc89161cb33e02e74e85 to setup workload packs
2. (cd bin/Debug/net6.0/publish/wwwroot; dotnet serve -p 8000)

JS console shows:
`ThreadPool Callback threw an unhandled exception of type System.TypeInitializationException`

@pranavkm is seeing this on Windows too.

**Comment by pranavkm** [comment]
FYI @danroth27

**Comment by lewing** [comment]
Verified Fixed!
