### ISSUE TITLE
shared memory temp folder

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#49822]
Shared memory files are placed under `/tmp`:

https://github.com/dotnet/runtime/blob/122c438e0987bf7bfd2a4a02368353d3774ff963/src/coreclr/pal/src/include/pal/palinternal.h#L623

Other usage of `/tmp` can be overridden by setting the `TMPDIR` envvar. This doesn't work for shared memory files. Can the envvar be taken into account here also? Or is this intentional?

**Comment by tmds** [comment]
> Other usage of /tmp can be overridden by setting the TMPDIR envvar. This doesn't work for shared memory files. Can the envvar be taken into account here also? Or is this intentional?

@janvorli you may know the answer to this.

I ran into this when trying to place all the temp files from .NET in a folder which I could remove.

**Comment by janvorli** [comment]
I can see that the usage of /tmp was added in https://github.com/dotnet/coreclr/pull/5030. @kouvel do you happen to remember if there was any reason for chosing a fixed path instead of getting the tmp folder path from the TMPDIR?

**Comment by kouvel** [comment]
The shared memory files are used for cross-process mutexes, which can have system-wide scope using the `Global\` prefix in the mutex name. Using `TMPDIR` would mean that two processes running with different `TMPDIR` would not be able to synchronize with one another using a global mutex. Other than that if the intention is to override the location for all processes on the system (not per process where those processes may need to synchronize with one another), then it could be made configurable, although in that case `/tmp` could also be aliased. It could be made configurable if necessary, though whether the configuration should be `TMPDIR` I'm not sure, thoughts?

**Comment by tmds** [comment]
@kouvel thanks for explaining. Can the non-`Global\` mutexes use `TMPDIR`?

The mutexes I encountered were created by `dotnet build` and I think they were non-global ones.

**Comment by kouvel** [comment]
Non-global mutexes have session scope, it would probably be unlikely that processes in one session would use a different `TMPDIR`, but possible. What is undesirable about using `/tmp` for shared memory files? Another option may be to expose a different config var if necessary, as `TMPDIR` may be used to configure the location for other temp files the app may produce, which may typically be for a different purpose than shared memory files that may be used for communication between processes. I thought that `dotnet build` also used a global mutex for the compile server, but I could be wrong.

**Comment by tmds** [comment]
When I run this step in a container:
```
RUN dotnet new console -o console && \
    dotnet publish console -o published &&\
    rm -rf console
```
The resulting image has these files in `/tmp`:
```
/tmp
|-- .dotnet
|   `-- shm
|       `-- session1
|           |-- 64b1f55464c0463c8ed8005891dd4192
|           `-- UuRnp1IqaCOXENVA6gDAjOmOHceFKkVv+u8De825vDM.server
|-- NuGetScratch
|   `-- lock
|       |-- b802791db6fc4b3395451c6cb15b3fe77050a94d
|       |-- d13fc424ae17637fc9df5ddefc8bcfaa248287e9
|       `-- effbb02e5017975996b2720d0dde89125b10edcc
|-- VBCSCompiler
|   `-- AnalyzerAssemblyLoader
|       `-- 64b1f55464c0463c8ed8005891dd4192
|           |-- 1
|           |   `-- Microsoft.CodeAnalysis.CSharp.NetAnalyzers.dll
|           `-- 2
|               |-- Microsoft.CodeAnalysis.NetAnalyzers.dll
|               |-- cs
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- de
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- es
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- fr
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- it
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- ja
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- ko
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- pl
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- pt-BR
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- ru
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- tr
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               |-- zh-Hans
|               |   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
|               `-- zh-Hant
|                   `-- Microsoft.CodeAnalysis.NetAnalyzers.resources.dll
```
I was trying to move these file to a common directory using `TMPDIR` when I noticed `/tmp/.dotnet/shm` did not move and created this issue to understand why that is so.

I'm fine separately removing this folder completely.
