### ISSUE TITLE
Assigning a ROM<byte> field to 'default' produces optimal codegen over assigning it to ROM<byte>.Empty

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#49834]
[From SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuGAHKAJYA3bBhgMASjGwATAPIA7ADYBPALIx80FQB4AQirEA+BgH0oEfAG4uPW93pMUDNQAoAlB3s9u5ywwBeBhkYADNsAFclDBtqHwBfb29HYmcAOQ8vOJ8eP3xAyWl5ZXVNbX1DGCMAOgBRfF4MFViEpOyeFOc5TM52nMLZRVUNLShdYEqTC3ygkPComO8fPILplp5E6nigA=)

```cs
using System;
public class C {
    private ReadOnlyMemory<Byte> _rom;
    
    public void M() {
        _rom = default;
    }
    
    public void N() {
        _rom = ReadOnlyMemory<Byte>.Empty;
    }
    
     public void O() {
         ReadOnlyMemory<byte> rom = default;
        _rom = rom;
    }
}
```

```asm
; Core CLR v5.0.321.7212 on amd64

C.M()
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu [rcx+8], xmm0
    L000c: ret

C.N()
    L0000: add rcx, 8
    L0004: xor eax, eax
    L0006: mov [rcx], rax
    L0009: mov [rcx+8], eax
    L000c: mov [rcx+0xc], eax
    L000f: ret

C.O()
    L0000: add rcx, 8
    L0004: xor eax, eax
    L0006: mov [rcx], rax
    L0009: mov [rcx+8], eax
    L000c: mov [rcx+0xc], eax
    L000f: ret
```

The assignment of _default(ROM\<byte\>)_ directly to the backing field results in a single SIMD write to 16 bytes of memory. However, accessing `ROM<byte>.Default` (or even using _default(T)_ but bouncing through a local) results in 3 separate writes corresponding to the 3 backing fields of the ROM\<byte\>. Ideally the JIT could recognize that _default(T)_ is being flowed across these paths and optimize the backing write where possible.

category:cq
theme:codegen
skill-level:intermediate
cost:medium
impact:small

**Comment by AndyAyersMS** [comment]
@sandreenko seems like something you could investigate?
cc @dotnet/jit-contrib

**Comment by benaadams** [comment]
Same for ReadOnlySpan [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHuGAHKAJYA3bBhgMASjGwATAPIA7ADYBPALIx80FQB4AQirEA+BgH0oEfAG4uPW93pMUDNQAoAlB3s9u5ywwBeBhkYADNsAFclDBtqHwBfb29HYmcAOQ8vOJ8eP3xAyWl5ZXVNbX1DGCMAOgBRfF4MFViEpOyeFOc5TM52nMLZRVUNLShdYEqTC3ygkPComO8fPILplp5E6k3HWFCGXAwoCLAMBgBlLJ9+YVFxKUGSs95sBQrjMzW2n06XHqXc6YFOaRaLrbibHzJRipBgZTy9fq+QFBe7FVRPF5vKp1BpNMEMCF2PpMaFdP7EnyooYqDGvCbvZHBMIgxYUpH+IKfPqbeJAA)
```csharp
public ref struct S {
    private ReadOnlySpan<Byte> _rom;
    
    public void M() {
        _rom = default;
    }
    
    public void N() {
        _rom = ReadOnlySpan<Byte>.Empty;
    }
    
     public void O() {
         ReadOnlySpan<byte> rom = default;
        _rom = rom;
    }
}
```
```asm
S.M()
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu [rcx], xmm0
    L000b: ret

S.N()
    L0000: xor eax, eax
    L0002: mov [rcx], rax
    L0005: xor eax, eax
    L0007: mov [rcx+8], eax
    L000a: ret

S.O()
    L0000: xor eax, eax
    L0002: mov [rcx], rax
    L0005: xor eax, eax
    L0007: mov [rcx+8], eax
    L000a: ret

```

**Comment by GrabYourPitchforks** [comment]
@benaadams Interestingly, in the last two methods in your sample the JIT doesn't re-use the existing zero-value register. It zeroes the register again before the second write.

**Comment by benaadams** [comment]
Different sized variables? Even though it does use the same register...

**Comment by erozenfeld** [comment]
> @benaadams Interestingly, in the last two methods in your sample the JIT doesn't re-use the existing zero-value register. It zeroes the register again before the second write.

This may be related to #37079.

**Comment by JulieLeeMSFT** [comment]
It is unlikely to happen in .NET 6. Moving to future.

**Comment by EgorBo** [comment]
Current codegen:
```asm
; Method C:M():this (FullOpts)
       xor      eax, eax
       mov      qword ptr [rcx+0x08], rax
       mov      qword ptr [rcx+0x10], rax
       ret      
; Total bytes of code: 11

; Method C:N():this (FullOpts)
       xor      eax, eax
       mov      qword ptr [rcx+0x08], rax
       mov      qword ptr [rcx+0x10], rax
       ret      
; Total bytes of code: 11

; Method C:O():this (FullOpts)
       xor      eax, eax
       mov      qword ptr [rcx+0x08], rax
       mov      qword ptr [rcx+0x10], rax
       ret      
; Total bytes of code: 11
```
