### ISSUE TITLE
Failure in System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildInvalidSignatureTwice

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#49836]
Failure seen on https://github.com/dotnet/runtime/pull/48369

https://dev.azure.com/dnceng/public/_build/results?buildId=1045010&view=ms.vss-test-web.build-test-results-tab&runId=32336274&resultId=175667&paneView=debug

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/48851
