### ISSUE TITLE
TimeZoneInfo.ConvertTimeFromUTC returns incorrect value

### ISSUE THREAD

**Issue by hciupinski** [dotnet/runtime#49869]
**Description**
I've got DateTime object equal **01/01/0001 00:00:00** and I would like to convert it to 'Asia/Baghdad' TimeZone. (UTC+3:00)
I would expect it to be **01/01/0001 03:00:00** but the result is **01/01/0001 02:58:00**.

**Configuration**
I'm working on MacOS11.2 and Visual Studio for Mac. As I've checked it with my colleague who works on Windows10 the converted value was at I was expecting **01/01/0001 03:00:00**.

Any ideas? 
![timezone_convert](https://user-images.githubusercontent.com/33696154/111796137-29241780-88c8-11eb-86d6-e91b99fc06b1.png)

**Comment by huoyaoyuan** [comment]
Leap second difference?

**Comment by Clockwork-Muse** [comment]
The value is correct, Windows is wrong.

When timezones were first introduced, there was an initial adjustment for each zone from local solar noon to a rounder offset.  This can be seen for almost every timezone.

Why Windows is wrong is that these adjustments were (mostly) performed in the late 1800s, and it doesn't store most of the history for timezones.  Linux derivatives store the entire history on most platforms (and Windows will as well when we move to ICU data).

**Comment by Clockwork-Muse** [comment]
> Leap second difference?

There have been 35ish leap seconds added.

**Comment by tarekgh** [comment]
@hciupinski 

What @Clockwork-Muse said is correct. If you look https://www.timeanddate.com/worldclock/converter.html?iso=19001231T210224&p1=27 you can see the same. 

Unfortunately, Windows is not carrying the historical time zone data for all time zones. If you look at the "Arabic Standard Time" zone data on Windows (which corresponds to `Asia/Baghda`) you'll see the data starts from year 2004. so for hostical dates before 2004, we'll use just Utc Offset of the zone itself which is 3 hours. 

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Arabic Standard Time\Dynamic DST` 

I am closing the issue but feel free to send any question if you have any.

**Comment by tarekgh** [comment]
@hciupinski 

What @Clockwork-Muse said is correct. If you look https://www.timeanddate.com/worldclock/converter.html?iso=19001231T210224&p1=27 you can see the same. 

Unfortunately, Windows is not carrying the historical time zone data for all time zones. If you look at the `Arabic Standard Time` zone data on Windows (which corresponds to `Asia/Baghdad`) you'll see the data starts from year 2004. so, for historical dates before 2004, we'll use just Utc Offset of the zone itself which is 3 hours. 

`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Arabic Standard Time\Dynamic DST` 

I am closing the issue but feel free to send any question if you have any.
