### ISSUE TITLE
Regressions/coreclr/GitHub_45929/test45929 intermittently fails with gcstress on arm64

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#49881]
Disabling this test on arm64 for now till we could investigate the crash.

Few issues where this has failed: 
https://github.com/dotnet/runtime/issues/47697
https://github.com/dotnet/runtime/issues/46803

**Comment by BruceForstall** [comment]
It's not just arm64. Here's a R2R Windows x64 case:

https://dev.azure.com/dnceng/public/_build/results?buildId=1047040&view=ms.vss-test-web.build-test-results-tab&runId=32390630&resultId=110633&paneView=debug

**Comment by BruceForstall** [comment]
Plus, https://github.com/dotnet/runtime/issues/46803 shows cases of Windows arm32 failures

**Comment by mangod9** [comment]
Ah ok, will disable globally then till we can investigate.

**Comment by jakobbotsch** [comment]
Failed in Windows ARM32 again in PR #56790: https://dev.azure.com/dnceng/public/_build/results?buildId=1277844&view=ms.vss-test-web.build-test-results-tab

**Comment by janvorli** [comment]
The test is clearly good at finding GC holes due to its stressy nature.

**Comment by kunalspathak** [comment]
I just reopened #46803 because the failure is not under GCStress but in normal R2R outerloop leg. @jakobbotsch - I think we can close this issue.

**Comment by jakobbotsch** [comment]
Sure
