### ISSUE TITLE
Assertion failed '!memBase->isContained()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#49880]
In `runtime-coreclr libraries-jitstress` pipeline, starting with:

https://dev.azure.com/dnceng/public/_build/results?buildId=1043206&view=results

Failure in "net6.0-Linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open", System.Buffers.Tests:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-46176226dcf6415fb8/System.Buffers.Tests/console.2958420a.log?sv=2019-07-07&se=2021-04-06T08%3A11%3A53Z&sr=c&sp=rl&sig=uyJ6VxtQz%2B8nUUEmIP2uwk%2B3cOaS6W93K0Ef%2BfJmr9o%3D

```
COMPlus_TieredCompilation=1
COMPlus_JitStress=1
COMPlus_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
COMPlus_DbgEnableMiniDump=1
+ ./RunTests.sh --runtime-path /home/helixbot/work/A6CA0954/p
----- start Wed Mar 17 08:22:54 UTC 2021 =============== To repro directly: =====================================================
pushd .
/home/helixbot/work/A6CA0954/p/dotnet exec --runtimeconfig System.Buffers.Tests.runtimeconfig.json --depsfile System.Buffers.Tests.deps.json xunit.console.dll System.Buffers.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/work/A6CA0954/w/B021097F/e ~/work/A6CA0954/w/B021097F/e
  Discovering: System.Buffers.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Buffers.Tests (found 42 of 44 test cases)
  Starting:    System.Buffers.Tests (parallel test collections = on, max threads = 2)
    System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure [SKIP]
      Condition(s) not met: "IsStressModeEnabledAndRemoteExecutorSupported"

Assert failure(PID 20228 [0x00004f04], Thread: 20234 [0x4f0a]): Assertion failed '!memBase->isContained()' in 'Bucket[Byte][System.Byte]:.ctor(int,int,int):this' during 'Generate code' (IL size 49)

    File: /__w/1/s/src/coreclr/jit/emitxarch.cpp Line: 3013
    Image: /home/helixbot/work/A6CA0954/p/dotnet
```

Possibly related to new stress mode? https://github.com/dotnet/runtime/pull/49636

@dotnet/jit-contrib

**Comment by sandreenko** [comment]
>> Possibly related to new stress mode? #49636

Probably this one or https://github.com/dotnet/runtime/pull/49084. I should have waited between merging them, now they are in the same bucket.

I will take a look.

**Comment by BruceForstall** [comment]
@sandreenko Any progress on this? It's still failing:

https://dev.azure.com/dnceng/public/_build/results?buildId=1069450&view=ms.vss-test-web.build-test-results-tab&runId=32877518&resultId=176732&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by BruceForstall** [comment]
btw, it also fails in the Windows x64 run, so it's not just Linux.

**Comment by sandreenko** [comment]
It is the same issue as https://github.com/dotnet/runtime/issues/41073. 

I will try to find come up with a patch for it if I don't I will disable the test in stress today.
