### ISSUE TITLE
Infrastructure - Rollout (April 2021)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#49889]
# Overview

We use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the **first Monday of the month (5/4)**.

| Change |  Impact | Assignee |
| --- | --- | --- |
|  #50084 | Update the minimum version of the SDK to 6.0 Preview 2. | @ViktorHofer |
| #49715 | Make Ninja the default CMake generator on Windows | @jkoritzinsky |
| #49906 | Reorganize CoreCLR native build to reduce CMake reconfigures when the build system is untouched | @jkoritzinsky |

## Archive
- [March 2021](https://github.com/dotnet/runtime/issues/48168)
- [December 2020](https://github.com/dotnet/runtime/issues/44524)
- [November 2020](https://github.com/dotnet/runtime/issues/43351)
- [September 2020](https://github.com/dotnet/runtime/issues/39788)
- [July 2020](https://github.com/dotnet/runtime/issues/37706)
- [June 2020](https://github.com/dotnet/runtime/issues/35895)
- [May 2020](https://github.com/dotnet/runtime/issues/35202)
- [April 2020](https://github.com/dotnet/runtime/issues/33821)

**Comment by trylek** [comment]
I originally added a mention of https://github.com/dotnet/runtime/pull/49004 but I think it's probably not worth announcing as part of the rollout as its impact on developer flow is actually very minuscule.

**Comment by BruceForstall** [comment]
@jkoritzinsky @trylek Did one of these changes make is so the native code PDBs are no longer copied to (for example) `artifacts\bin\coreclr\windows.x64.Checked\PDB`? There are managed code PDBs still there (e.g., crossgen2.pdb, R2RDump.pdb).

I notice there are still references to these things in `RunTimeArtifactsExcludeFiles` tags in src\tests\Common\Directory.Build.targets, that seem to indicate not having them there might prevent us from getting good core dumps in Helix runs.

**Comment by jkoritzinsky** [comment]
Try pulling the main branch. There was a bug in one of the PRs in the rollout that has been fixed since.

**Comment by BruceForstall** [comment]
Looks like https://github.com/dotnet/runtime/pull/50819? Ok, I don't have that one.

**Comment by jkoritzinsky** [comment]
Yep that's the fix.

**Comment by trylek** [comment]
Thanks so much Jeremy for figuring this out, I'm not sure if I'd have enough capacity for yet another bug investigation today :-).

**Comment by sadq30** [comment]
> # Overview
> We use this issue to announce planned Infrastructure changes that will impact the developer workflow in `dotnet/runtime`. Changes will be merged on the **first Monday of the month (4/5)**.
> 
> Change	Impact	Assignee
> #50084	Update the minimum version of the SDK to 6.0 Preview 2.	@ViktorHofer
> #49715	Make Ninja the default CMake generator on Windows	@jkoritzinsky
> #49906	Reorganize CoreCLR native build to reduce CMake reconfigures when the build system is untouched	@jkoritzinsky
> ## Archive
> * [March 2021](https://github.com/dotnet/runtime/issues/48168)
> * [December 2020](https://github.com/dotnet/runtime/issues/44524)
> * [November 2020](https://github.com/dotnet/runtime/issues/43351)
> * [September 2020](https://github.com/dotnet/runtime/issues/39788)
> * [July 2020](https://github.com/dotnet/runtime/issues/37706)
> * [June 2020](https://github.com/dotnet/runtime/issues/35895)
> * [May 2020](https://github.com/dotnet/runtime/issues/35202)
> * [April 2020](https://github.com/dotnet/runtime/issues/33821)
