### ISSUE TITLE
[wasm] Blazor workload tasks

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#49910]
For blazor wasm workload, currently:

- aspnetcore has a tool `install-blazoraot` which:
   - installs the workload manifest (json+targets)
   - installs the various packs that it needs (https://github.com/dotnet/aspnetcore/blob/main/src/Components/WebAssembly/BlazorManifest/src/WorkloadManifest.targets#L7-L9)

- This is missing an Emscripten dependency, but since packages for that just recently became available from `main`, we can include those

# Plan

- What we want to do eventually is to have two wasm packs available:
   - `*WebAssembly.Sdk*` pack - containing the props/targets, and any tasks required for building non-aot wasm apps
   - `*WebAssembly.AOT.Sdk*` pack - that would have bits required for AOT (the aot task+cross compiler+emscripten)

- And the blazor workload can then depend on only these two
  - where the AOT.sdk dependency can be conditional

- For *now*, we could just add the Emscripten references directly to install-blazoraot tool, and update the manifest.
   - So, blazor workload would depend on - aot+task+wasm.sdk+cross-compiler, and additionally Emscripten sdk

- In future, when we have a better acquisition story, then we can figure out how to do more of it on-demand

- For info, the Emscripten packages:
```xml
  <PackageReference Include="Microsoft.NET.Runtime.Emscripten.2.0.12.Node.osx-x64" Version="6.0.0-preview.3.21169.6" />
  <PackageReference Include="Microsoft.NET.Runtime.Emscripten.2.0.12.Python.osx-x64" Version="6.0.0-preview.3.21169.6" />
  <PackageReference Include="Microsoft.NET.Runtime.Emscripten.2.0.12.Sdk.osx-x64" Version="6.0.0-preview.3.21169.6" />
</ItemGroup>
```

@lewing @pranavkm thoughts? Feel free to correct me

**Comment by lewing** [comment]
closing for now
