### ISSUE TITLE
Missing test coverage for Module.GetMethod and Module.GetMethods

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#49926]
We have plenty of coverage for GetField but none for GetMethod(s):

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs#L139-L177

Note this requires writing some IL here: https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Runtime/tests/TestModule/System.Reflection.TestModule.il

**Comment by erafalovsky** [comment]
@MichalStrehovsky I'd like to work on this issue. Can you assign it to me?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky I'd like to work on this issue. Can you assign it to me please?

It's yours! Thank you!
