### ISSUE TITLE
System.Private.Uri test failures on Android

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#49932]
The following tests fail/flake on Android and will be skipped for now:

`Assert.False() Failure\nExpected: False\nActual:   True`

- [ ] System.PrivateUri.Tests.UriTests.Uri_DoesNotLockOnString

**Comment by viv718918** [comment]
> Tagging subscribers to this area: @dotnet/ncl
> See info in area-owners.md if you want to be subscribed.
> <details>
> <summary>Issue Details</summary>
> <hr />
> 
> The following tests fail/flake on Android and will be skipped for now:
> 
> 
> 
> `Assert.False() Failure\nExpected: False\nActual:   True`
> 
> 
> 
> - [ ] System.PrivateUri.Tests.UriTests.Uri_DoesNotLockOnString
> 
> <table>
>   <tr>
>     <th align="left">Author:</th>
>     <td>steveisok</td>
>   </tr>
>   <tr>
>     <th align="left">Assignees:</th>
>     <td>-</td>
>   </tr>
>   <tr>
>     <th align="left">Labels:</th>
>     <td>
> 
> `area-System.Net`, `os-android`, `runtime-mono`, `untriaged`
> 
> </td>
>   </tr>
>   <tr>
>     <th align="left">Milestone:</th>
>     <td>6.0.0</td>
>   </tr>
> </table>
> </details>

**Comment by mdh1418** [comment]
No longer fails locally. Debug mode also runs into https://github.com/dotnet/runtime/issues/56854
