### ISSUE TITLE
Analyzer Proposal: Seal internal/private types

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#49944]
There are numerous performance benefits to sealing types:
1.	Calls to overrides can be done directly rather than with virtual dispatch, which then also means they can be inlined.

```C#
public class C {
    internal void Call(SealedType o) => o.M();
    internal void Call(NonSealedType o) => o.M();
}

internal class BaseType
{
    public virtual void M() {}
}
internal class NonSealedType : BaseType
{
    public override void M() {}
}
internal sealed class SealedType : BaseType
{
    public override void M() {}
}
```
results in:
```
C.Call(SealedType)
    L0000: cmp [rdx], edx
    L0002: ret

C.Call(NonSealedType)
    L0000: mov rcx, rdx
    L0003: mov rax, [rdx]
    L0006: mov rax, [rax+0x40]
    L000a: mov rax, [rax+0x20]
    L000e: jmp rax
```

2.	`is`/`as` type checks for the type can be done more efficiently, as it only needs to compare the type itself rather than account for a potential hierarchy.

```C#
public class C {
    public bool IsSealed(Object o) => o is SealedType;
    public bool IsNotSealed(Object o) => o is NonSealedType;
}

internal class NonSealedType { }
internal sealed class SealedType { }
```
results in:
```
C.IsSealed(System.Object)
    L0000: test rdx, rdx
    L0003: je short L0016
    L0005: mov rax, 0x7ff7ab9ad180
    L000f: cmp [rdx], rax
    L0012: je short L0016
    L0014: xor edx, edx
    L0016: test rdx, rdx
    L0019: setne al
    L001c: movzx eax, al
    L001f: ret

C.IsNotSealed(System.Object)
    L0000: sub rsp, 0x28
    L0004: mov rcx, 0x7ff7ab9ad048
    L000e: call System.Runtime.CompilerServices.CastHelpers.IsInstanceOfClass(Void*, System.Object)
    L0013: test rax, rax
    L0016: setne al
    L0019: movzx eax, al
    L001c: add rsp, 0x28
    L0020: ret
```

3.	Arrays of that type don’t need covariance checks every time an element is stored into it.

```C#
public class C {
    internal void StoreSealed(SealedType[] arr, SealedType item) => arr[0] = item;
    internal void StoreNonSealed(NonSealedType[] arr, NonSealedType item) => arr[0] = item;
}

internal class NonSealedType { }
internal sealed class SealedType { }
```
results in:
```
C.StoreSealed(SealedType[], SealedType)
    L0000: sub rsp, 0x28
    L0004: cmp dword ptr [rdx+8], 0
    L0008: jbe short L001c
    L000a: lea rcx, [rdx+0x10]
    L000e: mov rdx, r8
    L0011: call 0x00007ff801db9f80
    L0016: nop
    L0017: add rsp, 0x28
    L001b: ret
    L001c: call 0x00007ff801f0bc70
    L0021: int3

C.StoreNonSealed(NonSealedType[], NonSealedType)
    L0000: sub rsp, 0x28
    L0004: mov rcx, rdx
    L0007: xor edx, edx
    L0009: call System.Runtime.CompilerServices.CastHelpers.StelemRef(System.Array, Int32, System.Object)
    L000e: nop
    L000f: add rsp, 0x28
    L0013: ret
```

4.	Creating spans of that type don’t need to validate the actual type of the array matches the specified generic type.

```C#
using System;
public class C {
    internal Span<SealedType> CreateSealed(SealedType[] arr) => arr;
    internal Span<NonSealedType> CreateNonSealedType(NonSealedType[] arr) => arr;
}

internal class NonSealedType { }
internal sealed class SealedType { }
```
results in:
```
C.CreateSealed(SealedType[])
    L0000: test r8, r8
    L0003: jne short L000b
    L0005: xor eax, eax
    L0007: xor ecx, ecx
    L0009: jmp short L0013
    L000b: lea rax, [r8+0x10]
    L000f: mov ecx, [r8+8]
    L0013: mov [rdx], rax
    L0016: mov [rdx+8], ecx
    L0019: mov rax, rdx
    L001c: ret

C.CreateNonSealedType(NonSealedType[])
    L0000: sub rsp, 0x28
    L0004: test r8, r8
    L0007: jne short L000f
    L0009: xor eax, eax
    L000b: xor ecx, ecx
    L000d: jmp short L0026
    L000f: mov rax, 0x7ff7aba4d870
    L0019: cmp [r8], rax
    L001c: jne short L0034
    L001e: lea rax, [r8+0x10]
    L0022: mov ecx, [r8+8]
    L0026: mov [rdx], rax
    L0029: mov [rdx+8], ecx
    L002c: mov rax, rdx
    L002f: add rsp, 0x28
    L0033: ret
    L0034: call System.ThrowHelper.ThrowArrayTypeMismatchException()
    L0039: int3
```

5.	Probably more both I’ve missed and that will emerge in the future.

We should add an analyzer, at either hidden or info level but that we’d look to turn on as a warning in dotnet/runtime, that flags:
- Internal and private non-static, non-abstract, non-sealed classes that
- Don’t have any derived types in its containing assembly
- Which also doesn't have InternalsVisibleTo on it

and flag that they should be sealed.  A fixer would seal the type.  We could also make it configurable on the visibility, in case someone wanted to e.g. also opt-in public types (we wouldn't/couldn't in dotnet/runtime).  We could also optionally factor in whether the type declares any new virtual methods, a protected ctor, or anything else that suggests the type is intended for derivation... upon detecting such things, we could either choose not to warn, or we could warn with a different diagnostic id.

If a developer working in the library ever wants to derive from such a type, they can remove the sealed when they add the derivation.

**Comment by danmoseley** [comment]
Can the JIT not perform a similar thought process?

**Comment by stephentoub** [comment]
> Can the JIT not perform a similar thought process?

It's the JIT that's doing these aforementioned optimizations based on the type being sealed, but the JIT can't assume that non-sealed types won't ever have derived types, e.g. if a derived type were to be reflection emitted.

**Comment by jkotas** [comment]
> Can the JIT not perform a similar thought process?

Full AOT that can do global analysis of all code that will ever run in the process can do this optimization.

JIT can do this optimization speculatively by assuming that the type is sealed, and undoing/rejiting all code that depends on this assumption when it is proven false. We have stayed away from speculative optimizitions like this so far. We have actually tried to build a similar speculative optimization for dictionaries of shared generic types, but we ended up rolling it back because of it proved to be hard to stabilize and had questionable performance characteristics.

**Comment by KalleOlaviNiemitalo** [comment]
Sealing a type might cause warning [CS0628](<https://docs.microsoft.com/dotnet/csharp/misc/cs0628> "Compiler Warning (level 4) CS0628") or [CA1047](<https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1047> "CA1047: Do not declare protected members in sealed types") if the type has protected members.
- Lets an override of `Object.Equals(Object obj)` check `obj is ThisType` rather than `obj.GetType() == this.GetType()`.

If the type is being sealed to help the JIT compiler, not for design reasons, then the developer might want to keep protected members protected so that the type can be easily unsealed again if a derived class is added.

If there is going to be a code fix that seals types, then perhaps it could also suppress those warnings.

**Comment by huoyaoyuan** [comment]
> Which also doesn't have InternalsVisibleTo on it

It's quite common for a lib project to have InternalsVisibleTo for its corresponding test project.

**Comment by stephentoub** [comment]
> It's quite common for a lib project to have InternalsVisibleTo for its corresponding test project.

Various optimizations are disabled by InternalsVisibleTo, e.g. the linker can't remove unused internals when building in a library marked InternalsVisibleTo.  I'm fine with that being a limitation for this analyzer, as it is for other analyzers, like CA1812 (avoid uninstantiated internal classes).

**Comment by stephentoub** [comment]
> Sealing a type might cause warning CS0628 or CA1047 if the type has protected members.

Yes, that's why I wrote "We could also optionally factor in whether the type declares any new virtual methods, a protected ctor, or anything else that suggests the type is intended for derivation... upon detecting such things, we could either choose not to warn, or we could warn with a different diagnostic id."

**Comment by stephentoub** [comment]
> JIT can do this optimization speculatively by assuming that the type is sealed, and undoing/rejiting all code that depends on this assumption when it is proven false.

Yes, though my understanding from previous discussions with @AndyAyersMS on the topic is we have no intention of doing that sort of work any time soon, even though his OSR work starts to open the door to that.

**Comment by GrabYourPitchforks** [comment]
Might be able to expand the analyzer scope even further:

* Public types which have only private ctors and which don't have a nested subclassed type
* Public types which have only internal ctors, no subclassed types within the same assembly, and no friend assemblies defined

**Comment by JamesNK** [comment]
> > It's quite common for a lib project to have InternalsVisibleTo for its corresponding test project.
> 
> Various optimizations are disabled by InternalsVisibleTo, e.g. the linker can't remove unused internals when building in a library marked InternalsVisibleTo. I'm fine with that being a limitation for this analyzer, as it is for other analyzers, like CA1812 (avoid uninstantiated internal classes).

Have we ever considered a flag on `InternalsVisibleToAttribute` to indicate that its usage is related to testing? Optimizations can then check whether the attribute exists without that flag set when making decisions.

I always use IVT for testing and never for sharing runtime code between assemblies.

**Comment by stephentoub** [comment]
> Optimizations can then check whether the attribute exists without that flag set when making decisions.

What would the analyzer do differently if that was set? Ignore the attribute and then it's up to you to either change your tests or suppress the warning if the tests were dependent on the type being unsealed?

**Comment by jnm2** [comment]
> A fixer would seal the type.

From personal experience actually having implemented exactly this analyzer to warn if classes aren't sealed and offer a fix, Roslyn has a design issue that means that you can't offer fixes for any diagnostics reported by your analyzer during the compilation end action. And the compilation end action is the most (only?) reasonable place to report everything, since you need to wait until all symbols have been analyzed in order to know whether any classes inherit from the ones you might report the diagnostic for.

Reported issue: https://github.com/dotnet/roslyn/issues/51653

**Comment by stephentoub** [comment]
I've been sealing stuff across dotnet/runtime.  Another case has come up that we might want to factor in to whether the analyzer raises a notification (or maybe a separate diagnostic ID for these less clear cases), or potentially it would just impact a fixer. 

Today, you can write code like this:
```C#
using System;

class C { }

class Consumer
{
    public static IDisposable Bar(C obj) => obj as IDisposable;
}
```
and that will compile fine.  However, if you seal C:
```C#
using System;

sealed class C { }

class Consumer
{
    public static IDisposable Bar(C obj) => obj as IDisposable;
}
```
that cast will now fail to compile:
```
error CS0039: Cannot convert type 'C' to 'System.IDisposable' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion
```
because the compiler can now see that C definitely doesn't implement the interface (whereas before a type derived from C may have).

This can also happen even without derived types in the picture, where casts are used to go from a concrete generic instantiation to an open generic, e.g. this compiles fine:
```C#
interface IMyInterface<T> {}

class C<T> : IMyInterface<T> {}

class Int32C : C<int>
{
    public static Int32C Instance { get; } = new Int32C();
}

class Consumer
{
    static IMyInterface<T> Bar<T>()
    {
        if (typeof(T) == typeof(int))
        {
            return (IMyInterface<T>)Int32C.Instance;
        }
        
        return null;
    }
}
```
Int32C implements `IMyInterface<T>`; the compiler doesn't know that it will in fact satisfy the cast at run time (it only knows the type implements `IMyInterface<int>` and it doesn't know that `T` == `int`), but because Int32C isn't sealed, it allows the cast to compile because a type derived from Int32C could implement `IMyInterface<T>`.  But, if you seal Int32C:
```C#
interface IMyInterface<T> {}

class C<T> : IMyInterface<T> {}

sealed class Int32C : C<int>
{
    public static Int32C Instance { get; } = new Int32C();
}

class Consumer
{
    static IMyInterface<T> Bar<T>()
    {
        if (typeof(T) == typeof(int))
        {
            return (IMyInterface<T>)Int32C.Instance;
        }
        
        return null;
    }
}
```
now you get:
```
error CS0030: Cannot convert type 'Int32C' to 'IMyInterface<T>'
```

Both of these cases can be solved by inserting an `(object)` cast in the middle.

**Comment by GrabYourPitchforks** [comment]
@stephentoub I made a small modification to your sample code and wanted to get your thoughts.

```cs
using System;

public class C {
    public static IDisposable M(MyClass c) {
        return c as IDisposable;  // CS0039
    }
}

public sealed class MyClass : System.Collections.Generic.List<int>
{
}
```

This feels wrong to me. The C# compiler in theory has no way of knowing whether that cast will succeed or fail at runtime, since it has no way of knowing the shape of the actual runtime superclass type. It only knows about what's exposed via the reference assembly.

Obviously we're not going to add _IDisposable_ to `List<T>`, but consider this as a generalized example. Since we also now have the ability to introduce default interface members, this means (in theory) if `sealed class Foo : IBar`, and we later make `IBar : IBaz` (at runtime, via default interface implementations so as not to break API contracts), then `Foo` also implicitly implements `IBaz` (at runtime) even though it's never explicitly stated in the code or compiled into the assembly.

**Comment by stephentoub** [comment]
@GrabYourPitchforks, to make sure I understand, you're questioning the C# compiler's warnings/errors in these cases and suggesting it shouldn't validate interface casts at all?

**Comment by GrabYourPitchforks** [comment]
> you're questioning the C# compiler's warnings/errors in these cases and suggesting it shouldn't validate interface casts at all?

Correct. Or at most, a warning ("are you sure you intended to write this? it probably won't work at runtime."), not an error ("it definitely won't work at runtime."). That would hopefully reduce any complexity in your proposed analyzer and fixer.

**Comment by stephentoub** [comment]
cc: @jaredpar 

I understand the position, and don't have a strong opinion about it.  But there are plenty of places where the C# compiler trusts the ref assembly and requires it to be accurate, making important decisions based on it.  It's why we have all those _dummy private fields throughout our ref assemblies.

**Comment by GrabYourPitchforks** [comment]
@stephentoub I didn't intend it to be an accuracy thing, more a versioning thing. You compile your application against the v5 ref assemblies but execute against a v6 runtime. (Both the v6 runtime and the v6 ref assemblies are in agreement on the public API shape.) With the current compiler behavior, there's an argument that it's a breaking change for us ever to add an interface to an already-shipped unsealed type.

**Comment by stephentoub** [comment]
I don't see how it's any more of a breaking change than,  say,  any time we add a new instance method. 

This argument also seems like a rabbit hole.  Should this also compile?
```C#
class C { }
class B { }
...
B b = ...;
C c = b;
```
After all, in a future build I could change B to derive from C, or I could do so in the implementation assembly but not ref assembly. But it's madness to me that such code might possibly compile.

**Comment by GrabYourPitchforks** [comment]
> Should this also compile?

No, because the cast isn't guaranteed to succeed. For anything that's not guaranteed, implicit conversions should fail at compile time. That's what "as" and "is" are for.

I'm not trying to go down a rabbit hole here. More like trying to figure out if some of the problems you discovered should be offloaded to the compiler as change requests rather than something your analyzer has to handle. But if we're starting to veer out of scope then let's not worry about it. :)

**Comment by stephentoub** [comment]
> No, because the cast isn't guaranteed to succeed.

I had two examples. One of them had this:
```C#
return (IMyInterface<T>)Int32C.Instance
```
and the other had this:
```C#
return obj as IDisposable;
```
So you weren't commenting on both examples, just the one that used `as`?

**Comment by GrabYourPitchforks** [comment]
> So you weren't commenting on both examples, just the one that used as?

Correct. Figured there's some magic generic goop in the other example. The is / as one is small enough where I can feign an understanding of it _and_ give you and give the C# team a perfect opportunity to school me on language nits. 😃

**Comment by stephentoub** [comment]
> Correct. 

Gotcha.  So you'd expect:
```C#
class C { }
class B { }
...
B b = ...;
C c = b as C;
```
to compile successfully.  I can see the viewpoint.

**Comment by bartonjs** [comment]
Sounds good, assuming the general heuristics of

* Internal and private non-static, non-abstract, non-sealed classes that
* Don’t have any derived types in its containing assembly
* Which also doesn't have InternalsVisibleTo on it (for internal types)

**Comment by geeknoid** [comment]
I have an implementation of the basic analyzer with tests here: https://github.com/geeknoid/UnsealedAnalyzer which I developed for our project. It could give a head-start to someone working on this issue. It doesn't support all the features requested here, but it doesn't cover the essentials.

**Comment by NewellClark** [comment]
I would like to be assigned to this.

**Comment by askazakov** [comment]
@stephentoub I'm sorry I've not catch is it https://rules.sonarsource.com/csharp/RSPEC-3260 about the same issue? Did I miss something important?

**Comment by stephentoub** [comment]
@askazakov, that's in an unrelated static analysis library rather than the analyzers that ship as part of the .NET SDK, and at least from the description it's only about private rather than non-public, e.g. it doesn't seem to cover internal types (at least not from the short description you linked to).

**Comment by meziantou** [comment]
I think the analyzer should exclude classes declared as `[ComImport]`/`[CoClass]` from the analysis as the fix may break the compilation:

````c#
using System.Runtime.InteropServices;

_ = (IFileSaveDialog)new FileSaveDialogRCW(); // If FileSaveDialogRCW is sealed: error CS0030: Cannot convert type 'FileSaveDialogRCW' to 'IFileSaveDialog'

[ComImport]
[Guid("C0B4E2F3-BA21-4773-8DBA-335EC946EB8B")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[CoClass(typeof(FileSaveDialogRCW))]
internal interface IFileSaveDialog
{
}

[ComImport]
[ClassInterface(ClassInterfaceType.None)]
[Guid("C0B4E2F3-BA21-4773-8DBA-335EC946EB8B")]
class FileSaveDialogRCW // 👈 sealed is not valid here because of `new NativeFileSaveDialog()`
{
}
````

**Comment by ericstj** [comment]
@meziantou -- it looks like this is currently under PR here https://github.com/dotnet/roslyn-analyzers/pull/5594  Would you mind adding your feedback there?
