### ISSUE TITLE
JIT (x86, .NET Framework) incorrectly optimizes away null checks for `string.Length`

### ISSUE THREAD

**Issue by GeeLaw** [dotnet/runtime#49957]
## Description

Suppose `string.Length` is retrieved but unused, then x86 JIT compilers for .NET Framework (2.0 to 4.8) will optimize away the null check. This causes `NullReferenceException` to **not** be thrown.

For example, the following code will write `Bad: string.` when run in .NET Framework 2.0 to 4.8, x86, Release mode:

```csharp
using System;

namespace Reproduction
{
  public static class Program
  {
    public static void Main()
    {
      try
      {
        // This null check is incorrectly optimized away.
        int unused = ((string)null).Length;
        Console.WriteLine("Bad: string.");
      }
      catch (NullReferenceException) { }
      try
      {
        // This null check is correctly preserved.
        int unused = ((double[])null).Length;
        Console.WriteLine("Bad: double[].");
      }
      catch (NullReferenceException) { }
      try
      {
        // This null check is correctly preserved.
        int unused = ((object[])null).Length;
        Console.WriteLine("Bad: object[].");
      }
      catch (NullReferenceException) { }
    }
  }
}
```

## Configuration

- Windows 10 (x64), version 1909, build 18363.1440.
- .NET Framework 2.0 to 4.8 (x86).
- Release mode.

This issue does not reproduce under x64, or under .NET Core or .NET 5.0. It also does not reproduce if JIT does not optimize the code.

## Why, though?

The point of saying `int unused = x.Length;` for string or array `x` is to obtain a high-performance null check. According to C# spec, this expression throws `NullReferenceException` if `x` is `null`.

The null checks for instance method invocations are very efficienct:

- If the call is direct virtual or interface, then no explicit check is done, because fetching the v-table for `null` will raise access violation, which is converted to `NullReferenceException` by CLR.
- If the call is non-virtual, then the check is a dummy comparison, `cmp [ecx], ecx` or `cmp [rcx], ecx` (`rcx` or `ecx` contains `this`). Again, access violation will be converted to `NullReferenceException` by CLR.

In extension methods, one might want to throw `NullReferenceException` immediately, even if the code **does not immediately dereference** the object. Doing an explicit reference comparison (and throwing an exception) does not lead to the most efficienct code. In other words, JIT does **not** optimize the following into `cmp [that], that`:

```csharp
// This works, but has large code size and not the most efficient.
public static void ThrowIfNull(this string that)
{
  if (ReferenceEquals(that, null))
    throw new NullReferenceException();
}
// This works, but has large code size and not the most efficient.
public static void ThrowIfNull<T>(this T[] that)
{
  if (ReferenceEquals(that, null))
    throw new NullReferenceException();
}
```

By C# spec, it's equivalent to write:

```csharp
// This might not work due to incorrect optimization.
public static void ThrowIfNull(this string that)
{
  int unused = that.Length;
}
// This works, and is very efficient.
public static void ThrowIfNull<T>(this T[] that)
{
  int unused = that.Length;
}
```

## Workaround

It turns out that `string.GetTypeCode()` does not suffer this problem.

```csharp
// This works, and is very efficient.
// The null check is preserved in the form of `cmp byte [that], al` or something.
// The call to `GetTypeCode` does not happen.
public static void ThrowIfNull(this string that)
{
  that.GetTypeCode();
}
```

**Comment by jeffschwMSFT** [comment]
@GeeLaw can you file this issue on https://developercommunity.visualstudio.com/home?  We do not have a place to track .NET Framework issues in this repo, as this is for .NET Core.  Once you have filed it, please link the feedback item to this issue.  Thanks.

**Comment by GeeLaw** [comment]
Thanks for the pointer... Didn't know where to send feedback for .NET Framework since Connect is closed. Will file the issue there :)
