### ISSUE TITLE
InvalidOperationException

### ISSUE THREAD

**Issue by Barshan-Mandal** [dotnet/runtime#49955]
![image](https://user-images.githubusercontent.com/74092409/111896531-85ac4180-8a44-11eb-98c8-e29db0fa334f.png)

**Comment by stephentoub** [comment]
Can you share the code for your repro rather than a debugger screenshot?

Is it possible the process for which this is throwing had already exited?

**Comment by Barshan-Mandal** [comment]
var procge = from proc in System.Diagnostics.Process.GetProcesses() orderby proc.ProcessName ascending select proc;
            
            foreach (var VARIABLE in procge)
            {
               
                try
                {
                    Console.WriteLine(VARIABLE.ProcessName);
                    Console.WriteLine(VARIABLE.StartInfo.UserName);
                    Console.WriteLine(VARIABLE.GetType().IsSecurityCritical.ToString());
                    Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
                }

**Comment by Barshan-Mandal** [comment]
.net 5 problem

**Comment by Barshan-Mandal** [comment]
problem in .net 5
`var procge = from proc in System.Diagnostics.Process.GetProcesses() orderby proc.ProcessName ascending select proc;

        foreach (var VARIABLE in procge)
        {
           
            try
            {
                Console.WriteLine(VARIABLE.ProcessName);
                Console.WriteLine(VARIABLE.StartInfo.UserName);
                Console.WriteLine(VARIABLE.GetType().IsSecurityCritical.ToString());
                Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
            }`

**Comment by Barshan-Mandal** [comment]
process has not exited...............................
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var procge = from proc in System.Diagnostics.Process.GetProcesses() orderby proc.ProcessName ascending select proc;
            
            foreach (var VARIABLE in procge)
            {
               
                try
                {
                    if (VARIABLE.HasExited==false)
                    {
                        Console.WriteLine(VARIABLE.ProcessName);
                        Console.WriteLine(VARIABLE.StartInfo.UserName);
                        Console.WriteLine(VARIABLE.GetType().IsSecurityCritical.ToString());
                        Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    Console.WriteLine("///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////");
                }
               
            }

        }
    }
}
also gives exception as above

**Comment by Barshan-Mandal** [comment]
| Name | Value | Type
-- | -- | -- | --
◢ | $exception | {"Process was not started by this object, so requested information cannot be determined."} | System.InvalidOperationException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233079 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Process was not started by this object, so requested information cannot be determined." | string
  | SerializationRemoteStackTraceString | null | string
  | SerializationStackTraceString | "   at System.Diagnostics.Process.get_StartInfo()\r\n   at ConsoleApp1.Program.Main(String[] args) in C:\\Users\\SCS\\source\\repos\\ConsoleApp1\\Program.cs:line 20" | string
  | ▶ SerializationWatsonBuckets | {byte[5616]} | object {byte[]}
  | Source | "System.Diagnostics.Process" | string
  | StackTrace | "   at System.Diagnostics.Process.get_StartInfo()\r\n   at ConsoleApp1.Program.Main(String[] args) in C:\\Users\\SCS\\source\\repos\\ConsoleApp1\\Program.cs:line 20" | string
  | ▶ TargetSite | {System.Diagnostics.ProcessStartInfo get_StartInfo()} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | _HResult | -2146233079 | int
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object[]
  | _exceptionMethod | null | System.Reflection.MethodBase
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | _ipForWatsonBuckets | 0x0000000000000000 | System.UIntPtr
  | _message | "Process was not started by this object, so requested information cannot be determined." | string
  | _remoteStackTraceString | null | string
  | _source | null | string
  | ▶ _stackTrace | {byte[96]} | byte[]
  | _stackTraceString | null | string
  | ▶ _watsonBuckets | {byte[5616]} | byte[]
  | _xcode | -532462766 | int
  | _xptrs | 0x0000000000000000 | System.IntPtr
  | ▶ Static members |   |

**Comment by Barshan-Mandal** [comment]
help me please....i am only 8 years old.please help me

**Comment by adamsitnik** [comment]
Hi @Barshan-Mandal 

The `StartInfo` property is valid only for processes, that have been started by the current process itself. Example:

```cs
ProcessStartInfo startInfo = new ProcessStartInfo(fileName: "notepad.exe");
Process notepadProcess = Process.Start(startInfo);
Console.WriteLine(notepadProcess.StartInfo.UserName);
```

If you want to determine the user name for processes that were not started by the current process, you can use [WMI](https://stackoverflow.com/a/777567) or [WinAPI](https://stackoverflow.com/a/38676215). Example:

```cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Principal;

namespace ConsoleApp67
{
    class Program
    {
        private const int PROCESS_VM_OPERATION = 0x0008;

        [DllImport("advapi32.dll", SetLastError = true)]
        private static extern bool OpenProcessToken(IntPtr ProcessHandle, uint DesiredAccess, out IntPtr TokenHandle);

        [DllImport("kernel32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool CloseHandle(IntPtr hObject);

        static void Main()
        { 
            var processes = from proc in Process.GetProcesses() orderby proc.ProcessName ascending select proc;

            foreach (var process in processes)
            {
                IntPtr processHandle = IntPtr.Zero;

                try
                {
                    OpenProcessToken(process.Handle, PROCESS_VM_OPERATION, out processHandle);

                    Console.WriteLine(process.ProcessName);
                    Console.WriteLine(GetProcessUser(processHandle));
                    Console.WriteLine(process.GetType().IsSecurityCritical.ToString());
                    Console.WriteLine("/////////////");
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    Console.WriteLine("/////////////");
                }
                finally
                {
                    if (processHandle != IntPtr.Zero)
                    {
                        CloseHandle(processHandle);
                    }
                }
            }
        }

        private static string GetProcessUser(IntPtr processHandle)
        {
            using (WindowsIdentity wi = new WindowsIdentity(processHandle))
            {
                return wi.Name;
            }
        }
    }
}
```

This requires the installation of an additional NuGet package:

```xml
  <ItemGroup>
    <PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
  </ItemGroup>
```

Could you say a little bit more about what you are trying to achievie?

**Comment by Barshan-Mandal** [comment]
Please add cross platform implementation

**Comment by danmoseley** [comment]
@Barshan-Mandal  could you please answer the question - what are you trying to achieve?

**Comment by Barshan-Mandal** [comment]
The example which you have given is only applicable for windows.But I want to apply it in all platform ie mac linux android ios etc.So it there any cross platform implementation of your code example?

**Comment by adamsitnik** [comment]
@Barshan-Mandal we know that the implementation is Windows-specific, but before we provide a cross-platform solution we would like to know what you are trying to achieve. The better understanding we have, the better answer we can provide.

**Comment by KalleOlaviNiemitalo** [comment]
`IsSecurityCritical` in the source code is unlikely to do what you wanted. Did you intend to make the program answer one of these questions:

- Does the process have higher privileges than normal users do?
- Do I have the authority to terminate the process?
- If I terminated the process, then would the operating system keep working or would it have to restart?

(I don't think .NET provides portable APIs for answering any of those questions.)

**Comment by Barshan-Mandal** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml.cs	24	Active
Error	CS1061	'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml.cs	14	Active
Error	XLS0414	The type 'ThemeResource' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml	10	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	App2.Skia.Gtk	D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\App2.Skia.Gtk.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.	App2.Skia.Wpf.Host	D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host.csproj	1

**Comment by Barshan-Mandal** [comment]
tnx..but please add them

**Comment by Barshan-Mandal** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\App.xaml.cs	24	Active
Error	CS1061	'MainPage' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.Skia.Tizen, App2.Skia.Wpf, App2.Wasm, App2.iOS, App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml.cs	14	Active
Error	XLS0414	The type 'ThemeResource' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	App2.macOS	D:\Temporary\testprojects\vs19\App2\App2.Shared\MainPage.xaml	10	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.	App2.Skia.Gtk	D:\Temporary\testprojects\vs19\App2\App2.Skia.Gtk\App2.Skia.Gtk.csproj	1	
Warning	NU1701	Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.	App2.Skia.Wpf.Host	D:\Temporary\testprojects\vs19\App2\App2.Skia.Wpf.Host\App2.Skia.Wpf.Host.csproj	1

**Comment by jeffhandley** [comment]
Without understanding what the scenario is that was being attempted, we won't be able to pursue this any further.
