### ISSUE TITLE
Test failure: JIT\\opt\\Structs\\structcopies\\structcopies.cmd in jitstress

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#49954]
https://dev.azure.com/dnceng/public/_build/results?buildId=1048985&view=ms.vss-test-web.build-test-results-tab

Test introduced by https://github.com/dotnet/runtime/pull/48377

**Comment by sandreenko** [comment]
interesting, the test was passing jitstress in the PR that merged it https://dev.azure.com/dnceng/public/_build/results?buildId=1033272&view=ms.vss-test-web.build-test-results-tab , will take a look.

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress 20210320.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1049624&view=ms.vss-test-web.build-test-results-tab&runId=32441392&resultId=107330&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
 -JIT\\opt\\Structs\\structcopies\\structcopies.cmd
```

**Error message:**
```
Return code: 1
Raw output file: C:\h\w\AC80094A\w\C5A50A70\e\JIT\opt\Reports\JIT.opt\Structs\structcopies\structcopies.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AC80094A\p\corerun.exe" structcopies.dll 
TestS8_WW1 failed
TestS8 failed
TestS16_W1 failed
TestS16 failed
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AC80094A\p
> C:\h\w\AC80094A\w\C5A50A70\e\JIT\opt\Structs\structcopies\structcopies.cmd
Expected: True
Actual: False

Stack trace
   at JIT_opt._Structs_structcopies_structcopies_._Structs_structcopies_structcopies_cmd()

```

**Comment by BruceForstall** [comment]
@sandreenko If you don't have a fix for this today, could you disable the test?

**Comment by sandreenko** [comment]
I am working on the fix, expecting it to be available today.
