### ISSUE TITLE
Issue : CompareTo of Half type when parameters are negative value

### ISSUE THREAD

**Issue by keicoon** [dotnet/runtime#49983]
Environment : dotnet core 5.0

Problem is `CompareTo` of Half type when parameters are negative value.
I expect below example result.
```
Half half1 = (Half)(-180f);
Half half2 = (Half)(-180f);

var a1 = half1.Equals(half2); // true
var a2 = half1 == half2; // true
var a3 = half1.CompareTo(half2); // not 0, but -1
```
Why `a3` value is -1? not 0 ?

I follow dotnet core code and find out some strange code.
`Half operator <` that called in `CompareTo` is right   ?
```
public static bool operator <(Half left, Half right)
{
    if (IsNaN(left) || IsNaN(right))
    {
        // IEEE defines that NaN is unordered with respect to everything, including itself.
        return false;
    }

    bool leftIsNegative = IsNegative(left);

    if (leftIsNegative != IsNegative(right))
    {
        // When the signs of left and right differ, we know that left is less than right if it is
        // the negative value. The exception to this is if both values are zero, in which case IEEE
        // says they should be equal, even if the signs differ.
        return leftIsNegative && !AreZero(left, right);
    }
    return (left._value < right._value) ^ leftIsNegative;
}
```
When both left and right is same value of negative, `<` make `-1` to return value.

Thanks to read this issue. Somebody help me :cry:

**Comment by KalleOlaviNiemitalo** [comment]
Apparently, the previous fix <https://github.com/dotnet/runtime/pull/39773> is not quite right. It omits the equality comparison that is in the Berkeley code.

**Comment by tannergooding** [comment]
If someone wants to provide a fix here, the change looks relatively simple.

**Comment by Marusyk** [comment]
Please assign it to me, I will try to prepare a PR for this

**Comment by danmoseley** [comment]
It's yours @Marusyk

**Comment by danmoseley** [comment]
@ntovas here are the Half tests:

https://github.com/dotnet/runtime/blob/e7b743cae325d4720fceaf7f84f68aaaf7bb7dbe/src/libraries/System.Runtime/tests/System/HalfTests.cs#L11

Please do let us know if you have trouble building and running tests. The docs should be accurate: if not we will fix them.

**Comment by danmoseley** [comment]
Oh hold on @ntovas, @Marusyk already is fixing this one. You would be welcome to pick another:

https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs++label%3Aeasy+
https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Aup-for-grabs+

**Comment by Marusyk** [comment]
No, I don't. It was closed and unassigned 18 days ago. I couldn't add and check tests without building it.

**Comment by danmoseley** [comment]
Per https://github.com/ucb-bar/berkeley-softfloat-3//blob/b64af41c3276f97f0e181920400ee056b9c88037/source/f16_le.c#L62

it should be
```diff
-            return (left._value < right._value) ^ leftIsNegative;
+
+            return (left._value == right._value) || (left._value < right._value) ^ leftIsNegative;
```
Just need some tests.
