### ISSUE TITLE
ILAsm errors when entrypoint method declared on an interface

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [dotnet/runtime#49998]
### Description

ILAsm 6.0.0-preview.2.21154.6 errors when a static method declared in an interface has `.entrypoint`. [C# 8.0 supports `Main` being declared in an interface](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/default-interface-methods#main-in-an-interface-closed), so this is a C# scenario that does not round-trip through ILDasm / ILAsm.

The C#:

```
using System;

namespace InterfaceMain
{
    interface Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

IL (excerpt):

```
.class interface private abstract auto ansi InterfaceMain.Program
{
  .method public hidebysig static void  Main(string[] args) cil managed
  {
    .entrypoint
    // Code size       11 (0xb)
    .maxstack  8
    IL_0000:  ldstr      "Hello World!"
    IL_0005:  call       void [System.Console]System.Console::WriteLine(string)
    IL_000a:  ret
  } // end of method Program::Main

} // end of class InterfaceMain.Program
```

Attached ZIP file with the reproduction: 
[InterfaceMain.zip](https://github.com/dotnet/runtime/files/6183146/InterfaceMain.zip)

**Repro instructions**: Download and extract the ZIP file, then run `roundtrip.bat`. This will install ILDasm and ILAsm from NuGet, build the C#, and disassemble / re-assemble the IL. (The `out.txt` file in the ZIP file shows a run of this script on my machine.)

**Expected behavior**: ILAsm completes successfully, producing an assembly `.\roundtrip\InterfaceMain.dll` semantically equivalent to `.\bin\Release\net5.0\InterfaceMain.dll`.

**Actual behavior**: ILAsm errors (exit code 1), with the error `Entrypoint in Interface: Method 'Main'`

### Configuration

* C# target framework: `net5.0`
* `dotnet` build engine: 16.9.0-preview-20611-06+5abf1ff7b
* Relevant SDKs
    * 5.0.100 [C:\Program Files\dotnet\sdk]
    * 5.0.102 [C:\Program Files\dotnet\sdk]
    * 5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
* OS: `Microsoft Windows [Version 10.0.18362.592]`
* Architecture: x64
* I don't believe the problem is specific to this configuration.

### Regression?

Reproduced with ILDasm/ILAsm NuGet package versions 5.0.0 and 6.0.0-preview.2.21154.6.

Since having an entrypoint in an interface was truly invalid prior to the .NET Core 3.0 runtime changes, the full .NET Framework ILAsm (version 4.8.3752.0) errors in the same way.

### Other information

In theory a workaround would be to change the interface to a non-interface class in the IL, then use some other tool to change it back to an interface after assembling. I suspect this could have further complications, though, and I haven't investigated it.

### Customer Impact

I'm filing this issue on behalf of my employer, PreEmptive LLC, as a member of the Dotfuscator team. (PreEmptive is a Microsoft partner, and [Dotfuscator is included in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/?view=vs-2019).) As Dotfuscator relies on ILDasm and ILAsm, it is currently unable to handle the C# scenario illustrated here.

_Disclaimer:_ Views expressed by the author do not necessarily represent those of PreEmptive.

**Comment by mletterle** [comment]
Relevant code in `ilasm/assem.cpp`:

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/coreclr/ilasm/assem.cpp#L738

**Comment by JulieLeeMSFT** [comment]
@Joe-Sewell-PreEmptive Can you proceed with the workaround you identified? I am trying to understand if you are blocked and business impact.

**Comment by Joe-Sewell-PreEmptive** [comment]
@JulieLeeMSFT At this point no users of Dotfuscator have been affected by this issue; we noticed it with our own internal testing. So we're not blocked at this point.

Disclaimer: Views expressed by the author do not necessarily represent those of PreEmptive.

**Comment by JulieLeeMSFT** [comment]
Thanks for the info. Good that you are not blocked. I will mark it as .NET 6, but it might change to future if we can’t get to it in time.

**Comment by ayousuf23** [comment]
I can try working on this issue. I will need some instructions on how to proceed.

**Comment by JulieLeeMSFT** [comment]
Thanks @ayousuf23. Are you still available to work on this?
@briansull please help @ayousuf23 with some instruction on how to proceed.

**Comment by briansull** [comment]
@ayousuf23 You can ping me here if you need help or have any questions

**Comment by ayousuf23** [comment]
@briansull I'm not sure if I am suited to solving this issue. I'm not sure what I should modify.

**Comment by briansull** [comment]
The fix for this might be as easy as deleting the line that checks and issues the error message:

```
file: src\coreclr\ilasm\assem.cpp

assem.cpp:728:        if(fIsInterface) report->error("Entrypoint in Interface: Method '%s'\n",pszMethodName);
```

**Comment by ayousuf23** [comment]
Sorry for the late response. I don't have access to a computer where I can finish working on the issue anymore. Please unassign me.

**Comment by TIHan** [comment]
I can look into this. As @briansull said, may be as easy as removing a single line.
