### ISSUE TITLE
Backport Fix memory leak with OptionsMonitor to .NET Core 5.0

### ISSUE THREAD

**Issue by Reena-Patel** [dotnet/runtime#50008]
### Describe the bug
Memory is not getting released for the IOptionsMonitor object

### To Reproduce
Use the below code

```
 private ServiceEndpointConfiguration _serviceEndpointConfiguration;
        public ABC( IOptionsMonitor<ServiceEndpointConfiguration> serviceEndpointConfiguration) 
            
        {
            _serviceEndpointConfiguration = serviceEndpointConfiguration.CurrentValue;
            serviceEndpointConfiguration.OnChange(configuration =>
            {
                _serviceEndpointConfiguration = configuration;
            });
        }

```
apply load on this and check the memory usage.

### Expected behavior
Memory should be released for the resource.

**Comment by maryamariyan** [comment]
Closing issue due to https://github.com/dotnet/runtime/issues/50008#issuecomment-786423997. We'd need either a small repro code or a pointer to what in the above partial snippet is disposable.
