### ISSUE TITLE
Package is not compatible with netcoreapp3.1 when using MSBuild but not VS

### ISSUE THREAD

**Issue by mgwynnSymbrium** [dotnet/runtime#50012]
### Describe the bug
When using Jenkins and MSBuild to build a .NET Core 3.1 application using Systemd 5.0.1, MSBuild errors out. Building the same application locally in Visual Studio does not have the same issue.

### To Reproduce
1. Create project using Systemd
2. Build locally in Visual Studio targeting x86 and .NET Core 3.1
3. Build on Jenkins using MSBuild with the following command: 
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "..\src\CommService\CommService.csproj" /p:Configuration=Release;Platform=x86 /t:rebuild /flp1:logfile=errors.txt;errorsonly /flp2:logfile=warnings.txt;warningsonly`

### Expected behavior
Build both locally and through Jenkins

### Additional context
I have upgraded to the newest versions of the NuGet package, updated nuget.exe on my server. Here is the error from Jenkins:

"D:\Jenkins\jobs\CommService - dotnet 2.0\workspace\src\CommService\CommService.csproj : error NU1202: Package Microsoft.Extensions.Hosting.Systemd 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.Extensions.Hosting.Systemd 5.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)"

This was previously a .NET Framework 4.6.1 app that has been transferred over to Core 3.1 due to a need to be run on Linux as well as Windows. The only other thing that has been done as part of the process to get a Jenkins build working has been to put a version of MSBuild on the server that supports 3.1 and calling that instead of the older one in the command.

**Comment by ViktorHofer** [comment]
Closing as we haven't heard back from the customer. Feel free to reopen to share more details.
