### ISSUE TITLE
UseWindowsService does not generate warning CA1416 "...is supported on 'windows'" in a project targeting net5.0

### ISSUE THREAD

**Issue by Assasello** [dotnet/runtime#50013]
I have a test project targeting net5.0. 

* When I use IWebHost.RunAsService() compiler generates warning  CA1416 'WebHostWindowsServiceExtensions.RunAsService(IWebHost)' is supported on 'windows'.
* When I use IHostBuilder.UseWindowsService() compiler does not generate CA1416 warning.

**Comment by eerhardt** [comment]
cc @buyaa-n

**Comment by hwoodiwiss** [comment]
I would be interested in picking this up if someone could assign it.

**Comment by hwoodiwiss** [comment]
I've prepared a PR for this if someone wouldn't mind reviewing.
#53941
