### ISSUE TITLE
Check for direct descendant when checking for systemd

### ISSUE THREAD

**Issue by FAAAAT** [dotnet/runtime#50015]
Hello guys:

I am using generic host to create a linux service and use service config like below:

```
[Unit]
Description=

[Service]
Type=notify
ExecStart=/path/to/Start.sh
WorkingDirectory=/path/
User=root
Group=root
Restart=on-failure
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=%n
PrivateTmp=false
Environment=DOTNET_ENVIRONMENT=Production
NotifyAccess=all

[Install]
WantedBy=multi-user.target

```
and the content of start.sh as below:
```
#!/bin/sh
dotnet xxxx.dll
```

But when I start the service, the service status is always activating(start) and will failed after a few seconds. The log information shows the host is started and the main logic of this program is running.

The program is running smoothly when I run it as a console app.

**I am not sure the host send the notify to systemd or not.**

Packages Version

    PackageReference Include="Microsoft.Extensions.Hosting" Version="3.0.0"
    PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="3.0.0"
    PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.0.0"

Code in main
```
		public static IHostBuilder CreateHostBuilder(string[] args) =>
			Host.CreateDefaultBuilder(args)
				.UseWindowsService()
				.UseSystemd()
				.ConfigureServices(
					(hostContext, services) =>
					{
						services.AddHostedService<Worker>();
                        var configuration = hostContext.Configuration.GetSection("Settings");
						services.Configure<Settings>(configuration);
					});
```

-----------------------------------------------------------------------------------------------------------
I have made some investigation. I found 'UseSystemd' will check current process 'IsSystemdService'
[UseSystemd](https://github.com/dotnet/extensions/blob/f4066026ca06984b07e90e61a6390ac38152ba93/src/Hosting/Systemd/src/SystemdHostBuilderExtensions.cs)
[IsSystemdService]
(https://github.com/dotnet/extensions/blob/f4066026ca06984b07e90e61a6390ac38152ba93/src/Hosting/Systemd/src/SystemdHelpers.cs)

I followed the logic and checked my service:
Output of service status

```
● r630monitor.service - Temp monitor and fan control for R620 server
   Loaded: loaded (/etc/systemd/system/r630monitor.service; enabled; vendor preset: disabled)
   Active: activating (start) since 六 2020-06-20 15:33:37 CST; 13s ago
 Main PID: 2579 (Start.sh)
   CGroup: /system.slice/r630monitor.service
           ├─2579 /bin/sh /path/to/Start.sh
           ├─2580 dotnet xxxx.dll
           └─2661 (some others)
```

and the content of /proc/2579/comm is:

`Start.sh`

Does it means that 'IsSystemdService' will return false and 'UseSystemd' is directly returned?

**Comment by tmds** [comment]
In your startup scripts you can use `exec`:
```
#!/bin/sh
exec dotnet xxxx.dll
```
This way the script process becomes the `dotnet` process, and the systemd detection from .NET will work.

**Comment by maryamariyan** [comment]
@FAAAAT does this help resolve the issue https://github.com/dotnet/runtime/issues/50015#issuecomment-804466971
