### ISSUE TITLE
Time out issue happening while preforming scan in azure redis cache. 

### ISSUE THREAD

**Issue by dkoshy** [dotnet/runtime#50010]
### Describe the bug
Timeout performing SCAN (5000ms), next: SCAN, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 0, serverEndpoint: serverendpoint_name:6380, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXXXXXX, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

### To Reproduce
 `         

             var server = Connection.GetServer(endpoint.Host, endpoint.Port,);

            var keys = server.Keys(pattern: pattern).Take(10);
            try
            {
                resultedKeys.AddRange(keys);
            }
            catch(Exception ex)
            {

            }

`

**Comment by danmoseley** [comment]
Hi @dkoshy should this be a bug in the https://github.com/topics/azure-redis-cache repo instead?

If not, could you please share more about why you believe it's a platform bug? Including a callstack.

**Comment by joperezr** [comment]
friendly ping @dkoshy do you think you can instead open an issue on the azure-redis-cache repo as @danmoseley suggests? It doesn't look like (from the code you shared) that this is anything directly related to the framework meaning that it is likely that we wouldn't be able to investigate/fix the issue.

**Comment by joperezr** [comment]
Given this issue is not really actionable from the dotnet/runtime repo side, I'll go ahead and close this issue for now. @dkoshy feel free to reopoen if you have more info or if you disagree.
