### ISSUE TITLE
UseWindowsService() does not work on docker containers

### ISSUE THREAD

**Issue by drakeaan** [dotnet/runtime#50020]
### Describe the bug
When creating a windows service of a .NET Core 3.0/3.1 project, the service does not start if it's running inside a container.

### To Reproduce
1. Create an ASP.NET Core 3.0 Project
2. Implement the Hosting extension and add app.UseWindowsService()
3. Create a docker container (.NET Framework) and install the .net core runtime
4. Register the service and attempt to start it.

### Expected behavior
The service should start.

### Additional context
[WindowsServiceHelpers](https://github.com/aspnet/Extensions/blob/master/src/Hosting/WindowsServices/src/WindowsServiceHelpers.cs) checks if the SessionId == 0. In containers, the sessionid will never be 0.

`return parent.SessionId == 0 && string.Equals("services", parent.ProcessName, StringComparison.OrdinalIgnoreCase);`

**Comment by eerhardt** [comment]
Closing as a duplicate of https://github.com/dotnet/runtime/issues/52416. That issue has the suggested solution, so using that one going forward.
