### ISSUE TITLE
Dependency injection does not work in multiple async threads include backgroundservice

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/runtime#50027]
Hi.I have a service which I inject to my backgroundservice using Dependency Injection.In backgroundservice I have timer which works every 10 seconds and an additional method to send async request using the service I've injected.When I turn off my timer everything works fine,but I need stopless method that send async request every 10 seconds.I think this cause an deadlock or the service I've injected does not properly works inside while loop.Can anyone help me? Thanks

**Comment by davidfowl** [comment]
There isn't enough information to make progress here, we should close this until we understand more.
