### ISSUE TITLE
Guidance Needed: How to deal with logging a custom object

### ISSUE THREAD

**Issue by mhsimkin** [dotnet/runtime#50032]
Hi. 

I'm looking for some guidance. I'm working on a custom log provider that will take log messages, convert them to our internal format and place them on a queue for consumption later.

I have the provider working.

However, I'm running into an issue when I try to build a legacy interface to replace our existing logging methods. I have built ILogger extension methods that match the legacy call signatures.

Inside those methods, I'm instantiating our custom logging object, populating it's properties, and calling the ILogger:Log method.  The custom logging object has an overridden ToString() method to support any of the other installed loggers.

Is this the best way?

Would it be better to pass a KeyValuePair collection and have my custom provider instantiate and populate the custom object.  If so, how do I achieve that?

Also, when the custom logging object is populated, there are properties that need to be set, but those values are not available to the extension methods.  The values are available to the LoggerProvider.

I was looking for a way to get hold of an IServiceProvider so that I could retrieve the additional values.  I have not figured out how to do that.  I ended up creating a singleton to hold those values.  

I thought about implementing a custom ILogger<T> and ILoggerFactory class so that I can replace the existing internal Logger class with a custom internal class that would duplicate the functionality of the internal Logger class.  However, I'm not sure this is the best approach.

Thank you for your help.

-marc

**Comment by maryamariyan** [comment]
@mhsimkin are you still stuck here? It might help if you look at how we have any of our own logging providers setup, e.g. [ConsoleLoggerProvider](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs)

**Comment by mhsimkin** [comment]
@maryamariyan given that I asked this question over 18 months ago, I have already reviewed all the code in the console and debug loggers.  I found a solution that works.
