### ISSUE TITLE
ConfigureHostDefaults

### ISSUE THREAD

**Issue by Condra963** [dotnet/runtime#50039]
Hello,

I am wondering if you have ConfigureHostDefaults for a Worker Service like you have ConfigureWebHostDefaults for a ASP.Net Core Web Application?

You can use ConifugreWebHostDefaults together with UseStartup in a WorkerService but then your service starts to listen at the default ports...

```
public static void Run(string[] args)
{
    using (IHost host = Host.CreateDefaultBuilder(args)
            .UseContentRoot(Directory.GetCurrentDirectory())
            .ConfigureWebHostDefaults(webBuilder => webBuilder
            .UseStartup<TStartup>())
            .Build())
    {
        host.Run();
    }
}
```

**Comment by maryamariyan** [comment]
Closing issue as per comment https://github.com/dotnet/runtime/issues/50039#issuecomment-577878379
