### ISSUE TITLE
Regressions in System.Buffers.Tests.RentReturnArrayPoolTests<Object>

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#50046]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [e0bbfa0f555cf5b9d8b8749e1a91a78924c9d927](https://github.com/dotnet/runtime/commit/e0bbfa0f555cf5b9d8b8749e1a91a78924c9d927)
Compare | [220b01a58697eeae580d97cc47879217efd6628f](https://github.com/dotnet/runtime/commit/220b01a58697eeae580d97cc47879217efd6628f)

### Regressions in System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[MultipleSerial](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Buffers.Tests.RentReturnArrayPoolTests(Object).MultipleSerial(RentalSize%3a%204096%2c%20ManipulateArray%3a%20False%2c%20Async%3a%20False%2c%20UseSharedPool%3a%20False).html>) | 237.14 ns | 251.64 ns | 1.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-5b76717b-514d-4b58-b6bd-7a639b3e5de6d74024926b3491a9f/598797ca-d383-4d46-9518-0f86c594add2.zip?sv=2019-07-07&se=2021-04-08T20%3A01%3A52Z&sr=c&sp=rl&sig=qGeHPCt%2BH0Kq8jn0lgbUvAWE4VXmClxGNc%2FZT4fdrGA%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-89fdb32d-14e5-43e4-a9e6-4e54df5992bdf29721d0cac4d67a9/40896071-325d-4787-8a62-962e7c4dc94a.zip?sv=2019-07-07&se=2021-04-09T02%3A40%3A56Z&sr=c&sp=rl&sig=k6owFCVVXXFsn%2FBgAqxDXLWwUt2FT9aSE6cssgp8vGg%3D>)

</details>

**Comment by DrewScoggins** [comment]
https://github.com/dotnet/runtime/pull/49031 looks like it could be related.

**Comment by DrewScoggins** [comment]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [01b6a0f74db7500facdfd456a20d258204878ddf](https://github.com/dotnet/runtime/commit/01b6a0f74db7500facdfd456a20d258204878ddf)
Compare | [6919fc2cac36d5527c0750987b00462f676f1c0f](https://github.com/dotnet/runtime/commit/6919fc2cac36d5527c0750987b00462f676f1c0f)


### Regressions in System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[SingleSerial](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Buffers.Tests.RentReturnArrayPoolTests(Object).SingleSerial(RentalSize%3a%204096%2c%20ManipulateArray%3a%20False%2c%20Async%3a%20False%2c%20UseSharedPool%3a%20False).html>) | 41.09 ns | 43.65 ns | 1.06 | | |
[MultipleSerial](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Buffers.Tests.RentReturnArrayPoolTests(Object).MultipleSerial(RentalSize%3a%204096%2c%20ManipulateArray%3a%20False%2c%20Async%3a%20False%2c%20UseSharedPool%3a%20False).html>) | 335.34 ns | 359.81 ns | 1.07 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-04d98943-4c0b-498c-8d43-b5d96d165a561b745fea5ce4b6987/06a9a45d-ddb1-4cfa-b37f-b64db9624113.zip?sv=2019-07-07&se=2021-04-02T14%3A33%3A40Z&sr=c&sp=rl&sig=eHB2D%2FSiVwt%2BGIjtI9I2pxzzgqeMkUMdB911E5UQraA%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-be097576-740b-414e-9524-6e0a5c595f0fbdd697a256b495c83/9f3c487b-5d87-4358-8f34-ccf55faa2147.zip?sv=2019-07-07&se=2021-04-02T20%3A34%3A58Z&sr=c&sp=rl&sig=rWIBLUH6RzYqDuDXYpyvjJAT8gAUI4ie5UJ6ezROxJM%3D>)

### Histogram
#### System.Buffers.Tests.RentReturnArrayPoolTests<Object>.SingleSerial(RentalSize: 4096, ManipulateArray: False, Async: False, UseSharedPool: False)

```log
[40.358 ; 41.753) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[41.753 ; 43.344) | @@@
[43.344 ; 44.939) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```
#### System.Buffers.Tests.RentReturnArrayPoolTests<Object>.MultipleSerial(RentalSize: 4096, ManipulateArray: False, Async: False, UseSharedPool: False)

```log
[332.619 ; 343.416) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[343.416 ; 355.130) | @
[355.130 ; 364.079) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [01b6a0f74db7500facdfd456a20d258204878ddf](https://github.com/dotnet/runtime/commit/01b6a0f74db7500facdfd456a20d258204878ddf)
Compare | [6919fc2cac36d5527c0750987b00462f676f1c0f](https://github.com/dotnet/runtime/commit/6919fc2cac36d5527c0750987b00462f676f1c0f)


### Regressions in System.Memory.Span&lt;Char&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[BinarySearch](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Memory.Span(Char).BinarySearch(Size%3a%20512).html>) | 16.45 ns | 19.14 ns | 1.16 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Memory.Span(Char)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Memory.Span(Char).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Memory.Span&lt;Char&gt;*'
```
<details>

**Comment by stephentoub** [comment]
Regression no longer shows up in the lab.  Closing.
