### ISSUE TITLE
Assembly binding fail when the executable is in %programfiles%

### ISSUE THREAD

**Issue by Echtelion** [dotnet/runtime#50043]
### Describe the bug
My 4.6.1 winform app reference some .net std lib, and they all reference Logging Abstractions.
When I run the app from the bin/release folder, everything work fine.
If I move this folder to programfiles, it doesn't start, and fail with a fuslog exception for this package. It work if I run the same executable in administrator mode...

The .NET executable.exe.config has a bindingredirect to the 3.1.3 version of all Microsoft.Extensions packages. The dll is well present in the output folder, while with a strange number... 
ilspy show : Microsoft.Extensions.Logging.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
While product properties show file = 3.100.320.12802 and product = 3.1.3+7d(...)

I am unable to reproduce the issue with a simple app. But here is a repro which show the difference of assembly binding between <project>/bin/debug and %programfiles%/existing/app

### To Reproduce
Create a console 4.6.1 solution, add reference to nuget logging.console and dependencies.
Add a netstd2.0 project, add reference to nuget logging.abstractions, reference it from the console app
Add in program.cs/Main : 
 ```
var logger = LoggerFactory.Create(c => c.AddConsole());
Class1 lib = new Class1(logger);
Console.ReadLine();
```
Add a ctor in class1.cs : 
 ```
public Class1(ILoggerFactory factory) { factory.CreateLogger<Class1>().LogWarning("class1 started"); }
```

Run the console app : work in the debug output. 
copy output files to programfiles and run it : fail when loading "System.Threading.Tasks.Extensions"

In this repro, adding a reference to the nuget System.Threading.Tasks.Extensions for the executable is enough to solve the issue. But I still have no idea why the binding change from a directory to another.

I joined the above repro, and the fuslogvw error for my app (sorry, in french)

[ConsoleFwApp.zip](https://github.com/dotnet/extensions/files/4569401/ConsoleFwApp.zip)

[Microsoft.Extensions.Logging.Abstractions, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60.HTM.zip](https://github.com/dotnet/extensions/files/4569397/Microsoft.Extensions.Logging.Abstractions.Version.3.1.0.0.Culture.neutral.PublicKeyToken.adb9793829ddae60.HTM.zip)

**Comment by davidwrighton** [comment]
Closing as  @echtelion has not responded in quite some time, and there is no actionable problem that we can solve without more details.
