### ISSUE TITLE
Building with allConfigurations on Linux fails on System.Speech

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#50060]
When I build on Linux with:

```shell
./build.sh -s clr+libs -rc release -allConfigurations
```

I get 12 build errors, all regarding System.Speech:

> CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/SrgsCompiler/SrgsCompiler.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]

<details>
<summary>All errors</summary>
<pre>
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/SrgsCompiler/SrgsCompiler.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/ISsmlParser.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/SsmlParser.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsEngineProxy.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsEvent.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsVoice.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/SrgsCompiler/SrgsCompiler.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/ISsmlParser.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/SsmlParser.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsEngineProxy.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsEvent.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
CSC : error CS2001: Source file '/code/personal/dotnet/runtime/src/libraries/System.Speech/src/Internal/Synthesis/TtsVoice.cs' could not be found. [/code/personal/dotnet/runtime/src/libraries/System.Speech/src/System.Speech.csproj]
    0 Warning(s)
    12 Error(s)
</pre>
</details>

Is this expected?

**Comment by ViktorHofer** [comment]
The casing of these files is wrong. Will send a quick fix.
