### ISSUE TITLE
Allow value converters (JsonConverter<T>) to handle dictionary keys

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#50071]
This is a placeholder issue to expose the internal `JsonSerializer` mechanism for supporting non-string primitives as dictionary keys. This will allow custom (user-provided) converters to handle them. This involves making these two virtual methods `public`:

https://github.com/dotnet/runtime/blob/cbc6aa617b93ee8bed1b1779fe26530d1f7a390b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L542-L546

**Comment by Jozkee** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/46520?

**Comment by layomia** [comment]
Yes, thanks @Jozkee.
