### ISSUE TITLE
Question: Reading log levels from appsettings.json in custom logger implementation

### ISSUE THREAD

**Issue by joejoe87577** [dotnet/runtime#50089]
I'm writing a custom logger implementing the `ILogger` interface, I've been basically copying the necessary methods and implementations from the `ConsoleLogger ` implementation.
The only issue remaining right now is the `LogLevel`, the settings I've put into the `appsettings.json` gets ignored when adding the `OptionsMonitor` with `IServiceCollection.Configure`. All the other settings for this specific area are read and updated fine, only the implementation of the log level is casusing problems.

I've added a this to my appsettings:
```JSON
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "EventJobLog": {
      "LogLevel": {
        "Default": "Information"
      },
      "ConnectionString": "[...]", 
      "UseDbConsole": true,
      "UseDbTable": false
    }
  }
```

The values for `ConnectionString`, `UseDbConsole` and `UseDbTable` are read just fine.

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
	Host.CreateDefaultBuilder(args)
		.ConfigureLogging((hostContext, loggerFactory) =>
		{
			loggerFactory.AddEventJobLogLogger();
		})
		.ConfigureServices((hostContext, services) =>
		{
			services.Configure<EventJobLogLoggerOptions>(hostContext.Configuration.GetSection(EventJobLogLoggerOptions.Name));
			// Code removed...
		});
```

And are also updated at runtime thanks to the reload Token in my logger implementation

```C#
[ProviderAlias("EventJobLogLogger")]
public class EventJobLogLoggerProvider : ILoggerProvider
{
	private readonly IOptionsMonitor<EventJobLogLoggerOptions> _options;
	private readonly IDisposable _optionsReloadToken;
	private readonly ConcurrentDictionary<String, EventJobLogLogger> _loggers = new ConcurrentDictionary<String, EventJobLogLogger>();

	public EventJobLogLoggerProvider(IOptionsMonitor<EventJobLogLoggerOptions> options)
	{
		this._options = options;
		this._optionsReloadToken = _options.OnChange(ReloadLoggerOptions);
	}

	public ILogger CreateLogger(String categoryName) => _loggers.GetOrAdd(categoryName, name => new EventJobLogLogger(name, _options.CurrentValue));

	public void Dispose()
	{
		_loggers.Clear();
		_optionsReloadToken.Dispose();
	}

	private void ReloadLoggerOptions(EventJobLogLoggerOptions configuration)
	{
		foreach (KeyValuePair<String, EventJobLogLogger> logger in _loggers)
		{
			logger.Value.Options = configuration;
		}
	}
}
```

I've added the `EventJobLoggerOptions` as simple POCO object

```C#
public class EventJobLogLoggerOptions
{
	public const String Name = "Logging:EventJobLog";

	public int EventId { get; set; }
	public LogLevel LogLevel { get; set; } = LogLevel.Warning;

	public String ConnectionString { get; set; }

	public String Werk { get; set; }

	public Boolean UseDbConsole { get; set; } = true;

	public Boolean UseDbTable { get; set; } = true;
}
```

Now in my implementation of the `EventJobLogLogger`

```C#
public class EventJobLogLogger : ILogger
{
	private readonly String _name;

	internal EventJobLogLoggerOptions Options;

	public EventJobLogLogger(String name, EventJobLogLoggerOptions config)
	{
		this._name = name;
		this.Options = config;
	}

	public IDisposable BeginScope<TState>(TState state) => default;
	public Boolean IsEnabled(LogLevel logLevel) => logLevel >= Options.LogLevel;
	public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, String> formatter)
	{
		if (!IsEnabled(logLevel))
			return;
		if (Options.UseDbTable || Options.UseDbConsole)
		{
			if (Options.UseDbTable)
				// Code removed...
			if (Options.UseDbConsole)
				// Code removed...
		}
	}
}
```

The `LogLevel` inside the `EventJobLogLoggerOptions ` is always the default value set in the `EventJobLogLoggerOptions`, while the other values are read and reloaded correctly.

Am I missing something here?

**Comment by maryamariyan** [comment]
> The only issue remaining right now is the LogLevel, the settings I've put into the appsettings.json gets ignored when adding the OptionsMonitor with IServiceCollection.Configure. All the other settings for this specific area are read and updated fine, only the implementation of the log level is casusing problems.

It's a bit hard to tell by just looking at the above snippets what is wrong :)
Are you seeing issues when reloading? or even the initial load is ignoring the log level?

**Comment by joejoe87577** [comment]
The issue happens is there on the inital load and reloading the settings with the `ReloadLoggerOptions` method. Curiously I couldn't find the implementation of the logLevels in the [ConsoleLoggerOptions](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerOptions.cs), I've basically copied and modified the rest of my code from the ConsoleLogger.

**Comment by maryamariyan** [comment]
In case that matters for your custom implementation, note that `ConsoleLoggeOptions` is actually deprecated. We actually use XConsoleFormatterOptions (e.g. checkout [SimpleConsoleFormatterOptions](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatterOptions.cs) and its usage)

HTH.
