### ISSUE TITLE
ReadFile experiment

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#50087]
The following comment from the Legacy implementation of `FileStream`:

https://github.com/dotnet/runtime/blob/010cbfe57608435948e41f59f0353ce1f7d4132d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/LegacyFileStreamStrategy.Windows.cs#L707-L708

tells us that Windows might turn small async reads into sync reads.

However, another comment tells us that it's impossible to use the number of bytes returned by `ReadFile`:

https://github.com/dotnet/runtime/blob/010cbfe57608435948e41f59f0353ce1f7d4132d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/LegacyFileStreamStrategy.Windows.cs#L856-L862

The official [doc](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile#synchronization-and-file-position) does not make it clear:

> ReadFile may return before the read operation is complete. In this scenario, ReadFile returns FALSE and the GetLastError function returns ERROR_IO_PENDING, which allows the calling process to continue while the system completes the read operation.

The goal of this issue is to verify whether we can use the number of bytes returned in such cases.

If something has changed and we can use it reliably, we should add an allocation-free code path that would be just returning a `ValueTask<int>(result)`. It's important as the default buffer size is just 4k, so in theory, it would be a very frequently used code path (fingers crossed).

The experiment could start with a quick validation of what Windows returns for very small reads, which could be done by running the following code:

<details>

```cs
const int fileSize = 10000;
const int userBufferSize = 1;
string filePath = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
File.WriteAllBytes(filePath, Enumerable.Range(0, fileSize).Select(i => (byte)i).ToArray());

try
{
    Memory<byte> userBuffer = new Memory<byte>(new byte[userBufferSize]);
    long bytesRead = 0;
    using (FileStream fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, 
        bufferSize: 1 /* disable buffering */, useAsync: true))
    {
        while (bytesRead < fileSize)
        {
            bytesRead += await fileStream.ReadAsync(userBuffer, CancellationToken.None);
        }
    }
}
finally
{
    File.Delete(filePath);
}
```

</details>

And using a debugger to see what gets returned [here](https://github.com/dotnet/runtime/blob/010cbfe57608435948e41f59f0353ce1f7d4132d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/FileStreamHelpers.Windows.cs#L345).

Then we could test different values of `userBufferSize` and if it seems that our assumptions are right, talk to the Windows Team and verify our assumptions and validate [this](https://github.com/dotnet/runtime/blob/010cbfe57608435948e41f59f0353ce1f7d4132d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/AsyncWindowsFileStreamStrategy.cs#L224-L230) comment.

If the experiment fails the issue should just be closed with an explanation.

**Comment by hypeartist** [comment]
@adamsitnik https://stackoverflow.com/a/30922414/13340257 ?

**Comment by adamsitnik** [comment]
> https://stackoverflow.com/a/30922414/13340257 

@hypeartist I am afraid that it does not help

**Comment by Jozkee** [comment]
After running a quick test similar to the one specified in the issue description, it noticed that [ReadFile](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile) returns zero (unsuccessful) even if we signal the function to only read 1 byte. 

Therefore, I don't think the comment in here is correct at all, we should consider removing it.
https://github.com/dotnet/runtime/blob/010cbfe57608435948e41f59f0353ce1f7d4132d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/LegacyFileStreamStrategy.Windows.cs#L707-L708

With that said, I'm closing this issue.
