### ISSUE TITLE
Make string.Remove(length of string) not throw but return this instead

### ISSUE THREAD

**Issue by jmairboeck** [dotnet/runtime#50094]
## Background and Motivation

Currently, for example, string.Remove(5) for a string of length 5 throws. For consistency with the other overload of Remove, as well as Substring, this should be changed to not throw but return the unmodified string instead.

The documentation should also be changed or clarified accordingly.

## Proposed API

Change the following in String.Remove(int):
```diff
        public string Remove(int startIndex)
        {
            if (startIndex < 0)
                throw new ArgumentOutOfRangeException(nameof(startIndex), SR.ArgumentOutOfRange_StartIndex);

-            if (startIndex >= Length)
+           if (startIndex > Length)
                throw new ArgumentOutOfRangeException(nameof(startIndex), SR.ArgumentOutOfRange_StartIndexLessThanLength);

            return Substring(0, startIndex);
        }
```
## Usage Examples

``` C#
var str = "abcd";
var test = str.Remove(4);
Debug.Assert(str == test);
```
should not throw an exception.

## Alternative Designs

none

## Risks

One could theoretically depend on the exception being thrown.

**Comment by stephentoub** [comment]
This seems like a design bug we should just fix.
