### ISSUE TITLE
`PriorityQueue` keeps node in memory when dequeued

### ISSUE THREAD

**Issue by alaatm** [dotnet/runtime#50114]
When the queue contains only one node, calling `Dequeue()` will keep a reference to that node.

```
class C {}

var pq = new PriorityQueue<C, int>();
pq.Enqueue(new C(), 0);
pq.Dequeue();

/*
At this point, pq._nodes[0] will still reference the enqueued object.
*/
```

The reference is cleared [here](https://github.com/dotnet/runtime/blob/f000c7db837f3455d107a3bf1503b523675292e7/src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs#L564) but then put back by `MoveDown*()`

ver: .net6 preview 2

**Comment by eiriktsarpalis** [comment]
Thank you for reporting the issue @alaatm!
