### ISSUE TITLE
What does "RuntimeFlavor" means?

### ISSUE THREAD

**Issue by Maniues** [dotnet/runtime#50123]
What does RuntimeFlavor mean in your build infrastructure?

**Comment by danmoseley** [comment]
Hi @Maniues , there is some help here from `build -?`:

```
  -runtimeFlavor (-rf)           Runtime flavor: CoreCLR or Mono.
                                 [Default: CoreCLR]
```
does that answer your question?

**Comment by Maniues** [comment]
> Hi @Maniues , there is some help here from `build -?`:
> 
> ```
>   -runtimeFlavor (-rf)           Runtime flavor: CoreCLR or Mono.
>                                  [Default: CoreCLR]
> ```
> 
> does that answer your question?

Does this make me use mono inside the dotnet / runtime CLI?

**Comment by danmoseley** [comment]
I actually don't know that. @steveisok ?

**Comment by directhex** [comment]
No. Passing runtimeFlavour lets you force specific behaviour inside certain subsets, for cases where the flavour cannot be inferred from the arch/os (e.g. `--subset packs.product` for linux-x64 needs to behave differently for coreclr vs mono runtime)

**Comment by Maniues** [comment]
Thanks for @danmoseley and @directhex for your answer.
Continuation of the thread in https://github.com/dotnet/runtime/issues/50128
