### ISSUE TITLE
Use R2RDump to validate that the set of methods compiled with CG2 matches CG1

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#50124]
We should double-check that Crossgen1 and Crossgen2 compile basically the same sets of methods and / or identify the remaining gaps. It would be ideal to add this to R2RDump --diff mode and probably run it over the framework assemblies.

/cc @dotnet/crossgen-contrib

**Comment by trylek** [comment]
@cshung for additional feedback towards the design here - we may be able to make this an automated CI test which would be super useful for long-term monitoring.

**Comment by cshung** [comment]
For the CI test part, I highly recommend not having to launch `R2RDump` as a process (as I did [here](https://github.com/dotnet/runtime/blob/cb4802635aefaf3963a994b668e77467c512bdeb/src/tests/readytorun/r2rdump/FrameworkTests/R2RDumpTester.cs#L51)). 

With the [ILCompiler.Reflection.ReadyToRun](https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun) library I [extracted](https://github.com/dotnet/runtime/pull/267) from `R2RDump`, we should be able to write pure C# tests to compare between two lists of signatures easily.

Here are a couple of blog posts I wrote talking about how to do exactly that.

- [Introduction to ILCompiler.Reflection.ReadyToRun](https://cshung.github.io/posts/introduction-to-ilcompiler-reflection-readytorun/)
- [Hello Reflection](https://cshung.github.io/posts/hello-reflection/) 

You can also just check out the really simple sample code [here](https://github.com/cshung/blog-samples/blob/master/HelloReflection/Program.cs).

*Feel free to ignore the part when I mention my personal feed in Hello Reflection, the library is available right at the build of the runtime repo*

**Comment by MichalStrehovsky** [comment]
> make this an automated CI test which would be super useful for long-term monitoring.

Do we plan to keep maintaining the old crossgen long term (past .NET 6)?

(There's cost in keeping it around - https://github.com/dotnet/runtime/commits/main/src/coreclr/zap - we're doing ~3 commits per month in the zap directory alone to keep it chugging along.)

**Comment by trylek** [comment]
AFAIK the current plan is to officially stop support for Crossgen1 but keep it around for .NET 6 in some form as an emergency option for customers potentially hitting issues with Crossgen2; my assumption is that the CG1 code will get physically deleted in .NET 7.

**Comment by trylek** [comment]
This is no longer actionable as the legacy Crossgen1 has been deleted from the CoreCLR source tree. These days we're analyzing Crossgen2 runtime performance autonomously.
