### ISSUE TITLE
Possible storage leak in nethost.cpp

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#50146]
A static analyzer has pointed out that there's this possible storage leak in nethost.cpp. I am not too familiar with this code, can someone please take a look?

https://github.com/dotnet/runtime/blob/aab9aa663d73e8c43bdc89fa72378e337cdd9c9e/src/native/corehost/nethost/nethost.cpp#L38-L67

We allocate `fxr` and `fxr_path`, They get initialized by calls to `fxr_resolver::try_get_existing_fxr`. If the buffer causes us an issue and we return `return StatusCode::HostApiBufferTooSmall`, `fxr`/`fxr_path` go out of scope. We may not be cleaning up the memory referenced by`fxr` and `fxr_path`?

**Comment by VSadov** [comment]
`string_t` is basically `std::string`  (or `std::wstring` on WIN32) . When it goes out of scope its destructor should do any cleanup that is necessary. 
Is that not happening here?

**Comment by vitek-karas** [comment]
Can you share the message from the static analyzer?

I don't see any problem in the code. The `fxr` is a module handle, but it will only ever contain the handle of already loaded library. On Windows we use `GetModuleHandle` which doesn't increment ref count, so there's nothing to leak. I don't know if there's any refcounting on Linux. Also the way we do this on Linux/Mac is pretty complicated, but in general we call `dlopen(..., RTLD_NOLOAD)`, if this increases a refcount on the return handle (if that's a thing on Linux) then we might be leaking that.

I agree with @VSadov that there should be no issues around strings.

**Comment by omajid** [comment]
This is the message from the analyzer:

```
Error: RESOURCE_LEAK (CWE-772): [#def2]
dotnet-v3.1.112-SDK/src/core-setup.0267ad09c6f2e2a37b23b7d230ffbf9e787dd388/src/corehost/cli/nethost/nethost.cpp:41: alloc_arg: "try_get_existing_fxr" allocates memory that is stored into "fxr".
dotnet-v3.1.112-SDK/src/core-setup.0267ad09c6f2e2a37b23b7d230ffbf9e787dd388/src/corehost/cli/nethost/nethost.cpp:68: leaked_storage: Variable "fxr" going out of scope leaks the storage it points to.
#   66|       *buffer_size = required_size;
#   67|       if (buffer == nullptr || input_buffer_size < required_size)
#   68|->         return StatusCode::HostApiBufferTooSmall;
#   69|   
#   70|       fxr_path.copy(buffer, len);
```

It could very well be a false positive.

**Comment by vitek-karas** [comment]
It seems that `dlopen` requires a matching `dlclose`, which will not happen in all cases here, so I guess this is a real leak.

**Comment by omajid** [comment]
Hm. I wonder if we fixed that already via https://github.com/dotnet/runtime/pull/47487

The static analyzer was looking at 3.1.112, not main.

**Comment by vitek-karas** [comment]
I don't think it fixed all of it. If `hostfxr` was found in the process the function returns the valid handle, so it's the responsibility of the caller to close it - which nethost doesn't.

**Comment by agocke** [comment]
I think the analyzer is incorrect here -- `dlclose` is a potentially dangerous optimization if anything has taken a pointer into the target, and there's no real way to ensure that that hasn't happened. I don't want to make such a change based purely on a static analysis tool. We should decide when to `dlclose` only as a matter of architecture.
