### ISSUE TITLE
Where is a list of classes that are in the Core runtime, vs. that are now in Nuget packages?

### ISSUE THREAD

**Issue by Dean-NC** [dotnet/runtime#50187]
For those of us who've coded in .Net Framework for many years, and are now just coming to .Net 5, it would be very helpful to see a list of runtime/framework classes that are still in "core", vs. those that have been moved to Nuget packages.  ...and without having to browse all around in Github, especially since the source for a lot of the classes are spread over many different folders.

I've searched quite a bit in the VStudio blogs, and on the Internet, but can't find a list.

It's frustrating to create a Visual Studio project targeting .Net 5, and find out that VS doesn't understand certain things, then after hunting around, you find that what you typed is not part of core .Net, but is now a Nuget package.

Thanks.

**Comment by MagicAndre1981** [comment]
Go to APIsof.net and search for your type.

If it shows in green it is an inbox class, if yellow it is nuget and has a link to the nuget page

Here in sample of [System.Data.Common](https://apisof.net/catalog/03ab2fb0-c3f0-6037-a195-d971e69674f0?fx=netcoreapp2.0) shows as inbox since .net core 2.0 and as nuget for older .net core versions.

![image](https://user-images.githubusercontent.com/8274816/112356909-552c0800-8ccf-11eb-90d1-47a41f08814d.png)

**Comment by huoyaoyuan** [comment]
Referencing the nuget package `Microsoft.Windows.Compatibility` will bring you all (should be all) the packages which are previously inbox and still compatible now.

**Comment by Dean-NC** [comment]
@huoyaoyuan  Thanks. I had seen that, and it's good to know, but I did also want to know what's where.

@MagicAndre1981 Thanks, this site looks good.  If it's accurate, it should be mentioned in the "What's New" documentation page for .Net 5, and also in any "migration" doc for classic Framework.

It doesn't look accurate: **_System.Diagnostics.EventLog_** shows for both 5.0 and 5.0-windows, but It's not part of the core 5.0 runtime.  It's Nuget.  Also, 5.0-windows is a "target", not a runtime, so that's confusing.  Using 5.0-windows as a target means you can prevent CA1416 warnings about cross-platform, but doesn't mean you can use _System.Diagnostics.EventLog_ without adding the Nuget package.

**Comment by joperezr** [comment]
Apisof.net is defenitely a good place to go, but if you are more interested on whether or not a specific assembly on this repo is part of the shared framework (ships with .NET Core) or an OOB (ships as a separate nuget package) you can take a look at this list which has all of the contents of the libraries that exist on the shared framework:

https://github.com/dotnet/runtime/blob/4581290e1b608e08ff628cceb6de2f3365a9912d/src/libraries/NetCoreAppLibrary.props#L4-L147

**Comment by joperezr** [comment]
Given the question here has been responded to, I'll go ahead and close the issue for housekeeping issues for now, but feel free to reopen in case you have any follow up questions.

**Comment by Dean-NC** [comment]
@joperezr Thanks!  This is what I was looking for.
