### ISSUE TITLE
Investigate removing MacOS entitlements on the dotnet host

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#50185]
Investigate if these dotnet host current entitlements are necessary:
 
com.apple.security.cs.allow-unsigned-executable-memory
com.apple.security.cs.allow-dyld-environment-variables
 
https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/entitlements.plist

There will be testing and investigation to make sure removing them doesn't break anything.

Oded Hanson:

We only needed com.apple.security.cs.allow-jit but,  indeed the process doesn't inherit the default DYLIB search paths and we need to manually add :/usr/local/lib:/usr/lib to the NATIVE_DLL_SEARCH_DIRECTORIES. I guess com.apple.security.cs.allow-dyld-environment-variables would have solved that, instead of adding the paths explicitly.

**Comment by akoeplinger** [comment]
`com.apple.security.cs.allow-unsigned-executable-memory` was done by https://github.com/dotnet/runtime/pull/51294

**Comment by agocke** [comment]
I think this is done. https://github.com/dotnet/runtime/pull/51294 closed out the only change we'd likely make here.
