### ISSUE TITLE
[WASM] Major size regression in dotnet.wasm

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#50210]
I'm seeing a 40KB regression on https://aka.ms/dotnetperfstatus:

![image](https://user-images.githubusercontent.com/8291187/112390071-bc43bf80-8cc3-11eb-99e5-8f4bed5a8b94.png)

Which all appears to be in the `dotnet.wasm` file:

![image](https://user-images.githubusercontent.com/8291187/112390122-cfef2600-8cc3-11eb-8bb1-57b33588cf61.png)

It went from `782,610` bytes on aab9aa663d73e8c43bdc to `824,698` bytes on 8dd8a4317dea158.

There were 2 changes that went in during that range, both of them could be possibilities:

* https://github.com/dotnet/runtime/pull/48931
* https://github.com/dotnet/runtime/pull/50132

cc @mattjohnsonpint @lewing @CoffeeFlux

**Comment by lewing** [comment]
@eerhardt pretty sure it was https://github.com/dotnet/runtime/pull/48931

**Comment by mattjohnsonpint** [comment]
I can look into it.  Curious what amount of increase is acceptable, and what should I be looking to optimize? Is it just total number of instructions?  There were a few strings and string arrays added as well. We had some discussion on that PR about whether a simple string array is better or worse than searching through one big string - not sure if either would have a size difference for wasm.

**Comment by mattjohnsonpint** [comment]
Just to double check - we don't have ICU in the browser, right?  I don't believe that is possible, but want to confirm.

Assuming not - I think it might be a good idea to have a `TimeZoneInfo.Browser.cs` split out from `TimeZoneInfo.Unix.cs` with only the parts needed for the browser.  That should trim down the size considerably.

**Comment by lewing** [comment]
we have icu in the browser

**Comment by mattjohnsonpint** [comment]
Does it pass through to ICU used *by* the browser somehow? Or we are bundling it in the wasm ourself?

**Comment by lewing** [comment]
we bundle icu and a filtered set of data

**Comment by mattjohnsonpint** [comment]
Ok.  I'll see what else I can think of.

**Comment by mattjohnsonpint** [comment]
Actually, since it appears we're only using the IANA ID and abbreviation for the time zone display names, it still makes sense to me to conditionally build TimeZoneInfo to trim out the ICU bits.  Unless we are including time zone display names in the ICU data, but I don't think we are since the current tests show otherwise.

**Comment by lewing** [comment]
That is definitely an option.  It's also possible that we can just hide a the new logic behind a feature flag that the illinker understands and we can break the reference chain.

**Comment by EgorBo** [comment]
From my understanding, all ICU data files for Browser currently strip everything related to timezones (including names for them), e.g.: https://github.com/dotnet/icu/blob/maint/maint-67/icu-filters/icudt.json#L198-L199

so all of those ICU functions must be linked out

**Comment by mattjohnsonpint** [comment]
Working on this.  Got a local wasm build going and doing some before/after size comparisons per @eerhardt's [instructions](https://github.com/dotnet/runtime/pull/49373#issuecomment-795970949).  I'll report back shortly.

**Comment by eerhardt** [comment]
With the latest runs on https://aka.ms/dotnetperfstatus, I can confirm this is now fixed, and we are now slightly lower than the size before the regression came in:

![image](https://user-images.githubusercontent.com/8291187/113162830-3b298280-9205-11eb-8a3c-9596f0e6959f.png)

Thanks again @mattjohnsonpint!

**Comment by mattjohnsonpint** [comment]
Glad to help!
