### ISSUE TITLE
Type.IsAssignableTo(Type) Method documentation issue

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#50221]
### Description

On https://docs.microsoft.com/en-us/dotnet/api/system.type.isassignableto?view=net-5.0 it says (in the returns section) the following:

`false` if none of these conditions are true, or if `targetType` or `this` is `null`.

This is a new API to .NET 5, and the documentation is incorrect as it will not return false if the `this` object is null, it will throw a `System.NullReferenceException` since it's an instance method, not an extension method.
I've tested this with .NET 6.0.100-preview.2.21158.2 and it should have the same result on other versions.

Code to reproduce:
```cs
((Type)null).IsAssignableTo(null)
```

**Comment by danmoseley** [comment]
@hamarb123 in case you're not aware, if you're interested you can offer a PR at https://github.com/dotnet/dotnet-api-docs

Right now most API docs are generated from that repo - although an increasing number will be generated from the code in this repo.

**Comment by hamarb123** [comment]
If I make a PR, what should I change it to?
Would it just be: `false` if none of these conditions are true, or if `targetType` is `null`.
