### ISSUE TITLE
iOS/MonoVM: waiting doesn't wait

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#50245]
### Description

WaitHandles don't seem to wait.

Repo:

```csharp
var t = new AutoResetEvent (false);
var rv = t.WaitOne (30000);
Console.WriteLine (rv);
```

this finishes immediately, printing `false`.

This happens in the iOS simulator (it does not happen on macOS)

### Regression?

Yes, it regressed between `6.0.100-preview.3.21161.23` and `6.0.100-preview.3.21172.2`.

CC @CoffeeFlux.

**Comment by CoffeeFlux** [comment]
This is likely the result of my threading changes, but just to confirm: this is without AOT? How urgent is the thing this is blocking? Wondering if I should tackle this ASAP or if waiting for next sprint is fine.

**Comment by spouliot** [comment]
@CoffeeFlux afaik this was seen on bots and those are not AOT, just the JIT. However it might happens on both...

>  is the thing this is blocking?

We'll not be updating dotnet runtime P3 builds until this is solved. So this blocks any new features (e.g. ICU) from reaching customers for P3.

**Comment by jkotas** [comment]
If it helps, this is most likely caused by the defines in this file being misconfigured for iOS: https://github.com/dotnet/runtime/blob/main/src/libraries/Native/Unix/System.Native/pal_threading.c#L64

**Comment by filipnavara** [comment]
Good point, old mono/mono used to manually undef HAVE_CLOCK_MONOTONIC because it was available only on iOS 10+. I thought the minimum iOS version was bumped but not sure to which exact version and whether is this was tested on new enough simulator.

**Comment by CoffeeFlux** [comment]
I assume it's those defines, yeah, but I thought I was careful to get them right for iOS :(

At least now I can test in the simulator without too much trouble, so I'll get something working.

**Comment by steveisok** [comment]
`System.Threading.ThreadPool` and `System.Threading.Timer` suites are routinely crashing.  Going to skip them for now.  Give them a run once this issue is fixed.
