### ISSUE TITLE
Is there plan to publish System.Collections.PriorityQueue as nuget package to backfill runtime prior to net6?

### ISSUE THREAD

**Issue by hanabi1224** [dotnet/runtime#50261]
That would be super useful, thanks!

**Comment by danmoseley** [comment]
@hanabi1224 would copy/paste into your project suffice for you until .NET 6 ships?

**Comment by hanabi1224** [comment]
@danmoseley I think so but my question is mainly on how to leverage this great feature in older runtimes? Will it be part of net standard API after net6 ship? Otherwise it will be a common need to have a backfill NuGet package, does that make sense?

**Comment by danmoseley** [comment]
.NET Standard is essentially a fixed point: there is no plan currently for a new version of it.

We do have https://www.nuget.org/packages/Microsoft.Experimental.Collections but no plans to update that either. Perhaps you yourself could publish it in a package, but please change the namespace to avoid confusion?

**Comment by eiriktsarpalis** [comment]
To my knowledge we don't ship NuGet packages containing individual classes; in this case the containing assembly is System.Collections which is part of the shared framework. Realistically it's unlikely we would ever do this.

The nuget ecosystem is full of [lovely PriorityQueue implementations](https://www.nuget.org/packages?q=PriorityQueue), I would recommend trying out one of those first and supporting their authors. Alternatively you could do what @danmoseley suggested, and publish a forked version of the .NET 6 priority queue.
