### ISSUE TITLE
[wasm] Reduce amount of exception filtering in code reached from Blazor template

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#50281]
Exception filtering on wasm is slow, because we cannot unwind stack and thus need to switch from AOT to interpreter for parts of the code.

Try to reduce amount of exception filtering in parts of our libraries, which are used in Blazor template. In the linked assemblies we have currently 9 filter blocks:

```
Microsoft.Extensions.DependencyInjection.dll.dis.txt:      IL_0033:  endfilter
System.Net.Http.dll.dis.txt:      IL_0058:  endfilter
System.Private.CoreLib.dll.dis.txt:      IL_0048:  endfilter
System.Private.CoreLib.dll.dis.txt:      IL_0079:  endfilter
System.Private.CoreLib.dll.dis.txt:        IL_00e1:  endfilter
System.Private.CoreLib.dll.dis.txt:        IL_0042:  endfilter
System.Text.Json.dll.dis.txt:      IL_0148:  endfilter
System.Text.Json.dll.dis.txt:      IL_0183:  endfilter
System.Text.Json.dll.dis.txt:      IL_002e:  endfilter
```

**Comment by stephentoub** [comment]
This was discussed here:
https://github.com/dotnet/runtime/pull/47197#issuecomment-781722225

**Comment by ilonatommy** [comment]
@radekdoulik, do we still plan to remove the filters in the light of @jkotas and @stephentoub arguments?
