### ISSUE TITLE
Cannot run simple hello world console app on Apple Silicon

### ISSUE THREAD

**Issue by bintr33** [dotnet/runtime#50319]
Created a 'Console' app using VS 2019 Community for Mac, select .Net 6.0
See below error on starting to debug - 

Failed to load Q, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-preview.2.21154.6/libhostfxr.dylib failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

**Comment by vitek-karas** [comment]
@sdmaclea 
I assume you have both .NET 5 or .NET 3.1 x64 and the .NET 6 arm64 preview installed, right?

We currently don't support installing the .NET 6 ARM64 preview side-by-side with any of the X64 releases (5, 3.1, ...).
Similar issue: https://github.com/dotnet/runtime/issues/48068

**Comment by bintr33** [comment]
I did. Thanks for pointing that out.
I used the dotnet-core-uninstall tool to remove them.

Below is the output after removing old ones. Now I get this error
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c

% ./dotnet-core-uninstall list


This tool cannot uninstall versions of the runtime or SDK that are
installed using zip/scripts. The versions that can be uninstalled with this
tool are:


.NET Core SDKs:

  6.0.100-preview.2.21155.3  (x64)  [Cannot uninstall version 6.0.0 and
above]


.NET Core Runtimes:

  6.0.0-preview.2.21154.6  (x64)  [Used by Visual Studio for Mac or SDKs.
Specify individually or use —-force to remove]

**Comment by vitek-karas** [comment]
I don't think 6.0 arm64 will work with VS for Mac right now (it's still pretty new).
For now I would suggest to keep the global install as x64 (in which case 5.0 and 3.1 should also work just fine if you need to install them).

If you want to try 6.0 arm64 previews, do it in a private install - download the zip, unzip it to some custom location. Running `dotnet` from there will use the arm64 install. If you want to run apps with it, run them either via `dotnet app.dll`, or set `DOTNET_ROOT` env. variable to the custom location and them run the app via its executable.

**Comment by bintr33** [comment]
Ok. but it also does not work with VSCode with C#
I only have below *v6 preview 2* sdk/runtime on my M1 Mac.  Are you saying that with this config, both VSCode and VS for Mac are not expected to allow debugging abilities for now?


dotnet --list-sdks
6.0.100-preview.2.21155.3 [/usr/local/share/dotnet/sdk

dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by vitek-karas** [comment]
@sdmaclea  should know when/how the debugger support for osx-arm64 support is going to be available. I don't think it's in Preview 2, but I could be wrong.

I also don't know if osx-x64 will work - but it probably has a much higher chance - so if you uninstall the arm64 and install x64 version - I would expect debuggers to work.

**Comment by bintr33** [comment]
Thanks a lot @vitek-karas Your x64 suggestion worked.
For ref:
[x64](https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-6.0.100-preview.2-macos-x64-installer) // [directlink](https://download.visualstudio.microsoft.com/download/pr/5e10dc75-294e-49f4-972e-218ae86191a3/e46d3533c30c8a864252a334820263a9/dotnet-sdk-6.0.100-preview.2.21155.3-osx-x64.pkg)



 % dotnet --list-sdks
6.0.100-preview.2.21155.3 [/usr/local/share/dotnet/sdk]

**Comment by sdmaclea** [comment]
@bintr33 There is a https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.11-beta1 beta debugger release which should work reasonably well with preview3.
