### ISSUE TITLE
WebProxy: IsBypassed(Uri) call is slow under load when bypassOnLocal is true

### ISSUE THREAD

**Issue by rmandvikar** [dotnet/runtime#50323]
### Description

In WebProxy, the `IsBypassed(Uri)` call is slow when `bypassOnLocal` is `true` under load. This is because the `SystemIPGlobalProperties.get_DomainName()` is a blocking call due to a lock thereby causing thread contention. This makes `IsLocal(Uri)` call slow, making `IsBypassed(Uri)` call slow.

```
class System.Net.WebProxy:
    ...
    ctor(Uri address, bool bypassOnLocal, string[] bypassList):
        // ...
    
    bool IsBypassed(Uri host):
        if (host == null)
            throw new ArgumentNullException(nameof(host))
        return
            Address == null ||
            (BypassProxyOnLocal && IsLocal(host)) ||
            IsMatchInBypassList(host)
    
    bool IsLocal(Uri host):
        // some checks, and IPGlobalProperties.GetIPGlobalProperties().DomainName call
        // which is slow and blocking under load
    
    bool IsMatchInBypassList(Uri input):
        // regex match checks using bypassList
```

### Configuration

* Which version of .NET is the code running on? netcore 3.1
* What OS version, and what distro if applicable? Windows 2016, IIS
* What is the architecture (x64, x86, ARM, ARM64)? x64
* If relevant, what are the specs of the machine?

platform:
os : Windows Server 2016 Datacenter
kernel_name : Windows
kernel_release : 10.0.14393
machine : x86_64

cpu:
vendor_id : GenuineIntel
model_name : Intel(R) Xeon(R) Gold 6132 CPU @ 2.60GHz
cpu_cores : 8
cpu_logical_processors : 8
mhz : 2600
family : 6
model : 79
stepping : 0

memory:
total : 12.88G

cluster size:
8 nodes

### Regression?

DNK

### Data

**Background**: The app that is load-tested is a REST api microservice that calls other REST apis and external network calls are proxied (using the WebProxy class).

- The JMeter load tests was capping at 90/s for the cluster. The times taken by dependency apis did not add up to the total time taken by the transaction. There were large time gaps that were unaccounted for (internal overhead) as the load increased. CPU Usage at ~20% steady (bounded), Memory Available / Usage steady indicating not bound by those resources.
- Load tests resulted in threads added to thread pool for api's w3wp process. The threads count increased ~2x during the leading 2m of a load run. This pointed to thread pool starvation.
- The endpoint with multiple worker processes (web gardening) perf'ed better at 135/s throughput (wp=2). CPU Usage at 20% * worker processes and steady (bounded). This pointed to thread pool starvation.

JMeter load test result:
```
Comment Users Duration Nodes # Samples Average Median 90% Line 95% Line 99% Line  Min   Max Error % Throughput
before    360      10m     8     55084    3863   3752     4505     4862    10443 2064 12122   0.00%   88.79632
```

### Analysis

The PerfView and memory dump traces collected during a load test pointed to the problem. The calls were slow while getting the DNS related information for the domain name in the URL (`System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()+24`).

```
[0x7ffd6ba75a84] ntdll!ZwWaitForSingleObject+14
[0x7ffd68404daf] KERNELBASE!WaitForSingleObjectEx+8f
[0x7ffd6749e5ec] dnsapi!TimedLock_Enter+2c
[0x7ffd6749ebd2] dnsapi!NetInfo_Get+2de
[0x7ffd674b78be] dnsapi!Config_GetDnsServerList+52
[0x7ffd674b79d3] dnsapi!Config_GetDnsServerListIp4+3b
[0x7ffd674a9ee7] dnsapi!DnsQueryConfig+21bd7
[0x7ffd6745c006] IPHLPAPI!AllocateAndGetFixedInfo+76
[0x7ffd6745c341] IPHLPAPI!GetNetworkParams+31
[0x7ffcef3ceae1] ILStubClass.IL_STUB_PInvoke(Microsoft.Win32.SafeHandles.SafeLocalAllocHandle, UInt32 ByRef)+a1
[0x7ffcef3ce8ad] System.Net.NetworkInformation.HostInformationPal.GetFixedInfo()+cd
[0x7ffcef3ce7b4] System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()+24
[0x7ffcef3ce698] System.Net.WebProxy.IsLocal(System.Uri)+a8
[0x7ffcee0b4c6a] System.Net.WebProxy.IsBypassed(System.Uri)+3a
[0x7ffcee0b4a8f] System.Net.Http.HttpConnectionPoolManager.SendAsync(System.Net.Http.HttpRequestMessage, Boolean, System.Threading.CancellationToken)+7f
[0x7ffcee0b4966] System.Net.Http.HttpConnectionHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken)+16
```

The `WebProxy` instance is a singleton with the proxy uri, `bypassOnLocal` set to `true`, and uris for `bypassList`.

```
class System.Net.WebProxy:
    ...
    ctor(Uri address, bool bypassOnLocal, string[] bypassList):
        // ...
    
    bool IsBypassed(Uri host):
        if (host == null)
            throw new ArgumentNullException(nameof(host))
        return
            Address == null ||
            (BypassProxyOnLocal && IsLocal(host)) ||
            IsMatchInBypassList(host)
    
    bool IsLocal(Uri host):
        // some checks, and IPGlobalProperties.GetIPGlobalProperties().DomainName call
        // which is slow and blocking under load
    
    bool IsMatchInBypassList(Uri input):
        // regex match checks using bypassList
```

We found that the `SystemIPGlobalProperties.get_DomainName()` is a blocking call due to a lock (see `dnsapi!TimedLock_Enter+2c` in IL trace above) thereby causing thread contention. This makes `IsLocal(Uri)` call slow. I set `BypassProxyOnLocal` to `false` to _bypass_ the `IsLocal(host)` call. The change resulted in ~4x'ing the throughput for the load test to 320/s (from 90/s) for the cluster, reducing the response time to 2.5s avg (from 3.9s avg), with a higher 810 users (from 360 users). CPU Usage was below 10% (from 20%) and api's w3wp threads count steady at 50-60 (from 50-100).

JMeter load test results (before and after):
```
Comment Users Duration Nodes # Samples Average Median 90% Line 95% Line 99% Line  Min   Max Error % Throughput
before    360      10m     8     55084    3863   3752     4505     4862    10443 2064 12122   0.00%   88.79632
after     810      10m     8    184909    2438   2339     3022     3194     3493 1951  7857   0.00%  319.79447
```

**Comment by stephentoub** [comment]
@dotnet/ncl, every call to IPGlobalProperties.GetIPGlobalProperties() creates a new instance,  so while the domain name is cached on the instance,  this defeats the cache.  Are we purposefully not caching the domain name,  e.g. because we think it might change? As written, this is indeed very expensive.

**Comment by iSazonov** [comment]
SystemIPGlobalProperties contains properties that may and may not change on the fly. Changing the computer name and / or domain requires a mandatory reboot and these properties can be cached on a permanent basis.

**Comment by iSazonov** [comment]
s_fixedInfoInitialized is never assigned to true in GetFixedInfo()

**Comment by stephentoub** [comment]
> s_fixedInfoInitialized is never assigned to true in GetFixedInfo()

It is, by EnsureInitialized.

**Comment by geoffkizer** [comment]
@wfurt Do you know if this is intentional?

**Comment by wfurt** [comment]
It seems like the offending change was https://github.com/dotnet/corefx/pull/16735 e.g. it is like this since 2.0.
We used lock and volatile read/write before. So I don't think that part is intentional. 

As far as caching hostname it self: AFAIK neither Windows nor Linux has good mechanism how to detect changes. 
While that may not change frequently and I personally would be ok if we document that we may not get updates. 
The interesting part we would need to test IMHO is dhcp. I think it is quite often when you close laptop and open it on different network and then you get new network identity. We _could_ listen to network changes and invalidate cache but that may have cost as well.

**Comment by stephentoub** [comment]
> It seems like the offending change was dotnet/corefx#16735 e.g. it is like this since 2.0.

No.  The use of EnsureInitialized here is fine. @iSazonov asked if its usage was wrong, but it's not.

The questionable part is that https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.Net.WebProxy/src/System/Net/WebProxy.cs#L178 doesn't cache the domain name: it calls https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/IPGlobalPropertiesPal.Windows.cs#L8-L11 which allocates a new instance each time.

**Comment by iSazonov** [comment]
> No. The use of EnsureInitialized here is fine. @iSazonov asked if its usage was wrong, but it's not.

The thought comes from the OP - it looks like the cache isn't working at all.
It would be interesting to see a real PerfView trace to confirm or disprove this.

**Comment by stephentoub** [comment]
@iSazonov, please read me comments.  It's not being cached for IsLocal because each IsLocal call invokes IPGlobalProperties.GetIPGlobalProperties(), which returns a new instance each time.  It doesn't matter that the domain is cached on that instance,  because the instance isn't reused.

**Comment by iSazonov** [comment]
@stephentoub Sorry my misunderstanding, but SystemIPGlobalProperties calls HostInformationPal.FixedInfo that is static and I'd expect there shouldn't have been repeated DNS lookups.

**Comment by stephentoub** [comment]
> Sorry my misunderstanding

Nope, you're right, it's static, I somehow though it was instance.  Apologies.

And, indeed, it is being cached correctly. So while there's other stuff to be cleaned up here (which I'll do shortly), this method is doing what it's supposed to be doing (at least on Windows).

@rmandvikar, can you please share a repro that shows otherwise?  You wrote:
"We found that the SystemIPGlobalProperties.get_DomainName() is a blocking call due to a lock"
are you seeing that method being called repeatedly, or just at the beginning of the app's execution?  It's optimistic in nature, meaning that if you made 100 concurrent calls at the beginning of the app, they would all result in a call to GetFixedInfo, but after at least one of them completed successfully, no future calls should end up in GetFixedInfo.

**Comment by rmandvikar** [comment]
> @rmandvikar, can you please share a repro that shows otherwise? You wrote:
> "We found that the SystemIPGlobalProperties.get_DomainName() is a blocking call due to a lock"
> are you seeing that method being called repeatedly, or just at the beginning of the app's execution? Is it possible your trace is just showing the initial locking that's happening, potentially with many concurrent requests on first use all blocked waiting for this?

This was an issue back in Aug 2020 for us, and I had not filed an issue then. Sorry, for not calling that out specifically in the post. I didn't see the `IsLocal(Uri)` code change from then so I filed the issue recently hoping that it will benefit others. I'll need some more time to run a load test. That said, the workaround for me was to bypass `IsLocal(Uri)` completely as that was definitely the bottlenext then. Any idea if the underlying code would have changed from then? Apologies again for the confusion.

**Comment by rmandvikar** [comment]
Here is a simple test showcasing the perf issue locally. Note the time taken for `BypassOnLocal(True)` on `netcoreapp3.1`. 
```
(net48) Passed (2)	209 ms	
Test	Duration	Error Message
BypassOnLocal(False) Passed	28 ms	
BypassOnLocal(True) Passed	181 ms	

(net5.0) Passed (2)	58 ms	
Test	Duration	Error Message
BypassOnLocal(False) Passed	20 ms	
BypassOnLocal(True) Passed	38 ms	

(netcoreapp3.1) Passed (2)	9.2 sec	
Test	Duration	Error Message
BypassOnLocal(False) Passed	24 ms	
BypassOnLocal(True) Passed	9.1 sec	// <-- woah!
```
nunit test:
```
		[Test]
		[TestCase(true)]
		[TestCase(false)]
		public void BypassOnLocal(bool bypassOnLocal)
		{
			var webproxy =
				new WebProxy(
					Address: new Uri("http://www.google.com"),
					BypassOnLocal: bypassOnLocal,
					BypassList: new[]
					{
						"(?i)[a-z0-9-_.]+github\\.com$" }
					);
			var count = 2_000;
			var sw = new Stopwatch();
			sw.Start();
			for (int i = 0; i < count; i++)
			{
				var isBypassed = webproxy.IsBypassed(new Uri("http://www.google.com"));
			}
			sw.Stop();
			Console.WriteLine(sw.ElapsedMilliseconds);
			Console.WriteLine(((double)sw.ElapsedMilliseconds) / 1000);
		}
```
dotnet runtimes installed on local:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by stephentoub** [comment]
> Note the time taken for BypassOnLocal(True) on netcoreapp3.1.

Aha, 3.1.  Yes, this was an issue in 3.1.  You can see the code here:
https://github.com/dotnet/corefx/blob/29cfd61ab26fcf803f8f59641112e0fc39e10f7f/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/SystemIPGlobalProperties.cs#L21-L45

As this was fixed in 5, I'm going to close this.  But thanks for the issue; while the concern you highlighted was already addressed, it highlighted some other things to be fixed as well.

**Comment by rmandvikar** [comment]
@stephentoub, Just making sure: even though it's fixed in `net5.0` shouldn't this be addressed with a patch for `netcoreapp3.1` as it's LTS and EOS is Dec 2022? My app is still on 3.1 and can't upgrade to 5.0 yet.

**Comment by stephentoub** [comment]
LTS doesn't mean everything is backported.  Only select fixes are backported when they're deemed impactful enough to enough apps/developers.
cc: @karelz

**Comment by rmandvikar** [comment]
@stephentoub, Could you please point me to commit that fixed the bug in `net5.0`?

**Comment by stephentoub** [comment]
> Could you please point me to commit that fixed the bug in net5.0?

https://github.com/dotnet/runtime/pull/1914/files#diff-35de7b31330089f70ddb6d21a92db1483e2b3f82358860c5ea0073ee5f90d1f9R35

**Comment by iSazonov** [comment]
> My app is still on 3.1 and can't upgrade to 5.0 yet.

If the performance is very critical for your scenario you could copy the code from .Net 5.0 in your project. License allows this and it is not so not much work.
