### ISSUE TITLE
a little bit slower runtime when converting a project from .net framework 4.8 to .net core 5.0

### ISSUE THREAD

**Issue by Spirch** [dotnet/runtime#50320]
### Description

this is .net framework 4.8 ---> .net core 5.0

I have a personal chess engine that I am working on and yesterday I decided to switch from .net framework to .net core.

I did not change 1 line of code in the process, exact same code.

When I did I noticed a loss of a few %, between 2% and up to 5% (so far)

This is enough to see an average of 500,000 to 2,000,000 moves per second difference in perft (google it if you dont know what this is, it's a type of test for a chess engine)

What I did is, I create a brand new .net core solution with 2 projects inside it.

    console application (this one is VB) <--- a way to control the engine
    class project (c#) <--- the engine

### Configuration

this is the vbproj of framework:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DefineTrace>true</DefineTrace>
    <OutputPath>..\..\Build\</OutputPath>
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <DocumentationFile>
    </DocumentationFile>
    <Optimize>true</Optimize>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
    <DebugType>pdbonly</DebugType>
    <PlatformTarget>x64</PlatformTarget>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
```

this is the csproj of framework:

```
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\..\Build\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <NoStdLib>false</NoStdLib>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Prefer32Bit>false</Prefer32Bit>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

```
this is the vbproj of core:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningsAsErrors>41999,42016,42017,42018,42019,42020,42021,42022,42032,42036</WarningsAsErrors>
    <PlatformTarget>x64</PlatformTarget>
    <RemoveIntegerChecks>true</RemoveIntegerChecks>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>pdbonly</DebugType>
    <DefineDebug>false</DefineDebug>      
  </PropertyGroup>
```

this is the csproj of core:

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>     
  </PropertyGroup>
```

### Regression?

for these timeline, I restricted the runtime to a specific core of my cpu to make sure it was under the same behaviour. I can reproduce it every time with or without this restriction

I do a warmup with a call to my engine before running the 5 tests in the yellow circle

dot trace time line of framework dot trace time line of framework
![framework timeline](https://user-images.githubusercontent.com/13721544/112727108-390aaf80-8ef7-11eb-8905-c6bdc5a17499.PNG)

dot trace time line of core dot trace time line of core
![core timeline](https://user-images.githubusercontent.com/13721544/112727107-38721900-8ef7-11eb-969b-735c2d8edd89.PNG)

I did read this: [TieredCompilation - Cold methods with hot loops may run slower with tiering #11006](https://github.com/dotnet/runtime/issues/11006) and I tried to switch on DisableTier0Jit or off TieredCompilation with no luck

**Comment by Spirch** [comment]
it should also be under area-TieredCompilation-coreclr  label I think

i don't know how to add this

**Comment by danmoseley** [comment]
If the tiered compilation flag makes no difference then it's probably not related to tiered compilation.
Can you dig into the perf comparison - are there particular platform APIs that seem consistently slower in one trace?

**Comment by En3Tho** [comment]
How invasive is dotTrace with your current settings? Can it somehow inject code preventing certain optimizations? Can your code be re-benchmarked with Benchmark.Net?

**Comment by Spirch** [comment]
> 
> 
> How invasive is dotTrace with your current settings? Can it somehow inject code preventing certain optimizations? Can your code be re-benchmarked with Benchmark.Net?

i don't  know if it is invasive or not but i can see it is slower just by running longer perft, i took a small one for this report

i can look into doing it under benchmark.net, i never used it so it make take a few hours before  post anything useful

**Comment by Spirch** [comment]
> 
> 
> If the tiered compilation flag makes no difference then it's probably not related to tiered compilation.
> Can you dig into the perf comparison - are there particular platform APIs that seem consistently slower in one trace?

in the .net core I tried to add random

`[MethodImpl(MethodImplOptions.AggressiveOptimization)]`

I get some "speed up" but it's still slower

I just did, with ILSpy 7.0 preview, save code as IL of the full dll (engine, not console) and I compared it

the order of the classes and some methods are different, not sure if that matter or not

**one thing that might matter** is for .net framework, one of my hot spot method have one field optimized out (not there anymore) while the .net core still have it (other method seem to have the same thing but they are not called in the perft)

IL code that use that field is _different_ other than that everything is identical between the two files

(one thing that is different, framework reference mscorlib while core reference System.Runtime, I assume this is normal)

would you be interested in seeing the IL files? ~13660 lines

**Comment by danmoseley** [comment]
Looking at the IL is probably not going to be useful. Instead can you compare the CPU profiles in both cases and see whether there is a particular part of the code that is slower?

**Comment by Spirch** [comment]
> 
> 
> Looking at the IL is probably not going to be useful. Instead can you compare the CPU profiles in both cases and see whether there is a particular part of the code that is slower?

I will see what I can do, I'm new-ish into digging into this kind of profiling

> 
> 
> How invasive is dotTrace with your current settings? Can it somehow inject code preventing certain optimizations? Can your code be re-benchmarked with Benchmark.Net?

this is what it give, the html output

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
test | 4.210 s | 0.0349 s | 0.0309 s

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT  [AttachedDebugger]
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
test | 4.602 s | 0.0244 s | 0.0228 s

**Comment by SingleAccretion** [comment]
Two interesting metrics that BDN can give you are code size & dynamic code path. The first is obtained by using a `[DisassemblyDiagnoser]` on the benchmarked class, the latter - `[HardwareCounters]` with the `HardwareCounter.InstructionRetired` flag. I would expect both to be on the bigger side for the .NET Core version.

Also, question: is your engine running a very tight loop or is the work more spread out among functions/paths?

**Comment by Spirch** [comment]
> 
> 
> Two interesting metrics that BDN can give you are code size & dynamic code path. The first is obtained by using a `[DisassemblyDiagnoser]` on the benchmarked class, the latter - `[HardwareCounters]` with the `HardwareCounter.InstructionRetired` flag. I would expect both to be on the bigger side for the .NET Core version given your benchmark results.

is it easy to setup? this is my first time to use BDN, i will look online and see if it can be done "quickly" otherwise it might wait until tomorrow

> > `[AttachedDebugger]`
> 
> Is that accurate? One should not be running benchmarks with the debugger attached...

I ran both inside visual studio(under release mode), this is outsite;

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
test | 4.097 s | 0.0166 s | 0.0155 s

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
test | 4.247 s | 0.0102 s | 0.0095 s


> 
> Also, question: is your engine running a very tight loop or is the work more spread out among functions/paths?

by definition there is a lot of loop in a perft in chess, in my case, they have a few lines of codes in each loop (usually between 1 and 5 lines) when looking at the result in dot trace, there is a lot of inlining being done, like a lot

**Comment by SingleAccretion** [comment]
> is it easy to setup? this is my first time to use BDN

Yep. See the [documentation](https://benchmarkdotnet.org/articles/features/disassembler.html).

> i will look online and see if it can be done "quickly" otherwise it might wait until tomorrow

Sure, no rush 👍.

> by definition there is a lot of loop in a perft in chess, in my case, they have a few lines of codes in each loop (usually between 1 and 5 lines) when looking at the result in dot trace, there is a lot of inlining being done, like a lot

Interesting. Machine code should tell the story better here then.

**Comment by Spirch** [comment]
ok, i made the [DisassemblyDiagnoser] working

if I compare the file between core and framework, literally everything is different or way too many thing, i'm not sure if that can be useful here

for the HardwareCounters

// Validating benchmarks:
The counter InstructionRetired is not available. Please make sure you are Windows 8+ without Hyper-V

weird restriction, do i really need to change my bios and/or windows configuration to run that?

**Comment by SingleAccretion** [comment]
> weird restriction, do i really need to change my bios and/or windows configuration to run that?

It is quite a low-level thing (built into the CPU), so you may have to, yes.

> if I compare the file between core and framework, literally everything is different or way too many thing, i'm not sure if that can be useful here

It will be the next thing to look at after profiling has run its course. What did the "Code Size" column numbers look like?

**Comment by Spirch** [comment]
16112 B for framework
15107 B for core

i will see tomorrow if i want to play with my virtualisation settings

**Comment by Spirch** [comment]
for reference here is what inlining vs no inlining look like (using dot trace)

![inlining](https://user-images.githubusercontent.com/13721544/112738514-e7cfdf80-8f39-11eb-89ae-266d93efe393.png)

**Comment by Spirch** [comment]
this is from moves/sec that get outputted in the console, I will redo the dot trace / benchmarknet later today
(using proper tool might show that it didnt matter. in the code I'm using stopwatch for the perft method)

if I add the
`[MethodImpl(MethodImplOptions.AggressiveOptimization)]`
to the methods, for the netcore solution, that doesn't get inlined, it get faster (still less than framework build)

in the console app, I control the
`Console.BufferHeight`
if I increase this before perft vs after, I see less difference(speed up) after the perft  (still less than framework build)

both solution together look faster  (still less than framework build)

**Comment by benaadams** [comment]
> for reference here is what inlining vs no inlining look like (using dot trace)

While testing things; looks like `Legal` inlines sometimes but not everytime and it gets called *a lot*; so you could add `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to the `Legal` method?

**Comment by Spirch** [comment]
ok, I think it wasnt just a feeling

quick note;
.net framework is still faster than the .net core when I run the console app
I changed some code versus yesterday, so you can't really compare today vs yesterday, still 100% identical code in both solution, minus the Attribute `MethodImpl `in the core solution
when i run dot trace, it include the console
when i run benchmarknet, it include only the engine, no console whatsoever

in both case, i limit to 1 cpu with this; 
```
using (var p = System.Diagnostics.Process.GetCurrentProcess())
{
     p.ProcessorAffinity = (IntPtr)2;
}
```

so...

the dottrace timeline look like identical vs my previous run, original post(this time around i removed some filtering in it, to show a bigger picture) I don't know if it will help

![dottrace timeline](https://user-images.githubusercontent.com/13721544/112767086-bced9600-8fe2-11eb-82d9-6c36eba6130b.png)


**the benchmark.net tell different story**

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
Perft | 4.148 s | 0.0068 s | 0.0060 s

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
Perft | 4.115 s | 0.0035 s | 0.0031 s


so now the .net core seem a little bit faster

if completely I remove the
`[MethodImpl(MethodImplOptions.AggressiveOptimization)]`

I'm now getting this;

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.201
  [Host]     : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT
  DefaultJob : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Method | Mean | Error | StdDev
-- | -- | -- | --
Perft | 4.187 s | 0.0093 s | 0.0087 s


I got a feeling that the console is where the "slowness" is coming from for the .net core, somehow
I'm not doing anything "crazy" at least I don't think so?

**Comment by Spirch** [comment]
> While testing things; looks like `Legal` inlines sometimes but not everytime and it gets called _a lot_; so you could add `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to the `Legal` method?

I tried some permutation of this vs [MethodImpl(MethodImplOptions.AggressiveOptimization)]

the AggressiveOptimization give more speed

**Comment by Spirch** [comment]
this is with console this time around, i was finally able to figure out how to make it work
(with `[MethodImpl(MethodImplOptions.AggressiveOptimization)] ` at the proper place like before)

so it seem the console slow the code down, somehow.

if it matter, I use / call / change these;

Console.BufferHeight
Console.CursorLeft
Console.CursorTop
Console.ForegroundColor
Console.WindowHeight
Console.WindowWidth
Console.Write
Console.WriteLine

the engine itself doesnt use any console 

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
  [Host] : .NET Framework 4.8 (4.8.4341.0), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

Method | Mean | Error | StdDev
-- | -- | -- | --
Perft | 4.109 s | 0.0084 s | 0.0078 s

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET Core SDK=5.0.201
  [Host] : .NET Core 5.0.4 (CoreCLR 5.0.421.11614, CoreFX 5.0.421.11614), X64 RyuJIT

Job=InProcess  Toolchain=InProcessEmitToolchain  

Method | Mean | Error | StdDev
-- | -- | -- | --
Perft | 4.212 s | 0.0197 s | 0.0175 s


funny fact, that small 0.1 seconds differences is enough to make the core solution slower by about ~770,000 less moves

**Comment by Symbai** [comment]
Could it be that the performance penalty is probably be caused ICU change on .NET5 which makes string usage a lot slower in many cases? _The function in the screenshot has a string as parameter..._

**Comment by danmoseley** [comment]
That is easy to test, by disabling it: https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu

In general though I recommend analyzing the profile systematically. Guessing probably won't help (unless perhaps it's guesses like this that can be quickly ruled out)

**Comment by danmoseley** [comment]
> one thing that i can see, console under core use a threadpool, see screenshot of dottrace, maybe this is where the slowdown is coming from, the perft is not async

I don't see evidence in the screenshot the console is slower. The only way to proceed would be to analyze your app further.

Because clr.dll was renamed coreclr.dll (etc) unfortunately you cannot simply diff the traces. It looks like you can bound your trace to eg Think1 on both sides, and then follow the tree down the most expensive parts, comparing each side to see where the extra cost might be. I don't know dottrace but it probably allows you to bound the trace to just one method and it's callees.

Ideally you get down to a point where you can see eg., some System.* method is say 10% slower and that gives you the 1.5-2.5% slowdown you're seeing. If you're unlucky, the cost is sort of spread all over.

**Comment by chrisaut** [comment]
FYI Dottrace allows [diffing of perf snapshots](https://www.jetbrains.com/help/profiler/Studying_Profiling_Results__Comparing_Profiling_Data.html), this should allow you to more easily see differences between the runtime. But you just have to dig down into the callstack to identify, and then isolate that code into it's own benchmark to confirm.

FWIW I would actually be interested in seeing your chess engine. If you open sourced it would also allow other people to investigate as a bonus ;-)

**Comment by Spirch** [comment]
I did the diff with dottrace, if I do it on sampling or tracing I don't see something that popup up, it's random
if I disable inlining, both are mostly identical, nothing stand out

one thing I tried, I went back to core 3.1, same issue then **I tried 2.1 that one got the same speed as 4.8**, first time under core

for fun I tried to use unsafe pointer on one "big" lookup, read only array and under 5.0 it got the same speed as 4.8 for the first time but I don't like that solution at all

so maybe it's a memory alignment? I'm simply speculating here and my own skill set to debug this is very very limited

**Comment by Spirch** [comment]
so I updated some part of the code and somehow now the performance, still same source code for core and framework, are identical or close (marge of error)

i can't explain exactly what caused the slowdown before and/or the current result 

I guess this can be closed unless someone want more information

**Comment by stephentoub** [comment]
> I guess this can be closed unless someone want more information

Ok, thanks, glad the issue resolved.
