### ISSUE TITLE
Keeping case for nonstandard headers

### ISSUE THREAD

**Issue by EtherealAO** [dotnet/runtime#50325]
## Background and Motivation

In some applications, they use nonstandard header format(e.g X-Request-Id instead of X-Request-ID),  when try add X-Request-Id into headers, it will be overrode by X-Request-ID, may lead into a 403 error.
## Proposed API

```diff
namespace System.Net.Http.Headers
{
    public abstract class HttpHeaders : IEnumerable<KeyValuePair<string, IEnumerable<string>>>
    {
+      public bool TryAddHeaderKeepingCase(string name, string? value) => ...
    }
}
```
## Usage Examples

``` C#
            var msg = new HttpRequestMessage(System.Net.Http.HttpMethod.Post,"url");
            msg.Headers.TryAddHeaderKeepingCase("X-Request-Id", Guid.NewGuid().ToString());
            var response = new HttpClient().SendAsync(msg);
```
## Alternative Designs

I haven't found an alternative yet...
## Risks

Maybe more RAM usage due to more string was allocated? But I don't think it's a problem.

**Comment by davidfowl** [comment]
> Maybe more RAM usage due to more string was allocated? But I don't think it's a problem.

This is absolutely a problem 😄

**Comment by EtherealAO** [comment]
> > Maybe more RAM usage due to more string was allocated? But I don't think it's a problem.
> 
> This is absolutely a problem 😄

But it's useful to me. Could you give me some solutions to do that? Now I'm forwarding those nonstandard requests to a golang program, so inconvenient.

**Comment by samsosa** [comment]
The solution is to fix the receiving end. Regarding [https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2](url) header names are case-insensitive. You should really make the golang program compatible accordingly, not the other way around.

**Comment by FiniteReality** [comment]
> The solution is to fix the receiving end. Regarding [https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2](url) header names are case-insensitive. You should really make the golang program compatible accordingly, not the other way around.

As much as we'd like the world to be perfect and free of bugs, sometimes that's just not how things work. 

Maybe `HttpHeaders.TryAddWithoutValidation` should be augmented with the ability to preserve the case of the header to unblock scenarios like this; after all to my knowledge it is exposed for "advanced" scenarios.

**Comment by karelz** [comment]
Triage: It is a corner case going against RFC. Adding API is overkill in such case.
Changing the `TryAddWithoutValidation` would be possible (and probably slightly better), but technically breaking change, so not worth it, given it impacts only bad apps and we have seen only 1 report so far. Closing.
