### ISSUE TITLE
I believe that Stream class should be removed from .NET

### ISSUE THREAD

**Issue by progalgo** [dotnet/runtime#50340]
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L14

Stream is probably among the most harmful types imaginable. Its idea comes from C programming language, if not before that. It represents mechanism of interacting with operating system. But in .NET it is used in such ways, that blur line between OS-interaction and abstract representation of byte-sequence. The fact that Stream supports both reading AND writing means that every component that uses Stream as a kind of interface must support both creation of write Stream as well as accepting read Stream. This is a situation where writing more code does not create any new real value. Eventually some authors choose to use one way, and others — another way. Eventually it causes inefficiencies in data transmission through various libraries and components. And tons of spaghetti code — the new kind, data spaghetti. Basically I believe Stream class should be completely removed from .NET. It's role as sequence of bytes could be easily occupied by IEnumerable&lt;byte&gt;. To control interaction with files and other tape-like devices we could devise a new type with read, write, and seek methods.

**Comment by stephentoub** [comment]
Thank you for the suggestion.  This is not going to happen.

**Comment by danmoseley** [comment]
@progalgo do you believe a read only stream like type would be useful?

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/39601
