### ISSUE TITLE
Question: Is JsonSerializer.SerializeToUtf8Bytes output platform specific with regard to endianness (LE & BE)?

### ISSUE THREAD

**Issue by MartyIX** [dotnet/runtime#50356]
Hi .NET runtime team,

I have noticed several PRs by Ulrich Weigand which patched several big/little endian issues (e.g. https://github.com/dotnet/runtime/pull/49708). My question is whether the output of https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer.serializetoutf8bytes?view=net-5.0 is platform specific (encoded in little endian on little-endian systems & big endian on big-endian systems) or not. Meaning, can I safely send the bytes produced by `JsonSerializer.SerializeToUtf8Bytes` to a different computer or not?

I did not succeed in finding useful information in [the](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter?view=net-5.0) [docs](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0).

Maybe my question is silly. Hopefully, it is not. Even if it is, maybe it will help others.

Thank you

**Comment by huoyaoyuan** [comment]
UTF8 doesn't have endianness. It defines its own bytes order.

**Comment by eiriktsarpalis** [comment]
Platform endianness should not influence the output of the encoding. FWIW #49708 concerned fixing a debug assertion in the generation of an internal key, the issue had no influence on the output encoding. Unless there are other issues I'm unaware of?

**Comment by MartyIX** [comment]
Thank you guys!

> FWIW #49708 concerned fixing a debug assertion in the generation of an internal key, the issue had no influence on the output encoding. Unless there are other issues I'm unaware of?

It is unrelated. It's just it reminded me to ask this question.
