### ISSUE TITLE
TargetOS is case-sensitive for iOSSimulator when running tests

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#50379]
`./dotnet.sh build src/libraries/System.Threading.Timer/tests/ /t:test /p:targetos=iossimulator /p:targetarchitecture=x64` will fail, but `./dotnet.sh build src/libraries/System.Threading.Timer/tests/ /t:test /p:targetos=iOSSimulator /p:targetarchitecture=x64` will succeed. MSBuild otherwise isn't case-sensitive, so this should probably just be fixed.

**Comment by filipnavara** [comment]
Same for `iOS`. Got bitten by it.

**Comment by lambdageek** [comment]
How is this happening?  `dotnet new console` then add this:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <P Condition="'$(P)' == ''">abCD</P>
  </PropertyGroup>

  <Target Name="AA">
    <Message Importance="High" Condition="'$(P)' == 'abCD'" Text="trail CAPS" />
    <Message Importance="High" Condition="'$(P)' == 'ABcd'" Text="LEAD caps" />
  </Target>

</Project>
```

```console
$ dotnet build /t:AA /p:P=ABCD
...
  trail CAPS
  LEAD caps
...
$ dotnet build /t:AA /p:P=abcd
...
  trail CAPS
  LEAD caps
...
```

**Comment by CoffeeFlux** [comment]
Yeah, msbuild is case-insensitive by default. In this case, it's failing due to what appears to be having to interface with cmake? Full log: https://gist.github.com/CoffeeFlux/c1e2d1f34c442b9fb4ff42a839a45d29

**Comment by steveisok** [comment]
I think it probably has everything to do w/ how we shuffle to cmake in AppleAppBuilder.

https://github.com/dotnet/runtime/blob/60d169bdec5b876fcfe009b140467a8b706c9bd8/src/tasks/AppleAppBuilder/Xcode.cs#L181

https://github.com/dotnet/runtime/blob/60d169bdec5b876fcfe009b140467a8b706c9bd8/src/tasks/AppleAppBuilder/Xcode.cs#L158-L174

**Comment by CoffeeFlux** [comment]
This issue persists, though the error has changed. New log: https://gist.github.com/CoffeeFlux/ebaac87f883ff0ffc36587c4bda25f3b

**Comment by MaximLipnin** [comment]
Thanks Ryan, I'll take a look.
