### ISSUE TITLE
dotnet build failing on project with System.UnauthorizedAccessException: Access to the path 'D:\test\...obj\Debug\net6.0\apphost.exe' is denied

### ISSUE THREAD

**Issue by kevinkoenig** [dotnet/runtime#50378]
### I am trying to build a project that has been working successfully on dotnet 6 preview 2.  I tried to build it today and i am getting the following stacktrace from dotnet build

Microsoft (R) Build Engine version 16.10.0-preview-21126-01+6819f7ab0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  [[90m13:12:15[39m] Working directory changed to [35mD:\test\AurigoQuote2Cash\AurigoQuote2Cash\ClientBuild[39m
  [[90m13:12:16[39m] Using gulpfile [35mD:\test\AurigoQuote2Cash\AurigoQuote2Cash\ClientBuild\gulpfile.js[39m
  [[90m13:12:16[39m] Starting '[36mbuild[39m'...
  [[90m13:12:16[39m] Starting '[36mbuild-bundle[39m'...
  ==================> Generating bundles...
  [[90m13:12:16[39m] Finished '[36mbuild-bundle[39m' after [35m28 ms[39m
  [[90m13:12:16[39m] Starting '[36m<anonymous>[39m'...
  [[90m13:12:16[39m] Finished '[36m<anonymous>[39m' after [35m3.19 ms[39m
  [[90m13:12:16[39m] Finished '[36mbuild[39m' after [35m33 ms[39m
  [[90m13:12:16[39m] Build Completed!
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  AurigoQuote2Cash.Model -> D:\test\AurigoQuote2Cash\AurigoQuote2Cash.Model\bin\Debug\net6.0\AurigoQuote2Cash.Model.dll
  AurigoQuote2Cash.Utility -> D:\test\AurigoQuote2Cash\AurigoQuote2Cash.Utility\bin\Debug\net6.0\AurigoQuote2Cash.Utility.dll
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018: System.UnauthorizedAccessException: Access to the path 'D:\test\AurigoQuote2Cash\AurigoQuote2Cash\obj\Debug\net6.0\apphost.exe' is denied. [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018: System.UnauthorizedAccessException: Access to the path 'D:\test\AurigoQuote2Cash\AurigoQuote2Cash\obj\Debug\net6.0\apphost.exe' is denied. [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.MachOUtils.RemoveSignature(String filePath) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__RemoveSignatureIfMachO|2() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(517,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\test\AurigoQuote2Cash\AurigoQuote2Cash\AurigoQuote2Cash.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:04.08

two of the three project successfully build, the main project fails with the error above.  I don't even know where to start.  I have tried creating a test repository created from a fresh git clone, but i get the same error.  Can someone help point me in the right direction.

Kevin Koenig

**Comment by vitek-karas** [comment]
This looks a lot like https://github.com/dotnet/runtime/issues/49332.
Can you try latest preview build from dotnet/installer?

**Comment by kevinkoenig** [comment]
i will try whatever you want.  I am currently running preview 2.  Can you point me in the right direction to install the build you want me to test with.

**Comment by vitek-karas** [comment]
If you go to https://github.com/dotnet/installer there's a large table near the end of the main page with all of the builds. Pick the first column (nightly builds) and the "installer" link for the right platform. It should remove your previous 6.0 preview on the machine. You can always uninstall and reinstall older builds.

**Comment by kevinkoenig** [comment]
As I was trying to install the additional previews, I noticed that I was having some significant script execution issues, and other security related items because of our domain.  I have since corrected the issue, and the build is now working correctly
