### ISSUE TITLE
AppHost on Mac should be dev-signed during publish

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#50375]
There are two tasks here: codesigning when publishing an apphost while running on Mac, and codesigning when publishing for Mac on another platform (cross-compiling).

Let's start by codesigning only when running CreateAppHost on Mac, for Mac, as long as the `codesign` tool is available.

Cross-compiling can be supported later.

**Comment by agocke** [comment]
@mateoatr Can you take a look at this next? I'm hoping it's a simple change in CreateAppHost and it should unblock our more complicated scenarios.

**Comment by vitek-karas** [comment]
This should be done for any apphost, even during `dotnet build`.

**Comment by vitek-karas** [comment]
@mateoatr is this now fixed with https://github.com/dotnet/runtime/pull/53913 being merged?

**Comment by mateoatr** [comment]
> @mateoatr is this now fixed with #53913 being merged?

Yep. That PR and the one on the SDK. Closing.
