### ISSUE TITLE
CreateDynamicArrayEnum pEnum not freed

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#50412]
Also from coverity.

CreateDynamicArrayEnum values aren't freed on error paths. For example:

https://github.com/dotnet/runtime/blob/82c705102a34c36c5395eb8804109f54c9750d90/src/coreclr/md/compiler/import.cpp#L74-L84

The allocated `pEnum` is not freed in `ErrExit`.

Are these accepted leaks? Or should we fix them?

cc @jkotas @janvorli @omajid

**Comment by janvorli** [comment]
Thank you for reporting this, it should be fixed.
