### ISSUE TITLE
SymReader::InitializeFromFile opens a few handles but never closes them

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#50422]
https://github.com/dotnet/runtime/blob/45fbba6a539fe2054d379faf697dab28d9be2828/src/coreclr/debug/ildbsymlib/symread.cpp#L543-L546

This method calls `WszCreateFile`, `WszCreateFileMapping` and `MapViewOfFile` but never `UnmapViewOfFile` or `CloseHandle`. It looks like it will leak resources on every call.

Other methods in this file, such as `SymReader::VerifyPEDebugInfo`, cleanup all resources before they return.

**Comment by tommcdon** [comment]
@omajid thank you for the bug report! Feel free to send us a PR if you are interested in contributing a fix.
