### ISSUE TITLE
DotNet 5 Blazor Debug.Writeline triggering DevToolsProxy[0] error.

### ISSUE THREAD

**Issue by JayGormley** [dotnet/runtime#50429]
I create a default .net 5 blazor web assembly app. Add simple code in the NavMenu.razor for a button that is supposed to write a message to the debug window using a simple System.Diagnostics.Debug.WriteLine() statement and it fails.  I get no results in the debug window while debugging yet the code executes when stepping through it.  Instead of displaying my messages in the debug window I get the following error in the projectname - AspNetCore Web Server output window:

 fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0]
      sending error response for id: msg-1710285C60A07130946D42BE3F293A0E:::1034 -> [Result: IsOk: False, IsErr: True, Value: , Error: {
        "result": {
          "type": "object",
          "subtype": "error",
          "description": "Failed to resolve member access for System.Diagnostics.Debug",
          "className": "ReferenceError"
        }
      } ]

Can easily be reproduced for me using the default startup .net 5 blazor web assembly app. Adding the following code to the NavMenu.razor file:

In the markup added a button the the nav div:
<button class="list-group-item list-group-item-action bg-light" @onclick="WriteTest">
        <span class="oi oi-list-rich" area-hidden="true"></span> Write Test
</button>

In the code section:
private void WriteTest()
        {
            System.Diagnostics.Debug.WriteLine("This is a test debug message!");
        }

**Comment by lewing** [comment]
I believe this is fixed in .NET 6.
