### ISSUE TITLE
Add more AsSpan overloads to StringSegment

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#50428]
## Background and Motivation

Many classes provide `AsSpan` methods and most provide at least the 3 basic methods, `AsSpan()`, `AsSpan(int start)`, `AsSpan(int start, int length)`.

The `StringSegment` class only provides `AsSpan()`, but it should provide the other two for consistency and ease of use.

## Proposed API

```diff
namespace Microsoft.Extensions.Primitives
{
    public readonly struct StringSegment : IEquatable<StringSegment>, IEquatable<string>
    {
        public ReadOnlySpan<char> AsSpan();
+       public ReadOnlySpan<char> AsSpan(int start);
+       public ReadOnlySpan<char> AsSpan(int start, int length);
    }
}
```

## Usage Examples

``` C#
// input.AsSpan().Slice(startIndex, typeLength);
input.AsSpan(startIndex, typeLength);
```

## Alternative Designs

No, other classes that provide `AsSpan` have similar overloads

## Risks

None

**Comment by bartonjs** [comment]
Looks good as proposed.

```C#
namespace Microsoft.Extensions.Primitives
{
    partial struct StringSegment : IEquatable<StringSegment>, IEquatable<string>
    {
       public ReadOnlySpan<char> AsSpan(int start);
       public ReadOnlySpan<char> AsSpan(int start, int length);
    }
}

**Comment by gfoidl** [comment]
I'd like to add these overloads.
