### ISSUE TITLE
Backport GCConfigs knobs to .net core 3.1

### ISSUE THREAD

**Issue by pnagori02** [dotnet/runtime#50430]
The new configs added in .net 5 are very useful is controlling & configuring the memory limits on containers.
We are on .net core 3.1 with our deployment in AKS. It would be great if we can backport these to 3.1 since we want to leverage them.
  System.GC.HighMemoryPercent
System.GC.HeapHardLimitSOHPercent,
System.GC.HeapHardLimitLOHPercent.
There are lot of companies running on 3.1 since it is LTS & would want to control them specially in container cases. It will help them as well. @Maoni0 @richlander @jkotas

**Comment by mangod9** [comment]
Hi @pnagori02, `GCHighMemPercent` and `GCHeapHardLimitPercent` should exist in 3.1. `SOH` and `POH` Percent settings are new in 5.

**Comment by pnagori02** [comment]
@mangod9 As per the documentation it says .net 5.

Setting name | Values | Version introduced
-- | -- | --
System.GC.HighMemoryPercent | decimal value | .NET 5.0

GCHeapHardLimitPercent  is there in 3.0 so it does not mention in this bug.

**Comment by mangod9** [comment]
> As per the documentation it says .net 5.

@cshung can confirm, but `GCHighMemPercent` should be available as an environment variable in 3.1. It was configurable via runtimeconfig in 5.

**Comment by pnagori02** [comment]
@jkotas This is for https://www.mediakind.com/ & we work on a B2B product. We are also raising this through our Microsoft support channel.
We have recently updated to 3.1.  We have 20 micro services with a good amount of C# code.
Our microservices load the in memory data of ~5 GB & we have lot of objects in gen2 & LOH.
This is the nature of our service. We do run into some of the existing open bugs for ex. - https://github.com/dotnet/runtime/issues/851

In our use case we want a lower value than 90 for GC to be aggressive.
As of now .net 5 is not in our upgrade path & we want to move directly to 6. This is because 3.1 is LTS & we don't want to move 5 which is STS. Also with the size of our Backend teams it is difficult to upgrades every 6 month. Thanks.

**Comment by Maoni0** [comment]
@pnagori02 is using an env var sufficient for your case?

**Comment by pnagori02** [comment]
Thanks @Maoni0 , Yes we can use environment variable.
As per above comment COMPlus_GCHighMemPercent is available in 3.1 ? We can see it here - https://github.com/dotnet/corert/blame/f2526602b0fd2897f9c0cbc637c322c8a167eb80/src/Native/gc/gcconfig.h#L114

Explicitly we are looking to a customized value for GCHighMemPercent only, others for now is OK.

**Comment by Maoni0** [comment]
yes it is supported on 3.1. we should document this. @gewarren I think I missed telling you the version for the env var for this config somehow. the [high mem percent config](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#high-memory-percent) should say .NET core 3.0 and .NET Framework 4.7.2 for the env var option. could you please get this added? thanks!

**Comment by pnagori02** [comment]
Thanks @Maoni0 .It would be good to mention in the docs that it will be hex format.

**Comment by Maoni0** [comment]
@pnagori02  this is mentioned at the top of the config page:

> For number values, use decimal notation for settings in the runtimeconfig.json file and hexadecimal notation for environment variable settings. For hexadecimal values, you can specify them with or without the "0x" prefix.
