### ISSUE TITLE
System.IO.Ports.SerialPort w/ WSL2 "Inappropriate ioctl for device"

### ISSUE THREAD

**Issue by pix64** [dotnet/runtime#50444]
### Description

System.IO.Ports.SerialPort fails to open ports when ran under WSL 2

System.UnauthorizedAccessException: 'Access to the port '/dev/ttyS1' is denied.'
Inner Exception: IOException: Inappropriate ioctl for device

Happens w/ System.IO.Ports 5.0.1 and 6.0.0-preview.2.21154.6
.NET 5.0, Ubuntu 20.04 (x64) under WSL2

```
using System.IO.Ports;
using System;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var port = new SerialPort("/dev/ttyS1");
            port.Open();
        }
    }
}
```

**Comment by Jozkee** [comment]
This is not supported by WSL2 as of today so I doubt we can do something on our side.
https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#can-i-access-the-gpu-in-wsl-2--are-there-plans-to-increase-hardware-support-

> As of right now WSL 2 does not include serial support, or USB device support.

Also found this related open issue https://github.com/microsoft/WSL/issues/4322
