### ISSUE TITLE
Crash in some tvOS test suite runs

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#50453]
In trying to bring up tvOS simulator runs on CI, there appears to be reliable crashes in a handful of suites.  What you'll find is that the tests actually start running, but at some seemingly random point the app will crash.

To reproduce:

```
./build.sh -Subset mono+libs -os tvOSSimulator -arch x64
./dotnet.sh build /t:Test src/libraries/System.Globalization/tests/ /p:TargetOS=tvOSSimulator /p:TargetArchitecture=x64
```

The following suites are impacted:

```
Microsoft.Bcl.AsyncInterfaces
System.CodeDom
System.Composition.Hosting
System.Composition.TypedParts
System.Dynamic.Runtime
System.Globalization
System.Linq.Expressions
System.Linq.Queryable
System.Linq
System.Numerics.Vectors
System.Runtime.CompilerServices.Unsafe
System.Runtime.InteropServices
System.Security.Cryptography.Primitives
System.Threading.Tasks
System.Xml.RW.*
System.Xml.XmlDocument
```

Running in Xcode doesn't give too many hints:

<img width="1237" alt="Screen Shot 2021-03-30 at 6 41 02 PM" src="https://user-images.githubusercontent.com/471438/113065853-843af180-9187-11eb-9c53-e406ae3816e6.png">

**Comment by CoffeeFlux** [comment]
I can reproduce this locally.

This happens reliably in a ThreadPool thread, and the test seems to be `AbbreviatedMonthGenitiveNames_Format_ReturnsExpected` more often than not. I'll try running that test on its own and see if this still reproduces.

The other threads all appear to report a functional stack trace, so it's not a problem with symbol resolution – I guess this is in jitted memory? That's kind of concerning, and extremely bizarre that it's only happening on tvOS.

**Comment by CoffeeFlux** [comment]
Running just that test seems to pass reliably.

**Comment by CoffeeFlux** [comment]
Running only that file fails reliably, on the same test: `AbbreviatedMonthGenitiveNames_Format_ReturnsExpected`

**Comment by CoffeeFlux** [comment]
The logging seems to be deceptive, and running only `AbbreviatedMonthGenitiveNames_FormatWithNull_ThrowsNullReferenceException` _does_ reliably crash.

**Comment by CoffeeFlux** [comment]
https://github.com/dotnet/runtime/issues/50667 would make this easier

**Comment by CoffeeFlux** [comment]
Given the crash is from trying to access `0x10`, I assume we're failing to emit a null check here for some reason.

It should be possible to repro using only this snippet once we have a tvOS sample to use:
```
            var v = new string[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" };
            var format = new DateTimeFormatInfo
            {
                AbbreviatedMonthGenitiveNames = v
            };
            v[0] = null;

            var dateTime = new DateTime(2014, 1, 28);
            try {
                dateTime.ToString("dd MMM yy", format);
            } catch (NullReferenceException) {
                Console.WriteLine("NRE thrown");
            }
```

This does not happen with the interpreter, so it's presumably a JIT issue. No idea why it would be tvOS specific... Will try to find a more minimal repro.

**Comment by CoffeeFlux** [comment]
Probably related: https://github.com/dotnet/runtime/commit/c329f7325925379883356c52f5f6b471e3b99c7f

**Comment by CoffeeFlux** [comment]
Adding `    setenv("MONO_DEBUG", "explicit-null-checks", TRUE);` to AppleAppBuilder fixes the issue, so that commit is definitely what's going on. Setting the explicit null checks does work as a temporary fix, but we need to decide how we want to address this long-term. cc: @imhameed @lambdageek

**Comment by lambdageek** [comment]
Thanks for investigating, Ryan!

I'm confused about https://github.com/dotnet/runtime/commit/c329f7325925379883356c52f5f6b471e3b99c7f

does the task-wide no-op exception handler inhibit the host-wide mach exception -> posix signal translation, too?  Or does it just prevent LLDB from installing their own task-wide exception handler, @imhameed ?

AFAIK mono implements implicit null checks by handling SIGSEGV and checking whether it came from JITed managed, or AOTed code.  So if we never get segvs, we would never get an NPE.

The crash on tvOS would mean that the fault IP -> MonoMethod lookup doesn't think the crash originates in a managed method.  Which possibly means there's a race condition, or maybe we don't have the right info available in a tvOS simulator.  @vargaz  is there something special about NPEs on tvOS?

> Running just that test seems to pass reliably, while running the full file fails reliably with the same last printed test.

That's suspicious.  I guess a race condition would explain it, though.

**Comment by CoffeeFlux** [comment]
I think you misunderstand—the reason that test passed reliably is because it was the wrong test. If you run the NRE test standalone, it will fail every time.

**Comment by imhameed** [comment]
> Thanks for investigating, Ryan!
> 
> I'm confused about [c329f73](https://github.com/dotnet/runtime/commit/c329f7325925379883356c52f5f6b471e3b99c7f)
> 
> does the task-wide no-op exception handler inhibit the host-wide mach exception -> posix signal translation, too? Or does it just prevent LLDB from installing their own task-wide exception handler, @imhameed ?

It shouldn't. If it did, macOS and iOS would fail too.

> 
> AFAIK mono implements implicit null checks by handling SIGSEGV and checking whether it came from JITed managed, or AOTed code. So if we never get segvs, we would never get an NPE.
> 
> The crash on tvOS would mean that the fault IP -> MonoMethod lookup doesn't think the crash originates in a managed method. Which possibly means there's a race condition, or maybe we don't have the right info available in a tvOS simulator. @vargaz is there something special about NPEs on tvOS?

Neither watchOS nor tvOS pass a usable `ucontext_t` to `SA_SIGINFO` signal handlers. They also don't support `setcontext`. These are used by our `SIGSEGV` -> `NullReferenceException` translation code. In their absence, we should fall back to explicit null checks. It looks like we do this already when llvmonly mode is used: https://github.com/dotnet/runtime/blob/12edbc0170403e38fb7a1925cc9794e7fdf481e4/src/mono/mono/mini/aot-compiler.c#L8827-L8828

**Comment by imhameed** [comment]
> Adding ` setenv("MONO_DEBUG", "explicit-null-checks", TRUE);` to AppleAppBuilder fixes the issue, so that commit is definitely what's going on. Setting the explicit null checks does work as a temporary fix, but we need to decide how we want to address this long-term.

Maybe we should unconditionally define `MONO_ARCH_EXPLICIT_NULL_CHECKS` to `1` when building for watchOS or tvOS, even when targeting an amd64 simulator. We can catch `SIGSEGV` (and `SIGFPE`) on watchOS and tvOS, but we can't rewrite the execution context to point somewhere that translates the signal to a .NET-level exception, so we have to use explicit null and arithmetic checks for these targets.

**Comment by CoffeeFlux** [comment]
Unconditionally enabling explicit null checks whenever we're targeting watchOS or tvOS sounds fine to me if we can't handle the exception properly on those platforms at all. I'll PR that later today—thanks!

**Comment by lambdageek** [comment]
Looks like we also define `MONO_ARCH_HAS_NO_PROPER_MONOCTX` for tvOS on arm64 and it's used by the interpreter.  Do we need that for the simulator too?
