### ISSUE TITLE
Investigate Mono performance for certain Xamarin Mac benchmarks

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#50455]
Of the tests [here](https://github.com/rolfbjarne/xamarin-macios/blob/2ec96e26a5e4b8d0ec458c0695f3e46b81ecbe48/tests/dotnet/CoreCLRPerfTest/ObjCBridge.cs), the following were at least 2x slower on Mono than on CoreCLR, the first two by a factor of ~15x:

* CallReturnString_LongString
* CreateObject
* CallReturnString_ShortString

We should investigate why and optimize this if possible, as it seems likely that the same issue would also affect mobile scenarios.

cc: @lambdageek

**Comment by CoffeeFlux** [comment]
cc: @SamMonoRT we should consider profiling this, given the dramatic difference

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by SamMonoRT** [comment]
Closing this issue. Measuring most of .NET MAUI.
