### ISSUE TITLE
Allow int.ToString and Parse to support radixes other than base-10 and base-16

### ISSUE THREAD

**Issue by kingcean** [dotnet/runtime#50491]
## Background and Motivation

In ECMAScript (JS) world, we can parse an integer with a radix to specify its positional notation like following.

```javascript
parseInt("120", 12);  // -> 168
parseInt("120", 10);  // -> 120
```

And we can also stringify a number (convert a number to string) with a radix (positional notation) like following.

```javascript
(168).toString(12);  // -> "120"
(120).toString(10);  // -> "120"
(3.14159265).toString(30); // => "3.47d01bpf"
```

Currently now .NET only supports DEC and HEX but JS supports 2-36.

## Proposed API

```diff
namespace System
{
    public struct Int32 : IComparable, IComparable<int>, IConvertible, IEquatable<int>, IFormattable
    {
+        public string ToString(int radix);
+        public static int Parse(string s, int radix);
+        public static int Parse(ReadOnlySpan<char> s, int radix);
+        public static bool TryParse(string s, int radix, out int result);
+        public static bool TryParse(ReadOnlySpan<char> s, int radix, out int result);
        // ... other fields and methods.
    }
    public struct Int64 : IComparable, IComparable<long>, IConvertible, IEquatable<long>, IFormattable
    {
+        public string ToString(int radix);
+        public static long Parse(string s, int radix);
+        public static long Parse(ReadOnlySpan<char> s, int radix);
+        public static bool TryParse(string s, int radix, out long result);
+        public static bool TryParse(ReadOnlySpan<char> s, int radix, out long result);
        // ... other fields and methods.
    }
    public struct Decimal : IComparable, IComparable<decimal>, IConvertible, IEquatable<decimal>, IFormattable
    {
+        public string ToString(int radix);
        // ... other fields and methods.
    }
    public struct Single : IComparable, IComparable<float>, IConvertible, IEquatable<float>, IFormattable
    {
+        public string ToString(int radix);
        // ... other fields and methods.
    }
    public struct Double : IComparable, IComparable<double>, IConvertible, IEquatable<double>, IFormattable
    {
+        public string ToString(int radix);
        // ... other fields and methods.
    }
}
```

## Implementation

Following are some sample codes of the implementation to convert a number to a string with a specific radix.

- [`int.ToString`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L112)
- [`long.ToString`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L136)
- [`double.ToString`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L171)

Following are about parsing.

- [`int.Parse`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L259)
- [`long.Parse`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L279)
- [`int.TryParse`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L324)
- [`long.TryParse`](https://github.com/nuscien/trivial/blob/a550fb5795b938cc72d03f4fcf29695cbb0ecd4a/Core/Maths/Arithmetic/Basic.cs#L375)

## Usage Examples

```csharp
int.Parse("120", 12);  // -> 168
int.Parse("120", 10);  // -> 120

168.ToString(12);  // -> "120"
120L.ToString(10);  // -> "120"
(3.14159265).ToString(30); // => "3.47d01bpf"
```

**Comment by GrabYourPitchforks** [comment]
I've updated the issue title to be a bit more descriptive. Can you describe your scenario a bit more? We already have inbox support for base10 and base16. Is base2 (binary) the most interesting radix for your workloads?

The main ECMAScript has a radix parameter is that historically, its _parse_ routine tries to deduce the representation of the incoming number, but this can lead to incorrect guesses. For example, `parseInt("0123")` will \[in older engines\] see the leading `'0'` and treat the incoming string as octal instead of decimal. This necessitates passing an explicit __10__ for the _radix_ parameter for the common scenario of wanting the treat the incoming string as decimal-formatted.

.NET doesn't have this same behavior, since all numbers are emitted and parsed as decimal by default. There's no auto-detection of octal vs. hex vs. decimal in the parsing routines. So there has historically been no need to have a specialized _radix_ parameter.

**Comment by kingcean** [comment]
Sometimes I need use following radixes.

- Base 2 for binary.
- Base 36. It represents a number in the string with the shortest length.

**Comment by stephentoub** [comment]
Just FYI, the Convert class already supports the ToString aspect of this for base 2, 8, 10, and 16, e.g.
```C#
Convert.ToString(12345, 2)
```
produces
```
"11000000111001"
```

**Comment by tannergooding** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/83619

While this API would be "more extensible" overall, it doesn't fit the current conventions and would be more work for less obvious overall benefits.

`Convert.ToString` does allow binary already as Stephen pointed out.
