### ISSUE TITLE
GSSAPI Error from NTLM Authentication Attempt from .net core Web API Running in AWS Lambda Runtime

### ISSUE THREAD

**Issue by AlexanderA7** [dotnet/runtime#50522]
I have a .net core 3.1 Web API running in AWS lambda trying to use NTLM authentication to another webapiproxy hosted by IIS.
I receive the error message below in the lambda logs when the request is made. 
![image](https://user-images.githubusercontent.com/77363330/113220457-71382800-9240-11eb-806a-dd21375c5373.png)

We have copied the gssntlm-ssp library and it's dependencies into the \publish\lib folder of our .net self-contained linux-64 distribution package that gets pushed to lambda and have verified that these files that should make it work are there. We ran our web api in a Ubuntu linux environment with gssntlm-ssp and it failed. After yum installing gssntlm-ssp, we made our request again and it then passed. So including this library and it's dependencies into our .net package published to lambda should have made our request work as well. What gives?

**Comment by AlexanderA7** [comment]
Exact error is "System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Preauthentication failed)."  Couldn't really find anything online pertaining to this exact issue. The webapiproxy that the request is being made to is logging an unauthorized http status code.

**Comment by wfurt** [comment]
Packaging gssntlm with your app is not sufficient. .NET has no direct dependency on in. It needs to be registered with OS  GSSAPI layer. You can check /etc/gss/mech.d/mech.ntlmssp.conf that the package delivers.

**Comment by AlexanderA7** [comment]
Yes. That makes sense. But how can this file be modified inside an AWS lambda which provides no access to that location? From my understanding, only files in /tmp can be read by lambda function.

**Comment by wfurt** [comment]
I don't think you can @AlexanderA7. You would need to switch to use containers. 
You could opt-in to old curl handler e.g. `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`
That will probably work for 3.1 but that option is gone in 5.0+
Alternatively you can embark on experimental path described in #887 (and the separate forks) . That will probably be part of 6.0.

**Comment by karelz** [comment]
Triage: Looks like the best option is to use containers as suggested above.
Closing.

**Comment by AlexanderA7** [comment]
Yes. Thanks.
