### ISSUE TITLE
Annotate unsupported APIs in System.Net

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#50530]
As part of https://github.com/dotnet/runtime/issues/47228 i am running an analyzer to detect APIs throwing PNSE but not annotated with Obsolete/SupportedOSPlatform/UnsupportedOSPlatform attributes, we need to annotate them so that developers get warnings when they use them unexpectedly

For now, I have results only for cross-platform builds, analysis of targeted builds are coming soon which could detect more APIs and will be added here

API | Comment | Suggestion | Location
-- | -- | -- | --
'WebSocket.RegisterPrefixes()' | unconditionally throws on all platforms | add [Obsolete] | libraries\System.Net.WebSockets\src\System\Net\WebSockets\WebSocket.cs(172,13)
All APIs in Quic |Seems only supported on windows, Linux, OSX, FreeBSD | add assembly level SupportedOSPlaform("windows"), SupportedOSPlaform("Linux"), SupportedOSPlaform("OSX"), SupportedOSPlaform("FreeBSD") attributs | runtime\artifacts\obj\System.Net.Quic\net6.0-Debug\System.Net.Quic.notsupported.cs(103,49)

Note: We are suggesting adding [Obsolete] for the APIs only supported in .Net framework but not supported in .NetCore, with the corresponding Message, DiagnosticId, and UrlFormat https://github.com/dotnet/runtime/blob/cecc76a29a8b6c1fca181a38f076b4d949081746/src/libraries/System.Net.Requests/src/System/Net/AuthenticationManager.cs#L17 You can claim the next available DiagnosticId from Obsoletions.cs .

cc @jeffhandley @terrajobst @GrabYourPitchforks

**Comment by marek-safar** [comment]
System.Net.Quick is already correctly annotated but the information propagation is blocked by #49278. I'd suggest resolving that issue first before putting more workarounds in.

**Comment by buyaa-n** [comment]
> System.Net.Quick is already correctly annotated

Hmm, I don't see assembly-level attributes, I might be missing something or you might be meant about API/Type level attributes. As this throws on all other platforms unconditionally I would add assembly-level Supported attribute for all supported ones

> but the information propagation is blocked by #49278.  I'd suggest resolving that issue first before putting more workarounds in.

System.Security.Cryptography.Algorithms and System.IO.Ports not included in this analysis because they don't have a cross-platform target, I might have more compatibility info after running analysis for targeted builds

**Comment by ManickaP** [comment]
S.N.Quic solved in https://github.com/dotnet/runtime/pull/49261
