### ISSUE TITLE
BAD_FREE for release_card_table?

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#50551]
Coverity reports an issue for:
```
release_card_table (&old_card_table[card_word (card_of(la))]);
```

It says:
```
Error: BAD_FREE
address_free: "release_card_table" frees address of "old_card_table[SVR::card_word(this->card_of(la))]".
```

Somehow Coverity thinks that instead of freeing the address that is in the table, we're trying to free at an offset in the table.

I'm not sure if this is a real issue, or a false positive because Coverity has an issue understanding the functions/data structures.

cc @Maoni0 @omajid

**Comment by jkotas** [comment]
Looks like a false positive to me.

**Comment by Maoni0** [comment]
right, it's a false positive. old_card_table[0] is not actually a real physical location, we just use it to make our calculation simpler. `old_card_table[card_word (card_of(la))]` is where the allocation physically starts.

**Comment by mangod9** [comment]
closing as by design for now. Please reopen if any action is required.
