### ISSUE TITLE
Inconsistent Behaviour for Uri.TryCreate on Windows/Linux

### ISSUE THREAD

**Issue by RichMercer** [dotnet/runtime#50564]
### Description

I am seeing a difference in behaviour on different platforms when calling Uri.TryCreate (string? uriString, UriKind uriKind, out Uri? result);

I am using the following call in my code:
`Uri.TryCreate("/a-relative-path", UriKind.Absolute, out var uri);`

On Windows the the method returns `false` and `out Uri?` is null. 

On Linux it returns `true` and `out Uri?` is "file:///a-relative-path/".

### Configuration

Running .NET 5.0 on Azure Linux App Service for production and locally on Windows 10. It also seems to work this way on .NET Core 3.1.x too.

**Comment by stephentoub** [comment]
For better or worse, this is by design, stemming from Uri's ability to implicitly represent file paths, and absolute file paths on Unix beginning with a forward slash.

**Comment by RichMercer** [comment]
I double checked the docs and didn't see this called out which would have saved a lot of head scratching and trying to debug across different platforms.

**Comment by stephentoub** [comment]
I've no doubt the docs could be improved :smile:

It is covered at https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0, e.g.
> Uri can also be used to represent local file system paths. These paths can be represented explicitly in URIs that begin with the file:// scheme, and implicitly in URIs that do not have the file:// scheme.

and

> These implicit file paths are not compliant with the URI specification and so should be avoided when possible. When using .NET Core on Unix-based systems, implicit file paths can be especially problematic, because an absolute implicit file path is indistinguishable from a relative path. When such ambiguity is present, Uri default to interpreting the path as an absolute URI.

But, anything we can do to help clear it further would be great.  Please feel free to make suggestions or even submit PRs with improvements at https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Uri.xml.

Thanks!

**Comment by iSazonov** [comment]
No doubt this example could be in the documentation as a warning for cross platform developers.

**Comment by RichMercer** [comment]
Thanks @stephentoub, I didn't think to check further up than the method call so mea culpa. I only checked the the TryCreate docs but it might be good to have a warning in there too as it directly impacts that method on Unix-based systems.

**Comment by stephentoub** [comment]
No mea culpa required.  The docs exist to help educate.  If they're not succeeding in conveying all the necessary information, something needs to be improved :smile:

**Comment by karelz** [comment]
Triage: Seems to be documented. If there is PR for improvement of some docs, we will be happy to take them. Thanks!
