### ISSUE TITLE
System.Collections.Immutable.Tests fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50579]
One test from System.Collections.Immutable.Tests fails on Android

- [ ] System.Collections.Immutable.Tests.ImmutableArrayTest.IStructuralEquatableGetHashCode
- [ ] System.Collections.Immutable.Tests.ImmutableSortedDictionaryTest.Indexer_KeyNotFoundException_ContainsKeyInMessage
- [ ] System.Collections.Immutable.Tests.ImmutableDictionaryTest.Indexer_KeyNotFoundException_ContainsKeyInMessage

```
System.Collections.Immutable.Tests.dll   Failed: 2

Test collection for System.Collections.Immutable.Tests.ImmutableSortedDictionaryTest
System.Collections.Immutable.Tests.ImmutableSortedDictionaryTest.Indexer_KeyNotFoundException_ContainsKeyInMessage
    Assert.Contains() Failure\nNot found: 'c'\nIn value:  Arg_KeyNotFoundWithKey, c

Test collection for System.Collections.Immutable.Tests.ImmutableDictionaryTest
System.Collections.Immutable.Tests.ImmutableDictionaryTest.Indexer_KeyNotFoundException_ContainsKeyInMessage
    Assert.Contains() Failure\nNot found: 'c'\nIn value:  Arg_KeyNotFoundWithKey, c
```
Based on CI runs from https://github.com/dotnet/runtime/pull/50095

**Comment by steveisok** [comment]
@mdh1418 These tests pass on Android and can be re-enabled.
