### ISSUE TITLE
System.Net.Primitives.Functional.Tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50571]
Several tests fail from System.Net.Primitives.Functional.Tests on Android

System.Net.Primitives.Functional.Tests
System.Net.Primitives.Functional.Tests.LoggingTest.EventSource_ExistsWithCorrectId
```
Test collection for System.Net.Primitives.Functional.Tests.LoggingTest
System.Net.Primitives.Functional.Tests.LoggingTest.EventSource_ExistsWithCorrectId
    System.ArgumentNullException : ArgumentNull_Generic Arg_ParamName_Name, collection
```

## PlatformNotSupportedException

- [ ] System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: Packet)
- [ ] System.Net.Primitives.Functional.Tests.SocketAddressTest.ToString_UnsupportedFamily_Throws(family: ControllerAreaNetwork)

Based on CI Runs from https://github.com/dotnet/runtime/pull/50095

**Comment by steveisok** [comment]
The test has a `SkipOnPlatform` and doesn't need to be fixed.
