### ISSUE TITLE
System.Diagnostics.Debug.Tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50570]
Several tests from System.Diagnostics.Debug.Tests fail on Android

- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.Debug_WriteLineNull_IndentsEmptyStringProperly
- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: 0, expectedIndentLevel: 0)
- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: 1, expectedIndentLevel: 1)
- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.IndentLevel_Set_GetReturnsExpected(indentLevel: -1, expectedIndentLevel: 0)
- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.Trace_ClearTraceListeners_StopsWritingToDebugger
- [ ] System.Diagnostics.Tests.DebugTestsUsingListeners.TraceWriteLineIf

Based on CI runs from https://github.com/dotnet/runtime/pull/50095

**Comment by mdh1418** [comment]
Just ran the tests locally, and they pass

**Comment by kotlarmilos** [comment]
@mdh1418 Encountered this while working on something else. May be enabled as this issue is resolved. https://github.com/dotnet/runtime/blob/b35572540e0904c6a23dc5466f73c361ed877dc1/src/libraries/System.Diagnostics.Debug/tests/DebugTestsUsingListeners.cs#L199
