### ISSUE TITLE
System.Security.Cryptography.Csp.Tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50580]
Several tests from System.Security.Cryptography.Csp.Tests fail on Android

- [ ] System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateSecondMinKey
- [ ] System.Security.Cryptography.Dsa.Tests.DSAKeyGeneration.GenerateMinKey

Based on CI runs from https://github.com/dotnet/runtime/pull/50095

**Comment by filipnavara** [comment]
@jkoritzinsky Do you remember if the DSA support on Android has some limitation other than key size >= 1024?

**Comment by filipnavara** [comment]
Nevermind, I suspect the DSA tests were fixed by https://github.com/dotnet/runtime/pull/50192.

**Comment by jkoritzinsky** [comment]
I think the key size >=1024 is the only limitation.

**Comment by filipnavara** [comment]
Thanks for confirmation. Given the timeline of the test run and the fix I tend to believe the DSA was actually fixed one day after the test run.
