### ISSUE TITLE
HttpRequestMessage.Headers.Add should validate the header value

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#50597]
As a security protection it would be nice if `HttpRequestMessage.Headers.Add` would check whether the value contains new lines. If you are allowing your users to send a certain header value, many people probably don't think about the following attack vector:

```c#
var headerValue = "<user-input>";
httpRequestMessage.Headers.Add("x-my-header", headerValue);

// user-input == "test\nx-other-header=value" // whoups
```

What do you think?

Best regards,
D.R.

**Comment by MihaZupan** [comment]
We added more strict new-line validation in #53505 that also addresses concerns raised here.
Thanks for raising the issue and please let us know if you have other concerns around headers.
