### ISSUE TITLE
Consider adding generic type-parameter overloads to `CancellationToken.Register`

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/runtime#50608]
## Background and Motivation

I would love to see an overload of the `CancellationToken.Register` methods that accepts generic type-parameter as an alternative to `object?`. This would ideally avoid unnecessary casting in callbacks, and the potential overhead of boxing/unboxing.

Currently, the only available overloads that exist all require the callback to be of type `object?`. This requires a cast.

```csharp
using System.Threading;
using CancellationTokenSource cts = new();

FooBar fooBar = new();

var registration = cts.Token.Register(
    obj => 
    {
        var fooBarInstance = (FooBar)obj;
    },
    fooBar);

public class FooBar { }
```

## Proposed API

```diff
public readonly struct CancellationToken
{
+   public CancellationTokenRegistration Register<T>(Action<T?> callback, T? state) { }
+   public CancellationTokenRegistration Register<T>(Action<T?, CancellationToken> callback, T? state) { }
+   public CancellationTokenRegistration Register<T>(Action<T?> callback, T? state, bool useSynchronizationContext) { }
}
```

## Usage Examples

Declare and assign a `CancellationTokenRegistration` and have a strongly typed callback:

```csharp
using System.Threading;
using CancellationTokenSource cts = new();

FooBar fooBar = new();

var registration = cts.Token.Register(
    fooBarInstance => 
    {
        // Use the strongly typed fooBarInstance, without casting
    },
    fooBar);

public class FooBar { }
```

## Alternative Designs

I cannot imagine any other alternatives to this, except for what already exists - which is the `object?` based alternative.

## Risks

The primary risk I believe these additions might add is ambiguity with regard to overload resolution.

**Comment by davidfowl** [comment]
@IEvangelist Are you concerned boxing as well?

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/30529.
