### ISSUE TITLE
Need to be able to include Analyzers / Source generators in refpack / transport packages 

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#50621]
We should define binplacing for source-generators that are part of NETCore / ASPNET, similar to what we already do for ref and lib.

We should package those in an analyzers directory following the normal conventions.

**Comment by safern** [comment]
adjusted the area as the ref packs are produced under the installer subset.

**Comment by ericstj** [comment]
Whether or not we do this is still TBD.   It's possible we decide to place these in the SDK along-side analyzers instead.

**Comment by ericstj** [comment]
This work is underway, I have a draft implementation: https://github.com/ericstj/runtime/commit/f478ca1e1a64167da0956022da1d51d562b037d8

Waiting on merging https://github.com/dotnet/runtime/pull/54890 as I wanted to refactor how bits flow between subsets.

**Comment by ViktorHofer** [comment]
The work described in this issue is completed. Closing.
