### ISSUE TITLE
System.Threading.Channels: Peek all channel content

### ISSUE THREAD

**Issue by hamedhajiloo** [dotnet/runtime#50634]
I need to read all the contents of the channel at once

**Comment by davidfowl** [comment]
Why?

**Comment by hamedhajiloo** [comment]
In the consumer, I receive data from db and write it to the channel
I need to tell my query to load the ones that are not in the channel

**Comment by davidfowl** [comment]
Can you share a code sample?

**Comment by hamedhajiloo** [comment]
In the previous comment I made a mistake.

In the Producer side, I receive data from db and write it to the channel
I need to tell my query to load the ones that are not in the channel

for example in producer side i have this sample
```var entities =
                await db.Set<Entity>()
                   .AsNoTracking()
                   .Where(m => m.Status == null)
                   .ToListAsync();

                foreach (var entity in entities)
                {
                    await channel.Writer.WriteAsync(entity);
                }```

At the same time, in the consumer side, the status is updated in db after the job is done
However, the consumer can reload before updating the status.
So I need the code to look like the following.

```
 var channelIds = new List<Guid>();
                //TODO: channelids fill from channel content
                var entities =
                await db.Set<Entity>()
                   .AsNoTracking()
                   .Where(m => m.SendStatus == null)
                   .Where(c=>!channelIds.Contains(c.Id))
                   .ToListAsync();

                foreach (var entity in entities)
                {
                    await channel.Writer.WriteAsync(entity);
                }

``

**Comment by davidfowl** [comment]
Sounds like you want a cursor, so you can avoid duplicating the work that's already been done. Or maybe a boolean to exclude records you've already queued?

**Comment by hamedhajiloo** [comment]
Exactly

**Comment by davidfowl** [comment]
I don't getting all of the data currently queued in the channel is the most efficient way to do what you're trying to do

**Comment by hamedhajiloo** [comment]
However, reading data from the queue seems to be very useful.
What do you think is the best solution?

**Comment by davidfowl** [comment]
What happens if one of the items has failed processing? Do you want to requeue them?

**Comment by hamedhajiloo** [comment]
If something like this happens, the status will not update and I will finally load it and add it to the queue.

**Comment by stephentoub** [comment]
There's no way to do this atomically today, given the implementation: an unbounded channel just uses `ConcurrentQueue<T>`, which does not have the ability to peek at more than the single next item.  As there haven't been a large number of requests for this, we'd have to completely reimplement the primary channel implementation to make this feasible (or update `ConcurrentQueue<T>` to make it possible), and we'd have efficiency concerns with copying everything into a newly-allocated array, I'm going to close this.  Thanks for the interest.
