### ISSUE TITLE
InMemoryDirectoryInfo is unexpectedly dependent on working directory due to its use of GetFullPath.

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#50648]
From the `runtime-coreclr libraries-jitstress` pipeline:

https://dev.azure.com/dnceng/public/_build/results?buildId=1069450&view=ms.vss-test-web.build-test-results-tab

This test fails all Windows arm64 runs (including JITMinOpts=1), with:
```
COMPlus_JITMinOpts=1
COMPlus_TieredCompilation=0
```

```
D:\h\w\BAA10A61\w\A0300974\e>call RunTests.cmd --runtime-path D:\h\w\BAA10A61\p 
----- start Fri 04/02/2021  1:01:32.06 ===============  To repro directly: ===================================================== 
pushd D:\h\w\BAA10A61\w\A0300974\e\
"D:\h\w\BAA10A61\p\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.FileSystemGlobbing.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.FileSystemGlobbing.Tests.deps.json xunit.console.dll Microsoft.Extensions.FileSystemGlobbing.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

D:\h\w\BAA10A61\w\A0300974\e>"D:\h\w\BAA10A61\p\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.FileSystemGlobbing.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.FileSystemGlobbing.Tests.deps.json xunit.console.dll Microsoft.Extensions.FileSystemGlobbing.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Microsoft.Extensions.FileSystemGlobbing.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.FileSystemGlobbing.Tests (found 97 test cases)
  Starting:    Microsoft.Extensions.FileSystemGlobbing.Tests (parallel test collections = on, max threads = 8)
    Microsoft.Extensions.FileSystemGlobbing.Tests.FunctionalTests.VerifyInMemoryDirectoryInfo_IsNotEmpty [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   0
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs(858,0): at Microsoft.Extensions.FileSystemGlobbing.Tests.FunctionalTests.VerifyInMemoryDirectoryInfo_IsNotEmpty()
  Finished:    Microsoft.Extensions.FileSystemGlobbing.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Extensions.FileSystemGlobbing.Tests  Total: 343, Errors: 0, Failed: 1, Skipped: 0, Time: 7.984s
----- end Fri 04/02/2021  1:01:42.74 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
Marking codegen for now

**Comment by BruceForstall** [comment]
This is due to https://github.com/dotnet/runtime/pull/45139

@Jozkee Can you please disable this test (or fix it) ASAP, so we don't see CI failures?

**Comment by ericstj** [comment]
It's just as easy to fix it.  Do a File.Exists check for that file before assuming the globbing API will find it.   Ideally the test would create its own data but I can see how that might be hard here (without mocking) since it is testing the root.

**Comment by ericstj** [comment]
Looks like @Jozkee might be out, I can submit a fix.

**Comment by ericstj** [comment]
Here's the bug:
https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L54-L57

Here's the docs:
https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L21-L26

But that call to GetFullPath isn't prepending `rootDir`, it ends up treating relative paths as relative to the app's working directory.

**Comment by ericstj** [comment]
There are two other places where this is happening in the same type:
https://github.com/dotnet/runtime/blob/aa235f8417c20289017892c2c873dd66c5e4f6e8/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L140
https://github.com/dotnet/runtime/blob/aa235f8417c20289017892c2c873dd66c5e4f6e8/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L152

It feels very wrong for these to be dependent upon the working directory, but we could be misunderstanding the purpose of this type...  Maybe it's just that the comment was wrong.  

@BrennanConroy can you let us know what's expected here?  Looks like its been this way since https://github.com/aspnet/FileSystem/commit/767f07ff39ec66e567d73a034f11bda260ab6123

**Comment by BruceForstall** [comment]
This needs to stay open to track the actual failure.

**Comment by BrennanConroy** [comment]
> can you let us know what's expected here?

I don't really remember. I assume it should be checking if the file is absolute and if not adding `rootDir`.

**Comment by Jozkee** [comment]
Assuming that we could change InMemoryDirectoryInfo to no longer depend on `Path.GetFullPath`, what should `FullName` property return if someone instantiates InMemoryDirectoryInfo with a relative path? It currently returns `Path.GetFullPath(yourRelativePath)`.

I guess we could prefix a dummy/hardcoded root. e.g: 

```cs
var imdi = new InMemoryDirectoryInfo(@".", files: null);
Console.WriteLine(imdi.FullName); // Prints "C:\"

imdi = new InMemoryDirectoryInfo(@"myDirectory", files: null);
Console.WriteLine(imdi.FullName); // Prints "C:\myDirectory"

**Comment by ericstj** [comment]
What does existing usage expect?

What if we didn’t remove usage of `GetFullPath` completely, but made sure to prepend `rootDir` to relative paths as the comment suggests?

**Comment by adamsitnik** [comment]
@Jozkee @carlossanlop were you able to identify the source of the problem? Is this a product bug and we should fix it in 6.0? Or a flaky test and 7.0 should be fine?

**Comment by Jozkee** [comment]
Will try to fix this in 6.0

**Comment by adamsitnik** [comment]
We  have moved it to 7.0 based on offline conversation

**Comment by krwq** [comment]
Here are the symptoms of usage:
https://github.com/dotnet/runtime/issues/93107

basically because of https://github.com/dotnet/runtime/blob/52806bc157decf345005249c9ea7969c8b9e7e1b/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L78
it's empty
