### ISSUE TITLE
Add StreamReader functionality to auto-convert URL to Stream enabling simpler file reads from the web.

### ISSUE THREAD

**Issue by FilipToth** [dotnet/runtime#50684]
## Background and Motivation

Hello, I was thinking of introducing a simple way for the StreamReader class to read files from the web. Or simpler way of reading files from the web. Although, I am not so sure whether it would conflict with the Solid Design Principle. Maybe, an even better way would be to introduce a separate class in System.Net that would have a Read() method that would take a URL as a parameter and simply return what it read as a string. I just think it would be beneficial to have an easy way of reading files from the web. 

## Proposed API

The only change to the API that I'm proposing is to add a check to the ValidateArgsAndOpenPath() method. The following added code will check whether the input path is a valid URL, in which case it will make a new instance of a WebClient and get the stream for the specific URL then, it'll just return the stream.
```diff
+using System.Net

class StreamReader : TextReader
{
     private static Stream ValidateArgsAndOpenPath(string path, Encoding encoding, int bufferSize)
     {
+        if (IsUrl(path))
+        {
+            var client = new WebClient();
+            var stream = client.OpenRead(path);
+            client.Dispose();
+
+            return stream;
+        }           
     }

+    private static bool IsValidUrl(string url) => Uri.IsWellFormedUriString(url, UriKind.RelativeOrAbsolute);
}
```
We could also do it like this:
```diff
- if (IsUrl(path))
+ if (Uri.IsWellFormedUriString(url, UriKind.RelativeOrAbsolute))

- private static bool IsValidUrl(string url) => Uri.IsWellFormedUriString(url, UriKind.RelativeOrAbsolute);
```
Whatever you guys prefer, I would prefer extracting the method.

## Usage Examples

A use case scenario would be creating a custom-built web scraper. Or pretty much anything that has to do with reading files from the web.
``` C#
// My super simple web scraper
var url = "https://raw.githubusercontent.com/dotnet/runtime/main/docs/coding-guidelines/adding-api-guidelines.md";
List<string> lines = new List<string>();

using (var reader = new StreamReader(url))
{
     string line;
     while ((line = reader.ReadLine()) != null)
          lines.Add(line);
}
```

## Alternative Designs

I also considered making a simple method of the WebClient class that would pretty much do just this.

## Risks

There are no breaking changes (As far as I'm concerned) that this proposal would introduce. Although, I am worried whether this complies with the Solid Design principle. It has been pointed out to me that some developers believe that the fact that the StreamReader constructor takes a path as a parameter already conflicts with the Solid Design principle. I would very much like to hear your opinions.

**Comment by huoyaoyuan** [comment]
WebClient has been deprecated and replaced by HttpClient.

Current usage with HttpClient:
```csharp
using var client = new HttpClient();
using(var stream = await client.GetAsync(url))
using(var reader = new StreamReader(stream))
{

}
```

It's encouraged to use async api for web contents, thus can't be performed in constructor.

**Comment by teo-tsirpanis** [comment]
Hello @FilipToth, first of all, [the `WebClient` class is not recommended for new development](https://github.com/dotnet/platform-compat/blob/master/docs/DE0004.md). The recommended alternative is the `HttpClient` class.

You have admitted youself that the `StreamReader` constructor that takes a path violates the SOLID principles. Further expanding its functionality does not seem a good idea to me and I persume the maintainers will concur.

Performing I/O is generally preferred to be done asynchronously, and as @huoyaoyuan said, performing network operations asynchronously is even more compelling to maintain high performance. What is more, an HTTP request will usually have more things to configure, such as headers, authorization, proxy server and so on. Even which `HttpClient` object to use is important, and [these objects are meant to be reused](https://stackoverflow.com/a/15708633/4964734), making me believe that such API would be downright harmful (either creating each client per request, or relying on a hidden global one is equally bad IMHO), and most probably see little use.

---

@huoyaoyuan, thanks for the example but it is wrong. First it does not reuse the `HttpClient` object as I said earlier, and second, the method in the second line should be `GetStreamAsync`.

**Comment by FilipToth** [comment]
Ok, Thank you very much for the explanation.

**Comment by FilipToth** [comment]
Ok, Thank you very much for the explanation.
