### ISSUE TITLE
Review UX from runtime nugets

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/runtime#50707]
Take [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging/) for example. 

 * `Project Site` and `Source Repository` point to https://github.com/dotnet/runtime 
 * `Release notes` points to https://github.com/dotnet/core/tree/main/release-notes

None of those give any contextual help on hos to gets started with or learn about Microsoft.Extensions.Logging

IMO `Project site` should link to https://docs.microsoft.com/en-us/dotnet/core/extensions/logging

`Release notes` should point to what has changed in this specific nuget, or perhaps the logging space (group of nugets)

**Comment by hoyosjs** [comment]
@terrajobst @richlander, who would be the best to answer something like this?

**Comment by joperezr** [comment]
We don't currently have Release Notes for individual packages. We also don't really expose through the UI the commit used to build that specific package version so the best way to figure out the diff between two packages is to open them and check the version info on the assembly for each package, and then use source control to find the changes that went into the new  one. One of the many problems that we would have if we were to add this, is that our packages currently carry multiple TFMs, some of which are not even live built anymore, so getting the release notes right might be tricky. I think a good place to start that might not be too complicated here, would be to add a link to the description of each package that points to the docs.microsoft.com relevant subpage for each package, so we can start from there and then add more things as we go on.

cc: @ericstj

**Comment by ericstj** [comment]
> We don't currently have Release Notes for individual packages. 

We do however, have release notes per release which often cover changes to the packages (like API diffs).  It might be interesting to connect those somehow.

This isn't unique to runtime.  ASP.NETCore has the same issue with its packages, eg: https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization/5.0.5
cc @mkArtakMSFT 


@terrajobst what's your thinking around this?

**Comment by SimonCropp** [comment]
> We don't currently have Release Notes for individual packages. We also don't really expose through the UI the commit used to build that specific package version so the best way to figure out the diff between two packages is to open them and check the version info on the assembly for each package, and then use source control to find the changes that went into the new one.

IMO this is an unreasonable expectation on the many who would like to know this information. wouldnt it be a better use of time for this information to be capture at the time of the change and added to nuget specific release notes?

**Comment by joperezr** [comment]
I agree. We should come up with a better way of communicating this and sharing this info on our packages. @terrajobst do you have any ideas or have you thought of how we can address this?
