### ISSUE TITLE
Add API to read, set and ensure capacity of Collection<T> and ObservableCollection<T>

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/runtime#50725]
## Background and Motivation

Several dynamic collections offer APIs to check the capacity of their underlying arrays and offer ways to increase it if you know the necessary size ahead of time. For example `List<T>.Capacity`, `HashSet<T>.EnsureCapacity(int)` or `Dictionary<TKey, TValue>.EnsureCapacity(int)`.

Recently this capability was added for `List<T>`, `Stack<T>`, and `Queue<T>`, but `Collection<T>` was overlooked. As it is the primary base class for strongly named collections, it should have the same capability.

See https://github.com/dotnet/runtime/issues/44801

## Proposed API

```
I propose to add the following methods:

namespace System.Collections.ObjectModel
{
     public class Collection<T> {
+	 	public int EnsureCapacity(int capacity);
     }
```

## Usage Examples

```
void FeedWork(T[] workload)
{
    // We know that each work item yields at least 3 results, so we can pre-resize for that
	int minCapacity = this.queue.Count + workload.Length * 3;
	this.collection.EnsureCapacity(minCapacity);

	for (T work in workload)
		for (U obj in GetResults(work))
			this.collection.Add(obj);

}
```

## Risks

It increases the surface API.

**Comment by huoyaoyuan** [comment]
`List<T>` is performant, so ensuring capacity can be beneficial. But `Collection<T>` is no that performant.

**Comment by Grauenwolf** [comment]
The performance of `Collection<T>` can be improved without sacrificing it's role as a base class.

**Comment by eiriktsarpalis** [comment]
Unlike `List<T>`, `Stack<T>` or `HashSet<T>` which are concrete implementations, `Collection<T>` wraps arbitrary `IList<T>` values, and therefore exposing an `EnsureCapacity` method is often impossible or meaningless.

Even if we wanted to do this, really we would have to add an `EnsureCapacity` method to `IList<T>`, which we generally avoid due to breaking change concerns.
