### ISSUE TITLE
[Perf] Regressions in Crossgen2 System.Net.WebProxy.dll Size

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#50738]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [3b0c4e426b3ce75f1ef9ed52a8d7726eb7336a57](https://github.com/dotnet/runtime/commit/3b0c4e426b3ce75f1ef9ed52a8d7726eb7336a57)
Compare | [b23205f59ab3853e4b6b43f91a7ca3900c0cc7d0](https://github.com/dotnet/runtime/commit/b23205f59ab3853e4b6b43f91a7ca3900c0cc7d0)

### Regressions in Crossgen2 System.Net.WebProxy.dll Size

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[dll Size](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20System.Net.WebProxy.dll%20Size.html>) | 18.00 KB | 19.50 KB | 1.08 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20System.Net.WebProxy.dll%20Size_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20System.Net.WebProxy.dll%20Size.html>)

<details>

#### Crossgen2 System.Net.WebProxy.dll Size

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by davidwrighton** [comment]
This regression was caused by adding new code to the System.Net.WebProxy dll. See #50368
