### ISSUE TITLE
Deadlock during generic host initialization

### ISSUE THREAD

**Issue by samushenkov** [dotnet/runtime#50734]
### Description

Hello guys.

Sometimes we randomly get a deadlock when use generic host builder.

### Configuration

Docker image used: mcr.microsoft.com/dotnet/core/runtime:3.1 (f5cb081d2836)

### Other information

We took a dump. Here are parallel stacks:

![image](https://user-images.githubusercontent.com/11872649/113573623-2b55d800-9623-11eb-94cb-9ee217309665.png)

For now we turned off console logger for NLog.

**Comment by stephentoub** [comment]
Thanks for the report.  This looks like https://github.com/dotnet/runtime/issues/34197, which was fixed for .NET 5 in https://github.com/dotnet/runtime/pull/34297.  Are you able to repro on .NET 5?

**Comment by samushenkov** [comment]
We have a pretty big code base, so moving to the latest sdk / runtime can take a lot of time. As a workaround we turned off console logging by NLog (since we don't really need it). Just wanted to report in case if it is still actual.

Thank you for fast reply.

**Comment by adamsitnik** [comment]
Since it got already fixed in #34297 and we don't plan to backport it to 3.1, I am going to close the issue.
