### ISSUE TITLE
[Wasm][AOT] Invoking Action<struct> is 7x slower than Action<ref>

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#50757]
### Description

Considering this code, using Mixed mode AOT without profile;

```csharp
private static void TestRegisterColor()
{
    var sw = Stopwatch.StartNew();
    int value = 0;
    for (int i = 0; i < 10000000; i++)
    {
        RegisterColor(null, c => value++);
    }
    sw.Stop();
    Console.WriteLine($"Color: {sw.ElapsedMilliseconds}");
}

private static void TestRegisterOther()
{
    var sw = Stopwatch.StartNew();
    int value = 0;
    for (int i = 0; i < 10000000; i++)
    {
        RegisterOther(null, c => value++);
    }
    sw.Stop();
    Console.WriteLine($"Other: {sw.ElapsedMilliseconds}");
}

private static void RegisterColor(object o, Action<Color> action)
{
    action(new Color());
}

private static void RegisterOther(object o, Action<IDisposable> action)
{
    action(null);
}
```

and 

```csharp
public struct Color
{
  public byte A { get; set; }
  public byte B { get; set; }
  public byte G { get; set; }
  public byte R { get; set; }
}
```

Results are:
```
Color: 1710
Other: 259
```

Repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/Bug50757/Bug50757

### Configuration

b7a164882573af99eaf200c4b21808ecaf6dbb8c

### Regression?

No

**Comment by kg** [comment]
I doubt it will significantly remove the gap, but maybe return an existing Color instance instead of a new one? This test case has to create a new instance and zero it (not THAT expensive, but definitely Work) then pass it as an argument value, vs the ref one just passing a nullptr.

**Comment by jeromelaban** [comment]
There are workarounds for that case specifically for sure (e.g. not use a generic delegate is a very good start), yet there are many cases where this is not possible to change (in the BCL or existing nuget packages).

I'd find interesting for the sharedvt generics exclusion when running mixed-mode AOT to be configurable, as the performance impact is far from neutral.

**Comment by kg** [comment]
I just meant from the perspective of "if this is fixed the two timing values should be ~equal", I absolutely agree

**Comment by CoffeeFlux** [comment]
FYI @jeffschwMSFT most of these wasm AOT-specific issues should just get the AOT label.

**Comment by jeromelaban** [comment]
As per @vargaz's help, adding `-O=gsharedvt` to `aot-cross` allows for gsharedvt code to be AOTed, and gives ~x2 performance improvement in `Action<struct>` invocation performance.

**Comment by SamMonoRT** [comment]
@jeromelaban @vargaz - based on above comment from @jeromelaban - this seems completed ?

**Comment by SamMonoRT** [comment]
Closing this, @jeromelaban please reopen if this is still an issue.
