### ISSUE TITLE
Fix the boxing when using the LoggerMessage.Define is used and values are converted ToString

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#50768]
### Description

Today LoggerMessage.Define is a high performance logging API that aims to reduce the overhead of logging by pre-parsing format strings and parameters holes to log. Today the values are stored in a LogValues\<T0,...,TN\> struct to avoid boxing. We do all of this work only to eventually box these arguments *and* allocate an array to turn this into a string. We should avoid the `object[]` and the boxing here.

### Regression?

No

### Data

```C#
using System;
using Microsoft.Extensions.Logging;

namespace ConsoleApp105
{
    class Program
    {
        static void Main(string[] args)
        {
            var callback = LoggerMessage.Define<int, int>(LogLevel.Information, new(0, "Event"), "This is a {Value} and a {Score}");
            var logger = new Logger();

            Console.WriteLine("Waiting");
            Console.ReadLine();

            for (int i = 0; i < 10000; i++)
            {
                callback(logger, 1, 0, null);
            }

            Console.WriteLine("Done");
            Console.ReadLine();

        }

        public class Logger : ILogger
        {
            public IDisposable BeginScope<TState>(TState state)
            {
                return null;
            }

            public bool IsEnabled(LogLevel logLevel)
            {
                return true;
            }

            public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
            {
                var value = formatter(state, exception);
                LogToSomeplace(value);
            }

            private void LogToSomeplace(string value)
            {
                
            }
        }
    }
}
```

|Type|Allocations|Bytes|Average Size \(Bytes\)|
|-|-|-|-|
| - System.Int32|20,010|480,240|24|
| - System.String|12,115|957,270|79.02|

When I add a 4 int parameters:

|Type|Allocations|Bytes|Average Size \(Bytes\)|
|-|-|-|-|
| - System.String|12,119|1,217,518|100.46|
| - System.Int32|40,010|960,240|24|
| - System.Object\[4\]|10,000|560,000|56|

### Analysis

We need to implement non-allocating formatting for these calls https://github.com/dotnet/runtime/blob/89498d8f6095511d1553fabe39fa8f0579b1cf2d/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L158-L189

**Comment by gfoidl** [comment]
As these methods go down to `string.Format` should this issue be based on https://github.com/dotnet/runtime/issues/14484 (or other similar issues) to have a clean solution without lots of duplications?

`ValueStringBuilder.AppendFormat` operates on `object`s too, so there's not much benefit in using this type.
Special casing some common value types is another possibility, then formatting to Span<char>. But that's a lot of duplicated and potentially outdated code once #14484, etc. are resolved.

As immediate solution one could special case the most common value-types (int, long, DateTime{Offset}, Guid) and have special code for formatting to string / Span<char> and use the ValueStringBuilder. But this is quite a bit of effort, though.

**Comment by davidfowl** [comment]
@gfoidl See https://github.com/dotnet/runtime/issues/50330#issue-842634386. We might be able to use this implementation inside of logging.

cc @geeknoid

**Comment by davidfowl** [comment]
Did some profiling to see if we fixed this because of the new usage of CompositeFormat in the logging codebase. It turns out that we're still calling [TryFormatArgumentIfNullOrEnumerable](https://github.com/dotnet/runtime/blob/ce78f97c8718ca6879e02f278fc10d0e4839ed7c/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LogValuesFormatter.cs#L266)

Which boxes the incoming arguments. Seems like a trivial fix and then we can close this!
