### ISSUE TITLE
[wasm][aot] method calls inside try/finally blocks are expensive

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#50783]
### Description

Given:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
static void MyWorkload() { }

void TryMethod() { 
  try { 
    EmptyMethod(); 
    EmptyMethod();
  }
  finally { }
}

void DirectMethod() { 
  EmptyMethod(); 
  EmptyMethod();
}
```

`TryMethod` executes about slower around 5x in FF and 6.5x in Chrome than `DirectMethod`.

This issue is a migration of https://github.com/mono/mono/issues/13653.

### Configuration

b7a164882573af99eaf200c4b21808ecaf6dbb8c

### Regression?

No

**Comment by vargaz** [comment]
Same as
https://github.com/dotnet/runtime/issues/56309
