### ISSUE TITLE
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by enricobenedos** [dotnet/runtime#50781]
### Description

I have an ASP.Net Core Web API installed on a Ubuntu Server 20.04 LTS virtual machine. I'm facing with a problem during a XML parsing. 
When I'm debugging my API on my macOS the issue does not appear, but when I publish my API on production this error is generated at `Document.Parse(myXML)`:
```
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
``` 

The problem seems related with the file encoding, in this case it is UTF8 with BOM. 
Why on my Mac the file parse does not generate any exception?
Why on ubuntu this is a problem?

### Configuration

Local machine (my dev machine) configuration:

- `macOS Big Sur`: 11.2.3
- `dotnet --version`: 5.0.201
- `Visual Studio`: 8.9.4 (build 25)

Production ubuntu machine:
- `Ubuntu`: 20.04.2 LTS
- `dotnet --version`: 3.1.407

### Other information

Full exception:
```
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text)
```

My code implementation:
```c#
[HttpPost]
        public ActionResult<GPX> PostGPX(GPX gpx)
        {
            try
            {
                //get bytes data
                byte[] data = System.Convert.FromBase64String(gpx.DocumentContent);
                _logger.LogDebug("Converted to byte array");

                //get xml human string
                string convertedXML = ASCIIEncoding.ASCII.GetString(data);

                //Parse the XML to XML object
                XDocument gpxDocument = XDocument.Parse(convertedXML);
                _logger.LogDebug("Created XML document");


                string gpxPath = _configuration.GetValue<string>("TempFolderPath") + "/" + gpx.Name + ".gpx";

                gpxDocument.Save(gpxPath);
                _logger.LogDebug("Saved GPX to {gpxPath}", gpxPath);


                return Ok();
            }
            catch (Exception excp)
            {
                _logger.LogError(excp, "Exception during gpx load");
                return BadRequest();
            }
        }
```

**Comment by krwq** [comment]
@enricobenedos I think it will be hard to debug this unless you provide either base64 or a file which could allow us to reproduce this issue. If you use the same data you're getting on ubuntu and try to parse it on OSX can you repro on one and not on the other?
