### ISSUE TITLE
TlbImp, dotnet core, and ARM64

### ISSUE THREAD

**Issue by austinkinross** [dotnet/runtime#50790]
Tagging @AaronRobinsonMSFT, based on your answer to a related question: 

> At the moment our feeling is that TypeLibConverter will not be brought to .NET Core. This is relatively easy to defend in the TlbImp case since using the .NET Framework TlbImp will create a PIA that is usable in .NET Core - if you know of a scenario where the .NET Framework TlbImp doesn't work, please share!

https://github.com/dotnet/runtime/issues/27698#issuecomment-442930605

I'm trying to port a desktop x64 WPF application to ARM64. On x64, we use TlbImp to generate C# versions of enums/structs etc defined in .IDL files. However, TlbImp doesn't support ARM64:

```
Supported machine types:
    X86
    X64
    Itanium
    ARM
    Agnostic
```

What should I do in this scenario?

**Comment by AaronRobinsonMSFT** [comment]
@austinkinross Great question. The only real pivot here is 32-bit or 64-bit width. I would recommend going with `X64` or ideally `Agnostic` if the target is `ARM64`.

**Comment by austinkinross** [comment]
Great, thanks for the conformation.

I had tried X64/Agnostic before asking the question, but they didn't work. My mistake was that I was passing TlbImpl's output into the old ILAsm that ships with VS. I switched over to the new ILAsm, and things started working as expected: https://www.nuget.org/packages/Microsoft.NETCore.ILAsm/.
