### ISSUE TITLE
Ninja is the default CMake generator on Windows

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#50794]
We now default to using Ninja for our native builds on Windows. Make sure to install Ninja as per the documentation in https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md if you want to use it. You can opt-out by using the `-msbuild` flag in the build scripts.

If you want to open a VS solution for the CoreCLR build, you can use `-vs coreclr.sln` to generate and open a solution in VS for your given configuration and architecture.

**Comment by EgorBo** [comment]
Does `-vs coreclr.sln` re-generate SLN in case if I pulled a lot of commits?

**Comment by jkoritzinsky** [comment]
Yes it should regenerate.

**Comment by mattjohnsonpint** [comment]
Docs PR coming so it doesn't say "optional"?

**Comment by jkoritzinsky** [comment]
Opened a PR for that: https://github.com/dotnet/runtime/pull/50809

**Comment by ViktorHofer** [comment]
Closing as people should now already be aware of the added dependency.
