### ISSUE TITLE
.NET 5 runtime fails on Windows 7

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#50824]
Per [the docs](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50), Windows 7 SP1 is a supported OS for .NET 5. But after installing the .NET 5.0.202 (x64) SDK onto a clean Win7 SP1 VM, the dotnet.exe process fails with this error: 

```
---------------------------
dotnet.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

Windows 7 does not define these API Set facade dlls.

**Comment by hez2010** [comment]
You need to make sure your system satisfies the prerequisites while using .NET 5 on Windows 7 SP1:

- Microsoft Visual C++ 2015-2019 Redistributable [64-bit](https://aka.ms/vs/16/release/vc_redist.x64.exe) / [32-bit](https://aka.ms/vs/16/release/vc_redist.x86.exe)
- KB3063858 [64-bit](https://www.microsoft.com/download/details.aspx?id=47442) / [32-bit](https://www.microsoft.com/download/details.aspx?id=47409)

**Comment by AArnott** [comment]
Thanks. After installing those two, it works. I can't see where that's documented, but it unblocks me.

**Comment by NikolaMilosavljevic** [comment]
.NET install prerequisites for Windows: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50
