### ISSUE TITLE
Microsoft.NET.Runtime.Emscripten.* packages are missing from the preview3 output

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#50822]
Tracking issue to make sure we address this for preview4. It looks like these packages aren't part of the set of packages being uploaded for preview3, perhaps some metadata about this is amiss.

**Comment by lewing** [comment]
cc @steveisok @akoeplinger

Not sure what is going on here but let's figure it out for the next preview.

**Comment by mmitche** [comment]
There was an issue with the staging pipeline that caused it not to populate this feed. Filed https://github.com/dotnet/arcade/issues/7200

Use https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.3.21202.5-2/nuget/v3/index.json for now.

**Comment by akoeplinger** [comment]
Ok, thanks. I don't see the Emscripten packages there though.

@mmitche is there any special setup we need to do? I checked the darc channel mappings and it looks correct to me:

```
(3374) https://github.com/dotnet/emsdk @ main -> .NET 6
(3416) https://github.com/dotnet/emsdk @ release/6.0-preview3 -> .NET 6 Preview 3
```

**Comment by mmitche** [comment]
@akoeplinger That build wasn't put through the staging pipeline. Is this the correct build? https://maestro-prod.westus2.cloudapp.azure.com/1850/https:%2F%2Fgithub.com%2Fdotnet%2Femsdk/latest/graph

Packages don't automatically appear in the output by being assigned the channel. For instance, you might easily end up with an incoherent product because installer might be referencing an older runtime than the latest runtime (e.g. accidental build). We stage installer and then its dependencies get pulled in transitively. We used to gather extensions too (prior to it being decommissioned in .NET 6).

We can update our process to gather this repo in addition to installer, if it's not ever referenced transitively.

**Comment by akoeplinger** [comment]
It looks like the issue is because aspnetcore used `dotnet/runtime` as the repo in Version.Details.xml but these packages are produced by the `dotnet/emsdk` repo: https://github.com/dotnet/aspnetcore/blob/main/eng/Version.Details.xml#L288-L299

**Comment by akoeplinger** [comment]
@mmitche yes the build you linked is the correct one. Is there a way to manually add it to the feed for now to unblock aspnetcore?

**Comment by mmitche** [comment]
@akoeplinger I can't find any assets with those names and versions. It looks like aspnetcore is referencing packages that don't exist?

It looks emsdk should be flowing into aspnetcore. I've added a subscription for that.

**Comment by mmitche** [comment]
See update here: https://github.com/dotnet/aspnetcore/pull/31576

**Comment by akoeplinger** [comment]
hm yeah looks like they used 6.0.0-preview.3.21175.11 copied from `Microsoft.NETCore.App.Runtime.win-x64` in the preview3 Versions.Details.xml and that then didn't get updated: https://github.com/dotnet/aspnetcore/blob/release/6.0-preview3/eng/Version.Details.xml#L288-L299

you're right that the only preview 3 build of dotnet/emsdk is indeed 6.0.0-preview.3.21176.1. @pranavkm I think you'll need to fix that on your end :)

**Comment by mmitche** [comment]
It's too late for p3 at this point, so this will have to be p4. The regular flow for this should now avoid this issue in the future.

**Comment by akoeplinger** [comment]
I see that there's no darc subscription for `dotnet/emsdk release/6.0-preview3` to `dotnet/aspnetcore release/6.0-preview3`, do we need to manually add those whenever a new release branch is created?

**Comment by akoeplinger** [comment]
Ah I see there's https://github.com/dotnet/arcade/blob/main/scripts/create-net6-preview-flow.ps1, sounds like we should add emsdk there. I'll open a PR.

**Comment by mmitche** [comment]
https://github.com/dotnet/arcade/pull/7202

**Comment by akoeplinger** [comment]
With https://github.com/dotnet/arcade/pull/7202 we'll get the flows set up correctly for preview4 branching, I don't think there's anything left for us to do here.
