### ISSUE TITLE
Add ability to run build.cmd -vs corehost.sln

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#50838]
After the change to use Ninja by default, the corehost.sln file is no longer generated. If I understand it correctly it can be retrieved back by running `build.cmd -s Host.Native -msbuild`, but that will trigger a full rebuild of all of the host components.
It would be nice to get a similar functionality to what `build.cmd -vs CoreCLR.sln` does and avoid the rebuild.

**Comment by vitek-karas** [comment]
@jkoritzinsky

**Comment by ViktorHofer** [comment]
Moving to 6.0 as it should be trivial to implement (very similar to coreclr.sln): https://github.com/dotnet/runtime/blob/181f788e09ebbb8e529b438a01f8275e4ec772af/eng/build.ps1#L130-L150

**Comment by davidhunter22** [comment]
Is it even possible to get a corehost.sln using "build.cmd -s Host.Native -msbuild". I got an error when I tried that command in 5.0.7

**Comment by vitek-karas** [comment]
I just tried in `main` and it works for me. What do you mean in `5.0.7`?

**Comment by davidhunter22** [comment]
I mean I downloaded the source with git tag v5.0.7. When I run 
build.cmd -s Host.Native -msbuild
I get 
`C:\Users\david\devel\dotnet\runtime_5.0.7\eng\common\build.ps1 : Missing an argument for parameter 'msbuildEngine'. Specify a parameter of type
'System.String' and try again.
At line:1 char:132
+ ... chitecture=x86 -restore -build /p:subset=Host.Native -msbuild -config ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [build.ps1], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,build.ps1
`
Note I am running this from the root of the checked out tree shoud I be running it elsewhere.
I am new to compiling the runtime so might be doing stuff completly wrong! What I am trying to do is open in Visual Studio a build of the stuff in src\installer\corehost so I can rummage aruind in it and get to understand the code a bit more.

**Comment by jkoritzinsky** [comment]
The -msbuild flag doesn't exist in the release/5.0 branch. It's the default behavior in that branch.

**Comment by elinor-fung** [comment]
This was added in https://github.com/dotnet/runtime/pull/60889
