### ISSUE TITLE
GCLatencyMode.SustainedLowLatency It doesn't work.

### ISSUE THREAD

**Issue by 1290690484** [dotnet/runtime#50847]
### Description

我在一个.net 5 webapi 项目上设置了 GCSettings.LatencyMode = GCLatencyMode.SustainedLowLatency;
之后新建了一个gc诊断日志输出到nohup文件中.
部署在一台2c4g的机器上.
使用Apache Jmeter 压测默认的WeatherForecast接口.
结果发现nohup文件还是存在2代内存堆前台回收,而且数量不少.
我的预期如下图.可以在gc的时候不接受请求.这样我的压测最大的响应时间就不会收到gc暂停的影响.
即便我要多付出一台服务器.

![image](https://user-images.githubusercontent.com/22309360/113878608-58a1b200-97ec-11eb-9eff-eb82a04d4dc7.png)

如上图.如果在2代内存堆gc的时候转发请求到其他服务器上.

### Configuration

.net 5 
centos-release-7-9.2009.0.el7.centos.x86_64

### Data

![image](https://user-images.githubusercontent.com/22309360/113877633-76bae280-97eb-11eb-9cf0-d3907c1748f1.png)

我的输出诊断日志代码

` 

   class GcEventListener : EventListener
    {
        private const int GC_KEYWORD = 0x0000001;
        private const int ThreadPool_KEYWORD = 0x10000;
        private EventSource _dotNetRuntime;
        private readonly EventLevel _eventLevel;
        private HashSet<string> RunedEventNames = new HashSet<string>();
        public GcEventListener()
        {
            Console.WriteLine("GcEventListenerRun");
            _eventLevel = EventLevel.Verbose;
        }

        protected override void OnEventSourceCreated(EventSource eventSource)
        {
            if (eventSource.Name.Equals("Microsoft-Windows-DotNETRuntime"))
            {
                _dotNetRuntime = eventSource;
                EnableEvents(eventSource, EventLevel.Verbose, (EventKeywords)GC_KEYWORD);
            }
        }

        long timeGCStart = 0;

        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            if (eventData.EventName.Contains("GCStart"))
            {
                string typeDesc = string.Empty;
                switch (int.Parse(eventData.Payload[3].ToString()))
                {
                    case 0:
                        typeDesc = "前台阻塞回收";
                        break;
                    case 1:
                        typeDesc = "后台回收";
                        break;
                    case 2:
                        typeDesc = "封锁垃圾收集发生在后台垃圾收集期间";
                        break;
                }
                string reason = string.Empty;

                switch (int.Parse(eventData.Payload[2].ToString()))
                {
                    case 0:
                        reason = "小对象堆分配";
                        break;
                    case 1:
                        reason = "诱导";
                        break;
                    case 2:
                        reason = "内存不足";
                        break;
                    case 3:
                        reason = "空";
                        break;
                    case 4:
                        reason = "大对象堆分配";
                        break;
                    case 5:
                        reason = "空间不足(小物件堆)";
                        break;
                    case 6:
                        reason = "空间不足(大对象堆)";
                        break;
                    case 7:
                        reason = "诱导但不是强制阻塞";
                        break;
                }

                Console.WriteLine($"垃圾回收开始,次数:{eventData.Payload[0]},代:{eventData.Payload[1]},{reason},{typeDesc}");
                timeGCStart = eventData.TimeStamp.Ticks;
            }
            else if (eventData.EventName.Contains("GCEnd"))
            {
                long timeGCEnd = eventData.TimeStamp.Ticks;
                long gcCollections = long.Parse(eventData.Payload[1].ToString());

                Console.WriteLine("{0}GC代{1} 释放耗时 took {2:f3}ms", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss:fff"), gcCollections, (double)(timeGCEnd - timeGCStart) / 10.0 / 1000.0);
            }

            //RunedEventNames.Add(eventData.EventName);
            //Console.WriteLine(string.Join(',', RunedEventNames));
            switch (eventData.EventName)
            {
                //case "GCStart_V2":
                //case "GCStart_V1":
                //    Console.WriteLine($"垃圾回收次数:{eventData.Payload[0]},代:{eventData.Payload[1]},{eventData.Payload[2]},{eventData.Payload[3]}");
                //    break;
                case "GCHeapStats_V1":
                    ProcessHeapStats(eventData);
                    break;
                case "GCAllocationTick_V3":
                    ProcessAllocationEvent(eventData);
                    break;
                case "GCTriggered":
                    Console.WriteLine($"触发GC的原因:{eventData.Payload[0]}");
                    break;
                case "ThreadPoolWorkerThreadStart":
                case "ThreadPoolWorkerThreadStop":
                case "ThreadPoolWorkerThreadRetirementStart":
                case "ThreadPoolWorkerThreadRetirementStop":

                    string eveDes = string.Empty;

                    switch (eventData.EventName)
                    {
                        case "ThreadPoolWorkerThreadStart":
                            eveDes = "工作线程已创建";
                            break;
                        case "ThreadPoolWorkerThreadStop":
                            eveDes = "工作线程已停止";
                            break;
                        case "ThreadPoolWorkerThreadRetirementStart":
                            eveDes = "辅助线程退出";
                            break;
                        case "ThreadPoolWorkerThreadRetirementStop":
                            eveDes = "退休的工作线程再次变为活动状态";
                            break;
                    }

                    Console.WriteLine($"{eveDes}:可用于处理工作的工作线程数，包括已经在处理工作的工作线程数。{eventData.Payload[0]}, 不可用于处理工作，但被保留以备以后使用更多线程的辅助线程数。{ eventData.Payload[1]}");
                    break;
                case "ThreadPoolWorkerThreadAdjustmentSample":
                    Console.WriteLine($"瞬时吞吐量:{eventData.Payload[0]}");
                    break;
                case "ThreadPoolWorkerThreadAdjustmentAdjustment":
                    string reason = string.Empty;
                    switch ((uint)eventData.Payload[2])
                    {
                        case 0:
                            reason = "预热";
                            break;
                        case 1:
                            reason = "正在初始化";
                            break;
                        case 2:
                            reason = "随机移动";
                            break;
                        case 3:
                            reason = "攀登动作";
                            break;
                        case 4:
                            reason = "Change point.更改点";
                            break;
                        case 5:
                            reason = "稳定";
                            break;
                        case 6:
                            reason = "饥饿";
                            break;
                        case 7:
                            reason = "线程超时";
                            break;
                    }
                    Console.WriteLine($"当线程注入（爬坡）算法确定并发级别已到位时，记录控制的更改。平均吞吐:{eventData.Payload[0]} ,新的活动工作线程数{eventData.Payload[1]},原因:{reason}");
                    break;
                //case "ThreadPoolWorkerThreadAdjustmentStats":
                //    Console.WriteLine("");
                //    break;

                case "IOThreadCreate_V1":
                    Console.WriteLine($"在线程池中创建一个I/O线程 : I/O线程数,包括新创建的线程:{eventData.Payload[0]},退休工作线程的数量{eventData.Payload[1]}");
                    break;

                case "IOThreadRetire_V1":
                    Console.WriteLine($"I/O线程将成为淘汰对象 : I/O线程数,包括新创建的线程:{eventData.Payload[0]},淘汰工作线程的数量{eventData.Payload[1]}");
                    break;

                case "IOThreadUnretire_V1":
                    Console.WriteLine($"I/O线程未退出，因为I/O在该线程成为退出候选者之后的等待时间内到达。I/O线程数,包括新创建的线程:{eventData.Payload[0]},淘汰工作线程的数量{eventData.Payload[1]}");
                    break;

                case "IOThreadTerminate":
                    Console.WriteLine($"I/O线程未退出，因为I/O在该线程成为退出候选者之后的等待时间内到达。I/O线程数,包括新创建的线程:{eventData.Payload[0]},淘汰工作线程的数量{eventData.Payload[1]}");
                    break;
            }
        }

        private void ProcessAllocationEvent(EventWrittenEventArgs eventData)
        {
            //Console.WriteLine($"{eventData.Payload[3]},{eventData.Payload[5].ToString()}");
            //_allocatedMemory.TrackValue((ulong)eventData.Payload[3], (string)eventData.Payload[5]);
        }
        private void ProcessHeapStats(EventWrittenEventArgs eventData)
        {
            Console.WriteLine($"{eventData.Payload[0]},{eventData.Payload[1]}");
            //_gen0Size.TrackValue((ulong)eventData.Payload[0]);
            //_gen0Promoted.TrackValue((ulong)eventData.Payload[1]);
            //_gen1Size.TrackValue((ulong)eventData.Payload[2]);
            //_gen1Promoted.TrackValue((ulong)eventData.Payload[3]);
            //_gen2Size.TrackValue((ulong)eventData.Payload[4]);
            //_gen2Survived.TrackValue((ulong)eventData.Payload[5]);
            //_lohSize.TrackValue((ulong)eventData.Payload[6]);
            //_lohSurvived.TrackValue((ulong)eventData.Payload[7]);
        }
    }`

**Comment by huoyaoyuan** [comment]
During the time of GC stop, you can't do anything in managed code. This is by the nature of GC.
Based on my knowledge, GC stop can't be eliminated totally in current implementation. `SustainedLowLatency` just tries it's best to make it shorter.

I wonder *if GC latency is meaningful for any real business logic*.

Sharing more data may be helpful, for example Gen2 stop time you've encountered(your image only shows the time of Gen0), the average/P95/P99 latency.

**Comment by huoyaoyuan** [comment]
Note: it should be impossible to guarantee **maximum** latency on non-realtime platform. Even OS scheduling can introduce random latency.

**Comment by 1290690484** [comment]
@huoyaoyuan @cshung 
我想做的是强制暂停Gen2的回收.因为耗时很大.之后应用会告知调度服务器(一个webapi程序)的内存情况.
预期上是一个百分比.越大代表越需要进行回收.调度器会告诉webapi停止接收请求.之后调度器会再次通知可以开始回收.
回收结束后应该回传调度器结果.然后调度器再分配流量进去.这样就会避免Gen2代回收在我的正常请求上.
我知道Gc有一个事件通知.但是不一定准确.我还在尝试.

**Comment by cshung** [comment]
@1290690484  Would this work? https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/notifications

**Comment by 1290690484** [comment]
@cshung @huoyaoyuan 
后台的Gen2 也会暂停全部线程的时间吗?如果是意义在哪里?
elaticSearch有一个配置是可以在gc的时候不接受请求的.所以我想模仿一下.

**Comment by huoyaoyuan** [comment]
就我的理解，GC的compact是必须暂停一切的，因为要更改所有的reference。
如果你使用batch GC，可能暂停时间会足够长，值得你去做什么。LowLatency的暂停时间应该是比通知另一台服务器更短的。
