### ISSUE TITLE
CodeDomProvider Operation is not supported on this platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#50850]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CodeDomProvider-Operation-is-not-support/1383186)._

---
Hi,

I'm trying to generate a simple code using CodeDomProvider, I've test it on a console application as well as on a web application, everytime it sends me the exception "Operation is not supported on this platform", where can I create this then? or where can I find information about how to do it?

Thnaks.

---
#### Feedback Bot on 3/28/2021, 11:06 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by terrajobst** [comment]
> I'm trying to generate a simple code using CodeDomProvider, I've test it on a console application as well as on a web application, everytime it sends me the exception "Operation is not supported on this platform", where can I create this then? or where can I find information about how to do it?

We need a bit more information:

1. What is the method you're calling that throws the exception?
2. Which .NET version are you running on?

Based on my psychic abilities I'm inclined to believe you're running into this known issue #18768.
