### ISSUE TITLE
System.Text.Json not properly disposing enumerators on exceptions

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#50851]
Related to #48322 and #46349.

The current IEnumerable converters don't dispose of enumerators in certain scenaria where nested element converters throw exceptions. Reproducing test (using a few System.Text.Json.Tests components):
```csharp
[Fact]
public static void WriteIEnumerableT_ElementSerializationThrows_DisposesEnumerators()
{
    var items = new RefCountedList<IEnumerable<int>>(Enumerable.Repeat(ThrowingEnumerable(), 1));
    Assert.Throws<DivideByZeroException>(() => JsonSerializer.Serialize(items.AsEnumerable()));
    Assert.Equal(0, items.RefCount); // items.RefCount evaluates to 1

    static IEnumerable<int> ThrowingEnumerable()
    {
        yield return 42;
        throw new DivideByZeroException();
    }
}
```
Note that #50778 makes changes to the serialization infrastructure to handle IEnumerator disposal in the async case, however changes on the individual converter level will still need to be made. cc @layomia @steveharter.

**Comment by steveharter** [comment]
Suggest moving to 7.0. No community asks that I'm aware of.

**Comment by eiriktsarpalis** [comment]
Note that this should be fixed for Dictionary converters as well.

**Comment by eiriktsarpalis** [comment]
Moving to Future, as we won't have time to work on this in the .NET 7 timeframe.

**Comment by eiriktsarpalis** [comment]
After deliberation we've decided to not fix this concern. It is largely a theoretical bug that no user has reported so far.
