### ISSUE TITLE
[iOS] Calendar not behaving correctly wrt culture

### ISSUE THREAD

**Issue by spouliot** [dotnet/runtime#50859]
### Description

I am re-enabling some tests to confirm ICU is working correctly to replace the _legacy_ mono code for iOS.

Most globalization tests have been re-enabled successfully, except for Calendar tests

https://github.com/xamarin/xamarin-macios/blob/main/tests/linker/ios/dont%20link/CalendarTest.cs

Those are not returning the expected types.

```
DontLink

DontLink.Calendars

DontLink.Calendars.CalendarTest
	[FAIL] Hijri :   Calendar
  Expected string length 34 but was 38. Strings differ at index 21.
  Expected: "System.Globalization.HijriCalendar"
  But was:  "System.Globalization.GregorianCalendar"
  --------------------------------^

		   at DontLink.Calendars.CalendarTest.Hijri() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/dont link/CalendarTest.cs:line 28
	[FAIL] ThaiBuddhist :   Calendar
  Expected string length 41 but was 38. Strings differ at index 21.
  Expected: "System.Globalization.ThaiBuddhistCalendar"
  But was:  "System.Globalization.GregorianCalendar"
  --------------------------------^

		   at DontLink.Calendars.CalendarTest.ThaiBuddhist() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/dont link/CalendarTest.cs:line 35
	[FAIL] UmAlQura :   Calendar
  Expected string length 37 but was 38. Strings differ at index 21.
  Expected: "System.Globalization.UmAlQuraCalendar"
  But was:  "System.Globalization.GregorianCalendar"
  --------------------------------^

		   at DontLink.Calendars.CalendarTest.UmAlQura() in /Users/poupou/git/main/xamarin-macios/tests/linker/ios/dont link/CalendarTest.cs:line 21
DontLink.Calendars.CalendarTest : 226.39 ms
DontLink.Calendars : 229.61 ms
```

### Configuration

* dotnet SDK 6.0.100-preview.3.21202.5 
* the ICU enabled code is not yet merged - in part since I can't re-enable this test
* unit test **Dont link** (where the linker is **not** used) shows the issue

### Regression?

Yes. This is working on the current Xamarin.iOS SDK.

### Other information

[xamarin-macios tracking issue for globalization](https://github.com/xamarin/xamarin-macios/issues/8906)

**Comment by spouliot** [comment]
c.c. @steveisok

**Comment by filipnavara** [comment]
The tests themselves looks somewhat fishy to be honest. The actual expected mapping:
- ar (Argentina, not Arabia) -> System.Globalization.GregorianCalendar
- ps (Persia) -> System.Globalization.PersianCalendar
- th (Thailand) -> System.Globalization.ThaiBuddhistCalendar

It doesn't explain why it would always return Gregorian calendar though.

**Comment by filipnavara** [comment]
The tests themselves looks somewhat fishy to be honest. The actual expected mapping:
- ar (Argentina, not Arabia) -> System.Globalization.GregorianCalendar
- ps (Persia) -> System.Globalization.PersianCalendar
- th (Thailand) -> System.Globalization.ThaiBuddhistCalendar

It doesn't explain why it would always return Gregorian calendar though.

**Comment by spouliot** [comment]
@filipnavara They are old tests we used to ensure DontLink and Link* tests gave the same results.

Being _old_ does does not make them good (or bad) but I disagree with your interpretation of `ar` as "RFC 5646 Language Tags" shows

```
 'ar': 'Arabic',
  'ar-AE': 'Arabic (U.A.E.)',
  'ar-BH': 'Arabic (Bahrain)',
  'ar-DZ': 'Arabic (Algeria)',
  'ar-EG': 'Arabic (Egypt)',
  'ar-IQ': 'Arabic (Iraq)',
  'ar-JO': 'Arabic (Jordan)',
  'ar-KW': 'Arabic (Kuwait)',
  'ar-LB': 'Arabic (Lebanon)',
  'ar-LY': 'Arabic (Libya)',
  'ar-MA': 'Arabic (Morocco)',
  'ar-OM': 'Arabic (Oman)',
  'ar-QA': 'Arabic (Qatar)',
  'ar-SA': 'Arabic (Saudi Arabia)',
  'ar-SY': 'Arabic (Syria)',
  'ar-TN': 'Arabic (Tunisia)',
  'ar-YE': 'Arabic (Yemen)',
```

**Comment by filipnavara** [comment]
I stand corrected on the Arabic. Somehow I was totally convinced because "ar" is used as country code for Argentina (ISO 3166). Nevertheless the `ar` culture and most of its subcultures still return Gregorian calendar. `ar-SA` returns `System.Globalization.UmAlQuraCalendar`.

**Comment by spouliot** [comment]
yeah, like I said the tests were to ensure the same calendar was returned - whether or not the linker was enabled
now was mono correct to return that specific calendar (or not) is another story, one that might have evolved over time (at least for the .net desktop framework side)

**Comment by filipnavara** [comment]
So, apparently the ICU data filters are currently applied on all platforms and these filters (https://github.com/dotnet/icu/blob/313017d0effca6e8ade5fefc8e580224e65d8525/icu-filters/icudt.json#L261-L266) exclude non-Gregorian calendars from the data.

**Comment by steveisok** [comment]
Good catch.  We built the filters initially w/ wasm in mind, so it looks like we'll have to tweak a little bit.

**Comment by lewing** [comment]
How important is ICU data size for iOS?

**Comment by steveisok** [comment]
Well, I haven't heard too much negative feedback re: the current ICU size ;-)

**Comment by marek-safar** [comment]
> How important is ICU data size for iOS?

It's big enough already ;-)

**Comment by tarekgh** [comment]
The framework already has the code for the calendars. This looks to me the issue is just associating the calendar Id to the culture. which I guess can be supported with minimal increase of size.

**Comment by lewing** [comment]
We can either add the calendars back in or change the test, it is a size trade off.  This appears to be marked p0 on iOS so I guess we need information from @spouliot

**Comment by steveisok** [comment]
Found we'll need to include "likelySubtags" in our filter in order for this to be fixed.  Good news is that it only adds .1 MB to the dat file.

**Comment by rolfbjarne** [comment]
I'm seeing different results now with the latest .NET bump: https://github.com/xamarin/xamarin-macios/pull/12064/commits/7e37fe622e772d8fc98c461bef03a68cbd8189bd

**Comment by filipnavara** [comment]
You are seeing the correct results now, ie. same as `net6.0` on desktop with system ICU.

**Comment by steveisok** [comment]
Assuming from the comments that this is fixed.  Please reopen if you find otherwise.
