### ISSUE TITLE
Microsoft.CSharp.Tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50864]
Several tests from Microsoft.CSharp.Tests fail on Android based on #50095 

## Microsoft.CSharp.Tests

- [ ] Microsoft.CSharp.RuntimeBinder.Tests.VarArgsTests.FailBindOnlyVarargsAvailable
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestParamsRuntimeTypes
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams3
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstAndSecondWithSecondArgumentWrongPlace
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestTwiceNamedParams
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams2
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestPositionalUnaffected
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestBadNonTrailing
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstAndSecondWithSecondArgumentNotFound
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestSimpleError
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.OnlyNameFirstArgumentMatchesWrongType
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NonExistentNameOnlyFirstArgument
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestPositionalUnaffected2
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams4
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlySecondWithSecondArgumentWrongPlace
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestParams
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlySecondWithSecondArgumentNotFound
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.OverrideChangesName
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstArgumentWrongPlace
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.AmbiguousInterfaceInheritedMethodError
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.AmbiguousMemberError
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateMethodFromOutside
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromDerivedSameAssemblyCalledOnBase
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromDerivedSameAssemblyCalledOnBase
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldSetFromSameAssembly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromDerivedDifferentAssembly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromDerivedDifferentAssembly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromSameAssembly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromOutside
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallAccessorDirectly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.NullaryCtorCallOnNoNullaryCtor
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallOperatorDirectly
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.QuinaryCtorCallOnNoQuinaryCtor
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.IndexingTests.TargetClassClaimsNonExistentMemberIsIndexer
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.MultiDimArrayTypeNames
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.IncorrectNumberOfIndices
- [ ] Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.ArrayTypeNames

```
Microsoft.CSharp.Tests.dll   Failed: 38

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallAccessorDirectly
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: 'string.Length.get': cannot explicitly ca···\nActual:   CantCallSpecialMethod\n          ↑ (pos 0)
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.NullaryCtorCallOnNoNullaryCtor
    Assert.Contains() Failure\nNot found: 0\nIn value:  BadCtorArgCount
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallOperatorDirectly
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: 'string.operator ==(string, string)': can···\nActual:   CantCallSpecialMethod\n          ↑ (pos 0)
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.QuinaryCtorCallOnNoQuinaryCtor
    Assert.Contains() Failure\nNot found: 5\nIn value:  BadCtorArgCount

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling
Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.MultiDimArrayTypeNames
    Assert.Contains() Failure\nNot found: int[,,]\nIn value:  NoImplicitConv
Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.IncorrectNumberOfIndices
    Assert.Contains() Failure\nNot found: []\nIn value:  BadIndexCount
Microsoft.CSharp.RuntimeBinder.Tests.ArrayHandling.ArrayTypeNames
    Assert.Contains() Failure\nNot found: int[*]\nIn value:  NoImplicitConv

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests
Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.AmbiguousInterfaceInheritedMethodError
    Assert.Contains() Failure\nNot found: 'Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.ICounter1.Count(System.Collections.ICollection)'\nIn value:  AmbigCall
Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.AmbiguousMemberError
    Assert.Contains() Failure\nNot found: 'Microsoft.CSharp.RuntimeBinder.Tests.RuntimeBinderTests.ICounter1.ExplicitCount'\nIn value:  AmbigMember

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.VarArgsTests
Microsoft.CSharp.RuntimeBinder.Tests.VarArgsTests.FailBindOnlyVarargsAvailable
    Assert.Contains() Failure\nNot found: OnlyVarargs\nIn value:  BadArgCount

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestParamsRuntimeTypes
    Assert.Contains() Failure\nNot found:  'b' \nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams3
    Assert.Contains() Failure\nNot found: 'y'\nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstAndSecondWithSecondArgumentWrongPlace
    Assert.Contains() Failure\nNot found: 'z'\nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestTwiceNamedParams
    Assert.Contains() Failure\nNot found: 'x'\nIn value:  DuplicateNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams
    Assert.Contains() Failure\nNot found: 'M'\nIn value:  BadArgCount
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams2
    Assert.Contains() Failure\nNot found: 'x'\nIn value:  NamedArgumentUsedInPositional
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestPositionalUnaffected
    Assert.Contains() Failure\nNot found: 'first'\nIn value:  NamedArgumentUsedInPositional
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestBadNonTrailing
    Assert.Contains() Failure\nNot found:  'c' \nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstAndSecondWithSecondArgumentNotFound
    Assert.Contains() Failure\nNot found: 'DoOtherStuff'\nIn value:  BadNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestSimpleError
    Assert.Contains() Failure\nNot found: 'b'\nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.OnlyNameFirstArgumentMatchesWrongType
    Assert.Contains() Failure\nNot found: 'Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TypeWithMethods.DoStuff(string, int)'\nIn value:  BadArgTypes
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NonExistentNameOnlyFirstArgument
    Assert.Contains() Failure\nNot found: 'DoStuff'\nIn value:  BadNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestPositionalUnaffected2
    Assert.Contains() Failure\nNot found: 'c'\nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestNamedParams4
    Assert.Contains() Failure\nNot found: 'M'\nIn value:  BadArgCount
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlySecondWithSecondArgumentWrongPlace
    Assert.Contains() Failure\nNot found: 'z'\nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.TestParams
    Assert.Contains() Failure\nNot found:  'b' \nIn value:  BadNonTrailingNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlySecondWithSecondArgumentNotFound
    Assert.Contains() Failure\nNot found: 'DoOtherStuff'\nIn value:  BadNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.OverrideChangesName
    Assert.Contains() Failure\nNot found: 'Adder'\nIn value:  BadNamedArgument
Microsoft.CSharp.RuntimeBinder.Tests.NamedArgumentTests.NameOnlyFirstArgumentWrongPlace
    Assert.Contains() Failure\nNot found: 'y'\nIn value:  BadNonTrailingNamedArgument

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.AccessTests
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateMethodFromOutside
    Assert.Contains() Failure\nNot found: BaseType.ProtectedPrivateMethod(int)\nIn value:  BadAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromDerivedSameAssemblyCalledOnBase
    Assert.Contains() Failure\nNot found: BaseType.ProtectedPrivateMethod(int)\nIn value:  BadProtectedAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromDerivedSameAssemblyCalledOnBase
    Assert.Contains() Failure\nNot found: BaseType.AField\nIn value:  BadProtectedAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldSetFromSameAssembly
    Assert.Contains() Failure\nNot found: BaseType.AField\nIn value:  BadAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromDerivedDifferentAssembly
    Assert.Contains() Failure\nNot found: BaseType.AField\nIn value:  BadAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromDerivedDifferentAssembly
    Assert.Contains() Failure\nNot found: BaseType.ProtectedPrivateMethod(int)\nIn value:  BadAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFromSameAssembly
    Assert.Contains() Failure\nNot found: BaseType.ProtectedPrivateMethod(int)\nIn value:  BadAccess
Microsoft.CSharp.RuntimeBinder.Tests.AccessTests.ProtectedPrivateFieldFromOutside
    Assert.Contains() Failure\nNot found: BaseType.AField\nIn value:  BadAccess

Test collection for Microsoft.CSharp.RuntimeBinder.Tests.IndexingTests
Microsoft.CSharp.RuntimeBinder.Tests.IndexingTests.TargetClassClaimsNonExistentMemberIsIndexer
    Assert.Contains() Failure\nNot found: []\nIn value:  BadIndexLHS
```

**Comment by steveisok** [comment]
@SamMonoRT This may be more runtime specific. Can someone from your team triage?

**Comment by SamMonoRT** [comment]
@fanyang-mono  - another of the Android failures

**Comment by lambdageek** [comment]
I didn't look if all the tests fail the same way, but at least some of them have a similar behavior:

@steveisok Some of these failures look like we're not getting the error messages from the string resources and are instead just using the error resource names.  Not sure if it's something about how `Microsoft.CSharp` is compiled for mobile, or if it's a culture issue or something.

```
Test collection for Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallAccessorDirectly
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: 'string.Length.get': cannot explicitly ca···\nActual:   CantCallSpecialMethod\n          ↑ (pos 0)
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.NullaryCtorCallOnNoNullaryCtor
    Assert.Contains() Failure\nNot found: 0\nIn value:  BadCtorArgCount
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.CannotCallOperatorDirectly
    Assert.Equal() Failure\n          ↓ (pos 0)\nExpected: 'string.operator ==(string, string)': can···\nActual:   CantCallSpecialMethod\n          ↑ (pos 0)
Microsoft.CSharp.RuntimeBinder.Tests.BindingErrors.QuinaryCtorCallOnNoQuinaryCtor
    Assert.Contains() Failure\nNot found: 5\nIn value:  BadCtorArgCount
```

For example `CannotCallOperatorDirectly` is expecting that a call throws and the exception message will be `'string.operator ==(string, string)': cannot explicitly call operator or accessor`  but instead we throw and the exception message is `CantCallSpecialMethod` which is the _name_ of the string resource that expands out to `'{0}': cannot explicitly call operator or accessor`

The tests explicitly change to InvariantCulture, so I don't think it's anything like a satellite assembly loading issue.

**Comment by steveisok** [comment]
Ah, thanks @lambdageek.  @mdh1418, I suspect these tests might be worthy of a re-run since we were inadvertently setting `UseSystemResourceKeys` to true.

**Comment by mdh1418** [comment]
No longer fails on Android x64 as of ec3f9fa03f7
