### ISSUE TITLE
AddRange() can add key-value pairs with `null` keys to ImmutableDictionary

### ISSUE THREAD

**Issue by atykhyy** [dotnet/runtime#50865]
### Description

It is not possible to add an item with a `null` key to an immutable dictionary using either the dictionary's or the builder's `.Add/.SetItem` methods:
```
ImmutableDictionary<string, int>.Empty.Add (null, 0) ; // throws ArgumentNullException
```
but it turns out that it _is_ possible to add an item with a `null` key using `.AddRange` and extension methods, such as `ToImmutableDictionary`, that rely on `.AddRange`:
```
ImmutableDictionary<string, int>.Empty.AddRange (new[] { new KeyValuePair<string, int> (null, 0) }) ; // ok???
```
This means that this natural-looking code is invalid:
```
ImmutableDictionary<K, V> Rebuild<K, V> (ImmutableDictionary<K, V> input)
{
    // NB: ignoring key comparers for simplicity
    var builder = ImmutableDictionary.CreateBuilder<K, V> () ;
    foreach (var kv in input) builder.Add (kv.Key, kv.Value) ;
    return builder.ToImmutable () ;
}
```
Given an `ImmutableDictionary`, users should be able to construct a copy of this dictionary using ordinary `.Add` methods, but this will fail if the input dictionary was constructed with `.AddRange` with `null` keys. This behavior is unexpected and so far as I am aware of, not documented. Is it an invariant of generic dictionaries with reference-typed keys that `null` is not a valid key? If it is an invariant, then `.AddRange` shouldn't construct dictionary instances that violate it. On the other hand, if it is not an invariant, then `.Add` shouldn't reject `null` keys. So the existing behavior is inconsistent whether it is an invariant or not.

### Other information

This behavior is observed in System.Collections.Immutable 5.0.0.

**Comment by eiriktsarpalis** [comment]
I can reproduce the issue. Would you be interested in contributing a fix?

**Comment by atykhyy** [comment]
It's simple to fix, but should it be fixed at all, and if so, which way? The ordinary mutable `Dictionary<,>` doesn't permit adding null keys via `ICollection<KeyValuePair<,>>.Add`, so making `ImmutableDictionary<,>.AddRange` reject null keys seems more reasonable as being in line with both `ImmutableDictionary<,>.Add` and with what the mutable collection is doing. However, fixing this either way will change existing behavior - behavior that has existed, for all I can tell, since the first release of System.Collections.Immutable - and potentially break existing code. Is that okay?

**Comment by eiriktsarpalis** [comment]
Yes, the `AddRange` method should be changed to reject `null` keys.

>  However, fixing this either way will change existing behavior - behavior that has existed, for all I can tell, since the first release of System.Collections.Immutable - and potentially break existing code. Is that okay?

This could be reasonably considered a breaking change, but it still is a bug and we should fix it. Entries with `null` keys cannot be looked up or updated individually. Tagging @stephentoub and @layomia for second opinions.

Note that the issue also impacts the `SetItems` method and the `SetRange` and `AddRange` methods for the mutable builder type. `ImmutableSortedDictionary` and `ImmutableHashSet` are not affected.
