### ISSUE TITLE
System.ComponentModel.Annotations.Tests Fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50884]
System.ComponentModel.Annotations.Tests
System.ComponentModel.DataAnnotations.Tests.ValidationExceptionTests.Ctor_SerializationInfo_StreamingContext

```
System.ComponentModel.Annotations.Tests.dll   Failed: 1

Test collection for System.ComponentModel.DataAnnotations.Tests.ValidationExceptionTests
System.ComponentModel.DataAnnotations.Tests.ValidationExceptionTests.Ctor_SerializationInfo_StreamingContext
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

**Comment by steveisok** [comment]
Same problem as https://github.com/dotnet/runtime/issues/50942

**Comment by mdh1418** [comment]
This no longer fails, and the tests are skipped with `Condition(s) not met: "IsBinaryFormatterSupported"`
