### ISSUE TITLE
Some Vector3 benchmarks have regressed on Windows ARM64

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#50899]
It looks like `System.Numerics.Tests.Perf_Vector3.UnitXBenchmark` has regressed compared to 5.0. **This regression is specific to Windows ARM64**, other configs were not affected

## Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net5.0 net6.0 --filter System.Numerics.Tests.Perf_Vector3.UnitXBenchmark --architecture arm64
```

##  Full data from the most recent comparison

<details>

| Result | Base | Diff | Ratio    | Alloc Delta | Modality   | Operating System        | Bit   | Processor Name                                | Base V        | Diff V      |
| ------ | ----:| ----:| -------- | -----------:| ---------- | ----------------------- | ----- | --------------------------------------------- | ------------- | ------------ |
| Same   | 0.13 | 0.08 | 1.64     |          +0 | bimodal    | Windows 10.0.19042      | X64   | AMD Ryzen Threadripper 2990WX                 | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.05 | 0.02 | 2.58     |          +0 | several?   | Windows 10.0.21337      | X64   | AMD Ryzen 9 3900X                             | 5.0.421.11614 | 6.0.21.16701|
| Same   | 0.07 | 0.02 | 3.31     |          +0 |            | Windows 10.0.21337      | X64   | AMD Ryzen Threadripper 3990X                  | 5.0.421.11614 | 6.0.21.16701|
| Same   | 0.26 | 0.00 | Infinity |          +0 |            | Windows 10.0.18363.1440 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.58 | 0.57 | 1.03     |          +0 | bimodal    | Windows 10.0.21337      | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)     | 5.0.421.11614 | 6.0.21.16701|
| Same   | 0.11 | 0.13 | 0.84     |          +0 | several?   | Windows 10.0.19042      | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)      | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.10 | 0.15 | 0.68     |          +0 |            | Windows 10.0.19042      | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)    | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.36 | 0.22 | 1.68     |          +0 | bimodal    | Windows 10.0.19042      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R) | 5.0.421.11614 | 6.0.21.16408|
| Same   | 0.09 | 0.10 | 0.94     |          +0 | multimodal | Windows 10.0.19042      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)  | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.29 | 0.11 | 2.74     |          +0 |            | Windows 10.0.19042      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)  | 5.0.421.11614 | 6.0.21.16408|
| Same   | 1.77 | 1.70 | 1.04     |          +0 |            | Windows 10.0.19042      | X64   | Intel Atom x7-Z8700 CPU 1.60GHz               | 5.0.421.11614 | 6.0.21.16309|
| Same   | 0.00 | 0.01 | 0.00     |          +0 |            | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16309|
| Same   | 0.16 | 0.19 | 0.87     |          +0 | several?   | alpine 3.11             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)    | 5.0.421.11614 | 6.0.21.16601|
| Same   | 0.00 | 1.54 | 0.00     |          +0 |            | ubuntu 16.04            | Arm64 | Unknown processor                             | 5.0.421.11614 | 6.0.21.17806|
| Same   | 0.00 | 1.54 | 0.00     |          +0 | multimodal | ubuntu 16.04            | Arm64 | Unknown processor                             | 5.0.421.11614 | 6.0.21.17806|
| Slower | 0.00 | 2.38 | 0.00     |          +0 |            | Windows 10.0.19042      | Arm64 | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.16309|
| Slower | 0.00 | 2.08 | 0.00     |          +0 |            | Windows 10.0.19042      | Arm64 | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.16201|
| Same   | 0.00 | 0.00 | NaN      |          +0 |            | Windows 10.0.18363.1440 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16701|
| Same   | 0.04 | 0.10 | 0.38     |          +0 |            | Windows 10.0.19042.867  | Arm   | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.17905|
| Same   | 0.48 | 0.54 | 0.90     |          +0 |            | macOS 11.2              | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)     | 5.0.421.11614 | 6.0.21.16408|
| Same   | 0.41 | 0.44 | 0.93     |          +0 |            | macOS 11.2.2            | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)    | 5.0.421.11614 | 6.0.21.16601|
| Same   | 0.33 | 0.31 | 1.06     |          +0 |            | macOS Mojave 10.14.5    | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)   | 5.0.421.11614 | 6.0.21.16309|
</details>

**Comment by danmoseley** [comment]
@adamsitnik I'm confused by the table. The "base" for the "slower" scenarios is 0.00. Is that right? It maybe is no surprise we regressed.

@DrewScoggins do we have recent official data?

**Comment by tannergooding** [comment]
I think most of these are new tests I added in August of last year: https://github.com/dotnet/performance/pull/1448

**Comment by DrewScoggins** [comment]
Not sure how I missed this issue before, sorry about that.

So we have both Ubuntu and Windows numbers for this test. As you can see in both we were regressed back in April, but on April 27th, Tanner commited https://github.com/dotnet/runtime/pull/51731, and we saw the regression go away.

![image](https://user-images.githubusercontent.com/9439069/128749594-0a7b13d1-6bf3-4f17-81f3-8612748fd783.png)
![image](https://user-images.githubusercontent.com/9439069/128749635-998f9019-f184-4752-aa1b-1ad672e47cae.png)

**Comment by tannergooding** [comment]
Thanks @DrewScoggins. I'm going to close this then.
