### ISSUE TITLE
Guid.CreateNew() has regressed a lot on macOS

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#50897]
It looks like `Guid.CreateNew()` has become few times slower compared to 5.0. **This regression is specific to `macOS`, Linux is not affected.**

## Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f net5.0 net6.0 --filter 'System.Tests.Perf_Guid.NewGuid`
```

##  Full data from the most recent comparison

<details>

| Result |    Base |    Diff | Ratio | Alloc Delta | Modality | Operating System        | Bit   | Processor Name                                | Base V        | Diff V      |
| ------ | -------:| -------:| -----:| -----------:| -------- | ----------------------- | ----- | --------------------------------------------- | ------------- | ------------ |
| Same   |   66.26 |   67.29 |  0.98 |          +0 |          | Windows 10.0.19042      | X64   | AMD Ryzen Threadripper 2990WX                 | 5.0.421.11614 | 6.0.21.16201|
| Same   |   51.51 |   49.42 |  1.04 |          +0 |          | Windows 10.0.21337      | X64   | AMD Ryzen 9 3900X                             | 5.0.421.11614 | 6.0.21.16701|
| Same   |   53.08 |   51.65 |  1.03 |          +0 |          | Windows 10.0.21337      | X64   | AMD Ryzen Threadripper 3990X                  | 5.0.421.11614 | 6.0.21.16701|
| Same   |   79.78 |   79.45 |  1.00 |          +0 |          | Windows 10.0.18363.1440 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16201|
| Slower |  357.46 |  688.03 |  0.52 |          +0 | several? | Windows 10.0.21337      | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)     | 5.0.421.11614 | 6.0.21.16701|
| Same   |   67.36 |   68.43 |  0.98 |          +0 |          | Windows 10.0.19042      | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)      | 5.0.421.11614 | 6.0.21.16201|
| Same   |   67.60 |   68.24 |  0.99 |          +0 |          | Windows 10.0.19042      | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)    | 5.0.421.11614 | 6.0.21.16201|
| Same   |   78.69 |   79.37 |  0.99 |          +0 |          | Windows 10.0.19042      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R) | 5.0.421.11614 | 6.0.21.16408|
| Same   |   59.24 |   59.51 |  1.00 |          +0 |          | Windows 10.0.19042      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)  | 5.0.421.11614 | 6.0.21.16201|
| Same   |   60.07 |   59.47 |  1.01 |          +0 |          | Windows 10.0.19042      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)  | 5.0.421.11614 | 6.0.21.16408|
| Same   |  245.99 |  244.95 |  1.00 |          +0 |          | Windows 10.0.19042      | X64   | Intel Atom x7-Z8700 CPU 1.60GHz               | 5.0.421.11614 | 6.0.21.16309|
| Same   |  745.46 |  713.66 |  1.04 |          +0 |          | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16309|
| Same   | 1912.05 | 1873.51 |  1.02 |          +0 |          | alpine 3.11             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)    | 5.0.421.11614 | 6.0.21.16601|
| Same   |  820.20 |  823.64 |  1.00 |          +0 |          | ubuntu 16.04            | Arm64 | Unknown processor                             | 5.0.421.11614 | 6.0.21.17806|
| Same   |  825.06 |  779.20 |  1.06 |          +0 |          | ubuntu 16.04            | Arm64 | Unknown processor                             | 5.0.421.11614 | 6.0.21.17806|
| Same   |   94.51 |   90.38 |  1.05 |          +0 |          | Windows 10.0.19042      | Arm64 | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.16309|
| Same   |   94.68 |   92.58 |  1.02 |          +0 |          | Windows 10.0.19042      | Arm64 | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.16201|
| Same   |  249.69 |  247.84 |  1.01 |          +0 |          | Windows 10.0.18363.1440 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz             | 5.0.421.11614 | 6.0.21.16701|
| Same   |  248.07 |  231.92 |  1.07 |          +0 |          | Windows 10.0.19042.867  | Arm   | Microsoft SQ1 3.0 GHz                         | 5.0.421.11614 | 6.0.21.17905|
| Slower |  116.40 |  874.96 |  0.13 |          +0 |          | macOS 11.2              | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)     | 5.0.421.11614 | 6.0.21.16408|
| Slower |   95.66 |  717.08 |  0.13 |          +0 |          | macOS 11.2.2            | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)    | 5.0.421.11614 | 6.0.21.16601|
| Slower |  216.78 |  994.44 |  0.22 |          +0 |          | macOS Mojave 10.14.5    | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)   | 5.0.421.11614 | 6.0.21.16309|

</details>

**Comment by GrabYourPitchforks** [comment]
Guessing this is a result of https://github.com/dotnet/runtime/pull/42770 (https://github.com/dotnet/runtime/issues/42752). OSX provides the `arc4random` inbox, so in previous versions of .NET we'd use that function for Guid generation. Now we use /dev/urandom.

@bartonjs Do you know if Apple provides an API call accelerator for accessing their CSPRNG? Something that would have less overhead than /dev/urandom?

**Comment by bartonjs** [comment]
> Do you know if Apple provides an API call accelerator for accessing their CSPRNG?

https://github.com/dotnet/runtime/blob/4d2fc1c5da31ea7db9a2775c413960a3f2d30765/src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/pal_random.c#L9-L17

Remove the validation and dual export of the success state and it's a one-liner.

> Something that would have less overhead than /dev/urandom?

I haven't profiled it, but it's probably at least as fast.

**Comment by GrabYourPitchforks** [comment]
@adamsitnik Would it be possible to run two benchmarks on Mac OSX on the latest main?

```cs
[Benchmark]
[SkipLocalsInit]
public Guid NewGuid1() => Guid.NewGuid();

[Benchmark]
[SkipLocalsInit]
public unsafe Guid NewGuid2()
{
    Guid g;
    RandomNumberGenerator.Fill(new Span<byte>((byte*)(&g), sizeof(Guid))); // uses CCRandomGenerateBytes, per Jeremy's comment
    return g;
}
```

It won't match _exactly_ what would happen from rewriting the crypto interop on Mac OSX, but it should serve as a good first-order approximation.

**Comment by jkotas** [comment]
> OSX provides the arc4random inbox,

Note that the arc4random inbox implementation is a wrapper over the core macOS crypto random API starting with OSX 1015: https://github.com/dotnet/runtime/pull/42770#issuecomment-699544795

The only performance difference between CCRandomGenerateBytes and arc4random should be the fixed overhead of the wrapping code starting with OSX 1015.

**Comment by vcsjones** [comment]
@GrabYourPitchforks Benchmark results on an Intel Mac from `main` at ccc47f55554e2ae12e7ec9a07ea19bd4b49e910c

BenchmarkDotNet=v0.12.1.20210419-develop, OS=macOS Big Sur 11.2.3 (20D91) [Darwin 20.3.0]
Intel Core i7-8700B CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100-preview.3.21202.5
  [Host]     : .NET 6.0.0 (6.0.21.20104), X64 RyuJIT
  Job-OTQAJG : .NET 6.0.0 (42.42.42.42424), X64 RyuJIT

Toolchain=main  

|   Method |      Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |----------:|---------:|---------:|------:|------:|------:|----------:|
| NewGuid1 | 617.68 ns | 5.156 ns | 4.305 ns |     - |     - |     - |         - |
| NewGuid2 |  84.60 ns | 0.884 ns | 0.784 ns |     - |     - |     - |         - |

**Comment by GrabYourPitchforks** [comment]
@vcsjones Thanks for the confirmation! This indicates pretty clearly that we should call the underlying crypto APIs directly without going through any type of wrapper. @bartonjs, you or Kevin want to self-assign?

**Comment by vcsjones** [comment]
@GrabYourPitchforks @bartonjs I can't self assign, but please assign to me.
