### ISSUE TITLE
ImmutableHashSet<T> is sorted

### ISSUE THREAD

**Issue by Nepcix** [dotnet/runtime#50904]
Not sorting is the default behavior for hashset
But I have a problem when I using ImmutableHashSet
```csharp
int[] vs1 = new int[] {7, 2, 5, 8, 0 };
ImmutableHashSet<int> vs2 = vs1.ToImmutableHashSet();
foreach (var item in vs2)
{
Console.Write(item);
}
Console.WriteLine();
```
output:02578

so,is it a bug ?

**Comment by Joe4evr** [comment]
The ordering here happens because that's how the internal buckets are ordered, which is based on the hashcode of the object you put into the set. And since the hashcode for an `int` is actually itself, it just so happens to look sorted when the values come out.

**Comment by Nepcix** [comment]
> The ordering here happens because that's how the internal buckets are ordered, which is based on the hashcode of the values you put into the set. And since the hashcode for an `int` is actually itself, it just so happens to look sorted when the values come out.

But I can't understand why immutableHashSet behaves differently from HashSet

**Comment by eiriktsarpalis** [comment]
> But I can't understand why immutableHashSet behaves differently from HashSet

It uses a different implementation. Enumerations of hashtables do not guarantee any particular ordering, therefore different implementations surface different orderings. Per @Joe4evr's comment if I change your code slightly:
```csharp
IEnumerable<string> vs1 = new int[] { 7, 2, 5, 8, 0 }.Select(x => x.ToString());
ImmutableHashSet<string> vs2 = vs1.ToImmutableHashSet();
foreach (var item in vs2)
{
Console.Write(item);
}
Console.WriteLine();
```
The output changes to `80725`, so clearly no sorting is involved. Curious to understand if your code somehow depends on the ordering of HashSet enumeration?

**Comment by Nepcix** [comment]
> > But I can't understand why immutableHashSet behaves differently from HashSet
> 
> It uses a different implementation. Enumerations of hashtables do not guarantee any particular ordering, therefore different implementations surface different orderings. Per @Joe4evr's comment if I change your code slightly:
> 
> ```cs
> IEnumerable<string> vs1 = new int[] { 7, 2, 5, 8, 0 }.Select(x => x.ToString());
> ImmutableHashSet<string> vs2 = vs1.ToImmutableHashSet();
> foreach (var item in vs2)
> {
> Console.Write(item);
> }
> Console.WriteLine();
> ```
> 
> The output changes to `80725`, so clearly no sorting is involved. Curious to understand if your code somehow depends on the ordering of HashSet enumeration?

thank you
and I have one last question
I need a collection which
Elements of the collection cannot be repeated
Collection cannot be modified
have any API available？

**Comment by Nepcix** [comment]
> > > But I can't understand why immutableHashSet behaves differently from HashSet
> > 
> > 
> > It uses a different implementation. Enumerations of hashtables do not guarantee any particular ordering, therefore different implementations surface different orderings. Per @Joe4evr's comment if I change your code slightly:
> > ```cs
> > IEnumerable<string> vs1 = new int[] { 7, 2, 5, 8, 0 }.Select(x => x.ToString());
> > ImmutableHashSet<string> vs2 = vs1.ToImmutableHashSet();
> > foreach (var item in vs2)
> > {
> > Console.Write(item);
> > }
> > Console.WriteLine();
> > ```
> > 
> > 
> > The output changes to `80725`, so clearly no sorting is involved. Curious to understand if your code somehow depends on the ordering of HashSet enumeration?
> 
> thank you
> and I have one last question
> I need a collection which
> Elements of the collection cannot be repeated
> Collection cannot be modified
> have any API available？

and Elements keep order

**Comment by eiriktsarpalis** [comment]
Yes, you can use [`ImmutableSortedSet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablesortedset-1?view=net-5.0).

**Comment by Clockwork-Muse** [comment]
@eiriktsarpalis - I think "elements keep order" may mean "elements keep _insertion_ order".

@Nepcix - 
In many cases you don't need to return the concrete type of an object - consider exposing [`IReadOnlySet<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlyset-1?view=net-5.0) to your users.  Note that, in general, _sets do not retain insertion order_, so if this was for some reason important you'll need to find an implementation that explicitly guarantees this (the C# library classes do not).

**Comment by eiriktsarpalis** [comment]
I am going to close the issue, since there doesn't seem to be anything actionable from the libraries perspective. Feel free to continue the conversation or reopen the issue.
