### ISSUE TITLE
Create a new test, instead of adding runtimeconfig.json to the existing Android functional test

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#50905]
Refer to https://github.com/dotnet/runtime/pull/50612
Address the `+1` comments from the above PR. (Addressed via https://github.com/dotnet/runtime/pull/56486)
And add incremental build to the msbuild task. (Doc: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-incrementally?view=vs-2019#to-specify-inputs-and-outputs-for-a-target)

**Comment by SamMonoRT** [comment]
Moving to 7.0.0, test functionality already exists, this is more of a refactoring suggestion.
