### ISSUE TITLE
Random.Next(int,int) can return out-of-bounds result in .NET 6 Preview 2

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#50911]
### Description

[My UnitTests](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/54d58f3eef59ff97059ee9752a53be0a12348c60/KGySoft.CoreLibraries.UnitTest/UnitTests/CoreLibraries/Extensions/RandomExtensionsTest.cs#L131) revealed the following bug when targeting .NET 6 Preview 2:

The [`Random(int,int)`](https://github.com/dotnet/runtime/blob/02e951f1e42ae2e9759bd5a3267f5bc2407e5ab6/src/libraries/System.Private.CoreLib/src/System/Random.cs#L82) method can return invalid results.

The following example has about 50% chance to return a huge negative value:

```cs
int i = new Random().Next(-1, Int32.MaxValue);
```

### Configuration

Reproducible with .NET 6 Preview 2

### Other information

The bug is reproducible only if there is no seed specified so the new `XoshiroImpl` is created internally.

**Comment by stephentoub** [comment]
Thanks for the bug report.  Fix is in https://github.com/dotnet/runtime/pull/50922.
