### ISSUE TITLE
[tvOS][globalization] Missing support for ICU

### ISSUE THREAD

**Issue by spouliot** [dotnet/runtime#50912]
### Description

https://github.com/dotnet/runtime/pull/49406 added ICU support for iOS (in P3). However similar support for tvOS was not added and runs into the same issue (stuck with invariant).

Note: it's unclear is Catalyst apps will be allowed (for App Store) to use the system ICU like it's being done for macOS. If Catalyst apps goes thru the same review process as iOS apps then ICU support will also be needed.

### Configuration

* SDK 6.0.100-preview.3.21202.5

### Regression?

Yes. Legacy Xamarin.tvOS SDK supports globalization.

### Other information

* https://github.com/dotnet/runtime/pull/49406 
* https://github.com/xamarin/xamarin-macios/issues/8906

**Comment by spouliot** [comment]
c.c. @steveisok

**Comment by steveisok** [comment]
I validated the icu bits are in the tvOS runtime pack feed.  What errors are you seeing?

**Comment by spouliot** [comment]
The `FailFast` / missing ICU error happens because of

```
if TARGET_OS_TV
	rv = 0;
	// Due to https://github.com/dotnet/runtime/issues/48508, we can't link with the .NET version of libmonosgen-2.0.dylib,
	// which means that we can't call monovm_initialize here (libxamarin.dylib fails native linking). Just ignore it for now.
	fprintf (stderr, "xamarin_vm_initialize (%i, %p, %p): Ignored due to https://github.com/dotnet/runtime/issues/48508.\n", propertyCount, propertyKeys, propertyValues);
#else
```
