### ISSUE TITLE
System.Diagnostics.DiagnosticSource.Tests Fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50924]
System.Diagnostics.DiagnosticSource.Tests
System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.NoExceptionThrownWhenProcessingStaticActivityProperties

```
System.Diagnostics.DiagnosticSource.Tests.dll   Failed: 1

Test collection for System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests
System.Diagnostics.Tests.DiagnosticSourceEventSourceBridgeTests.NoExceptionThrownWhenProcessingStaticActivityProperties
    System.ArgumentNullException : ArgumentNull_Generic Arg_ParamName_Name, eventSource

**Comment by steveisok** [comment]
Does not fail for regular Android runs.  We should re-enable the test.

**Comment by MaximLipnin** [comment]
The test is re-enabled in https://github.com/dotnet/runtime/pull/56209, closing it.
