### ISSUE TITLE
System.Runtime.Serialization.Primitives.Tests Fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50936]
System.Runtime.Serialization.Primitives.Tests
System.Runtime.Serialization.Tests.InvalidDataContractExceptionTests.Ctor_SerializationInfo_StreamingContext

```
System.Runtime.Serialization.Primitives.Tests.dll   Failed: 1

Test collection for System.Runtime.Serialization.Tests.InvalidDataContractExceptionTests
System.Runtime.Serialization.Tests.InvalidDataContractExceptionTests.Ctor_SerializationInfo_StreamingContext
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

**Comment by lewing** [comment]
these need a pnse?

**Comment by steveisok** [comment]
@mdh1418 Another binaryformatter one. These should all be disabled for mobile via feature detection.

**Comment by mdh1418** [comment]
This no longer fails, and the tests are skipped with `Condition(s) not met: "IsBinaryFormatterSupported"`
