### ISSUE TITLE
System.Threading.Channels.Tests Fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50943]
System.Threading.Channels.Tests
System.Threading.Channels.Tests.ChannelClosedExceptionTests.Serialization_Roundtrip

```
System.Threading.Channels.Tests.dll   Failed: 1

Test collection for System.Threading.Channels.Tests.ChannelClosedExceptionTests
System.Threading.Channels.Tests.ChannelClosedExceptionTests.Serialization_Roundtrip
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

**Comment by steveisok** [comment]
Same problem as https://github.com/dotnet/runtime/issues/50942

**Comment by mdh1418** [comment]
This no longer fails, and the tests are skipped with `Condition(s) not met: "IsBinaryFormatterSupported"`
