### ISSUE TITLE
System.Text.RegularExpressions.Tests Fails on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#50942]
System.Text.RegularExpressions.Tests
System.Text.RegularExpressions.Tests.RegexParserTests.RegexParseException_Serializes
System.Text.RegularExpressions.Tests.RegexMatchTimeoutExceptionTests.SerializationRoundtrip

```
System.Text.RegularExpressions.Tests.dll   Failed: 2

Test collection for System.Text.RegularExpressions.Tests.RegexParserTests
System.Text.RegularExpressions.Tests.RegexParserTests.RegexParseException_Serializes
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

Test collection for System.Text.RegularExpressions.Tests.RegexMatchTimeoutExceptionTests
System.Text.RegularExpressions.Tests.RegexMatchTimeoutExceptionTests.SerializationRoundtrip
    System.NotSupportedException : BinaryFormatter_SerializationDisallowed

**Comment by pgovind** [comment]
Will take a look at this later today. A question that comes to mind immediately is: Why does this fail suddenly? Has BF been disabled for android?

**Comment by eerhardt** [comment]
@pgovind - I thought all these "tests fail on android" are because there are problems in the mono android runtime, and not the library.

**Comment by pgovind** [comment]
Ah thanks, I was going to ping folks about what we are currently doing for android bugs. Un-assigned for now

**Comment by steveisok** [comment]
@mdh1418 We do not support binary formatter on android, so these tests can be skipped w/ `PlatformSpecific` or better yet see if they are feature detecting BF.

**Comment by mdh1418** [comment]
This no longer fails, and the tests are skipped with `Condition(s) not met: "IsBinaryFormatterSupported"`

**Comment by eerhardt** [comment]
Re-opening. We need to remove these ActiveIssues:

https://github.com/dotnet/runtime/blob/ec3f9fa03f72ceadfa0610196a12bab3b37b63f9/src/libraries/System.Text.RegularExpressions/tests/RegexMatchTimeoutExceptionTests.cs#L46-L48

https://github.com/dotnet/runtime/blob/ec3f9fa03f72ceadfa0610196a12bab3b37b63f9/src/libraries/System.Text.RegularExpressions/tests/RegexParserTests.netcoreapp.cs#L99-L101

**Comment by pgovind** [comment]
Just a note for myself: Nothing to do here. #55974 will fix/close this issue when it's merged
