### ISSUE TITLE
[wasm][aot][tests] System.Runtime.CompilerServices.Unsafe.Tests failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50962]
This can be reproduced on `main`.

[Logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Runtime.CompilerServices.Unsafe.Tests/console.48099730.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:47:49] fail: [FAIL] System.Runtime.CompilerServices.UnsafeTests.NullRef
[19:47:49] info: Assert.Throws() Failure
[19:47:49] info: Expected: typeof(System.NullReferenceException)
[19:47:49] info: Actual:   (No exception was thrown)
[19:47:49] info: 
[19:47:52] info: Finished:    System.Runtime.CompilerServices.Unsafe.Tests.dll
```

**Comment by vargaz** [comment]
This is not a wasm bug, in release mode, for the following code:
```
        Action a = () => Unsafe.NullRef<int>();
```
roslyn generates (in release mode):
```
      IL_0000:  call       !!0& [System.Runtime.CompilerServices.Unsafe]System.Runtime.CompilerServices.Unsafe::NullRef<int32>()
      IL_0005:  pop
```

So there is nothing to throw a nullref anymore.

**Comment by radical** [comment]
With `/p:EnableAggressiveTrimming=true`, this passes, but with `/p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true`, it fails. Why does it pass in the first case?

**Comment by radical** [comment]
![Screen Shot 2021-04-23 at 12 34 26 PM](https://user-images.githubusercontent.com/1472/115902545-89125e80-a430-11eb-8b6e-836183a7eb74.png)

I think:

- the exception is getting thrown
- *but* it gets eaten up somehow?
- I was seeing something like this in https://github.com/dotnet/runtime/issues/50969 where a PNSE would get thrown, but it looked like the exception got ignored, and execution resumed as if nothing had happened

I didn't dig into this much, so I could be wrong!

**Comment by radical** [comment]
btw, you can run the test in the browser with:
`WasmTestAppArgs="-method System.Runtime.CompilerServices.UnsafeTests.NullRef" WasmXHarnessArgs="--no-headless --no-quit" Scenario=WasmTestOnBrowser`

**Comment by vargaz** [comment]
So there are 2 problems here, the aot compiler misses a null check, but roslyn also does a bad optimization in release mode.
