### ISSUE TITLE
System.Text.Json to determine type

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#50974]
Hi,

using Newtonsoft.Json, I can do:

```
public class MembersBirthdaysData
{
    public int user_id { get; set; }
    public string user_uuid { get; set; }
    public DateTime date_of_birth { get; set; }
}

```
then Newtonsoft.Json will understand the type and do the necessary conversation but in System.Text.Json I have to do this:

```
class MembersBirthdaysData
{
    public string user_id { get; set; }
    public int userID
    {
        get
        {
            return Convert.ToInt32(user_id);
        }
    }
}

```
Why can't you make System.Text.Json to automatically convert the type which will help developers and save the time.

Thanks,
Jassim

**Comment by huoyaoyuan** [comment]
`JsonSerializerDefaults.Web` will do that.

**Comment by eiriktsarpalis** [comment]
Hi @jrahma, so if I'm understanding your question correctly, you want System.Text.Json to automatically convert snake_case property names to camelCase property names? 

This is not supported, even with `JsonSerializerDefaults.Web`. [The recommended capitalization for .NET properties is PascalCase](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) and most tooling has been designed around that convention.

If I change your code to the following:
```csharp
class Program
{
    public class MembersBirthdaysData
    {
        public int UserId { get; set; } = 42;
        public string UserUuid { get; set; } = "42";
        public DateTime DateOfBirth { get; set; } = DateTime.Today;
    }

    static void Main()
    {
        var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        Console.WriteLine(JsonSerializer.Serialize(new MembersBirthdaysData(), options));
    }
}
```
I will get the expected serialization:
```
{"userId":42,"userUuid":"42","dateOfBirth":"2021-04-09T00:00:00+01:00"}
```

I hope this answers your question.

**Comment by jrahma** [comment]
> Hi @jrahma, so if I'm understanding your question correctly, you want System.Text.Json to automatically convert snake_case property names to camelCase property names?
> 
> This is not supported, even with `JsonSerializerDefaults.Web`. [The recommended capitalization for .NET properties is PascalCase](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) and most tooling has been designed around that convention.
> 
> If I change your code to the following:
> 
> ```cs
> class Program
> {
>     public class MembersBirthdaysData
>     {
>         public int UserId { get; set; } = 42;
>         public string UserUuid { get; set; } = "42";
>         public DateTime DateOfBirth { get; set; } = DateTime.Today;
>     }
> 
>     static void Main()
>     {
>         var options = new JsonSerializerOptions(JsonSerializerDefaults.Web);
>         Console.WriteLine(JsonSerializer.Serialize(new MembersBirthdaysData(), options));
>     }
> }
> ```
> 
> I will get the expected serialization:
> 
> ```
> {"userId":42,"userUuid":"42","dateOfBirth":"2021-04-09T00:00:00+01:00"}
> ```
> 
> I hope this answers your question.

That is true but what I mean is to have it simple without setting a value, just like how it was with Newtonsoft.Json

I am sure if Newtonsoft.Json was able to do it then it's a piece of cake for Microsoft.

**Comment by jrahma** [comment]
> automatically

and you did NOT understand my question. My question was why do we need to use JsonSerializerOptions when we were able to do it without options using Newtonsoft.Json

It's all about simplifying and make things easier for the developers.

**Comment by eiriktsarpalis** [comment]
> That is true but what I mean is to have it simple without setting a value, just like how it was with Newtonsoft.Json
>
>I am sure if Newtonsoft.Json was able to do it then it's a piece of cake for Microsoft.

Newtonsoft.Json does not do this by default, as illustrated by this snippet:
```csharp
public class MembersBirthdaysData
{
    public int user_id { get; set; } = 42;
    public string user_uuid { get; set; } = "42";
    public DateTime date_of_birth { get; set; } = DateTime.Today;
}

static void Main()
{
    Console.WriteLine(JsonConvert.SerializeObject(new MembersBirthdaysData())); 
    // {"user_id":42,"user_uuid":"42","date_of_birth":"2021-04-09T00:00:00+01:00"}
}
```
Just like System.Text.Json you would need to opt in, via the [`CamelCaseNamingStrategy`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Serialization_CamelCaseNamingStrategy.htm) class.

> It's all about simplifying and make things easier for the developers.

Assuming we were in agreement about this making things simpler for developers, changing defaults would still constitute a breaking change so it is unlikely we would be adopting it.
