### ISSUE TITLE
[regions] use the used range in the regions allocator for the heap range

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#50983]
right now we just use the whole reserve range as the heap range (ie, g_gc_lowest_address, g_gc_highest_address), this should be change to use the start->used portion. we'll reserve a range for GC's own bookkeeping datastructures (I'll call it X) and only commit the portion that's used. IOW, we'll have a grow_brick_card_tables but this method will not need to ask for a new reserve range, it just needs to commit more in X.

**Comment by cshung** [comment]
Fixed in #52402
