### ISSUE TITLE
System.Text.Json is converting "+" to "\u002B"

### ISSUE THREAD

**Issue by pavinan** [dotnet/runtime#50998]
### Description

System.Text.Json is converting "+" to "\u002B"

```cs
using System.Text.Json;

namespace TestJSON
{
    class Program
    {
        static void Main(string[] args)
        {
            var res = JsonSerializer.Serialize(new Test());
            // expected { "A" : "+"}
            // but got {"A":"\u002B"}
        }

        public class Test
        {
            public string A { get; set; } = "+";
        }

    }
}

```

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

**Comment by layomia** [comment]
The default encoder used by System.Text.Json escapes some characters which might be sensitive when transmitted over the wire, depending on the scenario. See ["How to customize character encoding with System.Text.Json"](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-character-encoding) for more information on this.

For your specific scenario, a workaround is to use `JavaScriptEncoder.UnsafeRelaxedJsonEscaping` as shown below. Please see the linked doc for why this might be unsafe.

```cs
using System.Text.Encodings.Web;

var options = new JsonSerializerOptions { Encoder =  JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
var res = JsonSerializer.Serialize(new Test(), options);
```
