### ISSUE TITLE
JIT\Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest fails with Crossgen2 on Windows

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#51007]
OS: Windows
Architecture: x64, arm64
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1079632&view=ms.vss-test-web.build-test-results-tab&runId=33125858&resultId=100897&paneView=debug

[Scarce] diagnostic information:

<pre>
      Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
         at PlatformDefaultMemberFunctionTest.Test8ByteHFA(C*)
         at PlatformDefaultMemberFunctionTest.Main(System.String[])
      
      Return code:      1
      Raw output file:      D:\h\w\A8F208E3\w\AC620955\e\JIT\Directed\Reports\JIT.Directed\callconv\PlatformDefaultMemberFunction\PlatformDefaultMemberFunctionTest\PlatformDefaultMemberFunctionTest.output.txt
</pre>

I believe this is a recently introduced tests covering C# function pointer support; if that support required jitinterface changes, we may have missed their port to the Crossgen2 compiler.

/cc @dotnet/crossgen-contrib
/cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
The changes are ported over, and I just validated last week that they run correctly when the assembly is crossgenned with crossgen2.

**Comment by trylek** [comment]
Based on offline chat with Jeremy there seem to be two distinct issues here:

1) CoreCLR test infra doesn't make the TestLibrary.dll dependency visible to the Crossgen2 compiler and therefore it fails to compile the <code>Test8ByteHFA</code> method.

2) When the compiler fails to compiler the <code>Test8ByteHFA</code> method (so that it gets jitted), the test crashes when the rest of the app is compiled with Crossgen2. When the entire test is run in JIT mode, it passes; so it looks like something in the Crossgen2-compiled code is out of sync with the runtime JIT.
