### ISSUE TITLE
NetBSD buildslave?

### ISSUE THREAD

**Issue by krytarowski** [dotnet/runtime#5102]
We are already building 100% CoreCLR, 100% CoreFX, 100% CoreRT via pkgsrc-wip/NetBSD.

We are passing almost 90% of PAL tests (https://github.com/dotnet/coreclr/issues/3123)

I think it's about right time to plan NetBSD build machine. What are the requirements for one?

**Comment by ericstj** [comment]
@wfurt do we have any plans to build / support  NetBSD

**Comment by wfurt** [comment]
it seems unlikely at the moment - at least as an official platform. There is no Azure support AFAIK so this will be limited to community support.

**Comment by krytarowski** [comment]
NetBSD 9.0 included hyper-v support so it should be now easier... however I am still preempted with generic NetBSD enhancements.

**Comment by wfurt** [comment]
FreeBSD is now cros-compiled using Linux container (to make it easier) 
That may work for NetBSD as well to avoid hassle with bootstrap cli and Azure support.
