### ISSUE TITLE
[MONO][INTERPRETER] Perf Regression Microsoft.Extensions.DependencyInjection.GetService (26%) and others

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#51029]
For whatever reason, this only seems to come up clearly on the interpreter. Based on the time it happens, and the benchmarks, it looks like it could have been caused by this change: https://github.com/dotnet/runtime/commit/c24bf80fae47a27a5efd2c3382e53fa28bf4e4af

@davidfowl Could that change have caused this regression?

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [5e79b4f17a1486da0fd5e243c7aa5c712910d6a5](https://github.com/dotnet/runtime/commit/5e79b4f17a1486da0fd5e243c7aa5c712910d6a5)
Compare | [8fe4f8b2bc2cb4e033a8cdf5b55efa0bda41c6bc](https://github.com/dotnet/runtime/commit/8fe4f8b2bc2cb4e033a8cdf5b55efa0bda41c6bc)

### Regressions in Microsoft.Extensions.DependencyInjection.TimeToFirstService

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22Dynamic%22).html>) | 7.64 μs | 8.46 μs | 1.11 | | |
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22Runtime%22).html>) | 7.65 μs | 8.58 μs | 1.12 | | |
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22ILEmit%22).html>) | 7.63 μs | 8.55 μs | 1.12 | | |
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22Expressions%22).html>) | 7.61 μs | 8.60 μs | 1.13 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_4.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.TimeToFirstService*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-375a4e34-f4a7-4018-99a5-8cae6bda5dacbf17a190f2f4068a1/b4c78bd1-a734-4829-ad9e-3a117408d620.zip?sv=2019-07-07&se=2021-05-01T19%3A09%3A00Z&sr=c&sp=rl&sig=pG2RYubrEckHtr%2FdLcLZvryMsj%2BL3HJ%2BKv%2BXfFG%2Bdfw%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-5a543145-e6f4-44b4-8117-42ac16de4d5e1d63ef36f7d45c19b/4faaa7c1-084e-418a-b6bc-ade1bb875d71.zip?sv=2019-07-07&se=2021-05-02T09%3A27%3A47Z&sr=c&sp=rl&sig=Ptf4rHvGWRumEXKQb%2FwBPN%2BhDNvyFWljygV%2B0coJl4A%3D>)

#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "Dynamic")

```log

```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "Runtime")

```log

```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "ILEmit")

```log

```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "Expressions")

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [5e79b4f17a1486da0fd5e243c7aa5c712910d6a5](https://github.com/dotnet/runtime/commit/5e79b4f17a1486da0fd5e243c7aa5c712910d6a5)
Compare | [8fe4f8b2bc2cb4e033a8cdf5b55efa0bda41c6bc](https://github.com/dotnet/runtime/commit/8fe4f8b2bc2cb4e033a8cdf5b55efa0bda41c6bc)

### Regressions in Microsoft.Extensions.DependencyInjection.GetService

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[ServiceScope](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.GetService.ServiceScope.html>) | 715.68 ns | 901.26 ns | 1.26 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.GetService_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_05_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=true_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.GetService.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.GetService*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-375a4e34-f4a7-4018-99a5-8cae6bda5dacbf17a190f2f4068a1/b4c78bd1-a734-4829-ad9e-3a117408d620.zip?sv=2019-07-07&se=2021-05-01T19%3A09%3A00Z&sr=c&sp=rl&sig=pG2RYubrEckHtr%2FdLcLZvryMsj%2BL3HJ%2BKv%2BXfFG%2Bdfw%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-5a543145-e6f4-44b4-8117-42ac16de4d5e1d63ef36f7d45c19b/4faaa7c1-084e-418a-b6bc-ade1bb875d71.zip?sv=2019-07-07&se=2021-05-02T09%3A27%3A47Z&sr=c&sp=rl&sig=Ptf4rHvGWRumEXKQb%2FwBPN%2BhDNvyFWljygV%2B0coJl4A%3D>)

#### Microsoft.Extensions.DependencyInjection.GetService.ServiceScope

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by davidfowl** [comment]
Definitely. Where are these benchmarks?

**Comment by davidfowl** [comment]
@naricc Do these tests automatically re-run, the change is pretty much reverted.

**Comment by naricc** [comment]
@davidfowl It doesn't automatically tell me things have been fixed, but there are daily runs. And it looks like this has been fixed. Thanks!
