### ISSUE TITLE
OptionsFactory constructor should check for null validations before calling ToArray()

### ISSUE THREAD

**Issue by brettsam** [dotnet/runtime#51023]
Functions ran into this in .NET 6 Preview 3 as we have some older code that wraps `OptionsFactory` in a 2.1 library (before the validations were added). Once we moved to Preview 3, we get exceptions because the constructor we use passes null validations to the second constructor, resulting in a null ref.

This was changed here: https://github.com/dotnet/runtime/pull/49970
/cc @davidfowl 

https://github.com/dotnet/runtime/blob/3d30dc4511b925dc4f6248292d00e08dc731c514/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs#L23-L42

**Comment by davidfowl** [comment]
I think this would be trivial to fix but null IEnumerable\<T\> is an anti-pattern.

**Comment by davidfowl** [comment]
Ah, wait I see that we pass null ourselves 🤦🏾

**Comment by davidfowl** [comment]
Thanks for the report!
