### ISSUE TITLE
FilsStream.Read(buffer, offset, count) error in index validation

### ISSUE THREAD

**Issue by Rocco970** [dotnet/runtime#51024]
### Description

The FileStream.Read() function throws this error with valid values within the bound of the array : 

    ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements 
    from index to the end of the source collection.

Code to recreate  (Use file bigger than pageSizeInBytes):
  
        static void Main(string[] args)
        {
            const int pageSizeInBytes = 10485760; //10mb

            using (FileStream uploadFileStream = File.OpenRead("C:\\Users\\Downloads\\1 (2)"))
            {
                UploadFile(uploadFileStream);
                uploadFileStream.Close();
            };

            void UploadFile(FileStream uploadFileStream)
            {
                long prevLastByte = 0;
                long bytesRemain = uploadFileStream.Length;

                do
                {
                    long bytesToCopy = Math.Min(bytesRemain, pageSizeInBytes);
                    byte[] bytesToSend = new byte[bytesToCopy];

                    uploadFileStream.Read(bytesToSend, (int)prevLastByte, bytesToSend.Length);

                    prevLastByte += bytesToCopy;
                    bytesRemain -= bytesToCopy;

                } while (bytesRemain > 0);

            }
        }

Wrapping uploadFileStream.Read(bytesToSend, (int)prevLastByte, bytesToSend.Length); in a try/catch block to ignore the exception resolves the issue.

### Configuration

.NET 5
Windows 10 latest version

**Comment by huoyaoyuan** [comment]
Your code is wrong. You misunderstanded the `offset` argument. It means the offset of the array, not the offset of file. The `FileStream` itself moves the position of file.

BTW you don't need to count for remaining length. Sample code:

```csharp
byte block = new byte[BlockSize];
while (!fs.EndOfStream)
{
    int bytesRead = fs.Read(block);
    // do something with block
}
