### ISSUE TITLE
Inconsistent behaviour of RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)

### ISSUE THREAD

**Issue by polijp** [dotnet/runtime#51053]
Hi everyone.

Implementing an extension method IsCastableInto that indicates if a given Type A is castable into a Type B, I implemented a unit test.

In that purpose, I use reflection and I have these exceptions: System.ArgumentException: Object of type 'System.Byte' cannot be converted to type 'System.Decimal', with stack trace:

RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
    RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
    MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
    RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    MethodBase.Invoke(Object obj, Object[] parameters)

This is not compliant with the struct Decimal that implements implicit cast operators. I tested on .net core 3.1 and .net 5.0, on Windows 10 64bits,  it is the same issue.

Here is the code I used:

`[TestMethod]
        public void Test1()
        {
            var f = new Func<decimal, bool>(d => true);
            Assert.IsTrue(f.Invoke((sbyte)-1));
        }`

This one completes successfully and validates the following, that fail:
`[TestMethod]
        public void Test2()
        {
            var f = new Func<decimal, bool>(d => true);
            MethodInfo meth = f.Method;
            Assert.IsTrue((bool)f.Method.Invoke(f.Target, new object[] { (sbyte)-1 }));
        }`

        `[TestMethod]
        public void Test3()
        {
            var f = new Func<decimal, bool>(d => true);
            MethodInfo meth = f.Method;
            Assert.IsTrue((bool)f.Method.Invoke(f.Target, new object[] { (byte)1 }));
        }`

By the way, it seems that somewhere in the runtime, the info IsCastableInto exists, it could be a new method to add to class Type :).

**Comment by acaly** [comment]
Runtime never converts from byte/sbyte to decimal when calling a method. The first example works because when you compile that code, the C# compiler automatically insert an conversion instruction in between. In the reflection cases, C# compiler can't help so you see the runtime blaming about wrong type.

Checking and performing numeric conversions can be complicated as there is no "Method" in the runtime to do that, but usually IL instructions. The best way I know about is to use expression tree. For example:

```c#
using System;
using System.Linq.Expressions;

static bool CanConvert<T1, T2>()
{
    try
    {    
        var expr = Expression.Convert(
            Expression.Constant(default(T1), typeof(T1)),
            typeof(T2));
        return true;
    }
    catch
    {
        return false;
    }
}

Console.WriteLine($"int -> string: {CanConvert<int, string>()}"); //false
Console.WriteLine($"int -> byte: {CanConvert<int, byte>()}"); //true
Console.WriteLine($"byte -> int: {CanConvert<byte, int>()}"); //true
Console.WriteLine($"sbyte -> decimal: {CanConvert<sbyte, decimal>()}"); //true
```

The created expression tree object can also be used to perform the conversion later. Note that you can cache these objects (or a null in case of failure) yourself so when it failed the exception is only thrown once.

**Comment by polijp** [comment]
Hello.
Thank you for your answer.
So this documentation is wrong, isn’t it ?

https://docs.microsoft.com/fr-fr/dotnet/csharp/language-reference/builtin-types/numeric-conversions

 Maybe this issue must be tagged for a documentation update. Isn’t it ?

Thx

Envoyé de mon iPhone

**Comment by jkotas** [comment]
This documentation talks about C# language. The conversions performed by reflection are different from conversions performed by C# language.

**Comment by polijp** [comment]
Ok thank you for this information 

Envoyé de mon iPhone
