### ISSUE TITLE
RuntimeInformation.IsOSPlatform(OSPlatform.Linux) returns false on Android.

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#51052]
`RuntimeInformation.IsOSPlatform(OSPlatform.Linux)` returns `false` on android.

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 Thank you for reporting this issue. The original title "Breaking change in net5/6" indicated this is a breaking change - what is breaking change from? .NET Core 3.1? Mono?

It would be helpful to know when this worked so we can determine the scope of impact and what needs to happen.

/cc @marek-safar @steveisok

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 It looks like the `RuntimeInformation` approach above was supplanted by using [`OperatingSystem`](https://docs.microsoft.com/dotnet/api/system.operatingsystem) for this sort of query. See [`OperatingSystem.IsAndroid`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.isandroid).

**Comment by SupinePandora43** [comment]
> @SupinePandora43 It looks like the `RuntimeInformation` approach above was supplanted by [`OperatingSystem`](https://docs.microsoft.com/dotnet/api/system.operatingsystem) for this sort of query. See [`OperatingSystem.IsAndroid`](https://docs.microsoft.com/dotnet/api/system.operatingsystem.isandroid).

Yes, i already know about `OperatingSystemIsAndroid()`.
But there's libraries that still uses `RuntimInformation`.

**Comment by SupinePandora43** [comment]
> @SupinePandora43 Thank you for reporting this issue. The original title "Breaking change in net5/6" indicated this is a breaking change - what is this a breaking change from? .NET Core 3.1? Mono?
> 
> It would be helpful to know when this worked so we can determine the scope of impact and what needs to happen.
> 
> /cc @marek-safar @steveisok

in Non-SDK style project

with
`<TargetFrameworkVersion>v7.1</TargetFrameworkVersion>`
...
`<Reference Include="Mono.Android" />`
...
`<Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />`

`RuntimeInformation.IsOSPlatform(OSPlatform.Linux)` return `true`

**Comment by marek-safar** [comment]
It makes sense to update this to match our RID graph

**Comment by SupinePandora43** [comment]
@steveisok, how it's going?

**Comment by akoeplinger** [comment]
We've decided to keep this behavior since Android is not comparable to a normal Linux distribution.
It also matches what other programming languages/environments do, e.g. Flutter (https://api.flutter.dev/flutter/dart-io/Platform/isLinux.html):

> bool isLinux
> Whether the operating system is a version of Linux.
> This value is false if the operating system is a specialized version of Linux that identifies itself by a different name, for example Android (see isAndroid).

**Comment by SupinePandora43** [comment]
> We've decided to keep this behavior since Android is not comparable to a normal Linux distribution.
> It also matches what other programming languages/environments do, e.g. Flutter (https://api.flutter.dev/flutter/dart-io/Platform/isLinux.html):
> 
> > bool isLinux
> > Whether the operating system is a version of Linux.
> > This value is false if the operating system is a specialized version of Linux that identifies itself by a different name, for example Android (see isAndroid).

the flutter `Platform.is*` api you sent above, is comparable to `OperatingSystem.Is*` api
Not `OSPlatform`

**Comment by akoeplinger** [comment]
@SupinePandora43 for .NET 5+ the RuntimeInformation/OSPlatform APIs are not the preferred way anymore since the `OperatingSystem.IsAndroid()` etc. APIs are much simpler.

If you need to multi-target to an earlier .NET Core version you can use `RuntimeInformation.IsOSPlatform(OSPlatform.Create("ANDROID"))`, it internally calls into `OperatingSystem` on .NET5+ so the results will be the same.
