### ISSUE TITLE
Use ValueTask-returning async FileStream methods wherever possible

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#51050]
With https://github.com/dotnet/runtime/pull/50802 and the next upcoming PR from @carlossanlop the following `FileStream` methods are going to become allocation-free:

```cs
ValueTask<int> ReadAsync(Memory<byte> destination, CancellationToken cancellationToken = default)
ValueTask WriteAsync(ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default)
```

The "old", Task-returning overloads are still going to be allocating memory:

```cs
Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
```

The person who is willing to work on this task should:

1. Search the entire runtime repo for places where the mentioned Task-returning methods are used. Please keep in mind that it's possible that we are already doing the right thing and you won't find any places for improvements.
2. If you find places that can be improved, contribute benchmarks to the [dotnet/performance](https://github.com/dotnet/performance/tree/main/src/benchmarks/micro) repo after reading the [Microbenchmark Design Guidelines](https://github.com/dotnet/performance/blob/main/docs/microbenchmark-design-guidelines.md) doc. The benchmarks need to cover the code that is about to be changed.
3. Run the benchmarks following the [Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md) doc and ensure the changes are improving perf (with a focus on the managed allocations).
4. Contribute the improvements to dotnet/runtime and provide benchmark results

**Note**: some of the libraries are still targeting .NET Standard or even Full .NET Framework. For these libs, you might need to use conditional compilation like in the example below:

https://github.com/dotnet/runtime/blob/0af5228e8fbf24f4fecfe292c0df732e64ae13c2/src/libraries/System.IO.FileSystem/src/System/IO/File.cs#L986-L990

**Comment by stephentoub** [comment]
This is unlikely to be very fruitful.  I've previously made passes through to fix all such stream usage,  and we now have an analyzer that flags such usage.

**Comment by adamsitnik** [comment]
> This is unlikely to be very fruitful.

@stephentoub I agree, I just want someone to set it to `Error` and ensure that we are not doing it anywhere. 

> we now have an analyzer that flags such usage.

Thanks! We are going to mention the analyser in our FileStream perf best practices docs 👍

**Comment by stephentoub** [comment]
> I just want someone to set it to Error

What does this mean?

**Comment by adamsitnik** [comment]
> We treat warnings as errors.

I was not aware of that. In such a case, I am just going to close the issue. Thanks!
