### ISSUE TITLE
Consider adding BitConverter.GetBytes(Half value) overload

### ISSUE THREAD

**Issue by lucasteles** [dotnet/runtime#51081]
BitConverter has APIs to convert almost any primitive value to Bytes, but not Half (which is kinda new)  

```cs
    var number = (Half)2f;
    var b = BitConverter.GetBytes(number); // broken
```

**Comment by tannergooding** [comment]
Actually, this was already reviewed, approved and implemented via https://github.com/dotnet/runtime/issues/41318.

The APIs are available in the latest .NET 6 previews:
* https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.getbytes?view=net-6.0#System_BitConverter_GetBytes_System_Half_
* https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.tohalf?view=net-6.0
* https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter.trywritebytes?view=net-6.0#System_BitConverter_TryWriteBytes_System_Span_System_Byte__System_Half_
