### ISSUE TITLE
Reuse byte buffers when using MemoryPool<T>.Shared for blittable types

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#51100]
This is not API proposal as we don't need to change API surface. Currently, `MemoryPool<T>.Shared` is just a proxy for `ArrayPool<T>.Shared`. It could be smarter if `T` is a blittable type. Instead of maintaining the pool for each variation of `T` it could reinterpret **byte** buffer for every blittable type. Thus, `Memory<T>.Shared` is always backed by `ArrayPool<byte>.Shared` if `RuntimeHelpers.IsReferenceOrContainsReferences<T>` returns **false**.

**Comment by tannergooding** [comment]
This might not work as trivially as expected and could end up having a negative impact on perf because some platforms disallow or behave very poorly with misaligned data.

**Comment by jkotas** [comment]
Also, this would not work if one gets the underlying `Memory<T>` array and uses it with casting.

**Comment by sakno** [comment]
> Also, this would not work if one gets the underlying Memory<T> array and uses it with casting.

How? `MemoryMarshal.TryGetArray` will not return array because the memory block is backed by `MemoryManager<T>`. `ToArray` will create a copy.

> This might not work as trivially as expected and could end up having a negative impact on perf because some platforms disallow or behave very poorly with misaligned data.

On such platforms it's possible to leave the current behavior.

**Comment by tannergooding** [comment]
> On such platforms it's possible to leave the current behavior.

That can be all platforms, including x86/x64. While modern (in the last 10 years or so) CPUs have fast unaligned accesses, pre-2012 models tend to be lacking this support. Additionally, even modern platforms can have fairly significant penalties for cross cache-line and cross page-boundary reads/writes (although modern CPUs have greatly reduced the penalties here) which for large `T` will be more common (particularly if talking about something like `Vector<T>`, `Vector128<T>`, or `Vector256<T>`).

**Comment by jkotas** [comment]
> `MemoryMarshal.TryGetArray` will not return array because the memory block is backed by `MemoryManager<T>`

This is not correct. Try this - it is going to print true:
```
using System;
using System.Buffers;
using System.Runtime.InteropServices;

IMemoryOwner<byte> mo = MemoryPool<byte>.Shared.Rent(10);

Console.WriteLine(MemoryMarshal.TryGetArray<byte>(mo.Memory, out var segment));
```

**Comment by DaZombieKiller** [comment]
I think @sakno was referring to the case of a `Memory<T>` being backed by a `byte[]` buffer (as proposed), which would require the `Memory<T>` instance to use a `MemoryManager<T>` (as the underlying array isn't `T[]` but a `byte[]`.)

**Comment by sakno** [comment]
OK, I see that the implementation of this proposal is challenging of various platforms and require to change the behavior.
