### ISSUE TITLE
[Proposal] Obtain readonly ref to the value from Nullable<T>

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#51108]
## Background and Motivation
When I'm working with nullable type there is no way to obtain underlying value without in-place copy.

## Proposed API
```csharp
public static class MemoryMarshal
{
  public static ref readonly T GetReference<T>(in T? nullable)
    where T : struct;
}
```
The method returns **null** reference (`Unsafe.NullRef<T>`) if nullable value has no value. The method gives the similar abilities as the methods from `CollectionsMarshal` class.

## Usage Examples
```csharp
public static string ToString(in Guid? g)
{
  ref readonly Guid value = ref MemoryMarshal.GetReference(in g);
  if (Unsafe.IsNullRef<Guid>(Unsafe.AsRef(in value)))
    return string.Empty;

  return value.ToString();
}
```

## Risks
The user may attempt to deref **null** reference.

**Comment by jkotas** [comment]
Duplicate of #1534

**Comment by sakno** [comment]
Closing as duplicate.
