### ISSUE TITLE
[WASM][AOT] Assertion at /__w/1/s/src/mono/mono/mini/interp/transform.c:8811, condition `<disabled>' not met

### ISSUE THREAD

**Issue by dantronik-markus** [dotnet/runtime#51107]
### Configuration

* Which version of .NET is the code running on? .NET 6.0
* What OS and version, and what distro if applicable? Windows Server 2012
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I do not know.
* If you're using Blazor, which web browser(s) do you see this issue in?
We're using Blazor and the issue is shown in Microsoft Edge, Mozilla Firefox and Google Chrome

### Regression?
This worked in the previous Blazor build (last preview I tested before this was preview 6.0 update 1 (which had other issues but not this one))

### Other information
Specific log file from my browser console:
[192.168.1.53-1618226346938.log](https://github.com/dotnet/runtime/files/6296164/192.168.1.53-1618226346938.log)

The component throwing the issue is this one:
[JahrInput.zip](https://github.com/dotnet/runtime/files/6296177/JahrInput.zip)

The issue happens when clicking the down or up buttons on the <input type="number"> elements.

The "JahrRange" control is used in a Syncfusion Blazor dialog component. I doubt it's required that I attached the source code for that as well, but if you want I can do that.

**Comment by dantronik-markus** [comment]
I was able to pinpoint the issue to this warning:
Warnung	BL0005	Component parameter 'Jahr' should not be set outside of its component. JahrRange.razor	28	

The issue appears because of this warning.

**Comment by BrzVlad** [comment]
@dantronik-markus Could you provide a complete reproducing sample project ?

**Comment by dantronik-markus** [comment]
I've tried creating a small sample project. However, I appear to be blocked by https://github.com/dotnet/aspnetcore/issues/33283

**Comment by dantronik-markus** [comment]
Okay, I managed to get it working. You can find the repository here: https://github.com/dantronik-markus/blazor-publish-bug

**Comment by dantronik-markus** [comment]
Once the project is published and started, click any of the two Startjahr / Endjahr numeric select boxes.

**Comment by BrzVlad** [comment]
Had a similar crash reported in the past, but wasn't able to get my hands on a repro. Created fix for issue. Thanks !
