### ISSUE TITLE
Host should inform user about other installed archs on the system

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#51101]
Commands like `dotnet --info` or `dotnet --list-runtimes`/`dotnet --list-sdks` currently report only the runtimes/SDKs installed for the architecture used to run the command. But some systems can run more than one architecture, for example x86 and x64 on Windows (or x64 and arm64 on Apple M1).

For example if I install:
* .NET 5 x64
* .NET 3.1 x86 (either on purpose or accidently picked the wrong architecture)

Running `dotnet --info` will only list .NET 5 - which is confusing.

Consider adding the ability to "know about" all the other architectures on the system and either informing the user about their existence or maybe listing the runtimes in those locations in a separate section of the output.

**Comment by agocke** [comment]
I believe this is now complete. Is that right?
