### ISSUE TITLE
System.IO.Path - Path.GetFileNameWithoutExtension Method returning wrong info

### ISSUE THREAD

**Issue by frosadev** [dotnet/runtime#51106]
### Description

The method mentioned cannot handle windows paths (e.g. **c:\\folder1\\somefile.txt**) when running on Linux.

I have some strings that represent windows paths that I need to get the name of the files without the extensions.
On Windows the result is (from the example: **c:\\folder1\\somefile.txt**):

**somefile.txt**

The same application, when running on Linux the result is:

**c:\\folder1\\somefile**

I'm using .NET 5.

Is this the expected behavior?

Thanks in advance.

**Comment by watfordgnf** [comment]
Yes, from [System.IO.Path](https://docs.microsoft.com/en-us/dotnet/api/system.io.path?view=net-5.0#remarks):
> The current platform also determines the set of characters used to separate the elements of a path, and the set of characters that cannot be used when specifying paths. Because of these differences, the fields of the Path class as well as the exact behavior of some members of the Path class are platform-dependent.

**Comment by SimonCropp** [comment]
@carlossanlop seems this is by design and should be closed?

**Comment by carlossanlop** [comment]
It's expected behavior. The `\` and `:` characters are valid path name characters on Unix. Also, `C:\` is not a valid root prefix on Unix. The root should be `/`. So what's happening here is that the whole string is being considered a file name.
