### ISSUE TITLE
Blazor async timing issue

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/runtime#51115]
Reference:
https://github.com/dotnet/aspnetcore/issues/26314

https://github.com/dotnet/aspnetcore/issues/22400

https://stackoverflow.com/questions/63211539/blazor-startup-error-system-threading-synchronizationlockexception-cannot-wait

Fails:

	protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        try
        {
            IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(0, 100, "Rate of Unemployment")); 
        }
        catch (Exception ex)
        {
            string y = ex.Message; // 'Cannot wait on monitors on this runtime.':
        }
    }
	
Fails with 'Cannot wait on monitors on this runtime.' [See also](https://mudblazor.com/components/table):

	<MudTable ServerData="@(new Func<TableState, Task<TableData<Series>>>(LoadSeries))" Dense="true" Hover="true" @ref="seriesTable">
	
	private async Task<TableData<Series>> LoadSeries(TableState tableState)
    {
        IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(tableState.Page * tableState.PageSize, tableState.PageSize, searchTitle)); // fails
        return new TableData<Series> { TotalItems = 100, Items = series };
    }
	
	
After several hours of trying to solve this I pasted the code into a buttton click handler of another control and found that it runs just fine:

	public async Task OkClickHandler()
    {
        MudDialog.Close(DialogResult.Ok(true));

        if (string.IsNullOrEmpty(symbols))
            return;

        // test
        try
        {
            IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(0, 100, "Rate of Unemployment"));
            System.Diagnostics.Debug.Assert(series != null);  // works
        }
        catch (Exception ex)
        {
            string y = ex.Message;
        }
        // test

		// also works - never had a problem
        var results = await serviceClient.CallAsync(x => x.SeriesService.SaveLocalSeries(symbols.Split(',')));
    }

Under the hood my `serviceClient` does little more than call `httpClient`. I discovered if I make a call to httpClient before calling my code it works:

	protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
		
		// await Task.Delay(10000); // does not work
		
        httpClient = httpClientFactory.CreateClient("ServerAPI");

        try
        {
            var junk = await httpClient.GetFromJsonAsync<IEnumerable<Series>>($"DownloaderServices/GetLocalSeries/{0}/{100}/Rate of Unemployment"); // works
            IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(0, 100, "Rate of Unemployment")); // works
        }
        catch (Exception ex)
        {
            string y = ex.Message;
        }
    }

Making an unnecessary http call also works for the load event handler of the control.  I will provide working/non-working versions here:

Fails:	
	
	private async Task<TableData<Series>> LoadSeries(TableState tableState)
    {
        searchTitle = "Rate of Unemployment";
        //var junk = await httpClient.GetFromJsonAsync<IEnumerable<Series>>($"DownloaderServices/GetLocalSeries/{0}/{100}/Rate of Unemployment"); // works
        IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(tableState.Page * tableState.PageSize, tableState.PageSize, searchTitle)); // fails: Cannot wait on monitors on this runtime.
        return new TableData<Series> { TotalItems = 100, Items = series };
    }

Works - but only if unnecessary http call is also made in `OnInitializedAsync`:

	private async Task<TableData<Series>> LoadSeries(TableState tableState)
    {
        searchTitle = "Rate of Unemployment";
        var junk = await httpClient.GetFromJsonAsync<IEnumerable<Series>>($"DownloaderServices/GetLocalSeries/{0}/{100}/Rate of Unemployment"); // works
        IEnumerable<Series> series = await serviceClient.CallAsync(x => x.SeriesService.GetLocalSeries(tableState.Page * tableState.PageSize, tableState.PageSize, searchTitle)); // works
        return new TableData<Series> { TotalItems = 100, Items = series };
    }
	

The `Cannot wait on monitors on this runtime.` error message really seems misleading.  I spent a lot of time chasing that for naught.  If my code was blocking it should hang 100% of the time, correct?

Please suggest how I might fix this.  Thanks.

**Edit**:  I am still trying to solve this because it is blocking me.  Code below can be pasted in a new app.  Fails 100% of the time as shown:

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!firstRender)
            return;

        await base.OnAfterRenderAsync(firstRender);
        string txt = null;
        HttpClient httpClient = new HttpClient();
        
        
        if (true)
            await Task.Delay(50).ContinueWith(async x => txt = await httpClient.GetStringAsync(new Uri("https://localhost:5001"))); //fails
        else
            txt = await httpClient.GetStringAsync(new Uri("https://localhost:5001")); //works

        System.Diagnostics.Debug.Assert(txt != null);

    }

**Comment by stephentoub** [comment]
> Doing things like ContinueWith might be problematic and also lead to problems.

@javiercn, what about ContinueWith?

**Comment by sam-wheat** [comment]
Fails 100% of the time:

    await Task.Delay(50).ContinueWith(async x => txt = await httpClient.GetStringAsync(new Uri("https://localhost:5001"))); //fails

**Comment by javiercn** [comment]
@stephentoub just realized that part of the guidance was an oversight on my part.

We normally tell people to avoid things like ContinueWith and so on when they are doing async work to avoid running into issues with the sync context, however I just realized this doesn't apply here.

In any case, I think this should be reproducible on a "console" wasm app, since there's no Blazor involved in the repro and we don't have a sync context in webassembly like we do in server that could play a role here.

**Comment by stephentoub** [comment]
> Fails 100% of the time:

Because of the ContinueWith?  What is the call stack of the exception?

**Comment by sam-wheat** [comment]
![Capture](https://user-images.githubusercontent.com/16885210/114402910-262fe600-9b59-11eb-898a-1da1229933ad.PNG)

Steps to reproduce > New blazor project, .net hosted.  Add the following to index.razor:

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!firstRender)
            return;

        await base.OnAfterRenderAsync(firstRender);
        string txt = null;
        HttpClient httpClient = new HttpClient();


        if (true)
            await Task.Delay(50).ContinueWith(async x => txt = await httpClient.GetStringAsync(new Uri("https://localhost:5001"))); //fails
        else
            txt = await httpClient.GetStringAsync(new Uri("https://localhost:5001")); //works


        
        

        System.Diagnostics.Debug.Assert(txt != null);

    }

**Comment by stephentoub** [comment]
Your repro has a bug.  ContinueWith doesn't have an overload that accepts a task-returning delegate, so your ContinueWith call is actually returning a `Task<Task<string>>`, not a `Task<string>`.  Thus your await on the ContinueWith is only waiting for the synchronous call to the delegate to finish, not for the whole asynchronous operation it contains to finish.

Try appending `.Unwrap()` to the end of the ContinueWith, or try changing the `await` to instead be `await await`, and I expect you'll see your assert go away.

**Comment by sam-wheat** [comment]
Thanks I will try it.  For the record this is a bit off the track from the issue cited above.  I was throwing darts trying to fix my control as mentioned above.  The real problem I need to solve is in my first post.

**Comment by sam-wheat** [comment]
I found the issue.  Thanks.
