### ISSUE TITLE
JsonAfterConstructor validation attribute

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#51118]
## Background and Motivation

JsonConstructorAttribute is called before the properties are assigned.
There is no easy option to make validation after the assignment.

## Proposed API

```cs
class A
{
 // Called before properties assignment
 // public A() {}

 // Called after all properties are assigned
 [JsonValidationConstructor]
 public A(JsonValidation _)
 {
   // Here X = 1, Y = 0
   if(X + Y < 10) throw new Exception();
 }
 
 public int X {get;set;}
 public int Y {get;set;}
}
```

```cs
JsonSerializer.Deserialize("{\"X\":1}");
```

**Comment by eiriktsarpalis** [comment]
This is related to https://github.com/dotnet/runtime/issues/39896. I would recommend contributing to the conversation there on the design of the feature. Meanwhile please note that there is a [recommended workaround](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#callbacks) for this type of scenario.

I'm going to close this issue, thank you for your contribution.

**Comment by NN---** [comment]
The workaround is known but not so nice :)
