### ISSUE TITLE
DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies.

### ISSUE THREAD

**Issue by HemalathaChiranjeevulu** [dotnet/runtime#51122]
**Description:**

We are getting exception while converting multiple tiff file to single tiff file.

**Exception:**

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Gdip' threw an exception.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetImageEncodersSize(Int32& numEncoders, Int32& size)
   at System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders()

Inner Exception 1:
DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory

**Code snippet:**

             //Gets the input tiff files.
            string[] filePaths = Directory.GetFiles(@"Data");

            ImageCodecInfo encoderInfo = GetEncoderInfo("image/tiff");
            //Initialize EncoderParameters that contain specified number of Encoderparameter objects
            EncoderParameters encoderParams = new EncoderParameters(2);
            //Initialize EncoderParameter
            EncoderParameter parameter = new EncoderParameter(Encoder.Compression, (long)EncoderValue.CompressionNone);
            encoderParams.Param[0] = parameter;
            // Initializes the new instance for EncoderParameter.
            parameter = new EncoderParameter(Encoder.SaveFlag, (long)EncoderValue.MultiFrame);
            encoderParams.Param[1] = parameter;

            Bitmap pages = null;
            System.IO.Stream stream = new MemoryStream();
            //Convert multiple tiff files to a single tiff file.
            for (int i = 0; i < filePaths.Count(); i++)
            {
                if (i == 0)
                {
                    FileStream fileStreamPath = new FileStream(filePaths[i], FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                    pages = (Bitmap)Image.FromStream(fileStreamPath);

                    //Saves the first page.
                    pages.Save("TiffFile.tiff", encoderInfo, encoderParams);

                    //Saves the second page if any in tiff file.
                    int frameCount = pages.GetFrameCount(FrameDimension.Page);
                    if (frameCount > 1)
                    {
                        for (int j = 1; j < frameCount; j++)
                        {
                            encoderParams.Param[0] = new EncoderParameter(Encoder.SaveFlag, (long)EncoderValue.FrameDimensionPage);
                            pages.SelectActiveFrame(FrameDimension.Page, j);
                            pages.Save(stream, encoderInfo, encoderParams);
                        }
                    }
                    fileStreamPath.Close();
                }
                else
                {
                    //Save the intermediate frames.
                    encoderParams.Param[0] = new EncoderParameter(Encoder.SaveFlag, (long)EncoderValue.FrameDimensionPage);

                    FileStream fileStreamPath = new FileStream(filePaths[i], FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                    Bitmap bm = (Bitmap)Image.FromStream(fileStreamPath);
                    int frameCount = bm.GetFrameCount(FrameDimension.Page);
                    for (int k = 0; k < frameCount; k++)
                    {
                        bm.SelectActiveFrame(FrameDimension.Page, k);
                        pages.SaveAdd(bm, encoderParams);
                    }
                    fileStreamPath.Close();
                }
            }

          /// <summary>
        /// Gets the encoder info.
        /// </summary>
        /// <param name="mimeType">MIME type</param>
        /// <returns>Image code info.</returns>
        private static ImageCodecInfo GetEncoderInfo(String mimeType)
        {
            ImageCodecInfo[] encoders = ImageCodecInfo.GetImageEncoders();
            foreach (ImageCodecInfo imageCodecInfo in encoders)
            {
                if (imageCodecInfo.MimeType == mimeType)
                    return imageCodecInfo;
            }
            return null;
        }

Please find the issue reproduceable sample:
[CoreApplication.zip](https://github.com/dotnet/aspnetcore/files/6297677/CoreApplication.zip)

**Basic information:**

ASP.NET Core version: 3.1
IDE: Visual studio 2019

**Note:**

Issue not reproduced in simple core sample.
Issue reproduced in **docker sample** only.

**Comment by safern** [comment]
> Issue reproduced in docker sample only.

Hey, @HemalathaChiranjeevulu, dos your docker image have `libgdiplus` installed? If not you will need to install it for `System.Drawing.Common` to work.

I don't know which flavor is your image, but if you share that info I could provide instructions on how to install it.

**Comment by safern** [comment]
Thanks for the information. I will try to build a docker image with that docker file and try and repro. Will keep you posted, thanks for the info.

**Comment by safern** [comment]
Hey @HemalathaChiranjeevulu -- built the docker image and deployed a small webapi that did:

```cs
[ApiController]
[Route("test")]
public class DrawingController
{
    [HttpGet]
    public IEnumerable<string> Get()
    {
        var result = ImageCodecInfo.GetImageEncoders().Select(i => i.CodecName).ToArray();
        if (result.Length <= 0)
            return new[] { "empty" };
        
        return result;
    }
}
```

I ran the docker container and I can perfectly fine get the results:
![image](https://user-images.githubusercontent.com/22899328/117520053-3b7f1100-af5b-11eb-87c4-9dcd7f9e677f.png)

I used my custom server app because I couldn't get the dockerfile to build because I have no access to the `acrunifi01.azurecr.io/snu-api-base:1` docker image.

The reason why I chose that code is because of the stack trace:
```
StackTrace:
at System.Drawing.SafeNativeMethods.Gdip.GdipGetImageEncodersSize(Int32& numEncoders, Int32& size)
at System.Drawing.Imaging.ImageCodecInfo.GetImageEncoders()
```

Could you please provide the output of your app if you set `LD_DEBUG` env var to see where it is trying to search for libgdiplus? 

http://www.bnikolic.co.uk/blog/linux-ld-debug.html
