### ISSUE TITLE
Test failure: tracing/eventpipe/bigevent/bigevent/bigevent.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#51133]
GCStress=3, OSX arm64

Test timeout (1 hour timeout)

https://dev.azure.com/dnceng/public/_build/results?buildId=1082387&view=ms.vss-test-web.build-test-results-tab&runId=33192976&resultId=108630&paneView=debug

**Comment by BruceForstall** [comment]
@sdmaclea

**Comment by sdmaclea** [comment]
@Josalem I think we can just leave this test disabled unless you disagree.

**Comment by josalem** [comment]
Was the issue on ASi ever root caused?

**Comment by sdmaclea** [comment]
No root cause.  This was timing out with GCStress...  The bigevent said maybe gcstress incompatible was reasonable.

**Comment by noahfalk** [comment]
Closing based on @sdmaclea's suggestion. We'll leave the test disabled on GC-stress.
