### ISSUE TITLE
Test failure: baseservices/threading/generics/Monitor timeouts

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#51132]
GCStress=3, Linux arm, tests time out (1 hour timeout)

https://dev.azure.com/dnceng/public/_build/results?buildId=1082387&view=ms.vss-test-web.build-test-results-tab

Failures:
```
baseservices/threading/generics/Monitor/TryEnter03/TryEnter03.sh
baseservices/threading/generics/Monitor/TryEnter01/TryEnter01.sh
baseservices/threading/generics/Monitor/EnterExit12/EnterExit12.sh
baseservices/threading/generics/Monitor/TryEnter05/TryEnter05.sh
baseservices/threading/generics/Monitor/TryEnter06/TryEnter06.sh
```

**Comment by BruceForstall** [comment]
TryEnter03 and TryEnter06 also fail in the R2R Linux arm GCStress=f job (1.5 hour timeout):

https://dev.azure.com/dnceng/public/_build/results?buildId=1082729&view=ms.vss-test-web.build-test-results-tab

**Comment by mangod9** [comment]
Closing for now, assuming it only failed on a single build.
