### ISSUE TITLE
NET 5 returns wrong DateTimeFormat.FirstDayOfWeek

### ISSUE THREAD

**Issue by bella2793** [dotnet/runtime#51146]
Can somebody tell me how to get the right value from DateTimeFormat.FirstDayOfWeek when using NET5?

The culture I'm investigating on is "en-AU".

https://dotnetfiddle.net/v0RAV4 (.NET 4.7.2) vs https://dotnetfiddle.net/FYV8OW (NET 5).

The correct value is Monday. Why does NET5 return Sunday? How can I fix this behaviour?

**Comment by tarekgh** [comment]
@bella2793 thanks for your report. In .NET 5.0 we have started using ICU library which is using the standard CLDR published by Unicode standard. When looking at the data, I am seeing the data says the first day of week in Australia is Sunday. https://github.com/unicode-org/cldr/blob/03d36f135efc2062893b3365ed66f81e15f0065d/common/supplemental/supplementalData.xml#L4715

Doing some internet search, I am seeing people already not in agreement on that. 

In the full framework and in .NET Code up to 3.x, we use Windows NLS APIs (and not ICU) which returns the first day of week as Monday. I would suggest of you don't agree with CLDR data, you can try report the issue to them and get that fixed there. Note, .NET doesn't really carry any data. 

The article https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu is useful to know the change we have done in .NET 5.0 and also the doc has the info how you can switch back to the old behavior if need. We don't recommend that though as sticking with the standard is better choice in general. 

I am closing the issue but feel free to send any question and we'll be happy to help with.

**Comment by tarekgh** [comment]
Some other useful link https://unicode-org.atlassian.net/browse/CLDR-2472.
