### ISSUE TITLE
Best way to detect whether STA is supported at runtime?

### ISSUE THREAD

**Issue by rjmholt** [dotnet/runtime#51152]
In https://github.com/PowerShell/PowerShell/pull/15106, PowerShell is trying to add a check for STA support to determine what mode it should be started in.

Is there a cheaper way to detect whether STA threading is supported than to start a new thread in STA mode and check the exception?

**Comment by jkoritzinsky** [comment]
One way that would be cheaper would be to add an OS version/flavor check into PowerShell using P/Invokes to Windows APIs. There is no API in .NET that exposes this today.

**Comment by AaronRobinsonMSFT** [comment]
@rjmholt Expanding on what @jkoritzinsky said. Windows does have a non-supported scenario but the entire matrix is rather simple.

| Platform | Supports STA|
|-----------|-----|
| Windows | Yes |
| Windows Nano Server | No |
| Non-Windows | No |

**Comment by iSazonov** [comment]
The question comes from the fact there are internal Windows builds and I guess MSFT can not publish its version signatures and support this in a public code. (Currently we already check IsNanoServer and IsIoT but catch an issue again)
Also PowerShell checks STA at startup and we don't want to slow down startup scenario by creating new thread to make the check.

**Comment by AaronRobinsonMSFT** [comment]
>Currently we already check IsNanoServer and IsIoT but catch an issue again

@iSazonov Can you share the scenario where using IsWindows and IsNanoServer fails to detect a STA supported platform?

The general thought here is that exposing these COM centric configuration checks isn't something the runtime would like to be in the business of - it is just as costly to do it for the runtime as the user. The performance cost can be mitigated by turning it into a lazy check though. This does mitigate the check cost but still requires new API surface area for a rather narrow scenario.

We are more than willing to help come up with and document the checks to be successful. It was assumed that using IsWindows and IsNanoServer is enough but if that combination is insufficient please let us know so we can help document the correct approach.

**Comment by iSazonov** [comment]
> @iSazonov Can you share the scenario where using IsWindows and IsNanoServer fails to detect a STA supported platform?

I can not. [The issue](https://github.com/PowerShell/PowerShell/pull/15106) was opened by PowerShell MSFT team for internal Windows build. You could communicate with them internally.

In https://github.com/PowerShell/PowerShell/pull/15106 I suggested that we could do without this check at all and handle the possible exception in an acceptable way where the STA is assigned.

**Comment by AaronRobinsonMSFT** [comment]
@iSazonov Thanks for pushing me back to that issue. I will reach out offline and see if we can get another option.

**Comment by AaronRobinsonMSFT** [comment]
Closing the loop. We spoke offline and the recommended manner to detect STA support for cases on Windows 8 and greater is the following:

```csharp
static void Main(string[] args)
{
    bool staSupported;
    using (var checkSta = new CheckSta())
    {
        staSupported = checkSta.Supported;
    }
}

sealed class CheckSta : IDisposable
{
    [DllImport("api-ms-win-core-com-l1-1-0.dll")]
    private extern static int CoInitializeEx(IntPtr reserve, int coinit);

    [DllImport("api-ms-win-core-com-l1-1-0.dll")]
    private extern static void CoUninitialize();

    private readonly bool _staSupported;
    private readonly bool _cleanUp;

    public CheckSta()
    {
        // See objbase.h
        const int COINIT_APARTMENTTHREADED = 0x2;
        const int E_NOTIMPL = unchecked((int)0X80004001);
        int result = CoInitializeEx(IntPtr.Zero, COINIT_APARTMENTTHREADED);

        // If 0 is returned the thread has been initialized for the first time
        // as an STA and therefore must remain that way.
        _cleanUp = result > 0;
        _staSupported = result != E_NOTIMPL;
    }

    public bool Supported => _staSupported;

    void IDisposable.Dispose()
    {
        if (_cleanUp)
            CoUninitialize();
    }
}
```

/cc @SteveL-MSFT
