### ISSUE TITLE
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception. Getting the exception while calling https url from HttpWebRequest.(.Net core 3.1 and OpenSSL 1.1.1f and Ubuntu 20.04)

### ISSUE THREAD

**Issue by natataju** [dotnet/runtime#51161]
Hi! please help me.

With the following code able to get the response from https url in Windows environment .
In Ubuntu environment getting error "The SSL connection could not be established, see inner exception. Authentication failed, see inner exception. "

Ubuntu Environment Details
Ubuntu20.04
.net core 3.1
OpenSSl 1.1.1f

```c#
try
{
    ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12 ;
    Uri url = new Uri("https://*******.aspx");
    HttpWebRequest http = (HttpWebRequest)WebRequest.Create(url.ToString());
    HttpWebResponse resp = (HttpWebResponse)http.GetResponse();
    var returnValue = Convert.ToInt32(resp.StatusCode);
    Console.WriteLine(returnValue);  
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}
```

**Comment by wfurt** [comment]
ServicePointManager is obsolete and does not do really much on .NET Core. You should use [ServerCertificateValidationCallback](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.servercertificatevalidationcallback?view=netcore-3.1) or make the certificate trusted by your OS.

**Comment by ManickaP** [comment]
Triage: seems like answered.
