### ISSUE TITLE
IAsyncEnumerator<T>.DisposeAsync() throws NotSupportedException

### ISSUE THREAD

**Issue by ldematte** [dotnet/runtime#51176]
Not sure if this should be asked here or to the roslyn guys.
I am debugging some complex async code, and under some corner case (two enumerators, the first one throws - but it is more complicated than that) a call to DisposeAsync throws. 
The debugger does not help me (the exception seems to be originated directly at the call site); I tried to cook up a simpler use but to no avail (in other words: I cannot reproduce it with a simple repro) 

I am willing to dig it deeper, but before I waste too much time on this: is this a known corner case? I.e., does the async state machine classes/generated code throws this exception under known cases?
Thanks!

**Comment by HaloFour** [comment]
Looking at the disassembly of the async enumerator state machine it will throw `NotSupportedException` depending on the current state of the enumerator.  If I'm interpreting the disassembly correctly it seems that this will happen if there is a previous call to `MoveNextAsync()` and the returned `ValueTask<bool>` has not yet completed.  I am able to reproduce the exception with the following code:

```cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp9
{
    class Program
    {
        static async IAsyncEnumerable<int> M()
        {
            await Task.Delay(1000);
            yield return 1;
        }

        static async Task Main(string[] args)
        {
            var enumerable = M();
            var enumerator = enumerable.GetAsyncEnumerator();
            var task = enumerator.MoveNextAsync();
            await Task.Delay(10); // change this to >1000 and the exception will no longer be thrown
            enumerator.DisposeAsync();
        }
    }
}

```

**Comment by ldematte** [comment]
That's it! I call `MoveNextAsync` on both enumerators, the first one throws trying to complete, the second does not complete and `DisposeAsync` throws. I guess we can say it is "by design", but on the other hand I kind of expect `Dispose` not to throw (typical usage is in a finally block). But I can live with that knowing why.
Out of curiosity, how did you look at the IL of the state machine? I have tried dotPeek but it is "too clever", and ILasm (which is instead too clumsy).

**Comment by HaloFour** [comment]
I used [SharpLab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQAwAIpwCwG5lqZwCs+SBAzJjOgMLoDey6LmVWAbJgBzoCSAQQDOATwB2AYwCiYgK4BbAKYAnAIYAjADaKAPAEsxAFwB86ALIAKAJSNmre1ACcmDgDoAmnsWbg1svYc4OEwAdnQ4fwCWLGCoMJhIqJjQ9ApE9ABfOxZsoi4oXiguM1UDa1skKJYAN1VldAAPdABecz9ch2cLC0FRSQARPSEABwB7IQ1tKwarV0GR8cVhcQl2ytYspAygA==)

**Comment by stephentoub** [comment]
Closing as answered. Thanks.
