### ISSUE TITLE
.NET Apache Airflow equivalent

### ISSUE THREAD

**Issue by DMiradakis** [dotnet/runtime#51178]
Transferred from `dotnet/docs` by @IEvangelist per recommendation from @spboyer

---

Microsoft Team,

I’ll have to apologize to you ahead of time because this issue doesn’t indicate something is wrong with the doc itself, but I don’t know where else to go to ask someone at Microsoft this.

I am utterly fascinated with the technology behind Apache Airflow and Prefect - both automated scheduling/ETL platforms for Python.

.NET seems pretty incredible to me, and you guys have the TPL Dataflows, Signal R, and ASP.NET Core. I can TOTALLY see you guys launching a .NET competitor that wraps all of these up into some kind of automation/ETL platform just like Apache Airflow or Prefect. We just need them all combined into some kind of beautiful visualization and dashboarding platform, with something like Log4Net for logging capabilities.

I would so be down for checking out a tool like that, if only one existed.

Do you guys have any future plans for this library? Like big plans, such as what I mentioned? I’d love to check out any GitHub repos or anything else you have, but I don’t know where to go and not many people seem to even know about it.

Thanks!

-Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0290c0b7-088f-5b42-4803-6d00eec086c0
* Version Independent ID: dbd55321-1f94-2141-7e33-8e046fdfa48f
* Content: [Dataflow (Task Parallel Library)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library)
* Content Source: [docs/standard/parallel-programming/dataflow-task-parallel-library.md](https://github.com/dotnet/docs/blob/main/docs/standard/parallel-programming/dataflow-task-parallel-library.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by joperezr** [comment]
cc: @richlander @terrajobst do you guys have any comments here?

**Comment by terrajobst** [comment]
@eerhardt might

**Comment by eerhardt** [comment]
Unfortunately, this is the first I'm hearing about Apache Airflow. But it sounds interesting.

**Comment by danielleiszen** [comment]
[Sorry about posting here. I know its off topic and sure its not the responsibility of the dotnet team to develop these things, but I could not find a better topic for my comment]

Apache Airflow is available on the Azure platform for more than 2 yrs now. So it sounds MS supports this technology in some way. However I am quite shocked not finding any .NET client for it. Is there any known roadmap porting the existing official Python client to .NET? Thx

**Comment by DMiradakis** [comment]
Thanks everyone for the feedback! I'll be exploring this more on my own.
