### ISSUE TITLE
Issue on Win7 with Vectors

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#51206]
We have a test that effectively does a string comparison with a string and a ReadOnlySpan<byte>. It first checks that they are equal, then sets a byte in the span to a different value and checks they aren't equal, then sets the byte back and checks if they are equal again. However, sometimes (on Win7 only) the comparison doesn't come back as equal when the byte is set back.

The code is heavily optimized and relies on Vector and Unsafe.ReadUnaligned, etc, so it is possible we are doing something wrong, but this code has been around for a couple years and we haven't seen a failure on other OS's.

I've created a small app to hopefully making hitting the issue easier:
https://github.com/BrennanConroy/win7_repro

Everytime I've seen the issue, it's been at this check https://github.com/BrennanConroy/win7_repro/blob/840404e8fcf74ce1e6bc63eb1eeff5d277a72850/Methods.cs#L253-L266

Some interesting discussion about this issue at https://github.com/dotnet/aspnetcore/pull/31565#issuecomment-816582534

Flaky test issue: https://github.com/dotnet/aspnetcore/issues/31500

**Comment by briansull** [comment]
It sounds like you are saying that this test case fails intermittently but (only on Windows 7)

It is possible that Windows 7 doesn't properly support the AVX save/restore of YMM registers.

The method bool DoesOSSupportAVX() in codeman.cpp could be investigated.

**Comment by JulieLeeMSFT** [comment]
@BrennanConroy have you tried @briansull's suggestion?

**Comment by BrennanConroy** [comment]
What suggestion?

**Comment by JulieLeeMSFT** [comment]
> What suggestion?

"The method bool DoesOSSupportAVX() in codeman.cpp could be investigated." 

What is the priority of this issue? It is not likely to be looked into in .NET 6 timeframe. Is it ok to move to .NET 7?

**Comment by benaadams** [comment]
> > What suggestion?
> 
> "The method bool DoesOSSupportAVX() in codeman.cpp could be investigated."

That's in the Jit code?

> What is the priority of this issue? 

The http parser in Kestrel considers header values where only half of the vector256 is the same as equal as its only comparing the first 16 bytes rather than 32 bytes for this platform.

Assuming the intrinsics and their supported checks are working properly; then it may be the fallback `Vector<short>` paths presenting as `Vector<byte>.Count == 32` but then operating as `Vector<byte>.Count == 16`

**Comment by BrennanConroy** [comment]
> What is the priority of this issue?

In Kestrel we fallback to a slower code path so the issue isn't a huge concern in this specific case. The main concern is that this could break other code that doesn't have a fallback.

> The method bool DoesOSSupportAVX() in codeman.cpp could be investigated.

I have no experience diagnosing native code in Runtime and I don't think this issue is a good starting point.

**Comment by JulieLeeMSFT** [comment]
@BruceForstall @echesakov PTAL. CC @dotnet/jit-contrib. 

Given that this happens only on Win7, I will likely move this to .NET 7 after some more discussion.

**Comment by BruceForstall** [comment]
It's hard to imagine how this could be a JIT issue if it happens on only one version of Windows. If it's a context saving thing, it would be a VM issue.

Are tests running on the same hardware but a different OS (e.g., Win10) and NOT failing on the non-Win7 OS?

@VSadov @mangod9 Based on https://github.com/dotnet/runtime/pull/47212, maybe you should look

**Comment by VSadov** [comment]
Windows7 supports AVX as of SP1. I assume this is on Windows7 SP1?

**Comment by BrennanConroy** [comment]
> Are tests running on the same hardware but a different OS (e.g., Win10) and NOT failing on the non-Win7 OS?

I don't know about hardware, but different OS's yes. Would have to ask Core-Eng folks about the hardware.

> I assume this is on Windows7 SP1?

Yes, 6.1.7601 which is Win7 SP1

**Comment by mangod9** [comment]
given this is win7 only moving to .net 7. If this is blocking a core scenario we could investigate sooner.

**Comment by AaronRobinsonMSFT** [comment]
Win 7 is going out of support mid .NET 7, so this feature has less value and is unlikely to be addressed.

See https://github.com/dotnet/core/issues/7556
