### ISSUE TITLE
.net 5 runtime backward compatibility

### ISSUE THREAD

**Issue by blackchoey** [dotnet/runtime#51218]
Hello,
Can you share whether .NET 5 runtime is compatible with binary built for previous .NET Core versions?

My current situation is:
I have built a binary for ASP.NET Core 3.1 web app, now I need to run this web app on a machine with only .NET 5 installed.
I did a rough test, the web app can start and function well. But I'm not sure whether it's 100% fine to do so, or I will meet errors in some corner cases.

It would be great if there's a document explaining the backward compatibility.

**Comment by CoffeeFlux** [comment]
It is possible your app will run fine, but there are breaking changes across major versions and so it's also possible your app could hit one of them and not function correctly. In general, it is advisable to build and run with the same version, and we assume that when going from .NET Core 3 to .NET 5, apps will be recompiled. cc: @danmoseley in case I missed anything

**Comment by huoyaoyuan** [comment]
You can see breaking changes listed at https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0 
Generally, the .NET BCL keeps binary compatibility. There may be minor behavior changes or new exceptions, but the code should be executable. Feature removal will result in `PlatformNotSupportedException`.
However, application frameworks may drop certain members, make the code not loadable.

**Comment by jeffschwMSFT** [comment]
Thank you @huoyaoyuan for sharing the breaking change list.   @blackchoey let us know if you have more questions, for now I am going to close this issue.
