### ISSUE TITLE
Intended proper use of HttpClient

### ISSUE THREAD

**Issue by wet-certitude** [dotnet/runtime#51214]
According to the documentation "HttpClient is intended to be instantiated once and re-used throughout the life of an application". However, the documentation also states that the "The HttpClient class instance acts as a session", thus e.g. cookies are (by default) shared for all requests.

My question is: What is the correct way to use the `HttpClient` if an application needs to conduct HTTP requests on behalf of multiple users and avoid any interaction between these HTTP communications (cookies, potentials issues arising from re-using TCP connections etc.):

1. Use a single instance and set `HttpClientHandler.UseCookies` to false. In this case, are there other configurations required to completely separate request?
2. Use short-lived `HttpClient`s. In this case, what is the proper way to combat the issue with open socket exhaustion?

**Comment by wfurt** [comment]
The ` re-used` should be as much as possible - using example one is not absolute rule. Mixing users is always tricky and you can consider use one HttpClient per user. That would typically result in reasonable behavior unless you have thousands of users you are trying to multiplex.

**Comment by davidfowl** [comment]
That model is broken when you need different settings per user/tenant/backend. The HttpClient is intrinsically tied to the handler. For very simple cases where those constraints don't exist, it's fine to use a single static instance. The moment you need to configure handler settings it gets more complex. 

@wet-certitude in .NET Core/5 etc the HttpClient instance will share both the handler settings and underlying connections. The moment you have more than once HttpClient, the usage of concurrent sockets and throttling those are in your hands. For a contrived example, say you were making calls to the same backend with different handler settings based on the incoming user:

User1 -> HttpClient1 -> Backend
User2 -> HttpClient2 -> Backend

The connections across HttpClient1 and HttpClient2 aren't shared, so if you wanted to limit concurrency in some to the same backend, it would be your job to do so.

**Comment by davidfowl** [comment]
I should say, there are more advanced ways to manage handler to enable the scenario above to share the root handler. For example:


User1 -> HttpClient1 -> HttpHandler1 -> SocketsHttpHandler (shared) -> Backend
User2 -> HttpClient2 -> HttpHandler1 -> SocketsHttpHandler (shared) -> Backend

This would allow you to use different handler settings but share the root handler that manages connections.

**Comment by wet-certitude** [comment]
Thanks for your responses, I think it's clearer to me now.

To clarify, we do not need multiple different settings per user/tenant/backend, but we need to separate the clients (e.g. cookie stores) between users. A scenario would be request that are made to an external web application (think Github). Cookies that may be set during one user's call should not be available for another user's call to avoid mixing up user sessions.

Our initial approach was to create a HttpClient per request. This would create a lot of instances. We found that this approach is suboptimal as it exhausts available sockets (see https://www.aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/). The alternative was setting `HttpClientHanlder.UseCookies` to false to disallow cookies altogether.

My takeaway is that individual `HttpClient`s is the best approach; the socket limits in the OS should be adapted if neccesary. Does for our scenario sharing a `SocketHttpHandler` guarantee that there is not interference between calls/users/sessions?

**Comment by davidfowl** [comment]
If you don't have any requirements that result in configuring multiple handlers then you should use a single one with UseCookies set to false

**Comment by ManickaP** [comment]
Triage: seems like it's answered. Feel free to reopen if you have more questions.
