### ISSUE TITLE
Linux build: The dependency target "inject_debug_resources_coreclr" of target "runtimeinfo" does not exist.   

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#51248]
Sometime recently, I've become unable to build dotnet/runtime on Linux Ubuntu 20.04.2 LTS.

Steps:

1. `git pull` (HEAD is now b80ddefa8db351f4ed697a686d8b6ba1dd927c52)
2. `git clean -xdf` (just for good measure)
3. `./build.sh -s clr+libs -rc release`

Result:

<pre>
  -- Configuring done
  CMake Error at debug/runtimeinfo/CMakeLists.txt:34 (add_dependencies):
    The dependency target "inject_debug_resources_coreclr" of target
    "runtimeinfo" does not exist.
  
  
  -- Generating done
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  /code/personal/dotnet/runtime/src/coreclr
</pre>

I don't think anything in particular changed in my environment, and nor do I see any other error higher up in the build logs. I tried a branch that is a few weeks old and was able to build it successfully.

Any assistance getting the build working again would be appreciated.

**Comment by vcsjones** [comment]
I did a git bisect and it seems that the follow commit is what broke it for me:

> 8c2158f9fe12c82cd3c0a7f4150773654bc78aaf is the first bad commit
commit 8c2158f9fe12c82cd3c0a7f4150773654bc78aaf
Author: Jeremy Koritzinsky &lt;stripped@example.com>
Date:   Mon Apr 5 09:28:04 2021 -0700

    Make Ninja the default CMake generator on Windows for the repo (#49715)


@jkoritzinsky would you have any idea why your change might have caused me to start running in to this issue?

**Comment by jkoritzinsky** [comment]
Are you trying to cross build or are you doing a non-cross build?

**Comment by vcsjones** [comment]
@jkoritzinsky not a cross build, just `./build.sh -s clr+libs -rc release`

**Comment by jkoritzinsky** [comment]
I think I found the issue. Not sure how this didnt break earlier. I'll have a fix out soon.
