### ISSUE TITLE
[wasm][tests] Tracking issue for test failures with AOT

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51251]
This is for tracking test failures when running with AOT.

- The main PR for this work is https://github.com/dotnet/runtime/pull/48226
- And a follow up PR (https://github.com/dotnet/runtime/pull/50885) has various fixes for the EAT issues
  - this adds a build for EAT (and AOT) under `runtime-staging`

- These tests are built with `/p:RunAOTCompilation=true /p:EnableAggressiveTrimming=true` (AOT+EAT)
  - the EAT part can introduce issues, compared to a regular test build
  - But all those are either disabled, or fixed in the [second PR](https://github.com/dotnet/runtime/pull/50885)
  
- With the issues for just EAT, fixed, the AOT build should have only the AOT test failures
- the issues are labeled [wasm-aot-test](https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+label%3Awasm-aot-test)

## To reproduce locally:

1. use the branch from the [second PR](https://github.com/dotnet/runtime/pull/50885)
2. `$ /dotnet.sh build /p:Configuration=Release /p:TargetOS=Browser /p:TargetArchitecture=wasm /t:Test /path/to/project/file /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true`
3. If you are not able to reproduce it with the above, then try building with `/p:BuildAOTTestsOnHelix=true` to the above command line
4. If you still cannot reproduce, then ask on the discord channel, as it might be a helix issue

## tips:

* make sure to assign the issue to yourself, if you are working on it
* You can add `/p:DebuggerSupport=true` to get line numbers
* Add `/p:WasmNativeDebugSymbols=true /p:WasmNativeStrip=false` for better traces
* You can try `/p:_WasmDevel=true` for improving the build times (a bit)
* It can be useful to run the tests in a browser. For that:
	* `WasmXHarnessArgs="--no-headless --no-quit" Scenario=WasmTestOnBrowser` - this will launch chrome in "headed" mode, and it won't quit after the tests are done
	* And adding `WasmXHarnessMonoArgs="--runtime-arg=--trace=E"` - will get you extra traces, but with v8 you will only see Native stacktrace (mono_llvm_cpp_throw_exception), but in the browser's js console, you can see the full trace for that

|Name|Issue|crash/build-error|
|----|-----|-----|
|System.IO.Pipelines|https://github.com/dotnet/runtime/issues/50959|n|
|System.Runtime.Extensions.Tests|https://github.com/dotnet/runtime/issues/51676|n|
|System.Runtime.Serialization.Xml.ReflectionOnly.Tests|https://github.com/dotnet/runtime/issues/51679|n|
|System.Runtime.Tests|https://github.com/dotnet/runtime/issues/52393|n|
|System.Text.Json.Tests|https://github.com/dotnet/runtime/issues/51961|y|

## Tests that were failing till very recently
|Name|Issue|crash/build-error|
|----|-----|-----|
|System.Reflection.Tests|https://github.com/dotnet/runtime/issues/51673|n|
|System.Runtime.Loader.DefaultContext.Tests|https://github.com/dotnet/runtime/issues/51680|y|
|System.Runtime.Loader.Tests|https://github.com/dotnet/runtime/issues/51678|n|
|System.Text.Encodings.Web.Tests|https://github.com/dotnet/runtime/issues/50965|y|
|System.CodeDom.Tests|https://github.com/dotnet/runtime/issues/51723|y|

(not an exhaustive list. See label `wasm-aot-test` for all the issues)

**Comment by radical** [comment]
cc @steveisok @mdh1418 @vargaz @SamMonoRT @naricc

**Comment by SamMonoRT** [comment]
cc @fanyang-mono

**Comment by SamMonoRT** [comment]
@radical @lewing - any more work left for this tracking issue ?

**Comment by radical** [comment]
This can be closed now, as the original work is done.
