### ISSUE TITLE
dotnet publish single file and build signing

### ISSUE THREAD

**Issue by himanshu-sha** [dotnet/runtime#51252]
We have a project that we publish as single file executable. Here are steps we follow:

1. Call msbuild to build the solution
2. Sign all files in the output folder
3. Call dotnet publish : dotnet publish "path to csproj file" -r win-x64 /p:PublishSingleFile=true /p:IncludeAllContentForSelfExtract=true -c Release
4. Sign the published single executable file

When we run the single file executable, the temp files that were extracted contains unsigned files even though we sign them in step 2. How do we make sure that every file contained within the published single executable is signed?

**Comment by vitek-karas** [comment]
Unfortunately the output folder content is not used as input to publish (instead the files in intermediates `obj` are used for that), so modifying files in output will have no effect on publish.

We're introducing an extension point in the SDK for operations like signing files in single-file [Design](https://github.com/dotnet/designs/blob/main/accepted/2021/before_bundle_build_hook.md), [PR](https://github.com/dotnet/sdk/pull/18794).

**Comment by agocke** [comment]
Closed by https://github.com/dotnet/sdk/pull/18794
