### ISSUE TITLE
Dump generation not working for signals on macOS

### ISSUE THREAD

**Issue by kdubau** [dotnet/runtime#51268]
Dumps aren't being generated for signals on macOS.

Both `COMPlus_DbgEnableMiniDump=1` and `COMPlus_DbgEnableElfDumpOnMacOS=1` are exported correctly and dumps generated when an exception is unhandled.

But if I trigger a SigSegv from code there isn't any dump.

Code:
```csharp
class Program
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void callback();

    static void Main(string[] args)
    {
        _ = Marshal.GetDelegateForFunctionPointer((IntPtr)123, typeof(callback));
    }
}
```
Output:
> local@local ~/Projects/TestNET5dumps $ dotnet TestNET5dumps/bin/Debug/net5.0/TestNET5dumps.dll
> Segmentation fault: 11

We've also tried sending signals using the `kill` command (i.e., `kill -11 <pid>`) which also doesn't trigger any generation. 

Just for due diligence, we tested these things on Linux as well, and it all works as expected there. That is, the SigSegv from code and external signals from `kill` all trigger dump generation on Linux.

**Comment by mikem8361** [comment]
FYI: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/3616/Signal-Investigation?anchor=coreclr

**Comment by kdubau** [comment]
A SigAbrt from code also doesn't trigger generation.
```csharp
class Program
{
    [DllImport("libc")]
    static extern void abort();

    static void Main(string[] args)
    {
        abort();
    }
}

**Comment by mikem8361** [comment]
I'm not sure if we can support (or it may be difficult to suppress the recursion) catching abort()/SIGABORT because that what the managed unhandled exceptions do after writing the core dump in the PAL.

**Comment by kdubau** [comment]
Here's a look at what signals VSMac has seen with Mono in the last 90 days.
| Signal | Watson Hits |
| --- | --- |
term |	138,819
segv	 |20,275
abrt	|4,061
bus	|13

`SIGTERM` is what is sent by the OS when a user "Force Quits" the process (from activity monitor or Apple menu). This is usually because of a process hang or performance issues preventing a normal quit.

In terms or priority, we can probably live without `SIGBUS` given the low hits. But I think we definitely need the other three listed there, at least.

**Comment by mikem8361** [comment]
By default on both Linux and MacOS SIGTERM doesn't generate a coredump; it terminates the process silently.  So Mono does generate the crash json when a SIGTERM is sent?  For .NET Core, I would have to add another env var to enable core dump generation specifically for SIGTERM to maintain compatibility. Does that sound reasonable?

**Comment by kdubau** [comment]
@mikem8361 yes that sounds reasonable!

**Comment by mikem8361** [comment]
COMPlus_EnableDumpOnSigTerm is the env var for SIGTERM.
