### ISSUE TITLE
System.net.mail.SmtpClient fails to send mail from server having NTLM authentication 

### ISSUE THREAD

**Issue by ukashanoor** [dotnet/runtime#51260]
.Net Core version: 3.1
Server: Linux(Ubuntu 18.04 LTS)

**Issue**

Our use case is to send Email to customers using SMTP server. This SMTP server is configured with NTLM as authentication mechanism. When we make use of default "System.net.mail.SmtpClient" package in .NetCore, it fails to even create a successful connection.
And hence the email sending fails on the Linux server with .NetCore build.

**Code snippet**

We tried the following code snippet to send mail:

```c#
SmtpClient client = new SmtpClient();
client.Port = smtp.Port;
client.UseDefaultCredentials = false;
client.DeliveryMethod = SmtpDeliveryMethod.Network;
client.Credentials = new NetworkCredential(smtp.Login, smtp.Password);
client.Host = smtp.Server;
client.EnableSsl = smtp.EnableSSL;
mail.Body = builder.ToString();
client.Send(mail);
```

**Error**

"GSSAPI operation failed with error - An unsupported mechanism was requested. NTLM authentication requires the GSSAPI plugin 'gss-ntlmssp'.
So we installed the package 'gss-ntlmssp' on our linux server where the build is running but it still gives the error.

**Latest Error**

System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - An invalid name was supplied (Name is empty).

Can someone please suggest the correct fix for this issue or any work around for this problem?

**Comment by wfurt** [comment]
can you verify that smtp.Login and smtp.Password is not empty? And yes, the `gss-ntlmssp` provider is needed as the system does not have NTLM provider by default.

**Comment by ukashanoor** [comment]
smtp.Login and smtp.Password are not empty. We installed 'gss-ntlmssp' provider but we started facing another issue - **"System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - An invalid name was supplied (Name is empty)."**

**Comment by wfurt** [comment]
I have no more easy suggestions @ukashanoor. The next step would be providing simplified app and possibly test server. (dos not need to really authenticate). This issue is really not actionable at the moment.
Alternatively you can consider alternative MA like [MailKit](https://github.com/jstedfast/MailKit).

**Comment by ManickaP** [comment]
Triage: this is not actionable at the moment. Waiting for more info.

**Comment by karelz** [comment]
No reply in 4 months, closing.
