### ISSUE TITLE
Missing v2.1.27-dependencies tags on core-setup, core-fx and core-clr

### ISSUE THREAD

**Issue by klementi** [dotnet/runtime#51278]
It seems that .net core v2.1.27 [release](https://devblogs.microsoft.com/dotnet/net-core-april-2021-updates/)
is missing v2.1.27-dependencies tags on core-setup, core-fx and core-clr repositories

[core-setup](https://github.com/dotnet/core-setup/tags)
[core-fx](https://github.com/dotnet/corefx/tags)
[core-clr](https://github.com/dotnet/coreclr/tags)

Can you, please, add them?

**Comment by klementi** [comment]
We had the same problem with every release so far, can you include that into your runbooks going forward?

**Comment by rbhanda** [comment]
@aik-jahoda

**Comment by klementi** [comment]
I can see you added v2.1.27-dependencies tags for core-setup and core-fx, however core-clr tags (https://github.com/dotnet/coreclr/tags)[https://github.com/dotnet/coreclr/tags] are still missing

**Comment by ViktorHofer** [comment]
Closing as tags are now added.
