### ISSUE TITLE
System.Net.NetworkInformation needs Android PAL

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#51303]
Currently, System.Net.NetworkInformation implementation on Android falls back to Linux PAL. This needs to change because starting from API 24 Android restricts access to many files in the /sys filesystem which makes the API unsupported.

Right now the APIs fail with System.UnauthorizedAccessException. We need to write an Android-specific PAL layer that uses Java APIs via JNI to access the information to not break developers migrating from existing Mono based BCL.

/cc @steveisok

**Comment by filipnavara** [comment]
For reference, the Xamarin.Android implementation of the code resides [here](https://github.com/xamarin/xamarin-android/blob/main/src/monodroid/jni/xamarin_getifaddrs.cc). Mono used to call it through several indirections.

**Comment by wfurt** [comment]
It would be good to get list of failing methods & properties @marek-safar. I made changes in the past to linked GetAllNetworkInterfaces() do depend less on  /proc & /sys. It certainly feels better to throw PNSP or have alternative implementation than getting access violation. I would be curious to see how big that difference is.

**Comment by marek-safar** [comment]
@wfurt see #50567

**Comment by wfurt** [comment]
That list does not give the list of files @marek-safar. But it seems to be mostly stats.

**Comment by marek-safar** [comment]
@wfurt perhaps I misunderstood the ask, what are you looking for exactly?

**Comment by wfurt** [comment]
That is ok. I was primarily wondering how much code we will need to replace. Number of test is somewhat approximation. If there are only few functions we may simply add alternatives instead of doing whole new pal. there is already some precedent for that.
