### ISSUE TITLE
Blazor Wasm - Size regression in System.Text.Json.dll 

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#51311]
System.Text.Json.dll.br has a big spike in last two days as observed in https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0

![image](https://user-images.githubusercontent.com/46026722/114878987-c9d5fc00-9dce-11eb-9be9-ff125ffc80bf.png)

@eerhardt @CoffeeFlux

**Comment by eerhardt** [comment]
@eerhardt suggested that these 2 changes are possible offenders

#50778
#51025

@layomia @steveharter @eiriktsarpalis

**Comment by layomia** [comment]
These two changes are primarily `JsonConverter`-based features and are very likely to have caused the regression.

The JSON source generator will help reduce size for apps that use the new overloads that take pre-generated metadata (https://github.com/dotnet/runtime/pull/51300). The converters for these features will be trimmed out if not needed in an app, and if the [new](https://github.com/dotnet/runtime/issues/45448#issue-754827678) serializer methods are used instead of the [existing ones](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=net-5.0).

I don't expect the size regression here to be reversed until the JSON serialization logic within Blazor assemblies is refactored to use the new serializer methods. See  these [commits](https://github.com/eerhardt/aspnetcore/commits/json-tmp) for an early attempt. Happy to help with this effort.

**Comment by SamMonoRT** [comment]
Thanks @layomia  - do we know if there is any tracking issue for the refactoring work ?

**Comment by SamMonoRT** [comment]
cc @mkArtakMSFT - is this on your team ?

**Comment by SamMonoRT** [comment]
Want to put this note out, to make it very clear - We don't expect to backport any changes from dotnet/aspnetcore#31877 to be backported to Preview 4. But we need to make sure the necessary work has a timeline to make it in quickly.

**Comment by steveharter** [comment]
One potential path to reduce size as new features (and converters) are added is to initialize `JsonSerializerOptions` with no converters and then add only the converters necessary for the given application and scenarios. @layomia recently added the source-gen \ trimming work that does this but it could be extended and used without source-gen:
```cs
JsonSerializerOptions options = new JsonSerializerOptions;
options.Converters.Add(JsonConverters.String);
options.Converters.Add(JsonConverters.Int32);
options.Converters.Add(JsonConverters.JsonNode);
// etc

JsonNode node = ...
JsonSerializer.Serialize(node , options);

// or other variants:

// With JsonSerializerContext
JsonSerializerContext context = ... // must be initialized with converters like above
JsonSerializer.Serialize(node, context);

// Pass the converter directly
JsonSerializer.Serialize(node, JsonConverters.JsonNode, options);

// With the metadata type that also avoids a lookup
JsonTypeInfo<JsonNode> jsonNodeTypeinfo = ...
JsonSerializer.Serialize(node, jsonNodeTypeinfo);
```

**Comment by SamMonoRT** [comment]
Assigning to @layomia for tracking based on additional work building over the JSON SourceGenerator work

**Comment by layomia** [comment]
Following up on offline discussions on email, I'm noting on this issue that the path to reducing the regression here will not be about Blazor fully adopting the JSON source generator internally and in the default template (https://github.com/dotnet/aspnetcore/issues/31877). Size is important for Blazor, but it was discussed that the generator should focus on trim safety (already supported), and improve (de)serialization throughput (in progress with https://github.com/dotnet/runtime/issues/51945).

For mitigating the size regression here, this issue will instead focus on internal System.Text.Json changes to reduce the assembly size when source gen is not used:

- [ ] Possible linker removal JsonNode (+ ancillary classes) https://github.com/dotnet/runtime/issues/51756
- [ ] Evaluate existing converters for uncommonly-used collections using late-bound references to reduce assembly dependency size
- [ ] Consider linker switch to trim out ref emit code and always use normal reflection instead (https://github.com/dotnet/runtime/issues/38693). We've estimated ~16K compressed savings with this approach.

cc @SamMonoRT @CoffeeFlux @eerhardt @steveharter @ericstj @SteveSandersonMS @pranavkm @jkotas

**Comment by lewing** [comment]
Is there any remaining .NET6 work here?

**Comment by layomia** [comment]
I believe there's no work left here for 6.0 given the above plan https://github.com/dotnet/runtime/issues/51311#issuecomment-842386665. cc @eerhardt

**Comment by eiriktsarpalis** [comment]
I think we can close this issue now?
