### ISSUE TITLE
System.Xml.Xsl.XslTransformApi.Tests Fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51333]
All are failing with `System.TypeInitializationException : The type initializer for 'System.Xml.Tests.XsltApiTestCaseBase' threw an exception.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/26E60B80-C050-4C36-8BD2-D6C2F09F0F06/data/Containers/Bundle/Application/145C1627-64C5-4A0C-9116-AFA8B3565163/System.Xml.Xsl.XslTransformApi.Tests.app/TestFiles/TestData/XsltApi/xmlResolver_document_function_absolute_uri.xsl'.`

System.Xml.Xsl.XslTransformApi.Tests
System.Xml.Tests.CArgIntegrity.GetParam4
System.Xml.Tests.CArgIntegrity.GetParam10
System.Xml.Tests.CArgIntegrity.GetParam7
System.Xml.Tests.CArgIntegrity.var_types
System.Xml.Tests.CArgIntegrity.GetParam16
System.Xml.Tests.CArgIntegrity.GetParam1
System.Xml.Tests.CArgIntegrity.GetParam8
System.Xml.Tests.CArgIntegrity.GetParam12
System.Xml.Tests.CArgIntegrity.GetParam14
System.Xml.Tests.CArgIntegrity.GetParam15
System.Xml.Tests.CArgIntegrity.GetParam3
System.Xml.Tests.CArgIntegrity.GetParam2
System.Xml.Tests.CArgIntegrity.GetParamDoubles
System.Xml.Tests.CArgIntegrity.GetParam9
System.Xml.Tests.CArgIntegrity.GetParam17
System.Xml.Tests.CArgIntegrity.GetParam18
System.Xml.Tests.CArgIntegrity.GetParam5
System.Xml.Tests.CArgIntegrity.GetParam19
System.Xml.Tests.CArgIntegrity.GetParam13
System.Xml.Tests.CArgIntegrity.GetParam6
System.Xml.Tests.CArgAddParam.AddParam18
System.Xml.Tests.CArgAddParam.AddParam12
System.Xml.Tests.CArgAddParam.AddParam4
System.Xml.Tests.CArgAddParam.AddParam10
System.Xml.Tests.CArgAddParam.AddExtObject32
System.Xml.Tests.CArgAddParam.AddParam14
System.Xml.Tests.CArgAddParam.AddParam13
System.Xml.Tests.CArgAddParam.AddParam20
System.Xml.Tests.CArgAddParam.AddParam1
System.Xml.Tests.CArgAddParam.AddParam16
System.Xml.Tests.CArgAddParam.AddParam19
System.Xml.Tests.CArgAddParam.AddParam17
System.Xml.Tests.CArgAddParam.AddParam7
System.Xml.Tests.CArgAddParam.AddParam8
System.Xml.Tests.CArgAddParam.AddParam15
System.Xml.Tests.CArgAddParam.AddParam11
System.Xml.Tests.CArgAddParam.AddParam6
System.Xml.Tests.CArgAddParam.AddParam21
System.Xml.Tests.CArgAddParam.AddParam3
System.Xml.Tests.CArgAddParam.AddParam2
System.Xml.Tests.CArgAddParam.AddParam5
System.Xml.Tests.CArgAddParamMisc.AddParam1
System.Xml.Tests.CArgAddParamMisc.AddParam2
System.Xml.Tests.CArgAddParamMisc.AddParam3
System.Xml.Tests.CArgAddExtObj.AddExtObject28
System.Xml.Tests.CArgAddExtObj.AddExtObject11
System.Xml.Tests.CArgAddExtObj.AddExtObject8
System.Xml.Tests.CArgAddExtObj.AddExtObject20
System.Xml.Tests.CArgAddExtObj.AddExtObject24
System.Xml.Tests.CArgAddExtObj.AddExtObject17
System.Xml.Tests.CArgAddExtObj.AddExtObject14
System.Xml.Tests.CArgAddExtObj.AddExtObject4
System.Xml.Tests.CArgAddExtObj.AddExtObject27
System.Xml.Tests.CArgAddExtObj.AddExtObject6
System.Xml.Tests.CArgAddExtObj.AddExtObject29
System.Xml.Tests.CArgAddExtObj.AddExtObject12
System.Xml.Tests.CArgAddExtObj.AddExtObject19
System.Xml.Tests.CArgAddExtObj.AddExtObject18
System.Xml.Tests.CArgAddExtObj.AddExtObject10
System.Xml.Tests.CArgAddExtObj.AddExtObject26
System.Xml.Tests.CArgAddExtObj.AddExtObject32
System.Xml.Tests.CArgAddExtObj.AddExtObject3
System.Xml.Tests.CArgAddExtObj.AddExtObject15
System.Xml.Tests.CArgAddExtObj.TC_ExtensionObj_Function_Mismatch_IncorrectCasing
System.Xml.Tests.CArgAddExtObj.AddExtObject16
System.Xml.Tests.CArgAddExtObj.AddExtObject21
System.Xml.Tests.CArgAddExtObj.AddExtObject1
System.Xml.Tests.CArgAddExtObj.AddExtObject22
System.Xml.Tests.CArgAddExtObj.AddExtObject31
System.Xml.Tests.CArgAddExtObj.AddExtObject7
System.Xml.Tests.CArgAddExtObj.AddExtObject13
System.Xml.Tests.CArgAddExtObj.AddExtObject2
System.Xml.Tests.CArgAddExtObj.AddExtObject9
System.Xml.Tests.CArgRemoveParam.RemoveParam2
System.Xml.Tests.CArgRemoveParam.RemoveParam3
System.Xml.Tests.CArgRemoveParam.RemoveParam5
System.Xml.Tests.CArgRemoveParam.RemoveParam9
System.Xml.Tests.CArgRemoveParam.RemoveParam1
System.Xml.Tests.CArgRemoveParam.RemoveParam14
System.Xml.Tests.CArgRemoveParam.RemoveParam8
System.Xml.Tests.CArgRemoveParam.RemoveParam7
System.Xml.Tests.CArgRemoveParam.RemoveParam10
System.Xml.Tests.CArgRemoveParam.RemoveParam6
System.Xml.Tests.CArgRemoveParam.RemoveParam4
System.Xml.Tests.CArgRemoveParam.RemoveParam13
System.Xml.Tests.CArgRemoveParam.RemoveParam12
System.Xml.Tests.CArgRemoveParam.RemoveParam11
System.Xml.Tests.CArgRemoveParam.RemoveParam15
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj8
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj5
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj7
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj1
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj6
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj4
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj9
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj3
System.Xml.Tests.CArgRemoveExtObj.RemoveExtObj2
System.Xml.Tests.CArgClear.Clear4
System.Xml.Tests.CArgClear.Clear7
System.Xml.Tests.CArgClear.Clear5
System.Xml.Tests.CArgClear.Clear8
System.Xml.Tests.CArgClear.Clear2
System.Xml.Tests.CArgClear.Clear1
System.Xml.Tests.CArgClear.Clear6
System.Xml.Tests.CArgClear.Clear3
System.Xml.Tests.CSameInstanceXsltArgumentListGetParam.proc1
System.Xml.Tests.CSameInstanceXsltArgumentListGetParam.proc2
System.Xml.Tests.CSameInstanceXsltArgumentListGetExtnObject.proc2
System.Xml.Tests.CSameInstanceXsltArgumentListGetExtnObject.proc1
System.Xml.Tests.CSameInstanceXsltArgumentListTransform.proc1
System.Xml.Tests.CNullArgumentTest.Var7
System.Xml.Tests.CNullArgumentTest.Var6
System.Xml.Tests.CNullArgumentTest.Var8
System.Xml.Tests.CNullArgumentTest.Var14
System.Xml.Tests.CNullArgumentTest.Var2
System.Xml.Tests.CNullArgumentTest.Var9
System.Xml.Tests.CNullArgumentTest.Var3
System.Xml.Tests.CNullArgumentTest.Var1
System.Xml.Tests.CNullArgumentTest.Var4
System.Xml.Tests.CNullArgumentTest.Var11
System.Xml.Tests.CNullArgumentTest.Var12
System.Xml.Tests.CNullArgumentTest.Var13
System.Xml.Tests.CNullArgumentTest.Var10
System.Xml.Tests.CNullArgumentTest.Var5
System.Xml.Tests.CXmlResolverTest.XmlResolver2
System.Xml.Tests.CXmlResolverTest.TC_Xslt_Document_Function_Use_XmlUrlResolver
System.Xml.Tests.CXmlResolverTest.XmlResolver1
System.Xml.Tests.CXmlResolverTest.TC_AbsolutePath_Transform
System.Xml.Tests.CLoadTest.LoadGeneric7
System.Xml.Tests.CLoadTest.LoadGeneric5
System.Xml.Tests.CLoadTest.LoadGeneric2
System.Xml.Tests.CLoadTest.LoadGeneric9
System.Xml.Tests.CLoadTest.LoadGeneric6
System.Xml.Tests.CLoadTest.LoadGeneric3
System.Xml.Tests.CLoadTest.LoadGeneric11
System.Xml.Tests.CLoadTest.LoadGeneric4
System.Xml.Tests.CLoadTest.LoadGeneric12
System.Xml.Tests.CLoadTest.LoadGeneric1
System.Xml.Tests.CLoadTest.XslTransformThrowsPNSEWhenUsingScripts
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric3
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric2
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric9
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric12
System.Xml.Tests.CLoadXmlResolverTest.TC_Resolver_Null_Should_Not_Break_Transform
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric10
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric4
System.Xml.Tests.CLoadXmlResolverTest.TC_CustomNullResover_Then_XmlUrlResolver
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric11
System.Xml.Tests.CLoadXmlResolverTest.TC_No_Explicit_Resolver_Prohibits_External_Url
System.Xml.Tests.CLoadXmlResolverTest.LoadGeneric1
System.Xml.Tests.CLoadUrlResolverTest.LoadUrlResolver3
System.Xml.Tests.CLoadUrlResolverTest.LoadUrlResolver2
System.Xml.Tests.CLoadUrlResolverTest.LoadUrlResolver1
System.Xml.Tests.CLoadStringTest.LoadUrl1
System.Xml.Tests.CLoadStringTest.LoadUrl
System.Xml.Tests.CLoadStringTest.LoadUrl2
System.Xml.Tests.CLoadStringTest.LoadUrl3
System.Xml.Tests.CLoadXPathNavigableTest.LoadNavigator3
System.Xml.Tests.CLoadXPathNavigableTest.LoadNavigator1
System.Xml.Tests.CLoadXPathNavigableTest.LoadNavigator2
System.Xml.Tests.CLoadReaderTest.LoadXmlReader3
System.Xml.Tests.CLoadReaderTest.LoadXmlReader6
System.Xml.Tests.CLoadReaderTest.LoadXmlReader5
System.Xml.Tests.CLoadReaderTest.LoadXmlReader7
System.Xml.Tests.CLoadReaderTest.LoadXmlReader2
System.Xml.Tests.CLoadReaderTest.LoadXmlReader1
System.Xml.Tests.CLoadReaderTest.LoadXmlReader4
System.Xml.Tests.CTransformTestGeneric.TransformGeneric5
System.Xml.Tests.CTransformTestGeneric.TransformGeneric1
System.Xml.Tests.CTransformTestGeneric.TransformGeneric7
System.Xml.Tests.CTransformTestGeneric.TransformGeneric2
System.Xml.Tests.CTransformTestGeneric.TransformGeneric3
System.Xml.Tests.CTransformTestGeneric.TransformGeneric4
System.Xml.Tests.CTransformResolverTest.XmlResolver2
System.Xml.Tests.CTransformResolverTest.XmlResolver1
System.Xml.Tests.CTransformResolverTest.TC_AbsolutePath_Transform
System.Xml.Tests.CTransformResolverTest.TC_Xslt_Document_Function_Use_XmlUrlResolver
System.Xml.Tests.CTransformStrStrTest.TransformStrStr1
System.Xml.Tests.CTransformStrStrTest.TransformStrStr11
System.Xml.Tests.CTransformStrStrTest.TransformStrStr9
System.Xml.Tests.CTransformStrStrTest.TransformStrStr6
System.Xml.Tests.CTransformStrStrTest.TransformStrStr4
System.Xml.Tests.CTransformStrStrTest.TransformStrStr13
System.Xml.Tests.CTransformStrStrTest.TransformStrStr12
System.Xml.Tests.CTransformStrStrTest.TransformStrStr10
System.Xml.Tests.CTransformStrStrTest.TransformStrStr2
System.Xml.Tests.CTransformStrStrTest.TransformStrStr7
System.Xml.Tests.CTransformStrStrTest.TransformStrStr8
System.Xml.Tests.CTransformStrStrTest.TransformStrStr3
System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver1
System.Xml.Tests.CTransformStrStrResolverTest.TC_Xslt_Document_Function_Use_XmlUrlResolver
System.Xml.Tests.CTransformStrStrResolverTest.TransformStrStrResolver2
System.Xml.Tests.CNDP1_1SP1Test.var4
System.Xml.Tests.CNDP1_1SP1Test.TC_XPathNodeIterator_From_ExtensionObject
System.Xml.Tests.CNDP1_1SP1Test.var1
System.Xml.Tests.CNDP1_1SP1Test.var2
System.Xml.Tests.CSameInstanceXslTransformTestCase.Variations
System.Xml.Tests.SameInstanceXslTransformReader.Variations
System.Xml.Tests.SameInstanceXslTransformWriter.Variations

[System.Xml.Xsl.XslTransformApi.Tests.failures.log](https://github.com/dotnet/runtime/files/6320883/System.Xml.Xsl.XslTransformApi.Tests.failures.log)

**Comment by filipnavara** [comment]
Most, if not all, failures are caused by #52104.
