### ISSUE TITLE
System.Xml.XmlSchemaSet.Tests Fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51334]
System.Xml.XmlSchemaSet.Tests
System.Xml.Tests.TC_SchemaSet_Compile.v2
System.Xml.Tests.TC_SchemaSet_Schemas_ns.v2
System.Xml.Tests.TC_SchemaSet_Schemas_ns.v6
System.Xml.Tests.TC_SchemaSet_Schemas_ns.v4
System.Xml.Tests.TC_SchemaSet_Schemas_ns.v3
System.Xml.Tests.TC_SchemaSet_Schemas_ns.v5
System.Xml.Tests.TC_SchemaSet_IsCompiled.v3
System.Xml.Tests.TC_SchemaSet_IsCompiled.v2
System.Xml.Tests.TC_SchemaSet_Count.v2
System.Xml.Tests.TC_SchemaSet_Count.v3
System.Xml.Tests.TC_SchemaSet_GlobalTypes.v4
System.Xml.Tests.TC_SchemaSet_GlobalTypes.v5
System.Xml.Tests.TC_SchemaSet_Schemas.v3
System.Xml.Tests.TC_SchemaSet_Schemas.v2
System.Xml.Tests.TC_SchemaSet_Schemas.v4
System.Xml.Tests.TC_SchemaSet_Contains_Schema.v3
System.Xml.Tests.TC_SchemaSet_Contains_Schema.v4
System.Xml.Tests.TC_SchemaSet_Contains_Schema.v2
System.Xml.Tests.TC_SchemaSet_Includes.v107
System.Xml.Tests.TC_SchemaSet_Includes.v202
System.Xml.Tests.TC_SchemaSet_Includes.v1
System.Xml.Tests.TC_SchemaSet_Includes.v11
System.Xml.Tests.TC_SchemaSet_Includes.v102
System.Xml.Tests.TC_SchemaSet_Includes.v8
System.Xml.Tests.TC_SchemaSet_Includes.v201
System.Xml.Tests.TC_SchemaSet_Includes.v205
System.Xml.Tests.TC_SchemaSet_Includes.v9
System.Xml.Tests.TC_SchemaSet_Includes.v12
System.Xml.Tests.TC_SchemaSet_Includes.v101
System.Xml.Tests.TC_SchemaSet_Includes.v206
System.Xml.Tests.TC_SchemaSet_Includes.v207
System.Xml.Tests.TC_SchemaSet_Includes.v104
System.Xml.Tests.TC_SchemaSet_Includes.v204
System.Xml.Tests.TC_SchemaSet_Includes.v10
System.Xml.Tests.TC_SchemaSet_Includes.v105
System.Xml.Tests.TC_SchemaSet_Includes.v106
System.Xml.Tests.TC_SchemaSet_Includes.v203
System.Xml.Tests.TC_SchemaSet_Includes.v103
System.Xml.Tests.TC_SchemaSet_Includes.v2
System.Xml.Tests.TC_SchemaSet_CopyTo.v7
System.Xml.Tests.TC_SchemaSet_CopyTo.v6
System.Xml.Tests.TC_SchemaSet_CopyTo.v4
System.Xml.Tests.TC_SchemaSet_CopyTo.v5
System.Xml.Tests.TC_SchemaSet_CopyTo.v1
System.Xml.Tests.TC_SchemaSet_CopyTo.v2
System.Xml.Tests.TC_SchemaSet_CopyTo.v3
System.Xml.Tests.TC_SchemaSet_AllowXmlAttributes.v1
System.Xml.Tests.TC_SchemaSet_Remove.v4
System.Xml.Tests.TC_SchemaSet_Remove.v8
System.Xml.Tests.TC_SchemaSet_Remove.v10
System.Xml.Tests.TC_SchemaSet_Remove.v11
System.Xml.Tests.TC_SchemaSet_Remove.v5
System.Xml.Tests.TC_SchemaSet_Remove.v20
System.Xml.Tests.TC_SchemaSet_Remove.v6
System.Xml.Tests.TC_SchemaSet_Remove.v9
System.Xml.Tests.TC_SchemaSet_Remove.v3
System.Xml.Tests.TC_SchemaSet_Remove.v2
System.Xml.Tests.TC_SchemaSet_Remove.v7
System.Xml.Tests.TC_SchemaSet_Contains_ns.v4
System.Xml.Tests.TC_SchemaSet_Contains_ns.v3
System.Xml.Tests.TC_SchemaSet_Contains_ns.v2
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v22
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v10
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v20
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v3
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v1
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v2
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v14
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v23
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v11
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v8
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v13
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v7
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v21
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v12
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v15
System.Xml.Tests.TC_SchemaSet_ProhibitDTD.v4
System.Xml.Tests.TC_SchemaSet_Reprocess.v4
System.Xml.Tests.TC_SchemaSet_Reprocess.v51
System.Xml.Tests.TC_SchemaSet_Reprocess.v7
System.Xml.Tests.TC_SchemaSet_Reprocess.v9
System.Xml.Tests.TC_SchemaSet_Reprocess.v3
System.Xml.Tests.TC_SchemaSet_Reprocess.v11
System.Xml.Tests.TC_SchemaSet_Reprocess.v10
System.Xml.Tests.TC_SchemaSet_Reprocess.v5
System.Xml.Tests.TC_SchemaSet_Reprocess.v6
System.Xml.Tests.TC_SchemaSet_Reprocess.v12
System.Xml.Tests.TC_SchemaSet_Reprocess.v8
System.Xml.Tests.TC_SchemaSet_Reprocess.v2
System.Xml.Tests.TC_SchemaSet_Add_URL.v5
System.Xml.Tests.TC_SchemaSet_Add_URL.v9
System.Xml.Tests.TC_SchemaSet_Add_URL.v3
System.Xml.Tests.TC_SchemaSet_Add_URL.v11
System.Xml.Tests.TC_SchemaSet_Add_URL.v10
System.Xml.Tests.TC_SchemaSet_Add_URL.v6
System.Xml.Tests.TC_SchemaSet_Add_URL.v12
System.Xml.Tests.TC_SchemaSet_Add_URL.v13
System.Xml.Tests.TC_SchemaSet_Add_URL.v2
System.Xml.Tests.TC_SchemaSet_Add_URL.v8
System.Xml.Tests.TC_SchemaSet_Add_URL.v7
System.Xml.Tests.TC_SchemaSet_XmlResolver.v4
System.Xml.Tests.TC_SchemaSet_XmlResolver.v6
System.Xml.Tests.TC_SchemaSet_XmlResolver.v5
System.Xml.Tests.TC_SchemaSet_XmlResolver.v3
System.Xml.Tests.TC_SchemaSet_XmlResolver.v2
System.Xml.Tests.TC_SchemaSet_Imports.v117
System.Xml.Tests.TC_SchemaSet_Imports.v107
System.Xml.Tests.TC_SchemaSet_Imports.v106
System.Xml.Tests.TC_SchemaSet_Imports.v118
System.Xml.Tests.TC_SchemaSet_Imports.v113
System.Xml.Tests.TC_SchemaSet_Imports.v204
System.Xml.Tests.TC_SchemaSet_Imports.v206
System.Xml.Tests.TC_SchemaSet_Imports.v105
System.Xml.Tests.TC_SchemaSet_Imports.v120
System.Xml.Tests.TC_SchemaSet_Imports.v208
System.Xml.Tests.TC_SchemaSet_Imports.v21
System.Xml.Tests.TC_SchemaSet_Imports.v24
System.Xml.Tests.TC_SchemaSet_Imports.v219
System.Xml.Tests.TC_SchemaSet_Imports.v109
System.Xml.Tests.TC_SchemaSet_Imports.v8
System.Xml.Tests.TC_SchemaSet_Imports.v6
System.Xml.Tests.TC_SchemaSet_Imports.v214
System.Xml.Tests.TC_SchemaSet_Imports.v210
System.Xml.Tests.TC_SchemaSet_Imports.v13
System.Xml.Tests.TC_SchemaSet_Imports.v201
System.Xml.Tests.TC_SchemaSet_Imports.v217
System.Xml.Tests.TC_SchemaSet_Imports.v12
System.Xml.Tests.TC_SchemaSet_Imports.v203
System.Xml.Tests.TC_SchemaSet_Imports.v116
System.Xml.Tests.TC_SchemaSet_Imports.v112
System.Xml.Tests.TC_SchemaSet_Imports.v119
System.Xml.Tests.TC_SchemaSet_Imports.v209
System.Xml.Tests.TC_SchemaSet_Imports.v1
System.Xml.Tests.TC_SchemaSet_Imports.v108
System.Xml.Tests.TC_SchemaSet_Imports.v114
System.Xml.Tests.TC_SchemaSet_Imports.v110
System.Xml.Tests.TC_SchemaSet_Imports.v19
System.Xml.Tests.TC_SchemaSet_Imports.v111
System.Xml.Tests.TC_SchemaSet_Imports.v101
System.Xml.Tests.TC_SchemaSet_Imports.v9
System.Xml.Tests.TC_SchemaSet_Imports.v11
System.Xml.Tests.TC_SchemaSet_Imports.v16
System.Xml.Tests.TC_SchemaSet_Imports.v18
System.Xml.Tests.TC_SchemaSet_Imports.v17
System.Xml.Tests.TC_SchemaSet_Imports.v218
System.Xml.Tests.TC_SchemaSet_Imports.v202
System.Xml.Tests.TC_SchemaSet_Imports.v7
System.Xml.Tests.TC_SchemaSet_Imports.v220
System.Xml.Tests.TC_SchemaSet_Imports.v20
System.Xml.Tests.TC_SchemaSet_Imports.v205
System.Xml.Tests.TC_SchemaSet_Imports.v215
System.Xml.Tests.TC_SchemaSet_Imports.v212
System.Xml.Tests.TC_SchemaSet_Imports.v207
System.Xml.Tests.TC_SchemaSet_Imports.v102a
System.Xml.Tests.TC_SchemaSet_Imports.v14
System.Xml.Tests.TC_SchemaSet_Imports.v3
System.Xml.Tests.TC_SchemaSet_Imports.v102
System.Xml.Tests.TC_SchemaSet_Imports.v216
System.Xml.Tests.TC_SchemaSet_Imports.v15
System.Xml.Tests.TC_SchemaSet_Imports.v10
System.Xml.Tests.TC_SchemaSet_Imports.v202a
System.Xml.Tests.TC_SchemaSet_Imports.v213
System.Xml.Tests.TC_SchemaSet_Imports.v115
System.Xml.Tests.TC_SchemaSet_Imports.v104
System.Xml.Tests.TC_SchemaSet_Imports.v103
System.Xml.Tests.TC_SchemaSet_Imports.v211
System.Xml.Tests.TC_SchemaSet_Imports.v100
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v4
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v6
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v5
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v1
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v3
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v2
System.Xml.Tests.TC_SchemaSet_ValidationEventHandler.v7
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v10
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v9
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v11
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v6
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v5
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v4
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v8
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v3
System.Xml.Tests.TC_SchemaSet_Add_SchemaSet.v7
System.Xml.Tests.TC_SchemaSet_EnableUpaCheck.v1
System.Xml.Tests.TC_SchemaSet_Add_Reader.AddingSameReaderForNullNamespace
System.Xml.Tests.TC_SchemaSet_Add_Reader.ValidNamespaceReaderPositionedOnANonElementNode
System.Xml.Tests.TC_SchemaSet_Add_Reader.ValidNamespaceValidReaderWithResolverSetToNull
System.Xml.Tests.TC_SchemaSet_Add_Reader.NamespaceUnmatchingReaderValid
System.Xml.Tests.TC_SchemaSet_Add_Reader.ValidNamespaceValidReader
System.Xml.Tests.TC_SchemaSet_Add_Reader.NullNamespaceValidReader
System.Xml.Tests.TC_SchemaSet_Add_Reader.ValidNamespaceReaderPositionedOnElementButNoXsdSchemaTag
System.Xml.Tests.TC_SchemaSet_Add_Reader.AddingReaderOnXDRSchema
System.Xml.Tests.TC_SchemaSet_Add_Reader.Adding2ReadersOnSchemaWithNoNamespacesAddWithDiffNamespace
System.Xml.Tests.TC_SchemaSet_GlobalElements.v5
System.Xml.Tests.TC_SchemaSet_GlobalElements.v6
System.Xml.Tests.TC_SchemaSet_GlobalElements.v4
System.Xml.Tests.TC_SchemaSet_Add_Schema.v7
System.Xml.Tests.TC_SchemaSet_Add_Schema.v11
System.Xml.Tests.TC_SchemaSet_Add_Schema.v2
System.Xml.Tests.TC_SchemaSet_Add_Schema.v5
System.Xml.Tests.TC_SchemaSet_Add_Schema.v9
System.Xml.Tests.TC_SchemaSet_Add_Schema.v12a
System.Xml.Tests.TC_SchemaSet_Add_Schema.v4
System.Xml.Tests.TC_SchemaSet_Add_Schema.v10
System.Xml.Tests.TC_SchemaSet_Add_Schema.v6
System.Xml.Tests.TC_SchemaSet_Add_Schema.v3
System.Xml.Tests.TC_SchemaSet_Add_Schema.v8
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v10
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v5
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v3
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v4
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v8
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v7
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v11
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v6
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v9
System.Xml.Tests.TC_SchemaSet_RemoveRecursive.v2
System.Xml.Tests.TC_SchemaSet_Misc.Dev10_40509
System.Xml.Tests.TC_SchemaSet_Misc.v111
System.Xml.Tests.TC_SchemaSet_Misc.v102
System.Xml.Tests.TC_SchemaSet_Misc.v10
System.Xml.Tests.TC_SchemaSet_Misc.v106
System.Xml.Tests.TC_SchemaSet_Misc.v105
System.Xml.Tests.TC_SchemaSet_Misc.v112
System.Xml.Tests.TC_SchemaSet_Misc.v103
System.Xml.Tests.TC_SchemaSet_Misc.v21
System.Xml.Tests.TC_SchemaSet_Misc.v110
System.Xml.Tests.TC_SchemaSet_Misc.v27
System.Xml.Tests.TC_SchemaSet_Misc.v118
System.Xml.Tests.TC_SchemaSet_Misc.v2
System.Xml.Tests.TC_SchemaSet_Misc.v20
System.Xml.Tests.TC_SchemaSet_Misc.v107
System.Xml.Tests.TC_SchemaSet_Misc.v1
System.Xml.Tests.TC_SchemaSet_Misc.v25
System.Xml.Tests.TC_SchemaSet_Misc.v22
System.Xml.Tests.TC_SchemaSet_Misc.v26
System.Xml.Tests.TC_SchemaSet_Misc.Dev10_40561
System.Xml.Tests.TC_SchemaSet_Misc.v24
System.Xml.Tests.TC_SchemaSet_Misc.v109
System.Xml.Tests.TC_SchemaSet_Misc.v120
System.Xml.Tests.TC_SchemaSet_Misc.v120a
System.Xml.Tests.TC_SchemaSet_Misc.v28

[System.Xml.XmlSchemaSet.Tests.failures.log](https://github.com/dotnet/runtime/files/6320901/System.Xml.XmlSchemaSet.Tests.failures.log)

**Comment by filipnavara** [comment]
Most, if not all, failures are caused by #52104.
