### ISSUE TITLE
System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51338]
Most except for 6 tests fail with `System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/4E109469-BEB0-4BA3-918A-DF83E7945CD5/data/Containers/Bundle/ ...`

System.Xml.XmlSchema.XmlSchemaValidatorApi.Tests
System.Xml.Tests.TCValidateWhitespace_String.PassNonWhitespaceContent__ShouldNotWork
System.Xml.Tests.TCValidateWhitespace_String.TopLevelWhitespace
System.Xml.Tests.TCValidateWhitespace_String.WhitespaceInsideElement
System.Xml.Tests.TCValidateWhitespace_String.WhitespaceInEmptyContent__Invalid
System.Xml.Tests.TCAddSchema.ImportAnotherSchemaThat_Is_IsNot_InSchemaSet
System.Xml.Tests.TCValidateAfterRemove.v2
System.Xml.Tests.TCValidateAfterRemove.v1
System.Xml.Tests.TCValidateAttribute_String.AskForDefaultAttributesAndValidateThem
System.Xml.Tests.TCValidateAttribute_String.PassNull_LocalName_Namespace__Invalid
System.Xml.Tests.TCValidateAttribute_String.PassNullValueGetter__Invalid
System.Xml.Tests.TCValidateAttribute_String.Validate_Required_Optional_Default_Fixed_FixedRequired_Attribute
System.Xml.Tests.TCValidateAttribute_String.ValidateAnyAttribute
System.Xml.Tests.TCValidateAttribute_String.PassNullXmlSchemaInfo__Valid
System.Xml.Tests.TCValidateAttribute_String.ValidateSameAttributeTwice
System.Xml.Tests.TCValidateAttribute_String.ValidateAttributeWithNamespace
System.Xml.Tests.TCValidateAttribute_String.ValidateTopLevelAttribute
System.Xml.Tests.TCValidateAfterAddInvalidSchema.AddValid_Import_Include_Redefine
System.Xml.Tests.TCValidateAfterAddInvalidSchema.AddInvalid_Import_Include
System.Xml.Tests.TCValidateAfterAddInvalidSchema.AddEditInvalidImport
System.Xml.Tests.TCValidateAfterAddInvalidSchema.AddEditInvalidIncludeSchema
System.Xml.Tests.TCValidateAfterAdd.v1
System.Xml.Tests.TCValidateAfterAdd.v2
System.Xml.Tests.TCValidateWhitespace.TopLevelWhitespace
System.Xml.Tests.TCValidateWhitespace.PassNonWhitespaceContent
System.Xml.Tests.TCValidateWhitespace.WhitespaceInEmptyContent__Invalid
System.Xml.Tests.TCValidateWhitespace.WhitespaceInsideElement_Single
System.Xml.Tests.TCValidateAfterReprocess.v2
System.Xml.Tests.TCValidateAfterReprocess.v1
System.Xml.Tests.TCValidateText_String.SanityTestForSimpleType_MultipleCallInOneContext
System.Xml.Tests.TCValidateText_String.EmptyContent
System.Xml.Tests.TCValidateText_String.ElementOnlyContent
System.Xml.Tests.TCValidateText_String.v2
System.Xml.Tests.TCValidateText_String.MixedContent
System.Xml.Tests.TCConstructor.SetSchemaSetTo_Empty_NotCompiled_Compiled
System.Xml.Tests.TCValidateEndOfAttributes.CallWithoutValidationOfDefaultAttributesGetUnspecifiedDefault_Called_NotCalled
System.Xml.Tests.TCValidateEndOfAttributes.CallWithoutValidationOf_Optional_Fixed_Attributes
System.Xml.Tests.TCValidateEndOfAttributes.CallWithoutValidationOfRequiredAttribute
System.Xml.Tests.TCValidateEndOfAttributes.CallAfterValidationOfAllAttributes
System.Xml.Tests.TCValidateEndOfAttributes.CallOnELementWithNoAttributes
System.Xml.Tests.TCGetExpectedAttributes.Call_Before_After_GetUnspecifiedDefaultAttributesWhenJustDefaultAttributesAreLeft
System.Xml.Tests.TCGetExpectedAttributes.Call_Before_After_GetUnspecifiedDefaultAttributeWhenJust_Required_Optional_Fixed_FixedRequired_AttributesAreLeft
System.Xml.Tests.TCGetExpectedAttributes.CallOnElementWith_Required_Optional_Default_Fixed_FixedRequired_AttributesAfterValidateElement
System.Xml.Tests.TCGetExpectedAttributes.CallOnElementWithNoAttributesAfterValidateElement
System.Xml.Tests.TCInitialize.InitializeWithElementValidate_OtherElement_Type_Attribute
System.Xml.Tests.TCInitialize.InitializeWithTypeValidateElement
System.Xml.Tests.TCInitialize.InitializeWithAttributeValidate_OtherAttribute_Element_Type
System.Xml.Tests.TCInitialize.InitializeShouldResetIDConstraints
System.Xml.Tests.TCInitialize.InitializeWithTypeValidate_OtherType_Attribute
System.Xml.Tests.TCInitialize.SetPartiaValidationAndCallValidate_Text_WhiteSpace_Valid
System.Xml.Tests.TCInitialize.InitializeWithAttributeValidateSameAttribute
System.Xml.Tests.TCInitialize.InitializeWithElementValidateSameElement
System.Xml.Tests.TCInitialize.InitializeWithTypeValidateSameType
System.Xml.Tests.TCSkipToEndElement.SkipAfterValidating_ValidContent_IncompleteContent
System.Xml.Tests.TCSkipToEndElement.ValidateTextAndSkip
System.Xml.Tests.TCSkipToEndElement.CheckThatSkipToEndElementJumpsIntoRightContext
System.Xml.Tests.TCSkipToEndElement.PassNull
System.Xml.Tests.TCSkipToEndElement.ValidateAttributesAndSkip
System.Xml.Tests.TCValidateText.MixedContent
System.Xml.Tests.TCValidateText.EmptyContent
System.Xml.Tests.TCValidateText.ElementOnlyContent
System.Xml.Tests.TCValidateText.TopLevelText
System.Xml.Tests.TCValidateText.SanityTestForSimpleType_MultipleCallInOneContext
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.CallTwice
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.PassNull__Invalid
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.CallAfterValidatingSomeDefaultAttributes
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.CallOnElementWithFixedAttribute
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.NestBetweenValidateAttributeCalls
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.v6a
System.Xml.Tests.TCGetUnspecifiedDefaultAttributes.CallAfterGetExpectedAttributes
System.Xml.Tests.TCValidateAttribute.PassNullXmlSchemaInfo__Valid
System.Xml.Tests.TCValidateAttribute.ValidateAnyAttribute
System.Xml.Tests.TCValidateAttribute.Validate_Required_Optional_Default_Fixed_FixedRequired_Attribute
System.Xml.Tests.TCValidateAttribute.ValidateTopLevelAttribute
System.Xml.Tests.TCValidateAttribute.ValidateAttributeWithNamespace
System.Xml.Tests.TCValidateAttribute.ValidateSameAttributeTwice
System.Xml.Tests.TCValidateAttribute.PassNull_LocalName_NameSpace__Invalid
System.Xml.Tests.TCValidateAttribute.PassNullValueGetter__Invalid
System.Xml.Tests.TCValidateAttribute.AskForDefaultAttributesAndValidateThem
System.Xml.Tests.TCGetExpectedParticles.CallForSequenceWithChoiceGroup_Before_After_ValidatingGroupMembers
System.Xml.Tests.TCGetExpectedParticles.CallForAllAfterValidatingBothElements
System.Xml.Tests.TCGetExpectedParticles.CallForRestricted_Sequence_Choice_All__Before_After_ValidatingSeqElements
System.Xml.Tests.TCGetExpectedParticles.CallForElementWithReferenceToGlobalElement
System.Xml.Tests.TCGetExpectedParticles.CallForElementWithoutTypeDefined
System.Xml.Tests.TCGetExpectedParticles.CallAfterValidate_Element_Attribute_EndOfAttributes_ForAll
System.Xml.Tests.TCGetExpectedParticles.CallForChoiceAfterValidating_1_2_ChoiceElement
System.Xml.Tests.TCGetExpectedParticles.CallForSequence_Between_After_ValidationAllSeqElements
System.Xml.Tests.TCGetExpectedParticles.CallAfterValidate_Element_Attribute_EndOfAttributes_ForChoice
System.Xml.Tests.TCGetExpectedParticles.CallForChoiceWithSequenceGroup_Before_After_ValidatingGroupMembers
System.Xml.Tests.TCGetExpectedParticles.CallForExtendedSequence_Before_After_ValidatingSeqOrAllBaseElements
System.Xml.Tests.TCGetExpectedParticles.CallAfter_Constructor_Initialize_EndValidation
System.Xml.Tests.TCGetExpectedParticles.CallForAllAfterValidating_1_2_element
System.Xml.Tests.TCGetExpectedParticles.CallForExtendedChoice_Before_After_ValidatingBaseChoiceElement
System.Xml.Tests.TCGetExpectedParticles.CallForChoice_Before_After_ValidatingWildcard
System.Xml.Tests.TCGetExpectedParticles.CallAfterValidate_Element_Attribute_EndOfAttributes_ForSequence
System.Xml.Tests.TCGetExpectedParticles.CallForSequence_Before_After_ValidatingWildcard
System.Xml.Tests.TCGetExpectedParticles.CallForElementWithZeroMaxOccurs
System.Xml.Tests.TCGetExpectedParticles.CallForElementWithZeroMinOccurs
System.Xml.Tests.TCGetExpectedParticles.CallForChoiceWithElementsFromDifferentNamespaces
System.Xml.Tests.TCValidateEndElement.IncompleteContet__Valid
System.Xml.Tests.TCValidateEndElement.CallValidateTextThenValidateEndElementWithTypedValue
System.Xml.Tests.TCValidateEndElement.TestXmlSchemaInfoValuesAfterUnionValidation_Without_With_ValidationEndElementOverload
System.Xml.Tests.TCValidateEndElement.Typed_NullTypedValue
System.Xml.Tests.TCValidateEndElement.AllXmlSchemaInfoArgsCanBeNull
System.Xml.Tests.TCValidateEndElement.IncompleteContent__Invalid
System.Xml.Tests.TCValidateEndElement.SanityTestForComplexTypes
System.Xml.Tests.TCValidateEndElement.SanityTestForEmptyTypes
System.Xml.Tests.TCValidateEndElement.Typed_NullXmlSchemaInfo
System.Xml.Tests.TCValidateEndElement.TestForIdentityConstraints_Valid_InvalidDuplicateKey_InvalidKeyRefMissing_InvalidIdentitiConstraintIsSet
System.Xml.Tests.TCValidateEndElement.PassNull
System.Xml.Tests.TCValidateEndElement.TextNodeWithoutValidateTextCall
System.Xml.Tests.TCValidateEndElement.CheckSchemaInfoAfterCallingValidateEndElementWithTypedValue
System.Xml.Tests.TCValidateEndElement.CallValidateEndElementWithTypedValueForComplexContent
System.Xml.Tests.TCEndValidation.TestForRootLevelIdentityConstraints_Valid_IDREFMissingInvalid_IgnoreIdentityConstraintsIsSetInvalid
System.Xml.Tests.TCXmlResolver.SetResolverToCustomValidateSomethingSetResolverToNullThenVerify
System.Xml.Tests.TCXmlResolver.InternalSchemaSetShouldUseSeparateXmlResolver
System.Xml.Tests.TCXmlResolver.DefaultValueForXmlResolver_XmlUrlResolver
System.Xml.Tests.TCValidateElement.SanityTestsForNestedElements
System.Xml.Tests.TCValidateElement.CallWith_Null_False_XsiNil
System.Xml.Tests.TCValidateElement.CallValidateElementAndCHeckXmlSchemaInfoFOr_Simple_Complex_Empty_Mixed_Element_First_Second_Overload
System.Xml.Tests.TCValidateElement.CheckThatWarningsDontOccurWhenIgnoreValidationWarningsIsSet
System.Xml.Tests.TCValidateElement.VerifyThatSubstitutionGroupMembersAreResolvedAndAddedToTheList
System.Xml.Tests.TCValidateElement.CheckSchemaLocationIs_UsedWhenSpecified_NotUsedWhenFlagIsNotSet
System.Xml.Tests.TCValidateElement.CheckThatWarningOccursWhenUndefinedElementIsValidatedWithLaxValidation
System.Xml.Tests.TCValidateElement.ProvideValidXsiType
System.Xml.Tests.TCValidateElement.ProvideInvalidXsiType
System.Xml.Tests.TCValidateElement.CheckNoNamespaceSchemaLocationIs_UsedWhenSpecified_NotUsedWhenFlagIsSet
System.Xml.Tests.TCValidateElement.CallWithXsiNilTrue

[System.Xml.XmlSchemaSet.Tests.failures.log](https://github.com/dotnet/runtime/files/6320955/System.Xml.XmlSchemaSet.Tests.failures.log)

**Comment by filipnavara** [comment]
The test seems to pass locally now (with the AppleAppBuilder fix). We should reenable it on CI.
