### ISSUE TITLE
The variable in .razor file of Blazor WebAssembly project couldn't display hexadecimal correctly in EE window

### ISSUE THREAD

**Issue by Claire-kangkang** [dotnet/runtime#51358]
**Azure DevOps work item:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1261865

**Platform**
- [x] Windows
- [ ] macOS
- [ ] Linux

**Repro Steps**
1. Open VS and create a Blazor WebAssembly project.
![image](https://user-images.githubusercontent.com/70516076/114959539-d07c7600-9e97-11eb-8a1c-48d36b2beaed.png)
2. Set a breakpoint at the line 'currentCount++;' in Counter.razor file.
![image](https://user-images.githubusercontent.com/70516076/114959557-d7a38400-9e97-11eb-9b2f-c67479a0e917.png)
3. Press F5 to start debugging.
4. Switch to website and click to trigger the breakpoint.
![image](https://user-images.githubusercontent.com/70516076/114959576-e12cec00-9e97-11eb-9bed-2d40b23a4a3c.png)
5. Enable 'Hexadecimal Display' in EE window and check the value of ''currentCount'

**Actual Result**

The value of variable couldn't display hexadecimal.
![image](https://user-images.githubusercontent.com/70516076/114959598-eb4eea80-9e97-11eb-8fbe-ef5cbbc86303.png)

**Expected Result**
Hexadecimal display correctly.
![image](https://user-images.githubusercontent.com/70516076/114959626-f9047000-9e97-11eb-91e6-c185f8c0a4a3.png)

**Investigation**

This issue only reproduce in Blazor WebAssembly project.

**Comment by lewing** [comment]
@captainsafia any idea where we could read that setting?

**Comment by lewing** [comment]
perhaps we should make a tracking issue for all the settings we don't have access to but would like to

**Comment by BillHiebert** [comment]
@ilonatommy  hmm, not sure. Maybe @gregg-miskelly  would know.

**Comment by thaystg** [comment]
This is already working, but the view is different then the expected, it doesn't show 0x... in the beginning. But it's really showing in hex. If you want to change the view, then the issue should be opened on vscode-js-debug.

https://user-images.githubusercontent.com/4503299/174670321-33f417d9-d3ba-4041-944b-9630da787fd9.mp4
