### ISSUE TITLE
Generic logger does not show the generic parameter type name

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#51368]
When I use `ILogger<T>` in a generic type, I can not tell what's the complete type name the log is from, for we could not get the generic type parameter from the logger category name. Sometimes we use the same generic type with different generic parameters, and I can not tell the log comes from where, it's really bad experience.

I try to take a look at the implement code from <https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerT.cs#L29>, it's like below:

``` c#
private readonly ILogger _logger;

/// <summary>
/// Creates a new <see cref="Logger{T}"/>.
/// </summary>
/// <param name="factory">The factory.</param>
public Logger(ILoggerFactory factory)
{
    if (factory == null)
    {
        throw new ArgumentNullException(nameof(factory));
    }

    _logger = factory.CreateLogger(TypeNameHelper.GetTypeDisplayName(typeof(T), includeGenericParameters: false, nestedTypeDelimiter: '.'));
}
```

I'm wondering that if we could simply change the `includeGenericParameters` from `false` to `true`, is there any performance or something other concerns?

**Comment by maryamariyan** [comment]
If we switched the `includeGenericParameters` flag to true then using `CreateLogger<T>` would lead to category names with `<` and `>` characters:

```c#
var logger = factory.CreateLogger<GenericClass<GenericClass<string>>>();
// before: Microsoft.Extensions.Logging.Test.GenericClass
// after:  Microsoft.Extensions.Logging.Test.GenericClass<Microsoft.Extensions.Logging.Test.GenericClass<string>>

```

We'd need to make sure if we are OK with that and with the fact that this is a breaking change behavior.

**Comment by WeihanLi** [comment]
Yeah, that's exactly what we want. 
We can not tell the difference when we use the same generic type with different generic parameters logger currently.

**Comment by KalleOlaviNiemitalo** [comment]
Could your app register a custom implementation of `ILogger<>` that generates the category name the way you want?

It looks like [LoggerRuleSelector](https://github.com/dotnet/runtime/blob/2f740adc1457e8a28c1c072993b66f515977eb51/src/libraries/Microsoft.Extensions.Logging/src/LoggerRuleSelector.cs) does _not_ require the category name to consist of dot-delimited components, and thus would not need to be changed.

**Comment by WeihanLi** [comment]
Yeah, I can, we're trying this way now.
I'm here also want to see if others have this requirement, if so, maybe we could consider for a change in the logging library.

**Comment by KalleOlaviNiemitalo** [comment]
TraceSourceLoggerProvider however does expect dots as separators. <https://github.com/dotnet/runtime/blob/2f740adc1457e8a28c1c072993b66f515977eb51/src/libraries/Microsoft.Extensions.Logging.TraceSource/src/TraceSourceLoggerProvider.cs#L100-L104>

**Comment by WeihanLi** [comment]
implement this using the code below

``` csharp
public sealed class GenericLoggerOptions
{
    public Func<Type, bool>? FullNamePredict { get; set; }
}

internal sealed class GenericLogger<T> : ILogger<T>
{
    private readonly ILogger _logger;

    public GenericLogger(ILoggerFactory factory, IOptions<GenericLoggerOptions> options)
    {
        if (factory == null)
        {
            throw new ArgumentNullException(nameof(factory));
        }

        var includeGenericParameters = options.Value.FullNamePredict?.Invoke(typeof(T)) == true;
        _logger = factory.CreateLogger(TypeHelper.GetTypeDisplayName(typeof(T), includeGenericParameters: includeGenericParameters, nestedTypeDelimiter: '.'));
    }

    IDisposable ILogger.BeginScope<TState>(TState state)
    {
        return _logger.BeginScope(state);
    }
    bool ILogger.IsEnabled(LogLevel logLevel)
    {
        return _logger.IsEnabled(logLevel);
    }
    void ILogger.Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception? exception, Func<TState, Exception?, string> formatter)
    {
        _logger.Log(logLevel, eventId, state, exception, formatter);
    }
}

public static ILoggingBuilder UseCustomGenericLogger(this ILoggingBuilder loggingBuilder, Action<GenericLoggerOptions> genericLoggerConfig)
{
    Guard.NotNull(loggingBuilder, nameof(loggingBuilder));
    Guard.NotNull(genericLoggerConfig, nameof(genericLoggerConfig));
    loggingBuilder.Services.Configure(genericLoggerConfig);
    loggingBuilder.Services.AddSingleton(typeof(ILogger<>), typeof(GenericLogger<>));
    return loggingBuilder;
}
```

use sample:

``` csharp
using var services = new ServiceCollection()
        .AddLogging(builder => builder.AddConsole().UseCustomGenericLogger(options => options.FullNamePredict = _ => true))
        .AddSingleton(typeof(GenericTest<>))
        .BuildServiceProvider();
services.GetRequiredService<ILogger<GenericTest<int>>>().LogInformation("test");
```
