### ISSUE TITLE
RuntimeInformation.OSDescription wrong version number for ubuntu

### ISSUE THREAD

**Issue by JohannesDeml** [dotnet/runtime#51366]
### Description

When printing `System.Runtime.InteropServices.RuntimeInformation.OSDescription`, I get Ubuntu version 20.04.1, even though it should be 20.04.2. Full output:
```csharp
// Expected Output: Linux 5.8.0-48-generic #54~20.04.2-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021
// Actual Output:   Linux 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021
Console.WriteLine(RuntimeInformation.OSDescription);
```

System information:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ hostnamectl
   Static hostname: MacBook-M1
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: XXX
           Boot ID: XXX
  Operating System: Ubuntu 20.04.2 LTS
            Kernel: Linux 5.8.0-48-generic
      Architecture: x86-64
```

### Configuration
* dotnet --version: 5.0.201
* Ubuntu 20.04.2 x86-64

**Comment by am11** [comment]
OSDescription on Unix is implemented with [`uname(3)`](https://linux.die.net/man/3/uname) library call. So on your system, `uname(1)` command in shell will show the same values (with slightly different formatting).

e.g. dotnetfiddle is using Debian 10 (buster) according to `/etc/os-release`, but it is running Debian in a docker container on top of Ubuntu host, so OSDescription's output matches `uname(1)`'s. i.e. Ubuntu rather than Debian:
https://dotnetfiddle.net/l6mm0I

**Comment by danmoseley** [comment]
@JohannesDeml can you confirm what you see matches uname? 

What can cause os-release to differ other than a container?

**Comment by JohannesDeml** [comment]
@danmoseley  I can confirm, that uname spits out 20.04.1:
```
$ uname -v
#62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

```

**Comment by am11** [comment]
> What can cause os-release to differ other than a container?

`uname` is baked into the OS at build-time. The rest of the utilities / info files are package-time artifacts of userland. Depending on what changed and what didn't rebuilt before a patch release, these slight version differences are not uncommon in distros.

`OSDescription`'s reliance on `uname(3)` library call for versions on all Unix OSes is reasonable and commonly used in other software as well. It does not get affected if someone deletes or changes the release info file.

**Comment by jkotas** [comment]
Fixed by https://github.com/dotnet/runtime/pull/83976. `OSDescription` returns the system name from `/etc/os-release` now.
