### ISSUE TITLE
System.Diagnostics.DiagnosticSource.Switches.Tests Fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51376]
System.Diagnostics.DiagnosticSource.Switches.Tests
System.Diagnostics.Tests.ActivityTests.ActivityIdNonHierarchicalOverflow
System.Diagnostics.Tests.ActivityTests.IdFormat_ZeroTraceIdAndSpanIdWithHierarchicalFormat
System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalIsDefault
System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent

```
System.Diagnostics.DiagnosticSource.Switches.Tests.dll   Failed: 4

Test collection for System.Diagnostics.Tests.ActivityTests
System.Diagnostics.Tests.ActivityTests.ActivityIdNonHierarchicalOverflow
    Assert.InRange() Failure\r\nRange:  (55 - 56)\r\nActual: 27
System.Diagnostics.Tests.ActivityTests.IdFormat_ZeroTraceIdAndSpanIdWithHierarchicalFormat
    Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C
System.Diagnostics.Tests.ActivityTests.IdFormat_HierarchicalIsDefault
    Assert.Equal() Failure\nExpected: Hierarchical\nActual:   W3C
System.Diagnostics.Tests.ActivityTests.IdGenerationInternalParent
    Expected: |d5f08b52f2ffaeee86d061b6155f754c.child1-1. || |d5f08b52f2ffaeee86d061b6155f754c.1.\nActual: 00-d5f08b52f2ffaeee86d061b6155f754c-d95ea716e9fdebf3-00
```

**Comment by noahfalk** [comment]
Does this issue have an owner? If not I am going to assume it won't get fixed in the next few weeks and needs to be punted to 7.0

**Comment by mdh1418** [comment]
This is the same as https://github.com/dotnet/runtime/issues/37073, folding them in together.
