### ISSUE TITLE
Update documentation - Look into runtime tests test running command

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#51396]
Need to update the doc: There has been some change to the runtime test building and running infrastructure. The old command doesn't work any more. Need to figure out the current correct command and update the doc for it.

**Comment by SamMonoRT** [comment]
@akoeplinger might have an idea - @fanyang-mono what command is not working for you ?

**Comment by fanyang-mono** [comment]
> @akoeplinger might have an idea - @fanyang-mono what command is not working for you ?

The command to run runtime tests locally stopped working. It is not affecting runs on the CI. I just need to spend some time to sort it out.
