### ISSUE TITLE
Microsoft.Extensions.Logging.Console.Tests Fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51398]
Microsoft.Extensions.Logging.Console.Tests
Microsoft.Extensions.Logging.Console.Test.SimpleConsoleFormatterTests.Log_WritingScopes_LogsWithCorrectColorsWhenColorEnabled

```
Microsoft.Extensions.Logging.Console.Tests.dll   Failed: 1

Test collection for Microsoft.Extensions.Logging.Console.Test.SimpleConsoleFormatterTests
Microsoft.Extensions.Logging.Console.Test.SimpleConsoleFormatterTests.Log_WritingScopes_LogsWithCorrectColorsWhenColorEnabled(colorBehavior: Default)
    Assert.Equal() Failure\nExpected: 1\nActual:   2

**Comment by mkhamoyan** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74349

**Comment by mkhamoyan** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74349

**Comment by mkhamoyan** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74496
