### ISSUE TITLE
Remove dependency on X11 developer package

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#51404]
### Description

The System.Drawing.Common library currently has a dependency on the X11 developer native package (e.g. `libx11-dev`) in order to execute certain code paths.  Developer packages are not typically installed on end-user systems.  Instead, it should only be necessary to install the X11 client library (e.g. `libx11-6`).

The reason for the dependency on the developer package is because code in System.Drawing.Common is relying on the existence of a file named libX11.so.  A file by that name is not installed by the client package.  Instead, it provides these files:

* `/usr/lib/x86_64-linux-gnu/libX11.so.6`
* `/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0`

When you install the developer package, it adds a symbolic link to the versioned .so file:
* `/usr/lib/x86_64-linux-gnu/libX11.so` -> `/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0`

In order to remove the dependency on the version-less symbolic link file (and thus, the developer package) it'd be necessary to have library resolution logic that searches for a versioned .so file.

### Repro

On a Debian 11 system, install only `libx11-6` and not `libx11-dev`.

Run the following code to exercise the X11 logic:

```csharp
var g = Graphics.FromImage(new Bitmap(10, 10));
g.CopyFromScreen(new Point(0, 0), new Point(1, 1), new Size(1, 1));
```

Results in the following exception:
```
System.DllNotFoundException: 'Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory'
```

### Configuration

This applies to all supported .NET/.NET Core versions.

**Comment by safern** [comment]
Closing this issue per design doc: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md

We will be removing the Unix implementation entirely on .NET 7.
