### ISSUE TITLE
[release/3.1] Backport Fix for Issue 37162 AssemblyDependencyResolver filename should not be case sensitive

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#51405]
### AssemblyDependencyResolver filename should not be case sensitive

There is a problem with resolving multiple files with the same simple name (e.g. Module, module) in case insensitive OS like Windows for AssemblyDependencyResolver. Our internal storage for such cases throws that can cause problems for users who do not expect the error.

## Customer Impact

Reported by customer who was migrating to .Net Core from the Desktop runtime.

After migrating the mixed-mode C++/CLI application from targeting .NET Framework over to .NET Core 3.1, several obstacles have been encountered. One of them is an exception related to adding a duplicate key to a Dictionary in the AssemblyDependencyResolver. Alternatively, they might get an exception about the assembly having already been found with a different extension. Both of these problem point back to .NET Core having a mixture of case sensitivity and insensitivity.

## Regression?

No 

## Testing

customer scenario

## Risk

Low. 

Although getting casing correct with different OSs are notoriously hard, the resolution was be to make AssemblyDependencyResolver consistent with other parts of the runtime by choosing the first simple file name and not throwing afterwards for same simple filename with different casing

**Comment by jeffschwMSFT** [comment]
@LakshanF thanks for filing this matching issue, but the only required artifact is a pr.  Feel free to keep this open and linked or close in favor of the pr.

**Comment by vitek-karas** [comment]
@LakshanF has this been fixed?

**Comment by LakshanF** [comment]
Yes, this was merged with https://github.com/dotnet/coreclr/pull/28161
