### ISSUE TITLE
[MONO][PERF] Perf Regression in System.Tests.Perf_String

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#51418]
My best guess is this regression is caused by https://github.com/dotnet/runtime/commit/9bb0427e765e8aac89be0147599bd173486682ea
@stephentoub does that sound plausible?

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [3cbbadee12cc95bd62c70786d5408a2277a21e0a](https://github.com/dotnet/runtime/commit/3cbbadee12cc95bd62c70786d5408a2277a21e0a)
Compare | [2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc](https://github.com/dotnet/runtime/commit/2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc)
Diff | [Diff](https://github.com/dotnet/runtime/compare/3cbbadee12cc95bd62c70786d5408a2277a21e0a...2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc)

### Regressions in System.Collections.ContainsFalse&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[HashSet](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Collections.ContainsFalse(String).HashSet(Size%3a%20512).html>) | 16.25 μs | 17.74 μs | 1.09 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.ContainsFalse&lt;String&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-07a3c86a-e5c5-4acf-86d5-0595e5f7cc4ed9ca9aabc844db4a7/ba2e0257-ae81-48df-b8aa-f7548f469d35.zip?sv=2019-07-07&se=2021-05-11T10%3A58%3A45Z&sr=c&sp=rl&sig=mMjrirRewz4KYFFUbZOHOKFCZnWpOdxhkGWryu%2BOVr0%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c30f0fe0-5f85-47b8-a896-5dc122ff94ef4c88d6b82274410a3/888ed058-91d2-4d28-a1cd-b25782ddb798.zip?sv=2019-07-07&se=2021-05-12T01%3A12%3A47Z&sr=c&sp=rl&sig=LWKiKLEnxrJW18PNkxYJ83EXzaXZJdlITb4WnyP1wk4%3D>)

#### System.Collections.ContainsFalse&lt;String&gt;.HashSet(Size: 512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [3cbbadee12cc95bd62c70786d5408a2277a21e0a](https://github.com/dotnet/runtime/commit/3cbbadee12cc95bd62c70786d5408a2277a21e0a)
Compare | [2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc](https://github.com/dotnet/runtime/commit/2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc)
Diff | [Diff](https://github.com/dotnet/runtime/compare/3cbbadee12cc95bd62c70786d5408a2277a21e0a...2740fbbe0b3bf2e5b4aea9a121047b81b233a5cc)

### Regressions in System.Text.Json.Tests.Utf8JsonReaderCommentsTests

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Utf8JsonReaderCommentParsing](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Text.Json.Tests.Utf8JsonReaderCommentsTests.Utf8JsonReaderCommentParsing(CommentHandling%3a%20Skip%2c%20SegmentSize%3a%200%2c%20TestCase%3a%20LongMultiLine).html>) | 19.48 μs | 20.59 μs | 1.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Text.Json.Tests.Utf8JsonReaderCommentsTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Tests.Utf8JsonReaderCommentsTests*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-07a3c86a-e5c5-4acf-86d5-0595e5f7cc4ed9ca9aabc844db4a7/ba2e0257-ae81-48df-b8aa-f7548f469d35.zip?sv=2019-07-07&se=2021-05-11T10%3A58%3A45Z&sr=c&sp=rl&sig=mMjrirRewz4KYFFUbZOHOKFCZnWpOdxhkGWryu%2BOVr0%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-c30f0fe0-5f85-47b8-a896-5dc122ff94ef4c88d6b82274410a3/888ed058-91d2-4d28-a1cd-b25782ddb798.zip?sv=2019-07-07&se=2021-05-12T01%3A12%3A47Z&sr=c&sp=rl&sig=LWKiKLEnxrJW18PNkxYJ83EXzaXZJdlITb4WnyP1wk4%3D>)

#### System.Text.Json.Tests.Utf8JsonReaderCommentsTests.Utf8JsonReaderCommentParsing(CommentHandling: Skip, SegmentSize: 0, TestCase: LongMultiLine)

```log

```

There are performance regressions in several System.Tests.Perf_String benchmarks on mono. My best guess is that they are due to this change: https://github.com/dotnet/runtime/commit/9bb0427e765e8aac89be0147599bd173486682ea. @stephentoub  Is that plausible?

The autofiled issue is below; this is from the interpreter, but we see similar regressions in JIT mode.

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment]
> My best guess is this regression is caused by 9bb0427 @stephentoub does that sound plausible?

Do these tests even exercise those code paths? That change simply removed some overhead as part of copying data from strings to spans.  I wouldn't expect such copying to show up as part of,  for example,  doing a contains on a hashset.

**Comment by danmoseley** [comment]
@naricc is this Linux only? I only see Ubuntu above but you did not apply the os label.

**Comment by naricc** [comment]
@danmoseley All our mono perf runs are on ubuntu. So, I am not sure if this appears on any other platform. Should I always label these as linux in that case?

**Comment by danmoseley** [comment]
Ah that explains it. No I don't think so - @DrewScoggins sets os label(s) to tell us "does not reproduce on the other OSes" which is helpful. 
This is Mono specific though, or  does it show up on CoreCLR?

**Comment by naricc** [comment]
@danmoseley Looking at the data here: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.ContainsFalse(String).HashSet(Size:%20512).html, it looks like there might have been a regression around the same time in CoreCLR, but if so it is much more muted than in Mono.

I don't believe any issue was produced for it in CoreCLR.

**Comment by danmoseley** [comment]
@DrewScoggins  in your opinion is this mono specific?

**Comment by DrewScoggins** [comment]
I would go farther and say that this looks Mono AOT specific. I don't see this regression on Windows x64/x86, Ubuntu x64/Arm64, and Mono Interpreter and straight Mono.

**Comment by danmoseley** [comment]
Thanks @DrewScoggins . I wonder whether @stephentoub  changes are somehow exposing a problem there. Are there any other Mono AOT regressions in this interval?

**Comment by DrewScoggins** [comment]
If you click on the name of the test, and then on the yellow bar labeled Non-Top Counters you can see the number of GC's that were measured during the test. For this regression we had no GCs.

![image](https://user-images.githubusercontent.com/9439069/115438810-b063f400-a1c2-11eb-88f4-b1ddbee90f7e.png)

**Comment by danmoseley** [comment]
I agree with @DrewScoggins this doesn't appear to show up for CoreCLR
![image](https://user-images.githubusercontent.com/6385855/115592366-fc2ca100-a287-11eb-9045-e7411203b2e5.png)

@naricc this seems to be a case where a seemingly innocuous change in the libraries has caused bad behavior in Mono only. I think we have two option: revert @stephentoub 's changes and see whether it goes back, then reevaluate; or, ask Mono folks to investigate.

Do you agree -what is your preference?

**Comment by danmoseley** [comment]
cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
Agree with Steve's initial assessment at https://github.com/dotnet/runtime/issues/51418#issuecomment-821729569. It would be quite surprising to me if his change were the cause of this, and I'd be sad to see it reverted.

**Comment by danmoseley** [comment]
cc @marek-safar in case he has an idea.

**Comment by naricc** [comment]
@danmoseley @stephentoub 

 So, now that we have a week of additional data, it seems like this has fixed itself. Sorry for the false alarm; I was what looked like a regression, and saw changes to the string stuff, so thought it could potentially be related.
 
 For the HashSet ones it looks like it was on the plateau from about April 8th to April 21st,  then dropped back to the previous level. The json ones are just up and down a lot.
 
 I think we probably need to find better ways to filter these perf issues. But for now I am closing this one.

**Comment by danmoseley** [comment]
@naricc no problem at all. 

> I think we probably need to find better ways to filter these perf issues

The graph at the top look like real regressions to me. If they turned out to be false - that is great - but I do not know how you would filter such jumps.
