### ISSUE TITLE
[MONO][PERF] Perf Regression in some System.Buffers, System.Collections Benchmarks

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#51419]
My best guess is this was caused by the following change: https://github.com/dotnet/runtime/commit/295bcdc66d1cb4c462554a6980fff9c23b7d550c
@bbartels 

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a7ed1fd065da1b2309c07bacc1b44d2e567107c8](https://github.com/dotnet/runtime/commit/a7ed1fd065da1b2309c07bacc1b44d2e567107c8)
Compare | [5bad843281caac09e18958f27d7d914eb6086e77](https://github.com/dotnet/runtime/commit/5bad843281caac09e18958f27d7d914eb6086e77)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a7ed1fd065da1b2309c07bacc1b44d2e567107c8...5bad843281caac09e18958f27d7d914eb6086e77)

### Regressions in System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[MultipleSerial](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Buffers.Tests.RentReturnArrayPoolTests(Object).MultipleSerial(RentalSize%3a%204096%2c%20ManipulateArray%3a%20True%2c%20Async%3a%20False%2c%20UseSharedPool%3a%20True).html>) | 46.70 μs | 53.63 μs | 1.15 | | |
[MultipleSerial](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Buffers.Tests.RentReturnArrayPoolTests(Object).MultipleSerial(RentalSize%3a%204096%2c%20ManipulateArray%3a%20True%2c%20Async%3a%20False%2c%20UseSharedPool%3a%20False).html>) | 45.19 μs | 52.12 μs | 1.15 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_7.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_8.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_9.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_10.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_11.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_12.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_13.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_14.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object)_15.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Buffers.Tests.RentReturnArrayPoolTests(Object).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9dc4f03b-519f-4d6b-aa62-7e37d5d3f7e9379484eaa3e4e79b7/9d98fc35-712e-4697-a540-c5611aa82c30.zip?sv=2019-07-07&se=2021-05-07T11%3A26%3A47Z&sr=c&sp=rl&sig=Yg7Zuy1MtS8LQihqHLqAQNwt%2BrN3t84I3TdhlqlembU%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4abe693b-b607-4d50-b1a1-f8de2ac3260c401d4b244e64d108c/abad20eb-5b2b-4d29-a5cb-50cf3ed6eb9e.zip?sv=2019-07-07&se=2021-05-07T23%3A46%3A15Z&sr=c&sp=rl&sig=vCBFHoz8pA5nq9XKXfApNDuKEUOB00ROwd4CJTDH3M8%3D>)

#### System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;.MultipleSerial(RentalSize: 4096, ManipulateArray: True, Async: False, UseSharedPool: True)

```log

```
#### System.Buffers.Tests.RentReturnArrayPoolTests&lt;Object&gt;.MultipleSerial(RentalSize: 4096, ManipulateArray: True, Async: False, UseSharedPool: False)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a7ed1fd065da1b2309c07bacc1b44d2e567107c8](https://github.com/dotnet/runtime/commit/a7ed1fd065da1b2309c07bacc1b44d2e567107c8)
Compare | [5bad843281caac09e18958f27d7d914eb6086e77](https://github.com/dotnet/runtime/commit/5bad843281caac09e18958f27d7d914eb6086e77)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a7ed1fd065da1b2309c07bacc1b44d2e567107c8...5bad843281caac09e18958f27d7d914eb6086e77)

### Regressions in System.Collections.ContainsFalse&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[HashSet](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Collections.ContainsFalse(String).HashSet(Size%3a%20512).html>) | 16.13 μs | 18.46 μs | 1.14 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String)_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Collections.ContainsFalse(String).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.ContainsFalse&lt;String&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9dc4f03b-519f-4d6b-aa62-7e37d5d3f7e9379484eaa3e4e79b7/9d98fc35-712e-4697-a540-c5611aa82c30.zip?sv=2019-07-07&se=2021-05-07T11%3A26%3A47Z&sr=c&sp=rl&sig=Yg7Zuy1MtS8LQihqHLqAQNwt%2BrN3t84I3TdhlqlembU%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4abe693b-b607-4d50-b1a1-f8de2ac3260c401d4b244e64d108c/abad20eb-5b2b-4d29-a5cb-50cf3ed6eb9e.zip?sv=2019-07-07&se=2021-05-07T23%3A46%3A15Z&sr=c&sp=rl&sig=vCBFHoz8pA5nq9XKXfApNDuKEUOB00ROwd4CJTDH3M8%3D>)

#### System.Collections.ContainsFalse&lt;String&gt;.HashSet(Size: 512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by safern** [comment]
@naricc I guess this is not area-infrastructure-libraries, correct?

**Comment by naricc** [comment]
@safern I labeled it that because the underlying change that seems to have caused this is a libraries change. Is that not correct?

**Comment by safern** [comment]
What is the suspicious change?

**Comment by bbartels** [comment]
I had a look at the affected benchmarks and can't see any connection between the regressions and the linked change.

**Comment by naricc** [comment]
@safern https://github.com/dotnet/runtime/commit/295bcdc66d1cb4c462554a6980fff9c23b7d550c

But apparently the benchmarks don't actually use that. So I don't see any other plausible candidate and I will close this issue.
