### ISSUE TITLE
[Perf][Mono] Regressions in  System.Drawing.Tests.Perf_Color

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#51423]
It looks like this regression was caused by https://github.com/dotnet/runtime/commit/89498d8f6095511d1553fabe39fa8f0579b1cf2d
@L2 Is there anything to do about this?

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a3e0894f38b1ab558653e7c1b7322a8c4db92af1](https://github.com/dotnet/runtime/commit/a3e0894f38b1ab558653e7c1b7322a8c4db92af1)
Compare | [6bfc5f21dea7b550f1c807454d45408ef34764e1](https://github.com/dotnet/runtime/commit/6bfc5f21dea7b550f1c807454d45408ef34764e1)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...6bfc5f21dea7b550f1c807454d45408ef34764e1)

### Regressions in System.Drawing.Tests.Perf_Color

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[GetHue](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Drawing.Tests.Perf_Color.GetHue.html>) | 1.60 μs | 1.93 μs | 1.20 | | |
[GetBrightness](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Drawing.Tests.Perf_Color.GetBrightness.html>) | 1.18 μs | 1.42 μs | 1.20 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_7.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_8.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_9.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_10.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_11.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_12.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_13.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_14.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color_15.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_12_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/System.Drawing.Tests.Perf_Color.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Drawing.Tests.Perf_Color*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-4f289a83-011e-4af2-93d6-e54544451aaef8e9425d5ed45ccaa/6d6b6cd4-7320-4acb-8ebe-0f24ed4209e4.zip?sv=2019-07-07&se=2021-05-05T19%3A40%3A38Z&sr=c&sp=rl&sig=jpXdspM56nw22cwLixbAlaT6r3ta5%2BXlPj373BUFgwc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-7428b546-ea89-43f0-9d23-b45da4cd3a0731d56e954b543338d/57a3901c-6af6-49e3-aa41-64712f588ca5.zip?sv=2019-07-07&se=2021-05-06T16%3A34%3A52Z&sr=c&sp=rl&sig=5LEDRnUTyNz%2FIubzfnjqjefoZlGJSeiY5c10wJtIwj0%3D>)

#### System.Drawing.Tests.Perf_Color.GetHue

```log

```
#### System.Drawing.Tests.Perf_Color.GetBrightness

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by L2** [comment]
@naricc would you happen to have a copy of the assemblies for base and diff? On x64 this change certainly did speed things up but I have not looked at mono's performance impact. With the method being inlined, it should be a shorter code path but if you can get the assemblies that would be great and I'll take a look. Thanks.

**Comment by naricc** [comment]
@L2 I do not have the assemblies, only the commit hashes. @DrewScoggins I don't think there is any easy way to retrieve those, but I thought I would ask?

**Comment by DrewScoggins** [comment]
If you click on the details marker in the issue, you will see links to the payloads that we ran for both baseline and compare.

**Comment by BrzVlad** [comment]
There is nothing that can be done to improve this on the interp side. I also don't see this as a justification to revert the original change.
