### ISSUE TITLE
Socket.SendAsync and ReadOnlyMemory<byte>.Empty throws exception

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#51426]
### Description

Using `Socket.SendAsync` with `ReadOnlyMemory<byte>.Empty` was throwing a "Bad address" socket exception on Linux.

Broken:

```cs
await socket.SendAsync(ReadOnlyMemory<byte>.Empty, SocketFlags.None).ConfigureAwait(false);
```

Works:

```cs
await socket.SendAsync(Array.Empty<byte>(), SocketFlags.None).ConfigureAwait(false);
```

I only saw this error in a docker container so it might be specific to Linux.

### Configuration

Docker image `mcr.microsoft.com/dotnet/aspnet:5.0`.

### Regression?

No

### Other information

```
      System.Net.Sockets.SocketException (14): Bad address
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsync(Socket socket, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.SendAsync(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
```

**Comment by stephentoub** [comment]
"Bad address" maps to EFAULT, and the man page for send documents:
```
       EFAULT An invalid user space address was specified for an
              argument.
```
I suspect what's happening is we're passing down 0 as the buffer address, and even though the length is 0, the syscall still doesn't like it.  This doesn't happen then with `Array.Empty<byte>()`, as that's actually backed by a zero-length managed array, which does have a non-0 address.

**Comment by geoffkizer** [comment]
I suspect the same.

I'm deliberating where the fix should go. I'm thinking it's probably best to do this at the deepest layer to avoid any issues here, i.e. just before we call Send.

**Comment by stephentoub** [comment]
Note we already special-case count==0 for receives here:
https://github.com/dotnet/runtime/blob/8093c52a9a4abde623c1bf8b74334f11030847f2/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L739-L752
If we need to special-case count==0 for sends as well, ideally it'd be in the corresponding place for the write path.
