### ISSUE TITLE
R2R tests failing

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#51430]
In the outerloop job, all platforms, during crossgen CORE_ROOT step, with:
```
88 / 260 (32%, 1 failed): failed in 99 msecs, exit code 33, expected 0: crossgen @/__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Checked/crossgen.out/Microsoft.Extensions.Logging.Generators.dll.rsp
!! Error: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040 (FUSION_E_REF_DEF_MISMATCH))
  Microsoft (R) CoreCLR Native Image Generator - Version 6.0.0-ci
  Copyright (c) Microsoft Corporation.  All rights reserved.
!! Error compiling /__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/Microsoft.Extensions.Logging.Generators.dll: Could not find or load a specific file. (0x80131621 (COR_E_FILELOAD))
!! Error: compilation failed for "/__w/1/s/artifacts/tests/coreclr/Linux.x64.Checked/Tests/Core_Root/Microsoft.Extensions.Logging.Generators.dll" (0x80131621)
```

starting with https://dev.azure.com/dnceng/public/_build/results?buildId=1093577&view=results

@dotnet/crossgen-contrib Any crossgen changes that might have caused this? Or something else?

**Comment by mangod9** [comment]
hmm weird, this looks to be some sdk version mismatch. Wondering why its still using crossgen rather than crossgen2. cc @trylek

**Comment by jkotas** [comment]
This was introduce by #51064. Microsoft.Extensions.Logging.Generators should be excluded from Core_Root

**Comment by mangod9** [comment]
so should it be removed from being copied into `Core_Root` or excluded from being precompiled? I see references to `tests/skipCrossGenFiles.*` but no such files currently exist.

**Comment by jkotas** [comment]
> so should it be removed from being copied into Core_Root or excluded from being precompiled? 

or should all dependencies of the source generator be copied to core_root as well?

I do not know the answer to this question.

**Comment by mangod9** [comment]
thanks @trylek for the workaround to exclude this from being cg2-ed. Adding @maryamariyan to determine the right fix here to either exclude from `Core_Root` or include all dependencies too.

**Comment by maryamariyan** [comment]
I think this is related to comment: https://github.com/dotnet/runtime/pull/51064#issuecomment-819124660

cc: @safern @ericstj

**Comment by ericstj** [comment]
This is happening because the Cross-Gen tests are rather greedy with how they discover input to cross-gen.  CORE_ROOT isn't a thing that the build process creates, it's constructed by these tests.  Let  me dig up how we've excluded things in the past.

**Comment by ericstj** [comment]
Same issue we faced here: https://github.com/dotnet/runtime/pull/48858#issuecomment-789381586

Here's what we did to fix it: https://github.com/dotnet/runtime/pull/49067/files#diff-eca9f7212ff23b6ded37c0d8f25fc9c07227848945559b82ace20cd8152f1e78R8

We can make the same change here, and it should be done for all Generators.
https://github.com/dotnet/runtime/blob/2aba0c511ce6949513f2024c76a30585e7544628/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj#L8

**Comment by trylek** [comment]
For Eric's comment, Brian's fix just excluded the assembly from Crossgenning. This is what I proposed to do in

https://github.com/dotnet/runtime/pull/51445

The broader question is whether the assembly should be making it to <code>CORE_ROOT</code> at all; if not, it would be cleaner to exclude it in the script file I pointed out because on top of potentially breaking Crossgen2 compilation unneeded files also bloat the Helix payloads.
