### ISSUE TITLE
Third party notices contains a copyleft license

### ISSUE THREAD

**Issue by KevinCathcart** [dotnet/runtime#51436]
The third party notices file in this repository contains an entry indicating a copyleft license.

This is rather surprising, as I was expecting to see mostly permissive licenses, like MIT, X1q, ZLIB, BSD, Apache, public domain dedications, etc.

However there is a “xorshift (Wikipedia)” entry, with the copyleft CC-SA 3.0 Unported license. It not immediately clear to me what code, data file, comment, or documentation is derived from Wikipedia content, and this this license applies to. Depending on exactly which content that notice applies to, this could prove a problem for users, because most copyleft licenses are incompatible with each other.

If more clarity on what this applies to can be obtained, it would be rather helpful. (E.g. if this applies to code only in a unit test, it likely to be less of an issue than if it applies to the libraries or the runtime.)

**Comment by jkotas** [comment]
xorshift license entries added by https://github.com/dotnet/coreclr/pull/27215

@richlander

**Comment by benaadams** [comment]
Looks like its used by read2run compiler?

https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/zap/zapreadytorun.cpp#L566-L570

https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/DependencyAnalysis/ReadyToRun/AttributePresenceFilterNode.cs#L283-L287

Could switch to Xoroshiro which is used by the libs for Random https://github.com/dotnet/runtime/pull/47085 and is CC0 1.0 Universal (CC0 1.0) Public Domain

**Comment by KevinCathcart** [comment]
The question is if that implementation is derived from the Wikipedia. The notice lists two sources and two licenses. If these are mere derivatives of the CC-by licensed journal article, then fine. If they are based on copy pasted Wikipedia code, then not so fine.  (Admittedly, I prefer to avoid code under CC licenses other than CC0, since they were not really designed with software in mind, but I won’t object to their presence.)

**Comment by KevinCathcart** [comment]
Bad news: The code we have is very clearly copy and pasted from Wikipedia. 

Mixed news, The journal article does provide its own implementation, but the license is very unclear. The site claims the article is CC-BY 3.0 Unported, which is awkward, but fine. Further, the journal requires the software for an article to be available under GPL v2, GPLv3, or a GPL Compatible license. This normally refers to a tarball/zip file with the software, but this paper only has super short snippets inline in the paper, with no stated license. Even worse though at the time the paper was submitted, it was stated that author kept the copyright, and just granted permission for the journal to host the paper for free download. It is unclear if the jorunal had the authority to license this paper under CC-BY.

Good news: This being part of ready-to-run probably means this does not meaningfully impact customers, since I'm pretty self-contained deployments don't even include this code, on the basis of not needing it, and while this may effect the overall license of crossgen, it would

Good News: Shifting to xoshiro128\*\* is probably trivial, since its main function logically has the signature (if you use a version with explicit state passing, rather than static variables), so just drop in and update the two calls in ComputeAttributePresenceTable to use the new function name.

C++
```c++
static inline uint32_t RotateLeft(const uint32_t x, int k) {
	return (x << k) | (x >> (32 - k));
}

uint32_t Xoshiro128StarStar(uint32_t s[]) {
	const uint32_t result = RotateLeft(s[1] * 5, 7) * 9;
	const uint32_t t = s[1] << 9;

	s[2] ^= s[0];
	s[3] ^= s[1];
	s[1] ^= s[2];
	s[0] ^= s[3];

	s[2] ^= t;
	s[3] = RotateLeft(s[3], 11);

	return result;
}
```

and

C#
```c#
internal uint Xoshiro128StarStar(uint[] s)
{
    uint result = BitOperations.RotateLeft(s[1] * 5, 7) * 9;
    uint t = s[1] << 9;

    s[2] ^= s[0];
    s[3] ^= s[1];
    s[1] ^= s[2];
    s[0] ^= s[3];

    s[2] ^= t;
    s[3] = BitOperations.RotateLeft(s[3], 11);

    return result;
}
```

(I'm assuming we want both managed and native implementations to be the same, otherwise, I'd suggest just using System.Random directly in the managed implemention now.)

**Comment by KevinCathcart** [comment]
I've created a PR that resolves this via use of xoshiro128\*\* (chosen because we use it for x86 System.Random, and because it is a drop in replacement for xor128, using an identical state array and everything). Obviously, this is only one of many possible options to clear this up, but it was easy to throw together, is a simple, logical, and low risk way to resolve the uncertainty and potential copyleft nature of this piece of code.

No hard feeling you you would prefer to explore other ways of resolving this.

**Comment by danmoseley** [comment]
@jkotas maybe this should have crossgen label if it's R2R?
