### ISSUE TITLE
Weird Behaviors with Nullable Enum Generics

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/runtime#51467]
Compile the following code in .NET 5. F.Parse should return ¸LogLevel?, but instead returns LogLevel (non-nullable).

    public enum LogLevel
    {
        None,
        Debug,
        Info
    }

    public interface IFormatter<T>
    {
        T? Parse(string? value);
        string? Format(T? value);
    }

    public class FormatterEnum<T> : IFormatter<T>
        where T : Enum
    {
        public T? Parse(string? value) => default;
        public string? Format(T? value) => null;
    }

    public class MyClass
    {
        public void DoIt()
        {
            var F = new FormatterEnum<LogLevel>();
            var Value = F.Parse(null); // not nullable
        }
    }

Furthermore, if you add 'struct' constraint in addition to 'Enum', it throws these weird errors

> 'FormatterEnum<T>' does not implement interface member 'IFormatter<T>.Parse(string?)'. 'FormatterEnum<T>.Parse(string?)' cannot implement 'IFormatter<T>.Parse(string?)' because it does not have the matching return type of 'T'.
> 'FormatterEnum<T>' does not implement interface member 'IFormatter<T>.Format(T)'

What makes this message even more awkward is that you can delete class members, use "Implement Interface", it will add the members and keep saying the errors, so you keep clicking "Implement Interface" many times without solving anything.

**Comment by KalleOlaviNiemitalo** [comment]
I guess the problem is that, when `interface IFormatter<T>` has no `where T : struct` constraint, the compiler assumes that `T?` in its members means a nullable reference type, rather than `Nullable<T>`. Similar to <https://github.com/dotnet/csharplang/issues/3101>.

**Comment by mysteryx93** [comment]
The thread you linked was closed as "resolved in C# 9.0", and my question is specifically about 9.0. It's not helping.

I did however find a work-around. This works.

    public enum LogLevel
    {
        None,
        Debug,
        Info
    }

    public interface IFormatter<T>
    {
        T Parse(string? value);
        string? Format(T value);
    }

    public class FormatterEnum<T> : IFormatter<T?>
        where T : struct, Enum
    {
        public T? Parse(string? value) => default;
        public string? Format(T? value) => null;
    }

    public class MyClass
    {
        public void DoIt()
        {
            var f = new FormatterEnum<LogLevel>();
            var value = f.Parse(null);
        }
    }

Nonetheless, whether "by design" or not, the current design is non-intuitive and less than optimal. I think either the behaviour could be improved, or the error messages should be improved.

**Comment by mysteryx93** [comment]
I see that although T? on unconstrained type is supported in C#9, it means by design ValueOrDefault, not ValueOrNull. The errors could definitely be more explicit though.
https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/unconstrained-type-parameter-annotations.md

And the "default" constraint isn't documented at all.

If I want ValueOrNull, then I guess I have to keep the old approach of duplicating the base classes with class/struct constraints.

**Comment by KalleOlaviNiemitalo** [comment]
> What makes this message even more awkward is that you can delete class members, use "Implement Interface", it will add the members and keep saying the errors, so you keep clicking "Implement Interface" many times without solving anything.

That part might be worth reporting as a bug on Visual Studio or whatever you are using.
