### ISSUE TITLE
Use IValueTaskSource in PipeStream on Windows

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#51463]
FileStream was recently overhauled, including using an IValueTaskSource as part of its support for async operations.  PipeStream used an almost exact copy of the code FileStream had previously been using; we should similarly update PipeStream to use an IValueTaskSource implementation, either the exact same one, sharing the code, or something similar in spirit.  This will help to reduce allocations with PipeStream.

**Comment by carlossanlop** [comment]
@manandre Thank you for your contribution! I'd assign this issue to you but GitHub doesn't let me unless you participate in the discussion here. Consider the issue yours.

**Comment by manandre** [comment]
@carlossanlop Thanks for assigning me to this issue.
