### ISSUE TITLE
[API Proposal] Add an Activator.CreateInstances function for creating class instances from a collection of Types.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#51465]
## Background and Motivation

For years the ``Activator`` class helps with creating instances of types known at runtime, however currently it does not itterate and create instances of an Enumerable of types known at runtime without users writing code specifically to manually add it. Such code is trivial to add to the ``Activator`` class and could be added by a method in a expression body very easily with an ``.Select`` (and an ``.Where`` call to filter out null returns from ``Activator.CreateInstance(type)``) both of which can use a cached lambda that would only need to be allocated once in the entire runtime that the compiler would generate.

## Proposed API

```diff
namespace System
{
    public class Activator
    {
+        public static IEnumerable<object> CreateInstances(IEnumerable<Type> types)
+        {
+            List<object> instances = new();
+            foreach (var type in types)
+            {
+                var instance = Activator.CreateInstance(type);
+                if (instance is not null)
+                {
+                    instances.Add(instance);
+                }
+            }
+
+            return instances.AsEnumerable();
+        }
    }
 }
```

## Usage Examples

People wanting to make a plugin system which then creates instances of the plugin types that inherits from specific interfaces at runtime (plugins can contain types inheriting from multiple plugin interfaces/inheriting from the same interface as other types inside of them), or people who want to create instances of types only known at runtime for other reasons. As such being able to use the activator to instantiate from that enumerable of those specific types that inherit from said interface is the key here.

Let's start with an example of code not using it: https://gist.github.com/AraHaan/bb26620b1098b55e3db57b27588f048a#file-genericpluginloader-cs-L207-L221

That code could easily be simplified to:
```cs
var types = assembly.GetTypes();
if (typeof(T).FullName is null)
{
    PluginLoaderMessage?.Invoke(null, new("Type name cannot be null.", "Error!", ErrorLevel.Error));
}

var instances = Activator.CreateInstances(types.Where(type =>
    !type.IsInterface && !type.IsAbstract &&
    type.GetInterface(typeof(T).FullName!) is not null));
if (!instances.Any())
{
    this.Collect(assembly);
    continue;
}

plugins.AddRange(instances);
```

I find the code just above more readable and simpler as it makes the intent more clear that you want to create instances of every time in the plugin that inherits from a specific interface.

## Alternative Designs

Having the assembly loader be able to create instances of every type inheriting from that interface for me (was later scrapped because no idea if it might break how ``AssemblyLoadContext`` works, I guess an ``AssemblyLoadContext.CreateInstancesFromInterface()`` where it takes in the ``Type`` instance of that interface could be added. But then again it would then have to also try to call the ``Load`` functions instead of the user doing it and that would mean an overload of that function for every overload of ``Load`` that exists in the ``AssemblyLoadContext`` class. But it could be made to *try* to load the assembly into the context instance the function is invoked on, else the default context if it fails with that instance.

But perhaps both this, and this alternative option could be done if both are wanted / needed to simplify things like the code I posted even further.

## Risks

I think there should be low risks with adding this to .NET 6+ since it is a trivial change, I am not sure if it should be added to earlier frameworks (like netstandard2.0 however).

**Comment by GrabYourPitchforks** [comment]
It seems the only significant difference between the "old" an the "new" code is where the call to `Activator.CreateInstance(s)` appears. The code samples otherwise seem nearly identical. Would this API truly add significant value for this scenario?

Additionally, consider: your "old" and "new" code samples have different behavior. Your "new" code sample creates __up to 2__ instances of each type, but it only ever stores a single instance of each type in the plugins list. The "old" code sample only ever creates a single instance of each type.

**Comment by AraHaan** [comment]
I thought it only creates a single instance of each type, then from that filter out the null results.

**Comment by GrabYourPitchforks** [comment]
In your original linked code, consider changing your LINQ expression to the following.

```cs
                            var collection = types.Where(type =>
                                !type.IsInterface && !type.IsAbstract &&
                                type.GetInterface(typeof(T).FullName!) is not null))
                                .Select(Activator.CreateInstance).OfType<T>()ToList();
```

That forces _collection_ to be a singly-evaluated `List<T>`. Then you can call `plugins.AddRange(collection);` later in the function after you've done any special-casing for empty collections.

**Comment by john-h-k** [comment]
Why this method instead of just doing

```cs
yourType.Select(x => Activator.CreateInstance(x)).OfType<object>().ToList();
```

?

**Comment by davidfowl** [comment]
I don't see the value in this new API over the manual code. Also how would it deal with errors? Fail at the first one? Try all and aggregate? Give the user a callback to determine when to skip/handle errors? It seems like this would be be best to write the loop yourself.

**Comment by FilipToth** [comment]
> Why this method instead of just doing
> 
> 
> 
> ```cs
> 
> yourType.Select(x => Activator.CreateInstance(x)).OfType<object>().ToList();
> 
> ```
> 
> 
> 
> ?

I agree this API doesn't bring much value to the user since the user can just do a quick loop and create the instances.

**Comment by tannergooding** [comment]
Going to close this based on the comments/feedback above. It doesn't seem like this API would add much value over the existing alternatives and may end up much more complicated in the long run.
