### ISSUE TITLE
Invalid max_timestamp produced for EventPipe block header in .NET 6 previews

### ISSUE THREAD

**Issue by valco1994** [dotnet/runtime#51468]
As far as I see, EventPipe source code was seriously refactored since .NET 5 release.

Unfortunately, this refactoring introduce the following bug. In `ep-block.c` there is a code updating `min_timestamp` and `max_timestamp` for EventPipe block header. This code should update `min_timestamp` if current event timestamp is less than `min_timestamp` and update `max_timestamp` if current timestamp is more than `max_timestamp`. But currently, `max_timestamp` is updated when current timestamp is less than it, which is impossible, because `max_timestamp` is initialized as `INT64_MIN`. 

https://github.com/dotnet/runtime/blob/236cb21e3c1992c8cee6935ce67e2125ac4687e8/src/native/eventpipe/ep-block.c#L693

So, currently it's
```c
if (event_block_base->min_timestamp > instance_timestamp)
	event_block_base->min_timestamp = instance_timestamp;
if (event_block_base->max_timestamp > instance_timestamp)
	event_block_base->max_timestamp = instance_timestamp;
```
but should be
```c
if (event_block_base->min_timestamp > instance_timestamp)
	event_block_base->min_timestamp = instance_timestamp;
if (event_block_base->max_timestamp < instance_timestamp)
	event_block_base->max_timestamp = instance_timestamp;
```

**Comment by tommcdon** [comment]
@josalem
