### ISSUE TITLE
Use prolog-zero init knowledge in VN to delete branches

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#51472]
The test from @stephentoub:
```
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

class C
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    string M1()
    {
        var b = new S(4);
        return b.Finish();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    string M2()
    {
        var b = S.Create(4);
        return b.Finish();
    }


    public static int Main()
    {
        C c = new C();
        c.M1();
        c.M2();
        return 100;
    }
}

public ref struct S
{
    private object _f1;
    private object _f2;
    private char[] _f3;
    private Span<Char> _f4;
    private int _f5;

    internal S(int i)
    {
        _f1 = null;
        _f2 = null;
        _f3 = null;
        _f4 = _f3;
        _f5 = 0;
    }

    public static S Create(int i) => new S(i);

    public string Finish()
    {
        var s = _f4.ToString();
        this = default;
        return s;
    }
}
```
and we generate such code for M1:
```
IN0011: 000000 push     rsi
IN0012: 000001 sub      rsp, 80
IN0013: 000005 vxorps   xmm4, xmm4
IN0014: 000009 vmovdqa  xmmword ptr [rsp+20H], xmm4
IN0015: 00000F vmovdqa  xmmword ptr [rsp+30H], xmm4 <- [rsp+30H] is 0.
IN0016: 000015 vmovdqa  xmmword ptr [rsp+40H], xmm4

G_M56038_IG02:        ; offs=00001BH, size=000AH, bbWeight=1    PerfScore 2.25, gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref, isz

IN0001: 00001B mov      rcx, gword ptr [V01+0x10 rsp+30H] <-  [rsp+30H] is 0 => rcx is 0.
IN0002: 000020 test     rcx, rcx // rcx is 0 =>the result is 0.
IN0003: 000023 je       SHORT G_M56038_IG06 // won't take the branch
```
IR for it looks like:
```
***** BB01
STMT00011 (IL 0x000...  ???)
N003 (  3,  4) [000054] -A--G---R---              *  ASG       ref    $100
N002 (  1,  1) [000053] D------N----              +--*  LCL_VAR   ref    V03 tmp1         d:2 $100
N001 (  3,  4) [000028] ----G-------              \--*  LCL_FLD   ref    V01 loc0         [+16] Fseq[_f3] $100

***** BB01
STMT00012 (IL 0x000...  ???)
N004 (  5,  5) [000058] ------------              *  JTRUE     void  
N003 (  3,  3) [000057] J------N----              \--*  EQ        int    $180
N001 (  1,  1) [000039] ------------                 +--*  LCL_VAR   ref    V03 tmp1         u:2 $100
N002 (  1,  1) [000056] ------------                 \--*  CNS_INT   ref    null $VN.Null
```

to delete the unreachable code we should be able to teach VN that  `LCL_FLD   ref    V01 loc0         [+16] Fseq[_f3]` has zero value, so it is propagated to V03 and we delete the dead code.

Solving this will make M1 better and also will help us to make code between M1 and M2 closer (now M2 is generating worse code).

cc @AndyAyersMS @dotnet/jit-contrib 

category:cq
theme:value-numbering
skill-level:intermediate
cost:small
impact:small

**Comment by stephentoub** [comment]
> now M2 is generating worse code

Which, just to be clear, is my primary concern :smile:

**Comment by sandreenko** [comment]
> Which, just to be clear, is my primary concern 😄

Does the diff between M1 and M2 assembly add a bigger performance penalty than this extra condition and block?

I will try to fit it into 6.0.

**Comment by stephentoub** [comment]
> Does the diff between M1 and M2 assembly add a bigger performance penalty than this extra condition and block?

Don't know.  I was just highlighting I hadn't noticed the dead code / extra block, and my repro to you was meant to highlight the difference between M1 and M2... you then noticed the other thing.

**Comment by sandreenko** [comment]
the problem is in fgMorphCopyBlock that marks the lclVar as address exposed, it prevents it from being included in VN optimizations. It is not really needed to be marked as such, will be fixed together with other fgMorphCopyBlock changes.

**Comment by JulieLeeMSFT** [comment]
Moving to .NET 8.

**Comment by jakobbotsch** [comment]
`M1` and `M2` have identical codegen in release builds now and there is no unnecessary check in M1.
