### ISSUE TITLE
Add DynamicallyAccessedMemberTypes.Interfaces enum value

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#51487]
## Background and Motivation

Trimming tools (both ILLink and native AOT) remove interfaces if they're not used by the application. This means that APIs like `Type.GetInterfaces` may return a different set of values before and after trimming. The trimming tools will warn about these cases, but currently there's no good way to fix the issue when the code needs to call `Type.GetInterfaces`. For other similar APIs, like `Type.GetMethods` we have the `DynamicallyAccessedMembersAttribute` and the `DynamicallyAccessedMemberTypes.PublicMethods` annotation for example - which tells the trimming tools to preserve public methods on the annotate type.

The proposal is to add a similar mechanism for interfaces as well.

There already is `DynamicallyAccessedMemberTypes.All` annotation which will preserve everything, including interfaces, and so it already acts as a superset of the proposed annotation.

## Proposed API

```diff
namespace System.Diagnostics.CodeAnalysis
{
    enum DynamicallyAccessedMemberTypes
    {
        None = 0,
        PublicParameterlessConstructor = 0x0001,
        PublicConstructors = 0x0002 | PublicParameterlessConstructor,
        NonPublicConstructors = 0x0004,
        PublicMethods = 0x0008,
        NonPublicMethods = 0x0010,
        PublicFields = 0x0020,
        NonPublicFields = 0x0040,
        PublicNestedTypes = 0x0080,
        NonPublicNestedTypes = 0x0100,
        PublicProperties = 0x0200,
        NonPublicProperties = 0x0400,
        PublicEvents = 0x0800,
        NonPublicEvents = 0x1000,
+       Interfaces = 0x2000,
        All = ~None
    }
}
```

## Usage Examples

```C#
IEnumerable<Type> FindCustomInterfaces([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.Interfaces)] type)
{
    foreach (var ifaceType in type.GetInterfaces())
    {
        if (ifaceType.Name.EndsWith("Custom"))
            yield return ifaceType;
    }
}
```

Currently this could would have to use `DynamicallyAccessedMemberTypes.All` annotation which will increase the size of the application more than necessary.

## Risks

None really. Existing code produces warnings or has to use `All`. Adding `Interfaces` is basically a size optimization.

**Comment by jkotas** [comment]
Are there examples of real world code that uses this pattern?

**Comment by vitek-karas** [comment]
@eerhardt will probably have more. For example:
https://github.com/dotnet/aspnetcore/blob/24fe8526e1a378567b673abc28c373c58caea3fd/src/SignalR/common/Shared/ReflectionHelper.cs#L39
https://github.com/dotnet/runtime/blob/ccc47f55554e2ae12e7ec9a07ea19bd4b49e910c/src/libraries/Microsoft.Extensions.Options/src/OptionsServiceCollectionExtensions.cs#L147

I simplified the sample, the most typical is to check presence of a generic interface.

**Comment by jkotas** [comment]
These examples are using `typeof` that should make the linker keep the interface around. This annotation should not be needed for those.

I am specifically curious about a real-world example for the name pattern matching that is in the Usage Example.

**Comment by eerhardt** [comment]
> These examples are using typeof that should make the linker keep the interface around.

When I spoke with @MichalStrehovsky about this pattern, he mentioned https://github.com/dotnet/runtimelab/pull/514 as an example of places where the tooling may strip interfaces. A future optimization example he gave:

```C#
class Foo : IEnumerable<MyStruct> { ... }
```

Where `IEnumerable<MyStruct>` is never used, it should be fair game to remove that interface implementation fully (dropping from interface list and dropping the impl).

But if you pass `typeof(Foo)` into a method like 

https://github.com/dotnet/runtime/blob/82ca681cbac89d813a3ce397e0c665e6c051ed67/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs#L1361-L1373

Dropping the interface from the list would change the behavior of the app.

**Comment by MichalStrehovsky** [comment]
So for NativeAOT-like optimizations that can run the analysis on instantiated types, the thing there is that in the @eerhardt example gave above would either warn because the `MakeGenericType` is problematic for the analysis, or properly analyze the `MakeGenericType`, in which case the thing we `MakeGenericType`'d is likely using the interface and we wouldn't be able to drop it because of that. So the problem ends up being more in theoretical level - if we test for the interface but never actually use it (and I just realized we're not stripping the interfaces in NativeAOT yet, just the methods on the interface, so this is actually fully safe; I would like to drop the interfaces at some point though).

The problem in not-NativeAOT case is the same. If we have reflection that checks for the presence of the interface, but doesn't actually use it for anything (because it was a marker or something like that).

```csharp
public bool IsFooable(Type t) => t.GetInterfaces().Any(i => i.FullName == "IFooable");
```

Here we would definitely strip IFooable with illink. The question is whether it's okay to do it without a warning. Our general stance has been "no".

**Comment by bartonjs** [comment]
* There was some discussion that "Interfaces" was perhaps not the best name, but we couldn't come up with a better one, and since the scope is already "members" we felt it was OK.
```diff
namespace System.Diagnostics.CodeAnalysis
{
    enum DynamicallyAccessedMemberTypes
    {
        None = 0,
        PublicParameterlessConstructor = 0x0001,
        PublicConstructors = 0x0002 | PublicParameterlessConstructor,
        NonPublicConstructors = 0x0004,
        PublicMethods = 0x0008,
        NonPublicMethods = 0x0010,
        PublicFields = 0x0020,
        NonPublicFields = 0x0040,
        PublicNestedTypes = 0x0080,
        NonPublicNestedTypes = 0x0100,
        PublicProperties = 0x0200,
        NonPublicProperties = 0x0400,
        PublicEvents = 0x0800,
        NonPublicEvents = 0x1000,
+       Interfaces = 0x2000,
        All = ~None
    }
}
```
