### ISSUE TITLE
HTTP/3: Unit test variable length encoding

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#51519]
I discovered an issue in the shared variable-length encoding source code - https://github.com/dotnet/runtime/pull/51486

This type doesn't have any unit tests. Some should be added to check there are no further problems.

**Comment by ManickaP** [comment]
Triage: we should have this covered by Unit Tests.

**Comment by karelz** [comment]
Triage: This should be fairly straightforward, we can provide guidance if needed.

**Comment by karelz** [comment]
Great @pedrobsaila, let us know if you need any guidance / tips. Thanks!
