### ISSUE TITLE
Reflection of fields not updated after ApplyUpdate

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#51517]
@mikem8361, @tommcdon, the above will need investigation.  The RuntimeTypeCache is correctly being cleared, and new methods and properties added with ApplyUpdate are correctly showing up via reflection after an update, but fields are not.

_Originally posted by @stephentoub in https://github.com/dotnet/runtime/issues/51242#issuecomment-822103285_

**Comment by jkotas** [comment]
Changing `ApproxFieldDescIterator` to `EncApproxFieldDescIterator` in `RuntimeTypeHandle::GetFields` is a start. There may be more fixes needed beyond that.

**Comment by mikem8361** [comment]
@devsko:

 I tried to verify this fix for my use case with a local build. 
The behavior now is as follows:
- Loaded class with 7 public instance fields
- Adding an 8th public instance field
- Update via EnC and clear cache without any problem
- `type.GetFields()` now returns 
    * 7 original fields
    * 1 new field
    * 3 of the original fields twice (with different field handle)

I found a minimal repro for this. Key is that the class contains a field of type nint or nuint before the edit.

I created https://github.com/devsko/WebApplication1.

dotnet watch it
uncomment the second field in Class1 and
refresh your browser to reproduce.

**Comment by mikem8361** [comment]
I can repro it too once I add an nint field to my test.

**Comment by mikem8361** [comment]
@tmat I found that if one of the original fields is a "nint _field0" and I add a new "int _field1", the delta generated by roslyn "adds" two fields _field0 and _field1. If the original field is just an "int" then the delta generated only adds the new one (int _field1).  I think this may be a problem in roslyn with native ints.

The output of mdv: 
[mdv.txt](https://github.com/dotnet/runtime/files/6367024/mdv.txt)

I'm using a version of @lambdageek's hotreload-utils to generate the delta in my private in my fork [here](https://github.com/mikem8361/hotreload-utils/tree/testing). His utility generates the delta's from base/delta sources driven by a json file script.

Starting (base) test [source](https://github.com/mikem8361/hotreload-utils/blob/testing/src/hotreload-delta-gen/example/TestClass.cs).

Delta test [source]( https://github.com/mikem8361/hotreload-utils/blob/testing/src/hotreload-delta-gen/example/TestClass_v1.cs).

**Comment by mikem8361** [comment]
This is the mdv output when the original field is an "int" ("int _field0"):
[mdv_good.txt](https://github.com/dotnet/runtime/files/6367125/mdv_good.txt)

**Comment by tmat** [comment]
Note that EnC on members involving native integer types might misbehave currently: https://github.com/dotnet/roslyn/issues/48637

**Comment by mikem8361** [comment]
Looks like this issue is covered  with dotnet/roslyn#48637
