### ISSUE TITLE
Rename .dll to a dotnet specific name

### ISSUE THREAD

**Issue by litch0** [dotnet/runtime#51527]
## Background and Motivation
My motivation is very simple, Dlls are, in my view, a system dynamic link library, which means that they are native compiled code from a specific system (on linux they are .so and on osx they are .dylib) but since dotnet compiles to IL instead of native code, I feel like we need to have this difference. In my point of view, It wouldn't be needed to drastically make the change right away, I think it would be better to change in steps and see how the community feel about the new assembly names. Also, not to be mistaken, I don't hate the dll, It would be great to have dotnet accepting dlls and this new name at the same time, to not have to change all library names that are on nuget, for example.

I think the flow of change would look something like:
- Change the compiler output, but still allowing the developer to choose to output a dll with a property group, something like \<OutputDll\>true\<\/OutputDll\>
- Change in the runtime to accept the new assembly name, but still running and loading the older one

## Proposed API
- The change in the compiler to output the new assembly name instead of dll but still allowing the user to chosse if he wants to output dll by introducing a new property group property
- The change in the runtime to load and run the new assembly name assemblies but still loading and running dll assemblies

## Usage Examples
In my view this is just for ease of use or pragmatic design, so i do not have an example of usage  

## Alternative Designs
- .da = dotnet assembly
- .dla = dynamic library assembly
- .dot = dotnet

## Risks
Confusion of the community in the first moment, but with the documentation, the option to output the older name, the workshops and backwards compatibility with the older name, I fell this is not something we need to worry about.

**Comment by jnm2** [comment]
I wonder, does `.netmodule` already work?

**Comment by HaloFour** [comment]
This feels like a conversation that should have (and probably did) taken place 20 years ago.

DLL doesn't imply native code.  Several interpreted languages that predate .NET could be compiled to DLLs, including Visual Basic and Visual FoxPro.  DLL just means dynamically linked, and .NET assemblies are dynamically linked.

**Comment by litch0** [comment]
Ok! Sorry for the late issue.

**Comment by HaloFour** [comment]
I'm just one opinion of many, you don't need to close the issue on my account.  😄 

I was chatting in [Gitter](https://gitter.im/dotnet/csharplang) with others about this and it didn't sound like renaming the extension would work out of the box without tooling (and possibly) runtime support, which would probably make this a harder sell.  I personally wouldn't care if the runtime was entirely agnostic about file extensions, but that doesn't seem to be the case today.  And I would wager that it would be more challenging if trying to target both .NET Framework and .NET Core as I'm certain the former makes even more assumptions.

**Comment by jkotas** [comment]
> I personally wouldn't care if the runtime was entirely agnostic about file extensions, but that doesn't seem to be the case today.

The core runtime is agnostic about file extensions. For example, you can do `Assembly.LoadFile(Path.GetFullPath("test.whatever"));` and it will work just fine.

The extension conventions are 90+% tooling problem. The remaining 10% are assumptions in libraries like https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/DirectoryCatalog.cs#L73 and the few places where these conventions leak into the runtime.

**Comment by davidfowl** [comment]
https://grep.app/search?q=.dll&filter[lang][0]=C%23&filter[repo][0]=dotnet/runtime&filter[path][0]=src/libraries/System.Private.CoreLib/src/System/Runtime/Loader/

There are some fun ones in there
