### ISSUE TITLE
Finalize v1 pattern used by MetadataUpdateHandlers

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#51545]
Code interested in subscribing to hot reload notifications does so by adding an assembly-level attribute, with the attribute naming a type that exposes methods to be called when an update is applied, e.g.
https://github.com/dotnet/runtime/blob/c42d26c2cc12e83d722d1129b29820e207b3d392/src/coreclr/System.Private.CoreLib/src/System/Reflection/Metadata/RuntimeTypeMetadataUpdateHandler.cs#L7

That type exposes a set of methods, found and invoked via reflection, that conform to a pattern.  As of now, that pattern includes two methods that may be implemented:
```C#
static void BeforeUpdate(Type[]? types);
static void AfterUpdate(Type[]? types);
```

We need to finalize what the pattern looks like and update all of the in-box handlers and hot reload agents accordingly.

Known issues today:
- Currently the agent(s) just pass null for types, and most handlers we've implemented don't actually require the type information (some can optimize in certain situations if they're provided).  Do we want to keep the arguments?  Anything else that should be passed in?
- We currently use the BeforeUpdate to clear caches, and the AfterUpdate to refresh UI that might depend on those caches having been cleared.  However, clearing the caches prior to the update being applied isn't ideal, in that if code is running concurrently with the BeforeUpdate/ApplyUpdate/AfterUpdate sequence, that code might cause the cache to be repopulated after BeforeUpdate has cleared it and before the update is applied, resulting in the cache being refreshed to pre-update data.  It would be more robust (even though not 100%) if the caches could be cleared after the update; that way, even if a race condition resulted in some operation being performed after the update but still using pre-updated data, anything that repopulated the cache after it was cleared would do so with post-update information.

cc: @tommcdon, @mikem8361, @StephaneDelcroix, @pranavkm

**Comment by stephentoub** [comment]
Another reason we should look at having an "after" and "after after" event is a case like TypeDescriptor.  We currently hook the BeforeUpdate notification to call TypeDescriptor.Refresh in order to clear caches:
https://github.com/dotnet/runtime/blob/57104c730b7c382a0356e1a683e83d99e3b03d14/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectionCachesUpdateHandler.cs#L15-L37
But that in turn raises the TypeDescriptor.Refreshed event.  That's a good thing, because it means controls like Windows Form's PropertyGrid will automatically rebind.  But we want that rebinding to happen after reflection caches have been cleared, and there's no guarantee right now that's going to happen.

We either need to come up with an ordering system (e.g. where the TypeDescriptor handler can say it depends on the core reflection handler and shouldn't be invoked until after it's completed) or we need a middle layer: BeforeUpdate, AfterUpdate, AfterAfterUpdate (with a better name).

**Comment by jkotas** [comment]
> BeforeUpdate, AfterUpdate, AfterAfterUpdate (with a better name).

This is ordering system with absolute levels. It can be generalized as `AfterUpdateA`, `AfterUpdateB`, `AfterUpdateC`, ... . The agent gets a list of all methods the start with `AfterUpdate, sort them using the suffix, and invoke them in that order (just sharing an idea, I am not attached to it nor consider it particularly great).

Another option is to special case the core reflection handlers in the agent and always invoke them first. It would allow us to get by until we discover more need for ordering. It is probably a good idea to make sure that the core reflection handlers are invoked first in any case.

**Comment by stephentoub** [comment]
> Another option is to special case the core reflection handlers in the agent and always invoke them first.

I was thinking of doing a topological sort by assembly reference, which would achieve that.

**Comment by pranavkm** [comment]
Filling in some details from our offline sync up:

* We think using the topological sort might be a good first start. We can figure out more complex patterns if a need arises.
* We also proposed `ClearCache` and `UpdateApplication` as the two method names for the handlers. Both of these are invoked after a `ApplyDelta` event. A update handler may have either or both of these methods defined.

```C#
static void ClearCache(Type[]? updatedTypes);
static void UpdateApplication(Type[]? updatedTypes);
```

e.g.
```C#
foreach (var delta in deltas)
    ApplyUpdate(...);

foreach (var clearCache in _clearCaches)
    clearCache(updatedTypes);

foreach (var updateApp in _updateApps)
    updateApp(updatedTypes);
```
