### ISSUE TITLE
Commit info is missing from singlefilehost

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#51554]
In .NET 5, singlefilehost binary has commit information:

```sh
$ strings /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/5.0.5/runtimes/linux-x64/native/singlefilehost | \
    grep '@Commit'

@(#)Version 42.42.42.42424 @Commit: 2f740adc1457e8a28c1c072993b66f515977eb51
```
(version is the wrong / default / placeholder value, but at least we have the commit hash)

In .NET6 preview3, that info line is missing:

```sh
$ strings /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.0-preview.3.21201.4/runtimes/linux-x64/native/singlefilehost | \
    grep '@Commit'

# nothing
```

cc @VSadov, @janvorli

**Comment by VSadov** [comment]
I've checked `singlefilehost.exe` 5.0 and `apphost.exe` 5.0 and 3.1. None seems to have versioning information. 

Was that string included only on Unix? 
I wonder if that was intentional, considering the version was incorrect.

**Comment by am11** [comment]
In our hosted apps (singlefilehost)-based in Service Fabric cluster, that is a useful information to convey "which runtime this app was build against" for logging/monitoring purposes in production.
I have only used it on Linux.
Basically it about 10-20 bytes sized single string in a binary of 50K+ strings, so it doesn't hurt really (useful nonetheless). IMO that is. 🙂

**Comment by janvorli** [comment]
> I wonder if that was intentional, considering the version was incorrect.

What do you mean by "incorrect"?

**Comment by VSadov** [comment]
> What do you mean by "incorrect"?

It is literally `@(#)Version 42.42.42.42424 @Commit: 2f740adc1457e8a28c1c072993b66f515977eb51` 

This is a placeholder version, not a real one.

**Comment by janvorli** [comment]
The placeholder is used by all local builds. Only official builds include the real version.

**Comment by VSadov** [comment]
Also, in 3.1 `apphost` contains the following

@(#)Version 3.100.320.12801 @Commit: 4a9f85e9f89d7f686fef2ae2109d876b1e2eed2a

but that is gone in 5.0. 
I do not see any version info in 5.0 apphost

**Comment by VSadov** [comment]
I have a feeling the version info was removed in 5.0, but not completely and singlegilehost on Linux gets its commit sha somehow, while the version is a placeholder (that is - in an official sdk installed from apt-get)

**Comment by janvorli** [comment]
> that is - in an official sdk installed from apt-get

Ah, then that seems like a bug that was missed or if the version was removed intentionally, then I haven't heard about it and I don't understand the reason.

**Comment by vitek-karas** [comment]
I'm pretty sure we have an issue about the dev-only version somewhere, I just can't find it now.

**Comment by janvorli** [comment]
The problem is that even official one is missing the version string, according to Vlad.

**Comment by vitek-karas** [comment]
Yes I understand that - we need to fix it.

**Comment by VSadov** [comment]
It looks like removal of version info from apphost was intentional - https://github.com/dotnet/core-setup/pull/2287

**Comment by VSadov** [comment]
Some reasons why hosts should not be versioned were given in the discussion at https://github.com/dotnet/core-setup/pull/2090#issuecomment-295957715

**Comment by vitek-karas** [comment]
I think we should make it very explicit what we want:
* We WANT - Include the version of the apphost (build number and commit) in the binary - so that I can grep for it. This is to help debug problems - not for end user consumption.
* We DON'T WANT - include version resource on Windows - since that should be the version of the app which we have no control over. (This doesn't have a counterpart on Linux/macOS anyway)
