### ISSUE TITLE
[wasm] Unify BuildWinWasmRuntimes and BuildWasmRuntimes targets

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#51553]
To do that, we need to build the native parts with `cmake` and then unify the targets to one.

**Comment by steveisok** [comment]
@radekdoulik @lewing I'm assuming the 6.0 timeframe as milestone.

**Comment by ilonatommy** [comment]
Fixed with https://github.com/dotnet/runtime/pull/58878.
