### ISSUE TITLE
GetRequiredServices vs GetServices

### ISSUE THREAD

**Issue by qsdfplkj** [dotnet/runtime#51552]
This really confuses me... I have a number of services possibly zero.
I would like to use ServiceProviderServiceExtensions.GetServices but it uses GetRequiredServices internally.
It's really confusing... I would have expected an empty list if it doesn't find any items

Maybe fix this backwards compatible by using a number in GetServices(int minimumNumberOfRequiredServices = 1)

Now I have to write my own in order to get a empty list if no services are available.

**Comment by huoyaoyuan** [comment]
> I would have expected an empty list if it doesn't find any items

`GetServices` does return an empty array if there isn't such service. What are confusing you?

**Comment by MihaZupan** [comment]
It does use `GetRequiredServices` internally, but `GetRequiredService<IEnumerable<T>>`. 

> It's really confusing... I would have expected an empty list if it doesn't find any items

That is what it does.

**Comment by qsdfplkj** [comment]
The confusion is that It throws an exception when nothing is found. And does not return a empty list.

**Comment by huoyaoyuan** [comment]
```csharp
    interface I { }
    class C { }
    class Program
    {
        static void Main(string[] args)
        {
            using var sp = new ServiceCollection()
                .AddSingleton<C>()
                .BuildServiceProvider();

            var services = sp.GetServices<I>();
            Console.WriteLine(services.Count());
        }
    }
```

Outputs 0-and doesn't throw.

**Comment by qsdfplkj** [comment]
> ```cs
>     interface I { }
>     class C { }
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             using var sp = new ServiceCollection()
>                 .AddSingleton<C>()
>                 .BuildServiceProvider();
> 
>             var services = sp.GetServices<I>();
>             Console.WriteLine(services.Count());
>         }
>     }
> ```
> 
> Outputs 0-and doesn't throw.

I should have made this test myself. I've no clue where the exception came from. Maybe the implemented class for the interface required another service that wasn't registered.
