### ISSUE TITLE
System.Security.Cryptography libraries should conform to interop guidelines

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#51564]
The following list of directories do not conform to the [interop guidelines](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/interop-guidelines.md):

* https://github.com/dotnet/runtime/tree/main/src/libraries/System.Security.Cryptography.Pkcs/src/Interop
* https://github.com/dotnet/runtime/tree/main/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/Native

 Specifically, the [file organization section](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/interop-guidelines.md#file-organization) states that all `Interop.*.cs` files should all be defined in the [Common](https://github.com/dotnet/runtime/tree/main/src/libraries/Common/src/Interop) directory.  Conforming to the guidelines and having a standardized way of defining native interop supports the work for being able to [track and detect platform dependencies](https://github.com/dotnet/core/issues/5648).

**Comment by vcsjones** [comment]
Related / similar issue: https://github.com/dotnet/runtime/issues/26541

**Comment by pedrobsaila** [comment]
Hi.
I made a first PR for this issue #59913. If it's OK with you, I will try to make small PRs for System.Security.Cryptography.X509Certificates since there are 51 Interop references inside it.

**Comment by danmoseley** [comment]
@pedrobsaila I've assigned this to you ,thanks!

**Comment by bartonjs** [comment]
A current scan for `LibraryImport` or `DllImport` in the cryptography projects shows nothing outside of src\Common\src\Interop (for product code, tests have a couple)
