### ISSUE TITLE
[Blazor WASM] - Investigate 8% size regression in System.Memory.dll.br

### ISSUE THREAD

**Issue by SamMonoRT** [dotnet/runtime#51571]
Size increase for System.Memory.dll.br as observed from https://msit.powerbi.com/groups/me/apps/54e0e83f-07bc-45bf-87b7-a7677ff3af2a/dashboards/fa051820-ff60-4d40-8a08-bdcc1b47b1d0

![image](https://user-images.githubusercontent.com/46026722/115443926-e369b000-a1e1-11eb-8570-da16818143df.png)

cc @CoffeeFlux

**Comment by GrabYourPitchforks** [comment]
@SamMonoRT Do you have the raw files on disk for the before and after images? That would definitely help investigation, since we could look at the entire call graph and see if the regression was due to code within _System.Memory_ or is due to changes in one of its callers.

**Comment by SamMonoRT** [comment]
I don't have that information. I just saw an auto-filled issue by @DrewScoggins which has some more information : https://github.com/DrewScoggins/performance-2/issues/5087

**Comment by DrewScoggins** [comment]
Do you need the trimmed files or the actual full binaries from the NETCore.App package?

**Comment by DrewScoggins** [comment]
I will also copy over the full contents of the auto-filed issues, as it contains a few other dlls that have small regressions as well.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [7fa839a727e510f2b1b104eafb2c1fb339249756.](https://github.com/dotnet/runtime/commit/7fa839a727e510f2b1b104eafb2c1fb339249756)
Compare | [ee0719079c4c4540f5adb135f002ad3ecf6c25ea](https://github.com/dotnet/runtime/commit/ee0719079c4c4540f5adb135f002ad3ecf6c25ea)
Diff | [Diff](https://github.com/dotnet/runtime/compare/7fa839a727e510f2b1b104eafb2c1fb339249756...ee0719079c4c4540f5adb135f002ad3ecf6c25ea)


### Regressions in SOD - New Blazor Template - Publish

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Collections.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 22.00 KB | 23.50 KB | 1.07 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 79.08 KB | 83.19 KB | 1.05 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Memory.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 17.50 KB | 19.00 KB | 1.09 | | |
[SOD - New Blazor Template - Publish - Aggregate - .dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 2.09 MB | 2.12 MB | 1.01 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 240.50 KB | 253.00 KB | 1.05 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Collections.Concurrent.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 17.00 KB | 17.50 KB | 1.03 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Collections.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 9.79 KB | 10.45 KB | 1.07 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.ObjectModel.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 2.74 KB | 2.77 KB | 1.01 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Memory.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 8.59 KB | 9.26 KB | 1.08 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 92.47 KB | 97.24 KB | 1.05 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Memory.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 7.72 KB | 8.26 KB | 1.07 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Collections.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 8.82 KB | 9.38 KB | 1.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_401.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_402.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_403.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_404.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_405.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_406.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_407.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_408.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_409.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_410.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_411.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_412.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - New Blazor Template - Publish*'
```
<details>

### Histogram
#### SOD - New Blazor Template - Publish

```log

```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by GrabYourPitchforks** [comment]
The files after trimming but before compression would be best. That way I can plug the whole mess through ilspy and see what changed.

**Comment by DrewScoggins** [comment]
[Basline](https://pvscmdupload.blob.core.windows.net/drewtest/System.Memory.Baseline.dll)
[Comapre](https://pvscmdupload.blob.core.windows.net/drewtest/System.Memory.Compare.dll)

**Comment by DrewScoggins** [comment]
I am also going to make a change so that these artifacts are preserved by Helix, as reproducing them took me about 30 minutes.

**Comment by GrabYourPitchforks** [comment]
Sorry, I should clarify: I need _all_ files, not just System.Memory.dll. Otherwise I can't go back in the call graph.

**Comment by DrewScoggins** [comment]
Oh, sorry about that. Here is what you need.

[Baseline](https://pvscmdupload.blob.core.windows.net/drewtest/Baseline.zip)
[Compare](https://pvscmdupload.blob.core.windows.net/drewtest/Compare.zip)

**Comment by GrabYourPitchforks** [comment]
The trimmed _compare_ file graph contains lots of code to support `ArrayBufferWriter<T>` - this code wasn't in the trimmed _baseline_ graph. I'm still trying to track down who is calling this.

![image](https://user-images.githubusercontent.com/1746272/115481285-26874b80-a201-11eb-92ea-3721a64ac37c.png)

**Comment by GrabYourPitchforks** [comment]
My best guess is that this is a consequence of https://github.com/dotnet/runtime/pull/51025. The JSON stack now has direct dependencies to `JsonNode` which can't be trimmed away, and `JsonNode` itself has direct dependencies to `ArrayBufferWriter<T>` which can't be trimmed away.

**Comment by layomia** [comment]
Related to https://github.com/dotnet/runtime/issues/51311.

> The JSON stack now has direct dependencies to JsonNode which can't be trimmed away

FWIW the node types can't be trimmed away today because it is rooted by these [converters](https://github.com/dotnet/runtime/tree/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Node) which are in turn rooted by [this logic](https://github.com/dotnet/runtime/blob/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L38), which happens when [existing](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer?view=net-5.0) `JsonSerializerOptions`-based methods of `JsonSerializer` are used. When Blazor is updated to use new metadata-based APIs on `JsonSerializer` (https://github.com/dotnet/aspnetcore/issues/31877), I expect that these converters will be trimmed out if not needed by the application.

---

cc @steveharter on thoughts on whether we can minimize the dependency on `ArrayBufferWriter<T>` for apps that use the node feature.

**Comment by steveharter** [comment]
We can change the implementation to use `PooledByteBufferWriter` instead. That is what the non-Stream paths use today (the Stream paths use `ArrayBufferWriter<T>`.

**Comment by SamMonoRT** [comment]
Thanks for the quick change, resulted in decrease in size : 

![image](https://user-images.githubusercontent.com/46026722/116409453-db24fc80-a801-11eb-85c0-8dc46f2366fd.png)
