### ISSUE TITLE
[3.1] Deadlock during EventPipe session stop

### ISSUE THREAD

**Issue by sywhang** [dotnet/runtime#51579]
@xiaomi7732 reported this from a long-running Service Profiler session.

When an EventPipe session is stopped, it tries to walk through all EventPipeThread that are still writing and wait for them to finish in this YIELD_WHILE:
```cpp
    {
        SpinLockHolder _slh(&m_lock);
        SListElem<EventPipeThreadSessionState *> *pElem = m_pThreadSessionStateList->GetHead();
        while (pElem != NULL)
        {
            // Get the list and remove it from the thread.
            EventPipeBufferList *const pBufferList = pElem->GetValue()->GetBufferList();
            if (pBufferList != nullptr)
            {
                EventPipeThread *const pEventPipeThread = pBufferList->GetThread();
                if (pEventPipeThread != nullptr)
                {
                    YIELD_WHILE(pEventPipeThread->GetSessionWriteInProgress() == sessionIndex);
```

But it is possible for a deadlock to occur when one of such thread tries to allocate a new buffer and tries to take the EventPipeBufferManager lock. (`m_lock` in code above)

Specifically, the order of events that cause this to occur is as follows with the chronological order of events in parenthesis:

Thread 1: SetSessionWriteInProgress(1) -> WriteEvent (2) -> AllocateBufferForThread (5) [blocked on m_lock]
Thread 2: SuspendWriteEvent(3) -> SuspendWriteEvent(4) [blocked on YIELD_WHILE on SessionWriteInProgress]

This repros all the way to 3.1, so we'll need a backport to 5.0 and 3.1. 

[EDIT] https://github.com/dotnet/runtime/commit/c6d1756b69ee34cb96376fedc7a72b56975fd9ba fixed it in 5.0 actually. We only need to fix it on 3.1 

cc @josalem @noahfalk

**Comment by sywhang** [comment]
A potential fix has been shared with service profiler team for verification. Will update once I hear back

**Comment by polage-tr** [comment]
Hi guys,

Is there any progress in the subject of fixing the issue? when is it expected to be released? in which version?

**Comment by josalem** [comment]
@polage-tr, the engineer who was investigating this has since left the team, but I've adopted his issues. He left a draft PR to fix this which I'm intending to polish up. Due to a backlog of other issues, I haven't made it to this one yet, but it's getting near the top of my stack. This issue will get updated once there is more news.

**Comment by josalem** [comment]
Moving out of the 6 milestone for better bookkeeping since this is a 3.1 backport only change that doesn't affect 6.

**Comment by kevingosse** [comment]
I just ran into this (well, we've been running into it for a while, but I only just managed to track it down to this issue). Are there still plans for a 3.1 backport?

**Comment by josalem** [comment]
@kevingosse I've been looping back on stuff I missed while I was on leave recently. Would you be able to validate the changes in dotnet/coreclr#28229? There is a patch, but without validation, I'm hesitant to attempt to merge it into servicing and I can't seem to repro this locally.
