### ISSUE TITLE
Test System.ComponentModel.Tests.ReflectionCachesUpdateHandlerTests.ReflectionCachesUpdateHandler_CachesCleared is failing on mono OSX x64

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#51588]
## System.ComponentModel.Tests.ReflectionCachesUpdateHandlerTests.ReflectionCachesUpdateHandler_CachesCleared
This test was added in #51466 and it is failing on mono OSX x64.

### Console Log Summary

```
  Discovering: System.ComponentModel.TypeConverter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.TypeConverter.Tests (found 1371 of 1372 test cases)
  Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 12)
    System.ComponentModel.Tests.ReflectionCachesUpdateHandlerTests.ReflectionCachesUpdateHandler_CachesCleared [FAIL]
      System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs(1471,0): at System.Collections.Hashtable.HashtableEnumerator.MoveNext()
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs(843,0): at System.ComponentModel.ReflectTypeDescriptionProvider.GetPopulatedTypes(Module module)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(2352,0): at System.ComponentModel.TypeDescriptor.Refresh(Module module)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs(2392,0): at System.ComponentModel.TypeDescriptor.Refresh(Assembly assembly)
        /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectionCachesUpdateHandler.cs(34,0): at System.ComponentModel.ReflectionCachesUpdateHandler.BeforeUpdate(Type[] types)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.ComponentModel.TypeConverter.Tests
=== TEST EXECUTION SUMMARY ===
   System.ComponentModel.TypeConverter.Tests  Total: 7747, Errors: 0, Failed: 1, Skipped: 0, Time: 1.659s
```

### Configurations

* net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open

### Builds

| Build | Pull Request |
|-------|---------------|
| [1098117](https://dev.azure.com/dnceng/public/_build/results?buildId=1098117) | #51575 |
| [1098170](https://dev.azure.com/dnceng/public/_build/results?buildId=1098170) | #51550 |

/cc @stephentoub

Runfo Tracking Issue: [Test reflectioncachesupdatehandlertests.reflectioncachesupdatehandler_cachescleared failed](https://runfo.azurewebsites.net/tracking/issue/138)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1099152](https://dev.azure.com/dnceng/public/_build/results?buildId=1099152)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51589](https://github.com/dotnet/runtime/pull/51589)|net6.0-OSX-Debug-x64-CoreCLR_release-OSX.1015.Amd64.Open|
|[1099152](https://dev.azure.com/dnceng/public/_build/results?buildId=1099152)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51589](https://github.com/dotnet/runtime/pull/51589)|net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|
|[1099089](https://dev.azure.com/dnceng/public/_build/results?buildId=1099089)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48226](https://github.com/dotnet/runtime/pull/48226)|net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|
|[1099089](https://dev.azure.com/dnceng/public/_build/results?buildId=1099089)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 48226](https://github.com/dotnet/runtime/pull/48226)|net6.0-Linux-Debug-x64-Mono_release-Ubuntu.1604.Amd64.Open|
|[1099030](https://dev.azure.com/dnceng/public/_build/results?buildId=1099030)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51604](https://github.com/dotnet/runtime/pull/51604)|net6.0-Linux-Debug-arm64-Mono_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673|
|[1098811](https://dev.azure.com/dnceng/public/_build/results?buildId=1098811)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51530](https://github.com/dotnet/runtime/pull/51530)|net6.0-Linux-Debug-x64-Mono_release-Ubuntu.1804.Amd64.Open|
|[1098811](https://dev.azure.com/dnceng/public/_build/results?buildId=1098811)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51530](https://github.com/dotnet/runtime/pull/51530)|net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|
|[1098690](https://dev.azure.com/dnceng/public/_build/results?buildId=1098690)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51505](https://github.com/dotnet/runtime/pull/51505)|net6.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.312.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e|
|[1098170](https://dev.azure.com/dnceng/public/_build/results?buildId=1098170)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51550](https://github.com/dotnet/runtime/pull/51550)|net6.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|
|[1098117](https://dev.azure.com/dnceng/public/_build/results?buildId=1098117)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51575](https://github.com/dotnet/runtime/pull/51575)|net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|
|[1098089](https://dev.azure.com/dnceng/public/_build/results?buildId=1098089)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 51528](https://github.com/dotnet/runtime/pull/51528)|net6.0-OSX-Debug-x64-CoreCLR_checked-OSX.1013.Amd64.Open|
|[1098051](https://dev.azure.com/dnceng/public/_build/results?buildId=1098051)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-Mono_release-Debian.9.Amd64.Open|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|9|9|9|

**Comment by jeffhandley** [comment]
https://runfo.azurewebsites.net/search/tests/?q=definition%3Aruntime+name%3A%22system.componentmodel.tests.reflectioncachesupdatehandlertests.reflectioncachesupdatehandler_cachescleared%22

**Comment by VincentBu** [comment]
Failed again in [runtime 20210420.45](https://dev.azure.com/dnceng/public/_build/results?buildId=1098051&view=ms.vss-test-web.build-test-results-tab&runId=33590058&resultId=114101&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-Mono_release-Debian.9.Amd64.Open
 -System.ComponentModel.Tests.ReflectionCachesUpdateHandlerTests.ReflectionCachesUpdateHandler_CachesCleared
```

**Error message:**
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.


Stack trace
   at System.Collections.Hashtable.HashtableEnumerator.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs:line 1471
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetPopulatedTypes(Module module) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs:line 843
   at System.ComponentModel.TypeDescriptor.Refresh(Module module) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 2352
   at System.ComponentModel.TypeDescriptor.Refresh(Assembly assembly) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs:line 2392
   at System.ComponentModel.ReflectionCachesUpdateHandler.BeforeUpdate(Type[] types) in /_/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectionCachesUpdateHandler.cs:line 34
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
```

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/51618 is the root cause. https://github.com/dotnet/runtime/pull/51621 has a fix.
