### ISSUE TITLE
On macOS, Process.Dispose() doesn't kill the process

### ISSUE THREAD

**Issue by SteveL-MSFT** [dotnet/runtime#51594]
### Description

In PowerShell, when there is a problem in a pipeline, we use Process.Dispose() to clean up any remaining processes that is part of the pipeline.  We recently noticed that on macOS, those processes aren't actually killed.  This doesn't repro on Linux where the processes are properly killed.

```csharp
using System;
using System.Diagnostics;
using System.Threading;

namespace processdispose
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("yes running: {0}", Process.GetProcessesByName("yes").Length);
            var psi = new ProcessStartInfo();
            psi.FileName = "/usr/bin/yes";
            psi.RedirectStandardOutput = true;
            var y = Process.Start(psi);
            y.Dispose();
            Thread.Sleep(250);
            Console.WriteLine("yes running: {0}", Process.GetProcessesByName("yes").Length);
        }
    }
}
```

Expected: same number of `yes` processes before and after

Actual: the newly created `yes` process is still running after `Dispose()` is called and waiting some time for cleanup.  If you check, the `yes` process is still running after this program finishes.

### Configuration

macOS 11.2.3
.NET 5.0 or .NET 6.0-preview3

### Regression?

Don't know

**Comment by stephentoub** [comment]
Process.Dispose doesn't kill the process on any platform. It will close std redirection handles/file descriptors, so maybe that causes the target process to behave differently, but it doesn't kill it.

**Comment by SteveL-MSFT** [comment]
I see.  That makes sense then.  Seems like Linux and Windows is doing something different from macOS.  In this case, we'll update our code to kill those processes then since that is the intent.  Thanks.

**Comment by stephentoub** [comment]
Sounds good.  Thanks.
