### ISSUE TITLE
Question: how to generate a .pem file with private key from an X509Certificate2?

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#51597]
### Description
May I know if there is any way to generate a .pem file with private key from an X509Certificate2?
I tried the following:
1.Create a self-issued X509Certificate2 certificate(cert) with private key (the key generation algorithm is RSA ), saved as attached file. 
```
byte[] certbytes = cert.Export(X509ContentType.Pfx, "password"); 
File.WriteAllBytes(path, certbytes);
```
2.Wrote a console to:
1).Read the bytes, create an X509Certificate2 cert, Set a password to protect the cert.
2).Try to get the certificate, public key, private key to create a .pem file.
```
string path = "c:\\work\\0420\\cert";
            byte[] certbytes = File.ReadAllBytes(path);

            string password = "password";
            X509Certificate2 certWithPrivateKey = new X509Certificate2(certbytes, password, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);

            byte[] certificateBytes = certWithPrivateKey.RawData;
            char[] certificatePem = PemEncoding.Write("CERTIFICATE", certificateBytes);

            using (AsymmetricAlgorithm key = certWithPrivateKey.GetRSAPrivateKey())
            {
                byte[] pubKeyBytes = key.ExportSubjectPublicKeyInfo();
                char[] pubKeyPem = PemEncoding.Write("PUBLIC KEY", pubKeyBytes);

                byte[] encryptedPrivKeyBytes = key.ExportEncryptedPkcs8PrivateKey(
                    password,
                    new PbeParameters(
                        PbeEncryptionAlgorithm.Aes256Cbc,
                        HashAlgorithmName.SHA256,
                        iterationCount: 100_000));
                char[] privKeyPem = PemEncoding.Write("PRIVATE KEY", encryptedPrivKeyBytes);
            }
```
I could see non empty char arrays for above certificatePem, pubKeyPem and privKeyPem. But I'm not sure how to combine them into a .pem file.
I tried to convert them into string and concatenate them, but the .pem file generated in this way failed to be used in CreateFromEncryptedPemFile as CryptographicException as following:
`cert = X509Certificate2.CreateFromEncryptedPemFile(options.CertificatePath, options.CertificatePassword)`
The exception details is:
![image](https://user-images.githubusercontent.com/45407901/115474285-fedcb700-a1f1-11eb-9ec5-b00c3da32982.png)

I'm wondering if you know how to generate a .pem file with private key (with or without password) from an X509Certificate2 cert? Thanks!

Attached is the cert file from step1.
[cert.zip](https://github.com/dotnet/runtime/files/6347087/cert.zip)

**Comment by vcsjones** [comment]
You should be able to do something like this:

```csharp
string certPem = new string(PemEncoding.Write("CERTIFICATE", cert.RawData));
string keyPem;

if (cert.GetRSAPrivateKey() is RSA rsaKey)
{
    keyPem = new string(PemEncoding.Write("PRIVATE KEY", rsaKey.ExportPkcs8PrivateKey()));
}
else if (cert.GetECDsaPrivateKey() is ECDsa ecdsaKey)
{
    keyPem = new string(PemEncoding.Write("PRIVATE KEY", ecdsaKey.ExportPkcs8PrivateKey()));
}
else if (cert.GetDSAPrivateKey() is DSA dsaKey)
{
    keyPem = new string(PemEncoding.Write("PRIVATE KEY", dsaKey.ExportPkcs8PrivateKey()));
}
else
{
    throw new CryptographicException("Unknown certificate algorithm");
}

Console.WriteLine(certPem);
Console.WriteLine(keyPem);

var certAgain = X509Certificate2.CreateFromPem(certPem, keyPem);
```

That will export the private key in to a PEM-encoded PKCS8 private key.

**Comment by vcsjones** [comment]
If you want to use `ExportEncryptedPkcs8PrivateKey` then the PEM label would be ENCRYPTED PRIVATE KEY:

```csharp
PbeParameters pbe = new PbeParameters(PbeEncryptionAlgorithm.Aes128Cbc, HashAlgorithmName.SHA256, 600_000);
var certPem = new string(PemEncoding.Write("CERTIFICATE", cert.RawData));
string keyPem;

if (cert.GetECDsaPrivateKey() is ECDsa ecdsaKey)
{
    keyPem = new string(PemEncoding.Write("ENCRYPTED PRIVATE KEY", ecdsaKey.ExportEncryptedPkcs8PrivateKey("test", pbe)));
}
else if (cert.GetRSAPrivateKey() is RSA rsaKey)
{
    keyPem = new string(PemEncoding.Write("ENCRYPTED PRIVATE KEY", rsaKey.ExportEncryptedPkcs8PrivateKey("test", pbe)));
}
else if (cert.GetDSAPrivateKey() is DSA dsaKey)
{
    keyPem = new string(PemEncoding.Write("ENCRYPTED PRIVATE KEY", dsaKey.ExportEncryptedPkcs8PrivateKey("test", pbe)));
}
else
{
    throw new CryptographicException("Unknown certificate algorithm");
}

Console.WriteLine(certPem);
Console.WriteLine(keyPem);

var certAgain = X509Certificate2.CreateFromEncryptedPem(certPem, keyPem, "test");
```

**Comment by vcsjones** [comment]
And finally, if you want to "combine" them, one more example:

```csharp
string aggregatePem = certPem + "\n" + keyPem;

var certAgain = X509Certificate2.CreateFromPem(aggregatePem, aggregatePem);
```

Or if you write the combined contents to a file:

```csharp
string aggregatePem = certPem + "\n" + keyPem;
File.WriteAllText("combined.pem", aggregatePem);

var certAgain = X509Certificate2.CreateFromPemFile("combined.pem");
```

And for encrypted private key PEMs it would be the same but using the `Encrypted` versions of the appropriate methods.

**Comment by heng-liu** [comment]
Thanks a lot for your help! @vcsjones
I tried the one with password and it worked :)

**Comment by davidfowl** [comment]
@vcsjones This feels like recipe we should document somewhere

**Comment by vcsjones** [comment]
> This feels like recipe we should document somewhere

Yeah. Part of me is wondering though if there is a quality-of-life API that's missing. Something like:

```csharp
public class X509Certificate2 {
    public string ExportCertificatePem();
    public bool TryExportCertificatePem(Span<char> buffer, out int bytesWritten);
}

public class AsymmetricAlgorithm {
    public string ExportPkcs8PrivateKeyPem();
    public bool TryExportPkcs8PrivateKeyPem(Span<char> buffer, out int bytesWritten);
    public string TryExportEncryptedPkcs8PrivateKeyPem();
    public bool TryExportEncryptedPkcs8PrivateKeyPem(Span<char> buffer, out int bytesWritten);
}
```

Maybe @bartonjs has more thoughts on this.

**Comment by bartonjs** [comment]
The original question has been answered, and the "maybe there's room for improvement" is an API proposal, so I don't think anything's left from this issue.
