### ISSUE TITLE
Question: Is coreclr's use of SIMD-accelerated initobj legal for ref types T?

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#51638]
This is extracted out of a discussion whose salient points are https://github.com/dotnet/runtime/pull/51534#issuecomment-823856835 and https://github.com/dotnet/runtime/pull/51534#issuecomment-824182239.

In a nutshell, when the JIT sees an _initobj_ instruction, it will attempt to perform SIMD writes to the destination address, This is true whether or not the target type contains gcrefs. See the below example for a demonstration.

```cs
using System;

public class C {
    internal struct MyStruct
    {
        object _data0;
        object _data1;
    }
    
    internal class MyClass1
    {
        MyStruct _s;
        
        void Clear()
        {
            _s = default;
        }
    }
    
    internal class MyClass2
    {
        object _dataX;
        MyStruct _s;
        
        void Clear()
        {
            _s = default;
        }
    }
}
```

```asm
; Core CLR v5.0.421.11614 on amd64

MyClass1.Clear()
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu [rcx+8], xmm0
    L000c: ret

MyClass2.Clear()
    L0000: vzeroupper
    L0003: vxorps xmm0, xmm0, xmm0
    L0007: vmovdqu [rcx+0x10], xmm0
    L000c: ret
```

In this example, references to `MyStruct` are only guaranteed 8-byte aligned, _not_ 16-byte aligned. So it's possible that the _vmovdqu_ instruction could straddle a cache line boundary or a page boundary. The implicit assumption here is that even if the SIMD write as a whole is not atomic, each individual native word-sized element of the vector is published atomically (since the target address is native word-aligned).

Per https://github.com/dotnet/runtime/pull/51534#discussion_r616875863, this assumption is valid for ARM64. But per https://github.com/dotnet/runtime/pull/51534#issuecomment-823856835, this assumption might not be valid for x86 / x64 / ARM32.

So, the larger question: is the current JIT behavior legal such that no other thread will ever see a torn write to a gcref field, or is the JIT relying on undocumented behavior? And if we're relying on a potentially invalid assumption, do we need to change our behavior?

**Comment by tannergooding** [comment]
Notably Intel documents the following in "Volume 3A. 8.1.1 Guaranteed Atomic Operations"

![image](https://user-images.githubusercontent.com/10487869/115622672-0319da80-a2ad-11eb-97a7-d5fce52eb854.png)

AMD likewise documents in "Volume 1. 3.9.1.3 Atomicity of accesses"
![image](https://user-images.githubusercontent.com/10487869/115623004-758aba80-a2ad-11eb-92e3-247dc05b4242.png)

**Comment by JulieLeeMSFT** [comment]
@echesakovMSFT PTAL.

**Comment by echesakovMSFT** [comment]
I will investigate
