### ISSUE TITLE
[Perf] Blazor Wasm - Size Regression in System.Net.Http.Json.dll

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#51636]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [466deef23436fd8705db5ebaa6d719c3fa153766](https://github.com/dotnet/runtime/commit/466deef23436fd8705db5ebaa6d719c3fa153766)
Compare | [8c3180d932146b1a76600601c03082c6a81e1a53](https://github.com/dotnet/runtime/commit/8c3180d932146b1a76600601c03082c6a81e1a53)
Diff | [Diff](https://github.com/dotnet/runtime/compare/466deef23436fd8705db5ebaa6d719c3fa153766...8c3180d932146b1a76600601c03082c6a81e1a53)

### Regressions in SOD - New Blazor Template - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Net.Http.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 4.65 KB | 4.93 KB | 1.06 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Linq.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 9.56 KB | 9.65 KB | 1.01 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Net.Http.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 10.50 KB | 11.00 KB | 1.05 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Net.Http.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 4.17 KB | 4.42 KB | 1.06 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_4.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_21_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>)

<details>

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
@SamMonoRT

**Comment by SamMonoRT** [comment]
cc @CoffeeFlux @eerhardt @layomia

**Comment by eerhardt** [comment]
Looks to be https://github.com/dotnet/runtime/pull/51528. Why these new APIs aren't getting trimmed, I don't know.

**Comment by eiriktsarpalis** [comment]
@DrewScoggins how can I get more recent readings on individual file sizes? Links [like this one](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html) seem to only report aggregate sizes.

**Comment by steveharter** [comment]
I can't seem to repro. When I create a project that use other methods in S.N.H.Json.dll and publish\trim it, the new extensions (e.g.`GetFromJsonAsync(JsonSerializerContext)`) are not present in the `HttpClientJsonExtensions` static class.

Closing until we have a repro or more information on how to create a repro.
