### ISSUE TITLE
How to access environ from linux

### ISSUE THREAD

**Issue by markcanary** [dotnet/runtime#51647]
I am using a library (https://github.com/microsoft/vs-pty.net) that tries to get the linux envrion variable using the following p/invoke. 

It get this error: "Unable to find an entry point named 'SystemNative_GetEnviron' in shared library 'System.Native'."

```
[DllImport("System.Native", EntryPoint = "SystemNative_GetEnviron", SetLastError = true)]
internal static extern IntPtr GetEnviron();
```

No one is responding from the vs-pty.net project. Can anyone here help me figure out a solution to this?

**Comment by stephentoub** [comment]
Can you just use `Environment.GetEnvironmentVariable(string)`?

**Comment by markcanary** [comment]
> 
> 
> Can you just use `Environment.GetEnvironmentVariable(string)`? `System.Native.so` is an implementation detail of the runtime; it is not meant to be a stable public API, and can/does change.

The purpose of the Pty.Net project is to create a pseudo terminal for a command-line shell in Windows or Linux. I am trying to get the Linux part to work. Part of the process of doing this is the ability to inject user defined environment variables into the new shell process. This is a standard way of doing this in Linux native C code using the environ variable that is defined here (https://man7.org/linux/man-pages/man7/environ.7.html).

Below is the code from the library. It is trying to add the user environment variables to this pointer to an array of pointers so it will get inherited for the forked process. But this throws an exception when it tries to call the GetEnviron() method as I stated above.

```
IntPtr ppEnv = GetEnviron();
int offset = 0;
foreach (var kvp in environment)
{
     IntPtr pEnv = Marshal.StringToHGlobalAnsi($"{kvp.Key}={kvp.Value}");
     Marshal.WriteIntPtr(ppEnv, offset, pEnv);
     offset += SizeOfIntPtr;
}

Marshal.WriteIntPtr(ppEnv, offset, IntPtr.Zero);
```

I tried substituting the code below but that does not get the variables passed to the new process.

```
foreach (var environmentVariable in environment)
{
    Environment.SetEnvironmentVariable(environmentVariable.Key, environmentVariable.Value);
}

```
I would love a ".NET and won't break" way of doing this, but I haven't figured it out yet. Any suggestions?

**Comment by stephentoub** [comment]
> I tried substituting the code below but that does not get the variables passed to the new process.

What's launching the child process?  If it's Process.Start, it should pick up such calls to SetEnvironmentVariable.  If not, it likely won't.  The runtime loads all environment variables at startup and then all use of Environment.Get/SetEnvironmentVariable is on that copy, because getenv/setenv are not thread-safe.

If you must use setenv even with the thread-safety concerns, you can try P/Invoking to it, e.g.
```C#
[DllImport("libc")]
int setenv(string name, string value, int overwrite);
```

**Comment by markcanary** [comment]
The process cannot be launched using Process.Start because this is all standard Linux pseudo terminal (pty) stuff. The process is launched with a P/Invoke to execvp. I'll try your suggestion to use setenv and see if that works.

```
if (execvp(file, args) == -1)
{
    Environment.Exit(Marshal.GetLastWin32Error());
}
else
{
    // Unreachable
    Environment.Exit(-1);
}

[DllImport(LibSystem, SetLastError = true)]
private static extern int execvp(
    [MarshalAs(UnmanagedType.LPStr)] string file,
    [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPStr)] string?[] args);
```

**Comment by danmoseley** [comment]
Note that we do not support direct calls to our libraries native PAL which includes System.Native. Essentially: the API can change at any time. That is why you need to either use public managed API or call into the platform directly such as glibc.

**Comment by markcanary** [comment]
Good news! Calling setenv worked! I don't think there will be any thread issues in this use case. Below is the code that I am now using that works. I need to create a pull request for the vs-Pty.Net project though I am not hopeful that it will ever get approved and completed. The project seems fairly stale. My issue that I created 2 weeks ago about this issue has not been responded to. But the project does exactly what I was looking for.

Thanks for the assistance!

```c#
internal static void execvpe(string file, string?[] args, IDictionary<string, string> environment)
{
    // Set environment
    foreach (var environmentVariable in environment)
    {
        setenv(environmentVariable.Key, environmentVariable.Value, 1);
    }

    if (execvp(file, args) == -1)
    {
        Environment.Exit(Marshal.GetLastWin32Error());
    }
    else
    {
        // Unreachable
        Environment.Exit(-1);
    }
}

```
