### ISSUE TITLE
When Process.WaitForExitCore(int milliseconds) waits successfully, the redirected output streams miss some data

### ISSUE THREAD

**Issue by fandrei** [dotnet/runtime#51641]
### Description

When the following code executes, the output of the child processes doesn't return full text sometimes, even though all the WaitForExitCore(int milliseconds) calls finish successfully, i.e. no timeout happens. The expected behavior in this case is same as when calling WaitForExitCore() without the timeout arg.
```
	class Program
	{
		static void Main()
		{
			for (var i = 0; i < 1000; i++)
			{
				var res = RunTest();
				if (res.Trim() != "TEST")
					Debugger.Break(); // should never break here
			}

			Debugger.Break();
		}

		static string RunTest()
		{
			var info = new ProcessStartInfo(CmdPath, " /C echo TEST")
			{
				CreateNoWindow = true,
				UseShellExecute = false,
				RedirectStandardInput = true,
				RedirectStandardOutput = true,
				RedirectStandardError = true,
			};

			var process = Process.Start(info);

			var sync = new object();
			var buf = new StringBuilder();

			process.OutputDataReceived +=
				(_, args) =>
				{
					Thread.Sleep(1);
					lock (sync)
					{
						buf.AppendLine(args.Data);
						Trace.WriteLine(args.Data);
					}
				};
			process.BeginOutputReadLine();

			process.ErrorDataReceived +=
				(_, args) =>
				{
					Thread.Sleep(1);
					lock (sync)
					{
						buf.AppendLine(args.Data);
						Trace.WriteLine(args.Data);
					}
				};
			process.BeginErrorReadLine();

			if (!process.WaitForExit(10_000))
				throw new TimeoutException();

			lock (sync)
			{
				var res = buf.ToString();
				return res;
			}
		}

		static string CmdPath => Path.Combine(Environment.SystemDirectory, "cmd.exe");
	}
```

### Configuration

.NET 5, 6
Windows 10 x64

### Regression?

No

**Comment by tmds** [comment]
This is intentional because the reading could block for an indefinite time when there are still grand children keeping the streams alive when the direct child process has already exited.

https://github.com/dotnet/runtime/blob/e6bb456e608ad24a55f3fef2d1ee4ede07d6c729/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L211-L215

You can call `WaitForExit` a second time without a timeout.

**Comment by fandrei** [comment]
@tmds this behavior is quite counter-intuitive and I think that it's not documented. Why don't make waiting for the streams timed?

**Comment by tmds** [comment]
You could do this using `WaitForExitAsync` with a `CancellationToken` that times out.

**Comment by tmds** [comment]
> and I think that it's not documented. 

It is mentioned explicitly in the docs:

> When standard output has been redirected to asynchronous event handlers, it is possible that output processing will not have completed when this method returns. To ensure that asynchronous event handling has been completed, call the WaitForExit() overload that takes no parameter after receiving a true from this overload.

**Comment by fandrei** [comment]
@tmds well, if you insist.

**Comment by tmds** [comment]
@fandrei the implementation doesn't allow for the blocking calls to time out. The alternative is what is described in the docs, or use the async API. Can you close the issue?

**Comment by adaviding** [comment]
When the process has exited, it doesn't mean that you have read all the bytes out of the buffers that contain stdout and stderr data.  You will know when the buffers are drained when the `DataReceivedEventArgs.Data` member is `null`.  You should only stop reading when you see that `null` passed into your `DataReceivedEventHandler`s.

I can't seem to find the documentation to support that right now, but it was part of the official documentation about 3 months ago when I last looked.
