### ISSUE TITLE
Windows' Hotspot doesn't work after installing .NET 5 desktop runtime

### ISSUE THREAD

**Issue by MarcoPellizzoni** [dotnet/runtime#51650]
Hi, 
I tried to install and uninstall multiple times the .NET 5 desktop runtime, and the result is always the same. 
1) I install .NET 5, I reboot the system, I activate the hotspot and try to connect my smartphone. The smartphone receives an IP correctly, but says "internet is not available".
2) I uninstall .NET 5, I reboot the system, everything works fine.

Is there a firewall rule that is automatically set when installing net 5? Where to find it?
Or is it something else?
Can you please help me?

Update: I installed .NET 6 and the hotspot works fine! The problem is with .NET 5. Sadly I have a software that requires .NET 5. So my query still stands.

**Comment by marcpopMSFT** [comment]
@dleeapho

**Comment by dleeapho** [comment]
@MarcoPellizzoni can you confirm that it was .NET 5.0 Runtime you were installing or was it the .NET 5.0 SDK? Also which exact version was this?

**Comment by MarcoPellizzoni** [comment]
I tried bot the desktop runtime and the sdk, in the version 5.0.5 and also legacy

**Comment by NikolaMilosavljevic** [comment]
@MarcoPellizzoni would it be possible to collect .NET installation logs?

`%temp%\*.NET*`

I suggest zipping those files and sharing on One Drive or Google Drive.

**Comment by MarcoPellizzoni** [comment]
Hi,  thanks for the help. Today I reinstalled the .NET 5 desktop runtime from the microsoft website. I rebooted the system and there were no malfunctioning in the hotspot functionality. 
So I tried to install the Technitium DNS server (that I wanted to use and that requires NET 5) and rebooted. And that is the precise moment in which the hotspot doesnt'work. I also tried to kill the service process related to the DNS and the hotspot starts again to work. Evidently there is some misconfigurations with the DNS

**Comment by MarcoPellizzoni** [comment]
here there is the zip files installation logs
https://drive.google.com/file/d/1k4WS6wga9o4E9s4BfnrkvJN-oM0l3SO_/view?usp=sharing

**Comment by NikolaMilosavljevic** [comment]
Not a setup issue, but perhaps there is something in networking stack that could be affecting Windows' Hotspot feature.

**Comment by karelz** [comment]
@MarcoPellizzoni what exactly does not work? Do you have a C# repro? Are you able to minimize it to HelloWorld-style console app to demonstrate what fails?
Are you able to reproduce the same problem on another machine? (ideally vanilla OS setup without any other apps, services, etc.) ... which OS does it fail on anyway?

**Comment by karelz** [comment]
No response, closing. Feel free to reopen once there is more info available. Thanks!
