### ISSUE TITLE
[wasm][tests][aot] warning: Unable to compile method in `System.Runtime.Loader.DefaultContext.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51680]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-50885-merge-0e7ebf1b0da04b00b1/System.Runtime.Loader.DefaultContext.Tests/console.eddfad8b.log?sv=2019-07-07&se=2021-05-12T02%3A28%3A52Z&sr=c&sp=rl&sig=XfNwfMkn0ixVuoIGUXmVbXd2Ii65btZ5xFSp0cRA%2FLQ%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1101201&view=logs&jobId=fddee5b2-3265-5a91-40c1-750d81e69f3f&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=9df76bd4-3041-5537-002b-9e29a53263b9)

```
/home/helixbot/work/B3DB0956/p/dotnet-cli/sdk/6.0.100-preview.2.21155.3/MSBuild.dll -maxcpucount -verbosity:m /bl:/home/helixbot/work/B3DB0956/w/A413090A/uploads/xharness-output/AOTBuild.binlog /p:RunAOTCompilation=true publish/AOTTestProjectForHelix.proj
  AOT'ing 38 assemblies
/home/helixbot/work/B3DB0956/p/build/wasm/WasmApp.targets(137,5): warning : Unable to compile method 'System.Reflection.Assembly System.Runtime.Loader.Tests.TestClass:GetRefEmitAssembly (string,System.Reflection.Emit.AssemblyBuilderAccess)' due to: 'Could not resolve type with token 0100001d from typeref (expected class 'System.Reflection.ConstructorInfo' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Reflection.ConstructorInfo member:(null)'. [/home/helixbot/work/B3DB0956/w/A413090A/e/publish/AOTTestProjectForHelix.proj]
  Compiling native assets with emcc. This may take a while ...
```

**Comment by radical** [comment]
Should we change these warnings -> errors for the tracking PR?

**Comment by vargaz** [comment]
Does this still happen ?

**Comment by lewing** [comment]
cc @SamMonoRT

**Comment by vargaz** [comment]
How can I reproduce this ?

**Comment by ilonatommy** [comment]
Please, comment out:
https://github.com/dotnet/runtime/blob/8c2ef7f44cbbc69c203a4892126c77df48f93390/src/libraries/tests.proj#L406
then run:
```
dotnet build -bl /t:Test src/libraries/System.Runtime.Loader/tests /p:Configuration=Release /p:RunAOTCompilation=true  /p:TargetOS=Browser
```
example of errors you should get:
```
Failed to load method 0x6000091 from '/workspaces/runtime/artifacts/bin/System.Runtime.Loader.Tests/Release/net7.0/browser-wasm/publish/Newtonsoft.Json.dll' due to Could not resolve type with token 0100002f from typeref (expected class 'System.Collections.ObjectModel.Collection`1' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Collections.ObjectModel.Collection`1 member:(null). [/workspaces/runtime/src/libraries/System.Runtime.Loader/tests/System.Runtime.Loader.Tests.csproj]
```

**Comment by vargaz** [comment]
Why does tests.proj need to be changed ?

**Comment by ilonatommy** [comment]
Because in the current state tests inside project `System.Runtime.Loader` are disabled when we pass argument `/p:RunAOTCompilation=true`. And only with this argument they are reported to fail.

**Comment by vargaz** [comment]
Also, shouldn't it be built using ./dotnet.sh ?

**Comment by ilonatommy** [comment]
You're right, I've mistaken arguments. `p:RunAOTCompilation` != `TestNativeAot`. No commenting out needed to see the error. Dotnet.sh will have the same effect, you can use it as well.

**Comment by vargaz** [comment]
Can't reproduce this with 908f44026549981d8ef04af19113ccdbb32d3ecd.
