### ISSUE TITLE
[System.Reflection.PortableExecutable] Retrieve information from DebugDirectories

### ISSUE THREAD

**Issue by eddynaka** [dotnet/runtime#51694]
Hi,

I have a PE that contains the following information when I compiled a C++ project using /CETCOMPAT linker flag.

```bash
  Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    608181E3 cv            4F 00018688     6E88    Format: RSDS, {6CD3201B-996C-4757-998C-70AA00D90E23}, 1, C:\Dll1.pdb
    608181E3 feat          14 000186D8     6ED8    Counts: Pre-VC++ 11.00=0, C/C++=29, /GS=29, /sdl=2, guardN=27
    608181E3 dllchar        4 000186EC     6EEC

        00000001 extended DLL characteristics
                   CET compatible
```

Now, when I don't use the flag, I have:
```bash
  Debug Directories

        Time Type        Size      RVA  Pointer
    -------- ------- -------- -------- --------
    608181E3 cv            4F 00018648     6E48    Format: RSDS, {8669B357-7A9E-463C-BF96-BC98D683EF49}, 1, C:\Dll2.pdb
    608181E3 feat          14 00018698     6E98    Counts: Pre-VC++ 11.00=0, C/C++=29, /GS=29, /sdl=2, guardN=27
```

Using the following code:
```csharp
foreach (DebugDirectoryEntry debugDirectoryEntry in this.peReader.ReadDebugDirectory())
{
    // some code   
}
```

I can see some information, but I can't figure out how to check if I have the CET compatible. One thing that I noticed is that for the PE that contains the information, I can see one DebugDirectoryEntry with Type = 20.

In that case, if I make a check to see if 20 is there, is it safe to say that CETCOMPAT was used?

Thank you!

**Comment by jkotas** [comment]
This is documented in https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#extended-dll-characteristics

You also need to check that the `IMAGE_DLLCHARACTERISTICS_EX_CET_COMPAT` bit is set.

(This question does not have much to do with .NET runtime.)
