### ISSUE TITLE
Can't publish WinForms app for Linux

### ISSUE THREAD

**Issue by Sam-Dvorack** [dotnet/runtime#51691]
Steps to produce:

Create a project from Windows Forms App (.Net core) template in VisualStudio 2019 with .Net 5.0 or with .Net Core 3.1 .
Click on build -> publish
Change deployment mode to: Self-contained
Change target framework to: linux-x64

Error: 
![image](https://user-images.githubusercontent.com/47389279/115717113-26f72200-a37a-11eb-9f34-f5b522a40e3a.png)

`
2>There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsForms available for the specified RuntimeIdentifier 'linux-x64'.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
`

**Comment by bgline23** [comment]
I tried with no success
dotnet publish -r linux-x64 --self-contained

**Comment by gfoidl** [comment]
It's **Win**forms, so not intended to work on non-Windows platforms.
But the error-message could be improved.

**Comment by Sam-Dvorack** [comment]
Not intended to work on non-Windows platforms.
