### ISSUE TITLE
[wasm] SIMD support tracking issue

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#51709]
Context: https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md

Currently still not implemented in Safari. Many engines have implementation available as experimental feature, disabled by default. For example in Firefox it can be enabled in `about:config` by setting `javascript.options.wasm_simd` to `true`.

Emscripten support exists https://emscripten.org/docs/porting/simd.html. Can be enabled with `-msimd128`. SSE emulation also exists.

Possible future performance gains in Json https://github.com/dotnet/runtime/pull/41097

**Comment by tannergooding** [comment]
I feel this should be `area-System.Runtime.Intrinsics`.

While there are certainly internal optimizations possible for the Mono LLVM backend, the WASM SIMD support is very similar in principle to the x64 and ARM64 hardware intrinsics and so likely deserves the dedicated API surface and integration with `System.Numerics.Vector<T>` and friends.
