### ISSUE TITLE
AppContext.UnSetSwitch(string switchName)

### ISSUE THREAD

**Issue by christothes** [dotnet/runtime#51710]
## Background and Motivation

Currently `AppContext.SetSwitch(String, Boolean)` is a one way street. Once a switch has been set, it is not possible to ever get back to a state where `AppContext.TryGetSwitch(String, Boolean)` will return false. 

Consider code like [this](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionSettings.cs#L135-L158) where the value of a switch should take precedence over an environment variable. Once a switch has been set, it is not longer possible to fallback to the environment variable configuration.

This also creates a challenge for tests that want to validate behavior with switches set and unset because ordering of operations must be considered to test behavior with a switch both set and unset.

## Proposed API

```diff
namespace System
{
    public static partial class AppContext {
...
        public static void SetSwitch(string switchName, bool isEnabled)
+       public static void UnSetSwitch(string switchName)
...
```

## Usage Examples

``` C#
// Conditional unset of App config switch
if (AppContext.TryGetSwitch("foo", out bool val)) {
    AppContext.UnSetSwitch("foo");
}
```

**Comment by GrabYourPitchforks** [comment]
Wouldn't this potentially mess up linker behavior (where values in the csproj / JSON files map to `AppContext` values) or any _static readonly_ fields which have been initialized to the value of an `AppContext` switch? I can imagine this resulting in undefined behavior for relevant code paths,

**Comment by christothes** [comment]
> Wouldn't this potentially mess up linker behavior (where values in the csproj / JSON files map to `AppContext` values) or any _static readonly_ fields which have been initialized to the value of an `AppContext` switch? I can imagine this resulting in undefined behavior for relevant code paths,

The API already allows changing the value of a switch. Is un-setting different from that perspective? Also, the only way to access the state of a switch is via `TryGetSwitch` which seems to imply that any code relying on the value of a switch should expect that it may not be defined.

**Comment by tannergooding** [comment]
If this were taken, I think it would be `Unset`, not `UnSet`.

However, I also don't see a whole lot of need for `UnsetSwitch("name")` over `SetSwitch("name", false)`. Exposing `GetSwitch` (where we only have `GetData`) and `SetData` (for non-switch config options, since you need to go through `AppDomain.SetData` today for those) would be much higher on my list of missing APIs.

**Comment by christothes** [comment]
> However, I also don't see a whole lot of need for `UnsetSwitch("name")` over `SetSwitch("name", false)`. 

I don't see how `SetSwitch("name", false)` addresses any of the motivations mentioned in the issue description.

**Comment by tannergooding** [comment]
Ah, I see, I had misunderstood the problem and obviously need to re-read things 😅

**Comment by GrabYourPitchforks** [comment]
> The API already allows changing the value of a switch. Is un-setting different from that perspective?

Setting a switch is generally done _very_ early in an app lifecycle. By very early I generally mean "before user code even has a chance to run." If you look at [the callers of `SetSwitch`](https://source.dot.net/#System.Private.CoreLib/AppContext.cs,c89b66bac639630c,references), they're all unit test projects (which set a switch before exercising the behavior under test) or the `ThreadPool`'s own initialization routines.

For scenarios where a component's global behavior is intended to be changeable at runtime, I'd much rather we stick to first-class public APIs exposed by the component in question. Changing `AppContext` on-the-fly to override a previously set value seems like the wrong approach to take.

**Comment by christothes** [comment]
>  Changing `AppContext` on-the-fly to override a previously set value seems like the wrong approach to take.

If the value of a switch was immutable at runtime, I'd agree that adding a mechanism to un-set it at runtime would be wrong. However, the current API design invites change at any time.

I think the core issue is that the effects of calling `SetSwitch` cannot be undone. It seems that if the API exposes a way for callers to change config, it should also allow them to "undo" that change as well.

**Comment by danmoseley** [comment]
Agreed with @GrabYourPitchforks - I expect code to assume the value is immutable and read this value in static constructors and such. Without looking at why SetSwitch was added, it may have been a niche scenario. 

When we test these switches we typically spawn a process each time. That's the only way to be realistic in the general case.

**Comment by AlexGhiondea** [comment]
The `SetSwitch` method was added to allow app developers to change the configuration of their config switches from their code. 

Given the initial thinking around AppContext and how they are begin used (i.e. early on in the process start, once they are read they should be frozen, etc) I think that adding the `UnSetSwitch` will be at odds with the initial design.

**Comment by tannergooding** [comment]
Closing this based on the above feedback from @GrabYourPitchforks and @danmoseley
