### ISSUE TITLE
System.Text.Json uses strings to identify System.Collections.Immutable types

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#51745]
Today, System.Text.Json recognizes collection types in System.Collections.Immutable by comparing string type names:

https://github.com/dotnet/runtime/blob/6cd562f0d21eddebcb3d10f837329ca90ee9181a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L13-L18

https://github.com/dotnet/runtime/blob/6cd562f0d21eddebcb3d10f837329ca90ee9181a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L127-L139

The reason it does it this way (according to information I got from @layomia) is because on `netstandard2.0`, `System.Collections.Immutable` is not referenced by default. So adding a "hard" reference to it from `System.Text.Json` would mean any `netstandard2.0` consumers of `System.Text.Json` would also need to publish `System.Collections.Immutable` in their app. So to break this hard reference, it uses string type names.

However, on `netcoreapp`, this concern isn't valid because `System.Collections.Immutable` ships inbox. Therefore, we should be able to directly reference `System.Collections.Immutable` and remove all these string comparisons with just straight `typeof` checks.

Trimming size isn't necessarily a concern here because currently this code is preserving `System.Collections.Immutable` through `DynamicDependency` attributes. If we change this code for `netcoreapp` we can get rid of these `DynamicDependency` attributes altogether, and the trimmer will know which types to keep automatically. It will also remove some UnconditionalSuppressMessages.

cc @marek-safar @steveharter

**Comment by jkotas** [comment]
> Trimming size isn't necessarily a concern here because currently this code is preserving System.Collections.Immutable through DynamicDependency attribute

Is this DynamicDependency necessary? If the application does not use immutable collections at all, the name will never match and everything is going to work just fine. This should have been supression instead.

**Comment by eerhardt** [comment]
> Is this DynamicDependency necessary?

Yes, because Json needs to call the `CreateRange` methods on the Immutable collection. And the user's app might not be calling those methods directly, so they'll be trimmed out.

Note - we have trimming tests for these scenarios - https://github.com/dotnet/runtime/tree/main/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/TrimmingTests/Collections

**Comment by eiriktsarpalis** [comment]
> However, on netcoreapp, this concern isn't valid because System.Collections.Immutable ships inbox. Therefore, we should be able to directly reference System.Collections.Immutable and remove all these string comparisons with just straight typeof checks.

What would be the benefit of doing this on netcoreapp? The string comparisons in question appear to live in the converter factory, so it's really just a one-off check. It doesn't seem to outweigh the complexity of needing to maintain two separate factory implementations for both TFMs.

**Comment by eerhardt** [comment]
Given the current state of the product, I think this would actually be worse now. When I originally wrote this issue:

> Trimming size isn't necessarily a concern here because currently this code is preserving System.Collections.Immutable through DynamicDependency attributes.

This is no longer true. https://github.com/dotnet/runtime/pull/53317 removed these DynamicDependency attributes in order to make default blazor wasm apps smaller. So if we were to add hard-references to System.Collections.Immutable this would regress the size gains made in #53317.

Closing as I don't think we should do this anymore.
