### ISSUE TITLE
Debugging directories incorrect in CoreCLR workflow instructions.

### ISSUE THREAD

**Issue by GilesDMiddleton** [dotnet/runtime#51776]
In the following [.md](https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging.md)

If you follow the instructions, debugging fails to find the files specified because there's a missing parent folder `..\` and the first `\` is seen as `\\` in the output.

Step 5 needs to change, from,to
5. Set Command=`$(SolutionDir)\..\..\..\bin\coreclr\windows.$(Platform).$(Configuration)\corerun.exe`
5. Set Command=`$(SolutionDir)..\..\..\..\bin\coreclr\windows.$(Platform).$(Configuration)\corerun.exe`

Step 7, from, to
7. Set Working Directory=`$(SolutionDir)\..\..\..\bin\coreclr\windows.$(Platform).$(Configuration)`
7. Set Working Directory=`$(SolutionDir)..\..\..\..\bin\coreclr\windows.$(Platform).$(Configuration)`

Also noticed the same problem with step 8 `CORE_LIBRARIES`

I can make the appropriate PR

**Comment by SingleAccretion** [comment]
See #51577...

**Comment by GilesDMiddleton** [comment]
closed - duplicate
