### ISSUE TITLE
Intermittent failure in AddProvider_InvokeTypeMultipleTimes_Refreshes test and AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#51819]
AddProvider_InvokeTypeMultipleTimes_Refreshes test [failed](https://github.com/dotnet/runtime/pull/51818/checks?check_run_id=2427633910) in runtime (Libraries Test Run checked coreclr OSX x64 Debug) leg:
```
  Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 4)
    System.ComponentModel.Tests.TypeDescriptorTests.AddProvider_InvokeTypeMultipleTimes_Refreshes [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   3
```

**Comment by safern** [comment]
Happened again in: https://dev.azure.com/dnceng/public/_build/results?buildId=1107359&view=ms.vss-test-web.build-test-results-tab&runId=33804176&paneView=debug

**Comment by VincentBu** [comment]
Failed in [runtime-coreclr libraries-jitstress 20210428.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1111409&view=ms.vss-test-web.build-test-results-tab&runId=33887824&resultId=120603&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_checked-jitstress2_tiered-Ubuntu.1804.Amd64.Open
 -System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes
```

**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes() in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs:line 359
```

**Comment by danmoseley** [comment]
```
Console log: 'System.ComponentModel.TypeConverter.Tests' from job 6a590814-12cb-4b2a-a6e7-7ebffe9e04be (ubuntu.1804.armarch.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440 on ddvsotx2l087
running $HELIX_CORRELATION_PAYLOAD/scripts/0120b789f9164388b2230151ee1a8067/execute.sh in /home/helixbot/work/ABC70A03/w/B022096C/e max 2700 seconds
...
===========================================================================================================
/root/helix/work/workitem /root/helix/work/workitem
  Discovering: System.ComponentModel.TypeConverter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ComponentModel.TypeConverter.Tests (found 1371 of 1372 test cases)
  Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 4)
    System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes [FAIL]
      Assert.Equal() Failure
      Expected: 3
      Actual:   4
      Stack Trace:
        /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs(365,0): at System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes()
  Finished:    System.ComponentModel.TypeConverter.Tests
=== TEST EXECUTION SUMMARY ===
```

**Comment by danmoseley** [comment]
https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1QwUrDQBC9B%2fIPQ04p2NLWmxDBg4UIlVoDHkTKtjtttk1248ykMeLHu0mLeuhBGNgZ9s17b16GLEvkuhCGMPiCvTMWDsbqxFiLBC%2bODqlgyeDsz5Dqi9gHt%2b5h%2fk11B2hyJISZsYZz1HCbgFaCYkqMp%2bPpZHg9nMD4ZtzVIAyU1RDPUXKnIUkgutN6Qe5oNNIqtUd3wKytcO6tmqrAzLPwaolbQk%2fOETiCy8sZKcuVIrTyD56zkVMmPdVMmSLqzsEPQf%2b1Z2cTz8e46trY61RIYpAHf1DbQh29pQTEsZCxu7gDv0bPLfsER4tcMT6qEqO3fqsit8eNDFWj2l7hN785MqsdAosi4cZI7s9j9pKj%2b%2fdanbxxXZaKzCfCxtVW4gGsW3iqse5Frs52wiAMvgEbuumM8gEAAA%3d%3d&web=0

TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished >= datetime(2021-3-1 0:00:00)
and (Method == "AddProvider_InvokeTypeMultipleTimes_Refreshes" or Method == "AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes")
and Result == "Fail"
| extend json=parse_json(Properties)
| extend flavor = tostring(json["System.PhaseName"])
| project-away json
| where Message startswith "Assert.Equal"
| summarize count() by QueueName, flavor



QueueName | flavor | count_
-- | -- | --
ubuntu.1604.amd64.open.rt | libraries_test_run_release_coreclr_Linux_x64_Debug | 3
debian.9.amd64.open.rt | libraries_test_run_release_mono_interpreter_Linux_x64_Release | 1
ubuntu.1804.armarch.open | libraries_test_run_checked_coreclr_Linux_arm_Release | 7
osx.1014.amd64.open | libraries_test_run_release_mono_OSX_x64_Release | 1
ubuntu.1804.armarch.open | libraries_test_run_checked_coreclr_Linux_musl_arm_Release | 3
ubuntu.1804.amd64.open.rt | libraries_test_run_checked_coreclr_Linux_x64_Release | 2
ubuntu.1804.armarch.open | libraries_test_run_release_mono_Linux_arm64_Debug | 3
ubuntu.1604.amd64.open.rt | libraries_test_run_release_mono_Linux_x64_Debug | 4
ubuntu.1804.armarch.open | libraries_test_run_release_coreclr_Linux_arm64_Release | 2
windows.7.amd64.open.rt | libraries_test_run_release_coreclr_windows_x86_Debug | 2
osx.1013.amd64.open | libraries_test_run_checked_coreclr_OSX_x64_Debug | 4
osx.1015.amd64.open | libraries_test_run_release_mono_OSX_x64_Debug | 2
sles.15.amd64.open.rt | libraries_test_run_release_mono_Linux_x64_Debug | 1
osx.1014.amd64.open | libraries_test_run_release_mono_OSX_x64_Debug | 2
redhat.7.amd64.open.rt | libraries_test_run_release_mono_Linux_x64_Debug | 1
osx.1013.amd64.open | libraries_test_run_checked_coreclr_OSX_x64_Release | 1
ubuntu.1804.armarch.open | libraries_test_run_checked_coreclr_Linux_musl_arm64_Release | 2
osx.1015.amd64.open | libraries_test_run_release_coreclr_OSX_x64_Debug | 1
redhat.7.amd64.open.rt | libraries_test_run_release_coreclr_Linux_x64_Debug | 1
windows.10.amd64.server19h1.es.open.rt | build_windows_x64_Release_AllSubsets_Mono | 1
ubuntu.1604.amd64.open.rt | libraries_test_run_release_coreclr_Linux_x64_Release | 1
ubuntu.1604.amd64.open.rt | libraries_test_run_release_coreclr_Linux_musl_x64_Debug | 2
osx.1014.amd64.open | libraries_test_run_release_coreclr_OSX_x64_Debug | 1
windows.10.amd64.server19h1.es.open.rt | libraries_test_run_release_coreclr_windows_x86_Release | 1

**Comment by danmoseley** [comment]
Clearly it's not OS, runtime, or build flavor dependent.

@safern I don't know this code -- I don't see any obvious threads - maybe some static cache that other tests are interfering with concurrently? any theories?

**Comment by VincentBu** [comment]
Failed in [runtime 20210505.136](https://dev.azure.com/dnceng/public/_build/results?buildId=1124389&view=ms.vss-test-web.build-test-results-tab&runId=34196456&resultId=117115&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.1910.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-19.10-helix-amd64-cfcfd50-20191030180623
 -System.ComponentModel.Tests.TypeDescriptorTests.AddProvider_InvokeTypeMultipleTimes_Refreshes
```

**Error message:**
```
Assert.Equal() Failure
Expected: 3
Actual:   4


Stack trace
   at System.ComponentModel.Tests.TypeDescriptorTests.AddProvider_InvokeTypeMultipleTimes_Refreshes() in /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs:line 174
```

**Comment by danmoseley** [comment]
this first began on 23:14 UTC on 4/20 and then happened several times a day. This last major change to this library happened at 20:27 UTC on 4/20 by @stephentoub . I suspect it is related.

commit 291e7c09945e2efed53b67ca4c5fec2a9dba531d
Author: Stephen Toub <stoub@microsoft.com>
Date:   Tue Apr 20 14:27:14 2021 -0400

    Add metadata update handler to System.ComponentModel.TypeConverter (#51466)




```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= datetime(2021-1-1 0:00:00)
| where (Method == "AddProvider_InvokeTypeMultipleTimes_Refreshes" or Method == "AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes")
| where Result == "Fail"
| where Message startswith "Assert.Equal"
| project Queued
| top 10 by Queued asc
```

|Queued|
|---|
|2021-04-20 23:14:40.4960000|
|2021-04-20 23:28:30.6830000|
|2021-04-21 02:39:13.4920000|
|2021-04-21 18:31:42.7430000|
|2021-04-21 19:20:25.3030000|
|2021-04-22 05:10:51.9990000|
|2021-04-22 21:51:08.3190000|
|2021-04-22 23:59:34.9330000|
|2021-04-23 00:13:33.1390000|
|2021-04-23 13:28:11.4810000|

**Comment by danmoseley** [comment]
I believe this test was added in that change and is running concurrently causing this problem
https://github.com/dotnet/runtime/blob/e7b743cae325d4720fceaf7f84f68aaaf7bb7dbe/src/libraries/System.ComponentModel.TypeConverter/tests/ReflectionCachesUpdateHandlerTests.cs#L13

**Comment by danmoseley** [comment]
In the xunit code, I don't see any attribute like "Run this test on its own" nor any hook that I could achieve the same with. seems my options are
* disable all parallleism on the test assembly -- slow
* modify all the tests to make them block as needed
* identify all the tests that are affected and move them into the same test class so they run serially
* create a new test assembly just for this test
Are there any other better options? I'm inclined towards #4.

**Comment by safern** [comment]
Thanks, @danmoseley for the deep investigation. I was oof, that's why I'm responding till now.

If the problem is concurrency, we could move the conflicting tests to the same class and they would be run serially or annotate them as part of the same collection so they run serially.

Look at the `Custom Test Collections` section of this doc: https://xunit.net/docs/running-tests-in-parallel

**Comment by lambdageek** [comment]
@danmoseley  I did something like what Santiago Fernandez Madero suggested for the hot reload ApplyUpdate tests in #51144  - `[Collection(nameof(ApplyUpdateUtil.NoParallelTests))]` on the test classes, where `NoParallelTests` is annotated with `[CollectionDefinition("NoParallelTests", DisableParallelization = true)]`.  (Although I don't know if it's working yet  - since there's just one test class so far)

**Comment by danmoseley** [comment]
Thanks both. I find that doc slightly ambiguous, but my interpretation is that just applying `[CollectionDefinition("NoParallelTests", DisableParallelization = true)]` to the classes that should serialize should be enough. I'll try that.

**Comment by safern** [comment]
I believe the `CollectionDefinition` can only appear once on the assembly. This is per this paragraph:

> You can only have one of these attributes per assembly; if you want to combine multiple behaviors, do it with a single attribute. Also be aware that these values affect only this assembly; if multiple assemblies are running in parallel against one another, they have their own independent values.

**Comment by danmoseley** [comment]
> I believe the CollectionDefinition can only appear once on the assembly.

Right, that was ambiguous though because CollectionDefinitionAttribute is class scope.

As far as I can tell from a scan of the code, I need only put [Collection] on the one troublesome class, and all the others get the default collection (don't need attributes)
https://github.com/xunit/xunit/blob/c54cc52ffb275c81afed022521870193bbca6c39/src/xunit.execution/Sdk/Frameworks/CollectionPerClassTestCollectionFactory.cs#L49

**Comment by safern** [comment]
From what I understand you would need to add a `Collection` attribute with the same collection name to all the test classes that you want to run serially. By default if no collection is provided, each test class is its own collection. Meaning that test classes do run in parallel but tests in the same class run serially, because they are part of the same collection.

Does that make sense?

**Comment by stephentoub** [comment]
> This last major change to this library happened at 20:27 UTC on 4/20 by @stephentoub . I suspect it is related.

Yes, my change added a test that triggers a refresh of some static caches.  The tests failing sporadically here are subscribing to the static Refreshes event and expecting it to only be called a specific number of times; if the test I added is invoked concurrently with these, these will fail.

The test suite already has:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.ComponentModel.TypeConverter/tests/MemberDescriptorTests.cs#L12-L13
The fix then is to add:
```
[Collection("NoParallelTests")]
```
to the offending test classes, notably anything that interacts with TypeDescriptor.Refresh/Refreshed.

**Comment by danmoseley** [comment]
That can't be @stephentoub as he's not here. I came to the same conclusion, and verified it. I'll put up a PR.

**Comment by danmoseley** [comment]
@lambdageek I believe this means what you did is correct also.
