### ISSUE TITLE
Add `AppendReverse` and `Reverse` for `StringBuilder`

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/runtime#51815]
## Background and Motivation

The idea is to avoid additional allocations when reversing a string and adding it to the string builder. So these methods would make it easier to work with reversing

## Proposed API

```diff
namespace System.Text
{
     public sealed partial class StringBuilder : ISerializable
     {
+        public StringBuilder AppendReverse(string? value)
+        public StringBuilder Reverse()
```

#### Appending a reverse string
```cs
var sb = new StringBuilder();
sb.Append("Abc").AppendReverse("Abc");
Console.WriteLine(sb.ToString());
```
Output:
```
AbccbA
```

#### 1. Reverse the current value
```cs
var sb = new StringBuilder();
sb.Append("1234")
  .Append("abcd")
  .Reverse()
  .Append("Ducks");
Console.WriteLine(sb.ToString());
```
Output:
```
dcba4321Ducks
```

#### Psuedo-prepend
```cs
var sb = new StringBuilder();
sb.AppendReverse("White")
  .AppendReverse("Black")
  .AppendReverse("Goose")
  .Reverse();
Console.WriteLine(sb.ToString());
```
Output:
```
GooseBlackWhite
```

## Alternative Designs

I also thought about creating a separate class `ReverseStringBuilder`, but since there is nothing in these methods that cannot be implemented for `StringBuilder`, it's probably a good idea to stay on `StringBuilder`.

## Risks

Unlike `Append`, the new methods won't so fast, because we cannot simply copy a segment of memory, so it requires additional efforts.

**Comment by KalleOlaviNiemitalo** [comment]
Why do you want to reverse strings?

What would be the result of reversing a flag sequence like U+1F1EA U+1F1E8 (🇪🇨)? That's four `Char` values.

**Comment by GrabYourPitchforks** [comment]
FWIW [`StrReverse`](https://docs.microsoft.com/dotnet/api/microsoft.visualbasic.strings.strreverse) will properly handle things like flags, but why does this need to be on `StringBuilder`? It seems like an extremely edge-case scenario. The existing `StrReverse` method gets almost no usage today.

**Comment by WhiteBlackGoose** [comment]
Alright, thank you for your feedback, @KalleOlaviNiemitalo and @GrabYourPitchforks . I indeed couldn't find something that would justify having these methods to be in the base library.
