### ISSUE TITLE
dotnet publish --native

### ISSUE THREAD

**Issue by neoffer** [dotnet/runtime#51829]
I'm very unhappy because of performance talks about .net core. Most of people says that .net core is slower than Go and Java. I love .NET Core because it has perfect syntax and better IDE support. So I have to recommend this. 

Please add --native option to "dotnet publish" command. It should be easy to publish and deploy .net native web apps to have faster response times than Go and Java.

Also please add .net native support to Azure and Azure Pipelines.

**Comment by jeffschwMSFT** [comment]
Please see our .NET 6 theme for our native AOT experiment.  https://github.com/dotnet/runtimelab/issues/248.  You can track its progress in https://github.com/dotnet/runtimelab/tree/feature/NativeAOT.  During .NET 6 we do not plan on adding this as an official option, but we are gathering data for potentially adding in a future release.

**Comment by huoyaoyuan** [comment]
It's a common false sense about performance that "being native will increase performance". .NET Already executes in native. Publish in native will only improve startup performance, which can be improved by R2R.

**Comment by jeffschwMSFT** [comment]
Thanks @huoyaoyuan for the call out to R2R.  Here is the documentation on publishReadyToRun: https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run
