### ISSUE TITLE
will monovm support Universal binaries on iOS app store?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#51827]
as the .net6 preview1 said:

![image](https://user-images.githubusercontent.com/5187024/115977580-31006700-a5ac-11eb-8ba7-f3620d32959d.png)

iOS development use MonoVM will it not supported Universal binaries?
we are embedding monovm will it has any ill effect?

**Comment by filipnavara** [comment]
iOS app store is different from Mac app store. Which one do you mean? Can you clarify the question?

**Comment by srxqds** [comment]
> iOS app store is different from Mac app store. Which one do you mean? Can you clarify the question?

iOS app store

**Comment by filipnavara** [comment]
iOS app store has no requirement for universal binaries as far as I can tell. They were `arm64` all along. OTOH the Mac app store was historically `x64` only and now they require `arm64` in addition to that to support machines with Apple Silicon.

**Comment by marek-safar** [comment]
We'll ship that support as part of Apple publishing story but don't have plans to make it universally available as a component.

**Comment by srxqds** [comment]
ok, thank you for confirm.
