### ISSUE TITLE
ReferenceHandler.IgnoreCycles not handling duplicate strings properly

### ISSUE THREAD

**Issue by jsheetzati** [dotnet/runtime#51837]
### Description

Using System.Text.Json's ReferenceHandler.IgnoreCycles is not working properly with string properties. It seems that System.Text.Json is improperly detecting strings with the same value as a cycle.

### Configuration

System.Text.Json Nuget Version: 6.0.0-preview.3.21201.4

### Other information

Here is some sample code that demonstrates the issue. In this case, `parent.child.name` will be serialized as null. No cycles here so I was expecting the name 'John' to be serialized for both `parent.name` and `parent.child.name`. 

This same test works fine when not specifying `ReferenceHandler` and no cyclic exceptions are thrown.

```csharp
[Fact]
public void Test()
{
	var parent = new Parent
	{
		Name = "John",
		Age = 60,
		Child = new Child
		{
			Name = "John",
			Age = 15
		}
	};

	var json = JsonSerializer.Serialize(parent, new JsonSerializerOptions
	{
		ReferenceHandler = ReferenceHandler.IgnoreCycles,
		WriteIndented = true
	});
}

public class Parent
{
	public string Name { get; set; }

	public int Age { get; set; }

	public Child Child { get; set; }
}

public class Child
{
	public string Name { get; set; }

	public int Age { get; set; }
}
```

**Output without specifying `ReferenceHandler`**
```
{
  "Name": "John",
  "Age": 60,
  "Child": {
    "Name": "John",
    "Age": 15
  }
}
```

**Output when specifying `ReferenceHandler.IgnoreCycles`**
```
{
  "Name": "John",
  "Age": 60,
  "Child": {
    "Name": null,
    "Age": 15
  }
}
```

**Comment by GrabYourPitchforks** [comment]
JSON team - may want to investigate this behavior for other primitives that have reference equality, such as if a single instance of a boxed integer appears in multiple places.

**Comment by eiriktsarpalis** [comment]
Curiously this seem to only impact strings in my tests:
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

void Test(object? value)
{
    var list = new List<object?> { value, value };
    var options = new JsonSerializerOptions { ReferenceHandler = ReferenceHandler.IgnoreCycles };
    var json = JsonSerializer.Serialize(list, options);
    Console.WriteLine(json);
}

Test(42); // [42,42]
Test(new object()); // [{},{}]
Test("John"); // ["John",null]
```

There seems to be something about strings in particular that makes the serializer erroneously treat all recurring references as cycles.
