### ISSUE TITLE
Add SqlTypes members to remove SqlClient internal access hacks

### ISSUE THREAD

**Issue by Wraith2** [dotnet/runtime#51836]
## Background and Motivation

In the desktop framework the `System.Data.SqlClient` namespace was originally part of the `System.Data` assembly allowing SqlClient to access internal methods of some types in the `System.Data.SqlTypes` namespace. In netcore`SqlClient` was  split out into a separate assembly but rather than add new public apis to the `SqlTypes` struct overlay hacks were used to maintain the existing access to internals. 

`SqlClient` has now been split out of the framework entirely into a separate project `Microsoft.Data.SqlClient` and that project still uses the overlay hack to access internals, all collected into the [SqlTypeWorkarounds]([SqlClient/SqlTypeWorkarounds.cs at main · dotnet/SqlClient (github.com)](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlTypes/SqlTypeWorkarounds.cs)) class. It is unlikely that the layout or definition of the `SqlTypes` members will change but it is undesirable to have a first party library use such access when it is possible and relatively simple to extend the public api.

## Proposed API

```diff
namespace System.Data.SqlTypes
{
	public struct SqlDateTime
	{
+   	public static DateTime FromInternalRepresentation(int daypart, int timepart)
	}
	
	public struct SqlMoney
    {
+		public static SqlMoney FromInternalRepresentation(long value);
+		public long GetInternalRepresentation();
    }
    
    public struct SqlDecimal
    {
+		public GetInternalDataRepresentation(Span<uint> value)
    }
    
    public struct SqlBinary
    {
+		public static SqlBinary WrapBytes(byte[] bytes)    
    }
    
    public struct SqlGuid
    {
+		public static SqlGuid WrapBytes(byte[] bytes)
    }
}

```
## Usage Examples

Creating an `SqlMoney` from it's internal TDS representation will change from:

```csharp
...
	case TdsEnums.SQLUNIQUEID:
		value.SqlGuid = SqlTypeWorkarounds.SqlGuidCtor(unencryptedBytes, true);   // doesn't copy the byte array
        break;
...
    
public static class SqlTypeWorkarounds
{
    internal static SqlGuid SqlGuidCtor(byte[] value, bool ignored)
    {
        var c = default(SqlGuidCaster);
        c.Fake._value = value;
        return c.Real;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct SqlGuidLookalike
    {
        internal byte[] _value;
    }

    [StructLayout(LayoutKind.Explicit)]
    private struct SqlGuidCaster
    {
        [FieldOffset(0)]
        internal SqlGuid Real;
        [FieldOffset(0)]
        internal SqlGuidLookalike Fake;
    }
}
```

to:

```csharp
...
	case TdsEnums.SQLUNIQUEID:
		value.SqlGuid = SqlGuid.WrapBytes(unencryptedBytes);
        break;
...
```

### SqlDateTime.FromInternalRepresentation
- SqlDateTime has an internal static method `internal static DateTime ToDateTime(int daypart, int timepart)` which could have the access modifier changed to public. I chose not to suggest this because it doesn't convert an SqlDateTime instance to a DateTime, it converts parameters which are the internal representation used in TDS into a DateTime, the input and output are not what a user would expect without reading the documentation. 
- It could be argued that the return value should be an SqlDateTime however this is not how it is used and if an SqlDateTime were used it would usually need to be unwrapped because a user requested a known-not-null DateTime through `GetFieldValue<DateTime>` or `GetDateTime`

### SqlMoney.ToSqlInternalRepresentation
`SqlMoney` already contains an internal implementation of this method so i propose only to change the existing access modifier. The internal representation is an unscaled value read from a TDS packet.

### SqlMoney.FromInternalRepresentation
`SqlMoney` contains an internal ctor `internal SqlMoney(long value, int ignored)` which was used to perform an unscaled construction of `SqlMoney` from the internal representation. The ignored parameter is present because there is already a public ctor `internal SqlMoney(long value)` which performs a scaled creation. Since I've already proposed a method to get the unscaled value and contains the words InternalRepresentation it made sense to me to have a symmetric static method to do the creation from that representation. 

### SqlDecimal.GetInternalDataRepresentation

This method name was chosen for close to be similarity to the `SqlMoney` and `SqlDateTime` methods which provide access to internal data representations. This method does not give access to all of the internal data for the `SqlDecimal`, it only provides access to 4 Data uints which contain the value, it does not provide access to the additional 4 bytes of data (Status, Length, Precision and Scale) and because of that I have added the word Data in the middle of the name. Access to the other byte fields is done through existing public accessor properties.

This method could have been called `GetBits` for some symmetry with `decimal.GetBits`, i decided against this because it isn't an exactly analogous operation.

### SqlBinary.WrapBytes and SqlGuid.WrapBytes

These could be called `TakeBytes` but that felt clumsy or too low level a name. Their intention is to return an instance of their containing type which uses the reference to the array parameter passed in, currently byte[] ctor for each type would allocate a new appropriately sized array and copy the contents of the parameter into it.

### General

The existing behaviour of accessing internal members will be present in pre NET6 framework and SqlClient binaries for as long as both exist. It would cause compatibility problems discoverable only at runtime if we tried to change that. Adding these members will allow the same access to be done using a legitimate channel on NET6 and future SqlClient versions that compile against it. 

Adding these new members simply makes the access to data used by SqlClient official and thus documented. They should have no performance impact.

## Risks

The new members will need to be documented.

/cc area owners @ajcvickers, @roji and @David-Engel

**Comment by Wraith2** [comment]
@roji , @David-Engel triage?

**Comment by David-Engel** [comment]
This makes sense to me. Seems like one of the easier internals hacks to resolve in SqlClient since the breakup.

@roji @ajcvickers @saurabh500 @cheenamalhotra - Anyone object to exposing the proposed methods in `System.Data.SqlTypes` as public APIs?

**Comment by cheenamalhotra** [comment]
My initial thoughts:
1. Can we name APIs: `SqlBinary.WrapBytes` and `SqlGuid.WrapBytes` to:
   "`SqlBinary.FromByteArray(byte [])`" and "`SqlGuid.FromByteArray(byte [])`"
   This would keep the nomenclature similar to existing Types where an API instantiates an instance from another type, e.g. [DateTime.FromBinary](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.frombinary?view=net-5.0#System_DateTime_FromBinary_System_Int64_)? Also "Wrap/Unrap" terms are used for "Encrypt/Decrypt" interchangeably.
2. I don't see any .NET API with "internaldatarepresentation" naming convention. Could we rename these get and from APIs to their specific types, e.g. `ToLong()`/ `FromLong(long)` for `SqlMoney` and for `SqlDateTime` construction, you could call it `FromDateTimeParts`?
3. What is the return type of `SqlDecimal.GetInternalDataRepresentation` ? It's name could also be derived based on what it returns as `ToXxxx()`.

**Comment by roji** [comment]
* I'm assuming these changes are being proposed for .NET Core; if so, wouldn't the hacky workarounds have to continue being there for the .NET Framework version of Microsoft.Data.SqlClient? If so, is there value in doing this (and further driving the two codebases apart)?
* Does a similar problem exist on the writing side, i.e. does SqlClient need a ToInternalDataRepresentation as well (or are these already exposed in some other ways)?
* For SqlBinary and SqlGuid, I'd lean towards publicly exposing the 2nd constructor with a `createCopy` flag, rather than a static WrapBytes/FromByteArray - mainly because you already have a constructor accepting byte[] (so it would be more consistent/discoverable etc.). But that's a minor API shape question.
* I'll look at the other APIs more closely a bit later.

For the record, I'd have much preferred for these types to be copied into Microsoft.Data.SqlClient - [but that does seem impractical](https://github.com/dotnet/runtime/issues/1034#issuecomment-567565335).

**Comment by roji** [comment]
> I'm assuming these changes are being proposed for .NET Core; if so, wouldn't the hacky workarounds have to continue being there for the .NET Framework version of Microsoft.Data.SqlClient? If so, is there value in doing this (and further driving the two codebases apart)?

BTW, unless I'm mistaken the same holds for previous .NET Core versions - the earlier point when SqlTypeWorkarounds would be removable is when M.D.SqlClient drops support for net5.0, right? Is that worth pursuing?

**Comment by Joe4evr** [comment]
> 1. Can we name APIs: `SqlBinary.WrapBytes` and `SqlGuid.WrapBytes` to:
> "`SqlBinary.FromByteArray(byte [])`" and "`SqlGuid.FromByteArray(byte [])`"

Admittedly, I don't know much about these SQL types, but I don't understand the request for these factory methods, given that [both](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqlbinary.-ctor?view=net-5.0) of [those](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqlguid.-ctor?view=net-5.0#System_Data_SqlTypes_SqlGuid__ctor_System_Byte___) already have a constructor that takes in a `byte[]`.

**Comment by roji** [comment]
@Joe4evr if you look at the [implementation](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SQLGuid.cs#L37), you'll see these constructor copy the given byte array, which isn't good for perf and isn't needed when SqlClient is constructing the instance.

**Comment by Wraith2** [comment]
> Can we name APIs: SqlBinary.WrapBytes and SqlGuid.WrapBytes to:
"SqlBinary.FromByteArray(byte [])" and "SqlGuid.FromByteArray(byte [])"

I considered this but decided to use Wrap and Unwrap because it clearly communicates that the array passed in it taken and not copied which is important for correct use.

> I don't see any .NET API with "internaldatarepresentation" naming convention. Could we rename these get and from APIs to their specific types, e.g. ToLong()/ FromLong(long) for SqlMoney and for SqlDateTime construction, you could call it FromDateTimeParts?

The values returned being internal representations is important. The value contained in the returned data type is not the usual format that .net programs expect and should not be treated as convertible by standard apis. 

> What is the return type of SqlDecimal.GetInternalDataRepresentation ? It's name could also be derived based on what it returns as ToXxxx().

`void` is the return type, the span argument is filled with the bytes. It could be made `bool` or `OperationStatus` if that is more appropriate. Failure to pass in a correctly sized buffer is an exception state imo.

>I'm assuming these changes are being proposed for .NET Core; if so, wouldn't the hacky workarounds have to continue being there for the .NET Framework version of Microsoft.Data.SqlClient? If so, is there value in doing this (and further driving the two codebases apart)?

Yes, netcore only because netfx is frozen. There are always going to have to be separate code paths for the two frameworks so this doesn't add much extra burden. It will allow the type workarounds to be clearly marked as deprecated in tfms that use them, they should not be added to. It is not going to be possible to remove the existing hacks for the forseeable future. 

Being able to remove them and being able to say that they should not be used or extended anymore are two different goals. As an external library to the runtime SqlClient should not be using private implementation detail information like this, when it was done it was for pragmatic reasons but leaving it like this can be seen as implicit blessing and it should not be.

> Does a similar problem exist on the writing side, i.e. does SqlClient need a ToInternalDataRepresentation as well (or are these already exposed in some other ways)?

An existing operation handles the to direction conversion. 

>  I'd have much preferred for these types to be copied into Microsoft.Data.SqlClient

I agree but without that wouldn't be possible without breaking DataTable and DataAdapter interoperability. Those are still supported classes and likely to be in use a huge amount of LOB codebases.

**Comment by Wraith2** [comment]
SqlClient already multi targets and probably always will. As you say, the future where net6 is the lowest supported runtime is a long time away and may never occur.

I think it is worth doing because:
1) it removes rule breaking of SqlClient that can be cited as "Well MS do it themselves so I can too". We should not break rules that we want others to follow.
2) It makes the interface between SqlClient and System.Data.SqlTypes explicit so in future if they are removable it's clear what is being used.
3) It's relatively low effort

If someone feels that any of those points are incorrect then we can just carry on as we do currently.

**Comment by Wraith2** [comment]
Any chance of an update? This seems to be in limbo as untriaged. Is it not at least worth letting the design team look at it and decide whether it has any merit?

**Comment by roji** [comment]
Just to be clear, this would be waiting on the SqlClient team, should they decide they want to do this.

I personally still believe this has very little value:

1. This is very old code - it's been this way forever, and code around this is extremely unlikely to change.
2. It's very unlikely that these types or the APIs in question will be removed in the future.
3. Any churn in the runtime carries some risk
4. There's very little value in actually doing this

But as I wrote above, this is ultimately SqlClient's decision.

**Comment by David-Engel** [comment]
While I see that this is the "right" thing to do, I'll be honest. We don't have the bandwidth to push for it. If you (@Wraith2) want to submit the API and PR on the runtime side and the equivalent changes on the SqlClient side, I'm not against that. But you'd be waiting for us to create a suitable .NET x specific target and this feature alone isn't strong enough to warrant its own target. We will likely be creating a .NET 6 target (skipping 5 since it's out of support in May) and skipping 7 since I don't think it will be 
LTS.

I think you might get frustrated when people aren't prioritizing each required change.

There are many things I would prioritize over this. Examples:

1. I would love to see this addressed --> https://github.com/dotnet/SqlClient/issues/303
2. Difficult ones, I know: https://github.com/dotnet/SqlClient/issues/422 and https://github.com/dotnet/SqlClient/issues/647
3. https://github.com/dotnet/SqlClient/issues/1009
4. https://github.com/dotnet/SqlClient/issues/649
5. https://github.com/dotnet/SqlClient/issues/648
6. https://github.com/dotnet/SqlClient/issues/646
7. https://github.com/dotnet/SqlClient/issues/1256
8. https://github.com/dotnet/SqlClient/issues/113

Regards,
David

**Comment by Wraith2** [comment]
Ok.

**Comment by David-Engel** [comment]
Re-opening issue for consideration in a future .NET release.

**Comment by David-Engel** [comment]
> Is there anything preventing this going to review? There's still time to get it approved and possibly implemented in runtime for 7. Not that if it is included in there is no telling when it will be picked up by SqlClient but at least if if is available it _can_ be used if there is opportunity.

Sorry, just bandwidth.

I see a copy/paste typo in the proposal:

```
    public struct SqlGuid
    {
+		public static **SqlBinary** WrapBytes(byte[] bytes)
    }
```

Otherwise, I'm good with it.

We've shown that without new APIs, SqlClient will need to continue to use the union overlay hacks to maintain performance when targeting .NET Core/.NET. Moving to the current public APIs can result in over 10x slowdowns on hot paths converting between TDS data and SQL types. 

@GrabYourPitchforks What do we need to do to move this into review and who needs to approve it? Even if it doesn't make .NET 7, now is a good time to get the API approved while the requirements are fresh in our minds.

**Comment by Wraith2** [comment]
@jeffhandley I was suggested to tag you on this. We've got a slightly weird situation where @David-Engel is the owner of SqlClient but I don't think has permissions to mark this as ready for review, @ajcvickers and @roji are System.Data owners which theoretically own this but it's all SqlClient specific so they usually defer to David. Can you help resolve and see if we can get this to api review before the 7.0 cutoff?

**Comment by jeffhandley** [comment]
Thanks, @Wraith2. I updated this specific issue and fired off an email to resolve the permissions snag.

**Comment by terrajobst** [comment]
* `SqlDateTime`
    - The name `FromInternalRepresentation` feels off
    - Why does `SqlDateTime.FromInternalRepresentation` return a DateTime and not a `SqlDateTime`?
    - Do we need this at all?
    - How about `public static SqlDateTime FromParts(int dayPart, int timePart)`
* `SqlMoney`
    - How about `FromTdsValues` to `ToTdsValue`? This makes it clear what "internal representation" it refers to.
* `SqlDecimal`
    - Should return the number of elements written to the supplied span
    - `int GetTdsValue(Span<uint> destination)`
    - Don't you need a `SqlDecimal FromTdsValue(ReadOnlySpan<uint> source)`?
    - Why `int`? The constructor takes them as four `int` values.
* `SqlBinary`, `SqlGuid`
    - APIs that don't copy are unusual, but this works

```C#
namespace System.Data.SqlTypes;

public partial struct SqlDateTime
{
    public static SqlDateTime FromParts(int dayPart, int timePart);
}

public partial struct SqlMoney
{
    public static SqlMoney FromTdsValues(long value);
    public long GetTdsValue();
}

public partial struct SqlDecimal
{
    public int GetTdsValue(Span<uint> destination);
}

public partial struct SqlBinary
{
    public static SqlBinary WrapBytes(byte[] bytes);
}

public partial struct SqlGuid
{
    public static SqlGuid WrapBytes(byte[] bytes);
}
```

**Comment by Wraith2** [comment]
I posted in Youtube chat during the api review but it doesn't look like people can see all of the chat messages.
Is this approved for 7 or 8?

**Comment by bartonjs** [comment]
@Wraith2 Generally the API Review meeting doesn't talk about releases (other than "this looks scary big and you probably won't get feedback before it's frozen, you should probably wait for the next release").  The issue is marked as 7, so I assume the intent was to get it in for .NET 7.

**Comment by GrabYourPitchforks** [comment]
I missed review this morning due to a conflict but have a concern. __I believe we should not create `SqlGuid.WrapBytes`.__ The other APIs in the proposal are ok.

If we create `SqlGuid.WrapBytes`, the contracted behavior would be that the `SqlGuid` instance wraps the byte array, meaning that any changes to the byte array must be reflected back to the new `SqlGuid` instance. This implies that the layout of `SqlGuid` is forever locked to the following:

```cs
public struct SqlGuid
{
    private byte[] _value;
}
```

And we would never be able to change the internal layout to this more optimized shape:

```cs
public struct SqlGuid
{
    private Guid? _value;
}
```

This hampers our ability to make future improvements to the Framework. If we are really concerned about the performance of the `SqlGuid` type, we should just make perf improvements directly to its implementation without introducing any new API.

**Comment by terrajobst** [comment]
> If we create `SqlGuid.WrapBytes`, the contracted behavior would be that the `SqlGuid` instance wraps the byte array, meaning that any changes to the byte array must be reflected back to the new `SqlGuid` instance.

Yes, but. The type is in the framework since .NET 1.0. It's not to say that we can't improve the type, it just seems unlikely at this point...

**Comment by GrabYourPitchforks** [comment]
> It's not to say that we can't improve the type, it just seems unlikely at this point...

I wouldn't say it's unlikely. This issue was opened literally because there's a performance problem with the existing implementation. Why aren't we doing the easy non-API-changing thing to try fixing the implementation first, before considering new API?

**Comment by terrajobst** [comment]
> Yet here we are, in .NET 7, talking about improving the type.

LOL. I was more thinking the "the fundamental shape or encoding of the type". Adding methods that operate over the same shape is much easier to reason about.

> This issue was opened literally because there's a performance problem with the existing implementation. Why aren't we doing the easy non-API-changing thing to try fixing the implementation first, before considering new API _which permanently prevents us from fixing the implementation_?

That's a great question and @David-Engel would be more qualified to answer that. I assume these types are kinda frozen in their shape due to being tied to the TDS spec.

**Comment by GrabYourPitchforks** [comment]
> I assume these types are kinda frozen in their shape due to being tied to the TDS spec.

The TDS spec freezes the _capabilities_ of these types, but it doesn't freeze their _layout details_. We had quite the in-depth email discussion on this a few months ago.

**Comment by David-Engel** [comment]
>> This issue was opened literally because there's a performance problem with the existing implementation. Why aren't we doing the easy non-API-changing thing to try fixing the implementation first, before considering new API which permanently prevents us from fixing the implementation?

> That's a great question and @David-Engel would be more qualified to answer that. I assume these types are kinda frozen in their shape due to being tied to the TDS spec.

To clarify, I interpret the "fix the implementation" statement to mean fix the System.Data.SqlTypes implementation of `new SqlGuid(byte[] value)` where it [copies the byte array](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SQLGuid.cs#L39). (SqlBinary [does the same thing](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SQLBinary.cs#L38).)

SqlClient simply needs methods that avoid so much unnecessary byte copying, as the whole job of the database client is to construct many, many objects like these. I'm fine with whatever API shape we land on to accomplish that.

**Comment by bartonjs** [comment]
I think @GrabYourPitchforks 's version of "fix the implementation" is to change the field from `byte[]` to `Guid` (or `Guid?`), and invert the relationship of how the `byte[]` ctor and `Guid` ctor work.  Then the impl is storing values in the GUID-sized struct, not storing an array at all.

**Comment by MichalPetryka** [comment]
Since the struct seems to keep a separate state of null, I'd say that `Guid?` would be more applicable here.

**Comment by GrabYourPitchforks** [comment]
Right. "Fixing the implementation" wouldn't require adding any new API shape at all. It would literally be changing this:

```cs
private byte[] _value;
public SqlGuid(byte[] value)
{
    // argument length check
    _value = (byte[])value.Clone();
}
```

To:

```cs
private Guid? _value;
public SqlGuid(byte[] value)
{
    // argument length check
    _value = new Guid(value);
}
```

Aside from the length check (which you'd need in all cases), it's literally a single `mov` instruction of a 128-bit register and a single `xor` instruction on a 32-bit register. You can't really get much faster than that. (In fact, this has the added benefit that it doesn't need to update the GC card table since you're only storing references to value types, not references to reference types!)

**Comment by MichalPetryka** [comment]
FYI: optimizing the implementation would require implementing `ISerializable` so that binary serialization keeps working.

**Comment by MichalPetryka** [comment]
I've opened a draft to show how the proposed changes would look like: #72549

**Comment by terrajobst** [comment]
@David-Engel, what your thoughts on this? What @GrabYourPitchforks said makes sense to me.

**Comment by David-Engel** [comment]
> @David-Engel David Engel (Simba Technologies Inc) Vendor, what your thoughts on this? What @GrabYourPitchforks Levi Broderick FTE said makes sense to me.

Agreed. I'm all for PR #72549. We'll have to adjust/service System.Data.SqlClient and Microsoft.Data.SqlClient to keep them compatible with .NET 7. With that change, the API proposal here can eliminate the new `public static SqlGuid WrapBytes(byte[] bytes);` method.

**Comment by MichalPetryka** [comment]
Instead this is needed in order to maintain binary serialization (is a new API review needed?):
```C#
public partial struct SqlGuid : ISerializable
{
    public SqlGuid(SerializationInfo si, StreamingContext sc);
    void ISerializable.GetObjectData(SerializationInfo si, StreamingContext sc);
}
