### ISSUE TITLE
Assembly.ReflectionOnlyLoad(...) is obsoleted, consider remove the unused reference in mono

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#51838]
As part of https://github.com/dotnet/runtime/issues/50529 we have obsoleted several APIs not supported in .Net Core which caused a build warning in mono CoreClr 

I see the API calling `Assembly.ReflectionOnlyLoad(...)` is always called with a value of `false` for `bool reflectionOnly` parameter, which means that reference will never actually used. We might want to remove this parameter and related code section from https://github.com/dotnet/runtime/blob/90f97ac50154ee23449f273c3a8d13dfe985815b/src/mono/System.Private.CoreLib/src/System/RuntimeTypeHandle.cs#L290-L291

_Originally posted by @buyaa-n in https://github.com/dotnet/runtime/pull/50941#discussion_r619417207_

**Comment by SamMonoRT** [comment]
cc @fanyang-mono

**Comment by SamMonoRT** [comment]
Not sure what the best approach if for associated tests - completely remove from test suite or disable for certain runs.
