### ISSUE TITLE
SocketsHttpHandler.ConnectCallback and disposing stream

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#51841]
Should the stream returned by `SocketsHttpHandler.ConnectCallback` always be disposed if it is no longer used, or there is an error when using it?

I think there are situations, such as an error when a connection is starting, that will cause a stream to never be disposed.

**Comment by geoffkizer** [comment]
Yeah, it should be disposed. 

I did a quick look at the code and the only place I saw where we might not be properly disposing the stream is here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1445

That is, if the write of the initial SETTINGS frame fails. Does that sound like what you are seeing?

**Comment by JamesNK** [comment]
I think the error I saw was when I had an idle socket (1-2 minutes) and then used it to create a NetworkStream for a HTTP/2 request. The error complained about reading invalid content, then the stream was never disposed.

Do you want me to try to recreate it to get the error message?

**Comment by geoffkizer** [comment]
That could be related to the initial SETTINGS frame issue I describe above, if the socket was closed by the server and then we try to write to it.

How about if I fix the issue I describe above first, then you see if you can still repro something here?
