### ISSUE TITLE
Type library exporter encountered an error while processing error: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

### ISSUE THREAD

**Issue by vasudevpatelFTX** [dotnet/runtime#51858]
### Description

* Unable to generate type library in net5.0 TargetFramework
*  create class library with net5.0 sdk .
    Add below code in csproj file for generate .tlb file
     `<Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="call &quot;$(DevEnvDir)..\Tools\VsDevCmd.bat&quot;&#xD;&#xA;tlbexp &quot;$(TargetPath)&quot; /win32 /out:&quot;$(TargetName).tlb&quot;" />
    </Target>`

### Configuration

* net5.0 SDK
* visual studio 
   Microsoft Visual Studio Community 2019
   Version 16.9.3
* OS : Windows 10

### csproj File content download link

[csproj-file.docx](https://github.com/dotnet/runtime/files/6376905/csproj-file.docx)

**Comment by jkoritzinsky** [comment]
As mentioned in https://github.com/dotnet/runtime/issues/34609#issuecomment-610159634, Tlbexp is not supported in .NET 5 and we currently have no plans to support it. We recommend that you manually write an idl file and compile that into a tlb with the midl tool.

cc: @AaronRobinsonMSFT
