### ISSUE TITLE
File.Copy not working for (even small) AVI files

### ISSUE THREAD

**Issue by Omcsesz** [dotnet/runtime#51882]
### Description

Hello, Team!

I created a minimum working example, to illustrate the issue I'm having.
I want to use File.Copy() to copy a file to a certain location.
I attached the test project solution.
Am I missing something trivial?

### Observed behaviour:
The program creates a zero-length .avi file.

### Expected behaviour: 

The program should copy the file with the new name.

### Configuration

* Which version of .NET is the code running on? **.NET Framework 4.8**
* What OS and version, and what distro if applicable? **Win7** 
* What is the architecture (x64, x86, ARM, ARM64)? **x64**
* Do you know whether it is specific to that configuration? **I don't know**

### Regression?

* Did this work in a previous build or release of .NET Core, or from .NET Framework? **NO**
[TestProject__.zip](https://github.com/dotnet/runtime/files/6379154/TestProject__.zip)

**Comment by manandre** [comment]
Hello,

The `OpenFile` call creates an empty file and the returned `Stream' object is not used.
The `File.Exists` method then returns `true`, so the `File.Copy` is never called.
Moreover, the `VideoFile` field only contains the name of the file, the `FullPath` one contains... the full path.
Fix proposal for _MainWindow.xaml.cs_ (working on my local dev environment):

```cs
private void SaveVideoAs(object sender, RoutedEventArgs e)
{
    SaveFileDialog sfd = new SaveFileDialog();
    sfd.Filter = "AVI files (*.avi)|*.avi";

    if (sfd.ShowDialog() == System.Windows.Forms.DialogResult.OK)
    {
        if (!File.Exists(sfd.FileName)) 
        {
            File.Copy(((SearchResultTableRow)fileSearchResultsDataGrid.SelectedItem).FullPath,
                sfd.FileName);
        }
    }
}
```
You should use a (visual) debugger to help you analyzing the behavior of your application during its development.

**Comment by Omcsesz** [comment]
Fine, it works now!
Thanks, @manandre !
