### ISSUE TITLE
Infrastructure issue, running XML tests fails with error MSB4057: The target "Test" does not exist in the project.

### ISSUE THREAD

**Issue by lovettchris** [dotnet/runtime#51880]
### Description

Following instructions in [testing/libraries/testing.md](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md)

- cd dotnet\runtime\src\libraries\System.Private.Xml
- dotnet.cmd build /t:Test

(using dotnet.cmd script in the root of the repo, which is not mentioned in testing.md but seems to be needed)

Results in the following errors:

```
d:\git\lovettchris\dotnet\runtime\src\libraries\Common\tests\System\Xml\BaseLibManaged\BaseLibManaged.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\Common\tests\System\Xml\XmlDiff\XmlDiff.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Private.Xml\tests\XmlReaderLib\System.Xml.RW.XmlReaderLib.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\Common\tests\System\Xml\ModuleCore\ModuleCore.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\Microsoft.Win32.Registry\ref\Microsoft.Win32.Registry.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Private.Xml\src\System.Private.Xml.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\Common\tests\TestUtilities\TestUtilities.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\Common\tests\System\Xml\XmlCoreTest\XmlCoreTest.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Runtime.CompilerServices.Unsafe\ref\System.Runtime.CompilerServices.Unsafe.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Security.AccessControl\ref\System.Security.AccessControl.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Security.Principal.Windows\ref\System.Security.Principal.Windows.csproj : error MSB4057: The target "Test" does not exist in the project.
d:\git\lovettchris\dotnet\runtime\src\libraries\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj : error MSB4057: The target "Test" does not exist in the project.
```

### Configuration

* Which version of .NET is the code running on? latest master bits
* What OS and version, and what distro if applicable? windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* On AMD Rizen 9 with 12 cores + hyperthreading.

### Regression?

no idea

### Other information

I can run the tests inside Visual Studio 2019, but it is painfully slow to discover and run the tests (takes about 6 minutes to run the tests, even though the tests themselves run in about 8 seconds).

**Comment by safern** [comment]
Hello @lovettchris -- what you are running is going to run `/t:test` on the solution because you are passing the path to it's directory. Instead you need to provide the path to the directory that contains the `.Tests.csproj`; it seems like `System.Private.Xml` contains multiple on different folders.

As an alternative, you could probably try running `dotnet test` on the solution? I don't remember if that works fine.

**Comment by lovettchris** [comment]
Ah, I see now thanks.  I didn't dig deep enough looking for those *.Tests.csproj files.  That would have been a nice hint in the docs.   Also is there any way to make running the tests faster in Visual Studio? running a single test takes 8 minutes, even though the test itself only takes milliseconds seconds.

**Comment by safern** [comment]
Ah, I believe that might be because you probably built the runtime for `Debug`? May I ask, what did you run to build the repository? 

> That would have been a nice hint in the docs.

It seems like the docs do point to the `\tests` directory which usually contain the `.Tests.csproj` files, but it seems like `System.Private.Xml` tests structure is more complicated. Maybe adding a note to the docs makes sense, would you mind helping with that?

**Comment by lovettchris** [comment]
And dotnet test  is working on the solution and seems to be running in more reasonable times.  And yes, I think I am working with a debug build of dotnet runtime.

**Comment by lovettchris** [comment]
I'm considering this resolved for now.

**Comment by safern** [comment]
> And yes, I think I am working with a debug build of dotnet runtime.

That will cause the test slowness inside VS and outside of it, however VS will be waaaay slower. When building the repository I recommend using the `-rc Release` argument, that will tell the build infra to build the runtime with `Release` but the shared framework/libraries will still be `Debug` and that way the tests will run fast.

**Comment by lovettchris** [comment]
cool, thanks.
