### ISSUE TITLE
System.Text.Json: Deserialize not available in .NET Standard 2.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#51884]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SystemTextJson:-Deserialize-not-availa/1316679)._

---
[severity:Other]
I am working on a new framework. I tried to convert Json using System.Text.Json, not Newtonsoft.Json, but Deserialize doesn't work.

Since Entity Framework Core 5.0 is used, it is implemented in the class library using .NET Standard 2.1, and the type entering TResult is included in .NET Standard 2.0.

### Environment
- Windows 10 version 20H2
- Visual Studio 2019 version 16.8.4
- WPF .NET 5.0
- Class Library : .NET 5.0, .NET Standard 2.0, .NET Standard 2.1

/// <summary>
        /// Makes an HTTP GET request to the given controller and returns the deserialized response content.
        /// </summary>
        public async Task GetAsync(string controller)
        {
            try
            {
                using (var client = BaseClient())
                {
                    var response = await client. GetAsync(controller);
                    string json = await response. Content.ReadAsStringAsync();
                    TResult obj = JsonSerializer.Deserialize(json);
                    return obj;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex. Message);
            }
            return default(TResult);
        }

json data : [{"viewId":"0001","viewType":"tab","viewCategoryType":"system","appType":"ui","viewName":"View Management","className":"Monster.Solutions.Modules.Ribbon.Views.TestA, Monster.Solutions.Modules.Ribbon","desc":"뷰 관리","isUse":true,"createDate":"2021-01-21T00:00:00","createUser":"admin","createView":"system","lastModifyDate":"2021-01-21T00:00:00","lastModifyUser":"admin","lastModifyView":"system"}]

! [image.png] (https://aka.ms/dc/image?name=B388bbfdf4a07436a82e70f394d516394637468136095863113_20210121-171328-image.png&tid=388bbfdf4a07436a82e70f394d516394637468136095863113)

I solved the problem by installing Newtonsoft.Json and modifying the code slightly.

---
#### Feedback Bot on 1/22/2021, 00:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment]
In order to better understand your issue we would need to see the definition of the type that the json is being serialized into (based on your screenshot it's the `SysView` class). Would it be possible to share a standalone project that contains a minimal reproduction of the problem?

**Comment by eiriktsarpalis** [comment]
The OP has been redirected to this issue in the original ticket so hopefully they will see this eventually.

**Comment by eiriktsarpalis** [comment]
Given that there hasn't been any recent activity I'm going to close this issue for now. We can reopen in the future if new information comes by.
