### ISSUE TITLE
sealed odbc classes

### ISSUE THREAD

**Issue by 3GDXC** [dotnet/runtime#51885]
Please allow developers to derive from ODBC classes; some drivers that conform to ODBC also have additional attributes, methods it would be good to allow the developers to use system.data.odbc as a base and implement additional functionality to extend driver implementation.

**Comment by ajcvickers** [comment]
Unsealing methods can have knock-on effects for compatibility. Also, the ODBC provider is largely in maintenance mode. Therefore, we don't plan to make this change.
