### ISSUE TITLE
RuntimeLicenseContext.GetSavedLicenseKey throws exception for dynamic assemblies

### ISSUE THREAD

**Issue by BickelLukas** [dotnet/runtime#51924]
### Description

https://github.com/dotnet/runtime/blob/1c9e2009d9942a6df31daad8c912c68446856fa2/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/DesigntimeLicenseContext.cs#L80-L83

In the `System.ComponentModel.Design.RuntimeLicenseContext` the following lines state that `Location` returns null for in memory loaded assemblies. 

However `System.Reflection.Emit.InternalAssemblyBuilder` throws an exception when `Location` is accessed:

https://github.com/dotnet/runtime/blob/1c9e2009d9942a6df31daad8c912c68446856fa2/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/AssemblyBuilder.cs#L105

### Configuration

.NET 5.0
Windows x86

**Comment by safern** [comment]
@jkotas, @vitek-karas is this expected. It seems like this was changed on: https://github.com/dotnet/runtime/commit/b19d7980c6a0e1f03312c8c2033fcbd13822378f and on the PR review this is what was suggested to be done.

**Comment by jkotas** [comment]
We can either revert offending bit in the PR, or change the AssemblyBuilder `string Location` to just return empty string. I would vote for the latter.

**Comment by safern** [comment]
> to just return empty string. I would vote for the latter.

Sounds good. It seems like this regressed 3.1 -> 5.0 on `RuntimeLicenseContext.GetSavedLicenseKey` I think we should port it back to 5.0?

**Comment by eerhardt** [comment]
Moving to System.Reflection.Emit to change the `AssemblyBuilder.Location` behavior to return `string.Empty` as proposed by @jkotas above.

**Comment by pedrobsaila** [comment]
Hi, I made a PR for this issue #57396

**Comment by vitek-karas** [comment]
Thanks to @pedrobsaila #57396 is merged and should fix the underlying issue in AssemblyBuilder. Could you please validate that the issue is fixed (in a couple of days one the fix makes it into the nightly build).

**Comment by BickelLukas** [comment]
Seems to work now!
