### ISSUE TITLE
Synchronous operation is not supported when a ConnectCallback is specified on the SocketsHttpHandler instance.

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#51933]
### Description

System.NotSupportedException: 'Synchronous operation is not supported when a ConnectCallback is specified on the SocketsHttpHandler instance.'

I feel like I've been cheated. I remember being involved in the requirements phase of ConnectCallback so that we'd be finally able to use the stock HttpClient; but the actual implementation didn't work very well.

Found early on that if you tie into ConnectCallback, you can't access the base instance because it's declared private and it wasn't in ConnectCallback as described in the development item. So I wrote what I refer to as "run your mouth off code" to actually make the connection. (I only needed to get the socket out of the network stream so I can P/Invoke to set custom keepalive parameters but I have to write the whole thing.) But knowing from the beginning I needed sync code to work, I wrote both a sync and an async version of this.

And I did what is necessary to prevent deadlocks when calling the sync code, that is keep sync and async to separate instances and turn off HTTP/2 on the sync instance. I added diagnostics to check if anything tried to call something async (and if it happens internally I was going to file a low priority issue and redirect the call to the sync call). But rather I grind to a halt on this error.

If the programmer has gone so far as to set up synchronous use of HttpClient and set up a ConnectCallback; their choice should be honored, and the ConnectCallback invoked and assumed or asserted to actually be synchronous. Second-guessing the programmer who set all this up and arbitrarily saying no is a mistake.

### Configuration

.NET 5.0.3

### Regression?

No. New API in .NET 5.0.

### Other information

Workaround: continue using custom HTTP client

To fix, replace the line reading
`throw new NotSupportedException(SR.net_http_sync_operations_not_allowed_with_connect_callback);` at https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1325 with `Settings._connectCallback(host, port, cancellationToken).GetAwaiter().GetResult()`. It takes a few more lines to assert it was really synchronous if you chose to though.

**Comment by antonfirsov** [comment]
This has been addressed for .NET 6 in #45300.

**Comment by jhudsoncedaron** [comment]
@antonfirsov : Oh good. Easy "backport" for the next .NET 5 patch then. The code's all different so it won't cherry pick but copy/paste will work.

**Comment by antonfirsov** [comment]
Our process defines a very high bar for backports. It has to be a regression (not the case), or an adaption/migration blocker confirmed by multiple customers. Personally, I don't believe this will meet the bar, but let's see the verdict in the triage.

**Comment by jhudsoncedaron** [comment]
Just discovered you can't trick SendAsync() into being sync by returning a stream that isn't async from ConnectCallbackAsync. It deadlocks in EnsureReadAheadAndPollRead. I have no way to make the stock HttpClient work.

**Comment by karelz** [comment]
Triage: This affects only sync API - the impact should be fairly limited. If we have more upvotes, or the impact is huge, we could consider backport. Another alternative is to use 6.0 Previews for now.
How impactful is it for your application? Why do you need to use sync -- can you help us understand that?

**Comment by jhudsoncedaron** [comment]
Trying to use async results in async over sync over async which deadlocks the application. We've been locked out of remote desktop onto the production servers before.

When the application was young and we were first getting these, somebody published a (now-deleted) blog post on how to make async calls synchronous, so we use it. Trying to push the async down got stuck in System.Linq (in particular IEnumerable) and into object constructors, and into various other things. ValueTask didn't exist yet, and running up and down the stack all the time was too expensive, so the whole application of hundreds of thousands of lines got written with a synchronous API between the application and web servers.

Then the deadlocks started appearing. I scoured the framework for the causes and one by one started rooting them out. I had located the deadlock on out of memory on reading file asynchronously first and fixed that one. The second one found was in network monitor, which turned out to not actually affect us. Only then did we discover the code from the blog was just plain old wrong, and nothing like it could ever work. You may have seen the posts where I kept on trying to make private async contexts so that everybody calling async below it got intercepted. That was of this problem. I didn't need a scheduler. I needed to get rid of the deadlock where one async job was waiting for another in Task.GetAwaiter().GetResult(). Finally having no solution I wrote a custom http client and the deadlocks all but vanished. [There's actually one left. If you're actually out of memory in the bottom-level async file handler, the unhandled exception handler dies trying to transition back to managed code and fails to kill the process. This is really difficult to simulate because if the native heap has any room at all the code kills the process correctly.]

But everybody on my team wants to upgrade to .NET 5 for the specific purpose of getting rid of the custom http client. It's actually kind of buggy in ways that don't matter when our application is talking to itself, but it doesn't like proxy servers. And nobody is willing to ship a .net preview release to customers.

**Comment by karelz** [comment]
Triage: Thanks for info. If there are more reports of the issue blocking people, we can consider backporting to 5.0. There does not seem to be enough evidence at this moment. Closing for now.
