### ISSUE TITLE
Change namespace name `System.Text.Json.Node` to `System.Text.Json.Nodes`

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#51937]
As a change to API issue https://github.com/dotnet/runtime/issues/47649, change the namespace
`System.Text.Json.Node`
to
`System.Text.Json.Nodes`

See https://github.com/dotnet/runtime/issues/51637#issuecomment-825995129 for context.

The namespace includes the classes:
`JsonNode`
`JsonArray`
`JsonObject`
`JsonValue`

**Comment by bartonjs** [comment]
Renaming the namespace is approved as proposed

System.Text.Json.Node => System.Text.Json.Node**s**
