### ISSUE TITLE
[Perf] Regression in deps.json Size for Blazor Pizza App

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#51944]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline Commit | [c0d51224117c932288bc5eadbd3493fed10bc299](https://github.com/dotnet/runtime/commit/c0d51224117c932288bc5eadbd3493fed10bc299)
Baseline Publish | [Baseline](https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-dd243180b01749979b/SOD%20-%20Pizza%20App%20-%20Publish/Publish-blazorpizza.zip?sv=2019-07-07&se=2021-07-25T18%3A16%3A16Z&sr=c&sp=rl&sig=RjZd97iZgG96gMffQax19Bd7Y2emfbsOSLdsWvNaAA8%3D)
Compare Commit | [ac82799250fe42c8ba2941aef487aca94ecf04cc](https://github.com/dotnet/runtime/commit/ac82799250fe42c8ba2941aef487aca94ecf04cc)
Compare Publish | [Compare](https://helixri107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c2f672f4357048c98e/SOD%20-%20Pizza%20App%20-%20Publish/Publish-blazorpizza.zip?sv=2019-07-07&se=2021-07-25T22%3A52%3A25Z&sr=c&sp=rl&sig=rRgu9ztoRUB1ziNJM7qaek24oWxZi8FrAD2N810ekkc%3D)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c0d51224117c932288bc5eadbd3493fed10bc299...ac82799250fe42c8ba2941aef487aca94ecf04cc)

### Regressions in SOD - Pizza App - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - Pizza App - Publish - pub/BlazingPizza.ComponentsLibrary.deps.json](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 61.65 KB | 62.39 KB | 1.01 | 0.00 | | |
[SOD - Pizza App - Publish - Aggregate - .json](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 138.66 KB | 140.14 KB | 1.01 | 0.00 | | |
[SOD - Pizza App - Publish - pub/BlazingPizza.ComponentsLibrary.pdb](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 12.32 KB | 12.44 KB | 1.01 | 0.00 | | |
[SOD - Pizza App - Publish - pub/wwwroot/_framework/System.Net.Primitives.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 2.58 KB | 2.63 KB | 1.02 | 0.00 | | |
[SOD - Pizza App - Publish - pub/BlazingComponents.deps.json](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 61.60 KB | 62.34 KB | 1.01 | 0.00 | | |
[SOD - Pizza App - Publish - pub/wwwroot/_framework/System.Net.Http.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 5.90 KB | 5.97 KB | 1.01 | 0.00 | | |
[SOD - Pizza App - Publish - pub/wwwroot/_framework/dotnet.timezones.blat.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 70.18 KB | 72.20 KB | 1.03 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_27_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Pizza%20App%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - Pizza App - Publish*'
```
<details>

#### SOD - Pizza App - Publish

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by eerhardt** [comment]
A couple of notes:

1. I don't think the .deps.json files are actually part of the "published" output of a Blazor WASM app. So I'm not sure measuring their sizes is beneficial.
2. The changes in the .deps.json file include these entries:
![image](https://user-images.githubusercontent.com/8291187/116306371-969a5200-a76a-11eb-9404-368e7857b1ff.png)
Which I believe are caused from #51854 and #51853. cc @ViktorHofer

**Comment by DrewScoggins** [comment]
I see. I will change these tests to just measure the size in the wwwroot directory, as that seems like the place where we actually publish the WASM app.

**Comment by ViktorHofer** [comment]
> Which I believe are caused from #51854 and #51853. cc @ViktorHofer

Is there an issue with these changes?

**Comment by eerhardt** [comment]
> Is there an issue with these changes?

I'm not sure. Are they expected to be in the `.deps.json` files when they weren't before?

**Comment by ViktorHofer** [comment]
> I'm not sure. Are they expected to be in the .deps.json files when they weren't before?

How should I interpret the diff? Is the right hand side (the removal) with my changes or without? I don't know about which app's deps.json we are talking about? How is Cng and OpenSsl in that app referenced?

**Comment by eerhardt** [comment]
> How should I interpret the diff?

The left side is the "baseline", the right side is "after". The deps.json file got larger after the change, since the entries were added to it.

**Comment by ViktorHofer** [comment]
> Ok, then that explains why they are showing up. So it is expected then if they got moved inbox.

Yes, I believe moving them inbox results in them showing up in the deps.json.

**Comment by eerhardt** [comment]
Closing. See above reasoning:

1. We shouldn't be tracking deps.json file sizes because they are not part of the published Blazor WASM app.
2. These changes are expected.
