### ISSUE TITLE
[tvOS] ThrowsNullReferenceException causing hangs in tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51949]
System.ComponentModel.TypeConverter.Tests
Ctor_NullProperties_ThrowsNullReferenceException
Description_GetWithNullProperties_ThrowsNullReferenceException
Description_SetWithNullProperties_ThrowsNullReferenceException
Text_GetWithNullProperties_ThrowsNullReferenceException
Category_GetWithNullAttributes_ThrowsNullReferenceException
Description_GetWithNullAttributes_ThrowsNullReferenceException
DesignTimeOnly_GetWithNullAttributes_ThrowsNullReferenceException
DisplayName_GetWithNullAttributes_ThrowsNullReferenceException
IsBrowsable_GetWithNullAttributes_ThrowsNullReferenceException

System.Composition.Hosting.Core.Tests
AddBoundInstance_NullInstance_ThrowsNullReferenceExceptionOnDisposal
GetOrCreate_NullActivator_ThrowsNullReferenceException
GetOrCreate_NullOperation_ThrowsNullReferenceException
Dependencies_GetWhenNull_ThrowsNullReferenceException
GetDescriptor_GetWhenNull_ThrowsNullReferenceException

System.Diagnostics.StackTrace.Tests
System.Diagnostics.Tests.StackFrameExtensionsTests.HasSource_NullStackFrame_ThrowsNullReferenceException
System.Diagnostics.Tests.StackFrameExtensionsTests.HasILOffset_NullStackFrame_ThrowsNullReferenceException
System.Diagnostics.Tests.StackFrameExtensionsTests.HasMethod_NullStackFrame_ThrowsNullReferenceException

System.Drawing.Common.Tests
System.Drawing.Printing.Tests.PreviewPrintControllerTests.OnStartPage_InvokeNullDocument_ThrowsNullReferenceException
System.Drawing.Printing.Tests.PreviewPrintControllerTests.OnStartPage_InvokeNullEventArgs_ThrowsNullReferenceException
System.Drawing.Printing.Tests.PreviewPrintControllerTests.OnStartPage_PrintNotStarted_ThrowsNullReferenceException
System.Drawing.Printing.Tests.PreviewPrintControllerTests.OnStartPrint_InvokeNullDocument_ThrowsNullReferenceException
System.Drawing.Tests.SystemFontsTests.GetFontByName_NoSuchName_ReturnsNull(systemFontName: "")

System.Globalization.Tests
System.Globalization.Tests.DateTimeFormatInfoMonthGenitiveNames.MonthGenitiveNames_FormatWithNull_ThrowsNullReferenceException
System.Globalization.Tests.DateTimeFormatInfoAbbreviatedMonthGenitiveNames.AbbreviatedMonthGenitiveNames_FormatWithNull_ThrowsNullReferenceException
System.Globalization.Tests.DateTimeFormatInfoMonthNames.MonthNames_FormatWithNull_ThrowsNullReferenceException
System.Globalization.Tests.DateTimeFormatInfoAbbreviatedMonthNames.AbbreviatedMonthNames_FormatWithNull_ThrowsNullReferenceException
System.Globalization.Tests.DateTimeFormatInfoDayNames.DayNames_FormatWithNull_ThrowsNullReferenceException

System.Linq.Expressions.Test
System.Linq.Expressions.Tests.CallTests.Call_InstanceNullInside_ThrowsNullReferenceExceptionOnInvocation(useInterpreter: True)

System.Linq.Queryable.Test
System.Linq.Tests.CastTests.CastingNullToNonnullableIsNullReferenceException

System.Linq.Tests
System.Linq.Tests.CastTests.CastingNullToNonnullableIsNullReferenceException

System.Memory.Tests
System.SpanTests.MemoryMarshalTests.GetArrayDataReference_NullInput_ThrowsNullRef

System.Runtime.CompilerServices.Unsafe.Tests
System.Runtime.CompilerServices.UnsafeTests.NullRef

System.Runtime.Extensions.Tests
System.Tests.EnvironmentTests.CurrentDirectory_Null_Path_Throws_ArgumentNullException

System.Runtime.InteropServices.Tests
System.Runtime.InteropServices.Tests.TypeLibImportClassAttributeTests.Ctor_NullImportClass_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.CollectionsMarshalTests.GetValueRefOrNullRefClass
System.Runtime.InteropServices.Tests.ComSourceInterfacesAttributeTests.Ctor_NullSourceInterfaceType1_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.ComSourceInterfacesAttributeTests.Ctor_NullSourceInterfaceType2_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.ComSourceInterfacesAttributeTests.Ctor_NullSourceInterfaceType3_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.ComSourceInterfacesAttributeTests.Ctor_NullSourceInterfaceType4_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.CollectionsMarshalTests.GetValueRefOrNullRefValueType
System.Runtime.InteropServices.Tests.PtrToStructureTests.PtrToStructure_ZeroPointerWithType_ReturnsNull
System.Runtime.InteropServices.Tests.ComAwareEventInfoTests.Ctor_NullType_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.ComAwareEventInfoTests.Properties_NoSuchEvent_ThrowsNullReferenceException
System.Runtime.InteropServices.Tests.ComAwareEventInfoTests.Methods_NoSuchEvent_ThrowsNullReferenceException

**Comment by vargaz** [comment]
Is this for simulator or device ? How can I reproduce this ?

**Comment by mdh1418** [comment]
This is tvOSSimulator x64, which I built with `./build.sh -os tvOSSImulator -arch x64 -c Debug`. I have been running via 
 `./dotnet.sh build /t:Test /p:TargetOS=tvOSSimulator /p:TargetArchitecture=x64 /p:Configuration=Debug src/libraries/System.Diagnostics.StackTrace/tests/System.Diagnostics.StackTrace.Tests.csproj`
