### ISSUE TITLE
Stale narrowing check for tail calls in importer

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#51957]
As noted in https://github.com/dotnet/runtime/pull/51903, the following check seems to be stale:
https://github.com/dotnet/runtime/blob/9a318320ca245bef064a5d9a540ff75e00ac096f/src/coreclr/jit/importer.cpp#L7762-L7768 We should remove it.

**Comment by sandreenko** [comment]
I think the problem could be with native calls that could have different normalizing rules, but maybe with @jkoritzinsky changes we can filter out such calls.

**Comment by SingleAccretion** [comment]
[Related transform in morph](https://github.com/dotnet/runtime/blob/f372f6b5fd49648c6742ded9f609feea5e4013c3/src/coreclr/jit/morph.cpp#L12799).
