### ISSUE TITLE
API Proposal: C# 10 interpolated strings support, part 3

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#51962]
## Background and Motivation

[Part 1](https://github.com/dotnet/runtime/issues/50601) and [part 2](https://github.com/dotnet/runtime/issues/50635) added APIs to support the improved interpolated string literal feature in C# 10. After a bit more design in the space, we want to make a few minor changes to the names and add a new attribute to help improve the authoring and usage experience for users.

The general driving goal here was to standardize the names builder types use. It is expected that our guidance to API authors will be "Your interpolated string builder types should start with the words `InterpolatedString` and end with `Builder`". This convention will help make it clearer for users when something is a valid builder type.

## Updated API: `InterpolatedStringDefaultBuilder`

We rename `InterpolatedStringBuilder` to `InterpolatedStringDefaultBuilder`. This is being done to avoid confusion with the new attribute.

```cs
-    public ref struct InterpolatedStringBuilder
+    public ref struct InterpolatedStringDefaultBuilder
```

## Proposed API: `InterpolatedStringBuilderAttribute`

This attribute marks a type as being a valid builder type. This is a change from the existing proposal, where the validity of the conversion was being determined from doing a bunch of overload resolution. This should make errors more sane and helpful to end users.

Open question: Should we allow this on interfaces as well? With abstract statics in interfaces, it would theoretically be possible to use type parameter constrained to an interface as a builder type, but that would only be valid if the interface can be attributed with this.

```cs
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class InterpolatedStringBuilderAttribute : Attribute
    {
        public InterpolatedStringBuilderAttribute()
        {
        }
    }
}
```

We then update the structs defined in Parts 1 and 2 as follows, to add the attribute and also standardize the naming of the other struct types with the rules mentioned above:

```cs
namespace System.Runtime.CompilerServices
{
+   [InterpolatedStringBuilder]
    public ref struct InterpolatedStringDefaultBuilder ...

+   [InterpolatedStringBuilder]
-   public ref struct InterpolatedSpanBuilder ...
+   public ref struct InterpolatedStringSpanBuilder ...
}

namespace System.Text
{
    public sealed class StringBuilder
    {
+       [InterpolatedStringBuilder]
-       public struct InterpolatedAppendFormatBuilder ...
+       public struct InterpolatedStringAppendFormatBuilder ...
    }
}
```

**Comment by KalleOlaviNiemitalo** [comment]
> ```C#
> public bool UseLazyComputation { get; }
```

> ```diff
> +   [InterpolatedStringBuilder(UseLazyComputation = true)]
>     public ref struct InterpolatedSpanBuilder ...
> ```

Does `UseLazyComputation` need a `set` accessor as well?

**Comment by 333fred** [comment]
> Does `UseLazyComputation` need a `set` accessor as well?

That would be helpful, wouldn't it 😅

**Comment by FilipToth** [comment]
I don't really see much use in this API. The user can do all that themselves and execute the methods whenever they want. Do you have any use-case scenarios where this would be simpler or more efficient that you could share with us?

**Comment by 333fred** [comment]
> I don't really see much use in this API. The user can do all that themselves and execute the methods whenever they want. Do you have any use-case scenarios where this would be simpler or more efficient that you could share with us?

I would suggest reading through the linked part one and two proposals, and the language feature they are here to support. Most of these apis will not be used directly by consumers.

**Comment by 333fred** [comment]
LDM met today, and rejected the idea of `UseLazyComputation`. The property and explanation has been removed from the proposal.

**Comment by michalczerwinski** [comment]
One thing which would be really useful to include in this proposal is some way of splitting string format into constant literals.
I stumbled upon this problem trying to implement feature for EF Core to allow string.Format/interpolation to be translated into SQL. 

Currently the string.Format parsing is encapsulated in ValueStringBuilder.AppendFormatHelper. If we can make it public or at least some part of it it would be beneficial.

**Comment by bartonjs** [comment]
After a long discussion we think the best convention we'll come up with is the suffix "InterpolatedStringHandler"

Therefore, the renames should be

* InterpolatedStringHandlerArgumentAttribute
* InterpolatedStringHandlerAttribute
* DefaultInterpolatedStringHandler
* SpanInterpolatedStringHandler
* StringBuilder+AppendFormatInterpolatedStringHandler

The attribute is otherwise good as proposed

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class InterpolatedStringHandlerAttribute : Attribute
    {
        public InterpolatedStringHandlerAttribute()
        {
        }
    }
}
```

**Comment by bartonjs** [comment]
For what it's worth, the `StringBuilder+AppendFormatInterpolatedStringHandler` type may want a further rename, I don't believe we updated the name after expanding it to be used on StringBuilder.Append and AppendLine.  So it's _probably_ `StringBuilder+AppendInterpolatedStringHandler`.

**Comment by stephentoub** [comment]
> SpanInterpolatedStringHandler

We previously decided this was MemoryExtensions+InterpolatedTryWriteBuilder.  So should it now be MemoryExtensions+TryWriteInterpolatedStringHandler, or was the switch back to "Span" intentional?

> StringBuilder+AppendFormatInterpolatedStringHandler

We'd already previously decided this StringBuilder+InterpolatedAppendBuilder, so, yes, it should now be StringBuilder+AppendInterpolatedStringHandler.

**Comment by 333fred** [comment]
> > SpanInterpolatedStringHandler
> 
> We previously decided this was MemoryExtensions+InterpolatedTryWriteBuilder.  So should it now be MemoryExtensions+TryWriteInterpolatedStringHandler, or was the switch back to "Span" intentional?

If we did that's my fault, as I missed the rename. So yes, it should by TryWrite instead of Span.

**Comment by bartonjs** [comment]
Thanks for catching the clerical errors, @stephentoub.  I went ahead and updated the "AppendFormat" and "Span" entries to have their correctly agreed upon elements used with the current pattern.

**Comment by tannergooding** [comment]
@stephentoub, could you mark this as 6.0.0 or 7.0.0 as appropriate?
