### ISSUE TITLE
System.Text.Json.JsonSerializer does not skip members with `default` DateTime values

### ISSUE THREAD

**Issue by RaptorCZ** [dotnet/runtime#51975]
### Description

I have web service proxy generated using Svcutil. I want to serialize result to JSON but it results empty value. Newtonsoft serializer works fine.

Check this fiddle:
https://dotnetfiddle.net/wNtRuQ

Default serializer generates empty object. 
With some options, it generates properties, but wrong ones. If property is not Specified, it generates defaults.
Newtonsoft serializer generates correct json.

How to setup JsonSerializer to get the same result?

**Comment by eiriktsarpalis** [comment]
The issue is in line 54 in your snippet: The member `getVozidloResponse1` in `getVozidloResponse` is a field and therefore ignored by default. The second example works because you enabled field serialization, but simply changing the field into a property in the parent should suffice:
```diff
- public extKnzVozidloDTO[] getVozidloResponse1;
+ public extKnzVozidloDTO[] getVozidloResponse1 { get; set; }
```

**Comment by RaptorCZ** [comment]
Ok I understand, that's the 1st problem.
And now how to handle "not specified" properties and handle all as null. To get the same result as from Newtonsoft serializer.

**Comment by eiriktsarpalis** [comment]
You mean serializing `default` value types like `DateTime` as `null`? The current behaviour is by design, have you tried converting your properties to `DateTime?`?

**Comment by RaptorCZ** [comment]
Sample is from autogenerated proxy class from web service. I'm just consumer of that class, can't edit anything.

Newtonsoft serializer generates:
```
"datumPrvniRegistraceCRSpecified": false
```
and ignores 
```
datumPrvniRegistraceCR
```

But MS serializer generates:
```
"datumPrvniRegistraceCR": "0001-01-01T00:00:00",
"datumPrvniRegistraceCRSpecified": false
```

**Comment by eiriktsarpalis** [comment]
In that case I would recommend filing an issue with the maintainers of the the library to a) generate properties instead of fields and b) use nullable types for optional value types.

The current behaviour of System.Text.Json w.r.t. handling of `default` value types is by design.
