### ISSUE TITLE
Implement optimized CopyToAsync for StreamPipeReader

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#51972]
The [`StreamPipeReader`](https://github.com/dotnet/runtime/blob/6cde32922e8329c75b2db3e028c7b80b11afd0a8/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeReader.cs) implementation can be optimized by immediately writing all of the buffered bytes to the reader then delegating to CopyToAsync on the underlying Stream implementation.

**Comment by iSazonov** [comment]
StreamPipeReader link is broken.

**Comment by davidfowl** [comment]
Man you're fast 😄
