### ISSUE TITLE
Instantiation over object aborts devirtualization

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#51974]
Filing an issue per https://github.com/dotnet/runtime/pull/51918/files#r621402011.

```csharp
using System;
using System.Runtime.CompilerServices;

class Program
{
    static int Main()
    {
        MyStruct<Atom> s = default;
        return ((IFoo)s).GetTheType() == typeof(Atom) ? 100 : -1;
    }
}

interface IFoo
{
    Type GetTheType();
}

struct MyStruct<T> : IFoo
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    Type IFoo.GetTheType() => typeof(T);
}

class Atom { }
```

When compiling the above with crossgen2 ("normal mode", with optimizations), we devirtualize the call to `GetTheType` (in crossgen2, `resolveVirtualMethod` in CorInfoImpl.cs returns `true`).

If we however replace `MyStruct<Atom>` with `MyStruct<object>`, the devirtualization fails. Presumably because `object` is considered crossing the version boundary. Maybe it shouldn't be a version bubble boundary.

**Comment by davidwrighton** [comment]
Did not have time to do this in the 6.0 release. Pushing to 7.0

**Comment by davidwrighton** [comment]
This works now.
