### ISSUE TITLE
Incorrect devirtualization in shared generic context

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#51982]
```csharp
using Internal;
using System;
using System.Runtime.CompilerServices;

Console.WriteLine(Foo<Atom1>.Call());
Console.WriteLine(Foo<Atom2>.Call());


interface IFooable<T>
{
    public string DoFoo(T x);
}

class Base : IFooable<Atom2>
{
    string IFooable<Atom2>.DoFoo(Atom2 x) => "Base";
}

sealed class Foo<T> : Base, IFooable<T>
{
    string IFooable<T>.DoFoo(T x) => "Foo";

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static string Call()
    {
        var f = new Foo<T>();
        return ((IFooable<T>)f).DoFoo(default) + ((IFooable<Atom2>)f).DoFoo(null);
    }
}

class Atom1 { }
class Atom2 { }
```

Compile the above with `csc /noconfig /nostdlib Program.cs /r:System.Private.CoreLib.dll` and run with corerun.

Output:

```
FooBase
FooFoo
```

Now add `/O` to the csc command line.

Output:

```
FooFoo
FooFoo
```

**Comment by MichalStrehovsky** [comment]
Note this hits problem in both the VM and in crossgen2. The repro steps are without R2R, but there's a similar problem when compiled with crossgen2.

**Comment by mangod9** [comment]
Assigning to @trylek since he might be potentially working in the related typesystem code.

**Comment by davidwrighton** [comment]
@AndyAyersMS, its absolutely do-able, but what I think is a more reasonable approach, is that a devirtualize to `IFooable<__Canon>` on a type which only implements 1 possible instantiation should perform the devirtualization, but when there are 2 possible candidate target types, to skip devirtualization. Multiple implementations of the same interface on a type are rare and generally not worth writing the extremely fragile logic that can make it work. I'm looking at that now.
