### ISSUE TITLE
System.Text.RegularExpressions.MatchCollection should implement IEnumerable<Match> and ICollection<Match>, not just the non-generic interfaces 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#52012]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemTextRegularExpressionsMatchColl/1384389)._

---
The following code doesn't compile:

```
Regex sampleRegex = /* something */;
string sampleInputString = /* something */;
Func<Match, ResultType> sampleSelector = /* something */;

var matchResults = sampleRegex.Matches(sampleInputString). Select(sampleSelector);
```
it has to be rewritten to

```
Regex sampleRegex = /* something */;
string sampleInputString = /* something */;
Func<Match, ResultType> sampleSelector = /* something */;

var matchResults = sampleRegex.Matches(sampleInputString). Cast<Match>(). Select(sampleSelector);
```

According to the Object Browser, System.Text.RegularExpressions.MatchCollection implements only System.Collections.ICollection and System.Collections.IEnumerable but neither System.Collections.Generic.ICollection<Match> nor System.Collections.Generic.IEnumerable<Match> as one would expect.

Another example:

```
            var thisRegex = new Regex("(\\d+)");

var matches = thisRegex.Matches("abc123def456");
            
var firstMatch = matches[0];
            Debug.Assert(firstMatch.Success);

foreach (var match in matches) {
                Debug.Assert(match. Success);
            }

```
firstMatch.Success is ok, but match. Success won't compile because match is an object instead of a Match.

---
#### Feedback Bot on 3/29/2021, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by terrajobst** [comment]
> The following code doesn't compile:

It does compile in .NET Core 2.0 or higher (fixed with #13933). We don't have any plans to backport such a change to .NET Framework though.
