### ISSUE TITLE
Test failure System.Net.WebSockets.Tests.WebSocketDeflateTests.PayloadShouldHaveSimilarSizeWhenSplitIntoSegments

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52031]
Run: [runtime 20210428.85](https://dev.azure.com/dnceng/public/_build/results?buildId=1112663&view=ms.vss-test-web.build-test-results-tab&runId=33916946&resultId=139904&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm-CoreCLR_checked-(Alpine.313.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-arm32v7-20210414141857-1ea6b0a
 -System.Net.WebSockets.Tests.WebSocketDeflateTests.PayloadShouldHaveSimilarSizeWhenSplitIntoSegments(windowBits: 15)
```

**Error message:**
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs:line 564
   at System.Net.WebSockets.Tests.WebSocketDeflateTests.PayloadShouldHaveSimilarSizeWhenSplitIntoSegments(Int32 windowBits) in /_/src/libraries/System.Net.WebSockets/tests/WebSocketDeflateTests.cs:line 444
--- End of stack trace from previous location ---
```

**Comment by zlatanov** [comment]
To me this issue seems unrelated to the reverted "fix ber scanf/printf". For some reason, unknown to me, on ARM architecture, this test takes more than 5 seconds to complete.

I have created this test to check that deflate context takeover works as expected, but it is a bit speculative on the compression algorithm. We can either increase the timeout (or even remove it entirely and depend on xunit cancelling the test if something hangs), or can even delete this test, because if in the future the underlying compression ratio changes for some reason, this test will be outdated and can start to fail.

//cc @CarnaViire

**Comment by CarnaViire** [comment]
Timeouts like that tend to be unreliable in our CI, if the test is executed on a heavily loaded machine, it may take more than expected... That being said, we should first gather statistics, how common is this test failure, or it was a one-off. I'll search for the stats.

Btw, how could the algorithm change that much so the aggregation of compressed parts of the message will be much bigger/smaller than the compressed whole message?.. wouldn't it be a different/new algo then, not DEFLATE as it was described in RFC?

**Comment by zlatanov** [comment]
> Btw, how could the algorithm change that much so the aggregation of compressed parts of the message will be much bigger/smaller than the compressed whole message?.. wouldn't it be a different/new algo then, not DEFLATE as it was described in RFC?

The deflate only describes the structure/format of the data. The algorithm is implementation detail that might change (for example zlib-intel vs classic zlib), memory constraints, different performance optimizations that might trade compression ratio for speed.

**Comment by CarnaViire** [comment]
I see that it is failing quite regularly for 14 and 15 window bits for

alpine.313.arm32
alpine.312.arm64
ubuntu.1804.arm32
ubuntu.1804.arm64

I'm ok with removing the test as we cannot depend on it from the algorithm's point of view, but... Interesting that it is not failing, but hanging, and it's only on arm. I'm interested in what will happen if we just remove our timeout, whether it will complete after some more time, or will continue hanging until killed as LongRunningTest 🤔

**Comment by zlatanov** [comment]
> I'm interested in what will happen if we just remove our timeout, whether it will complete after some more time, or will continue hanging until killed as LongRunningTest

There is only one way to find out 😎

However I have the nagging suspicion that there is some problem with `Random` on ARM. 
There is nothing else in this test that is different from the other deflate tests. Some of them should actually be more expensive than this one.

Is there any way I could run a test on ARM, or the only way would be to create e DRAFT PR that I would delete later?

**Comment by zlatanov** [comment]
@CarnaViire I created a PR, we wait now to see the run times for the test. If I am correct, the fix should be successful. If however you feel that we should remove the test, let me know.

**Comment by CarnaViire** [comment]
Would it defeat the purpose of the test to make the message smaller, e.g. frame x5, not x10?
I also wanted to ask about NextBytes, but you've done that already 🙂

And as for running a test on ARM, I'd say CI is the best way I know of.

**Comment by zlatanov** [comment]
> Would it defeat the purpose of the test to make the message smaller, e.g. frame x5, not x10?

It would not. 5 is as good a number as 10 in this case 😊 Let's see how the CI build turns out, I think the issue here was the usage of `Random`.

**Comment by BruceForstall** [comment]
@CarnaViire 

> And as for running a test on ARM, I'd say CI is the best way I know of.

@karelz should be able to arrange for you to get access to an ARM machine if needed.

**Comment by zlatanov** [comment]
@CarnaViire can we run this code in one of the failing environments (alpine.313.arm32, alpine.312.arm64, ubuntu.1804.arm32, ubuntu.1804.arm64):

```c#
using System;
using System.Diagnostics;

var random = new Random(0);
var stopwatch = Stopwatch.StartNew();

for (int i = 0; i < 1_000_000; ++i)
{
    random.Next(maxValue: 10);
}

stopwatch.Stop();
Console.WriteLine(stopwatch.Elapsed);
```
It shouldn't take more than a few hundred milliseconds on the slowest silicon. On my i7 machine it takes `00:00:00.0074053`.

//cc @danmoseley @BruceForstall @karelz

**Comment by karelz** [comment]
@BruceForstall I have no idea how to get hands on ARM machines -- perhaps infra folks can help here? @ViktorHofer any idea?

**Comment by ViktorHofer** [comment]
cc @MattGal

**Comment by danmoseley** [comment]
@zlatanov how would an issue with Random consistently only affect 14 and 15? 
I did not look at the code, do those values affect what zlib is asked to do?

**Comment by zlatanov** [comment]
Also to note why I don't think it's the zlib causing the delays - I have other tests that send / receive payloads of the same or bigger size, with totally random data, which is very hard to compress, and they don't time out.

**Comment by danmoseley** [comment]
Got it. Interesting. Apologies for crossing questions on the PR as well.

**Comment by BruceForstall** [comment]
@zlatanov Given this test continues to fail in some `runtime` pipeline runs, which is the PR innerloop, can you disable it until it has been investigated?

**Comment by danmoseley** [comment]
@BruceForstall this was done in #52086

I agree (this is a reminder to us all 🙂) that when a test fails regularly in CI we should disable it immediately if we can't fix it immediately.  We're good engineers and prefer to investigate and fix rather than disable anything, but that can happen while it's disabled. 🙂

**Comment by MattGal** [comment]
> @BruceForstall I have no idea how to get hands on ARM machines -- perhaps infra folks can help here? @ViktorHofer any idea?

I assume Viktor CC'ed me for this.  We have a limited # of ARM machines that can be accessed via SSH / RDP from appropriate source IPs, you can reach out to @ilyas1974 or myself if he's unavailable to borrow a machine.

**Comment by CarnaViire** [comment]
@zlatanov I was finally able to get access to and setup an ARM machine (failed to setup alpine, so using ubuntu.1804.arm64) to run the code with `Random` you've posted here https://github.com/dotnet/runtime/issues/52031#issuecomment-829906954. No breakthrough though... it shows around `00:00:00.0308034` on multiple runs.
I'll try to run and measure the whole test. If you have any experiments for this test you'd like to check, just send it and I'll run it for you.

**Comment by CarnaViire** [comment]
For the whole test too, I see at max `00:00:00.3995667` for 15 bits, nowhere near 5 seconds...

**Comment by danmoseley** [comment]
That's wacky -- we know from [Kusto ](https://github.com/dotnet/runtime/pull/52086#issuecomment-829720825) that it was *always* failing (for 14/15). Not even flaky. That includes Ubuntu.1804.arm64.

It's our own zlib, right? It's not an issue with which zlib is on the machine?

**Comment by karelz** [comment]
Looks like yet another one of the cases where chasing down test failures in CI is difficult without having access to the exact CI machine setup :( ... is there a way to get temporary access to one of the CI machines to confirm we can reproduce it there manually at least?

**Comment by CarnaViire** [comment]
As I understand it, I actually did use one of the CI machines that was excluded from the rotation for me: https://github.com/dotnet/core-eng/issues/13006. But because it's excluded, it's not getting the same load it did while it was in CI, so maybe that's the reason... I also ended up creating my own docker image for Ubuntu 18.04, but I doubt it could influence it that much? Or could it?
@danmoseley what makes you say it was *always* failing? We wouldn't have green CI when merging the original PR if that was the case, but we did...

**Comment by zlatanov** [comment]
Thanks @CarnaViire!

I still don't think this is related to zlib. @danmoseley we don't use machine wide installation of zlib. In case of ARM, we use the classic zlib instead of zlib-intel.

I will look at the build/tests outputs to see if I can find something interesting. As @CarnaViire suggested it might be related to how busy is the machine, but from `0.01` seconds to `7` seconds seem a bit too much for me. I don't expect the xunit runtime to launch more concurrent tests than there are CPUs. Also if this was the case we should see the total runtime for all the tests combined to be in order of magnitude slower than the other environments.

**Comment by zlatanov** [comment]
After looking again in the build logs, I don't think it's load related either. The run times are too consistent - almost `4 seconds` for 13 bits, `7 seconds` for 14 bits and `14 seconds` for 15 bits.

If it was load related, I expect we would have deviations, but we don't.

**Comment by danmoseley** [comment]
> @danmoseley what makes you say it was always failing?

I spoke imprecisely, I meant when it failed, it was always 14 or 15, try this query:

Execute: [Web](https://dataexplorer.azure.com/clusters/engsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAG2QQUvDQBCF74X%2bhyGnFtI0rTchhYoIESpoAz1vsq%2fNmuys7OwiEX%2b8aQp6EQZm5vH45jEVJLxBYh%2bE5rNveneGqTOsC8MMTyfnuzLACjn%2bXUr9r%2ffZ1ZNt7KW%2bGj5beNCTYSMtNO0K0iogGIvFNt9uVnerDeX3%2bbWW85liTdXwASoKSo6DjIeyF4TshPromg5BsmpMK3%2fCI879CJzU5AZ48IqbdkJ4nGXdQmlZW2U4uSaSaK3y5gvUuMhhsaR6oANC63RKtz%2bk9BoRse%2bNkpT2%2fhItOIzjASLqAvoBXTZNIzMBAAA%3d) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2QQUvDQBCF74X%2bhyGnFtI0rTchhYoIESpoAz1vsq%2fNmuys7OwiEX%2b8aQp6EQZm5vH45jEVJLxBYh%2bE5rNveneGqTOsC8MMTyfnuzLACjn%2bXUr9r%2ffZ1ZNt7KW%2bGj5beNCTYSMtNO0K0iogGIvFNt9uVnerDeX3%2bbWW85liTdXwASoKSo6DjIeyF4TshPromg5BsmpMK3%2fCI879CJzU5AZ48IqbdkJ4nGXdQmlZW2U4uSaSaK3y5gvUuMhhsaR6oANC63RKtz%2bk9BoRse%2bNkpT2%2fhItOIzjASLqAvoBXTZNIzMBAAA%3d&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAG2QQUvDQBCF74X%2bhyGnFtI0rTchhYoIESpoAz1vsq%2fNmuys7OwiEX%2b8aQp6EQZm5vH45jEVJLxBYh%2bE5rNveneGqTOsC8MMTyfnuzLACjn%2bXUr9r%2ffZ1ZNt7KW%2bGj5beNCTYSMtNO0K0iogGIvFNt9uVnerDeX3%2bbWW85liTdXwASoKSo6DjIeyF4TshPromg5BsmpMK3%2fCI879CJzU5AZ48IqbdkJ4nGXdQmlZW2U4uSaSaK3y5gvUuMhhsaR6oANC63RKtz%2bk9BoRse%2bNkpT2%2fhItOIzjASLqAvoBXTZNIzMBAAA%3d&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2QQUvDQBCF74X%2bhyGnFtI0rTchhYoIESpoAz1vsq%2fNmuys7OwiEX%2b8aQp6EQZm5vH45jEVJLxBYh%2bE5rNveneGqTOsC8MMTyfnuzLACjn%2bXUr9r%2ffZ1ZNt7KW%2bGj5beNCTYSMtNO0K0iogGIvFNt9uVnerDeX3%2bbWW85liTdXwASoKSo6DjIeyF4TshPromg5BsmpMK3%2fCI879CJzU5AZ48IqbdkJ4nGXdQmlZW2U4uSaSaK3y5gvUuMhhsaR6oANC63RKtz%2bk9BoRse%2bNkpT2%2fhItOIzjASLqAvoBXTZNIzMBAAA%3d&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished >= datetime(2021-3-1 0:00:00)
and Type == "System.Net.WebSockets.Tests.WebSocketDeflateTests"
and Branch == "refs/heads/main"
| summarize count() by Method, Result, QueueAlias, Arguments, Message
```

**Comment by danmoseley** [comment]
> After looking again in the build logs, I don't think it's load related either. The run times are too consistent - almost 4 seconds for 13 bits, 7 seconds for 14 bits and 14 seconds for 15 bits.

Which logs are these? I didn't think we retained data for individual tests unless they failed, and I thought you couldn't repro locally.

Something else I see from querying the failures: it never fails on 13, and it fails on 15 about twice as much as 14. When it fails for 14, it always fails for 15. (This is consistent with the "machine mysteriously slow" theory)

One other idea -- roll back #52086 and add a Stopwatch around each part of the test, including the Random loop, to measure how long each part takes. Put a try/catch for TaskCanceledException around the whole test, and if it's hit, then add those sub-times into the message. That will tell us where the time was spent. Ideally we'd do this locally on @CarnaViire 's ARM machine and just run the test over and over that way ?

**Comment by danmoseley** [comment]
This probably can be done with a simple console app, no xunit involved.

**Comment by zlatanov** [comment]
> Which logs are these? I didn't think we retained data for individual tests unless they failed, and I thought you couldn't repro locally.

The build logs seem to be retained for 60 days. If you go to the tests and filter them you can find the websocket tests for each of the platform. The run times are too consistent. You can try and find older builds (PRs that mentioned this issue) and you will see similar run times.

And because I originally used 5 seconds as cancellation timeout, having the test throw `TaskCanceledException` after 14 seconds is dubious.

![image](https://user-images.githubusercontent.com/2470527/117638069-2688c480-b18b-11eb-9123-b614c12fdbfe.png)

**Comment by CarnaViire** [comment]
I've found the difference between what I was running on my machine and what was failing in CI. I was running on Release runtime, but the test actually ran overtime on Checked runtime.
Here on Release runtime, the test takes the same 0.3s I was seeing
![image](https://user-images.githubusercontent.com/3184057/117713905-86588d00-b1d6-11eb-9eaf-068be8d00872.png)
And here on Checked runtime, it takes more than 5s
![image](https://user-images.githubusercontent.com/3184057/117714136-ce77af80-b1d6-11eb-9060-7b3171782b05.png)
The pipeline with these results is [here](https://dev.azure.com/dnceng/public/_build/results?buildId=1130823&view=ms.vss-test-web.build-test-results-tab).
I will build Checked runtime on my machine to confirm I have the repro and to see what exactly takes the time.

**Comment by danmoseley** [comment]
I was racking my brain to think what we were missing, and you figured it out. 👏

**Comment by CarnaViire** [comment]
I've run the measurements multiple times on Checked runtime and it was indeed Random taking all the time there: random part takes `4.8s` and deflate part takes `0.3s`. When I apply fix from https://github.com/dotnet/runtime/pull/52052, random part reduces to `0.02s` 😲.
@danmoseley should we pass a word about it to people owning Random?
I will reopen @zlatanov's PR as the fix is working, and I will double-check that in CI 😊

**Comment by jkotas** [comment]
I do not see an obvious reason why it should be that much slower compared to release build.
