### ISSUE TITLE
[wasm] System.Text.Json tests timing out

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#52059]
The tests seem to be timing out on the browser. Earlier it seemed like some regression fixes had [fixed this too](https://github.com/dotnet/runtime/pull/51012#issuecomment-827757257), but it seems 
to be happening [again.](https://github.com/dotnet/runtime/issues/50433)

PR that bumps the timeout, to unblock CI.

cc @ViktorHofer

**Comment by radekdoulik** [comment]
Ops, different issue.

**Comment by lewing** [comment]
how close to the limit are the builds that pass?  Does increasing the timeout actually fix it.
