### ISSUE TITLE
Getting "The SSL connection could not be established" error when connecting to a certain website

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#52053]
### Description

Using HttpClient, When attempting to make GET requests to a certain web address, the method *occasionally* fails with an error `The SSL connection could not be established, see inner exception.` where the inner exception says `Exception of type 'System.Net.InternalException' was thrown. -2146892963`. Occasionally is the key here - it sometimes "just works" (in the provided code below it should result in 503 Service Temporarily Unavailable when it works.)

Minimal reproducible code:
```cs
HttpClient client = new HttpClient();
await client.GetStringAsync("https://newbiepr.gitlab.io"); // Fails on this line
```

Exception details:

<div class="spacer"><table id="t1" style="border-color:#B56172"><tbody><tr><td class="typeheader" style="background:#B56172" colspan="2">HttpRequestException<span class="fixedextenser">4</span></td></tr><tr id="sum2"><td colspan="2" class="summary" style="background:#F4DEE3;color:black">The SSL connection could not be established, see inner exception.</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t3"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">HelpLink</th><td><i>null</i></td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2146233088</td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><table id="t4" class="expandable"><tbody><tr><td class="typeheader" colspan="2">InternalException<span class="fixedextenser">4</span></td></tr><tr id="sum5"><td colspan="2" class="summary" style="">Exception of type 'System.Net.InternalException' was thrown. -2146892963</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t6"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">HelpLink</th><td><i>null</i></td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2146233088</td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><i>null</i></td></tr><tr><th class="member" title="System.String">Message</th><td>Exception of type 'System.Net.InternalException' was thrown. -2146892963</td></tr><tr><th class="member" title="System.String">Source</th><td>System.Net.Security</td></tr><tr><th class="member" title="System.String">StackTrace</th><td>&nbsp;&nbsp; at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)<br>&nbsp;&nbsp; at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials&amp; credentialsHandle, SafeDeleteSslContext&amp; context, String targetName, ReadOnlySpan`1 inputBuffer, Byte[]&amp; outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)<br>&nbsp;&nbsp; at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]&amp; output)<br>&nbsp;&nbsp; at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)<br>&nbsp;&nbsp; at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)<br>&nbsp;&nbsp; at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)</td></tr><tr><th class="member" title="System.Reflection.MethodBase">TargetSite</th><td><div id="c7">TargetSite</div></td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">Message</th><td>The SSL connection could not be established, see inner exception.</td></tr><tr><th class="member" title="System.String">Source</th><td>System.Net.Http</td></tr><tr><th class="member" title="System.String">StackTrace</th><td>&nbsp;&nbsp; at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)<br>&nbsp;&nbsp; at UserQuery.Main(), line 2</td></tr><tr><th class="member" title="System.Net.HttpStatusCode?">StatusCode</th><td><i>null</i></td></tr></tbody></table></div>

### Configuration

Windows version: Windows 10 Pro Insiders Preview Build 21364 (Dev ring), x64, Korean
.NET SDK used: 5.0.200-preview.21077.7

### Regression?

As far as I can tell it can be reproduced on .NET Framework 4.8 that's installed on my Windows as well, albeit with a different error message:
<table id="t1"><tbody><tr><td class="typeheader" colspan="2">HttpRequestException<span class="fixedextenser">4</span></td></tr><tr id="sum2"><td colspan="2" class="summary">An error occurred while sending the request.</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t3"><tbody><tr><td class="typeheader" colspan="2">IDictionary (1 item)<span class="fixedextenser">4</span></td></tr><tr><th title="System.Object">Key</th><th title="System.Object">Value</th></tr><tr><td>LINQPad.LineNumber</td><td>6</td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">HelpLink</th><td><i>null</i></td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2146233088</td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><table id="t4" class="expandable"><tbody><tr><td class="typeheader" colspan="2">WebException<span class="fixedextenser">4</span></td></tr><tr id="sum5"><td colspan="2" class="summary">The request was aborted: Could not create SSL/TLS secure channel.</td></tr><tr><th class="member" title="System.String">Message</th><td>The request was aborted: Could not create SSL/TLS secure channel.</td></tr><tr><th class="member" title="System.Collections.IDictionary">Data</th><td><table id="t6"><tbody><tr><td class="typeheader" colspan="1">(0 items)</td></tr></tbody></table></td></tr><tr><th class="member" title="System.Exception">InnerException</th><td><i>null</i></td></tr><tr><th class="member" title="System.Reflection.MethodBase">TargetSite</th><td><div id="c7">TargetSite</div></td></tr><tr><th class="member" title="System.String">StackTrace</th><td>&nbsp;&nbsp; 위치: System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)<br>&nbsp;&nbsp; 위치: System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)</td></tr><tr><th class="member" title="System.String">HelpLink</th><td><i>null</i></td></tr><tr><th class="member" title="System.String">Source</th><td>System</td></tr><tr><th class="member" title="System.Int32">HResult</th><td>-2146233079</td></tr><tr><th class="member" title="System.Net.WebExceptionStatus">Status</th><td>SecureChannelFailure</td></tr><tr><th class="member" title="System.Net.WebResponse">Response</th><td><i>null</i></td></tr></tbody></table></td></tr><tr><th class="member" title="System.String">Message</th><td>An error occurred while sending the request.</td></tr><tr><th class="member" title="System.String">Source</th><td>mscorlib</td></tr><tr><th class="member" title="System.String">StackTrace</th><td>&nbsp;&nbsp; 위치: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<br>&nbsp;&nbsp; 위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<br>&nbsp;&nbsp; 위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()<br>&nbsp;&nbsp; 위치: UserQuery.&lt;RunUserAuthoredQuery&gt;d__0.MoveNext() 파일 C:\Users\gotos\AppData\Local\Temp\LINQPad5\_tjauvduk\query_uwxuos.cs:줄 41</td></tr></tbody></table>

### Other information

As far as I can tell, I do not see any sort of similar errors showing up when I make the request with other tools such as `curl` or Edge browser.

Might be related: https://github.com/dotnet/runtime/issues/44058 (although the issue was closed for insufficient info)

If you're having trouble reproducing the issue I am happy to provide packet captures for troubleshooting.

**Comment by Gnbrkm41** [comment]
I've also had someone running the same program on Windows 7 having a slightly different issue with the same address (the program is self-contained with *some version of* 5.0.x runtime, not exactly sure what it is) - here's the stack trace. I cannot reproduce the issue locally so can't really pull out much details from here but I suppose it could be related:
![image](https://user-images.githubusercontent.com/42944058/116565908-3d384b80-a941-11eb-90ab-741d8a9b02d8.png)

**Comment by vcsjones** [comment]
> (in the provided code below it should result in 503 Service Temporarily Unavailable when it works.

I am able to consistently get a 503, so it "works". What .NET runtime are you targeting? I see you are using the 5.0 SDK, but it would be helpful to know if you are targeting `netcoreapp3.1`, `net5.0`, etc.

> running the same program on Windows 7 having a slightly different issue with the same address

Based on the SSLLabs of this host, it has _very_ modern TLS configuration. In particular, it only permits `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 `, `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 `, and `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ` for TLSv1.2 (1.3 is not applicable to Windows 7). None of these cipher suites are available on Windows 7, [according to the documentation][1]. So I would expect the handshake to fail on Windows 7.

[1]: https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-7

**Comment by Gnbrkm41** [comment]
> What .NET runtime are you targeting?

I targeted net5.0-windows when I built my app, and when I run `Environment.Version` on LINQPad 6 (which was what I was using to gather info about the error) I get 5.0.2 so I expect it to be using the SDK stated above.

> None of these cipher suites are available on Windows 7... So I would expect the handshake to fail on Windows 7.

Ah, that's something that I didn't really know about. That explains why it failed with a different error on Windows 7...

**Comment by vcsjones** [comment]
@Gnbrkm41 What happens if you try `https://vcsjones.dev`? My site has the same cipher suite configuration as the site you are using. If it works, then we can rule out cipher suites.

**Comment by Gnbrkm41** [comment]
I am getting the same error with your site as well:
![image](https://user-images.githubusercontent.com/42944058/116573985-44af2300-a948-11eb-91fd-93a3abfdbe23.png)

It's possible that it's something specific to my PC. Since I have a couple other PCs (one with insider builds, and one without) I can try the same thing on those as well and see if I get the same issue.

**Comment by vcsjones** [comment]
@Gnbrkm41 Are you using LinqPad 5 or 6? The 5 version is based on .NET Framework whereas 6 is based on .NET Core. Would just be another helpful datapoint.

**Comment by Gnbrkm41** [comment]
I am definitely aware of the difference between LINQPad 5 and 6 - I am using 6 for the tests, although it did fail with the same error on LINQPad 5 as well (see the top comment for the stacktrace on LINQPad 5).

```
Host runtime version: 3.1.13
Default query runtime version: 5.0.2
Default query reference assembly version: 5.0.0
Roslyn Version: 3.8.0-5.20562.2
FSharp.Compiler.Service version: 22.0.3.0
NuGet client version: 5.6.0.5
```

**Comment by Gnbrkm41** [comment]
As far as I can tell, I'm not seeing the same issue happening when targeting .NET Core 3.1 on the same machine I was testing the issue initially. When I revert back to using 5.0.2 SDK it starts happening again.

**Comment by Gnbrkm41** [comment]
What I'm finding very odd is that it works fine on console applications however on GUI apps (e.g. WPF) it seems to reproduce consistently?

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
```
xaml:
```
<Window x:Class="WpfApp4.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp4"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Button Click="Button_Click"/>
    </Grid>
</Window>
```
The code-behind:
```cs
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Windows;

namespace WpfApp4
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            HttpClient client = new HttpClient();

            try
            {
                await client.GetStringAsync("https://vcsjones.dev");
            }

            catch (Exception ex)
            {
                MessageBox.Show($"Exception thrown: {ex}");
            }
        }
    }
}

```

With the most barebones GUI program I have above, I get the error I described earlier like once in every two tries.
```
---------------------------

---------------------------
Exception thrown: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

 ---> System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146892963

   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)

   at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteSslContext& context, String targetName, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)

   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)

   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)

   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

   at WpfApp4.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\gotos\source\repos\WpfApp4\WpfApp4\MainWindow.xaml.cs:line 24
---------------------------
확인   
---------------------------
```

I was never able to get the error to reproduce on a console application (targeting net5.0 also), and given that all the errors I've experienced was on either a WPF app (which is my own) or a WinForms app (LINQPad), could there be some common cause that's causing the issue to happen on GUI apps and not on console apps?

**Comment by vcsjones** [comment]
> could there be some common cause that's causing the issue to happen on GUI apps and not on console apps?

Hmm. I was not able to reproduce that... maybe @wfurt might be aware of something.

**Comment by wfurt** [comment]
Could you force TLS 1.2 and try it again @Gnbrkm41? 3.1 would not do TLS 1.3 AFAIK. If we can show this is happening only with TLS 1.3 we would probably need Schannel trace and I can take it to the Schannel team. 
(or alternatively HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client\Enabled -> 0)

**Comment by wfurt** [comment]
Note that the SEC_E_INVALID_PARAMETER is somewhat strange. There is cache for some inner SSL structures as well as the underlying TLS may or may not try to do TLS resume. Either one _may_ explain the inconsistency behavior.

**Comment by Gnbrkm41** [comment]
It definitely seems related, as I am not having the issue when TLS 1.3 is disabled through registry.  What's odd is that disabling TLS 1.3 also fixes the issue that happen on .NET Framework apps as well? Does .NET Framework also support TLS 1.3?

**Comment by Gnbrkm41** [comment]
> we would probably need Schannel trace and I can take it to the Schannel team.

How would I do that? Some instructions on obtaining the trace would be appreciated. 😄

**Comment by wfurt** [comment]
Not yet, but TLS 1.3 should be supported in 4.8 in May update. It is possible that the code already made it to insider dev channel. I lost track. It should be also easy to see it with Wireshark.

**Comment by wfurt** [comment]
```
logman start schannel_trace -p "{37D2C3CD-C5D4-4587-8531-4696C44244C8}" 0x7fffffff -o schannel.etl -ets -ln schannel

run repro

logman stop schannel_trace -ets
```
```

**Comment by Gnbrkm41** [comment]
I got the Schannel trace with the instructions you've provided. Not sure if it contains any sensitive information - is it okay if I post it here directly, or should I mail it to you? If latter is the case, just tell me the mail address I should send the file to.

**Comment by wfurt** [comment]
play it safe and send it to my GH email. (or send me link to it)

**Comment by Gnbrkm41** [comment]
Done - Please take a look. Thanks!

**Comment by karelz** [comment]
Triage: We got the data, we have to look at it a bit deeper -- suspicion is that it may require OS team to investigate.

**Comment by wfurt** [comment]
I don't know. It would be _nice_ to get final confirmation when fix is available. I don't think the internal Windows issues are visible so we can use this is communication channel when windows work is done.

**Comment by karelz** [comment]
Triage: Let's keep it in Future opened so that we can track progress of the Windows bug fix.

**Comment by Gnbrkm41** [comment]
Cannot seem to reproduce the issue on the latest preview build (Build 21390) - I think the bug is fixed on the Windows side. Thanks for the help! Closing the issue.

**Comment by wfurt** [comment]
thanks for confirmation @Gnbrkm41
