### ISSUE TITLE
[Size] Regression in System.Text.Json for Blazor WASM

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#52063]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [dae827e42a42e578eacd962d11cb08d8dacf7292](https://github.com/dotnet/runtime/commit/dae827e42a42e578eacd962d11cb08d8dacf7292)
Compare | [636988a0727d01479f9af94ef1c56bb7e79ecb24](https://github.com/dotnet/runtime/commit/636988a0727d01479f9af94ef1c56bb7e79ecb24)
Diff | [Diff](https://github.com/dotnet/runtime/compare/dae827e42a42e578eacd962d11cb08d8dacf7292...636988a0727d01479f9af94ef1c56bb7e79ecb24)

### Improvemnts in SOD - Pizza App - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - Pizza App - Publish - pub/wwwroot/_framework/System.Text.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 86.42 KB | 88.90 KB | 1.03 | 0.00 | | |
[SOD - Pizza App - Publish - pub/wwwroot/_framework/System.Text.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 100.94 KB | 103.84 KB | 1.03 | 0.00 | | |
[SOD - Pizza App - Publish - pub/wwwroot/_framework/System.Text.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20Pizza%20App%20-%20Publish.html>) | 262.00 KB | 270.00 KB | 1.03 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20Pizza%20App%20-%20Publish_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20Pizza%20App%20-%20Publish_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20Pizza%20App%20-%20Publish_5.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20Pizza%20App%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - Pizza App - Publish*'
```
<details>

#### SOD - Pizza App - Publish

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [dae827e42a42e578eacd962d11cb08d8dacf7292](https://github.com/dotnet/runtime/commit/dae827e42a42e578eacd962d11cb08d8dacf7292)
Compare | [636988a0727d01479f9af94ef1c56bb7e79ecb24](https://github.com/dotnet/runtime/commit/636988a0727d01479f9af94ef1c56bb7e79ecb24)
Diff | [Diff](https://github.com/dotnet/runtime/compare/dae827e42a42e578eacd962d11cb08d8dacf7292...636988a0727d01479f9af94ef1c56bb7e79ecb24)

### Improvemnts in SOD - New Blazor Template - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 97.77 KB | 100.18 KB | 1.02 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 254.50 KB | 261.00 KB | 1.03 | 0.00 | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 83.96 KB | 85.96 KB | 1.02 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish_5.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_29_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Improvement/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - New Blazor Template - Publish*'
```
<details>

#### SOD - New Blazor Template - Publish

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by eerhardt** [comment]
cc @steveharter - looks like your change https://github.com/dotnet/runtime/pull/51717 caused this.

**Comment by steveharter** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/52934. I didn't re-verify but trimming was verified in that PR.
