### ISSUE TITLE
Tests on strings fails inside docker container

### ISSUE THREAD

**Issue by FlavioCFOliveira** [dotnet/runtime#52064]
I'm using dotnet core and running a couple os tests on customized string extensions inside a docker container and it fail always, but it works well on a windows machine.

i've tryed to enforce the portuguese culture but it does not work, what am i missing here?

As example, i'm trying to remove diacritics from a string using as follows:

```c#
public static string RemoveDiacritics(this string input)
{
    var normalizedString = input.Normalize(NormalizationForm.FormD);
    var stringBuilder = new StringBuilder();

    foreach (var c in normalizedString)
    {
        var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
        if (unicodeCategory != UnicodeCategory.NonSpacingMark)
        {
            stringBuilder.Append(c);
        }
    }

    return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
}
```

Here is the test example (NUnit)
```c#
        [Test]
        public void StringExtensions_RemoveDiacritics_SUCCESS()
        {
            string originalStr = "amahã deverá ser çábado";
            string cleanStr = originalStr.RemoveDiacritics();
            Assert.AreEqual("amaha devera ser cabado", cleanStr);
        }

```

Here is the dockerfile example:

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:3.1-focal
WORKDIR /

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV TZ Europe/Lisbon

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

```

**Comment by tarekgh** [comment]
I have run the exact docker container `mcr.microsoft.com/dotnet/sdk:3.1-focal` and executed the code:

```C#
    class Program
    {
        public static string RemoveDiacritics(string input)
        {
            var normalizedString = input.Normalize(NormalizationForm.FormD);
            var stringBuilder = new StringBuilder();

            foreach (var c in normalizedString)
            {
                var unicodeCategory = CharUnicodeInfo.GetUnicodeCategory(c);
                if (unicodeCategory != UnicodeCategory.NonSpacingMark)
                {
                    stringBuilder.Append(c);
                }
            }

            return stringBuilder.ToString().Normalize(NormalizationForm.FormC);
        }

        static void Main(string[] args)
        {
            Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
            Console.WriteLine($"{RuntimeInformation.OSDescription}");

            string originalStr = "amahã deverá ser çábado";
            string cleanStr = RemoveDiacritics(originalStr);
            Console.WriteLine("amaha devera ser cabado");
            Console.WriteLine($"{cleanStr} {"amaha devera ser cabado" == cleanStr}");
            Console.ReadLine();
        }
    }
```

And I am getting the following output 

```
.NET Core 3.1.14
Linux 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021
amaha devera ser cabado
amaha devera ser cabado True
```

So it looks it is working fine for me. The only possible reason could be you have the following in your csproj file? 

```Xml
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
```

which enable the invariant mode on your app? 

it would be a clever idea if you can run the following code and send the output:

```C#
Console.WriteLine(CultureInfo.GetCultureInfo("en-US").NumberFormat.CurrencySymbol);
```

**Comment by FlavioCFOliveira** [comment]
Hello Tarek

Thanks in advance for your help, i've tested your suggestion and it keeps not working.

The tests fails when i run ```dotnet test``` inside of a sdk container

For a better undertanding how to reproduce, i've created a repo with the code explaining can you take a look at:

https://github.com/FlavioCFOliveira/TestsOnStrings

Thanks again for your help

**Comment by tarekgh** [comment]
@FlavioCFOliveira I have followed the instructions in your repo, and I have noticed two things. 

- I saw you have defined `<RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />` which is wrong as this can force Invariant mode. Sorry if my previous comments confused you but I was not asking you to add it. anyway, try to remove all occurrence of this from all projects.
- Somehow in the file `LibTests/StringExtensionsTests.cs` I noticed the `originalStr` is garbled. Could be cloning did not clone it as Utf8 encoding file? I had to restore the correct contents of the string and save the file as Utf8 encoding to ensure the string will not change again. 

After that, I have deleted `bin` and `obj` folders and then rebuilt (using `dotnet build`) then run and I am seeing the test pass. I deleted the bin and obj files because I noticed the runtime config file was containing the Invariant mode enabling flag and wanted to ensure everything will build from scratch. 

```
root@2e9e160162bc:/app# dotnet test
Test run for /app/LibTests/bin/Debug/netcoreapp3.1/LibTests.dll(.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.7.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

A total of 1 test files matched the specified pattern.

Test Run Successful.
Total tests: 1
     Passed: 1
 Total time: 1.4618 Seconds
```

**Comment by FlavioCFOliveira** [comment]
Hello Tarek,

I've tested again, now i've removed the previously added ```RuntimeHostConfigurationOption``` option. Following your suggestion, i've reconverted the test file back to utf8 and it worked perfectly. Somehow the file become ANSI (maybe a clone issue) and that was messing with the test executions.

Thank you very much for your time and patience
