### ISSUE TITLE
[wasm] Cannot get location for a loaded assembly (`Assembly.Location`)

### ISSUE THREAD

**Issue by ddobric** [dotnet/runtime#52062]
Hi all,

trying to evaluate the CSharp expression, that fails when adding reference. Following code fails at the first line:

```
var options = ScriptOptions.Default.AddReferences(typeof(TItem).Assembly);

Func<TItem, bool> discountFilterExpression = await CSharpScript.EvaluateAsync<Func<TItem, bool>>(this.Expression, options);

```

The error:

`"Can't create a metadata reference to an assembly without location" `

The same code works in a .NET 5 application. It fails when started in the Blazor web assembly standalone.

### Project settings
```

<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseBlazorWebAssembly>true</UseBlazorWebAssembly>
    <!--<RazorLangVersion>3.0</RazorLangVersion>-->
  </PropertyGroup>
```

**Comment by lewing** [comment]
The assemblies you load at startup in the webassembly runtime don't have a location so you are hitting https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Compilers/Core/Portable/MetadataReference/MetadataReference.cs#L333

**Comment by lewing** [comment]
Like with SingleFile applications Assembly.Location is expected to be empty in this case so this is the expected behavior.
