### ISSUE TITLE
AppleAppBuilder doesn't embed test data from subdirectories

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#52104]
Some test assemblies rely on test data being compiled into the published app. One example is System.Security.Cryptography.X509Certificates which copies several test certificates into the `TestData` directory.

AppleAppBuilder currently doesn't copy these data into the app bundle so the tests fail to find the data.

Notably, this code doesn't list files in subdirectories:
https://github.com/dotnet/runtime/blob/6b71dd24ff84c7aca11f791c614bf24acb04db83/src/tasks/AppleAppBuilder/Xcode.cs#L66-L69

Fixing that is relatively easy but CMake still flattens out the resource structure in the output Xcode project.

**Comment by directhex** [comment]
As best I can determine, CMake isn't entirely to blame here. Xcode flattens _all_ file references in Resources. If you want a directory structure, you need a _folder_ reference, which is handled differently (and obviously means we can't filter the files the way we do in xcode.cs)

Will run some experiments

**Comment by directhex** [comment]
OK, I've determined that RESOURCE in cmakelists _always_ takes the flattening approach. It seems there's a slightly different MACOSX_PACKAGE_LOCATION which works with subdirectories. Gotta get the syntax right...

**Comment by directhex** [comment]
Xcode is cursed
