### ISSUE TITLE
[iOS][tvOS] Microsoft.Extensions.HostFactoryResolver.Tests No Test Cases Found on iOS tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#52118]
```
default	13:15:22.157862-0400	Microsoft.Extensions.HostFactoryResolver.Tests	No test cases discovered
info	13:15:22.168461-0400	Microsoft.Extensions.HostFactoryResolver.Tests	assembly_preload_hook: System.Xml.ReaderWriter  /Users/mdhwang/Library/Developer/CoreSimulator/Devices/71D00C72-A1BD-4EF7-87EA-B22842EC1650/data/Containers/Bundle/Application/7E00DBF5-783E-40EA-9C84-A915B102591D/Microsoft.Extensions.HostFactoryResolver.Tests.app
default	13:15:22.218782-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Xml file was written to the provided writer.
default	13:15:22.219031-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0
default	13:15:22.219175-0400	Microsoft.Extensions.HostFactoryResolver.Tests	[TerminateWithSuccess]
default	13:15:22.219753-0400	Microsoft.Extensions.HostFactoryResolver.Tests	----- Done -----
info	13:15:22.220879-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Exit code: 0.
```

**Comment by mdh1418** [comment]
Turns out that `HostFactoryResolverTests.cs` was not being compiled, so there were no tests. This shouldn't be iOS/tvOS specific, but for all platforms.

**Comment by mdh1418** [comment]
This makes me wonder how many other test suites are missing tests as a result of not explicitly including the test files.

**Comment by eerhardt** [comment]
Note: this "library" is special, in that we don't build the library and ship it in a NuGet package. Instead, the source files are shipped in the NuGet package.

> Turns out that HostFactoryResolverTests.cs was not being compiled,

This looks like a mistake in the test .csproj. In Extensions libraries, we typically use `<EnableDefaultItems>true</EnableDefaultItems>`. But we didn't in these tests. I'll put a PR to fix it.
