### ISSUE TITLE
Trimming on .NET6 fails, on .NET5 it works

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#52113]
I have a project publishing through VS with trimming enabled. The app works perfectly fine on .NET 5. On .NET 6 the app is much smaller, I guess more files have been removed, but it crashes on start. Without trimming feature, the app also works on .NET 6.

So there is a trimming regression on .NET 6. 

FYI: I've switched from `link` to `copyused` mode, after reading that was a breaking change on .NET6, but I get the same results.

### Configuration

```
.NET SDK:
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

```

![image](https://user-images.githubusercontent.com/14368203/116723982-60660800-a9e0-11eb-92b7-96fd3d00b991.png)

On .NET 5 its the same as above just with `net5.0-windows...` as target framework

### Regression?

Yes

### Other information / Stacktrace

```
System.TypeInitializationException: The type initializer for 'System.Windows.Media.FontFamily' threw an exception.
 ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load.
 ---> System.MissingMethodException: Method not found: 'Boolean System.AppDomain.IsDefaultAppDomain()'.
   at <CrtImplementationDetails>.LanguageSupport._Initialize(LanguageSupport* )
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   --- End of inner exception stack trace ---
   at <CrtImplementationDetails>.ThrowModuleLoadException(String errorMessage, Exception innerException)
   at <CrtImplementationDetails>.LanguageSupport.Initialize(LanguageSupport* )
   at .cctor()
   --- End of inner exception stack trace ---
   at MS.Internal.FontCache.DWriteFactory.get_SystemFontCollection()
   at MS.Internal.FontCache.FamilyCollection.FromWindowsFonts(Uri folderUri)
   at System.Windows.Media.FontFamily.PreCreateDefaultFamilyCollection()
   at System.Windows.Media.FontFamily..cctor()
   at System.Windows.Media.Typeface..ctor(FonFamily fontFamily, FontStyle style, FontWeight weight, FontStretch stretch)
   --- End of inner exception stack trace ---
```

### Files which have been removed on .NET 6 publish
![image](https://user-images.githubusercontent.com/14368203/116725686-8e4c4c00-a9e2-11eb-8cbe-380df50db6bd.png)

### Files which exist on .NET 5 but not on .NET 6 publish
![image](https://user-images.githubusercontent.com/14368203/116725733-a2904900-a9e2-11eb-816c-fe19016701e4.png)

**Comment by jkoritzinsky** [comment]
cc: @vitek-karas @sbomer @agocke

**Comment by agocke** [comment]
@symbai Do you happen to be using WinForms or WPF? Neither of those frameworks are trim compatible.
