### ISSUE TITLE
[wasm] helix/windows tests issues tracking issue

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#52138]
https://github.com/dotnet/runtime/pull/51951 runs the `normal` scenario tests on windows/helix.

These tests are failing:
* ~~System.Runtime https://github.com/dotnet/runtime/issues/52007~~ fix: https://github.com/dotnet/runtime/pull/52066
* ~~Microsoft.Extensions.Http https://github.com/dotnet/runtime/issues/52008~~ fix: https://github.com/dotnet/runtime/pull/52707
* ~~System.Text.Json https://github.com/dotnet/runtime/issues/52106~~ fix: https://github.com/dotnet/runtime/pull/52142
* ~~System.CodeDom https://github.com/dotnet/runtime/issues/52107~~ fix: https://github.com/dotnet/runtime/pull/52540
* System.IO.Compression and System.IO.Compression.ZipFile https://github.com/dotnet/runtime/issues/52108
* ~~System.Numerics.Tensors https://github.com/dotnet/runtime/issues/52134~~ fix: https://github.com/dotnet/runtime/pull/52536
* ~~System.ServiceModel.Syndication https://github.com/dotnet/runtime/issues/52135~~ fix: https://github.com/dotnet/runtime/pull/52705
* System.Xml.Xsl.XslCompiledTransformApi https://github.com/dotnet/runtime/issues/52136
* Wasm.Console.Sample https://github.com/dotnet/runtime/issues/52137

Browser:

* Wasm.Build.Tests failing on windows https://github.com/dotnet/runtime/issues/52843

**Comment by radical** [comment]
Can we enable the other tests?

**Comment by lewing** [comment]
It is very interesting how sensitive these tests are to the build host vs the runtime host

**Comment by lewing** [comment]
> Can we enable the other tests?

We need to check on capacity.

**Comment by radical** [comment]
> > Can we enable the other tests?
> 
> 
> 
> We need to check on capacity.

Start with a couple then? System.buffers?

**Comment by radekdoulik** [comment]
> Can we enable the other tests?

My plan was to get it working on helix (it uses the `normal` scenario, so it runs a lot of things already, interpreter only). It is now relatively good - we have these 10 failures instead of  cca 110 in the beginning, when I started and pretty much nothing worked on helix :-)

So I think we can enable AOT now, see if there are any additional issues and then fix them along the way. I have already opened PR's for 2 of these.

**Comment by radekdoulik** [comment]
> It is very interesting how sensitive these tests are to the build host vs the runtime host

Yes :-) OTOH, some of these are similar issues, some related to files (directory separators?), some to line endings (LF vs CRLF) and then there's either timeout issue or something else, maybe related to docker or localization.
