### ISSUE TITLE
[MacCatalyst] Interpreter crash when running some test suites

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#52158]
As we're trying to enable tests for MacCatalyst, some suites are crashing at what seems to be startup.  

**Steps to reproduce**

- Clone https://github.com/directhex/runtime/tree/catalyst-test-run
- `./build.sh -Subset mono+libs -os MacCatalyst -arch x64`
- `./dotnet.sh build /t:Test src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests /p:TargetOS=MacCatalyst /p:TargetArchitecture=x64 /p:MonoForceInterpreter=true`

**StackTrace**

https://github.com/dotnet/runtime/blob/6b8bbdbd04a72aeab972a82ab8975569002022db/src/mono/mono/mini/tramp-amd64.c#L932

```
#0	0x000000010e287e39 in mono_arch_create_sdb_trampoline at /Users/steve/dev/jo-runtime/src/mono/mono/mini/tramp-amd64.c:932
#1	0x000000010e199aaa in mini_get_breakpoint_trampoline at /Users/steve/dev/jo-runtime/src/mono/mono/mini/mini-trampolines.c:1623
#2	0x000000010e1fdfd9 in mono_arch_init at /Users/steve/dev/jo-runtime/src/mono/mono/mini/mini-amd64.c:1437
#3	0x000000010e08647c in mini_init at /Users/steve/dev/jo-runtime/src/mono/mono/mini/mini-runtime.c:4346
#4	0x000000010e142f5d in mono_jit_init_version at /Users/steve/dev/jo-runtime/src/mono/mono/mini/driver.c:2841
#5	0x000000010e3d356a in mono_ios_runtime_init at /Users/steve/dev/jo-runtime/artifacts/bin/Microsoft.Extensions.Configuration.EnvironmentVariables.Tests/net6.0-Debug/maccatalyst-x64/AppBundle/runtime.m:310
```

**Comment by lambdageek** [comment]
Usually I see that stack trace when we try to mmap a page for code without specifying hardened runtime and JIT entitlement.

I don't know why we need to hit anything in an interp-only mode.

@vargaz

**Comment by steveisok** [comment]
Note the suite specified will pass under JIT

**Comment by lambdageek** [comment]
> Note the suite specified will pass under JIT

The AppleAppBuilder task only asks for the hardened runtime and the JIT entitlement if we're building for Catalyst and not using AOT or the interpreter.

https://github.com/dotnet/runtime/blob/d2fba8fdc44f5ed7a4676c219c626e36a3fa2998/src/tasks/AppleAppBuilder/Xcode.cs#L90-L97

If it turns out we always need this sdb trampoline, even in interp-only mode, we should just always ask for the entitlements.

But probably we're not initializing the runtime in the right way.

**Comment by steveisok** [comment]
Since we're going to move to AOT just interp for both arm64 and x64, this issue can be closed.
