### ISSUE TITLE
WeakRefCollection Equals behavior

### ISSUE THREAD

**Issue by hrrrrustic** [dotnet/runtime#52160]
https://github.com/dotnet/runtime/blob/bad6ea00b5abe011deb2002d07551b95e526b07d/src/libraries/System.Drawing.Common/src/System/Drawing/ClientUtils.cs#L98-L103

Seems like this is a common equals pattern, so why `true` is returning here?

**Comment by MihaZupan** [comment]
This looks like a bug, though from the [usages](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Drawing.Common/src/misc/GDI/DeviceContexts.cs), `Equals` will never be called.

Did you see this kind of issue (returning true after failed pattern match) elsewhere?

**Comment by hrrrrustic** [comment]
Simple scan for
```C#
bool Equals( param )
{
      if( pattern_matching param)
      {
           return
      }
}
```
didn't find any more cases

**Comment by safern** [comment]
Yeah definitely looks like a bug when porting the code over from .NET Framework: https://referencesource.microsoft.com/#System.Drawing/misc/ClientUtils.cs,340
