### ISSUE TITLE
System.Collections.Generic.PriorityQueue<T> - System.IndexOutOfRangeException on TryDequeue

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#52170]
I've just received a `System.IndexOutOfRangeException` on `TryDequeue` with literally no stacktrace except of:
`at System.Collections.Generic.PriorityQueue2.TryDequeue(TElement& element, TPriority& priority)` the line of code where it happens is: `while (CustomerQueue.TryDequeue(out Customer customer, out _))`

in VS debugger I can see that it has one item but item type TElement/Customer is null for some reason: `[0] = (null, 0)`. I cannot actively reproduce this issue.

### Configuration

.NET SDK:
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

**Comment by danmoseley** [comment]
Is it possible it had concurrent writes?

**Comment by Symbai** [comment]
It adds from one thread dequeues from another thread. If you ask me this, I guess its not a thread safe collection then.

**Comment by danmoseley** [comment]
@Symbai that's correct - aside from the non generic Hashtable, which allows a single writer to run concurrently with readers, I believe the only built in collections that allow non exclusive writes are those in the System.Collections.Concurrent namespace.
