### ISSUE TITLE
[Suggestion] ROS.Slice with auto-end-check like BinaryReader ?

### ISSUE THREAD

**Issue by wstaelens** [dotnet/runtime#52188]
## Background and Motivation

I've been converting code from .NET Framework to .NET 5.

.NET Framework code

```
    public override void ReadRecord(System.IO.BinaryReader r)
    {
      if (Type == (RecordType)r.ReadUInt32())
      {
        this.Size = r.ReadUInt32();
        cjIn = r.ReadUInt32();
        Data = r.ReadBytes((int)cjIn);
      }
    }
```

.NET 5 code

```
    public override void ReadRecord(ReadOnlySpan<byte> r)
    {
      if (Type == (RecordType)BinaryPrimitives.ReadUInt32LittleEndian(r)) 
      {
        this.Size = BinaryPrimitives.ReadUInt32LittleEndian(r.Slice(4)); 
        cjIn = BinaryPrimitives.ReadUInt32LittleEndian(r.Slice(8)); 
        Data = r.Slice(12, (int)cjIn).ToArray();
      }
    }
```

The .NET 5 code crashed.
<br />
After looking why, I've seen that `Size` field was 16 *(bytes)* and `cjln` was set to 20 *(bytes)*.

The whole record to read was 16 bytes, and reading the remeaning bytes for the `Data` field starts at index 12, but it should read 20 (according to cjln).

by using `Data = r.ReadBytes((int)cjLn));`  the BinaryReader's ReadBytes reads 4 bytes, because it internally checks if it reads the end.

The `Data = r.Slice(12, (int)cjLn).ToArray();` gives an `ArgumentOutOfRangeException` because it tries to read 20 bytes but there are only 4 available.

If I did `Data = r.Slice(12);` this would be a risk, because I had to read other data behind the Data (not in this example) the Data would contain all remaining bytes, which could be wrong.

Could this be something a ROS.Slice that either reads the given `length` or returns the remaining data in case there is less?

Now we have to do something as: `Math.Min(Size - x, length)`...

**Comment by Joe4evr** [comment]
The question I feel you should be asking yourself about your scenario is: If `cjln` indicates how many bytes should be read for the `Data`, why is it too large?

**Comment by wstaelens** [comment]
> The question I feel you should be asking yourself about your scenario is: If `cjln` indicates how many bytes should be read for the `Data`, why is it too large?

My code works fine in my case, just an example. Don't let us go off-road. 

A Slice with a length but that could return less data if there isn't enough, similar to BinaryReader.ReadBytes is what I suggested.

**Comment by Wraith2** [comment]
> > The question I feel you should be asking yourself about your scenario is: If `cjln` indicates how many bytes should be read for the `Data`, why is it too large?
> 
> My code works fine in my case, just an example. Don't let us go off-road.

Yes but it probably shouldn't. You asked for a certain length of data and then silently didn't get that returned. If you want to be able to accept fewer bytes than you're told are present then handling that detail yourself and having the choice be obvious and documentable in the codebase seems sensible.

> A Slice with a length but that could return less data if there isn't enough, similar to BinaryReader.ReadBytes is what I suggested.

Wouldn't `r.Slice[12..]` do that?

**Comment by Joe4evr** [comment]
@Wraith2 
> Wouldn't `r.Slice[12..]` do that?

Already mentioned in the OP:
> If I did `Data = r.Slice(12);` this would be a risk, because I had to read other data behind the Data (not in this example) the Data would contain all remaining bytes, which could be wrong.

**Comment by wstaelens** [comment]
got again hit by this 'nasty' 'bug' in production. Where a number of bytes to read is bigger than the available bytes. The BinaryReader.ReadBytes method nicely trims the array and gives all bytes or the available bytes. ROS.Slice just throws.

original code:
```
BinaryReader r; // reader of part of data 65008 bytes (length)
byte[] ObjectData = r.ReadBytes(r.ReadInt32()); // Object length is 65004
```

spanified code:
```
// r is a ReadOnlySpan<byte> of 65008 bytes (length)

int bytesRead = 0;
var numBytes = BinaryPrimitives.ReadInt32LittleEndian(r[bytesRead..]); // numbytes = 118940
bytesRead += 4;
byte[] ObjectData = r.Slice(bytesRead, numBytes).ToArray(); // throws System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'
```

BinaryReader.ReadBytes takes the size into account (array being trimmed: https://source.dot.net/#System.Private.CoreLib/BinaryReader.cs,510 )

ReadOnlySpan<T>.Slice  just throws: https://source.dot.net/#System.Private.CoreLib/ReadOnlySpan.cs,350 

To me it feels like a bug that the Slice should check the size of the ReadOnlySpan.

**Comment by tannergooding** [comment]
This doesn't sound like something we would be interested in provided due to the potential dangers it represents.

Using the `Slice` API alongside `Math.Min` (or `int.Min` now in .NET 7) -or- the relevant range pattern is a safer and less error-prone alternative that can be customized to the consumers needs.
