### ISSUE TITLE
[iOS][tvOS] System.Security.Cryptography RoundtripEmptyArray flakes on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#52199]
These tests haven't failed locally based on `b491d634bb7`, but have failed on CI in the three lanes of the same run.
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=e4e455c5-b032-5051-d2c5-a64982c9ac45&t=0263a457-10d3-5b56-3414-171b09292e09
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=accacb66-0a14-52ef-4079-6344686d9d4c&t=34fbd35e-866b-51a1-9063-fb50703b1957
https://dev.azure.com/dnceng/public/_build/results?buildId=1118648&view=logs&j=60bb76d0-1552-55d1-167a-0040a91a2806&t=0bd88bfe-5770-5552-db3f-b8a830860b26

```
System.Security.Cryptography.Csp.Tests.dll   Failed: 2
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))


System.Security.Cryptography.Algorithms.Tests.dll   Failed: 2
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Span.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
Test collection for System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array
System.Security.Cryptography.Rsa.Tests.EncryptDecrypt_Array.RoundtripEmptyArray
    Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - RSAdecrypt wrong input (err -1))
```

**Comment by filipnavara** [comment]
I was somewhat afraid of this. Looks like older iOS versions suffer from the same bug as the older macOS versions where the validation of PKCS#1 RSA padding is incorrectly rejecting empty data. The error is virtually indistinguishable from other incorrect padding errors.

I'm not sure how to proceed on this. There are two options and both may potentially result in timing attack flaws:

1) Detect the errSecParam error, fallback to decoding the RSA second time as raw data and validating the RSA padding to see if it matches empty data
2) On older iOS versions always decode the RSA as raw data and do the depadding in managed code.

I've already written and tested the second approach on macOS earlier with this depadding code:
``` 
        internal static bool DepadPkcs1Encryption(
            ReadOnlySpan<byte> source,
            Span<byte> destination,
            out int bytesWritten)
        {
            // https://tools.ietf.org/html/rfc3447#section-7.2.1

            // Starts with 00 02, followed by at least 8 bytes of non-zero padding and
            // then followed by 00
            if (source.Length < 11)
                throw new CryptographicException();

            bool invalidPadding = false;

            invalidPadding |= source[0] != 0;
            invalidPadding |= source[1] != 2;

            // Count non-zero padding bytes
            int inPadding = 1;
            int paddingLength = 0;
            for (int i = 2; i < source.Length; i++)
            {
                inPadding &= (((int)source[i] + 0xff) >> 8);
                paddingLength += inPadding;
            }

            // Verify there was at least 8 padding bytes and that zero follows
            invalidPadding |= paddingLength == (paddingLength & 7);
            invalidPadding |= paddingLength == source.Length - 2;

            if (invalidPadding)
                throw new CryptographicException();

            ReadOnlySpan<byte> message = source.Slice(paddingLength + 3);

            if (message.Length <= destination.Length)
            {
                message.CopyTo(destination);
                bytesWritten = message.Length;
                return true;
            }
            else
            {
                bytesWritten = 0;
                return false;
            }
        }
```

**Comment by vcsjones** [comment]
For my own curiosity, what is "older iOS"? 10? 12?

**Comment by filipnavara** [comment]
We have to figure that out. On macOS it was broken up to 10.14. If iOS was fixed broken in the same timeframe that would point towards iOS 12 being the last broken version and iOS 13 the first fixed.

**Comment by filipnavara** [comment]
The Helix logs suggest the error happened on iOS 13.5 and tvOS 13.4. Locally I use iOS 14.5 simulator where the error doesn't happen.

**Comment by vcsjones** [comment]
Third option would be to do nothing and disable the test on !macOS and document it as a platform quirk for older platforms. Empty encryption / decryption in PKCS1 RSA seems... less likely to be demanded. The upshot being then we would not need to implement any of the PKCS padding ourselves.

That could at least be an interim step as well while the rest of the tests / functionality is brought up.

**Comment by filipnavara** [comment]
I am generally fine with having the quirk but there is prior precedent in implementing the RSA padding in managed code in RsaPaddingProcessor. In fact the same quirk exists on decryption and encryption and the encryption code path already has a workaround.

**Comment by bartonjs** [comment]
> here is prior precedent in implementing the RSA padding in managed code in RsaPaddingProcessor

My recollection is that we only do manual padding when encrypting empty, but that Windows decrypt-empty worked fine.

> Third option would be to do nothing and disable the test on !macOS and document it as a platform quirk for older platforms. 

If it was a server OS I'd be worried about some DOS-ability from that.  But for clients that concern doesn't really apply... and encrypting/decrypting nothing is obviously not very common (since both Windows and macOS/iOS have had boundary condition bugs on it).

Just documenting it as broken on older iOS-variants might be the way to go.  There's more compat wiggle room there, since the unified stack hasn't ever run on those OSes.  (Sure, regressing from Mono is unfortunate, but, there are probably a handful of papercuts already.)

**Comment by mdh1418** [comment]
Not sure how to disable the test for a specific version of iOS/tvOS, so keeping the active issue for now and pushing this to 7.0.0
