### ISSUE TITLE
Issue with date formatting to string using .ToString("M")

### ISSUE THREAD

**Issue by sarbanjeet** [dotnet/runtime#52198]
### Describe the bug
Date formating to string is having an issue in DotnetCore. While formatting using **`.ToString("M")`**, output in framework 4.7 and Rosyln is the same but different in Dotnet core. 

Dotnet Core adding extra **ZERO**. It is returning May 03 which looks like May 2003. 

**Output for `DateTime.Now.ToString("M")`**
Dotnet Core:     **May 03**
Framework 4.7: **May 3**
Roslyn:              **May 3**

### To Reproduce
Just use:` Console.WriteLine(DateTime.Now.ToString("M"));`
Here are all the dotnetfiddle links. 
[Dotnet Core: May 03](https://dotnetfiddle.net/RafEK7)
[Framework 4.7: May 3](https://dotnetfiddle.net/YKagG2)
[Roslyn: May 3](https://dotnetfiddle.net/fBMFnh)

**Comment by sarbanjeet** [comment]
@pgovind
@tannergooding

**Comment by tannergooding** [comment]
CC. @tarekgh, @GrabYourPitchforks

**Comment by tarekgh** [comment]
@sarbanjeet 

When you run with donnet on https://dotnetfiddle.net/, you'll running on a Linux machine and that machine will have the Invariant Culture as the default user culture. The invariant culture will have the month day pattern defined as `MMMM dd` which will print the day as 2-digits. When running as .NET Framework 4.7, you will be running on a Windows machine with `en-US` default user culture which will have the month day pattern defined as `MMMM d` which print the day as single digits. 

you can try running the code:

```C#
using System;
using System.Globalization;
using System.Runtime.InteropServices;

public class Program
{
	public static void Main()
	{
        Console.WriteLine($"{RuntimeInformation.OSDescription}");
        Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
		
		Console.WriteLine(DateTime.UtcNow.ToString("M"));
        Console.WriteLine($"`{CultureInfo.CurrentCulture}`");
        Console.WriteLine($"{CultureInfo.CurrentCulture.DateTimeFormat.MonthDayPattern}");
	}
}
```

with netcore run you will get the output:

```
Linux 5.4.0-1046-azure #48~18.04.1-Ubuntu SMP Tue Apr 13 19:41:38 UTC 2021
.NET 5.0.5
May 03
``
MMMM dd

```

while with .NET Framework 4.7 run you will get: 

```
Microsoft Windows 10.0.17763 
.NET Framework 4.7.3740.0
May 3
`en-US`
MMMM d
```

You are not using the exact same culture to expect same result. try adding the following line in the netcore run before the date formatting and you should get the same result. 

```C#
CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
```

I am closing the issue but feel free to send any question and I'll be happy to help with. Thanks for your report.
