### ISSUE TITLE
Error message “mscoreei.dll could not be loaded” on PC startup running Windows 10

### ISSUE THREAD

**Issue by MrBapMan** [dotnet/runtime#52204]
Running Windows 10 with .Net Framework v4.0.30319. File version for mscoreei.dll is 4.8.4180.0.

Ran sfc /scannow. Results: Beginning system scan. This process will take some time.

Beginning verification phase of system scan. Verification 100% complete.

Windows Resource Protection found corrupt files but was unable to fix some of them. From CBS.log: 2021-05-02 13:07:03, Info CSI 00000008 Hashes for file member [l:12]'mscoreei.dll' do not match. Expected: {l:20 b:36d3bf6b06b68587e22e20fd043e08d93c563a71}. Actual: {l:20 b:e5e3f512d288641dabcc7a60cd933d5436cd3233}. 2021-05-02 13:07:03, Info CSI 00000009 [SR] Cannot repair member file [l:12]'mscoreei.dll' of NetFx4-mscoreei_dll, version 4.0.15805.110, arch x86, versionScope neutral, pkt {l:8 b:b03f5f7f11d50a3a} in the store, hash mismatch 2021-05-02 13:07:03, Info CSI 0000000a Hashes for file member [l:12]'mscoreei.dll' do not match. Expected: {l:20 b:36d3bf6b06b68587e22e20fd043e08d93c563a71}. Actual: {l:20 b:e5e3f512d288641dabcc7a60cd933d5436cd3233}. 2021-05-02 13:07:03, Info CSI 0000000b [SR] Cannot repair member file [l:12]'mscoreei.dll' of NetFx4-mscoreei_dll, version 4.0.15805.110, arch x86, versionScope neutral, pkt {l:8 b:b03f5f7f11d50a3a} in the store, hash mismatch 2021-05-02 13:07:03, Info CSI 0000000c [SR] This component was referenced by [l:78]'Package_3_for_KB4601554~31bf3856ad364e35~amd64~~10.0.4341.2.4601554-32_neutral' 2021-05-02 13:07:03, Info CSI 0000000d Hashes for file member [l:12]'mscoreei.dll' do not match. Expected: {l:20 b:36d3bf6b06b68587e22e20fd043e08d93c563a71}. Actual: {l:20 b:e5e3f512d288641dabcc7a60cd933d5436cd3233}. 2021-05-02 13:07:03, Info CSI 0000000e Hashes for file member [l:12]'mscoreei.dll' do not match. Expected: {l:20 b:36d3bf6b06b68587e22e20fd043e08d93c563a71}. Actual: {l:20 b:e5e3f512d288641dabcc7a60cd933d5436cd3233}. 2021-05-02 13:07:03, Info CSI 0000000f [SR] Could not reproject corrupted file ??\C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll; source file in store is also corrupted 2021-05-02 13:07:03, Info CSI 00000010 [SR] Verify complete 2021-05-02 13:09:05, Info CBS Trusted Installer is shutting down because: SHUTDOWN_REASON_AUTOSTOP

Ran C:\WINDOWS\system32>sfc /verifyfile=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll

Windows Resource Protection found integrity violations.

Ran C:\WINDOWS\system32>DISM /Online /Cleanup-Image /RestoreHealth

Deployment Image Servicing and Management tool Version: 10.0.19041.844

Image Version: 10.0.19041.928

[==========================100.0%==========================] Error: 0x800f081f

The source files could not be found.

Any help or ideas to solve the problem would be appreciated.

**Comment by jkotas** [comment]
This issue is with .NET Framework. It is not actionable in this repo. Could you please report it via https://developercommunity.visualstudio.com/ where it will get routed to the right people?
