### ISSUE TITLE
JSON custom DateTime format \/Date(1605712704841)\/

### ISSUE THREAD

**Issue by martindrlik** [dotnet/runtime#52203]
Hello guys,

for compatibility I'm trying to serialize `DateTime` to custom date time format: `\/Date(1605712704841)\/`. I am not sure what is the origin of escaping forward slash and the name of this format.

First I thought that this would be possible to do by implementing own `JsonConverter<>`:

```
public class JsonConverterBackslashDateTime : JsonConverter<DateTime>
{
    public override void Write(Utf8JsonWriter writer, DateTime value, JsonSerializerOptions options)
    {
        var unixTimeMilliseconds = ((DateTimeOffset)value).ToUnixTimeMilliseconds();
        writer.WriteStringValue(@$"\/Date({unixTimeMilliseconds})\/");
    }
}
```

This will produce string as following `"\\/Date(1619690852000)\\/"`. Note that escaped back slash.
It seems that `Utf8JsonWriter.WriteStringValue` recognize `\/` as back slash that needs to be escaped and forward slash.

I am wondering if there are some options how to serialize to `\/Date(milliseconds)\/` date time format and still be able to use [System.Text.Json.JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer?view=net-5.0). Thank you.

**Comment by eiriktsarpalis** [comment]
I don't think that forward slashes can be escaped, which I suppose is why you had add the literal `@` prefix to your string. This results in the backslash being treated as a separate character and is therefore (correctly) escaped in the serialization. I'm curious though what character you would expect an escaped forward slash to map.

**Comment by martindrlik** [comment]
@eiriktsarpalis thank you for your answer. I do not think that forward slash needs to be escaped. It is only required for compatibility with following date time JSON format described [here](https://www.newtonsoft.com/json/help/html/DatesInJSON.htm).
![image](https://user-images.githubusercontent.com/533091/117001995-4cbde880-ace3-11eb-8e79-99da00d487d8.png)

Also note [this question on stackoverflow](https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped) where there is some explanation of why backslash is used.

**Comment by eiriktsarpalis** [comment]
Writing unescaped backslash characters does not seem to be possible under any [configuration of the JavaScriptEncoder](https://github.com/dotnet/runtime/blob/24a87ddf5c9ec090b826c2f3f6c730f71aed9f6f/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/DefaultJavaScriptEncoder.cs#L28-L36). Given that this is an old Microsoft format that used to be the default in JSON.net, it stands to reason that certain users might need to support this format. Tagging @GrabYourPitchforks and @layomia who might know of any workarounds that could be used here.

**Comment by GrabYourPitchforks** [comment]
Seems like the easiest mechanism would be to add APIs which would allow you to add pre-escaped text:

```cs
public readonly struct JsonEncodedText
{
    public static JsonEncodedText Raw(string escapedValue);
}

// ...

writer.WriteStringValue(JsonEscapedText.Raw($"/Date({unixTimeMilliseconds})/"));
```

**Comment by martindrlik** [comment]
@GrabYourPitchforks thank you for your answer. If I get it correctly there could be new `WriteStringValue` method overload that takes `JsonEncodedText` and simply writes what is in there without escaping?

```
writer.WriteStringValue(JsonEscapedText.Raw(@$"\/Date({unixTimeMilliseconds})\/"));
```
would result to `"\/Date(1619690852000)\/"` (note that double quoted as it is still JSON string value). That would be nice.

It might be also possible to add `WriteRaw` method to `Utf8JsonWriter`. Perhaps as an `extension` method, as it might not be needed in most cases.
```
public static void WriteRaw(this Utf8JsonWriter writer, ...)
{
    // writes without escaping
}
```

**Comment by eiriktsarpalis** [comment]
@martindrlik out of curiosity, did you try to implement the `Read` part of the converter for this format?

**Comment by martindrlik** [comment]
@eiriktsarpalis not yet. Currently there is no need for us as it is only used to serialize response. Consumer of this response has already adapted JSON deserializer to accept \/Date(millis)\/ format.

**Comment by Clockwork-Muse** [comment]
> @eiriktsarpalis not yet. Currently there is no need for us as it is only used to serialize response. Consumer of this response has already adapted JSON deserializer to accept `\/Date(millis)\/` format.

Uh, this implies that there's active development happening on both sides here.  At that point the question becomes "Can you agree on changing the date format?".  Possibly gated by an API version.

**Comment by martindrlik** [comment]
> > @eiriktsarpalis not yet. Currently there is no need for us as it is only used to serialize response. Consumer of this response has already adapted JSON deserializer to accept `\/Date(millis)\/` format.
> 
> 
> 
> Uh, this implies that there's active development happening on both sides here.  At that point the question becomes "Can you agree on changing the date format?".  Possibly gated by an API version.

It is deserialized by our customers. We can use new date format for new API and when announced as breaking change it might be used for existing API, but for convenience it would be nice to be able to use `\/Date(millis)\/` with this JsonSerializer. But I agree that need for `\/` should be dropped someday and if we don't find a reasonable solution we will change to better date time format.

**Comment by martindrlik** [comment]
Any news on this? Is it possible that "\/Date(millis)\/" format will be supported somehow?

**Comment by eiriktsarpalis** [comment]
There is a proposed API for adding support for writing raw json in https://github.com/dotnet/runtime/issues/1784. We are planning on releasing this in time for .NET 6.

I'm going to close this issue, feel free to contribute to the conversation in the linked issue.
