### ISSUE TITLE
Micro-optimizations for STJ generated source

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#52218]
- [x] Consider public option for honoring runtime-provided custom converters
- [x] Consider moving custom converter verification source to common helper
- [x] When fetching runtime-provided customers, use a dictionary lookup (rather than for-loop) when `JsonSerializerOptions.Converters` count > ~15
- [x] ~Make `JsonSerializerContext.GetTypeInfo(Type)` derived implementation based on dictionary-lookup if root-serializable type count > 64~ (cf. https://github.com/dotnet/runtime/pull/81239/files#r1088396569)

**Comment by eiriktsarpalis** [comment]
Issues were addressed by #86526.
