### ISSUE TITLE
Move Logging Source Generator to MS.Extensions.Logging.Abstractions

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#52222]
Library authors today can use the `LoggerMessage.Define` APIs and log messages by only referencing `Microsoft.Extensions.Logging.Abstractions`.

However, in order to use the new Logging source generation feature, they now need to reference `Microsoft.Extensions.Logging` as well.

We should move the source generator and attribute to `Microsoft.Extensions.Logging.Abstractions`, so library authors don't need to change their references to use this new feature.

**Comment by maryamariyan** [comment]
@eerhardt OK to work on this without discussing over API review meetings?

**Comment by eerhardt** [comment]
If we have consensus with stakeholders, I think this could be an "email only" API review. None of the API shape would change, just which assembly it is contained in.

I guess I would get buy-off with all the stakeholders before working on it.

**Comment by davidfowl** [comment]
+1 on this moving

**Comment by ericstj** [comment]
Seems fine to me.  Moving things is fine in previews without type-forwards.  I don’t even think there is a case where folks would notice the move, since there is no scenario for runtime consumption nor design-time binary consumption of the type from it's old location.
