### ISSUE TITLE
Improve hosting test/dev experience

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#52220]
Right now there are instructions about running all coreclr tests in the [workflow](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/testing.md) but the instructions on individual tests just says to run `dotnet build --test`, but there are a number of test projects in `src/test/hosting` and it's not easy to run all of them. The tests themselves also implicitly require other partitions to be built, but do not have an explicit requirement.

We could make some small improvements here:

- Add some instructions
- Add a script that represents the "canonical" way to run tests for this component
- See if the dev loop is still fast if we add an explicit reference to the `clr.runtime` partition

**Comment by elinor-fung** [comment]
@agocke Was this specifically for runtime tests under `src/tests/hosting`? I deleted `src/tests/hosting` a while back (projects in there were a combination of unused and unuseful).

I think the actual host tests (`src/installer/tests`) are covered by https://github.com/dotnet/runtime/issues/43705.

**Comment by agocke** [comment]
I think this was about src/tests/hosting, but I think the main result was that I just didn't understand what was in there, so I think deleting has resolved this.
