### ISSUE TITLE
Memory corruption when calling `Exception.ToString()` in debug build

### ISSUE THREAD

**Issue by ptasev** [dotnet/runtime#52233]
### Description
I'm seeing a strange memory issue with one of my apps.  I am allocating a large array of references types during a binary file read.  Later on during the binary read, an exception is thrown. It seems upon calling the exception's `ToString()` method, the app freezes for a while and once it becomes responsive again I can see that it still shows to be using ~10GB of memory. I expected that the memory would be cleaned up eventually as I'm not holding a reference to it as far as I can tell.

A member of the C# Discord server asked me to run a command in WinDbg preview (`!dumpheap -stat`) and said that the result showed that there is memory corruption. Result:
`Object <exec cmd="!ListNearObj /d 00000245d3233138">00000245d3233138</exec> has an invalid method table.`

This only appears when I build the app in debug configuration. The problem does not happen in release build.

Sorry for the vague description of the bug as I'm not too familiar with these tools to investigate and understand what is happening.

### Configuration

* Which version of .NET is the code running on? .NET Core 3.1
* What OS and version, and what distro if applicable? Windows 10 Pro 2004
* What is the architecture (x64, x86, ARM, ARM64)? x64, AMD Ryzen 2600
* Do you know whether it is specific to that configuration? I don't believe it's specific to Windows or the processor.

### Regression?

This is running inside a WinForms app so I couldn't try .NET Core 2.1 or earlier.  I haven't been successful in reproducing it in a console app.

### Other information

Commenting out lines 44 and 45 of Form1.cs seems to make the problem go away (the calls to exception ToString).
I am allocating a large array on line 34 of PrtCollision.cs.

Stack trace of the exception:
```csharp
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AoMEngineLibrary.Graphics.Prt.PrtBinaryReader.ReadString() in C:\c\Sandbox\FullCodeMemoryIssue\src\AoMEngineLibrary\Graphics\Prt\PrtBinaryReader.cs:line 24
   at AoMEngineLibrary.Graphics.Prt.PrtCollisionType..ctor(PrtBinaryReader reader) in C:\c\Sandbox\FullCodeMemoryIssue\src\AoMEngineLibrary\Graphics\Prt\PrtCollisionType.cs:line 46
   at AoMEngineLibrary.Graphics.Prt.PrtFile..ctor(Stream stream) in C:\c\Sandbox\FullCodeMemoryIssue\src\AoMEngineLibrary\Graphics\Prt\PrtFile.cs:line 124
   at AoMBrgEditor.Form1.PrtTesting() in C:\c\Sandbox\FullCodeMemoryIssue\src\AoMBrgEditor\Form1.cs:line 32
```

Here's the code to reproduce the issue:
[FullCodeMemoryIssue.zip](https://github.com/dotnet/runtime/files/6418888/FullCodeMemoryIssue.zip)

**Comment by jkotas** [comment]
> Object <exec cmd="!ListNearObj /d 00000245d3233138">00000245d3233138</exec> has an invalid method table.

This looks like a bug in verify heap handling of 2GB+ arrays.

cc @dotnet/gc
