### ISSUE TITLE
Account for lack of baselining when moving to CSProj packages

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#52251]
### Description

When packing with PKGProj the package index + harvesting validation ensured our dependencies were rather current, even for those packages we were no longer building.  We should make sure we think about how to handle this once moving to CSProj, so that we ensure that we ship 6.0 with the latest serviced dependencies.

If I look at https://github.com/dotnet/runtime/blob/fb931c6fa65470899f811f8102523cf320ee7a50/eng/Versions.props#L82-L115
I see a few cases of stale dependencies, or dependencies which are even a major release behind.

The fix here may be as simple as ensuring darc-subscriptions from past servicing releases which are still being built, and a manual pass over the list to ensure it's up to date for those repos which don't publish to darc.  We could consider validation for this somewhere as well, or just remember to do a pass every release.

cc @Anipik @ViktorHofer @safern @joperezr

**Comment by ericstj** [comment]
@ViktorHofer pinging here as you may have addressed this in your csproj conversion PR.

**Comment by ViktorHofer** [comment]
> and a manual pass over the list to ensure it's up to date

I already did recently this but can't find the commit right now. If this issue doesn't track adding automation then I believe we can close it.

**Comment by ViktorHofer** [comment]
Closing as versions are up-to-date. That said, we should consider using dependabot in the repo.
