### ISSUE TITLE
Should we remove DynamicallyAccessedMembers attributes on JsonSerializer?

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#52268]
In 5.0, we annotated the JsonSerializer APIs with `DynamicallyAccessedMembers` attributes in #38595.

https://github.com/dotnet/runtime/blob/300c39ddf8a736384418fb01e0338f66c0afff4d/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs#L43-L44

https://github.com/dotnet/runtime/blob/300c39ddf8a736384418fb01e0338f66c0afff4d/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L26-L27

In 6.0, we resolved all the ILLink warnings in System.Text.Json in #51886, which caused us to also add the `RequiresUnreferencedCode` attributes. This is because the trim annotations can't model everything that needs to be preserved to make these APIs trim compatible. For example, see https://github.com/mono/linker/issues/1087.

Having both sets of attributes on these APIs isn't really ideal. The `DynamicallyAccessedMembers` attributes will only preserve members on the top-level type. So having the `DynamicallyAccessedMembers` gives a false sense of hope that this API will work with trimming, when in reality it won't.

The small benefit it does provide is in the case where the user is not serializing a graph, but just a class with primitive properties. However, even in this case, we'd like the user to move to use the source generator instead. So keeping these attributes for this tiny case doesn't seem to outweigh the benefit of the encouragement to move to using the source generator.

We also didn't annotate the DataContractSerializer and XmlSerializer APIs like this. We just marked the unsafe APIs with `RequiresUnreferencedCode`.

However, if we have plans for making the non-source generation Json serializer APIs work with trimming in 6.0, it might not be worth the effort of removing these attributes now, just to add them back in the near future.

cc @vitek-karas @agocke @layomia @steveharter

**Comment by vitek-karas** [comment]
I think we should remove them - as mentioned they are not enough and won't help in most cases anyway.

> However, if we have plans for making the non-source generation Json serializer APIs work with trimming in 6.0, it might not be worth the effort of removing these attributes now, just to add them back in the near future.

If we do come up with a solution, I doubt it will be using the exact same annotations, so we would have to change this anyway. I don't mind revisiting this code again, if we have a reason to do so.

**Comment by eerhardt** [comment]
Just an FYI - we have trimming tests for these attributes:

https://github.com/dotnet/runtime/blob/c9c954be788c4d4d13af326d83ba206a7f2ce45d/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/TrimmingTests/SerializerEntryPoint/SerializeAsync.ToStream.BoxedObject.cs#L31-L39

I assume as part of this work, we would be deleting those tests as well.

**Comment by eerhardt** [comment]
@steveharter @layomia - I plan on working on this. Just ensuring you don't have any objections to removing these attributes.

**Comment by davidfowl** [comment]
Didn't we decide that if we had a special [DAM] we could propagate these from user code to preserve type the call sites?

**Comment by eerhardt** [comment]
Yes, when the linker supports making a custom [DAM], then we can mark these methods with that. But we don’t have that feature yet.
