### ISSUE TITLE
System.Reflection.Metadata.MetadataReader returns unexpected signature for a field within a .winmd file

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/runtime#52264]
This issue is related to https://github.com/dotnet/roslyn/issues/52516. I believe the root cause of the crash is that compiler gets unexpected data from the MetadataReader. In particular, I observed the following behavior with a private copy of Windows.Win32.winmd.  I think it was built from https://github.com/wravery/win32metadata/commit/037e672427cfa7b8c5905715bd40847c27b50103. If you cannot build one, I can provide a copy that I used for the investigation.

We are trying to resolve the signature of the Anonymous field in Windows.Win32.System.OleAutomation.VARIANT
structure:
![image](https://user-images.githubusercontent.com/10522107/117050828-abc33380-acca-11eb-9b06-6263e782e10d.png)

```
TypeDef #4351 (02001100)
-------------------------------------------------------
	TypDefName: Windows.Win32.System.OleAutomation.VARIANT  (02001100)
	Flags     : [Public] [SequentialLayout] [Class] [Sealed] [AnsiClass] [BeforeFieldInit]  (00100109)
	Extends   : 0100000A [TypeRef] System.ValueType
	Field #1 (0400f77d)
	-------------------------------------------------------
		Field Name: Anonymous (0400F77D)
		Flags     : [Public]  (00000006)
		CallCnvntn: [FIELD]
		Field type:  ValueClass _Anonymous_e__Union
```

The type of the field is another structure named _Anonymous_e__Struct, it is nested into Windows.Win32.System.OleAutomation.VARIANT structure. 

1. We start reading the signature of the field and getting a TypeHandle for its type. The handle is a TypeReference handle.
2. We get TypeReference for the handle. Name is "_Anonymous_e__Union", ResolutionScope is another TypeReference handle.
3. We are getting information for the new TypeRefernce. Name is "VARIANT", Namespace is "Windows.Win32.System.OleAutomation", ResolutionScope is NIL ModuleDefinition handle.

Several things feel strange about all that information:
- The _Anonymous_e__Union is defined in the same module. Ideally the TypeHandle that we get on the first step should be a TypeDefinition handle. We can handle a type reference like that, assuming it provides expected information, but ideally a type definition handle should be returned.
- The same goes for the TypeReference handle we get on the second step.
- Finally, the resolution scope that we get on the last step doesn't look right at all. If it is a ModuleDefinition handle, then it should be a handle for the current module, i.e. the value equal to ```System.Reflection.Metadata.EntityHandle.ModuleDefinition``` field, but it is a NIL handle. Another thing we could handle as the resolution scope in this situation is a ModuleReference handle pointing to the containing module.

**Comment by AlekseyTs** [comment]
I didn't check bytes in ILDasm

**Comment by tmat** [comment]
If ILDASM has the same output as SRM then the bug is likely in the writer that produced the file. Is this file produced by WinMDExp? It could be a bug there (i.e. CCI).

**Comment by AlekseyTs** [comment]
@tmat I sent you the .winmd via Teams

**Comment by weltkante** [comment]
> Is this file produced by WinMDExp?

from the project https://github.com/microsoft/win32metadata, probably by System.Reflection.Metadata [here](https://github.com/microsoft/win32metadata/blob/master/sources/ClangSharpSourceToWinmd/ClangSharpSourceWinmdGenerator.cs)

(just following along and not involved in either)

**Comment by krwq** [comment]
@AlekseyTs @tmat seems this issue is missing the winmd file. Any chance you could attach it here? (or base64 of that file if github doesn't allow binary)

**Comment by AlekseyTs** [comment]
@krwq Attached winmd file.   [winmd (1).zip](https://github.com/dotnet/runtime/files/7022844/winmd.1.zip)

**Comment by steveharter** [comment]
Closing; we do not plan on supporting WinMD per https://github.com/dotnet/runtime/pull/58344#issuecomment-945240122
