### ISSUE TITLE
Some animated GIFs don't render frames correctly on Linux

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#52285]
### Description

When using `ImageAnimator.Animate` to animate GIFs that use variable frame delays, max loop counts, or partial frame updates, there are issues rendering the frames on Linux.

The issues seem to be down in `libgdiplus` and corresponding issues were filed there. This is a tracking issue for the .NET Libraries.

* GIF PropertyTagFrameDelay PropertyItem does not retrieve all frame delays mono/libgdiplus#703
    * The first frame's delay gets used for all frames, leading to animation timing drift
* GIF PropertyTagLoopCount PropertyItem always returns 0 mono/libgdiplus#704
    * GIFs will loop indefinitely instead of stopping after the loop count
* Animated GIFs don't render the frame correctly when only a portion is updated mono/libgdiplus#705
    * The images are rendered as partial images and often contain noise

### Configuration

* .NET 6.0 Preview 5
* Ubuntu 20.04 (via WSL2 on Windows 10)
* x64
* Linux specific; not sure if specific to Ubuntu or Ubuntu under WSL

### Regression?

No. There were worse problems with `ImageAnimator` on Linux before #52236. These issues were discovered while adding manual tests for ImageAnimator that capture frame renderings of animations.

### Other information

I recommend we close this since it's been a longstanding issue, there aren't currently app models that easily surface this scenario, and there haven't been customer reports of it. But I wanted to file it so that we could have the known issue logged.

**Comment by safern** [comment]
Thank you for the deep investigation, @jeffhandley. As you mentioned in the description, I also think we should close this, but it is a great write up to have here as history so that if a customer ever searches for this, they can find the libgdiplus underlying issues and move to the right place. I will go ahead and close the issue as we have tracking issues on libgdiplus.
