### ISSUE TITLE
missing some commands in namespace `Intrinsics`

### ISSUE THREAD

**Issue by ShuiRuTian** [dotnet/runtime#52289]
## Background and Motivation

Some instructions are missing like `_mm_set1_epi8` in sse2.

Sometimes this command is useful, we could get a Vector<128> like [17,17...17](repeated 16 times) in one cpu cycle.

## Proposed API

Personally, I do not care the name, but I know it is important, this is just an example.

```
namespace System.Runtime.Intrinsics.X86
{
    public abstract class Sse2 : Sse{
        + // _mm_set1_epi8 in SSE2
        + static Vector128<byte> BroadcastByte<byte>(byte _byte);
    }
}
```

## Usage Examples

```
var tmp = Sse2.BroadcastByte(8);
// Then I got a Vector<128> `tmp` full with byte 8 repeated 16 times.
```
For a real case, I want to implement SwissTable, but find missing this command.

## Alternative Designs

Well, as far as I know, rust provide it: https://doc.rust-lang.org/core/arch/x86_64/index.html

## Risks

I guess there was a reason for not adding this command at first, but maybe there is a chance to review and add more commands now?

**Comment by EgorBo** [comment]
@ShuiRuTian `Vector128.Create()` and other overloads should do it for you

**Comment by ShuiRuTian** [comment]
@EgorBo Thanks a lot, bro. This really helps.
