### ISSUE TITLE
System.Net.Sockets.SocketException (125) With Nginx 

### ISSUE THREAD

**Issue by vikeshkataria** [dotnet/runtime#52299]
****Problem :**  Reverse proxy server is not working.. I tried to configure UI with krestel service url in that case some of parallel requests are getting failed giving error socket exception 125...**

1. **krestel service configuration**
              [Unit]
              Description=WebAPIApp
              [Service]
              WorkingDirectory=/var/www/API
              ExecStart=/usr/bin/dotnet /var/www/API/WebAPI.dll
              Restart=always
              # Restart service after 10 seconds if the dotnet service crashes:
              RestartSec=10
              KillSignal=SIGINT
              SyslogIdentifier=dotnet-example
              User=www-data
              Environment=ASPNETCORE_ENVIRONMENT=Production              
              Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false              
              [Install]
              WantedBy=multi-user.target

2. Tested krestel service and its working without any error.

3. NGNIX site with below configuration
              server {
              listen        4001;
              location / {
                  proxy_pass         http://MachineNamewithDomain:5001;
                  proxy_http_version 1.1;
                  proxy_set_header   Upgrade $http_upgrade;
                  proxy_set_header   Connection keep-alive;
                  proxy_set_header   Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header   X-Forwarded-Proto $scheme;
              }
          }

4.  After reboot of machine,  I checked the service is Up and running on port number 4001 .. I tried to access swagger and it is also working but
      when i am executing API its execute only once after that it is giving 502 bad gateway error.. I checked the logs there was  nothing.
5 then i tried to access krestel service , its also running and up.. I tried to access swagger , it is also working and able to access all API without any error.

6.  I configured krestel service URL (port number 5001)  with Angular UI.. Application is working now but i observed two challanges there
    **1. sometimes it is not responding and response is coming blank.. I check on browser network HTTPstatuscode 200
    2.  Paralle request genrating from UI ( 20 requests of same single API ) in that case it is taking time and few requests converting into CORS error and  getting response of some request..  i checked the log  i am getting socket exception error**

2021-04-26 06:10:52,700 [139] ERROR System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> **System.Net.Sockets.SocketException (125): Operation canceled**
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

Please assist me on this problem..

**Comment by karelz** [comment]
It is not clear to me what exactly is source of your problems. As first step, I would recommend to identify what is failing and where (client side, reverse proxy, or backend), e.g. by using packet capture tools like Wireshark on client or on NGINX server.
In your case, does it mean the socket was closed by OS, remote connection (NGINX), or was the cancellation induced in the process by .NET Core client?

Overall, we can help with specific .NET Core problems - so if there is something wrong with .NET Core, we can provide guidance, help or at least routing to the right place (sometimes we may need a clear small repro to be able to do that).
For end-to-end scenarios involving other products (like NGINX that does not involve .NET Core at all), I would recommend to use general developer-help sites, like StackOverflow to find the right experts.

**Comment by vikeshkataria** [comment]
Deployed on Linux 

1. Angular -------------------------------------------------->  2. Core API -------------------------------------------- > 3. Geoserver
                  **(using Kerstel server URL to access API)**                             (Accessing data through **httpClient**)


1. From Angular app i am  hitting 20 requests parallelly to single API.

2. In Core API I am connecting to Geoserver thorugh HTTPClient. 
    
            try
            {
               
                using (HttpClient client = new HttpClient())
                {
                    HttpResponseMessage response = await client.GetAsync(uri);
                    byte[] content = await response.Content.ReadAsByteArrayAsync();
                    response.Dispose();
                    return File(content, "image/png");
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex);
            }

       **In catch block i am getting Socket excpetion 125 : operation canceled.**

       **Out of Above 20 requests 5 to 8 request are processing fine and rest are giving socket exception error in Linux enviornment.**


       I deployed same code on windows server IIS, it is working fine... i am getting all 20 requests responses from geoserver and returning to UI.

**Problem : On Linux enviornment ... Core API requests giving socket exception 125....**

**Comment by karelz** [comment]
I am still confused. What is Geoserver? What do you deploy on IIS that it works fine?
Can you remove Angular from your repro and use just Console app in "Core API"? -- just simple client and server to demonstrate what is going on.
Did you look at the packet capture to find out what is happening to the sockets?

Without a clear minimal repro we won't be able to make this actionable ...

**Comment by karelz** [comment]
Not actionable at this moment without additional info, closing. Feel free to reopen once there is more info available. Thanks!
