### ISSUE TITLE
Extra package dependencies appearing for current framework.

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#52318]
### Description

We try to avoid dependencies on packages when that same assembly is inbox in a framework.

Take System.Text.Json for example:
https://www.nuget.org/packages/System.Text.Json/5.0.2
![image](https://user-images.githubusercontent.com/8918108/117186892-2dc96000-ad90-11eb-9443-3efbceaeda14.png)
https://www.nuget.org/packages/System.Text.Json/4.7.0
![image](https://user-images.githubusercontent.com/8918108/117186951-3f126c80-ad90-11eb-8944-e012bbc85f9b.png)
https://www.nuget.org/packages/Microsoft.Extensions.Primitives/5.0.1
![image](https://user-images.githubusercontent.com/8918108/117189541-2f485780-ad93-11eb-80ed-c853f8e6def8.png)

In PKGProj this is accomplished with https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Build.Tasks.Packaging/src/CreateTrimDependencyGroups.cs

Right now in 6.0 this is broken due to the [packageIndex.json](https://github.com/dotnet/runtime/blob/main/src/libraries/pkg/baseline/packageIndex.json) missing inboxOn entries for 6.0.  

We should also decide how we handle this once we move to csproj.  It's really only interesting any more for the current .NET version as that's the only place where we have package/framework duality with exact match with an inbox library.  Coincidentally, this will happen automatically as a side-effect of our`$(NetCoreAppCurrent)` configurations in the projects, even when excluded from the package, since we cannot filter the `project.assets.json` that nuget's Pack task sees.  So long as we ensure not to include ProjectReferences for inbox assemblies, we'll see an empty dependency group.  Take Microsoft.Extensions.Primitives as an example (built with changes from https://github.com/dotnet/runtime/pull/52084): https://gist.github.com/ericstj/624ab958327a1eb5ca2cc76c10c4a836#file-microsoft-extensions-primitives-nuspec-L29

So we should fix the index to include 6.0 versions so that anything that's still built using pkgproj has the expected behavior as in past releases.

We should also be more intentional about preserving this behavior in libraries which move to CSProj.  I believe we've discussed having validation for this @Anipik, here's a good use case.

cc @eerhardt

**Comment by ericstj** [comment]
Related: https://github.com/NuGet/Home/issues/7344

**Comment by ericstj** [comment]
Note: here we benefit from the fact that project.assets.json isn't trimmed to exclude the dependency groups for frameworks which are omitted from the package.  It's not clear to me if that's always desired.  @Anipik are you aware of any other case where we'd want to omit both the asset and the dependency group?

**Comment by ViktorHofer** [comment]
> So long as we ensure not to include ProjectReferences for inbox assemblies, we'll see an empty dependency group.

I would hope that https://github.com/NuGet/Home/issues/7344 gets traction as I would really want to switch to P2Ps for inbox references at some point.

IMHO aside from security implications of dependencies I'm not too concerned about these added dependencies as they are trimmed out by package conflict resolution later anyway. Of course it would be great if we could avoid their download entirely but I see this more as an inconvenience and less as a blocker for the pkgproj migration.

**Comment by ericstj** [comment]
> really want to switch to P2Ps for inbox references at some point.

We'll need to solve hiding those P2Ps from NuGet anyway, can't have a package reference to System.Runtime, so I imagine we can choose to hide them on specific frameworks as well to get the right behavior without that NuGet feature.  I'm with you on really wanting that NuGet feature though.  I think it's a better and simpler overall story and make it so our customers don't need to have this complexity and still get similar benefits.

>  less as a blocker for the pkgproj migration.

Actually the projects that are migrated to CSProj coincidentally get the right behavior, so I wasn't thinking of it as a blocker.  More that we'd want to be more intentional about that, and think about if it would ever be problematic.

**Comment by ericstj** [comment]
> We should also be more intentional about preserving this behavior in libraries which move to CSProj.

Do we need anything to make sure that we don't unnecessarily rely on a PackageReference when an assembly is inbox?

If I look at our 7.0 packages, I see they have this problem.
https://www.nuget.org/packages/System.Net.Http.Json/7.0.0-preview.4.22229.4
https://www.nuget.org/packages/Microsoft.Extensions.Logging.Console/7.0.0-preview.4.22229.4
