### ISSUE TITLE
[Perf] Regressions in System.ComponentModel.Tests.Perf_TypeDescriptorTests

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#52317]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [d2dff5d7e2d42437753ce537af1dc3df3a867975](https://github.com/dotnet/runtime/commit/d2dff5d7e2d42437753ce537af1dc3df3a867975)
Compare | [94221f30cce9783f39d30eebbd9994f9711472e7](https://github.com/dotnet/runtime/commit/94221f30cce9783f39d30eebbd9994f9711472e7)
Diff | [Diff](https://github.com/dotnet/runtime/compare/d2dff5d7e2d42437753ce537af1dc3df3a867975...94221f30cce9783f39d30eebbd9994f9711472e7)

### Regressions in System.ComponentModel.Tests.Perf_TypeDescriptorTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(System.ComponentModel.Tests.ClassIDerived)).html>) | 144.68 ns | 153.80 ns | 1.06 | 0.00 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(System.Enum)).html>) | 197.88 ns | 217.19 ns | 1.10 | 0.01 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(string)).html>) | 146.33 ns | 155.31 ns | 1.06 | 0.01 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(System.ComponentModel.Tests.ClassWithNoConverter)).html>) | 132.39 ns | 145.91 ns | 1.10 | 0.01 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(int)).html>) | 199.22 ns | 215.23 ns | 1.08 | 0.01 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(System.Guid)).html>) | 203.19 ns | 216.42 ns | 1.07 | 0.01 | | |
[GetConverter - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert%3a%20typeof(System.ComponentModel.Tests.IDerived)).html>) | 120.26 ns | 129.63 ns | 1.08 | 0.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.ComponentModel.Tests.Perf_TypeDescriptorTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.ComponentModel.Tests.Perf_TypeDescriptorTests*'
```
<details>

### Payloads

[Baseline](<>)
[Compare](<>)

#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(System.ComponentModel.Tests.ClassIDerived))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(System.Enum))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(string))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(System.ComponentModel.Tests.ClassWithNoConverter))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(int))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(System.Guid))

```log

```
#### System.ComponentModel.Tests.Perf_TypeDescriptorTests.GetConverter(typeToConvert: typeof(System.ComponentModel.Tests.IDerived))

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
https://github.com/dotnet/runtime/pull/52016 seems like it could be related.

**Comment by ericstj** [comment]
@DrewScoggins I see we seem to have gained back this regression and then some, perhaps this was caused by an AMD64 JIT code quality regression that's been fixed?
![image](https://user-images.githubusercontent.com/8918108/127070394-403abcac-569b-466c-8f2f-42c759219be2.png)
![image](https://user-images.githubusercontent.com/8918108/127070519-c2079021-ac0d-4a6b-97f2-f25667067e55.png)

**Comment by safern** [comment]
@DrewScoggins could you please confirm that this regression is not there anymore as @ericstj suggested so that we can close this issue?

**Comment by DrewScoggins** [comment]
Yeah, looking through the commits that could have caused this, I don't see any real culprits besides PGO data update. And since we have seen this number come back down I think closing it is fine.
