### ISSUE TITLE
[Perf] Regressions related to JSON Source Generators

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#52311]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [8093c52a9a4abde623c1bf8b74334f11030847f2](https://github.com/dotnet/runtime/commit/8093c52a9a4abde623c1bf8b74334f11030847f2)
Compare | [9b364cf02c4a715c5eebba794766fc982960eeef](https://github.com/dotnet/runtime/commit/9b364cf02c4a715c5eebba794766fc982960eeef)
Diff | [Diff](https://github.com/dotnet/runtime/compare/8093c52a9a4abde623c1bf8b74334f11030847f2...9b364cf02c4a715c5eebba794766fc982960eeef)

### Regressions in System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[DeserializeFromString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.Json.Serialization.Tests.ReadJson(Int32).DeserializeFromString.html>) | 165.80 ns | 177.44 ns | 1.07 | 0.05 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.ReadJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.ReadJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-1d294f66-0356-4f14-bfa7-6c04630ea08cb795c6ad45f46deb9/f0a82038-bc0b-4a29-b816-20156d6aa6b9.zip?sv=2019-07-07&se=2021-05-18T04%3A13%3A07Z&sr=c&sp=rl&sig=92vRKfGmUDJFr048e0kB2g49XEgH%2BRH0iNua0VImG6o%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-6212c436-43ba-440c-a289-74c0648481ff637e762178447bc9b/d19d1982-cb4d-4746-a695-f06c578be713.zip?sv=2019-07-07&se=2021-05-19T13%3A21%3A29Z&sr=c&sp=rl&sig=xoWhu4D1UtNm3rEt3S4Ugb0kvpPiInQ1PRCYiA6u1pc%3D>)

#### System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;.DeserializeFromString

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [ddaa1c3c503f989db48102f50a693765e4e6ae2a](https://github.com/dotnet/runtime/commit/ddaa1c3c503f989db48102f50a693765e4e6ae2a)
Compare | [8c3180d932146b1a76600601c03082c6a81e1a53](https://github.com/dotnet/runtime/commit/8c3180d932146b1a76600601c03082c6a81e1a53)
Diff | [Diff](https://github.com/dotnet/runtime/compare/ddaa1c3c503f989db48102f50a693765e4e6ae2a...8c3180d932146b1a76600601c03082c6a81e1a53)

### Regressions in System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SerializeToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.Json.Serialization.Tests.WriteJson(Int32).SerializeToString.html>) | 183.15 ns | 209.11 ns | 1.14 | 0.04 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-a75b0c24-115e-41f4-8a38-4039cd481427e31911255db4f4fa5/5299d9d6-121e-4bc8-af75-22c23a5b5fc3.zip?sv=2019-07-07&se=2021-05-20T15%3A30%3A29Z&sr=c&sp=rl&sig=NhX8b8NdNzAr38thS1causVJXHoHg64xUo%2FBm4ZwJ2E%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-839bbfd3-efdb-46a4-862b-b8d00741a71b2864515457248e4a8/d4489adc-3af0-4ff0-8adb-81c63a1d11dc.zip?sv=2019-07-07&se=2021-05-21T05%3A44%3A36Z&sr=c&sp=rl&sig=ldI3sFGHXSoi7bgSPybdX4n9vb0GCHCpXXfXxVfQqiI%3D>)

#### System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;.SerializeToString

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [94d41d70d7038d94149d485a0f153eb8012859b3](https://github.com/dotnet/runtime/commit/94d41d70d7038d94149d485a0f153eb8012859b3)
Compare | [08e00bea231ad8e5afa83fc9d4e74ed667f16997](https://github.com/dotnet/runtime/commit/08e00bea231ad8e5afa83fc9d4e74ed667f16997)
Diff | [Diff](https://github.com/dotnet/runtime/compare/94d41d70d7038d94149d485a0f153eb8012859b3...08e00bea231ad8e5afa83fc9d4e74ed667f16997)

### Regressions in System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[DeserializeFromUtf8Bytes - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Text.Json.Serialization.Tests.ReadJson(Int32).DeserializeFromUtf8Bytes.html>) | 82.12 ns | 86.61 ns | 1.05 | 0.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_03_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Text.Json.Serialization.Tests.ReadJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_03_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Text.Json.Serialization.Tests.ReadJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<>)
[Compare](<>)

#### System.Text.Json.Serialization.Tests.ReadJson&lt;Int32&gt;.DeserializeFromUtf8Bytes

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [508e56025f66f5c2c00a8f1902816959bb61e0ac](https://github.com/dotnet/runtime/commit/508e56025f66f5c2c00a8f1902816959bb61e0ac)
Compare | [65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed](https://github.com/dotnet/runtime/commit/65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed)
Diff | [Diff](https://github.com/dotnet/runtime/compare/508e56025f66f5c2c00a8f1902816959bb61e0ac...65bcecebde4aebd5926952ccfc4dc8e7fbf7eaed)

### Regressions in System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SerializeToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Text.Json.Serialization.Tests.WriteJson(Int32).SerializeToString.html>) | 141.11 ns | 158.72 ns | 1.12 | 0.15 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_26_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-92d8e263-192b-47a0-b0fc-f8e4663a7132d09c7450b0549b1b2/1e2ad9f0-c937-4f2c-9688-188d1722bc26.zip?sv=2019-07-07&se=2021-05-20T19%3A49%3A56Z&sr=c&sp=rl&sig=aZ5UfiTXxlahVaZNkLNcwOBD6Kl0uNtmCtuZQUU7eXk%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-e75ce71e-be15-43a4-8c4e-493d688ea41a1177a1f74b64d6ea5/5cf6e11a-0934-4d76-8207-2c96c5667758.zip?sv=2019-07-07&se=2021-05-21T11%3A31%3A07Z&sr=c&sp=rl&sig=61hIA8%2BKm%2FoP6aoNVdJtuEVpDHpuoQC90ER0Mso%2FNhc%3D>)

#### System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;.SerializeToString

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [a5e626a015a37cf332e993804cd8bb42943c14c2](https://github.com/dotnet/runtime/commit/a5e626a015a37cf332e993804cd8bb42943c14c2)
Compare | [6b71dd24ff84c7aca11f791c614bf24acb04db83](https://github.com/dotnet/runtime/commit/6b71dd24ff84c7aca11f791c614bf24acb04db83)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a5e626a015a37cf332e993804cd8bb42943c14c2...6b71dd24ff84c7aca11f791c614bf24acb04db83)

### Regressions in System.Text.Json.Serialization.Tests.WriteJson&lt;HashSet&lt;String&gt;&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SerializeObjectProperty - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.Json.Serialization.Tests.WriteJson(HashSet(String)).SerializeObjectProperty.html>) | 8.67 μs | 9.52 μs | 1.10 | 0.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.WriteJson(HashSet(String))_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_04_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.Json.Serialization.Tests.WriteJson(HashSet(String)).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.WriteJson&lt;HashSet&lt;String&gt;&gt;*'
```
<details>

### Payloads

[Baseline](<>)
[Compare](<>)

#### System.Text.Json.Serialization.Tests.WriteJson&lt;HashSet&lt;String&gt;&gt;.SerializeObjectProperty

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by steveharter** [comment]
Please re-verify based on https://github.com/dotnet/runtime/pull/57327. Thanks
