### ISSUE TITLE
Incorrect/incomplete value numbering of partial stores of constants

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#52320]
Reproduction:
```cs
private static bool UseAsgOpt(int a)
{
    Unsafe.InitBlock(ref Unsafe.As<int, byte>(ref a), 0, 2);

    return a == 1 << 20;
}
```
Tree in question in VN:
```scala
***** BB01, STMT00000(before)
N005 (  9,  8) [000005] -A------R---              *  ASG       short
N004 (  7,  6) [000004] n------N----              +--*  IND       short
N003 (  3,  3) [000001] ------------              |  \--*  ADDR      byref
N002 (  3,  2) [000000] U------N----              |     \--*  LCL_VAR   int    V00 arg0         ud:1->2
N001 (  1,  1) [000002] ------------              \--*  CNS_INT   int    0

N001 [000002]   CNS_INT   0 => $40 {IntCns 0}
N002 [000000]   LCL_VAR   V00 arg0         ud:1->2 => $80 {InitVal($40)}
N003 [000001]   ADDR      => $100 {PtrToLoc($40, $0)}
    VNForCastOper(short) is $42
Tree [000005] assigned VN to local var V00/2: VN $40 {IntCns 0}
N005 [000005]   ASG       => $VN.Void

***** BB01, STMT00000(after)
N005 (  9,  8) [000005] -A------R---              *  ASG       short  $VN.Void
N004 (  7,  6) [000004] n------N----              +--*  IND       short  $40
N003 (  3,  3) [000001] ------------              |  \--*  ADDR      byref  $100
N002 (  3,  2) [000000] U------N----              |     \--*  LCL_VAR   int    V00 arg0         ud:1->2 $80
N001 (  1,  1) [000002] ------------              \--*  CNS_INT   int    0 $40
```
We end up assigning `$40` to `V00` despite the partial store of a constant. This eventually leads to incorrect codegen:
```asm
xor eax, eax
ret
```
(`UseAsgOpt(1 << 20)` will return `false` while it should return `true`)

This happens because `VNApplySelectorsAssignTypeCoerce` [doesn't do anything](https://github.com/dotnet/runtime/blob/d058930b2bf416635710b8b4022839a1ee1b8e6e/src/coreclr/jit/valuenum.cpp#L3652) for constant RHSs.

Naively blocking this with `elem = VNMakeNormalUnique(elem);` for the `isConstant` branch results in 6 regressions across the framework and a fairly huge diff in tests (`3391 total methods with Code Size differences (450 improved, 2941 regressed)`).

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Who is covering the VN issues these days?

**Comment by AndyAyersMS** [comment]
@sandreenko perhaps you can take a look. If you're too busy, let me know.

**Comment by sandreenko** [comment]
Unsafe code and VN are my favorites, looking at it now.

**Comment by SingleAccretion** [comment]
This might not be of any usefulness, but in the weeks since I've found this I also found a fix for a very similar issues: https://github.com/dotnet/coreclr/pull/18627.
