### ISSUE TITLE
Container Runtime Performance Metrics

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#52351]
# Container Runtime Performance Metrics

The goal of this document is to define a standard set of density-oriented measures that have high fidelity to user scenarios and that will generate metrics that (A) the .NET team can use to address .NET runtime challenges, and (B) that users can use to make application decisions. Some of the measures defined in this document might be considered non-standard or obscure. We're exploring the space looking for opportunities to improve.

We've spent a lot of time with [TechEmpower](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=composite) over the past several years. It also [runs in containers](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/CSharp/aspnetcore). TechEmpower runs a service run as fast as it can, blasting it with as much traffic as it can manage from a load generator. A lot of users, however, are interested in density, and for services to acquiesce when load drops off in order to host more than one app on physical hardware. TechEmpower doesn't exhibit or validate that scenario.

The following is an initial performance testing plan. It is subject to change as we start seeing test results or get feedback.

## Measures

The following measures will be used for the various scenarios that will be tested.

**Table**: Container metrics for app Foo using machine bar

| Scenarios   | Startup (ms) | Latency P50 (ms) | Latency P99 (ms) | Peak memory usage (mb) | Throughput (RPS) | Errors | App count |
|-------------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|
| Mini: 40mb; .25 core            |   |   |   |   |   |   |   |
| Small: 100mb; 1 core            |   |   |   |   |   |   |   |
| Medium: 250MB; 2 cores          |   |   |   |   |   |   |   |
| Large: 500MB; 4 cores           |   |   |   |   |   |   |   |
| Quarter-machine: xmb; y cores   |   |   |   |   |   |   |   | 
| Half-machine: xmb; y cores      |   |   |   |   |   |   |   |
| Whole-machine: xmb; y cores     |   |   |   |   |   |   |   |

- **Startup**: Time it takes for the app to return the first response, in milliseconds.
- **Latency**: Various latency measurements, in milliseconds.
- **Peak memory usage**: The peak memory measurement, in megabytes.
- **Throughput**: Requests per second of the run, either from a single app serving traffic on a single port or multiple copies of the same app each using a separate port.
- **Errors**: The number of request errors (no response or an HTTP return code other than 200).
- **App count**: The number of apps used for the measurement. A single app instance serving traffic on a single port would be "1", while 1 app per core on a "Large" machine would be "4".

Notes:

- The table itself does not specify the app to be used, but is a template for recording the results for an app, for one or more of the rows.
- The table doesn't assume machine type. The machine type should be clarified in the table title and in the table rows.
- Some of the scenarios in the table will fail with some of the tests. We just need to record that. In some cases, that will be expected.
- Some of these tests may be more important to run regularly than others.
- We should avoid warming up the product for these tests. We're not looking for best or average of three runs. We want the worst numbers, not the best ones. We don't want users to have to warm up the product as a requirement of getting good performance out of the product, unless of course that's a requirement of their own software. That said, we do want repeatable metrics, so there may prove to be a tension on those points. Perhaps "worst" and "repeatable" are actually separate efforts (one done once, and the other regularly).

## Load Test

Load test for 300s.

- 10 RPS
- 100 RPS
- 1,000 RPS
- 10,000 RPS

The first three tests are intended as meaningful. The last one is a stress test. There is no need to go higher.

## Density tests

Similar to the load test, but with multiple instances of the same app on the same machine.

Run for 300s.

- 1,000 RPS
- 10,000 RPS

Configurations (assuming a machine with 16+ cores):

1. 40x Mini apps
2. 10x small apps
3. 1x small apps per core
4. 4x quarter apps.

Configurations #1 and #2 are intended to use similar capacity (at least compute) and same with configurations #3 and #4. The second two apps can also be compared to a 1x whole-machine. Depending on the core count on the machine, there may need to be some adjustments to make the math work out. The goal is that these configurations are equivalent to one another so that they can be directly compared.

## Load swing tests

Same values as above, but transition between them. Always start with the higher value.

Run for 1000s. Transition every 100s.
Repeat. Run for 100s. Transition ever 10s.

- 100 RPS -> 10 RPS -> 100 RPS ->  …
- 1000 RPS -> 100 RPS -> 100 RPS -> …
- 10000 RPS -> 1000 RPS -> 1000 RPS ->  …
- 10000 RPS -> 10 RPS -> 10000 RPS -> …

Does memory drop from 100 RPS -> 10 RPS, for example? Does it grow again back when the traffic transitions to 100 RPS level, for example? Is the speed by which memory levels change acceptable/compelling?

How rough is the transition? How long does it take to adapt/acclimate to the optimal memory usage, RPS, latency, and error rate?  Is it possible to cause the process to perform poorly (OOM, drop requests, high-latency jitter) by very quickly increasing load (1000 RPS -> 10000 RPS)? If we don't see challenges at those numbers, what are the numbers  or conditions by which the product will perform poorly?

Ideally, we find a configuration where the product is rocked so violently on rough seas that we accept water in the boat, and then we increase the time between or height of the waves just enough that the product can notice a trend and (just barely) react acceptably. That's the point we want to identify, and it becomes our maximum most-stressed QoS level.

Perhaps we'll find that measuring an app with no warmup is enough to cause poor behavior.

The results of the swing tests don't lend themselves to recording in this table. We'll have to figure out how to record these. Perhaps, we'll just do this style of testing once and see if it warrants repeating, after analysis of the results.

## Machine configurations

We should test with the following configurations and priorities.

**Operating systems** (in priority order):

- Linux container (Linux host) -- 70% focus
- Windows container -- process isolated -- 20% focus
- Windows container -- Hyper-V isolated -- 10% focus

Note: We should not proactively test the performance of Linux containers hosted on Windows or macOS.

**Linux distros** (in priority order; latest supported version):
- Alpine

Note: Alpine vs Debian (or Ubuntu) is controversial. This one could go either way.

**Windows SKUs** (in priority order; latest supported version):
- Nano Server

Note: Nano Server vs Server Core is also tough. Let's focus on Nano Server until we see a reason to do different.
	
**Architectures** (in priority order):
- x64 (100% focus)
- Arm64 (kick tires for early data; greater focus in .NET 7.0)

**Proposed apps**:
- TechEmpower middleware
- A TBD app

**Good resources**:

- [Everything You Know About Latency Is Wrong – Brave New Geek](https://bravenewgeek.com/everything-you-know-about-latency-is-wrong/)

**Comment by mangod9** [comment]
@richlander there has been some progress around containers sizing work. Can this be closed?
