### ISSUE TITLE
Questions regarding PGO and the ICorJitInfo interface

### ISSUE THREAD

**Issue by tonybaloney** [dotnet/runtime#52365]
I'm implementing a system that consumes the .NET ryuJIT via loading of the clrjit library and implements the `ICorJitInfo` interface as per the spec.

In .NET 6 preview 3 some additional methods have been added to the interface:

- `getPgoInstrumentationResults`
- `allocPgoInstrumentationBySchema`
- `getLikelyClass`

Just reading about the new PGO functionality and then inspecting how these methods are implemented in `jitinterface.cpp`, I can see the use of the `pgo.h` and `pgo.cpp`, with a `PgoManager` singleton instance. 

I have questions :-)

- Is there an API to get these instances or to instantiate them?
- Is the PGO API designed only for the .NET implementation of the ryuJIT CEE
- Will `PgoManager` be available to clrjit consumers?
- Is the PGO implementation agnostic of managed/unmanaged CIL instructions?

**Comment by jkotas** [comment]
I assume that you are asking about this in the context of your https://github.com/tonybaloney/Pyjion project.

Encoding of the PGO data is tied with the CIL instruction stream. The only way to import code into RyuJIT is via CIL instructions. PGO data is augmenting the code and so it has to be tied to the CIL instructions. Once the code and PGO data are imported into JIT IR, the optimizations are agnostic of the original PGO data representation.

There are multiple implementations of the EE side of the PGO data management. There is one for the dynamic PGO and different one for static PGO.

**Comment by tonybaloney** [comment]
Hi Jan. Yes, I'm asking for Pyjion :-)

Pyjion compiles Python byte code into CIL instructions and then uses ryuJIT to compile Python code objects into methods using the JIT.
There is already a "PGO-style" profiler in Pyjion, which emits instructions in the CIL which have dup'ed evaluation stack pointers to observe dynamic types and optimize paths and then uses that profile data the next time the method is called to optimize certain types and field properties.

I was wondering if the .NET PGO will do things like branch optimization of the compiled machine code from the CIL instructions?

**Comment by jkotas** [comment]
Yes, .NET PGO does things like branch optimization and hot/cold spliting.

**Comment by AndyAyersMS** [comment]
> There is already a "PGO-style" profiler in Pyjion... to observe dynamic types 

There is a similar capability in .NET PGO-- during Tier0 jit invocations with the BBINSTR flag set, the jit will add "class probes" at virtual and interface call sites. These probes invoke a runtime helper which maintains a sampled histogram of the possible class values. The data gathered by these probes is recorded via a jit-created schema that is registered with the runtime via `allocPgoInstrumentationBySchema`.

The class profile information can also be persisted out of process (via event records) and post-processed by the [`dotnet-pgo` ](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/docs/design/features/dotnet-pgo.md) tool into a data file  (`.mibc`) that can be fed to crossgen2. Here the data can be used for optimizing prejitted code and also embedded in the assembly so it is available for future jit invocations.

Outside tools can also parse and understand the data in the `.mibc`, so we might explore switching over what you're doing to rely on this information instead. These class probe the jit adds are likely a subset of the ones you're adding; if you point me at some examples where you're using this information outside of calls perhaps we can consider extending what we're doing to cover the other cases you've found interesting.

The PGO data stream also includes information about block execution counts, and the jit reads and reacts to this information too (and likewise outside tools can use this information for various optimizations).

**Comment by JulieLeeMSFT** [comment]
@tonybaloney please let us know if your questions are all answered.

**Comment by tonybaloney** [comment]
Thank you!
