### ISSUE TITLE
Add EventSource event for service registration statistics

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#52364]
When the service provider is being built, we enumerate all service descriptors. It would be extremely useful to have an event that dumps out statistics for what types were registered in the container (at the right level of verbosity obviously):
- Number of descriptors in the collection
- Number of singletons
- Number of transients
- Number of scoped services
- Number of open generics
- Number of closed generics

These should be identified by service provider instance (applications can have more than one).

We should also add a more verbose event that dumps out the service collection registrations as is.

cc @pakrym

**Comment by eerhardt** [comment]
Moving out of 6.0 as this isn't a "must have" to release.
