### ISSUE TITLE
.unaligned prefix ignored on initblk and cpblk

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/runtime#5236]
Strictly speaking the JIT needs to make sure to generate references that are aligned with respect to the byte size specified by any unaligned prefix on initblk and cpblk. Today's implemented ignores them.

For some architectures, generating unaligned references may cause execution faults at runtime. For others, they can be less efficient than aligned references. At the moment all the targets RyuJIT supports do not require this for correctness, but might benefit on the performance side, especially for large block operations.

The MC++ compiler does generate these block operations today with unaligned prefixes to capture the original access size when vectorizing array initialization loops to block set operations (initblk).

category:correctness
theme:msil
skill-level:intermediate
cost:small

**Comment by EgorBo** [comment]
It's no longer ignored: https://github.com/dotnet/runtime/blob/0262a63be0f560fa902b1e31e9a10760e466352d/src/coreclr/jit/importer.cpp#L10397-L10402
