### ISSUE TITLE
Ok, found a bug that could definitely be causing this: Third Quarter Moon

### ISSUE THREAD

**Issue by ModestGoblin** [dotnet/runtime#52367]
Ok, found a bug that could definitely be causing this:

https://github.com/dotnet/runtime/blob/59d9d0d16858635a8c228be2ab7ad8882b0d1c71/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.cs#L328-L335

currentTimeMs is `Environment.TickCount`, which in this case happens to be negative.

The if clause controls if the hill climbing is even run. 

`_separated.priorCompletedWorkRequestsTime` and `_separated.nextCompletedWorkRequestsTime` start out as zero on process start, and only get updated if the hill climbing code is run.

Therefore, `requiredInterval = 0 - 0` and `elapsedInterval = negativeNumber - 0`. This causes the if statement to become
`if (negativeNumber - 0 >= 0 - 0)` which returns false, so the hill climbing code is not run, and therefore the variables never get updated, and remain zero. The native version of the thread pool code does all math with unsigned numbers which would avoid such a bug, ~and it's equivalent part is not even quite the same math in the first place~.

The easy fix here is probably to use unsigned arithmetic, but alternatively having the two fields get initialized to Environment.TickCount probably also works.

_Originally posted by @KevinCathcart in https://github.com/dotnet/runtime/issues/51935#issuecomment-832362190_

**Comment by Joe4evr** [comment]
And copy-pasting someone else's post into a new thread with none of the context is useful, how?
