### ISSUE TITLE
Intermittent deadlock in .NET 5.0.5 while attached to debugger

### ISSUE THREAD

**Issue by joakimriedel** [dotnet/runtime#52379]
### Description

See: https://github.com/dotnet/runtime/issues/42375

After the last fix, I haven't seen the deadlock for many months. But now I got a deadlock again which looks very similar, and have produced a dump file for you to look at.

Since the old issue is locked, I open up this new issue to track if this is a new problem or that the old bug have re-occurred in later version of .NET.

Ping @kouvel since you were investigating the last issue.

### Configuration

.NET 5.0.5
Win10 Pro build 20H2
Threadripper 3960X

### Regression?

Perhaps?

### Other information

Email me, or provide an e-mail address, for the link to the dump file since it's a full dump which may contain sensitive info.

**Comment by kouvel** [comment]
Thanks @joakimriedel, could you please send me a link to the dump file at kouvel@microsoft.com?

**Comment by joakimriedel** [comment]
@kouvel you've got mail!

**Comment by kouvel** [comment]
Thanks, I think I see the problem and looks like a short-window race between suspending the runtime for two different reasons. I'll think about a fix. How often are you seeing this?

**Comment by kouvel** [comment]
For the time being it should be possible to work around the issue by passing `COMPlus_TieredCompilation=0` when starting the process to be debugged, such as in the debug startup variables if starting from the debugger.

**Comment by kouvel** [comment]
> does it have any negative side-effects?

Perf may be a bit lower but probably wouldn't make much difference when debugging.

**Comment by kouvel** [comment]
Discussed offline, what I thought was a problem doesn't seem to be one that would cause a hang of this sort. Hopefully there'll be more info from another repro.

**Comment by kouvel** [comment]
Closing for now as discussed offline

**Comment by kouvel** [comment]
Further investigation led to finding an issue that appears to be causing the deadlock. Thanks for sharing the additional dumps, @joakimriedel. There is another issue that is a duplicate, https://github.com/dotnet/runtime/issues/58471. Since this issue is already closed, we can track this issue further with https://github.com/dotnet/runtime/issues/58471.
