### ISSUE TITLE
Croatian CultureInfo is not resolving parent culture info

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/runtime#52388]
### Description

Resolving strings for the Croatian cultureinfo "hr-HR" does not failover to the less specific "hr" culture info

### Configuration

* .NET 5 / 6
* Blazor
* x64
* All web browsers

### Other information

Worked around this issue by changing the culture info for my translation file to "hr" from "hr-HR"

**Comment by filipnavara** [comment]
There's few more similar issues on the mobile platforms that use the filtered ICU data. I suspect something could have been filtered out from there.

**Comment by tarekgh** [comment]
CC @lewing

**Comment by ilonatommy** [comment]
Checked on dotnet 7 preview 4 and it either works fine or I don't fully understand the scenario. I created a small repro where we have 2 razors for Croatian: 
- `hr.razor` with { "Greeting": "Zdravo svijete! hr", "Greeting2": "Another Zdravo svijete! hr"}
- 'hr-HR.razor` with { "Greeting": "Zdravo svijete! hr-HR"}
Setting the culture for `hr-HR`:
```
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("hr-HR");
CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("hr-HR");
```
we are getting the correct view of:
![image](https://user-images.githubusercontent.com/32700855/174605294-40765087-fdb6-43e6-ab5c-fd6265d9a282.png)

where 1st value is from specific culture and the 2nd is from the general culture. Was it the problem you wanted to solve, @csharpfritz? If not and it's still an existing issue, please give us the minimal repro.
