### ISSUE TITLE
GC object finalized with remaining strong reference

### ISSUE THREAD

**Issue by Reaper1121** [dotnet/runtime#52380]
### Description
	
	The GC finalize objects that have a remaining strong reference, that object may still be used which would cause object resurrection.
	The issue happens during manually invoked GC collection, don't know about automatic GC collection.
	I expect for objects that have a remaining strong reference to be GC finalized once there are no remaining strong references.
	
	The issue can be tricky to reproduce, I have made a small repo to clone with comments that shows off the issue.
	The repo: https://github.com/Reaper1121/GC-Finalizer-Issue
	
	I can provide additional code samples reproducing the issue if required.
	
### Configuration

	I've tested this on these configurations:

	Runtime: .NET Core 5.0.202, .NET Core 3.1.405 and .NET Framework 4.8
	OS: Windows 10 Enterprise LTSC 1809 (OS Build 17763.1518) and my friend Windows 7 Ultimate machine.
	Architecture: x64 and x86
	This is a Win32 desktop application, blazor is not used.

	Its not configuration specific, works on other configurations.

### Regression?

	The issue exists in previous builds of .NET Core, including .NET Framework.

### Other information

	There is a possible workaround:
	Calling "GC.SuppressFinalize(Object)" on objects stored in fields or properties that should not be finalized, once the class is in the process of being finalized objects that should not be finalized are re-registered for finalize using "GC.ReRegisterForFinalize(Object)".
	
	I may be wrong and this is not a bug within the GC, I would like to know why am I getting this what appears to be random behavior? I have used C# since .NET Framework days and have never encountered or noticed this.

**Comment by svick** [comment]
I haven't looked at your code in detail, but do I understand it correctly that the issue is that you expect finalizers to be called in a specific order, but they are called in a different order? If that is the case, then I think there is no bug, because the GC does not guarantee the order in which finalizers are called, as is explained [in the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.object.finalize?view=net-5.0&WT.mc_id=DOP-MVP-5002735#how-finalization-works):

> The finalizers of two objects are not guaranteed to run in any specific order, even if one object refers to the other. That is, if Object A has a reference to Object B and both have finalizers, Object B might have already been finalized when the finalizer of Object A starts.

This is one of the many reasons why finalizers are generally discouraged.

**Comment by Reaper1121** [comment]
Yes, this would be my exact problem! I don't know why I never knew this but I forgot to check this page of the documentation and I've spent days trying to figure out what is causing this.
I think can close this issue now, there is no need for any further investigation.
