### ISSUE TITLE
System.Text.Json: Make the Utf8JsonWriter always insert newlines between the end of comments and the start of arrays or objects

### ISSUE THREAD

**Issue by Fydar** [dotnet/runtime#52408]
## 📄 Brief

Change the `Utf8JsonWriter` to always insert newlines **between** the **end of comments** and the **start of arrays or objects** when `JsonWriterOptions.Indented` is set to `true`.

This change will produce Json that is more human-readable and in-line with Json that is hand-authored.

I would go so far as to say that comments at the start of a document should **always** be on their own lines.

Below are differences between the actual result (highlighted in **red**) and the proposed result (highlighted in **green**).

```diff
- /*This is a comment at the top of the document.*/{
+ /*This is a comment at the top of the document.*/
+ {
    "SimpleProperty": "String Value"
  }
```

```diff
  {
    "ObjectProperty":
-   /*This is a comment before an object value.*/{
+   /*This is a comment before an object value.*/
+   {
      "ChildProperty": "Property Value"
    }
  }
```

```diff
- /*This is a comment at the top of the document.*/[
+ /*This is a comment at the top of the document.*/
+ [
    /*This is a comment before an array element.*/
    [
      /*This is a comment before an object in an array.*/
      {
        "ChildProperty":
-       /*This is a comment before an array value.*/[
+       /*This is a comment before an array value.*/
+       [
          {
            "ChildProperty": "Property Value"
          }
        ]
      }
    ]
  ]
```

This change is a **breaking change**, but does so to better serve the original intent behind the `JsonWriterOptions.Indented` functionality (to produce output that is human-readable).

> "There are **other issues** with writing comments using the `Utf8JsonWriter`; this ticket does not intend to address all of the other issues, but instead proposes an **incremental improvement** over the current behaviour."

## 🔎 Detailed Description

Always inserting a newline before the start of objects and arrays is a common way of formatting comments in Json-like serialized data.

Deciding how Json-like data should be formatted is a controversial topic; the topic of how comments should be included in the mix is even more controversial.

> ⚠ Currently, you are unable to write comments **after** commas in objects (as comments are always placed after the previous value in a property).
>
> For this to be fixed there will have to be API changes made to facilitate both writing **before and after** commas that are delimiting properties in Json.

#### ✅ Test Case

```csharp
using System;
using System.IO;
using System.Text.Json;

namespace SystemTextJsonCommentNewlineProposal.Objects
{
    class Program
    {
        private static void Main(string[] args)
        {
            var output = new MemoryStream();
            var writer = new Utf8JsonWriter(output, new JsonWriterOptions()
            {
                // Important as proposed changes should only occur to indented Json only.
                Indented = true
            });

            writer.WriteCommentValue("This is a comment at the top of the document.");

            // This "start object" token appears on the same line as the previous comment.
            writer.WriteStartObject();

            writer.WritePropertyName("ObjectProperty");
            writer.WriteCommentValue("This is a comment before an object value.");

            // This "start object" token appears on the same line as the previous comment.
            writer.WriteStartObject();

            writer.WritePropertyName("ChildProperty");
            writer.WriteStringValue("Property Value");
            writer.WriteEndObject();
            writer.WriteEndObject();

            writer.Flush();

            // Output to the console.
            output.Seek(0, SeekOrigin.Begin);
            using var streamReader = new StreamReader(output);
            Console.WriteLine(streamReader.ReadToEnd());
        }
    }
}
```

**.NET Fiddle:** [https://dotnetfiddle.net/PCSfnT](https://dotnetfiddle.net/PCSfnT)

#### 🧪 Expected Result

When writing a comment before writing an object, the comment should be on its own on a line.

```jsonc
/*This is a comment at the top of the document.*/
{
  "ObjectProperty": 
  /*This is a comment before an object value.*/
  {
    "ChildProperty": "Property Value"
  }
}
```

#### 🔎 Actual Result

When writing a comment before writing an object, the start object token is on the same line as the comment.

```jsonc
/*This is a comment at the top of the document.*/{
  "ObjectProperty": 
  /*This is a comment before an object value.*/{
    "ChildProperty": "Property Value"
  }
}
```

#### ⚖ Difference

Differences between the actual result (red) and the expected result (green).

```diff
- /*This is a comment at the top of the document.*/{
+ /*This is a comment at the top of the document.*/
+ {
    "ObjectProperty":
-   /*This is a comment before an object value.*/{
+   /*This is a comment before an object value.*/
+   {
      "ChildProperty": "Property Value"
    }
  }
```

#### ✅ Test Case

```csharp
using System;
using System.IO;
using System.Text.Json;

namespace SystemTextJsonCommentNewlineProposal
{
    class Program
    {
        private static void Main(string[] args)
        {
            var output = new MemoryStream();
            var writer = new Utf8JsonWriter(output, new JsonWriterOptions()
            {
                // Important as proposed changes should only occur to indented Json only.
                Indented = true
            });

            writer.WriteCommentValue("This is a comment at the top of the document.");

            // This "start array" token appears on the same line as the previous comment.
            writer.WriteStartArray();

            writer.WriteCommentValue("This is a comment before an array element.");
            writer.WriteStartArray();
            writer.WriteCommentValue("This is a comment before an object in an array.");
            writer.WriteStartObject();
            writer.WritePropertyName("ChildProperty");
            writer.WriteCommentValue("This is a comment before an array value.");

            // This "start array" token appears on the same line as the previous comment.
            writer.WriteStartArray();

            writer.WriteStartObject();
            writer.WritePropertyName("ChildProperty");
            writer.WriteStringValue("Property Value");
            writer.WriteEndObject();
            writer.WriteEndArray();
            writer.WriteEndObject();
            writer.WriteEndArray();
            writer.WriteEndArray();

            writer.Flush();

            // Output to the console.
            output.Seek(0, SeekOrigin.Begin);
            using var streamReader = new StreamReader(output);
            Console.WriteLine(streamReader.ReadToEnd());
        }
    }
}
```

**.NET Fiddle:** [https://dotnetfiddle.net/8uskG7](https://dotnetfiddle.net/8uskG7)

#### 🧪 Expected Result

When writing a comment before writing an array, the comment should be on its own on a line.

```jsonc
/*This is a comment at the top of the document.*/
[
  /*This is a comment before an array element.*/
  [
    /*This is a comment before an object in an array.*/
    {
      "ChildProperty":
      /*This is a comment before an array value.*/
      [
        {
          "ChildProperty": "Property Value"
        }
      ]
    }
  ]
]
```

#### 🔎 Actual Result

When writing a comment before an array **at the start of the file**, the comment is on the same line as the beginning of the array.

Comments before array elements

```jsonc
/*This is a comment at the top of the document.*/[
  /*This is a comment before an array element.*/
  [
    /*This is a comment before an object in an array.*/
    {
      "ChildProperty":
      /*This is a comment before an array value.*/[
        {
          "ChildProperty": "Property Value"
        }
      ]
    }
  ]
]
```

#### ⚖ Difference

Differences between the actual result (red) and the expected result (green).

```diff
- /*This is a comment at the top of the document.*/[
+ /*This is a comment at the top of the document.*/
+ [
    /*This is a comment before an array element.*/
    [
      /*This is a comment before an object in an array.*/
      {
        "ChildProperty":
-       /*This is a comment before an array value.*/[
+       /*This is a comment before an array value.*/
+       [
          {
            "ChildProperty": "Property Value"
          }
        ]
      }
    ]
  ]
```

## ⚙ Configuration

**.NET Version:** 5.0.102

## ℹ Other information

*'The JSON5 Data Interchange Format'* Available at: <https://spec.json5.org/> [Accessed 6 May 2021]

**Comment by eiriktsarpalis** [comment]
Hi @Fydar, and thanks for writing such a detailed proposal. Superficially this seems like a reasonable change to me, although I defer to @GrabYourPitchforks, @layomia and @ahsonkhan who might be more aware of potential pitfalls.

**Comment by ahsonkhan** [comment]
Changing the output JSON format is typically a breaking change and this request is somewhat an edge case (using comments which isn't valid JSON per RFC, with indented). There isn't a clear set of rules for the output here, and as stated in the issue, could be a bit controversial, so such a change should require substantive rationale/benefit and some more customer requests, before prioritizing it, imo.

**Comment by Fydar** [comment]
> Does the `// comment` style of comment have this concern as well?

I believe there current is a way to create single-line (or `// comment`) comments using the `Utf8JsonWriter`.

**Comment by nicholas-ross** [comment]
I would like to see a WriteNewLine() method added to the Utf8JsonWriter.

I do my output with minimal formatting where each large object is on its own line. I currently do this by flushing the writer and then writing a new line to the stream.

If people want to do their own formatting then maybe there also could be a WriteIndent() method with ways to change the indent level.

**Comment by lateapexearlyspeed** [comment]
Hi, I would like to learn and try this, but not sure if we have decided to be able to change based on description in this issue ?
Also during learning related code, I just found and raised another clearer and straightforward [issue](https://github.com/dotnet/runtime/issues/75075) about json comment, about which I have raised [PR](https://github.com/dotnet/runtime/pull/75074), could anyone help have a look at it also? thanks.

**Comment by krwq** [comment]
@eiriktsarpalis @layomia I'm fine with this breaking change considering this change should not break any parsers and I'm guessing most of the people who see comments formatted this way will be rather annoyed.

**Comment by krwq** [comment]
@lateapexearlyspeed send a patch and it will be easier to discuss it there. If the change will end up super complicated for whatever reason we might decide against it but honestly I doubt it and this looks like reasonable breaking change.

**Comment by eiriktsarpalis** [comment]
Curious why we think this is a breaking change? AFAIK JSON doesn't have whitespace significance so adding newlines to a formatting style shouldn't technically break anything.

**Comment by krwq** [comment]
@eiriktsarpalis I have mixed feeling as well. I think this originated from https://github.com/dotnet/runtime/issues/52408#issuecomment-915754546

**Comment by eiriktsarpalis** [comment]
Unless anybody disagrees, I think we can remove the breaking change labels.
