### ISSUE TITLE
M1 -MAC cannot run asp.net core

### ISSUE THREAD

**Issue by zack542** [dotnet/runtime#52411]
### Describe the bug
`Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.5/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.5/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.5/libhostpolicy.dylib: mach-o, but wrong architecture
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.5/libhostpolicy.dylib: mach-o, but wrong architecture
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.5]
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[1062] test2.dll' has exited with code 130 (0x82).`

### Further technical details
- ASP.NET Core last version  
- Include the output of `dotnet --info`
- `liuxiaolei@liuxiaoleideMacBook-Pro ~ % dotnet --info
.NET SDK (反映任何 global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

运行时环境:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  3.1.408 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.3.21202.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- `Visual Studio Community 2019 for Mac
Version 8.9.7 (build 8)
Installation UUID: 70bf02f3-065d-42c8-a53c-68d12c7630e0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

Mono Framework MDK
Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

Roslyn (Language Service)
3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

NuGet
版本: 5.8.0.6860

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks
SDK 版本:
	6.0.100-preview.3.21202.5
	5.0.202
	5.0.201
	5.0.103
	3.1.408
	3.1.407
	3.1.406
MSBuild SDK: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
运行时: /usr/local/share/dotnet/dotnet
运行时版本:
	6.0.0-preview.3.21201.4
	5.0.5
	5.0.4
	5.0.3
	3.1.14
	3.1.13
	3.1.12

.NET Core 3.1 SDK
SDK: 3.1.408

Xamarin.Profiler
未找到 /Applications/Xamarin Profiler.app

Updater
版本: 11

Xamarin.Android
未安装

Microsoft OpenJDK for Mobile
Java SDK: 未找到

Android Designer EPL 代码在此处提供:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

Android Device Manager
Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

Xamarin Designer
Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

Apple Developer Tools
A valid Xcode installation was not found at the configured location: '/Library/Developer/CommandLineTools'

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

Build Information
Release ID: 809070008
Git revision: 8b7ac2442978ec88d09703fafa4e43eb774f0a26
Build date: 2021-04-16 07:38:03-04
Build branch: release-8.9
Xamarin extensions: 8b7ac2442978ec88d09703fafa4e43eb774f0a26

Operating System
Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Fri Mar  5 01:14:02 PST 2021
    root:xnu-7195.101.1~3/RELEASE_ARM64_T8101 x86_64
`

**Comment by jeffschwMSFT** [comment]
Currently .NET Core is not functional if both the X64 and Apple M1 versions are installed sxs.  This issue is tracked by https://github.com/dotnet/runtime/issues/48068.  In the short term you can remove the previous /usr/shared/dotnet and install just the Apple M1 version.
