### ISSUE TITLE
Mono component architecture for Android.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#52439]
Mono component architecture currently supports two models, either full static, where components and Mono runtime are statically linked into final binary, or dynamic, where a shared Mono runtime library is linked with a stub library as well as logic to dynamic load component, deployed as shared libraries. Full details can be found here: https://github.com/dotnet/runtime/blob/main/docs/design/mono/components.md

After some initial discussion with Android team a third options popped up, building Mono runtime as a shared library using the dynamic component model, but instead of building and ship the components as shared libraries, build them as static libraries and give SDK team ability to decide if you would like to build them as shared libraries themselves or if they would like to consume them differently (like linking them into their own Android specific libraries) and use Mono's loader hooks to resolve requested symbols during runtime.

It should be fairly straight forward to achieve this using existing build system by adding an additional cmake/define for this scenario, but there are a couple of outstanding things to discuss before that could be complete:

Should the libraries build under this configuration always be build using PIC?

How we should handle eglib, right now it is either build into components shared library or in case of static linking, eglib is part of static Mono runtime, so components will get these symbols from static Mono runtime during linking. In this new mode however eglib symbols won't be available so we need to decide if we should ship eglib as a separate library in this configuration.

Still build the shared libraries as well in case consumers of Android nugets would like to utilize default dynamic component model?

//CC @lambdageek @grendello

**Comment by grendello** [comment]
//CC @jonpryor

**Comment by grendello** [comment]
For Android the static libraries should always be built with PIC - they will always be linked into a shared library.

**Comment by grendello** [comment]
I don't think there's need to put dynamic component libraries in the Android nugets. They will be consumed via Xamarin.Android, which will produce all the shared libraries it needs.

**Comment by lateralusX** [comment]
Question is if there will be other consumers of the Android nuget except Xamarin.Android.

**Comment by grendello** [comment]
> Question is if there will be other consumers of the Android nuget except Xamarin.Android.

I don't think so, @jonpryor?

**Comment by jonpryor** [comment]
What constitutes the "Android nugets" in this context?  The `microsoft.netcore.app.runtime.android-*` packages?  The `Microsoft.NET.Sdk.Android.Manifest-6.0.100` workload nugets?  Something else?

What constitutes a "consumer"?

The `microsoft.netcore.app.runtime.android-*` packages will be *public*, freely downloadable by anybody who cares to do so.  Will there be "other consumers"?  *Maybe*!  Maybe not!  It depends on the creativity of our community.

Without *known* "other consumers", it's hard to design for them.  The only *known* consumer is née Xamarin.Android.

---

That said, there is an *imagined* alternate consumer: around a year ago, I was chatting with someone who wanted to run a command-line app on Android devices, along the lines of:

```
adb push my-app.zip /data/local/tmp
adb shell unzip /data/local/tmp/my-app.zip
adb shell /data/local/tmp/my-app/my-app args…
```

We managed to prototype this, somewhat, atop mono: https://gist.github.com/jonpryor/55670ee1b15c421f3fa2f0c9e29a01e9

This app unfortunately also needed access to Java APIs, which significantly increased the complexity of things.  Ignoring *that* aspect, it's not "unimaginable" to imagine running stand-alone console apps on an Android device.

I imagine "stand-alone console app" support isn't in the cards for .net6, but maybe eventually?

**Comment by lateralusX** [comment]
Was informed by @grendello that XA decided to use pre-build component shared libraries and pre-build shared mono runtime. The following PR adds support for dynamic component support on Android, https://github.com/dotnet/runtime/pull/53221.

**Comment by lateralusX** [comment]
Closing this since https://github.com/dotnet/runtime/pull/53221 should handle dynamic component support on Android.
