### ISSUE TITLE
Proposal: Allow CurrentCulture to be set via environment variable

### ISSUE THREAD

**Issue by glatzert** [dotnet/runtime#52438]
## Background and Motivation

As a german (or european) powershell module author, i stumbled upon an issue, that's been interesting and bugging: Someone parsed the output of the dotnet compiler to find a directory name (`Publish-Module` does this).
The parsing works something like this: `new Regex("Output directory: (\w*)` [wildly simplified], which works well on en-US machines, but failes miserably on anything else.

Besides that: an error message in english will be found easily with google. An error message in german might not be found easily with bing. Your milage will vary with the language.

Both problems, could be alliviated, if I could force the CurrentCulture to a specific language - either via command line switch or via environment variable.

## Proposed API

```
set DOTNET_Culture=en-us
dotnet [...]
```

or for single use:
`dotnet --CurrentCulture en-us [...]`

## Alternatives

As an alternative, it would be an option to Ignore the CurrentCulture and make dotnet use the culture, the assembly defines as neutral:

`set DOTNET_IgnoreCurrentCulture=1`

**Comment by svick** [comment]
There already is an environment variable to ignore the culture of the operating system and use the invariant culture instead: [`DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization?WT.mc_id=DOP-MVP-5002735#invariant-mode).
