### ISSUE TITLE
Yet another async over sync bug in HttpClient

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#52448]
### Description

https://github.com/dotnet/runtime/blob/0bda3221665e206844652f8f1671dfca68861a62/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L457

returns a Task (wrapped in a ValueTask) directly off a TaskCompletionSource.

https://github.com/dotnet/runtime/blob/0bda3221665e206844652f8f1671dfca68861a62/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L837

Ttries to await said task.

### Configuration

master as of https://github.com/dotnet/runtime/commit/453502e6b8162aa40e96e68dfd0b7ef337cf90b4 (should still be HEAD at time of posting). Found by inspection trying to understand #51933

### Regression?

No?

### Other information

Workaround: Set HttpClientHandler.MaxConnectionsPerServer to something stupidly huge.

**Comment by jhudsoncedaron** [comment]
<STRIKE>block</STRIKE>deadlock

**Comment by jhudsoncedaron** [comment]
It will never call Task.ContinueWith(), nor schedule a job on the ThreadPool and wait for it.

**Comment by jhudsoncedaron** [comment]
I'll bite. What am I missing?

````
var tc = new System.Threading.Tasks.TaskCompletionSource<object>();
var th = new System.Threading.Thread(() =>
{
    System.Threading.Thread.Sleep(100);
	tc.TrySetResult("Hi");
});
th.Start();
Console.WriteLine(tc.Task.GetAwaiter().GetResult());
````

````
IL_0000:  newobj      UserQuery+<>c__DisplayClass4_0..ctor
IL_0005:  stloc.0     
IL_0006:  nop         
IL_0007:  ldloc.0     
IL_0008:  newobj      System.Threading.Tasks.TaskCompletionSource<System.Object>..ctor
IL_000D:  stfld       UserQuery+<>c__DisplayClass4_0.tc
IL_0012:  ldloc.0     
IL_0013:  ldftn       UserQuery+<>c__DisplayClass4_0.<Main>b__0
IL_0019:  newobj      System.Threading.ThreadStart..ctor
IL_001E:  newobj      System.Threading.Thread..ctor
IL_0023:  stloc.1     
IL_0024:  ldloc.1     
IL_0025:  callvirt    System.Threading.Thread.Start
IL_002A:  nop         
IL_002B:  ldloc.0     
IL_002C:  ldfld       UserQuery+<>c__DisplayClass4_0.tc
IL_0031:  callvirt    System.Threading.Tasks.TaskCompletionSource<System.Object>.get_Task
IL_0036:  callvirt    System.Threading.Tasks.Task<System.Object>.GetAwaiter
IL_003B:  stloc.2     
IL_003C:  ldloca.s    02 
IL_003E:  call        System.Runtime.CompilerServices.TaskAwaiter<System.Object>.GetResult
IL_0043:  call        System.Console.WriteLine
IL_0048:  nop         
IL_0049:  ret         

get_QueryCancelToken:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery._queryCancelTokenOrigin
IL_0006:  callvirt    System.Lazy<System.Threading.CancellationToken>.get_Value
IL_000B:  ret         

<>c__DisplayClass4_0.<Main>b__0:
IL_0000:  nop         
IL_0001:  ldc.i4.s    64 
IL_0003:  call        System.Threading.Thread.Sleep
IL_0008:  nop         
IL_0009:  ldarg.0     
IL_000A:  ldfld       UserQuery+<>c__DisplayClass4_0.tc
IL_000F:  ldstr       "Hi"
IL_0014:  callvirt    System.Threading.Tasks.TaskCompletionSource<System.Object>.TrySetResult
IL_0019:  pop         
IL_001A:  ret         

<>c__DisplayClass4_0..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  ret         
````

but

````
var tc = new System.Threading.Tasks.TaskCompletionSource<object>();
var th = new System.Threading.Thread(() =>
{
    System.Threading.Thread.Sleep(100);
	tc.TrySetResult("Hi");
});
th.Start();
Console.WriteLine(await tc.Task);
````
IL_0000:  newobj      UserQuery+<Main>d__4..ctor
IL_0005:  stloc.0     
IL_0006:  ldloc.0     
IL_0007:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Create
IL_000C:  stfld       UserQuery+<Main>d__4.<>t__builder
IL_0011:  ldloc.0     
IL_0012:  ldarg.0     
IL_0013:  stfld       UserQuery+<Main>d__4.<>4__this
IL_0018:  ldloc.0     
IL_0019:  ldc.i4.m1   
IL_001A:  stfld       UserQuery+<Main>d__4.<>1__state
IL_001F:  ldloc.0     
IL_0020:  ldflda      UserQuery+<Main>d__4.<>t__builder
IL_0025:  ldloca.s    00 
IL_0027:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<<Main>d__4>
IL_002C:  ldloc.0     
IL_002D:  ldflda      UserQuery+<Main>d__4.<>t__builder
IL_0032:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.get_Task
IL_0037:  ret         

get_QueryCancelToken:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery._queryCancelTokenOrigin
IL_0006:  callvirt    System.Lazy<System.Threading.CancellationToken>.get_Value
IL_000B:  ret         

<>c__DisplayClass4_0.<Main>b__0:
IL_0000:  nop         
IL_0001:  ldc.i4.s    64 
IL_0003:  call        System.Threading.Thread.Sleep
IL_0008:  nop         
IL_0009:  ldarg.0     
IL_000A:  ldfld       UserQuery+<>c__DisplayClass4_0.tc
IL_000F:  ldstr       "Hi"
IL_0014:  callvirt    System.Threading.Tasks.TaskCompletionSource<System.Object>.TrySetResult
IL_0019:  pop         
IL_001A:  ret         

<>c__DisplayClass4_0..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  ret         

d__4.MoveNext:
IL_0000:  ldarg.0     
IL_0001:  ldfld       UserQuery+<Main>d__4.<>1__state
IL_0006:  stloc.0     
IL_0007:  ldloc.0     
IL_0008:  brfalse.s   IL_000C
IL_000A:  br.s        IL_0011
IL_000C:  br          IL_009B
IL_0011:  ldarg.0     
IL_0012:  newobj      UserQuery+<>c__DisplayClass4_0..ctor
IL_0017:  stfld       UserQuery+<Main>d__4.<>8__1
IL_001C:  nop         
IL_001D:  ldarg.0     
IL_001E:  ldfld       UserQuery+<Main>d__4.<>8__1
IL_0023:  newobj      System.Threading.Tasks.TaskCompletionSource<System.Object>..ctor
IL_0028:  stfld       UserQuery+<>c__DisplayClass4_0.tc
IL_002D:  ldarg.0     
IL_002E:  ldarg.0     
IL_002F:  ldfld       UserQuery+<Main>d__4.<>8__1
IL_0034:  ldftn       UserQuery+<>c__DisplayClass4_0.<Main>b__0
IL_003A:  newobj      System.Threading.ThreadStart..ctor
IL_003F:  newobj      System.Threading.Thread..ctor
IL_0044:  stfld       UserQuery+<Main>d__4.<th>5__2
IL_0049:  ldarg.0     
IL_004A:  ldfld       UserQuery+<Main>d__4.<th>5__2
IL_004F:  callvirt    System.Threading.Thread.Start
IL_0054:  nop         
IL_0055:  ldarg.0     
IL_0056:  ldfld       UserQuery+<Main>d__4.<>8__1
IL_005B:  ldfld       UserQuery+<>c__DisplayClass4_0.tc
IL_0060:  callvirt    System.Threading.Tasks.TaskCompletionSource<System.Object>.get_Task
IL_0065:  callvirt    System.Threading.Tasks.Task<System.Object>.GetAwaiter
IL_006A:  stloc.1     
IL_006B:  ldloca.s    01 
IL_006D:  call        System.Runtime.CompilerServices.TaskAwaiter<System.Object>.get_IsCompleted
IL_0072:  brtrue.s    IL_00B7
IL_0074:  ldarg.0     
IL_0075:  ldc.i4.0    
IL_0076:  dup         
IL_0077:  stloc.0     
IL_0078:  stfld       UserQuery+<Main>d__4.<>1__state
IL_007D:  ldarg.0     
IL_007E:  ldloc.1     
IL_007F:  stfld       UserQuery+<Main>d__4.<>u__1
IL_0084:  ldarg.0     
IL_0085:  stloc.2     
IL_0086:  ldarg.0     
IL_0087:  ldflda      UserQuery+<Main>d__4.<>t__builder
IL_008C:  ldloca.s    01 
IL_008E:  ldloca.s    02 
IL_0090:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AwaitUnsafeOnCompleted<TaskAwaiter`1,<Main>d__4>
IL_0095:  nop         
IL_0096:  leave       IL_0121
IL_009B:  ldarg.0     
IL_009C:  ldfld       UserQuery+<Main>d__4.<>u__1
IL_00A1:  stloc.1     
IL_00A2:  ldarg.0     
IL_00A3:  ldflda      UserQuery+<Main>d__4.<>u__1
IL_00A8:  initobj     System.Runtime.CompilerServices.TaskAwaiter<System.Object>
IL_00AE:  ldarg.0     
IL_00AF:  ldc.i4.m1   
IL_00B0:  dup         
IL_00B1:  stloc.0     
IL_00B2:  stfld       UserQuery+<Main>d__4.<>1__state
IL_00B7:  ldarg.0     
IL_00B8:  ldloca.s    01 
IL_00BA:  call        System.Runtime.CompilerServices.TaskAwaiter<System.Object>.GetResult
IL_00BF:  stfld       UserQuery+<Main>d__4.<>s__3
IL_00C4:  ldarg.0     
IL_00C5:  ldfld       UserQuery+<Main>d__4.<>s__3
IL_00CA:  call        System.Console.WriteLine
IL_00CF:  nop         
IL_00D0:  ldarg.0     
IL_00D1:  ldnull      
IL_00D2:  stfld       UserQuery+<Main>d__4.<>s__3
IL_00D7:  leave.s     IL_00FF
IL_00D9:  stloc.3     
IL_00DA:  ldarg.0     
IL_00DB:  ldc.i4.s    FE 
IL_00DD:  stfld       UserQuery+<Main>d__4.<>1__state
IL_00E2:  ldarg.0     
IL_00E3:  ldnull      
IL_00E4:  stfld       UserQuery+<Main>d__4.<>8__1
IL_00E9:  ldarg.0     
IL_00EA:  ldnull      
IL_00EB:  stfld       UserQuery+<Main>d__4.<th>5__2
IL_00F0:  ldarg.0     
IL_00F1:  ldflda      UserQuery+<Main>d__4.<>t__builder
IL_00F6:  ldloc.3     
IL_00F7:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetException
IL_00FC:  nop         
IL_00FD:  leave.s     IL_0121
IL_00FF:  ldarg.0     
IL_0100:  ldc.i4.s    FE 
IL_0102:  stfld       UserQuery+<Main>d__4.<>1__state
IL_0107:  ldarg.0     
IL_0108:  ldnull      
IL_0109:  stfld       UserQuery+<Main>d__4.<>8__1
IL_010E:  ldarg.0     
IL_010F:  ldnull      
IL_0110:  stfld       UserQuery+<Main>d__4.<th>5__2
IL_0115:  ldarg.0     
IL_0116:  ldflda      UserQuery+<Main>d__4.<>t__builder
IL_011B:  call        System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult
IL_0120:  nop         
IL_0121:  ret         

d__4.SetStateMachine:
IL_0000:  ret         

d__4..ctor:
IL_0000:  ldarg.0     
IL_0001:  call        System.Object..ctor
IL_0006:  nop         
IL_0007:  ret         
````

**Comment by stephentoub** [comment]
By default,  await continuations run synchronously as part of the antecedent task's completion, so there's no additional thread hop or work item scheduling to the thread pool involved. If any such queuing is happening, it's happening regardless of whether you await or AsTask().GetAwaiter().GetResult(), which internally is itself just a continuation that completes a manual reset event.

**Comment by jhudsoncedaron** [comment]
Ok. I need to run some more analysis on that. It sounded good, then it didn't. If returning to pool goes and runs the whole second upload/download of the next sync request it isn't a whole lot better.

**Comment by jhudsoncedaron** [comment]
And that's exactly what happens. CompleteResponse -> ReturnConnectionToPool -> ReturnConnection -> TransferConnection -> TrySetResult -> SendUsingHttp11Async's state machine, and since that call is synchronous (async := false) it proceeds to run (via series of Nt calls that just call the next one because I don't have auth here) HttpConnection.SendAsyncCore (async := false) and run the entire request on the previous one being returned to queue.

**Comment by stephentoub** [comment]
> And that's exactly what happens. CompleteResponse -> ReturnConnectionToPool -> ReturnConnection -> TransferConnection -> TrySetResult -> SendUsingHttp11Async's state machine, and since that call is synchronous (async := false) it proceeds to run (via series of Nt calls that just call the next one because I don't have auth here) HttpConnection.SendAsyncCore (async := false) and run the entire request on the previous one being returned to queue.

Please share a runnable repro demonstrating what you're saying.  TransferConnection's transferring happens using tasks created with RunContinuationsAsynchronously: TrySetResult on such a task will always queue the continuation, never run it synchronously.

**Comment by jhudsoncedaron** [comment]
"TrySetResult on such a task will always queue the continuation, never run it synchronously."

You know, that's what I used to think until you just convinced me otherwise. So I set up a trivial test case and sure enough it does run synchronously.

````
[ThreadStatic] private int test;

async System.Threading.Tasks.Task<int> Main()
{
	test = 4;
	var continuation = new System.Threading.Tasks.TaskCompletionSource<int>();
	var th = new Thread(() => { Thread.Sleep(500); test = 3; continuation.TrySetResult(5); });
	th.Start();
	Console.WriteLine(await continuation.Task);
	Console.WriteLine(test);
	return 0;
}

// Outputs:
// 5
// 3
````

**Comment by stephentoub** [comment]
> new System.Threading.Tasks.TaskCompletionSource<int>();

You didn't pass TaskCreationOptions.RunContinuationsAsynchronously to the ctor.

I wrote: "TransferConnection's transferring happens using tasks created with RunContinuationsAsynchronously: TrySetResult on such a task will always queue the continuation, never run it synchronously."

**Comment by stephentoub** [comment]
But regardless of whether it runs sync or async, your repro will always print 5 3. I don't know what is trying to show.

**Comment by jhudsoncedaron** [comment]
Oh snap. We're back to the deadlock and my code change suggestion doesn't work.

> I don't know what it's trying to show.

That the continuation ran on the thread created by new Thread().Start using [ThreadStatic] to identify the thread it's running on.

**Comment by jhudsoncedaron** [comment]
So I have discussed this stuff with the team internally, and at this point we're willing to say just document you shouldn't call HttpClient.Send() from a TaskScheduler thread and we'll stop trying to use it and just keep with the custom client.

**Comment by stephentoub** [comment]
> discussed this stuff with the team internally

Can you clarify... which team?

> just document you shouldn't call HttpClient.Send() from a TaskScheduler thread

I think it's fine to expand the documentation to state there are niche situations where a sync call may need to block waiting for async work to complete. You should be able to avoid all of them if you're so inclined.

**Comment by jhudsoncedaron** [comment]
> which team?

That would be our own application development team.

> You should be able to avoid all of them if you're so inclined.

I suppose you could document every last case ...

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/52413.
