### ISSUE TITLE
Unused interop code in System.Management

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#52458]
The following types in https://github.com/dotnet/runtime/blob/98ac23212e6017c615e7e855e676fc43c8e44cb8/src/libraries/System.Management/src/System/Management/InteropClasses/WMIInterop.cs are unused and should be removed.  One of the issues with having this code is that it leads to incorrect assumptions of what native dependencies the codebase has (part of https://github.com/dotnet/core/issues/5651).

* IWbemLocator 
* WbemLocator 
* IWbemServices_Old
* IWbemShutdown 
* IUnsecuredApartment 
* UnsecuredApartment
* IWbemPropertyProvider
* IWbemEventProvider 
* IWbemEventProviderQuerySink 
* IWbemEventProviderSecurity 
* IWbemProviderIdentity
* IWbemEventConsumerProvider
* IWbemProviderInit
* IWbemProviderInitSink
* WbemDecoupledRegistrar
* IWbemDecoupledRegistrar
* MofCompiler
* WbemBackupRestore
* WbemDecoupledBasicEventProvider
* WbemQuery

**Comment by hrrrrustic** [comment]
@danmoseley Uh, you've already picked this one :)

**Comment by hrrrrustic** [comment]
Will you close it or I can submit PR? 😄

**Comment by danmoseley** [comment]
I'll have a PR up in a moment. Just an easy one to do between meetings 😄
