### ISSUE TITLE
HttpClient Http/2 doesn't flush frames when hitting the window limit

### ISSUE THREAD

**Issue by deathchurch** [dotnet/runtime#52451]
I have come across a strange issue when sending json log events using Serilog using the HTTP sink, but the issue will only appear if the receiving ASP.NET API is behind an F5 load balancer. The issue is that not all the data will be sent to the VIP on the F5 and the sending will hang until a timeout is reached (be that in IIS, httpClient timeout or F5 timeout).

I was able to get some POST's request to work by modifying the HTTP/2 profile on the F5 (https://support.f5.com/csp/article/K04412053), altering the Receive Window setting from the default 32kb, they only support a maximum of 128KB in this setting. That will work if I am sending say 50 events, but the default for the sink and what we would like to use is 1000 events. Due to the unknown size of what a list of events may be, I can not guarantee adjusting this receive window size would be a reasonable fix.

In summary:-

Sending API ->(HTTP/2)-> Receiving API - Works OK
Sending API ->(HTTP/1.1)-> Receiving API - Works OK

Sending API ->(HTTP/2)-> F5 VIP --> F5 Server Side ->(HTTP/2)-> Receiving API - Does Not Work
Sending API ->(HTTP/1.1)-> F5 VIP --> F5 Server Side ->(HTTP/2)-> Receiving API - Works OK

I have raised a case with F5 and they seem reluctant to investigate as they have used nghttp and are able to easily send 1000 events using HTTP/2 and indeed I can use curl to do the same, so they are saying this is pointing to aspnet rather than F5.

Example curl command that works fine
`curl -vkX POST -H "Content-Type: application/json" -d @Events100.json https://IPADDRESS_HERE --http2`

The original setup is using aspnetcore 3.1 web api that logs using serilog with the http sink to another aspnetcore 3.1 web api that will receive these serilog events and store them in a database.

For further testing I have created a simple dotnetcore 3.1 console application that will read a file (which just contains the events serilog would have been sending) and uses a httpClient to send to a basic aspnetcore 3.1 web api that will receive the data (not using IIS but just plain Kestrel) and write out to a file, this testing also fails with the timeout scenario.

This is all running on Windows Server 2019 Core.

For reference the events I am talking about are like this:-
``` json
{
  "events": [
    {
      "Timestamp": "2021-05-05T10:25:32.5505666+00:00",
      "Level": "Information",
      "MessageTemplate": "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {Elapsed:0.0000} ms",
      "RenderedMessage": "START - HTTP \"GET\" \"/weatherforecast\" responded 200 in 2.1560 ms",
      "Properties": {
        "RequestMethod": "GET",
        "RequestPath": "/weatherforecast",
        "StatusCode": 200,
        "Elapsed": 2.156,
        "SourceContext": "Serilog.AspNetCore.RequestLoggingMiddleware",
        "RequestId": "80000812-0006-f800-b63f-84710c7967bb",
        "SpanId": "|478ab71d-48fb709e612eba23.",
        "TraceId": "478ab71d-48fb709e612eba23",
        "ParentId": "",
        "MachineName": "HOSTNAME_HERE",
        "ThreadId": 9,
        "Application": "APP_NAME_HERE"
      },
      "Renderings": {
        "Elapsed": [
          {
            "Format": "0.0000",
            "Rendering": "2.1560"
          }
        ]
      }
    },
   !-- x amount of more events here --!
  ]
}
```
I do have wireshark traces that I have sent to F5 and can easily reproduce the issue. Before going on to that, is this the right place to raise this issue?

Also, is this going to be a battle of vendors where each one blames the other and the customer (me) doesn't get anywhere?

**Comment by Tratcher** [comment]
@deathchurch by the way, you can tell F5 that their window update algorithm is sub-par. They shouldn't wait for the window to be full before sending an update. That causes unnecessary stalls in the data flow where the client can't send anything else while it waits for the update.

**Comment by deathchurch** [comment]
Thanks @Tratcher for looking into this, I am pleased (in a bad way) that you have been able to replicate the issue. I suppose this means for the time being aspnetcore and F5 with HTTP/2 is not a recommended scenario.

**Comment by geoffkizer** [comment]
It may be weird behavior from F5, but it's still legal. It seems like we could hit this in other cases as well, it's just not nearly as likely.

It sounds like @Tratcher has diagnosed the problem:

> The client sends 5 full frames, 80kb, and then waits for the timeout. Then it sends one more 16kb frame and the RST_STREAM together. 16kb would have put it right at the 96kb limit, but it still should have sent the data. **It sounds like it doesn't flush if it hits the window limit.**

If this analysis is correct, we should definitely fix this.

**Comment by deathchurch** [comment]
Thanks @geoffkizer I think F5 were of the same opinion, they quoted https://datatracker.ietf.org/doc/html/rfc7540#section-5.2.1, and that on the client side they wait for the window to be filled before sending a window update, also they queried why they would they be expected to update the window if its not being used. I think they were open to any suggestions from Microsoft as to what they could improve.

I see you have a PR, hopefully that will resolve the problem, would that be targeted only to net6.0 or would that be available for net5.0 and netcore3.1?

**Comment by Tratcher** [comment]
@karelz for the backport question. Since this is a client stall and an interop issue it is a good candidate for backport.

**Comment by geoffkizer** [comment]
@deathchurch The current F5 behavior will result in poor performance. The client will send up to the window size, then it will need to wait until it gets a window update from the server. This will result in a stall in sending approx equal to the round trip time.

To improve performance, they should send window updates more frequently. Exactly how frequently is a somewhat complex question. For HttpClient, we send a window update for every approx (total window size / 8) bytes consumed by the app. I believe ASP.NET does something similar. But we're also looking at changing our receive window size heuristics for 6.0. There's not necessarily a perfect answer here, but what they are currently doing is definitely suboptimal.

**Comment by karelz** [comment]
Given the above (the fact F5 uses something that leads to more problems), I wonder if we should backport our fix or not.
@deathchurch how much is it blocking you? If the fix is only in 6.0, are you able to consume it and use it to unblock yourself?

If we have more customers hitting it, I am all for backporting.

**Comment by deathchurch** [comment]
@karelz our current policy is to be on the LTS version of framework, so moving to 6.0 would be a 2022 task, probably looking at 12-18 months of staying on 3.1.  At the moment for a workaround wherever we have seen this issue, or potentially could see the issue we are having to explicitly set the client side profile on the F5 to only offer HTTP/1.1, the server side can still be HTTP/2, but it would be better to have the whole call chain as HTTP/2.

@geoffkizer I will pass those suggestions onto F5, in fact they might have already viewed this thread.

**Comment by karelz** [comment]
Thanks @deathchurch for the context. Let's see if more customers are hit by this then.
