### ISSUE TITLE
Tests fails on Android arm devices with unknown opcode name for 1265

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#52454]
Quite a few runtime tests are failing with the following error. For example, src/tests/JIT/Math/Functions/Functions_r.csproj
```
05-06 15:18:31.724 13101 13125 I DOTNET  : MonoRunner initialize,, entryPointLibName=Functions_r.dll
05-06 15:18:31.725 13101 13125 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Math/files/runtimeconfig.bin
05-06 15:18:31.726 13101 13125 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Math/files
05-06 15:18:31.729   13125 D DOTNET  : ((null) error) unknown opcode name for 1265
05-06 15:18:31.729 13101 13125 E DOTNET  : Exit code: 1.
05-06 15:18:31.762   863   863 I Zygote  : Process 13101 exited cleanly (1)
05-06 15:18:31.762  1515  3783 I ActivityManager: Process net.dot.JIT_Math (pid 13101) has died: fg  FGS 
05-06 15:18:31.763  1515  1593 I libprocessgroup: Successfully killed process cgroup uid 10260 pid 13101 in 0ms
```

**Comment by akoeplinger** [comment]
This is hitting the libraries tests as well, for the last ~7 days or so.

**Comment by SamMonoRT** [comment]
@fanyang-mono - isn't this also hitting Android arm32 (arm) devices ?

**Comment by lambdageek** [comment]
This was also seen in Xamarin.Android in .NET 6 Preview 3

https://gist.github.com/grendello/f16aef0be1ce9a43172b19af8228c29f

There's a native stack trace in there.

The most recent PR we had that did stuff to mini-ops.h was https://github.com/dotnet/runtime/pull/49260  but I'm not sure that just adding more opcodes could result in an out of bounds access, since it should just all go through the macros.  Maybe genmdesc needs to know about the new opcodes?

**Comment by lambdageek** [comment]
> And apparently it is not defined (??) when building the runtime for Android for CI.

@imhameed the `DISABLE_ASSERT_MESSAGES` macro is mostly meant for WebAssembly: all the string literals take a bunch of space - all the log messages turn into something like "file.c:1234 <disabled>".  On all the other platforms it wants to actually print the message.

> `g_error ("Opcode '%s' missing from machine description file", ...)`

I think you're right - that one looks suspicious.

> opcode 1265 corresponds to OP_ARM64_XNARROW_SCALAR. That opcode should only ever be handled by the LLVM backend. I have no idea why mini's native code generator is touching this.

is it possible we emit some intrinsic even without LLVM?

**Comment by fanyang-mono** [comment]
The weird thing about this bug is that when removing the definition of `DISABLE_LOGGING`, this issue just went away. There isn't any error message being printed out.

**Comment by lambdageek** [comment]
Ah ok.  in that case when `DISABLE_LOGGING` _is_ defined, any call to `mono_inst_name` will error out.  So if the error goes away completely when `DISABLE_LOGGING` is not defined, then: (a) the instruction code is in range (ie between `OP_LOAD` and `OP_LAST`), but (b) the caller of `mono_inst_name` in `mono_local_regalloc` is some non-fatal context. 

So i think it's one of these three, and not the `g_error`:

https://github.com/dotnet/runtime/blob/b306268b614145908061b14dd24d860dcf3bd6b9/src/mono/mono/mini/mini-codegen.c#L1161-L1166

now I'm not sure what `spec` and `ispec` are, but I guess this block of code is validating that the `mini-ops` instruction specs match the genmdesc description.  but I don't understand what the `== ' '` is supposed to mean.  But apparently `OP_ARM64_XNARROW_SCALAR` isn't satisfying it.

And this actually explains why mini cares about an LLVM instruction - it's not that it appears in any generated code - it's just looping through all defined instruction opcodes.

**Comment by imhameed** [comment]
Oh yeah, `g_error` is fatal. What's confusing is I don't remember seeing any of those 3 messages ever being printed out when doing work on an arm64 Linux server.

**Comment by fanyang-mono** [comment]
> Ah ok. in that case when `DISABLE_LOGGING` _is_ defined, any call to `mono_inst_name` will error out. So if the error goes away completely when `DISABLE_LOGGING` is not defined, then: (a) the instruction code is in range (ie between `OP_LOAD` and `OP_LAST`), but (b) the caller of `mono_inst_name` in `mono_local_regalloc` is some non-fatal context.
> 
> So i think it's one of these three, and not the `g_error`:
> 
> https://github.com/dotnet/runtime/blob/b306268b614145908061b14dd24d860dcf3bd6b9/src/mono/mono/mini/mini-codegen.c#L1161-L1166
> 
> now I'm not sure what `spec` and `ispec` are, but I guess this block of code is validating that the `mini-ops` instruction specs match the genmdesc description. but I don't understand what the `== ' '` is supposed to mean. But apparently `OP_ARM64_XNARROW_SCALAR` isn't satisfying it.
> 
> And this actually explains why mini cares about an LLVM instruction - it's not that it appears in any generated code - it's just looping through all defined instruction opcodes.

So the proper fix is to guard the LLVM only opcodes with a LLVM only macro?

**Comment by vargaz** [comment]
In theory, printf is mapped to g_print on android because of this line:
#ifdef HOST_ANDROID
#define printf g_print
#endif

And g_print is supposed to log into the android event log. So if these lines are hit, they should print something out to the log. Does that happen ?

**Comment by fanyang-mono** [comment]
@vargaz took over and is investigating this issue.
