### ISSUE TITLE
Marshal.GetDelegateForFunctionPoiner returns invalid delegate type

### ISSUE THREAD

**Issue by qrp73** [dotnet/runtime#52502]
There is unmanaged interface which is used to setup callback function with specific signature.

I wrote implementation of this interface in C# and used Marshal.GetDelegateForFunctionPoiner to get delegate for unmanaged function pointer. 

```
[SuppressUnmanagedCodeSecurity]
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
private unsafe delegate void CallbackDelegate(int arg0, int arg1, float arg2, void* arg3);
...
// IntPtr pCallback - unmanaged function pointer obtained from unmanaged code
_callback = (CallbackDelegate)Marshal.GetDelegateForFunctionPointer(pCallback, typeof(CallbackDelegate));
```

It worked well when my code was called from unmanaged code.

But later unmanaged library was switched to managed code which trying to set a pointer to it's managed delegate as unmanaged pointer. This unmanaged code works well with unmanaged interface implementation. But it cause a problem in my managed code. 

It throws the following exception:
```
InvalidCastException: Unable to cast object of type 'ExtCallbackDelegate' to type 'CallbackDelegate'
```

I check it with debugger and it shows that the call Marshal.GetDelegateForFunctionPointer(pCallback, typeof(CallbackDelegate)) returns instance of type ExtCallbackDelegate which is not available (and cannot be available) at compilation time in my code. And when I try to cast it to CallbackDelegate it fails and raise exception.

I think the problem here is because Marshal.GetDelegateForFunctionPointer returns invalid delegate type which is incompatible with delegate type passed as an argument.

Any idea on how to fix it? 

Currently I implemented workaround by calling function pointer pCallback directly from IL code (with calli instruction):
```
ldarg.s    arg0
ldarg.s    arg1
ldarg.s    arg2
ldarg.s    arg3
ldarg.s    pCallback
calli      unmanaged stdcall void(int32, int32, float32, void*)
```

It requires IL code patch after compilation so such solution is hard to support. Also this call is performance critical and I cannot use reflection for that.

It looks that this issue is related with this one: https://github.com/dotnet/runtime/issues/9074

Technical detail:
Framework version: .NET Framework 4.0 Client Profile
OS: Windows 7 x64
Architecture: Process running in x86 mode

**Comment by jkotas** [comment]
Function pointers introduced in C# 9 allow you to write this in C#. This will compile into the same calli instruction as what is in your IL workaround:
```
unsafe
{
    ((delegate *unmanaged[Stdcall]<int, int, float, void*, void>)_callback)(arg0, arg1, arg2, arg3);
}
```
Note that some of the function pointers features do not work on .NET Framework. The C# compiler will report error for most of these situation.

**Comment by qrp73** [comment]
function pointers works ok with C# 9, but it needs to use lang version 9. Unfortunately it is not available in .net 4 compiller. Any other solution? All what I need is just to cast native pointer (which points to not accessible managed delegate) to the managed delegate...

**Comment by jkotas** [comment]
If you need to use C# compiler that comes with .NET Framework, then going via IL is the only reasonable option.

**Comment by gfoidl** [comment]
@qrp73 https://github.com/ltrzesniewski/InlineIL.Fody may help you at writing IL.
