### ISSUE TITLE
Suggestion: WebSockets Please consider exposing the ability to send and receive ping/pong control frames

### ISSUE THREAD

**Issue by alexisatkinson** [dotnet/runtime#52503]
This has previously been discussed in https://github.com/dotnet/runtime/issues/35473

ManagedWebSocket currently handles ping and pong messages transparently to the user, but it would be useful to allow clients to initiate sending and also to receive these messages.

Further to the issue above, I would like to provide another reason for wanting this.

This is useful when a web socket client is connecting to a web socket server that runs a service and there is no useful application level messaging to determine round trip response time.  A very concrete example would be connecting to web socket market data servers that may be running out of different data centers and wanting to measure round/trip response times.  Being able to measure the ping/pong round trip response is similar to using a FIX Protocol test request and heartbeat response to determine round trip response times.

I realise the use case above is perhaps esoteric, but using ping/pong to determine a round trip time can be useful in a number of situations where the client does not control the server protocol and no application level messages are suitable for this.

**Comment by karelz** [comment]
Triage:
- We should not expose Ping/Pong APIs just to provide side-effect capabilities as RTT measurement ... the APIs would confuse users in "if, why and when" they should use the APIs.
- We could consider exposing RTT property, but that seems like a bit of overkill.
- Best option would be to use [`ConnectCallback`](https://github.com/dotnet/runtime/issues/41949) and then set up underlying sockets the way one wishes, incl. querying for RTT there (directly on the Socket).

Closing as the last point above should provide reasonable workaround for the rare scenario.
