### ISSUE TITLE
DPAPI Unprotect CryptographicException: The operation completed successfully

### ISSUE THREAD

**Issue by bgavrilMS** [dotnet/runtime#52537]
### Description

1. Encrypt some data with DPAPI on Windows using `System.Security.Cryptography.ProtectedData` version `4.5.0` 
https://www.nuget.org/packages/System.Security.Cryptography.ProtectedData/4.5.0

2. Sometimes, the library throws an exception saying ` The operation completed successfully.`

Note: I've contacted the Windows DPAPI dev team and they have this should not throw an exception.

```
System.Security.Cryptography.CryptographicException: The operation completed successfully.
at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
```

### Configuration

* Which version of .NET is the code running on? net core 3.1
* What OS and version, and what distro if applicable? Win10

**Comment by mbsnl** [comment]
Reading this [https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/dpapi-masterkey-backup-failures](url)
Question: When you are in a domain with a Read-Only Domain Controller, would adding the following Registry entry, resolve the Connect-AzAccount issue?


Path | HKEY_LOCAL_MACHINE\Software\Microsoft\Cryptography\Protect\Providers\df9d8cd0-1501-11d1-8c7a-00c04fc297eb
-- | --
Setting | ProtectionPolicy
Data Type | DWORD
Value | 1
OS restart requested | Yes

**Comment by bartonjs** [comment]
@GrabYourPitchforks Since you were following up on this via alternate streams, I'm leaving the triage sorting up to you.

**Comment by GrabYourPitchforks** [comment]
Per email, issue seems transitory and customer can no longer repro it. Feel free to reopen this issue if we get a solid repro.
