### ISSUE TITLE
Should we backport recent FileStream improvements to Microsoft.IO.Redist?

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#52533]
@ericstj @JeremyKuhne I wanted to follow up on the question of whether we should consider backporting our recent `FileStream` improvements to `Microsoft.IO.Redist`.

The main limitation is the usage of `IValueTaskSource` which is a .NET Core concept and it's not available for Full Framework. 

The only idea that I have is to create a dedicated implementation of [AsyncWindowsFileStreamStrategy](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/AsyncWindowsFileStreamStrategy.cs) for `Microsoft.IO.Redist`. It would be more or less the `AsyncWindowsFileStreamStrategy` before @carlossanlop memory allocations improvements (which required to use `IValueTaskSource`).

It would not be hard from a development perspective (copy-paste of two files, some `#if MS_IO_REDIST` here and there), but it would increase a lot the maintenance cost as it would require us to maintain three implementations of async FileStream strategies:

* `AsyncWindowsFileStreamStrategy` (what we ship by default in .NET 6)
* `Net5CompatFileStreamStrategy` (what users can fallback to if they want)
* `AsyncWindowsFileStreamStrategy`  for `MS_IO_REDIST`

I would prefer not to backport it until we have a strong business case that would justify the investment.

cc @jeffhandley @carlossanlop @Jozkee @stephentoub

**Comment by jkotas** [comment]
> I would prefer not to backport it until we have a strong business case that would justify the investment.

We should not do this proactively. The only reason for doing this would be if there is a really important customer asking for it.

I think it is safe to close this issue.

**Comment by ericstj** [comment]
Thanks for considering this.  I was only suggesting as an option if it was cheap/free.  I agree we shouldn't be doing significant engineering investment for this.
