### ISSUE TITLE
JsonSerializer.Deserialize doesn't deserialize chinese strings

### ISSUE THREAD

**Issue by thepra** [dotnet/runtime#52534]
### Description

I have this JSON string:
```
[{"id":"6098d7d6c66ced2dd645e398","name":"一册A班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e399","name":"一册B班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39a","name":"三册A班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39b","name":"三册B班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39c","name":"四册A班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39d","name":"四册B班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39e","name":"五册班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e39f","name":"六册班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e3a0","name":"八册班","teachersIds":[]},
{"id":"6098d7d6c66ced2dd645e3a1","name":"九册班","teachersIds":[]}]
```

and when I do `JsonSerializer.Deserialize<List<Classes>>(json);` in my Blazor WebAssembly client
I get the list but the `name` property is always `null`, as if it's impossible to parse those unicode strings.
Is there any way around this? Forcing in some way the decoding to UTF8?

### Configuration

* Which version of .NET is the code running on? .NET 5
* What OS and version, and what distro if applicable? Windows 10 Pro
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No
* If you're using Blazor, which web browser(s) do you see this issue in? Chrome

### Other information

No errors in this regard, and the namespace is `System.Text.Json` of that `JsonSerializer`

**Comment by GrabYourPitchforks** [comment]
The `Deserialize` method doesn't special-case Chinese vs. any other language. I suspect something else is happening. Can you share the definition of your `Classes` class?

**Comment by thepra** [comment]
Did some extra testing and it's the old camelCasing issue, so I have only the old hack on WebAssembly given that AddJsonOptions(...) doesn't exist on the client pipeline:
```
((JsonSerializerOptions)typeof(JsonSerializerOptions)
	.GetField("s_defaultOptions", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic).GetValue(null))
						.PropertyNameCaseInsensitive = true;
```
or
```
((JsonSerializerOptions)typeof(JsonSerializerOptions)
	.GetField("s_defaultOptions", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic).GetValue(null))
						.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
```

It's weird also that by default in a Blazor WebAssembly template with hosting the back-end isn't serializable by default on the front-end side without some JSON setup to make it compatible.

**Comment by eiriktsarpalis** [comment]
I'm going to close the issue as by-design. Assuming the WebAssembly host builder is lacking functionality to specify a custom `JsonSerializerOptions` instance, I would recommend filing a separate issue in the aspnetcore repo.
