### ISSUE TITLE
Channels: a minimum capacity before WaitToWriteAsync() returns.

### ISSUE THREAD

**Issue by JVanloofsvelt** [dotnet/runtime#52544]
## Background and Motivation
Channels are a great addition to .NET to help with async producer-consumer scenarios, but I feel like they lack a feature that would make them even more useful. 

Imagine a scenario where your producer is a loop that opens a connection to an external service, a service that uses this connection to push messages to your service. With a channel you can buffer these messages, and the consumers can process them on their own pace. So far so good.

But due to a sudden spike in the load, the external service is flooding you with messages and your buffer (bounded channel) is filling up. You chose to create a bounded channel because you didn't want this scenario to cause all your memory to be used up by those buffered messages.

Ideally, you would close that connection with the external service, wait for some time to give your consumers a chance to empty the buffer to some extent (fully empty, half-empty, whatever). You can now reopen the connection with the external service to start receiving more messages before your channel dries up completely and your consumers end up idling. 

At this time the ChannelWriter class has a `WaitToWriteAsync()` method that allows your producer to wait for any message slot in your bounded channel to be freed up. There is no way to wait until some larger number of slots is freed up, and neither do the Channel or ChannelWriter have a `.Count` property. Using `WaitToWriteAsync()` you would be opening and closing the connection with the external service for each message, and in some cases this would be considered excessive.

## Proposed API
I have no strong opinion on the ideal API to help this scenario, but it could be something like an overload to `WaitToWriteAsync()` that accepts a required number of "free slots" before the method should return.

For example:
```c#
WaitToWriteAsync(int minimumRemainingCapacity, CancellationToken cancellationToken);
````
@stephentoub I read your very informative blogpost on channels: https://devblogs.microsoft.com/dotnet/an-introduction-to-system-threading-channels/ Thanks for this. I'm interested to hear your opinion.

**Comment by stephentoub** [comment]
>  it could be something like an overload to WaitToWriteAsync() that accepts a required number of "free slots" before the method should return

I don't think we'd want to do this on a per-operation basis: that would not only increase complexity, but it would lead to significant inefficiencies, having to find the next pending write that would support the currently available number of free slots.

What would be possible, and what we previously considered doing but didn't due to lack of motivating scenarios, would be adding a low water mark to BoundedChannelOptions, such that all operations would not only respect the capacity but also the minimum amount of space available before writers could be released.

**Comment by JVanloofsvelt** [comment]
Yes you're right, on a per-operation basis brings additional complexities that I didn't think of earlier. So a 'low water mark' for BoundedChannelOptions would at least be simpler to implement. 

In the use case I had in mind there is only one writer, so if this writer is waiting for a 'low water' signal by awaiting WaitToWriteAsync(), then there are few(er) race condition troubles once the number of messages in the channel drops below the mark: it will only drop further until the single writer notices the signal returned through WaitToWriteAsync(), since no other writer is adding items to the channel (the semantics of the signal is preserved: 'you are now able to write to the channel again').

I'm not sure if blocking the writer while writing is sufficient for my suggested use case, since it needs to be notified **_before_** the writer/producer fetches more messages from its source (its acting more like a message pump I guess). Thats why I'm relying on WaitToWriteAsync(). Perhaps both methods can wait for the low water mark signal.

My use case, more specifically, is one where I open a streaming websocket connection to a Firebase database: their realtime database streams updates to my service that queues them in the service's internal memory. If it happens that there is a flood of updates, then I close this connection once the internal buffer/channel has filled up.  On the other end of the channel there is a consumer that launches up to N concurrent Tasks to process the messages.

Thanks for considering my suggestion. It's great to hear you have also thought about a 'low water mark'.
