### ISSUE TITLE
WebSocket compression issues when testing server-side with Autobahn

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/runtime#52551]
When trying to add WebSockets compression support to ASP.NET Core I ran the Autobahn test suite against the server and hit multiple test cases failing.

I'm going to focus on a single one in this issue because it's already complicated enough (and hopefully same root issue).

This specific issue is looking at test 12.4.11 which states: "Send 1000 compressed messages each of payload size 8192, auto-fragment to 256 octets. Use default permessage-deflate offer." I modified the client window bits to be 12 (was testing various window bits and hitting issues on different tests with different window bits)

I manually looped over all the messages until I found one that wasn't 8192 in size and have isolated that individual message for the repro below.

Single message test bytes from client
[compressed8192fromClient12bit.txt](https://github.com/dotnet/runtime/files/6454163/compressed8192fromClient12bit.txt)

```c#
[Fact]
public async Task CompressTest()
{
    WebSocketTestStream stream = new();
    using WebSocket server = WebSocket.CreateFromStream(stream, new WebSocketCreationOptions
    {
        IsServer = true,
        KeepAliveInterval = TimeSpan.Zero,
        DangerousDeflateOptions = new()
        {
            ClientMaxWindowBits = 12,
            ServerMaxWindowBits = 15,
            ClientContextTakeover = false,
        }
    });
    using WebSocket client = WebSocket.CreateFromStream(stream.Remote, new WebSocketCreationOptions
    {
        KeepAliveInterval = TimeSpan.Zero,
        DangerousDeflateOptions = new()
        {
            ClientMaxWindowBits = 12,
            ServerMaxWindowBits = 15,
            ClientContextTakeover = false,
        }
    });

    using var fileStream = File.OpenRead("<path to>/compressed8192fromClient12bit.txt");
    int r = 1;
    var fileBuf = new byte[2000];
    while (r != 0)
    {
        r = await fileStream.ReadAsync(fileBuf);
        await stream.Remote.WriteAsync(fileBuf.AsMemory(0, r), default);
    }

    var buf = new byte[8192];
    int total = 0;
    while (true)
    {
        var res = await server.ReceiveAsync(buf, default);
        total += res.Count;
        if (res.EndOfMessage == true)
        {
            Assert.Equal(8192, total);
            break;
        }
    }
}
```

Some more information about this specific message:
Inflated sections (bytes): 320, 3226, 822, 1736, 2115 - total = 8219
WebSocket frame lengths: 256, 256, 256, 256, 243

cc @zlatanov in case you're interested

**Comment by zlatanov** [comment]
@BrennanConroy I added a barebone websocket server here: https://github.com/zlatanov/websockets-compliance. After running the test case `12.4.11` it passed without problems. Actually all tests pass without any issues.

I ran the tests using the latest build from the runtime and `corerun.exe "C:\Projects\Github\websockets-compliance\src\bin\Debug\net5.0\WebSocketCompliance.dll"`.

I didn't find any issues in your code at first glance. Can you try and run my project and see if the test succeeds / fails?

[kestrel_case_12_4_1.zip](https://github.com/dotnet/runtime/files/6455515/kestrel_case_12_4_1.zip)

**Comment by zlatanov** [comment]
I've attached the results for all 12.* cases, all green.

[kestrel_case_12.zip](https://github.com/dotnet/runtime/files/6456632/kestrel_case_12.zip)

> Also, how do you run your app?

Assuming that you have https://github.com/dotnet/runtime in `x:\runtime`, I build it with `build.cmd clr+libs -rc Release`. Then copy the output of `Microsoft.AspNetCore.App` from `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.5` to `x:\runtime\artifacts\bin\testhost\net6.0-windows-Debug-x64\shared\Microsoft.NETCore.App\6.0.0`.

Build my project in either debug or release. Then start it with:

```bash
cd "x:\runtime\artifacts\bin\testhost\net6.0-windows-Debug-x64\shared\Microsoft.NETCore.App\6.0.0"
corerun.exe "x:\websockets-compliance\src\bin\$(Configuration)\net5.0\WebSocketCompliance.dll" --urls http://localhost:9001
```

**Comment by zlatanov** [comment]
Thanks for the findings. I will investigate what is happening.
