### ISSUE TITLE
Unable to use the package on Linux (Ubuntu) running .Net Core 5.0

### ISSUE THREAD

**Issue by red4cape** [dotnet/runtime#52570]
I have been getting the below error while trying to start my application on Ubuntu 20.04, with .Net 5.0 installed.

An assembly specified in the application dependencies manifest (Entry.deps.json) was not found: package: 'System.Drawing.Common', version: '5.0.2' path: 'runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll'

The project builds and runs without any errors on Mac OSx... However when I publish the Release to Ubuntu, I get the above error.

Note: I am using package Svg version 3.2.3, which is dependent on System.Drawing.Common.

I have already tried adding "System.Drawing.Common" nuget to the project but no luck. Any help is appreciated.

**Comment by safern** [comment]
@red4cape, so to understand correctly, you are building on OSX and then trying to deploy to your Ubuntu machine? How are you building/deploying the app? 

Could you provide a small example app and some steps to reproduce?

**Comment by red4cape** [comment]
I develop using Visual Studio for Mac (not VS Code).

Steps to reproduce:

1. Create Console application. Choose .Net 5.0
2. Install the [Official Svg Nuget](https://www.nuget.org/packages/Svg/)
3. Write any simple Svg Load code. (Example provided at the bottom).
4. Build
5. Publish to local file system from Visual Studio
6. Copy the Published folder to Ubuntu 20.04 [Note: Ubuntu already has dotnet installed following [Ubuntu Dotnet Installation](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)]
7. Run the binary as > ./Entry.dll  [Note: I named my console app "Entry"]
8. You would get the below error.
`An assembly specified in the application dependencies manifest (Entry.deps.json) was not found: package: 'System.Drawing.Common', version: '5.0.2' path: 'runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll'`

Sample code to add in program.cs Main():
`
var path = "/local/path/file.svg";
var pngPath = "/local/path/converted.png";
var svgDocument = SvgDocument.Open<SvgDocument>(path);
var bitmap = svgDocument.Draw();
bitmap.Save(pngPath, ImageFormat.Png);
`

**Comment by red4cape** [comment]
Added a symbolic link to "/usr/share/dotnet/shared/Microsoft.AspNetCore.App/5.0.5" from "runtimes/unix/lib/netcoreapp3.0".
That fixed the problem. Good enough for now to unblock me.
