### ISSUE TITLE
Please have System.Collections.Generic.Dictionary<TKey, TValue> implement ISet (and IReadOnlySet) <KeyValuePair<TKey, TValue>>

### ISSUE THREAD

**Issue by RonenGlants** [dotnet/runtime#52589]
## Background and Motivation

By definition, all dictionary keys are different, therefore it is guaranteed that there will be no duplicated KeyValuePair s.

From [this](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?redirectedfrom=MSDN&view=net-5.0) documentation:
> For purposes of enumeration, each item in the dictionary is treated as a KeyValuePair structure representing a value and its key. The order in which the items are returned is undefined.

It is suggested that by definition the key-value collection has no predefined order.

For these two reasons, I think that It is more accurate to mark the collection as a set.
This implementation will help to treat the dictionary as an order agnosic and not repetitive collection which will help with abstraction in some cases.

## Proposed API

```diff
namespace System.Collections.Generic
{
-    public class Dictionary<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>>, IEnumerable<KeyValuePair<TKey, TValue>>, IEnumerable, IDictionary<TKey, TValue>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue>, ICollection, IDictionary, IDeserializationCallback, ISerializable where TKey : notnull {
+    public class Dictionary<TKey, TValue> : ISet<KeyValuePair<TKey, TValue>>, ICollection<KeyValuePair<TKey, TValue>>, IEnumerable<KeyValuePair<TKey, TValue>>, IEnumerable, IDictionary<TKey, TValue>, IReadOnlySet<KeyValuePair<TKey, TValue>>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue>, ICollection, IDictionary, IDeserializationCallback, ISerializable where TKey : notnull
     }
```

## Usage Examples

``` C#
// Method with the following signature will be able to accept dictionaries and assume anything that is relevant only to sets.
public static bool SomeMethod<T>(this IReadOnlySet<T> value) => false;
```

## Alternative Designs

In my suggestion, I added the interfaces ISet and IReadOnlySet to the list of interfaces.
Another possibility is to replace ICollection with ISet (same for read-only) for ISet is implementing ICollection.

## Risks

I don't think of any risks with just adding the interfaces.
With the replacement alternative, there is maybe a backward compatibility issue(?).
Though I can not think of a scenario in which someone cares if ICollection is a direct implementation or a "second hand" implementation. (Dictionary is ICollection == true in both options).

**Comment by ohadschn** [comment]
Related: https://github.com/dotnet/runtime/issues/23244

**Comment by eiriktsarpalis** [comment]
> It is suggested that by definition the key-value collection has no predefined order.
>
>For these two reasons, I think that It is more accurate to mark the collection as a set.

There is nothing about `ICollection<T>` that presupposes a fixed order of elements, that is a property typically reserved for types implementing `IList<T>`.

What would be the motivating use case for implementing ISet in Dictionary? While it is technically true that a dictionary forms a set over key/value pairs, I don't think it is a useful abstraction in that context (IDictionary being more appropriate in most cases). Note that implementing set semantics appropriately would require specifying equality comparison for the value type, something that the mutable dictionary does not do. There is also a performance penalty associated with appending interface implementations to existing types, so we generally try to avoid it for popular types like Dictionary unless there is a compelling use case.

In light of the above, I don't think we should making this change. /cc @jkotas

**Comment by jkotas** [comment]
I agree with @eiriktsarpalis assesment.

**Comment by RonenGlants** [comment]
Thank you for the response. 
I guess it is not as naive as I originally thought.
