### ISSUE TITLE
Duplicated loop body

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#52586]
Follow pattern results in a duplicated loop body:
```c#
        for (int i = 0; i < arr.Length; i++)
        {
            for (int j = i; j < arr.Length; j++)
            {
                var b = arr[j];
                Console.WriteLine(b);
            }
        }
```
See https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgMwAEOZAwmQN5FmMXmYAsZAsgBSwJkwBKOgyaiAbhABOZKdIC8/AKYB3MrwDaMALoBuEaMYAzAPbSeMPlDIKADDrVkAPDMmSAdABlFMAOYIAFvZQANTBAvoG9IQGMWQmZrxkAFbWavYpzrKe3n6ByaHh0bGiUcXFAPTlEtIQqbLqULoRZUyVmLgAnFwQAnpFLeJSZMB1rupJTf0DjO1dwL3NsQC+i4wrU+tLQA

category:cq
theme:loop-opt
skill-level:expert
cost:medium
impact:small

**Comment by AndyAyersMS** [comment]
cc @BruceForstall

**Comment by BruceForstall** [comment]
https://github.com/dotnet/runtime/issues/8558 Covers this somewhat: loop cloning kicks in for the inner loop, eliminates the "fast path" bounds check. But later on, assertion prop gets rid of the array null check it inserted, and range prop gets rid of the "slow path" bounds check, so the loops are the same. Assertion prop doesn't get rid of the extra "i < 0" check that gets inserted (which is should). If that was eliminated, we're left with https://github.com/dotnet/runtime/issues/5820.
