### ISSUE TITLE
Resident Set Size on Linux remains much higher than managed memory usage in .NET 5.0

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/runtime#52592]
After upgrading our application, running on Ubuntu 18.04, from .NET Core 3.1 to .NET 5.0 we're seeing a consistently higher Resident Set Size memory usage.

The application normally processes web requests at a steady rate, but once per day it updates its data, which causes much higher RAM usage for 1-30 minutes. After this, we see the managed memory (as reported by `GC.GetTotalMemory`) drop about the same way on .NET 3.1 and 5.0. However, the Resident Set Size for the process either remains unchanged or drops gradually over the next few hours, but is still way higher than managed memory - we're talking ~6 GB reported by `GC.GetTotalMemory` and ~33 GB Resident Set Size.

To further confuse things, we had 3 instances of the application running at the same time on the same machine receiving the same requests. One on .NET 3.1, another on .NET 5.0 with otherwise identical code and another on .NET 5.0 with some code differences. The RSS dropped for the .NET 3.1 version and the identical .NET 5.0 version, but not the newer .NET 5 version, implying something about our code changes may have caused the difference, but I can't see what that can be when the managed memory went down the same way for all of them.

https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/ mentions a number of GC changes in .NET 5, in particular #37894 which sounds relevant. Is there any documentation on how RSS is expected to behave in .NET 5? For example, when does the GC consider itself to be in a "low memory situation"? I was unable to find anything. Basically, what we're trying to figure out is whether this is a problem or expected behavior. If expected, the next question would then be how to tell how much RAM the server really has available to run more instances of the application.

**Comment by mangod9** [comment]
Adding @PeterSolMS as fyi. RSS is something handled by the OS and dont believe .net can influence how resident vs. swapped would be managed. Assume you dont see any other performance issues with the app (like throughput differences due to frequent GCs and such)?

**Comment by Maoni0** [comment]
are you using Server GC? in .NET 5 we moved the decommit at the end of ephemeral segment out of the GC pause so you would see resident pages gradually dropping, however it wouldn't be as long as hours. it should come down much more quickly than that unless you need the memory committed again. if you could [collect a trace for these processes](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#how-to-collect-top-level-gc-metrics) that'd be helpful.

high memory load is explained [here](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#gc-is-per-process-but-is-aware-of-physical-memory-load-on-the-machine). 

@PeterSolMS it'd be helpful to have some instrumentation around the decommit since now we don't know how much we will be decommitting. perhaps at the beginning of the GC we could give some info how much we've decommitted so far?

**Comment by loop-evgeny** [comment]
We are using server GC. Thanks for the link, that's the kind of thing I was looking for! I will read it in more detail later, but I saw that "low memory situation" means 90-97% memory used. That was not the case on this machine (it has 512 GB RAM and no more than 75% of that was ever used), so sounds like maybe the GC didn't think it needed to bother to return RAM to the OS?

Here is the managed memory usage from last night:
![image](https://user-images.githubusercontent.com/34301024/117952713-b65a7a00-b315-11eb-98c8-dfcf82907a52.png)
The yellow line is a .NET 3.1 version, the black one is .NET 5.0 with otherwise identical code and blue is .NET 5 with code changes. Quite similar other than the height of the peak.

Now, here is the sum of (VmRSS+VmSwap) over the same period:
![image](https://user-images.githubusercontent.com/34301024/117953124-210bb580-b316-11eb-97ef-c877c291e180.png)
Here the read line is .NET 3.1, the yellow is .NET 5.0 with otherwise identical code and black .NET 5.0 with code changes.
(Confusing that the colors are not the same, I know, but I can't control that, sorry!)

I'm not sure if I can get a trace - that would have have a high CPU or RAM overhead or use a lot of disk, right? Can it run with the tracing on for something like 12 hours?

**Comment by mangod9** [comment]
can you provide some details / pseudocode of your changes? Perhaps you could try reverting some which feel allocation/caching related and see if that has any effect? Thx.

**Comment by loop-evgeny** [comment]
I ran the test again over the last 4 days, this time with each version of our code (labelled v44 and v45 here) on both .NET 3.1 and 5.0. There is also an earlier version (v43 here), which is on .NET 3.1 only.

Again, the managed memory (GC.GetTotalMemory) is very similar between them:

![managed2](https://user-images.githubusercontent.com/34301024/118483528-66652400-b716-11eb-994e-e25880c5dc70.png)

VmRSS+VmSwap is markedly different between .NET 3.1 and 5.0 for otherwise identical code:

![private-bytes2](https://user-images.githubusercontent.com/34301024/118483527-65cc8d80-b716-11eb-9402-1cacf5b7a48b.png)

... but it seems to have gotten worse with each release of our code (v43->v44->v45) even on .NET 3.1. The spike occurs around 02:30 when we run a nightly scheduled task to reload some data and does not fully go down until 10:00-22:00, depending on that day - but it does eventually go down, which is something.

No, I cannot provide pseudocode, as it's a large and complex application. We also made a lot of changes between releases and trying to bisect which change caused it to get worse would be very time-consuming.

So my main question is: is there anything we can do to get .NET to return RAM to the OS sooner?

I will try to get a trace.

**Comment by loop-evgeny** [comment]
I found that our v43 version was doing a `GC.Collect()` after the big nightly data reload, while the v44 and v45 code versions were not. I enabled the `GC.Collect()` again and got this:

![private-bytes3-v45](https://user-images.githubusercontent.com/34301024/118631821-26fb0e00-b7d0-11eb-988d-0ba0423598ae.png)

So the RAM usage goes down much sooner than without the `GC.Collect()`, but it still takes much longer in .NET 5.0. (We disabled the `GC.Collect()` because of a problem where if 5-10 processes did this around the same time they all got "stuck" inside the `GC.Collect()` call, which was pretty bad! So I'm reluctant to re-enable that in production.)

In our v44 version I additionally made it reload some of the data every 15 minutes instead of just once per day, trying to repro the problem quicker, and got this:

![private-bytes3-v44](https://user-images.githubusercontent.com/34301024/118632027-54e05280-b7d0-11eb-804d-94178e204373.png)

So not really the same, unfortunately - .NET 5.0 does use noticeably more RAM, but it doesn't take hours and hours to release it (probably because we then use more RAM again very soon).

**Comment by loop-evgeny** [comment]
We've had to downgrade our application to .NET Core 3.1 for now because of this issue, but will have to upgrade from 3.1 eventually, so we'd still like to solve this. I have traces now for .NET 3.1 and 5.0 versions over the same time period with the same requests sent to them. Is there a way I can send those traces to you without uploading them here @Maoni0 ?

**Comment by mangod9** [comment]
Hey @loop-evgeny, please send a link to the traces to my email (should be included in my profile). Also adding @brianrob since this is a perf degradation investigation when compared to 3.1. Thanks!

**Comment by loop-evgeny** [comment]
Emailed, thanks!

**Comment by loop-evgeny** [comment]
@mangod9 Any idea when you may be able to look at this? It's no longer urgent for us, but we will eventually need to upgrade from 3.1, and preferably to 6.0 (since that's an LTS version), so it would be great to get any fix for this into 6.0.

**Comment by PeterSolMS** [comment]
Hi @loop-evgeny,  sorry about the delay. I had a look at the profiles, and I suspect that a change to gradually decommit memory in Server GC causes the issue. The intention was in fact to give back memory more slowly to the OS, but not *that* slowly - to give back several GB like in your case should take less than a minute. I wonder whether this problem is specific to Linux - I'll try to repro on our side, and possibly ask you for more information.

**Comment by loop-evgeny** [comment]
I see that #55174 got merged recently. Will this be in 6.0.0-preview.7? Should I tests our application on that?

**Comment by PeterSolMS** [comment]
Hi @loop-evgeny, it looks like I just missed the preview 7 deadline. Of course it would be very useful to test your application with the fix - you could either wait for preview 8, or build coreclr yourself and copy it over a preview 7 install for testing.

Either way, it would be great if you could provide an updated profile - that would help us check that the change did have the intended effect.

**Comment by loop-evgeny** [comment]
I don't fancy building coreclr myself (I remember trying some time ago and not getting very far), but if you want to upload a private build (linux-x64) somewhere I could give it a shot once preview 7 is out. (Probably not for a while, since preview 6 was just released 5 days ago?)

**Comment by PeterSolMS** [comment]
I'll see what I can do about providing a private build once preview 7 is out.

**Comment by mangod9** [comment]
Hey @PeterSolMS, assume the fix has been merged but this is open till it can be validated?

**Comment by Maoni0** [comment]
could we validate this with the next preview build?

**Comment by loop-evgeny** [comment]
Preview 7 is out. If you could make a build with this fix I can probably try it out next week. After that I'll be on holidays for 2 weeks. @PeterSolMS

**Comment by Maoni0** [comment]
Peter is still on vacation this week. you could get a daily build from [here](https://aka.ms/dotnet/6.0/daily/dotnet-runtime-linux-x64.tar.gz) that contains Peter's change.

**Comment by loop-evgeny** [comment]
The results so from one night of test (zooming in on the interesting part):

[W-2021-08-18](https://user-images.githubusercontent.com/34301024/129860053-1c1cc97b-9a5f-40aa-a5f4-daf56a4ce938.png)

"-withfix" is .NET 6.0 daily build 21416.10. Private bytes does go down this time, but still takes almost 2 hours to do so.

The peak memory usage, both managed and VmRSS, is also noticeably higher on .NET 6.0 than 5.0.

**Comment by mangod9** [comment]
Hi @loop-evgeny, is it possible to collect gc-only traces on both 5 and 6, so we could analyze this further?

**Comment by loop-evgeny** [comment]
Hi @mangod9 you mean exactly the same traces, as before, right? `dotnet-trace collect --profile gc-collect --duration 12:00:00 -p 17131 -o ...` ?

Should I do that with the daily build of the 6.0 SDK or the stable 5.0 SDK or the SDK version matching the .NET runtime for each process?

**Comment by mangod9** [comment]
> you mean exactly the same traces, as before, right

Yeah correct, ideally the sdk version matching the runtime to ensure there are not issues with collection.

**Comment by loop-evgeny** [comment]
Alright, I've set that up, will email you the traces tomorrow if all goes well!

**Comment by loop-evgeny** [comment]
Emailed you the traces @mangod9. Here are the corresponding memory usage profiles, for midnight to 10:00 today (the same time the traces cover).

W/v45

![W-2021-08-20](https://user-images.githubusercontent.com/34301024/130207782-dbf12e8a-6db7-45bb-851d-48c4f4d7c7d6.png)

X/v50

![X 2021-08-20](https://user-images.githubusercontent.com/34301024/130207806-e4938a95-be03-45f8-8cd1-0582e91b82a7.png)

**Comment by loop-evgeny** [comment]
Hi @PeterSolMS , I just got back from a vacation. Thanks for the further fixes! How do I test these? Apply the nightly binaries on top of preview7 as before?

**Comment by PeterSolMS** [comment]
Hi @loop-evgeny, I think that should work, if not, let me know.

**Comment by loop-evgeny** [comment]
Ran the same test with  .NET 6.0.0-rc.2.21458 and it looks much better now! Still not as good as .NET 3.1, but I think we'll be able to upgrade now. Thanks very much for the fixes!

![W2021-09-13](https://user-images.githubusercontent.com/34301024/133110045-b0680977-dc98-4600-9e49-72e7264f7166.png)
![X2021-09-13](https://user-images.githubusercontent.com/34301024/133110060-fe10d102-0422-40e6-a849-900b114bb95f.png)
