### ISSUE TITLE
Conversion between JsonElement and JsonNode

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/runtime#52611]
Hey everyone,

I have a question: the original writable DOM design had dedicated APIs to convert `JsonElement` from and to `JsonNode` instances. I don't see an equivalent in the recent implementation. Is this planned?

Thanks.

**Comment by eiriktsarpalis** [comment]
cc @steveharter

**Comment by kevinchalet** [comment]
I see there's a `Create` method to create a JSON node from a `JsonElement` but I don't see an equivalent to do the reverse operation. Did I miss something?

**Comment by steveharter** [comment]
Some of the design thoughts on interop between `JsonElement` and `JsonNode` is explained in this [section](https://github.com/dotnet/designs/blob/main/accepted/2020/serializer/WriteableDomAndDynamic.md#interop-with-jsonelement).

The functionality to obtain a `JsonNode` from `JsonElement.ToNode()` can be done by just creating a node with the appropriate `JsonElement`.

The reverse -- going from `JsonNode` to `JsonElement` can be an expensive operation if the underlying node is not based on `JsonElement` as will be the case when in "edit mode" when creating new nodes. For these cases it would need to basically do a `JsonSerializer.Deserialize<JsonElement>(node.ToJsonString())`, and providing that in a method like `JsonNode.ToElement()` is perhaps is hiding too much.

@kevinchalet can you go over the scenarios where you think it is useful to go from `JsonNode` to `JsonElement`?

**Comment by kevinchalet** [comment]
Thanks for your reply @steveharter!

> @kevinchalet can you go over the scenarios where you think it is useful to go from `JsonNode` to `JsonElement`?

Sure. Here's a very concrete scenario: in the OpenIddict project (that was one of the first "big" projects to adopt STJ everywhere, BTW), we allow storing extra properties in the DB entities (e.g OrchardCore's OpenID module uses these properties to store things like application roles: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs#L88-L98 / https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.OpenId.Core/Services/Managers/OpenIdApplicationManager.cs#L155-L162).

At the time, the `ImmutableDictionary<string, JsonElement>` representation was chosen because it was the most reasonable compromise between perf and convenience (using `JsonElement` directly is not super friendly as you can't easily "add" new properties).

Being able to natively convert a `JsonNode` like an array to a `JsonElement` would be very useful in that case and would likely help make things clearer and cleaner.

**Comment by kevinchalet** [comment]
Another concrete use case: OpenIddict uses a struct called `OpenIddictParameter` to represent OpenID Connect parameters, that can be primitives like strings, integers or booleans, but also more complex JSON representations using `JsonElement`: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Abstractions/Primitives/OpenIddictParameter.cs

If there was native conversion between `JsonNode` and `JsonElement`, one could simply do `new OpenIddictParameter(a JSON node instance)` without requiring a massive change in that primitive to support both `JsonElement` and `JsonNode` (which would basically require duplicating a lot of logic).

**Comment by kevinchalet** [comment]
@steveharter I'd love to hear your thoughts about these scenarios 😄

**Comment by kevinchalet** [comment]
@steveharter did you have a chance to take a look at the scenarios I mentioned?

**Comment by steveharter** [comment]
> If there was native conversion between JsonNode and JsonElement, one could simply do new OpenIddictParameter(a JSON node instance) without requiring a massive change in that primitive to support both JsonElement and JsonNode (which would basically require duplicating a lot of logic).

In V6 RTM (after Preview 7 unfortunately) there is a new feature that allows a `JsonNode` to deserialize to any serializer-supported type, including `JsonElement`:
```cs
 JsonNode node = JsonNode.Parse("42");
 JsonElement element = node.Deserialize<JsonElement>();
 int i = element.GetInt32(); // 42
```

Note that this is not a free operation; basically a the node is serialized to `byte[]` and that buffer is used to deserialize a `JsonElement`.

@KevinCathcart is this sufficient to close this issue, or should we move to 7.0 for better interop? Thanks

**Comment by steveharter** [comment]
Closing; assuming the new JsonSerializer extensions are sufficient. Please re-open if necessary.
