### ISSUE TITLE
Min 0 Budget changes between 2.2 -> 3.x+ leads to P99 regressions

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#52623]
This is a performance regression which was originally tracked via #42938. Since then the issue has been closed; however, it is still being hit in partner teams.

/cc @Maoni0 @mangod9

**Comment by Maoni0** [comment]
if you are talking about the issue your team hit that you brought to my attention months ago, that was not related to 42938. the issue you hit was a change in behavior. that behavior is not going to change again. you can use the config I mentioned to revert to the previous behavior.  

if you are referring to a different issue that you believe is related 42938, then please share some data with us so we can verify it.
