### ISSUE TITLE
Test failure Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52631]
Run: [runtime 20210511.85](https://dev.azure.com/dnceng/public/_build/results?buildId=1133313&view=ms.vss-test-web.build-test-results-tab&runId=34392204&resultId=103187&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open

- Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange

```

**Error message:**
```
Callback should have been invoked
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.cs:line 408
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20220618.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1832165&view=ms.vss-test-web.build-test-results-tab&runId=48479454&paneView=debug&resultId=145038)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open

- Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange

```
**Error message:**
```
Callback should have been invoked
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.cs:line 407
--- End of stack trace from previous location ---
```

**Comment by jkotas** [comment]
Failed again in https://github.com/dotnet/runtime/pull/71820

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20220709.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1869897&view=ms.vss-test-web.build-test-results-tab&runId=49010196&paneView=debug&resultId=130581)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open

- Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange

```
**Error message:**
```
Callback should have been invoked
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.TokenCallbackInvokedOnFileChange() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.cs:line 407
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
Milestone should not be future for something impacting CI, at a minimum we should disable the test in the near term.

**Comment by danmoseley** [comment]
Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI1RS2vCQBC%2bC%2f6HwZMBW9tLbym0imChattAj7Jmx2TMOhv2USn447vZxGqhB0%2b7M99jXhla947WK2f7vSPsNDFUxDIlZjTwqU01d7i3oPk3mMv%2fqC96E1nhbQjj8REOJRqEGTHZEiU8psD6MLx5uJNJ49DCbXVIUxjMBKnBGXlFV2oZkUxXyBOh1Ebk1Zy%2fQiiXPCOFk1JwgX9U1ooCwTphnD2QK2FwUkZabfQOcwf9HsCKalTECCk4bZ0hLoa1MBbXO6t5uDK6RuMIbXI7xW0YxJHmhdhjMrqUryeat1R4Ixr8CrP8kt96LT%2bC7s2jx8Y%2fpp5MXl5hJgKNXBjJm66vLFw1CLPvGu9jol3y6HSKmJt25WPQ7jp%2bnz0peUXZyFv4%2fQZN0nnEzfd7P4rG%2bA1VAgAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1RS2vCQBC%2bC%2f6HwZMBW9tLbym0imChattAj7Jmx2TMOhv2USn447vZxGqhB0%2b7M99jXhla947WK2f7vSPsNDFUxDIlZjTwqU01d7i3oPk3mMv%2fqC96E1nhbQjj8REOJRqEGTHZEiU8psD6MLx5uJNJ49DCbXVIUxjMBKnBGXlFV2oZkUxXyBOh1Ebk1Zy%2fQiiXPCOFk1JwgX9U1ooCwTphnD2QK2FwUkZabfQOcwf9HsCKalTECCk4bZ0hLoa1MBbXO6t5uDK6RuMIbXI7xW0YxJHmhdhjMrqUryeat1R4Ixr8CrP8kt96LT%2bC7s2jx8Y%2fpp5MXl5hJgKNXBjJm66vLFw1CLPvGu9jol3y6HSKmJt25WPQ7jp%2bnz0peUXZyFv4%2fQZN0nnEzfd7P4rG%2bA1VAgAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI1RS2vCQBC%2bC%2f6HwZMBW9tLbym0imChattAj7Jmx2TMOhv2USn447vZxGqhB0%2b7M99jXhla947WK2f7vSPsNDFUxDIlZjTwqU01d7i3oPk3mMv%2fqC96E1nhbQjj8REOJRqEGTHZEiU8psD6MLx5uJNJ49DCbXVIUxjMBKnBGXlFV2oZkUxXyBOh1Ebk1Zy%2fQiiXPCOFk1JwgX9U1ooCwTphnD2QK2FwUkZabfQOcwf9HsCKalTECCk4bZ0hLoa1MBbXO6t5uDK6RuMIbXI7xW0YxJHmhdhjMrqUryeat1R4Ixr8CrP8kt96LT%2bC7s2jx8Y%2fpp5MXl5hJgKNXBjJm66vLFw1CLPvGu9jol3y6HSKmJt25WPQ7jp%2bnz0peUXZyFv4%2fQZN0nnEzfd7P4rG%2bA1VAgAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1RS2vCQBC%2bC%2f6HwZMBW9tLbym0imChattAj7Jmx2TMOhv2USn447vZxGqhB0%2b7M99jXhla947WK2f7vSPsNDFUxDIlZjTwqU01d7i3oPk3mMv%2fqC96E1nhbQjj8REOJRqEGTHZEiU8psD6MLx5uJNJ49DCbXVIUxjMBKnBGXlFV2oZkUxXyBOh1Ebk1Zy%2fQiiXPCOFk1JwgX9U1ooCwTphnD2QK2FwUkZabfQOcwf9HsCKalTECCk4bZ0hLoa1MBbXO6t5uDK6RuMIbXI7xW0YxJHmhdhjMrqUryeat1R4Ixr8CrP8kt96LT%2bC7s2jx8Y%2fpp5MXl5hJgKNXBjJm66vLFw1CLPvGu9jol3y6HSKmJt25WPQ7jp%2bnz0peUXZyFv4%2fQZN0nnEzfd7P4rG%2bA1VAgAA&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
//| where Finished >= now(-60d)
| where Result == "Fail"
| where Method == "TokenCallbackInvokedOnFileChange"
| where Message startswith "Callback"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,
  Duration,
  Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```
says this is failing in this way 9 times a month.

**Comment by danmoseley** [comment]
Seems disproportionately likely to be jitstress (ie slow) and/or 32 bit. and only Windows. No strong signal of a product bug. Disabling for Windows when on jitstress or 32 bit may eliminate the problem or make it very rare.

|Pipeline|OS|Arch|count_|
|---|---|---|---|
|runtime-coreclr libraries-jitstress2-jitstressregs|windows.10.amd64.open.rt|x86|2|
|runtime|windows.10.amd64.open.rt|x86|4|
|runtime-coreclr libraries-pgo|windows.10.amd64.open.rt|x64|1|
|runtime-coreclr libraries-jitstressregs|windows.10.amd64.open.rt|x86|1|
|runtime-coreclr libraries-jitstress|windows.10.amd64.open.rt|x86|1|
