### ISSUE TITLE
Crash in clr.dll When Allocating Memory in .NET Framework 4.8

### ISSUE THREAD

**Issue by Vercidium** [dotnet/runtime#52637]
### Description

Recently after upgrading from .NET Framework 4.7.1 to 4.8, some users have reported that the program crashes on startup. I do not face these crashes on my PC, nor do most users.

I have collected crash dumps from them (with heap) and found that the program crashes at random points when allocating memory, e.g. `var x = new int[64]`.

The thrown exception is : `Unhandled exception at 0x00007FFF9EAEEFA6 (clr.dll) in sectorsedge.exe.16324.dmp: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF`.

I have attached the user’s crash dump here: [REDACTED]
I have uploaded the accompanying build of the game here: [REDACTED]

### Configuration

* Which version of .NET is the code running on? .NET Framework 4.8
* What OS and version, and what distro if applicable? Windows 10,    OS Version 10.0.19042,    CLR Version 4.8.4341.0
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? It may be, only some users face this issue

### Regression?

Reverting the game to .NET Framework 4.7.1 fixes these issues.

### Other information

The program crashes on the main thread with no other threads running.

The program always crashes at code in the [NVorbis C# Ogg Vorbis Decoder](https://github.com/NVorbis/NVorbis) project, which I have built with .NET Standard 2.0. Its only dependency is `System.Memory (PackageReference Version 4.5.4)` and this project runs without problems on my PC.

NVorbis is the only project that references System.Memory, and the `System.Memory.dll` file that I ship with the game states it has `File version 4.6.28619.1` and `Product version 4.6.28619.01`.

The full native stack trace is:

```
clr.dll!GcInfoDecoder::EnumerateLiveSlots()	Unknown
clr.dll!GcStackCrawlCallBack()	Unknown
clr.dll!GCToEEInterface::GcScanRoots()	Unknown
clr.dll!WKS::gc_heap::mark_phase()	Unknown
clr.dll!WKS::gc_heap::gc1()	Unknown
clr.dll!WKS::gc_heap::garbage_collect()	Unknown
clr.dll!WKS::GCHeap::GarbageCollectGeneration()	Unknown
clr.dll!WKS::GCHeap::Alloc()	Unknown
clr.dll!JIT_NewArr1(struct CORINFO_CLASS_STRUCT_ *,__int64)	Unknown
00007fff3fef9ab9()	Unknown
00007fff3fef98fa()	Unknown
00007fff3fef86d4()	Unknown
00007fff3fef7d8d()	Unknown
00007fff3fef7b3e()	Unknown
00007fff3fef780d()	Unknown
00007fff3fef7524()	Unknown
00007fff3fef73e3()	Unknown
00007fff3feeb16d()	Unknown
00007fff3feeabfd()	Unknown
00007fff3feeab46()	Unknown
00007fff3feea914()	Unknown
00007fff3fee9204()	Unknown
00007fff3fed2595()	Unknown
00007fff3fd8cced()	Unknown
00007fff3fd8b8af()	Unknown
00007fff3fd8afde()	Unknown
00007fff3fd8a95c()	Unknown
00007fff3fd8a815()	Unknown
00007fff3fd8a7c7()	Unknown
00007fff3fd8a744()	Unknown
00007fff3fd6c8bc()	Unknown
00007fff3f9b1b19()	Unknown
00007fff3f984441()	Unknown
clr.dll!UMThunkStub()	Unknown
user32.dll!UserCallWinProcCheckWow()	Unknown
user32.dll!DispatchMessageWorker()	Unknown
00007fff3fbdf581()	Unknown
00007fff3fd8a308()	Unknown
00007fff3fd89fdb()	Unknown
00007fff3f99eb71()	Unknown
00007fff3f99eabc()	Unknown
00007fff3f8a2983()	Unknown
00007fff3f602609()	Unknown
clr.dll!CallDescrWorkerInternal()	Unknown
clr.dll!CallDescrWorkerWithHandler()	Unknown
clr.dll!MethodDescCallSite::CallTargetWorker()	Unknown
clr.dll!RunMain()	Unknown
clr.dll!Assembly::ExecuteMainMethod()	Unknown
clr.dll!SystemDomain::ExecuteMainMethod()	Unknown
clr.dll!ExecuteEXE(struct HINSTANCE__ *)	Unknown
clr.dll!_CorExeMainInternal()	Unknown
clr.dll!_CorExeMain()	Unknown
mscoreei.dll!_CorExeMain()	Unknown
mscoree.dll!_CorExeMain_Exported()	Unknown
kernel32.dll!BaseThreadInitThunk()	Unknown
ntdll.dll!RtlUserThreadStart()	Unknown
```

**Comment by jkotas** [comment]
Could you please report this issue using VS Developer Community Portal (https://github.com/dotnet/core#getting-help)? It is the best place to report .NET Framework issues. .NET Framework issues are not actionable in this repo. 

I have noticed that the binaries that you have shared are obfluscated. Obfluscators are common source of hard to understand crashes like this one. Have you run into this crash with non-obfluscated binaries?

**Comment by Vercidium** [comment]
Thank you, I created an issue on the VS Developer Community Portal [here ](https://developercommunity.visualstudio.com/t/access-violation-when-allocating-memory-in-net-fra/1414826) but thought I should share the technical details here. No worries!
