### ISSUE TITLE
FileSystemWatcher with winforms Form as SynchronizingObject: event handlers not called on forms thread

### ISSUE THREAD

**Issue by msneijders** [dotnet/runtime#52644]
### Description
Using `FileSystemWatcher` on a Winforms `Form`, setting `SynchronizeObject` to this form and adding a Changed event handler. This handler is executed on a different thread (worker thread) than this Form was created on (main thread). According to [docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher.synchronizingobject?view=net-5.0#remarks) it should execute on the main thread?

Small test solution:

[WinFormsApp_FileSystemWatcher.zip](https://github.com/dotnet/runtime/files/6466781/WinFormsApp_FileSystemWatcher.zip)

### Configuration

.NET 5.0.6

### Regression?

It is at least a regression coming from .NET Framework 4.7.1, but I haven't tested a previous .NET Core version.

**Comment by Balkoth** [comment]
I can confirm this, as i just came across this issue and wanted to write a bug report myself. Even if `SynchronizingObject` is set to a Control on the UI-Thread and InvokeRequired is true, the event handlers are called from a different thread.

**Comment by thomsj** [comment]
I also noticed this, a couple of months ago. I've just committed my fix.
