### ISSUE TITLE
WebSockets test failures on Android

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#52645]
As per https://github.com/dotnet/runtime/pull/52052#issuecomment-838655841, creating an issue to track WebSockets test failures on Android and put them under ActiveIssue.

`ubuntu.1804.amd64.android` - x86, x64

- System.Net.WebSockets.Tests.WebSocketDeflateTests.WebSocketWithoutDeflateShouldThrowOnCompressedMessage
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: The WebSocket received compressed frame w···
Actual:   net_Websockets_PerMessageCompressedFlagWh···
          ↑ (pos 0)
```

- System.Net.WebSockets.Tests.WebSocketDeflateTests.ReceiveUncompressedMessageWhenCompressionEnabled
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: The WebSocket received compressed frame w···
Actual:   net_Websockets_PerMessageCompressedFlagWh···
          ↑ (pos 0)
```

- System.Net.WebSockets.Tests.WebSocketDeflateTests.ReceiveInvalidCompressedData
```
Assert.Equal() Failure
          ↓ (pos 0)
Expected: The message was compressed using an unsup···
Actual:   ZLibUnsupportedCompression
          ↑ (pos 0)
```

**Comment by karelz** [comment]
@steveisok can you please triage this one? (set milestone + remove 'untriaged' label) Thanks!

**Comment by steveisok** [comment]
Appears that we're not handling resources files properly.

**Comment by steveisok** [comment]
For some reason we're defaulting to true.  If I set the value to false, the tests pass.

https://github.com/dotnet/runtime/blob/24544e0cf7bd3c1085456b35de2048405afe4f18/eng/testing/tests.mobile.targets#L20

**Comment by mdh1418** [comment]
It seems like that is defaulted to true to help reduce the assembly size by trimming. I wonder if theres something specifically being trimmed out to cause it to fail. 
Based off these:
https://github.com/dotnet/runtime/commit/45143278b0dfe09f373e22af95f5f4b7c8ecb15d
https://github.com/dotnet/runtime/commit/7f491db5a211b7f460703845dae93f7eef65ffba
https://github.com/xamarin/xamarin-android/pull/5337
