### ISSUE TITLE
System.Text.Json.JsonSerializer.Serialize<T> omits generic list

### ISSUE THREAD

**Issue by HermannGruber** [dotnet/runtime#52653]
### Description

I have a data transfer object (DTO) of type (say) Master with a property of type List<Slave>. When I call System.Text.Json.JsonSerializer.Serialize<Master>(...) then the JSON thus obtained does not contain the list, although it is nonempty. I also serialized my DTO using Newtonsoft.Json.JsonConvert.SerializeObject, and this one serializes the list correctly.

For a repro, see the following repo:
https://github.com/HermannGruber/JsonSerializeRepro

When I F5 into the repro, it produces the following output on my Windows 10 machine:

JsonSerializer
{}
JsonConvert
{
  "Slaves": [
    {
      "Bar": "779-20~1234",
      "BarBar": false,
      "BarBarBar": "2021.2"
    },
    {
      "Bar": "779-20~2345",
      "BarBar": false,
      "BarBarBar": "2021.2"
    }
  ]
}

C:\1_Projects\JsonSerialize\JsonSerialize\bin\Debug\net5.0\JsonSerialize.exe (process 15440) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

My obvious workaround for now is to use the Newtonsoft implementation, but I'd prefer to use the built-in serialization of the platform.

**Comment by benaadams** [comment]
The List is a field rather than a property which System.Text.Json doesn't serialize by default.

You can either change it to a property `{ get; set; }` or add `IncludeFields = true` to your `JsonSerializerOptions`

**Comment by HermannGruber** [comment]
Ugh - that's what I had overlooked for hours. I will change it to a property, and this resolves the issue. Thank you very much!
