### ISSUE TITLE
HttpClient: Consider removing MailAddressParser

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#52664]
This parser is used for the From header, which is an uncommon HTTP header.

This class contains a lot of complicated logic, and contributes in a nontrivial way to Blazor assembly size. See discussion here: https://github.com/dotnet/runtime/issues/44534#issuecomment-814932326

Unlike most parsers, this parser does not produce a strongly-typed value -- it just validates the mail address and returns it as a string. 

We should consider just removing this entirely. This would help Blazor assembly size, and keep consistency between full framework and Blazor. 

The impact of removing this would be that From header values that were previously considered invalid, and thus were either discarded or caused exceptions, would now be considered valid. Given that the From header is not commonly used, and only error cases are affected, I don't think this is a problem.

**Comment by KevinCathcart** [comment]
I am very skeptical that this has *ever* provided meaningful value. That header is both rare, and so completely unimportant, that even when the header is supplied this validation is probably just pointlessly wasting CPU cycles. 

Sure, it could theoretically catch a bug in a crawler that sends a malformed address, but does anyone really care? The only thing I can realistically see any server bothering to do with that header is log it. I'd wager most server implementations make no effort to validate it, and in the unlikely event a server cared enough to validate, the user of the client would see the "400 Bad Request" error that said server should return for header validation failure, and the body of the response *should* explain what it objected to. That is the same sort of error they would get for any server side parsing error of an obscure or custom header HttpClient does not know about.

And if the server was returning that header, it is even less important to validate it as that is so non-standard that no client is even going to bother checking for it, much less use it for anything.

**Comment by geoffkizer** [comment]
@dotnet/ncl Any objections?

**Comment by wfurt** [comment]
no. I do agree that the parsing has little value.

**Comment by kasperk81** [comment]
While I agree with previous comments, but removing the public MailAddress class straight up as part of this cleanup work without going through [obsoletion](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/better-obsoletion.md) first is not a good idea. I suggest to bring back MailAddress and keep the scope of this change to "removal of From header validation".

**Comment by KevinCathcart** [comment]
The public class named MailAddress lives in a different assembly (System.Net.Mail), and was not deleted. Only an internal stub version of the same class was deleted. That stub version was needed because the actual parser was shared source (and is still used in System.Net.Mail) and depended on there being a class with that name.
