### ISSUE TITLE
Updated runtime-deps installer needed for Fedora 34

### ISSUE THREAD

**Issue by leecow** [dotnet/runtime#52667]
Fedora 34 no longer requires compat-openssl10 to build and run .NET applications. An updated runtime-deps is needed to reflect this. 

/cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
[Triage] @crummel do you know which .NET versions are supported with Fedora-built packages?

**Comment by NikolaMilosavljevic** [comment]
PR for 6.0 is available: https://github.com/dotnet/runtime/pull/52674

Working on 5.0 and 3.1 changes.
