### ISSUE TITLE
GC seem not work in some case

### ISSUE THREAD

**Issue by mslichao** [dotnet/runtime#52676]
### Description

I have 2 code snippet:

First:
```
        static void Main()
        {
            // for (int i = 0; i < 0; i++) { }
            WeakReference weakReference = new WeakReference(new MemoryStream());
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Console.WriteLine(weakReference.IsAlive);
        }
```

Second:
```
        static void Main()
        {
            for (int i = 0; i < 0; i++) { }
            WeakReference weakReference = new WeakReference(new MemoryStream());
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Console.WriteLine(weakReference.IsAlive);
        }
```

The different of these 2 code snippets is whether have the empty for-loop at the beginning.
The output of first is True, which means the MemoryStream object still there, but for second, the output is False, which means the MemoryStream object is released.

Is this a bug? And how to explain this different?

I expected the MemoryStream can be released, is there any method to do this operation?

PS: I run them both in Release mode.

### Configuration

Both Net 5.0 and NetCore 3.1

### Regression?

No

### Other information

N/A

**Comment by GrabYourPitchforks** [comment]
@dotnet/jit-contrib Can this behavior be explained by tiered JIT? I recall some earlier discussion around tiering behaving differently when loops are present in the method. Otherwise please repath to GC or elsewhere as appropriate.

**Comment by davidfowl** [comment]
Things are probably rooted by the stack, not the weak reference.

**Comment by AndyAyersMS** [comment]
>  Can this behavior be explained by tiered JIT?

Yes. The first version will be jitted at Tier0, which is less aggressive about "retiring" GC references. The second version has a loop and so by default will bypass Tier0, and so be optimized, and so has more aggressive retiring of GC refs.

The only reliable way to ensure that there are no references to newed-up objects in a method is to return from the method.

So this behavior is by design.

**Comment by mslichao** [comment]
> > Can this behavior be explained by tiered JIT?
> 
> Yes. The first version will be jitted at Tier0, which is less aggressive about "retiring" GC references. The second version has a loop and so by default will bypass Tier0, and so be optimized, and so has more aggressive retiring of GC refs.
> 
> The only reliable way to ensure that there are no references to newed-up objects in a method is to return from the method.
> 
> So this behavior is by design.

This works, thanks very much.
