### ISSUE TITLE
Publishing for ARM target run time

### ISSUE THREAD

**Issue by kalijana** [dotnet/runtime#52692]
have a armv5 custom SOC and trying to publish linux-arm  with self contained and single file options .( from windows 10 system)

 But unable to run the application . OS is Debian GNU linux

**Comment by vitek-karas** [comment]
Could you please provide a bit more info:
* "Unable to run the app" - what does this mean? How does it fail?
* What version of .NET are you using?
* Does it work if you try it non-single-file?
* What version of the OS?

**Comment by jkotas** [comment]
> a armv5 custom SOC

.NET needs armv7

**Comment by kalijana** [comment]
.net version 3.1 
.debian gnu 3.1 as well 
issue is the executable does not get recognized

**Comment by kalijana** [comment]
processor       : ARM926EJ-S rev 0 (v5l)
CPU architecture: 5TEJ

**Comment by kalijana** [comment]
so does that mean that for this ARM SOC i cant do a cross compile ?

**Comment by jkotas** [comment]
It would not work even if you compiled natively. This SOC is ARM v5, but .NET needs ARM v7.

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/7764
