### ISSUE TITLE
TypeDescriptor.GetProperties should not have nullable items

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#527]
**Version Used**: 
VS 16.4, .Net Core 3.1

**Steps to Reproduce**:

```csharp
var allProperties =
    TypeDescriptor.GetProperties(typeof(T));

var pds = new List<PropertyDescriptor>();

foreach (PropertyDescriptor prop in allProperties)
{
}
```

**Expected Behavior**:
No warnings

**Actual Behavior**:
CS8606 // Possible null reference assignment to iteration variable

-------------------

How can any PropertyDescriptor be `null`?

**Comment by ericstj** [comment]
We haven't annotated TypeConverter assembly yet.  See https://github.com/dotnet/runtime/issues/2339
