### ISSUE TITLE
Make SortedList<TKey,TValue> API consistent 

### ISSUE THREAD

**Issue by TechnologicalPizza** [dotnet/runtime#52702]
## Background and Motivation

`SortedList<TKey, TValue>` exposes an inconsistent enumeration API compared to other types in `System.Collections.Generic`. This makes access slower and creates needless allocations due to boxing.
This change would better expose the internal code and would not need any new logic as all of this already exists internally.

## Proposed API

```diff
namespace System.Collections.Generic
{
    public class SortedList<TKey, TValue> : ICollection<KeyValuePair<TKey, TValue>>, IEnumerable<KeyValuePair<TKey, TValue>>, IEnumerable, IDictionary<TKey, TValue>, IReadOnlyCollection<KeyValuePair<TKey, TValue>>, IReadOnlyDictionary<TKey, TValue>, ICollection, IDictionary where TKey : notnull
    {
-       public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator();
+       public SortedList<TKey, TValue>.KeyList.Enumerator GetEnumerator();
+       IEnumerator<TKey> IEnumerable<TKey>.GetEnumerator();

-       private struct Enumerator : IEnumerator<KeyValuePair<TKey, TValue>>, IDictionaryEnumerator
+       public struct Enumerator : IEnumerator<KeyValuePair<TKey, TValue>>, IDictionaryEnumerator
        {
        }

-       private sealed class KeyList : IList<Key>, ICollection
+       public sealed class KeyList : IList<Key>, ICollection
        {
-           public IEnumerator<TKey> GetEnumerator();
+           public SortedList<TKey, TValue>.KeyList.Enumerator GetEnumerator();
+           IEnumerator<TKey> IEnumerable<TKey>.GetEnumerator();
        }
		
-       private sealed class ValueList : IList<TValue>, ICollection
+       public sealed class ValueList : IList<TValue>, ICollection
        {
-           public IEnumerator<TValue> GetEnumerator();
+           public SortedList<TKey, TValue>.ValueList.Enumerator GetEnumerator();
+           IEnumerator<TValue> IEnumerable<TValue>.GetEnumerator();
        }
    }
}
```

## Usage Examples

The usage remains the same. This is merely a simple performance and consistency improvement.

## Alternative Designs

Most types in `System.Collections.Generic` use struct enumerators to allow for allocationless iteration. 
If we take `SortedDictionary<TKey, Value>` as an example (which has a similar API to `SortedList<TKey, TValue>`), it exposes sealed `KeyList` and `ValueList` types as well as struct enumerators, which all combined allow for allocationless iteration over keys, values, or pairs of both.

## Risks

This should realistically not be a breaking change in most scenarios. Performance should only improve due to use of sealed types and struct enumerators. The underlying code/behavior would actually not change because the only thing that changes is how we expose the enumerators (the code already exists).

**Comment by jkotas** [comment]
Changing `public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator();` to `public SortedList<TKey, TValue>.KeyList.Enumerator GetEnumerator();` would be unacceptable breaking change.

**Comment by TechnologicalPizza** [comment]
So for example, referencing a netstandard2.0 project from a version with this change would break? Is that what you're referring to?

**Comment by jkotas** [comment]
Correct.

**Comment by TechnologicalPizza** [comment]
So we could realistically make KeyList, ValueList and Enumerator public, and give them public constructors that take a `SortedList<TKey, TValue>`, right?

**Comment by jkotas** [comment]
It would be unusual pattern for collections, but yes that would be possible.

**Comment by eiriktsarpalis** [comment]
> So we could realistically make KeyList, ValueList and Enumerator public, and give them public constructors that take a SortedList<TKey, TValue>, right?

I think there are very clear ergonomic and discoverability issues with such an approach, so it's unlikely it would benefit most users. It also remains to be seen what the performance benefits of such an addition might be.

I'd therefore be inclined to close this, unfortunately the best solution also happens to be a binary breaking change.
