### ISSUE TITLE
[wasm] `mono-aot-cross` broken on OSX due to `System.Threading.AutoreleasePool not found`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#52718]
This seems to have broken with https://github.com/dotnet/runtime/commit/60735c6d3f61ea93b903fd36e1656b8c2bbb4a96

```
NSAutoreleasePool instance should be added to all threads. (#52023)
Add an NSAutoreleasePool to all managed create threads including the Main and Finalizer.

This expands the current support where support was only added to ThreadPool threads. 

New feature switch was created and the ThreadPool one was removed.
 - System.Threading.Thread.EnableAutoreleasePool

Updated AutoReleaseTest for the new scenarios.
```

Steps to reproduce:

`make -C src/mono/sample/wasm/console AOT=1 MSBUILD_ARGS="/fl /flp:v=diag /v:n"`

.. fails with:
```
  Wasm.Console.Sample -> /Users/radical/dev/r4/src/mono/sample/wasm/console/bin/browser-wasm/publish/
  AOT'ing 7 assemblies
  Exit code: 134
/Users/radical/dev/r4/src/mono/wasm/build/WasmApp.targets(145,5): error : Precompiling failed for /Users/radical/dev/r4/src/mono/sample/wasm/console/bin/browser-wasm/publish/System.Console.dll: Error: Process returned non-zero exit code:  [/Users/radical/dev/r4/src/mono/sample/wasm/console/Wasm.Console.Sample.csproj]
```

Looking at the `msbuild.log`, `mono-aot-cross` is failing with:

```
Runtime critical type System.Threading.AutoreleasePool not found
```

**Comment by radical** [comment]
cc @AaronRobinsonMSFT @vargaz

**Comment by AaronRobinsonMSFT** [comment]
@radical Sorry about this. The failing code is at

https://github.com/dotnet/runtime/blob/d77854a16eaa29f1a141f1da267885dcf2675027/src/mono/mono/metadata/domain.c#L368-L373

Unsure how we need to deal with this. @marek-safar or @lambdageek can you offer a suggestion here?

**Comment by lambdageek** [comment]
Can either change the load method to "try load from name" and then deal with NULL at the autoreleasepool callsites, or add a `&& !defined(MONO_CROSS_COMPILING)` to the ifdef (that might be the wrong name - sorry I'm on a phone)

**Comment by lambdageek** [comment]
"try load from" and check at callsites is probably better. @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@lambdageek Thanks. You've given me more than enough to try and investigate.

**Comment by AaronRobinsonMSFT** [comment]
@vargaz I see your change and it is partially complete. We should also check and branch here:

https://github.com/dotnet/runtime/blob/3659af935e2912fcaefb6b3964116c8722c334c2/src/mono/mono/metadata/threads.c#L3928-L3948
