### ISSUE TITLE
.NET 5.0.6 (5.0.203 SDK) coreclr.dll symbols unavailable

### ISSUE THREAD

**Issue by Decimation** [dotnet/runtime#52717]
The .NET 5.0.6 (5.0.203 SDK) `coreclr.dll` doesn't have its symbol file `coreclr.pdb` available on the Microsoft Symbol Server.

Using `symchk` fails:

`symchk.exe .\coreclr.dll /s SRV*output*http://msdl.microsoft.com/download/symbols`

```
SYMCHK: coreclr.dll          FAILED  - coreclr.pdb mismatched or not found

SYMCHK: FAILED files = 1
SYMCHK: PASSED + IGNORED files = 0
```

I also tried using WinDbg to access the symbol file but it was also unable to retrieve it from the Symbol Server.

**Comment by hoyosjs** [comment]
@rbhanda can you please check that the release pipeline properly ran the publish to MSDL steps?

**Comment by rbhanda** [comment]
Hi @hoyosjs I am looking and re-running the publishing step

**Comment by hoyosjs** [comment]
Thanks for the report @Decimation, I've verified that I can properly read the symbols from MSDL now.
