### ISSUE TITLE
HttpWebRequest failed with 401 Error

### ISSUE THREAD

**Issue by ircaxn** [dotnet/runtime#52723]
We have our application configured to run on .NET Core 2.2. In our application, we are making a HttpWebRequest to one of our service and passing the credential as NetworkCredential. The web request is working fine and we are able to get the proper response from our service when the passing username doesn't have any special characters in there.

In case of the username is having a special character '@' , then the web request is getting failed with 401 status error code.

I tried the same application and code to run under .Net Framework 4.8 and .Net Core 3.1 and in both cases the web request is working fine even passing the username with special characters. I copied the execution code below of how i am making a httpwebrequest.

Is there any known issue with .Net Core 2.2 on making HttpWebRequests and passing NetworkCredentials() which has special characters in it and whether is it resolved with any specific versions?

```c#
            Uri l_Uri = new Uri("http://myservice/search/config");
            string l_UserId = "Vcjt@2a";
            string l_Password = "KL@420kdg";

            WebResponse l_WebResponse = null;
            HttpWebRequest l_WebRequest = (HttpWebRequest)HttpWebRequest.Create(l_Uri);

            if (l_WebRequest != null)
            {
                l_WebRequest.ContentType = "application/json";
                l_WebRequest.Method = "GET";
                l_WebRequest.Credentials = new NetworkCredential(l_UserId, l_Password);
                
                string l_ReadValue = null;
                StreamReader inputStream = null;

                try
                {
                    l_WebResponse = l_WebRequest.GetResponse();
                    inputStream = new StreamReader(l_WebResponse.GetResponseStream());
                    l_ReadValue = inputStream.ReadToEnd().Trim();
                }
                catch (WebException we)
                {
                    HttpWebResponse l_HttpResponse = (HttpWebResponse)we.Response;
                    if (l_HttpResponse != null && l_HttpResponse.StatusCode == HttpStatusCode.Forbidden)
                    {
                        l_IsValidAccount = false;
                    }
                }
                catch (Exception e)
                {
                    l_IsValidAccount = false;

                }
                finally
                {
                    if (inputStream != null) inputStream.Dispose();
                    if (l_WebResponse != null) l_WebResponse.Close();
                }
            }//else do nothing
```

**Comment by karelz** [comment]
@ircaxn based on your description, it seems that it works fine for you on .NET Core 3.1 -- doesn't that answer your question "_whether is it resolved with any specific versions_", or am I missing some nuance here?

Given that .NET Core 2.2 is unsupported and .NET Core 2.1 [ends support in couple of months](https://github.com/dotnet/core/blob/main/releases.md#supported-net-versions), it does not seem to be valuable to find out why .NET Core 2.2 or 2.1 is not working well.

Also note that `HttpWebRequest` is [obsoleted](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest?view=net-5.0#remarks) - it has suboptimal performance and has feature gaps (compared to .NET Framework) on .NET Core 2.0+ and .NET 5+ -- we recommend to use `HttpClient` instead.

**Comment by ircaxn** [comment]
@karelz Thank you for your response.

I meant that is there any possible fixes on .NET Core 2.2 on this issue, but as mentioned it is unsupported now and there is no choice and we need to migrate to .NET Core 3.1.

Once again thanks for your response and am satisfied with that.
