### ISSUE TITLE
Implement an analyzer to detect usage of RequiresPreviewFeaturesAttribute

### ISSUE THREAD

**Issue by pgovind** [dotnet/runtime#52726]
https://github.com/dotnet/designs/blob/main/accepted/2021/preview-features/preview-features.md#api-analyzer introduces the `RequiresPreviewFeatures` attribute. With https://github.com/dotnet/runtime/pull/52419, the attribute is now live in dotnet/runtime. We need to implement an analyzer to track the usage of the `RequiresPreviewFeaturesAttribute`.

Attribute definition for reference
``` csharp
namespace System.Runtime.Versioning
{
    [AttributeUsage(AttributeTargets.Assembly |
                    AttributeTargets.Module |
                    AttributeTargets.Class |
                    AttributeTargets.Interface |
                    AttributeTargets.Delegate |
                    AttributeTargets.Struct |
                    AttributeTargets.Enum |
                    AttributeTargets.Constructor |
                    AttributeTargets.Method |
                    AttributeTargets.Property |
                    AttributeTargets.Field |
                    AttributeTargets.Event, AllowMultiple = true, Inherited = false)]
    public sealed class RequiresPreviewFeaturesAttribute : Attribute
    {
        public RequiresPreviewFeaturesAttribute();
    }
}
```

This attribute can target many language constructs, so the analyzer performance has to be considered carefully during implementation. Some prior art exists here with the PlatformCompatAnalyzer.

This post will be updated shortly with the test matrix for the analyzer implementation.

cc @tannergooding @terrajobst @jeffhandley @mavasani

**Comment by pgovind** [comment]
I'm guessing it's ok in this instance to add the `ApprovedRule` label to the issue?

**Comment by carlossanlop** [comment]
Fixed by https://github.com/dotnet/roslyn-analyzers/pull/5155
