### ISSUE TITLE
AddHostedService just work for first instance

### ISSUE THREAD

**Issue by ahdung** [dotnet/runtime#52747]
asp.net core 5.0 project.

My app read urls from appsettings.json, and access them intermittently, so I wrote a `TimerCheckJob` class:
```c#
class TimerCheckJob : IHostedService {
    public TimerCheckJob(string url) {} // accept url arg
    ...
}
```
and `AddHostedService` them:
```c#
foreach (var url in urls) {
    services.AddHostedService(_=>new TimerCheckJob(url));
}
```
But just first instance of `TimerCheckJob` work, please tell me why and how? thank you.

**Comment by davidfowl** [comment]
See https://github.com/dotnet/runtime/issues/38751

**Comment by ahdung** [comment]
got it, change to:
```c#
foreach (var url in urls) {
    services.AddSingleton<IHostedService>(_=>new TimerCheckJob(url));
}
```
Can’t believe you professional guys are thinking such simple, why can't add multiple instances??? jesus.

**Comment by maryamariyan** [comment]
closing as dupe
