### ISSUE TITLE
[QUIC]: ListenerStart sometimes fails with INVALID_STATE

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#52742]
I get this while running QUIC tests in loop on Linux:

```
Starting round 47
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 6.0.0-dev)
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 62 of 96 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
      System.Net.Quic.QuicException : ListenerStart failed. 127.0.0.1:0 Error Code: INVALID_STATE
      Stack Trace:
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/QuicExceptionHelpers.cs(12,0): at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicListener.cs(138,0): at System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(QuicListenerOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicListener.cs(67,0): at System.Net.Quic.Implementations.MsQuic.MsQuicListener..ctor(QuicListenerOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicImplementationProvider.cs(14,0): at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateListener(QuicListenerOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs(43,0): at System.Net.Quic.QuicListener..ctor(QuicImplementationProvider implementationProvider, QuicListenerOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs(36,0): at System.Net.Quic.QuicListener..ctor(QuicImplementationProvider implementationProvider, IPEndPoint listenEndPoint, SslServerAuthenticationOptions sslServerAuthenticationOptions)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(63,0): at System.Net.Quic.Tests.QuicTestBase`1.CreateQuicListener(IPEndPoint endpoint)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(58,0): at System.Net.Quic.Tests.QuicTestBase`1.CreateQuicListener()
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(68,0): at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(357,0): at System.Net.Quic.Tests.QuicStreamTests`1.ReadWrite_Random_Success(Int32 readSize, Int32 writeSize)
        --- End of stack trace from previous location ---
  Finished:    System.Net.Quic.Functional.Tests
```

I did little bit of digging and the failure is coming from msquic

https://github.com/microsoft/msquic/blob/26cff1a8de7890cf7ff77709ee14b51bc84e330e/src/core/listener.c#L284-L293

I can reproduced it in 50-100 runs.  At this point I don't have evidence that we pass in invalid data. 
It is certainly possible that there are multiple tests trying to bind to the same address, but since the port is 0, I would assume some port will get assigned by OS. 

cc: @nibanks @ThadHouse

**Comment by ThadHouse** [comment]
Do you have etl logs. Theres a few things in that path that can result in INVALID_STATE, so it might not exactly be that one. Logs should help us figure out which one is actually getting hit. CLOG should work on linux to be able to get logs.

**Comment by wfurt** [comment]
I will try to collect them today. Do you want the raw lltng logs or the converted one? 
https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md

**Comment by ThadHouse** [comment]
The converted ones please.

**Comment by wfurt** [comment]
Here is the log file @ThadHouse ~5G
https://microsoft-my.sharepoint.com/:u:/p/toweinfu/EfZ-SobH5B5Dk1MtPj72CSkB9aWqELrGN9qyP5eFFxGUvg?e=ju2lUV

**Comment by nibanks** [comment]
```
[1][2e73.2e8b][09:54:03.528362][ api] Enter 10 (0x7f30ac0dcff0).
[1][2e73.2e8b][09:54:03.528902][bind][0x7f30b80394e0] Listener (0x7f30ac076d90) already registered on ALPN
[1][2e73.2e8b][09:54:03.528903][list][0x7f30ac0dcff0] ERROR, "Register with binding".
[1][2e73.2e8b][09:54:03.528913][ api] Exit 200000002
```
Seems you have some other listener already running (perhaps in the process of cleaning up) on the binding (socket).

**Comment by nibanks** [comment]
Just looked for `7f30ac076d90` in the logs and it seems like it's not a race. The listener that is already registered was started a long time ago and keeps running for quite some time afterwards.

**Comment by wfurt** [comment]
Since we are binding on port 0, it should create new one, right @nibanks ?

**Comment by nibanks** [comment]
FYI, I just put together this trouble shooting guide PR (https://github.com/microsoft/msquic/pull/1620) to explain the steps clearly so that anyone else can do the same diagnostics themselves.

**Comment by nibanks** [comment]
> Since we are binding on port 0, it should create new one, right @nibanks ?

This collision can only happen if the new listener is trying to bind to exactly the same local, non-zero port. Are you positive you are passing down `0` for the port? If so, the only way I could see a collision then is that the networking stack is assigning us an already used ephemeral port. The relevant logic is in `QuicLibraryGetBinding` but essentially it does this for every binding:

```
QuicLibraryGetBinding(localAddr, remoteAddr = null)
  lock()
  binding = QuicLibraryLookupBinding(localAddr, remoteAddr) // Always fails with localAddr.port == 0
  unlock()
  if (binding) return binding

  newBinding = QuicBindingInitialize(localAddr, remoteAddr)
  newLocalAddr = binding.LocalAddr()

  lock()
  binding = QuicLibraryLookupBinding(newLocalAddr, remoteAddr)
  if (!binding) AddBindingToLookup(newBinding); 
  else newBinding = binding
  unlock()

  return newBinding
```
So the key take away here is that if the new binding created via `QuicBindingInitialize` ends up returning a binding that matches an existing one, then we will end up using that existing one, which already has another listener registered possibly.

So the big question is why would the stack be returning the same port for a socket that's already used?

**Comment by wfurt** [comment]
I can add more debug around ports. Generally all the test would pass in "127.0.0.1:0" and then expect port to be allocated. Do you see from the logs what port was assigned to the "old" listener?

**Comment by nibanks** [comment]
> I can add more debug around ports. Generally all the test would pass in "127.0.0.1:0" and then expect port to be allocated. Do you see from the logs what port was assigned to the "old" listener?

I'll take a look.

**Comment by nibanks** [comment]
Ok, so it definitely looks like the stack assigned us the same port. Here's where the original listener was created:
```
[1][2e73.2e8c][09:53:43.971759][list][0x7f30ac076d90] Created, Registration=0x55ab78aaa970
[1][2e73.2e8c][09:53:43.971776][data][0x7f30ac0bb850] Created, local=[::]:0, remote=None
[1][2e73.2e8c][09:53:43.971847][bind][0x7f30b80394e0] Created, Udp=0x7f30ac0bb850 LocalAddr=[::]:45510 RemoteAddr=*:0
```
And here's where the new listener is created:
```
[1][2e73.2e8b][09:54:03.528370][data][0x7f30a01ebba0] Created, local=[::]:0, remote=None
[1][2e73.2e8b][09:54:03.528857][bind][0x7f30ac0054d0] Created, Udp=0x7f30a01ebba0 LocalAddr=[::]:45510 RemoteAddr=*:0
[1][2e73.2e8b][09:54:03.528858][bind][0x7f30ac0054d0] Cleaning up
[1][2e73.2e8b][09:54:03.528858][data][0x7f30a01ebba0] Destroyed
[1][2e73.2e8b][09:54:03.528901][bind][0x7f30ac0054d0] Destroyed
[1][2e73.2e8b][09:54:03.528902][bind][0x7f30b80394e0] Listener (0x7f30ac076d90) already registered on ALPN
```
As you can see, it is binding to a wildcard port initially, and eventually gets assigned `45510` which was already assigned to us above. So we end up cleaning up that binding and just reusing the one we already had that matched.

I have no idea why Linux would do this. AFAIK, Windows never will reuse a UDP port when assigning a new ephemeral port to a socket.

**Comment by ThadHouse** [comment]
We've seen linux do this before. Since we use Reuseport to enable RSS, that also seems to allow wildcard ports to grab an existing socket with reuseport. We had this issue on client side before and can solve it there, but hadn't ran into this on the server side, and without knowledge into the Linux kernel itself it's likely harder to solve.

**Comment by wfurt** [comment]
I think in practice, most services will run on specific port. So in a way this is mostly specific to the test setup.

cc: @tmds for any additional thoughts.

**Comment by wfurt** [comment]
also if there is explicit flag for the reuse, we can use it for the test runs.

**Comment by ThadHouse** [comment]
There's no user configurable way to disable the use of SO_REUSEPORT.

**Comment by wfurt** [comment]
yes, I was thinking about possibly adding way to disable SO_REUSEPORT explicitly instead of turning it to internal "magic". I think both options you suggested would be viable for the test runs @ThadHouse

**Comment by nibanks** [comment]
BTW, for our test code, we explicitly use a semi-random local port at the app layer and if binding fails, we just trying Port+1, in a loop.

**Comment by wfurt** [comment]
ok. I'll check with the team. I'm glad we understand what is going.

**Comment by nibanks** [comment]
FYI, I've created https://github.com/microsoft/msquic/pull/1621 to detect this scenario, improve the logging and change the error code to `QUIC_STATUS_INTERNAL_ERROR` if this happens.

**Comment by wfurt** [comment]
I'm running loop test again with that change @nibanks 
I bump to similar put probably separate issue:
```
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
      System.Net.Quic.QuicException : ConfigurationOpen failed. Error Code: INVALID_PARAMETER
      Stack Trace:
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/QuicExceptionHelpers.cs(12,0): at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs(117,0): at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, List`1 alpnProtocols)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs(34,0): at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicClientConnectionOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs(111,0): at System.Net.Quic.Implementations.MsQuic.MsQuicConnection..ctor(QuicClientConnectionOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicImplementationProvider.cs(19,0): at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateConnection(QuicClientConnectionOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(44,0): at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, QuicClientConnectionOptions options)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(37,0): at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, EndPoint remoteEndPoint, SslClientAuthenticationOptions sslClientAuthenticationOptions, IPEndPoint localEndPoint)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(53,0): at System.Net.Quic.Tests.QuicTestBase`1.CreateQuicConnection(IPEndPoint endpoint)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(90,0): at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass16_0.<<RunClientServer>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(82,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs(78,0): at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout)
        /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs(22,0): at System.Net.Quic.Tests.QuicStreamTests`1.BasicTest()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Quic.Functional.Tests
```

I'll try to use the updated guide to get some insight.

**Comment by tmds** [comment]
From the discussion it looks like `SO_REUSEPORT` causes Linux to allow multiple sockets to have the same ephemeral port.
I wasn't aware.

`msquic` shouldn't use `SO_REUSEPORT` then when configured for an ephemeral port (port: `0`).
Otherwise, other `msquic` users can still run into this issue.

**Comment by geoffkizer** [comment]
I think we do something in our Socket code to deal with this issue. @wfurt @tmds do you folks know?

**Comment by wfurt** [comment]
Should be fixed by https://github.com/microsoft/msquic/pull/1751
I did not see this for long time so closing for now.
