### ISSUE TITLE
.pdb file is not being produced in case of full facades.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#52743]
I was playing with System.Diagnostics.Eventlog when i discovered we are missing the pdb file for net461 ref build.

On further debugging it looks like genfacades task is not generating the new pdb. https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.GenFacades/ILRewriter/GenFacades.cs#L133

I checked the packages, and they contain the pdb file. 

@ericstj can you shed some light on this ? not sure where packages are getting the pdb. 

cc @ViktorHofer @safern

**Comment by ericstj** [comment]
> @ericstj can you shed some light on this ? not sure where packages are getting the pdb.

Did you build the package and inspect the nuspec?

**Comment by ericstj** [comment]
https://gist.github.com/ericstj/32ee8319728c79a0920a1b8369959834#file-system-diagnostics-eventlog-nuspec-L50-L51
I don't see a PDB.  I think we've never had it.  

There are other reasons we want to remove that re-writing behavior in GenFacades, add this to the list.

**Comment by Anipik** [comment]
> Did you build the package and inspect the nuspec?

it has the correct output path for the pdb.

**Comment by ViktorHofer** [comment]
@ericstj should this be fixed by https://github.com/dotnet/runtime/commit/c0a17340942cd9120c6eb7ac7dd59cc6904936dc?

**Comment by ericstj** [comment]
Yes it should, since we've removed the use case that would hit that.
