### ISSUE TITLE
[iOS] DSA API surface on iOS

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#52758]
Ref: https://github.com/dotnet/runtime/pull/51926#discussion_r621639268, https://github.com/dotnet/runtime/pull/52755#issuecomment-841180329

Currently `System.Security.Cryptography.DSA.Create` returns a useless object on iOS. The object doesn't implement key generation, signing or verification since none of them are supported at the OS level. This is obviously not ideal because it may falsely lead someone to believe that the `DSA` works under some circumstances and it increases the binary size.

There are two way to deal with it:
- Leave it as is and annotate the APIs with appropriate attributes to give people compile-time warnings from the platform analyzer.
- Remove `DSASecurityTransforms` on iOS completely and make `DSA.Create` itself throw `PlatformNotSupportedException`. This has some collateral damage where `CryptoConfig` needs to be modified not to return any `DSA` types to avoid breaking assumptions elsewhere in the code.

Preferably this should be decided and cleaned up before putting any more annotations in the S.S.C.Algorithms code and before specific DSA-related tests are disabled.

**Comment by steveisok** [comment]
I think PNSE on `DSA.Create` seems like the cleaner approach if it's possible to pull off.

**Comment by filipnavara** [comment]
It's definitely possible. At some point I had a branch with it but I decided not to pursue it as part of the bring-up PR because it would be hard to read along with the other changes.

**Comment by filipnavara** [comment]
I'll revive the branch once my other iOS PRs are merged, it would only create conflicts now.

**Comment by bartonjs** [comment]
> I think PNSE on DSA.Create seems like the cleaner approach if it's possible to pull off.

I agree.  There may be some annoying collateral, but it's probably OK.

```C#
private AsymmetricAlgorithm LoadAnything(ReadOnlySpan<byte> data)
{
    RSA rsa = RSA.Create();
    DSA dsa = DSA.Create();
    ECDsa ecdsa = ECDsa.Create();

    try
    {
        rsa.ImportRSAPrivateKey(data, out _);
        return rsa;
    }

// repeat for all file formats of all types
}
```

This kind of thing would need to structure the code to not call DSA.Create too early (and to check for it failing).  But it'll be pretty rare, I think, and the platform squiggler will warn them if they say iOS is in scope.

**Comment by filipnavara** [comment]
The change is quite small: https://github.com/dotnet/runtime/compare/main...filipnavara:dsa-ios?expand=1 ... it can be cleaned up a bit once #52191 is merged to remove DSASecurityTransforms.iOS.cs completely.
