### ISSUE TITLE
[.NET Core 3.1] How to print to a Windows identity-authenticated network printer on Linux?

### ISSUE THREAD

**Issue by apetrut** [dotnet/runtime#52761]
Hi,

The app is built in .NET Core 3.1 and running inside a Linux container.
I am trying to print to a network printer located at a specific IP address using impersonated Windows identity.

I followed [this ](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.runimpersonated?view=netframework-4.8#System_Security_Principal_WindowsIdentity_RunImpersonated_Microsoft_Win32_SafeHandles_SafeAccessTokenHandle_System_Action_) tutorial to provide User impersonation, but it throws this error:

REF ID: 4cd2b50f-d511-4d32-9855-463a0328186b] - System.MissingMethodException: .ctor
   at MyService.LogonUser(String lpszUsername, String lpszDomain, String lpszPassword, Int32 dwLogonType, Int32 dwLogonProvider, SafeAccessTokenHandle& phToken)

The tutorial states that this code is supported in .NET Core 3.1, hence I would expect for it to work. 
Maybe there is something that I'm missing?

Thanks,
Andrei

**Comment by teo-tsirpanis** [comment]
Inside a _Linux_ container? Is that function even supported on Linux?

In .NET 5 and 6, the `System.Security.Principal.Windows` assembly has a `[assembly: SupportedOSPlatform("windows")]`, meaning it's Windows-only. And [the .NET Core 3.1 sources of the `WindowsIdentity` class](https://github.com/dotnet/corefx/blob/release/3.1/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsIdentity.cs) are full of Windows API calls.

If you were on .NET 5+ you would most probably get a platform compatibility analyzer warning that this function is not supported on Linux. And I guess the `Impersonate` method's documentation assumed that it's obvious that impersonation makes sense on Windows only.

**Comment by apetrut** [comment]
@teo-tsirpanis Ok, what would be a solution to this issue? In order to print to a network printer, I need a mechanism to pass the domain, username and password.

Otherwise I would get these errors:

System.Drawing.Printing.InvalidPrinterException: Settings to access printer '\\My_IP\Printer_Name' are not valid.
 at System.Drawing.Printing.PageSettings.get_PaperSize()
   at System.Drawing.Printing.PrintingServices.CreateGraphicsContext(PrinterSettings settings, PageSettings default_page_settings)
   at System.Drawing.Printing.StandardPrintController.OnStartPrint(PrintDocument document, PrintEventArgs e)
   at System.Drawing.Printing.PrintDocument.Print()

and
 System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Drawing.Printing.PrintingServices.EndDoc(GraphicsPrinter gr)
   at System.Drawing.Printing.StandardPrintController.OnEndPrint(PrintDocument document, PrintEventArgs e)
   at DevExpress.XtraPrinting.PrintingSystemBase.PrintDocument(PrintDocument pd)<---

**Comment by teo-tsirpanis** [comment]
@apetrut I would suggest you to change the issue to something like "How to print to a Windows identity-authenticated printer on Linux?".

My intuition says that the answer is "You can't, Linux has no concept of Windows Identity", but let's wait a .NET team member to respond. I am not familiar with the `System.Drawing` namespace and the extent of its cross-platform features.

**Comment by joshudson** [comment]
For some reason I expect the answer to start with "Step 1, install winbind". The API probably exists for .NET Core to tie into if it really wants, but the setup is going to be way nontrivial.

**Comment by wfurt** [comment]
.NET depends on underlying Linux printing. I think you will need to figure out how to print on your printer from your container first @apetrut.
And yes, impresonification is Windows concept and there is way on Unix how particular function can run as different user.

**Comment by apetrut** [comment]
@wfurt , this is exactly what I am trying to figure out, if there is a way on Unix how particular function can run as different user. Do you know if .NET Core 3.1 supports this on Linux containers?

**Comment by wfurt** [comment]
I don't think you need to run function as particular user. What you need is ability to prove your identity and credentials to printing service. Depending on printing protocol that can be done in variety of ways. 

This may not be clear but .NET does not implement own printing. It is only thin wrapper around libcups. You will need to create and configure print queue with http://www.cups.org 

You may take look at https://www.north-47.com/knowledge-base/network-printing-with-cups-from-docker/

**Comment by apetrut** [comment]
Thanks, @wfurt . I will investigate your approach when I have more time. For the moment, I decided to create a Worker Service (that is running as a Windows service - no containerization involved here) and will listen to messages coming from the other microservices running inside Linux (I use RabbitMQ for sending messages between microservices). In this way I can print using impersonation separate from other microservices that are running under Linux.

**Comment by safern** [comment]
Given that the question seems responded I will close this issue. Please let me know if you have any other questions.
