### ISSUE TITLE
Refresh Clientcertificate in HttpClientHandler

### ISSUE THREAD

**Issue by gakhande** [dotnet/runtime#52779]
I am working on using HttpClient for our web app to send the requests to the backend
Currently with how the things are coded, we ingest the SSL certificate( used to communicate with the BE) in the primary http handler at the startup
We need a way to refresh the certificate whenever a new cert is available in the Key Vault

Here is the code in our Startup:

```c#
Events.LogTraceEvent(LoggingManager, LogType.Information.ToString(), $"Loading Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ from KeyVault");
var certificate = AzureCertificateService.FindCertificate(Config.CertConfig.ClientCertSubject, Config.CertConfig.ClientCertLocation, Config.CertConfig.AzureKeyVaultAddress);
if (certificate != null)
{​​​​​
Events.LogTraceEvent(LoggingManager, LogType.Information.ToString(), $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ successfully loaded");
IfxTracer.LogMessage(IfxTracingLevel.Informational, "0", $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ successfully loaded with Thumbprint {​​​​​certificate.Thumbprint}​​​​​");
}​​​​​
else
{​​​​​
Events.LogTraceEvent(LoggingManager, LogType.Error.ToString(), $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ failed to load");
IfxTracer.LogMessage(IfxTracingLevel.Error, "0", $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ failed to load");
}​​​​​

        services.AddHttpClient(Options.DefaultName).ConfigurePrimaryHttpMessageHandler(() =>
        {​​​​​
            var handler = new HttpClientHandler();
            
            if (certificate != null)
            {​​​​​
                handler.ClientCertificates.Add(certificate);

                Events.LogTraceEvent(LoggingManager, LogType.Information.ToString(), $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ added to HttpClientHandler");
                IfxTracer.LogMessage(IfxTracingLevel.Informational, "0", $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ added to HttpClientHandler with Thumbprint {​​​​​certificate.Thumbprint}​​​​​");
            }​​​​​
            else
            {​​​​​
                Events.LogTraceEvent(LoggingManager, LogType.Error.ToString(), $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ failed add to HttpClientHandler");
                IfxTracer.LogMessage(IfxTracingLevel.Error, "0", $"Certificate {​​​​​Config.CertConfig.ClientCertSubject}​​​​​ failed add to HttpClientHandler");
            }​​​​​
            return handler;
        }​​​​​);
```
This is how we create the httpclient and send the request to the BE:

```c#
HttpClient httpClient = HttpClientFactory.CreateClient();
SendBackendRequest(httpClient, clientRequestBytes, Accessor.HttpContext.Connection.RemoteIpAddress.ToString(), AuthgatewayConfigController.Url.ToString(), LoggingManager);
```

How can we refresh the cert without using any locking and not causing other calls to fail?

**Comment by CarnaViire** [comment]
If my knowledge is correct, `SocketsHttpHandler.SslOptions.LocalCertificateSelectionCallback` should be used for situations like this. @wfurt could you please verify and help with how it should be set up?

**Comment by wfurt** [comment]
yes, the callback should work e.g. use SocketsHttpHandler explicitly instead of HttpClientHandler. Alternatively, you would need to create new client once change is detected. It is not safe to modify the certificates when HttpClient is in use.

**Comment by CarnaViire** [comment]
Creating new client wouldn't help if HttpClientFactory is used.
So I would expect code looking something like that

```c#
services.AddHttpClient(...)
    .ConfigurePrimaryHttpMessageHandler(() =>
    {​​​​​
        return new SocketsHttpHandler()
        {
            SslOptions = new SslClientAuthenticationOptions()
            {
                LocalCertificateSelectionCallback = (object sender, string targetHost, X509CertificateCollection localCertificates, X509Certificate? remoteCertificate, string[] acceptableIssuers) => 
                {
                     // extract certificate from Key Vault or whatever cache you have and return it here
                }
            }
        };
    });
```

Please let me know if this helps @gakhande

**Comment by gakhande** [comment]
Thanks a lot. So, will the below code ensure that the certificate gets refreshed whenever a new certificate is available in the Vault? And this wont affect any other calls to the service.
services.AddHttpClient(Options.DefaultName).ConfigurePrimaryHttpMessageHandler(() =>
            {
                return new SocketsHttpHandler()
                {
                    SslOptions = new SslClientAuthenticationOptions()
                    {
                        LocalCertificateSelectionCallback = (object sender, string targetHost, X509CertificateCollection localCertificates, X509Certificate? remoteCertificate, string[] acceptableIssuers) =>
                        {
                            var certificate = AzureCertificateService.FindCertificate(Config.CertConfig.ClientCertSubject, Config.CertConfig.ClientCertLocation, Config.CertConfig.AzureKeyVaultAddress);
                            if (certificate != null)
                            {
                                Events.LogTraceEvent(LoggingManager, LogType.Information.ToString(), $"Certificate {Config.CertConfig.ClientCertSubject} successfully loaded");
                                IfxTracer.LogMessage(IfxTracingLevel.Informational, "0", $"Certificate {Config.CertConfig.ClientCertSubject} successfully loaded with Thumbprint {certificate.Thumbprint}");
                            }
                            else
                            {
                                Events.LogTraceEvent(LoggingManager, LogType.Error.ToString(), $"Certificate {Config.CertConfig.ClientCertSubject} failed to load");
                                IfxTracer.LogMessage(IfxTracingLevel.Error, "0", $"Certificate {Config.CertConfig.ClientCertSubject} failed to load");
                            }

                            return certificate;
                        }
                    }
                };
            });

**Comment by CarnaViire** [comment]
This will retrieve a certificate from Key Vault every time new connection is established (please correct me if I'm wrong @wfurt). So if the cert was changed by the time new HTTP connection is created, new cert will be returned, otherwise you will just retrieve the same one.

I wonder about an overhead you may get on every connection creation, because I don't know how fast your Key Vault is. @wfurt do you have any thoughts here? Is some caching possible/profitable?

**Comment by gakhande** [comment]
We need to handle a scenarios where the certificate automatically refreshes whenever a need certificate is available in AKV without having to restart the service. Also we want to make sure that AKV is not throttled.

**Comment by CarnaViire** [comment]
Is AKV able to notify you in some way that certificate changed there?

**Comment by gakhande** [comment]
no but can we use some AKV cache that asynchronously fetches the cert from the AKV?

**Comment by gakhande** [comment]
we will have to probably compare the thumbprints of the certs to identify if there is a new certificate available.

**Comment by CarnaViire** [comment]
Yes, that's what I had in mind when I was talking about caching before. Get the cert from the cache in LocalCertificateSelectionCallback, and in parallel check whether the cache needs to be updated from AKV.

I'm closing this issue as answered. If the LocalCertificateSelectionCallback wouldn't work for you for some reason, feel free to reopen.
