### ISSUE TITLE
exclusive_sync::check() in release builds

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#52770]
- Should `exclusive_sync::check()` be running in release builds at all?
- If yes, should it rather be `FATAL_GC_ERROR` instead?

One of partner teams hit DebugBreak in this method due to unrelated bug. It came as a surprise that CoreCLR GC is calling DebugBreak in release builds.

**Comment by mangod9** [comment]
Looks like its been this way for a while.

**Comment by Maoni0** [comment]
I added this when I enabled BGC and since this logic is pretty tricky I wanted to do some cheap checks in retail to help catch bugs. since this is cheap enough we can keep it in retail but yes, we should change it to FATAL_GC_ERROR instead.

**Comment by Maoni0** [comment]
#56660
