### ISSUE TITLE
System.Diagnostics.PerformanceCounter package: cannot read counters unless administrator

### ISSUE THREAD

**Issue by rickyburrell** [dotnet/runtime#52801]
In the latest version (5.0.1) of the System.Diagnostics.PerformanceCounter package, there is a bug that prevents non administrators from reading counter data - they get 0's for all values read using Permon on local box or via remote registry. Usually, you only need to be a member of the "Performance Monitor Users" group.

The port from .Net framework to Core removed a line of code from SharedperformanceCounter.Initialize that set the correct security descriptor on the counter memory mapped file.

See picture below for comparison between .Net & Core versions.

Please can someone fix?

![Perf Counters Issue](https://user-images.githubusercontent.com/29256754/118349184-77176d80-b54f-11eb-8751-70a2f4836518.png)

**Comment by rickyburrell** [comment]
For interest's sake - here are the permissions that are no longer correctly applied to the memory mapped file:
![image](https://user-images.githubusercontent.com/29256754/118606855-2d7d8b80-b7b8-11eb-86d6-89d35986503f.png)

**Comment by danmoseley** [comment]
@Anipik is this fixed by your #48026 ? 

@rickyburrell I assume this works in the latest 6.0 preview?

**Comment by Anipik** [comment]
yes it should be fixed now
