### ISSUE TITLE
On x64 platform, "stelem.ref" ignores high bits of "native int" index

### ISSUE THREAD

**Issue by kevinjwz** [dotnet/runtime#52817]
`IndexOutOfRangeException` not thrown when index=0x100000000.
[sharplab test](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyA6AJXwwEsBbGZgYQjcADpwA2MKAGVJAN05gYAZwDc1akQDMjMkkYl6/agG9q9c/QDaAWRgYAFhAAmASRFiAFLYfO3wsQDywlwQeErMAHIQLnhinHjxAOYAlAC6ZhZMekQo9FIYMBLcAPqsMABmHhDAAFYwYBiWqfQAhlBQaPQJeBj0nJ0BtfW9si1iODDJGRYWALwAfK3tlpzNs/Sj4zBqVDPTVt6Oru5edkd+gcGcoeFRMXHdKem7mbqMufmFMCUuKB7xjWabQ6XQBfU6YM2EymLxm5gWSygKzWGzGEx2e1hOmyuWsLXiHhhM1MWJmoygiPo6zwMAA7vRBnUGpYyLRUhi4eZyYiDNS6X0eiy2RzOd1evEnDAEFT6B4xckyAAeRWaEgiuH7GafIqlCoeYEQvCShCdPA4MRiZLqrUFHW/fXtEiG42dWhWzWvACcDqRbPdWIAvtQg1QgA=)

**Comment by teo-tsirpanis** [comment]
Judging from the disassembly, the `stelem.ref` instruction calls `System.Runtime.CompilerServices.CastHelpers.StelemRef` helper method, which takes the index as a 32-bit integer. The index's high part is thrown away becoming zero, and the runtime happily stores your object to the array's zeroth position.

**Comment by GrabYourPitchforks** [comment]
Regression from 3.1, introduced in 5.0.

**Comment by GrabYourPitchforks** [comment]
Repathed to VM area, because that really seems like the closest thing to the true area owners.
/cc @VSadov

**Comment by SingleAccretion** [comment]
> Judging from the disassembly, the stelem.ref instruction calls System.Runtime.CompilerServices.CastHelpers.StelemRef helper method, which takes the index as a 32-bit integer. The index's high part is thrown away becoming zero, and the runtime happily stores your object to the array's zeroth position.

That's correct. It looks like [we just import a call to the helper](https://github.com/dotnet/runtime/blob/127be4b3894d8b9126009a653679c80d64e8d797/src/coreclr/jit/importer.cpp#L12445), and it is the helper's responsibility to check out of range conditions, [which it does](https://github.com/dotnet/runtime/blob/127be4b3894d8b9126009a653679c80d64e8d797/src/coreclr/System.Private.CoreLib/src/System/Runtime/CompilerServices/CastHelpers.cs#L568). I am wondering what would be needed here beyond changing the helper's signature to take `nint` instead of `int`.

**Comment by GrabYourPitchforks** [comment]
> I am wondering what would be needed here beyond changing the helper's signature to take nint instead of int.

That's why I pathed it under VM. Not sure if we require JIT changes to ensure 32-bit int indices (the 99.9999% case) are properly native word size extended before invoking the helper method. The VM area owners would know for sure.

**Comment by teo-tsirpanis** [comment]
I also noticed that the native-sized index is first `conv.i8`ed. Is that done on purpose? The documentation of `stelem.ref` says that the index is of type `native int`. Why first convert it to an `int64`?

**Comment by SingleAccretion** [comment]
> Not sure if we require JIT changes to ensure 32-bit int indices (the 99.9999% case) are properly native word size extended before invoking the helper method.

I suspect changes will be needed, heh (looks like we don't sign extend right now), or an alternative version of the helper. Another note: seems like `ldelema` has the same problem.

**Comment by VSadov** [comment]
When I am running the `Stelem_Ref` repro with 3.1, I get the same results as on 5.0. I do not think this is a regression.

The previous implementation of the helper in x64 assembly truncated the index to 32bit as well - https://github.com/dotnet/runtime/pull/32722/files#r633023865

**Comment by am11** [comment]
It does not throw from `Stelem_I4` either on 3.1 (linux-x64).

**Comment by davidwrighton** [comment]
I've looked into this. We can't just extend the helper to take a nint, we'll need to have a parallel helper, or force the index to be sign extended to nint. The abi of several of our platforms doesn't reliably set the high bits to 0 when passing 32bit values.
