### ISSUE TITLE
dotnet publish with no-rebuild on a single file fails

### ISSUE THREAD

**Issue by timheuer** [dotnet/runtime#52819]
### Description
When running dotnet publish with --no-build option and also adding singlefile options, it fails.  I'm hopeful I'm just missing a step.  I tried a few builds on the dependent projects, but nothing seemed to work for me

```
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'D:\source\repos\FloatingGlucose\FloatingGlucose\obj\Release\net5.0-windows\win10-x64\singlefilehost.exe'. [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018: File name: 'D:\source\repos\FloatingGlucose\FloatingGlucose\obj\Release\net5.0-windows\win10-x64\singlefilehost.exe' [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) in System.IO.FileSystem.dll:token 0x60001aa+0x59 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) in System.IO.FileSystem.dll:token 0x60000ef+0x56 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.BinaryUtils.CopyFile(String sourcePath, String destinationPath) in Microsoft.NET.HostModel.dll:token 0x6000065+0x20 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) in Microsoft.NET.HostModel.dll:token 0x600003b+0x123 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() in Microsoft.NET.Build.Tasks.dll:token 0x60000ea+0x1a6 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in Microsoft.NET.Build.Tasks.dll:token 0x60004b2+0x0 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in Microsoft.Build.dll:token 0x60015da+0x3e [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1057,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) in Microsoft.Build.dll:token 0x600145a+0x2b5 [D:\source\repos\FloatingGlucose\FloatingGlucose\FloatingGlucose.csproj]
```
### Repro example
Repo: https://github.com/timheuer/FloatingGlucose
 
Steps:

1. Git clone https://github.com/timheuer/floatingglucose
2. Git submodule update –init –recurseive
3. Dotnet restore -r win10-x64
4. Dotnet build FloatingGlucose/FloatingGlucose.csproj -r win10-x64 –configuration Release
5. dotnet publish --configuration Release --runtime=win10-x64 --output ./publish -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained=true -p:DebugType=None .\FloatingGlucose\FloatingGlucose.csproj --no-build

Removing --no-build resolves this.  _Why not just do that?_ Well, we've established a devops best practice to be explicit about the build/restore steps in our templates/discussions/etc.  So this pattern should also work with singlefile.

### Configuration

`dotnet --version`
6.0.100-preview.4.21255.9

`dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.4.21255.9
 Commit:    950e4949a7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\

Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21228.15 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21226.14 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21222.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21222.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21223.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by alexrp** [comment]
If you set `PublishSingleFile=true` during `dotnet build` as well, it will work.

**Comment by agocke** [comment]
Unfortunately this is a design issue. Unless `build` is given all the properties of `publish`, it can never be guaranteed that `publish` will succeed. Adding `PublishSingleFile` during build does fix this, and at the moment this is the correct solution.

In general, different options cannot be passed to build and publish and expect to succeed without rebuild.
