### ISSUE TITLE
Self-contained GUI application on macOS opens a terminal

### ISSUE THREAD

**Issue by vadi2** [dotnet/runtime#52813]
I'm publishing an app for macOS built with qml.net + .NET 5 and when I launch the binary, it opens a corresponding terminal window. 

How can I configure it not to open a terminal window? It's not desired for a GUI application.

```xml
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX')) and '$(Configuration)' == 'Release'">
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>Link</TrimMode>
  </PropertyGroup>
```

![image](https://user-images.githubusercontent.com/110988/118371750-43b7fb80-b5ae-11eb-86e0-a146fc2c5f6c.png)

**Comment by hez2010** [comment]
How about changing the value of `OutputType` to `WinExe`?

**Comment by vadi2** [comment]
Unfortunately no, same result. Binary can be found on https://github.com/health-validator/Hammer/suites/2752019601/artifacts/60876628

**Comment by vadi2** [comment]
Ping, anything I can do here to provide a better experience on macOS?

**Comment by hez2010** [comment]
You need to create an application bundle on macOS manually.
See https://docs.avaloniaui.net/docs/distribution-publishing/macos

**Comment by agocke** [comment]
This seems to be a property of the Mac deployment system for GUI apps. .NET 5 doesn't ship any GUI frameworks for Mac in-box so this is a question that is better suited for the author of your GUI framework.
