### ISSUE TITLE
Change in behavior of CultureInfo between Net Core 3.1 and Net 5 (breaking change ?)

### ISSUE THREAD

**Issue by thibault-reigner** [dotnet/runtime#52837]
### Description

I have observed a change between Net Core 3.1.15 and Net 5.0.6 on Windows 10 (19042.985) for the following code 
```
System.Globalization.CultureInfo.GetCultureInfo(1033).CompareInfo.Compare("ss", "ß").Dump();
```
The result being : 
on Net Core 3.1 : 0 
on Net 5 : -1 

I suspect the correct result is 0 as SQL Server collation Latin1_General_CS_AS (whose location id is 1033) also considers the two strings as equal.

As I could not find a breaking change listed in https://docs.microsoft.com/en-us/dotnet/core/compatibility/5.0 explaining this, I created this issue.

**Comment by Joe4evr** [comment]
This is likely a byproduct from [the switch to ICU Culture Info](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) (which *is* listed in the breaking change list).

**Comment by thibault-reigner** [comment]
> This is likely a byproduct from [the switch to ICU Culture Info](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api) (which _is_ listed in the breaking change list).

Thank you for your answer 👍 I indeed did not consider a difference in behaviour between NLS and ICU for a same culture.
Hence it is indeed not an issue in .NET itself. I will close this issue.
