### ISSUE TITLE
Support to request extensions://** by HttpClient

### ISSUE THREAD

**Issue by newbe36524** [dotnet/runtime#52836]
### Is your feature request related to a problem? Please describe.

When I try to develop a browser extension by blazor. I have to fetch some resources hosts in extensions://* protocol by HttpClient.

But it throw a exception like:

```cs
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Only 'http', 'https', and 'blob' schemes are allowed. (Parameter 'requestUri')
System.ArgumentException: Only 'http', 'https', and 'blob' schemes are allowed. (Parameter 'requestUri')
   at System.Net.Http.HttpRequestMessage.InitializeValues(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, Uri requestUri)
   at System.Net.Http.HttpClient.CreateRequestMessage(HttpMethod method, Uri uri)
   at System.Net.Http.HttpClient.GetStreamAsync(Uri requestUri, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsync(Uri requestUri)
   at System.Net.Http.HttpClient.GetStreamAsync(String requestUri)
   at Newbe.Blazors.TryNet.Pages.Index.Compile(String text, MetadataReference[] additionalReferences) in D:\Repo\newbe\Newbe.Demo\src\BlogDemos\Newbe.Blazor\Newbe.Blazors.TryNet\Newbe.Blazors.TryNet\Pages\Index.cs:line 64
   at Newbe.Blazors.TryNet.Pages.Index.CompileAndEncode(String text, MetadataReference[] additionalReferences) in D:\Repo\newbe\Newbe.Demo\src\BlogDemos\Newbe.Blazor\Newbe.Blazors.TryNet\Newbe.Blazors.TryNet\Pages\Index.cs:line 49
   at Newbe.Blazors.TryNet.Pages.Index.OnClickRunAsync() in D:\Repo\newbe\Newbe.Demo\src\BlogDemos\Newbe.Blazor\Newbe.Blazors.TryNet\Newbe.Blazors.TryNet\Pages\Index.cs:line 86
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Describe the solution you'd like
A clear and concise description of what you want to happen. Include any alternative solutions you've considered.

Please allow some additional schema like 'extensions' by some Property in HttpClient class.

**Comment by karelz** [comment]
@newbe36524 what is "extensions://* protocol"? I never heard of that. What does it do? What's the protocol?

As the exception says, `HttpClient` does not support it -- even `Uri` does not support it.
Is it something that JavaScript / WebAssembly natively support? If yes, then it would be feature request for .NET WebAssembly I assume ...

**Comment by newbe36524** [comment]
> @newbe36524 what is "extensions://* protocol"? I never heard of that. What does it do? What's the protocol?
> 
> As the exception says, `HttpClient` does not support it -- even `Uri` does not support it.
> Is it something that JavaScript / WebAssembly natively support? If yes, then it would be feature request for .NET WebAssembly I assume ...

I can develop a chrome extension by Blazor WebAssembly. just like this project https://github.com/newbe36524/Amazing-Favorites.

In this way, I can using C# to build a chrome extensions.

However, if I want to request a resource such as extension://gglgheekopdecoeeinlggdmedamjbjpj/sample.json by HttpClient. The exception raised

![image](https://user-images.githubusercontent.com/7685462/118478165-2320aa80-b742-11eb-9ae5-b138bbc20ade.png)

**Comment by newbe36524** [comment]
Actually, I try to port a Blazor WebAssembly project from hosted style into to chrome extension style. But block by if I want to send a request with extensions://* protocol since all files is host in extensions folder instead of a web server.
It will throw a exception by HttpClient as the code below:

https://github.com/BlazorRepl/BlazorRepl/blob/master/Core/CompilationService.cs#L233

**Comment by karelz** [comment]
It is still not clear to me what is the "extensions://*" protocol? Is it just HTTP? Or something else?
How does JavaScript or something else communicate with such endpoints?

That will answer the question if it is something `HttpClient` in WebAssembly might want to support or not.

**Comment by newbe36524** [comment]
> It is still not clear to me what is the "extensions://*" protocol? Is it just HTTP? Or something else?
> How does JavaScript or something else communicate with such endpoints?
> 
> That will answer the question if it is something `HttpClient` in WebAssembly might want to support or not.

Just like http but they are real files hosted by browser extensions and target to browser extensions folder.
Take edge as a example. 
I open extensions 
![image](https://user-images.githubusercontent.com/7685462/118483519-ae04a380-b748-11eb-91f0-c8a4b3544f74.png)

click any one of backgroud page of a extensions
![image](https://user-images.githubusercontent.com/7685462/118483940-3b47f800-b749-11eb-8f85-1e94c8c9dc3f.png)


dev tool will show as below, and refresh dev tools by F5, you can find networks details, and open anyone of them that target to chrome-extensions:// and "open it in new tab", you could find url with extensions://*
![image](https://user-images.githubusercontent.com/7685462/118483809-0e93e080-b749-11eb-8948-b4957ee5d967.png)

**Comment by BenLampson** [comment]
> It is still not clear to me what is the "extensions://*" protocol? Is it just HTTP? Or something else?
> How does JavaScript or something else communicate with such endpoints?
> 
> That will answer the question if it is something `HttpClient` in WebAssembly might want to support or not.

The extensions://* is chrome or the chromium system's private "extends manager protocol"
it's full string is :  chrome-extension://<extensionID>/<pathToFile>
extensionID is target extendsid, 
path to file is the relative path about the extends folder.

You can think that is chromium's private file protocol, like file:\\.....

**Comment by newbe36524** [comment]
@wfurt In fact now, I am limited by this line of code because its requirements must be within the given range.
https://github.com/dotnet/runtime/blob/ab4e593f44f739896ff84f617b14c1c0676b9d38/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L810

I'm curious if it's possible to change this behavior by way of dependency injection or other options to be able to support wider or narrower scopes, rather than using this hard-coded approach.
The rest doesn't need to be modified.
This check is currently bypassed in my project by reflection, which works but does not seem elegant and efficient.
https://github.com/newbe36524/Newbe.Demo/blob/feature/blazor/src/BlogDemos/Newbe.Blazor/Newbe.Blazors.TryNet/Newbe.Blazors.TryNet/Pages/Index.cs#L67

**Comment by scalablecory** [comment]
@newbe36524 I believe that is only checked if you set `BaseUri`. If you give an absolute `Uri` in your `HttpRequestMessage`, does that solve your problem?

CC @marek-safar @kjpou1 @lewing we should consider if it makes sense to explicitly support things like this for browser.

**Comment by MihaZupan** [comment]
The check is also in `HttpRequestMessage` which will reject any Uri scheme except for:
`http`, `https`, `ws`, `wss` and (for browser) `blob`.

**Comment by newbe36524** [comment]
@scalablecory Yeah, just as @MihaZupan  mentioned, for now, it block me in HttpClient.BaseUri and HttpRequestMessage.Uri, and even WebRequest.Create.
So there is no way for me to send that request to the schema in C# class. I must skip the checking by reflection as I metioned above.

**Comment by geoffkizer** [comment]
> If this boils down to schema check only, I think we could loosen the restriction for wasm.

Yeah, I'm not sure what the point of checking this in HttpClient/HttpRequestMessage themselves is. 

The underlying HttpClientHandler will enforce whatever schemes it knows how to handle. Limiting this at the HttpClient/HttpRequestMessage layer seems unnecessary.

**Comment by karelz** [comment]
Triage: We agree that `HttpClient`/`HttpRequestMessage` should not do any schema validation. We already have `blob` for wasm.
Let's keep the check only in Handler.

**Comment by karelz** [comment]
@stephentoub what do you think?

**Comment by newbe36524** [comment]
Hi, friends, any update? I wonder that would it be ok in next net 6 preview or not?

**Comment by wfurt** [comment]
AFIK It is too late for preview 6 @newbe36524. We agreed this may make sense but it is not on top of the priority list.

**Comment by karelz** [comment]
Yes, we would take a PR.

@stephentoub do you have opinion on the plan?

**Comment by stephentoub** [comment]
> @stephentoub do you have opinion on the plan?

As long as all of our handlers do the appropriate validation for what they're capable of, removing such validation from HttpClient / HttpRequesrMessage sounds like the right thing to do.
