### ISSUE TITLE
Download link for dotnet CORE does not redirect anywhere

### ISSUE THREAD

**Issue by affanmustafa** [dotnet/runtime#52831]
I have a WPF application that requires .NET Core 2.2 and 3.1. In case they are not installed, a window pops up which says the following:

![Capture](https://user-images.githubusercontent.com/69677074/118444360-7117bd00-b706-11eb-90f1-06719ed6b435.PNG)

When you click "Yes" to install .NET Core, nothing happens. No browser window opens up and it seems like the link is broken. After doing nothing, the application just closes down.

**Comment by vitek-karas** [comment]
I just tried it on 3.1 and it works locally. When I run it with no .NET Core installed it pops up the dialog above, and when I click Yes it opens a web page in my default browser. I don't know what's causing it to not work in your case. You can try to set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=host.txt` and run the app and repro the issue. It should produce a detailed log file in `host.txt` which should contain information about which URL it tried to open. (This will only work in 3.1).

Maybe make sure that the machine has correctly configured default browser - all the dialog does is try to open a URL using the OSes "ShellExecute open" which is equivalent to doing `Win+R` and pasting a URL into the dialog an enter.

**Comment by vitek-karas** [comment]
This is not actionable without more details. Please feel free to reopen or create a new issue if this is still a problem.
