### ISSUE TITLE
System.Text.Json 5.0.2 not supported on Azure Functions Default Run Time

### ISSUE THREAD

**Issue by notaroobob** [dotnet/runtime#52845]
### Description

System.Text.Json 5.0.2 brings with it an update to System.Text.Encodings.Web of 5.0.1.

The Dot net Runtimes for Azure Functions (linux in my case) is not allowing any executable to fire up. Specifically it's throwing an error that System.Text.Encodings.Web 5.0.0 is not found (which is true because it's now 5.0.1). Trying to force an update to 5.0.1 for Encodings.Web via nuget packages did not resolve the issue.

Reverting to System.Text.Json 5.0.1 (and System.Text.Encodings.Web to 5.0.0) fixes the issue for now, but I'll be needing to walk on egg shells for the next couple of months until Dot Net 6 consolidates and ships as default for the greater azure eco system.

### Configuration

* Which version of .NET is the code running on? - dot net core 3.1
* What OS and version, and what distro if applicable? - Locally Mac OS 11.3.1. Deployed to Linux Consumption Function Tier 
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? Unknown, assumption is no

### Regression?

Resolved via downgrading to System.Text.Json 5.0.1

**Comment by notaroobob** [comment]
And I didn't realize this was in response to a CVE the need to go to 5.0.1 for the Encodings library. Whitesource is complaining on Github PRs.

**Comment by eiriktsarpalis** [comment]
Judging by the stacktrace this seems like an issue related to Azure functions .NET infrastructure. Have you tried contacting the Azure functions team?

**Comment by notaroobob** [comment]
> Judging by the stacktrace this seems like an issue related to Azure functions .NET infrastructure. Have you tried contacting the Azure functions team?

I have not yet as it took me a minute to get this data put together. I see a [conversation](https://github.com/dotnet/runtime/issues/45560) going to back to December for System.Text.Json not referencing Live dlls versus those that are in the shared framework.

Recommended approach is a new github issue then?

**Comment by eiriktsarpalis** [comment]
> Recommended approach is a new github issue then?

Yes. I'm not familiar with Azure functions or how its assembly loading mechanism works. I would recommend filing an issue with them so that they can triage on their side. We can revisit if this turns out to be a packaging issue for System.Text.Json.

**Comment by eiriktsarpalis** [comment]
It seems that there's nothing actionable from the STJ library perspective. Closing in favor of https://github.com/Azure/Azure-Functions/issues/1898.
