### ISSUE TITLE
[MacCatalyst][libraries] System.Threading.Thread.Tests failures

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#52856]
System.Threading.Thread.Tests.dll   Failed: 8
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"WaitAllNotSupportedOnSta_Test0\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"DefaultApartmentStateMain.exe\", testName: \"SetApartmentStateTest\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"GetApartmentStateTest\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"MTAMain.exe\", testName: \"GetApartmentStateTest\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"WaitAllNotSupportedOnSta_Test1\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"MTAMain.exe\", testName: \"SetApartmentStateTest\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"DefaultApartmentStateMain.exe\", testName: \"GetApartmentStateTest\")
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"SetApartmentStateTest\")
```
System.Threading.Thread.Tests.dll   Failed: 8

Test collection for System.Threading.Threads.Tests.ThreadTests
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"WaitAllNotSupportedOnSta_Test0\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"DefaultApartmentStateMain.exe\", testName: \"SetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"GetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"MTAMain.exe\", testName: \"GetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"WaitAllNotSupportedOnSta_Test1\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"MTAMain.exe\", testName: \"SetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"DefaultApartmentStateMain.exe\", testName: \"GetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory
System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: \"STAMain.exe\", testName: \"SetApartmentStateTest\")
    System.ComponentModel.Win32Exception : No such file or directory

**Comment by mangod9** [comment]
assume this is specific to Mono? hence moving to Threading-mono for now.

**Comment by steveisok** [comment]
This should not work on MacCatalyst and is flagged as being skipped.
