### ISSUE TITLE
[MacCatalyst][libraries] System.Diagnostics.Process.Tests fails on MacCatalyst

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#52852]
System.Diagnostics.Process.Tests.dll   Failed: 7
System.Diagnostics.Tests.ProcessTests.MaxWorkingSet_GetNotStarted_ThrowsInvalidOperationException
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_Executes(filenameAsUrl: False)
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_Executes(filenameAsUrl: True)
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_WorkingDirectory
System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName
System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported
System.Diagnostics.Tests.ProcessTests.MinWorkingSet_GetNotStarted_ThrowsInvalidOperationException
```
System.Diagnostics.Process.Tests.dll   Failed: 7

Test collection for System.Diagnostics.Process.Tests.dll
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_Executes(filenameAsUrl: False)
    System.ComponentModel.Win32Exception : No such file or directory
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_Executes(filenameAsUrl: True)
    System.ComponentModel.Win32Exception : No such file or directory
System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_WorkingDirectory
    System.ComponentModel.Win32Exception : No such file or directory
System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName
    System.ComponentModel.Win32Exception : No such file or directory
System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported
    System.ComponentModel.Win32Exception : Undefined error: 0

**Comment by steveisok** [comment]
@akoeplinger Is this actually going to ever work on catalyst?

**Comment by steveisok** [comment]
These tests are all skipped on platform, which means they aren't intended to work. No need for this issue to be open.
