### ISSUE TITLE
Race in scoped services promoted to singleton caching

### ISSUE THREAD

**Issue by pakrym** [dotnet/runtime#52863]
The https://github.com/dotnet/runtime/pull/52484 attempted to fix the race where `CallSiteRuntimeResolver.Instance.Resolve` and compiled service accessors have a different source of truth for a scoped services promoted to singletons caching location.

The former presumes the value is cached in callSite.Value the latter in `ResolvedServices` dictionary on the scope.

The problem with the fix is that it only tightened the race for directly resolved services but did nothing for indirectly-resolved ones.

For the following chain:

`A(Singleton)->B(Scoped)`

When A is resolved B is also resolved and cached into the `callSite.Value`. When a direct compiled accessor for `B` is executed on the root scope it would bypass the logic in the fix and would use the ResolvedService collection, skipping `callSite.Value` entirely.

**Comment by pakrym** [comment]
I think this test illustrates the problem:

```C#
        [Fact]
        public void ScopedServiceResolvedFromSingletonAfterCompilation2()
        {
            ServiceProvider sp = new ServiceCollection()
                                .AddScoped<A>()
                                .AddSingleton<IFakeOpenGenericService<A>, FakeOpenGenericService<A>>()
                                .BuildServiceProvider();

            var scope = sp.CreateScope();
            for (int i = 0; i < 10; i++)
            {
                scope.ServiceProvider.GetRequiredService<A>();
                Thread.Sleep(10); // Give the background thread time to compile
            }

            Assert.Same(sp.GetRequiredService<IFakeOpenGenericService<A>>().Value, sp.GetRequiredService<A>());
        }
```

`IFakeOpenGenericService<A>` would promote `A` to the singleton so both `IFakeOpenGenericService<A>.Value` and `A` resolved from root should be the same.

**Comment by davidfowl** [comment]
cc @maryamariyan @eerhardt
