### ISSUE TITLE
System.Diagnostics.Process.GetProcesses() returns truncated 15 char string on macOS

### ISSUE THREAD

**Issue by SimeonIksanov** [dotnet/runtime#52860]
When using Process.GetProcesses() on macOS in dotnet core it returns process names as strings max 15 chars. It truncates the process names to be 15 char long.

### Configuration
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

**Comment by wfurt** [comment]
I think that comes from MAXCOMLEN limit on kinfo_proc. I think we would need to find different way than
```c#
info.ProcessName = Marshal.PtrToStringAnsi((IntPtr)kinfo->ki_comm)!;
```

**Comment by Genbox** [comment]
To whomever grabs this. The sysctrl interface in macOS does not support giving longer paths. You need the libproc interface instead. Luckily, the interop is [already implemented](https://github.com/dotnet/runtime/blob/f54ec728b0c836f6633b9ce52c9fe97452e5232e/src/libraries/Common/src/Interop/OSX/Interop.libproc.cs#L331) in .NET Runtime.

That means, to fix this issue, it would be a simple matter to rewrite the [line here](https://github.com/dotnet/runtime/blob/f54ec728b0c836f6633b9ce52c9fe97452e5232e/src/libraries/Common/src/Interop/FreeBSD/Interop.Process.cs#L126), to use the libproc interop.

**Comment by sonodima** [comment]
Is there anything blocking the transition to using the main module's `FileName` property in the implementation of `Process.Name` and `Process.GetProcessesByName`?

Given that even the **ps** command extracts the long name from the main module's path I believe it's the right thing to do here as well.

**Comment by danmoseley** [comment]
@sonodima I think this issue is available if you want to give it a try.

**Comment by wfurt** [comment]
That would work only for current process right @sonodima? (e.g. it would not work for all processes in the system)
Even that would be good improvement.

**Comment by am11** [comment]
> For anyone with this problem, a workaround is to call `Process.GetCurrentProcess().MainModule.FileName` instead. Something like this:
> 
> ```cs
> string? fileName = currentProcess.MainModule?.FileName;
> 
> if (string.IsNullOrEmpty(fileName))
>     throw new InvalidOperationException("Unable to obtain process name");
> 
> char[] split = { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar };
> 
> int idx = fileName.LastIndexOfAny(split);
> string processName = fileName.Substring(idx + 1);
> ```

This produces the same result: `Path.GetFileName(Environment.ProcessPath)` (.NET 6+).

**Comment by sonodima** [comment]
> That would work only for current process right @sonodima? (e.g. it would not work for all processes in the system) Even that would be good improvement.

This should work on all the processes. I wrote a similar implementation some time ago in another project's process abstraction, and using the filename was still better behaviour than using the truncated name.

Moreover, in [these tests](https://github.com/dotnet/runtime/issues/30909#issuecomment-656022834) using the path appears to work well even on system processes which would otherwise require sudo permissions.
