### ISSUE TITLE
Why Directory.EnumerateFiles doesn't support globs like in Bash?

### ISSUE THREAD

**Issue by alvinseville7cf** [dotnet/runtime#52868]
Hello! This is a question rather than an issue. Why Directory.EnumerateFiles doesn't support globs like in [Bash](https://www.gnu.org/software/bash/manual/bash.html#Pattern-Matching)? Is it planned to be improved in the future?

**Comment by iSazonov** [comment]
There is  [Microsoft.Extensions.FileSystemGlobbing](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.filesystemglobbing?view=dotnet-plat-ext-5.0)
