### ISSUE TITLE
Expression.Equal with DynamicList seems to return only the first matches

### ISSUE THREAD

**Issue by gyankov** [dotnet/runtime#52867]
### Description

Building an expression with Expression.Equal to filter a DynamicList only returns the first match

### Configuration

Below you will find a sample where the issue can be reproduced:

- [sample]( https://progresssoftware-my.sharepoint.com/:u:/g/personal/gyankov_progress_com/Eb5vR8b5OmlDlzkRfyNM-iABCoQYnIFiQ4oJFTol1LPc-A?e=913y5k)

### Other information

The above sample contains a simplified version of our implementation. Using the same expression for a collection with a type works correctly.

**Comment by cston** [comment]
Thanks for reporting an issue @gyankov. Please consider including a one or two line example of the use of `Expression.Equal` along with the actual and expected results.

**Comment by gyankov** [comment]
@cston I have provided a runnable sample, you can check it in the link below:

- [sample]( https://progresssoftware-my.sharepoint.com/:u:/g/personal/gyankov_progress_com/Eb5vR8b5OmlDlzkRfyNM-iABCoQYnIFiQ4oJFTol1LPc-A?e=913y5k)

**Comment by svick** [comment]
@gyankov That project still contains quite a lot of code and does not really explain what the issue is. Can you simplify it even further? Also, can you describe exactly what behavior you expect and contrast it with the behavior you see?

**Comment by gyankov** [comment]
@svick I am afraid I am not able to simplify it more. I am only able to replicate it when I have multi level grouping. I will try to explain it in steps:

1. Group the data
2. Map(Select) the result to objects which contain group field and group items
3. Group items are retrieved by filtering the data with Expression.Equal
4. Then group the items of every group and select them as in step 2

For better understanding, below I will paste the resulted query:

```
{System.Collections.Generic.List`1[System.Object]
	.GroupBy(item => [Dynamic])
	.Select(group33736294 => new GroupModel() {
		Items = System.Collections.Generic.List`1[System.Object]
				.Where(item => ([Dynamic] == group33736294.Key))
				.GroupBy(item => [Dynamic])
				.Select(group34948909 => new GroupModel() {Items = group34948909})})}
```

**Comment by cston** [comment]
@gyankov, sorry for the delay responding.

It looks the expressions passed to `Expression.Equal()` are typed as `System.Object` even though the values are `System.String` at runtime. As a result, I believe `Expression.Equal()` will use `object.Equals()` to compare the values rather than `string.Equals()`.

If the expressions are converted to `System.String`, the result of the query appears to be correct:
```csharp
result = Expression.Equal(
    Expression.Convert(left, typeof(string)),
    Expression.Convert(right, typeof(string)));
```

**Comment by gyankov** [comment]
@cston Thanks for the update.

I tested to convert the values as suggested and indeed it returns the items as expected, however, I have a follow up question.

As types might differ, how do I get the runtime type of a LambdaExpression body?
