### ISSUE TITLE
Blazor wasm TimeZoneInfo.GetSystemTimeZones() return only few timezones

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#52873]
cc: @guardrex

Opening this bug as directed in this thread [(https://github.com/dotnet/AspNetCore.Docs/issues/22329)]
I am using Blazor wasm client side to list the Timezone using the following code
```
foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
                  _logger.LogInformation(z.Id);
```
it only returns few timezones

```
America/St_Johns
  America/Argentina/Catamarca
  America/Sao_Paulo
  UTC
  Europe/London
  Europe/Lisbon
  Europe/Berlin
  Africa/Tripoli
  Africa/Nairobi
  Europe/Moscow
  Australia/Perth
  Australia/Sydney
  Pacific/Tongatapu
```

Not only that, but when i  try to get the users Time zone, i get incorrect out put

```
currentTimeZone = TimeZoneInfo.Local;
Even this is returning Incorrect Result ( I am in Chicago), but this returns 'America/Los_Angeles'.
```

I tried to follow the article and add the property group, but that did not help in anyway.
[https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0#localization]

[Sample Project SourceCode](https://github.com/nssidhu/TimeZoneissue)

**Comment by tarekgh** [comment]
CC @lewing @tqiu8

**Comment by lewing** [comment]
What version of .NET are you using?

**Comment by nssidhu** [comment]
.NET 5


Sent from Yahoo Mail for iPhone


On Tuesday, May 18, 2021, 3:57 PM, Larry Ewing ***@***.***> wrote:




What version of .NET are you using?

**Comment by nssidhu** [comment]
![Debug Point is not hit](https://user-images.githubusercontent.com/3267605/118734820-c3d79e80-b804-11eb-8c78-697226e26354.jpg)
![NET 5 Info](https://user-images.githubusercontent.com/3267605/118734821-c4703500-b804-11eb-8889-8a842256c253.jpg)

**Comment by nssidhu** [comment]
> What version of .NET are you using?

I have also update the link to sample project source code on github
[Source Code](https://github.com/nssidhu/TimeZoneissue) its on the counter Page

**Comment by lewing** [comment]
@nssidhu this issue should be fixed in the .NET 6 preview, @tqiu8 should we backport the filtering fixes to .NET 5?

**Comment by nssidhu** [comment]
I would request HotFix for .NET 5 if possible , some orgs(ok with me) don't allow Preview versions to be used in production and it will be a long wait.

**Comment by nssidhu** [comment]
Is there specific .NET Preview version that need to be installed to overcome this ?

**Comment by tqiu8** [comment]
> @nssidhu this issue should be fixed in the .NET 6 preview, @tqiu8 should we backport the filtering fixes to .NET 5?

Yes we can do that.

**Comment by lewing** [comment]
this is fixed in .NET 6 and we don't have plans to backport to .NET 5 at this point.
