### ISSUE TITLE
Null Reference Exception In System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment

### ISSUE THREAD

**Issue by Yortw** [dotnet/runtime#52875]
### Description

In production systems (but not our dev environment, we cannot reproduce at will) we are seeing a null reference exception thrown out of System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment. This is being called as the result of an MS App Insights (v2.17) SDK call.

The stack trace/exception details look like:
System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
at System.SpanHelpers.PerTypeValues`1..cctor()
--- End of inner exception stack trace ---
at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
at System.Diagnostics.ActivityTraceId.CreateRandom()
at System.Diagnostics.Activity.GenerateW3CId()
at System.Diagnostics.Activity.Start()
at Microsoft.ApplicationInsights.TelemetryClientExtensions.<>c__DisplayClass3_0`1.<StartOperation>b__0()
at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)
at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[T](TelemetryClient telemetryClient, T operationTelemetry)
<rest of stacktrace contains user application methods and has been snipped for brevity/privacy>

This has only started happening on recent builds of our software, going back to earlier builds of our product gets rid of the error. The two significant changes between those builds are our application assemblies changed from targeting .Net 4.5 to .Net 4.8, and the app insights SDK and dependencies were all upgraded (to 2.17 of App Insights, and the dependency that came with that except for System.Diagnostics.DiagnosticsSource which has been updated to 5.0.0.1).

### Configuration
.Net 4.8
Windows 10
x86 .Net WinForms executable
Do not believe this is specific to this configuration, but uncertain.

**Comment by GrabYourPitchforks** [comment]
@jkotas Suppose this might be related to the `Unsafe.ByteOffset` issues we saw earlier in Full Framework?

**Comment by jkotas** [comment]
@Yortw Could you please report this issue using VS Developer Community Portal (https://github.com/dotnet/core#getting-help)? It is the best place to report .NET Framework issues. .NET Framework issues are not actionable in this repo.

> Suppose this might be related to the Unsafe.ByteOffset issues we saw earlier in Full Framework?

That issue was fixed last year (https://github.com/dotnet/runtime/issues/13701#issuecomment-670722879). Assuming that this crash is happning on fully patched system, it is likely something different.

**Comment by Yortw** [comment]
Sure thing, sorry for my mistake. Thanks for your assistance, team.
