### ISSUE TITLE
Question: Best way to get nullable annotation metadata at runtime

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#52876]
In ASP.NET Core we want to [change behavior based on the nullability of a parameter](https://github.com/dotnet/aspnetcore/issues/32375). What is the best way to get that information at runtime?

(I think I remember a first-class API being added for this but I couldn't find it)

**Comment by danmoseley** [comment]
@buyaa-n

**Comment by buyaa-n** [comment]
> (I think I remember a first-class API being added for this but I couldn't find it)

The API still at the [proposal ](https://github.com/dotnet/runtime/issues/29723) stage, but it is planned for 6.0

**Comment by JamesNK** [comment]
Thanks!
