### ISSUE TITLE
Test failure System.Text.Json.Tests.Serialization.CollectionTests.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52888]
Run: [runtime-libraries-coreclr outerloop 20210517.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1141570&view=ms.vss-test-web.build-test-results-tab&runId=34605078&resultId=104598&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Text.Json.Tests.Serialization.CollectionTests.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation

```

**Error message:**
```
Assert.Equal() Failure
Expected: 1
Actual:   2


Stack trace
   at System.Text.Json.Tests.Serialization.CollectionTests.WriteAsyncEnumerable_LongRunningEnumeration_Cancellation() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/CollectionTests/CollectionTests.AsyncEnumerable.cs:line 90
--- End of stack trace from previous location ---
```

**Comment by eiriktsarpalis** [comment]
That particular build is now gone, but recent history of runs for the particular test in Windows81.Amd64 have all been passing:

https://dev.azure.com/dnceng/public/_build/results?buildId=1248053&view=ms.vss-test-web.build-test-results-tab&runId=37073170&resultId=104619&paneView=history

I'm going to close for now but we can reopen if failures start reoccurring.
