### ISSUE TITLE
Validate that a manifest based EventSource app can be trimmed

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#52900]
Trimmer has [capability](https://github.com/mono/linker/pull/1929) to preserve derived types which was used in `EventSource` to ensure that a manifest is correctly created for a derived EventSource type that uses the manifest path. 

We should validate this although it’s a little challenging to have an EventSource scenario (requires a listener to activate the source) with the path that generates the manifest (that calls the non-dynamic event methods).

**Comment by LakshanF** [comment]
Validated that this works using Microsoft.NETCore.App 6.0.0-rc.1.21371.4, attaching a sample (not comprehensive) program that tests this in trimmed mode.
[program.txt](https://github.com/dotnet/runtime/files/6858004/program.txt)

**Comment by vitek-karas** [comment]
Why can't we add this as an automated test?
