### ISSUE TITLE
value in id property don't match between TimeZoneInfo.Local and item TimeZoneInfo that i get from TimeZoneInfo.GetSystemTimeZones();

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#52916]
I am using .NET 5 blazor wasm with hosted web API.

The value of the id field does not match between the between TimeZoneInfo.Local and item TimeZoneInfo that i get from TimeZoneInfo.GetSystemTimeZones();

I am creating a project where i wan to list all the timezones  and pre-select the timezone user is in.

First approach was to get the list of timezone on the wasm client side, but this only returns few timezone(14 only)
   var TimeZoneList = TimeZoneInfo.GetSystemTimeZones();

so created a WebAPI method that would run this code on server side and return the full list of time zone.

But now the problem is that when i get users current time zone by running the following code in index.razor
TimeZoneInfo.Local
it get me Id with value 'America/Chicago'

But i am not able to find this Id value from the list returned from the server, hence i am not able to preselect the timezone for user.

[Link To Project SourceCode](https://github.com/nssidhu/TimeZoneissue)

**Comment by lewing** [comment]
Which version of .NET5 are you using? Have you tried the latest .NET6 preview to see if that improves the situation?

**Comment by nssidhu** [comment]
Yes, it works in .NET 6 as expected.

Sent from Yahoo Mail for iPhone


On Wednesday, June 16, 2021, 7:18 PM, Larry Ewing ***@***.***> wrote:




Which version of .NET5 are you using? Have you tried the latest .NET6 preview to see if that improves the situation?
