### ISSUE TITLE
SuppressUnmanagedCodeSecurity no effect in .NET Core, will it slow down the performance?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#52953]
No performance test, just curious.

**Comment by GrabYourPitchforks** [comment]
The runtime ignores it; it has no effect on the p/invoke codegen. So it shouldn't affect performance of a running application.

It _may_ affect the performance of introspection routines like reflection, simply by virtue of the fact that it's metadata that needs to be processed by the runtime and projected back as a user-visible object.

**Comment by GF-Huang** [comment]
I means, I remember in .NET Framework, add this attribute to P/Invoke methods will speed up performance, in .NET Core it becomes no effect, will .NET Core P/Invoke slower than .NET Framework with `SuppressUnmanagedCodeSecurity`.

**Comment by reflectronic** [comment]
In .NET Core they are fast "by default."
