### ISSUE TITLE
New rule suggestion:  require overriding Equals(Object) and GetHashCode() when implementing IEquatable

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/runtime#52958]
### Describe the problem you are trying to solve

According to the documentation of [IEquatable](https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-5.0), "If you implement IEquatable<T>, you should also override the base class implementations of Equals(Object) and GetHashCode() so that their behavior is consistent with that of the Equals(T) method"

### Describe suggestions on how to achieve the rule

Similarly to [CS0659 'class' overrides Object.Equals(object o) but does not override Object.GetHashCode()](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0659?f1url=%3FappId%3Droslyn%26k%3Dk(CS0659)), there should be a rule requiring overriding `Equals(object)` when implementing `IEquatable<T>`.

**Comment by stephentoub** [comment]
This already exists:
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1067
