### ISSUE TITLE
ProcessStartInfo.Verbs doesn't show all possible verbs

### ISSUE THREAD

**Issue by robertmuehsig** [dotnet/runtime#52960]
### Description

I noticed that not all available `Verbs` are detected correctly. Example:

If I try to open a specific .docx file like this:

```
string path = "C:\\Users\\muehsig\\AppData\\Local\\Temp\\test.docx"
var info = new ProcessStartInfo(path);
```

The "resulting" List of verbs is this:
![image](https://user-images.githubusercontent.com/756703/118784660-7e60b300-b890-11eb-960d-b5e00537f83b.png)

The "missing" verb that I try to find is the "New" verb. 

The Windows Explorer itself seems to recognize it correctly:

![image](https://user-images.githubusercontent.com/756703/118784958-b23bd880-b890-11eb-8f1d-cd03f2376d0d.png)

I found 2 stackoverflow questions with a similar issue and on answer was, that the "Verbs" property is more or less broken:

* https://stackoverflow.com/questions/31809435/get-list-of-available-verbs-file-association-to-use-with-processstartinfo-in-c
* https://stackoverflow.com/questions/51282565/processstartinfo-verbs-for-png-and-jpg-are-only-printto

Even if the `Verbs` property doesn't show the "New" verb, it is totally fine to execute the process with the "New" verb. 

I couldn't find a "Remarks" section for this issue in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.verbs?view=net-5.0) and I'm not sure if this is a "bug" or "by design" - at least it should be documented, that the list is not accurate.

### Configuration

* .NET Framework 4.7.2
* Windows 10 Version 1909
* x64
* Office 365 installed (otherwise .docx would be unkown I guess)

**Comment by pinkfloydx33** [comment]
I don't have an answer for *why* but if you look at the source code your first SO link points to (and the code in the second answer on that question), "new" is explicitly skipped when populating the list of verbs.

https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.Win32.cs#L38-L41

**Comment by danmoseley** [comment]
Note that you can improve docs yourself if you like (click pencil icon on the topic). Docs are not tracked in this repo unless they're generated from the code (which some are)

**Comment by robertmuehsig** [comment]
Yep, but I wanted to make sure if the statement is correct that this list doesn't include all possible verbs and some are missing (e.g. "new") on purpose.

**Comment by danmoseley** [comment]
I suspect we do not know the answer. @jkotas can you remember any context from long ago?

**Comment by jkotas** [comment]
I do not know for sure why `new` is skipped here. It has been like that since .NET Framework 1.0. My guess is that the `new` verb is special: It does not make sense to apply it to the existing item like the other verbs because it is meant to create new item.

> this list doesn't include all possible verbs and some are missing (e.g. "new") on purpose.

Yes, the `new` is clearly special cased. The other verbs are missing since this code was written a long before Windows 8 and the new ways to discover the verbs existed.

**Comment by KalleOlaviNiemitalo** [comment]
[ShellNew](https://docs.microsoft.com/en-us/windows/win32/shell/context#extending-the-new-submenu) is a separate Registry key though.

**Comment by adamsitnik** [comment]
Since this seems to be by-design, the docs have been updated (https://github.com/dotnet/dotnet-api-docs/pull/6841) and changing it would be a braking change, I am going to close the issue.

@robertmuehsig big thanks for updating our docs!
