### ISSUE TITLE
Support arrays in `mono_reflection_create_custom_attr_data_args_noalloc`

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#52977]
`mono_reflection_create_custom_attr_data_args_noalloc` does not currently support arrays. If a custom attribute has an array field/property, the non-AOT-compatible version that creates managed objects (`mono_reflection_create_custom_attr_data_args`) needs to be used instead. The `_noalloc` version should be updated to allow for improved AOT support.

When this is done, reading of `UnmanagedCallConvAttribute` should use this functionality.

cc @lambdageek @CoffeeFlux

**Comment by lambdageek** [comment]
This is going to be slightly painful, but doable - I wonder if we should actually make `_noalloc` default and then make a wrapper that converts an unmanaged version of the data into managed objects.

Something like

```c
typedef struct MonoCustomAttrValueArray MonoCustomAttrValueArray;

typedef struct MonoCustomAttrValue {
  union {
    gpointer prim; /* int/enum/MonoType*/string */
    MonoCustomAttrValueArray *array_val;
  }
} MonoCustomAttrValue;

struct MonoCustomAttrValueArray {
  int len;
 MonoCustomAttrValue values[MONO_ZERO_LEN_ARRAY];
};

/* returns a prim value directly, or a MonoCustomAttrValueArray* for arrays.  Allocated from allocator, or g_malloc if allocator is NULL. */
gpointer load_cattr_value (MonoMemoryManager *allocator, MonoType *type, char *p, char *boundp, char **endp, MonoError *error);

/* convert a native custom attribute value into a managed representation. returns FALSE if the value is a primitive and doesn't need conversion, or TRUE if conversion was performed and *out_obj is the result */
gboolean convert_cattr_value_to_object (gpointer val, MonoType *type, MonoObject **out_obj);
```

Something like this.

**Comment by lambdageek** [comment]
This affects the `CallConv` property of `[UnmanagedCallersOnly]` which makes it difficult to use function pointers with Mono AOT on Windows (where we need to often specify a non-default CallConv) /cc @lateralusX

**Comment by lambdageek** [comment]
We should do a more targeted solution since this is primarily affecting the AOT compiler when we're looking for well-known attributes like `UnmanagedCallersOnly` where we know it's always a `Type[]` value on a property.

So we could add a load cattr value function as I suggest above, but we wouldn't have to update all existing callers, and we could focus on just the attribute value types that we expect to see there.
