### ISSUE TITLE
structreturn test regression.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#52988]
After https://github.com/dotnet/runtime/pull/52288 JIT\Directed\StructABI\structreturn is failing on all platforms with:
```
BEGIN EXECUTION
 "D:\Sergey\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe"  structreturn.dll
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at TestHFAandHVA.TestReturnViaThrowing[T]() in structreturn.dll:token 0x6000077+0x0
   at TestHFAandHVA.TestThrowing() in structreturn.dll:token 0x6000078+0x0
   at TestHFAandHVA.TestReturnVectorT() in structreturn.dll:token 0x6000079+0x141
   at TestHFAandHVA.Test() in structreturn.dll:token 0x600008a+0xa
   at TestStructs.Main() in structreturn.dll:token 0x6000095+0xf
Expected: 100
Actual: -532462766
```
[Example1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1145376&view=ms.vss-test-web.build-test-results-tab&runId=34686562&paneView=debug&resultId=107583), [example1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1145895&view=ms.vss-test-web.build-test-results-tab)stress mode is not required.

PTAL @tannergooding , @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
I think we should make all the StructABI tests pri-0

**Comment by tannergooding** [comment]
Will take a look.

**Comment by sandreenko** [comment]
closing in favor of https://github.com/dotnet/runtime/issues/52954
