### ISSUE TITLE
compile crossgen2 itself with crossgen2 and trimming. 

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#52996]
Now that crossgen2 has replaced original crossgen would be good to enable precompilation + trimming for the tool to reduce the package size.

**Comment by AntonLapounov** [comment]
We do precompile crossgen2; however, it is not trim-compatible at present, because it uses COM to invoke the native DiaSymReader in order to generated PDBs.

**Comment by AntonLapounov** [comment]
WIP: #56787

**Comment by davidwrighton** [comment]
This is now done. We actually compile with NativeAOT which is even better.
