### ISSUE TITLE
libgomp conflict on Linux arm64

### ISSUE THREAD

**Issue by xsacha** [dotnet/runtime#53002]
### Description

On net 5.0.5, using ARM64 Ubuntu 18.04 (Jetson NX), I was getting a failed library load for a native library.
I isolated the issue to the usage of the system libgomp.so.1 in my native library, which conflicts with the OMP usage within net5.

### Configuration

.NET 5.0.5
Ubuntu 18.04 (Jetson NX)
ARM64
It is specific to this configuration. Does not affect x64 Ubuntu, CentOS or other platforms I tested.

### Regression?

This issue does not occur on .NET Core 3.1 or below. It started when I switched to .NET 5

### Other information

Workaround:
I start my program with the following environment variable to workaround the issue:
LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1

**Comment by jkotas** [comment]
cc @mthalman

**Comment by joperezr** [comment]
ping @mthalman is there anything we can do here?

**Comment by janvorli** [comment]
@xsacha I am not aware of .NET itself using libomp. None of the shared libraries that are part of .NET runtime references that library. I've just checked all of them with ldd. So I wonder what in your case has pulled it in. Do you happen to use some 3rd party component?

**Comment by janvorli** [comment]
Oh, maybe you are using ML.NET? That component seems to have a dependency on libomp.

**Comment by xsacha** [comment]
I'm not using ML.NET and the dependency seems to disappear if I go back to .NET Core 3.1

**Comment by janvorli** [comment]
Ok, then there should be no dependency on the omp. I've double checked with the 5.0.5 version and none of our shared libraries reference it directly. If you cd into the shared/Microsoft.NETCore.App/5.0.5 subdirectory of the .NET installation and run `ldd *.so`, can you see the libomp listed on your device?

**Comment by xsacha** [comment]
I don't see it with ldd either. It must be a runtime dependency.

**Comment by janvorli** [comment]
Could you please try to enable debugging of dynamic libraries loading using the `LD_DEBUG` env variable and share the output (ideally as a gist) after running your app with the failure? You'd just put `LD_DEBUG=all LD_DEBUG_OUTPUT=lddebuglog.txt ` into the command line in front of your command to launch your app, so e.g. `LD_DEBUG=all LD_DEBUG_OUTPUT=lddebuglog.txt dotnet myapp.dll`.

**Comment by xsacha** [comment]
Can I use LD_DEBUG=lib instead because that one is absolutely massive and does not appear to be ending

**Comment by janvorli** [comment]
Let's try `LD_DEBUG=files,libs` then

**Comment by xsacha** [comment]
This is the log without LD_PRELOAD set: https://pastebin.com/Fig9pAjX (Fails with .NET5)
This is the log with LD_PRELOAD set: https://pastebin.com/2MLWcG1B (Succeeds with .NET5)

**Comment by janvorli** [comment]
It seems that it is only pulled in because it is referenced by the /usr/local/lib64/Imagus/libc10.so. I don't see any other reference or an attempt to load it dynamically in the failing case. And it is actually looking for it at /usr/lib/aarch64-linux-gnu/libgomp.so.1.
In the second case with the preload, the libgomp is actually referenced as needed by another binary, the /usr/local/bin/Imagus.Configuration.Service.

Could you please dump dependencies of those two files (/usr/local/lib64/Imagus/libc10.so and /usr/local/bin/Imagus.Configuration.Service) using `ldd -r`? Please note the `-r` that will show undefined symbols if any.

My wild guess is that the preload just fixes loading of one of your binaries that don't explicitly reference the libgomp, but need some symbols from it.

**Comment by xsacha** [comment]
jane@jane-desktop:~$ ldd -r /usr/local/lib64/Imagus/libc10.so 
        linux-vdso.so.1 (0x0000007fb34bd000)
        libnuma.so.1 => /usr/lib/aarch64-linux-gnu/libnuma.so.1 (0x0000007fb33c3000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007fb322f000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007fb3175000)
        libgomp.so.1 => /usr/lib/aarch64-linux-gnu/libgomp.so.1 (0x0000007fb3138000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007fb3114000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007fb30e8000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007fb2f8f000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fb3492000)

jane@jane-desktop:~$ ldd -r /usr/local/bin/Imagus.Configuration.Service 
        linux-vdso.so.1 (0x0000007f8e1f7000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f8e159000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f8e144000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f8dfb0000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f8def6000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f8ded2000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8dd79000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f8e1cc000)

**Comment by janvorli** [comment]
Ok, thank you. I have a couple of additional questions:
* What is the actual error you are seeing when you run your application without the LD_PRELOAD?
* How did you figure out it is related to the libgomp?
* Does the version with .NET 3.1 still work on the same machine? Could you please share the same LD_DEBUG log (`LD_DEBUG=files,libs`) for that version?

**Comment by xsacha** [comment]
I see no errors when running it. It just hard crashes. When debugging it with gdb, I had a look at where it crashed and noticed it was always in

Thread 62 ".NET ThreadPool" received signal SIG34, Real-time event 34.
[Switching to Thread 0x7e13fff150 (LWP 16556)]
0x0000007fb7602ad8 in ?? () from /usr/share/imagus-people/libcoreclr.so

when trying to resolve the native dependencies. I looked up related issues online and found someone suggesting to use the LD_PRELOAD.

I had the exact same version working on the same machine (It's Jetson so the software hasn't changed in ages) but since having this issue, I have since changed our software to use latest EFCore features. I can find the version again that ran on both but the LD_DEBUG was largely uneventful and just worked when on .NET Core 3.1.

**Comment by janvorli** [comment]
I am sorry for not responding earlier, I have just got back from three weeks of my vacation. The signal above is not a problem, .NET uses that signal internally. You need to tell GDB to not to break in on that signal using the following command:
```
handle SIG34 nostop noprint
```

**Comment by qmfrederik** [comment]
I'm seeing a similar issue on aarch64 hardware (rpi4), after upgrading to .NET 6.0.

```
---- System.DllNotFoundException : Unable to load shared library 'libavcodec.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /lib/aarch64-linux-gnu/libgomp.so.1: cannot allocate memory in static TLS block
```

@xsacha Do you also get the "cannot allocate memory in static TLS block" error message?

This failure is in a unit test and the failure correlates with the upgrade to .NET 6.0. We're seeing this on Ubuntu 20.04.

Is it possible that static TLS memory is a constrained resource, and that new versions of .NET use a bit more of that memory than previous versions? Could that lead to insufficient memory being available when libgomp is being loaded (which may explain why LD_PRELOAD works, since that would load libgomp first)?

**Comment by qmfrederik** [comment]
These links seems to support the hypothesis that thread local storage is a scarce resource on aarch64, and it would be interesting to know if newer versions of .NET consume more thread local storage than previous versions.

- https://patchwork.ozlabs.org/project/glibc/patch/20140514203250.GK26038@redacted.bos.redhat.com/
- https://bugzilla.redhat.com/show_bug.cgi?id=1722181

**Comment by xsacha** [comment]
I don't remember seeing that part of the message but it's possible. I am also using your dotnet-packaging.
Thanks for expanding on this issue. I've just been using LD_PRELOAD for arm64 so far. All my applications appear to require it since .NET 5.

**Comment by qmfrederik** [comment]
> I've just been using LD_PRELOAD for arm64 so far.

If you have the time, could you try without LD_PRELOAD and see if the error message is TLS-related? If it is not, sorry for hijacking your issue ;-).

> Now I'm worried if it's a constrained static TLS size, has the issue been moved to a different libraries by preloading gomp?

I haven't been able to confirm yet it's related to thread local storage. But I think it is. In that case, I would assume that another library somehow gracefully handles the error condition, instead of failing like libgomp?

This thread goes into more detail: https://sourceware.org/legacy-ml/libc-alpha/2019-09/msg00512.html; https://sourceware.org/bugzilla/show_bug.cgi?id=25051 seems to introduce an option (`rtld.optional_static_tls`) to make the amount of "surplus" static TLS bytes tunable.

I'm going to run a test on Ubuntu 21.10 to see if it makes a difference.

**Comment by xsacha** [comment]
It does sound like it's the same issue. I'll confirm today. Unfortunately the Jetson devices are stuck on Ubuntu 18.04 right now so any new Ubuntu changes that mitigate this wouldn't be feasible.

**Comment by danmoseley** [comment]
@xsacha @qmfrederik is this issue still useful?

**Comment by xsacha** [comment]
I understand the issue still happens in .NET 6.0 but is likely not directly related to .NET but rather the TLS size.
Unfortunately Jetson is still stuck on Ubuntu 18.04 where I face this issue but the LD_PRELOAD workaround has been working so far.

**Comment by ViktorHofer** [comment]
@jeffhandley I don't think belongs in area-Infrastructure, at least this isn't actionable on our side.

**Comment by jkotas** [comment]
@janvorli Can we check how much TLS is consumed by .NET runtime - just to make sure that it is reasonable?

Otherwise, I think this can be closed. There is not much we can do about this in .NET runtime.

**Comment by jkotas** [comment]
These sizes are like 2x more than I would expect. Could you please dump the symbols from the TLS section so that we can tell where it is coming from?

**Comment by janvorli** [comment]
Here are the numbers from 
This is for coreclr:
```
0000000000000000 l       .tbss  0000000000000008              .hidden t_pOwnedCrstsChain
0000000000000018 l       .tbss  0000000000000008              .hidden t_pCurrentExceptionContext
0000000000000010 l       .tbss  0000000000000008              .hidden t_pCurrentExceptionRecord
0000000000000008 l       .tbss  0000000000000004              .hidden t_dwCurrentExceptionCode
0000000000000020 l       .tbss  0000000000000008              .hidden t_cbILJittedForThread
0000000000000028 l       .tbss  0000000000000008              .hidden t_cMethodsJittedForThread
0000000000000030 l       .tbss  0000000000000008              .hidden t_c100nsTicksInJitForThread
0000000000000048 l       .tbss  0000000000000018              .hidden gCurrentThreadInfo
0000000000000038 l       .tbss  0000000000000004              .hidden t_ForbidGCLoaderUseCount
0000000000000040 l       .tbss  0000000000000008              .hidden t_pStackWalkerWalkingThread
0000000000000060 l       .tbss  0000000000000008              .hidden t_ThreadType
0000000000000068 l       .tbss  0000000000000008              .hidden t_CantStopCount
0000000000000070 l       .tbss  0000000000000004              .hidden CHECK::t_count
0000000000000074 l       .tbss  0000000000000004              .hidden t_CantAllocCount
0000000000000078 l       .tbss  0000000000000008              .hidden StressLog::t_pCurrentThreadLog
0000000000000080 l       .tbss  0000000000000001              .hidden t_triedToCreateThreadStressLog
0000000000000081 l       .tbss  0000000000000001              BinderTracing::t_AssemblyLoadStartInProgress
0000000000000090 l       .tbss  0000000000000001              __tls_guard
0000000000000088 l       .tbss  0000000000000008              .hidden EventPipeCoreCLRThreadHolderTLS::g_threadHolderTLS
0000000000000092 l       .tbss  0000000000000001              __tls_guard
0000000000000091 l       .tbss  0000000000000001              .hidden tls_destructionMonitor
00000000000000a0 l       .tbss  0000000000000030              PAL_ThrowExceptionFromContext::threadLocalExceptionStorage
00000000000000d0 l       .tbss  0000000000000008              t_nativeExceptionHolderHead
00000000000000d8 l       .tbss  0000000000000008              .hidden THREADSilentGetCurrentThreadId()::tid
00000000000000e0 l       .tbss  0000000000000008              tls_cache
00000000000000e8 l       .tbss  0000000000000004              tls_cache_destroyed
00000000000000f0 l       .tbss  0000000000000008              tls_cache
00000000000000f8 l       .tbss  0000000000000004              tls_cache_destroyed
```

And this for JIT:
```
0000000000000000 l       .tbss  0000000000000008              .hidden gJitTls
0000000000000008 l       .tbss  0000000000000004              .hidden CHECK::t_count
000000000000000c l       .tbss  0000000000000004              .hidden t_CantAllocCount
0000000000000010 l       .tbss  0000000000000008              .hidden StressLog::t_pCurrentThreadLog
0000000000000018 l       .tbss  0000000000000001              .hidden t_triedToCreateThreadStressLog
0000000000000020 l       .tbss  0000000000000008              .hidden t_ThreadType
0000000000000030 l       .tbss  0000000000000030              PAL_ThrowExceptionFromContext::threadLocalExceptionStorage
0000000000000060 l       .tbss  0000000000000008              t_nativeExceptionHolderHead
0000000000000068 l       .tbss  0000000000000008              .hidden THREADSilentGetCurrentThreadId()::tid

```

**Comment by jkotas** [comment]
I was missing the PAL exception handling, but that is hard to fix. It is part of the larger problem of eliminating the PAL.
