### ISSUE TITLE
.Net 5 linq2db supported version

### ISSUE THREAD

**Issue by sarabu07** [dotnet/runtime#53060]
Could you tell me what is the linq2db version i need to use to start integration with .Net 5? Right now we are using linq2db 3.1.0 with .Net 5 and getting "Connection request timed out" error when connecting to oracle autonomous database. .Net core 3.1 code is working good connecting to same database.

**Comment by jkotas** [comment]
https://github.com/linq2db/linq2db repo is the place to ask this question. Could you please ask there instead?
