### ISSUE TITLE
PEReader.GetPESectionBlock() cache ineffective (calls mmap+munmap for every call)

### ISSUE THREAD

**Issue by dgrunwald** [dotnet/runtime#53080]
### Description

In https://github.com/icsharpcode/ILSpy/issues/2416, @tellowkrinkle observed unexpected significant disk I/O when decompiling with ilspycmd.
ilspycmd uses System.Reflection.Metadata to read the assembly being decompiled. Due to the caching bug described below, reading 14 MB of assemblies requires 6.5 GB of disk I/O.

### Configuration

@tellowkrinkle originally observed the problem on MacOS; but we've managed to reproduce it on Linux ubuntu 5.8.0-44-generic x86_64.
.NET runtime is version 3.1.15; but System.Reflection.Metadata.dll is used via NuGet in version 5.0.0.

### Data

strace shows a large number of syscalls:
```
mmap(NULL, 1143380, PROT_READ, MAP_SHARED, 40, 0) = 0x7f5ab4554000
madvise(0x7f5ab4554000, 1143380, MADV_DONTFORK) = 0
msync(0x7f5ab4554000, 1142356, MS_SYNC|MS_INVALIDATE) = 0
munmap(0x7f5ab4554000, 1143380)         = 0
```
This sequence of syscalls seems to repeat once for each call to `System.Reflection.Metadata.PEReaderExtensions.GetMethodBody`.
The `msync` call seems to flush the disk cache -> every single call to `GetMethodBody` ends up performing disk I/O.

Setting a breakpoint on `msync` shows that it is called from the following stack:
```
(lldb) clrstack
OS Thread Id: 0x2044 (1)
        Child SP               IP Call Site
00007FFFFFFFA4D0 00007ffff7fa5960 [InlinedCallFrame: 00007fffffffa4d0] Interop+Sys.MSync(IntPtr, UInt64, MemoryMappedSyncFlags)
00007FFFFFFFA4D0 00007fff7e9b8683 [InlinedCallFrame: 00007fffffffa4d0] Interop+Sys.MSync(IntPtr, UInt64, MemoryMappedSyncFlags)
00007FFFFFFFA4C0 00007FFF7E9B8683 ILStubClass.IL_STUB_PInvoke(IntPtr, UInt64, MemoryMappedSyncFlags)
00007FFFFFFFA550 00007FFF7E5B9ACB System.IO.MemoryMappedFiles.MemoryMappedView.Flush(UIntPtr) [/_/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedView.Unix.cs @ 147]
00007FFFFFFFA5A0 00007FFF7E5B9A24 System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Flush() [/_/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedViewAccessor.cs @ 71]
00007FFFFFFFA5C0 00007FFF7E5B994C System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Dispose(Boolean) [/_/src/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedViewAccessor.cs @ 41]
00007FFFFFFFA5F0 00007FFF7D830C5D System.IO.UnmanagedMemoryAccessor.Dispose() [/_/src/System.Private.CoreLib/shared/System/IO/UnmanagedMemoryAccessor.cs @ 120]
00007FFFFFFFA610 00007FFF7E9B7FB4 System.Reflection.Internal.MemoryMappedFileBlock+DisposableData.Release() [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/MemoryBlocks/MemoryMappedFileBlock.cs @ 49]
00007FFFFFFFA630 00007FFF7E9B7F04 System.Reflection.Internal.MemoryMappedFileBlock+DisposableData.Release()
00007FFFFFFFA670 00007FFF7E9B7DA0 System.Reflection.Internal.CriticalDisposableObject.Dispose() [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/Utilities/CriticalDisposableObject.cs @ 13]
00007FFFFFFFA690 00007FFF7E9B7C74 System.Reflection.Internal.MemoryMappedFileBlock.Dispose() [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/MemoryBlocks/MemoryMappedFileBlock.cs @ 67]
00007FFFFFFFA6B0 00007FFF7E9B7B63 System.Reflection.PortableExecutable.PEReader.GetPESectionBlock(Int32) [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs @ 416]
00007FFFFFFFA760 00007FFF7E9B7850 System.Reflection.PortableExecutable.PEReader.GetSectionData(Int32) [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs @ 485]
00007FFFFFFFA7F0 00007FFF7E9B76E8 System.Reflection.Metadata.PEReaderExtensions.GetMethodBody(System.Reflection.PortableExecutable.PEReader, Int32) [/_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/PEReaderExtensions.cs @ 31]
00007FFFFFFFA8B0 00007FFF7E9B62A0 ICSharpCode.Decompiler.CSharp.CSharpDecompiler.ReadCodeMappingInfo(ICSharpCode.Decompiler.Metadata.PEFile, ICSharpCode.Decompiler.Metadata.CodeMappingInfo, System.Reflection.Metadata.MethodDefinitionHandle, System.Reflection.Metadata.MethodDefinitionHandle, System.Collections.Generic.Queue`1<System.Reflection.Metadata.MethodDefinitionHandle>, System.Collections.Generic.HashSet`1<System.Reflection.Metadata.TypeDefinitionHandle>) [/home/siegfried/ILSpy/ICSharpCode.Decompiler/CSharp/CSharpDecompiler.cs @ 673]
```

### Analysis

The caching logic in https://github.com/dotnet/runtime/blob/202c9fd3463ada7094762eb1274d948c5dd78bc7/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L377 is broken:
there is a "cache miss" code path that creates a new `AbstractMemoryBlock` and caches it; but there is no "cache hit" code path that returns the existing `AbstractMemoryBlock` without allocating a new one.
For each index only the first-created `AbstractMemoryBlock` is returned to the caller, but every additional call to `GetPESectionBlock` unnecessarily creates+disposes an additional `AbstractMemoryBlock`.
The code path commented as `// another thread created the block already, we need to dispose ours:` ends up running all the time, even in single-threaded code!
When `PEStreamOptions.PrefetchEntireImage` is not in use, this triggers additional syscalls.

Also, I don't see a good reason for calling `msync` at all, given that the file is mapped read-only.

**Comment by krwq** [comment]
@dgrunwald do you feel like sending PR with the fix? Do you have a simpler repo perhaps which doesn't involve ilspycmd?

**Comment by dgrunwald** [comment]
It reproduces with this short program (full project: [SRMPerfTest.zip](https://github.com/dotnet/runtime/files/6804399/SRMPerfTest.zip)):
```c#
using System;
using System.IO;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

using var fs = new FileStream(typeof(PEReader).Assembly.Location, FileMode.Open);
using var pe = new PEReader(fs, PEStreamOptions.Default);
var reader = pe.GetMetadataReader();
int totalMethodSizes = 0;
int numMethodBodies = 0;
foreach (var mh in reader.MethodDefinitions)
{
    var md = reader.GetMethodDefinition(mh);
    if (md.RelativeVirtualAddress != 0)
    {
        var body = pe.GetMethodBody(md.RelativeVirtualAddress);
        totalMethodSizes += body.Size;
        numMethodBodies++;
    }
}
Console.WriteLine($"numMethodBodies = {numMethodBodies}");
Console.WriteLine($"totalMethodSizes = {totalMethodSizes}");
```

Publish for linux, and run:
```
$ ./SRMPerfTest
numMethodBodies = 3355
totalMethodSizes = 148711
$ strace ./SRMPerfTest |& grep msync | wc -l
3356
```

There's one msync call when loading the metadata from the assembly, and then another call for each method body.
For me the program takes 3.35s counting the method bodies in System.Reflection.Metadata.dll.

The bug can be worked around by using `PEStreamOptions.PrefetchEntireImage`. This avoids the `msync` calls completely and reduces the run-time to 2.24s. I think the `msync` doesn't actually flush the disk cache on Linux (unlike what was reported on MacOS, which I can't test on) so the performance impact isn't as catastrophic.

I believe the fix would be something like this change to `PEReader.GetPESectionBlock`:
```diff
            if (_lazyPESectionBlocks == null)
            {
                Interlocked.CompareExchange(ref _lazyPESectionBlocks, new AbstractMemoryBlock[PEHeaders.SectionHeaders.Length], null);
            }

+         var exitingBlock = Volatile.Read(ref _lazyPESectionBlocks[index]);
+         if (existingBlock != null) return existingBlock;

            AbstractMemoryBlock newBlock;
```
but I haven't tested that yet.

**Comment by tellowkrinkle** [comment]
> The bug can be worked around by using `PEStreamOptions.PrefetchEntireImage`. This avoids the `msync` calls completely and reduces the run-time to 2.24s. I think the `msync` doesn't actually flush the disk cache on Linux (unlike what was reported on MacOS, which I can't test on) so the performance impact isn't as catastrophic.

Testing on MacOS, I got permission errors trying to open the file in place, so I copied it to `/tmp/` (and then to an SD card).
```
SSD     | PEStreamOptions.Default             |  2.2s
SSD     | PEStreamOptions.PrefetchEntireImage |  0.074s
SD Card | PEStreamOptions.Default             | 13.7s
SD Card | PEStreamOptions.PrefetchEntireImage |  0.09s
```

**Comment by krwq** [comment]
@dgrunwald @tellowkrinkle any chance you could try the proposed fix above and see the numbers? Would be nice to see the comparison run on the same machine.
