### ISSUE TITLE
[HTTP/3] Disabled test classes 

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#53093]
In HTTP functional tests, there is 3 places where the whole test classes are suppressed with `#if false`:
- **Cookies**: `SocketsHttpHandlerTest_Cookies_Http3_MsQuic` and `SocketsHttpHandlerTest_Cookies_Http3_Mock`
- ~~**Cancellation**: `SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_MsQuic` and `SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_Mock`~~ -> #54727
- ~~**AltSvc**: `SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3_MsQuic` and `SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3_Mock`~~ -> #53786

This issue is to serve as a reminder to investigate and either fix or delete the tests. This issue can be split into separate ones for individual problems.

**Comment by geoffkizer** [comment]
Reopened since I'm disabling the cookie tests again.

**Comment by karelz** [comment]
Triage: Cookie tests blocked on #55025
