### ISSUE TITLE
HotReload fails when building library tests

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#53091]
### Repro

1. Clone https://github.com/dotnet/runtime
2. Run `.\build.cmd -subset clr+libs+libs.tests -c Release`

The build eventually fails with:
```
'C:\Program' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\tagoo\.nuget\packages\microsoft.dotnet.hotreload.utils.generator.buildtool\1.0.1-alpha.0.21267.1\build\Microsoft.DotNet.HotReload.Utils.Generator.BuildTool.targets(56,5): error MSB3073: The command "C:\Program Files\dotnet\dotnet.exe C:\Users\tagoo\.nuget\packages\microsoft.dotnet.hotreload.utils.generator.buildtool\1.0.1-alpha.0.21267.1\build\\..\tools\net6.0\Microsoft.DotNet.HotReload.Utils.Generator.BuildTool.dll -msbuild:C:\Users\tagoo\Source\repos\runtime\src\libraries\System.Runtime.Loader\tests\ApplyUpdate\System.Reflection.Metadata.ApplyUpdate.Test.MethodBody1\System.Reflection.Metadata.ApplyUpdate.Test.MethodBody1.csproj -script:C:\Users\tagoo\Source\repos\runtime\src\libraries\System.Runtime.Loader\tests\ApplyUpdate\System.Reflection.Metadata.ApplyUpdate.Test.MethodBody1\deltascript.json -p:Configuration=Release" exited with code 9009. [C:\Users\tagoo\Source\repos\runtime\src\libraries\System.Runtime.Loader\tests\ApplyUpdate\System.Reflection.Metadata.ApplyUpdate.Test.MethodBody1\System.Reflection.Metadata.ApplyUpdate.Test.MethodBody1.csproj]
```

### Expected Behavior

The build should succeed and not fail because `dotnet.exe` is installed into the default location

**Comment by tannergooding** [comment]
This looks to be failing because `HotReload` runs `<Exec Command="$(_HotReloadDeltaGeneratorCommand) $(_HotReloadDeltaGeneratorArgs)" />`, where `<_HotReloadDeltaGeneratorCommand>$(DotNetTool) $(_HotReloadDeltaGeneratorPath)</_HotReloadDeltaGeneratorCommand>`.

I'd expect that `DotNetTool` should be properly quoted for this to work.

**Comment by ViktorHofer** [comment]
Was fixed with https://github.com/dotnet/hotreload-utils/pull/27 and the fix will be ingested with https://github.com/dotnet/runtime/pull/52967. Thanks for reporting though 👍
