### ISSUE TITLE
Add ConsoleColor.Unknown

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#53099]
## Background and Motivation

Currently, on Linux, Console.BackgroundColor (and probably ForegroundColor probably too) can return -1 which is currently not a valid enum value.
The unknown ConsoleColor value is set there: https://source.dot.net/#System.Console/System/Console.cs,319

## Proposed API

```diff
public enum ConsoleColor
{
+   Unknown = -1,
    Black = 0,
```

## Usage Examples

``` C#
if(Console.BackgroundColor == ConsoleColor.Unknown)
{
    // Special handling.
} else {
     // Regular handling.
}
```

## Alternative Designs

An alternative option would be to not leak the Unknown ConsoleColor.  (But I doubt it's possible.)

## Risks

This would break the following code:  

```csharp
if( !Enum.IsDefined( typeof(ConsoleColor), System.Console.BackgroundColor ) )
    System.Console.BackgroundColor = ConsoleColor.Black;
```

## Note

If this proposal is not accepted, it would be nice to mention in the docs of Background/ForegroundColor that it may return (ConsoleColor)-1.

**Comment by Kuinox** [comment]
I found this commit comment:  
https://github.com/dotnet/runtime/commit/49de936d58c0da9bcd68c8236168cb29645920f2  
> We use a value of (ConsoleColor)(-1) to represent an unknown color.  This is not added to the contract so that a) we don't cause problems for existing implementations, and b) we don't encourage the usage of a new Unknown value that's really meant to be an implementation detail.  
Which explain why there is no `ConsoleColor.Unknown` currently.

**Comment by danmoseley** [comment]
Given that explanation do you want to close?

**Comment by Kuinox** [comment]
There is no doc about this, the only piece of information about this behavior I found was the commit message:  
Should I close this and open another issue asking for the docs, or rewrite this issue ?

**Comment by danmoseley** [comment]
@Kuinox issues with the API docs are tracked in dotnet/dotnet-api-docs repo for most libraries. We are migrating to generating them from XML doc comments in this repo and others but that hasn't been done for System.Console (https://github.com/dotnet/runtime/issues/48959).

The quickest way to update the docs is to click the "pencil" Edit button in the top right of the topics eg https://docs.microsoft.com/en-us/dotnet/api/system.console.backgroundcolor?view=net-5.0. Then you can edit directly and create a PR. Given you need to change two topics, you might prefer to edit and create a PR in the usual way so you have a single PR here.

**Comment by Kuinox** [comment]
Ok, I opened https://github.com/dotnet/dotnet-api-docs/pull/6795.

**Comment by danmoseley** [comment]
Thanks!
