### ISSUE TITLE
[Android] System.Diagnostics.Process LongProcessNamesAreSupported Fails

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#53095]
Failures in Runfo in last 30 days as of 9/23:
Day | Run | OS
-- | -- | --
9/22 | Rolling run [26785](https://runfo.azurewebsites.net/view/build/?number=26785) | net7.0-Linux-Release-x64-CoreCLR_checked-(Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open

net7.0-Linux-Release-x64-CoreCLR_checked-(Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open - [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2f9c0a9a463943b991/System.Diagnostics.Process.Tests/1/console.c446c4aa.log?%3Fhelixlogtype%3Dresult) - 9/22:
```
    System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported [FAIL]
      Assert.Contains() Failure
      Not found: (filter expression)
      In value:  Process[] [System.Diagnostics.Process (helix_docker_work.sh), System.Diagnostics.Process (execute.sh), System.Diagnostics.Process (bash), System.Diagnostics.Process (dotnet), System.Diagnostics.Process (123456789012345)]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs(2221,0): at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Android Arm and Arm64
```
System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported
Assert.Contains() Failure
Not found: (filter expression)
In value:  Process[] [System.Diagnostics.Process (s.Process.Tests), System.Diagnostics.Process (sleep)
at System.Diagnostics.Tests.ProcessTests.LongProcessNamesAreSupported() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 2128
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004a27+0x6a

**Comment by steveisok** [comment]
This seems to be API level specific. Will revisit when we bump the api level on devices.

**Comment by karelz** [comment]
Looks generic, not specific to Android -- marking for re-triage

**Comment by Jozkee** [comment]
The runfo log is no longer useful so will close for now until a new hit appears. When that happens, it is likely that the quick fix would be to just disable the test for the specific config, at least until we invest into closing https://github.com/dotnet/runtime/issues/29330.
