### ISSUE TITLE
Optimizing "constant_string".Length

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#5310]
Lots of times for readability I use `"constant_string".Length` instead of `15` in my code. For example:

``` csharp
string TextAfterFoo(string s) =>
    s.Substring(s.IndexOf("Foo") + "Foo".Length); // a lot more readable than `3`
```

It would be nice if RyuJIT could optimize this as a JIT-time constant, so a string wouldn't have to actually be loaded and called `Length` on.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by EgorBo** [comment]
Implemented in https://github.com/dotnet/runtime/pull/1378
