### ISSUE TITLE
LIST ADD METHOD

### ISSUE THREAD

**Issue by NemesisWasAlienToo** [dotnet/runtime#53128]
DID YOU GUYS REALLY JUST MULTIPLIED THE NEW SIZE BY 2?!
WHY 2 YOU COULD JUST INCREASE THE SIZE BY LIKE 20 PERCENT, WOULDNT IT BE BETTER?!
this issue is in List.grow function witch is used by add.
## int newCapacity = _items.Length == 0? _defaultCapacity : _items.Length * 2;
this is not an issue i dont know what to call this

**Comment by jkotas** [comment]
> THE SIZE BY LIKE 20 PERCENT, WOULDNT IT BE BETTER?!

That depends on your scenario. 20 percent would be worse than 2x for number of scenarios.

**Comment by jeuxjeux20** [comment]
You can also use `List<T>.Capacity` and the `List<T>` constructor to set your own capacity if it's clearly a problem for your case.

**Comment by NemesisWasAlienToo** [comment]
what scenarios?
can you be more specific?
so i can avoid them and increase my perfornamce when coding?

**Comment by NemesisWasAlienToo** [comment]
> You can also use `List<T>.Capacity` and the `List<T>` constructor to set your own capacity if it's clearly a problem for your case.

Capacity function will increase the size with a 2 factor too, so whats the diffrence? am i missin smt?

**Comment by En3Tho** [comment]
Consider you have a list of 4 items, what's the minimum growth when 20% is < 0? 1 item? That means you will have 1 item resizes until you hit 10 elements and them you will have 2 item resizes until 15. And so on. Somewhere in the distant future when ai will conquer the earth you will finally get to 200 elements in your list. Do you expect this to be perfomant behaviour or what?

**Comment by EgorBo** [comment]
It's a trade-off between high memory usage vs frequency of allocations + expensive copy operations. Feel free to suggest a better way, but make sure your suggestion doesn't just improve your specific case and comes with a detailed analysis why it should be changed.

Maybe there is a way to pre-set initial capacity or the multiplier based on Profile data (PGO) somehow.

**Comment by jeuxjeux20** [comment]
> what scenarios?
> can you be more specific?
> so i can avoid them and increase my perfornamce when coding?

Can you please send us some benchmarks using BenchmarkDotNet using `List<T>` so we can see the actual performance hit? Thanks!

**Comment by eiriktsarpalis** [comment]
I would recommend sharing a benchmarks that illustrate the performance issues you are facing with the current grow function.

**Comment by WatchDogsDev** [comment]
Here is some benchmark results with 2^24 + 1 items :

![image](https://user-images.githubusercontent.com/29868640/122252003-41fc9300-cee0-11eb-9ff1-e15ffc503ee0.png)

The code:
```
    [MemoryDiagnoser]
    public class MyBenchmark
    {
        [Params(16777216 + 1)]
        public int itemsCount {get; set;}

        [Benchmark]
        public List<string> WithCapacity()
        {
            var list = new List<string>(itemsCount);

            for(int i = 0; i < itemsCount; i++)
            {
                list.Add(i.ToString());
            }

            for(int i = 0; i < itemsCount; i++)
            {
                var a = list[i];
            }

            return list;
        }

        [Benchmark]
        public List<string> WithoutCapacity()
        {
            var list = new List<string>();

            for(int i = 0; i < itemsCount; i++)
            {
                list.Add(i.ToString());
            }

            
            for(int i = 0; i < itemsCount; i++)
            {
                var a = list[i];
            }

            return list;
        }
    }
```

**Comment by danmoseley** [comment]
That doesn't seem too bad: without any knowledge of the capacity you need, it's only ~10% slower.

You may want to repeat that with a 20% multiplier (use your own copy of the List code). It may be worse.

**Comment by danmoseley** [comment]
If your concern is wasted space, you can use TrimExcess()

**Comment by WatchDogsDev** [comment]
I appreciate your help. TrimExcess is very useful.

Here is some results with lower itemCount values : 
![benchmark-1](https://user-images.githubusercontent.com/29868640/122273378-a1fe3400-cef6-11eb-909e-be2bbfa274e8.png)

But I think it should be something like this :

When capacity is lower than 32/64/128 => 4x the capacity
Then start to 2x the capacity until maybe 1,000,000
Then start to increase the capacity by 50%
And lower the capacity multiplier while it is going bigger 

This method maybe solves the high memory usage problem.
The capacity increment algorithm should be something dynamic I think.

**Comment by danmoseley** [comment]
> The capacity increment algorithm should be something dynamic I think

Maybe, but the tricky part is proving you have something that is better under many different circumstances. It is a lot of work. Is this something you want to pursue?

In the end if a scenario is so perf critical that a different strategy is clearly better, it may be best to make a custom tuned collection for that. If allocation is the concern it could use array pooling.

**Comment by WatchDogsDev** [comment]
How about this ? :)

![benchmark-3](https://user-images.githubusercontent.com/29868640/125171138-d7c9cc00-e1c7-11eb-965d-7c6f793f6ccf.png)

I think we are here to enhance DotNetCore implementations. It should go better & better, So we are just coming up with ideas.

Is there any tutorial to test my own implementation on my own system ? \
Do I need to download the whole dotnet source code ?

**Comment by eiriktsarpalis** [comment]
Hey @WatchDogsDev, assuming you need to modify `System.Collections.Generic.List<T>` itself you would need to clone, modify and build `dotnet/runtime`. We use the https://github.com/dotnet/performance repo to run benchmarks against private builds, in particular please see [this guide](https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/README.md#private-runtime-builds) for more information on how to do it. Feel free to share any findings you have with us.

In the meantime, I'm going to close this issue but feel free to reopen if any actionable findings turn up.
