### ISSUE TITLE
Test failure readytorun/tests/generics/generics.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53162]
Run: [runtime-coreclr gcstress-extra 20210522.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1151815&view=ms.vss-test-web.build-test-results-tab&runId=34825280&resultId=108504&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_zapdisable_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-a45aeeb-20190620155855

- readytorun/tests/generics/generics.sh

```
**Error message:**
```
Assert failure(PID 695 [0x000002b7], Thread: 695 [0x02b7]): (pMTReal != NULL) || !pCF->IsFrameless()
File: /__w/1/s/src/coreclr/vm/gcenv.ee.common.cpp Line: 379
Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f816ea730)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f816ea730)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f816df7f8)
/root/helix/work/workitem/readytorun/tests/generics/generics.sh: line 377:   695 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/readytorun/tests/Reports/readytorun.tests/generics/generics.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun generics.dll ''
Gathering state for process 695 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.695.dmp
Written 67010560 bytes (16360 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/readytorun/tests/generics/generics.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._generics_generics_._generics_generics_sh()
```

**Comment by VincentBu** [comment]
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-05-23T23:08:33.302Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1152327&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34837166&amp;resultId=109358&amp;paneView=debug)
2021-05-23T08:02:35.784Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1152004&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34829784&amp;resultId=109410&amp;paneView=debug)
2021-05-22T22:34:37.461Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1151815&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34825280&amp;resultId=108504&amp;paneView=debug)

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr jitstress-isas-arm 20210529.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1162985&view=ms.vss-test-web.build-test-results-tab&runId=35071530&resultId=107550&paneView=debug) with diffrent error message.

Failed test:
```
CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1100.ARM64.Open

- readytorun/tests/generics/generics.sh

```
**Error message:**
```
task_for_pid(42637) FAILED 5 (os/kern) failure
/private/tmp/helix/working/B18709B6/w/AB84092C/e/readytorun/tests/generics/generics.sh: line 377: 42637 Segmentation fault: 11  (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/B18709B6/w/AB84092C/e/readytorun/tests/Reports/readytorun.tests/generics/generics.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/B18709B6/p/corerun generics.dll ''
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/B18709B6/p
/private/tmp/helix/working/B18709B6/w/AB84092C/e/readytorun/tests/generics/generics.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._generics_generics_._generics_generics_sh()
```

**Historical failures of this test has updated in this [comment](https://github.com/dotnet/runtime/issues/53162#issuecomment-846813144).**

**Comment by mangod9** [comment]
I am guessing this is with crossgen and not crossgen2. Please reopen if this continues to repro after replacing crossgen.
