### ISSUE TITLE
Move crossgen out from the tools dir and into the lib dir instead

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#5316]
Currently, the CoreCLR package puts the crossgen program under the tools directory, and because of this dotnet publish won't copy it over to the runtime. The reason why we need it is because in corefx we want to ngen the runtime we use to build the repo. Is it posible to change the nuspec to have the crossgen program under lib?

related: dotnet/buildtools#487

cc: @JohnChen0 @weshaggard

**Comment by jkoritzinsky** [comment]
With repo consolidation, the libraries build as part of the same repo as crossgen, so it isn't being used via packages. I'm going to close this for now.
