### ISSUE TITLE
Raw Blazor code can't work with VB.NET

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#53169]
### Describe the bug
I created a C# Blazor Wasm app, then translated it to VB.NET, where I erased the .razor files, and used the auto generated classes from the C# project instead *translated to VB.NET code). The project builds, but the browser shows a tip sating there is a runtime error.
So, why can't the dll generated by VB.NET work just like the one created by C#. It is the same code after all. 
- Is there am issue with VB.NET and Mono?
-  or is there some expression trees somewher that VB generates in a different way than C#, and you can't parse in Blazor engine? 
- or is there something wrong in my translated  VB code itself? 
Nite that I can write the Blazor components using VB XMl literals, then generate the classes, so, VB can work with Blazor like I did in Vazor as an alternatiove to C# Razor. But first, the raw vb blazor code should work.

### To Reproduce
The vb code is here:
https://github.com/VBAndCs/BlazorVB
I also added the C# and VB dlls if you want to compare the IL code of them.

**Comment by VBAndCs** [comment]
@javiercn 
Thanks for your response. One know issue of VB.NET is that it's expression trees has some different syntax than those of C#. I faced some issues of that in EFCore because if fails to parse some VB expression trees. 
I don't know if Blazor uses expression trees or not, so, is there any part of Blazor that can run in a similar scenario? 
If not, so, it must be something in Mono runtime that can't recognize some form of IL generated by VB.NET.

**Comment by CyrusNajmabadi** [comment]
@vbandcs does your code use expression trees?

**Comment by VBAndCs** [comment]
@CyrusNajmabadi
I am not using any thing. I just translated C# code, which contains many lambdas, some of them returns another lambdas, and I don't know exactly which of these could be an expression tree. Sp I asked the experts just to eliminate this possibility.

**Comment by CoffeeFlux** [comment]
Can you post the actual runtime error you're seeing? That should make it easier to tell what's actually causing the problem, because at least in theory VB should work fine.

**Comment by VBAndCs** [comment]
@CoffeeFlux 
The browser doesn't show any details. Just a yellow label at the bottom that an error occurred. If the details are written to desk somewhere, please tell me.  And anyway, you can compile the source ant try it. Maybe I am missing a point in the code that causes this error. I added nothing extra. Just translated the C# app that the Blazor template crates.

**Comment by lewing** [comment]
@SamMonoRT @marek-safar thoughts on what to do here?

**Comment by VBAndCs** [comment]
Can anyone at least explain what is the cause of this problem?

**Comment by VBAndCs** [comment]
It took me a while to find that this issue has been transferred to runtime.
Anyway: is there any new about this issue?

**Comment by marek-safar** [comment]
There is nothing special about VB from runtime perspective. I think we need to see what the actual error is first before moving forward.

@lewing could someone one your team try the attached repro?

**Comment by lorcQc** [comment]
It can help...
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Attributes may only be added immediately after frames of type Element or Component
System.InvalidOperationException: Attributes may only be added immediately after frames of type Element or Component
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AssertCanAddAttribute()
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddAttribute(Int32 sequence, String name, MulticastDelegate value)
   at BlazorVB.Shared.NavMenu.BuildRenderTree(RenderTreeBuilder __builder) in C:\Users\xxx\Desktop\BlazorVB-master\BlazorCs\Shared\NavMenu.razor.g.vb:line 18
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
If I remove the lines that starts with `__builder.AddAttribute` in [this method](https://github.com/VBAndCs/BlazorVB/blob/0eee320d51ff55971a0b572ac1681fba209cb20e/BlazorCs/Shared/NavMenu.razor.g.vb#L18), the three pages of the project are displayed without error.

**Comment by VBAndCs** [comment]
@lorcQc
Thanks alot. Now it works but the nav menu doesn't appear. At leat we know what to fix now.
How did you get this exception details? It doesn't even appean in the output window.

**Comment by VBAndCs** [comment]
This is the new BuildRenderTree for the NavMenu class. It works but there is something missing (maybe in resources), so the nav menu is there but unvisable. I can click its location and see the options. I will copy the resources from C# again and see.

```VB.NET
        Protected Overrides Sub BuildRenderTree(ByVal __builder As Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)
            __builder.OpenElement(0, "div")
            __builder.AddAttribute(1, "class", "top-row pl-4 navbar navbar-dark")
            __builder.AddAttribute(2, "b-i797s6suhi")
            __builder.AddMarkupContent(3, "<a class=""navbar-brand"" href b-i797s6suhi>WebApplication3</a>" & vbCrLf & "    ")
            __builder.OpenElement(4, "button")
            __builder.AddAttribute(5, "class", "navbar-toggler")
            __builder.AddAttribute(6, "onclick",
                                   EventCallback.Factory.Create(Of MouseEventArgs)(Me, AddressOf ToggleNavMenu))
            __builder.AddAttribute(7, "b-i797s6suhi")
            __builder.AddMarkupContent(8, "<span class=""navbar-toggler-icon"" b-i797s6suhi></span>")
            __builder.CloseElement()
            __builder.CloseElement()
            __builder.AddMarkupContent(9, vbCrLf & vbCrLf)
            __builder.OpenElement(10, "div")
            __builder.AddAttribute(11, "class", NavMenuCssClass)
            __builder.AddAttribute(12, "onclick", EventCallback.Factory.Create(Of MouseEventArgs)(Me, AddressOf ToggleNavMenu))
            __builder.AddAttribute(13, "b-i797s6suhi")
            __builder.OpenElement(14, "ul")
            __builder.AddAttribute(15, "class", "nav flex-column")
            __builder.AddAttribute(16, "b-i797s6suhi")
            __builder.OpenElement(17, "li")
            __builder.AddAttribute(18, "class", "nav-item px-3")
            __builder.AddAttribute(19, "b-i797s6suhi")
            __builder.OpenComponent(Of Microsoft.AspNetCore.Components.Routing.NavLink)(20)
            __builder.AddAttribute(21, "class", "nav-link")
            __builder.AddAttribute(22, "href", "")
            __builder.AddAttribute(23, "Match", Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck(Of Microsoft.AspNetCore.Components.Routing.NavLinkMatch)(NavLinkMatch.All))
            __builder.AddAttribute(24, "ChildContent", CType((Sub(__builder2)
                                                                  __builder2.AddMarkupContent(25, "<span class=""oi oi-home"" aria-hidden=""true"" b-i797s6suhi></span> Home" & vbCrLf & "            ")
                                                              End Sub), Microsoft.AspNetCore.Components.RenderFragment))
            __builder.CloseComponent()
            __builder.CloseElement()
            __builder.AddMarkupContent(26, vbCrLf & "        ")
            __builder.OpenElement(27, "li")
            __builder.AddAttribute(28, "class", "nav-item px-3")
            __builder.AddAttribute(29, "b-i797s6suhi")
            __builder.OpenComponent(Of Microsoft.AspNetCore.Components.Routing.NavLink)(30)
            __builder.AddAttribute(31, "class", "nav-link")
            __builder.AddAttribute(32, "href", "counter")
            __builder.AddAttribute(33, "ChildContent", CType((Sub(__builder2)
                                                                  __builder2.AddMarkupContent(34, "<span class=""oi oi-plus"" aria-hidden=""true"" b-i797s6suhi></span> Counter" & vbCrLf & "            ")
                                                              End Sub), Microsoft.AspNetCore.Components.RenderFragment))
            __builder.CloseComponent()
            __builder.CloseElement()
            __builder.AddMarkupContent(35, vbCrLf & "        ")
            __builder.OpenElement(36, "li")
            __builder.AddAttribute(37, "class", "nav-item px-3")
            __builder.AddAttribute(38, "b-i797s6suhi")
            __builder.OpenComponent(Of Microsoft.AspNetCore.Components.Routing.NavLink)(39)
            __builder.AddAttribute(40, "class", "nav-link")
            __builder.AddAttribute(41, "href", "fetchdata")
            __builder.AddAttribute(42, "ChildContent", CType((Sub(__builder2)
                                                                  __builder2.AddMarkupContent(43, "<span class=""oi oi-list-rich"" aria-hidden=""true"" b-i797s6suhi></span> Fetch data" & vbCrLf & "            ")
                                                              End Sub), Microsoft.AspNetCore.Components.RenderFragment))
            __builder.CloseComponent()
            __builder.CloseElement()
            __builder.CloseElement()
            __builder.CloseElement()
        End Sub
```

**Comment by lorcQc** [comment]
I found the exception by looking in the chrome console (in dev tools).
For nav menu styles, the original project contains a NavMenu.razor.css file in the shared folder. [Blazor CSS isolation](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-6.0)
You can probably just copy the style from this file into your app.css file.
