### ISSUE TITLE
EventSourceActivity doesn't seem to be used anywhere

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#53177]
The `EventSourceActivity` class doesn't seem to be used by anything in CoreLib. Since we run linker on corelib during build, the class is actually removed from the product and can't be used by tests or product - which sort of proves that it's not needed.
Should we remove it?

**Comment by noahfalk** [comment]
This code looks dead to me. I'd say remove it unless @brianrob responds back with a hidden use-case.

cc @josalem

**Comment by brianrob** [comment]
Looks dead to me as well.  This looks like it was part of the TraceLogging work, and I know that there was some pull-back of the public facing surface at this time, so that's probably what happened here.  Let's remove it.
