### ISSUE TITLE
How useful is C# "dynamic" with System.Text.Json.Nodes.JsonObject?

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#53195]
Currently `JsonObject` supports C# "dynamic" which primarily means an instance of `JsonObject` can get\set a property value without having to use a string for the property name. 

Although dynamic support [has been requested](https://github.com/dotnet/runtime/issues/29690), I believe it was primarily desired as a work-around since System.Text.Json didn't have a writeable DOM feature yet.

**Since System.Text.Json now has a writable DOM through `JsonNode` without dynamic, is the dynamic capability redundant and should it be removed?**

In theory, support for dynamic could make code sharing between C# and scripting languaged like JavaScript a bit easier, but what are other benefits are there? 

Some negatives of dynamic:
- Dynamic is slower.
- There is no IntelliSense or type checking (also the case with non-dynamic cases).
- The current implementation requires casts to the appropriate type or call to `GetValue<T>()`, so the copy-paste ability for JavaScript doesn't quite work.
- Requires `System.Text.Json.dll` to have a reference to the large `System.Linq.Expressions.dll`, although the IL Linker removes that if dynamic is not used.
- Doesn't help with arrays.

Here's a brief sample of dynamic and non-dynamic programming models:
```cs
const string Json = "{\"MyNumber\":42, \"MyArray\":[10,11]}";

// dynamic
{
    dynamic obj = JsonNode.Parse(Json);
    int number = (int)obj.MyNumber;
    Debug.Assert(number == 42);
    
    obj.MyString = "Hello";
    Debug.Assert((string)obj.MyString == "Hello");
}

// non-dynamic
{
    JsonObject obj = JsonNode.Parse(Json).AsObject();
    int number = (int)obj["MyNumber"];
    Debug.Assert(number == 42);
    
    obj["MyString"] = "Hello";
    Debug.Assert((string)obj["MyString"] == "Hello");
}
```

Note that properties on a strongly-typed POCO and collection elements can also be declared as dynamic, and the `JsonSerializer` can also support dynamic.

**Comment by FilipToth** [comment]
Well, in my opinion, dynamic makes it a lot cleaner to read/write DOM in applications where speed isn’t a major issue.

**Comment by davidfowl** [comment]
cc @JamesNK

**Comment by jkotas** [comment]
> Requires System.Text.Json.dll to have a reference to the large System.Linq.Expressions.dll, although the IL Linker removes that if dynamic is not used.

System.Linq.Expression is "archived component". `dynamic` as it exist today is effectively deprecated tech. It is not good for new tech to take dependency on effectively deprecated tech.

**Comment by FilipToth** [comment]
@jkotas are there any plans to update it?

**Comment by jkotas** [comment]
I am not aware of any plans around better `dynamic`. I agree that it is attractive for certain scenarios and there may be a way to reinvent it to be simple, lean, fast, and without the problematic heavy `System.Linq.Expression` dependency, but that is completely speculative at this point.

**Comment by FilipToth** [comment]
@jkotas Maybe in later dotnet versions then. Thanks.

**Comment by davidfowl** [comment]
@CyrusNajmabadi  how crazy would it be to do something with embedded languages and JSON? Using the JSON to drive IntelliSense of the dynamic object being returned from these APIs? Of course it's easy when you have a JSON literal but I wonder if the schema for IntelliSense could come from outside of the C# type system and feed into it (I guess it's effectively F# type providers).

**Comment by JamesNK** [comment]
My feedback is the same:
* I don't see many people using dynamic with Json.NET (however I don't go looking for this kind of information).
* I don't think it is a hugely valuable feature.
* I wouldn't recommend making it a focus of how a JSON DOM is used, but if you want to make it an option, and you're ok with the complexity that adds, then go ahead.

**Comment by stonstad** [comment]
I prefer the dynamic approach because, after deserialization, it is implementation agnostic.

**Comment by stonstad** [comment]
> Maybe in later dotnet versions then. Thanks.

This feature (deserialization to dynamic) was actually supposed to ship in .NET 6.0, having missed the cut-off for 5.0.

**Comment by imba-tjd** [comment]
> System.Linq.Expression is "archived component".

Unrelated to this issue, is there a list of "archived component" to let us know what are not in actively developed?

**Comment by KalleOlaviNiemitalo** [comment]
There was apparently a list of archived components in <https://github.com/dotnet/runtime/issues/27790>, but I don't know if more components have been archived since then.

**Comment by gregsdennis** [comment]
I prefer a strongly-typed approach.  In Manatee.Json (now deprecated), I set up implicit casts from compatible types into my `JsonValue` type, which was a holder for any JSON value.  It supported

- numeric types
- booleans
- strings
- `JsonObject`
- `JsonArray`

Limiting it to these types keeps a nice strong type model but also allows for fairly dynamic building.

```c#
var obj = new JsonObject
    {
        ["key"] = "value",
        ["otherKey"] = 9
    }
var array = new JsonArray { "value", 9, obj };
```

Using implicit casts this way may give some people (*cough* E. Lippert *cough*) a bit of heartburn, but it makes for some very readable code.  It's not 100% copy-paste-able from JS, but it's pretty close.

Secondarily, I tend to stay as far away from `dynamic` as possible.  It has its uses, but it's not ideal for everyday use.  Generally, there's a better solution; you just have to find it.

**Comment by lukasf** [comment]
I really like the approach from @gregsdennis! But I assume not everyone likes implicit casts.

It would be really cool if we could define implicit casts in extension methods. Then we could have an extension class in a namespace `System.Text.Json.Nodes.Implicit`. If we'd include that, we'd get implicit casting, allowing fluid JS-like syntax without all the downsides of `dynamic`. Users who don't include it won't have to worry about implicit casts happening without notice.

**Comment by KrzysztofCwalina** [comment]
I think using dynamic for writing/mutating the DOM is clunky, but I think it's very useful for reading. We have many Azure SDK libraries that return raw JSON payloads (as opposed to deserialized "model" types) and we are hoping to use JsonNode with dynamic to access the returned data, e.g.
```
dynamic json = client.GetSomething(...);
int x = json.Foo.Bar.Baz;
```

It does worry me that 'dynamic' is considered to be archived.

**Comment by stephentoub** [comment]
> It does worry me that 'dynamic' is considered to be archived.

Just to clarify, Krzysztof, it worries you in general about `dynamic` (e.g. that it's not being invested in), or it worries you about this new JSON support taking a dependency on such a thing?

**Comment by gregsdennis** [comment]
I know the question wasn't directed at me, but I'm definitely worried that the JSON API could be dependent on `dynamic`. It's widely regarded as a code smell and should be considered only as a last option.

**Comment by KrzysztofCwalina** [comment]
> Just to clarify, Krzysztof, it worries you in general about dynamic (e.g. that it's not being invested in), or it worries you about this new JSON support taking a dependency on such a thing?

Both.

**Comment by steveharter** [comment]
To recap feedback:
- "dynamic" is somewhat "archived" technology and there may be a newer flavor of it coming up.
  - This potential newer flavor may have improved performance as well as new features.
  - It is not 100% certain to me if code that uses "dynamic" today will be completely forward-compatible with any newer "dynamic" flavor, thus introducing some risk in adopting it at this time.
- Currently "dynamic" is useful sugar in certain scenarios, but otherwise not a high priority or high consumption feature.
- The new `JsonNode` feature avoids most of the scenarios that made "dynamic" useful previously (that is, a writable DOM).

Based on this, I'm inclined to suggest removing the "dynamic" support for V6 unless I hear feedback otherwise from @KrzysztofCwalina or others.

**Comment by stephentoub** [comment]
That sounds like the right decision to me, @steveharter.

**Comment by KrzysztofCwalina** [comment]
Who's working on the "This potential newer flavor" of dynamic? I do think we need it at some point. It might be a syntactic sugar, but the current syntax obscures the user intent enough that our current plan for untyped APIs in the Azure SDK might not be viable without it. After all C# is just a syntactic sugar for IL, and you would not enjoy coding in IL, would you? :-)

cc: @MadsTorgersen

**Comment by KrzysztofCwalina** [comment]
Having said that, I would totally prefer a new dynamic flavor. There is no reason to involve the DLR into what amounts to syntactic sugar over dictionary access. I would prefer if dynamic was implemented as a set of attributes applied to simple lookup and cast APIs.

**Comment by John0King** [comment]
@steveharter 

what are being "archived" ?   dynamic or  System.Linq.Expression  ?

**Comment by jkotas** [comment]
@John0King Both dynamic (as it exists today) and System.Linq.Expression are archived components. See https://github.com/dotnet/runtime/issues/27790 for the discussion.

**Comment by John0King** [comment]
@jkotas   Linq and Expression are largely used in many many place, such as  EF Core,   And I believe many people do not know about the talking even start,    your team should have a announcement  to the community that you are discussing about those ,   I find that any news in  https://github.com/dotnet/announcements/issues be noticed by me is also too late, you already done the change   and is waiting for feedback about the new change.

In fact,  today's `.Join` method in Linq  is not easy to use  compare a `.LeftJoin()` or `.RightJoin`  expression, and With all async mode , there no  async version of `ToListAsync()`  `ToArrayAsync`  method.
and make those things archived, seems claims their death,  but where's the replacement ?

IMO,  you can claim something should not be used , but there must be a replacement,   otherwise,  how can anyone who used those code and  move forward  together with  the .Net version ?  Please don't drop developers !  there no more developers of .net to drop anymore!

**Comment by jkotas** [comment]
>  how can anyone who used those code and move forward together with the .Net version ?

We are not deleting any of these APIs. The existing code that uses these APIs can be moved to new .Net versions just fine.

**Comment by John0King** [comment]
@jkotas   I think "archived"  means:  ready for obsolete and deprecated

**Comment by stephentoub** [comment]
> I think "archived" means: ready for obsolete and deprecated

It does not.  The meaning as we use it is spelled out in the README for the relevant library:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md
"The library and supporting language features are mature and no longer evolving, and the risk of code change likely exceeds the benefit. We will consider changes that address significant bugs or regressions, or changes that are necessary to continue shipping the binaries. Other changes will be rejected."

**Comment by davidikin45** [comment]
Wasn't the whole point of https://github.com/dotnet/runtime/issues/29690 to allow WebAPI to accept dynamic json payloads and access them easily. e.g model.Property1? Seems strange you would regress this functionality previously provided by Newtonsoft.Json

`[HttpPost]
public async Task<IActionResult> SubmitAsync(dynamic model)`

**Comment by gregsdennis** [comment]
Yes, but it was concluded that `dynamic` is the wrong way to support this as it subverts the type system.
