### ISSUE TITLE
[Test][Infra] See how many tests were run in a specific lane

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#53191]
It was trying to find a way to look at the number of tests run in a specific lane, and I couldn't find it. I can see the total number of tests run, but not easily discover how many in a specific test lane. Maybe I was just unable to discover this feature, but if it doesn't exist, it would be good to add.

This make actually belong with azdo.

**Comment by hoyosjs** [comment]
@naricc what do you mean by lane? You mean a helix queue?

**Comment by naricc** [comment]
I mean, when you create a PR, you see several lanes (aka "legs") of tests. For example "runtime (CoreCLR Pri0 Runtime Tests Run windows x86 checked)"; I was never able to determine how many tests ran in specific lanes. I don't think these correspond to helix queues.

**Comment by agocke** [comment]
This would be an AzDo feature.
