### ISSUE TITLE
Addition of "dotnet dev-certs" command makes all WASM work items time out

### ISSUE THREAD

**Issue by MattGal** [dotnet/runtime#53207]
See https://github.com/dotnet/runtime/pull/53180, then most [any log file produced for WASM testing thereafter on windows docker containers](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53184-merge-94442eaa4fa14f84ac/System.Runtime.CompilerServices.VisualC.Tests/console.877ffb82.log?sv=2019-07-07&se=2021-06-13T22%3A19%3A03Z&sr=c&sp=rl&sig=VJIB40ATEO2xsoWwRgFv7KGPaZtIU0ixiQil2eSY24k%3D):

```
...
C:\helix\work\workitem>dotnet dev-certs https 

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 1800 seconds and was killed
...
```

Every WASM work item has timed out at 30 or 45 minutes since, and the queue is thus buried.

This commit should be immediately reverted, then tested locally using `mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-webassembly-amd64-20210422161149-94a50b5`.  

@danmoseley FYI.

**Comment by MattGal** [comment]
@pavelsavara FYI.

**Comment by premun** [comment]
@pavelsavara also please note that when you have a fix, the right place for this code is possible the Helix SDK in Arcade as all users of XHarness / WASM will need this capability to run successfully. Hit me up and we can chat more

**Comment by premun** [comment]
Btw how come the PR where the change was introduced didn't time out?

**Comment by MattGal** [comment]
> Btw how come the PR where the change was introduced didn't time out?

Because it was merged without passing checks.
![image](https://user-images.githubusercontent.com/7862010/119526265-1b5d9900-bd34-11eb-88ea-e8735e315743.png)

If you merge with 2 of 34 checks passing, that means you could break between 0 and 32 checks.
