### ISSUE TITLE
Port projects from pkgproj to dotnet pack 

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#53202]
steps to port projects 

Steps to start porting projects
- Remove PkgProj folder
- set ```<IsPackable>true</IsPackable>``` for src proj
- Move the PackageDescription from the project's Directory.Build.props file into the csproj.
- Run the pack command 

Examine the package
- use /p:GenerateCompatibilitySuppressionFile=true to generate suppressions file. Examine the suppresions before automatically suppressing them.
- https://github.com/Anipik/PackagePortTester to validate the new and old packages are same
- if there are any extra dependencies, see if the dependency is actuall needed.   If not, remove it or add a condition so that it doesn't apply to the TargetFramework.  If the ProjectReference is to an inbox framework assembly that does not have a package add  ```PrivateAssets="all"``` to the `ProjectReference`.
- if there are missing references for a compatible framework, add the project reference and a comment explaining why.
- Removing placeholder frameworks is fine. Do not remove placeholder files though (ie Xamarin).
- For any extra files compaterror, analyserfiles you will have to hook up to the new pack command (support added for analyzers, & compat errors)
- Add git diffs to the pr for reviewers.

eg 
https://github.com/dotnet/runtime/pull/55134
https://github.com/dotnet/runtime/pull/54250

Following is the list of packages that need to be ported to dotnet pack task

- [x] Microsoft.AspNetCore.Internal.Transport https://github.com/dotnet/runtime/pull/56674
- [ ] Microsoft.Bcl.AsyncInterfaces: https://github.com/dotnet/runtime/pull/56712
- [ ] Microsoft.Diagnostics.Tracing.EventSource.Redist: https://github.com/dotnet/runtime/pull/56712
- [ ] Microsoft.IO.Redist: https://github.com/dotnet/runtime/pull/56712
- [ ] Microsoft.Win32.Registry.AccessControl: https://github.com/dotnet/runtime/pull/56712
- [ ] Microsoft.Win32.SystemEvents: https://github.com/dotnet/runtime/pull/56712
- [x] Microsoft.Windows.Compatibility https://github.com/dotnet/runtime/pull/56686
- [ ] Microsoft.XmlSerializer.Generator: https://github.com/dotnet/runtime/pull/56712
- [ ] System.CodeDom: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Collections.Immutable: https://github.com/dotnet/runtime/pull/56712
- [ ] System.ComponentModel.Composition: https://github.com/dotnet/runtime/pull/56712
- [ ] System.ComponentModel.Composition.Registration: https://github.com/dotnet/runtime/pull/56712
- [x] System.Composition: https://github.com/dotnet/runtime/pull/55208
- [x] System.Composition.AttributedModel: https://github.com/dotnet/runtime/pull/55208
- [x] System.Composition.Convention: https://github.com/dotnet/runtime/pull/55208
- [x] System.Composition.Hosting: https://github.com/dotnet/runtime/pull/55208
- [x] System.Composition.Runtime: https://github.com/dotnet/runtime/pull/55208
- [x] System.Composition.TypedParts: https://github.com/dotnet/runtime/pull/55208
- [ ] System.Configuration.ConfigurationManager: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Data.Odbc: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Data.OleDb: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Diagnostics.EventLog: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Diagnostics.DiagnosticSource: https://github.com/dotnet/runtime/pull/56712
- [x] System.Diagnostics.PerformanceCounter
- [ ] System.DirectoryServices: https://github.com/dotnet/runtime/pull/56712
- [ ] System.DirectoryServices.AccountManagement: https://github.com/dotnet/runtime/pull/56712
- [ ] System.DirectoryServices.Protocols: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Drawing.Common: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Formats.Asn1: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Formats.Cbor: https://github.com/dotnet/runtime/pull/56712
- [ ] System.IO.Packaging: https://github.com/dotnet/runtime/pull/56712
- [ ] System.IO.Pipelines: https://github.com/dotnet/runtime/pull/56712
- [ ] System.IO.Ports: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Management: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Memory.Data: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Net.Http.Json: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Net.Http.WinHttpHandler: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Numerics.Tensors: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Reflection.Context: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Reflection.Metadata: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Reflection.MetadataLoadContext: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Resources.Extensions: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Runtime.Caching: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Runtime.CompilerServices.Unsafe: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Security.Cryptography.Pkcs: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Security.Cryptography.ProtectedData: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Security.Cryptography.Xml: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Security.Permissions: https://github.com/dotnet/runtime/pull/56712
- [ ] System.ServiceModel.Syndication: https://github.com/dotnet/runtime/pull/56712
- [ ] System.ServiceProcess.ServiceController: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Speech: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Text.Encoding.CodePages: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Text.Encodings.Web: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Text.Json:  https://github.com/dotnet/runtime/pull/56712
- [ ] System.Threading.AccessControl: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Threading.Channels: https://github.com/dotnet/runtime/pull/56712
- [ ] System.Threading.Tasks.Dataflow: https://github.com/dotnet/runtime/pull/56712
- [x] System.Windows.Extensions

cc @ericstj @ViktorHofer @safern

**Comment by ViktorHofer** [comment]
The System.Composition* projects should already be portable today as they neither have reference assemblies nor runtime assets.

**Comment by ViktorHofer** [comment]
Also I just removed the few packages from the list that were dead-ended with https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f

**Comment by ericstj** [comment]
Is there any ordering requirement for these, or can we just port them at will?

**Comment by ViktorHofer** [comment]
nit: this list is incomplete, it's missing the `Microsoft.Private.CoreFx.OOB`, the `Microsoft.Windows.Compatibility` and the `runtime.native.System.IO.Ports` libraries on the libraries side. 

Apart from that, we should also try to get the runtime and host pkgprojs migrated to be able to remove our usage of `Microsoft.DotNet.Build.Tasks.Packaging` entirely. Those are simple "here are files, please pack them up" projects and could be worked on in parallel to the libraries packages.

**Comment by Anipik** [comment]
> Is there any ordering requirement for these, or can we just port them at will?

we have added the required infra and we have some example prs as well. we can start trimming this list down.
