### ISSUE TITLE
XDocument Fails To Parse XML produced by Interop.Excel (finds non-existent illegal character)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#53230]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XDocument-Fails-To-Parse-XML-produced-by/1407006)._

---
[severity:It bothers me. A fix would be nice]
I will start with how I am getting around the problem. Here is code that works (below). The key feature that allows this code to compile is the removal of the '0' (NUL) character, which the output from Excel has as a final character. (Visual Studio specifically complains about the character in the last position, so I could also have just trimmed it)
```
XDocument.Parse(((string)dataRange.Value[Excel.XlRangeValueDataType.xlRangeValueMSPersistXML]). Replace("\x00", ""))
```
(Note that 'dataRange' is an Excel.Range object. I'm using the Microsoft.Office.Interop.Excel V16.0 with .Net 5)
Here is the original, problematic version:

```
XDocument.Parse((string)dataRange.Value[Excel.XlRangeValueDataType.xlRangeValueMSPersistXML])
```
This raises an Exception with the following messages: 
   - "'.', hexadecimal value 0x00, is an invalid character. Line 211, position 7."
   - '{0}', hexadecimal value {1}, is an invalid character.

Note that the XML is coming directly out of Excel and my only contribution is casting it from object to string.

There are two mysteries here:
    
1. In an earlier version I used System.XmlDocument an that was able to load the same XML just fine. I have also put the code through various validation services and they could read it without issues. _That suggests, only XDocument is seeing the NUL character_.  

2. I also put the XML into two HEX editors and neither shows a NUL character at the end. I don't know at what point this character is being generated.

I will carry on with my fix, but it would be great if I didn't have to use such a hack.

---
#### Feedback Bot on 4/25/2021, 08:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by krwq** [comment]
Can you save the XML and share here? (ideally save it directly from the code rather than copy & pasting as it might be the key to solving this issue)
