### ISSUE TITLE
Socket dual mode not working on Unix systems

### ISSUE THREAD

**Issue by ncorreia** [dotnet/runtime#53234]
### Description

When opening a socket in dual mode and receiving data with ReceiveFrom method (cannot use Receive as I need to capture the sending endpoint), I get the following exception on Unix systems:

```
Unhandled exception. System.PlatformNotSupportedException: This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
   at System.Net.Sockets.SocketPal.CheckDualModeReceiveSupport(Socket socket)
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
```

This runs fine on Windows machines.

Here's the code I'm using:

```C#
class Program
    {
        static void Main(string[] args)
        {
            var endPoint = new IPEndPoint(IPAddress.IPv6Any, 11000);
            using var socket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);
            socket.DualMode = true;
            var buffer = new byte[1024];
            EndPoint senderRemote = new IPEndPoint(IPAddress.IPv6Any, 0);
            socket.Bind(endPoint);
            var bytes = socket.ReceiveFrom(buffer, 0, buffer.Length, SocketFlags.None, ref senderRemote);
            Console.WriteLine($"Received {bytes} bytes");
        }
    }
```

### Configuration

Tried on macOS 11.3 as well as on Ubuntu 18.04 and saw the exception above on both systems. 
It succeeds on Windows 10.

Tested with .NET 5.0.102

**Comment by filipnavara** [comment]
It's certainly not supported on macOS but it should work on Linux.

**Comment by wfurt** [comment]
this is known limitation of osx/macOS/iOS.
I tested the code on Ubuntu18 and works fine for me.

**Comment by ncorreia** [comment]
My setup was not right, I can confirm that it works on Ubuntu, just not on macOS.

Is there a workaround for macos, or is there an upcoming fix?

**Comment by ncorreia** [comment]
Thanks everyone for the prompt help. It looks like this can be closed as a known issue on macos. It would be nice though if this limitation was more obvious to find either through documentation or error messaging.
