### ISSUE TITLE
Add leftjoin/rightjoin syntax to linq to end the horrific syntax currently required

### ISSUE THREAD

**Issue by JohnGalt1717** [dotnet/runtime#53236]
## Background and Motivation
Right now doing left and right joins in linq is horrific and requires a ton of code that shouldn't be necessary if the proper language keywords were added.

## Proposed API

Add leftjoin/right join syntax.

## Usage Examples

from c in db.Contacts left join d in db.Domains on c.Id equals d.ContactId select new {c, d} //d would be nullable here.
from c in db.Contacts right join d in db.Domains on right c.Id equals d.ContactId select new {c, d} //c would be nullable here.

Of course you could easily write both as left joins so right could be dropped.

## Alternative Designs

from c in db.Contacts leftjoin d in db.Domains on c.Id equals d.ContactId select new {c, d} //d would be nullable here.

## Risks
Intellisense issues with left join right join because of multi word syntax maybe? Hence the second option.

**Comment by JohnGalt1717** [comment]
area: area-System.Linq
area: area-System.Linq.Expressions

**Comment by vcsjones** [comment]
Adding new language constructs for the LINQ query expression syntax would probably need to be a language proposal in the `csharplang` repository. It looks like there is some existing discussion on that here https://github.com/dotnet/csharplang/discussions/361

**Comment by JohnGalt1717** [comment]
hrm. The new language constructs and extensions that were just announced link here, hence why I published here.

**Comment by eiriktsarpalis** [comment]
Closing in favor of https://github.com/dotnet/csharplang/discussions/361.
