### ISSUE TITLE
Emsdk needs to be signed

### ISSUE THREAD

**Issue by adiaaida** [dotnet/runtime#53252]
Today, emsdk neither signs in their official builds, nor does it have the configuration to post-build sign, so we risk attempting to publish unsigned files out of that repo. If we want to in-build sign, the yaml/build.cmd in emsdk needs to be updated. If we want to post-build sign, we need to add the configuration for doing post-build signing.

/cc: @mmitche for more details about post-build signing

**Comment by akoeplinger** [comment]
@mmitche let me know what we need to do to enable post-build signing.

**Comment by mmitche** [comment]
> @mmitche let me know what we need to do to enable post-build signing.

In the publishing.props file, you'll need to set the PostBuildSign property true. Then you'll need to fill itemgroup ItemsToSignPostBuild with the items that you need signed (in this case the nupkg files).

**Comment by akoeplinger** [comment]
@mmitche I made the change to use post build signing and I see the xml files in the AssetManifests AzDO artifact. Is there any way to try running a postbuild sign to see whether it really works?

**Comment by adiaaida** [comment]
If we have the build id, we can probably run it through the validation pipeline to see.

**Comment by akoeplinger** [comment]
@adiaaida cool thanks, the build id is 91768.

**Comment by adiaaida** [comment]
Will run it through

**Comment by adiaaida** [comment]
Sorry this took so long. I accidentally ran without post-build signing turned on yesterday, so I had to rerun it this morning. It looks like there were some errors in post-build signing because there are files without a certificate specified:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1159890&view=logs&j=9ff0e0af-24e7-5b0f-fa76-5e12fc9920ef&t=04e39753-8cfe-5fb5-2824-43b4c4b51e3b

**Comment by mmitche** [comment]
Looks like `.pyd` files need to get signed. Should they get the same signature as `.py`?

**Comment by mmitche** [comment]
That's currently specified as "<FileExtensionSignInfo Include=".py" CertificateName="3PartySHA2" />"

**Comment by adiaaida** [comment]
Also, some `.cat` files

**Comment by mmitche** [comment]
> Also, some `.cat` files

I can only assume those get the `3PurrtySHA2` cert.

**Comment by akoeplinger** [comment]
Also `.vbs`. I'll add them to the `FileExtensionSignInfo` until we update the arcade version: https://github.com/dotnet/arcade/blob/c3e0e4070f6cd3873b775e3f4136e29f4d66cb49/src/Microsoft.DotNet.Arcade.Sdk/tools/Sign.props#L38-L43

**Comment by akoeplinger** [comment]
@adiaaida I've started a validation build here but it's been going on for almost 3 hours now, so not sure if that's expected: https://dev.azure.com/dnceng/internal/_build/results?buildId=1160272&view=results

**Comment by mmitche** [comment]
Not expected. It appears to be failing when signing the .py files. I am not sure whether this is a result of the certificate or the files themselves.

**Comment by mmitche** [comment]
Just received note from the ESRP folks that .py files do not support the `3PartSHA2` cert

**Comment by trevors20** [comment]
Hey guys.  We need to STOP these builds NOW.  ESRP has contacted us that this is causing an issue with their signing.  Who can help me?

**Comment by adiaaida** [comment]
As far as I can see, there are currently no builds attempting to do this signing. So long as we do not manually start anything before we revert the changes @akoeplinger made to turn this on, there shouldn't be anything that attempts to send these files to ESRP. @mmitche @lukas-lansky

**Comment by hoyosjs** [comment]
@akoeplinger @mmitche looks like js, vbs files can't be dual signed and py files can't be signed with the 3rd party cert. I've opened https://github.com/dotnet/emsdk/pull/23 while we figure this out.

**Comment by akoeplinger** [comment]
Merged https://github.com/dotnet/emsdk/pull/23 so we shouldn't be hitting this issue now.

**Comment by adiaaida** [comment]
> I paused validation pipeline per @hoyosjs's request

The validation pipeline only runs on repos that have been onboarded. It does not run on emsdk by default, as it has not been onboarded, only on manual runs. I have reenabled it.

**Comment by akoeplinger** [comment]
@adiaaida can we try running build 92037 through the validation pipeline? It has the signing fixes.

**Comment by adiaaida** [comment]
Yes, let’s do

**Comment by akoeplinger** [comment]
Ok, I triggered https://dev.azure.com/dnceng/internal/_build/results?buildId=1161830&view=results

**Comment by mmitche** [comment]
@akoeplinger I cancelled it again to avoid potential issues...are we sure that pyd can be signed with 3Party?

**Comment by akoeplinger** [comment]
From what I can find a .pyd is essentially a Windows .dll library so it should work.

**Comment by adiaaida** [comment]
The .cat files too?

**Comment by akoeplinger** [comment]
We don't have these in emsdk I think, but .ps1 ran into the same issue so I disabled those too :)

**Comment by akoeplinger** [comment]
Ah right, but looks like the latest build passed the signing stage so should be good now: https://dev.azure.com/dnceng/internal/_build/results?buildId=1162317&view=results

**Comment by mmitche** [comment]
You might take a look at the output packages and give the files inside them a once over.

**Comment by adiaaida** [comment]
Looks like the last thing to do is to add *.js to emsdk's SignCheckExclusionsFile.txt (this is runtime's: https://github.com/dotnet/runtime/blob/main/eng/SignCheckExclusionsFile.txt)

**Comment by akoeplinger** [comment]
I added the SignCheckExclusionsFile.txt and signing validation passed now: https://dev.azure.com/dnceng/internal/_build/results?buildId=1164165&view=results

It failed trying to validate .symbols.nupkg which is expected since we don't have symbols for emsdk, where can I disable that validation?

**Comment by akoeplinger** [comment]
Closing this since I think we've done the necessary things here, please let me know if something is still missing.
