### ISSUE TITLE
Remove System.Text.Json's DynamicDependencies on Collections.Immutable

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#53256]
Today, `JsonSerializer` takes a `DynamicDependency` on basically all the System.Collection.Immutable `CreateRange` methods:

https://github.com/dotnet/runtime/blob/5f15498d937653986821d636c04cd03c58d4bb4c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L154-L159

https://github.com/dotnet/runtime/blob/5f15498d937653986821d636c04cd03c58d4bb4c/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L186-L187

This causes all of the Immutable Collection types to be rooted in an application, even if the app doesn't use the types. This is a fairly substantial amount of code, especially in cases where every KB counts, like Blazor WASM apps.

With https://github.com/dotnet/runtime/issues/53205, I found out that a bunch of other collection types don't work in JsonSerializer in a trimmed app. That makes me think that these Immutable collection types really shouldn't be treated specially, especially considering they bring in so much unused code.

I prototyped what it would look like removing these DynamicDependencies [here](https://github.com/eerhardt/runtime/tree/RemoveJsonImmutableReference). Using this prototype I was able to measure just how much code these DynamicDependencies are causing:

**Before**: 2,600,754 bytes
**After**: 2,572,198 bytes

It decreases the app size almost 28KB .br compressed.

With the advent of the JSON source generator, we can make applications that call `JsonSerializer` trim-safe by telling developers to use the source generator when they need to serialize/deserialize objects. If they care about trim-safety, they can convert their code to use the source generator, and it will work, even after trimming.

However, the problem with removing these attributes is that existing apps that use Immutable Collections in a JSON graph would be broken once they are trimmed. For normal apps, we will give them a warning in all places they call the serializer. However, for Blazor WASM apps, these warnings are suppressed by default. So apps won't see them.

I can think of the following strategies we could take to resolve this:

1. Just remove the DynamicDependencies, and if developers run into issues we tell them to either use the source generator, or tell them which ImmutableCollection methods to root in their app.
2. Introduce a new [feature switch](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md), which conditionally adds these DynamicDependencies. By default in Blazor WASM apps, the switch is set to **not** root these collections. Developers who run into problems in their app can just flip the feature switch, and these collections will be rooted again.
3. Continue down the current path, and if we fix https://github.com/dotnet/runtime/issues/53205, JSON will root even more collections that may not even be used in the application.

In my opinion, using Immutable Collections in a JSON graph isn't a super common case. Paying this price in all apps that use JSON isn't worth the tradeoff.

Thoughts?

@steveharter @layomia @eiriktsarpalis @Jozkee @vitek-karas @marek-safar @SteveSandersonMS @pranavkm @danroth27 @stephentoub @jkotas

**Comment by jkotas** [comment]
> In my opinion, using Immutable Collections in a JSON graph isn't a super common case. 

+1

My vote would be for Option 1 Just remove the DynamicDependencies.

**Comment by stephentoub** [comment]
+1 to Jan's +1.

**Comment by marek-safar** [comment]
> In my opinion, using Immutable Collections in a JSON graph isn't a super common case.

I agree and if you also consider other sensitive workloads that would benefit from this and have lower expectations about pre-net6 compatibility it makes even more sense.
