### ISSUE TITLE
provide builtin placeholder feature for configuration component

### ISSUE THREAD

**Issue by hiwjcn** [dotnet/runtime#53272]
just like:

```json
{
"server_ip":"127.0.0.1",
"redis":{
"connection_string":"${server_ip}:6379"
}
}
```

**Comment by joperezr** [comment]
@hiwjcn Can you elaborate a bit more of what will that configuration will be used for? Usually for API Proposals we have template and call out the actual proposed APIs with the usage scenarios. You can take a look at this as an example of how a proposal should look like: https://github.com/dotnet/runtime/issues/53296
