### ISSUE TITLE
Adhere to the package support policy by building and packaging supported frameworks only

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53282]
Continuation of https://github.com/dotnet/runtime/issues/47530

The runtime repository currently produces 102 packages from libraries of which 25 of those contain assets which will be unsupported when we release .NET 6 in November 2021. The list of unsupported assets includes netstandard1.x assets as those apply to unsupported application frameworks only as in any case where a netstandard1.x asset is present, a netstandard2.0 (and in most cases a net461 asset) exists as well which allows to run on .NET Framework 4.6.1 or .NET Core 3.1 and above.

The reasons for trimming out unsupported assets are:
- Simplified build graph and reduced build times
- Less restore size as the NS1.x dependency graph doesn't need to be restored
- Package validation costs
- Fat packages
- Maintenance of code bases which are not tested anymore.

Based on these disadvantages we will remove the remaining unsupported assets from packages in dotnet/runtime.

### NETStandard,Version=1.x -> .NETStandard,Version=2.0
- Microsoft.Extensions.HostFactoryResolver.Sources
- System.Collections.Immutable
- System.Diagnostics.DiagnosticSource
- System.IO.Packaging
- System.Numerics.Tensors
- System.Reflection.Context
- System.Reflection.Metadata
- System.Runtime.CompilerServices.Unsafe
- System.Threading.Channels
- System.Threading.Tasks.Dataflow

PR: https://github.com/dotnet/runtime/pull/53283

### NETCoreApp,Version=2.x|3.0 -> .NETCoreApp,Version=3.1
- Microsoft.Win32.SystemEvents
- System.Data.Odbc
- System.Diagnostics.EventLog
- System.ComponentModel.Composition
- System.Diagnostics.PerformanceCounter
- System.DirectoryServices
- System.DirectoryServices.AccountManagement
- System.DirectoryServices.Protocols
- System.Management
- System.Runtime.CompilerServices.Unsafe
- System.Security.Principal.Windows
- System.Speech
- System.Text.Encoding.CodePages
- System.Threading.Channels

PR: https://github.com/dotnet/runtime/pull/53358

### NETFramework,Version=4.5|4.5.1|4.6 -> .NETFramework.Version=4.6.1
- System.Diagnostics.DiagnosticSource
- System.Runtime.CompilerServices.Unsafe
- System.IO.Packaging
- System.ComponentModel.Composition.Registration
- System.ComponentModel.Composition
- System.DirectoryServices
- System.DirectoryServices.AccountManagement
- System.DirectoryServices.Protocols
- System.IO.Packaging
- System.Management
- System.Reflection.Context
- System.Runtime.Caching
- System.Speech

PR: https://github.com/dotnet/runtime/pull/53319

cc @danmoseley @ericstj @terrajobst @Anipik

**Comment by grbell-ms** [comment]
Aren't net452, net460, and net461 supported through April 2022?
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by ViktorHofer** [comment]
> Aren't net452, net460, and net461 supported through April 2022?
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

You are right. For .NET Framework we decided to upgrade to net461 as that's the earliest version that support .NET Standard 2.0 which is the baseline for our packages. The table above shows that only 13 packages targeted an earlier version of .NET Framework as the majority already moved to net461 or later.

Thanks for linking to the document. That indicates that we want to upgrade our .NET Framework assets again when we branch off for NET7 which will likely release next year in November.

**Comment by grbell-ms** [comment]
I was confused about the phrase "assets which will be unsupported when we release .NET 6 in November 2021". I interpreted that as "assets that target frameworks which will be unsupported when we release .NET 6 in November 2021". But I guess you meant "assets which will be unsupported by .NET 6 when we release in November 2021", which makes more sense.

**Comment by ViktorHofer** [comment]
Closing as work is completed.
