### ISSUE TITLE
AppHost should be disabled by default for macOS like it is for iOS / tvOS / Mac Catalyst / Android

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#53307]
### Description

Xamarin.Mac for .NET (the `net6.0-macos` target framework) are like mobile platforms in that the app host should be disabled by default here:

https://github.com/dotnet/sdk/blob/c53c8ac81e1bcb8118c31bc4f5622396c72e9959/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L118-L119

I'm not sure what's the best way to do it though, since the applicable RIDs (`osx-x64`/`osx-arm64`) are also used for other target frameworks where the app host shouldn't get the same behavior.

CC @akoeplinger

**Comment by agocke** [comment]
We're actually planning on enabling the apphost for Mac due to the x64/ARM64 split on Apple Si.

What's the reason why mobile platforms need to have the apphost disabled?

**Comment by rolfbjarne** [comment]
> What's the reason why mobile platforms need to have the apphost disabled?

We don't use it, we host the runtime (either Mono or CoreCLR) ourselves.

**Comment by akoeplinger** [comment]
Hm as a workaround you can set `_RuntimeIdentifierUsesAppHost=false` and `UseAppHost=false`.

**Comment by agocke** [comment]
Yeah, I'm not sure that's bad as an actual solution -- it seems like we just need to decide on the correct properties to set in the Xamarin targets.

**Comment by rolfbjarne** [comment]
> Hm as a workaround you can set `_RuntimeIdentifierUsesAppHost=false` and `UseAppHost=false`.

That can only be set in the csproj, because `_RuntimeIdentifierUsesAppHost` is evaluated before our WorkloadManifest.targets file is loaded (where we can set properties ourselves).

You can see the Import order here: https://gist.github.com/rolfbjarne/848f5c5fed4f3e1a5314232d269bb670

AutoImports.props is loaded at line 27: https://gist.github.com/rolfbjarne/848f5c5fed4f3e1a5314232d269bb670#file-gistfile1-txt-L27 - this is the first time our code is loaded, and at this point we can't set properties (https://github.com/xamarin/xamarin-macios/blob/85ce924296eb17b4a3860b32cc94d8b4c1bfae00/dotnet/targets/Microsoft.Sdk.DefaultItems.template.props#L5-L16)

Microsoft.NET.RuntimeIdentifierInference.targets is loaded at line 52: https://gist.github.com/rolfbjarne/848f5c5fed4f3e1a5314232d269bb670#file-gistfile1-txt-L52

Our WorkloadManifest.targets is loaded at line 65: https://gist.github.com/rolfbjarne/848f5c5fed4f3e1a5314232d269bb670#file-gistfile1-txt-L65 - this is where we can set properties, but it's too late.

**Comment by agocke** [comment]
Note: we will be enabling the AppHost for coreclr in order to support Apple Silicon. I don't know if there's a different configuration where that doesn't make sense.

**Comment by agocke** [comment]
As we're enabling the AppHost for Mac we may be removing some of those properties, so I would be careful about dependencies here. Clearly `UseAppHost` is public, so there's no problem there, but I'm not sure what will change in our usage of `_RuntimeIdentifierUsesAppHost`

**Comment by steveisok** [comment]
@akoeplinger what do you think the best solution is?

**Comment by vitek-karas** [comment]
I think this should be solved in the SDK specific to Xamarin.Mac - I assume there's such a thing as the core SDK will not produce apps for it. Should we maybe move the issue to the repo which track the work on that SDK?

**Comment by akoeplinger** [comment]
With https://github.com/dotnet/sdk/pull/18639 the RuntimeIdentifierInference.targets is now imported after the workload targets so setting ` _RuntimeIdentifierUsesAppHost=false` and `UseAppHost=false` should work now as a workaround.

Ideally we shouldn't need to rely on a "private" msbuild property though,  an explicit `UseAppHost=false` setting should be enough to disable the apphost completely.

We only need the `RuntimeIdentifierUsesAppHost=false` to disable this error check here: https://github.com/dotnet/sdk/blob/e2687a3e6e5259d2167173977e64f1e9ab91f51b/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.RuntimeIdentifierInference.targets#L148-L149
 
@agocke sounds like if you touch this code anyway, can we just relax that check?

**Comment by agocke** [comment]
I think the right approach for now is to use `_RuntimeIdentifierUsesAppHost`. I don't think disabling that check is the right thing -- it's an important safe guard for later passes that may require the apphost.

It seems better to make `_RuntimeIdentifierUsesAppHost` a public property, since it's being used like one. I'm going to close this issue for now since it's been resolved (at least temporarily). If we want to come back to this, the SDK is the right repo for a new issue.
