### ISSUE TITLE
How to create Certificate Signing Request (CSR) when using dynamic engine for openssl

### ISSUE THREAD

**Issue by Dvergatal** [dotnet/runtime#53345]
Hi all,
i have configured OpenSSL library to use my pkcs11 dynamic engine. Now i am using Pkcs11Interop library to connect to the token and generate key pair. Key pair has been generated and i see it on the token via pkcs11-tool. The problem is now that i would like to generate CSR and i really don't know how to pass my private key object from the token to the the function of X509Request.

I was thinking of getting the key pointer from the pkcs11 token using ENGINE_load_private_key method which would return me SafeEvpPKeyHandle but i really don't know how to pass it to X509Request call. 

Maybe there is a much better solution and someone could point me to it.

BR
Piotr

**Comment by vcsjones** [comment]
> function of X509Request

Is this a class from another library?

> return me SafeEvpPKeyHandle but i really don't know how to pass it

If you can get an EVP_PKEY handle to a key, you can construct an instance of the appropriate algorithm using `RSAOpenSsl` or `ECDsaOpenSsl` from the [System.Security.Cryptography.OpenSsl][1] package. Something like:


```csharp
SafeEvpPKeyHandle handle; // Get your handle
RSA rsa = new RSAOpenSsl(handle);
// Pass your RSA object around as needed
```

If you need an `X509Certificate2` object, you can use `CopyWithPrivateKey` so you have an instance backed by a key from PKCS11.

[1]: https://www.nuget.org/packages/System.Security.Cryptography.OpenSsl/

**Comment by vcsjones** [comment]
If you can get a `SafeEvpPKeyHandle`, you can use `CertificateRequest` to generate a request. A contrived example would look something like this:


```csharp
SafeEvpPKeyHandle handle; // Get your handle
RSA rsa = new RSAOpenSsl(handle);

CertificateRequest req = new CertificateRequest("CN=potato", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
byte[] requestDer = req.CreateSigningRequest();
string requestPem = new string(PemEncoding.Write("CERTIFICATE REQUEST", requestDer));
Console.WriteLine(requestPem);
```

**Comment by Dvergatal** [comment]
Ok but i have a new problem. I am unable to use from System.Security.Cryptography.OpenSsl.dll. I see that i have this library in my sdk /usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.6/ but i am unable to use it in my project. The project TargetFramework is Net5.0 so it should work but it is not.

**Comment by vcsjones** [comment]
> I have even tried to use package from nuget and i see it is being downloaded to .nuget/packages/system.security.cryptography.openssl but it doesn' see symbols from it.

You should be able to use it as a package reference:

```xml
<PackageReference Include="System.Security.Cryptography.OpenSsl" Version="5.0.0" />
```

The `RSAOpenSsl` class is in the `System.Security.Cryptography` namespace. There is no `System.Security.Cryptography.OpenSsl` namespace.

If you are still running in to issues, can you create a sample project that reproduces the issue and share it on GitHub as a public repository?

**Comment by Dvergatal** [comment]
Ok i have solved my problem. I was using version library 5.0.6 not 5.0.0 and also i was using namespace System.Security.Cryptography.OpenSsl instead of System.Security.Cryptography. My bad:P

Thx for help.

**Comment by Dvergatal** [comment]
Btw. is there some mechanism ported to determine the mechanism of the SafeEvpPKeyHandle? Because in OpenSSL there is this EVP_PKEY_type field from which i can determine the correct key structure.

**Comment by vcsjones** [comment]
@Dvergatal can you share the code you had to produce this error, or did you use my example code verbatim?

**Comment by Dvergatal** [comment]
Yeah i can give you the code of my [DynamicEngine assembly](https://github.com/Dvergatal/OpenSsl.DynamicEngine). The usage is like that:

```C#
                    IEngine engine = EngineFactory.GetEngine(new EngineFactory.OpenSSLConfig
                        {
                            EngineId = "pkcs11",
                            EnginePath = "/lib/engines-1.1/libpkcs11.so",
                            ModulePath = "/lib/libtpm2_pkcs11.so"
                        }
                    );
                    // ...
                    // Perform cryptographic operations
                    // ...
                    engine.Login("123456890");
                    SafeEvpPKeyHandle pKeyHandle = engine.GetPrivKey("key_label");
                    string requestPem = engine.GetCSR(pKeyHandle, "CN=potato", HashAlgorithmName.SHA256);
                    Console.WriteLine(requestPem);
```

But in order to work you need to have an initialized pkcs11 token with key pair generated. In my case i'm using physical tpm token with tpm2-pkcs11 module. Btw. i assume you know how to initialize token and generate all the data on it, but if you need help i can assist.

**Comment by Dvergatal** [comment]
Ok. After some investigations i have found that this error is being called from dotnet code from file ./src/Native/Unix/System.Security.Cryptography.Native/pal_rsa.c at line 164 because key has no private key but that is not true. The keys on the token are private and public.

Is it possible that the dotnet openssl library cannot work with dynamic engines?

**Comment by vcsjones** [comment]
> My guess is that because i'm using external key, which is on the token, this method should return this 0 here am i right?

That should be the case. The function is a negative, Has<em>No</em>PrivateKey, so returning 0 here would mean we would believe it has a private key.

Can you determine if `RSA_meth_get_flags` has the `RSA_FLAG_EXT_PKEY` flag for your key?

**Comment by Dvergatal** [comment]
Yeah but does dotnet have this RSA_meth_get_flags equivalent?

**Comment by Dvergatal** [comment]
Ok this is a bug in the dotnet openssl implementation. This checking if key is privte shouldn't be in there. This should be handled by the openssl itself or the checking should be on the key itself. Not on the method of the key. I'm opening a bug and this is really a critical one,

**Comment by bartonjs** [comment]
> This should be handled by the openssl itself

I agree, and OpenSSL 3.0 does check it.  Unfortunately, OpenSSL 1.0 and 1.1 both segfault if you pass a public-only key into a private key operation, which is why we need the check.  The check appears to be not quite right, but we'll need some help in figuring out what the right check should be.

**Comment by Dvergatal** [comment]
Ok i have written it to you this should be done on rsa key itself like that:
```c
RSA_set_flags()
```

and this is the docs for the method https://www.openssl.org/docs/man1.1.0/man3/RSA_set_flags.html.

**Comment by vcsjones** [comment]
That looks promising. However `RSA_test_flags` is new in OpenSSL 1.1.0, it would need to be shimmed for OpenSSL 1.0.2 support.

Since the `RSA` object is not opaque in 1.0.2, I think it would be a matter of checking the [`flags`](https://github.com/openssl/openssl/blob/12ad22dd16ffe47f8cde3cddb84a160e8cdb3e30/crypto/rsa/rsa.h#L153) field.

**Comment by Dvergatal** [comment]
> That looks promising. However `RSA_test_flags` is new in OpenSSL 1.1.0, it would need to be shimmed for OpenSSL 1.0.2 support.
> 
> Since the `RSA` object is not opaque in 1.0.2, I think it would be a matter of checking the [`flags`](https://github.com/openssl/openssl/blob/12ad22dd16ffe47f8cde3cddb84a160e8cdb3e30/crypto/rsa/rsa.h#L153) field.

Yes. In libp11 there was also the same [bug](https://github.com/OpenSC/libp11/issues/304) but with setting this field. And it was fixed as you say.

**Comment by vcsjones** [comment]
@bartonjs what do you think? I can prepare a PR for this change if it seems reasonable to you.

**Comment by Dvergatal** [comment]
Btw. for a quick checking i have added in the code of libp11 a simple change:

```c
        if (key->isPrivate) {
                RSA_set_method(rsa, PKCS11_get_rsa_method());
                RSA_meth_set_flags(RSA_get_method(rsa), RSA_FLAG_EXT_PKEY);
#if OPENSSL_VERSION_NUMBER >= 0x10100005L && !defined(LIBRESSL_VERSION_NUMBER)
                RSA_set_flags(rsa, RSA_FLAG_EXT_PKEY);
#else
                rsa->flags |= RSA_FLAG_EXT_PKEY;
#endif
                printf("flaga ustawiona\n");
        }
```

The line ` RSA_meth_set_flags(RSA_get_method(rsa), RSA_FLAG_EXT_PKEY); was added and CSR started to be generated. 
The error `Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:04075093:rsa routines:RSA_sign:value missing` is gone.

**Comment by bartonjs** [comment]
I guess I'm surprised by how anything would be working with this already.  If RSA_FLAG_EXT_PKEY isn't set, then things like RSA_sign are going to try using the CRT parameter fields, which I expect would be null...  The flag being set means it'll call the callback instead, so it seems like it should already be set at the engine level.  (Unless the point is just that we checked the engine and we should have checked the key).

I'd be concerned that something is already relying on the "we checked the engine" behavior, so I'd or-in the new acceptance criteria, not just change it.  But maybe I'm being overly cautious.

**Comment by Dvergatal** [comment]
Have you been verifying, if it works with external key on HSM? In my case i'm using pkcs11 engine together with tpm2-pkcs11 module and from what i have been talking with guys from openssl this is how it should be implemented. The checking should be on the object itself not the method because the method is global per engine. This is a relict left when no one thought about changing engines during the work on crypto materials.

**Comment by Dvergatal** [comment]
Hi, is it possible for a quick fix ASAP?

**Comment by vcsjones** [comment]
> is it possible for a quick fix ASAP?

Is your expectation that this is fixed for .NET 5? I would not think any changes for this would come until .NET 6, unless you are comfortable using pre-releases for urgency.

**Comment by Dvergatal** [comment]
Yeah i can switch to .NET 6 pre-release, because this is a critical bug in our company assembly to go further with the work. For now i am working with workaround in the pkcs11 engine but i do not want to make rubbish in our OS firmware.
