### ISSUE TITLE
Regex.Matches is fast with match but very slow without

### ISSUE THREAD

**Issue by KarlssonBernoulli** [dotnet/runtime#53349]
### Description

The performance of RegEx.Matches differs very much in case the test string contains one match or no match.

```C#
var regEx = new System.Text.RegularExpressions.Regex(@".*Viper");
var sb = new StringBuilder();

for(var i = 0 ; i < 100000; i++)
{
    sb.Append(" ");
}

var strNoMatch = sb.ToString();
var strWithMatch = $"{strNoMatch}      Viper      ";

var res = regEx.Matches(strWithMatch).ToList();  // fast in any way (acceptable)
var res = regEx.Matches(strNoMatch).ToList();  // very slow (inacceptable)

```

If the reg ex pattern is changed to ```^.*Viper``` both ways are fast.

In PHP the same is always fast - with a match in the test string or without: 

```PHP
$str = "";
$pattern = "/.*Viper/";

for($i = 1; $i <= 1000000; $i++) {
    $str .= " ";
} 

echo preg_match($pattern, $str);

```

### Configuration

.NET Core Version 3.1 
OS Windows 10 Enterprise

**Comment by MihaZupan** [comment]
[Source](https://gist.github.com/MihaZupan/d371ab060ab21067a443093be966cee2)
|  Method | Length | ContainsMatch |            Mean |         Error |        StdDev |
|-------- |------- |-------------- |----------------:|--------------:|--------------:|
| IsMatch |     10 |         False |      1,816.6 ns |       3.51 ns |       3.11 ns |
| IsMatch |     10 |          True |        214.2 ns |       1.14 ns |       1.01 ns |
| IsMatch |   1000 |         False | 10,078,399.6 ns | 183,610.15 ns | 162,765.62 ns |
| IsMatch |   1000 |          True |        285.2 ns |       0.67 ns |       0.62 ns |

**Comment by stephentoub** [comment]
> The performance of RegEx.Matches differs very much in case the test string contains one match or no match.

This is not a general statement, but rather specific to the pattern you're using.  PHP almost certainly is applying an auto-anchoring optimization.  Try changing your .NET regex from `@".*Viper"` to `@"^.*Viper"`, and you should see both matches and non-matches run equally and very fast.  The auto-anchoring is tracked by https://github.com/dotnet/runtime/issues/42447.  This particular example would also be helped by https://github.com/dotnet/runtime/pull/51508.

Closing as a dup.  Thanks.
