### ISSUE TITLE
[.NET 5] Proper DisplayName in CultureInfo "aa" missing

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [dotnet/runtime#53362]
### Description

`CultureInfo` for `aa` (Afar) does not contain a proper `DisplayName` nor the `NativeName`. Both fields contain only `aa`.

**Reproduce:**

```csharp
var aa = CultureInfo.GetCultureInfo( "aa" );
```

**Expected Behaviour**

```csharp
aa.DisplayName == "Afar"
aa.NativeName == "Qafaraf"
```

**Actual Behaviour**

```csharp
aa.DisplayName == "aa"
aa.NativeName == "aa"
```

### Configuration

* Framework: `net5.0-windows10.0.19041`
* Platform: Windows 10 20H2
* Arch: x64
* Local culture: reproducible with German and English system

### Regression?

+ in .NET Framework 4.8: `aa.DisplayName == "Afar"`
+ in .NET 3.1: `aa.DisplayName == "Qafar"`

Cheers,
Georg

**Comment by tarekgh** [comment]
Thanks @georg-eckert-zeiss for reporting the issue.
