### ISSUE TITLE
Coding Style: Using 'new()' without the type on the left-hand side

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#53369]
I've seen a few usages of the new `new()` syntax cropping up on our code. In many cases, it looks great:

https://github.com/dotnet/runtime/blob/5dcc340a17e32d81dc12f644449c8b58396b2fd7/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/QueueOfTConverter.cs#L13

It cuts out a lot of "cruft", in this case having to have another `QueueOfTConverter<TCollection, TElement>` in the line.

However, there are cases where we are using `new()` without having the Type context on the same line. Here are some examples:

https://github.com/dotnet/runtime/blob/5dcc340a17e32d81dc12f644449c8b58396b2fd7/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L223-L225

https://github.com/dotnet/runtime/blob/5dcc340a17e32d81dc12f644449c8b58396b2fd7/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L403-L409

https://github.com/dotnet/runtime/blob/5dcc340a17e32d81dc12f644449c8b58396b2fd7/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L525-L528

And probably the "worst" one, because you need to find out what `dict` is typed as, and then parse the `TValue` of its Type to see what Type of object is getting created here:

https://github.com/dotnet/runtime/blob/5dcc340a17e32d81dc12f644449c8b58396b2fd7/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/CollectionsMarshalTests.cs#L283-L287

In these cases, it feels like this violates the reasoning behind this [coding style rule](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md):

> 10. We only use `var` when the type is explicitly named on the right-hand side, typically due to either `new` or an explicit cast, e.g. `var stream = new FileStream(...)` not `var stream = OpenStandardInput()`.

I think we should add the converse rule here, and only allow `new()` when the type is explicitly named on the left-hand side.

cc @stephentoub

**Comment by bartonjs** [comment]
Doesn't seem like there's any dissent.

Two potential edits:

```diff
10. We only use `var` when the type is explicitly named on the right-hand side, typically due to either `new` or an explicit cast, e.g. `var stream = new FileStream(...)` not `var stream = OpenStandardInput()`.
+   - Similarly, target-typed `new()` can only be used when the type is explicitly named on the left-hand side, in a variable definition statement or a field definition statement. e.g. `FileStream stream = new(...);`, but not `stream = new(...);` (where the type was specified on a previous line).
```

```diff
19. Make all internal and private types static or sealed unless derivation from them is required.  As with any implementation detail, they can be changed if/when derivation is required in the future.
+20. We only use target-typed `new()` when the type is explicitly named on the left-hand side.  Thus, `FileStream stream = new(...);` is acceptable, but `stream = new(...);` is not.
```
