### ISSUE TITLE
.NET 6 Preview 4 Blazor AOT - Low End mobile devices - Out Of Memory

### ISSUE THREAD

**Issue by Erakx** [dotnet/runtime#53365]
### Describe the bug
With .NET 6 Preview 4 Blazor AOT, low end mobile devices run exception on page load.

**Devices used:** 
- iPhone 6 iOS 12.5.2 : Browser : Safari
- Samsung Galaxy S8 Android 9. Browser : Samsung internet 14.0.3.5

### Exceptions
**iPhone 6 (on page load). Error:**
[Error] Error: Out of memory

printErr (blazor.webassembly.js:1:27263)
(fonction anonyme) (blazor.webassembly.js:1:28713)
asyncFunctionResume
(fonction anonyme)
promiseReactionJob

**Samsung Galaxy S8 (on page load or if load success, when reload). Error:**
Streaming compilation failed. Falling back to ArrayBuffer instantiation.  RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
blazor.webassembly.js:1 TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js:1
    at async https:/perl.azurewebsites.net/_framework/blazor.webassembly.js:1
    at async https:/perl.azurewebsites.net/_framework/blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js:1
    at async https:/perl.azurewebsites.net/_framework/blazor.webassembly.js:1
    at async https:/perl.azurewebsites.net/_framework/blazor.webassembly.js:1

### To Reproduce
Upgrade a project to preview 4 and publish on azure with AOT Compilation.

### dotnet --info

SDK .NET (reflétant tous les fichiers global.json):
 Version:   6.0.100-preview.4.21255.9
 Commit:    950e4949a7

Environnement d'exécution:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\

Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by JinShil** [comment]
I ran into this also using a Raspberry Pi 3.

**Comment by lewing** [comment]
this is a hard problem to solve in the general case, AOT'd code is going to be much larger than interpreted code despite a very large amount of work that has been done to link out unused code.  It would be nice if we had a built in way to load the interpreter on memory constrained devices but that wouldn't help with execution speed.

**Comment by JinShil** [comment]
The default Blazor WASM project (hosted), when published as self-contained, trimmed, and with AoT, is only about 80MB.  The wwwroot\_framework folder is only about 30MB.  Yet, it still causes this out of memory error when running on a system with 1GB of memory, 600MB of which is free.  What specifically is consuming so much memory?

**Comment by lewing** [comment]
cc @pranavkm @SteveSandersonMS

**Comment by danroth27** [comment]
@JinShil I think you might be looking at the wrong files. The ASP.NET Core server project doesn't get downloaded to the browser - only published output from the client project should get download. In .NET 5, the total published output size of the client project should be just over 2MB (trimmed and compressed). In .NET 6 with AOT, the published size should be just under 4MB.

Regardless, why this results in an out of memory error on some devices still needs to be investigated..

**Comment by JinShil** [comment]
@danroth27  I understand.  I was intentionally overcounting the size of the application hoping to illustrate that there simply isn't enough data to justify the out of memory error.  The error should be easily reproducible on the Raspberry Pi 3 running the default Blazor WASM project.  I hope that helps with troubleshooting.

**Comment by h3x4d3c1m4l** [comment]
Firefox memory usage shows a 512 MB arraybuffer. This is preview 5 and the app is published in Release+AoT mode.

![image](https://user-images.githubusercontent.com/2611894/125627665-2bfc2fbf-0123-4a84-9ae1-ca80f55ee5c3.png)

This is the same app running from Visual Studio (so Debug mode + not AoT):

![image](https://user-images.githubusercontent.com/2611894/125627921-36eae972-d468-4e12-8d4e-a5b4a895626f.png)

**Comment by h3x4d3c1m4l** [comment]
I think this line of code might be the issue: https://github.com/dotnet/runtime/blob/56d9474f530579c67b294cbbde0724e966dbb05b/src/mono/wasm/build/WasmApp.Native.targets#L256

Perhaps this can be lowered to something like 128 MB? I just can't find how to override using my csproj (perhaps this is not possible, but I should be able to change it in the .target/.props files of the Sdk). Will report back whenever I tested it :)

**Comment by h3x4d3c1m4l** [comment]
In `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.5.21301.5\Sdk\WasmApp.targets` I changed the following line:

`<EmccLDFlags>$(EmccFlags) -s TOTAL_MEMORY=536870912</EmccLDFlags>`

to:

`<EmccLDFlags>$(EmccFlags) -s TOTAL_MEMORY=134217728</EmccLDFlags>`

I now see this in my browser:

![image](https://user-images.githubusercontent.com/2611894/125735075-74c733d1-1889-42f8-ad84-1e6baf194482.png)

This looks a lot better. I still have to test on the more 'limited' devices I have available.

**Comment by lewing** [comment]
We can definitely make this more easily configurable now that the required tooling is part of the workload.

**Comment by legistek** [comment]
So does this mean we have to decide in advance what our app's maximum ram usage is going to be? And presumably pick something that is appropriate for our minimum device target? That seems like it could get real dicey.

**Comment by h3x4d3c1m4l** [comment]
@legistek No, only if .NET would invoke Emscripten with the parameter to disallow memory growth. See [here](https://emscripten.org/docs/optimizing/Optimizing-Code.html) for more info on that.

But that is not the case. So this value will just be the initial amount of memory that your WASM app allocates.

**Comment by pavelsavara** [comment]
See also https://github.com/dotnet/runtime/pull/80849
