### ISSUE TITLE
The RuntimeIdentifier platform 'browser-wasm' and the PlatformTarget 'x64' must be compatible

### ISSUE THREAD

**Issue by FrantzUml** [dotnet/runtime#53379]
When A webassembly blazor is created, we got errors when targeted x64 : NETSDK1032	La plateforme de RuntimeIdentifier 'browser-wasm' et le PlatformTarget 'x64' doivent être compatibles.

**Comment by lewing** [comment]
what version of dotnet are you using?

can you provide a simple test case?
