### ISSUE TITLE
[Webassembly] Calling static methods via interop mechanisms doesn't seem to support typedarrays as arguments

### ISSUE THREAD

**Issue by javiercn** [dotnet/runtime#53378]
### Description

When calling .NET from JS in WebAssembly and providing a typed array as argument, the array doesn't correctly appear on the .NET side.

This works correctly when .NET calls JS and the array is provided as a return value.

```js
const method = Binding.bind_static_method('fqn.MyMethod');
const arr = new Uint8Array(...);
const result = method(arr);
```

```csharp
public static int MyMethod(byte [] data)
{
    return data.Length;
}
```

If .NET calls JS and the JS function returns an UInt8Array it works correctly:

```js
function jsReturnsUint8Array()
{
    const arr = new Uint8Array(...);
    return arr;
}
```

### Configuration

* Which version of .NET is the code running on?
WebAssembly
* If you're using Blazor, which web browser(s) do you see this issue in?
Edge 90 (although likely happens in all browsers)

### Regression?

Unknown

**Comment by kg** [comment]
I don't believe we can support this. The JS array would have to be copied into a temporary .NET array, then copied back upon return and discarded. The only types we could theoretically pass that TypedArray as are T* and Span<T>.
