### ISSUE TITLE
[Mono] Mark long running/weird runtime tests with outer loop flag.

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#53386]
The long running/weird runtime tests are
- GC/Scenarios/LeakWheel/leakwheel/leakwheel.sh

**Comment by SamMonoRT** [comment]
Where do you actually mark them ? In issues.target file, or some other file maintaining a list of long running tests meant for outer loop only ?

**Comment by fanyang-mono** [comment]
> Where do you actually mark them ? In issues.target file, or some other file maintaining a list of long running tests meant for outer loop only ?

I don't know exactly how to do it now. I will need to find out.

**Comment by SamMonoRT** [comment]
@akoeplinger @ViktorHofer - any idea where that flag is to mark long running tests to run only in outer loop ?

**Comment by ViktorHofer** [comment]
That's a code change. Add the `[Outerloop]` attribute to the test.
