### ISSUE TITLE
[wasm] Build improvements ideas

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#53394]
Based on @lewing's review of https://github.com/dotnet/runtime/pull/52941

- [ ] Can runtime packs have a props file that would get imported automatically?
- [ ] Consider moving some bits of Emscripten property checks and setup to the WorkloadManifest package.
- [x] For the link step we pass `-s TOTAL_MEMORY=536870912` - should this become a property?

**Comment by radical** [comment]
@akoeplinger any idea about `Can runtime packs have a props file that would get imported automatically?`

I couldn't find anything on this, and trying it locally it didn't seem to work.

**Comment by akoeplinger** [comment]
@radical I'm not aware of anything that imports .props for runtime packs, they're treated specially by the .NET SDK and not really like a normal nuget package. We could come up with some logic that we put into the .NET SDK though.

**Comment by radical** [comment]
Merged the todo items with https://github.com/dotnet/runtime/issues/50287 .
