### ISSUE TITLE
Consider removing the System.Memory dependency from TestUtilities on .NETFramework

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53422]
Currently VS fails to transitively build the System.Runtime.CompilerServices.Unsafe.ilproj reference in TestUtilities.csproj when a test project is built. This is likely connected to the reference pointing to a non standard C# project (ilproj).

As a mitigation and to speed up the build on .NET Framework test projects we should consider removing the System.Memory dependency for the net461 build of TestUtilities.csproj as only System.Text.Encodings.Web depends on the BoundedMemory functionality on .NETFramework.

Alternatively we might be able to investigate why VS fails to build the transitive dependency but I'm unsure where to start here.

cc @GrabYourPitchforks @ericstj @Anipik @safern

**Comment by GrabYourPitchforks** [comment]
Can we make the netframework build of TestUtilities depend on the NuGet versions of these packages rather than the live-built versions?

**Comment by ViktorHofer** [comment]
> Can we make the netframework build of TestUtilities depend on the NuGet versions of these packages rather than the live-built versions?

That isn't possible as source projects intentionally target the live built version of System.Runtime.CompilerServices.Unsafe. Mixing these with a reference to the package will make NuGet unhappy.

I would love to root causing why the ilproj isn't built transitively inside VS instead of working around it. Unfortunately I doubt that the project-system folks or I will have cycles to spend time on it anytime soon...

**Comment by ViktorHofer** [comment]
> Currently VS fails to transitively build the System.Runtime.CompilerServices.Unsafe.ilproj

Closing as that project doesn't exist anymore. Unsafe is now just a boring C# project that type forwards to CoreLib.
