### ISSUE TITLE
Download CoreCLR product download for Mono failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53421]
```
Starting: Download CoreCLR product download for Mono
==============================================================================
Task         : Download build artifacts
Description  : Download files that were saved as artifacts of a completed build
Version      : 0.186.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-build-artifacts
==============================================================================
Downloading artifacts for build: 1161146
##[error]Artifact CoreCLRProduct___Linux_arm64_release not found for build 1161146. Please ensure you have published artifacts in any previous phases of the current build.
Finishing: Download CoreCLR product download for Mono
```

cc @naricc @akoeplinger @steveisok

**Comment by akoeplinger** [comment]
@ViktorHofer do you have an example build log? no idea why this would fail.

**Comment by ericstj** [comment]
Based on his comments I imagine it's https://dev.azure.com/dnceng/public/_build/results?buildId=1161146&view=logs&j=ecfd4eca-a79d-5010-5cc7-224332d2af8a&t=236bfeb8-30a9-5be2-64ba-6046b281294b

Perhaps this is due to the other CoreCLR build leg failing? Tracked in https://github.com/dotnet/runtime/issues/53420

That'd still be a problem here since we shouldn't sequence builds if their dependent builds failed.

**Comment by ViktorHofer** [comment]
Sorry for the to include the link. Eric already found the respective build. Question, why does Mono still depend on CoreCLR assets? Shouldn't we avoid such a dependency?

**Comment by akoeplinger** [comment]
That's the way these runtime tests are setup now, I'm not familiar exactly why they're doing it that way. Presumably so we don't need to rebuild all the tests again and just swap the runtime in CORE_ROOT.

**Comment by naricc** [comment]
@ViktorHofer  Right now for the runtime tests, we actually have to build coreclr to get corerun, and then patch it with mono runtime bits. I have an issue assigned to me to fix this by just building a more version of "corerun", but haven't gotten to it yet.

**Comment by ViktorHofer** [comment]
"Fixed" in https://github.com/dotnet/runtime/pull/54094
