### ISSUE TITLE
SerialPort.BytesToWrite return a wrong value on linux

### ISSUE THREAD

**Issue by dmrayt** [dotnet/runtime#53430]
### Description

The property SerialPort.BytesToWrite doesn't work on Linux, it's return the same value as SerialPort.BytesToRead.

### Configuration

.NET 5.05
Embedded Linux kernel 5.4.77 ARM64

### Regression?

The code is working on Windows, I never tested it on Linux before.

### Other information

The error come from a wrong parameter passed from SerialStream.Unix.cs to pal_termios.cs.
In SerialStream.ByteToWrite an enum for the queue is passed to TermiosGetAvailableBytes(), in pal_termios.cs the function SystemIoPortsNative_TermiosAvailableBytes() want a boolean to decide which queue should be read.

**Comment by adamsitnik** [comment]
Hi @dmrayt 

Thank you for detailed bug report. Since you have found the source of the issue, would you be interested in sending a PR with a fix?
