### ISSUE TITLE
[wasm] AOT build doesn't handle satellite assemblies correctly

### ISSUE THREAD

**Issue by lbargaoanu** [dotnet/runtime#53431]
I'm trying to AOT compile a [project](https://github.com/lbargaoanu/RoslynInBlazor/blob/master/RoslynInBlazor/RoslynInBlazor.csproj) that references Roslyn.
It says it cannot find some assemblies. I'm guessing it should find them by itself. But I can help with [that](https://github.com/lbargaoanu/RoslynInBlazor/blob/744e6dc846ff2b4f67390219ca530ddd475f1362/RoslynInBlazor/RoslynInBlazor.csproj#L12).
After explictly adding that package, I get "Bug: Number of aot assemblies doesn't match the number of generated bitcode files. BitcodeFiles: 100 vs Assemblies: 172".
Ideally, the compile would succeed just with the Roslyn package.

**Comment by pranavkm** [comment]
FYI @radical / @lewing

**Comment by lewing** [comment]
The failure here is an overly restrictive sanity check on the aot output.  @radical please remove the check.

**Comment by lewing** [comment]
I take that back, they're getting added to the list of assemblies to AOT then the aot step isn't preserving the path information so they overwrite each other and the count is off as a result.  @radical is working on a fix for both issues.

**Comment by radical** [comment]
@lbargaoanu You can workaround the issue by adding this to your csproj:

```xml
 <Target Name="RemoveSatelliteAssemblies" BeforeTargets="WasmBuildApp">
    <ItemGroup>
      <WasmAssembliesToBundle Remove="@(WasmAssembliesToBundle)" Condition="$([System.String]::Copy('%(Identity)').EndsWith('.resources.dll'))" />
    </ItemGroup>
  </Target>
```

**Comment by lbargaoanu** [comment]
@radical Thanks, I'll try that.
