### ISSUE TITLE
VS can't debug a trimmed win-x64 app

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#53448]
Using the latest 6.0 SDK from https://github.com/dotnet/installer#installers-and-binaries:

1. `dotnet new console`
2. `dotnet publish -p:PublishTrimmed=true -r win-x64 `
3. Open the project in Visual Studio (I used `Version 16.10.0`)
4. In the `Project Properties` => `Debug` window, set the `Launch: Executable` and the `Executable:` path to `<project dir>\bin\Debug\net6.0\win-x64\publish\HelloWorld.exe`
5. F5

### Expected results
My app should launch and the debugger should be attached.

### Actual results

```
Fatal error. Internal CLR error. (0x80131506)

C:\DotNetTest\HelloWorld\bin\Debug\net6.0\win-x64\publish\HelloWorld.exe (process 26872) exited with code -2146233082.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

### Notes

The app runs fine with executed from the command line. It just fails to launch under the debugger.

cc @vitek-karas @mikem8361

**Comment by vitek-karas** [comment]
This needs somebody with experience of debugging the debuggee - I tried... and failed miserably.
The obvious guess is that trimming removes some type/method which is crucial for debugging. Is there some kind of logging we can turn on to get a better error, or something like that?

**Comment by hoyosjs** [comment]
I tried producing this in 7.0 preview 6 and  6.0.400-preview.22330.6 and I was able to debug this with no issues. @vitek-karas @eerhardt have you seen this happen still?

**Comment by vitek-karas** [comment]
I haven't seen this for a long time - I've actually worked on some "VS debugging trimmed code" stuff recently and it worked just fine.

**Comment by hoyosjs** [comment]
I'm closing this then. If you find a repro with something that didn't root  and we end up in an EE fault, let me know please :)
