### ISSUE TITLE
StreamPipeReader.ReadAsync() throws a NullReferenceException when CancelPendingRead() is called during a zero-byte read

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/runtime#53451]
Affected Mac:
Mac OS: Big Sur(11.4)
.NET 6 SDK: 6.0.100-preview.5.21277.7(runtime 6.0.0-preview.5.21276.11)

Repro steps:
1. Download and install 6.0.100-preview.5.21277.exe from [Pipelines - Run Creating-release-for-build-91923 artifacts (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D1159998%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=04%7C01%7Cv-huwang%40microsoft.com%7C7d7da5b4bd4c4313225e08d92167ab77%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637577551501177962%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=E7Viv%2F7jnDE2NB1VS5Df97i0h5I9H%2BoFAMs21JiSzWE%3D&reserved=0)

2. Dotnet new web in CLI

3. Dotnet build and dotnet run

4. Open safari browser and input "https://localhost:5001"

5. In CLI, hit ctrl +c to stop web running

Expected Result:
Stop web running successfully without any warning.

Actual Result:
Warn "Microsoft.AspNetCore.Server.Kestrel[0],Connection processing ended abnormally. " occurred.
![image](https://user-images.githubusercontent.com/46206739/119963013-32251980-bfda-11eb-8842-fca65e6880e3.png)

Note:
It not repro when hit ctrl +c after quit safari browser.

**Comment by stephentoub** [comment]
> I find that unexpected @wfurt.

I assume from your mentioning Tomas that the underlying stream is an SslStream? What kind of Stream is it in turn wrapping?

**Comment by davidfowl** [comment]
In Kestrel, SSLStream.

**Comment by davidfowl** [comment]
Well, it's an SslStream wrapping our own Stream in Kestrel, so it might be our stream as well.

**Comment by stephentoub** [comment]
> so it might be our stream as well

Right,  I was asking what the SslStream is wrapping. It's delegating to the inner stream at https://github.com/dotnet/runtime/blob/c6b5994fbc251ef99c90ed05ce8b10059778e7cd/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L797; if the token had cancelation requested, I'd have expected that to throw.

**Comment by davidfowl** [comment]
Yah:

https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/Shared/ServerInfrastructure/DuplexPipeStream.cs#L123-L128

**Comment by stephentoub** [comment]
> Yah

I assume that `_throwOnCancelled` is false and that's why it's returning 0 rather than throwing?

**Comment by halter73** [comment]
`_throwOnCancelled` should only affect `PipeReader.CancelPendingRead()`/`ReadResult.IsCanceled`. It shouldn't affect what happens given a canceled token imo. Looking at the code, it looks like the CancellationToken is flowed to the underlying Stream and I don't see anything catching an OperationCanceledException. It's not necessarily an SslStream issue though. It could also be something to do with Kestrel's Socket transport.
