### ISSUE TITLE
CoreCLR non-Windows cmake build error

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#53466]
CoreCLR non-Windows builds have this warning/error:
```
-- Configuring done
CMake Error at /__w/1/s/src/native/corehost/exe.cmake:23 (add_executable):
  Cannot find source file:

    /__w/1/s/artifacts/obj/coreclr/Linux.x64.Checked/utilcode/CMakeFiles/utilcode_obj.dir/clrhost_nodependencies.cpp.o

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  /__w/1/s/src/native/corehost/apphost/static/CMakeLists.txt:92 (include)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
/__w/1/s
/__w/1/s/artifacts/obj/coreclr/Linux.x64.Checked /__w/1/s
```

E.g., https://dev.azure.com/dnceng/public/_build/results?buildId=1162592&view=logs&j=54cabf5c-1ba4-54c9-31cb-a3ef0d378039&t=43aed140-0b0f-5596-36b8-b27458d6e610

@jkoritzinsky Do errors from cmake invocations not fail the builds?
@dotnet/runtime-infrastructure

**Comment by NikolaMilosavljevic** [comment]
[Triage] @hoyosjs can you share the reasons for moving to installer?

**Comment by hoyosjs** [comment]
@NikolaMilosavljevic Historically, core-setup / host issues have been tracked in installer

**Comment by agocke** [comment]
Looks like this isn't happening anymore. Closing.
