### ISSUE TITLE
How to create static library from system.text.json?

### ISSUE THREAD

**Issue by subhamvs** [dotnet/runtime#53472]
Hi all,
When I am installing [system.text.json](https://www.nuget.org/packages/System.Text.Json) via Nuget manager. I could see that dll (dynamic library) installed and linked with my sln executable. Please share the way to generate static lib for System.Text.Json library?

**Comment by huoyaoyuan** [comment]
lib is an unmanaged concept and not applicable to .NET. A similar technology is ILLink which can merge multiple .NET assemblies into one.
