### ISSUE TITLE
Better System.Half integration in existing APIs

### ISSUE THREAD

**Issue by Dotpys** [dotnet/runtime#53481]
## Background and Motivation

Currently there are various APIs using different data types like integers and floats but some of them lacks support for the float16 (System.Half) data type introduced in .NET 5.

In my particular case I work with graphics data and would be nice to have some sort of integration of the System.Half type inside of the System.IO.BinaryReader class, like a ReadHalf() method. As for now the only workaround i found is reading the number as a short and copy the binary data to a Half variable in a custom static method for the short data type.

```C#
public static unsafe Half ToHalf(this short value)
{
    Half result;
    Buffer.MemoryCopy(&value, &result, 2, 2);
    return result;
}
```

Altohugh this is very specific, it could be a starting point for other APIs to make use of the Half data type.

## Proposed API
```diff
namespace System.IO
{
      public class BinaryReader : IDisposable
      {
+           public virtual System.Half ReadHalf();
      }
}
```

## Usage Examples

This is an use case for one of my projects
``` C#
BinaryReader vertexBufferReader = new BinaryReader(vertexBufferStream);
for(int i=0; i<256; i++)
{     //Reads the X, Y, Z, W components in order.
      normals[i][0] = vertexBufferReader.ReadHalf();
      normals[i][1] = vertexBufferReader.ReadHalf();
      normals[i][2] = vertexBufferReader.ReadHalf();
      normals[i][3] = vertexBufferReader.ReadHalf(;
}
```

**Comment by tannergooding** [comment]
This binary was already reviewed, approved, and implemented and is in the latest .NET 6 previews: https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader.readhalf?view=net-6.0#System_IO_BinaryReader_ReadHalf

Similar support was added to `BinaryWriter` and `BinaryPrimitives`: https://github.com/dotnet/runtime/issues/38456
