### ISSUE TITLE
Simplify names of DateOnly and TimeOnly

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/runtime#53496]
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/DateOnly.cs

The names should be

1. DateTime
2. Date
3. Time

The word "Only" is unneeded additional text.

We don't differentiate between a number with a decimal place (Decimal) and a number without a decimal by suffixing the word "Only" after all the whole-number types - I don't think we should do it for Date or Time either.

**Comment by Joe4evr** [comment]
https://github.com/dotnet/runtime/issues/49036#issuecomment-802237375
