### ISSUE TITLE
Should TimeOnly.IsBetween return True or False when start==end ?

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#53492]
https://github.com/dotnet/runtime/blob/fea7ff2cce79da2df9cf1c50ce215287750f055e/src/libraries/System.Private.CoreLib/src/System/TimeOnly.cs#L178

Think scenario below:
```
Shop A: 8:00-21:00
Shop B: 20:00-8:00
Shop C: 0:00-0:00 (24:00 is not allowed)
```
I would think that Shop C is a 24 hour shop. 

However, `anyTime.IsBetween(TimeOnly.MinValue, TimeOnly.MinValue)` returns False, which is not very intuitive. I'd suggest that `IsBetween` returns True if `start`==`end`. Or at least, the behavior should be documented.

**Comment by iSazonov** [comment]
It was explicit design decision to implement `[ ... )` range (with exclusive right bound).
/cc @tarekgh

**Comment by skyoxZ** [comment]
> It was explicit design decision to implement `[ ... )` range (with exclusive right bound).
> /cc @tarekgh

It also supports ranges that span midnight. The question is, does 1:00-1:00 span midnight? I think we need a way to represent a full-day range much more than an empty range.

**Comment by tarekgh** [comment]
> It also supports ranges that span midnight. The question is, does 1:00-1:00 span midnight? 

No. 

> We need a way to represent a full-day range much more than an empty range.

You can represent the full day by something like 

```C#
    TimeOnly t1 = new TimeOnly(1, 0, 0);
    TimeOnly t2 = new TimeOnly(1, 0, 0).Add(new TimeSpan(-1));
    Console.WriteLine(new TimeOnly(0, 0, 0).IsBetween(t1, t2));
```

I am closing the issue but feel free to reply with any question and we'll be happy to help with.

**Comment by skyoxZ** [comment]
> You can represent the full day by something like
> 
> ```cs
>     TimeOnly t1 = new TimeOnly(1, 0, 0);
>     TimeOnly t2 = t1.Add(new TimeSpan(-1));
>     Console.WriteLine(new TimeOnly(0, 0, 0).IsBetween(t1, t2));
> ```

@tarekgh  It's not full day: `t2` is not in [`t1`, `t2`)

**Comment by tarekgh** [comment]
@skyoxZ thanks for the reply. I reactivated the issue to provide some solution for that.

**Comment by mattjohnsonpint** [comment]
I think we should document the behavior, but it should not change.  Given any two numeric values that are exactly the same, there is zero quantity between them.  `3 - 3 = 0`.  Likewise, any two `TimeOnly` values that are the same has zero elapsed duration between them. `03:00:00 - 03:00:00 = 0 seconds`.

If you want to treat `t2` as being the next day, then you can do a separate check:

```csharp
bool result = t1 == t2 || t.IsBetween(t1, t2);
````

**Comment by mattjohnsonpint** [comment]
I do think, however that we should support parsing `"24:00"`, possibly with another API with an `out bool nextDay` overload.  That can be tracked in a separate issue.

**Comment by skyoxZ** [comment]
> If you want to treat `t2` as being the next day, then you can do a separate check:
> 
> ```cs
> bool result = t1 == t2 || t.IsBetween(t1, t2);
> ```

I believe most use cases of `IsBetween` want to treat `t2` as being the next day if `t1`==`t2`.

**Comment by tarekgh** [comment]
> I believe most use cases of IsBetween want to treat t2 as being the next day if t1==t2.

I would prefer to have the users be explicit about that and not assuming any behavior different than the generic behavior of the API. I mean testing `t1 == t2` is more explicit showing the intention.
