### ISSUE TITLE
QUIC: IPv6 constant looks suspicious in native helper

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#53495]
I noticed this while reviewing #53461.

```c#
namespace System.Net.Quic.Implementations.MsQuic.Internal
{
    internal static class MsQuicAddressHelpers
    {
        internal const ushort IPv4 = 2;
        internal const ushort IPv6 = 23;

..
       internal static SOCKADDR_INET IPEndPointToINet(IPEndPoint endpoint)
       {
                       socketAddress.Ipv6._family = IPv6;

```

AF_INET6 is 10 on Linux and 30 on macOS. It feels like this should come from PAL.
It also seems like our tests use CreateQuicListener() that use IPEndPoint(IPAddress.Loopback, 0) so we may have test gaps for IPv6.

**Comment by treysis** [comment]
Loopback/localhost shouldn't be used. It is very unclear what the system will resolve it to. Either you specify the address family, or you use literal addresses for localhost.

**Comment by ThadHouse** [comment]
In MsQuic, we ensure all IPv6 family values seen through the API are 23, to match windows.
