### ISSUE TITLE
QUIC: revisit support for ServerCertificateContext

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#53507]
#53175 added support for ServerCertificateContext. While it is functionally complete, it uses reflection to access private members of the ServerCertificateContext. This happens once per server so there may not be performance issue but it may become maintenance hassle. 
We should look into new API so we can access everything directly. (or find some other solution)

**Comment by rzikm** [comment]
Proposal to make `ServerCertificateContext` properties public: #67552
