### ISSUE TITLE
Microsoft.DotNet.PackageTesting is hardcoding OS and arch values

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53521]
See this section: https://github.com/dotnet/arcade/blob/c7d6bd607715f334cda90e01967bb0c02dee09be/src/Microsoft.DotNet.PackageTesting/GetCompatiblePackageTargetFrameworks.cs#L143-L150.

The PackageTesting logic should not hardcode the child values for Unix and also not assume that every OS offers an x64 architecture. In general it would be best if the OS and the Architecture isn't hardcoded at all.

cc @Anipik @ericstj

**Comment by ericstj** [comment]
I believe this was fixed in https://github.com/dotnet/arcade/pull/7510
