### ISSUE TITLE
GenFacades error when trying to build System.Configuration.ConfigurationManager inside VS

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53529]
```
14>C:\Users\vihofer\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21276.5\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Security.Policy.Evidence' in any of the seed assemblies.
14>C:\Users\vihofer\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21276.5\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Security.Policy.EvidenceBase' in any of the seed assemblies.
14>Done building project "System.Security.Permissions.csproj" -- FAILED.
```

Repro steps:
```
build.cmd clr+libs -rc Release
build.cmd -vs System.Configuration.ConfigurationManager
```

cc @Anipik @ericstj

**Comment by Anipik** [comment]
@ViktorHofer  what are the steps to repro here ? build -s clr.libs followed by build -vs projectName  ?

**Comment by ViktorHofer** [comment]
Updated the top post with the repro step.

**Comment by ericstj** [comment]
Those types were pushed down to `System.Security.AccessControl`.  I'm guessing that you don't have that project in the SLN.

**Comment by ViktorHofer** [comment]
S.S.AccessControl is part of the solution file:

![image](https://user-images.githubusercontent.com/7412651/120360794-70d41000-c309-11eb-9794-f4513e24458a.png)

**Comment by ericstj** [comment]
Just tried this and it didn't repro for me.  @ViktorHofer perhaps https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f made this go away?

**Comment by ericstj** [comment]
I was able to reproduce this error in another project and understand the problem (see #51601)  Will submit a fix for this.

**Comment by ericstj** [comment]
Closing as this is no-repro in latest.
