### ISSUE TITLE
JIT assertion failure in CG2 compilation of Interop\PInvoke\Vector2_3_4\Vector2_3_4\Vector2_3_4.cmd

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#53558]
OS: **Windows**
Architecture: **x86**
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1165903&view=ms.vss-test-web.build-test-results-tab&runId=35147306&resultId=103194&paneView=debug

Diagnostic information:

<pre>
" "dotnet" "C:\h\w\B46509BB\p\crossgen2\crossgen2.dll" @"C:\h\w\B46509BB\w\B78D0A64\e\Interop\PInvoke\Vector2_3_4\Vector2_3_4\Vector2_3_4.dll.rsp"   -r:C:\h\w\B46509BB\w\B78D0A64\e\Interop\PInvoke\Vector2_3_4\Vector2_3_4\IL-CG2*.dll -r:C:\h\w\B46509BB\w\B78D0A64\e\Interop\PInvoke\Vector2_3_4\Vector2_3_4\IL-CG2*.dll"
D:\workspace_work\1\s\src\coreclr\jit\emitxarch.cpp:4351
Assertion failed '!"Please use emitIns_Mov() to correctly handle move elision"' in 'Vector2_3_4TestNative:CreateVector2FromFloats(float,float):System.Numerics.Vector2' during 'Generate code' (IL size 18)

D:\workspace_work\1\s\src\coreclr\jit\emitxarch.cpp:4351
Assertion failed '!"Please use emitIns_Mov() to correctly handle move elision"' in 'Vector2_3_4Test:RunVector2Tests()' during 'Generate code' (IL size 398)

Crossgen2 failed with exitcode - -2147483645
Test Harness Exitcode is : 1
</pre>

/cc @dotnet/crossgen-contrib @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
cc @tannergooding

**Comment by tannergooding** [comment]
Looking

**Comment by tannergooding** [comment]
Fix should be up here: https://github.com/dotnet/runtime/pull/53569
