### ISSUE TITLE
Ensure shared framework consumes source-built RID graph

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#53550]
Related to https://github.com/dotnet/runtime/pull/50818

I believe the shared framework build process is still consuming the statically defined, checked-in, runtime.json.

We need to make sure it uses the generated one.

I suggest we do this by making the shared framework always consume it from an output location (along with the assemblies, etc).  Then make the `Microsoft.NETCore.Platforms` project responsible for putting it there, whether it builds it or not.

Also we should consider scenarios like https://github.com/dotnet/runtime/pull/52907 where folks want to add RIDs without necessarily doing a source build.

Perhaps there is a way to use the RID generation process in more conditions while still ensuring the checked-in copy is up-to-date?

**Comment by ericstj** [comment]
Note that the fix here will likely require changes in installer and libraries.  It's likely going to be me fixing this if I can find the time to get to it.  Would love help identifying what to change in installer and how to test this sort of thing (EG: hypothetical new linux or new arch). cc @ViktorHofer @crummel

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic this seems important enough to keep in 6.0.

**Comment by ViktorHofer** [comment]
@ericstj as this issue still targets 6.0, do you have someone to work on it?

**Comment by ericstj** [comment]
I'll leave it to the owners of the area to make the call and fix it if they deem it necessary.  I don't see it as must fix for 6.0 unless there's a source build scenario that requires it.

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic should we keep this in 6.0 or move it out?

**Comment by tmds** [comment]
> I'll leave it to the owners of the area to make the call and fix it if they deem it necessary. I don't see it as must fix for 6.0 unless there's a source build scenario that requires it.

This is needed to make .NET 6.0 and .NET 7.0 source-build on new versions of a distro.

Currently maintainers need to patch the runtime graph before the build works.

If this is fixed on `main`, we can see if the patch works for .NET 6 and .NET 7. If it does, maintainers can include it, and no longer need to worry about updating the runtime graph.

>  Would love help identifying what to change in installer and how to test this sort of thing (EG: hypothetical new linux or new arch).

I have a long open issue for this: https://github.com/dotnet/source-build/issues/297.

We need to identify when we're using the _build host rid_ and when we're using the _target rid_.

The bootstrap SDK won't know about the unknown distro, so we may need to force it to be compatible. That's already possible by setting `DOTNET_RUNTIME_ID`. This controls the _build host rid_. For example: if we're using Microsoft's portable build, it can be set to `linux-x64`.

The target RID should be treated as the name of the thing we're building. Source-build is already passing this name as `TargetRid` to the runtime repo. `SourceBuild.props` then maps it to `PackageRid`. In https://github.com/dotnet/runtime/pull/74504 I'm exposing it as an arg on the top-level build script.

**Comment by tmds** [comment]
@ericstj I'm source-building .NET 7 with https://github.com/dotnet/runtime/pull/74504 on an unknown distro (I changed my `/etc/os-release` to `Fedora 39`). Besides the PR, I made a change to source-build so it sets `RuntimeOS` to `linux` during the runtime build to make it use the `linux-x64` prebuilts/sdk.

The build passes.

The `shared/Microsoft.NETCore.App/7.0.0-rc.2.22451.11/Microsoft.NETCore.App.deps.json` doesn't have a `runtimes` section like:
```
  "runtimes": {
    "fedora.39-x64": [
      "fedora.39",
      "fedora-x64",
      "fedora",
      "linux-x64",
      "linux",
      "unix-x64",
      "unix",
      "any",
      "base"
    ]
  }
```

That is tracked by this issue, right?

If we fix it, we should have all the bits we need to make .NET 7 source-build work on unknown distros.

**Comment by ericstj** [comment]
> **doesn't** have a runtimes section
> That is tracked by this issue, right?

It should be.  You do see that runtime listed in the `runtime.json` in the built `Microsoft.NETCore.Platforms`?

If so I believe all that's needed to fix this is to plumb the generated runtime.json into the shared framework build.
If not - then there might be more needed to plumb the new runtime into the RID graph generation process.

**Comment by NikolaMilosavljevic** [comment]
@MichaelSimons

**Comment by tmds** [comment]
> It should be. You do see that runtime listed in the runtime.json in the built Microsoft.NETCore.Platforms?

Yes, it's in the package `runtime.json` file.
