### ISSUE TITLE
XmlSerializer serialization of enum differs from .NET Framework (crashes)

### ISSUE THREAD

**Issue by nick-beer** [dotnet/runtime#53553]
The following code works in .NET Framework, but crashes in .NET 5:

```cs
using System.IO;
using System.Xml;
using System.Xml.Serialization;

namespace ConsoleApp11
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var ms = new MemoryStream())
            {
                var writer = XmlWriter.Create(ms);
                writer.WriteStartElement("Items");
                var serializer = new XmlSerializer(typeof(object));
                object o = MyItems.Shoes;
                serializer.Serialize(writer, o);
                writer.WriteEndElement();
            }
        }
    }

    public enum MyItems
    {
        Socks,
        Shoes,
        Shirt,
        Shorts
    }
}
```

In .NET 5, it throws an `InvalidOperationException` inside of `XmlSerializer.Serialize` [here](https://github.com/dotnet/runtime/blob/7e651850f7eeb69fa5e9a291197f22a9721a48a1/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriter.cs#L366).

It appears the difference (or one of them) is that [.NET Framework uses](https://referencesource.microsoft.com/#System.Xml/System/Xml/Serialization/XmlSerializationWriter.cs,180) `Type.GetTypeCode()` in the beginning of that method, which for this enum returns Int32.  In .NET 5, the t.GetTypeCode() extension method [is used](https://github.com/dotnet/runtime/blob/7e651850f7eeb69fa5e9a291197f22a9721a48a1/src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializationWriter.cs#L252), which just switches over the actual type of the object.

I couldn't find this change of behavior documented anywhere, and it's not immediately clear what a workaround might be.  The code above is obviously a much simplified version of the code in a core library used by applications running in both .NET Framework and .NET 5.

**Comment by mconnew** [comment]
This is a hangover from the early .NET Core 1.0 days when Type.GetTypeCode wasn't supported. The only reason this change was made was to work around the missing api.
