### ISSUE TITLE
CG2 runtime crash in JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\Runtime_34170.cmd

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#53560]
OS: **Windows**
Architecture: **arm**
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1165903&view=ms.vss-test-web.build-test-results-tab&runId=35147350&resultId=108556&paneView=debug

Diagnostic information:

<pre>
      Response file: D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\\Runtime_34170.dll.rsp
      D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\IL-CG2\Runtime_34170.dll
      -o:D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\\Runtime_34170.dll
      --targetarch:arm
      --verify-type-and-field-layout
      -r:D:\h\w\A64C0919\p\System.*.dll
      -r:D:\h\w\A64C0919\p\Microsoft.*.dll
      -r:D:\h\w\A64C0919\p\mscorlib.dll
      -r:D:\h\w\A64C0919\p\netstandard.dll
      -O
      " "dotnet" "D:\h\w\A64C0919\p\crossgen2\crossgen2.dll" @"D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\\Runtime_34170.dll.rsp"   -r:D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\IL-CG2\*.dll"
      Emitting R2R PE file: D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\\Runtime_34170.dll
       "D:\h\w\A64C0919\p\corerun.exe"  Runtime_34170.dll 
      1
      1
      Expected: 100
      Actual: -2146232797
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\A64C0919\p
      > D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\Runtime_34170.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Regression._JitBlue_Runtime_34170_Runtime_34170_Runtime_34170_._JitBlue_Runtime_34170_Runtime_34170_Runtime_34170_cmd()
      Output:
        Could Not Find D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\JitBlue\Runtime_34170\Runtime_34170\Runtime_34170.dll.rsp
        Process terminated. Assertion failed.
           at Test.Main() in Runtime_34170.dll:token 0x6000006+0x56
        
        Return code:      1
        Raw output file:      D:\h\w\A64C0919\w\AE010938\e\JIT\Regression\Reports\JIT.Regression\JitBlue\Runtime_34170\Runtime_34170\Runtime_34170.output.txt
        Raw output:
        BEGIN EXECUTION
        Runtime_34170.dll
                1 file(s) copied.
</pre>

/cc @dotnet/crossgen-contrib

**Comment by VincentBu** [comment]
Failed again in [runtime-coreclr r2r 20210609.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1179293&view=ms.vss-test-web.build-test-results-tab&runId=35496632&resultId=109342&paneView=debug)

Failed test:
```
R2R Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.sh

```
**Error message:**
```
/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.sh: line 254: -r:/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.dll.rsp': No such file or directory
Process terminated. Assertion failed.
at Test.Main() in Runtime_34170.dll:token 0x6000006+0x56
/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.sh: line 375:  9466 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/IL-CG2/Runtime_34170.dll
Response file: /root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.dll.rsp
/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/IL-CG2/Runtime_34170.dll
-o:/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.dll
in ReleaseLock
/root/helix/work/correlation/corerun Runtime_34170.dll ''
1
1
Gathering state for process 9466 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.9466.dmp
Written 61554688 bytes (15028 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_34170/Runtime_34170/Runtime_34170.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_34170_Runtime_34170_Runtime_34170_._JitBlue_Runtime_34170_Runtime_34170_Runtime_34170_sh()
```

**Comment by mangod9** [comment]
intermittent failure, moving to 7 for now.

**Comment by mangod9** [comment]
Closing since this hasnt reproed a while.

**Comment by MichalStrehovsky** [comment]
Hasn't reproduced because we don't run the test:

https://github.com/dotnet/runtime/blob/a54a823ece1094dd05b7380614bd43566834a8f9/src/tests/issues.targets#L922-L924

**Comment by trylek** [comment]
Closing as no recent repro.
