### ISSUE TITLE
[wasm][aot] Don't AOT the helper assemblies for `ApplyUpdateTest.StaticMethodBodyUpdate` in `System.Runtime.Loader` tests

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#53565]
[AOT tracking PR](https://github.com/dotnet/runtime/pull/52004) has:

```
[17:48:49] fail: [FAIL] System.Reflection.Metadata.ApplyUpdateTest.StaticMethodBodyUpdate
[17:48:49] info: Assert.Equal() Failure
[17:48:49] info:           â†“ (pos 0)
[17:48:49] info: Expected: NEW STRING
[17:48:49] info: Actual:   OLD STRING
[17:48:49] info:           â†‘ (pos 0)
```

According to @lambdageek we shouldn't be AOT'ing the assemblies being used by the `ApplyUpdateTests`(eg. https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Loader/tests/System.Runtime.Loader.Tests.csproj#L41)

We would need to set `%(WasmASsembliesToBundle._InternalForceInterpret)=true` for such assemblies.

Also, would be nice to have a common way of doing this across wasm/iOS/android.

Note: this doesn't fail on `main` because `System.Runtime.Loader.Tests` are disabled completely

**Comment by lewing** [comment]
Is there any reason to run this test when AOTing?  Do we have any plan to do hot reload in combination with AOT?

**Comment by lambdageek** [comment]
> Is there any reason to run this test when AOTing? Do we have any plan to do hot reload in combination with AOT?

@lewing yes - we should eventually support a hybrid execution mode where the BCL is AOTd but the user assemblies are interpreted and are hot-reloadable.  In principle the runtime can already support it.  (Maybe just on mobile, though)

**Comment by lewing** [comment]
This was more a question of "Are we officially supporting hot-reload on Wasm with aot+interp on .NET6" than "does it work" (it does).

cc @marek-safar

**Comment by marek-safar** [comment]
I don't think we need hybrid or full AOT support for webassembly hot reload. We could even block it with some error message to make it clear that something went wrong when settings things up.

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/54617
