### ISSUE TITLE
MonoVM: Missing runtime workloads for Mac Catalyst and macOS

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#53579]
### Description

Currently there are runtime workloads for iOS and tvOS:

https://github.com/dotnet/runtime/blob/dbb05eba3b229df3d4c15ce08de9f84c7febb7b3/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in#L33-L63

but we're missing runtime workloads for Mac Catalyst and macOS.

While not strictly necessary, this would make it easier for us to acquire the AOT compilers for Mac Catalyst and macOS.

CC @steveisok

**Comment by lewing** [comment]
actually it looks like there are only catalyst builds, do we need osx builds as well?

**Comment by steveisok** [comment]
Yeah, looks like we do.

**Comment by steveisok** [comment]
@rolfbjarne @dalexsoto I was under the impression that xam macos was using coreclr as the runtime.  Is that not correct?

**Comment by filipnavara** [comment]
> I was under the impression that xam macos was using coreclr as the runtime. Is that not correct?

It supports both and uses the `UseMonoRuntime` property to switch. The default is still set to Mono in current previews.

**Comment by rolfbjarne** [comment]
> > I was under the impression that xam macos was using coreclr as the runtime. Is that not correct?
> 
> It supports both and uses the `UseMonoRuntime` property to switch. The default is still set to Mono in current previews.

Correct, Mono is still the default, and you can set `UseMonoRuntime=false` to get CoreCLR.
