### ISSUE TITLE
Looking for secrets.json in debug path

### ISSUE THREAD

**Issue by LexRaaphorst** [dotnet/runtime#53584]
### Description

One of our developers (not all) is having an issue with AddUserSecrets in a test project:

        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<BaseTest>()
            .Build();
makes the fileprovider look for secrets.json in debug folder (net5.0) of the project. 

A MVC project in the same solution is looking in the correct folder for the secrets.json. The only difference I can find is VS2019 version (16.9.4 (not working) vs 16.9.3 (working)).

Any help is appreciated.

### Configuration

.Net 5.0
Windows10
X64

### Other information

We 'solved' it for now by copying the secrets.json to debug folder.

**Comment by maryamariyan** [comment]
Is this a bug for VS then?
