### ISSUE TITLE
Failed to build "CoreCLR component".

### ISSUE THREAD

**Issue by sangramsalunkhe97** [dotnet/runtime#53594]
During the compile "board.sh" facing the issue "Failed to build "CoreCLR component"".
**./build.sh**

![Failed_core_CLI](https://user-images.githubusercontent.com/81962828/120468629-0c738800-c3bf-11eb-8968-060b4ac1d206.png)

**Comment by hoyosjs** [comment]
This doesn't tell me much. Sorry. Can you try deleting `artifacts/obj/coreclr/Linux.x64.Debug/cmake_cmd_line.txt` (or the one for your build configuration) and retry? It's not obvious from you output what went wrong. We also recommend building inside Docker to ensure you have all the dependencies. The one we use for Linux x64 currently is `mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-20201227183837-5fe0e50` and instructions can be found in https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/linux-instructions.md
