### ISSUE TITLE
Incorrect documented IOException in ZipFile.ExtractToDirectory

### ISSUE THREAD

**Issue by pkanavos** [dotnet/runtime#53609]
In `ZipFile.ExtractToDirectory` and `ZipFileExtensions.ExtractToDirectory`, the remarks and documentation say that IOException is thrown if the destination directory already exists. This is incorrect, as the method that's eventually called, the internal [ExtractRelativeToDirectory](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFileExtensions.ZipArchiveEntry.Extract.cs#L87) method works fine with existing destination folders.

This was first asked in [this SO question](https://stackoverflow.com/questions/67806595/does-zipfile-extracttodirectory-throw-an-exception-when-the-directory-exists/67807550). I also opened an [issue in the dotnett-api-docs repo](https://github.com/dotnet/dotnet-api-docs/issues/6788)

https://github.com/dotnet/runtime/blob/0e557e8fb5b37fbbc57c0a56cae8cfd1ce61b610/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFile.Extract.cs#L64

**Comment by adamsitnik** [comment]
Hi @pkanavos 

Would you like to contribute a PR where you would remove the remark and add a test that ensures that it's true?

Thanks!

**Comment by Jozkee** [comment]
@pkanavos for System.IO.Compression namespace, the source of truth of documentation is the triple-slash comments in our source, can you please send the PR to this repo (dotnet/runtime) instead? We will port it to dotnet-api-docs ourselves, it's going to be automated soon.

cc @carlossanlop
