### ISSUE TITLE
Microsoft.Windows.Compatibility depends on non-existent package

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#53615]
In p5, I see this issue in package validation: https://dev.azure.com/dnceng/internal/_build/results?buildId=1166651&view=logs&j=38f37d44-1649-5acd-0b92-165e751e1470&t=e3a67328-30a8-5faa-9e47-9d1f680342f0&l=752

```
##[error]Microsoft.Windows.Compatibility.6.0.0-preview.5.21301.5.nupkg's dependency 'System.Security.Cryptography.Cng' upon versions: [6.0.0-preview.5.21301.5, ) not found locally nor in nuget.org
```

The System.Security.Cryptography.Cng package does not appear to have been produced since p4.

**Comment by bartonjs** [comment]
We turned off the package in https://github.com/dotnet/runtime/pull/51853.  It should be the case that .NET 6-based packages can just drop the package reference to the Cng package.

Looping in @ViktorHofer and @ericstj to make sure I'm correct.

**Comment by ericstj** [comment]
Yep, that's correct.  The Windows Compat package needs to be changed to refer to the old stable build of that package.

@mmitche can we do a manual fixup to the nuspec to not block P5?  The fix would be to change the version of CNG referenced from `6.0.0-preview.5...` version to `5.0.0`

**Comment by mmitche** [comment]
> Yep, that's correct. The Windows Compat package needs to be changed to refer to the old stable build of that package.
> 
> @mmitche can we do a manual fixup to the nuspec to not block P5? The fix would be to change the version of CNG referenced from `6.0.0-preview.5...` version to `5.0.0`

Yeah, I think we probably can. Let me look into it. Is the package unusable if we don't?

**Comment by ericstj** [comment]
I think the workaround might be to manually downgrade when referencing this package.  So it would look like this:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="6.0.0-preview.5.21301.5" />
    <PackageReference Include="System.Security.Cryptography.Cng" NoWarn="NU1605" Version="5.0.0" />
  </ItemGroup>
```
