### ISSUE TITLE
[workloads] Keeping workload updates compatible with older runtime versions

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#53621]
Context:

- `dotnet/runtime` has the workload manifest, and the packs
- `sdk` takes a reference to that, and populates `sdk-manifests`
- So, when the sdk is built, the `runtime` version that it includes is in sync with the version in `sdk-manifests` for the workloads

Problem:

- Given such a sdk *installation*
  - if you then install a workload version which is newer than what the sdk references,
  - then you get the newer packs, and a newer manifest
  - *but* the runtime pack is still the the older one that sdk was installed with

- This mismatch of versions can cause issues, eg. if the newer wasm targets are expecting to find some new files in the runtime pack

Question:
- What are the expectation of compatibility here, between the workload packs, and the runtime pack in the sdk?
- And how do we achieve that? And test?

cc @lewing @steveisok @akoeplinger @marek-safar

**Comment by marek-safar** [comment]
>  the runtime pack is still the the older one that sdk was installed with

Why is it the older one if the manifest includes an updated version of runtime pack too?

**Comment by steveisok** [comment]
> >  the runtime pack is still the the older one that sdk was installed with
> 
> 
> 
> Why is it the older one if the manifest includes an updated version of runtime pack too?

The sdk pins the runtime pack to its own version by default.  What each workload should do is provide KnownRuntimePack items with the right versions.

**Comment by marek-safar** [comment]
> The sdk pins the runtime pack to its own version by default. 

yeah, that seems wrong

**Comment by mhutch** [comment]
The MSBuild targets should be resolving the runtime pack versions from the workload manifest rather than listing them explicitly. /cc @dsplaisted

**Comment by mhutch** [comment]
My initial take is that the `ProcessFrameworkReferences` task should be reading the pack versions from the manifest and treating them as if they were `KnownRuntimePack` values, and the SDK should not contain explicit `KnownRuntimePack` values for packs shipped in manifests.

**Comment by dsplaisted** [comment]
This is an old bug, I believe it was addressed with https://github.com/dotnet/sdk/pull/19596.

I think this can be closed.

**Comment by radical** [comment]
> This is an old bug, I believe it was addressed with [dotnet/sdk#19596](https://github.com/dotnet/sdk/pull/19596).
> 
> I think this can be closed.

Yeah, that sounds correct. Closing this. @lewing please re-open if anything is pending here.
