### ISSUE TITLE
CoreCLR runtime error: 0x80131022

### ISSUE THREAD

**Issue by ssaarian** [dotnet/runtime#53640]
My dotnet 5 wrapper/hosting project runs ok at c++ console app, and as compiled dll at c++ console app, however, when I run this at c# console- I'm getting and error: CoreCLR runtime error 0x80131022 as .
this statement returns a valid value.
 `coreclr_initialize_ptr initializeCoreClr = (coreclr_initialize_ptr)GetProcAddress(coreClr, "coreclr_initialize");`
this statement is where I'm getting the error.
`    int hr = initializeCoreClr(
        runtimePath,        // AppDomain base path
        appDomainFriendlyName,       // AppDomain friendly name
        sizeof(propertyKeys) / sizeof(char*),   // Property count
        propertyKeys,       // Property names
        propertyValues,     // Property values
        &hostHandle,        // Host handle
        &domainId);         // AppDomain ID`
I made all compile setting same on both c++ and c# console apps, and still can't figure out the problem.

This is my dllimport statement:
`        [DllImport("NetNativeHost.dll", CharSet = CharSet.Ansi, CallingConvention = CallingConvention.Cdecl)]
        private extern static int InvokeManagedMethod2(
            string appDomainFriendlyName,
            string entryPointAssemblyName,
            string entryPointTypeName,
            string entryPointMethodName,
            string jobName,
            int iterations,
            double[] data);`
I have tried with or without `CharSet` setting, `Cdecl` and `StdCall` calling convention; nothing was helpful. 

Wonder if anyone had similar issues, so we can share some experiences...
Thanks in advance for your help.

**Comment by vitek-karas** [comment]
It's not supported to call `coreclr_initialize` twice in the same process - the runtime can only be initialized once.
So if you're running a .NET process and try to call `coreclr_intialize` from it again, it should fail like this.

Using the `coreclr_initialize` is not a recommended way to do native hosting of the runtime. I would strongly recommend to use the `hostfxr` APIs instead (https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-nethosth-and-hostfxrh). That way also supports using native hosting APIs in a process with already loaded .NET runtime (attach scenario).
