### ISSUE TITLE
Hosting .NET Core with nethost and hostfxr libraries' APIs -  What do I pass in argv to hostfxr_initialize_for_dotnet_command_line?

### ISSUE THREAD

**Issue by lissity** [dotnet/runtime#53676]
I've read all the documentation and information about this that I can possibly find, but I can't seem to figure out the correct arguments for `hostfxr_initialize_for_dotnet_command_line`.

My native host has found the hostfxr, loaded it and got the exports needed. I've looked at the code snippet [here](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#running-app-with-additional-runtime-properties), and read the description about the parameters:

- `argc`: Number of argv arguments
- `argv`: Command-line arguments for running an application (as if through the dotnet executable).
- `parameters`: Optional. Additional parameters for initialization
- `host_context_handle`: On success, this will be populated with an opaque value representing the initialized host context

More about the argv (and argc) parameter:
- `argc `and `argv `- the command line for running a managed application. These represent the arguments which would have been passed to the muxer if the app was being run from the command line.

The [design document](https://github.com/dotnet/runtime/blob/main/docs/design/features/native-hosting.md#initialize-host-context) specifies that "The command line is parsed to determine the app path.", where `argv `is the "command line". 

I do not know which arguments would be passed to the "muxer" if running from the command line. What do I pass as `argv`? I've tried different combinations of ["dotnet", "run", "--project", "/path/"] and ["run", "--project", "/path/"], but every time it does not manage to initialize the hosting context. The `host_context_handle `is 0x0000000000000000 after the call.

Any help is appreciated.

**Comment by vitek-karas** [comment]
Sorry for the confusion. This is talking only about the runtime command line options for `dotnet`. Running an app directly (without trying to build it first) is done by calling `dotnet app.dll args`, so the `argv` should be something like `app.dll args`.

The `dotnet run` command is available only from the .NET SDK and will not work if only the .NET Runtime is installed - so it's not supported by the native hosting APIs.

I'm improving the docs on this here: https://github.com/dotnet/runtime/pull/53678 - let me know if this makes it clearer.

**Comment by lissity** [comment]
Thank you for the help! It works now 👍 
It might just be me who is not so familiar with the dotnet-command, but the documentation changes definitely makes it clearer. The example is really helpful.
