### ISSUE TITLE
GetSection("ConnectionStrings") must list the connection strings only from the current environment

### ISSUE THREAD

**Issue by wendellestradairely** [dotnet/runtime#53687]
I got my config setup like this:

```csharp
configuration = new ConfigurationBuilder()
  .SetBasePath(environment.ContentRootPath)
  .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
  .AddJsonFile($"appsettings.{environment.EnvironmentName}.json", optional: true)
  .AddEnvironmentVariables()
  .Build();
```
The current environment that is running is `development` but when I retrieve all the connection strings, it combines all the connection strings from `appsettings.json` and `appsettings.Development.json`:

`appsettings.Development.json`
```json
"ConnectionStrings": {
  "01": "<connection string>",
  "99": "<connection string>"
 }
```
`appsettings.json`
```json
"ConnectionStrings": {
  "Default": "<connection string>",
  "Local": "<connection string>"
 }
```
When I query the list of connection strings, it lists all the connection strings of all the json files.
```csharp
configuration.GetSection("ConnectionStrings").GetChildren().Select(e => e.Key).ToList();
```
![image](https://user-images.githubusercontent.com/50942719/120650139-0dd0ad80-c4b0-11eb-894a-a540cb3cee9d.png)

Is this an expected behavior? Is there any function or utility that I can call to only list the connection strings of the current environment?

EF Core version:
Database provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Target framework: (e.g. .NET 5.0)
Operating system:
IDE: (e.g. Visual Studio 2019 16.3)

**Comment by safern** [comment]
@maryamariyan @davidfowl I believe this is by design because both files are added to the configuration builder?

**Comment by maryamariyan** [comment]
The behavior is expected. "appsettings.json" values would be available for all environments (e.g. Production and Development). Don't add values to "appsettings.json" if you don't want them in all environments.

In your example, you add ConnectionStrings for Production in "appsettings.Production.json" and for Development to "appsettings.Development.json".

**Comment by wendellestradairely** [comment]
@maryamariyan Thanks for the info. I now understand why it's happening. I think we can close this now.
