### ISSUE TITLE
LSRA spill cost issue

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#53703]
https://github.com/dotnet/runtime/pull/51901 changed loop cloning to scale the "slow" path cloned loop blocks to 1% of the original block weights. This led to a number of benchmark regressions, such as in ludcmp: https://github.com/dotnet/runtime/issues/52316.

The root cause of these regressions appears to be that poor resulting register allocation leads to the introduction of stack load/store due to reload and reg alloc resolution moves, to the hottest variable in the hottest inner loop.

In particular, for the `ludcmp` function, in the post-51901 compiler, we see this inner loop code:
```
G_M42486_IG40:        ; gcrefRegs=00008002 {rcx r15}, byrefRegs=00000200 {r9}, loop=IG40, byref, isz
 00007ffb`f15436f0 0004D0 4D8BE7               mov      r12, r15
 00007ffb`f15436f3 0004D3 8B5C2434             mov      ebx, dword ptr [rsp+34H] ; **** extra load
 00007ffb`f15436f7 0004D7 4863FB               movsxd   rdi, ebx
 00007ffb`f15436fa 0004DA C4C17B1054FC10       vmovsd   xmm2, qword ptr [r12+8*rdi+16]
 00007ffb`f1543701 0004E1 488B7CF910           mov      rdi, gword ptr [rcx+8*rdi+16]
 00007ffb`f1543706 0004E6 3B6F08               cmp      ebp, dword ptr [rdi+8]
 00007ffb`f1543709 0004E9 0F83CB080000         jae      G_M42486_IG98
 00007ffb`f154370f 0004EF C4A16B5954EF10       vmulsd   xmm2, xmm2, qword ptr [rdi+8*r13+16]
 00007ffb`f1543716 0004F6 C4E1735CCA           vsubsd   xmm1, xmm1, xmm2
 00007ffb`f154371b 0004FB FFC3                 inc      ebx
 00007ffb`f154371d 0004FD 3BDD                 cmp      ebx, ebp
 00007ffb`f154371f 0004FF 895C2434             mov      dword ptr [rsp+34H], ebx ; **** extra store
 00007ffb`f1543723 000503 7CCB                 jl       SHORT G_M42486_IG40
```

On entry to the loop, the hot variable V09 (stored at `rsp+34H`) gets spilled into a new predecessor block (created due to a critical edge split) so its `r12` register can be used by another variable. All the registers are in use at this point, and LSRA decided to spill V09, despite the fact it is the hottest variable and this is the hottest loop (with the highest block weight). Immediately after `r12` is defined, V09 is reloaded, now into `ebx`. at the bottom of the block, V09 needs to get stored back to the stack as a resolution move, since the head of this very block expects it there.

When LSRA goes to spill something for V26 (and thus spills V09), it uses the table of per-register spill costs computed in `LinearScan::updateSpillCost()`. This uses the `interval->recentRefPosition` for V09. The recentRefPosition is in a block with a low weight, thus causing LSRA to choose V09 to spill, as the lowest cost register to spill (with the spill cost affected by block weight).

If, instead, the `FAR_NEXT_REF` was evaluated first (it is not), then LSRA would have noticed that V09 is immediately used after this position, and would choose to spill something else.

Previously, before the block weights were scaled, the cost of spilling V09 was high, so it was not spilled. In the new code, the `recentRefPosition` is in a "cold path" block with scaled-down weight.

**Comment by BruceForstall** [comment]
@kunalspathak Please add / clarify any details here base on our discussion and debugging session.

**Comment by BruceForstall** [comment]
If we can't find an adequate mitigation for this problem, we should revert https://github.com/dotnet/runtime/pull/51901

**Comment by kunalspathak** [comment]
> If, instead, the FAR_NEXT_REF was evaluated first (it is not), then LSRA would have noticed that V09 is immediately used after this position, and would choose to spill something else.

When deciding which register to spill, ideal thing to do even as per literature is to consider the register that will not be used the longest possible time.
Here is the excerpt from "Wimmer, C. and Mössenböck, D. "[Optimized Interval Splitting in a Linear Scan Register Allocator](http://portal.acm.org/citation.cfm?id=1064998&dl=ACM&coll=ACM&CFID=105967773&CFTOKEN=80545349)," ACM VEE 2005, pp. 132-141." (Section 3.2 Spilling of Intervals):

*Finding the optimal interval for spilling, i.e. the one with the smallest negative impact on the overall performance, would be too time-consuming. Instead, we apply a heuristic that is based on the use positions of the active and inactive intervals: The interval that is not used for the longest time is spilled.*

I tried swapping the selection heuristics by making `FAR_NEXT_REF` applied before `SPILL_COST`. Here are the diffs on superpmi replay:

**windows x64 libraries**

```
Summary of Perf Score diffs:
(Lower is better)

Total PerfScoreUnits of base: 16326059043978586
Total PerfScoreUnits of diff: 16326059072526934
Total PerfScoreUnits of delta: 28548342.86 (0.00% of base)
    diff is a regression.


--------------------------------------------------------------------------------

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 689230
Total bytes of diff: 691185
Total bytes of delta: 1955 (0.28% of base)
    diff is a regression.
```

**windows x64 benchmarks**

```
Summary of Perf Score diffs:
(Lower is better)

Total PerfScoreUnits of base: 977828245.2299995
Total PerfScoreUnits of diff: 969437938.0000004
Total PerfScoreUnits of delta: -8390307.23 (-0.86% of base)
    diff is an improvement.


--------------------------------------------------------------------------------

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 333072
Total bytes of diff: 335067
Total bytes of delta: 1995 (0.60% of base)
    diff is a regression.
```

> The recentRefPosition is in a block with a low weight, thus causing LSRA to choose V09 to spill

I still need to understand what we take into account the block weight of recent refPosition (i.e. why we look backward). Again, from the paper, section 3.2: *The spilling heuristic only considers future use positions, but does not look backward to previous uses.* .

To formulate this problem, when decide the spill cost of a register, we take into account just the block weight of last refposition, (assuming that we would spill precisely after the last refposition). However, when it comes to deciding if we should really spill at after that last position, we check if the last refposition [was Regoptional/ActualRef](https://github.com/dotnet/runtime/blob/42755615cfc7378b0045da105238ce44cd385a12/src/coreclr/jit/lsra.cpp#L3274-L3284). Because of that, we end up adding resolutions for such variables inside expensive blocks, that are totally not related to the block having last refPosition.

we do not do based on some previous refPosition

**Comment by BruceForstall** [comment]
In the test case, I also noticed some odd LSRA block sequence, where the block in question, BB124, is processed after its predecessors *and* after its fall-through successor (Note that I don't understand the block layout algorithm). Perhaps that contributes to the problem?

**Comment by kunalspathak** [comment]
@BruceForstall - We always process all the predecessors of a block first. `BB64` is the fall-through block of `BB124` and I do see that it is processed after `BB124`.

```
BB62  [0128]  1       BB61                  7.84  5 [???..???)-> BB65  ( cond )                     internal idxlen LIR 
BB124 [0141]  2       BB62,BB124           62.10  5 [0DB..0F8)-> BB124 ( cond )                     i idxlen bwd LoopPH LIR align 
BB64  [0123]  1       BB124                 7.84  5 [???..???)-> BB66  (always)                     internal LIR 
BB131 [0148]  1       BB58                  3.92    [???..???)-> BB65  (always)                     internal LIR 

LSRA Block sequence:

BB66( 15.68) 
BB67(  7.84) 
BB68( 15.68) 
BB69(  3.96) 
BB124( 62.10) 
BB64(  7.84) 
BB125(  1.98) 
BB36( 15.68) 
```

Perhaps, I should add some more `JITDUMP` logging around sequencing so we can reason out why particular block was sequenced that way.

**Comment by kunalspathak** [comment]
I conducted another experiment to take into account not just the spill cost of recent refposition, but also reload cost of next refPosition and take the max of the two. That helps in picking the registers that do not have high spill/reload cost. Here are the numbers for windows/x64 benchmarks/libraries:

```
d:\git\dotnet-runtime\src\coreclr\jit>jit-analyze -b E:\spmi\asm.reloadweight.libraries.pmi.windows.x64.checked\base -d E:\spmi\asm.reloadweight.libraries.pmi.windows.x64.checked\diff -m PerfScore,CodeSize -c 0

Summary of Perf Score diffs:
(Lower is better)

Total PerfScoreUnits of base: 173075468521.34
Total PerfScoreUnits of diff: 172839103599.67984
Total PerfScoreUnits of delta: -236364921.66 (-0.14% of base)
Total PerfScoreUnits of relative delta: 0.13
    diff is an improvement.
    relative diff is a regression.


--------------------------------------------------------------------------------

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 430676
Total bytes of diff: 431364
Total bytes of delta: 688 (0.16% of base)
Total bytes of relative delta: 0.5144947332467257
    diff is a regression.
    relative diff is a regression.


--------------------------------------------------------------------------------

d:\git\dotnet-runtime\src\coreclr\jit>jit-analyze -b E:\spmi\asm.reloadweight.benchmarks.run.windows.x64.checked.10\base -d E:\spmi\asm.reloadweight.benchmarks.run.windows.x64.checked.10\diff -m PerfScore,CodeSize -c 0

Summary of Perf Score diffs:
(Lower is better)

Total PerfScoreUnits of base: 976740252.9000001
Total PerfScoreUnits of diff: 959951383.18
Total PerfScoreUnits of delta: -16788869.72 (-1.72% of base)
Total PerfScoreUnits of relative delta: -0.17
    diff is an improvement.
    relative diff is an improvement.


--------------------------------------------------------------------------------

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 106734
Total bytes of diff: 107117
Total bytes of delta: 383 (0.36% of base)
Total bytes of relative delta: 0.2240271085911703
    diff is a regression.
    relative diff is a regression.

```
