### ISSUE TITLE
Simply the concurrency limit with task

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#53709]
## Background and Motivation

Currently, if we need to limit the concurrency, it may be a little hard to implement(maybe there's something I missed)

When we use Parallel, we could use `MaxDegreeOfParallelism` to limit the max concurrency, if we could add something like that to `Task.WhenAll` and `Task.WhenAny` method

When I use `Task.WhenAll`, I usually use a `SemephoreSlim` to limit the concurrency like follows:

``` C#
var nums = Enmuerable.Range(1, 1000);
using var semaphore = new SemaphoreSlim(1, 50);
var result = await Task.WhenAll(
    nums
        .Select(async x =>
        {
            try
            {
                await semaphore.WaitAsync();
                return await GetDetail(x);
            }
            finally
            {
                semaphore.Release();
            }
        })
).ToArray());
```

I think it's maybe a common requirement, hope there's a simple API to implement this.

## Proposed API

```diff
namespace System.Threading.Tasks
{
     public class Task{
+      public static Task WhenAll(IEnumerable<Task> tasks, int maxDegreeOfParallelism);
+      public static Task<TResult[]> WhenAll<TResult>(IEnumerable<Task<TResult>> tasks, int maxDegreeOfParallelism);
+      public static Task<Task> WhenAny(IEnumerable<Task> tasks, int maxDegreeOfParallelism);
+      public static Task<Task<TResult>> WhenAny<TResult>(IEnumerable<Task<TResult>> tasks, int maxDegreeOfParallelism);
     }
```

## Usage Examples

``` C#
var nums = Enmuerable.Range(1, 1000);
await Task.WhenAll(nums.Select(async n => {
   // async code block
}), 50);
```

## Risks

Maybe there's something I missed.

**Comment by huoyaoyuan** [comment]
When a `Task` is passed to `WhenAll`, it is already running and may take a thread. Any limitation may only apply when it awaits something.
An api with custom `TaskSchedular` makes more sense.

**Comment by stephentoub** [comment]
Sounds like you're asking for Parallel.ForEachAsync, which already exists for .NET 6 and supports ParallelOptions, including both TaskScheduler and MaxDegreeOfParallelism.
https://github.com/dotnet/runtime/blob/911640b3a891f92ff66e9c82ce65f71d203f11a2/src/libraries/System.Threading.Tasks.Parallel/ref/System.Threading.Tasks.Parallel.cs#L39-L44

**Comment by WeihanLi** [comment]
`Parallel.ForEachAsync` is exactly what I need, thanks greatly for your work @stephentoub

**Comment by stephentoub** [comment]
Great :smile:
