### ISSUE TITLE
Improve codegen for inserting zeros.

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#53713]
As per https://github.com/dotnet/runtime/pull/53578/files#r645282551, we are currently emitting a `pslddq` followed by a `psrldq` to zero the 4th element.

This is decent codegen for the SSE/SSE2 baseline but is inefficient compared to other patterns we could generate for modern hardware.

We should likely replace this with the relevant logic from `vector.WithElement(3, 0.0f)`, which can then generate a `insertps xmm, xmm, 0b00_00_1000` which will preserve all existing values in `xmm` and zero the third element.

category:cq
theme:codegen
skill-level:expert
cost:small
impact:small

**Comment by tannergooding** [comment]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBkBLAOwEcBuGvSasAcgFd8MKBzC4BtRswCs8wQGZhSJqQYBhBjQDeNBqYPUzTDcy0A1GGAzQdAWRgYAFhAAmAClgAZgz2js4MAG4OAJTmlsYWlmbEAOwRDvKWAL4mSdbkdg5OUBpunj7+MEEhRRqRYDE5pvGJSal1GWbZCaaNVprBhdAoDKVefoEDoVDDdQ3dDM0tTG3pvV2ZQA= is a related case where we could insert the 3rd element and simultaneously zero the 4th using `insertps`

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib

**Comment by tannergooding** [comment]
@JulieLeeMSFT, I'd note that this isn't a bug/correctness issue and is simply a codegen efficiency/perf improvement and so likely isn't required for .NET 6

**Comment by JulieLeeMSFT** [comment]
Thanks @tannergooding. Moved to .NET 7.

**Comment by echesakovMSFT** [comment]
I agree with Tanner's assessment here - it not a bug and not critical to be worked on in .NET 6.

**Comment by echesakovMSFT** [comment]
Un-assigning myself
cc @BruceForstall

**Comment by tannergooding** [comment]
This was fixed as part of the general refactoring to use HWIntrinsics for all the System.Numerics accelerated types
