### ISSUE TITLE
JIT: Throw statement triggers: "has ldstr VM restriction"

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#53726]
### Description

The JIT is not able to inline this method because of the ` throw new FormatException("Bad variable size int");` statement with the following error: 

```
generic !!0  (value class System.ReadOnlySpan`1<unsigned int8>,int32,int32&)
Fail Reason: has ldstr VM restriction
```

A cleanup version of the offending code:

```
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static T ReadVariableSizeInt<T>(ReadOnlySpan<byte> buffer, int pos, out int offset) where T : unmanaged
        {
            if (typeof(T) == typeof(int) || typeof(T) == typeof(uint))
            {
                int ui = 0;

                offset = 0;

                byte b = buffer[pos + 0];
                ui |= (b & 0x7F);
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 1];
                ui |= (b & 0x7F) << 7;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 2];
                ui |= (b & 0x7F) << 14;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 3];
                ui |= (b & 0x7F) << 21;
                offset++;
                if ((b & 0x80) == 0)
                    goto End;

                b = buffer[pos + 4];
                ui |= (b & 0x7F) << 28;
                offset++;
                if ((b & 0x80) != 0)
                    throw new FormatException("Bad variable size int");

                End: return (T)(object)ui;
            }

            throw new NotSupportedException($"The type {nameof(T)} is not supported to be written.");
        }
```

### Configuration
.Net 5.0 

### Analysis
It sounds to me that because the offending line is a throw statement and is to be marked as cold, that restriction should not apply.

**Comment by EgorBo** [comment]
```
INLINER: during 'fgInline' result 'failed this callee' reason 'no return opcode'
```
Looks like JIT incorrectly assumes this method never returns (all branches end with 'throw'). I'll take a look.

**Comment by EgorBo** [comment]
From my understanding that is intentional: we don't inline methods with string literals inside from other modules, e.g.:

ClassLibrary1:
```csharp
public class Class1
{
    public string GetString() => "Hello";
}
```

ConsoleApp1 (references ClassLibrary1 lib):
```csharp
string Test() => Class1.GetString();
```
because the way interning works, we only can inline it if ClassLibrary doesn't use that literal anywhere.

**Comment by redknightlois** [comment]
Yes, I dont know really why it cannot be inlined. But in this case where there is no such construct and also it is essentially a `throw` it doesn't make much sense that it behaves like that. Or, no method that throws should be able to be inlined.

**Comment by JulieLeeMSFT** [comment]
CC @AndyAyersMS.

> Yes, I dont know really why it cannot be inlined.

**Comment by redknightlois** [comment]
@andy-ms LOL, you got the scream :D

**Comment by redknightlois** [comment]
@AndyAyersMS ROFL, you got the scream.

**Comment by JulieLeeMSFT** [comment]
Pushing out to .NET 7 since it is not likely to be handled by Preview 7.
