### ISSUE TITLE
Mono shared libraries in Android runtime pack is not stripped for release builds.

### ISSUE THREAD

**Issue by lateralusX** [dotnet/runtime#53722]
Doing release build targeting Android (x64 in this case) doesn't strip the resulting .so files, meaning `libmonosgen-2.0.so` is 18 MB in size, but when stripped, 3.67 MB. The same goes for `libmono-component-*.so` and probably for other `.so` files included in APK when building sample app on Android.

**Comment by steveisok** [comment]
Should be fixed with https://github.com/dotnet/runtime/pull/53240

**Comment by lateralusX** [comment]
We will need stripping of `libmono-component-*.so` as well, not just `libmonosgen-2.0.so`.

**Comment by steveisok** [comment]
@directhex You resolve this, correct?
