### ISSUE TITLE
c#  await writer. WriteAsync( string uit);

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#53737]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/c--await-writerWriteAsync-string-uit/1435565)._

---
I use 
  TextBox.Text = await sr. ReadToEndAsync(); => TextBox.TextChanged..
and              await writer. WriteAsync( string uit);

My suggestion: for . WriteAsync the same procedure:
    await writer. WriteAsync(  TextBox.Text );
 'Moving' instead of 'copying' the data to the file
  results then also in  TextBox.TextChanged..

---
#### Feedback Bot on 5/31/2021, 01:12 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  As @Youssef1313 stated,  however, this is not possible. I also think it's undesirable that such syntax would result in mutating the Textbook. If you like it in your projects,  you could implement an extension method that takes a TextBox and writes its contents and clears the box.
