### ISSUE TITLE
Encoding EncoderReplacementFallback not replacing in codepage 1252

### ISSUE THREAD

**Issue by psiservices-brian-chance** [dotnet/runtime#53745]
### Description

Using System.Text.Encoding.CodePages with codepage 1252, the fallback does not seem to be working or I am not understanding how to use it (highly possible).

The windows-1252 code page [https://en.wikipedia.org/wiki/Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) does not have mappings for [129, 141, 143, 144, 157], shouldn't those bytes be replaced with the fallback character (63 aka "?")

dotnet 5 command line app...
```xml
PackageReference Include="System.Text.Encoding.CodePages" Version="5.0.0" />
```
```c#
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var enc1252 = Encoding.GetEncoding(1252, EncoderFallback.ReplacementFallback, DecoderFallback.ReplacementFallback);
var s = enc1252.GetString(new byte[] { 141 });
var b = enc1252.GetBytes(s);
Console.WriteLine(b[0]); // output 141
```

The Java CharsetDecoder/CharsetEncoder does replace the values...
```Java
String s = new String(new byte[] {(byte)141}, "Cp1252");
byte[] b = s.getBytes("Cp1252");
System.out.println(b[0]); // output 63
```

### Configuration
dotnet 5
Windows 10

### Other Information
Using EncoderFallback.ExceptionFallback and DecoderFallback.ExceptionFallback doesn't throw.

**Comment by tarekgh** [comment]
@psiservices-brian-chance these unassigned characters in `1252` are mapped to itself. This is the behavior inherited from Windows OS. Unfortunately, we cannot change this behavior now as many apps depend on the current behavior and changing it would be a serious breaking change.

**Comment by psiservices-brian-chance** [comment]
Thanks.
