### ISSUE TITLE
Cannot profile ReadyToRun code on win-x64

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#53743]
Trying to profile ReadyToRun code in .NET 6 on win-x64 results in unresolved call stacks.  For instance, profiling the ASP.NET benchmark below for .NET 5 and .NET 6 results in 1.6%–2.2% of call stacks "broken" in .NET 5 and 60.8% of call stack "broken" in .NET 6 as reported by PerfView.
```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --scenario json --profile aspnet-perf-win --variable warmup=0 --variable duration=0 --application.collect true --application.collectStartup true --application.framework net6.0
```

**Comment by hoyosjs** [comment]
cc: @dotnet/dotnet-diag @brianrob FYI

**Comment by tommcdon** [comment]
@trylek

**Comment by adamsitnik** [comment]
It would be great to fix it as it makes profiling on Windows a painful experience.

**Comment by AntonLapounov** [comment]
Pedro Justo has found that we generate `lea RSP` instructions in epilogs without emitting `UWOP_SET_FPREG`, which is not allowed according to the [documentation](https://docs.microsoft.com/en-us/cpp/build/prolog-and-epilog?view=msvc-160#epilog-code):
> When a frame pointer is not used, the epilog must use `add RSP,constant` to deallocate the fixed part of the stack. It may not use `lea RSP,constant[RSP]` instead.

As far as I can tell, we generate the same epilogs in .NET 5, so I suspect the finding above does not fully explain the issue we started seeing in .NET 6.

**Comment by AntonLapounov** [comment]
Opened #54320 for emitting `LEA RSP` without `UWOP_SET_FPREG`.
