### ISSUE TITLE
DllNotFoundException invoking HttpClient.GetStringAsync in MAUI

### ISSUE THREAD

**Issue by efonsecab** [dotnet/runtime#53749]
### Description
When running a Blazor MAUI app in an iOS emulator, we get an exception "DllNotFoundException: libcoreclr.so"

Failing in this line:
this.Result = await http.GetStringAsync("https://petstore.swagger.io/v2/store/inventory");

### Configuration

* Which version of .NET is the code running on? .NET 6 preview 4
* What OS and version, and what distro if applicable? iOS emulator

### Screenshots
<img width="477" alt="Screen Shot 2021-06-04 at 16 12 25" src="https://user-images.githubusercontent.com/3481899/120868047-5dff4c80-c550-11eb-8399-2913a1c95cab.png">

**Comment by filipnavara** [comment]
Unfortunately, anything related to cryptography on iOS won't work properly until Preview 6. The managed HTTP stack depends on it too. It may be possible to switch to the NSURL-based HTTP stack by adding `runtime-options.plist` inside the app bundle (.app) with this:

```
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
    <dict>
        <key>HttpMessageHandler</key>
        <string>NSUrlSessionHandler</string>
    </dict>
</plist>
```

(untested)

**Comment by efonsecab** [comment]
> Unfortunately, anything related to cryptography on iOS won't work properly until Preview 6. The managed HTTP stack depends on it too. It may be possible to switch to the NSURL-based HTTP stack by adding `runtime-options.plist` inside the app bundle (.app) with this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <plist version="1.0">
>     <dict>
>         <key>HttpMessageHandler</key>
>         <string>NSUrlSessionHandler</string>
>     </dict>
> </plist>
> ```
> 
> (untested)

Thanks, was not able to make that work, but I made it work using HTTP (non-secure) for testing at least.

**Comment by marek-safar** [comment]
The issue should be addressed in Preview7
