### ISSUE TITLE
Xamarin.iOS net6 builds are seeing ~10% larger AOT data sizes

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#53740]
We should investigate and try to understand what is causing this, and fix it if possible. Improvements could potentially generalize to other platforms—this is just the only case where we have a clear point of comparison.

**Comment by SamMonoRT** [comment]
These issues are created after investigating. More to come : 
1. https://github.com/dotnet/runtime/issues/54850 
2. https://github.com/dotnet/runtime/issues/54849

**Comment by SamMonoRT** [comment]
https://github.com/dotnet/icu/pull/131 should help slightly.

**Comment by SamMonoRT** [comment]
We'll keep working on this, but nothing concrete is expected to be checked in the 6.0.0 timeframe. Moving to 7.0.0

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/pull/58982

**Comment by vargaz** [comment]
One potential reason is that unless the 'nodebug' aot option was given, the aot data contains debug info/sequence point info. So if the old build system used that flag in release mode, but the new one doesn't that might explain the difference.

**Comment by imhameed** [comment]
AOT data sizes turned out not to differ very much once LLVM was enabled in xamarin-macios.
