### ISSUE TITLE
"EntryPointNotFoundException" thrown on GetEnumerator

### ISSUE THREAD

**Issue by BatanGaming** [dotnet/runtime#53769]
I'm working on study project and my goal is to convert assembly into dynamic assembly with dynamically generated methods. Currently I'm adding functionality for generic types/methods. 
So, idea is to create method definition with pre-defined body which will call my `GetMethod` method which will return `Delegate`  with original body and then caller will call this delegate. I know that I must rewrite all tokens in method body (because I use `SetCode` method) and I do it. Also I generate specialized types/methods if they are generic e.g we have method `TestMethod<T>` and than call it `TestMethod<int>` so `GetMethod` will return exactly `TestMethod<int>` with no `T` in the body.
So, let's see this code:
```c#
public static class Program
{
    public static void View<T, TEntity>(T list) where T: IEnumerable<TEntity> {
        foreach (var entity in list) {
            Console.WriteLine(entity);
        }

        Console.WriteLine();
    }

    public static void Main(string[] args) {
        View<List<int>, int>(Enumerable.Range(0, 10).ToList()); // Works fine
        TestClass.ViewStatic<List<int>, int>(Enumerable.Range(0, 10).ToList()); // Works fine
        var obj = new TestClass();
        obj.ViewInstance<List<int>, int>(Enumerable.Range(0, 10).ToList()); // Throws exception
    }
}

public class TestClass
{
    public void ViewInstance<T, TEntity>(T list) where T : IEnumerable<TEntity> {
        foreach (var entity in list) {
            Console.WriteLine(entity);
        }

        Console.WriteLine();
    }

    public static void ViewStatic<T, TEntity>(T list) where T : IEnumerable<TEntity> {
        foreach (var entity in list) {
            Console.WriteLine(entity);
        }

        Console.WriteLine();
    }
}
```
Here's [generated code](https://github.com/dotnet/runtime/files/6602592/generated.txt). So, static methods' calls work fine, but when calling instance method it throws exception and, to be honest, `EntryPointNotFoundException` doesn't say anything in this context. So, I want to understand what I'm doing wrong and why this happens?

**Comment by huoyaoyuan** [comment]
A common source of mistake is argument index in `ldarg`. In static method, `ldarg.0` is the first argument. In instance method, `ldarg.0` is `this`, and `ldarg.1` is the first argument. Make sure you are aware of this.

**Comment by BatanGaming** [comment]
Oh, yeah, I guess when I was refactoring the pre-defined body of methods I forgot about parameters, because now I see only `ldarg.0` for instance method. I will give reply

**Comment by BatanGaming** [comment]
So, yeah, there's a problem with arguments. I need to pass parameters to delegate starting from 1, not 0, if the method isn't static, because I'm using `CreateDelegate(Type, object?)` which is doing all work for me. Thank you a lot, you put my thoughts in right direction.
