### ISSUE TITLE
Add method for searching all indexes of char or string in string

### ISSUE THREAD

**Issue by MrVeil303** [dotnet/runtime#53771]
## Background and Motivation

Method for searching all indexes of char or string in string would be useful.

## Proposed API

```diff
namespace System
{
    public class String : IEnumerable<char>, IEnumerable, ICloneable, IComparable, IComparable<string?>, IConvertible, IEquatable<string?
    {
+        public int[] AllIndexesOf(char value)
+        public int[] AllIndexesOf(char value, int startIndex)
+        public int[] AllIndexesOf(char value, int startIndex, int count)
+        public int[] AllIndexesOf(char value, StringComparison comparisonType)
+        public int[] AllIndexesOf(string value)
+        public int[] AllIndexesOf(string value, int startIndex)
+        public int[] AllIndexesOf(string value, int startIndex, int count)
+        public int[] AllIndexesOf(string value, int startIndex, int count, StringComparison comparisonType)
+        public int[] AllIndexesOf(string value, int startIndex, StringComparison comparisonType)
+        public int[] AllIndexesOf(string value, StringComparison comparisonType)

```

## Usage Examples

``` C#
    "Hello".AllIndexesOf('l');
```

**Comment by MrVeil303** [comment]
Maybe also add
```
public int[] AllIndexesOfAny(char[] anyOf)
public int[] AllIndexesOfAny(char[] anyOf, int startIndex)
public int[] AllIndexesOfAny(char[] anyOf, int startIndex, int count)
```
But I don't think that it would be useful.

**Comment by sunkin351** [comment]
If someone really needs something like this, its easy to write in user code on top of `string.IndexOf()`. And personally, with how this would allocate on each call, might not be worth it in the long run.

**Comment by Clockwork-Muse** [comment]
It won't get you _indexes_ (which maybe should be changed), but you can get a list of matches via regex.  Depending on what you're trying to do the various regex operations may be better for you (ie, if you want this to do replacements based on the index, regex will probably be the way to go).

**Comment by Clockwork-Muse** [comment]
Sample workaround method:
```csharp
public static IEnumerable<int> AllIndexesOf(this string source, char val, int startIndex) 
{
    startIndex -= 1;
    while ((startIndex = source.IndexOf(val, startIndex + 1)) != -1)
    {
        yield return startIndex;
    }
}
```

**Comment by MrVeil303** [comment]
> If someone really needs something like this, its easy to write in user code on top of `string.IndexOf()`. And personally, with how this would allocate on each call, might not be worth it in the long run.

I know, that it is "easy to write in user code on top of `string.IndexOf()", but .NET class library already has a lot of methods to solve such an easy problems, like this and I think that it would be useful to add this to standart string methods, to don't write this method a lot of times anywhere.

**Comment by MrVeil303** [comment]
> It won't get you _indexes_ (which maybe should be changed), but you can get a list of matches via regex.  Depending on what you're trying to do the various regex operations may be better for you (ie, if you want this to do replacements based on the index, regex will probably be the way to go).

I don't really like to use regex, because I think, that it make code less readable. And please see my answer to @sunkin351 for reason, why I proposed this.

**Comment by sunkin351** [comment]
> to don't write this method a lot of times anywhere.

Technically speaking, you'd only need to write them once and then copy on a per project basis. That said though, for those looking to avoid GC overhead, you might wanna revise the API to not return newly allocated arrays. That's my only pet peve. There are a few solutions to this, such as enumerating them instead of returning an array of them.

**Comment by Clockwork-Muse** [comment]
>  I think that it would be useful to add this to standart string methods, to don't write this method a lot of times anywhere.

... And what is this method going to be used for?  API surface area has a cost, and just a blanket "it would be useful" isn't (usually) significant enough justification to add it.

Note that `IndexOf` is going to be niche already, and I expect it is being ignored in favor of some higher level abstractions.

> Technically speaking, you'd only need to write them once and then copy on a per project basis.

Or better, publish a package.

**Comment by Symbai** [comment]
> to don't write this method a lot of times anywhere.

Can you give us examples here on github how many times this is used by developers? I believe its an edge case scenario and shouldn't be added. Also because "I believe its useful" isn't really an argument. When this is enough, then we should add EVERYTHING into the runtime, because there is always someone finding something useful.

**Comment by davidfowl** [comment]
Maybe an enumerator pattern to avoid the array allocation.

**Comment by MrVeil303** [comment]
> > to don't write this method a lot of times anywhere.
> 
> Can you give us examples here on github how many times this is used by developers? I believe its an edge case scenario and shouldn't be added. Also because "I believe its useful" isn't really an argument. When this is enough, then we should add EVERYTHING into the runtime, because there is always someone finding something useful.

Search on github says that there are 7308 matches for [AllIndexesOf](https://github.com/search?l=C%23&q=AllIndexesOf&type=Code) + 73 matches for [AllIndicesOf](https://github.com/search?l=C%23&q=AllIndicesOf&type=Code) in C# code. 
And I think, that suggestion means, that I suggest something and people discuss, is it needed or not. Maybe I translated or understood  this label incorrectly, then there are my apologies.

**Comment by MrVeil303** [comment]
> >  I think that it would be useful to add this to standart string methods, to don't write this method a lot of times anywhere.
> 
> ... And what is this method going to be used for?  API surface area has a cost, and just a blanket "it would be useful" isn't (usually) significant enough justification to add it.
> 
> Note that `IndexOf` is going to be niche already, and I expect it is being ignored in favor of some higher level abstractions.
> 
> > Technically speaking, you'd only need to write them once and then copy on a per project basis.
> 
> Or better, publish a package.

You can search on github for it and see "what is this method going to be used for". I think, that 7381 matches is large amount and one of the reasons, why I created this issue. Maybe people need such a simple method ?

**Comment by MrVeil303** [comment]
> > to don't write this method a lot of times anywhere.
> 
> Technically speaking, you'd only need to write them once and then copy on a per project basis.
> 
> That said though, for those looking to avoid GC overhead, you might wanna revise the API to not return newly allocated arrays. That's my only pet peve. There are a few solutions to this, such as enumerating them instead of returning an array of them. (Ideally with a `struct` enumerator)

This is something like @Clockwork-Muse [commented](https://github.com/dotnet/runtime/issues/53771#issuecomment-855282866) ?

**Comment by Sergio0694** [comment]
Just my two cents, I think we should all be **very** careful going forwards about introducing new APIs that allocate like this, or really about introducing any new APIs either returning or accepting arrays. Specifically, the proposal should at the very least make a good case for these APIs, detailing why they'd be necessary and what issues they would solve. Right now the "example" is literally just calling the proposed API - that's not a use case example, it's just a sample of what the syntax would look like 😟

What I mean is:
- When would developers need to call this API?
- What problem would they be trying to solve?
- How would they use the resulting indices from these APIs?
- (Most importantly) Couldn't they achieve just the same in a faster and non-allocating way by just leveraging one of the other existing APIs (eg. `IndexOf` as was already suggested by @sunkin351, or some other `string`/`ReadOnlySpan<T>` extension)?
- If that's not the case (which I doubt), wouldn't there still be a better API surface to possibly propose compared to this?

To make an example: I would honestly not be surprised if, with such an API being added, we then saw developers using it to literally just call `string.Substring` a bunch of times over the initial text. Which would then just literally be `string.Split` with extra steps (and even less efficient), not to mention the fact that you could basically achieve the same with no allocations whatsoever in many cases by just iterating and tokenizing the `string` as a `ReadOnlySpan<char>` directly ([reference API here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.stringextensions.tokenize)). What I'm saying is, we should really be careful about introducing new APIs that could nudge developers into inefficient patterns like this 🙂

**Comment by hopperpl** [comment]
Adding more temporary array allocation is quite the opposite of what I want. I would never call this API, and neither would anyone creating a high-performance application or creating a library that needs to implement fast parsing of data.

If I wanted something, then it's something more like:

`bool TrySplit(char delimiter, in ReadOnlySpan<char> value, Span<Range> ranges)`

Range contains the position.
Strings can easily be converted to ROS\<char\>; function overloads with startIndex, and length should be a remnant of the past.

**Comment by MrVeil303** [comment]
I didn't think that this issue will take so much time. I believe that someone of this repository contributors will think about this suggestion and maybe add this feature in the future (because .net already has methods for searching first index, last index but not the rest). Thanks for your attention. Have a good time.
