### ISSUE TITLE
IEnumerable<TSource>.ToList with a key selector

### ISSUE THREAD

**Issue by pedrobarbs** [dotnet/runtime#53777]
## Background and Motivation

Writting code over and over often bring us the need of creating general propouse libraries with functions that help us to improve coding speed and code semantics.

I would like to suggest a very common extension method that I see developers implementing to be part of default LINQ API. 

```C#
var properties = someList.ToList(p => p.SomeProperty);
```

## Proposed API

```C#
public static List<TKey> ToList<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector);
```

## Usage Examples

``` C#
...

var names = users.ToList(user => user.Name);

...
```

## Benefits

It would bring a default implementation such as the argument validations. As a very common extension method, it can vary from developer to developer and sometimes it can lead to an unexpected behaviour. It would be great if the framework could give us a default implementation saving us time and providing a predicted behaviour.

## Other notes
I could grab this one.

**Comment by huoyaoyuan** [comment]
It's just `Select().ToList()`. There are also other collection building operators like `ToArray`, `ToImmutableArray`, `ToHashSet`. List isn't special and doesn't worth a special case for orthogonal operation.

**Comment by eiriktsarpalis** [comment]
> public static List<TSource> ToList<TSource, TKey>(this IEnumerable<TSource> source, Func<TSource, TKey> keySelector);

I'm not sure I am able to deduce how the proposed method is supposed to function just by looking at its signature: it transforms `TSource` enumerables into `TSource` enumerables. What are `TKey` values used for? Guaranteeing uniqueness?

**Comment by stephentoub** [comment]
I suspect it was a typo / copy-paste-error and it was supposed to be:
```C#
public static List<TResult> ToList<TSource, TResult>(this IEnumerable<TSource> source, Func<TSource, TResult> resultSelector);
```

But I agree with @huoyaoyuan's comments, that functionally you can do the same thing as:
```C#
var names = users.ToList(user => user.Name);
```
with
```C#
var names = users.Select(user => user.Name).ToList();
```
and the intent of LINQ is that it provides these very common building blocks that can then be used to simply construct the desired query, only deviating from that for specific patterns deemed the 90% case, e.g. Count that takes a predicate.

Given that, I don't think the rises to the level of something we should add new API for.

My $.02.

**Comment by pedrobarbs** [comment]
@stephentoub you're correct, the return type would be the selected property's type.

Regarding the reason for not considering it into LINQ, I understand and makes sense. 

Thanks!
