### ISSUE TITLE
Invalid counting of cached log formatters

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#53785]
### Description

[M.E.L.FormattedLogValues](https://github.com/dotnet/runtime/blob/2d4acbde200dba78794d9baf8cc69c170267fde0/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/FormattedLogValues.cs) incorrectly counts number of cached formatters. Let's take a look at `FormattedLogValues` ctor in commit 78c05c341381d1bb853a2e054da00f6bcbfe7f40:

```csharp
if (_count >= MaxCachedFormatters)
{
    if (!_formatters.TryGetValue(format, out _formatter))
    {
        _formatter = new LogValuesFormatter(format);
    }
}
else
{
    _formatter = _formatters.GetOrAdd(format, f =>
    {
        Interlocked.Increment(ref _count);
        return new LogValuesFormatter(f);
    });
}
```

`GetOrAdd` method of concurrent dictionary is not atomic so the factory can be called twice or more for the same key but only one value can be stored in this dictionary. As a result, increment will be called for the same key multiple times.

I think there is no need for separate `_count` variable and `Count` property of concurrent dictionary can be used instead.

### Configuration
N/A

### Regression?
Up to current version of .NET

**Comment by davidfowl** [comment]
Yea, but it doesn't matter if it's not accurate.

**Comment by BrennanConroy** [comment]
Correct, https://github.com/aspnet/Logging/pull/561/files#r106302224
