### ISSUE TITLE
What's the best way to specify structure layout difference on architectures?

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#53790]
When trying to modernize P/Invoke in System.Drawing.Common, I saw this:

https://github.com/dotnet/runtime/blob/11c9394f4ef4a1fc66f93b334ee4f29164c4ff44/src/libraries/System.Drawing.Common/src/Interop/Windows/Interop.Comdlg32.cs#L17-L63

Win32 and Win64 uses different packing size for the struct (confirmed in commdlg.h). This is not easy to define in managed code. Defining two types like this looks very error-prone. Does it worth compiling separately for different archs?

**Comment by jkotas** [comment]
You can define two types, but hide the difference behind interface. https://github.com/dotnet/runtime/pull/33899 has real world example of this technique.
