### ISSUE TITLE
Simpler API for using .p8 files with ECDsa?

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#53807]
When working with _Sign in with Apple_ in ASP.NET Core, part of the process involves generating a JWT signed with a key downloaded from the Apple Developer Portal, which is provided by Apple as a `.p8` file.

As far as I'm aware, there isn't an API in-box in .NET that allows a developer to directly consume the raw content of the `.p8` file as-is and use it.

This test shows an approach to use the file without requiring post-processing with a tool like OpenSSL to create file in a different format before using it in code.

```csharp
[Fact]
public static async Task Create_ECDsa_From_P8_File()
{
    string privateKey = await File.ReadAllTextAsync("Auth_KeyId.p8");

    if (privateKey.StartsWith("-----BEGIN PRIVATE KEY-----", StringComparison.Ordinal))
    {
        string[] lines = privateKey.Split('\n');
        privateKey = string.Join(string.Empty, lines[1..^1]);
    }

    byte[] source = Convert.FromBase64String(privateKey);

    using var algorithm = ECDsa.Create();
    algorithm.ImportPkcs8PrivateKey(source, out _);
}
```

Given recent work for supporting PEM files, is there potential for adding one or more APIs in the .NET 6 release to make the above simpler? Ignoring the specific method name (I'm not familiar with the _exact_ naming for the type of key/certificate in use in this scenario), something like this:

```csharp
[Fact]
public static async Task Create_ECDsa_From_P8_File()
{
    byte[] source = await File.ReadAllBytesAsync("key.p8");

    using var algorithm = ECDsa.Create();
    algorithm.ImportPkcs8File(source);
}
```

Alternatively, is there already something in .NET for doing this that I've missed that doesn't need the string manipulation before it can be passed to `ECDsa`?

**Comment by vcsjones** [comment]
If it is a PEM encoded PKCS8 key then you should be able to use [`ECDsa.ImportFromPem`][1] which was introduced in .NET 5. Something like:


```csharp
string privateKey = await File.ReadAllTextAsync("Auth_KeyId.p8");
using var algorithm = ECDsa.Create();
algorithm.ImportFromPem(privateKey);
```

**Comment by martincostello** [comment]
Bingo - that works, thanks @vcsjones.

I was sure I tried that out before opening this and it didn't work, but I think I must have gotten something mixed up somewhere... 🤔

In the original code I had in .NET Core 3.1 before PEM was supported at all to do this I went with `byte[]` as a sort of lowest-common denominator for _"a key loaded from wherever"_, so I think I must have gotten in a tangle between the `Span<byte>` members and the `string` ones, and was hunting for something `byte`-based that would just take the file content.

**Comment by krwq** [comment]
@martincostello please let us know if this can be closed or do you have expectations on any follow up work

**Comment by vcsjones** [comment]
> that works

Excellent. 

> and was hunting for something byte-based that would just take the file content.

Yeah, I think a `ReadOnlySpan<byte>` of what is essentially text content would be an unexpected API design. It'd mean making an assumption about how the file is encoded (UTF8? UTF16-LE?). Since the purpose of PEM is to be a textual representation of the key, the PEM import accepts text as input.

**Comment by martincostello** [comment]
> Yeah, I think a `ReadOnlySpan<byte>` of what is essentially text content would be an unexpected API design. It'd mean making an assumption about how the file is encoded (UTF8? UTF16-LE?). Since the purpose of PEM is to be a textual representation of the key, the PEM import accepts text as input.

Thanks again, that makes a lot more sense to me now.
