### ISSUE TITLE
Package testing shouldn't hard code restore sources

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53810]
https://github.com/dotnet/runtime/blob/8709d595f7105cbf73774ec762266bc56f99cf04/src/libraries/pkg/test/packageTest.targets#L10-L16

The `RestoreSources` property is hardly used anymore as it doesn't support authentication and instead we specify the restore sources in the repo's NuGet.config file. We probably want to copy that file next to the test app so that the restore sources aren't duplicated.

cc @Anipik @ericstj @safern @joperezr

**Comment by safern** [comment]
> We probably want to copy that file next to the test app so that the restore sources aren't duplicated.

For the `LocalPackagesPath` would you have a placeholder and replace it before copying the file to the test app folder?

**Comment by ericstj** [comment]
Maybe we can just use [RestoreAdditionalProjectSources](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties) for `LocalPackagesPath`

**Comment by safern** [comment]
I didn't know that property existed, good to know.

**Comment by ViktorHofer** [comment]
That was fixed via https://github.com/dotnet/runtime/pull/53905
