### ISSUE TITLE
String Left and Right methods

### ISSUE THREAD

**Issue by ptjuanramos** [dotnet/runtime#53826]
## Background and Motivation

Many times in many use cases, operations needs to retrieve the _leftmost_ and _rightmost_ characters from a string. The normal procedure is to create a centralized method for that string manipulation(in case that is being used throughout the project).

Even though that is just a small implementation, we could imagine that many projects in the all industry are just repeating the same code and probably the same tests.

## Proposed API

```diff
namespace System
{
     public partial class String {

+        // Get the leftmost size characters of a string
+        public string Left(int size);

+        // Get the rightmost size characters of a string
+        public string Right(int size);

     }
```

## Usage Examples

I have the string, "String example",  which has 14 characters.

I want to retrieve the leftmost 6 characters of that string, the expected result is

``` csharp 
string leftString = "String example".Left(6); 
\\The output should be 'String'
```

Now, I want to retrieve the rightmost 7 characters, the expected result is:

``` csharp 
string rightString= "String example".Right(7); 
\\The output should be 'example'
```

**Comment by GrabYourPitchforks** [comment]
Is this equivalent to the following?

```cs
string left = "string example"[..6]; // take first 6 chars
string right = "string example"[^7..]; // take last 7 chars
```

**Comment by ptjuanramos** [comment]
G

> Is this equivalent to the following?
> 
> ```cs
> string left = "string example"[..6]; // take first 6 chars
> string right = "string example"[^7..]; // take last 7 chars
> ```

No comments on that! Indeed it is equivalent. But just a quick question, should my proposal as a alternative implementation(Not being passive agressive)?

**Comment by GrabYourPitchforks** [comment]
> should my proposal considered a alternative implementation

Not sure. I've seen `First` and `Last` utility methods with behaviors of "take _up to_ the specified number of chars if the string is too small." So `"shortString".First(100)` would return the original input rather than throw. But I'm guessing this behavior might not be appropriate for your scenarios?

**Comment by ptjuanramos** [comment]
Yeap, I should put that use case in my description, that is exactly the behaviour that I wanted. 
```csharp
 string left = "string example"[..6];
 ``` 
throws _ArgumentOutOfRangeException_ if the string is too small and my proposal does what `First` and `Last` utility methods does what I proposed. However, you could have only the `string` implementation and not an external library.

**Comment by GrabYourPitchforks** [comment]
Related: when discussing `First`, devs often want it as part of a larger string truncation + ellipsis feature. See https://github.com/dotnet/runtime/issues/31655 for some discussion of problems that crop up with such a construction.

If the request is "take _exactly_ the first or last chars from the string", I think the existing framework patterns already cover the scenario pretty well.

**Comment by ptjuanramos** [comment]
I see your point and I can see a potential proposal in the UI related framework libraries to create that truncation + ellipsis. 
However, I believe that leftmost operation for example, takes the most characters that he cans from a string, which lead me thinking that `string.Left(...)` wouldn't throw an exception if the string is to short.

**Comment by stephentoub** [comment]
Thanks for the suggestion.  Given the existing support for C# range syntax with strings, I don't think we should be adding to String named versions of a subset of what's already possible with a well-known and concise syntax.  That syntax also makes it possible to customize the behavior you want, e.g. if you want to limit to just what's available, that's easily achieved by adding in a Math.Min call, e.g.
```C#
someString[..Math.Min(6, someString.Length)]
```
Given that, I'm going to close the issue.  Thanks for the suggestion.
