### ISSUE TITLE
[wasm][aot] Figure out how to handle APIs not supported on AOT

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#53825]
Some APIs, like `Assembly.GetCallingAssembly()` are not supported on wasm/AOT. We should have a clear behavior for this, eg. throw an exception, or maybe mark these APIs, so that the user is aware that these are not supported.

Example case: https://github.com/dotnet/runtime/issues/53815

How is this handled for non-wasm+aot cases?

cc @vargaz @steveisok

**Comment by lewing** [comment]
We could make a mono AOT analyzer that look for attributes when AOT is enabled, I'm not sure there is a more general way to solve this.

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/issues/53815
