### ISSUE TITLE
JIT: Vector3Interop_ro.cmd fails on Windows ARM64 with Full PGO

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#53838]
https://dev.azure.com/dnceng/public/_build/results?buildId=1174221&view=ms.vss-test-web.build-test-results-tab

See also https://github.com/dotnet/runtime/issues/52864#issuecomment-849728530

**Comment by AndyAyersMS** [comment]
This is failing reliably in the lab, but so far I can't get a local repro.

**Comment by AndyAyersMS** [comment]
Still failing, see eg https://dev.azure.com/dnceng/public/_build/results?buildId=1232289&view=ms.vss-test-web.build-test-results-tab

@EgorBo can you see if you can get this to repro?

**Comment by EgorBo** [comment]
> Still failing, see eg https://dev.azure.com/dnceng/public/_build/results?buildId=1232289&view=ms.vss-test-web.build-test-results-tab
> 
> @EgorBo can you see if you can get this to repro?

Will try!

**Comment by AndyAyersMS** [comment]
Possibly relevant: https://github.com/dotnet/runtime/issues/46347

**Comment by AndyAyersMS** [comment]
Any luck with a repro? I am about to try again...

**Comment by AndyAyersMS** [comment]
Still no luck reproing this in isolation. I will try a full test run. 

From the failure text it would appear something is perhaps corrupting the stack args...?
```
callBack_RPInvoke_Vector3Arg_Unix:
1, 2, 3
10, 20, 30
Sum0,1,2,3 = 14, NaN, NaN, 936
```
The middle two sums depend on a vector arg passed in memory.

**Comment by EgorBo** [comment]
> Any luck with a repro? I am about to try again...

Sorry forgot to respond. I couldn't access any remote win-arm64 machine so I tried to repro it on linux-arm64 and osx-arm64 (M1) - with no luck, even with jit/gc stress flags + FullPGO

**Comment by AndyAyersMS** [comment]
[Now seems to be happening](https://dev.azure.com/dnceng/public/_build/results?buildId=1285112&view=ms.vss-test-web.build-test-results-tab&runId=37938600&resultId=108938&paneView=debug) in the _r variant too. Same failure mode:
```
callBack_RPInvoke_Vector3Arg_Unix:
1, 2, 3
10, 20, 30
Sum0,1,2,3 = 14, NaN, NaN, 936
RPInvoke Vector3Arg_Unix test failed
```
some float args get corrupted around a reverse pinvoke.

Going to try reproing this once more. Suspect it requires GC or similar to kick in at just the "wrong" time. So maybe GC stress will do the trick.

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib anyone else with a windows arm64 box want to try their hand at reproing this? I am out of ideas.

**Comment by echesakovMSFT** [comment]
@AndyAyersMS I can try tomorrow.
The CI link is dead, can you please tell what environment variables were set when this test failed?

**Comment by echesakovMSFT** [comment]
No luck with reproing this so far but I noticed that `COMPlus_TieredCompilation=1` is set for fullpgo in the CI.

**Comment by AndyAyersMS** [comment]
Yes (didn't mention it because that's a default setting).

I wonder if we can get access to one of the CI machines. This test fails very consistently there.

**Comment by echesakovMSFT** [comment]
> I wonder if we can get access to one of the CI machines. This test fails very consistently there.

It was possible in the past. @MattGal can you help with this?

**Comment by MattGal** [comment]
> > I wonder if we can get access to one of the CI machines. This test fails very consistently there.
> 
> It was possible in the past. @MattGal can you help with this?

Happy to do so, I've preemptively taken the machine from Andy's log above offline in case it's that-machine-specific too.  It will require an on-corpnet (not VPN) device to remote to it.  @AndyAyersMS Hit me up on Teams and we'll figure something out.

**Comment by echesakovMSFT** [comment]
@AndyAyersMS I reproduced the failure and I think I have a suspect:
- when I built the test (and its native components) locally I can not reproduce the failure even with 100 iterations
- when I replace the test native components with artifacts from the CI it fails immediately 

In the CI we use
```
Visual Studio 2019 Developer Command Prompt v16.10.3
The C compiler identification is MSVC 19.29.30038.1
```

This is what I have
```
Visual Studio 2019 Developer Command Prompt v16.10.5
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30040 for x86
```

So it might an issue in VC.

**Comment by MattGal** [comment]
@echesakov the "for x86" part may be relevant?  These ARM64 windows machines can and do run x86 and amd64 binaries (very slowly an possibly with issues) , so if you're building for x86, even if running on your own ARM64 machine, you may not be going down the same path.

**Comment by echesakovMSFT** [comment]
It also looks that setting `set COMPlus_ReadyToRun=0` is sufficient to repro the issue.

**Comment by echesakovMSFT** [comment]
>the "for x86" part may be relevant?

@MattGal  I believe *"for x86"* stands for Hostx86. Both native artifacts are ARM64 binaries.

**Comment by AndyAyersMS** [comment]
@echesakov thanks... looks like I was using 19.28.29715.1 to try and repro.

**Comment by echesakovMSFT** [comment]
I the issue that the following block https://github.com/dotnet/runtime/blob/b2714bc0a738035f10887d87d8b28cb5ac66c3ef/src/coreclr/jit/lowerarmarch.cpp#L1166-L1193 
doesn't zero upper filed of `op2` as it does for `op1`

**Comment by echesakovMSFT** [comment]
Confirmed - the following patch
```diff
--- a/src/coreclr/jit/lowerarmarch.cpp
+++ b/src/coreclr/jit/lowerarmarch.cpp
@@ -1190,6 +1190,17 @@ void Lowering::LowerHWIntrinsicDot(GenTreeHWIntrinsic* node)
         op1 = comp->gtNewSimdAsHWIntrinsicNode(simdType, op1, idx, tmp1, NI_AdvSimd_Insert, simdBaseJitType, simdSize);
         BlockRange().InsertAfter(tmp1, op1);
         LowerNode(op1);
+
+        idx = comp->gtNewIconNode(0x03, TYP_INT);
+        BlockRange().InsertAfter(op2, idx);
+
+        tmp2 = comp->gtNewZeroConNode(TYP_FLOAT);
+        BlockRange().InsertAfter(idx, tmp2);
+        LowerNode(tmp2);
+
+        op2 = comp->gtNewSimdAsHWIntrinsicNode(simdType, op2, idx, tmp2, NI_AdvSimd_Insert, simdBaseJitType, simdSize);
+        BlockRange().InsertAfter(tmp2, op2);
+        LowerNode(op2);
```
fixes the test failure for me.

**Comment by AndyAyersMS** [comment]
Thanks for chasing this down. The fix looks good to me, can you put up a PR?
