### ISSUE TITLE
Pipeline dependency issue: Artifact CoreCLRProduct bits missing.

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#53842]
We have builds failing to acquire the CoreCLR runtime bits. I am not sure why these are needed for the mono bits there. @directhex  or @akoeplinger any idea there? For example https://dev.azure.com/dnceng/public/_build/results?buildId=1170249&view=logs&j=a3584aa7-f6a0-5e90-05ca-4edce1db7c76&t=6251704e-67a1-5275-71bd-ce7ee4c63087

This is likely caused by #53696 as product dependencies have been removed from the shared test build and this had an implicit dependency edge. We can get this working by adding the dependency explicitly if needed, or removing the download if not necessary.

cc: @dotnet/runtime-infrastructure 

Runfo Tracking Issue: [Pipeline dependency issue: Artifact CoreCLRProduct bits missing.](https://runfo.azurewebsites.net/tracking/issue/136)
|Definition|Build|Kind|Job Name|
|---|---|---|---|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1178491](https://dev.azure.com/dnceng/public/_build/results?buildId=1178491)|[PR 53920](https://github.com/dotnet/runtime/pull/53920)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1178491](https://dev.azure.com/dnceng/public/_build/results?buildId=1178491)|[PR 53920](https://github.com/dotnet/runtime/pull/53920)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1177036](https://dev.azure.com/dnceng/public/_build/results?buildId=1177036)|Rolling|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1177036](https://dev.azure.com/dnceng/public/_build/results?buildId=1177036)|Rolling|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176617](https://dev.azure.com/dnceng/public/_build/results?buildId=1176617)|[PR 53439](https://github.com/dotnet/runtime/pull/53439)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176617](https://dev.azure.com/dnceng/public/_build/results?buildId=1176617)|[PR 53439](https://github.com/dotnet/runtime/pull/53439)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176566](https://dev.azure.com/dnceng/public/_build/results?buildId=1176566)|[PR 52866](https://github.com/dotnet/runtime/pull/52866)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176566](https://dev.azure.com/dnceng/public/_build/results?buildId=1176566)|[PR 52866](https://github.com/dotnet/runtime/pull/52866)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176412](https://dev.azure.com/dnceng/public/_build/results?buildId=1176412)|[PR 53698](https://github.com/dotnet/runtime/pull/53698)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176412](https://dev.azure.com/dnceng/public/_build/results?buildId=1176412)|[PR 53698](https://github.com/dotnet/runtime/pull/53698)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176339](https://dev.azure.com/dnceng/public/_build/results?buildId=1176339)|[PR 53866](https://github.com/dotnet/runtime/pull/53866)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176091](https://dev.azure.com/dnceng/public/_build/results?buildId=1176091)|Rolling|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176091](https://dev.azure.com/dnceng/public/_build/results?buildId=1176091)|Rolling|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176063](https://dev.azure.com/dnceng/public/_build/results?buildId=1176063)|[PR 53669](https://github.com/dotnet/runtime/pull/53669)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1176063](https://dev.azure.com/dnceng/public/_build/results?buildId=1176063)|[PR 53669](https://github.com/dotnet/runtime/pull/53669)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175897](https://dev.azure.com/dnceng/public/_build/results?buildId=1175897)|Rolling|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175897](https://dev.azure.com/dnceng/public/_build/results?buildId=1175897)|Rolling|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175285](https://dev.azure.com/dnceng/public/_build/results?buildId=1175285)|[PR 53836](https://github.com/dotnet/runtime/pull/53836)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175285](https://dev.azure.com/dnceng/public/_build/results?buildId=1175285)|[PR 53836](https://github.com/dotnet/runtime/pull/53836)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175261](https://dev.azure.com/dnceng/public/_build/results?buildId=1175261)|[PR 53763](https://github.com/dotnet/runtime/pull/53763)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1175261](https://dev.azure.com/dnceng/public/_build/results?buildId=1175261)|[PR 53763](https://github.com/dotnet/runtime/pull/53763)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174593](https://dev.azure.com/dnceng/public/_build/results?buildId=1174593)|[PR 53606](https://github.com/dotnet/runtime/pull/53606)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174593](https://dev.azure.com/dnceng/public/_build/results?buildId=1174593)|[PR 53606](https://github.com/dotnet/runtime/pull/53606)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174517](https://dev.azure.com/dnceng/public/_build/results?buildId=1174517)|Rolling|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174291](https://dev.azure.com/dnceng/public/_build/results?buildId=1174291)|[PR 53806](https://github.com/dotnet/runtime/pull/53806)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174264](https://dev.azure.com/dnceng/public/_build/results?buildId=1174264)|[PR 52791](https://github.com/dotnet/runtime/pull/52791)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174264](https://dev.azure.com/dnceng/public/_build/results?buildId=1174264)|[PR 52791](https://github.com/dotnet/runtime/pull/52791)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174155](https://dev.azure.com/dnceng/public/_build/results?buildId=1174155)|Rolling|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174093](https://dev.azure.com/dnceng/public/_build/results?buildId=1174093)|[PR 53656](https://github.com/dotnet/runtime/pull/53656)|Mono monointerpreter Pri0 Runtime Tests Run  OSX x64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1174093](https://dev.azure.com/dnceng/public/_build/results?buildId=1174093)|[PR 53656](https://github.com/dotnet/runtime/pull/53656)|Mono minijit Pri0 Runtime Tests Run  OSX x64 release|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|2|17|17|

**Comment by hoyosjs** [comment]
Is CoreCLR's product build needed to build the coreroot on mono's builds?

**Comment by SingleAccretion** [comment]
See also #53421.

**Comment by hoyosjs** [comment]
So yes, based on the last comment this is bad.

**Comment by akoeplinger** [comment]
If someone knows how to add the dependency in the .yml please feel free to do it :)

**Comment by directhex** [comment]
https://github.com/dotnet/runtime/blob/d617e830ec621db80f6df9ed8ba75176f5ba6035/eng/pipelines/runtime.yml#L596-603 is how you do dependence

**Comment by safern** [comment]
This is a known issue that came out during the surge and that @naricc was working on. https://github.com/dotnet/runtime/issues/43952

It seems like he has not gotten cycles to fix it. 

the short term fix should be make sure we are getting the right dependency always for mono against coreclr here: https://github.com/dotnet/runtime/blob/43b1f2c165257faae4d6a4aa886b701b63d2d5c0/eng/pipelines/common/templates/runtimes/run-test-job.yml#L66
