### ISSUE TITLE
Helix package testing uses LKG shared framework instead of live built

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#53854]
From one of the test binlogs:

```
PlatformManifests = C:\h\w\B0C609B1\p\dotnet-cli\packs\Microsoft.NETCore.App.Ref\6.0.0-preview.3.21201.4\data\PlatformManifest.txt
```

This might be problematic when contents of the shared framework change or when the repository changes versions.

@ericstj @Anipik are we using a LKG SDK in conflict resolution intentionally?

**Comment by ericstj** [comment]
True we can remove this dependency now that we only depend on RefPack.

How were you planning to do this?  Perhaps we can just change the following to use TestPackageVersion.

https://github.com/dotnet/runtime/blob/543a983671252751e3c8128f0e359e8b551e0998/src/libraries/pkg/test/frameworkSettings/net6.0/settings.targets#L3 

Alternatively we can emit a new property that is the live-built version (so it works for packages that aren't on the common versioning).
