### ISSUE TITLE
[Mono] MSBuild Task housekeeping

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#53873]
As discovered in https://github.com/dotnet/runtime/pull/53827, we are hardcoding paths to `net6.0` and `net472` for MSBuild tasks that are configured to multi-target.  We should instead create a template props file and generate with the tool version we have configured in runtime.  

Also, while we are at it, we should create a property similar to `NetCoreAppToolCurrent` and use it within our tasks.  `NetCoreAppToolCurrent` will likely bump more aggressively between new sdks and we won't really need to.  

So, the issue boils down to:

- [x]  Create a property similar to `NetCoreAppToolCurrent` called `NetCoreAppMSBuildTasksCurrent` and update the tasks in `src/tasks` to use it.
- [x]  Create a template Sdk.props file for `Microsoft.NET.Runtime.RuntimeConfigParser.Task` and `Microsoft.NET.Runtime.MonoAOTCompiler.Task`
- [ ] Create a template Sdk.targets file for `Microsoft.NET.Runtime.WebAssembly.Sdk`

**Comment by radical** [comment]
> Create a property similar to NetCoreAppToolCurrent called NetCoreAppMSBuildTasksCurrent and update the tasks in src/tasks to use it.

`NetCoreAppMSBuildTasksCurrent` - this one would for the .net framework, right? Why `*Current` then? Naming can be discussed on the PR too.

**Comment by steveisok** [comment]
@radical Naming is always up for discussion - especially when I name things ;-)
