### ISSUE TITLE
Blazor Debugging Issue

### ISSUE THREAD

**Issue by neufeld-cc** [dotnet/runtime#53878]
### Describe the bug
we have a Blazor Client WASM application that includes several different projects.  When opening up the debugger in Edge or Chrome we only had access to a few of the projects.

I found that any project that had an attribute with an enum in the constructor would not load in the debugger.

### To Reproduce

```
    public enum MyEnum
    {
        FirstEnum,
        SecondEnum,
        LastEnum,        
    }
	
    public class CustomEnumAttribute : Attribute
    {
        public MyEnum MyEnum { get; set; }
        
        public CustomEnumAttribute(MyEnum myEnum) : base()
        {
            this.MyEnum = myEnum;
        }    
    }
		
    // Any project that refrerenced this attribute like this was not included
    public class MyClass
    {
        [CustomEnum(MyEnum.FirstEnum)]
        public object MyProperty { get; set; }
    }

```

Workaround to get my projects to show up in the debugger again:

```
    public enum MyEnum
    {
        FirstEnum,
        SecondEnum,
        LastEnum,        
    }
    
    
    public class CustomEnumAttribute : Attribute
    {
        public MyEnum MyEnum { get; set; }
        
        public CustomEnumAttribute(string myEnumString) : base()
        {
            this.MyEnum = Enum.Parse<MyEnum>(myEnumString);
        }
    }
    
    // To fix this so the project would be able to debug
    public class MyClass
    {
        [CustomEnum("FirstEnum")]
        public object MyProperty { get; set; }
    }
```

**Comment by lewing** [comment]
@neufeld-cc what version of .NET are you using?  I believe this should be fixed in the .NET6 previews.

**Comment by neufeld-cc** [comment]
@lewing we are using .NET 5.0 although some of my referencing projects are .NET Standard 2.1 (I have the same issue with both .NET 5.0 and standard 2.1 projects)

**Comment by lewing** [comment]
I believe this is fixed in .NET6 now.  @thaystg can you confirm and close?

**Comment by thaystg** [comment]
It's fixed.
