### ISSUE TITLE
[wasm] fix SendAsync_GetWithInvalidHostHeader_ThrowsException - doesn't throw on WASM

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#53874]
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http11.SendAsync_GetWithInvalidHostHeader_ThrowsException on WASM in browser expects `HttpRequestMessage.Headers.Host` validation.

```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)\nActual:   (No exception was thrown)]]
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_GetWithInvalidHostHeader_ThrowsException()
```

**Comment by lewing** [comment]
I'm not sure how serious this one is, it looks like we're missing validation on an invalid header and we might end up pulling in a lot of code to do that validation, but someone should take a look.

**Comment by ilonatommy** [comment]
@pavelsavara, what do you think about @lewing's hypothesis?

**Comment by pavelsavara** [comment]
Perhaps it's not that bad ?
https://github.com/dotnet/runtime/blob/3c33b4293107c607ae8669545114d6f9891432cb/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpRequestHeaders.cs#L116

https://github.com/dotnet/runtime/blob/3c33b4293107c607ae8669545114d6f9891432cb/src/libraries/System.Net.Http/src/System/Net/Http/HttpRuleParser.cs#L199
