### ISSUE TITLE
Dynamically load netstandard implementation assembly

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/runtime#53884]
We have an application that dynamically loads types that are specified in a configuration file.
In .NET Framework it is fairly simple by just calling Type.GetType() assuming all dependencies are present in the working directory.

We run into issues when porting the application to .NET Core and .NET 5.0 since the application is required to explicitly load/resolve dependency assemblies. The code below takes care of most assemblies that are present in the working directory:

```
        static ServiceManager()
        {
            AssemblyLoadContext.Default.Resolving += LoadAssembly;
        }

        private static Assembly LoadAssembly(AssemblyLoadContext context, AssemblyName assemblyName)
        {
            var exeName = $"{assemblyName.Name}.exe";
            var dllName = $"{assemblyName.Name}.dll";

            var assemblyPath = File.Exists(exeName)
                ? Path.Combine(Environment.CurrentDirectory, exeName)
                : Path.Combine(Environment.CurrentDirectory, dllName);

            return context.LoadFromAssemblyPath(assemblyPath);
        }

```
However it cannot resolve the netstandard implementation assemblies such as:

```
EXCEPTION (LEVEL 1): System.IO.FileNotFoundException
EXCEPTION MESSAGE: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
STACK TRACE:
```

What is the recommended .NET Core/.NET 5.0+ API for resolving such assemblies?

**Comment by vitek-karas** [comment]
Are all the assemblies the app will need to load part of the app when it's built, or you add assemblies by copying files into the application directory?

Do you run the application as self-contained or framework-dependent (for example, does you application directory contain `coreclr.dll`)?

As for the specific error, do you happen to have two versions of the ASP.NET assembly somewhere?

You can try using [assembly binder tracing](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/collect-details) to get very detailed information about the resolution process including more detailed error information. That might help diagnose what's going on.

Does the file `Microsoft.AspNetCore.Mvc.Core.dll` exist in the application directory?

**Comment by WenningQiu** [comment]
The assemblies the app needs to load is unknown to the app at build time so they cannot be referenced by the app project; the assemblies are instead copied into the application's directory.

The application should work for both self-contained and framework-dependent deployment scenarios, although my testing was framework-dependent scenario when the issue was discovered.

I may have multiple versions of ASP.NET Core assemblies somewhere on my system, but there should be only one version in the application's directory.

File `Microsoft.AspNetCore.Mvc.Core.dll` is netstandard2.0 assembly that comes from package microsoft.aspnetcore.mvc.core, the assembly is not copied to the application's directory, instead an appropriate implementation assembly should be resolved/supplied by .NET Core runtime.

Thanks for suggesting "assembly binder tracing", I'll take a look.

**Comment by vitek-karas** [comment]
Thanks for the info.
.NET Core does not probe for files on disk on its own. Instead the default resolution logic only relies on information written by the SDK into the `app.deps.json` file. So copying additional assemblies into the application's directory will not make them available to the app automatically. Implementing assembly resolution handler is one way to solve this problem (a good way). Couple of notes to the code you shared:
* In .NET Core or .NET 5+ managed assemblies should never have the `.exe` extension. It might be better to only work with `.dll`.
* If the assemblies should be in the same directory as the application, then a better way to get that path is [`AppContext.BaseDirectory`](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.basedirectory?view=net-5.0). Current directory doesn't have to point to the application directory and it may lead to loading assemblies from different place.

Regarding `Microsoft.AspNetCore.Mvc.Core`. Where does the exception come from? Is it from your resolution handler or somewhere else?

Is your app built as an ASP.NET app? In .NET Core/.NET 5+ there are multiple frameworks. The "core" one is `Microsoft.NETCore.App` but that doesn't contain ASP.NET assemblies. To use ASP.NET the app must reference `Microsoft.AspNetCore.App` framework as well. You can check this in the `app.runtimeconfig.json` file produced in the output. If the app is not referencing ASP.NET framework then it won't resolve the ASP.NET assembly and it would probably fail this way.

**Comment by davidfowl** [comment]
These are good questions. ASP.NET Core is a shared framework and the packages you're using are deprecated for ASP.NET Core >= 3.0. You might get lucky and it might work but the latest versions of these [packages](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core/) should indicate to you that they are a dead end 😄 (2.2.5).

**Comment by WenningQiu** [comment]
@vitek-karas, @davidfowl Thanks for the information.

The application is capable of hosting the configured types as Windows Service or Daemon and it has no reference to ASP.NET or ASP.NET Core. 

The dynamically loaded type uses ASP.NET Core to host its business logic, and that's where the dependency to `Microsoft.AspNetCore.Mvc.Core` comes from. However the project for the type targets net48, netcoreapp2.1, netcoreapp3.1 and ne5.0, and reference to `microsoft.aspnetcore.mvc.core` package is conditional on net48 and netcoreapp2.1 only which I was able to verify in `project.assets.json`. So request for `Microsoft.AspNetCore.Mvc.Core` at runtime on .NET Core 3.1 is really puzzling.

One the other hand, everything works if I let the application directly reference the project for the loaded type without using assembly resolution handler.

**Comment by vitek-karas** [comment]
Currently we don't have a way to dynamically load frameworks. So in this case I would recommend to build the app with a reference to ASP.NET Core framework. It will have very little effect on the app - runtime loads code lazily, so if nothing needs ASP.NET then it won't get loaded.

(For example, this is the reason why PowerShell 7 is built as a .NET app with reference to the WindowsDesktop framework, even though powershell itself doesn't need anything from it, but it could load cmdlets which might need WinForms or similar)

If you directly reference the code in the app I think it works because SDK recognizes that the ASP.NET assembly is not in the framework and will copy it into the app directory.

**Comment by WenningQiu** [comment]
To confirm @vitek-karas's comment of "currently we don't have a way to dynamically load frameworks" and to clarify the "puzzling" comment I made about `Microsoft.AspNetCore.Mvc.Core` - the version of `Microsoft.AspNetCore.Mvc.Core` that fails to be resolved is 3.1.0.0 on .NET Core 3.1 and 5.0.0.0 on .NET 5.0, not the versions that are in package `microsoft.aspnetcore.mvc.core`; so it is something internal to the frameworks.

**Comment by vitek-karas** [comment]
It's hard to tell what's going on, if you could get the detailed binder trace (as per above link) that should tell us exactly what's going on an why.

**Comment by WenningQiu** [comment]
@vitek-karas Please find the attached trace.
[net5trace.zip](https://github.com/dotnet/runtime/files/6639058/net5trace.zip)

**Comment by davidfowl** [comment]
What does your project file look like @WenningQiu ?

**Comment by WenningQiu** [comment]
@davidfowl I forgot to mention that the problem appears to be solved by following @vitek-karas  suggestion to add more references to the hosting app, specifically by changing Worker SDK to Web SDK. Below is the project file (simplified with irrelevant stuff removed) for the hosting app:

```
<Project Sdk="Microsoft.NET.Sdk.Web">  <!-- Used to be "Microsoft.Net.Sdk.Worker"  -->
  <PropertyGroup>
    <RootNamespace>CSG.Framework.WorkerService</RootNamespace>
    <AssemblyName>CSG.Framework.WorkerService</AssemblyName>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\Framework.snk</AssemblyOriginatorKeyFile>
    <TargetFrameworks>net48;netcoreapp3.1;net5.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <PlatformTarget>$(Platform)</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet>..\..\..\Framework.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType Condition=" '$(TargetFramework)' == 'net48' ">full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <IncludeSymbols>true</IncludeSymbols>
    <CodeAnalysisRuleSet>..\..\..\Framework.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType Condition=" '$(TargetFramework)' == 'net48' ">pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup  Condition=" '$(TargetFramework)' == 'net48' ">
    <!--
    5.0.x packages build for net48 but would have the error below at runtime.
    Could not load type 'Microsoft.Extensions.Primitives.InplaceStringBuilder' from assembly 'Microsoft.Extensions.Primitives, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
    -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.15" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.15" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' != 'net48' ">
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\Framework.snk" />
  </ItemGroup>
</Project>
```

**Comment by davidfowl** [comment]
So everything is sovled?

**Comment by WenningQiu** [comment]
Yes this particular issue is solved by changing the hosting app to use Web SDK.

**Comment by davidfowl** [comment]
Great!
