### ISSUE TITLE
Fully trimmed console hello world fails to start the runtime

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#53898]
Using latest nightly SDK from dotnet/installers on Windows x64

 ```console
dotnet new console
dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimmerDefaultAction=link
.\bin\Debug\net6.0\win-x64\publish\app.exe
```

Will fail with:
```console
Failed to create CoreCLR, HRESULT: 0x80004005
```

The failure happens during `coreclr_initialize` so only `System.Private.CoreLib` was loaded. Which means trimming corelib itself is the problem, no user code is involved.

This is VERY likely related to Built-in COM trimming. Publishing the app with:
```console
dotnet publish -r win-x64 -p:PublishTrimmed=true -p:TrimmerDefaultAction=link -p:BuiltInComInteropSupport=true
```

will fix the problem and the app starts just fine.

**Comment by vitek-karas** [comment]
The problem is very likely this line: https://github.com/dotnet/runtime/blob/d35882aece16fedf8c2b0538a8fa5a6e46b28dab/src/coreclr/vm/appdomain.cpp#L1508

This will unconditionally try to load `System.__ComObject` class, but that is not rooted since the class definition in corelib.h is behind the `BuiltInComInteropIsSupported` feature switch:
https://github.com/dotnet/runtime/blob/0377558d943bec26031ec4801f3ff1f7e1caeb53/src/coreclr/vm/corelib.h#L205-L209

We'll have to figure out if the native-side BuiltinComInteropSupport feature switch boolean is initialized by the time we get to AppDomain.cpp and put the `__ComObject` load under a condition. Assuming it's safe to do so - hard to tell what else in the runtime might require that class to exist and it's not being the feature switch check either.

**Comment by agocke** [comment]
Looks like an unconditional load to me
https://github.com/dotnet/runtime/blob/0377558d943bec26031ec4801f3ff1f7e1caeb53/src/coreclr/vm/appdomain.cpp#L1508

**Comment by agocke** [comment]
Heh, found it at the same time.

I'm surprised any of these failures result in such a bad error message. Any way we could print something more useful here? Regardless of the fix?

**Comment by vitek-karas** [comment]
Honestly this is more of a CoreCLR global question - when really bad things happen in CoreCLR the error reported is bad, to say the least. If I read the code correctly this should be throwing exception internally and then catching it here: https://github.com/dotnet/runtime/blob/0377558d943bec26031ec4801f3ff1f7e1caeb53/src/coreclr/vm/ceemain.cpp#L1070. But the catch basically swallows it - it only sets the `E_FAIL` here: https://github.com/dotnet/runtime/blob/0377558d943bec26031ec4801f3ff1f7e1caeb53/src/coreclr/vm/ceemain.cpp#L1088 because it doesn't know any better.

I have no idea why we can't extract anything from the exception and print it out - granted, it's dangerous to do anything since the runtime is not correctly initialized.

**Comment by LakshanF** [comment]
I found the __comobject case as well and will try to special case that class so as not to have that under the feature switch to see if that will fix the issue (should move past this particular failure)
