### ISSUE TITLE
HTTP-HTTPS redirection issue after installation of .NET Core 5 Runtime.

### ISSUE THREAD

**Issue by fdaniels110** [dotnet/runtime#53906]
### Description

We have a .NET Core 3.1 application using the Azure AD B2B integration with Identity.  The application sits behind a firewall that translates any incoming request to HTTP from HTTPS.  Normally that would cause a correlation issue, but we added a little snippet of middleware to the service 
```C#
services.Configure<OpenIdConnectOptions>(AzureADDefaults.OpenIdScheme, options =>
{
    options.Events.OnRedirectToIdentityProvider = async ctx =>
    {
        var url = ctx.ProtocolMessage.RedirectUri = Configuration.GetValue(typeof(string), "AppUrl") + Configuration.GetSection("AzureAD:CallbackPath").Value;
        Task.FromResult(0);
    };
}
```
with the fully qualified URL in the `appsettings.json` file as such 
```json
{
"AppUrl": "https://<baseUrl>/<appUrl>"
}
```
This worked until yesterday when we installed the .NET 5 Hosting Bundle and Runtime after which requests were starting to fail after an https redirect.  Connections resumed after removing the translation _(Note: a change I greatly approve)_

Was there any change to the way that http requests are processed or correlated?  
Would a .NET 5 runtime installation mess normally mess with the .NET 3.1 runtime in such a way?

### Configuration

* Which version of .NET is the code running on?
.NET Core 3.1 with default build config and with the following publish settings
publish -o release/Release --configuration Release ./_project_.csproj
* What OS and version, and what distro if applicable?
Windows Server 2012 
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
No

**Comment by wfurt** [comment]
The runtimes should be fully independent @fdaniels110 . You should check your service to figure out if 3.1 is actually used as expected. Note that single process can only use one runtime. So for example if you have have library targeting 3.1 but if the service runs with 5.0 even the library code will be executed with 5.0.

**Comment by chucker** [comment]
@fdaniels110 do you happen to have the Windows Update KB5003637 installed?

**Comment by fdaniels110** [comment]
> 
> 
> The runtimes should be fully independent @fdaniels110 . You should check your service to figure out if 3.1 is actually used as expected. Note that single process can only use one runtime. So for example if you have have library targeting 3.1 but if the service runs with 5.0 even the library code will be executed with 5.0.

Hi @wfurt, the application should be running as 3.1 as there is only one project that generates a dll and that project specifies a TargetFramework of 3.1 in its project file.  Unless there is a way for Nuget packages to run in a different runtime than the parent application?  
In that case, these are the only Packages referenced that could run in a different context.
```xml
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="3.1.2" />
    <PackageReference Include="Microsoft.Web.Administration" Version="11.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.0-preview1.19506.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.0-preview1.19506.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="3.1.0-preview1.19506.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="System.DirectoryServices" Version="4.7.0" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="4.7.0" />
    <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
  </ItemGroup>
```

> 
> 
> @fdaniels110 do you happen to have the Windows Update KB5003637 installed?

Hi @chucker, no I do not have that installed. Patches were last applied in May and this was release this week it looks like.

**Comment by karelz** [comment]
Triage: Not enough info, closing for now. Feel free to reopen when there is additional information.
