### ISSUE TITLE
Test failures in "runtime-coreclr libraries-jitstress" pipeline

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#53940]
Starting with:

https://dev.azure.com/dnceng/public/_build/results?buildId=1178460&view=ms.vss-test-web.build-test-results-tab

many new x64/arm64 issues (x86 issues are https://github.com/dotnet/runtime/issues/53568)

I tracked down System.Diagnostics.Tests.ProcessWaitingTests.WaitAsyncForPeerProcess (windows x64 JitStress=2) to https://github.com/dotnet/runtime/pull/53684

@tannergooding

**Comment by tannergooding** [comment]
I'll revert #53684, apparently running outerloop and gcstress wasn't enough and there is some issue remaining.

**Comment by tannergooding** [comment]
https://github.com/dotnet/runtime/pull/53942 reverts the problematic PR.
