### ISSUE TITLE
RemoveEach method for List to remove and iterate item in one function

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#53980]
## Background and Motivation

For adding flexibility of powerful `RemoveAll` function that internally manage array of the list efficiently. We can have control over how to use the removed element while iterating array only once in any way and compact code signature. I would like to have another method that return `IEnumerable<(T item,int index)>` instead of just `int` counter

## Proposed API

```diff
namespace System.Collections.Generic
{
    public class List<T> : IList<T>, IList, IReadOnlyList<T> {

-       public int RemoveAll(Predicate<T> match)
+       public int RemoveAll(Predicate<T> match) => RemoveEach(match).Count();
+        public IEnumerable<(T item,int index)> RemoveEach(Predicate<T> match)
        {
            if (match == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.match);
            }

            int freeIndex = 0;   // the first free slot in items array

            // Find the first item which needs to be removed.
            while (freeIndex < _size && !match(_items[freeIndex])) freeIndex++;
-           if (freeIndex >= _size) return 0;
+           if (freeIndex >= _size) yield break;
+           yield return (_items[freeIndex],freeIndex);

            int current = freeIndex + 1;
            while (current < _size)
            {
                // Find the first item which needs to be kept.
-               while (current < _size && match(_items[current])) current++;
+               while (current < _size && match(_items[current]))
+               {
+                   yield return (_items[current],current);
+                   current++;
+               }

                if (current < _size)
                {
                    // copy item to the free slot.
                    _items[freeIndex++] = _items[current++];
                }
            }

            if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
            {
                Array.Clear(_items, freeIndex, _size - freeIndex); // Clear the elements so that the gc can reclaim the references.
            }

-           int result = _size - freeIndex;
            _size = freeIndex;
            _version++;
-           return result;
        }

    }
}
```
## Usage Examples

``` C#
var items = new List<Item>();
var pairedID = new List<Item,GUID>();

////

foreach(var (item,index) in items.RemoveEach((item) => item.Destroyed))
    dictionary.Remove(item);

var diabled = items.RemoveEach((item) => !item.Enabled).Select((pair) => pair.item).ToArray(); // splitting List into Item[]

```

## Alternative Designs

There are many alternative approach but none are as compact and efficient as this

## Risks

This would possible to create incomplete iteration and threading problem maybe?

**Comment by huoyaoyuan** [comment]
Delegating `RemoveAll` to the new method will degrade its performance.

Another concern is that during the execution of `RemoveAll`, list is in a inconsistent state and will recover when it completes. If the new api returns `IEnuemrable<T>`, what should be the state of the list during enumeration? Inconsistent state is definitely not an option.

**Comment by Thaina** [comment]
> Delegating `RemoveAll` to the new method will degrade its performance.
> 
> Another concern is that during the execution of `RemoveAll`, list is in a inconsistent state and will recover when it completes. If the new api returns `IEnuemrable<T>`, what should be the state of the list during enumeration? Inconsistent state is definitely not an option.

That was certainly a risk I had mention. But I think that was developer's own risk, another option it to make it become the same state as normal iteration in foreach (when we iterate collection and add or remove object, it will throwing `InvalidOperationException`)

Delegating `RemoveAll` is just for convenient to write diff here, it not necessary, we can keep it as it was

**Comment by eiriktsarpalis** [comment]
I think @huoyaoyuan makes an excellent point about the enumerator modifying the source list. This is something of an anti-pattern, as in general the expectation with enumerables is that they be enumerated deterministically multiple times without side-effects. I don't think we should be adding such a method to `List<T>`.

That being said, I understand the motivation for requesting this. Out of curiosity, have you tried measuring the performance of your use case with the proposed method versus an implementation that iterates over the list twice? Roughly
```csharp
foreach (T item in list)
{
    // handle elements to be removed
    if (predicate(item)) handleRemovedItem(item);
}

// finally, remove them.
list.RemoveAll(predicate);
```

**Comment by Thaina** [comment]
@eiriktsarpalis That would be also up to the complication of predicate logic. If the logic have to access intensive property for example, that would scaling two times that predicate

Another problem is the handle might make the property of item changed and predicate function might rely on that property

**Comment by rootflood** [comment]
@Thaina hi friend
i have few problem with RemoveEach, in fact IEnuemrable never execute until IEnuemrable.ToArray() is execute so developer should execute that to ensure remove
so:
```c#
List<T> List;
var Res =  List.RemoveEach(match);// not removed but executed
Res.ToArray(); // Removed!
```
but i think this problem can fix with
```C#
public int RemoveAll(Predicate<T> match, out T[] Removed)
```
what do you think?

**Comment by eiriktsarpalis** [comment]
> That would be also up to the complication of predicate logic. If the logic have to access intensive property for example, that would scaling two times that predicate
>
> Another problem is the handle might make the property of item changed and predicate function might rely on that property

These are valid concerns in principle, but it would be interesting to see how they translate to benchmarks in your particular use case.

> but i think this problem can fix with
>
>> public int RemoveAll(Predicate<T> match, out T[] Removed)
>> public int RemoveAll(Predicate<T> match, action<T> NotMatch)
>
> what do you think?

@rootflood it is possible to express both of these methods in terms of the existing `RemoveAll` method. For example
```csharp
public static int RemoveAll(this List<T> list, Predicate<T> match, Action<T> notMatched) 
    => list.RemoveAll(t =>
        {
            if (match(t)) return true;
            notMatched(t);
            return false;
        });
```

I neglected to mention that adding more methods to a popular generic class like `List<T>` adds runtime overhead in a non pay-for-play way. We generally avoid doing it unless there is overwhelming evidence that the addition provides value to users. I would say that this proposal addresses a niche use case so it's unlikely it would ever be accepted.

With that being said I'm going to close the issue, thank you for contributing the proposal!

**Comment by rootflood** [comment]
>I neglected to mention that adding more methods to a popular generic class like List<T> adds runtime overhead in a non pay-for-play way.

right, nanoseconds have overhead very much and even more than class initialization every time
