### ISSUE TITLE
ETW + GetJitOptimizationTier causes application to hang on exit

### ISSUE THREAD

**Issue by leculver** [dotnet/runtime#540]
**Issue**:  There is a deadlock on shutdown in this callstack:

    03 coreclr!__DangerousSwitchToThread
    04 coreclr!__SwitchToThread
    05 coreclr!SpinLock::SpinToAcquire
    06 coreclr!SpinLock::GetLock
    07 coreclr!SpinLock::Holder::{ctor}
    08 coreclr!CallCounter::IsCallCountingEnabled
    09 coreclr!TieredCompilationManager::GetInitialOptimizationTier
    0a coreclr!PrepareCodeConfig::GetJitOptimizationTier
    0b coreclr!ETW::MethodLog::SendMethodEvent
    0c coreclr!ETW::MethodLog::SendEventsForJitMethodsHelper
    0d coreclr!ETW::MethodLog::SendEventsForJitMethods
    0e coreclr!ETW::EnumerationLog::IterateDomain
    0f coreclr!ETW::EnumerationLog::IterateAppDomain
    10 coreclr!ETW::EnumerationLog::EnumerationHelper
    11 coreclr!ETW::EnumerationLog::ProcessShutdown
    12 coreclr!EEShutDownHelper
    13 coreclr!EEShutDown

**Root Cause**:  I think when the process was shutdown, some other thread was holding the CallCounter spinlock.  When IsCallCountingEnabled attempts to take that same spinlock it will spin forever.

I'm not sure the right fix here, but it seems like we need to check if the process has shut down in [SpinToAcquire](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/spinlock.cpp#L267) and if so either FailFast or allow the lock to be taken since it'll never be released.

**Crash dumps:** I've placed several crash dumps on this internal share: \\\\leculver0\public\12_04_spin

**Impact**:  This deeply impacts Visual Studio users with .Net Core based unit tests.  For example, this bug is absolutely killing my productivity right now.

VS turns on ETW while debugging tests, and since these unit tests (obviously) load your dlls into memory, they cannot be written to while the test is running.  This means that if the test process hangs on shutdown and you can no longer build your project because the files are locked.  This happens regularly, I'm seeing it multiple times per hour requiring me to "taskkill" the offending process.

What's worse, about once every hour or two one of these processes will go into a strange zombie state where I cannot kill it, but the files remain locked...requiring a reboot or log out to kill the process.  (This is likely an unrelated windows issue, but it still makes the bug even more annoying).

This has also been reported by our end users in VS who use .Net Core based unit tests.  Here's a two external issues opened about this (but there's likely others, I didn't dig deeply):
https://developercommunity.visualstudio.com/content/problem/793032/the-file-is-locked-by-net-core-host.html
https://developercommunity.visualstudio.com/content/problem/396723/the-file-is-locked-by-net-core-host-9988-visual-st.html

**Comment by leculver** [comment]
@jkotas @stephentoub Do either of you all know who might be a good person to take a look at this?

**Comment by jkotas** [comment]
Looks like a dup of https://github.com/dotnet/coreclr/issues/27129 . Try upgrading to 3.1 - the fix should be included in 3.1.

cc @kouvel

**Comment by leculver** [comment]
Ah this is on 3.0 I think.  We might need to get VS updated with this fix?

    00007ff8`027e0000 00007ff8`02d4a000   coreclr    (private pdb symbols)  d:\symbols\coreclr.pdb\E96688D2489144F78DDBF2FFA384BB481\coreclr.pdb
        Loaded symbol image file: coreclr.dll
        Image path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0\coreclr.dll
        Image name: coreclr.dll
        Browse all global symbols  functions  data
        Timestamp:        Thu Sep 12 16:02:04 2019 (5D7ACE6C)
        CheckSum:         0055E336
        ImageSize:        0056A000
        File version:     4.700.19.46205
        Product version:  4.700.19.46205
        File flags:       0 (Mask 3F)
        File OS:          4 Unknown Win32
        File type:        0.0 Unknown
        File date:        00000000.00000000
        Translations:     0409.04b0
        Information from resource tables:
            CompanyName:      Microsoft Corporation
            ProductName:      Microsoft® .NET Core
            InternalName:     CoreCLR.dll
            OriginalFilename: CoreCLR.dll
            ProductVersion:   4,700,19,46205 @Commit: 922429db0144dd6f3b4324805464dae82857512a
            FileVersion:      4,700,19,46205 @Commit: 922429db0144dd6f3b4324805464dae82857512a
            FileDescription:  Microsoft .NET Runtime
            LegalCopyright:   © Microsoft Corporation.  All rights reserved.
            Comments:         Flavor=Retail

**Comment by jkotas** [comment]
Next VS update should start bundling 3.1 instead of 3.0.

**Comment by reduckted** [comment]
> @jkotas Next VS update

By "next VS update", do you mean 16.5 or do you mean the next 16.4.x release?

**Comment by jkotas** [comment]
I believe that it is in 16.4. https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1/ has some more details.

**Comment by kouvel** [comment]
This should be resolved by https://github.com/dotnet/coreclr/pull/27238 (master) and https://github.com/dotnet/coreclr/pull/27241 (3.1)

**Comment by leculver** [comment]
The question I have is: Are we satisfied that the fix in 3.1 is sufficient to ensure our customers have a way out of this problem?  I ended up having to uninstall 3.0 and install 3.1 to get this failure to stop, will our customers be able to figure this out from the symptoms given (or do we expect no new customers will be bitten by this)?

**Comment by jkotas** [comment]
> Are we satisfied that the fix in 3.1 is sufficient

Yes. [.NET Core 3.0 support ends](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) in ~7 weeks.
