### ISSUE TITLE
Question about new DateOnly / TimeOnly wrt DateTime

### ISSUE THREAD

**Issue by celluj34** [dotnet/runtime#54003]
Hello;

With the introduction of `DateOnly` and `TimeOnly` in .Net 6, was there any consideration or discussion about updating `DateTime` to be a composition of a `DateOnly` and a `TimeOnly` property?

**Comment by huoyaoyuan** [comment]
For performance, the internal storage of `DateTime` is more compact than `DateOnly`  plus `TimeOnly`. Currently converting `DateTime` to `DateOnly` and `TimeOnly` are done by constructors. There can be properties and composing constructor.

**Comment by celluj34** [comment]
That all makes sense. I was just curious, thanks!
