### ISSUE TITLE
Add NetCoreAppCurrent configurations to every library that targets .NETStandard or .NETCoreApp

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54012]
With the evolution of .NET (net5.0 and above), building .NETCoreApp libraries becomes more important as they benefit from features like linking, compiler optimizations and the platform analyzer which is not enabled in dotnet/runtime for .NETStandard and .NETFramework tfms. To go even further, nullability warnings are more mature when targeting the very latest .NETCoreApp configuration and newer APIs become available to target which are often more efficient or easier to read. An example of such an API is the string.Contains usage over string.IndexOf which .NET even warns about now. Last but not least this avoid the need to reference the netstandard shim which means we don't cross assembly universes.

I propose to add a `NetCoreAppCurrent` configuration to any library that doesn't have one and targets .NETStandard or .NETCoreApp. Please note that this won't increase the overall build times as by default, only the best applicable tfm is built per project in a traversal build. That said, when building an individual library, build times will increase slightly as filtering doesn't happen there.

@marek-safar and @eerhardt especially expressed their interest in this.

Here's the list of the 49 libraries which don't have a `NetCoreAppCurrent` (and neither any .NETCoreApp) configuration:

- [ ] Microsoft.Extensions.Caching.Abstractions
- [ ] Microsoft.Extensions.Caching.Memory
- [x] Microsoft.Extensions.Configuration
- [x] Microsoft.Extensions.Configuration.Abstractions
- [x] Microsoft.Extensions.Configuration.Binder
- [x] Microsoft.Extensions.Configuration.CommandLine
- [x] Microsoft.Extensions.Configuration.EnvironmentVariables
- [ ] Microsoft.Extensions.Configuration.FileExtensions
- [ ] Microsoft.Extensions.Configuration.Ini
- [ ] Microsoft.Extensions.Configuration.Json
- [ ] Microsoft.Extensions.Configuration.UserSecrets
- [ ] Microsoft.Extensions.Configuration.Xml
- [x] Microsoft.Extensions.DependencyInjection
- [x] Microsoft.Extensions.DependencyInjection.Abstractions
- [ ] Microsoft.Extensions.DependencyInjection.Specification.Tests
- [x] Microsoft.Extensions.DependencyModel
- [x] Microsoft.Extensions.FileProviders.Abstractions
- [ ] Microsoft.Extensions.FileProviders.Composite
- [x] Microsoft.Extensions.FileProviders.Physical
- [x] Microsoft.Extensions.FileSystemGlobbing
- [x] Microsoft.Extensions.Hosting
- [ ] Microsoft.Extensions.Hosting.Abstractions
- [x] Microsoft.Extensions.Hosting.Systemd: https://github.com/dotnet/runtime/pull/59880
- [ ] Microsoft.Extensions.Hosting.WindowsServices
- [ ] Microsoft.Extensions.Http
- [ ] Microsoft.Extensions.Logging
- [ ] Microsoft.Extensions.Logging.Configuration
- [ ] Microsoft.Extensions.Logging.Debug
- [ ] Microsoft.Extensions.Logging.EventLog
- [ ] Microsoft.Extensions.Logging.TraceSource
- [ ] Microsoft.Extensions.Options
- [ ] Microsoft.Extensions.Options.ConfigurationExtensions
- [ ] Microsoft.Extensions.Options.DataAnnotations
- [x] Microsoft.Win32.Registry.AccessControl: https://github.com/dotnet/runtime/pull/54544
- [x] System.ComponentModel.Composition.Registration: https://github.com/dotnet/runtime/pull/54544
- [x] System.Composition.AttributedModel: https://github.com/dotnet/runtime/pull/54544
- [x] System.Composition.Convention: https://github.com/dotnet/runtime/pull/54544
- [x] System.Composition.Hosting: https://github.com/dotnet/runtime/pull/54544
- [x] System.Composition.Runtime: https://github.com/dotnet/runtime/pull/54544
- [x] System.Composition.TypedParts: https://github.com/dotnet/runtime/pull/54544
- [x] System.Data.OleDb: https://github.com/dotnet/runtime/pull/54544
- [x] System.IO.Packaging: https://github.com/dotnet/runtime/pull/54544
- [x] System.IO.Ports https://github.com/dotnet/runtime/pull/54544
- [x] System.Memory.Data: https://github.com/dotnet/runtime/pull/54544
- [x] System.Net.Http.WinHttpHandler: https://github.com/dotnet/runtime/pull/54544
- [x] System.Numerics.Tensors: https://github.com/dotnet/runtime/pull/54544
- [x] System.Reflection.Context: https://github.com/dotnet/runtime/pull/54544
- [x] System.Resources.Extensions: https://github.com/dotnet/runtime/pull/54544
- [x] System.Threading.AccessControl: https://github.com/dotnet/runtime/pull/54544

cc @ericstj @Anipik @safern @stephentoub @jkotas

**Comment by jkotas** [comment]
You may be missing `System.IO.Hashing` that is recent addition and does not have `NetCoreAppCurrent`. (It has `net6.0` that is not the same thing.)

**Comment by jkotas** [comment]
cc @davidfowl

**Comment by ericstj** [comment]
@ViktorHofer you talk about some of the benefits the .NET team may see by adding these configurations.  What is the impact to our customers?  What benefits will they see by us doing this, and are there any downsides?

**Comment by ViktorHofer** [comment]
Some of the advantages that are listed in the top post are observable by customers as well but let me exclusively list the pros and cons for customers.

Pro:
- Better nullability annotations based on nullability warnings being more mature on `NetCoreAppCurrent` than on .NETStandard.
- Being able to use APIs which are only available on the very latest and greatest version of .NETCoreApp
- `NetCoreAppCurrent` compiled assemblies should be more efficient than .NETStandard ones as more efficient APIs can be used under the shell and because of compiler optimizations that aren't available on .NETStandard.
- Something that I discussed with @eerhardt offline and which he believes shouldn't be neglected is the reduced amount of infrastructure maintenance. Community members usually don't know which references they need to add to satisfy a new build configuration and by adding the configurations as part of the repository versioning, that's already handled. Of course this doesn't exclusively apply to community members, we ourselves often struggle with adding new configurations. Ultimately that results in more time for feature and productivity work which should have a positive impact on our customers.
- Probably hard to measure but by not requiring the netstandard.dll shim, less type forwarding is happening during runtime.

Cons:
- Bigger packages. For most of the packages listed above, usually an increase of few KB - i.e. Microsoft.Extensions.FileSystemGlobbing.dll is 37KB small. There are of course exceptions when libraries target multiple rids.
- Not something that is introduced by this change but an overall concern: The .NETStandard configuration in the packages becomes untested as currently there's no suitable tfm in our test matrix that would pick the .NETStandard asset over the .NETCoreApp one. That of course opens the question what the .NETStandard implementation assembly is used for as .NETCoreApp and .NETFramework tfms are available which are preferred during runtime.

With the recent added support for shipping `NetCoreAppCurrent` assets in packages and being able to validate them in the packaging system together with the defined package support policy that dotnet/runtime now adheres I believe the pros 
outweigh the cons.

**Comment by eerhardt** [comment]
> opens the question what the .NETStandard implementation assembly is used for as .NETCoreApp and .NETFramework tfms are available which are preferred during runtime

Xamarin, Unity, UWP, etc. That list will get smaller over time, but there are other runtimes that aren't core or desktop that get used today.

**Comment by ViktorHofer** [comment]
cc @buyaa-n for the platform analyzer aspect of this discussion

**Comment by ericstj** [comment]
> Bigger packages. For most of the packages listed above, usually an increase of few KB 

This should be an easy thing to measure and share (even if only an estimate based on a good heuristic).  We could diff that with what was previously shipped (eg: before asset deprecation) to demonstrate the net result.  Perhaps we can also extrapolate over time what it would look like given our support policy.  One of the arguments against additional configurations in the past was unbounded package growth, now we're saying it's not unbounded, it's only X number of configurations for in-support .NET versions.  It'd be nice to say what the total impact is to all impacted packages and back up our statement about overall impact being small.

> Not something that is introduced by this change but an overall concern: The .NETStandard configuration in the packages becomes untested

While that characteristic isn't introduced with this change it does become more important as it's easier for folks to create differences between configurations.  I can imagine this being important for libraries like System.Text.Encodings.Web, System.Text.Json, and Microsoft.Extensions.* where we're doing active feature development and would care about how those features function on older frameworks (that are still in support).  I wonder what it would take to support downlevel test runs for these?  I can imagine it's much cheaper now that helix has support for deploying frameworks and we build the tests in a way that they shouldn't depend on a custom shared framework.

I really like this direction and I think it sets us up for an overall better maintainable codebase over future releases.

@ViktorHofer it seems like this and some of your other changes work together to realize an overall vision for our targeting strategy over the lifetime of .NET 6.0 onward.  Do you think it makes sense to record this in a vision/design doc?

**Comment by ViktorHofer** [comment]
> This should be an easy thing to measure and share (even if only an estimate based on a good heuristic). We could diff that with what was previously shipped (eg: before asset deprecation) to demonstrate the net result. Perhaps we can also extrapolate over time what it would look like given our support policy. One of the arguments against additional configurations in the past was unbounded package growth, now we're saying it's not unbounded, it's only X number of configurations for in-support .NET versions. It'd be nice to say what the total impact is to all impacted packages and back up our statement about overall impact being small.

Easy as of that I just spent 4 hours collecting and analyzing the data, sure 😄. For the analysis I respected both the assemblies sizes as well as the documentation file sizes. Please see the table below that provides data or the discussed packages. The size increase in the Microsoft.Extensions.* packages are expected as those didn't benefit from the removal of unsupported assets. The biggest outliner is System.Data.OleDb which grow 2-3x (depending on NET 7 vs NET 8).

| PackageId | CurrentSize | ApplicableTFM Size | 5.0 Package Size | 6.0 New Package Size | 7.0 Package Size | 8.0 Package Size |
| --- | --- | --- | --- | --- | --- | --- |
| Microsoft.Extensions.Caching.Abstractions | 39.67 KB | 7.91 KB |  | 47.58 KB (+ 19.94%) | 55.49 KB (+ 39.87%) | 63.39 KB (+ 59.81%) |
| Microsoft.Extensions.Caching.Memory | 48.28 KB | 13.81 KB |  | 62.09 KB (+ 28.59%) | 75.9 KB (+ 57.19%) | 89.7 KB (+ 85.78%) |
| Microsoft.Extensions.Configuration | 44.11 KB | 10.24 KB |  | 54.35 KB (+ 23.22%) | 64.59 KB (+ 46.44%) | 74.83 KB (+ 69.67%) |
| Microsoft.Extensions.Configuration.Abstractions | 36.13 KB | 7.12 KB |  | 43.25 KB (+ 19.71%) | 50.38 KB (+ 39.42%) | 57.5 KB (+ 59.13%) |
| Microsoft.Extensions.Configuration.Binder | 42.21 KB | 11.33 KB |  | 53.54 KB (+ 26.84%) | 64.87 KB (+ 53.68%) | 76.19 KB (+ 80.51%) |
| Microsoft.Extensions.Configuration.CommandLine | 32.15 KB | 6.41 KB |  | 38.56 KB (+ 19.92%) | 44.96 KB (+ 39.84%) | 51.37 KB (+ 59.76%) |
| Microsoft.Extensions.Configuration.EnvironmentVariables | 27.39 KB | 4.08 KB |  | 31.47 KB (+ 14.88%) | 35.54 KB (+ 29.75%) | 39.62 KB (+ 44.63%) |
| Microsoft.Extensions.Configuration.FileExtensions | 36.24 KB | 7.68 KB |  | 43.92 KB (+ 21.2%) | 51.6 KB (+ 42.39%) | 59.28 KB (+ 63.59%) |
| Microsoft.Extensions.Configuration.Ini | 32.47 KB | 6.34 KB |  | 38.81 KB (+ 19.53%) | 45.15 KB (+ 39.06%) | 51.49 KB (+ 58.59%) |
| Microsoft.Extensions.Configuration.Json | 43.13 KB | 7.38 KB |  | 50.5 KB (+ 17.1%) | 57.88 KB (+ 34.2%) | 65.26 KB (+ 51.31%) |
| Microsoft.Extensions.Configuration.UserSecrets | 34.34 KB | 6.58 KB |  | 40.92 KB (+ 19.15%) | 47.49 KB (+ 38.3%) | 54.07 KB (+ 57.45%) |
| Microsoft.Extensions.Configuration.Xml | 41.1 KB | 10.37 KB |  | 51.47 KB (+ 25.24%) | 61.84 KB (+ 50.48%) | 72.21 KB (+ 75.71%) |
| Microsoft.Extensions.DependencyInjection | 119.04 KB | 32.38 KB |  | 151.42 KB (+ 27.21%) | 183.8 KB (+ 54.41%) | 216.19 KB (+ 81.62%) |
| Microsoft.Extensions.DependencyInjection.Abstractions | 76.95 KB | 15.29 KB |  | 92.23 KB (+ 19.86%) | 107.52 KB (+ 39.73%) | 122.8 KB (+ 59.59%) |
| Microsoft.Extensions.DependencyModel | 83.39 KB | 30.42 KB |  | 113.81 KB (+ 36.48%) | 144.24 KB (+ 72.97%) | 174.66 KB (+ 109.45%) |
| Microsoft.Extensions.FileProviders.Abstractions | 31.09 KB | 4.98 KB |  | 36.07 KB (+ 16%) | 41.04 KB (+ 32%) | 46.02 KB (+ 48.01%) |
| Microsoft.Extensions.FileProviders.Composite | 27.35 KB | 3.64 KB |  | 30.99 KB (+ 13.32%) | 34.64 KB (+ 26.64%) | 38.28 KB (+ 39.95%) |
| Microsoft.Extensions.FileProviders.Physical | 55.55 KB | 15.54 KB |  | 71.1 KB (+ 27.98%) | 86.64 KB (+ 55.96%) | 102.18 KB (+ 83.93%) |
| Microsoft.Extensions.FileSystemGlobbing | 55.43 KB | 16.58 KB |  | 72.01 KB (+ 29.91%) | 88.58 KB (+ 59.82%) | 105.16 KB (+ 89.73%) |
| Microsoft.Extensions.Hosting | 85.88 KB | 20.65 KB |  | 106.54 KB (+ 24.05%) | 127.19 KB (+ 48.1%) | 147.85 KB (+ 72.15%) |
| Microsoft.Extensions.Hosting.Abstractions | 53.79 KB | 8.31 KB |  | 62.1 KB (+ 15.45%) | 70.41 KB (+ 30.9%) | 78.72 KB (+ 46.35%) |
| Microsoft.Extensions.Hosting.Systemd | 22.83 KB | 5.69 KB |  | 28.51 KB (+ 24.91%) | 34.2 KB (+ 49.82%) | 39.89 KB (+ 74.73%) |
| Microsoft.Extensions.Hosting.WindowsServices | 36.93 KB | 6.42 KB |  | 43.35 KB (+ 17.38%) | 49.76 KB (+ 34.76%) | 56.18 KB (+ 52.14%) |
| Microsoft.Extensions.Http | 75.5 KB | 25.7 KB |  | 101.19 KB (+ 34.04%) | 126.89 KB (+ 68.07%) | 152.58 KB (+ 102.11%) |
| Microsoft.Extensions.Logging | 74.54 KB | 16.51 KB |  | 91.06 KB (+ 22.15%) | 107.57 KB (+ 44.31%) | 124.09 KB (+ 66.46%) |
| Microsoft.Extensions.Logging.Configuration | 35.6 KB | 7.79 KB |  | 43.4 KB (+ 21.89%) | 51.19 KB (+ 43.79%) | 58.99 KB (+ 65.68%) |
| Microsoft.Extensions.Logging.Debug | 26.09 KB | 3.66 KB |  | 29.75 KB (+ 14.03%) | 33.41 KB (+ 28.06%) | 37.07 KB (+ 42.09%) |
| Microsoft.Extensions.Logging.EventLog | 33.5 KB | 7.01 KB |  | 40.51 KB (+ 20.93%) | 47.52 KB (+ 41.87%) | 54.54 KB (+ 62.8%) |
| Microsoft.Extensions.Logging.TraceSource | 28.77 KB | 4.76 KB |  | 33.53 KB (+ 16.53%) | 38.29 KB (+ 33.06%) | 43.04 KB (+ 49.59%) |
| Microsoft.Extensions.Options | 96.31 KB | 20.98 KB |  | 117.29 KB (+ 21.78%) | 138.27 KB (+ 43.56%) | 159.24 KB (+ 65.34%) |
| Microsoft.Extensions.Options.ConfigurationExtensions | 31.57 KB | 5.78 KB |  | 37.34 KB (+ 18.3%) | 43.12 KB (+ 36.6%) | 48.9 KB (+ 54.91%) |
| Microsoft.Extensions.Options.DataAnnotations | 34.22 KB | 4.68 KB |  | 38.89 KB (+ 13.66%) | 43.57 KB (+ 27.33%) | 48.25 KB (+ 40.99%) |
| Microsoft.Win32.Registry.AccessControl | 48.68 KB | 5.96 KB | 207 KB | 54.65 KB (+ 12.25%) | 60.61 KB (+ 24.49%) | 66.57 KB (+ 36.74%) |
| System.ComponentModel.Composition.Registration | 43.79 KB | 16.75 KB | 71 KB | 60.54 KB (+ 38.25%) | 77.29 KB (+ 76.49%) | 94.04 KB (+ 114.74%) |
| System.Composition.AttributedModel | 28.75 KB | 3.59 KB | 86 KB | 32.34 KB (+ 12.5%) | 35.93 KB (+ 24.99%) | 39.53 KB (+ 37.49%) |
| System.Composition.Convention | 61.05 KB | 18.9 KB | 144 KB | 79.95 KB (+ 30.96%) | 98.85 KB (+ 61.91%) | 117.75 KB (+ 92.87%) |
| System.Composition.Hosting | 67.24 KB | 21.56 KB | 154 KB | 88.8 KB (+ 32.07%) | 110.37 KB (+ 64.14%) | 131.93 KB (+ 96.21%) |
| System.Composition.Runtime | 36.53 KB | 7.34 KB | 99 KB | 43.87 KB (+ 20.09%) | 51.21 KB (+ 40.18%) | 58.55 KB (+ 60.27%) |
| System.Composition.TypedParts | 67.98 KB | 24.01 KB | 157 KB | 91.99 KB (+ 35.32%) | 116 KB (+ 70.63%) | 140.01 KB (+ 105.95%) |
| System.Data.OleDb | 379.89 KB | 179.01 KB | 385 KB | 558.91 KB (+ 47.12%) | 737.92 KB (+ 94.25%) | 916.93 KB (+ 141.37%) |
| System.IO.Packaging | 126.06 KB | 52.31 KB | 234 KB | 178.37 KB (+ 41.5%) | 230.67 KB (+ 82.99%) | 282.98 KB (+ 124.49%) |
| System.IO.Ports | 197.48 KB | 35.27 KB | 241 KB | 232.75 KB (+ 17.86%) | 268.02 KB (+ 35.72%) | 303.28 KB (+ 53.58%) |
| System.Memory.Data | 44.34 KB | 10.03 KB | 54 KB | 54.37 KB (+ 22.62%) | 64.4 KB (+ 45.24%) | 74.43 KB (+ 67.87%) |
| System.Net.Http.WinHttpHandler | 286.55 KB | 60.39 KB | 396 KB | 346.94 KB (+ 21.08%) | 407.33 KB (+ 42.15%) | 467.73 KB (+ 63.23%) |
| System.Numerics.Tensors | 68.52 KB | 19.29 KB | 93 KB | 87.81 KB (+ 28.14%) | 107.1 KB (+ 56.29%) | 126.38 KB (+ 84.43%) |
| System.Reflection.Context | 64 KB | 32.75 KB |  154 KB | 96.75 KB (+ 51.17%) | 129.5 KB (+ 102.33%) | 162.24 KB (+ 153.5%) |
| System.Resources.Extensions | 69.76 KB | 24.04 KB | 90 KB  | 93.8 KB (+ 34.46%) | 117.84 KB (+ 68.92%) | 141.87 KB (+ 103.38%) |
| System.Threading.AccessControl | 104.18 KB | 21.71 KB | 276 KB | 125.89 KB (+ 20.84%) | 147.61 KB (+ 41.69%) | 169.32 KB (+ 62.53%) |

**Comment by ViktorHofer** [comment]
> @ViktorHofer it seems like this and some of your other changes work together to realize an overall vision for our targeting strategy over the lifetime of .NET 6.0 onward. Do you think it makes sense to record this in a vision/design doc?

Probably would make sense but do people still read design docs in 10+ years from now (/sarcasm)? Usually I prefer to put as much detail as possible into commit messages, PRs, issues and docs as those are preserved over time. I already mentioned to couple folks that I would like to  present the versioning and packaging changes in a libraries teams specific talk. If there's still a need for a design document after that or if you explicitly want it to be written, I'm happy to do so.

**Comment by ericstj** [comment]
After 8.0 we assume the sizes are steady-state, right?  Did any of the size differences surprise you or suggest that we should do things to reduce the size (like move to runtime checks from cross compilation)?

Repo docs might serve the same purpose as design. Just hoping he can record what we do and why, and hopefully get a comprehensive view of everything that might be related so that we can be sure to deliver a complete story. Definitely the talk (and associated resources) could help.

**Comment by ViktorHofer** [comment]
> After 8.0 we assume the sizes are steady-state, right?

Correct. Every even major version, starting with 8.0, will carry along three NETCoreApp assets (if the project doesn't target rids and also exkluding ref assemblies) and every odd number two (LTS + Current).

The one that stands out is OleDb but not because of it targeting rids but because of the overall assembly and public api (xml) size.

We already know that there are a few OOBs that target many rids and are therefore quite large (i.e. Odbc) but those are already in main and aren't part of this specific discussion.

**Comment by ericstj** [comment]
The size increase looks acceptable to me and seems like the right tradeoff to make to achieve the overall simplification of the targeting of libraries.  I'd be interested to hear the opinion of others like @jkotas @davidfowl @stephentoub @eerhardt.

What are your thoughts about the testing gap?  How hard would that be to fill?

**Comment by eerhardt** [comment]
I support this change. I think it will make it easier for OOB libraries to use new features. And it will help with new contributors because we won't have to teach them how to add a new target to a library.

**Comment by ViktorHofer** [comment]
> And it will help with new contributors because we won't have to teach them how to add a new target to a library.

Which funnily enough shouldn't need to be taught as it should be straightforward but because of the the added complexity because of reference projects, "ProjectReference vs Reference" and runtime specific assets this unfortunately isn't the case.

**Comment by Anipik** [comment]
@ViktorHofer is it .NET 6 deliverable ?

**Comment by ViktorHofer** [comment]
It's not a deliverable in the sense that it must happen in .NET 6 or that customers are waiting for it but I really want to get this in before we fork.

**Comment by ViktorHofer** [comment]
The majority of libraries now have a net6.0 configuration and the remaining ones will get one in the main branch. Moving to 7.0.
