### ISSUE TITLE
Debugger corrupts vectors on breakpoint

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#54025]
Not seeing why this happens in C# in both .Net 5/6, but not .Net Core 3.1:

```c#
    var v = Vector256.Create(1.0f, 2.0f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f);      //<1, 2, 3, 4, 5, 6, 7, 8>
    v = Vector256.Create(1.0f);                                                    //<1, 1, 1, 1, 0, 0, 0, 7.17E-43>
    v = Vector256.Create(-1.0f, -2.0f, -3.0f, -4.0f, -5.0f, -6.0f, -7.0f, -8.0f);  //<-1, -2, -3, -4, -5, -6, -7, -8>
    v = Vector256.Create(1.0f);                                                    //<1, 1, 1, 1, 1, 1, 1, 1>
```
The upper bits of line 2 should have matched line 4. However, moving the code around makes it occur with line 1.

_Originally posted by @jeffk100 in https://github.com/dotnet/runtime/discussions/53967_

**Comment by sdmaclea** [comment]
@jeffk100 Exactly what platform are you seeing this on.

Is this amd64/x64, x86, arm64, or arm?
Is this Windows or Linux?

**Comment by jeffk100** [comment]
Yes, I am seeing this on Windows x64, the latest.

**Comment by hoyosjs** [comment]
PreBP:

```
E:\mocks\debuggerVector\Program.cs @ 11:
00007ff7`ba66fc6a c5fd10058e000000 vmovupd ymm0,ymmword ptr [debuggerVector!debuggerVector.Program.Main(System.String[])+0xf0 (00007ff7`ba66fd00)]
00007ff7`ba66fc72 c5fd114560      vmovupd ymmword ptr [rbp+60h],ymm0
00007ff7`ba66fc77 c5fd104560      vmovupd ymm0,ymmword ptr [rbp+60h]
00007ff7`ba66fc7c c5fd1185a0000000 vmovupd ymmword ptr [rbp+0A0h],ymm0
```

PostBP:
```asm
E:\mocks\debuggerVector\Program.cs @ 11:
00007ff7`ba68fc6a cc              int     3
00007ff7`ba68fc6b fd              std
00007ff7`ba68fc6c 10058e000000    adc     byte ptr [debuggerVector!debuggerVector.Program.Main(System.String[])+0xf0 (00007ff7`ba68fd00)],al
00007ff7`ba68fc72 c5fd114560      vmovupd ymmword ptr [rbp+60h],ymm0
00007ff7`ba68fc77 c5fd104560      vmovupd ymm0,ymmword ptr [rbp+60h]
00007ff7`ba68fc7c c5fd1185a0000000 vmovupd ymmword ptr [rbp+0A0h],ymm0
``` 

Looks like when we extract the instruction for the BP, we don't properly extract the instruction (or we don't extract and jump to the instruction after properly). cc: @sdmaclea

**Comment by sdmaclea** [comment]
The PostBP code looks OK to me.  I think this is just a simple Breakpoint.
```asm
00007ff7`ba68fc6a cc              int     3
```

The revised code is supposed to be in a patch buffer.

The real question is are we parsing and handling this correctly:
```asm
00007ff7`ba66fc6a c5fd10058e000000 vmovupd ymm0,ymmword ptr [debuggerVector!debuggerVector.Program.Main(System.String[])+0xf0 (00007ff7`ba66fd00)]
```

From the disassembly it look like it is a PC relative ptr.  It is possible/probable that wasn't handled correctly.

**Comment by sdmaclea** [comment]
The code to debug is here

https://github.com/dotnet/runtime/blob/d07f9111c57fab97aa135bebb2687471a8bfc5bf/src/coreclr/debug/ee/controller.cpp#L4378-L4422

For 
```asm
00007ff7`ba66fc6a c5fd10058e000000 vmovupd ymm0,ymmword ptr [debuggerVector!debuggerVector.Program.Main(System.String[])+0xf0 (00007ff7`ba66fd00)]
```

The instruction uses PC relative (RIP) 256-bit (ymmword) move.  So we need to fall into the `if (m_instrAttrib.m_dwOffsetToDisp != 0)` case.  It is possible we don't handle 256-bit data yet...

I manually looked at the `NativeWalker::DecodeInstructionForPatchSkip` code, it looks to me like it will decode properly.

@hoyosjs I am happy to help with this, but it seems like an ideal thing to knowledge transfer as I transition.

**Comment by sdmaclea** [comment]
Looks like `SharedPatchBypassBuffer::cbBufferBypass` is set to 16 bytes.  So it is too small for YMMWORD RIP moves.

**Comment by tommcdon** [comment]
Re-opening this issue as the original fix broke linux/mac debugging

**Comment by hoyosjs** [comment]
@jeffkl is this something that is blocking your inner loop? I have the change up against 6.0, does that work for you?
