### ISSUE TITLE
[Bug][Mono] MonoClassField attrs have not set correctly.

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#54051]
we embed mono, found that the MonoClassField attrs have not been set correctly.

```c#
class Test
{
     private int a = 1; // this field should have 
}
```

```c++
MonoClass* TestClass;
MonoClassField* afield = mono_class_get_field_from_name(TestClass, "a");

int flags = mono_field_get_flags(a);

the flags only have FIELD_ATTRIBUTE_PRIVATE value
```
the flags should have FIELD_ATTRIBUTE_HAS_DEFAULT or FIELD_ATTRIBUTE_LITERAL value?

how can I get default field value with embedder

**Comment by lambdageek** [comment]
@srxqds there's no bug here.

In your example there is not a constant with a default value.  There's an implicit constructor for `A::.ctor` that initialized the `a` field to `1`.

You need something like

```csharp
class A {
  const int c = 7;
}
```
to get something with the literal and has_default flags.

https://sharplab.io/#v2:C4LglgNgPgAgzAAhgJgQQQQbwLACgEEIAOATmAG4CGwApgmAHbAKUIC8CAjANx56HEyVWkk4A2ekwQAjdgmS98hfoQDGAewYBnZo2aq5CvAF88QA

**Comment by srxqds** [comment]
thank you
