### ISSUE TITLE
Multi-Targets library dll reasoning

### ISSUE THREAD

**Issue by ryancheung** [dotnet/runtime#54055]
### Description

I have a [multi-targets library](https://www.nuget.org/packages/FreeTypeSharp/2.0.0-preview3)  targets both `.net6.0` and `.net 6.0-android`. 
And I have a .`net6` Android app reference the library, but it reason the library to the `.net6.0` dll instead of the `.net6-android` dll!

The workaround I found:
Like the targets in [Maui](https://github.com/dotnet/maui/blob/main/src/Core/src/Core-net6.csproj#L3) project, it targets `.net6.0-android` and `.netstandard2.1`, but no `.net6.0`.
I change the `.net6.0` target of the library to `.netstandard2.1` , everythings works fine!

According the [design doc](https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md#compatibility-rules), the precedence rules for `.net6.0-android` is:

1. net6.0-android
2. net6.0
3. monoandroid12.0 - 1.0 (no warning)
4. net5.0
5. netcoreapp3.1 – 1.0
6. netstandard2.1 – 1.0
7. net4.x – 1.0 (NU1701 warning)

### Configuration

.NET 6 Preview 4
x86 in Android Emulator

### Other information

Sample project for reproducing the bug: [FreeTypeSharp.Android.Test](https://github.com/ryancheung/FreeTypeSharp/blob/main/FreeTypeSharp.Android.Test/FreeTypeSharp.Android.Test.csproj)

**Comment by ryancheung** [comment]
Workaround from  https://github.com/NuGet/Home/issues/10889

```
  <Target Name="_CollectPackageReferencesFixes" BeforeTargets="CollectPackageReferences">
    <PropertyGroup Condition="'$(PackageTargetFallback)' != '' and '$(AssetTargetFallback)' == ''">
      <AssetTargetFallback>$(PackageTargetFallback)</AssetTargetFallback>
      <PackageTargetFallback></PackageTargetFallback>
    </PropertyGroup>
  </Target>
```

**Comment by akoeplinger** [comment]
Thanks, like you found this depends on https://github.com/NuGet/Home/issues/10889 so there's nothing we can do here until these changes flow into the .NET SDK.
