### ISSUE TITLE
System.Threading.Channels - Is implementing a custom upper bound condition possible?

### ISSUE THREAD

**Issue by jstutson** [dotnet/runtime#54069]
Channels are great for their performance and async support.  However, I'm finding it extremely difficult to determine how I might implement my own bounded channel with a custom upper bound condition and whether this is strongly contradictory to the design of channels.

Rather than bound the collection by item count, I would like to restrict it by the sum of a property on the items in the channel.  In my case, this property is the size of the text in the object.  So, my goal is to limit the amount of text in memory at a time using the bounding of this channel.  Would this be a large departure from the locking mechanisms used to keep track of item count in channels?

As requested by this ticket: https://github.com/dotnet/runtime/issues/30049
The internals of Channel really aren't exposed.  So before I dive into understanding how Channels work underneath, I wonder if a channel bound of this nature has been considered, and whether it could be provided as an extension rather than me attempting to re-implement channels with a different boundary or wrapping it.

**Comment by stephentoub** [comment]
> Would this be a large departure from the locking mechanisms used to keep track of item count in channels?

For better or worse, the bounded channel implementation effectively locks around all operations, so it wouldn't significantly complicate locking.  However, there are other issues you'll likely hit and have to make decisions about.

You describe effectively wanting a `Func<T, int>` to determine the number of items each entry represents.  In those terms, today the system effectively implicitly uses a `t => 1` function, with every entry mapping to a single count against the bound.  Modifying some of the implementation to accomodate an alternate `Func<T, int>` would, for the most part, not be complicated.  Where it would become more challenging is around operations like `WaitForWriteAsync`, as now the implementation needs to be able to understand for a given waiter exactly how much room it requires, and the release of an element might enable only a subset of waiters to actually wake up.  Similarly, bounded channel today supports multiple modes for what to do in the face of a write when the channel is full.  It defaults to asynchronously blocking, but there are other options, like dropping the oldest element or the newest element.  In a world where everything has the same worth, that's simple: one in, one out.  In a world where everything may have different worths, there's now more policy to think about here.

I don't expect we'd add something like what you mention anytime soon, certainly not in .NET 6.  It also wouldn't be easily built on top of the existing internal components we use; you're really talking about an entirely new implementation.  I think your best bet would be to copy/paste the code for the existing bounded channel, and then modify it until it meets your needs.

Hope that helps.
