### ISSUE TITLE
Result from applying CultureInfo(nb-NO) to double.Tostring("N") differs between .net4 and .net5.0.7

### ISSUE THREAD

**Issue by sondr** [dotnet/runtime#54065]
When applying CultureInfo("nb-NO") to double.ToString it produces different results on .net 4 and .net 5.0.7.

Ex:
```
var n = 62.469;
var toTxt = n.ToString("n", new System.Globalization.CultureInfo("nb-NO"));
Console.WriteLine(toTxt);
```
Runtime version 4.0.30319.42000 produces: 
62,47

while runtime version 5.0.7 produces: 
62,469

(Tested on Windows 10 (19043.1052))

**Comment by stephentoub** [comment]
See https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#floating-point-formatting-and-parsing-behavior-changed and https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/. Thanks.

**Comment by danmoseley** [comment]
@sondr I will close this as it is intentional for standard compliance and correctness.

**Comment by tarekgh** [comment]
CC @tannergooding
