### ISSUE TITLE
JIT should optimize x % 2^k (==|!=) 0 to bitwise AND.

### ISSUE THREAD

**Issue by jfd16** [dotnet/runtime#54091]
In general, <code>x % 2<sup>k</sup></code> is not the same as <code>x & (2<sup>k</sup> - 1)</code> when `x` is signed (the latter is the Euclidean remainder, not the truncated remainder as required by the modulo operator) so the JIT compiler has to emit additional instructions to handle negative values of `x`.

However, this optimization is safe when the only use of the result is to check if it is equal (or not equal) to zero.

See example code and disassembly here:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACMxgYUYG8bGfmnjySRsAgQANowCSuAKIA3GADsAFAEtFGRggCUjALwA+LYwCkjUvr2MADAG5uvBs0HDRE6fKUBVRblUBzRRgAEzUNLV1DRmUAV3UMbQRTc0sbe2oAXyA=

**Comment by SingleAccretion** [comment]
This has been implemented in .NET 6 - see #45463.

E. g. here's the codegen for `IsEven` now:
```asm
test     cl, 1
sete     al
movzx    rax, al
ret      
```

**Comment by jfd16** [comment]
@SingleAccretion Thanks for letting me know, closing this.
