### ISSUE TITLE
Process.MainWindowHandle alway return IntPtr.Zero in .Net Core3.1

### ISSUE THREAD

**Issue by VShawn** [dotnet/runtime#54092]
```
                var app = System.Diagnostics.Process.Start("mspaint");
                var prsmwh = app.MainWindowHandle;
                while (prsmwh == IntPtr.Zero)
                {
                    prsmwh = app.MainWindowHandle;
                }
                Console.WriteLine($"Done");
```

this code above running on:

| Net framework 4.8 |  .Net core 3.1 | .Net 5 |
| ---- | ---- | ---- |
| Show "done" | Loop won't stop | Show "done" |

**Comment by KalleOlaviNiemitalo** [comment]
Fixing this would mean backporting <https://github.com/dotnet/runtime/issues/32690> / <https://github.com/dotnet/runtime/pull/32695> to .NET Core 3.1.

**Comment by adamsitnik** [comment]
> Fixing this would mean backporting #32690 / #32695 to .NET Core 3.1.

@danmoseley does this meet the backporting to 3.1 bar?

**Comment by danmoseley** [comment]
We have a high bar for backporting - particularly to 3.1 as our customers expect it to be as stable as possible. @VShawn can you upgrade to 5.0?

The bar would be something like: substantial/widespread impact and doesn't have a good workaround.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/runtime/pull/32695#issuecomment-594945845> mentions a workaround.

**Comment by danmoseley** [comment]
Right. @VShawn I will close this - thanks for the report - please let us know if you can neither upgrade nor work around this.

**Comment by VShawn** [comment]
thx for your works, I've upgraded to 5.0
