### ISSUE TITLE
Explicit GC Transitions

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#54106]
For functions where the actual native code is very fast the transition can be a major source of overhead, in these cases having the ability to manually add transitions would be very useful (real-world example: Vulkan command recording, `vkCmd*` methods are very cheap, and many are executed in a row). Something similar may be possible to do using
```cs
[UnmanagedCallersOnly]
private static void TransitionMethod()
{
    call
    call
    call
}
```
and taking an unmanaged function pointer to `TransitionMethod` as @tannergooding pointed out, but it's rather ugly.

This should be relatively simple to do, the only problem is that JIT needs to recognize this and not emit nested transitions, but this would also be needed for the above workaround.

Also note that while `SuppressGCTransition` somewhat helps with these scenarios, it's not ideal. Another use-case where `SuppressGCTransition` doesn't help at all is having two larger native calls right after another (for example, calling `Kernel32.WideCharToMultiByte` to marshal a `string` and then calling another native function) in these cases the transition doesn't weigh in as much, but having fewer transitions is still desirable.

**Comment by HurricanKai** [comment]
In regards to JIT recognizing this pattern see https://github.com/dotnet/runtime/issues/54107

**Comment by jkotas** [comment]
> For functions where the actual native code is very fast the transition can be a major source of overhead, in these cases having the ability to manually add transitions would be very useful (real-world example:

I do not think we would want to compilicate the public surface for these sort of optimizations. This would make sense to do as a JIT optimization - make the JIT recognize certain patterns where the transitions can be batched or omitted.

**Comment by Perksey** [comment]
Sure, but the JIT will have to account for a lot of things and in some cases the developer may have more information than the JIT is able to safely deduce (with tight considerations on GC SLAs and whatnot). I'd say such optimization would be in the same vein as explicitly telling the JIT to aggressively inline, for example - it's good to be able to specify this sort of thing for an extra bit of granularity.

even just a simple
```cs
GCBarrier.ToPreemptive();

vk.CmdQuickCall();
vk.CmdSomeOtherQuickCall();
vk.CmdALotOfOtherCalls();
vk.CmdALotOfOtherCalls();
vk.CmdALotOfOtherCalls();
vk.CmdMaybeByNowTheJitHasDecidedTheseAreTooManyCallsButWeKnowItsNotBecauseWeKnowTheseAreQuickButTheJitDoesntNecessarilyKnowThis();

GCBarrier.ToCooperative();
```

**Comment by jkotas** [comment]
>  safely deduce (with tight considerations on GC SLAs and whatnot

Defining the rules for how to use these sort of API safely, without tieing our hands in how to evolve the runtime, is not easy.

`CmdMaybeByNowTheJitHasDecidedTheseAreTooManyCallsButWeKnowItsNotBecauseWeKnowTheseAreQuickButTheJitDoesntNecessarilyKnowThis` would be a corner case of a corner case. Solving this corner case of a corner case is not worth the high complexity.

**Comment by JulieLeeMSFT** [comment]
@HurricanKai if you are ok with @jkotas's answer, we will close this issue and discuss/handle GC transition in #54107.

**Comment by HurricanKai** [comment]
I think #54107 should handle most of these scenarios fine. I think when that is resolved evaluating whether anything else is worth discussing will be possible. Thank you!
