### ISSUE TITLE
JIT EH write thru crash

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#54100]
The JIT crashes while compiling the following program:
```csharp
// Generated by Fuzzlyn v1.1 on 2021-06-12 00:42:21
// Seed: 11991615925769861084
// Reduced from 166.4 KiB to 0.8 KiB in 00:10:53
// Crashes the runtime
public class Program
{
    static ushort[][] s_23 = new ushort[][]{new ushort[]{0}};
    static short s_32;
    static short s_33;
    static int s_45;
    public static void Main()
    {
        ushort[] vr4 = s_23[0];
        ushort vr6 = M45();
    }

    static ushort M45()
    {
        short var0;
        try
        {
            var0 = s_32;
        }
        finally
        {
            var0 = s_33;
            int var1 = s_45;
            ulong vr8 = default(ulong);
            var0 = (short)((sbyte)vr8 - var0);
            try
            {
                M46();
            }
            finally
            {
                M46();
            }

            System.Console.WriteLine(var1);
        }

        return 0;
    }

    static ulong M46()
    {
        return default(ulong);
    }
}
```

There is no non-empty block [here](https://github.com/dotnet/runtime/blob/cc6d3147ff1f10d2ee2b0751cf799fc4cc1abbae/src/coreclr/jit/lsrabuild.cpp#L1921). With `COMPlus_EnableEHWriteThru=0` things seems to go alright.
cc @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
This is a rare scenario where we have an empty `try` clause and so we do not find a non-empty block to insert zero-inits for. The solution would be to insert a scratch block with `GT_NOP` tree and use that to insert zero-init ref position. Thanks Bruce for helping me understand about the scratch block.

**Comment by BruceForstall** [comment]
> We could re-run the empty try removal after optimizing, but I suspect it will almost never find newly empty trys.

I suggested that in an off-line conversation with Kunal, but it seems better to just make LSRA more robust (in the cheapest/simplest way possible) to the "empty block" possibility.
