### ISSUE TITLE
What's the correct target for obfuscating single-file publish?

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#54109]
`<Target Name="AfterCompile"/>`?
`<Target Name="BeforePublish"/>`?

Try a lot, but not works.

**Comment by Fabi** [comment]
> `<Target Name="AfterCompile"/>`?
> `<Target Name="BeforePublish"/>`?
> 
> Try a lot, but not works.

Check the integration of eazfuscator.

**Comment by GF-Huang** [comment]
> > `<Target Name="AfterCompile"/>`?
> > `<Target Name="BeforePublish"/>`?
> > Try a lot, but not works.
> 
> Check the integration of eazfuscator.

Give a link please.

**Comment by Fabi** [comment]
> > > `<Target Name="AfterCompile"/>`?
> > > `<Target Name="BeforePublish"/>`?
> > > Try a lot, but not works.
> > 
> > 
> > Check the integration of eazfuscator.
> 
> Give a link please.

https://www.nuget.org/packages/Gapotchenko.Eazfuscator.NET

**Comment by GF-Huang** [comment]
It is impractical, which contains a large number of targets files, and it takes a lot of time to understand it.

**Comment by Fabi** [comment]
> It is impractical, which contains a large number of targets files, and it takes a lot of time to understand it.

take the correct target file

**Comment by vitek-karas** [comment]
We're introducing an extension point in the SDK for operations like this (primarily for signing, but it should work for obfuscation as well) [Design](https://github.com/dotnet/designs/blob/main/accepted/2021/before_bundle_build_hook.md), [PR](https://github.com/dotnet/sdk/pull/18794).

**Comment by agocke** [comment]
Closing as resolved
