### ISSUE TITLE
[mono][llvm] finalizearray.dll fails with LLVM AOT + JIT

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#54113]
`/GC/Features/Finalizer/finalizeother/finalizearray/finalizearray.dll` will fail to pass when built with LLVM AOT:

```
$ MONO_ENV_OPTIONS="--aot=llvm,llvm-path=$MONO_PREFIX" $CORE_ROOT/corerun finalizearray.dll
```

and then executed with LLVM JIT:

```
$ MONO_ENV_OPTIONS="--llvm" $CORE_ROOT/corerun finalizearray.dll
Test for Finalize() for array of objects failed!
```

**Comment by fanyang-mono** [comment]
Moving to 8.0.0

**Comment by BrzVlad** [comment]
Known limitation of mono GC. Already disabled in https://github.com/dotnet/runtime/pull/58719
