### ISSUE TITLE
DiagnosticListener.AllListeners is not thread-safe

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#54111]
[DiagnosticListener.AllListeners](https://github.com/dotnet/runtime/blob/c95aa3f48aa591dca870ee00c31c3d8bdc740b5a/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs#L35-L49) is intended to be thread-safe (by default all static .NET APIs are), however it uses an unsafe initialization pattern:
```C#
                if (s_allListenerObservable == null)
                {
                    s_allListenerObservable = new AllListenerObservable();
                }
                return s_allListenerObservable;
```

Multiple threads executing that code in parallel could each observe s_allListenerObservable = null, then allocate separate instances. Each of those threads might then return the instance they allocated resulting in the AllListeners singleton reporting different values per-thread. The expected behavior is that regardless of thread AllListeners should always return the same object.

This can be fixed by changing the code to look like this and marking the variable volatile:
```C#
                if (s_allListenerObservable == null)
                {
                    Interlocked.CompareExchange(ref s_allListenerObservable, new AllListenerObservable(), null);
                }
                return s_allListenerObservable;
```

**Comment by davidfowl** [comment]
Fix in 6.0 backport to 5.x and 3.1.x?

**Comment by tommcdon** [comment]
@josalem

**Comment by noahfalk** [comment]
Generally we wouldn't backport when there is an easy workaround and we don't anticipate many people would hit the bug. For workaround you can stick a lock around the call to AllListeners. Given the buggy code has existed ~10 years with this being the only reported hit + DiagnosticListener being a relatively uncommon API I also wouldn't anticipate many people would hit it.

While I have no strong objection to backporting, given what I know so far it doesn't seem merited.

**Comment by davidfowl** [comment]
So the milestone should be 6.x?

**Comment by tommcdon** [comment]
> So the milestone should be 6.x?

Agreed. Moved to 6.0. After fixing in 6.0 we can evaluate if it should be backported to 5.0 or 3.1.

**Comment by noahfalk** [comment]
oh yeah, sorry about that. Setting it to 5.0.x was mistake, I intended 6.
