### ISSUE TITLE
HttpListenerRequest.RemoteEndPoint potentially can be null

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#54116]
#41189 marks [Interop.HttpApi.GetRemoteEndPoint](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Windows/HttpApi/Interop.HttpApi.cs#L837) as returning nullable however [HttpListenerRequest.RemoteEndPoint](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.HttpListener/src/System/Net/Windows/HttpListenerRequest.Windows.cs#L291) is not marked as nullable.

```cs
        internal static unsafe IPEndPoint? GetRemoteEndPoint(IntPtr memoryBlob, IntPtr originalAddress)
```

```cs
        public IPEndPoint RemoteEndPoint
        {
            get
            {
                if (_remoteEndPoint == null)
                {
                    _remoteEndPoint = Interop.HttpApi.GetRemoteEndPoint(RequestBuffer, OriginalBlobAddress);
                }
                if (NetEventSource.Log.IsEnabled()) NetEventSource.Info(this, "_remoteEndPoint" + _remoteEndPoint);
                return _remoteEndPoint!;
            }
        }
```

**Comment by stephentoub** [comment]
Have you observed an actual problem here or is your content based just on code inspection?

GetRemoteEndPoint always returns non-null for IPv4 and IPv6.

**Comment by NN---** [comment]
The problem is more theoretical.
If the method is expected to work only with IPv4 and IPv6 , it should throw and not return null.

**Comment by stephentoub** [comment]
The method is an internal implementation detail.

**Comment by NN---** [comment]
Ok. It just can in some corner case return null.

**Comment by stephentoub** [comment]
> It just can in some corner case return 

From the public API? Can you share a repro? If that's actually the case, the annotation should be fixed.
