### ISSUE TITLE
arm64 ci pipelines are failing 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#54125]
The first job with the issues: https://dev.azure.com/dnceng/public/_build/results?buildId=1182203&view=results (6 days ago)

The errors look like:
```
##[error].packages\microsoft.dotnet.helix.sdk\6.0.0-beta.21304.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(78,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item profiler.transitions in job 65c02f43-d291-4aad-a09f-a931fffefb58 has failed.
```
and the error log shows:
```
{"Message":"NotFound","ActivityId":"2506c1745f27b94cafca06bb1790c3e4"}
```

link https://github.com/dotnet/runtime/issues/702

looks like an infrastructure issue to me.

**Comment by ericstj** [comment]
This might be same issue as https://github.com/dotnet/runtime/issues/54948.  I can't check the logs to see if they have the same error code as they've been deleted.

**Comment by hoyosjs** [comment]
Closing this one in favor of #54948 as the other one seems to have more actionable logs.
