### ISSUE TITLE
Crossgen code removal tracking issue

### ISSUE THREAD

**Issue by mangod9** [dotnet/runtime#54129]
The intent for this is to track changes as code for crossgen is removed. Epic for crossgen replacement: #43653.

First set of changes:
1. Remove crossgen from build: https://github.com/dotnet/runtime/pull/53458.
2. Remove crossgen related test scripts: https://github.com/dotnet/runtime/pull/54348
3. Remove more crossgen related files from building: https://github.com/dotnet/runtime/pull/54458

We can add more as cleanup progresses.

**Comment by jkoritzinsky** [comment]
@mangod9 does the existence of this tracking issue mean that the crossgen.exe removal was clean upstack and we can start removing more crossgen code?

**Comment by mangod9** [comment]
Not quite. It was created based on the ask here: https://github.com/dotnet/runtime/pull/53458#issuecomment-859399268. Notice the milestone is .net 7 :). Will update this issue once we get clearance across repos, mostly post preview6 release at the earliest.

**Comment by mangod9** [comment]
For additional context we continue to find cases which need fixing as the removal change propagates across repos. Eg: 
https://github.com/dotnet/sdk/pull/18197/commits/f89440cf115bd8c6ec01baa4351612eda4ec8210
https://github.com/dotnet/installer/pull/10888

**Comment by jkoritzinsky** [comment]
That sounds good! Just keep this thread up to date for when code removal can commence. I know the whole interop team is looking forward to helping with the cleanup.

**Comment by AaronRobinsonMSFT** [comment]
@mangod9 Is this issue the same as https://github.com/dotnet/runtime/issues/53007?

**Comment by mangod9** [comment]
yeah guess we can roll this into #53007 if removing `CROSSGEN_COMPILE` would complete the cleanup for crossgen.
