### ISSUE TITLE
[Perf] Regressions in Integer Formatting

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54166]
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_Int32

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Int32.ToString(value%3a%202147483647).html>) | 24.70 ns | 34.44 ns | 1.39 | 0.21 | | |
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Int32.TryFormat(value%3a%202147483647).html>) | 19.39 ns | 21.12 ns | 1.09 | 0.17 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Int32_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Int32_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Int32.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Int32*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_Int32.ToString(value: 2147483647)

```log

```
#### System.Tests.Perf_Int32.TryFormat(value: 2147483647)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_UInt64

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt64.TryFormat(value%3a%2012345).html>) | 10.78 ns | 12.11 ns | 1.12 | 0.13 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt64_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt64.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_UInt64*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_UInt64.TryFormat(value: 12345)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a](https://github.com/dotnet/runtime/commit/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a)
Compare | [8fb2eb53f75971ce492f14bebb93ed7a236bcd6e](https://github.com/dotnet/runtime/commit/8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4c7f4ee74d7a9e5bcc73b552dd020df02b039c8a...8fb2eb53f75971ce492f14bebb93ed7a236bcd6e)

### Regressions in System.Tests.Perf_Version

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryFormatL - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_Version.TryFormatL.html>) | 96.02 ns | 103.50 ns | 1.08 | 0.15 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Version_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_Version.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Version*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-09b0e867-d918-493d-8f94-1ed57e7c008ca6480ee76424784ac/d17f1bb6-cf7d-43e9-82f4-d7b958031de9.zip?sv=2019-07-07&se=2021-06-17T14%3A13%3A59Z&sr=c&sp=rl&sig=4y%2FfMT1VANdqOiV7YklImmCgyUNsLeW1vgMV5YQWdCo%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9a10712e-55d4-4710-8cc4-a7764f27676722b004842d841ee99/e20c8586-25be-495a-9117-95dd22f83a6e.zip?sv=2019-07-07&se=2021-06-17T20%3A36%3A56Z&sr=c&sp=rl&sig=QKoTBO7ix54nB3Ag0uJir2PLiqWfCxIxMffTt5tLT4w%3D>)

#### System.Tests.Perf_Version.TryFormatL

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [28e63279342bd2f6ca43442d864f487613a53bc9](https://github.com/dotnet/runtime/commit/28e63279342bd2f6ca43442d864f487613a53bc9)
Compare | [d49bcbe0441f5c954cddcbe28a222eb34917bcaf](https://github.com/dotnet/runtime/commit/d49bcbe0441f5c954cddcbe28a222eb34917bcaf)
Diff | [Diff](https://github.com/dotnet/runtime/compare/28e63279342bd2f6ca43442d864f487613a53bc9...d49bcbe0441f5c954cddcbe28a222eb34917bcaf)

### Regressions in System.Tests.Perf_UInt32

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt32.ToString(value%3a%204294967295).html>) | 22.92 ns | 25.28 ns | 1.10 | 0.24 | | |
[TryFormat - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Tests.Perf_UInt32.TryFormat(value%3a%204294967295).html>) | 17.54 ns | 20.77 ns | 1.18 | 0.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt32_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt32_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Tests.Perf_UInt32.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_UInt32*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-f2d20920-0bc0-4bb9-9d1d-8d34eb6d47c6c216c972f62465292/99063571-1fe1-4096-8569-59b2e86938a4.zip?sv=2019-07-07&se=2021-06-18T18%3A28%3A15Z&sr=c&sp=rl&sig=CuaIYn6sp0EYxmgqo1u%2FF5V2IjlpjtZgzufOov%2B2mm0%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-f7b88df2-2a36-4dbd-a714-925cb640fe3c2d7e9db63214e9fbe/bc83e467-c725-44b8-a0ae-9c7b252f25ee.zip?sv=2019-07-07&se=2021-06-19T01%3A07%3A40Z&sr=c&sp=rl&sig=jgPCNxUQFidzmxgWf%2BJL4S1pK8dKXjvRl2T99A2SlQw%3D>)

#### System.Tests.Perf_UInt32.ToString(value: 4294967295)

```log

```
#### System.Tests.Perf_UInt32.TryFormat(value: 4294967295)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmoseley** [comment]
@tannergooding looking at the list of changes, https://github.com/dotnet/runtime/commit/fdbef6ca18d902d78299dec50fe91fbbd16a94c9 popped out, but Dragon doesn't do much actual division does it?

**Comment by tannergooding** [comment]
Dragon is for floating-point. Integer formatting frequently divides by 10: https://source.dot.net/#System.Private.CoreLib/Number.Formatting.cs,c66436177df5dc9b

**Comment by stephentoub** [comment]
cc: @pentp

**Comment by pentp** [comment]
I don't have an arm64 machine to do perf tests, so I'm trying to get some assembly diffs, but I can't get `jit-dasm` to work with anything I try. From a clean repo I built the following stuff:
```
.\build.cmd Clr.Runtime+Clr.CoreLib+Clr.NativeCoreLib -a x64 -c Release
.\build.cmd Clr.Runtime+Clr.CoreLib+Clr.NativeCoreLib -a arm64 -c Release
.\build.cmd Clr.AllJits -a x64 -c Checked
```
I then tried to get dasm output:
```
jit-dasm-pmi.exe --altjit windows.x64.Checked\clrjit_win_arm64_x64.dll --corerun windows.x64.Release\corerun.exe windows.arm64.Release\IL\System.Private.CoreLib.dll -v
Copying default jit: C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release ==> C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\-backup
JIT DASM PMI failed: Access to the path 'C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release' is denied.
Restoring default jit: C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\-backup ==> C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\-backup'.
```

I also tried with -j option and it complains about the file being in use (by itself probably, nothing else has it open):
```
jit-dasm-pmi.exe -j windows.x64.Release\clrjit.dll --altjit windows.x64.Checked\clrjit_win_arm64_x64.dll --corerun windows.x64.Release\corerun.exe windows.arm64.Release\IL\System.Private.CoreLib.dll -v
Copying default jit: C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit.dll ==> C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit-backup.dll
Copying in the test jit: C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit.dll ==> C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit.dll
JIT DASM PMI failed: The process cannot access the file 'C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit.dll' because it is being used by another process.
```

I then tried to manually copy the clrjit.dll files and run with --nocopy:
```
jit-dasm-pmi.exe -j windows.x64.Release\clrjit.dll --altjit windows.x64.Checked\clrjit_win_arm64_x64.dll --corerun windows.x64.Release\corerun.exe windows.arm64.Release\IL\System.Private.CoreLib.dll -v --nocopy
...
Running: C:\dev\ref-runtime\artifacts\bin\coreclr\windows.x64.Release\corerun.exe C:\dev\jitutils\bin\pmi.dll DRIVEALL-QUIET windows.arm64.Release\IL\System.Private.CoreLib.dll
...
Managed assembly: C:\dev\jitutils\bin\pmi.dll
Arguments (2): DRIVEALL-QUIET windows.arm64.Release\IL\System.Private.CoreLib.dll
BEGIN: coreclr_initialize failed - Error: 0x80004005
END: coreclr_initialize failed - Error: 0x80004005
1 errors compiling set.
```

I've clearly misunderstood how these utilities work. Can they even be used to get arm64 asm dumps on win-x64 or is there a better/easier way?

**Comment by danmoseley** [comment]
@dotnet/jit-contrib could someone help @pentp here?

I've updated the area to codegen as I can't see a relevant change on the libraries side, let me know if that's not right.

**Comment by danmoseley** [comment]
Untriaging for codegen team to do.

**Comment by JulieLeeMSFT** [comment]
CC @AndyAyersMS PTAL.

**Comment by AndyAyersMS** [comment]
Test history implicate #52893. In particular the change was merged, reverted, and then re-merged, which matches the up-down-up seen here:

![newplot (66)](https://user-images.githubusercontent.com/10121823/129118237-dabefb28-eb04-4d24-b277-44a0ee8d4b6b.png)

As for how to get diffs, it should be something like:
```
;; builds as you do above, in both "ref" and "diff" repos

jit-diff diff --base --base_root <path to ref repo> --core_root <path to release core_root in either repo> --altjit clrjit_win_arm64_x64.dll -t X --pmi

jit-diff diff --diff --diff_root <path to diff repo> --core_root <path to release core_root in either repo> --altjit clrjit_win_arm64_x64.dll -t X --pmi

jit-analyze --base X\base --diff X\diff
```

**Comment by JulieLeeMSFT** [comment]
Thanks @AndyAyersMS.
@pentp then what is the plan? Are we going to revert #52893?

**Comment by AndyAyersMS** [comment]
#52893 clearly improves the cost of division on x64, so at this point I'd say there is something unexpected going on that is arm64 specific and we should try and figure out what that is.

EG Here's the windows x64 results for that same test over the same time interval.

![newplot (67)](https://user-images.githubusercontent.com/10121823/129123333-3058baa9-9657-4c46-8371-a425808f808f.png)

@pentp if you can't get diffs using the above let me know and I'll actually go try it myself to make sure I didn't leave out anything important.

**Comment by AndyAyersMS** [comment]
Marking as 6.0 at least until we've better understood what's going on.

**Comment by tannergooding** [comment]
I wonder if its partially due to certain operations, such as integer division, being significantly more expensive on x86/x64 (as you only have `div` which computes the remainder as well).

On A64, the benefits of avoiding `div` are lessened and some of the algorithms that avoid `div` might expect you can have things like `lea` instead.

**Comment by EgorBo** [comment]
@AndyAyersMS can it also be PGO related? https://github.com/dotnet/runtime/commit/dc7598e509023489d911ac3b643e2f426490d310

![image](https://user-images.githubusercontent.com/523221/129240023-dbf4549b-bf56-4bbc-af2b-a7a814f4f556.png)

**Comment by pentp** [comment]
So I managed to finally generate a diff: https://www.diffchecker.com/Rr7cRI2V
I suspect the slowdown comes from using `mul x,x,x` instead of `umull x, w, w`?

**Comment by AndyAyersMS** [comment]
I think these are running on Surface Pro X machines, which are A76 (big).

@echesakov can you ask the Arm folks to take a look and see if they have any ideas?

**Comment by echesakovMSFT** [comment]
@TamarChristinaArm Do you think you or someone on your team would be able to help us with the issue?

**Comment by TamarChristinaArm** [comment]
> @TamarChristinaArm Do you think you or someone on your team would be able to help us with the issue?

Sure thing!, taking a look.

**Comment by TamarChristinaArm** [comment]
> So I managed to finally generate a diff: https://www.diffchecker.com/Rr7cRI2V
> I suspect the slowdown comes from using `mul Xd, Xn, Xm` instead of `umull Xd, Wn, Wm`?

I think this is correct culprid, the loop has a long dependency chain off the value out of the `mul/umull` with little independent instructions so it's bound by these two and `64-bit mul` has twice the latency of `umull`.

> Edit: ARM software optimization guides seem to indicate that `mul` and `umull` have identical latencies/throughput. `umulh` is more expensive, but it's only used once and it should still be faster than a bunch of `lsr/sub/add` instructions...

`64-bit mul` has a latency of `4(3)` and `umull` has `2(1)` on Cortex-A76.  Were you perhaps comparing the AArch32 instructions? Note that on AArch64 `mul` and `umull` aren't real instructions but are architectural aliases for `madd` and `umaddl` respectively so you need to look at the latencies for those.

The `mul` seems to be unneeded though, both inputs are 32-bits so you should be able to just use `umull` there as before.

**Comment by TamarChristinaArm** [comment]
As a side note, while looking at the diff I noticed some other general improvements that could be made in the future:

```
sxtw    x3, w6	
lsl     x3, x3, #1	
add     x2, x2, x3
```

can become 

```
add     x2, x2, w6, sxtw, #1
```

and 

```
lsl     w3, w3, #1
sub     w3, w0, w3
```

can become

```
sub     w3, w0, w3, lsl 1
```

lastly

```
sub     x2, x2, #2
strh    w1, [x2]
```

can become

```
strh    w1, [x2, #-2]!
```

and probably want to move the constant out of the loop.
