### ISSUE TITLE
[Perf] Regressions in System.Collections.ContainsFalse<String>

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54167]
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [478571ca82dedc4f07f6a176709224adf3ee367a](https://github.com/dotnet/runtime/commit/478571ca82dedc4f07f6a176709224adf3ee367a)
Compare | [d81ad044fa6830f5f31f6b6e8224ebf66a3c298c](https://github.com/dotnet/runtime/commit/d81ad044fa6830f5f31f6b6e8224ebf66a3c298c)
Diff | [Diff](https://github.com/dotnet/runtime/compare/478571ca82dedc4f07f6a176709224adf3ee367a...d81ad044fa6830f5f31f6b6e8224ebf66a3c298c)

### Regressions in System.Collections.ContainsFalse&lt;String&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[LinkedList - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Collections.ContainsFalse(String).LinkedList(Size%3a%20512).html>) | 1.47 ms | 1.60 ms | 1.09 | 0.26 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Collections.ContainsFalse(String)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_25_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Collections.ContainsFalse(String).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.ContainsFalse&lt;String&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-952fd767-ffbc-44ec-a020-8aaf03a6ac0e47e08438f9e46c08d/972fa73a-edb0-49c6-87c0-680a62996b8e.zip?sv=2019-07-07&se=2021-06-19T03%3A23%3A02Z&sr=c&sp=rl&sig=Df40gTXVc3hnycEZ0R5eQVNItGwMjc3DFqD2iic9Tf0%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0988b720-d32a-4733-82f4-126b7aef3cdcab1d91486c7454cb7/b3a5ad10-130a-40d0-8fde-7519707acf35.zip?sv=2019-07-07&se=2021-06-19T16%3A55%3A27Z&sr=c&sp=rl&sig=ixL7fd0HRtcg9GUnPtbwnelrNUOhlAUDbyIVa4VzuTY%3D>)

#### System.Collections.ContainsFalse&lt;String&gt;.LinkedList(Size: 512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmoseley** [comment]
It appears to have returned to norm (or slightly better)

![image](https://user-images.githubusercontent.com/6385855/127078974-7a7b12bb-766f-47e9-88d6-e2204be9011e.png)

@agocke I don't see any plausible change in the diff. I also notice that it is a somewhat fuzzy onset and a fuzzy departure (assuming it is 'fixed'). Is this potentially pgo related?

**Comment by eiriktsarpalis** [comment]
Seems to have regressed again in the past few weeks with recent runs being seemingly bimodal.
![image](https://user-images.githubusercontent.com/2813363/129440875-0b88bffe-342b-4726-8aab-6f2fa1605c72.png)

**Comment by AndyAyersMS** [comment]
>  ... potentially pgo related?

LIkely so. There's no persistent regression. Some parts of the jit are overly sensitive to small details in PGO. We're not going to be able to fix this for .NET 6.

![newplot (69)](https://user-images.githubusercontent.com/10121823/129452812-bfae3271-459e-45f0-8fdc-28d16fd3c7cf.png)

**Comment by JulieLeeMSFT** [comment]
Moving to .NET 7.
