### ISSUE TITLE
RegionInfo NativeName Unknown

### ISSUE THREAD

**Issue by GioviQ** [dotnet/runtime#54178]
.NET 5.0.7

Running my web app from Visual Studio, I have

new RegionInfo("it-IT").NativeName -> "Italia"
new RegionInfo("it-DE").NativeName -> "Germania"

My deployed web app on Windows Server 2019 (en-US + it-IT language) with .NET 5.0.7 Hosting bundle

new RegionInfo("it-IT").NativeName -> "Italia"
new RegionInfo("it-DE").NativeName -> "Unknown Region (DE)"

What is missing on Windows Server? 
Is .NET 5.0.7 Hosting bundle installer not enough?

**Comment by michaelgsharp** [comment]
Are you using x86 or x64?

**Comment by tarekgh** [comment]
@GioviQ .NET depends on the underlying OS to get the globalization functionality. When running on Windows 10 client we use the ICU library. but on Windows Server 2019 the ICU library is not there and we just use the NLS APIs. That is why you are seeing this difference. 

If the size of your app is not a concern, you may opt-in to use the [ICU app-local](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-XFOT1Y13nKinE4ZvZfDFxw&epi=a1LgFw09t88-XFOT1Y13nKinE4ZvZfDFxw&irgwc=1&OCID=AID2000142_aff_7806_1243925&tduid=%28ir__mrdukhopi0kfqxeykk0sohzifv2xurnreuxvqyey00%29%287806%29%281243925%29%28a1LgFw09t88-XFOT1Y13nKinE4ZvZfDFxw%29%28%29&irclickid=_mrdukhopi0kfqxeykk0sohzifv2xurnreuxvqyey00#app-local-icu) feature to get your app carry the version of the ICU when running on Windows Server 2019. The ICU is a NuGet package which you can get it by adding the following to your csproj

```Xml
<ItemGroup>
  <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2" />
</ItemGroup>
```

I am closing the issue, but feel free to reply back with any question.

**Comment by GioviQ** [comment]
Target runtime of my blazor app is "Portable".

I am administrator of Windows Server, so how to install ICU library at OS level?

**Comment by tarekgh** [comment]
> I am administrator of Windows Server, so how to install ICU library at OS level?

Windows Server 2019 already have some version of ICU but .NET don't load for some technical reasons. There is no official way to install another/different ICU library there. 

@lewing do you know a way they can install ICU with the portable Blazor app when installing on Windows Server 2019

**Comment by lewing** [comment]
@tarekgh wasm should pull in its own ICU for blazor apps so I think this is just a result of NativeName being stripped from the data, but more generally it would be possible to package newer icu versions for old versions of windows if we wanted to.
