### ISSUE TITLE
[Perf] Regression in WriteJson String Serialization

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54174]
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [e68d2a3252256b40ca282f52125039f96c0ddee9](https://github.com/dotnet/runtime/commit/e68d2a3252256b40ca282f52125039f96c0ddee9)
Compare | [253a25325895307a48602c7c192f01c81f700f42](https://github.com/dotnet/runtime/commit/253a25325895307a48602c7c192f01c81f700f42)
Diff | [Diff](https://github.com/dotnet/runtime/compare/e68d2a3252256b40ca282f52125039f96c0ddee9...253a25325895307a48602c7c192f01c81f700f42)

### Regressions in System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SerializeToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Text.Json.Serialization.Tests.WriteJson(Int32).SerializeToString.html>) | 275.55 ns | 292.64 ns | 1.06 | 0.16 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-116154b7-ed77-44f4-9cc1-b13de10446604c173d4e1084f09b5/95339e41-a4fa-4683-aeb1-6386fbf7bb6a.zip?sv=2019-07-07&se=2021-07-02T18%3A43%3A23Z&sr=c&sp=rl&sig=MlCTU5RSp7N0EkcrYz0U3r05vhqpBjJGWQbCpw744AU%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-21c55486-147a-4930-9b11-284b3f5cf95d309fe49a5304cd9b8/741d9473-1e8f-478d-93cc-f93907606f7a.zip?sv=2019-07-07&se=2021-07-03T04%3A59%3A34Z&sr=c&sp=rl&sig=UBNGqu%2B76cjWks4XWEu5AegncJiHK2nj4%2Fwcqa37q%2Bw%3D>)

#### System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;.SerializeToString

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by ericstj** [comment]
@layomia looks like this was regressed by https://github.com/dotnet/runtime/commit/6e5f722a9dab49f9626ea95326ef6e74129621ca.  However it seems this benchmark is now doing better than the baseline:
![image](https://user-images.githubusercontent.com/8918108/127070980-2f9cb6f4-fb91-4704-bbbe-585691d8e43a.png)

**Comment by layomia** [comment]
@ericstj yup, closing per https://github.com/dotnet/runtime/issues/54171#issuecomment-887694703.
