### ISSUE TITLE
Can I list all available cultures/languages from localization resources?

### ISSUE THREAD

**Issue by myshon** [dotnet/runtime#54175]
In my .NET Core application, I keep localization data as EmbeddedResource restext files

```
MyLocalization.restext
MyLocalization.pl.restext
MyLocalization.de.restext
MyLocalization.fr.restext
```
I would like to list dynamically all available files or their languages (in the case above: en - default, pl, de, fr). When I try to list resources by

`var files = executingAssembly.GetManifestResourceNames();`

I receive only one item `MyLocalization.resources`. It is possible to list dynamically available languages/cultures from EmbeddedResource files?

.NET Core SDK: 5.0.102

**Comment by tarekgh** [comment]
@myshon 

One idea is to get the ResourceManager object used to access the resources, then enumerate all cultures with trying to get the ResourceSet for each culture. Something like:

```C#
    ResourceManager rm = new ResourceManager("MyLocalization", executingAssembly); // You need to pass the right parameter in your case.

    foreach (CultureInfo ci in CultureInfo.GetCultures(CultureTypes.AllCultures))
    {
        if (rm.GetResourceSet(ci, true, false) != null)
        {
            Console.WriteLine($"{rm.BaseName} Resource Language: {ci.Name}");
        }
    }
```

The other idea is to enumerate all folders under your executing assembly folder and search for the satellite assemblies. Something like:


```C#
    foreach (string folder in Directory.EnumerateDirectories(Path.GetDirectoryName(executingAssembly.Location)))
    {
        foreach (string fileName in Directory.EnumerateFiles(folder, executingAssembly.GetName().Name + ".resources.dll"))
        {
            Console.WriteLine($"{Path.GetFileName(folder)} .. {fileName}");
        }
    }
```

**Comment by krwq** [comment]
@myshon did @tarekgh's suggestion work for you?
