### ISSUE TITLE
[Perf] Regression in Span Indexing

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54172]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [c3126d0b0e3038c1bcb9a6ec4200841be3de03ba](https://github.com/dotnet/runtime/commit/c3126d0b0e3038c1bcb9a6ec4200841be3de03ba)
Compare | [e0671e7ec6696449b61d61d19d3dd802b49a4fb3](https://github.com/dotnet/runtime/commit/e0671e7ec6696449b61d61d19d3dd802b49a4fb3)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3126d0b0e3038c1bcb9a6ec4200841be3de03ba...e0671e7ec6696449b61d61d19d3dd802b49a4fb3)

### Regressions in System.Memory.Span&lt;Byte&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[IndexOfAnyFourValues - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Memory.Span(Byte).IndexOfAnyFourValues(Size%3a%20512).html>) | 42.03 ns | 620.97 ns | 14.78 | 0.51 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Memory.Span(Byte)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Memory.Span(Byte).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Memory.Span&lt;Byte&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-766f7f3d-8638-44b4-8b9a-6b357f815d8344334405fa1484b86/d4eb32e6-81c9-4272-9f1e-a0a70f084a0d.zip?sv=2019-07-07&se=2021-07-04T01%3A58%3A50Z&sr=c&sp=rl&sig=LVE6FsI2wlhBb1lwYrGXS%2Fs4ZBYru%2FqkK4e4zy1N5QM%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-632a3ed0-3737-4316-9b17-084e77470770173d45320b541d6b6/9c920ee2-4bc6-45d2-bd17-1a2683291a15.zip?sv=2019-07-07&se=2021-07-04T15%3A33%3A22Z&sr=c&sp=rl&sig=nEDSIiEuGX5qnOgTZjng7I56lkOgixSq4mDfQf72%2FYw%3D>)

#### System.Memory.Span&lt;Byte&gt;.IndexOfAnyFourValues(Size: 512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [c3126d0b0e3038c1bcb9a6ec4200841be3de03ba](https://github.com/dotnet/runtime/commit/c3126d0b0e3038c1bcb9a6ec4200841be3de03ba)
Compare | [e0671e7ec6696449b61d61d19d3dd802b49a4fb3](https://github.com/dotnet/runtime/commit/e0671e7ec6696449b61d61d19d3dd802b49a4fb3)
Diff | [Diff](https://github.com/dotnet/runtime/compare/c3126d0b0e3038c1bcb9a6ec4200841be3de03ba...e0671e7ec6696449b61d61d19d3dd802b49a4fb3)

### Regressions in System.Memory.Span&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[IndexOfAnyFourValues - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Memory.Span(Int32).IndexOfAnyFourValues(Size%3a%20512).html>) | 286.54 ns | 623.94 ns | 2.18 | 0.01 | | |
[BinarySearch - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Memory.Span(Int32).BinarySearch(Size%3a%20512).html>) | 15.75 ns | 21.30 ns | 1.35 | 0.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Memory.Span(Int32)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Memory.Span(Int32)_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_08_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Memory.Span(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Memory.Span&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-766f7f3d-8638-44b4-8b9a-6b357f815d8344334405fa1484b86/d4eb32e6-81c9-4272-9f1e-a0a70f084a0d.zip?sv=2019-07-07&se=2021-07-04T01%3A58%3A50Z&sr=c&sp=rl&sig=LVE6FsI2wlhBb1lwYrGXS%2Fs4ZBYru%2FqkK4e4zy1N5QM%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-632a3ed0-3737-4316-9b17-084e77470770173d45320b541d6b6/9c920ee2-4bc6-45d2-bd17-1a2683291a15.zip?sv=2019-07-07&se=2021-07-04T15%3A33%3A22Z&sr=c&sp=rl&sig=nEDSIiEuGX5qnOgTZjng7I56lkOgixSq4mDfQf72%2FYw%3D>)

#### System.Memory.Span&lt;Int32&gt;.IndexOfAnyFourValues(Size: 512)

```log

```
#### System.Memory.Span&lt;Int32&gt;.BinarySearch(Size: 512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by GrabYourPitchforks** [comment]
Regression in `IndexOfAnyFourValues` is expected and is a consequence of https://github.com/dotnet/runtime/pull/53652.

I don't see any recent changes to `BinarySearch`'s source code. Perhaps codegen changed recently?

**Comment by DrewScoggins** [comment]
Looking at the diff, for BinarySearch it happens over a PGO update, so my guess is that is the most likely cause. @AndyAyersMS already has an issue open for that, so I will close this one as the other issue is by design.
