### ISSUE TITLE
[System.Text.Json] [Polymorphic serialization] Serialization does not take care of properties with base class where derived objects are passed

### ISSUE THREAD

**Issue by RamjotSingh** [dotnet/runtime#54188]
System.Text.Json does not support polymorphic serialization of objects properly if the property is a of base type but the object assigned during runtime is a derived class. The following example demonstrates the issues

```cs
class Program
    {
        static void Main(string[] args)
        {
            ModelClass modelClass = new ModelClass
            {
                Prop = new DerivedClass
                {
                    BaseProp = "Base",
                    DerivedProp = "Derived",
                },
            };

            string serializedString = JsonSerializer.Serialize<object>(modelClass);
        }
    }

    public class ModelClass
    {
        public BaseClass Prop { get; set; }
    }

    public class BaseClass
    {
        public string BaseProp { get; set; }
    }

    public class DerivedClass : BaseClass
    {
        public string DerivedProp { get; set; }
    }
```

The json we get is
```json
{"Prop":{"BaseProp":"Base"}}
```
Which is missing `DerivedProp` from the payload. This is already taking into account the fix specified in https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism (it doesn't really matter here since the top level object is not a derivative).

It is important to note that this issue has relation to https://github.com/dotnet/runtime/issues/29937 but is not the same as that since the issue talks about top level object being a derivate.

**Comment by eiriktsarpalis** [comment]
> It is important to note that this issue has relation to #29937 but is not the same as that since the issue talks about top level object being a derivate.

That's not quite correct, #29937 will be addressing polymorphic serialization for both root-level and nested values, so it would cover your example as well.

I'm going to close this issue, feel free to continue the conversation in #29937.
