### ISSUE TITLE
[System.Text.Json] Support constructor parameters in JsonConverter attribute

### ISSUE THREAD

**Issue by RamjotSingh** [dotnet/runtime#54187]
## Background and Motivation

JsonConverter attribute allows customizing the json serialization and deserialization process. However, today there is no way to specify constructor arguments that the converter themselves take.

Best example of this is JsonStringEnumConverter which has following constructor

```cs
public JsonStringEnumConverter(JsonNamingPolicy? namingPolicy = null, bool allowIntegerValues = true)
```

It is pretty common to specify that you want enum members to be camel cased. However, using JsonConveter attribute it is not possible to do this, unless you create another converter which sets that by default.

Newtonsoft.Json supports the following attribute constructor allowing parameters to be specified.

```cs
public JsonConverterAttribute(Type converterType, params object[] converterParameters)
```

## Proposed API

```cs
public JsonConverterAttribute(Type converterType, params object[] converterParameters)
```

## Usage Examples

```cs
[JsonConverter(typeof(JsonStringEnumConverter), JsonNamingPolicy.CamelCase, true)]
```

**Comment by FilipToth** [comment]
Sounds good. Before I do any thinking about whether this fits in with the `System.Text.Json` APIs. There’s a question I have:
What would get thrown if I pass in say: `typeof(int)`? Or would we just use the default type?

I would maybe consider making that an enum.

**Comment by eiriktsarpalis** [comment]
It would have been easier to address this particular case if `JsonStringEnumConverter` had not been marked sealed, but I would say that [using a JsonConverterFactory](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#sample-factory-pattern-converter) is the recommended approach for working around this issue in the general case:
```csharp
public class MyStringEnumConverterFactory : JsonConverterFactory
{
    private readonly JsonStringEnumConverter _converter;

    public MyStringEnumConverterFactory() : this(JsonNamingPolicy.CamelCase, allowIntegerValues: true)
    { }

    public MyStringEnumConverterFactory(JsonNamingPolicy namingPolicy, bool allowIntegerValues)
    {
        _converter = new JsonStringEnumConverter(namingPolicy, allowIntegerValues);
    }

    public override bool CanConvert(Type typeToConvert) => _converter.CanConvert(typeToConvert);
    public override JsonConverter? CreateConverter(Type typeToConvert, JsonSerializerOptions options) => _converter.CreateConverter(typeToConvert, options);
}
```

**Comment by FilipToth** [comment]
@eiriktsarpalis 
Just to clarify, why did we seal the   `JsonStringEnumConverter` type? I get that there's not really a reason why would we have any other class inherit from the `JsonStringEnumConverter` type, but is that the only reason for sealing it? Or is there anything glaringly obvious I'm missing? Would there be any risks associated with making that class not sealed?

**Comment by eiriktsarpalis** [comment]
> Just to clarify, why did we seal the JsonStringEnumConverter type? I get that there's not really a reason why would we have any other class inherit from the JsonStringEnumConverter type, but is that the only reason for sealing it?

I don't have historical context on that decision, perhaps @layomia or @steveharter might know. I don't think we should be sealing any public converter types, because it blocks scenaria like the one we're discussing here.

> Would there be any risks associated with making that class not sealed?

I don't think so. Technically you would be breaking reflection code such as `typeof(JsonStringEnumConverter).IsSealed` but that's the only issue I can think of. @bartonjs or @stephentoub might know if there is precedent here.

**Comment by stephentoub** [comment]
Unsealing a type previously shipped as sealed is not considered to be a breaking change.  Sealing a type previously shipped as unsealed is a breaking change.

My preference is always to err on the side of sealing until scenarios present themselves for which derivation is important, at which point effort needs to be invested in making sure the type was fully designed for being derived from, having one or more methods overridden, etc.  (Note there are several performance benefits to types being sealed as well.)

**Comment by eiriktsarpalis** [comment]
FWIW performance should not be a substantial consideration in the case of converter factories, since they are only being used during the converter generation phase.

**Comment by RamjotSingh** [comment]
@eiriktsarpalis That is precisely what I had done. Here is my implementation at the moment. But it is not ideal to have this unnecessary code in every codebase.

```cs
    /// <summary>
    /// Since SystemTextJson at the moment does not support specifying constructor arguments to converters, this converter just
    /// forces <see cref="JsonStringEnumConverter"/> to use camel casing.
    /// </summary>
    public class JsonStringCamelTextEnumConverter : JsonConverterFactory
    {
        private readonly JsonStringEnumConverter jsonStringEnumConverter;

        /// <summary>
        /// Initializes a new instance of the <see cref="JsonStringCamelTextEnumConverter"/> class.
        /// </summary>
        public JsonStringCamelTextEnumConverter()
        {
            this.jsonStringEnumConverter = new JsonStringEnumConverter(
                JsonNamingPolicy.CamelCase,
                allowIntegerValues: true);
        }

        /// <summary>
        /// Determines if the current converter can convert the type.
        /// </summary>
        /// <param name="typeToConvert">Type to convert.</param>
        /// <returns>True if the type can be converted, false otherwise.</returns>
        public override bool CanConvert(Type typeToConvert)
        {
            return this.jsonStringEnumConverter.CanConvert(typeToConvert);
        }

        /// <summary>
        /// Creates a converter to perform conversion.
        /// </summary>
        /// <param name="typeToConvert">Type to convert.</param>
        /// <param name="options">Serializer options to use.</param>
        /// <returns>Json converter instance.</returns>
        public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
        {
            return this.jsonStringEnumConverter.CreateConverter(typeToConvert, options);
        }
    }
```

**Comment by FilipToth** [comment]
> I don't have historical context on that decision, perhaps @layomia or @steveharter might know. I don't think we should be sealing any public converter types, because it blocks scenaria like the one we're discussing here.

Ok, thanks, I see.

I tried searching for `typeof(JsonStringEnumConverter).IsSealed`, didn't find any references in the runtime (My vscode has been acting up with large codebases lately), and please note that I didn't search for variations eg.
```cs
var type = typeof(JsonStringEnumConverter);
if (type.IsSealed)
    ...
```
I am not sure how the review team would feel about unsealing the type especially for a minor change like this where we already have a workaround as mentioned by @eiriktsarpalis. 

I was also thinking of maybe not just adding an attribute, but maybe just adding an overload?

**Comment by eiriktsarpalis** [comment]
I'd support making such a change, pending feedback from @steveharter and @layomia .

**Comment by ericstj** [comment]
Here was the previous request: https://github.com/dotnet/runtime/issues/30486

**Comment by eiriktsarpalis** [comment]
I think we could still do this, the existing workaround is needlessly cumbersome.

**Comment by FilipToth** [comment]
@ericstj That proposal is simply to unseal the `JsonConverter` type, this proposal is different.

Plus, I disagree with the decision of @layomia in #30486, we should not just reject a proposal when a workaround is available. In the end, that is how the dotnet platform grows.

again, there's really no downside to unsealing the type, it isn't considered a breaking change. There shouldn't be any performance issues with this. If it solves a problem, I don't see a reason for not approving this.

**Comment by RamjotSingh** [comment]
Folks I think we kind of are limiting ourselves to one specific converter. Unsealing will solve the problem for one specific case, but the fact I still need to write a converter is still wrong.

If we instead allow constuctor params to be passed in JsonConverter attribute, we enable JsonStringEnum + every other converter without needing to derive from them. The converter can then stay sealed and people can pass the naming strategy when calling it using attribute.

So I think unsealing is like treating symptoms while leaving the disease as is.

**Comment by eiriktsarpalis** [comment]
> Folks I think we kind of are limiting ourselves to one specific converter. Unsealing will solve the problem for one specific case, but the fact I still need to write a converter is still wrong.

I would not support having the attribute accept constructor parameters. It is not type safe and it restricts you to parameter types that support literal values. Using converter inheritance to achieve the same goal OTOH is type safe, can be used with arbitrary parameters and is a fairly understood pattern. 

I would recommend closing this issue and unsealing any public converters to unblock users.

**Comment by stephentoub** [comment]
> I would recommend closing this issue and unsealing any public converters to unblock users

Unsealing types, especially ones with virtual members,  needs to be accompanied by reviewing the type for extensibility.  This particular case would need additional changes beyond just unsealing.

**Comment by eiriktsarpalis** [comment]
> This particular case of JsonStringEnumConverter would need additional changes beyond just unsealing.

I'm not sure what you mean, what additional changes would be required in this case?

**Comment by stephentoub** [comment]
For example,  it has unsealed virtual methods that suggest you can configure the behavior,  but the actual converter factory it's creating is internal. And unless the derived ctor also stores the arguments,  even if it were public it wouldn't have access to the private members storing that  options data to know what to pass in. Unsealed types with virtuals need to be carefully thought through for extensibility. If we're going to unseal the type, we need to go through the exercise of how the type can/will be used.  If we're not going to do that,  at a minimum we should seal all virtual methods at the same time the type is unsealed.

**Comment by eiriktsarpalis** [comment]
Ah, good point. While overriding methods might be considered a valid option for certain use cases (for instance constrain `CanConvert` to a specific subset of enums), it exposes the type to the usual caveats of authoring converter factories (mismatch between types supported in `CanConvert` and the factory method itself). Given that this concern is orthogonal to the problem being discussed here, I say we should play it safe and seal all virtual members. I suppose we can reconsider depending on future feedback.

**Comment by layomia** [comment]
`JsonConstructorAttribute` is unsealed and exposes a virtual [`CreateConverter`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonconverterattribute.createconverter?view=net-5.0) method, which allows folks to pass state to converters through ctor parameters. Here's an example of using the API in our [tests](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/CustomConverterTests/CustomConverterTests.Attribute.cs#L10-L31). I don't think we need the proposed API since we have existing API that satisfies the motivating scenario.

**Comment by RamjotSingh** [comment]
@layomia It doesnt solve the ask. The ask is to specify parameters through constructor. Something that still can't be supported hence I think this API is still needed.

**Comment by ericstj** [comment]
I think in @layomia's example you can still specify parameters through constructor, you just write a different attribute name and have strongly typed parameters.

So it would look like
```C#
[JsonStringEnumConverter(JsonNamingPolicy.CamelCase, true)]
```

With corresponding attribute:
```C#
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Class, AllowMultiple = false)]
private class JsonStringEnumConverterAttribute : JsonConverterAttribute
{
    private readonly JsonNamingPolicy _namingPolicy;
    private readonly bool _allowIntegerValues;
    public JsonStringEnumConverterAttribute (JsonNamingPolicy namingPolicy, bool allowIntegerValues)
    {
        _namingPolicy = namingPolicy;
       _allowIntegerValues = allowIntegerValues;
    }

    public override JsonConverter CreateConverter(Type typeToConvert) =>new JsonStringEnumConverter(_namingPolicy, _allowIntegerValues );
}
```

@dotnet/area-system-text-json would it make sense for us to add attributes like this for our converters which have constructor parameters?

**Comment by eiriktsarpalis** [comment]
It actually is possible to create a general-purpose attribute that supports arguments:
```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

JsonSerializer.Serialize((MyEnum)42); // throws exception, as expected

[JsonConverterWithArgs(typeof(JsonStringEnumConverter), null, false)]
public enum MyEnum { A = 0, B = 1, C = 2 }

public class JsonConverterWithArgsAttribute : JsonConverterAttribute
{
    public JsonConverterWithArgsAttribute(Type converterType, params object?[] converterArguments)
    {
        ConverterType = converterType;
        ConverterArguments = converterArguments;
    }

    // CreateConverter method is only called if base.ConverterType is null 
    // so store the type parameter in a new property in the derived attribute
    // https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L278
    public new Type ConverterType { get; }
    public object?[] ConverterArguments { get; }

    public override JsonConverter? CreateConverter(Type _)
    {
        return (JsonConverter)Activator.CreateInstance(ConverterType, ConverterArguments)!;
    }
}
```
For the case of `StringEnumConverter` however it's not particularly useful: `JsonNamingPolicy` is a class and thus the only valid argument that can be declared at the attribute level is `null`.

**Comment by ericstj** [comment]
> actually is possible to create a general-purpose attribute

Sure it's possible, but is it really useful?  Do folks really want to initialize converters through loosely typed API?

> For the case of StringEnumConverter however it's not particularly useful: JsonNamingPolicy is a class and thus the only valid argument that can be declared at the attribute level is null.

That's a good point and is a problem with the initial proposal as well.  I guess to make that scenario work the attribute would need to take a `JsonKnownNamingPolicy`.

**Comment by eiriktsarpalis** [comment]
In light of the above, I feel we should close this issue for the following reasons:

* It's not type-safe.
* Doesn't work with non-constant parameters.
* There exists a workaround for users that need it.
