### ISSUE TITLE
Android crash on API 21 with "method setServerNames (Ljava/util/List;)V was not found"

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#54182]
### Description

I am having crashes on startup on Android API 21 (5.0) with an error:

> F/DOTNET  ( 3231): /__w/1/s/src/libraries/Native/Unix/System.Security.Cryptography.Native.Android/pal_jni.c:573 (GetMethod): method setServerNames (Ljava/util/List;)V was not found

### Configuration

OS: Android 5.0 / API 21
.NET: 6.0.100-preview.5.21302.13
Android SDK: 30.0.100-preview.5.28

### Regression?

Not sure.

### Other information

[adb-logcat-com.microsoft.maui.devicetests-com.microsoft.maui.devicetests.TestInstrumentation.log](https://github.com/dotnet/runtime/files/6651398/adb-logcat-com.microsoft.maui.devicetests-com.microsoft.maui.devicetests.TestInstrumentation.log)

**Comment by filipnavara** [comment]
I keep forgetting what is the minimum supported Android version. Apparently this API was added in API level 24 / Android 7.0. There may be some alternatives available on downlevel versions (https://stackoverflow.com/questions/38682872/what-is-the-alternative-of-sslparameter-setservernames-in-android-sdk-level-23).

cc @steveisok

**Comment by steveisok** [comment]
API level 21 is the min.  We'll look into it.
