### ISSUE TITLE
[iOS] BundleResource in targets is not working

### ISSUE THREAD

**Issue by ryancheung** [dotnet/runtime#54198]
### Description

BundleResource populated in target files(e.g: *.targets from nuget package) is not working. There's no resource copied to result .app directory.

A minimal csproj file show the issue:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-ios</TargetFramework>
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <!--This is not working-->
  <Target
    Name="IncludeContent"
    BeforeTargets="PrepareForBuild">

    <ItemGroup>
      <BundleResource Include="Hello.txt" />
    </ItemGroup>
  </Target>

  <!--This is working
    <ItemGroup>
      <BundleResource Include="Hello.txt" />
    </ItemGroup>
  -->
</Project>
```

The full reproducing project: https://github.com/ryancheung/iOSApp1

### Configuration

.NET 6 Preview 4
macOS 11 BigSur
x64 ios emulator

### Regression?

Yes! It previously works in old Xamarin.iOS project.

**Comment by SamMonoRT** [comment]
@marek-safar @dalexsoto : The above comment seems like move to xamarin-macios moved.
