### ISSUE TITLE
Question: are APIs in System.Security.Cryptography.Cng and System.Security.Cryptography.Pkcs available in Mono?

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#54195]
Hi, we've called APIs in those two packages in net5.0 code path and they worked correctly.
I'm wondering if the APIs work if calling them in Mono from non-Windows platforms? 
I think that is,
1. Does the full framework code path of those APIs in the two packages depend on any windows platform specific APIs?
2. If all APIs are supported on Mono, may I know if all tests are add for Mono?
Thanks!

**Comment by vcsjones** [comment]
> Does the full framework code path of those APIs in the two packages

` System.Security.Cryptography.Cng` is entirely Windows-specific and depend on Win32 APIs. Namespaces and types with "Cng" in their name are implemented using Windows's [CNG APIs].

`System.Security.Cryptography.Pkcs` has some dependencies on Windows' specific APIs but much of it has cross-platform capabilities. Can you describe more about what APIs you are leveraging in this package / namespace?

[CNG APIs]: https://docs.microsoft.com/en-us/windows/win32/seccng/about-cng

**Comment by bartonjs** [comment]
The questions seem to be answered and there hasn't been activity in a long while, closing.
