### ISSUE TITLE
Serialize strings that look like dates changes data 

### ISSUE THREAD

**Issue by paul1956** [dotnet/runtime#54197]
### Description

I am serializing a dictionary of strings one of the strings has the value "2021-05-22T01:06:22.076-00:00" After serialization I get "5/22/2021 1:06:22 AM-00:00" 
```
Dim RecentData As New Dictionary(Of String, String)
RecentData.Add("Sample", "2021-05-22T01:06:22.076-00:00")
Dim options As New JsonSerializerOptions With {
                .WriteIndented = True
                }
Dim jsonString As String =  JsonSerializer.Serialize(RecentData, options)
```
I really want the strings left alone is this a bug or if not how can I stop this translation? 

### Configuration

Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Regression?

don't know

* Do you know of any workarounds?
no - I hope someone can provide one.

**Comment by FilipToth** [comment]
That is correct behavior, it correctly serializes the JSON and converts the time to a valid `DateTime`. I did notice you used the European date/time format, and the output was in the US date/time format. Is that the problem?

> If that is the problem

I think you can just convert it back to the European date/time. I am not aware of whether you can pass `CultureInfo` into the serializer. Although, that would be something to look into as an API suggestion if that doesn’t exist, maybe.

**Comment by huoyaoyuan** [comment]
I can't reproduce your behavior if pasting your code into `Main`. I've also changed my `CurrentCulture` to `en-us` but nothing changed. You may provide a more detailed repro that can be observed in `Main`.

**Comment by eiriktsarpalis** [comment]
Likewise, I can't reproduce the issue with the provided code.

**Comment by paul1956** [comment]
Filip Toth replied with below
```
"That is correct behavior, it correctly serializes the JSON and converts the time to a valid DateTime. I did notice you used the European date/time format, and the output was in the US date/time format. Is that the problem? **YES**
If that is the problem
I think you can just convert it back to the European date/time. I am not aware of whether you can pass CultureInfo into the serializer.  Although, that would be something to look into as an API suggestion if that doesn’t exist, maybe.
```
Yes that is the issue except I am not passing in a DateTime I am passing in an arbitrary string that happens to look like a European Date/Time. It could be a European Date or a US Date or some random string of characters.

I assume this has something to do with my Windows edition/settings (us-EN) so it may not reproduce on other versions of Windows.

**Comment by eiriktsarpalis** [comment]
> Yes that is the issue except I am not passing in a DateTime I am passing in an arbitrary string that happens to look like a European Date/Time. It could be a European Date or a US Date or some random string of characters.

System.Text.Json does not dispatch to converters depending on the shape of the serialized string, cf. [StringConverter.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/StringConverter.cs).

Could you please confirm that the snippet shared in the OP does indeed reproduce the error as reported? As @huoyaoyuan pointed out earlier the code will in fact throw a `NullReferenceException` since no dictionary is being initialized.

**Comment by paul1956** [comment]
It was a small snippet the full application is at https://github.com/paul1956/CareLink and it has test data since you will not be able to log in.  You can load sample data under Options, save it (document/Carelink.json) and then compare the two files.

**Comment by paul1956** [comment]
I am going to close and do more research and create a small repo. Thanks.

**Comment by paul1956** [comment]
@eiriktsarpalis @huoyaoyuan Sorry for the confusion, the code I was working with has a post processors for Dates that was doing the Euro to US date conversion after the serialization and before returning the result to my code when I remove it everything works as expected.
