### ISSUE TITLE
Test failure System.IO.Packaging.Tests.Tests.VeryLargePart

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54208]
Run: [runtime-libraries-coreclr outerloop 20210614.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1185840&view=ms.vss-test-web.build-test-results-tab&runId=35643852&resultId=102031&paneView=debug)

Failed test:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open

- System.IO.Packaging.Tests.Tests.VeryLargePart

```
**Error message:**
```
Assert.Equal() Failure
Expected: 826571
Actual:   1048576


Stack trace
   at System.IO.Packaging.Tests.Tests.VeryLargePart() in /_/src/libraries/System.IO.Packaging/tests/Tests.cs:line 3828
```

**Comment by adamsitnik** [comment]
@VincentBu have it failed just once?

I've taken a brief look and: the code from `System.IO.Packaging` was not modified for a long time, but the test itself creates a 6 GB file:

https://github.com/dotnet/runtime/blob/ec2712962d0117dfdca7738ae20f0ce3483eab67/src/libraries/System.IO.Packaging/tests/Tests.cs#L3794

My guess would be that we have run out of space on this particular machine.

**Comment by VincentBu** [comment]
> @VincentBu have it failed just once?
> 
> I've taken a brief look and: the code from `System.IO.Packaging` was not modified for a long time, but the test itself creates a 6 GB file:
> 
> https://github.com/dotnet/runtime/blob/ec2712962d0117dfdca7738ae20f0ce3483eab67/src/libraries/System.IO.Packaging/tests/Tests.cs#L3794
> 
> My guess would be that we have run out of space on this particular machine.

Yes, this test just failed this time ,I can't fined historical failures on Kusto query.

**Comment by stephentoub** [comment]
I expect this is actually a real failure due to a latent test bug.  The highlighted line assumes that the Read call will always return exactly what was asked for:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.IO.Packaging/tests/Tests.cs#L3826-L3828
That's not guaranteed.
