### ISSUE TITLE
Couldn't use Debug.Writeline in asp.net 5 Blazor webassembly

### ISSUE THREAD

**Issue by BrandoZhangTest** [dotnet/runtime#54213]
### Describe the bug
Couldn't use Debug.Writeline in asp.net 5 Blazor webassembly, but we could use it in asp.net core 3.1

### To Reproduce
In the balzor default project, modify the IncrementCount to use  Debug.WriteLine("aaaa");
```

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;

        Debug.WriteLine("aaaa");
    }
}

```
 

### Further technical details
- ASP.NET Core 5 
- 5.0.5
- Visual Studio 2019

**Comment by carlblanchard** [comment]
Is this going to be fixed in a .net 5 patch or go straight to .net 6?

**Comment by thaystg** [comment]
This is working on .net 6.
It's being printed as a `console.warning`.
