### ISSUE TITLE
StreamWriter causes bus error on Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by backfromexile** [dotnet/runtime#54214]
### Description

I have a long running process that sporadically writes text into a file.  
I noticed that my program often crashes with a bus error while writing to the file.  

I had two different configurations.  
The first one was a `StreamWriter` that I opened at the start and closed (disposed) when the program exited.
Here I noticed the mentioned bus errors regularly but I couldn't find a pattern.
Then I switched to the second configuration which used `File.AppendAllLines` instead of an always opened `StreamWriter`. The bus errors appeared noticably less often but are still there.

I am fairly sure that the bus errors are caused by the `StreamWriter` because the error always occured when the process tried to write to the file. Simply having the `StreamWriter` open did not cause any bus errors as far as I tested.

As a note, I manually called the garbage collector using `GC.Collect` regularly after the program writes to the file if that may cause the issues.

### Configuration
* Which version of .NET is the code running on?
.NET 5.0.101 (published as self-contained single file for linux_x64 + trim unused assemblies)
* What OS and version, and what distro if applicable?
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-124-generic x86_64)
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
I didn't test that much but I had no issues on Windows 10

### Regression?
First time I encountered that issue, so probably yes.

### Other information
I have NOT tried running a simple program only using a `StreamWriter` with a long running loop. However, I am 99.9% sure it's the `StreamWriter`

**Comment by stephentoub** [comment]
Can you please share a repro?

**Comment by backfromexile** [comment]
> Can you please share a repro?
I will try to create a small repro that causes this error. However, the issue usually appeared after a few days so it might take some time

**Comment by jkotas** [comment]
If it is hard to repro, we may be able to find the root cause of the problem from coredump:

- Set there environment variables https://github.com/dotnet/runtime/issues/45557#issuecomment-738547930
- Reproduce the crash and share coredump for the bus error

**Comment by backfromexile** [comment]
> If it is hard to repro, we may be able to find the root cause of the problem from coredump:
> 
> * Set there environment variables [#45557 (comment)](https://github.com/dotnet/runtime/issues/45557#issuecomment-738547930)
> * Reproduce the crash and share coredump for the bus error

I will look into it and try to get a core dump. I am not the owner of the system and do not have root privileges and I haven't found any coredump files of older runs so far.

**Comment by adamsitnik** [comment]
> I will look into it and try to get a core dump.

@backfromexile were you able to get a repro or a core dump? Do you have a stack trace of the exception?
