### ISSUE TITLE
S.S.C.OpenSsl doesn't have UnsupportedOSPlatform annotation at assembly level on IosSimulator

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#54212]
Not sure whether it's an issue - when building S.S.C.OpenSsl for IosSimulator, the build produces a PNSE-assembly but the assembly metadata has `[assembly: SupportedOSPlatform("iOS")]` annotation even though it's marked as unsupported at csproj level using `<UnsupportedOSPlatforms>windows;browser;android;ios;tvos</UnsupportedOSPlatforms>` (see https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography.OpenSsl/Directory.Build.props#L6)

![image](https://user-images.githubusercontent.com/3258267/122028035-4b98d480-cdd4-11eb-9175-4c6709317ea2.png)

**Comment by akoeplinger** [comment]
@buyaa-n this sounds unexpected.

**Comment by buyaa-n** [comment]
That is expected, MSBuild would add SupportedOSPlatform attribute for any targeted build with the target platform, even it was PNSE only

**Comment by ViktorHofer** [comment]
We could easily fix that in our infra if we want to but I'm not sure it's important...

**Comment by buyaa-n** [comment]
> We could easily fix that in our infra if we want to but I'm not sure it's important...

I believe the cross-platform build is important because that is the one that will be shipped (which has the UnsupportedOSPlatform for windows, browser, android, ios, tvos). Honestly, I do not know for what we need an assembly that throws within all APIs, so I could not say if that is important or how important it is 😛

**Comment by safern** [comment]
Does it really matter though? Assemblies that throw not supported are runtime assemblies and the analyzer runs against the compile assemblies (ref). I know it's odd, but it doesn't seem to hurt anything.

**Comment by akoeplinger** [comment]
Yeah I didn't realize this was about the implementation assembly and not the ref assembly. I agree that it's not important for the former.
