### ISSUE TITLE
[iOS] Crash in AppleCrypto:AppleCryptoNative_SslIsHostnameMatch

### ISSUE THREAD

**Issue by spouliot** [dotnet/runtime#54239]
### Description

One of Xamarin.iOS unit test `LinkSdk.CryptoTest:SSL_IP_5706` is causing a crash in the PAL code.

It looks like a null CFArray is being used to get a count of items, causing a SIGSEGV.

```
	  at <unknown> <0xffffffff>
	  at AppleCrypto:AppleCryptoNative_SslIsHostnameMatch <0x001f7>
	  at AppleCrypto:SslCheckHostnameMatch <0x00112>
```

```
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

...

Thread 0 Crashed:: tid_103  Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff202e5079 CFArrayGetCount + 5
1   libSystem.Security.Cryptography.Native.Apple.dylib	0x000000010f111edb AppleCryptoNative_SslIsHostnameMatch + 763
2   ???                           	0x0000000114fbe258 0 + 4647019096
```

This test was disabled (until now) for a different reason: https://github.com/dotnet/runtime/issues/36897
IOW it might never have worked with the PAL.

### Configuration

* dotnet preview 6
* under iOS / tvOS

### Regression?

Kind of. This works properly with mono 2020-2

### Other information

[stdout-20210615_134005.log](https://github.com/dotnet/runtime/files/6658349/stdout-20210615_134005.log)

[link sdk_2021-06-15-135541_XAMBOT-1100-20210615_135542.crash.txt](https://github.com/dotnet/runtime/files/6658352/link.sdk_2021-06-15-135541_XAMBOT-1100-20210615_135542.crash.txt)

**Comment by filipnavara** [comment]
I fixed this some time ago.

**Comment by filipnavara** [comment]
https://github.com/dotnet/runtime/pull/53029
