### ISSUE TITLE
System.ComponentModel.Annotations dll version mismatch

### ISSUE THREAD

**Issue by varunmankal** [dotnet/runtime#54257]
We are using 4.7.0 version of System.ComponentModel.Annotations package that targets netStandard 2.0. Its dll present in the ref and lib folder of that package has version mismatch. 

I can see this issue had been reported earlier. I went through [this](https://github.com/dotnet/runtime/issues/41221) thread. By turning on auto-binding redirects, we will not see this issue. 

My scenario is slightly complicated to apply this work around. Here is my scenario:

My team has a library that targets netStandard 2.0 and dependent on the 4.7.0 version of System.ComponentModel.Annotations package. The library is used by one of our internal products which is a 4.7.2 .NET Framework application. When we run the application by disabling auto-binding redirects, we see version mismatch issue of the package. However, when we enable auto-binding redirects, we do not see the issue.

Now, if external customers use the .NET Framework application then they might see this issue depending on the state of auto-binding redirects. If it's turned on, they will not see the issue and vice-versa. 

So, we cannot rely on this. Is there a way to make sure that our end users definitely would not face this version mismatch issue ?

**Comment by ajcvickers** [comment]
@varunmankal I don't believe there is any other solution here than using binding redirects. @ericstj Can you confirm?

**Comment by ericstj** [comment]
Binding redirects are an unfortunate reality with .NETFramework and NuGet.  

> My team has a library that targets netStandard 2.0 and dependent on the 4.7.0 version of System.ComponentModel.Annotations package.

For this System.ComponentModel.Annotations in particular you can avoid this by cross-targeting to .NETFramework in your library (`<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>`).  On .NETFramework this package (and thus bindingRedirects for it) are not required since it's types are part of the framework.
