### ISSUE TITLE
Debugging Blazor AOT RuntimeError: indirect call signature mismatch

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#54264]
From @lbargaoanu https://github.com/dotnet/runtime/discussions/54049

I get this error while trying to run my Blazor AOT compiled code (it works without AOT) and I'm not sure how to investigate. Can I set some flag to get a useful stack trace or some other debugging information?
[Repro](https://github.com/lbargaoanu/RoslynInBlazor/tree/CoreWf).

@lewing

**Comment by lewing** [comment]
@lbargaoanu what version were you testing with and can you create a sample to reproduce this issue?

**Comment by lbargaoanu** [comment]
Preview 4. The link is in the initial message. [Repro](https://github.com/lbargaoanu/RoslynInBlazor/tree/CoreWf).

**Comment by radekdoulik** [comment]
@danroth27 does it still happen with latest preview?

**Comment by danroth27** [comment]
@radekdoulik I ported the issue, but the original reporter is @lbargaoanu.

**Comment by lbargaoanu** [comment]
Fixed! The AOT-ed code is slower than the interpreted code, but I'm guessing that's a general problem.

**Comment by radekdoulik** [comment]
Thank you for retesting it! I hope the AOT performance will improve in future.
