### ISSUE TITLE
Allow JsonIgnore on classes and structs

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#54269]
## Background and Motivation
Today, ```JsonIgnore``` can only be specified on properties and fields.  This creates a needlessly redundant scenario when ```JsonIgnore``` should be applied to all members of a type.

For example, today one must write:
```
    public class Person {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Optional<long> Id { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Optional<string> FirstName { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Optional<string> LastName { get; set; }
        
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Optional<int> Age { get; set; }
    }

    [JsonConverter(typeof(OptionalJsonConverter))]
    public struct Optional<T>  {
      /* ... */
    }
```

When it would be much nicer to be able to write:
```
    public class Person {
        public Optional<long> Id { get; set; }
        public Optional<string> FirstName { get; set; }
        public Optional<string> LastName { get; set; }
        public Optional<int> Age { get; set; }
    }

    [JsonConverter(typeof(OptionalJsonConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public struct Optional<T>  {
      /* ... */
    }
```

## Proposed API

```[JsonIgnore(Condition = ...)]``` should be specifiable on a class/struct to indicate that all properties/fields of that type have the specified default ```JsonIgnore``` condition.

```
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class JsonIgnoreAttribute : JsonAttribute
```

## Usage Examples
See Above.

## Alternative Designs
Today you can specify a global ```JsonIgnore``` value using ```JsonSerializerOptions.DefaultIgnoreCondition``` however, this is undesirable because it will impact other types you are (de)serializing and not just your target type.

## Risks
None.  Today ```JsonIgnore``` cannot be applied to classes so enabling it will not be a breaking change.

**Comment by TonyValenti** [comment]
@steveharter

**Comment by eiriktsarpalis** [comment]
Related to #50294 and #55781. In https://github.com/dotnet/runtime/issues/55781#issuecomment-881280929 I sketched a potential API for customizing ignored values (and not just `null`/`default` values). Would such an alternative suit your use case?
