### ISSUE TITLE
.NET Core - code is very slow when run on a computer with many cores

### ISSUE THREAD

**Issue by PatrikBak** [dotnet/runtime#54276]
Here's the code:

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

BenchmarkRunner.Run(typeof(Test));

public class Test
{
    [Benchmark]
    public Task Test_1() => TestCode(1);

    [Benchmark]
    public Task Test_Many() => TestCode(80);

    private static Task TestCode(int degreeOfParallelism) 
        => ParallelForEach(Enumerable.Range(1, degreeOfParallelism), degreeOfParallelism, _ => MethodRunInParallel());

    private static Task MethodRunInParallel()
    {
        var set = new HashSet<int>();
        for (var i = 0; i < 100000; i++)
            set.Add(i);
        return Task.CompletedTask;
    }

    private static Task ParallelForEach<T>(IEnumerable<T> source, int degreeOfParallelism, Func<T, Task> asyncAction)
    {
        var tasks = Partitioner
            .Create(source)
            .GetPartitions(degreeOfParallelism)
            .Select(partition => Task.Run(async () =>
            {
                using (partition)
                    while (partition.MoveNext())
                        await asyncAction(partition.Current);
            }));
        return Task.WhenAll(tasks);
    }
}
```

`lscpu`:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                160
On-line CPU(s) list:   0-159
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             8
NUMA node(s):          8
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 47
Model name:            Intel(R) Xeon(R) CPU E7- 2860  @ 2.27GHz
Stepping:              2
CPU MHz:               1064.000
CPU max MHz:           2266,0000
CPU min MHz:           1064,0000
BogoMIPS:              4521.94
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              24576K
NUMA node0 CPU(s):     0-9,80-89
NUMA node1 CPU(s):     10-19,90-99
NUMA node2 CPU(s):     20-29,100-109
NUMA node3 CPU(s):     30-39,110-119
NUMA node4 CPU(s):     40-49,120-129
NUMA node5 CPU(s):     50-59,130-139
NUMA node6 CPU(s):     60-69,140-149
NUMA node7 CPU(s):     70-79,150-159
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 popcnt aes lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid dtherm ida arat
```

`dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e
Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.300/
Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e
.NET SDKs installed:
  5.0.300 [/usr/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

[Result of `taskset -c 0-9 dotnet run -c Release`](https://pastebin.com/F4WPn0b0)
[Result of `dotnet run -c Release`.](https://pastebin.com/GN1GjBku)

Using all physical cores seems to slow down the execution 53-times. I would naturally expect some overhead, but not this high.

Is there a way to set up my .NET Core application so it uses multiple cores better?

**Comment by Clockwork-Muse** [comment]
```csharp
private static Task MethodRunInParallel()
{
    var set = new HashSet<int>();
    for (var i = 0; i < 100000; i++)
        set.Add(i);
    return Task.CompletedTask;
}
```

You're creating a hash set for each thread, and reallocating the backing array multiple times as the size increases, so at minimum the multi-thread version isn't using the same amount of memory.  The minimum amount of memory you're using is ~30GB, _without_ counting reallocations.  A naive thing to check would be if you were experiencing GC stalls.  If you pre-size the `HashSet`, does the situation improve?  
Too, there's only so many threads created by the runtime by default.  What is `ThreadPool.ThreadCount` before execution?  And what does `ThreadPool.GetMaxThreads()`/`ThreadPool.GetMinThreads()` return?

**Comment by Savlik** [comment]
Hi, thank you for suggestions. 
>  If you pre-size the HashSet, does the situation improve?

I tried pre-allocating memory for HashSet. Improvement was negligible. It still takes more than ten times than serial execution. 

> And what does ThreadPool.GetMaxThreads()/ThreadPool.GetMinThreads() return?

```
Maximum worker threads: 	32767
Maximum completion port threads: 1000
Available worker threads: 	32766
Available completion port threads: 1000
Min worker threads: 	160
Min completion port threads: 160
```

>  What is ThreadPool.ThreadCount before execution?

At the start of the program it is `1` and during parallel benchmark it stabilizes around `98`.

**Comment by mangod9** [comment]
Hey @PatrikBak, are you running this with any special config? Is it running with server or workstation GC? Also since this machine has 8 NUMA nodes, it inherently might not scale since the TP will schedule threads on all nodes, and cross-NUMA memory accesses are relatively slow and can cause further contention. Though in your sample doesnt look like you are accessing memory allocated on one thread from another, so that might not be too much of an issue. 

Can you affinitize the process to a single NUMA node and see the perf difference (Process Explorer can help with that on windows, so hoping debian has some similar tool)?

**Comment by Clockwork-Muse** [comment]
> At the start of the program it is `1` and during parallel benchmark it stabilizes around `98`.

... so you have at least some time lost due to thread startup (the normal .5 - 1 second wait for threadpool threads shouldn't be an issue since the minimum is so high).  I'd be curious what would happen if you could get the threadpool to pre-allocate ~100 threads.

**Comment by Savlik** [comment]
Hi @mangod9 , I am coworker of @PatrikBak.

> are you running this with any special config?

No special config. 

> Is it running with server or workstation GC?

I am running it with default values, so workstation GC, I guess. 

> Can you affinitize the process to a single NUMA node and see the perf difference?

Yes, I can. I have done some more tests and it seems to me, that thread distribution across NUMA nodes has some impact, but the total number of threads is more relelevant.

8 threads on one NUMA node:
`taskset -c 0-7 dotnet run -c Release`

```
|    Method |     Mean |    Error |   StdDev |   Median |
|---------- |---------:|---------:|---------:|---------:|
|    Test_1 | 18.79 ms | 0.264 ms | 0.247 ms | 18.78 ms |
| Test_Many | 12.90 ms | 0.499 ms | 1.456 ms | 12.24 ms |
```

8 thread all on different NUMA nodes:
`taskset -c 0,10,20,30,40,50,60,70 dotnet run -c Release`

```
|    Method |     Mean |    Error |   StdDev |
|---------- |---------:|---------:|---------:|
|    Test_1 | 19.96 ms | 0.314 ms | 0.294 ms |
| Test_Many | 23.32 ms | 1.338 ms | 3.707 ms |
```

2x8 threads:
`taskset -c 0-7,10-17 dotnet run -c Release`

```
|    Method |     Mean |    Error |    StdDev |
|---------- |---------:|---------:|----------:|
|    Test_1 | 19.58 ms | 0.390 ms |  0.494 ms |
| Test_Many | 49.01 ms | 4.178 ms | 11.785 ms |
```

8x2 threads:
`taskset -c 0,1,10,11,20,21,30,31,40,41,50,51,60,61,70,71 dotnet run -c Release`

```
|    Method |     Mean |    Error |    StdDev |
|---------- |---------:|---------:|----------:|
|    Test_1 | 20.09 ms | 0.345 ms |  0.288 ms |
| Test_Many | 74.88 ms | 5.600 ms | 16.512 ms |
```

4x8 threads:
`taskset -c 0-7,10-17,20-27,30-37 dotnet run -c Release`

```
|    Method |      Mean |     Error |    StdDev |
|---------- |----------:|----------:|----------:|
|    Test_1 |  19.86 ms |  0.391 ms |  0.653 ms |
| Test_Many | 182.90 ms | 14.529 ms | 40.980 ms |
```

8x4 threads:
`taskset -c 0-3,10-13,20-23,30-33,40-43,50-53,60-63,70-73 dotnet run -c Release`

```
|    Method |      Mean |     Error |    StdDev |
|---------- |----------:|----------:|----------:|
|    Test_1 |  18.93 ms |  0.362 ms |  0.321 ms |
| Test_Many | 173.70 ms | 10.266 ms | 28.787 ms |
```

> Though in your sample doesnt look like you are accessing memory allocated on one thread from another, so that might not be too much of an issue.

That was exactly my thoughts, but I do not understand dotnet internals that well.

**Comment by mangod9** [comment]
Might be worthwhile to test with serverGC..

**Comment by Savlik** [comment]
> I'd be curious what would happen if you could get the threadpool to pre-allocate ~100 threads.

No difference :-(

> Might be worthwhile to test with serverGC..

No difference :-(

**Comment by Clockwork-Muse** [comment]
> 8 threads on one NUMA node:
`taskset -c 0-7 dotnet run -c Release`

Uh, now I'm curious, does this actually change how many threads the runtime sees?  Although the results imply that it does.

[Related config to try](https://stackoverflow.com/questions/26830237/why-is-my-net-app-only-using-single-numa-node)

[Definitely related, unsure of effects](https://github.com/dotnet/runtime/issues/9748).

How much memory does your machine actually have?

**Comment by mangod9** [comment]
> Uh, now I'm curious, does this actually change how many threads the runtime sees

I assume you mean how many cores the runtime sees? 

Yeah NUMA aware threadpool is on the radar, but not sure how much it helps in this particular case, since all allocations are localized to the method. If `MethodRunInParallel` was awaiting on something then it would certainly matter, unless the `preallocating the HashSet` has made it a static or something

**Comment by Clockwork-Muse** [comment]
@mangod9 - What I was really getting at was, if the threadpool was only able to see the restricted set of cores, then fewer of them would be executing in parallel.

`HashSet` doesn't appear to be using an array pool,  but the runtime is likely still able to reuse the previous memory anyways.

I'm half curious what would happen if you rewrote your task launching method to not capture the context, but I don't know that would be a huge difference.

**Comment by kouvel** [comment]
Since there are significant allocations in the test, with more allocations in the parallel execution than the serial one, how does the perf change with server GC (`COMPlus_gcServer=1`)? I believe workstation GC does not scale as well as server GC in allocation perf across multiple threads, maybe that would be a reason. It doesn't look like there is anything special about the thread pool in the test case.

**Comment by En3Tho** [comment]
Do cpu frequency change when running mt test? Do server processors run at exact speed all the time or they can throttle/boost too? It could be running single thread at max boost clocks and multi at much lower speed

**Comment by Maoni0** [comment]
@kouvel looks like @Savlik already tried with server GC and saw no difference:

>> Might be worthwhile to test with serverGC..

> No difference :-(

instead of guessing, why not take a profile and see where the bottle neck is? you could start with a general CPU profile which may or may not reveal the culprit right away; and if needed take one with context switches which will tell you why threads aren't running. I'll take GC area off for now as there isn't any evidence that this is due to GC. I've included @brianrob who could help you with general perf investigation if needed.

**Comment by kouvel** [comment]
I missed that server GC was already tried, I'm sure I read it before but forgot :)

On my machine, which is not a multi-numa machine, and after initializing the `HashSet` with the capacity, I'm seeing a lot of page faults on Windows. I'm guessing that it's an indication that memory is not being reused, rather freed memory is being released to the OS and new memory is committed. I'm seeing a significant portion of time spent in filling the hash set in page faults as a result.

I also tried eliminating the allocations and reusing the memory instead. The perf seems to depend heavily on how memory is reused between threads. When threads frequently reuse memory that was recently operated on by other threads, perf is 4-5x as slow.

The size of the hash set would probably put it in the "large" allocation bucket. I tried smaller capacity to make it a "small" allocation, and perf was not much better but committed memory was a lot more stable.

It seems likely to me that the perf issues involved are tied with whether GC memory is reused, and how it's reused between threads and numa nodes.

**Comment by Maoni0** [comment]
if you are allocating temporary large objects you'd be triggering gen2 GCs pretty often and that could result in frequent decommit/recommit. we generally advise folks to pool large objects. 

collecting profiles can confirm whether this is the case or not. you can do a general collection with `perfview collect`.

**Comment by kouvel** [comment]
Yes that's what I saw, but when I changed the allocation sizes to be "small" objects, perf was the same. Of course a larger portion of time was spent in allocation itself, but it was not comparable to reusing memory well without allocations.

**Comment by mangod9** [comment]
closing since this is not actionable currently. @PatrikBak please reopen if you still have concerns -- one point to note that we have enabled new "Regions" functionality in .NET 7 and it might be worthwhile to run your scenario on that to ensure there arent any further concerns. Thx!
