### ISSUE TITLE
[Wasm][AOT] Performance regression in List<string> foreach

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#54272]
### Description

A performance regression happened when using this repro (with `-O=gsharedvt` for `mono-aot-cross`):

```csharp
var SUT = new List<object>();
SUT.AddRange(Enumerable.Range(1, 1000)
	.Select(i => (object)null));

var sw = Stopwatch.StartNew();

for (int i = 0; i < 5000; i++)
{
	int count = 0;
	foreach (var item in SUT)
	{
		count++;
	}
}

sw.Stop();
Console.WriteLine($"TestForeachListOfT: {sw.Elapsed}");
```

Some performance benchmarks:

**With df6e9560a47:**
Result: `TestForeachListOfT: 00:00:00.3979650`

![image](https://user-images.githubusercontent.com/5839577/122224784-717cb280-ce82-11eb-815e-c7f0cb8652b2.png)

**With a822d3909b9**:
Result: `TestForeachListOfT: 00:00:00.1164150`
![image](https://user-images.githubusercontent.com/5839577/122225519-24e5a700-ce83-11eb-8c9e-86e64bf8a315.png)

**With d07f9111c57 and 337216a96c1:**
Result: `TestForeachListOfT: 00:00:00.2462100`
![image](https://user-images.githubusercontent.com/5839577/122225329-f667cc00-ce82-11eb-8376-706d93e2c68c.png)

### Regression?

Yes

**Comment by vargaz** [comment]
This should be fixed by
https://github.com/dotnet/runtime/commit/d4fc723b4982a49deb4a43b5d145cbd667e6077d

**Comment by jeromelaban** [comment]
Here's the perf numbers, with 881e90231b9:

TestForeachListOfT: 00:00:00.3946000
dotnet.js:2298 TestForListOfT: 00:00:00.0623000
dotnet.js:2298 TestForArray: 00:00:00.0212000

Still with `-O=gsharedvt`, it looks like the situation has not improved.

**Comment by vargaz** [comment]
What is the issue here ? Is it that foreach on a list is slower than a for loop or a for loop on an array ?

**Comment by jeromelaban** [comment]
The issue is that the foreach loop is calling into interpreted code, where as the for loop is not. When the code in the method is AOTed, it's 3x faster than the interpreted one (see the flame chart for a822d39 above).

**Comment by jeromelaban** [comment]
Here's the full sample I'm running:

```csharp
static void Main(string[] args)
{
	TestForeachListOfT();
	TestForListOfT();
	TestForArray();
}

private static void TestForArray()
{
	var SUT = new List<object>();
	SUT.AddRange(Enumerable.Range(1, 1000)
		.Select(i => (object)null));
	var SUT2 = SUT.ToArray();

	var sw = Stopwatch.StartNew();

	for (int i = 0; i < 5000; i++)
	{
		int count = 0;
		foreach (var item in SUT2)
		{
			count++;
		}
	}

	sw.Stop();
	Console.WriteLine($"TestForArray: {sw.Elapsed}");
}


private static void TestForListOfT()
{
	var SUT = new List<object>();
	SUT.AddRange(Enumerable.Range(1, 1000)
		.Select(i => (object)null));

	var sw = Stopwatch.StartNew();

	for (int j = 0; j < 5000; j++)
	{
		int count = 0;
		for (int i = 0; i < SUT.Count; i++)
		{
			count++;
		}
	}

	sw.Stop();
	Console.WriteLine($"TestForListOfT: {sw.Elapsed}");
}

private static void TestForeachListOfT()
{
	var SUT = new List<object>();
	SUT.AddRange(Enumerable.Range(1, 1000)
		.Select(i => (object)null));

	var sw = Stopwatch.StartNew();

	for (int i = 0; i < 5000; i++)
	{
		int count = 0;
		foreach (var item in SUT)
		{
			count++;
		}
	}

	sw.Stop();
	Console.WriteLine($"TestForeachListOfT: {sw.Elapsed}");
}
```

**Comment by jeromelaban** [comment]
I reran the sample above with e983168f871, and here are the results:
```
TestEnumeratorListOfT: 00:00:00.1430000
TestForeachListOfT: 00:00:00.3181000
TestForListOfT: 00:00:00.1434000
TestForArray: 00:00:00.0161000
```

**Comment by jeromelaban** [comment]
This behavior was caused by a rogue `MONO_INLINE_LIMIT=1` set for prior troubleshooting, which interferes with the ability of the AOT compiler to remove empty `finally` blocks.

Thanks @vargaz for the troubleshooting.
