### ISSUE TITLE
[EnC] Add test case for deleting custom attributes using ApplyUpdate

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#54284]
Now that https://github.com/dotnet/runtime/pull/54060 and #54619 have been merged, we can add new tests to validate that CoreCLR ApplyUpdate behaves correctly when custom attributes are deleted.

**Comment by noahfalk** [comment]
@mikem8361

**Comment by lambdageek** [comment]
I think the new capability went in (#54619).  But we don't have a testcase.
