### ISSUE TITLE
Azure Pipelines status is not reported for GitHub for pull requests

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#54285]
Looking at the past few PRs, like https://github.com/dotnet/runtime/pull/54238, https://github.com/dotnet/runtime/pull/54282, and others, the Azure Pipeline run statuses are not being sent to GitHub. However, the pipelines do appear to actually be running. In the case of the former PR, the pipeline run can be seen at https://dev.azure.com/dnceng/public/_build/results?buildId=1190227&view=results.

**Comment by jkoritzinsky** [comment]
This is a known Azure DevOps outage.

**Comment by vcsjones** [comment]
Hm, okay. I'll close this then.
