### ISSUE TITLE
Document HttpResponseMessage.Dispose will terminate response and notify the server

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#54294]
`HttpResponseMessage.Dispose()` docs should mention that it will terminate a response early and send a notification to the server (e.g. HTTP/2 RST_STREAM).

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpresponsemessage.dispose?view=net-5.0

**Comment by geoffkizer** [comment]
I suppose we could do this, but it's sort of a low-level detail that is invisible to most people. And the behavior is version dependent.

Why does it matter? If a user disposes the HttpResponseMessage then they have indicated they don't care about the response anymore. Whether that actually cancels it on the wire or not seems like an implementation detail.

**Comment by karelz** [comment]
Triage: @JamesNK do you want to put up PR with the language change from email exchange?

**Comment by karelz** [comment]
Found it: "Disposing a response that is in-progress can signal to the server that the response is no longer needed. This signal is implementation/protocol dependent"
