### ISSUE TITLE
Update `SystemNative_AlignedAlloc` to properly check `aligned_alloc` availability for Apple targets

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#54296]
https://github.com/dotnet/runtime/pull/54006 introduced new `NativeMemory` APIs including one that wraps `aligned_alloc` where available.

On Apple targets this is only available on 10.15 or later but we currently target 10.13 and as such have a `#if HAVE_ALIGNED_ALLOC && !defined(__APPLE__)` check.

Ideally we would update this to correctly check for the availability of `aligned_alloc` (either via CMake magic or some existing Apple specific define) so we can light up on iOS, OSX, and Apple Silicon.

**Comment by filipnavara** [comment]
Would it make sense to use `__builtin_available` and generate runtime check or is it not worth it?

**Comment by tannergooding** [comment]
I don't think its worth it for this scenario. We are falling back to `posix_memalign` which is likely a wrapper for (or the underlying implementation of) `aligned_alloc`. Its simply just a matter of preferring the official C API when its available over the older POSIX API.

**Comment by filipnavara** [comment]
Makes sense.
