### ISSUE TITLE
Obtain an X509Certificate2 with an RSACryptoServiceProvider as PrivateKey

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#54327]
We have .NET 4.8 code which makes heavy use of RSACryptoServiceProvider, we especially need X509Certificate2 instances with RSACryptoServiceProvider instances as PrivateKey. We want to port the code to .NET 5 now and realized that when we load X509Certificate2 instances that the PrivateKey is of type RSACng which is unfortunately a problem.

Is there a way to "downgrade" the PrivateKey to an RSACryptoServiceProvider instance? Or is there a legacy feature switch or something like that to use RSACryptoServiceProvider by default again?

Best regards,
D.R.

**Comment by drauch** [comment]
In one area of our code we even have the private key available in memory, unfortunately not even this code helped us:

```
var rsaPrivateKey = certificate.GetRSAPrivateKey();
var privateKeyBytes = rsaPrivateKey.ExportPkcs8PrivateKey();
var rsa = new RSACryptoServiceProvider();
rsa.ImportPkcs8PrivateKey(privateKeyBytes, out _);
var newCert = certificate.CloneWithoutPrivateKey();
var newCertWithPrivateKey = newCert.CopyWithPrivateKey(rsa);
// newCertWithPrivateKey.PrivateKey is again RSACng :(
```

**Comment by vcsjones** [comment]
> Is there a way to "downgrade" the PrivateKey to an RSACryptoServiceProvider instance?

To my knowledge no, it will prefer to return `RSACng` instances when it can. It might actually return `RSACryptoServiceProvider` for some narrow cases where CNG cannot be used with persisted keys. The best approach going forward would not be to treat it as any particular RSA implementation and instead cast it to `RSA`, like `(RSA)certificate.PrivateKey`.

But `PrivateKey` [is going to be obsoleted in .NET 6][1], so you should use `GetRSAPrivateKey()` instead.

> is of type RSACng which is unfortunately a problem.

Is there a particular reason why you need an `RSACryptoServiceProvider`, other than the code having already been written to assume a specific RSA implementation?

[1]: https://github.com/dotnet/runtime/issues/47977#issuecomment-848081543

**Comment by drauch** [comment]
> Is there a particular reason why you need an RSACryptoServiceProvider, other than the code having already been written to assume a specific RSA implementation?

Yes, indeed. We're having a system where we have (test) private keys in a database (exported from RSACryptoServiceProviders by using `ExportCspBlob`), we need to re-import those CSP blobs into X509Certificate2 instances as its private key. Is there a way to import such CSP blobs into an X509Certificate2 instance? Is there a common format between RSACryptoServiceProvider and RSACng?

Best regards,
D.R.

**Comment by vcsjones** [comment]
> Is there a way to import such CSP blobs into an X509Certificate2 instance?

To import a CSP blob you can do something like this:

```csharp
(X509Certificate2 cert, byte[] cspBlob) = GetCertificateAndCspBlob();

using RSACryptoServiceProvider rsa = new();
rsa.ImportCspBlob(cspBlob);
X509Certificate2 certWithCspBlob = cert.CopyWithPrivateKey(rsa);
```

But as you noted earlier, it will become an `RSACng` key.

**Comment by drauch** [comment]
In order to call SignerSignEx2 I also need to build a SIGNER_PROVIDER_INFO structure. Until now I got the necessary properties from `((RSACryptoServiceProvider) privateKey).CspKeyContainerInfo` (properties: ProviderName, ProviderType, KeyContainerName). I can't find any similar properties on `RSACng`. Do you know how to get the necessary information to call SignerSignEx2?

**Comment by vcsjones** [comment]
>  I also need to build a SIGNER_PROVIDER_INFO structure

Since you are building a certificate that has an associated private key, you should be able to pass in `NULL` to `pProviderInfo`. `pProviderInfo` is used when the certificate and signing key are disjoint. But since you are combining the cert and private key in to a certificate with an associated private key, providing a `pProviderInfo` is redundant. 

If you do have a disjoint certificate and signing key, then you can just keep using the `RSACryptoServiceProvider` and use a certificate that has no associated private key.

I threw together an example here: https://gist.github.com/vcsjones/6901b344188b179d59fb0255e8999f29

This will do a bare-bones minimum of signing, doesn't time stamp, etc. but demonstrates enough of using `SignerSignEx2` with a certificate.

**Comment by bartonjs** [comment]
> Is there a common format between RSACryptoServiceProvider and RSACng?

For public keys there are two, {Import,Export}SubjectPublicKeyInfo and {Import,Export}RSAPublicKey.

For private keys there are two and a half: {Import,Export}Pkcs8PrivateKey, {Import,Export}RSAPrivateKey, and {Import,Export}EncryptedPkcs8PrivateKey.

Anything that isn't the Windows CAPI/CSP blob format, really.  You could also just translate the CSP blob to RSAParameters (oh, add another import/export format) manually, like we do for Linux compat: https://source.dot.net/#System.Security.Cryptography.Csp/System/Security/Cryptography/CapiHelper.Shared.cs,b7bc764e6deb34f5

**Comment by bartonjs** [comment]
Given a lack of followup this seems to be addressed, so closing the issue.  If there's still something pending, replying and/or reactivating is fine.
