### ISSUE TITLE
HttpStatusCode is missing code 429 (TooManyRequests)

### ISSUE THREAD

**Issue by deanchalk** [dotnet/runtime#54321]
### Description

Different versions of System.Net.Primitives have slightly different HttpStatusCode  enums - which isn't correct.
I am building a UWP app and the version of System.Net.Primitives referenced is missing status code 429

Here is the decompiled code

```c#
// Decompiled with JetBrains decompiler
// Type: System.Net.HttpStatusCode
// Assembly: System.Net.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 09D466F1-640B-4238-B745-5963E2F2B264
// Assembly location: C:\Users\deanc\.nuget\packages\microsoft.netcore.universalwindowsplatform\6.2.9\ref\uap10.0.15138\System.Net.Primitives.dll

namespace System.Net
{
  /// <summary>Contains the values of status codes defined for HTTP.</summary>
  public enum HttpStatusCode
  {
..............
  }
}
```

It looks like all status codes are there apart from 429 (TooManyRequests). If you look at the System.Net.Primitives for Xamarin Forms (for example), the 429 code is there correctly.

**Comment by Symbai** [comment]
https://source.dot.net/#System.Net.Primitives/System/Net/HttpStatusCode.cs,76

**Comment by stephentoub** [comment]
TooManyRequests was added to HttpStatusCode in https://github.com/dotnet/corefx/pull/26727 for .NET Core 2.1 in response to https://github.com/dotnet/runtime/issues/15650.  It's not available in the enum earlier than that.

**Comment by huoyaoyuan** [comment]
You should be able to do a conversion `(HttpStatusCode)429` to use it.

**Comment by karelz** [comment]
Triage: Simple workaround above, closing for now.
