### ISSUE TITLE
Workflow docs for testing provide instructions that will not work

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#54323]
The docs at https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md include no mention that libs.pretest is required. Running the commands as written will generate many test failures with this error:

> '"E:\git\runtime\artifacts\bin\testhost\net6.0-windows-Release-x64\dotnet.exe"' is not recognized as an internal or external command, operable program or batch file

A couple thoughts/concerns:

1. It appears this doc page has been out-of-date a long time. It suggests that either nobody is reading these docs or nobody is reporting when they are broken. This makes it very likely a future change will put them back in a broken state that will again go unnoticed. Some potential solutions: Delete the page, replace the content with a link to another page that does stay up-to-date, include a message at the top of the page indicating the last time someone validated the instructions were correct, make some procedural change that enforces the docs to remain up-to-date with infra changes.
2. We could add a heuristic check in the test target that verifies some expected files exist and warns the user that they need to run libs.pretest if not. The current error that dotnet.exe is missing doesn't help discover what step was missed.

**Comment by ViktorHofer** [comment]
Testing requires building first which is documented here: https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md.

The `libs.pretest` subset is part of the `libs` subset. What we can do better in the instructions that you pointed to above is that following the building instructions is a prerequisite before testing (because we don't define dependencies between components today).

Does that make sense?

**Comment by noahfalk** [comment]
Thanks @ViktorHofer! Knowing that libs.pretest is part of libs does make me less worried, so that certainly helps : ) I still think (and I believe you agreed) the current instructions can be misleading, but it is much easier for me to imagine that many people were using the instructions as-is with success because they had already built the libs subset at some point prior. Thanks for clarifying my misunderstanding there.

I updated the PR https://github.com/dotnet/runtime/pull/54324/files with some language that seems more clear to me. Feel free to use it as-is if you like it or we can gladly write it another way. Thanks!

**Comment by ericstj** [comment]
Fixed in https://github.com/dotnet/runtime/pull/54324
