### ISSUE TITLE
[.NET 6 Preview 5] Debugger crashes on Apple Silicon (M1) - 0x80131c3c

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/runtime#54322]
Hey all,

I am running into an issue with the .NET 6 debugger on an Apple M1.

I use a fresh copy of macOS Sig Sur 11.4 on a brandnew MBP 13 M1. 
With .NET SDK ARM64 6.0.100-preview.4.
With VS Code 1.57.0 (M1 version).
With VS for Mac 8.10.1 (build 71).
 
This error occurs when F5’ing in VS Code or VS for Mac:

`Unable to attach to CoreCLR. Unknown Error: 0x80131c3c
`

Is this maybe a regression?
I found this here:
https://github.com/OmniSharp/omnisharp-vscode/issues/4390

But it seems it was fixed before.

Thanks.

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by ChristianWeyer** [comment]
FYI: I just tried it with Preview 5 – no change, same error.

**Comment by hoyosjs** [comment]
I tested this on preview 5 and found no issues. I also checked that there was a change for that codepath between preview 4 and preview 5. The issue you linked mentions a permissions issue related to the omnisharp extension in x64 vs arm64. If you reproduce this with just hello world I'd think it's that first. If you have a repro though feel free to share and I'll take a look again.

**Comment by ChristianWeyer** [comment]
OK, I completely removed all runtimes and SDKs.
Seems it was the issue that we currently cannot use x64 and ARM64 runtimes/SDKs side-by-side.

Now with a fresh .NET 6.0 Preview 5 installed, the debugger works in VS Code. It does not work in VS for Mac.

Thanks!
