### ISSUE TITLE
Issue running WinForms Ribbon apps on .NET 5.0.7 (regression)

### ISSUE THREAD

**Issue by MatthewBeardmore** [dotnet/runtime#54335]
### Description

Previously, running WinForms with Ribbon apps worked properly in both .NET Core 3.1 and .NET 5 5.0.6, but after updating to 5.0.7, the application crashes as soon as you attempt to choose a combobox option. I have attached a repo project based off of the sample project from https://github.com/harborsiem/WindowsRibbon/tree/master/Samples/CS/06-ComboBox. Other than the conversion from .NET Framework, it is the same as the code at that URL.

In order to reproduce, launch the project, then select any option in the comboboxes - as soon as the mouse hovers over an option, the AccessViolationException occurs.

### Configuration

.NET 5.0.7 
Windows 10 21H1
x64

### Regression?

This previously worked in .NET 5.0.6 and .NET Core 3.1 (still works in both of these on machines that do not have 5.0.7 installed).
[06-ComboBox.zip](https://github.com/dotnet/runtime/files/6671043/06-ComboBox.zip)
I also have tried this against .NET 6.0 preview 4, which experiences the same issue as .NET 5.0.7.

### Other information?

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by jkotas** [comment]
@jkoritzinsky @AaronRobinsonMSFT

**Comment by MatthewBeardmore** [comment]
I found issue 54132, which appears to be related. I took the SDK from https://github.com/dotnet/runtime/issues/54132#issuecomment-862699818 and ran it against this sample project, and the sample project does not crash when selecting combo boxes.

**Comment by AaronRobinsonMSFT** [comment]
@MatthewBeardmore Thank you for reporting this issue. We already determined this behavior needed to be fixed so we are servicing .NET 5 via #54244. Reporting this helps reinforce that decision.

**Comment by jkoritzinsky** [comment]
Fixed by #54244
