### ISSUE TITLE
Uncaught ReferenceError: config is not defined

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54330]
WASM specific issue: `net6.0-Browser-Release-wasm-Mono_Release-wasmtestonbrowser-Ubuntu.1804.Amd64.Open`

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54319-merge-2a40ee7278394c5087/Microsoft.Extensions.Http.Tests/console.1e4b4b90.log?sv=2019-07-07&se=2021-07-07T11%3A09%3A33Z&sr=c&sp=rl&sig=%2BA25WrP3jkuD2wvD%2B2t8ORhgRXDo4aMP7bV%2Bhi%2BNlOM%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1191788&view=ms.vss-test-web.build-test-results-tab&runId=35771832&paneView=debug&resultId=169870

cc @akoeplinger

**Comment by akoeplinger** [comment]
@radical any idea what might be happening here?

**Comment by lewing** [comment]
This should be fixed now
