### ISSUE TITLE
Move of Evidence type regressed on .NETStandard2.0 with package removal of System.Security.AccessControl

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#54341]
I moved Evidence down to `System.Security.AccessControl` earlier this release since this broke the dependency from `System.Security.Cryptography.Xml` on `System.Security.Permissions`.  https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f

Dependencies on `System.Security.Permissions` are undesired as that package is entirely legacy and has other unrelated dependencies (SystemEvents, Drawing, Windows.Extensions).

This change hasn't yet shipped, and by removing the `System.Security.AccessControl` package in https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f#diff-96cf205e7d17fc3e8555ab5b26de3d26ae7039db478c09a610202cf1aebe9ca7 it will not ship for `netstandard2.0`.

I suggest we bring back just the `System.Security.AccessControl` package in order to move this type in the `netstandard2.0` reference, so that we can avoid the dependency on `System.Security.Permissions` in this package.  We can remove that package in `net7.0`.

This issue caused the problem here: https://github.com/dotnet/aspnetcore/pull/33571

**Comment by ericstj** [comment]
cc @viktorhofer

**Comment by bartonjs** [comment]
I defer entirely to you guys (@ericstj / @ViktorHofer) here.

**Comment by Anipik** [comment]
@ericstj should we address this in 6.0 ?

**Comment by ericstj** [comment]
Yes if possible.  This will only become harder to fix in 7.0.  I think @ViktorHofer was planning to do this.

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/commit/56894f09aaac6e635136dec68dfc174159911796
