### ISSUE TITLE
System shared-library dependencies are not lazily loaded in single-file on Linux

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#54347]
See https://github.com/dotnet/runtime/issues/45720 for an example.

It looks like the default runtime deployment avoids this by loading libSystem.Net.Security.Native.so lazily, which will only then load many of the system libraries. Since that library is not statically compiled into the host, its dependencies are loaded eagerly.

Unfortunately the only way to implement this may be to call dlopen ourselves, since I don't know a way of getting the Linux linker to automatically insert the stub.

**Comment by VSadov** [comment]
This should be fixed in https://github.com/dotnet/runtime/pull/55037
