### ISSUE TITLE
Regressions in System.Text.Encodings.Web.Tests.Perf_Encoders

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54354]
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [9a64a29c38319a3c7724894fbf3e1e14b6fa799e](https://github.com/dotnet/runtime/commit/9a64a29c38319a3c7724894fbf3e1e14b6fa799e)
Compare | [a4b3772d1ada339220145843138d4c622134adeb](https://github.com/dotnet/runtime/commit/a4b3772d1ada339220145843138d4c622134adeb)
Diff | [Diff](https://github.com/dotnet/runtime/compare/9a64a29c38319a3c7724894fbf3e1e14b6fa799e...a4b3772d1ada339220145843138d4c622134adeb)

### Regressions in System.Text.Encodings.Web.Tests.Perf_Encoders

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[EncodeUtf8 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf8(arguments%3a%20UnsafeRelaxed%2cno%20(escaping%20%2f)%20required%2c512).html>) | 72.07 ns | 78.22 ns | 1.09 | 0.02 | | |
[EncodeUtf8 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf8(arguments%3a%20UnsafeRelaxed%2chello%20%22there%22%2c512).html>) | 91.27 ns | 96.62 ns | 1.06 | 0.02 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_15_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Encodings.Web.Tests.Perf_Encoders_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_15_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Encodings.Web.Tests.Perf_Encoders_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_15_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Encodings.Web.Tests.Perf_Encoders.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Encodings.Web.Tests.Perf_Encoders*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-51f4b8ab-d2f4-41c4-b8c2-1e61d38499585a180df01ad4322b4/41d30ea7-0b57-4cb4-bb1a-55dcecb936fb.zip?sv=2019-07-07&se=2021-07-09T12%3A17%3A44Z&sr=c&sp=rl&sig=edaAOB9rncDtgyXukcItTUys%2FXcYT3%2FIGtONGFI8mx0%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-b40c4926-7965-41f8-9819-dbf2e6122b2b746672ac13949079c/a8ae745e-e3e8-46f1-b2fa-d5ec038ed5ab.zip?sv=2019-07-07&se=2021-07-10T04%3A29%3A13Z&sr=c&sp=rl&sig=5xFeJ46jJyubjqeBZtjFn4YXfXxfqBJvnyOkQPMBKGI%3D>)

#### System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf8(arguments: UnsafeRelaxed,no &lt;escaping /&gt; required,512)

```log

```
#### System.Text.Encodings.Web.Tests.Perf_Encoders.EncodeUtf8(arguments: UnsafeRelaxed,hello "there",512)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by GrabYourPitchforks** [comment]
The diff shows no changes to the _System.Text.Encodings.Web_ sources between those two commits. PGO or JIT issue, perhaps?

**Comment by DrewScoggins** [comment]
Sorry, I did not mean to copy this issue over. This is not a regression.
