### ISSUE TITLE
#40711 breaks nullable reference types

### ISSUE THREAD

**Issue by Kaelum** [dotnet/runtime#54367]
None of the collection objects support `KeyValuePair<string?, string?>`, which means the only way that you can use the `FormUrlEncodedContent` class is by creating a `List<KeyValuePair<string?, string?>>` object.  Is this the intention of the core team?

@ManickaP is wrong in the #40711 statement.  An entire year of requiring others to write absurd code is not acceptable.  This needs to be escalated to someone higher.

**Comment by Kaelum** [comment]
P.S. When using .NET Core 3.1 with `<Nullable>enable</Nullable>` using `Dictionary<string, string>` works, no warnings, and no errors.  Upgrading the .NET 5.0 compiles with warnings.  So, who is being protected?

**Comment by Joe4evr** [comment]
Strange. Nullable covariance should allow any `IEnumerable<KeyValuePair<string, string>>` (such as `Dictionary<string, string>`) to be assigned to an `IEnumerable<KeyValuePair<string?, string?>>` without issue.

@jcouv I believe you know most about the nullable rules.

**Comment by Kaelum** [comment]
@Joe4evr let me clarify.  At the time that we wrote the described code, casting as `IEnumerable<KeyValuePair<string?, string?>>` was not supported.  The majority of people who wrote those applications for .NET Core 3.1 and earlier, may not know this is now allowed.  The purpose of this thread to show that the statement, "**_By removing nullability from the key, we are removing ability to pass null values and have them encoded as empty strings (which has been allowed up until this change). This might actually break someone._**" is hypocritical, and actually breaks existing code.

Changing the key to `string?`, and internally changing `null` to `Sting.Empty` is breaking in itself.  Documenting this now, 3+ years later, doesn't fix anything.  As I stated in my first statement, waiting a year for this to be handled is not acceptable.  This needs to immediately be addressed.

**Comment by Kaelum** [comment]
P.S. The HTTP protocol does not support the key being `null` or the value being `null`, so this change to allow nulls is invalid, in and of itself.

**Comment by MihaZupan** [comment]
How is this issue different from the discussions on #38494?

**Comment by Kaelum** [comment]
> How is this issue different from the discussions on #38494?

That issue only contains a small subset of the whole issue, but it's ultimate resolution may be the same.  It has also been sitting around for a year without a resolution.  On August 12, 2020, long before .NET 5.0 was released, @ManickaP effectively shutdown the discussion w/o any support for doing so.  I'm sorry, but there is a serious failure in communication between the teams involved.

> Note that this is the existing behaviour, not what the PR did.

It was not previously documented as doing so.  The initial nullable implementation documented the key and value types as `string`, not `string?`, thus the change that caused this issue, is breaking.

> #40711 was reverting a previous change, it's not introducing new behaviour.

The reversion broke the fix/correction.  As stated above, this change should never have been implemented in the first place.  It is very clear that this breaking chance was never researched properly.

**Comment by jcouv** [comment]
I'm joining the conversation late so I apologize if I'm missing some context. 
Reading the thread and as someone unfamiliar with `FormUrlEncodedContent`, I would find useful to have code snippet to illustrate the problem: "Here's how we want to use a certain API with nullability and if we annotate that API a certain way then we get an undesirable behavior (compiler warnings)".

**Comment by Kaelum** [comment]
@jcouv as a consumer, these changes should never have been made.  This class is solely used for HTTP purposes, it originally was defined as `string` (not `string?`), and the HTTP protocol does not allow either the key, or the value, to be `null`.  I have no idea why anyone at Microsoft thought that this change was needed.

**Comment by ManickaP** [comment]
Thanks for bringing your concerns up!  I'll try to explain what happened there.

> it originally was defined as `string`

This was before nullability for reference types has been introduced, therefore it was equivalent to `string?` with nullability checks.

> On August 12, 2020, long before .NET 5.0 was released

This is for us actually quite late in the release cycle since we're the bottom of the whole stack, we need to freeze all API/feature quite early.

Note that empty/null (depends on your interpretation) keys and/or values are allowed: https://url.spec.whatwg.org/#application/x-www-form-urlencoded.

The original change for 5.0 made non-nullable only keys https://github.com/dotnet/runtime/pull/40267 not values. I'm now considering making both of them non-nullable so that they would be compatible with `Dictionary<string, string>` which seems to be the most useful scenario. The only question is whether to introduce a new ctor or remove the nullability completely.

---

This conversation is not different from https://github.com/dotnet/runtime/issues/38494 and https://github.com/dotnet/runtime/issues/44458. If you have any particular suggestions about the API shape, please share them in one of the issues. I don't see a point in keeping this issue opened and having the discussion split even more.

I have this in my pipeline for 6.0 and it'll get resolved.

**Comment by Kaelum** [comment]
>> it originally was defined as `string`
>
> This was before nullability for reference types has been introduced, therefore it was equivalent to string? with nullability checks.

I suggest that you look back at the .NET 3.1 implementation of nullability checks.  We had updated ALL of our code to be 100% compliant, and they were defined as `string` with nullability checks on.  Because of this change in .NET 5.0, all related code was broken when we upgraded.

> Note that empty/null (depends on your interpretation) keys and/or values are allowed

That is where you are wrong.  There is no interpretation that needs to be made at all.  The specification is extremely clear, and uses the term `empty`, as does every related RFC.

> I have this in my pipeline for 6.0 and it'll get resolved.

Which means that this will be broken for at least a year, for those who followed the guidelines, and aren't allowed to upgrade to a new .NET version until it has been out for at least 6 months.  Bugs fixes don't have this limitation.

**Comment by karelz** [comment]
@Kaelum I see that you are passionate about this topic. I would like to ask everyone for calming down the discussion and sticking to technical details. Let's try not to attack each other and let's try not to make broad statements.


It seems we are mixing several discussions here -- what is the right way to fix it and when/where it should be fixed.
We do not have time machine, so there is no point in making statements what should have happened in the past. Let's try to focus on what is the right thing to do and THEN we can discuss when and where the right thing can happen.

@Kaelum you seem to believe you know what is the right solution. And some people on this thread disagree with that.
Can we focus on getting to consensus first? i.e. discussing technical disagreements first, using evidence ideally with references ... and perhaps opening up to possibility that other people might interpret certain things differently.

**Comment by Kaelum** [comment]
@karelz I have made it very clear that waiting a year for this to be available, is not acceptable.  This bug, and it is a bug, was introduced due to lack of proper research.  Since it affects everyone, it should be fixed in the soonest possible release.  The exact fix does not matter to us.  It only needs to take into account that a `Dictionary<TKey, Tvalue>` has never allowed the `TKey` to be null.

**Comment by karelz** [comment]
> This bug, and it is a bug, was introduced due to lack of proper research.

First, there is still debate, if it is a bug - see https://github.com/dotnet/runtime/issues/38494#issuecomment-865371772. I think we can at least agree that it is a problem affecting customers. Let's agree on that.
Second, regarding your speculation about lack of proper research -- the truth is that EVERY bug in EVERY software in the world is an oversight and could have been prevented. However, I hope we all agree it is not practical to expect SW products to be bug-free. Overall, I fail to see how is your statement about research helping here in arriving to resolution.

> I have made it very clear that waiting a year for this to be available, is not acceptable. ... Since it affects everyone, it should be fixed in the soonest possible release.

You hinted at your disappointment about waiting for .NET 6. That said, you are 3rd person to notice the problem (IMO that does not qualify like "affects everyone") and there is a simple workaround. Even if we had a simple fix available, I don't think it would make the bar for servicing given the known impact and workaround availability at this moment. Let's focus on addressing it in .NET 6 and then we can revisit if the impact on .NET developers is bigger than it is now.
