### ISSUE TITLE
Incomplete loading of DacpGcHeapDetails in ClrDataAccess::ServerGCHeapDetails

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#54368]
The structure `DacpGcHeapDetails` has many fields:

https://github.com/dotnet/runtime/blob/1306b036c1414afa39608ed8ede24fe003191132/src/coreclr/inc/dacprivate.h#L725-L757

But the `ServerGCHeapDetails` function only loads a subset of them:

https://github.com/dotnet/runtime/blob/1306b036c1414afa39608ed8ede24fe003191132/src/coreclr/debug/daccess/request_svr.cpp#L102-L144

Comparing with the workstation GC, so code is also questionable - for example - do we need to check of the validity of the finalization queue?

https://github.com/dotnet/runtime/blob/72a26f921ffbd49bb5a634d8ad2fa81f0a549928/src/coreclr/debug/daccess/request.cpp#L2772-L2828

In particular, the fact that `saved_sweep_ephemeral_seg` is not loaded during `ServerGCHeapDetails` is leading SOS to believe a region build of the GC to be a segment build, leading to subsequent errors. 

Therefore `saved_sweep_ephemeral_seg` has to be fixed. The other fields are less clear. As far as I understand the SOS code, it looks like those fields are also accessed in the server GC case as well, so we should fix those as well.

@dotnet/gc for awareness

**Comment by tommcdon** [comment]
@cshung Thank you for the bug report. Feel free to submit a PR correcting the inaccuracies in the DAC.
cc @mikem8361

**Comment by noahfalk** [comment]
thanks @cshung! 👍
