### ISSUE TITLE
Bad result for 5 or more service implementations of interface

### ISSUE THREAD

**Issue by billybraga** [dotnet/runtime#54407]
### Description

See [simple repro repo](https://github.com/billybraga/DotnetEnumerableServiceBug/blob/main/DotnetEnumerableServiceBug/Program.cs).

Basically, in dotnet 6 preview5, getting IEnumerable<> service (to get all implementations) is broken if service provider validates on build because slots are not always determined the same way and the validate step builds call site cache differently.

This snippet will throw:

```csharp
var services = new ServiceCollection();
services.AddSingleton<ICustomService, CustomService1>();
services.AddSingleton<ICustomService, CustomService2>();
services.AddSingleton<ICustomService, CustomService3>();
services.AddSingleton<ICustomService, CustomService4>();
services.AddSingleton<ICustomService, CustomService5>();
var serviceProvider = services.BuildServiceProvider(
    new ServiceProviderOptions
    {
        ValidateOnBuild = true
    }
);
var customServices = serviceProvider
    .GetService<IEnumerable<ICustomService>>()
    .ToArray()
// Index 1 should be CustomService2 but instead we get 5
if (customServices[1] is CustomService5 && customServices[4] is CustomService5)
{
    throw new Exception(
        "This is not right"
    );
}
```

### Configuration

dotnet 6 preview 5.21301.5

### Regression?

Yes

### Other information

I think this is the code that caused the bug : https://github.com/dotnet/runtime/commit/bb2d2c45410b9407a9657df7f5ca113bced53a43#diff-12fe7d127bc25efffaedd4b50d0b12792aa7c236e855d782c127424fa2f9dbb0

The problem is maybe that `descriptors.GetSlot()` should be used here : https://github.com/dotnet/runtime/blob/v6.0.0-preview.5.21301.5/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CallSiteFactory.cs#L176

**Comment by davidfowl** [comment]
Thanks! I'll take a look.

**Comment by billybraga** [comment]
I forgot to specify that without `ValidateOnBuild` it seems to work fine, since that call sites aren`t cached before executing `TryCreateEnumerable`. But when `ValidateOnBuild` is true, the validation phase primes the call site cache with slot values using `ServiceDescriptorCacheItem.GetSlot()`, and then `TryCreateEnumerable` uses `int slot = descriptors.Count - i - 1` which doesn't produce that same values.

**Comment by davidfowl** [comment]
And this only repros with 5 or more instances?

**Comment by billybraga** [comment]
5 or more. Below that there are cache misses, but all the services seem ok.

**Comment by davidfowl** [comment]
OK I'm gonna try to get this fixed in preview6

**Comment by NinoFloris** [comment]
I was just starting to debug the same thing. In our case this surfaced as `HostBuilder` calling one of our `IStartupFilters` twice and another never causing NREs due to dependencies on the latter one.

Tracked it down to the point where `CallSiteFactory.TryCreateExact` would return a different implementation type than the descriptor stated, indeed due to something else being cached in the same slot already. 😅

Happy to see the fix is up, I'll pin the version to preview 4 for now.

**Comment by davidfowl** [comment]
Better workaround is to disable ValidateOnBuild

**Comment by davidfowl** [comment]
Here's an update to the known issues list with a workaround https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#net-runtime
