### ISSUE TITLE
System.Diagnostics.PerformanceCounter written perfcounters is not working in linux

### ISSUE THREAD

**Issue by sachin-agarwal-by** [dotnet/runtime#54415]
I want to use System.Diagnostics.PerformanceCounter for kuberentes pods which is in linux but seems its not working any idea

**Comment by gfoidl** [comment]
They are Windows-only. 
Have a look at [What diagnostic tools are available in .NET Core? / Metrics](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/#metrics)

**Comment by danmoseley** [comment]
Closing as this is answered thanks @gfoidl 

@sachin-agarwal-by let us know if you have more questions.

**Comment by jkotas** [comment]
Do we need to get System.Diagnostics.PerformanceCounter annotate as Windows-specific? I just tried to reference System.Diagnostics.PerformanceCounter on Linux in .NET 6 and got no warnings about it being supported on Windows only.

**Comment by jkotas** [comment]
Sorry for false alarm. I must have forgotten to save the file or something. I see the warning as expected: 
```
C:\repro\Program.cs(9,31): warning CA1416: This call site is reachable on all platforms. 'PerformanceCounter' is only supported on: 'windows'. [C:\repro\repro.csproj]
```

**Comment by sachin-agarwal-by** [comment]
Thanks for ur suggestion But the way we uses System.Diagnostics.PerformanceCounter in .net code to find the cpu and memory usage once this code will deploy to azure kubernetes pod which will be running in linux then this code will never work so dont we have something which I can write as a code to find cpu and memory useage from percounter and same code work when this deployed to pods?

**Comment by jkotas** [comment]
Take a look at `System.Diagnostic.Process.TotalProcessorTime` and similar properties.

**Comment by sachin-agarwal-by** [comment]
But will it give the entire PC CPU and Memory usage as PerfCounter provides ?

**Comment by jkotas** [comment]
It will only give you the CPU and Memory usage of the current process. We do not have cross-platform APIs that return CPU and Memory usage of the whole machine.

**Comment by danmoseley** [comment]
I thought we had a proposal for this, but it was for hardware not counters: https://github.com/dotnet/runtime/issues/22948. Arguably, it could be a 3rd party library - perhaps there is one.

**Comment by sachin-agarwal-by** [comment]
@danmoseley can you please  share any third party which can achieve this.

**Comment by danmoseley** [comment]
@sachin-agarwal-by I do not know of one: perhaps searching Nuget and GitHub might find one. Please share here if you do.
