### ISSUE TITLE
Paths ending on "0x00A0 NO-BREAK SPACE" character are trimmed in DirectoryInfo

### ISSUE THREAD

**Issue by pp111** [dotnet/runtime#54419]
### Description

Windows allows folder names ending on "0x00A0 NO-BREAK SPACE" character, however in .NET the folder name is trimmed.
To reproduce it, create a folder inside E:\Test with just that character on the name (Pressing ALT, and input 0160, then leave ALT key), like the following:
"E:\Test\ "

Run this code:

```
string path = @"E:\Test"; //base folder, must be empty for this example
DirectoryInfo directory = new DirectoryInfo(path);
var directories = directory.GetDirectories();
var subdir = new DirectoryInfo(directories[0].FullName); //this will get the subfolder with the weird name
System.Diagnostics.Debug.Assert(subdir.FullName == directories[0].FullName, "Directory name was trimmed!!!");

```

Long paths must be enabled.

### Configuration
.NET Framework 4.8
Windows 10 20H2

### Regression?
A similar bug was reported (and fixed?) here:
https://github.com/dotnet/runtime/issues/22309

### Other information
It seems that the error is raised regardless of the Switch.System.IO.UseLegacyPathHandling value.

**Comment by vcsjones** [comment]
> .NET Framework 4.8

I can reproduce this in .NET Framework, but I cannot reproduce this in .NET 5 or .NET Core 3.1.

**Comment by adamsitnik** [comment]
> I can reproduce this in .NET Framework, but I cannot reproduce this in .NET 5 or .NET Core 3.1.

@carlossanlop do you have any suspicions on what could be causing that?

**Comment by pp111** [comment]
In System.IO.PathInternal.cs there is a list of characters that will be trimmed:

`internal static readonly char[] s_trimEndChars =
        {
            (char)0x9,          // Horizontal tab
            (char)0xA,          // Line feed
            (char)0xB,          // Vertical tab
            (char)0xC,          // Form feed
            (char)0xD,          // Carriage return
            (char)0x20,         // Space
            (char)0x85,         // Next line
            (char)0xA0          // Non breaking space
        };`

Maybe (char)0xA0 should not be there?

**Comment by adamsitnik** [comment]
I've tried to repro using it latest .NET 6 using the following test:

```cs
[Fact]
public void NonBreakingSpaceIsSupported()
{
    string emptyFolder = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
    DirectoryInfo rootFolder = new(emptyFolder);
    Assert.False(rootFolder.Exists);

    try
    {
        rootFolder.Create();

        string nameWithNonBreakingSpace = new string((char)0xA0, 1);
        DirectoryInfo subdirectory = rootFolder.CreateSubdirectory(nameWithNonBreakingSpace);

        Assert.Equal(nameWithNonBreakingSpace, subdirectory.Name);
        Assert.Equal(nameWithNonBreakingSpace, rootFolder.GetDirectories().Single().Name);
        Assert.Equal(Path.Combine(rootFolder.FullName, nameWithNonBreakingSpace), subdirectory.FullName);
        Assert.Equal(Path.Combine(rootFolder.FullName, nameWithNonBreakingSpace), rootFolder.GetDirectories().Single().FullName);
    }
    finally
    {
        if (rootFolder.Exists)
        {
            rootFolder.Delete(recursive: true);
        }
    }
}
```

the test has passed, so it's a Full .NET Framework bug. Since it's not a security issue, we are not going to fix it.
