### ISSUE TITLE
Preview 5 has two identical copies of System.Security.Cryptography.Cng.dll

### ISSUE THREAD

**Issue by ericsink** [dotnet/runtime#54427]
In .NET 6 preview 5, there are identical copies of System.​Security.​Cryptography.​Cng.dll in two different targeting packs, one in Microsoft.​NETCore.​App.Ref and another in Microsoft.​AspNetCore.​App.Ref.

I first mentioned this in a Tweet:

https://twitter.com/eric_sink/status/1405727524194242566

to which @davidfowl replied "That sounds like a bug...", so I figured it should be logged, and hopefully this is the right place.

**Comment by dougbu** [comment]
I like one line fixes 😃
