### ISSUE TITLE
Roll forward options and behavior aren't fully documented on docs.microsoft.com

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#54434]
I believe https://github.com/dotnet/runtime/blob/main/docs/design/features/multilevel-sharedfx-lookup.md  is the most complete documentation, but there's nothing on docs.microsoft.com about all the possible settings.

**Comment by vitek-karas** [comment]
The best documentation we have is here https://github.com/dotnet/designs/blob/main/accepted/2019/runtime-binding.md and the technical one is here https://github.com/dotnet/runtime/blob/main/docs/design/features/framework-version-resolution.md. But neither is on docs.

**Comment by vitek-karas** [comment]
This PR https://github.com/dotnet/docs/pull/25039 adds the necessary descriptions I think. So I'll close this in favor of that PR and its tracking issue https://github.com/dotnet/docs/issues/12237.
