### ISSUE TITLE
System.Text.Json source generator does not use globally prefixed namespace for nullable DateTime

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/runtime#54433]
### Description

I tried to use the new source generator in a project with a `MyProject.System` namespace and could not compile because the generated code for a nullable `DateTime?` does not properly use `global::` prefix for the generic parameter in `Nullable<T>`.

**Example code**
```csharp
namespace MyProject.System
{
	public record SomeCode();
}

namespace MyProject.OtherNamespace
{
	public class Subject
	{
		public DateTime? Timestamp { get; set; }
	}

	[JsonSerializable(typeof(Subject))]
	public partial class JsonContext : JsonSerializerContext
	{
	}
}
```

The generated code in `JsonContext.NullableSystemDateTime.g.cs` contains the following two lines which refers to the wrong System namespace.
```csharp
private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Nullable<System.DateTime>> _NullableSystemDateTime;
public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Nullable<System.DateTime>> NullableSystemDateTime
```

Expected generated code that should work would be the following.
```csharp
private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Nullable<global::System.DateTime>> _NullableSystemDateTime;
public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Nullable<global::System.DateTime>> NullableSystemDateTime
```

### Configuration

**dotnet**
6.0.100-preview.5.21302.13

**System.Text.Json**
6.0.0-preview.5.21301.5

### Other information

**Compiler error**
```
1>C:\project-path\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.NullableSystemDateTime.g.cs(8,108,8,116): error CS0234: The type or namespace name 'DateTime' does not exist in the namespace 'MyProject.System' (are you missing an assembly reference?)
1>C:\project-path\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\JsonContext.NullableSystemDateTime.g.cs(7,109,7,117): error CS0234: The type or namespace name 'DateTime' does not exist in the namespace 'MyProject.System' (are you missing an assembly reference?)
```

**Comment by layomia** [comment]
This has been fixed in recent PRs for the source generator. @DavidZidar you can try the fix by adding a package reference to the latest build of System.Text.Json - https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=System.Text.Json&protocolType=NuGet&view=versions. Please let us know if you have further issues using the source generator.

**Comment by DavidZidar** [comment]
@layomia Just tried it, seems to be working, thanks!
