### ISSUE TITLE
.NET 6 SDK Preview 5 TrimMode has no effect

### ISSUE THREAD

**Issue by tomrus88** [dotnet/runtime#54445]
### Description
I've tested publishing default WinForms app template with latest .NET 6 SDK Preview 5 with following command lines:
`dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=Link`
`dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=CopyUsed`
`dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:TrimMode=Copy`
and all of them produce exact same output (identical size), this doesn't seems to be intended...

### Configuration
.NET 6 SDK Preview 5
Windows 10 x64

**Comment by Symbai** [comment]
[Winforms and WPF doesn't support trimming](https://github.com/dotnet/runtime/issues/52113#issuecomment-830473998) (although trimming unofficially worked in some scenarios before) and I believe they disabled it in latest SDK version for both.

**Comment by tomrus88** [comment]
You can workaround missing types etc my adding TrimmerRootAssembly or TrimmerRootDescriptor directives into project file, so I don't see why they would completely disable trimming for WinForms/WPF...

And if it's indeed completely disabled, it should at least say so when you publish... Like "PublishTrimmed/TrimMode options were ignored because..."

**Comment by alexrp** [comment]
[You should be getting such warnings](https://github.com/dotnet/sdk/blob/fa1d9c437b87edfc5643c96c67833d415e007967/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L114-L117):

```xml
    <NetSdkWarning Condition="'$(UseWindowsForms)' == 'true' and '$(PublishTrimmed)' == 'true'"
                 ResourceName="TrimmingWindowsFormsIsNotSupported" />
    <NetSdkWarning Condition="'$(UseWpf)' == 'true' and '$(PublishTrimmed)' == 'true'"
                 ResourceName="TrimmingWpfIsNotSupported" />
```

**Comment by tomrus88** [comment]
Yes there's a warnings, but they don't imply that settings I pass have no effect. Also how do I restore old pre .NET 6.0 behavior?

**Comment by agocke** [comment]
As mentioned, trimming WinForms is unsupported and not likely to work.

TrimMode not being included in the up-to-date check does look like a bug, filed here: https://github.com/mono/linker/issues/2102
