### ISSUE TITLE
[JIT] Casting System.Func lacks quick inlined check

### ISSUE THREAD

**Issue by omariom** [dotnet/runtime#54452]
For `Cast1` JIT [doesn't generate inlined check](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKDIAIBhOmgbxro7uIFYAeASwB2GNHSEYAfIzwZyACgjAAVjDAY6ipQEo6AXilyeA4aPEStmgNw12nAGIQIxkWOFSGM0guWr1mnfp0cg5O4qZuFsrW1JzMMZwMAK64GBD4PNIpAMzeKmoaygEGSSlpPJFK0bG2HCWp+ADiMIIwUPxgRmGukpkYKLm+Bdp6xcn1TS1tHXxdZhXRAL42tFlcpHQhvAAq5KJbpFIsS9Q0xKsAJjAANjAA5tgYMN2MY2XccuJiWtGnF9d3DyeWwASjBcIkruo6mkJq12kYtntQeDIRI5FsvtEgA==).

```C#
using System;
class C 
{
    Func<int, int> Cast1(object obj) => (Func<int, int>)obj;

    Foo<int, int> Cast2(object obj) => (Foo<int, int>)obj;
    
    CustomFunc Cast3(object obj) => (CustomFunc)obj;
    
    CustomGenericFunc<int, int> Cast4(object obj) => (CustomGenericFunc<int, int>)obj;
}

public class Foo<T1, T2> {}

public delegate int CustomFunc(int i);

public delegate TResult CustomGenericFunc<T, TResult>(T i);
```

category:cq
theme:inlining
skill-level:intermediate
cost:medium
impact:small

**Comment by omariom** [comment]
[The same](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNMgyEMaAbxoNjDXjx14M5ABQRgAKxhgMDO/YCURk4eom/DBWwoBgAzBgBeVwcGPCYAVgAeMww0Ux4APg1ff2NiAHZQ01wGLggXLg5JSQYAflDrcncGEAYAZiy/AF8vYx60lyFLVtsHJxc3T2zjHxzjQOCwyLcY4qEOXAxRYjiO2fzC3mLS8srqupCGppb2vu6pvXvkiw2UEcdnKI8+mdn5wqXorE1htRABxGBcGTKbZJHipZKZPp+fZhQ4lMolU61eqNZptXbGO53LStBgAExg0gA5tgMDB+jp1pt8NtrE9eO4siTyZSYDS6QwACpsVSVAZMsEQqFgGGC1LC0WSDDpayC0ycmhAA===) for `isinst`

**Comment by jfd16** [comment]
The issue here is that the `HasVariance` check does not take into account that no variance is possible because all type arguments at variant positions are value types.

It is safe under these conditions to consider an instance of a variant generic type as invariant (at least as the target type of castclass/isinst):
* All type arguments at covariant positions are sealed types (including value types).
* All type arguments at contravariant positions are value types or `System.Object`.

**Comment by JulieLeeMSFT** [comment]
CC @kunalspathak for casting and @EgorBo for inlining.

**Comment by EgorBo** [comment]
Codegen for `Cast1` in .NET 9.0:

```asm
; Method C:Cast1(System.Object):System.Func`2[int,int]:this (FullOpts)
G_M16451_IG01:  ;; offset=0x0000
       sub      rsp, 40
						;; size=4 bbWeight=1 PerfScore 0.25

G_M16451_IG02:  ;; offset=0x0004
       mov      rax, rdx
       test     rax, rax
       je       SHORT G_M16451_IG05
						;; size=8 bbWeight=1 PerfScore 1.50

G_M16451_IG03:  ;; offset=0x000C
       mov      rcx, 0x7FFB5C1BAE78      ; System.Func`2[int,int]
       cmp      qword ptr [rax], rcx
       je       SHORT G_M16451_IG05
						;; size=15 bbWeight=0.50 PerfScore 2.12

G_M16451_IG04:  ;; offset=0x001B
       call     CORINFO_HELP_CHKCASTANY
						;; size=5 bbWeight=0.25 PerfScore 0.25

G_M16451_IG05:  ;; offset=0x0020
       nop      
						;; size=1 bbWeight=1 PerfScore 0.25

G_M16451_IG06:  ;; offset=0x0021
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25
; Total bytes of code: 38
```
