### ISSUE TITLE
LdapConnection BeginSendRequest does not provide information requested through the DirectoryControl

### ISSUE THREAD

**Issue by klettier** [dotnet/runtime#54464]
### Description

I'm interested in getting information related to deleted Users from attribute **member** of **Group** in Active Directory but even if I'm able to retrieve the needed information from unary request I'm facing an issue when being notified of the change.

When executing the request from LDP or from C# code using **SearchRequest** (System.DirectoryServices.Protocols) with the right controls, in this case **LDAP_SERVER_SHOW_DEACTIVATED_LINK_OID** I'm able to get the requested information.

![image](https://user-images.githubusercontent.com/3425823/122684424-9320c580-d205-11eb-9b2d-30bcc3a7628a.png)

But when I'm using **BeginSendRequestAsync** to be notified of the change with again the right controls I'm unable to see in **member** attribute the deleted users.

Is this a know limitation of the notification API ?

### Configuration

* net5.0-windows
* Windows server 2019
* x64 architecture 

### Regression?

I don't know if this is supported

### Other information

* No workaround

**Comment by joperezr** [comment]
Hello @klettier thanks for your submission. Do you mind sharing a snippet of how you are trying to perform the search and initializing the controls? Also, are you running your code on Windows or Linux? I agree with you that if it works with ldp.exe it should work as well with S.DS.P SearchRequest.
