### ISSUE TITLE
Unnecessary array allocations in RuntimeTypeCache

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#5446]
Was profiling some code using `dynamic` just now when I saw `RuntimeTypeCache` come up in the profiler. I decided to take a look into its sources, and it looks like there are indeed many places where it could be improved perf-wise (although not all of them relate to my code). For example:
- [This](https://github.com/dotnet/coreclr/blob/aedfba00f7977b2c00022df74d1bbe03e73260c8/src/mscorlib/src/System/RtType.cs#L297) looks less than optimal, since we're creating a temporary 1-element array and immediately returning its first element. (Unfortunately, it looks a tad hard to refactor, since it's taken as a ref parameter before being returned.)
- I also have a suspicion that [this](https://github.com/dotnet/coreclr/blob/aedfba00f7977b2c00022df74d1bbe03e73260c8/src/mscorlib/src/System/RtType.cs#L126) might be causing more allocations than necessary, since it always returns a new array even though the `ListBuilder<T>.ToArray()` method is only called internally.

There are probably some other places that could be sped up, too, but I won't write them all down here. Raising this issue as a self-reminder in case I get time to work on this later, but anyone who wants to is welcome to take this up too.

**Comment by steveharter** [comment]
Closing due to age; also the "dynamic" feature is not intended to be performant.
