### ISSUE TITLE
Should CodePageDataItem be a struct?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#5447]
The [`CodePageDataItem`](https://github.com/dotnet/coreclr/blob/43b39a73cbf832ec13ec29ed356cb75834e7a8d7/src/mscorlib/src/System/Globalization/EncodingDataItem.Unix.cs#L8) class looks like it would be a good candidate for a struct; it's immutable and used in a [bunch](https://github.com/dotnet/coreclr/search?utf8=%E2%9C%93&q=CodePageDataItem) of different places throughout the repo. Not sure if this would present any issues with serialization/reflection though, and also the class is used in at least 3 different native code files.

**Comment by GrabYourPitchforks** [comment]
Tarek, is this worth doing? We might only create a small handful of these ever, and since they're involved in `Interlocked.CompareExchange` we might not be able to use structs anyway.

**Comment by tarekgh** [comment]
This is not worth it to do as it is currently used only 8 encodings we support by default and we cache them anyway. so the current cost is really negligible.
