### ISSUE TITLE
Throws an exception when opening an existing file

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/runtime#54474]
## Repro Steps
1.	Create NET Core console application
2.	Open Program.cs, add below code for Main method (\\\winformtest\WinFormsRuntime\Libs\WFCTestLib\Util\Images\class.ico is an existing icon.)
```
            String fileName = @"\\winformtest\WinFormsRuntime\Libs\WFCTestLib\Util\Images\class.ico";
            // String fileName = @"C:\Users\v-qiashi\Desktop\Images\test.ico";

            Stream fs = File.Open(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
            Icon ico = new Icon(fs);
            fs.Close();
```
3.	Build and run
## Actual result
Throw System.IO.IOException.
![image](https://user-images.githubusercontent.com/54019172/122734224-78575b00-d2b0-11eb-8130-c671bda85473.png)

## .NET Core Version
.NET 6.0.100-preview.7.21320.2

# Regression? 

Yes, this is a regression issue, it cannot repro on .Net 6.0.100-preview.6.21315.23.

# More info 
This issue not occurs when setting fileName to a local path, like:
` String fileName = @"C:\Users\v-qiashi\Desktop\Images\test.ico";`

**Comment by adamsitnik** [comment]
@Lydia-Shi big thanks for a very detailed bug report, I am going to fix it asap

**Comment by Lydia-Shi** [comment]
This issue has been fixed on .NET SDK latest build 6.0.100-preview.7.21324.6.

**Comment by adamsitnik** [comment]
@Lydia-Shi big thanks for confirmation! and appologies for the bug. I've added tests in #54483 to ensure the bug is never coming back
