### ISSUE TITLE
A System.NullReferenceException was throwing when get a **gif** image using Image.FromFile() method

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/runtime#54475]
### Description
A System.NullReferenceException was throwing when get a **gif** image using Image.FromFile() method.
[CallStack.txt](https://github.com/dotnet/winforms/files/6685418/CallStack.txt)

**Expected behavior:**
The **gif** image should get using Image.FromFile() method correctly.

**Minimal repro:**
1. Create a WinForms .NET core project targeting .NET 6.0
2. Add following code to the structure method of Form1
`Image.FromFile(@"\\ServerName\Images\animated.gif");`
Below is the animated.gif file:
![animated](https://user-images.githubusercontent.com/62929087/122738796-e43bc280-d2b4-11eb-838a-c9b8d7b1f05a.gif)
3. Build and run the project

### Configuration
.NET SDK 6.0.100-preview.7.21320.4

### Regression?
Yes, this is a regression issue.

### Other information
 This issue doesn't repro when file was saved on a local path

**Comment by jkotas** [comment]
Note: This issue doesn't repro when file was saved on a local path

cc @adamsitnik

**Comment by adamsitnik** [comment]
It's a bug that I've introduced in #53669. I've sent a fix in #54483

**Comment by safern** [comment]
@adamsitnik since this was a regression, are you going to port this to Preview6 branch?

**Comment by adamsitnik** [comment]
> since this was a regression, are you going to port this to Preview6 branch?

We should definitely do that. Do we have some nice bot for that?

**Comment by Amy-Li03** [comment]
This issue has been fixed on .NET SDK latest build 6.0.100-preview.7.21324.6
