### ISSUE TITLE
Add Mariner Linux distro to CI validation

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54478]
Leadership asked us to validate against Mariner in our CI matrix. There are containers available that could be used and afaik @MattGal already ran our test suite on it and found just one single failing test.

`mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620)`

@danmoseley do we want to run this for every PR or just for every rolling build on main?

@safern or @hoyosjs could you please help with adding the distro to our CI matrix?

**Comment by ViktorHofer** [comment]
cc @hoyosjs

**Comment by danmoseley** [comment]
> @danmoseley do we want to run this for every PR or just for every rolling build on main?

We can assume that there will (very?) rarely be Mariner specific failures. So rolling build is fine. (In future, perhaps we will have configurations that we run even less often that rolling builds.)

**Comment by safern** [comment]
I guess since this is a Linux distro we can just add a helix queue to the Linux test flavors? The Linux portable build should work just fine?

**Comment by MattGal** [comment]
> I guess since this is a Linux distro we can just add a helix queue to the Linux test flavors? The Linux portable build should work just fine?

Yes, I reused a job list from one of your portable runs in the test run I did, no special build or anything.

**Comment by safern** [comment]
Sounds good. So this should be simple to add. I'll take care of this.

**Comment by ViktorHofer** [comment]
@safern any update on this? We would like to have this in place for 6.0.

**Comment by safern** [comment]
Oops, I missed this. I'll put up a PR either today or tomorrow.
