### ISSUE TITLE
Transient CFData in Interop.AppleCrypto.X509GetRawData isn't being disposed

### ISSUE THREAD

**Issue by odhanson** [dotnet/runtime#54489]
Interop.AppleCrypto.X509GetRawData makes a call to AppleCryptoNative_X509GetRawData which will result in a reference to a CFData.

This object is never disposed, albeit at some point its finalizer would be called, it's better to dispose it immediately.

**Comment by bartonjs** [comment]
I already updated the title of the PR, but I'll just comment here: There's no memory leak, or potential memory leak.  A leak means it's not being tracked and will never be freed.

That said, disposing in a timely manner is goodness both for memory usage and for avoiding finalizations.

**Comment by odhanson** [comment]
> I already updated the title of the PR, but I'll just comment here: There's no memory leak, or potential memory leak. A leak means it's not being tracked and will never be freed.
> 
> That said, disposing in a timely manner is goodness both for memory usage and for avoiding finalizations.

Thanks. I mentioned that in the description, but agree that the title was poorly chosen. Thanks for fixing it
