### ISSUE TITLE
Blazor globalization inconsistency between WASM and Server

### ISSUE THREAD

**Issue by guardrex** [dotnet/runtime#54486]
### Describe the bug

Working on updates to the Blazor Glob/Loc topic on https://github.com/dotnet/AspNetCore.Docs/pull/22525. cc: @hishamco 

Either I've hit a bug or a personal knowledge gap: Globalization of a number isn't consistent across Blazor Server and Blazor WebAssembly. 
* If a **_knowledge gap_** that I have, then I'll address this behavior in the topic's updates.
* If a **_bug_**, then *here it is*.

#### Blazor WebAssembly (✔️ **_Working-as-expected Case_**)

1. Create a new Blazor WebAssembly app from the project template.

1. Add `CultureExample1` component to the app's `Pages` folder:

   ```razor
   @page "/culture-example-1"
   @using System.Globalization
   @using System.Threading

   <h1>Culture Example 1</h1>

   <!-- 
       Updated code here, but screenshot is this comment will be left as-is.
       I'll add a screenshot of this output at the end of this issue.
   -->
   <ul>
       <li><b>CultureInfo.CurrentCulture</b>: @CultureInfo.CurrentCulture</li>
       <li><b>CultureInfo.CurrentUICulture</b>: @CultureInfo.CurrentUICulture</li>
       <li><b>Thread.CurrentThread.CurrentCulture</b>: @Thread.CurrentThread.CurrentCulture</li>
       <li><b>Thread.CurrentThread.CurrentUICulture</b>: @Thread.CurrentThread.CurrentUICulture</li>
   </ul>

   <h2>Rendered values</h2>

   <ul>
       <li><b>Date</b>: @dt</li>
       <li><b>number</b>: @number.ToString("N2")</li>
   </ul>

   @code {
       private DateTime dt = DateTime.Now;
       private double number = 1999.69;
   }
   ```

1. Run the app. Use a browser with Peruvian Spanish (`es-PE`) as the first language choice:

   <img width="526" alt="Capture1" src="https://user-images.githubusercontent.com/1622880/122559464-fa235c00-d004-11eb-99cd-e4be31d7ece0.PNG">

   The date **_AND number_** are globalized (i.e., in Spanish: date is day-month format + 24-hour clock & number has a comma decimal and period separator). ✔️ *All good.* ✔️

#### Blazor Server (❌ **_Inconsistent/Not-working-as-expected Case_**)

1. Create a new Blazor Server app from the project template.

1. Add loc services:

   ```csharp
   services.AddLocalization();
   ```

1. Add loc middleware to the pipeline immediately after Routing Middleware:

   ```csharp
   app.UseRequestLocalization(new RequestLocalizationOptions()
       .AddSupportedCultures(new[] { "en-US", "es-PE" })
       .AddSupportedUICultures(new[] { "en-US", "es-PE" }));
   ```

1. Add the same `CultureExample1` component :point_up: to the app's `Pages` folder.

1. Run the app. Use a browser with Peruvian Spanish (`es-PE`) as the first language choice:

  <img width="526" alt="Capture" src="https://user-images.githubusercontent.com/1622880/122561540-9a7a8000-d007-11eb-8ddf-11807f684bc9.PNG">

   The date is globalized ✔️, **_BUT the number isn't_** ❌ (i.e., the number doesn't have a comma decimal and period separator).

   Is this the expected outcome, or is this a 🐞? If expected behavior, why? ... because I'll need to address this delta in the doc.

### Exceptions (if any)

**_None_**

### Further technical details

- ASP.NET Core version

  **5.0.6**

- Include the output of `dotnet --info`

  ```
  .NET SDK (reflecting any global.json):
   Version:   5.0.300
   Commit:    2e0c8c940e

  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19043
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

  Host (useful for support):
    Version: 5.0.6
    Commit:  478b2f8c0e

  .NET SDKs installed:
    3.1.302 [C:\Program Files\dotnet\sdk]
    5.0.202 [C:\Program Files\dotnet\sdk]
    5.0.300 [C:\Program Files\dotnet\sdk]

  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

  **Visual Studio 16.10.0**

**Comment by hishamco** [comment]
Seems the issue was a runtime one :(

**Comment by tarekgh** [comment]
The server format is correct per Unicode standard. You may look at:

https://github.com/unicode-org/cldr/blob/829d6d3d911dbf032a118c3834737445292dc3e8/common/main/es.xml#L5805
https://github.com/unicode-org/cldr/blob/829d6d3d911dbf032a118c3834737445292dc3e8/common/main/es_PE.xml#L292

If you think this is incorrect in the standard, you can file a ticket to CLDR http://cldr.unicode.org/index/bug-reports.

**Comment by tarekgh** [comment]
I am keeping this issue open to let WASM team decide if need to change anything in the client.

**Comment by guardrex** [comment]
Thanks @tarekgh ... I wasn't aware of that (obviously lol). Now that I've researched it further, I see that Spanish is split on the format and that Peru is one of the ones with an English-like format for numbers. 

Indeed, the Blazor WebAssembly app then goes the other way and is perhaps a problem here. It's number format is a comma decimal and period number separator AFAICT.

**Comment by guardrex** [comment]
@javiercn ... I think I can go ahead and merge the Blazor docs loc PR. Currently, it seems like WASM is incorrect on the number format, but we usually don't document bugs that are undergoing fixes, especially for patch releases that will be backported ... if that's what will happen for this.

**Comment by radical** [comment]
Moving this to 8.0 milestone. Feel free to change, if anyone is planning to land a fix for this in 7.0 .

**Comment by pavelsavara** [comment]
cc @ilonatommy

**Comment by hishamco** [comment]
@guardrex what's the status of this one?

**Comment by ilonatommy** [comment]
> cc @ilonatommy

Thank you, I will check it. At the fist look it seems kind of logical. We are reducing globalization data loaded to the app as much as possible and we are not loading data for "es-PE" at all. The only Spanish locales we are supporting are: "es_419", "es_ES", "es_MX". Supported locales in WASM can be checked here for browser:
https://github.com/dotnet/icu/blob/cb39ef7979da97c65ee27a626eb83b0290216298/icu-filters/icudt_browser.json#L129
and here for mobiles:
https://github.com/dotnet/icu/blob/dotnet/main/icu-filters/icudt_mobile.json.

**Comment by guardrex** [comment]
@hishamco ... *Investigation phase*. I solved it for the Blazor glob/loc doc by avoiding the problematic locale for the demonstration in the doc. We good on that, as I don't intend to change anything even if inconsistencies are resolved. What I'll do tho if inconsistencies aren't resolved is add something to the doc to explain why locales might be different between Blazor Server and Blazor WASM. I'm 👀 on here for what I can tell folks if ultimately behavior is deemed ***by-design***/***won't-fix***.

**Comment by ilonatommy** [comment]
Sorry for the delay, the situation is following:

Expected number format for "es-ES": 1.234,5 (reference: Console Application)
Expected number format for "es-PE: 1,234.5

Blazor WASM is not using full set of locales in contrast to Blazor Server. We have a reduced list of locales that I quoted in the previous reply. As "es-PE" is not on the list, Blazor WASM is using a fallback to "es-ES" instead.

After adding "es-PE" to ICU locale set the result is as expected:
![image](https://user-images.githubusercontent.com/32700855/216280712-e9efa777-5b61-467c-b2e5-cc73dae903f3.png)

We are thinking about ICU customization for such situations when the application requires less frequently used locales but it is in a prototype phase only. For today I can offer you a temporary fix, same as here: https://github.com/dotnet/runtime/issues/53239#issuecomment-1358010791
I can share the custom version of ICU files that have "es-PE" added with @hishamco and you could replace the officially shipped ones. What do you think about it?

**Comment by guardrex** [comment]
@ilonatommy ... I see what you were working on with #33895, but you're saying that Blazor WASM has a subset of locales, thus that Blazor WASM might not localize correctly due to a missing locale on the client. ***However***, my issue here is that it was ***Blazor Server*** that wasn't behaving as expected. See my opening remarks :point_up:. If you'd like me to check again, let me know, and I'll run another pair of tests to see if it still repros here.

**Comment by ilonatommy** [comment]
> _**However**_, my issue here is that it was _**Blazor Server**_ that wasn't behaving as expected. See my opening remarks ☝️. 

I understand that you opened the issue with the intention to report Blazro Server's incorrect behavior but after the discussion and @tarekgh's research, it was figured out it is the other way around. See: https://github.com/dotnet/runtime/issues/54486#issuecomment-865206478

The issue was left opened to continue solving it on WASM side - if Server is in line with Unicode standard and is not the same as WASM then it means something is wrong with WASM. Did I missunderstand something?

**Comment by guardrex** [comment]
My bad, @ilonatommy ... I forgot what happened. I opened this back in 2021, and I should've reviewed the follow-up remarks.

Is it possible for a dev to add a locale to a Blazor WebAssembly app? I suppose it would be a good idea to let devs know in the Blazor glob+loc article if they can (and how) or if that's unsupported.

**Comment by ilonatommy** [comment]
Right now it is not supported but we are considering this option in https://github.com/dotnet/runtime/pull/80421. In the current state we do have a workaround, mentioned here: https://github.com/dotnet/runtime/issues/54486#issuecomment-1413391747 but it is not a perfect solution and I do not consider it an official fix - that's why it is not in the documentation. Once we support custom ICU loading the docs on that will be added to the runtime repo, as in the PR.

**Comment by guardrex** [comment]
This is what happens on *one cup* of ☕ in the morning! I think it takes ***three cups*** to get going these days! 🙈

I'll remark that adding locales isn't currently supported and maintain a tracking entry to check back later on custom ICU loading so that if/when that becomes available I can work it into a future version of the article. Thanks for bearing with me.

*NOW!* ... ***More*** ☕☕☕ ***PLZ!*** 🤣

**Comment by ilonatommy** [comment]
> I'll remark that adding locales isn't currently supported and maintain a tracking entry to check back later on custom ICU loading so that if/when that becomes available I can work it into a future version of the article. 

Good idea, thank you for taking care of that. And no worries, the issue was indeed confusing. I am closing at this stage because it seems clear what is going on.
