### ISSUE TITLE
IServiceProvider returns invalid IOptions instance in case of multiple independent appsettings.json files

### ISSUE THREAD

**Issue by f-i-x-7** [dotnet/runtime#54509]
### Description

Repro is available [here](https://github.com/f-i-x-7/ReproduceServiceProviderIssueInTests)

It uses .NET Core 3.1 + Microsoft.Extensions.* 3.1.13 because it is configuration of real app where I encountered this issue. However, it also reproduces with .NET Core 3.1 + Microsoft.Extensions.* 3.1.16 (lates 3.1.* version of Microsoft.Extensions.* as of now) as well as with .NET 5.0 + Microsoft.Extensions.* 5.0.0.

Repro is rather small,  so I copy-paste its code to this issue:

```c#
    public sealed class FooOptions : IOptions<FooOptions>
    {
        private static readonly Dictionary<string, string> EmptyDict = new Dictionary<string, string>(0);

        public IDictionary<string, string> KeyValuePairs { get; set; } = EmptyDict;

        FooOptions IOptions<FooOptions>.Value => this;
    }

    public sealed class Foo
    {
        private readonly FooOptions _options;

        public Foo(IOptions<FooOptions> options)
        {
            _options = options?.Value ?? throw new ArgumentNullException(nameof(options));
        }

        public int OptionsCount => _options.KeyValuePairs.Count;
    }

    public class FooOptionsTest
    {
        private readonly FooOptions defaultOptions;
        private readonly IConfiguration defaultConfig;

        public FooOptionsTest()
        {
            (defaultOptions, defaultConfig) = GetOptionsAndConfig("appsettings.Default.json");
        }

        [Fact]
        public void TestWithDefaultOptions()
        {
            var foo = CreateFoo();

            Assert.Equal("Value1", defaultConfig["FooOptions:KeyValuePairs:Prop1"]); // OK
            Assert.Equal("Value2", defaultConfig["FooOptions:KeyValuePairs:Prop2"]); // OK
            Assert.Null(defaultConfig["FooOptions:KeyValuePairs:Prop3"]); // OK
            Assert.Equal(2, foo.OptionsCount); // fails, count == 3
        }

        [Fact]
        public void TestWithCustomOptions()
        {
            var (customOptions, customConfig) = GetOptionsAndConfig("appsettings.Custom.json");
            var foo = CreateFoo(customOptions);

            Assert.Null(customConfig["FooOptions:KeyValuePairs:Prop1"]); // OK
            Assert.Null(customConfig["FooOptions:KeyValuePairs:Prop2"]); // OK
            Assert.Equal("Value3", customConfig["FooOptions:KeyValuePairs:Prop3"]); // OK
            Assert.Equal(1, foo.OptionsCount); // fails, count == 3
        }

        private Foo CreateFoo(FooOptions? customOptions = null) => new Foo(customOptions ?? defaultOptions);

        private static (FooOptions, IConfiguration) GetOptionsAndConfig(string configFile)
        {
            var builder = new ConfigurationBuilder()
                .AddJsonFile(configFile);

            var config = builder
                .Build();

            var services = new ServiceCollection();
            services.Configure<FooOptions>(config.GetSection("FooOptions"));

            using (var serviceProvider = services.BuildServiceProvider())
            {
                return (serviceProvider.GetRequiredService<IOptions<FooOptions>>().Value, config);
            }
        }
    }
```

appsettings.Default.json:
```
{
  "FooOptions": {
    "KeyValuePairs": {
      "Prop1": "Value1",
      "Prop2": "Value2"
    }
  }
}
```

appsettings.Custom.json:
```
{
  "FooOptions": {
    "KeyValuePairs": {
      "Prop3":  "Value3"
    }
  }
}
```

Both appsettings files are independent, and they are parsed using independent instances of all involved objects (IConfigurationBuilder, IConfiguration, ServiceCollection, IServiceProvider) so I expected that result Options class will not contain merged KeyValuePairs. Also note that direct access to IConfiguration instances works fine, so I believe this is issue in Microsoft.Extensions.DependencyInjection and/or Microsoft.Extensions.Options.ConfigurationExtensions rather than in Microsoft.Extensions.Configuration.

### Configuration
This is configuration of machine where repro was created.

dotnet --list-runtimes:

Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Part of output of the systeminfo command:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1596 Mhz

### Regression?

Don't know, I did not check the behavior in earlier versions of Microsoft.Extensions.* and/or earlier versions of .NET Core.

### Other information
If only TestWithDefaultOptions is run then test succeeds. Seems like in my case when all tests are run then actually TestWithDefaultOptions is run first, and its usage of 2 appsettings files spoils registrations inside ServiceProvider or smth like that.

**Comment by wzchua** [comment]
your test is loading `"appsettings.Default.json"` in its constructor. This adds its entries into the static dictionary you assigned to the property.

**Comment by f-i-x-7** [comment]
> your test is loading `"appsettings.Default.json"` in its constructor

Yes, this is indented behavior: in real app most of tests use default options and only a couple of tests need custom options from separate file.



> This set its entries into the static dictionary you assigned to the property.
> 
> The binder just calls the setter of the dictionary instance that is already there.

Shouldn't be there separate dictionary instance for each ServiceCollection instance instead of just single static dictionary?

**Comment by wzchua** [comment]
If you initialize with `public IDictionary<string, string> KeyValuePairs { get; set; } = new Dictionary<string, string>();`, there won't be a static instance reference

**Comment by f-i-x-7** [comment]
> If you initialize with `public IDictionary<string, string> KeyValuePairs { get; set; } = new Dictionary<string, string>();`, there won't be a static instance reference

Thanks! I thought that new IOptions<T> creation will create new Dictionary and assign it to property of my options class, so I used static empty dictionary. I'll try suggested code.

**Comment by wzchua** [comment]
If you have an instance set, the binder will use that. You should be able to leave it as null as well.

**Comment by f-i-x-7** [comment]
I confirm that it works with such change:

`public IDictionary<string, string> KeyValuePairs { get; set; } = new Dictionary<string, string>();`

or with such change:

`public IDictionary<string, string> KeyValuePairs { get; set; } = null!;`

So the reasons I've encountered this issue were:
1) Lack of detailed knowledge how binding of IOptions<T> works
2) A passion to 'perfect' code without ` = null!;` and without allocations of new dictionaries that, as I thought because of p.1, will be thrown away anyway

@wzchua, thanks for your help! I will close the issue.
