### ISSUE TITLE
QUIC: Make System.Net.Quic API internal

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#54534]
In .NET 6 we won't be shipping QUIC APIs as public APIs, just HTTP/3 implementation.
We need to make current System.Net.Quic API surface internal only (and share it with ASP.NET team to build their server on top of it)

**Comment by halter73** [comment]
+ @wtgodbe Who I think will be looking at consuming this in ASP.NET

**Comment by ManickaP** [comment]
@wtgodbe The runtime side should be done, I don't know if you want to keep this open until ASP.NET side is done or if you keep track in your own issue?

**Comment by ManickaP** [comment]
Since ASP.NET has they're own issue now, closing.
