### ISSUE TITLE
Make ValueStringBuilder public

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#54535]
Why is this internal: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Text/ValueStringBuilder.cs

As other Librarys already try to copy this (https://github.com/AngleSharp/AngleSharp/pull/981), I suggest to make it public.
see also: https://github.com/dotnet/runtime/issues/25587

**Comment by huoyaoyuan** [comment]
> Why is this internal

Because it's design isn't mature and using it requires explicit attention. I have found potential misuse even in the runtime repo.

**Comment by turbedi** [comment]
[Duplicate issue](https://github.com/dotnet/runtime/issues/25587)

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/25587
