### ISSUE TITLE
I get an error periodically System.IO.Strategies.FileStreamHelpers.GetFileLength(SafeFileHandle , String)

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#54549]
```
2021-06-22 15:59:28.1479|ERROR|XsltCheck.XsltCheckHostedService|При загрузке документа C:\Temp\XsltCheck\33_FlkService - 20200915\20200915_185346_0330f7b6-2d98-455f-a5d5-c25b690545d5.xml произошла ошибка = Неверный дескриптор. : 'C:\Temp\XsltCheck\33_FlkService - 20200915\20200915_185346_0330f7b6-2d98-455f-a5d5-c25b690545d5.xml'
System.IO.IOException: Неверный дескриптор. : 'C:\Temp\XsltCheck\33_FlkService - 20200915\20200915_185346_0330f7b6-2d98-455f-a5d5-c25b690545d5.xml'
   at System.IO.Strategies.FileStreamHelpers.GetFileLength(SafeFileHandle , String ) in System.Private.CoreLib.dll:token 0x60031be+0x19
   at System.IO.Strategies.WindowsFileStreamStrategy.get_Length() in System.Private.CoreLib.dll:token 0x6003268+0x23
   at System.IO.Strategies.AsyncWindowsFileStreamStrategy.ReadAsyncInternal(Memory`1 , CancellationToken ) in System.Private.CoreLib.dll:token 0x6003239+0x31
   at System.IO.Strategies.AsyncWindowsFileStreamStrategy.ReadAsync(Memory`1 , CancellationToken ) in System.Private.CoreLib.dll:token 0x6003238+0x0
   at System.IO.Strategies.BufferedFileStreamStrategy.ReadAsync(Memory`1 , CancellationToken ) in System.Private.CoreLib.dll:token 0x6003160+0x70
   at System.IO.FileStream.ReadAsync(Memory`1 , CancellationToken ) in System.Private.CoreLib.dll:token 0x6002fd4+0x22
   at System.Xml.XmlTextReaderImpl.InitStreamInputAsync(Uri , String , Stream , Byte[] , Int32 , Encoding ) in System.Private.Xml.dll:token 0x6000d53+0x122
   at System.Xml.XmlTextReaderImpl.FinishInitStreamAsync() in System.Private.Xml.dll:token 0x6000d44+0xcc
   at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task , Func`2 , TArg ) in System.Private.Xml.dll:token 0x60005fa+0x6e
   at XsltCheck.EsadChannel.TryGetEsadAsync(String fullFileName, CancellationToken cancellationToken) in XsltCheck.dll:token 0x600000a+0x119
```

**.net 6 p5**
**What other details are needed?**

**Comment by stephentoub** [comment]
cc: @adamsitnik

**Comment by adamsitnik** [comment]
Hi @kronic 

Could you please provide the exact version you are using? The output of `dotnet --info` should be fine

**Comment by carlossanlop** [comment]
@kronic can you share a code snippet we can use to repro the issue?

**Comment by kronic** [comment]
**dotnet --info**
Пакет SDK для .NET (отражающий любой global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.5.21302.13\

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.5.21301.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by kronic** [comment]
@carlossanlop 
Tomorrow I'll post the project

**Comment by danmoseley** [comment]
`произошла ошибка = Неверный дескриптор` = error, invalid handle.

**Comment by kronic** [comment]
@carlossanlop [proj](https://yadi.sk/d/6nHhM73FbIe_5g)
where can i send the password?
run RunProd.bat about 20 times, sometimes an error appears

**Comment by kronic** [comment]
@adamsitnik I sent the password for the test project to the email.

**Comment by kronic** [comment]
@adamsitnik any news?

**Comment by danmoseley** [comment]
@kronic until @adamsitnik gets a chance to look, could you please try the repo on the latest bits from main? https://github.com/dotnet/installer

**Comment by adamsitnik** [comment]
I've tried to repro it multiple times on both my Windows machines and I've failed. 

@kronic could you please try our latest bits from https://github.com/dotnet/installer?

**Comment by kronic** [comment]
@adamsitnik @danmoseley Thank you, the problem is no longer repeated on .net core 6 prev 7

**Comment by adamsitnik** [comment]
@kronic thank you for confirmation!
