### ISSUE TITLE
API request: string.IsInterned(ReadOnlySpan<char>)

### ISSUE THREAD

**Issue by panost** [dotnet/runtime#54546]
## Background and Motivation
String.IsInterned currently accepts a string parameter. When processing a `ReadOnlySpan<char>` it would be nice to be able to check if a string is interned, without a string allocation upfront. This would be especially useful for strings that would be used frequently.

## Proposed API

```C#
public class String
{
    // Existing API
    public static string? IsInterned(string str);

    // New API
  + public static string? IsInterned(ReadOnlySpan<char> str);
}

```

## Usage Examples

``` C#
ReadOnlySpan<char> span = GetNextFragment();
string found = string.IsInterned( span );
if ( found != null ) // it is a well known string constant and it will be handled accordingly.
// Also we can take route where this string is compared with string constants using `ReferenceEquals`
else // probably allocate a new string and handle it as unknown 
```

## Risks
None. This does not affect the string intern pool, just makes a query.

## Notes

This is not duplicate of  #28368 (API request: string.Intern(ReadOnlySpan<char> ...), where the more intrusive string.Intern was proposed by @ladeak, with the risks explained in the comments there.
I did however, copied and changed some parts from it.

**Comment by stephentoub** [comment]
> This is not duplicate of #28368

That issue also proposed `public static bool IsInterned(ReadOnlySpan<char> str)`.

**Comment by stephentoub** [comment]
> Perhaps that addition may enable this optimization also.

What optimization?

**Comment by panost** [comment]
> That issue also proposed public static bool IsInterned(ReadOnlySpan<char> str).

That is not the same. It returns bool and not string. It is not clear to me why a boolean return was chosen.
Also all the comments there, are about string.Interned 

> What optimization?

switch support of `ReadOnlyspan<char>` with cases of constant strings. This is something for C# team. Let's not elaborate on it here.

**Comment by stephentoub** [comment]
> switch support of ReadOnlyspan<char> with cases of constant strings. This is something for C# team. Let's not elaborate on it here.

You called it out as a potential reason for having the API, which is why I'm questioning it.  It's not clear to me how it would help, especially given the overhead of the IsInterned method.  I expect in many cases it would be a deoptimization.  The C# compiler also doesn't use the existing String.IsInterned(String) method today when using strings in a case like your example.

**Comment by panost** [comment]
@stephentoub : OK, removed. I left the unnecessary allocation example. I hope that IsInterned lookup is justified in those cases. It is the prime reason I asked this API, the switch/case example was just an afterthought

**Comment by Clockwork-Muse** [comment]
> // Also we can take route where this string is compared with string constants using `ReferenceEquals`

`string.Equals(...)` already makes this comparison for you, as one of the first comparisons, so that's not going to be much of an optimization.

**Comment by GrabYourPitchforks** [comment]
Seems like the scenario would be best handled not by querying the string intern table, but rather being able to use spans as keys into `Dictionary<string, ...>` / `HashSet<string>` instances? See https://github.com/dotnet/runtime/issues/27229 for more information.

**Comment by panost** [comment]
@GrabYourPitchforks No, they are not thread safe.

I did implement [a thread safe StringCache](https://github.com/panost/StringCache) using fat locks on additions, but I believe that String.IsInterned will be more performant and it is a global solution to the problem, since it can use strings from all assemblies and not only the ones in your scope.

I don't know why everybody suggest that string intern table shouldn't be used.
Are any plans to be obsolete in a future version? If not, what are the valid/suggested use cases for it ?

**Comment by GrabYourPitchforks** [comment]
The string intern table is primarily intended as a codegen and memory footprint optimization for literal data. It's not really intended as a global cache that you can query with arbitrary data read from the wire. It obviously _can_ be used that way, but it's not optimized for that scenario, and per Steve's comment I really think you'd find the performance lacking.

> No, they are not thread safe.

They're thread safe for reads assuming you're not actively writing to the dictionary. I assumed from your description that you have a finite set of literals you're comparing the incoming data against, which implies a prepopulated global cache, and if you see incoming data that's not part of that set you're hydrating it as a string _without_ adding it to the global cache. If you're adding the data to the global cache, then you'd need both some global locking mechanism and some policy to ensure that your application isn't subject to memory exhaustion attacks. That was also my sentiment behind the comments at https://github.com/dotnet/runtime/issues/28368 where I was cool on the original idea.

What exactly are you trying to do?

**Comment by panost** [comment]
I did make a benchmark and I was surprised to find out that you and Steve were correct. IsInterned was more than six times slower then a Dictionary lookup!

|      Method |      Mean |     Error |    StdDev |
|------------ |----------:|----------:|----------:|
|  Dictionary |  2.858 us | 0.0338 us | 0.0316 us |
|      Intern | 18.055 us | 0.1496 us | 0.1399 us |

Something is very wrong with the implementation of IsInterned. What makes it so slow ? Is it the locking that has to do, to support string.Intern ? Can the implementation be split to a fast readonly dictionary that searches the internal pool and a thread safe dictionary that has the implementation of string.Intern and uses the readonly first for lookup ?
It is hard for me to accept that the code that searches internal structures, such as the intern string pool has such a lousy implementation
Anyway those questions belong to a new issue
I am closing this
