### ISSUE TITLE
[browser-wasm] Support Mono runtime components in workload

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#54565]
The browser-wasm workload should support selecting different mono runtime components (#50862) for different configurations.

This depends on #54417

**Comment by radical** [comment]
From Wasm targets pov, they will get a list of files to link for dotnet.js/wasm?

**Comment by lambdageek** [comment]
> From Wasm targets pov, they will get a list of files to link for dotnet.js/wasm?

The workflow will be the same for all workloads:
1. Populate `@(_MonoComponents)` with the components you want for example `""` or `"hot_reload;diagnostics_tracing"`
2. Call the `_MonoSelectRuntimeComponents` target at the aproprite time in your build
3. Combine `@(_MonoRuntimeComponentLink)` with the full path of the `native/` directory of your runtime pack and link those libraries together with `libmonosgen-2.0.a` when building your host.
4. You now have an app bundle with components (or component stubs, depending on what you chose)

**Comment by lewing** [comment]
now is that https://github.com/dotnet/runtime/pull/54432 is in we need to follow up here
