### ISSUE TITLE
Path to .NET 6.0 for this repo

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#54569]
It’s time to start looking ahead to ensure we have a smooth landing for our GA release in November! To do this predictably we progressively stabilize starting from this repo upwards. This process will very much like [last year]( https://github.com/dotnet/runtime/issues/38286).

## Milestones

We’ll shortly begin to pass through issues that haven’t been triaged yet, or that have their milestone set to 6.0. Our goal is that only issues that are must-fix for the release have the milestone set to 6.0. Note: if an issue has its milestone set to 6.0 that doesn’t necessarily mean it won’t get fixed for the 6.0 release. It means that the others need to get fixed first. In many cases we’d still take a PR for other fixes. By reducing the bugs set to 6.0 we make sure we focus on what we really need to fix to make a quality release.

## Key dates in this repo

On July 13th feature work in this repo will stop. This is also the date we expect to snapshot the branch for our final preview release. There may be a few cases where feature work runs longer with special approval, but by this date we aim to be working only on final bug fixes.

On Aug 17th we aim to get to zero bugs in this repo for the 6.0 milestone. This is also the point where we move 6.0 development to its own branch. All code changes will continue to go into main, and we’ll cherry-pick into that branch just the critical ones we want to go out in .NET 6.0. What this means is that you, the community, can continue to work normally in main throughout.

## How you can help

As always, we welcome any and all bug reports and pull requests We also ask for your understanding when we cannot fix something – and if you believe we mis-prioritized an issue, we welcome [your feedback](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md).

The above dates only apply to this repo: up-stack repos such as dotnet/aspnetcore and dotnet/winforms will run longer on their own schedules, but we will all release together in November.

**Comment by danmoseley** [comment]
Thanks for all your help! Here's an update of how we're doing with bugs set to the 6.0 milestone. We have just over two weeks to get to zero before the branch for 7.0.

![graph (Small)](https://user-images.githubusercontent.com/6385855/127688035-d784782a-7313-4506-b9a9-41c0adf4a22a.png)

**Comment by danmoseley** [comment]
Your help is welcome! If you want to help root cause or fix any issues, take a look here:

https://issuesof.net/?q=is%3Aopen%20is%3Aissue%20repo%3Aruntime%20milestone%3A6.0.0

I've linked to @terrajobst handy app that allows querying across dotnet repos, and complex conditional operations with parentheses and operators.

**Comment by Anipik** [comment]
closing in favour of https://github.com/dotnet/runtime/issues/57770
