### ISSUE TITLE
[iOS] Clean up sample build when AOT+LLVM is enabled

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#54572]
By default the AppleAppBuilder will add `-llvm.o` files to `target_link_libraries` in CMakeLists.  This works great for tests, but not for the sample because we are picking up all files from `bin` and adding them to `APP_RESOURCES`.

We should clean this up a bit and try to make it similar to the test build.

**Comment by directhex** [comment]
Adding everything from bin was intentional, as part of #52372, to fix tests failing due to missing subdirectories (i.e. test data not being included)

Your thought is we should be explicitly filtering out `-llvm.o` suffixed files from AppResources?

**Comment by steveisok** [comment]
Yes, in the test build the .o files are in the obj directory and aren't included.
