### ISSUE TITLE
ConfigurationSection should take IConfigurationRoot and not ConfigurationRoot

### ISSUE THREAD

**Issue by kassemsandarusi** [dotnet/runtime#54579]
https://github.com/dotnet/runtime/blob/d0a102843040a3950827c498fa05da6e9f55a2b9/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationSection.cs#L24

Is there any reason for this to _specifically_ use the concrete ConfigurationRoot and not just IConfigurationRoot? It seems more extensible to simply take the `IConfigurationRoot`

I have a use case where I am porting an app between two config sources that and want to know what values are dead. The best way I see that working is an implementing wrapper around the existing `IConfigurationRoot` interface that logs out accesses to each key. This gets a little tricky with `ConfigurationSection`, because its constructor requires the concrete `ConfigurationRoot` and not just `IConfigurationRoot`.

**Comment by KalleOlaviNiemitalo** [comment]
In the code that you cited, the constructor already takes an IConfigurationRoot. This was apparently implemented in <https://github.com/dotnet/extensions/pull/605>.

**Comment by KalleOlaviNiemitalo** [comment]
The change went in some time between .NET Platform Extensions 2.2 and 3.0. Because it breaks binary compatibility, I don't believe the maintainers will backport it to older versions.

**Comment by kassemsandarusi** [comment]
Ah you're correct. In fact I linked directly to a constructor with IConfigurationRoot. My mistake!
