### ISSUE TITLE
ArPow stage 2: implementing source-build CI

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#54573]
The runtime repo has a [source-build CI leg](https://github.com/dotnet/runtime/blob/main/eng/pipelines/global-build.yml#L128).  This leg should be updated to build with ArPow (arcade-powered source-build).  The internal builds should publish the resulting Microsoft.SourceBuild.Intermediate packages.  This allows dependent repos' source-build legs to build with the runtime's source-built output.

ArPow provides [AzDO templates](https://github.com/dotnet/source-build/blob/master/Documentation/planning/arcade-powered-source-build/onboarding/ci-onboarding.md) for running source-build legs but may not be feasible to use within the runtime's build templates.

**Comment by MichaelSimons** [comment]
cc @ViktorHofer.

**Comment by ViktorHofer** [comment]
@MichaelSimons thanks for opening the issue. To share expectations, when do we need this? Most of us are currently fully booked on feature work, that's why I'm asking.

**Comment by MichaelSimons** [comment]
>To share expectations, when do we need this?

Two week timeframe

That being said, I would be willing to help out given some direction if you would like.  For starters, is it feasible to utilize the arcade SB templates or should the job continue to utilize the `global-build-job.yml`?  For consistency, I'm guessing it would be best to continue to use the `global-build-job.yml`?

**Comment by ViktorHofer** [comment]
Spoke with @Anipik, he will pick this task up. @MichaelSimons regarding your earlier question, yes we would like to not add another build pipeline and add a leg into the existing "runtime-official" pipeline and yml.

**Comment by Anipik** [comment]
It seems like darc is not  publishing these packages. talking a look into it.
