### ISSUE TITLE
SerialStream doesn't override memory-based Read-/WriteAsync methods

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54575]
When adding a `NetCoreAppCurrent` configuration to System.IO.Ports, roslyn warns that SerialStream's memory-based `ReadAsync` and `WriteAsync` methods aren't overridden. I was unsure if this requires api-approval so I'm filing this issue.

```
/home/vihofer/runtime/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.cs(13,35): error CA1844: 'SerialStream' overrides array-based 'ReadAsync' but does not override memory-based 'ReadAsync'. Consider overriding memory-based 'ReadAsync' to improve performance. [/home/vihofer/runtime/src/libraries/System.IO.Ports/src/System.IO.Ports.csproj]
/home/vihofer/runtime/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.cs(13,35): error CA1844: 'SerialStream' overrides array-based 'WriteAsync' but does not override memory-based 'WriteAsync'. Consider overriding memory-based 'WriteAsync' to improve performance. [/home/vihofer/runtime/src/libraries/System.IO.Ports/src/System.IO.Ports.csproj]
```

- [x] Unix part (#56866)
- [ ] Windows part

cc @adamsitnik @carlossanlop @Jozkee @jeffhandley

**Comment by stephentoub** [comment]
> I was unsure if this requires api-approval so I'm filing this issue.

No approval required.

**Comment by adamsitnik** [comment]
@ViktorHofer do you intend to work on it? If not, could please mark it as up-for-grabs and remove your assignment?

**Comment by i3arnon** [comment]
@adamsitnik Should I take this to mean there's an interest in implementing the `ReadAsync` & `WriteAsync`  overloads (memory and array based) for the Windows version of `SerialStream` as well?
