### ISSUE TITLE
No usable version of libssl was found on Apple Silicon M1 Mac 

### ISSUE THREAD

**Issue by andrewchaa** [dotnet/runtime#54597]
Code in Azure function breaks locally on M1 Mac when AesGCM does `Decrypt`

### Description

This is the part of the code that breaks

```csharp
using var cipher = new AesGcm(key);
cipher.Decrypt(nonce, toDecrypt, tag, decryptedData, associatedData);
```

I have installed openssl and set `DYLD_LIBRARY_PATH` in ~/.zshrc
It worked on Intel-based Mac, but breaks still on arm-based M1 Mac.

### Configuration

* netcoreapp3.1
* OS Version: Mac OS Big Sur Version 11.4, (Apple M1), 16 GB
* Architecture: arm
* openssl version: LibreSSL 2.8.3, openssl@1.1

Can anyone help please? This seems to be the only issue that stops me from developing in .NET on M1 Mac.

**Comment by vcsjones** [comment]
Can you make sure that the openssl you installed via homebrew is x86-64, not arm64? It can be confirmed with a command like:

```
otool -vh /opt/path/to/openssl/from/homebrew/openssl@1.1/lib/libcrypto.1.1.dylib
``` 

The mach header should indicate what architecture it was built for:

```
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00       DYLIB    14       1720   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

If it indicates an architecture other than X86_64, then you should re-install openssl with homebrew to make sure you get the right architecture.

**Comment by bartonjs** [comment]
@vcsjones I'm confused.  They said they were running on an arm64 device, so wouldn't arm64 libcrypto/libssl be the right answer and x86_64 the wrong answer?

**Comment by vcsjones** [comment]
@bartonjs 

> netcoreapp3.1

They said they are running .NET Core 3.1, there is no macOS ARM64 build of the runtime for .NET Core 3.1, so I would assume they are running in Rosetta 2 (x64 compat mode). You can't load an ARM64 library in to an x86_64 process.

**Comment by bartonjs** [comment]
Ooooh, tricky, tricky.

**Comment by andrewchaa** [comment]
@vcsjones Thanks a lot. I've checked and it's ARM64

```
./libcrypto.1.1.dylib:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64    ARM64        ALL  0x00       DYLIB    15       1816   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

I'll try to install X86_64 openssl
