### ISSUE TITLE
IssuerSigningKeyResolver doesn't support async

### ISSUE THREAD

**Issue by punitsinghi** [dotnet/runtime#54605]
Microsoft.IdentityModel.Tokens.IssuerSigningKeyResolver doesn't support async delegate and hence any async call is a blocking call.

            IssuerSigningKeyResolver = (token, securityToken, identifier, parameters) =>
                    {
                        
                    }

**Comment by danmoseley** [comment]
@davidfowl  do you know where bugs are tracked for this type?

**Comment by davidfowl** [comment]
I believe it's https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

cc @Tratcher @blowdart

**Comment by Tratcher** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/d6f2b66d788195b50f2b1f700beb497851194c73/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L388

**Comment by blowdart** [comment]
Yup plus it's arguable it should block because nothing can continue until the keys are retrieved.

**Comment by davidfowl** [comment]
@blowdart you can wait without blocking

**Comment by danmoseley** [comment]
OK, @punitsinghi please go ahead and open this issue in https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet instead.

I'm going to close this here.

**Comment by punitsinghi** [comment]
Thanks,  created #1660

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1660
