### ISSUE TITLE
DotNet 6 preview 5 Blazor wasm vs js performance

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#54600]
Is it normal that wasm function with for loop about 8-10 times slower than js?
Test sources are below...

# Average test result in Chrome (mac, 91.0.4472.114 )
- interop for loop: 870.092 ms
- js for loop: 30.949 ms
- local for loop: 860 ms

# Average test result in Safari 14.1.1
- blazor for loop: 302.338ms
- js for loop: 39.324ms
- local for loop: 290 ms

# Sources
Pure (empty) method call takes about 0.5 - 1 ms, so it does not influence to results.

Typescript
```ts
(window as any).Test = Test;
export function Test(): void {
  
  console.time('interop for loop');
  DotNet.invokeMethod("Lib", "TestFunc");
  console.timeEnd('interop for loop');

  console.time('js for loop');
  let r = 0;
  for (let i = 0; i< 10000000; i++) r = r + i;
  console.timeEnd('js for loop');
  (window as any).__result = r;
}
```

Razor page
```razor
@page "/Click"
@using System.Runtime.CompilerServices
@using Microsoft.JSInterop
@using System.Diagnostics
@{
    Console.WriteLine("Render");
}
<h3>Click</h3>
<button @onclick="OnClick">Test Interop</button>
<button @onclick="OnClickLocal">Test Local</button>

@code {

    private static int _r;

    protected override bool ShouldRender() => false;

    private void OnClick()
    {
        if (JS is not IJSUnmarshalledRuntime ujs) return;
        ujs.InvokeUnmarshalled<bool>("Test");
    }

    [Inject]
    public IJSRuntime? JS { get; set; }

    [JSInvokable]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static void TestFunc()
    {
        var r = 0;
        for (var i = 0; i < 10000000; i++) r += i;
        _r = r;
    }
    private void OnClickLocal()
    {
        var sw = Stopwatch.StartNew();
        var r = 0;
        for (var i = 0; i < 10000000; i++) r += i;
        _r = r;
        sw.Stop();
        Console.WriteLine($"local for loop {sw.ElapsedMilliseconds}");
    }
}
```

**Comment by hez2010** [comment]
blazor is using il interpreter on browser currently, so it generally runs slower than js.

**Comment by kefyru** [comment]
Cool! Thanks.
I already discovered about AOT, but cant run app on Mac.
I run > dotnet publish -c Release : ok,
but when i run > dotnet run -c Release, seems like project rebuilding and starts without AOT compilation... What am i doing wrong?

**Comment by kefyru** [comment]
> blazor is using mono il interpreter on browser by default currently, so it generally runs slower than js.
> It can be improved by using mono AOT compilation in .NET 6, and may be further improved by using dotnet NativeAOT in the future.
> 
> Tested on my machine:
> 
> Without Blazor AOT compilation:
> 
> ```
> interop for loop: 674.65625 ms
> js for loop: 17.7158203125 ms
> local for loop 668
> ```
> 
> With Blazor AOT compilation:
> 
> ```
> interop for loop: 0.7548828125 ms
> js for loop: 16.7470703125 ms
> local for loop 0
> ```

Cool! Thanks.
I already discovered about AOT, but cant run app on Mac.
I run > dotnet publish -c Release : ok,
but when i run > dotnet run -c Release, seems like project rebuilding and starts without AOT compilation... What am i doing wrong?

**Comment by hez2010** [comment]
AOT compilation only available when you publish your app.

```
dotnet publish -c Release /p:RunAOTCompilation=true
```

**Comment by kefyru** [comment]
> AOT compilation is only available when you publish your app.
> 
> ```
> dotnet publish -c Release /p:RunAOTCompilation=true
> ```
> 
> Then you can use any http server to serve static files under `bin/Release/net6.0/publish/wwwroot`.

Thanks a lot!
I've got it works.
Using MAMP http server (http://www.mamp.info) for mac, with document root targeted to .../bin/release/net6.0/publish/wwwroot

results:
interop for loop: 0.108 ms
js for loop: 11.836ms
local for loop 0

Problem solved :)
