### ISSUE TITLE
System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceiveAsync fails

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#54627]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1201745&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b)

Seen on #54053 .

```
    System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceiveAsync [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/UnixDomainSocketTest.cs(372,0): at System.Net.Sockets.Tests.UnixDomainSocketTest.ConcurrentSendReceiveAsync()
        --- End of stack trace from previous location ---
```

**Comment by karelz** [comment]
Failures **3/12-6/23 (incl. PRs)**:

Date | Build | OS
-- | -- | --
3/19 | PR #49855 | Windows.10.Amd64.Server19H1.ES.Open
6/23 | PR #54053 | Windows.10.Amd64.Server19H1.ES.Open

**Comment by rzikm** [comment]
No recent hits, not actionable at this moment, closing until issue resurfaces.
