### ISSUE TITLE
Mobile Networking Tests

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#54626]
The mobile side of networking tests is currently being assessed by running outer loop tests for Android in https://github.com/dotnet/runtime/pull/54618. Once we grasp the state of networking tests with regards to pass/fail rates, we can determine next steps.

Possible next steps:
Move the outerloop tests to innerloop for Android 
Use echo server in XHarness for Android in case of instability in Azure
Stand-up Loopback tests for Android

**Comment by steveisok** [comment]
@mdh1418 I moved this to 7.0, but it is a small effort to enable outerloop.  Might be a good idea to do that part in 6.
