### ISSUE TITLE
System.Timers.Timer should have a way to set dueTime

### ISSUE THREAD

**Issue by jez9999** [dotnet/runtime#54620]
At the moment, `System.Timers.Timer` (which uses a `System.Threading.Timer` internally) has no way to set `dueTime`.  `dueTime` allows the caller to decide how long the initial delay before the first callback should be.  For some reason, `System.Timers.Timer` doesn't provide the option to configure this, and instead, always sets the value to the interval:

https://github.com/dotnet/runtime/blob/0416c3469b7bccff087b89db3d9967dfd36070a3/src/libraries/System.ComponentModel.TypeConverter/src/System/Timers/Timer.cs#L131

As users will frequently want to be able to trigger the timer immediately upon start, `dueTime` should be configurable on `System.Timers.Timer`.  Or maybe there could be a `TickImmediately` bool on the class, and/or passed in to the `Start` method.

**Comment by jez9999** [comment]
Have submitted a PR for a proposed "tick immediately" option.

**Comment by svick** [comment]
If you want to add a new API, you need to go through [the API review process](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md), you shouldn't just submit a PR.

**Comment by jez9999** [comment]
@svick Have submitted api proposal in issue #54737

**Comment by safern** [comment]
Thanks @jez9999 -- closign this in favor of: https://github.com/dotnet/runtime/issues/54737
