### ISSUE TITLE
Consider Reloadable Attribute for Hot Reload 

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#54633]
## Background and Motivation

Roslyn is adding a Reloadable Type feature.  Types marked with the ```Reloadable``` attribute instructs the Roslyn compiler to emit a new type rather than updating it when applying changes with .NET Hot Reload.  This feature enables inner-dev loop changes to be made that normally would be considered to be rude edits.  We are proposing the ```Reloadable``` attribute to be used by frameworks, 3rd party libraries, and end users.  It will be consumed by the Roslyn compiler.

## Proposed API

```csharp
namespace System.Runtime.CompilerServices
{  
  [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]  
  public class ReloadableAttribute : Attribute  
  {  

  }
}

```

## Usage Examples

MyUIFramework knows how to serialize, instantiate, reinitialize, and display onscreen any View subclass.  So even 'rude edits' that ends up being new version of types can be applied by MyUIFramework during a .NET Hot Reload session.

```csharp
namespace MyUIFramework
{
  [Reloadable]
  public class View
  {

  }
}
```

## Alternative Designs

1. One alternative would be to the add known types at the Roslyn level, though this limits future extensibility by 3rd parties and app developers.  

2. Another alternative is to define an internal attribute for each framework that supports the reloadable type feature.  The disadvantage is that there are possible conflicts when using InternalVisibleTo, and a lack of central documentation of the feature.

## Risks

None at the runtime library level, as this only defines an attribute

**Comment by tommcdon** [comment]
@stephentoub @tmat @mikem8361 @pranavkm

**Comment by pranavkm** [comment]
Since it's an API proposal:

```C#
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]  
public sealed class ReloadableAttribute : Attribute  
{  
}
```

Also consider `ReloadableAttribute` -> `ApplyUpdateReloadableTypeAttribute` so that it's very clear about it's intent.

**Comment by tmat** [comment]
`ApplyUpdateReloadableAttribute` sounds odd to me.

**Comment by tommcdon** [comment]
We should also consider placing the attribute in the System.Reflection.Metadata namespace, which is next to the [MetadataUpdateHandler](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/Metadata/MetadataUpdateHandlerAttribute.cs) attribute.

**Comment by tmat** [comment]
I chose `System.Runtime.CompilerServices` because this attribute is for compiler consumption and has no meaning for the runtime

**Comment by tommcdon** [comment]
Updated the proposal with @pranavkm suggestion to include ```AllowMultiple = false```

**Comment by stephentoub** [comment]
Do we envision this ever being applied to things beyond types (even if not in .NET 6)?  Wondering if it should be named ReloadableType instead of just Reloadable.

**Comment by tmat** [comment]
One possibility would be methods if we need finer-grained control.

**Comment by terrajobst** [comment]
* We should avoid "good names", that is single word names like `[Reloadable]`.
* Assuming you don't like `EditMetadataByCreatingNewTypeAttribute` come back with a few proposals and we can pick one over email

```C#
namespace System.Runtime.CompilerServices
{  
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false)]  
    public class EditMetadataByCreatingNewTypeAttribute : Attribute  
    {  
    }
}
```

**Comment by tmat** [comment]
How about `ReloadOnMetadataUpdate`?

**Comment by terrajobst** [comment]
We agreed over email to `CreateNewOnMetadataUpdateAttribute`
