### ISSUE TITLE
WPF application uses different versions of .NET runtimes

### ISSUE THREAD

**Issue by duskembayev** [dotnet/runtime#54669]
### Description
I have WPF application with generated `.runtimeconfig.json`
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "rollForward": "disable",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "5.0.6"
    }
  }
}
```

The application uses two different runtime versions at the same time. Looks like, `Microsoft.NETCore.App` framework ignores `rollForward`  option.
![image](https://user-images.githubusercontent.com/14294244/123225154-19295e80-d4db-11eb-9df6-f1ab95312d88.png)

Sample project: https://github.com/duskembayev/dotnet_runtime_issue_54669

### Configuration
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18363 Build 18363

```
dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Other information
It works properly if I declare explicitly all frameworks in `.runtimeconfig.json` 
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "rollForward": "disable",
    "frameworks": [{
            "name": "Microsoft.NETCore.App",
            "version": "5.0.6"
        }, {
            "name": "Microsoft.WindowsDesktop.App",
            "version": "5.0.6"
    }]
  }
}
```

**Comment by vitek-karas** [comment]
The runtime config of the `Microsoft.WindowsDesktop.App` looks like this:
```json
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "5.0.6",
      "rollForward": "LatestPatch"
    }
  }
}
```

So it explicitly allows latest patch. The rollfoward setting is not inherited, each framework reference defines it anew. I understand that in this specific case it probably doesn't do what you want. At the same time, declaring all framework references explicitly in this case doesn't seem like a terrible solution.

The framework resolution algorithm is described here: https://github.com/dotnet/runtime/blob/main/docs/design/features/framework-version-resolution.md. Although this particular case is probably not covered there.

**Comment by duskembayev** [comment]
Thanks, @vitek-karas.

Currently, I looking for the right way to generate `.runtimeconfig.json` with a customized `frameworks` section containing all required records.
I already tried to declare `runtimeconfig.template.json`, but it is not applicable to `frameworks` section.

Could you, please, suggest a solution?

**Comment by vitek-karas** [comment]
I'm no aware of any which is directly built into the SDK. You can create a post-build step which overwrites the file.

Just curious: Why is it important to you to disable roll-forward completely?

**Comment by duskembayev** [comment]
>You can create a post-build step which overwrites the file.

Yes, I know, but this way doesn't look right. Maybe in future versions, there will be better ways to do such customizations.

>Why is it important to you to disable roll-forward completely?

The sample above is just for demonstration. Actually, real application delivered to end-user with customized runtime and CLR hosting. That's why at the current stage of development we want to ensure that the exact version of the runtime is used. 

Thanks!

**Comment by vitek-karas** [comment]
> Anyway, current behavior looks very strange. I'm sure that Microsoft.WindowsDesktop.App uses the internals of Microsoft.NETCore.App. As a consequence, Microsoft.NETCore.App should support backward compatibility for patches of internal features.

`Microsoft.NETCore.App` is backward compatible, that's why it's OK to run 5.0.7 NetCore with 5.0.6 WindowsDesktop.

The reason for allowing patch roll-forward are security patches - let's say we need to patch the NetCore.App, if the versions were 100% rigid, we would also have to release a new version of WindowsDesktop, just to allow the higher version of NetCore.App.

> Actually, real application delivered to end-user with customized runtime and CLR hosting. That's why at the current stage of development we want to ensure that the exact version of the runtime is used.

So you install your customized runtime into a global location? (like Program Files) If you're not, then I don't see the need to freeze the versions since you would have full control over the install location (not allowing any other versions there).

**Comment by duskembayev** [comment]
>So you install your customized runtime into a global location? (like Program Files) If you're not, then I don't see the need to freeze the versions since you would have full control over the install location (not allowing any other versions there).

We install runtime into a custom (**not** global) location. But it can contain multiple versions of runtime (i.e. 5.0.6, 5.0.7, 6.0.0, etc.) at the same time.

As I said before, we implemented some CLR customizations (such as custom location, sandboxing, custom clr hosting, plugin system). If you are interested in our cases - I can provide more details privately (email or call). We will be happy to discuss the implemented solutions.
