### ISSUE TITLE
Marshal.PtrToStructure fails to split strings in .NET Core 5

### ISSUE THREAD

**Issue by jlchavez** [dotnet/runtime#54662]
When marshaling a BSTR to a Struct it fails to split the strings as it did in .NET Framework 4.7.2

Edit
Added a test on .NET Fiddle:
[Test Marshal.PtrToStructure NET 5](https://dotnetfiddle.net/fZ97zx)

### Description

On the following example a string of "012", should be split into "01" a "2" but the strings point to the correct position but doesn't contain the correct ending mark for the first one, so the result would be "012" and "2". Yes it's obvious that a masrsahlling of the bytes directly to the struct would produce this behavior, but I would file it as a bug, not a feature. My string obviously is a 64 character long with 13 fields, this is just a small example of the problem.

    using System;
    using System.Runtime.InteropServices;
    using System.Text;

    public class Program
    {
        public static void Main()
        {
           string str = "012";
           IntPtr pBuf = Marshal.StringToBSTR(str);
           CEStruct ces = (CEStruct)Marshal.PtrToStructure(pBuf, typeof(CEStruct));
           Console.WriteLine(ces.tipoDocumento);
           Console.WriteLine(ces.tipoContribuyente);
        }
    }
    
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct CEStruct
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 2)]
        public string tipoDocumento;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 1)]
        public string tipoContribuyente;
    }

### Configuration
Visual Studio 2019 16.10.1
.NET Core 5
Windows 10.0.19042.1052
64bit
Not specific to configuration 

### Regression?
 It works fine in .net 4.7.2

**Comment by huoyaoyuan** [comment]
On .NET Core 3.1 it outputs "01" and "2" too.

**Comment by jlchavez** [comment]
Thanks @huoyaoyuan 

I Added a .NET Fiddle to the issue, it runs in .net 5 with all the code that a friend reported to me that failed, built another solution for him, but there it fails.

**Comment by jkotas** [comment]
cc @jkoritzinsky
