### ISSUE TITLE
Connect_DualMode_DnsConnect_RetrievedEndPoints_Success - Assert ::1

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#54677]
Affected test namespaces:
- System.Net.Sockets.Tests.ConnectTask
- System.Net.Sockets.Tests.ConnectCancellableTask
- System.Net.Sockets.Tests.ConnectSync
- System.Net.Sockets.Tests.ConnectSyncForceNonBlocking
- System.Net.Sockets.Tests.ConnectApm
- System.Net.Sockets.Tests.ConnectEap

```
    System.Net.Sockets.Tests.ConnectCancellableTask.Connect_DualMode_DnsConnect_RetrievedEndPoints_Success [FAIL]
      Assert.Equal() Failure
      Expected: ::ffff:127.0.0.1
      Actual:   ::1
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs(132,0): at System.Net.Sockets.Tests.Connect`1.Connect_DualMode_DnsConnect_RetrievedEndPoints_Success()
        --- End of stack trace from previous location ---
```

Test failures **3/12-6/23 (incl. PRs)**:

Date | Run | OS | Flavor | Namespace
-- | -- | -- | -- | --
6/6 | Official run | SLES.12.Amd64.Open | Mono | ConnectSync
6/6 | Official run | RedHat.7.Amd64.Open | CoreCLR | ConnectEap
6/7 | PR #53837 | Debian.10.Amd64.Open | Mono | ConnectCancellableTask
6/8 | Official run | SLES.12.Amd64.Open | Mono | ConnectCancellableTask
6/8 | PR #53808 | Alpine.312.Amd64.Open | CoreCLR | ConnectTask
6/8 | PR #53869 | Fedora.30.Amd64.Open | Mono | ConnectEap
6/8 | PR #53206 | SLES.15.Amd64.Open | CoreCLR | ConnectCancellableTask
6/9 | Official run | Fedora.30.Amd64.Open | CoreCLR | ConnectApm
6/10 | PR #53968 | Ubuntu.1804.ArmArch.Open | Mono | ConnectTask
6/10 | PR #53972 | Centos.8.Amd64.Open | Mono | ConnectSyncForceNonBlocking
6/10 | PR #53984 | SLES.15.Amd64.Open | CoreCLR | ConnectCancellableTask
6/11 | PR #53982 | Centos.8.Amd64.Open | CoreCLR | ConnectApm
6/11 | Official run | Debian.9.Amd64.Open | Mono | ConnectApm
6/13 | PR #54094 | Debian.10.Amd64.Open | Mono | ConnectApm
6/14 | PR #54133 | Ubuntu.1804.ArmArch.Open | Mono | ConnectSyncForceNonBlocking
6/14 | Official run | Ubuntu.1910.Amd64.Open | CoreCLR | ConnectCancellableTask
6/14 | PR #54099 | Centos.8.Amd64.Open | Mono | ConnectSync
6/14 | PR #53606 | Debian.10.Amd64.Open | CoreCLR | ConnectCancellableTask
6/16 | PR #54250 | Debian.10.Amd64.Open | Mono | ConnectTask
6/16 | PR #54245 | Fedora.30.Amd64.Open | CoreCLR | ConnectSync
6/16 | PR #54245 | Fedora.30.Amd64.Open | CoreCLR | ConnectTask
6/17 | PR #54040 | SLES.15.Amd64.Open | Mono | ConnectTask
6/18 | PR #53450 | Debian.10.Amd64.Open | Mono | ConnectSync
6/18 | PR #54305 | Fedora.30.Amd64.Open | CoreCLR | ConnectTask
6/18 | Official run | Fedora.30.Amd64.Open | CoreCLR | ConnectSync
6/18 | PR #53450 | SLES.15.Amd64.Open | Mono | ConnectSync
6/18 | PR #54281 | Debian.9.Amd64.Open | Mono | ConnectTask
6/18 | PR #54246 | SLES.15.Amd64.Open | Mono | ConnectTask
6/19 | PR #54207 | Centos.8.Amd64.Open | Mono | ConnectSync
6/19 | PR #54261 | Debian.9.Amd64.Open | Mono | ConnectApm
6/20 | PR #54451 | Debian.9.Amd64.Open | Mono | ConnectCancellableTask
6/21 | PR #54477 | Debian.10.Amd64.Open | Mono | ConnectSync
6/21 | PR #54246 | SLES.15.Amd64.Open | CoreCLR | ConnectSyncForceNonBlocking
6/21 | PR #54218 | Debian.10.Amd64.Open | Mono | ConnectCancellableTask
6/21 | PR #54136 | Debian.10.Amd64.Open | Mono | ConnectCancellableTask
6/22 | Official run | Debian.10.Amd64.Open | Mono | ConnectSync
6/22 | PR #54253 | Alpine.312.Amd64.Open | CoreCLR | ConnectTask
6/22 | PR #49737 | Fedora.30.Amd64.Open | Mono | ConnectTask
6/22 | PR #54511 | Debian.10.Amd64.Open | CoreCLR | ConnectSync
6/22 | PR #54578 | Fedora.30.Amd64.Open | Mono | ConnectTask
6/23 | PR #54518 | Debian.10.Amd64.Open | CoreCLR | ConnectApm
6/23 | PR #54253 | Fedora.30.Amd64.Open | Mono | ConnectSync
6/23 | PR #54595 | SLES.15.Amd64.Open | Mono | ConnectEap
6/23 | Official run | Centos.8.Amd64.Open | Mono | ConnectCancellableTask
6/23 | PR #54544 | SLES.15.Amd64.Open | CoreCLR | ConnectTask
6/23 | PR #54568 | Fedora.30.Amd64.Open | Mono | ConnectEap
6/23 | PR #54053 | SLES.15.Amd64.Open | CoreCLR | ConnectCancellableTask
6/23 | PR #54621 | Fedora.30.Amd64.Open | CoreCLR | ConnectCancellableTask
6/23 | PR #54625 | Centos.8.Amd64.Open | CoreCLR | ConnectEap
6/24 | 1x PR | -- | -- | --
6/26 | 2x Official run + 1x PR | -- | -- | --
6/27 | 3x PR | -- | -- | --
6/28 | 6x PR | -- | -- | --
6/29 | 3x PR | -- | -- | Attempt for fix in PR #54681
6/30 | 5x PR | -- | -- | --
7/1 | 3x PR | -- | -- | --
7/2 | 1x PR | -- | -- | --
7/7 | 2x PR | -- | -- | --
7/8 | 4x PR | -- | -- | --
7/9 | 1x PR | -- | -- | --
7/10 | Official run | Centos.8.Amd64.Open | Mono | ConnectTask
7/10 | Official run | SLES.15.Amd64.Open | CoreCLR | ConnectTask
7/10 | PR #53151 | Debian.10.Amd64.Open | Mono | ConnectApm
7/13 | Official run | Fedora.32.Amd64.Open | Mono | ConnectTask
7/14 | PR #52699 | Alpine.312.Amd64.Open | CoreCLR | ConnectCancellableTask
7/15 | PR #55772 | Centos.8.Amd64.Open | CoreCLR | ConnectCancellableTask
7/16 | PR #55787 | Debian.9.Amd64.Open | Mono | ConnectEap
7/16 | PR #55856 | Centos.8.Amd64.Open | Mono | ConnectTask
7/16 | PR #55857 | SLES.15.Amd64.Open | Mono | ConnectCancellableTask
7/18 | PR #55882 | RedHat.7.Amd64.Open | Mono | ConnectCancellableTask
7/18 | PR #55857 | Fedora.32.Amd64.Open | Mono | ConnectApm

**Comment by karelz** [comment]
@antonfirsov this looks like recent regression -- any idea why?
We should disable the test ASAP -- 50 failures in 18 days.

**Comment by antonfirsov** [comment]
This is a new test introduced in #53581. Looks like `client.LocalEndpoint` doesn't get mapped to IPv6:
https://github.com/dotnet/runtime/blob/0d31ddb6c0fa7b9846167016734a63cdbbcc42b8/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs#L132

Likely a product bug, only affects Linux.

@tmds any tips what is going wrong here?

**Comment by antonfirsov** [comment]
If I get https://github.com/dotnet/runtime/issues/53447#issuecomment-852086387 right, the bug pointed out in that issue is still present.

**Comment by tmds** [comment]
@antonfirsov I think we need to update the test expectation and allow both
```
 ::ffff:127.0.0.1
 ::1
```
as values for `LocalEndPoint`.

**Comment by danmoseley** [comment]
Hit this just now on SLES15 Arm64 in the preview 6 branch.

**Comment by karelz** [comment]
This is still happening, reopening

**Comment by karelz** [comment]
Test disabled in PR #56003
