### ISSUE TITLE
Missing Span/Memory overloads

### ISSUE THREAD

**Issue by shravan2x** [dotnet/runtime#54697]
## Background and Motivation

Support was added for Span/Memory types recently, but not all common APIs support them. If one part of code doesn't support them, the only options are to use `ToArray` (which presumably copies data unnecessarily) or to just stick to `byte[]`.

## Proposed API

- `MemoryStream` constructor that accepts Span/ReadOnlySpan/Memory/ReadOnlyMemory.
- HttpClient's `ByteArrayContent` constructor that accepts Span/ReadOnlySpan/Memory/ReadOnlyMemory

## Usage Examples

`new MemoryStream(span);`
`new ByteArrayContent(span);`

## Risks

None I'm aware of.

**Comment by filipnavara** [comment]
It would need to make a copy for a Span anyway so you would not save anything compared to ToArray. The lifetime of these objects (on heap) can easily exceed the lifetime of the Span (possibly on stack).

**Comment by stephentoub** [comment]
> MemoryStream constructor that accepts Span/ReadOnlySpan

As @filipnavara mentions, these would necessarily need to ToArray.  I don't think adding those APIs sends the right message to the consumer, as it suggests something else is happening.  Better to just let the call site use ToArray.

> MemoryStream constructor that accepts Memory/ReadOnlyMemory

This is tracked by https://github.com/dotnet/runtime/issues/22838.

> HttpClient's ByteArrayContent constructor that accepts Span/ReadOnlySpan

Same as for MemoryStream above.

> HttpClient's ByteArrayContent constructor that accepts Memory/ReadOnlyMemory

There's already ReadOnlyMemoryContent (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.readonlymemorycontent?view=net-5.0).

So, I think this can be closed as dup of https://github.com/dotnet/runtime/issues/22838.  Please let me know if I missed anything else.

**Comment by shravan2x** [comment]
The points you made on `Span<>` types make sense to me. Could you clarify why we chose to build/maintain separate containers `ByteArrayContent` and `ReadOnlyMemoryContent`? I believe `byte[]` implicitly converts to `Memory<byte>` anyway and logically they both seem to refer to refer to byte buffers.

**Comment by filipnavara** [comment]
I think ByteArrayContent predates the Span/Memory types

**Comment by shravan2x** [comment]
But wouldn't overloads make more sense then? Or maybe just a new catch-all type like `BufferContent` and deprecating `ByteArrayContent`? Surely the perf implication of using `Memory<>` would not matter much in a networking context? I'm sure there was a reason we chose to go this route, I'm just curious what that is.

**Comment by stephentoub** [comment]
> So, I think this can be closed as dup of https://github.com/dotnet/runtime/issues/22838. Please let me know if I missed anything else.

Closing.
