### ISSUE TITLE
[Question] Why are dot-prefixed files considered "Sensitive"?

### ISSUE THREAD

**Issue by YuKitsune** [dotnet/runtime#54712]
I spent a good amount of time trying to figure out why a Configuration Provider using the `PhysicalFileProvider` refused to read a dot-prefixed file (E.g. `.env`).
It turns out, dot-prefixed files are considered sensitive:
https://github.com/dotnet/runtime/blob/75b6c99e2c704b3e366ce86020633c517a821d61/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/ExclusionFilters.cs#L15-L23

It was introduced as part of this PR in the previous repository: https://github.com/aspnet/FileSystem/pull/280

After finding this, I had two questions:
1. Why are dot-prefixed files considered sensitive?
2. Why are sensitive files excluded from `PhysicalFileProvider` by default.

For further context, I'm working on an app where I need to read the configuration from a file called `.env`. I kept getting `FileNotFoundExceptions` and had to dig into the source code to find out why.
I've attempted to address the confusing error in this PR: https://github.com/dotnet/runtime/pull/54717

**Comment by adamsitnik** [comment]
@blowdart @Tratcher @pranavkm can any of you answer the question?

**Comment by blowdart** [comment]
Convention. They were hidden from linux directory listings, much like files with the hidden file attribute or system file attribute on Windows. They often contain configuration information. We follow that convention.

**Comment by YuKitsune** [comment]
Thanks @blowdart 
Not suggesting any changes, just curious as to why they were considered sensitive, and that answers my question 😄
