### ISSUE TITLE
QUIC: Rename S.N.Quic --> S.N.Private.Quic

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#54720]
Follow up for #54534

The naming scheme for our internal libraries contains **Private** to properly communicate the intent. I intentionally skipped this step in the #54610 to cause the least churn possible while very active development is ongoing and also to get the change in ASAP.

**We should decide whether we want to do the rename and if so when.**

This issue is irrelevant post 6.0, since we plan to properly expose the APIs for 7.0.

**Comment by ManickaP** [comment]
@karelz this needs triage with our QUIC team.

**Comment by karelz** [comment]
I think we should do it for .NET 6. Let's discuss on Tue in QUIC meeting.

**Comment by karelz** [comment]
Triage: We should hide it behind the PreviewFeatureAttribute

**Comment by ManickaP** [comment]
Related to https://github.com/dotnet/runtime/issues/55024

**Comment by ManickaP** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/55024
