### ISSUE TITLE
The Microsoft.NETCore.App runtime for .NET preview5 is missing when install .NET preview6 and preview5 at the same time.

### ISSUE THREAD

**Issue by Jiangpeng14** [dotnet/runtime#54735]
Affected Mac:
Mac OS: Catalina(10.15.7)
.NET 6 SDK: 
6.0.100-preview.5.21302.13(runtime 6.0.0-preview.5.21301.5)
6.0.100-preview.6.21324.9(runtime 6.0.0-preview.6.21324.10)

Repro steps:
1. Install .NET 6 preview5 from https://dev.azure.com/dnceng/internal/_build/results?buildId=1168822&view=artifacts&pathAsName=false&type=publishedArtifacts
2. Run "dotnet --info" in the terminal
3. Install .NET 6 preview6 from https://github.com/dotnet/installer
4. Run "dotnet --info" in the terminal

Expected Result:
All the SDKs and runtimes should display separately.

Actual Result:
The Microsoft.NETCore.App runtime for .NET preview5 is missing.

dotnet info for preview5:
![Screen Shot 2021-06-25 at 4 12 12 PM](https://user-images.githubusercontent.com/84758135/123406553-a1902800-d5dd-11eb-8bff-986404572ff6.png)

dotnet info for preview5 and preview6:
![image](https://user-images.githubusercontent.com/84758135/123406961-08154600-d5de-11eb-9279-f5b7d2b913b5.png)

**Comment by marcpopMSFT** [comment]
@dleeapho Any idea on the mac installer and this behavior wrt the runtime?  I didn't think the mac installer would force upgrade like the windows one but seems like it is for net core runtime which I'd assume would come from your team.

CC @wli3

**Comment by dleeapho** [comment]
I believe runtime pkg installs are simply side-by-side.

**Comment by NikolaMilosavljevic** [comment]
Reopening as https://github.com/dotnet/arcade/pull/7695 has updated the infra, but the change in dotnet/runtime, to consume this infra, is still pending.
