### ISSUE TITLE
dotnet watch (net 6.0 preview 5) - attach to process... not working and no breakpoints hit #18538

### ISSUE THREAD

**Issue by dotnetshadow** [dotnet/runtime#54730]
### Description
I'm trying .net 6 preview 5, I created a **blazor webassembly** project using the default template.  Next I go to the **Server** project open a command prompt and run `dotnet watch`.

I go to the `counter.razor` page and put a breakpoint on `currentCount++; ` (line 15)
In Microsoft Visual Studio Enterprise 2019 Preview (Version 16.11.0 Preview 2.0) I Go to Debug -> Attach to Process...

**Issues**

1. In previous versions of Visual Studio 2019 I could find the processor name belonging to my application. I can't seem to find the processor exe file listed anymore. Just doesn't show up in the list.
2. So I decided to run `dotnet watch --no-hot-reload` this time the processor name is displayed in the list and I am able to choose it. But my breakpoint never gets hit
3. I next decide to abandon using the `dotnet cli` and instead just press `F5` from within Visual Studio it brings up the it's cli window and opens the site and breakpoints work correctly.
4. Using debugging through Visual Studio I noticed that if I tried to change the `counter.razor` by updating the `<h1>` tag nothing changed. Are edits not supported while debugging?

**Questions**

1. Differences between trying to use the `dotnet cli` directly and trying to attach the process? Why can't I use Debug->Attach to Process and have my breakpoints hit?
2. Is hot module reloading disabled when debugging within visual studio? i.e. can I edit the the razor page and expect to see pages?

This issue also happens with other app types such asp asp.net core mvc

### Configuration
.NET 6.0 preview 5
Visual Studio Enterprise 2019 Preview (Version 16.11.0 Preview 2.0)

### Other information
https://github.com/dotnet/sdk/issues/18538

**Comment by tommcdon** [comment]
@mikem8361

**Comment by mikem8361** [comment]
Debugging (attach) isn't supported after a hot reload edit and hot reload edits like yours (editing a razor page) while debugging (ENC) is still a work in progress as far as I know.

**Comment by dotnetshadow** [comment]
> 
> 
> Debugging (attach) isn't supported after a hot reload edit and hot reload edits like yours (editing a razor page) while debugging (ENC) is still a work in progress as far as I know.

Thanks for clearing that part up. The main concern now is why can't I use Debug->Attach to Process and have my breakpoints hit?

**Comment by mikem8361** [comment]
If you haven't done any hot reload edits before attaching, your breakpoints and debugging in general should work fine.  If there were edits before attach, the attach would popup an error dialog.  Is your problem that the attach was successful but your breakpoints weren't hit?  Did the breakpoint get resolved to addresses?

**Comment by dotnetshadow** [comment]
> Is your problem that the attach was successful but your breakpoints weren't hit?
Yes that's correct. 

1. Create a new blazor webassembly app (.net 6.0 preview 5), 
2. go to the server project open up a windows terminal `dotnet run`. 
3. Go to visual studio 2019 preview or standard Debug-> Attach to Process... find the process. 
4. Set a breakpoint on counter increment
5. It will attach but no breakpoints hit

**Comment by mikem8361** [comment]
I'm including some VS folks: @gregg-miskelly, @caslan.  I'm not sure if this is the runtime yet and hot reload isn't involved in your last repro.

**Comment by gregg-miskelly** [comment]
Are you trying to debug code running in the browser? Or server-side code?
If the browser, how are you trying to attach to the process? (what transport, engine, process are you using)

**Comment by dotnetshadow** [comment]
@gregg-miskelly I'm trying to debug a blazor webassembly app. I'm trying to do what I've always done with a blazor webassembly app whereby I can attach my dotnet process of whatever app I'm currently runn say Foo.exe (server project), then I can debug the classic counter component in the client project. 

If you can see a few comments above I've outlined exactly what I do

I also got a response from here that perhaps preview 5 doesn't currently allow this
https://github.com/dotnet/aspnetcore/issues/33871

**Comment by hoyosjs** [comment]
Moving to mono as this is webassembly.

**Comment by lewing** [comment]
cc @pranavkm

**Comment by lambdageek** [comment]
There are a couple of  issues being described in this discussion, but I think we can separate them into two groups:
1. `dotnet watch` and debugging client-side blazor webassembly apps.  This is currently not implemented.
2. A problem with `dotnet run` described in https://github.com/dotnet/runtime/issues/54730#issuecomment-870513054
   > Yes that's correct.
   > 1. Create a new blazor webassembly app (.net 6.0 preview 5),
   > 2. go to the server project open up a windows terminal `dotnet run`.
   > 3. Go to visual studio 2019 preview or standard Debug-> Attach to Process... find the process.
   > 4. Set a breakpoint on counter increment
   > 5. It will attach but no breakpoints hit

@pranavkm  is `dotnet run` of the server project, followed by an attach from VS expected to work for debugging the client-side app in preview 5? /cc @danroth27

**Comment by pranavkm** [comment]
> is dotnet run of the server project, followed by an attach from VS expected to work for debugging the client-side app in preview 5

Spoke to our resident debugger expert (@captainsafia) and it sounds like that has never worked. The app must be launched with debugger attached for WASM debugging to work.

**Comment by lambdageek** [comment]
Sorry about the confusion @dotnetshadow.  WASM debugging and hot reload are still evolving, so not every scenario is fully functional yet.

**Comment by dotnetshadow** [comment]
@lambdageek I agree while hot reload might not work in this scenario, but I did run `dotnet run`  and disabled hot reload and the other command which escapes me.

To be honest I'm confused about all these comments in this thread. 

Could someone kindly just answer if this scenario should be working without hot reload without any fancy stuff, just a straight `dotnet run` command:

1.  Create a new blazor webassembly app (.net 6.0 preview 5),
2.  go to the server project open up a windows terminal dotnet run.
3.  Go to visual studio 2019 preview or standard Debug-> Attach to Process... find the process.
4.  Set a breakpoint on counter increment
5.  It will attach but no breakpoints hit

Should the above work? Yes or No simple as that

**Comment by captainsafia** [comment]
> So just to clarify everything the only way to debug a wasm client project right now is to press F5 in Visual Studio?

Not quite. There are three different ways to debug Blazor WASM apps at the moment:

- F5 from Visual Studio
- Using the `blazorwasm` debug configuration in VS Code
- Running `dotnet run` then opening a Chrome browser with debugging ports configured then launching the app there"

There's a few technical limitations at the moment that prevent WASM from behaving well in the "start the app then attach a debugger" like https://github.com/dotnet/aspnetcore/issues/30620.

**Comment by dotnetshadow** [comment]
> 
> 
> > So just to clarify everything the only way to debug a wasm client project right now is to press F5 in Visual Studio?
> 
> Not quite. There are three different ways to debug Blazor WASM apps at the moment:
> 
>     * F5 from Visual Studio
> 
>     * Using the `blazorwasm` debug configuration in VS Code
> 
>     * Running `dotnet run` then opening a Chrome browser with debugging ports configured then launching the app there"
> 
> 
> There's a few technical limitations at the moment that prevent WASM from behaving well in the "start the app then attach a debugger" like [dotnet/aspnetcore#30620](https://github.com/dotnet/aspnetcore/issues/30620).

Awesome thanks for the summary, helps a lot. I will try a couple of the alternatives suggested much appreciated.
