### ISSUE TITLE
[crossgen2] Assertion fail occures on COMPlus_JitDump

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#54739]
### Description

Crossgen2 fails to compile SPC with COMPlus_JitDump enabled.

Build runtime with:
```
./build.sh -c Debug -s clr+libs
```
Install rutime:
```
cp -r artifacts/bin/coreclr/Linux.x64.Debug/* ../x64_debug_main/
cp -r artifacts/bin/runtime/net6.0-Linux-Debug-x64/* ../x64_debug_main/
```
Run crossgen2 with dumping knob:
```
COMPlus_JitDump="System.Reflection.Metadata.BlobReader:.ctor" ./corerun ./crossgen2/crossgen2.dll ./System.Private.CoreLib.dll -O --out ./System.Private.CoreLib.ni.dll  > dump.txt

Assert failure(PID 8552 [0x00002168], Thread: 8552 [0x2168]): Assertion failed 'unreached' in 'System.Reflection.Metadata.BlobReader:.ctor(System.Reflection.Internal.MemoryBlock):this' during 'Emit GC+EH tables' (IL size 80)

    File: /home/tmustafin/dotnet/57_runtime/src/coreclr/jit/ee_il_dll.cpp Line: 855
    Image: /home/tmustafin/dotnet/x64_debug_main/corerun

Aborted (core dumped)
```
[dump.txt](https://github.com/dotnet/runtime/files/6715839/dump.txt)

### Configuration

Runtime state: main branch on c139d00640485e8c231c54d1573dc02d7c9e8daf
OS: ubuntu 18.04
Architecture: x64

**Comment by t-mustafin** [comment]
cc @jkotas @alpencolt

**Comment by jkotas** [comment]
What is the value of `siVarLocType` when you hit this?

**Comment by t-mustafin** [comment]
```
855                 unreached(); // unexpected
(gdb) p var->loc.vlType
$1 = ICorDebugInfo::VLT_REG_REG
```

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib @AndyAyersMS.

**Comment by MichalStrehovsky** [comment]
Just for posterity - setting the environment variable enables JitDump on the JIT that is compiling crossgen2 itself. It will not dump stuff that crossgen2 is compiling. To do the latter, `--codegenopt:NGenDump=...` has to be specified instead (it's a crossgen2 command line argument).

**Comment by sandreenko** [comment]
Do you have https://github.com/dotnet/runtime/pull/54861 in your branch? I have fixed one unreached case there recently.

**Comment by AndyAyersMS** [comment]
This does not repro for me with latest bits.

**Comment by t-mustafin** [comment]
> Do you have #54861 in your branch? I have fixed one unreached case there recently.

Thanks, it works. Close the issue.
