### ISSUE TITLE
Compiled regex timeout skewed on first evaluation

### ISSUE THREAD

**Issue by Timovzl** [dotnet/runtime#54747]
### Description

When we need a performant, reusable `Regex`, we construct one, with `RegexOptions.Compiled`. We accept the one-time performance hit, and expect an instance that can be used at high performance afterwards.

The `matchTimeout` parameter lets us evaluate dynamically created expressions with a certain safety, protecting us against inefficient expressions. In this use case, we want to set a relatively small timeout. 50 milliseconds is quite a lot of time for the CPU to evaluate a single expression against a small input.

**Unfortunately, with a reasonable timeout like 50 milliseconds, the _first_ evaluation will sometimes unexpectedly exceed its timeout (about once per 7500 attempts in my test).**

This is problematic because we can no longer reliably use a reasonable timeout. We would have to use a timeout like 300 milliseconds merely to prevent the false-positive exception on the first evaluation, but such a long timeout may be unacceptable.

It does not matter how efficient the expression is. It does not matter how simple the input string is (although empty input does not suffer from the problem, perhaps due to some short-circuiting).

Unit tests confirm that the first evaluation consistently takes much longer than subsequent ones, although the amount of overhead fluctuates.

**My best guess is that the overhead on the first evaluation comes from the JIT compilation of the code generated by the `Regex`.**

### Workaround

By running the following code immediately after `Regex` construction, the problem can be worked around entirely:

```cs
// Warm up, since the first evaluation is slow and risks hitting the timeout, presumably because the compiled code needs to be JIT'ed
try
{
	_ = regex.IsMatch("");
}
catch (RegexMatchTimeoutException)
{
	// No problem, as our regex is now compiled and should be fast on further evaluations
}
```

### Minimal Repro

With xUnit:

```cs
[Fact]
public void UsuallyThrowDueToSkewedInitialEvaluationTimeout()
{
	// Parallel helps run into the timeout with fewer attempts and in less than, although a regularly loop also works with sufficient attempts
	Parallel.For(0, 30_000, _ =>
	{
		// Is complex enough to hit the issue, but evaluates in a mere ~50-500 ticks on non-first invocation
		var regex = new Regex(@"(^|[^0-9])00200\d{11}($|[^0-9])",
			RegexOptions.Compiled | RegexOptions.ExplicitCapture,
			matchTimeout: TimeSpan.FromMilliseconds(50));

		// If we enable warmup, the problem disappears
		//try
		//{
		//	regex.IsMatch("");
		//}
		//catch (RegexMatchTimeoutException)
		//{
		//	// No problem, as our regex is now compiled and should be fast on further evaluations
		//}

		// Only the initial evaluation of an instance is relevant to this test
		regex.IsMatch("Lorem 002001234567890123 ipsum dolor sit amet, consectetur adipiscing elit. Aenean ultrices eleifend volutpat.");
	});
}
```

### Suggested Solution

At least if `RegexOptions.Compiled` is given, it makes sense to me to perform the described warmup (see Workaround) in the `Regex` constructor.

This way, the `matchTimeout` parameter becomes the reliable tool it was meant to be.

The cost is that we pay a bit more for an instance if we discard it unused.

Constructing a `Regex` with `RegexOptions.Compiled` comes at a cost anyway, so it seems like the _correct_ place to pay for the overhead.

### Configuration

Tested with both .NET Core 3.1 and .NET 5, on both 64-bit Windows and 64-bit Linux, in both debug and release mode.

.NET 5 requires a slightly harder input text to reproduce the issue, and it has a smaller chance of the test doing so. It may take a few test runs to observe it. Alternatively a reduced timeout (say, 20 ms) also does the trick.

**Comment by Timovzl** [comment]
Update: On netcoreapp3.1, with a timeout of 20 miliseconds and 100K attempts, I can sometimes hit timeouts even with the workaround in place. The workaround still makes a huge difference, but in general there seem to be _enormous_ fluctuations in the evaluation time: from 50 ticks to 20 milliseconds. Could it be garbage collection pausing things for that long?

**Comment by danmoseley** [comment]
In your workaround case, are you literally compiling the empty string pattern, ie., you're causing the regex implementation to JIT? Or it would be the actual pattern, ie., you're causing code to be generated for it?

The tricky thing here would be how to fix this without causing a security problem because someone is trying to protect against compiling patterns that are unexpectedly slow to compile. (Although the timeout is to support untrusted text, not untrusted patterns, a pattern could be poorly crafted.)

**Comment by Timovzl** [comment]
> In your workaround case, are you literally compiling the empty string pattern [...]? Or it would be the actual pattern, ie., you're causing code to be generated for it?

The latter. The `regex` variable contains a `Regex` object, i.e. one that is initialized with the _actual_ pattern. I am merely performing a first evaluation against the pattern, with the empty string as the haystack. In other words, my workaround is making sure that the first ever evaluation (which seems the suffer the overhead of code compilation) is perfomed separately, prior to the first ever "real" evaluation (where we _do_ care about a timely result).

> The tricky thing here would be how to fix this without causing a security problem because someone is trying to protect against compiling patterns that are unexpectedly slow to compile. (Although the timeout is to support untrusted text, not untrusted patterns, a pattern could be poorly crafted.)

Interesting thought. So what you are saying is that people could be relying on the (supposedly unintended, and definitely undocumented) side-effect that the compilation time is included in the initial evaluation time, and thus could benefit from its timeout?

Could you explain what were to happen if compiling the pattern takes more than the specified (evaluation) timeout? My assumption is that compilation will not be interrupted, and that an exception will be thrown immediately after compilation finishes. E.g. if we specify a timeout of 1 millisecond, and compilation takes 2 milliseconds, we would get an exception after 2 milliseconds. Is that correct?

**Comment by danmoseley** [comment]
@Timovzl just came across this again -- could you use source generated regex? it should be better in all ways.
https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-source-generators

**Comment by Timovzl** [comment]
@danmoseley I agree that source-generated regexes are preferable wherever they are feasible.

For my specific scenario, the expressions are created at runtime by senior operators, so they cannot be generated at compile time.

From a general perspective, I don't think the existence of source-generated regexes excuses the issue. It makes the `matchTimeout` parameter very unreliable, which is a bit of a booby trap.

To use `matchTimeout` more-or-less reliably, the current workaround seems to be to perform at least an initial evaluation of the `Regex` within a try/catch for the `RegexMatchTimeoutException`. This still leaves the much rarer spikes on non-first evaluations, which I can only attribute to garbage collection. To counter those as well, instead, _every_ evaluation could be performed in a try/catch, with a single retry attempt that does _not_ catch.

```cs
public static bool MatchesPattern(Regex patternWithTimeout, string input)
{
	// The regex has a timeout, but to disregard delays caused by initial compilation or GC, allow one retry
	try
	{
		return patternWithTimeout.IsMatch(input);
	}
	catch (RegexMatchTimeoutException)
	{
		return patternWithTimeout.IsMatch(input);
	}
}
```

**Comment by danmoseley** [comment]
Hmm, perhaps I'm misunderstanding, but what's happening and your workaround don't seem unreasonable to me. Yes, the timeout is for untrusted text (not patterns) so it's not very interesting to protect against slow compilation. But the timeout might be being applied not just to protect against hostile input text but simply to limit the time spent period. And warming up patterns, as you're doing, is a common pattern for services - eg., on a background thread.
Finally, whenever the pattern is known at compile time, and is likely to be used, it makes sense to do precompilation with source generation, and that is possible for almost every such case.

**Comment by danmoseley** [comment]
I could imagine a scenario where the individual time needs to be capped, but also the aggregate time. In that case the calling code could measure the average time spent, and switch to a shorter timeout if it gets high. That could accommodate occasional spikes for GC or whatever reason without reducing the overall P99 responsiveness or whatever. The calling code has the power to do that too.

**Comment by Timovzl** [comment]
> Finally, whenever the pattern is known at compile time, and is likely to be used, it makes sense to do precompilation with source generation, and that is possible for almost every such case.

Agreed, except for the fact that there is no documentation stating that JIT compilation happens on the first evaluation rather than on construction. Shouldn't we expect only very few developers to realize this?

> But the timeout might be being applied not just to protect against hostile input text but simply to limit the time spent period.

Interesting point. I had not considered that interpretation.

My own use case and expectation was limiting the complexity of the work, i.e. throwing if the _input_ is at fault. The alternative is limiting the total time spent, i.e. throwing if too much time has elapsed regardless of what caused this.

I do find myself wondering which is the more common requirement. I'm leaning towards the former. The [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.matchtimeout#remarks) is too, when it states the purpose of the parameter:

> This prevents the regular expression engine from processing input strings that require excessive backtracking.

If the goal is to protect against input strings that require excessive backtracking, then significant fluctuations caused by initial compilation or garbage collection are making it harder to tune in for that goal.

The effects of getting it wrong are also quite severe. Ideally, if a second is spent on garbage collection, handling a request takes a second longer - unfortunate, but not often problematic. Currently, however, that second spent doing garbage collection can turn an acceptable input into an unacceptable one, resulting in an exception.

It seems to me that at the very least the documentation should warn a developer to consider these influences when picking a timeout. Even then, it's hard to use for the stated purpose, because the average regex evaluation duration pales next to worst-case GC or compilation times.

**Comment by danmoseley** [comment]
@Timovzl we'd welcome PR's to the docs if you have suggested wording (just click the pencil button on the doc page)

The timeout was added for denial of service protection. ([like this example with .NET regex](https://stackstatus.tumblr.com/post/147710624694/outage-postmortem-july-20-2016)). To a first order I would expect attacks on backtracking would cause delays much longer than any reasonable GC pause. But, this is just speculation.

I do think docs are the next step here. Feel free to offer PR or issue into https://github.com/dotnet/docs or https://github.com/dotnet/dotnet-api-docs.

**Comment by danmoseley** [comment]
cc @dotnet/area-system-text-regularexpressions though, I don't own this area.
