### ISSUE TITLE
System.Net tests failing with System.TimeoutException

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#54778]
For example:
- Test: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.**Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection**
```  System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(timeoutPropertyName: "PooledConnectionLifetime") [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs(196,0): at System.Net.Test.Common.Http2LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(1441,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_ConnectionPooling_Test.Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection(String timeoutPropertyName)
        --- End of stack trace from previous location ---
```

**Comment by jkotas** [comment]
Failed in #54656

**Comment by jkotas** [comment]
Failed in #54774

**Comment by karelz** [comment]
Failures **4/28-6/27 (incl. PRs)**:

Date | Test | Details
-- | -- | --

- 6/8:
  - (Http2) GetAsync_Redirect_CookiesArePreserved - 5 failures in PR #53851 - 2 Windows, 3 Linux
- 6/18:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 2 failures in PR #54437 - all Linux
  - GetAsync_ResponseHasNormalLineEndings_Success - 1 failure in PR #54437 - Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 2 failures in PRs - Windows and Linux
- 6/23:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 8 failures in PRs - some Windows (7 failures in PR #53851)
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 1 failure in PR #54437 - Linux
- 6/24:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 2 failures in PRs - all Linux
  - GetAsync_ResponseHasNormalLineEndings_Success - 1 failure PR #54437 - Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 1 failure in PR #54698 - Linux
- 6/25:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 29 failures in PRs - all Linux
  - GetAsync_ResponseHasNormalLineEndings_Success - 15 failures in PRs - all Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 19 failures in PRs - all Linux
- 6/26:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 12 failures in PRs - all Linux
  - GetAsync_ResponseHasNormalLineEndings_Success - 4 failures in PRs - all Linux
  - SocketsHttpHandlerTest_Cookies_Http3_Mock.GetAsync_Redirect_CookiesArePreserved - 14 failures (8 in Official runs, 6 in PRs) - 2x Windows, 2x OSX, 10x Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 8 failures in PRs - all Linux
- 6/27:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 4 failures in PRs - all Linux
  - GetAsync_ResponseHasNormalLineEndings_Success - 4 failures in PRs - all Linux
  - SocketsHttpHandlerTest_Cookies_Http3_Mock.GetAsync_Redirect_CookiesArePreserved - 5 failures on Official runs - 1 OSX, 4 Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 5 failures in PRs - all Linux
- 6/28:
  - Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection - 7 failures in PRs - all Linux
  - SocketsHttpHandlerTest_Cookies_Http3_Mock.GetAsync_Redirect_CookiesArePreserved - 2 failures (1 official run, 1 PR) - all Linux
  - SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders - 3 failures in PRs - all Linux

**Comment by karelz** [comment]
Looks like a regression around 6/18 ... @dotnet/ncl any idea what might have caused the regression?

**Comment by karelz** [comment]
@geoffkizer 2 of the tests are HTTP/2 cookies tests -- is it perhaps caused by your PR #54727?

**Comment by geoffkizer** [comment]
Yes, these tests were disabled until that PR.

Looks like these are still flaky, and apparently much flakier on Linux than Windows for whatever reason.

We should disable these again. I'll put up a PR.

**Comment by karelz** [comment]
Thanks @geoffkizer! We still have 3 tests not covered by your PR ... we need to figure out what to do about them and likely disable them as well.

**Comment by geoffkizer** [comment]
I'm seeing a ton of TimeoutExceptions on my PR to disable these tests. For example: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54843-merge-5fea1e54014e4d049e/System.Net.Http.Functional.Tests/console.1c5cee98.log?sv=2019-07-07&se=2021-07-18T17%3A51%3A18Z&sr=c&sp=rl&sig=eMv7cbmp3wfyHjUEuXsbeRsXa%2FtVrWqCy%2FPhbk8pVPQ%3D

Not sure what is going on here, but it doesn't look isolated to any particular test(s).

**Comment by MihaZupan** [comment]
Numbers for `System.Net.` failures within the last 15 days, sorted by the number of failures per Queue+Method combination:

[Query](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA42QQWvCQBCF7/6KIacEtOChxwhtQbBQaWugRxmzY7LG7MrMBEnpj+9EqQrtoXtZ2Nn33jevINF3km6vMvqCY01MUPQHAlFklaPXGpJVL0rt3ZI0GYEdDA7OIshzSObo99dBulIsm4KxJChjUPRBIClqgnggRvUxQI0C6ltyEDtNIDK8kAhW/1VkxrqLPkDjg8t9CMSQPseNwM8OIWr6yoNePcmNLXdh8JnYfpUPVZKZ5MBxR6VOmAK2BGZ0qiA/NZGBxdvTwl0KWg3dGMoMsIrp9N5lo9vct446Wg5O11hrhqN3f5J/RG4WVrDcJknXtsj+k+ApGrLBlMOdZmN42G6NltwjYyhr2y4HZMZ+vadQaZ222NBaSNPzhyyDTQ8XqLF1rXW8bvPLbgZTG0Z2xmbKU/437na6sSgCAAA=)

QueueName | Count | AffectedBranches | Method
-- | -- | -- | --
ubuntu.1604.amd64.open.rt | 44985 | 67 | IncompleteResponseStream_ResponseDropped_CancelsRequestToServer
ubuntu.1604.amd64.open.rt | 42037 | 65 | GetAsync_AddMultipleCookieHeaders_CookiesSent
ubuntu.1604.amd64.open.rt | 39586 | 63 | TestLoopbackAsync
ubuntu.1604.amd64.open.rt | 31387 | 64 | Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection
ubuntu.1604.amd64.open.rt | 24829 | 59 | PlaintextStreamFilter_SimpleDelegatingStream_Success
ubuntu.1604.amd64.open.rt | 23595 | 54 | GetAsync_MissingExpires_ReturnNull
ubuntu.1604.amd64.open.rt | 23360 | 58 | SendAsync_WithZeroLengthHeaderName_Throws
ubuntu.1604.amd64.open.rt | 23359 | 48 | PostAsync_ManyDifferentRequestHeaders_SentCorrectly
ubuntu.1604.amd64.open.rt | 23341 | 55 | SendAsync_RequestWithSimpleHeader_ResponseReferencesUnmodifiedRequestHeaders
ubuntu.1604.amd64.open.rt | 23097 | 50 | ConnectCallback_BindLocalAddress_Success
ubuntu.1604.amd64.open.rt | 22550 | 58 | GetAsync_SetCookieContainer_CookieSent
ubuntu.1604.amd64.open.rt | 22322 | 52 | PlaintextStreamFilter_ExceptionDuringCallback_ThrowsHttpRequestExceptionWithInnerException
ubuntu.1604.amd64.open.rt | 21382 | 55 | SetAfterUse_Throws
ubuntu.1604.amd64.open.rt | 21333 | 53 | HttpClientHandler_MultipleAuthenticateHeaders_WithSameAuth_Succeeds
ubuntu.1604.amd64.open.rt | 20900 | 49 | PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly
ubuntu.1604.amd64.open.rt | 20598 | 55 | ReadAsStreamAsync_EmptyResponseBody_HandlerProducesWellBehavedResponseStream
ubuntu.1604.amd64.open.rt | 20165 | 51 | SendAsync_RequestHeaderInResponse_Success
ubuntu.1604.amd64.open.rt | 20165 | 51 | SendAsync_MultipleExpected100Responses_ReceivesCorrectResponse
ubuntu.1604.amd64.open.rt | 19627 | 42 | DisposeTargetStream_ThrowsObjectDisposedException
ubuntu.1604.amd64.open.rt | 19185 | 49 | ExecutionContext_Suppressed_Success
ubuntu.1604.amd64.open.rt | 17697 | 47 | SendRequest_UriPathHasReservedChars_ServerReceivedExpectedPath
ubuntu.1604.amd64.open.rt | 17413 | 48 | HPack_HeaderEncoding
ubuntu.1604.amd64.open.rt | 13965 | 40 | GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly
ubuntu.1604.amd64.open.rt | 10837 | 31 | GetAsync_CookiePathDoesNotMatchRequestPath_CookieAccepted
ubuntu.1604.amd64.open.rt | 10290 | 31 | GetAsync_ResponseHasNormalLineEndings_Success
ubuntu.1604.amd64.open.rt | 8575 | 24 | GetAsyncWithBasicAuth_ReceiveSetCookie_CookieSent
ubuntu.1604.amd64.open.rt | 6860 | 17 | GetAsync_Redirect_CookiesArePreserved
ubuntu.1604.amd64.open.rt | 5145 | 12 | GetAsyncWithRedirect_ReceiveSetCookie_CookieSent
sles.15.amd64.open.rt | 4900 | 15 | Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection
ubuntu.1604.amd64.open.rt | 4165 | 14 | GetAsyncWithRedirect_SetCookieContainer_CorrectCookiesSent
ubuntu.1804.amd64.open.rt | 2940 | 12 | GetAsync_ResponseHasNormalLineEndings_Success
ubuntu.1604.amd64.open.rt | 2713 | 3 | ConnectCallback_ContextHasCorrectProperties_Success
sles.15.amd64.open.rt | 2450 | 10 | GetAsync_ResponseHasNormalLineEndings_Success
ubuntu.1804.amd64.open.rt | 1715 | 5 | GetAsyncWithBasicAuth_ReceiveSetCookie_CookieSent
ubuntu.1804.amd64.open.rt | 1715 | 6 | Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection
sles.15.amd64.open.rt | 1470 | 6 | PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly
sles.15.amd64.open.rt | 1225 | 4 | GetAsyncWithRedirect_SetCookieContainer_CorrectCookiesSent
ubuntu.1804.amd64.open.rt | 1225 | 4 | GetAsyncWithRedirect_ReceiveSetCookie_CookieSent
ubuntu.1804.amd64.open.rt | 1225 | 5 | GetAsync_Redirect_CookiesArePreserved
sles.15.amd64.open.rt | 1225 | 5 | TestLoopbackAsync

(there are more)

The failures seem to be Linux-related, with `ubuntu.1604.amd64.open.rt` being by far the most affected.

**Comment by karelz** [comment]
Here's breakdown of main branch per date, demonstrating that something happened on 6/23:

Failures 3/12-6/29 (incl. PRs) - main branch:
Date | Number of Timeout failures | Details
-- | -- | --
6/19 | 2 | Official run - 2
6/20 | 1 | Official run - 1
6/21 | 1 | Official run - 1
6/22 | 2 | Official run - 2
6/23 | 43 | PR #54437 - 29, PR #53851 - 7, PR #54618 - 4, PR #54610 - 1, PR #54053 - 1, Official run - 1
6/24 | 81
6/25 | 437
6/26 | 224
6/27 | 134
6/28 | 694
6/29 | 357 | from 10 hours only

Total 6/23-6/29: 1970

**Comment by geoffkizer** [comment]
Some of these tests are pretty basic -- single request, no delays or timing issue, etc. Strange.

**Comment by karelz** [comment]
Yes, it almost feels like something changed in infra ...

**Comment by karelz** [comment]
@geoffkizer I updated the table -- there are 4 tests in *_Http3_Mock category. Could they have regressed due to your recent changes?

**Comment by MattGal** [comment]
@karelz it's quite easy for me to re-send a job from > 4 days ago to the current machines and see if it still has the problem, even repeatedly if that's useful.  Just pick a "blessed" one and I can send it around.

 Some more thoughts:

- Helix Machines didn't change on the 23rd, the last rollout was on the 24th, so if you're looking at this happening "around 6/18-6/23", the machines did not change.
- The only linux things that changed in that time were RedHat 7 and SLES 12.  Nothing else about, say, the ubuntu.1604.amd64.open.rt image changed in that time frame (image version, artifacts applied, etc).

**Comment by MihaZupan** [comment]
The mass failures across all PRs started happening somewhere around 9pm on the 24th (+- a few h) - that is why I am suspicious of https://github.com/dotnet/runtime/commit/c88da2905317c0b199c5814594f1ea5d079e0760).

@MattGal Would you be able to run CI on the runtime at https://github.com/dotnet/runtime/commit/1d84e014ac2b6d11b1ddc452ce1a7706395abcb6 (parent of the above commit)?

I've been running CI on a revert of the commit in https://github.com/dotnet/runtime/pull/54939 and haven't hit a timeout failure yet.

**Comment by MattGal** [comment]
> @MattGal Would you be able to run CI on the runtime at [1d84e01](https://github.com/dotnet/runtime/commit/1d84e014ac2b6d11b1ddc452ce1a7706395abcb6) (parent of the above commit)?

Yes but I need some details about what you're interested in, please ping me on Teams?

**Comment by geoffkizer** [comment]
> there are 4 tests in *_Http3_Mock category. Could they have regressed due to your recent changes?

GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly is a test I enabled for HTTP3 in my PR. so it's possible that this is a separate regression from whatever else is going on here. But it seems like we should figure out the general issue here first.

**Comment by MihaZupan** [comment]
Looks like the failures stopped with #55006.

**Comment by karelz** [comment]
There are still some occurrences of test `Http2_SmallConnectionTimeout_SubsequentRequestUsesDifferentConnection` failures after 7/1 when the above was supposed to be addressed, though they seem to be :

Day | Failures
-- | --
7/2 | 1x PR #54884 - PR from 6/29
7/5 | 2x PR #55182 (testing PR for this issue)
7/6 | 3x PR #55182 (testing PR for this issue)
7/7 | 1x PR #54949 - PR from 6/30
7/8 | 4x PR #55292 (testing PR for this issue)
7/20 | 1x PR #53949 - old PR from 6/9
