### ISSUE TITLE
Entrypoint verification should work on Apple platforms

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#54784]
If you add a new entry point in the unix shims, but forget to add it to `entrypoints.c`, you get a nice build error:

```
EXEC : error : /workspaces/runtime/src/libraries/Native/Unix/System.Security.Cryptography.Native/entrypoints.c file did not match entries exported from /workspaces/runtime/artifacts/obj/native/net6.0-Linux-Debug-x64/System.Security.Cryptography.Native/libSystem.Security.Cryptography.Native.OpenSsl.so [/workspaces/runtime/src/libraries/Native/build-native.proj]
  DIFFERENCES FOUND: 
  CryptoNative_Foob
  ninja: build stopped: subcommand failed.
```

This does not appear to work for macOS. Adding a new exported function and omitting it from `entrypoints.c` does not fail the build.

**Comment by vcsjones** [comment]
I implemented this, and there are a number of crypto things that are not in `entrypoints.c`:

> AppleCryptoNative_DigestReset,AppleCryptoNative_EcdhKeyAgree,AppleCryptoNative_SecKeychainEnumerateCerts,AppleCryptoNative_SslCopyCADistinguishedNames,AppleCryptoNative_SslCopyCertChain,AppleCryptoNative_SslIsHostnameMatch,AppleCryptoNative_SslRead,AppleCryptoNative_SslSetBreakOnClientAuth,AppleCryptoNative_SslSetBreakOnServerAuth,AppleCryptoNative_SslSetIoCallbacks,AppleCryptoNative_SslWrite,AppleCryptoNative_X509ChainCreate,AppleCryptoNative_X509DemuxAndRetainHandle,AppleCryptoNative_X509GetPublicKey,AppleCryptoNative_X509StoreAddCertificate,AppleCryptoNative_X509StoreRemoveCertificate

Should this be fixed?

**Comment by jkotas** [comment]
cc @VSadov

**Comment by VSadov** [comment]
Yes, the idea is that it should work on all platforms. I do not remember if there was any reason why this does not work on OSX. 

And the mismatches need to be fixed.

**Comment by VSadov** [comment]
It is possible that when validation script was switched from Python to bash, it stopped working on OSX.

**Comment by VSadov** [comment]
@vcsjones - 
> I implemented this, and there are a number of crypto things that are not in entrypoints.c:

Did you implement  the part that enables `verify-entrypoints.sh` to work on OSX and now see the failures, or added those new functions?

**Comment by vcsjones** [comment]
> Did you implement the part that enables verify-entrypoints.sh to work on OSX and now see the failures

Correct. Picking the first one as an example, here is the export:

https://github.com/dotnet/runtime/blob/118c530033b43d47fcabab00efce414d5e4fd19c/src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/pal_digest.h#L73

but it is nowhere in here:

https://github.com/dotnet/runtime/blob/main/src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/entrypoints.c


> And the mismatches need to be fixed.

I will submit a PR to correct these along with a working validation script.

**Comment by VSadov** [comment]
> I will submit a PR to correct these along with a working validation script.

Thanks!!
