### ISSUE TITLE
HostFXR managed bindings

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#54788]
## Background and Motivation

[GmodDotNet](https://github.com/GmodNET/GmodDotNet) is a c++ binary, that loads .NET runtime and .NET assemblies to game's (Garry's Mod) process.
With [NativeAot](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT) i was able to make a `.dll` that can be directly loaded into game ([MagicTrick Project](https://github.com/SupinePandora43/MagicTrick))

so it would be possible (as an option) to convert [native c++ side](https://github.com/GmodNET/GmodDotNet/tree/f5dec89c995847ca4793c2ae3a8a2c039025064a/gm_dotnet_native) to c#

it will let others integrate .NET runtime more easily to something that loads c binaries without even writing c/c++ code

~why? i don't know~

## Proposed API

HostFXR api

## Usage Examples

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs

## Risks

Launching runtime from runtime could be unstable.

**Comment by vitek-karas** [comment]
There are some rare scenarios where calling `hostfxr` from managed code makes sense - discovering list of runtimes/SDKs (SDK does that now) or resolving SDK version (MSBuild/SDK does that).

The case where one uses NativeAot to build the "native" entry-point which then invokes managed code is another one I guess. But in this case, why not run everything via NativeAot then? The only reason I can come up with is that the managed code to be executed cannot run under NativeAot (dynamic plugin systems for example can't).

Also just providing the PInvoke definitions is not ideal as the `hostfxr` API is designed for C/C++ invocation. Providing a managed API would include wrapping it with small helpers to turn things into proper managed code behaviors. For example return `IEnumerable` from the functions which return lists of things.

All in all I don't see much value in providing (and maintaining) official managed API for hostfxr.

**Comment by vitek-karas** [comment]
The more I think about this - if there's interest, this would be a great NuGet package, but currently I don't see enough interest in this to make it an official part of the .NET product.
