### ISSUE TITLE
Why does ReadOnlySpan<char> == (equals) fails?

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#54793]
The following code says it's not equal. Without slicing, i.e. it succeed. Why?! Both ReadonlySpan<char>'s when calling `ToString()` have the same output and matches the string it compares against, see output below.

### Code
```C#
using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine(Check("aHello World", 1)); //Returns FALSE, i.e. fails
		//Without slicing, it works
		Console.WriteLine(Check("Hello World", 0)); //Returns TRUE, i.e. fails
	}
	
	static bool Check(string s, int slicePos) {
		var span = s.AsSpan();
		var newSpan = span.Slice(slicePos);
		Console.WriteLine(newSpan.ToString()); //Print out span
		return newSpan == "Hello World";
	}
}
```
### Output
```
Hello World
False
Hello World
True
```

Tested on https://dotnetfiddle.net/ with .NET5 (and local with .NET6 on Windows 10.) There might be a very simple reason but I don't see it.

**Comment by GalaxiaGuy** [comment]
It seems the version without slicing works "by chance". If you construct a new string that looks the same but isn't the literal "Hello World" it probably won't.

From the docs on ReadOnlySpan:

https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1.op_equality

> This tests if two ReadOnlySpan<T> instances point to the same starting memory location, and have the same Length values. This does not compare the contents of two ReadOnlySpan<T> instances

**Comment by GrabYourPitchforks** [comment]
As @GalaxiaGuy said, `Span<T>`'s equality operator compares the memory addresses and the length, not the contents. If you want to compare the contents, use [`SequenceEqual`](https://docs.microsoft.com/dotnet/api/system.memoryextensions.sequenceequal) instead.

```cs
ReadOnlySpan<char> theSpan = GetSpan();
if (theSpan.SequenceEqual("Some string literal")) { /* do something */ }
```

**Comment by Symbai** [comment]
@GrabYourPitchforks When it compares the memory addresses how can the example above return TRUE? The string can NEVER have the same memory address than the span. It should be a bug then

**Comment by GalaxiaGuy** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.string.intern?view=net-5.0

> For example, if you assign the same literal string to several variables, the runtime retrieves the same reference to the literal string from the intern pool and assigns it to each variable.

**Comment by Symbai** [comment]
Thanks, this was very confusing. Is there a reason why ReadOnlySpan<char> == string is allowed? It sounds like this shouldn't be used so I wonder why this is possible. Maybe the analyze should treat this as error instead of a warning (it could be fixed by calling AsSpan method on the string).

**Comment by Joe4evr** [comment]
> Is there a reason why ReadOnlySpan == string is allowed?

It happens to fall out from `string`'s implicit conversion to `ROS<char>` so the `==` operator is eligible to resolve to.
