### ISSUE TITLE
Static fields should not contribute to cyclic struct layout 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#5479]
Consider the following code: 

```c#
class Program
{
    static void Main(string[] args)
    {
        var x = MyStruct.Empty;
    }

    public struct MyStruct
    {
        public static readonly MyStruct? Empty = null;
    }
}
```

This code will compile with C# 6.0 and is legal according to the CLI spec.  The type definition is recursive but the layout of the struct is not because the field involved here is static.  The CLR is unable to handle this though and fails at runtime with a `TypeLoadException`:

> Unhandled Exception: System.TypeLoadException: Could not load type 'ConsoleApplication1.Program+MyStruct' from assembly 'ConsoleApplication59, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by mangod9** [comment]
Closing since there doesnt seem to be any particular reasons to be fix in the near term.
