### ISSUE TITLE
Add Dispose/IDisposable to GCHandle

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#54792]
> Follow up from @jkotas's comment: https://github.com/dotnet/runtime/issues/19459#issuecomment-854001647. The same issue also contains an extensive conversation about this proposal, with some practical use case scenarios as well (in particular, see this comment by @jkoritzinsky: https://github.com/dotnet/runtime/issues/19459#issuecomment-855132396).

## Proposed API

```diff
namespace System.Runtime.InteropServices
{
      public struct GCHandle
+        : IDisposable
      {
+        public void Dispose();
      }
}
```

## Usage Examples

```csharp
// Given...
[DllImport("nativelib")]
public static unsafe extern void DoCallback(IntPtr state, delegate*<IntPtr, void> callback);

[UnmanagedCallersOnly]
public static void Callback(IntPtr state)
{
    GCHandle handle = GCHandle.FromIntPtr(state);
    object state = handle.Target;
}

// ...this PR would enable this
using (GCHandle handle = GCHandle.Alloc(state))
{
    DoCallback(handle, &Callback);
}
```

## Risks

Copying/boxing a `GChandle` value and calling `Dispose` on each copy will still possibly result in a crash. This is the same behavior as other approved APIs already though (eg. `DependentHandle`), and it's a limitation with C# not having proper move semantics.

**Comment by AaronRobinsonMSFT** [comment]
Based on the conversation in https://github.com/dotnet/runtime/issues/19459 I think there is enough to move onto an API review.

**Comment by stephentoub** [comment]
I assume the behavior / implementation is just:
```C#
public void Dispose() => Free();
```

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub I think it would check for `IntPtr.Zero` first.

```csharp
public void Dispose()
{
    if (_handle != IntPtr.Zero)
        Free();
}
```

**Comment by stephentoub** [comment]
Yup. Thanks.

**Comment by jkotas** [comment]
> public void Dispose()
> {
>    if (IsAllocated)
>        Free();
> }

This implementation is both not thread safe (you cannot safely call it from multiple threads and assuming first one wins) and slower than necessary (pays extra for the interlocked compare change inside Free).

I think we would either want thread safe implementation; or non-thread safe fast implementation (w/o interlocked compare exchange).

**Comment by stephentoub** [comment]
> I think we would either want thread safe implementation; or non-thread safe fast implementation (w/o interlocked compare exchange).

Yes, sorry, I was just trying to ask about the semantics of what Dispose did, rather than actually implement it in a comment.

From a thread-safety perspective, I think it'd be really confusing/error-prone if Free and Dispose had different thread-safety guarantees, so my preference would be to have Dispose use CompareExchange, e.g.
```C#
IntPtr handle = Interlocked.Exchange(ref _handle, IntPtr.Zero);
if (handle != IntPtr.Zero)
    InternalFree(GetHandleValue(handle));
```

**Comment by MichalStrehovsky** [comment]
Is `IDisposable` on a struct really a good idea?

As a quick poll:

```csharp
var m = MyStruct.Alloc();
using (m)
{
}
Console.WriteLine(m);

struct MyStruct : IDisposable
{
    private bool _isUsed;

    public static MyStruct Alloc() => new MyStruct { _isUsed = true };

    public void Dispose()
    {
        _isUsed = false;
    }

    public override string ToString()
    {
        return $"IsUsed: {_isUsed}";
    }
}
```

People whose intuition says this is going to print `IsUsed: true`, can you give this comment a "Laugh" reaction? If you think this will print `IsUsed: false`, can you give this comment a "Confused" reaction?

**Comment by stephentoub** [comment]
> Is IDisposable on a struct really a good idea?

We do it in other advanced places that have a similar potential for misuse,  e.g.
https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memoryhandle.dispose?view=net-5.0

**Comment by stephentoub** [comment]
> Note that the thread-safety guarantee in Free is nearly useless

If we really believe it's useless, then we should remove it from both.

My point is that I think Free and Dispose should make the same guarantees.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Runtime.InteropServices
{
    public struct GCHandle : IDisposable
    {
        public void Dispose();
    }
}
```

**Comment by AaronRobinsonMSFT** [comment]
Given some of the fallout from https://github.com/dotnet/runtime/pull/55596, I think we need to consider the impact of this change. Moving back to API needs work.

**Comment by Neme12** [comment]
I don't think the issue with xunit should block this API. This could happen when any type whatsoever starts implementing `IDisposable`. And it's only in tests - users can change their code. This issue wouldn't come from a library.

**Comment by Sergio0694** [comment]
Superseded by #94134, closing this.
