### ISSUE TITLE
IMetaDataImport::EnumMemberRefs is always empty in .NET 6 preview

### ISSUE THREAD

**Issue by kalikin** [dotnet/runtime#54795]
Hello. 
In our profiler we have always used [IMetaDataImport::EnumMemberRefs](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/imetadataimport-enummemberrefs-method) without a problem. But in .NET  6.0.100-preview.5.21302.13 the enumerator always appears to be empty, i.e. the *pcTokens* is always 0.

It is not reproducible on .NET 5.0 and earlier versions. I haven't tried other .NET  6 versions until now. 
So far, I've tried the preview only on Linux x64.

I made [a small repository](https://github.com/kalikin/enumMemberRefs) which demonstrates the problem.

**Comment by jkotas** [comment]
Looks like a regression introduced by #50471

cc @janvorli @tmds
