### ISSUE TITLE
What exactly is the managed calling convention?

### ISSUE THREAD

**Issue by nike4613** [dotnet/runtime#54796]
I have been working on some stuff which (intentionally) relies on runtime internals such as the managed calling convention to facilitate higher-level functionality. To figure out what exactly it is, I have been referencing [this document](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md) which seems to be a mostly accurate description. From what I can tell, that document describes the managed calling convention as the platform's native calling convention, with the following argument order: `this` pointer (if present), return buffer pointer (if present), generic context (if present), all other arguments.

On [Windows x64](https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#parameter-passing), I would expect the following:

The managed method
```cs
int DoSomething(int arga, int argb)
```
should be equivalent to this C definition:
```c
int DoSomething(void* thisptr, int arga, int argb);
```
which would have no return buffer, and have `thisptr` in `rcx`, `arga` in `rdx`, and `argb` in `r8`. And this is exactly what I see. All is well so far.

But this seems to break down somewhat once there are arguments on the stack. The Windows x64 calling convention page states that all arguments beyond the first 4 are pushed, in reverse order, to the stack, such that the top of the stack is the first argument which is not passed in a register.

While looking around the codebase, I came across [the comment describing `fgCanFastTailCall`](https://github.com/dotnet/runtime/blob/v5.0.7/src/coreclr/src/jit/morph.cpp#L6588), which mentions in its section about Windows AMD64 that each argument on the stack is either in one register or in one 8-byte stack slot. This already seems inconsistent with the native calling convention, which, unless I'm blind, mentions nothing about fix-size stack slots, and in fact, its examples very much seem to contradict that.

But there's more that, as far as I can tell, is entirely undocumented anywhere. 

I was looking into the calling convention for the following method:
```cs
class GenericSrc<T>
{
    public void FromSTCtx(T value, int a, int b, int c, int d, int e, int f); // the implementation is not important
}
```
Specifically, the instantiation of it with the type argument `System.String`, which makes it a shared implementation.

What I would *expect* this method's calling convention to look like just before `call`ing to it is as follows (stack is indexed starting from the top of it, going down):
Argument | Location
------------|----------
*`this` pointer* | `rcx`
*generic context* | nowhere, because the runtime gets generic information from the `this` pointer
`value` | `rdx`
`a` | `r8`
`b` | `r9`
`c` | top of stack
`d` | stack[1]
`e` | stack[2]
`f` | stack[3]

Importantly for me, this would mean that I could *theoretically* pop the return address after the call, push whatever's in `b`, and be able to pretend like there was one more argument at the start. 

This is *not* what I have observed however.

The way this method is called instead looks like this (at least when the .NET assembly is built in debug mode):
Argument | Location
------------|----------
*`this` pointer* | `rcx`
`value` | `rdx`
`a` | `r8`
`b` | `r9`
*`this` pointer (again)* | top of stack
`value` *(again)* | stack[1]
`a` *(again)* | stack[2]
`b` *(again)* | stack[3]
`c` | stack[4]
`d` | stack[5]
`e` | stack[6]
`f` | stack[7]

This doesn't seem to correspond with any calling convention I have ever heard of, and *certainly* isn't documented. It almost seems unintentional even. I say this because it seems like generated method bodies *don't even use* the duplicated arguments on stack, instead using only the values passed in registers.

**What exactly is the managed calling convention?**

**Comment by Wraith2** [comment]
Does https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md#calling-convention-specifics-for-x86 help?

**Comment by teo-tsirpanis** [comment]
The simplest and less informative answer would be that it is an implementation detail. Once it is documented it will start being depended upon by code like yours, which might limit future innovation and optimization opportunities. I am not knowledgeable on the matter at all but I bet that using the _managed_ calling convention over _unmanaged_ code is exactly as unsupported as it sounds. Besides, there are lots of managed concepts like object references that the GC may move at almost any time, generics, and more, that unmanaged languages have no qeuivalent and cannot grasp.

**Comment by nike4613** [comment]
> The simplest and least informative answer would be that it is an implementation detail. Once it is documented it will start being depended upon by code like yours, which might limit future innovation and optimization opportunities. I am not knowledgeable on the matter at all but I bet that using the _managed_ calling convention over _unmanaged_ code is exactly as unsupported as it sounds. Besides, there are lots of managed concepts like object references that the GC may move at almost any time, generics, and more, that unmanaged languages have no qeuivalent and cannot grasp.

I am quite aware of this. However, this is something which *must* be done with the managed calling convention, as my goal here is detouring generic methods like existing tools such as MonoMod are already able to do for non-generic methods. I already have code which is capable of, and *successfully*, rewrites generic contexts, and the only remaining problem is when I need to insert a new generic context argument to make the detour work, which may require moving an argument to the stack. 

Even if all I can get are pointers to where in the codebase I can look to find this stuff out, that will still be a great boon for me.

**Comment by SingleAccretion** [comment]
I believe what you are observing here is the "outgoing args space" (or at least that's the term RyuJit uses internally). It is documented [here](https://docs.microsoft.com/en-us/cpp/build/stack-usage?view=msvc-160#stack-allocation):
> The parameter area is always at the bottom of the stack (even if alloca is used), so that it will always be adjacent to the return address during any function call. It contains at least four entries, but always enough space to hold all the parameters needed by any function that may be called. Note that space is always allocated for the register parameters, even if the parameters themselves are never homed to the stack; a callee is guaranteed that space has been allocated for all its parameters

**Comment by jakobbotsch** [comment]
> While looking around the codebase, I came across the comment describing fgCanFastTailCall, which mentions in its section about Windows AMD64 that each argument on the stack is either in one register or in one 8-byte stack slot. This already seems inconsistent with the native calling convention, which, unless I'm blind, mentions nothing about fix-size stack slots, and in fact, its examples very much seem to contradict that.

What the comment is saying is that arguments never take up a variable amount of stack slots in AMD64 on Windows. All arguments take up exactly one stack slot because they are either passed by value in <= 8 bytes, or they are passed as a pointer. This is also the case in the native calling convention. This is not the case in for instance the SysV calling convention, where larger arguments can still be passed by value, occupying multiple stack slots in the callee's stack frame (assuming you count the argument area as the callee's stack frame). 

> This doesn't seem to correspond with any calling convention I have ever heard of, and certainly isn't documented.

What you are observing here is the shadow stack space. It is also the case for the native calling convention, see for example the disassembly here: https://godbolt.org/z/Mo5456hjj
The `c` argument starts at `rsp+40`, after the shadow space for `this`, `value`, `a` and `b`.

It's very possible the native compiler does a better job of not spilling the first four arguments into the shadow space when not required.

Note that there is a reason for the calling convention to have this shadow space: it vastly simplifies the handling of variadic args.
In that case the compiler just spills the first four arguments into the shadow space and then handling variadic args is simple.
See for instance this disassembly: https://godbolt.org/z/G3jsTjdsr
From the caller's perspective, calling both `Foo` and `Bar` are similar, but the compiler uses the shadow space to handle the variadic args by first spilling the argument registers into that area.

**Comment by jakobbotsch** [comment]
There are some minor differences between the managed and native calling convention, but I believe for the most part they are compatible. One difference is that in the managed calling convention, the callee widens return values up to 4-bytes, which is not the case for the native calling convention.

@jkoritzinsky might know of more examples.

**Comment by sandreenko** [comment]
Hi @nike4613 , I believe you got an answer to your question. As a summary:
1. the managed calling convention is an implementation detail. All who relies on the current implementation are risking;
2. if you need communication with another language use interop and we will generate calls using native calling conv;
3.  we are planning to further divert the managed calling convention from the native on all platforms in the next releases;
4. we are thinking about adding stress modes like: pass X arguments in registers, pass return value in Y, pass arguments in different order etc. The expectation is that if we change
https://github.com/dotnet/runtime/blob/69711860262e44458bbe276393ea3eb9f7a2192a/src/coreclr/jit/targetamd64.h#L254
```
#define REG_NATIVE_INTRET               REG_EAX 
#define REG_MANAGE_INTRET             REG_AnyReg
```
everything should keep working.

>  However, this is something which must be done with the managed calling convention.

I do not see where this "must" comes from.

**Comment by AndyAyersMS** [comment]
I don't see why this issue is marked as 6.0 -- so I'm going to move it to future.

**Comment by sandreenko** [comment]
> I don't see why this issue is marked as 6.0 -- so I'm going to move it to future.

it will be closed automatically in 12 days as I was told.

**Comment by nike4613** [comment]
@SingleAccretion @jakobbotsch It seems like I am seeing the shadow stack space, thanks.

@sandreenko I am fully aware that it is an implementation detail, and that it is subject to change; that is fine. I would like it to be documented *somewhere* in this repo, whether somewhere in the BOTR or in some (preferably interlinked) place in code that can easily be read.

> I do not see where this "must" comes from.

The "must" came from the way I was approaching generic patching. In particular, I was trying to avoid generating untold numbers of helper methods to correctly patch any given method by having a small hand-written assembly helper to transform a call with no explicit generic context parameter to one with an explicit generic context parameter. However, after messing with that and thinking about how to port it to other platforms, I think I will just generate lots of helpers anyway. Its simpler that way.

However, having knowledge of the managed calling convention can still let me limit the number of methods which I am actually patching by combining similar-enough parameter types (reference types -> `object`, in-register integer -> `IntPtr`, etc).

I still request some more centralized/comprehensive descriptions of the calling convention.

**Comment by jakobbotsch** [comment]
The ABI is detailed in [clr-abi.md](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/clr-abi.md) so I will close this.
