### ISSUE TITLE
.NET 6 Preview 5, WebAssembly Double Parse Issue in (RTL Arabic) Chrome

### ISSUE THREAD

**Issue by smjltd** [dotnet/runtime#54819]
Parse String to Double Fails with Error **Format_InvalidString**

Input: 

41058.56

Code:
`try { double.Parse(str); } catch (Exception e) { Console.WriteLine("Input String: " + str + "\nError Message: " + e.Message); }`

Error:
**Format_InvalidString**

Output:
Error Message: Format_InvalidString
blazor.webassembly.js:1 Input String: 41058.56

Only Occurs if Chrome/Edge is in Arabic Language otherwise works fine

**Comment by smjltd** [comment]
best area would be blazor-webassembly, since it's related to webassembly.

**Comment by svick** [comment]
I think this is the expected behavior. `double.Parse(str)` uses the current culture, which means it expects culture-specific decimal separator. As far as I can tell, for Arabic, that's "٫": arabic decimal separator. If you want to parse strings with decimal point, you should use the "invariant" culture:

```c#
double.Parse(str, CultureInfo.InvariantCulture);
```

(Note that I haven't tested this with blazor, but I think the behavior should be the same there.)

**Comment by tarekgh** [comment]
@svick comment is correct. parsing depends on the current culture. If the current culture set to Arabic, the string get parsed will need to have the decimal separator matching the current culture. The recommendation to use Invariant Culture for formatting and parsing is correct too. That can guarantee the parsing always succeed. 

@lewing I marked the issue with `arch-wasm` to double check if there is anything specific here for WASM. otherwise we can close this issue.

**Comment by tarekgh** [comment]
@smjltd I am closing this issue. You can just parse the string you have using [Parse(String, IFormatProvider)](https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=net-5.0#System_Double_Parse_System_String_System_IFormatProvider_). i.e. you can call `double.Parse("41058.56", CultureInfo.InvariantCulture)`. Feel free to send any question or you need any help and we'll be happy to help.

**Comment by smjltd** [comment]
> @smjltd I am closing this issue. You can just parse the string you have using [Parse(String, IFormatProvider)](https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=net-5.0#System_Double_Parse_System_String_System_IFormatProvider_). i.e. you can call `double.Parse("41058.56", CultureInfo.InvariantCulture)`. Feel free to send any question or you need any help and we'll be happy to help.

Thank You.. The solution worked, although this was not required in blazor was dotnet3.0 onwards

**Comment by smjltd** [comment]
This Issue Still Occurs on for example: 
`                <input type="number" class="form-control" value="@Math.Round(repairCostTotal.GeneralMaterialCost,2))" readonly />
`

Need to add Invariant Culture for Every Field where it's auto converting to string

`<input type="number" class="form-control" value="@Math.Round(repairCostTotal.GeneralMaterialCost,2).ToString(CultureInfo.InvariantCulture)" readonly />`

**Comment by smjltd** [comment]
> 
> 
> @smjltd I am closing this issue. You can just parse the string you have using [Parse(String, IFormatProvider)](https://docs.microsoft.com/en-us/dotnet/api/system.double.parse?view=net-5.0#System_Double_Parse_System_String_System_IFormatProvider_). i.e. you can call `double.Parse("41058.56", CultureInfo.InvariantCulture)`. Feel free to send any question or you need any help and we'll be happy to help.

please reopen the case

**Comment by tarekgh** [comment]
@smjltd as stated in the comment https://github.com/dotnet/runtime/issues/54819#issuecomment-869934668 the parsing depends on the culture. if a number formatted with a specific culture, it needs to be parsed with same culture (or compatible culture). The parser cannot handle any possible formatted numbers. That is, we encourage when formatting a number, format it with Invariant culture and when parsing parse, it with Invariant culture too.  

Please look at the [doc](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-numeric?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-h7lW8QpTMDdvj2IxeP.YqQ&epi=a1LgFw09t88-h7lW8QpTMDdvj2IxeP.YqQ&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=%28ir__mrdukhopi0kfqxeykk0sohzifv2xueo2rnxvqyey00%29%287806%29%281243925%29%28a1LgFw09t88-h7lW8QpTMDdvj2IxeP.YqQ%29%28%29&irclickid=_mrdukhopi0kfqxeykk0sohzifv2xueo2rnxvqyey00#parsing-and-format-providers) for more info.
