### ISSUE TITLE
System.IntPtr(long) constructor throws overflow

### ISSUE THREAD

**Issue by manu-st** [dotnet/runtime#5482]
The current .NET Framework on Windows and CoreCLR have the following implementation for System.IntPtr(long):

```
public unsafe IntPtr(long value)
{
    #if WIN32
        m_value = (void *)checked((int)value);
    #else
        m_value = (void *)value;
    #endif
}
```

This is quite unfortunate on 32-bit platforms because if you get a pointer value as a long which has the higher bit set, it will always throw an overflow exception.

To reproduce:

```
IntPtr ptr = new IntPtr(0x80000000);
```

The code should have been:

```
public unsafe IntPtr(long value)
{
    #if WIN32
        m_value = (void *)checked((uint)value);
    #else
        m_value = (void *)value;
    #endif
}
```

since we only care that the higher 32-bits of the long parameter are all zeros.

**Comment by tannergooding** [comment]
Going to close this as we are not looking at making breaking changes to how `IntPtr` works.

For C# 9, there are two new language keywords `nint` and `nuint` which map to `IntPtr` and `UIntPtr`, respectively.
When using these new keywords, you get support for checked/unchecked contexts, operators, and other niceties normally expected from integral types. They can be used to avoid overflow, when that behavior is desired.
