### ISSUE TITLE
IServiceCollection.Add multiple implementations of an interface results in duplicate instances when injecting IEnumerable of interface 

### ISSUE THREAD

**Issue by fvilches17** [dotnet/runtime#54823]
### Description
_Note: although I used Blazor and VS2021 IDE in the below example, it by all means is not a Blazor bug or VS bug. It's a .NET 6 bug pertaining to  [Microsoft.Extensions.DependencyInjection.IServicesCollection](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.iservicecollection?view=dotnet-plat-ext-5.0)_

I created a Blazor Server .NET 6 project using the out of the box Visual Studio 2021 template.

I created interface `IAnimal.cs` with method `MakeSound()`

I registered multiple animals in `Startup.cs`
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();
    services.AddServerSideBlazor();
    services.AddScoped<IAnimal, Cat>();
    services.AddScoped<IAnimal, Cow>();
    services.AddScoped<IAnimal, Doggy>();
    services.AddScoped<IAnimal, Duck>();
    services.AddScoped<IAnimal, Fox>();
}
```

I have a simple razor page
```csharp
@page "/"
@page "/animal-sounds"
@using Injector.Models

@foreach (var animal in Animals)
{
    <p>@animal.GetType().Name: @animal.MakeSound()</p>
}

@code {
    [Inject]
    protected IEnumerable<IAnimal> Animals { get; set; }
}
```

### Expected Result
![image](https://user-images.githubusercontent.com/13502806/123631511-eed4f980-d86a-11eb-8d4d-4a30e6561deb.png)

### Actual
![image](https://user-images.githubusercontent.com/13502806/123631532-f5637100-d86a-11eb-9034-f673fd5cea8d.png)

### Steps to reproduce
1. Make sure you have the [latest version of .NET 6](https://dotnet.microsoft.com/download/dotnet/6.0) installed on your machine of course
2. Clone [this repo](https://github.com/fvilches17/DotNet6.DependencyInjection.Bug)
3. Open a command line and run `dotnet run` at the project (.csproj) level. 
4. Navigate to https://localhost:5001

* You can switch to [this branch](https://github.com/fvilches17/DotNet6.DependencyInjection.Bug/tree/dotnet-5-version) which is identical but runs on .NET5. Re-run the app, and notice the app behaves as expected.

### Configuration
* Which version of .NET is the code running on? `6.0.100-preview.5.21302.13`
* What OS and version, and what distro if applicable? `Windows 10 Pro 21H1 OS build 19043.1081`
* What is the architecture (x64, x86, ARM, ARM64)? `x64`
* Do you know whether it is specific to that configuration? `Not sure`
* If you're using Blazor, which web browser(s) do you see this issue in? `Microsoft Edge Chromium Version 91.0.864.59 (Official build) (64-bit)`

### Regression?
Yes! .NET 5!  Here's the exact same code but the project(csproj) changed to use `<TargetFramework>net5.0</TargetFramework>`

If you downgrade the project to .NET5 and re-run it, you get the expected result ✅

### Other information
This unexpected behavior occurs regardless of whether you register a singleton, transient, and/or scoped. 

No stack traces, the app doesn't throw exceptions.

Debug and place a breakpoint on [this line](https://github.com/fvilches17/DotNet6.DependencyInjection.Bug/blob/a7e26a5e702e8f58b6822fabbd50f434f766b6a3/Injector/Startup.cs#L28), and notice in `services` that all the `IAnimal` implemenations where registered. 

Now place a breakpoint on [this line](https://github.com/fvilches17/DotNet6.DependencyInjection.Bug/blob/a7e26a5e702e8f58b6822fabbd50f434f766b6a3/Injector/Pages/AnimalSounds.razor#L6). This is the class where the IEnumerable<IAnimal> is being injected. Notice the Animals enumerable contains the correct number of animals, but it has duplicate animals.

* Do you know of any workarounds?
Other than having to downgrade my app to the supported .NET5, not so far.

**Comment by vcsjones** [comment]
I believe this is a duplicate of #54407. The known issue list at https://github.com/dotnet/core/blob/main/release-notes/6.0/known-issues.md#net-runtime has a workaround, and I believe it will be fixed when preview6 is released.

**Comment by fvilches17** [comment]
@vcsjones thanks! Indeed. Closing off this issue.
