### ISSUE TITLE
TreeSubSet.Min and TreeSubSet.Max work incorrectly with custom comparer

### ISSUE THREAD

**Issue by petrogavriluk** [dotnet/runtime#54834]
### Description

The code below gives the wrong result:

    var comparer = Comparer<int>.Create((x, y) => x - y);  
    var set = new SortedSet<int>(new[]{1, 4}, comparer);  
    var view = set.GetViewBetween(1, 2);  
    Console.WriteLine(view.Max); // Prints 4 instead of 1  

According to the documentation of IComparer.Compare() it can return any integer, not only [-1, 0, 1]. So this comparer should be ok.

### Configuration

I run it on .net 5, but I think it is present in other versions as well.

### Regression?

A similar issue was mentioned in [20474](https://github.com/dotnet/runtime/issues/20474) (without comparer though). So I think it is regression.

### Other information

I have found the reason why it happens in code:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs#L135 https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs#L164
The comparison result is checked against 1 and -1, instead of (comp > 0) and (comp < 0).

**Comment by eiriktsarpalis** [comment]
This seems like a bug introduced by https://github.com/dotnet/corefx/pull/16771. It seems like a trivial fix, would you be willing to contribute a PR?

**Comment by petrogavriluk** [comment]
I haven't contributed here yet, but yes, I can try.
Should I also add tests?

**Comment by eiriktsarpalis** [comment]
Thanks, assigning the issue to you. A couple of tests reproducing your scenario for both min and max should suffice.

Please let me know if you have any questions on the dev workflow.
