### ISSUE TITLE
Mono's RuntimeAssembly.GetName calls CodeBase

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#54835]
CodeBase is marked as `RequiresAssemblyFiles`, which means that it can throw an exception if the application is published as a single-file application.

https://github.com/dotnet/runtime/blob/bde0322a9e11fba40a7a65c6d38200d6514efc72/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L253-L256

We should decide what to do here for Mono. In CoreCLR, we don't call CodeBase directly, but instead we call the underlying `GetCodeBase()` method, which returns `null` when running in a single-file application:

https://github.com/dotnet/runtime/blob/bde0322a9e11fba40a7a65c6d38200d6514efc72/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L102-L117

Maybe we should do the same?

cc @akoeplinger @steveisok

**Comment by eerhardt** [comment]
I needed to suppress the new IL3002 warning from the `RequiresAssemblyFiles` analyzer in https://github.com/dotnet/runtime/pull/54741.

**Comment by lambdageek** [comment]
Fixed by https://github.com/dotnet/runtime/pull/54895
