### ISSUE TITLE
Loop Cloning is disabled on Arrays of Structs

### ISSUE THREAD

**Issue by badamczewski** [dotnet/runtime#54846]
Tested on .NET 5

Loop Cloning is disabled on structs of arrays making it somewhat not ideal for performance scenarios:

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGjWIBmBrgxQOYDAyk0A3jQYWmW3jwYANZZYs0AvmtpayDACpLDZ6idNJhQGAFkACikAbQBdBmwASgYApycAM2gIm0NeBgBeBjpHPIAeBnI6KpKAahrk1LSm7GjeWJY7AoZeVUCmhjc+i0GXIA===

The code in question that disables loop cloning is here and it's still on master so it will also affect .NET 6:

https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/loopcloning.cpp#L2060

Code:

```csharp
public struct S
{
    public int X;     
}

public class Test {
    public void M(S[] a) {
        for(int i = 0; i < 1000; i++) {
            a[i].X = i;
        }
    }
}
```

X86:

```asm
    L0000: sub rsp, 0x28
    L0004: xor eax, eax
    L0006: mov ecx, [rdx+8]
    L0009: cmp eax, ecx
    L000b: jae short L0023
    L000d: movsxd r8, eax
    L0010: mov [rdx+r8*4+0x10], eax
    L0015: inc eax
    L0017: cmp eax, 0x3e8
    L001c: jl short L0009
    L001e: add rsp, 0x28
    L0022: ret
    L0023: call 0x00007ffc6346a5e0
    L0028: int3
```

**Comment by BruceForstall** [comment]
This is a dup of https://github.com/dotnet/runtime/issues/48897

**Comment by BruceForstall** [comment]
I'm going to close this, and track the work with #48897
