### ISSUE TITLE
[mono] iOS - Size reduction: don't emit impossible generic function instantiations

### ISSUE THREAD

**Issue by imhameed** [dotnet/runtime#54850]
Seen while investigating [size differences between legacy Mono and netcore Mono](https://github.com/xamarin/xamarin-macios/issues/10249#issuecomment-868195729) when used for iOS.

Some generic functions take generic parameters that themselves have type parameters that have `struct` constraints, but we still generate `T_REF` (boxed, non-value-type, shared) instantiations for these functions.

**(This should affect any target that uses FullAOT; this includes iOS/tvOS)**

**Comment by imhameed** [comment]
Tried a toy workaround for this that doesn't generate ref instantiations for functions with at least one struct constraint and doesn't generate gsharedvt instantiations for functions with at least one class constraint. This results in a savings of around 200 KiB in `.text` for a FullAOT + LLVM compiled copy of System.Private.CoreLib.dll on amd64 Linux (from 9.11 MiB to 8.92 MiB), and results in a `__text` savings of about 92.16 KiB for arm64 iOS using a linked copy of System.Private.CoreLib.dll (3 MiB to 2.91 MiB).

**Comment by imhameed** [comment]
This should be straightforward, although it would be great to have better test FullAOT test coverage before doing this. https://github.com/dotnet/runtime/pull/55362 goes part of the way there but it'd be preferable to have CI coverage that would have caught https://github.com/dotnet/runtime/issues/56100.

**Comment by SamMonoRT** [comment]
Assigning to @ivanpovazan
