### ISSUE TITLE
Custom EventSources in shared library seem to have unused code

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#54859]
The `EventSource `type has an [attribute ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L235-L237)that the trimmer will interpret to keep all members of it as well as all its descendants. A pending trimmer [checkin ](https://github.com/mono/linker/pull/2114)honors this for non-public custom `EventSources `in library trim mode that affects the shared framework library build.

There is a sizeable difference (around 70K or so of IL) of code that is kept after this trimmer change. A quick [analysis ](https://github.com/mono/linker/issues/1949#issuecomment-869184670)of the difference shows that there are members in custom event sources that were not noticed earlier. For example, [NetEventSource ](https://github.com/dotnet/runtime/blob/385b6f3e5fd6fbf08a8a82bde5a5f57f18018c2a/src/libraries/Common/src/System/Net/Logging/NetEventSource.Common.cs#L39)is used in multiple libraries where the additional members might not be needed (we shipped without this extra code prior to the trimmer change).

Consider removing members from these custom `EventSource `in the source code itself if they are not needed in the libraries or add tests if they are needed.

**Comment by stephentoub** [comment]
@LakshanF, FYI, the NetEventSource ones you're referring to are implemented as some shared methods in a partial class, and then each networking library includes that partial file and adds its own partial file that primarily just adds a unique guid / name.  So it's not as simple as just removing unused code from that shared file, as different libs may use different subsets of the methods, and were relying on the linker to get rid of unused ones.

**Comment by LakshanF** [comment]
@stephentoub, unfortunately the [pending ](https://github.com/mono/linker/pull/2114)PR will make the trimmer not get rid of unused code in a special mode of trimming named 'library mode' that is used in building the libraries in the runtime. This is to handle cases like [this ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs#L25) library test that logs using the `NetEventSource`. 

Below are some relevant details

- Prior to .NET6, The trimmer had a special handling for `EventSource` to allow cases like the test case above which only kept nested types
- In .NET6, trimmer added a feature to generalize the `EventSource `pattern by allowing the dynamic attribute to be applied to types such that all its derived types will also get the dynamic attribute applied
                - However, this will only happen if a type is used and there is a `object.GetType()` reflection pattern on that type
- We still couldn't get rid of the pre .NET6 special handling of EventSource due to the library mode trimming getting rid of unused code in the non-publicly visible `NetEventSource `since there is no` object.GetType()` in the library
- The pending PR adds an optimization mode that when disabled will allow the dynamic attribute to be applied to derived types only when the type is referenced (does not need `object.GetType()` reflection pattern)
                - I assume this optimization mode will be disabled in the library build for all libraries that will cause the size problem above
- The `EventSource `dynamic attribute scope is really large (All, which will preserve everything) since that is the only way to get `NestedTypes `to be preserved. We have a pending [issue ](https://github.com/mono/linker/issues/1174) to scope this down but still will likely impact this scenario to some degree since I assume we will keep methods as well in `EventSource`.

**Comment by marek-safar** [comment]
> Are there reasons why we have to get rid of the special handling for .NET 6?

There are two reasons
 - It always marks the nested types even if the event source support is explicitly disabled
 - We use different logic to mark potentially same code twice

> Note that this is not just about the extra IL. It has also impact at runtime when tracing is enable that is increasingly more common. The event source will have to build manifests for the unused events now.

I suggested libraries trim mode implementation in the linker which would address that instead of marking everything.

**Comment by tommcdon** [comment]
@LakshanF @vitek-karas  do you plan on fixing this issue in .NET 6?

**Comment by LakshanF** [comment]
We are talking to the network team to see if they can fix this (as in use only the source code they need instead of relying on the trimmer to remove unused code). Its possible that this might not be possible to do in 6.0 in which case, we can punt this issue

**Comment by LakshanF** [comment]
Below are the specific file size differences I can see when trimming shared FX assemblies in library mode (for example, for the first file, passing this line to the trimmer (with additional details): `-a "runtime\artifacts\obj\System.Net.Primitives\net6.0-windows-Debug\PreTrim\System.Net.NetworkInformation.dll" library`

```
System.Net.NetworkInformation.dll, Difference: 9,216, Percent: 11.84% Pre:87,040, Post:77,824
System.Net.Primitives.dll, Difference: 8,704, Percent: 9.44% Pre:100,864, Post:92,160
System.Net.Quic.dll, Difference: 8,192, Percent: 6.90% Pre:126,976, Post:118,784
System.Net.NameResolution.dll, Difference: 7,680, Percent: 17.86% Pre:50,688, Post:43,008
System.Net.Sockets.dll, Difference: 6,656, Percent: 3.15% Pre:218,112, Post:211,456
System.Net.Requests.dll, Difference: 6,144, Percent: 3.92% Pre:162,816, Post:156,672
System.Net.Http.dll, Difference: 5,632, Percent: 0.72% Pre:791,040, Post:785,408
System.Net.Security.dll, Difference: 5,120, Percent: 1.86% Pre:280,064, Post:274,944
System.Net.Mail.dll, Difference: 4,608, Percent: 1.94% Pre:241,664, Post:237,056
System.Net.HttpListener.dll, Difference: 3,584, Percent: 1.15% Pre:316,416, Post:312,832
```

**Comment by LakshanF** [comment]
Looking at the attached ILDASM output for `System.Net.NetworkInformation.dll` (before and after), you can see the differences in NetEventSource source (for example, `.method public hidebysig static void  Verbose(object thisOrContextObject, object message, [opt] string memberName) cil managed`).

[System.Net.NetworkInformation_baseline.txt](https://github.com/dotnet/runtime/files/6850370/System.Net.NetworkInformation_baseline.txt)
[System.Net.NetworkInformation_additiona_size.txt](https://github.com/dotnet/runtime/files/6850374/System.Net.NetworkInformation_additiona_size.txt)

**Comment by jkotas** [comment]
The linker runs automatically at the end of libraries build. You can do release build before and after the change and check the sizes of the affected assemblies.
