### ISSUE TITLE
System.Runtime.CompilerServices - Undoc 6.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#54879]
The APIs in the table below were introduced in .NET 6.0 and are showing up as undocumented in the dotnet-api-docs repo.

Some of them are already documented in triple slash comments in source. Area owners, please: 

1. Verify if there are any APIs from the table have not been documented in source. If you find any, document them in triple slash and submit a PR to runtime to commit the documentation.
2. Clone the dotnet-api-docs repo and port the triple slash comments by running this [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) command:

```
DocsPortingTool \
    -Direction ToDocs \
    -Docs %REPOS%\dotnet-api-docs\xml \
    -Intellisense %REPOS%\runtime\artifacts\bin\ \
    -IncludedAssemblies System.Runtime.CompilerServices \
    -IncludedNamespaces System.Runtime.CompilerServices \
    -Save true
```

3. Submit a PR to dotnet-api-docs with the ported documentation.

<details>
  <summary>Undoc 6.0 System.Runtime.CompilerServices APIs table</summary>

| Undoc 6.0 API                                                                                                                                                                                    |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [M:System.Runtime.CompilerServices.CallConvSuppressGCTransition.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/CallConvSuppressGCTransition.xml) |
| [T:System.Runtime.CompilerServices.CallConvSuppressGCTransition](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/CallConvSuppressGCTransition.xml)       |
| [M:System.Runtime.CompilerServices.Unsafe.Add\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/Unsafe.xml)                       |
| [M:System.Runtime.CompilerServices.Unsafe.AddByteOffset\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/Unsafe.xml)             |
| [M:System.Runtime.CompilerServices.Unsafe.Subtract\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/Unsafe.xml)                  |
| [M:System.Runtime.CompilerServices.Unsafe.SubtractByteOffset\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.CompilerServices/Unsafe.xml)        |

</details>

**Comment by danmoseley** [comment]
We need to document 6.0 API in the 6.0 timeframe (even though work is in docs repo). I'll do it.

**Comment by danmoseley** [comment]
M:System.Runtime.CompilerServices.Unsafe are implemented in IL so it has a hard coded doc file at src\libraries\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.xml

**Comment by danmoseley** [comment]
@safern the new member is present in src\libraries\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.xml. However, after i build it's not present in artifacts\bin\docs\System.Runtime.CompilerServices.Unsafe.xml. That one, like the other files in there, has a timestamp of 10/09/2020  09:10 PM .. it's getting restored from somewhere. Compare eg System.Runtime.xml, which is being built into output folders below artifacts\bin.

1. Where do we need to change for this. ilproj to copy it's checked-in System.Runtime.CompilerServices.Unsafe.xml into artifacts? 
2. What is that point of all these old files? Does this mean we haven't updated intellisense since then?

**Comment by krwq** [comment]
@danmoseley since the PR is merged can this be closed or is there anything left?

**Comment by danmoseley** [comment]
The members that were added to the ilproj need porting. Don't recall what the tool didn't do it. If you throw up a quick docs PR that adds their text manually then we can close this.

**Comment by safern** [comment]
> build it's not present in artifacts\bin\docs\System.Runtime.CompilerServices.Unsafe.xml

@danmoseley the `artifacts\bin\docs` is populated from the intellisense package. The xml files we generate from the build (presumably the one we have statically defined for the ilproj) are under `artifacts\bin\<project-name>\<configuration>`.

**Comment by danmoseley** [comment]
@krwq could you look at that and see what's left if anything?

if there's only work in dotnet-api-docs then this is not subject to zbb.
