### ISSUE TITLE
Microsoft.Win32.Handles - Undoc 6.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#54871]
The following APIs were introduced in 6.0 and did not get documented in triple slash. They will need to be manually documented directly in dotnet-api-docs, and must target the net6-rc1 branch. This needs to be done before Tuesday September 14th so we have enough time to generate the IntelliSense package that will be shipped to GA.

| Undoc APIs                                                                                                                                                                               |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [M:Microsoft.Win32.SafeHandles.SafeFileHandle.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/Microsoft.Win32.SafeHandles/SafeFileHandle.xml)                         |
| [P:Microsoft.Win32.SafeHandles.SafeFileHandle.IsAsync](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/Microsoft.Win32.SafeHandles/SafeFileHandle.xml)                       |
| [M:Microsoft.Win32.SafeHandles.SafeMemoryMappedViewHandle.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/Microsoft.Win32.SafeHandles/SafeMemoryMappedViewHandle.xml) |

**Comment by danmoseley** [comment]
Some of these are Xamarin only, and come from mono/mono. Eg
  `    <MemberSignature Language="C#" Value="public SafeMemoryMappedFileHandle (IntPtr preexistingHandle, bool ownsHandle);" FrameworkAlternate="xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0" />`
only exists at https://github.com/mono/mono/blob/main/mcs/class/System.Core/Microsoft.Win32.SafeHandles/SafeMemoryMappedFileHandle.cs#L40

**Comment by carlossanlop** [comment]
@danmoseley thanks for taking care of the triple slash docs.

Where did you see the `<MemberSignature>` restricted to xamarin frameworks? This is what I see:

- SafeFileHandle.ctor: https://github.com/dotnet/dotnet-api-docs/blob/74cf0e5ca80d5499794cab71fa733f34b59a0e94/xml/Microsoft.Win32.SafeHandles/SafeFileHandle.xml#L92
- SafeFileHandle.IsAsync: https://github.com/dotnet/dotnet-api-docs/blob/74cf0e5ca80d5499794cab71fa733f34b59a0e94/xml/Microsoft.Win32.SafeHandles/SafeFileHandle.xml#L181
- SafeMemoryFileHandle.ctor (the one you shared) it says 6.0: https://github.com/dotnet/dotnet-api-docs/blob/74cf0e5ca80d5499794cab71fa733f34b59a0e94/xml/Microsoft.Win32.SafeHandles/SafeMemoryMappedViewHandle.xml#L57

The Excel report (which is generated by the Docs build system that creates the dotnet-api-docs xml files) is confirming it too:

![image](https://user-images.githubusercontent.com/1175054/132766908-d846e41d-40cb-4987-91e9-fa62f869cd27.png)

**Comment by danmoseley** [comment]
I don't recall so I believe you 😀
