### ISSUE TITLE
System.Numerics - Undoc 6.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#54878]
The APIs in the table below were introduced in .NET 6.0 and are showing up as undocumented in the dotnet-api-docs repo.

Some of them are already documented in triple slash comments in source. Area owners, please: 

1. Verify if there are any APIs from the table have not been documented in source. If you find any, document them in triple slash and submit a PR to runtime to commit the documentation.
2. Clone the dotnet-api-docs repo and port the triple slash comments by running this [DocsPortingTool](https://github.com/carlossanlop/DocsPortingTool) command:

```
DocsPortingTool \
    -Direction ToDocs \
    -Docs %REPOS%\dotnet-api-docs\xml \
    -Intellisense %REPOS%\runtime\artifacts\bin\ \
    -IncludedAssemblies System.Numerics \
    -IncludedNamespaces System.Numerics \
    -Save true
```

3. Submit a PR to dotnet-api-docs with the ported documentation.

<details>
  <summary>Undoc 6.0 System.Numerics APIs table</summary>

| Undoc 6.0 API                                                                                                                                      |
|----------------------------------------------------------------------------------------------------------------------------------------------------|
| [M:System.Numerics.BitOperations.IsPow2(System.Int32)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/BitOperations.xml)  |
| [M:System.Numerics.BitOperations.IsPow2(System.Int64)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/BitOperations.xml)  |
| [M:System.Numerics.BitOperations.IsPow2(System.UInt32)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/BitOperations.xml) |
| [M:System.Numerics.BitOperations.IsPow2(System.UInt64)](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Numerics/BitOperations.xml) |

</details>

**Comment by danmoseley** [comment]
Got it to work with `-IncludedAssemblies System.Private.CoreLib,System.Runtime -IncludedNamespaces System.Numerics ` ... the assemblies need to be both the implementation and facade, if it's type forwarded.
