### ISSUE TITLE
Add memory-based Read/WriteAsync overloads to SerialStream

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54916]
// 'SerialStream' overrides array-based 'ReadAsync' but does not override memory-based 'ReadAsync'. Consider overriding memory-based 'ReadAsync' to improve performance.
// 'SerialStream' overrides array-based 'WriteAsync' but does not override memory-based 'WriteAsync'. Consider overriding memory-based 'WriteAsync' to improve performance.

Disabling the warning in https://github.com/dotnet/runtime/pull/54544. The overloads should be added to improve performance on .NETCoreApp.

cc @krwq @wfurt @stephentoub

**Comment by wcontayon** [comment]
Hi @ViktorHofer it's an interesting issue. Can I try a PR ?

**Comment by ViktorHofer** [comment]
Absolutely. I just assigned you to the issue. Go for it :)

**Comment by krwq** [comment]
@wcontayon thanks for offering help! Note you'll likely need to do a tiny refactor of code

**Comment by adamsitnik** [comment]
fixed by #56866
