### ISSUE TITLE
System.Text.Json and ISerializable

### ISSUE THREAD

**Issue by denis-dbm** [dotnet/runtime#54940]
Are there plans to support ISerializable in System.Text.Json?

Newtonsoft lib does that: https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#ISerializable

Thanks

**Comment by eiriktsarpalis** [comment]
The short answer is no. We are planning on [deprecating BinaryFormatter and related types in future releases](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md), which also includes `ISerializable`. 

The linked document details the justification behind this decision, but TL;DR the design of BinaryFormatter (including `ISerializable`) contains serious security flaws, so we would never consider incorporating support in new serializers.

Related to #30083. cc @GrabYourPitchforks
