### ISSUE TITLE
String.IndexOf("\0") Zero 

### ISSUE THREAD

**Issue by my522cn** [dotnet/runtime#54951]
### Description
Before dotnet5, below code d and e are both 9. But in dotnet5, e is 0. I think it is a bug.
> string a = "FT4EVT0DA\0\0\0?\u007f\0\0";
var d = a.IndexOf('\0');
var e = a.IndexOf("\0");

### Configuration

* Which version of .NET is the code running on?
* 5.0
* What OS and version, and what distro if applicable?
* Win10 20H2
* What is the architecture (x64, x86, ARM, ARM64)?
* x64

**Comment by Symbai** [comment]
Using [Fiddle](https://dotnetfiddle.net/) when selecting .NET5 the char overload [returns 9 and string based returns 0](https://dotnetfiddle.net/Widget/C0U8Wq). Selecting .NET Framework 4.7.2 or Rosyln 3.8 [both returns 9](https://dotnetfiddle.net/Widget/bfUttE):

**Comment by teo-tsirpanis** [comment]
Hello, .NET 5 [started using the ICU globalization libraries](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu) on Windows 10 1903 or newer for consistency with other operating systems. This change has unavoidably brought some breaking behavioral changes like this one.

In your case however, if you are simply looking for null characters in a string, an ordinal search would be ideal for you. `IndexOf` with a character always makes ordinal searches, and you can perform an ordinal search on a string like this:

``` csharp
var e = a.IndexOf("\0", StringComparison.Ordinal);
```

**Comment by tarekgh** [comment]
@my522cn please look at the issue https://github.com/dotnet/runtime/issues/46569 for more details. I am closing this issue but feel free to send any question and we'll be happy to help with.
