### ISSUE TITLE
WinHttpHandler vs. SocketsHttpHandler Digest Authentication

### ISSUE THREAD

**Issue by ben-002** [dotnet/runtime#54958]
I have a .NET core 3.1 console application in which I need to make a request to the Mongodb Atlas API. For that, a digest authentication is required.
I'm also using `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)` to switch from using the `SocketsHttpHandler` to using `WinHttpHandler`. If not, I receive a 401 response status code. 

From what I understand, this "switching" is no more available starting .NET 5. In te perspective of updating my application to .NET 5, or just avoiding to add that switching in my code, is there any workaround to use the default handler, `SocketsHttpHandler`?

**Comment by teo-tsirpanis** [comment]
You can use the [`Systen.Net.Http.WinHttpHandler`](https://www.nuget.org/packages/System.Net.Http.WinHttpHandler/) NuGet package.

**Comment by wfurt** [comment]
We should figure out why the default handler does not work @ben-002. and fix it. Can you share some more details?

**Comment by ben-002** [comment]
@wfurt I'm not sure if this is a malfunction of the default handler or it's by design.  Or if I'm doing something wrong.
The idea is that the following code works only when setting `AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false)`. Otherwise the result will have a 401 status code. 
I presume that the old handler completely manages the digest way of authentication whilst the SocketsHttpHandler not? and I need to code the next steps required in a digest authentication? 

``` C#
            const string domain = "https://cloud.mongodb.com/";
            var credCache = new CredentialCache
            {
                {
                    new Uri(domain),
                    "Digest",
                    new NetworkCredential("mongoAtlasProjectPublicKeyPlaceholder", "mongoAtlasProjectPrivateKeyPlaceholder")
                }
            };
            var client = new HttpClient(new HttpClientHandler { Credentials = credCache });
            client .DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var result =  await client.GetAsync($"https://cloud.mongodb.com/api/atlas/v1.0/groups/{"project id placeholder"}/accessList/{"ip to check placeholder"}");

```

**Comment by wfurt** [comment]
Since the URL is https you can use Fiddler to see the inner traffic. Seeing the passing and not passing request/response would be good.  If running under debugger look for any thrown and handed exception.

**Comment by karelz** [comment]
@ben-002 were you able to get the info asked for above?

**Comment by ben-002** [comment]
Sorry for my late response. 
Just for testing, I created a new personal project in Mongo. 
In a dummy Console App I tried the code already mentioned above. Indeed, targeting .NET5 was fine. The requests I've seen in fiddler are below:
![image](https://user-images.githubusercontent.com/69915112/125510384-caedc1b3-a98a-48ff-ab3d-8bd9feb8cb26.png)
However, when targeting .Net core 3.1 without using AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false), the following calls are made:
![image](https://user-images.githubusercontent.com/69915112/125510672-917b4238-70f4-4d47-afac-e836f69d70d2.png)
It looks like the digest autentication is incomplete.
If setting AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false), fiddler shows:
![image](https://user-images.githubusercontent.com/69915112/125510800-d9a7103c-797e-4d5f-acaf-16529a13866a.png)

The code was ran in debuggin mode, no exception was thrown.

I discovered the initial problem tring to execute the mentioned code for a mongodb project that's not managed by me. I said in .NET5 there is no problem. The truth is there is no problem when using my personal project. When authenticating for the one that is not managed by me, the only working solution is targeting .Net Core 3.1 with AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false). Otherwise, 401 is returned. At this moment I can't understand why. Maybe there are some mongodb project configurations, but then why it works in .Net Core 3.1 with UseSocketsHttpHandler false? Unfortunateley I am unable to provide more details about it.

**Comment by wfurt** [comment]
That is not that surprising @ben-002. 3.1 has two completely separate implementations. SocketHandler was improved over time and there were several issue related to digest fixed in 5. 
So if I read it correctly there is no work left for 5.x or 6.0 e.g. the Sockethandler works as it should, right?

**Comment by ben-002** [comment]
@wfurt It works in 5 with my personal mongo db project. Not sure why is not working with the one that's not managed by me. It might be some mongo configurations that I'm not aware of.  However, for the same project, Net Core 3.1 with AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false) works fine.  If there is indeed a matter of mongo configurations, Sockethandler  is fine. 
Because I wasn't able to reproduce the  problem by linking a .NET 5 project with a mongo personal project, I think the best option is to close the issue.
