### ISSUE TITLE
[HTTP/3] Implement connection scavenging

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#54968]
We are not scavenging HTTP3 connections currently (i.e. based on idle timeout or lifetime). We need to implement this.

**Comment by karelz** [comment]
Triage: Would manifest as memory leak

**Comment by ManickaP** [comment]
@geoffkizer What exactly is missing? I see we check the expiration and dispose and clean up the connection:
https://github.com/dotnet/runtime/blob/f59a132bfe9ff797f9d192d67f07673a13b6b29e/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L812-L818

**Comment by geoffkizer** [comment]
There's no HTTP3 logic here: https://github.com/dotnet/runtime/blob/f59a132bfe9ff797f9d192d67f07673a13b6b29e/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1971

**Comment by geoffkizer** [comment]
BTW, I think we should update the HTTP3 connection pooling logic in general to match the recent changes I made to HTTP11/2. As part of that, this should just fall out.
