### ISSUE TITLE
File system access is broken on .net 5 on windows 7 SP1 so it would seem, need a favor

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [dotnet/runtime#54967]
got a small request for a W7 User here , i got a problem with a .net 5 App called Ryujinx its an Emulator for the Switch, as above has already stated its File System Access is broken .net 5s is for W7 so it would seem , was hoping you guys would do me this favor and be able to fix this issue 

https://media.discordapp.net/attachments/859825783714873365/859829308212903974/dunno.png

since nowhere has it said that ESUS is required for regular functionality by .net 5 , its only prerequisite for security updates, would appreciate

**Comment by adamsitnik** [comment]
> its File System Access is broken .net 5s is for W7 

@washingleavesandthensome23-434 On the screen shot that you have provided I can see a `NullReferenceException` being thrown from a code that seems to have nothing to do with file IO. Could you please provide more information? What exactly does not work on Windows 7 using .NET 5?

**Comment by washingleavesandthensome23-434** [comment]
well issue is ryujinx , is built with .net 5 in mind , and well i gotta restart like 15 times till it actually launches a game , other times i get said above issue like in the screenshot constantly when trying to launch a game , so a ryujinx supporter mentioned something about it possibly being something relating to  File System Access being broken for .net 5 for W7, btw i didnt tag this ticket of course IO related was the msftbot

**Comment by adamsitnik** [comment]
> a ryujinx supporter mentioned something about it possibly being something relating to File System Access being broken for .net 5 for W7

I am sorry, but we need more than that to be able to help. Do you have a link to the issue that you are mentioning?

**Comment by washingleavesandthensome23-434** [comment]
its ok i kinda taken care off it , issue can be closed thanks
