### ISSUE TITLE
Microsoft.NET.Workload.Mono.Toolchain does not get me the arm64 AOT compiler for Mac Catalyst

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#54996]
### Description

If I try to use the AOT compiler for Mac Catalyst/ARM64 (RID: `maccatalyst-arm64`), it doesn't work, because the only aot compiler in the MonoAotCrossCompiler item group is the one for `maccatalyst-x64`:

<img width="641" alt="Screenshot 2021-07-01 at 09 24 01" src="https://user-images.githubusercontent.com/249268/124083418-1fc15400-da4e-11eb-898f-8b14fdebf46b.png">

This is when executing on an M1 machine (but with the x64 version of .NET)

Binlog: [msbuild.binlog.zip](https://github.com/dotnet/runtime/files/6746193/msbuild.binlog.zip)

CC @steveisok @akoeplinger

**Comment by steveisok** [comment]
@rolfbjarne For me, the binlog zip doesn't appear to have the right file in it.

**Comment by rolfbjarne** [comment]
> @rolfbjarne For me, the binlog zip doesn't appear to have the right file in it.

Don't double click on it on macOS, because macOS will unzip it, and then see that it's a gzcompressed file inside, and gunzip that, which creates an invalid file.

If you've already done that, you should be able to make it valid again by gzipping it again.

**Comment by steveisok** [comment]
The maccatalyst cross pack looks to have the right props file:

`<MonoAotCrossCompiler RuntimeIdentifier="maccatalyst-arm64" ... />`

However, when I look at your binlog, the only MonoAotCrossCompiler item added has a runtimeidentifier w/ `maccatalyst-x64`.  Can you look in your workload pack and tell me what the Sdk.props file says?

**Comment by steveisok** [comment]
This appears to be a workload install problem.  We use alias-to for maccatalyst and the simulators in order to give you the right target architecture pack.  If you are using an x64 host on m1, then the right behavior would be to be able to target both x64 and arm64.  The correct fix would be to make all ios/tvos/maccatalyst packs install.
