### ISSUE TITLE
Add ref accessors for List<T>

### ISSUE THREAD

**Issue by naminodarie** [dotnet/runtime#54999]
## Background and Motivation

Add ref accessors for `List<T>` same as `Dictionary<TKey, TValue>`. #27062.

**Motivation**

Updating `struct` causes struct copies. It may be expensive.

```csharp
struct LargeStruct
{
    // Other members...
    
    public int MyInt { get; set; }

    // Other members...
}

LargeStruct value= list[index]; // struct copy
value.MyInt++;
list[index] = value; // another struct copy
```

## Proposed API

```csharp
namespace System.Runtime.InteropServices
{
    public static class CollectionsMarshal
    {
        /// <summary>
        ///   Gets a reference to the value at the given <paramref name="index"/>.
        /// </summary>
        public static ref T GetValueRef<T>(List<T> list, int index);
    }
}
```

## Usage Examples

``` C#
ref LargeStruct value = ref CollectionsMarshal.GetValueRef(list, index); // avoid struct copy
value.MyInt++;
```

## Alternative Designs

It can also be resolved using `CollectionsMarshal.AsSpan`, but it doesn't correspond to API of `Dictionary<TKey, TValue>`. 
I think this is non-intuitive.

```csharp
// List<T> use AsSpan
ref var listRef = ref CollectionsMarshal.AsSpan(list)[index];

// Dictionary<TKey, TValue> use ref accessor
ref var dictRef = ref CollectionsMarshal.GetValueRef(dictionary, key);
```

**Comment by huoyaoyuan** [comment]
> It can also be resolved using `CollectionsMarshal.AsSpan`, but it doesn't correspond to API of `Dictionary<TKey, TValue>`.
> I think this is non-intuitive.

I think `AsSpan` is already a perfect solution. Considering boundary check, checking span boundary is somehow more institutive than `Unsafe.IsNullRef`.

The list and dictionary methods lives in the same class `CollectionMarshal`, so there should be no difficulty of discovery.

**Comment by eiriktsarpalis** [comment]
> I think AsSpan is already a perfect solution. Considering boundary check, checking span boundary is somehow more institutive than Unsafe.IsNullRef.

> The list and dictionary methods lives in the same class CollectionMarshal, so there should be no difficulty of discovery.

Both great points. Unlike Dictionary I don't think there is much benefit in exposing ref accessors for List. I will close this issue, but we can always revisit should we discover a compelling reason to include it.

**Comment by naminodarie** [comment]
Thanks for reviewing!
