### ISSUE TITLE
stackalloc behavior with constant size that isn't a power of 2

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#55001]
Cf. https://github.com/dotnet/aspnetcore/pull/33776#discussion_r661668436

```c#
public char A()
{
    Span<char> span = stackalloc char[20];          // not a power of two
    return span[0];
}

public char B()
{
    Span<char> span = stackalloc char[32];          // power of two
    return span[0];
}

[SkipLocalsInit]
public char A1()
{
    Span<char> span = stackalloc char[20];          // not a power of two + SkipLocalsInit
    return span[0];
}

[SkipLocalsInit]
public char B1()
{
    Span<char> span = stackalloc char[32];          // power of two + SkipLocalsInit
    return span[0];
}
```

I'd expect similar codegen for cases A, and B. As well similar codegen for A1, and B1.
But codegen is different, and for case A1 it seems SkipLocalsInit isn't honored. The [IL seems correct](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSA6AJQFcA7DbAWxiYDCEHgAc8MKAGUJAN2xgYAZwDcVKoQDMDYnQBiECHQDeVOmYZawACwCGUOgEEAFAEpT5k5XPe6kkTY4AHms7AD46RX8OOgBeCIwbMABrG1xcCDA6EKgAbWIaAF1VLx8zQgB2CKicwuLvAF93MyaLLNt7ACFXFs9Ssz8A4PbwyIDY+MSUtIy2uxyNYiKW7wqqgJqlkrNGrboWnMkk7BEAGQzUxQBJDmwMApbNWfsHUm7d3r6BoOyRqPHFBLJVLpTLZPK1ZbmVajDgbOrmHbefaHY5nMAXa63e67R7ZOgdV5ud6Q/pRIZhNbROIAybAmZghabPoMSowuEtHb1IA=).

```asm
; A()
       push      rbp
       sub       rsp,10
       mov       rbp,rsp
       mov       rax,0DF49DDFD0FFA
       mov       [rbp+8],rax
       push      0
       push      0
       push      0
       push      0
       push      0
       push      0
       lea       rax,[rsp]
       movzx     eax,word ptr [rax]
       mov       rcx,0DF49DDFD0FFA
       cmp       [rbp+8],rcx
       je        short M00_L00
       call      CORINFO_HELP_FAIL_FAST
M00_L00:
       nop
       lea       rsp,[rbp+10]
       pop       rbp
       ret
; Total bytes of code 69

; B()
       push      rbp
       sub       rsp,10
       mov       rbp,rsp
       mov       rax,0AA9270D694B9
       mov       [rbp+8],rax
       mov       eax,4
M00_L00:
       push      0
       push      0
       dec       rax
       jne       short M00_L00
       lea       rax,[rsp]
       movzx     eax,word ptr [rax]
       mov       rcx,0AA9270D694B9
       cmp       [rbp+8],rcx
       je        short M00_L01
       call      CORINFO_HELP_FAIL_FAST
M00_L01:
       nop
       lea       rsp,[rbp+10]
       pop       rbp
       ret
; Total bytes of code 71

; A1()
       push      rbp
       sub       rsp,10
       mov       rbp,rsp
       mov       rax,49EA6D9A17EC
       mov       [rbp+8],rax
       push      0
       push      0
       push      0
       push      0
       push      0
       push      0
       lea       rax,[rsp]
       movzx     eax,word ptr [rax]
       mov       rcx,49EA6D9A17EC
       cmp       [rbp+8],rcx
       je        short M00_L00
       call      CORINFO_HELP_FAIL_FAST
M00_L00:
       nop
       lea       rsp,[rbp+10]
       pop       rbp
       ret
; Total bytes of code 69

; B1()
       push      rbp
       sub       rsp,10
       mov       rbp,rsp
       mov       rax,0B091A3F8138B
       mov       [rbp+8],rax
       test      [rsp],esp
       sub       rsp,40
       lea       rax,[rsp]
       movzx     eax,word ptr [rax]
       mov       rcx,0B091A3F8138B
       cmp       [rbp+8],rcx
       je        short M00_L00
       call      CORINFO_HELP_FAIL_FAST
M00_L00:
       nop
       lea       rsp,[rbp+10]
       pop       rbp
       ret
; Total bytes of code 64
```

If the constant allocation sizes are increased (e.g. to 60 and 64 respectively) this behavior doesn't show up.

---

The underlying "issue" is that we need to allocate 20 chars, so it's kind of unnatural to manually round up to the next power of two to get best codegen. Quoting @halter73:

> I think we should only ask for what we need and let the JIT optimize how it sees fit.

**Comment by EgorBo** [comment]
Isn't `A`'s codegen better than `B`? `B` has a loop to zero it while `A` unrolls it.

**Comment by gfoidl** [comment]
I don't know. It's a tiny loop and cpu's LSD should detect that and "unroll" it at hardware level.

Case A1 bothers me most. Codegen should be similar to B1, especially with SkipLocalsInit applied.

**Comment by EgorBo** [comment]
A quick benchmark:
```
| Method |      Mean |     Error |    StdDev |
|------- |----------:|----------:|----------:|
|      A | 1.4341 ns | 0.0334 ns | 0.0313 ns |
|      B | 1.9782 ns | 0.0309 ns | 0.0258 ns |
|     A1 | 1.0952 ns | 0.0101 ns | 0.0090 ns |
|     B1 | 0.6469 ns | 0.0120 ns | 0.0094 ns |
```

**Comment by hopperpl** [comment]
The Loop Stream Detector (LSD) does not work well for such tiny loops with effectively just 2 µops. The VTune reference manual states: "Typically, LSD provides good uOp support. However, in some rare cases, optimal uOp delivery cannot be reached for small loops whose size (in terms of number of uOps) does not suit well the LSD structure."

Therefore, the last loop iteration has a branch misprediction, which the benchmark confirms. 

In either case, a vmovdqa xmm instruction should be faster than push 0, which is actually generated up to stackalloc char[16]

**Comment by EgorBo** [comment]
Minor optimization, doesn't meet the bar for .NET 6.0, moving to 7.0
