### ISSUE TITLE
Incorrect string comparison for Japanese Dakuten and Handakuten with IgnoreCase option in .NET 5 ICU

### ISSUE THREAD

**Issue by naminodarie** [dotnet/runtime#55009]
### Description

similar to #54987 and #55008.

```C#
using System;
using System.Globalization;

Compare("は", "ば");
Compare("は", "ぱ");
Compare("ば", "ぱ");
Compare("ハ", "バ");
Compare("ハ", "パ");
Compare("バ", "パ");

void Compare(string s1, string s2)
{
    var result = CultureInfo.InvariantCulture.CompareInfo.Compare(s1, s2, CompareOptions.IgnoreCase);
    Console.WriteLine($"{s1} {CompareChar(result)} {s2}");
}
char CompareChar(int result) => result switch
{
    < 0 => '<',
    > 0 => '>',
    _ => '=',
};
```

When running this code with NLS or without IgnoreCase or IgnoreNonSpace, the result is:

```
は < ば
は < ぱ
ば < ぱ
ハ < バ
ハ < パ
バ < パ
```

but with ICU and IgnoreCase:

```
は < ば
は < ぱ
ば < ぱ
ハ > バ
ハ > パ
バ > パ
```

character|unicode|decomposed
:---:|:---|:---
は|U+306F|U+306F
ば|U+3070|U+306F U+3099
ぱ|U+3071|U+306F U+309A
ハ|U+30CF|U+30CF
バ|U+30D0|U+30CF U+3099
パ|U+30D1|U+30CF U+309A

### Configuration

.NET 5 or greater with ICU (default) option.

### Regression?

Yes

### Other information

HIRAGANA: https://www.unicode.org/charts/PDF/U3040.pdf
KATAKANA: https://www.unicode.org/charts/PDF/U30A0.pdf

**Comment by naminodarie** [comment]
@tarekgh It seems that updating custom collation rules for hiragana/katakana can solved this issue.
Can I send a PR?

**Comment by tarekgh** [comment]
@naminodarie how much you are familiar with the collation customization with ICU? I am asking because it is very tricky and fixing something can break something else. 

You are welcome to submit a PR and tag me there. Thanks for willing to help.
