### ISSUE TITLE
Append doesn't exist in System.Linq in net461 even with package installed

### ISSUE THREAD

**Issue by WhiteBlackGoose** [dotnet/runtime#55002]
I'm trying to multitarget net461 but I get a compilation error related to missing Append method. To repro the issue, just create an empty console app (even with `dotnet new console` too), change the target to `net461`, `dotnet add package System.Linq`, and refer to Linq's Append:
```cs
using System.Linq;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var a = new[] { 1, 2, 3 };
            a.Append(35);
        }
    }
}
```
![image](https://user-images.githubusercontent.com/31178401/124106035-848ba700-da6c-11eb-8ca0-d6d636bebe87.png)
Just in case, here's my csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq" Version="4.3.0" />
  </ItemGroup>

</Project>
```
Judging by [fuget](https://www.fuget.org/packages/System.Linq/4.3.0/netstandard1.6/lib/System.Linq.dll/System.Linq/Enumerable#Append), it should be there. Is it a bug or I missed something?

**Comment by stephentoub** [comment]
System.Linq.Enumerable is part of .NET Framework; adding a nuget reference to System.Linq doesn't replace the System.Linq.Enumerable you're using.  Enumerable.Append is only available in .NET Framework as of .NET Framework 4.7.1.

https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.append
![image](https://user-images.githubusercontent.com/2642209/124110901-b8e47080-da36-11eb-8abc-964545ba94e7.png)

**Comment by WhiteBlackGoose** [comment]
Isn't System.Linq supposed to add missing methods from higher targets to lower? Also, since it's still the same System.Linq namespace, shouldn't it see the newly added extension method from the package?

**Comment by WhiteBlackGoose** [comment]
Ooh, it indeed doesn't have it, thanks Stephentoub and Tebeco who is not here.
