### ISSUE TITLE
Visual Studio 2019 runtime error

### ISSUE THREAD

**Issue by krisrajzlive** [dotnet/runtime#55011]
All of a sudden got this error:

Evaluating the function System.Diagnostics.TrackInternalListeners.get timed out and needed to be aborted in an unsafe way. This may have corrupted the target process.

If the problem happens regularly, consider disabling the Tools->Options setting 'Debugging'->General->Enable property evaluation and other implicit function calls or change the code to disable evaluation of this method. See help for information on doing this.

Visited MS docs at https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?view=vs-2019, read and tried everything.

Tried many fixes but none of them helped
1. No .net code change has been detected
2. Commented the recent client side javascript changes
3. As per the dialog enabled\disabled Enable property evaluation
4. Retstarted my PC few times
5. retstarted VS
6. Updated Windows and restarted
7. Updated VS 2019 and restarted

Still can't run the project and stuck with the annoying dialog. Please let me know is there any other fix I should try

**Comment by tommcdon** [comment]
Hi, this seems to be an issue with Visual Studio.  Please follow these instructions on reporting a problem: https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
