### ISSUE TITLE
How do I access server certificate validation errors during LDAP connections?

### ISSUE THREAD

**Issue by AnthonyMastrean** [dotnet/runtime#55017]
How am I supposed to _implement_ server certificate checks in the [`LdapSessionOptions.VerifyServerCertificate`](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.ldapsessionoptions.verifyservercertificate?view=dotnet-plat-ext-5.0#System_DirectoryServices_Protocols_LdapSessionOptions_VerifyServerCertificate) callback without access to a populated [`SslPolicyErrors`](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslpolicyerrors?view=net-5.0)? 

I noticed that `SslStream`, via `SecureChannel`, performs certificate validation that returns a complete set of [policy errors](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs#L29). The routine it calls appears to be [internal/private and based on complicated interop](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs#L925) that I doubt I'm supposed to duplicate.

I know that `X509Certificate2` can provide a pass/fail answer. But, that runs only the `X509Chain` status checks, which does not include, for example, "RemoteCertificateNameMismatch".

```csharp
private bool VerifyServerCertificate(LdapConnection connection, X509Certificate certificate)
{
    var certificate2 = new X509Certificate2(certificate);
    return certificate2.Verify();
}
```

I could build an `X509Chain` and enumerate status, but that still misses the (few) other validations from `SslPolicyErrors`. And now I'm responsible for managing two extra disposable resources (although I'm not sure I can dispose them because each contains the original certificate that was passed in and I don't dare dispose that early).

```csharp
private bool VerifyServerCertificate(LdapConnection connection, X509Certificate certificate)
{
    var certificate2 = new X509Certificate2(certificate);
    var chain = new X509Chain();

    if (chain.Build(certificate2))
    {
        return true;
    }

    foreach (var element in chain.ChainElements)
    {
        foreach (var status in elements.ChainElementStatus)
        {
            // ... log something
        }
    }

    return false;
}
```

**Comment by wfurt** [comment]
chain.Build will return true if verification was successful. Rest would be only diagnostic IMHO. You may consider checking *(E)KU e.g. making sure the certificate was issued for server - X509Chain does not know. 

Peer can also return intermediate certificates. Verification can fail without them so preferably you want to make them available. 

Is there already API on the ldap that you truing to fit in? 

cc: @bartonjs for any more thoughts.

**Comment by AnthonyMastrean** [comment]
We allow application administrators to configure an LDAP server for authentication. They need detailed feedback on the certificate validation errors to know what changes to affect. For example...

 * replacing an IP address with a DNS name in the LDAP configuration
 * adding trusted certificates to the application server
 * or even requesting subject alternative names to be added to the remote server's certificate

We are currently using that [other LDAP library](https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/). It uses an `SslStream` directly and so provides the remote certificate validation callback that I mentioned earlier, which is provided by `SecureChannel` and does all the validations and hands them to you in a built chain and policy errors flags enum.

```csharp
public delegate bool RemoteCertificateValidationCallback(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors);
```

We're trying to move to System.DirectoryServices.Protocols, but finding it a bit trickier to provide the same level of detail.

**Comment by bartonjs** [comment]
According to https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/enable-ldap-over-ssl-3rd-certification-authority, LDAPS and HTTPS certificates should use roughly the same validation logic, which is the same logic built into SslStream.  (It's possible LDAPS isn't supposed to support wildcarding the SAN entry, not sure)

X509Chain will give you the obvious things... chained to a trusted root, not revoked, not expired.

```C#
chain.ApplicationPolicy.Add(new Oid("1.3.6.1.5.5.7.3.1", "1.3.6.1.5.5.7.3.1"));
```

will also add in "and the cert is valid as a TLS server cert".  But you're still missing the hostname check.

A simple way to perform the check would be to just make a new connection via SslStream, memo-izing the answer for the certificate.

```C#
private class LdapValidator
{
    private readonly string _hostname;
    private ConcurrentDictionary<string, bool> _knownCerts = new ConcurrentDictionary<string, bool>();

    internal LdapValidator(string hostname)
    {
        _hostname = hostname;
    }

    internal bool VerifyServerCertificate(LdapConnection connection, X509Certificate certificate)
    {
        return _knownCerts.GetOrAdd(
                certificate.GetCertHashString(HashAlgorithmName.SHA256),
                s => VerifyServerCertificateCore((X509Certificate2)certificate, _hostname));
    }

    private bool VerifyServerCertificateCore(X509Certificate2 certificate, string hostname)
    {
        try
        {
            // Use SslStream to connect to the host again.
        }
        catch (Whatever SslStream throws on failure)
        {
            return false;
        }

        return true;
    }
}
```

(at least, I couldn't figure out where the hostname is under the LdapConnection)

> The routine it calls appears to be internal/private and based on complicated interop that I doubt I'm supposed to duplicate.

That's correct :smile:.

We've brainstormed exposing the hostname check in #28771, but haven't really driven that anywhere.

**Comment by wfurt** [comment]
We could possibly move some code fragments to `Common` and use in in multiple places.

**Comment by wfurt** [comment]
I will make some changes to support #55193 @AnthonyMastrean. That should make it easier for LDAP to consume. 
You can always proceed with what @bartonjs outlined.

**Comment by AnthonyMastrean** [comment]
@wfurt I looked at #56175 and the `CertificateValidation` class and the improved `BuildChainAndVerifyProperties` method are still marked `internal`. Would these need to be _used_ by the `LdapConnection` class as part of improving the server certificate validation callback? Or do these need to be made public so that I can call them manually? Either way, is there an issue to track the next step?
