### ISSUE TITLE
[HTTP/3] Loopback server should handle graceful shutdown properly

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55025]
Currently, the HTTP3 loopback server used in tests is sending a GOAWAY frame but never closing the connection. This seems to lead to occasional races with the client in tests that issue multiple requests with the server closing the connection between requests. Some cookie tests are an example of this.

To function correctly per the RFC and to prevent these races, the HTTP3 loopback server needs to do the following:

(1) Send GOAWAY (it's doing this already)
(2) Accept any incoming streams and abort them with the H3_REQUEST_REJECTED
(3) When the client closes the connection, the AcceptStream operation from (2) will return null, indicating the connection has been closed. At this point the server can close its connection.

See https://quicwg.org/base-drafts/draft-ietf-quic-http.html#name-connection-shutdown

Note: I'm not sure the client is handling graceful shutdown properly itself; we may need to fix this as well in order to get this all to work.

**Comment by geoffkizer** [comment]
I'm removing "test enhancement" here because the root issue isn't a test issue. We can't implement this properly in the loopback server because there's some product issue (not understood yet) that causes this to not work.

**Comment by karelz** [comment]
Triage: Affects test reliability
