### ISSUE TITLE
ToBase64Transform wholly inadequate to live in the BCL

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#55029]
As can be seen in the code, it transforms chunks *per 3 bytes*.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Encoding/src/System/Security/Cryptography/Base64Transforms.cs#L37

This means it skips any and all simd paths in Base64.EncodeToUtf8, not to mention a gazillion calls to this transformer with tiny arrays to get the data encoded.

Benchmarking this against `Convert.ToBase64String` *for reference only, I really do want a stream* on a random 4k image results in more than an order of magnitude difference. So if `Convert.ToBase64String` can do it in 10ms, `ToBase64Transform` does it in say 120ms.

**Comment by gfoidl** [comment]
For reference / completeness: https://github.com/dotnet/runtime/issues/30294#issuecomment-513304310

**Comment by NinoFloris** [comment]
Thanks @stephentoub!
