### ISSUE TITLE
ILVerify: bug in verification of InitOnly fields

### ISSUE THREAD

**Issue by lovettchris** [dotnet/runtime#55033]
### Description

This code fails to verify:

```csharp
using System;

namespace ILVerifyBug
{
    public class ActorId
    {
        public readonly ulong Value;
    }

    class Program
    {
        ActorId id = new ActorId();

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }

        public override int GetHashCode()
        {
            return this.id.Value.GetHashCode();
        }
    }
}
```

### Configuration

* Which version of .NET is the code running on? .net 5.0
* What OS and version, and what distro if applicable? Windows 10
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? No

### Regression?

Don't know

### Other information

The errors are being reported by this line of code in `ImportAddressOfField`:

https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/ILVerification/ILImporter.Verify.cs#L2110

**Comment by JulieLeeMSFT** [comment]
Moving from .NET 6 to future because ILVerify is preview feature.
