### ISSUE TITLE
CryptoNative_GetX509NameRawBytes assert failure in CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55038]
This assert:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Native/Unix/System.Security.Cryptography.Native/openssl.c#L391-L404
failed here:

net6.0-Linux-Debug-x64-CoreCLR_release-SLES.15.Amd64.Open
https://dev.azure.com/dnceng/public/_build/results?buildId=1215774&view=ms.vss-test-web.build-test-results-tab&runId=36284970&paneView=debug
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51653-merge-c7295d0c68554d41ae/System.Security.Cryptography.X509Certificates.Tests/console.6e780ff5.log?sv=2019-07-07&se=2021-07-21T14%3A13%3A18Z&sr=c&sp=rl&sig=82j5HfZOmJPAZLgdXSXr5OMinlqsbJ1YQcdl9J1mYdk%3D
```
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.X509Certificates.Tests (found 606 of 700 test cases)
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 2)
dotnet: /__w/1/s/src/libraries/Native/Unix/System.Security.Cryptography.Native/openssl.c:402: int32_t CryptoNative_GetX509NameRawBytes(X509_NAME *, uint8_t *, int32_t): Assertion `0 && "Huge length X509_NAME"' failed.
./RunTests.sh: line 162: 14474 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

**Comment by vcsjones** [comment]
Looks like a dupe of #49732.

**Comment by stephentoub** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/49732.
