### ISSUE TITLE
Sub-optimal code generated for Unsafe.As

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#55064]
### Description
```csharp
using System.Runtime.CompilerServices;

[MethodImpl(MethodImplOptions.AggressiveInlining)]
byte Create<T>(T value)
{
    return Unsafe.As<T, byte>(ref value);
}

Console.WriteLine(Create(500));
Console.WriteLine(Create(500L));

```

JIT dump:
```asm
mov     dword ptr [rsp+0x44], 0x1f4
movzx   ecx, byte ptr [rsp+0x44]
call    System.Console.WriteLine(Int32)
mov     qword ptr [rsp+0x38], 0x1f4
movzx   ecx, byte ptr [rsp+0x38]
call    System.Console.WriteLine(Int32)

```

I think the `ref` can be omitted so that `value` won't be spilled to stack,
which is expected to be (on a little endian system):
```asm
mov	     ecx, 0xf4
call    System.Console.WriteLine(Int32)
mov     ecx, 0xf4
call    System.Console.WriteLine(Int32)

```

### Configuration
Version: .NET 6 preview 5
Tiered Compilation: off

category:cq
theme:codegen
skill-level:intermediate
cost:small
impact:medium

**Comment by tannergooding** [comment]
Only the first two would print `0xF4` (`244`) and only on a little endian system.

The latter two are converting from float/double, respectively, and will both print `0` (as the floating-point representation involves a sign, exponent, and mantissa and the LSB will be `0` for this).
There are certainly some improvements that could go on here, but its not quite as simple as just taking the least significant byte of the input integer.

**Comment by hez2010** [comment]
My bad. I used `(byte)(TTarget)(object)value` pattern for the comparation and didn't realize that `(byte)(float)(object)value` isn't the same with `Unsafe.As<float, byte>(value)`.
