### ISSUE TITLE
Files with GPL license

### ISSUE THREAD

**Issue by fb33** [dotnet/runtime#55072]
Hello,

Our license analysis tool (ORT) has detected the presence of a GPL license that is not compatible with most opensource policies of companies that do not produce opensource software.

https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/bench.cs#L65
https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/THIRD-PARTY-NOTICES.TXT#L17

Can you change this, so that you don't use GPL code anymore?
Or can you confirm that this code (bench.cs) is not packaged in the production module ?

Thanks,
Regards

**Comment by alexrp** [comment]
That code is for testing/benchmarking the Mono JIT. It is never shipped with the .NET distribution in any form.

**Comment by richlander** [comment]
Our policy is:

- No GPL for the shipping product.
- GPL for test code is A-OK.
- Test code gets its own third party notice (TPN) to (A) acknowledge the third part use, and (B) isolate test code notices (GPL or otherwise) from the product TPN.

**Comment by SamMonoRT** [comment]
This issue can be closed as this is test code only. @fb33 - please close if this satisfies the current requirements.

**Comment by fb33** [comment]
Thanks for your answers
