### ISSUE TITLE
FOREACH-loop doesn't throw InvalidOperationException on collection modification

### ISSUE THREAD

**Issue by NiJeTi** [dotnet/runtime#55088]
### Description

Suddenly this code doesn't throw InvalidOperationException on `list[0] = 0` nor `list.Add(3)` lines:

```cs
var list = new List<int> { 0, 1, 2 };

foreach (var x in list)
{
    if (x == 0)
    {
        for (var i = int.MinValue; i < int.MaxValue; i++)
            list[0] = 0;

        list.Add(3);
    }

    Console.Out.WriteLine(x);
}
```

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

This bug isn't specific to any configuration.

### Regression?

First time this worked in a .NET Framework 4.6.1 and so on up to .NET 5.

### Other information

If you change the number of `for` loop iterations at least by 1, exception will be thrown successfully on `enumerator.MoveNext()` method.

This bug is caused by internal `_version` field of the `List` type. After full cycle by `int` `_version` decreases by 1 and `Add` method call increases it. It makes it equal to the same value it was before `for` loop and let's `MoveNext` to successfully work.

This bug can be fixed by calculating `_version` another way (not just incrementing it). Using hash code, for example.
But it will significantly increase modification methods load so, IMHO, it should not be done.

**Comment by huoyaoyuan** [comment]
> After full cycle by `int`

This is definitely a rare case that most lists won't live for so long.
Currently implementation already has overhead, and we don't want to increase it more.

**Comment by GrabYourPitchforks** [comment]
I agree with @huoyaoyuan that this is such an edge case that it wouldn't happen under any reasonable course of execution. IMO there's no need for us to defend against this kind of code.
