### ISSUE TITLE
Configuration variable cannot be read from appsettings.json on MacOS when running as published single file

### ISSUE THREAD

**Issue by RishoT17** [dotnet/runtime#55089]
### Describe the bug
A custom configuration variable set in appsettings.json is not read correctly using Configuration.GetSection().Value. It is null when ran as a standalone executable, after being published using "dotnet publish". This works fine on Windows (win10-x64).

### To Reproduce
1. On MacOS, create a new project using the "ASP.NET Core Empty" Visual Studio template
2. Change appsettings.json to:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "HostUrl": "http://192.168.0.1:5000"
}
```
3. Change the Startup class to:
```
public class Startup
    {
        public IConfiguration Configuration { get; }
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            Console.WriteLine("Configuration - HostUrl: " + Configuration.GetSection("HostUrl").Value);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
            });
        }
    }
```
4. Publish using "dotnet publish --self-contained true -p:PublishSingleFile=true -r osx.11.0-x64"
5. Run bin\Debug\net5.0\osx.11.0-x64\publish\YourAppName.app (double-click the file in Finder)
6. Notice that console prints out "Configuration - HostUrl:" without the actual value from appsettings.json

### Exceptions (if any)
This works fine on win10-x64, also works fine when ran from within VS on Mac

### Further technical details
- ASP.NET Core version
  - Microsoft.AspNetCore.App (5.0.0)
  - Microsoft.NETCore.App (5.0.0)

- Include the output of `dotnet --info`

> .NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

> Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.301/

> Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

> .NET SDKs installed:
  3.1.410 [/usr/local/share/dotnet/sdk]
  5.0.301 [/usr/local/share/dotnet/sdk]

> .NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

> To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
  - Visual Studio for Mac Professional 8.10.3 (build 15)
  - macOS BigStur Version 11.2.3

**Comment by eerhardt** [comment]
@RishoT17 - what does it do when you don't publish single file?

Also, can you show your exact terminal output when running on MacOS? In your repro steps you have:

```
5. Run bin\Debug\net5.0\osx.11.0-x64\publish\YourAppName.exe
```

which doesn't make sense on MacOS

**Comment by RishoT17** [comment]
@eerhardt I updated step 5 to
`5. Run bin\Debug\net5.0\osx.11.0-x64\publish\YourAppName.app (double-click the file in Finder)`

I get the same output for non-single file. Here's the output:

```
Last login: Mon Jul  5 14:14:39 on ****

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Users/MyName/Projects/ProjectName/bin/Debug/net5.0/osx.11.0-x64/publish/ProjectName; exit;
MyName$ /Users/MyName/Projects/ProjectName/bin/Debug/net5.0/osx.11.0-x64/publish/ProjectName; exit;
Configuration - HostUrl: 
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/MyName
```

**Comment by eerhardt** [comment]
The content root gets defaulted to `Directory.GetCurrentDirectory()` here:

https://github.com/dotnet/runtime/blob/515f7c104975fface92b7e155c92bb3b96f67b3b/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L192

`GetCurrentDirectory` is the current working directory of the process. When you run in VS, the current working directory is the folder your .csproj is. And there is an `appsettings.json` file in that folder, so it reads that instead of the one in `bin\Debug\...`.  But when you publish, `GetCurrentDirectory()` is where your Terminal is currently `cd'd` into. In the case when you just double-click the app on a mac, it must be setting the current working directory to `/Users/MyName`.

If you always want the content root to be something else, you can add the following line in your Program.cs file:

```c#
        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseContentRoot(AppContext.BaseDirectory);  // add this line
                    webBuilder.UseStartup<Startup>();
                });
```

**Comment by eerhardt** [comment]
Closing as I believe I have explained the behavior here and have recommended a solution. Feel free to re-open if this is not the case.

**Comment by Tratcher** [comment]
Is there any way to detect the app was launched this way and automatically set the content root to the AppContext.BaseDirectory?

**Comment by eerhardt** [comment]
> any way to detect the app was launched this way

Launched which way? 

I believe that would be a breaking change....

**Comment by Tratcher** [comment]
Launched interactively from the GUI vs being run from the command line.

**Comment by eerhardt** [comment]
That I don't know how to detect... :(

**Comment by RishoT17** [comment]
Thanks for your help! I now understand what's happening and how to fix it.

I might be worth looking more into this. Considering usability, from the end-user's perspective, it might still look "broken": Double-clicking the executable produced by the exactly same code should probably behave in the identical way between Mac and Windows. Although I understand that a change like that could cause more backward-compatibility issues.
