### ISSUE TITLE
Blazor Web assembly project with prerendering and accessing data through Grpc is not running in local IIS server

### ISSUE THREAD

**Issue by Keerthi-Mettu** [dotnet/runtime#55093]
### Description
I have two simple web assembly projects having Grpc service in the following links.
[without pre-rendering](https://github.com/Keerthi-Mettu/SimpleGrpc-in-Blazor-Wasm)
[with pre-rendering](https://github.com/Keerthi-Mettu/BlazorWasm-Pre-rendering-with-Grpc)

Both the solutions work fine when run in Visual studio. However, when each of the solutions is published and hosted through the local IIS server, the one without pre-rendering is working fine but the other is not. 

![image](https://user-images.githubusercontent.com/79932039/124316278-389f3780-db2a-11eb-82db-516d2d3d3296.png)
_The output of the web assembly project when hosted thru local IIS._

![image](https://user-images.githubusercontent.com/79932039/124316634-bfecab00-db2a-11eb-9b45-40e08e9f1e97.png)
_The output of the pre-rendered web assembly project when hosted thru local IIS._

**Error in brief:**
```
RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.Net.Http.Http2ConnectionException: The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode) in System.Net.Http.dll:token 0x60005f3+0x6
at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame) in System.Net.Http.dll:token 0x60005bc+0x1ea
at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync() in System.Net.Http.dll:token 0x60005bd+0x93
```

Code snippet in the prerendering project solution that is registering the Grpc channel as a service in the startup.cs file:

```c#
 public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllersWithViews();
            services.AddRazorPages();
            services.AddGrpc();
            services.AddSingleton<HttpClient>(sp =>
            {
                // Get the address that the app is currently running at
                var server = sp.GetRequiredService<IServer>();
                var addressFeature = server.Features.Get<IServerAddressesFeature>();
                string baseAddress = addressFeature.Addresses.First();
                return new HttpClient { BaseAddress = new Uri(baseAddress) };
            });

            services.AddSingleton(services =>
            {
                var server = services.GetRequiredService<IServer>();
                var addressFeature = server.Features.Get<IServerAddressesFeature>();
                string baseAddress = addressFeature.Addresses.First();
                Console.WriteLine("first base in server -- " + addressFeature.Addresses.First());
                Console.WriteLine("last base in server -- " + addressFeature.Addresses.Last());
                var httpHandler = new GrpcWebHandler(GrpcWebMode.GrpcWeb, new HttpClientHandler());
                return GrpcChannel.ForAddress(baseAddress, new GrpcChannelOptions { HttpHandler = httpHandler });
            });
        }
```

Startup.cs code in non-prerendering solution vs Startup.cs code in the prerendering solution
![image](https://user-images.githubusercontent.com/79932039/124319519-2ffd3000-db2f-11eb-83c4-e5c027baf302.png)

Program.cs code in non-prerendering solution vs Program.cs code in prerendering solution
![image](https://user-images.githubusercontent.com/79932039/124318920-45258f00-db2e-11eb-8903-83d1a7fe466a.png)

Please let me know if I am missing anything.

### Configuration

- .Net 6 preview 5
- ![image](https://user-images.githubusercontent.com/79932039/124498769-be60f400-dd71-11eb-9f32-c5504f759d1c.png)
- _In IIS, the site binding is having a HTTPS connection (with a self- signed certificate)_
- My OS build version is 19042.1052

**Comment by ManickaP** [comment]
The error looks like you are trying to connect to HTTP 1.1 server while expecting H/2, probably over http and not https (versioning there should be handle by ALPN).
This doesn't seem like `HttpClient` issue, gRPC, IIS and Blazor are well beyond my knowledge.

@JamesNK is this something you could help with?

**Comment by Keerthi-Mettu** [comment]
However, when this pre-rendered solution is run locally through visual studio, it works on the H2 protocol. 

_Screenshots of the browser Network tab:_

![image](https://user-images.githubusercontent.com/79932039/124674445-98217e00-de6f-11eb-8ae7-cb89793243de.png)
![image](https://user-images.githubusercontent.com/79932039/124674475-af606b80-de6f-11eb-971a-a605ae70c08c.png)

I have also tested this project running on a remote IIS server, where the website is configured with a valid trusted certificate for HTTPS bindings. But still, the error persists.  

Please let me know if I missed any configurations so far. Thanks

**Comment by ManickaP** [comment]
Could you collect IIS logs with protocol version: https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#logging-protocol-version

**Comment by Keerthi-Mettu** [comment]
[past 2 days log files.zip](https://github.com/dotnet/runtime/files/6778790/past.2.days.log.files.zip)

I added the log files for both my local IIS and remote system IIS (recently enabled protocol version logging in this) in separate folders for the last 2 days.

**Comment by Keerthi-Mettu** [comment]
Thank you for asking the log files.

From my understanding through these logs, I see that my remote IIS server is on version 8.5, and it is supporting the non-prerendering Grpc solution via HTTP 1.1 protocol but not the prerendering solution. Now I know that IIS 8.5 doesn't support H2 protocol (stated in the same link you sent), I just need to know why is the prerendering Grpc is not at all working (even via HTTP 1.1) or are there any additional steps/configs to let it work?

**Comment by ManickaP** [comment]
Yep, it's 1.1:
```
# remote
2021-07-07 08:25:45 10.157.232.182 GET / - 443 - S01062c7e81ff0db7.vw.shawcable.net HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/91.0.4472.114+Safari/537.36+Edg/91.0.864.59 - 500 0 0 675
# local
2021-07-07 00:38:35 127.0.0.1 GET / - 443 - 127.0.0.1 HTTP/2 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/91.0.4472.124+Safari/537.36 - 500 0 0 242
```

You have to make sure you're using H/2. This might be misconfigured IIS. I recommend checking https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10/http2-on-iis#iis-with-http2-demo-walkthrough and further on that page.

I'm trying to help as much as possible but IIS is out of scope of this repo and my knowledge so I cannot give you easy, precise solution to your problem.

**Comment by karelz** [comment]
Triage: Seems to be answered to our best knowledge, closing
