### ISSUE TITLE
Prepare the JIT for a standalone build

### ISSUE THREAD

**Issue by pgavlin** [dotnet/runtime#5510]
i.e. a build that can take place in isolation from the rest of CoreCLR.

In large part this involves removing dependencies between the JIT and the runtime. How a dependency is removed differs based on its nature:
- OS/environmental dependencies may either be subsumed into the JIT's PAL or moved behind the JIT hosting interface (as appropriate)
- EE data structures/utilcode may be replaced with data structures that are private to the JIT or moved behind the JIT/EE interface (as appropriate)

category:implementation
theme:build
skill-level:intermediate
cost:medium
impact:medium

**Comment by AndyAyersMS** [comment]
Things are fairly well isolated now: `build -subset clr.jit` is pretty minimal.
