### ISSUE TITLE
.NET Core System.Math type has no overloaded support for Exp(decimal)

### ISSUE THREAD

**Issue by carlyman77** [dotnet/runtime#55113]
At time of writing, there are no overloaded methods in the `System.Math` type for many `decimal` operations, including `Exp(decimal)`. I noticed this became quite the issue when attempting to perform calculations such as calculating the determinant of a matrix. I believe this extra functionality will be extremely useful for those of us who require extra precision.

Proposed area would be area-System.Numerics.

Thank you for reading and I look forward to the discussion.

**Comment by huoyaoyuan** [comment]
You do not need to open separated issues for closed topics (Math and decimal).

Since there's no hardware support for `decimal`, the implementation of these methods would be quite difficult, especially when you are requiring precision. We also need to first define then test the rounding cases.

**Comment by carlyman77** [comment]
My apologies -  by "native support" I wasn't referring to a hardware requirement, I was meaning that I'd like to see `decimal` overloads of existing methods. I will update the description.

**Comment by koszeggy** [comment]
> I wasn't referring to a hardware requirement, I was meaning that I'd like to see `decimal` overloads of existing methods.

Feel free to use my [`DecimalExtensions`](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/master/KGySoft.CoreLibraries/CoreLibraries/_Extensions/DecimalExtensions.cs), which happens to have `Exp` and `Log` methods. Maybe it could be optimized further but it can be a good start. Available also as a [NuGet](https://www.nuget.org/packages/KGySoft.CoreLibraries).

**Comment by carlyman77** [comment]
> Feel free to use my [`DecimalExtensions`]

Thanks mate. I ended up writing my own, but it'd be great to see these included in the FCL as standard. Ideally, with an arbitrary sized rational (such as `Rational<T, T>` for example) - not asking for too much eh? 😂

**Comment by huoyaoyuan** [comment]
> but it'd be great to see these included in the FCL as standard.

BCL requires a lot. It should be stable in behaviour, which require us to define every cases and can hardly change in future. It should be performant. There should be a lot of consumers, especially in first party components to make it benefitial to live in BCL.

**Comment by huoyaoyuan** [comment]
> Hasn't this already been done for `double`?

`double` is defined by IEEE754 specification. `decimal` was originally an MS internal type. It isn't implemented widely.

**Comment by tannergooding** [comment]
This is "by design". `System.Decimal` is a type designed for and around `currency` and does not expose many of the concepts required to correctly support transcendental functions.

We may in the future look at providing the IEEE 754 `decimal` types and would provide such APIs for said types if that happens.
