### ISSUE TITLE
Wrong nullability annotation in Enumerable.Max(IEnumerable<TSource>, IComparer<TSource> comparer) method

### ISSUE THREAD

**Issue by hrumhurum** [dotnet/runtime#55125]
https://github.com/dotnet/runtime/blob/0605bb3aba533702f234c907906ef076a97131fe/src/libraries/System.Linq/src/System/Linq/Max.cs#L445

The current method signature is:

 ```TSource? Max<TSource>(this IEnumerable<TSource> source, IComparer<TSource>? comparer)```

but it should be:

 ```TSource Max<TSource>(this IEnumerable<TSource> source, IComparer<TSource>? comparer)```

because there is no possibility for the method to return `default` value. `Max` (and `Min`) methods always throw an exception when the sequence has no elements.

**Comment by eiriktsarpalis** [comment]
The throwing behaviour is confined to value type enumerables: for reference types the same methods will instead return null. Therefore the existing annotation is correct in the general case.
