### ISSUE TITLE
Analyzer proposal: Declare elements attributed with `JsonPropertyName` as nullable

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#55130]
For example, I had the following:

```csharp
    internal sealed record DocfxConfiguration(
        [property: JsonPropertyName("build")] DocfxBuild Build);

    internal sealed record DocfxBuild(
        [property: JsonPropertyName("content")] DocfxContent[] Contents);

    internal sealed record DocfxContent(
        [property: JsonPropertyName("exclude")] string[] Excludes);
```

I think all those properties should be declared as nullable, since they can be missing from the json file being deserialized.

**Comment by eiriktsarpalis** [comment]
I'm not sure I understand why properties specifically annotated with `JsonPropertyName` should be made nullable. Isn't it the case that _any_ deserialized property could be missing from the underlying JSON?

Realistically we'd be looking at adding an analyzer that demands _every_ type being declared as nullable, which in practice could be problematic.
