### ISSUE TITLE
JIT incorrectly reorders method call and static field load

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#55140]
```csharp
// Generated by Fuzzlyn v1.2 on 2021-07-04 03:25:56
// Seed: 15223751612356996744
// Reduced from 39.3 KiB to 0.3 KiB in 00:00:22
// Debug: Outputs 1
// Release: Outputs 0
using System.Runtime.CompilerServices;

public class Program
{
    static byte s_9;
    public static void Main()
    {
        uint vr0 = (uint)((0 - M4()) + s_9);
        System.Console.WriteLine(vr0);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static int M4()
    {
        return s_9++;
    }
}
```
Looks like we end up loading `s_9` before the call to `M4` when optimizing. The problem is that this needs to check for more side effects:
https://github.com/dotnet/runtime/blob/607f98c888b31566c773712c3153236c7cec05d2/src/coreclr/jit/morph.cpp#L12900-L12950

**Comment by SingleAccretion** [comment]
This should use `gtCanSwapOrder` for the first transform, while the second transform can be done always. I'll put up a fix.

**Comment by jakobbotsch** [comment]
> Edit: do these identities apply for floating point?

I believe so yes, since floating point addition is commutative.
