### ISSUE TITLE
[SuperPMI] Investigate EH interactions across the JIT/EE interface.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/runtime#5514]
In order to isolate the JIT from CoreCLR, EH interactions over the interface need to be understood and any supported/necessary interactions codified appropriately. This includes interactions with the CLR's `DebugState` APIs, as the JIT must stop calling them directly as part of dotnet/runtime#5513/#4126.

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Closing
