### ISSUE TITLE
MsQuic configuration handle is created but not used

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55158]
See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs#L175

**Comment by geoffkizer** [comment]
Note also, we create another equivalent config handle here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs#L162

This one is stored into a field, then used later in ConnectAsync.

This all seems less than ideal. I wonder if we should just pass QuicClientConnectionOptions to ConnectAsync, or something like that.

**Comment by ManickaP** [comment]
Relevant issue: https://github.com/dotnet/runtime/issues/42642

**Comment by karelz** [comment]
Triage: Not needed, but super simple (remove 1 line).
