### ISSUE TITLE
QUIC: SHUTDOWN_INITIATED_BY_TRANSPORT on connection should not result in QuicOperationAbortedException

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55157]
SHUTDOWN_INITIATED_BY_TRANSPORT can indicate a variety of different errors, including stateless reset or a QUIC protocol error. It's determined locally by MsQuic (hence the name). 

Currently, if we receive SHUTDOWN_INITIATED_BY_TRANSPORT from MsQuic, we generate a QuicOperationAbortedException for any attempted operations on the connection (e.g. AcceptStreamAsync). 

This seems like the wrong exception. QuicOperationAbortedException is intended to mean that the local user closed the connection, and thus the outstanding operation was aborted as a result. 

We could use QuicConnectionAbortedException here, except that this requires an error code, and is intended for cases where the peer explicitly closed the connection, so it doesn't seem ideal.

We probably need a new exception type for this. And we may want to distinguish different error cases within this.

**Comment by wfurt** [comment]
can we reliably detect the reason? 
cc: @nibanks

**Comment by nibanks** [comment]
> can we reliably detect the reason? 
> cc: @nibanks 

The event does give you a status code. It might not always clearly differentiate all possible reasons, but if you ever need more, we can add more specific status codes.

**Comment by karelz** [comment]
Triage: QUIC does not have direct users. Unless ASP.NET needs this, it is not critical for 6.0. Moving to 7.0 for now.
