### ISSUE TITLE
QUIC: Implement cancellation support for QuicConnection.CloseAsync

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55155]
The cancellationToken is ignored currently.

**Comment by karelz** [comment]
Triage: This behavior of QuicConnection does not seem to be critical for 6.0. On QuicStream it is.
Moving to 7.0.

**Comment by ManickaP** [comment]
Closing since this is covered by https://github.com/dotnet/runtime/issues/68902, at best we can cancel waiting for the event, there's no way to cancel an operation in msquic.
