### ISSUE TITLE
Test failure System.Drawing.PrimitivesTests.PointFTests.EqualityTest_NotPointF

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55168]
Run: [runtime-coreclr libraries-jitstress 20210704.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1219863&view=ms.vss-test-web.build-test-results-tab&runId=36366046&resultId=111708&paneView=debug)

Failed test:
```
net6.0-Linux-Release-arm64-CoreCLR_checked-jitminopts-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.Drawing.PrimitivesTests.PointFTests.EqualityTest_NotPointF

```
**Error message:**
```
Assert.Equal() Failure
Expected: False
Actual:   True


Stack trace
   at System.Drawing.PrimitivesTests.PointFTests.EqualityTest_NotPointF() in /_/src/libraries/System.Drawing.Primitives/tests/PointFTests.cs:line 159
```

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
