### ISSUE TITLE
Saving a cloned image after using Graphics.FromImage results in no output on Linux

### ISSUE THREAD

**Issue by handerss-tibco** [dotnet/runtime#55165]
Link to a re-producible example: https://github.com/handerss-tibco/dotnet-no-graphics/blob/main/Program.cs

### Description

Running a program on Linux and Windows result in different behavior when trying to save an `Image` which has been modified via `Graphics.FromImage` and then subsequently cloned.

```csharp
var image = ...; // Some image
var modifiedImage = UseGraphics(image); // Modify using Graphics.FromImage
var clone = modifiedImage.Clone() as Image;
clone.save("out.png"); // Blank image on Linux. Works as expected on Windows.
```

Interestingly, if the `modifiedImage` is saved to a memory stream or to disk (the saved result can be discarded), then saving the clone works as expected. Also if we use `new Bitmap(modifiedImage)` instead of clone, then the save also works as expected. Flushing the graphics buffer or modifying `modifiedImage` via e.g. `SetPixel` still produces a blank image on Linux.

A re-producible example is available at: https://github.com/handerss-tibco/dotnet-no-graphics. This example will produce one blank image `out1.png`, and two correct images `out{2,3}.png` on Linux. All images are correct on Windows however.

### Configuration

Runtime: .NET 5.0.7
Linux: WSL2 running Ubuntu-20.04 with `libgdiplus` installed.
Arch: x64

**Comment by koszeggy** [comment]
@handerss-tibco: It is a known issue and affects also Mono (maybe a bug in libgdiplus?). But there is a workaround that [I also use](https://github.com/koszeggy/KGySoft.Drawing/blob/0f8cec1f6a20c36894d0a1588ec30dcb81d4de73/KGySoft.Drawing/Drawing/_Extensions/BitmapExtensions.cs#L1101) in my libraries:

```cs
/// <summary>
/// Returns a clone of a bitmap in a way that works also on Linux where Image.Clone
/// may return a fully transparent image.
/// </summary>
internal static Bitmap CloneBitmap(this Bitmap bmp) =>
    bmp.Clone(new Rectangle(Point.Empty, bmp.Size), bmp.PixelFormat);
```

In fact, in some cases this is not enough, eg. multipage `Bitmaps` may have further issues (TIFF, GIF, Icons) so I created also a [`CloneCurrentFrame`](https://github.com/koszeggy/KGySoft.Drawing/blob/0f8cec1f6a20c36894d0a1588ec30dcb81d4de73/KGySoft.Drawing/Drawing/_Extensions/BitmapExtensions.cs#L207) method, feel free to use it.

**Comment by handerss-tibco** [comment]
@koszeggy Our current workaround is to just copy the bitmap using `new Bitmap`. This works for our case but probably won't work for performance intensive stuff (since Clone is copy-on-write).

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
