### ISSUE TITLE
Global Mutex

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#55169]
The documentation doesn't go into much detail about this.

Are global [Mutexes](https://docs.microsoft.com/en-us/dotnet/api/system.threading.mutex?view=net-5.0) by default lockable by any user?
Is it the same on Windows and Unix?

cc @kouvel @stephentoub

**Comment by kouvel** [comment]
Yes by default global mutexes can be locked by any user on Windows and Unixes.

**Comment by tmds** [comment]
Closing, my question is answered.
