### ISSUE TITLE
Warning SYSLIB0014: (FtpWebRequest)WebRequest.Create() is obsolete (use HttpClient)	

### ISSUE THREAD

**Issue by GW-Lab** [dotnet/runtime#55166]
If you lookup the documentation for warning  SYSLIB0014 then the alternative for  (FtpWebRequest)WebRequest.Create() is HttpClient.

This is wrong or i'm missing something here?

**Comment by ManickaP** [comment]
@aik-jahoda I see that you added the obsoletions here. Is this correct? What is the recommended replacement? `HttpClient` cannot handle ftp requests AFAIK.

**Comment by GW-Lab** [comment]
In VS 16.11.2 using .Net 6 you get the warning  SYSLIB0014  if you use (FtpWebRequest)WebRequest.Create()  see picture 1:

It is stated to use HttpClient instead.  (but this is misleading / wrong)

1. The warning obsolate is ok bud the solution to use HttpClient is wrong!!! 
2. So my questions is what is the alternative?

Picture 1:
(https://user-images.githubusercontent.com/49092462/124575982-2c79e980-de4c-11eb-988b-f71296d70185.png)t

**Comment by karelz** [comment]
Here's the warning text: https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0014
It is true, that it does not explicitly mention `FtpWebRequest` - alternatives for it are mentioned in its docs though: https://docs.microsoft.com/en-us/dotnet/api/system.net.ftpwebrequest?view=net-5.0#remarks

I don't think we need to update the inline text in VS warning, but perhaps we can update the docs article: https://docs.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0014#workarounds

**Comment by GW-Lab** [comment]
Ok. thanks
