### ISSUE TITLE
Can't Blazor WASM use  P/Invoke to import C++ DLL?

### ISSUE THREAD

**Issue by BigHeadDev** [dotnet/runtime#55171]
WebBrowser console output “DLLNotFound”

**Comment by Joe4evr** [comment]
No. WASM is spec'd to execute within a safe browser sandbox, so you can't do arbitrary file IO (among a few other things).

**Comment by radical** [comment]
With preview7,  libraries can be added with `<NativeFileReference Include="foo.dll" />`. It will get linked in.
You can wait for the preview7 release, or try it from https://github.com/dotnet/installer#installers-and-binaries .
