### ISSUE TITLE
Add a ReadOnlySpan<char> version for FixedTimeEquals

### ISSUE THREAD

**Issue by dzsibi** [dotnet/runtime#55175]
## Background and Motivation

.NET Core has `CryptographicOperations.FixedTimeEquals` for byte spans since 2.1. It would make sense to include an overload that takes `ReadOnlySpan<char>` for its parameters, making it possible to use it with strings and char spans. This could come in handy in a variety of scenarios where constant-time string comparisons are needed - the most relevant example that comes to mind would be checking API keys / tokens, which are usually passed in as strings.

If one wants to perform a constant-type string comparison right now, one needs to either implement one, copy and paste the existing code fragment for byte spans, or encode the string before performing a comparison. These all seem error prone and inefficient to me.

## Proposed API

```diff
namespace System.Security.Cryptography
{
    public static class CryptographicOperations
    {
        public static bool FixedTimeEquals(ReadOnlySpan<byte> left, ReadOnlySpan<byte> right)
+       public static bool FixedTimeEquals(ReadOnlySpan<char> left, ReadOnlySpan<char> right)
    }
}
```

Note: the actual implementation would be the same.

## Usage Examples

The same as for the original FixedTimeEquals, but now `key` and `actualKey` can be strings.

``` C#
if (!CryptographicOperations.FixedTimeEquals(key, actualKey))
    throw new MyLittleUnauthorizedException();
```

## Alternative Designs

Another option would be to implement a new StringComparer/StringComparison type, something like OrdinalFixedTime. I think that would be an overkill - few use cases require constant time string comparisons. It also wouldn't work as one might expect for most operations where it might be useful - implementing constant-time Contains operations on collections is not really possible using the existing interfaces and algorithms.

## Risks

I am not aware of any.

**Comment by teo-tsirpanis** [comment]
You can use [`MemoryMarshal.AsBytes`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.asbytes) to convert your span of characters to a span of bytes and then call `FixedTimeEquals`.

Introducing overloads for more types other than bytes would open the argument for making `FixedTimeEquals` generic, something IMHO not needed because cryptography mainly deals with bytes.

**Comment by vcsjones** [comment]
One thing that would concern me about this API would be that it implies it is reasonable to compare text data securely and as long as this proposed API is used, it is somehow secure.

I would more generally expect most secrets like API tokens / keys to be stored in some hashed form, which outputs bytes. So you'd hash / run through some KDF the input token and compare the hashes (bytes).

**Comment by dzsibi** [comment]
> You can use [`MemoryMarshal.AsBytes`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.asbytes) to convert your span of characters to a span of bytes and then call `FixedTimeEquals`.

That seems to be a very reasonable workaround. The whole suggestion was more a matter of convenience than one born of necessity. 

>Introducing overloads for more types other than bytes would open the argument for making FixedTimeEquals generic, something IMHO not needed because cryptography mainly deals with bytes.

I somewhat agree with the sentiment, and as neat as a generic constant-time comparer for primitive / bytes-marshallable types would look, I don't think it would have all that many real-world scenarios where it is useful.

>One thing that would concern me about this API would be that it implies it is reasonable to compare text data securely and as long as this proposed API is used, it is somehow secure.

That would definitely be the wrong message. Going through the legitimate use cases of the proposed function (where one would encounter strings), I realize now that one can almost always implement them in a way that ends up comparing bytes:

- When hashes are stored as strings, you have a choice of converting the hash of the input to a string or converting the stored hash to bytes before comparison. The same logic can be applied when validating MACs and other shared key based stuff - you can decode the input instead of encoding the output before comparison. The whole thing is not an issue for public key based stuff, since you would need to decode the signature anyways. That said, there might be situations when doing it the other way around might be more convenient, depending on how components not under the developer's control behave and return results.
- For 2FA codes and for phone number / e-mail validation, you can usually use integers, where constant time comparisons come free (especially for modern TOTP codes that already have integer outputs, and which are a way better solution than persisting a randomly generated value). You also need some sort of rate limit / quota on any such endpoints, which would usually prevent people from taking advantage of timing attacks anyways - and if such a limit is not present, simple brute forcing might yield better results with short codes.

In the end, I agree that having a somewhat opinionated API here might be beneficial and might steer users towards better practices - and I applaud the consideration. Although I doubt that the overlap between "people storing cleartext passwords in the database" and "people looking for constant-time string comparison algorithms" is significant - of course one could argue that it is better to use cleartext passwords / API keys with constant-time string comparison algorithms than without.

The comparisons in my original use case serve a different purpose, aren't even in the context of a web application, and due to architectural constraints the original plaintext cannot be thrown away and replaced with a hash - so while hash based comparisons would work, they are completely unnecessary, since the plaintext is always in memory. When I ran into the FixedTimeEquals function, I immediately thought how neat would a char based version would be, and that others could surely use it as well - I now realize that others really shouldn't in most cases.

Based on this, I would like to withdraw the proposal. Thanks for the feedback, and I appreciate the quick response.
