### ISSUE TITLE
DateTimeOffset incorrect values on Mobile Browser

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#55183]
I have ran into issue while testing with Real device (iPhone 12 pro Max) on live.browserstack.com as well as on one of the older iphone device that I have.

Web App
built using .NET 6 Preview
Deployed on Azure Web App

1) Normal Browser Testing on google chrome
     Issue 1) DateTimeOffset discrepancy
                DateTimeOffset is displaying -5
                TimezoneInfo.Local is displaying offset as -6
          
![DeskTop DateTimeOffset  (2)](https://user-images.githubusercontent.com/3267605/124370783-89a14f80-dc40-11eb-9984-a7f2cba27898.png)

2) testing done on **live.browserstack.com** using iPhone 12 Pro Max (using Safari) image, Device GPS Location is Atlanta, US
   Issue 1)
              DateTimeOffset value is not a correct DateTimeOffset. when submitting to Controller that accepts DateTimeOffset as parameter, controller fails with invalid dateTimeOffset value error
                
![iPhone DateTimeOffset Issue](https://user-images.githubusercontent.com/3267605/124370740-59f24780-dc40-11eb-89b2-90f1cd87f2cd.png)

**Comment by kg** [comment]
>     1. testing done on **live.browserstack.com** using iPhone 12 Pro Max (using Safari) image, Device GPS Location is Atlanta, US

Can you confirm what time zone the test device is set to? The GPS location has no direct impact on time zone data, and wasm cannot read GPS

**Comment by Clockwork-Muse** [comment]
> wasm cannot read GPS

It can call the browser geolocation API, but presumably that isn't the driving factor (As compared to, say, the browser setting a culture with the relevant zone).

**Comment by lewing** [comment]
@nssidhu the runtime reads the timezone from Intl.DateTimeFormat().resolvedOptions().timeZone what is that set to in your test case?
