### ISSUE TITLE
System.Security.Cryptography.Xml.Utils.GetAnyPublicKey returns only RSA or null?

### ISSUE THREAD

**Issue by alexaka1** [dotnet/runtime#55194]
This is the line in question:
https://github.com/dotnet/runtime/blob/7e43f8c2b23fd29b6176edd3b7f4631e51764702/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/Utils.cs#L753
But what about DSA or ECDsa keys? Shouldn't it check for them when `GetRSAPublicKey()` returns null?
How about `return (AsymmetricAlgorithm) (certificate.GetRSAPublicKey() ?? certificate.GetDSAPublicKey() ?? certificate.GetECDsaPublicKey()); `?

**Comment by bartonjs** [comment]
Do you have a specifically impacted scenario, or is this just a code inspection question?

My recollection is that SignedXml doesn't support ECDSA, so having GetECDsaPublicKey in there doesn't make sense.  And GetDSAPublicKey isn't part of .NET Standard 2.0, so we can't call it without splitting the library.  Given that there's not a lot usage of DSA we thought it wasn't worth splitting for it.

**Comment by alexaka1** [comment]
@bartonjs I am trying to validate XAdES signatures in XML files. I already use SignedXML for signing such documents with ECDSA keys. The `SigningKey` property has no trouble accepting an `ECDsa` object. The only extra thing I had to do is register a [`System.Security.Cryptography.SignatureDescription`](https://github.com/dotnet/runtime/issues/36103#issuecomment-631039599).
Also I just need to put eg.: `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512` into the `SignedInfo.SignatureMethod` and it works like a charm.

The problem comes when I try to check the signature of an XML signed with something else than an RSA key. I make a new SignedXml, load the signature, and it fails (returns false) because the key returned is null. (I debugged it with Rider and the above referenced code was where it starts to fail, because it returns null. My use case doesn't need DSA keys, but my country will start to require ECC based keys for digital signatures starting with Q3 2021, and we're going ahead implementing it sooner rather than later.

What would you suggest I try to do? I could just rip the entire source code of the classes required to reach that particular line, and re-implement them with the needed changes in our app, but I'd rather avoid re-inventing the wheel.

ps.: To be honest I didn't research what platforms support what functions of the Cryptography library, my use case is Windows x64, though I believe we compile into portable runtime.

**Comment by bartonjs** [comment]
It looks like:

* NET Framework's version does try all three
* GetECDsaPublicKey is part of .NET Standard 2.0, so no problems adding that one
* We recently split the compilation of this assembly as part of unifying how we build our NuGet packages, so we can add the DSA call in the .NET (nee Core) specific line.

So adding those calls is a reasonable compat thing to do.

**Comment by vcsjones** [comment]
@bartonjs I can pick this one up for 6.0.
