### ISSUE TITLE
[HTTP/3] Certificate name validation different than HTTP/1.1?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55193]
I have a Kestrel server configured to serve HTTP/1.1 and HTTP/3 on the same port with the same certificate. The certificate is the ASP.NET Core development certificate.

`HttpClient` throws this error when calling with HTTP/1.1:
```
    System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
    ---- System.Security.Authentication.AuthenticationException : The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
```
I need to setup a handler with `ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator` to successfully call it.

Meanwhile, `HttpClient` calling HTTP/3 doesn't need the validation callback. It happily accepts the dev certificate as trusted.

Should HTTP/1.1 and HTTP/2 have different certificate validation behavior than HTTP/3?

**Comment by wfurt** [comment]
I assume this is on Windows? Can you please post your dev certificate? I would not expect differences but this would help with investigation.

**Comment by JamesNK** [comment]
Yes, this is Windows.

Password is "quic"
[devcert.zip](https://github.com/dotnet/runtime/files/6768766/devcert.zip)

**Comment by wfurt** [comment]
Is the certificate trusted @JamesNK ? I used code from #55192 without the validation callback and it works fine for me:
```
C:\Users\test\source\repos\h3> C:\Users\test\source\repos\h3\bin\Debug\net6.0\win-x64\publish\h3
Hello World! HTTP/3
```
Now the mapping `127.0.0.1` <-> `localhost` should _not_ work IMHO unless the address is in `AlternativeSubjectName`.

**Comment by JamesNK** [comment]
I think the cert is trusted.

The issue isn't that HttpClient successfully makes an HTTP/3 call. The issue is that is different behavior from HTTP/1.1 and HTTP/2 which fail.

**Comment by wfurt** [comment]
I understand but I was not able to reproduce it. I assume it works if you use the `localhost`? Perhaps you can create simple repro with both client & server and cert from file?

**Comment by JamesNK** [comment]
Repo is in https://github.com/dotnet/aspnetcore/pull/34104

Test: `Listen_Http3AndSocketsCoexistOnSameEndpoint_ClientSuccess`. The `CallHttp3AndHttp1EndpointsAsync` method specifically. HTTP/3 call works without a callback, while HTTP/1.1 call requires it.

**Comment by wfurt** [comment]
I get it now. The complain is that QICK/H3 work but it should not. I know what the problem is.
