### ISSUE TITLE
.NET 5 Unicode lowercase regression with ª (code point 00AA)

### ISSUE THREAD

**Issue by leppie** [dotnet/runtime#55204]
This character is considered lowercase in all .NET versions, but regressed in .NET 5.

Repro
```
var text = "ª";
Console.WriteLine(text);
Console.WriteLine(char.IsLower(text, 0)); // return true for all FX except .NET 5 (tested on Windows/Linux)
Console.WriteLine(char.IsUpper(text, 0)); // all good still
```

From https://www.unicode.org/Public/13.0.0/ucd/PropList.txt 
```
00AA          ; Other_Lowercase # Lo       FEMININE ORDINAL INDICATOR
```

I haven't checked any other characters, but this specific one caused a test failure for me in IronScheme. See https://github.com/IronScheme/IronScheme/issues/78

**Comment by MichalPetryka** [comment]
Does this happen on Windows when you force .Net 5 to use NLS [as explained here](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#nls)? If yes then this is caused by ICU and probably should be filed [here](https://github.com/unicode-org/icu).

**Comment by leppie** [comment]
> Does this happen on Windows when you force .Net 5 to use NLS [as explained here](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#nls)? If yes then this is caused by ICU and probably should be filed [here](https://github.com/unicode-org/icu).

Seems the same either way
```
C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>set | find "DOTNET_SYSTEM_GLOBALIZATION_USENLS"

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>dotnet run
ª
False
False

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>set DOTNET_SYSTEM_GLOBALIZATION_USENLS=true

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>set | find "DOTNET_SYSTEM_GLOBALIZATION_USENLS"
DOTNET_SYSTEM_GLOBALIZATION_USENLS=true

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>dotnet run
ª
False
False

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>set DOTNET_SYSTEM_GLOBALIZATION_USENLS=1

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>set | find "DOTNET_SYSTEM_GLOBALIZATION_USENLS"
DOTNET_SYSTEM_GLOBALIZATION_USENLS=1

C:\Users\leppie\source\repos\ConsoleApp47\ConsoleApp47>dotnet run
ª
False
False
```

**Comment by ufcpp** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.char.islower?view=net-5.0

> Valid lowercase letters are members of the following category in UnicodeCategory: LowercaseLetter.

**Comment by svick** [comment]
@ufcpp On Windows with default settings, when I run `char.GetUnicodeCategory('ª')` on .Net Core 3.1, I get `LowercaseLetter`, but on .Net 5.0, I get `OtherLetter` (which is consistent with `Lo` from UCD). Are you saying that the previous behavior was a bug and the new behavior is correct?

**Comment by leppie** [comment]
> https://docs.microsoft.com/en-us/dotnet/api/system.char.islower?view=net-5.0
> 
> > Valid lowercase letters are members of the following category in UnicodeCategory: LowercaseLetter.

Prior to .NET 5 any char with a `Lowercase` property was considered lowercase. Which is consistent with interpretations from other languages, eg Java, R6RS Scheme.

Also the UnicodeCategory is `OtherLetter`. `char.IsLetter` return `true`. (as returned by .NET 5)

**Comment by leppie** [comment]
> @ufcpp On Windows with default settings, when I run `char.GetUnicodeCategory('ª')` on .Net Core 3.1, I get `LowercaseLetter`, but on .Net 5.0, I get `OtherLetter` (which is consistent with `Lo` from UCD). Are you saying that the previous behavior was a bug and the new behavior is correct?

Good spot! I agree it should be `OtherLetter`, but I also feel it should be considered lowercase.

**Comment by tarekgh** [comment]
> Good spot! I agree it should be OtherLetter, but I also feel it should be considered lowercase.

We depend on how Unicode define the character property. Unicode defined it as `Lo` which is Other-Letter and not lower-case letter `Ll`. Also, if you look at the casing data, you'll find `ª` has no upper-case mapping. 

`00AA;FEMININE ORDINAL INDICATOR;Lo;0;L;<super> 0061;;;;N;;;;;`

If you disagree with that, feel free to raise you issue to Unicode.org to fix that. From .NET side, we need to stick with what Unicode standard provide.

**Comment by svick** [comment]
@tarekgh But [U+00AA *does* have the Lowercase property](https://www.unicode.org/Public/13.0.0/ucd/DerivedCoreProperties.txt):

```
# Derived Property: Lowercase
#  Generated from: Ll + Other_Lowercase

0061..007A    ; Lowercase # L&  [26] LATIN SMALL LETTER A..LATIN SMALL LETTER Z
00AA          ; Lowercase # Lo       FEMININE ORDINAL INDICATOR
...
```

Isn't that what `char.IsLower` should use, instead of being limited to just `Ll`?

**Comment by leppie** [comment]
> We depend on how Unicode define the character property. Unicode defined it as `Lo` which is Other-Letter and not lower-case letter `Ll`. Also, if you look at the casing data, you'll find `ª` has no upper-case mapping.

Here is perhaps a better example.  Which behaves as follows for all FX.

Roman numerals. Lets take one `Ⅰ`. (2160)

`char.ToLower('Ⅰ')` => `ⅰ`  // correct (2170)
`char.ToUpper('ⅰ')` => `Ⅰ`  // correct (2160)

`char.IsLower` => `false` for both
`char.IsUpper` => `false` for both

`TextInfo.ToTitleCase("ⅰ")` => `ⅰ` // should be Ⅰ

**Comment by leppie** [comment]
> `TextInfo.ToTitleCase("ⅰ")` => `ⅰ` // should be Ⅰ

```
2160;ROMAN NUMERAL ONE;Nl;0;L;<compat> 0049;;;1;N;;;;2170;
2170;SMALL ROMAN NUMERAL ONE;Nl;0;L;<compat> 0069;;;1;N;;;2160;;2160
```
`Simple_Titlecase_Mapping` is the last value.

> Note: If this field is null, then the Simple_Titlecase_Mapping is the same as the Simple_Uppercase_Mapping for this character.

http://www.unicode.org/reports/tr44/#Simple_Titlecase_Mapping

Seems much of the Unicode spec is simply ignored or not implemented.

**Comment by GrabYourPitchforks** [comment]
Correct - .NET has considerable gaps in how it handles Unicode properties. For example, case comparison is done via normalize-to-uppercase instead of normalize-to-casefold. (I want to change this, but it would be a _substantial_ breaking change, and that's a very hard pill to swallow.) For better or worse, the `char.IsLower` method [is documented](https://docs.microsoft.com/dotnet/api/system.char.islower) such that the code sample below always passes.

```cs
char originalChar = GetChar();
bool isLowerA = char.IsLower(originalChar);
bool isLowerB = char.GetUnicodeCategory(originalChar) == UnicodeCategory.LowercaseLetter;
Assert.Equal(isLowerA, isLowerB);
```

Is it wrong? Yes. As @leppie correctly points out, we should instead be using the derived property map. The .NET Framework Unicode APIs were based on a much earlier version of the Unicode standard (I think 4.1.0?), and [in that standard](https://www.unicode.org/Public/4.1.0/ucd/UnicodeData.txt) the code point `U+00AA` did indeed have category _LowercaseLetter_. .NET 5's data tables are populated from Unicode 13.0.0 data files, which changed the category of `U+00AA`. This means that `char.IsLower` returns a different answer across framework versions, but it's still consistent with the result returned by `char.GetUnicodeCategory`, which means it's still fulfilling its documented contract and we would not consider this a runtime bug.

All of that said, I would love love love to change these APIs to make them more standards-compliant, but that's a much deeper conversation since it changes fundamental behaviors of many of these APIs, and we'd need to weigh it against the potential for applications to break. (See https://github.com/dotnet/runtime/pull/27540, https://github.com/dotnet/runtime/issues/32247 for some earlier discussion on the perils involved here.) Such a discussion really belongs as its own broader issue rather than as something confined to `char.IsLower`.

**Comment by ufcpp** [comment]
@svick 
I'm not sure whether docs or runtime is wrong. Maybe .NET Core 3.1 or earlier uses "Derived Property: Lowercase", but docs says "following in UnicodeCategory".

**Comment by ufcpp** [comment]
FYI

Go's IsLower returns false:

```go
package main

import "fmt"
import "unicode"

func main() {
	fmt.Println(unicode.IsLower(rune('ª'))) // false
}
```

Rust's is_lowercase returns true:

```rs
fn main() {
    println!("{}", 'ª'.is_lowercase()); // true
}
```

[The Rust's api document](https://doc.rust-lang.org/std/primitive.char.html#method.is_lowercase) explicitly refers to DerivedCoreProperties, while Go does not.

**Comment by tarekgh** [comment]
@ufcpp

> I'm not sure whether docs or runtime is wrong. Maybe .NET Core 3.1 or earlier uses "Derived Property: Lowercase", but docs says "following in UnicodeCategory".

.NET Core 3.x didn't use Derived Property but it had the `ª` classified as `Ll` instead `Lo`. run the following code on 3.1 and 5.0 and you'll see the difference.

```C#
    Console.WriteLine($"{char.GetUnicodeCategory('\u00aa')}");
```
