### ISSUE TITLE
Getting issue while publishing blazor client with AOTCompilation

### ISSUE THREAD

**Issue by vinayiscool** [dotnet/runtime#55205]
![image](https://user-images.githubusercontent.com/78460365/124601030-00c72580-de85-11eb-9433-9671ef8aa38c.png)

Steps : 
1) As per https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-4/ blog installed AOT with below command.
  dotnet workload install microsoft-net-sdk-blazorwebassembly-aot
2) Sets RunAOTCompilation proerpty to project path
<RunAOTCompilation>true</RunAOTCompilation>
3) dotnet publish -c Release
while executing 3rd step getting attached image error.

blazor webassembly .NET 6 Preview 4 version with AOT compilation

@pranavkm

**Comment by lewing** [comment]
This has been fixed in later previews, @radical do you know when the fix went in?
