### ISSUE TITLE
Enumerable.Join method adds additional items when called for large collections

### ISSUE THREAD

**Issue by Vasar007** [dotnet/runtime#55219]
### Description

I recently discovered that Enumerable.Join method can have quite a strange behavior sometimes. In my tests I use the following code (I tried to simplify it):

```csharp
[Fact]
public void ForCollectionWithRandomSize_NoIssue() // This test works fine.
{
    const int count = 10_000;
    IReadOnlyList<int> collectionWithSomeItems = CreateList(count);

    ForCollectionWithRandomSize(collectionWithSomeItems);
}

[Fact]
public void ForCollectionWithRandomSize_Issue() // This test failes.
{
    const int countToReproduceTheIssue = 100_000;
    IReadOnlyList<int> collectionWithSomeItems = CreateList(countToReproduceTheIssue);

    ForCollectionWithRandomSize(collectionWithSomeItems);
}

private static IReadOnlyList<int> CreateList(int count)
{
    var random = new Random();
    var values = Enumerable
        .Range(0, count)
        .Select(_ => random.Next());

    var result = new List<int>(capacity: count);
    result.AddRange(values);
    return result.AsReadOnly();
}

private static void ForCollectionWithRandomSize<T>(IReadOnlyList<T> collectionWithSomeItems)
{
    // Arrange.
    // NOTE: I simplified following lines of code.
    IReadOnlyList<T> randomOrder = collectionWithSomeItems;
    IReadOnlyList<T> expectedCollection = randomOrder;

    // Act.
    // Join method keeps order of the first collection, e.g. "randomOrder" in our case.
    var actualCollection = randomOrder.Join(
        collectionWithSomeItems,
        x => x,
        x => x,
        (sourceItem, orderItem) => sourceItem,
        EqualityComparer<T>.Default
    ).ToList();

    // Assert.
    Assert.Equal(expectedCollection, actualCollection);
}
```

In the tests I create rather large collection and call `Enumerable.Join` (there are more complicated logic in my code but I erase it to make it clear). And it looks like `Enumerable.Join` method adds additional items when called for the large collecitons. In my case:

> Not too large collection:
> before join — 10_000
> after join  — 10_000

![image](https://user-images.githubusercontent.com/21951872/124646206-0597d380-de9d-11eb-803a-8b38d420944e.png)

> Large collection:
> before join — 100_000
> after join  — 100_004

![image](https://user-images.githubusercontent.com/21951872/124646132-f0bb4000-de9c-11eb-9408-136c233141b7.png)

So, is this behavior by design? Or what should I do to avoid such issue with `Enumerable.Join` method?

### Configuration

* .NET version: .NET Framework 4.7.2, .NET Core 3.1, .NET 5 (using these 3 targets in my tests)
* OS: Windows 10 20H2
* Architecture: x64

### Regression?

Issue reproduced on both targets: .NET Core and .NET Framework.

### Other information

I think that this aspect of `Enumerable.Join` depends on EqualityComparer because in my other tests with custom structs all works fine without any issues (with the same logic I presented above).

**Comment by svick** [comment]
Yes, this behavior is by design *for collections that contain duplicates*, which your random list with 100 000 items usually does.

Each integer from the first collection matches with each intenger in the second collection with the same value. And that means each duplicate matches more than once, resulting in those additional items.

To see this, you can use the collection of `new[] { 1, 2, 1 }`, which will produce: 1, 1, 2, 1, 1 (5 items instead of just 3).

I don't know what you should do instead, because I don't know what your original code attempted to do.

**Comment by Vasar007** [comment]
Okay, thanks @svick for the answer! I decided to reduce collection size for the tests and filter duplicates.
