### ISSUE TITLE
HTTP/3: Improve user experience when TLS 1.3 is not enabled on Windows

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55237]
TLS 1.3 can be disabled via a registry key. If HTTP/3 is used on a machine that has a modern version of Windows that supports TLS 1.3, but 1.3 has been disabled, then HTTP/3 fails.

The error message isn't immediately helpful:

```
Message:
System.Net.Quic.QuicException : ConfigurationLoadCredential failed. Error Code: 0x80090331

Stack Trace:
Quic.dll:token 0x6000192+0x11
Quic.dll:token 0x60001dc+0x314
Quic.dll:token 0x60001da+0x0
Quic.dll:token 0x60000ec+0xb
Quic.dll:token 0x6000115+0x0
Quic.dll:token 0x6000064+0x6
```

Options:
1. Add check for 1.3 to `QuicImplementationProviders.MsQuic.IsSupported`
2. Throw a friendly error message when attempting to do QUIC.

How to disable:
https://social.technet.microsoft.com/Forums/windows/en-US/bcc6be0b-0385-4aff-82ae-b6e973fe398d/0x80090331-the-client-and-server-cannot-communicate-because-they-do-not-possess-a-common-algorithm

**Comment by ManickaP** [comment]
Triage: Seems reasonable, we should do it.

**Comment by wfurt** [comment]
Seems like this this is platform OS error `SEC_E_ALGORITHM_MISMATCH`
That looks windows specific. So as ability to disable protocol version. 
On Linux one can possibly disable all TLS1.3 algorithms. 

I'm wondering if we can add new status code and handle the differences in msquic pal @nibanks?

**Comment by karelz** [comment]
Triage: This is rare situation that someone disables explicitly TLS 1.3.
As soon as we have decent message on OS which does NOT support TLS 1.3 on Windows, we can deal with it in .NET 7.
Moving to 7.0

Should be fairly straightforward to do - up-for-grabs.
