### ISSUE TITLE
Provide a API to get an `IList<T>` from a `Collection<T>`

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#55234]
This could be implemented by making the `IList<T> Items` property public, or providing a new API in `CollectionsMarshal `.

**Comment by xtqqczze** [comment]
If such an API is not implemented, I guess this works:

```csharp
public class CollectionEx<T> : Collection<T>
{
    public new IList<T> Items => base.Items;
}

IList<T> ilist = ((CollectionEx<T>)collection).Items;
```

**Comment by GrabYourPitchforks** [comment]
`Collection<T>` already implements `IList<T>`.

```cs
System.Collections.Generic.IList<int> list = new System.Collections.ObjectModel.Collection<int>();
list.Add(42);
Console.WriteLine(list[0]); // prints 42
```

**Comment by huoyaoyuan** [comment]
He should be meaning the `IList<T>` passed in constructor, which is invoked by `Collection<T>`, and doesn't invoke `Collection<T>.SetItem` etc.

**Comment by GrabYourPitchforks** [comment]
Sorry - I still don't quite understand. Can you provide a code sample showing what you're trying to do?

**Comment by eiriktsarpalis** [comment]
I'm going to close this for now since it's been inactive for a while, but feel free to reopen when you can provide us with a code sample.
