### ISSUE TITLE
huge vm usage in docker when program crash can't dump.

### ISSUE THREAD

**Issue by raoyang** [dotnet/runtime#55254]
I use dotnet core 3.1 in docker, memory limit 8G.  config environment COMPlus_DbgEnableMiniDump=1 to collect dump file when program crash.
the program uses less than 100MB of memory, but virtual memory usage is always near 60GB. After about an hour later, the docker container uses memory approaching limit and program been killed by container.
I have noticed the same question in issue:https://github.com/dotnet/runtime/issues/7740

**Comment by noahfalk** [comment]
@mikem8361

**Comment by mikem8361** [comment]
In 3.1, issue #7740 has been fixed.  Full dumps no longer incorrectly add all the uncommitted virtual memory. Did you try a heap dump?

**Comment by raoyang** [comment]
> In 3.1, issue #7740 has been fixed. Full dumps no longer incorrectly add all the uncommitted virtual memory. Did you try a heap dump?

Heap or Mini dump cannot help.

**Comment by mikem8361** [comment]
Sorry I haven't respond sooner.  Are you still having problems with createdump attempting to create GB dumps? Have you tried 6.0 yet?  When you said "Heap or Mini dump cannot help." do you mean that setting COMPlus_DbgMiniDumpType=2 to still repros the problem?
