### ISSUE TITLE
Can not compile -- daccess.cpp

### ISSUE THREAD

**Issue by iCodeSometime** [dotnet/runtime#5525]
When running build clean, it runs up until it gets to daccess.cpp, and it crashes saying "The system cannot find the path specified."
[CoreCLR_Windows_NT__x64__Debug_err.txt](https://github.com/dotnet/coreclr/files/210134/CoreCLR_Windows_NT__x64__Debug_err.txt)
[CoreCLR_Windows_NT__x64__Debug_log.txt](https://github.com/dotnet/coreclr/files/210135/CoreCLR_Windows_NT__x64__Debug_log.txt)

**Comment by jkoritzinsky** [comment]
Closing as this issue very old is not reproducible in master.
