### ISSUE TITLE
Facing System platform not support for Excel Interop in mac .Net core

### ISSUE THREAD

**Issue by ajithvallabai** [dotnet/runtime#55269]
Hi ,
I created a  .Net core console project in Mac machine.
I tried to open a excel sheet(perform basic automation in excel) with Microsoft.Office.Interop.Excel; from COM object but i am facing below error

I am getting same error  while opening  Powerpoint, Word and for Outlook 
![image](https://user-images.githubusercontent.com/8075112/124772352-93d18f80-df59-11eb-93dc-e17b00f871ef.png)

In accordance with this answer https://stackoverflow.com/questions/41172984/office-excel-com-interop-on-mac-osx-using-net-core it was not supported in 2016. In 2021 is there any support  or any alternative workaround in Mac

**Comment by huoyaoyuan** [comment]
Nothing has changed for COM. It's still Windows only. It's hard to port to other OS because it relies on the OS to do much of work.

**Comment by ajithvallabai** [comment]
@huoyaoyuan  do you know any 3d party library for office automations or excel automations without licensing/purchase in Mac  ?

**Comment by huoyaoyuan** [comment]
I don't know. Anyway, there is nothing to do with .NET now.

**Comment by ajithvallabai** [comment]
okay thanks i will close the issue
