### ISSUE TITLE
 System.Net.NameResolution.Functional.Tests failing on SLES

### ISSUE THREAD

**Issue by mateoatr** [dotnet/runtime#55271]
[runtime 20210706.106](https://dev.azure.com/dnceng/public/_build/results?buildId=1223228&view=results)

System.Net.NameResolution.Functional.Tests

First batch (disabled in PR #55446 on 7/10):
  - GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName
  - GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName
  - GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(hostName: "")
  - GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok(hostName: "")

More tests disabled in PR #55543 on 7/13, e.g.:
  - Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses
  - Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses

https://dev.azure.com/dnceng/public/_build/results?buildId=1223228&view=ms.vss-test-web.build-test-results-tab&runId=36449720&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=148177

Tests throwing `System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known`.

**Comment by hoyosjs** [comment]
@karelz @ManickaP This is blocking. I've opened #55436 as a tracking issue. It's hit 14 rolling builds. I'll be disabling this set of tests.

**Comment by ManickaP** [comment]
This looks like an infra issue, I've filed a bug in core-eng last week: https://github.com/dotnet/core-eng/issues/13675

**Comment by karelz** [comment]
@hoyosjs please do not remove untriaged in future -- we need to go through the issues and decide on milestone.
