### ISSUE TITLE
DataContractJsonSerializer can't serialize contract with ExtensionDataObject

### ISSUE THREAD

**Issue by Umqra** [dotnet/runtime#55270]
### Description

If you use `DataContractJsonSerializer` with `ExtensionDataObject` and try to serialize data when extension data contains a nested complex object with the single property then the serializer throws an exception because the deserializer incorrectly decides that property of a nested object has the type of array but this assumption breaks serializer invariants.

Consider the following data contract:
```C#
[DataContract]
public class ContractGeneric : IExtensibleDataObject
{
    public ExtensionDataObject ExtensionData { get; set; }
}
```

If you try to deserialize JSON `{"item":{"id":0}}` to the type `ContractGeneric ` and after that immediately serialize this data back to JSON then you get the exception:
```
Unhandled exception. System.Runtime.Serialization.SerializationException: 
There was an error serializing the object of type DataContractJsonSerializeExample.ContractGeneric. 
Encountered unexpected element local name 'id' for item in collection. 'item' is the only valid local name for elements in a collection.
```

You can find a repository with the full example here: https://github.com/Umqra/DataContractJsonSerializeExample
Also, there is a docker image with a console application that reproduces the bug: https://hub.docker.com/r/sivukhin/data-contract-json-serializer-example

### Configuration

Runtime: .NET 5.0 but problem also reproduced in netcoreapp2.0
Operation System: Windows
Architecture: x64

### Problem

Probably the cause of the problem lies in the automatic type detection for `ExtensionDataObject` content, more precisely inconsistency in behaviour of deserializer for JSON may happen at the following line: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializerReadContext.cs#L969

Here `XmlObjectSerializerReadContext` tries to determine type of element and in case when object contains only single property the algorithm decide that this is an array (which is wrong!).

**Comment by Umqra** [comment]
Should I mention someone to draw attention to the issue?

**Comment by StephenMolloy** [comment]
Some more information. I can reproduce this exception on .Net 6, but not on .Net 4.8.
