### ISSUE TITLE
[HTTP/3] QPACK: Need better exception message for non-ASCII values

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55310]
See QPackEncoder.EncodeValueStringPart, here: 
https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/QPackEncoder.cs#L320

The current error message is "ASCII header value." That's not an actual sentence.

**Comment by karelz** [comment]
Triage: Simple to do, but not critical for 6.0.

**Comment by pedrobsaila** [comment]
Hi I submitted a PR for this issue #55886
