### ISSUE TITLE
Stopwatch Start/Restart/Stop incorrect ElapsedTicks value (.net 5)

### ISSUE THREAD

**Issue by vadmyst** [dotnet/runtime#55311]
I'm trying to measure execution time of a method that performs wait with SpinWait.SpinOnce() and encountered  some counterintuitive results. I'm using .net 5, both on Windows and Linux.

My sample code below contains two Stopwatch class instances: one inside a method with SpinWait to measure how much SpinWait.SpinOnce() spinning is left and the other to measure total time elapsed of the wait.

Code below produces following results for 10 iterations. 
```
Outer 827 µs, inner: 222 µs
Outer 12 µs, inner: 56 µs
Outer 11 µs, inner: 61 µs
Outer 7 µs, inner: 54 µs
Outer 7 µs, inner: 54 µs
Outer 7 µs, inner: 52 µs
Outer 13 µs, inner: 63 µs
Outer 9 µs, inner: 58 µs
Outer 8 µs, inner: 58 µs
Outer 7 µs, inner: 55 µs
```
We can ignore first one. It looks like the outer Stopwatch measures less elapsed time than inner Stopwatch. 
How can this be? When I replace SpinWait with Thread.Sleep(1) outer and inner values become as expected: outer is larger than inner. Additionally, if I track elapsed ticks myself for the outer Stopwatch (not using Restart/Stop but just single Start at the beginning and tracking ElapsedTicks) I receive proper results and Outer time is higher than inner.

It looks like Stopwatch.Start/Restart/Stop is doing something that might influence elapsed ticks continuity.
And here's the code how to reproduce the issue:
```
private static ulong NanoSecPerTick = (1000UL * 1000UL * 1000UL) / (ulong)Stopwatch.Frequency;

private static ulong SpinWait(ulong microsToWait)
{
    System.Threading.SpinWait sp = new System.Threading.SpinWait();
    Stopwatch sw = Stopwatch.StartNew();

    ulong microsElapsed = 0;
    do
    {
        sp.SpinOnce();
        microsElapsed += ((ulong)sw.ElapsedTicks * NanoSecPerTick) / 1000;
    } while (microsElapsed <= microsToWait);

    return microsElapsed;
}

Stopwatch swOuter = new Stopwatch();
for (int i = 0; i < 10; i++)
{
    swOuter.Restart();
    ulong microsWaited = SpinWait(50);
    swOuter.Stop();
    
    ulong outerWait = ((ulong)swOuter.ElapsedTicks * NanoSecPerTick) / 1000;                
    Console.WriteLine($"Outer {outerWait} μs, inner: {microsWaited} μs");
}
```

**Comment by jkotas** [comment]
> `microsElapsed += ((ulong)sw.ElapsedTicks * NanoSecPerTick) / 1000;`

This line has a bug. `sw.ElapsedTicks` returns cumulative time since the Stopwatch was started, but you are using it as if it was time since ElapsedTicks  was called last time.

**Comment by vadmyst** [comment]
Yes, issue was with time accumulation. Thanks for catching that.
After changing to 
```
microsElapsed = ((ulong)sw.ElapsedTicks * NanoSecPerTick) / 1000;
```

I got proper output:
```
Outer 357 µs, inner: 177 µs
Outer 50 µs, inner: 50 µs
Outer 50 µs, inner: 50 µs
Outer 52 µs, inner: 52 µs
Outer 50 µs, inner: 50 µs
Outer 51 µs, inner: 50 µs
Outer 50 µs, inner: 50 µs
Outer 50 µs, inner: 50 µs
Outer 50 µs, inner: 50 µs
Outer 50 µs, inner: 50 µs
```
