### ISSUE TITLE
How to open a WPF window in a library project(dll)?

### ISSUE THREAD

**Issue by xiaoxstz** [dotnet/runtime#55329]
**My target:**
create a C# library to open a WPF Window, and then package it as a dll file. In the end, the dll can be called by other platform(for example: python)

If it's a Winform window, it's easy. Because in `Window Forms Control library`, it's easy to open a WinForm window. 

So, how to open a WinForm window in a library project?

**Comment by huoyaoyuan** [comment]
> the dll can be called by other platform

How will it be called?

If it's called through `dotnet.exe`, then it is actually an executable, not a library.

**Comment by xiaoxstz** [comment]
Use a python package named `pythonnet`.

For example

# The C# part
```C#
namespace ImgWindowFrm
{
    public class ImgWindow
    {
        public int Add(int a,int b)
        {
            return a + b;
        }
    }
}
```

# The python part
```python
import clr
clr.AddReference("ImgWindowFrm")  # dll name
from ImgWindowFrm import *        # from namespace import *

if __name__ == '__main__':
    instance = ImgWindow()       # class name
    #instance.ShowForm()
    print('2+3=', instance.Add(2, 3))
```

**Comment by huoyaoyuan** [comment]
There shouldn't be anything special for WPF. A regular WPF control library should be able to do so.

**Comment by jkoritzinsky** [comment]
@xiaoxstz do you still need assistance here?

**Comment by xiaoxstz** [comment]
Yes.
I still need assistance.

WinForm library can open a Winform Window by C# code. But how can we a WPF Window by C# code?

If you can give me a example for this, I can solve this issue by myself

**Comment by AaronRobinsonMSFT** [comment]
@xiaoxstz I am going to close this for now. Please do let us know if assistance is still needed. Thanks.
