### ISSUE TITLE
PGO: Optimize isinst with class probes

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#55325]
Example:
```csharp
void Test(object o)
{
    if (o is Program)
    {
        Console.WriteLine();
    }
}
```
Current codegen:
```asm
G_M25341_IG01:
       sub      rsp, 40
G_M25341_IG02:
       mov      rcx, 0xD1FFAB1E
       call     CORINFO_HELP_ISINSTANCEOFCLASS
       test     rax, rax
       je       SHORT G_M25341_IG04
G_M25341_IG03:
       add      rsp, 40
       jmp      System.Console:WriteLine()
G_M25341_IG04:
       add      rsp, 40
       ret      
; Total bytes of code: 38
```
As you can see - we give up on inlined checks and just call the `CORINFO_HELP_ISINSTANCEOFCLASS` helper.
Ideally we could emit a fast-path check from a class probe. So it could be:
```
if (o->pMT == classProbe || call CORINFO_HELP_ISINSTANCEOFCLASS)
```
I wonder if such an improvement could optimize e.g. this hot-path in JsonSerializer:
![image](https://user-images.githubusercontent.com/523221/124912927-30963a80-dff7-11eb-97b7-695798434954.png)

where the converter is mostly ObjectDefaultConverter for most benchmarks (in real world apps likehood can be smaller)

**Comment by EgorBo** [comment]
cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
For cases where the object is used after the test we may already have downstream class probes that would tell us the likely class. I wonder if we could leverage that somehow?

Ideally we'd probe each object's class just once instead of at each use. We're not set up to do that now as we don't understand how definitions and uses inter-relate.

**Comment by EgorBo** [comment]
> For cases where the object is used after the test we may already have downstream class probes that would tell us the likely class. I wonder if we could leverage that somehow?

Good idea, so we can avoid more class probes in tier0

**Comment by EgorBo** [comment]
Closed via 
https://github.com/dotnet/runtime/pull/65460
https://github.com/dotnet/runtime/pull/65922
https://github.com/dotnet/runtime/pull/69869
