### ISSUE TITLE
JIT: Methods with switches aren't inlineable

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#55336]
Example:
```csharp
public int Test1(char format) =>
    format switch
    {
        'A' => 1,
        'B' => 2,
        'C' => 3,
        'D' => 4,
        _ => 0,
    };

public int Test2() => Test1('B');
```
Codegen for `Test2`:
```asm
       mov      edx, 66
       jmp      ConsoleApp26.Program:Test1(ushort):int:this
; Total bytes of code: 10
```
Currently it's failed to inline into `Test2`:
```
INLINER: during 'fgInline' result 'failed this callee' reason 'has switch'
```
I guess it's tricky for the importer, but at least we could import it as a single JTRUE block when we pass a constant at the callsite (and that arg feeds that switch).

/cc @AndyAyersMS

**Comment by MichalPetryka** [comment]
This is also a case for a `switch` on a `sizeof(T)` in a generic method with an `unmanaged` constraint, those switches should be completely ignored by the inlined as the JIT always knows which path will be taken.

**Comment by AndyAyersMS** [comment]
See #10634 and https://github.com/dotnet/runtime/issues/10658#issuecomment-404367941 -- latter has a prototype of the changes needed to enable inlining of switches.

There is a cache of switch info kept in the jit (`m_switchDescMap`) that might need updating/invalidating too, I haven't looked.
