### ISSUE TITLE
[Mono][TE] Optimize thread related functions

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#55339]
The following performance data was collected against JsonPlatform benchmark on linux x64. The top 3 time consuming functions are

- mono_threads_state_poll_with_info (_actionable_)
- System.Threading.LowLevelLifoSemaphore/Counts:InterlockedCompareExchange -> System.Threading.Interlocked:CompareExchange (ulong&,ulong,ulong)
- mono_monitor_ensure_owned

Here is the perf results shown via speedscope
<img width="1562" alt="Screen Shot 2021-07-08 at 11 22 06 AM" src="https://user-images.githubusercontent.com/52458914/124952279-1b62e100-dfe2-11eb-93b2-265d6307bc3d.png">

To view the data locally in details, unzip and drop the following file in speedscope
[perf-data-dwarf-new.txt.zip](https://github.com/dotnet/runtime/files/6785787/perf-data-dwarf-new.txt.zip)

**Mono mode:** desktop JIT

cc: @BrzVlad @lambdageek @vargaz @marek-safar

**Comment by lambdageek** [comment]
Time spent in `mono_thread_state_poll_with_info` should correlate with time spent in GC pauses.

**Comment by vargaz** [comment]
CompareExchange is usually costly since its synchronization code. It could also indicate contention.

**Comment by SamMonoRT** [comment]
Moving to 7.0.0

**Comment by fanyang-mono** [comment]
Talked to @SamMonoRT offline. Will provide newer profile data next week.

**Comment by fanyang-mono** [comment]
There isn't resource for working on this. Plus, MonoVM Runtime Nuget Packages are deprecated starting .NET9 Preview7 (See https://github.com/dotnet/docs/issues/41366).
