### ISSUE TITLE
[Blazor WASM] CultureInfo.DisplayName not consistent

### ISSUE THREAD

**Issue by enricobenedos** [dotnet/runtime#55348]
### Describe the bug
`CultureInfo` `DisplayName` property does not return a consistent value in Blazor WASM projects. 

### To Reproduce
**_Example:_**
```c#
var enCulture = new CultureInfo("en-US");
Console.WriteLine(enCulture.DisplayName);
```
_Actual Value_
`en (US)`

_Expected Value_
`English (United States)`
(as described in https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.displayname?view=net-5.0)

### Exceptions (if any)

No exceptions.

### Further technical details
- .NET 5.0
- Include the output of `dotnet --info`
```console
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
```
Microsoft Visual Studio Professional 2019
Version 16.10.3
```

**Comment by svick** [comment]
Blazor WASM has its own cut-down version of culture data, and, as I understand it, [that excludes culture names](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#icu-on-webassembly). (Though that article does not explicitly mention `DisplayName` for some reason.) I think that explains the behavior you see.

**Comment by enricobenedos** [comment]
Hi @svick,
probably you are right. But I think that Blazor WASM as frontend framework cannot miss the `DisplayName` feature.
I understand that it is for performance purposes but at this point I think that it can be solved using an adjunctive dependency that include the right cultures names. So every developer can decide if include it on his projects.
