### ISSUE TITLE
Optimize Vector128<T> equality against Zero/AllBitsSet

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#55343]
### Description

Vector128<T> equality checks against `Vector128<T>.Zero` could be optimized to generate the same ASM (`vmovupd` + `vptest` instead of `vxorps` + `vpcmpeqb` + `vpmovmskb`  + `cmp` or `vxorps` + `vmovupd` + `vpcmpeqb` + `vpmovmskb`  + `cmp`)  as `Sse41.TestZ` does (when SSE 4.1 is supported) and against `Vector128<T>.AllBitsSet` to the ASM from `Sse41.TestC`.

```C#
    public static bool A(Vector128<byte> v)
    {
        return Sse41.TestZ(v, v);
    }

    public static bool B1(Vector128<byte> v)
    {
        return v.Equals(Vector128<byte>.Zero);
    }

    public static bool B2(Vector128<byte> v)
    {
        return Vector128<byte>.Zero.Equals(v);
    }
```

```C#
    public static bool A(Vector128<byte> v)
    {
        return Sse41.TestC(v, Vector128<byte>.AllBitsSet);
    }

    public static bool B1(Vector128<byte> v)
    {
        return v.Equals(Vector128<byte>.AllBitsSet);
    }

    public static bool B2(Vector128<byte> v)
    {
        return Vector128<byte>.AllBitsSet.Equals(v);
    }
```

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea.

### Data

[Sharplab for Zero](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFqVp3KzC4A3AFgAUGUq1GLdpx4Y+AobhoANABxJxEycQDMMpOWa5sAMxiUATOQAqMXBkkBvSeS+Vj1U8AgIABtyAEEACgA1GDAMaCpbLQAeYABPDBgAPnIANwBKT28PCW9SygB2cgBlXBgUWicXAC1wnLRcvL1SgF9JQq8jE3IA4PIAISoomLioBOS0jOz8/vJisu9iSpyaAFEARwZsINwp2PjElPSsmiaYKAhOld79Eo3fKn9AkLHbU5m5y6LDorNbrCrkaJnWYXBbXW73XYHI4nfJdbzPbpAA===)
[Sharplab for AllBitsSet](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFqVp3KzC4A3AFgAUGUq1GLdpx4Y+AobhoANABxJxEycQDMMpOWa5sAMxiUATOQAqMXBkkBvSeS+Vj1U8AgIABtyAEEqAAoANRgwDGgqWy0AHmAATwwYAD5yADcASk9vDwlvMsoAdnIAZVwYFFonFwBhCNy0chi4hKTUjOyaUKCggCFWDFxqmAx8vTKAXyKvJZ8TcgDgsNto2PioRJT0zJyClZLy71zsKDNyAF4auttNaDaOrr2DvuPB4bGJqYzOYXSqPeqNZwYABaEQYHQYsxWi30pW8RjWGxCI0iHx6h36J0KqK85xBxCquRoAFEAI4MbBBXA7br7XpHAZDUbjSbTRHE8jIlbovzrQJY7a41n4455IllUkXcmdXZ474cv7cwHUukMpkFYFeZHzIA=)

**Comment by EgorBo** [comment]
@MichalPetryka should be easy to fix in `Vector128.Equals` (C#), do you want to give it a try?

llvm-mca dump: https://www.diffchecker.com/iYXeqb1h
(movmsk vs xor+vptest) - but not sure it's like that on all CPUs

**Comment by EgorBo** [comment]
E.g. on Zen1 vptest is 4/2 (lat/rec.tp) while movmsk is 3/2

**Comment by MichalPetryka** [comment]
> @MichalPetryka should be easy to fix in `Vector128.Equals`, see [here](https://github.com/dotnet/runtime/blob/45b384dd0ab2b53a19ee0e92b6e33ea33afce0d9/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector128_1.cs#L118-L119) (C#), do you want to give it a try?
> 
> llvm-mca dump: https://www.diffchecker.com/iYXeqb1h
> (movmsk vs xor+vptest) - but not sure it's like that on all CPUs

For checks against Zero/AllBitsSet the xor could also be omitted.

**Comment by SingleAccretion** [comment]
Noting that there is an existing optimization for the `Zero` vector in lowering: https://github.com/dotnet/runtime/blob/f30c848bfec03cadb0b9ec85234d9ec82698b78e/src/coreclr/jit/lowerxarch.cpp#L1269
It doesn't kick in this case because there's a temp in the way.

How to deal with that may perhaps be the most interesting question here.

**Comment by EgorBo** [comment]
I have a quick fix in work, but since it's not urget I'm marking it as 7.0.0

> How to deal with that may perhaps be the most interesting question here.

In my fix I propagate it during inlining

**Comment by MichalPetryka** [comment]
After checking again, with AllBitsSet Xor + TestZ seem to be better than TestC with AllBitsSet, so I guess only Zero can be optimized.

**Comment by EgorBo** [comment]
> After checking again, with AllBitsSet Xor + TestZ seem to be better than TestC with AllBitsSet since that generates an additional move, so I guess only Zero can be optimized.

Thanks for confirming that! I guess we can close this issues once #55875 is merged then

**Comment by MichalPetryka** [comment]
> After checking again, with AllBitsSet Xor + TestZ seem to be better than TestC with AllBitsSet since that generates an additional move, so I guess only Zero can be optimized.

[For reference](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFqVp3KzC4A3AFgAUGUq1GLdpx4Y+AobhoANABxJxEycQDMMpOWa5sAMxiUATOQAqMXBkkBvSeS+Vj1U8AgIABtyAEEqAAoANRgwDGgqWy0AHmAATwwYAD5yADcASk9vDwlvMsoAdnIAZVwYFFonFwBhCNy0chi4hKTUjOyaUKCggCFWDFxqmAx8vTKAXyKvJZ8TcgDgsNto2PioRJT0zJyClZLy71zsKDNyAF4auttNaDaOrr2DvuPB4bGJqYzOYXSqPeqNZwYABaEQYHQYsxWiwk8yAA=)

**Comment by EgorBo** [comment]
Closed with https://github.com/dotnet/runtime/pull/55875
