### ISSUE TITLE
[HTTP/3] All requests have a body

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#55347]
When interop testing with both Kestrel and Http.Sys, all requests from HttpClient appear to have a body, even those without an HttpContent.

Http/3 uses a quic stream per request and indicates the end of the request by closing the stream (setting the FIN flag on the quic frame).
https://www.rfc-editor.org/rfc/rfc9000.html#section-19.8
I think the issue is here, where the client sends the headers and then closes the stream as separate operations:
https://github.com/dotnet/runtime/blob/7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L146-L157
That means that the headers are sent in a frame without the FIN flag and that an additional empty quic frame is sent with the FIN flag to close the connection. (This is extrapolation, I don't have a trace to confirm this).

Compare to Http/2 where it ensures EndStream is set on the initial headers frame.
https://github.com/dotnet/runtime/blob/f30c848bfec03cadb0b9ec85234d9ec82698b78e/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1438

The distinction between a request without a body vs a request who's body ends up being empty are meaningful to the server so this will cause compat issues. I think the request headers need to be sent and the stream closed in the same operation/frame/packet.

**Comment by karelz** [comment]
Triage: We need to investigate and understand better what's going on ...

**Comment by geoffkizer** [comment]
> That means that the headers are sent in a frame without the FIN flag and that an additional empty quic frame is sent with the FIN flag to close the connection.

This should be invisible to the peer. In both cases, you will receive the header data and then EOF.

> The distinction between a request without a body vs a request who's body ends up being empty are meaningful to the server so this will cause compat issues.

I don't think there is a distinction between these for HTTP3.

I'm not sure how you distinguish these for HTTP1.1, either... is a request with Content-Length: 0 a request without a body, or a request whose body ends up empty?

**Comment by Tratcher** [comment]
Here's an example we struggled with recently in YARP: 
- We need to proxy a request using different protocols for the inbound and outbound (e.g. HTTP/2 inbound, HTTP/1.1 outbound). 
- To send the request with HttpClient we need to decide in advance if we should supply an HttpContent for the body. 
  - If we do supply an HttpContent without a Content-Length then HttpClient always adds a `Transfer-Encoding: chunked` header, even if the body ends up being empty. Many servers will refuse a GET request that has a `Transfer-Encoding: chunked` header so we have to avoid creating an HttpContent unnecessarily. These rules are inconsistent across servers so we don't want to make hard coded assumptions.
- We can't read the request body in advance or we break 100-continue rules. We have to be able to decide if there's any possibility of a body by inspecting only headers and server state.

At first we mitigated this by [inspecting headers](https://github.com/microsoft/reverse-proxy/blob/bfb6406e03a342722f0661f0059f63a8c1eedc3d/src/ReverseProxy/Forwarder/HttpForwarder.cs#L361-L388) and making fallback assumptions for things like GET requests. We improved on that by exposing a [IHttpRequestBodyDetectionFeature.CanHaveBody](https://github.com/dotnet/aspnetcore/blob/1395fa8574a574ca969463952d4c5e89e9febe89/src/Http/Http.Features/src/IHttpRequestBodyDetectionFeature.cs#L9) to let the application know if the server was expecting a body based on transport state like the HTTP/2 END_OF_STREAM flag on request headers. A request with `Content-Length: 0` is considered to have no body.

Http.Sys mitigates this in a different way. Since they always pretend HTTP/2 and 3 requests are HTTP/1.x for app compat reasons, any request that isn't immediately closed and therefor might have a body will have the `Transfer-Encoding: chunked` header added to it so the application can detect if a body is expected.

QuickStream has WriteAsync overloads that take an endStream flag that I think could address this issue.
https://github.com/dotnet/runtime/blob/3ec6907d3e565c17219235183c85060e1c2bfafd/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs#L96
That's what [Kestrel](https://github.com/dotnet/aspnetcore/blob/3826122d81dd9a62efcc765c56eedbaed9969cb1/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs#L273) uses when it's writing out response data and it knows it has reached the end of the stream.

MSQuic looks like it surfaces this state on StreamEventDataReceive.[Flags](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/MsQuicNativeMethods.cs#L515) = [FIN](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/MsQuicEnums.cs#L94) 

I don't know if QuicStream has a good way of representing that on the Read APIs.

**Comment by geoffkizer** [comment]
I understand your issue here (I think).

That said, packet boundaries between data (including FIN) are not something that is semantically meaningful in QUIC. That's how TCP works too. You can't depend on a packet not having a FIN to mean that there is definitely more data coming.

**Comment by Tratcher** [comment]
> You can't depend on a packet not having a FIN to mean that there is definitely more data coming.

True, but we mainly need the opposite signal: If a packet does have a FIN flag then we know there is no more data coming. The ask is to send that FIN as early as possible, with the request headers, if there is no body following.

**Comment by geoffkizer** [comment]
We can try to do that, but does it solve your problem?

You'll still need to deal with the case where the FIN arrives separately.

**Comment by Tratcher** [comment]
You're right. Even in HTTP/2 people didn't have to put the end_of_stream on the headers frame if there was no body, they could always send an empty data frame to end the stream, but the norm was end it with the headers. I expect people will try to maintain that with HTTP/3 for consistency, compatibility, and efficiency, but you're right that the looser layering means it's harder to guarantee.

**Comment by karelz** [comment]
Triage: Looks like perf impact only. What we do is legal.
Unless #55707 is addressed for reading, server won't be able to take advantage of it anyway.

Moving to 7.0

**Comment by Tratcher** [comment]
This is not primarily a perf concern, I expect it to be a compat/interop issue, it already causes weird behavior with http.sys. We'll raise this in the next sync meeting.

**Comment by geoffkizer** [comment]
> We can't read the request body in advance or we break 100-continue rules. We have to be able to decide if there's any possibility of a body by inspecting only headers and server state.

It seems reasonable to assume that if there's an Expect: 100-continue header, then there's a body too.

For non-100-continue cases, couldn't you read ahead into the request body and see if there's actually a body or not?

**Comment by Tratcher** [comment]
> For non-100-continue cases, couldn't you read ahead into the request body and see if there's actually a body or not?

That might be possible, but still more complex than being able to check without trying to read the body. If that read doesn't complete immediately you don't want to delay proxying, so that task and its buffer have to be handed off to another component.

**Comment by karelz** [comment]
Triage: Given simplicity, we should fix it to make interop a bit better.
