### ISSUE TITLE
Stringbuilder.Append should have an IFormattable overload

### ISSUE THREAD

**Issue by jrmoreno1** [dotnet/runtime#55366]
## Background and Motivation

StringBuilder has several overloads, but none of them work with an interpolated string without first turning it into a string.  Given that purpose of the StringBuilder is performance, it seems like turning the interpolation into a string first is going to give a performance hit.

## Proposed API

```diff
namespace System.Text
{
     public sealed class StringBuilder : System.Runtime.Serialization.ISerializable
     {
+        public StringBuilder AppendFormat(IFormattable)
     }
}
```

## Usage Examples

``` C#
const string lastName = "Moreno";
const string firstName = "John";
var sb = new StringBuilder();
IFormattable name = $"{lastName}, {firstName}";
sb.AppendFormat(name);
```
-->

## Risks

It's possible that the implementation for the overload would be slower than sb.AppendFormat("{0}, {1}", lastName, firstName);

**Comment by stephentoub** [comment]
This is addressed by https://github.com/dotnet/runtime/pull/51653.  With it, you can just write:
```C#
sb.Append($"{lastName}, {firstName}");
```
and the right things happen.

Closing as a dup of https://github.com/dotnet/runtime/issues/50635. Thanks.
