### ISSUE TITLE
signed XML CheckSignature always return Null Reference exception after upgrading to .Net 5

### ISSUE THREAD

**Issue by sarahm7** [dotnet/runtime#55383]
### Description

We are currently verifying the certificate from Google SAML response and the signed XML CheckSignature always return Null Reference exception after upgrading to .Net 5

```
public void LoadXml(string xml)
{
            this.xmlDoc = new XmlDocument();
            this.xmlDoc.PreserveWhitespace = true;
            this.xmlDoc.XmlResolver = null;
            this.xmlDoc.LoadXml(xml);
            this.xmlNameSpaceManager = this.GetNamespaceManager();
}

public void LoadXmlFromBase64(string response)
{
    System.Text.UTF8Encoding enc = new System.Text.UTF8Encoding();
    this.LoadXml(enc.GetString(Convert.FromBase64String(response)));
}

public class Certificate
{
        public X509Certificate2 Cert { get; set; }

        public void LoadCertificate(string certificate)
        {
            this.LoadCertificate(this.StringToByteArray(certificate));
        }

        public void LoadCertificate(byte[] certificate)
        {
            this.Cert = new X509Certificate2(certificate);
        }

        private byte[] StringToByteArray(string st)
        {
            byte[] bytes = new byte[st.Length];
            for (int i = 0; i < st.Length; i++)
            {
                bytes[i] = (byte)st[i];
            }

            return bytes;
        }
    }

public bool IsValid()
        {
            try
            {
                XmlNodeList nodeList = this.xmlDoc.SelectNodes("//ds:Signature", this.xmlNameSpaceManager);

                SignedXml signedXml = new SignedXml(this.xmlDoc);

                if (nodeList.Count == 0)
                {
                    return false;
                }

                signedXml.LoadXml((XmlElement)nodeList[0]);
                return this.ValidateSignatureReference(signedXml) && signedXml.CheckSignature(this.certificate.Cert, true) && !this.IsExpired();
            }
            catch (NullReferenceException ex)
            {
                throw ex;
            }
           
        }
```
### Regression?

Yes, .Net Framework 4.7.2
### Other information

![image](https://user-images.githubusercontent.com/27810542/125015162-87584e80-e0a1-11eb-8c99-2d96f4d08c21.png)

Things i've tried:
- already used the new X509Certificate2(certificate); after getting the error Unsupported on this platform error
- i tried the following but its still has Null Reference Exception or false output
a. signedXml.CheckSignature(this.certificate.Cert, false)
b. signedXml.CheckSignature(this.certificate.Cert.PublicKey.Key)
c. signedXml.CheckSignature()

**Comment by vcsjones** [comment]
Can you include the public certificate that is being used to validate the SAML response?

Is this occurring on Windows, Linux, or MacOS?

**Comment by sarahm7** [comment]
This is in Windows and here's the public cert:

`-----BEGIN CERTIFICATE-----MIIDdDCCAlygAwIBAgIGAWAqTtw1MA0GCSqGSIb3DQEBCwUAMHsxFDASBgNVBAoTC0dvb2dsZSBJbmMuMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MQ8wDQYDVQQDEwZHb29nbGUxGDAWBgNVBAsTD0dvb2dsZSBGb3IgV29yazELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWEwHhcNMTcxMjA2MDUzMTM2WhcNMjIxMjA1MDUzMTM2WjB7MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEPMA0GA1UEAxMGR29vZ2xlMRgwFgYDVQQLEw9Hb29nbGUgRm9yIFdvcmsxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtewo+Wub3UEhIYQjTDwb5V9kjazsPikSIuAocV/7mmz30yuohH/6SXxXBDQxMgYdQ33ol0ecUSSCNuKHVLsoqEMcylDBoXdC8B5FbyBBhnvQQp95l/o80o5TNpwhRyTzjr87ory3mnvHHl7UAvEve+5KYfhsDHXpWRPxaOv5SlWWorynwLnf9PbWRLvwkp41caV8SefVEszWiP+KedPHJ3OR3G0ZAfIy8TtngGWN4F/GM7+qb/8dE8d5eBq+khvvWCuUHvXS1i2d9/nBOg2+q+t52SFR15May9DWab8H0z++E/J4VnbneqrQjq/T/igvISKbKpzFRu7RVWZi+svvUQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBqMKnvUbBAMBnzt1czyTBnTpGtUvurqENNPy8LKb+08DfNgA38tII7Xz7B7RHEf8Wp9NkpIKL9v3l+yzSLQ9V5IKnrmavdpSP0DT84FnFAR1TiDwmIe08BDzhq85EnYJ+GAEtsHP7pYu0zcqSZiAOWxvUdJS5v+dLyUfKfuAxqImZE6KQWOvQpKyOxs8S513hFr3kxAY61WqN01Wpm/Yt4L5em9nXhoVQ5XDug3TASeZRTZc69BSe0RyHsXVaARhnfYklj4GBnKwFPd7crEHvAfQrknYhnrS+dAxEq1muK1OFuSXsnEXSSQ6m4qcEgHeWNFd9kuLRfPvnfynKRvA3h-----END CERTIFICATE-----`

**Comment by vcsjones** [comment]
Thanks for the certificate. I see from your screenshot that the exception is happening in `IsKeyTheCorrectAlgorithm`.

If I had to guess, this `Type.GetType` here is returning `null`:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/SignedXml.cs#L1007

Would it be possible for you to include a sample SAML response that is reproducing the issue? 

Also, does your application make use of `CryptoConfig.AddAlgorithm` anywhere?

**Comment by sarahm7** [comment]
Yes, when i debugged it Type.GetType is returning null. See attached for the sample SAML response: [samlResponse.txt](https://github.com/dotnet/runtime/files/6813047/samlResponse.txt)

Yes, we use the AddAlgorithm:

```
public static void Init()
        {
            if (!initialized)
            {
                CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");
            }

            initialized = true;
        }

////////////////////////
public class Response
    {
        private Certificate certificate;
        public Response(string certificateStr)
        {
            RSAPKCS1SHA256SignatureDescription.Init();
            this.certificate = new Certificate();
            this.certificate.LoadCertificate(certificateStr);
        }
}
```

**Comment by vcsjones** [comment]
> Yes, we use the AddAlgorithm:

Can you try removing the `AddAlgorithm`? .NET 5+ support `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`:

https://github.com/dotnet/runtime/blob/fa779e8cb2b5868a0ac2fd4215f39ffb91f0dab0/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs#L35

Since `RSAPKCS1SHA256SignatureDescription` is internal, I assume this is your own implementation, and `KeyAlgorithm` is referring to something that does not exist in .NET 5.

**Comment by sarahm7** [comment]
thanks so much for your help @vcsjones ! it's working as expected now. 👍
