### ISSUE TITLE
How to Cache System text Json Converters?

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#55388]
I've the following converter for nullable enums....
But it is recreated for same Type very time (I thought CreateConverter type would be cached)

Whats the best way to cache the converter?

    using MCC.Utilities.ExtensionMethods;
    using System;
    using System.Reflection;
    using System.Runtime.CompilerServices;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    namespace MCC.Utilities.Serialisation
    {
        public class MccJsonStringEnumConverterFactory : JsonConverterFactory
        {
            public MccJsonStringEnumConverterFactory()
                : this(namingPolicy: null, allowIntegerValues: true)
            {
            }

            public MccJsonStringEnumConverterFactory(JsonNamingPolicy? namingPolicy = null, bool allowIntegerValues = true)
            {
            }

            public override bool CanConvert(Type typeToConvert)
            {
                var nullableType = Nullable.GetUnderlyingType(typeToConvert);
                if (nullableType != null)
                {
                    return nullableType.IsEnum;
                }
                return typeToConvert.IsEnum;
            }

            public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
            {
                var converterType = typeof(MccJsonStringEnumConverter<>).MakeGenericType(typeToConvert);
                return (JsonConverter)Activator.CreateInstance(converterType);
            }
        }

        public class MccJsonStringEnumConverter<T> : JsonConverter<T>
        {
            private readonly Type _type;
            private readonly TypeCode _typeCode;

            public MccJsonStringEnumConverter()
            {
                var typeToConvert = typeof(T);
                var nullableType = Nullable.GetUnderlyingType(typeToConvert);
                if (nullableType != null)
                {
                    this._type = nullableType;
                }
                else
                {
                    this._type = typeToConvert;
                }
                _typeCode=Type.GetTypeCode(this._type);
            }

            public override bool CanConvert(Type typeToConvert)
            {
                return typeof(T).IsAssignableFrom(typeToConvert);
            }

            public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.String)
                {
                    string value = reader.GetString();

                    if (String.IsNullOrEmpty(value)) return default;

                    // for performance, parse with ignoreCase:false first.
                    if (!Enum.TryParse(_type, value,
                        ignoreCase: false, out object result)
                    && !Enum.TryParse(_type, value,
                        ignoreCase: true, out result))
                    {
                        throw new JsonException(
                            $"Unable to convert \"{value}\" to Enum \"{_type}\".");
                    }

                    return (T)result;
                }
                else 
                {
                    switch (_typeCode)
                    {
                        // Switch cases ordered by expected frequency

                        case TypeCode.Int32:
                            if (reader.TryGetInt32(out int int32))
                            {
                                return Unsafe.As<int, T>(ref int32);
                            }
                            break;
                        case TypeCode.UInt32:
                            if (reader.TryGetUInt32(out uint uint32))
                            {
                                return Unsafe.As<uint, T>(ref uint32);
                            }
                            break;
                        case TypeCode.UInt64:
                            if (reader.TryGetUInt64(out ulong uint64))
                            {
                                return Unsafe.As<ulong, T>(ref uint64);
                            }
                            break;
                        case TypeCode.Int64:
                            if (reader.TryGetInt64(out long int64))
                            {
                                return Unsafe.As<long, T>(ref int64);
                            }
                            break;
                        case TypeCode.SByte:
                            if (reader.TryGetSByte(out sbyte byte8))
                            {
                                return Unsafe.As<sbyte, T>(ref byte8);
                            }
                            break;
                        case TypeCode.Byte:
                            if (reader.TryGetByte(out byte ubyte8))
                            {
                                return Unsafe.As<byte, T>(ref ubyte8);
                            }
                            break;
                        case TypeCode.Int16:
                            if (reader.TryGetInt16(out short int16))
                            {
                                return Unsafe.As<short, T>(ref int16);
                            }
                            break;
                        case TypeCode.UInt16:
                            if (reader.TryGetUInt16(out ushort uint16))
                            {
                                return Unsafe.As<ushort, T>(ref uint16);
                            }
                            break;
                    }
                }
                return default;
            }

            public override void Write(Utf8JsonWriter writer,
                T value, JsonSerializerOptions options)
            {
                writer.WriteStringValue(value?.ToString());
            }
        }
    }

**Comment by Joe4evr** [comment]
Putting a Dictionary in the JsonConverterFactory is my usual quick-and-dirty method of caching in these cases.
```cs
private readonly Dictionary<Type, JsonConverter> _cache = new();

public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
{
    if (!_cache.TryGetValue(typeToConvert, out var converter)
    {
        var converterType = typeof(MccJsonStringEnumConverter<>).MakeGenericType(typeToConvert);
        converter = (JsonConverter)Activator.CreateInstance(converterType);
        _cache[typeToConvert] = converter;
    }
    return converter;
}
```

**Comment by jogibear9988** [comment]
I've done like this now:
(but I thought, isn't this already done by the MS code, and is this the intended way?)

    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    namespace MCC.Utilities.Serialisation
    {
        public class MccJsonStringEnumConverterFactory : JsonConverterFactory
        {
            private static Dictionary<Type, JsonConverter> _cache = new();

            public MccJsonStringEnumConverterFactory()
                : this(namingPolicy: null, allowIntegerValues: true)
            {
            }

            public MccJsonStringEnumConverterFactory(JsonNamingPolicy? namingPolicy = null, bool allowIntegerValues = true)
            {
            }

            public override bool CanConvert(Type typeToConvert)
            {
                var nullableType = Nullable.GetUnderlyingType(typeToConvert);
                if (nullableType != null)
                {
                    return nullableType.IsEnum;
                }
                return typeToConvert.IsEnum;
            }

            public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
            {
                if (!_cache.TryGetValue(typeToConvert, out var converter))
                {
                    var converterType = typeof(MccJsonStringEnumConverter<>).MakeGenericType(typeToConvert);
                    converter = (JsonConverter)Activator.CreateInstance(converterType);
                    var newCache = new Dictionary<Type, JsonConverter>(_cache);
                    newCache[typeToConvert] = converter;
                    _cache = newCache;
                }
                return converter;
            }
        }

        public class MccJsonStringEnumConverter<T> : JsonConverter<T>
        {
            private readonly Type _type;
            private readonly TypeCode _typeCode;

            public MccJsonStringEnumConverter()
            {
                var typeToConvert = typeof(T);
                var nullableType = Nullable.GetUnderlyingType(typeToConvert);
                if (nullableType != null)
                {
                    this._type = nullableType;
                }
                else
                {
                    this._type = typeToConvert;
                }
                _typeCode = Type.GetTypeCode(this._type);
            }

            public override bool CanConvert(Type typeToConvert)
            {
                return typeof(T).IsAssignableFrom(typeToConvert);
            }

            public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                if (reader.TokenType == JsonTokenType.String)
                {
                    string value = reader.GetString();

                    if (String.IsNullOrEmpty(value)) return default;

                    // for performance, parse with ignoreCase:false first.
                    if (!Enum.TryParse(_type, value,
                        ignoreCase: false, out object result)
                    && !Enum.TryParse(_type, value,
                        ignoreCase: true, out result))
                    {
                        throw new JsonException(
                            $"Unable to convert \"{value}\" to Enum \"{_type}\".");
                    }

                    return (T)result;
                }
                else 
                {
                    switch (_typeCode)
                    {
                        // Switch cases ordered by expected frequency

                        case TypeCode.Int32:
                            if (reader.TryGetInt32(out int int32))
                            {
                                return Unsafe.As<int, T>(ref int32);
                            }
                            break;
                        case TypeCode.UInt32:
                            if (reader.TryGetUInt32(out uint uint32))
                            {
                                return Unsafe.As<uint, T>(ref uint32);
                            }
                            break;
                        case TypeCode.UInt64:
                            if (reader.TryGetUInt64(out ulong uint64))
                            {
                                return Unsafe.As<ulong, T>(ref uint64);
                            }
                            break;
                        case TypeCode.Int64:
                            if (reader.TryGetInt64(out long int64))
                            {
                                return Unsafe.As<long, T>(ref int64);
                            }
                            break;
                        case TypeCode.SByte:
                            if (reader.TryGetSByte(out sbyte byte8))
                            {
                                return Unsafe.As<sbyte, T>(ref byte8);
                            }
                            break;
                        case TypeCode.Byte:
                            if (reader.TryGetByte(out byte ubyte8))
                            {
                                return Unsafe.As<byte, T>(ref ubyte8);
                            }
                            break;
                        case TypeCode.Int16:
                            if (reader.TryGetInt16(out short int16))
                            {
                                return Unsafe.As<short, T>(ref int16);
                            }
                            break;
                        case TypeCode.UInt16:
                            if (reader.TryGetUInt16(out ushort uint16))
                            {
                                return Unsafe.As<ushort, T>(ref uint16);
                            }
                            break;
                    }
                }
                return default;
            }

            public override void Write(Utf8JsonWriter writer,
                T value, JsonSerializerOptions options)
            {
                writer.WriteStringValue(value?.ToString());
            }
        }
    }

**Comment by Joe4evr** [comment]
> isn't this already done by the MS code

Why would they? All the `S.T.Json` stuff was designed to be as minimalistic as possible. It's much easier to make a consumer *add* whatever caching strategy they want if they need to, compared to having one by default and someone needing to remove/change it.

**Comment by jogibear9988** [comment]
but if i use the ms stringenumconverter, is this cached or not?

Von meinem iPhone gesendet

**Comment by acaly** [comment]
@jogibear9988 Using a `Dictionary` as static field without a lock would have problems in multithread environments. It's better to use a `ConcurrentDictionary` for a more quick-and-dirty solution.

**Comment by jogibear9988** [comment]
@acaly  why?
I replace the whole dictionary with a complete new one. So there will not be a write access to the existing one.

**Comment by acaly** [comment]
Yes, your method should work correctly. What I suggested is just an alternative, to use a thread-safe container instead of creating immutable containers whenever it's modified. Actually `ConcurrentDictionary` should be as fast as normal `Dictionary` when reading.

**Comment by eiriktsarpalis** [comment]
I believe converters [are being cached by STJ](https://github.com/dotnet/runtime/blob/56d9474f530579c67b294cbbde0724e966dbb05b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L175-L179), however each `JsonSerializerOptions` instance maintains [its own cache for converters](https://github.com/dotnet/runtime/blob/56d9474f530579c67b294cbbde0724e966dbb05b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L27). 

Unless you are instantiating a new options instance on every serialization, converter factories should not be invoked more than once per type (modulo concurrency scenaria).

**Comment by jogibear9988** [comment]
@eiriktsarpalis I'll check again, but as I saw they were not cached (or my constructor was hit again).
But maybe I've an error with the options. I'll check

**Comment by jogibear9988** [comment]
I've tested again.

The CreateConverter of the JsonConverterFactory is called again every time (for the same type). So the Factory is cached, but not the Converters it creates.

**Comment by eiriktsarpalis** [comment]
Could you share a standalone reproduction that demonstrates this behavior?

**Comment by eiriktsarpalis** [comment]
I'm going to close this for now. Feel free to reopen whenever you are able to share a reproducing code sample.
