### ISSUE TITLE
System.Linq.Expressions.NewExpression.Constructor is marked nullable - should be not null

### ISSUE THREAD

**Issue by MrTA2** [dotnet/runtime#55399]
## Background and Motivation

Proper nullability decoration

## Proposed API

```diff
namespace System.Linq.Expressions
{
  public class NewExpression .....
  {
-    public ConstructorInfo? Constructor { get; }
+    public ConstructorInfo Constructor { get; }
  }
  public class MethodCallExpression .....
  {
-    public MethodInfo? Method { get; }
+    public MethodInfo Method { get; }
  }
}
```

## Usage Examples

```diff
NewExpression newExpression = ...;
- var ctor = newExpression.Constructor!;
+ var ctor = newExpression.Constructor;
MethodCallExpression methodCallExpression = ...;
- var method = methodCallExpression.Method!;
+ var method = methodCallExpression.Method;
```

**Comment by stephentoub** [comment]
This will print "True":
```C#
using System;
using System.Linq.Expressions;

NewExpression ne = Expression.New(typeof(int));
Console.WriteLine(ne.Constructor is null);
```
highlighting the property can return null.

**Comment by MrTA2** [comment]
@stephentoub why is that even allowed? Shouldn't we force them to use `Expression.Constant(0)` for this?

**Comment by stephentoub** [comment]
> why is that even allowed?

I can't speak to the design or implementation here.  The nullable annotations were added subsequently and reflect the reality of what's possible.  If the implementation were changed such that null couldn't be returned here, then the annotation could be updated to reflect that, but at the moment it's accurate.

**Comment by huoyaoyuan** [comment]
It will be `null` for any value type. The default (all-zero) constructor is not defined in metadata, but represented as `new` expression.

**Comment by stephentoub** [comment]
Closing,  as the nullable annotation is correct. Thanks.
