### ISSUE TITLE
Make DefaultInterpolatedStringHandler Text and Clear APIs public

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#55390]
## Background and Motivation

The new `DefaultInterpolatedStringHandler` type (supporting https://github.com/dotnet/runtime/issues/50601 and following parts) is great, but there are two design decisions that restrict its actual usefulness a lot in some scenarios. Specifically, the fact `Text` and `Clear` are internal and not public prevents developers from being able to use this type directly in an efficient manner. I'm aware that the reason these are not public is that this type is "only meant to be used directly by the compiler", but my argument is that this is an artificial solution that just prevents developers aware of this type from being able to use it effectively, without actually solving the supposed issue anyway, as the type itself can still in fact be used directly, just... Slower and with completely avoidable allocations.

Here's my points in support for this proposals:

- As mentioned above, the whole type is already public, and can already technically be used by developers. The only result of keeping those two APIs internal is that developers won't be able to use it effectively, so they'll have to either just accept the useless allocation, or just copy-paste the whole type in their own project (eg. [I'm doing that](https://github.com/Sergio0694/ComputeSharp/blob/dae3024cae8aaae18fbb2a9fa59ab0ce64073002/src/ComputeSharp/Shaders/Renderer/HlslShaderRenderer.cs#L199)), which is clunky and not ideal.
- Yes, the type is a struct and as such one needs to be careful (eg. it must not be copied and used in different places). But then again, it is in `System.Runtime.CompilerServices`, which already contains _far_ more dangerous APIs, and it's also a place where only developers specifically looking for it will find it, and they will be aware of these nuances. I'm not advocating for making the whole type a more accessible API in a more common namespace, as I totally agree the type is not "safe enough" for that. I'm just arguing for making these two APIs public for advanced developers that will be specifically looking for them.
- Point raised by @333fred on Discord: _"the whole namespace is niche and generally only supposed to be used by the compiler, so we should only put things in it that should be used by the compiler"_. That isn't actually true for the namespace already, as there's plenty of APIs that are either explicitly meant to be used by developers and not the compiler anyway (eg. the `Unsafe` class, or the various calling conventions for function pointers), as well as some that are originally intented just for compilers but that are still widely used by library authors in general and have even received better support for this (eg. `ConditionalWeakTable<K, V>`, which also got enumerator support a while back). Just using the namespace as a reason to keep these two APIs internal seem like an arbitrary decision in this regard that in this case just removes value that is there already.
- Quoting @tannergooding on Discord: _"Sergio's complaint is that its effectively public, without actually being public. There will be a language feature dependency on it and that means (essentially) compat for all time. Because if it changes, any existing programs compiled using the feature will now break, so it qualifies as a binary breaking change, which is the worst kind. So its not just Roslyn depends on it, and the .NET team owns both, so we can say its ok its C# depends on it, and if Joe or Sally use the feature in their program, their program now depends on the contract, even if its "internal" so its effectively public, just not directly usable"_. As in, there is little to no maintenance cost being added in making these two APIs public, as the whole type will already have to be (and is) well tested and maintained in the future. **EDIT:** there was a misunderstanding on this last point, see https://github.com/dotnet/runtime/issues/55390#issuecomment-877269175 for clarification 🙂

I agree that it would be nice to have an "official" public pooled builder type in the future, possibly when/if C# gets support for moveonly structs, sure. But the point is that for now, making those two APIs public can already add a ton of value for developers looking for a type like that. The `DefaultInterpolatedStringHandler` is an optimized span of char builder with pooling support, that's already built-in into .NET 6, what's not to love? It's brilliant - just needs these two final bits public 😄

## Proposed API

This proposal is about making these two APIs public. No functional changes at all are required.

https://github.com/dotnet/runtime/blob/d431d6a15726797965336176efe9ae15aba241fd/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs#L128-L129

https://github.com/dotnet/runtime/blob/d431d6a15726797965336176efe9ae15aba241fd/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs#L116-L126

 Goes without saying that I'd be happy to contribute the change if this was approved 🙌

## Usage Examples

As mentioned above, I'm using a custom builder type [here](https://github.com/Sergio0694/ComputeSharp/blob/dae3024cae8aaae18fbb2a9fa59ab0ce64073002/src/ComputeSharp/Shaders/Renderer/HlslShaderRenderer.cs#L25), and that's an example of something that could just benefit from using the built-in builder. In that case I don't ever need an actual `string` as a result, as I just get the final `ReadOnlySpan<char>` buffer and pass it to a native API to compile the resulting HLSL source. Furthermore, `DefaultInterpolatedStringHandler` also has dedicated APIs to append formatted values (eg. implementing `ISpanFormattable`) which would be great to have.

Furthermore, I'm updating that part of the library to instead emit all the HLSL generation code directly into consuming projects, through a source generator (to speedup the whole process and make it more specialized). To do so, I'm going to need to pass a target builder to the generated method (which is an implementation detail and meant for direct usage by consumers). It'd be great if I could just pass a reference to an `DefaultInterpolatedStringHandler` instance instead of having to make my own custom builder type public as well to allow generated code to use it, like so (simplifying a bit):

```csharp
// Generated in consuming projects
public partial struct MyShaderType : IShader<MyShaderType>
{
    [GeneratedCode("...", "...")]
    [DebuggerNonUserCode]
    [ExcludeFromCodeCoverage]
    [EditorBrowsableState(EditorBrowsableState.Never)]
    [Obsolete("This method is not intended to be used directly by user code")]
    static void IShader<MyShaderType>.EmitHlslSource(ref DefaultInterpolatedStringHandler handler)
    {
        // Emit HLSL code specific for MyShaderType
    }
}
```
```csharp
// Code in my library executing the shader
internal static IDxcBlobObject LoadShader<T>()
    where T : IShader<T>
{
    DefaultInterpolatedStringHandler handler = new(...);

    T.EmitHlslSource(ref handler);

    IDxcBlobObject shaderBytecode = ShaderCompiler.Instance.CompileShader(handler.Text); // Ta-dà! 🎉

    handler.Clear();

    return shaderBytecode;
}
```

## Risks

Not really any given the namespace the type is in, as mentioned above.
Developers using the type directly should already be aware of the needed moveonly semantics to avoid issues.

**Comment by tannergooding** [comment]
> Quoting @tannergooding on Discord: "Sergio's complaint is that its effectively public, without actually being public. There will be a language feature dependency on it and that means (essentially) compat for all time. Because if it changes, any existing programs compiled using the feature will now break, so it qualifies as a binary breaking change, which is the worst kind. So its not just Roslyn depends on it, and the .NET team owns both, so we can say its ok its C# depends on it, and if Joe or Sally use the feature in their program, their program now depends on the contract, even if its "internal" so its effectively public, just not directly usable". As in, there is little to no maintenance cost being added in making these two APIs public, as the whole type will already have to be (and is) well tested and maintained in the future.

I misunderstood this originally based on the context of the related Discord discussion. These APIs do look to be used entirely internally and are not directly used by the compiler, so it should not actually be breaking.

There may still be merit in exposing them, but my general statement quoted was incorrect :)

**Comment by Sergio0694** [comment]
@tannergooding I've updated the proposal linking your clarification on that point 😄

Pinging @joperezr as area owner, does the proposal seem reasonable? I know we missed the .NET 6 release at this point, but given that proper language support for `moveonly` is still nowhere on the roadmap (which means that `ValueStringBuilder` is also not coming any time soon), I think there's value in adding this to .NET 7 still, especially given the low cost. Would it make sense to mark this as ready to review and set the milestone to .NET 7, unless you feel strongly against it or have feedbacks?

Thanks! 🙂

**Comment by Sergio0694** [comment]
@dotnet/area-system-runtime-compilerservices just bumping this now that `main` is targeting .NET 7. Unless there's specific concerns on the proposed changes, was wondering whether we could mark this for the .NET 7 milestone and as ready for review, so we can have FXDC take a look. I just cannot stress enough how useful this type could be with those two extra APIs being public, for advanced developers who are aware that the type exists and knowing how to use it properly 😄

**Comment by joperezr** [comment]
@stephentoub since I believe you are more familiar with this type, do you see any issue on marking this as ready for review?

**Comment by stephentoub** [comment]
We can mark it as ready for review.  It'll be an interesting discussion, though ;-)

**Comment by terrajobst** [comment]
* There are two concerns:
    1. The `Text` property might constrain our implementation (e.g. we couldn't do a linked list of buffers). We could, however, expose a `TryGetText()` if we cared enough.
    2. We designed the type as a building block for the C# string interpolation feature that is used by compiler generated code. The concern is that this type is easy to be used unsafely, due to no move semantics in .NET.
* Hence, we'd rather not make these APIs public

```C#
namespace System.Runtime.CompilerServices
{    
    public partial struct DefaultInterpolatedStringHandler
    {
        // These APIs already exist, but are internal
        public void Clear();
        public ReadOnlySpan<char> Text { get; }
    }
}
```
