### ISSUE TITLE
Disable System.Linq.Expressions.Expression.New(typeof(int))

### ISSUE THREAD

**Issue by MrTA2** [dotnet/runtime#55401]
## Background and Motivation

This creates a weird `NewExpression` where the constructor is null. The result of this would be the value of 0, so why not just use `Expression.Constant(0)`. Related: [make constructor property not null](https://github.com/dotnet/runtime/issues/55399)

## Proposed API

No changes, but specifying a type without constructors (such as a primitive value type) should throw instead of succeeding when calling `Expression.New`.

## Usage Examples

``` C#
// instead of
var expression = Expression.New(typeof(int));
// use this:
var expression = Expression.Constant(0);
```

## Risks

Backwards compatibility risk, however this is small: this type of code is only written by various libraries such as ORMs.

**Comment by huoyaoyuan** [comment]
> why not just use `Expression.Constant(0)`

Because `new int()` is valid in C#, and expression tree is meant to preserve the original code you wrote in C#.

**Comment by cston** [comment]
Changing `Expression.New(Type)` to throw an exception for value types (with implicit parameterless constructors) would be a breaking change for existing callers.

It's unlikely we'd change this and break compatibility.
