### ISSUE TITLE
Exception in MsQuicStream.HandleWriteStartState can abandon CancellationTokenRegistration

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55437]
In HandleWriteStartState, we do some initial checks, then register a CancellationTokenRegistration, and then do some additional checks on SendState that could throw. If these do throw, then the CancellationTokenRegistration is abandoned and could fire at any time in the future, which is not what we want.

At a minimum we should unregister the CancellationTokenRegistration if an exception occurs here. Better, it would be good to avoid registering it until after we have done the checks that may throw. It's not obvious to me if this is valid to do, though.

**Comment by karelz** [comment]
Triage: We have similar problem in Read part -- over there the checks won't have impact on customers / users of the API. We will just raise useless event.
We should check if it is the same here. If yes, we can punt to 7.0. Otherwise fix it.
