### ISSUE TITLE
Suggest `Enum.HasFlag` on modern frameworks.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#55455]
The `System.Enum` type has a `HasFlag` method that allows easily and intuitively checking if a bit is set on enums with the `[Flags]` attribute, but it has been historically avoided because on it used to do some expensive boxings and type checks, until it got optimized in .NET Core 2.1.

The problem is that few people know that it's now fine to use this method without fears of performance issues, which is why I propose an analyzer that would warn on bitwise tests on enum flags and offer to fix them to use `Enum.HasFlag`.

### How it would work

|The analyzer would convert this|to that|
|-|-|
|`(x & MyEnum.Foo) == MyEnum.Foo`|`x.HasFlag(MyEnum.Foo)`|
|`(x & MyEnum.Foo) != MyEnum.Foo`|`!x.HasFlag(MyEnum.Foo)`|
|`(x & MyEnum.Foo) == 0`|`!x.HasFlag(MyEnum.Foo)`|
|`(x & MyEnum.Foo) != 0`|`x.HasFlag(MyEnum.Foo)`|
|`(x & (MyEnum) 8) == 0`|_the analyzer would not trigger_|

### Supported frameworks

To avoid any performance regressions, the analyzer would be enabled when the project exclusively targets at least .NET Core 2.1 or .NET Standard 2.1 (I don't know whether `HasFlag` is optimized on Xamarin/Unity/UWP). It would not be enabled on projects targeting .NET Standard 2.0 because they might be used from a .NET Framework project.

**Comment by MichalPetryka** [comment]
Checks against 0 have a different behavior from HasFlag when MyEnum.Foo has more than 1 bit set, HasFlag checks if all bits are set then and != 0 checks if any bit is set.

**Comment by jkotas** [comment]
> intuitively

It may be a personal style choice. I find `(x & MyEnum.Foo) != 0` and `(x & MyEnum.Foo) == 0` to be more intuitive and idiomatic than `HasFlag`. It is a few characters shorter too.

**Comment by teo-tsirpanis** [comment]
> Checks against 0 have a different behavior from HasFlag when MyEnum.Foo has more than 1 bit set, HasFlag checks if all bits are set then and != 0 checks if any bit is set.

Okay @MichalPetryka the analyzer could work only when `HasFlag` is passed a flag with only one bit set.

**Comment by jkotas** [comment]
> it used to do some expensive boxings and type checks, until it got optimized in .NET Core 2.1.

Note that this optimization is not guaranteed to kick in. The optimization won't kick in `Debug` builds, in tier 0 JIT, or when the method is too big.

**Comment by teo-tsirpanis** [comment]
I see, if that optimization is not guaranteed, there is no reason to encourage moving to `HasFlag` en masse, especially since there are many kinds of enum bitwise AND check depending on the exact intention, as Michal said.
