### ISSUE TITLE
Can both TaskContinuationOptions.OnlyOnRanToCompletion and TaskContinuationOptions.RunContinuationsAsynchronously be used to create continuation task?

### ISSUE THREAD

**Issue by BhusanBibhuti** [dotnet/runtime#55464]
I want to create a continuation task and I want the continuation task to run if the antecedent ran to completion and the continuation task may run on a different thread than the antecedent one.

Is this a valid implementation ?
Here is something I want to do:-

private async Task<(List<ProductDto>, List<BundleLineDto>)> ProcessUpdateDeal(CreateDealForExternalSourceRequest createDealRequest, Services.Deal.Generated.DealHeader latestDeal, CreateDealForExternalSourceResponse dealResponse)
        {
            var tasks = new List<Task>();
            var productLines = new List<ProductDto>();
            var bundleLines = new List<BundleLineDto>();
            var taskContinuationOptions = TaskContinuationOptions.OnlyOnRanToCompletion | TaskContinuationOptions.RunContinuationsAsynchronously;

            try
            {
                if (createDealRequest.DealHeader != null)
                {
                    var updateDealHeaderTask = _dealHeaderBuilder.UpdateDealHeader(latestDeal.DealId, createDealRequest);
                    var updateDealHeaderContinuationTask = updateDealHeaderTask.ContinueWith(UpdateDealHeaderContinuationTaskAction, **taskContinuationOptions**);
                    tasks.Add(updateDealHeaderContinuationTask);
                }
            }
            catch (AggregateException aggregateException)
            {
                /*TO DO --Log to logger */
                for (int j = 0; j < aggregateException.InnerExceptions.Count; j++)
                {
                    Debug.WriteLine("\n-------------------------------------------------\n{0}", aggregateException.InnerExceptions[j].ToString());
                }
                throw;
            }
            return (productLines, bundleLines);
        }

**Comment by stephentoub** [comment]
If you have:
```C#
Task a = ...;
Task b = a.ContinueWith(..., TaskContinuationOptions.OnlyOnRanToCompletion | TaskContinuationOptions.RunContinuationsAsynchronously);
Task c = b.ContinueWith(...);
```
the OnlyOnRanToCompletion will cause `b` to be canceled if `a` completes in any state other than RanToCompletion, and the RunContinuationsAsynchronously will force `c` to always execute asynchronously from `b`'s completion, regardless of whether `c` is created with ExecuteSynchronously.  The `RunContinuationsAsynchronously` passed to the a.ContinueWith is configuring `b`'s behavior and saying that any continuations off of b should be asynchronous.

That said, by default tasks created by ContinueWith are always executed asynchronously from the antecedent, so if your goal is for `b` to be asynchronous from `a`'s completion, just don't pass ExecuteSynchronously.
