### ISSUE TITLE
Constant string local variable does not get fold in release mode

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/runtime#55476]
I am not sure if is this a bug or this is the expected behavior. 

I was playing with generated code that the JIT compiler generates for the following simple program. 

![image](https://user-images.githubusercontent.com/17148381/125204161-770ac400-e299-11eb-9254-d00b86c66e30.png)

Am wondering why the JIT compiler does not produce the same codegen for the `Main` method just like it did for the `Another` method in the program? 

As that variable `a` is not used other than in the `Console.WriteLine()` place, can't we fold that as a constant string and eliminate that redundant codegen. 

link to code => https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACRukDs26A3uthbgguZWWpY9gG5gBO2Y2AvBQEQAJAKYAbEQHs+AblpN8ATgAUXANTY+AZQAWbIQE9IfAJRS5FWdgC+Fi1nwA2XABZsAQQB244FqFtFRi3ozBUVBUQk+bDVNHX1DE2CLazRLIA=

**Comment by EgorBo** [comment]
I had a branch for this opt somewhere but the jit-diffs only found a few Exception-related code paths so I gave up on it as non-profitable, any real-world examples where it could be useful?

**Comment by KalleOlaviNiemitalo** [comment]
> just like it did for the `Another` method in the program?

The constant strings in `Another` are concatenated by the C# compiler, not the JIT compiler. If you use `const string a = "Hello";` in `Main`, then the C# compiler concatenates that too. <https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgYGYAE9sIOyaoDeqmZ2ccp5JK59mAxgPYB2AzsLgAyYCGmALyYARAAkAphAjMRAbmoNcATgAUAgNSiAygAsAThICefdiICUcpWUWYAvrdsZcANmwAWTAEFWzYLol9VXNbWmsVVXEpGRFMLRE9QxMzS3DbBxQ7IA==>

**Comment by ShreyasJejurkar** [comment]
> > just like it did for the `Another` method in the program?
> 
> The constant strings in `Another` are concatenated by the C# compiler, not the JIT compiler. If you use `const string a = "Hello";` in `Main`, then the C# compiler concatenates that too. 

But if we go back to basics, the variable a is only used  at that line and it's never used again and also its string and haven't manipulated in that method body overall, so I there is high chance to get that fold, but JIT did not did which surprised me. 

BTW this is not even complex optimization, seems like basic to me.

**Comment by ShreyasJejurkar** [comment]
> I had a branch for this opt, but the jit-diffs only found a few Exception-related code paths, so I gave up on it as non-profitable. Any real-world examples where it could be useful?

No Egor. But I was expecting that to get fold. It's not even a complex optimization that we see in other compilers.

**Comment by stephentoub** [comment]
> It's not even a complex optimization

It's complex enough to make adding additional code for it when there's little to no value a suspect thing to do.  The JIT doesn't see:
```C#
var a = "Hello";
Console.WriteLine(a + "Shreyas");
```
Rather, the C# compiler translates that into the equivalent of:
```C#
Console.WriteLine(String.Concat("Hello", "Shreyas"));
```
That means in order to understand that this could become:
```C#
Console.WriteLine("HelloShreyas");
```
the JIT would actually need to be taught about the semantics of the String.Concat method, which means making it a JIT intrinsic.

**Comment by ShreyasJejurkar** [comment]
@stephentoub Thanks Stephen, totally makes sense to me and I understood. 
What I thought there might be a phase in C# compiler just like morphing in JIT compiler where C# compiler has seen that the variable `a` has string literal and it is not even manipulated over its lifetime so we can directly fold with const value instead of having variable. And subsequently, we would have reduced the JIT ASM codegen for that. 

Is that possible @stephentoub @EgorBo with today's C# compiler? 

I also agree with @EgorBo that there wasn't a profitable diff with this optimization. But here we are getting diff for CoreLibs correct? and those are highly optimized, but if you consider this scenario in day-to-day general developer life, this scenario is quite common and those can get the benefit from this kinda optimization as well.

**Comment by stephentoub** [comment]
That's a question for dotnet/roslyn.

**Comment by ShreyasJejurkar** [comment]
@stephentoub Ohhh. Hmmm. But any idea or insights you have on that?

**Comment by stephentoub** [comment]
The C# compiler already does some level of constant folding; that's exactly why in your second example the `"Hello" + "Shreyas"` was transformed into `"HelloShreyas"`.  But it doesn't currently do more complex folding across non-const variables.  If it's something you're concerned about, I recommend discussing it in the dotnet/roslyn repo.  But if you're unable to come up with real-world examples where it would matter, it's not clear to me it's worth the discussion.  Thanks.

**Comment by ShreyasJejurkar** [comment]
OK, @stephentoub I understood. Thanks. 👍
