### ISSUE TITLE
deploy nginx with .net core

### ISSUE THREAD

**Issue by jindovu** [dotnet/runtime#55470]
I have been upgrade from .net core 2.2 to .net core 3.1, when I'm running on enviroment window server it's work ok howerver when I'm trying to upgrade and deploy on ubuntu 20.4 (Nginx) server, it's can't access to images and the reponse always is 404,
I try to upload with a page html & image it's working ok, could you help me to please check this 
- Folder contains images in wwwroot

> 1. images
> 2. user-content

```
server {
        listen 80;
        server_name webtest.vn, *.webtest.vn;
        root    /var/www/webtest;

        location / {
            proxy_pass         http://localhost:5000/;
            proxy_redirect     off;
            proxy_http_version 1.1;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_set_header   X-Forwarded-Host $server_name;

            # Sets the maximum allowed size of the client request body.
            client_max_body_size    10m;
            # Sets buffer size for reading client request body.
            client_body_buffer_size 128k;
            # Defines a timeout for establishing a connection with a proxied server.
            proxy_connect_timeout   90;
            # Sets a timeout for transmitting a request to the proxied server.
            proxy_send_timeout      90;
            # Defines a timeout for reading a response from the proxied server.
            proxy_read_timeout      90;
            # Sets the number and size of the buffers used for reading a response from the proxied server.
            proxy_buffers           32 4k;
         }
}

Thank you.
```

**Comment by wfurt** [comment]
Where the .NET comes into picture @jindovu? It seems like this is problem with nginx so you should probably ask there. 
If there is Kestrel behind the nginx, you should collect logs and ask on aspnetcore repo.

**Comment by jindovu** [comment]
- yes, I put wrong place, the problem I just guess came from .net core, seem like it's not know the root of web that's why it always display 404 not found and I created one page html & folder contains images only for testing the configuration Nginx is working fine (Images display is ok), when switch to .net core it's always display 404 and I don't know how to fix it

**Comment by karelz** [comment]
@jindovu does a HelloWorld app work for you well? What is different on your app that breaks it? Can you create isolated repro and file issue in appropriate repo please?

**Comment by jindovu** [comment]
Thank you for your support, I have been resolved problem with config below
![image](https://user-images.githubusercontent.com/19401173/125395446-68c1c280-e3d5-11eb-9538-ddeae80ddfbc.png)

**Comment by karelz** [comment]
OK, closing as unrelated to .NET Core.
Looks like a problem in config of your server.
