### ISSUE TITLE
Unsafe.SizeOf<T>() causes an additional mov over sizeof(T)

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#55472]
### Description

In some cases, `Unsafe.SizeOf<T>` produces an additional `mov` over `sizeof(T)` (both over not compile time known types). 

### Configuration

Sharplab Core CLR v5.0.721.25508

### Regression?

No idea.

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBhCfAB1YAbGFADKIgG6swMXAG4AsACgy5UQAtsUPgBlsweszYdFS5cQDMlKknLNc2AGYxKAJnIAVWRmUBvZeSB5ADaAFKsGADiMEwi0gAUGACefDAQjvGsLACU2QC6AUGW1rbAEBCC5ACCADweAHzxwEkYMMF55M2tuNnkAO7qIi4e5CB2TPjYTNgA5jAAJoWB/kpBa5QA7J0tsjQ6MTMY6uQ15LisAF5pGR7ZpmsAvkvkz2ER0bFQCcmp6Zk5+WexWopXKlQAQnVGl02h0YT1+oNYJ5RuNJtM5otVkEVusilt4XsDkcTuQAKpMBzOGiiS4wADyjih8TuzyeSgeQA===)

**Comment by GrabYourPitchforks** [comment]
@jkotas There's an existing proposal to move the `Unsafe` type down to corelib. Might this issue be resolved as a side effect of that work?

**Comment by jkotas** [comment]
> proposal to move the Unsafe type down to corelib.

... and turn it into JIT intrinsic. I agree that turning Unsafe into JIT intrinsic is likely to fix this issue.

**Comment by AndyAyersMS** [comment]
Also likely to be fixed if/when we implement forward sub (#6973)
