### ISSUE TITLE
Test failure: Assertion failed 'op1->IsLocal()' in win-x64

### ISSUE THREAD

**Issue by mateoatr** [dotnet/runtime#55512]
[runtime-coreclr jitstress2-jitstressregs 20210711.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1231826&view=ms.vss-test-web.build-test-results-tab)

We are hitting the following assert on win-x64:

https://github.com/dotnet/runtime/blob/633e04481f21a23d567cf49177f76fbef3a34cfe/src/coreclr/jit/codegenxarch.cpp#L4472-L4476

Log example:

```
> C:\h\w\B1BD097E\w\B17B097F\e\JIT\Directed\nullabletypes\boxunboxinterface_ro\boxunboxinterface_ro.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Directed._nullabletypes_boxunboxinterface_ro_boxunboxinterface_ro_._nullabletypes_boxunboxinterface_ro_boxunboxinterface_ro_cmd() in JIT.Directed.XUnitWrapper.dll:token 0x6000272+0x284
      Output:
        
        Assert failure(PID 5588 [0x000015d4], Thread: 1172 [0x0494]): Assertion failed 'op1->IsLocal()' in 'Helper:Compare(System.Nullable`1[ImplementTwoInterfaceGen`1],ImplementTwoInterfaceGen`1[Int32]):bool' during 'Generate code' (IL size 25)
        
            File: D:\workspace\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 4476
            Image: C:\h\w\B1BD097E\p\corerun.exe
```

@BruceForstall

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib New assertion on xarch

**Comment by BruceForstall** [comment]
A lot of failures in "CoreCLR windows x64 Checked jitstressregs8_x86_noavx" here:

https://dev.azure.com/dnceng/public/_build/results?buildId=1231870&view=ms.vss-test-web.build-test-results-tab&runId=36681690&paneView=debug

**Comment by BruceForstall** [comment]
@kunalspathak Looks like only JitStressRegs=8 is affected. Can you look?

**Comment by kunalspathak** [comment]
I see that it succeeded in [recent jitstressregs run](https://dev.azure.com/dnceng/public/_build/results?buildId=1231643&view=results). I also synced-up main and don't see it reproing anymore.

**Comment by kunalspathak** [comment]
My bad...I didn't set the right environment variables. I can see it is still reproing.

**Comment by kunalspathak** [comment]
Got introduced from https://github.com/dotnet/runtime/pull/55045

![image](https://user-images.githubusercontent.com/12488060/125358681-11145000-e31e-11eb-8275-91dd3d88c7db.png)
