### ISSUE TITLE
Error "The program can't start because api-ms-win-core-winrt-l1-1-0.dll is missing" after publishing .net 6 app on Windows 7

### ISSUE THREAD

**Issue by littlehoneybunnytuttifruttipumpkinpie** [dotnet/runtime#55514]
Trying to publish somewhat basic .net 6 web app that runs just fine after "Build", but after publishing it with "Self-Contained" deployment and trying to run the executable, the app shows the error "The program can't start because api-ms-win-core-winrt-l1-1-0.dll is missing"

![image](https://user-images.githubusercontent.com/20084989/125215263-c805c280-e26f-11eb-8764-34cb3ae81725.png)

![image](https://user-images.githubusercontent.com/20084989/125215285-e8ce1800-e26f-11eb-96bf-506b1266f949.png)

Also getting a different error after changing deployment from "Self-Contained" to "Framework-Dependent".
In such case the app cannot be published at all and shows "An error has occured" message (notice "occured" spelling).

![image](https://user-images.githubusercontent.com/20084989/125215466-6abe4100-e270-11eb-93c7-394a2415be3f.png)

The contents of the log file is as follows:
==================
2021/07/11 5:48:22 PM
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Build failed. Check the Output window for more details.<---

Microsoft.WebTools.Shared.Exceptions.WebToolsException: Build failed. Check the Output window for more details.
===================

==================

I'm fairly new to .Net Core & .Net 5/6, so may be doing something wrong. I'm also aware I'm using experimental features with AOT publishing.

### Further technical details
- ASP.NET 6 Preview (Version:   6.0.100-preview.5.21302.13)
- Windows 7 Pro
- Visual Studio Community 2019

**[EDIT]:**
Regarding first issue above (error), I searched my OS drive for "api-ms-win-core-winrt-l1-1-0.dll" and found one, and now the app has a new error "{program name} stopped working".

![image](https://user-images.githubusercontent.com/20084989/125239249-4036ad00-e29d-11eb-8fc6-6b3cc23e85c8.png)

Regarding 2nd issue above with publishing, I noticed the reason for the last error in VS:
"Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app."
This somewhat explains that I need to review my settings and I can consider this issue resolved. (should I edit this post and remove that issue?)

**Comment by agocke** [comment]
Single-file publishing is not currently supported for Windows 7. We need to remove the checkbox for that environment.

**Comment by jaedan** [comment]
Currently building with single file and a target of win7-x64 builds successfully, but it fails to run with the error above. On the official support page, .net 6 still claims to support windows 7, but it's clear that in reality that support does not include all features, such as this one.

Since windows 7 is still supported with extended security updates, that means we need to continue to support it in our applications. For applications deployed as a single binary, this bug becomes a major problem.

I'd like to see this addressed. Deployment-level features such as this can't just drop windows 7 until the extended support contracts are expired.

Barring an actual fix, at a minimum targeting windows 7 for single file must fail to build, since it does not actually work.

**Comment by sgf** [comment]
In fact, there are a lot of servers running on Windows server 2008 and a large number of users are using Windows 7.
I am not forcing the .net team to support Win7&Server2008

It is that when you propose that you do not support it, customers will increase the cost and investment of system migration. When our solution competes with other languages (such as go and rust), they can smoothly solve this low-level system compatibility problem. , And our dear .net can't do it.
So why should customers choose us.

Even if most customers have updated to the new system, but small number of customers are still a market share that cannot be ignored. Microsoft is rich in wealth and disagrees, but we are a small company with different conditions and difficult survival.
think about it.


What is even more incomprehensible is that windows is Microsoft's own product, and both go and rust can do it. However, the .net team has always been reluctant to support their own product, even though the product is outdated. But as a cross-platform platform, isn't the goal to code once and run everywhere.

GO-Lang:Yes,We can.No dependencies.
Rust-Lang:Yes,We can,No dependencies.
.net(F#,C#,VB.net): Sorry,We do not support windows7&windows server 2008,Please update your operating system.

**Comment by agocke** [comment]
To be clear, Win7 *is* supported in .NET 6, just not for the "single-file publishing" feature. This feature happens to be very difficult to implement for win7, and therefore didn't make the cut

**Comment by Thog** [comment]
> To be clear, Win7 _is_ supported in .NET 6, just not for the "single-file publishing" feature. This feature happens to be very difficult to implement for win7, and therefore didn't make the cut

It should be noted that single file publishing used to work fine on .NET 5 on Windows 7.
This behavior should be at least documented and be considered a regression in my opinion.

**Comment by sukney** [comment]
Microsoft's own products don't support itself, and it's too worrying

**Comment by agocke** [comment]
We've found a workaround that we think will allow single-file to function without the shims, so this should now work.

Please note, however, that Windows 7 is out of standard support. and has been since 2020.
