### ISSUE TITLE
AOT error building dotnet/performance benchmarks

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#55515]
Command: 

``` ~/workspace/runtime-clean/dotnet.sh run -c Release --runtimeSrcDir ~/workspace/runtime-clean/ --runtimes wasm --aotcompilermode wasm --framework net6.0```

I get a bunch of AOT errors like:

```/Users/naricc/workspace/runtime-clean/src/mono/wasm/build/WasmApp.Native.targets(414,5): warning : Unable to compile method 'void Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl:ResetWindowsHeapTracingFlags (string,bool)' due to: 'Method not found: void Microsoft.Win32.RegistryKey.DeleteValue(string)'. [/Users/naricc/workspace/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/Job-LPKKXK/BenchmarkDotNet.Autogenerated.csproj]```

Full output with MONO_LOG_LEVEL=deug here: https://gist.github.com/naricc/4d775852b6628957dc63756000e92e62

I tried modifying the generated project use interpreter, with trimming enabled, and the project ran.

**Comment by naricc** [comment]
This doesn't seem to be happening any more.

**Comment by vargaz** [comment]
Seems to be some kind of linker/build problem:
Sigil.dll references System.Runtime.InteropServices.PInvoke which is not part of the build

**Comment by radekdoulik** [comment]
This should be fixed by https://github.com/dotnet/performance/commit/de17d6e8bf6a1620dfb4dd76e96affba8977b446
