### ISSUE TITLE
x86 Linux build fails

### ISSUE THREAD

**Issue by t-mustafin** [dotnet/runtime#55521]
x86 Linux build fails with message:
```
  /home/tmustafin/dotnet/runtime/src/coreclr/vm/i386/jithelp.S:314:21: error: cannot use more than one symbol in memory operand
      add eax, offset _GLOBAL_OFFSET_TABLE_+1
                      ^
  vm/wks/CMakeFiles/cee_wks_core.dir/build.make:3330: recipe for target 'vm/wks/CMakeFiles/cee_wks_core.dir/__/i386/jithelp.S.o' failed
```
Problem occures on https://github.com/dotnet/runtime/blob/738b09bee351a60f1a7c037d5968b1e4145f6c82/src/coreclr/vm/i386/jithelp.S#L395.
Build command:
```
sudo ./eng/common/cross/build-rootfs.sh x86 bionic
ROOTFS_DIR=`pwd`/.tools/rootfs/x86 ./build.sh --cross --clang9 --arch x86 --configuration Release --subset clr.runtime+clr.corelib+clr.iltools+clr.dactools+clr.jit /p:EnableSourceLink=false
```

cc @janvorli @jkotas @alpencolt @gbalykov

**Comment by janvorli** [comment]
I've just found that it is a clang issue. The build works fine with clang 10, but not with clang 9 for some reason. @t-mustafin would using clang-10 be an option for you? The clang 9 seems to be somehow confused by the instruction. Even with just `add eax, offset _GLOBAL_OFFSET_TABLE_`, it complains the same way.

**Comment by janvorli** [comment]
It seems to be a known issue in clang, apparently fixed in clang >=10:
https://bugs.llvm.org/show_bug.cgi?id=32530

**Comment by alpencolt** [comment]
@janvorli we use old clang-5 for production builds. Thank you for information, we'll check whether this bug exists on other clang versions.

**Comment by janvorli** [comment]
I have a workaround that works on the older clangs as well, just verifying that it generates the expected code.

**Comment by janvorli** [comment]
It seems to generate proper code, the diff is:
```diff
diff --git a/src/coreclr/vm/i386/jithelp.S b/src/coreclr/vm/i386/jithelp.S
index dc56da1d177..4f227c9cf60 100644
--- a/src/coreclr/vm/i386/jithelp.S
+++ b/src/coreclr/vm/i386/jithelp.S
@@ -392,7 +392,9 @@ LEAF_ENTRY JIT_WriteBarrier_Callable, _TEXT
 1:
     pop     eax
 2:
-    add     eax, offset _GLOBAL_OFFSET_TABLE_+1 // (2b - 1b)
+.att_syntax
+    addl     $_GLOBAL_OFFSET_TABLE_+(2b-1b), %eax
+.intel_syntax noprefix
     mov     eax, dword ptr [eax + C_FUNC(JIT_WriteBarrierEAX_Loc)@GOT]
     xchg    eax, dword ptr [esp]
     ret
```

**Comment by t-mustafin** [comment]
@janvorli  Thanks, it works for me with clang9 and clang5.

**Comment by alpencolt** [comment]
@janvorli btw as I see clang11 is last supported version. Are there plans for adding clang12 support?

**Comment by janvorli** [comment]
@alpencolt yes, I'd like to support the latest clang releases. I haven't monitored the llvm releases recently, so I've missed the fact that there is a version 12 already. Have you tried it and found issues with it?

**Comment by alpencolt** [comment]
It seems it was released in April. We haven't tried it yet but want to update our toolchain and I check which version fits more.
If you're ok with using latest one we can check clang12 on ARM close to autumn.

**Comment by janvorli** [comment]
Usually moving to a new version just works. In some cases, it caused build breaks in the past that we needed to fix.
