### ISSUE TITLE
API that returns framework version

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#55522]
In the past we've refrained from providing an API that provides the version information of the .NET platform. The reason being that we know developers can't be trusted to write version checks correctly. For operating system detection we provide APIs in the form `OperatingSystem.IsXxxVersionAtLeast(int major, int minor)` where a developer can ask for the minimum version. This pattern also allows the platform to lie and treat one platform as the superset of another, which is what we do for Mac Catalyst, for instance.

At the same time, we needed a mechanism for exposing the framework version for diagnostic purposes. So we ended up with the [FrameworkDescription](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=net-5.0) API:

```C#
namespace System.Runtime.InteropServices
{
    public static class RuntimeInformation
    {
        public string FrameworkDescription { get; }
    }
}
```

This API intentionally doesn't make any guarantees on the format of the string and we generally discourage developers from parsing it.

Now the accessibility team reached out and asked us to expose the .NET platform version so that it can be returned to screen readers via the [FrameworkId](https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids) property. This property enables screen readers to make assumptions about the UI structure. Today, it returns strings like "WPF" and "WinForms". However, .NET Framework and .NET Core are drifting further apart which is why they would also like to know which flavor of WinForms and WPF the application is using, which also includes the platform version. To quote @DaveTryon:

> Our desired outcome is that we can programmatically prevent rules from running on .NET Framework (where accessibility bugs are not expected to be fixed), while still running them on .NET Core (where accessibility bugs are eventually expected to be fixed).
>
> There's a subsequent scenario: Suppose that .NET Core version X contains two accessibility bugs, and that we have rules for each bug. One of these bugs gets fixed in .NET Core version Y, and the other gets fixed in .NET Core version Z. In an ideal world, the rule detecting the first bug would be enabled for all versions Y or newer; the rule detecting the second bug would be enabled for all versions Z or newer. This scenario only seems possible if the version can be both parsed and compared in some way that won't break every time a new version of .NET Core is released.

Please note that screen readers do not have have the capability to call APIs in the inspected process; they entirely rely on the data exposed via the UI automation infrastructure. Hence, our normal pattern of "we don't tell you a version number, you ask us" isn't workable.

There are two options:

1. We use `RuntimeInformation.FrameworkDescription`. In this world, we'd need to guarantee the format of the string moving forward and ensure it remains parseable.

2. We introduce a new API that returns the framework version, e.g. `RuntimeInformation.FrameworkVersion`. This new API would only be available on .NET Core and thus wouldn't need to indicate whether it's .NET Framework or .NET Core.

/cc @merriemcgaw  @JeremyKuhne @DaveTryon

**Comment by eerhardt** [comment]
Now that we have a "reasonable" versioning story, is `Environment.Version` not good enough for this going forward? We use it in our tests in a few places:

https://github.com/dotnet/runtime/blob/a31d0d57eff985a68828c37775d103b91032f786/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L25

https://github.com/dotnet/arcade/blob/7f52af24016a4b749a2c1f219105c0f5a7100028/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs#L95-L96

And even WCF uses it:

https://github.com/dotnet/wcf/blob/d01878ef604038bed1261a1fe55c9e3d89ebd390/src/Common/src/Internals/System/Runtime/WcfEventSource.cs#L23-L26

**Comment by terrajobst** [comment]
Can't believe I completely forgot about `Environment.Version` 🤦

Yes, that might be reasonable!

**Comment by terrajobst** [comment]
@eerhardt does this work for single file? It looks it would return the user's assembly version in that case.

**Comment by jkotas** [comment]
Yes, it works for single file. Single preserves assembly identities. The API always returns CoreLib version.

**Comment by terrajobst** [comment]
* We concluded we don't need a new API, we'll just use `Environment.Version` which exposes the platform version
* WinForms/WPF can decide to support an `AppCompat` switch so that both that if the new string returned via the UIA's `FrameworkId` property breaks people, they can get back the old behavior.

**Comment by jkoritzinsky** [comment]
@terrajobst can we close this issue if we don't need to add a new API?

**Comment by terrajobst** [comment]
Yep
