### ISSUE TITLE
Socket.Select on linux gives wrong result when fails to connect

### ISSUE THREAD

**Issue by jinek** [dotnet/runtime#55538]
### Description

When running `Socket.Select` against failing port it gives different result on Windows and on Linux. Futhermore, it seems on Linux the result does not make any sense.

This code can be used to reproduce the issue:

```c#
        private static void Main()
        {   
            using var socket = new Socket( SocketType.Stream, ProtocolType.Tcp)
            {
                Blocking = false
            };
            
            try
            {
                socket.Connect("127.0.0.1", 41324); 
            }
            catch (SocketException socketException) when (socketException.SocketErrorCode==SocketError.WouldBlock)
            {
                IList lst = new List<Socket> {socket};
                IList lst2 = new List<Socket> {socket};
                IList lst3 = new List<Socket> {socket};
                Socket.Select(lst,lst2,lst3,10000000);
                Console.WriteLine($"Result: {socket.Connected} {lst.Count} {lst2.Count} {lst3.Count}");
            }
        }
```

On Linux it says
```
Result: True 1 1 1
```

But on windows (looks like correct)
```
Result: False 0 0 1
```
### Configuration

* netcoreapp3.1
* Ubuntu 18 and Windows 10

### Other information

If I try to connect with Blocking = true, then it gives SocketException both on Windows and Linux

Looks like related to https://github.com/dotnet/runtime/issues/920

**Comment by karelz** [comment]
@tmds any idea what might go on here?

**Comment by tmds** [comment]
The `1 1 1` is what we get back from Linux, so this is a platform difference. I don't think we can/should change this.

The `True` is the result of:

https://github.com/dotnet/runtime/blob/5b0c6dd5756eea63a57b1f69b182f7386da0f631/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L435-L440

This is missing reading out the actual result from the async connect using `getsockopt` with `SO_ERROR`.

The next operation that gets performed on the socket will throw (because the socket is actually not connected) and update the state to not connected. So this issue gets masked by that.

**Comment by jinek** [comment]
Little OOT: I understand that we use poll rather than select, but I've just tried to see what would be result of select. What surprises me is that select does not mark socket as having an error, but may be I'm doing something wrong here.

```
Blocking: 0
Connect: -1
Select: 2
1 1 0
```

The application is:
```
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <errno.h>
#include <sys/utsname.h>
#include <sys/ioctl.h>
#include <sys/poll.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <cstring>
#include <arpa/inet.h>

int main() {

    struct sockaddr_in address;

    int theSocket = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
    int on=1;
    std::cout << "Blocking: " << ioctl(theSocket, FIONBIO, (char *)&on) << std::endl;
    address.sin_family = AF_INET;
    address.sin_port = htons(21431);
    address.sin_addr.s_addr = inet_addr("127.0.0.1");

    std::cout << "Connect: " << connect(theSocket, (struct sockaddr *)&address, sizeof (address)) << std::endl;

    struct timeval tv;
    fd_set readSet;
    fd_set writeSet;
    fd_set errorSet;
    FD_ZERO(&readSet);
    FD_ZERO(&writeSet);
    FD_ZERO(&errorSet);
    FD_SET(theSocket, &readSet);
    FD_SET(theSocket, &writeSet);
    FD_SET(theSocket, &errorSet);
    tv.tv_sec = 10;
    tv.tv_usec = 0;
    std::cout << "Select: " << select(theSocket + 1, &readSet, &writeSet, &errorSet, &tv) << std::endl;

    std::cout << FD_ISSET(theSocket , &readSet) << " "
              << FD_ISSET(theSocket , &writeSet) << " "
              << FD_ISSET(theSocket , &errorSet) << std::endl;
    return 0;
}


```

**Comment by jinek** [comment]
I've also checked the mentioned condition in mono https://github.com/mono/mono/blob/main/mcs/class/System/System.Net.Sockets/Socket.cs#L507 It checks for error additionally after the write check.

**Comment by tmds** [comment]
@jinek how does this behave on Windows when you add a `Thread.Sleep(1000)` at the start of the `catch` block? Is `Connected` still `false`?

**Comment by tmds** [comment]
> we want to know that we can connect or we can not connect to an endpoint, and that must be done within a timeout.

This works cross-platform on all versions of .NET:

```cs
var checkWrite = new List<Socket> { socket };
var checkError = new List<Socket> { socket };
Socket.Select(null, checkWrite, checkError, timeout);
if (checkError.Count > 0)
{
    Console.WriteLine("Connect failed");
}
else if (checkWrite.Count > 0)
{
    Console.WriteLine("Connect successful");
}
else
{
    Console.WriteLine("Timeout");
}
```

**Comment by antonfirsov** [comment]
I will try to chat with @geoffkizer on his opinion regarding being platform compatible VS consistent across multiple platforms. May reopen this if we conclude that we can do a better job here.
