### ISSUE TITLE
Non-deterministic but frequent crashes from System.Linq.Expressions.Tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#55536]
Crash stacktrace:
```
00 (Inline) --------     coreclr!Stub::HasExternalEntryPoint [D:\workspace\_work\1\s\src\coreclr\vm\stublink.h @ 720] 
01 (Inline) --------     coreclr!Stub::GetEntryPointInternal [D:\workspace\_work\1\s\src\coreclr\vm\stublink.h @ 764] 
02 (Inline) --------     coreclr!Stub::GetEntryPoint [D:\workspace\_work\1\s\src\coreclr\vm\stublink.h @ 609] 
03 0738c640 72bcc90a     coreclr!COMDelegate::BindToMethod+0x100 [D:\workspace\_work\1\s\src\coreclr\vm\comdelegate.cpp @ 1125] 
04 0738c700 08c9fd93     coreclr!COMDelegate::BindToMethodInfo+0x11a [D:\workspace\_work\1\s\src\coreclr\vm\comdelegate.cpp @ 1059] 
05 0738c71c 08c9fc68     System_Private_CoreLib!System.Delegate.CreateDelegateInternal(System.RuntimeType, System.Reflection.RuntimeMethodInfo, System.Object, System.DelegateBindingFlags)+0x29e285b*** WARNING: Unable to verify checksum for System.Private.CoreLib.dll
```

Here's the .md file with the various runfo details:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55499-merge-76bc4fdcdfe24d4e9c/System.Linq.Expressions.Tests/how-to-debug-dump.md?sv=2019-07-07&se=2021-08-01T20%3A15%3A12Z&sr=c&sp=rl&sig=czdFtHQqe0OW7J%2BSIH81r7kABJ4%2FH%2F1v1T%2F4LhwnZ9g%3D

**Comment by jkotas** [comment]
The problem is that both the ShuffleThunk and some other JITed method occupy same memory block.

```
0:010> ? pShuffleThunk
Evaluate expression: 113897496 = 06c9f018
0:010> !ip2md 06c9f018
MethodDesc:   024d8cd0
Method Name:          System.Linq.Expressions.Tests.TypeEqual.CannotReduce()
```

@janvorli I think it is very likely caused by your W^X PR. Could you please take a look?

**Comment by janvorli** [comment]
I am taking a look.

**Comment by stephentoub** [comment]
Thanks, @janvorli.

**Comment by danmoseley** [comment]
Nice to see the generated how-to-debug-dump.md being useful.

**Comment by janvorli** [comment]
@danmoseley I was actually very pleasantly surprised by the WinDbg ability to investigate debug dumps from Linux including local variable values that I've discovered thanks to this .md file.
