### ISSUE TITLE
[iOS] PosixSignalRegistrationTests: InvalidOperationException : No data found for <test name>

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#55563]
The following library tests fail with `System.InvalidOperationException : No data found` on the apple CI staging lanes:  

- System.Tests.PosixSignalRegistrationTests.Create_ValidSignal_Success
- System.Tests.PosixSignalRegistrationTests.Create_UninstallableSignal_Throws
- System.Tests.PosixSignalRegistrationTests.SignalHandlerCalledForKnownSignals
- System.Tests.PosixSignalRegistrationTests.Dispose_Idempotent

https://dev.azure.com/dnceng/public/_build/results?buildId=1234380&view=logs&jobId=accacb66-0a14-52ef-4079-6344686d9d4c

cc @steveisok

**Comment by steveisok** [comment]
Didn't we skip a bunch already? Should these tests actually work on iOS?  If not, let's skip.

**Comment by MaximLipnin** [comment]
> Didn't we skip a bunch already? Should these tests actually work on iOS? If not, let's skip.

Previously, it was RemoteExecutor-related issue https://github.com/dotnet/runtime/issues/55328

**Comment by jkotas** [comment]
> System.InvalidOperationException : No data found

This is xunit limitation. xunit does not like empty `MemberData`.

**Comment by stephentoub** [comment]
> This is xunit limitation. xunit does not like empty MemberData.

Ugh, that's right (and annoying).  I'll take care of it.
