### ISSUE TITLE
Reading JSON Documents from a Stream (System.Text.Json)

### ISSUE THREAD

**Issue by no1melman** [dotnet/runtime#55561]
So I had the need to read objects from a stream, the most rudimental way of thinking about it is

```csharp

await using var stream = new MemoryStream() // obviously doesn't have to be this kind of stream, could be pipes or something

foreach(var item in Items)
{
    await stream.Write(JsonSerializer.SerializeToUtf8Bytes(item));
}

// --- So above would be some kind of conceptual "Server"

```

You can't read from this stream by simply doing this:

```
var item = await JsonSerializer.DeserializeAsync<Item>(utf8Stream);
```

Because that would entail having to read to the end of the file (that's what it looks like in the source code), and if there were anymore objects in than just the one, it will fail.

So I created this [JsonStreamReader](https://gist.github.com/no1melman/e66dc6f8a4ec4efb57731db444ddeeb9)

The interesting part is having to new up a UTF8Reader each time:

https://gist.github.com/no1melman/e66dc6f8a4ec4efb57731db444ddeeb9#file-jsonstreamreader-cs-L88-L90

My original solution was done so you didn't, but for some reason, it felt like the reader didn't "consume" the final brace, so when you get it to read again, it says "`}` is an unknown json string" or something similar.

So I was wondering, should the utf8 reader just consume this final thing - or allow the user to "forward" its position in the stream to carry on reading?

It's also pointed out in the source code of the Utf8 Reader that hitting `ReadCore` or this https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.ReadCore.cs is actually expensive. So I guess, mine could be? although I don't really understand the context of that.

**Comment by eiriktsarpalis** [comment]
> Because that would entail having to read to the end of the file (that's what it looks like in the source code), and if there were anymore objects in than just the one, it will fail.

.NET 6 STJ will include support for IAsyncEnumerable which can be used for streamed serialization and deserialization. In particular, the dedicated [`JsonSerializer.DeserializeAsyncEnumerable` method](https://github.com/dotnet/runtime/blob/4e9d89ac0a333b86867cf898b9ad438d324c66d1/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs#L344-L360) can be used to deserialize root-level JSON arrays in a streaming manner.

Hope this covers your use case.

cf. #50778

**Comment by layomia** [comment]
@no1melman it looks like your scenario has been covered, so I'll close this issue. Please let us know if you have further feedback.
