### ISSUE TITLE
TryGetNameInfo_LocalHost tests failing with HostNotFound

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#55576]
In NameResolutionPalTests, using last night's sources, these are all failing for me on Windows 10 21H1

TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo(true|false)
TryGetAddrInfo_LocalHost_TryGetNameInfo
TryGetNameInfo_LocalHost_IPv6 
with
`Assert.Equal() Failure\r\nExpected: Success\r\nActual:   HostNotFound`

I can ping localhost from the shell. Not sure how to troubleshoot further.

**Comment by danmoseley** [comment]
The next step if I looked further might be to create a repro in C. I won't have time to look myself at least for a while, and it's not a problem to ignore these 4 tests for now if it's just me.

**Comment by karelz** [comment]
@danmoseley is it 100% repro on your machine? I don't think we saw it anywhere else ...

**Comment by danmoseley** [comment]
I'll close until I have time to dig in further.

**Comment by danmoseley** [comment]
It seems to repro on my machine. Is there anything I can gather to help

**Comment by danmoseley** [comment]
TryGetNameInfo_LocalHost_IPv6 and TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo fail here
```
string name = NameResolutionPal.TryGetNameInfo(new IPAddress(new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 }), out error, out nativeErrorCode);
```
it appears that on this machine, it cannot resolve this to localhost.  

I noticed this line in another file which sounds like this:
https://github.com/dotnet/runtime/blob/f5ec451f88d482a658fd3f387a808650fbaf3425/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TestSettings.cs#L22

I haven't done anything special to my machine. presumably it's configured a little differently. @wfurt is there a way to tell that this won't work, so it can skip?

**Comment by wfurt** [comment]
What `ipconfig /all` gives you @danmoseley ?

**Comment by danmoseley** [comment]
Sent offline. Also,
```
C:\>ping 0:0:0:0:0:0:0:1

Pinging ::1 with 32 bytes of data:
Reply from ::1: time<1ms
```

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/pull/63259#issuecomment-1007750010
