### ISSUE TITLE
ExchangeAlgorithmType enum is missing 44550

### ISSUE THREAD

**Issue by omghb** [dotnet/runtime#55570]
### Description

- ExchangeAlgorithmType enum is missing 44550
- I stumbled about this as I logged `SslStream.KeyExchangeAlgorithm`
```C#
Console.WriteLine("Key exchange: {0} strength {1}", stream.KeyExchangeAlgorithm, stream.KeyExchangeStrength);
```
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.keyexchangealgorithm?view=net-5.0

### Configuration

.NET 5.0

### Regression?

No, was never included.

### Other information

See also [Archived Forums > .NET Framework Class Libraries > SslStream.KeyExchangeAlgorithm 44550](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d0298622-a7cc-40e8-a4bf-8b74696ff548/sslstreamkeyexchangealgorithm-44550?forum=netfxbcl)

**Comment by karelz** [comment]
That would be missing in [`System.Security.Authentication.ExchangeAlgorithmType`](https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.exchangealgorithmtype?view=net-5.0) ... moving to Security area ...

**Comment by vcsjones** [comment]
I noticed that in the Unix PAL for `KeyExchangeAlgorithm` that `DiffieHellman` is used for ECDHE suites, whereas SChannel uses the unnamed enum value.

https://github.com/dotnet/runtime/blob/b2a670b5421af99edad62f8cb5ae172cd8d05030/src/libraries/System.Net.Security/src/System/Net/Security/TlsCipherSuiteData.Lookup.cs#L1833-L1836

My understanding of `ExchangeAlgorithmType.DiffieHellman` is that it is for FF-DH, not ECDHE. If a new enum value is added for ECDH then it would perhaps make sense to change the Unix PAL lookup to use the new enum instead of mixing it in with `DiffieHellman`.

**Comment by bartonjs** [comment]
@karelz The enum is part of System.Net.Primitives and is logically part of SslStream, namespace notwithstanding.

**Comment by rzikm** [comment]
Looks like we explicitly group all Diffie-Hellman variants together to a single enum value (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/System/Net/Security/TlsCipherSuiteNameParser.ttinclude#L75-L96), we can do the same on Windows for consistency, or add new enum values and use them everywhere.

**Comment by wfurt** [comment]
triage: we should add new enum and fix up the mapping.

**Comment by rzikm** [comment]
Triage: It would be good to update all 3 enum types pertaining to the cipher suite properties to stay current and to report more detailed information for users who use the properties for auditing purposes.

**Comment by rzikm** [comment]
I tried looking into adding more values so that we are on par with what we get from TLS ciphersuites in

**Comment by bartonjs** [comment]
> do we care about using the same numbers as underlying windows crypto does?

My gut says the numbers are the same so that no one had to write a mapping table; a convenience that only made sense when the framework was (largely) Windows-only.  So, "no" (but we can't change any of the existing numbered things).

**Comment by wfurt** [comment]
We had similar problem with https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.protocolfamily?view=net-8.0 There are some Linux specific so we put them to the end so they are less likely to collide with Windows numbering. 
If Windows will ever supports them we will need to add some mapping like we do for other platforms.

**Comment by rzikm** [comment]
Moving to 10.0.0 milestone as this is not critical to 9.0.0, but still would be nice to get it in.

**Comment by rzikm** [comment]
Since #100361, the plan is to obsolete the enum, closing as won't do.
