### ISSUE TITLE
Updating NuGet section of build instructions

### ISSUE THREAD

**Issue by ezephir** [dotnet/runtime#5557]
Right now, the NuGet section of the build instructions doesn't work because NuGet and package versions are both too old. I'd like to update this section because it is blocking validation of the instructions on OS X (#4133).

I'd like to do the following:
- Change the package source to `https://dotnet.myget.org/F/dotnet-core/api/v3/index.json`
- Replace the current package versions with the following project.json:

```
{
  "frameworks": {
    "dnxcore50": {}
  },

  "dependencies": {
    "System.Console": "4.0.0-*",
    "System.Diagnostics.Contracts": "4.0.1-*",
    "System.Diagnostics.Debug": "4.0.11-*",
    "System.Diagnostics.Tools": "4.0.1-*",
    "System.Globalization":  "4.0.11-*",
    "System.IO":  "4.1.0-*",
    "System.IO.FileSystem.Primitives": "4.0.1-*",
    "System.Reflection": "4.1.0-*",
    "System.Resources.ResourceManager": "4.0.1-*",
    "System.Runtime": "4.1.0-*",
    "System.Runtime.Extensions": "4.1.0-*",
    "System.Runtime.Handles": "4.0.1-*",
    "System.Runtime.InteropServices": "4.1.0-*",
    "System.Text.Encoding": "4.0.11-*",
    "System.Text.Encoding.Extensions": "4.0.11-*",
    "System.Threading": "4.0.11-*",
    "System.Threading.Tasks": "4.0.11-*"
  }
}
```

These are the newest versions listed in that feed.
- Update to either NuGet v3+ (which seems to be required for downloading the 4.0.11 packages for some reason) or switching to dotnet cli.

I'm looking for some feedback about how to proceed. To start:
- **Is this a sane thing to do**?
- **Did I pick the right versions**?
- **Are floating package versions okay**? If the instructions continue to use NuGet, this requires version 3.4 of the command line tool with is still a release candidate. The version of dotnet cli downloaded by the build process seems to work okay.
- **Why are so many dependencies specified for the "Hello World" example?** Since they don't seem to be used directly in the example, my intuition would want to specify a minimal set and let dependency management resolve the rest.

**Comment by jkotas** [comment]
Build instructions have changed a lot since 2016. This issue is no longer relevant.
