### ISSUE TITLE
Json serialization format for Datetime

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#556]
```c#
var a= new DateTime(2019,12,5,1,2,3,44);
a.ToString("O");

// Output: 2019-12-05T01:02:03.0440000

System.Text.Json.JsonSerializer.Serialize(a, typeof(DateTime));

// Output "2019-12-05T01:02:03.044"
```

Should in second case "O" format be used with "fffffff"?

**Comment by Clockwork-Muse** [comment]
Without having looked at the code, it's probably truncating to the last non-zero digit (or to the nearest digit triple - millis, micros, etc).  Since the amount is/_should be_ exact, there's no information lost here.

**Comment by layomia** [comment]
The underlying `Utf8JsonWriter` writes DateTime and DateTimeOffset instances according to the extended ISO 8601 profile (not roundtrippable "O", which is too strict on deserialization). Trailing second fraction zeros are omitted, so the writer produces the smallest output required to roundtrip. See some [test data](https://github.com/dotnet/runtime/blob/7ea817f30755079e44616b60bc09f0bb6857d6cd/src/libraries/System.Text.Json/tests/JsonDateTimeTestData.cs#L234-L250) showing how the writer trims. 

I've filed an issue to add this information to the [official docs](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#support-for-formatting): https://github.com/dotnet/docs/issues/16128.
