### ISSUE TITLE
[Question] What other compilers is RyuJIT compared against?

### ISSUE THREAD

**Issue by alexcovington** [dotnet/runtime#55603]
I have a general question, wasn't sure where the best place to post this. Please let me know if I can ask this question in more appropriate place.

Are there other compilers that RyuJIT is compared against, specifically regarding codegen? For example, MSVC/GCC/Clang are all typically compared against each other when looking at the quality of generated code. While it wouldn't be exactly a 1-to-1 comparison, I'm wondering if there are any similar comparisons done between RyuJIT and other compilers, such as MSVC or Clang.

**Comment by JulieLeeMSFT** [comment]
CC @BruceForstall

**Comment by BruceForstall** [comment]
There are several options. For managed code, RyuJIT can sometimes be compared against JIT32 (the previous JIT, used for .NET Framework x86), or JIT64 (the previous JIT, used for .NET Framework x64 before 4.6). https://sharplab.io/ can help here.

Also, it can be compared against the Mono .NET runtime codegen, which does in some configurations use clang (LLVM).

Source code can sometimes be transliterated to C/C++ and compared against VC/GCC/Clang, e.g., using https://godbolt.org/ and comparing the result against an "equivalent" RyuJIT output.

**Comment by AndyAyersMS** [comment]
Going to mark this as "future" as it's not something that directly impacts 6.0.

@alexcovington let us know if there's more we can tell you. As Bruce says there aren't a lot of direct comparisons one can do.

**Comment by alexcovington** [comment]
Thanks, @AndyAyersMS and @BruceForstall! 

That's all good information to have, we just wanted to make sure we were making the same kinds of comparisons as the .NET team. My question is answered, so I'm going to close this for now.
