### ISSUE TITLE
[Docs] Windows build requirements - external tools vs. VS components

### ISSUE THREAD

**Issue by cw2** [dotnet/runtime#55629]
The [Requirements to build dotnet/runtime on Windows](https://github.com/dotnet/runtime/blob/1778ae292f58ff0c88c599f32c65383ff92ef746/docs/workflow/requirements/windows-requirements.md) document lists a few external tools (namely CMake, Ninja and Python) that needs to be downloaded, installed and their executable added to the default PATH environment variable - but all these tools are already parts of the Visual Studio Community 2019 (with sufficient/higher versions) and can be easily installed via Visual Studio Installer (which can be automated further in provided .vsconfig), thus making the build environment setup basically just one-step VS install.

**Comment by cw2** [comment]
Closing (no feedback in almost a week).

**Comment by jkotas** [comment]
> making the build environment setup basically just one-step VS install.

I like this idea. Are you interested in submitting a PR to update and simplify the requirement doc with this one-step VS install?

**Comment by jkotas** [comment]
I am sorry that nobody on the team found time to comment on this sooner.

**Comment by hoyosjs** [comment]
I think this is a good idea. At some point this wasn't included as the workloads were heavy (python) or didn't come with a high enough version (cmake). Now there's either the right versions, or enough checks in place to prevent that from breaking us. This would be a pretty good thing. Only thing to check is if our validation happens once the development environment has been initialized to ensure tools are in the path (would be a small change otherwise probably).

**Comment by cw2** [comment]
> I like this idea. Are you interested in submitting a PR to update and simplify the requirement doc with this one-step VS install?

Yes (however, English is not my native language, so it will definitely require some proofreading).

**Comment by cw2** [comment]
> I am sorry that nobody on the team found time to comment on this sooner.

No problem, I understand there is so much work going on, priorities etc. and only limited resources...

**Comment by cw2** [comment]
> I think this is a good idea. At some point this wasn't included as the workloads were heavy (python) or didn't come with a high enough version (cmake). Now there's either the right versions, or enough checks in place to prevent that from breaking us. This would be a pretty good thing. Only thing to check is if our validation happens once the development environment has been initialized to ensure tools are in the path (would be a small change otherwise probably).

I am thinking about adding something like

- It's recommended to use 'Workloads' installation approach. The following are the minimum requirements:
    - .NET Desktop Development with all default components.
    - Desktop Development with C++ with all default components.
- The build tools (CMake, Ninja and Python) can be downloaded and installed separately (see detailed instructions in the section below) or by selecting the following individual components:
    - "C++ CMake tools for Windows" _(includes Ninja)_
    - For building x86 "Python 3 32-bit"
    - For building x64 "Python 3 64-bit"

I have not checked the environment validation mechanism itself, but after installing the mentioned VS components (I have not installed the tools externally), the build and running test suite seems to be working, but it needs to be verified more thoroughly.

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/56234
