### ISSUE TITLE
Possible Concurrency Bug?

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#55620]
I have a an app that runs a number of different Tasks.  I'm testing it in .NET 6x and I'm getting errors like this:

```
This exception was originally thrown at this call stack:
    System.Runtime.CompilerServices.AsyncTaskMethodBuilder<TResult>.AsyncStateMachineBox<TStateMachine>.MoveNext(System.Threading.Thread)
```

and

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
```

I'm not sure if this is a bug in my code or something somewhere else but I'm at a total loss on how to narrow down the issue.  Any thoughts or ideas?

**Comment by stephentoub** [comment]
Are you able to share a repro, as minimal as possible?

Are you able to attach a debugger and get more details about the failure, where exactly the exception is coming from, etc.?

It's of course possible it's a bug in the runtime, but given the sheer volume and variety of async methods we execute as part of the various repos that compose .NET, if there was such an issue here I'd expect to have seen it already.

Do you use any custom awaiters, e.g. await anything other than Task/ValueTask?  Do you implement IValueTaskSource anywhere?

**Comment by TonyValenti** [comment]
@stephentoub -
No custom awaiters and nothing other than Task/ValueTask.  I haven't been able to create a minimal repro but I have a VM with the code on it that is causing the issue.  When I run my app in VS, I get those errors within a few seconds.  Here's a  screen shot showing what I see.  The exception seems to come from no-where.

![image](https://user-images.githubusercontent.com/13609558/125555760-b22d3bbf-c984-42f7-9134-f048b89e3741.png)



If you email TV@MatterMovers.net I can get you access to the VM.

**Comment by TonyValenti** [comment]
![image](https://user-images.githubusercontent.com/13609558/125555927-34c5be51-eaf5-4e81-bc11-307fd02404f5.png)

**Comment by stephentoub** [comment]
Sent you an email.

**Comment by mangod9** [comment]
Hi @TonyValenti, could you please clarify what OS/arch you are hitting this on?

**Comment by TonyValenti** [comment]
@stephentoub resolved this last night. A value task was double awaited.
