### ISSUE TITLE
ConstraintException in System.Data.DataSet.Merge when deleting and adding a row with the same primary key

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#55661]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ConstraintException-in-SystemDataDataS/1352126)._

---
[severity:It's more difficult to complete my work]
We recently found a problem where we're getting a System.Data.ConstraintException thrown when trying to use the System.Data.DataSet.Merge method in a specific case: when the user removes a row, then manually enters a new one with the same primary key column values.

Our expectation would be that—given that the row that was initially in the DataSet no longer exists—the new one should not trigger a primary key violation. But it seems it does.

A different way to explain this problem is that the documentation suggests that `ds. Merge(ds. GetChanges())` (where `ds` is of type System.Data.DataSet) should be a no-op in all circumstances (that is, for any sequence of operations applied to the dataset), yet it isn't.

I've posted a question with a minimal reproducible example here: https://docs.microsoft.com/en-us/answers/questions/274821/constraintexception-in-systemdatadatasetmerge-when.html

We've found a workaround, but it changes our code from linear to quadratic complexity and we would prefer to avoid additional computation for large datasets.

Thank you!

---
#### Feedback Bot on 3/2/2021, 03:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### . . on 3/10/2021, 01:01 PM: 

<p>And so just to make it complete, the workaround we’re using is as follows: every time we add an item to a table, we scan all deleted items in that table and check whether the new row would match the primary key of some deleted row. If we find a match, instead of adding a new item, we undelete and edit the deleted one. The problem here is that the only available way to access deleted rows is linear in the number of all rows in the table, which makes the code slow for larger datasets.</p>

#### Feedback Bot on 6/1/2021, 04:23 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Dada Huo [MSFT] on 6/29/2021, 07:15 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ?</p>

#### . . on 6/30/2021, 03:39 PM: 

<p>Yes, I can reproduce.</p>

#### Feedback Bot on 7/1/2021, 02:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Given that DataSet is a legacy technology and that there is a good workaround, this is not something we plan to fix.
