### ISSUE TITLE
Access modifier cleanup in Task

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#55665]
This property can be `private protected` (C# 7.2) instead of `internal`:

https://github.com/dotnet/runtime/blob/8bf8030e24c75818c901d9c4d4674938aff3a28e/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L799

**Comment by stephentoub** [comment]
Thanks. You're welcome to submit a PR.  We don't need an issue tracking using private protected instead of internal on one member, though.

**Comment by danmoseley** [comment]
I'm going to close this as an issue isn't appropriate but as above we would welcome a PR.
