### ISSUE TITLE
Double {{ output from interpolated strings

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55688]
There is an ASP.NET Core tool that generates some code. It uses string interpolation. It has many escaped curly braces, `{{`, that are being output in the generated code as double braces rather than single.

https://github.com/dotnet/aspnetcore/blob/3826122d81dd9a62efcc765c56eedbaed9969cb1/src/Servers/Kestrel/tools/CodeGenerator/FeatureCollectionGenerator.cs

You can see this show up in a unit test:

```
﻿ Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.GeneratedCodeTests.GeneratedCodeIsUpToDate
   Source: GeneratedCodeTests.cs line 22
   Duration: 441 ms

  Message: 
Assert.Equal() Failure
                                   ↓ (pos 693)
Expected: ···ore.Internal.Http\r\n{\r\n    internal enum KnownHeaderType\r\n    ···
Actual:   ···ore.Internal.Http\r\n{{\r\n    internal enum KnownHeaderType\r\n   ···
                                   ↑ (pos 693)
```

@stephentoub Am I right that you have made changes to string interpolation recently? C# 10 features have recently been enabled in aspnetcore repo. That might be related.

**Comment by stephentoub** [comment]
What version of the C# compiler do you have? It had a bug for a few days that manifested in this manner.

**Comment by JamesNK** [comment]
I think Arcade decides - https://github.com/dotnet/arcade/blob/0ec8c018893653d73b363a2a449d8fee5de2fd0a/eng/Versions.props#L37

**Comment by JamesNK** [comment]
It looks like runtime has overriden it to use a newer version - https://github.com/dotnet/runtime/blob/d953229d5429d2ffde833740dd481aab864d3e0c/eng/Versions.props#L21

**Comment by stephentoub** [comment]
If you add `#error version` somewhere in your C# file,  it should print out the version number as a compilation error.

**Comment by JamesNK** [comment]
Compiler version: '4.0.0-3.21359.3 (cabdf2c3)'. Language version: 10.0.

**Comment by stephentoub** [comment]
Yeah, that's about 3 commits away from having the fix (https://github.com/dotnet/roslyn/pull/54706) for https://github.com/dotnet/roslyn/issues/54703.
