### ISSUE TITLE
QUIC: we should figure out how to properly handle international names in Quic/Http3

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#55687]
This was raised as part #55468.
For international names, we should make sure they are properly set for outbound connections.
On Listener, we may need to pass the name certificate selection callback. 

We should make sure that in both cases we match SslStream. 
It is unclear at this point what MsQuic expects and if it does any normalization. e.g. punycode of if this is expected from caller. 

cc: @nibanks

**Comment by nibanks** [comment]
The SNI is treated practically as a binary blob by MsQuic, directly from the TLS payload. So it could be anything from the peer.

**Comment by ManickaP** [comment]
Triage: we need to unicode the data. Unicode names are not that wide-spread, punting to 7.0
