### ISSUE TITLE
SDK 3.1 does not run on Linux ARM64 CentOS 7

### ISSUE THREAD

**Issue by datalogics-robb** [dotnet/runtime#55686]
CentOS 7 uses gcc-4.8 on all architectures, which contains a runtime library with versioned symbols. 
 .NET Core Linux runs on CentOS 7 x86_64, but does not run on CentOS 7  ARM64.

x86_64  CentOS 7 looks like this:
```
strings /bin/dotnet | grep GLIBCXX
GLIBCXX_3.4.9
GLIBCXX_3.4.11
GLIBCXX_3.4
(python-env-puma) robb@puma:~$ /bin/dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
(python-env-puma) robb@puma:~$ /bin/dotnet --version
3.1.409
(python-env-puma) robb@puma:~$ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
(python-env-puma) robb@puma:~$ uname -a
Linux puma.dlogics.com 3.10.0-1160.25.1.el7.x86_64 dotnet/sdk#1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
(python-env-puma) robb@puma:~$ 
```

While CentOS 7 AArch64  looks like this:
```
robb@brazo:~$ strings /usr/share/dotnet/dotnet | grep GLIBCXX
GLIBCXX_3.4.21
GLIBCXX_3.4
GLIBCXX_3.4.9
GLIBCXX_3.4.20
GLIBCXX_3.4.11
robb@brazo:~$ /usr/share/dotnet/dotnet --version
/usr/share/dotnet/dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/dotnet/dotnet)
/usr/share/dotnet/dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/dotnet/dotnet)
robb@brazo:~$ strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
robb@brazo:~$ uname -a
Linux brazo.dlogics.com 4.18.0-193.28.1.el7.aarch64 dotnet/sdk#1 SMP Wed Oct 21 16:25:35 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
robb@brazo:~$ 
```

Which is non-functional.  Support by distribution should be independent of the architecture, and if it is not, it should be clearly documented as such.
My organization is now in the position of deciding how to support .NET Core, either by supplying  a newer version of the c++ standard library on this one platform, or by reducing the platforms supported by our product.

**Comment by wfurt** [comment]
Is your system fully updated @datalogics-robb?
cc: @janvorli

**Comment by DancingCorpse** [comment]
I met the same problem on my CentOS 7 ARM64 machine, is there any progress about this issue?

**Comment by datalogics-robb** [comment]
@wfurt Yes - the problem is that Microsoft does not support GlibC 2.17 on ARM Linux - and that means the 3.1 SDK does not support Cent OS 7.

They do support Debian 9 (GlibC 2.24) so we have moved support for ARM Linux to this distro.
Details are here:
  https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md

**Comment by wfurt** [comment]
@janvorli would probably know if there is some specific reason. AFAIK some of older versions were quite buggy.

**Comment by janvorli** [comment]
The Microsoft builds of .NET is not supported for CentOS 7 ARM / ARM64, only x64. These targets are cross-built on Ubuntu 16.04, so that dictates the minimum usable glibc version. The problem is that we don't have cross build support targeting CentOS and we only produce binaries for non-x64 distros using crossbuild. 
@tmds, does Redhat produce .NET Core 3.1 packages for arm/arm64 RHEL?

**Comment by tmds** [comment]
> does Redhat produce .NET Core 3.1 packages for arm/arm64 RHEL?

No, we'll build arm64 packages of .NET 6 for RHEL8.

You could use Microsoft's .NET Core 3.1 arm64 container image to run the app on CentOS 7.
