### ISSUE TITLE
PGO: Issues with MIBC data and classes from different assemblies

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#55695]
When we call a virtual method of a class which is located in a different assembly - we can't get the "likely class" from MIBC data in crossgen2 composite mode in order to devirtualize it using GDV (Guarded Devirtualization). The Composite mode was supposed to merge those two assemblies so we shouldn't have any problems with the class histograms.

### Repro:

Create a console app (`ConsoleApp1`) and a class library (`ClassLibrary1`) with the following snippets:
`ClassLibrary`'s [Classes.cs](https://gist.github.com/EgorBo/34d6a6f5f07c4cbd218d33cb1b1e8504)
`ConsoleApp`1's [Program.cs](https://gist.github.com/EgorBo/24f7f20035bcb00ecc9aaac7a49e9a87)

Make sure `ConsoleApp1` references `ClassLibrary1`.

Run it:
```
dotnet run -c Release

507
471
471
471
472
472
472
471
```
Now turn on the DynamicPGO:
```
$env:DOTNET_TieredPGO=1
dotnet run -c Release

516
375
384
371
371
371
371
371
```
As you can see - it's faster, mainly because [GetValue](https://gist.github.com/EgorBo/24f7f20035bcb00ecc9aaac7a49e9a87#file-program-cs-L40) was devirtalized (via guarded devirtualization)

Now let's run [this](https://gist.github.com/EgorBo/548cc5d80b92e80fe97f99246e48368c) powershell script. It's supposed to collect MIBC data (static profile) and re-build the app using that data and PublishReadyToRun mode, so the final performance should be the same as the Dynamic PGO one above ^. Unfortunately, it's not:
```
500
449
440
446
445
445
483
439
```
However, if I move `Classes.cs` to `ConsoleApp1` assembly and re-run the script - it'll work as expected (as fast as the Dynamic PGO mode).

/cc @AndyAyersMS @davidwrighton

**Comment by EgorBo** [comment]
We believe it explains why in some benchmarks we don't see improvements from the static PGO in comparison with FullPGO, e.g.:
![image](https://user-images.githubusercontent.com/523221/125707947-ff7fb1aa-7a28-4974-9fdd-dea0b188ce2b.png)

**Comment by AndyAyersMS** [comment]
Thanks for opening this. 

When I run your script using latest preview 7 build (after some trouble getting the right dotnet-pgo and the right crossgen2 installed) I sometimes see something odd, do you see this too?

```
Generated d:\bugs\r55695\app.mibc
# Methods: 1381
# Methods with any profile data: 633
# Methods with 32-bit block counts: 0
# Methods with 64-bit block counts: 0
# Methods with 32-bit edge counts: 0
# Methods with 64-bit edge counts: 633
# Type handle histograms: 436 in 191 methods
# GetLikelyClass data: 0 in 0 methods
# Call sites where getLikelyClass is null: 104
# Call sites where getLikelyClass is unknown: 0
# Call sites where getLikelyClass returns data that devirtualizes: 332
Generated d:\bugs\r55695\app.mibc.txt
@@@ Alloc failing, existing schema clash...
```
That last line is some diagnostic output accidentally left in the runtime by me as part of #53247.

As you note the .mibc data seems correct, eg:
```
      "Method": "[app]Tests.Test(ClassAFactoryFactory)",
      "InstrumentationData": [
        {
          "ILOffset": 3,
          "InstrumentationKind": "EdgeLongCount",
          "Other": 30,
          "Data": 0
        },
        {
          "ILOffset": 4,
          "InstrumentationKind": "TypeHandleHistogramLongCount",
          "Other": -2147483648,
          "Data": 400000000
        },
        {
          "ILOffset": 4,
          "InstrumentationKind": "TypeHandleHistogramTypeHandle",
          "Other": -2147483648,
          "Data": [
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory",
            "[lib]ClassBFactoryFactory"
          ]
        },
```
but if you dump the pgo data from the R2R image (via r2rdump on app.r2r.dll), you see there isn't any:
```
long Tests.Test(ClassAFactoryFactory)
Handle: 0x06000002
Rid: 2
EntryPointRuntimeFunctionId: 32999
Number of RuntimeFunctions: 1

PGO info:

long Tests.Test(ClassAFactoryFactory)
Id: 32999
StartAddress: 0x00BC9290
Size: 77 bytes
UnwindRVA: 0x0013B6DC...
```

I think the extra args for crossgen2 may need to be slightly different:
```
/p:PublishReadyToRunCrossgen2ExtraArgs=--embed-pgo-data%3b--mibc%3a$mibcPath
```
(second escaped char changes from 3b ";" to 3a ":") but seems like perhaps the pgo data doesn't get embedded no matter what?

The crossgen2 command line per msbuild binlog looks plausible:
```
C:\Users\andya\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.0-preview.7.21360.10\tools\crossgen2.exe --targetos:windows
--targetarch:x64
-O
--embed-pgo-data
--mibc:d:\bugs\r55695\app.mibc
--composite
--out:"obj\Release\net6.0\win-x64\R2R\app.r2r.dll"
D:\bugs\r55695\lib\bin\Release\net6.0\lib.dll
obj\Release\net6.0\win-x64\app.dl
...
```
The second run should arguably also disable QJFL (and maybe TieredPGO), that is with just default runtime options (static/dynamic pgo) we should see good perf.

**Comment by AndyAyersMS** [comment]
Seems most likely an issue in crossgen2. Maybe relabel?

**Comment by EgorBo** [comment]
I've just created a repro here https://github.com/EgorBo/StaticPGO_Example (two ps1 scripts in App folder to run the Static and Dynamic PGO scenarios)

**Comment by EgorBo** [comment]
From what I see - PGO is not applied at all when Composite mode is enabled (matches what Andy noticed)

**Comment by EgorBo** [comment]
hm... `--partial` passed to crossgen2 fixes the Composite mode and brings performance to DynamicPGO level 🤔

**Comment by EgorBo** [comment]
> The second run should arguably also disable QJFL (and maybe TieredPGO),

@AndyAyersMS, QJFL is not needed indeed, but TieredPGO looks like is needed for some reason, I don't have an explanation for it yet. Maybe `CORJIT_FLAG_BBOPT` is not set for `tier1`

**Comment by EgorBo** [comment]
Looks like the problem is here

![image](https://user-images.githubusercontent.com/523221/126397678-6a58435f-7626-4a97-9d5b-cdb4524e78d9.png)

`onlyDefinedInAssembly`=`Lib` for some reason, well, I know why - it's the first lib passed to crossgen2 in msbuild (before App.dll).

But I suspect OnlyDefinedInAssembly should be `null` in Composite mode.

**Comment by EgorBo** [comment]
Workaround for the issue: `--compilebubblegenerics` flag (it also sets `onlyDefinedInAssembly` to null)
