### ISSUE TITLE
QUIC: ShutdownCompleted cancellation token does not actually cancel the call

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#55706]
We register for cancellation here, but even if the registration fires, we don't actually do anything to cancel the `ShutdownCompletionSource`.

**Comment by CarnaViire** [comment]
You mean to let msquic know about that, i.e. to call for an immediate abortive shutdown?

Update:
Ah, I see, we touch on the wrong completion source here
https://github.com/dotnet/runtime/blob/7cfa94509078e599df748fdea11a1cf7d371ebf1/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L607-L625
This looks like a copy-paste bug
