### ISSUE TITLE
GCStress: Have a mode for compulsory relocation

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#5572]
While running GCStress, we invoke the collector at various stress-points. However, not all objects will move in these GCs, only those the collector deems fit for relocation will move.

It is very useful to have a super-gcstress mode where all live objects will be relocated in every collection. This will not only expose more bugs, but also make gc-stress failures deterministic.

**Comment by BruceForstall** [comment]
I'm going to close this as a dup of https://github.com/dotnet/runtime/issues/10187 (yes, this one came first)
