### ISSUE TITLE
[bug] string compare behavior different on two pc.

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#55723]
### Description

the code:
```c#

class Program
{
       static void Main(string[] args)
        {
            List<string> test = new List<string>();
            test.Add("using System;");
            test.Add("using System.");
            test.Sort();
            Console.WriteLine("test:" + test[0] + test[1]);
     }
}
```

it print out `test:using System.using System;` on my pc, but `test:using System;using System.` on other pc.

### Configuration

window10
dotnet5.0.4
x64

use dotnet publish:

dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -o ..\bin\ 

### Regression?

no.

**Comment by huoyaoyuan** [comment]
Unfortunately, the default ordering of string depends on current culture. This is a known behavior and there are code depending on this.

**Comment by srxqds** [comment]
ok, thank you
