### ISSUE TITLE
Mono: The PINVOKE_OVERRIDE callback doesn't work when AOT-compiling code with direct-pinvoke

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#55733]
### Description

For mobile platforms, we pass the `direct-pinvoke` option to the AOT compiler, so that the AOT compiler emits a direct reference to the native method for P/Invokes. This is an important size optimization, because it allows us to ask the native linker to remove unused code (and if the AOT compiler used dlopen/dlsym, then the native linker wouldn't see those calls, and remove the native methods that are in fact required). This is also a performance optimization (it's obviously faster to just call the native function instead of having to look it up).

However, a problem arises when we pass a PINVOKE_OVERRIDE function to Mono to redirect P/Invokes: in particular we redirect P/Invokes to the objc_msgSend family of functions to our own versions (that are able to catch any Objective-C exceptions). The AOT compiler obviously doesn't know that we want to do this (because we do it at runtime), so it emits a direct call to the objc_msgSend function declared in the DllImport, and at runtime our PINVOKE_OVERRIDE function is never called.

I'm not sure about the best way to solve this, but one idea would be to be able to tell the AOT compiler that if it sees a P/Invoke to native function `X`, it should instead emit a call to the native function `Y`.

At the moment this only affects Mac Catalyst on M1 (because we have to use to use the AOT compiler there), and since size isn't that much of an issue, a workaround is to not use `direct-pinvoke` for now. However, this is something it would be nice to have a solution to at some point.

**Comment by jkotas** [comment]
For CoreCLR, we have have solved this problem by hardcoded special casing of `objc_msgSend` family of functions to make them not eligible for optimizations like direct pinvoke. We treat it as a legacy quirk for backward compatibility with Xamarin. We do not think that it is useful to have generalized features that override the source code meaning. The source code should be source of truth.

**Comment by lambdageek** [comment]
Fixed by #55845
