### ISSUE TITLE
System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib raised when trying to connect to SSAS datasource

### ISSUE THREAD

**Issue by unical1988** [dotnet/runtime#55734]
Hello guys ! 

I have this issue i am facing while trying to connect to a Cube deployed in SSAS to query.

I am using this code to connect to the datasource and then to the cube : 

         
` AdomdConnection conn = new AdomdConnection("Data Source=localhost");
            conn.Open();`

But the second line throws an exception : 

> System.TypeLoadException' in Microsoft.AnalysisServices.AdomdClient.dll
> Could not load type 'System.Security.Principal.WindowsImpersonationContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=...'.

Why is this exception occuring in my very basid example ?

Thanks for the clarification

**Comment by jkotas** [comment]
You are running an assembly compiled for .NET Framework on .NET Core. It works fine in many cases, but it is not guaranteed to work.

In this specific case, the assembly is referencing WindowsImpersonationContext that was intentionally omitted in .NET Core. The discussion about it is at https://github.com/dotnet/runtime/issues/20647#issuecomment-454860914 . 

You should be able to fix this by switching to ADOMD package that is compatible with .NET Core: https://docs.microsoft.com/en-us/analysis-services/client-libraries

Duplicate of #35389

**Comment by unical1988** [comment]
Do you mean i should add another reference Microsoft.AnalysisServices.AdomdClient to my project that is compatible with .NET Framework ?

**Comment by jkotas** [comment]
I meant switch to https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.NetCore.retail.amd64 when running on .NET Core.

**Comment by unical1988** [comment]
Yes sure i understood, thanks for the GREAT help ! it works now.
