### ISSUE TITLE
Generate core dumps in SigKill 

### ISSUE THREAD

**Issue by kdubau** [dotnet/runtime#55739]
### Description

With the fix for https://github.com/dotnet/runtime/issues/51268 we added `COMPlus_EnableDumpOnSigTerm` to enabled dumps on SigTerm.  We also need to add `COMPlus_EnableDumpOnSigKill` to enable them for the kill signal. 

On macOS when a user force quits a .app (or a 'foreground' process, usually something that shows in the dock) the OS will send a TERM signal, but when the process is a 'background' process (does not show in the dock) the OS will send a KILL.  In order to collect dumps from misbehaving sub/background procs that the user needs to force quit, we need the option to enable this.

**Comment by stephentoub** [comment]
sigkill can't be handled.  The OS simply terminates the process.

**Comment by kdubau** [comment]
🤦🏻‍♂️ ... thanks, I remember that now from the Mono days.
