### ISSUE TITLE
COREHOST_TRACE=1 without COREHOST_TRACEFILE set causes process to freeze when using MSBuildLocator

### ISSUE THREAD

**Issue by zivkan** [dotnet/runtime#55755]
### Description

using `CLRHOST_TRACE=1` in a project that also uses Microsoft.Build.Locator causes `MSBuildLocator.RegisterDefaults()` to freeze the process. I didn't dig deeper to see what in the locator is causing it to freeze.

### Configuration

I tested both net5.0 and net6.0, specifically, 5.0.8 and 6.0.0-preview.6.21353.1.

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="16.8" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.4.1" />
  </ItemGroup>

</Project>
```

Program.cs:
```csharp
using System;
using Microsoft.Build.Construction;
using Microsoft.Build.Evaluation;

namespace msbuildApis
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Registering MSBuild Locator defaults");
            Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults();

            MainInternal(args);
        }

        static void MainInternal(string[] args)
        {
            Console.WriteLine("Loading project " + args[0]);
            var project = ProjectRootElement.Open(args[0], ProjectCollection.GlobalProjectCollection, preserveFormatting: true);
            Console.WriteLine("Worked");
        }
    }
}
```

With `COREHOST_TRACE=0`, this program outputs "Worked". With `COREHOST_TRACE=1`, but `COREHOST_TRACEFILE` unset this program stops at "Registering MSBuild Locator defaults", with the following trace text as the last output:
```text
--- Begin breadcrumb write
Breadcrumbs will be written using a background thread
Breadcrumb thread write callback...
--- End breadcrumb write 1
```

There are pages and pages of other traces that I don't want to copy above this.

Setting `COREHOST_TRACEFILE` to a filename, the program will continue/complete.

### Regression?

🤷‍♂️

**Comment by vitek-karas** [comment]
This is a bug in `Microsoft.Build.Locator`. It starts a child process to run `dotnet --info`. When `COREHOST_TRACE=1` is set, that process will produce lot of diagnostics output to `stderr`. The way the process is started is setup to capture `stderr`. See [here](https://github.com/microsoft/MSBuildLocator/blob/d83904bff187ce8245f430b93e8b5fbfefb6beef/src/MSBuildLocator/DotNetSdkLocationHelper.cs#L96). But nothing is reading it. So this will fill in some buffer and when that is full, it will block.

Workaround is to also set `COREHOST_TRACEFILE` as you mention above.

**Comment by zivkan** [comment]
Oops, sorry for wasting your time.
