### ISSUE TITLE
[QUIC] Throw PNSE for unsupported SslOptions (client and server)

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55759]
Todo: please at least make a list which one are not supported.

Related https://github.com/dotnet/runtime/issues/32069 and https://github.com/dotnet/runtime/issues/32071

**Comment by wfurt** [comment]
reverted by #56097

**Comment by ManickaP** [comment]
@wfurt do you still plan to tackle this for 6.0 or should we postpone it / close it in favor of adding the implementation?

**Comment by wfurt** [comment]
I'm not sure what we want to do here. I can fix the other tests and finish this easily. But I worry somewhat about compat and causing more harm. For the local certificate selection callback somebody may have it set by default (like we do) in case server asks for certificate ... and that may be never in case of H3. 

So perhaps I can do everything but `LocalCertificateSelectionCallback` ???
