### ISSUE TITLE
Windows 2012 R2 Server & WebClient Requests | Inablility to make SSL/TSL Connection

### ISSUE THREAD

**Issue by Bibikski** [dotnet/runtime#55764]
There is an issue with Windows 2012 R2 Server and making a WebClient request with a .net application. This error prohibits any WebClient calls. However, this bug has not been found on any other Windows Version that is not a end of life product. The temporary resolution to this issue, as stated before, is to switch to another Microsoft server version.  

The application I was trying to run was a Asp.Net Web Form, however this bug was also spotted with any other application using .Net Framework.  In fact, the first published observation of this bug is from StackOverFlow, which the responder has observed an issue with a cipher mismatch. 

https://stackoverflow.com/questions/68186849/getting-could-not-create-ssl-tls-secure-channel-on-windows-server-2012-r2

Here is the Stack Trace Message:
>Source : mscorlib
>Error Occurred : 7/12/2021 10:57:45 AM
>Error: An error occurred while sending the request.
>StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>  at [REDACTED].<BolAsync>d__6.MoveNext() in [REDACTED]
>--- End of stack trace from previous location where exception was thrown ---
>   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>   at [REDACTED].<CreateShipmentAsync>d__4.MoveNext() in [REDACTED]
>Error Occurred : 7/12/2021 10:57:45 AM
>Error: The request was aborted: Could not create SSL/TLS secure channel.
>StackTrace:    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

The .NET Framework Version of this Application is ***v4.8***

It appears to have gotten a null response as highlighted in the image [**System.Net.Http.HttpClientHandler.GetResponseCallBack()**]
![image](https://user-images.githubusercontent.com/42878698/125842309-2d34d5e7-535f-4747-b0d5-c9b4220b3c2d.png)

As stated before, steps to follow are listed below

1. Spin up a Windows 2012 R2 Server 
2. Create a simple application that makes a web call using the System.Net.Http.WebRequest dynamic link library
3. Run said application on the machine
4. Observe Results

Hopefully this is fixable! 
Thank you for your time,
Bibikski

**Comment by vcsjones** [comment]
>  However, this bug has not been found on any other Windows Version that is not a end of life product. The temporary resolution to this issue, as stated before, is to switch to another Microsoft server version.

If the issue does not reproduce on Windows Server 2016+ then I suspect you are running in to a cipher suite issue. .NET Framework (and .NET Core, .NET 5+) use SChannel on Windows for TLS/HTTPS.

Many websites are moving to more secure HTTPS configurations, such as requiring ECDHE+AESGCM. Windows Server 2012 R2 lacks some modern cipher suites.

It's difficult to say the exact problem without knowing the server you are connecting to with `WebRequest`.

**Comment by karelz** [comment]
@vcsjones @wfurt would Wireshark trace be able to confirm if it is indeed cipher suite problem? ... it would be really nice to have a how-to for self-diagnosing

@Bibikski we do not track .NET Framework problems on GitHub. Moreover this one seems to be more OS version limitation rather than .NET Framework bug.
I will leave it open until we have some more answers and then close it ...

**Comment by Bibikski** [comment]
> 
> 
> @vcsjones @wfurt would Wireshark trace be able to confirm if it is indeed cipher suite problem? ... it would be really nice to have a how-to for self-diagnosing
> 
> @Bibikski we do not track .NET Framework problems on GitHub. Moreover this one seems to be more OS version limitation rather than .NET Framework bug.
> I will leave it open until we have some more answers and then close it ...

No problem. However I ran Wireshark, and my apologies I meant to include that in my report. Wireshark was not even detecting an outbound and or inbound request during the HTTP call. Yet, the cipher statement that @vcsjones stated is most likely the cause. I will pass this information around to my team.

Thank you for the help and the diagnosing.
Have a wonderful day,
Bibikski
