### ISSUE TITLE
SslStream delayed client certificate with legacy OpenSSL

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#55761]
#54692 added support for `NegotiateClientCertificateAsync` on Linux. This seems to work reliably only with OpenSSL 1.1.1 (current LTS) We should investigate the failures on older OpenSSL versions (1.0.0 and 1.1.0) and possibly throw PNSP.

It would be _nice_ to re-test with OpenSSL 3.0 to make sure we did not use anything marked as deprecated or missing in 3.0.

**Comment by wfurt** [comment]
related to #49346

**Comment by karelz** [comment]
Triage: We should add the PNSE and check OpenSSL 3.0 for 6.0 release.
Then we can move it to Future or decide to close as the legacy OpenSSL versions are being pushed out of distros.

**Comment by aik-jahoda** [comment]
Tested following configuration:
- .net SslStream authenticated as server - openssl 1.0.0t.
- openssl s_clients (non .net): OpenSSL 1.0.0t, OpenSSL 1.1.1k, OpenSSL 3.0.0-beta1
The above configuration works as expected. 

SslStream authenticated as client is without change, throwing PNSE (when using openssl version smaller than 1.1.1) would 
1) be breaking change
2) be not nice as the exception would be triggered by server (when requesting certificate) and would depends on server. Instead client shouldn't ignore server HELLO request.

**Comment by karelz** [comment]
Triage: Given that we didn't throw PNSE in 5.0, but relied on server reaction to unsupported feature (e.g. refused connection, etc.), it is fine to keep it in 6.0 the same way for certain older OpenSSL versions (which are on older distros which in time will be out of support anyway).
If there is business demand in future, we can reconsider.
