### ISSUE TITLE
[HTTP/3] SocketsHttpHandlerTest_Http3_MsQuic.ClientSettingsReceived_Success timing out

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#55774]
Failure query

https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22system.net.http.functional.tests.socketshttphandlertest_http3_msquic.clientsettingsreceived_success%22

Test failures typically have the following call stack 

```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.ClientSettingsReceived_Success(headerSizeLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(78,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ClientSettingsReceived_Success(Int32 headerSizeLimit)
        --- End of stack trace from previous location ---
```

Note: thus far this has only failed in Pull Requests so it's not definitively a bug. However the PRs aren't networking related to my understanding hence seems more likely it is a bug here. It's also hit 14 times now.

**Comment by ManickaP** [comment]
Triage: 27 occurrences so far, we might disable it. For 6.0 we need to at least rule out whether it's product bug
```
"Method": ClientSettingsReceived_Success,
"count_": 27,
"min_Queued": 2021-07-15T02:49:58.522Z,
```

**Comment by karelz** [comment]
Failures 5/17-7/16 (incl. PRs):

Date | Failures
-- | --
7/15 | 20 failures -- 19x Fedora.32.Amd64.Open, 1x Debian.10.Amd64.Open ... 2 official builds
7/16 | 12 failures (so far) - 11x Fedora.32.Amd64.Open, 1x Ubuntu.1804.ArmArch.Open ... 3 official builds

We should disable it at least on Fedora ASAP to avoid creating noise for everybody in PRs.

**Comment by karelz** [comment]
Test disabled in PR #55811

**Comment by ManickaP** [comment]
Re-enabled in #67418, no occurrences in Kusto.
