### ISSUE TITLE
ThreadLocals of the same type T can interfere with each other's trackAllValues

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#55796]
Repro:

Problem 1:
Compile and run the program below
Actual result: 100
Expected result: 0. The values associated with collected threads should not be reported.

Problem 2:
Uncomment `UNRELATED_THREAD_LOCAL`, compile and run the program below
Actual result: 0
Expected result: same as with `UNRELATED_THREAD_LOCAL` commented out. The two unrelated ThreadLocal instances should not influence each other

```csharplang
// #define UNRELATED_THREAD_LOCAL

using System;
using System.Threading;

class Program
{
#if UNRELATED_THREAD_LOCAL
    static ThreadLocal<bool> s_unrelatedThreadLocal;
#endif
    static ThreadLocal<bool> s_threadLocal;

    static void Work()
    {
#if UNRELATED_THREAD_LOCAL
        s_unrelatedThreadLocal.Value = true;
#endif
        s_threadLocal.Value = true;
    }

    static void Main(string[] args)
    {
#if UNRELATED_THREAD_LOCAL
        s_unrelatedThreadLocal = new ThreadLocal<bool>(false);
#endif
        s_threadLocal = new ThreadLocal<bool>(true);
        for (int i = 0; i < 100; i++)
        {
            Thread t = new Thread(Work);
            t.Start();
            t.Join();
        }
        GC.Collect();
        GC.WaitForPendingFinalizers();
        int count = 0;
        foreach (var x in s_threadLocal.Values) { if (x) count++; }
        Console.WriteLine(count);
    }
}
```

**Comment by stephentoub** [comment]
> Actual result: 100
> Expected result: 0. The values associated with collected threads should not be reported.

Why would the expected result be 0?  The purpose of trackAllValues:true is that all values are kept, regardless of whether the thread is still alive.  Or, at least, that was the intention, even if the docs are confusing on the topic.  The idea was to be able to use it for things like parallel aggregations or parallel storage of resources that should be cleaned up; the main host would spawn all of the operations, they'd all go off and do their work on whatever threads, and then the host could query Values after the fact and collect/dispose of all of the values or resources, without concern for whether the underlying threads were still around.

So, the actual result of 100 is what I'd expect.

> Uncomment UNRELATED_THREAD_LOCAL, compile and run the program below
> Actual result: 0
> Expected result: same as with UNRELATED_THREAD_LOCAL commented out. The two unrelated ThreadLocal instances should not influence each other

This, however, does appear to be a bug.

**Comment by jkotas** [comment]
> The purpose of trackAllValues:true is that all values are kept, regardless of whether the thread is still alive. Or, at least, that was the intention, even if the docs are confusing on the topic

Yes, the docs are confusing. It is not what I would expect the behavior to be by reading the docs.

**Comment by stephentoub** [comment]
> the docs are confusing

Agreed.  I'll submit a PR to fix them.
