### ISSUE TITLE
Change clang static analyzer reports store directory

### ISSUE THREAD

**Issue by xiangzhai** [dotnet/runtime#558]
Hi,

Thanks @janvorli  Enabled build with clang static analyzer https://github.com/dotnet/coreclr/pull/23121  Then it is able to scan-build for X86, ARM64 and MIPS64.  But it is not easy to distinguish the reports under /tmp directory.  So I changed clang static analyzer report store directory to `BinDir`, for example, `artifacts/bin/coreclr/Linux.x64.Debug/scan-build-log/2019-12-05-141136-4752-1` or `artifacts/bin/coreclr/Linux.mips64.Debug/2019-12-05-114840-12748-1`.

Please review the patch:

```
diff --git a/src/coreclr/build.sh b/src/coreclr/build.sh
index c9a34ca..d282862 100755
--- a/src/coreclr/build.sh
+++ b/src/coreclr/build.sh
@@ -257,7 +257,7 @@ build_native()
     if [ $__StaticAnalyzer == 1 ]; then
         pushd "$intermediatesForBuild"
 
-        buildTool="$SCAN_BUILD_COMMAND $buildTool"
+        buildTool="$SCAN_BUILD_COMMAND -o $__BinDir/scan-build-log $buildTool"
         echo "Executing $buildTool install -j $__NumProc"
         $buildTool install -j $__NumProc
 
```

Thanks,
Leslie Zhai

**Comment by janvorli** [comment]
@xiangzhai thank you, it looks like a very useful change, can you please create a PR for it? I'll be happy to get it in.

**Comment by xiangzhai** [comment]
Hi @janvorli 

Please review it  https://github.com/dotnet/runtime/pull/559

Thanks,
Leslie Zhai
