### ISSUE TITLE
[HTTP/3] Investigate stress low request numbers

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55810]
H/3: TOTAL                     Success: 6,280	Canceled: 518	Fail: 0
H/2: TOTAL                     Success: 1,430,586	Canceled: 106,339	Fail: 0
H/1: TOTAL                     Success: 2,131,086	Canceled: 151,112	Fail: 1

The number of processed requests is suspiciously low.

**Comment by karelz** [comment]
Triage: Looks like we are getting stuck somewhere -- that is high pri for 6.0.

**Comment by CarnaViire** [comment]
Numbers are not low anymore, but we have another problem #56310

I'm closing this for now, will reopen if we'll see this again.
