### ISSUE TITLE
[QUIC] Erroneous flow of inbound MsQuicStream ctor doesn't release safe handle

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55814]
Source: Coder review session

https://github.com/dotnet/runtime/blob/f59a132bfe9ff797f9d192d67f07673a13b6b29e/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L114-L118

See ctor for outbound, it does release it.

It should not matter that we're doing it on msquic thread.

Alternative: Return a specific error code in MsQuicConnection to clean the handle for us.

**Comment by rzikm** [comment]
I think the code is correct as-is. When exception is thrown (when does it actually happen?), then the `NativeCallbackHandler` returns `MsQuicStatusCodes.InternalError`, which will cause MsQuic to release the Stream on its own. Thoughts? @ManickaP

**Comment by ManickaP** [comment]
Based on what do you think msquic will release the handle if we return error code from NEW_STREAM event? Have you found it somewhere in msquic docs/code?

**Comment by rzikm** [comment]
I have checked the source code

**Comment by ManickaP** [comment]
You're right, it's the same behavior as with new incoming connection on a listener, but it's not documented anywhere in msquic.
Let's close this then.
