### ISSUE TITLE
[QUIC] Introduce properties to distiguish uni/bi directional streams

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55816]
ATM moment we're using `CanRead|CanWrite` to determine whether the stream is uni or bi directional.
Might be useful to introduce Is(Uni|Bi)Directional to distinguish the type of the stream instead of that.

**Comment by karelz** [comment]
Triage: Part of QuicStream API

**Comment by ManickaP** [comment]
The current implementation of `CanRead|Write` returns false when the stream is disposed. Whether querying the properties after `Dispose` is a good or bad idea is a different question. Also we already have the enum for stream creation via connection, so we can take advantage of it.

**Comment by wfurt** [comment]
There may be other reasons why `CanWrite` may be false because it depends on internal and peer's state. 
That is different IMHO from knowing is the stream was Bidirectional or Unidirectional e.g. even Bidirectional stream can be in state when `CanWrite` is false.

**Comment by ManickaP** [comment]
Closing as covered by https://github.com/dotnet/runtime/issues/69675
