### ISSUE TITLE
[API Proposal]: Allow StringComparer in more string methods

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#55824]
### Background and motivation

Currently there are wonky workarounds/inconsistencies that are necessary when doing case-insensitive string operations.  This often involves lower/uppercasing strings and working with derivities.

### API Proposal

```C#
string.StartsWith("SomeText", StringComparer.InvariantCultureIgnoreCase);
string.EndsWith("SomeText", StringComparer.InvariantCultureIgnoreCase);
string.Contains("SomeText", StringComparer.InvariantCultureIgnoreCase);
string.Replace("SomeText", "Other Text", StringComparer.InvariantCultureIgnoreCase);
```     

### API Usage

See above.

### Risks

None that I can think of.

**Comment by davidfowl** [comment]
Your proposal looks like the usage section, can you propose the overloads to the methods you'd like to see in the diff view like the template describes? e.g. https://github.com/dotnet/runtime/issues/55510

**Comment by Tornhoof** [comment]
All of your suggestions already exist?
See e.g. https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-5.0#System_String_Contains_System_String_System_StringComparison_

**Comment by tarekgh** [comment]
I don't think we need to expose such overloads. We already have APIs that can achieve that easily. We already have overloads that takes StringComparisons.InvariantCultureIgnoreCase which can be used. 

[String.StartsWith](https://docs.microsoft.com/en-us/dotnet/api/system.string.startswith?view=net-5.0#System_String_StartsWith_System_String_System_StringComparison_)
[String.EndsWith](https://docs.microsoft.com/en-us/dotnet/api/system.string.endswith?view=net-5.0#System_String_EndsWith_System_String_System_StringComparison_)
[String.Contains](https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-5.0#System_String_Contains_System_Char_System_StringComparison_)
[String.Replace](https://docs.microsoft.com/en-us/dotnet/api/system.string.replace?view=net-5.0#System_String_Replace_System_String_System_String_System_StringComparison_)

Also, in general, I wouldn't recommend exposing more overload on string class that not behaving as ordinal. Instead for linguistics behaviors ComareInfo should be used moving forward.

**Comment by GSPP** [comment]
What would these methods do? A `StringComparer` can only compare entire strings. It has no API for comparing a part of a string. I suspect you mean `StringComparison` overloads and those do exist already.
