### ISSUE TITLE
[HTTP/3] Native test crashes on Windows (native heap corruption)

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#55830]
Native crashes happen quite a lot for me when I ran HTTP/3 tests (about 25% of runs). This doesn't happen at all on S.N.Quic tests, so it might be related to the way HTTP/3 is implemented (or lack of S.N.Quic tests). I also believe that @ManickaP and @wfurt that are running tests on Linux don't get the crashes, or at least not that much, so they might be Windows-specific.

MsQuic version:
`SystemNetMsQuicTransportVersion=6.0.0-preview.7.21357.1`
where I expect msquic revision to be https://github.com/microsoft/msquic/commit/3e40721bff04845208bc07eb4ee0c5e421e6388d but I'm not 100% sure.

I've looked through last 10 crashes I had.

1) Most of them (7 of 10) are AVE happening in datapath_winuser.c around SocketProc->Parent->Type check https://github.com/microsoft/msquic/blob/main/src/platform/datapath_winuser.c#L3941 Most of them were failing with the same address that is stored in SocketProc->Parent; twice Parent was null; once the error shown 0xFFFFF... but Parent was other address.

![image](https://user-images.githubusercontent.com/3184057/125961413-08ed7311-48cb-4b07-9571-8a1b3733fddb.png)

2) Out of range around GetQueuedCompletionStatus (1 of 10) https://github.com/microsoft/msquic/blob/main/src/platform/datapath_winuser.c#L3904

![image](https://user-images.githubusercontent.com/3184057/125962463-0871cfd5-6e72-4a35-aa92-884e8843894a.png)

3) AVE on heap allocation for QuicConnStart (1 of 10)

![image](https://user-images.githubusercontent.com/3184057/125962638-d116ef5c-e1f8-4a71-9211-c8240af2a20d.png)

4) Heap corruption on freeing on QuicSendBufferFree (1 of 10)

![image](https://user-images.githubusercontent.com/3184057/125962887-c77be3bd-b7e3-4b30-86cd-69f1028097db.png)

@nibanks what would be the best way for us to investigate this? I might try to collect msquic traces for the first type of failures, though the log file will be huge, as I need to ran all of HTTP/3 tests to get the crash. Other types would be hard to catch. I do have these 10 dumps I've looked through, but I don't know if they will be useful.

cc @wfurt the errors seem to be different from https://github.com/dotnet/runtime/issues/55380

**Comment by nibanks** [comment]
I took a quick look at the heap allocation exception, and MsQuic state generally looks fine. So I am leaning towards there being some general corruption in the process. Can you try running with application verifier enabled to see if it catches any issues closer to the source? cc @ThadHouse

**Comment by CarnaViire** [comment]
We did some investigation with @nibanks offline on the results of app verifier. Unfortunately we didn't see anything useful, just confirmed that the reason for the first case with SocketProc->Parent was also the corruption.

**Comment by CarnaViire** [comment]
@nibanks @wfurt you had a conversation previously about returning codes from the callbacks and ownership of the handles. I don't have a full understanding of the matter yet, but could the corruption be a symptom of invalid behavior there? E.g. both we and msquic think we own the handle and free it 2 times instead of 1.

**Comment by wfurt** [comment]
I will try to reproduce @CarnaViire. We have few places when debug assert was added as well as you can check if you ever hit the case when we return failure to msquic.

**Comment by shuxinqin** [comment]
I had a fatal problem before. I'm not sure if it's related to your discussion.

```csharp
static async Task Test()
{
    var alpns = new string[] { "h3", "h3-32", "h3-31", "h3-30", "h3-29", "sample" };

    QuicClientConnectionOptions options = new QuicClientConnectionOptions();
    options.ClientAuthenticationOptions = new SslClientAuthenticationOptions()
    {
        ApplicationProtocols = alpns.Select(a => new SslApplicationProtocol(a)).ToList()
    };

    options.RemoteEndPoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 4567);

    QuicConnection quicConnection = new QuicConnection(options);
    QuicStream stream = quicConnection.OpenBidirectionalStream();

    //stream.Dispose();
    quicConnection.Dispose();
    stream.Dispose();  // Disposes QuicStream after QuicConnection disposed, it will cause the program to crash.
}
```
![memory_corrupt](https://user-images.githubusercontent.com/11437679/126263247-e1f25cbe-bd97-40d3-8f27-b2a2ccbce89f.png)

**Comment by wfurt** [comment]
What build do you use @shuxinqin? There were MANY recent fixes and the code you posted looks old.

**Comment by shuxinqin** [comment]
yeah, I'm using code(System.Net.Quic) from about two months ago, and it depends on msquic_windows_x64_Release_openssl_1.3.0.
I'm trying to upgrade to the latest code in a few tests.

**Comment by wfurt** [comment]
note that OpenSSL on Windows will _not_ work. see #55544.
I think the problem @CarnaViire opened is real and you may hit it as well.

**Comment by shuxinqin** [comment]
e...msquic_windows_x64_Release_openssl_1.3.0 is work successfully on my computer(windows10) actually.
I started with the msquic_windows_x64_Release_schannel_1.3.0, but it unable to establish connection with Java(https://github.com/netty/netty-incubator-codec-quic), so I switched to msquic_windows_x64_Release_openssl_1.3.0 and it run successfully.
And i meet the problem @CarnaViire opened too. After running for a while, the program will crash, it exited with code -1073741819. Maybe it's because the code I'm using is too old. I'm trying to upgrade to the latest code!

**Comment by wfurt** [comment]
for Schannel to work you generally need to have Insider Preview build @shuxinqin

**Comment by shuxinqin** [comment]
Schannel work successfully to me and it can communicate with aioquic(python https://github.com/aiortc/aioquic), it just can't communicate with Java(https://github.com/netty/netty-incubator-codec-quic), because an error occurred during the handshake phase. I got the key word was NO_COMMON_SIGNATURE_ALGORITHMS. So i have to use msquic_windows_x64_Release_openssl_1.3.0.

**Comment by wfurt** [comment]
@nibanks may know the answer.

**Comment by karelz** [comment]
@shuxinqin heads up that we won't ship System.Net.Quic APIs in .NET 6.0 -- we intentionally removed reference assembly from public builds. We know we will need to make lots of changes to the API surface and we didn't have time to finalize them for 6.0 for public consumption.

**Comment by nibanks** [comment]
It sounds like you might have some unsupported algorithms configured on the peer side that schannel doesn't like. Schannel should support all the normal default ones. ChaCha20 is the only one that it doesn't. Perhaps that's your issue.
