### ISSUE TITLE
Application with alive foreground thread shuts down unexpectedly. 

### ISSUE THREAD

**Issue by baal2000** [dotnet/runtime#55840]
### Description

An ASP.NET Core application runs in a Docker container. It is a monolith web server that also does many other things other than responding to the web requests: communicates with Postgres, ingests IoT device data, processes the data, etc. It may consume a significant amount of RAM (35 GB+) . What it does though may or may not have any relevance to the issue we experienced with it. We could not reproduce the issue as a small, low footprint repro.

The application suddenly shuts down on its own at a random moment during its lifetime, with no external trigger: Could be days after it had started. _ExitCode_ is reported as _0_ externally and also when checked inside the AppDomain.ProcessExit event handler.

This happens very rarely, but due to 1000s of application servers running at a given time, we used to get a few sudden restarts every day until found a workaround by trial and error method. The workaround may point to the source of the issue.

Below is a simplified startup logic that causes the application to experience unexpected and random exits. Here the main application thread starts a new foreground thread and then exits. The new thread in turn starts the application logic threads and then gets blocked indefinitely in Thread.Sleep(). The unhandled exception handler is never gets hit and is left out for simplicity.
This foreground thread is supposed to keep the application from exiting, yet it does suddenly exits intermittently and only reports _"Received ProcessExit notification. ExitCode = 0"_.

```
   class Program
    {
        static Task<int> Main(string[] args)
        {          
           AppDomain.CurrentDomain.ProcessExit += (_, _) =>
            {
                Console.WriteLine($"Received ProcessExit notification. ExitCode = {Environment.ExitCode.ToString(CultureInfo.InvariantCulture)}.");
            };

           // Starting a new foreground thread.
           new Thread(() =>
           {
                StartBusinessLogic();           

               // Block the thread to prevent the application from exiting.
                Console.WriteLine("Waiting in Thread.Sleep");
                Thread.Sleep(Timeout.Infinite);
                // This should never happen
               Environment.ExitCode = 99;
                Console.WriteLine("Thread.Sleep exited unexpectedly");
            }).Start();
            
           return Task.FromResult(0);
        }
   }
```

When the application is updated to exclude the foreground thread creation and block the original main startup thread, then everything works as expected and the application does not exit until it is told so. 
```
   class Program
    {
        static Task<int> Main(string[] args)
        {          
           AppDomain.CurrentDomain.ProcessExit += (_, _) =>
            {
                Console.WriteLine($"Received ProcessExit notification. ExitCode = {Environment.ExitCode.ToString(CultureInfo.InvariantCulture)}.");
            };

            StartBusinessLogic();           

            // Prevent the application from exiting by blocking the main foreground thread.
            Console.WriteLine("Waiting in Thread.Sleep");
            Thread.Sleep(Timeout.Infinite);
            // This should never happen
           Console.WriteLine("Thread.Sleep exited unexpectedly");
          
           return Task.FromResult(99);
        }
   }
 ```

### Configuration
* .NET Core 3.1/5/0
* Ubuntu 20.04, Docker.
*  x64

**Comment by davidwrighton** [comment]
The way the foreground/background thread system works, is that it detects when the main function exits, the runtime transitions in a mode where it monitors the set of foreground threads, and causes that startup thread to wait. When the set of foreground threads goes to 0, then the main thread will trigger the actual shutdown process.

So, your workaround should reliably avoid this problem.

That said, I've done an audit of the thread shutdown/creation/suspension/attach/detach/etc portions of the codebase looking for possible race conditions, etc, and while from your errors, it does appear likely that something is wrong in there, I was unable to find the actual fault. In order to investigate further we would need additional details/logging information.
