### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#55855]
When on `.NET SDK 6.0.100-preview.7.21359.1`

```
error CS0121: The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.Select<TSource, TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, TResult>)' and 'Internal.CommandLine.Enumerable.Select<T, U>(System.Collections.Generic.IEnumerable<T>, System.Func<T, U>)'
```

This is code from here
https://github.com/dotnet/runtime/blob/6b6310b1c96457a2950c526dd1e46ed055343de2/src/coreclr/tools/Common/CommandLine/Enumerable.cs#L21-L29
and here
https://github.com/dotnet/runtime/blob/6b6310b1c96457a2950c526dd1e46ed055343de2/src/coreclr/tools/Common/CommandLine/Enumerable.cs#L42-L45

**Comment by stephentoub** [comment]
What is Internal.CommandLine ?  It seems like there are two equally valid extension methods, and so the compiler is telling you it doesn't know which to pick.

**Comment by jkotas** [comment]
It is command line parser for crossgen2 too and other tools.

**Comment by kant2002** [comment]
I update original issue with locations of the code which was breaking for me.

**Comment by kant2002** [comment]
Is this happens because of implicit namespace imports?
This is only area which I can guess can differ between .NET 6 Preview 4 and .NET 6 Preview 7.

**Comment by MichalStrehovsky** [comment]
Oh wow - https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-new-program-style

For console applications, the following directives are implicitly included in every source file in the application:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
```

🤮

Looks like the docs miss one very important piece of information: how do I tell MSBuild "HELL NO!" to this?

**Comment by kant2002** [comment]
Yes. I confirm that System.Linq added to `ILCompiler.ImplicitNamespaceImports.cs`, and that's behavior is by default.

There only 2 places in repo where `src/coreclr/tools/Common/CommandLine/Enumerable.cs` file included.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/tools/aot/crossgen2/crossgen2.props#L50
and 
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj#L55

so I assume I should add `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` in that files instead of removing source code. Then I should add same property to ILC where I discover the issue.

**Comment by MichalStrehovsky** [comment]
Hm, that disables the support for `<Import Include="Blah" />` completely.

I think we'll want `<DisableImplicitNamespaceImports_DotNet>true</DisableImplicitNamespaceImports_DotNet>` and put that in src\coreclr\tools\Directory.Build.props so that we never have to deal with that in our tools again.

**Comment by RussKie** [comment]
You could also do `<Import Remove="System.Linq" />` in your csproj/props files to exclude specific imports.

**Comment by MichalStrehovsky** [comment]
> You could also do `<Import Remove="System.Linq" />` in your csproj/props files to exclude specific imports.

Not a fan of that. https://github.com/dotnet/sdk/issues/18825 is already discussing adding new additional usings that are going to cause more build breaks. E.g. the proposed System.Diagnostics addition is going to break the build for [Chocolatey](https://github.com/chocolatey/choco/blob/af3e8c9577ed29d7572581418a8274fd6ce7709b/src/chocolatey/infrastructure/adapters/Process.cs#L22), [Microsoft Terminal](https://github.com/microsoft/terminal/blob/e7108332f72a3c14c72a65484d091c4e79ab28b2/samples/ConPTY/MiniTerm/MiniTerm/Processes/Process.cs#L10), [azure pipelines agent](https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Listener/DistributedTask.Pipelines/Yaml/Contracts/Process.cs#L8) and countless other projects.

The discussion shouldn't really be about what other namespaces we add by default, but what namespaces should be removed from the defaults.

The only ones that are maybe, __maybe__, okay are `System` and `System.Collections.Generic`. Everything else: I don't want that in my projects.

**Comment by RussKie** [comment]
My suggestion was to show another way of solving the issue, and not discuss global usings in general.

**Comment by MichalStrehovsky** [comment]
Understood - I was just trying to point out that solution wouldn't satisfy the "so that we never have to deal with that in our tools again" part.

**Comment by RussKie** [comment]
> Oh wow - [docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-new-program-style](https://docs.microsoft.com/en-us/dotnet/core/tutorials/top-level-templates#use-the-new-program-style)
> Looks like the docs miss one very important piece of information: how do I tell MSBuild "HELL NO!" to this?

https://github.com/dotnet/docs/issues/25436

**Comment by MichalStrehovsky** [comment]
> dotnet/docs#25436

@kant2002 already has a pull request in flight: https://github.com/dotnet/docs/pull/25232
