### ISSUE TITLE
[HTTP/3] Update ALPN to h3

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55894]
The latest draft has finalized "h3" as the ALPN identifier.

https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#appendix-B.1

>    *  Removed draft version guidance; added final version string

https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-3

>    A client MAY attempt access to a resource with an "https" URI by
>    resolving the host identifier to an IP address, establishing a QUIC
>    connection to that address on the indicated port (including
>    validation of the server certificate as described above), and sending
>    an HTTP/3 request message targeting the URI to the server over that
>    secured connection.  Unless some other mechanism is used to select
>    HTTP/3, **the token "h3" is used in the Application Layer Protocol
>    Negotiation (ALPN; see [RFC7301]) extension during the TLS handshake.**

https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-11.1

>    This document creates a new registration for the identification of
>    HTTP/3 in the "Application Layer Protocol Negotiation (ALPN) Protocol
>    IDs" registry established in [RFC7301].
> 
>    The "h3" string identifies HTTP/3:
> 
>    Protocol:  HTTP/3
> 
>    Identification Sequence:  0x68 0x33 ("h3")
> 
>    Specification:  This document

**Comment by geoffkizer** [comment]
Pretty sure this is at least part of the underlying issue for https://github.com/dotnet/runtime/issues/54726
