### ISSUE TITLE
Evaluate changing ValueTask to have two reference fields instead of one

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55891]
Today, ValueTask has a single field that can be null (if the operation completed synchronously and successfully), a Task, or an IValueTaskSource.  Every operation on the ValueTask then needs to distinguish which of these it is, which if it's not null, entails an `is Task` type check.  The resulting CastHelpers.IsInstanceOfClass check consumes a measurably significant portion of the overhead for interacting with ValueTask.

An alternative would be to simply have two fields instead of one, one strongly-typed as Task and one strongly-typed as IValueTaskSource.  Then we no longer need to do type checks and can instead just do null checks.  That should make interactions with a ValueTask cheaper, in exchange for the ValueTask itself being larger, which means more state passed back from async method calls, larger state machines, more zero'ing, etc.

**Comment by gfoidl** [comment]
Idea: stick to the one reference field, but add a field of type
```c#
private enum Mode : byte
{
    Completed = 0,
    Task = 1,
    ValueTaskSource = 2
}
```
and use this to check the state / mode, use `Unsafe.As` to "cast". Then the VT just gets one byte larger (padding left out in this consideration) which could be a reasonable compromise.

**Comment by stephentoub** [comment]
That can break type/memory safety in the face of torn reads.

**Comment by stephentoub** [comment]
Another option to consider:
Make Task implement IValueTaskSource. We'd still have the one field,  but strongly-typed as IValueTaskSource. This would make the IVTS case faster,  as it would remove the type check.  It would also remove the type check for Task, but add multiple interface dispatch. But potentially if the ValueTask methods were inlined, guarded devirtualization at a given call site would get most of that back? cc: @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Yes, seems like GDV would work well in this case, though it effectively does an (exact) type check under the covers.

@EgorBo has been looking into extending class profiling to cover user written type tests; with that it seems possible that the current code patterns could be similarly optimized.
