### ISSUE TITLE
[HTTP/3] SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 10) fails

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#55901]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55848-merge-2184098765af4a5dab/System.Net.Http.Functional.Tests/console.e53e1391.log?sv=2019-07-07&se=2021-08-05T19%3A14%3A07Z&sr=c&sp=rl&sig=t5fCnf%2FCwLQ%2Fd8V%2FcmmAF21nLAvDL2zaE9Omh%2BOzLCM%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1242777&view=logs&jobId=71afe768-e493-597c-228c-037834193aeb&j=71afe768-e493-597c-228c-037834193aeb&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6)

```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(273,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(Int32 streamLimit)
        --- End of stack trace from previous location ---
```

_Originally posted by @radical in https://github.com/dotnet/runtime/issues/53688#issuecomment-882254518_

@ManickaP:
I did a quick Kusto query and:
```
"Method": SendMoreThanStreamLimitRequestsConcurrently_LastWaits,
"Result": Fail,
"Arguments": streamLimit: 10,
"count_": 159,
"min_Queued": 2021-07-16T14:42:38.333Z,
```

So it got broken on 16.7. and fails consistently only for stream limit 10.

**Comment by karelz** [comment]
Test failures 5/19-7/18 (incl. PRs):

Day | Failures
-- | --
5/20-6/2 | Failures in PR #52704
6/7 | Failures in PR #53802
7/16 | 19 failures (incl. 1 on official run)
7/17 | 9 failures (incl. 1 on official run)
7/18 | 7 failures (incl. 4 on official runs)
7/19 (so far) | 4 failures (3 on official runs)

We should disable the test ASAP - @ManickaP are you looking at it?

**Comment by ManickaP** [comment]
The first two in your table must be mock, which has been disable for a while, you have to filter test type as well.

**Comment by karelz** [comment]
Yep, sorry, fell for it again. Table is now updated.

**Comment by karelz** [comment]
Disabled in PR #55912 on 7/19

**Comment by rzikm** [comment]
Test reenabled in https://github.com/dotnet/runtime/pull/67419, the failure has not been reproduced after hundreds of runs in a VM similar to what we use in CI
