### ISSUE TITLE
RPM and Debian package generation requires /p:PortableBuild=false, but it shouldn't

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#5592]
## Background

Running this from dotnet/runtime@ab81efd4d575 generates RPM packages:

```
docker run -it --rm -v $(pwd):/work:z -w /work \
  mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-f39df28-20191023143754 bash

yum install -y ruby-devel gcc make rpm-build rubygems
gem install --no-document fpm

./build.sh /p:PortableBuild=false
```

> https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/92 tracks creating a CentOS image with `fpm` already installed. It's not the focus of this issue.

Note `/p:PortableBuild=false`. That changes how the output functions: it is no longer a portable Linux build--it may only work on the distro it was built on.

The official build works around this by splitting the shared framework build apart from the packaging process. First, it builds the portable Linux runtime, then it builds in non-portable mode to create the RPM and Debian packages. It overrides the artifacts location to essentially trick the non-portable builds into packing up the portable runtime.

It is difficult to reproduce the official build's steps locally, making it difficult to make changes to the Debian and RPM packages. (I checked in a dev script a while ago to do this at [tools-local/scripts/dev/master-build-deb-rpm-docker.sh](https://github.com/dotnet/runtime/blob/10717887317beb824e57cdb29417663615211e99/tools-local/scripts/dev/master-build-deb-rpm-docker.sh), but it's not tested in CI and is out of date.)

## Proposal

We should change the build so that `./build.sh` (portable) can produce RPM packages. Right now we have a capability check to silently disable RPM and Debian packaging if the required toolsets aren't available on the machine.

We should consider making it an opt-in flag, to avoid regressing devs' build time if they don't care about RPM/Deb package output. A simple switch would be `/p:BuildLinuxPackages=true`. (Last time I tried locally, the Debian package tooling took 45 min+ for no apparent reason. 😨 Likely a problem with my environment, but it might be a common issue.)

## Caveat

Setting `/p:PortableBuild=false` does do one useful thing we need to provide a replacement for: it sets the `OutputRid` based on the running platform, for example `centos.7-x64` rather than portable `linux-x64`.

We create distro-specific `dotnet-runtime-deps-x.y` packages, because each distro has different package names for the libraries .NET Core requires. This means we have files like [dotnet-runtime-deps-rpm_config_centos.7-x64.json](https://github.com/dotnet/runtime/blob/10717887317beb824e57cdb29417663615211e99/src/installer/pkg/packaging/rpm/dotnet-runtime-deps-rpm_config_centos.7-x64.json) that are intended for a specific distro. The `OutputRid` is used to determine which json file is used.

We should instead have the build produce *all* `dotnet-runtime-deps-x.y` packages, not select one. It is not required to build each `dotnet-runtime-deps` package on its target platform, and building all of them during a developer's local build makes it significantly easier to test dependency changes. It will also let us reduce the number of steps in the official build.

---

The capability checks are around here: https://github.com/dotnet/runtime/blob/10717887317beb824e57cdb29417663615211e99/src/installer/pkg/Directory.Build.targets#L68

The flags preventing Debian and RPM packages from building at all under `linux-x64` are here:
https://github.com/dotnet/runtime/blob/10717887317beb824e57cdb29417663615211e99/src/installer/pkg/Directory.Build.props#L39-L47

/cc @NikolaMilosavljevic

**Comment by NikolaMilosavljevic** [comment]
Fixed with https://github.com/dotnet/runtime/pull/32185
