### ISSUE TITLE
[Perf] Changes: about 10k size increase in system.test.json.dll 

### ISSUE THREAD

**Issue by Lxiamail** [dotnet/runtime#55937]
### Description
 about 10k size increase in system.test.json.dll 
### Configuration
All
### Regression?
yes
### Data
<html>
<body>
<h3 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Run Information</h3>

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | a8926ba6ecadb259694e09650225d9094081a7df
Compare | 5842db2c301cb1752ae854232a4fbae51d4a9ed0
Diff | Diff

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/92b822b6b73de2ad9d5322c5220b17a72e4e6bf94930eba50509a5e0adccd7de/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/92b822b6b73de2ad9d5322c5220b17a72e4e6bf94930eba50509a5e0adccd7de/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f312e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_1.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/9dffd6fbbea31f82bf7fd3e0a20951b95108c0d8d0cc1b1bddc54516004f9840/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/9dffd6fbbea31f82bf7fd3e0a20951b95108c0d8d0cc1b1bddc54516004f9840/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f322e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_2.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/8d49a5e5676456e624e24118463de75b7d92fed55a24fe0d1488fd52c817baf3/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/8d49a5e5676456e624e24118463de75b7d92fed55a24fe0d1488fd52c817baf3/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f332e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_3.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/49bd0bcd5b128e09dd83942cd954d6a9c3a8f2ef3d6fa16f6a1bc1bd7c9f9674/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/49bd0bcd5b128e09dd83942cd954d6a9c3a8f2ef3d6fa16f6a1bc1bd7c9f9674/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f342e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_4.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/b70b414831fdc8c1840e94a6f707afbaa5ff82a0f3e80421bdd58e9c9b9aad06/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/b70b414831fdc8c1840e94a6f707afbaa5ff82a0f3e80421bdd58e9c9b9aad06/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f352e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_5.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/1998a3e9d69422d6b6907a98083087e996f0fccd6c9f7d99d70576dfc7101467/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/1998a3e9d69422d6b6907a98083087e996f0fccd6c9f7d99d70576dfc7101467/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f362e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_6.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/55b0a7fc399c868b2902b4fdcaf3ce17aed9141a5777d7effdc8ed3c8dd30989/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/55b0a7fc399c868b2902b4fdcaf3ce17aed9141a5777d7effdc8ed3c8dd30989/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f372e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_7.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/38afa5077c3793f4fe70c31f8956bd0e987a8a91eae1aaa584ab8f25a006c90a/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/38afa5077c3793f4fe70c31f8956bd0e987a8a91eae1aaa584ab8f25a006c90a/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f382e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_8.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/6f4904ca0d7e006f3144ff30f3e8b58d46eb2b1e05e6fab8077e8d7e9390a8c5/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/6f4904ca0d7e006f3144ff30f3e8b58d46eb2b1e05e6fab8077e8d7e9390a8c5/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f392e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_9.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/989d1f205df63ec731080fa5326126984e8ae50a5179453bdaa62cbfdb4b0b04/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;"><img src="https://camo.githubusercontent.com/989d1f205df63ec731080fa5326126984e8ae50a5179453bdaa62cbfdb4b0b04/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30375f31375f323032312f726566732f68656164732f6d61696e5f7836345f7562756e747525323031382e30345f436f6d70696c6174696f6e4d6f64653d7761736d5f52756e4b696e643d626c617a6f725f7363656e6172696f735f52656772657373696f6e2f534f442532302d2532304d696e696d756d253230426c617a6f7225323054656d706c6174652532302d2532305075626c6973685f31302e706e67" alt="graph" data-canonical-src="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish_10.png" style="box-sizing: content-box; border-style: none; background-color: var(--color-bg-primary); max-width: 100%;"></a><br style="box-sizing: border-box;"><a href="https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20Minimum%20Blazor%20Template%20-%20Publish.html" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-text-link); text-decoration: none;">Historical Data in Reporting System</a></p>
</body>
</html>
Repro:
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - Minimum Blazor Template - Publish*'

**Comment by eerhardt** [comment]
This issue doesn't have as much information as previous issues. 

1. Do we have before and after .zips of the publish folder? 

2. It also doesn't have the before/after ratio table either, for example:

![image](https://user-images.githubusercontent.com/8291187/126199256-4bc9dd0b-9df4-4974-9c4b-86083d446747.png)


cc @DrewScoggins

**Comment by eerhardt** [comment]
This could very well be https://github.com/dotnet/runtime/pull/55108, as it is in the before and after commit range.

cc @eiriktsarpalis

**Comment by DrewScoggins** [comment]
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Compare | [5842db2c301cb1752ae854232a4fbae51d4a9ed0](https://github.com/dotnet/runtime/commit/5842db2c301cb1752ae854232a4fbae51d4a9ed0)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a8926ba6ecadb259694e09650225d9094081a7df...5842db2c301cb1752ae854232a4fbae51d4a9ed0)


### Regressions in SOD - New Blazor Template - Publish

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 250.50 KB | 261.00 KB | 1.04 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.ComponentModel.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 1.31 KB | 1.33 KB | 1.01 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Private.Runtime.InteropServices.JavaScript.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 9.70 KB | 9.94 KB | 1.02 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Private.Runtime.InteropServices.JavaScript.dll](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 20.50 KB | 21.00 KB | 1.02 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 83.34 KB | 86.19 KB | 1.03 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Private.Runtime.InteropServices.JavaScript.dll.br](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 8.63 KB | 8.80 KB | 1.02 | 0.00 | True | | |
[SOD - New Blazor Template - Publish - pub/wwwroot/_framework/System.Text.Json.dll.gz](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=blazor_scenarios/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>) | 97.35 KB | 100.66 KB | 1.03 | 0.00 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish_7.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_17_2021/refs/heads/main_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=blazor_scenarios_Regression/SOD%20-%20New%20Blazor%20Template%20-%20Publish.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'SOD - New Blazor Template - Publish*'
```
<details>

### Payloads

[Baseline](<https://helixri8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-386d4d2e850c44da93/SOD%20-%20New%20Blazor%20Template%20-%20Publish/Publish-emptyblazorwasmtemplate.zip?sv=2019-07-07&se=2021-10-13T04%3A40%3A38Z&sr=c&sp=rl&sig=ApNVTlPFRNFHLP8Lx4EsR%2FFY3MADyhM0m%2F1hDsUcuhA%3D>)
[Compare](<https://helixri8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d77645c6158646cca3/SOD%20-%20New%20Blazor%20Template%20-%20Publish/Publish-emptyblazorwasmtemplate.zip?sv=2019-07-07&se=2021-10-15T07%3A25%3A46Z&sr=c&sp=rl&sig=0qTk%2FkEhFMED%2BWYX0OgK7ecilxnZvDtjFl3r3ukHxG0%3D>)

### Histogram
#### SOD - New Blazor Template - Publish

```log

```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by eerhardt** [comment]
Diffing the baseline and compare assemblies, this was caused mostly by #55108. There were also changes from #55846 in there, but those weren't as large.

![image](https://user-images.githubusercontent.com/8291187/126230792-d08be6a7-396d-49cb-8ab5-52199825d710.png)

@eiriktsarpalis @layomia

**Comment by eiriktsarpalis** [comment]
The reported size regression is an expected side-effect of new features being added to the serializer. I have submitted #55991 which somewhat mitigates the issue (contributing ~2K of uncompressed size reduction, ~100B compressed).

After conversation with @eerhardt, I'm going to close this issue as by-design.
