### ISSUE TITLE
P/Invoke and GCHandle pinning regression on .NET 5.0.301

### ISSUE THREAD

**Issue by ied206** [dotnet/runtime#55944]
#### Summary

Updating .NET runtime to 5.0.301 from 5.0.202 [breaks the existing p/invoke code](https://github.com/ied206/Joveler.Compression/issues/4).

I have a zlib pinvoke library, [Joveler.Compression.Zlib](https://github.com/ied206/Joveler.Compression).
Its zlib inflate/deflate streaming API has broken since upgrading .NET SDK to 5.0.301.

I highly suspect a bug of .NET runtime in handling [pinned GCHandle](https://devblogs.microsoft.com/dotnet/using-gc-efficiently-part-3/). 

#### Details

zlib uses C struct `z_stream` as its context object, and requires the address of `z_stream` must not change while the object is alive. This is undocumented, but apparent on [zlib's `s->strm != strm` check code](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/deflate.c#L361). (`s->strm` is the zlib allocated address, and `strm` is parameter address).

Thus the wrapper **must pin** `z_stream` with GCHandle to prevent GC from moving the object.
If it doesn't, zlib `deflate()/inflate()` occasionally returns `Z_STREAM_ERROR` code, as GC changed the address of `z_stream`.

```csharp
// This code worked prior to .NET SDK 5.0.301
_zs64 = new ZStreamL64(); // .NET translated z_stream
_zsPin = GCHandle.Alloc(_zs64, GCHandleType.Pinned); // GCHandle pinning
...
ZLibRet ret = ZLibInit.Lib.L64.Deflate(_zs64, ZLibFlush.NoFlush); // returns Z_STREAM_ERROR on .NET SDK 5.0.301
```

If I change the code not to pin GCHandle, its test code randomly fails on every .NET platform.

```csharp
// This code randomly fails on .NET Framework 4.8, .NET Core 3.1, .NET 5.0
_zs64 = new ZStreamL64(); // .NET translated z_stream
_zsPin = GCHandle.Alloc(_zs64, GCHandleType.Pinned); // Does not pins GCHandle
...
ZLibRet ret = ZLibInit.Lib.L64.Deflate(_zs64, ZLibFlush.NoFlush); // randomly returns Z_STREAM_ERROR 
```

Therefore, it is highly suspected that there is a bug around pinned GCHandle handling since .NET SDK 5.0.301.

### Configuration

- .NET 5.0.301 on Windows x86, x64
- .NET 5.0.302 on Ubuntu 20.04 x64

### Regression?

The test code worked on every .NET platform prior to 5,0.301.
You can look at [Azure Pipelines build log](https://dev.azure.com/ied206/Joveler.Compression/_build/results?buildId=215&view=logs&j=43d32c17-ff19-5d0a-58b3-52a09bf40d57&t=40753517-6ef9-53c3-7af8-64cbc564be72), which was performed on 2021-04-11 with .NET 5.0.202 SDK.

- .NET 5.0
    - .NET 5.0.202 on Windows x64
    - .NET 5.0.202 on Ubuntu 20.04 x64
    - .NET 5.0.102 on Debian 10 arm64 (emulated with QEMU 6.0)
    - .NET 5.0.102 on Debian 10 arm64 (emulated with QEMU 4.1)
- .NET Core 3.1
- .NET Framework 4.8

#### Reproduce 

To reproduce this issue, simply checkout [Joveler.Compression](https://github.com/ied206/Joveler.Compression) repo and run the tests on .NET SDK 5.0.301 or higher.
The tests should fail like this:

![image](https://user-images.githubusercontent.com/7675657/126197631-adf955bd-31a1-45b1-b73b-1edd2669b916.png)

To test GCHandle pinning effect, change [L182](https://github.com/ied206/Joveler.Compression/blob/1e0120ec3a4d52f1a8ac3c2b289a4a20e08f6936/Joveler.Compression.ZLib/ZLibStreams.cs#L182) and [L173](https://github.com/ied206/Joveler.Compression/blob/1e0120ec3a4d52f1a8ac3c2b289a4a20e08f6936/Joveler.Compression.ZLib/ZLibStreams.cs#L173) of `ZLibStreams.cs` like this:

```csharp
// BEFORE (pinned)
_zsPin = GCHandle.Alloc(<HANDLE>, GCHandleType.Pinned);

// AFTER (not pinned)
_zsPin = GCHandle.Alloc(<HANDLE>, GCHandleType.Normal);
```

#### Why suspect GCHandle pinning?

Different from my zlib wrapper, my [xz-utils wrapper](https://github.com/ied206/Joveler.Compression/tree/master/Joveler.Compression.XZ) and [lz4 wrapper](https://github.com/ied206/Joveler.Compression/tree/master/Joveler.Compression.LZ4) works fine on the latest .NET SDK. The only thing zlib wrapper does differently is the GCHandle pinning of `context object (z_stream)`.

Credit to @Luzifix who noticed and [reported](https://github.com/ied206/Joveler.Compression/issues/4) test failure.

**Comment by ied206** [comment]
Tagging @dotnet/area-GC-coreclr as it is likely to be an issue with GC.

**Comment by mangod9** [comment]
@cshung @Maoni0. There was a change around moving statics to the POH, but not sure whether that would affect this scenario.

**Comment by jkotas** [comment]
@jkoritzinsky Fixed by https://github.com/dotnet/runtime/pull/54244 ?

**Comment by jkoritzinsky** [comment]
Yes
