### ISSUE TITLE
Incorrect Regex matching result in compiled mode

### ISSUE THREAD

**Issue by LiyeXu** [dotnet/runtime#55943]
Below is giving a False output which is incorrect. Could be a duplicate issue of this: [https://github.com/dotnet/runtime/issues/52612](url)

`            string pattern = "[^12]ab|@#";
            string input = "_ab";
            Console.WriteLine($"{Regex.IsMatch(input, pattern, RegexOptions.Compiled)}");
                //$"{Regex.IsMatch(input, pattern)}");`

**Comment by pgovind** [comment]
IIRC 52612 is already fixed. Going to first try to repro this locally with the latest bits

**Comment by pgovind** [comment]
Alright, can confirm that on the latest bits, this doesn't reproduce. Going to close this as fixed with https://github.com/dotnet/runtime/pull/53135
