### ISSUE TITLE
QUIC: handling of timeouts should be improved 

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#55984]
Currently we set timeout in SafeMsQuicConfigurationHandle

https://github.com/dotnet/runtime/blob/633e04481f21a23d567cf49177f76fbef3a34cfe/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs#L118-L127

When timeout _is_ Timeout.InfiniteTimeSpan we should set the value to 0. 
If we skip setting it, default 30s timeout would still apply. 

There is _separate_ timeout setting for Connect. So if somebody wishes to control that either by allowing more time on slow network or vice versa they currently cannot do that via timeouts. (smaller timeout can be enforced via cancellation token as mitigation ) We can either apply current timeout in both cases or split the timeout setting.

**Comment by GSPP** [comment]
Maybe the timeout should be rounded in order to improve precision?

**Comment by karelz** [comment]
Triage: We do not disable timeout on msquic when we get `Timeout.InfiniteTimeSpan` from API -- should be simple to rearrange.
