### ISSUE TITLE
[Regression] Multiple HTTP/2 streams created concurrently not all reaching the server

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55980]
A gRPC test that works in .NET 5 now fails in .NET 6.

The test starts 201 gRPC calls over HTTP/2 concurrently, waits for them all to reach the server, and then completes. `SocketsHttpHandler.EnableMultipleHttp2Connections` is true so the client should be creating 3 HTTP/2 connections (server max streams is the default of 100) so all calls reach the server.

Logs seem to indicate that two connections are made and 200 calls reach the server. The 201st never makes it.

Attached are complete logs (LONG): [MaxConcurrentStreams_StartConcurrently.txt](https://github.com/dotnet/runtime/files/6845229/MaxConcurrentStreams_StartConcurrently.txt)

Repo: https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/net6-concurrentstreams
Test: StreamingTests.MaxConcurrentStreams_StartConcurrently_AdditionalConnectionsCreated

https://github.com/JamesNK/grpc-dotnet/blob/5f9fe9a0442d99e3bce30be8b2ccf5ddbebd5beb/test/FunctionalTests/Client/StreamingTests.cs#L894-L992

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21368.1
 Commit:    a5889518cc
```

**Comment by geoffkizer** [comment]
This is likely due to my connection pooling PR. Will investigate.
