### ISSUE TITLE
[API Proposal]: Add an overload of Encoding.GetString that takes a ReadOnlySpan<byte>

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [dotnet/runtime#55998]
### Background and motivation

Today if you've got a ReadOnlySpan<byte> and want to use Encoding.GetString, you need to either copy the contents pointed by the ReadOnlySpan<byte> to a byte[] which can be expensive or pin it to a pointer and use the overload that takes a byte pointer and an integer which represents the size. Both of which aren't convenient and you need to use unsafe code for the less expensive option which some people might not like. I'm proposing to add a new overload that takes an ReadOnlySpan<byte> which pins internally and uses the overload that takes a byte pointer but the caller doesn't need to use unsafe code and it will look much cleaner.

### API Proposal

```C#
namespace System.Text
{
    public abstract class Encoding : ICloneable
    {
        public virtual string GetString(ReadOnlySpan<byte> buffer);
        public virtual string GetString(ReadOnlySpan<byte> buffer, int index, int count);
    }
}
```     

### API Usage

```C#
ReadOnlySpan<byte> buffer;
Encoding encoding = Encoding.Unicode;
string text = Encoding.Default.GetString(buffer);
```

**Comment by stephentoub** [comment]
This already exists:
https://github.com/dotnet/runtime/blob/4c92aef2b08f9c4374c520e7e664a44f1ad8ce56/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs#L944

**Comment by Jaiganeshkumaran** [comment]
Is it available in UWP?

**Comment by reflectronic** [comment]
No, it is .NET Standard 2.1 only, just like all of the library APIs that use Span.

**Comment by Jaiganeshkumaran** [comment]
However, Span can be installed in a .NET Standard 2.0 through the System.Memory package so why not? At least they could've created an extension method with the same signature.

**Comment by Jaiganeshkumaran** [comment]
Anyway even if .NET Core 2.1 has that, it doesn't have another signature I proposed that takes the index and the count. You shouldn't need to copy it to a byte[] for that functionality.

**Comment by stephentoub** [comment]
> You shouldn't need to copy it to a byte[] for that functionality.

You don't:
```C#
Encoding.UTF8.GetString(bytes.AsSpan(offset, count)
```
or
```C#
Encoding.UTF8.GetString(span.Slice(offset, count));
```

**Comment by Jaiganeshkumaran** [comment]
However it would be better if there was the overload so it will be consistent with byte[].

**Comment by teo-tsirpanis** [comment]
> However it would be better if there was the overload so it will be consistent with byte[].

The purpose of spans is exactly to avoid passing `offset` and `count`.

**Comment by Jaiganeshkumaran** [comment]
The purpose of byte[] is also that, it has a Length property however there's an overload for that.

**Comment by stephentoub** [comment]
There's an overload with byte[] so that you can process a subset of it; with just arrays, you'd have to allocate/copy that subarray into a new one.  With spans, you can process a subset simply by slicing it, which is essentially free.

All of our span-based functionality is based purely on spans and does not accept an offset/count.  That's by design.

**Comment by teo-tsirpanis** [comment]
Also `System.Memory` looks like it is not maintained anymore; its version is stuck at 4.5.x, the last non-patch release was about two years ago, and almost surely will not get any new APIs.

Even if it got an overload of `GetString` that accepts spans, it would be in an extension method causing an asymmetry and binary incompatibilities with the rest of the framework.

@Jaiganeshkumaran if you are stuck on UWP I am recommending you to create an extension method like this:

``` csharp
internal static class EncodingExtensions {
  public static unsafe string GetString(this Encoding encoding, ReadOnlySpan<byte> span) {
    fixed (byte* ptr = span)
        return encoding.GetString(ptr, span.Length);
  }
}
```

You shouldn't worry about the extension method being unsafe. It might be, but calling it is safe. And it is also so small that it is very easily comprehensible.

**Comment by Jaiganeshkumaran** [comment]
@teo-tsirpanis I'm not stuck with UWP, I'm just building for the UWP app model. Why aren't you providing modern .NET stuff to UWP? UWP isn't a dead old technology, it's an actively maintained technology and actively used. If UWP is dead, Microsoft would've openly announced it long before.

**Comment by Jaiganeshkumaran** [comment]
Anyway thanks for the code snippet for the extension method. I'll close this issue.
