### ISSUE TITLE
[QUIC] S.N.Quic internally ignores `MsQuicApi.IsQuicSupported`

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#56005]
We expose this flag, but if caller ignores it and calls some APIs we'll end up with `NullReferenceException` or something else that's similarly bad.

**Comment by karelz** [comment]
@Tratcher is it impacting you badly for 6.0? Or is 7.0 sufficient?
How does it surface to ASP.NET customers?

**Comment by Tratcher** [comment]
This was discovered when the AppContext switch disabled the MsQuic library loading. We weren't checking IsSupported yet so the QuicListener APIs threw NullReferenceExceptions.

We'll add our own calls to IsSupported regardless so we're not directly affected by this.

**Comment by karelz** [comment]
OK, moving to 7.0 then. Thanks!

**Comment by karelz** [comment]
@ManickaP plans to close it with QuicProvider PR.

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/pull/70421

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/pull/70421
