### ISSUE TITLE
[Perf] Regressions in System.Text.RegularExpressions.Tests.Perf_Regex_Common

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56018]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [96ce6b35359b3c159ef3e685dd67cf30bb46769b](https://github.com/dotnet/runtime/commit/96ce6b35359b3c159ef3e685dd67cf30bb46769b)
Compare | [c5edf0e09541e2c9c4441c0abdf23f712507596c](https://github.com/dotnet/runtime/commit/c5edf0e09541e2c9c4441c0abdf23f712507596c)
Diff | [Diff](https://github.com/dotnet/runtime/compare/96ce6b35359b3c159ef3e685dd67cf30bb46769b...c5edf0e09541e2c9c4441c0abdf23f712507596c)

### Regressions in System.Text.RegularExpressions.Tests.Perf_Regex_Common

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[OneNodeBacktracking - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.OneNodeBacktracking(Options%3a%20Compiled).html>) | 1.78 μs | 2.23 μs | 1.25 | 0.02 | False | | |
[CtorInvoke - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.CtorInvoke(Options%3a%20Compiled).html>) | 138.34 μs | 154.34 μs | 1.12 | 0.00 | False | | |
[Date_IsMatch - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Date_IsMatch(Options%3a%20Compiled).html>) | 79.03 ns | 87.87 ns | 1.11 | 0.03 | False | | |
[Ctor - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Ctor(Options%3a%20Compiled).html>) | 29.66 μs | 34.19 μs | 1.15 | 0.03 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common_4.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Text.RegularExpressions.Tests.Perf_Regex_Common.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.RegularExpressions.Tests.Perf_Regex_Common*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-a8da751e-04f1-4ce6-88ce-a45e60614ceb106f4d4fb914f46ac/12ff34fe-21bb-4099-bbc3-5b6e281c2898.zip?sv=2019-07-07&se=2021-08-17T11%3A02%3A23Z&sr=c&sp=rl&sig=9XCNOfmTdW6nupG2EfRxlDrSCRDOno1HtjPqoiVQBZU%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-30bb0bfb-9b58-4017-a9b5-04cdaa0671ea97d88038759452dab/9c3aecf1-8ec0-4036-9dd7-dd0c74a3a881.zip?sv=2019-07-07&se=2021-08-17T18%3A22%3A42Z&sr=c&sp=rl&sig=A9OL0cnpC3AuRehCj9XqLC3Uj7Ol4xyL7q9453i6ltw%3D>)

#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.OneNodeBacktracking(Options: Compiled)

```log

```
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.CtorInvoke(Options: Compiled)

```log

```
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Date_IsMatch(Options: Compiled)

```log

```
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Ctor(Options: Compiled)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
Seems related to https://github.com/dotnet/runtime/pull/51508

**Comment by DrewScoggins** [comment]
Improvements from this change:

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [96ce6b35359b3c159ef3e685dd67cf30bb46769b](https://github.com/dotnet/runtime/commit/96ce6b35359b3c159ef3e685dd67cf30bb46769b)
Compare | [c5edf0e09541e2c9c4441c0abdf23f712507596c](https://github.com/dotnet/runtime/commit/c5edf0e09541e2c9c4441c0abdf23f712507596c)
Diff | [Diff](https://github.com/dotnet/runtime/compare/96ce6b35359b3c159ef3e685dd67cf30bb46769b...c5edf0e09541e2c9c4441c0abdf23f712507596c)


### Improvemnts in System.Text.RegularExpressions.Tests.Perf_Regex_Common

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Backtracking - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Backtracking(Options%3a%20None).html>) | 1.85 μs | 268.47 ns | 0.15 | 0.03 | True | | |
[Backtracking - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Text.RegularExpressions.Tests.Perf_Regex_Common.Backtracking(Options%3a%20Compiled).html>) | 471.42 ns | 176.56 ns | 0.37 | 0.01 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/System.Text.RegularExpressions.Tests.Perf_Regex_Common_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/System.Text.RegularExpressions.Tests.Perf_Regex_Common_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/System.Text.RegularExpressions.Tests.Perf_Regex_Common.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.RegularExpressions.Tests.Perf_Regex_Common*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-a8da751e-04f1-4ce6-88ce-a45e60614ceb106f4d4fb914f46ac/12ff34fe-21bb-4099-bbc3-5b6e281c2898.zip?sv=2019-07-07&se=2021-08-17T11%3A02%3A23Z&sr=c&sp=rl&sig=9XCNOfmTdW6nupG2EfRxlDrSCRDOno1HtjPqoiVQBZU%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-30bb0bfb-9b58-4017-a9b5-04cdaa0671ea97d88038759452dab/9c3aecf1-8ec0-4036-9dd7-dd0c74a3a881.zip?sv=2019-07-07&se=2021-08-17T18%3A22%3A42Z&sr=c&sp=rl&sig=A9OL0cnpC3AuRehCj9XqLC3Uj7Ol4xyL7q9453i6ltw%3D>)

### Histogram
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Backtracking(Options: None)

```log

```
#### System.Text.RegularExpressions.Tests.Perf_Regex_Common.Backtracking(Options: Compiled)

```log

```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment]
cc: @pgovind

**Comment by pgovind** [comment]
Will look into this after https://github.com/dotnet/runtime/pull/55960#issuecomment-883589136

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/51508 was reverted.  Presumably/hopefully this will go away as well.

**Comment by pgovind** [comment]
Yup, we reverted #51508. I'd be very very surprised if the regressions/improvements here still remain. I'm going to close this issue for now. We can re-open if the regressions still exist.
