### ISSUE TITLE
[Perf] Regressions in Version.ToString and TryFormat

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56011]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b1375a9c34966c563bc5ebeab9b5964682a3e939](https://github.com/dotnet/runtime/commit/b1375a9c34966c563bc5ebeab9b5964682a3e939)
Compare | [cf7394339937535dd97ed1082bb6d0d30f34eab0](https://github.com/dotnet/runtime/commit/cf7394339937535dd97ed1082bb6d0d30f34eab0)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b1375a9c34966c563bc5ebeab9b5964682a3e939...cf7394339937535dd97ed1082bb6d0d30f34eab0)

### Regressions in System.Tests.Perf_Version

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryFormat2 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.TryFormat2.html>) | 17.17 ns | 32.16 ns | 1.87 | 0.01 | True | | |
[TryFormat3 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.TryFormat3.html>) | 23.97 ns | 42.82 ns | 1.79 | 0.03 | True | | |
[TryFormatL - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.TryFormatL.html>) | 78.01 ns | 97.99 ns | 1.26 | 0.01 | False | | |
[ToString3 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.ToString3.html>) | 36.00 ns | 54.86 ns | 1.52 | 0.02 | True | | |
[ToString2 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.ToString2.html>) | 29.64 ns | 45.83 ns | 1.55 | 0.03 | True | | |
[TryFormat4 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.TryFormat4.html>) | 28.72 ns | 52.89 ns | 1.84 | 0.02 | True | | |
[ToStringL - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.ToStringL.html>) | 92.87 ns | 113.91 ns | 1.23 | 0.02 | False | | |
[ToString4 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Version.ToString4.html>) | 42.31 ns | 64.52 ns | 1.52 | 0.03 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_6.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_7.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version_8.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Version.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Version*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-b09195c8-532e-4582-998c-bc928422d98fd8c4a687b2a48f4b9/26416678-07a9-4293-ba6c-999e471da89e.zip?sv=2019-07-07&se=2021-08-12T11%3A52%3A51Z&sr=c&sp=rl&sig=Z7M0zdQljLKGsdx%2FsIPegenfGubNp%2Fn57ooN61sWWj8%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-3620e7fd-c891-4f7d-9fcf-8b272ba85bd741bbc21ad4e45bbae/49a2750a-6fc6-4006-aad6-672ef8c48d58.zip?sv=2019-07-07&se=2021-08-12T17%3A57%3A54Z&sr=c&sp=rl&sig=zdzhd276qPvZCHlJRG5a33Vdn6QMpQ6%2BZ0upIZ7yCTI%3D>)

#### System.Tests.Perf_Version.TryFormat2

```log

```
#### System.Tests.Perf_Version.TryFormat3

```log

```
#### System.Tests.Perf_Version.TryFormatL

```log

```
#### System.Tests.Perf_Version.ToString3

```log

```
#### System.Tests.Perf_Version.ToString2

```log

```
#### System.Tests.Perf_Version.TryFormat4

```log

```
#### System.Tests.Perf_Version.ToStringL

```log

```
#### System.Tests.Perf_Version.ToString4

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment]
@DrewScoggins, as we talked about yesterday, the Perf_DateTimeCultureInfo and Perf_DateTime sections here are erroneous and should be removed, yes?

**Comment by DrewScoggins** [comment]
Yes, sorry about that. I just updated this.

**Comment by stephentoub** [comment]
Thanks, Drew.
