### ISSUE TITLE
[Perf] Regression in XmlSerialization

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56014]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;SimpleStructWithProperties&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(SimpleStructWithProperties).XmlSerializer_.html>) | 1.72 μs | 1.89 μs | 1.10 | 0.11 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(SimpleStructWithProperties)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(SimpleStructWithProperties).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;SimpleStructWithProperties&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;SimpleStructWithProperties&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_FromStream&lt;SimpleStructWithProperties&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_FromStream(SimpleStructWithProperties).XmlSerializer_.html>) | 3.98 μs | 4.98 μs | 1.25 | 0.07 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_FromStream(SimpleStructWithProperties)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_FromStream(SimpleStructWithProperties).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_FromStream&lt;SimpleStructWithProperties&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_FromStream&lt;SimpleStructWithProperties&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;ClassImplementingIXmlSerialiable&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(ClassImplementingIXmlSerialiable).XmlSerializer_.html>) | 954.03 ns | 1.24 μs | 1.30 | 0.15 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(ClassImplementingIXmlSerialiable)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(ClassImplementingIXmlSerialiable).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;ClassImplementingIXmlSerialiable&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;ClassImplementingIXmlSerialiable&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_FromStream&lt;ClassImplementingIXmlSerialiable&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_FromStream(ClassImplementingIXmlSerialiable).XmlSerializer_.html>) | 2.46 μs | 3.27 μs | 1.33 | 0.10 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_FromStream(ClassImplementingIXmlSerialiable)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_FromStream(ClassImplementingIXmlSerialiable).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_FromStream&lt;ClassImplementingIXmlSerialiable&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_FromStream&lt;ClassImplementingIXmlSerialiable&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;XmlElement&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(XmlElement).XmlSerializer_.html>) | 938.80 ns | 1.09 μs | 1.16 | 0.18 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(XmlElement)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(XmlElement).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;XmlElement&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;XmlElement&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [b412aac8757d7ac29ab66910e462649eeaecda18](https://github.com/dotnet/runtime/commit/b412aac8757d7ac29ab66910e462649eeaecda18)
Compare | [a8926ba6ecadb259694e09650225d9094081a7df](https://github.com/dotnet/runtime/commit/a8926ba6ecadb259694e09650225d9094081a7df)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b412aac8757d7ac29ab66910e462649eeaecda18...a8926ba6ecadb259694e09650225d9094081a7df)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;LoginViewModel&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(LoginViewModel).XmlSerializer_.html>) | 1.95 μs | 2.18 μs | 1.12 | 0.10 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(LoginViewModel)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(LoginViewModel).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;LoginViewModel&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-0dbf5c61-b7a0-4b17-8da6-a48efde9f251963fcfcce7c43eba9/4e8d15db-4e59-43f4-acf2-c5ca94256299.zip?sv=2019-07-07&se=2021-08-13T22%3A16%3A26Z&sr=c&sp=rl&sig=1W2vlyToz7DNOzDx2spOmyPd2m3C%2BTzTmROFvJhwq2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-12ecd180-9f9a-4682-ad00-50817d5fc822b3a28596e0f49d781/56a40dbf-d5dc-4008-b34b-81d7e55a6f25.zip?sv=2019-07-07&se=2021-08-14T04%3A41%3A36Z&sr=c&sp=rl&sig=v6roQLdNY7%2BVBqLG%2FM41U6zoAz3Ry1JvHPdYu6Dhzl8%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;LoginViewModel&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment]
Seems related to https://github.com/dotnet/runtime/pull/54949

**Comment by stephentoub** [comment]
cc: @StephenMolloy
