### ISSUE TITLE
[Perf] Regression in Copy and EqualityComparers

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56019]
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [75fb0c3a05656bb11ea7524eb39966a504970b1d](https://github.com/dotnet/runtime/commit/75fb0c3a05656bb11ea7524eb39966a504970b1d)
Compare | [7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4](https://github.com/dotnet/runtime/commit/7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4)
Diff | [Diff](https://github.com/dotnet/runtime/compare/75fb0c3a05656bb11ea7524eb39966a504970b1d...7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4)

### Regressions in System.Collections.CopyTo&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ReadOnlySpan - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Collections.CopyTo(Int32).ReadOnlySpan(Size%3a%202048).html>) | 147.80 ns | 168.70 ns | 1.14 | 0.00 | True | | |
[ReadOnlyMemory - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Collections.CopyTo(Int32).ReadOnlyMemory(Size%3a%202048).html>) | 147.72 ns | 170.49 ns | 1.15 | 0.00 | True | | |
[Span - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Collections.CopyTo(Int32).Span(Size%3a%202048).html>) | 144.90 ns | 168.09 ns | 1.16 | 0.00 | True | | |
[Array - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Collections.CopyTo(Int32).Array(Size%3a%202048).html>) | 147.85 ns | 169.45 ns | 1.15 | 0.00 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Collections.CopyTo(Int32)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Collections.CopyTo(Int32)_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Collections.CopyTo(Int32)_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Collections.CopyTo(Int32)_4.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Collections.CopyTo(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CopyTo&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-6dedb40f-9692-4c1f-a258-dde9bf3630fde22980a6d2446c793/d5b255de-84d4-4540-b453-f90e910174fb.zip?sv=2019-07-07&se=2021-08-07T09%3A54%3A48Z&sr=c&sp=rl&sig=jwuMcRCkGykGBf1YSqWTyW4A%2BnQCCL%2Fre%2FR5oa%2BT3MI%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-6d151fba-ea0e-485b-8d79-2d4bc73f61aadb82e55448f44b2a8/bff62928-4039-47d0-91a9-25734e327625.zip?sv=2019-07-07&se=2021-08-07T17%3A01%3A34Z&sr=c&sp=rl&sig=tBXr6QpUgRtjsT2%2F431%2FOqkJ7qjGcIgE1xSFAE8QCRo%3D>)

#### System.Collections.CopyTo&lt;Int32&gt;.ReadOnlySpan(Size: 2048)

```log

```
#### System.Collections.CopyTo&lt;Int32&gt;.ReadOnlyMemory(Size: 2048)

```log

```
#### System.Collections.CopyTo&lt;Int32&gt;.Span(Size: 2048)

```log

```
#### System.Collections.CopyTo&lt;Int32&gt;.Array(Size: 2048)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [75fb0c3a05656bb11ea7524eb39966a504970b1d](https://github.com/dotnet/runtime/commit/75fb0c3a05656bb11ea7524eb39966a504970b1d)
Compare | [7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4](https://github.com/dotnet/runtime/commit/7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4)
Diff | [Diff](https://github.com/dotnet/runtime/compare/75fb0c3a05656bb11ea7524eb39966a504970b1d...7ab7eaa24c318cf67ff2b5bc9713b61a86c567b4)

### Regressions in Devirtualization.EqualityComparer

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ValueTupleCompareWrapped - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/Devirtualization.EqualityComparer.ValueTupleCompareWrapped.html>) | 4.35 ns | 7.55 ns | 1.74 | 0.08 | True | | |
[ValueTupleCompareCached - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/Devirtualization.EqualityComparer.ValueTupleCompareCached.html>) | 4.36 ns | 5.74 ns | 1.32 | 0.13 | False | | |
[ValueTupleCompareNoOpt - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/Devirtualization.EqualityComparer.ValueTupleCompareNoOpt.html>) | 5.48 ns | 7.88 ns | 1.44 | 0.15 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/Devirtualization.EqualityComparer_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/Devirtualization.EqualityComparer_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/Devirtualization.EqualityComparer_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/Devirtualization.EqualityComparer.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Devirtualization.EqualityComparer*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-6dedb40f-9692-4c1f-a258-dde9bf3630fde22980a6d2446c793/d5b255de-84d4-4540-b453-f90e910174fb.zip?sv=2019-07-07&se=2021-08-07T09%3A54%3A48Z&sr=c&sp=rl&sig=jwuMcRCkGykGBf1YSqWTyW4A%2BnQCCL%2Fre%2FR5oa%2BT3MI%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-6d151fba-ea0e-485b-8d79-2d4bc73f61aadb82e55448f44b2a8/bff62928-4039-47d0-91a9-25734e327625.zip?sv=2019-07-07&se=2021-08-07T17%3A01%3A34Z&sr=c&sp=rl&sig=tBXr6QpUgRtjsT2%2F431%2FOqkJ7qjGcIgE1xSFAE8QCRo%3D>)

#### Devirtualization.EqualityComparer.ValueTupleCompareWrapped

```log

```
#### Devirtualization.EqualityComparer.ValueTupleCompareCached

```log

```
#### Devirtualization.EqualityComparer.ValueTupleCompareNoOpt

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by EgorBo** [comment]
The EqualityComparer benchmarks are regressed by https://github.com/dotnet/runtime/pull/50446 (seems like it regressed struct support), I'll take a look
