### ISSUE TITLE
breakpoint hit on razor view only if razor and code are in same page, but not with code-behind

### ISSUE THREAD

**Issue by brunofrance** [dotnet/runtime#56029]
Hi,

Can you help me to understand if it's a bug or if it's me ?

I start a new default blazor wasm project :
in counter.razor, I insert this small piece of code : 
```
@if (currentCount > 10)
{
   <h3>Yes !!</h3>
}
```
I set a breakpoint on th **@if (currentCount > 10)**
It is hit : all is good !
**but**,
If I move the @code and set it in Counter.razor.cs, the counter works fine, the breakpoints inside the .razor.cs are hitted, but the breakpoint on th **@if (currentCount > 10)** is no longer reached

Thanks for your help : all my project use code-behind approach...

**Comment by thaystg** [comment]
If I understood it correctly, this is working on .net7.

![image](https://user-images.githubusercontent.com/4503299/182173595-5a2bf659-2a52-43a5-b778-3ed8b1ba8040.png)

**Comment by ilonatommy** [comment]
Fixed by https://github.com/microsoft/vscode-js-debug/pull/1354.
