### ISSUE TITLE
Blazor WASM interactive debug session doesn't work with default project settings

### ISSUE THREAD

**Issue by RobertBouillon** [dotnet/runtime#56022]
### Description
ALT+SHIFT+D will result in the following error
![image](https://user-images.githubusercontent.com/612152/109886121-9b9cc280-7c4d-11eb-8e57-5192d15d7769.png)
(Regression of dotnet/aspnetcore#26824)

### Workaround
Prevent VS from opening a browser by disabling "Launch Browser" in the project settings.
![image](https://user-images.githubusercontent.com/612152/109886174-a8211b00-7c4d-11eb-8f15-2c5105464981.png)

Note that if you use the workaround, you can no longer add or hit breakpoints in VS.

### To Reproduce
1. Create a new Blazor WASM project
2. Press F5 to start debugging
3. Press ALT+SHIFT+D to begin a debugging session

### Expected Results
A new browser window will open with a debugging session

### Actual Results
Chrome displays a "WebSocket Disconnected" error

### Environment
Chrome: Version 88.0.4324.190 (Official Build) (64-bit)
Win 10 20H2 19042.804
VS 2019 16.9.0

**Comment by thaystg** [comment]
Without the workaround on Vs you can debug and add breakpoints?
But you would like to debug using Chrome DevTools that is why you are trying to use ALT+SHIFT+D?

**Comment by RobertBouillon** [comment]
> Without the workaround on Vs you can debug and add breakpoints?
> But you would like to debug using Chrome DevTools that is why you are trying to use ALT+SHIFT+D?

I don't recall exactly why I needed this. I believe it was because I needed some debugging feature that wasn't available in Visual Studio and I [came across an article pointing me to this method](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser-1) instead.

**Comment by thaystg** [comment]
I think this is the expected behavior, if you want to debug from chrome you need to start the app without debugging.
![image](https://user-images.githubusercontent.com/4503299/183956654-6684600b-a3dd-4253-857b-18d8a00e38ee.png)
And then press ALT+SHIFT+D to begin a debugging session.

**Comment by RobertBouillon** [comment]
> I think this is the expected behavior

I just want to note the [guidance provided here](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-5.0&tabs=visual-studio#debug-in-the-browser-1) is different.

Is the intention for Visual Studio to provide complete in-process debugging? I cannot currently break in startup code and VS doesn't break on exception, which is why I resorted to chrome as a workaround.

I would like to be able to use my IDE to debug my application. Neither VS nor Chrome provide a fully-featured environment for development, and would prefer to debug WASM from within VS.

**Comment by thaystg** [comment]
VS can break on exceptions if you enable this setting:
![image](https://github.com/dotnet/runtime/assets/4503299/428bae94-c599-4bac-a6ef-dddbd5b9e483)

Also, the expected behavior is this one:
To debug using VS as the IDE: press F5 / Start Debugging
To debug using chrome as the IDE: press ctrl-F5 / Start Without Debugging

Please if you have any other issue let me know.
