### ISSUE TITLE
Improve Error when Desktop Runtime is not installed.

### ISSUE THREAD

**Issue by sr55** [dotnet/runtime#56038]
Hey.

Today, if you don't have Desktop Runtime installed, you get the following error:

![image](https://user-images.githubusercontent.com/628593/126371505-a28305c6-d6a6-4ad6-a0d1-6a6def773cb8.png)

or

![image](https://user-images.githubusercontent.com/628593/126372121-7be1594a-51d3-405d-816c-401834268b7a.png)

The problem we have, is users are regularly confusing .NET and .NET Desktop Runtime. 

Would it be possible to improve these messages to be more explicit as to what is needed and if possible, a more direct download link?

From a users perspective, many won't know the difference between console and desktop applications and will simply choose the first download link.

![image](https://user-images.githubusercontent.com/628593/126372320-7f0c508e-5fc0-4ed1-bfa6-f87deccefc76.png)

If not, if anyone has better advice on how to make this more user friendly that would be helpful.

We are avoiding bundling as we are a small team and won't be able to keep up with the .NET side of security updates.

**Comment by ryalanms** [comment]
Is there anything WPF can do to improve this error message?

**Comment by vitek-karas** [comment]
Thanks for the feedback. This is an ongoing effort to improve the error experience. I created a tracking issue to link together all the issues and asks around this area: https://github.com/dotnet/runtime/issues/56146

Particularly relevant to this specific issue are:
* https://github.com/dotnet/runtime/issues/3816
* https://github.com/dotnet/runtime/issues/36765

**Comment by sr55** [comment]
Thank!  Will subscribe upstream. Feel free to close as duplicate.
