### ISSUE TITLE
Test failure TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific - different port

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56042]
```
System.Net.Sockets.Tests.LocalEndPointTestIPv4Sync.TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific [FAIL]
      Assert.Equal() Failure
      Expected: 127.0.0.1:39706
      Actual:   127.0.0.1:39708
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/LocalEndPointTest.cs(137,0): at System.Net.Sockets.Tests.LocalEndPointTest`1.TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific()
        --- End of stack trace from previous location ---
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54845-merge-176f2e0dc3214643a1/System.Net.Sockets.Tests/console.54af2133.log?sv=2019-07-07&se=2021-08-09T16%3A11%3A35Z&sr=c&sp=rl&sig=TwHCJtlbhuryivUNOBcc5mLYFViBbacNt4UMjBEWfhg%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1246649&view=logs&j=d10aa0b1-a1a0-5e3f-d20a-a36b4319a21f&t=59f04130-a1ae-5fc8-21eb-448a87f814b9

**Comment by karelz** [comment]
Failures 5/20-7/20 (incl. PRs):

Day | Run | OS
-- | -- | --
6/8 | PR #53888 | Ubuntu.1804.ArmArch.Open
7/17 | PR #55862 | Fedora.32.Amd64.Open
7/20 | PR #54845 | Ubuntu.1604.Amd64.Open

**Comment by karelz** [comment]
@antonfirsov is it related to #52141?

**Comment by antonfirsov** [comment]
Yes, essentially the same test bug in a very similar test, linked #56399 to this issue.
