### ISSUE TITLE
BITCAST vs. CAST in faster unsigned division codegen

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#56053]
For faster division, we have a special case of using `BITCAST` for xarch and `CAST` for armarch. See https://github.com/dotnet/runtime/pull/52893/files#diff-8b369256957ebd643910d92e3975f4c94b350010802b23e558ca965680f4907aR5311-R5314

When working on https://github.com/dotnet/runtime/pull/55852 , @sandreenko  and I noticed this and wanted to have an issue so we can track all the conversation here. 

Related references: https://github.com/dotnet/runtime/pull/52893#issuecomment-881680701

**Comment by kunalspathak** [comment]
@pentp

**Comment by sandreenko** [comment]
My understanding is that we want to use `GT_CAST` for all cases and check diffs to see that the generated code for `int<-long` is just changing register from `rax` to `eax` like C++ does.
