### ISSUE TITLE
Failure test:SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56069]
Run [runtime-coreclr libraries-jitstress 20210720.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1247804&view=ms.vss-test-web.build-test-results-tab&runId=37066102&resultId=167287&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open

- SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties

```
**Error message:**
```
System.OutOfMemoryException : Insufficient memory to continue the execution of the program.


Stack trace
   at System.Speech.Internal.SapiInterop.ISpRecognizer.CreateRecoContext(ISpRecoContext& ppNewCtxt)
   at System.Speech.Internal.SapiInterop.SapiRecognizer.<>c__DisplayClass9_0.<CreateRecoContext>b__0() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Internal.SapiInterop.SapiRecognizer.CreateRecoContext() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134
   at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc) in /_/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs:line 446
   at System.Speech.Recognition.SpeechRecognitionEngine.get_RecoBase() in /_/src/libraries/System.Speech/src/Recognition/SpeechRecognitionEngine.cs:line 660
   at SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties() in /_/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs:line 75
```

**Comment by danmoseley** [comment]
@BruceForstall  is this stress mode likely to make OOM more likely?

**Comment by BruceForstall** [comment]
> @BruceForstall is this stress mode likely to make OOM more likely?

Seems very unlikely

**Comment by danmoseley** [comment]
It has only failed once in 2 months. Not enough to investigate. Please reactivate if this happens again.


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= ago(60d)
| where Method == "SpeechRecognitionEngineProperties" 
| where Result == "Fail"
```

|JobId|WorkItemId|EventId|JobName|WorkItemName|WorkItemFriendlyName|Type|Method|ArgumentHash|Arguments|Result|Duration|Exception|Message|StackTrace|Traits|Reason|Attempt|AzurePipelinesTestRunId|AzurePipelinesTestResultId|JobId1|WorkItemId1|JobName1|Name|FriendlyName|Status|PassCount|FailCount|SkipCount|WarnCount|Queued|Started|Finished|ExitCode|ConsoleUri|MachineName|WorkItemType|Uri|PassOnRetryCount|Attempt1|QueueName|LogUploadSeconds|LogSizeBytes|JobId2|Name1|Source|Type1|Build|Creator|System|IsExternal|PullRequestId|Queued1|Started1|Finished1|TestsPass|TestsFail|TestsSkip|ItemsPass|ItemsWarning|ItemsBadExit|ItemsFail|ItemsError|ItemsTimeout|InitialItems|TotalItems|JobList|Properties|QueueName1|ItemsNotRun|TestsPassedOnRetry|ItemsPassedOnRetry|Attempt2|ItemsDeadLetter|QueueAlias|DockerTag|TeamProject|Repository|Branch|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|16703703|714014905||61ba79e8-9cec-4a68-a583-2f4647721162|d7eef6cc-432b-479e-bcb7-8572dcc8339b|System.Speech.Tests|SampleSynthesisTests.SynthesizeRecognizeTests|SpeechRecognitionEngineProperties|||Fail|0.057||System.OutOfMemoryException : Insufficient memory to continue the execution of the program.|   at System.Speech.Internal.SapiInterop.ISpRecognizer.CreateRecoContext(ISpRecoContext& ppNewCtxt)<br>   at System.Speech.Internal.SapiInterop.SapiRecognizer.<>c__DisplayClass9_0.<CreateRecoContext>b__0() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134<br>   at System.Speech.Internal.SapiInterop.SapiRecognizer.CreateRecoContext() in /_/src/libraries/System.Speech/src/Internal/SapiInterop/SapiRecognizer.cs:line 134<br>   at System.Speech.Recognition.RecognizerBase.Initialize(SapiRecognizer recognizer, Boolean inproc) in /_/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs:line 446<br>   at System.Speech.Recognition.SpeechRecognitionEngine.get_RecoBase() in /_/src/libraries/System.Speech/src/Recognition/SpeechRecognitionEngine.cs:line 660<br>   at SampleSynthesisTests.SynthesizeRecognizeTests.SpeechRecognitionEngineProperties() in /_/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs:line 75||||37066102|167287|16703703|714014905|61ba79e8-9cec-4a68-a583-2f4647721162|d7eef6cc-432b-479e-bcb7-8572dcc8339b|System.Speech.Tests|Pass|0|0|0|0|2021-07-20 07:30:42.0680000|2021-07-20 08:28:21.6180000|2021-07-20 08:35:13.7450000|0|https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-61ba79e89cec4a68a5/System.Speech.Tests/console.bc0ce43d.log?sv=2019-07-07&se=2021-08-09T07%3A30%3A37Z&sr=c&sp=rl&sig=sAGdGUjYVzb%2BKsqsnU4Z7Ymx1PngUhQko2wdHcG8sm0%3D|DDARM64-059|other||0|1|windows.10.arm64v8.open|0|0|16703703|61ba79e8-9cec-4a68-a583-2f4647721162|ci/public/dotnet/runtime/refs/heads/main|test/functional/cli/innerloop/||27||1||2021-07-20 07:30:41.8960000|2021-07-20 07:30:41.9120000|2021-07-20 08:40:45.8290000|89003|1|1261|272|0|0|0|0|0|271|272|https://helixde8s23ayyeko0k025g8.blob.core.windows.net/helix-job-31e4e790-c35e-44f5-b47b-03482068d6f162f11b3926d43cc9a/job-list-bae6e5b1-30ff-4c16-9eee-94bbcbffd525.json?sv=2019-07-07&se=2021-08-09T07%3A30%3A27Z&sr=c&sp=rl&sig=jPR1Gx397fBlzON%2FLgiGt5VmbiIAoZIJP36v0DTyNQo%3D|{"operatingSystem":"Windows.10.Arm64v8.Open","configuration":"Release","System.JobAttempt":"1","System.PhaseAttempt":"1","runtimeFlavor":"coreclr","System.PhaseName":"libraries_test_run_checked_coreclr_windows_arm64_Release","BuildNumber":"20210720.1","Reason":"Schedule","architecture":"arm64","System.JobId":"43e320c8-9861-5cff-9f08-1de31d3a4445","scenario":"jitstress1","DefinitionName":"runtime-coreclr libraries-jitstress","AzurePipelinesTestRunId":"37066102","Project":"public","BuildId":"1247804","System.JobName":"__default","System.StageAttempt":"1","DefinitionId":"833","System.StageName":"__default","CollectionUri":"https://dev.azure.com/dnceng/"}|windows.10.arm64v8.open|0|0|0||0|windows.10.arm64v8.open||public|dotnet/runtime|refs/heads/main|
