### ISSUE TITLE
[MacCatalyst] App crash in System.Text.Json.SourceGeneration.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#56085]
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56074-merge-3683c1d883c447d980/System.Text.Json.SourceGeneration.Tests/console.dd4fdc70.log?sv=2019-07-07&se=2021-08-10T10%3A25%3A24Z&sr=c&sp=rl&sig=Juu4DaIYlZxqCYt7nOUC0oPOYZbUKEJDhFJsxqzb2%2Bg%3D

Perhaps, more details in https://github.com/dotnet/runtime/pull/55566

cc @steveisok

**Comment by steveisok** [comment]
Fixed by https://github.com/dotnet/runtime/pull/65652
