### ISSUE TITLE
Static Socket.ConnectAsync can not connect to a DnsEndPoint containing IPv6-mapped address string

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#56099]
The following DualMode `ConnectAsync` code works as expected:

```C#
using Socket server = MakeServer(out int port);
string hostname = "[::FFFF:127.0.0.1]";
DnsEndPoint ep = new DnsEndPoint(hostname, port);
using Socket socket0 = new Socket(SocketType.Stream, ProtocolType.Tcp);
await socket0.ConnectAsync(ep);

static Socket MakeServer(out int port) {
    Socket server = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
    server.Bind(new IPEndPoint(IPAddress.Loopback, 0));
    port = ((IPEndPoint)server.LocalEndPoint).Port;
    server.Listen();
    _ = server.AcceptAsync();
    return server;
}
```

while "equivalent" `Socket.ConnectAsync(AddressFamily,SocketType,SocketAsyncEventArgs)` connect code fails on both Windows and Linux:

```C#
using Socket server = MakeServer(out int port);
string hostname = "[::FFFF:127.0.0.1]";
DnsEndPoint ep = new DnsEndPoint(hostname, port);

SocketAsyncEventArgs a = new SocketAsyncEventArgs { RemoteEndPoint = ep };

ManualResetEvent mre = new ManualResetEvent(false);
a.Completed += (_, __) =>
{
    mre.Set();
};

if (Socket.ConnectAsync(SocketType.Stream, ProtocolType.Tcp, a))
{
    mre.WaitOne();
}

if (a.SocketError != SocketError.Success)
{
    throw new SocketException((int)a.SocketError);
}
```

The reason is that the internal implementation [is creating a non-dual-mode socket](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs#L712) for which the underlying native connect calls fail to connect to an IPV6-mapped IPv4 endpoint. (`10049 - WSAEADDRNOTAVAIL` on Windows).

We can easily fix this by detecting `address.IsIPv4MappedToIPv6` and either creating an IPv4 socket, or enabling `DualMode` in such cases.

**Comment by karelz** [comment]
@antonfirsov how did you discover it? Is it a regression against 5.0?
I know we made changes in the space during 6.0 ...

**Comment by antonfirsov** [comment]
This is an ancient issue in the Socket class, present in all previous .NET Core versions and .NET Framework. It stopped impacting SocketsHttpHandler since 5.0, because we are using DualMode sockets  now instead of the static ConnectAsync method.

**Comment by karelz** [comment]
OK, moving it to 7.0 in that case.
