### ISSUE TITLE
TryAddEnumerable fails with service descriptors created with constructor and imlementation factory

### ISSUE THREAD

**Issue by billybraga** [dotnet/runtime#56105]
### Description

Since ServiceDescriptor's constructor that takes the implementation factory takes a func that returns `object` (`Func<IServiceProvider, object>`), if we call it directly with something like `x => new MyService()`, `ImplementationFactory`'s type becomes `Func<IServiceProvider, object>`.

This causes `TryAddEnumerable` to fail because `GetImplementationType()` returns `object`.

Repro:

```
public class MyService : IMyService {}

var services = new ServiceCollection();
services.TryAddEnumerable(
    new ServiceDescriptor(
        typeof(IMyService),
        _ => new MyService(),
        ServiceLifetime.Singleton
    )
);
```

The previous code snippet throws the following exception:

```
Unhandled exception. System.ArgumentException: Implementation type cannot be 'System.Object' because it is indistinguishable from other services registered for 'TryAddEnumerableTest6.IMyService'. (Parameter 'descriptor')
   at Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(IServiceCollection services, ServiceDescriptor descriptor) in Microsoft.Extensions.DependencyInjection.Abstractions.dll
...
```

There are also other related problems like duplicate implementations if we use `services.Add(new ServiceDescriptor(x => xxx` and `services.TryAddEnumerable(ServiceDescriptor.Singleton<IMyService, MyService>`.

### Configuration

I tested dotnet 5 and dotnet 6 preview 6 on Windows.

**Comment by davidfowl** [comment]
How would you expect this to work?

**Comment by billybraga** [comment]
Maybe the constructor should be private or protected to avoid confusion (since we can't call it directly with a lambda) and force people to use `ServiceDescriptor.Singleton(...)` and other factory methods, which fork fine since the parameter is generic (`Func<IServiceProvider, TService>`).

**Comment by eerhardt** [comment]
Can you cast to workaround this issue?

```
public class MyService : IMyService {}

services.TryAddEnumerable(
    new ServiceDescriptor(
        typeof(IMyService),
        (Func<IServiceProvider, MyService>)(_ => new MyService()),
        ServiceLifetime.Singleton));
```

**Comment by billybraga** [comment]
Yes, seems to work.

**Comment by eerhardt** [comment]
I don't believe we can do anything else here. Is the workaround above acceptable? Or to use the `Describe` factory method to create the ServiceDescriptor.

Note that we can't hide the public API anymore, since that would be a breaking change. And it is valid to use that API when not using `TryAddEnumerable`.

**Comment by billybraga** [comment]
I understand. Maybe this could be documented somewhere.
