### ISSUE TITLE
System.Net.Dns.GetHostName gives Socket Exception

### ISSUE THREAD

**Issue by KratiChauhan** [dotnet/runtime#56132]
We have been using "System.Net.Dns.GetHostName()" in our application (using framework V4.7). It works well on my development environment, but when I create the build and test on the other machine (windows 10 machine), we get below error.

SocketException :
Message :  A system call has failed
Error Code :  10107
System.Net.Sockets.SocketException (0x80004005): A system call has failed
   at System.Net.Sockets.Socket.InitializeSockets()
   at System.Net.Dns.GetHostName()

**Comment by karelz** [comment]
Hello @KratiChauhan. We do not track .NET Framework issues in this repo -- it is only for .NET Core / .NET 5+.
Based on your callstack, it seems there is something very wrong with your machine. The OS is unable to initialize parts of its subsystem. I would recommend to repair the machine / reimage it.
If it is persistent, you can try to check which OS initialization fails by debugging into .NET Framework.
Here is related code:
- https://referencesource.microsoft.com/#System/net/System/Net/DNS.cs,459
- https://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,5954

Closing as unrelated to this repo.

**Comment by KratiChauhan** [comment]
Thanks for your suggestion. Will try them. I am however able to resolve the name when I run the powershell command [System.Net.Dns]::GetHostName().
Also the previous version of application using the command works but not the new application that we create.
