### ISSUE TITLE
Incorrect documentation for SslClientAuthenticationOptions's CertificateRevocationCheckMode

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56136]
`IntelliSense` is reporting that the default value for the revocation mode is `Online`.
![image](https://user-images.githubusercontent.com/25307628/126609834-6205c14a-8708-4edd-88a7-9e737d4fb2e4.png)
![image](https://user-images.githubusercontent.com/25307628/126611660-88267448-7228-485a-9343-e2ad5e9b6a56.png)

The actual default is `NoCheck`.
Where is this comment coming from? It's not in the source code as far as I can tell.

The [online documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions.certificaterevocationcheckmode?view=net-6.0#property-value) correctly states it's `NoCheck`.

(`SslServerAuthenticationOptions` shares the same problem)

**Comment by karelz** [comment]
IntelliSense should be harvested from online docs AFAIK - @jeffhandley do we have someone to check with?

**Comment by filipnavara** [comment]
That's quite worrying. We have been relying on the default being `Online` in our product.

**Comment by karelz** [comment]
Yep, seems to be `NoCheck` by default in 6.0, 5.0 and 3.1:

6.0:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Security/src/System/Net/Security/SslClientAuthenticationOptions.cs#L14
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Security/src/System/Net/Security/SslServerAuthenticationOptions.cs#L12

5.0:
https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Security/src/System/Net/Security/SslClientAuthenticationOptions.cs#L14
https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Security/src/System/Net/Security/SslServerAuthenticationOptions.cs#L12

3.1:
https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.Security/src/System/Net/Security/SslClientAuthenticationOptions.cs#L15
https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.Security/src/System/Net/Security/SslServerAuthenticationOptions.cs#L13

@filipnavara have you seen impact on your product? (from your customers) Or is that recent assumption you made?

**Comment by karelz** [comment]
Ah, the documentation was fixed in February 2021: https://github.com/dotnet/dotnet-api-docs/pull/4920 ... it didn't make it into IntelliSense yet. That happens with major releases, like 6.0.
@jeffhandley it is now solved.

Closing as addressed.

**Comment by filipnavara** [comment]
> have you seen impact on your product?

It's something we changed quite recently so it was likely released only to very small amount of customers and our testers. We were cleaning up the code to remove traces of old SSL/TLS versions and to switch most options to their system/framework defaults. This was done in response to Windows 11 enabling TLS 1.3 by default and old SSL workaround no longer being effective on any modern systems.

**Comment by karelz** [comment]
@filipnavara looks like you have reasonable way to react in your product then. Sorry for the trouble!
