### ISSUE TITLE
TypeInfo.GetDeclaredMethods() / GetDeclaredABC() methods behavior inconsistent with the documentation on it

### ISSUE THREAD

**Issue by xiaomi7732** [dotnet/runtime#56131]
### Description
According to the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.typeinfo.getdeclaredproperty?view=net-5.0), quotes:
> Returns an object that represents the specified **public** property declared by the current type.

However, the APIs actually get back **Non-Public** members as well, for example:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Reflection/TypeInfo.cs#L30

Which is the expected behavior? Is it just doc out of date?

**Comment by buyaa-n** [comment]
I think that behavior is changed, seems just the same attribute is applied to all members, should we remove that `DynamicallyAccessedMemberTypes.NonPublicProperties` part @eerhardt?

**Comment by eerhardt** [comment]
Looking at the code, it finds NonPublic members. See `DeclaredOnlyLookup`:

https://github.com/dotnet/runtime/blob/cf52b7e38d28b7e28358cee052effe0ed47efb2e/src/libraries/System.Private.CoreLib/src/System/Reflection/TypeInfo.cs#L34-L46

https://github.com/dotnet/runtime/blob/cf52b7e38d28b7e28358cee052effe0ed47efb2e/src/libraries/System.Private.CoreLib/src/System/Reflection/TypeInfo.cs#L147

**Comment by buyaa-n** [comment]
> Looking at the code, it finds NonPublic members.

Thanks, all APIs in the doc says they return a "public" member, apparently need to check all APIs and update the doc instead

**Comment by pedrobsaila** [comment]
Hi a made a PR for this issue dotnet/dotnet-api-docs#7090
