### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#56140]
### Background and motivation

In many cases, especially for serialization, using reflection gives pure performance.
We should use dictionaries or something like that for caching type accordance, which also not very fast.
Generics sometimes solve problem, but not always.

It would be great to have possibility to call generics by Type in runtime.

### API Proposal

```c#
public interface System.ITypeToGenericProxy 
{
    object? Invoke<T>(T? target) 
}
```

// Add new method to System.Type class:
```c#
public object? InvokeGenericProxy(ITypeToGenericProxy  proxy, object? target)
{ 
   // intrinsic return proxy.Invoke<T*>(target)
   // where T* type parameter generated from this type
}
```

### API Usage

```c#
public class MySerializer: ITypeToGenericProxy
{
  // ITypeToGenericProxy implementation
  public object? Invoke<T>(T target)
  {
      if (target is null) return Deserizlize<T>();
      Serialize(target);
      return null;
  }
  
  public Stream Stream { get; set; }

  // read type header and deserialize object of this type
  public object? Deserialize() {
     if (NullFormatter.Instance.Read(Stream)) return null;
     var type = TypeFormatter.Instance.Read(Stream);
     return type.InvokeGenericProxy(this, null); // will finally call Deserialize<T>
  }

  // this method can deserialize T, chilren classes of T, or T can be interface
  public T? Deserialize<T>()  {
     if (NullFormatter.Instance.Read(Stream)) return null;
     var type = TypeFormatter.Instance.Read(Stream);
     if (type == typeof(T) return Formatter<T>.Read(Stream);
     else return (T) type.InvokeGenericProxy(this, null);
  }

  public void Serialize(object data) { 
     if (data is null) NullFormatter.Instance.Wrtite(Stream);
     else data.GetType().InvokeGenericProxy(this, data); // will finally call Serialize<T>
  }

  public void Serialize<T>(T data) {
     if (data is null) { NullFormatter.Instance.Wrtite(Stream); return; }
     var type = data.GetType();
     if (typeof(T) == type) {
         // data exactly is T
         TypeFormatter.Instance.Write<T>(Stream);
         Formatter<T>.Instance.Write(Stream, data);
     }
     // T is interface or data is derivative of T class
     else type.InvokeGenericProxy(this, data);
  }

}
```

**Comment by huoyaoyuan** [comment]
> `var type = TypeFormatter.Instance.Read(Stream);`

Reading a `Type` from serializable data is extremely dangerous. Binary serialization is going to be removed to prevent such usage. Any use case containing such behavior shouldn't be considered.

**Comment by kefyru** [comment]
> > `var type = TypeFormatter.Instance.Read(Stream);`
> 
> Reading a `Type` from serializable data is extremely dangerous. Binary serialization is going to be removed to prevent such usage. Any use case containing such behavior shouldn't be considered.

Yes it is, but it can be use for internal (closed) protocols or with security checking.
In this example TypeFormatter just read some id of type and resolve type by this id.
This does anyway but with reflection.

**Comment by svick** [comment]
> We should use dictionaries or something like that for caching type accordance, which also not very fast.

What makes you think the proposed method would be any faster than a dictionary?

**Comment by kefyru** [comment]
> > We should use dictionaries or something like that for caching type accordance, which also not very fast.
> 
> 
> 
> What makes you think the proposed method would be any faster than a dictionary?

Generic call takes about 2ns, dictionary lookup by type takes 30-40ns

**Comment by svick** [comment]
> > > We should use dictionaries or something like that for caching type accordance, which also not very fast.
> > 
> > 
> > What makes you think the proposed method would be any faster than a dictionary?
> 
> Generic call takes about 2ns, dictionary lookup by type takes 30-40ns

Yeah, but the method you're proposing would need to do a lot more than a simple generic call. So how do you suggest it could be implemented in a way that makes it faster than a dictionary?

**Comment by kefyru** [comment]
> Yeah, but the method you're proposing would need to do a lot more than a simple generic call. So how do you suggest it could be implemented in a way that makes it faster than a dictionary?

I could answer if i knew how generic methods builds in runtime (under the hood).
All i know, MakeGenericMethod(...) in reflection do a lot of work and finally calls internal GetStubIfNeeded(...) which i think builds generic method implementation with needed signature...

**Comment by kefyru** [comment]
> Yeah, but the method you're proposing would need to do a lot more than a simple generic call. So how do you suggest it could be implemented in a way that makes it faster than a dictionary?

Ok, than would be enough to have type instance id.

I.e every type instantiating in app domain gets id from it, in order of instantiation.

AppDomain {
internal static int _typeInstanceId;
internal static int GetTypeInstanceId => ++_typeInstanceId;
...}

Type {
internal int _instanceId = Appdomain.CurrentDomain.GetTypeInstanceId;
Public int InstanceId => _instanceId;
...}

**Comment by acaly** [comment]
Optimization should be applied to bottlenecks first. There is no point to optimize a dictionary lookup into an array indexing while you have a much much heavy IO before it.

**Comment by DemiMarie** [comment]
> > `var type = TypeFormatter.Instance.Read(Stream);`
> 
> Reading a `Type` from serializable data is extremely dangerous. Binary serialization is going to be removed to prevent such usage. Any use case containing such behavior shouldn't be considered.

As a security researcher, thank you!
