### ISSUE TITLE
R2R jobs should not pass -O to crossgen2

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#56148]
When -O is passed, crossgen2 will ignore the assembly's "debug" bit. We have some JIT tests that rely on this bit to be respected which are currently disabled because of this behavior since our R2R jobs pass -O. Some more discussion in #55062.

cc @dotnet/crossgen-contrib

**Comment by MichalStrehovsky** [comment]
The jobs should be changed not to pass `-O`. The `-O` was required to optimize before #44514 got merged.

The `-O` was supposed to be removed per https://github.com/dotnet/runtime/pull/44514#issuecomment-726425655 but it probably slipped through the cracks.

**Comment by jakobbotsch** [comment]
The -O parameter was readded in #49867 it looks like.

**Comment by MichalStrehovsky** [comment]
Ah okay, I don't know what going on there then. I'll leave that to the crossgen team.

**Comment by mangod9** [comment]
@jakobbotsch, is this a blocker for .net 6?

**Comment by jakobbotsch** [comment]
@mangod9 No, the test is just disabled for R2R jobs at the moment. Reenabling it can wait.

**Comment by mangod9** [comment]
Ok thanks will move to 7

**Comment by davidwrighton** [comment]
Consider doing this during the downtime between 7 and 8.

**Comment by ivdiazsa** [comment]
Just to confirm, should we stop passing `-O` altogether to crossgen2, or just for the R2R jobs?

**Comment by davidwrighton** [comment]
Looking at Simon's original change it appears he didn't handle the composite case, so composite builds might still need explicit control. I'd like you to look into that and verify if you make a change here, that we don't regress composite compilation. In addition, if we are going to disable passing -O to crossgen2 in our tests, we should probably consider not passing it in the SDK, so we would need to validate all of our scenarios continue to work correctly if we do that.
