### ISSUE TITLE
[RyuJIT][Linux][Inliner] In-lining heuristic needs to be tuned for Linux ABI

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#5615]
On Linux, there are no callee saved floating-point regs.  This suggests that in-liner multipliers or heuristics needs to be tuned to in-line methods with floating-point args more than on Windows.

category:cq
theme:inlining
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
Having some compelling examples would be a good start.

I'm (still) somewhat ambivalent about tuning the heuristics for particular ABIs as I worry it will lead to cross-plaform perf anomalies. That being said, when we do work on inlining heuristics, we need to be careful to blend them well across ISAs and ABIs.

**Comment by AndyAyersMS** [comment]
Think we can close this.
