### ISSUE TITLE
[API Proposal]: IServiceProvider should implement IDisposable

### ISSUE THREAD

**Issue by lord-executor** [dotnet/runtime#56150]
### Background and motivation

Trying to create a compliant implementation of Ninject that works as a service provider, I have come across a small inconsistency.

The [DependencyInjectionSpecificationTests](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs) already **assume** that the service provider implements `IDisposable`, but the `IServiceProvider` interface does not make that clear. Any service provider implementation has to add the `IDisposable` separately.

Currently, the `DependencyInjectionSpecificationTests.DisposesInReverseOrderOfCreation` method contains the hard assumption that the service provider implements `IDisposable` on [line 793](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/DependencyInjectionSpecificationTests.cs#L793)

```C#
[Fact]
public void DisposesInReverseOrderOfCreation()
{
    // Arrange
    var serviceCollection = new TestServiceCollection();
    // ...
    var serviceProvider = CreateServiceProvider(serviceCollection);

    // ...

    // Act
    ((IDisposable)serviceProvider).Dispose();

    // Assert
    // ...
}
```

It also looks like this was at some point an _optional_ requirement since in other tests like `DisposingScopeDisposesService` **check** for an `IDisposable` implementation with code like
```C#
var disposableProvider = provider as IDisposable;
if (disposableProvider != null)
{
    disposableProvider.Dispose();
    // ...
}
```

Making `IServiceProvider` implement `IDisposable` would make the API more clear and would allow for some cleanup of the compliance tests.

### API Proposal

```C#
namespace System
{
    public interface IServiceProvider : IDisposable
    {
        object GetService(Type serviceType);
    }
}
```     

### API Usage

```C#
using (var provider = new ServiceProvider(services, ServiceProviderOptions.Default))
{
    // ... get some services
}
```     

### Risks

None that I can see since that is already implicitly covered by `DependencyInjectionSpecificationTests.DisposesInReverseOrderOfCreation`

**Comment by eerhardt** [comment]
The [ISerivceProvider](https://docs.microsoft.com/dotnet/api/system.iserviceprovider) interface has shipped since the .NET Framework 1 days. It is part of netstandard. We can't change it as it would be a massive breaking change.

See https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-changes.md#bucket-1-public-contract

> Adding an interface to the set of base types of an interface

Closing as this isn't a change we can make.

**Comment by lord-executor** [comment]
Hmm... Fair enough. That _would_ be a breaking change with netstandard. But, isn't requiring implementations of `IServiceProvider` to also implement `IDisposable` _also_ a bit of a breaking change? I mean technically, the compliance tests are quite quesionable since they rely on the fact that `ServiceProvider` behaves like an `IServiceScope` if you cast it as an `IDisposable`.

Of course I see the constraints of maintaining some form of backwards compatibility, but trying to replace a DI container that behaves in such weird ways is.... not exactly easy. It shouldn't be that hard to find out what a "proper" implementation should actually do.

**Comment by eerhardt** [comment]
We can definitely change the compliance tests to be consistent - in this case, don't do hard casting, but instead use `is` or `as` checks. I agree it shouldn't be a hard constraint for all `IServiceProvider` implementations to be `IDisposable`.

**Comment by lord-executor** [comment]
Sounds reasonable enough. I can create a new bug ticket and create a small PR for that. Would that be the way to proceed?

The tricky bit is going to be trying to find out if that assumption is used anywhere else in the code, but I guess running all the tests should already cover the vast majority of use cases.
