### ISSUE TITLE
.NET 6 Android AOT fails on certain folder names

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#56163]
### Description

Create a `dotnet new android` project in a folder named such as `BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True`.

Build with `-c Release -p:RunAOTCompilation=true`, and you get the error:

```
Precompiling failed for C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll: Error: Loaded assembly 'C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle And├£ml├ñ├╝ts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll' doesn't match original file name 'C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle And▄mlΣⁿts_arm64-v8a_False_True\obj\Release\android-arm64\linked\System.Private.CoreLib.dll'. Set MONO_PATH to the assembly's location. [C:\src\xamarin-android\bin\TestDebug\temp\BuildAotApplicationAndBundle AndÜmläüts_arm64-v8a_False_True\UnnamedProject.csproj]
```

A screenshot of the `.binlog` viewer shows odd characters as well:

![image](https://user-images.githubusercontent.com/840039/126675644-bb5fac69-bef1-4fc9-a57f-4a8b184ba98f.png)

Logs: [msbuild.zip](https://github.com/dotnet/runtime/files/6863886/msbuild.zip)

### Configuration

```
> dotnet --version
6.0.100-rc.1.21369.3
```

I believe this would also happen in Preview 7.

### Regression?

No, Android AOT is a new feature.

/cc @akoeplinger @steveisok

**Comment by SamMonoRT** [comment]
@steveisok @vargaz - any update ?

**Comment by vargaz** [comment]
Can someone who is on windows look at this ?

**Comment by lewing** [comment]
cc @radekdoulik

**Comment by lewing** [comment]
I think we've seen some other strange failures with encoding of filenames on windows in the build.

**Comment by radekdoulik** [comment]
> 
> 
> I think we've seen some other strange failures with encoding of filenames on windows in the build.

I know about this one https://github.com/dotnet/runtime/issues/52108. It is happening during runtime though.

**Comment by SamMonoRT** [comment]
Removing the area-Codegen-AOT-mono label.

**Comment by SamMonoRT** [comment]
@lewing @steveisok - this is something we can discuss on Monday, not too certain if this is a release blocking or a 7.0 issue at the moment.

**Comment by steveisok** [comment]
I think this is something we should try to fix for 6.0.

**Comment by lewing** [comment]
I'm pretty sure this is the AOT compiler assuming something that isn't always true about the character encoding of the filesystem on windows so I doubt this is android specific.

**Comment by lewing** [comment]
@jonathanpeppers what locale is your system using?

**Comment by jonathanpeppers** [comment]
I'm using `en-US`. We have a unit test from legacy Xamarin.Android testing this scenario:

https://github.com/xamarin/xamarin-android/blob/f7d32102cc3ada67aa12cc0beed2cf97226f41b3/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs#L158-L161

I saw it fail on CI as well as locally.

I think we have this test because usernames could commonly have special characters, and VS puts new projects in `%userprofile%\source\repos` by default.

**Comment by vargaz** [comment]
So this used to work in xamarin.android on windows ?

**Comment by jonathanpeppers** [comment]
Yes, these tests still pass for legacy Xamarin.Android on Windows.

We setup a symbolic link named `SDK Ümläüts` to an Android NDK as well:

https://github.com/xamarin/xamarin-android/blob/f7d32102cc3ada67aa12cc0beed2cf97226f41b3/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AotTests.cs#L18-L22

Neither were working with .NET 6 yet.

**Comment by radekdoulik** [comment]
I am able to reproduce it with our samples. Building the bench sample in `src\mono\sample\wasm\browser-bench-řeřicha` ends with:

    Error: Loaded assembly '...\src\mono\sample\wasm\browser-bench-┼Öe┼Öicha\bin\browser-wasm\publish\System.Private.CoreLib.dll' doesn't match original file name '...\src\mono\sample\wasm\browser-bench-°e°icha\bin\browser-wasm\publish\System.Private.CoreLib.dll'. Set MONO_PATH to the assembly's location.

**Comment by radekdoulik** [comment]
The non-utf8 path is being created in the `mono_path_canonicalize` which uses the `g_get_current_dir` to retrieve current working directory. On windows it is returning the path in the system encoding, like CP-1250 for example. So the above PR adds win32 implementation, which uses native call to retrieve utf-16 string and converts it to utf-8.

I didn't checked the legacy xamarin.android on windows. IIRC it was built with mingw though, so that might have different `getcwd` implementation and thus returning the string in utf-8?

**Comment by jonathanpeppers** [comment]
This isn't actually fixed in `dotnet new android` projects, I think this will fix it: https://github.com/dotnet/runtime/pull/62725
