### ISSUE TITLE
`kind == Overwrite` assert in jitstress

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#56174]
The failures look like:
```
      Assert failure(PID 1028 [0x00000404], Thread: 3768 [0x0eb8]): Assertion failed 'kind == Overwrite' in 'Microsoft.CodeAnalysis.CodeGen.ILBuilder:RealizeBlocks():this' during 'Do value numbering' (IL size 537)
      
          File: D:\workspace\_work\1\s\src\coreclr\jit\jithashtable.h Line: 238
```

and are common for all platforms, they appeared in https://dev.azure.com/dnceng/public/_build/results?buildId=1252387&view=ms.vss-test-web.build-test-results-tab, changes in that batch https://dev.azure.com/dnceng/public/_traceability/runview/changes?currentRunId=1252387

PTAL @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Probably my change (#55936)
