### ISSUE TITLE
Failure test: JIT\\jit64\\regress\\vsw\\373472\\test_il\\test_il.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56197]
Run: [runtime-coreclr jitstress 20210721.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1252387&view=ms.vss-test-web.build-test-results-tab&runId=37177630&paneView=debug&resultId=101163)

Failed test:
```
CoreCLR windows x86 Checked zapdisable @ Windows.10.Amd64.Open

- JIT\\jit64\\regress\\vsw\\373472\\test_il\\test_il.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\9F6208D2\w\B704099E\uploads\Reports\JIT.jit64\regress\vsw\373472\test_il\test_il.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\9F6208D2\p\corerun.exe"  test_il.dll
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at StrideTest.Test2() in test.exe:token 0x6000003+0x2
Test2 failed
test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
at StrideTest.Test3() in test.exe:token 0x6000004+0x2
Test3 failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9F6208D2\p
C:\h\w\9F6208D2\w\B704099E\e\JIT\jit64\regress\vsw\373472\test_il\test_il.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._regress_vsw_373472_test_il_test_il_._regress_vsw_373472_test_il_test_il_cmd() in JIT.jit64.XUnitWrapper.dll:token 0x600069e+0x284
```

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch PTAL.

**Comment by jakobbotsch** [comment]
This test is allocating arrays of 576 MB and seems to be failing intermittently only in 32-bit. I'm inclined to believe it's failing because there is not always a contiguous block of memory of this size. On my machine the test seems to work.

Given that this is a regression test for jit64 I'm not sure how valuable it is to keep the test in coreclr. The .cs version of the test has this comment at the top:
```csharp
// This test is used to try out very large decrementing loop strides.  The strides cannot be negated if the integer
// is too large.  For example, a stride of 0xA0000000 cannot be turned into a signed number.  For the most
// part, other things prevent us from getting to OSR with a condition like this but it's good to have
// coverage for large strides.
```

Not sure if the optimization it is talking about is one we do in RyuJIT at all. @BruceForstall do you know? The file is here: https://github.com/dotnet/runtime/blob/main/src/tests/JIT/jit64/regress/vsw/373472/test.cs

**Comment by BruceForstall** [comment]
> Not sure if the optimization it is talking about is one we do in RyuJIT at all. @BruceForstall do you know?

It's talking about JIT64's Operator Strength Reduction, not RyuJIT's On Stack Replacement.

Test1 passed (in this case), meaning we could allocate that memory block at least once. Maybe between tests we could force GC (`GC.Collect()`) (also, prevent inlining of the tests to avoid extending lifetimes across the Collect call)?

True, I'm not sure how applicable the test is to RyuJIT, but it might be an interesting extreme boundary case to keep.

**Comment by jakobbotsch** [comment]
I don't think we can reliably make it work, e.g. #8661 and #10002 are the same issue where it also fails in test1.
An alternative is to catch OutOfMemoryException and succeed if we want to keep the test.  Then at least it will run when there is enough memory. Or alternative, we can disable it on 32-bit test runs. What do you think?

**Comment by BruceForstall** [comment]
Maybe we should just disable the test. It's too bad we don't have a "pri-2" category of tests that is rarely run due to potential issues, but potentially useful for catching extreme cases.
