### ISSUE TITLE
latest system.text.json (6.0.0-rc.1.21372.4) does not support net5.0

### ISSUE THREAD

**Issue by jasond-s** [dotnet/runtime#56205]
### system.text.json 6.0.0-rc.1.21372.4 does not support net5.0

Have download the latest build for the nuget package inline with this article https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/ which states that it is compatible with net5.0 but appears to not be.

![supported_runtime_list](https://user-images.githubusercontent.com/4137207/126756965-95fd87f4-ddbd-41b8-bb4d-1f1878bacc43.png)

### Configuration

My project is a net5.0 console project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="6.0.0-rc.1.21372.4" /> <!-- borks -->
    <PackageReference Include="Utf8Json" Version="1.3.7" />
  </ItemGroup>

</Project>
```

### Regression?

Yes the package previously supported the net5 runtime.

### Other information

I wanted to check if the `JsonSourceGenerationOptionsAttribute` supported subclassing so that you don't have to copy all those setting to every class they are used and you could have `MyJsonSourceGenerationOptionsAttribute` but I am a bit blocked in verifying. A quick code review looks like you cannot, which would be very very sad.

**Comment by filipnavara** [comment]
It will fallback to the `netcoreapp3.1` assets (`.NETCoreApp, Version=3.1` on your screenshot) so it should build on `net5.0` just fine.

**Comment by jasond-s** [comment]
So I just need to find these guys in the RC builds I guess (they aren't published)?

System.Runtime.CompilerServices.Unsafe 6.0.0-rc.1.21372.4
System.Text.Encodings.Web 6.0.0-rc.1.21372.4

Will the fall-back to `NETCoreApp3.1` still include the source generators though? I would have thought that build would not hit the `BUILDING_SOURCE_GENERATOR` preprocessor arg.

**Comment by filipnavara** [comment]
None of the `6.0.0-rc.1` packages are in the NuGet.org feed because Preview 7 and RC 1 was not released yet. You can reference the internal feeds by providing custom [NuGet.config](https://github.com/dotnet/runtime/blob/main/NuGet.config) file.

**Comment by filipnavara** [comment]
I don't know how are the source generators published but the [project file](https://github.com/dotnet/runtime/blob/7b19ccefccb4d116a64bf09c9bb1db3dd1df35e8/src/libraries/System.Text.Json/gen/System.Text.Json.SourceGeneration.csproj#L2-L17) for them targets `netstandard2.0` and includes the `BUILDING_SOURCE_GENERATOR` definition.

**Comment by jasond-s** [comment]
> None of the `6.0.0-rc.1` packages are in the NuGet.org feed because Preview 7 and RC 1 was not released yet. You can reference the internal feeds by providing custom [NuGet.config](https://github.com/dotnet/runtime/blob/main/NuGet.config) file.

This was all I needed, massive thanks. And no, you can't subclass the options.
