### ISSUE TITLE
LoggerMessageAttribute generated source does not respect escaped characters and does not compile

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/runtime#56203]
### Description

The source code generated for the following log method does not compile.

```cs
[LoggerMessage(
    EventId = 1,
    Level   = LogLevel.Debug,
    Message = "This is a log message: \"{Value1}\"")]
public static partial void SomeEvent(ILogger logger, string value1, string value2);
```

The fact that this log method includes parameters that are not encoded into `Message` forces a custom log state type to be generated, with the following code:

```cs
public override string ToString()
{
    var Value1 = this._value1;

    return $"This is a log message: "{Value1}"";
}
```

### Configuration

Running .NET SDK 6.0.100-preview.6.21355.2 with version 6.0.0-preview.6.21352.12 of Microsoft.Extensions.Logging.Abstractions.

**Comment by maryamariyan** [comment]
for your sample code, the in the error list you should see:

```
warning SYSLIB1015: Argument 'value2' is not referenced from the logging message
```

which points to what needs to get fixed.

**Comment by maryamariyan** [comment]
Thanks for the report, here's another repro code:

```c#
        [LoggerMessage(EventId = 1, Message = "This is a log message: {Value1} {Value2}")]
        public static partial void SomeEvent(ILogger logger, LogLevel logLevel, string value1, string value2);
```
