### ISSUE TITLE
Please consider not throwing an exception when Process.Kill() is called for a process that exited previously

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/runtime#56214]
This is inspired by an earlier issue https://github.com/dotnet/runtime/issues/16848 If I want to wait for a running process to exit in some short period of time and terminate it if it fails to exits on itself then I'm likely to write code like this:

    if(!process.WaitForExit(5000))
    {
        process.Kill();
    }
    process.Dispose();

however if the process exits right after `WaitForExit()` returns "it's still running" then call to `Kill()` will yield an `InvalidOperationException`. This is the documented behavior. This causes a lot of extra code to be necessary to deal with this race condition.

Is the current behavior really needed? The purpose of `Kill()` is to get rid of the process. If the process exited - okay, less work, just do nothing. Who would want the exception instead of just doing nothing?

Yes, that would change the contract but it looks like a change for the better.

Could you please consider changing this rather inconvenient behavior?

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/dotnet/runtime/issues/28672, which was addressed in .NET Core 3.x.

@Dmitry-Me Are you still seeing this behavior in recent versions of .NET?

**Comment by Dmitry-Me** [comment]
@GrabYourPitchforks Clearly there was a change in behavior somewhere between core2.1 and core3.1 "Classic" .NET framework (4.7.2) is still with old behavior. Anyway this change is not documented - this https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-5.0 still mentions old behavior. This is why I was not aware of the change.

**Comment by danmoseley** [comment]
@Dmitry-Me any interest in offering an edit to https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-5.0  ? (click pencil button in top right)

**Comment by Dmitry-Me** [comment]
I created this defect https://github.com/dotnet/dotnet-api-docs/issues/6966

**Comment by adamsitnik** [comment]
Let's use dotnet/dotnet-api-docs#6966 for tracking the remaining work (updating docs)

**Comment by GSPP** [comment]
Great that this is already there. Any process can die at any time. Any correct usage of `WaitForExit` therefore requires a pointless try-catch.
