### ISSUE TITLE
With .Net 6 Preview7, failed to open '/etc/dotnet/install_location' when running dotnet tool

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#56219]
Repro steps:

1. Install .NET 6 Preview7 SDK(6.0.100-preview.7.21369.19) 
2. Run below commands:
dotnet tool install -g doTNetsay
dotnet tool list -g
dotnetsay

Expected Result:
Tool dotnetsay can be run successfully 

Actual Result:
Failed to open '/etc/dotnet/install_location' when running dotnet tool:
`The install_location file ['/etc/dotnet/install_location'] failed to open: No such file or directory.`

![image](https://user-images.githubusercontent.com/87680983/126617889-efea00dc-a793-4dca-9522-310f01f12c69.png)

Note: Not repro Windows10

Dotnet info:
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21369.19
 Commit:    cdbd475cb6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100-preview.7.21369.19/

Host (useful for support):
  Version: 6.0.0-preview.7.21368.2
  Commit:  8d3afa3a4a

.NET SDKs installed:
  6.0.100-preview.7.21369.19 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21369.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21368.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by vitek-karas** [comment]
I'm gonna give this a shot of fixing (to refresh my linux debugging non-skills).

**Comment by agocke** [comment]
Looks like that error should not be printed, but it is not causing any other side effects (the process is not exiting) so I don't think this is blocking

**Comment by vitek-karas** [comment]
It is blocking - we can't alter an output (stderr or stdout) of a console app if it works - the entire functionality of the app might be to print something to stderr and if something else tries to parse it it would be broken.

**Comment by mateoatr** [comment]
We must change this to info:

https://github.com/dotnet/runtime/blob/09e1608667049294ba74a1e1fbee39dc9d8f194b/src/native/corehost/hostmisc/pal.unix.cpp#L441-L445

**Comment by agocke** [comment]
This is blocking Preview 7?

**Comment by vitek-karas** [comment]
I have a candidate fix https://github.com/dotnet/runtime/compare/main...vitek-karas:FixErrorOnInstallLocation?expand=1

Trying to test it.

**Comment by vitek-karas** [comment]
Blocking Preview 7 - don't know - it might. It's pretty bad and there's really no work around (creating the file is one, but one needs to know what to put into it).
