### ISSUE TITLE
Build Instructions for Raspberry Pi devices

### ISSUE THREAD

**Issue by kphillisjr** [dotnet/runtime#5621]
I was looking over the documentation and noticed that there is no information how to run CoreCLR on the [Raspberry Pi](https://en.wikipedia.org/wiki/Raspberry_Pi).
- [ ] Instructions to build/run CoreCLR on **Raspberry Pi 1** series - This SOC features a single ARM1176JZF-S cpu core. This means that the device features the [ARM11](https://en.wikipedia.org/wiki/ARM11) Micro-architecture.
- [x] Instructions to build/run CoreCLR on **Raspberry Pi 2** series  - This SOC features a quad-core [Cortex-A7](https://en.wikipedia.org/wiki/ARM_Cortex-A7) cpu. This means that these devices feature the ARMv7-A  Micro-architecture.
- [x] Instructions to build/run CoreCLR on **Raspberry Pi 3** series  - This SOC features a quad-core [Cortex-A53](https://en.wikipedia.org/wiki/ARM_Cortex-A53) cpu. This means that all of these boards feature the ARMv8-A Micro-architecture.
- [x] Create Instructions for above targets using Windows 10 PC.

**Comment by franksinankaya** [comment]
Support for the VFPvX-D16 Floating point variant is now available on coreclr in case you missed it.

See https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/cross-building.md#cross-compiling-coreclr-for-other-vfp-configurations

Cross compiling CoreCLR for Other VFP configurations

**Comment by jkotas** [comment]
ARM v6 support is tracked by https://github.com/dotnet/runtime/issues/7764.

Raspberry 2 and 3 work fine.

If there is anything remaining worth spending time on that is not addressed by https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/cross-building.md#cross-compiling-coreclr-for-other-vfp-configurations, please open a new specific issue on it.
