### ISSUE TITLE
c# Native host dll import issue

### ISSUE THREAD

**Issue by ssaarian** [dotnet/runtime#56245]
I designed my c# native host c++ project with self-contained coreclr reference in mind; the main method receives the path of the coreclr folder (no hard coded coreclr.dll reference), and it is working ok being tested inside the visual studio; being tested-- having referenced to multiple folders, etc.

My understanding was that the c# native host dll is a true windows native assembly and that can be loaded (dll import) to any windows native apps with no issues. However,...

My actual/target hosting client is the Inno Setup (32 bit), and it failing to load my native assembly (native 32bit). 
As long as inno founds my declared api call, it attempts to load my dll to its process memory. I expected that my dll should be  loaded with no issues until the point where I will make my 1st call to contact to my managed assembly. By that point  I MUST HAVE READY THE c# .NET runtime (obviously). I assumed that inno would have a blank blueprint of my native assembly functions when loaded, thinking that the native assembly has no dependencies. However, it fails loading it, as I said, and It will work if I would have installed the vc++ redistributable prior to inno run. There is another option to work around this- is to call the api with ‘delay’ keyword (inno specific), load the vc++ redistributable, then use it (this scenario works like “late-binding”).

Anyway, this, vc++ redistributable requirement tells me that my c# native host project has a dependency to vc++ redistributable and is not really a “native” 😉.

Well, I looked to my c++ project external dependencies and found tons of correct_*.h found at C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\ directory. On the other hand, the vc++ redistributable installation does not create any specific folder with similar content.

My question is: 
Is this true-- that the c++ native wrapper will have dependency to vc++ redistributable, or I’m doing something incorrect, and my compiled c++ native host assembly should have no dependency to vc++ redistributable at all (if I do correctly)…  

Thanks for any thoughts in advance,
Sam

P.S.
I have another c++ created dll import to inno setup (same project), and that requires no such vc++ prerequisites at all (as it supposed to be).

**Comment by jkotas** [comment]
> vc++ redistributable requirement

You either need to copy the required vc++ redistributables next to your native .dll. Or you need to link the C runtime library statically to your native .dll - go to project properties `C/C++` / `Code Generation` /  `Runtime Library` and make sure to check `MultiThreaded (/MT)`. https://docs.microsoft.com/cpp/atl/benefits-and-tradeoffs-of-the-method-used-to-link-to-the-crt?view=msvc-160 has more details about the tradeoffs involved in statics vs. dynamic linking of C runtime library on Windows.

**Comment by ssaarian** [comment]
Thank you Jan for confirming the fact of .net native hosting c++ project dependency to vc++ redistributable, and giving tips on working around it.
As I mentioned, I use this project to handle some .net tasks within inno installer, and currently I install the vc++ redistributable if I don't found it on target system. I'll check other suggested options as I move forward with my tests.

Thanks again,
Sam
