### ISSUE TITLE
[wasm][debugger] Cannot see members of a `Task` in a `ContinueWith` lambda, with preview7

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56249]
blazorwasm template app:

![Screen Shot 2021-07-23 at 4 32 19 PM](https://user-images.githubusercontent.com/1472/126838454-b2223c2f-4ce7-4246-ae31-1eac294e83ec.png)

- cannot see members of `t` with hover
- cannot see members of `t` in `locals` window either

cc @thaystg

**Comment by lewing** [comment]
@radical is this a regression?

**Comment by thaystg** [comment]
Yes, this is a regression.
