### ISSUE TITLE
Loading assembly problem

### ISSUE THREAD

**Issue by mohsensaleh2010** [dotnet/runtime#56253]
I have multiple project as bellow:

1- Infrastructure: this is classLibrary project and contains infrastructural classes, interfaces and etc.

2- Runable Project: this is asp.net core 5 project and used for launch other business project and has reference from `Infrastructure` project

3- Business solution : this has multiple class library project for `api, service, domain, ...` layers 

in `Infrastructure` project there is an interface as bellow:

    using Microsoft.Extensions.DependencyInjection;

    namespace Infrastructure
    {
    public interface IModuleLoader
    {
         void Register(IServiceCollection serviceCollection);
    }
    }

in the `Business.Api` project there is class that implement `IModuleLoader` interface 

    namespace Business.Api
    {
    public class BusinessModuleLoader : IModuleLoader
    {
        public void Register(IServiceCollection services)
        {
            services.AddControllers().AddApplicationPart(this.GetType().Assembly);
    //...
        }
    }
    }

in the `Runable` Project have this class for loading business Assembly project 

    public static class ModuleLoaderHelper
    {
        public static void LoadModules(this IServiceCollection services)
        {
            AutoLoading(services);
        }

        private static void AutoLoading(IServiceCollection services)
        {
            var path = AppDomain.CurrentDomain.BaseDirectory;
            DirectoryInfo di = new DirectoryInfo(path);
            FileInfo[] fis = di.GetFiles("Business.Api.dll");

            var mtype = typeof(Infrastructure.IModuleLoader);

            foreach (var f in fis)
            {
                try
                {

                    var loadContext = new PluginLoadContext(f.FullName);
                    var asm = loadContext.LoadFromAssemblyName(new AssemblyName(Path.GetFileNameWithoutExtension(f.FullName)));
                             var moduleLoader = asm.GetTypes().FirstOrDefault(p => mtype.IsAssignableFrom(p));

                    if (moduleLoader == null)
                        continue;

                    Infrastructure.IModuleLoader loader = (Infrastructure.IModuleLoader)Activator.CreateInstance(moduleLoader);

                    loader.Register(services);

                }
                catch (Exception exp)
                {
                    Console.WriteLine(exp.Message + exp.StackTrace);
                }
            }
        }

        class PluginLoadContext : AssemblyLoadContext
        {
            private AssemblyDependencyResolver _resolver;

            public PluginLoadContext(string pluginPath)
            {
                _resolver = new AssemblyDependencyResolver(pluginPath);
            }

            protected override Assembly Load(AssemblyName assemblyName)
            {
                string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
                if (assemblyPath != null)
                {
                    return LoadFromAssemblyPath(assemblyPath);
                }

                return null;
            }

            protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
            {
                string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
                if (libraryPath != null)
                {
                    return LoadUnmanagedDllFromPath(libraryPath);
                }

                return IntPtr.Zero;
            }
        }
    }
    }

the `Business.Api` assembly loaded and `BusinessModuleLoader` type exists in loaded assembly but  
doesn't match in this line of code `var moduleLoader = asm.GetTypes().FirstOrDefault(p => mtype.IsAssignableFrom(p));` and varable `moduleLoader` is `null`

How can I solve this problem?

**Comment by vitek-karas** [comment]
Please take a look at this [guide](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#simple-plugin-with-no-dependencies) (and it's [sample](https://github.com/dotnet/samples/tree/main/core/extensions/AppWithPlugin)). 

Quoting from the guide:
> The <Private>false</Private> element is important. This tells MSBuild to not copy PluginBase.dll to the output directory for HelloPlugin. If the PluginBase.dll assembly is present in the output directory, PluginLoadContext will find the assembly there and load it when it loads the HelloPlugin.dll assembly. At this point, the HelloPlugin.HelloCommand type will implement the ICommand interface from the PluginBase.dll in the output directory of the HelloPlugin project, not the ICommand interface that is loaded into the default load context. Since the runtime sees these two types as different types from different assemblies, the AppWithPlugin.Program.CreateCommands method won't find the commands. As a result, the <Private>false</Private> metadata is required for the reference to the assembly containing the plugin interfaces.

Simply put, make sure that the project reference from your plugin to the infrastructure assembly has the `<Private>false</Private>` metadata on it.

**Comment by agocke** [comment]
Closing as resolved
