### ISSUE TITLE
System.Text.Json: JsonStringEnumConverter ignores its JsonNamingPolicy during deserialization.

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/runtime#56258]
# Excessively Negative  Foreword 
Hello folks, 
I wasn't going to bother filing this issue, but after seeing [this blog post](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/) showing significant investment in space age source-generator tech at the presumed expense of long standing and more (subjectively) fundamental issues such as #782 (which just fell off the .NET 6 release wagon) I am compelled to provide feedback on actual usability problems with STJ. 

I intentionally held off on trying to adopt STJ for over 2 years because I kept reading about limitations, but it seems even now I can't use it for a pretty basic REST API integration without writing multiple custom converters to handle common patterns such as snake case along side string enum representations. Writing a custom naming policy isn't hard, but when it doesn't work with the other built-in components such as JsonStringEnumConverter, it has only created a 2nd problem for me to solve.

The worst part about this is I spent time debugging and reading docs and code trying to understand what I was doing wrong. I just wasn't expecting it to work fine for serialization but not for deserialization. I've run into other unexpected gaps that were less painful, but still disappointing. Admittedly part of this pain was caused because I am writing the code in F# which has it's own friction with the C# biased ecosystem, but **deserisalizing an enum from a string is not an F# specific problem.** [The docs are somewhere between misleading and flat-out incorrect](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-customize-properties#enums-as-strings). Note the last example that directly specifies the naming policy for deserialization when it will not be respected. That is setting the user up for confusion and disappointment. 

# Actual Issue Description

I am resubmitting this issue as a dupe of #31619 and #41138. Those were closed and locked so I cannot comment there.

The previous closure stems from [this comment](https://github.com/dotnet/runtime/pull/42302#pullrequestreview-674544699) partially copied below (emphasize mine).

> ... We are trying to map the result of a naming policy conversion back to enum property values. On the surface, this is no different from what we do when deserializing object properties using JsonSerializerOptions.PropertyNamingPolicy.
**The complication here is with flag combination values. We cannot cache all possible transformed enum property name values, of which there could be several, opening the door to security vulnerabilities (#36726 (comment)).** ...

### My concrete ask here is either:

A) Could we simply exclude [Flags] enums from the deserialization handling for now? My gut tells me the vast majority of enum deserializations in the wild will not use [Flags] and will simply be 1-1 enum mappings.

B) If [Flags] support MUST be included for consistency, could we use limit the cache size and allow a perf penalty for cache misses?

I hope it is not too late in the release cycle to get this into .NET 6.

**Comment by layomia** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/31619. Please see https://github.com/dotnet/runtime/issues/31619#issuecomment-891488195.

**Comment by AlgorithmsAreCool** [comment]
@layomia can #31619 also be unlocked? I would like to leave a comment there.

**Comment by layomia** [comment]
@AlgorithmsAreCool done. cc @terrajobst
