### ISSUE TITLE
UnconditionalSuppressMessage does not fully suppress in compiler-rewritten methods

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/runtime#56252]
Given the following code, using .NET SDK 6.0.100-preview.5.21302.13:

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;

namespace DemoTrimmedApp
{
    class Program
    {
        static void Main()
        {
            foreach (var type in SuperHandyReflectionUtil.GetTypeNames())
            {
                Console.WriteLine(type);
            }
        }
    }

    class EligibleForTrimming { }

    class AlsoEligibleForTrimming { }

    class SuperHandyReflectionUtil
    {
        [UnconditionalSuppressMessage(
            "Trimming",
            "IL2026:Methods annotated with 'RequiresUnreferencedCodeAttribute' require dynamic access otherwise can break functionality when trimming application code",
            Justification = "look, I just want to see what happens here.")]
        public static IEnumerable<string> GetTypeNames()
        {
            foreach (var type in Assembly.GetCallingAssembly().GetTypes())
            {
                yield return type.Name;
            }
        }
    }
}
```

and given the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

</Project>
```

then, when publishing with the command line, like so:

```shell
dotnet publish -c Release --self-contained -r win-x64
```

I expect to have no trimming-related warnings.

Instead, I get the following warning applied to the compiler-generated iterator method:

> Program.cs(31,34): Trim analysis warning IL2026: DemoTrimmedApp.SuperHandyReflectionUtil.<GetTypeNames>d__0.MoveNext(): Using method 'System.Reflection.Assembly.GetTypes()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.

**Comment by vitek-karas** [comment]
Thanks for reporting this. It's a problem we recently found out ourselves: https://github.com/mono/linker/issues/2163

You can "workaround" it by setting `<TrimmerDefaultAction>link</TrimmerDefaultAction>` in your project file. This will make it so that the main application assembly is also fully trimmed (the default is to not trim it) - which will have a side effect that the trimmer will correctly see the suppression (the reason why is rather complicated).
