### ISSUE TITLE
build.sh -s host does not work on unbuntu x64

### ISSUE THREAD

**Issue by AustinWise** [dotnet/runtime#56275]
### Description

I performed the following steps on Ubuntu:

```
git clone https://github.com/dotnet/runtime.git
cd runtime
./build.sh -s host
```

I got the following error:

```
 Copying /home/austin/runtime/artifacts/bin/coreclr/Linux.x64.Debug//corehost/. to /home/austin/runtime/artifacts/bin/linux-x64.Debug/corehost
  cp: cannot stat '/home/austin/runtime/artifacts/bin/coreclr/Linux.x64.Debug//corehost/.': No such file or directory
/home/austin/runtime/src/installer/corehost.proj(41,5): error MSB3073: The command "/home/austin/runtime/src/native/corehost/build.sh Debug x64 -apphostver "6.0.0-dev" -hostver "6.0.0-dev" -fxrver "6.0.0-dev" -policyver "6.0.0-dev" -commithash "N/A" -os Linux -cmakeargs "-DVERSION_FILE_PATH=/home/austin/runtime/artifacts/obj/_version.c" -coreclrartifacts /home/austin/runtime/artifacts/bin/coreclr/Linux.x64.Debug/ -runtimeflavor CoreCLR" exited with code 1.
```

The output of `./build.sh -s help` suggests that 'host' (i.e. corehost and related components) is a supported subset to build via the `-s` argument.

Looking inside the output `artifacts/bin` folder, I see no `coreclr` folder. Furthermore, while I do see a `linux-x64.Debug` folder, this differs in casing and punctuation from the `Linux.x64.Debug` path element in the error message.

Is this `build.sh -s host` command supposed to work on Linux?

### Configuration

OS: Ubuntu 20.04
Architecture: x64
Revision checked out: 7d30da68a91d1cced11a0302cc7a8aa9a0ea9af1
Environment setup: Followed [these instructions](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/linux-requirements.md#toolchain-setup) to setup compilers on Ubuntu

### Further notes

The offending `coreclrartifacts` argument appears to come from [this line](https://github.com/dotnet/runtime/blob/d019e70d2b7c2f7cd1137fac084dbcdc3d2e05f5/eng/liveBuilds.targets#L17) in `eng/liveBuilds.targets`. I can send in the results of `./build.sh -s host --bl` if that would help.

**Comment by am11** [comment]
> Is this `build.sh -s host` command supposed to work on Linux?

Yes, however, some subsets (like `libs`, `host`..) depend on presence of one of the runtime flavor; coreclr or mono. This is to support CI scenarios where one leg builds CoreCLR and upload artifacts and other leg downloads those artifact and build a different subset.

```sh
# first build clr or build host

# subset is also the first positional parameter so it works without -s
./build.sh clr
./build.sh host
```

or its short form: `./build.sh clr+host`. you may also be interested in packs (which builds consumable tarball, dotnet-dev-6.0...tar.gz), i.e.: `./build.sh clr+host+packs`.

**Comment by AustinWise** [comment]
That did the trick, thanks!

I guess there is a tradeoff between each subset build its dependencies and only building exactly what is asked for. I can see the value of faster iteration speed when you are working on just one component. But it was a bit confusing.
