### ISSUE TITLE
System.Text.Json source generation with base class and different assembly

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#56276]
### Description

System.Text.Json fails to generate source for types that have a base class with a generic type, but only when it is in a different assembly.

Here is a minimal repro:

- create a net6 class library. Add the following types to it:

```csharp 
public class CitiesData
{
}

public class Patch2<T>  { }

public class CitiesDataWrapped2 : Patch2<AspNetCoreWebApi2.Entities.CitiesData>
{
}
```

- create a NET6 app that has a reference to the library created above, as well as to:
`<PackageReference Include="System.Text.Json" Version="6.0.0-preview.6.21352.12" />`

Add the following type to enable source generation:
```csharp
[JsonSerializable(typeof(CitiesDataWrapped2), GenerationMode = JsonSourceGenerationMode.MetadataAndSerialization)]
public partial class SampleJsonContext : JsonSerializerContext
{
}
```

### Expected vs Error
Expected that source generation succeeds, but it fail with the following output:

```
2>CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'TypedConstant is an array. Use Values property.'
2>C:\Users\...\Program.cs(72,26,72,43): error CS0534: 'SampleJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
```

### Further Findings
If there is no separate library project and all types are in the same project, then source generation succeeds.
If I remove the generic type parameter from `Patch2<T>` (but keeping the types in a separate library) source generation succeeds.

### Configuration

VS 2022, 17.0.0 Preview 2.1
NET 6 latest preview
System.Text.Json Version="6.0.0-preview.6.21352.12
Windows x64

### Regression?

This is a pre-release feature of `System.Text.Json`.

### Workaround?

No workaround, as the types in the separate library in reality also comes from a separate (3rd party) source.

**Comment by layomia** [comment]
@ladeak, thanks for the feedback! Does this issue repro when using the [latest build](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&view=versions&package=System.Text.Json&version=6.0.0-rc.1.21402.2&protocolType=NuGet) of System.Text.Json/the source generator?

**Comment by ladeak** [comment]
Version 6.0.0-rc.1.21402.3 looks good, thank you for the follow up :)
