### ISSUE TITLE
[API Proposal]: Mark HttpClient.Dispose as obsoleted

### ISSUE THREAD

**Issue by wsq003** [dotnet/runtime#56284]
### Background and motivation

HttpClient.Dispose voilate an important implicit C# regulation that every IDisposable instance should be disposed instantly, locally and safely.

In all situation except HttpClient you are encouraged to write code like `using (var conn = new SqlConnection())`, but when you encounter HttpClient, such code will lead your application to a sudden DEATH, because of network port exhaust.

```C#
using var client = new HttpClient();
var res = await client.GetStringAsync(url);
```     
Such code is dangerous and in fact forbiddened. 

Becasuse such usage is in fact forbiddened, I suggest we remove HttpClient.Dispose to prevent such common mistake.
A considerable step is to mark this function obsoleted at first. Then we will be able to remove HttpClient.Dispose finally someday.

### API Proposal

1. HttpClient.Dispose should work as expected, or it should be removed.
2. Becuase of network inherent delay and disorder, you can not release a network port instantly. So it is impossible to make HttpClient.Dispose work as expected (instantly, locally, safely).
3. Since it is impossible to make HttpClient.Dispose work as expected, we  should remove it.

HttpClient should provide a separate function such as Close() or Release() or Stop() to release it's resource.

### API Usage

```C#
using var client = new HttpClient();
var res = await client.GetStringAsync(url);
```  

Such code should compile with an obsoleted warning.

### Risks

1. Existing application may fail to compile if programmer choose to treat warning as error.

### Additional

After discussion, here comes a new point:
1. Public constructor of HttpClient should also be marked as obsoleted. So user will be warned to use some kind of factory, instead of creating too many instances.

**Comment by huoyaoyuan** [comment]
Resource exhausting may happen for any resource. 

> such code will lead your application to a sudden DEATH, because of network port exhaust

It's exhaust because of **creating** so much http clients, not **disposing**.

> Becuase of network inherent delay and disorder, you can not release a network port instantly

`IAsyncDisposable` could be considered, but `IDisposable` should be left there.

**Comment by wsq003** [comment]
> Resource exhausting may happen for any resource.
> 
> > such code will lead your application to a sudden DEATH, because of network port exhaust
> 
> It's exhaust because of **creating** so much http clients, not **disposing**.
> 
> > Becuase of network inherent delay and disorder, you can not release a network port instantly
> 
> `IAsyncDisposable` could be considered, but `IDisposable` should be left there.



✅ **GOOD** This is encourage in most conditions.
```C#
using (var conn = new SqlConnection())
```
❌ **BAD** This will lead to a sudden death.
```C#
using (var client = new HttpClient())
```

How can you distinguish these two?

**Comment by svick** [comment]
@wsq003 How does obsoleting and removing `Dispose` help? It will only encourage people to write:

```c#
var client = new HttpClient();
```

Which is even worse than with `using`.

**Comment by wsq003** [comment]
> @wsq003 How does obsoleting and removing `Dispose` help? It will only encourage people to write:
> 
> ```cs
> var client = new HttpClient();
> ```
> 
> Which is even worse than with `using`.

I consider this better, because it will fail fast.
It would be easier to encounter this bug in test case.

Maybe we should also market default constructor of HttpClient as obsoleted, to force programmer to use some factory.

**Comment by huoyaoyuan** [comment]
> to force programmer to use some factory.

Then people will create a lot of factories and still die.

**Comment by wsq003** [comment]
> > to force programmer to use some factory.
> 
> Then people will create a lot of factories and still die.

```C#
public static class HttpClientDefaultFactory
{
	static HttpClient client = new HttpClient();

	public static HttpClient GetHttpClient()
	{
		return client;
	}
}
```
A factory simple like this would really help a lot.
Key point is programmer should be warned for danger like using (var client = new HttpClient()).

**Comment by huoyaoyuan** [comment]
Generally, if something will hurt *when done a lot*, warning on a single operation won't help.

For example it's well known that doing `+` for string in loop hurts performance, however when you have a known value of strings, `+` becomes the fastest operation.

**Comment by MihaZupan** [comment]
> C# regulation that every IDispose instance should be disposed instantly, locally

What regulation?

Quoting @stephentoub from https://github.com/dotnet/runtime/issues/53371#issuecomment-849851844:

> it's disposable for the same reason other types are disposable: dispose it when you're done with it and want its resources cleaned up. The HttpClient instance stores resources like a connection pool, so it shouldn't be disposed until you want to clean up that connection pool. It should be created, used repeatedly for all relevant requests, and then when you're done with it, dispose it (or just exit the app).

Obsoleting `Dispose` is wrong because it does have value when used correctly.

It is true that not everyone knows how to use HttpClient correctly.
Proposals like #33124 are there to discuss how the experience can be improved.

Telling users not to dispose the client makes the problem worse.

> A factory simple like this would really help a lot.

How is that better than the user writing `private static readonly HttpClient Http = new();`?

> Key point is programmer should be warned for danger like `using (var client = new HttpClient())`.

That would be a job of an analyser to flag problematic use cases, not obsoleting the underlying API.
Before investing time into that, proposals like #33124 should be carefully considered instead.

**Comment by wsq003** [comment]
> Generally, if something will hurt _when done a lot_, warning on a single operation won't help.
> 
> For example it's well known that doing `+` for string in loop hurts performance, however when you have a known value of strings, `+` becomes the fastest operation.

Disagreed.

A performance issue will raise slowly, and you will be warned by monitor system. Most monitor system will monitor CPU/Memory system. Then you will have a chance to make things right before it broken.

HttpClient.Dispose is different, it will lead to a sudden death. CPU/Memory is normal and application suddenly dead.

**Comment by huoyaoyuan** [comment]
For non network-intensive applications, for example ones only check for news on startup, creating a temporary `HttpClient` and dispose it immediately is good because it doesn't hold for network resource for a long time.

**Comment by huoyaoyuan** [comment]
> CPU/Memory is normal and application suddenly dead.

It will also hang if you do a lot of synchronize disk IO on a same mechanical disk. Single operation isn't harmful though.

**Comment by wsq003** [comment]
> For non network-intensive applications, for example ones only check for news on startup, creating a temporary `HttpClient` and dispose it immediately is good because it doesn't hold for network resource for a long time.

Disagreed.

One machine, despite physical or virtual, will not run a lot of application/process. So a static HttpClient is worth while and will not hurt.
A static HttpClient is what really happen in daily programming. And is suggested by most stackoverflow answers.

**Comment by huoyaoyuan** [comment]
> So a static HttpClient is worth while and will not hurt.

It hurts the working set of the process.

**Comment by wsq003** [comment]
> > CPU/Memory is normal and application suddenly dead.
> 
> It will also hang if you do a lot of synchronize disk IO on a same mechanical disk. Single operation isn't harmful though.

This is true. An eligible monitor system should also monitor disk IO. In a reasonable system, disk IO will hardly suddenly hang, because disk IO usually have a high threshold.

HttpClient.Dispose is different from disk IO because it has a low threshold that can easily touch.

**Comment by wsq003** [comment]
> > So a static HttpClient is worth while and will not hurt.
> 
> It hurts the working set of the process.

Be realistic.
A static HttpClient is what really happen in daily programming. And is suggested by most stackoverflow answers.

**Comment by huoyaoyuan** [comment]
> A static HttpClient is what really happen in daily programming. And is suggested by most stackoverflow answers.

Adding a static one is a reasonable request. **Forcing** people to use it is not.

**Comment by wsq003** [comment]
> 
> How is that better than the user writing `private static readonly HttpClient Http = new();`?
> 

This is theoretically correct, but this will make current application fail to compile. 
Make it obsoleted will give programmer a warning, and will not break current application.

**Comment by wsq003** [comment]
> > A static HttpClient is what really happen in daily programming. And is suggested by most stackoverflow answers.
> 
> Adding a static one is a reasonable request. **Forcing** people to use it is not.

Programmer should be warned. If a common looking code would lead to death.

**Comment by huoyaoyuan** [comment]
> Make it obsoleted will give programmer a warning, and will not break current application.

Warning is a *breaking change*. Codebases with high quality requirement will treat obsolete members as removed and not use them even with supressions.

**Comment by wsq003** [comment]
> > Make it obsoleted will give programmer a warning, and will not break current application.
> 
> Warning is a _breaking change_. Codebases with high quality requirement will treat obsolete members as removed and not use them even with supressions.

Yes, this is a risk listed.
Worth it or not?
I believe yes.

**Comment by acaly** [comment]
As a programmer, I think the current documentation is very clear about this. The first time I read about HttpClient I knew I should only create one. Whatever you do, you can't prevent people from misusing if they never read documentation.

**Comment by huoyaoyuan** [comment]
The bar of obsoleting members for .NET is **very high**. The recent obsoletions are mainly about severe security risk or members that no longer function at all. Performance risks are more likely to be handled by analyzers, which can be turned on or off.

**Comment by wsq003** [comment]
> That would be a job of an analyser to flag problematic use cases. 

This sound reasonable. Maybe visual studio should give a message in compile time? 
A high quality application usually will eliminate all error/warning/message in compile time.
Maybe a compile message is already strong enough?

**Comment by wsq003** [comment]
> > to force programmer to use some factory.
> 
> Then people will create a lot of factories and still die.

```C#
System.Net.Http.HttpClientFactory
```
Looks like an official factory already exist. The question here is how to inform programmers to use such factory.

**Comment by wsq003** [comment]
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

Some guys already did a lot of wonderful background work there. The question is normal programmer did not know all these. They need to be warned.

**Comment by wsq003** [comment]
> As a programmer, I think the current documentation is very clear about this. The first time I read about HttpClient I knew I should only create one. Whatever you do, you can't prevent people from misusing if they never read documentation.

Question here is no one will read every document, especially when this is a common looking case, and it works after compile.
How programmer work? Write code based on experience, if it compiles and works, then finished. Right?

**Comment by wsq003** [comment]
A senior MSFT member suggested to use HttpClient in singleton in https://github.com/dotnet/aspnetcore/issues/21559

HttpClient.Dispose is useless and misleading.

**Comment by filipnavara** [comment]
> HttpClient.Dispose is useless and misleading.

It totally is not. Moreover, lot of the StackOverflow answers are lacking some details on when it's actually reasonable to cache the instance and when it is not. It is really harmful because way too many developers instantly run into complicated schemes to keep one instance or use special factories (which avoid problem with DNS that is not really relevant anymore since SocketsHttpHandler can deal with it).

The whole premise of the proposal is wrong, the issue is not disposing (or lack of it) but the creation of too many instances that will get you into trouble. Removing the dispose would only lead to people doing `new HttpClient()` all over the place and relying on GC to clean it up which is even worse.

For example, in our client application we have a concept of application objects that are created/disposed based on online/offline state (based on network availability or user controlled switch). The lifetime of `HttpClient` perfectly fits into this model and we do want to control it explicitly.

**Comment by acaly** [comment]
> if it compiles and works, then finished. Right?

It depends on how you define "works".

Regarding your comparison between `HttpClient` and `SqlConnection`, I think the names have indicated their difference: you create one connection is for one specific request, but your application as a whole is usually be considered as **_one_** client, which is able to make **_many_** connections with **_the_** server. If the name of `HttpClient` was instead `HttpConnection` then I would agree it is misleading.

Of course even if this is a big problem for programmers, as others have pointed out, removing `Dispose` is not a solution.

**Comment by wsq003** [comment]
> > if it compiles and works, then finished. Right?
> 
> It depends on how you define "works".
> 
> Regarding your comparison between `HttpClient` and `SqlConnection`, I think the names have indicated their difference: one connection is for one specific request, but your application as a whole should usually be considered as **_one_** client, which is able to make **_many_** connections with **_the_** server. If the name of `HttpClient` was instead `HttpConnection` then I would agree it is misleading.
> 
> Of course even if this is a big problem for programmers, as others have pointed out, removing `Dispose` is not a solution.

Sounds interesting. Maybe `HttpClient` should be renamed to `HttpClientPool`? Maybe `HttpClientPool` should hide from user, just like `SqlConnectionPool` is invisible to user.

**Comment by karelz** [comment]
Triage: As discussed above, obsoleting is not an option -- too breaking, little value. Having it properly documented is the best way. There are options we could think about in Future, though they are breaking.
BTW: `HttpClientFactory` is only for DI systems (like ASP.NET).

Closing.
