### ISSUE TITLE
Consider providing SIMD JIT intrinsics for Matrix and Quaternion operations

### ISSUE THREAD

**Issue by vanka78bg** [dotnet/runtime#5630]
Currently System.Numerics.Vectors takes advantage of certain JIT intrinsics provided by RyuJIT to accelerate some Vector operations. For instance, addind two Vector4 variables together would emit a single SIMD instruction for packed addition. In contrast, Matrix and Quaternion operations cannot take advantage of this due to a lack of JIT support. For example, transforming a Vector4 variable by a Matrix4x4 would emit 16 scalar multiplications and 12 scalar additions, instead of only 4 packed multiplications and 3 packed additions.

The most common indended usage of the System.Numerics.Vectors library is in graphically intensive 2D and 3D applications, which often need to apply affine transformations to many vectors. For this reason, providing SIMD acceleration for Matrix and Quaternion operations can be of a great benefit, with a theoretical speedup by a factor of 4 or more. However such improvements are not currently possible without the necessary JIT support. In my opinion, the biggest performance advantage can be achieved by accelerating at least the following opertations:
1. Transforming a Vector by a Matrix
2. Transforming a Vector by a Quaternion
3. Multiplying a Matrix by a Matrix
4. Transposing a Matrix (to implement 3 efficiently)

category:cq
theme:vector-codegen
skill-level:expert
cost:large
impact:medium

**Comment by tannergooding** [comment]
We opted to do this in managed due to the complexity and size of the IR for Matrix4x4. However, for Quaternion and Plane this has already been done.
