### ISSUE TITLE
Revise System.Text.Json APIs for source generator before it becomes stable

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#56300]
## Revise System.Text.Json APIs for source generator before it becomes stable

The new System.Text.Json source generator was introduced in https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator. However, I don't think those APIs are in right shapes. They should take use of new language feature introduced in C# 10 and .NET 6, and furthermore, some upcoming features in near future.

### Abstract statics in interface
.NET 6 and C# 10 introduced "abstract statics in interface" which allows virtual static to be declared in interfaces and to be implemented in classes/structs. System.Text.Json APIs for source generator should take use of them.

I.e. instead of introducing `JsonTypeInfo` and APIs consumes `JsonTypeInfo` in  System.Text.Json, a new interface `IJsonSerializable` containing static abstract method `SerializeJson` and `DeserializeJson` should be introduced.

```csharp
interface IJsonSerializable<T> where T : IJsonSerializable<T>
{
    abstract string SerializeJson(T obj, JsonSerializerOptions options);
    abstract T DeserializeJson(string str, JsonSerializerOptions options);
}
```

And then users can mark their types with `partial` and apply `JsonSerializable` attribute to types they want to generate code for serialization, then the source generator should implement `IJsonSerializable<T>` for them in a partial class/struct. This approach 
 not only requires no API changes but also avoid the versioning issue, and the serializer/deserializer can know whether a type implemented `IJsonSerializable` from `T` directly without need of any instance. Furthermore, this also allows users to implement their own serialization methods.

### Generic attributes
C# 10 is introducing generic attributes, so instead of an attribute receiving a `Type` as parameter, the attribute itself should be made generic:

```csharp
public JsonSerializableAttribute<T> : Attribute where T : IJsonSerializable<T> { }
```

So users can use `[JsonSerializable<T>]` to mark types they want to do serialization. This approach not only gets rid of `typeof(T)` usage, but also applys constraints to `T` to satisfy `IJsonSerializable<T>`. 

### Extension interfaces
C# will soon introduce extension interfaces in near future, so source generator can make use of this feature to extend the interface `IJsonSerializable` for existing types and users will no longer need to mark their types as partial. 

This will also enable scenario for generating (de)serialization code for not owned types. 

### Solution
The existing bunch of APIs introduced in `System.Text.Json` for source generators are totally unnecessary at all, **please don't ship those APIs to stable** because they will soon be out-of-date. They should be removed.

```diff
namespace System.Text.Json
{
    public static class JsonSerializer
    {
-         public static object? Deserialize(ReadOnlySpan<byte> utf8Json, Type returnType, JsonSerializerContext context) => ...;
-         public static object? Deserialize(ReadOnlySpan<char> json, Type returnType, JsonSerializerContext context) => ...;
-         public static object? Deserialize(string json, Type returnType, JsonSerializerContext context) => ...;
-         public static object? Deserialize(ref Utf8JsonReader reader, Type returnType, JsonSerializerContext context) => ...;
-         public static ValueTask<object?> DeserializeAsync(Stream utf8Json, Type returnType, JsonSerializerContext context, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static ValueTask<TValue?> DeserializeAsync<TValue>(Stream utf8Json, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static TValue? Deserialize<TValue>(ReadOnlySpan<byte> utf8Json, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
-         public static TValue? Deserialize<TValue>(string json, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
-         public static TValue? Deserialize<TValue>(ReadOnlySpan<char> json, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
-         public static TValue? Deserialize<TValue>(ref Utf8JsonReader reader, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
-         public static string Serialize(object? value, Type inputType, JsonSerializerContext context) => ...;
-         public static void Serialize(Utf8JsonWriter writer, object? value, Type inputType, JsonSerializerContext context) { }
-         public static Task SerializeAsync(Stream utf8Json, object? value, Type inputType, JsonSerializerContext context, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task SerializeAsync<TValue>(Stream utf8Json, TValue value, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static byte[] SerializeToUtf8Bytes(object? value, Type inputType, JsonSerializerContext context) => ...;
-         public static byte[] SerializeToUtf8Bytes<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
-         public static void Serialize<TValue>(Utf8JsonWriter writer, TValue value, JsonTypeInfo<TValue> jsonTypeInfo) { }
-         public static string Serialize<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo) => ...;
    }
}

namespace System.Net.Http.Json
{
    public static partial class HttpClientJsonExtensions
    {
-         public static Task<object?> GetFromJsonAsync(this HttpClient client, string? requestUri, Type type, JsonSerializerContext context, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<object?> GetFromJsonAsync(this HttpClient client, System.Uri? requestUri, Type type, JsonSerializerContext context, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<TValue?> GetFromJsonAsync<TValue>(this HttpClient client, string? requestUri, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<TValue?> GetFromJsonAsync<TValue>(this HttpClient client, System.Uri? requestUri, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<HttpResponseMessage> PostAsJsonAsync<TValue>(this HttpClient client, string? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<HttpResponseMessage> PostAsJsonAsync<TValue>(this HttpClient client, System.Uri? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<HttpResponseMessage> PutAsJsonAsync<TValue>(this HttpClient client, string? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<HttpResponseMessage> PutAsJsonAsync<TValue>(this HttpClient client, System.Uri? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
    }
    public static partial class HttpContentJsonExtensions
    {
-         public static Task<object?> ReadFromJsonAsync(this HttpContent content, Type type, JsonSerializerContext context, CancellationToken cancellationToken = default(CancellationToken)) => ...;
-         public static Task<T?> ReadFromJsonAsync<T>(this HttpContent content, JsonTypeInfo<TValue> jsonTypeInfo, CancellationToken cancellationToken = default(CancellationToken)) => ...;
    }
    public sealed partial class JsonContent : HttpContent
    {
-         public static JsonContent<object?> Create(object? inputValue, Type inputType, JsonSerializerContext context, MediaTypeHeaderValue? mediaType = null) => ...;
-         public static JsonContent<TValue> Create<TValue>(TValue? inputValue, JsonTypeInfo<TValue> jsonTypeInfo, MediaTypeHeaderValue? mediaType = null) => ...;
    }
    public sealed partial class JsonContent<TValue> : JsonContent
    {
-         public TValue? Value { get }
    }
}
```

And reimplement the source generator with help of abstract statics in interface, then add APIs with constraints `IJsonSerialiable<T>` to use generated code for serialization, or modify existing APIs to use generated code for those who implemented `IJsonSerializable<T>`.

```csharp
namespace System.Text.Json
{
    public static class JsonSerializer
    {
        public string Serialize<T>(T obj, JsonSerializerOptions options) where T : IJsonSerializable<T>
        {
            return T.Serialize(obj, options);
        }
        public T Deserialize<T>(string str, JsonSerializerOptions options) where T : IJsonSerializable<T>
        {
            return T.Deserialize(str, options);
        }
        // also for Span<> and async APIs ......
    }
}
```

Since abstract statics in interface will be provided as a preview feature in .NET 6, the System.Text.Json source generator should also be provided as a preview feature.

And after extension interfaces being shipped, reimplement the source generator to use extension interfaces instead of requiring users to mark their types as `partial`.

**Comment by eiriktsarpalis** [comment]
Using static abstract interface methods to specify (de)serializable types is an excellent concept, one that has been successfully tried in other languages that support typeclass-like constructs. That being said, SIMs are still a very much experimental runtime feature that will ship with .NET 6, whereas System.Text.Json is a library that targets multiple TFMs, including `net461`. Structuring our sourcegen APIs around that feature would be premature at this point, to say the least.

It's certainly something we might consider for some future release though. cc @stephentoub @tannergooding

**Comment by huoyaoyuan** [comment]
> It's certainly something we might consider for some future release though.

Every release API we shipped will become a dept. If we decide to ship a new version with SIM, we should ensure it doesn't conflict with current API. Duplicated APIs may also confuse people.

I think we should **design the api shape** for SIM-enabled generation as soon as possible.

**Comment by hez2010** [comment]
> whereas System.Text.Json is a library that targets multiple TFMs, including `net461`. Structuring our sourcegen APIs around that feature would be premature at this point, to say the least.

Then I think the current APIs designed for source generator should be provided as a separate nuget package, not built-in feature. This will minimize the impact of deprecating current design in the future.

**Comment by layomia** [comment]
Facilitating assembly trimming is a first-class goal of the JSON source-gen feature. We considered utilizing static interface methods as a vehicle for registering generated code, but did not move forward with the idea. Designing source-generated serialization implementations around interfaces is an anti-pattern for trimming because the ILLinker cannot statically determine which concrete implementations will not be needed at runtime (and can be removed). Please see https://github.com/dotnet/runtime/issues/51945#issuecomment-841252144. cc @eerhardt @jkotas 

In addition, the proposed SIM implementation will not work for non-owned types, including framework types. I do not envision us making several serializable built-in types like collections implement this new interface, but they are important in many user apps.

We will always need separate `JsonSerializer` overloads for source-generation because we want backwards compatibility for existing dynamic `JsonSerializer` usage. We need a set of APIs that take generated code directly so that the serializer implementation can be factored to not reference reflection logic (& related logic to support all serializer functionality) so that they can be trimmed by the linker. This way, the pre-existing serializer overloads based on `JsonSerializationOptions` can be left-as is to continue their dynamic functionality. This bifurcation is required, regardless of what mechanism we package the generated code in (SIM, `JsonTypeInfo<T>`, etc.)

**Comment by terrajobst** [comment]
@hez2010 @huoyaoyuan

> Every release API we shipped will become a dept. If we decide to ship a new version with SIM, we should ensure it doesn't conflict with current API. Duplicated APIs may also confuse people.

I hear you. But there is a trade-off: waiting for a mythical runtime/language feature means we can't add value now, which usually also means we don't learn anything about how useful this feature might be.

Shipping the generator support as preview, would have been an option, but the feature to mark part of our APIs as preview is brand new in this release and we focused on getting it right for the generic math feature. At this point it would be extremely disruptive to mark the generator APIs as preview.

If the preview feature proofs to be a good model, we'll likely use it more moving forward.
