### ISSUE TITLE
Mono.Android-Tests crash when AOT is enabled

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#56315]
### Description

We're hitting a test causes the test app to crash when using `-p:RunAOTCompilation=true`, but it works fine with JIT:

```
********** Crash dump: **********
Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64:9/PSR1.180720.075/5124027:user/release-keys'
#00 0x00059eac /data/app/Mono.Android.NET_Tests-vtnerz4bHqSkZSQWYCTLvw==/lib/x86/libmonosgen-2.0.so
ves_icall_System_IO_Stream_HasOverriddenBeginEndWrite
/__w/1/s\src/mono/mono/metadata/icall.c:3261:38
ves_icall_System_IO_Stream_HasOverriddenBeginEndWrite_raw
/__w/1/s\src/mono/mono/metadata/icall-def-netcore.h:128:0
#01 0x0000d84f <anonymous:e25e6000>
Crash dump is completed
```

It seems to happen during this test:

```
07-26 10:50:51.003  8393  8410 I NUnit   : Redirect_POST_With_Content_Works 
```

https://github.com/xamarin/xamarin-android/blob/e4debf72015549e6e19cbfb247a47fead6ce7a01/tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs#L387-L408

### Configuration

```
dotnet --version
6.0.100-rc.1.21372.10
```

Runtime version:
```
~\.nuget\packages\microsoft.netcore.app.runtime.mono.android-x86\6.0.0-rc.1.21372.1\runtimes\android-x86\native\libmonosgen-2.0.so
```

### Regression?

No, Android AOT is new.

### Other information

Full logcat output: [aot.txt](https://github.com/dotnet/runtime/files/6879766/aot.txt)

/cc @steveisok

**Comment by jonathanpeppers** [comment]
`-p:UseNativeHttpHandler=false` makes the crash go away. But then we get other test failures because `AndroidMessageHandler` isn't used.

**Comment by lambdageek** [comment]
@jonathanpeppers does the IL trimmer run when you AOT this test?

I see that in the `HasOverridenBeginEndRead` implementation we explicitly check whether the linker removed the Stream BeginRead / EndRead methods, but in `HasOverridenBeginEndWrite` we don't

https://github.com/dotnet/runtime/blob/6d3518520ae041fb4c6c1c54d5abf0975a38a450/src/mono/mono/metadata/icall.c#L3231-L3265

So `curr_klass_vtable [io_stream_begin_write_slot]->klass` might be a bad access.

**Comment by jonathanpeppers** [comment]
@lambdageek yes, the tests that fail like this were built for Release, and so they are trimmed.

**Comment by lambdageek** [comment]
Ok, I'm going to try to PR the same check for trimmed methods in `BeginWrite/EndWrite` - I'm assuming that will fix it.
