### ISSUE TITLE
Additional Diagnostics in Dependency Injection

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#56313]
The goal is to help customers better understand how their applications are running by adding events and counters that can give more insights and will help them debug potential performance issues. It'll also help us debug customer applications and write tools that would be able to glean insights from traces.

We would like to help customers better understand some statistics about registered services:
* How many singleton services?
* How many scoped services?
* How many transient services?
* How many container instances are in the processes?

**Comment by eerhardt** [comment]
@davidfowl - were you thinking that all 4 of the above would be "counters" (for example how many times services were resolved). Do you think a single event during `BuildServiceProvider` that logs how many singleton, scoped, and transient service types?

**Comment by davidfowl** [comment]
Initially I was thinking counters but now I'm thinking event because they don't change throughout the lifetime of the app.

**Comment by eerhardt** [comment]
> but now I'm thinking event because they don't change throughout the lifetime of the app.

So you are thinking the count of types, and not the count of instances. Right?

> add service provider instance id to the event and existing events

I assume adding info to an existing event isn't considered a "breaking change"

**Comment by davidfowl** [comment]
> So you are thinking the count of types, and not the count of instances. Right?

Correct, instances can be found using an allocation profiler.

> I assume adding info to an existing event isn't considered a "breaking change"

That's right.

**Comment by davidfowl** [comment]
I'm also thinking we should dump the list of registrations
