### ISSUE TITLE
[wasm][debugger] Blazor/Program.cs, top level main, local var `builder` is not shown in locals

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56326]
Using blazorwasm template project, with VS 17 preview 2.1, and sdk `6.0.100-preview.7.21373.8`:

1. Breakpoint in the top level main in `Program.cs`:
 
![Screen Shot 2021-07-26 at 4 53 15 PM](https://user-images.githubusercontent.com/1472/127057672-b1f0ea05-602f-4b73-8a14-11d50b59ccf1.png)

2. The local variable `builder` doesn't show up in `locals`, hover, or the immediate window.

![Screen Shot 2021-07-26 at 4 52 58 PM](https://user-images.githubusercontent.com/1472/127057675-a2705b97-5e7d-4764-ac41-df592fa986f2.png)

Watch window:
![Screen Shot 2021-07-26 at 4 38 34 PM](https://user-images.githubusercontent.com/1472/127059104-432f442c-f5bd-41ba-adc1-a1c826854dd9.png)

Note that a local string variable in the same scope, does show up.

cc @thaystg

**Comment by thaystg** [comment]
I got the same behavior on .net 5. I didn't investigate yet, but it's not a regression.

**Comment by thaystg** [comment]
![image](https://user-images.githubusercontent.com/4503299/130086784-b96c9680-1bbf-462e-9e8b-0624b0fda98a.png)
It's fixed.
