### ISSUE TITLE
[HTTP/3] Add ClientCertificates API

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#56362]
What support is there for `ClientCertificates` in HTTP/3? Can you do mTLS in HTTP/3?

If mTLS it is supported by HTTP/3, what is the status of `ClientCertificates` support in `SocketsHttpHandler` for .NET 6?

**Comment by JamesNK** [comment]
Related question: How can the server get access to the client certificate? The `QuicConnection` accepted on the server seems like the logical place for the server to get access the client certificate.

**Comment by wfurt** [comment]
Client certificates only work on Windows using certificate collection. (Linux support tracked by https://github.com/microsoft/msquic/issues/1803 and callback by https://github.com/microsoft/msquic/issues/1249)

It seems like logical place would be `PeerCertificate` on QuicConnection ... but we don't have that. Any thoughts on this @geoffkizer ?

For now, you would need to register custom validation callback @JamesNK to get hands on the actual certificate.

**Comment by JamesNK** [comment]
> For now, you would need to register custom validation callback @JamesNK to get hands on the actual certificate.

Can you point me at your tests for using client certs with HTTP/3? It will be easier for me to figure out how to make the client cert available to server apps if I can follow an example.

**Comment by wfurt** [comment]
https://github.com/dotnet/runtime/blob/5938d685c4599bf46809106b4d4df294ee894749/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs#L313

One more caveat I forget about is the https://github.com/microsoft/msquic/pull/1728.
It seems like client certificates tests are passing for MsQuic so I'm not sure if the failure I saw and tried to fix is related to my machine/certificate or not.

**Comment by JamesNK** [comment]
Does using `RemoteCertificateValidationCallback` to get the certificate mean we would lose the built-in certificate validation functionality?

**Comment by JamesNK** [comment]
Stuff:
1. I see `RemoteCertificateValidationCallback` has a SslPolicyErrors argument. Can the method return false if the value is not `SslPolicyErrors.None` to keep the default validation behavior?
2. `RemoteCertificateValidationCallback` on the server doesn't seem to get executed for me. As far as I can tell I have the same configuration options as your test. `RemoteCertificateValidationCallback` for the client is being called. I know the client certificate is reaching the server because RequireClientCertificate is true and the test errors if I remove the client certificate. Why isn't `RemoteCertificateValidationCallback` being called on the server?
3. On the server there are multiple requests created by a `QuicListener`. That means the callback is invoked multiple times and there needs to be a way to associate the certificate from `RemoteCertificateValidationCallback` with a particular `QuicConnection`. On the server we have an accept loop, i.e. call `QuicListener.AcceptConnectionAsync` then do some stuff with the QuicConnection then call accept again. Will `RemoteCertificateValidationCallback` only be called when `AcceptConnectionAsync` is called?

```cs
X509Certificate2 currentClientCertificate = null;
var options = ...;
options.RemoteCertificateValidationCallback = (...) =>
{
    currentClientCertificate = certificate;

    return sslPolicyErrors == SslPolicyErrors.None;
};
_listener = new QuicListener(options);

while (true)
{
    currentClientCertificate = null;
    var connection = await _listener.AcceptConnectionAsync();

    return (connection, currentClientCertificate);
}
```

**Comment by wfurt** [comment]
yes, default validation is always called and you cannot not avoid that (if you want to)
It will pass the chain and the result to the callback so:
1) yes, SslPolicyErrors.None means certificate and chain is good. 
2) for this one I'm not sure. I can re-run the test and see if we broke something recently in attempt to validate the name as well (or something else) 
3) the callback _should_ give you the `QuicConnection` as `sender` but it does not at the moment because the provider e.g. MsQuicConnection does not have linkage up.

**Comment by JamesNK** [comment]
Passing `QuicConnection` as sender in the callback doesn't really help. There is no property bag on `QuicConnection` to stash the certificate on so they return from `AcceptConnectionAsync` together.

Simplest solution is adding a `public X509Certifiacate2 PeerCertificate { get; }` property on `QuicConnection`.

**Comment by rzikm** [comment]
As of latest main, there is `RemoteCertificate` property on `QuicConnection`, so it seems to me that there is nothing else to do in this issue. @JamesNK feel free to reopen this if there is something missing.
