### ISSUE TITLE
Problem with arithmetic of double

### ISSUE THREAD

**Issue by Maximys** [dotnet/runtime#56371]
### Description

Currently I trying to fix [Issue #49611](https://github.com/dotnet/runtime/issues/49611) and I made some commits to my [brunch](https://github.com/Maximys/runtime/tree/fix/49611-fixes-of-invalid-biginteger-casting) . Described issue was fixed by my changes, but I had found one more problem, which can be reproduced by tests from [this commit](https://github.com/Maximys/runtime/commit/7de6a7c1f6c5b0ac14a63e423004a97fdfeb356c).
I had started to investigate this problem and found, that next simple code provide invalid result:

```
internal static class Program
    {
        public static void Main(string[] args)
        {
            double tmp4 = 836653375363579309516074612984d;

            Console.WriteLine(tmp4.ToString("F0"));
            tmp4 += 5.0d;
            Console.WriteLine(tmp4.ToString("F0"));
            tmp4 = tmp4 + 5.0d;
            Console.WriteLine(tmp4.ToString("F0"));

            Console.ReadKey();
        }
    }
```
all Console.WriteLine return me: 836653375363579241826235711488 .
Guys, what's wrong? Why simple increment of double does not work?

### Configuration

* .NET 3.1/.NET 5
* Windows 10 Pro
* x64

### Regression?

Under .NET Framework 4.7.2 I have 836653375363579000000000000000 as result which is wrong too.

**Comment by EgorBo** [comment]
That is how floating point works according to IEEE754. Your number is so big that the step between representable numbers is bigger than what you try to add.

**Comment by EgorBo** [comment]
cc @tannergooding

**Comment by svick** [comment]
To see the problem described by @EgorBo, you can use the `Math.BitIncrement` method, which returns the next representable value:

```c#
double tmp4 = 836653375363579309516074612984d;
Console.WriteLine(tmp4);                           // 8.366533753635792E+29
Console.WriteLine(Math.BitIncrement(tmp4));        // 8.366533753635794E+29
Console.WriteLine(Math.BitIncrement(tmp4) - tmp4); // 140737488355328
```

You can see that the difference is a lot bigger than 5, which is why adding that value does nothing.

Also, notice that your first output line already has the "wrong" value, i.e. one that is different than the one in your code.

In general, you can expect around 15 decimal digits of precision from `double`.

**Comment by JulieLeeMSFT** [comment]
@Maximys do comments from egorbo and svick answer your question? If so, can we close this issue?

**Comment by Maximys** [comment]
@JulieLeeMSFT , yes, you can close this issue. Thank you so much
