### ISSUE TITLE
Non Open Source license notice in THIRD-PARTY-NOTICES.TXT

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#56394]
https://github.com/dotnet/runtime/pull/42476 introduced a bunch of code and an additional license with this note:

```
You acknowledge that this software is not designed, licensed or
intended  for  use  in  the  design, construction, operation or
maintenance of any nuclear facility.
```

That's a field-of-use restriction, which is not compatible with the [Open Source Definition](https://opensource.org/osd-annotated):
 
> 6. No Discrimination Against Fields of Endeavor
> 
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

Or with the [Debian Free Software Guidelines](https://www.debian.org/social_contract):

> No Discrimination Against Fields of Endeavor
>
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

[This license was also rejected by Fedora](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/3EPXMPK3PADRZ5PPWG53SKP3RZ6QAXQW/), as well as Red Hat (though I don't have a public reference for the last one).

cc @dleeapho @leecow @dseefeld @crummel @MichaelSimons

**Comment by tannergooding** [comment]
CC. @richlander

This could be worked around by switching to a different implementation that isn't from the musl libm. https://github.com/amd/aocl-libm-ose/ is one viable alternative as it is MIT licensed and doesn't appear to have any sublicensing requirements

**Comment by svick** [comment]
Just making sure: is that actually the correct license? https://github.com/dotnet/runtime/pull/42476#discussion_r498975234 talks about adding the "Sun license", but does not mention where exactly it came from.

And if this really is a problem, should musl be notified that it contains non-open source code?

**Comment by omajid** [comment]
I am not familiar with musl, but I took a quick look:

```
$ git remote -v
origin  git://git.musl-libc.org/musl (fetch)
origin  git://git.musl-libc.org/musl (push)
$ git rev-parse HEAD
1f0c7cb1cc2170bf230623dc0b57d9a9f001af08
$ grep -ir nuclear
$ grep -ir 'facility'
src/misc/syslog.c:static int log_facility = LOG_USER;
src/misc/syslog.c:void openlog(const char *ident, int opt, int facility)
src/misc/syslog.c:      log_facility = facility;
src/misc/syslog.c:      if (!(priority & LOG_FACMASK)) priority |= log_facility;
include/syslog.h:#define facilitynames ((CODE *)(const CODE []){ \
```

So musl doesn't have any reference to "nuclear facility", the concerning bit from THIRD-PARTY-LICENSE.TXT.

**Comment by jkotas** [comment]
@alexcovington Where did the "License notice for Sun Microsystems" you have added in #42476 came from? The Sun license notice in musl is much simpler: https://github.com/bminor/musl/blob/master/src/math/scalb.c

**Comment by alexcovington** [comment]
@jkotas If I remember right, it was this one: https://github.com/simonbyrne/libmcr/blob/master/copyright

**Comment by tannergooding** [comment]
We should likely be taking it from the official source: https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT?h=v1.2.2
and https://git.musl-libc.org/cgit/musl/tree/src/math/scalb.c?h=v1.2.2

which matches what @jkotas linked to in the person's fork above

**Comment by danmoseley** [comment]
Since the implementation does indeed match

https://git.musl-libc.org/cgit/musl/tree/src/math/scalbn.c?h=v1.2.2
https://git.musl-libc.org/cgit/musl/tree/src/math/scalbnf.c?h=v1.2.2

files that contain no license headers, and the encompassing musl notice says https://git.musl-libc.org/cgit/musl/tree/COPYRIGHT?h=v1.2.2 
```
Much of the math library code (src/math/* and src/complex/*) is
Copyright © 1993,2004 Sun Microsystems or
Copyright © 2003-2011 David Schultz or
Copyright © 2003-2009 Steven G. Kargl or
Copyright © 2003-2009 Bruce D. Evans or
Copyright © 2008 Stephen L. Moshier or
Copyright © 2017-2018 Arm Limited
and labelled as such in comments in the individual source files. All
have been licensed under extremely permissive terms.
```

It seems the work here is simply to remove the Sun license, leaving the musl MIT text, is that right? There is no code change needed.

**Comment by danmoseley** [comment]
@tannergooding do you agree with my assessment? If so I will remove this.

**Comment by richlander** [comment]
LGTM

**Comment by tannergooding** [comment]
@danmoseley that looks to be right.
