### ISSUE TITLE
CultureInfo.CurrentCulture is a readonly instance

### ISSUE THREAD

**Issue by rjmholt** [dotnet/runtime#56405]
### Description

From https://github.com/PowerShell/PowerShell/issues/15828.

The [.NET documentation on CultureInfo.CurrentCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture) indicates that in older versions of .NET Framework, it used to be a readonly API, but since .NET 4.6 it's settable. However it doesn't seem to document that the default object you get from the API is readonly (i.e. you can set the property, but you can't mutate the default value).

Looking through the git history, I think https://github.com/dotnet/runtime/commit/ea1203ab577d77cd951129c426d0e650ad60fda1 made this change, but I can't find any reference to it being made deliberately. Since that commit is a native code migration though, I can see how I might miss that the change wasn't actually made there.

Unfortunately, users have hit this in PowerShell 7 and are reporting it as a bug.

Is this change intentional? If so, I can open a doc issue.

### Configuration

- .NET 5.0.4
- Windows 10.0.19041
- x64
- 
Not known to be specific to that configuration.

### Workaround

```csharp
var culture = new CultureInfo("en-GB");
culture.DateTimeFormat.ShortDatePattern = "yyyy-MM-dd";
CultureInfo.CurrentCulture = culture;
```

**Comment by tarekgh** [comment]
@rjmholt thanks for reporting. Feel free to open issue in https://github.com/dotnet/dotnet-api-docs/ or to just submit a PR to fix that there.

**Comment by rjmholt** [comment]
>  Feel free to open issue in https://github.com/dotnet/dotnet-api-docs/ or to just submit a PR to fix that there.

Ok, so based on that I'm assuming this was intentional? Is there any reasoning around that?

**Comment by tarekgh** [comment]
@rjmholt I want back and reviewed the code we had in .NET Framework 4.5 and even 3.5 and I am seeing by default we always return read only object from CultureInfo.CurrentCulture. Here is the code from 3.5 as example which is setting the object as readonly. In which version you think we used to return mutable object from CurrentCulture?

```C#
private unsafe static CultureInfo InitUserDefaultCulture()
{
	int preferLCID = default(int);
	string fallbackToString = nativeGetUserDefaultLCID(&preferLCID, 1024);
	CultureInfo cultureByLCIDOrName = GetCultureByLCIDOrName(preferLCID, fallbackToString);
	if (cultureByLCIDOrName == null)
	{
		fallbackToString = nativeGetUserDefaultLCID(&preferLCID, 2048);
		cultureByLCIDOrName = GetCultureByLCIDOrName(preferLCID, fallbackToString);
		if (cultureByLCIDOrName == null)
		{
			return InvariantCulture;
		}
	}
	cultureByLCIDOrName.m_isReadOnly = true;
	return cultureByLCIDOrName;
}
```

**Comment by rjmholt** [comment]
Ok I've looked into this further (I originally took the original user's report at face value) and I have a rather mysterious result.

Running this directly as a .NET program I get the expected error:

![image](https://user-images.githubusercontent.com/7009879/127217228-58b6aede-a075-4dd1-899f-70fae4cc9329.png)

But running the same thing from Windows PowerShell "works":

![image](https://user-images.githubusercontent.com/7009879/127216643-82b81d9a-72d3-4d54-83ae-f37ce5a646a2.png)

And now it throws again in PS 7...

So this is clearly a PowerShell issue of some kind, but I have no idea how...

**Comment by tarekgh** [comment]
could be PowerShell is manually overriding the CurrentCulture with mutable object. It looks next step is to open issue for PowerShell :-) 

https://github.com/PowerShell/PowerShell

**Comment by rjmholt** [comment]
> It looks next step is to open issue for PowerShell :-)

Thanks, yeah, [that's where I came from](https://github.com/PowerShell/PowerShell/issues/15828) 🙂
