### ISSUE TITLE
Avoid cross references from reference to source projects via protection

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#56428]
https://github.com/dotnet/runtime/pull/56417 showed that it's possible to accidentally add a ProjectReference from a ref project to a source one. It should be possible to guarantee that this doesn't happen again via a Target that checks if a reference project is available when a source project is referenced from a reference project and throws in such cases. Performance should be considered as an IO operation per ProjectReference might slow down the build. As an optimization, the IO check could only be triggered if a ProjectReference's parent folder is "src".

Alternatively by merging reference and source projects we would avoid this problem entirely: https://github.com/dotnet/runtime/issues/37961.

**Comment by ericstj** [comment]
I gave this a try in https://github.com/ericstj/runtime/commit/66dca09639305ec25cfcd694ce82af0ef85088b4 and it caught both of the issues from #56417 and had no false positives.  @ViktorHofer, do you want me to put up a PR?

**Comment by ViktorHofer** [comment]
If the validation code allows to reference a source project that doesn't have a reference project but only a source one, i.e. System.Composition*, then sure please send a PR.

**Comment by ericstj** [comment]
We don't have any cases like that today, but I can imagine us getting there if we took a piecemeal approach to ref-project consolidation. In that case I'd expect us to permit it if the src-project referenced produced a reference assembly. I've added a condition for this.
