### ISSUE TITLE
System.Net.Security test run killed on Mono Linux

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56478]
System.Net.Security test suite is rather often killed on Mono - Linux (mostly RedHat 7 and SLES 12)
- High frequency -- failure ~1/day

Data from 7/8-8/23 (incl. PRs) ... with console logs verified:

Day | Run | OS
-- | -- | --
7/14 | Official run | SLES.12.Amd64.Open
7/15 | PR #55724 | RedHat.7.Amd64.Open
7/18 | Official run | RedHat.7.Amd64.Open
7/19 | Official run | SLES.12.Amd64.Open
7/19 | Official run | SLES.12.Amd64.Open
7/21 | PR #55664 | RedHat.7.Amd64.Open
7/23 | PR #56196 | RedHat.7.Amd64.Open
7/24 | PR #56211 | RedHat.7.Amd64.Open
7/27 | PR #56380 | RedHat.7.Amd64.Open
7/28 | PR #56466 | RedHat.7.Amd64.Open
7/28 | Official run | SLES.12.Amd64.Open
7/29 | PR #56534 | RedHat.7.Amd64.Open
8/5 | PR #56538 | RedHat.7.Amd64.Open
8/5 | PR #56568 | RedHat.7.Amd64.Open
8/8 | PR #57036 | RedHat.7.Amd64.Open
8/9 | PR #57005 | RedHat.7.Amd64.Open
8/9 | PR #55362 | RedHat.7.Amd64.Open
8/11 | Official run | SLES.12.Amd64.Open
8/11 | Official run | SLES.12.Amd64.Open (not a duplicate of above)
8/13 | PR #57210 | RedHat.7.Amd64.Open
8/14 | PR #57329 | RedHat.7.Amd64.Open
8/14 | Official run | RedHat.7.Amd64.Open
8/15 | PR #57432 | RedHat.7.Amd64.Open
8/15 | Official run | SLES.12.Amd64.Open
8/16 | PR #57501 | RedHat.7.Amd64.Open
8/18 | PR #57678 | RedHat.7.Amd64.Open
8/23 | Official run | SLES.12.Amd64.Open
8/24 | Official run - release/6.0 | RedHat.7.Amd64.Open
8/26 | PR #57996 | RedHat.7.Amd64.Open
8/30 | Official run - main=7.0 | SLES.12.Amd64.Open
8/31 | Official run - release/6.0 | SLES.12.Amd64.Open

Data from 3/29-7/8 (incl. PRs) -- without console log verification (the logs are not available anymore):
- Looks like **regression introduced on 4/26**

Day | Run | OS
-- | -- | --
4/26 | PR #51853 | RedHat.7.Amd64.Open
4/26 | PR #51620 | RedHat.7.Amd64.Open
4/27 | PR #51869 | RedHat.7.Amd64.Open
4/28 | PR #51976 | RedHat.7.Amd64.Open
4/29 | Official run | SLES.12.Amd64.Open
5/1 | PR #50815 | RedHat.7.Amd64.Open
5/3 | PR #52202 | RedHat.7.Amd64.Open
5/4 | PR #52147 | RedHat.7.Amd64.Open
5/4 | PR #52235 | RedHat.7.Amd64.Open
5/4 | Official run | SLES.12.Amd64.Open
5/5 | PR #52266 | RedHat.7.Amd64.Open
5/6 | PR #52344 | RedHat.7.Amd64.Open
5/7 | PR #52229 | RedHat.7.Amd64.Open
5/7 | PR #52373 | RedHat.7.Amd64.Open
5/7 | PR #52246 | RedHat.7.Amd64.Open
5/8 | Official run | SLES.12.Amd64.Open
5/8 | PR #52212 | RedHat.7.Amd64.Open
5/11 | Official run | SLES.12.Amd64.Open
5/12 | PR #52433 | RedHat.7.Amd64.Open
5/13 | PR #52691 | RedHat.7.Amd64.Open
5/14 | PR #52777 | RedHat.7.Amd64.Open
5/15 | PR #52812 | RedHat.7.Amd64.Open
5/17 | PR #52140 | RedHat.7.Amd64.Open
5/17 | Official run | SLES.12.Amd64.Open
5/18 | Official run | SLES.12.Amd64.Open
5/19 | Official run | Alpine.312.Amd64.Open
5/20 | PR #53044 | RedHat.7.Amd64.Open
5/21 | PR #50337 | RedHat.7.Amd64.Open
5/24 | PR #53180 | RedHat.7.Amd64.Open
5/25 | PR #53225 | RedHat.7.Amd64.Open
5/26 | Official run | Alpine.312.Amd64.Open
5/26 | PR #51953 | RedHat.7.Amd64.Open
5/27 | PR #53340 | RedHat.7.Amd64.Open
5/27 | PR #43954 | RedHat.7.Amd64.Open
5/28 | PR #53392 | RedHat.7.Amd64.Open
5/30 | PR #53450 | RedHat.7.Amd64.Open
6/1 | PR #48487 | RedHat.7.Amd64.Open
6/1 | PR #51665 | RedHat.7.Amd64.Open
6/3 | PR #53652 | RedHat.7.Amd64.Open
6/4 | PR #53716 | RedHat.7.Amd64.Open
6/8 | PR #48725 | RedHat.7.Amd64.Open
6/8 | PR #53669 | RedHat.7.Amd64.Open
6/9 | PR #52923 | Alpine.312.Amd64.Open
6/9 | PR #53866 | RedHat.7.Amd64.Open
6/9 | Official run | Debian.9.Amd64.Open
6/10 | PR #53968 | RedHat.7.Amd64.Open
6/11 | PR #53704 | RedHat.7.Amd64.Open
6/11 | PR #53882 | RedHat.7.Amd64.Open
6/11 | PR #54024 | RedHat.7.Amd64.Open
6/14 | Official run | SLES.12.Amd64.Open
6/15 | PR #53201 | RedHat.7.Amd64.Open
6/15 | PR #54098 | RedHat.7.Amd64.Open
6/17 | PR #54246 | RedHat.7.Amd64.Open
6/17 | PR #54289 | Alpine.312.Amd64.Open
6/17 | PR #54127 | RedHat.7.Amd64.Open
6/17 | Official run | RedHat.7.Amd64.Open
6/18 | PR #47640 | RedHat.7.Amd64.Open
6/21 | Official run | SLES.12.Amd64.Open
6/21 | PR #54186 | RedHat.7.Amd64.Open
6/22 | Official run | SLES.12.Amd64.Open
6/23 | PR #54253 | RedHat.7.Amd64.Open
6/24 | PR #53603 | RedHat.7.Amd64.Open
6/25 | PR #54685 | RedHat.7.Amd64.Open
6/26 | PR #54656 | RedHat.7.Amd64.Open
6/26 | PR #54246 | RedHat.7.Amd64.Open
6/26 | Official run | SLES.12.Amd64.Open
6/28 | Official run | SLES.12.Amd64.Open
6/28 | Official run | SLES.12.Amd64.Open
6/30 | PR #54254 | RedHat.7.Amd64.Open
6/30 | Official run | RedHat.7.Amd64.Open
6/30 | PR #54812 | RedHat.7.Amd64.Open
6/30 | PR #54959 | RedHat.7.Amd64.Open
7/1 | PR #54136 | RedHat.7.Amd64.Open
7/1 | PR #54625 | RedHat.7.Amd64.Open
7/1 | PR #55012 | RedHat.7.Amd64.Open
7/2 | PR #55076 | RedHat.7.Amd64.Open
7/6 | PR #55188 | RedHat.7.Amd64.Open
7/7 | PR #55258 | RedHat.7.Amd64.Open
7/7 | PR #55266 | RedHat.7.Amd64.Open
7/7 | Official run | SLES.12.Amd64.Open
7/8 | Official run | SLES.12.Amd64.Open

Example of log from 7/27:
- https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56380-merge-ae572e8845ac4fe9aa/System.Net.Security.Tests/console.f9389516.log?sv=2019-07-07&se=2021-08-16T14%3A19%3A31Z&sr=c&sp=rl&sig=RlC4y4P%2BmtdRIuYYn3uW8q94Q91vxO0bLUJJ12fcQNk%3D

<details>

```
Console log: 'System.Net.Security.Tests' from job ae572e88-45ac-4fe9-aaf0-b4dc6e8d9c57 workitem c9a39349-9953-4d79-8314-b7bf004c82ad (redhat.7.amd64.open.rt) executed on machine a000FA9
+ ./RunTests.sh --runtime-path /mnt/work/BBD00A47/p
----- start Tue Jul 27 14:43:07 UTC 2021 =============== To repro directly: =====================================================
pushd .
/mnt/work/BBD00A47/p/dotnet exec --runtimeconfig System.Net.Security.Tests.runtimeconfig.json --depsfile System.Net.Security.Tests.deps.json xunit.console.dll System.Net.Security.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/mnt/work/BBD00A47/w/A01A08F7/e /mnt/work/BBD00A47/w/A01A08F7/e
  Discovering: System.Net.Security.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Security.Tests (found 286 of 472 test cases)
  Starting:    System.Net.Security.Tests (parallel test collections = on, max threads = 2)
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_SelfSignedClientEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_ServerEKUClientAuth_Fails [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_ClientEKUServerAuth_Fails [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_NoEKUServerAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.SslStreamEKUTest.SslStream_NoEKUClientAuth_Ok [SKIP]
      Condition(s) not met: "IsRootCertificateInstalled"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_OnlyTls13CipherSuiteAllowedButChosenProtocolsDoesNotAllowIt_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicyAndTls13Supported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_OnlyNonTls13CipherSuiteAllowedButOtherSideDoesNotAllowIt_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowSameTwoOnBothSidesLessPreferredIsTls13_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.NegotiatedCipherSuite_SslProtocolIsTls13_ShouldBeTls13 [SKIP]
      Condition(s) not met: "Tls13Supported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowSomeCipherSuitesWithNoEncryptionOption_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_OnlyNonTls13CipherSuitesAllowedButChosenProtocolDoesNotAllowIt_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_ThreeCipherSuitesWithTwoOverlapping_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowedCipherSuitesIncludesSubsetOfInput_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowOneOnOneSideTls13_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicyAndTls13Supported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowTwoOnBothSidesWithSingleOverlapNonTls13_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_TwoCipherSuitesWithAllOverlapping_Success [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.Tls13IsSupported_GetValue_ReturnsTrue [SKIP]
      Condition(s) not met: "IsKnownPlatformSupportingTls13"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_AllowTwoOnBothSidesWithNoOverlapNonTls13_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_OnlyTls13CipherSuiteAllowedOtherSideDoesNotAllowTls13_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicyAndTls13Supported"
    System.Net.Security.Tests.NegotiatedCipherSuiteTest.CipherSuitesPolicy_NothingAllowed_Fails [SKIP]
      Condition(s) not met: "CipherSuitesPolicySupported"
    System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsyncNoRenego_Succeeds [SKIP]
      Condition(s) not met: "SupportsRenegotiation"
    System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_NegotiateClientCertificateAsync_ServerDontDrainClientData [SKIP]
      Condition(s) not met: "SupportsRenegotiation"
['System.Net.Security.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```
</details>

**Comment by karelz** [comment]
Potentially related massive hangs from 7/8-7/28 (incl. PRs):

Day | Run | OS | Notes
-- | -- | -- | --
7/8 | PR #55354 | Ubuntu.1604.Amd64.Open | 29 tests hang
7/19 | PR #55915 | RedHat.7.Amd64.Open | 29 tests hang

**Comment by karelz** [comment]
@marek-safar @steveisok @lewing can you please help get this Mono issue triaged against 6.0?

**Comment by lewing** [comment]
This is an odd failure that appears to be a timeout in the tests

https://dev.azure.com/dnceng/public/_build/results?buildId=1297452&view=logs&j=71afe768-e493-597c-228c-037834193aeb&s=b15d9194-8f26-5328-b47f-5968c76b37e7&t=fe87d331-02fa-5ca6-e382-69b0a11bb0f6&l=153

Looks somewhat similar but on coreclr (it's a crash not a hang but...)

**Comment by karelz** [comment]
@lewing I filed your failure in separate issue #57722

**Comment by lewing** [comment]
Assigning to 7.0 will review with @marek-safar and @steveisok when they are back.

**Comment by krwq** [comment]
ping

**Comment by adamsitnik** [comment]
Hit again in https://dev.azure.com/dnceng/public/_build/results?buildId=1678628&view=logs&j=3b5945b0-87a7-52cf-843a-406c21a8e27e

[Console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-47e3ad91888c450f92/System.Net.Security.Tests/1/console.eaf79791.log?sv=2019-07-07&se=2022-04-12T20%3A47%3A18Z&sr=c&sp=rl&sig=vvYfrZxzGuCR9EoQf0sU3d%2FQoaxSAS1vyXbnsi6Z4AE%3D) says it's due to `EXECUTION TIMED OUT` but there were no `Long Running Test` reported.

**Comment by danmoseley** [comment]
> due to EXECUTION TIMED OUT but there were no Long Running Test reported.

IIRC we've seen this with crypto tests also. It's consistent with the tests completing, then something hanging.

**Comment by lewing** [comment]
I wonder if it is the runtime process failing to exit and timing out?

cc @lambdageek

**Comment by adamsitnik** [comment]
> It's consistent with the tests completing, then something hanging.

With BenchmarkDotNet I've observed such behavior for types with locking finalizers (https://github.com/dotnet/BenchmarkDotNet/pull/1571).

**Comment by danmoseley** [comment]
I have also seen a manifestation that was fixed a few days ago herE: https://github.com/dotnet/runtime/pull/67166

**Comment by rzikm** [comment]
This issue has not been seen for at least 60 days, closing until this resurfaces.
