### ISSUE TITLE
ComWrappers feature imbalance between platforms

### ISSUE THREAD

**Issue by b-iotti** [dotnet/runtime#56474]
As a part of enabling support for [`ComWrappers`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.comwrappers) on non-Windows platforms, the feature availability across platforms is now different.

Once the contents of #54838 are in place, non-Windows platforms will be allowed to use the `IUnknown` interfaces.

Currently, the following are Windows-only:
- [ ] Marshalling - Some APIs, such as [`Marshal.GetIUnknownForObject`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshal.getiunknownforobject), respect the "Global registration" of `ComWrappers` but currently those APIs are Windows only. We should enable all `Marshal` APIs that support the `ComWrappers` API.
   - Related: https://github.com/dotnet/runtime/issues/54317
- [x] Update existing API testing https://github.com/dotnet/runtime/issues/51072
- [x] Platform compatibility metadata - `ComWrappers` is currently marked as only supported on Windows:
https://github.com/dotnet/runtime/blob/a6b9a63f3521d8217c3639aefd97001287f78ae8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.cs#L72-L74
   - Should be able to remove that attribute on the `ComWrappers` class
   - Might be a good idea to mark just the `RegisterForMarshalling` method as only supported on windows (based on the lack of marshalling with the global instance above)

**Comment by AaronRobinsonMSFT** [comment]
The addition of the new ["unwrapping" APIs on `ComWrappers](https://github.com/dotnet/runtime/pull/80402) makes the final checkbox above unnecessary. The API disparity still exists but at this point there is no strong push for it be addressed. If people find this issue, we can reconsider on an API by API basis.
