### ISSUE TITLE
ReaderWriterLock.IsLockHeld randomly fails in .NET 5

### ISSUE THREAD

**Issue by psantosl** [dotnet/runtime#56497]
### Description

We develop Plastic SCM, and we are creating a new GUI for it based on Avalonia and .NET 5.0. Plastic has been in development for years, starting on .net 2.0 and mono. This code uses ReaderWriterLock and has been working without issues for a long time (which does not mean it is bug free).

The problem is that the code needs to upgrade a reader lock to a writer lock, and before doing that, it checks that "a lock is held". Well, sometimes it doesn't work. We never saw it in .NET Framework or Mono, but as soon as we ported to .NET 5, it is failing randomly.

### Configuration
* Which version of .NET is the code running on? .NET 5
* What OS and version, and what distro if applicable? macOS
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Other information
We were unable to repro on an isolated application, it just happens with the full Plastic SCM GUI running on macOS.

Here you can see the issue, based on our logs (check the lines marked with ** as relevant ones):

* Line 02: Thread 18 acquires a readerlock. IsReaderLockHeld goes to true.
* Line 11: Thread 18 IsReaderLockHeld is false incorrectly! There is 1 reader inside.
* Line 14: A new reader lock is requested, but again IsReaderLockHeld:False incorrectly.
There are other threads operating inside the same context, just adding complexity.

As I said, we can't repro with a single-threaded simple scenario.

```
00 - 2021-07-28 18:30:42,438 tester DEBUG WorkspaceTree - AcquireReaderLockBefore:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:IsReaderLockHeld:False.Count:0
01 - 2021-07-28 18:30:42,441 tester DEBUG WorkspaceTree - AcquireReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:1
02 - 2021-07-28 18:30:42,448 tester DEBUG WorkspaceTree - AcquireReaderLockBefore:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:**IsReaderLockHeld:True**.Count:1
03 - 2021-07-28 18:30:42,448 tester DEBUG WorkspaceTree - AcquireReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:2
04 - 2021-07-28 18:31:03,701 tester DEBUG WorkspaceTree - AcquireReaderLockBefore:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:1:IsReaderLockHeld:False.Count:2
05 - 2021-07-28 18:31:03,701 tester DEBUG WorkspaceTree - AcquireReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:1.Count:3
06 - 2021-07-28 18:32:25,124 tester DEBUG WorkspaceTree - ReleaseReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:2
07 - 2021-07-28 18:32:25,125 tester DEBUG WorkspaceTree - ReleaseReaderLockAfter:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:IsReaderLockHeld:False
08 - 2021-07-28 18:32:25,125 tester DEBUG WorkspaceTree - AcquireReaderLockBefore:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:IsReaderLockHeld:False.Count:2
09 - 2021-07-28 18:32:25,125 tester DEBUG WorkspaceTree - AcquireReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:3
10 - 2021-07-28 18:32:40,617 tester DEBUG WorkspaceTree - ReleaseReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:2
11 - 2021-07-28 18:32:40,618 tester DEBUG WorkspaceTree - ReleaseReaderLockAfter:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:**IsReaderLockHeld:False**
12 - 2021-07-28 18:32:40,617 tester DEBUG WorkspaceTree - ReleaseReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:1.Count:1
13 - 2021-07-28 18:32:40,618 tester DEBUG WorkspaceTree - ReleaseReaderLockAfter:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:1:IsReaderLockHeld:False
14 - 2021-07-28 18:32:40,633 tester DEBUG WorkspaceTree - AcquireReaderLockBefore:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18:**IsReaderLockHeld:False**.Count:1
15 - 2021-07-28 18:32:40,633 tester DEBUG WorkspaceTree - AcquireReaderLock:946360b4-5cfe-4d92-b13a-f9c4478828d7:Thid:18.Count:2
```

**Comment by psantosl** [comment]
If we copy/paste the ReaderWriterLock.cs code inside our app, and rebuild, the issue does not happen. Maybe some optimization setting is killing us.

**Comment by mangod9** [comment]
Hi @psantosl,  Is it possible to provide a dump when such a situation occurs?

**Comment by psantosl** [comment]
The dump just shows a deadlock, but the problem is that the IsReaderLockHeld did not work as expected :'(
