### ISSUE TITLE
Module.ScopeName returns `appname.dll` for single-file apps

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#56519]
When published as a single file, this code prints `single-file.dll`.

```C#
class Program
{
    public static void Main()
    {
         Console.WriteLine(typeof(Program).Assembly.GetModules()[0].ScopeName);
    }
}
```

It's unclear whether this is the correct behavior or just an oversight. `Name` and `FullyQualifiedName` both return `<Unknown>`

**Comment by jkotas** [comment]
I think it is the correct behavior. ScopeName is meant to return the scope name from metadata, with no sugar coating.

**Comment by agocke** [comment]
Is `.dll` appropriate? That was the strange part for me.

**Comment by agocke** [comment]
If we do not end up changing this behavior, I think the behavior change should maybe be on MetadataLoadContext (at the suppression in https://github.com/dotnet/runtime/pull/56196) to produce a string different from `<Unknown>` when loading from memory

**Comment by jkotas** [comment]
> I think the behavior change should maybe be on MetadataLoadContext 

Agree. `ScopeName` should return [`ModuleDefinition.Name`](https://docs.microsoft.com/dotnet/api/system.reflection.metadata.moduledefinition.name)

> Is .dll appropriate?

Roslyn uses the filename, including the suffix, for this by default. You can override the default using `/modulename` Roslyn switch. E.g. Compile .dll with `/modulename:banana` - `ScopeName` will return `banana` without `.dll` suffix.

**Comment by agocke** [comment]
I'm going to close this as by-design. Changing these values now seems like low value without a motivating scenario.
