### ISSUE TITLE
Why on Ctrl+C my process suddenly stopped on “Task<T>.Result”, but works fine with “await Task<T>”?

### ISSUE THREAD

**Issue by kentlinux** [dotnet/runtime#56529]
Please help to understand what's going on. 

I have async method. It return `Task<T>`.

I need wait this method result BUT with correct stop by Ctrl+C.

The problem is:

If I wait in this way - all works fine:

      var result = await Task<T>
If I wait in this way - main process suddenly stoped:

      var result = Task<T>.Result 
To show it in code, I write small test (sorry - I can't make it smaller)

```
using System;
using System.Threading.Tasks;

namespace StopTest4
{
    internal static class ConsoleApp
    {
        private static readonly TaskCompletionSource<bool> GetFirstString = new TaskCompletionSource<bool>();

        private static void OnCancelKeyPressed(object sender, ConsoleCancelEventArgs args)
        {
            Console.WriteLine("Got Stop Signal (by Crt+C)");
            GetFirstString.TrySetResult(false);
            
            args.Cancel = true;
        }

        public static int Main(string[] args)
        {
            try
            {
                var appTask = RunAsync();

                Console.CancelKeyPress += OnCancelKeyPressed;

                return appTask.Result;
            }
            catch (Exception e)
            {
                Console.WriteLine($"Got exception while run main task of the App - {e}");
            }

            return -2;
        }
        
        
        private static async Task<int> RunAsync()
        {
            Console.WriteLine("RunAsync START");
            try
            {
                await LoadWorksFine().ConfigureAwait(false);
                //await LoadWithProcessSuddenlyClose().ConfigureAwait(false);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Got Exception - {e}");
            }
            Console.WriteLine("Stopped!");
            return 0;
        }

        private static Task LoadWithProcessSuddenlyClose()
        {
            try
            {
                Console.WriteLine($"Befor LoadString");
                var result = LoadString().Result;
                Console.WriteLine($"After LoadString - result=\"{result}\"");
            }
            catch (Exception e)
            {
                Console.WriteLine($"LOAD: Got Exception - {e}");
            }
            return Task.CompletedTask;
        }

        private static async Task LoadWorksFine()
        {
            try
            {
                Console.WriteLine($"Befor LoadString");
                var result = await LoadString();
                Console.WriteLine($"After LoadString - result=\"{result}\"");
            }
            catch (Exception e)
            {
                Console.WriteLine($"LOAD: Got Exception - {e}");
            }
        }

        private static async Task<string> LoadString()
        {
            Console.WriteLine($"LoadString: Start");
            try
            {
                if (!await GetFirstString.Task.ConfigureAwait(false))
                {
                    Console.WriteLine($"LoadString: waited task Failed!");
                    return "false";
                }
                Console.WriteLine($"LoadString: waited task Success!");
                return "true";

            }
            catch (Exception e)
            {
                Console.WriteLine($"LoadString: Got Exception - {e}");
            }
            return null;
        }

    } 
}
```
How to check:

If You run the test and press Ctrl+C you will see such output:

```
% dotnet StopTest4.dll
RunAsync START
Befor LoadString
LoadString: Start
^CGot Stop Signal (by Crt+C)                  <---- Here press Ctrl+C
LoadString: waited task Failed!
After LoadString - result="false"
Stopped!
%
```
All works fine!

Now in method RunAsync comment LoadWorksFine() and uncomment LoadWithProcessSuddenlyClose(). Like this:

```
    private static async Task<int> RunAsync()
    {
        Console.WriteLine("RunAsync START");
        try
        {
            //await LoadWorksFine().ConfigureAwait(false);
            await LoadWithProcessSuddenlyClose().ConfigureAwait(false);
        }
        catch (Exception e)
        {
            Console.WriteLine($"Got Exception - {e}");
        }
        Console.WriteLine("Stopped!");
        return 0;
    }
```
Now run the test and press Ctrl+C you will see such output:

```
% dotnet StopTest4.dll
RunAsync START
Befor LoadString
LoadString: Start
^C                  <---- Here press Ctrl+C
%
```
There are no any exceptions or errors - just process stopped.

It works on MacOS, Linux and Windows.

Who knows why? As for me - both variants correct.

Thank You!

**Comment by stephentoub** [comment]
Because your example is synchronously blocking the RunAsync method waiting for the handler to be invoked,  but by that point you haven't hooked up the handler.  So when ctrl-C is pressed, there isn't a handler to cancel the ctrl-C, and the OS kills the process.

**Comment by kentlinux** [comment]
> Because your example is synchronously blocking the RunAsync method waiting for the handler to be invoked, but by that point you haven't hooked up the handler. So when ctrl-C is pressed, there isn't a handler to cancel the ctrl-C, and the OS kills the process.

Thanks! You are right! In this code:

 1  var appTask = RunAsync();
 2
 3 Console.CancelKeyPress += OnCancelKeyPressed;
 4 
 5 return appTask.Result; 

Line 3 never called.

BUT, can You explain WHY?

On line 1 I create Task. Only create. I wait the task on line 5.
Why line 3 never called?

**Comment by stephentoub** [comment]
> BUT, can You explain WHY?

I was trying to.  I'll try again.

You call RunAsync:
```C#
var appTask = RunAsync();
```
RunAsync calls LoadWithProcessSuddenlyClose:
```C#
await LoadWithProcessSuddenlyClose().ConfigureAwait(false);
```
Note that this is exactly the same as if you'd written:
```C#
Task t = LoadWithProcessSuddenlyClose().ConfigureAwait(false);
await t;
```
meaning you're calling LoadWithProcessSuddenlyClose synchronously from RunAsync, and there are no awaits that complete asynchronously prior to it, so your Main method has synchronously invoked LoadWithProcessSuddenlyClose.  Then LoadWithProcessSuddenlyClose synchronously blocks:
```
var result = LoadString().Result;
```
waiting for the ctrl-C handler to be invoked.  You've created a deadlock: you're blocking waiting for something that can only happen after this call returns, because it's only hooked up after this call returns, but this call will never return because it requires the hooked up thing from being invoked to do so.

**Comment by kentlinux** [comment]
Thank You! Now I understood!
