### ISSUE TITLE
Task-Like custom implementation breaks AsyncLocal data 

### ISSUE THREAD

**Issue by jlchavez** [dotnet/runtime#56594]
I've created a custom Task object that uses a custom TaskMethodBuilder, that should interact with some scoped data that will flow through the async calls. When using the .net Task object it works fine, but when done in OperationTask (my custom task) the data get's stuck until in returns to a normal Task. The OperationTask has a Wrapper that points to the current OperationScope on the current thread, based on AsyncLocal. New OperationScopes can be created at any point, something like TransactionScope.

The sample project provides a couple of tests for each scenario, two for Task and two for OperationTask, and the Test returns a Success since the OperationScope Id (shown in brackets) goes up and down as expected when scopes are created and destroyed.

On the Task tests, AsyncLocal flows correctly, as described by this diagnostics

```
Standard Output: 
    [0] SetUp
    [1] Calling async method
    [2] Emulating another scope
    [3] AsyncStep1 Start
    [3] AsyncStep1 End
    OperationScope 3 Disposed 
    --- Pop Wrapper ---
    On Pop OperationScope to 2
    OperationScope 2 Disposed 
    --- Pop Wrapper ---
    On Pop OperationScope to 1
    [1] Back from async method <= EXPECTED BEHAVIOR CORRECT
    Success
    --- Pop Wrapper ---
    On Pop OperationScope to 0
    [0] TearDown
```

On the OperationTask test all push and pop to the stack goes fine, until returning to the parent method, before the TearDown. There is an internal call to Push and Pop on the OprationTaskMethodBuilder, but without them the results are the same.

```
Standard Output: 
    [0] SetUp
    [1] Calling async method
    [2] AsyncStep3 Pushing new scope
    [3] AsyncStep3 Start
    [3] AsyncStep1 End
    OperationScope 3 Disposed 
    --- Pop Wrapper ---
    On Pop OperationScope to 2
    --- Pop Wrapper ---
    On Pop OperationScope to 1
    [3] Back from async method  <= THIS IS WERE IT SHOULD SHOW 1, BUT SHOWS 3
    --- Pop Wrapper ---
    On Pop OperationScope to 0
    [0] TearDown
```

The sample project is located at https://github.com/jlchavez/OperationResult, with the source code library and the NUnit Tests.
Testing in Visual Studio 16.10.1 and .NET 5

I don't know if it is a bug in custom task-like calls or if it's a bug in my code, but if someone could help diagnose this because you know better .net core, it would be great help, so that can point me to what is wrong, on the part of AsyncLocal interaction.

Thanks.

**Comment by davidfowl** [comment]
Your async method builder needs to implement execution context capture and restore. You can copy what the default implementation does to make it work the way you would expect

**Comment by stephentoub** [comment]
Closing as answered.
