### ISSUE TITLE
The State of Future Support for .NET on the HarmonyOS platform

### ISSUE THREAD

**Issue by 0x5350** [dotnet/runtime#56632]
Good day. 

Recently, Huawei announced HarmonyOS, and their full initial product line and ecosystem for the new OS and ecosystem. The new OS will run on phones, snartwatches, smart TVs and embedded devices, fitting very much in line with .NET's idea of a cross-platform framework for developing _all_ your apps.

Huawei already has a huge user base, and anyway, HarmonyOS may gain large traction. Already, a huge amount of Huawei devices exist that will receive HarmonyOS, and many new ones will be manufactured.

As a result, it makes sense that the Open platform, .NET, would eventually gain support for it.

Then, given the large user base of Huawei devices, and their popularity in regions such as South Africa where Huawei is the most popular platform, it would make sense that eventual work would be done to bring HarmonyOS support to the platform.

What, then, will be the future state of work on the .NET platform to support the future HarmonyOS platform that will run on countless devices, both present and future?

**Comment by buchuitoudegou** [comment]
😅

**Comment by danmoseley** [comment]
@richlander

**Comment by richlander** [comment]
Interesting idea. We welcome Huawei or the community to make this opportunity a reality. This is similar to how Samsung invested in making .NET available for Tizen. We have collaborated with Samsung over multiple releases. We'd by happy to do the same again with another group. This isn't a project that the .NET Team intends to take on.

**Comment by 0x5350** [comment]
Quite right. The awesome spirit of community made .NET on Tizen a reality.  I suppose the same will happen for HarmonyOS. It's still early days, so we'll see what happens!

**Comment by richlander** [comment]
Sure. If HarmonyOS grows to become a strong ecosystem alongside Android and iOS then that would certainly be of interest to .NET developers (and they'd tell us) and to the team. This is the first I've heard of a request for .NET on HarmonyOS. We'll watch and see how ecosystem adoption for HarmonyOS progresses globally.

**Comment by 0x5350** [comment]
Awesome. Thanks so much for your assistance! This would be quite an interesting topic going forward. For now, then, in the early days of this new ecosystem, I guess it's up to the community to begin realising such a project.
