### ISSUE TITLE
[libraries] CoreCLR Linux x64 Test_BadEventSource_MismatchedIds Event Activity not empty

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#56642]
```
BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds [FAIL]
      Assert.Equal() Failure
      Expected: 00000000-0000-0000-0000-000000000000
      Actual:   f0c32f75-9212-44df-9585-e78b65800480
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsUserErrors.cs(136,0): at BasicEventSourceTests.TestsUserErrors.Test_Bad_EventSource_Startup(Boolean onStartup, Listener listener, EventSourceSettings settings)
        /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsUserErrors.cs(85,0): at BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds()
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1268612&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56583-merge-e0490a57708e42389f/System.Diagnostics.Tracing.Tests/console.a2a05ddf.log?sv=2019-07-07&se=2021-08-19T16%3A23%3A15Z&sr=c&sp=rl&sig=c2IwhvostiWjP1WXXJ9kj33Ly3uC8E5F11qQjdIlVlU%3D

**Comment by josalem** [comment]
Based on the timing of the test failure this was probably just a hit of #56279 before #56442 was merged (~5 hours ago which is when the test failure happened as well). I'll close this for now, and we can reopen this or #56279 if we see the failure again.
