### ISSUE TITLE
Nullability of JsonConverter.Write(T value) not correct

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#56645]
The method `JsonConverter<T>.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)` has a non-nullable `T value` but `null` can be passed if the converter overrides the `bool HandleNull {get}` method and returns true. That method was added in 5.0 so I believe there was miscommunication around the nullability there. The default is `false` meaning `null` is not passed and the serializer handles it.

### API suggestion:
```diff
namespace System.Text.Json.Serialization
{
    public abstract class JsonConverter<T> : System.Text.Json.Serialization.JsonConverter
    {
-       public abstract void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options);
+       public abstract void Write(Utf8JsonWriter writer, T? value, JsonSerializerOptions options);
    }
}
```

This is a compile-time breaking change for all custom converters (which are common) that are compiled in a nullable context.

Note the corresponding ["T? Read()"](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L143) method already supports nullability.

@stephentoub are we still making nullable changes in 6.0 like this?

**UPDATE**: per discussion, we will unannotate the `value` parameter instead of making it nullable. This may prevent consumers from assuming the converter can always handle `null`. Each derived type should specify the appropriate nullability on the `value` parameter.

**Comment by stephentoub** [comment]
> @stephentoub are we still making nullable changes in 6.0 like this?

Yes. cc: @jeffhandley

**Comment by jeffhandley** [comment]
@steveharter We have been treating nullable annotation mistakes as bugs; we don't need to go through API Review. Instead, we are simply aggregating the changes made in documentation by adding them to dotnet/docs#21202.

**Comment by jeffhandley** [comment]
...although considering that partner team projects are likely to be affected by this change, we should send out an upcoming breaking change announcement to the internal mailing list for the change before this gets merged in.

**Comment by eiriktsarpalis** [comment]
How common is it for custom converters to enable `HandleNull`? I'm slightly concerned that even though technically this would be the correct annotation, it would be adding noise to the vast majority of custom converters that haven't opted into null handling. My expectation is that users overriding `HandleNull` probably know what they are doing and will likely add the needed null check.

**Comment by steveharter** [comment]
> How common is it for custom converters to enable HandleNull? I'm slightly concerned that even though technically this would be the correct annotation, it would be adding noise to the vast majority of custom converters that haven't opted into null handling.

It is likely rare, although the feature was requested by the community.

This is more of a best practice question around nullability -- do we error on the side of correctness (it can be null in some cases, even if rare) or the most common cases? I believe we've been erroring on the side of correctness. 

@jeffhandley thoughts?

**Comment by jeffhandley** [comment]
What's the risk of being incorrect here? What kind of bugs could materialize with an incorrect annotation for when someone does opt into `HandleNull`?

**Comment by steveharter** [comment]
My understanding is that we want to always annotate for nullability even for the rare cases. E.g. `Activator.CreateInstance()` may return a `null` object in rare cases so the return value is nullable.

> What's the risk of being incorrect here?

Since this is on an abstract base class, there are both author and consumer implications:
- For an author, which overrides `HandleNull` to return true, the annotation is not correct.
- For an author, which does not override `HandleNull` (which is the common case), the annotation is not accurate since `value` cannot be `null`.
- For a consumer that calls a custom converter's `Write()` method directly, the annotation may not be correct if the converter supports returning null. The consumer should check `HandleNull` before calling the converter.

**Comment by eiriktsarpalis** [comment]
> This is more of a best practice question around nullability -- do we error on the side of correctness (it can be null in some cases, even if rare) or the most common cases? I believe we've been erroring on the side of correctness.

Good question. We have a [document](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md#annotation-guidance) detailing nullability annotation guidelines. IIRC during the .NET 5 annotation effort we did have a few API annotations intentionally deviate from the underlying implementation out of usability concerns, although at this point I can't remember which. Perhaps @stephentoub, @buyaa-n or @krwq do.

> For a consumer that calls a custom converter's Write() method directly, the annotation may not be correct if the converter supports returning null. The consumer should check HandleNull before calling the converter.

If anything, that may be an argument against making the change, since most existing converters do not handle null values. For example, the following code will currently correctly produce a nullability warning
```csharp
JsonSerializer.Serialize(new MyPoco()); // throws NullReferenceException

[JsonConverter(typeof(MyPocoConverter))]
public class MyPoco
{
    public JsonDocument? Document { get; set; }
}

public class MyPocoConverter : JsonConverter<MyPoco>
{
    public override void Write(Utf8JsonWriter writer, MyPoco value, JsonSerializerOptions options)
    {
        var converter = (JsonConverter<JsonDocument>)options.GetConverter(typeof(JsonDocument));
        converter.Write(writer, value.Document, options); // will currently correctly produce a nullability warning
    }

    public override MyPoco? Read(ref Utf8JsonReader reader, Type _, JsonSerializerOptions options)
    {
        throw new System.NotImplementedException();
    }
}
```
but would not produce any warnings using the proposed signature.

**Comment by stephentoub** [comment]
We want the annotation to be as accurate as possible.  If it's possible null might be passed in, the default stance is it should be nullable.

The main exemptions we've made are places like `System.Reflection.InterfaceMapping`.  It's a struct with public reference-type fields, so, technically, they should be nullable.  However, no one has any reason to create one of these outside of the runtime APIs that produce them, and it always sets them to non-null.  As such, making them nullable would have made all consumption more complicated for no actual benefit.

In this HandlesNull case, the Write argument will only ever be null if this class overrides HandleNull to return true?  I could see an argument made that the code is opting-in to violating the nullability annotations by overriding HandleNull.  At the same time, that's not necessarily the case, if converter A derives from JsonConverter and overrides HandleNull, and then component B derives from A, at which point it might be given nulls and hasn't overridden HandleNull.

**Comment by jeffhandley** [comment]
> at which point it might be given nulls and hasn't itself overridden HandleNull.

That's the kind of risk I was looking for. If the annotations give a false sense of safety, and code becomes less defensive because of it, and then bugs can surface (especially in something like serialization), then that's very high risk methinks.

**Comment by jeffhandley** [comment]
> but would not produce any warnings using the proposed signature.

I overlooked that sentence in @eiriktsarpalis's comment previous. If we were to change it, and there is no nullability warning there, what would happen at runtime for that scenario?

**Comment by stephentoub** [comment]
> what would happen at runtime for that scenario?

Depends on the converter implementation.  If it was written trusting the reference type argument nullability annotations, there's a good chance it would null ref.  If it was written not trusting the nullability annotation, it would do the null check and do whatever it wanted in response to null.

> I overlooked that sentence

I did, too.  Essentially we're saying we've made the nullability of a particular parameter variant based on an unrelated virtual property.  Fundamentally, the problem here is we have no way to express that with nullable annotations.  We're also saying we expect these method to be both overridden and invoked, which no matter what annotation we pick is going to produce the wrong answer for someone.  We should consider the implications of using `#nullable disable`/`#nullable restore` around that parameter to just make it oblivious.

**Comment by eiriktsarpalis** [comment]
> > what would happen at runtime for that scenario?
>
> Depends on the converter implementation. If it was written trusting the reference type argument nullability annotations, there's a good chance it would null ref. If it was written not trusting the nullability annotation, it would do the null check and do whatever it wanted in response to null.

Like many converters, it does trust the annotation and does indeed null ref. One could argue we should change the annotation and also update all OOB and third party converters to handle null. But if that becomes the new best practice, what's the point of `HandleNull`? All converters would now need to handle null.

> I did, too. Essentially we're saying we've made the nullability of a particular parameter variant based on an unrelated virtual property. Fundamentally, we have no way to express that with nullable annotations. We're also saying we expect this method to be both overridden and invoked, which no matter what annotation we pick is going to produce the wrong answer for someone. We should consider the implications of using #nullable disable/#nullable restore around that parameter to just make it oblivious.

I think it is an issue of thoroughly documenting the modality that `HandleNull` introduces. It should be easy to accomplish since the name of the property is fairly suggestive.

> if converter A derives from JsonConverter and overrides HandleNull, and then component B derives from A, at which point it might be given nulls and hasn't itself overridden HandleNull.

How common would such a scenario be? Our OOB converters as well as most of our documentation seem to encourage a compositional model rather than one based on inheritance. I don't think it's a concern that warrants introducing unnecessary null checks in 95% of converter implementations out there.

**Comment by stephentoub** [comment]
> I think it is an issue of thoroughly documenting the modality that HandleNull introduces. It should be easy to accomplish since the name of the property is fairly suggestive.

If we annotate the parameter, no matter how we annotate it we're going to get it wrong for some use.  So why annotate it at all?  Hence: "We should consider the implications of using #nullable disable/#nullable restore around that parameter to just make it oblivious."

**Comment by steveharter** [comment]
Since the consumer scenario where someone calls the converter directly (Eirik's example) may NullReference, that is a good reason not to add the annotation. When forwarding to a converter in that example, `HandleNull` should be inspected to determine if it should call the converter or just write null for it, but since we can't enforce that pattern, erroring on the side of safety seems better even though it goes against the mainstream nullability practices.

FWIW the canonical example of overriding `HandleNull` and returning `true` is a custom String converter that writes a `null` string reference an empty JSON string (instead of writing null or ignoring it). In any case, these scenarios should be rare.

So new proposed plan:
- Disable nullable around that parameter
- Update the existing xml doc for Write() to mention HandleNull.

**Comment by steveharter** [comment]
Since the consumer scenario where someone calls the converter directly (Eirik's example) may NullReference, that is a valid reason not to add the nullable annotation. When forwarding to a converter in that example, HandleNull should be called first to determine if it should call the converter or just write null for it, but since we can't enforce that pattern, erroring on the side of safety seems better even though it goes against the mainstream nullability practices.

Also, not obvious, but if we don't annotating nullable on the base class `JsonConverter<T>.Write(...)` it does allow a derived converter to add the nullable if it overrides `AllowNull` and returns `true`, so nullability should be (or can be made) correct for consumers if calling the concrete converter class which should be the common case.

FWIW the canonical example of overriding HandleNull and returning true is a custom String converter that writes a null string reference an empty JSON string (instead of writing null or ignoring it). In any case, these scenarios should be rare.

To enumerate the options:
1) Leave as-is; the parameter is considered not nullable. May prevent NullReferences, but nullability annotations go against mainstream guidance.
2) Change to nullable; consumers that call "normal" converters may assume `null` is handled, causing NullReference.
3) (**suggested**) Do not annotate the value on the base class `JsonConverter<T>`. Although no nullability attributes are written to IL for `JsonConverter<T>.Write()`, currently for Roslyn this appears is going to be the same as (1) where ! may be needed when calling the base class in order to prevent a warning\error. See sample below.

In all cases, we should also update the existing xml doc for Write() to clear up the semantics and mention HandleNull.

<details>
  <summary>Sample code</summary>

```cs
#nullable enable

using System;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            // Use a converter that is annotated with nullable:
            NullableConverterString nullable = new();
            nullable.Write(null);
            Converter<string?> baseNullable = nullable;
            baseNullable.Write(null);
            Converter<string> baseNullable2 = nullable!;
            baseNullable2.Write(null); // error, but should work?

            // Use a converter that is annotated with non-nullable:
            NonNullableConverterString nonnullable = new();
            nonnullable.Write(null); // error, as expected
            Converter<string> baseNonNullable = nonnullable;
            baseNonNullable.Write(null); // error, but should work?

            // Use a converter that is not annotated:
            NotAnnotatedConverterString notAnnotated = new();
            notAnnotated.Write(null);
            Converter<string> notAnnotatedBase = notAnnotated;
            notAnnotatedBase.Write(null); // error, but should work?
        }
    }

    public class Converter<T>
    {
        public virtual void Write(
#nullable disable
        T
#nullable enable
            value)
        {
            if (true)
            {
                Console.WriteLine(value?.ToString());
            }
        }
    }

    public class NullableConverterString : Converter<string?>
    {
        public override void Write(string? value)
        {
            base.Write(value);
        }
    }

    public class NonNullableConverterString : Converter<string>
    {
        public override void Write(string value)
        {
            base.Write(value);
            base.Write(null); // error, but should work?
        }
    }

#nullable disable
    public class NotAnnotatedConverterString : Converter<string>
    {
        public override void Write(string value)
        {
            base.Write(value);
            base.Write(null);
        }
    }
#nullable enable
}
```
</details>

**Comment by jeffhandley** [comment]
I support the suggested `#3` option of being "oblivious" here, and I think this could set a good precedent for the scenario of both nullable and non-nullable being incorrect leading us to be intentionally oblivious.

**Comment by eiriktsarpalis** [comment]
> Although no nullability attributes are written to IL for JsonConverter<T>.Write(), currently for Roslyn this appears is going to be the same as (1) where ! may be needed when calling the base class in order to prevent a warning\error. See sample below.

Curious how making the parameter oblivious changes warning semantics here. Switching between non-nullable and nullable-oblivious in the base method of your code sample did not produce a different set of warnings.

**Comment by jeffhandley** [comment]
> Switching between non-nullable and nullable-oblivious in the base method of your code sample did not produce a different set of warnings.

Ah, indeed. Here's an illustration of the behavior.  I believe the new reflection APIs would express the difference, but the editor isn't presenting the oblivious state.

![image](https://user-images.githubusercontent.com/1031940/128411991-0d7d62a6-0694-4df7-82f6-0c62f09694fb.png)
