### ISSUE TITLE
ICorDebugProcess5::EnumerateHeapRegions returned a COR_SEGMENT that grow backwards under USE_REGIONS

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#56653]
I attempted to enumerate the POH regions using the API, but the API gave me a `COR_SEGMENT` structure with `start >= end`, which does not make sense.

**Comment by josalem** [comment]
CC @davmason

**Comment by davmason** [comment]
The heap data parsing happens in https://github.com/dotnet/runtime/blob/f83a9d9689433ce522b91e74a9631c83847e3b64/src/coreclr/debug/daccess/dacdbiimpl.cpp#L6891-L6986

It looks like it gets the data from this function:
https://github.com/dotnet/runtime/blob/f83a9d9689433ce522b91e74a9631c83847e3b64/src/coreclr/debug/daccess/dacdbiimpl.cpp#L6740-L6815

Specifically the line `dac_generation poh  = *GenerationTableIndex(g_gcDacGlobals->generation_table, 4); ` Seems suspicious. Is this the same issue that we saw for the profiler, where g_gcDacGlobals is wrong for regions?

**Comment by cshung** [comment]
I think I have figured out what is going on. In `USE_REGIONS` build, we don't have `allocation_start` for `generation` anymore, and we have a separated linked list of regions for gen1 and gen0 as well.

Here is a work in progress commit (note - to be removed) that fixes the POH enumeration with regions on.
https://github.com/cshung/runtime/commit/8dec23ff083e8eb80cbe4552b6860ea4bc1d2e50?w=1
