### ISSUE TITLE
Test hang: System.Net.Sockets.Tests.CreateSocket.Ctor_SafeHandle_Listening_Success

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56666]
Long-running test detected: System.Net.Sockets.Tests.CreateSocket.Ctor_SafeHandle_Listening_Success

Hangs 7/8-7/31 (incl. PRs)

Day | Run | OS | Runtime
-- | -- | -- | --
7/22  | PR #55577 | Ubuntu.1804.ArmArch.Open | Mono
7/30 | Official run | Alpine.312.Amd64.Open | CoreCLR

**Comment by wfurt** [comment]
Ctor_SafeHandle_Listening_Success should not hang with https://github.com/dotnet/runtime/pull/56717. We can open separate issue if we see test failures.
