### ISSUE TITLE
I Can Not Deserialize Object of IQueryable type

### ISSUE THREAD

**Issue by arminatwork** [dotnet/runtime#56671]
hi there

in my project of asp.net core 3.1 , I using distributed redis cache and i have iqueryable of city.
i want to deserialize this object, but give me error :

![Screenshot 2021-07-31 135440](https://user-images.githubusercontent.com/68272602/127735465-ee0ca5bc-3be8-4cdc-b23e-abcc7236c586.png)

my code is :

` serializedList = Encoding.UTF8.GetString(cache);`
 `list = JsonConvert.DeserializeObject<IQueryable<CityProvince>>(serializedList);`

tank you for watching🙌

**Comment by davidfowl** [comment]
Why not use a `List<CityProvince>`? IQueryable doesn't buy you anything here.

**Comment by arminatwork** [comment]
> Why not use a `List<CityProvince>`? IQueryable doesn't buy you anything here.

Because i dont know my list city is what🤷‍♂️

I want to filtered and etc on query
Impossible?

**Comment by svick** [comment]
@arminatwork If you want to perform filtering on the deserialized collection, that still works with a `List<T>`, since that type implements `IEnumerable<T>`.
