### ISSUE TITLE
The repo license doesn't get recognized by GitHub again

### ISSUE THREAD

**Issue by MichaelAgarkov** [dotnet/runtime#56697]
![image](https://user-images.githubusercontent.com/81249219/127773653-882dffc9-7d07-45f8-9f1d-beddc623d6d1.png)

**Comment by hez2010** [comment]
Need revert https://github.com/dotnet/runtime/pull/37626. But it requires arcade being updated first so that the license can be recognized by build toolchain.

**Comment by krwq** [comment]
changing label since the suggestion is that Arcade should be updated

**Comment by ViktorHofer** [comment]
> The repo license doesn't get recognized by GitHub again

The repo license never got recognizhed by GitHub for dotnet/runtime as the THIRD-PARTY-NOTICES.TXT lists conflicting licenses which confuses GitHub's license detection. There is nothing that we can do that and likely need support from GitHub to exclude files from their license detection logic. More information can be found here: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository.

Closing as not actionable.
