### ISSUE TITLE
Stop Gatekeeping SequencePosition.GetObject()/GetPosition()

### ISSUE THREAD

**Issue by zacharylayne** [dotnet/runtime#56692]
https://github.com/dotnet/runtime/blob/26ddd7a44eef96509596fd60b908f0948732cd79/src/libraries/System.Memory/src/System/SequencePosition.cs#L31

In the halcyon days of 2018 some eons ago when `SequencePosition` went from using [properties to `GetObject()` and `GetPosition()`](https://github.com/dotnet/runtime/commit/acf77b316be8d98c7ac1c9d386bcdbee52e007b8#diff-4ac14efcf7f47a783bd5339786e0bda252a15315d5db3b6ffc4b7fdd38ddcaf3), for whatever reason `[EditorBrowsable(EditorBrowsableState.Never)]` was plopped on.

Now I understand on this and any other matter no amount of hyperbole would be too great in describing the depths of my ignorance. But given that the two methods show up in API reference and their usefulness when implementing exotic new forms of `ReadOnlySequence`, `ReadOnlySequenceSegment`, `SequenceReader`, et. al., shouldn't they be visible in the editor? Or alternatively with `EditorBrowsableState.Advanced`?

**Comment by svick** [comment]
>  But given that the two methods show up in API reference and their usefulness when implementing exotic new forms of `ReadOnlySequence`, `ReadOnlySequenceSegment`, `SequenceReader`, et. al., shouldn't they be visible in the editor?

I believe that is the reason why they are not browsable: the majority of users shouldn't touch these methods, so it's better that they're hidden. For the few people who are implementing their own exotic library types, hiding them shouldn't be a big impediment.

**Comment by adamsitnik** [comment]
> I believe that is the reason why they are not browsable: the majority of users shouldn't touch these methods, so it's better that they're hidden. For the few people who are implementing their own exotic library types, hiding them shouldn't be a big impediment.

@svick is right. We do that on purpose (here and in plenty of other places in dotnet/runtime) and we don't intend to change that unless there is a good reason for more users to discover these APIs.
