### ISSUE TITLE
Strange events from System.Runtime EventCounters under Linux

### ISSUE THREAD

**Issue by neyromant** [dotnet/runtime#56695]
Hi.
After migrating from .net 5 sdk 5.0.101 to net 5 sdk 5.0.302, I noticed strange behavior in System.Runtime EventCounters under Linux. It's about the "cpu-usage" counter. I began to receive two events in the required time interval. Moreover, in the second event, the value is clearly incorrect.

I wrote a small program to demonstrate this behavior:
```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics.Tracing;

namespace EventCountersProblem
{
    class Program
    {
        static void Main(string[] args)
        {
            var eventListener = new CpuTimeEventListener();
            
            Console.WriteLine("Press enter for exit");
            Console.ReadLine();
            GC.KeepAlive(eventListener);
        }
    }

    public class CpuTimeEventListener : EventListener
    {
        private readonly EventLevel _level = EventLevel.Verbose;
        
        protected override void OnEventSourceCreated(EventSource source)
        {
            if (source.Name.Equals("System.Runtime"))
            {
                var refreshInterval = new Dictionary<string, string>();
                refreshInterval.Add("EventCounterIntervalSec", "5");
                EnableEvents(source, _level, (EventKeywords)(-1), refreshInterval);
            }
        }
        protected override void OnEventWritten(EventWrittenEventArgs eventData)
        {
            if (eventData.EventName.Equals("EventCounters"))
            {
                for (int i = 0; i < eventData.Payload.Count; i++)
                {
                    IDictionary<string, object> eventPayload = eventData.Payload[i] as IDictionary<string, object>;

                    if (eventPayload != null)
                    {
                        if (eventPayload["Name"] == "cpu-usage")
                        {
                            Console.WriteLine($"{DateTime.Now}:");
                            foreach (var ep in eventPayload)
                            {
                                Console.WriteLine($"{ep.Key}: {ep.Value}");
                            }

                            Console.WriteLine("=========");
                        }
                    }
                }
            }
        }
    }
}

```
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>

```
This project is published as a self-contained application:
```sh
dotnet publish -f net5.0 -r linux-x64 -c Release
```

Below is the output of the program when working under Windows:
```
Press enter for exit
01.08.2021 15:56:44:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 5,0044165
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
01.08.2021 15:56:49:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 5,00996
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
```
Everything is correct here, one event every 5 seconds with the correct value.

Below is the output of the program when running under Linux Centos (CentOS Linux release 7.4.1708 (Core)):
(When run in wsl2 (ubuntu or centos), the behavior is the same)
```
8/1/2021 3:11:48 PM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 4.9997354
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
8/1/2021 3:11:48 PM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 24
StandardDeviation: 0
Count: 1
Min: 24
Max: 24
IntervalSec: 0.0314531
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
8/1/2021 3:11:53 PM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 4.968951
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
8/1/2021 3:11:53 PM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 35
StandardDeviation: 0
Count: 1
Min: 35
Max: 35
IntervalSec: 0.0021859
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========

```

Here we see that two events are generated in a 5 second interval. In the first event, the correct value. In the second event, the value is incorrect (24% and 35% of cpu-usage).
The second event has a similarly strange meaning in IntervalSec field.

Please tell me what could be the reason for this behavior? Is this a bug? Is this related to #53836?

Thanks in advance for your reply.

p.s.
My dotnet --info output below:
```
Пакет SDK для .NET (отражающий любой global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.6.21352.12
  Commit:  770d630b28

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by josalem** [comment]
> Please tell me what could be the reason for this behavior? Is this a bug? Is this related to #53836?

I think your intuition is probably correct, though I'm not sure why that change would cause that behavior. On a quick glance, the new logic should be doing exactly what the old logic did and can't increment the timestamp by anything other than a multiple of the interval (due to the `Math.Ceil`). I'll see if this repros locally for me and try to debug through it.

**Comment by neyromant** [comment]
@josalem I also tested the work of the application built in SDK 5.0.301. No problems observed.
global.json:
```
{
  "sdk": {
    "version": "5.0.301"
  }
}
```
My test program output:
```
8/3/2021 11:57:15 AM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 5.000747
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
8/3/2021 11:57:20 AM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 4.999878
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
8/3/2021 11:57:25 AM:
Name: cpu-usage
DisplayName: CPU Usage
Mean: 0
StandardDeviation: 0
Count: 1
Min: 0
Max: 0
IntervalSec: 4.9999447
Series: Interval=5000
CounterType: Mean
Metadata:
DisplayUnits: %
=========
```

The problem has been observed since SDK version 5.0.302.
The problem is also present in SDK 6.0.100-preview.6.21355.2.

If necessary, I can provide more technical information about the environment or carry out the necessary checks on other SDKs.

**Comment by josalem** [comment]
I think I've worked out what happened.

The new logic:
```csharp
TimeSpan delta = now - _nextPollingTimeStamp;
if (delta > TimeSpan.Zero && _pollingIntervalInMilliseconds > 0)
	_nextPollingTimeStamp += TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds * Math.Ceiling(delta.TotalMilliseconds / _pollingIntervalInMilliseconds));
```

can have wonky behavior if the sleep in `CounterGroup.PollForValues` wakes up early.

`delta` can be negative, which will result in `_nextPollingTimeStamp` not being updated. This means that `sleepDurationInMilliseconds` will be set to `1` and the counter will fire again on the next loop because `_nextPollingTimeStamp < now + new TimeSpan.FromMilliseconds(1)` will be true.

https://github.com/dotnet/runtime/blob/4d26112c07391f563cb0ca46af1993635399007e/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L267-L306

A fix would be to switch to the following:
```csharp
private const TimeSpan MinimumPollingInterval = TimeSpan.FromSeconds(1);

// ...

TimeSpan delta = now - _nextPollingTimeStamp;
delta = MinimumPollingInterval > delta ? MinimumPollingInterval : delta;
if (_pollingIntervalInMilliseconds > 0)
	_nextPollingTimeStamp += TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds * Math.Ceiling(delta.TotalMilliseconds / _pollingIntervalInMilliseconds));
```

The `now - _nextPollingTimeStamp` is calculating the difference between when the counter woke up (`now`) and when it was _supposed_ to wake up (`_nextPollingTimeStamp`). This is supposed to then increment `_nextPollingTimeStamp` to the next discrete increment of `_pollingIntervalInMillseconds` from the origin time. This prevents the interval from sliding if counters take sufficiently long amounts of time to calculate. This updated logic without the loop, however, only increments if `now > _nextPollingTimeStamp` (if the counter woke up _after_ the intended timestamp).

I need to do some more testing to be sure, but I believe this is the case. If this is true, we'll need to backport the fix to 5.0 and 3.1 since this snippet was backported all the way back.

CC @dotnet/dotnet-diag

**Comment by hoyosjs** [comment]
Reopening for servicing ports.

**Comment by tommcdon** [comment]
@hoyosjs @josalem can this issue be closed or is there a request for a backport?

**Comment by josalem** [comment]
The original issue was for .net5. It has been fixed in .net6 already. We should consider back porting it to .net5 at least.

**Comment by deeprobin** [comment]
This has already been fixed for .NET 6 (as @josalem said). This seems to be a small change [^1]. 
I think the `/backport` command would be very useful here [^2].

If for some reason it doesn't work with this, I can investigate the issue in more detail.

[^1]: [Diff of pull request #57170](https://github.com/dotnet/runtime/pull/57170/files)
[^2]: [backport.yml Workflow](https://github.com/dotnet/runtime/blob/1c7675493dbf05a8ebd7b3e069f07284fd6db640/.github/workflows/backport.yml) - [source](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/eng/actions/backport/index.js)

**Comment by josalem** [comment]
With support for .net5 ending in May, I'm not sure it is worth the effort to backport this change. I can be convinced otherwise, though. For now, I'll close this.
