### ISSUE TITLE
DateTime.ToString formatting inconsistency across platforms

### ISSUE THREAD

**Issue by aha-tech** [dotnet/runtime#567]
Running the following snippet on eithet .NET Core 2.0 or 3.0
```
Console.WriteLine(new DateTime(2019,12,02).ToString("ddd", new CultureInfo("da-DK")));
```
Gives `ma` on Windows and `man` on Mac and Linux.

**Comment by Clockwork-Muse** [comment]
This is likely due [to relying on the OS for the localization](https://github.com/dotnet/corefx/issues/24797).

So, as designed, not a bug.

**Comment by aha-tech** [comment]
Ah, okay didn't know that .Thanks!
