### ISSUE TITLE
ExecutionEngineException using SpanDebugView

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#56703]
While debugging using VS2022 preview 2.1 against an app using 6.0.0-preview.7.21377.19.

I do not see any unsafe code in this app, so it is likely a bug. I'll add more info if I see it again.
```
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at System.Buffer.__Memmove(Byte*, Byte*, UIntPtr)
--------------------------------
   at System.Buffer._Memmove(Byte ByRef, Byte ByRef, UIntPtr)
   at System.ReadOnlySpan`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at System.SpanDebugView`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.ReadOnlySpan`1<Char>)
   at System.String.JoinCore[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.ReadOnlySpan`1<Char>, System.Collections.Generic.IEnumerable`1<System.__Canon>)
```

**Comment by josalem** [comment]
CC @mikem8361 & @hoyosjs

**Comment by am11** [comment]
A similar `SpanDebugView` issue (#13099) was fixed in https://github.com/dotnet/coreclr/pull/26572.

**Comment by danmoseley** [comment]
I hit this twice last night, but couldn't get a reasonable repro. I do still think likely a diagnostics bug as i don't see any unsafe code or pinvokes. 

If I get in a state where this might happen again, is there any diagnostics I can gather, eg., somehow register a jit debugger? Not sure what to attach to that would allow me to get a dump.

**Comment by danmoseley** [comment]
I'll gather more info about the code in question when I hit it again. Not sure where I was debugging.

**Comment by josalem** [comment]
> is there any diagnostics I can gather

I asked my team and they said if you can get a dump at the error it should be pretty easy (famous last words) to spot where the exception is being thrown from.

**Comment by danmoseley** [comment]
Ah right, so attach a second debugger in native mode and wait. I was hoping there might be a COMPLUS flag that somehow popped the debugger prompt at the point of the native exception..

**Comment by hoyosjs** [comment]
If there's an execution engine exception, this is likely in the runtime side and not the debugger side. You can't double attach other than non-invasively in that case - although that's usually useful. What I normally do in those cases is instrument the fatal exception path to block so I can dump the process. 

In debug builds there is a variable `COMPlus_DbgOOBinFEEE` that triggers a debug break, but I have a feeling that if this only repros under the debugger, that will be seen as an unknown debug even and the kernel will proceed to tear down the process due to the unhandled event.

**Comment by danmoseley** [comment]
I see. That's unfortunate. (Why doesn't `COMPlus_DbgOOBinFEEE` work in release? Seems like it could be really useful in some fault in production scenario)

https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/Documentation/project-docs/clr-configuration-knobs.md doesn't mention debug only.

**Comment by am11** [comment]
> https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/Documentation/project-docs/clr-configuration-knobs.md doesn't mention debug only.

https://github.com/dotnet/runtime/issues/41902#issuecomment-687504305 (RETAIL ones work in release build, others don't)

**Comment by danmoseley** [comment]
Ah, I see. Also, I misunderstood what COMPlus_DbgOOBinFEEE would do -- I was wondering if there was something that would break on the exception itself. Possibly COMPlus_DbgNo2ndChance, again debug only.

I'll look out to see if I hit it again.

**Comment by noahfalk** [comment]
If you manage to hit again @danmoseley I'd suggest trying to use windbg to attach to the debuggee non-invasively and capture a dump at that point. Often you can do this as long as you haven't yet dismissed whatever error dialog VS is showing you. If the debuggee is exiting prior to attaching then there may not be anything easy you can do other than trying to observe what the repro conditions are. For this issue I'd guess some of the factors would be what line of code the debugger is stopped at, what is the code of the current function, and which debug windows (Locals, Watch, Autos) are in view. Based on the callstack I'd guess that the debugger is trying to do a function evaluation on some string concatenation expression.

> Why doesn't COMPlus_DbgOOBinFEEE work in release? 

Probably no good reason except that someone was cautious long ago and issues didn't come up often where this switch would have been helpful. I see no issue in making it available on release builds other than its a bit of work to be done.

**Comment by danmoseley** [comment]
Will do.

**Comment by tommcdon** [comment]
@danmoseley I haven't seen other reports of this issue and I am guessing that the debugger issue reported here didn't repro again.  Any objection if we close this issue (or move to future if we feel we don't want to lose track of it)?

**Comment by danmoseley** [comment]
Sounds good to me.

(Should we open an issue suggesting that COMPlus_DbgOOBinFEEE or COMPlus_DbgNo2ndChance or whatever be exposed in release? It sounds like it might make investigating these things easier in future. Totally up to you)
