### ISSUE TITLE
Custom attribute with TypeRef enum constructor parameter breaks debugging on WebAssembly

### ISSUE THREAD

**Issue by addabis** [dotnet/runtime#56722]
### Description

I have a simple Blazor application, which references another project in the same solution. When the referenced project defines a custom attribute with enum constructor parameter type, which is applied on a declaration in the Blazor assembly, it's not possible to set a breakpoint and symbols for the assembly seem not to work.

Repro: https://github.com/addabis/blazor_attribute_enum_debugger_bug

Referenced assembly:
```
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
public class AttributeWithEnum : Attribute
{
    public AttributeWithEnum(TestEnum value)
    {
    }
}

public enum TestEnum
{
    FirstValue = 0,
    OtherValue = 2,
}
```

Blazor project:

```
[AttributeWithEnum(TestEnum.OtherValue)]
public int Counter { get; set; }
```

If I do any of the following, the problem disappears and symbols are properly used:

1) Move the attribute and enum to the Blazor project (so that it's not a TypeRef). Moving just the attribute does not help.
2) Use an attribute with `enum` parameter from runtime assemblies (e.g. `MethodImplAttribute`).
3) Change the attribute parameter type to something else than `enum` (e.g. `int`). It's enough to use another constructor.

### Configuration

Visual Studio 16.10.4, 5.0.8 runtime & WebAssembly packages, seems to happen on older runtimes too.

### Regression?

Likely, I do not remember encountering this after .NET 5.0 was released.

### Other information

In the debugger log the response is:

```
"message": {
    "seq": 6,
    "type": "response",
    "request_seq": 4,
    "command": "setBreakpoints",
    "success": true,
    "body": {
        "breakpoints": [
            {
                "id": 2,
                "verified": false,
                "message": "Unbound breakpoint"
            }
        ]
    }
}
```

**Comment by thaystg** [comment]
This was fixed in this PR:
https://github.com/dotnet/runtime/commit/2f0f2c8455bea23bd9a38522d2c5f4c7f6253c70
And a test case was added, so I think it's working.

**Comment by addabis** [comment]
@thaystg Thanks, it did not occur to me to test it on a preview version. I can confirm this is resolved on the new version of the package.
