### ISSUE TITLE
Varargs not supported on Linux/x64

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#56726]
There are lot of tests that are disabled stating that Unix/x64 do not support varargs. This is a tracking issue so we can have conversation here on why it is not supported and what is needed to support it.

https://github.com/dotnet/runtime/blob/aa4290f3f0aadf86882a439d124db3215851760b/src/tests/issues.targets#L633-L663

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/10478 ?

**Comment by kunalspathak** [comment]
Thanks @jkotas  for pointing out. I will close this one.
