### ISSUE TITLE
Unexpected behavior when setting a property on an object in a foreach loop enumerating a grouped enumerable

### ISSUE THREAD

**Issue by bzd3y** [dotnet/runtime#56738]
I have tried this in .net48 and also net5.0 (VS2019 16.10.3) and see the same unexpected behavior in both. Hopefully this is in the right place, but if not I can move it.

I remember running into this some time ago and not getting too deep into it and I don't remember if I came across an explanation. But I just ran in to it again and after putting more time into it, I haven't been able to come up with an explanation. But if somebody has one here, that would be great. But even with an explanation, it seems like this behavior would be problematic.

In the code below there is a `GroupBy()`, with result selector, called on an `IEnumerable`. In a subsequent `foreach` loop on the resulting IEnumerable, a property on the result objects is set to a non-`null` value. In a second `foreach`, loop when that property is checked it is still `null`, which seems unexpected. I'm aware of `GroupBy` being deferred and greedy, but I can't think of why either would (have to) cause this.

So it seems like the property should either be set or at least an exception thrown (not sure how that would even be possible given this situation).

Forcing execution with `ToList()` immediately after doing the `GroupBy` gives the expected behavior of the property being non-`null` in the second `foreach`. But for some reason forcing execution in either `foreach` statement doesn't give the expected behavior either.

To reproduce just paste the below code in an new console app.

```c#
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
	public class Batch
	{
		public int BatchNumber { get; set; }
		public Message Message { get; set; }
	}

	public class Message
	{
		public string BatchId { get; set; }
	}

	class Program
	{
		static void Main(string[] args)
		{
			List<string> emails = new List<string>();

			for (int i = 0; i < 8; i++)
			{
				emails.Add("a");
				emails.Add("b");
				emails.Add("c");
				emails.Add("d");
			};

			IEnumerable<Batch> batches = emails.GroupBy(x => x, (n, b) => new Batch()
			{
				//Message = new Message() { BatchId = "1" } // assigning Message here produces the expected behavior without having to force execution below
			})/*.ToList()*/; // forcing evaluation here causes the expected behavior

			// create a message for each batch
			foreach (Batch batch in batches/*.ToList()*/) // explicitly forcing evaluation here still causes unexpected behavior
			{
				Console.WriteLine("First, before: {0}", batch.Message == null); // True (expected)
				batch.Message = new Message() { BatchId = "2" };
				Console.WriteLine("First, after: {0}", batch.Message == null); // False (expected)
			}

			foreach (Batch batch in batches/*.ToList()*/) // explicitly forcing evaluation here still causes unexpected behavior
			{
				Console.WriteLine("Second loop: {0}", batch.Message == null); // True (unexpected).
			}
		}
	}
}
```

**Comment by stephentoub** [comment]
Every enumeration of `batches` will re-execute the whole GroupBy.  The objects returned in the first enumeration aren't cached anywhere: when you re-enumerate, you're getting entirely new objects.

**Comment by bzd3y** [comment]
Ah, okay. Thanks! I do remember coming across that the first time now that you explain it. And I probably thought "That makes sense" and moved on. It seems unintuitive, but I guess simple projections with `Select()` would work the same way.
