### ISSUE TITLE
Dictionary<TKey, TValue> permits null keys; documentation states otherwise.

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#56747]
Related issue:  #31401

### IDictionary<TKey, TValue>
The documentation of interface IDictionary<TKey, TValue> contains the following: 
> Implementations can vary in whether they allow key to be null.

in the remarks of these two members:
```
public TValue this[TKey key] { get; set; }
public void Add (TKey key, TValue value);
```

However, in their Exceptions sections, both members also indicate that if the key is null, they will throw an ArgumentNullException.  This bit of the documentation does not indicate that it may vary with implementations.

### Dictionary<TKey, TValue>
In the documentation of the class Dictionary<TKey, TValue>, 
```
public TValue this[TKey key] { get; set; }
public void Add (TKey key, TValue value);
```
The remarks contain the following statement:

> A key cannot be null, but a value can be, if the value type TValue is a reference type.

Additionally, the Dictionary<TKey, TValue> tooltip in Visual Studio for Mac shows a constraint that the Key cannot be null:
![Screen Shot 2021-08-02 at 1 00 55 PM](https://user-images.githubusercontent.com/62225294/127912083-64de3693-e67d-4061-9d1b-a7b3d05cc7ec.png)

While enumerating a Dictionary, I encountered a KeyValue pair with a null key.  I'm not sure how it got in there, but it is there, so the Dictionary<TKey, TValue> is definitely allowing null keys.

### Output of "dotnet --info"

> .NET SDK (reflecting any global.json):
>  Version:   5.0.302
>  Commit:    c005824e35
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/5.0.302/
> 
> Host (useful for support):
>   Version: 5.0.8
>   Commit:  35964c9215
> 
> .NET SDKs installed:
>   3.1.201 [/usr/local/share/dotnet/sdk]
>   3.1.403 [/usr/local/share/dotnet/sdk]
>   3.1.404 [/usr/local/share/dotnet/sdk]
>   3.1.410 [/usr/local/share/dotnet/sdk]
>   3.1.411 [/usr/local/share/dotnet/sdk]
>   5.0.100 [/usr/local/share/dotnet/sdk]
>   5.0.101 [/usr/local/share/dotnet/sdk]
>   5.0.102 [/usr/local/share/dotnet/sdk]
>   5.0.301 [/usr/local/share/dotnet/sdk]
>   5.0.302 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 

### Desired Actions

- [ ] Update the documentation of interface IDictionary<TKey, TValue> regarding throwing ArgumentNullException.  It should note that this may vary between implementations rather than simply state it will be thrown.
- [ ] Determine whether the behaviour of class Dictionary<TKey, TValue> or its documentation is correct, and update accordingly.

**Comment by svick** [comment]
> Update the documentation of interface IDictionary<TKey, TValue> regarding throwing ArgumentNullException.  It should note that this may vary between implementations rather than simply state it will be thrown.

In general, the Exceptions section shows exceptions that *can* be thrown, but that does not mean they *have to* be thrown in those situations. So I think there's nothing to do here.

> Determine whether the behaviour of class Dictionary<TKey, TValue> or its documentation is correct, and update accordingly.

Because of a bug (https://github.com/dotnet/runtime/issues/50865), `AddRange` could be used to add a `null` key to a `Dictionary`. That bug should be fixed in .Net 6, so I think there is nothing else to do about this. (Unless you think the `null` key got into the `Dictionary` using something other than `AddRange`.)

**Comment by mrj001** [comment]
On further investigation, I was unable to find where the null key was added.  

I did find that the code was incorrectly using an enumerator - calling Current before MoveNext.  The results of this are "undefined".

Once I fixed this, the null key went away.  So there is nothing to do.  Closing.
