### ISSUE TITLE
JIT omits copy of aliased struct passed as implicit byref

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#56743]
```csharp
static void Foo(S h)
{
    h.H = &h;
    Bar(h);
}
 
struct S
{
    public long A, B;
    public S* H;
}
 
[MethodImpl(MethodImplOptions.NoInlining)]
static void Bar(S h)
{
}
```

Generates:
```
; Assembly listing for method Program:Foo(S)
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; fully interruptible
; No PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  5, 10   )   byref  ->  rcx         ld-addr-op single-def
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   "OutgoingArgSpace"
;* V02 tmp1         [V02    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.A(offs=0x00) P-DEP "field V00.A (fldOffset=0x0)"
;* V03 tmp2         [V03    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.B(offs=0x08) P-DEP "field V00.B (fldOffset=0x8)"
;* V04 tmp3         [V04    ] (  0,  0   )    long  ->  zero-ref    do-not-enreg[] V05.H(offs=0x10) P-DEP "field V00.H (fldOffset=0x10)"
;* V05 tmp4         [V05    ] (  0,  0   )  struct (24) zero-ref    do-not-enreg[S] "Promoted implicit byref"
;
; Lcl frame size = 0
G_M25920_IG01:              ;; offset=0000H
                                                ;; bbWeight=1    PerfScore 0.00
G_M25920_IG02:              ;; offset=0000H
       48894910             mov      qword ptr [rcx+16], rcx
                                                ;; bbWeight=1    PerfScore 1.00
G_M25920_IG03:              ;; offset=0004H
       E94F3DFFFF           jmp      Program:Bar(S)
                                                ;; bbWeight=1    PerfScore 2.00
; Total bytes of code 9, prolog size 0, PerfScore 3.90, instruction count 2, allocated bytes for code 9 (MethodHash=ccee9abf) for method Program:Foo(S)
```

It does not seem right that `h.H == &h` inside of `Bar`.

cc @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
CC @sandreenko

**Comment by sandreenko** [comment]
> It does not seem right that h.H == &h inside of Bar.

I don't understand the issue, could you please clarify?

**Comment by jakobbotsch** [comment]
> I don't understand the issue, could you please clarify?

I expect `h.H` in `Bar` to point to `h` in `Foo`, but it should not be pointing to `h` in `Bar`.

To make it less controversial I got rid of the unsafe code. I expect the following program to give the same result in debug and release:
```csharp
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

class Program
{
    [MethodImpl(MethodImplOptions.NoOptimization)]
    static int Main()
    {
        return Foo(default, default);
    }

    static int Foo(S s, Span<S> span)
    {
        span = MemoryMarshal.CreateSpan(ref s, 1);
        return Bar(s, span);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Bar(S h, Span<S> s)
    {
        s[0].A = 10;
        return h.A;
    }

    struct S
    {
        public int A, B, C, D;
    }
}
```

Currently it returns 10 in release and 0 in debug. On other platforms where `S` is not passed by implicit by-ref it returns 0.

**Comment by sandreenko** [comment]
I see, thanks Jakob, I will take a look.

**Comment by AndyAyersMS** [comment]
Seems like in `fgCallHasMustCopyByrefParameter` we must also check for the case where `arg2` is a struct that can contain a byref (which may refer to `arg`).

Or for the unsafe case, where `arg2` is a pointer or a struct containing a pointer that may refer to `arg`.

**Comment by jakobbotsch** [comment]
> Or for the unsafe case, where arg2 is a pointer or a struct containing a pointer that may refer to arg.

I still don't think this is enough:
```csharp
using System.Runtime.CompilerServices;

unsafe class Program
{
    [MethodImpl(MethodImplOptions.NoOptimization)]
    static int Main()
    {
        return Foo(default);
    }

    static S* s_s;
    static int Foo(S s)
    {
        s_s = &s;
        return Bar(s);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Bar(S h)
    {
        s_s->A = 10;
        return h.A;
    }

    struct S
    {
        public int A, B, C, D;
    }
}
```

**Comment by sandreenko** [comment]
So `fgCallHasMustCopyByrefParameter` is checking for `interferingArg` but it does not consider static locals, only arguments. Looks like we will have to forbid such optimization.

**Comment by AndyAyersMS** [comment]
Or do some form of more general analysis -- if we see the byref being stored somewhere then we must assume the byref can be aliased.

**Comment by jakobbotsch** [comment]
I think we can allow it if the arg has not been address exposed. Unfortunately for implicit byrefs it seems we only have ld-addr-op which will exclude a lot of cases.

**Comment by AndyAyersMS** [comment]
Also note we track non-call appearances via the weighted early ref count. So presumably if an implicit byref only has call appearances then the current tests suffice...?

In other words, if RCS_EARLY == RCS_EARLY_WEIGHTED we should be ok, even if RCS_EARLY > 1.

**Comment by AndyAyersMS** [comment]
Also we need to be sure that at those sites the implicit byref is passed as an implicit byref and not as a pointer or ref. I think that's already the case, but we'd have to double-check.
