### ISSUE TITLE
[API Proposal]: Add StringSplitOptions.RemoveDuplicates.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#56761]
### Background and motivation

StringSplitOptions is missing an option to remove duplicate strings from the resulting array leaving each string their own unique item when the user does not want duplicate entries of the same string within the resulting array from calls to ``string.Split(...)``.

### API Proposal

```diff
namespace System
{
  [Flags]
  public enum StringSplitOptions
  {
    None = 0,
    RemoveEmptyEntries = 1,
    TrimEntries = 2,
+    RemoveDuplicates = 4,
  }
}
```     

### API Usage

A valid usage of this is when you are making a source generator and you want to filter out the obtained string from an ``AdditionalFile`` that the C# compiler loaded up for you by each line like so:

```cs
var lines = contents?.Split(new []{ "\r\n", "\n", "\r"}, StringSplitOptions.RemoveEmptyEntries);
```

But then you also want ``Split(...)`` to not include duplicate lines from said ``AdditionalFile`` if they contain such but yet ``Split(...)`` does not do such a thing (yet) making you have to try to probe for duplicate entries in the array then remove and resize said array after the fact of it's creation.

After that is done then you can process those lines to generate code for the user and then everything would compile fine on their end.

### Risks

I think the risk for this is minimal and the functionality should be trivial to add (hopefully).

**Comment by wsq003** [comment]
I would like to suggest `RemoveDuplicates = 4`, so it would be possible to activate multiple options like `RemoveEmptyEntries | RemoveDuplicates`

**Comment by WeihanLi** [comment]
`RemoveDuplicates = 4` is more reasonable for a flagged enum

**Comment by AraHaan** [comment]
Edited, thanks.

**Comment by Joe4evr** [comment]
Why not simply pipe the resulting array into a `HashSet<string>`? That way you can also pass in the kind of comparison you want to do (which is *heavily* recommended to do any time string operations are involved).

**Comment by AraHaan** [comment]
But isn't ``HashSet<string>`` slower than using ``Distinct()`` from ``System.Linq;``?

**Comment by svick** [comment]
@AraHaan If it is, then use `Distinct()`. The point is that there is no reason to embed this functionality directly into `string.Split`, when the BCL already lets you easily and efficiently do it today.

**Comment by GrabYourPitchforks** [comment]
Another benefit to piping this to a `HashSet<string>` is that you can specify which comparer you want to use. For example, you can specify whether you want duplicate checking done in a case-sensitive or a case-insensitive fashion.

**Comment by stephentoub** [comment]
I agree with the feedback: if the consumer needs duplicates removed, they should remove the duplicates using `HashSet<T>` or `Distinct()` (which just uses `HashSet<T>` today).  Thanks for the suggestion.
