### ISSUE TITLE
Optimize `CollectionsMarshal.AsSpan` with inlining and bounds check removal

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#56773]
### Description

Currently `CollectionsMarshal.AsSpan` has 2 big codegen issues:
1. It doesn't get inlined despite it being mostly a small forward to the span constructor (with a null check added). Inlining it would eliminate the null check in a lot of cases
2. The JIT doesn't know that _size will never be more than the array length which leads to some really sad codegen due to the safety checks.

Both issues could be easily solved, first one by applying `[MethodImpl(MethodImplOptions.AggressiveInlining)]` on the method and the second one by replacing `new Span<T>(list._items, 0, list._size)` with `MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(list._items), list._size)`.

The result would look like this:
```C#
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static Span<T> AsSpan<T>(List<T> list)
    => list is null ? default : MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(list._items), list._size);
```

Optimizing it would be especially helpful in cases like #54999 where the operation performed on the span is simple and most likely AsSpan takes most of the time there.

### Configuration

SharpLab Core CLR 5.0.721.25508 on amd64, since the code is the same on main the issue is most likely also there.

### Regression?

Afaik AsSpan wasn't changed since its introduction, so no.

### Data

[Sharplab comparing current and proposed implementation](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6zY1kALbFDEAZbMHbc+AjdU0BmbSQGblxsADMYJlIGABVVDBoAbxoGVKYA5iDZMWwuAB5eHgA+BgBBcgAKZ15cDCEOWtEC4oZeAEoGAF4S0txs3Mr2nzSGFLSAbQApXgwAcRguGWUKjABPMRgIMIrCjDa2gF0x1OIM8iyc/JievsvyPOuqmrqGjCbrhklntuORv+7Ps9WrgGFwOJJJAwAPwMAAmMDC2HBGAYIFBMAA7gx+lcihUvrUWAB9GYwfC4NAMOiUgkYYm4XgALxgbWGaV+p0C2MuzQwPVIT1q9Ua+F5JXaXRuOIFQ1+vymM3miygyzWGy2Ox4+yO1BG4wAsjAMHYILCDOJJBVDcbTeaxJIAPJiPgQLi4FilADmntguAZChgRi+XEKnsOHLOF1yDyll1IMcFLxFMcBtR+ur+mYBtOBoPBkJh8MRyNRDEN+Ggq31jlwDkkwlg2AwMBxFVgYTLZMr1agtew9fmGFKUCg2FWABEm9g2AiZAsVPjnsTSeS2jSl0SGczWTQAL40fxRBjVIWvd5FJK/XYyLj92LjA4MEnN8ls1LXqC3yG7J9bmBvhgxBVBQm0iH8iQDXteFdHxdyAA==)

**Comment by MihaZupan** [comment]
> MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(list._items), list._size)

This could create a Span longer than the array if the list was modified from a different thread.

Afaik the concerns around the method were that the array could change under you, but this would bring in more unsafety. Maybe that's fine given it's under `CollectionsMarshal`, but just pointing it out.

**Comment by adamsitnik** [comment]
> This could create a Span longer than the array if the list was modified from a different thread.

How would the current implementation prevent from that? `List<T>` is not thread-safe, so we should rather not be worried about that.

@GrabYourPitchforks do you have any objections for using `MemoryMarshal.GetArrayDataReference` as proposed?

**Comment by MihaZupan** [comment]
The `new Span<T>(list._items, 0, list._size)` span ctor will check the array length and throw if `list._size` is bigger than the array length.

With `MemoryMarshal.CreateSpan`, there is no such check.
Thread A calls into `AsSpan()`, reading the array from `list._items`.
Thread B modifies the list (adds elements / resizes to capacity).
Thread A reads the `list._size` and creates the span.

The returned span could now be longer than the array it is wrapping, pointing into arbitrary memory.

> List<T> is not thread-safe, so we should rather not be worried about that.

If you violated the thread safety before, you could get an exception. Now you could be corrupting memory.

**Comment by adamsitnik** [comment]
@MihaZupan thanks!

In such a case, we should not change it.

**Comment by GrabYourPitchforks** [comment]
> If you violated the thread safety before, you could get an exception. Now you could be corrupting memory.

This is correct. In general, we want to avoid optimizations that convert "I corrupted the state of a single instance" into "I corrupted the state of the entire application."

We've rejected such changes before. See https://github.com/dotnet/runtime/pull/47186 and https://github.com/dotnet/corefx/pull/39173#issuecomment-508589163 (https://github.com/dotnet/runtime/issues/30141).

I feel we shouldn't take this change.

**Comment by MichalPetryka** [comment]
What about the AggressiveInlining?

**Comment by MihaZupan** [comment]
I suppose it could instead be written with an extra `Math.Min` to avoid that:
```c#
T[] array = list._items;
return MemoryMarshal.CreateSpan(ref MemoryMarshal.GetArrayDataReference(array), Math.Min(array.Length, list._size));
```

Adds a few bytes but avoids corruption. This would also avoid the exception race.

**Comment by GrabYourPitchforks** [comment]
> Adds a few bytes but avoids corruption.

This is also an invalid optimization, especially if the `List<T>` has been generated via a deserializer. (The `T[]` might actually be of type `U[]`, and the safety checks are necessary.)

The point of the `CollectionMarshal` APIs is that they perform checks upfront so that you can get the returned span once, then perform bulk operations on it. It's not intended that you call these APIs in a loop, etc. Given this, I'm not inclined to take any part of this change, including the AggressiveInlining changes.

**Comment by adamsitnik** [comment]
@MichalPetryka thank you for your proposal and for creating an issue before sending a PR (this is very rare here ;) )

Since one of the proposed changes is not safe and another should not be an issue as this method should never be on a hot path, I am closing the issue.
