### ISSUE TITLE
[net6.0][BlazorWasmSdk] build does not link native files

### ISSUE THREAD

**Issue by emepetres** [dotnet/runtime#56783]
Blazor WASM SDK only links native libraries on `dotnet publish`, so it is not possible to debug the solution while using native linking. The reason is that emscripten targets seems to be only executed on publish.

I've been playing with `WasmBuildAppAfterThisTarget` property but no luck.

How could I link native files on dotnet build?

Sample csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-rc.1.21376.14" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0-rc.1.21376.14" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <UsingBrowserRuntimeWorkload>true</UsingBrowserRuntimeWorkload>
    <!-- <WasmBuildAppAfterThisTarget>Build</WasmBuildAppAfterThisTarget> -->
    <WasmBuildNative>true</WasmBuildNative>
  </PropertyGroup>

  <ItemGroup>
    <NativeFileReference Include="libTest.o" ScanForPInvokes="true" />
  </ItemGroup>

</Project> 
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. I believe this is being fixed already. @lewing do you have an existing issue tracking the resolution?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. I believe this is being fixed already. @lewing do you have an existing issue tracking the resolution?

**Comment by radical** [comment]
Changes have merged, but waiting to test that with VS before closing this.

**Comment by emepetres** [comment]
@radical did you test it linking a native library? Usint latest VS2022, and a vanilla client blazor app linking a native library, I'm getting the following error:

![imagen](https://user-images.githubusercontent.com/1446793/134156279-5a136cf4-af66-4ee4-af4e-865f0c4a17c7.png)

**Comment by radical** [comment]
> @radical did you test it linking a native library? Usint latest VS2022, and a vanilla client blazor app linking a native library, I'm getting the following error:
> 
> ![imagen](https://user-images.githubusercontent.com/1446793/134156279-5a136cf4-af66-4ee4-af4e-865f0c4a17c7.png)

The latest bits with these changes are not in the VS preview yet. You need to install the latest rc2 sdk from https://github.com/dotnet/installer . And then install the `Wasm-tools` workload.
