### ISSUE TITLE
What should the default DistributedContextPropagator be

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56794]
#50658 and #55556 added APIs for controlling distributed context propagation.
Part of those APIs is a [`CreateDefaultPropagator`](https://github.com/dotnet/runtime/blob/71f9191846292b61a93de54a18bdcac389d90988/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DistributedContextPropagator.cs#L94) method that is used to seed the global static `Current` property.

HttpClient and ASP.NET Core both consume these APIs and as such inherit the default behavior.

`CreateDefaultPropagator` currently returns a `LegacyPropagator`, which is preserving pre-.NET 6 behavior of injecting context by default.

Having injection ON by default means some user scenarios work out of the box:
- ASP.NET Core services will preserve the trace across process boundaries even if they haven't been explicitly instrumented for distributed tracing
- For services that collect logs, actions performed across different services can still be attributed to a shared incoming request
- Even when some of the services are not instrumented, others still benefit from the trace as it continues to flow

On the other hand it brings some downsides:
- Some services are very strict about the headers they are expecting and may refuse requests that contain trace-related headers. This may be relatively difficult for users to diagnose as the behavior of HttpClient depends on whether it was used from within the ASP.NET Core pipeline or not
- We are spending a few cycles every request to decide on whether to do anything, or potentially sending extra headers that may just get ignored
- There are theoretical privacy concerns of correlating requests based on the trace id, outlined in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#privacy-of-traceparent-field)
- More discussion around the behavior: #35337

**For 7.0, we should decide whether injecting context is the right default for the platform.**

cc: @tarekgh @noahfalk @shirhatti @davidfowl @dotnet/ncl

**Comment by tommcdon** [comment]
Moving older issues to the Future milestone as it is unlikely we will have time to address this in the .NET 7 timeframe.  Please feel free to move this issue back to .NET 7 if there is active work to address the feature request.

**Comment by MihaZupan** [comment]
Given we're not changing anything here for 7 and there appears to be no interest in doing so in the future, I'm fine with just closing this.
Feel free to reopen if you disagree.
