### ISSUE TITLE
Understanding the behavior of JIT compiling generics

### ISSUE THREAD

**Issue by L2** [dotnet/runtime#56807]
For example, when running the following IndexerSet benchmark: https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Indexer/IndexerSet.cs

with the following command:
`dotnet run -c Release -f net6.0 --filter "System.Collections.IndexerSet<String>.Span*"`

For which I've specified the type argument as `string` and for it to run only the `Span` benchmark:

```
public T Span()
{
    T result = default;
    var collection = new Span<T>(_array);
    for (int i = 0; i < collection.Length; i++)
        collection[i] = default;
    return result;
}
```

This method produces the following assembly (win-x64):

<details><summary>Span() benchmark with generics</summary>

```
System.Collections.IndexerSet`1[[System.__Canon, System.Private.CoreLib]].Span()
push    rdi
push    rsi
sub     rsp,38h
xor     eax,eax
mov     qword ptr [rsp+20h],rax
mov     qword ptr [rsp+28h],rax
mov     qword ptr [rsp+30h],rcx
mov     rsi,rcx
mov     rdi,qword ptr [rsi+10h]
mov     rcx,qword ptr [rsi]
mov     rdx,qword ptr [rcx+30h]
mov     rdx,qword ptr [rdx]
mov     rdx,qword ptr [rdx+18h]
test    rdx,rdx
je      00007ffd`174c6bf3
jmp     00007ffd`174c6c05
mov rdx,7FFD175A93A0h
call    coreclr!JIT_GenericHandleClass (00007ffd`76d97e70)
mov     rdx,rax
lea     rcx,[rsp+20h]
mov     r8,rdi
call    00007ffd`1724ae60 (System.Span`1[[System.__Canon, System.Private.CoreLib]]..ctor(System.__Canon[]), mdToken: 0000000006001787)
xor     eax,eax
jmp     00007ffd`174c6c27
mov     rdx,qword ptr [rsp+20h]
movsxd  rcx,eax
xor     r8d,r8d
mov     qword ptr [rdx+rcx*8],r8
inc     eax
cmp     eax,dword ptr [rsp+28h]
jl      00007ffd`174c6c16
xor     eax,eax
add     rsp,38h
pop     rsi
pop     rdi
ret
```
</details>

<details><summary> where that last call to `ctor` gives this assembly:</summary>

```
System.Span`1[[System.__Canon, System.Private.CoreLib]]..ctor(System.__Canon[])
push    rdi
push    rsi
push    rbp
push    rbx
sub     rsp,28h
mov     qword ptr [rsp+20h],rdx
mov     rbx,rcx
mov     rdi,rdx
mov     rsi,r8
test    rsi,rsi
je      00007ffd`174ca3ed
mov     rcx,rsi
call    coreclr!ObjectNative::GetClass (00007ffd`76d895a0)
mov     rbp,rax
mov     rcx,qword ptr [rdi+30h]
mov     rcx,qword ptr [rcx]
mov     rcx,qword ptr [rcx+18h]
test    rcx,rcx
je      00007ffd`174ca3b8
jmp     00007ffd`174ca3cd
mov     rcx,rdi
mov rdx,7FFD175AB530h
call    coreclr!JIT_GenericHandleClass (00007ffd`76d97e70)
mov     rcx,rax
call    coreclr!JIT_GetRuntimeType (00007ffd`76c861b0)
cmp     rax,rbp
jne     00007ffd`174ca3ff
lea     rax,[rsi+10h]
mov     qword ptr [rbx],rax
mov     eax,dword ptr [rsi+8]
mov     dword ptr [rbx+8],eax
add     rsp,28h
pop     rbx
pop     rbp
pop     rsi
pop     rdi
ret
xor     eax,eax
mov     qword ptr [rbx],rax
mov     qword ptr [rbx+8],rax
add     rsp,28h
pop     rbx
pop     rbp
pop     rsi
pop     rdi
ret
call    00007ffd`1723a978 (System.ThrowHelper.ThrowArrayTypeMismatchException(), mdToken: 0000000006001C82)
int     3
```
</details>

However, if you remove the generics from this benchmark and just use string as the specified type, for which the Span function ends up looking like this:

```
public string Span()
{
    string result = default;
    var collection = new Span<string>(_array);
    for (int i = 0; i < collection.Length; i++)
        collection[i] = default;
    return result;
}
```

It generates the following assembly:

<details><summary>Span() benchmark without generics</summary>

```
System.Collections.IndexerSet.Span()
mov     rax,qword ptr [rcx+8]
test    rax,rax
jne     00007ffd`109d656f
xor     edx,edx
xor     ecx,ecx
jmp     00007ffd`109d6576
lea     rdx,[rax+10h]
mov     ecx,dword ptr [rax+8]
xor     eax,eax
test    ecx,ecx
jle     00007ffd`109d6590
nop     dword ptr [rax]
movsxd  r8,eax
xor     r9d,r9d
mov     qword ptr [rdx+r8*8],r9
inc     eax
cmp     eax,ecx
jl      00007ffd`109d6580
xor     eax,eax
ret
```
</details>

If at runtime the JIT knows that the specified type to the generic Span() is `string`, why doesn't a non-generic version of the assembly (specifically for `string`) get produced so that anytime we use `string` we can use this version instead?

This document on C# generics says:
https://docs.microsoft.com/en-us/previous-versions/ms379564(v=vs.80)?redirectedfrom=MSDN

> Generics Benefits
Generics in .NET let you reuse code and the effort you put into implementing it. The types and internal data can change **without causing code bloat**, regardless of whether you are using value or reference types

Is code bloat the main reason it's not done? So that different assemblies aren't produced for many specified types leading to higher memory usage?

Thanks!

**Comment by jakobbotsch** [comment]
Indeed, code bloat (at runtime) is the main reason. For reference types different generic instantiations will very often look close to identical, so only a single version is generated. There's some developer documentation [here](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/shared-generics.md).
