### ISSUE TITLE
`Microsoft.Extensions.FileProviders.Physical.Tests` test fails with `System.UnauthorizedAccessException`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56810]
Test failed on `runtime (Libraries Test Run release coreclr windows x64 Debug)`, for https://github.com/dotnet/runtime/pull/56769

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1273892&view=logs&jobId=55b384d0-d6b0-5894-fd8a-d754d713246e&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56769-merge-da619550a2714ba9ab/Microsoft.Extensions.FileProviders.Physical.Tests/1/console.1709f040.log?sv=2019-07-07&se=2021-08-23T20%3A28%3A44Z&sr=c&sp=rl&sig=aTL7QI4H7SL%2B0oxnRoXkI3lVADQHPA9Ne5t8xTe9DkY%3D)

```
Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: False, linkWasBroken: False) [FAIL]
      System.UnauthorizedAccessException : Access to the path 'C:\h\w\ABC3094B\t\y5tfj3va.j2q\y4b1rsjy.300' is denied.
      Stack Trace:
        /_/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs(60,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs(423,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs(1026,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.netcoreapp.cs(104,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(Boolean useWildcard, Boolean linkWasBroken)
        --- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment]
cc @Jozkee

**Comment by Jozkee** [comment]
FWIW: I think the scenario here is: re-create a symlink with a different target i.e: delete it, then create it back.
But this error seems to be very unusual, it has been hit just once in the whole time the test has existed. Plus I tried to locally repro by doing the above mentioned 100k times in a loop and never got the error. 

I will keep it in 7.0.0 since it may not be possible to fix it in 6.0.0.

cc @carlossanlop

**Comment by danmoseley** [comment]
@jozkee I don't think we should leave tests with known failure modes if possible. The failures add up. Can we either temporarily catch this exception, tracking with this issue, or disable the test, again tracking with this issue? The former seems better. LMK if you would like me to push that up.

**Comment by Jozkee** [comment]
@danmoseley, I just sent https://github.com/dotnet/runtime/pull/57299 for disabling the test
