### ISSUE TITLE
Remove type forward suppressions in the package validation suppression files when the tooling understands those

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#56823]
At the time of writing PackageValidation doesn't understand type forwards and flags those as errors. During the conversion from pkgproj to the NuGet Pack task these errors had to be suppressed. When the PackageValidation tooling is more mature and doesn't flag type errors as errors anymore, the suppressions should be removed.

1. Search for `CP0001` in **/CompatibilitySuppressions.xml files
2. Remove the obvious type forwards
3. Make sure that package validation which runs after Pack doesn't raise errors anymore

cc @safern @Anipik @ericstj

**Comment by ericstj** [comment]
Should be fixed once we have an SDK/PackageValidation package with https://github.com/dotnet/sdk/issues/18676.  When ingesting that we can rebaseline all projects and ensure that all CP001 are gone.

**Comment by ViktorHofer** [comment]
I think this was already by @joperezr?

**Comment by joperezr** [comment]
yup, looks like I forgot to close this one, but yeah I took care of this a while back.
