### ISSUE TITLE
The ChannelReader.ReadAllAsync(CancellationToken) method does not react promptly to cancellation

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#56820]
Hi! I am propagating an issue that appeared 2 months ago on StackOverflow, regarding the behavior of the [`ChannelReader<T>.ReadAllAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.readallasync) method when supplied with a `CancellationToken` argument. The expectation is that a cancellation signal would be propagated instantly to a consumer who enumerates the resulting `IAsyncEnumerable<T>`, but this is not what always happens. Depending on the timing of the cancellation, the consumer may get notified only at the end of the `await foreach` loop, potentially a long time after the actual cancellation occurred.

The StackOverflow question: [ChannelReader.ReadAllAsync(CancellationToken) not actually cancelled mid-iteration](https://stackoverflow.com/questions/67569758/channelreader-readallasynccancellationtoken-not-actually-cancelled-mid-iterati)

Demo app that reproduces the issue: [link to dotnetfiddle](https://dotnetfiddle.net/CXKj20)

I would like to ask if this behavior is by design.

**Comment by adamsitnik** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
> I would like to ask if this behavior is by design.

It is.  There's already data available for reading immediately, so there's effectively nothing to cancel.  The implementation of the iterator is just sitting in this tight loop:
https://github.com/dotnet/runtime/blob/95147163dac477da5177f5c5402ae9b93feb5c89/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelReader.netstandard21.cs#L22-L25
as long as data is available immediately.  As soon as there isn't, it'll escape out to the outer loop, which will check for cancellation.

That said, it could be changed.  I don't have a strong opinion on whether preferring cancellation is preferable; I expect it would depend on the use case.

**Comment by theodorzoulias** [comment]
Thanks @stephentoub for the clarification! The current behavior is OK for me, since I consider the channels a performance-critical mechanism, and doing a `token.ThrowIfCancellationRequested();` after every `yield` could potentially affect the performance, while being redundant in many cases. I'll post your response to the [StackOverflow question](https://stackoverflow.com/questions/67569758/channelreader-readallasynccancellationtoken-not-actually-cancelled-mid-iterati) as an answer.

Maybe adding a brief clarification in [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.readallasync) would be a good idea, as some StackOverflow users have suggested. 😃

**Comment by theodorzoulias** [comment]
Related: [ChannelReader<T>.ReadAllAsync(CancellationToken) - important cancellation details missing in docs](https://github.com/dotnet/dotnet-api-docs/issues/6751)
