### ISSUE TITLE
RijndaelManaged Decryption behaves different in .NET 6

### ISSUE THREAD

**Issue by Kokujou** [dotnet/runtime#56834]
First: This Problem is breaking our whole backend because we're using an encryption using a crypto key for our encryption.
i sadly don't have much insight about why/how/what this actualy is, but i will try my best to describe the Problem.

```c#
if (string.IsNullOrEmpty(cryptoKey)) cryptoKey = DefaultCryptoKey;

if (string.IsNullOrEmpty(inputText))
    return inputText;

var rijndaelCipher = new RijndaelManaged();
var encryptedData = Convert.FromBase64String(inputText);
var salt = Encoding.ASCII.GetBytes(cryptoKey.Length.ToString());
var secretKey = new PasswordDeriveBytes(cryptoKey, salt);
var decryptor =
    rijndaelCipher.CreateDecryptor(secretKey.GetBytes(32), secretKey.GetBytes(16));
var memoryStream = new MemoryStream(encryptedData);
var cryptoStream = new CryptoStream(memoryStream, decryptor, CryptoStreamMode.Read);
var plainText = new byte[encryptedData.Length];
var decryptedCount = cryptoStream.Read(plainText, 0, plainText.Length);

memoryStream.Close();
cryptoStream.Close();
var decryptedData = Encoding.Unicode.GetString(plainText, 0, decryptedCount);

return decryptedData;
```

this is the code which was just working fine even after migrating from .NET Framework 4.7.2 to .NET 5, but now in .NET 6 for some reason it omits 5 characters at the end of my example String

let me share this example data with you:
decrypted vaue:
aGNZR+BUSHwKA4W+VFQOcEZ1ek9Ou+vb6/8CVY64ezCyD9HJbMGd4dDJnkKoGkHB
.NET 5 and below: 
QktDaxRgA6j0uwVhfzM!e
QktDaxRgA6j0uwVh

at least i aready compared the resut of the base64 encryption in both services byte-by-byte and can say that there is no difference, so i'm pretty sure it has something to do with the actual decryption.

System Info: 
Dotnet Version: dotnet-sdk-6.0.100-preview.6.21355.2-win-x64
Visual Studio: 2019 16.11 preview 2

Additional Steps:
I already tried to resolve al those obsolete marks in the code - also with no success
i tried to implement our old DLL with .NET Framework 4.7.2 in the project as a DLL dependency - same result.

i hope someone can help me. we can't change this way of decrypting, we need to have exact the same data here. our project is realy big and if i started now to change this decryption in so many places i would probably be decapitated by my fellow programmers. we have the chance to slowly migrate parts of our application to the newes .NET version, but it still needs to  be connected to the old code so we can work in iterations.

**Comment by vcsjones** [comment]
This is likely the same issue as https://github.com/dotnet/runtime/issues/55527. The `CryptoStream`'s `Read` is assuming the entire buffer will be filled in a single call instead of looping until there is no longer any data left.

**Comment by stephentoub** [comment]
Closing as a dup.  Stream.Read has never guaranteed that it would read as much data as was requested, so this line is broken:
```C#
var decryptedCount = cryptoStream.Read(plainText, 0, plainText.Length);
```
It so happened that the previous CryptoStream implementation did so aggressively, but that was flawed for a variety of reasons.  The change is documented here:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by Kokujou** [comment]
thank you! it i found a solution based on that response. 
the provided code exampe was not really working because there is no .Slice method on byte[] (probably the buffer was a ReadOnlySpan) and .Take was not acting well, too.

but i found after that a solution where someone was using cryptoStream.copyTo(memoryStream) and memoryStream.ToArray()
which is then restoring the functionality again :)

Thank you so much for your kind help!

**Comment by vcsjones** [comment]
@Kokujou Glad you were able to get it working. When .NET 6 Preview 7 is released, you can avoid `CryptoStream` entirely and write:

```csharp
using var aes = Aes.Create();
var encryptedData = Convert.FromBase64String(inputText);
var salt = Encoding.ASCII.GetBytes(cryptoKey.Length.ToString());
using var secretKey = new PasswordDeriveBytes(cryptoKey, salt);
aes.Key = secretKey.GetBytes(32);
var plainText = aes.DecryptCbc(encryptedData, secretKey.GetBytes(16));
var decryptedData = Encoding.Unicode.GetString(plainText, 0, plainText.Length);
```

**Comment by Kokujou** [comment]
that's even better :) i would also use the replacemanet for DerivedBytes but our salt has just 2 bytes and the recommended replacement class needs at least 8.
