### ISSUE TITLE
[wasm][eat] `System.Net.Primitives.Functional.Tests.LoggingTests` test failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#56847]
[System.Net.Primitives.Functional.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-52004-merge-7a4dd01ba7eb45b883/System.Net.Primitives.Functional.Tests/1/console.77807b73.log?sv=2019-07-07&se=2021-08-24T06%3A48%3A53Z&sr=c&sp=rl&sig=IhTugai%2BC8NrqjQD9I2jBBfVtHJGbKMeEI0anAMGtes%3D)
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1275375&view=logs&jobId=fddee5b2-3265-5a91-40c1-750d81e69f3f&j=fddee5b2-3265-5a91-40c1-750d81e69f3f&t=b539fe9c-4231-5c9f-4235-451fd41db683)

```
[07:27:21] fail: [FAIL] System.Net.Primitives.Functional.Tests.LoggingTest.EventSource_ExistsWithCorrectId
[07:27:21] info: Assert.Equal() Failure
[07:27:21] info:           â†“ (pos 0)
[07:27:21] info: Expected: Private.InternalDiagnostics.System.Net.PrÂ·Â·Â·
[07:27:21] info: Actual:   NetEventSource
[07:27:21] info:           â†‘ (pos 0)
[07:27:21] info:    at System.Net.Primitives.Functional.Tests.LoggingTest.EventSource_ExistsWithCorrectId()
[07:27:21] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
```

Tests built with `/p:EnableAggressiveTrimming=true`

**Comment by lewing** [comment]
This looks suspiciously like corrupted memory, we should investigate further.

cc @lateralusX

**Comment by radekdoulik** [comment]
The tests does use reflection to check whether an event source type exists.

https://github.com/dotnet/runtime/blob/913fdbe2f42e28210e302616b030284eba64b3cc/src/libraries/System.Net.Primitives/tests/FunctionalTests/LoggingTest.cs#L14-L25

I am not sure whether the test is intended to "survive" linking. @stephentoub, should the test work even when linked with illink?

**Comment by stephentoub** [comment]
> should the test work even when linked with illink?

What linker-related switches are being set?  This test would depend on EventSources being properly kept.  If, for example, System.Diagnostics.Tracing.EventSource.IsSupported is being set to false, I expect this test would not work.

**Comment by radekdoulik** [comment]
It is set to false, indeed. I see it in the binlog when `illink` is run with:
```
--feature System.Diagnostics.Tracing.EventSource.IsSupported false
```

**Comment by radekdoulik** [comment]
@radical do we run the test without trimming too? If so then we might disable it conditionally by this feature switch?

**Comment by radekdoulik** [comment]
Or we can probably just set the feature switch in the test project, I will open PR for that.

**Comment by lateralusX** [comment]
> This looks suspiciously like corrupted memory, we should investigate further.
> 
> cc @lateralusX

Any test that intends to test anything with EventSource support needs to set the EventSource feature flag or needed things will be trimmed away causing test failures. We had similar issues with at least https://github.com/dotnet/runtime/issues/52652 on Android as well.
