### ISSUE TITLE
macOS dotnet 3.1/5 debug alternatively working, run without debug works always

### ISSUE THREAD

**Issue by DaviehS** [dotnet/runtime#56850]
### Description
I started working with a macbook, installed latest Rider and mac VS, and also Rider EAP
When I try debuging it gets "stuck" running the service on some assembly, whereas when I click run it always works and launches the service 

I'm experiencing the same issue with Rider, Rider EAP, mac VS

In the debug window it shows bunch of :
`
Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Net.Security.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Net.Security.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Net.Security.dll was not found or failed to read
`
difference is that when I click Run wihoutt debug it always works, and passes all these Assemblies and launches the service (swagger in my case), but in debug, it sometimes works, and sometimes jsut hangs on one of the Assemblies and nothing happens.

recently it gets to 
`Loaded Assembly '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/Microsoft.CSharp.dll'
Loading module /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/Microsoft.CSharp.dll in application domain 1:clrhost
Pdb file for assembly /usr/local/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/Microsoft.CSharp.dll was not found or failed to read`

and get's stuck there ^ 

### Configuration
dotnet 3.1/5
macbook pro 15 2018 indel 6-core I7 big sur 11.4

### Other information

What helps make debug work, is try Run normally without debug once or twice, and then try debug again, and sometimes it helps.

**Comment by tommcdon** [comment]
Closing this issue as we do not have a concrete repro to diagnose the issue.  Please feel free to open a new issue or comment on this if there are repro steps.
