### ISSUE TITLE
[API Proposal]: Obsolete System.Security.SecurityContext

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#56868]
### Background and motivation

Splitting off this from https://github.com/dotnet/runtime/issues/50528 to obsolete `System.Security.SecurityContext`.

This API is a remnant of CAS which has largely already been deprecated. All public members of this type throw a `PlatformNotSupportedException`.

### API Proposal

Obsolete this type under the same diagnostic as we have used for the other CAS related obsoletions. 

```C#
namespace System.Security
{
#if NET7_0_OR_GREATER
    [Obsolete(Obsoletions.CodeAccessSecurityMessage, DiagnosticId = Obsoletions.CodeAccessSecurityDiagId, UrlFormat = Obsoletions.SharedUrlFormat)]
#endif
    public sealed partial class SecurityContext {}
}
```     

### API Usage

No expected usages of this API.

**Comment by bartonjs** [comment]
@jeffhandley Are we in "please, don't" or "please, do" for this kind of thing for 6.0?  (The class is PNSE for all members except the ctor, I don't expect any review pushback)  Just trying to remember the boundary conditions :smile:.

**Comment by vcsjones** [comment]
I opened this before @jeffhandley said we can probably skip API reviews for this, so, I'll close it. If I'm wrong, we can re-open it. https://github.com/dotnet/runtime/issues/50528#issuecomment-893981312

**Comment by jeffhandley** [comment]
I'm comfortable taking this kind of an obsoletion at this stage. We've been pushing some other obsoletions through for RC1 as well, where we know the breaking impact is very low.
