### ISSUE TITLE
Http/3 adds alt-used header even when alt-svc isn't is used

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#56876]
https://github.com/dotnet/runtime/blob/0c200955af77bf17cd05488db96d3cdb3716a16c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L528-L529

This code makes the incorrect assumption that Alt-Svc is required, and therefore Alt-Used should always be added. Alt-Svc isn't required when using `HttpVersion.Version30` and `HttpVersionPolicy.RequestVersionExact` and Alt-Used should not be added in this situation.

```c#
            using var client = new HttpClient(handler);
            client.DefaultRequestVersion = HttpVersion.Version30;
            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
            var response = await client.GetStringAsync(address);
```

Impact: Unknown
Priority: Low

**Comment by geoffkizer** [comment]
Yeah, good issue.

We need to remember whether we saw an Alt-Svc that told us where/how to do H3, and only send the header if we have.
