### ISSUE TITLE
Mono does not support querying for and open generic type when searching for Attributes

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#56887]
### Description

While fixing issue #56492 in coreclr, I discovered that the generic attribute test was not running on any platform. When I enabled it, not only did mono have issue #56492, it also didn't appear to support generic attribute at all. This may be a blocker for dotnet/roslyn#55190. As part of the fix for the coreclr bug, in PR #56879 I will be fixing the build of the generic attribute test, but disabling it on mono platforms.

@RikkiGibson, please comment on this issue and its importance.
@alekseyTs, fyi, please make sure the right person in mono is aware of this.

**Comment by SamMonoRT** [comment]
@lambdageek @vargaz fyi

**Comment by vargaz** [comment]
The test fails at this line:
        Assert(CustomAttributeExtensions.GetCustomAttributes(programTypeInfo, typeof(MultiAttribute<>), false) == null);

because it calls Array.CreateInstance () with the open generic type.
Looking at the custom attribute code, I don't see the place where it checks for generic type definitions and returns null.

**Comment by RikkiGibson** [comment]
I am looking into whether the compiler team considers it a ship blocker for the feature. cc @jaredpar @jcouv

**Comment by davidwrighton** [comment]
Ah, if its just the issue around the open type... see `internal static object[] GetCustomAttributes(RuntimeType type, RuntimeType caType, bool inherit)` in `src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeCustomAttributeData.cs`. there is a check `bool useObjectArray = (caType.IsValueType || caType.ContainsGenericParameters);` and `typeof(MultiAttribute<>)` ContainsGenericParemters I believe. So in that case instead of creating an array of type `MultiAttribute<>` the array is of type `object`.

**Comment by davidwrighton** [comment]
I do agree though, where is the null coming from? That just seems odd. I'll take a look at the coreclr behavior, and try and figure out what is supposed to trigger that to happen..

**Comment by davidwrighton** [comment]
Ah. The null comes from https://github.com/dotnet/runtime/blob/1fb151f63dca644347a5c608d7ab17f7cb8e1ccb/src/coreclr/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L468 The internal custom attribute functions return object[] and then that line converts the `object[]` into an `Attribute[]` or null. I can't explain why anyone would write the code this way, but that's where the null comes from.

**Comment by RikkiGibson** [comment]
Speculatively I think the compiler sees a few options from our POV:

1. We are able to get generic attributes support in Mono in the .NET 6 timeframe and the compiler ships "generic attributes" in C# 10. This is the happy path.
2. Mono won't be able to support generic attributes in .NET 6, and the compiler ships "generic attributes" under a preview flag with the caveat that it may not currently work depending on the target runtime.
3. (not sure if this would work) We introduce a [`RuntimeFeature`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimefeature?view=net-5.0) for "generic attributes" and make the compiler detect its presence during compilation, ensuring that compilation fails against platforms which don't fully support the feature.

Feel free to correct me here @jcouv @jaredpar if these options don't seem right.

**Comment by davidwrighton** [comment]
@RikkiGibson I've spent a bit of time looking into the issue (and figuring out how to run the tests under Mono), and I can say that while the Generic Attributes test as written fails, it ONLY fails for the case of attempting to look up an attribute of an open type. As that particular query could exist outside of any actual usage of generic attributes I believe it is irrelevant to general generic attribute support.

As such, I think that there is no risk to the C# feature at this time even if this particular issue isn't fixed in Mono, and that I'd like @vargaz/@lambdageek to determine what priority/approach they wish to take on fixing the remaining issue identified via this test.

**Comment by vargaz** [comment]
Is the GetCustomAttribute () call supposed to return null for an open type ? According to the docs, it should return a (possible empty) array, or throw an exception.

**Comment by davidwrighton** [comment]
Well that's a good question. I'd like to defer to @steveharter for what should this thing be doing, and then lets make the two runtimes implement the same logic. I'm generally of the opinion that the particular scenario we're talking about here is probably just wrong.

**Comment by Joe4evr** [comment]
> I can say that while the Generic Attributes test as written fails, it ONLY fails for the case of attempting to look up an attribute of an open type.

Just to confirm, that means in a case of:
```cs
public sealed MyGenericAttribute<T> : NonGenericBaseAttribute { }
```
asking `GetCustomAttributes<NonGenericBaseAttribute>()` *does* include any instances of `MyGenericAttribute<>` with whatever type arguments were at the use-site?

I might be biased, but I'm under the impression that's going to be the majority case. Of course, if Mono can fix the problematic case in time, that's all the better, but maybe it doesn't need to be a full blocker.

**Comment by vargaz** [comment]
If we want to make GetCustomAttributes () work with an open type, then it needs to return an object[], since the return array needs to contain different instantiations of the same type.

**Comment by davidwrighton** [comment]
I don't think we have any consensus on what the behavior should be for anything involving open generics and the GetCustomAttributes api. Obviously we can't return an array of open types. I'm not entirely comfortable with just returning null as CoreCLR does, and I'm pretty sure an exception around bad array type creation isn't what should happen either. Also we can't change the signature of any public apis. That is why I pinged @steveharter because he's nominally in charge of reflection, and might be able to provide a more reasoned opinion on what should happen. However as this is a fairly edge case, I'm ok with shipping what we do have. However, if we decide to do that, I'd like to know so I can modify the existing coreclr runtime test to get rid of the current tests around open generics and re--enable it for mono, as we don't have any coverage for generic attributes in mono at all right now.

**Comment by Joe4evr** [comment]
> If we want to make GetCustomAttributes () work with an open type, then it needs to return an object[], since the return array needs to contain different instantiations of the same type.

Doesn't it already return `Attribute[]`? That's already enough.

**Comment by vargaz** [comment]
Returning Attribute[] could work.

**Comment by SamMonoRT** [comment]
Is there any work to be done here for 6.0 ?

**Comment by davidwrighton** [comment]
No, we'll deal with this in 7.0. I quite like the idea of consolidating on the idea that a request for the open type yields an Attribute[] filled with the closed instances that are actually on the metadata object, but I don't think that will happen now. Also, from some internal discussion about the thicket of runtime/metadata problems that have been identified it looks like the C# feature will be pushed into preview, so we can both get the code out there, and fix the rest of the ecosystem before we make this a fully supported C# feature.

**Comment by madelson** [comment]
Also related: #64169

**Comment by SamMonoRT** [comment]
@davidwrighton @vargaz - do we need any work towards this for 7.0 ? Want to make sure we have enough time for that if needed.

**Comment by SamMonoRT** [comment]
Moving to 8.0.0 for any new Mono support needed.

**Comment by marek-safar** [comment]
Can this issue be now closed?

**Comment by vargaz** [comment]
Fixed in https://github.com/dotnet/runtime/pull/78091.
