### ISSUE TITLE
coreclr build emits extraneous "CI" logging output

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#569]
Even after #448 was fixed, there is extraneous output without using the "-ci" build option, e.g.:
```
##vso[task.prependpath]F:\gh\runtime\.dotnet
```

I used:
```
src\coreclr\build.cmd x64 checked skiptests
```

**Comment by BruceForstall** [comment]
@ViktorHofer

**Comment by ViktorHofer** [comment]
That's an overlook in @chcosta's change which I already reported: https://github.com/dotnet/arcade/pull/4483#issuecomment-562040112

**Comment by chcosta** [comment]
https://github.com/dotnet/arcade/pull/4498

**Comment by BruceForstall** [comment]
This is fixed.
