### ISSUE TITLE
Remove System.Linq entirely in default Blazor WASM app

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#56916]
We've removed a lot of System.Linq usages in a default Blazor WASM app. With the latest builds, there is only 1 method left `ToArray`, and it only has 3 callers:

![image](https://user-images.githubusercontent.com/8291187/128384177-3e68fbaf-ddf9-476a-a33c-d2f1e0b7d301.png)

We should be able to replace these 3 places with:

```C#
new List<T>(...).ToArray()
```

This would completely remove System.Linq from the default Blazor WASM app. Saving 3KB compressed size, saving a whole HTTP request to download the assembly, and saving the expense of loading that assembly at runtime.

cc @stephentoub

**Comment by am11** [comment]
@eerhardt, can we move it to 6.0 milestone since it's already merged? :)
