### ISSUE TITLE
Using X509Certificate2 with an instance backed by a key from PKCS11 causes authorization failure

### ISSUE THREAD

**Issue by Dvergatal** [dotnet/runtime#56924]
Hi all,
I have a problem with a certificate which is being made like this:

```c#
        public virtual X509Certificate2 GetPFX(byte[] certDer, SafeEvpPKeyHandle pKeyHandle)
        {
            var cert = new X509Certificate2(certDer);
            // TODO: determine algorithm type
            var key = new RSAOpenSsl(pKeyHandle);
            var certWithKey = cert.CopyWithPrivateKey(key);
            return cert;
        }
```

and pKeyHandle is on pkcs11 token. According to this reply:
>> function of X509Request
>
> Is this a class from another library?
>
>> return me SafeEvpPKeyHandle but i really don't know how to pass it
>
>If you can get an EVP_PKEY handle to a key, you can construct an instance of the appropriate algorithm using `RSAOpenSsl` or `ECDsaOpenSsl` from the [System.Security.Cryptography.OpenSsl][1] package. Something like:
>
>
>```csharp
> SafeEvpPKeyHandle handle; // Get your handle
> RSA rsa = new RSAOpenSsl(handle);
> // Pass your RSA object around as needed
> ```
>
> If you need an `X509Certificate2` object, you can use `CopyWithPrivateKey` so you have an instance backed by a key from PKCS11.

> [1]: https://www.nuget.org/packages/System.Security.Cryptography.OpenSsl/

_Originally posted by @vcsjones in https://github.com/dotnet/runtime/issues/53345#issuecomment-849685534_

cert.CopyWithPrivateKey(key);` should give me an instance backed by a key from PKCS11, but when i'm trying to connect using RestSharp api with an endpoint i get this error:
> Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed. "These requirements were not met:\nDenyAnonymousAuthorizationRequirement: Requires an authenticated user."

After some digging i found out that certificate has this property HasPrivateKey which is set on false, but it is a pointer to pkcs11. Is it possible that this might lead to the above error? I wouldn't have suspected that this might be a RestSharp library problem cause it uses dotnet implementation for connection and i think that this error is being caused by an incomplete, for some reason, certificate (but it has it's private key on the pkcs11 token).

**Comment by Dvergatal** [comment]
Ok i have verified it with pfx certificate made from key.key and crt.crt files. Now all is connecting properly. But the problem is i am unable to use certificate from file and the key is in pkcs#11 api. Is it possible that the endpoint also needs updated dotnet core?

**Comment by Dvergatal** [comment]
I have also verified using curl call:
```bash
curl --engine pkcs11 -X POST --tlsv1.1 --key-type ENG --key a32eabf0ab1ea0dd3f5ef8f935a8d01e5c347224 --cert-type ENG --cert a32eabf0ab1ea0dd3f5ef8f935a8d01e5c347224 --data-binary @data.json https://some-address -H "Content-Type: application/json
```
that the connection is being established.

**Comment by Dvergatal** [comment]
Ok the problem was on my side:D i was returning bad certificate, not the one returned by _CopyWithPrivateKey_. So i'm closing this issue.

**Comment by bartonjs** [comment]
> i was returning bad certificate,

I was about to say... "looks like you're returning cert, not certWithKey" :smile:.

Glad you got it worked out.

**Comment by Dvergatal** [comment]
Yeah @bartonjs, my mistake:P For some reason i haven't seen this in the code... _certWithKey_ is returning a new object, not modyfing the old one and i had assigned a new one to the _certWithKey_ but the mine function, was returning the old one :P Thx anyway and sorry for making such noise:P My crypto system now is fully operational:D
