### ISSUE TITLE
Question: on macOS, what's the possible reasons for "Interop+AppleCrypto+AppleCommonCryptoCryptographicException : The user name or passphrase you entered is not correct."

### ISSUE THREAD

**Issue by heng-liu** [dotnet/runtime#56929]
We have several tests to create a self-issued certificate, then add it to store` CurrentUser\My` on macOS.
The tests works well on CI for nearly a month, but now they start to fail on CI very often.

The error is as following in [build](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5058571&view=logs&j=a1762d43-9ec6-55e8-af8b-c0d9842bd83b&t=6d0220f8-d751-5901-dc18-2ec44f6eb39f):
```
System.AggregateException : One or more errors occurred. (The user name or passphrase you entered is not correct.) (The following constructor parameters did not have matching fixture data: CertificatesFixture fixture)
  [xUnit.net 00:00:03.92]       ---- Interop+AppleCrypto+AppleCommonCryptoCryptographicException : The user name or passphrase you entered is not correct.
  [xUnit.net 00:00:03.92]       ---- The following constructor parameters did not have matching fixture data: CertificatesFixture fixture
  [xUnit.net 00:00:03.92]       Stack Trace:
  [xUnit.net 00:00:03.92]         
  [xUnit.net 00:00:03.92]         ----- Inner Stack Trace #1 (Interop+AppleCrypto+AppleCommonCryptoCryptographicException) -----
  [xUnit.net 00:00:03.92]            at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain)
  [xUnit.net 00:00:03.92]            at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
  [xUnit.net 00:00:03.92]            at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
  [xUnit.net 00:00:03.92]         /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs(91,0): at Test.Utility.Signing.TrustedTestCert`1.AddCertificateToStore()
  [xUnit.net 00:00:03.92]         /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs(77,0): at Test.Utility.Signing.TrustedTestCert`1..ctor(T source, Func`2 getCert, StoreName storeName, StoreLocation storeLocation, Nullable`1 maximumValidityPeriod)
  [xUnit.net 00:00:03.92]         /Users/runner/work/1/s/test/TestUtilities/Test.Utility/Signing/TrustedTestCert.cs(21,0): at Test.Utility.Signing.TrustedTestCert.Create(X509Certificate2 cert, StoreName storeName, StoreLocation storeLocation, Nullable`1 maximumValidityPeriod)
  [xUnit.net 00:00:03.92]         /Users/runner/work/1/s/test/NuGet.Core.Tests/NuGet.Commands.Test/CertificatesFixture.cs(24,0): at NuGet.Commands.Test.CertificatesFixture..ctor()
```
I tried to repro locally, but the tests passed on my mac machine. And what's more, on CI it sometimes passed.

May I know the possible reasons for this exception? 
Does it require a specific state of the machine running this test? (e.g. the login.keychain needs to be unlocked/locked?)  If so, may I know if there is any way to make the test more robust (do not depend on the machine status)? Thanks!

**Comment by filipnavara** [comment]
Apple stores certificates and private keys separately and pairs them together based on the thumbprint of the certificate. Is it possible that there are some leftovers in the keychain of the CI machine that incorrectly get paired?

**Comment by bartonjs** [comment]
The inner exception would be illuminating (at Interop.AppleCrypto.X509StoreAddCertificate), but it's only printing the callstack and the type, not the message.

My suspicion is that some CI machine doesn't have the default keychain (generally login.keychain) in an unlocked state, so the call to add to the keychain failed with an access denied / locked / etc error.

**Comment by heng-liu** [comment]
Thanks @filipnavara and @bartonjs for your help!
Looks like [this ](https://github.com/actions/virtual-environments/pull/3853/files) fixes the issue.
I may need some more runs to validate that.

**Comment by bartonjs** [comment]
Since it sounds like there's nothing else here, going ahead and closing.
