### ISSUE TITLE
.Net 5 Directory.Delete needs new permissions (vs .Net 4.8)

### ISSUE THREAD

**Issue by Inspyro** [dotnet/runtime#56922]
### Description
`Directory.Delete(somePath, recursive: true)` throws an `UnauthorizedAccessException` when the user has no `ListDirectory` rights on the parent directory

Repro sample:
```csharp
var parent = Directory.CreateDirectory(@"C:\Temp\someparent");
var ac = parent.GetAccessControl();
ac.SetAccessRule(new FileSystemAccessRule(WindowsIdentity.GetCurrent().User, FileSystemRights.ListDirectory, AccessControlType.Deny));
parent.SetAccessControl(ac);

var subDir = Directory.CreateDirectory(@"C:\Temp\someparent\subdir");
Directory.Delete(subDir.FullName, recursive: true);
```

throws:
```
UnauthorizedAccessException: Access to the path 'C:\Temp\someparent\subdir' is denied.
at System.IO.FileSystem.GetFindData(String fullPath, WIN32_FIND_DATA& findData)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
```
This is unexpected, because:
- the same user created the directory
- the user can still create sub directories and files within the directory
- same code works without exception in .Net 4.8
- the directory can be deleted without the recursive: true option

### Configuration
.NET target: Core 5.0.8, and Framework 48 (4.0.30319.42000)
Operating system: Windows 20H2

### Regression?
Yes the same code example from above works without problems in .Net 4.8

### Other information
In our case, enabling the list permission on the parent directory is not an acceptable solution, due to the security implications.

**Comment by adamsitnik** [comment]
It seems to be a regression introduced by https://github.com/dotnet/corefx/pull/28124

**Comment by adamsitnik** [comment]
@Inspyro thank you for a detailed bug report, the problem has been fixed and it's going to be part of .NET 6
