### ISSUE TITLE
Test failure: CloseOutputAsync_ClientInitiated_CanReceive_CanClose

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56927]
Test `System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose`

Day | Run | OS
-----|-----|-----
8/2 | PR #56604 | ubuntu.1804.amd64.open.rt
7/26 | PR #56325 | ubuntu.1804.amd64.open.rt
7/20 | Official run | ubuntu.1804.amd64.open.rt
7/15 | PR #53505 | ubuntu.1804.amd64.open.rt
7/14 | PR #55582 | ubuntu.1804.amd64.open.rt

```
Assert.Equal() Failure
Expected: 17
Actual:   0
   at System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(Uri server) in System.Net.WebSockets.Client.Tests.dll:token 0x6000114+0x2db
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
This is/was wasm/mono issue, arguments of the tests are: `ws(s)://127.0.0.1:...` while we use `corefx-net-http11.azurewebsites.net`.
This stopped on 2.8., so it's probably already fixed.
1 occurrence of timeout on our endpoint on 7.8. which is probably environmental.

Closing for now, if it reoccurs, we might reopen.
