### ISSUE TITLE
Math/MathF.Truncate isn't an intrinsic and results in inefficient codegen

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#56931]
### Description

Math/MathF.Truncate results in bad codegen that calls into native modf which is pretty slow. Instead, it should be an intrinsic for vroundsd/vroundss like Ceiling and Floor are (and clang also does do it for truncate).

### Configuration

Sharplab Core CLR 5.0.721.25508 on amd64

### Regression?

No idea.

### Data

[Sharplab for Math](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACY8pRgVwDtdsAzGZqUYAVGLgw0A3jUazmTFmwAmEdsAA2A4VC5hsGGAAoVazY14BKGXOnU595gHZGAWX0ALAHTbd+o5YBua1kAX2DGcIZmVkYTDQEAYRgAS3VjVXjzKzsbcPtiZzcMLyTU5M4Ac0NA8LCc2UiFGLizADF1CGh00wFLcNsHOQLXD092zqhqiyD6xjqQoA=)
[Sharplab for MathF](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACY8pRgVwDtdsAzGZqUYAVGLgw0A3jUazmTFm14AbCNgwioXMOpgAKFWo28AlDLnTqc68wDsjALLqAFgDEAdMK2cdGfaYBuc1kAX2DGcIZmVkZDdUYAYRgAS2UDVXjTcMsbOWJ7Jww3dyTU5M4AcwMTIKs5MLrZSIUYuI1XVWh0o1izRsYc3LtHFw8OiC7A8IaQoA=)
[Godbolt clang for double](https://godbolt.org/z/frY1vhhn9)
[Godbolt clang for float](https://godbolt.org/z/5YE4oxnjT)

**Comment by tannergooding** [comment]
This should be a relatively simple fix but is going to be for 7.0.0 at the earliest.

**Comment by danmoseley** [comment]
@MichalPetryka any interest in offering a PR?

**Comment by MichalPetryka** [comment]
I've never worked with the JIT so I'd prefer somebody else to do it since I don't really know how sadly.

**Comment by danmoseley** [comment]
Fair enough. Still, if you have an interest I expect @tannergooding could give pointers. 😄
