### ISSUE TITLE
API Proposal: ValueTask.GetResult()

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#56932]
````
public partial struct ValueTask {
    void GetResult();
}
````

````
public partial struct ValueTask<T> {
    T GetResult();
}
````

Rationale: CA2012 says that ValueTask.GetAwaiter().GetResult() doesn't work unless the task has already completed, and to await the task instead. Normally, this would be correct, but sometimes await simply does not work because it's a live thread not an async job and some things don't like their thread id changed out from under them. I've had a handful lurking for years in the test harness (probably causing sporadic test failures we never could find) because the finally blocks were too complex for the analyzer. (I need to check the main codebase).

Example use:

````
var applicationserver = null;
try {
    //...
    applicationserver = new Highlander(...);
    //...
    applicationserver.DisposeAsync().GetResult();
    applicationserver = null;
    // Do something to the backing store
    applicationserver = new Highlander(...);   
} finally {
    applicationserver?.DisposeAsync();
}
````

The production code really does have to tear these down asynchronously but the test harness needs to wait for it to be completely torn down. Changing to IDispose() would be the tail wagging the dog.

Plausible implementation:
````
void ValueTask::GetResult()
{
	if (!IsCompleted)
	{
		var waiter = new ManualResetEventSlim();
		GetAwaiter().OnCompleted(waiter.Set);
		waiter.Wait();
		waiter.Dispose();
	}
	if (IsFaulted) AsTask().GetAwaiter().GetResult(); // Throws exception (might be possible to do better internally)
}

void ValueTask<TResult>::GetResult()
{
	if (!IsCompleted)
	{
		var waiter = new ManualResetEventSlim();
		GetAwaiter().OnCompleted(waiter.Set);
		waiter.Wait();
		waiter.Dispose();
	}
        return IsFaulted
              ? AsTask().GetAwaiter().GetResult() // Throws exception (might be possible to do better internally)
              : Result;
}
````

Food for thought: Task.GetResult() => Task.GetAwaiter().GetResult() for symmetry.

**Comment by svick** [comment]
If I remember correctly, `ValueTask` not having a blocking way to get the result (or any other blocking APIs) was a very conscious design decision to steer people towards using `await`.

If you do need to block, you should use `AsTask()`, and then use the blocking member from `Task`.

**Comment by jhudsoncedaron** [comment]
@svick : Which would have been nice if .GetAwaiter().GetResult() didn't pass most test cases.

**Comment by stephentoub** [comment]
I don't want us to add an API to ValueTask that synchronously blocks waiting for it to complete. Code can just do .AsTask() and synchronously wait on that if it must.

**Comment by adamsitnik** [comment]
> I don't want us to add an API to ValueTask that synchronously blocks waiting for it to complete

Same here. @jhudsoncedaron thank you for your proposal
