### ISSUE TITLE
`Graphics.DrawString` fails to render certain unicode characters.

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/runtime#56948]
* .NET Core Version: 
All versions.

* Have you experienced this same bug with .NET Framework?: 
Yes.

**Problem description:**

Certain unicode characters fail to render using `Graphics.DrawString()`.

The sample app below produces the following result when trying to render the string `"ᦎᦷᦑᦺᦖᦺᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ"`:

![image](https://user-images.githubusercontent.com/9663150/128096012-b3457188-1682-439f-97e7-ddfc1546cc37.png)

```cs
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            ResizeRedraw=true;
        }

        protected override void OnPaint(PaintEventArgs e)
        {
            using var textBrush = new SolidBrush(ForeColor);
            var itemText = "ᦎᦷᦑᦺᦖᦺᧈᦉᦲᧇᦉᦸᧂᦗᧃᦓᦱ";
            var boundingSize = e.Graphics.MeasureString(itemText, Font);

            // Doesn't work
            e.Graphics.DrawString(
                itemText, 
                Font, 
                Brushes.Black, 
                ClientSize.Width / 2 - boundingSize.Width / 2, 
                ClientSize.Height / 2 - boundingSize.Height / 2);

            // Works
            TextRenderer.DrawText(
                e.Graphics,
                itemText,
                Font,
                new Rectangle(
                    (int)(ClientSize.Width / 2 - boundingSize.Width / 2),
                    (int)(ClientSize.Height / 2 - boundingSize.Height / 2) + 50, 
                    300, 300),
                ForeColor, 
                flags: TextFormatFlags.TextBoxControl);
        }
    }
```

**Comment by dreddy-work** [comment]
@safern , this looks like problem in the System.Drawing or Windows.  Transferring here for initial investigation.

**Comment by tarekgh** [comment]
@weltkante is right. The font looks don't have mapping glyphs to the input text and GDI+ couldn't find a better font to fallback to. I am not sure if GDI does it even. This looks limitation that the callers should use fonts having glyphs for the used text.

@KlausLoeffelmann what exactly the font used in your sample?
