### ISSUE TITLE
Exceptions from QUIC APIs should derive from IOException

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#56954]
For one, exceptions from streams usually derive from IOException and QuicStream should follow this.

But it also seems reasonable and consistent to have exceptions from QuicConnection/QuicListener derive from IOException as well. In particular, some exceptions are used for both QuicStream and QuicConnection.

Related: https://github.com/dotnet/runtime/issues/56292#issuecomment-887956058

**Comment by GSPP** [comment]
Precedent is mostly that `IOException` is not being used as a base class. Rather, `QuicException` should be caught by calling code.

**Comment by geoffkizer** [comment]
The problem is that QuicStream derives from Stream, and in general Stream throws IOException. So at least for QuicStream, it seems like we should derive from IOException. so that code that is operating on a generic Stream can at least distinguish IOExceptions from other exceptions.

That said, I don't know how consistent we are about this in general with Stream. Maybe it's not worth it. @stephentoub thoughts?

**Comment by stephentoub** [comment]
I think it's fine to derive from IOException, though we can discuss it with API review when all of this comes through.  There's a lot of antiquated exception derivation stemming from decisions 20 years ago, e.g. the closest existing counterpart to QuicException is probably SocketException, but we're obviously not going to make QuicException derive from Win32Exception or SystemException.  There are plenty of exceptions that derive from IOException, and it is what's propagated from types like NetworkStream.

**Comment by nibanks** [comment]
What about any exceptions/errors related to invalid parameters? TLS/security/crypto related errors? I'm not sure all QUIC errors should be considered IOExceptions necessarily. But I guess it's more of a question: Does the base class of an exception reflect the **type** of exception or **source** of exception?

**Comment by ManickaP** [comment]
Closing as covered by https://github.com/dotnet/runtime/issues/70669
