### ISSUE TITLE
QuicException should be abstract and not thrown directly

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#56955]
Right now we have a handful of exception types that derive from QuicException, e.g. QuicConnectionAbortedException.

We also sometimes throw QuicException directly, in particular when an msquic API fails. 

We should not throw QuicException generically like this. We should try to interpret the msquic error code, and act appropriately -- either map it to a specific (new or existing) exception, or handle the error internally, or similar. In the worst case we could probably throw something like QuicInternalException to indicate "something bad happened, we don't know what" but that should be as rare as possible.

**Comment by GSPP** [comment]
The `SqlException` way of doing things is really nice. All exceptions are an `SqlException` and you can interrogate that object to analyze the error.

In my opinion, this is the gold standard for a high-level API.

`SocketException` is another such success story.

So I'd propose that `QuicException` (and derived types) would be the only ones thrown. There should be an integer code that allows callers to detect the specific condition.

**Comment by geoffkizer** [comment]
> So I'd propose that QuicException (and derived types) would be the only ones thrown. There should be an integer code that allows callers to detect the specific condition.

That seems like a reasonable way to go, and in fact when we've had similar discussions in the past we have tended to do exactly that. 

That said, it is somewhat orthogonal to this issue. The thing I'm trying to get at in this issue (which unfortunately may not be as clear as I had hoped) is that we shouldn't just expose the msquic error code/error text to the user. We should interpret it, and either silently handle it ourselves, or map it to one of our well-defined exception cases. Whether those exception cases are exposed as a separate exceptions deriving from an abstract base exception, or a single concrete exception with an enum to distinguish different exception cases, is orthogonal.

**Comment by GSPP** [comment]
I understand better now.

Not letting msquic details leak out seems wise. Who knows if .NET will use msquic at all in 5 or 10 years from now?

For example, the previous HTTP stack has migrated away from WinHTTP. I believe SqlClient is migrating as well but I could be mistaken.

**Comment by geoffkizer** [comment]
> Who knows if .NET will use msquic at all in 5 or 10 years from now?

Yep. And even if we do, we might be using msquic v2 or v3, which might have differences in how this stuff is handled.

**Comment by ManickaP** [comment]
Closing as covered by https://github.com/dotnet/runtime/issues/70669
