### ISSUE TITLE
Need reorder conditions in HasWildCardCharacters method

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#56964]
Update:  HasWildCardCharacters () is not used any more. PR to remove #57028.

Original issue:

### Description

I'd expect users use `*` and `?` chars more often and they should be on first place. ([Docs ](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fsa/0b034646-4e23-4874-8488-2adac231ff23?redirectedfrom=MSDN)say the same.)

https://github.com/dotnet/runtime/blob/6ac03709fd2d017e84f8139284cfa6b5c3a56934/src/libraries/System.Private.CoreLib/src/System/IO/PathInternal.Windows.cs#L174-L195

### Configuration

.Net 6.0 Preview.6

**Comment by adamsitnik** [comment]
I am not sure if reording would help us a lot, but using the vectorized version might be worth giving a try:

https://github.com/dotnet/runtime/blob/e847c8c71da94a2a70c2391352cd13ea8dbb6e8f/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.cs#L725-L733

@iSazonov would you be interested in running some benchmarks and sending a PR?

**Comment by iSazonov** [comment]
It seems the HasWildCardCharacters method is not used any more and could be removed.

Looking the file I think vectorization could be used for other methods in the file.
And I guess it's worth it.

> @iSazonov would you be interested in running some benchmarks and sending a PR?

I have an interest (to get this in PowerShell) but haven't experience for the work today. :-(

**Comment by iSazonov** [comment]
@adamsitnik I think it is better to remove the dead code and close the issue. See #57028.

If you see any chance to improve performance of methods in the file (PathInternal.Windows.cs) I will open new tracking issue.
