### ISSUE TITLE
[ARM] LSRA heuristic tuning

### ISSUE THREAD

**Issue by alpencolt** [dotnet/runtime#56978]
I've tried to apply orderings described in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/lsra-heuristic-tuning.md#outcome on ARM and measure application startup time, but difference was less than stddev.

1. Have you performed measurement on real applications or benchmarks with described orderings? What results have you observed?
2. Does the option `COMPlus_JitLsraOrdering` available for code generated by crosgen2?
3. [`emitter::getInsExecutionCharacteristics()`]( https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/emitarm.cpp#L8221) isn't implemented for ARM and `superpmi` cannot be used as metric. Could you share amount of generations and measurement, it will be useful for estimation if we'll decide to use genetic algorithm with real apps.

cc @jkotas @CarolEidt @kunalspathak

**Comment by alpencolt** [comment]
Hm, I forgot that crossgen2 expect options via `--codegenopt`. Let me check again.

**Comment by alpencolt** [comment]
Tried to pass heuristics through `--codegenopt` but difference still be non observable.
Could you share measurements on real apps if you have.

**Comment by kunalspathak** [comment]
> I've tried to apply orderings described in https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/lsra-heuristic-tuning.md#outcome on ARM and measure application startup time, but difference was less than stddev.

May I know what apps you tried?

> * Have you performed measurement on real applications or benchmarks with described orderings? What results have you observed?

Short answer No. As you noticed in [heuristic tuning](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/lsra-heuristic-tuning.md) document, every time there is a new offspring, we need to measure its performance to see if it is beneficial or not. Since there are 1000s of offsprings produced during the process, we wanted to make sure that the fitness calculation for each offspring (performance measurement) is fast. Hence, we relied on `PerfScore` metrics on set of superpmi collections. It is much faster and reliable than running benchmarks for every combination. Although `PerfScore` might not be accurate, we have seen it the past that it gives decent speculation on the execution time and we use that metric to measure the diff.


> * [`emitter::getInsExecutionCharacteristics()`](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/emitarm.cpp#L8221) isn't implemented for ARM and `superpmi` cannot be used as metric. Could you share amount of generations and measurement, it will be useful for estimation if we'll decide to use genetic algorithm with real apps.

We have used `--altjit` mechanism (basically produce the JIT code for a specific target OS/arch) and you could do that from different host OS. For example, I ran the following from my windows/x64 to get the diff for linux/arm. Note the parameters I used for `-target_os` and `-target_arch`.

```
python superpmi.py asmdiffs -f benchmarks -base_jit_path clrjit_unix_arm_x86.dll -diff_jit_path copy_clrjit_unix_arm_x86.dll -target_os Linux -target_arch arm -arch x86 -error_limit 10 -diff_jit_option JitLsraOrdering=APCDEGHNIOFJKLBMQ

```

Let me know if you have more questions and I will be happy to answer them.

**Comment by alpencolt** [comment]
@kunalspathak we use set of https://github.com/Samsung/Tizen-CSharp-Samples applications and run on galaxy watches. Since there are 1000s of offsprings generated during process and one run in our environment consume ~5 hours the only possible way to find heuristics is using superpmi.


> We have used `--altjit` mechanism (basically produce the JIT code for a specific target OS/arch) and you could do that from different host OS. For example, I ran the following from my windows/x64 to get the diff for linux/arm. Note the parameters I used for `-target_os` and `-target_arch`.

According to [docs](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/design/coreclr/jit/Perf-Score.md#modern-cpu-hardware-documentation) `PerfScore` is based on [`emitter::getInsExecutionCharacteristics()`](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/emitarm.cpp#L8221) which returns always `1` latency and throughput and it will not provide correct measurements. Correct me if I wrong.
We can implement this method and it doesn't look as an impossible task but I want to know what effect may cause LSRA tuning to overall performance first. I'll check benchmarks on x64 and share results.

And according to documentation `PerfScore` doesn't consider speculative execution, am I right?

**Comment by kunalspathak** [comment]
> According to docs PerfScore is based on emitter::getInsExecutionCharacteristics() which returns always 1 latency and throughput and it will not provide correct measurements. 

That's correct. That is the reason the column under `Linux-arm Libraries` 's of https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/lsra-heuristic-tuning.md#outcome, the `PerfScore` is off for all the combinations compared to other configurations. The `python` command in https://github.com/dotnet/runtime/issues/56978#issuecomment-895484416 would give you `CodeSize` diff on linux-arm but `PerfScore` will not be accurate.

> I'll check benchmarks on x64 and share results.

That would be great. A step further, to get a faster estimate on x64 for any combination, you could also do the following - You could run your benchmark using [superpmi collect](https://github.com/dotnet/runtime/blob/main/src/coreclr/scripts/superpmi.md#collections) which would cache all the runtime data in `.mc` files. Next, you could use `superpmi asmdiff` technique with various combinations on the produced `.mc` file to see how the register allocation ordering impacts your benchmark. This will give you the closest approximation of the impact on your benchmarks without running them for every combination.

> And according to documentation PerfScore doesn't consider speculative execution, am I right?

That is correct. It is the best guess estimate and most often better than `CodeSize` metrics when you want to measure an impact of register allocation changes.

**Comment by kunalspathak** [comment]
No further action is needed on our side. Closing the issue.
