### ISSUE TITLE
[API Proposal]: Equivalent to ICLRStrongName::StrongNameSignatureVerificationEx from .NET Framework

### ISSUE THREAD

**Issue by MartyMcFly85** [dotnet/runtime#56976]
### Background and motivation

In order to be able to verify the strong name of a .NET assembly at runtime without launching an external process like sn.exe which might not be practical in all situations, there should be an equivalent to ICLRStrongName::StrongNameSignatureVerificationEx from .NET Framework (MSCorEE.dll).

### API Proposal

```C#
namespace System.Reflection.AssemblyName
{
    public bool VerifyStrongNameSignature();
}
```     

### API Usage

```C#
// Verify the strong name signature.
bool isValid = Assembly.GetExecutingAssembly().VerifyStrongNameSignature();
```

**Comment by jkotas** [comment]
Strong name signatures are deprecated in .NET Core / .NET 5+. Nothing in the runtime pays attention to them. They are not meant to be used for security purposes (documented in https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named). 

Why do you need to validate the strong name signatures in .NET Core / .NET 5+?

**Comment by MartyMcFly85** [comment]
In our applications and components/librarys we use strong name verification in order to make sure that our libraries can only be used from out own applications. For example, we don't want to allow 3rd parties to use our libararies for reading our proprietary file formats or enable them to have their libraries loaded into our processes as plug-ins by them implementing our extensibility interfaces.
We are fully aware, that strong names should not be used for security purposes. A possible alternative would be verifying authenticode signatures of the respective assemblies but this process takes significantly longer than strong name verification which is why we're unable to use that. 
If .NET (Core) not longer offers support for strong name verification, do you have any other suggestion for the aforementionend scenarios?

**Comment by jkotas** [comment]
If your application runs on Windows only, you can keep using `ICLRStrongName::StrongNameSignatureVerificationEx` from .NET Framework. .NET Framework is part of Windows OS and it is not going away.

If you need cross-platform implementation, you can write your own managed implementation. Here is example of managed strong name signing implementation: https://gist.github.com/jkotas/a21de87b790e06979635 . The strong name validation is very similar, except that you compare the signature instead of writing it out into the image.

**Comment by MartyMcFly85** [comment]
Thank you very much for your suggestions and for providing the managed strong name signing implementation. We're indeed looking for a fully managed code solution since some of our solutions need to run on Linux as well as on Windows. However, using the provided strong name signing implementation at runtime and out in the field would require us to somehow embed our strong name key pair (including the private key) into our deliverables. The ICLRStrongName::StrongNameSignatureVerificationEx is able to verify the integrity of a strong name signature without access to the private key and we need a solution that works in a similar way.

**Comment by jkotas** [comment]
To verification of the signature needs to read the public key from the image. The private key is not necessary. Here is an example for how to do it: https://gist.github.com/jkotas/efc9d4f0e734da9a7d81e96599724955
