### ISSUE TITLE
System.Text.Json Source Generator not working with classes in global namespace

### ISSUE THREAD

**Issue by Vake93** [dotnet/runtime#56970]
### Description
If a class is defined in the global namespace, the JsonSerializerContext class code generation does not work.
Installed .NET SDK Version is: 6.0.100-preview.6.21355.2

Steps to re-create this is as follows:
1. Create a new .NET 6 console application
2. Add a reference to the latest preview of System.Text.Json NuGet (I tested with 6.0.0-rc.1.21405.12)
3. Replace the contents of Program.cs with the following

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

string SerializeSourceGen() => JsonSerializer.Serialize(new Person("Vishvaka", "Ranasinghe", 28));

SerializeSourceGen();

public class Person
{
    public Person(string firstName, string lastName, uint age)
    {
        FirstName = firstName;
        LastName = lastName;
        Age = age;
    }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public uint Age { get; set; }
}

[JsonSerializable(typeof(Person))]
internal partial class MyJsonContext : JsonSerializerContext
{
}
```

4. Run with dotnet run command. Notice the build fails.
5.  Now replace the contents of Program.cs with the following
```C#
using Experiments;
using System.Text.Json;

string SerializeSourceGen() => JsonSerializer.Serialize(new Person("Vishvaka", "Ranasinghe", 28));
SerializeSourceGen();
```
6. Create new Models.cs file with the contents as:
```C#
using System.Text.Json.Serialization;

namespace Experiments
{
    public class Person
    {
        public Person(string firstName, string lastName, uint age)
        {
            FirstName = firstName;
            LastName = lastName;
            Age = age;
        }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public uint Age { get; set; }
    }

    [JsonSerializable(typeof(Person))]
    internal partial class MyJsonContext : JsonSerializerContext
    {
    }
}
```
7. Project build and run as expected.

Not having support for classes cause the need to create additional files with namespaces when trying to create a simple application using top-level statements.

**Comment by stephentoub** [comment]
Thanks. Dup of https://github.com/dotnet/runtime/issues/56920.
