### ISSUE TITLE
Dynamic certificate update is failing in HTTPClient Handler for mutual authentication?

### ISSUE THREAD

**Issue by smartaquarius10** [dotnet/runtime#56975]
Team,

I have made an api in .net core 3.1 and created a custom HTTP Client Handler to manage dynamic certificates per http call but, the calls with only first certificate remains successful. Any call for other certificates gives authentication error from server side because **ClientCertificates.Clear()** is not working. 

**Startup.cs**

    services.AddHttpClient(Configuration["ClientName"], c =>
                 {
                     c.BaseAddress = new Uri(Configuration["URL"]);
                 }).ConfigurePrimaryHttpMessageHandler<RegistryHttpHandler>()
    
    
     service.AddSingleton<IHttpClient, HttpClient>(); //My custom http client class 
    
     service.AddTransient<RegistryHttpHandler>();  // Here life time doesn't matter because Http Client is singleton

**The code for send async is:**

     using (var client = _clientFactory.CreateClient(clientName))
                    {
                        using (var response = await client.SendAsync(request))
                        {
                            if (response != null)
                            {
                                data= await response.Content.ReadAsStringAsync();
                            }                        
                        }
                    }

**The code for certificate handler is:**

    public class CertificateRegistryHttpHandler : HttpClientHandler, IDisposable
        {
            private readonly IConfiguration _configuration;
            private readonly Dictionary<string, X509Certificate2> _certMap;
            private bool disposedValue;
            public CertificateRegistryHttpHandler(IConfiguration configuration) : base()
            {
                _configuration = configuration;
                _certMap = new Dictionary<string, X509Certificate2>() { { configuration["DefaultCertificateName"], new X509Certificate2(fileName: Path.Combine(configuration["CertificatePath"], configuration["DefaultCertificateName"]), password: _configuration[configuration["DefaultCertificateName"]]) } };
            }
    
            protected override async Task<HttpResponseMessage> SendAsync(
                    HttpRequestMessage request,
                    CancellationToken cancellationToken)
            {
                var appId = (string)Microsoft.AspNetCore.WebUtilities.QueryHelpers.ParseQuery(request.RequestUri.Query)["myID"];
                string certName = _configuration[appId];
                if (!string.IsNullOrEmpty(certName))
                {
                    string certPass = _configuration[certName];
                    if (!string.IsNullOrEmpty(certPass))
                    {
                        if (!_certMap.ContainsKey(certName))
                        {
                            string certPath = Path.Combine(_configuration["CertificatePath"], certName);
                            if (File.Exists(certPath))
                            {
                                _certMap.Add(certName, new X509Certificate2(fileName: certPath, password: certPass));
                                AddCertificate(certName);
                            }
                            else
                            {
                                AddCertificate(_configuration["DefaultCertificateName"]);
                            }
                        }
                        else
                        {
                            AddCertificate(certName);
                        }
    
                    }
                    else
                    {
                        AddCertificate(_configuration["DefaultCertificateName"]);
                    }
                }
                else
                {
                    AddCertificate(_configuration["DefaultCertificateName"]);
                }
                return await base.SendAsync(request, cancellationToken);
            }
            private void AddCertificate(string certName)
            {
                if (_certMap[certName]!=null && !ClientCertificates.Contains(_certMap[certName]))
                {
                    ClientCertificates.Clear();
                    ClientCertificates.Add(_certMap[certName]);
                }
            }
            protected override void Dispose(bool disposing)
            {
                if (!disposedValue)
                {
                    if (disposing)
                    {
                        _certMap.Values.All(x =>
                        {
                            x.Dispose();
                            return true;
                        });
                        _certMap.Clear();
                    }
                    base.Dispose();
                    disposedValue = true;
                }
            }
            public new void Dispose()
            {
                Dispose(disposing: true);
                GC.SuppressFinalize(this);
            }
        }
    }

In debug mode, I have cleared the pervious certificate and added the new one. Still, httpclient is sending the request with the old one and server returns authentication error. 

But, on waiting for around 3 minutes in the debug the request with updated certificate also works. Then again update the certificate and wait for around 3 minutes. Can anyone please suggest the procedure to update the certificates in the ClientCertificates collection of httpclienthandler immediately as I'm facing error in production and local machine as well. 

In local machine, I have windows 10 Enterprise version 1909 ( OS build 1863.1621)

**Comment by CarnaViire** [comment]
If you want dynamic certificates, you need to use `SocketsHttpHandler.SslOptions.LocalCertificateSelectionCallback`
Please see this issue for examples https://github.com/dotnet/runtime/issues/52779

Also, you are using HttpClientFactory, so `System.Net.Http.HttpClient` you create on this line
`using (var client = _clientFactory.CreateClient(clientName))`
will reuse `RegistryHttpHandler` for the handler lifetime configured inside HttpClientFactory, after that new handler will be created. By default, handler lifetime is 2 minutes. This is why you've seen the cert "fixed" after two minutes.

I am not sure if the usage of HttpClientFactory is intended and/or needed, especially if you want HttpClient to be a singleton. You can just register it as a singleton in CI. By HttpClient here I mean `System.Net.Http.HttpClient` not your custom class which seems to be using it inside.

You can do it like this

```c#
        services.AddSingleton(sp => new HttpClient(new SocketsHttpHandler()
        {
            PooledConnectionLifetime = TimeSpan.FromMinutes(2), // or whatever time you expect to have DNS changes
            SslOptions = new SslClientAuthenticationOptions()
            {
                LocalCertificateSelectionCallback = (object sender, string targetHost, X509CertificateCollection localCertificates, X509Certificate? remoteCertificate, string[] acceptableIssuers) => 
                {
                    // return certificate based on some logic, e.g. the one you previously had in RegistryHttpHandler
                }
            }
        }));
```

Then you can have it injected into your custom class. Be sure *not to call Dispose* on the singleton instance.

Please let me know if any of this helps.

**Comment by smartaquarius10** [comment]
@CarnaViire ,

Hello, thank you very much for sharing the code. Actually, I thought why to recreate HttpClientFactory as I read somewhere that objects of httpclient or factory or anything else related to this should be created only once rather than again and again. So under that impression I have done this. There is no specific reason other than this. Currently, in my project I'm using 2 http clients both are calling different api's in a different way(out of which one I have already shown above). 

But I'm unable to understand this comment of yours. Am I doing anything wrong. Or not following the correct pattern. I would be thankful if can suggest.  

**I am not sure if the usage of HttpClientFactory is intended and/or needed, especially if you want HttpClient to be a singleton.**

Other than this, could you please suggest me the procedure to bypass ssl validation in your code. The problem is that my on premises server doesn't have updated TLS cipher suites. So around 20 to 30 times in a day I get the error **[SSL connection could not be established. Value cannot be null](https://docs.microsoft.com/en-us/answers/questions/489456/httpclienthandler-throwing-exception-when-handling.html)**

**Comment by CarnaViire** [comment]
> Am I doing anything wrong. Or not following the correct pattern.

You should not be modifying `ClientCertificates` on the run. This property needs to be set before the first request is fired.
If you want to pick a certificate on the run depending on any logic, instead of `ClientCertificates`, you need to use `SocketsHttpHandler.SslOptions.LocalCertificateSelectionCallback`
Please see this issue for example #52779

**Comment by CarnaViire** [comment]
> I read somewhere that objects of httpclient or factory or anything else related to this should be created only once rather than again and again.

That is true. That's why I proposed registration as a singleton.

You certainly can continue using HttpClientFactory if you wish so. It is not wrong, it is just an overhead I though you might not need.

**Comment by CarnaViire** [comment]
Closing as answered. If you have any troubles on setting up `LocalCertificateSelectionCallback`, feel free to reopen.

**Comment by smartaquarius10** [comment]
@CarnaViire , Sure will check. One last thing. Could you please suggest the procedure of bypassing SSL validation in this. Because as per my understanding we don't have this field **ServerCertificateCustomValidationCallback** in socket handler

**Comment by ManickaP** [comment]
`SslOptions.RemoteCertificateValidationCallback` should give you the equivalent functionality.
