### ISSUE TITLE
Support for Android "Profiled AOT" in .NET 6

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#56989]
This feature in Xamarin.Android is also known as "Startup Tracing":

https://devblogs.microsoft.com/xamarin/faster-android-startup-times-with-startup-tracing/

Yet another name for this might be "profile guided optimization".

For .NET 6, we'd like users be able to do something like the following in Release builds:

```xml
<RunAOTCompilation>true</RunAOTCompilation>
<UseProfiledAOT>true</UseProfiledAOT>
```

This would use a built-in profile that the Android workload provides as well as the .NET MAUI workload. Recording a custom profile for a developer's app is probably not something we need in .NET 6. However, the Android & .NET MAUI teams would need to be able to record profiles. .NET MAUI's startup path is still quite a bit in flux, so ideally we would be automate the creation of the built-in MAUI profile.

There are a few pieces missing from dotnet/runtime at the moment:

1. `libmono-profiler-aot.so`
2. `aprofutil`
3. `MonoAOTCompiler.AotProfilePath` only accepts 1 value:

https://github.com/dotnet/runtime/blob/ce3447c78fbddfe8485d6d7e527c1e8a7429d8f0/src/tasks/AotCompilerTask/MonoAOTCompiler.cs#L111-L114

For .NET 6, I think we can take a simple approach:

1. Build & ship `libmono-profiler-aot.so` in the Android runtime packs.
2. The Android workload can ship a `aprofutil` from mono/mono. We can emit warnings that mention recording custom AOT profiles is an experimental feature.
3. We can emit `profile-only,profile=foo.aprof` for `%(AotArguments)` in the Android MSBuild targets until there is a different way.

These would get us by for now.

In the long run, recording custom AOT profiles might be something that `dotnet-trace` / diagnostics should support.

**Comment by akoeplinger** [comment]
So we need to do two things:

- [ ] enable build of `libmono-profiler-aot.so` in mono.proj (it's already done for Browser)
- [ ] support multiple arguments for `AotProfilePath` in MonoAOTCompiler

**Comment by steveisok** [comment]
> So we need to do two things:
> 
> * [ ]  enable build of `libmono-profiler-aot.so` in mono.proj (it's already done for Browser)

I'm assuming we would want to include this file in the aot pack, correct?

**Comment by jonathanpeppers** [comment]
@steveisok it could got in the AOT pack, but you would need an item group like this:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.MonoCrossAOT.Sdk.props.in#L2-L4

Then the Android workload could include this file in apps when needed.

**Comment by jonathanpeppers** [comment]
@steveisok I'm able to build a `libmono-profiler-aot.so` that works successfully:

* https://github.com/dotnet/runtime/compare/main...jonathanpeppers:libmono-profiler-aot.so
* https://discord.com/channels/732297728826277939/732297837953679412/875493456334696448

When you're around next week, let's discuss what I need to do to finish this.

I'm having trouble building the AOT packs, such as:

https://github.com/dotnet/runtime/blob/main/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.MonoCrossAOT.sfxproj

```
$ ./build.sh mono.aotcross -os android -c Release -bl -pack
...
monoaotcross.proj(32,7): error MSB4184: The expression """.Substring(0, -1)" cannot be evaluated. Length cannot be less than zero. (Parameter 'length')
```

I'm probably doing something wrong.

**Comment by akoeplinger** [comment]
@jonathanpeppers looks like you need to pass `/p:MonoCrossAOTTargetOS=Android`

**Comment by jonathanpeppers** [comment]
Thanks, I ended up using:

```
$ ./build.sh mono+packs -os android -c Release -bl -p:MonoCrossAOTTargetOS=Android
```

I might be able to finish now, I'll give a try.

**Comment by jonathanpeppers** [comment]
I got `libmono-profiler-aot.so` added to the `Microsoft.NETCore.App.Runtime.AOT.[host-rid].Cross.[target-rid]` packs, and added a new item group for its path.

But the problem is these packs are only imported when `$(RunAOTCompilation)` is true:

https://github.com/dotnet/runtime/blob/6fca5a5d957765374749cb6871b5ec17277ec4d5/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.targets.in#L20-L25

When users record a profile, they won't be using AOT. Generally you just run a Debug build to record a profile, and `$(RunAOTCompilation)` would be blank.

Should I add this file to the runtime packs? And I would add something to exclude it in the Android workload for most builds? Similar to a Mono component, I guess?

**Comment by steveisok** [comment]
Moving the milestone to .NET 7 as we plan on trying to streamline w/ diagnostics.

**Comment by steveisok** [comment]
In .NET 7, with https://github.com/dotnet/runtime/pull/70194, https://github.com/dotnet/runtime/pull/70851, and https://github.com/dotnet/runtime/pull/68571, we have a replacement for `libmono-profiler-aot.so` and `aprofutil`.
