### ISSUE TITLE
[API Proposal]: System.Diagnostics.Process.WaitForExit() should return the Process to allow chaining of calls

### ISSUE THREAD

**Issue by CorruptComputer** [dotnet/runtime#57001]
### Background and motivation

This would allow method calls to be chained and reduce the number of lines of code required for certain actions.

### API Proposal

Before
```C#
namespace System.Diagnostics
{
     public class Process
     {
         public void WaitForExit();
     }
}
```     

After:
```C#
namespace System.Diagnostics
{
     public class Process
     {
         public Process WaitForExit();
     }
}
```     

### API Usage

Before:
```C#
Process p = Process.Start(exeFilePath);
p.WaitForExit();

if (p.ExitCode == 1)
{
    // Handle the error somehow
}
```

After:
```C#
if (Process.Start(exeFilePath).WaitForExit().ExitCode == 1)
{
    // Handle the error somehow
}
```     

### Risks

It currently returns void, so I'm not sure if this would cause any issues with backwards compatibility. 
Since if someone is already using the above 'Before' code it would continue working without any changes.

**Comment by GSPP** [comment]
Chaining of calls serves to compress the program in terms of the number of its characters. There is a heavy price to pay: the program becomes harder to read and maintain.

**Comment by huoyaoyuan** [comment]
> so I'm not sure if this would cause any issues with backwards compatibility

It's obviously breaking change and unacceptable.

Chaining calls isn't fashioned in BCL. Only a few cases like `StringBuilder` use the pattern.

**Comment by CorruptComputer** [comment]
> the program becomes harder to read and maintain.

I think there are situations where this could make code easier to read, take these two examples:
```c#
// Returns the exit code given by the executable
private int RunExecutable(string exeFilePath)
{
    Process p = Process.Start(exeFilePath);
    p.WaitForExit();

    return p.ExitCode;
}
```
```c#
// Returns the exit code given by the executable
private int RunExecutable(string exeFilePath) => 
    Process.Start(exeFilePath).WaitForExit().ExitCode;
```
I personally find the second one to be more easily readable, and a lot more concise.
Adding this wouldn't force you to use it if you dislike chaining. 
But rather, it would just be an option if you wanted to, the top code would still work fine even if this change were accepted.

> It's obviously breaking change and unacceptable.

Could you explain a situation in which this would be a breaking change? 
I can't think of any situations where changing this would cause it to break existing code.

**Comment by KalleOlaviNiemitalo** [comment]
This would be a binary breaking change, i.e. the new version of System.Diagnostics.Process.dll would not be compatible with assemblies that were built before the change and use the WaitForExit method. The assemblies would have to be rebuilt from source.

**Comment by huoyaoyuan** [comment]
The method's binary signature consists of name, parameter types and return type. Changing any of them is a breaking change.

**Comment by CorruptComputer** [comment]
I guess that is true you would need to rebuild the application, but I feel like that is kind of a moot point since you need to rebuild your application anyways when upgrading .NET versions. So in practice that would be a non-issue.

**Comment by svick** [comment]
@CorruptComputer It is an issue when you're trying to use a library that was built for an older version of .Net on a newer version of .Net.

**Comment by adamsitnik** [comment]
Hi @CorruptComputer 

Thank you for your proposal. As others have pointed out, this would be a [breaking change](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/coding-guidelines/breaking-changes.md#bucket-1-public-contract). 

If you want, you can introduce an [extension method](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) to your app|lib and get a similar effect:

```cs
static class ProcessExtensions
{
    static Process WaitForExitAndReturn(this Process process)
    {
        process.WaitForExit();
        return process;
    }
}
```

Since we can't accept breaking changes, I am going to close the issue. Thanks!
