### ISSUE TITLE
Type name conflicts in PowerShell after moving to .Net 6.0 Preview7

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#57017]
### Description

See https://github.com/PowerShell/PowerShell/pull/15886 It is very amazing to see such name conflicts.

1. System.Management.Automation.ExecutionContext vs System.Threading.ExecutionContext

Proposal is to rename System.Threading.ExecutionContext to System.Threading.**ThreadExecutionContext**

"ExecutionContext" is such a common pattern that there will be conflicts in many projects.

2. System.Management.Automation.DriveNotFoundException vs System.IO.DriveNotFoundException

I haven't exact proposal. If we renamed System.Management.Automation.DriveNotFoundException to System.Management.Automation.**PSDriveNotFoundException** in PowerShell repository this would be a breaking change. I feel it is not accessible  /cc @SteveL-MSFT @adityapatwardhan 

I hope .Net can find alternative name for  System.IO.DriveNotFoundException (maybe **IODriveNotFoundException**?)

### Regression?

Regression in PowerShell after moving to .Net Core 6.0 Preview.7.

**Comment by jkotas** [comment]
> Proposal is to rename System.Threading.ExecutionContext

ExecutionContext is a very old type introduced more than decade ago. Renaming it would be significant breaking change.

I think you are getting bitten by implicit namespaces feature. You may want to set:
```
<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>
<DisableImplicitNamespaceImports_DotNet>true</DisableImplicitNamespaceImports_DotNet>
```
in the Powershell repo to disable it. FWIW, it is what we have done in this repo as well.

**Comment by iSazonov** [comment]
> it is what we have done in this repo as well.

@jkotas Thanks! Is the problem caused by changing the default values in Preview7?

**Comment by MichalStrehovsky** [comment]
It's caused by implicit usings that add an implicit "using System.Threading" at the beginning of all CS files. The above properties disable the feature.

The feature is going to be disabled by default after Preview 7 because it causes trouble like this in existing code (and more): https://github.com/dotnet/sdk/issues/19521
