### ISSUE TITLE
[Mono] Linker generating invalid IL with exception filters

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#57010]
The exception filters introduced in https://github.com/dotnet/runtime/compare/ab0991e1adf2e4ebbcb09a1ddcfdfc031aa21510...40ed818e5ecd9f413ca75bb62c2eb4913acbc723#diff-b79affd636899ac98b816c1398f9dca19bc4850a939a3815c09c5a9931094a4c started to make the iOS AOT functional tests fail with:

```
[System.Net.Http.dll] Unable to compile method 'void System.Net.Http.Http3RequestStream/<SendAsync>d__28:MoveNext ()' due to: 'Invalid IL code in System.Net.Http.Http3RequestStream/<SendAsync>d__28:MoveNext (): IL_05e1: pop 
```

As a result, the iOS and Catalyst legs are failing on CI.

**Comment by vargaz** [comment]
Can you attach the linked assembly ?

**Comment by steveisok** [comment]
[System.Net.Http.dll.zip](https://github.com/dotnet/runtime/files/6948253/System.Net.Http.dll.zip)

**Comment by vargaz** [comment]
How can I reproduce this ?

**Comment by steveisok** [comment]
Pull main, build for iOSSimulator, and then build the functional test.

./dotnet.sh build /t:Test src/tests/FunctionalTests/iOS/Simulator/AOT /p:TargetOS=iOSSimulator /p:TargetArchitecture=x64

**Comment by vargaz** [comment]
This is a linker problem, the original IL in `'<SendAsync>d__28'::MoveNext` is:
```
            filter
            {
              IL_0746:  isinst     [System.Net.Quic]System.Net.Quic.QuicStreamAbortedException
              IL_074b:  dup
              IL_074c:  brtrue.s   IL_0752

              IL_074e:  pop
```
while the linked one is:
```
            filter
            {
              IL_078c:  brtrue.s   IL_0792

              IL_078e:  pop
```
which is not valid anymore.

**Comment by lewing** [comment]
cc @agocke @sbomer @eerhardt @marek-safar

**Comment by SamMonoRT** [comment]
@steveisok - does this https://github.com/dotnet/runtime/pull/57011 address this in entirety ?

**Comment by SamMonoRT** [comment]
Assigning to you for tracking purpose

**Comment by agocke** [comment]
Thanks, we'll take a look at the linker issue.

**Comment by SamMonoRT** [comment]
> Thanks, we'll take a look at the linker issue.

Thanks, is there a better Label to use for tracking linker related issues, and/or does this issue need to be ported over to some other repo ?

**Comment by kasperk81** [comment]
how about transfer this to linker repo https://github.com/mono/linker/issues? or at least have one issue talking about this exception filters bug analysis.

**Comment by SamMonoRT** [comment]
@vitek-karas - do you have a corresponding issue in mono\linker repo or will you use this to track the actual fix ?

**Comment by SamMonoRT** [comment]
Closing this issue, we will track via mono/linker#2181
