### ISSUE TITLE
Should be nullable value when mixing with a non-nullable value

### ISSUE THREAD

**Issue by MaledongGit** [dotnet/runtime#57042]
https://github.com/dotnet/runtime/blob/5aced7eb238ed2dc9e95734ede4be6e11d74dd9c/src/libraries/System.Collections/src/System/Collections/Generic/CollectionExtensions.cs#L15-L23

Notice the function: L23 is a conditional return (a non-nullable value with a nullable value).  The return type (L15) should be "TValue?" instead of "TValue", obviously in a nullable limit, because it MAY return you a nullable return——What I mean is: If we meet with a nullable with a non-nullable value, it should always be the nullable value's defination as a return type.

PS: I suspect it's a compiler bug, but I'm not sure.... Please be kind to tell me whether it should be fixed? or I should fix the code as:

```csharp
 public static TValue? GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue) 
```
Just add a "?" after "TValue" for nullable check condition.

Test under net 6.0

**Comment by stephentoub** [comment]
In this overload, the caller gets to specify the `TValue`.  If they specify a nullable `TValue`, then it'll be nullable.  If they specify a non-nullable `TValue`, then it'll be non-nullable, and they'll get a warning if they try to pass in a nullable `defaultValue`.  The signature is correct as-is.  Thanks.

**Comment by MaledongGit** [comment]
Hi @stephentoub:

Maybe I didn't make myself so clear, here're some things confusing me a lot:

https://github.com/dotnet/runtime/blob/5aced7eb238ed2dc9e95734ede4be6e11d74dd9c/src/libraries/System.Collections/src/System/Collections/Generic/CollectionExtensions.cs#L10-L13

If as what you said, why does the function above call the overrload one I mentioned in 1st post, return a nullable (TValue?)? It should also return a TValue instead?

I mean from the nullable check, the compiler can only do the static check, so we can make sure any type shouldn't be null in default if necessary, but if for null, maybe a question mark is needed?

>the caller gets to specify the TValue. If they specify a nullable TValue, then it'll be nullable. If they specify a non-nullable TValue, then it'll be non-nullable……

Yes, I know it, however this is just the problem：

1. Since the return value (maybe nullable / non-nullable), how to make a static-checking nullable work properly? 

2. Another issue is:  How can you assign a nullable value (with a question mark) to a non-nullable value type (without a non-nullable mark)? You see in my 1st post, the "return" may return "TValue?" or "TValue", but the accepter is "TValue"....(On the other hand, we don't know what TValue is, maybe struct, class...)?

You see that if you write codes like this, there'll be errors:

```csharp
public static TValue GetValueOrDefault<TKey, TValue>(this IReadOnlyDictionary<TKey, TValue> dictionary, TKey key, TValue defaultValue)
        {
            if (dictionary == null)
            {
                throw new ArgumentNullException(nameof(dictionary));
            }

            TValue? value;
            return value;  //Error here, you cannot convert a TValue? to TValue
        }
```

So how can you dynamically assign a "TValue?" or "TValue" to "TValue" directly in my post, I think it seems something strange :( 

Sorry to bother you, but like to talk with you about more tech on .NET :D

**Comment by stephentoub** [comment]
> If as what you said, why does the function above call the overrload one I mentioned in 1st post, return a nullable (TValue?)? It should also return a TValue instead?

Because there the caller isn't supplying the defaultValue. When they specify it,  it must conform to the nullability of TValue or else there will be a warning.  But in this overload, the default value is null for reference types,  so no matter if TValue is nullable or not,  null can still be returned. 

> So how can you dynamically assign a "TValue?" or "TValue" to "TValue" directly in my post

I don't understand the question,  sorry.  If you're asking why it's possible in L23 for the value to be returned when TryGetValue returns true,  it's because the annotations on TryGetValue tell the compiler that if TValue is not nullable then the out value will also be non-null.

**Comment by MaledongGit** [comment]
>I don't understand the question, sorry. If you're asking why it's possible in L23 for the value to be returned when TryGetValue returns true, it's because the annotations on TryGetValue tell the compiler that if TValue is not nullable then the out value will also be non-null.

@stephentoub: 
Maybe the picture can make me more clear:
![image](https://user-images.githubusercontent.com/52018749/128631712-f7db8d20-48c0-47b6-aae9-0a9b7b94093f.png)

The yellow part returns you a nullable value, the red part returns you a non-nullable value, statically checked through the compiler. But why the green part (non-nullable) can accept both nullable and non-nullable value? On the other hand, since this is a generic type, you don't know whether it's struct or class? This is my confusing :D

**Comment by svick** [comment]
@MaledongGit It can accept a nullable value value *that's known to be not `null`*. If `TryGetValue` returns `true`, then the `out value` will never be `null`, so it can be safely returned from this method.

**Comment by MaledongGit** [comment]
> @MaledongGit I'm not sure if this is what is confusing you, but but can accept a nullable value value _that's known to be not `null`_. If `TryGetValue` returns `true`, then the `out value` will never be `null`, so it can be safely returned from this method.

Yes, it seems you get what I said.
Consider the return type may be true / false, so we have to use "TValue?" instead of "TValue", because we don't know which value will return. As for it, the return type doesn't know which will return either, so it should be "TValue?" better IMO ;)

**Comment by stephentoub** [comment]
> the return type doesn't know which will return either

If TryGetValue returns true,  the function will return a TValue guaranteed to only be null if TValue is nullable. If TryGetValue returns false,  the function will return defaultValue,  which will only be null if TValue is nullable.  Either way,  the return value will only be null if TValue is nullable,  so not having a question mark on the return type is correct,  and adding a question mark to the return type would lose valuable information about the nullability.

**Comment by stephentoub** [comment]
> you don't know which type it will be (struct/class...?) But for struct or class with a question mark, the meaning is quite diff....

If TValue ends up being instantiated with a value type, a question mark in TValue? is simply ignored.  That's how the language defines the semantics.

**Comment by MaledongGit** [comment]
Thanks @stephentoub

>If TValue ends up being instantiated with a value type, a question mark in TValue? is simply ignored. That's how the language defines the semantics.
