### ISSUE TITLE
Unnecessary stack spilling for struct instant property access

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#57055]
### Description
Repro:
```csharp
int Test()
{
    var a = new A().X;
    return 1 + a;
}

struct A
{
    public int X { get; }
}
```

Codegen:
```asm
push rax
xor eax, eax
mov [rsp], rax
lea rax, [rsp]
xor edx, edx
mov [rax], edx
mov eax, [rax]
inc eax
add rsp, 8
ret
```

But if I change the code to:
```csharp
int Test()
{
    var a = new A();
    return 1 + a.X;
}

struct A
{
    public int X { get; }
}
```

The codegen will become:
```asm
mov eax, 1
ret
```

I think JIT should recognize patterns like: `initobj` - `call` - `stloc` - `ldloc`

Also applies to method calls. 

### Configuration
.NET 6 Preivew 6

**Comment by AndyAyersMS** [comment]
Interesting -- I would have guessed const prop could handle this one either way.

**Comment by hez2010** [comment]
Seems that #64171 doesn't fix this issue.

![image](https://user-images.githubusercontent.com/14960345/152687918-3d824e5b-b4b0-44ee-b04a-ab2aed01cd69.png)

**Comment by EgorBo** [comment]
Yes it didn't, but it did improve the case from the tweet.
I had to make it conservative to avoid size regressions so I leave this issue open
