### ISSUE TITLE
HttpClient and MultipartFormDataContent formatting issue

### ISSUE THREAD

**Issue by Daybreakerflint** [dotnet/runtime#57056]
### Description
I have been reverse engineering a Web Interface of a device and I am using the HttpClient class along with MultipartFormDataContent to replicate the upload of a new firmware.

![grafik](https://user-images.githubusercontent.com/45481353/128668339-75cdcc74-a80b-43ee-8e6e-c5f8c642993b.png)

This is how the headers looked`in the first tries. On the left is the one generated in dotnet and the other by the browser Firefox.
The device then tried to redirect to the main landing page.

Then I added quotation marks on the fields `filename`, `csrf_token` and the filename itself `upgrade.tar.gz`
Here is the code and how the header looked in the end:
```csharp
                using (var handler = new HttpClientHandler { UseCookies = false, AllowAutoRedirect = false,  })
                using (var client = new HttpClient(handler) { BaseAddress = baseAddress})
                using (var request = new HttpRequestMessage() )
                {
                    request.RequestUri = new Uri(requestUri);
                    request.Headers.Referrer = baseAddress;
                    request.Headers.Add("Accept", "application/json, text/plain, */*");
                    request.Headers.Add("Accept-Encoding", "gzip, deflate");
                    request.Headers.Referrer = new Uri(URL + "/web_whw/");
                    request.Headers.Add("Connection", "keep-alive");
                    if (!LoginExpired)
                        request.Headers.Add("Cookie", $"sid={SID}; lsid={LSID}");
                    
                    switch (method)
                    {
                        case RequestMethod.POST:
                            request.Method = HttpMethod.Post;
                            request.Content = new StringContent(content, Encoding.UTF8, "application/x-www-form-urlencoded");
                            break;
                        case RequestMethod.FILE:
                            request.Method = HttpMethod.Post;
                            request.Headers.Add("enctype", "multipart/form-data");
                            request.Headers.Add("Origin", URL);

                            if (!File.Exists(content))
                            {
                                response.Body = "";
                                Logger.Debug($"The path '{content}' doesn't point to a file");
                                break;
                            }

                            MultipartFormDataContent form = new MultipartFormDataContent();

                            var tokenContent = new StreamContent(StringToStream(Token));
                            tokenContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
                            {
                                Name = "\"csrf_token\"",
                            };
                            form.Add(tokenContent);

                            var fileStream = new FileStream(content, FileMode.Open);
                            var file = new StreamContent(fileStream);
                            file.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
                            {
                                Name = "\"filename\"",
                                FileName = $"\"{Path.GetFileName(content)}\"",
                            };
                            file.Headers.ContentType = new MediaTypeHeaderValue("application/x-gzip");
                            form.Add(file, "filename", Path.GetFileName(content));

                            request.Content = form;
                            break;
                        case RequestMethod.GET:
                        default:
                            request.Method = HttpMethod.Get;
                            break;
                    }
                    
                    client.Timeout = Timeout;
                    var result = await client.SendAsync(request);

                    result.EnsureSuccessStatusCode();

                    response.Body = await result.Content.ReadAsStringAsync();
                    response.Success = true;
                    Logger.Debug($"{method.ToString("F")} to url={requestUri} successful");
                    Logger.Trace($"Reply: {response.Body}");
                }
```
![grafik](https://user-images.githubusercontent.com/45481353/128669093-7102a97d-165f-4ca8-88d6-6634faca3be2.png)

In the end, there were still quotation marks around the `boundary` value in the header and the device responed that it can't decipher/check the file.

I have tried a couple of different attempts but with no success. I don't know exactly the http standart but I assume that either dotnet or the browser is at fault. What I can say for sure is that the browser works flawlessly but dotnet doesn't.

### Configuration
.NET SDK:
 Version:   5.0.203
 Commit:    383637d63f

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

**Comment by Daybreakerflint** [comment]
I have found a programmatically solution to my problem:
I just set the ContentType manually without the quotation marks.
This works fine with the device at hand. But the quotation marks of the above mentioned fields still needs to be set manually.
```csharp
                            string boundary = Guid.NewGuid().ToString();
                            // ...
                            MultipartFormDataContent form = new MultipartFormDataContent(boundary);
                            // ...
                            form.Headers.ContentType = new MediaTypeHeaderValue("multipart/form-data");
                            var headerParameter = new NameValueHeaderValue("boundary", boundary);
                            form.Headers.ContentType.Parameters.Add(headerParameter);
                            request.Content = form;
```

**Comment by ManickaP** [comment]
RFC allows and in some cases mandates quotes: https://datatracker.ietf.org/doc/html/rfc7578#section-4.1
> and it is often necessary to enclose the
   "boundary" parameter values in quotes in the Content-Type header
   field.
   
More RFC definitions: https://datatracker.ietf.org/doc/html/rfc2046#section-5.1.1
> The grammar for parameters on the Content-
   type field is such that it is often necessary to enclose the boundary
   parameter values in quotes on the Content-type line.  This is not
   always necessary, but never hurts.

If the problem really lies in quotes around boundary parameter then your server is not compliant. You should probably file an issue with whomever implements it.

**Comment by Daybreakerflint** [comment]
I will file an issue with them about the `boundary` parameter.

Is it the same with the mentioned `filename`, `csrf_token` and `upgrade.tar.gz` parameters/values?

**Comment by ManickaP** [comment]
I think that you could find that in the RFC as well. Since this is not a client issue, I'll close this. 
If you find out that we're going against the specification in some of the other cases, please feel free to reopen.
