### ISSUE TITLE
Datetime format issue for "yyyy/MM/dd HH:mm:ss:ffff"

### ISSUE THREAD

**Issue by qiuhaotc** [dotnet/runtime#57050]
### Description

From Aug 5 2021, we have been experiencing the date time format issue. The "/" no longer showing in the results string, was replaced to " ", the format only showing in correct format when we specified the culture to ```CultureInfo.InvariantCulture```

Before, we got: ```2021/08/09 08:38:59:2537```
Now, we got: ```2021 08 09 08:39:09:8465```

### Configuration

Test both on .net core and .net framework

![Format Issue](https://user-images.githubusercontent.com/8034473/128650857-f5f9d763-3431-47ae-b1b8-edb51b714b38.png)

**Comment by wzchua** [comment]
the `DateSeparator` in the currentculture probably got changed to space.

```cs
var cinfo = new CultureInfo(CultureInfo.InvariantCulture.Name);
cinfo.DateTimeFormat.DateSeparator = " ";
var t = DateTime.Now.ToString("yyyy/MM/dd", cinfo);
```

**Comment by qiuhaotc** [comment]
> the `DateSeparator` in the currentculture probably got changed to space.
> 
> I can replicate the behaviour with this:
> 
> ```cs
> var cinfo = new CultureInfo(CultureInfo.InvariantCulture.Name);
> cinfo.DateTimeFormat.DateSeparator = " ";
> var t = DateTime.Now.ToString("yyyy/MM/dd", cinfo);
> ```

Thanks for the information, that must be the reason
