### ISSUE TITLE
Building native components with `-msbuild` fails when VS 2022 is installed

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#57062]
I have latest dogfood version of VS 2022 installed (I also have VS 2019 SxS installed). Trying to run for example `build.cmd -vs CoreCLR.sln` fails. Trying to build any native component with `-msbuild` fails this way:

```console
CMake Error: Could not create named generator Visual Studio

Generators
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
```

I have latest (3.21.1) CMake installed.

**Comment by trylek** [comment]
@jkoritzinsky - as part of my work on merging sections of test build scripts into the MSBuild project I hit this too using the latest codebase - I have your change to <code>gen-buildsys.cmd</code> in my runtime repo clone yet I'm still hitting the following error when trying to build CoreCLR with the <code>-msbuild</code> switch after installing the dogfooding version of VS2022:

<pre>
  BUILD: Commencing build of native components for windows.x64.Release
  BUILD: Using environment: "D:\VS22Pre\VC\Auxiliary\Build\vcvarsall.bat" amd64
  **********************************************************************
  ** Visual Studio 2022 Developer Command Prompt v17.0.0-pre.3.1
  ** Copyright (c) 2021 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'
  BUILD: Regenerating the Visual Studio solution
  Not searching for unused variables given on the command line.
  CMake Error: Could not create named generator Visual Studio 17 2022

  Generators
  * Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                   Use -A option to specify architecture.
    Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                   Optional [arch] can be "Win64" or "ARM".
    Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                   Optional [arch] can be "Win64" or "IA64".
    Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                   Optional [arch] can be "Win64" or "IA64".
...
</pre>

Is that just a local problem on my machine or does some general issue remain even after your primary fix?

Thanks

Tomas

**Comment by jkoritzinsky** [comment]
Hi @trylek,

I believe you need to install a newer version of CMake on your system. It looks like the generator name is correctly resolved (which is what this issue was for), but now you need to install CMake 3.21 (I believe) on your machine for CMake to understand the generator name.
