### ISSUE TITLE
System.IO.Tests.FileStream tests failing intermittently

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#57083]
See https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Aruntime+name%3ASystem.IO.Tests.FileStream

These tests used to be stable -- this may be a product issue.

**Comment by adamsitnik** [comment]
This is being tracked by https://github.com/dotnet/runtime/issues/56894 and https://github.com/dotnet/runtime/issues/56815
