### ISSUE TITLE
[wasm][debugger] Support System.Diagnostics.Debugger attributes

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#57085]
- [x] System.Diagnostics.DebuggerHiddenAttribute
- [x] System.Diagnostics.DebuggerStepThroughAttribute ([#63679](https://github.com/dotnet/runtime/pull/63679))
- [x] System.Diagnostics.DebuggerNonUserCodeAttribute ([#63876](https://github.com/dotnet/runtime/pull/63876))
- [x] System.Diagnostics.DebuggerStepperBoundaryAttribute
- [x] System.Diagnostics.DebuggerBrowsableAttribute ToDo: custom accessors for static and non-static
- [x] System.Diagnostics.DebuggerDisplayAttribute
- [x] System.Diagnostics.DebuggerTypeProxyAttribute
- [ ] System.Diagnostics.DebuggerVisualizerAttribute

**Comment by lewing** [comment]
@ilonatommy @thaystg what are the current thoughts on VisualizerAttribute?

**Comment by ilonatommy** [comment]
Last time I was not able to make VisualizerAttribute work in Console Application and due to lack of reference project I suspended working on it.

**Comment by ilonatommy** [comment]
Use case for `System.Diagnostics.DebuggerVisualizerAttribute` is:
- VS debugger (it does not work for VS Code or other debuggers)
- Target framework: net standard (does not work for .net).

We won't be implementing it, closing.
