### ISSUE TITLE
Annotate unsupported APIs in System.Net.Security

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#57097]
As part of https://github.com/dotnet/runtime/issues/47228 running an analyzer to detect APIs throwing PNSE but have not being annotated with the any of `Obsolete, SupportedOSPlatform, UnsupportedOSPlatform` attributes, we need to annotate them so that developers get warnings when they use them unexpectedly

API | Finding | Reachable platforms | Comment | Suggestion | Location
-- | -- | -- | -- | -- | --
'NegotiateStreamPal.QueryContextClientSpecifiedSpn(SafeDeleteContext)' |  unconditionally throws PNSE | reachable on iOS, OSX, Unix, Android | internal API | Might need unsupported   annotations for these platforms | Common\src\System\Net\Security\NegotiateStreamPal.Unix.cs(32,13)
'CipherSuitesPolicyPal.CipherSuitesPolicyPal(IEnumerable<TlsCipherSuite>)' |  unconditionally throws PNSE | reachable on Windows | Internal API used by pulbic   constructor CipherSuitesPolicy(IEnumerable<TlsCipherSuite>   allowedCipherSuites) | Add Unsupported on windows | System.Net.Security\src\System\Net\Security\CipherSuitesPolicyPal.Windows.cs(12,13)
'NegotiateStreamPal.QueryContextAssociatedName(SafeDeleteContext?)'  | unconditionally throws PNSE | reachable on iOS, OSX, Unix,   Android | internal API | Might need unsupported annotations for these platforms | System.Net.Security\src\System\Net\Security\NegotiateStreamPal.Unix.cs(37,13)
'SslStreamPal.Renegotiate(ref   SafeFreeCredentials?, ref SafeDeleteSslContext?, SslAuthenticationOptions, out byte[]?)' | unconditionally throws PNSE | reachable on Android | unreferenced internal API | Might be a dead code, or else add annotations | System.Net.Security\src\System\Net\Security\SslStreamPal.Android.cs(50,13)
'SslStreamPal.Renegotiate(ref   SafeFreeCredentials?, ref SafeDeleteSslContext?, SslAuthenticationOptions, out byte[]?)' | unconditionally throws PNSE | reachable on iOS, OSX, tvOS | unreferenced internal API | Might be a dead code, or else add annotations | System.Net.Security\src\System\Net\Security\SslStreamPal.OSX.cs(57,13)

cc @jeffhandley @terrajobst @GrabYourPitchforks

**Comment by wfurt** [comment]
The  `Renegotiate` shows up as public `NegotiateClientCertificateAsync` API. 

CipherSuitePolicy works on macOS and Linux with certain versions of OpenSSL
https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy.-ctor?view=net-5.0

**Comment by ManickaP** [comment]
Triage: @jeffhandley How critical is this for 6.0? This is coming in quite hot, 1 week before ZBB.

**Comment by jeffhandley** [comment]
It's OK to punt this out to 7.0.
