### ISSUE TITLE
Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException failing very often

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#57115]
This failed 2600 times since 2021/6/15. That's 40-50 times a day. As far as I can tell, it will fail 100% of the time, although only in OuterLoop. It was written backwards.

@VincentBu could you please have a look to see why we don't already have an issue for this? Is it in a run you don't normally look at?

**Comment by VincentBu** [comment]
@danmoseley I have opened a issue in [#54260](https://github.com/dotnet/runtime/issues/54260). It's really weird that I can't find it by searching key word 'Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException'.

**Comment by danmoseley** [comment]
@VincentBu oh! You're right. Yes, that makes me think it might be a good idea to include the method name of the test (ie "Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException") here in the body of such issues, not just the fully qualified name ("System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException") as Github can't find it otherwise.

**Comment by shimingsg** [comment]
> @VincentBu oh! You're right. Yes, that makes me think it might be a good idea to include the method name of the test (ie "Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException") here in the body of such issues, not just the fully qualified name ("System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException") as Github can't find it otherwise.
@danmoseley ,  I just searched with keyword "ThrowsInvalidOperationException" I got the all issues contains this keyword. if the keywords contains "_" or other simbols, this case could not be searched. I suspected this is an search bug in github.
