### ISSUE TITLE
Generate Deserialize methods as well in System-Text.Json source generator.

### ISSUE THREAD

**Issue by mrange** [dotnet/runtime#57117]
Hi.
I was asked if I had any further feedback on the JSON Serializer in ticket: https://github.com/dotnet/runtime/issues/56995

One thing that came to mind is that in my experiments generating a deserialize method can lead to performance improvements.

I suspect you considered it and for some reason not implemented it but in case you are interested my testing shows an increase in performance with ~30% for a simple object when using generated code rather than metadata driven deserializer. In addition it seems to have positive impact on the memory aspect.

In case you are interested here is my experiment: https://github.com/mrange/T4JsonSerializer

**Comment by layomia** [comment]
Thanks. Yes, we did consider it but were running out of time for 6.0. Dup of https://github.com/dotnet/runtime/issues/55043.
