### ISSUE TITLE
emsdk and runtime workloads should publish workload blobs to the right places, with good paths

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#57154]
In emsdk and (possibly) runtime, the manifest blobs are being dropped from publishing. See the "Workloads" artifact here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1261503&view=artifacts&pathAsName=false&type=publishedArtifacts

This involves a couple things:
- Update ItemsToPushToBlobFeed to include those artifacts
- Set the RelativeBlobPath correctly for those artifacts. The form should be: `emsdk|Runtime/<Full Nuget Version Number>/workloads/<file>`

Note that the full nuget version number is the non-stable version numer. Since some of these artifacts stabilize their version numbers, it's highly important that build to build these paths be unique. It's also important for the hygiene of the storage location that no extra /'s or preceding /'s appear, and that we use the same top level prefixes that other repos do (`component/full version/...`)

**Comment by directhex** [comment]
Just to confirm, @mmitche, the top level should be "emsdk" in your example, i.e. in the "dotnet-emsdk-official" job, there's a "emsdk" artifact push containing a directory "6.0.4.37702", and inside it there should be files?

And which files _precisely_ are you expecting to see in there which currently you aren't? The .wixpack.zip files? Or something else?

**Comment by mmitche** [comment]
The build's artifacts don't matter at all. What appears in PackageArtifacts and BlobArtifacts and the MergedManifest (inside BlobArtifacts) are what matters. These are automatically populated by whatever is in ItemsToPushToBlobFeed before the call to publish. These items tell the push what files need to be published for other builds (or customers) to consume, as well as their relative paths within blob storage.

See aspnetcore's logic for a good template. https://github.com/dotnet/aspnetcore/blob/main/eng/Publishing.props#L58-L85

**Comment by directhex** [comment]
@mmitche how's this https://maestro-prod.westus2.cloudapp.azure.com/1647/https:%2F%2Fgithub.com%2Fdotnet%2Femsdk/latest/graph

**Comment by mmitche** [comment]
I think that is going to be right for stable builds, but it still appears to be missing the workload artifacts.

**Comment by mmitche** [comment]
@joeloff will know for sure, but I think it's all of them.

**Comment by joeloff** [comment]
The MSIs and the corresponding .json files. Some of the JSON files will have GUIDy names (those are for the packs). VS components will have more readable names. For example, from a previous EMSDK build, we'd want

```
0032ac322c79a6fae1abaad560c186d9.json
776d91824f437135c5e73b8650768748.json
792b7cb63ec0e49081d170db33d0609c.json
80be127b0a95e217f38c0d2beca6ec43.json
ff7305e9530353f9890b2d5f2b698cfa.json
Microsoft.Emscripten.2.0.23.Node.win-x64.6.0.0-preview.7.21377.2.msi
Microsoft.Emscripten.2.0.23.Python.win-x64.6.0.0-preview.7.21377.2.msi
Microsoft.Emscripten.2.0.23.Sdk.win-x64.6.0.0-preview.7.21377.2.msi
microsoft.net.sdk.emscripten.6.0.json
Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-preview.7.21377.2-x64.msi
Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-preview.7.21377.2-x86.msi
```

**Comment by directhex** [comment]
OK. https://maestro-prod.westus2.cloudapp.azure.com/1647/https:%2F%2Fgithub.com%2Fdotnet%2Femsdk/latest/graph is good?

**Comment by mmitche** [comment]
Getting close, I believe you want to omit "Runtime", and then I believe @joeloff wants the items that were in the Workload AzDO artifact to be under a separate directory so they are easy to harvest for insertion. So putting them under a "workloads" relative blob dir.

E.g. `emsdk/6.0.0-rc.1.21412.5/workloads/61fa459e77618622b967a092751fbf18.json`

**Comment by joeloff** [comment]
+1 for what @mmitche said. For now we'll do this manually, but having a single artifact we can download will simplify things and make it easier once we try to automate this in the staging pipeline since we'd want to push emsdk and runtime into separate VSDROP blobs

**Comment by directhex** [comment]
```
emsdk/6.0.0-rc.1.21412.8/Microsoft.Emscripten.2.0.23.Node.win-x64.6.0.0-rc.1.21412.8.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21412.8-x86.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21412.8-x64.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21412.8-arm64.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/Microsoft.Emscripten.2.0.23.Sdk.win-x64.6.0.0-rc.1.21412.8.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/Microsoft.Emscripten.2.0.23.Python.win-x64.6.0.0-rc.1.21412.8.msi.wixpack.zip
emsdk/6.0.0-rc.1.21412.8/workloads/Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21412.8-x64.msi
emsdk/6.0.0-rc.1.21412.8/workloads/microsoft.net.sdk.emscripten.6.0.json
emsdk/6.0.0-rc.1.21412.8/workloads/Microsoft.Emscripten.2.0.23.Sdk.win-x64.6.0.0-rc.1.21412.8.msi
emsdk/6.0.0-rc.1.21412.8/workloads/Microsoft.Emscripten.2.0.23.Python.win-x64.6.0.0-rc.1.21412.8.msi
emsdk/6.0.0-rc.1.21412.8/workloads/Microsoft.Emscripten.2.0.23.Node.win-x64.6.0.0-rc.1.21412.8.msi
emsdk/6.0.0-rc.1.21412.8/workloads/f3e1c7f5e6720c4146709baed25546de.json
emsdk/6.0.0-rc.1.21412.8/workloads/8413033a47ff161892bc5c3cc056907e.json
emsdk/6.0.0-rc.1.21412.8/workloads/624f0c732eaa4ff18aa608e20f9f1070.json
emsdk/6.0.0-rc.1.21412.8/workloads/4a6f447ae040913f7843663ea1056bfe.json
emsdk/6.0.0-rc.1.21412.8/workloads/3ab1ec7f0584f1735a9c371995a85148.json
emsdk/6.0.0-rc.1.21412.8/workloads/Microsoft.NET.Workload.Emscripten.Manifest-6.0.100.6.0.0-rc.1.21412.8-x86.msi
```

now?

**Comment by directhex** [comment]
https://github.com/dotnet/emsdk/pull/60 is up, done for today.

**Comment by mmitche** [comment]
It's gorgeous!!

**Comment by directhex** [comment]
I'm trying to figure out how to do it on Runtime, but that has a rather, uh, different repo layout in this regard. No publishing.props, etc. Just trying to find a good insertion point for making the requested changes

**Comment by mmitche** [comment]
runtime does an explicit call to PushToAzureDevOpsArtifacts in `src/installer/prepare-artifacts.proj` to publish its blob artifacts. This may be changing (@riarenas to comment). I'd look there first.

**Comment by riarenas** [comment]
Yeah, prepare-artifacts.proj is the right place to put this today. I'm moving a lot of what's in there to publishing.props, but that's still underway and I'll make sure that the changes for this are ported as well.

**Comment by joeloff** [comment]
@directhex Are both runtime and SDK on the latest set of Arcade tools? I pushed a number of fixes into the tooling last week

**Comment by directhex** [comment]
Not sure. Can't check. A truck took out my Internet

**Comment by joeloff** [comment]
Also, what's the plan for building workloads for different SDK feature bands. Usually most repos would branch once unlike the SDK where we can have multiple branches consuming the same runtime for different feature bands. Only reason I'm asking is that we'd need to ensure that if you're building workloads for different feature bands in the same runtime branch, we might want to consider adding an additional discriminator in the publishing path that includes the feature band so that we don't pull 6.0.1xx abd 6.0.2xx workloads into the same VSDROP as that would push both into the same VS release.

**Comment by mmitche** [comment]
Yeah, I recommend adding a differentiator after workloads (6.0.100, 6.0.200, etc.)

**Comment by akoeplinger** [comment]
Opened a PR for the dotnet/runtime side of the changes: https://github.com/dotnet/runtime/issues/57154
