### ISSUE TITLE
System.IO Symbolic Link work planned for .NET 7

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#57205]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
We introduced new features for symbolic links in .NET 6 (#51605). We will deliver further capabilities and enhancements for symbolic links during .NET 7.

## Planned for .NET 7

- [x] #29940
- [x] #38824

## Backlog (roughly in priority order)

- [ ] #53577
- [ ] #52666
- [ ] #58612
- [ ] #52908
- [ ] #1908
- [ ] #34363
- [ ] #62975
- [ ] #20874

**Comment by wegylexy** [comment]
Creating symbolic links without developer mode or elevation fails silently. Should it throw that it is unprivileged?

**Comment by iSazonov** [comment]
It throw https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs#L62-L67

**Comment by wegylexy** [comment]
@iSazonov Tested on Windows 10 21H1 19043 without Developer Mode with .NET 6 RTM; it does not throw.

**Comment by adamsitnik** [comment]
> Tested on Windows 10 21H1 19043 without Developer Mode with .NET 6 RTM; it does not throw.

cc @carlossanlop @Jozkee

**Comment by jeffhandley** [comment]
Closing this issue in favor of #64596. The items from this epic were merged into that one.
