### ISSUE TITLE
Developers should be guided away from more obsolete APIs in .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#57207]
Continuing on the momentum from #39269, #46767, and #33360, .NET 7 should guide developers away from more APIs that are considered obsolete but haven't yet been annotated as such.

## Planned for .NET 7
- [x] #42857
- [x] #59061
- [x] #50535 (PR #59734)

## Backlog (in roughly priority order)
- [ ] #889
    - This requires proposing replacement APIs for all places `StringDictionary` is used in public APIs (including aspnetcore)
- [ ] #32954
- [ ] dotnet/designs#147
- [ ] #39235

## Definition of Done

Each obsoletion needs to have the following Definition of Done applied.

* Pre-announce the upcoming breaking change to partner teams using our breaking change DL at least 2 weeks before merge
* Use the [Obsoletions.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Obsoletions.cs) file to define the message and diagnostic ID
* Add the obsoletion to the [list of diagnostics](https://github.com/dotnet/runtime/blob/master/docs/project/list-of-diagnostics.md)
* Create the breaking change document issue
* Announce the breaking change to our partner teams using our breaking change DL upon merge
* Register the aka.ms link for SYSLIBxxxx obsoletions (see @jeffhandley)

**Comment by AraHaan** [comment]
I think obsolete types should face the same fate as ``BinaryFormater`` and be deleted in .NET 8.
