### ISSUE TITLE
Libraries continuous improvement work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#57209]
## Summary
With each release of .NET, we improve and grow the core libraries. Below are the continuous improvement epics created by libraries area for .NET 7.

#### Meta / Infrastructure
- [ ] #43849
- [ ] #44969
- [ ] #65260

#### Microsoft.Extensions
- [x] #64015

#### System.Buffers
- [ ] #64598

#### System.Collections
- [x] #64599

#### System.Console
- [x] #64487

#### System.Diagnostics
- [x] #62027

#### System.Diagnostics.Process
- [x] #64600

#### System.IO
- [x] #64596

#### System.IO.Compression
- [x] #62658

#### System.Linq
- [x] #64601

#### System.Numerics
- [ ] #47244
- [x] #63548

#### System.Reflection
- [ ] #44655

#### System.Runtime
- [ ] #64603

#### System.Security
- [ ] #64488

#### System.Text.Json
- [x] #63762

#### System.Text.RegularExpressions
- [x] #62758

#### System.Xml
- [x] #64602

**Comment by carlossanlop** [comment]
@jeffhandley Should I add the Compression uber issue to your list here?: #62658

**Comment by danmoseley** [comment]
Closing this as it has served its purpose. cc @jeffhandley
