### ISSUE TITLE
Failing to build coreclr for osx-arm64

### ISSUE THREAD

**Issue by odhanson** [dotnet/runtime#57218]
I am working on preview 7 tag:
`git checkout tags/v6.0.0-preview.7.21377.19`

Then running the command (on a MacOS x64 machine):

`src/coreclr/build-runtime.sh -arm64 -debug`

Will produce the following error:

```
/Users/runner/work/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:4629:6: error: "Don't know how to get hi-res current time on this platform"
    #error "Don't know how to get hi-res current time on this platform"
```

This is consistent on a few machines I have been testing. Am I doing anything wrong ?

**Comment by AaronRobinsonMSFT** [comment]
@odhanson I am able to successfully build on an ARM64 OSX using the above command. I will try on my amd64 machine next.

**Comment by AaronRobinsonMSFT** [comment]
I can confirm I get the same failure on AMD64 OSX. Both of the following commands failed:

`./src/coreclr/build-runtime.sh -arm64 -debug`

`./build.sh clr -a arm64 -c Debug --cross`

**Comment by odhanson** [comment]
Exactly.  I wonder how the automation build is working ?

**Comment by ViktorHofer** [comment]
@jeffschwMSFT can someone on your team please take a closer look?

**Comment by jeffschwMSFT** [comment]
@mangod9

**Comment by janvorli** [comment]
I have originally made the changes to enable cross build for arm64 macOS on x64 (and vice versa).
When building coreclr for arm64 on macos x64, you also need to pass in the -cross flag:
`src/coreclr/build-runtime.sh -arm64 -debug -cross`
That works correctly. 
As for the global build.sh script, e.g. this works as well on my x64 macOS:
`./build.sh clr+libs -c Release -rc Checked -arch arm64 -cross`

**Comment by odhanson** [comment]
Thanks, I guess I missed the -cross option. 
Closing the issue
