### ISSUE TITLE
Multiple .NET Core DAC (Data Access Component) debugger runtimes

### ISSUE THREAD

**Issue by dmex** [dotnet/runtime#57222]
Hello,

.NET Core is currently shipping two somewhat identical versions of the same DAC runtime: 

`"\dotnet\shared\Microsoft.NETCore.App\5.0.8\mscordaccore.dll"`
`"\dotnet\shared\Microsoft.NETCore.App\5.0.8\mscordaccore_x86_x86_4.700.21.31506.dll"`

The 32bit versions seem to be identical while the 64bit versions differ in file sizes:

![image](https://user-images.githubusercontent.com/1306177/129075542-49680e71-f732-4614-af1d-7e3c93a24747.png)

Are there any major differences between these versions of DAC?

SOS and Windbg are using the first binary (ICLRDataTarget/IXCLRDataProcess), Profilers and `debugshim` (ICLRDebugging) are using the latter `name_host_target_version.flavor.dll` while ClrMD is using both the former and latter. The runtime shim also returns this via `FormatLongDacModuleName` here:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/debug/shim/debugshim.cpp#L631-L726

ClrMD exports both filenames via public interfaces:
https://github.com/microsoft/clrmd/blob/124b189a2519c4f13610c6bf94e516243647af2e/src/Microsoft.Diagnostics.Runtime/src/DataTargets/DacInfo.cs#L15-L30

Also here via public interface via these functions:
`ClrInfoProvider.GetDacFileName();`
`ClrInfoProvider.GetDacRequestFileName();`
https://github.com/microsoft/clrmd/blob/124b189a2519c4f13610c6bf94e516243647af2e/src/Microsoft.Diagnostics.Runtime/src/DataTargets/ClrInfoProvider.cs#L79-L108

It doesn't make much sense to have two identical DLLs shipping with the runtime providing the exact same functionality so should we expect one of these files to vanish at some point? Which version of DAC should third parties be using going forward?

**Comment by josalem** [comment]
CC @mikem8361 @hoyosjs

**Comment by hoyosjs** [comment]
The reasons for this are historical: runtime and DAC need to match. The one with the shorter name is meant for consumption in live debugging as it lives next to the DLLs from the runtime. The other one is used as there are scenarios where it needs to be fetched from the symbol server. Some of these are for debugging dump and some other cases (remote cross architecture debugging and such). As long as the short name DAC matches the version of the runtime being used, feel free to use that one.

**Comment by dmex** [comment]
> The other one is used as there are scenarios where it needs to be fetched

IMO this stuff should be merged into one DLL at some point to reduce complexity. The other reason to consider the removal of the duplicate DAC... That file is about 1MB right now so merging it would also remove 1TB bandwidth/load on the download servers for every 100,000 users downloading/installing .NET Core.

> As long as the short name DAC matches the version of the runtime being used, feel free to use that one.

@hoyosjs 

We've been using mscordacwks.dll for > 12 years and updating stuff for mscordaccore.dll was confusing seeing the runtime split the same features/usage between those two DLLs across the framework and no documents or comments describing the reasoning/usage for one or the other. Thanks for clarifying 👍

**Comment by hoyosjs** [comment]
Both existed on framework too. The usage is still the same. I will try to take a look at deleting it of the shared framework in 7.0 if there's time for it.
