### ISSUE TITLE
[API Proposal]: Attribute required by library authors to disable trimming on a specific type and all derived types

### ISSUE THREAD

**Issue by TheCakeMonster** [dotnet/runtime#57231]
### Background and motivation

There are certain scenarios where libraries are built to use reflection to achieve functionality that is not otherwise possible. One such example exists in a library I use, in which reflection is used to call private methods on types derived from base classes defined in the library, where the derived types are created by other developers in their own assemblies outside of the library. This enables the library to call methods with loosely defined signatures (where the types and number of parameters are not restricted by a contract.)

We are concerned that, if trimming is applied to classes on which this is performed, the private methods on people's derived types will be removed and the runtime signature searching we do will fail. This will break people's applications in ways that they may not understand.

Trimming is applicable to the vast majority of the library, but should not be performed on a small handful of types within it. What we need, then, is a way to disable trimming on these few, specific types, and all types derived from them.

At the moment, the only option is to disallow trimming on the whole of the library, as we cannot indicate those types to which trimming must not be applied.

We would like instead to be able to apply a new attribute to those few types in the library against which this dynamic behaviour is performed, asking the linker not to attempt to trim them. In other words, the new attribute acts like a switch, disabling any form of member level trimming at all on those specific types, but allowing trimming to be applied to the rest of the library.

I had hoped that the DynamicallyAccessedMembersAttribute would offer this capability, but it does not. Additional code would be needed to get DynamicallyAccessedMembersAttribute to understand that a type is subject to complex enough reflection that it will not be able to reason about it. This is likely to be a problem encountered by a number of library authors using advanced reflection scenarios.

My recommendation is to add an attribute that tells the linker to perform no trimming on the type to which it is applied. This attribute would target classes. However other authors may have reasons for being able to apply this to structs.

### API Proposal

```C#
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Class, Inherited = true)]
    public class NotTrimmableAttribute : Attribute
    {
    }
}
```     

The attribute itself is only half of the change. The linker would need to be modified to look for types to which it has been applied, and bypass trimming on any such type. The necessary changes could be shortlisted by looking for usage of the DynamicallyAccessedMembersAttribute, as this also affects trimming, but in a much more complex way.

### API Usage

```C#
// Define a type that is not to be trimmed
[NotTrimmable]
public class ClassUsedInComplexReflectionScenarios
{
    private void PerformAction(string parameterA, int parameterB)
    {
        // Code that is initiated by the framework goes here
    }
}
```     

### Risks

Naming is hard; the largest risk here is the choice of an attribute name that does not clearly define the purpose of the attribute. The problem is that the DynamicallyAccessedMembersAttribute is an attribute that people might expect to have this behaviour - as I did when I raised https://github.com/dotnet/runtime/issues/57140

However, we should be able to manage this risk with documentation.

**Comment by TheCakeMonster** [comment]
No, it is effectively done by passing a the name of the type in as a parameter to an API, sometimes from a separate process. The name of the type is not visible to the trimmer to reason about. I have tried DynamicallyAccessedMembers, and it's unable to solve the problem because of insufficient access to the type name.

There are a number of reflection-based scenarios where the trimmer will not be able to gather enough information to do the right thing. For example the name of a type being accessed by reflection might come from a database, or a configuration file, or via an external API.

This attribute is designed to turn off trimming when the type name is not available for static analysis.

**Comment by Sergio0694** [comment]
Wondering if this is at least partially related to https://github.com/dotnet/runtime/issues/50333, given that in both cases the issue stems from some additional methods from external assemblies being invoked through reflection from some other library at runtime, without a way for either library authors nor consumers to easily annotate them to indicate the exact dependency? 🤔

I know the two issues are not exactly the same (eg. in the linked one the code is generate by a source generator), but there seem to be some similarities at a glance that I'd be curious to know whether they'd have a common solution for both of them (or one possibly just being a subset of the other) 😄

**Comment by TheCakeMonster** [comment]
@Sergio0694 I think that's a fair comment. I think what I am proposing is much simpler than in that issue though. My attribute simply states "please leave me alone". I am suggesting that there is no need for huge amounts of complexity, in certain scenarios. The attribute would allow a developer to say simply "I know what I am doing"

This covers complex edge cases that we don't need to think too hard about at this stage. It's a catch-all when none of the more sophisticated solutions that have been developed are going to work. Sometimes, developers just need to opt out.

**Comment by TheCakeMonster** [comment]
I suppose I should say here that I know that what I am recommending is already largely possible via XML, if you manually create an XML file of a very specific name. Giving a coder the opportunity to do the same thing via code seems a reasonable approach, preferable to those people who think code first.

**Comment by MichalStrehovsky** [comment]
We've been avoiding adding facilities that allow making something an unconditional root. The problems are twofold:

* It disallows trimming. Before you say "that's the point", consider an assembly that has many types, but only some of which are related to the thing marked `[NonTrimmable]`. An app might be using part of the assembly that doesn't care about the `[NonTrimmable]` part, but because of `[NonTrimmable]`, we have to keep those part anyway - there's no way to **connect the thing that relies on the `[NonTrimmable]` part (the thing that actually does `Type.GetType`) with the types marked `[NonTrimmable]`**.
    * Trimming is such a mysterious things to most people that I can see how people for whom `[DynamicallyAccessedMembers]` would be a good solution would go for `NonTrimmable`. The `DynamicallyAccessedMembers` solution is actually fully trimmable - if the type is not referenced by anything, we're going to remove it, with all members. Also if nobody calls object.GetType on an instance of such type (or subtype), we're still going to trim the members.
* The other problem is that we try to go for annotations that not just keep things, but also make it possible to prove trimming correctness. The `[DynamicallyAccessedMembers]` on type doesn't just keep the members - it also helps dataflow analysis figure out the `GetMethods` call is safe. If the `Base` type wasn't annotated, trimming would produce a warning that methods could have been stripped. With `[NonTrimmable], there's going to be a `Type.GetType` call in the app that produces trimming warnings that need to be suppressed. Suppressed warnings may rely on invariants that will no longer hold as the library evolves (e.g. what if someone uses it for a type that doesn't derive from the `[NonTrimmable]` type).

As you say, this is achievable through XML or through the DynamicDependency attribute. I'm a bit weary of adding more first class support for this pattern.

**Comment by TheCakeMonster** [comment]
I understand your reticence, but I think there is a risk in the opposite direction. I think people are going to end up turning off trimming at the assembly level if they don't have the tools they need to make it work for them. Rather than making trimming more effective, this makes it far less effective.

The fact that this can be done with XML is good for scenarios where the developer doesn't own the code on which trimming behaviour needs to be adjusted. However. using XML is somewhat unsatisfactory when the code is owned by the developer. The XML is somewhat out of sight of the code. Each time an application is changed - such as a new type being added that is impacted by trimming, it will be necessary to remember to change the XML file, as well as write the code. That is a risk for people, and again is likely to encourage them to turn it off.

**Comment by jkotas** [comment]
The primary risks with trimming in complex reflection scenarios are in functionality breaks and too complex models that are hard to reason about.

I think it is actually perfectly fine workaround to just turn off trimming at assembly level in complex reflection scenarios that were not designed with trimming in mind. Very simple and it is typically not giving up much of binary size savings anyway.

**Comment by TheCakeMonster** [comment]
@jkotas It depends. I wonder if it is important to separate types of code into different categories.

1. End user code. I agree that trimming on end user code will have a limited effect. They write their code specifically to do the job in hand. They are unlikely to write a lot of code that isn't needed or actively used. However, to be fair, it even that depends on the business model. If a company has a single application then trimming is likely to offer little benefit. However, there is plenty of scope for more advanced teams who segregate their UI for different user audiences, or different usage scenarios, but share common business and data access tiers. In that situation, trimming might easily remove 50% or more of the code they have produced when they build a specific UI.
2. Library code. This is quite different. Library authors like to offer advanced functionality in lots of different directions, catering for advanced usage scenarios that a limited subset of developers might use. Libraries can get quite bog quite quickly, and the use of any individual feature (and the associated set of classes) can be relatively small for a lot of users.

To everyone following this thread, the feature I am suggesting is very much aimed at library authors. Library authors tend to be more advanced in their understanding of the platform by their very nature - they have matured to a point where they think they have something to offer the wider community. As a result, their experience might help them make good choices about more advanced features.

**Comment by jkotas** [comment]
> Library authors like to offer advanced functionality in lots of different directions

I agree. It does not scale to add declarative built-in support (ie attribute) for each of these directions. There is very large variety of patterns used by existing reflection-heavy libraries.

The solution we have for that are source generators. The source generators can generate code to keep the exact types and methods around for trimming. Or even better, the source generator can short-circuit use of reflection to make the application startup and run faster. We have used both these approaches to make System.Text.Json library trimming friendly.

**Comment by TheCakeMonster** [comment]
@jkotas Source generators are yet more complexity. Whilst I have considered that as an approach, I wonder if that is really the right solution here.

It feels like it is getting increasingly hard to do a simple thing when it comes to trimming. I have to wonder how much code it is appropriate for people have to write to maintain the functionality they had before a feature was introduced. I can say with confidence is that a source generator isn't one line of code to add.

If we aren't careful, we are at risk of alienating an important part of the community. If library authors are destined to have less ability to control trimming on their libraries than the end developers who use their work, then being a library author could become unviable.

**Comment by jkotas** [comment]
There are going to be libraries that do not work well with trimming by design. There are going to be libraries where the authors choose to not deal with the additional complexity of implementing trimming friendly mode. Both of these options are perfectly valid. 

The trimming compatibility is not a mandatory feature for library authors to implement. It is similar to cross-platform compatibility that is not mandatory either. Number of .NET libraries out there do not work well on non-Windows.

I expect that we will see new set of libraries to emerge that will offer trimming and AOT friendly alternatives to the existing reflection heavy libraries. For example, https://github.com/pakrym/jab
