### ISSUE TITLE
Relocation strategy for mscorlib.ni.dll

### ISSUE THREAD

**Issue by papaslavik** [dotnet/runtime#5723]
Testing a trivial application on Linux x64 with mscorlib.ni.dll reveals that a large amount of memory is counted as Private_Dirty after PEImageLayout::ApplyBaseRelocations() is called.

7f3dc749e000-7f3dc7a53000 rw-p 00001000 08:01 7871311                    /home/wvoquine/coreclr-demo/runtime/mscorlib.ni.dll
Private_Dirty: 2820 kB 

7f3dc7a74000-7f3dc81ff000 r-xp 005d7000 08:01 7871311                    /home/wvoquine/coreclr-demo/runtime/mscorlib.ni.dll
Private_Dirty: 1012 kB 

Are there any current plans to reduce the relocation impact to dirty memory?

**Comment by jkoritzinsky** [comment]
@jkotas should this issue still be open?
