### ISSUE TITLE
Single-file apps are not signable on MacOS in P7+

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#57242]
I tried this locally, and it looks like it works properly in P6 and broke in P7.

**Comment by agocke** [comment]
Ah, I bet I know what's wrong here -- we updated _CreateAppHost to sign on Mac, but I bet _CreateAppHost runs before bundling, so the apphost is signed, which messes with the layout, and the resulting binary is malformed. Runnable, but not signable.

cc @mateoatr

**Comment by agocke** [comment]
@mateoatr After thinking about this, I think there are two fixes we need to make

1. Don't sign the bundle in `_CreateAppHost` if single-file publish is enabled
2. Add a reusable `_MacOSCodesign` task or target that can be called after `GenerateBundle` in the case that `PublishSingleFile` is true.

**Comment by mateoatr** [comment]
That sounds about right. I'll make the changes.
