### ISSUE TITLE
[Generic Math]: Add some non-generic base interfaces to the current generic math interfaces.

### ISSUE THREAD

**Issue by Summpot** [dotnet/runtime#57264]
### Background and motivation

In c#, efficiently judging whether an object is a number is difficult.
With the arrival of Generic math, I saw a little light.
I can't help but wonder if I can write code like this.
``` csharp
if(obj is INumber){
    //do something
}
```
But when I actually handed it, I was disappointed.
There is only one `INumber<TSelf>` interface.
Obviously I don't need to judge whether it is a number even when I know what type of `obj` is.
So I hope to add non-generic base interfaces to all generic interfaces in Generic Math to improve the efficiency of pattern matching.

### API Proposal
Use INumber as an example.
```C#
namespace System
{
     public interface INumber<TSelf>
        : INumber
          IAdditionOperators<TSelf, TSelf, TSelf>,
          IAdditiveIdentity<TSelf, TSelf>,
          IComparisonOperators<TSelf, TSelf>,   // implies IEquatableOperators<TSelf, TSelf>
          IDecrementOperators<TSelf>,
          IDivisionOperators<TSelf, TSelf, TSelf>,
          IIncrementOperators<TSelf>,
          IModulusOperators<TSelf, TSelf, TSelf>,
          IMultiplicativeIdentity<TSelf, TSelf>,
          IMultiplyOperators<TSelf, TSelf, TSelf>,
          ISpanFormattable,                     // implies IFormattable
          ISpanParseable<TSelf>,                // implies IParseable<TSelf>
          ISubtractionOperators<TSelf, TSelf, TSelf>,
          IUnaryNegationOperators<TSelf, TSelf>,
          IUnaryPlusOperators<TSelf, TSelf>
        where TSelf : INumber<TSelf>
     {
          //...
     }

     public interface INumber
     {
          //...
     }
}
```     

### API Usage

```C#
// When judging whether an object is a number.
if(obj is INumber){
    //Do something only can do with a number.
}
```

**Comment by alexrp** [comment]
What is the use case here? It's not immediately obvious to me what the `Do something only can do with a number` part would be without also knowing `TSelf`.

**Comment by Summpot** [comment]
> What is the use case here? It's not immediately obvious to me what the `Do something only can do with a number` part would be without also knowing `TSelf`.

For example, when doing some custom serialization work, we don’t care about the length of the number. We just want to find something to represent a number. It is not the best choice to use `object` even when we know it is a number. Just a compromise.
@alexrp

**Comment by Summpot** [comment]
And I think these non-generic interfaces should be added even just for consistency. Almost all .net generic interfaces have corresponding non-generic interfaces, don’t they? 
@alexrp

**Comment by alexrp** [comment]
Many of the non-generic interfaces are considered a mistake / legacy leftover from .NET 1.0 days. Most of them would not be here if .NET was redesigned from scratch.

**Comment by svick** [comment]
> For example, when doing some custom serialization work, we don’t care about the length of the number. We just want to find something to represent a number. It is not the best choice to use `object` even when we know it is a number. Just a compromise.

In what way are you going to treat an `INumber` differently? Can you provide a specific example?

**Comment by Summpot** [comment]
> In what way are you going to treat an `INumber` differently? Can you provide a specific example?

Consider that there is a method in BinaryPrimitives whose signature is like this.
``` csharp
public static IUnsignedNumber ReadNumberLittleEndian/ReadNumberBigEndian(ReadOnlySpan<Byte> source);
```

**Comment by svick** [comment]
@Summpot 

> Consider that there is a method in BinaryPrimitives whose signature is like this.
> 
> ```cs
> public static IUnsignedNumber ReadNumberLittleEndian/ReadNumberBigEndian(ReadOnlySpan<Byte> source);
> ```

I don't see how that would work:

1. Generic math doesn't work on interfaces themselves, it only works on generic types constrained to interfaces. And you have no way of getting that here.
2. It would have to allocate on every call. That goes against the philosophy of how .Net has been evolving recently.
