### ISSUE TITLE
System.Threading.Channels.ChannelOptions.SingleWriter is not used?

### ISSUE THREAD

**Issue by krispenner** [dotnet/runtime#57265]
I was trying to understand what the `SingleWriter` property on the `ChannelOptions` class did in regards to concurrent access and locking within a `Channel` but it appears to be ignored from the source code referenced below. Can anyone please confirm that is the correct source code or am I looking in the wrong place?

https://github.com/dotnet/runtime/blob/c8dc49e6e7a654cc730a18c209513561f560c1ae/src/libraries/System.Threading.Channels/src/System/Threading/Channels/Channel.cs#L62

Also, `ChannelOptions.SingleReader` seems to only be used for unbounded channels, which many docs I read say to avoid due to possible memory exceptions. However, is it safe to assume that the `SingleConsumerUnboundedChannel` is more performant that the `BoundedChannel` when there is only one reader?

If the above is correct, would it make sense to move `SingleReader` from the base `ChannelOptions` class to the `UnboundedChannelOptions`, since it is only applicable to unbounded channels and avoids any confusion? Also the `SingleWriter` property could be dropped completely if it is not used as this is misleading. Unless of course this is used elsewhere that you can point me to please. Regardless, I'm mostly just interested in understanding how these two properties affect the underlying channel.

Thank you.

**Comment by stephentoub** [comment]
They are available for implementations to use to optimize, enabling the developer to express their intent.  Right now with the built-in implementations, it's only used in CreateUnbounded. That could change in the future. 

> However, is it safe to assume that the SingleConsumerUnboundedChannel is more performant that the BoundedChannel when there is only one reader?

Yes, unbounded channels in general have less overhead than bounded. 

> would it make sense to move SingleReader from the base ChannelOptions class to the UnboundedChannelOptions,

No.  a) it's there for a developer to express their intent,  it's an implementation detail whether an implementation uses that constraint to optimize,  other of our implementations might use it in the future,  and other implementations outside of the library may already be doing so.  And b) that would be a breaking change.
