### ISSUE TITLE
[.NET 6] Improving the default Random.NextInt64 performance for derived classes

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#57272]
### Description

Consider a pre-.NET 6 library used from .NET 6 that has a derived `Random` class but doesn't override the `NextInt64` methods ([example](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/Development/KGySoft.CoreLibraries/Security/Cryptography/SecureRandom.cs)).

As such a class has no overridden `NextInt64` methods, the internal `Net5CompatImpl` [implementation](https://github.com/dotnet/runtime/blob/dcd1e03ab42ea52d488f6874f40403f5f6069818/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L104) kicks in, whose private [`NextUInt64`](https://github.com/dotnet/runtime/blob/dcd1e03ab42ea52d488f6874f40403f5f6069818/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L145) method ends up calling the `Next()` method 8 times for each byte in the `ulong` sample to be generated.

### Proposed fix

Please consider changing the current `NextUInt64` method like this:

```cs
private unsafe ulong NextUInt64()
{
    Span<byte> resultBytes = stackalloc byte[8];
    _parent.NextBytes(resultBytes); // instead of: NextBytes(resultBytes);
    return BitConverter.ToUInt64(resultBytes);
}
```

The proposed change above calls the possibly overridden `NextBytes(Span<byte>)` overload, which gives a chance for a pre-.NET 6 class to fill up the buffer much more efficiently. If `NextBytes(Span<byte>)` is not overridden either, then this eventually calls the current `Net5CompatImpl` [implementation](https://github.com/dotnet/runtime/blob/dcd1e03ab42ea52d488f6874f40403f5f6069818/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L164) with those repeated `Next` calls.

### Risks

This will produce different results from the current implementation but since .NET 6 is not released yet I don't think it's a real issue.

**Comment by stephentoub** [comment]
This would help the cited case (potentially significantly), but hurt multiple other cases:
- Calling NextInt64 on a `new Random(seed)`
- Calling NextInt64 on a `new DerivedRandom()` that doesn't override `NextBytes(Span<byte>)`
as now we're adding an additional virtual call to the parent's NextBytes.  I tried it out locally, and while there's some noise, it seems to have a negative impact to the tune of around 3%. And if someone has overridden the recently introduced `NextBytes(Span<byte>)`, then I expect there's a good chance they will also end up overriding the new methods, and so the delegation pattern won't matter.

I'm inclined to say that the current implementation is making the right tradeoffs.

**Comment by stephentoub** [comment]
That was discussed previously but dismissed due to it not providing good enough distribution.

**Comment by koszeggy** [comment]
Ah, ok. At least, I tried it. :)

I still hope that 3% degradation on the legacy path (which actually has no baseline from any previous version that could be worse) is worth for a drastic improvement. Which of course will be out of question when everyone will have released their fixed libraries with the missing overrides...

**Comment by stephentoub** [comment]
> I still hope that 3% degradation on the legacy path (which actually has no baseline from any previous version that could be worse) is worth for a drastic improvement.

It's not legacy. This applies to `new Random(42)`.  A type derived from `Random` can address the deficiency better than we can by simply overriding the new method, and it's only an issue to begin with if it's already overridden newer methods on the type.  Code using `new Random(42)` has no recourse.

**Comment by stephentoub** [comment]
Thank you for the suggestion.

**Comment by koszeggy** [comment]
@stephentoub: Sorry for bothering again (after the issue is closed) but suddenly an idea came to my mind, which cures also another (maybe more serious) issue: when creating a derived random class, the ~legacy~ compatible algorithm _always allocates and initializes `_seedArray`, even if it is never needed_ (eg. when all methods are overridden, and base is never used).

`Net5CompatImpl` is now used for two use cases:
1. When we use a seed (`new Random(42)`)
2. When we have a derived `Random` class (`new DerivedRandom()`)

Actually case 2.) could use a 3rd `ImplBase` implementation (eg. `LazyNet5CompatImpl`?), which is very similar to `Net5CompatImpl`, but
* Its constructor does nothing. `_seedArray` is initialized on demand in `InternalSample`
* Its `NextUInt64()` can call `_parent.NextBytes(resultBytes)` because it now has no negative impact on case 1.)

Will you reopen the issue?
Or, should I create a new one, addressing the potentially unnecessary allocation/initialization issue?
Or, should I maybe prepare a pull request and reference this issue?

**Comment by stephentoub** [comment]
I'm currently experimenting with something similar, having a dedicated implementation for the `new Random(int)` case, which then necessarily means there's a dedicated implementation for the `new DerivedRandom(...)` case.  My goal is to avoid the virtual dispatch in the former, but a small tweak could likely then enable lazy-init of the _seedArray as you suggest.

**Comment by stephentoub** [comment]
(I was going to just put up a PR, assuming the numbers panned out, but I can re-open this to track.)
