### ISSUE TITLE
wasm-tools workload install fails due to unsigned package

### ISSUE THREAD

**Issue by johngsandiford** [dotnet/runtime#57296]
After installing .NET 6 preview 7 (via Visual Studio 2022 install) I then try to install the following in order to use AOT with Blazor WASM as per the ASP.NET .NET 6 preview 7 blog:

dotnet workload install wasm-tools

This fails with the following:

Workload installation failed: Failed to validate package signing.

Verifying Microsoft.NET.Runtime.MonoTargets.Sdk.6.0.0-preview.7.21377.19

error: NU3004: The package is not signed.

Package signature validation failed.

Please advise, thanks John

**Comment by steveisok** [comment]
@directhex @mmitche @joeloff Any idea?

**Comment by joeloff** [comment]
So, if you installed a signed .NET SDK, then it will validate that workload packs are signed. For unsigned builds this is turned off. However, we no longer produce signed nightly builds, but new packages, e.g. from RC will get published. 

I looked at the package on NuGet.org and it's definitely signed. Any chance you have another feed configured that pulled the unsigned package before it got to NuGet?

**Comment by mmitche** [comment]
Yep, I'd check two things:
- Your configured feeds only includes nuget.org for this test (so it can't pick up unsigned bits)
- Your cache doesn't include a previous version of this package that is not signed.

**Comment by johngsandiford** [comment]
Removing sources I had added for previous previews gets it passed this error.  I am now getting different errors but will raise a separate issue if I can't resolve them.  Thanks, John
