### ISSUE TITLE
Superpmi fails to replay with missing map GetTailCallHelpers

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#57306]
```

superpmi.py replay -core_root C:\h\w\AF4A091E\p -jitoption TieredCompilation=0 -target_os windows -target_arch x64 -arch x64 -jit_path C:\h\w\AF4A091E\p\clrjit_win_x64_x64.dll -f coreclr_tests

MISSING: Method context 215249 failed to replay: SuperPMI assertion failed (missing map GetTailCallHelpers)

```

**Comment by AndyAyersMS** [comment]
Can you assign a milestone and remove the untriaged label?

**Comment by jakobbotsch** [comment]
I'll see if I can figure this out, from a first cursory glance I don't see why it shouldn't just work.

**Comment by jakobbotsch** [comment]
I think we just need a new collection, after #57009 there are new tail calls that require helpers that previously didn't in some of the tests.

**Comment by kunalspathak** [comment]
Ok, I have triggered one and will verify once it is complete.

**Comment by kunalspathak** [comment]
I have verified and the latest collection fixes the issue.
