### ISSUE TITLE
Improve feature parity between JsonSerializerOptions and JsonSourceGenerationOptionsAttribute

### ISSUE THREAD

**Issue by ithline** [dotnet/runtime#57321]
EDIT See https://github.com/dotnet/runtime/issues/57321#issuecomment-1625883026 for an API proposal.

<details><summary>Original Proposal</summary>
<p>
Currently source generator for JSON serialization in `System.Text.Json` creates a static property named `Default` that receives default `JsonSerializerOptions` defined by the source generator. These can be modified by using `JsonSourceGenerationOptionsAttribute`, but several options are missing and cannot be set, e.g. `PropertyNameCaseInsensitive`, `NumberHandling`, `DictionaryKeyPolicy`...

It would be really helpful if these missing options could be added to the `JsonSourceGenerationOptionsAttribute` or at least disable generating of the `Default` property, so we could provide our own configuration for the default instance.
</p>
</details>

**Comment by layomia** [comment]
Have you tried using the generated ctor on your context type that takes a `JsonSerializerOptions` instance?

e.g.

```cs
[JsonSerializable(typeof(Foo))]
internal partial sealed class MyContext : JsonSerializerContext { }

JsonSerializerOptions options = new() { ... };
MyContext context = new(options);

JsonSerializer.Serialize(foo, context.Foo);
```

**Comment by Ithline** [comment]
Yes, that can be used as a workaround, but the generator still forces public API of my custom `JsonSerializerContext` type. I work with a third party API that needs some specific options set to work and having a `Default` property with basically invalid settings is not a good design. Everyone on the team would need to be aware not to use this property but instead use some other instance.

Ideally even the constructors would not be automatically generated and left to the developer. 
I use need metadata generation to get rid of trimming warnings and don't need the sped up pre-generated serializer.

**Comment by eiriktsarpalis** [comment]
@layomia given that there's a workaround, does this meet the bar for 6.0.0?

**Comment by eiriktsarpalis** [comment]
Moving to 7.0.0, we need to think about API design for this particular use case and we have a 6.0 workaround via the generated constructors.

**Comment by zachcwillson** [comment]
Hey folks,

Would love to see this added so we can avoid `[JsonPropertyName]` attributes that are required for deserializing

```json
{
    "property": "x"
}
```
into
```cs
public sealed record Poco
{
    public string Property { get; set; }
}
```
Without needing to do any additional work.

Currently we have to:
```cs
public sealed record Poco
{
    [JsonPropertyName("property")]
    public string Property { get; set; }
}
```

**Comment by eiriktsarpalis** [comment]
Have you tried using the `JsonSourceGenerationOptionsAttribute`?

```C#
string json = JsonSerializer.Serialize(new Poco { Property = "prop" }, MyContext.Default.Poco);
Console.WriteLine(json); // {"property":"prop"}

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Poco))]
internal partial class MyContext : JsonSerializerContext { }

public sealed record Poco
{
    public string Property { get; set; }
}
```

**Comment by zachcwillson** [comment]
@eiriktsarpalis I had tried that but found it imperfect.

In the scenario I have the following:
```cs
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ODataCollection<Poco>))]
internal partial class MyContext : JsonSerializerContext { }

public sealed record Poco
{
    public string Property { get; set; }
}

public sealed record ODataCollection<T>
{
    [JsonPropertyName("value")]
    public T[] Values { get; set; }

    [JsonPropertyName("@odata.nextLink")]
    public string NextLink { get; set; }
}
```
and I attempt:
```cs
var jsonString = "{ \"value\": [ { \"property\": \"obj1\" }, { \"property\": \"obj2\" } ] }";
var deserialized = JsonSerializer.Deserialize(jsonString, MyContext.Default.ODataCollectionPoco);
```
`deserialized.Values` is null, but we expect it to have two elements

**Comment by eiriktsarpalis** [comment]
We should close the gap between `JsonSerializerOptions` and `JsonSourceGenerationOptionsAttribute` so that users can configure the `Default` JsonSerializerContext without needing to create [instances from scratch](https://github.com/dotnet/runtime/issues/57321#issuecomment-898007911).

## API Proposal

The proposed new properties/constructors are taken directly from the [`JsonSerializerOptions` class](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions?view=net-8.0).

```diff
namespace System.Text.Json.Serialization;

public partial class JsonSourceGenerationOptionsAttribute
{
    public JsonSourceGenerationOptionsAttribute();
    public JsonSourceGenerationOptionsAttribute(JsonSerializerDefaults defaults);

+   public bool AllowTrailingCommas { get; set; }
+   public bool DefaultBufferSize { get; set; }
    public JsonIgnoreCondition DefaultIgnoreCondition { get; set; }
+   public JsonKnownNamingPolicy DictionaryKeyPolicy { get; set; }
    public bool IgnoreReadOnlyFields { get; set; }
    public bool IgnoreReadOnlyProperties { get; set; }
    public bool IncludeFields { get; set; }
+   public bool MaxDepth { get; set; }
+   public JsonNumberHandling NumberHandling { get; set; }
+   public bool PropertyNameCaseInsensitive { get; set; }
    public JsonKnownNamingPolicy PropertyNamingPolicy { get; set; }
+   public JsonCommentHandling ReadCommentHandling { get; set; }
+   public JsonUnknownTypeHandling UnknownTypeHandling { get; set; }
+   public JsonUnmappedMemberHandling UnmappedMemberHandling { get; set; }
    public bool WriteIndented { get; set; }
}
```

Note that the above leaves out the `Converters`, `Encoder` and `ReferenceHandler` properties from JsonSerializerOptions as they are reference types and cannot be specified on attribute annotations. We can consider adding support for these in the future: common values can be represented via proxy enum types as is the case of `JsonKnownNamingPolicy` being used instead of the `JsonNamingPolicy` class.

**Comment by terrajobst** [comment]
* We considered exposing the constructor parameter as a property but we don't believe anyone should need that

```diff
namespace System.Text.Json.Serialization;

public partial class JsonSourceGenerationOptionsAttribute
{
    public JsonSourceGenerationOptionsAttribute();
+   public JsonSourceGenerationOptionsAttribute(JsonSerializerDefaults defaults);

+   public bool AllowTrailingCommas { get; set; }
+   public Type[]? Converters { get; set; }
+   public int DefaultBufferSize { get; set; }
    public JsonIgnoreCondition DefaultIgnoreCondition { get; set; }
+   public JsonKnownNamingPolicy DictionaryKeyPolicy { get; set; }
    public bool IgnoreReadOnlyFields { get; set; }
    public bool IgnoreReadOnlyProperties { get; set; }
    public bool IncludeFields { get; set; }
+   public int MaxDepth { get; set; }
+   public JsonNumberHandling NumberHandling { get; set; }
+   public JsonObjectCreationHandling PreferredObjectCreationHandling { get; set; }
+   public bool PropertyNameCaseInsensitive { get; set; }
    public JsonKnownNamingPolicy PropertyNamingPolicy { get; set; }
+   public JsonCommentHandling ReadCommentHandling { get; set; }
+   public JsonUnknownTypeHandling UnknownTypeHandling { get; set; }
+   public JsonUnmappedMemberHandling UnmappedMemberHandling { get; set; }
    public bool WriteIndented { get; set; }
}
```
