### ISSUE TITLE
Reflection not working in existing project

### ISSUE THREAD

**Issue by JamesHill3** [dotnet/runtime#57373]
### Describe the bug
After upgrading my project from .Net 6 Preview 6 to .Net 6 Preview 7, a shared component that uses reflection no longer works. The offending code is unchanged and has worked through all preview versions of .Net 6.

To make matters worse, the offending code works on my local machine using the SDK, but fails on our development server which has .Net 6 Preview 7 hosting bundle installed.

### Exceptions (if any)

The error message is less than helpful, referring to generic type '<>A{00000004}`3':

> System.TypeLoadException: The generic type '**<>A{00000004}`3**' was used with an invalid instantiation in assembly 'CarrisMaestro.Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. at CarrisMaestro.Web.Pages.Shared.Components.Tabs.Pages_Shared_Components_Tabs_Default.b__10_1() at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in System.Private.CoreLib.dll:token 0x6004ee7+0x28 at CarrisMaestro.Web.Pages.Shared.Components.Tabs.Pages_Shared_Components_Tabs_Default.b__10_1() in CarrisMaestro.Web.dll:token 0x6000756+0x1c at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder) in Microsoft.AspNetCore.Razor.Runtime.dll:token 0x6000047+0x70 at CarrisMaestro.Web.TagHelpers.FixedHeaderTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in C:\Users\James\source\repos\Web_Carris_Maestro\CarrisMaestro.Web\TagHelpers\FixedHeaderTagHelper.cs:line 23

### Further technical details
- Microsoft Visual Studio Community 2022 Preview (64-bit)  Version 17.0.0 Preview 3.0

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.4.20251.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.5.21301.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.4.20251.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.5.21301.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by stephentoub** [comment]
I assume `dynamic` is being used somewhere?  This looks like a dup of https://github.com/dotnet/roslyn/issues/55609.

**Comment by stephentoub** [comment]
Oh, wait, it's about reflection, not interpolated strings.  I read it too quickly.

**Comment by stephentoub** [comment]
Are ref structs being used anywhere?  dynamic?  This looks an awful lot like what you'd get with combining dynamic with something that can't be used as a generic type parameter, like a ref struct.
```C#
class Program
{
    static void Main()
    {
        S s = default;
        s.M((dynamic)5);
    }
}

ref struct S
{
    public void M<T>(T value) { }
}
```
yielding:
```
Unhandled exception. System.TypeLoadException: The generic type '<>A{00000004}`3' was used with an invalid instantiation in assembly 'ConsoleApp13, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Program.Main()
```

**Comment by JamesHill3** [comment]
@stephentoub The resulting error does look the same. I'll dig a little deeper in the reflection and see is dynamic is used.

**Comment by joperezr** [comment]
@JamesHill3 could it be possible for you to share some diagnostic logs of your build/publish process so that we can check if in fact the IL Trimmer is not removing any method incorrectly? (Given that the new callstack you are getting seems to be a MissingMethodException)

**Comment by JamesHill3** [comment]
@joperezr My apologies for the delay in responding. As this project is actively being developed for a go-live that will likely coincide with the release of .Net 6, I couldn't spend more than a day trying to figure this out. I ended up downgrading the projects so that we could stay on track for our end of year release.

I'm going to wait until preview 8 is released and try again. If I encounter the same issue, I'll share the logs that you requested.
