### ISSUE TITLE
Direct Downloads to Setup Executables - Shortened Urls

### ISSUE THREAD

**Issue by snickler** [dotnet/runtime#574]
Hello,

I am wondering if there's a possibility of direct downloads being provided in a short URL form (aka.ms/dotnet-hosting-3-1-0 for example), rather than 150+ character URLs? In my particular case, I'm managing versions of a docker image based on IIS that installs the ASP.NET Core Hosting Windows Hosting Bundle. It would be great if we had a short URL that could be intuitive, rather than going to the "Thank you for downloading" page and then retrieving the actual direct url from there.

**Comment by Symbai** [comment]
I think this might be difficult with different bitness, OS, sdk / runtimes executables. The URL won't be that much shorter if all necessary information are included in the end.

As an alternative you may want to take a look at the installer script instead: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script to get direct downloads.

**Comment by snickler** [comment]
Actually, thank you for that suggestion. I COMPLETELY forgot about this script. Although it only lists SDK and Runtimes with the blob url, I just assumed I could replace the runtime file location with the file name of the dotnet-hosting exe... I was correct. 

https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/3.1.0/dotnet-hosting-3.1.0-win.exe

I don't understand why https://download.visualstudio.microsoft.com/download/pr/fa3f472e-f47f-4ef5-8242-d3438dd59b42/9b2d9d4eecb33fe98060fd2a2cb01dcd/dotnet-hosting-3.1.0-win.exe would be used instead of the url above.

**Comment by dagood** [comment]
You may want to try out the aspnet images from https://github.com/dotnet/dotnet-docker, although I'm not sure how that differs from installing the whole hosting bundle.

I'm transferring this issue to aspnet/aspnetcore. The hosting bundle is built there (this repo is only .NET Core Runtime), and they may have better suggestions on how to acquire it, or whether the existing ASP.NET Docker images should work for you.

**Comment by dagood** [comment]
Apologies, forgot that "transfer issue" doesn't work across the orgs, and it looks like my ZenHub "move issue" button has disappeared. 😕

I'm closing this issue in this repo but encourage you to ask in https://github.com/aspnet/AspNetCore for any more questions, sorry for the inconvenience.
