### ISSUE TITLE
Make Math/MathF.Sign inlineable for floating point data

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#57413]
### Description

Math/MathF.Sign for floating point data currently isn't inlined, probably due to the throw there. Since it's a simple math operation, it should probably be inlined.

### Configuration

Sharplab Core CLR 5.0.721.25508 on amd64

### Regression?

No idea.

### Data

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACY8pRgVwDtdsAzGZqUYAVGLgw0A3jUazmTFmwCWnDIwDKSgOacAFABMI7YABsB+gJQy506nPvMA7IwCy2DAAsAdJp0GLANzWsgC+wYzhDMysjCpqvnq8JhDujLxWdjbh9sTObp4AYj7aiYHhYdQhQA===)

### Analysis

Moving the throw there to a throw helper should probably make it inlineable.

**Comment by dakersnar** [comment]
Closing this for reasons explained above.
