### ISSUE TITLE
[WIP] Major performance reduction with net6 vs classic xamarin

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#57427]
### Description

This is going to be a bit of a weird one, but something is happening with threads/async/locking when using net6.

I have a Xamarin.Android app

https://github.com/dotnet/maui/tree/6.0.100-preview.7.6

**Comment by mattleibow** [comment]
Hmm... This appears to be running slow in xamarin as well. Well, there are about 1500 UI tests all doing things, so 10-15 seconds is not that slow - especially since I added delays to wait for layouts to happen.

Don't mind me.

Also, great work on net6. A bit rough, but still pretty rad.

**Comment by danmoseley** [comment]
@mattleibow that aside do you have any other feedback on .NET 6 so far? Eg perf and size vs before.
