### ISSUE TITLE
Blazor WASM AOT not working on MacOS 10.13.6

### ISSUE THREAD

**Issue by ar0311** [dotnet/runtime#57431]
Installed 6.0-preview-7 SDK on MacOS 10.13.6 (High Sierra)

Ran "sudo dotnet workload install wasm-tools", installed OK

dotnet new blazorwasm, add "RunAOTCompilation" to csproj.

dotnet publish -c Release generates the following error:

/usr/local/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/6.0.0-preview.7.21377.19/Sdk/WasmApp.Native.targets(443,5): warning : [/Users/adam/Repos/blazorwasm60pre7/obj/Release/net6.0/linked/Microsoft.AspNetCore.Components.dll] dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin [/Users/adam/Repos/blazorwasm60pre7/blazorwasm60pre7.csproj]

Some Googling leads me to suspect it may have something to do with the workload package itself being built on MacOS 10.15

**Comment by pranavkm** [comment]
FYI @radical  / @lewing

**Comment by radical** [comment]
cc @vargaz

**Comment by vargaz** [comment]
Probably needs to target a lower osx version with -mmacosx-version-min=10.13 or something.

**Comment by vargaz** [comment]
The mono/mono repo had:
MACOS_VERSION_MIN?=10.9

**Comment by lewing** [comment]
this is going to be a problem for any of the cross runtimes correct?

**Comment by lambdageek** [comment]
> this is going to be a problem for any of the cross runtimes correct?

yea, this will affect every cross-compiler /cc @akoeplinger

**Comment by akoeplinger** [comment]
.NET 6 only supports macOS 10.14+ according to https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#macos

**Comment by akoeplinger** [comment]
Though right now we're still targeting 10.13 as the min version for mono here: https://github.com/dotnet/runtime/blob/6acb72bb66c3b68672a0653b35a193b39677c33b/src/mono/Directory.Build.props#L20

We're missing this condition for wasm/android: https://github.com/dotnet/runtime/blob/6acb72bb66c3b68672a0653b35a193b39677c33b/src/mono/mono.proj#L556-L558
