### ISSUE TITLE
Bug in TieredPgo?

### ISSUE THREAD

**Issue by Anarh2404** [dotnet/runtime#57441]
### Description

Repro https://github.com/Anarh2404/TieredPgoRepro
With DOTNET_TieredPGO=1 app crashes after ~120 iterations with NullReferenceException. 
With DOTNET_TieredPGO=0 it works well.
Reproduce on Windows. It doesn't crash on linux or Macos

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

**Comment by EgorBo** [comment]
I can reproduce it on .NET 6.0 Preview 7 but it doesn't reproduce using the latest daily build. Hard to say what exactly fixed it.

**Comment by JulieLeeMSFT** [comment]
@Anarh2404 closing this issue because it was fixed. Please reopen if it fails again.
