### ISSUE TITLE
About TCP connect timeout

### ISSUE THREAD

**Issue by EzrealJ** [dotnet/runtime#57468]
When TCP initiates a connection on Windows, it will report a timeout at about 21s (Linux is a longer time). Check other Issues to know that this is restricted by the Windows system; but using Java does not have this restriction, probably it has done some Changes. This situation has led to a lot of extreme situations where we need to abandon C# and use Java instead, which adds a lot of time cost. Will the community consider optimizing this aspect in the future?

**Comment by danmoseley** [comment]
Just curious how long before it time out if you use Java?

Do you have a code snippet and other repro info eg is it IPv4 or IPv6 etc. does it repro using another means like Python?

**Comment by wfurt** [comment]
AFAIK this comes from OS defaults. You may be able to change that as well as you can use Timeout for sync operations or Cancellation token for ConnectAsync if you want to fail sooner.

**Comment by EzrealJ** [comment]
@danmoseley Sorry for the ambiguity.C# library depends on TCPClient when connecting to MySql, Java may depend on other; I don’t think Java has any difference in the implementation of TCP connect. I originally wanted to ask the community if there are plans to make the timeout of TCP connections break through the OS limits

@wfurt Thank you very much for your answer, I will try to change the OS settings,

I will close this issue first
