### ISSUE TITLE
Negative Length in ReadOnlySequence

### ISSUE THREAD

**Issue by kuda1978** [dotnet/runtime#57472]
### Description

In some cases Length of ReadOnlySequence was Negative.

Test for reproduce problem: [ReadOnlySequenceTests.cs](https://gist.github.com/kuda1978/2108aa365eb3bd88c48f2ee23cd8f71a)

### Configuration
.Net SDK: 5.0.400, 6.0.100-preview.7.21379.14

### Solution
In file `~\dotnet\runtime\src\libraries\System.Memory\src\System\Buffers\ReadOnlySequence.cs` replace folowing string:
```
public ReadOnlySequence(ReadOnlyMemory<T> memory)
{
    if (MemoryMarshal.TryGetMemoryManager(memory, out MemoryManager<T>? manager, out int index, out int length))
    {
        ...
        _endInteger = index + length;
```

**Comment by adamsitnik** [comment]
I've confirmed that it's reproducible on 3.1, 5.0 and 6.0 and I am 99.9% sure it's a bug. I am on it.
