### ISSUE TITLE
Using Compare data annotation on record parameter

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/runtime#57475]
Few of the validation data annotations work on `record`  parameters, for example`Compare` only works on the `Property` type and the following code won't compile:

```csharp
public record PasswordChangeCommand(
    [Required, MaxLength(64)]
    string CurrentPassword,

    [Required, MaxLength(64)]
    string NewPassword,

    [Compare("NewPassword"), MaxLength(64)]
    string ConfirmNewPassword
) : IRequest;
```

> Error	CS0592	Attribute 'Compare' is not valid on this declaration type. It is only valid on 'property, indexer' declarations.

It would be great if `AttributeTargets.Parameter` was added to the `Compare` and the rest of the validation attributes.
```csharp 
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter, AllowMultiple = false)]
public class CompareAttribute : ValidationAttribute
{
}
```

**Comment by mo-esmp** [comment]
I know this functionality could be achieved by using property but I want to make it readonly and avoid writing extra code to use private field and so on. Let's consider I have an API and want to bind received data to a class that all properties should be read-only:
```csharp
public async Task<IActionResult> Post(PasswordChangeCommand command)
{
    if (!ModelState.IsValid)
        return BadRequest(ModelState);

    await _mediator.Send(command);

    return Ok();
}
```
By using `record` I could have that functionality without writing extra codes to pass values from the constructor and assign them to properties for each model.

**Comment by huoyaoyuan** [comment]
> by using property

> By using `record`

```csharp
public record PasswordChangeCommand(
    [property: Required, MaxLength(64)]
    string CurrentPassword,

    [property: Required, MaxLength(64)]
    string NewPassword,

    [property: Compare("NewPassword"), MaxLength(64)]
    string ConfirmNewPassword
) : IRequest;
```
