### ISSUE TITLE
An error with SignatureAlgorithm in X509Certificate2 (.net core 3.1, .net 5)

### ISSUE THREAD

**Issue by ZiCold** [dotnet/runtime#57477]
### Description

I've encountered an issue with creating X509Certificate2 class from an open certificate file (.cer).
The problem is that issue exists only in .net core 3 / .net 5, but not in .net framework 4.5+

X509Certificate2 class has property:
`public Oid SignatureAlgorithm { get; } `

Oid has properties:
```
public string? FriendlyName { get; set; }
public string? Value { get; set; }
```

For all of my certificates:

In the case of .Net Framework they are:
```
Value: "1.2.643.7.1.1.3.2"
FriendlyName: null
```
(which are right values)

In the case of .Net Core 3.1 / .Net Core 5 there is an error:

> System.Security.Cryptography.CryptographicException: 'The OID value is invalid.'

Message: The OID value is invalid.
Source: System.Security.Cryptography.Encoding
Stacktrace:

>    at System.Security.Cryptography.Oid.FromOidValue(String oidValue, OidGroup group)
>    at System.Security.Cryptography.X509Certificates.X509Certificate2.get_SignatureAlgorithm()

It's worth to mention that certificates were issued by Russian Federation Certification Centers and 
"1.2.643.7.1.1.3.2" is "GOST R 34.10-2012 algorithm for 256 bit keys".

But it should not affect extracting values. What can I do?

**Comment by vcsjones** [comment]
I can reproduce it. Interestingly, it does reproduce on Windows, not Linux. I'll take a look to at least see what is going on.

**Comment by vcsjones** [comment]
Simpler reproduction:

```c#
var oid = Oid.FromOidValue("1.2.643.7.1.1.3.2", OidGroup.All);
Console.WriteLine(oid.Value);
```

This fails, interestingly enough.

**Comment by vcsjones** [comment]
Although it fails on .NET Framework 4.8 for me, too.

**Comment by bartonjs** [comment]
> The downside is FriendlyName could do a directory query now.

I feel like Windows told me that they got rid of that feature on Win10.  So it's probably a fine change :smile:.

**Comment by ZiCold** [comment]
Thank you so much! I will look forward to the fix!
