### ISSUE TITLE
Add FreeBSD to mono build in runtime.yml

### ISSUE THREAD

**Issue by jasonpugsley** [dotnet/runtime#57487]
I have PR https://github.com/dotnet/runtime/pull/57027 in progress with some fixes to allow the mono subset to be built under native FreeBSD as well as cross-built under Linux.
FreeBSD is currently enabled for CI build (Linux cross-build) under these sections:

- CoreCLR Product Build FreeBSD x64 release
- Libraries Build FreeBSD x64 Debug
- Installer Build and Test coreclr FreeBSD_x64 Release

At the moment, `eng/pipelines/runtime.yml` doesn't have FreeBSD under any of the mono build sections.

After https://github.com/dotnet/runtime/pull/57027 is merged, could the owners of `eng/pipelines/runtime.yml` please investigate adding FreeBSD to the relevant section/s.

**Comment by ViktorHofer** [comment]
cc @safern

**Comment by Thefrank** [comment]
poking issue as https://github.com/dotnet/runtime/pull/57027 got merged

**Comment by safern** [comment]
cc: @steveisok
