### ISSUE TITLE
[HTTP/3] Test timeout: Public_Interop_ExactVersion_BufferContent_Success

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57498]
Test type: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic

Failures 6/16-8/16 (incl. PRs):

Day | Run
-- | --
8/12 | 2x Official run

Failure:
```
System.TimeoutException : The operation has timed out.

   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_ExactVersion_BufferContent_Success(String uri) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 508
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment]
Which args? This is testing against external servers, so it matters whether if it's the same external server.
And just to confirm this is outerloop, isn't it?

**Comment by karelz** [comment]
@ManickaP uri was `https://cloudflare-quic.com/` in both cases.
The failures were <10 minutes apart.

**Comment by rzikm** [comment]
The test to `https://cloudflare-quic.com/` is enabled and there are no recent test failures. Closing as not actionable.
