### ISSUE TITLE
OptionsCache cached an Exception

### ISSUE THREAD

**Issue by Shazhko-Artem** [dotnet/runtime#57496]
We face a problem in the project: if an option cannot be configured due to an exception, it does not try to do it again at the next request. This is very strange and not obvious. For example, when we register a service as a singleton (in DI) and an exception is thrown when we receive it, then when we request that service again, we will try to resolve it again, BUT the behavior in options are completely different.

After analysis, it turned out that `OptionsCache` uses `Lazy` inside the `ConcurrentDictionary`, that is why an exception from the `OptionsFactory` is cached, instead of throw this exception to the up.

Why would you use  `Lazy` inside the `ConcurrentDictionary` when you call the `Value` property right away anyway?
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Options/src/OptionsCache.cs#L31-L50

Why not use `ConcurrentDictionary<string, TOptions>`? There is a `GetOrAdd` overload method in the `ConcurrentDictionary` that takes a `Func<string, TOptions>`, so you can use it.
``` c#
_cache.GetOrAdd(name, key => createOptions());
```

**Comment by Shazhko-Artem** [comment]
There are 3 interfaces to get the options:
- `IOptions<>` uses `OptionsManager<>`
- `IOptionsSnapshot<>` uses `OptionsManager<>`
- `IOptionsMonitor<>` uses `OptionsMonitor<>`

All of these implementations use a factory (`IOptionsFactory<>`), but the behavior is not uniform. If the factory throws an exception, then on the next attempt to get the options, the factory will be called again from the `OptionsManager<>`. In the case of the `OptionsMonitor<>`, the behavior is fundamentally different, the error will be cached and the factory is no longer called.

I find this behavior to be very strange and non-obvious.

**Comment by Shazhko-Artem** [comment]
I corrected the description because there was a mistake.

**Comment by Shazhko-Artem** [comment]
is there any update?

**Comment by maryamariyan** [comment]
@Shazhko-Artem Do you have a minimal repro code to share with this?

**Comment by eerhardt** [comment]
Closing as there isn't a minimal repro listed. Please re-open with a minimal repro. Please see https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-bug-report.
