### ISSUE TITLE
Debug Diagnostics always allocates StringBuilder with new optimized String Interpolation

### ISSUE THREAD

**Issue by snakefoot** [dotnet/runtime#57526]
When using the old string.Format then it would make use of internal StringBuilder-pool.

Now it always allocates a new StringBuilder, and throws it away:

https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs#L301

**Comment by stephentoub** [comment]
That code is not for string.Format. That's the code for Debug.Assert, which is only compiled in for `#define DEBUG`, and specifically on the path where Debug.Assert is given a false condition, which means it's failing an assert and by default is about to crash the process.  Why is a `StringBuilder` allocation there concerning?

**Comment by snakefoot** [comment]
Lets try again old-style-interpolated-strings would convert into string.Format, and string.Format would make use of StringBuilder-pool.

Also it is not only `Debug.Assert` that you have received additional springles. The same also applies for `Debug.WriteIf` and `Debug.WriteLineIf` that hopefully doesn't crash the process.

Why not use `DefaultInterpolatedStringHandler` instead of `AssertInterpolatedStringHandler` in `Debug` ?

**Comment by stephentoub** [comment]
> Why not use DefaultInterpolatedStringHandler instead of StringBuilder.AppendInterpolatedStringHandler in Debug ?

Because DefaultInterpolatedStringHandler is a ref struct.

**Comment by snakefoot** [comment]
Just strange that it is promoted as a performance improvement with less-allocation, but then becomes a knife in your back.

Anyway I just looked for some example code of how to use the new optimization, but I guess I have to continue looking.

**Comment by stephentoub** [comment]
> becomes a knife in your back (when the condition is true)

Can you please share concrete examples of where you're using Debug.WriteIf on code paths where the extra StringBuilder matters?

If they exist,  it's fixable with more code.  It simply seems to me right now like the wrong tradeoff to add more code for this.

Thanks.

**Comment by snakefoot** [comment]
I think it makes good sense for `Debug.Assert()`. I was just curious why this decision was made for `Debug.WriteIf` (And now you have told that it is because `DefaultInterpolatedStringHandler` is impossible to reuse).

Now I just have to figure out why Microsoft have implemented an optimization that only can be used for Logging just before crashing the process

**Comment by stephentoub** [comment]
> Now I just have to figure out why Microsoft have implemented an optimization, that only can be used for Logging just before crashing the process (And hard to reuse anywhere else without inferring a performance hit because of StringBuilder-allocations).

Huh? I don't understand your question / comment.

**Comment by snakefoot** [comment]
> Huh? I don't understand your question / comment.

Lets say I have another place where I want to check a condition, before doing the string-interpolation (Just like `Debug.WriteIf`)

How would I do that, since I cannot use `DefaultInterpolatedStringHandler` ? And I don't want to use `AppendInterpolatedStringHandler` because of the StringBuilder-allocation-hit ?

**Comment by stephentoub** [comment]
Pool StringBuilders, or implement appends yourself using whatever mechanism you want, or create your handler as a ref struct, or...

**Comment by snakefoot** [comment]
Yep thank you for confirming that implementing own StringBuilder-pool is only way forward. Maybe update the [The handler pattern](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/improved-interpolated-strings#the-handler-pattern) with concrete example that uses `AppendInterpolatedStringHandler` with a note about optional StringBuilder-pool.

And also explain that `DefaultInterpolatedStringHandler` cannot be wrapped in custom handles because it is very sensitive about its lifetime.

**Comment by stephentoub** [comment]
> implementing own StringBuilder-pool is only way forward

It is not the only way. 

But thank you for the feedback.

**Comment by snakefoot** [comment]
> It is not the only way.

So how to I get a the formatted-string using a custom-handler without allocating the StringBuilder, and not doing carbon-copy of `DefaultInterpolatedStringHandler`?

**Comment by stephentoub** [comment]
Make your handler a ref struct.

**Comment by snakefoot** [comment]
Why did you not decide not to make `AssertInterpolatedStringHandler` a `ref struct` and re-use `DefaultInterpolatedStringHandler` ?

**Comment by stephentoub** [comment]
Based on the stated belief that allocations in those situations do not matter.

**Comment by snakefoot** [comment]
Thank you for the answers. Though I still don't understand the choice to opt-in for allocations, when it is just a matter of changing to `ref struct` to fix it. But I have what I need.

**Comment by stephentoub** [comment]
> I still don't understand the choice to opt-in for allocations, when it is just a matter of changing to ref struct to fix it

If a handler is a ref struct, you can't do `$"...{await Foo()}..."` with awaits _inside_ of formatting holes.  In our experience, that's a very rare need, but technically it is a functional limitation.  So you trade that off against other costs.  If you believe that additional overhead isn't a big deal when passing true to Debug.WriteIf, because that's typically only done in debug builds when you're gathering additional information about something that's not working correctly, then it's better to accomodate even that rare need than to avoid costs that don't matter.  If you believe that those costs do matter in these situations, then you make a different tradeoff, e.g. adding additional code to implement appending yourself, or pooling StringBuilders to use the existing logic there, and so on.
