### ISSUE TITLE
EnvironmentVariablesConfigurationProvider not load connection string prefix POSTGRESQLCONNSTR_ on Azure AppService

### ISSUE THREAD

**Issue by thohng** [dotnet/runtime#57545]
### Description

On Azure AppService, it is able to add connection string for PostgreSQL. But the configuration does not load the PostgreSQL connection string. The workaround is select 'Custom' when adding connection string instead of 'PostgreSQL' provider.

### Configuration

Setup PostgreSQL connection string on Azure AppService
![image](https://user-images.githubusercontent.com/9668549/129653247-10c778a5-39a3-4536-bc25-73f59020f337.png)

Checking Azure AppService Environments
![image](https://user-images.githubusercontent.com/9668549/129653484-61e88b1d-4e7c-4d90-b0af-1f65853349d6.png)

### Other information

Latest code on repository:
https://github.com/dotnet/runtime/blob/faa05598c1981d74b9dc37504da8472400b3aeba/src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/src/EnvironmentVariablesConfigurationProvider.cs#L15-L20

```
public class EnvironmentVariablesConfigurationProvider : ConfigurationProvider
{
	private const string MySqlServerPrefix = "MYSQLCONNSTR_";
	private const string SqlAzureServerPrefix = "SQLAZURECONNSTR_";
	private const string SqlServerPrefix = "SQLCONNSTR_";
	private const string CustomPrefix = "CUSTOMCONNSTR_";

	private readonly string _prefix;
```

**Comment by thohng** [comment]
Related document of Azure AppService / Configure connection strings

https://docs.microsoft.com/en-us/azure/app-service/configure-common#configure-connection-strings

```
At runtime, connection strings are available as environment variables, prefixed with the following connection types:

SQLServer: SQLCONNSTR_
MySQL: MYSQLCONNSTR_
SQLAzure: SQLAZURECONNSTR_
Custom: CUSTOMCONNSTR_
PostgreSQL: POSTGRESQLCONNSTR_
```

**Comment by thohng** [comment]
Current dotnet document

https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#connection-string-prefixes

**Comment by davidfowl** [comment]
We should just add it.

**Comment by thohng** [comment]
The issue is not fixed
