### ISSUE TITLE
NameResolutionTelemetry event source provides average dns lookup time, which is not very informative

### ISSUE THREAD

**Issue by HolyPrapor** [dotnet/runtime#57553]
An average time is misleading in a lot of cases because one is unable to see spikes of load. 

Unfortunately, .NET [NameResolutionTelemetry](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionTelemetry.cs) does not calculate informative percentiles nor it has a way to calculate those because underlying stop/fail events do not have a stopwatch (or at least hostname) to calculate latency.

I understand that underlying counters do not calculate percentiles because it's expensive and calculate average instead. (It's better than nothing)

But as far as I can see, it is very easy to add this info to events so that one could calculate whatever he needs.

Would you consider this proposal?

**Comment by MihaZupan** [comment]
The NameResolution telemetry will emit Start/Stop pairs for each resolution.

The events will be fired from within the same async scope and can as such be correlated (an `AsyncLocal` created during Start will be visible during Stop).
From this, you can get the time taken for a specific operation by calculating the difference between the event timestamps, or calculate any other statistic you are interested in.

For an example, see https://gist.github.com/MihaZupan/ba499563e5d602d990872fd9f5c35229 that is making use of the [`Yarp.ReverseProxy.Telemetry.Consumption`](https://www.nuget.org/packages/Yarp.ReverseProxy.Telemetry.Consumption/1.0.0-preview.12.21328.2) package (it can be used outside of YARP). The sample does correlation for Kestrel events, but then pattern is the same for name resolution.

**Comment by MihaZupan** [comment]
That said, if there are some statistics that would be useful to include in counters for multiple users,  we would certainly consider it - one such discussion is going on in https://github.com/dotnet/runtime/issues/48885

**Comment by jkotas** [comment]
> The events will be fired from within the same async scope and can as such be correlated (an AsyncLocal created during Start will be visible during Stop).

AsyncLocals work only if you are consuming the events in-proc.

@MihaZupan Is it possible to correlate the events in out-of-proc listener? Out-of-proc listeners are very common in telemetry solutions.

**Comment by MihaZupan** [comment]
> Is it possible to correlate the events in out-of-proc listener?

Yes. If you enable the `TplEventSource` with the [`TasksFlowActivityIds`](https://github.com/dotnet/runtime/blob/885e7a20fb554a085e66ec6643aa3cb3f197faa3/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TplEventSource.cs#L123) keyword, other `EventSource` events will also contain an `ActivityID`. The activity ID is also tracked as an `AsyncLocal` by [`ActivityTracker`](https://github.com/dotnet/runtime/blob/885e7a20fb554a085e66ec6643aa3cb3f197faa3/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/ActivityTracker.cs#L622) and it encodes an async scope hiearchy.

An example with `PerfView` using `*System.Net.Sockets,*System.Net.NameResolution,*System.Net.Http,*System.Net.Security,System.Threading.Tasks.TplEventSource:0x80:4`:
![image](https://user-images.githubusercontent.com/25307628/129730938-148c2fae-2662-4919-ad82-5e21d7edbc9a.png)

**Comment by karelz** [comment]
Triage: Seems to be addressed - solution does exist. Closing.
