### ISSUE TITLE
EventPipeEventDispatcher throttling.

### ISSUE THREAD

**Issue by Fluoxetinum** [dotnet/runtime#57554]
My service is working in docker container with 69 other services in docker containers with is hosted on single server with 30 physical cores and 256 Gb of memory. In most of time it consumes about 150% of CPU.
In some random moment CPU load moves up to 3000%. With htop linux util I see huge count of threads (100+) from threadpool. 
After investigation with dotnet-dump/-trace I found that one of services with is consuming 250% of CPU does nothing in this time (http service, logs contains only warnings from heartbeat. w/out requests or other work). This service consists of 100+ threads with one thread working on 100% of CPU. 
Stacktrace of this thread rests to EventPipeEventDispatcher thread.

So we have 2 problems. 
 - The first one is high loaded EventPipeEventDispatcher thread, which is consuming 1 core. 
 - ThreadPool algorithms which makes hundreds of threads in all 70 services who run on 30 cores on single server when trying to solve perf issues

What can we do? To solve this we plan to implement EventPipeEventDispatcher by ourselves (to send not all metrics, but to send 1 per second). To do this, we tried to Import metrics methods from CLR manually (https://github.com/dotnet/runtime/blob/86a5b7eafc4699321dae0cb6578fc7e874914e39/src/coreclr/System.Private.CoreLib/src/System/Diagnostics/Eventing/EventPipe.CoreCLR.cs) with no luck. How can we do this? Or may be somewhere exists conf parameters which will allow us to reduce pressure to this thread?

(Sorry for my poor English)

**Comment by Fluoxetinum** [comment]
@trylek

**Comment by Fluoxetinum** [comment]
@lateralusX

**Comment by tommcdon** [comment]
@josalem

**Comment by trylek** [comment]
I'm no thread expert myself but I happen to have one as my team peer so /cc-ing @kouvel.

**Comment by josalem** [comment]
Before we dig into how we might solve the problem, I want to ask a few clarifying questions:

* What version of .net is your application running on, e.g., 3.1 or 5.0? Which revision of that version, e.g., 3.1.17 vs 3.1.10?
* `EventPipeEventDispatcher` should only be on if you are using `EventPipe` in some capacity, e.g., using an `EventListener` to listen to events from `Microsoft-Windows-DotNETRuntime` or collecting a trace with dotnet-trace. How are you using EventPipe in your application?
  * Your comment mentions metrics and an interval. If you are collecting metrics via Diagnostics EventCounters, then those should already be respecting a specified event frequency. More details here will be helpful.
* Can you give a high level overview of what you are collecting (types of events, metrics, etc.) and the frequency that you are sending these events or expect to receive these events?
* What tooling are you using to collect metrics?

**Comment by kouvel** [comment]
> ThreadPool algorithms which makes hundreds of threads in all 70 services who run on 30 cores on single server when trying to solve perf issues

Are the containers CPU-limited in any way, or is the intention to allow them to use as much CPU as necessary?

Thread pool threads are created somewhat as needed and they time out if they haven't been used for ~20 s or so, so if a service lingers with 100+ threads for several minutes it would seem that it is occasionally using them. What is happening in the services when the thread count increases to 100+?
