### ISSUE TITLE
Command line arguments not parsing with section 

### ISSUE THREAD

**Issue by shersh** [dotnet/runtime#57568]
### Description

Command Line arguments don't parsed with section. 
For example:

> myapp.exe Section__ConnectionUri=Hello

will not parsed to class 

```cs
public class Section
{
       public string ConnectionUri {get;set;}
}
```

Only one working way:

> myapp.exe Section:ConnectionUri=Hello

### Configuration

.NET 5

**Comment by shersh** [comment]
It's area-Extensions-Configuration I think

**Comment by shersh** [comment]
@ericstj @maryamariyan @michaelgsharp @safern @tarekgh

**Comment by maryamariyan** [comment]
Did you take a look at the documentation and guide in https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#command-line-arguments?

Do you have a minimal repro code to share?
