### ISSUE TITLE
[mscorlib] Enum.ValuesAndNames could be a struct

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#5757]
Right now [`ValuesAndNames`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Enum.cs#L673), which is used by `Enum`, is defined as a typical POCO class. However, it doesn't look like the fields in question are actually being modified anywhere, nor is it being passed as a parameter to any methods, so it might be good for converting to a class to avoid heap allocations during `Enum.InternalGetValues` and `InternalGetNames`. Additionally, it could have `readonly` fields.

**Comment by GrabYourPitchforks** [comment]
Closed since there seems to be nothing left to do here. The value is cached using `Type`'s normal ancillary data caching mechanism. Accessing the names and values is now mostly allocation-free except for the single allocation needed to return a fresh array every time.
