### ISSUE TITLE
[mscorlib] Moving more of the String functions to managed code

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#5758]
As it stands, many 'high-level' string functions like `IndexOf`, `LastIndexOf`, `Replace` etc. are implemented natively when they could be written in managed code. I noticed this was done with one of the `string.Replace` overloads in f007485, so maybe it would be good to do this to make the code more accessible to newcomers, if they aren't familiar with how the C++ code maps to C#.

**Comment by joperezr** [comment]
Closing as from @jkotas response above there is nothing left to be done here. @jamesqo feel free to reopen if you think otherwise.
