### ISSUE TITLE
LLVM AOT doesn't work on MacCatalyst

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#57589]
### Description

Example application (create from empty project with modified .csproj): 
[Archive.zip](https://github.com/dotnet/runtime/files/7001957/Archive.zip)

### Configuration

.NET 6.0.100-rc.1.21415.3
macOS 12.0 Beta
Xcode 13 beta 4 (iirc)

### Regression?

It probably never worked?

### Other information

```
  ld: building for Mac Catalyst, but linking in object file built for , file '/Users/filipnavara/Projects/llvmbug/obj/Debug/net6.0-maccatalyst/maccatalyst-arm64/nativelibraries/aot-output/arm64/llvmbug.dll.llvm.o'
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(847,3): error : clang++ exited with code 1 [/Users/filipnavara/Projects/llvmbug/llvmbug.csproj]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/15.0.100-preview.7.230/targets/Xamarin.Shared.Sdk.targets(847,3): error :          [/Users/filipnavara/Projects/llvmbug/llvmbug.csproj]
```

Looks like the LLVM compiler didn't get passed the `-target arm64-apple-ios14.2-macabi`. Note that other targets use `-mtriple=...` which doesn't work on MacCatalyst AFAIK.

**Comment by lambdageek** [comment]
*Update* /cc @directhex @akoeplinger - may just be an issue with the AOT compiler task, not with codegen per se

**Comment by directhex** [comment]
> _Update_ /cc @directhex @akoeplinger - may just be an issue with the AOT compiler task, not with codegen per se

the error in Filip's output sure looks that way
