### ISSUE TITLE
Unpin C# compiler version

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#57583]
We're currently pinning the version of the C# compiler to use to make sure we're using a new enough one for new C# 10 features.  We should make sure a new enough compiler is flowing in and then stop pinning it; otherwise, we're missing out on compiler fixes/improvements.
https://github.com/dotnet/runtime/blob/3e3b00c53b127ec20e1d4d74bb75992fb650e08a/eng/Versions.props#L20-L21

**Comment by ViktorHofer** [comment]
We should be able to unpin the compiler with the next Arcade update in both main and release/6.0. I would want to see that happening in the release branch as well to make sure that we use a coherent version of the compiler.

**Comment by ViktorHofer** [comment]
Will be fixed with https://github.com/dotnet/runtime/pull/57627 and https://github.com/dotnet/runtime/pull/57628.

**Comment by ericstj** [comment]
Closing this as referenced PRs have been merged.
