### ISSUE TITLE
[API Proposal]: Add UnicodeRanges.ArabicExtendedB to System.Text.Encodings.Web

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#57609]
## Proposal

```cs
namespace System.Text.Unicode
{
    // existing type
    public static class UnicodeRanges
    {
        // new API
        public static UnicodeRange ArabicExtendedB { get; }
    }
}
```

## Discussion

When new versions of Unicode are released, we ingest them into .NET. Typically this ingestion is nothing more than updating the data tables backing _System.Private.CoreLib_ and _System.Text.Encodings.Web_ and does not require new API surface. However, on occasion Unicode will add new blocks to the BMP, and since we expose block information via the [`UnicodeRanges`](https://apisof.net/catalog/9b78b6d7-9bb2-ab8f-8b6e-d4ceef8150e7) type, we need to update that type to account for these introductions. This allows consumers of _System.Text.Encodings.Web_ to granularly allow or disallow characters from these blocks to appear unescaped on the wire.

The file which contains these APIs is located [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/src/System/Text/Unicode/UnicodeRanges.generated.cs) and is generated [by a tool](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Encodings.Web/tools/GenUnicodeRanges/Program.cs).

As part of https://github.com/dotnet/runtime/issues/44423, when Unicode 14.0 is released on September 14, we will ingest that data into .NET 7. They're adding a new block _Arabic Extended-B_ to the BMP ([more info](https://www.unicode.org/charts/PDF/Unicode-14.0/U140-0870.pdf)). This API proposal is to support this new block's usage within our apps.

**Comment by terrajobst** [comment]
This looks very reasonable

**Comment by GrabYourPitchforks** [comment]
@terrajobst What would be *really* nice is if I could correct the capitalization on some existing properties without breaking consumers. ;)

**Comment by tarekgh** [comment]
> What would be really nice is if I could correct the capitalization on some existing properties without breaking consumers. ;)

Expose a new property with right capitalization and hide the old ones :-)

**Comment by terrajobst** [comment]
Meh. Crypto is living proof that having the wrong capitalization isn't a world ending event :-)

**Comment by tarekgh** [comment]
> Meh. Crypto is living proof that having the wrong capitalization isn't a world ending event :-)

I was kidding :-) 
One option we can file issue for C# compiler to be not case sensitive and just break the world :-) ... kidding again.

**Comment by terrajobst** [comment]
There is *virtualized* casing mode for the C# compiler, called `vbc` 😝

**Comment by terrajobst** [comment]
Looks good as proposed

```C#
namespace System.Text.Unicode
{
    // existing type
    public static class UnicodeRanges
    {
        // new API
        public static UnicodeRange ArabicExtendedB { get; }
    }
}
```

**Comment by bgrainger** [comment]
> The file which contains these APIs is located here and is generated by a tool.

I opened a PR with the updates from running the tool: https://github.com/dotnet/runtime/pull/63901
