### ISSUE TITLE
[QUIC] Developers have QUIC library so they can develop their own protocols on top

### ISSUE THREAD

**Issue by samsp-msft** [dotnet/runtime#57601]
Provide a QUIC API as part of System.Net.QUIC that can be used by 3rd parties.

**Comment by karelz** [comment]
System.Net.Quic APIs are now part of 7.0 as Preview (to reserve option to change them in next release, once we have some dogfooders).
If you have feedback on 7.0 Quic APIs (positive or constructive), please let us know ASAP.
