### ISSUE TITLE
[API Proposal]: Allow the user to explicitly choose the algorithm used by System.Random

### ISSUE THREAD

**Issue by JimmyCushnie** [dotnet/runtime#57624]
### Background and motivation

#47085, merged for .NET 6, introduced some impressive upgrades to the algorithm behind `System.Random`. The new algorithm is dramatically faster, and it also doesn't have the old implementation's limitations in terms of observed mathematical randomness (#23198).

However, the old implementation was still kept around for backwards compatibility. It is used when providing an explicit seed to the `Random`, so that the same seed will produce the same sequence both before and after .NET 6.

To me this seems a very unfortunate situation. There are lots of scenarios where one would want to seed their RNG but still benefit from the faster performance and increased randomness, for example procedural generation in video games.

This proposal would add an advanced API that allows users to explicitly choose which algorithm is used by the `Random`. Users could have a Xoshiro `Random` with a specific seed, something that is currently not possible.

### API Proposal

```C#
namespace System
{
    public class Random
    {
        /// <summary>
        /// These are the supported algorithms used by <see cref="Random"/> to generate pseudo-random numbers.
        /// </summary>
        public enum ImplementationAlgorithm
        {
            Unknown = 0,

            /// <summary> 
            /// This was the original algorithm used until .NET 6. 
            /// </summary>
            KnuthSubtractive,

            /// <summary> 
            /// This is a new algorithm introduced in .NET 6, optimized for 32-bit systems. 
            /// </summary>
            Xoshiro128StarStar,

            /// <summary> 
            /// This is a new algorithm introduced in .NET 6, optimized for 64-bit systems. 
            /// </summary>
            Xoshiro256StarStar,
        }

        public ImplementationAlgorithm Algorithm { get; }

        public Random(ImplementationAlgorithm algorithm);
        public Random(ImplementationAlgorithm algorithm, int seed);
    }
}
```     

### API Usage

```C#
var fastSeededRandom = new Random(Random.ImplementationAlgorithm.Xoshiro256StarStar, seed: 6969);
```     

### Risks

None that I'm aware of.

**Comment by JimmyCushnie** [comment]
If folks agree that this is a good change and should be implemented, I would like to take on implementing it and I request that the issue be assigned to me. It would be a great honor to have my code in .NET.

**Comment by GrabYourPitchforks** [comment]
There was significant discussion on this point over at https://github.com/dotnet/runtime/issues/23198. Consensus was that we don't want the `Random` class to become an in-box dumping ground of individual algorithms that fulfill target scenarios and that we don't want people taking a dependency on the fact that a Xoshiro-based algorithm is provided in-box.

**Comment by JimmyCushnie** [comment]
That is fair enough. Any user who does need this advanced functionality can just make their own `XoshiroRandom` class based on the .NET code. I was planning to do that myself, but I figured it'd be good etiquette to try contributing upstream first.

Gonna leave this issue open for now to wait for more feedback & thoughts.

**Comment by JimmyCushnie** [comment]
Okay, on further reflection I 100% agree. `System.Random`'s implementation should be totally opaque to the user.
