### ISSUE TITLE
Every minor version of .NET 5 exist at the same time

### ISSUE THREAD

**Issue by doyenho** [dotnet/runtime#57629]
The minor version should replace the older version, else they will occupy large disk space, no many garbage files there.

**Comment by KalleOlaviNiemitalo** [comment]
This might be a duplicate of <https://github.com/dotnet/installer/issues/7368>, if the leftover directories were empty. However, @doyenho mentioned "many garbage files".

**Comment by NikolaMilosavljevic** [comment]
[Triage] @doyenho can you share the steps to get to the state you see on your machine? Which installers did you run, etc?

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing, not enough information to investigate this issue.
