### ISSUE TITLE
Missing .yml dependency in Mono llvmaot Pri0 Runtime Tests job

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#57645]
In https://github.com/dotnet/runtime/pull/57637/checks?check_run_id=3361778536 the `Mono llvmaot Pri0 Runtime Tests Run Linux x64 release` job failed because it tried to download the `CoreCLRProduct___Linux_x64_release` artifact but the job that was supposed to produce that artifact (`CoreCLR Product Build Linux x64 release`) failed too.

This means we're missing a `dependsOn` since the llvmaot job shouldn't have started when the CoreCLR product build job failed.

/cc @fanyang-mono @naricc @imhameed

**Comment by SamMonoRT** [comment]
@naricc @akoeplinger - is this still a problem, how are current jobs handling a build/dependency failed case ? Can we close this issue ?

**Comment by naricc** [comment]
This will be fixed when this is fixed: https://github.com/dotnet/runtime/issues/45521

**Comment by SamMonoRT** [comment]
@jandupej - sending your way, this is related to #45521 in your queue. Low priority.

**Comment by kotlarmilos** [comment]
Closing this issue. Please re-open if still relevant.
