### ISSUE TITLE
Question: Limits of loaded assemblies

### ISSUE THREAD

**Issue by AndreasHeisel** [dotnet/runtime#57652]
Hello .NET-Team,

are there any limits regarding the count of loaded assemblies? 

Background: Roslyns CSharpScript is a cool tool, but it generates a new assembly per script. We plan an application that heavily relies on scripting.  If we use CSharpScript, that would mean a lot of assemblies.

Thanks

**Comment by jkotas** [comment]
There is no artificial limit. The number of assemblies that can be loaded is limited by amount of available memory only (and the range of 32-bit numbers).

However, some of the internal algorithms in the runtime are `O(#loaded_assemblies)`. You may see degraded performance as you load many assemblies.

**Comment by AndreasHeisel** [comment]
Thanks @jkotas. 

Are there practical experiences when the performance degradation becomes noticeable? 100, 1,000 10,000 100,000?

Would a solution that uses fewer assemblies with more types perform better?

**Comment by jkotas** [comment]
> Are there practical experiences when the performance degradation becomes noticeable? 100, 1,000 

I would say that it becomes noticeable in various places above 1000 loaded assemblies.

For example, run this in Visual Studio:
```
using System;
using System.Reflection;
using System.Reflection.Emit;

for (int i = 0; i < 10_000; i++)
{
    AssemblyBuilder.DefineDynamicAssembly(new AssemblyName($"MyAssembly{i}"), AssemblyBuilderAccess.Run);
}

Console.WriteLine("Hello World!");
```
Set a breakpoint at `Console.WriteLine("Hello World!")` and go to Debug - Windows - Modules in the menu.

> Would a solution that uses fewer assemblies with more types perform better?

Yes.
