### ISSUE TITLE
Remove code guarded by FEATURE_READYTORUN_COMPILER (outside of the coreclr/jit directory. It is still used there)

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#57659]
This code is now dead with the removal of crossgen1.

**Comment by am11** [comment]
> outside of the coreclr/jit directory. It is still used there

Would it make sense to delete it from jit as well? when/if this feature's definition is deleted from clrdefinitions.cmake, this condition will become dead: https://github.com/dotnet/runtime/blob/dc25ef85cbf10cec91957030f320873fd71c1c11/src/coreclr/jit/CMakeLists.txt#L51-L53

**Comment by jkoritzinsky** [comment]
For the JIT, we could move it to use a `FEATURE_READYTORUN` define instead of the `FEATURE_READYTORUN_COMPILER` define, but we can't delete it the same way since the code is still used.

**Comment by am11** [comment]
Ah right. I wasn't paying enough attention. It has the same name but different meaning in the JIT. Renaming it makes sense.
