### ISSUE TITLE
JSON source generator misses JsonSerializerContext in root namespace

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#57663]
### Description

When the derived JsonSerializerContext type is in the root namespace the source generator misses it.

### Configuration

.NET 6.0 preview 7, CLI.

### Regression?
No

Repro:
```c#
using System.Text.Json.Serialization;

// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");

public class MyJsonData
{
    public string Id {  get; set; }
}

[JsonSerializable(typeof(MyJsonData))]
internal partial class MyJsonContext : JsonSerializerContext
{
}
```

**Expected**: successful compile

**Actual**: `error CS0534: 'MyJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'`

**Comment by eiriktsarpalis** [comment]
Duplicate of #56920?

**Comment by ericstj** [comment]
Dang it, I searched but I somehow missed it.  Thanks!
