### ISSUE TITLE
HelloiOS failing on CI with exit code 1

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#57666]
fail: Application has finished with exit code 1 but 42 was expected

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1301425&view=logs&j=accacb66-0a14-52ef-4079-6344686d9d4c&t=34fbd35e-866b-51a1-9063-fb50703b1957
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57208-merge-a4448e0ceaaa4674bd/HelloiOS/1/console.278950b6.log?sv=2019-07-07&se=2021-09-07T16%3A18%3A09Z&sr=c&sp=rl&sig=9gsD9dTlrxlcXIhyd8AkMi2OIYk8s%2Fa5ifkI3IgIIJg%3D

**Comment by steveisok** [comment]
From the looks of the logs produced, it seems related to https://github.com/dotnet/xharness/issues/692
