### ISSUE TITLE
Support Svg class or ISvg interface 

### ISSUE THREAD

**Issue by reader-man** [dotnet/runtime#57679]
Hi,
Thanks for the great job on .net 6.

I would like to ask for adding an Svg class or at least an ISvg interface, to handle the growing need for smaller size resources that can scale easily on any DPI size.

for starter, it can have functions to return an image object, with the specified size.
load from an svg file or stream.
and maybe if there is time, some matrix transformations.

if the there is no time for the class, then at least the ISvg interface with sufficient functionality, will be good, so other developers can implement on it.

Regards.

**Comment by JeremyKuhne** [comment]
As System.Drawing.Common is a GDI/GDI+ wrapper and only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now, this feature is out of scope. Please see our [recommendations](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#recommended-action) for other libraries to consider.
