### ISSUE TITLE
Move from .Net Core 3.1 to .Net 6 missing components?

### ISSUE THREAD

**Issue by ddemland** [dotnet/runtime#57680]
Move from .Net Core 3.1 to .Net 6 missing components?
I am at a lost. I have an application that was originally created in .Net Framework and last year moved it to .Net Core 3.1 with little trouble. I am now using Visual Studio 2022 Preview and .Net 6 Version 7 Preview to test moving to .Net 6. Overall not to many issues but I have a couple that I just cannot seem to find answers to:

•	System.Configuration does not seem to include ConfigurationSection or ConfigurationElement which is leading to ConfigurationProperty being undefined. Where are these now?
•	System.Windows.Data does not seem to included anywhere and this leaves both ValueConversion as an attribute and IValueConverter undefined.

These errors lead to these messages:

•	The type name 'ConfigurationElement' could not be found in the namespace 'System.Configuration'. This type has been forwarded to assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.	ReaderGui.Core	C:\Repositories\Translator\LogReader6\ReaderGui.Core\Config\GeneralElement.cs
•	The type name 'ConfigurationPropertyAttribute' could not be found in the namespace 'System.Configuration'. This type has been forwarded to assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.	ReaderGui.Core	C:\Repositories\Translator\LogReader6\ReaderGui.Core\Config\GeneralElement.cs
•	The type name 'ConfigurationProperty' could not be found in the namespace 'System.Configuration'. This type has been forwarded to assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.	ReaderGui.Core	C:\Repositories\Translator\LogReader6\ReaderGui.Core\Config\GeneralElement.cs

What am I missing in this upgrade?

Thank You,

David

**Comment by ddemland** [comment]
I am sorry I did not do that right. Here is the configuration:

`  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
  </PropertyGroup>
`

**Comment by ddemland** [comment]
I guess I am still at a loss. This is what the .csproj file looks like:

`
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevExpress.WindowsDesktop.Wpf" Version="20.2.8" />
    <PackageReference Include="FrameworkExtract.System.Deployment" Version="4.0.30319" />
    <PackageReference Include="Telerik.UI.for.Wpf.NetCore.Xaml" Version="2021.2.615" />
    <PackageReference Include="Telerik.Windows.Controls.Navigation.for.Wpf.Xaml" Version="2021.2.615" />
	<PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReaderGui.Core\ReaderGui.Core.csproj" />
    <ProjectReference Include="..\ReaderGui.DataProviders.PublixInventory\ReaderGui.DataProviders.PublixInventory.csproj" />
  </ItemGroup>

</Project>
`

I have no idea what I still have these two issues:

• System.Configuration does not seem to include ConfigurationSection or ConfigurationElement which is leading to ConfigurationProperty being undefined. Where are these now?
• System.Windows.Data does not seem to included anywhere and this leaves both ValueConversion as an attribute and IValueConverter undefined.

All the information on .Net 6, on the Internet, state that these are all in .Net 6. Yet I cannot get them to compile. How do I fix this?

Thank You,

David

**Comment by ddemland** [comment]
Here are the references I am referring to:

https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.valueconversionattribute?view=net-5.0
https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.ivalueconverter?view=net-5.0

Both of these show .Net 6 Preview 7 is supported and that is what I am using. The page: https://stackoverflow.com/questions/66015639/cannot-import-system-windows-data shows that a reference can be added to the System.Windows.Data DLL. However, in Visual Studio 2019 or Visual Studio 2022 Preview, this link does not exist. Can a reference to System.Windows.Data be added to a project and if so how?

I really need the help to get this working.

Thank You,

David

**Comment by KalleOlaviNiemitalo** [comment]
> The type name 'ConfigurationElement' could not be found in the namespace 'System.Configuration'. This type has been forwarded to assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. ReaderGui.Core C:\Repositories\Translator\LogReader6\ReaderGui.Core\Config\GeneralElement.cs

It was compiling a file in ReaderGui.Core.  However, in [ReaderGui.txt](https://github.com/dotnet/runtime/files/7034253/ReaderGui.txt), you have `<PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-*" />` and `<ProjectReference Include="..\ReaderGui.Core\ReaderGui.Core.csproj" />`, so this is not the ReaderGui.Core project itself but rather one that refers to it.  Should you add the PackageReference into ReaderGui.Core.csproj, instead?

**Comment by ddemland** [comment]
I finally figured this out. First I needed to add the NuGet package System.Configuration.ConfigurationManager. Then I had to changed all the projects I had create to define net6.0-windows since VS 2022 Preview only defined them as net6.0. After that I just had to clean up some reference issues and now it builds. This can be closed.

**Comment by joperezr** [comment]
Hello @ddemland sorry for the troubles you had and that it took us this long to look into this issue. As you figured out, what you were missing was a package reference to System.Configuration.ConfigurationManager which is the one that defines ConfigurationSection and ConfigurationElement types in .NET 6. For future reference, I recommend using the [portability analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) which will help you find out if all types exist when retargeting your projects, as well as the use of [APIsOf.NET](https://apisof.net/) site which will help you find if a type exists in a framework and where is it implemented. In your example above, you can use the site to find the required package reference:

![image](https://user-images.githubusercontent.com/13854455/131547845-7859f379-516f-449b-ab8e-e0cdbdf5ea9a.png)
