### ISSUE TITLE
System.Text.Json: custom equality comparer

### ISSUE THREAD

**Issue by bugproof** [dotnet/runtime#577]
newtonsoft json supports `EqualityComparer` property in serializer settings, is this option planned in System.Text.Json?

**Comment by ahsonkhan** [comment]
In what scenario are you using [`EqualityComparer`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_EqualityComparer.htm), @bugproof 

I would like to know more about your requirements and use case.

**Comment by bugproof** [comment]
I am using `ReferenceEqualityComparer` that compares by reference to avoid duplicate objects in serialized JSON IIRC.

```cs
public sealed class ReferenceEqualityComparer : IEqualityComparer, IEqualityComparer<object>
{
    public static ReferenceEqualityComparer Default { get; } = new ReferenceEqualityComparer();

    private ReferenceEqualityComparer() {}

    public bool Equals(object x, object y) => ReferenceEquals(x, y);
    public int GetHashCode(object obj) => RuntimeHelpers.GetHashCode(obj);
}
```

**Comment by ahsonkhan** [comment]
The default behavior of the `ReferenceHandling` feature within `System.Text.Json` that is coming for 5.0 will use `ReferenceEquals`. I believe that means you wouldn't need that custom equality comparer.

See this spec and issue for more details:
https://github.com/dotnet/runtime/blob/cc1ac66d0a0df6e9139431a7fa42636050ce9a6d/src/libraries/System.Text.Json/docs/ReferenceHandling_spec.md
https://github.com/dotnet/corefx/issues/41002

Let me know if that works for your scenario.
Thanks!

**Comment by bugproof** [comment]
It should work but we'll see https://stackoverflow.com/questions/46936395/why-doesnt-reference-loop-detection-use-reference-equality?rq=1

**Comment by ahsonkhan** [comment]
> making it default in system.text.json will be great

Great. Marking this as future.

**Comment by layomia** [comment]
The reference handling handling feature uses `ReferenceEquals` by default, which is what is being requested here. If this doesn't work for you, please feel free to reopen with your scenario.
