### ISSUE TITLE
Some MethodInfo(s) of array types loaded by MetadataLoadContext are incorrectly evaluated as equal.

### ISSUE THREAD

**Issue by shin1m** [dotnet/runtime#57728]
### Description

Some MethodInfo(s) of array types loaded by MetadataLoadContext are incorrectly evaluated as equal.
They are expected not to be equal.

```
        [Fact]
        public void MethodsShouldBeDistinguished()
        {
            using var context = new MetadataLoadContext(new PathAssemblyResolver(Directory.EnumerateFiles(RuntimeEnvironment.GetRuntimeDirectory(), "*.dll").Append(typeof(ArrayTests).Assembly.Location)));
            Type project(Type x) => context.LoadFromAssemblyName(x.Assembly.FullName).GetType(x.FullName, true);
17          void test(Type type) => Assert.NotEqual(type.GetMethod("Get"), type.GetMethod("Set"));
            test(typeof(int[]));
19          test(project(typeof(int[])));
        }
```

```
  Failed MLCTests.ArrayTests.MethodsShouldBeDistinguished [54 ms]
  Error Message:
   Assert.NotEqual() Failure
Expected: Not System.Int32 Get(System.Int32)
Actual:   System.Void Set(System.Int32, System.Int32)
  Stack Trace:
     at MLCTests.ArrayTests.<MethodsShouldBeDistinguished>g__test|0_1(Type type) in .../MLCTests/ArrayTests.cs:line 17
   at MLCTests.ArrayTests.MethodsShouldBeDistinguished() in .../MLCTests/ArrayTests.cs:line 19
```

[MLCTests.tar.gz](https://github.com/dotnet/runtime/files/7014561/MLCTests.tar.gz)

### Configuration

* System.Reflection.MetadataLoadContext      5.0.1

```
$ LANG=C dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   .../sdk/6.0.100-preview.5.21302.13/

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b
```

### Other information

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoArrayType.cs#L150

In the above method, Get, Set, and Address can have same `uniquifier`  between calls.
I think `uniquifier` should be consistent for a MetadataLoadContext instance.

**Comment by joperezr** [comment]
Thanks for the report @shin1m. Do you know if this is a regression from 5.0? cc @steveharter

**Comment by shin1m** [comment]
@joperezr cc @steveharter 

> Thanks for the report @shin1m. Do you know if this is a regression from 5.0? cc @steveharter

Sorry, I don't know if or not because 5.0.1 is the first version to me.
According to [this view](https://github.com/dotnet/runtime/blame/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoArrayType.cs#L150), the code comes from https://github.com/dotnet/corefx/pull/33201 written 3 years ago.

Regards,

**Comment by shin1m** [comment]
@buyaa-n the error message of `Assert.NotEqual()` is confusing.
The test case says that Get and Set should NOT be EQUAL, but it fails.

The other assertions fail as well:
```
var get = type.GetMethod("Get");
var set = type.GetMethod("Set");
// get and set should not be equal.
// all assertions below fail for array types loaded by MetadataLoadContext.
Asssert.False(get.Equals(set));
Asssert.True(get != set);
Asssert.False(get == set);
```

**Comment by buyaa-n** [comment]
> Look carefully at 'Other information' of the issue.

Oops, sorry did not notice that

> An easy way would be to assign constant uniquifiers to Get/Set/Address.

If that is the case then the `uniquifier` is redundant, doesn't seem we need that at all

**Comment by joperezr** [comment]
cc: @steveharter PTAL regarding the need of `uniquifier`

**Comment by steveharter** [comment]
> An easy way would be to assign constant uniquifiers to Get/Set/Address.
>> If that is the case then the uniquifier is redundant, doesn't seem we need that at all

Although currently `uniquifier` is not needed due to adding the `ReturnType` in the last PR (which by coincidence is unique across the 3 methods), keeping the `uniquifier`, but making it hard-coded instead (e.g. 0=Get; 1=Set; 2=Address) would still be good to make the code more clear and consistent with the other areas that use `uniquifier`. Currently since it is incremental it is broken.

**Comment by buyaa-n** [comment]
> keeping the uniquifier, but making it hard-coded instead

That is even better as do not need the ReturnType check anymore
