### ISSUE TITLE
[HTTP/3] Loopback server should dispose underlying QUIC connection

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#57779]
The logic to do this is currently disabled: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs#L57

We should re enable this and fix tests accordingly.

**Comment by karelz** [comment]
Triage: We disabled the behavior to make tests pass on all versions of HTTP -- we will have to review the failures again once we work on this.

**Comment by karelz** [comment]
Triage: Try it and see what it does. If there are too many issues, we are fine with Future.

**Comment by ManickaP** [comment]
Let's revisit this while working on `CloseAsync`/`DisposeAsync` in https://github.com/dotnet/runtime/issues/68902
