### ISSUE TITLE
AES using legacy code The string after encryption and decryption is not equivalent to the original one

### ISSUE THREAD

**Issue by aplib** [dotnet/runtime#57808]
.NEt 5-6 (latest net framework versions?)
AES implementation incompatibility with 4.0) (not sure if the code is correct)
The string after encryption and decryption is not equivalent to the original one
```
samples (legacy code):

// AES Encryption
var encryptor = Aes.Create();
var key = rfc.GetBytes(16);
var IV = rfc.GetBytes(16);
encryptor.Key = key;
// This field is not assigned:
encryptor.IV = IV; // **BUG** 
// Partially random result when used this:
encryptor.CreateEncryptor()      // Not correct
encryptor.CreateEncryptor(key, IV)  // Correct using

// AES Decryption
// Symmetrical decryption behavior:
var decryptor = Aes.Create();
var key = rfc.GetBytes(16);
var IV = rfc.GetBytes(16);
decryptor.Key = key;
// This field is not assigned:
decryptor.IV = IV;  // **BUG**
// Partially random result when used this:
decryptor.CreateDecryptor()      // Not correct
decryptor.CreateDecryptor(key, IV) // Correct using
```
Input:

"Parameter1=1,Parameter1=1,Parameter1=1,Parameter1=1,Parameter1=1"

Output:

"��pX.�a�n}��Oxameter1=1,Parameter1=1,Parameter1=1,Parameter1=1"

### Configuration
.NET 5-6 last and previous versions

### Regression?
Works legacy code from Net framework 4.0

**Comment by vcsjones** [comment]
Hm. I'm having a bit of a hard time reproducing the issue that you are reporting. It sounds like you are saying that the `IV` property is being ignored when using `CreateEncryptor()` or `CreateDecryptor()` . I tried to reproduce this with no luck:


```csharp
using System;
using System.Security.Cryptography;

using var aes = Aes.Create();
using var rfc = new Rfc2898DeriveBytes("mypassword", salt: new byte[8]);

aes.Key = rfc.GetBytes(16);
aes.IV = rfc.GetBytes(16);
using var encryptor = aes.CreateEncryptor();
var encrypted = encryptor.TransformFinalBlock(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 }, 0, 8); 

Console.WriteLine(BitConverter.ToString(encrypted));

using var aes2 = Aes.Create();
aes2.Key = aes.Key;
aes2.IV = aes.IV;
using var decryptor = aes.CreateDecryptor();
var decrypted = decryptor.TransformFinalBlock(encrypted, 0, encrypted.Length);

Console.WriteLine(BitConverter.ToString(decrypted));
```

This produces identical output from .NET Framework 4.8 to .NET 5.

Can you adapt this sample program to reproduce the issue, or creating a running program that reproduces the issue?

I don't see anything in the code that would indicate there is an issue, either:

https://github.com/dotnet/runtime/blob/1313a689fd5e1d282f8910a4c77fbe15315d6d98/src/libraries/System.Security.Cryptography.Algorithms/src/Internal/Cryptography/AesImplementation.cs#L11-L29
