### ISSUE TITLE
Remove debian 9 and add debian 11 to helix queues

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57837]
Based on our official support matrix we don't support Debian 9 for .NET 6 anymore: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md.

Also as Debian 11 has released, we should add it to our helix queues: 
- https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/helix-queues-setup.yml
- https://github.com/dotnet/runtime/blob/main/eng/pipelines/coreclr/templates/helix-queues-setup.yml

Target: We need this in both release/6.0-rc1 and main. I should have opened the issue sooner...

cc @am11 in case you want to pick this up. Hopefully this is easier than the alpine 3.14 change.

**Comment by am11** [comment]
Sure. I can take a look.

> Hopefully this is easier than the alpine 3.14 change.

Hopefully, lets see what helix thinks about bullseye.. 😁
