### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by CeSun** [dotnet/runtime#57840]
Environment: Android->Termux->Ubuntu20.04(install by proot)

Any command executed is wrong, error info is "Segmentation fault".

```
root@localhost:~/dotnet# dotnet

Usage: dotnet [options]
Usage: dotnet [path-to-application]

Options:
  -h|--help         Display help.
  --info            Display .NET information.
  --list-sdks       Display the installed SDKs.
  --list-runtimes   Display the installed runtimes.

path-to-application:
  The path to an application .dll file to execute.
root@localhost:~/dotnet# dotnet --info
Segmentation fault
```

**Comment by am11** [comment]
proot is a chroot environment where coreclr sometimes [does not work well](https://github.com/dotnet/runtime/issues/33051), especially if the environment is missing some modern (kernel v4 / v5) syscalls.

I don't have Android atm, but could you try `PROOT_NO_SECCOMP=1 dotnet --info`?

If not, you can trace:
```sh
COREHOST_TRACE=1 COREHOST_TRACE_VERBOSITY=4 dotnet --info
```
and/or natively, if `strace(1)` is available:
```sh
strace -f dotnet --info
```
to find out the sigsegv origin.
