### ISSUE TITLE
[API Proposal]: Change behaviour of Setting SymmetricAlgorithm.KeySize (Or add documentation)

### ISSUE THREAD

**Issue by Insomniak47** [dotnet/runtime#57859]
### Background and motivation

System.Security.Cryptography's SymmetricAlgorithm class has a bit of a surprising API. Unfortunately since it backs so many things I think it might be hard to make meaningful changes to but I'd like to propose a few options that I think could make it a bit easier to figure out what's going wrong.

The main issue is that setting KeySize nulls out the key. I wouldn't think that it'd have to be set most of the time but there's a few examples on StackOverflow of people finding out that explicitly setting it causes problems. I think that if the idea is to support key generation without being explicit about it then it would make sense for setting a keysize through the public setter when the key is already set to throw an exception. InvalidOperation seems to fit given that it's based on an invalid state of the object. 

Alternatively since that would be a breaking change the documentation of KeySize in the XML docs would be useful. It could just have remarks added to it to indicate the behaviour so people (like myself). Don't have to dredge around for it since the current (in IDE) docs don't mention it at all.

ex:
```cs
        //
        // Summary:
        //     Gets or sets the size, in bits, of the secret key used by the symmetric algorithm.
        //
        // Returns:
        //     The size, in bits, of the secret key used by the symmetric algorithm.
        //
        // Exceptions:
        //   T:System.Security.Cryptography.CryptographicException:
        //     The key size is not valid.
        public virtual int KeySize { get; set; }
```

I'd be happy to make any changes to make this a bit easier to use

### API Proposal

Add IOE when KeySize is set after key has been set. Alternatively add documentation about the behaviour of the setter of KeySize in a way that you don't have to track through the docs to find out. 

### API Usage

```C#
namespace System.Collections.Generic
{
	public void DoTheThingCurrently(byte[] key)
	{
		var aes = Aes.Create();
        aes.Key = key;
        aes.KeySize = key.Length*8
        // Key is now null
        // :(
	}

	public void DoTheNewThing(byte[] key)
    {
		var aes = Aes.Create();
        aes.Key = key;
        aes.KeySize = key.Length*8;
        // InvalidOperationException thrown with appropriate message explaining what has happened.
    }
}
```     

### Risks

The exception change would be breaking for specific cases so it would introduce some risk to people who were doing something along the lines of creating an AES and repeatedly setting the keysize. As well there would be places internally that would have to null things before re-setting the KeySize value and internal access to it may have to route to a new backing field instead of the current auto-property

The documentation change would be extremely low cost and would at least make the process of figuring out why you can't decrypt something a bit less frustrating since the current docs don't show the parent classes notes about resetting the key.

**Comment by bartonjs** [comment]
All of the crypto classes (are supposed to) generate new keys when the key size is changed.  I don't think we're going to take a breaking change here.

The documentation could/should be clearer, though.

**Comment by GrabYourPitchforks** [comment]
Since the `Aes` type does not override the _KeySize_ property, the docs for this type already inherit the base type's docs, including the "it resets the key" disclaimer.

https://docs.microsoft.com/dotnet/api/system.security.cryptography.symmetricalgorithm.keysize

What's the particular doc improvement being suggested?

**Comment by Insomniak47** [comment]
Hey all, as you can see from my snippet that doesn't come up in the IDE or within the docs when you jump to definition nothing comes up.

**Comment by Insomniak47** [comment]
> All of the crypto classes (are supposed to) generate new keys when the key size is changed

Just curious what the design rationale for that is. From a consumer perspective I'm sure you can see why it would be confusing that setting the size of the key would change the key itself especially if I've explicitly set the key.

**Comment by GrabYourPitchforks** [comment]
> Just curious what the design rationale for that is.

This behavior predates our time on the team. But if I had to guess, I'd say that it's to support scenarios where users wanted the key to be auto-generated on the call to _CreateEncryptor_.

> From a consumer perspective I'm sure you can see why it would be confusing...

If you look through the _area-System.Security_ issues you'll find that most of the current owners lament the design of the legacy crypto APIs. :) They're often confusing or inefficient or just plain head-scratchers. Our time lately has been spent standing up newer, friendlier APIs and migrating folks from the older APIs to the newer APIs. I suspect we'll get around to crafting a replacement for this API weirdness before too long.

**Comment by tshowers-bt** [comment]
> > All of the crypto classes (are supposed to) generate new keys when the key size is changed
> 
> Just curious what the design rationale for that is. From a consumer perspective I'm sure you can see why it would be confusing that setting the size of the key would change the key itself especially if I've explicitly set the key.

I agree; the API doesn't do much to communicate itself. I think the presence of the `GenerateKey` method also confuses things. Based on the code [here](https://github.com/dotnet/runtime/blob/2d3acc6a3dff03f89cc3d08d5f1fb6f5fb3077fc/src/libraries/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/SymmetricAlgorithm.cs#L113) it looks like re-assigning `KeySize` to its current size would still cause a new key to be generated (next time `.Key` was accessed) so having `.GenerateKey` in the public API doesn't really accomplish anything; but the fact that it _does_ exist kind of implies that it would which is part of what makes the behaviour of `KeySize` surprising. If `KeySize` was readonly and `GenerateKey` took a size it would be much more intuitive IMO.

**Comment by Insomniak47** [comment]
@GrabYourPitchforks if you want to let me know the best way to get the docs in (in xml comments on the base type) or something else then I'll be happy to make the doc changes.

**Comment by vcsjones** [comment]
> @GrabYourPitchforks if you want to let me know the best way to get the docs in (in xml comments on the base type) or something else then I'll be happy to make the doc changes.

The docs live in the https://github.com/dotnet/dotnet-api-docs repository. For example, `SymmetricAlgorithm`:

https://github.com/dotnet/dotnet-api-docs/blob/83fce9c61a35c1460c8bb59b17ad8bf06e31c989/xml/System.Security.Cryptography/SymmetricAlgorithm.xml#L1877

**Comment by Insomniak47** [comment]
Hi @vcsjones that's the documentation we're noting doesn't make it into IDE's so I'm not clear on what changes I would have to make to make the changes that we've noted would make things easier.

**Comment by Insomniak47** [comment]
@GrabYourPitchforks  @vcsjones I'd love to pick this up if you guys want to toss that bit of info my way

**Comment by bartonjs** [comment]
> I'd love to pick this up if you guys want to toss that bit of info my way

Done!

**Comment by vcsjones** [comment]
I think there is still an outstanding question:

> Will changing the summary there reflect in the IDE docs?

I'm not sure where Visual Studio derives the text for intelligence hovers and if that data is pulled from the `dotnet-api-docs` repo.

**Comment by Insomniak47** [comment]
Usually it's from XML docs. I'm wondering if it's because the remarks is a cdata block instead of being plaintext.

**Comment by bartonjs** [comment]
> I'm wondering if it's because the remarks is a cdata block instead of being plaintext.

I believe that Visual Studio only shows Summary and Returns (methods) / Value (properties) information, and never shows remarks.

So the change would be to do something like

```diff
      <Docs>
-       <summary>Gets or sets the size, in bits, of the secret key used by the symmetric algorithm.</summary>
+       <summary>Gets or sets the size, in bits, of the secret key used by the symmetric algorithm. Note that assigning a value to this property will reset the <see cref="System.Security.Cryptography.SymmetricAlgorithm.Key" /> property.</summary>
```

**Comment by Insomniak47** [comment]
@bartonjs I'll check on some of my libs tomorrow and if that's the case I'll make the change. Thanks for the help all

**Comment by danmoseley** [comment]
@carlossanlop can you confirm that <remarks> are never shown in intellisense?

**Comment by Insomniak47** [comment]
I know that this is minor but I've got it on my list to follow up on it. Any preferences here? @danmoseley @GrabYourPitchforks
