### ISSUE TITLE
[API Proposal]: Add a GetDebuggerDisplay() to Object

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#57887]
### Background and motivation

```DebuggerDisplayAttribute``` vastly improves the debugging experience but is sub-optimal in how it is used today.  It is sub-optimal because:
1. As an attribute, you cannot (easily) query its value from another class
2. Most implementations use a different value for each class.  For example, ```[DebuggerDisplay("{x} = {y}")] and ```[DebuggerDisplay("{FirstName,nq}")]```.  This bloats the compiled assembly with extra strings.

Having a ```DebuggerDisplayAttribute``` on a class vastly improves the debugging experience.  I personally believe that nearly every class should have a custom DebuggerDisplay.

### API Proposal

```C#
namespace System
{
     [DebuggerDisplay("{GetDebuggerDisplay(),nq}")]
     public class Object
     {
          public virtual string GetDebuggerDisplay();
     }
}
```     

### API Usage

```C#
public class Foo {
  public override string GetDebuggerDisplay(){
    return "Hello World";
  }
}
```     

### Risks

Any class that already has a ```GetDebuggerDisplay``` member would need to be refactored.

**Comment by alexrp** [comment]
Adding new methods to `System.Object` is basically a non-starter due to the compatibility concerns.

**Comment by GrabYourPitchforks** [comment]
> I personally believe that nearly every class should have a custom DebuggerDisplay.

Why? For collection types like `List<T>` and `Dictionary<TKey, TValue>` I can see this, but collections and other "special" types don't represent the majority of types that exist in the .NET ecosystem. Most real-world types are simple data types (think `Person` with simple _FirstName_, _LastName_, etc. properties) or types that implement some specific business logic. For these types, why would the majority of developers want the debugger to display something other than a dump of all the fields / properties on the type?

**Comment by TonyValenti** [comment]
@GrabYourPitchforks -
It would be great if, by default, it dumped the fields similar to what ```records``` do.  Today, if you want to see them, you'll find yourself constantly "expanding" the variable in VS or adding watches.

**Comment by GrabYourPitchforks** [comment]
@TonyValenti If VS had an option to auto-expand objects so that all of their fields & properties were visible by default, would that suffice for your needs?

**Comment by TonyValenti** [comment]
@GrabYourPitchforks - 
When mouse-overing a variable in VS, yes, it should always expand by default.

When adding a watch to a variable, either auto expand or add a column that shows a string that is similar to what would have been generated if the object were a record.

**Comment by AaronRobinsonMSFT** [comment]
@TonyValenti This seems like a reasonable feature request. The best way to get traction on that and determine if it aligns with current plans is to file an issue via https://developercommunity.visualstudio.com/home. An internal feature request will be create for the VS Debugger team.

I will close this for now but if this requires any new .NET support we can reopen it or file a specific issue for the feature support.

/cc @caslan

**Comment by TonyValenti** [comment]
@GrabYourPitchforks  @AaronRobinsonMSFT - Thanks so much!  I opened this link:
https://developercommunity.visualstudio.com/t/Auto-Expand-Object-in-Tooltip/1511762?entry=myfeedback&space=8&preview2=true

And would love it if you'd vote on the feature and nudge whoever would build it.  :-)
