### ISSUE TITLE
SocketException: An existing connection was forcibly closed by the remote host. .net core

### ISSUE THREAD

**Issue by ghost1372** [dotnet/runtime#57895]
### Description
I set up a proxy through Windows settings (Internet Options) (proxy type is pac) now when I try to use httpclient or webclient, I get the following error

```
SocketException: An existing connection was forcibly closed by the remote host. .net core
```
codes

```c#
using (WebClient client = new WebClient())
{
    client.DownloadFile("https://www.github.com", "localfile.html");
}
```
in .Net Framework everythings wotk fine but in .net core 5.0 i get this error

### Configuration

* Which version of .NET is the code running on? 5.0
* What OS and version, and what distro if applicable? 10.0.19043
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration?
* If you're using Blazor, which web browser(s) do you see this issue in?

### Regression?

.NET Framework worked fine

**Comment by ManickaP** [comment]
Have you tried set up the proxy explicitly either as [env variables](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-5.0#remarks) or set up a [Proxy](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.proxy?view=net-5.0) property?

I don't know how far automatic proxy detection from system settings goes @wfurt?

**Comment by ghost1372** [comment]
i tried this
![image](https://user-images.githubusercontent.com/9213496/130427886-9122c102-8554-4739-99a2-c3fbd59d3f87.png)

```
HttpWebRequest request = (HttpWebRequest)HttpWebRequest.Create("https://github.com");    
HttpWebResponse response = (HttpWebResponse)request.GetResponse();
```
and this
```

HttpClient client = new HttpClient();
HttpResponseMessage response = await client.GetAsync("http://www.github.com/");
response.EnsureSuccessStatusCode();
string responseBody = await response.Content.ReadAsStringAsync();
Console.WriteLine(responseBody);
```

but i get error
`SocketException: An existing connection was forcibly closed by the remote host.
`        

i also tried this (i dont know this is correct or not)
```
var handler = new HttpClientHandler();
handler.Proxy = HttpClient.DefaultProxy;
HttpClient client = new HttpClient(handler);
 
```
but did not work

@ManickaP  can you give an example code?

**Comment by ManickaP** [comment]
Try setting up the proxy explicitly, eg. setting up environment variables `HTTP_PROXY` and `HTTPS_PROXY` on command line and then running your program from the same command line.

**Comment by wfurt** [comment]
Do you know what exactly that scrip returns @ghost1372? The PAC processing is generally handled by OS but we had few issues in the past. You can also try to get packet captures with Wireshark to both see the response and see where the client is connecting to. 
If feels like this is specific to your environment so it will be difficult to diagnose from outside.

**Comment by ghost1372** [comment]
@wfurt  i dont know what is returned, also this issue only exist in .Net Core and .Net Framework work without any problem

**Comment by wfurt** [comment]
Wireshark should tell you as well as you can try to fetch it with `curl` or similar tool. Fact that Framework work will not help us to figure out what is going on.

**Comment by karelz** [comment]
Looks like this is not actionable, closing. Feel free to reopen if there are Wireshark traces telling us more what is wrong.
