### ISSUE TITLE
Test failure Microsoft.Extensions.Hosting.Tests.ConsoleLifetimeExitTests.EnsureEnvironmentExitDoesntHang

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#57908]
Run: [runtime-coreclr libraries-jitstress  20210821.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1309768&view=ms.vss-test-web.build-test-results-tab&runId=38558352&paneView=debug&resultId=111321)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open

- Microsoft.Extensions.Hosting.Tests.ConsoleLifetimeExitTests.EnsureEnvironmentExitDoesntHang

```
**Error message:**
```
The hosted process should have exited within 10 seconds
Expected: True
Actual:   False


Stack trace
   at Microsoft.Extensions.Hosting.Tests.ConsoleLifetimeExitTests.EnsureEnvironmentExitDoesntHang() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/ConsoleLifetimeExitTests.cs:line 133
```

Runfo Tracking Issue: [ensureenvironmentexitdoesnthang](https://runfo.azurewebsites.net/tracking/issue/176)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1394020](https://dev.azure.com/dnceng/public/_build/results?buildId=1394020)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a7f1e9a6779148bdba/Microsoft.Extensions.Hosting.Unit.Tests/1/console.958f1bca.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T23%25253A46%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNTyU7SGhtEK4mINwocgfmSx7Djn7Rbg07PP%25252BaO3xKMg%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a7f1e9a6779148bdba/Microsoft.Extensions.Hosting.Unit.Tests/ddc1f7bf-57bb-4b9d-a501-478ce5c51732.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T23%25253A46%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNTyU7SGhtEK4mINwocgfmSx7Djn7Rbg07PP%25252BaO3xKMg%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|1|1|

**Comment by ViktorHofer** [comment]
Happened again in https://dev.azure.com/dnceng/public/_build/results?buildId=1394020&view=ms.vss-test-web.build-test-results-tab&runId=40523928&resultId=106752&paneView=debug.

**Comment by eerhardt** [comment]
It looks like both times this failed, it was on a "slow" coreclr. The first time it was during "jitstress" and this last time it was on a checked x86 coreclr.

Is there a way we can detect when running in these modes, and skip the test in those cases?

**Comment by danmoseley** [comment]
It's usually easier to just increase the timeout. At least if the test is only verifying there's no hang, and in normal circumstances will still complete quickly.

**Comment by danmoseley** [comment]
We have tests eg that I eventually upped to 30s timeout that normally complete in 2s.

**Comment by krwq** [comment]
I've created a PR which increases the timeout up to 30s https://github.com/dotnet/runtime/pull/59811 . If this happens again I'd expect either the configuration be horribly slow or an actual product issue

**Comment by krwq** [comment]
I'll close this issue for now since the timeout is increased. If we see another hit we should re-validate if the test should be changed/timeout increased further/this is an actual product issue
