### ISSUE TITLE
Consider supporting linker scripts on Linux

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#57904]
This code does not work:

	const string libc = "libc.so";
	[DllImport( libc, SetLastError = true, CallingConvention = CallingConvention.Cdecl )]
	public static extern int eventfd( uint initval, eEventFdFlags flags );

To make it work, the dll name must say `libc.so.6`

This is suboptimal because compatibility. C++ linkers, and Linux DLL loader, can parse the `libc.so` text file, and resolve into the actual DLL which is `libc.so.6`. It should not be too hard to do the same in the .NET runtime when processing these `[DllImport]` attributes.

For reference, here’s a content of `libc.so` from some AMD64 Linux I'm using:

```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib/x86_64-linux-gnu/libc.so.6 /usr/lib/x86_64-linux-gnu/libc_nonshared.a  AS_NEEDED ( /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 ) )
```

**Comment by am11** [comment]
> To make it work, the dll name must say `libc.so.6`

or use name without the extension:

```diff
- const string libc = "libc.so";
+ const string libc = "libc";
[DllImport( libc, SetLastError = true, CallingConvention = CallingConvention.Cdecl )]
public static extern int eventfd( uint initval, eEventFdFlags flags );
```
native library resolver can also be used if the built-in resolution is not sufficient:

```c#
using System;
using System.Reflection;
using System.Runtime.InteropServices;

class C
{
    const string libc = "my-libc.so";
    [DllImport(libc, SetLastError = true, CallingConvention = CallingConvention.Cdecl)]
    static extern int getpid();

    // set resolver in static constructor (in there, parse linker script etc.)
    static C() => NativeLibrary.SetDllImportResolver(typeof(C).Assembly,
        (string libraryName, Assembly assembly, DllImportSearchPath? searchPath) =>
            libraryName == "my-libc.so" ? NativeLibrary.Load(nameof(libc)) : IntPtr.Zero);

    static void Main() => Console.WriteLine("pid: {0}", getpid());
}
```

**Comment by Const-me** [comment]
@am11 Thanks, it worked.
