### ISSUE TITLE
[JitStressWithRandomNumbers] Assertion failed '!genIsValidFloatReg(reg) Generate code'

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#57911]
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-f26c04388af241ca9d/JIT.Regression/1/console.f621fe1b.log?sv=2019-07-07&se=2021-09-12T00%3A10%3A43Z&sr=c&sp=rl&sig=xX%2FwSE9hoH%2FWaOhtQFIwGMXAc9V3kIgeQes1vC4jiNM%3D

repro steps:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=99
JIT\Regression\VS-ia64-JIT\V1.2-M02\b17023\b17023\b17023.cmd
```
Failure log:
```
    Assert failure(PID 2352 [0x00000930], Thread: 5852 [0x16dc]): Assertion failed '!genIsValidFloatReg(reg)' in 'MyTest:Main():int' during 'Generate code' (IL size 20)
      
          File: D:\workspace\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 34
          Image: C:\h\w\B1AA09D8\p\corerun.exe
```

the issue from a quality week JitStress experiment.

**Comment by BruceForstall** [comment]
I don't think this meets the .NET 6 bar; moving to 7.0
