### ISSUE TITLE
[JitStressWithRandomNumbers]  ObjectStackAllocationTests is failing with `COMPlus_JitStress=8`.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#57910]
we probably just need to add a few more `COMPlus_JitStressModeNamesNot` values to https://github.com/dotnet/runtime/blob/2c93c89548f307f8087b6fd5cfe1d90727821eee/src/tests/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests.csproj#L20

Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-8ae5e4b1155b45a69f/JIT/1/console.1cf10682.log?sv=2019-07-07&se=2021-09-11T23%3A48%3A09Z&sr=c&sp=rl&sig=3rGNPn3G41MYciL2XvwhFNFi2Z6hsT1g6UnU9%2FNqR84%3D

repro x64 windows:
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=8
JIT\opt\ObjectStackAllocation\ObjectStackAllocationTests\ObjectStackAllocationTests.cmd
```

the issue from a quality week JitStress experiment.

**Comment by BruceForstall** [comment]
Found many cases of this in a new random JitStress run:

https://dev.azure.com/dnceng/public/_build/results?buildId=1950662&view=ms.vss-test-web.build-test-results-tab&runId=50202566&resultId=103618&paneView=debug

Should we just disable it for JitStress? (mark JitOptimizationSensitive?)
