### ISSUE TITLE
[JitStressWithRandomNumbers] Assertion failed '!"Bad type in gtNewZeroConNode" Morph - Global'

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#57918]
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-99d96019591e4ca68b/JIT.jit64/1/console.91aaa4e8.log?sv=2019-07-07&se=2021-09-11T23%3A54%3A43Z&sr=c&sp=rl&sig=cN9Z73inZDSPT47yY0ccNyKDEXn%2BVO49zomq028wEhk%3D

Repro steps (arm64 windows):
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=7
JIT\jit64\localloc\call\call07_small\call07_small.cmd
```

Failure log:
```
      Assert failure(PID 13408 [0x00003460], Thread: 10752 [0x2a00]): Assertion failed '!"Bad type in gtNewZeroConNode"' in 'LocallocTest:func3(int,long,long):bool:this' during 'Morph - Global' (IL size 200)
      
          File: D:\workspace\_work\1\s\src\coreclr\jit\gentree.cpp Line: 6342
          Image: D:\h\w\A3D208FC\p\corerun.exe
```

the issue from a quality week JitStress experiment.

**Comment by sandreenko** [comment]
@jakobbotsch could you please take a look at this issue when you have time? Here we have a LCL_VAR long and under `STRESS_LCL_FLDS` we replace it with `LCL_VAR TYP_BLOCK<16>` and change uses to `LCL_FLD long` but later we do a tail call:
https://github.com/dotnet/runtime/blob/07b13f4b9c7c35bb73ffb49e58ffdb24be7533d2/src/coreclr/jit/morph.cpp#L9005

and there we don't expect TYP_BLOCK there.

I am not sure if the fix should be to forbid stressing this var
https://github.com/dotnet/runtime/blob/07b13f4b9c7c35bb73ffb49e58ffdb24be7533d2/src/coreclr/jit/compiler.h#L477

or if we should change the logic in the tail call.

probably it is stress only and we can move it to 7.0.

**Comment by jakobbotsch** [comment]
This is happening when we optimize self-tail-calls into a loop. In that case we need to zero out locals that we would normally zero-init in the prolog, and that does not handle `TYP_BLK`.

I tried for a while to come up with a non-stress repro but the zero-init is done only for IL locals and I don't see a way to produce a TYP_BLK IL local without the stress mode, so I'll move this to 7.0.

**Comment by jakobbotsch** [comment]
I tried just morphing it as `GT_ASG(GT_BLK(GT_ADDR(GT_LCL_VAR blklcl))), 0)` but the JIT is not really prepared to handle assignments to these `TYP_BLK` locals. But, I am confused why we even have them instead of just using structs with block layout. Perhaps something to clean up at some point.

**Comment by BruceForstall** [comment]
I have an experiment to run random with JitStress values in the CI and hit this with `COMPlus_JitStress=8b`:

https://dev.azure.com/dnceng/public/_build/results?buildId=1940063&view=ms.vss-test-web.build-test-results-tab&runId=50024108&resultId=108540&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by jakobbotsch** [comment]
The stress mode itself is a little weird. It explicitly converts only IL locals to `TYP_BLK` locals, but we will never see a `TYP_BLK` IL local so we are stress testing something that we will never see. In this particular case we are trying to insert explicit zero initialization for an IL local and we simply do not support that for `TYP_BLK`.

**Comment by BruceForstall** [comment]
A few questions: why do we have that stress mode, and is it still valuable? Possibly it was introduced before we had an adequate number of comprehensive struct test cases as a way to artificially increase that number. If that is true, is that still a concern? Or do we get good IL-level BLK stress cases via Fuzzlyn/Antigen/Span<>/etc.?

**Comment by jakobbotsch** [comment]
I don't know, but I would be all for removing it, or at least changing it so that we are not doing it for IL locals.

**Comment by BruceForstall** [comment]
Sergey asked above: can we add new exclusions in `Compiler::lvaStressLclFldCB()` (setting ` varDsc->lvNoLclFldStress = true`) in the failure case?

**Comment by jakobbotsch** [comment]
Yes, we can. The question is if there is any value in the stress mode if we have to keep adding exclusions for it, like you asked above.

There is already a whole bunch of exclusions, and as I mentioned above, stressing IL locals in this way is strange as we will never see `TYP_BLK` IL locals. Yet, we exclude compiler temps in the mode -- the exact locals that we may actually see as `TYP_BLK`.
