### ISSUE TITLE
dotnet crashes in illink-sharedframework.targets step on OSX arm64

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#57934]
```
  Trimming osx-arm64 runtime pack assemblies with ILLinker...
/Users/runner/work/1/s/src/libraries/illink-sharedframework.targets(41,5): error MSB6006: "dotnet" exited with code 138. [/Users/runner/work/1/s/src/libraries/src.proj]
##[error]src/libraries/illink-sharedframework.targets(41,5): error MSB6006: (NETCORE_ENGINEERING_TELEMETRY=Build) "dotnet" exited with code 138.

Build FAILED.

/Users/runner/work/1/s/src/libraries/illink-sharedframework.targets(41,5): error MSB6006: "dotnet" exited with code 138. [/Users/runner/work/1/s/src/libraries/src.proj]
    0 Warning(s)
```

A binlog is available but I doubt that it contains more information than the console log.

Configuration: `Libraries Build OSX arm64 Release`
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1311165&view=logs&j=308fa0e8-fdc8-51bf-1190-831815f155a6

cc @vitek-karas @sdmaclea @eerhardt

**Comment by eerhardt** [comment]
Does this error consistently happen on OSX arm64? Or is it intermittent?

If it doesn't consistently happen, I wonder if it is an arm64 runtime issue.

**Comment by ViktorHofer** [comment]
> Does this error consistently happen on OSX arm64? Or is it intermittent?

First time I saw this code path crashing dotnet - on any configuration.

**Comment by ViktorHofer** [comment]
Happened again inside an official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1311843&view=logs&j=7b15a708-e7a6-57b7-3b4e-f5800ba55b15&t=243ef27e-b070-53a9-23c1-2491d19c653e&l=1697

**Comment by mdh1418** [comment]
This seemed to happen on OSX x64 Debug as well 
https://dev.azure.com/dnceng/public/_build/results?buildId=1337769&view=logs&j=0ce95488-260d-5e86-47b9-82bc4e703e0b&t=822b0d86-b2cc-5adc-53e4-31a3c632d85c
