### ISSUE TITLE
[Microsoft.Extensions.DependencyInjection] After configuring a type using Configure<T> when properties inside it defines a property with ``{ get; set; } = some default value;`` results in the value set in Configure<T> to be overwritten.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#57950]
### Description
When a type specified in ``.Configure<T>`` is instantiated and some provides specific values they want to use with it from within the body of ``.Configure<T>``, if they was to obtain the object later using DI and then they access the properties getter it looks like what happens instead is that the getter either:
- overwrites the value specified from ``.Configure<T>``
- DI's value that was specified in ``.Configure<T>`` was somehow overwritten by the default value of the property defined in the type itself.
- some other issue (possibly a bug in DI)

https://gist.github.com/AraHaan/579d9eafb260e5866e3793c553a7d36b

### Configuration

Currently it seems to happen with my 64 Bit Windows 11 install (with .NET 6 rc.1), With my MacOS v12.0 Beta 6 (with the .NET 5.0.9 runtime (5.0.400 SDK) and .NET 6 rc.1 runtime reproduces the issue on my end)

Note: The exact build of .NET 6 rc.1 is: 6.0.100-rc.1.21413.11

### Regression?

According to the creator of the Remora.Discord library it works for them in a build of .NET 5, but it is not yet clear to me which exact build of .NET 5 they are using.

### Other information

On the gist above what happens is that I set the property in that type using ``.Configure<T>`` to ``some other value``, when I go to print the value from console it prints the default set ``some value`` instead on my end.

**Comment by AraHaan** [comment]
cc: @maryamariyan @michaelgsharp @safern @tarekgh

**Comment by tarekgh** [comment]
CC @eerhardt

**Comment by eerhardt** [comment]
@AraHaan - the code in your gist doesn't work. When running it, I get:

```
Unhandled exception. System.InvalidOperationException: No service for type 'TestDependencyInjectionIssue.ExampleOptions' has been registered.
```

**Comment by eerhardt** [comment]
I think your issue is that you need to use:

```C#
var options = Services.GetRequiredService<IOptions<ExampleOptions>>();
```

instead of

```C#
var options = Services.GetRequiredService<ExampleOptions>();
```

**Comment by AraHaan** [comment]
After testing locally that was the issue all along.
