### ISSUE TITLE
Assertion at /__w/1/s/src/mono/mono/sgen/sgen-alloc.c:409, condition `<disabled>' not met

### ISSUE THREAD

**Issue by CaptainMinnette** [dotnet/runtime#57976]
### Description

When attempting to debug my Blazor WASM project in Chrome, it quickly crashes.

\* Assertion at /__w/1/s/src/mono/mono/sgen/sgen-alloc.c:409, condition `\<disabled>' not met

Uncaught (in promise) ExitStatus

\* Assertion at /__w/1/s/src/mono/mono/metadata/sgen-stw.c:73, condition `\<disabled>' not met

Uncaught ExitStatus

![](https://i.imgur.com/KFhsvrL.png)

In Firefox, there is a similar error:

/__w/1/s/src/mono/mono/utils/hazard-pointer.c:194 \<disabled>

This is a large and complex program; I made a good deal of changes to enable a brand new use-case, and after doing so this is the result. I never call HttpClient.GetStringAsync(), which seems to have previously been a culprit  here: #42628

I also doubt I have any methods that exceed 32kb, another potential cause. 

### Configuration

.NET 5.0.3
Windows 10 Pro v1909
x64 architecture
Google Chrome and Firefox exhibit similar issues

**Comment by lewing** [comment]
Can you reproduce the issue in .NET 6?

**Comment by CaptainMinnette** [comment]
I discovered two issues that caused this:

-an endpoint call that attempted to pass a Guid? into the constructed string
![jQLRVa9](https://user-images.githubusercontent.com/88004653/130699640-7f36c2ec-8582-4d94-adac-ff96afed8a48.png)
-a class TicketHandler that instantiated a ChannelHandler property, which itself instantiated a TicketHandler property.
