### ISSUE TITLE
dotnet/runtime and dotnet/emsdk fail to build stable for .NET 6

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#57982]
When attempting to build stable for .NET 6, runtime and emsdk get the following error:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1312809&view=logs&j=55625a83-07ac-525a-fb32-9d705da79581&t=ed547991-520a-5120-9a9a-8b7bdbddb033

```
D:\workspace\_work\1\s\.packages\microsoft.dotnet.build.tasks.packaging\6.0.0-beta.21418.12\build\Packaging.targets(800,5): error : No VersionSuffix was set. Ensure it is set before targets in packaging are ran. [D:\workspace\_work\1\s\src\mono\nuget\Microsoft.NET.Runtime.MonoTargets.Sdk\Microsoft.NET.Runtime.MonoTargets.Sdk.pkgproj]
##[error].packages\microsoft.dotnet.build.tasks.packaging\6.0.0-beta.21418.12\build\Packaging.targets(800,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) No VersionSuffix was set. Ensure it is set before targets in packaging are ran.
```

Note that this only happens with pkgproj projects, and that the target in arcade that is hitting this hasn't changed in a couple years.

**Comment by lewing** [comment]
cc @steveisok

**Comment by akoeplinger** [comment]
Hm no idea why that happens. @ViktorHofer since you're a .pkgproj expert do you know what's going on here?

**Comment by ViktorHofer** [comment]
@mmitche is this just happening for mono packages or for installer and coreclr ones as well?

cc @Anipik @ericstj

**Comment by mmitche** [comment]
@ViktorHofer I think just mono pkgprojs.

**Comment by Anipik** [comment]
I think i know the fix here .

**Comment by Anipik** [comment]
I think we have hit this earlier. i might know the fix here. let me try it out

**Comment by steveisok** [comment]
@Anipik @mmitche Is this still an issue?  Looks like it may have been resolved, but want to be sure.

**Comment by mmitche** [comment]
Nope, resolved.
