### ISSUE TITLE
Cannot get symbol ucol_setMaxVariable_50 from libicui18n

### ISSUE THREAD

**Issue by abarberenaCPDS** [dotnet/runtime#57983]
After following the steps here, https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.103-linux-arm64-binaries. I am getting the following exception when running:

```net core
dotnet --version

Cannot get symbol ucol_setMaxVariable_50 from libicui18n
Error: /lib64/libicui18n.so.50: undefined symbol: ucol_setMaxVariable_50
[1]    8639 abort      dotnet --version
```

### Environment:

- Raspberry Pi 3B+
- [Micro Center 32GB microSDHC Card Class 10](https://www.microcenter.com/product/485584/micro-center-32gb-microsdhc-card-class-10-flash-memory-card-with-adapter)
- Clean install of [Centos aarch64 RPI Minimal 4](http://mirrors.ocf.berkeley.edu/centos-altarch/7.9.2009/isos/aarch64/images/CentOS-Userland-7-aarch64-RaspberryPI-Minimal-4-2009-sda.raw.xz)

```bash
name -a
Linux centosraspberrypi 5.4.72-v8.1.el7 dotnet/sdk
#1 SMP PREEMPT Wed Oct 21 17:35:36 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by tarekgh** [comment]
@@abarberenaCPDS please let's know if the workaround is working for you.

**Comment by tarekgh** [comment]
another idea to work around this is to use the [ICU app-local feature](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu)

Include the following in your csproj:

```Xml
  <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  </ItemGroup>
```

**Comment by abarberenaCPDS** [comment]
@tarekgh , let me try right now, I'll post the details shortly, thx for following up!

**Comment by abarberenaCPDS** [comment]
#### 👋 Update
I just executed the steps and got an issue trying to configure the ICU library, I guess I would need some help to figure out what's preventing the configure script to run fine

``` bash
~/icubuild/icu/source > **./configure --prefix=/home/ec2-user/libicu**
checking for ICU version numbers... release 68.1, library 68.1, unicode version 13.0
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
...

checking for nl_langinfo's argument to obtain the codeset... CODESET
checking for namespace support... no
**configure: error: Namespace support is required to build ICU.**
```

After this point, I can't run the make command obviously, Do you mind giving me a few hints on what could I try?

thx!

**Comment by tarekgh** [comment]
@abarberenaCPDS does `clang` package installed on your machine? if so could you try uninstall clang and keep only gcc and try again?

**Comment by tarekgh** [comment]
CC @jefgen.

**Comment by jefgen** [comment]
Two quick comments:

I wonder if maybe you have an old version of the compiler which doesn't support C++11, or perhaps doesn't enable it by default. IIRC, I think on older versions of GCC you had to turn on C++11 support manually.

You could try running configure again with this enabled to force turning on C++11 support:
`export CXXFLAGS="-std=c++11" ./configure`


Another idea might be to try using a pre-built version of [MS-ICU](https://github.com/microsoft/icu) for ARM64 and see if that works for you using the ICU app-local feature, like @tarekgh suggested.

https://www.nuget.org/packages/Microsoft.ICU.ICU4C.Runtime/

Note: The MS-ICU `linux-arm64` runtime Nuget is compiled using the .NET Core Ubuntu 16.04 (xenial) Cross-ARM64 image, and should work for aarch64/ARM64 with Ubuntu 16.04 and above, but I'm not sure about CentOS off-hand.

**Comment by abarberenaCPDS** [comment]
Thx guys for following up,

I think the option you suggest to use/reference as a package (nuget) would work, basically, after decompressing the tar, I can't even run a simple dotnet --version.

On the other hand, I tried as suggested and still no luck, see below:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/43246964/130559499-796c5bc6-16f5-4804-a6e7-a80886028c8c.png">

I confirmed I have gcc installed and apparently, no clang although I see a couple packages listed, which I could not remove at all.

Then, I tried

```bash
export CXXFLAGS="-std=c++11" ; ./configure --prefix=/home/ec2-user/libicu
```

And same result:

```bash
checking for ICU version numbers... release 68.1, library 68.1, unicode version 13.0
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking for clang... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for clang++... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.20... yes
checking for ICULEHB... no
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for python3... python3
checking for gmake... /usr/bin/gmake
checking for doxygen... no
checking checking for executable suffix...
checking whether strict compiling is on... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 8
checking whether runnable 64 bit binaries are built by default... yes
checking which Makefile fragment to use for aarch64-unknown-linux-gnu... mh-linux
checking for floor in -lm... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... ranlib
checking for a sed that does not truncate output... /usr/bin/sed
checking for ar... ar
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether to enable dynamic loading of plugins. Ignored if plugins disabled.... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for library containing dlopen... -ldl
checking for dlopen... yes
checking for gettimeofday... yes
checking if we have a C++ compiler... Good
checking for pthread_attr_init in -lpthread... yes
checking for mmap... yes
checking for genccode assembly... -a gcc
checking for inttypes.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking whether byte ordering is bigendian... no
checking for nl_langinfo... yes
checking for nl_langinfo's argument to obtain the codeset... CODESET
checking for namespace support... no
configure: error: Namespace support is required to build ICU.
```

**Comment by tarekgh** [comment]
@abarberenaCPDS sorry for the inconvenience. There is one more thing it is worth trying. try download and compile older version of ICU like [ICU v53 Source](https://github.com/unicode-org/icu/archive/refs/tags/release-53-2.tar.gz). I don't have your environment to try it myself but if you have instructions how I can clone your environment I can try it.

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh,

No worries, I appreciate the help!, I will try with ICU v53 and report back.

About the steps to reproduce, it's very simple, I am using a Raspberry PI 3B+, flash the micro SD card with Centos 7 ARM64 (aarch64) (http://isoredirect.centos.org/altarch/7/isos/aarch64/) using the official RPi app and that's it! Just try to setup DotNet Core following the steps from the official docs.

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh, yes please, if you don't mind sharing the steps, please post, That way I will ensure I am doing exactly the same and if I can work it out, I will close this issue.

Man! this thread has proven to be very useful.

**Comment by tarekgh** [comment]
Here is how to download, build, and install latest GCC. Please note this will take long time. Also ensure you have enough free disk space (around 8 GB or so). 

```
mkdir ~/GCC-source
cd ~/GCC-source
svn co svn://gcc.gnu.org/svn/gcc/tags/gcc_9_2_0_release/
cd gcc_9_2_0_release/
./contrib/download_prerequisites
cd ..
mkdir gcc_9_2_0_release-build/
cd gcc_9_2_0_release-build/
../gcc_9_2_0_release/configure && make && sudo make install && echo "finished"
hash -r
echo "/usr/local/lib64" > usrLocalLib64.conf
mv usrLocalLib64.conf /etc/ld.so.conf.d/
ldconfig
```

After finishing, you can follow the instruction https://github.com/dotnet/runtime/issues/57983#issuecomment-906818035 to build ICU v53 and then you should be ready to go.

**Comment by abarberenaCPDS** [comment]
👋  Update
Hey @tarekgh, yeah, you're right, building time is taking way too long ( >4.5 hrs). Since my last message, I've been struggling to successfully build.

#### Hardware

- Raspberry Pi 3B+
- [Micro Center 32GB microSDHC Card Class 10](https://www.microcenter.com/product/485584/micro-center-32gb-microsdhc-card-class-10-flash-memory-card-with-adapter)

This is what I am observing:

#### Hardware issues
- The build hangs up, and the RPi 3b+ freezes
- I added a fan and still gets hot
- Also tried with make -j 2 and did not help

#### Alternative reads

- [Script to download and install new GCC](https://www.raspberrypi.org/forums/viewtopic.php?t=212636)
- [New major release of GCC](https://www.raspberrypi.org/forums/viewtopic.php?t=273441)
- [Precompiled Raspberry Pi CPU optimized](https://github.com/abhiTronix/raspberry-pi-cross-compilers)

**Comment by tarekgh** [comment]
@abarberenaCPDS if you install dotnet and run it, do you get the errors:

```
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by dotnet)
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)
```

If not, then you may not need to get the latest GCC. I was doing the GCC to update `GLIBCXX`.

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh, yes I got those errors.

**Comment by tarekgh** [comment]
Could you extract the content of the attached zip file to the folder `/usr/lib64/` and check if this will make dotnet pass this error?

[libstdc++.so.6.0.zip](https://github.com/dotnet/runtime/files/7073163/libstdc%2B%2B.so.6.0.zip)

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh, so... no luck...  😞  

<img width="619" alt="image" src="https://user-images.githubusercontent.com/43246964/131430964-2924008c-12ec-40dd-897b-cd893c6ede9b.png">

**Comment by tarekgh** [comment]
@abarberenaCPDS I got a notification you have replied but I am not seeing any reply!
Just want to make sure I didn't miss anything here.

**Comment by tarekgh** [comment]
@abarberenaCPDS looks you have passed the first error 

```
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by dotnet)
dotnet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)
```

Now you are very close, you just need to execute the instructions in https://github.com/dotnet/runtime/issues/57983#issuecomment-906818035 and you should be good to go.

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh, sorry for the late reply, I took some days off. I wanted to report that sadly I couldn't make it work.

- I tried your ZIP, then build ICU and still did not work.
- I tried compiling the GCC again and no luck

**Comment by tarekgh** [comment]
@abarberenaCPDS thanks for your reply. what is the error you are currently getting?

**Comment by abarberenaCPDS** [comment]
Hey man, I am still getting the same error I reported at the top of this thread

`ucol_setMaxVariable_50 from libicui18n`

**Comment by tarekgh** [comment]
From the error you have, it looks ICU was not installed correctly. 

Just to confirm, after building ICU v53 you have done the following two steps:

```
make install
export LD_LIBRARY_PATH=/home/user/libicu/lib/
```

Also, would be good adding `export LD_LIBRARY_PATH=/home/user/libicu/lib/` to `$HOME/.bashrc` then try again.

**Comment by abarberenaCPDS** [comment]
Hey @tarekgh, yes, you're right, ICU is a blocker for me.

Keep in mind that we already tried to enable GCC and did not work, we also tried with the compiled libs and still the same.

ICU can't successfully build  due to `configure: error: Namespace support is required to build ICU.`

~/icu53source/icu-release-53-2/icu4c/source> ./configure --prefix=/home/root/libicu
```bash
checking for ICU version numbers... release 53.2, library 53.2, unicode version 6.3
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether to build debug libraries... no
checking whether to build release libraries... yes
checking for clang... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for clang++... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for gmake... /usr/bin/gmake
checking for doxygen... no
checking checking for executable suffix...
checking whether strict compiling is on... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void *... 8
checking whether runnable 64 bit binaries are built by default... yes
checking which Makefile fragment to use for aarch64-unknown-linux-gnu... mh-linux
checking for floor in -lm... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking whether to enable auto cleanup of libraries... no
checking whether to enable draft APIs... yes
checking for ranlib... ranlib
checking for ar... ar
checking whether to enable renaming of symbols... yes
checking whether to enable function and data tracing... no
checking elf.h usability... yes
checking elf.h presence... yes
checking for elf.h... yes
checking whether to enable dynamic loading of plugins... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for library containing dlopen... -ldl
checking for dlopen... yes
checking for gettimeofday... yes
checking if we have a C++ compiler... Good
checking if #include <string> works... yes
checking if #include <atomic> works... yes
checking for pthread_attr_init in -lpthread... yes
checking for mmap... yes
checking for genccode assembly... -a gcc
checking for inttypes.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking whether byte ordering is bigendian... no
checking for nl_langinfo... yes
checking for nl_langinfo's argument to obtain the codeset... CODESET
checking for namespace support... no
configure: error: Namespace support is required to build ICU.
```

**Comment by Kaelum** [comment]
In another thread, I found the following:

`sudo yum install libicu60`

Once I ran that, .NET 5.0 was working on an AWS Linux 2 ARM64 instance.

**Comment by abarberenaCPDS** [comment]
Hey @Kaelum, thanks for your comment, I appreciate your help but unfortunately the solution is not applicable in this case.

Keep in mind that the architecture I am using is a clean install of [Centos aarch64 RPI Minimal 4](http://mirrors.ocf.berkeley.edu/centos-altarch/7.9.2009/isos/aarch64/images/CentOS-Userland-7-aarch64-RaspberryPI-Minimal-4-2009-sda.raw.xz)

```bash
Package libicu-50.2-4.el7_7.aarch64 already installed and latest version
Nothing to do
```

**Comment by janvorli** [comment]
@abarberenaCPDS please note that CentOS 7 is not supported for arm/arm64. See the support matrix here: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md. arm/arm64 is only supported on Ubuntu, Debian and Alpine. The reason is that we cross build for arm/arm64 distros on x64 devices and our scripts to generate rootfs don't support targeting redhat based distros. The distros that we target use newer libc / icu / etc. So while things might work if you upgrade the libc on CentOS 7 and build / install a newer libicu, replacing libc in a distro is a potential issue for some low level OS functionality where it is expected that libc and some other libraries match.

**Comment by tarekgh** [comment]
I am closing this issue per @janvorli comment. @abarberenaCPDS feel free to send any more question we can help with if you have any. Thanks for your report.

**Comment by abarberenaCPDS** [comment]
Hey @janvorli, thanks for the link, that makes sense. I think I am going to suggest to MS to add this matrix in the [Download .NET page](https://dotnet.microsoft.com/download/dotnet/5.0).

I am still wondering how @tarekgh was able to successfully build LibIcu using the same image I referenced and run NetCore with no issues. That makes me cringe 😢

**Comment by tarekgh** [comment]
> I am still wondering how @tarekgh Tarek Mahmoud Sayed FTE was able to successfully build LibIcu using the same image I referenced and run NetCore with no issues. That makes me cringe 😢.

I think the only step you couldn't do is what I mentioned in my comment https://github.com/dotnet/runtime/issues/57983#issuecomment-907548411. In my case, although took long time but was successfully completed and helped in compiling ICU v53 after that. The only difference I had is my micro SD card I used was 64 GB and I used [Aluminum Heat Sink](https://www.adafruit.com/product/3082?gclid=CjwKCAjw7rWKBhAtEiwAJ3CWLKZjoXvdlxPv3-E8PX8HyOf6J1c8gnRO_Nj4xrGhFt2-sAIZX7y3qhoCx0EQAvD_BwE)

**Comment by abarberenaCPDS** [comment]
@tarekgh, I can't thank you enough for your assistance and time spent in this issue 🥇.

It was very good to connect with you and I can say I learned a lot. I will try with a bigger card, that might be the problem.

Abe
