### ISSUE TITLE
An exception error pops up when converting Persian calendar To Gregorian calendar

### ISSUE THREAD

**Issue by Jenna-Zheng** [dotnet/runtime#57994]
* .NET Core Version: 
.NET SDK 6.0.100-rc.1.21417.19

* Have you experienced this same bug with .NET Framework?: 
Yes

* More info:
This issue is a feedback [1377707](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1377707)
![image](https://user-images.githubusercontent.com/64949616/130545410-6ad8a47e-926c-4292-8e43-b2ec7fcc17a9.png)

**Problem description:**
An exception error pops up about System.FormatException: 'String '1400/04/31' was not recognized as a valid DateTime.'
![image](https://user-images.githubusercontent.com/64949616/130544069-090ec757-6001-430b-b125-2500669d9dff.png)

![image](https://user-images.githubusercontent.com/64949616/130547457-ff4bf07f-2d9b-4b7b-a5e1-ff3815e06f1b.png)

**Expected behavior:**
An exception should not pop up

**Minimal repro:**
1. Extract " [WinFormsApp36.zip](https://github.com/dotnet/winforms/files/7035929/WinFormsApp36.zip)" and open it in VS.
2. Build and run the app.
3. Click the Button control.

**Or**

1. Create a Core winforms app and open form designer.
2. Add a **Button** Control and double click it.
3. Add this Code '**using System.Globalization;**' to Form1.cs file 
4. Add below method to Form1 class.
        **public DateTime ToGregorian(DateTime value)
        {
        return new DateTime(value.Year, value.Month, value.Day, new PersianCalendar());
        }**
5. Add the code '**var date = ToGregorian(DateTime.Parse("1400/04/31"));**' to button1_Click event.
6. Build and run the app.
7. Click the Button control.

**Comment by ryank425** [comment]
Use following link to convert from PersianCalendar correctly.

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.persiancalendar?view=net-5.0

You are trying to put
1400/04/31 on DateTime.Parse which expects Gregorian calendar as you are not passing anything other than string for Cultural Info. There is no 31th day in April 1400 on Gregorian calendar and that is why you are getting that exception.

**Comment by tarekgh** [comment]
When doing 

```C#
	DateTime.Parse("1400/04/31")
```

You are parsing the date as a Gregorian date and not a date in the Persian calendar. Obviously this is a wrong Gregorian date because month April cannot have 31 days. If you want to parse the date as a date in Presian calendar, you need to do the following:

```C#

    CultureInfo ci = CultureInfo.GetCultureInfo("fa-IR");
    DateTime value = DateTime.Parse("1400/04/31", ci);
```

This should make the rest of your code work.

**Comment by msalehdtr** [comment]
Thank you very much 
It Worked for me and 
`CultureInfo ci = CultureInfo.GetCultureInfo("fa-IR");`
`DateTime.Parse(maskedTextBox2.Text, ci)`
Will Covert Persian calendar To Gregorian calendar without any problem
Good Luck
