### ISSUE TITLE
[wasm][debugger] Assertion while debugging

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#58021]
![image](https://user-images.githubusercontent.com/4503299/130637439-6cf59f4d-72e1-4b3d-a8e1-b5ba28ba1b4d.png)

* Assertion at /__w/1/s/src/mono/mono/metadata/class.c:5769, condition `<disabled>' not met

* Assertion at /__w/1/s/src/mono/mono/metadata/class.c:5769, condition `<disabled>' not met

* Assertion at /__w/1/s/src/mono/mono/metadata/class.c:5769, condition `<disabled>' not met

* Assertion at /__w/1/s/src/mono/mono/metadata/class.c:5769, condition `<disabled>' not met

**Comment by lewing** [comment]
ci hit https://github.com/dotnet/runtime/issues/58062
