### ISSUE TITLE
System.Reflection.Metadata doesn't handle generic attributes

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#58073]
We get a BadImageFormatException if the custom attribute constructor refers to the T's of the owning type.

I have a fix in #57466 but I won't have time to write tests anytime soon. It's better if that's handled by the owners of S.R.M.

**Comment by krwq** [comment]
Proactively adding to 6.0 - per @RikkiGibson and @tmat generic attributes will ship in 6.0 which means this scenario will be broken. The initial version of the implementation is in the PR above, missing tests.

**Comment by joperezr** [comment]
Looks like the PR you pointed to was closed. @tmat @RikkiGibson do we still want to get this in 6.0? is somebody going to finish the work that @MichalStrehovsky started?

**Comment by RikkiGibson** [comment]
We are including the feature under the "preview" language version, which means it is not supported and it's expected that some things will still be broken in the upcoming .NET 6 release.￼

If we are able to get more fixes related to the feature into .NET 6, then great, but it's not urgent right now.

**Comment by joperezr** [comment]
Got it, will mark this issue as net7.0 then for now. If we can still get it for 6.0 that would be great, but given the time window that seems like it could not make it in time.
