### ISSUE TITLE
Coreclr Universal Test Execution Framework

### ISSUE THREAD

**Issue by ramarag** [dotnet/runtime#5808]
# Summary of Current state of affairs:

The tests are built using MSBuild with a mix of coreclr repo specific build logic and targets from https://github.com/dotnet/buildtools.  

**Note: Moving the build system to domino\cli is an orthogonal but relevant issue.**, we are more interested in running the built tests in this issue

The output of the build is exe/dll and associated .cmd and .sh which knows how to run the test. 
To run these scripts individually we just need to set the environment variable CORE_ROOT to point to a folder containing the runtime and framework libraries 

These test scripts are currently  Run in an automated manner using two different ways 
1. On Windows, xunit is used to orchestrate the test running and result collection automation
2. On Linux and MacOs - A shell script is currently being used to do the same

Going Forward we would like to consolidate the test automation mechanisms across all target architectures where coreclr needs to run.  
## Deciding on Test Execution Framework
1. Xunit is a managed application written in C# that is currently used by Corefx repo as their test automation framework. It needs a fully functional runtime to run the tests. The current task need not be even considered if the amount of effort to bring up the runtime to run xunit was comparable to bringing up HelloWorld for coreclr on a new platform, But that is not the case so as Xunit uses a lot of non trivial services provided by the runtime like Reflection.
2. There are test frameworks used by open source projects like [llvm](http://llvm.org/docs/TestingGuide.html) which target multiple platforms  [LIT](http://llvm.org/docs/CommandGuide/lit.html). In this particular case LIT depends upon python to be present on the target platform. So this approach may not be convenient to us as bringing up python might not be a priority for our target platforms like ARM64 or nano server

This leads to the conclusion that the Test Execution Framework needs to be a native(c++) application as  that would imply if we build coreclr for a target system the executor will also work. Please do shout out if you disagree or have better alternatives.
## Native Test Execution Framework- Smarty

For years CLR team have been using a native test executor called smarty, this can be re purposed here.
# Current Plan of Action
## Stage 1:
1. As part of the test build or as a Pre Run Step generate a flat list file called Tests.lst that can be consumed by the smarty infrastructure 
2. The Tests.lst file will have metadata for all the tests [even if they are not available as part of test drop] which are only useful for the automation like 
   a. Test time out
   b.  Categorizing tests by the different environment they are expected to be used - For example those that are currently passing for Gcstress level 2 for check builds
3. This metadata should ideally remain with the corresponding test project
4. Smarty will use this Tests.lst and a drop of pre built tests along with custom arguments to run the tests and display the results.
## Stage 2:
1. Do further refinements and provide tooling support to make the metadata editing easier. like scatter/gather mechanisms proposed by @briansull , @RussKeldorph  and others
# Analysis :

Most of the work above work can be accomplished by using the existing coreclr test build system and open sourcing smarty.
1. There exists a python script which generates a Test.lst, https://github.com/dotnet/coreclr/blob/master/tests/scripts/lst_creator.py
2. The generated Tests.lst  for arm64 in https://github.com/dotnet/coreclr/tree/master/tests/scripts/test
3. Smarty Sources will need an overhaul to work crossplatform
4. As a stop gap measure before Stage 2 kicks in we could use https://github.com/dotnet/coreclr/blob/master/tests/scripts/migrate-tags.py to migrate metadata without having to resort to edit individaul test projects. @jeffschwMSFT mentioned that a checked in Tests.lst file is a recipe for nightmare when we branch and merge repos

Please feel free to provide opinions, alternatives or suggestions

**Comment by BruceForstall** [comment]
There is no effort to do this now. I'm going to close the issue. If we decide to bring it back, the issue could be re-opened (or, more likely, a new design and issue would be created).
