### ISSUE TITLE
TaskTimeoutExtensions.WhenAllOrAnyFailed eats OperationCanceledExceptions from awaited tasks

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#58081]
If one of the tasks passed to WhenAllOrAnyFailed throws OperationCanceledException, the original exception is eaten and replaced with a new cancellation exception that comes directly from WhenAllOrAnyFailed itself.

Issue seems to be caused by this: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L110

And this logic looks suspect too: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L82

Seems like we should not treat a cancellation exception any differently here than any other exception.

@stephentoub Thoughts?

**Comment by stephentoub** [comment]
> Seems like we should not treat a cancellation exception any differently here than any other exception.

We need to treat it a _little_ differently, in that Task does.  We should probably have designed this differently from the start, but the three-state nature of a completed task differentiates cancellation from faulted, and Task.Exception is non-null if and only if Task.IsFaulted is true, meaning Task.Exception is null if Task.IsCanceled is true.

If you want to change the WhenAllOrAnyFailed behavior, you could try replacing:
https://github.com/dotnet/runtime/blob/3dd793797e00ca293e03c18411863aba1742d34d/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs#L110
with
```C#
try
{
    a.GetAwaiter().GetResult();
}
catch (Exception e)
{
    tcs.TrySetException(e);
}
```

**Comment by geoffkizer** [comment]
> We need to treat it a little differently, in that Task does. 

Only if we rely on Task.Status/IsFaulted/IsCanceled/Exception, right? If we avoid those then it seems like we will not have issues.
