### ISSUE TITLE
Console.WriteLine throw FormatException when print  json string

### ISSUE THREAD

**Issue by panyi-dev** [dotnet/runtime#58098]
.net5.0 project, when print json string  throw System.FormatException . like this:

![S2021-08-25 15 06 02](https://user-images.githubusercontent.com/6744243/130742774-e868687d-0a18-4405-b03f-562d733b49c0.png)

Enviroment:

 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]

**Comment by DaZombieKiller** [comment]
This is because `{` and `}` have special meaning in format strings.

You need to either:
1. Use the `Console.WriteLine(string)` overload.
```cs
static void Main(string[] args) => Display("{\"\"}");

static void Display(string message) => Console.WriteLine(message);

static void Display(string format, params object[] args) => Console.WriteLine(format, args);
```
2. Escape each `{` and `}` character by doubling them up.
```cs
static void Main(string[] args) => Display("{{\"\"}}");

static void Display(string format, params object[] args) => Console.WriteLine(format, args);
```

**Comment by eiriktsarpalis** [comment]
As @DaZombieKiller already mentioned, this is by design. Please refer to the [Console.WriteLine documentation](https://docs.microsoft.com/en-us/dotnet/api/system.console.writeline?view=net-5.0#System_Console_WriteLine_System_String_System_Object___) for more details.

**Comment by panyi-dev** [comment]
Each JSON string contains these characters。

**Comment by DaZombieKiller** [comment]
> 
> 
> Each JSON string contains these characters。

The problem is that you're passing the JSON string to `Console.WriteLine(string, params object[])`, which expects a format string for its first argument, not a regular string. So it tries to parse your JSON as a format string and throws an exception when it realizes that it's invalid. Both workarounds I suggested above will solve that issue.
