### ISSUE TITLE
Failed Assembly.Load and Assembly.LoadFile leaks memory

### ISSUE THREAD

**Issue by kornelpal** [dotnet/runtime#58093]
### Description

On each call to `Assembly.Load` and (non-cached) `Assembly.LoadFile` a new `IndividualAssemblyLoadContext` is created and the constructor of the `AssemblyLoadContext` base class creates a strong GC handle as these are not collectible. This results in the empty `IndividualAssemblyLoadContext` being kept alive even when the `Assembly.Load` or `Assembly.LoadFile` method fails, including non-existent files in the case of `Assembly.LoadFile`.

This results in a memory leak when the code keeps retrying failed assembly loads . I've found this memory leak using [WCF Core](https://github.com/dotnet/wcf) that – when using `XmlSerializer` – keeps trying to load the non-existent `*.XmlSerializers.dll` assemblies.

### Configuration

.NET 5.0.9
WCF Core 3.2.1
OS/architecture agnostic

### Regression?

Yes, failed assembly load does not leak memory in .NET Framework.

### Other information

As a potential solution, the strong GC handle could be created after the first assembly was successfully loaded so that failed assembly loads are not causing memory leak. Alternatively, the issue could be fixed in `IndividualAssemblyLoadContext` only, if backward compatibility of `AssemblyLoadContext` is a concern.

In case of WCF Core and `XmlSerializer` the only workaround I can think of is generating a [compiled XML serializer](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator) so that `Assembly.LoadFile` is successful and returns the same `Assembly` instance even though `XmlSerializer` is not caching it, so there is no memory leak.

**Comment by Meister1977** [comment]
Would it be possible to fix this issue earlier? We have multiple microservices and because there is no workaround, we have to restart them daily.

**Comment by Meister1977** [comment]
Neither https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator or https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil.xmlserializer-guide is working to create serializer dll. 
Both thows exceptions with .net 5.0 target framework. So there is no workaround.

**Comment by agocke** [comment]
Unfortunately, this is a core piece of how the `AssemblyLoadContext` interacts with native code -- the native code keeps a strong reference to the AssemblyLoadContext.  This is how the code has worked since 3.0. Removing the strong reference from the native side is a significant rearchitecture of the assembly loading code, basically a new feature. That unfortunately means that 7.0 is the earliest option we have to change it.

**Comment by agocke** [comment]
One area we haven't explored is changes to XmlSerializer itself -- possibly an external replacement for the functionality. That's not my area of expertise, but I would be curious in your usage of XmlSerializer. Is it direct, or indirect through WCF?

**Comment by kornelpal** [comment]
`XmlSerializer` is used by WCF Core directly. Reusing `ChannelFactory<>` is generally improving performance and should reduce assembly loads. Microsoft.XmlSerializer.Generator bug #58421 on the other hand makes generating `*.XmlSerializers.dll` assemblies less feasible. When `XmlSerializer` is used directly, reusing the same instance should reduce assembly loads. Some `XmlSerializer` constructors/methods (not the ones used by WCF Core) also cache the loaded/generated serializers that reduces assembly loads.

Maybe adding a `File.Exists` check to `Assembly` or `XmlSerializer` was the simplest short term workaround.

**Comment by kornelpal** [comment]
I've posted a [workaround](https://github.com/dotnet/runtime/issues/58421#issuecomment-909658913) for the [Microsoft.XmlSerializer.Generator bug](https://github.com/dotnet/runtime/issues/58421) that enables working around the side effects of this bug in `XmlSerializer` by generating `*.XmlSerializers.dll` files.

**Comment by VSadov** [comment]
Fixed in https://github.com/dotnet/runtime/pull/68203

**Comment by jkotas** [comment]
The change is being reverted (#68478)

**Comment by teo-tsirpanis** [comment]
> the native code keeps a strong reference to the AssemblyLoadContext. This is how the code has worked since 3.0. Removing the strong reference from the native side is a significant rearchitecture of the assembly loading code, basically a new feature.

How about allowing `Unload` to be called on non-unloadable `AssemblyLoadContext`s if they have no assemblies loaded? Calling it would release the native counterpart and prohibit subsequent loads, effectively rendering it unusable. Would that be a less invasive change? (or maybe not, just saw https://github.com/dotnet/runtime/pull/68203#issuecomment-1102801533)

And it would solve the problem more cleanly. Checking if the file exists before loading it is still vulnerable to failures other than the file not existing, and does not generalize to loading assemblies via things like `Assembly.Load(byte[])`. The loading code would look like the following:

``` csharp
var alc = new IsolatedAssemblyLoadContext();
try
{
    result = alc.LoadAssemblyFromFile(path);
}
catch
{
    alc.Unload();
    throw;
}
```

**Comment by agocke** [comment]
Fixed by https://github.com/dotnet/runtime/pull/68502
