### ISSUE TITLE
[ios][mono][JIT] Are there any plan to allow dotnet full support / JIT / non-AOT on ios?

### ISSUE THREAD

**Issue by Thaina** [dotnet/runtime#58115]
As of new version of ios there seem to be some changes in policy and system of apple to allow JIT support

https://twitter.com/altstoreio/status/1413180831636492288

Are there anything dotnet need to be done to launch full JIT support on ios platform? Are there any plan relate to this?

area-EnC-mono
os-ios

**Comment by filipnavara** [comment]
The JIT is still not officially allowed even if it works under some circumstances for side-loaded applications.
