### ISSUE TITLE
Run "dotnet --info" on Win11,the RID shown "win10-x64"

### ISSUE THREAD

**Issue by haiyanliu2** [dotnet/runtime#58125]
Environment: Version 17.0.0 Preview 4.0 [31618.318.main]+ NET 6 SDK: 6.0.100-rc.1.21418.40
Repro steps:
1.Install NET 6 SDK: 6.0.100-rc.1.21418.40
2.Run "dotnet --info" on Command Prompt

Expected
RID should be win11-x64.

Actual
RID shown win10-x64.
![image](https://user-images.githubusercontent.com/87641893/130210513-c683a0d1-d319-4b97-847a-62ef47b83862.png)

dotnet --info
.NET SDK (reflecting any global.json):
Version: 6.0.100-rc.1.21418.40
Commit: 4bef385e31

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22443
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-rc.1.21418.40\

Host (useful for support):
Version: 6.0.0-rc.1.21418.9
Commit: 2a28e2f015

.NET SDKs installed:
6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
6.0.100-rc.1.21418.40 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0-rc.1.21418.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0-rc.1.21418.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-rc.1.21418.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by NikolaMilosavljevic** [comment]
[Triage] @vitek-karas do you know which team should own this? Can you tag them or add the label?

**Comment by vitek-karas** [comment]
When I looked into this the windows OS itself acts like Win10 (version is still 10.0....). See for example this discussion: https://github.com/dotnet/runtime/pull/58588#issuecomment-912132192

I think we should not support `win11` RIDs (same way we don't have Windows Server RIDs) as there would be no difference between `win11` and `win10`.

**Comment by vitek-karas** [comment]
@richlander for visibility

**Comment by agocke** [comment]
It's not looking like Windows itself will change anything at the OS level to report a Win 11 version. I think we should stick with the `win10` moniker as well.

**Comment by agocke** [comment]
Closing this out unless we find new info to suggest we need a win11 RID.
