### ISSUE TITLE
Remove `!` from `Microsoft.Extensions.DependencyModel`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#58139]
### Description

This is a blanket issue for all `!` operations that were added in #57445 (mainly in https://github.com/dotnet/runtime/pull/57445/commits/57dee2460c49efd9a5c27d4a623f704d8b7c9733)
They should be removed or reviewed.

**Comment by AnudeepGunukula** [comment]
Hi @eerhardt @maxkoshevoi  . i am interested in this project
i would like to work on this issue.

**Comment by eerhardt** [comment]
Sounds good. I assigned it to you.

**Comment by AnudeepGunukula** [comment]
Hi @eerhardt . i had made a pr that might solve this issue
Kindly review it and please let me know the changes if needed.
Thanks in advance

**Comment by maxkoshevoi** [comment]
Should this be closed since https://github.com/dotnet/runtime/pull/60842 is merged?

**Comment by eerhardt** [comment]
Yes! The PR wasn't linked to this issue as "fixes". Closing.
