### ISSUE TITLE
[API Proposal]: add Except for single item to Linq

### ISSUE THREAD

**Issue by Mrxx99** [dotnet/runtime#58132]
### Background and motivation

Often (maybe even more often than not) I want to use the Enumerable.Except extension method with only one item.
I often then write it like this:
```C#
var result = enumerable.Except(new[] { 50 });
```
which is not so clear to read as if there was a separate method and also allocates an array unnecessarily.
So I would suggest a "Except" method that only takes a single item. I would not mind if it was called ExceptItem, ExceptSingle or something similar if overloading the existing Except would be a problem. It would also avoid creating/allocating the HashSet that is used in the implemenation of Except.

As the following benchmark shows a separate method (only a naive implementation by me) could improve performance drastically, so that maybe even an analyzer would make sense suggesting the usage of the new Except method if a usage like shown above is detected:

```C#
public static class Extensions
{
    public static IEnumerable<T> ExceptItem<T>(this IEnumerable<T> enumerable, T item)
    {
        foreach (var i in enumerable)
        {
            if (!EqualityComparer<T>.Default.Equals(i, item))
                yield return i;
        }
    }
}
```

<details>
  <summary>Benchmark results</summary>

|     Method* |    enumerable* | item |          Mean |         Error |        StdDev |        Median | Ratio |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|----------- |----------- |----- |--------------:|--------------:|--------------:|--------------:|------:|--------:|--------:|--------:|----------:|
|     Except |     0..0   |    0 |     122.11 ns |      0.700 ns |      0.655 ns |     122.02 ns |  1.00 |  0.1197 |       - |       - |     376 B |
| ExceptItem |     0..0   |    0 |      52.52 ns |      0.947 ns |      0.791 ns |      52.34 ns |  0.43 |  0.0204 |       - |       - |      64 B |
|            |            |      |               |               |               |               |       |         |         |         |           |
|     Except |    0..10   |    5 |     445.04 ns |      5.590 ns |      4.955 ns |     443.89 ns |  1.00 |  0.2270 |       - |       - |     712 B |
| ExceptItem |    0..10   |    5 |     156.93 ns |      1.479 ns |      1.235 ns |     156.65 ns |  0.35 |  0.0331 |       - |       - |     104 B |
|            |            |      |               |               |               |               |       |         |         |         |           |
|     Except |   0..100   |   50 |   3,231.31 ns |     64.436 ns |     81.491 ns |   3,216.97 ns |  1.00 |  1.4038 |       - |       - |   4,416 B |
| ExceptItem |   0..100   |   50 |   1,020.85 ns |      6.583 ns |      5.139 ns |   1,018.88 ns |  0.32 |  0.0324 |       - |       - |     104 B |
|            |            |      |               |               |               |               |       |         |         |         |           |
|     Except |  0..1000   |  500 |  27,940.21 ns |    179.199 ns |    149.639 ns |  27,960.29 ns |  1.00 | 10.5591 |       - |       - |  33,208 B |
| ExceptItem |  0..1000   |  500 |   9,447.54 ns |     89.973 ns |     70.245 ns |   9,451.44 ns |  0.34 |  0.0305 |       - |       - |     104 B |
|            |            |      |               |               |               |               |       |         |         |         |           |
|     Except | 0..10000   | 5000 | 477,018.51 ns | 10,538.887 ns | 30,407.098 ns | 465,937.11 ns |  1.00 | 90.8203 | 90.8203 | 90.8203 | 524,888 B |
| ExceptItem | 0..10000   | 5000 |  97,279.62 ns |    457.594 ns |    357.260 ns |  97,221.33 ns |  0.21 |       - |       - |       - |     104 B |

> BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1165 (21H1/May2021Update)
Intel Core i5-8250U CPU 1.60GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100-preview.4.21255.9
  [Host]     : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT
  DefaultJob : .NET 5.0.6 (5.0.621.22011), X64 RyuJIT

_* = enumerable created with `Enumerabe.Range`_
</details>

<details>
  <summary>Benchmark Code</summary>

```C#
[MemoryDiagnoser]
public class Benchmark
{
    public IEnumerable<object[]> NumbersArgumentsSource() { ... }

    [Benchmark(Baseline = true)]
    [ArgumentsSource(nameof(NumbersArgumentsSource))]
    public int Except(IEnumerable<int> enumerable, int item)
    {
        return enumerable.Except(new[] { item }).Count();
    }

    [Benchmark]
    [ArgumentsSource(nameof(NumbersArgumentsSource))]
    public int ExceptItem(IEnumerable<int> enumerable, int item)
    {
        return enumerable.ExceptItem(item).Count();
    }
}
```
</details>

### API Proposal

```C# 
namespace System.Linq
{
     public static class Enumerable
     {
        public static IEnumerable<TSource> ExceptItem<TSource>(this IEnumerable<TSource> source, TSource item);
        public static IEnumerable<TSource> ExceptItem<TSource>(this IEnumerable<TSource> source, TSource item, IEqualityComparer<TSource>? comparer);
     }
}
```     

### API Usage

```C#
var enumerable = Enumerable.Range(0, 100);

var result = enumerable.ExceptItem(50);
```

**Comment by eiriktsarpalis** [comment]
I believe consensus is we should not be adding the proposed API, so I'm going to close this. @Mrxx99 thank you for contributing the proposal!
