### ISSUE TITLE
"Clean up old artifacts owned by root" installer CI step failing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#58168]
```
docker: failed to register layer: error creating overlay mount to /datadisks/disk1/docker/overlay2/1eda470062a4ed8ce630ab79396d2a9b2c6cd3f2ca11e79d1d76d46b0106b3af/merged: no such file or directory.
See 'docker run --help'.
+ mkdir /datadisks/disk1/workspace/_work/1/s
mkdir: cannot create directory ‘/datadisks/disk1/workspace/_work/1/s’: File exists
##[error]Bash exited with code '1'.
```

from https://dev.azure.com/dnceng/public/_build/results?buildId=1317664&view=logs&jobId=78dbf170-f19d-550a-7379-a971ae8e679d&j=78dbf170-f19d-550a-7379-a971ae8e679d&t=4ff00257-e32b-5514-e832-c460084f2e29

**Comment by ViktorHofer** [comment]
@NikolaMilosavljevic when you remove the "untriaged" label please set a milestone.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @ViktorHofer do you know if this still repros?

**Comment by ViktorHofer** [comment]
Not that I know of.
