### ISSUE TITLE
Question about System.MissingMethodException: Method not found

### ISSUE THREAD

**Issue by dxynnez** [dotnet/runtime#58173]
Hi,

We are on .net core 3.1 and recently hit a strange problem which should be related to the classic .net dll hell.

We have a reference A which was built with package B (assembly version 2), we explicitly install an older version of B (assembly version 1) by mistake. I thought in that case either the build would fail or assembly B would not be able to load at runtime as A would require version 2 of package B but we only have version 1. But none of them seem to be the case and only the 'System.MissingMethodException' exception was thrown when package A try to invoke some APIs defined in package B during runtime. **So my first question is, does .net core automatically do bindingRedirect or my understanding is wrong?**

Ironically, those methods actually do exist in both versions of B - in version 2, we abstract the mentioned methods into another layer which the current interface inherits from, but the API surface didn't change. **So my second question is, in such case, why would those methods failed to be located at runtime?**

I am still pretty new to .net, especially new to the runtime assembly loading logic. I would appreciate it if someone can help me understand the above questions. Thanks in advance!

**Comment by dxynnez** [comment]
@Joe4evr thanks for taking time to code the example! That's crystal clear!

**Comment by dxynnez** [comment]
> There's no binding redirects in .NET Core / 5 / 6. Assembly reference is loaded if its version is same or higher than what is requested.

Thanks for the information! I just double checked our build and the problem is actually the opposite - we actually installed a higher version (assembly version) of B.
That makes sense as A was built with lower version of B, so CLR would be able to use a higher version of B.

**Comment by agocke** [comment]
Looks like this question was answered -- we don't do automatic binding redirects, but do try to load the highest version. If the loaded assembly doesn't match the interface that the reference was compiled against, that can cause a variety of failures, including MissingMethodException.

Closing for now, unless there's an unanswered question.
