### ISSUE TITLE
Mono: handle structs larger than 256 bytes correctly

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#58190]
We hardcode the size of structs to 256 bytes here:
https://github.com/dotnet/runtime/blob/3f61d42cdfc65cfa1822986a9d257f1558545c4d/src/mono/mono/mini/mini-runtime.c#L3400 

and here:

https://github.com/dotnet/runtime/blob/3f61d42cdfc65cfa1822986a9d257f1558545c4d/src/mono/mono/mini/mini-runtime.c#L3160

This causes an out of bounds check to abort the app when running the System.Text.Json tests on iOS arm64 devices because of this large struct: https://github.com/dotnet/runtime/blob/7b19ccefccb4d116a64bf09c9bb1db3dd1df35e8/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.SimpleTestStruct.cs

Note: we probably should also port https://github.com/dotnet/runtime/pull/52501 to `mono_jit_runtime_invoke`.

**Comment by SamMonoRT** [comment]
@lambdageek - we can close this right ? Fixed in main and backport also merged

**Comment by lambdageek** [comment]
Yes, that's right.
