### ISSUE TITLE
System.Text.Json code gen: collision when two classes share same name but different namespaces

### ISSUE THREAD

**Issue by Jericho** [dotnet/runtime#58198]
Given a class named `ClassA` in the `MyLibrary.Models` namespace and another class also named `ClassA` but in the `MyLibrary.Models.Legacy` namespace, and given the fact that I am decorating my custom serializer context like so:
```csharp
[JsonSerializable(typeof(MyLibrary.Models.ClassA))]
[JsonSerializable(typeof(MyLibrary.Models.Legacy.ClassA))]
internal partial class MyJsonSerializerContext : JsonSerializerContext
{
}
```

I get different symptoms depending on the version of VS.NET I'm using.

**When using VS.NET 2022**
```
Warning	CS8785	Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'MyJsonSerializerContext.ClassA.g.cs' of the added source file must be unique within a generator.
Error	CS0534	'MyJsonSerializerContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'instanceOptions' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?, JsonSerializerOptions?)'
```
![image](https://user-images.githubusercontent.com/112710/131006492-7857de83-944f-4bb9-ba9f-bfba6ea13c87.png)

**When using VS.NET 2019**
Visual Studio does not throw any error which leads me to think, incorrectly, that everything worked successfully but in actuality only one of the two `ClassA` is processed and the generated code for the second `ClassA` class is missing. As you can see in this screenshot of the generated code, only one of the two `ClassA` classes has been processed:

![image](https://user-images.githubusercontent.com/112710/131006297-779f7f5a-a863-4aaa-971d-7e2276d30c2b.png)

**Repro**
```csharp
using System;
using System.Text.Json.Serialization;

namespace MultipleClassesWithSameName
{
	public static class Program
	{
		public static void Main()
		{
			Console.WriteLine("Hello World!");
		}
	}
}

namespace MultipleClassesWithSameName.Utilities
{
	[JsonSerializable(typeof(MultipleClassesWithSameName.Models.ClassA))]
	[JsonSerializable(typeof(MultipleClassesWithSameName.Models.Legacy.ClassA))]
	internal partial class MyJsonSerializerContext : JsonSerializerContext
	{
	}
}

namespace MultipleClassesWithSameName.Models
{
	public class ClassA
	{
		[JsonPropertyName("id")]
		public string Id { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }
	}
}

namespace MultipleClassesWithSameName.Models.Legacy
{
	public class ClassA
	{
		[JsonPropertyName("id")]
		public int Id { get; set; }

		[JsonPropertyName("name")]
		public string Name { get; set; }
	}
}
```

**Comment by Jericho** [comment]
I confirm the workaround proposed by @steveharter works but it sure would be nice if this was handled automatically.

These are the two attributes I added to my custom context to solve the problem:
```csharp
[JsonSerializable(typeof(MyLibrary.Models.ClassA))]
[JsonSerializable(typeof(MyLibrary.Models.Legacy.ClassA), TypeInfoPropertyName = "LegacyClassA")]
```

**Side note:**
It appears that, behind the scenes, the code generator automatically generates code for `ClassA[]` and names it `ClassAArray`. Additionally, it also automatically generates code for `Legacy.ClassA[]` and names it `ClassAArray` which results in the same name conflict.

I worked around this issue by adding the following attribute to my context:
```csharp
[JsonSerializable(typeof(MyLibrary.Models.Legacy.ClassA[]), TypeInfoPropertyName = "LegacyClassAArray")]
```

**Comment by layomia** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/58938.

The generator now issues a diagnostic if there's a type name collision:

`error SYSLIB1031: There are multiple types named Location. Source was generated for the first
one detected. Use 'JsonSerializableAttribute.TypeInfoPropertyName' to resolve this collision.`

There's no great strategy for resolving name conflicts, it is better to leave it to the developer.
