### ISSUE TITLE
There are missing and mismatching cultures between .net and the os

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#58200]
### Description

There a re a few differences with the way the cultures work from the native mobile platform (iOS/Android) to the way .NET works.

One example is that Android has `in-ID` which is `id-ID` in .NET.

It ends up the case where it has to be manually mapped.

https://gist.github.com/JannieT/8d789ca837679cbd59244564160ebe32

I believe there are a few more differences, especially around Android allowing weird combinations between language and cultures.

**Comment by steveisok** [comment]
@mattleibow I'm going to close the issue as there's nothing we can do besides filing issues on Android.  That said, if this does impact iOS, please feel free to reopen and we can investigate.

**Comment by mattleibow** [comment]
This does happen on iOS as well. You can check the gist for each platform in the corresponding files.

Regardless, is it not possible to have some additional code that maps from whatever the icu gives to the .net values? Or is this a mismatch between the java and the icu?

**Comment by AraHaan** [comment]
I think it is between the java and the icu.

**Comment by mattleibow** [comment]
Doesn't that mean that we should more match the Java world since that is what Android is using? And Kotlin is also using that API. And also the Resources system uses the suffixes `drawable-xxxx`.
