### ISSUE TITLE
emsdk should place stable versioned blobs in a non-stable dir

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#58213]
This is the test-RTM build of emsdk:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1317768&view=results

It placed the 6..0 blobs in a stable dir (check MergedManifest.xml):

Blob Id="emsdk/**6.0.0**/Microsoft.Emscripten.2.0.23.Node.win-x64.6.0.0.msi.wixpack.zip" NonShipping="false" />

This should be in a non-stable directory. I am pretty sure this is almost correct, just that the package version obtained here: https://github.com/dotnet/emsdk/blob/main/eng/Publishing.props#L24 is a stable one. It may be able to be resolved by setting IsShipping=false or BlockStable=true before calling the msbuild task.

**Comment by SamMonoRT** [comment]
@akoeplinger - is this Mono specific ?

**Comment by mmitche** [comment]
> @akoeplinger - is this Mono specific ?

Nope, this is just an emsdk infra issue. @Anipik is resolving this. https://github.com/dotnet/emsdk/pull/71

**Comment by SamMonoRT** [comment]
@mmitche - what's the best Label used for such infra issues ? want to make sure it gets triaged correctly and has a milestone added

**Comment by mmitche** [comment]
probably area-infrastructure-mono

**Comment by SamMonoRT** [comment]
cc @steveisok fyi

**Comment by akoeplinger** [comment]
@mmitche https://github.com/dotnet/emsdk/pull/71 was merged, can we close this?
