### ISSUE TITLE
Remove `!` from `Microsoft.Extensions.FileSystemGlobbing`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#58211]
### Description

This is a blanket issue for all `!` operations that were added in https://github.com/dotnet/runtime/pull/57398
They should be removed or reviewed.

Left to be fixed/reviewed:
- [x] `FileSystemInfoBase.ParentDirectory` should be able to return null, but none of the implementation do that (`!` were added to allow that though). 
- [x] Implementations of `DirectoryInfoBase` differ in nullability for `GetDirectory` and `GetFile`

| Class | Can `GetDirectory` return null?  | Can `GetFile` return null? |
| :------------- |:-------------:| :-----:|
| DirectoryInfoBase | No (according to `<returns>` doc) | No (according to `<returns>` doc) |
| DirectoryInfoWrapper | Yes | No |
| InMemoryDirectoryInfo | No | Yes |

**Comment by jeffhandley** [comment]
Fixed in #57398
