### ISSUE TITLE
Some non-shipping packages in runtime have stable versions

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#58214]
The following non-shipping packages are getting stable versions when building in release mode:

- 'ILCompiler.Reflection.ReadyToRun.Experimental'
- 'runtime.linux-arm.Microsoft.CrossOsDiag.Private.CoreCLR'
- 'runtime.linux-arm64.Microsoft.CrossOsDiag.Private.CoreCLR'
- 'runtime.linux-musl-arm.Microsoft.CrossOsDiag.Private.CoreCLR'
- 'runtime.linux-musl-arm64.Microsoft.CrossOsDiag.Private.CoreCLR'
- 'runtime.linux-musl-x64.Microsoft.CrossOsDiag.Private.CoreCLR'

**Comment by ViktorHofer** [comment]
@Anipik can this be closed now?

**Comment by Anipik** [comment]
yes this is resolved.
