### ISSUE TITLE
Add more UTF8 marshalling tests 

### ISSUE THREAD

**Issue by tijoytom** [dotnet/runtime#5822]
1. It might be nice to include some test cases where we have strings with values outside the BMP.
   2.It might be nice to include some test cases where we have strings with values outside the BMP. As well as tests with ill-formed UTF-16 strings (trailing surrogates followed by leading ones, unpaired surrogates, etc) to codify the behavior we expect. 
2. out string where the string reference is modified.

**Comment by AaronRobinsonMSFT** [comment]
We have acceptable coverage for UTF-8.
