### ISSUE TITLE
System.Text.Json.SourceGeneration.Unit.Tests are disabled in WASM

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#58226]
Our System.Text.Json.SourceGeneration.Tests use the following to add references to the compilation:

https://github.com/dotnet/runtime/blob/7994e5940d8e093e6a7a6008358b539f9d8a352d/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.UnitTests/CompilationHelper.cs#L31-L37

This doesn't work in `browser-wasm` because `Assembly.Location` returns `string.Empty`. Thus we get exceptions that empty string is not a valid file path.

If we feel we need to run these tests on `browser-wasm`, we need to figure out a way to reference these assemblies so Roslyn can compile code.

cc @lewing @radical

**Comment by elinor-fung** [comment]
This is the case for all source generator unit tests, not just the System.Text.Json ones. Some of the others are disabled for other reasons beyond the `Assembly.Location` usage, but they do all currently `Assembly.Location` in some way to set up the references needed for compilation.
