### ISSUE TITLE
Remove "requestId" arguments from HTTP tests loopback server API

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#58239]
This is used very infrequently, and doesn't actually seem to be necessary in the places where it is used.

It also is weirdly inconsistent across HTTP/1.1/2/3. 

In general, it seems like non-version-specific tests should never need this, and we should just remove it.

**Comment by karelz** [comment]
Triage: This should be fairly simple, marking as up-for-grabs. Good for learning more about HTTP protocol.

**Comment by AnudeepGunukula** [comment]
Hi @karelz , @geoffkizer .
i had made a pr that will close this issue.
kindly review it and please let me know the changes if needed.

**Comment by AnudeepGunukula** [comment]
kinldy eloborate the issue
i removed the requestId argument from loopbackserver.cs and then
also removed argument from the abstract methods in genericloopbackserver.cs 
which further causing errors in  its implemented methods in http2loopbackconnection.cs and http3loopbackconnection.cs
kindly help me here should i continue removing requestId from those methods also.

**Comment by karelz** [comment]
@AnudeepGunukula I think the idea was to remove the argument -- which means, incl. inherited classes. Making it compile should be fairly straightforward, shouldn't it?
