### ISSUE TITLE
Extra file exist check in FileSystem.MoveDirectory on Unix

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#58240]
### Description

See https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L373-L376

There are two places where the FileSystem.MoveDirectory helper is used and in both places there is already the same check.

(The comment for Windows in the code is also weird.)

**Comment by carlossanlop** [comment]
Yes, there are two `FileExists` checks, but the first one is for the source path, and the second one is for the destination path. Since there is no bug or potential improvement we could make, I'll go ahead and close the issue.

https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L376

https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L393

**Comment by iSazonov** [comment]
@carlossanlop The issue is about _callsites_ - there are the check too.

**Comment by carlossanlop** [comment]
Thanks for the clarification. I saw the PR first and noticed the internal FileExists calls were being collapsed into one.

@m0ddixx the internal FileExists calls should not get modified. But I still think the fix should be approached differently. Feel free to submit a new PR if you would still like to address this.

**Comment by deeprobin** [comment]
> @carlossanlop The issue is about _callsites_ - there are the check too.
> 
> > There are two places where the FileSystem.MoveDirectory **helper is used** and in both places there is already the same check.

https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs#L288-L289

https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L376-L391

You should keep in mind that we throw a `DirectoryNotFoundException` in the first check and an `IOException` in the 2nd check.
Here I think it should be analyzed if `FileSystem.Move` is called by other methods or if there is any reason to do this (similar looking) check twice.

@JeremyKuhne According to `git blame` you have implemented this check. Can you enlighten us?

For reference: https://github.com/dotnet/corefx/pull/17913 & https://github.com/dotnet/corefx/pull/19716

/cc @alexperovich
/cc @stephentoub

**Comment by adamsitnik** [comment]
The issue got already solved by https://github.com/dotnet/runtime/pull/63675

@deeprobin if you are looking for something similar then https://github.com/dotnet/runtime/issues/65092 would be a great candidate

**Comment by deeprobin** [comment]
@adamsitnik 
Hi Adam, first I need to merge a few PRs before I start working on new issues (I still have a few open).
But if it's nothing time critical you can assign me the issue.
