### ISSUE TITLE
WebProxy method IsBypassed(uri) returns false although uri is in bypass list

### ISSUE THREAD

**Issue by FireEmerald** [dotnet/runtime#58249]
### Description

_[IWebProxy.GetProxy(uri)](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webproxy.getproxy?view=net-5.0)_ is only defined to return a proxy for the given `uri` assuming there is a proxy for it. Otherwise, it is assumed that _[IWebProxy.IsBypassed(uri)](https://docs.microsoft.com/en-gb/dotnet/api/system.net.webproxy.isbypassed?view=net-5.0)_ is called first and would return `true`. Thus a caller shouldn't call `GetProxy()`.

The problem is that _IsBypassed(uri)_ returns `false` if the `uri` matches a entry from the bypass list, instead of `true`.

### Example

**Code snippet:**
``` c#
private static void TestProxy()
{
    IWebProxy proxy = HttpClient.DefaultProxy;
    var uris = new List<Uri>()
    {
        new ("http://server.mynet.internal"),
        new ("http://google.de")
    };

    foreach (Uri uri in uris)
    {
        if (!proxy.IsBypassed(uri))
        {
            Uri proxyUri = proxy.GetProxy(uri);
            Console.WriteLine($"Proxy for Uri {uri.OriginalString} is used: {proxyUri?.ToString() ?? "<null>"}");
        }
        else
        {
            Console.WriteLine($"Bypassed proxy for Uri {uri.OriginalString}.");
        }
    }
}
```

**Actual Result:**
```
Proxy for Uri http://server.mynet.internal is used: <null>
Proxy for Uri http://google.de is used: http://192.168.0.100:1234/
```

**Expected Result:**
```
Bypassed proxy for Uri http://server.mynet.internal.
Proxy for Uri http://google.de is used: http://192.168.0.100:1234/
```

Windows Settings > Network & Internet > Proxy > Manual proxy settings
![Proxy](https://user-images.githubusercontent.com/1107939/131106422-51386178-1e02-4150-9ce0-271dcf4914b1.png)

### Configuration

<details>

```
.NET SDK (according to "global.json"):
 Version:   5.0.203
 Commit:    383637d63f

Runtime environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

### Other information

Ref some infos in #30066

**Comment by FireEmerald** [comment]
> What version do you have @FireEmerald and did you check that browser and/or .NET Framework process the wildcard properly? And does it work if you remove the `*`?

I already posted my whole Configuration in the very [first post](https://github.com/dotnet/runtime/issues/58249#issue-981073250). My tests are all executed in a simple .NET Core 5 Console App.

@wfurt Let's say our app retrieves the default proxy using `HttpClient.DefaultProxy` and gets a `IWebProxy` object back. This may be the `HttpEnvironmentProxy.cs` implementation or `HttpWindowsProxy.cs` or something else. The key point is now that depending on which implementation was just returned, the method `IsBypassed()` is implemented or always returns `false` - because of _performance reasons_ in the `HttpWindowsProxy` class.

I **don't** think that's a good idea. I would now suggest everybody to never call `IsBypassed()` as you can't rely on it, this makes the method on the interface useless. Just always call `GetProxy()` and check if the result is null or empty. What do you think?

**Comment by FireEmerald** [comment]
I correct myself you **MUST** call both methods, first `IsBypassed()` and then check if `GetProxy()` returns null. Because depending on the implementation you get from `HttpClient.DefaultProxy`.

-  `HttpEnvironmentProxy.cs`: `IsBypassed()` returns true or false, but `GetProxy()` **always** returns the proxy string.
- `HttpWindowsProxy.cs`: `IsBypassed()` **always** returns false, but `GetProxy()` null or the proxy to use.

**Comment by wfurt** [comment]
The IWebProxy is not great - but I think it is too late to change it. AFAIK it was meat that somebody can provide their own implementation but I don't think the use case was for somebody use consume HttpCliebnt's proxies directly. So yes, this is technically bug as it breaks the contract. But what is the use case? As I asked before, does it impact the ability to use HttpCLient?

**Comment by geoffkizer** [comment]
The documentation at https://docs.microsoft.com/en-gb/dotnet/api/system.net.webproxy.getproxy?view=net-5.0 does not seem to match the implementation. In particular, I believe we return null if the Uri is not proxied. The documentation seems to imply that we would return the original Uri in this case, which is (a) wrong and (b) weird. Am I missing something here?

**Comment by geoffkizer** [comment]
It seems weird to me that we essentially have two ways to say "this Uri is not proxied" -- you can *either* return false from IsBypassed, or you can return null from GetProxy(). And anyone who uses IWebProxy needs to check both.

In practice, as long as you check both, you should be fine.

That said, it seems like it would be better if it worked like this:

GetProxy(uri): Returns proxy Uri if proxied, null if not
IsBypassed(uri): Returns false if proxied, true if not. In other words this is equivalent to GetProxy(uri) == null.

If I want to get the proxy Uri (if any), I can call GetProxy() and don't need to call IsBypassed first.
If I only care about knowing if the Uri is bypassed, I can just call IsBypassed.

**Comment by wfurt** [comment]
I agree about the functionality @geoffkizer. Would that be breaking change if HttpClient does not use the IsBypassed(uri)? 

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs#L381-L401

In case of Windows/PAC the answer for neither question is simple. So effectively we would really need to do the processing twice.

**Comment by stephentoub** [comment]
> Would that be breaking change if HttpClient does not use the IsBypassed(uri)?

Considering examples like
https://github.com/microsoft/azure-pipelines-agent/blob/d6450cbb6c2b59af1b312959082ad38d045efa4e/src/Agent.Sdk/AgentWebProxy.cs#L74
and
https://github.com/NuGet/NuGet.Client/blob/543d419b002c33b2f63740b47e62db137d80d2b3/src/NuGet.Core/NuGet.Configuration/Proxy/WebProxy.cs#L68
yes.

**Comment by geoffkizer** [comment]
Yeah, I agree, we can't really make any semantic changes here in the interface definition.

I think what we should do is clarify how this should be used, in order to get correct results.

I think we should say this:

If you want to determine if a URL is proxied or not, you should first call IsBypassed(url). If this returns true, the URL is not proxied. If it returns false, you should call GetProxy(url). If this returns null, the URL is not proxied. If it returns non-null, that's the proxy URI for this URL.

Implicit in this is a couple things:
(1) Getting false from IsBypassed(url) does not guarantee that the URL is actually proxied; you need to call GetProxy to determine this. This is intentional because in some cases (windows proxy) it's inefficient to implement IsBypassed separately from GetProxy.
(2) The result you get from GetProxy is basically undefined when IsBypassed is true, and you should not rely on it. The docs say this returns the original Uri, but I don't think our implementations reliably do this, and frankly it's kind of weird.

Thoughts?

**Comment by karelz** [comment]
Triage: Agreed. Not ideal, but the interface is already shipped and we can't change it.
Let's document this.

@FireEmerald what do you think? Are you interested in helping with the docs clarifications?

**Comment by FireEmerald** [comment]
I'm unable to provide support to update the docs, sorry.

**Comment by MihaZupan** [comment]
Sorry I noticed the docs PR too late, @liveans can you please also fix the samples in the docs that show bypass patterns like `;*.contoso.com` which make no sense in Regex?

Using the current sample from the docs:
```c#
WebProxy proxy = new WebProxy("http://contoso", false, new string[] { ";*.Contoso.com" });	
proxy.IsBypassed(new Uri("http://acontoso-com")).Dump(); // True as the dot is matching any character
```

**Comment by liveans** [comment]
> Sorry I noticed the docs PR too late, @liveans can you please also fix the samples in the docs that show bypass patterns like `;*.contoso.com` which make no sense in Regex?
> 
> Using the current sample from the docs:
> 
> ```cs
> WebProxy proxy = new WebProxy("http://contoso", false, new string[] { ";*.Contoso.com" });	
> proxy.IsBypassed(new Uri("http://acontoso-com")).Dump(); // True as the dot is matching any character
> ```

Sure, I'll fix it on another PR
