### ISSUE TITLE
XmlSerializer throws exception on creation if using derived type that only partially overrides a property

### ISSUE THREAD

**Issue by Hallupa** [dotnet/runtime#58257]
The XmlSerializer throws exception on creation if the type specified is a derived type that partially overrides property.
Code example below:

```
class Program
{
    static void Main(string[] args)
    {
        XmlSerializer serializer = new XmlSerializer(typeof(B));
    }
}

[Serializable]
public class A
{
    public virtual int Abc { get; set; }
}

[Serializable]
public class B : A
{
    public override int Abc
    {
        set
        {
            base.Abc = value;
        }
    }
}
```

On creation of the XmlSerializer raises an 'Object reference not set to an instance of an object'. I've tried the same code as above in .net Framework and it works fine. In .net Core in throws the exception.

Tested this on .net Core 5.0 (Throws exception) and .net Framework 4.7.2 (Works) so seems to be a .net Core issue only. Tested on Windows 10 x64.

### Other information
A work around is to override the getter as well as the setter. When that is done, the code works so the issue only seems to happen when a property is partially overriden.

**Comment by StephenMolloy** [comment]
I do not have a PR to point to for this, but this no longer reproduces. Seems it was fixed in 6.0.
