### ISSUE TITLE
Empty string cannot be parsed to a nullable int with System.Text.Json with JsonNumberHandling.AllowReadingFromString

### ISSUE THREAD

**Issue by dxk3355** [dotnet/runtime#58289]
When parsing the empty string "" into an int? the .net JsonSerializer.Deserialize function will error out even with the option JsonNumberHandling.AllowReadingFromString enabled as well.  I can imagine there is an argument to be made that an empty string is not a null, however it is effectively the same as null in a situation when someone does not enter a value for an integer field.  I would expect that the empty string with JsonNumberHandling.AllowReadingFromString is treated the same as when there is a null in the field.  Instead it appears to be treating it more like than empty value.  

```
using System;
using System.Text.Json;

namespace TestJsonParse
{
    class Program
    {
        const string jsonInput1 = "{\"pn\":\"1\",\"buildingId\":\"1\"}";
        const string jsonInput2 = "{\"pn\":\"2\",\"buildingId\": null }";
        const string jsonInput3 = "{\"pn\":\"3\",\"buildingId\":\"\"}";  // This will error 

        static void Main(string[] args)
        {
            try
            {
                var opts = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                    IgnoreReadOnlyFields = true,
                    NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString
                };
                TestClass tc = JsonSerializer.Deserialize<TestClass>(jsonInput1, opts);
                Console.WriteLine(tc.ToString());
                tc = JsonSerializer.Deserialize<TestClass>(jsonInput2, opts);
                Console.WriteLine(tc.ToString());
                tc = JsonSerializer.Deserialize<TestClass>(jsonInput3, opts);  // Error here
                Console.WriteLine(tc.ToString());
            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

        public class TestClass
        {
            public int pn { get; set; }
            public int? buildingId { get; set; }

            public override string ToString()
            {
                return "pn:\t" + pn + System.Environment.NewLine +
                       "buildingId:\t" + buildingId.GetValueOrDefault(0) + System.Environment.NewLine;

            }
        }
    }
}
```

### Configuration

NET 5.0.9
Windows 10 x64

### Regression?

No

### Other information

The only possible work around is to read the value as a string then create a different get/set that parses the string.

The source JSON is likely using Newtonsoft JSON which does not seem to be compatible with  System.Text.Json in this respect.  When using NewtonSoft to deserialize the same inputs as provided the buildingId is 0 in the default configuration.

**Comment by steveharter** [comment]
STJ does not treat an empty string the same as `null` (or as the default value), so this JSON should throw where `buildingId` is deserialized to a `nullable<int>`:

```cs
const string jsonInput3 = "{\"pn\":\"3\",\"buildingId\":\"\"}";  // This will error 
```

The same behavior exists in 5.0.

A workaround is to create a custom `string` converter to treat empty string as `null`. Some have also done the opposite: treating `null` as empty string.

See also https://github.com/dotnet/runtime/issues/34310

cc @layomia @eiriktsarpalis
