### ISSUE TITLE
Concatenation of interpolated strings is corrupted

### ISSUE THREAD

**Issue by jamesgurung** [dotnet/runtime#58288]
The following project works as expected on Windows 10 x64, with the latest .NET Core SDK daily build:
```text
> dotnet --version
6.0.100-rc.2.21426.20

> dotnet new console
The template "Console Application" was created successfully.

> echo Console.WriteLine($"{1} {2}" + $""); > Program.cs

> dotnet run
1 2
```
However, if I delete `bin` and`obj`, and rebuild the same project in Visual Studio 17 Preview 3.1, it now **incorrectly outputs `2 1`**.

This is a minimal repro of a real issue I've encountered. It seems to occur when two interpolated strings are added together.

I can't work out what is different about how Visual Studio is building the project, but it's clearly causing an issue.

**Comment by Youssef1313** [comment]
This was already fixed in https://github.com/dotnet/roslyn/pull/55494. Will be released in 17.0 Preview 4.

**Comment by Youssef1313** [comment]
> I can't work out what is different about how Visual Studio is building the project, but it's clearly causing an issue.

Just to answer this part. That's a new language feature in C# 10 ([improved interpolated strings](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/improved-interpolated-strings.md))

**Comment by jamesgurung** [comment]
Thanks @Youssef1313. Does Visual Studio build with a different language version than `dotnet build`?

**Comment by Youssef1313** [comment]
If the language version is specified in MSBuild property `LanguageVersion` (via a .csproj or a .props file), then they should be using the same language version. You can see the compiler and language versions if you added `#error version` to the top of any source file in the project.

What I'm suspecting is that in both cases you're building with C# 10, however, the compiler version used by Visual Studio is more recent and it contains the new feature.
