### ISSUE TITLE
ALPN processing on Linux can be improved

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#58299]
this was noticed while working on #57079
There are few places when we allocate when we may not need to - particularly converting ALPN list to array. 
The list is typically small so we may use stackalloc. 
Further more, typical use would probably have only http11 and h2. We can probably special-case this and avoid processing for each connection.  HttpClient already does that:

https://github.com/dotnet/runtime/blob/999e412b15f92878cf2f3478e2c431606d2635ef/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L298-L300

**Comment by rzikm** [comment]
After discussion, there don't seem to be more opportunities for (meaningful) optimizations other than stackalloc'ing the buffer when setting ALPN.
