### ISSUE TITLE
IsStructMarshalable fails on C# arrays and fixed arrays with explicit bounds and attributes

### ISSUE THREAD

**Issue by kyanha** [dotnet/runtime#58305]
See #44508 for the reason for this regression.

### Description

I'm trying to implement source-specific multicast (IPv4 and IPv6) in C#, see #36170. To do so, I need to create a struct, like so:

```cs
[StructLayout(LayoutKind.Sequential, Pack = 1, Size = 128)]
internal unsafe struct GroupSourceRequest {
  [MarshalAs(UnmanagedType.U4)]
  internal Int32 InterfaceIndex;
  [MarshalAs(UnmanagedType.ByValArray, ArraySubType = UnmanagedType.U1, SizeConst = 128)]
  internal SockaddrStorage Group;
  [MarshalAs(UnmanagedType.ByValArray, ArraySubType = UnmanagedType.U1, SizeConst = 128)]
  internal SockaddrStorage Source;

  internal static int Size { get => Marshal.SizeOf<GroupSourceRequest>(); }
}
```

SockaddrStorage is as close as I can come to the SOCKADDR_STORAGE structure from the Windows SDK's winsock2.h (which also has the problem that it needs to be aligned on a 64-bit boundary, which the runtime doesn't enable):

```cs
[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal Struct SockaddrStorage {
  Int16 Family;
  fixed byte StructureData[126];
}
```

and I have to essentially fake a &lt;reinterpret_cast&gt; by directly copying data to and from SockaddrStorage4 and SockaddrStorage6 structures, which are intended to be reinterpreted from the same memory as SockaddrStorage.

The problem is that I need to marshal the GroupSourceRequest structure, including its two SockaddrStorage, for the setsockopt opcodes of MCAST_JOIN_SOURCE_GROUP and MCAST_LEAVE_SOURCE_GROUP.

Cause: The code in vm/fieldmarshaler.cpp returns false if it's an array, even when there's attributes describing precisely how it's supposed to be marshaled.

Regression: That new code completely breaks `MarshalAs(UnmanagedType.ByValArray, ArraySubType=UnmanagedType.U1, SizeConst=128)` even with all the information necessary to figure out the correct sizing of it.

I suspect this might also be why I'm getting errors of invalid or unaligned memory when I try to pass it (as `ref GroupSourceRequest`) to setsockopt when I manually pass the size (rather than trying to use `Marshal.SizeOf<GroupSourceRequest>()`, but Visual Studio's debugger is much less than helpful when dealing with fixed arrays.

### Configuration

.NET 5.0, Windows 10, x64. Linux doesn't appear to have the constants necessary for source-specific multicast; FreeBSD does, but I can't find any build of anything newer than beta3 for it, so I'm not even bothering there yet.
 
### Other information

From my test log:
```
Message: 
Test method SourceMulticast.Tests.SourceMulticastManagerTests.InstantiateASMMOnANewSocket4 threw exception: 
System.ArgumentException: Type 'Kyanha.Net.Sockets.SourceMulticast.Internal.GroupSourceReqStruct' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.

  Stack Trace: 
Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
Marshal.SizeOf(Type t)
Marshal.SizeOf[T]()
GroupSourceReqStruct.get_Size() line 41
SocketExtensions.DoProtocolIndependentMcastSourceOperation(Socket socket, SourceMulticastOpcode opcode, Socket sock, UInt32 Interface, IPAddress Group, IPAddress Source) line 58
SocketExtensions.JoinMulticastGroupWithSource(Socket sock, MulticastGroupSourceOption mgso) line 16
SourceMulticastManager.JoinSourceGroup(MulticastGroupSourceOption mgso) line 96
SourceMulticastManagerTests.InstantiateASMMOnANewSocket4() line 63
```

**Comment by fbrosseau** [comment]
While this does not answer your question about the custom MarshalAs, is there a reason why you haven't simply defined `Group` and `Source` as fixed 128 byte arrays directly within GroupSourceRequest? In fact at that point, I am not sure it is much clearer than a single flat array of [4 + 128 + 128] and avoid the marshaller altogether?

> and I have to essentially fake a <reinterpret_cast> by directly copying data to and from SockaddrStorage4 and SockaddrStorage6 structures, which are intended to be reinterpreted from the same memory as SockaddrStorage.

For simplicity, you can leverage IPEndPoint.Serialize and copy that into the corresponding segment of your blob. This is a bit allocatey, but saves you from encoding sockaddr_in / in6 yourself.

**Comment by jkotas** [comment]
> avoid the marshaller altogether?

Yes, it is a good practice to avoid complex interop marshaling using `MarshalAs`. It is both slow and tricky to get it right. It is best to keep your structs blittable where possible. https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices

**Comment by kyanha** [comment]
> 
> 
> > avoid the marshaller altogether?
> 
> Yes, it is a good practice to avoid complex interop marshaling using `MarshalAs`. It is both slow and tricky to get it right. It is best to keep your structs blittable where possible. https://docs.microsoft.com/en-us/dotnet/standard/native-interop/best-practices

My structs are as blittable as they can be -- I literally want to take a contiguous 128 bytes of memory and copy it into 2 specific locations in a 260-byte allocation.

But fixed arrays don't have the benefits of methods like Array.Copy<T> to do so.

So I end up with unsafe C# that looks like C or C++. `for (int i=0; i<128; i++) { PinnedGroupSourceReq[i+offset] = PinnedSockaddrStorage[i]; }`

How the [expletive elided] am I supposed to write this to look like C#?

**Comment by kyanha** [comment]
> 
> 
> While this does not answer your question about the custom MarshalAs, is there a reason why you haven't simply defined `Group` and `Source` as fixed 128 byte arrays directly within GroupSourceRequest? In fact at that point, I am not sure it is much clearer than a single flat array of [4 + 128 + 128] and avoid the marshaller altogether?

Because IPEndPoint.this[] doesn't give access to the full structure. It only gives access from the third byte to the end; the Family member is not provided as part of the subscriptable implementation.

> > and I have to essentially fake a <reinterpret_cast> by directly copying data to and from SockaddrStorage4 and SockaddrStorage6 structures, which are intended to be reinterpreted from the same memory as SockaddrStorage.
> 
> For simplicity, you can leverage IPEndPoint.Serialize and copy that into the corresponding segment of your blob. This is a bit allocatey, but saves you from encoding sockaddr_in / in6 yourself. I doubt multicast membership changes would be in the critical path? At least compared to actually doing something useful over multicast.

I already am doing this.

But the implementation in System.Net.Primitives is apparently designed to be the absolutely least-blittable structures they could possibly be.

**Comment by jkotas** [comment]
> which also has the problem that it needs to be aligned on a 64-bit boundary, which the runtime doesn't enable

You can get the structure aligned by defining a dummy long field. The Windows SDK achieves the alignment by defining a dummy long field as well.

```
[StructLayout(LayoutKind.Sequential)]
internal struct sockaddr_storage
{
  short ss_family;
  fixed byte StructureData[118];
  long __ss_align; // Used to align the structure.
}
```

Out coding convention is to use the exact same names as native platform headers for interop. `__ss_align` is used by Windows SDK for the dummy long field, so I have done the same here.

> The problem is that I need to marshal the GroupSourceRequest structure

The struct is blittable. You should not need to marshal the structure in any way. You can strip all the `MarshalAs` directives, and pass a pointer to it into `setsockopt`.

> So I end up with unsafe C# that looks like C or C++.

It is not unusual for the C# interop code to look like C or C++. Nothing wrong with that.

**Comment by AaronRobinsonMSFT** [comment]
Close this based on the response in https://github.com/dotnet/runtime/issues/58305#issuecomment-908343545
