### ISSUE TITLE
Runtime silent installation progress

### ISSUE THREAD

**Issue by wf-soft** [dotnet/runtime#58307]
How can I get the installation progress from the silent installation of the EXE file at runtime?

**Comment by wf-soft** [comment]
I'm currently using Process. Start (netRuntimeFile, "/ silent / install") to deploy the runtime, but I can't get his installation progress

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic can you check if our installer has options for progress notification in silent installs?

**Comment by wf-soft** [comment]
@NikolaMilosavljevic  There are no options for progress in setup

**Comment by NikolaMilosavljevic** [comment]
@wf-soft it sounds like this would be a request for a new functionality in .NET setup. Can you share a bit about scenarios where this would be used, perhaps there are alternatives that could be utilized?

**Comment by NikolaMilosavljevic** [comment]
Closing.
