### ISSUE TITLE
String.Equals(other, Ordinal) could be faster if the length comparsion was moved up

### ISSUE THREAD

**Issue by electricessence** [dotnet/runtime#58310]
### Description

For ordinal comparisons, comparing string lengths before checking equality tends to be faster.

### Configuration

.NET 5.0
Windows 10 x64

### Analysis

The benchmarks were initially to test Strings vs Spans, but the `.Length` test kept being a noticeable improvement.
https://github.com/electricessence/PerformanceExperiments

The mscorlb source (at least the one I found) shows the following before all other comparisons.
```cs
            if ((Object)this == (Object)value) {
                return true;
            }
 
            if ((Object)value == null) {
                return false;
            }
```

If ordinal comparisons are common, and since strings tend to be of different lengths, why not put a special case in for ordinal comparisons?  If the string is not null, then you can check the length before comparing references.

Are my assumptions wrong about why comparing lengths first performs better?

I'll refrain from further analysis about how `String.Equals(other, StringComparison)` is implemented, but its simply seems like some optimizations could occur here.

**Comment by EgorBo** [comment]
@electricessence `String.Equals` does use `a.Length != b.Length` as a fast out for Ordinal, see https://github.com/dotnet/runtime/blob/cffaa78235ea93d5e3eeb56956579df503e11250/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L724

Judging by 
> The mscorlb source
I guess you were looking at old .NET Framework sources.

**Comment by stephentoub** [comment]
Equal references are very common, especially due to const strings. As are null values, and you can't do a length check before a null check. The very next thing after that is switching based on the comparison type,  and if it's ordinal,  it does a length check. So I'm not sure what you're proposing about moving a length check earlier? A length check for culturally-sensitive comparisons isn't valid.

**Comment by EgorBo** [comment]
> Equal references are very common, especially due to const strings. As are null values, and you can't do a length check before a null check. The very next thing after that is switching based on the comparison type, and if it's ordinal, it does a length check. So I'm not sure what you're proposing about moving a length check earlier? A length check for culturally-sensitive comparisons isn't valid.

btw, reminds me a hack @GrabYourPitchforks shared in Discord:

`a.Length != b.Length` check can be optimized into `a.Length != b.Length && a[0] != b[0]` via a single read:
```csharp
bool eq = Unsafe.ReadUnaligned<ulong>(Unsafe.As<int, long>(ref str1._stringLength)) == 
          Unsafe.ReadUnaligned<ulong>(Unsafe.As<int, long>(ref str2._stringLength))
```
so we also will fast out for single-char strings with different content. And this check will still work for empty strings due to `\0`

**Comment by electricessence** [comment]
@EgorBo thanks for pointing me to the real code.

**Comment by electricessence** [comment]
So I ran a quick benchmark with .NET 6 (just `.Equals(string)`) in powershell with `-c release` to be sure no debugger and got results that were in line with real expectations.

https://github.com/electricessence/PerformanceExperiments/blob/master/PerformanceExperiments/StringEqualsTests.cs

Intel CPU Run 1:
|                               Method |     Mean |    Error |   StdDev |
|------------------------------------- |---------:|---------:|---------:|
|                     Equals_WithNulls | 56.54 ns | 0.474 ns | 0.370 ns |
|  EqualsWithLengthTestFirst_WithNulls | 53.43 ns | 0.302 ns | 0.283 ns |
|                       Equals_NoNulls | 53.07 ns | 0.386 ns | 0.322 ns |
|    EqualsWithLengthTestFirst_NoNulls | 51.27 ns | 0.232 ns | 0.217 ns |
| EqualsWithLengthTestFirstNoNullCheck | 51.21 ns | 0.265 ns | 0.248 ns |

Intel CPU Run 2:
|                               Method |     Mean |    Error |   StdDev |   Median |
|------------------------------------- |---------:|---------:|---------:|---------:|
|                     Equals_WithNulls | 59.49 ns | 1.714 ns | 4.891 ns | 56.59 ns |
|  EqualsWithLengthTestFirst_WithNulls | 54.93 ns | 0.249 ns | 0.221 ns | 54.86 ns |
|                       Equals_NoNulls | 49.00 ns | 0.731 ns | 0.571 ns | 48.80 ns |
|    EqualsWithLengthTestFirst_NoNulls | 51.73 ns | 0.354 ns | 0.277 ns | 51.66 ns |
| EqualsWithLengthTestFirstNoNullCheck | 51.97 ns | 0.753 ns | 0.705 ns | 51.77 ns |

AMD CPU Run:
|                               Method |     Mean |    Error |   StdDev |
|------------------------------------- |---------:|---------:|---------:|
|                     Equals_WithNulls | 60.05 ns | 1.275 ns | 2.427 ns |
|  EqualsWithLengthTestFirst_WithNulls | 52.10 ns | 1.049 ns | 1.208 ns |
|                       Equals_NoNulls | 50.74 ns | 1.073 ns | 1.054 ns |
|    EqualsWithLengthTestFirst_NoNulls | 49.53 ns | 1.040 ns | 1.113 ns |
| EqualsWithLengthTestFirstNoNullCheck | 46.90 ns | 0.970 ns | 0.860 ns |

Not sure what to think at this point.  It seems to still be true that you can squeeze maybe 10% possibly 25% if you already know your other string is not null and do a length check first.  I would have hoped this was some how baked in.

Is there some compiler magic that can solve this?

**Comment by electricessence** [comment]
@EgorBo, I've also noticed that if lengths are equal and there could be some quick shortcuts added here:
https://github.com/dotnet/runtime/blob/cffaa78235ea93d5e3eeb56956579df503e11250/src/libraries/System.Private.CoreLib/src/System/String.Comparison.cs#L24

A proposed change:
```cs
        private static bool EqualsHelper(string strA, string strB)
        {
            Debug.Assert(strA != null);
            Debug.Assert(strB != null);
            Debug.Assert(strA.Length == strB.Length);

            switch(strA.Length)
            {
                case 0:
                    return true;
                case 1:
                    return strA[0]==strB[0];
            }
            

            return SpanHelpers.SequenceEqual(
                    ref Unsafe.As<char, byte>(ref strA.GetRawStringData()),
                    ref Unsafe.As<char, byte>(ref strB.GetRawStringData()),
                    ((uint)strA.Length) * sizeof(char));
        }
```

**Comment by EgorBo** [comment]
> @EgorBo, I've also noticed that if lengths are equal and there could be some quick shortcuts added here:

All callers of `EqualsHelper` do this kind of checks already.

**Comment by electricessence** [comment]
I understand there may not be a fix for this.  But I don't think I can shatter my idea that if you already know your strings aren't null that a length check upfront will be faster.  I'd prefer to be wrong about that.

**Comment by Clockwork-Muse** [comment]
@electricessence - The only way to remove the null check in a general equality method is if the compiler could elide it.

**Comment by electricessence** [comment]
> All callers of `EqualsHelper` do this kind of checks already.

@EgorBo not for the specific cases of 0 and 1.

**Comment by GrabYourPitchforks** [comment]
The comment I made on Discord was based on a conversation I had with Andy a while back, where we were bantering whether the JIT could special-case `operator==` against a non-literal string and a literal string and produce optimal codegen. For example, `(str == "some_literal")` becomes:

* If the literal is the empty string, a simple length check of _str_.
* If the literal is 1 or 2 chars, a single 64-bit read of _str.Length_ (which will include the first char and the second char or the null terminator).
* If the literal is 3 or 4 chars, a single 64-bit read of _str.Length_ (encompasses first two chars) plus a single 32-bit read of chars 3 + 4 (or 3 + null terminator).
* Etc.

Example:

```cs
// original
bool isHello = str == "Hello";

// optimized (rewritten by JIT)
bool isHello = ReadAsUInt64(&str.Length) == 0x0065004800000005 /* "He" + length(5) */
  && ReadAsUInt64(&str.Length + 8) == 0x0000006F006C006C /* "llo\0" */;
```

(I may have gotten the endianness wrong in this example, but you get the gist.)

**Comment by stephentoub** [comment]
> The comment I made on Discord

Is this issue now tracking implementing the proposed length+first-char optimization?

If not, what is it tracking, or can it be closed?

**Comment by electricessence** [comment]
I think it's worth closing as long as there's awareness of it.
