### ISSUE TITLE
The build instructions do not mention clr.dactools (soon nativeprereqs)

### ISSUE THREAD

**Issue by albertlab0** [dotnet/runtime#58328]
Hi I am hitting on this issue with latest version:

The application to execute does not exist: 

**9>The application to execute does not exist: 'E:/work/dotnet/runtime/artifacts/bin/coreclr/windows.x64.Debug/DacTableGen/DacTableGen.dll'
9>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'E:\work\dotnet\runtime\artifacts\obj\coreclr\windows.x64.Debug\ide\CMakeFiles\1f2a7b96d174e6afb14c443eb282e277\inject_debug_resources_singlefilehost.timestamp.rule;E:\work\dotnet\runtime\artifacts\obj\coreclr\windows.x64.Debug\ide\CMakeFiles\1b6f9782b401a901cd7a6d111bc248c5\inject_debug_resources_singlefilehost.rule' exited with code -2147450751.**

This seems to be related to DAC/ninja.
Any idea what is the real issue here?

**Comment by tommcdon** [comment]
@hoyosjs @mikem8361

**Comment by hoyosjs** [comment]
What was your command to build? You need to run `./build.cmd clr.dactools -c debug` at least once.

**Comment by albertlab0** [comment]
I was following the instructions from:
https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging.md

where _./build.cmd clr.dactools -c debug wasn't mentioned.

That comand does fix the problem
