### ISSUE TITLE
Test failure: ConnectAsync_Cancel_ThrowsCancellationException

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#58355]
Test type: `System.Net.WebSockets.Client.Tests.CancelTest`

Failures 6/30-8/30 (incl. PRs):

Day | Run | OS
-- | -- | --
7/16 | 2x PR #55849 | Ubuntu.1804.Amd64.Open - Mono / wasm
8/13 | Official run | Ubuntu.1604.Amd64.Open - CoreCLR
8/27 | PR #58285 | Ubuntu.1804.Amd64.Open - Mono / wasm
9/2 | PR #57208 | windows.10.amd64.server20h1.open.rt - Mono / wasm (pending verification in Kusto)

Failure:
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)

   at System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by mdh1418** [comment]
Also seen on https://dev.azure.com/dnceng/public/_build/results?buildId=1341104&view=logs&j=f9ca8601-c4c2-5da2-61cf-0da7d83d7557&t=6f9dc6e4-5fb8-536e-70b9-642f2da0a848
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57208-merge-acfe8ed5abcd4ea499/System.Net.WebSockets.Client.Tests/1/console.3964cd41.log?sv=2019-07-07&se=2021-09-23T15%3A02%3A15Z&sr=c&sp=rl&sig=pLYZdJ0aw5j0ZXuP9CsaiAvUc3I5taR16kDxoP5oQB8%3D
From unrelated PR https://github.com/dotnet/runtime/pull/57208

**Comment by CarnaViire** [comment]
There's a recent spike in failures for the test for coreclr, noticed in #59204

Count | Date | Branch | OS
-- | -- | -- | --
108 | 2021-09-21 | main, pr #59204 |	"osx.1014.amd64","osx.1015.amd64","sles.15.amd64","centos.8.amd64","windows.81.amd64","debian.10.amd64","debian.11.amd64","fedora.34.amd64","ubuntu.1804.amd64","ubuntu.1604.amd64","windows.10.amd64.server19h1.es","alpine.312.amd64","windows.11.amd64.clientpre","osx.1100.arm64","redhat.7.amd64","windows.10.amd64.server19h1","sles.12.amd64","ubuntu.1910.amd64","windows.nano.1809.amd64","mariner.1.0.amd64","debian.10.arm32","windows.server.core.1909.amd64","debian.11.arm32","windows.10.amd64.serverrs5","windows.7.amd64","osx.1013.amd64","ubuntu.1804.armarch" 
82 | 2021-09-20 | main |	"osx.1100.arm64","osx.1015.amd64","sles.12.amd64","osx.1013.amd64","alpine.312.amd64","debian.10.arm32","debian.11.arm32","osx.1014.amd64","fedora.34.amd64","windows.10.amd64.serverrs5","windows.nano.1809.amd64","debian.10.amd64","ubuntu.1910.amd64","windows.10.amd64.server19h1","windows.81.amd64","mariner.1.0.amd64","sles.15.amd64","redhat.7.amd64","centos.8.amd64","ubuntu.1604.amd64","ubuntu.1804.armarch","windows.7.amd64","ubuntu.1804.amd64","debian.11.amd64"
83 | 2021-09-19 | main |	"sles.15.amd64","sles.12.amd64","alpine.312.amd64","windows.81.amd64","windows.nano.1809.amd64","windows.10.amd64.server19h1","ubuntu.1910.amd64","mariner.1.0.amd64","windows.10.amd64.serverrs5","windows.7.amd64","redhat.7.amd64","ubuntu.1604.amd64","debian.11.arm32","debian.10.amd64","debian.11.amd64","fedora.34.amd64","ubuntu.1804.amd64","ubuntu.1804.armarch","centos.8.amd64","debian.10.arm32","osx.1014.amd64","osx.1013.amd64","windows.server.core.1909.amd64","osx.1015.amd64","osx.1100.arm64"

**Comment by am11** [comment]
Seems like it has spiked quite significantly in outerloop runs after tweaking made in https://github.com/dotnet/runtime/commit/360df71eadde0d1394ee7b89693f83913f75575d.

cc @ViktorHofer noticed many legs are failing on this test.

**Comment by rzikm** [comment]
No recent hits, closing until issue resurfaces.
