### ISSUE TITLE
Incorrect ordering of Slovak words in F# and C#

### ISSUE THREAD

**Issue by janbodnar** [dotnet/runtime#58362]
I tried to sort Slovak words in different languages. In C#, it was roughly good; F# sorting was completely off.
(None of the languages got it right 1oo%, Go and Raku languages  are closest to the correct solution.)

I tested the examples on .NET 5.0.400 with x86_64 Linux. 

### C# version

```
using System;
using System.Globalization;
using System.Collections.Generic;

Console.OutputEncoding = System.Text.Encoding.UTF8;
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("sk-SK");

var words = new List<string>
{
    "čaj", "auto", "pot", "márny", "kľak", "chyba" ,"drevo", "cibuľa", "džíp" ,"džem", "šum" ,"pól", "čučoriedka" ,
    "banán", "čerešňa", "červený", "klam" ,"čierny", "tŕň" ,"pôst" ,"hôrny", "mat", "chobot", "cesnak", "kĺb",
    "mäta", "ďateľ", "troska", "sýkorka", "elektrón", "fuj" ,"zem", "guma", "hora", "genzír", "ihla", "pýr", "hrozno",
    "jazva", "džavot", "lom"
};

words.Sort();

foreach (var word in words)
{
    Console.Write($"{word} ");
}
```
The **C# version** got this output:
auto banán cesnak cibuľa čaj čerešňa červený čierny čučoriedka ďateľ drevo džavot džem džíp elektrón fuj genzír guma hora hôrny hrozno chobot chyba ihla jazva kľak klam kĺb lom márny mat mäta pól pot pôst pýr sýkorka šum tŕň troska zem 

This sorting has issues with accents. While č correctly follows c, other letters are incorrect. 

The following is the correct ordering of characters in Slovak language:

a, á, ä, b, c, č, d, ď, dz, dž, e, é, f, g, h, ch, i, í, j, k, l, ĺ, ľ, m, n, ň, o, ó, ô, p, q, r, ŕ, s, š, t, ť, u, ú, v, w, x, y, ý, z, ž

Note that plain characters always precede the accented ones. So the word ďateľ should go after drevo, the sequence
kľak klam kĺb should be klam kĺb kľak, márny mat mäta should be mat márny mäta, pól pot pôst should be
pot pól pôst, and tŕň troska should be troska tŕň.

The words with digraph ch are correct. The ch follows h. (The dž digraphs are probably also good. Not 100% sure because there is an issue with ď.)

The correct solution:
auto banán cesnak cibuľa čaj čerešňa červený čierny čučoriedka drevo ďateľ džavot džem 
džíp elektrón fuj gejzír guma hora hôrny hrozno chobot chyba ihla jazva klam kĺb kľak lom 
mat márny mäta pot pól pôst pýr sýkorka šum troska tŕň zem

### F# version

```
open System
open System.Globalization

let skSk = CultureInfo("sk-SK");

Console.OutputEncoding <- System.Text.Encoding.UTF8
CultureInfo.DefaultThreadCurrentCulture <- skSk

let words = 
    [|
        "čaj"; "auto"; "pot"; "márny"; "kľak"; "chyba" ;"drevo"; "cibuľa"; "džíp" ;"džem"; "šum" ;"pól"; "čučoriedka" 
        "banán"; "čerešňa"; "červený"; "klam" ;"čierny"; "tŕň" ;"pôst" ;"hôrny"; "mat"; "chobot"; "cesnak"; "kĺb"
        "mäta"; "ďateľ"; "troska"; "sýkorka"; "elektrón"; "fuj" ;"zem"; "guma"; "hora"; "genzír"; "ihla"; "pýr"; "hrozno"
        "jazva"; "džavot"; "lom"
    |]

words |> Array.sort |> Array.iter (fun e -> Console.Write($"{e} "))
```

Output: 
auto banán cesnak chobot chyba cibuľa drevo džavot džem džíp elektrón fuj genzír guma hora hrozno hôrny ihla jazva klam kĺb kľak lom mat márny mäta pot pól pôst pýr sýkorka troska tŕň zem čaj čerešňa červený čierny čučoriedka ďateľ šum 

The F# version is off. The accents and the digraphs are incorrect. The accented chars are just thrown after plain letters.
Interestingly, the sorting of accented characters inside words (klam kĺb kľak),  (mat márny mäta), (pot pól pôs) is correct here.

**Comment by tarekgh** [comment]
@janbodnar please file this issue on dotnet/fsharp as this is not specific to the runtime repo. Thanks.

Side note, why you are using `CultureInfo.DefaultThreadCurrentCulture`? I guess the correct property to use is `CultureInfo.CurrentCulture` instead.

**Comment by janbodnar** [comment]
@tarekgh 
While I am more interested in a correct F#  solution, the C# is also not correct. 
Hmm, System.Globalization is not part of the runtime?

Both CultureInfo.DefaultThreadCurrentCulture and CultureInfo.CurrentCulture give the same result.

**Comment by tarekgh** [comment]
@janbodnar .NET is getting its sorting behavior from ICU library (which is implementing the Unicode standard Collation Algorithm). Playing with Swedish culture sorting, it looks to me ICU is treading `d` < `ď` as you mentioned only if you compare them as one character. But treat them as equal if it is part of the word which means it will sort according to what comes next after `d` and `ď`. You may play with ICU sorting by going to the [Collation Demo](https://icu4c-demos.unicode.org/icu-bin/collation.html). Choose `sv` locale from the dropdown box and then paste the string you want to sort in Input box then click sort button. 

If you think this is a wrong behavior, I suggest you open a ticket to the ICU library explaining the correct https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues/.

**Comment by MichalStrehovsky** [comment]
> Note that plain characters always precede the accented ones

Sorting in Slovak is more complicated than that - see e.g. https://jazykovaporadna.sme.sk/q/1138/.

As Tarek wrote, the default sorting in .NET follows what ICU says. The C# example above matches ICU output.

The F# `Array.sort` doesn't call into the default comparer for strings and instead does its own thing (per F# docs "*Elements are compared using Operators.compare.*", whatever that means). That's why the result is different and not lexicographically correct for the sk-SK locale.

**Comment by janbodnar** [comment]
>  it looks to me ICU is treading d < ď as you mentioned only if you compare them as one character. But treat them as equal if it is part of the word which means it will sort according to what comes next after d and ď.

At least in Slovak case, it depends on the length of the word. The accents are ignored if they are at the same position 
but the length of the words are different. If the length is the same, then accented go after not accented.

> As Tarek wrote, the default sorting in .NET follows what ICU says. The C# example above matches ICU output.

I have checked the demo and there are we can find two Slovak sorting norms: standard sk norm and search sk norm.
The standard is the one that C# uses apparently; it is probably geared to the overall Unicode standard. The second 
one, called `sk-u-co-search` is the most correct one, according to my knowledge about sorting. 

So maybe, the situation could be improved by adding an additional Slovak LCID? We can find a separate Spanish one 
(1034 | Spanish - Spain (Traditional Sort) ).

> The ICU Collation Service supports many levels of comparison (named “Levels”, but also known as “Strengths”). Having these categories enables ICU to sort strings precisely according to local conventions.

It also could be a good idea to have some API for these.

I will check with the F# team about this.

**Comment by tarekgh** [comment]
> The second one, called sk-u-co-search is the most correct one, according to my knowledge about sorting.

I am seeing this one still sorting `ďateľ < drevo` which is different than what you originally mentioned. 


> So maybe, the situation could be improved by adding an additional Slovak LCID?

LCID is obsolete concept, and shouldn't be used anymore. We may fix allowing the culture name `sk-u-co-search` in .NET though.

**Comment by tarekgh** [comment]
In .NET 8.0 you can get the desired sort order by using the culture name including the collation behavior. like:

```C#
CultureInfo.CurrentCulture = new CultureInfo("sk-SK_search"); // using `search` collation for sk-SK
```
