### ISSUE TITLE
[API Proposal]: Provide MemoryMarshal.Cast(Memory) method or alternative to asynchrously fill an array

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#58363]
### Background and motivation

There needs to be an easy way of reading a stream into an array or structures asynchronously.

Synchronously reading a stream of structures into an array seems easy using this method: 

```c#
static T[] CreateArrayFromStream<T>(Stream stream, long offset, int count) where T : struct
{
    T[] array = new T[count];
    var spanT = array.AsSpan();
    var spanBytes = MemoryMarshal.Cast<T, byte>(spanT);
    stream.Seek(offset, SeekOrigin.Begin);
    stream.Read(spanBytes);
    return array;
}
```

Usage:

```c#
var arr = new byte[] {10, 0, 0, 0, 100, 0, 0, 0};
var ms =  new MemoryStream(arr);
var result = CreateArrayFromStream<int>(ms, 0, 2);
System.Console.WriteLine(result); // == new int[] {10, 100}
```

However `Read` is synchronous and replacing it with `ReadAsync` isn't possible.

```c#
static async Task<T[]> CreateArrayFromStreamAsync<T>(Stream stream, long offset, int count) where T : struct
{
    T[] array = new T[count];
    var memT = array.AsMemory();
    var memBytes = MemoryMarshal.Cast<T, byte>(memT);  // Compiler Error
    stream.Seek(offset, SeekOrigin.Begin);
    await stream.ReadAsync(memBytes);
    return array;
}
```

### API Proposal

```C#
namespace System.Runtime.InteropServices
{
     public static class MemoryMarshal
     {
          Memory<TTo> Cast<TFrom, TTo>(Memory<TFrom> memory);
     }
}
```     

### API Usage

```C#
var memBytes = MemoryMarshal.Cast<T, byte>(memT);  // This statement would compile

### Risks

_No response_

**Comment by GrabYourPitchforks** [comment]
This cannot be done reliably without killing the performance of `Memory<T>` in general. The reason for this is that unlike `Span<T>` - which has an interior ref to the data - a `Memory<T>` contains a reference to the real object itself. We make strong assumptions about what types of objects can be contained here. For example, we cannot currently back a `Memory<byte>` with a `char[]`, and if we were to support this we'd need to include these polymorphic checks every single time somebody calls `Memory<T>.get_Span`.

What you can do as a workaround is to implement your own custom `IMemoryManager<T>`, where its span and pinned pointer getters perform the translation from _U_ -\> _T_ within the implementation. For example, you could wrap an `IMemoryManager<byte>` around a `string` instance, performing the fixups yourself as needed. Then create a `ReadOnlyMemory<byte>` around your own `IMemoryManager<byte>` instance.

This would be unsafe-equivalent code, so you'd need to make sure your translations are valid and do not create dangling references or writable references to readonly memory, and you'd need to be prepared for these code paths to allocate more than a typical `Memory<T>` would. (Creating an `IMemoryManager<T>` necessarily involves an allocation.) But it does allow you to take full control of this if needed.

**Comment by Sergio0694** [comment]
@virzak If it helps, we have this API available in the `Microsoft.Toolkit.HighPerformance` package (now `CommunityToolkit.HighPerformance`), it's [`MemoryExtensions.Cast<TFrom,TTo>(Memory<TFrom>)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.memoryextensions.cast). The same extension is also available for `ReadOnlyMemory<T>` as well. It uses an implementation similar to the one @GrabYourPitchforks mentioned, with some optimizations where possible (eg. there are specialized memory managers for `string`-backed `Memory<T>` instances as well as for `T[]`-backed ones, etc.) to make the custom manager faster and remove double indirections when possible. 😄

**Comment by adamsitnik** [comment]
Since we are not interested in adding it to BCL and an alternative exists, I am going to close the issue. Thanks!

**Comment by virzak** [comment]
`AsBytes` solves my issue. Thanks! Was also considering @mgravell 's solution at SO: https://stackoverflow.com/a/54512940/6461844 

For anyone interested in my implementation:

<details>

```cs
public static class StreamExtensions
{
    public static async Task<T[]> CreateArrayAsync<T>(this Stream stream, long offset, long count, CancellationToken ct = default) where T : unmanaged
        => await MemoryUtils.CreateArrayFromStreamAsync<T>(stream, offset, count, ct).ConfigureAwait(false);

    public static T[] CreateArray<T>(this Stream stream, long offset, long count) where T : unmanaged
        => MemoryUtils.CreateArrayFromStream<T>(stream, offset, count);
}

public static class MemoryUtils
{
    /// <summary>
    /// Creates an array of structs from a stream asynchronously
    /// </summary>
    /// <typeparam name="T">Unmanaged structure to read</typeparam>
    /// <param name="stream">The stream to read from</param>
    /// <param name="offset">A byte offset relative to the origin parameter.</param>
    /// <param name="count">Count of structures to read</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Array of structs of type T</returns>
    public static async Task<T[]> CreateArrayFromStreamAsync<T>(Stream stream, long offset, long count, CancellationToken ct = default) where T : unmanaged
    {
        var array = new T[count];
        var memT = array.AsMemory();
        var memBytes = memT.AsBytes();
        stream.Seek(offset, SeekOrigin.Begin);
        await stream.ReadAsync(memBytes, ct).ConfigureAwait(false);
        return array;
    }

    /// <summary>
    /// Creates an array of structs from a stream
    /// </summary>
    /// <typeparam name="T">Unmanaged structure to read</typeparam>
    /// <param name="stream">The stream to read from</param>
    /// <param name="offset">A byte offset relative to the origin parameter.</param>
    /// <param name="count">Count of structures to read</param>
    /// <returns>Array of structs of type T</returns>
    public static T[] CreateArrayFromStream<T>(Stream stream, long offset, long count) where T : unmanaged
    {
        T[] array = new T[count];
        var spanT = array.AsSpan();
        var spanBytes = MemoryMarshal.Cast<T, byte>(spanT);
        stream.Seek(offset, SeekOrigin.Begin);
        stream.Read(spanBytes);
        return array;
    }
}
```
</details>

So what's the most efficient way of reading an array of structs from a stream?

Reading into a byte array, then converting to struct results in allocating twice. I'd guess that's how the majority of implementations deal with it.
How does it compare to `CommunityToolkit.HighPerformance`'s `AsBytes` extension? Does it kill the performance? Will it be worse if a lot of structs are being read?

Perhaps the API proposal should be to extend `System.IO.Stream` instead?

```diff
namespace System.IO
{
  public abstract class Stream 
  {
+   public static async ValueTask<int> ReadAsync<T>(Stream stream, Memory<T> buffer, CancellationToken cancellationToken = default) where T : unmanaged
  }
}
```

**Comment by GrabYourPitchforks** [comment]
@virzak A Stream API won't be added for the same reason I gave at https://github.com/dotnet/runtime/issues/58363#issuecomment-908560666. Performing a reinterpreting cast from _T_ to _U_ is not generally a safe operation, and this would encourage callers to splat arbitrary bit patterns over structs which may not be able to handle such patterns in a type-safe fashion. It could lead to vulnerabilities in the application in addition to the unexpected perf hit mentioned previously.
