### ISSUE TITLE
[API Proposal]: Introduce RandomAccess.SetLength(SafeFileHandle handle) method

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#58376]
### Background and motivation

Recently, we have introduced new `RandomAccess` type (#24847) which exposes some convenient methods for File IO. One of them is `RandomAccess.GetLength(SafeFileHandle)` that allows for reading file length.

When it comes to setting file length, users can:

* use `FileMode.Truncate` to truncate given file when opening it.
* specify `preallocationSize` to set initial size when opening the file.

The problem is that by using the new APIs, they can't set file length after the file has been opened.

`FileStream` exposes `SetLength` method, so should `RandomAccess`.

### API Proposal

```C#
namespace System.IO
{
    public static class RandomAccess
    {
        public static void SetLength(SafeFileHandle handle, long length);
    }
}
```     

### API Usage

```C#
void WriteToFile(string path, string contents, Encoding encoding)
{
    long estimatedFileSize = encoding.GetMaxByteCount(contents.Length); // estimated file length
    using SafeFileHandle fileHandle = OpenHandle(path, FileMode.Create, FileAccess.Write, preallocationSize: estimatedFileSize);

    byte[] bytes = encoding.GetBytes(contents);
    RandomAccess.Write(fileHandle, bytes, fileOffset: 0);

    if (bytes.Length < estimatedFileSize) // shrink the size if initial estimation was wrong
    {
        RandomAccess.SetLength(fileHandle, bytes.Length);
    }
}
```     

### Risks

I can't see any.

**Comment by adamsitnik** [comment]
> Open a FileStream, get its SafeFileHandle, use that for reads/writes and call FileStream.SetLength() to set the file length?

Yes. The alternative it to specify the exact size as `preallocationSize` when opening file

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.IO
{
    public partial static class RandomAccess
    {
        public static void SetLength(SafeFileHandle handle, long length);
    }
}
```
