### ISSUE TITLE
Move the JIT interface to explicitly sized types.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/runtime#5837]
Now that the JIT may be built on many platforms using many toolchains, we should make sure that the JIT/EE interface uses types with well-defined sizes on all platforms. This includes e.g. replacing unsized types (int, unsigned, etc.) with sized equivalents from stdint, ensuring that all enums have explicit sizes.

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
I'm going to close this
