### ISSUE TITLE
[WASM] 4GB address space

### ISSUE THREAD

**Issue by htdag** [dotnet/runtime#58382]
Consider `-s MAXIMUM_MEMORY=4GB` emcc flag and it's implications for mono VM codebase.
Review other aspects, which may prevent handling large data. 
Among others, how many copies of data we have at any time.

----- Original description
Got out of memory when load big file (~1GB) to memory.
```cs
// <InputFile OnChange="OnInputFileChange"
async Task OnInputFileChange(InputFileChangeEventArgs e)
{
    var file = e.File;
    using (var stream = file.OpenReadStream(file.Size))
    {
        var ms = new MemoryStream((int)file.Size);
        await stream.CopyToAsync(ms); // memory access out of bounds | Out of memory
        
        // ...
    }
}
```
=>
```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[120]:0x53cf
    at <anonymous>:wasm-function[3924]:0xc7ead
    at <anonymous>:wasm-function[3925]:0xc7f03
    at <anonymous>:wasm-function[1749]:0x43fd6
    at <anonymous>:wasm-function[3923]:0xc7e2b
    at <anonymous>:wasm-function[6542]:0x158b1e
    at Object.Module._mono_wasm_string_from_utf16 [as mono_wasm_string_from_utf16] (dotnet.6.0.0-preview.7.21377.19.js:1)
    at Object.js_string_to_mono_string_new (dotnet.6.0.0-preview.7.21377.19.js:1)
    at Object.js_string_to_mono_string (dotnet.6.0.0-preview.7.21377.19.js:1)
    at Object.converter_ssss [as compiled_function] (converter_ssss:11)
```

**Comment by jtorjo** [comment]
So if I read this correctly, there's no chance of this making it in .net7 as well?

**Comment by pavelsavara** [comment]
It would be good to test if it possibly works already.
Adding 
`<EmccExtraLDFlags> -s MAXIMUM_MEMORY=4294901760</EmccExtraLDFlags>` to .csproj may do the initial trick. Then allocate lot of memory and do some basic testing. To see if we have signed integer arithmetic dealing with pointers by mistake somewhere in the runtime code.

**Comment by pavelsavara** [comment]
I just quickly tested sample with 

```
    <WasmBuildNative>true</WasmBuildNative>
    <EmccInitialHeapSize>4294901760</EmccInitialHeapSize>
    <EmccExtraLDFlags> -s MAXIMUM_MEMORY=4294901760</EmccExtraLDFlags>
```

and it said hello world as normal.

Firefox
![image](https://github.com/dotnet/runtime/assets/271576/730558c5-e20d-490e-844c-b4920d497260)

Chrome
![image](https://github.com/dotnet/runtime/assets/271576/359be481-0c3a-452d-9c5a-421c80058d43)

But when I tried to allocate large memory it failed.

```
var xxx=new byte[0x8000_0000];
Console.WriteLine ("alloc");
xxx[0]=1;
Console.WriteLine ("write");
xxx[0x7000_0000]=1;
Console.WriteLine ("write");
Console.WriteLine($"Read {xxx[0x7000_0000]+xxx[0]}");
```

```
C:\Dev\runtime\src\mono\sample\wasm\browser-advanced\Program.cs:line 17
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object , Span`1 , BindingFlags )
Error: Arithmetic operation resulted in an overflow.
    at marshal_exception_to_js (http://localhost:8506/dotnet.runtime.js:2485:18)
    at invoke_method_and_handle_exception (http://localhost:8506/dotnet.runtime.js:3516:19)
    at runtimeHelpers.javaScriptExports.call_entry_point (http://localhost:8506/dotnet.runtime.js:4818:13)
    at mono_run_main (http://localhost:8506/dotnet.runtime.js:15521:45)
    at http://localhost:8506/main.js:81:27
```

@kg any hint ?

**Comment by pavelsavara** [comment]
With array size under `2146435071` it just worked!

```
            var xxx=new byte[0X7FEF_FFFF];
            Console.WriteLine ("alloc");
            xxx[0]=1;
            Console.WriteLine ("write");
            xxx[0X7FEF_FFFE]=1;
            Console.WriteLine ("write");
            Console.WriteLine($"Read {xxx[0X7FEF_FFFE]+xxx[0]}");
```

This will not solve 2GB downloads, but we have https://github.com/dotnet/runtime/issues/45954 for that.

I'm closing this as done. 

If there are specific use cases where we overflow the pointer size, please open another issue. Many thanks!

**Comment by pavelsavara** [comment]
I was also able to allocate 4 024 434 686 bytes as 2 arrays.
```
var xxx=new byte[0X7FEFFFFF];
var yyy=new byte[0X6FEFFFFF];
```

**Comment by jtorjo** [comment]
@pavelsavara 
1. Will this make it into next .net8 preview?
2. Will this be back-ported to .net7 ?

Thanks!

**Comment by pavelsavara** [comment]
I didn't do any runtime change to test this. So I guess it would already work with Net8 preview 7, I tested with main branch.

>     1. Will this make it into next .net8 preview?
Yes

>     2. Will this be back-ported to .net7 ?
No
