### ISSUE TITLE
File.ReadAllBytes* should support non-seekable files

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#58383]
As of today, `File.WriteAllBytes*` APIs support non-seekable files, but `File.ReadAllBytes*` don't.

The following call to `FileStream.Length` is going to throw:

https://github.com/dotnet/runtime/blob/d033e1a902a7ff6eb6df199733e7c26dfc811ef4/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L336

The funny thing is that we already almost support it:

https://github.com/dotnet/runtime/blob/d033e1a902a7ff6eb6df199733e7c26dfc811ef4/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L341-L348

We need:

* [ ] test that shows the broken scenario
* [ ] a fix

**Comment by lateapexearlyspeed** [comment]
Hi @adamsitnik could you please help on question: 
how to create non-seekable readable FileStream in Windows by calling path based `new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 1, FileOptions.SequentialScan)` which is used in File.ReadAllBytes() ?
I can only create non-seekable FileStream by creating namedPipe then `new FileStream(new SafeFileHandle(namedPipeServer.SafePipeHandle.DangerousGetHandle(), true), FileAccess.Read)` which is code from [test](https://github.com/dotnet/runtime/blob/2b37600804f57448bbbb1738558838d84e7889af/src/libraries/System.IO.FileSystem/tests/FileStream/FileStreamConformanceTests.Windows.cs#L30)

**Comment by adamsitnik** [comment]
@lateapexearlyspeed Appologies for the delay, I've missed GH notificaiton for your question.

You can take a look at the tests that I am trying to add in #58506 :

https://github.com/dotnet/runtime/blob/2b1510fbd40e0251204b3852572dfbcf8adec05b/src/libraries/System.IO.FileSystem/tests/RandomAccess/NonSeekable_AsyncHandles.cs#L21-L25

in your case you should be able to create a `FileStream` from given path. Sth like this:

```cs
string pipeName = FileSystemTest.GetNamedPipeServerStreamName();
string pipePath = Path.GetFullPath($@"\\.\pipe\{pipeName}");

using (var server = new NamedPipeServerStream(pipeName, PipeDirection.InOut))
using (FileStream fs = new FileStream(pipePath, FileMode.Open, access, FileShare.None, FileOptions.Asynchronous))
```

**Comment by lateapexearlyspeed** [comment]
@adamsitnik Thanks for help, test cases finished in [PR](https://github.com/dotnet/runtime/pull/58434), sync version test for `File.ReadAllBytes()` passed but async version test for `File.ReadAllBytesAsync()` failed, with [exception](https://dev.azure.com/dnceng/public/_build/results?buildId=1354487&view=ms.vss-test-web.build-test-results-tab&runId=39613038&resultId=142811&paneView=debug): 

> System.IO.IOException : The parameter is incorrect. : '\.\pipe\a0b5cd9498c54bb4a6ea30fd57edf8d8'
> at System.IO.File.InternalReadAllBytesUnknownLengthAsync(FileStream fs, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs:line 812
>    at System.IO.Tests.File_ReadWriteAllBytesAsync.ReadAllBytesAsync_NonSeekableFileStream() in /_/src/libraries/System.IO.FileSystem/tests/File/ReadWriteAllBytesAsync.cs:line 202
> --- End of stack trace from previous location ---

which can be reproduced by following call:
```
            string pipeName = FileSystemTest.GetNamedPipeServerStreamName();
            string pipePath = Path.GetFullPath($@"\\.\pipe\{pipeName}");

            var namedPipeWriterStream = new NamedPipeServerStream(pipeName, PipeDirection.Out);
            var fs = new FileStream(pipePath, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 1, FileOptions.Asynchronous | FileOptions.SequentialScan);
            await fs.ReadAsync(new byte[3].AsMemory()); // Here will throw same exception as test case throws
```
Not sure is there issue inside FileStream for async operation ?

**Comment by adamsitnik** [comment]
> Not sure is there issue inside FileStream for async operation ?

Most likely. I am going to build your fork and try to repro it locally

**Comment by adamsitnik** [comment]
It turned out that the [official docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile#parameters) were not telling the exact truth.

> For an hFile that does not support byte offsets, Offset and OffsetHigh are ignored.

I've [added](https://github.com/dotnet/runtime/pull/58434/commits/d4cf11eeb980d77a890cbdb24b45b10d08222817) an `handle.CanSeek` condition to your PR (#58434) and the tests are passing now. 

cc @stephentoub

**Comment by lateapexearlyspeed** [comment]
Hi @adamsitnik I marked [PR](https://github.com/dotnet/runtime/pull/58434) as ready for review now.
