### ISSUE TITLE
System.Drawing.Common does not display some characters.

### ISSUE THREAD

**Issue by N08I40K** [dotnet/runtime#58395]
### Description

If the repeating characters are similar to these "𝑎 𝑑 𝑧 𝑢 𝔥", then the operation of drawing text on the picture does not occur, and subsequent ones too.

```
string text = "𝑎 𝑑 𝑧 𝑢 𝔥";
using (Bitmap MainPicture = new Bitmap(1000, 500, PixelFormat.Format24bppRgb))
using (Rectangle TextRectangle1 = new Rectangle(25, 25, 950, 200))
using (Rectangle TextRectangle2 = new Rectangle(25, 250, 950, 200))
using (Graphics graph = Graphics.FromImage(MainPicture))
using (Font font = new Font("Arial", 35, FontStyle.Regular))
{
    graph.FillRectangle(Brushes.Black, FillRectangle);

    Console.WriteLine("TEXT: " + text);
    // Draw text
    graph.DrawString("\"" + text + "\"", font, Brushes.White, TextRectangle1, StringFormat.GenericTypographic);
    graph.DrawString("Normal text", font, Brushes.White, TextRectangle2, StringFormat.GenericTypographic);

    MainPicture.Save("path/to/picture.png", System.Drawing.Imaging.ImageFormat.Png);
}
```

### Configuration

I'm using .Net 4.7.
Linux (KDE neon) x64/

### Regression?

It happened initially.

### Other information

There were no exceptions.

I think this is because of the character encoding. Windows-1251.

I did not find any workarounds. Suggestions to use other fonts (like "Cambria Math"), but it didn't help.

**Comment by danmoseley** [comment]
@N08I40K hello, you mention .NET 4.7, which is .NET Framework. 
The right place for .NET Framework generally is here: https://developercommunity.visualstudio.com/search?space=61

Hmm, but you also mention Linux. Are you using .NET 5.0? This is very likely a bug in libgdiplus.

**Comment by N08I40K** [comment]
Oh sorry)
On account of gdiplus, are there any alternatives?

> @N08I40K hello, you mention .NET 4.7, which is .NET Framework.
> The right place for .NET Framework generally is here: https://developercommunity.visualstudio.com/search?space=61
> 
> Hmm, but you also mention Linux. Are you using .NET 5.0? This is very likely a bug in libgdiplus.

**Comment by danmoseley** [comment]
Yes, there are some great alternatives. Please see below. We don't recommend new development on Unix with System.Drawing as it's less stable/fully featured.  

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Does that help?

**Comment by N08I40K** [comment]
> Yes, there are some great alternatives. Please see below. We don't recommend new development on Unix with System.Drawing as it's less stable/fully featured.
> 
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only
> 
> Does that help?

Ok I'll try using something else. thanks

**Comment by N08I40K** [comment]
Should I close the topic or leave it open?

**Comment by tarekgh** [comment]
@N08I40K I am seeing you are reporting the issue on Windows too

```
I'm using .Net 4.7.
```

We'll keep this issue open to look at the problem there.

**Comment by N08I40K** [comment]
> @N08I40K I am seeing you are reporting the issue on Windows too

Wrongly put it. In the project settings, the target framework is .NET Framework 4.7.
The application compiles and runs on Linux. Mono 6.12.0.122 is used to run

**Comment by tarekgh** [comment]
Thanks for the info. I am closing this issue then.
