### ISSUE TITLE
`WindowsIdentity.RunImpersonated` method throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by InteXX** [dotnet/runtime#58407]
> The recommendation is to change the code to use `WindowsIdentity.RunImpersonated` method.
>
> _Originally posted by @jkotas in https://github.com/dotnet/runtime/issues/35389#issuecomment-619076543_

It seems worth noting that this method always throws a ` PlatformNotSupportedException` under .NET Standard 2.0.

```
/// <summary>Runs the specified action as the impersonated Windows identity. Instead of using an impersonated method call and running your function in <see cref="T:System.Security.Principal.WindowsImpersonationContext" />, you can use <see cref="M:System.Security.Principal.WindowsIdentity.RunImpersonated(Microsoft.Win32.SafeHandles.SafeAccessTokenHandle,System.Action)" /> and provide your function directly as a parameter.</summary>
/// <param name="safeAccessTokenHandle">The SafeAccessTokenHandle of the impersonated Windows identity.</param>
/// <param name="action">The System.Action to run.</param>
public static void RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
{
  throw new PlatformNotSupportedException(SR.PlatformNotSupported_Principal);
}
```
I obtained this code via Telerik's JustDecompile, run against various assemblies found in the `System.Security.Principal.Windows` package.

Am I missing something here?

**Comment by jkotas** [comment]
> new PlatformNotSupportedException(SR.PlatformNotSupported_Principal);

This is fallback implementation that is used on non-Windows. There is actual implementation in the Windows specific version of the assembly. For example, try to decompile `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.9\System.Security.Principal.Windows.dll`.

**Comment by InteXX** [comment]
Very good, thank you.
