### ISSUE TITLE
[Mono Android] GC failures on CI

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#58409]
Helix log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58391-merge-626fe575e8274f5cb8/PayloadGroup0/1/console.db111ed0.log?sv=2019-07-07&se=2021-09-19T22%3A26%3A05Z&sr=c&sp=rl&sig=PVhipPkzy8wvR5qQxB9awCQPVaZ0uABj9Rkw4u7Hpq4%3D

CI leg [Build Android x64 Release AllSubsets_Mono_RuntimeTests]: https://dev.azure.com/dnceng/public/_build/results?buildId=1329504&view=logs&j=b6f63eff-75cc-59ca-fdbf-d2121601a613&t=92df95dc-ad7c-5fec-a8b4-c8301b7a2225

Errors and stack traces:
```
      Expected: True
      Actual:   False
      Stack Trace:
           at GC_Scenarios._Resurrection_continue_continue_._Resurrection_continue_continue_sh()
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A9A008EC/w/AEC40927/uploads/Reports/GC.Scenarios/Resurrection/continue/continue.output.txt
```

```
      Expected: True
      Actual:   False
      Stack Trace:
           at GC_Features._Finalizer_finalizeother_finalizearray_finalizearray_._Finalizer_finalizeother_finalizearray_finalizearray_sh()
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A9A008EC/w/AEC40927/uploads/Reports/GC.Features/Finalizer/finalizeother/finalizearray/finalizearray.output.txt
```

**Comment by BrzVlad** [comment]
These tests just need to be disabled

**Comment by fanyang-mono** [comment]
@BrzVlad Could you please provide more details why these tests are not supposed to run on Android?

**Comment by BrzVlad** [comment]
Disabled in https://github.com/dotnet/runtime/pull/58719

**Comment by fanyang-mono** [comment]
The reason why these tests need to be disabled is because currently precise GC is not supported on mono.
