### ISSUE TITLE
WaitAsync - optimize for no timeout and non-cancellable CancellationToken

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#58401]
WaitAsync could be optimized to no-op if no timeout is provided and the CancellationToken can't be canceled.

i.e. build in this optimization:
```cs
if (cancellationToken.CanBeCanceled)
{
    return _tcs.Task.WaitAsync(cancellationToken);
}
else
{
    return _tcs.Task;
}
```

**Comment by stephentoub** [comment]
> WaitAsync could be optimized to no-op if no timeout is provided and the CancellationToken can't be canceled.

It does:
https://github.com/dotnet/runtime/blob/ad9281d4ef6441cf0ca4cf5698a19b6a9ad3b1f1/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L2754-L2757

**Comment by JamesNK** [comment]
Got it!

I looked at how it was implemented and I read this - https://github.com/dotnet/runtime/blob/66d23a791cd59f862c1c628ed1fb516362ebcd5a/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs - I didn't notice the `tests` in the path.
