### ISSUE TITLE
[6.0] No build warning from RequiredPreviewFeatures attribute?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#58419]
When 6.0 RC1 or RC2 bits, I can create a basic website with this bit of code in `Program.cs`:

```cs
using Microsoft.AspNetCore.Server.Kestrel.Core;

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel((context, options) =>
{
    options.ListenAnyIP(5001, listenOptions =>
    {
        listenOptions.UseHttps();
        listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
    });
});
var app = builder.Build();

app.MapGet("/", () => "Hello World!");
app.Run();
```

Build completes successfully. No warnings or errors:

![image](https://user-images.githubusercontent.com/303201/131437617-0923f73f-f83d-4e42-9f26-ddfd6eafaae3.png)

What I expected is a warning that my app is using an experimental feature from `HttpProtocols.Http1AndHttp2AndHttp3` and that needs to be enabled:

![image](https://user-images.githubusercontent.com/303201/131437532-70337f45-1e5c-4cb9-a0af-df5625142765.png)

**Comment by stephentoub** [comment]
cc: @pgovind, @jeffhandley

**Comment by pgovind** [comment]
The DetectPreviewFeaturesAnalyzer is still reporting Info. I need to get 1 more PR in before I can bump it up to Error. ETA is end of the week

**Comment by jeffhandley** [comment]
Since this is known and expected, I'm going to go ahead and close this issue.  This will be addressed in RC2 when we've finished the analyzer and updated it to report as Error. Thanks for reporting, nonetheless, @JamesNK!
