### ISSUE TITLE
[6.0.100-rc.1.21425.10] ControlzEx Failed to build with Nullability of reference types error when retarget to .NET 6.0 

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#58422]
**Application Name**: ControlzEx
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: 6.0.100-rc.1.21425.10

 
**Verify Scenarios:**
1) Windows 10 RS5 X64 + dotnet-sdk-5.0.401-win-x64 PASS
2) Windows 10 RS5 X64 + dotnet-sdk-6.0.100-preview.6.21322.2 PASS
3) Windows 19H1+dotnet-sdk-6.0.100-rc.1.21424.13: Fail
4) Windows 10 RS5 X64+dotnet-sdk-6.0.100-rc.1.21425.10: Fail

**App Source checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1388731 

**Repro steps**:

This is a net5 app, issue occurs when re-target it to .NET 6.0 rc1 build.

1)Copy AppSource to machine :
2) Change "net5.0-windows" to "net6.0-windows" in Directory.Build.props.
3) Run dotnet build

**Expected Result:**

No Error

**Actual Result**:

There is an error.

Error :
```
D:\ControlzExSource\src\ControlzEx\Behaviors\GlowWindowBehavior.cs(125,46): error CS8622: Nullability of reference types in type of parameter 'o' of 'void GlowWindowBehavior.AssociatedObjectOnClosing(object o, CancelEventArgs args)' doesn't match the target delegate 'CancelEventHandler' (possibly because of nullability attributes). [D:\ControlzExSource\src\ControlzEx\ControlzEx_sy4g1miv_wpftmp.csproj]
D:\ControlzExSource\src\ControlzEx\Behaviors\GlowWindowBehavior.cs(288,50): error CS8622: Nullability of reference types in type of parameter 'o' of 'void GlowWindowBehavior.AssociatedObjectOnClosing(object o, CancelEventArgs args)' doesn't match the target delegate 'CancelEventHandler' (possibly because of nullability attributes). [D:\ControlzExSource\src\ControlzEx\ControlzEx_sy4g1miv_wpftmp.csproj]
```
**Findings** :

**Exception in GlowWindowBehavior.cs(line:125)**
```
this.AssociatedObject.Closing -= this.AssociatedObjectOnClosing;

....

private void AssociatedObjectOnClosing(object o, CancelEventArgs args)
        {
            if (!args.Cancel)
            {
                this.AssociatedObject.IsVisibleChanged -= this.AssociatedObjectIsVisibleChanged;
            }
        }

delegate is given System.ComponentModel.CancelEventHandler(line:8)
public delegate void CancelEventHandler(object sender, CancelEventArgs e);

```
**If we change the parameter of AssociatedObjectOnClosing to nullable, we can successfully build.
(This change is not required for versions before 6.0.100-preview.6.21322.2 .)**

```
private void AssociatedObjectOnClosing(object? o, CancelEventArgs args)
        {
            if (!args.Cancel)
            {
                this.AssociatedObject.IsVisibleChanged -= this.AssociatedObjectIsVisibleChanged;
            }
        }
```
**This change is not required for versions before 6.0.100-preview.6.21322.2 .**

@dotnet-actwx-bot @dotnet/compat

@jeffhandley

**Comment by Junjun-zhao** [comment]
Creating this new one since WPF team looked into it and indicated that it is Runtime issue.  
https://github.com/dotnet/wpf/issues/5221

**Comment by batzen** [comment]
Would have been way easier to redirect this to ControlzEx instead of runtime.
I just fixed the code in ControlzEx.

**Comment by Junjun-zhao** [comment]
Thanks for fixing this issue. Closing it.
