### ISSUE TITLE
HttpClient headers extension

### ISSUE THREAD

**Issue by zxcvqwerasdf** [dotnet/runtime#58425]
Hi, there is any option to control the order of HttpClient headers?
Or how to add same name headers in one request? (Separate line cookies for example, instead of one line)
System.Net.Http.Headers.HttpRequestHeaders is read only and you can't control order and other header things.
Thank you.

**Comment by karelz** [comment]
@zxcvqwerasdf there is no such support to my best knowledge - definitely not for order and most likely not for same name headers.
Why do you need to control these things? Is it for pretty printing the requests? Or some other reasons?

**Comment by zxcvqwerasdf** [comment]
@karelz Because some sites don't work if you have not ordered headers in request or one line cookies instead of separate lines.

**Comment by karelz** [comment]
This is the first time we hear anything like that. Which sites are those?
Do you know which server they run?

**Comment by zxcvqwerasdf** [comment]
@karelz It's not about what server they run, it's about what data they parsing and compare between each other and if they don't same (even order) - you got kick out from session. I need make same request as my browser do, including order, lower/upper case. This is why i need to control order of headers and separate line cookies.

**Comment by karelz** [comment]
@zxcvqwerasdf understood. However, for a platform like us, it is about how common such endpoints are. If this is the only app / server playing nasty games, we will likely not expose new APIs just for them. If it is more wide-spread scenario or if there is reasonable chance it will become more wide-spread scenario, then it is different story.

One thing that may eventually help you is LLHTTP (Low-Level HTTP APIs) we are investing into. It is only early prototype now, but we hope to land it in .NET 7.0. You should be able to customize how headers are sent there, incl. order, etc. if you care ...

**Comment by ManickaP** [comment]
@zxcvqwerasdf add cookies, there shouldn't be more than one cookie header in the request, [RFC 6265](https://www.rfc-editor.org/rfc/rfc6265.html#section-5.4)

> When the user agent generates an HTTP request, the user agent MUST NOT attach more than one Cookie header field.

If you're hitting issues with cookies, aren't you by any chance hitting this: https://github.com/dotnet/runtime/issues/42856 Unfortunately, we do have a bug in concatenating them.

**Comment by zxcvqwerasdf** [comment]
@ManickaP It's allowed in HTTP/2.0
https://tools.ietf.org/html/rfc7540#section-8.1.2.5

**Comment by zxcvqwerasdf** [comment]
@karelz Thank you, i will read about LLHTTP.

**Comment by karelz** [comment]
Triage: This is way too advanced for HttpClient. LLHTTP is better option. Or if we have many more people interested, we may change our mind in Future.
