### ISSUE TITLE
[.NET 6] PriorityQueue not FIFO at same priority

### ISSUE THREAD

**Issue by died** [dotnet/runtime#58432]
### Description
Trying [PriorityQueue](https://docs.microsoft.com/en-us/dotnet/api/system.collections.queue?view=net-6.0) on .NET 6, assume the **queue should be FIFO on same priority** , but actually it was not.
The dequeue order seems very random.

![img](https://i.imgur.com/jayoumK.png)

I have test code on [dotnetfiddle](https://dotnetfiddle.net/hdXZ2B) although it can't run .NET 6.

### Configuration

* .NET 6 Preview 7.21378.6
* Win10 Build 19043 X86 64

**Comment by Sergio0694** [comment]
This is by design, [see here](https://github.com/dotnet/runtime/issues/43957):

> "Not a stable queue (elements enqueued with equal priority not guaranteed to be dequeued in the same order)."

**Comment by hez2010** [comment]
PriorityQueue doesn't imply FIFO, this is by design. To simulate FIFO behavior, you can add a second priority index for it:

```csharp
ulong id = 0;

var q = new PriorityQueue<int, (Priority Priority, ulong Index)>();
q.Enqueue(1, (Priority.Low, Interlocked.Increment(ref id)));
q.Enqueue(2, (Priority.Low, Interlocked.Increment(ref id)));
q.Enqueue(3, (Priority.High, Interlocked.Increment(ref id)));
q.Enqueue(4, (Priority.Medium, Interlocked.Increment(ref id)));
q.Enqueue(5, (Priority.High, Interlocked.Increment(ref id)));
q.Enqueue(6, (Priority.Low, Interlocked.Increment(ref id)));
q.Enqueue(7, (Priority.High, Interlocked.Increment(ref id)));
q.Enqueue(8, (Priority.Low, Interlocked.Increment(ref id)));
q.Enqueue(9, (Priority.High, Interlocked.Increment(ref id)));
q.Enqueue(10, (Priority.Medium, Interlocked.Increment(ref id)));
q.Enqueue(11, (Priority.Medium, Interlocked.Increment(ref id)));

while (q.TryDequeue(out var elem, out var priority))
{
    Console.WriteLine($"{elem}, priority = {priority}");
}

enum Priority { Low, Medium, High }
```

**Comment by died** [comment]
> This is by design, [see here](https://github.com/dotnet/runtime/issues/43957):
> 
> > "Not a stable queue (elements enqueued with equal priority not guaranteed to be dequeued in the same order)."

Yea, but if it not FIFO, it should not called "Queue", maybe rename to PriorityHash will be more sense.

**Comment by hez2010** [comment]
See previous discussions in #43957.

**Comment by died** [comment]
Although the author don't think so, I still agree with many other said "[PriorityQueue is wrong naming](https://github.com/dotnet/runtime/issues/43957#issuecomment-804024166)".
