### ISSUE TITLE
[Libraries][iOS/MacCatalyst/tvOS] IsIanaIdTest fails from mismatched expectation

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#58440]
<s>In https://github.com/dotnet/runtime/pull/57732, several TimeZoneInfoTests were tweaked to pass on iOS/MacCatalyst/tvOS. At the time, when running tests, `America/Buenos_Aires` was no recognized as an IanaID on iOS/MacCatalyst/tvOS, so that value was used instead of `Pacific Standard Time` which throws TimeZoneNotFound ahead of returning false for IsIanaId.

I'm not certain what is supposed to be a TimeZoneId and not IanaId on iOS/MacCatalyst/tvOS yet, and I'm not sure exactly what had changed between that change and the latest run on https://github.com/dotnet/runtime/pull/57208 to cause it to no longer *not* be an IanaId.

The fix should simply be finding a known TimeZoneId on iOS/MacCatalyst/tvOS that is and will not be recognized as an IanaId. </s>

-----

From another glance with https://github.com/dotnet/runtime/issues/58440#issuecomment-910460096, it appears that the failure is directly from this addition to the test https://github.com/dotnet/runtime/blob/faafb3294d24b7a0f14c9b11a4058bf5f6088d4c/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs#L2667

The newest check fails on iOS/MacCatalyst/tvOS as the `TimeZoneInfo.Local.Id` is `America/New_York`. The check expects for the `TimeZoneInfo.Local.Id` to be an `Iana Id` if the platform is **NOT** windows or if the Id is **NOT** UTC. It seems as though `America/New_York` is evaluated as not being an Iana Id.

**Comment by tarekgh** [comment]
@mdh1418 we had a bug which we have recently fixed it https://github.com/dotnet/runtime/issues/58326. could be this is the reason?

**Comment by mdh1418** [comment]
@tarekgh Ah it does look like the culprit instead of my original suspicion. It looks like on iOS/tvOS/MacCatalyst the `TimeZoneInfo.Local.Id` is `America/New_York` (atleast on my local machine), and so that is evaluated as having an Iana Id

**Comment by mdh1418** [comment]
Right, the problem is the test itself, I'm thinking the right action would be to extend 
`expected || TimeZoneInfo.Local.Id.Equals("Utc", StringComparison.OrdinalIgnoreCase)` 
to 
`expected || PlatformDetection.IsiOS || PlatformDetection.IstvOS || TimeZoneInfo.Local.Id.Equals("Utc", StringComparison.OrdinalIgnoreCase)`

**Comment by tarekgh** [comment]
I am not sure why you need to add these extra conditions? Could you tell in detail what are the TZ Ids which fail on iOS or tvOS?

**Comment by mdh1418** [comment]
@tarekgh  I updated the description since my first glance/assumption was incorrect. 
> Could you tell in detail what are the TZ Ids which fail on iOS or tvOS?

The only failure seems to be that `iOS/MacCatalyst/tvOS` has a `TimeZoneInfo.Local.Id` that is an Iana Id that is not UTC.
To me it seems like its a problem with the check specifically for iOS/MacCatalyst/tvOS.
