### ISSUE TITLE
[API Proposal]: Add System.Guid support to StringBuilder

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#58458]
### Background and motivation

When build a `string` that uses a `Guid` in its composition, even when using a `StringBuilder` it is required to create a temporary `string` representation of the `Guid`.

### API Proposal

```C#
namespace System.Text
{
     public sealed partial class StringBuilder : ISerializable
     {
          public StringBuilder Append(Guid value) => AppendSpanFormattable(value);
     }
}
```     

### API Usage

```C#
var sb = new StringBuilder();
sb.Append(Guid.NewGuid());
```

**Comment by GrabYourPitchforks** [comment]
@stephentoub Now that `ISpanFormattable` is public, wouldn't implementing the API at https://github.com/dotnet/runtime/issues/32380 solve this problem once and for all? StringBuilder's interpolated string builder already supports this IIRC, so `StringBuilder.Append($"{Guid.NewGuid()}")` should be temporary-allocation-free.

**Comment by tannergooding** [comment]
Now that `ISpanFormattable` is public, perhaps we should just make `StringBuilder AppendSpanFormattable<T>(T value) where T : ISpanFormattable` public.

That would allow efficient specialization for any value type, not just `Guid`. CC. @stephentoub

**Comment by tannergooding** [comment]
Seems @GrabYourPitchforks and I had the same idea here 😄

**Comment by stephentoub** [comment]
> Now that ISpanFormattable is public, perhaps we should just make StringBuilder AppendSpanFormattable<T>(T value) where T : ISpanFormattable public.

We could debate whether to constraint it vs allowing any T and doing an interface check.  But, sure, I'd be fine with another Append(T) overload here.

**Comment by paulomorgado** [comment]
@stephentoub, @tannergooding, @GrabYourPitchforks, like this? #58458

**Comment by GrabYourPitchforks** [comment]
@paulomorgado Sounds about right, yeah. Like Tanner alluded to and Steve said explicitly, maybe the new `Append` overload gets a generic constraint tacked on to it, but we can let the architects go down that rabbit hole.

**Comment by stephentoub** [comment]
Closing in favor of https://github.com/dotnet/runtime/issues/58459.
