### ISSUE TITLE
Runtime fails to source build - libSystem.IO.Ports.Native.so.dbg not found

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#58455]
The runtime repo is failing to source build.

`./build.sh -c Release --restore --build --pack /p:ArcadeBuildFromSource=true -bl`

/repos/runtime/.dotnet/sdk/6.0.100-rc.1.21411.28/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file '/repos/runtime/artifacts/source-build/self/src/artifacts/bin/native/net6.0-Linux-Release-x64/libSystem.IO.Ports.Native.so.dbg' to be packed was not found on disk. [/repos/runtime/artifacts/source-build/self/src/src/libraries/System.IO.Ports/pkg/runtime.linux-x64.runtime.native.System.IO.Ports.proj]

I noticed the `runtime.linux-x64.runtime.native.System.IO.Ports.proj` project was recently changed to ` <IsPackable>true</IsPackable>` with https://github.com/dotnet/runtime/commit/85441ce69b81dfd5bf57b9d00ba525440b7bb25d.

Note: this should be caught at the repo level once https://github.com/dotnet/runtime/issues/54573 is implemented.

**Comment by MichaelSimons** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
> The file '/repos/runtime/artifacts/source-build/self/src/artifacts/bin/native/net6.0-Linux-Release-x64/libSystem.IO.Ports.Native.so.dbg' to be packed was not found on disk

Are native assets and/or symbols not built during source build?

Do you have a binlog or can you post what `ls -la /repos/runtime/artifacts/source-build/self/src/artifacts/bin/native/net6.0-Linux-Release-x64/` prints? Would like to understand why the native symbol file is missing.

**Comment by MichaelSimons** [comment]
I apologize, I intended to include a binlog.  Here is a link to one (Microsoft internal link) - https://devdiv.visualstudio.com/DefaultCollection/Personal/_git/msimons?path=%2Fissue-notes%2Fruntime.issue-58455.sourcebuild.binlog

Native assets are built.  For example '/repos/runtime/artifacts/source-build/self/src/artifacts/bin/native/net6.0-Linux-Release-x64/libSystem.IO.Ports.Native.so' is produced by the build.  I'm not seeing symbols.  @dseefeld, @crummel - Should source-build be producing symbols?

**Comment by ViktorHofer** [comment]
cc @dseefeld @crummel. This sounds like sourcebuild isn't producing the expected symbols. As we aren't hitting this in normal CI builds I would imagine there's an unexpected difference in behavior when building from source.

**Comment by MichaelSimons** [comment]
Source build is setting `keepNativeSymbols=true` [here](https://github.com/dotnet/runtime/blob/release/6.0/eng/SourceBuild.props#L47).  This setting prevents the symbols from being stripped out and placed into a separate .dbg file.  [Here ](https://github.com/dotnet/source-build/pull/1776/files#diff-3cc321025ad7a47e73d552f56eba06e9fb93de57daff50548b9c5e3a98febdad)is some context on this behavior.  When I build source-build without this setting the build error does not occur.

To support this, should this pack code be modified to respect the `keepNativeSymbols` setting and skip packing symbols?

**Comment by ViktorHofer** [comment]
Got it. So in that case, you want to modify this line to only apply if `$(keepNativeSymbols)` isn't true: https://github.com/dotnet/runtime/blob/9bdd29220a8e3a806a3657b78775a443d1a6d8c1/src/libraries/System.IO.Ports/pkg/runtime.native.System.IO.Ports.props#L11.

**Comment by ViktorHofer** [comment]
Do you want to submit a fix or should I?

**Comment by MichaelSimons** [comment]
I just finished testing the fix and will submit a PR.  Thanks for the help on this @ViktorHofer!

**Comment by ViktorHofer** [comment]
Fixed with https://github.com/dotnet/runtime/commit/b8b42ba93092225381424fa09180b65f4c91def3
