### ISSUE TITLE
StringBuilder.Insert() overload to insert a character any number of times

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#58461]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StringBuilderInsert-overload-to-inser/1496985)._

---
I think you should add another `StringBuilder.Insert()` overload.

It would look like this:

StringBuilder StringBuilder.Insert(int index, char value, char count);

Currently, the closest method inserts any number of strings. But if I want to insert multiple copies of a `char`, a method like this could potentially be more performant.

---
#### Feedback Bot on 8/8/2021, 10:57 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by danmoseley** [comment]
We already have a method to insert a string, a char[], or a ReadOnlySpan<char>. I do not think it is so common to want to insert the same character several times and in such a hot path that it would be much better to have such a method.

**Comment by SoftCircuits** [comment]
> We already have a method to insert a string, a char[], or a ReadOnlySpan. I do not think it is so common to want to insert the same character several times and in such a hot path that it would be much better to have such a method.

Neither string, char[] or ReadOnlySpan is the same as inserting multiple copies of the same character. This can be accomplished in C# code, but better performance should be possible if implemented in the frameworks.

**Comment by danmoseley** [comment]
It probably would be faster, the question is whether this is common enough scenario in performance critical code to be worth an API.
