### ISSUE TITLE
Should not `IAsyncEnumerable` inherit from (implement) `IEnumerable`?

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#58476]
The question is self-explicative.
This is an opinion and a "learning question" and maybe could be wrong (of course is wrong) by so many things I can't see.

At the end something that **_can be enumerated_** asynchronously is something that **_can be enumerated_**.
The same way something generic that **_can be enumerated_** is something that simply **_can be enumerated_** (non generic `IEnumerable`).

The only point is that `IEnumerable` will have to block until he retrieves the next element to return and `IAsyncEnumerable` can be awaited.

What am I missing? Is some design decision? Are there downsides if this were the way I'm talking?

**Comment by stephentoub** [comment]
Making IAsyncEnumerable inherit IEnumerable means anyone that wants to expose the asynchronous functionality is also forced to expose the synchronous functionality.  Typically these components are I/O-based, and so such a requirement then forces inherently asynchronous and scalable operations to expose non-scalable synchronous counterparts.  Moreover, it makes it difficult to do so well even if doing so well is possible, e.g. if you write an async iterator in C# like:
```C#
public static IAsyncEnumerable<int> Filter(ChannelReader<int> reader, Func<int, bool> predicate)
{
    await foreach (int item in reader.ReadAllAsync())
        if (predicate(item))
            yield return item;
}
```
how is the compiler supposed to create a good implementation of `IEnumerable<T>`?  It would have to either emit that implementation as doing sync-over-async, having MoveNext call MoveNextAsync and then block waiting for it to complete, which we actively discourage as an anti-pattern and bad practice, or somehow figure out how to come up with a synchronous counterpart to all composed async operations, which isn't possible in many situations (like in my example above, where there's no synchronous counterpart to ReadAllAsync).

**Comment by DrkWzrd** [comment]
@stephentoub Thank you for the answer
