### ISSUE TITLE
[HTTP/2] Send RST_STREAM instead EOF if request has Content-Length, but body is not sent

### ISSUE THREAD

**Issue by alnikola** [dotnet/runtime#58498]
In Except 100-Continue scenario, there seems to be an issue with how `Http2Stream` handles non-successful response codes  from the server while waiting for `100-Continue` response to start sending the request body.

Currently, if `Http2Stream` receives >300 response code while waiting for `100-Contiue`, it [signals](https://github.com/dotnet/runtime/blob/c156ebe0f7be4a81584336d3a152aabad791db25/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L618) the request thread [waiting inside SendRequestBodyAsync](https://github.com/dotnet/runtime/blob/c156ebe0f7be4a81584336d3a152aabad791db25/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L191) to not send the request body by returning `false` from `WaitFor100ContinueAsync`. Further, it [sends EndOfStream](https://github.com/dotnet/runtime/blob/c156ebe0f7be4a81584336d3a152aabad791db25/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L288) to the server to signal that it shouldn't expect any body. Upon EOF receival, the server is expected to just stop waiting for request body. However, it has been discovered that actually it doesn't work this way if the request has Content-Length header.

If Content-Length is set on a request, then server expect that either the full body to be sent from the client or to get a RST_STREAM with CANCEL code. Since the client currently sends EOF, the server treats this as protocol violation and responds by sending RST_STREAM with PROTOCOL_ERROR code. The client reacts to this code by terminating response even if it's a stream being read by some code on the client side.

This PR sends RST_STREAM with CANCEL if the request has Content-Length, but the body has not been sent.

**Comment by geoffkizer** [comment]
I think we should send RST_STREAM with CANCEL in all cases here, meaning regardless of whether the request has a Content-Length or not. That's simpler (no need to check for Content-Length) and seems more correct, in that it will signal to the server that we cancelled the request body send instead of completing it successfully.

**Comment by alnikola** [comment]
@geoffkizer I implemented the fix following you suggestion. Please, check the linked PR.

**Comment by karelz** [comment]
Triage: Exists for 2 release, nobody complained so far -> not critical for 6.0.
