### ISSUE TITLE
[dotnet-dump] dumpobj fails for a stack object from a coredump

### ISSUE THREAD

**Issue by clguiman** [dotnet/runtime#58517]
[dump-focal-5.0.8-focal-Release.dmp.zip](https://github.com/dotnet/runtime/files/7093214/dump-focal-5.0.8-focal-Release.dmp.zip)
### Description
Running the following commands with the attached coredump (5.0.8 focal) will fail to inspect the stack object:

`
setthread 19
clrstack -i -a 2
Loaded C:\Users\clguiman\AppData\Local\Temp\SymbolCache\mscordbi.dll/elf-buildid-coreclr-9e417e6f356c686f80c90cb2dc76593a0f2d7cae/mscordbi.dll
Loaded C:\Users\clguiman\AppData\Local\Temp\SymbolCache\mscordaccore.dll/elf-buildid-coreclr-9e417e6f356c686f80c90cb2dc76593a0f2d7cae/mscordaccore.dll

Dumping managed stack and managed variables using ICorDebug.
=============================================================================
Child SP         IP               Call Site
00007F6940BFDDC0 00007f69bbcc5aff [NativeStackFrame]
00007F6940BFE640 00007f6941e917fc 00007F6940BFE650 (null) [Managed to Unmanaged transition: 00007F6940BFE650]
00007F6940BFE6D0 00007f694202dd10 [DEFAULT] ValueClass System.Net.Sockets.SocketError System.Net.Sockets.SocketPal.SelectViaPoll(Class System.Collections.IList,I4,Class System.Collections.IList,I4,Class System.Collections.IList,I4,Ptr ValueClass PollEvent,I4,I4) (/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.Net.Sockets.dll)

PARAMETERS:
  + System.Net.Sockets.Socket[] checkRead   (2 elements)
  + int checkReadInitialCount  = 2
  + System.Collections.IList checkWrite = null
  + int checkWriteInitialCount  = 0
  + System.Collections.IList checkError = null
  + int checkErrorInitialCount  = 0
  **+ Interop+PollEvent* events @ 0x7f6940bfe760**
  + (Error 0x80131304 retrieving parameter 'eventsLength')
  + (Error 0x80131304 retrieving parameter 'microseconds')
...
Stack walk complete.
====

**do 0x7f6940bfe760**
<Note: this object has an invalid CLASS field>
Invalid object
`

The coredump contains the full heap and dotnet-dump should be able to inspect the object at address 0x7f6940bfe760

**Comment by tommcdon** [comment]
@mikem8361 @hoyosjs

**Comment by mikem8361** [comment]
The reason do may not be working is that that variable `Interop+PollEvent* events @ 0x7f6940bfe760` is a pointer and could be an interior pointer in the middle of an object which the do command can't handle.

**Comment by delmyers** [comment]
@mikem8361 It is unclear what feedback it is that you are looking for from Claudiu.

**Comment by mikem8361** [comment]
I guess the feedback is to confirm before I close this issue that he agrees that `Interop+PollEvent* events @ 0x7f6940bfe760` is a pointer or an interior pointer and not an object.  The `do` command won't work in those cases.

**Comment by clguiman** [comment]
Sorry for not replying to the original comment, I missed the notification.
Is there some way to inspect the dereferenced pointer using the ICorDebug APIs? I was under the impression `do` is using `ICorDebugReferenceValue::Dereference`

**Comment by mikem8361** [comment]
The `do` command uses low level DAC APIs like ISOSDacInterface::GetObjectData() to validate and return the details of the object. The `clrstack -i` is pretty much the only SOS command that uses the ICorDebug API and it looks like it does use ICorDebugReferenceValue::Dereference to dereference the function parameters and other ICorDebug APIs to display the value. 

I looked at it a little more and `events` is a pointer to a value type so `DumpObj` isn't going to work. SOS does have the `DumpVC` which dumps value types but it requires the method table address.  It is easy to get the MT address for VT's in an object (DumpObj has a MT column) but `clrstack -i` doesn't display it for parameters or locals.

**Comment by mikem8361** [comment]
@clguiman are you ok with closing this issue now?

**Comment by delmyers** [comment]
If I understand the bug correctly, it looks like there is still a problem. Claudiu is not able to enumerate the parameters on the stack.

**Comment by mikem8361** [comment]
Can not enumerate parameters using SOS or the ICorDebug APIs?  The title/main comment is about SOS problems dumping a value type parameter. There is really nothing we can do in SOS (there is no ICorDebug API to get a ICorDebugValue's method table address to use with the !DumpVC command).  If the he is having problems with the appropriate ICorDebug to query info about this value type, then either the title should change or a new issue detailing the ICorDebug* API that fails.

**Comment by clguiman** [comment]
I originally ran into the issue while using the ICorDebug APIs, but I wasn't aware pointers to value types are a special case. I assumed SOS had the same issue, that's why I opened the bug with an SOS repro.
I will investigate and see if I can inspect the object using your proposal and create a new bug if I fail.
