### ISSUE TITLE
Mono MacCatalyst AOT offsets leg failing in official buidls

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#58563]
From the log that was sent via mail:

Unfortunately the log in AzDO doesn't print any output for me.

```
2 error(s), 0 warning(s)
--
  | nodename nor servname provided, or not known
  | nodename nor servname provided, or not known
```

Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1334959&view=results

**Comment by ViktorHofer** [comment]
@directhex are you able to access the log actually? I don't get anything from AzDO returned.

**Comment by directhex** [comment]
I get the status of the steps (i.e. build was green, upload was red), no actual text output.

**Comment by ViktorHofer** [comment]
@dotnet/dnceng can you please take a look? Is there a way to retrieve the console log?

**Comment by ViktorHofer** [comment]
Ah cool 😄 thanks Ricardo.

`2021-09-01T18:21:45.7266830Z ##[error]nodename nor servname provided, or not known`

@dotnet/dnceng is that a DNS issue?

**Comment by MattGal** [comment]
> Ah cool 😄 thanks Ricardo.
> 
> `2021-09-01T18:21:45.7266830Z ##[error]nodename nor servname provided, or not known`
> 
> @dotnet/dnceng is that a DNS issue?

Indeed, but of code we don't control that's in the [azure-pipelines-agent repo](https://github.com/microsoft/azure-pipelines-agent/blob/master/src/Agent.Plugins/PipelineArtifact/PipelineArtifactPlugin.cs).  I'll look around to see if they have anything on the backlog about retry and make sure they do.

**Comment by ViktorHofer** [comment]
Presumably that's another case where an exponential retry mechanism would've made sense :)

Thanks Matt for taking a look. Presumably there's nothing we can do apart from escalating which doesn't feel right unless this starts to be come a pattern. Closing...
