### ISSUE TITLE
In .NET 6, Preview 7, having a property name with space and using JsonSourceGenerationOptions causes errors in generated files 

### ISSUE THREAD

**Issue by rajasekarshanmugam** [dotnet/runtime#58580]
Was trying to move a legacy integration system - unfortunately the specific JSON has a space in the property name.Equivalent property has been decorated using JsonPropertyName attribute. However when trying to move to using the new source generator, there are errors in the generated code files.

For e.g. to reproduce the error, include the below snippet in a new .NET 6 console app.

	[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
	[JsonSerializable(typeof(Book))]
	internal partial class BookContext : JsonSerializerContext
	{
	}

	public class Book
	{
		[JsonPropertyName("title name")]
		public string TitleName { get; set; }
	}

Compilation will throw below errors or an equivalent (have edited the long file paths)

1>\TestJSONPerformance\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\BookContext.Book.g.cs(69,38,69,50): error CS0103: The name 'namePropName' does not exist in the current context
1>\TestJSONPerformance\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\BookContext.PropertyNames.g.cs(8,65,8,70): warning CS0649: Field 'BookContext.title' is never assigned to, and will always have its default value
1>Done building project "TestJSONPerformance.csproj" -- FAILED.

Checked the documentation to see if properties with legal special characters or spaces allowed, could not any references. No issues/errors were found on search too.

### Configuration
- .NET 6, Preview 7
- Win10 21h1
- x64
- error happens only if json source generator is enabled, workaround is to move back using default serialization without source generation.

**Comment by eiriktsarpalis** [comment]
Hi @rajasekarshanmugam, using the following console app
```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

Console.WriteLine(JsonSerializer.Serialize(new Book { TitleName = "name" }, MyJsonContext.Default.Book));

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Book))]
internal partial class MyJsonContext : JsonSerializerContext
{
}

public class Book
{
    [JsonPropertyName("title name")]
    public string? TitleName { get; set; }
}
```
compiles and runs as expected using dotnet sdk version 6.0.100-rc.2.21452.10. Does the issue still reproduce for you if you use [a newer sdk version](https://github.com/dotnet/installer#installers-and-binaries)?

**Comment by rajasekarshanmugam** [comment]
Thank you for the quick note. I don't think I am using the newer version of the SDK. Will try a new version/nightly and revert back.

**Comment by rajasekarshanmugam** [comment]
@eiriktsarpalis - Tried with version - 6.0.100-rc.1.21453.34. Above sample works fine with no errors.

However, on trying another scenario in a larger application, getting some errors. I am trying to isolate into a smaller scenario and would post back if one is available. Possibly something wrong with the JsonSerializationContext context.

Exception is below (edited file paths as they were super long).

Unhandled exception. System.InvalidOperationException: Metadata for type 'System.String' was not provided to the serializer. The serializer method used does not support reflection-based creation of serialization-related type metadata. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NoMetadataForType(Type type)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerContext context, Type type)
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerContext context)
   at JsonDeserialization.DeserializeUsingContext() in \TestJSONPerformance\Program.Steps.cs:line 122
   at Program.<Main>$(String[] args) in \TestJSONPerformance\Program.Steps.cs:line 10

Is there a way to look into generated sources using a property in csproj?

**Comment by eiriktsarpalis** [comment]
> Is there a way to look into generated sources using a property in csproj?

Yes, hitting F12 on your `JsonSerializerContext` class should reveal the generated source files in the IDE.

> However, on trying another scenario in a larger application, getting some errors. I am trying to isolate into a smaller scenario and would post back if one is available. Possibly something wrong with the JsonSerializationContext context.

Isolating into a reproducing app would help tracking down the issue. Would it be possible to create a separate issue when you do? I'm going to close this one for now. Thanks.

**Comment by rajasekarshanmugam** [comment]
@eiriktsarpalis - absolutely, will try to get a reproducing app and open a new ticket.
