### ISSUE TITLE
Support variance in IDynamicInterfaceCastable

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#58619]
We might be able to allow interfaces that are compatible through variance to be returned from Getinterfaceimplementation.

**Comment by AaronRobinsonMSFT** [comment]
I believe the first attempt here will be updating the following to use `IsAssignableTo`.

https://github.com/dotnet/runtime/blob/918e6a9a278bc66fb191c43d4db4a71e63ffad31/src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/DynamicInterfaceCastableHelpers.cs#L37-L38

There is likely other fallout here and we need to think about how IDIC works with variance in general.
