### ISSUE TITLE
System.Runtime.CompilerServices - Undoc 6.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#58657]
The following APIs were introduced in 6.0 and did not get documented in triple slash. They will need to be manually documented directly in dotnet-api-docs, and must target the net6-rc1 branch. This needs to be done before Tuesday September 14th so we have enough time to generate the IntelliSense package that will be shipped to GA.

| Undoc APIs                                                                                                                                                                                                       |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [M:System.Runtime.CompilerServices.CreateNewOnMetadataUpdateAttribute.#ctor](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/CreateNewOnMetadataUpdateAttribute.xml) |
| [M:System.Runtime.CompilerServices.Unsafe.Add\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                                   |
| [M:System.Runtime.CompilerServices.Unsafe.AddByteOffset\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                         |
| [M:System.Runtime.CompilerServices.Unsafe.IsNullRef\`\`1(\`\`0@)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                                            |
| [M:System.Runtime.CompilerServices.Unsafe.NullRef\`\`1](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                                                    |
| [M:System.Runtime.CompilerServices.Unsafe.Subtract\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                              |
| [M:System.Runtime.CompilerServices.Unsafe.SubtractByteOffset\`\`1(\`\`0@,System.UIntPtr)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Runtime.CompilerServices/Unsafe.xml)                    |

**Comment by joperezr** [comment]
Created PR https://github.com/dotnet/dotnet-api-docs/pull/7130 to fix this. Note that all Unsafe APIs where actually already documented so I left those intact and only documented the missing contructor
