### ISSUE TITLE
Different number decimal separators for the culture fr-CH in different environments

### ISSUE THREAD

**Issue by hhao01-becls** [dotnet/runtime#58650]
### Description

I find a weird thing, and I'm not sure this is a bug or not.
Our code needs to convert the number from string to double for different culture. But when we handle the culture **fr-CH**, we find the inconsistent behavior between local development environment (Win10 x64, VS 2019 with .NET Core 5.0.400) and Azure App Service environment (Windows x64, .NET Core 5.0.204).

You can find the example code below.
```
using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine(CultureInfo.GetCultureInfo("fr-CH").NumberFormat.NumberDecimalSeparator);
		Console.WriteLine(new CultureInfo("fr-CH", false).NumberFormat.NumberDecimalSeparator);
		
		var isTypeValid = double.TryParse("12,3", NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint, CultureInfo.GetCultureInfo("fr-CH"), out var doubleValue);
		Console.WriteLine("isTypeValid:" + isTypeValid);
		Console.WriteLine("doubleValue:" + doubleValue);

	}
}
```
For the local development environment, the output is 
```
,
,
isTypeValid:True
doubleValue:12.3
```
For the Azure App Service environment, the output is 
```
.
.
isTypeValid:False
doubleValue:0

```

In order to check which is correct, I also use other websites to verify the output.
For https://try.dot.net/, the output is 
```
.
.
isTypeValid:False
doubleValue:0
```

For https://dotnetfiddle.net/, the output is
```
,
,
isTypeValid:True
doubleValue:12.3
```

The question is which output is correct? Thanks.

**Comment by tannergooding** [comment]
@GrabYourPitchforks, @tarekgh. Are you familiar with any localization gotchas in this area?

We simply use `info.NumberDecimalSeparator` (https://source.dot.net/#System.Private.CoreLib/Number.Parsing.cs,b3578775a3c73d2e,references) when parsing the string and based on the above, it should work as expected.

**Comment by hhao01-becls** [comment]
We also find a similar issue #37743 related to this culture.

**Comment by tarekgh** [comment]
@hhao01-becls 

When running on `Azure App Service environment (Windows x64, .NET Core 5.0.204).` what version of Windows used there? 

To clarify why I am asking this question, .NET 5.0 uses ICU library for the globalization support. On Windows 10 ICU library is part of the OS. On previous versions of Windows (and some Windows Server SKUs), ICU is not installed there, and we will fall back to use the native Windows NLS APIs instead which can give different results. You can opt-in using ICU on such platforms which not having ICU by adding the following to your csproj:

```Xml
  <ItemGroup>
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  </ItemGroup>
```

Please let's know if this help or you have any more questions.

**Comment by hhao01-becls** [comment]
@tarekgh Thanks. Your answer resolved my question. It looks like the Azure App Service uses Windows Server as the operation system. According to [.NET globalization and ICU](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu), I tried the **App-local ICU** method, and it works.
