### ISSUE TITLE
System.Drawing - Undoc 6.0 APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#58653]
The following APIs were introduced in 6.0 and did not get documented in triple slash. They will need to be manually documented directly in dotnet-api-docs, and must target the net6-rc1 branch. This needs to be done before Tuesday September 14th so we have enough time to generate the IntelliSense package that will be shipped to GA.

| Undoc APIs                                                                                                                                                                              |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [M:System.Drawing.PointF.#ctor(System.Numerics.Vector2)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/PointF.xml)                                         |
| [M:System.Drawing.PointF.op_Explicit(System.Drawing.PointF)~System.Numerics.Vector2](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/PointF.xml)             |
| [M:System.Drawing.PointF.op_Explicit(System.Numerics.Vector2)~System.Drawing.PointF](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/PointF.xml)             |
| [M:System.Drawing.PointF.ToVector2](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/PointF.xml)                                                              |
| [M:System.Drawing.RectangleF.#ctor(System.Numerics.Vector4)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/RectangleF.xml)                                 |
| [M:System.Drawing.RectangleF.op_Explicit(System.Numerics.Vector4)~System.Drawing.RectangleF](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/RectangleF.xml) |
| [M:System.Drawing.RectangleF.op_Explicit(System.Drawing.RectangleF)~System.Numerics.Vector4](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/RectangleF.xml) |
| [M:System.Drawing.RectangleF.ToVector4](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/RectangleF.xml)                                                      |
| [M:System.Drawing.SizeF.#ctor(System.Numerics.Vector2)](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/SizeF.xml)                                           |
| [M:System.Drawing.SizeF.op_Explicit(System.Numerics.Vector2)~System.Drawing.SizeF](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/SizeF.xml)                |
| [M:System.Drawing.SizeF.op_Explicit(System.Drawing.SizeF)~System.Numerics.Vector2](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/SizeF.xml)                |
| [M:System.Drawing.SizeF.ToVector2](https://github.com/dotnet/dotnet-api-docs/blob/net6-rc1/xml/System.Drawing/SizeF.xml)                                                                |

**Comment by carlossanlop** [comment]
Friendly reminder that today is the last day to submit these missing docs to the net6-rc1 branch of dotnet-api-docs.

**Comment by ericstj** [comment]
These all appear to have been added with https://github.com/dotnet/runtime/commit/664e232c51a5223ca41a6db5a02e824815c483ec cc @JeremyKuhne

That change included triple-slash docs, but apparently not all the fields that were required.  @JeremyKuhne can you look at filling in those missing doc fields.  They should be the ones listed as "To be added" in the files that @carlossanlop links above.

**Comment by maryamariyan** [comment]
@carlossanlop I believe this can now be closed right?

**Comment by safern** [comment]
Thanks @maryamariyan for taking care of this.
