### ISSUE TITLE
Determine from Host  when HostedServices have completed / stopped working

### ISSUE THREAD

**Issue by fgheysels** [dotnet/runtime#58675]
When creating a `Host` that has one or more registered `HostedServices`, it would be nice if you can get somehow informed when all those HostedServices have stopped running.  
This would be usefull to be able to gracefully shutdown an application.

Suppose I have an application that has 2 hosted services:

```csharp
var host = 
    Host.CreateDefaultBuilder(args)
        .ConfigureServices(services =>
        {
            services.AddHostedService<Worker1>();
            services.AddHostedService<Worker2>();                   
        })
        .UseConsoleLifetime()
        .Build();
        
await host.RunAsync(cts.Token);
```

When the application is stopped by sending a termination signal (CTRL+C), the `StopAsync` method of the hostedservices will be called, and hence, we can gracefully stop those services.   However, depending on what the services do, stopping those services might take some time.
Therefore, it would be good if we can give the application (host) some time to make sure that all hosted services are stopped before the application itself stops.

For instance by adding an additional awaitable method which returns a completed task when all registered hosted services have completed:

```csharp
var host = ....

await host.RunAsync(cts.Token);
await host.WaitForHostedServices();
```

**Comment by fgheysels** [comment]
I did some testing, but it seems that the task that is returned by `RunAsync` only completes when all hostedservices have completed as well.

**Comment by fgheysels** [comment]
The strange thing though is that, if I have this code in my `BackgroundService` which is called from a console application:

(code for demo purposes)
```csharp
public class Worker : BackgroundService
{        
    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (stoppingToken.IsCancellationRequested == false)
        {
            Console.WriteLine("working");
            await Task.Delay(TimeSpan.FromMilliseconds(2000), stoppingToken);
        }

        Console.WriteLine("Worker stopped executing");
    }

   public override async Task StopAsync(CancellationToken cancellationToken)
   {
        Console.WriteLine("Stop called for worker");
        await base.StopAsync(cancellationToken);
   }
}
```
When I press CTRL+C, the application is stopping.   I can see from the output that `StopAsync` for the worker is called, but the code after the `while` loop in the `ExecuteAsync` method is never executed.  
In the example above, I don't see the line 'Worker stopped executing' being outputed to the console.  When inspecting the source code of the `BackgroundService`class, the [StopAsync](https://github.com/dotnet/runtime/blob/7d54e21f0a846f504a621c4f7ebe0b8cdd13ad81/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L60) method makes sure that the cancellationToken that is used in the `ExecuteAsync` method is signalled.   In the `ExecuteAsync` method , I'm checking if the CancellationToken is canceled or not.  Once it is, we should exit the while loop, and I would expect that the code after that while loop is also executed, but this doesn't seem to be the case ?

**Comment by eerhardt** [comment]
@fgheysels - regarding the top comment - 

> but it seems that the task that is returned by RunAsync only completes when all hostedservices have completed as well.

This is correct. The task returned by RunAsync waits for all the hosted services to have run, and stopped, before returning. We can update the docs to make this explicit.

> When I press CTRL+C, the application is stopping. I can see from the output that StopAsync for the worker is called, but the code after the while loop in the ExecuteAsync method is never executed.

The reason this happens is because the `stoppingToken` is being stopped while your method is inside `Task.Delay`. When this happens, `Task.Delay` throws a `TaskCanceledException`. Which means your `ExecuteAsync` doesn't finish executing - because an uncaught exception occurred. Thus, `Console.WriteLine("Worker stopped executing");` is never executed.
