### ISSUE TITLE
[API Proposal]: string.Create Span overload

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#58691]
### Background and motivation

Pass `Span<char>` and `ReadOnlySpan<char>` to `string.Create` method.
When using `string.Create` it is typically used for highly optimized scenarios for constructing strings, and usually having some parts of the string to be created in Span types. However, spans cannot be passed in the *state* parameter because span-s cannot be used as generic parameter of the `string.Create` method

`string.Create` seems to be still significantly faster compared to using a buffer (ArrayPool or stackalloc) for manually constructing the strings. (even when using DefaultInterpolatedStringHandler)

### API Proposal

```C#
namespace System;

public delegate void ReadOnlySpanSpanAction<T, TArg>(Span<T> span, ReadOnlySpan<TArg> arg);

public static string Create<T>(int length, ReadOnlySpan<T> state, ReadOnlySpanSpanAction<char, T> action);
```

And equivalent overloads for `Span<T>` counterpart. Because I am bad at naming, please feel free to consider a better name for `ReadOnlySpanSpanAction`.

### API Usage

```C#
public string DoWork(ReadOnlySpan<char> input)
{
    span = input.Slice(1, 4);
    return string.Create(11 + span.Length, span, (buffer, state) =>
    {
        var prefix = "Substring: ";
        prefix.CopyTo(buffer);
        buffer = buffer.Slice(prefix.Length);
        state.CopyTo(buffer);
    });
}
```

**Comment by Sergio0694** [comment]
Note that you can already achieve the same today with no need for any new APIs. For instance:

```csharp
public unsafe string DoWork(ReadOnlySpan<char> input)
{
    fixed (char* p = input)
    {
        const string prefix = "Substring: ";

        return string.Create(prefix.Length + input.Length, (Ptr: (IntPtr)p, input.Length), (buffer, state) =>
        {
            ReadOnlySpan<char> input = new((void*)state.Ptr, state.Length);

            prefix.CopyTo(buffer);

            input.CopyTo(buffer[prefix.Length..]);
        });
    }
}
```

If your `T` in the input `ReadOnlySpan<T>` is not an unmanaged type, you can still pin it like so:

```csharp
fixed (void* p = &Unsafe.As<string, byte>(ref MemoryMarshal.GetReference(input)))
{
    return string.Create(input.Length, (Ptr: (IntPtr)p, input.Length), (buffer, state) =>
    {
        ReadOnlySpan<string> input = MemoryMarshal.CreateSpan(ref Unsafe.As<byte, string>(ref *(byte*)state.Ptr), state.Length);

        // Do some work...
    });
}
```

This is well defined and will work fine, it's just very clunky 😄

Also, I'm not saying this API proposal is unnecessary, just pointing out a workaround to unblock you in the meantime 🙂

**Comment by svick** [comment]
My problem with this is that it's too limited. The old overload supports any type for state (as long as it's not a stack-only type). The proposed overload only supports ROS<char> and nothing else. That's not a problem that can be solved well in C# today, but I think it's still a problem, because it limits the usefulness of the proposed overload.

**Comment by acaly** [comment]
I agree with svick. There are many APIs that are not usable with ref structs besides this one. I really hope C# and runtime will allow ref structs as generic arguments, which solves all those problems.

**Comment by ladeak** [comment]
@Jozkee could you suggest who would triage this API request?

**Comment by Jozkee** [comment]
@ladeak I already triaged it, I set Future as I don't know if this is something worth having it's own API given these two things: it is very limited as it only adds support for ReadOnlySpan<char>, as pointed by the other commenters, and it has a workaround.

**Comment by ladeak** [comment]
Yes, but unfortunately, the workarounds involve `unsafe`.

**Comment by Jozkee** [comment]
> the workarounds involve unsafe.

Why is that a problem for you?

**Comment by stephentoub** [comment]
string.Create now supports this with its TState being allows ref struct
