### ISSUE TITLE
Using `ToastNotificationManagerCompat` etc. with .NET 5

### ISSUE THREAD

**Issue by pr8x** [dotnet/runtime#58697]
Hey, not sure if this is the right place to ask, but here we go: I am trying to port some code to .NET 5 and I was previously just referencing `Microsoft.Toolkit.Uwp.Notifications` to get access to `Microsoft.Toolkit.Uwp.Notifications` and the `ToastNotificationManagerCompat` compat class. With .NET5 that doesn't seem to be possible anymore:

> NETSDK1130 - Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.

So I am using the `net5.0-windows10.0.18362.0` TFM now. That however lacks some types such as `ToastNotificationManagerCompat` or `ToastContentBuilder`. Am I missing something?

**Comment by huoyaoyuan** [comment]
It's better to ask at https://github.com/microsoft/cswinrt
