### ISSUE TITLE
Test failure SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58704]
Run: [runtime-coreclr libraries-jitstress 20210905.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1343796&view=ms.vss-test-web.build-test-results-tab&runId=39350954&resultId=170265&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open

- SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at SampleSynthesisTests.SynthesizeRecognizeTests.SpeechSynthesizerToSpeechRecognitionEngine() in /_/src/libraries/System.Speech/tests/SynthesizeRecognizeTests.cs:line 52
```

**Comment by danmoseley** [comment]
This means that recognition timed out. Something was so slow it didn't complete in 30 secs?
https://github.com/danmoseley/runtime/blob/0cc6aa37009589d8eba2c886e396fe7a67c025bf/src/libraries/System.Speech/src/Recognition/RecognizerBase.cs#L3066

**Comment by danmoseley** [comment]
If this keeps happening I'll look into increasing the timeout.
