### ISSUE TITLE
Assertion failed 'block->countOfInEdges() > 0' during 'Remove empty finally' with infinite loop in finally

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#58729]
```csharp
public static void Main()
{
    try
    {
        System.Console.WriteLine("A");
    }
    finally
    {
        while (true)
        {
        }
    }
}
```

```text
Assert failure(PID 14880 [0x00003a20], Thread: 23380 [0x5b54]): Assertion failed 'block->countOfInEdges() > 0' in 'Program:Main()' during 'Remove empty finally' (IL size 16)

    File: D:\dev\dotnet\runtime\src\coreclr\jit\fgflow.cpp Line: 280
    Image: D:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
```

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL.

**Comment by kunalspathak** [comment]
I have seen cases where roslyn would add unreachable infinite loop inside finally - https://github.com/dotnet/roslyn/issues/51205

**Comment by EgorBo** [comment]
I also saw in the past that until we calculate preds we don't maintain bbRefs 100% accurate in the initial phases

**Comment by kunalspathak** [comment]
So it is not directly related to dotnet/roslyn#51205 but has similar effects. 

Roslyn duplicates the infinite loop from inside the `finally` block to the outside and add a jump to it leaving the infinite loop inside `finally` as it-is. Of course, jit need to be resilient to such ILs, but may be there is room to improve in roslyn as well - @jaredpar ?

```
IL to import:
IL_0000  72 33 11 00 70    ldstr        0x70001133
IL_0005  28 3c 00 00 0a    call         0xA00003C
IL_000a  de 02             leave.s      2 (IL_000e)
IL_000c  2b fe             br.s         -2 (IL_000c)
IL_000e  2b fe             br.s         -2 (IL_000e)
```

**Comment by jaredpar** [comment]
> Roslyn duplicates the infinite loop from inside the finally block to the outside and add a jump to it leaving the infinite loop inside finally as it-is and unreachable. 

Making sure we're on the same page: the loop outside the finally is the unreachable one correct? 

> may be there is room to improve in roslyn as well 

Possibly. I'm a bit surprised we are duplicating here, not sure why we'd be doing that when a loop is inside a `finally`. @cston any intuition here?

**Comment by kunalspathak** [comment]
>  the loop outside the finally is the unreachable one correct?

No, the loop inside the finally is unreachable. We directly jump to the loop outside on `IL_000e  `

**Comment by jaredpar** [comment]
Yes but won't an exception jump to the finally block?

**Comment by kunalspathak** [comment]
> Yes but won't an exception jump to the finally block?

That's right, my bad. I got confused with the symptoms seen in  dotnet/roslyn#51205

**Comment by cston** [comment]
> Roslyn duplicates the infinite loop from inside the finally block to the outside

It looks like the `IL_000e br.s IL_000e` after the `finally` is not a duplicate but just the instruction emitted for the block following a `finally` when that block is unreachable.
