### ISSUE TITLE
Revise pthread_condattr_setclock on Android

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#58737]
See https://github.com/dotnet/runtime/pull/58701#issuecomment-913789763

---

We can likely use `pthread_condattr_setclock` on Android in NDK r21.  Also our minimum supported ios version is now greater than the version that didn't support CLOCK_MONOTONIC.

So we can likely change the ifdef around `BROKEN_CLOCK_SOURCE` to exclude ios and Android

https://github.com/dotnet/runtime/blob/e55968b688acc9819ff47740fe645400f33eb36b/src/mono/mono/utils/mono-os-mutex.h#L39-L41

**Comment by filipnavara** [comment]
I think it's broken or unavailable on API level <= 20, which would roughly mean that it is available since Android 5.0. What is the minimum supported version now?

**Comment by MichalStrehovsky** [comment]
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/Directory.Build.props#L32

**Comment by lambdageek** [comment]
I'm mildly inclined to push this to 7.0.  The actual change is trivial, but I'm not sure if we will recognize failures if it leads to problems.

**Comment by MichalStrehovsky** [comment]
#62978 put back the previously rolled back fix for this in libSystem.Native. I believe this issue is still tracking using the API on Mono.

**Comment by akoeplinger** [comment]
Filed https://github.com/dotnet/runtime/issues/73650 for the remaining iOS/macOS piece.
