### ISSUE TITLE
When I run the diagnostic analysis tool, got some warning

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#58743]
Related:

![image](https://user-images.githubusercontent.com/7604648/132319867-74ec466e-2abb-4f3d-85c0-4e809ba62b20.png)

Is this expected, if not, do we need some fix?

**Comment by danmoseley** [comment]
@stephentoub do we run this analyzer against our own code?

I assume all use in public classes (such as ours above apparently) would need to be suppressed as removing would be a breaking change.

**Comment by danmoseley** [comment]
I guess I'm wrong - #41918 fixes two of these already.

**Comment by stephentoub** [comment]
> do we run this analyzer against our own code?

"AA0011" isn't a Roslyn analyzer.  It's part of the Visual Studio "Diagnostic Analysis" tool window, which let's you analyze dumps and then reports on things it finds.

**Comment by stephentoub** [comment]
> Is this expected, if not, do we need some fix?

Most of those types are not in this repo, and of the ones that are, they need a finalizer.  Sometimes there are valid reasons to have them.  You can also see in the analysis that there are very few of these instances.

I don't see anything that needs to be handled here.

Thanks.
