### ISSUE TITLE
CoreCLR GCC Product Build Linux x64 leg failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#58744]
```
CMake Error at /__w/1/s/src/libraries/Native/Unix/configure.cmake:683 (check_library_exists):
  check_library_exists Macro invoked with incorrect arguments for macro
  named: CHECK_LIBRARY_EXISTS
Call Stack (most recent call first):
  /__w/1/s/src/libraries/Native/Unix/CMakeLists.txt:112 (include)

-- Configuring incomplete, errors occurred!
See also "/__w/1/s/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeOutput.log".
See also "/__w/1/s/artifacts/obj/coreclr/Linux.x64.Checked/CMakeFiles/CMakeError.log".
/__w/1/s
/__w/1/s/artifacts/obj/coreclr/Linux.x64.Checked /__w/1/s
Executing make install -j 4
make: *** No rule to make target `install'.  Stop.
/__w/1/s
##[error]Failed to build "CoreCLR component".
##[error]Bash exited with code '2'.
```

Likely regressed with https://github.com/dotnet/runtime/pull/58701 which didn't run the failing leg (for whatever reason?).

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Not at my PC anymore for the rest of the day, but submitted #58746 to see if it fixes it. That line cost me half an hour of investigation (I saw a red herring) and it feels like it might be behind this too.

**Comment by ViktorHofer** [comment]
Reverted the offending change in https://github.com/dotnet/runtime/pull/58755.

**Comment by MichalStrehovsky** [comment]
> which didn't run the failing leg (for whatever reason?).

@ViktorHofer Looks like the leg only triggers when coreclr is changed but it doesn't consider changes to src/libraries/Native to be coreclr changes (it also doesn't trigger in #58746).

I tried to find where the definition of "coreclr changes" is but got lost in the yaml. Filed https://github.com/dotnet/runtime/issues/58779 so that it doesn't get lost.
