### ISSUE TITLE
Blazor HttpClient has null entries when JSON deserialized into collections

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#58748]
### Describe the bug
When using the `HttpClient` to deserialize data you must use an array, you cannot use collections. Using collections will result in extra entries in the collection which are null.

The file `weather.json` contains an array with 5 object entries.
`Http.GetFromJsonAsync<WeatherForecast[]>` returns an array with a proper length of 5.
`Http.GetFromJsonAsync<ICollection<WeatherForecast>>` returns a collection with a length of 8, with the last 3 being `null`.

![image](https://user-images.githubusercontent.com/10222521/132204697-b0ebd8a8-69f0-4c15-ba61-db361613a6d8.png)

### To Reproduce
1. Scaffold up a new Blazor project.
2. Open the /Pages/FetchData.razor file
3. Put a breakpoint on `forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");`
4. Add a new line `var bug = await Http.GetFromJsonAsync<ICollection<WeatherForecast>>("sample-data/weather.json");`
5. Run the application and compare the data from the two functions.

```cs
    protected override async Task OnInitializedAsync()
    {
        forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");
        var bug = await Http.GetFromJsonAsync<ICollection<WeatherForecast>>("sample-data/weather.json");
    }
```

### Further technical details
- ASP.NET Core version 5.0.9
- Include the output of `dotnet --info`
- Windows 10, Visual Studio 16.11.2

```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53
```

**Comment by pavelsavara** [comment]
I tested with dotnet.6.0.0-rc.1.21430. and VS 2021 preview 4 and it worked just fine.
![image](https://user-images.githubusercontent.com/271576/132379813-fde0295d-904d-4233-985f-c00bf06da88f.png)

**Comment by pavelsavara** [comment]
I was able to replicate on 5.0.400 + VS 16.11.2
![image](https://user-images.githubusercontent.com/271576/132383638-644bf41a-fcc7-4f63-a551-567b4d6017d0.png)

The `_items` is internal buffer and the public API returns correct value of `.Count`.

You could try to add following code to your test to validate it.
```
        Console.WriteLine("forecasts " + forecasts!.Length);
        Console.WriteLine("beetle " + bug!.Count);
```

**Comment by vanillajonathan** [comment]
@javiercn
Yes, the Count property for the collection does have the right value.

Yes, I was looking at the internal capacity. I was looking at the `_items` property.

The Length property of the WeatherForecast array a has a value of 5.
The Count property of the WeatherForecast  collection has a value of 5 but its internal contents (`_items`) contains 8 entries of which 3 are null.

![image](https://user-images.githubusercontent.com/10222521/132508103-bf9a9d63-20b1-47ac-8dad-dbf8615f5bf6.png)

The regular (non-WASM) application seem to behave slightly different, here the debugger does not show any `_items` property and it does not show any entries that are null.
