### ISSUE TITLE
The actual `ExceptBy` and `IntersectBy` APIs differ from the approved APIs

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/runtime#58756]
### Description

It was originally proposed to have heterogenous element types for the `second` parameter for both `ExceptBy` and `IntersectBy` APIs, but after discussions the API was approved with non-heterogenous element types. Here is a comparison of the original proposed API, and the approved API.

```diff
namespace System.Linq
{
    public static class Enumerable
    {
-        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelectorFirst);
-        public static IEnumerable<TSource1> ExceptBy<TSource1, TSource2, TKey>(this IEnumerable<TSource1> first, IEnumerable<TSource2> second, Func<TSource1, TKey> keySelectorFirst, Func<TSource2, TKey> keySelectorSecond);
-        public static IEnumerable<TSource1> ExceptBy<TSource1, TSource2, TKey>(this IEnumerable<TSource1> first, IEnumerable<TSource2> second, Func<TSource1, TKey> keySelectorFirst, Func<TSource2, TKey> keySelectorSecond, IEqualityComparer<TKey> comparer);

+        public static IQueryable<TSource> ExceptBy<TSource, TKey>(this IQueryable<TSource> source1, IEnumerable<TSource> source2, Expression<Func<TSource, TKey>> keySelector);
+        public static IQueryable<TSource> ExceptBy<TSource, TKey>(this IQueryable<TSource> source1, IEnumerable<TSource> source2, Expression<Func<TSource, TKey>> keySelector, IEqualityComparer<TKey>? comparer);

-        public static IEnumerable<TSource> IntersectBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelectorFirst);
-        public static IEnumerable<TSource1> IntersectBy<TSource1, TSource2, TKey>(this IEnumerable<TSource1> first, IEnumerable<TSource2> second, Func<TSource1, TKey> keySelectorFirst, Func<TSource2, TKey> keySelectorSecond);
-        public static IEnumerable<TSource1> IntersectBy<TSource1, TSource2, TKey>(this IEnumerable<TSource1> first, IEnumerable<TSource2> second, Func<TSource1, TKey> keySelectorFirst, Func<TSource2, TKey> keySelectorSecond, IEqualityComparer<TKey> comparer);

+        public static IQueryable<TSource> IntersectBy<TSource, TKey>(this IQueryable<TSource> source1, IEnumerable<TSource> source2, Expression<Func<TSource, TKey>> keySelector);
+        public static IQueryable<TSource> IntersectBy<TSource, TKey>(this IQueryable<TSource> source1, IEnumerable<TSource> source2, Expression<Func<TSource, TKey>> keySelector, IEqualityComparer<TKey>? comparer);
    }
}
```

Here is the actual API as it exists today:

```csharp
namespace System.Linq
{
    public static class Enumerable
    {
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector);
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer);

        public static IEnumerable<TSource> IntersectBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector);
        public static IEnumerable<TSource> IntersectBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer);        
    }
}        
```

The same is true for the `Queryable` implementation of these two new APIs. However, the API that was merged as part of #50335 PR and as noted by @eiriktsarpalis.

As they exist today, the APIs are arguably impractical or at the least a bit difficult to use.

#### Where the API could be improved

When you have two collections of the same type, and you want to either except or intersect on a common discriminator (i.e.; the `keySelector` in this case), you can only use the type as the discriminator. The `*By` extension feels like it should match the pattern of the `Except` extension in that `first` type matches the `second`.

```csharp
Person[] people =
{
    new("David", "Pine", 37),
    new("John", "Smith", 99),
    new("Jane", "Warren", 37)
};

Person[] morePeople =
{
    new("Ada", "Lovelace", 36),
    new("Chris", "Pine", 41),
    new("Maria", "Pixel", 37)
};

// Using "Except"
foreach (var p in people.Except(morePeople))
{
    Console.WriteLine(p);
    // Person { FirstName = David, LastName = Pine, Age = 37 }
    // Person { FirstName = John, LastName = Smith, Age = 99 }
    // Person { FirstName = Jane, LastName = Warren, Age = 37 }
}

record Person(string FirstName, string LastName, int Age);
```

Now using, `ExceptBy`:

```csharp
Person[] people =
{
    new("David", "Pine", 37),
    new("John", "Smith", 99),
    new("Jane", "Warren", 37)
};

Person[] morePeople =
{
    new("Ada", "Lovelace", 36),
    new("Chris", "Pine", 41),
    new("Maria", "Pixel", 37)
};

// Using "Except"
foreach (var p in people.ExceptBy(morePeople, p => p))
{
    Console.WriteLine(p);
    // Person { FirstName = David, LastName = Pine, Age = 37 }
    // Person { FirstName = John, LastName = Smith, Age = 99 }
    // Person { FirstName = Jane, LastName = Warren, Age = 37 }
}
```

This is the same as doing the `Except`, but if I wanted to have a key selector that was the last name it might look like this:

```csharp
Person[] people =
{
    new("David", "Pine", 37),
    new("John", "Smith", 99),
    new("Jane", "Warren", 37)
};

Person[] morePeople =
{
    new("Ada", "Lovelace", 36),
    new("Chris", "Pine", 41),
    new("Maria", "Pixel", 37)
};

// Using "Except"
foreach (var p in people.ExceptBy(morePeople.Select(p => p.LastName), p => p.LastName))
{
    Console.WriteLine(p);
    // Person { FirstName = John, LastName = Smith, Age = 99 }
    // Person { FirstName = Jane, LastName = Warren, Age = 37 }
}
```

This requires an extra select to select the keys from `second` collection, mapping it to the `TKey`. This isn't really ideal IMO, but I guess I'm curious if anyone else agrees?

Also, all of these newer APIs are missing their triple slash comments - was that intentional?

It might be a separate issue to file for that, but here are all the APIs in question that do not have triple slash comments.

- `Chunk`
- `ExceptBy`
- `ElementAt(..., Index)`
- `ElementAtOrDefault(..., Index)`
- `DistinctBy`
- `LastOrDefault(..., defaultValue)`
- `MaxBy`
- `MinBy`
- `SingleOrDefault(..., defaultValue)`
- `UnionBy`
- `Zip`

I'd love to help out with this, just let me know. Furthermore, I'd be happy to help with adjusting these APIs assuming there is still time before .NET 6 ships and of course if you all agree?

**Comment by eiriktsarpalis** [comment]
The API as approved [can be found here](https://github.com/dotnet/runtime/issues/27687#issuecomment-769339626). In the case of `Enumerable.ExceptBy` it looks as follows:
```csharp
public static class Enumerable
{
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TSource> second, Func<TSource, TKey> keySelector);
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TSource> second, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer);
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelectorFirst);
        public static IEnumerable<TSource> ExceptBy<TSource, TKey>(this IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelectorFirst, IEqualityComparer<TKey>? comparer);
}
```
I decided to drop the first couple of methods because I encountered issues with overload resolution/type inference when both method variants were exposed. The choice was influenced by the fact that they derive trivially from the second pair of methods (whereas the converse does not hold). 

Thus this is not a case of implemented APIs _differing_ from what was approved, but rather some approved APIs not being implemented at all. Approvals are a necessary but not sufficient condition for an API to find its way into the product. From time to time an area owner might decide to "unapprove" an approved API if new evidence suggests that the design does not meet the quality bar.

I find it unlikely that we would consider implementing the omitted methods in the future, due to the aforementioned issues. As you've already pointed out, they can be derived by calling a `Select` on the second argument.

cc @stephentoub @terrajobst

**Comment by IEvangelist** [comment]
Hi @eiriktsarpalis, I do see that - but I'm a bit conflicted. That is why I wanted to raise the issue. I just feel like it's too different than its counterpart `Except` where both collection types are the same.

**Comment by eiriktsarpalis** [comment]
I'm going to close this as by-design. At this stage we're not considering bringing back homogeneous overloads due to the aforementioned type inference issues.
