### ISSUE TITLE
Linux/ARM:  Communication lack of libunwind-devel community

### ISSUE THREAD

**Issue by leemgs** [dotnet/runtime#5876]
# > https://github.com/dotnet/core/blob/master/release-notes/1.0/Release-Notes-RC2.md

> - libunwind for DotNet Core: The call chain determination for exception handling and stack traces
> - Debian/Ubuntu: libunwind8  
> - CentOS/RHEL: libunwind
> - OS X: Part of OS

According to the summary of .NET Core RC2,  The call chain determination (for exception handling) and stack traces are performed by a `libunwind` library. However, It seems that the mailing-list of the `libunwind`open-source community is not active even though their community is an ancestor (e.g. mainline) of `libunwind` libraries that are used in a lot of modern Linux distributions and software platforms.  I am afraid that we can well(=effectively, successfully,...) utilize the `libunwind` libraries for .NET Core among  the popular CPU architectures (e.g. X86, X64, ARM, MIPS, PPC, and so on. ). At first glance,  the google's `libunwind` repository is more active/mature than the original `libunwind` community. Anyone who know this happening? 
- Original libunwind-devel mailling-list: 
  http://www.nongnu.org/libunwind/
  https://lists.nongnu.org/mailman/listinfo/libunwind-devel
- Google's libunwind git repository (for Android release):
  https://android.googlesource.com/platform/external/libunwind/

**Comment by jkotas** [comment]
We have local copy of https://github.com/libunwind/libunwind (https://github.com/dotnet/coreclr/pull/17094).
