### ISSUE TITLE
src/libraries/Native changes don't trigger GCC leg

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#58779]
The root cause behind the clean build blocking issue #58744 is that the GCC leg wasn't triggered.

This is likely because the GCC leg only runs on coreclr changes and the change to src/libraries/Native wasn't considered a coreclr change. Maybe those should be.

**Comment by hoyosjs** [comment]
Fixed in https://github.com/dotnet/runtime/pull/61958
