### ISSUE TITLE
Blazor AOT compilation runs out of memory, is extremely slow, results in a giant website

### ISSUE THREAD

**Issue by wihrl** [dotnet/runtime#58792]
### Describe the bug
It takes 45+ minutes to compile our project. The resulting wwwroot is 340MB.

One of the reasons for this is constantly running out of memory.
The compilation spawns many clang processes, choking my PC with "only" 16GB of RAM.
It may be due to it trying to utilize all 16 CPU threads.

A possible solution could be allowing the user to set a maximum worker count?

### To Reproduce
Compile a large Blazor WASM project with many dependencies with AOT.

### Further technical details
.NET 6 Preview 7

**Comment by wihrl** [comment]
128 assemblies according to the build output. The production release build without AOT is 70MB.

**Comment by radical** [comment]
re:too many cores being used:
In the next release (rc1), the msbuild AOT tasks work with msbuild to get decide how many cores to use. Which should mean that VS can control that number, or you can use `/m:N` argument on the command line for building, to control that.

**Comment by lewing** [comment]
This can be controlled by the msbuild properties that @radical mentioned.  If you still have problems after RC1 please reopen.
