### ISSUE TITLE
[API Proposal]: Implicit Guid Conversion to string

### ISSUE THREAD

**Issue by mumby0168** [dotnet/runtime#58798]
### Background and motivation

It would be nice to not have to call the `ToString()` method on a guid when directly assigning it to a string.

### API Proposal

```C#
string guid = Guid.NewGuid();
```     

vs

```C#
string guid = Guid.NewGuid().ToString();
```

### API Usage

```C#
string guid = Guid.NewGuid();
```     

### Risks

I don't see any.

**Comment by stephentoub** [comment]
We avoid adding implicit conversions that allocate, which this would. It's also not clear why Guid would special here,  why it would be demanding of such a conversion but other primitives wouldn't. And in any such implicit conversion,  there's a risk that the loss of type information hides a bug. And the implicit conversion would necessarily need to pick a default format to use: with ToString, you can pad that in to be specific.

I appreciate your taking the time to open this issue.  I don't think this is something we should add. Adding ".ToString()" to create a new string does not seem onerous enough to warrant this.

**Comment by mumby0168** [comment]
Okay that makes sense happy to close this. Thanks for your time.
