### ISSUE TITLE
Source-build encounters circular PublishBuilder dependency in WasmAppBuilder

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#58816]
This issue was discovered while updating source-build to the latest 6.0 commit shas - https://github.com/dotnet/installer/pull/11710/files

/repos/tarball1/src/runtime.c300b096419523024f2b807ec9db3c2d91df0298/artifacts/source-build/self/src/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj(33,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "PublishBuilder".

Binlog - [runtime.circularbuild.sourcebuild.zip](https://github.com/dotnet/runtime/files/7130269/runtime.circularbuild.sourcebuild.zip)

This is what the call graph looks like:
MSBuild WasmAppBuilder net6.0;net472
	WasmAppBuilder net6.0 -> Build
		WasmAppBuilder net472 -> publish
			MSBuild
			    Parameters
			        Projects = WasmAppBuilder.csproj
			        Targets = Publish
			        Properties = TargetFramework=net472
			    Global Properties:
			        TargetFramework = net472

This appears to be caused by this target in WasmAppBuilder.csproj - https://github.com/dotnet/runtime/blob/release/6.0/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj#L26

```
  <Target Name="PublishBuilder"
          AfterTargets="Build">

    <!-- needed for publishing with multi-targeting. We are publishing essentially to get the SR.MetadataLoadContext.dll :/ -->
    <ItemGroup>
      <_PublishFramework Include="$(TargetFrameworks)" />
    </ItemGroup>
    <MSBuild Projects="$(MSBuildProjectFile)" Targets="Publish" Properties="TargetFramework=%(_PublishFramework.Identity)" />
  </Target>
```

**Comment by MichaelSimons** [comment]
cc @safern

**Comment by ViktorHofer** [comment]
cc @akoeplinger @steveisok

**Comment by steveisok** [comment]
@radical Would be the best person to look into this.

**Comment by radical** [comment]
Can you try this patch?

```diff
diff --git a/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj b/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj
index 7c7377e5c42..a487a4f270a 100644
--- a/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj
+++ b/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj
@@ -25,13 +25,14 @@
   </ItemGroup>
 
   <Target Name="PublishBuilder"
-          AfterTargets="Build">
+          AfterTargets="Build"
+          Condition="'$(_RunningForPublishBuilder)' != 'true'">
 
     <!-- needed for publishing with multi-targeting. We are publishing essentially to get the SR.MetadataLoadContext.dll :/ -->
     <ItemGroup>
       <_PublishFramework Include="$(TargetFrameworks)" />
     </ItemGroup>
-    <MSBuild Projects="$(MSBuildProjectFile)" Targets="Publish" Properties="TargetFramework=%(_PublishFramework.Identity)" />
+    <MSBuild Projects="$(MSBuildProjectFile)" Targets="Publish" Properties="TargetFramework=%(_PublishFramework.Identity);_RunningForPublishBuilder=true" />
   </Target>
 
   <Target Name="GetFilesToPackage" Returns="@(FilesToPackage)">
```

**Comment by MichaelSimons** [comment]
Yes, I can give it a try and will report back.

**Comment by MichaelSimons** [comment]
@radical, I have confirmed your suggested fix addressed the issue.

**Comment by MichaelSimons** [comment]
This really shouldn't be closed yet IMO as the fix isn't available in release/6.0 yet.

**Comment by ericstj** [comment]
Fix introduced build failures. Let me suggest an alternative:
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies

most other tasks leverage this.

see if that would let you completely replace publish. Cc @Anipik

**Comment by radical** [comment]
> see if that would let you completely replace publish.

Updated https://github.com/dotnet/runtime/pull/59136 to try this

**Comment by ericstj** [comment]
@radical can you please make the same fix to `main`?  It looks like it still has this issue.
https://github.com/dotnet/runtime/blob/82993d2c9319b5ba6c8ecd8a79aa01e300ce5afd/src/tasks/WasmAppBuilder/WasmAppBuilder.csproj#L34
cc @dotnet/runtime-infrastructure

**Comment by lewing** [comment]
I think we can close this now.
