### ISSUE TITLE
[wasm] Fix "Clean" target for build, and publish

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#58826]
Currently, we end up leaving many files around even after a clean.

- [x] Blazor: Build with relinking (#58913)
- [x] ~~Blazor: Publish with relinking~~
- [x] ~~Blazor: Publish with AOT~~
- [x] non-Blazor: Build with relinking
- [x] ~~non-Blazor: Publish with relinking~~
- [x] ~~non-Blazor: Publish with AOT~~

Blazor doesn't support Clean with publish (https://github.com/dotnet/aspnetcore/issues/36546#issuecomment-920849896)

**Comment by radical** [comment]
note: this affects *rebuilds* also

**Comment by radical** [comment]
Blazor part blocked on https://github.com/dotnet/sdk/issues/20938 .

**Comment by ilonatommy** [comment]
@radical, it seems the Blazor issue got closed with no plans of fixing.

**Comment by radical** [comment]
This is already complete. Sorry, I missed closing this issue.
