### ISSUE TITLE
Validator does not validate annotated fields of a record type in .Net 6

### ISSUE THREAD

**Issue by harrodotnet** [dotnet/runtime#58839]
System.ComponentModel.DataAnnotations.Validator does not validate annotated fields in a record type in .Net 6

Not sure if this is a bug or a missing feature. I was experimenting with the new record type and tried to use DataAnnotations on the fields  to validate the record, i.e
`public record PersonRecord(string FirstName, [Required] string LastName, [EmailAddress] string Email);`

This unittest demonstrates the difference between classes and record.

`namespace TestRecordValidation
{
    using System.ComponentModel.DataAnnotations;
    using Xunit;

    public record PersonRecord(string FirstName, [Required] string LastName, [EmailAddress] string Email);

    public class PersonClass
    {
        public string FirstName { get; init; }

        [Required]
        public string LastName { get; init; }

        [EmailAddress]
        public string Email { get; init; }
    } 

    public class RecordValidationTest
    {
        // as reference, this test using a class works as expected
        [Fact]
        public void GivenAnInvalidClass_WhenValidated_ValidationExceptionIsThrown()
        {
            PersonClass personClass = new() { FirstName = "foo", LastName = null, Email = "bar" };
            Assert.Throws<ValidationException>(() => Validator.ValidateObject(personClass, new ValidationContext(personClass)));
        }

        // This test fails, no validationexception is thrown when validating an invalid record
        // Output from xUnit:
        // 
        // Message: 
        // Assert.Throws() Failure
        // Expected: typeof(System.ComponentModel.DataAnnotations.ValidationException)
        // Actual:   (No exception was thrown)
        [Fact]
        public void GivenAnInvalidRecord_WhenValidated_ValidationExceptionIsThrown()
        {
            PersonRecord personRecord = new(FirstName: "foo", LastName: null, Email: "bar" );
            Assert.Throws<ValidationException>(() => Validator.ValidateObject(personRecord, new ValidationContext(personRecord)));
        }
    }
}
`

### Configuration
.Net 6, Windows 11, x64; issue not specific to this configuration

**Comment by pinkfloydx33** [comment]
You're annotating the constructor parameter and **not** the property. The latter is what the validator looks at. You need to add the `property` attribute target:

```csharp
public record PersonRecord(string FirstName, [property: Required] string LastName, [property: EmailAddress] string Email);
```

Compare this [Sharplab](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwJQKYCOArgJYBOewAggC41kkBGRNeGIGt9TLbA3gF9UmbAFEAtgEMSAGyrBgFAM5KuDZq3ac663hkHJkGYxmEYKAYwD2ZYBgAKeMkqsA7fNdsAKKHAAMGABi5Eo0AHKS4ngANBgA2gAOZFYJTjQAnhz4xOSUALpY/hgAMpKhEVGxicmpZBkcEtJyCspKBb4BjbIAlADcQA=) to [this one](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgASwwJQKYCOArgJYBOewAggC41kkBGRNeGIGt9TLbA3gF9UmbAFEAtgEMSAGyrBgFAM5KuDZq3ac663hkHJkGYxmEYKAYwD2ZYBgAKeMkqsA7fNdsAKKHAAMGABi5Eo0AHKS4ngANBgA2vjE5JQAulj+GAAykqERUbFxEtJyCspKab4BRbIAlADcQA=). You'll see the generated C# and where the attributes are placed.

**Comment by harrodotnet** [comment]
@pinkfloydx33 
Thank you for your fast and clear answer!
