### ISSUE TITLE
FltToInt: OverflowException in Debug and no exception in Release

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#58832]
I noticed that we assign the same VN for "checked" and "unchecked" conversions from double to integer [here](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/valuenum.cpp#L9830-L9835), so I came up with the following repro that throws `OverflowException` in Debug (as expected) and prints "done" in Release:
```csharp
using System;

public class Program
{
    static double fld = double.MaxValue;

    static void Main()
    {
        double x = fld;
        try { Console.WriteLine(checked((ulong)x)); } catch { }

        if ((ulong)x == checked((ulong)x)) // should throw here
            Console.WriteLine("done"); // not expected to be invoked
    }
}
```

**Comment by SingleAccretion** [comment]
Quite surprising this wasn't caught while I was adding VN tests for all these casts.

.NET 6 fix would be to add the overflow exception somewhere [here](https://github.com/dotnet/runtime/blob/c515c50411e7bf57f13a13663b52a5d1b127f09c/src/coreclr/jit/valuenum.cpp#L9514).

.NET 7 fix is to delete all the `VNFunc`s for helpers (they're not needed anymore) and route all the codepaths through `VNForCast`, which should also add the exception set.
