### ISSUE TITLE
Automate Diffing of Release, Checked and Debug JITs

### ISSUE THREAD

**Issue by adiaaida** [dotnet/runtime#5884]
Create a script to verify there's no difference in jit outputs for check versus debug builds and checked vs release builds. We have verified this locally, but we need to automate it.

category:correctness
theme:testing
skill-level:intermediate
cost:medium

**Comment by JulieLeeMSFT** [comment]
Added Checked and Release diff in AzDo pipeline by https://github.com/dotnet/runtime/pull/61335.
Closing this issue.
