### ISSUE TITLE
[API Proposal]: Add IComparable to MemberInfo

### ISSUE THREAD

**Issue by chkn** [dotnet/runtime#58842]
### Background and motivation

Sometimes you need to compare `MemberInfo`s. This happens most frequently for me when I want to use `Type` as a key in a binary search tree. Currently, you need to wrap them in a struct that implements `IComparable`. As the implementation appears to be fairly trivial, this seems like unnecessary boilerplate.

### API Proposal

```C#
using System;

namespace System.Reflection
{
     public abstract class MemberInfo : IComparable, IComparable<MemberInfo> /* , ... */
     {
          public int CompareTo(MemberInfo other)
          {
               if (this == other) return 0;
               if (this.Module == other.Module) return this.MetadataToken - other.MetadataToken;
               return this.Module.ModuleVersionId < other.Module.ModuleVersionId ? -1 : 1;
          }
          public int CompareTo(object obj) => CompareTo((MemberInfo)obj);
     }
}
```     

### API Usage

```F#
let add (foo: 't) map = Map.add typeof<'t> foo map

// ^ currently gives:
// error FS0001: The type 'System.Type' does not support the 'comparison' constraint. For example, it does not support the 'System.IComparable' interface
```     

### Risks

None to my knowledge.

**Comment by huoyaoyuan** [comment]
> Sometimes you need to compare `MemberInfo`s. This happens most frequently for me when I want to use `Type` as a key in an F# Map.

F# should fit the BCL, not the opposite. There are no apparent definition of member infos.

**Comment by chkn** [comment]
> F# should fit the BCL, not the opposite.

Apologies if it wasn't clear, but this proposal doesn't have anything to do with F#. I've edited the description to avoid any confusion in case anyone is skimming for keywords in the future.

> There are no apparent definition of member infos.

Let me explain. Every member in a .NET assembly has a [MetadataToken](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=net-5.0), which is an integer. From that doc:

`A value which, in combination with Module, uniquely identifies a metadata element.`

So now we look at Module, which contains [ModuleVersionId](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.module.moduleversionid?view=net-5.0#System_Reflection_Module_ModuleVersionId). That doc says:

`Gets a universally unique identifier (UUID) that can be used to distinguish between two versions of a module.`

As you can see in my code sample, it's trivial to use these to derive a natural comparison. Though admittedly, I am no metadata expert, so I might be missing something.

**Comment by huoyaoyuan** [comment]
> Every member in a .NET assembly has a MetadataToken, which is an integer.

It's meant for equality, not ordering. It's a limitation that has to be represented by integer which is sortable. `IComparable` means high level ordering of the object, not its underlying representation.

**Comment by huoyaoyuan** [comment]
> Every member in a .NET assembly has a MetadataToken, which is an integer.

It's meant for equality, not ordering. It's a limitation that has to be represented by integer which is sortable. `IComparable` means high level ordering of the object.

**Comment by chkn** [comment]
Ok I think I understand the concern. I could see how metadata token is an internal detail and people might expect the ordering to be something more externally obvious like declaration order.

I suppose another issue would be if an ordered list were saved somewhere and then one assembly was recompiled- it could have the same identity but different MVID, changing the ordering.

I would still like to see at least Type be comparable, though possibly with a different implementation than the one I suggested

**Comment by stephentoub** [comment]
> I would still like to see at least Type be comparable

Based on what?  There's no intrinsically correct sort order.  Should they be ordered by Type name?  By type full name?  By metadata token?  By assembly and then namespace and then type name?  Are value types somehow "less than" reference types, or vice versa?

As there's no obvious ordering, I don't think Type should be comparable, either.

**Comment by chkn** [comment]
> Based on what? There's no intrinsically correct sort order. Should they be ordered by Type name? By type full name? By metadata token? By assembly and then namespace and then type name? Are value types somehow "less than" reference types, or vice versa?

I think it's perfectly fine for the ordering to be arbitrary, as long as it's consistent and works for all Types. The problem is, when you do need such an ordering, you find yourself asking those exact questions. Personally, I chose the combination of metadata token and MVID, but I am no expert and could've just as easily chosen type full name without realizing that different types in different assemblies could have the same full name.

So I suppose what I'm asking is for the experts in the BCL to choose an arbitrary ordering for these objects that is consistent and complete that we can use without having to reinvent the wheel and go through all of those questions ourselves.

**Comment by stephentoub** [comment]
In what scenario do you need an arbitrary ordering but don't care what that ordering is?

**Comment by chkn** [comment]
@stephentoub One case that I already mentioned is using it as a key in a binary search tree.

Another case I encountered was in making a canonicalizable AST for a DSL- all nodes have to be comparable so arguments to commutative binary ops can be sorted to arrive at the canonical form

**Comment by MichalStrehovsky** [comment]
What is the arbitrary ordering you would propose?

Here are some restrictions to make it more interesting:

* Name and Namespace can be empty (there's no requirement types have unique name for e.g. types with `compilercontrolled` visibility [in the metadata](https://www.ecma-international.org/publications-and-standards/standards/ecma-335/) and one can have multiple types with an empty name/namespace)
* `MetadataToken` can throw and not produce number (see `MemberInfo.MetadataToken` docs for some examples).

**Comment by chkn** [comment]
> MetadataToken can throw and not produce number (see MemberInfo.MetadataToken docs for some examples).

Yeah my proposal was basically metadata token followed by MVID (pseudocode in description). At least in the case where `MetadataToken` can throw there appears to be a workaround.

**Comment by MichalStrehovsky** [comment]
Even if we hypothetically were able to make MetadataToken work 100% of time (we can't), one can just do this:

`typeof(object), new TypeDelegator(typeof(object))`

What's the sort order of these?

The bottom line is that Type cannot be made IComparable. .NET offers a solution to this in the form of IComparer interface. If in your specific domain you only have to worry about a subset of types (the runtime types), make a IComparar that compares them using module and token. It will not work for all possible types, but it will work for those that you care about. If F# map cannot consume IComparer, it's an F# issue.

**Comment by MichalStrehovsky** [comment]
(Also, comparing MetadataToken will not give a stable sort for generic types, so one needs to make sure the types are not generic. The tokens are the same irrespective of generic arguments.)

**Comment by chkn** [comment]
Makes sense. Thanks for giving my proposal fair consideration!
