### ISSUE TITLE
question about jit code on mono interal call case crash.

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#58858]
hi，I am embedding mono with the unreal engine.  Crash occurred in below case:

the c++ code
```c++

template<class TEnum>
class TEnumAsByte
{
	typedef TEnumAsByte_EnumClass<TIsEnumClass<TEnum>::Value> Check;

public:
	typedef TEnum EnumType;

	TEnumAsByte() = default;
	TEnumAsByte(const TEnumAsByte&) = default;
	TEnumAsByte& operator=(const TEnumAsByte&) = default;

	/**
	 * Constructor, initialize to the enum value.
	 *
	 * @param InValue value to construct with.
	 */
	FORCEINLINE TEnumAsByte( TEnum InValue )
		: Value(static_cast<uint8>(InValue))
	{ }

	/**
	 * Constructor, initialize to the int32 value.
	 *
	 * @param InValue value to construct with.
	 */
	explicit FORCEINLINE TEnumAsByte( int32 InValue )
		: Value(static_cast<uint8>(InValue))
	{ }

	/**
	 * Constructor, initialize to the int32 value.
	 *
	 * @param InValue value to construct with.
	 */
	explicit FORCEINLINE TEnumAsByte( uint8 InValue )
		: Value(InValue)
	{ }

public:
	/**
	 * Compares two enumeration values for equality.
	 *
	 * @param InValue The value to compare with.
	 * @return true if the two values are equal, false otherwise.
	 */
	bool operator==( TEnum InValue ) const
	{
		return static_cast<TEnum>(Value) == InValue;
	}

	/**
	 * Compares two enumeration values for equality.
	 *
	 * @param InValue The value to compare with.
	 * @return true if the two values are equal, false otherwise.
	 */
	bool operator==(TEnumAsByte InValue) const
	{
		return Value == InValue.Value;
	}

	/** Implicit conversion to TEnum. */
	operator TEnum() const
	{
		return (TEnum)Value;
	}

public:

	/**
	 * Gets the enumeration value.
	 *
	 * @return The enumeration value.
	 */
	TEnum GetValue() const
	{
		return (TEnum)Value;
	}

private:

	/** Holds the value as a byte. **/
	uint8 Value;


	FORCEINLINE friend uint32 GetTypeHash(const TEnumAsByte& Enum)
	{
		return GetTypeHash(Enum.Value);
	}
};


struct FPhysicalSurfaceName
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY()
	TEnumAsByte<enum EPhysicalSurface> Type;
};

static TEnumAsByte<enum EPhysicalSurface> Internal_FPhysicalSurfaceName_get_Type (MonoObject* self)
{
   return ReadonlyScriptingObjectConverter<FPhysicalSurfaceName>(self)->Type;
}

```
the c#code 
```c#
public enum EPhysicalSurfaceAsByte : byte
{
	SurfaceType_Default = 0,
	SurfaceType1 = 1,
	SurfaceType2 = 2,
	SurfaceType3 = 3,
	SurfaceType4 = 4,
	SurfaceType5 = 5,
	SurfaceType6 = 6,
	SurfaceType7 = 7,
	SurfaceType8 = 8,
	SurfaceType9 = 9,
	SurfaceType10 = 10,
}
public partial class FPhysicalSurfaceName : ScriptingWrapperOfType
{

	public EPhysicalSurfaceAsByte Type
	{
		[MethodImpl(MethodImplOptions.InternalCall)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall)]
		set;
	}

}
```

this will crash when garbage collection because the FPhysicalSurfaceName obj memory is written bad.

but if I replace the return type using `uint8` instead of  `TEnumAsByte<enum EPhysicalSurface>` will be work well.

I found when return type  `TEnumAsByte<enum EPhysicalSurface>` has more three instructions than `uint8`.

![image](https://user-images.githubusercontent.com/5187024/132660268-1f581690-0ab4-463b-82a6-5afb94d13665.png)

why it causes the crash?

**Comment by lambdageek** [comment]
I think this is because in the Windows ABI, a C++ class like `TEnumAsByte<enum EPhysicalSurface>` is not returned in a register, but instead the ABI expects that the caller will allocate a value on the struct and pass its address in the RAX register.

I think this is because `template <class T> TEnumAsByte` has user-defined constructors, which looks like it disqualifies the type from being passed in a register https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#return-values

Whereas on the managed side, an enum is assumed to be returned as its underlying type (ie byte), and it will expect the result to be in RAX.

---

In general, @srxqds it is better to use simple plain old data in the interop methods between managed and native code.

You could also do something like this:

C#
```
public EPhysicalSurfaceAsByte Type
	{
		get {
                   EPhysicalSurfaceAsByte v;
                   private_getter (ref v);
                   return v;
                }
	}

	[MethodImpl(MethodImplOptions.InternalCall)]
	void private_Type_getter (ref EPhysicalSurfaceAsByte outval);
```

C++:
```
    static 
    void private_Type_getter (MonoObject *self, TEnumAsByte<enum EPhysicalSurface> *outval) 
   {
      *outval = ReadonlyScriptingObjectConverter<FPhysicalSurfaceName>(self)->Type;
   }
```

This will do the same thing (pass a pointer to a temporary on the stack), but it will be explicit on both the native and the managed side, and the ABI will be ok because pointers arguments are passed in registers in both C++ and in Mono.

**Comment by srxqds** [comment]
ok, thank you

**Comment by srxqds** [comment]
> I think this is because in the Windows ABI, a C++ class like `TEnumAsByte<enum EPhysicalSurface>` is not returned in a register, but instead the ABI expects that the caller will allocate a value on the struct and pass its address in the RAX register.
> 
> I think this is because `template <class T> TEnumAsByte` has user-defined constructors, which looks like it disqualifies the type from being passed in a register https://docs.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-160#return-values
> 
> Whereas on the managed side, an enum is assumed to be returned as its underlying type (ie byte), and it will expect the result to be in RAX.
> 
> In general, @srxqds it is better to use simple plain old data in the interop methods between managed and native code.
> 
> You could also do something like this:
> 
> C#
> 
> ```
> public EPhysicalSurfaceAsByte Type
> 	{
> 		get {
>                    EPhysicalSurfaceAsByte v;
>                    private_getter (ref v);
>                    return v;
>                 }
> 	}
> 
> 	[MethodImpl(MethodImplOptions.InternalCall)]
> 	void private_Type_getter (ref EPhysicalSurfaceAsByte outval);
> ```
> 
> C++:
> 
> ```
>     static 
>     void private_Type_getter (MonoObject *self, TEnumAsByte<enum EPhysicalSurface> *outval) 
>    {
>       *outval = ReadonlyScriptingObjectConverter<FPhysicalSurfaceName>(self)->Type;
>    }
> ```
> 
> This will do the same thing (pass a pointer to a temporary on the stack), but it will be explicit on both the native and the managed side, and the ABI will be ok because pointers arguments are passed in registers in both C++ and in Mono.

@lambdageek I try this solution, but it crashed again. you can check the snapshot.
![image](https://user-images.githubusercontent.com/5187024/135076910-0cc6b303-fc95-4ddd-bbe4-380ed678b5a8.png)

![image](https://user-images.githubusercontent.com/5187024/135077078-a3d18a1a-9e54-4f29-8e46-4534c7ea0af8.png)
