### ISSUE TITLE
Please provide MSI installer for .Net5

### ISSUE THREAD

**Issue by wsy** [dotnet/runtime#58859]
I'm trying to deploy .Net5 runtime via Group Policy, which supports only MSI Installer.
I mean, something like `dotnet-runtime-5.0-windows-x64.msi`.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Have you considered using some of the available tooling for conversion of EXE into an MSI, or preferably use SCCM for deployment?

**Comment by wsy** [comment]
> [Triage] Have you considered using some of the available tooling for conversion of EXE into an MSI, or preferably use SCCM for deployment?

Actually, I had never thought about that before. I will try and evaluate the above workarounds.
But I still believe .Net should provide MSI installer.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing the issue. Problem with MSI is that it does not provide proper ref-counting for all .NET install scenarios. Therefore we use .NET EXE bundle package.
