### ISSUE TITLE
JObject Support

### ISSUE THREAD

**Issue by guochenglai** [dotnet/runtime#58856]
Hi team,
Cloud you Support JObject serialize and deserialize from NewtonSoft.Json. Or Could you develop an equivalent class in SystemTextJson

**Comment by hez2010** [comment]
You can use JsonNode in .NET 6 instead.

**Comment by ylabade** [comment]
Maybe you can use `JsonElement` :
```cs
using System.Text.Json;
using System.Text.Json.Serialization;

var json = "{\"key\":\"value\"}";
var document = JsonSerializer.Deserialize<Document>(json);
var value = document.Value.GetString();

public class Document
{
    [JsonPropertyName("key")]
    public JsonElement Value { get; set; }
}
```

**Comment by eiriktsarpalis** [comment]
As already mentioned, there's `JsonDocument`/`JsonElement` which provide similar functionality but are restricted to read-only access. Additionally .NET 6 will see the inclusion of `JsonNode` which is a construct largely equivalent to `JObect`.

> Cloud you Support JObject serialize and deserialize from NewtonSoft.Json.

We cannot depend on Newtonsoft.Json, so really this is a question of `Newtonsoft.Json` (or some other 3p library) providing `System.Text.Json` converters for `JObject`.
