### ISSUE TITLE
.NET 6: when format a number with '$', the display position is strange.

### ISSUE THREAD

**Issue by moonmile** [dotnet/runtime#58876]
### Description

When I format a number with '$' and , the display position of the number is strange.
The display is strange when two strings are concatenated.

Repo Code:

```
      int n = 10;
      int m = 20;

      var msg1 = $"n is {n}";
      Console.WriteLine(msg1);
      var msg2 = $"n is {n} \nm is {m} \n";
      Console.WriteLine(msg2);
      // msg2 is
      //  n is 10
      //  m is 20

      // 
      var msg3 = $"n is {n} \n" + $"m is {m} \n";
      Console.WriteLine(msg3);
      // msg3 is 
      //  10n is
      //  20m is
```

by .NET6

![image](https://user-images.githubusercontent.com/1286584/132707443-9b74c16b-ad3a-4c26-b281-7c32ff15c130.png)

by .NET5

![image](https://user-images.githubusercontent.com/1286584/132707722-69d9e1a6-501a-4035-b198-dba41ac1a927.png)

### Configuration

- dotnet version 6.0.100-preview.7.21379.14
- windows 10.0.19043.1165
- x64

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/55461, which has already been fixed, and you should see the fix in the next preview.

**Comment by moonmile** [comment]
Thank you very much. I wait for the next version.
