### ISSUE TITLE
Source Generator projects don't need to be included in other library's sln files

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#58879]
Any library that references System.Text.Json is getting the Json Source Generator project in their .sln file:

https://github.com/dotnet/runtime/blob/ef857626c5a0ad29cffb61a2f8db87e083ca2332/src/libraries/Microsoft.Extensions.Configuration.Json/Microsoft.Extensions.Configuration.Json.sln#L54-L55

https://github.com/dotnet/runtime/blob/ef857626c5a0ad29cffb61a2f8db87e083ca2332/src/libraries/Microsoft.Extensions.DependencyModel/Microsoft.Extensions.DependencyModel.sln#L24-L25

https://github.com/dotnet/runtime/blob/ef857626c5a0ad29cffb61a2f8db87e083ca2332/src/libraries/System.Net.Http.Json/System.Net.Http.Json.sln#L28-L29

These are unnecessary, bloating the .sln file. With https://github.com/dotnet/runtime/pull/58446, there are now 2 .csprojs for each source generator - each targeting a different version of Roslyn. Which will make it even worse.

We only really need the Source Generator projects in the .sln files of the libraries that build source generators: Json and Logging.Abstractions.

cc @ViktorHofer

**Comment by ViktorHofer** [comment]
That is by design as solution files need to be dependency closure complete. If library A depends on System.Text.Json then the source generators of System.Text.Json need to be available in the solution as otherwise System.Text.Json isn't buildable.

In other terms, VS requires all ProjectReferences (which represent the build graph) to be part of the solution.

**Comment by eerhardt** [comment]
> then the source generators of System.Text.Json need to be available in the solution as otherwise System.Text.Json isn't buildable.

I think this is where the disconnect lies. The System.Text.Json src project doesn't need the STJ source generator to be buildable. The only reason it has a "project reference" to it is for packing purposes. Because we want the source generator to be packed in the STJ nuget package. But to just build the System.Text.Json src project, the source generator isn't necessary.

**Comment by ViktorHofer** [comment]
> I think this is where the disconnect lies. The System.Text.Json src project doesn't need the STJ source generator to be buildable. The only reason it has a "project reference" to it is for packing purposes. Because we want the source generator to be packed in the STJ nuget package. But to just build the System.Text.Json src project, the source generator isn't necessary.

Just to double check, you are saying the System.Text.Json source generator isn't an analyzer input to the System.Text.Json source project? If not, then I question the existence of the ProjectReference (AnalyzerReference is a P2P) from S.T.J to the analyzer. That seems wrong. We should find a better way to express that an analyzer should be part of the shared framework.

**Comment by eerhardt** [comment]
> Just to double check, you are saying the System.Text.Json source generator isn't an analyzer input to the System.Text.Json source project?

Correct. Here are the analyzers that are passed during a `net7.0` build of the System.Text.Json source project:
![image](https://user-images.githubusercontent.com/8291187/167443984-94c5199d-a82f-4f08-8da9-3afb06e716a5.png)

**Comment by ViktorHofer** [comment]
I took a closer look. Even though I was able to tackle the underlying problem with https://github.com/dotnet/runtime/pull/69069, the change won't help with this specific issue. System.Text.Json ships as package and includes the analyzer project inside it. Even though the analyzer is not a compile dependency, it's a package dependency which is expressed via the `AnalyzerRefernence` item(s) in the project file.

When I remove the projects from the solution and delete the obj and bin folders of the two source generator projects I hit the following issue:

```
8>------ Build started: Project: System.Text.Json (src\System.Text.Json), Configuration: Debug Any CPU ------
8>System.Text.Json -> C:\git\runtime4\artifacts\bin\System.Text.Json\Debug\net7.0\System.Text.Json.dll
8>System.Text.Json -> C:\git\runtime4\artifacts\bin\System.Text.Json\Debug\net6.0\System.Text.Json.dll
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath)
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath)
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfos(IEnumerable`1 referencePaths)
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
8>C:\git\runtime4\.dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
8>Done building project "System.Text.Json.csproj" -- FAILED.
8>System.Text.Json -> C:\git\runtime4\artifacts\bin\System.Text.Json\Debug\net462\System.Text.Json.dll
========== Build: 1 succeeded, 1 failed, 6 up-to-date, 0 skipped ==========
```

I have been seeing this happen whenever a solution's dependency graph isn't complete. As said, even though the analyzers aren't a compile dependency, they are dependencies in the graph ([an `AnalyzerReference` is a `ProjectReference`](https://github.com/dotnet/runtime/blob/0533792282ba5546e10cb5c3d10748aff46ddc1a/src/libraries/Directory.Build.targets#L204-L221)).
