### ISSUE TITLE
Assertion failed 'varTypeIsSIMD(user) && (returnType == user->TypeGet())'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#58897]
Test: JIT\Directed\StructABI\structreturn\structreturn.cmd

```
Assert failure(PID 31040 [0x00007940], Thread: 24376 [0x5f38]): Assertion failed 'varTypeIsSIMD(user) && (returnType == user->TypeGet())' in 'TestHFAandHVA:ReturnVector2WrapperPromoted():Vector2Wrapper' during 'Lowering nodeinfo' (IL size 24)

    File: C:\gh\runtime\src\coreclr\jit\lower.cpp Line: 3518
    Image: c:\gh\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
```

Configuration:
```
COMPlus_TieredCompilation=0
COMPlus_EnableSSE2=0
COMPlus_JitStress=1
```

Appears to be x64 only, Windows and Linux.

https://dev.azure.com/dnceng/public/_build/results?buildId=1349692&view=ms.vss-test-web.build-test-results-tab&runId=39537082&resultId=109747&paneView=debug

@tannergooding @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Simpler repro configuration:
```
COMPlus_TieredCompilation=0
COMPlus_EnableSSE2=0
COMPlus_JitStressModeNames=STRESS_PROMOTE_FEWER_STRUCTS
COMPlus_JitStressModeNamesOnly=1
```

The `EnableSSE2=0` forces Vector2.get_Zero to not be intrinsic. This prevents promoting V01 so we end up with a LCL_FLD instead of a LCL_VAR. Lower gets upset with that.

```
STMT00001 (IL 0x008...0x00F)
               [000010] -ACXG+------              *  ASG       simd8  (copy)
               [000004] D----+-N----              +--*  LCL_FLD   simd8  V01 loc1         [+0] Fseq[f1]
               [000006] --CXG+------              \--*  CALL      simd8  System.Numerics.Vector2.get_Zero
```

@sandreenko Should STRESS_PROMOTE_FEWER_STRUCTS have an exception for some things, like structs of a single SIMD type field?

(btw, does it really make sense to allow `EnableSSE=0` or `EnableSSE2=0`? Isn't SSE2 our min-bar hardware?)

**Comment by tannergooding** [comment]
> (btw, does it really make sense to allow EnableSSE=0 or EnableSSE2=0? Isn't SSE2 our min-bar hardware

These exist so devs can test validate code paths as needed, such as being able to test the software fallback path on a machine which has SSE/SSE2 path. This is important since not all configurations support intrinsics (such as ARM32 or x86 Linux).

**Comment by sandreenko** [comment]
> STMT00001 (IL 0x008...0x00F)
>                [000010] -ACXG+------              *  ASG       simd8  (copy)
>                [000004] D----+-N----              +--*  LCL_FLD   simd8  V01 loc1         [+0] Fseq[f1]
>                [000006] --CXG+------              \--*  CALL      simd8  System.Numerics.Vector2.get_Zero

why does it trigger the assert?
```
assert(
varTypeIsSIMD(user) // ASG sim8 -> yes
 && 
(returnType == user->TypeGet()) // simd8 == simd8 -> yes
```

**Comment by kunalspathak** [comment]
> why does it trigger the assert?

Because in https://github.com/dotnet/runtime/pull/53578, we [retype the `call` type to `SIMD8`](https://github.com/dotnet/runtime/pull/53578/files#diff-af8a9db9bb28767adad71c804c3a62d35b4e34ffbc64362b7138ab703ef964ccR9540). In lower, the `returnType` is ABI-specific `long` for `Vector2` and that doesn't match with `user-TypeGet()` which is `SIMD8`. 

I think the right assert should be the following, that makes sure that if call type was ever modified (in importer) it was SIMD and it matches with the type of user. If not, then the user type should match the ABI-specific `returnType` .

```c++
assert((varTypeIsSIMD(user) && user->TypeIs(origType)) || (returnType == user->TypeGet()));
```

**Comment by sandreenko** [comment]
>> Because in #53578, we retype the call type to SIMD8. In lower, the returnType is ABI-specific long for Vector2 and that doesn't match with user-TypeGet() which is SIMD8.

So the tree that comes to the lowering function that triggers the assert is:
```
              [000010] -ACXG+------              *  ASG       simd8  (copy)
               [000004] D----+-N----              +--*  LCL_FLD   simd8  V01 loc1         [+0] Fseq[f1]
               [000006] --CXG+------              \--*  CALL      LONG System.Numerics.Vector2.get_Zero
```
?


it looks fine, `LowerStoreLocCommon` has logic to work with it and add a bitcast and transform it into:
```
*  ASG       simd8  (copy)
+--*  LCL_FLD   simd8  V01 loc1         [+0] Fseq[f1]
\--* BITCAST simd8
     \--*  CALL      LONG System.Numerics.Vector2.get_Zero
```

meaning that we can relax the assert and ignore it for 6.0 because release generates correct code.

**Comment by kunalspathak** [comment]
The tree we have is following (note, the `CALL` is of type `simd8` and not `LONG` because of our retyping in importer that I pointed.

```
STMT00001 (IL 0x008...0x00F)
N003 ( 18, 10) [000010] -ACXG---R---              *  ASG       simd8  (copy)
N002 (  3,  4) [000004] D------N----              +--*  LCL_FLD   simd8  V01 loc1         [+0] Fseq[f1]
N001 ( 14,  5) [000006] --CXG-------              \--*  CALL      simd8  System.Numerics.Vector2.get_Zero
```

Here is the tree before/after lowering and yes, we do add bitcast to transform. 

```
(before)
N001 ( 14,  5) [000006] --CXG-------         t6 =    CALL      simd8  System.Numerics.Vector2.get_Zero
                                                  /--*  t6     simd8  
N003 ( 18, 10) [000010] DA-XG-------              *  STORE_LCL_FLD simd8  V01 loc1         [+0] Fseq[f1]

------
(after)

N001 ( 14,  5) [000006] --CXG-------         t6 =    CALL      long   System.Numerics.Vector2.get_Zero
                                                  /--*  t6     long   
               [000026] -cCXG-------        t26 = *  BITCAST   simd8 
                                                  /--*  t26    simd8  
N003 ( 18, 10) [000010] DA-XG-------              *  STORE_LCL_FLD simd8  V01 loc1         [+0] Fseq[f1]
```

I will send out PR shortly.
