### ISSUE TITLE
DOTNET_ vs COMPlus_ env var prefix for creating dumps

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#58924]
Based on this docs: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps the environment variable `DOTNET_DbgEnableMiniDump` should work the same way as `COMPlus_DbgEnableMiniDump`.
However, the former (DOTNET_...) didn't work for me and the latter (COMPlus_) did. Is the documentation wrong or is this a bug/missing feature?

Running in `mcr.microsoft.com/dotnet/nightly/sdk:6.0-bullseye-slim` docker image:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21457.2
 Commit:    1aefb20570

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100-rc.1.21457.2/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  6.0.100-rc.1.21457.2 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by hoyosjs** [comment]
This should've started working with https://github.com/dotnet/runtime/pull/50507, not sure why it didn't. Regardless we should amend the public docs to at least state this is only a 6.0+ feature.

**Comment by hoyosjs** [comment]
Turns our this is handled in the procabort handler which is in the PAL. Such layer doesn't have the CLR's config facility, so we do a hard manual check: https://github.com/dotnet/runtime/blob/331823f4046da1530dd950ac3ad8a87b3cdd584d/src/coreclr/pal/src/thread/process.cpp#L3278-L3297

Affected variables:
- COMPlus_EnableAlternateStackCheck
- COMPlus_EnableAssertDialog
- COMPlus_DefaultStackSize
- COMPlus_UseDefaultBaseAddr
- COMPlus_CodeHeapReserveForJumpStubs (
- COMPlus_LTTng
- COMPlus_DbgEnableMiniDump
- COMPlus_DbgMiniDumpName
- COMPlus_DbgMiniDumpType
- COMPlus_CreateDumpDiagnostics
- COMPlus_EnableCrashReport

cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
>Regardless we should amend the public docs to at least state this is only a 6.0+ feature.

That is documented. Unfortunately it seems some of the official variables do their own thing &ndash; this is unfortunate. This isn't a .NET 6 issue really so we can move this to .NET 7 for now.
