### ISSUE TITLE
System.IO.Pipelines need support targetframework NETStandard 2.1

### ISSUE THREAD

**Issue by KumoKyaku** [dotnet/runtime#58925]
Now System.IO.Pipelines Package support NETStandard 2.0, but need deepend System.Buffers (>= 4.5.1),System.Memory (>= 4.5.4),System.Threading.Tasks.Extensions (>= 4.5.4).

In Unity2021.2 support netstardard2.1 dll, and System.IO.Pipelines NETStandard 2.0 dll in unity need dependencies.
![image](https://user-images.githubusercontent.com/15962980/132817327-0a3f1472-382d-4cbe-aa96-2ae05f046d87.png)

So, we need a System.IO.Pipelines NETStandard 2.1 dll to remove System.Buffers,System.Memory dependencies.
https://www.nuget.org/packages/System.IO.Pipelines/6.0.0-preview.7.21377.19

**Comment by ViktorHofer** [comment]
Why can't unity use the netstandard2.0 asset which depends on System.Memory and System.Buffers? We have many more assemblies that depend on these two references.

**Comment by KumoKyaku** [comment]
In Unity 2021.2  add System.Memory,System.Buffers dll can resolve this problem, but 
Many unity plug-in need bring in  System.Memory,System.Buffers, and every plug-in author bring in dll by heself, and cause class conflict.
And netstandard2.1 can minimum dependency can be achieved.
If we have a no dependencies netstandard2.1 dll will helpful.

**Comment by ViktorHofer** [comment]
As mentioned, we have many libraries in dotnet/runtime that depend on System.Memory and/or System.Buffers. We are not going to introduce a netstandard2.1 tfm for every one of these as it increases the project file's complexity and increases build times. IMO this sounds like an authoring problem of plugin authors.

**Comment by KumoKyaku** [comment]
If netstandard 2.1 is not supported, then in order to use "System.IO.Pipelines", 4 libraries need to be referenced.
System.Buffers (>= 4.5.1)
System.Memory (>= 4.5.4)
System.Threading.Tasks.Extensions (>= 4.5.4).
System.Runtime.CompilerServices.Unsafe (>= 4.5.3)

With netstandard 2.1 support, dependencies can be reduced to 0.
Reducing dependencies is essential to reduce the complexity of dependencies and greatly reduces class conflicts and library version inconsistencies.
My own library supports both netstandard2.0, 2.1 net 5.0.
I don't think that supporting an additional platform, netstandard 2.1, has a significant impact on the complexity of the project files.
The reason for removing support for a target framework because of increased build time sounds strange.

On different platforms, such as unity, there are all sorts of strange restrictions on the use of libraries. Isn't that what dotnet is supposed to do, to support as many scenarios as possible, within the limits of what is allowed?

**Comment by ViktorHofer** [comment]
My question is, where would we draw the line? We already have a quite complex configuration/tfm matrix and introducing more configurations just for the sake of a simplified dependency graph doesn't sound right to me.

I would like to hear from the Unity team first why authoring plugins that target netstandard2.0 is causing troubles.

@marek-safar @davidfowl do we have a point of contact from the Unity team?

**Comment by KumoKyaku** [comment]
A link to a useful use case, this problem has been occurring frequently in unity.
https://forum.unity.com/threads/2021-2-0b6-and-system-memory-readonlyspan-under-net-4-8.1152104/

**Comment by ViktorHofer** [comment]
Just read through the whole discussion about Unity's support of .NETStandard 2.1 on Mono's .NETFramework and the planned .NET 6 support. I think https://forum.unity.com/threads/unity-future-net-development-status.1092205/page-7#post-7468879 summarizes well what needs to be done to avoid problems with assemblies that are part of unity's combined netstandard2.1+net48 profile and are included in packages.

The underlying issue to me sounds like Unity's lack of support of correctly handling NuGet packages and it not using any of the SDK targets, i.e. conflict resolution which would handle trimming out runtime targets that are already satisfied by the runtime (in this case the runtime for mono would be the netstandard+net48 profile).

**Comment by ViktorHofer** [comment]
In example, when you use the Microsoft.NET.Sdk in your project, target netstandard2.1 and reference a netstandard2.0 library like System.Memory which is already satisfied by the target framework, the SDK (conflict resolution and ResolveAssemblyReferences) would make sure that the correct version is used.

When you then look at the Csc invocation in the binlog (which you can create by adding the /bl flag: `dotnet build /bl`), you can see that the reference from the framework (also called inbox reference) is used instead the one from the System.Memory package.

 That's because conflict resolution (`ResolvePackageFileConflicts`) trims out conflicting reference and runtime assets:

![image](https://user-images.githubusercontent.com/7412651/132845252-93e717a7-913c-4301-9077-283ef75591ab.png)


In this case the inbox System.Memory.dll from the netstandard2.1 framework directory won over the asset from the System.Memory package:

```
Encountered conflict between 'Reference:C:\Users\vihofer\.nuget\packages\system.memory\4.5.4\lib\netstandard2.0\System.Memory.dll' and 'Reference:C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Memory.dll'. Choosing 'Reference:C:\Program Files\dotnet\packs\NETStandard.Library.Ref\2.1.0\ref\netstandard2.1\System.Memory.dll' because AssemblyVersion '4.0.2.0' is greater than '4.0.1.1'.
```

**Comment by KumoKyaku** [comment]
You are right, now I understand the problem.
netstandard2.1dll is not the answer.
There is nothing to do but wait for the unity team to fix it.
