### ISSUE TITLE
System.Text.Json Source Generator name conflicts

### ISSUE THREAD

**Issue by romfir** [dotnet/runtime#58938]
### Description

For class:
```csharp
[JsonSerializable(typeof(Func<Func<int>, int>))]
internal partial class MyJsonContext : JsonSerializerContext
{
}
```
`System.Text.Json` source generator will generate property with name: `FuncFuncInt32Int32`
For `typeof(Func<Func<int, int>>)` the name will be the same and for class like this:
```csharp
[JsonSerializable(typeof(Func<Func<int>, int>))]
[JsonSerializable(typeof(Func<Func<int, int>>))]
internal partial class MyJsonContext : JsonSerializerContext
{
}
```
the generator fails to produce any output.

### Configuration

dotnet --version
`6.0.100-preview.7.21379.14`

**Comment by layomia** [comment]
[`JsonSerializableAttribute.TypeInfoPropertyName`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonserializableattribute.typeinfopropertyname?view=net-6.0#System_Text_Json_Serialization_JsonSerializableAttribute_TypeInfoPropertyName) exists to help resolve potential conflicts between generated property names. 

Can you trying setting a custom name for one of the generated `JsonTypeInfo<T>` property names:

```cs
[JsonSerializable(typeof(Func<Func<int>, int>))]
[JsonSerializable(typeof(Func<Func<int, int>>), TypeInfoPropertyName = "FuncOfFunc")]
internal partial class MyJsonContext : JsonSerializerContext
{
}
```

**Comment by romfir** [comment]
> [`JsonSerializableAttribute.TypeInfoPropertyName`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonserializableattribute.typeinfopropertyname?view=net-6.0#System_Text_Json_Serialization_JsonSerializableAttribute_TypeInfoPropertyName) exists to help resolve potential conflicts between generated property names.
> 
> Can you trying setting a custom name for one of the generated `JsonTypeInfo<T>` property names:
> 
> ```cs
> [JsonSerializable(typeof(Func<Func<int>, int>))]
> [JsonSerializable(typeof(Func<Func<int, int>>), TypeInfoPropertyName = "FuncOfFunc")]
> internal partial class MyJsonContext : JsonSerializerContext
> {
> }
> ```

It works when I manually set prop name via `TypeInfoPropertyName`, but this feels like a workaround, there should be at least some diagnostic error that the developer can use this property to set a name, instead source gen does not output anything

**Comment by layomia** [comment]
We do issue a diagnostic if we detect a collision:

```
CSC : error SYSLIB1031: There are multiple types named FuncFuncInt32Int32. Source was generated for the first one detected. Use 'JsonSerializableAttribute.TypeInfoPropertyName' to resolve this collision. [D:\repos\dotnet_runtime\src\libraries\System.Text.Json\tests\System.Text.Json.SourceGeneration.Tests\System.Text.Json.SourceGeneration.Tests.csproj]
```

**Comment by eiriktsarpalis** [comment]
Related to #58198.

**Comment by layomia** [comment]
Closing this issue per https://github.com/dotnet/runtime/issues/58938#issuecomment-917004832. There's no standard for resolving name clashes, so it is better for the developer resolve them.
