### ISSUE TITLE
Test failure CurrencyNegativePattern_Get_ReturnsExpected_ByLocale in macOS 12 beta 8

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#58944]
Using macOS 12 beta 8, this test fails:

```
[xUnit.net 00:00:02.25]     System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(locale: "es-BO") [FAIL]
  Failed System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(locale: "es-BO") [25 ms]
  Error Message:
   Assert.Contains() Failure
Not found: 12
In value:  Int32[] [1]
  Stack Trace:
     at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(String locale) in /Users/kjones/Projects/dotnet/runtime-main/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyNegativePattern.cs:line 56
```

<details>
<summary>dotnet --info</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21430.12
 Commit:    2b28e04218

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /Users/kjones/Projects/dotnet/runtime-main/.dotnet/sdk/6.0.100-rc.1.21430.12/
</details>

**Comment by EgorBo** [comment]
@vcsjones what version of ICU macOS 12b8 is bundled with? `uconv -V`

**Comment by vcsjones** [comment]
@EgorBo I don't think macOS ships with `uconv -V` out of the box, but after doing some poking it looks like 68.2.

**Comment by tarekgh** [comment]
I looked at that, Mac Monterey is using ICU version `68.2` but looks it is Apple specific customized ICU which at least different than the one on Windows 11 which has the same version. I think we can just fix the test.
