### ISSUE TITLE
[JIT] Asm difference for F# and C# methods

### ISSUE THREAD

**Issue by En3Tho** [dotnet/runtime#58941]
I'm not sure whether this might be JIt imporvement or F#.. Basically I will duplicate this in fsharp repo (https://github.com/dotnet/fsharp/issues/12138) too.

Consider these 2 methods:

``` fsharp
[<MethodImpl(MethodImplOptions.AggressiveInlining)>]
let fold initial folder (enumerator: #IEnumerator<'i>) =
    let folder = OptimizedClosures.FSharpFunc<_,_,_>.Adapt folder
    let mutable enumerator = enumerator
    let mutable result = initial
    while enumerator.MoveNext() do
        result <- folder.Invoke(result, enumerator.Current)
    result
```

``` csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static TResult Fold<TResult, TItem, TEnumerator>(TResult result, FSharpFunc<TResult, FSharpFunc<TItem, TResult>> folder, TEnumerator enumerator)
            where TEnumerator : IEnumerator<TItem>
{
    var fSharpFunc = OptimizedClosures.FSharpFunc<TResult, TItem, TResult>.Adapt(folder);
    var enumerator2 = enumerator;
    var result2 = result;
    while (enumerator2.MoveNext())
        result2 = fSharpFunc.Invoke(result2, enumerator2.Current);

    return result2;
}
```

They look very similar but there is an importnat il emit difference:

C# method is compiled to this basically:

``` csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static TResult FoldRoslynVersion<TResult, TItem, TEnumerator>(TResult result, FSharpFunc<TResult, FSharpFunc<TItem, TResult>> folder, TEnumerator enumerator)
            where TEnumerator : IEnumerator<TItem>
{
    var fSharpFunc = OptimizedClosures.FSharpFunc<TResult, TItem, TResult>.Adapt(folder);
    var enumerator2 = enumerator;
    var result2 = result;
    goto movenext;

    logic:
    result2 = fSharpFunc.Invoke(result2, enumerator2.Current);

    movenext:
    if (!enumerator2.MoveNext())
        return result2;

    goto logic;
}
```

While F# is compiled to this basically:
``` csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static TResult FoldFSharpVersion<TResult, TItem, TEnumerator>(TResult result, FSharpFunc<TResult, FSharpFunc<TItem, TResult>> folder, TEnumerator enumerator)
            where TEnumerator : IEnumerator<TItem>
{
    var fSharpFunc = OptimizedClosures.FSharpFunc<TResult, TItem, TResult>.Adapt(folder);
    var enumerator2 = enumerator;
    var result2 = result;

    movenext:
    if (!enumerator2.MoveNext())
        goto exit;

    result2 = fSharpFunc.Invoke(result2, enumerator2.Current);
    goto movenext;

    exit:
    return result2;
}
```

While difference might be non obvious, C# version with condition at the end of the method results in 10-15% perf imporvement while having the same assembly size.

![image](https://user-images.githubusercontent.com/37334640/132863701-02b976aa-4819-456a-883c-ee887ecddee8.png)

Can JIT compiler regonize these patterns better and ideally emit the same code for both variants?

category:cq
theme:loop-opt
skill-level:expert
cost:large
impact:large

**Comment by EgorBo** [comment]
@BruceForstall a loop optimization for you I guess:
```csharp
static void Test()
{
start:
    if (Cond())
    {
        DoWork();
        goto start;
    }
}
```
should be transformed into the same as:
```csharp
static void Caller2()
{
    goto condition;
start:
    DoWork();
condition:
    if (Cond())
        goto start;
}
```
it might make code a bit bigger but loop body will be more efficient.

**Comment by EgorBo** [comment]
Proof that Roslyn does it:
![image](https://user-images.githubusercontent.com/523221/132865783-07b39e1d-4537-4752-8eaa-590fb741a287.png)

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/132869682-c6f48c9a-8e93-4108-bc3e-187e862dea99.png)

**Comment by BruceForstall** [comment]
The F# generated IL doesn't match the patterns the JIT looks for to do loop inversion or loop recognition, so the loop doesn't get added to our loop table for consideration for future optimization. We do mark the blocks with loop weights because we use a different logic for determining that.

Fixing this is part of a more general task to improve RyuJIT loop recognition.

**Comment by jakobbotsch** [comment]
Fixed by PRs listed in https://github.com/dotnet/runtime/issues/93144#issuecomment-1853750565

**Comment by En3Tho** [comment]
@jakobbotsch Thank you!
