### ISSUE TITLE
[API Proposal]: System.Collections.Generic.SortedList<TKey, TValue> should have SetByIndex(Int32,TValue)

### ISSUE THREAD

**Issue by rhaokiel** [dotnet/runtime#58962]
### Background and motivation

There is no way to set the value of an entry by index in the generic [`SortedList<TKey, TValue>`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections/src/System/Collections/Generic/SortedList.cs) like there is in the [non-generic version](https://github.com/dotnet/runtime/blob/3de64689ebb56f55da3c0acfeb3a572c9ef207af/src/libraries/System.Collections.NonGeneric/src/System/Collections/SortedList.cs#L552). This causes code to incur a BinarySearch cost (log n) to set the value when the index is already known.

I'm rather surprised nobody has mentioned this here even though there is interest over on [StackOverflow](https://stackoverflow.com/questions/44292800/setbyindex-equivalent-for-system-collections-generic-sortedlist) (4 years old).

### API Proposal
(Updated to reflect API Review's conclusions)

```diff
namespace System.Collections.Generic
{
    public class SortedList<TKey, TValue>
    {
+       public TKey GetKeyAtIndex(int index)
-       private TKey GetKey(int index)
        { ... }

+       public TValue GetValueAtIndex(int index)
-       private TValue GetByIndex(int index)
        { ... }

+       public void SetValueAtIndex(int index, TValue value)
+       {
+           if (index < 0 || index >= _size)
+               throw new ArgumentOutOfRangeException(nameof(index), index, SR.ArgumentOutOfRange_Index);
+           values[index] = value;
+           version++;
+       }
```

### Usage Examples

**Allows an overriding class to handle complicated scenarios**
Such as this example in which a binary search must be performed before deciding between a set or remove operation.
```C#
var index = this.IndexOfKey(key);
var newValue = this.Values[index] + incrValue;
if (newValue == 0) // or any condition that can only be decided once the index is known
    this.RemoveAt(index);
else
    this.SetValueByIndex(index, newValue);
```

### Risks

The index of a particular key could change via another thread between acquisition and use. However, none of the other currently implemented methods in `SortedList<TKey, TValue>` take precautions to make the class thread-safe.

**Comment by eiriktsarpalis** [comment]
Updating the value of a dictionary without specifying the key feels a bit error-prone to me. That being said, I understand the motivation and there is precedent in the non-generic collection. @stephentoub should we be considering this?

**Comment by rhaokiel** [comment]
It might be the practical use of this is only applicable to a class override to further extend the functionality, which is my use case. So maybe `protected` is more appropriate?

**Comment by krwq** [comment]
@rhaokiel ping

**Comment by rhaokiel** [comment]
My apologies for the delay. @eiriktsarpalis, I've updated the proposal to use `protected` as suggested and added an example. Are there any other concerns that need to be discussed?

**Comment by eiriktsarpalis** [comment]
I think this is ok, we can put it up for review.

**Comment by rhaokiel** [comment]
@eiriktsarpalis sure. I'm not very sure on the etiquette though. Do I submit a PR at this point? I believe the following changes would satisfying the approved API:

```diff
namespace System.Collections.Generic
{
    public class SortedList<TKey, TValue>
    {
+       public TKey GetKeyAtIndex(int index)
-       private TKey GetKey(int index)
        { ... }

+       public TValue GetValueAtIndex(int index)
-       private TValue GetByIndex(int index)
        { ... }

+       public void SetValueAtIndex(int index, TValue value)
+       {
+           if (index < 0 || index >= _size)
+               throw new ArgumentOutOfRangeException(nameof(index), index, SR.ArgumentOutOfRange_Index);
+           values[index] = value;
+           version++;
+       }


        public sealed class KeyList : IList<TKey>, ICollection
        {
            public TKey this[int index]
            {
                get
                {
+                    return _dict.GetKeyAtIndex(index);
-                    return _dict.GetKey(index);


        public sealed class ValueList : IList<TValue>, ICollection
        {
            public TValue this[int index]
            {
                get
                {
+                    return _dict.GetValueAtIndex(index);
-                    return _dict.GetByIndex(index);
```

**Comment by eiriktsarpalis** [comment]
Yes feel free to submit a PR, public API diff should match what was approved in https://github.com/dotnet/runtime/issues/58962#issuecomment-941332116

**Comment by stephentoub** [comment]
@eiriktsarpalis, can this be closed now?
