### ISSUE TITLE
[API Proposal]: Add Arm64 to ProcessorArchitecture and ImageFileMachine enums

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#58970]
### Background and motivation

We now support Arm64 as a target architecture, but not all of the various enums that describe Arm64 PE files have been updated to allow for that support. In particular the System.Reflection.ImageFileMachine enum, and the System.Reflection.ProcessorArchitecture enums are missing arm64 implementation.

### API Proposal

```C#
namespace System.Reflection
{
     public enum ImageFileMachine
     {
          ...
          // Note that the name is ALLCAPS here to follow the style of the other existing enum values (I386, IA64, AMD64 and ARM)
          ARM64 = 0xAA64
     }

    public ProcessorArchitecture
    {
        ...
        Arm64 = 6
    }
}
```

### API Usage

The impact of a change to ImageFileMachine should be fairly subtle. It effects the behavior of reading an assembly with the System.Reflection.MetadataLoadContext library. Currently, when an Arm64 assembly is loaded, it is given the `ProcessorArchitecture` of `None` where it should get the new value `Arm64`.

```C#
Console.WriteLine(new AssemblyName("SomeName, ProcessorArchitecture=Arm64").ProcessorArchitecture);
```

The above should print `Arm64` instead of failing with
```
Unhandled exception. System.IO.FileLoadException: The given assembly name or codebase was invalid. (0x80131047)
   at System.Reflection.AssemblyName.nInit()
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at <Program>$.<Main>$(String[] args) in C:\Users\david\source\repos\ConsoleApp6\ConsoleApp6\Program.cs:line 7
```

In addition if an assembly is compiled as targetting Arm64, its `AssemblyName` should have a `ProcessorArchitecture` of `Arm64`.

### Risks

Assembly names are a notoriously complex subject, and changing the processing to report Arm64 instead of None could in theory cause some issues. However, I do not believe that simply adding the new enums is much of a risk, and it does provide the ability for us to fix such issues over time.

**Comment by jkotas** [comment]
These enums are effectively deprecated in .NET Core/5+. .NET Core/5+ runs on ARM64 and Wasm just fine without having the respective values in these enums. These enums are not used for anything relevant anymore. I think it would be better to obsolete them instead.


`AssemblyName.ProcessorArchitecture` is not a proper part of assembly. It does not roundtrip through AssemblyName string representation. It is ignored by the loader in .NET Core. For example, this runs successfully on .NET 6:
```
    var an = new AssemblyName("System.Diagnostics.Process");
    an.ProcessorArchitecture = ProcessorArchitecture.IA64; // IA64 is Itanium
    Console.WriteLine(Assembly.Load(an.FullName)); // IA64 is not included in the full name
    Console.WriteLine(Assembly.Load(an)); // Works fine on .NET Core (fails on .NET Framework)
```
`AssemblyName` type has other similar thumbtacked properties: `AssemblyName.VersionCompatibility`, `AssemblyName.HashAlgorithm` and `AssemblyName.CodeBase`. I think we should obsolete all of them. https://github.com/dotnet/runtime/issues/42857 is opened on obsoleting AsssemblyName.CodeBase.

**Comment by terrajobst** [comment]
Makes sense. Let's not do that then.

**Comment by jkotas** [comment]
> AssemblyName type has other similar thumbtacked properties: AssemblyName.VersionCompatibility, AssemblyName.HashAlgorithm

Opened https://github.com/dotnet/runtime/issues/59061
