### ISSUE TITLE
HTTP/3 without AppContext switch doesn't give descriptive error

### ISSUE THREAD

**Issue by shirhatti** [dotnet/runtime#58971]
### Description

When attempting to use HTTP/3 without setting the `System.Net.SocketsHttpHandler.Http3Support` app context switch, the error isn't sufficiently descriptive.

```
System.Net.Http.HttpRequestException
  HResult=0x80131500
  Message=Requesting HTTP version 3.0 with version policy RequestVersionOrHigher while unable to establish HTTP/3 connection.
  Source=System.Net.Http
```

I incorrectly assumed unable to establish HTTP/3 connection implied the remote server was not reachable.

Can we modify the exception message to indicate this is a configuration issue and not an issue with the remote server? This would have saved me a fair bit of time and I'm sure I'm the only person who'll hit this issue 😅

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21457.2
 Commit:    1aefb20570

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22455
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21457.2\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  6.0.100-rc.1.21457.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by karelz** [comment]
Triage: Pity we didn't discover it a bit earlier for RC2 (which just forked). We do not think it will be common for people to run into this. Closing.
