### ISSUE TITLE
Parallel.ForEachAsync hits assert when loop body throws OperationCanceledException

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#58981]
When processing loop completion in case of an exception, cancellation exceptions are being filtered out. This can lead to zero exceptions being present.

Repro:

    static async IAsyncEnumerable<int> DummySequence()
    {
        yield return 0;
    }

    ForEachAsync(DummySequence(), 4, TaskScheduler.Default, default, async (item, ct) =>
    {
        throw new OperationCanceledException(ct); //The critical line
    }).Wait();

I noticed that the same issue can happen when the async enumerator itself throws using the cancellation token passed to it. It also can happen with `Enumerator.DisposeAsync()`.

I wonder what would happen if the lock `WaitAsync` throws due to cancellation. That's hard to test so I did not attempt it. I'd assume that it would not lead to the same problem because the wait can only throw in a true cancellation case.

I found this through code review. Otherwise, I found the implementation to be very nice... I tried really hard to break it but it seems that all cases I can think of are handled. I like a lot how new workers are started. They expand like a telescope with the last one initiating the next one only when needed.

I'm not sure how to resolve this. Maybe, cancellation exceptions should simply be present in the final `AggregateException`? Sometimes, we need to debug given only the exception from a production error notification. Any information present there can only help.

@stephentoub

**Comment by skyoxZ** [comment]
I'm curious if it's normal to `throw new OperationCanceledException(ct)` without ensuring `ct.IsCancellationRequested`

**Comment by stephentoub** [comment]
> I'm curious if it's normal to throw new OperationCanceledException(ct) without ensuring ct.IsCancellationRequested

It's not

**Comment by danmoseley** [comment]
Maybe in debug builds that constructor should assert ct.IsCancellationRequested so we know at least we aren't doing this in paths our tests run.
