### ISSUE TITLE
Backport `UseConsoleLifetime()` fix from net6 to net5.

### ISSUE THREAD

**Issue by williamdenton** [dotnet/runtime#59014]
### Description

As discussed in https://github.com/dotnet/runtime/issues/51221, `UseConsoleLifetime()` on `HostBuilder` is broken in net5 unless there is tty attached.

In docker there is no tty by default, so `docker stop` will kill the container and the graceful shutdown will not be triggered in dotnet. This is particularly impactful for `IHostedService` which has an expectation that `StopAsync()` will be called so it can clean up.

Unless this is backported, Net5 docker apps will not shutdown cleanly. This is probably impacting many users already without them realising. This PR https://github.com/dotnet/runtime/pull/52891  fixes the issue in net6. I believe this should also be back ported to net5 

### Regression?

This is a regressions from netcoreapp3.1, and is fixed in net6.

**Comment by tmds** [comment]
> In docker there is no tty by default, so docker stop will kill the container and the graceful shutdown will not be triggered in dotnet.

`docker stop` uses `SIGTERM` by default which works in .NET 5.

@williamdenton are you overriding the `STOPSIGNAL` in your `Dockerfile`?
What lead you to change the `STOPSIGNAL` to `SIGINT`?

**Comment by williamdenton** [comment]
my apologies, i misinterpreted the logs that log4net was displaying. 

The problem lies with log4net not here. Shutdown is happening gracefully (proven with console.writeline), but log4net is not writing to the console once sigterm is received when in docker. Why is still a mystery, i will open an issue over at  https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore
