### ISSUE TITLE
DateTime.UtcNow Analyzer

### ISSUE THREAD

**Issue by mikadumont** [dotnet/runtime#59012]
Analyzer that suggests DateTime.**UtcNow** whenever DateTime.**Now** is used.

**Comment by tannergooding** [comment]
CC. @tarekgh, does this sound like something we should move forward on/around?

**Comment by Clockwork-Muse** [comment]
.... and/or what happens if we ever get a clock, as proposed in #36617 (since then the recommendation would be to usually get the time from the clock, as opposed to the static property).

**Comment by tarekgh** [comment]
I don't think we need to have this analyzer. There is a legitimate use for `DateTime.Now` . Suggesting `DateTime.UtcNow` everywhere wouldn't be good. I will agree only if the analyzer can detect the usage of the result and suggest `DateTime.UtcNow` only in the wrong usage cases.

**Comment by NickCraver** [comment]
@tarekgh What's the harm in having an opt-in analyzer? In some codebases, there's zero legitimate usages and we want to actively prevent that. I've worked on many of these...and we ended up writing an analyzer in the solution.

**Comment by tarekgh** [comment]
I'll be fine if it is opt-in analyzer and not on by default.

**Comment by stephentoub** [comment]
> In some codebases, there's zero legitimate usages and we want to actively prevent that.

Does that really need a specific analyzer?  Couldn't such code bases just add the method to a banned API list?
https://github.com/dotnet/roslyn-analyzers/tree/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers

**Comment by ufcpp** [comment]
I think the biggest problem with `DateTime` is that the cast operator converts "DateTime" with `Unspecified` kind to `DateTimeOffset` as `Local` kind.

```cs
// There is no problem with Utc and Local.
DateTimeOffset fromUtc = new DateTime(2022, 1, 1, 0, 0, 0, DateTimeKind.Utc);
Console.WriteLine(fromUtc); // 2022/01/01 0:00:00 +00:00

DateTimeOffset fromLocal = new DateTime(2022, 1, 1, 0, 0, 0, DateTimeKind.Local);
Console.WriteLine(fromLocal); // 2022/01/01 0:00:00 +09:00 in Japanese Locale

// Unspecified frequently cause problems.
// I'd like this to be banned.
DateTimeOffset fromUnspecified = new DateTime(2022, 1, 1, 0, 0, 0, DateTimeKind.Unspecified);
Console.WriteLine(fromUnspecified); // same as Local

DateTimeOffset misused = fromUtc.DateTime;
Console.WriteLine(misused); // 2022/01/01 0:00:00 +09:00! - undesirable in many case, IMO
```

Should `operator DateTimeOffset(DateTime dateTime)` be unconditionallly banned? or banned only when `DateTime` has `Unspecified` kind? The banned API list is sufficient for the formater but not for the latter?

**Comment by Clockwork-Muse** [comment]
>// Unspecified frequently cause problems.
>// I'd like this to be banned.

Just ban `DateTimeKind.Unspecified`?  It's going to cause problems in places other than the conversion operator.  Some of those uses may show up during runtime, though, which an analyzer wouldn't be able to catch either.

Although if you're doing a lot of work where `Unspecified` would show up a lot, you're probably better off using NodaTime (because you're dealing with other timezones).

**Comment by NickCraver** [comment]
> > In some codebases, there's zero legitimate usages and we want to actively prevent that.
> 
> Does that really need a specific analyzer? Couldn't such code bases just add the method to a banned API list? [https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md?rgh-link-date=2022-09-10T02%3A06%3A21Z)

Nope - I wasn't even aware of this and it didn't exist when we went to solve this problem. I agree that's an excellent solution to the problem, thanks for the pointer!

**Comment by tarekgh** [comment]
> Does that really need a specific analyzer? Couldn't such code bases just add the method to a banned API list?

DateTime.Now has a legitimate usage and I don't think we need to add it to the banned API list. Imagine you have UI app that wants to show the current time? There are more scenarios for DateTime.Now too.

> Should operator DateTimeOffset(DateTime dateTime) be unconditionallly banned?

We have the discussion in the issue https://github.com/dotnet/runtime/issues/32954 which talking about that. It makes sense adding the implicit operator `DateTimeOffset(DateTime dateTime)` to the banned list.

**Comment by NickCraver** [comment]
@tarekgh The banned API list is user opt-in per project or solution for ones _they_ want to ban, it's not a global change to the framework.

**Comment by tarekgh** [comment]
Thanks @NickCraver. What is not clear to me if we have a ready to use banned list file for users to use? If users create their own file and add the API to it, then I am fine with that.

**Comment by stephentoub** [comment]
> users create their own file and add the API to it

Correct.

**Comment by tarekgh** [comment]
Thanks @stephentoub. Per that I am closing this issue. Please let me know if anyone wants to discuss more and I can re-open the issue.

**Comment by ufcpp** [comment]
> Just ban DateTimeKind.Unspecified?

I use at least `default(DateTime)` and `DateTimeOffset.Date` - whose `Kind` is `Unspecified`.
