### ISSUE TITLE
New rule suggestion: Warn against using Uri as a key

### ISSUE THREAD

**Issue by IgorMilavec** [dotnet/runtime#59011]
### Describe the problem you are trying to solve

I just got burned by using System.Uri as a key in a Dictionary containing *pre-authenticated* protocol clients. Turns out System.Uri doesn't include user information when comparing objects (as dully documented [here](https://docs.microsoft.com/en-us/dotnet/api/system.uri.equals?view=net-5.0#remarks)). Meaning I just got back protocol clients for wrong users from the dictionary.... ouch.

I presume that aligning Uri's implementation of equality is out of the question due to legacy compatibility. That's why I propose to create an analyzer rule that would warn callers of possible consequences of using Uri in described manner.

### Describe suggestions on how to achieve the rule

Any generic collection where System.Uri is used as a key type should be flagged as possibly problematic.
At least Dictionary, HashSet and SortedDictionary, ConcurrentDictionary come to mind.

**Comment by karelz** [comment]
Triage: We expect that the code analyzer will have mostly false positives as most people don't use User Info. As such, it will create noise and defeat the purpose.
If we have more people running into this, we can revisit, but it seems rare as it is first report in years.
Closing for now. We can reopen later if there is more impact info.
