### ISSUE TITLE
[mono] Hard-coded path to Xcode

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#59022]
The build system is hard-coding Xcode path:

https://github.com/dotnet/runtime/blob/206dba75f00e67c839709e0632b22819329d73d0/src/mono/mono.proj#L44

On my system the path does not exist since I only have the Xcode beta installed. This should ideally use `xcrun` instead, or worse `xcode-select -p` as alternative. Note that getting the path manually breaks some advanced overrides through environment variables so `xcrun` is definitely preferred.

**Comment by directhex** [comment]
This was largely addressed in e7312999cad2, the hardcoded Xcode path is now a fallback only.
