### ISSUE TITLE
System.Threading.Tasks.Extensions: Missing net standard 2.1 type forwarders in Nuget Package

### ISSUE THREAD

**Issue by simonferquel** [dotnet/runtime#59021]
### Description

System.Threading.Tasks.Extensions brings ValueTask to .net standard 2.0 libraries. This is pretty cool. 
When Building a .net 5.0 app or library, and depending directly or indirectly on System.Threading.Tasks.Extensions package, you get a dll forwarding `System.ValueTask, System.Threading.Tasks.Extension to the implementing type within .Net 5.0 BCL.

However, this is not the case when building a .net standard 2.1 library. This can lead into issues like Ambiguous Type errors at compile type. As an example, imaging:
- Nuget Package Foo is a package only built for .net standard 2.0, It depends on System.Threading.Tasks.Extensions to expose public symbols of type ValueTask
- I want to write a Bar .net standard 2.1 library that consumes Foo and that also expose public symbols of type ValueTask.
By default, I get Ambiguous type errors.
We could imagine that using aliased references could be a workaround. But this way, any code depending on both Foo and Bar must deal with 2 different ValueTask and will probably need to duplicate some code to deal with the fact that there are 2 totally different ValueTask types living in the project. This is far from being practical.

### Configuration

This is a problem when building .net standard 2.1 libraries

### Regression?

This can be considered a regression (there is no ambiguous type issues when building .net standard 2.0 libraries)

### Other information

Discovered while prototyping upgrade of some internal Unity tooling that needs to be compiled as .net standard 2.1 (need to be loadable both from .net 5 and latest Mono while bringing access to System.Span, ValueTask etc.). This is thus a real world issue.

**Comment by Jozkee** [comment]
@simonferquel do you have a small repro of what you are describing? if I understand correctly you are saying that projects that are netstandard2.1 or >= net5.0 that have a dependency on a netstandard2.0 project that exposes a ValueTask member are broken. I tried that locally but didn't get any build errors.

@danmoseley is there an specific area that deals with nuget package issues or is it responsibility of each area owner?

**Comment by danmoseley** [comment]
> @danmoseley is there an specific area that deals with nuget package issues or is it responsibility of each area owner?

It could be infrastructure-libraries, but I suggest to figure out what's going on first.

**Comment by simonferquel** [comment]
I figured out that what was missing is actually a combination of smarts happening with Nuget and .net standard 2.1 compatible targets that was missing in my build script:
- Somehow when building a .net standard 2.1 library that references some well known nuget packages, the package reference is replaced by a reference to a compat shim dll (happens with System.Threading.Tasks.Extensions, System.Memory etc.).
This shim dll is a reference assembly that consists entirely of typeforwards to .net standard 2.1 types.

Those shims are not deployed when publishing the ultimate .net 5 project (they are reference assemblies, that is expected) and at runtime they are replaced by facade assemblies with a matching name provided by the runtime, that does type forward to the concrete types.

Can you confirm I figured things correctly ? - unfortunately due to some legacy systems we can't use nuget package references in the current context.
Also, I was originally misled by the fact Microsoft.Bcl.AsyncInterfaces handles things differently, with the package itself containing a .net standard 2.1-specific implementation that forwards to netstandard.dll.

**Comment by stephentoub** [comment]
It sounds like the issue was resolved, and the last message is from a year and a half ago, so I'm going to close it.  If there's still a problem, please feel free to re-open with more details.  Thanks.
