### ISSUE TITLE
HashSet<T> take out extra element during 'foreach'

### ISSUE THREAD

**Issue by alet** [dotnet/runtime#59026]
In class contain HashSet<T> element 'foreach' output extra element. The MWE in attach

% dotnet --version
3.1.412
% uname -a
Linux workstation 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[MWE.zip](https://github.com/dotnet/runtime/files/7153221/MWE.zip)

**Comment by En3Tho** [comment]
It's expected. You have 2 items in hashset1 thus you print it's items 2 times.

**Comment by alet** [comment]
But why? I enumerate objects on first level only

**Comment by alet** [comment]
Oh! I see, mistype. It should be 'Console.WriteLine(string.Join(" ", j));' and it works as expected.

But there is a bug in my program related. I'll try understand.

**Comment by EgorBo** [comment]
@alet can this issue be closed then?

**Comment by alet** [comment]
I don't sure. Is it better possible open new ticket or wait with this issue until resolve bug in my program

**Comment by stephentoub** [comment]
Please open a new issue if you have a new repro demonstrating an issue with the type. Thanks.
