### ISSUE TITLE
MemoryCache stopped working in 5.0.0

### ISSUE THREAD

**Issue by eocron** [dotnet/runtime#59025]
### Description

MemoryCache.CreateEntry not creating anything in cache.

### Configuration

Windows 10
.net 50
NUnit project
Microsoft.Extensions.Caching.Memory 5.0.0 from nuget

### Other information

        [Test]
        public async Task CacheTest()
        {
            var cache = new MemoryCache(new MemoryCacheOptions());
            cache.CreateEntry("foo").SetValue("bar").SetAbsoluteExpiration(TimeSpan.FromSeconds(100));
            string result;
            Assert.IsTrue(cache.TryGetValue("foo", out result)); //this will fail
        }

**Update 1:**

Looking in decompiled code I see it requires for entry to be disposed. Is there some reason why it doesn't have more explanatory Commit/Apply/Configure+Build methods?
Also, no documentation has been found by me for this one.

**Comment by huoyaoyuan** [comment]
You can use extension method `Set` from `CacheExtensions`:


```csharp
cache.Set("foo", "bar", TimeSpan.FromSeconds(100));
```

`CreateEntry` isn't friendly for direct usage. Use the extension methods.

**Comment by eerhardt** [comment]
> Looking in decompiled code I see it requires for entry to be disposed.

This is correct. It was not an ideal design from the start, but since it has shipped for multiple versions, we can't make a breaking change any longer.

See https://github.com/dotnet/runtime/issues/36556

Using the extensions methods, as @huoyaoyuan points out, is the best option.
