### ISSUE TITLE
`*Operators` interfaces naming

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#59030]
```
IAdditionOperators
IDivisionOperators 
IMultiplyOperators
ISubtractionOperators
```
It seems like we should have `IMultiplicationOperators` instead of `IMultiplyOperators`

Same for `IUnaryNegationOperators` and `IUnaryPlusOperators` but I don't have a better suggestion.

**Comment by tannergooding** [comment]
> It seems like we should have IMultiplicationOperators instead of IMultiplyOperators
>
> Same for IUnaryNegationOperators and IUnaryPlusOperators but I don't have a better suggestion.

API review already looked at this and selected the current naming convention based on the underlying IL name of the operators. This was done to be the most "cross language" compatible and to remove most ambiguity.
Some of the names are indeed less nice than others, and not all of the map 1-to-1 with the naming that you might encounter in a given languages docs (such as `op_Modulus`, where C# calls it the `remainder` instead).

**Comment by alrz** [comment]
>Some of the names are indeed less nice than others, and not all of the map 1-to-1 with the naming that you might encounter in a given languages docs 

I didn't mean this should follow names from some other place, I'm saying they are not consistent with each other.

**Comment by alrz** [comment]
>API review already looked at this and selected the current naming convention based on the underlying IL name of the operators.\

Fair enough.

**Comment by alrz** [comment]
Somehow I managed to run a github action by closing this issue? 

https://github.com/dotnet/runtime/actions/runs/1230442242
https://github.com/dotnet/runtime/actions/runs/1230442696

**Comment by tannergooding** [comment]
> I'm saying they are not consistent with each other.

Right, this is just an inconsistency with the IL naming. I'll raise it when we take the next look at the feature, but I'm not positive we'll actually see a change here.
