### ISSUE TITLE
Order of serialized properties determined by dictionary enumeration on fast-path source generators

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#59043]
Currently, the fast-path source generator will use the [`TryFilterSerializableProps` method](https://github.com/dotnet/runtime/blob/ad0c3618e4e901f4cd4874553d1937180923f37e/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L806) to determine the properties that are serializable. The results are returned as a dictionary, [which the source generator will enumerate in order to emit the relevant logic](https://github.com/dotnet/runtime/blob/ad0c3618e4e901f4cd4874553d1937180923f37e/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L832).

Note that dictionary enumeration [does not provide any guarantees on ordering](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.valuecollection?view=net-5.0#remarks), as such it is likely that this could end up not honoring the desired serialization order (e.g. as specified by the `JsonPropertyOrderAttribute`). That being said, the current implementation of System.Collections.Generic.Dictionary _happens to_ preserve ordering due to an implementation detail that may well change in the future. We should update the `TryFilterSerializableProps` method to provide more robust guarantees on property ordering.

**Comment by eiriktsarpalis** [comment]
Given that the source generator targets `netstandard2.0`, for the 6.0 release we might want to check if this is honored in older implementations of Dictionary, up to and including the netfx implementation.

**Comment by danmoseley** [comment]
I wonder whether when built in DEBUG we should have our dictionary randomize its enumeration. Long ago, before string hash codes were randomized by default, the libraries used to randomize string hashcodes (XOR them with the build number or similar) in DEBUG only.

**Comment by GSPP** [comment]
@danmoseley I have worked on a large application that relied on `Dictionary` usually being ordered in about 1000 places... I am a fan of intentionally breaking behavior that is not guaranteed but I think that really has to happen in v1 or else it's an upgrade pain.

**Comment by danmoseley** [comment]
@GSPP in general no framework can reasonably guarantee undefined behavior, post v1 or not. It so heavily constrains maintenance, perf improvements, etc. As well we do not test such behavior - so we do not necessarily know when it changes - nor necessarily know that anyone depends on it.  That may turn up much later when the product is in servicing mode. We have seen the result of this in .NET Framework where callers even depended on details of timing to the extent performance improvements caused breaks and had to be reverted later. .NET Core introduced SxS deployment to give more freedom to make improvements like this. 

There can always be exceptions where something is so widely assumed in the ecosystem that it is best to document it. I do not have the data to guess whether this is the case here or not but my guess is that it is unlikely.

**Comment by eiriktsarpalis** [comment]
Moving to Future, as we won't have time to work on this.
