### ISSUE TITLE
Obsolete thumbtacked AssemblyName properties 

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#59061]
### Background and motivation

AssemblyName has number of properties that are not proper part of assembly name. They do not not roundtrip through AssemblyName string representation and they are ignored by the assembly loader in .NET Core. They should be obsoleted.

### API Proposal

```diff
    public sealed partial class AssemblyName
    {
        public System.Configuration.Assemblies.AssemblyHashAlgorithm HashAlgorithm
        {
+           [Obsolete("AssemblyName.HashAlgorithm has been deprecated and is not supported.")]
            get;
+           [Obsolete("AssemblyName.HashAlgorithm has been deprecated and is not supported.")]
            set;
        }
        public System.Reflection.ProcessorArchitecture ProcessorArchitecture
        {
+           [Obsolete("AssemblyName.ProcessorArchitecture has been deprecated and is not supported.")]
            get;
+           [Obsolete("AssemblyName.ProcessorArchitecture has been deprecated and is not supported.")]
            set;
        }
        public System.Configuration.Assemblies.AssemblyVersionCompatibility VersionCompatibility
        {
+           [Obsolete("AssemblyName.VersionCompatibility has been deprecated and is not supported.")]
            get;
+           [Obsolete("AssemblyName.VersionCompatibility has been deprecated and is not supported.")]
            set;
        }
    }
```     

### API Usage

```C#
var an = new AssemblyName("System.Diagnostics.Process");
an.ProcessorArchitecture = ProcessorArchitecture.IA64; // IA64 is Itanium
Console.WriteLine(an.FullName); // IA64 is not included in the full name
Console.WriteLine(Assembly.Load(an)); // Works fine, requested ProcessorArchitecture is ignored
```

**Comment by vitek-karas** [comment]
Would there be some replacement for functionality like:

```C#
Assembly asm = Assembly.GetAssemblyName(path);
Console.WriteLine(asm.ProcessorArchitecture);
```

Specifically the architecture can be rather useful to get like this. The GetAssemblyName effectively exposes the PE/managed header parser from the runtime to the managed world. The code above does not load the assembly, and it's relatively efficient.

Just trying to add context for cases where the obsoleted properties can be useful.

**Comment by jkotas** [comment]
> Assembly asm = Assembly.GetAssemblyName(path);
> Console.WriteLine(asm.ProcessorArchitecture);

Use `System.Reflection.Metadata`. `System.Reflection.Metadata` is full featured PE parser. We have been recommending to use `System.Reflection.Metadata` for all situations where `Assembly.GetAssemblyName` is missing features or where it is not fast enough, e.g. https://github.com/dotnet/runtime/issues/21785#issuecomment-655161523

**Comment by bartonjs** [comment]
Looks good as proposed (though we moved the obsoletions to the properties instead of the accessors

```diff
    public sealed partial class AssemblyName
    {
+       [Obsolete("AssemblyName.HashAlgorithm has been deprecated and is not supported.", DiagnosticId = next available)]
        public System.Configuration.Assemblies.AssemblyHashAlgorithm HashAlgorithm { get; set; }
+       [Obsolete("AssemblyName.ProcessorArchitecture has been deprecated and is not supported.", DiagnosticId = same as above)]
        public System.Reflection.ProcessorArchitecture ProcessorArchitecture { get; set; }
+       [Obsolete("AssemblyName.VersionCompatibility has been deprecated and is not supported.", DiagnosticId = same as above)]
        public System.Configuration.Assemblies.AssemblyVersionCompatibility VersionCompatibility { get; set;}
    }
```

**Comment by Forgind** [comment]
@jkotas, I had some trouble figuring out how to get architecture out of System.Reflection.Metadata and had trouble finding a relevant example on GitHub. Could you link to somewhere someone did it? Thanks!

**Comment by jkotas** [comment]
@Forgind We do not respond to comments on old closed PRs and issues. If it is still a problem, open a new [discussion]( https://github.com/dotnet/runtime/discussions) or [issue](https://github.com/dotnet/runtime/issues)
