### ISSUE TITLE
Hosting .NET Core using nethost and hostfxr - Finding nethost.dll on client machine

### ISSUE THREAD

**Issue by lissity** [dotnet/runtime#59082]
I have some questions about the linking with nethost.lib and nethost.dll.
Let's say I have an application that is hosting the .NET Core runtime. I can link with nethost.lib when building but nethost.dll needs to be located at runtime. If moving my application to a client's machine (where the path to nethost.dll could be different as well as the version) how should nethost.dll be found? 

What would the best practice be in this case?

**Comment by vitek-karas** [comment]
The recommendation is to ship `nethost` with your app. You can either use dynamic library or you can statically link `nethost` to your application. The package contains `nethost.dll`/`nethost.lib` (the dynamic library) and `libnethost.lib` (the static library) on Windows and `libnethost.so` (the dynamic library) and `libnethost.a` (the static library) on Linux (and similar on other platforms).

**Comment by lissity** [comment]
My application that hosts .NET is in a directory that is added to the path. This means that the nethost.dll will also be exposed in the path. I am afraid that this may affect applications that are already installed since they may also have (another) nethost.dll (possibly with a different version) in the path. Any suggestions how I should handle this?

**Comment by vitek-karas** [comment]
In that case statically linking the `nethost` into your app seems like the best solution. There will be no additional file on disk, the code will become part of your native host app.

**Comment by lissity** [comment]
Thank you for the help!
