### ISSUE TITLE
Add `DateOnly` and `TimeOnly` string body parameter support

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#59118]
### Describe the bug
When using `DateOnly` or `TimeOnly` as parts of request body, ASP.NET expects `string` to be passed, but throws

```
Serialization and deserialization of 'System.DateOnly'/'System.TimeOnly' instances are not supported and should be avoided.
```

when it is. Passing `DateTime` as string (eg. `"2021-09-14T21:10:54.798Z"`) works just fine, so how is `DateOnly` and `TimeOnly` less secure?

### To Reproduce

- Create action with `DateOnly` or `TimeOnly` parameter, or add `DateOnly` or `TimeOnly` property to a request model.
- Send a request to said action, and specify `DateOnly` value as `"2021-09-14"`, or `TimeOnly` value as `"10:54"` (just random values to demonstrate needed format).

### Exceptions (if any)

`NotSupportedException` mentioned above.

### Further technical details
- ASP.NET Core .NET 6 RC1
- IDE: VS 2022 Preview 4.0

Related to: 
- https://github.com/dotnet/runtime/issues/41920
- https://github.com/dotnet/aspnetcore/issues/36511

### Workaround

```cs
builder.Services.AddControllers()
        .AddJsonOptions(options =>
        {
            options.JsonSerializerOptions.Converters.Add(new DateOnlyJsonConverter());
            options.JsonSerializerOptions.Converters.Add(new TimeOnlyJsonConverter());
        });

...

public sealed class DateOnlyJsonConverter : JsonConverter<DateOnly>
{
    public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return DateOnly.Parse(reader.GetString()!);
    }

    public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
    {
        var isoDate = value.ToString("O");
        writer.WriteStringValue(isoDate);
    }
}

public sealed class TimeOnlyJsonConverter : JsonConverter<TimeOnly>
{
    public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return TimeOnly.Parse(reader.GetString()!);
    }

    public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
    {
        var isoTime = value.ToString("O");
        writer.WriteStringValue(isoTime);
    }
}
```

**Comment by wzchua** [comment]
See https://github.com/dotnet/runtime/issues/53539

**Comment by GrabYourPitchforks** [comment]
Dupe of https://github.com/dotnet/runtime/issues/53539.

**Comment by maxkoshevoi** [comment]
My concern is more about ASP.NET than serialization of those types. Since #53539 won't make it into .NET 6, does this mean that for a year there won't be an out of the box way to use `DateOnly` and `TimeOnly` in ASP.NET API?

**Comment by eiriktsarpalis** [comment]
The exception message being thrown in RC1 contained confusing messaging and has since been updated in #58775 (see [relevant change](https://github.com/dotnet/runtime/pull/58775/files#diff-f343f56e41ad406150ed9d35e7548f0d118dd3038c57dff2ff309e5e96331091R495)). TL;DR the `UnsupportedTypeConverter` was initially constrained to types whose deserialization is associated with security issues but has since expanded its scope with a relevant change to its error message.

That also means `DateOnly` and `TimeOnly` won't be support OOB in .NET 6. You can work around this by specifying custom converters for the types.

Closing as duplicate of #53539.

**Comment by maxkoshevoi** [comment]
Got it. Created a NuGet to add support for them in body and query argiments: https://www.nuget.org/packages/DateOnlyTimeOnly.AspNet
