### ISSUE TITLE
Uncorrect output on my PC on C# language

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59125]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Uncorrect-output-on-my-PC-on-C-language/1490573)._

---
**[ENG]** Hello! When I launch my code on C# language, the output becomes 314,15999999999997 like on my screenshot. It's very strange because my program just calculate 10.0*10.0*3.1416 and I thought that output would be 314.16. I also launch my program with numbers 10.0*10.0*3.141 (result was 314.1) and 10.0*10.0*3.14159 (result was 314.159). I also calculated 10.0*10.0*3.1416 with online-compilator to compare the output with my visual studio result and i got 314.16 (you can see it on my second screenshot). Question: why is my computer outputting 314.15999999999997 instead of 314.16?
**[RUS]** Здравствуйте! Я запускаю свой код на C# языке, выводится результат 314,15999999999997 как на моём первом скриншоте. Это очень странно, потому что моя программа подсчитывает произведение 10.0*10.0*3.1416 и я думал, что вывод будет 314.16. Я также запустил свою программу с числами 10.0*10.0*3.141 (результат был 314.1) и 10.0*10.0*3.14159 (результат был 314.159). Помимо этого я посчитал 10.0*10.0*3.1416 с помощью онлайн-компилятора, чтобы сравнить вывод с результатом в visual studio, и я получил 314.16 (вы можете видеть это на моём втором скриншоте. Вопрос: почему мой компьютер выводит 314,15999999999997 вместо 314.16?
! [изображение.png] (https://aka.ms/dc/image?name=B7fc11b30e3ce46af89cc8b9dc7f4deca637631711211634511_20210729-185839-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png&tid=7fc11b30e3ce46af89cc8b9dc7f4deca637631711211634511)
! [изображение.png] (https://aka.ms/dc/image?name=B46b466dd746c447387aa8a63a268e9d7637631711362230563_20210729-185854-%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png&tid=46b466dd746c447387aa8a63a268e9d7637631711362230563)

---
#### Alison Jin [MSFT] on 7/29/2021, 08:03 PM: 

<p>Thank you for your feedback! Does this reproduce for all project or specific project? If it’s reproduce with the specific project, could you please provide a sample solution that has this problem so that we can conduct further research? It would be very helpful if you could provide some screenshots of this issue. Thanks for your help!</p>
<p>We look forward to hearing from you!</p>

#### Левон Хорасанджян on 8/3/2021, 10:06 AM: 

(private comment, text removed)
#### Feedback Bot on 8/8/2021, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mburbea** [comment]
Not an issue. Welcome to ieee754. 
The formula in question appears to be `10.0 * 10.0 * 3.1416`. (You can even simplify it to `100 * 3.1416`) and you will get the same result.  You can try this in your browser's console and you will also get the same result. So it's not C# here but how the doubles are represented. 

Now for some mind bending stuff `3.1416 * 100` does indeed produce the expected output of `314.16`. Because floating point multiplication is non-associative.

**Comment by danmoseley** [comment]
@mburbea is correct. this is how floating point math works.

Most likely what you want is to format the double to a limited number of decimal places. There are detailed explanations herE:
https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/
https://docs.microsoft.com/en-us/dotnet/api/system.double.tostring?view=net-5.0

If you actually want a higher precision result, you will need to use some specialized math package instead.
