### ISSUE TITLE
Process.Start doesn't work in . Net5

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59124]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/ProcessStart-doesnt-work-in-Net5/1494751)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:Worked in .Net Framework, not in .Net 5]
I have been able to use System.Diagnostics.Process.Start(fileName) since version 1 of .Net Framework I think.

Why does this not work in .Net 5? I know the file name exists.

I've tried:

var p = new Process();
                                        
p.StartInfo = new ProcessStartInfo();
{ 
    // Set the working directory
    p.StartInfo.Arguments = outputFileInfo.Directory.FullName;
    p.StartInfo.FileName = fileInfo.FullName;
};
bool started = p.Start();

Or just 

Process.Start(fileName); 

And both do not work.

Is this a known issue, or what changed in .Net Core land?

---
#### Feedback Bot on 8/4/2021, 10:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### CyraxSputnik on 8/17/2021, 08:24 AM: 

<p>It seems that you are not using this property:</p>
<p>Process.Start(new ProcessStartInfo { <strong>UseShellExecute = true</strong>, FileName = fileName });</p>

---
### Original Solutions
(no solutions)

**Comment by adamsitnik** [comment]
As mentioned by @CyraxSputnik in the original issue, the difference between .NET and .NET Core is the default value of `UseShellExecute`

From the [docs](https://docs.microsoft.com/dotnet/api/system.diagnostics.processstartinfo.useshellexecute):

> The default is true on .NET Framework apps and false on .NET Core apps.

If setting it does not help, please reopen the issue.
