### ISSUE TITLE
directory.getfiles does not take advantage of the index

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59126]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/directorygetfiles-does-not-take-advanta/1466897)._

---
On Windows machine, directory.getfiles and .getdirectories with specified search pattern  apparently don't take advantage of the indexing. If I use them on a directory with thousands of files or subdirectories, it may run for minutes, while the search in Windows Explorer is instant provided that this directory is included in Windows Search index. <br><br>To reproduce:<br>1. have a directory with thousands of files<br>2. include it in Windows Search index and let it populate<br>3. in windows explorer, search for a particular file; observe instant results<br>4. search for the same file from the application, using .getfiles. Observe minutes of waiting.<br><br>Note that this also applies to the network shares, i.e. you can search in a directory on a remote network share, and if shared directory is indexed on the server, Windows Explorer search gets instant results on your local machine.

---
#### Mila Zhou[MSFT] on 7/4/2021, 07:44 PM: 

<p>Is this issue related to Visual Studio? Does this reproduce for all project or specific project? If it’s reproduce with the specific project, which project do you use(C# , C++ console, Web,  UWP or others )?  It would be very helpful if you could provide some screenshots of this problem.</p>

#### vrapp on 7/5/2021, 00:48 PM: 

<p>I would say, it’s related to the .Net Framework, or even more specifically, to the implementation of it on Windows platform.</p>
<p>The easiest way to reproduce it probably is in WinForms application, but being part of the runtime, it probably works the same in any project.</p>
<p>Regarding screenshots - I’m not sure how I can provide screenshots showing that something is fast in one scenario and slow in another. Screenshot of the stopwatch showing the time in both cases?</p>

#### Feedback Bot on 7/13/2021, 04:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marie Shi [MSFT] on 7/13/2021, 06:54 PM: 

<p>Hi vrapp,</p>
<p>Thanks for your feedback! In order to investigate this issue in the further, we must reproduce this issue on our side first, so somethings want to confirm with you:</p>
<ol>
<li>You said “The easiest way to reproduce it probably is in WinForms application”, could you describe how to reproduce this issue using winforms application?</li>
<li>Could you please provide detail reproduce steps and simple app for use to reproduce this issue? Also it would be better if you could provide a video to record your issue.</li>
<li>In addition, which OS version and .Net Framework are you using?</li>
</ol>
<p>Thanks,<br>
Marie</p>

#### vrapp on 7/21/2021, 08:01 AM: 

<p>Here is attached sample project. The demonstration video can be seen at<br>
<a target='_blank' href="https://youtu.be/Le90mHN_1pw">https://youtu.be/Le90mHN_1pw</a></p>
<p>In the video you can see how this search is taking 12 seconds by Framework call from the program, and then I search for the same in Windows Explorer, and the results come instantly.</p>
<p>This is so because the directory is included in Windows Search index. So search in Windows Explorer does take advantage of that, while Framework call does not. In a larger directory it will be not 12 seconds but minutes, depending on the size, while in Explorer it still will be instant thanks to the index.</p>
<p>Note that this particular directory was on a remote Windows server share, and it was included in search index on the server.</p>

#### Feedback Bot on 7/20/2021, 07:22 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### vrapp on 7/21/2021, 08:03 AM: 

<p>…the answers to the 3rd question: this is Windows 10 2004; the application was using .Net Framework 4.8, as you can see in the attached project.</p>

#### Feedback Bot on 7/21/2021, 07:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by danmoseley** [comment]
My assumption is that an numeration of the filesystem is "up to date" in some sense, whereas the Windows indexing service is not, nor does it index everywhere. therefore it's quite inappropriate for our enumeration APi to consult it. It might be interesting to offer a nice API over the Windows indexing service, if one does not exist, but that's something that can be done in a library and shared on NuGet.

I don't think we've had other asks for this -- @JeremyKuhne maybe remembers ?

**Comment by danmoseley** [comment]
I'm going to close though for reasoning above.

**Comment by danmoseley** [comment]
We appreciate the suggestion though!

**Comment by JeremyKuhne** [comment]
I don't remember any asks about hitting the indexing service. For the record, the current search service (the indexing service ended with Windows 8) is documented here: https://docs.microsoft.com/en-us/windows/win32/search/-search-developers-guide-entry-page
