### ISSUE TITLE
Potential performance regression in Array.Sort for arrays of reference types

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#59149]
```cmd
git clone https://github.com/dotnet/performance.git
py .\scripts\benchmarks_ci.py -f net5.0 net6.0 --filter "System.Collections.Sort<IntClass>.Array" --bdn-arguments "--miniterationcount 100 --maxiterationcount 101 --outliers dontremove --memoryrandomization true"
```

Both Windows and Unix are affected:

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Collections.Sort(IntClass).Array(Size%3a%20512).html

![image](https://user-images.githubusercontent.com/6011991/133425156-e070b9f9-5288-40f6-a700-a1a4135c1907.png)

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Collections.Sort(IntClass).Array(Size%3a%20512).html

![image](https://user-images.githubusercontent.com/6011991/133425228-a4f56324-0540-420d-92f6-9362499d9214.png)

**Comment by adamsitnik** [comment]
There are more array sorting-related benchmarks that have regressed across multiple configs, so the better config would be:

```cmd
--filter 'System.Collections.Sort*Array*'
```

**Comment by danmoseley** [comment]
Is it possible to isolate a commit range? Seems like a sharp change. Might help see whether PGO is a suspect or not.

**Comment by jeffhandley** [comment]
@DrewScoggins Could you help narrow down the commit range for this regression?

**Comment by DrewScoggins** [comment]
https://github.com/dotnet/runtime/compare/7b7954aac35ff34e747a45ee51d58d56868f0aba...0df29f7dc4c8371bd5de99916b85dc692e03c714

**Comment by dakersnar** [comment]
Seems to have improved over time.
