### ISSUE TITLE
Potential perf regression in Utf8Encoding.GetBytes

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#59146]
```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f net5.0 net6.0 --filter 'System.Text.Perf_Utf8Encoding.GetBytes'
```

Both Windows and Unix are affected:

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Text.Perf_Utf8Encoding.GetBytes(Input%3a%20Cyrillic).html

![image](https://user-images.githubusercontent.com/6011991/133419976-145d1881-e3b1-424c-b493-84324028520d.png)

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Text.Perf_Utf8Encoding.GetBytes(Input%3a%20Cyrillic).html

![image](https://user-images.githubusercontent.com/6011991/133420085-0b5da6c3-7aa3-4547-bb43-4420508f0d3a.png)

@GrabYourPitchforks it might be caused by #51190

ARM is not affected: 

<details>

| Ratio | Operating System        | Bit   | Processor Name                                  |
| -----:| ----------------------- | ----- | ----------------------------------------------- |
|  0.83 | Windows 10.0.19043.1165 | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
|  0.83 | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   |
|  0.89 | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   |
|  0.91 | Windows 10.0.18363.1621 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
|  0.81 | Windows 8.1             | X64   | Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge)   |
|  0.89 | Windows 10.0.19042.685  | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |
|  0.87 | Windows 10.0.19043.1165 | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        |
|  0.97 | Windows 10.0.22454      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   |
|  0.83 | Windows 10.0.22451      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
|  0.82 | Windows 10.0.19042.1165 | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
|  0.80 | Windows 7 SP1           | X64   | Intel Core2 Duo CPU T9600 2.80GHz               |
|  0.87 | centos 8                | X64   | AMD EPYC 7452                                   |
|  0.90 | debian 10               | X64   | AMD EPYC 7452                                   |
|  0.85 | rhel 7                  | X64   | AMD EPYC 7452                                   |
|  0.87 | sles 15                 | X64   | AMD EPYC 7452                                   |
|  0.89 | opensuse-leap 15.3      | X64   | AMD EPYC 7452                                   |
|  0.88 | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
|  0.86 | ubuntu 18.04            | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
|  0.86 | alpine 3.13             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
|  0.99 | ubuntu 16.04            | Arm64 | Unknown processor                               |
|  0.98 | Windows 10.0.19043.1165 | Arm64 | Microsoft SQ1 3.0 GHz                           |
|  0.99 | Windows 10.0.22000      | Arm64 | Microsoft SQ1 3.0 GHz                           |
|  0.92 | Windows 10.0.19043.1165 | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
|  0.95 | Windows 10.0.18363.1621 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
|  1.01 | Windows 10.0.19043.1165 | Arm   | Microsoft SQ1 3.0 GHz                           |
|  0.83 | macOS Big Sur 11.5.2    | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |
|  0.95 | macOS Big Sur 11.5.2    | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      |
|  0.88 | macOS Big Sur 11.4      | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |

</details>

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/dotnet/runtime/issues/52313? If so, it would be resolved by https://github.com/dotnet/runtime/issues/57698.

Summary: PGO isn't running over non-English scenarios, and it's causing some of the UTF-8 logic to be reordered in a suboptimal fashion.

**Comment by adamsitnik** [comment]
> Possible dupe of #52313? 

That is correct, appologies the for duplicate!
