### ISSUE TITLE
Using Sync Method of HTTP Client (.NET 5) in .NET Framework 4.8

### ISSUE THREAD

**Issue by din-prajapati** [dotnet/runtime#59144]
Hello Team,

By Looking at below link of Sync HTTP Client Send (synchronous method); it looks like it has been introduced in .NET 5. 
https://github.com/dotnet/runtime/issues/32125

Now, I have the same situation where i need to use synchronous method of HTTPClient in a class library project's method which is used by other library internally; Now i can not change every calling method as Async due to async methods of httpclient.  Also, internal library is in .NET Framework 4.8. So, i would like to know is there any way (may be extension method if possible) where i can use that sync version of method in .net Framework 4.8 as i can not upgrade to class library to .NET 5

Feel free to suggest good approach where i can call sync methods of HTTPClient of .NET 5 in internal library targeted to .NET 4.8 ?

**Comment by teo-tsirpanis** [comment]
Hello, the synchronous `HttpClient` methods were introduced on .NET 5, are not available on .NET Framework and most probably will never be since Framework is not receiving new features.

If you own both class libraries you mention, I think that porting them to .NET 5 and making the entire call chain `async` is worth the effort and will yield significant performance benefits (besides taking advantage of asynchrony, the synchronous `HttpClient` methods support only HTTP/1).

If you don't own the code of the internal .NET Framework 4.8 library, you can still import it on a .NET 5 project. I haven't exactly understood these libraries or how they interact, feel free to correct me if I misunderstood something.

**Comment by karelz** [comment]
.NET Framework 4.8 was announced to be last major version of .NET Framework: https://devblogs.microsoft.com/dotnet/net-core-is-the-future-of-net/
We do not have plans to add new features there, unless they are super-critical (e.g. TLS 1.3 support for compliance and security reason).

Overall, HttpClient sync APIs were added only to ease up migration of large project from .NET Framework to .NET Core. We discourage customers to use them. They are not tuned for high performance. We expect high perf scenarios to use async variants.
On .NET Framework, you can use `HttpWebRequest` to get sync APIs. That is a reasonable approach there. However, be aware that such model will be harder to migrate to .NET Core as `HttpWebRequest` is legacy, with limited functionality and performance as explicit non-goal.

Closing as answered.

Note: We do not track .NET Framework issues / questions on GitHub. [VS Developer Community](https://developercommunity.visualstudio.com/search?space=61) is the right feedback channel.

**Comment by din-prajapati** [comment]
Thanks for your reply.

> `If you own both class libraries you mention, I think that porting them to .NET 5 and making the entire call chain async is worth the effort and will yield significant performance benefits (besides taking advantage of asynchrony, the synchronous HttpClient methods support only HTTP/1).`
Making entire call to Asyn will be hell lot of effort. we can not make hell lot of method call to async. And We can not migrate to .NET 5 from .NET 4.8 as .net 5 is based on Core concepts.

I was looking any way by which i can still use httpclient and its .Send (synchronous) methdo in .net framework 4.8. OR is there any thread safe and secure approach where i can make async api call (using httpClient) in Sync chain of methods call so that i did not have to make every parent method call as async.

Any help will be highly appreciated.

Thoughts !!
