### ISSUE TITLE
System.Text.Json source generator fails when targetting multiple frameworks without referencing STJ

### ISSUE THREAD

**Issue by ashakoor** [dotnet/runtime#59140]
### Description
When using the `System.Text.Json` source generator in a project targeting multiple frameworks, including .NET 6.0, without referencing the `System.Text.Json` package, the following errors are given upon compilation:

- `CS0534 'TestClassJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'`
- `CS7036 There is no argument given that corresponds to the required formal parameter 'instanceOptions' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?, JsonSerializerOptions?)'`

Minimal reproduction:
```csharp
using System.Text.Json.Serialization;

namespace StjTest
{
    public class TestClass { }

#if NET6_0_OR_GREATER
    [JsonSerializable(typeof(TestClass))]
    internal partial class TestClassJsonContext : JsonSerializerContext { }
#endif
}
```
in a "Class Library" project with `<TargetFrameworks>net5.0;net6.0</TargetFrameworks>`.
I have not yet been able to reproduce this issue in a "Console Application" project.

### Configuration
Visual Studio 2022 Community, Preview 4
.NET SDK 6.0.100-rc.1.21458.32
Issue is architecture-agnostic

### Other information
Workaround is to reference `System.Text.Json` 6.0.0 or later conditionally for the target frameworks that need it, as referencing the package in .NET 6.0 will cause the built-in and referenced source generators to conflict.

**Comment by layomia** [comment]
I wasn't able to repro this issue using the latest RC2 SDK - https://github.com/dotnet/installer#installers-and-binaries. Please try this version and let us know if you still face issues here. Also note the source generator can be used with net5.0 as well.

```cs
using System.Text.Json.Serialization;

namespace StjTest
{
    public class TestClass { }

#if NET6_0_OR_GREATER
    [JsonSerializable(typeof(TestClass))]
    internal partial class TestClassJsonContext : JsonSerializerContext { }
#endif
}
```

```cs
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
    <ImplicitUsings Condition="'$(TargetFramework)' == 'net6.0'">enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```
