### ISSUE TITLE
[macOS] Potential perf regression in Timer 

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#59150]
It seems to be affecting only macOS (cc @Lxiamail @jeffhandley)

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py -f net5.0 net6.0 --filter System.Threading.Tests.Perf_Timer.ShortScheduleAndDisposeWithFiringTimers
```

| Result | Ratio | Operating System        |
| ------ | -----:| ----------------------- |
| Same   |  1.06 | Windows 10.0.19043.1165 |
| Same   |  0.93 | Windows 10.0.20348      |
| Same   |  1.11 | Windows 10.0.20348      |
| Same   |  1.00 | Windows 10.0.18363.1621 |
| Same   |  0.91 | Windows 8.1             |
| Same   |  1.01 | Windows 10.0.19042.685  |
| Same   |  1.01 | Windows 10.0.19043.1165 |
| Same   |  1.01 | Windows 10.0.22454      |
| Same   |  1.07 | Windows 10.0.22451      |
| Same   |  0.97 | Windows 10.0.19042.1165 |
| Slower |  0.70 | Windows 7 SP1           |
| Same   |  1.06 | centos 8                |
| Same   |  1.02 | debian 10               |
| Same   |  1.01 | rhel 7                  |
| Faster |  1.15 | sles 15                 |
| Same   |  1.08 | opensuse-leap 15.3      |
| Same   |  1.10 | ubuntu 18.04            |
| Same   |  1.01 | ubuntu 18.04            |
| Same   |  1.02 | alpine 3.13             |
| Same   |  1.08 | ubuntu 16.04            |
| Same   |  1.06 | Windows 10.0.19043.1165 |
| Same   |  1.00 | Windows 10.0.22000      |
| Same   |  0.98 | Windows 10.0.19043.1165 |
| Same   |  1.00 | Windows 10.0.18363.1621 |
| Same   |  1.02 | Windows 10.0.19043.1165 |
| Slower |  **0.82** | macOS Big Sur 11.5.2    |
| Slower |  **0.75** | macOS Big Sur 11.5.2    |
| Slower |  **0.77** | macOS Big Sur 11.4      |

**Comment by mangod9** [comment]
I am going to close this since customers havent reported any perf concerns with this.
