### ISSUE TITLE
Microsoft.Extensions packages missing .NET (Core) targets

### ISSUE THREAD

**Issue by pentp** [dotnet/runtime#59158]
#35606 removed a ton of build targets for mostly Microsoft.Extensions packages that are now built only for `netstandard2.0` and `net461`.
This doesn't look right - some of these packages now depend on long deprecated `netstandard2.0` packages and after upgrading my app to .NET 6 rc1 it started pulling in these packages that should be long forgotten already (e.g., `System.Buffers/4.5.1`).

I thought the general idea was to move in the exact opposite direction - instead of moving back to `netstandard2.0` only packages we should be adding .NET [Core] targets to all packages and at some point hopefully drop `netstandard2.0` and `net461` targets entirely.

Some examples of obsolete dependencies that weren't there for .NET 5 versions:
```json
"Microsoft.Extensions.DependencyModel/6.0.0-rc.1.21451.13": {
  "dependencies": {
    "System.Buffers": "4.5.1",
    "System.Memory": "4.5.4",

"Microsoft.Extensions.Logging.Abstractions/6.0.0-rc.1.21451.13": {
  "dependencies": {
    "System.Buffers": "4.5.1",
    "System.Memory": "4.5.4"
```

**Comment by ViktorHofer** [comment]
> I thought the general idea was to move in the exact opposite direction - instead of moving back to netstandard2.0 only packages we should be adding .NET [Core] targets to all packages and at some point hopefully drop netstandard2.0 and net461 targets entirely.

Correct. Adding .NETCoreApp configurations to all the packages in dotnet/runtime is tracked via https://github.com/dotnet/runtime/issues/54012. Feel free to contribute in case you want to help make progress on the issue.

**Comment by ViktorHofer** [comment]
> This doesn't look right - some of these packages now depend on long deprecated netstandard2.0 packages and after upgrading my app to .NET 6 rc1 it started pulling in these packages that should be long forgotten already (e.g., System.Buffers/4.5.1).

Note that these packages will continue to pull in these dependencies as long as the packages support netstandard2.0. There are no plans to stop supporting .NETStandard in our packages anytime soon (i.e. during .NET 7 or .NET 8).

**Comment by pentp** [comment]
> Note that these packages will continue to pull in these dependencies as long as the packages support netstandard2.0. There are no plans to stop supporting .NETStandard in our packages anytime soon (i.e. during .NET 7 or .NET 8).

If they had a .NET [Core] target (like they had in .NET 5 versions), then they would not have these legacy dependencies when used from a .NET 6 app.

**Comment by ViktorHofer** [comment]
> If they had a .NET [Core] target (like they had in .NET 5 versions), then they would not have these legacy dependencies when used from a .NET 6 app. So this is a sort-of regression when compared to .NET 5.

Adding dependencies to the graph (even if such dependencies aren't built live anymore) isn't considered a regression. We still service the System.Memory and System.Buffers packages in case of security issues.

Also, in many cases you will still get the .NETStandard asset into your dependency graph, i.e. when you reference a third party package that only offers a netstandard2.0 lib and depends on these packages.

That said, as mentioned, we added .NETCoreApp tfms to many of our packages during .NET 6 and the rest will follow with .NET 7.

**Comment by ViktorHofer** [comment]
Just opened https://github.com/dotnet/runtime/blob/cbe463bfb602dde7cbfcf78e5ef87743b4f87a4c/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/Microsoft.Extensions.Logging.Abstractions.csproj#L33-L36 for Microsoft.Extensions.Logging.Abstractions one as that one already had a net6.0 asset but the dependencies weren't conditioned accordingly to not apply to it.

**Comment by pentp** [comment]
It looks like this is now covered by the two other issues.
It's a bit unfortunate that Microsoft.Extensions.DependencyModel will have these legacy dependencies in .NET 6.0, but probably not worth any last minute changes.

**Comment by ViktorHofer** [comment]
@pentp thanks for reporting. I just merged the PR that fixes the issue with M.E.Logging.Abstractions and the change will flow into packages produced by .NET 6 RC2 and onwards.

Regarding the DependencyModel one, I agree but fixing that at this point in the cycle likely doesn't meet the bar. As said, this already got fixed in main so the first .NET 7 preview release will contain the fix.
