### ISSUE TITLE
CS8714: Dictionary<TKey, TValue> where TKey: notnull - WHY?

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#59179]
## Background and Motivation

I really don't understand why TKey constrains with 'notnull'...

for example: 
```C#
public class MyClass<T> 
where T: class? // for example
{
   private Dictionary<T, int> _cache; // warning CS8714
   private int GetCached(T? val) {
      if (val is null) return 0; // or throw exception
      return _cache.TryGetValue(val, out var cached) ? cached : 0;
   }
}
```
Maybe it is some solution to prevent this warning in order to not use ```#pragma warning disable...```, which makes code quite ugly.

## Proposed API

Remove notnull constrain from TKey

**Comment by jaredpar** [comment]
Transferring to runtime as the definition of `TKey` currently has the `notnull` constraint hence the compiler is issuing the correct warning here.

**Comment by stephentoub** [comment]
> I really don't understand why TKey constrains with 'notnull'

Because `Dictionary<TKey, TValue>` doesn't permit null keys, e.g.
https://github.com/dotnet/runtime/blob/82993d2c9319b5ba6c8ecd8a79aa01e300ce5afd/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L503-L506
The nullable constraint is reflecting that reality.

**Comment by danmoseley** [comment]
@kefyru let us know if this didn't answer the question satisfactorily!

**Comment by kefyru** [comment]
Ok. I have problem.

public MyComponent<T> : IComponent where T : notnull

With this constraint i cant use this component in razor markup. Compiler cant generate source.

**Comment by danmoseley** [comment]
@mkArtakMSFT do you have insight here?

**Comment by kefyru** [comment]
I absolutely understand why key can't be null, but type constraint 'notnull' does more harm than good (IMHO), and imposes restrictions to usage.. May by some language constructions like <TKey!, TVal> could solve inconvenience.

```C#
public class MyComponent<T> : IComponent where T : notnull 
{
   ...
   private Dictionary<T, int> _cache; // OK
   // using this component in razor markup causes a compilation error
   // Compile Error CS0449 : 
   // The constraints "class", "struct", "unmanaged", "not null" and "default" 
   // cannot be combined or repeated, so they must be specified first in the list of constraints.
   ...
}
```

```C#
public class MyComponent<T> : IComponent  // without T : notnull 
{
   ...
   private Dictionary<T, int> _cache; // warning CS8714
   ...
}
```

```C#
public class MyComponent<T> : IComponent  // without T : notnull 
{
   ...
#pragma warning disable 8714
   private Dictionary<T, int> _cache; // OK, but not pretty
#pragma warning restore 8714
   ...
}
```
