### ISSUE TITLE
[Net6 - RC1] Json Source Generator - JsonSerializerContext Breaking Change?

### ISSUE THREAD

**Issue by srpeirce** [dotnet/runtime#59177]
### Describe the bug
I am using JSON Source generators as per this article: https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-1/

Since upgrading to RC1 the code no-longer compiles. Is this an intended change to the API? I can't find any issues related in this repo.

### To Reproduce

In Preview 7 I had code like this, based on examples here: https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/ 

```csharp
[JsonSerializable(typeof(ChannelViewModel))]
    [JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
    internal partial class ChannelViewModelContext : JsonSerializerContext { }
```

After Upgrading to RC1 this code no longer compiles due to `Base class 'System.Text.Json.Serialization.JsonSerializerContext' doesn't contain parameterless constructor`.

Upon inspection the new contract is:
`protected JsonSerializerContext(JsonSerializerOptions? instanceOptions, JsonSerializerOptions? defaultOptions)`

Is this change intended, if so, can provide example of usage?

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by eiriktsarpalis** [comment]
Hi @srpeirce, both the `ChannelViewModelContext ` constructor and the `GetTypeInfo` methods are meant to be implemented by the source generator and not the developer, so neither need be specified explicitly. This means that you would need to write your class as follows:
```csharp
    [JsonSerializable(typeof(ChannelViewModel))]
    [JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
    internal partial class ChannelViewModelContext : JsonSerializerContext
    {
    }
```
If this fails to compile on your project it is likely that either something is wrong with your project or you might be using a broken SDK version. Would it be possible to a standalone, minimal console application that demonstrates the issue? Please also include the SDK version you are using (obtainable by writing `dotnet --version` in the CLI).

**Comment by layomia** [comment]
This issue should be resolved when you upgrade to the RC2 or higher version of the SDK and recompile your application. To try a fix now, download and try preview version of the RC2 installer - https://github.com/dotnet/installer#installers-and-binaries. Please let us know if you still face issues here.
