### ISSUE TITLE
[dotnet-sdk-6.0.100-rc.2.21463.12] grandnode item name change from Chinese (Simplified, China). Zh-CN to Chinese (Simplified, China). Zh-Hans-CN

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#59193]
**Application Name**:  grandnode
**Windows OS Build**: Windows 19h1 
**CPU**: X64 
**.NET Build Number**:dotnet-sdk-6.0.100-rc.2.21463.12

**Verify Scenarios:**

1). Windows 19h1 X64  +dotnet-sdk-6.0.100-rc.1.21405.13:Fail
2). Windows 19h1 X64  +dotnet-sdk-6.0.100-rc.2.21463.12:Fail
3). Windows 19h1 X64  +dotnet-sdk-6.0.100-preview.7.21379.14:Fail
4). Windows 19h1 X64  +dotnet-sdk-6.0.100-alpha.1.21062.11:Fail
5). Windows Rs5 X64   +dotnet-sdk-5.0.401 :Pass
6). Windows Rs5 X64  +dotnet-sdk-3.1.413:Pass

**Github Repo link:** https://github.com/grandnode/grandnode

**App Source and App Checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1404693

**Repro steps**:
This is 3.1 app, but we are running it on 6.0, machine only have 6.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 6.0.

1. copy app 
2. install mongodb
3.
   Delete DB

    Open CMD, input command "cd C:\Program Files\MongoDB\Server\4.0\bin".
     Input command "mongo.exe".
     Input command "use GrandNodeDB".
     Input command "db.dropDatabase()".
  Restore DB

   Open CMD, input command "cd C:\Program Files\MongoDB\Server\4.0\bin".
   Input command to Restore DB: "mongorestore --db GrandNodeDB 

   Start DB
   Open cmd, input net start MongoDB

 4. Open CMD, input command "cd %APP_CLIENT_ROOT%\GrandNode\GrandNode".
 5. Input command "dotnet Grand.Web.dll".
 6. Open Edge, Input http://localhost:5000.
 7. Click Settings.
 8. Click "Log in" link.
 9. Input appcompat1@163.com in the “Email” text box.
 10. Input %APP_TEST_COMMON_KEY1% in the “Password” text box.
 11. Click “Log in” button.
 12. Click Settings.
 13. Click “Admin” icon.
 14. Click Configuration item.
 15. Click Languages item.
 16. Click Add new button.
 17. Click Language culture drop down box.
 18. Then click Chinese (Simplified, China). Zh-CN item.

**Expected Result:**

Click successfully

**Actual Result:**

Can not find Chinese (Simplified, China). Zh-CN item,
Item name change to Chinese (Simplified, China). Zh-Hans-CN.

**Minimal Repro steps**:

1) Create a ConsoleApp (.net6 or .net5, but we need to run on .net6)
2) Replace this code in Program.cs :
```
static void Main(string[] args)

        {
            CultureInfo[] cinfo = CultureInfo.GetCultures(CultureTypes.AllCultures & ~CultureTypes.NeutralCultures);
            foreach (CultureInfo cul in cinfo)

            {
                Console.Write(cul.DisplayName + cul.Name + "\n");
            }
        }
```

**Expected Result**:

There is a language culture "Zh-CN".

**Actual Result**:
 Language culture "Zh-CN" change to "Zh-Hans-CN".

@dotnet-actwx-bot @dotnet/compat

**Comment by maryamariyan** [comment]
> This is 3.1 app, but we are running it on 6.0, machine only have 6.0 installed

> Create a ConsoleApp (.net6 or .net5, but we need to run on .net6)

/cc @safern @tarekgh

**Comment by tarekgh** [comment]
This is CLDR Unicode behavior we are getting from ICU. The enumeration will return the names that is desired to be used e.g. `Zh-Hans-CN`. 
`zh-CN` is considered alias for `Zh-Hans-CN` which means you still can create a culture with that name. i.e. you can do

```C#

    CultureInfo zhCNCulture = new CultureInfo.GetCltureInfo("zh-CN");
```

In .NET, starting from v5.0 and 6.0 we are following the Unicode standard behavior for that.
