### ISSUE TITLE
HttpWebRequest creates many connections

### ISSUE THREAD

**Issue by MhdTlb** [dotnet/runtime#59207]
### Steps to reproduce

1. Create a Class Library project and make target frameworks net462 and netstandard2.0.
2. Add a new class to the project with following code:

```
        public class Httpwebrequesttest
	{
              public static void Run()
              {
                  for (int i = 0; i < 1000; i++)
                  {
                      var client = WebRequest.CreateHttp("http://localhost:80");
                      using (var res = client.GetResponse())
                      {
      
                      }
                      Console.WriteLine($"{i}");
                  }
                  Console.WriteLine($"press enter then exit");
                  Console.ReadLine();
              }
          }
```
3. Add Console project to the solution and make target framework as netcoreapp3.1
4. Add the Class library project as dependency to the Console App and call the `Httpwebrequesttest.Run` method from the Console App
5. Open a CMD and run this command `netstat -na | find "80"`

### Expected behavior

I was expecting to see few TCP connections but there are hundreds of them with the **TIME_WAIT** status:
` ...
TCP    [::1]:63056            [::1]:80               TIME_WAIT
...`

If I change the target framework of the Console Application to `net462` and I run the netstat command, i can see few TCP connections with status **ESTABLISHED**

### Notes
- I tried to play with [ServicePointManager.DefaultConnectionLimit](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.defaultconnectionlimit?redirectedfrom=MSDN&view=net-5.0#System_Net_ServicePointManager_DefaultConnectionLimit) in the Class Library project but it did not help
- Also, I changed connectionManagment.maxConnection(https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/connectionmanagement-element-network-settings?redirectedfrom=MSDN) in App.config file without luck

**Comment by ManickaP** [comment]
Should be fixed in https://github.com/dotnet/corefx/pull/41462 which went into 5.0. If you switch to .NET 5.0 do you still see this problem?

In .NET Core `WebRequest` is based on `HttpClient`, so that's why it has such a different behavior from .NET Framework. We do recommend to switch to `HttpClient` if you plan to target .NET Core and .NET 5.0+ runtimes.

**Comment by MhdTlb** [comment]
@ManickaP .Net5.0 does not have the issue

**Comment by ManickaP** [comment]
@MhdTlb thanks for the confirmation.

How much is the issue impacting you? And would you be able to upgrade to .NET 5.0 (or 6.0 which is RC1 now)?

**Comment by karelz** [comment]
Triage: Addressed in 5.0+. Closing.

**Comment by MhdTlb** [comment]
@ManickaP  Unfortunately, we can not upgrade to .NET 5.0 right now. Is there a workaround to keep using 3.1?

**Comment by karelz** [comment]
@MhdTlb there is no workaround to our best knowledge. Why cannot you upgrade to .NET 5.0 now? What limits you?
If you need LTS, did you consider .NET 6.0? (it is now in RC1 which has go-live license, with GA following soon in November)

**Comment by ManickaP** [comment]
@MhdTlb you'd need use `HttpClient` and cache it yourself.
