### ISSUE TITLE
Is the breaking change in PipeWriterStream.WriteAsync intentional?

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#59209]
### Description

In upgrading my System.IO.Pipelines dependency from 5.0.1 to 7.0, some of my tests are failing because `PipeWriterStream.WriteAsync(null, 0, 0, CancellationToken.None)` now throws `ArgumentNullException` where it didn't before.

Certainly a null buffer is an odd argument to pass in, but when the length is 0, it isn't used so the fact that many stream implementations including `PipeWriteStream` allowed it (until now) might make sense.

Is this breaking change intentional or accidental? As the only breaking change among all my 700+ tests, it seems like it may be worthwhile to revert that change.

```
Message: 
System.ArgumentNullException : Value cannot be null.
Parameter name: buffer

  Stack Trace: 
PipeWriterStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
CombinedStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) line 124
<WriteAsync>d__29.MoveNext() line 314
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
TaskAwaiter.GetResult()
<Write_InputValidation>d__18.MoveNext() line 168
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
TaskAwaiter.ThrowForNonSuccess(Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by teo-tsirpanis** [comment]
The change was introduced in https://github.com/dotnet/runtime/commit/0acbafe06130149028c353c8aade702d6777edd5#diff-00e86876bc791a683ff6ba5718cda5bf0291b29a692c1e57b057fe4bb1ae96b2.

**Comment by stephentoub** [comment]
It was intentional as part of aiming to ensure more consistency among our Streams.  The fact that it happened to allow null in that one corner case was not intentional; it just happened to work as an implementation detail of the checks ReadOnlyMemory was performing.

**Comment by danmoseley** [comment]
Do we have a breaking change note that covers this, or could mention it?

**Comment by stephentoub** [comment]
> Do we have a breaking change note that covers this, or could mention it?

That passing a null byte[] to Stream.Read might throw?  I mean, we could add one if you really want to, but it's expected.  It's a bug plain and simple that it wasn't previously failing for this error condition.
