### ISSUE TITLE
Exporting a X509Certificate2Collection with PKCS7 on Windows produces DER with trailing zeros

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#59212]
Doing a PKCS7 export on Windows with `X509Certificate2Collection` always seems to include a few trailing zeros.

Simple repro:

```csharp
using System.Security.Cryptography.X509Certificates;

X509Certificate2Collection cc = new();
cc.Export(X509ContentType.Pkcs7);
```

In hex, this will produce something like `302306092A864886F70D010702A01630140201013100300B06092A864886F70D010701310000000000`.

There are four trailing zero octets there that are not necessary.

I would expect the export to create a valid DER encoded PKCS7 document with no trailing data.

----

I'm guessing this is something the Windows API is doing and we just report back whatever Windows gives us. It would be nice if we corrected this. Possibly by doing:

1. Get the real length with `int realLen = AsnReader.PeekEncodedValue().Length`
2. Verify that the trailing data, if any, is all zeros.
3. Return a `result.Slice(0, realLen).ToArray();`

Or perhaps these are load-bearing zeros and we need to keep them.

**Comment by vcsjones** [comment]
> Or perhaps these are load-bearing zeros and we need to keep them.

If this is true (I cannot imagine why) then at least I think the PEM PKCS7 exports should not include these.

**Comment by bartonjs** [comment]
I also assume it's a Windows-ism.

Maybe we should put the length == 0 check before the PALs and just blit out the right answer for all platforms :smile:.

**Comment by vcsjones** [comment]
> Maybe we should put the length == 0

@bartonjs This occurs regardless if the collection is empty or not. With one cert:

```
308201C706092A864886F70D010702A08201B8308201B40201013100300B0609
2A864886F70D010701A082019C308201983081FBA00302010202087CCE38E470
954027300A06082A8648CE3D040302300F310D300B06035504031304626C6168
301E170D3231303931363137343835315A170D3231303931363137343835315A
300F310D300B06035504031304626C616830819B301006072A8648CE3D020106
052B810400230381860004015E4911CB5FEA6D6BEBB2D2C32F75654DB58B7FEF
29A47E946DEB3B41845DBC38282F89AAB29A893B5568EC41159A7C4A5E2EAD51
9BE36A68CD4E427AF89759078A004A9733DE3550EE23EA0274B584C748C7B153
702E2C1785C07F46C77786B69989E339B6FD997CFFC4E5ABF1C1C6419859B9FA
B125CA9D05742286EF8AC642C6126F300A06082A8648CE3D04030203818B0030
81870241360EE86CB2A17D06A9547FB67B2953A6D5F96DAD68C010ACD6F07030
8F506990368D62696C090B4EF47DDBB6734D10467795C0CF93AECA7F92F96FA9
79B30508F4024201B0CB5D318451804A41BEDED14326D0742993E0D281155E7C
9224B728812F2DF101794994F59C9C8B0A62EF3BFE63E2C9A7548A2901525969
B6307DDE7EF5E29834310000000000
```

**Comment by bartonjs** [comment]
::boggle::
