### ISSUE TITLE
WebSocket UTF8 output validation doesn't throw

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#59214]
I believe that `0xC0 0x80` is invalid UTF8 sequence. 
The RFC says that we should fail https://datatracker.ietf.org/doc/html/rfc6455#section-8.1

```
byte[] buffer = new byte[2];
// Invalid continuation byte
buffer[0] = 0xc0;
buffer[1] = 0x80;
var ex = await Assert.ThrowsAsync<WebSocketException>(() =>
{
    return SendAsync(
        cws,
        new ArraySegment<byte>(buffer),
        WebSocketMessageType.Text,
        true,
        cts.Token);
});
```

**Comment by MihaZupan** [comment]
We are doing that when receiving frames:
https://github.com/dotnet/runtime/blob/b9926a56350867e76db3d4e25b0db91e9001f968/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L823-L828

>    When an endpoint is to interpret a byte stream as UTF-8 but finds
   that the byte stream is not, in fact, a valid UTF-8 stream, that
   endpoint MUST _Fail the WebSocket Connection_.

I read that as something that applies to the receiving side.

**Comment by GrabYourPitchforks** [comment]
Agree with @MihaZupan's assessment here. If you do want to throw on the sending side as a sort of value add ("Hey, caller, you're about to violate the protocol."), you could, but if the contract is that the caller is well-behaved then it's not strictly necessary. Validation will incur some overhead.

**Comment by pavelsavara** [comment]
I found this while implementing WS on WASM.
I didn't have strong opinion either way, I just wanted to discuss it.

Thanks all, closing this.
