### ISSUE TITLE
Decrypted String Issues (chars missing) with System.Security.Cryptography -> AesCng and other classes for encryption/decryption in net6.0 rc1

### ISSUE THREAD

**Issue by milen-denev** [dotnet/runtime#59219]
### Description

I started using .NET 6.0 rc1 in an application. Somewhere around the thousands of lines code `JsonSerializer.Deserialize` was throwing an exception because of issues with the deserialization. I went investigating and I found that the actual cause of the thrown exception is that **after decrypting** a json serialized data, **part of the string is missing**. **This doesn't apply only to JsonStrings but also to any type of string containing anything.**

### Configuration

* .NET 6.0 rc1
* OS: Windows 10 , with update Tuesday 14/09/2021 KB_Something installed
* Architecture -> x64
* Do you know whether it is specific to that configuration? -> I have no idea, but possibly no

### Regression?

* This issue appears in .NET 6.0 rc1 (and I think older previews too) and disappears if I change `<TargetFramework>net6.0</TargetFramework>` to something not being net6.0

### Sample Code

```CSharp
 /// <summary>
        /// Encrypts a string
        /// </summary>
        /// <param name="PlainText">Text to be encrypted</param>
        /// <param name="Password">Password to encrypt with</param>
        /// <param name="Salt">Salt to encrypt with</param>
        /// <param name="HashAlgorithm">Can be either SHA1 or MD5</param>
        /// <param name="PasswordIterations">Number of iterations to do</param>
        /// <param name="InitialVector">Needs to be 16 ASCII characters long</param>
        /// <param name="KeySize">Can be 128, 192, or 256</param>
        /// <returns>An encrypted string</returns>
        public static string Encrypt(string PlainText, string Password, string InitialVector,
            string Salt = "Test", string HashAlgorithm = "SHA1",
            int PasswordIterations = 1,
            int KeySize = 256)
        {
            if (string.IsNullOrEmpty(PlainText))
                return "";

            byte[] InitialVectorBytes = Encoding.ASCII.GetBytes(InitialVector);
            byte[] SaltValueBytes = Encoding.ASCII.GetBytes(Salt);
            byte[] PlainTextBytes = Encoding.UTF8.GetBytes(PlainText);
            PasswordDeriveBytes DerivedPassword = new PasswordDeriveBytes(Password, SaltValueBytes, HashAlgorithm, PasswordIterations);
            byte[] KeyBytes = DerivedPassword.GetBytes(KeySize / 8);
            AesCng SymmetricKey = new AesCng();
            SymmetricKey.Mode = CipherMode.CBC;
            byte[] CipherTextBytes = null;

            using (ICryptoTransform Encryptor = SymmetricKey.CreateEncryptor(KeyBytes, InitialVectorBytes))
            {
                using (MemoryStream MemStream = new MemoryStream())
                {
                    using (CryptoStream CryptoStream = new CryptoStream(MemStream, Encryptor, CryptoStreamMode.Write))
                    {
                        CryptoStream.Write(PlainTextBytes, 0, PlainTextBytes.Length);
                        CryptoStream.FlushFinalBlock();
                        CipherTextBytes = MemStream.ToArray();
                        MemStream.Close();
                        CryptoStream.Close();
                    }
                }
            }

            SymmetricKey.Clear();

            return Convert.ToBase64String(CipherTextBytes);
        }

        /// <summary>
        /// Decrypts a string
        /// </summary>
        /// <param name="CipherText">Text to be decrypted</param>
        /// <param name="Password">Password to decrypt with</param>
        /// <param name="Salt">Salt to decrypt with</param>
        /// <param name="HashAlgorithm">Can be either SHA1 or MD5</param>
        /// <param name="PasswordIterations">Number of iterations to do</param>
        /// <param name="InitialVector">Needs to be 16 ASCII characters long</param>
        /// <param name="KeySize">Can be 128, 192, or 256</param>
        /// <returns>A decrypted string</returns>
        public static string Decrypt(string CipherText, string Password, string InitialVector,
            string Salt = "Test", string HashAlgorithm = "SHA1",
            int PasswordIterations = 1, int KeySize = 256)
        {
            if (string.IsNullOrEmpty(CipherText))
                return "";

            byte[] InitialVectorBytes = Encoding.ASCII.GetBytes(InitialVector);
            byte[] SaltValueBytes = Encoding.ASCII.GetBytes(Salt);
            byte[] CipherTextBytes = Convert.FromBase64String(CipherText);
            PasswordDeriveBytes DerivedPassword = new PasswordDeriveBytes(Password, SaltValueBytes, HashAlgorithm, PasswordIterations);
            byte[] KeyBytes = DerivedPassword.GetBytes(KeySize / 8);
            AesCng SymmetricKey = new AesCng();
            SymmetricKey.Mode = CipherMode.CBC;
            byte[] PlainTextBytes = new byte[CipherTextBytes.Length];
            int ByteCount = 0;

            using (ICryptoTransform Decryptor = SymmetricKey.CreateDecryptor(KeyBytes, InitialVectorBytes))
            {
                using (MemoryStream MemStream = new MemoryStream(CipherTextBytes))
                {
                    using (CryptoStream CryptoStream = new CryptoStream(MemStream, Decryptor, CryptoStreamMode.Read))
                    {

                        ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length);
                        MemStream.Close();
                        CryptoStream.Close();
                    }
                }
            }

            SymmetricKey.Clear();

            return Encoding.UTF8.GetString(PlainTextBytes, 0, ByteCount);
        }
```
###  and implementation of the issue

```CSharp
public static class Program
    {
        public static void Main()
        {
            WriteLine("Starting");
            WriteLine("=============== Text to encrypt ============");
            string Password = "hjfvjkvhvkjvjh87587665";
            string IV = "VgRFr54cd*xv05vx";
            string TestString = "Top-level statements means the compiler generates the namespace, class, and method elements for your main program. You can look at the code for the new application and imagine that it contains the statements inside the Main method generated by earlier templates. You can add more statements to the program, just like you can add more statements to your Main method in the traditional style. You can even add functions. They're created as local functions nested inside the generated Main method.";
            WriteLine(TestString);
            WriteLine("=============== Result ============");
            string EncryptedString = AES256Bit.Encrypt(TestString, Password, IV);
            WriteLine(EncryptedString);
            WriteLine("=============== Decrypted Result ============");
            string DecryptedString = AES256Bit.Decrypt(EncryptedString, Password, IV);
            WriteLine(DecryptedString);
            WriteLine("Finished");
            ReadLine();
        }
    }
```

#### net5.0 + `System.Security.Cryptography.Cng`

![Screenshot](https://cdn.denevcloud.com/denevcloud/NET5.0.jpg)

#### net6.0

![Screenshot](https://cdn.denevcloud.com/denevcloud/NET6.0.jpg)

**Comment by bartonjs** [comment]
This is duplicate of #55527.

Unfortunately, the error is in your code.  CryptoStream used to "over-read" to try to always fill the provided buffer on a call to Read.  Now it behaves more simply, which requires callers to correctly follow the read pattern for streams.

```diff
                    using (CryptoStream CryptoStream = new CryptoStream(MemStream, Decryptor, CryptoStreamMode.Read))
                    {

-                       ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length);
+                       int read = 0;
+                       ByteCount = 0;
+
+                       while ((read = CryptoStream.Read(PlainTextBytes, ByteCount, PlainTextBytes.Length)) != 0)
+                       {
+                           ByteCount += read;
+                       }
+
                        MemStream.Close();
                        CryptoStream.Close();
                    }
```

This is described in the [breaking changes for .NET 6.0 documentation](https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0).  Specifically, https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by danmoseley** [comment]
@bartonjs as an aside, does it matter that Dispose is not being called "inside out" here? Although, perhaps this is just the sample code.
```c#
                using (MemoryStream MemStream = new MemoryStream(CipherTextBytes))
                {
                    using (CryptoStream CryptoStream = new CryptoStream(MemStream, Decryptor, CryptoStreamMode.Read))
                    {

                        ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length);
                        MemStream.Close();
                        CryptoStream.Close();
                    }
                }
```
I know that in some circumstances that can lead to losing data.

**Comment by danmoseley** [comment]
Simply removing the explicit Close() calls would fix the problem -- the using statements will call Dispose() for you, which is all Close() calls.

**Comment by bartonjs** [comment]
> , does it matter that Dispose is not being called "inside out" here?

Nah, that affects CryptoStream.Write.  That problem, classically, is using CryptoStream.Write to write to a MemoryStream, then extracting the MemoryStream's contents before calling cs.FlushFinalBlock (which is called by Dispose)... and that means you have everything except the last N bytes.

CryptoStream in Read mode understands when the data is done, since the underlying stream returned 0.

**Comment by danmoseley** [comment]
I guess I meant in the general case -- the code sample shows the pattern of acquiring A then B, disposing A then B. I know in some contexts (file IO?) that can cause data loss because B may flush data that A would consume. I'm curious whether that's a general pattern we recommend, to acquire and dispose in reverse order (as is naturally ensured by nested using statements)

**Comment by GrabYourPitchforks** [comment]
> I guess I meant in the general case -- the code sample shows the pattern of acquiring A then B, disposing A then B. I know in some contexts (file IO?) that can cause data loss because B may flush data that A would consume. I'm curious whether that's a general pattern we recommend, to acquire and dispose in reverse order (as is naturally ensured by nested using statements)

@danmoseley You're right - the order of operations can be a bit obtuse here. You'll have to stop and do this same "wait, what?" check every time you have disposable wrapper objects. A `CryptoStream` that wraps a `MemoryStream` is one example. A `StreamWriter` that wraps a `FileStream` is another example. Generally speaking, nested _using_ statements should handle this properly, but I know it gives me pause every time I see it. :)

That's one of the reasons I think the one-shot crypto APIs will be more useful to folks going forward. They're simply easier to use, saving you from writing tons of \[possibly incorrect!\] boilerplate code. See https://github.com/dotnet/runtime/issues/2406, https://github.com/dotnet/runtime/issues/40012, https://github.com/dotnet/runtime/issues/24897.

An even _better_ solution would be to provide an opinionated crypto stack similar to aspnet's DataProtection. This would save users from needing to know the intricacies of using the primitive algorithm building blocks. But this might be such a domain-specific scenario that I don't know if we're the right layer to include it.
