### ISSUE TITLE
Enum.ToUInt64() performance improvement

### ISSUE THREAD

**Issue by Timovzl** [dotnet/runtime#59248]
`Enum.ToUInt64()` currently takes an `object` and switches on the type code. That seems unnecessary, at least on little-endian.

A generic, practically branchless overload could be written:

```cs
internal static ulong ToUInt64<T>(T value)
    where T : unmanaged
{
    if (BitConverter.IsLittleEndian) // Hopefully a JIT constant, so that the branch gets optimized away?
    {
        Span<ulong> ulongSpan = stackalloc ulong[] { 0UL };
        Span<T> span = MemoryMarshal.Cast<ulong, T>(ulongSpan);

        span[0] = enumValue;

        return ulongSpan[0];
    }
    else
    {
        return ToUInt64((object)value); // Original implementation, though perhaps improvements are possible
    }
}
```

The above could probably be made even more concise with `Unsafe.As()`.

TBD: What is the requirement for negative values? For example, this implementation converts `sbyte` `-1` to `255`, whereas `(ulong)(sbyte)(-1)` equals `18446744073709551615`. Clearly the two are not compatible, but I believe that each can be roundtripped as long as it is used exclusively. `255` becomes `-1` again if we cast it back to `sbyte` (but notably not when we cast to `long`). Alternatively, perhaps the solution could be tweaked to get a different result for negative values.

**Comment by EgorBo** [comment]
Any benchmarks to see the diff? I think the default impl is pretty efficient, it must be a jump-table over typecode https://github.com/dotnet/runtime/blob/ae46d07eb778fd9e1d4cdfe799a9e1ee7ed1d570/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L273-L288

In theory we can easily intrinsify `Type.GetTypeCode(typeof())` in JIT but I'm not sure it worth the effort as it seems it's the only usage in BCL that will be optimized.

**Comment by Timovzl** [comment]
@EgorBo I had missed the generic overload that now exists, my apologies. I must have been looking at an outdated version of the file. It avoids any boxing, and its implementation is actually using `Unsafe.As()`! What do you know. :smile:

If the jump table is all that we might save, then this does not seem too worthwhile.

**Comment by GrabYourPitchforks** [comment]
Wouldn't it suffice to use the enum size instead of the type code? Per ECMA-335, Sec. II.14.3, it's going to be a 1-, 2-, 4-, or 8-byte integral type. Then you only need 4 branches total. (Bool is a bit weird, but if you're backing an enum with bool then I'm not too worried about you suddenly getting a value like `0x2` once the conversion completes, so may as well treat it the same as a byte.)

**Comment by Timovzl** [comment]
@GrabYourPitchforks Interesting idea. I've tried playing with enum sizes before, and it required calling `Marshal.SizeOf()` (either on the type itself if `T` is constrainted to `unmanaged`, or on either the underlying type otherwise). This made it worthwhile to store the result in a static field in a generic type. This leaves me wondering if the gains of having fewer branch options outweights the cost of going through such a field.
