### ISSUE TITLE
Missing tag/release for 5.0.10

### ISSUE THREAD

**Issue by ta264** [dotnet/runtime#59250]
5.0.10 was released on 14th September but there is no tag/release on the GitHub repository.

Please can you create one - various of us in the community use it to build .NET for FreeBSD.

Thanks.

**Comment by ViktorHofer** [comment]
@Anipik @aik-jahoda how is that possible? Is tagging still a manual process?

**Comment by Anipik** [comment]
@rbhanda

**Comment by ericstj** [comment]
I see the tag here: https://github.com/dotnet/runtime/releases/tag/v5.0.10

Perhaps the timing was just off?

**Comment by Anipik** [comment]
> Perhaps the timing was just off?

there were 2 different commits in the manifest due to which tool didnt work
