### ISSUE TITLE
Consider adding ArgumentEmptyException

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#59273]
This is a frequently occurring check we do in our APIs and unit tests and may warrant a dedicated exception akin to ArgumentNullException.

We'd like to throw this in cases were a sequence or collection is empty but don't want to go to the hassle of creating a dedicated exception ourselves, it would be neat if it was part of the runtime, please consider.

Thx

**Comment by NN---** [comment]
What about ArgumentEmptyOrNullException ?:)

**Comment by tannergooding** [comment]
The existing standard here is to throw `ArgumentException` (some users throw `ArgumentOutOfRangeException` instead).

I don' think this is something worth adding to the BCL at this time.
