### ISSUE TITLE
Dotnet doesn't run apps from /tmp on Linux

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#59280]
### To Reproduce

Use Visual Studio 2019 to compile a .NET Core 5.0 console application which prints “hello, world.” Don’t publish the app, compile only.

Install .NET Core 5.0 runtime (no ASP, no SDK, runtime only). I did so on AMD64 VmWare running Ubuntu 20.04.3 LTS.

Copy the build output to Linux, anywhere under `/tmp` directory.

Run it with `dotnet HelloWorld.dll`

### Exceptions (if any)

```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'HelloWorld.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
```

The same binaries are running fine if launched anywhere from home directory `~/`

### Further technical details

```
Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.9 [/snap/dotnet-runtime-50/16/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by agocke** [comment]
Just tried this and couldn't repro the issue. My dotnet info:

```
$ dotnet --info

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by vitek-karas** [comment]
It would be helpful to get host traces for this failure.

```console
export COREHOST_TRACE=1
export COREHOST_TRACE_FILE=host.txt
dotnet HelloWorld.dll
```

Please note that the produced `host.txt` can contain information about the machine and current user (like paths, environment variables and similar), consider this before sharing the file publicly.

Another idea, does `dotnet ./HelloWorld.dll` work?

**Comment by agocke** [comment]
Closing since the issue is stale

**Comment by Const-me** [comment]
@agocke You have a native build of .NET, i.e. the runtime works on top of your Linux kernel.

When I filed the bug, I was using the snap package with the runtime. Snap works on top of an AppArmor-based sandbox.

This unnecessary intermediate abstraction layer between the runtime and the OS breaks quite a few things. This particular bug is just one of them, here’s another: https://stackoverflow.com/a/69146535/
