### ISSUE TITLE
Implicit SourceGenerator: System.Text.Json.SourceGeneration (net 6.0)

### ISSUE THREAD

**Issue by bernd5** [dotnet/runtime#59284]
For simple Apps which have no explicit SourceGenerator and do nothing with JSON I would like to load/analyze projects as fast as possible.
In roslyn workspaces is a check for sourcegenerators: https://github.com/dotnet/roslyn/blob/60a431bf454e78ae3cefc1930d356a72eaaba20c/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.CompilationTracker.cs#L1078
which is now practically always false - therefore it must be compiled all the time.

Why is it included even if the project does not refer to something related to JSON (like a hello-world app)? Please remove this implicit source generator for those projects.

**Comment by eiriktsarpalis** [comment]
cc @layomia @ericstj

**Comment by bernd5** [comment]
The implicit imports seem to be disabled now...

**Comment by layomia** [comment]
Dup of https://github.com/dotnet/roslyn/issues/55518 - I believe we are striving to address this for net6.0 cc @eerhardt @ericstj @jaredpar
