### ISSUE TITLE
Implement `ToString()` on `System.Collections.DictionaryEntry`

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/runtime#59292]
`DictionaryEntry` still doesn't have a good display in the debugger or when printing it to a log.

Could we implement `ToString()` that returns `$"{Key} = {Value}"`, like `KeyValurPair<TKey,TValue>` has?
https://github.com/dotnet/runtime/blob/ae46d07eb778fd9e1d4cdfe799a9e1ee7ed1d570/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/KeyValuePair.cs#L46

**Comment by eiriktsarpalis** [comment]
So, should this be a change to how `ToString()` is implemented or would it make more sense to add a `DebuggerDisplayAttribute`?

**Comment by KirillOsenkov** [comment]
I'd prefer `ToString()` because there are several advantages:

 * `ToString()` is useful in various other contexts, such as various text logs, format strings, interpolated strings, printf debugging, etc.
 * `KeyValuePair<TKey, TValue>` uses `ToString()`
 * compiler verifies correctness (vs. whatever you write in `DebuggerDisplay` is stringly typed)
 * you can place a breakpoint in `ToString()`
 * it's faster for the debugger (single eval call vs. interpreting the debugger display string)

**Comment by KirillOsenkov** [comment]
It's so frustrating when you see a useless type name in the logs for example, where it could have been meaningful and helpful to have the actual values.

**Comment by Joe4evr** [comment]
> * compiler verifies correctness (vs. whatever you write in `DebuggerDisplay` is stringly typed)

Current preview can have compiler verification, tho:
```cs
[DebuggerDisplay($"{{{nameof(DebugDisplay)},nq}}")]
public class C
{
    private string DebugDisplay => ...;
}
```

**Comment by KirillOsenkov** [comment]
That's a good point, but unfortunately nobody writes it that way. Look at all existing DebuggerDisplay usages:
https://source.dot.net/#System.Private.CoreLib/DebuggerDisplayAttribute.cs,761078d4519dc54e,references

I just had to fix this recently because someone refactored code and forgot to update DebuggerDisplay:
https://github.com/dotnet/msbuild/pull/6650/files

**Comment by Joe4evr** [comment]
> That's a good point, but unfortunately nobody writes it that way.

Only because the feature is new and nobody's used it yet. But at the very least, any *new* applications of `DebuggerDisplay` could (and I believe *should*) make use of the new feature so that mistakes like the one you linked can be spotted at compile-time.

**Comment by krwq** [comment]
@KirillOsenkov would you expect to add any string escaping into `ToString`? I'd expect to make it consistent with perhaps Tuple or other similar classes

**Comment by KirillOsenkov** [comment]
sure, anything is fine, ValueTuple, KVP, as long as it’s something.

**Comment by KirillOsenkov** [comment]
curious how ToString looks for anonymous types and old Tuples

**Comment by eiriktsarpalis** [comment]
> curious how ToString looks for anonymous types and old Tuples

FWIW both prettyprint their contents.

**Comment by jeffhandley** [comment]
I'm tempted to just reuse the implementation for `KeyValuePair.ToString()`. It's available as a static internal:

```c#
        internal static string PairToString(object? key, object? value) =>
            string.Create(null, stackalloc char[256], $"[{key}, {value}]");
```

There's no escaping or anything else fancy here, as anything like that would have performance hits for negligible value (only in odd cases). Here are the tests I have illustrating what the behavior would be:

```c#
    public class DictionaryEntry_Tests
    {
        public static IEnumerable<object?[]> ToString_Inputs()
        {
            yield return new object?[] { "key", "value", "[key, value]" };
            yield return new object?[] { 1, 2, "[1, 2]" };
            yield return new object?[] { typeof(object), (object?)null, "[System.Object, ]" };
            yield return new object?[] { "[key, value", "]]", "[[key, value, ]]]" };
            yield return new object?[] { new DictionaryEntry("key", "key"), new DictionaryEntry("value", "value"), "[[key, key], [value, value]]" };
        }

        [Theory]
        [MemberData(nameof(ToString_Inputs))]
        public void ToString_FormatsKeyValue(object key, object? value, string expected)
        {
            var entry = new DictionaryEntry(key, value);
            var result = entry.ToString();

            Assert.Equal(expected, result);
        }
    }
```

Any objections to taking this approach?

**Comment by danmoseley** [comment]
Does it truncate if key or value is huge? And do we want it to?

**Comment by jeffhandley** [comment]
It does not do any truncation. Scanning through all places where we override `ToString`, I see lots of instances where we emit or build unbounded strings; I haven't found any where we truncate.
