### ISSUE TITLE
Test failure System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59297]
Run: [runtime-libraries-coreclr outerloop  20210917.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1368228&view=ms.vss-test-web.build-test-results-tab&runId=39938366&resultId=104048&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart

```
**Error message:**
```
Assert.Equal() Failure
Expected: 6
Actual:   5


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 208
```

**Comment by ericstj** [comment]
The test was expecting Connected followed by Exception
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs#L205-L209

However it looks to me like the Connected event happens asynchronously on worker thread whenever client connects
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestService.cs#L37-L39

Whereas the Exception happens synchronously as the service starts:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/Program.cs#L19-L30

I see that the write tries to wait on connection:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.TestService/TestService.cs#L114-L117

However this doesn't wait on the the continuation that writes the Connected event.

This looks like a race to me.

Similar to https://github.com/dotnet/runtime/issues/38945 cc @danmoseley

I'll propose a fix.
