### ISSUE TITLE
[API Proposal]: Method to obtain an "empty" JsonDocument

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#59303]
### Background and motivation

There are use cases where for interoperability with other APIs, application code may need to pass an instance of `JsonDocument` to other code, even if there is no need for it have any particular content. However, there is no way to directly create such an "empty" `JsonDocument`, requiring code to parse a string or serialize an object to obtain an instance of `JsonDocument`. Here are two possible approaches as-of .NET 6 RC1:

```csharp
using var document1 = JsonDocument.Parse("{}");
using var document2 = JsonSerializer.SerializeToDocument(new object());
```

There are 3 such usages of the first example in the aspnetcore repo:

1. https://github.com/dotnet/aspnetcore/blob/493b4a2570c500a88071f80541380c39936a6d15/src/Security/Authentication/OAuth/src/OAuthHandler.cs#L248
2. https://github.com/dotnet/aspnetcore/blob/493b4a2570c500a88071f80541380c39936a6d15/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L768
3. https://github.com/dotnet/aspnetcore/blob/493b4a2570c500a88071f80541380c39936a6d15/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L118

It would be more intuitive to have a publicly accessible factory method which would allow an "empty" `JsonDocument` to be obtained by application code without requiring content to be parsed first.

### API Proposal

```diff
namespace System.Text.Json
{
     public sealed class JsonDocument : IDisposable
     {
+       public static JsonDocument Empty();
     }
}
```     

### API Usage

```C#
using var empty = JsonDocument.Empty();
```

### Risks

None that I can think of.

**Comment by FiniteReality** [comment]
Part of me wants to say this should be a property, rather than a method, as it's effectively the "identity" JsonDocument. Otherwise, I agree; I've needed something like this multiple times.

**Comment by eiriktsarpalis** [comment]
`JsonDocument` is read-only so we might as well expose as a property that returns a singleton instance.

cc @steveharter

**Comment by eiriktsarpalis** [comment]
Any particular reason why `Empty` should specifically return `{}` rather than say `[]` or `null`? Should it be called `EmptyObject` instead?

**Comment by martincostello** [comment]
Out of those choices, I think my preference would be for `EmptyObject` returning `{}`.

In my head I would think of an empty _document_ as an object, as `[]` I'd think as an array not a document and `null` as not being anything at all.

**Comment by eiriktsarpalis** [comment]
Even though the type is named `JsonDocument`, it is perfectly capable of representing JSON values other than documents. I think the addition would only be worth it if exposed as a singleton, but on the other hand it would be difficult to justify a singleton `IDisposable` (even if we special cased the disposal to be a no-op).
