### ISSUE TITLE
ClientWebSocket Performance issues on Linux

### ISSUE THREAD

**Issue by ShakesB33r** [dotnet/runtime#59314]
### Description

Receiving data using a ClientWebSocket is approximately 10x more CPU intensive on Linux than on Windows for smaller throughput levels, and has a maximum throughput of roughly half (please see later post for info). This is just for receiving data in a loop with minimal processing being done.

### Configuration

I have noted the issue on multiple Linux platforms, including virtualized Ubuntu 21.04 running through VMWare and Ubuntu 20.04 on wsl2 on my PC (i7-8750h), which is the same PC I use to test the Windows (10 Home 21H1) version. I have also observed the high CPU usage issue on Ubuntu 20.04 Server instances on AWS, using both ARM (graviton 2nd gen) and x86 (Rome) CPUs. The issue is also persistent across both .NET 5 and .NET 6 RC1. 

Please see later posts for code and more info.

**Comment by ShakesB33r** [comment]
Updated code, also have been able to confirm the issue is also present on a bare metal Ubuntu 21.04 installation on a Threadripper 2990WX machine.

**Comment by stephentoub** [comment]
> ~10x slower

Are you seeing it actually be slower?  Or, rather, are you just seeing more CPU consumed for a benchmark that only does one send/receive at a time on a machine with more cores than that?

**Comment by ShakesB33r** [comment]
> Are you seeing it actually be slower? Or, rather, are you just seeing more CPU consumed for a benchmark that only does one send/receive at a time on a machine with more cores than that?

The CPU consumed is significantly higher to process the same number of messages. This is irrespective of whether the number of sockets is smaller or larger than the number of cores, e.g. I first noticed the issue when having roughly 30 incoming streams on an 8 core machine, consuming roughly 40-50% of the total CPU budget which seemed outrageously high.

**Comment by stephentoub** [comment]
Thanks,  I understand.  The point of my questions was around CPU vs throughout.  Are you seeing slower throughout our just now CPU consumption? Given the threading model involved,  I have no trouble believing more CPU is being spent when the system isn't saturated, especially if the extra CPU is sure to thread pool threads spinning waiting for work.  I'd like to understand if you're seeing significantly slower throughput when you've saturated the CPUs.

**Comment by ShakesB33r** [comment]
I have not tested saturating the CPU and seeing if the number of messages can still scale higher if that's what you are asking, but this is something I could try if it would be useful.

**Comment by stephentoub** [comment]
> but this is something I could try if it would be useful.

Yes, thanks. It's of course valuable in its own right avoiding spending CPU cycles that would otherwise be unused.  But the title of this issue you opened is "ClientWebSocket is ~10x slower on Linux"... I've not seen any evidence of that.  Spending additional CPU cycles that weren't otherwise being used isn't the same as running slower.

**Comment by ShakesB33r** [comment]
Well it's problematic in so far as I would like to run other CPU intensive processes on the same machine, I will see if the throughput can scale as we approach and reach 100% CPU later today.

**Comment by ShakesB33r** [comment]
I tested a modified version of the code which gradually increases the number of connections on two machines, one Windows server 2019, one Ubuntu 20.04, both running on AWS C5a.large (2 thread one core EPYC Rome) instances. 

Linux performance was able to continue to scale somewhat after saturating the CPU but saturated the CPU much sooner and had a less than half maximum throughput. Windows however did drop some sockets whereas Linux did not.

Please note that in the Windows measurements the CPU usage is roughly half of the total as there was significant (roughly half) CPU time taken by the "System" process.

[Link to repository](https://github.com/ShakesB33r/WebSocketIssueDemo)

And graphs of performance measurements
![Figure_1](https://user-images.githubusercontent.com/23510603/134067601-50c61da9-94df-4db3-b7f6-b11a54b6eb1c.png)

![Figure_2](https://user-images.githubusercontent.com/23510603/134067607-652be905-6137-453c-9909-43971ca273f1.png)

**Comment by ShakesB33r** [comment]
Do you suspect it is related to the use of IOCP vs epoll? In any event, I would be happy to run another benchmark, but not personally sure how to set up pure sockets code. Any advice would be appreciated.

**Comment by karelz** [comment]
@antonfirsov can you help point out to example/test of simple Sockets server & client code?
