### ISSUE TITLE
System.Drawing.Common.Tests fail many test in VS with "Unable to load DLL 'libgdiplus' or one of its dependencies"

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#59326]
### Description
When System.Drawing.Common.Tests started from the console if fail only 9 tests but when I try to run tests from VS it fails about all tests with the same error
```
    System.TypeInitializationException : The type initializer for 'Gdip' threw an exception.
---- System.DllNotFoundException : Unable to load DLL 'libgdiplus' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
``` 
At the same time, Test Explorer shows that the same tests are passed also. See screenshot:
![Screenshot_16](https://user-images.githubusercontent.com/6407980/133960663-ef453260-f015-4e46-9290-6a3e53da99bf.png)

Test Explorer does not have tools to find tests by name so it is very difficult to find 9 tests that were failed from the console.

How I can find the test by name quickly? For example `System.Drawing.Tests.FontTests.ToLogFont_InvokeGraphics_ReturnsExpected` test.

### Configuration
net7.0 net48
Windows 10 (Russian)
x64

**Comment by safern** [comment]
Interesting, could you inspect the `System.Drawing.Common.dll` asset under the test folder? It seems like it might have picked up the `Unix` asset for some reason?

**Comment by AlexRadch** [comment]
>Interesting, could you inspect the System.Drawing.Common.dll asset under the test folder? It seems like it might have picked up the Unix asset for some reason?

@safern I do not see something unusual in `System.Drawing.Common.dll`.

I found that JSON files for some DLLs contain unusual targets: `".NETStandard,Version=v2.0/",` and sometimes `".NETCoreApp,Version=v7.0/"` with empty string after slash.

>Also could you share the steps that you used to build and run the tests?

I rebuild `System.Drawing.Common` solution and then `Run All Tests`.

**Comment by AlexRadch** [comment]
I think it is `Test Explorer` issue.
The `System.Drawing.Common.Tests` project describe 3 TargetFrameworks: "net7.0-windows;net7.0-Unix;net48".
But in `Test Explorer` I see 4 target frameworks: net48, **net7.0**, net7.0-windows, net7.0-Unix
**net7.0** contains all tests from `net7.0-windows` and `net7.0-Unix` except those should be skipped.

See screenshot:
![Screenshot_17](https://user-images.githubusercontent.com/6407980/134425060-8a424d71-75ed-4f4f-9db4-c6205dd682cc.png)

So I think it is `Test Explorer` issue. It creates **net7.0** target framework and puts in it all tests from `net7.0-windows` and `net7.0-Unix`.

**Comment by danmoseley** [comment]
In that case I think it is best to move this issue to https://github.com/microsoft/vstest. I do not have the power to do this so I have to close here. If you want to pursue please open an issue there.
