### ISSUE TITLE
[API Proposal]: ConcurrentDictionary.TrimExcess

### ISSUE THREAD

**Issue by zgxnet** [dotnet/runtime#59324]
### Background and motivation

Current implementation of ConcurrentDictionary does not have methods to trim the internal storage, and this is really helpful in a number of scenarios.

### API Proposal

```C#
namespace System.Collections.Concurrent
{
    public class ConcurrentDictionary<TKey, TValue>
    {
        public void TrimExcess (); //just like Dictionary.TrimExcess();
        public void TrimExcess(int capacity); //just like Dictionary.TrimExcess(int capacity);
    }
}
```     

### API Usage

```C#
// Fancy the value
var c = new ConcurrentDictionary<int,int>();
//Add a number of items
...
//Remove a number of items
...
// Trim the collection to save memory
c.TrimExcess(c.Count);
//or
c.TrimExcess();
```

### Risks

No Risk

**Comment by eiriktsarpalis** [comment]
I'm not 100% on top of the ConcurrentDictionary implementation, but I believe it should be feasible to implement a `TrimExcess` method: the operation would need to acquire all locks and then copy all entries into a fresh [`Tables`](https://github.com/dotnet/runtime/blob/6c9921d2ad188d81af53892930a87ee5ad97c979/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2200) instance.

I'm not sure what the use cases for such a method would be though. Per [documentation in `Dictionary.TrimExcess`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trimexcess?view=net-5.0)

> This method can be used to minimize the memory overhead once it is known that no new elements will be added.

Assuming the purpose of `TrimExcess()` is to minimize memory usage for subsequent read-only access, I'm not sure why a `ConcurrentDictionary` would be necessary here.

**Comment by zgxnet** [comment]
In a long-running system, e.g. a web server, the system may encounter some bursts of requests, which makes the ConcurrentDictionary very large and consumes a lot of memory. After the outbreak, we may wish to release the memory. I think this is a very common scenario.

> I'm not 100% on top of the ConcurrentDictionary implementation, but I believe it should be feasible to implement a `TrimExcess` method: the operation would need to acquire all locks and then copy all entries into a fresh [`Tables`](https://github.com/dotnet/runtime/blob/6c9921d2ad188d81af53892930a87ee5ad97c979/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L2200) instance.
> 
> I'm not sure what the use cases for such a method would be though. Per [documentation in `Dictionary.TrimExcess`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trimexcess?view=net-5.0)
> 
> > This method can be used to minimize the memory overhead once it is known that no new elements will be added.
> 
> Assuming the purpose of `TrimExcess()` is to minimize memory usage for subsequent read-only access, I'm not sure why a `ConcurrentDictionary` would be necessary here.

**Comment by eiriktsarpalis** [comment]
> In a long-running system, e.g. a web server, the system may encounter some bursts of requests, which makes the ConcurrentDictionary very large and consumes a lot of memory. After the outbreak, we may wish to release the memory. I think this is a very common scenario.

In that scenario, locking the dictionary while it is being trimmed sounds like a recipe for spikes in request latencies. But we might still consider adding it. @stephentoub thoughts?

**Comment by zgxnet** [comment]
ConcurrentDictionary._tables._buckets is a Node array, whose length can be even greater than the number of elements, and this array will not shrink when the elements are removed.
> ConcurrentDictionary stores its data differently than does a Dictionary; the vast majority of memory it consumes is stored in nodes per element, rather than one large array. Have you actually confirmed that TrimExcess would meaningfully achieve what you're hoping for? Can you share an example?

**Comment by stephentoub** [comment]
> whose length can be even greater than the number of elements

Yes, but all it stores are the node references; with Dictionary, each entry stores both the TKey and the TValue and additional state (a hash code and next link).

**Comment by zgxnet** [comment]
The references also occupy a lot of memory. On 64-bit systems, a reference takes about 40% memory of a Node.

> > whose length can be even greater than the number of elements
> 
> Yes, but all it stores are the node references; with Dictionary, each entry stores both the TKey and the TValue and additional state (a hash code and next link).

**Comment by stephentoub** [comment]
> The references also occupy a lot of memory. On 64-bit systems, for simple key/value, e.g. ConcurrentDictionary<int, int>, a reference takes about 40% memory of a Node.

A reference is 8 bytes on 64-bit.

Can you please share a repro of the scenario that's causing you to want such a method?
