### ISSUE TITLE
IconConverterTest.TestConvertTo fail on net48 on non-English Windows

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#59333]
### Description
`System.ComponentModel.TypeConverterTests.IconConverterTest.TestConvertTo` fail on net48 on non-English Windows:
```
 System.ComponentModel.TypeConverterTests.IconConverterTest.TestConvertTo
   Source: IconConverterTests.cs line 138
   Duration: 1 min

  Message: 
Assert.Equal() Failure
           ↓ (pos 1)
Expected: (none)
Actual:   (отсутствует)
           ↑ (pos 1)

  Stack Trace: 
IconConverterTest.TestConvertTo() line 177
```

It fails because `IconConverter.ConvertTo(null, typeof(string))` return localized string on net48 and not localized on net7.0.

What should be fixed?
1. Test themself. Different for net48 and net7.0 .
2. net48 implementation to remove localization.
3. **net7.0 implementation to add localization.**

I think that the third choice will be correct.

### Configuration

net48 and net7.0
Windows 10 (Russian)
x64

### Regression?

I think net7.0 `IconConverter.ConvertTo` implementation has regression.

**Comment by safern** [comment]
@AlexRadch from looking at the `.net7.0` implementation it looks like the resource is indeed a localizable resource: https://github.com/dotnet/runtime/blob/47c7e1128c25a35ab631c33bccc37b81c21c17f5/src/libraries/System.Drawing.Common/src/System/Drawing/IconConverter.cs#L34

However we don't localize them when we run the tests. @ericstj do you know when do we localize resources for .NET Core?

I think what we can do is, we can run this test with remote executor and force the current culture to be `en_US`?

**Comment by AlexRadch** [comment]
@safern can you help me with how to debug tests and library source code also? Can you give me a link with such instructions? Now when I debug tests in VS it can debug only test project code but not library source code.

**Comment by AlexRadch** [comment]
> I think what we can do is, we can run this test with remote executor and force the current culture to be `en_US`?

I created PR to fix this issue, it uses Invariant UI culture but it will not test the localization to other languages.

Does .Net have tests to test that it is localized to other languages and that localization is used by code?
