### ISSUE TITLE
I can't reference Codepages

### ISSUE THREAD

**Issue by ZiCold** [dotnet/runtime#59348]
### Description

Steps:
1. Create simple net5 condole application
2. Add System.Text.Encoding.CodePages nuget package 
![CodePages package](https://user-images.githubusercontent.com/46999908/134017492-7366ad43-773a-47ba-827f-73d35ed8c33c.jpg)
3. Try to reference it with using 
![CodePages package](https://user-images.githubusercontent.com/46999908/134017442-078c757e-68c6-4370-9652-44148cdd729f.jpg)

What can I do?

**Comment by vcsjones** [comment]
Can you please describe the issue you are having a little more? Did you mean to post the same screenshot twice, or was the second one supposed to be something different?

Note that a lot of the functionality in this package is in the `System.Text` namespace, not `System.Text.Encoding.CodePages` like the package name.

Once you have your package referenced, you should be able to use it like:

```csharp
using System.Collections.Generic;
using System.Text;

class EntryPoint
{
    static void Main()
    {
        IEnumerable<EncodingInfo> encodings = CodePagesEncodingProvider.Instance.GetEncodings();

        foreach (EncodingInfo info in encodings)
        {
            System.Console.WriteLine(info.DisplayName);
        }
    }
}
```

**Comment by ZiCold** [comment]
@vcsjones I am sorry for skreenshot missplacement. Here is the right one 
![Codepages Using](https://user-images.githubusercontent.com/46999908/134025877-0390fad0-0ea3-4171-b05a-9f68c9dd743e.jpg)

But it doesn't matter. I didn't know (couldn't find) which namespace to use. And it is interesting but now I don't need CodePages nuget package to use CodePagesEncodingProvider.
Is it intented?

**Comment by vcsjones** [comment]
> don't need CodePages nuget package to use CodePagesEncodingProvider.

Since you are using .NET 5, no you don't need the package reference. I believe this package is shipped in-box in .NET. The package exists for other platforms that use .NET Standard (like .NET Framework).

**Comment by ZiCold** [comment]
Then I think I can close this issue. Thank you so much!
