### ISSUE TITLE
Move throw calls inside `ThrowHelper.Get*` methods

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#59378]
I believe that's indeed the point. We may need a pass at the reader/writer `ThrowHelper` implementation to throw inline rather than return exceptions, assuming there have been no JIT changes that render the optimization redundant.

_Originally posted by @layomia in https://github.com/dotnet/runtime/pull/55564#discussion_r712510021_

**Comment by GrabYourPitchforks** [comment]
For reference, the typical convention is to have _Get\*_ methods return an `Exception` instance, with _Throw\*_ methods throwing the `Exception` instance. See for example:

https://github.com/dotnet/runtime/blob/fd5b60f9f938306e97f2356b0d3c5c7eb9f84336/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs#L228-L232

**Comment by GrabYourPitchforks** [comment]
Maybe for wrapping exceptions? I agree it's atypical.

**Comment by eiriktsarpalis** [comment]
> Maybe for wrapping exceptions? I agree it's atypical.

One use case seems to be calling throw helpers inside expressions, using a `throw` directly results in much simpler code overall. Though it didn't seem like particularly common occurrence, at least in System.Text.Json.
