### ISSUE TITLE
QUIC port conflicts do not report an error

### ISSUE THREAD

**Issue by Tratcher** [dotnet/runtime#59382]
Scenario: Create a Kestrel based app with one endpoint. Set it to HTTP/3 only. Start two instances of the app.
```c#
webHost.ConfigureKestrel((context, options) =>
{
    options.ListenAnyIP(5001, listenOptions =>
    {
        listenOptions.UseHttps();
        listenOptions.Protocols = HttpProtocols.Http3;
    });
})
```
Expected: A port conflict should be reported.

Actual: No conflict errors are reported. All requests appear to be handled by the first instance.

Here's the conflict exception reported when using HTTP/1:
```
System.IO.IOException: Failed to bind to address https://[::]:5002: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint) in D:\github\aspnetcore\src\servers\kestrel\Transport.Sockets\src\SocketTransportOptions.cs:line 136
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind() in D:\github\aspnetcore\src\servers\kestrel\Transport.Sockets\src\SocketConnectionListener.cs:line 44
```

**Comment by wfurt** [comment]
cc: @nibanks

**Comment by nibanks** [comment]
Is this Windows specific? At least for Windows, it's an unfortunate byproduct of how per-CPU UDP socket sharing works.

**Comment by Tratcher** [comment]
Yes, this was tested on Windows.

**Comment by karelz** [comment]
@nibanks is there a workaround / fix that could be implemented in msquic to detect the situation?
Or disable load balancing between processes - even if it is opt-in, we could use it from .NET.

**Comment by nibanks** [comment]
Not that I know of, but I am following up with my team. I'll let you know if we come up with anything.

**Comment by thhous-msft** [comment]
BTW Linux will have the same issue as well. And especially because of how Linux is designed to specifically allow cross process socket sharing, I don't think this would be fixable on that platform.

**Comment by nibanks** [comment]
So it seems we found a solution on Windows: https://github.com/microsoft/msquic/pull/2017.

**Comment by nibanks** [comment]
We just merged this fix into MsQuic. It will be in the next prerelease (early this month most likely).

**Comment by nibanks** [comment]
(at least for Windows)

**Comment by wfurt** [comment]
We will need to turn the crank on https://github.com/dotnet/msquic and pull it in once built. 7.0/main is currently using main branch of msquic so the prerelease is independent.

**Comment by ManickaP** [comment]
Triage: won't fix since it's not fixable on Linux without gutting the perf. On windows we might get a fix in the future.
We should document as known issue: open issue in msquic for docs and point asp.net docs there.
