### ISSUE TITLE
SkipUseReferenceAssembly=true in ProjectReference is giving VS trouble to resolve some APIs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#59390]
@ViktorHofer 

When I open the `System.IO.FileSystem.AccessControl` solution in Visual Studio 2022 (either directly, or by calling `build.cmd -vs System.IO.FileSystem.AccessControl`), VS is unable to resolve some APIs correctly when I open some test files like [FileSystemAclExtensionsTests.cs](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.FileSystem.AccessControl/tests/FileSystemAclExtensionsTests.cs).

<details>
  <summary>This is what I see (expand):</summary>

![image](https://user-images.githubusercontent.com/1175054/134104116-e3f252c6-7436-4118-a4b6-356d1d904114.png)

</details>

The test csproj is importing the src csproj with the parameter `SkipUseReferenceAssembly=true`.

<details>
  <summary>If I remove it (and fix the path of the imported csproj), the issue goes away (expand):</summary>

![image](https://user-images.githubusercontent.com/1175054/134103638-ddc6fe42-a58a-4cd5-9d45-e9f36de1fe11.png)

</details>

But I'm keeping this change locally for now, as a workaround. I do not know if this problem has its root cause somewhere else, so I wanted to let you know first, since you introduced the attribute in a PR that affected many other csproj files: https://github.com/dotnet/runtime/pull/35606

**Comment by ViktorHofer** [comment]
@carlossanlop I can't repro this issue. Can you please try it again? My guess is that this got fixed by related infra changes.

**Comment by carlossanlop** [comment]
I didn't repro either. This issue is fixed, @ViktorHofer. Thanks! Closing.
