### ISSUE TITLE
DacDbiInterfaceImpl::IsModuleMapped returns S_FALSE without setting *isModuleMapped

### ISSUE THREAD

**Issue by delmyers** [dotnet/runtime#59393]
### Description

I'm seeing this while debugging a windows dump of a .NET 6 preview app. Essentially, when
querying the mapping mode of a dynamic module in an ASP.NET app, there is no PE image 
for the module, so IsModuleMapped returns S_FALSE without ever setting the out
variable. According to the SAL of the function, the value should be set. It makes sense
that the function should return false in the isModuleMapped out variable in this situation.

### Configuration

debugging a dump collected with the "createdump" app of a .NET 6 preview 7.21379.14 running an x86 ASP.NET app on Windows.

### Regression?

No. This is a new API

### Other information

This can be worked-around by setting the value of the output variable to false before calling the API, and by checking for S_OK instead of hr > 0 for success.

The fix should be rather simple. I can supply it. I also have a dump that exercises this code if it is helpful.

**Comment by tommcdon** [comment]
Thanks for reporting this issue! PR's are welcome.
cc @hoyosjs

**Comment by hoyosjs** [comment]
As you say, S_OK is the only case where the value should be trusted. We could definitely set it at the beginning of the public API in the DBI or in the DAC/DBI interface.

**Comment by delmyers** [comment]
I have a fix for this, build cmd is giving me the following errors when I try to build:

```
E:\dotnetruntime\.dotnet\sdk\6.0.100-rc.1.21430.12\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: File 'E:\dotnetruntime\artifacts\bin\coreclr\windows.x64.Debug\PDB\crossgen2.pdb' is not added because the package already contains file 'runtimes\win-x64\lib\net7.0\..\..\..\..\tools\crossgen2.pdb' [E:\dotnetruntime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
E:\dotnetruntime\.dotnet\sdk\6.0.100-rc.1.21430.12\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: File 'E:\dotnetruntime\artifacts\bin\coreclr\windows.x64.Debug\PDB\ILCompiler.DependencyAnalysisFramework.pdb' is not added because the package already contains file 'runtimes\win-x64\lib\net7.0\..\..\..\..\tools\ILCompiler.DependencyAnalysisFramework.pdb' [E:\dotnetruntime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
E:\dotnetruntime\.dotnet\sdk\6.0.100-rc.1.21430.12\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: File 'E:\dotnetruntime\artifacts\bin\coreclr\windows.x64.Debug\PDB\ILCompiler.Diagnostics.pdb' is not added because the package already contains file 'runtimes\win-x64\lib\net7.0\..\..\..\..\tools\ILCompiler.Diagnostics.pdb' [E:\dotnetruntime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
E:\dotnetruntime\.dotnet\sdk\6.0.100-rc.1.21430.12\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: File 'E:\dotnetruntime\artifacts\bin\coreclr\windows.x64.Debug\PDB\ILCompiler.ReadyToRun.pdb' is not added because the package already contains file 'runtimes\win-x64\lib\net7.0\..\..\..\..\tools\ILCompiler.ReadyToRun.pdb' [E:\dotnetruntime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
E:\dotnetruntime\.dotnet\sdk\6.0.100-rc.1.21430.12\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5118: File 'E:\dotnetruntime\artifacts\bin\coreclr\windows.x64.Debug\PDB\ILCompiler.TypeSystem.ReadyToRun.pdb' is not added because the package already contains file 'runtimes\win-x64\lib\net7.0\..\..\..\..\tools\ILCompiler.TypeSystem.ReadyToRun.pdb' [E:\dotnetruntime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
```
Any ideas waht I should do?

**Comment by hoyosjs** [comment]
That project is problematic. I'll not waste your time to diagnose it. For these purposes `build.cmd clr.runtime+clr.tools+clr.dactools+clr.corelib+clr.nativecorelib -c release` should get all you need to `artifacts\bin\coreclr\Windows.x64.Release\`, with the System.Private.CoreLib.dll there and the binaries under sharedFramework. You can't use the dump as the dump will mismatch. Do you have any other repro?

**Comment by delmyers** [comment]
> That project is problematic. I'll not waste your time to diagnose it. For these purposes `build.cmd clr.runtime+clr.tools+clr.dactools+clr.corelib+clr.nativecorelib -c release` should get all you need to `artifacts\bin\coreclr\Windows.x64.Release\`, with the System.Private.CoreLib.dll there and the binaries under sharedFramework. You can't use the dump as the dump will mismatch. Do you have any other repro?

OK, I'll try building with that command.

I can't use the same dump in order to test. I have not been able to get an error like this on any other scenario other than dumps. The module that is failing is a dynamic module for which the debugger cannot find the the loaded IL for the in-memory PEFile (if (pPEFile->HasLoadedIL()) fails). Potentially because the dump was taken at a non-gc-safe point? I don't really know why, but the PE file does not seem to be complete in this case.

In theory, I should be able to capture a dump by running the app under the newly built runtime in order to test, yes?

**Comment by hoyosjs** [comment]
Yes, that happens.
