### ISSUE TITLE
Compat: Revert behavior of DecoderNLS / EncoderNLS.Convert to match Full Framework

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#594]
## Background

Marked as __blocking-partner__ since a first-party partner is having trouble with deployment due to this.

In .NET Core 3.x, we made a change to how `Encoder.Convert` and `Decoder.Convert` work in order to fix how the _completed_ parameter's values are set on output and to bring the methods in line with the _Remarks_ section of [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.text.decoder.convert). See https://github.com/dotnet/coreclr/issues/23020 and https://github.com/dotnet/coreclr/issues/27191 for the original bugs.

Unfortunately the sample code in the _Examples_ section of [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.text.decoder.convert) relies on the old non-compliant behavior of these methods, and it's leading to regressions in applications which have used that sample code. See https://github.com/dotnet/corefx/issues/42423 for one example, where the application enters an infinite loop on some inputs.

## Proposed behavioral change

The proposal is to restore the _completed_ output parameter logic that was present in Full Framework and .NET Core 1.x / 2.x.

We've already identified some call sites that might regress as a result of backing out these changes, and work items are open for those issues. See https://github.com/aspnet/AspNetCore/pull/17747 for one example.

**Comment by danmosemsft** [comment]
Wasn't there a 3.1 change to make here? I don't see it.

**Comment by anurse** [comment]
Ping on this. Is a change for 3.1 coming in Feb? We have internal partners asking for it and a matching reaction we need to make (https://github.com/dotnet/aspnetcore/pull/17747).

**Comment by GrabYourPitchforks** [comment]
@anurse Still on track for Feb. Branch is open as of this morning and PR is https://github.com/dotnet/coreclr/pull/27996.

**Comment by anurse** [comment]
Awesome, we've got our reaction ready and approved and will include it in Feb as well.

**Comment by GrabYourPitchforks** [comment]
Closing because this change is now in all relevant branches.
