### ISSUE TITLE
`SlimSemaphore.WaitAsync` throws wrong exception type on cancellation before waiting

### ISSUE THREAD

**Issue by atifaziz** [dotnet/runtime#59402]
### Description

[`SlimSemaphore.WaitAsync(CancellationToken)`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim.waitasync) is documented to throw [`OperationCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.operationcanceledexception), but when the cancellation is requested at the time `WaitAsync` is called, it throws [`TaskCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception) instead.

For example, the following throws `OperationCanceledException` after a second:

```c#
using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
using var s = new SemaphoreSlim(0);
await s.WaitAsync(cts.Token).ConfigureAwait(false); // throws OperationCanceledException after a second
```

However, if the cancellation is request before entering the wait, a `TaskCanceledException` is thrown immediately:

```c#
using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
using var s = new SemaphoreSlim(0);
cts.Cancel(); // cancel before waiting
await s.WaitAsync(cts.Token).ConfigureAwait(false); // throws TaskCanceledException immediately
```

One would expect `OperationCanceledException` to be thrown irrespective of when the cancellation was requested, before or during the wait.

### Configuration

* Which version of .NET is the code running on? **5.0.10**
* What OS and version, and what distro if applicable? **Windows 10, Version 21H1 (OS Build 19043.1237)**
* What is the architecture (x64, x86, ARM, ARM64)? **Intel64 Family 6 Model 126 Stepping 5, GenuineIntel**
* Do you know whether it is specific to that configuration? **Yes, does not seem specific**
* If you're using Blazor, which web browser(s) do you see this issue in? **N/A**

### Regression?

I don't believe so, but I only checked against .NET Core runtime 3.1.19 and the same observation can be made there.

### Other information

I believe the problem may come from the following early bail-out for cancellation.

https://github.com/dotnet/runtime/blob/78593b9e095f974305b2033b465455e458e30267/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L609-L611

Incidentally, the tests for the _synchronous wait_ case check specifically that `OperationCanceledException` is thrown if cancellation is requested _before_ the wait:

https://github.com/dotnet/runtime/blob/e30c2004c63d81b3579cd894b357cfc51c5b2c8d/src/libraries/System.Threading/tests/SemaphoreSlimCancellationTests.cs#L11-L26

On the other hand, the [asynchronous wait test case](https://github.com/dotnet/runtime/blob/e30c2004c63d81b3579cd894b357cfc51c5b2c8d/src/libraries/System.Threading/tests/SemaphoreSlimCancellationTests.cs#L55) doesn't make the same assertion. Rather than asserting the resulting exception, it checks that the task was cancelled (and might explain how the discrepancy might have slipped):

https://github.com/dotnet/runtime/blob/e30c2004c63d81b3579cd894b357cfc51c5b2c8d/src/libraries/System.Threading/tests/SemaphoreSlimCancellationTests.cs#L70

### Workaround

A potential workaround via an extension method could be:

```c#
static class Extensions
{
    public static async Task FixedWaitAsync(this SemaphoreSlim semaphore, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        try
        {	        
            await semaphore.WaitAsync(cancellationToken).ConfigureAwait(false);
        }
        catch (TaskCanceledException ex)
        {
            throw new OperationCanceledException("The operation was canceled.", ex, ex.CancellationToken);
        }
    }
}
```

Ditto for other overloads of `WaitAsync`.

---
/cc @p-schuler

**Comment by stephentoub** [comment]
> when the cancellation is requested at the time WaitAsync is called, it throws TaskCanceledException instead

TaskCanceledException is an OperationCanceledException; the former derives from the latter.

**Comment by atifaziz** [comment]
Thanks for [that reminder](https://devblogs.microsoft.com/premier-developer/recommended-patterns-for-cancellationtoken/#handling-cancellation-exceptions), @stephentoub. 🤦🏽‍♂️ I guess seen from the relationship perspective between the two exceptions, the implementation is in line with the documentation even if it had me confused for a bit. I had an assertion reading `Assert.ThrowsExactly<OperationCanceledException>` that was triggering in some cases and not in others. The problem was being too strict with `ThrowsExactly`. Sorry for the false alarm.
