### ISSUE TITLE
Cannot change the ReadOnly file attribute

### ISSUE THREAD

**Issue by DenisRumyantsev** [dotnet/runtime#59406]
Hi, we maintain [the Azure DevOps pipeline agent](https://github.com/microsoft/azure-pipelines-agent), and I am currently working on [this issue](https://github.com/microsoft/azure-pipelines-agent/issues/3307). As I can see from provided logs, the error occurs when trying to change the `ReadOnly` file attribute from `true` to `false` during [this line](https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Sdk/Util/IOUtil.cs#L461) execution:

```cs
item.Attributes = item.Attributes & ~FileAttributes.ReadOnly;
```

The issue persists for the agent build with the `3.1.15` .NET runtime version and can be reproduced only on the `Linux-ARM64` architecture when trying to change the status of an empty file with a bad name. Example of such name: `_70@@ÿ__@8`. Such file appears during specific pipelines execution (its appearance does not depend on the agent).

There is a stack trace of this error:

```
System.ArgumentException: Invalid File or Directory attributes value. (Parameter 'Attributes')
   at System.IO.FileStatus.SetAttributes(String path, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.RemoveReadOnly(FileSystemInfo item)
```

**Comment by carlossanlop** [comment]
This issue with the `ReadOnly` flag (not being able to change it) was fixed in .NET 5.0+ : https://github.com/dotnet/runtime/pull/52235/

A workaround is to execute `chmod -r <filename>` with `System.Diagnostics.Process`, which will remove read-only rights to user, group and others at once.

@danmoseley @jeffhandley does this meet the bar for a backport to 3.1? The fix was large because it involved some refactoring due to having duplicate code changing attribute values.

**Comment by carlossanlop** [comment]
Actually, I was wrong - My test code was creating the file incorrectly, and the test was failing with the exact same callstack. I was then able to change the readonly attribute without issues in 3.1.

I noticed your method `RemoveReadOnly` is called in three places.

- In this place, you previously check if the file exists: https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Sdk/Util/IOUtil.cs#L200

- Here you check if the directory exists: https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Sdk/Util/IOUtil.cs#L82-L90

- But here, you don't check: https://github.com/microsoft/azure-pipelines-agent/blob/e25038c60732f8191de7b852f1759e094bd3cff2/src/Agent.Sdk/Util/IOUtil.cs#L127

Your log file is precisely reporting that the callstack comes from that third location:

```
 ---> System.ArgumentException: Invalid File or Directory attributes value. (Parameter 'Attributes')
   at System.IO.FileStatus.SetAttributes(String path, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.RemoveReadOnly(FileSystemInfo item)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass10_0.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
```

Which is consistent with my repro: You cannot set the attributes of a file or directory that does not exist.

@DenisRumyantsev can you add an `Exists` check right before calling `RemoveReadOnly` in that third case and see if that fixes it?

**Comment by danmoseley** [comment]
Doesn't this message simply mean that a bad value of FileAttributes is passed?
https://github.com/dotnet/corefx/blob/release/3.1/src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs#L108

if it was a missing file, it would throw FNFE instead.

**Comment by danmoseley** [comment]
never mind, I follow now. I guess it's for historical reasons that get of Attributes on a nonexistent file doesn't throw.
https://github.com/dotnet/corefx/blob/release/3.1/src/System.IO.FileSystem/src/System/IO/FileStatus.Unix.cs#L73-L74

**Comment by Jozkee** [comment]
> can you add an Exists check right before calling RemoveReadOnly in that third case and see if that fixes it?

@carlossanlop I don't think the `Exists` check will solve the problem because `RemoveReadOnly` already checks `if (item.Attributes.HasFlag(FileAttributes.ReadOnly))`, that should guard for non-existent files.

**Comment by Jozkee** [comment]
Actually, I take that back. 
When the file doesn't exists, `Attributes` will have a value of `-1`.

if you do `if (item.Attributes.HasFlag(FileAttributes.ReadOnly))` that will evaluate to true for 1 (the value of ReadOnly) and -1 (the not-exists value). 

Bottom line is, don't rely on that condition since it will be true when the file doesn't exists.

**Comment by DenisRumyantsev** [comment]
@Jozkee @carlossanlop at first, I thought that the file could not be found because of its bad name (maybe some troubles with encoding) or because it was missing at the moment of changing its attributes. Reasons why I doubt it now:

* An empty file with this name does exist and I can see it;

* When the file is missing, `item.Attributes.HasFlag(FileAttributes.ReadOnly)` actually returns `true` without an exception.
However, when executing the line of code `item.Attributes = item.Attributes & ~FileAttributes.ReadOnly;`
another exception is thrown when the file is missing, as @danmoseley have already mentioned above:

```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '<path_to_file>'.
File name: '<path_to_file>'
   at System.IO.FileSystem.SetAttributes(String fullPath, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
```

Actual exception stack-trace:

```
System.ArgumentException: Invalid File or Directory attributes value. (Parameter 'Attributes')
   at System.IO.FileStatus.SetAttributes(String path, FileAttributes attributes)
   at System.IO.FileSystemInfo.set_Attributes(FileAttributes value)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.RemoveReadOnly(FileSystemInfo item)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.<>c__DisplayClass10_0.<DeleteDirectory>b__0(FileSystemInfo item)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
```

I am going to implement additional checks and logging and return back to provide more info when receiving it.

**Comment by danmoseley** [comment]
Another option is to copy/paste the pinvokes into a test app to eliminate System.IO entirely.

**Comment by Jozkee** [comment]
@DenisRumyantsev were you able to solve this issue?

**Comment by Jozkee** [comment]
Will close this issue since I think this is related to performing `FileSystemInfo.Attributes.HasFlag(FileAttributes))` when `Attributes = -1`, @DenisRumyantsev please re-open if you think otherwise.
