### ISSUE TITLE
System.Speech.Tests fail GrammarBuilder test on non-English OS

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#59400]
### Description

`System.Speech.Tests` fail `SampleSynthesisTests.GrammarTests.GrammarBuilder` test on non-English OS with next exception `System.InvalidOperationException : The language for the grammar does not match the language of the speech recognizer.`

### Configuration
net7.0
Windows 10 (Russian)
x64

**Comment by danmoseley** [comment]
thanks for the report @AlexRadch . Could you share a callstack?

Do you have any interest in investigating a little? If not we can probably just disable on non-English. This code is essentially identical to .NET Framework and it sounds like all the other tests pass for you.

**Comment by AlexRadch** [comment]
Hi @danmoseley,

> thanks for the report @AlexRadch . Could you share a callstack?
```
      SampleSynthesisTests.GrammarTests.GrammarBuilder [FAIL]
        System.InvalidOperationException : The language for the grammar does not match the language of the speech recognizer.
        Stack Trace:
          D:\Code\runtime\src\libraries\System.Speech\src\Recognition\RecognizerBase.cs(2640,0): at System.Speech.Recognition.RecognizerBase.ThrowIfSapiErrorCode(SAPIErrorCodes errorCode)
          D:\Code\runtime\src\libraries\System.Speech\src\Recognition\RecognizerBase.cs(1630,0): at System.Speech.Recognition.RecognizerBase.LoadSapiGrammarFromCfg(SapiGrammar sapiGrammar, Grammar grammar, Uri baseUri, Boolean enabled, Single weight, Int32 priority)
          D:\Code\runtime\src\libraries\System.Speech\src\Recognition\RecognizerBase.cs(1426,0): at System.Speech.Recognition.RecognizerBase.LoadSapiGrammar(Grammar grammar, SapiGrammar sapiGrammar, Boolean enabled, Single weight, Int32 priority)
          D:\Code\runtime\src\libraries\System.Speech\src\Recognition\RecognizerBase.cs(64,0): at System.Speech.Recognition.RecognizerBase.LoadGrammar(Grammar grammar)
          D:\Code\runtime\src\libraries\System.Speech\src\Recognition\SpeechRecognitionEngine.cs(317,0): at System.Speech.Recognition.SpeechRecognitionEngine.LoadGrammar(Grammar grammar)
          D:\Code\runtime\src\libraries\System.Speech\tests\GrammarTests.cs(120,0): at SampleSynthesisTests.GrammarTests.GrammarBuilder()
```

> Do you have any interest in investigating a little? If not we can probably just disable on non-English. This code is essentially identical to .NET Framework and it sounds like all the other tests pass for you.

Yes, all other tests pass on my computer.
