### ISSUE TITLE
Make `mono` CSP Compliant

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/runtime#59416]
Whilst [investigating improving CSP compliance in Blazor](https://github.com/dotnet/aspnetcore/issues/34428), I found that Blazor WASM requires `unsafe-eval` due to mono's usage of `eval`:

https://github.com/dotnet/runtime/blob/96cb482d2dde661cc394e66c8ee94d5edecd1724/src/mono/wasm/runtime/library_mono.js#L745

This issue is to examine feasibility of removing this dependency on `eval` so that `unsafe-eval` is no longer required in the Blazor WASM CSP.

---

For reference, I found this [article](https://developers.google.com/web/fundamentals/security/csp/) to be helpful for understanding CSP peculiarities ([eval section](https://developers.google.com/web/fundamentals/security/csp/#eval_too)).

**Comment by lambdageek** [comment]
A naive search shows that `mono_wasm_call_function_on` is used by the debug proxy.  So perhaps we can move it to some JS lib that isn't used in released apps?

/cc @thaystg

**Comment by lewing** [comment]
> A naive search shows that `mono_wasm_call_function_on` is used by the debug proxy. So perhaps we can move it to some JS lib that isn't used in released apps?
> 
> /cc @thaystg

we could actually make the proxy inject the support methods and save some space

**Comment by Ponant** [comment]
@TanayParikh , it is great you out there are working on CSP cleanup.
Regarding the references for reading about CSP, you can find interesting ones here 
https://github.com/Ponant/Galebra.Security/tree/master/src/Galebra.Security.Headers.Csp

**Comment by lewing** [comment]
this is gone in main

**Comment by lewing** [comment]
yes
