### ISSUE TITLE
Environment.OSVersion returns "Windows NT 10.0.22458.0" on my Windows 11 22458.1000

### ISSUE THREAD

**Issue by mingtong** [dotnet/runtime#59427]
I am using .NET Framework 4.0.
Will the API return correct OS Version after Windows 11 released? 
Sorry, I mean, what OS Version will be returned after Windows 11 released?

**Comment by mingtong** [comment]
> .NET 4 just like .NET only returns what we get from the OS. There are likely other APIs you can directly call using p/invoke. But I'll throw this over to runtime for better guidance. The repos here only deal with .NET Core and .NET 5, not .NET Framework

 Thanks for your reply.
I just tried .NET 6, it still returns the same.

**Comment by jeffschwMSFT** [comment]
@danmoseley

**Comment by tannergooding** [comment]
This is simply the information reported by the OS.

Windows 11 is still `10.0.*.0` in the latest beta and (last I checked) internal preview builds:
![image](https://user-images.githubusercontent.com/10487869/134380133-a15c92b4-c12b-4c18-a0cf-dc76994ad322.png)

**Comment by danmoseley** [comment]
This is correct -- we just pass the Windows version through.

Note that macOS is a bit more complicated as it depends on what SDK we built with, and we decided not to fake it -- 
https://github.com/dotnet/runtime/issues/58575
https://github.com/dotnet/runtime/issues/41012

cc @wfurt

**Comment by danmoseley** [comment]
@mingtong for what purpose do you need to read the OS version? In theory logging/diagnostics is one of the few valid purposes. Generally it's not recommended to use the OS version to decide whether a feature is supported, because it might get supported later.

**Comment by mingtong** [comment]
> @mingtong for what purpose do you need to read the OS version? In theory logging/diagnostics is one of the few valid purposes. Generally it's not recommended to use the OS version to decide whether a feature is supported, because it might get supported later.

I pass the OS version to server, and server decide which data will be returned.

My App wants to support Windows 11 in advance, so I want to have it testable as early as possible, then once 11 be released, we can announce we support the latest Windows.

You said it's not recommended, then what is the best practice to do it?

**Comment by danmoseley** [comment]
@mingtong I see. Could you share why the server needs to know the OS version of the client? What is the data and how does it change? If you lied and told the server you were running on a Windows 10 client, would it be a problem?

**Comment by wfurt** [comment]
More discussion specific to Win11 is also here: https://github.com/dotnet/runtime/pull/58588
#59135 makes detections based on build number. Since Windows 11 is really just never Windows 10, is there specific functionality you are trying to detect @mingtong?

**Comment by mingtong** [comment]
> @mingtong I see. Could you share why the server needs to know the OS version of the client? What is the data and how does it change? If you lied and told the server you were running on a Windows 10 client, would it be a problem?

Some data is not expected to be shown on target OS.
If Windows 11 always return a version as Win 10, then it won't be a problem.
If  Windows 11 returns a version as Win 11, then current code needs to be refactored.

**Comment by danmoseley** [comment]
@mingtong but why is the version relevant -- why does the code need to be refactored? for what purpose is the version used?

If for example, you're checking whether a feature is supported, often there are more reliable ways to do this than checking a version number. Eg., GetProcAddress.
