### ISSUE TITLE
Standalone JIT build

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#59426]
I would like to better understand JIT internals, and in order to do that, I think building standalone JIT would be important.
If that's possible, I would not want compile whole coreclr for that.

So I decide to create small [repo](https://github.com/kant2002/myjit) where I can document steps for that.
I'm building on Linux, and have following error in CMake which indicates that I miss something

I configure cmake using 
```
cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER_ID=clang -DCMAKE_C_COMPILER_ID=clang
```
When compile, it fails with following error
```
In file included from ~/myjit/jit/alloc.cpp:4:
~/myjit/jit/jitpch.h:5:10: fatal error: windows.h: No such file or directory
    5 | #include <windows.h>
      |          ^~~~~~~~~~~
```

I'm bit puzzled, since I cannot find means how find this file during Linux builds.

**Comment by jkoritzinsky** [comment]
You can build with either `./build.sh clr.jit` or `./build.sh clr.alljits` to build only the jit and any support tools.

We currently don't support directly running `cmake` as there's various different properties that we set to get the build set up successfully (and these change as we improve our build infrastructure).

**Comment by kant2002** [comment]
That make sense. After playing a bit with build, I realize why it's better does not explain these things, too much things inter-dependent.
