### ISSUE TITLE
Http client certificate authorization Issue in .NET 5 in Docker

### ISSUE THREAD

**Issue by loga0060** [dotnet/runtime#59435]
### Description
We have a new project in .net 5 where the code is working in windows 10 but not working in Linux -- 

The issue is when trying to send a certificate authorized http request using httpclient to a partner API.  It only shows an SSLError when running on Linux(Docker/AKS)

here is my extension method to add certificate, cert is a pfx which i convert to X509Certificate2 
```c#
public static X509Certificate2 FindBySubject()
        {
            var filepath = @"CA Gateway cert.pfx";
            X509Certificate2 certificate = new X509Certificate2(filepath, "*******");
            return certificate;
        }
 public static class HttpClientHandlerExtensions
    {
        public static HttpClientHandler AddClientCertificate(this HttpClientHandler handler, X509Certificate2 certificate)
        {
            handler.ClientCertificates.Add(certificate);
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            return handler;
        }
  public static IHttpClientBuilder AddClientCertificate(this IHttpClientBuilder httpClientBuilder, X509Certificate2 certificate)
        {
            httpClientBuilder.ConfigureHttpMessageHandlerBuilder(builder =>
            {
                if (builder.PrimaryHandler is HttpClientHandler handler)
                {
                    handler.AddClientCertificate(certificate);
                }
                else
                {
                    throw new InvalidOperationException($"Only {typeof(HttpClientHandler).FullName} handler type is supported. Actual type: {builder.PrimaryHandler.GetType().FullName}");
                }
            });
            return httpClientBuilder;
        }
    }
```
### Configuration

Which version of .NET is the code running on?
.NET 5.0
What OS and version, and what distro if applicable?
Debian
What is the architecture (x64, x86, ARM, ARM64)?
x64
  

### Regression?
  Just started with .net 5

### Other information

I have tried the suggestions on #47580 and others still this error shows up

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
  -->

**Comment by wfurt** [comment]
Can you get packet capture and verify if the client certificate is sent on wire? And if so, does it go out with intermediate CAs? It may be best to compare working and not working case. 

Since you also mentioned Docker, all all the CAs (and anything related) accessible in your container?  
It may be also useful to cut all layers and try simple repro either via SslStream or simple HttpCLient.

**Comment by loga0060** [comment]
@wfurt thanks for the reply, We have resolved the issue after adding the intermediate CAs to the docker file 
COPY ["./test.crt", "/usr/local/share/ca-certificates/test.crt"]
COPY ["./testroot.crt", "/usr/local/share/ca-certificates/testroot.crt"]
RUN update-ca-certificates

**Comment by karelz** [comment]
@wfurt this seems to be a little bit repeating pattern, unless my memory is failing me.
Should we perhaps create some "how to" doc? With simple troubleshooting steps? (simple HelloWorld-style test, what to capture and what to look for)
