### ISSUE TITLE
Is ALPN support in OpenSSL a required feature?

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#59431]
This code doesn't make it clear: 

https://github.com/dotnet/runtime/blob/0ea3b7d8cf957508a94061b8e921b28d6f6becd6/src/libraries/Native/Unix/System.Security.Cryptography.Native/opensslshim.h#L462-L471

`SSL_set_alpn_protos` is required, but `SSL_CTX_set_alpn_protos` is a lightup? Is that right/intentional? Seems to me like both should be lightup (or both required).

Older versions of OpenSSL 1.0 don't have either of these symbols, and now the runtime fails when running against those.

**Comment by omajid** [comment]
cc @bartonjs @crummel

**Comment by omajid** [comment]
cc @wfurt

**Comment by wfurt** [comment]
I think the expectation is to support 1.0.2 or older. (unless we can kill it as will since that is unsupported by OpenSSL) 
And ALPN is essential for HTTP2.
I can look into why the expectation is different.

**Comment by bartonjs** [comment]
> and now the runtime fails when running against those.

What version(s) does that affect?  I thought we had coverage across 1.0.2+

**Comment by wfurt** [comment]
That would be great. There was similar issue with Ubuntu 14.04 ... but even the 16.04 way too old now and out os support. (should still work as we have it as part of CI matrix)

**Comment by wfurt** [comment]
BTW I just check and for Centos 7 I have OpenSSL 1.0.2k-fips.(and that should be sufficient)  Is that not available for rhel-7?

**Comment by omajid** [comment]
>  Is that not available for rhel-7

It is, or at least something close enough. CentOS rebuilds packages from RHEL, so I am going to be really really surprised if the latest RHEL package is older.

The issue that came up in the installer CI is only because an old container image is being used. It seems like this was the baseline RHEL 7 container created when .NET Core 1.0 was released, and it hasn't been updated since.

**Comment by wfurt** [comment]
nice. It is amazing that it lasted that long :)

**Comment by bartonjs** [comment]
While there's room for us to do a pass and find out what LIGHTUPs are actually expected to be REQUIRED based on minimums changing over time, I think the original question/problem has been resolved.
