### ISSUE TITLE
.NET 6 static abstract interface members in combination with static members fail with a MissingMethodException

### ISSUE THREAD

**Issue by Ronto4** [dotnet/runtime#59432]
### Description

When using an `abstract static` interface method and providing a `static` interface method in the code above it, running this program fails with a `System.MissingMethodException` if you are using a class (by somehow referencing it, e.g. declaring a variable of its type or by using a static method on it) implementing said interface in a method that gets called.

Example:

```C#
class Program
{
    static void Main()
    {
        Console.WriteLine("Start");
        SomeClass someInstance = new(); // line 6
        CalledMethod(); // line 7
        Console.WriteLine("Done");
    }

    static void CalledMethod()
    {
        SomeClass.SomeStaticMethodInClass();
    }
}

interface ISomeInterface
{
    static int SomeStaticMethod() => 42; // line 19
    static abstract int SomeStaticAbstractMethod(); // line 20
}

class SomeClass : ISomeInterface
{
    public static int SomeStaticAbstractMethod() => 42;
    public static int SomeStaticMethodInClass() => 42;
}
```
When running this code (`dotnet run`), I receive the following output:
```
Unhandled exception. System.MissingMethodException: Method not found: 'Int32 ISomeInterface.SomeStaticAbstractMethod()'.
```
When commenting out line 6, I get the following output:
```
Start
Unhandled exception. System.MissingMethodException: Method not found: 'Int32 ISomeInterface.SomeStaticAbstractMethod()'.
   at Program.CalledMethod()
   at Program.Main() in /path/to/Program.cs:line 7
```
Both problems can be fixed by either
1. commenting out line 19,
2. commenting out line 20, or
3. swapping lines 19 and 20, so that the `static` method is below the `static abstract` method.

Note three additional points:
1. All other methods in the interface (`static` methods below the `static abstract` one, normal `abstract` methods above or below, or more `static abstract` ones (that have to be above any `static` methods)) work as expected, as far as I could tell with some tests.
2. The program builds just fine, and it only throws the `MissingMethodException` if a called method contains a reference to a derived class of the interface. It's not important whether the reference is actually reached.
3. Referencing the interface itself, e.g. by calling its `static` method, works as expected (it just works).

### Configuration

- .NET version: 6.0.100-rc.1.21458.32
- `.csproj` settings: `TargetFramework`: `net6.0`; `ImplicitUsings`: `enable`; `LangVersion`: `preview`; `Nullable`: `enable`
- OS: Ubuntu 20.04.3 LTS amd64
- I have not tested it on other specifications (obviously it won't work on .NET 5 or older).

### Regression?

All I can say is that it will not work on anything not .NET 6 as `static abstract` interface members were introduced in this version.

### Other information

All stack traces are in the description section. I have no idea where this behavior may come from, which is caused by the fact that I know almost nothing about the inner workings of the .NET runtime.

As a workaround I can recommend placing all `static` methods in interfaces below all `static abstract` methods.

This is also my first issue here, so feel free to point out any information you may need that I didn't provide.

**Comment by mangod9** [comment]
@trylek @davidwrighton

**Comment by mangod9** [comment]
Moving to 7 based on the discussion in the PR
