### ISSUE TITLE
OperatingSystem.IsWindowsVersionAtLeast and SupportedOSPlatformAttribute using different version numbers for older Windows

### ISSUE THREAD

**Issue by mikestek** [dotnet/runtime#59433]
The current way that SupportedOSPlatformAttribute is documented and I see it being used is with the strings "windows7.0", "windows8.0", "windows8.1". 

This means when using OperatingSystem.IsWindowsVersionAtLeast the expected values to match those versions are (7,0) (8,0) (8,1)

But for older (pre Windows 10) versions of Windows the names and version numbers don't match so Windows 7 is actually Version 6.1, Windows 8 is Version 6.2 and Windows 8.1 is Version 6.3

This means that using OperatingSystem.IsWindowsVersionAtLeast with values that match the SupportedOSPlatformAttribute strings will not match.

If you use the versions of  (7,0) (8,0) (8,1) then it will not match at runtime. If you use  (6,1) (6,2) (6,3) then you will get compile warnings that you aren't properly checking for the required OS version.

**Comment by filipnavara** [comment]
Both of them should use the version numbers reported by the system (ie. 6.x). Some of the annotations were incorrect and fixed recently.

**Comment by filipnavara** [comment]
On second thought lot of the docs (https://github.com/dotnet/docs/blob/main/docs/standard/analyzers/platform-compat-analyzer.md) still use the marketing version numbers. I suppose it should be fixed and clarified.

**Comment by mikestek** [comment]
> On second thought lot of the docs (https://github.com/dotnet/docs/blob/main/docs/standard/analyzers/platform-compat-analyzer.md) still use the marketing version numbers. I suppose it should be fixed and clarified.

That's exactly where my confusion is coming from

**Comment by mikestek** [comment]
I've submitted this as an issue for the documentation. https://github.com/dotnet/docs/issues/26216

**Comment by dotMorten** [comment]
>Both of them should use the version numbers reported by the system (ie. 6.x).

This makes no sense to me. We use "10.0.xxxxxx.0" in the target framework. That's the number we're used to working with.

**Comment by filipnavara** [comment]
@dotMorten Windows 10 reports the 10.x version as long as you mark in application manifest (https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests) that you are aware of it. .NET creates the manifest for you in the apphost and it works at least since .NET 5.

**Comment by dotMorten** [comment]
@filipnavara That doesn't make any sense to me. Class libraries don't have that manifest for instance.

**Comment by filipnavara** [comment]
The manifest is always on the executable and it should always be there if you compile with the correct SDK. Version 6.1 is Windows 7, version 10.x is Windows 10, so it's normal to see both in the source code.

**Comment by dotMorten** [comment]
Gotcha, but gotta say this feels extremely error prone and un-intuitive to developers

**Comment by filipnavara** [comment]
> this feels extremely error prone

It is error prone but that's because of Windows versioning itself. It had a mismatch between the reported API version and the marketing version. That dates back all the way to Vista where Microsoft found out how many apps do the version check incorrectly and thus stopped bumping the major version not to break them. It was only rectified later by adding the option to the manifest that marks your application aware of the higher versions.

**Comment by dotMorten** [comment]
I get that. Doesn't mean the implementation needs to be that. Android for instance differs too and isn't reporting the OS version but the API Level.
