### ISSUE TITLE
superpmi: support Linux arm/arm64 benchmarks collection

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#59446]
https://github.com/dotnet/runtime/pull/47900 enabled a SuperPMI collection of the micro-benchmarks in the https://github.com/dotnet/performance repo.

However, by that PR:

> Currently, I have disable the collection for Linux arm/arm64 because it needs special handling to perform "dotnet MicroBenchmarks.dll" inside a $TMP folder because during execution of benchmarks, we also perform build of boiler plate code which is not allowed in docker since the directory is readonly.

This issue tracks enabling the collection for Linux arm/arm64.

**Comment by kunalspathak** [comment]
Fixed by https://github.com/dotnet/runtime/pull/74152
