### ISSUE TITLE
[API Proposal]: Add TrySelect

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#59463]
### Background and motivation

linq improvement

### API Proposal

```C#
namespace System.Linq
{
        public delegate TResult TrySelector<in T1, T2, out TResult>(T1 arg1, out T2 arg2);
	public static class Ext
	{
		public static IEnumerable<TResult> TrySelect<T, TResult>(this IEnumerable<T> enumerable, TrySelector<T, TResult, bool> trySelector)
		{
			foreach (var val in enumerable)
			{
				if (trySelector(val, out var res))
				{
					yield return res;
				}
			}
		}
	}
}
```     

### API Usage

```C#
foreach (var i in new[]{"1","2","3", "a"}.TrySelect((string v, out int r)=>int.TryParse(v, out r)))
{
				
}
//1,2,3
```     

### Risks

No

**Comment by huoyaoyuan** [comment]
I'd call it `SelectWhere`. It's quite useful to combine the two operations into one, since they often share duplicated calculations.

**Comment by kronic** [comment]
@huoyaoyuan the name is not important

**Comment by eiriktsarpalis** [comment]
I think it would be better if we could somehow avoid the addtional delegate type. F# call their equivalent method [`choose`](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#choose) but it works using an `Option<T>` construct.

**Comment by kronic** [comment]
@eiriktsarpalis What's wrong with adding delegate?

**Comment by eiriktsarpalis** [comment]
Closing per feedback.
