### ISSUE TITLE
`Microsoft.Extensions.Logging`'s `ILogger` should support providing a message in a function

### ISSUE THREAD

**Issue by YarekTyshchenko** [dotnet/runtime#59469]
### Is your feature request related to a problem? Please describe.
Some log messages require computation to generate that is wasted if the log level is turned off. Example: Trace logging that serialises large objects to display in logs, those serialisations still run when the trace logging is turned off

### Describe the solution you'd like
Allow wrapping the message in a closure / lambda:

```csharp
this.Logger.LogTrace(_ => $"Message that is computed only when the Trace level is displayed");`
```

This allows users to put all the expensive computation into the lambda:

```csharp
this.Logger.LogTrace(_ => {
    var serialisedData = data.Serialise();
    return $"The data is currently {serialisedData}";
});
```

### Additional context
I'm aware that there are other logging frameworks that do have this feature, but for now the built in logging is mostly sufficient for my usecase. It would be nice to also meet the above too.

**Comment by svick** [comment]
Note that if `ILogger` added support for [the new C# 10/.Net 6 string interpolation](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/), then you could write just `this.Logger.LogTrace($"The data is currently {data.Serialise()}");`, and it would compile into efficient code like:

```c#
var logger = Logger;
var handler = new TraceLoggerInterpolatedStringHandler(22, 1, logger, out bool shouldAppend);
if (shouldAppend)
{
    handler.AppendLiteral("The data is currently ");
    handler.AppendFormatted(data.Serialise());
}
logger.LogTrace(ref handler);
```

Here, `shouldAppend` would be set based on `logger.IsEnabled()`.

**Comment by MithrilMan** [comment]
The syntax above doesn't support structured logs. Is just string interpolation that generate a plain string, correct?

Would be nice to have logging source generator to use structured log like now plus the ability to execute its arguments (when arguments are expressions) only if log is enabled, preventing the need to surround logging calls with the logger.IsEnabled check and use of `SkipEnabledCheck` parameter on `LoggerMessageAttribute`

But I suspect this isn't currently technically possible

**Comment by maryamariyan** [comment]
As @gfoidl suggested if you would like to guard expensive logic for logging it's expected to wrap it around `IsEnabled` check.

For more information about how we ended up at the current design with logging source generator you could refer to this document: https://github.com/dotnet/designs/blob/main/accepted/2021/logging-generator.md#benefits-with-the-string-interpolation-builder-approach where it states how we also considered a string interpolation builder approach while ending up with the current design.

Closing issue as won't fix.
