### ISSUE TITLE
[API Proposal]: bool HashSet<T>.Update(T value, out T actual)

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#59468]
### Background and motivation

```C# 
public struct Item<TKey, TValue> : IEquatable<Item<TKey,TValue>>
{
   public TKey Key; // item1 == item2 means item1.Key == item2.key, values can be different
   public TValue Value;
   public bool Equals(Item<T> other) => Equals(Key, other.Key);
   public override int GetHashCode() => Key.GetHashCode();
}

// HashSet<Item<string,string> set;
var item = new Item<string,string>() {Key = someKey, Value = someValue};
if (set.TryGetValue(item, out var actual) // 1st search
{
   if (Equals(actual.Value, item.Value) return; // set contains actual data

   ...
   // do something with actual.Value
   ...

   // set.Add(item) --> false, we have no way to update item

   set.Remove(actual); // 2nd search 
   set.Add(item); // 3rd search
} 
else set.Add(item); // 2nd search
```

in this example if item exists, we have to search 3 times to update item with new Value
if not exists - 2 times

### API Proposal

add 
```C#
// returns true if item exists and updated, false if added
public bool Update(T value, out T actual) {...}

// returns true if item removed and take out removed value
public bool Remove(T value, out T actual) {...}
```   

In any case, we will search one time

### API Usage

```C#
if (set.Update(item, out var actual) {
   // do something with actual.Value
}
```  

```C#
if (set.Remove(item, out var actual) {
   // do something with actual.Value
}
```

**Comment by svick** [comment]
Why are you using `HashSet<T>` for storing key-value pairs, instead of using `Dictionary<K, V>`, which (mostly) already has the methods that you're looking for?

**Comment by kefyru** [comment]
Dictionary does not have methods to update value.
We can just set value by key (with no information about previous value).
Or try add...
```C#
// Dictionary<int,int> d;
if (d.TryGetValue(1, out actual) DoSomething(actual); // 1st search
d[1] = newValue; //2nd search
```
if it would be some method like ```C# d.Set(key, newVal, out actual)```...
Anyway, HashSet takes less memory i think, and should return value faster than dictionary, because dictionary has to find key (1), then from key takes index of value, then takes value (2). HashSet does it in one step. In big collection it may be faster, because all data contained in one memory segment.

**Comment by huoyaoyuan** [comment]
You can use `CollectionsMarshal.GetValueRefOrAddDefault` to achieve in one search.

**Comment by svick** [comment]
> Dictionary does not have methods to update value.

[It does on .Net 6, in the `CollectionsMarshal` class, using `ref` returns.](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.collectionsmarshal?view=net-6.0&WT.mc_id=DOP-MVP-5002735) With that, you can implement your `Set` like this:

```c#
public static bool SetOrAdd<TKey, TValue>(
    this Dictionary<TKey, TValue> dictionary, TKey key, TValue newValue, out TValue oldValueOrDefault)
{
    ref TValue value = ref CollectionsMarshal.GetValueRefOrAddDefault(dictionary, key, out bool exists);
    oldValueOrDefault = value;
    value = newValue;
    return exists;
}
```

**Comment by krwq** [comment]
@kefyru does solution suggest by @svick sound good to you or do you think the APIs would still be useful?

**Comment by kefyru** [comment]
Yes it is. Thanks.

**Comment by krwq** [comment]
Thanks for confirmation @kefyru! I'll close the issue since there is no action left here. Feel free to re-open if you feel there is something we should do here
