### ISSUE TITLE
System.Text.Json: Guid from JsonElement not valid.

### ISSUE THREAD

**Issue by AntonIOIOIO** [dotnet/runtime#59474]
### Description

When you call GetGuid() from JsonElement the only valid format is 00000000-0000-0000-0000-000000000000? 

Why is that?

https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Node/JsonString.cs

The code is hardcoded to "D".
public Guid GetGuid() => Guid.ParseExact(_value, "D");

**Comment by ryank425** [comment]
https://github.com/dotnet/runtime/issues/30692#issuecomment-581164186

**Comment by layomia** [comment]
Closing as a dup of https://github.com/dotnet/runtime/issues/30692.

@ryank425 I don't see how a custom converter would work here since that is used for `JsonSerializer` support and also in the `JsonNode.WriteTo` hierarchical implentations (but not for reading).

**Comment by layomia** [comment]
@AntonIOIOIO do you have a blocking scenario where this extended support would be useful?

**Comment by AntonIOIOIO** [comment]
No blocking. We can always just call GetString and wrap that in a Guide.Parse.
But it is very weird that the GetGuid can throw on valid Guid, that is not at all helpful to anybody. We just need a overload, don't know why it was hardcoded in the first place.
