### ISSUE TITLE
Intercept the Http Requests in asp.net MVC using c#

### ISSUE THREAD

**Issue by Saipavan018** [dotnet/runtime#59472]
Hi all,

     How to intercept the Http Requests in asp.net MVC application without changing the source code 
    Anyone help me on this..

Thank you

**Comment by karelz** [comment]
@Saipavan018 can you please be more specific? What do you mean by interpret?
Are you trying to respond to a request on server side via MVC? Or are you creating new requests to backend pages?

**Comment by Saipavan018** [comment]
Hi  @karelz 
My things is we have two applications like clientside application and own application
If we run the application intercept the  function call before CLR execution without changing the source code
It is possible in java using java agent and instrumentation api of byte buddy

I think it is possible in .net but how to implement I don't know can u help me

**Comment by karelz** [comment]
@Saipavan018 I still don't understand what you're trying to achieve. Can you please start with basic questions:
- Are you talking about server side or client side?
- Are you trying to modify request on server, before ASP.NET processes it?

**Comment by Saipavan018** [comment]
Ok @karelz 
Can u please check this url https://sudonull.com/post/79373-Intercepting-NET-CLR-Functions

Please read the link And help me

**Comment by karelz** [comment]
@Saipavan018 the article describes how to hack on internal data structures of the Runtime. That is fragile, entirely unsupported and highly discouraged. It is good for learning how things work behind the scenes, but not for applications.

It is not clear to me still how that article is related to HTTP requests and MVC app.
Are you trying to inject code or modify code of existing application which you cannot recompile? Is that the problem you are facing?

**Comment by Saipavan018** [comment]
Ha yes  inject the code or modify the code at runtime without changing the source code

**Comment by karelz** [comment]
The only supported approach is to use Profiler APIs -- the goal is to enable profilers to inject instrumentation, etc. Overall, such approach has diagnostic-only solutions.
Hacks like the article you linked are unsupported and fragile as the underlying infra can change without warning at any moment, incl. servicing or security updates, so it is not reliable.

I would consider your question answered and recommend to close it.
