### ISSUE TITLE
ActiveIssue not skipped on CI for iOS/tvOS devices in Release Configuration

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#59488]
`System.Collections.Generic.Tests.ComparerTests.NullableComparisons<Int32>` is not being skipped on CI as evidenced by this [build result](https://dev.azure.com/dnceng/public/_build/results?buildId=1375633&view=ms.vss-test-web.build-test-results-tab&runId=40122362&resultId=108435&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab) even though there is an `ActiveIssue` attribute https://github.com/dotnet/runtime/blob/41e86773243ae6471ff26eb74e327c04e14e8a67/src/libraries/System.Collections/tests/Generic/Comparers/Comparer.Tests.cs#L238

Oddly enough, running the suite locally on iOSSimulator and on iOS (local iPad), the test is skipped.

**Comment by mdh1418** [comment]
Looks like the test started failing since 9/17? https://dev.azure.com/dnceng/public/_test/analytics?definitionId=924&contextType=build
Not sure why it would be considered a pass before then if it is supposed to be skipped.

**Comment by mdh1418** [comment]
![Screen Shot 2021-09-22 at 16 09 04](https://user-images.githubusercontent.com/16830051/134414551-56c2e2e2-6d26-487a-b063-bd12bba8f199.png)
This is the first instance of the test failing (ActiveIssue not being skipped)
Which seems to point at https://github.com/dotnet/runtime/pull/57326, and it has been flakey (in skipping this ActiveIssue attribute)

**Comment by mdh1418** [comment]
Filtered on iOS arm64 and tvOS arm64 test runs.
![Screen Shot 2021-09-23 at 11 05 45](https://user-images.githubusercontent.com/16830051/134533179-77bc2d6c-de5f-48de-9362-7c98757dfac6.png)

**Comment by mdh1418** [comment]
Looks like this is a Release configuration specific problem. on iOS arm64 release, tests are failing, and this ActiveIssue is being skipped, the reason why only this test was caught was because we are only running a small subset of test suites at the moment for devices. When adding an [ActiveIssue("", TestPlatforms.iOS)] to a test in System.Buffers, the test is still ran when in iOS arm64 Release.

**Comment by safern** [comment]
We don't do much special logic for ActiveIssue, we just check if we are running on that platform:
https://github.com/dotnet/arcade/blob/e43b85e9b4e9ca62b89e407acdf0e56a2cbfd81a/src/Microsoft.DotNet.XUnitExtensions/src/DiscovererHelpers.cs#L28

https://github.com/dotnet/arcade/blob/e43b85e9b4e9ca62b89e407acdf0e56a2cbfd81a/src/Microsoft.DotNet.XUnitExtensions/src/DiscovererHelpers.cs#L29

So maybe something else is happening in `RuntimeInformation.IsOSPlatform`? 

cc: @steveisok

**Comment by steveisok** [comment]
`IsOSPlatform` looks good.  We're trimming in our test runs, so we're trying to see what things are like w/o it.

**Comment by steveisok** [comment]
No better... An untrimmed app build in release fails the same way.

**Comment by steveisok** [comment]
I found why and we should be able to work around it.  

https://github.com/dotnet/arcade/blob/9ab314e39dc623d53c3c7a63a6f63772b01ff6b3/src/Microsoft.DotNet.XUnitExtensions/src/DiscovererHelpers.cs#L17

This returns false because in release mode, `Environment.Version.Major` returns 0 and `RuntimeInformation.FrameworkDescription` returns ".NET".  It's not clear why the version returns 0.

**Comment by steveisok** [comment]
We'll need an arcade bump in order to take https://github.com/dotnet/arcade/pull/7965

That should fix the problem.

**Comment by steveisok** [comment]
> Looks like a bug when running on iOS/tvOS?

On the version, for sure.  I don't know why yet.  I've ruled out the linker on my end.  The only other thing that mucks w/ the assemblies is `ILStrip`.  I have yet to run w/ that task disabled.  That's the next thing I'm going to try.

**Comment by steveisok** [comment]
Confirmed this is no longer an issue.
