### ISSUE TITLE
System.Text.Json: make not-generic JsonConverter constructor public

### ISSUE THREAD

**Issue by raffaeler** [dotnet/runtime#59493]
### Background and motivation

**Background**: I am creating custom Json Converters using code generation.
I create them using the JsonConverterFactory and I currently need to use `Activator.CreateInstance` to create the generic `JsonConverter<T>` which is totally useless because I dynamically generate the code.
I would rather want to "new" my JsonConverter avoiding `Activator.CreateInstance` at all.

**Motivation**: performance.

### API Proposal

```C#
namespace System.Text.Json.Serialization
{
    public abstract class JsonConverter
    {
        public JsonConverter() { }
        public abstract bool CanConvert(Type typeToConvert);
        internal virtual Type TypeToConvert => null;
    }
}
```     

The current implementation has **`internal`**` JsonConverter() { }`

### API Usage

```C#
public class MyConverter : JsonConverter
{
 // ...
}
```     

### Risks

I currently see no risks

**Comment by fbrosseau** [comment]
Obviously being able to `new` would be the top performance, but if you are going to be generating code either way, couldn't you create a factory method that you bind a delegate to? That should be almost ideal too.

**Comment by huoyaoyuan** [comment]
> I create them using the `JsonConverterFactory` and I currently need to use `Activator.CreateInstance` to create the generic `JsonConverter<T>` which is totally useless because I dynamically generate the code.

What code are you generating?

The typical usage of `JsonConverterFactory` can't avoid such reflection, since it's moving applying a `Type` to `<T>`.

**Comment by raffaeler** [comment]
> What code are you generating?
I generate (using Linq Expressions) a delegate for the `Read` and another for the `Write`.
As the expressions can't generate types, I can't generate the whole JsonConverter. I could use Roslyn for that but the compilation process (first run) would be hugely slower.

> The typical usage of JsonConverterFactory can't avoid such reflection, since it's moving applying a Type to <T>.
If the constructor for `JsonConverter` was public, there will be no need to create my converter by reflection. It would suffice a simple new (which is faster).
I definitely can avoid all the reflection because I generate a lambda.

I forgot to mention there would be also the need to expose the untyped versions of `Read` and `Write`. Sorry for that.

**Comment by huoyaoyuan** [comment]
> I forgot to mention there would be also the need to expose the untyped versions of `Read` and `Write`. Sorry for that.

System.Text.Json works differently from Newtonsoft.Json. Generic `JsonConverter<T>` is used by generic `JsonPropertyInfo<T>`, which directly assigns typed fields. Maybe you need more example for how would you implement the converter.

**Comment by raffaeler** [comment]
> Maybe you need more example for how would you implement the converter.

I don't get this.
The converter is up and running. I don't need `T` because I just use the `System.Type`.
The generated expressions are typed of course. But this perf hit is just occurs the first time.

**Comment by huoyaoyuan** [comment]
> The generated expressions are typed of course.

I mean how would you use the generated expression? Create a delegate, which is still typed? Or box with `object` somehow?

**Comment by raffaeler** [comment]
> I mean how would you use the generated expression? Create a delegate, which is still typed? Or box with object somehow?

If the read / write passes the root object as `object`, it would be boxed only in the minor cases of value types. The expression can just cast the object to the correct type in the generated code.

**Comment by huoyaoyuan** [comment]
> If the read / write passes the root object as object

https://github.com/dotnet/runtime/blob/bfaa457c804efb9247f495b7e04444b2bf216308/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Helpers.cs#L73-L83

Interesting. The generic method is preferred, but the non-generic path does exist too.

**Comment by eiriktsarpalis** [comment]
> Interesting. The generic method is preferred, but the boxing path does exist too.

Note that this only happens in root-object serialization to accommodate to users passing untyped parameters. In general though the STJ infrastructure requires (correctly in my view) that every value of type `T` should be handled by a `JsonConverter<T>` instance. See for example 
https://github.com/dotnet/runtime/blob/097637261b2ee0ca0c11f240bddf0b48a29d379b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfoOfT.cs#L226 
or
https://github.com/dotnet/runtime/blob/097637261b2ee0ca0c11f240bddf0b48a29d379b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/JsonCollectionConverter.cs#L28
In other words, having a non-generic `JsonConverter` might work fine if only acting on root-level types, however it would fail as soon you started looking at serializing nested values.

@raffaeler I'm not sure I understand your issue, could you share a code sample that demonstrates it? You should still be able to generate dynamic methods that depend on a generic parameter provided that the parameter is in scope at the method generation site ([here's how STJ does this](https://github.com/dotnet/runtime/blob/097637261b2ee0ca0c11f240bddf0b48a29d379b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/ReflectionEmitMemberAccessor.cs#L227)). If you want to avoid emitting code for every generic instantiation you can always fall back to `AssemblyBuilder`/`TypeBuilder` but that takes considerably more effort to get right.

**Comment by raffaeler** [comment]
> In other words, having a non-generic JsonConverter might work fine if only acting on root-level types, however it would fail as soon you started looking at serializing nested values.

By the way, this would perfectly work in my use-case.

> I'm not sure I understand your issue [...]

If you look back to my initial post, you will see I have the problem only in the Factory «I create them using the JsonConverterFactory »
In other words:
- I am perfectly fine in generating the code for `Read` and `Write`. I am already doing it and they are faster than the default implementation.
- I am trying to avoid the `CreateInstance` of the typed converter within the `JsonConverterFactory`, that's all.

It is not a big waste of time, but every code-generation scenario falls in this issue.

**Comment by eiriktsarpalis** [comment]
> I am perfectly fine in generating the code for Read and Write. I am already doing it and they are faster than the default implementation.
> I am trying to avoid the CreateInstance of the typed converter within the JsonConverterFactory, that's all.

So I'm assuming your motivations are performance-related? Skipping the additional checks done by the `JsonConverter<T>.Write`/`Read` methods? Or something different?

**Comment by raffaeler** [comment]
> So I'm assuming your motivations are performance-related? 

Yes, as I wrote in the motivations

> Skipping the additional checks done by the JsonConverter<T>.Write/Read methods? Or something different?

Let's start skipping `Activator.CreateInstance` in the factory. Of course, any other additional code that may be avoided is welcome.

**Comment by eiriktsarpalis** [comment]
> > Skipping the additional checks done by the JsonConverter.Write/Read methods? Or something different?
>
> Let's start skipping Activator.CreateInstance in the factory.

This is our recommended pattern when writing factories. Can I ask why you think it shouldn't be used? Note that any reflection costs are paid once on the first serialization, instances are cached for subsequent uses.

**Comment by raffaeler** [comment]
> This is our recommended pattern when writing factories. Can I ask why you think it shouldn't be used? Note that any reflection costs are paid once on the first serialization, instances are cached for subsequent uses.

I have to pass a parameter to the factory, so that they are passed to my converter.
This parameter contains type-specific information as well as some storage to cache the delegates.

Therefore, it cannot be cached for more than one type.
Anyway, I am not able to quantify the loss of perf since I can't use the untyped version.

In my experience, when generating code, the untyped version is always the best way to proceed (even when I generated typed code). The untyped is the bridge to the generated code.
For example, in the past I had huge troubles with `IObservable<T>` just because there is no `IObservable`.

**Comment by eiriktsarpalis** [comment]
> In my experience, when generating code, the untyped version is always the best way to proceed (even when I generated typed code). The untyped is the bridge to the generated code. For example, in the past I had huge troubles with IObservable<T> just because there is no IObservable.

That does not necessarily align with my personal experience, generic code does lead to improved performance since it allows the JIT to optimize for the particular type and eliminate boxing/runtime type testing. 

Out of curiosity, would using a `JsonConverter<object>` not solve your particular problem?

**Comment by raffaeler** [comment]
I believe you are misunderstanding.
At development time you do not know the type that will be serialized.
At runtime, you will discover the type that will need to be serialized. But this type will be passed as `Type` and not a generic type `T`.
This means the following:
- Yes, typed code is better, in fact the generated code is entirely typed and never deals with `object`
- At development time you have no way to know the type `T`. The factory should take a `Type` and not `T` simply because this is how code generation can work

With regards to `JsonConverter<object>`, while I can cast to my type in the generated code, I am not sure on the performance impact for value types. Frankly I don't like this solution, but I can make some micro benchmark to see if I can gain something on the reference types.

**Comment by eiriktsarpalis** [comment]
>  At development time you do not know the type that will be serialized. At runtime, you will discover the type that will need to be serialized. But this type will be passed as Type and not a generic type T.

That's the point of the converter factory: you can convert a `Type` instance to a generic type T using the `Type.MakeGenericType` method in conjuction with `Activator.CreateInstance`. Here's [an example](https://github.com/dotnet/runtime/blob/d698901a80227b985ae8e33c7ce138d186bed0ed/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/NullableConverterFactory.cs#L50) taken from our NullableConverterFactory implementation.

**Comment by raffaeler** [comment]
So we are back to the very beginning.
What you wrote is **exactly** what I am currently doing.
Anyway, I would really like to avoid the `Activator.CreateInstance` as a `new` of a non-generic `JsonConverter` would be faster.

**Comment by eiriktsarpalis** [comment]
> Anyway, I would really like to avoid the Activator.CreateInstance as a new of a non-generic JsonConverter would be faster.

While technically correct, the instance is cached for future use so any performance penalties would get amortized throughout the application's lifetime. 

> So we are back to the very beginning.

I think we might be talking past eachother. A standalone console app that illustrates what you are trying to do (and quantifies the performance issues you are facing) might help.

**Comment by raffaeler** [comment]
> I think we might be talking past eachother. A standalone console app that illustrates what you are trying to do (and quantifies the performance issues you are facing) might help.

The relevant code is the one I posted. All the rest is very complex, has external dependencies and useless to this specific discussion.

The reason why I posted here is because, thanks to code generation, not only I obtain better perf (easy part) but I also generate the JSON for a different model (matching the model of the consumer). And of course is symmetrical when deserializing.
Thanks anyway

**Comment by eiriktsarpalis** [comment]
It is not possible to opt out of caching JsonConverter instances. The infrastructure will generally associate a single converter instance per type (with the sole exception being property-level `JsonConverterAttribute` declarations). As mentioned already a `T` type that is not assignable from the type of the serialized document is not supported and will generally result in errors when attempting to use the converter in a nested document.

> Therefore, the JSON converter does not necessarily have all the required parameters to perform the conversion.

I'm not sure what additional parameters would be required per instance. Perhaps a code sample illustrating what the converter is trying to achieve might provide clarity.

**Comment by eiriktsarpalis** [comment]
> The JSON Converter I created is very complex with a lot of dependencies, I can't simply publish a snippet as it would be meaningless.

Surely it could be trimmed down to a minimal sample? I understand that it might be time consuming to achieve, but it might lead me to provide better recommendation or consider improvements to the existing API.

> Ideally, the serialization and deserialization converters should be different. As this is not supported by the infrastructure, I am trying to do this by configuration, but some of the required parameters may be become available at a later time (run-time).

I understand the concern, however the current converter design requires one instance responsible for both serialization and deserialization concerns. For cases where serialization and deserialization are "asymmetric" I would recommend applying the DTO pattern and issue separate types/converters for each scenario.

**Comment by raffaeler** [comment]
> Surely it could be trimmed down to a minimal sample?

OMG the entire code is dynamically generated. The constructor just have a lot of parameters that are given to the generator. I don't believe this would be very helpful or readable without the entire context.

The goal is avoiding DTOs for perf reasons.
I can serialize/deserialize model A into model B regardless the difference of structure in the graph or even the data types.
This works but I would like to make it more dynamic so that if a new version pops up, I can change the converter instead of creating a parallel mechanism to inform the cached converter.
