### ISSUE TITLE
Right shift of specific BigInteger values is producing incorrect results

### ISSUE THREAD

**Issue by slozier** [dotnet/runtime#59509]
### Description

In the following example we start off with `-0x1ffffffff`, left shift by 31 bits and then right shift by 31 bits. The expected result would be `-0x1ffffffff` but we're getting `-0x100000001ffffffff`.

```C#
BigInteger x = -8589934591;
BigInteger y = (x << 31) >> 31;

Debug.Assert(x == y);
```

### Configuration

Running on .NET 6.0.100-rc.1.21458.32

### Regression

This is a regression from .NET Framework/.NET Core/.NET 5.

### Other information

Might be related to the fix in https://github.com/dotnet/runtime/pull/54115

@tannergooding

**Comment by wzchua** [comment]
Hmm, I'll look into this
