### ISSUE TITLE
Question: are any of the latest GC improvements available to .net core 2.1 (UWP)?

### ISSUE THREAD

**Issue by jtorjo** [dotnet/runtime#59517]
Hi, 

I'm talking about https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/

I know they are for .net 5, but since we're talking about the GC, I'm still hoping they can apply to older versions as well.

I'm asking because the GC on .net core 2.1 is horrible, and I've already spent days trying to optimize my code to avoid those pesky GC pauses, and I've got pretty much nothing to show for.

**Comment by huoyaoyuan** [comment]
There shouldn't be. Although 2.1 was still in LTS lifetime during years, only security patches will be applied.

**Comment by jtorjo** [comment]
@huoyaoyuan Thanks! Yeah, that's insanely sad...

**Comment by martincostello** [comment]
2.1 is no longer supported _at all_ and you should move onto at least 3.1, otherwise you're using a runtime that will receive no patches for future security issues and vulnerabilities.

**Comment by huoyaoyuan** [comment]
> 2.1 is no longer supported at all and you should move onto at least 3.1

UWP was a fork of 2.1 and supported separatedly. We can't update the runtime of UWP right now, which has been requested for years.

**Comment by mangod9** [comment]
Currently there are no specific plans to port .net 5 (or 6) GC features to previous releases. There are some specific changes that sometimes get backported but that is a rarity.

**Comment by jtorjo** [comment]
Yeah, that's beyond sad.
