### ISSUE TITLE
JsonSourceGenerator runs twice?

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#59539]
### Description

I am trying to use JsonSerializable attribute in Blazor project, to exercise the json source generator. I am getting multiple errors about duplicit definitions.

In the Analyzers section of Dependencies in VS I see the `System.Text.Json.SourceGeneration.dll` listed twice, so it looks like the generator might be running 2 times? It is the same version of it in 2 locations, `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.1.21451.13\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll` and `~\.nuget\packages\system.text.json\6.0.0-rc.1.21451.13\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll`

### Configuration

Windows 10/x64
Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 4.1 [31717.71.d17.0]

### Other information

Repro:  https://github.com/radekdoulik/BlazorAppWithJSONSerialization/tree/try-to-use-json-serialization-generator
Build output: https://gist.github.com/radekdoulik/ed442d531f574e99407e924ffd617ad2

**Comment by layomia** [comment]
I was able to repro this on `6.0.100-rc.1.21463.6`, but the warnings went away using the latest [RC 2 SDK version](https://github.com/dotnet/installer#installers-and-binaries) (6.0.100-rc.2.21474.16) and installing `wasm-tools` as instructed by the SDK (`dotnet workload install wasm-tools`).

Please let us know if you still face issues here.

cc @eerhardt @ericstj @pranavkm.

**Comment by ericstj** [comment]
> C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0-rc.1.21451.13\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll and ~\.nuget\packages\system.text.json\6.0.0-rc.1.21451.13\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll

In this case these packages are the same version, we rely on conflict resolution dropping the OOB one (preferring inbox).  The rule that makes that win was broken up until https://github.com/dotnet/sdk/pull/19878 (thanks @rainersigwald).
