### ISSUE TITLE
Tasks required for servicing 6.0.1

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#59533]
- [x]  Branding Update to 6.0.1
 - [x]  update the emsdk version if not updated automatically
 - [x] correctly set GeneratePackageOnBuild
  
``` <GeneratePackageOnBuild Condition="'$(BuildAllConfigurations)' != 'true' and '$(IsRIDSpecificProject)' != 'true' and '$(PreReleaseVersionLabel)' == 'servicing' and '$(GitHubRepositoryName)' != `'runtimelab'">false</GeneratePackageOnBuild>```

- [x] Packages that need to be produced with every servicing build are WindowsDesktopTransportPackage, Coreclr Packages, mono packages, runtime packs
- [x]  Enable ref pack validation. (apicompat and assembly version)

**Comment by ViktorHofer** [comment]
>  correctly set GeneratePackageOnBuild

What's wrong about the current condition? Just checked https://github.com/dotnet/runtime/blob/44b44501c76c46bd79ee52b7d9a9d8a4957fc85f/eng/packaging.targets#L21-L24 and it looks right to me.

**Comment by hoyosjs** [comment]
We don't produce packages on servicing?

**Comment by Anipik** [comment]
>  What's wrong about the current condition? Just checked

It will be addition with the existing condition i.e. In servicing branch produce the package we will set to GeneratePackageOnBuild to true in csproj
and attached line will set to false for other ci legs except the allconfig leg

**Comment by Anipik** [comment]
> We don't produce packages on servicing?

we dont produce until we have a change. thats libraries policy. for coreclr we just dont produce stable versions

**Comment by ViktorHofer** [comment]
> It will be addition with the existing condition i.e. In servicing branch produce the package we will set to GeneratePackageOnBuild to true in csproj
and attached line will set to false for other ci legs except the allconfig leg

I'm not sure what you mean by that. Can you please elaborate? The condition doesn't apply to servicing.

**Comment by Anipik** [comment]
The existing condition will be false for servicing which means no packages will be produces

now think of a scenario where we need to ship system.diagnostics.eventlog in the servicing 
we can set GeneratePackageOnBuild this true in csproj and that would start building the package.
but the package will be build in multiple legs and all of them will try to push the same package to the bar which would result in error

so we need disable the building of package in all legs other than allconfig leg

**Comment by ViktorHofer** [comment]
Got it, thanks for clarifying. That makes perfect sense.
