### ISSUE TITLE
Remove _validator field from ObjectCollection in HTTP header code

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#59549]
See here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/Headers/ObjectCollection.cs#L18

We could implement the "validator" as a virtual method instead of a delegate, and save a bit of space.

There's only one validator delegate that is ever passed in here anyway, so we would only need one subclass here.

**Comment by karelz** [comment]
Triage: Would be nice perf improvement, not critical for 7.0. Although we have PR up which may land in 7.0.
