### ISSUE TITLE
Add LoongArch64 architecture port

### ISSUE THREAD

**Issue by shushanhf** [dotnet/runtime#59561]
We want to add  a new  CPU-architecture LoongArch64 for dotnet  based on the .NET6 within the next 3-4 monthons.

Now we had finished the .NET3.1 on LoongArch64-Linux, and running the dotnet projects is ok.

We will also add the LoongArch64 to mono.

The porting .NET6 and mono for  LoongArch64 is under way.

**Comment by shushanhf** [comment]
@mangod9

**Comment by shushanhf** [comment]
![deb-LA-dotnet31](https://user-images.githubusercontent.com/35673267/134638715-b86de0e5-c16d-42dc-bf06-7f9317688921.png)

**Comment by mangod9** [comment]
Thanks @shushanhf for creating the issue. I assume this is for tracking purposes only, or are you running into any issues?

**Comment by shushanhf** [comment]
> Thanks @shushanhf for creating the issue. I assume this is for tracking purposes only, or are you running into any issues?

Thanks for your reponse!
Does the dotnet fundation argree to  accept the LoongArch64-CPU supporing the .NET?

**Comment by mangod9** [comment]
thanks for the clarification, Perhaps @richlander can route that question appropriately.

**Comment by Joe4evr** [comment]
This looks pretty similar to #52909
I'm guessing that means the proposed API is as such:
```diff
namespace System.Runtime.InteropServices
{
    public enum Architecture
    {
        X86,
        X64,
        Arm,
        Arm64,
        Wasm,
        S390x,
+       LoongArch64
    }
}
```

**Comment by huoyaoyuan** [comment]
s390x is a good comparison for what you need to do. You can also view the s390x branch in dotnet/runtimelab repo.

**Comment by shushanhf** [comment]
Hello, @jkotas
The LoongArch64 is a new architecture which its e_machine code is "EM_LOONGARCH 258(0x102)", it is not the mips64 architecture.

**Comment by am11** [comment]
Yup, LoongArch, RISC-V and MIPS architectures have few commonalities but they are different ISAs with their own opcodes / assembly syntaxes (https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html#overview-of-loongarch-isa).

Looking forward to see your contribution in `main` branch, especially around scaling out from few conservative assumptions  in CoreCLR like: `if it is not XARCH, then it must be ARM`. :)

cc @xiangzhai

**Comment by shushanhf** [comment]
> Yup, LoongArch, RISC-V and MIPS architectures have few commonalities but they are different ISAs with their own opcodes / assembly syntaxes (https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html#overview-of-loongarch-isa).
> 
> Looking forward to see your contribution in `main` branch, especially around scaling out from few conservative assumptions in CoreCLR like: `if it is not XARCH, then it must be ARM`. :)
> 
> cc @xiangzhai

Thanks~
We will push the LoongArch as soon as possible.

**Comment by xiangzhai** [comment]
Hi @am11 @jkotas 

Long time no see :)

@shushanhf  Comrade Qiao  is leading .NET porting for [LoongArch](https://en.wikipedia.org/wiki/Loongson#LoongArch).  And [FlightFinder](https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/FlightFinder) is able to run for LoongArch at present. Congratulations!

Cheers,
Leslie Zhai

**Comment by shushanhf** [comment]
> Hi @am11 @jkotas
> 
> Long time no see :)
> 
> @shushanhf Comrade Qiao is leading .NET porting for [LoongArch](https://en.wikipedia.org/wiki/Loongson#LoongArch). And [FlightFinder](https://github.com/aspnet/samples/tree/main/samples/aspnetcore/blazor/FlightFinder) is able to run for LoongArch at present. Congratulations!
> 
> Cheers,
> Leslie Zhai

**Comment by yhj200722** [comment]
dotnet fundation should argree to accept some new CPU-architecture supporing the .NET, that's helpful for dotnet ecosystem

**Comment by shushanhf** [comment]
> fundation

yes, I agree with you.
Now, we had finished or passed about 90% of the runtime testsuites, 9491/10564.

And we are debuging and amending the JIT of the mono-6.13 on LoongArch64-linux.

**Comment by tonyqus** [comment]
I agree with @jkotas. DNF is created to raise the ecosystem and community instead of making decisions for .net runtime project. Same cases happen in CNCF projects. Only PMC/maintainer are allowed to make decision for single projects.

**Comment by shushanhf** [comment]
> dotnet/runtime project encourages ports to new architectures as stated in our contribution guidelines: https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#contributing-ports
> 
> > dotnet fundation should argree to accept some new CPU-architecture supporing the .NET
> 
> Nit: This is a common misconception of .NET Foundation role. .NET Foundation does not have control over what type of changes its member projects accept or reject. It is in the jurisdiction of each individual project to decide that.

Hi, @jkotas , now we are ready to commit runtime-loongarch64 to the runtime repository,
what should we prepare before our commiting ?

**Comment by directhex** [comment]
What's the plan for continuous integration? i.e. if the changes you're proposing go into main, how do we validate them? How do we ensure we don't break it in future?

**Comment by jkotas** [comment]
> what should we prepare before our commiting ?

Split the changes into multiple PRs of manageable size that can be reviewed and merged independently. E.g. PR for PAL changes, PR for libraries changes, PR for build infra changes, etc.

> What's the plan for continuous integration? 

We have prior art here with other community supported ports: Tizen, Linux x86, FreeBSD, S/390x, ... . The first step would be to set up a cross-build leg in the CI that ensures that your port keeps building at least.

**Comment by tonyqus** [comment]
@directhex You just asked a question in my mind. Good job 👍 

I am curious about how .NET team build different versions. How do you run your CI/CD for S/390x? Do you have a real IBM S/390x server or based on S/390 emulator?  In other words, do they need to send a new Loogson-arch CPU powered server to US in order to finish your CI/CD process?

**Comment by jkotas** [comment]
In principle, we can hook up any provided machines to add additional CI validation. The machines do not have to be physically in Redmond (in fact, vast majority of the CI machines are not in Redmond). They just need to be connected to internet and be able to handle the load for given trigger (e.g. up to 100 runs per day for PR validation) and the job has to be reliable.

For S/390x, there is no PR validation currently. There is post-PR rolling build running twice a day (https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-community.yml) that is cross-building on Linux x64 machine. I am not sure who is monitoring the results of this job.

**Comment by shushanhf** [comment]
> We have prior art here with other community supported ports: Tizen, Linux x86, FreeBSD, S/390x, ... . The first step would be to set up a cross-build leg in the CI that ensures that your port keeps building at least.

Thanks~
First, I will commit some patches one by one and this is not difficult for me.
There is a bit unclear for the setting up of the cross-building. I don't know how to set up cross-build in your CI env?

**Comment by jkotas** [comment]
>There is a bit unclear for the setting up of the cross-building. I don't know how to set up cross-build in your CI env?

You can use what was done for Tizen cross-build as a blueprint: https://github.com/dotnet/runtime/issues/60452#issuecomment-950443736

**Comment by shushanhf** [comment]
> > There is a bit unclear for the setting up of the cross-building. I don't know how to set up cross-build in your CI env?
> 
> You can use what was done for Tizen cross-build as a blueprint: [#60452 (comment)](https://github.com/dotnet/runtime/issues/60452#issuecomment-950443736)

I have to supply a docker-container for cross-building for Loongarch64 ?

cross-building is just for the native part of the runtime ?
First, building the coreclr ?  Second, build the library liking the corefx ?

**Comment by directhex** [comment]
The whole build happens on x64.

The native parts are done using clang with a --sys root value set to an OS system root in /crossrootfs/arch name (see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/main/src/ubuntu/18.04/cross). The expectation is that clang 9 from Ubuntu 18.04 supports your arch - if not, you may need to get creative in setting up the docker image. The managed parts are done on x64, just setting and using TargetArchitecture for any platform specific managed code

**Comment by shushanhf** [comment]
> The native parts are done using clang with a --sys root value set to an OS system root in /crossrootfs/arch name (see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/main/src/ubuntu/18.04/cross). The expectation is that clang 9 from Ubuntu 18.04 supports your arch - if not, you may need to get creative in setting up the docker image. The managed parts are done on x64, just setting and using TargetArchitecture for any platform specific managed code

Thanks~
I have finished the porting on Loongarch64-linux last week.
Now I will split it to small patches for reviewing and commit  them first ?  Then I will also supply a docker-container for cross-building on x64-linux.
Is it right ?

**Comment by shushanhf** [comment]
> The whole build happens on x64. The native parts are done using clang with a --sys root value set to an OS system root in /crossrootfs/arch name (see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/main/src/ubuntu/18.04/cross). The expectation is that clang 9 from Ubuntu 18.04 supports your arch - if not, you may need to get creative in setting up the docker image. The managed parts are done on x64, just setting and using TargetArchitecture for any platform specific managed code
> […](#)
> Sent from my iPhone
> On Dec 12, 2021, at 10:57 PM, Qiao ***@***.***> wrote: ﻿ There is a bit unclear for the setting up of the cross-building. I don't know how to set up cross-build in your CI env? You can use what was done for Tizen cross-build as a blueprint: #60452 (comment) I have to supply a docker-container for cross-building for Loongarch64 ? cross-building is just for the native part of the runtime ? First, building the coreclr ? Second, build the library liking the corefx ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thanks~
I have finished the porting on Loongarch64-linux last week.
Now I will split it to small patches for reviewing and commit  them first ?  Then I will also supply a docker-container for cross-building on x64-linux.
Is it right ?

**Comment by BruceForstall** [comment]
@shushanhf All the pull requests in dotnet/runtime to enable LoongArch64 have been merged. Can or should this issue now be closed? Or, is it tracking additional work?

**Comment by shushanhf** [comment]
> @shushanhf All the pull requests in dotnet/runtime to enable LoongArch64 have been merged. Can or should this issue now be closed? Or, is it tracking additional work?

Thanks very much!
I think maybe it's better to close this PR and creating a new issue to ttack the TODOs for LA .

**Comment by shushanhf** [comment]
close this PR and the TODOs for LA will be tracked by a new issue.

Thanks

**Comment by hez2010** [comment]
Will we have official build for loongarch64 port?
