### ISSUE TITLE
AssemblyName.CodeBase is ignored in LoadFromAssemblyName

### ISSUE THREAD

**Issue by adrianm64** [dotnet/runtime#59565]
### Description

When porting a .NET Framework application to core I replaced 
```cs
...
assemblyName.CodeBase = "C:\Path\To\Assembly.dll";
var assembly = Assembly.Load(assemblyName);
```
with

```cs
...
assemblyName.CodeBase = "C:\Path\To\Assembly.dll";
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyName(assemblyName);
```
But it didn't work. It ignored the path in CodeBase and used the normal assembly loading pattern.

I changed the code to
```cs
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath("C:\Path\To\Assembly.dll");
```
which works fine.

## Expected behavior
LoadFromAssemblyName using CodeBase or a a compiler warning/error when assigning the AssemblyName.CodeBase property.

### Configuration

Microsoft NetCoreApp 3.1.0

### Regression?

Yes, worked in .NET Framework

**Comment by vitek-karas** [comment]
`CodeBase` is obsolete in .NET Core/.NET5 +. In fact `Assembly.CodeBase` is already marked as obsolete, but `AssemblyName.CodeBase` isn't (overlooked unfortunately).

This is effectively a duplicate of https://github.com/dotnet/runtime/issues/42857.

**Comment by adrianm64** [comment]
Thank you for the quick response.
