### ISSUE TITLE
Eliminate allocations when enumerating empty collections

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#59596]
Turns out the world is full of empty collections. Empty lists, empty dictionaries, empty sets. The world is also full of code that ends up enumerating these empty collections. And if this code happens to hold an interface type such as IList&lt;T> or IReadOnlyList&lt;T>, then enumerating these empty collections causes a heap allocation:

```csharp
IReadOnlyList<int> l = new List<int>();
foreach (var foo in l)   // <-- allocates an enumerator, *sigh*
{
}
```

It should be possible to eliminate these allocations by adding a teeny bit of logic to the collection types. For example, consider List&lt;T>:

```csharp
public class List<T>
{
    IEnumerator<T> IEnumerable<T>.GetEnumerator()
        => (_size == 0) ? _staticEmptyEnumerator : new Enumerator(this);

    private static readonly EmptyEnumerator _staticEmptyEnumerator = new ();

    private sealed class EmptyEnumerator : IEnumerator<T>
    {
        public void Dispose() {}
        public bool MoveNext() => false;
        public void Reset() {}
        public T Current => throw new NotSupportedException();
        object IEnumerator.Current => throw new NotSupportedException();
    }
}
```

The above code detects if the collection is empty and then returns a static enumerator instance to the caller. No allocation occurs, the world is a slightly better place as a result.

**Comment by GrabYourPitchforks** [comment]
Just as a heads up, this would be an observable behavioral change.

```cs
IList<string> list = new List<string>();
var enumerator = list.GetEnumerator();
list.Add("Hello!");
enumerator.MoveNext(); // this currently throws; with this proposal, it would returns false
```

**Comment by stephentoub** [comment]
> this would be an observable behavioral change

It is observable, but I think that's ok in this particular case.  List's enumerator effectively snapshots the state of the list at the time it's created (by tracking the version number), and even though it implements Reset, it doesn't reset the version number as part of the operation, and in fact itself validates that it still matches the original.  So, this is just taking something that was exceptional before and giving it a valid meaning.

Your top-level point holds, though: we need to be careful where we employ such optimizations. Note that `T[]`s already do this: if you iterate over an empty array, you're using a singleton enumerator:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/System.Private.CoreLib/src/System/Array.CoreCLR.cs#L470-L476
We also do this sporadically in other collections, e.g.
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L295-L297

I think it's fine to do it on further types, as long as:
1) We know empty instances of the type are frequently enumerated.
2) The enumerator can't already be used to represent a later state of the collection, e.g. it has no version check.

For example, while it might be ok to do this for `List<T>`, it's not ok to do it for `ConcurrentDictionary<TKey, TValue>`.

**Comment by ChrML** [comment]
This is a good idea. Perhaps even better to have one static property with an empty enumerator that all collections can consume.

Just mind that this will very slightly change the behavior of the enumerators. E.g. previously if you get the enumerator for an empty list, store it, add something to the list and then enumerate the enumerator, you'd get an exception indicating that the collection has changed. This will no longer be the case with an empty enumerator. It would silently give you no data. But I guess that's very subtle, and perhaps unimportant. You'd have to abuse enumerators in a multithreaded environment to encounter that difference.

**Comment by geeknoid** [comment]
Having Enumerator.Empty<T> as a static somewhere would be a nice complement to Array.Empty<T>.

**Comment by stephentoub** [comment]
`Enumerable.Empty<T>().GetEnumerator()` provides that, but it's in System.Linq and thus not usable lower in the stack. I'd be ok with us exposing an implementation lower as long as we replaced others like it we currently have.
