### ISSUE TITLE
The asp.net core program is deployed on a win7 computer, and an error  “The type initializer for 'System.DateTime' threw an exception” is reported when running

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/runtime#59594]
+ System 

  - Provider 

   [ Name]  .NET Runtime 
 
  - EventID 1026 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2021-09-25T03:31:05.000000000Z 
 
   EventRecordID 113558 
 
   Channel Application 
 
   Computer win7-PC 
 
   Security 
 

- EventData 

   Application: ZhaoyangParking.exe CoreCLR Version: 6.0.21.37719 .NET Version: 6.0.0-preview.7.21377.19 Description: The process was terminated due to an unhandled exception. Exception Info: System.TypeInitializationException: The type initializer for 'System.DateTime' threw an exception. ---> System.ArgumentNullException: Value cannot be null. (Parameter 'handle') at System.Runtime.InteropServices.NativeLibrary.GetExport(IntPtr , String ) in System.Private.CoreLib.dll:token 0x6002fa0+0x17 at System.DateTime.GetGetSystemTimeAsFileTimeFnPtr() in System.Private.CoreLib.dll:token 0x6000cc7+0x0 at System.DateTime..cctor() in System.Private.CoreLib.dll:token 0x6000cc9+0x60 --- End of inner exception stack trace --- at System.DateTime.get_UtcNow() in System.Private.CoreLib.dll:token 0x6000cc2+0x0 at System.DateTimeOffset.get_UtcNow() in System.Private.CoreLib.dll:token 0x6000cd5+0x0 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat() in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000579+0x0 at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x600028d+0x61 at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in Microsoft.AspNetCore.Hosting.dll:token 0x60000b1+0x23b at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken ) in Microsoft.Extensions.Hosting.dll:token 0x6000065+0x177 at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost , CancellationToken ) in Microsoft.Extensions.Hosting.Abstractions.dll:token 0x6000016+0x93 at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost , CancellationToken ) in Microsoft.Extensions.Hosting.Abstractions.dll:token 0x6000016+0x1be at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost ) in Microsoft.Extensions.Hosting.Abstractions.dll:token 0x6000015+0x15 at Microsoft.AspNetCore.Builder.WebApplication.Run(String url) in Microsoft.AspNetCore.dll:token 0x6000041+0x7 at <Program>$.<Main>$(String[] args) in E:\Learn\ZhaoyangParking\ZhaoyangParking\Program.cs:line 55

**Comment by jkotas** [comment]
.NET apps have additional prerequisites on Windows 7: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#additional-deps

This error is likely caused by missing KB3063858

**Comment by quan0zhou** [comment]
That's true. KB3063858 is missing. Thank you very much

> .NET apps have additional prerequisites on Windows 7: https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#additional-deps
> 
> This error is likely caused by missing KB3063858

**Comment by GrabYourPitchforks** [comment]
@jkotas Should we surface an clearer error message from the cctor if we detect this method is missing? This is the second issue reported in the last few months regarding this missing KB. (Though I think this is a mandatory KB, so I don't know how 6 years in there are some machines missing it?)

**Comment by jkotas** [comment]
> Should we surface an clearer error message from the cctor if we detect this method is missing? 

The problem is that `LoadLibraryEx` does not work as expected. There are number of places in runtime and libraries that may hit a problem due to the missing KB. If we wanted to do something about this, I think we would want to detect the missing KB during runtime startup by validating that `LoadLibraryEx` works as expected.
