### ISSUE TITLE
Microsoft.XmlSerializer.Generator package does not install correctly as a tool.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/runtime#596]
When running `dotnet dotnet-Microsoft.XmlSerializer.Generator` from the command line the tool will not be found. The package is not correctly installing the tool as a "dotnet CLI tool". This can be worked around by including the `<DotNetCliToolReference>` element to the csproj directly.

This currently works in VS because VS will do two Restores, the second Restore will properly create the packages/.tools folder that will contain dotnet-Microsoft.XmlSerializer.Generator. After doing this in VS then the command line will work so long as nothing was cleaned.

Original issue: dotnet/corefx#41286

- [ ] Port to 3.1.x

**Comment by HongGit** [comment]
This is by design per MSDN doc on [Microsoft.XmlSerializer.Generator](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/xml-serializer-generator).
