### ISSUE TITLE
MemoryMappedViewAccessor: Dispose flushes on temporary files

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#59606]
### Description
Currently it seems that the MemoryMappedViewAccessor created from a MemoryMappedFile flushes when the view is disposed.
While this behavior is fully acceptable in regular scenarios where the View is created, written to and closed again. In this situation the modifications need to be flushed to disk.

Another possibility is though to use the MM-File as a temporary buffer, where the FileStream is created with FileOptions.Temporary and when the MM-FIle and the FileStream get closed, the temporary storage file is also deleted.

For my case I open many MM-Files (with the temporary flag), knowing the file is of all files in advance and setting the file size with SetLength (also using the WinAPI SetFileValidLength, and making it also a sparse file with winAPI IOControl). Then a full view is created.

So my question is if there is a solution to skip the flush (that I currently don't) or if I should make an API proposal that allows to skip the Dispose, or to advise the view to do a discard (by using DiscardVirtualMemory). 

[Edit] It seems when disposing the MemoryMappedFile before the View works without flushing, but I don't know if this is the intended behavior?

### Configuration
My configuration currently is .NET 5/Win10/x64

### Regression?
No, there is no regression. It is a problem that has existed for a longer time and maybe no one has ever encountered it since it has to to only with temporary files.

### Data
An unfinished project can be seen here: https://github.com/msedi/MappableFileStream

**Comment by stephentoub** [comment]
Can you elaborate on what's going wrong? Is the flush causing something to fail,  or is the concern unnecessary overhead?

**Comment by msedi** [comment]
@stephentoub: > Can you elaborate on what's going wrong? Is the flush causing something to fail, or is the concern unnecessary overhead?

You are right, I was not clear about this. The Flush causes a lot of time which is end the end useless, since the file is deleted afterwards. I have a wide range of memory configurations (ranging from 16GB to 1TB RAM). Where the 16GB is not really a problem, although a full flush also causes ~7s on my disk, a 64GB starts to getting an overhead. When the RAM increases it gets even worse.

**Comment by stephentoub** [comment]
Thanks.

You wrote:
"where the FileStream is created with FileOptions.Temporary"
What is FileOptions.Temporary?  That's not one of the enum values.

**Comment by msedi** [comment]
Sorry, I meant the FileOptions.DeleteOnClose.

**Comment by Jozkee** [comment]
Seems like you are proposing to extend MemoryMappedFiles, instead of a discussion can you please elaborate an API proposal for your needs?
https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md

**Comment by stephentoub** [comment]
> Seems like you are proposing to extend MemoryMappedFiles, instead of a discussion can you please elaborate an API proposal for your needs?

@Jozkee, there may be opportunity here for the implementation to simply avoid flushing if the file is going to be deleted immediately.  Before discussing new API, we should determine whether that's viable.

**Comment by msedi** [comment]
@stephentoub: I'm currently working on the proposal. Will take a few more minutes to get some examples.
