### ISSUE TITLE
Running 'dotnet-serve' with .NET 6.0 RC1 ARM on an Apple M1: Nothing happens

### ISSUE THREAD

**Issue by ChristianWeyer** [dotnet/runtime#59618]
*Note:* I wanted to just add a comment to https://github.com/dotnet/runtime/issues/52335 - but it is locked.

The original issue is in the `dotnet-serve`repo, but the maintainer asked me to report it here, as well.
https://github.com/natemcmaster/dotnet-serve/issues/99

I have a MBP with an Apple M1. Running macOS 11.6.
And I am running .NET 6 RC1 SDK for ARM.

After installing `dotnet-serve` (https://github.com/natemcmaster/dotnet-serve) and trying to run it in a folder, just nothing happens - or it seems so.

https://user-images.githubusercontent.com/888718/134798576-c181e0f8-fd97-47c6-8b4d-e16c939454c3.mov

This seems related to https://github.com/dotnet/runtime/issues/52335?
Thanks!

**Comment by jeffschwMSFT** [comment]
@ChristianWeyer what is the error code from the process?  That may give a clue on what is happening.

**Comment by ChristianWeyer** [comment]
All I get and see is in the video above. Any hint on how to see the error code?

**Comment by jeffschwMSFT** [comment]
Run the command and then execute 'echo $?'

**Comment by ChristianWeyer** [comment]
This results in: `137`

**Comment by jeffschwMSFT** [comment]
Seems related to https://github.com/dotnet/sdk/issues/21349

**Comment by joperezr** [comment]
Actually seems like this is a dupe of that issue. Seems like the fix for this should go in the sdk for this, so @ChristianWeyer is it ok to close this as a dupe of sdk and just track the fix there?

**Comment by ChristianWeyer** [comment]
Yes, sir!
