### ISSUE TITLE
[API Proposal]: Make it easier to append values to an array

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#59610]
### Background and motivation

I have an API that takes an array and I got an array from handed to me from another API. I'd like to be able append values to this array and get an array back in a single line of code (preferably a single expression rather than a statement). My specific scenarios was mutating existing command line arguments to pass to an API that was expecting command line args.

Ways I can think of doing this today:

```C#
T[] AppendWithInnerArray<T>(T[] array, IEnumerable<T> values)
{
    if (Enumerable.TryGetNonEnumeratedCount(values, out int count))
    {
        var newArray = new T[array.Length + count];
        array.CopyTo(newArray, 0);
        var index = count;
        foreach (var item in values)
        {
            array[index++] = item;
        }
        return newArray;
    }

    var list = new List<T>(array);
    list.AddRange(values);
    return list.ToArray();
}

T[] AppendWithList<T>(T[] array, IEnumerable<T> values)
{
    var list = new List<T>(array);
    list.AddRange(values);
    return list.ToArray();
}

T[] AppendWithEnumerable<T>(T[] array, IEnumerable<T> values) => array.Concat(values).ToArray();
```

`AppendWithEnumerable` comes the closest but there are inefficiencies and it requires LINQ and it's dependencies.

### API Proposal

```C#
namespace System
{
    public class Array
    {
        public T[] Append(T value);
        public T[] Append(IEnumerable<T> values);
    }
}
```     

### API Usage

```C#
args = args.Append(new [] { "--verbose", " true" });

ExecuteAppWithArgs(args);
```

### Risks

None that I can think of. More allocations maybe but that was the case anyways since the APIs take arrays.

### Other

- The Append that takes an 

We could get crazy and support + for arrays 😄.

```C#
args = args + new[ ] { "--verbose", "true" };
```

**Comment by stephentoub** [comment]
`array.Concat(...).ToArray()`?

**Comment by davidfowl** [comment]
Yah I updated the implementation list with it and also looked and saw that is is somewhat optimized for `ICollection<T>` etc.

**Comment by stephentoub** [comment]
> saw that is is somewhat optimized for ICollection

If the scenario is:

"My specific scenarios was mutating existing command line arguments to pass to an API that was expecting command line args."

and we're allocating at least one new array of not multiple,  there's no way this needs to be hyper-optimized:-)

Why is Concat/Append.ToArray insufficient?

**Comment by davidfowl** [comment]
It's unintuitive.

**Comment by stephentoub** [comment]
How is it unintuitive?

**Comment by davidfowl** [comment]
Maybe its a taste thing, but I think something like:

```C#
args = array.Append(new [] { "--debug", "true" });
```

I know I suggested a static:

```C#
args = array.Concat(new [] { "--debug", "true" }).ToArray();
```

Maybe I'm splitting hairs but 2 things bug me:
- The dependency on LINQ given that we care about linking now
- Concat + ToArray for what seems like a pretty common operation that should be "array native".

PS: This is a pretty cool site I found for comparing other languages runtimes for common idioms: https://www.programming-idioms.org/idiom/166/concatenate-two-lists/3295/dart

**Comment by omariom** [comment]
`Append`  sounds like a mutating method. It will be confusing beginners.

**Comment by stephentoub** [comment]
> The dependency on LINQ given that we care about linking now

If the concern is the extra assembly, it's a rare application that won't use anything from System.Linq.dll.

> Concat + ToArray for what seems like a pretty common operation that should be "array native".

I don't see it.

> Also creating a new array for the single value append feels slightly syntactically noisy.

LINQ has an Append method:
```C#
args = array.Append("hello").ToArray();
```

**Comment by davidfowl** [comment]
OK, I'll close it.

**Comment by theodorzoulias** [comment]
@davidfowl if this API existed, I would probably have used it many times over the years. On the other hand it would make tricky to use the LINQ `Append` operator on arrays, because of the name conflict. Many people wouldn't realize that they invoke the `Array.Append` instead of the intended `System.Linq.Append`.

```c#
args = args
    .AsEnumerable() // Without this, an extra array would be allocated for no reason
    .Append("--verbose")
    .Where(arg => !excluded.Contains(arg))
    .ToArray();
```
