### ISSUE TITLE
Error in the documentation of the Task.ContinueWith method?

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#59620]
Hi! I think that I might have found an error in the documentation of the [`Task.ContinueWith`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith#System_Threading_Tasks_Task_ContinueWith_System_Action_System_Threading_Tasks_Task__System_Threading_CancellationToken_) method. The documentation states:

> Exceptions
> ObjectDisposedException
> The `CancellationTokenSource` that created the token has already been disposed.

I've tried to reproduce this exception, without success. Here is my attempt to reproduce it:

```c#
using System;
using System.Threading;
using System.Threading.Tasks;

public static class Program
{
    public static async Task Main()
    {
        var cts = new CancellationTokenSource();
        var cancellationToken = cts.Token;
        cts.Dispose();
        await Task.Delay(100).ContinueWith(t =>
        {
            Console.WriteLine("Continuation OK");
        }, cancellationToken);
    }
}
```

This program outputs the text `"Continuation OK"`, instead of throwing an `ObjectDisposedException` exception which was my expectation. You can [try it on Fiddle](https://dotnetfiddle.net/C3ctzt). Is this an error in the documentation, or my understanding of what the documentation says is wrong?

**Comment by stephentoub** [comment]
Thanks.  This is stale. It used to be the case that registering with token from a disposed CTS would throw,  but at some point we made it more forgiving as it was too difficult to reason about.  At this point it should be safe to remove that from the docs.
