### ISSUE TITLE
X509Store.Add pops up a dialog, fails on OneCore system

### ISSUE THREAD

**Issue by tire0011** [dotnet/runtime#59638]
### Background and motivation

The problem was already described here:
[issue 24160](https://github.com/dotnet/runtime/issues/24160)

It is not okay that the issue is closed and nothing is changed. The current behaviour is total misleading. We not expect a:
WindowsCryptographicException 'The operation was canceled by the user'. There was no user action at all. I was misleading and losed some time because I could not bring the message with the failing of the popup window together. 

There are many not supported exceptions to bring the hint It is not working on the system and that is fine. The .net core should bring also in that situation a not supported exception on a nano system. And it is not a problem on core framework level to detect that case and bring a more suitable message to the developer.

### API Proposal

```C#
X509Store store = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
string certPath = "c:\\test\\t.cer";
try
{
            store.Add(new X509Certificate2(X509Certificate2.CreateFromCertFile(certPath)));
}
catch(NotsupportedException e)
{
  Console.WriteLine(e.Message); // Not supported on nano server because user pop up can not be shown.
}
```     

### API Usage

```C#
X509Store store = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadWrite);
string certPath = "c:\\test\\t.cer";
try
{
            store.Add(new X509Certificate2(X509Certificate2.CreateFromCertFile(certPath)));
}
catch(NotsupportedException e)
{
  Console.WriteLine(e.Message); // Not supported on nano server because user pop up can not be shown.
}
```     

### Risks

no risk

**Comment by bartonjs** [comment]
Assuming that we can sensibly detect that we're on Nano/OneCore it would be possible to do something like

```C#
int ret = CertAddToStore(...);

if (ret == ERROR_CANCELLED && IsNano())
{
    throw new NotSupportedException(...);
}
else if (ret != ERROR_SUCCESS)
{
    throw CreateException(ret);
}
```

But then we get into a question of whether or not that would break anyone.  `CryptographicException` is already a thing that can happen from calling store.Add... so it's a thing that people could reasonably be depending on, like

```C#
try
{
    cuRoot.Add(cert);
}
catch (CryptographicException)
{
    // There's no fallback from adding to LocalMachine\Root, just let this exception bubble out.
    lmRoot.Add(cert);
}
```

If the complaint is really just about the message, we could do a CryptographicException with a custom message... but the value feels small to me.

**Comment by bartonjs** [comment]
Since the best we can do is change the exception type or message in this situation, and there doesn't seem to be a huge support base for that proposal, closing the issue.
