### ISSUE TITLE
`System.Version` can't be Json-deserialized

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#59632]
### Description

`System.Version` class can't be json deserialized.

![image](https://user-images.githubusercontent.com/40547839/134861099-2f97050b-9f85-4320-a2c7-e3ffadbd67b0.png)
![image](https://user-images.githubusercontent.com/40547839/134860676-b66a4feb-0508-4451-a07f-f6b873b8a031.png)

### Configuration

Windows 10
Running .net 6.0.100-preview.7.21379.14

### Regression?

I don't know, but surely in .net 5 this bug exists.

**Comment by N0D4N** [comment]
.NET 5 doesn't have built-in converter for Version.
on .NET 6.0.100-rc.1.21458.32 for following code i get next output
```cs
using System;
using System.Text.Json;

var v = new Version(4,32,23,3425);
var json = JsonSerializer.Serialize(v);
var v2 = JsonSerializer.Deserialize<Version>(json);
Console.WriteLine("Json: " + json);
Console.WriteLine("V: " + v.ToString());
Console.WriteLine("V2: " + v2!.ToString());
/* Output of running previous code
Json: "4.32.23.3425"
V: 4.32.23.3425
V2: 4.32.23.3425
*/
```

**Comment by martincostello** [comment]
Yeah, support for this was added in .NET 6 by #41384.

**Comment by DrkWzrd** [comment]
Wow, this is weird, why then this occurs to me?

This is my powershell text copied
```
Windows PowerShell
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

Prueba la nueva tecnología PowerShell multiplataforma https://aka.ms/pscore6

PS C:\WINDOWS\system32> dotnet --version
6.0.100-preview.7.21379.14
PS C:\WINDOWS\system32>
```

**Comment by eiriktsarpalis** [comment]
I can't reproduce either. It might be that you're either 1) accidentally targeting net5.0 in your application or 2) trying to deserialize JSON of the form `{ "Major" : 4, "Minor" : 1, .... }` which is not supported by the new converter.

**Comment by DrkWzrd** [comment]
@eiriktsarpalis I'm so dumb, option 1 was right.

I'm closing this, thanks. And sorry for the inconvenience
