### ISSUE TITLE
Alpine docker image does not obey local timezone anymore

### ISSUE THREAD

**Issue by nalla** [dotnet/runtime#59636]
### Description
The release 6.0.0-rc.1 does not obey the local timezone information. This is a regression, see the following steps to reproduce

### Steps to reproduce
```
private static void Main(string[] args)
{
	Console.WriteLine(TimeZoneInfo.Local.DisplayName);
}
```

#### Working
```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
    WORKDIR /build
    COPY src/Foo.sln .
    COPY src/Foo/*.csproj ./Foo/
    RUN dotnet restore ./Foo.sln
    COPY src/Foo/ ./Foo/
FROM build as publish
    WORKDIR /build/Foo
    RUN dotnet publish -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runtime
    RUN apk update --no-cache && apk upgrade --no-cache
    RUN apk add --no-cache tzdata
    ENV TZ=Europe/Berlin
    ENV LANG=de_DE.UTF-8
    ENV LANGUAGE=${LANG}
    ENV LC_ALL=${LANG}
    RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    WORKDIR /app
    COPY --from=publish /build/Foo/out ./
    ENTRYPOINT [ "dotnet", "Foo.dll" ]
```

This will produce the following output
```
(UTC+01:00) CET
```

#### Bug
When you now take the same code, change target framework from `net5.0` to `net6.0` and use the same `Dockerfile` as a base and use `mcr.microsoft.com/dotnet/sdk:6.0` and `mcr.microsoft.com/dotnet/aspnet:6.0-alpine`, you will get the following output
```
(UTC+00:00) Coordinated Universal Time
```

**Comment by am11** [comment]
Seems like TZ was working on .NET 5 with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` on .NET 5.0, but not on .NET 6.

```diff
- FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS runtime
+ FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS runtime
    RUN apk update --no-cache && apk upgrade --no-cache
-   RUN apk add --no-cache tzdata
+   RUN apk add --no-cache tzdata icu-libs
    ENV TZ=Europe/Berlin
    ENV LANG=de_DE.UTF-8
    ENV LANGUAGE=${LANG}
    ENV LC_ALL=${LANG}
+   ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    WORKDIR /app
    COPY --from=publish /build/Foo/out ./
    ENTRYPOINT [ "dotnet", "Foo.dll" ]
```

results in:
```
Console.WriteLine(TimeZoneInfo.Local.DisplayName)
// (UTC+01:00) Mitteleuropäische Zeit (Berlin)

Console.WriteLine(TimeZoneInfo.Local.Id)
// (Berlin) Europe/Berlin
```

on both, 5.0 and 6.0.

not sure if it is an intentional change or accidental breakage.

**Comment by nalla** [comment]
Thanks, this works. So current behavior is correct, `net5.0` behavior was somewhat faulty.

**Comment by am11** [comment]
Perhaps @GrabYourPitchforks and @tarekgh can answer more accurately whether or not if it is a regression. To me the behavior of net5.0 seems correct; recognize correct TZ even in the invariant mode.

**Comment by tarekgh** [comment]
Thanks @nalla for reporting this issue. It is a regression and I am looking at it.

**Comment by tarekgh** [comment]
This issue is addressed by the PR https://github.com/dotnet/runtime/pull/59727.
