### ISSUE TITLE
ComWrappers: are there any (Roslyn) Source Generators planned?

### ISSUE THREAD

**Issue by obiwanjacobi** [dotnet/runtime#59651]
I am dipping my toes into COM interop with the ComWrappers API.
The necessary plumbing code involved in any serious COM interop project is considerable.
[My project has almost a 100 interfaces or structs](https://github.com/obiwanjacobi/vst.net/tree/master/Source3/Code/Jacobi.Vst3.Core).

So a logical question: _(How) can we generate this code and are there any plans to provide this feature?_

cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
>So a logical question: (How) can we generate this code and are there any plans to provide this feature?

@obiwanjacobi We are actively investigating options for .NET 7. Using Roslyn source generators is an option, another is to follow the [C#/WinRT](https://github.com/microsoft/CsWinRT) pattern which also has benefits. As we move further into the .NET 7 planning phase issues will be created and the community consulted on their opinion as well. @jkoritzinsky is going to be investigating options and starting that conversation when appropriate.

**Comment by obiwanjacobi** [comment]
Thanks @AaronRobinsonMSFT - So that will take a year at least..?
What if I can't wait that long and want to create something that at least covers my use case?
Is there any source code available (as inspiration) of the old COM interop (CCW/RCW) and how it handled marshaling?
I am mainly looking for guidance how to handle all those `MarshalAs` and `StructLayout` code attributes.

BTW: I am unfamiliar with C#/WinRT and did not understand its benefits from looking at the code...
/cc @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment]
> So that will take a year at least..?

That is a good estimate for an official release. We would likely have Preview releases much earlier though.

> What if I can't wait that long and want to create something that at least covers my use case?
> Is there any source code available (as inspiration) of the old COM interop (CCW/RCW) and how it handled marshaling?

That is entirely possible. I think at this point there are two main options.

1) Manually write the interop code. This seems like a lot but once you start it is actually relatively quick going. I'd say about 2 weeks for ~100 interfaces and types. It could be faster depending on experience though.

1) Use something like [SharpGenTools](https://github.com/SharpGenTools/SharpGenTools) to start with.

> I am unfamiliar with C#/WinRT and did not understand its benefits from looking at the code...

The benefits are it is a standalone tool that reads an independent source of truth (i.e., `WinMD`) as opposed to C# which requires at least an initial definition be written in C#. There are composability approaches that could make a Roslyn source generator work like a standalone tool or a simpler tool that goes from `WinMD`, `TLB`, or `IDL` to C# and then use a Roslyn source generator to fill in the interop goo &ndash; lots of options. My intention was to point out that there the approach isn't obvious or clear given the complexity of UX with the Roslyn source generator nor is it great with a standalone tool. We also need to weight how the experience with work in non-Windows.

**Comment by obiwanjacobi** [comment]
Thanks @AaronRobinsonMSFT for the pointers.

[I just spent the better part of the day with SharpGenTools](https://github.com/obiwanjacobi/vst.net/tree/ddne3/Source3/Code/SharpGenToolsTest) and although it looks very promising, I don't think it can generate the code I am looking for. For instance: I cannot to get it to generate real C# interfaces from the C++ COM code. I have tried several mappings, bindings and what not but it's not doing it. Also, I cannot find how to put the generated code somewhere else than buried in the obj folder and how to actually use the generated code...

SharpGenTools is my preferred option for that actual source of what I am doing is a 3rd party Cpp Sdk. I imagine just having to run my generator project when a new Sdk version comes out... (would be nice)

Using ComWrapper -with or without code gen- seems a lot more work, provided I can massage SharpGenTools a bit more to do what I want...

I would be interested to know if the future plans for ComWrapper source gen includes generating from Cpp source code?

**Comment by AaronRobinsonMSFT** [comment]
> I would be interested to know if the future plans for ComWrapper source gen includes generating from Cpp source code?

@obiwanjacobi That would likely be a P2 since the C++ is very tricky to make cross-platform successfully and it is substantially more difficult to generate than canonical C#. It is something that is on our list of nice to haves but I am skeptical it would be a P0 or P1. I could see a potential P1 being generation of TLBs, from which C/C++ headers could be generated using Windows tooling though.

Keep the questions/comments/requests coming; these types of issues help to drive priorities.

**Comment by jkotas** [comment]
Proposed plan: https://github.com/dotnet/runtime/pull/60143

**Comment by AaronRobinsonMSFT** [comment]
Closing this now that the tracking issue is available. See https://github.com/dotnet/runtime/issues/66674.
