### ISSUE TITLE
`AssemblyName.CodeBase` stripped from `AssemblyName` before going to Resolving event handler

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#59669]
On .NET Framework, `Assembly.Load(AssemblyName)` will consider the value of `AssemblyName.CodeBase` before failing to load the assembly.
On .NET Core, not only is the `CodeBase` property ignored, but it's *omitted* from a copy of the `AssemblyName` that is given to the `AssemblyLoadContext.Resolving` event handler, where I had hoped to re-implement the .NET Framework behavior of honoring that property.

For backwards compatibility when an app migrates from NetFX to .NET Core, being able to see the `CodeBase` property would be useful. Why is it omitted? Would you consider modifying .NET Core to propagate that property when calling the `Resolving` event handler to give the host more options for finding assemblies?

Repro:

```cs
using System;
using System.Reflection;
#if NETCOREAPP
using System.Runtime.Loader;
#endif

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
#if NETCOREAPP
            AssemblyLoadContext.Default.Resolving += ALC_Resolving;
#endif

            AssemblyName an = AssemblyName.GetAssemblyName(@"C:\git\threading\bin\SosThreadingTools\Debug\net472\SosThreadingTools.dll");
#if NETCOREAPP
           // not necessary on net472
           an.CodeBase = @"C:\git\threading\bin\SosThreadingTools\Debug\net472\SosThreadingTools.dll";
#endif

            Assembly a = Assembly.Load(an); // throws on net5.0
            Console.WriteLine("a is not null: " + (a is object));
        }

#if NETCOREAPP
        private static Assembly ALC_Resolving(AssemblyLoadContext arg1, AssemblyName arg2)
        {
            if (!string.IsNullOrEmpty(arg2.CodeBase)) // null on net5.0
            {
                return arg1.LoadFromAssemblyPath(arg2.CodeBase);
            }

            return null;
        }
#endif
    }
}
```

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/issues/7752 has some context

**Comment by AArnott** [comment]
Thanks for the context. I get that .NET Core wants to diverge in assembly load behavior from Framework. I would like to see the Codebase property preserved in the Resolving event just so an app can choose to re-implement Framework behavior. Right now, it appears to be impossible.

**Comment by agocke** [comment]
We now have precedent from ProcessorArchitecture that we don't preserve obsolete information moving through AssemblyName. CodeBase is in the same category. Closing as Won't Fix.
