### ISSUE TITLE
Dictionary concurrency behaviour

### ISSUE THREAD

**Issue by franzzua** [dotnet/runtime#59688]
### Description

When many threads are trying to add values with different keys in one dictionary at same time, sometimes it throws exception, but sometimes it inserts not all values.

### Configuration

* .NET 5
* Windows 10
* x64

### Other information

```
public void DictTest()
{
    var dict = new Dictionary<string, int>();
    var promise = Task.Delay(1000);
    const int count = 10;
    var tasks = Enumerable.Range(0, count)
        .Select(number => Task.Run(async () =>
        {
            await promise;
            dict[$"task {number}"] = number;
        }))
        .ToArray();
    Task.WaitAll(tasks);
    Assert.AreEqual(dict.Keys.Count, count);
}
```
If exception have not been throwed, `dict` contains just 4 keys, or maybe 8 keys, but not 10.

### Expected behaviour
Throwing an exception if not all keys have been inserted

**Comment by huoyaoyuan** [comment]
For thread safety, use `ConcurrentDictionary` instead. Most collections are non thread-safe by default.

**Comment by theodorzoulias** [comment]
@franzzua the behavior you observe is called "undefined behavior", and it's kind of expected when multiple threads are mutating non-thread-safe objects without synchronization.
