### ISSUE TITLE
Issue with HttpClient using it on PUT/POST verbs on aspnet core 2.1

### ISSUE THREAD

**Issue by contactkiran1899** [dotnet/runtime#59692]
We are getting an I/O exception with httpclient when using it on aspnet core 2.1
This is happening only when there is multiple servers/ distributed environment.

### Describe the bug
when we try to POST/PUT verb using aspnet core 2.1 we are seeing an I/O exception coming up
ERROR: 
```
System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.
---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
--- End of inner exception stack trace ---
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
     at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
     at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
     at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```

### To Reproduce
we are able to see this exception when it is in distributed environment and multiple servers in play. unable to replicate it locally

### Further technical details
- ASP.NET Core version 2.1
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by scalablecory** [comment]
It looks like the request is being canceled. Do you have a cancellation token triggering, or a timeout configured on the `HttpClientHandler`/`SocketsHttpHandler`?

**Comment by karelz** [comment]
@contactkiran1899 note that ASP.NET Core 2.1 is supported only on .NET Framework, not on .NET Core 2.1 anymore -- see [.NET Releases](https://github.com/dotnet/core/blob/main/releases.md) and [.NET Core 2.1 end of support](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/)

**Comment by contactkiran1899** [comment]
> It looks like the request is being canceled. Do you have a cancellation token triggering, or a timeout configured on the `HttpClientHandler`/`SocketsHttpHandler`?

Dont have a timeout configured on the httpclienthandler. do we know the general timeout limit for a httpclienthandler ??
we dont have  a cancellation token getting triggered.  We have series of PUT verb calls happening at that time . So, im not sure whether the httpclient socket connection is closed after multiple requests. Also we dont see this happening all the time 8-10 instances through out the day.

**Comment by contactkiran1899** [comment]
> .NET Core 2.1 end of support

@karelz  this was happening much before the .NET Core 2.1 end of support. happened to open this ticket just now.

**Comment by karelz** [comment]
@contactkiran1899 do you still run into the issue on .NET Core 2.1 (which is unsupported)? Or were you able to upgrade to newer version?
If you upgraded, can you please confirm if you're still running into the problem?

**Comment by karelz** [comment]
No response for a month, closing as not enough info to make it actionable.
