### ISSUE TITLE
[wasm] Unable to evaluate in Blazor Wasm

### ISSUE THREAD

**Issue by Andrew-Webb** [dotnet/runtime#59694]
Visual Studio Pro 2019 @ version 16.11.3

1. Create a new Blazor WebAssembly project (ASP.NET hosted; .NET 5.0).
2. Set the Server project to be the startup project.
3. Run it with F5.
4. Go to the `Fetch data` page.
5. Observe the correct weather data.
6. Close the browser / stop running the project.
7. Edit `Pages/FetchData.razor` in the Client project and change the GetFromJsonAsync call to this...

```
        try
        {
            forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast1");
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }
```

8. Set breakpoint on the `Console.WriteLine(ex.Message);` line.
9. Re-run the app with F5.
10. Go to `Fetch data` page.
11. Breakpoint set above will have been hit, since path "WeatherForecast1" is bad.
12. `ex` is in scope.  We suspect that the type of the exception is not actually System.Exception, so in QuickWatch window type `ex.GetType()` and press enter.

The result is...

![](https://user-images.githubusercontent.com/3470891/127134204-2bb7713a-1091-45b3-9321-eb6a3365bae0.png)

This repro has been derived from my earlier repro posted to https://github.com/mono/mono/issues/19942 and re-test and updated with the latest version of Visual Studio 2019 as of September 28th 2021.

**Comment by thaystg** [comment]
This is working on net6.
![image](https://user-images.githubusercontent.com/4503299/135078844-b903a7b3-a417-4952-a39f-cbc341f4b83c.png)

**Comment by Andrew-Webb** [comment]
@thaystg 

In .NET 5.0 - which is all I can use - if I **log** the type of the exception...

```
        try
        {
            forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast1");
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.GetType());
        }
```

I get "System.Text.Json.JsonException" - not System.RuntimeType.  Did you try to evaluate `ex.GetType()`?

**Comment by thaystg** [comment]
![image](https://user-images.githubusercontent.com/4503299/135090208-79e8b426-4727-4eb6-8e8e-0cff4a866870.png)
GetType() returns a System.RuntimeType, as you can see in the picture. Console.WriteLine calls a ToString, that is why you see a different result.

**Comment by Andrew-Webb** [comment]
Ok, I can see the `System.Text.Json.JsonException` in your new screenshot, so I'm satisfied that there's been a full evaluation.  I just wanted to check and double-check.  Thanks.

Might there be a fix for .NET 5?  Or will we *have* to move on to .NET 6 in order to eval expressions in the debugger (for Blazor Webassembly)?  I ask because this failure ("Unable to evaluate") is very, very common and having to migrate all my .NET 5 projects to 6 might be a pain.

**Comment by thaystg** [comment]
Yes, you will need to migrate to .NET 6, we don't have plans to backport this feature to .NET 5. I'm sorry about that.

**Comment by Andrew-Webb** [comment]
Ok, thanks!  I feel happier today knowing this long-standing problem will be gone in the near future.
