### ISSUE TITLE
Dotnet command cannot be found after installing .NET 6.0.100-rc.2.21476.4-osx-x64.pkg on Apple M1.

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/runtime#59691]
Affected Mac:
Mac OS: Big Sur(11.6)-M1 chip
.NET 6 SDK:
.NET 6.0.100-rc.2.21476.4

Repro steps:
1.Install .NET 6 RC2 SDK on Mac M1: 6.0.100-rc.2.21476.4
Artifacts:https://dev.azure.com/dnceng/internal/_build/results?buildId=1387263&view=artifacts&pathAsName=false
2.Run "dotnet --info" on terminal.

Expected:
Dotnet info should be displayed normally.

Actual:
Dotnet command cannot be found.
![Screen Shot 2021-09-28 at 10 51 55 AM](https://user-images.githubusercontent.com/46206739/135032584-149e0dd7-868b-4c38-a78f-4735372292e3.png)

Notes:
This issue not repro when installing .NET 6.0.100-rc.2.21476.4-osx-arm64.pkg.
![Screen Shot 2021-09-28 at 10 54 04 AM](https://user-images.githubusercontent.com/46206739/135033667-803be084-ac00-48f4-a885-db87cc6d4e9d.png)

**Comment by jeffschwMSFT** [comment]
cc @ericstj

**Comment by ericstj** [comment]
@richlander This is by design. Only the ARM64 installer adds itself to path on an ARM64 machine.

https://github.com/dotnet/designs/blob/main/accepted/2021/x64-emulation-on-arm64/x64-emulation.md#install-location

You can run the dontet command directly from /usr/local/share/dotnet/x64

**Comment by richlander** [comment]
I will discuss this in the RC2 blog post.

**Comment by JiahongJin1** [comment]
Yes, we can run dotnet command directly from /usr/local/share/dotnet/x64, so close this issue as it is by design.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/46206739/135224485-d29aa6f2-8cff-4f96-90a3-82fe15db03ea.png)
