### ISSUE TITLE
.Net 6 Host High CPU Issuie

### ISSUE THREAD

**Issue by OrhanAykac** [dotnet/runtime#59693]
### Description
I'm developing a project on Visual Studio 2022 Preview 4.1 with .Net 6 RC1
That project is a .Net 6 WebAPI and Blazor Web Assembly ClientApp

When project first run its using %15 of CPU, then if I close the project then VS CPU using to high CPU but usage does not decrease.
How can I solve this issue?
Thanks.

![Screenshot_1](https://user-images.githubusercontent.com/28669799/135039585-337000ca-8bd7-49c2-be7a-9a9f6c21934d.jpg)

### Configuration

My PC configuration;
CPU  İ7 10750H
RAM 16GM
Disk NVME

**Comment by jeffschwMSFT** [comment]
@OrhanAykac given this is related to Visual Studio performance, can you file the issue using https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?  Then link the issue here?

**Comment by OrhanAykac** [comment]
Hi @jeffschwMSFT ,
Thanks, I will do.
