### ISSUE TITLE
Linux: Instantiating a LdapConnection with a server string including a port number in .Net6.0-rc1 System.DirectoryServices.Protocols throws later an error at a SendRequest

### ISSUE THREAD

**Issue by p3rdu** [dotnet/runtime#59701]
### Description
If you instantiate a LdapConnection with a string consisting from a server name and a port number e.g.
```
LdapConnection ldap = new LdapConnection("ldap.example.com:636");
```  
then a later method call like 
```
DirectoryResponse dResp = ldap.SendRequest(request);
```
yields
```
Exception has occurred: CLR/System.DirectoryServices.Protocols.LdapException
An unhandled exception of type 'System.DirectoryServices.Protocols.LdapException' occurred in System.DirectoryServices.Protocols.dll: 'A bad parameter was passed to a routine.'
   at System.DirectoryServices.Protocols.LdapConnection.Connect()
   at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request)
```

However when instantiating the LdapConnection in this manner 
```
LdapConnection ldap = new LdapConnection(new LdapDirectoryIdentifier("ldap.example.com",636));
```
then same SendRequest works without exceptions.

Documentation at

[.Net Documentation System_DirectoryServices_Protocols_LdapConnection__ctor_System_String_](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.ldapconnection.-ctor?view=dotnet-plat-ext-5.0#System_DirectoryServices_Protocols_LdapConnection__ctor_System_String_)

states that

server String
A string specifying the server which can be a domain name, LDAP server name or dotted strings representing the IP address of the LDAP server. Optionally, this parameter may also include a port number, separated from the right end of the string by a colon (:).

### Configuration

.Net6-rc1 Linux Ubuntu 18.04 x86-64

### Regression?

Don't know.

**Comment by joperezr** [comment]
Thanks for finding this issue and for logging it @p3rdu. We should be consistent to how Windows currently works here, which by looking at the documentation that you found, then we should likely be parsing this and setting the port accordingly. Did you get a chance to check if this works in Windows? I'm marking this issue as up-for-grabs in case anyone wants to get a stab at it before we get to it.

**Comment by KamranShahid** [comment]
faced same issue today in .net core 3.1 application

**Comment by alexavator** [comment]
faced same issue today in .net core 3.1 and .net5 application.

**Comment by alexavator** [comment]
@KamranShahid thank you for answering, 
Well, yes, there is a workaround by using a LdapDirectoryIdentifier. 

But I just mention, that I faced with a problem using LdapConnection(string) ctor, because it is still not fixed. 

By the way, I faced with [another problem ](https://github.com/dotnet/runtime/issues/66652) now

**Comment by retifrav** [comment]
I got this issue on Kubuntu 22.04 (*and on Mac OS 12.4*) with the following .NET environment:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.300 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

I have a .NET 6 project that uses `System.DirectoryServices.Protocols` version `6.0.1`.

I can confirm that LDAP connection string with port (`some.domain.com:389`) works only on Windows, while on GNU/Linux and Mac OS that fails with "*A bad parameter was passed to a routine*" error. Removing the port from connection string (`some.domain.com`) does indeed resolve the issue.

**Comment by KamranShahid** [comment]
Best thing is to always test out the build in WSL2 with for atleast with linux distributable. in .net core 2.1 time have faces some similar issue with some logging framework and able to resolve after able to debug/reproduce it with WSL2

**Comment by silkfire** [comment]
How about for .NET 8?

**Comment by buyaa-n** [comment]
Now it is late for fixing it in .NET 8, in this RC2 timeframe we basically only fix regressions from previous release. Given that there is a work around we can consider fixing it in .NET 9.

**Comment by KamranShahid** [comment]
not good if even not fixing in .net 8. I faced it in .net 3.1

**Comment by buyaa-n** [comment]
@silkfire @KamranShahid this is fixed in main (.NET 9), if you still want it ported to .NET 8 a `customer testing` would be helpful for getting servicing approval from management. You could test the fix by [Dogfooding daily builds of .NET](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md#dogfooding-daily-builds-of-net), the example in the doc is for `.NET 8`, you will need to update the Nuget feeds into `.NET 9` feed: https://github.com/dotnet/runtime/blob/42a6776e6cb1569fe277181f424ccbbe243cf386/NuGet.config#L23 
After your verification we could ask for porting the fix into .NET 8, thank you!
