### ISSUE TITLE
FindPythonWindows does not error gracefully

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/runtime#59724]
I recently tried to `Build.cmd -libs` in the runtime and had the following error:

`F:\src\runtime\eng\python.targets(8,5): error MSB3073: The command "..." exited with code 9009. [F:\src\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]`

I installed Python for Windows and then the build succeeded.

**Expected behavior:** The build error indicates what the user needs to do to fix the problem (install a missing prerequisite). Ideally runtime would be able to install the prerequisites it needs in a repo-local fashion if they're not present on the machine.

**Actual behavior:** A relatively cryptic error message is given instead.

**Comment by safern** [comment]
cc: @hoyosjs @ivdiazsa @ViktorHofer I thought this experience was improved as we "errored" early on our dependencies?

**Comment by RussKie** [comment]
Hitting the same trying to build release/net6.0 branch

**Comment by ViktorHofer** [comment]
The ideal solution to that would be to replace the python logic in System.Private.CoreLib with a C# source generator or/and with msbuild logic. cc @jkotas

**Comment by ViktorHofer** [comment]
As the relevant code pieces are owned by CoreCLR, changing labels to reflect that.

**Comment by Anipik** [comment]
yep i hit this one several times as well :P
