### ISSUE TITLE
.NET6 preview 7 cannot find  System.Net.Quic automatically.

### ISSUE THREAD

**Issue by SilentHill** [dotnet/runtime#59730]
Hi,
I found an issue about System.Net.Quic in .NET6 preview 7
I created a .NET6 preview 7 C# project but it cannot find the System.Net.Quic.QuicListener.
I have to browse to "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0-preview.7.21377.19" to reference it directly.

In .NET6 Preview 6, it is normal.
In .NET6 Preview 7, it is abnormal.

Would you please check it? Thanks!

**Comment by wfurt** [comment]
This is expected. .NET 6.0 will NOT have public QUIC API. (for lack of time to get it in)

**Comment by wfurt** [comment]
related to https://github.com/dotnet/runtime/issues/54534.

**Comment by karelz** [comment]
Duplicate of #54534
