### ISSUE TITLE
Licence of Microsoft.Extensions in .NET Core 3.1.x ?

### ISSUE THREAD

**Issue by ericbl** [dotnet/runtime#59740]
The Microsoft.Extensions have different licence according to the versions:
Still apache2 on 3.1.19
https://github.com/dotnet/extensions/blob/v3.1.19/LICENSE.txt  (last change on this file is 3 years old)
but MIT on 5.0.1
https://github.com/dotnet/extensions/blob/v5.0.1/LICENSE.txt
which got then moved to this repo runtime if I understand properly.

Can you please clarify the licence of  Microsoft.Extensions for .NET 3.1 ?
If MIT, please update the licence file.
If Apache2, add a comment in the Readme to confirm it, this sounds misleading.

**Comment by ericbl** [comment]
related to https://github.com/dotnet/aspnetcore/issues/18873 where the licence was changed from Apache2 to MIT on Aspnet.Core, howerver only for .NET 6
as also asked in https://github.com/dotnet/aspnetcore/issues/37091

**Comment by eerhardt** [comment]
The above is correct. Microsoft.Extensions versions 3.1.x and earlier are licensed with Apache v2. In the 5.0 timeframe we moved the code to dotnet/runtime, and switched the license to MIT for versions 5.0 and going forward.

See https://github.com/dotnet/extensions/issues/2965 and https://github.com/dotnet/extensions/pull/3028.

You can also see the license on nuget.org for the specific version (or by looking in the nuget package). For example - https://www.nuget.org/packages/Microsoft.Extensions.Primitives/3.1.19.
