### ISSUE TITLE
Mono does not load native shared libraries next to an assembly with a DllImport to it.

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#59766]
When the following layout is provided on disk:

```
host/xunit.console.dll
dir/Microsoft.Interop.DllImportGenerator.Tests.dll
dir/Microsoft.Interop.NativeExportsNE.so
dir/Microsoft.Interop.DllImportGenerator.Tests.deps.json
dir/Microsoft.Interop.DllImportGenerator.Tests.runtimeconfig.json
...
```

And the process is run as follows:

```
dotnet exec --runtimeconfig DllImportGenerator.Tests.runtimeconfig.json --depsfile DllImportGenerator.Tests.deps.json xunit.console.dll DllImportGenerator.Tests.dll
```

Then Mono will fail to find the `Microsoft.Interop.NativeExports.so` shared library. CoreCLR is able to successfully find it and resolve exports with the same configuration (the only difference is Mono vs CoreCLR).

Here's the output from LD_DEBUG=libs for Mono:

>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:
>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:
>         1:     find library=libMicrosoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so
>         1:
>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:
>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:
>         1:     find library=libMicrosoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so
>         1:
>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE
>         1:
>         1:     find library=Microsoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/Microsoft.Interop.Tests.NativeExportsNE.so
>         1:
>         1:     find library=libMicrosoft.Interop.Tests.NativeExportsNE.so [0]; searching
>         1:      search cache=/etc/ld.so.cache
>         1:      search path=/lib64:/usr/lib64          (system search path)
>         1:       trying file=/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so
>         1:       trying file=/usr/lib64/libMicrosoft.Interop.Tests.NativeExportsNE.so

And for CoreCLR:

>          1:     calling init: /runtime/artifacts/bin/DllImportGenerator.Tests/net7.0-Debug/Microsoft.Interop.Tests.NativeExportsNE.so

**Comment by lambdageek** [comment]
Interesting.

It should definitely be looking next to the assembly if the `DLLIMPORTSEARCHPATH_ASSEMBLY_DIRECTORY` flag is set: 

https://github.com/dotnet/runtime/blob/8e9ab9f885644d6dee0b4813982507c10db14bf9/src/mono/mono/metadata/native-library.c#L529-L534

It looks like we set the  flag when it goes through `NativeLibrary.LoadByName`, but if you just have a normal `[DllImport]` and no dll import search flags on a custom attribute on the module, we set them to `0` which doesn't include the assembly directory

https://github.com/dotnet/runtime/blob/8e9ab9f885644d6dee0b4813982507c10db14bf9/src/mono/mono/metadata/native-library.c#L1050-L1052
