### ISSUE TITLE
random.next(low, hi) his is sometimes exclusive and sometimes inclusive.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59788]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/randomnextlow-hi-his-is-sometimes-ex/1478158)._

---
It has taken a lot of searching in various places on the net but from what I have seen Random.Next(min, max) the min value should be inclusive and the max value should be exclusive, I have also seen documentation that said the upper bound had to be equal to or greater than the lower.  I ran Next(4, 5) 100 times and got 4 every time, as expected. I ran Next(6, 5) and it threw an error, as expected. I ran Next(5,5) 100 times and got 5 every time, this is a problem because 5 is not less than the exclusive upper bound of 5.

As I see this it is a problem with the documentation, or a bug. If there is some explanation it might be a feature.  Or I could have a misunderstanding, it's been known to happen. 

If it was up to me the doc would say the upper bound had to be greater than the lower and Next(5,5) would throw an error. 

Another thing that makes it shakey for me is that Next(4,5) returns a maximum value of 4 and if I change the minimum to 5 the maximum it returns goes up. Changing the minimum should not change the maximum value it returns.

---
#### Feedback Bot on 7/19/2021, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by stephentoub** [comment]
The docs state:
https://docs.microsoft.com/en-us/dotnet/api/system.random.next?view=net-5.0#System_Random_Next_System_Int32_System_Int32_
"A 32-bit signed integer greater than or equal to minValue and less than maxValue; that is, the range of return values includes minValue but not maxValue. If minValue equals maxValue, minValue is returned."

So:

> I ran Next(5,5) 100 times and got 5 every time, this is a problem because 5 is not less than the exclusive upper bound of 5

This matches the doc'd behavior quoted: "If minValue equals maxValue, minValue is returned."
