### ISSUE TITLE
API Named SetupDiEnumDeviceInterfaces Of setupapi.dll  Error At .net core platform

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59787]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/API-Named-SetupDiEnumDeviceInterfaces-Of/1485487)._

---
[severity:I'm unable to use this version]
In .net6 and .net core 3.1 ，API Named SetupDiEnumDeviceInterfaces Of setupapi.dll  does not work.when same code work normally at .net framework

---
#### Feedback Bot on 7/25/2021, 07:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jeffschwMSFT** [comment]
I presume you are referring to this Win32 API: https://docs.microsoft.com/en-us/windows/win32/api/setupapi/nf-setupapi-setupdienumdeviceinterfaces.  Can you share your DllImport signature?

**Comment by AaronRobinsonMSFT** [comment]
Closing due to lack of information. Please feel free to open a new issues with the requested details &ndash; https://github.com/dotnet/runtime/issues/59787#issuecomment-931359297.
