### ISSUE TITLE
System.Text.Json: SourceGenerator on byte[] generates array of numbers not base64 string

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#59791]
I would like to take a stab at fixing this if the team agrees it is an issue.

### Description

Given this class:

```csharp
	internal class TestClass
	{
		public string Name { get; set; } = "Hello world";
		public int Value { get; set; } = 1337;
		public byte[] Binary { get; set; } = new byte[255];
	}
```

When serialized like this...

```csharp
string json = JsonSerializer.Serialize(new TestClass());
```

...you get...

```json
"{\"Name\":\"Hello world\",\"Value\":1337,\"Binary\":\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"}"
```

But if you do via a source generator a la...

```csharp
	[JsonSerializable(typeof(TestClass))]
	internal partial class JsonContext : JsonSerializerContext
	{
	}

	string json = JsonSerializer.Serialize(new TestClass(), JsonContext.Default.TestClass);
```

...you get...

```json
"{\"Name\":\"Hello world\",\"Value\":1337,\"Binary\":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}"
```

I think it is incorrect but also way slower ⌛ 

### Configuration

* Which version of .NET is the code running on? 6.0.100-rtm.21479.19

**Comment by eiriktsarpalis** [comment]
cc @layomia @ericstj. I suspect that divergent serialization formats might make this a good candidate for servicing in 6.0. Note that it would probably require adding an additional API to expose [ByteArrayConverter](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/ByteArrayConverter.cs) to the generator.

**Comment by ericstj** [comment]
I agree, I'd really hope we could have a state where we either support the serialization as the same or throw if it cannot be supported  Is this an outlier or is their some pattern that lends itself to a tail of these behavior differences?  Can we do something systematic to find all of them?

WRT to a new API, can we do something like GetDefaultConverter<T>() where T is the type to convert?  I believe that could still be trimmer safe, rather efficient once JIT specializes the method, and avoid forcing us to add new APIs for every new thing we add a built in converter for.

**Comment by eiriktsarpalis** [comment]
> Can we do something systematic to find all of them?

Effectively should check to find what in box converters are not being to source gen.

**Comment by ericstj** [comment]
>  in box converters are not being exposed to source gen.

Seems that we should have test cases for all of these that can be run through source generator.

Shouldn't the source generator be sharing the code that understands all inbox converters and either have a source-generator representation of the algo (if it is small and unlikely to require servicing), or fetch the converter and call into it?  Or is this grey-area where the converter is only hooked up with runtime settings?

**Comment by steveharter** [comment]
> Shouldn't the source generator be sharing the code that understands all inbox converters and either have a source-generator representation of the algo (if it is small and unlikely to require servicing), or fetch the converter and call into it? Or is this grey-area where the converter is only hooked up with runtime settings?

In this case the converter is implicit and not hooked up with runtime settings. The source-generator effectively has hard-coded knowledge of all inbox converters, which is separate from the serializer's, and the one for `byte[]` was missed. Sharing more collection tests would have caught this earlier, but that does require manually converting the existing tests.

**Comment by steveharter** [comment]
Options for v6:
1) Add method to obtain the ByteArrayConverter like we do for all other converters (requires public API add)
2) Detect usage of `byte[]` and fallback to the serializer (no fast path). This doesn't require any new API.
3) Keep as-is; not acceptable IMO since the srcgen vs. serializer serialization format would not be compatible. This means if you serialize byte[] with srcgen, then the reflection-based serializer won't be able to deserialize the JSON. And vice-versa.

**Comment by am11** [comment]
If performance is on par with .NET 5, IMO option 2 sounds reasonable to avoid the regression.
