### ISSUE TITLE
Add support to specify the ALC in which to generate a dynamic assembly.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/runtime#598]
Example Scenario

XmlSerializer lives in the default ALC of a project.
A type marked as Serializable lives in a custom ALC such as part of a plug-in to the project.
It finds and uses the XmlSerializer in the default ALC and creates the dynamic assembly in the default ALC which then doesn't know anything about the type needing to be serialized because it is in a different ALC.

This requires new APIs in CoreClr which WCF would then need to use to enable specifying where to create the generated dynamic assembly.

Original issue: dotnet/corefx#41286

- [ ] Port to 3.1.x

**Comment by jkotas** [comment]
> This requires new APIs in CoreClr

[AssemblyLoadContext.EnterContextualReflection](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.entercontextualreflection?view=netcore-3.0) should allow you to do this.
