### ISSUE TITLE
NullReferenceException in BindingDoesNotThrowIfReloadedDuringBinding

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#59800]
```
Microsoft.Extensions.Configuration.Test.ConfigurationTests.BindingDoesNotThrowIfReloadedDuringBinding

System.NullReferenceException : Object reference not set to an instance of an object
  at Microsoft.Extensions.Configuration.Test.ConfigurationTests.BindingDoesNotThrowIfReloadedDuringBinding() in /_/src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs:line 987
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1392305&view=ms.vss-test-web.build-test-results-tab&runId=40488044&resultId=110366&paneView=debug

Configuration: `net7.0-Linux-Release-x64-Mono_release-Ubuntu.1804.Amd64.Open`

Runfo Tracking Issue: [bindingdoesnotthrowifreloadedduringbinding](https://runfo.azurewebsites.net/tracking/issue/175)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1392305](https://dev.azure.com/dnceng/public/_build/results?buildId=1392305)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-Linux-Release-x64-Mono_release-Ubuntu.1804.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8b4381365e05413fbb/Microsoft.Extensions.Configuration.Functional.Tests/1/console.4a8c1222.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T05%25253A54%25253A06Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DnH46tOO8w%25252FI6IWZUjKk2ImszAXpx5CVKGFGCE2KVvvs%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8b4381365e05413fbb/Microsoft.Extensions.Configuration.Functional.Tests/2c43c89d-aa3e-4b4a-8a9f-e561c8db01e7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T05%25253A54%25253A06Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DnH46tOO8w%25252FI6IWZUjKk2ImszAXpx5CVKGFGCE2KVvvs%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|1|

**Comment by maryamariyan** [comment]
the test has been there for 3 years, seems like it might not be hit often, worth updating the how the test is written here:

https://github.com/dotnet/runtime/blob/48090398ac359a8862a87682b3265cb3e2f80a9d/src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs#L980-L987

**Comment by krwq** [comment]
I'd recommend to disable the test if not actively working on it. Would be good to validate if this is a product or test issue - it seems test could be a culprit but I'll leave the area owner to decide - please make sure to set appropriate label
