### ISSUE TITLE
Blazor WASM AOT code is 1 to 1.5 orders of magnitude slower than native CLR

### ISSUE THREAD

**Issue by jbecke** [dotnet/runtime#59816]
### Describe the bug

Non-UI code run in Blazor WASM/AOT in the browser is 1 to 1.5 orders of magnitude slower than native CLR across a wide variety of workloads. I would expect WASM AOT to always be a bit slower than native but not an *order of magnitude* or more slower. 

We have been able to repro these [benchmarks](https://csharp-wasm-benchmark.acmion.com/) in real-world workloads involving the [OpenXML SDK](https://github.com/EricWhiteDev/Open-Xml-PowerTools) and [OpenXML PowerTools](https://github.com/EricWhiteDev/Open-Xml-PowerTools). Specifically we have a workload that runs in ~300ms on Mac CLR while taking *4000ms when AOT'd with Blazor*, and 8000ms when interpreted with the WASM CLR.

- Is this expected behavior with .NET 6 Preview 7? 
- Is this being worked on or should we take this as a fact of life?
  - WASM/AOT is currently unusable for us until this is at least on the same order of magnitude in terms of speed

### To Reproduce
See [benchmarks](https://csharp-wasm-benchmark.acmion.com/) -> seems to be most any workload is MUCH slower than native CLR.

### Exceptions (if any)
n/a

### Further technical details
- ASP.NET Core version: .NET 6 Preview 7
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14/

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS Code 1.60.2

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by SamMonoRT** [comment]
@lewing - do we have most recent numbers to compare. My guess is we can close this, but wanted to verify this.

**Comment by SamMonoRT** [comment]
@radekdoulik - based on your last measurements, do you think we can close this ?

**Comment by lewing** [comment]
There has been considerable improvement in the AOT targets since 6p7. If you would like to update the issue with your experience on .NET 8 preview 6 we will take a look.
