### ISSUE TITLE
Investigate codegen for Vector128.GetUpper

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#59838]
As per https://github.com/dotnet/runtime/pull/53450#discussion_r719753375, it would like be beneficial to investigate changing the codegen of `Vector128.GetUpper` to use `DUP` rather than `EXT` on ARM64.

category:cq
theme:codegen

**Comment by JulieLeeMSFT** [comment]
Cc @dotnet/jit-contrib

**Comment by TIHan** [comment]
@TamarChristinaArm , I have a question, looking at the [A78 Optimization Guide](https://developer.arm.com/documentation/102160/r1p2/?lang=en), EXT D-form and DUP D-form both have the same latency and throughput, is this indeed true? If so, then there wouldn't be a benefit to emitting `DUP` instead of `EXT` here.

**Comment by TamarChristinaArm** [comment]
@TIHan yeah they have the same latency and throughput across all Arm Cortex and Neoverse cores.
The only improvement here is if one does `Vector128.GetUpper().AsScalar()` in which case the genreg `DUP` is faster than `EXT + UMOV`.

**Comment by tannergooding** [comment]
`GetUpper/Lower()` followed be a `GetElement` (including `ToScalar()`) seems like a general morph optimization.

**Comment by TamarChristinaArm** [comment]
> `GetUpper/Lower()` followed be a `GetElement` (including `ToScalar()`) seems like a general morph optimization.

Indeed, we also do some of the following, like `Vector128<uint>.GetUpper().ToScalar() >> 16` would instead generate an `UMOV` on shorts instead by remapping the index.  I don't know how common that is in .NET code, we typically see it during some image/video processing workloads.  Just mentioning in case useful.

**Comment by TIHan** [comment]
Thank you for the information @TamarChristinaArm .

Closing this issue as we confirmed the optimization won't benefit. I'll leave it up to @tannergooding to create another issue regarding `Vector128.GetUpper().AsScalar()` if we plan to do that.
