### ISSUE TITLE
Expose _version in List<T> and other collections

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#59854]
### Background and motivation

I want to check if lis was changed.
It has private field _version.

### API Proposal

```C#
public class List<T> // Dictionary, Set, e.t.c
{
    public int Version => _version
}

```     
or
```C#
public static class CollectionsMarshal
{
   public static int GetVersion(List<T> src) => src._version;
   public static int GetVersion(Dictionary<T> src) => src._version;
   // e.t.c.
}
```

### API Usage

```C#
var ver = list.Version;
if (ver != _validVersion) {
   // do something
   _validVersion = ver;
}
```
or
```C#
var ver = CollectionsMarshal.GetVersion(list);
if (ver != _validVersion) {
   // do something
   _validVersion = ver;
}
```

**Comment by teo-tsirpanis** [comment]
I wouldn't expose the integer value of the collection's version, but something like the following:

``` csharp
public readonly struct CollectionChangeTracker {
    public bool HasChanged { get { ... } }
}

public static class CollectionsMarshal
{
   public static CollectionChangeTracker TrackChanges(List<T> src) => ...;
   public static CollectionChangeTracker TrackChanges(Dictionary<T> src) => ...;
   // e.t.c.
}
```

And it could be used like this:

``` csharp
var list = new List<int>();
var changeTracker = CollectionsMarshal.TrackChanges(list);

Assert.False(changeTracker.HasChanged);

list.Add(0);
Assert.True(changeTracker.HasChanged);
```

**Comment by EgorBo** [comment]
I think `TrackChanges` name can be confused, e.g. one might expect it track things like
```
myList[4] = 0;
```

**Comment by teo-tsirpanis** [comment]
It does track item changes actually:

https://github.com/dotnet/runtime/blob/70cb44e6997b88126b50268f0c0a4db9cad6aa17/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L155-L163

**Comment by EgorBo** [comment]
> It does track item changes actually:

Ah, indeed, I could argue that more complicated examples like  `myList[4].MyProperty = 0` 🙂 won't trigger it... but it happens even today with "ImmutableList" etc..

**Comment by eiriktsarpalis** [comment]
The `_version_` field is an implementation detail intended to detect modification during enumeration. As such, I don't think it should be exposed in any public APIs. We generally avoid adding new APIs to very popular generic types unless there is a compelling use case. As such, I'm going to close this issue.

Wouldn't a specialized collection like [`ObservableCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?view=net-5.0) cover your use case perhaps?

**Comment by Joe4evr** [comment]
Note also that it's already possible to circumvent the version increment with `CollectionsMarshal.AsSpan`.
```cs
var myList = new List<int>() { 0, 1, 2, 3, 4, 5 }
var span = CollectionsMarshal.AsSpan(myList);
span[4] = 0; // updates the list contents, doesn't increment '_version'
```
