### ISSUE TITLE
Type.IsAssignable() treats all enum arrays assignable from each other

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/runtime#59877]
I found this unexpected behavior when trouble-shooting a puzzling bug in my application. 

The root cause turns out to be that C# treats all enum array as assignable from each other even though the element enum types are not treated as assignable. The code below demos such behavior.

    enum EnumOne { One, Two, Three }
    enum EnumTwo { Mon, Tue, Wed, Thur }
    
    var thisIsFalse = typeof(EnumOne).IsAssignableFrom(typeof(EnumTwo));
    var thisIsTrue = typeof(EnumOne[]).IsAssignableFrom(typeof(EnumTwo[]));

My further test shows that such behavior dates back to .NET Framework and is carried on to .NET 5. I am hesitant to claim it as a bug simply because of its long history, but it definitely is counter intuitive. Can someone help me understand the rationale?

Type.IsAssignableTo() behaves the same way.

**Comment by SingleAccretion** [comment]
> but it definitely is counter intuitive

Nevertheless, by design. It is the consequence of how array compatibility is defined in ECMA 335 (see `I.8.7`):

> The reduced type ignores the semantic differences between enumerations 
and the signed and unsigned integer types; treating these types the same if they have the same 
number of bits.

> A signature type T is compatible-with a signature type U if and only if at least one of the 
following holds.

> 5. T is a zero-based rank-1 array V[], and U is a zero-based rank-1 array W[], and V is 
array-element-compatible-with W.
> 6. T is an array with rank r and element type V, and U is an array with the same rank r and 
element type W, and V is array-element-compatible-with W.

> A signature type T is array-element-compatible-with a signature type U if and only if T has 
underlying type V and U has underlying type W and either: 
> 1. V is compatible-with W; or 
> 2. V and W have the same reduced type.

A rationale for this decision, made "in V1", is not known to me.

**Comment by jkotas** [comment]
Note that there are also opposite cases - where the types are assignable and the arrays are not:
```csharp
var thisIsTrue = typeof(object).IsAssignableFrom(typeof(int));
var thisIsFalse = typeof(object[]).IsAssignableFrom(typeof(int[]));
```

**Comment by jkotas** [comment]
> Can someone help me understand the rationale?

It does not violate type and memory safety in any way, so it did not hurt to allow it. I am not aware of the motivating reason for allowing it.

**Comment by WenningQiu** [comment]
Well the C# compiler apparently takes a different view - our app generates code based on the outcome of IsAssignableFrom(), but the generated code won't compile.

**Comment by SingleAccretion** [comment]
Yes... this is one of the unfortunate cases where the C# and runtime type systems disagree.
