### ISSUE TITLE
Allow a pre-generated serialization assembly to load in the same ALC the type is in.

### ISSUE THREAD

**Issue by StephenBonikowsky** [dotnet/runtime#599]
The XmlSerializer by default loads a pre-generated serialization assembly into the default context even when the type it was generated for lives in a different ALC.

Need to create a mechanism that allows the pre-generated serialization assembly to be loaded into the ALC where the type it was generated for lives.

Original issue: dotnet/corefx#41286

- [ ] Port to 3.1.x

**Comment by HongGit** [comment]
Dupe#1388
