### ISSUE TITLE
[API Proposal]: Flag to include all SSL intermediate certificates explicitly in SslStreamCertificateContext

### ISSUE THREAD

**Issue by dnobori** [dotnet/runtime#59906]
### Background and motivation

Hello.

SSL negotiation in modern HTTPS web servers sometimes requires the function to submit the multiple trust paths of SSL intermediate certificates to the HTTPS web clients. An well-known example is the cross root certificate technique which is recently widely used including Let's Encrypt. Cross-root certificates are required to support both legacy and modern SSL clients. (As an example, in particular, people need to resolve the problem that has been occurring since September 30, 2021 with the expiration of Let's Encrypt's older CAs.) As an example of the necessity of the multiple trust path of SSL intermediate certificates is documented in the https://letsencrypt.org/docs/certificate-compatibility/ web page.

The current implementation of SSLStreamCertificateContext.Create() always uses X509Chain.Build() to create an SSL intermediate certificate chain, even if the developer specifies multiple intermediate certificates in the additionalCertificates argument. So only single trust chain will be left, and all other chains will be deleted. In other words, even if a developer carefully builds multiple intermediate certificate chains manually with the additionalCertificates parameter, the previous SSLStreamCertificateContext.Create() function always leaves only a single chain out of the multiple chains, and all other chains will disappear.

Therefore the current .NET's SslStream and Kestrel Web Server implementations are unable to provide the fundamental functionality that is supported by popular SSL web servers (e.g. Nginx) for modern SSL applications.

This suggestion adds the addAllAdditionalCertificatesIfSupported flag to the SSLStreamCertificateContext.Create() method.

If the developer sets this flag, the SSLStreamCertificateContext.Create() API will not use X509Chain.Build() to build the chain. Instead, the API will copy each of specified intermediate certificates from X509Certificate2Collection to the certificates array simply. Thus the SslStream or Kestrel Web Server will respond to the SSL client with the whole trust chain without unintentional deletion.

This new flag is optional and never change the API specification. If this flag is not set, it will not change the behavior at all.

I already implemented the new API in https://github.com/dnobori/runtime/commit/131f64b2f69e1545daa40131f703f7efd2454300 and submit the https://github.com/dotnet/runtime/pull/59898 PR. Then @davidfowl kindly informed me that I need to follow the API review process before PR. Therefore I open this issue here.

### API Proposal

- My proposed API:

```C#
namespace System.Net.Security
{
    public partial class SslStreamCertificateContext
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static SslStreamCertificateContext Create(X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline); // Existing
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static SslStreamCertificateContext Create(X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline, SslCertificateTrust? trust); // Existing
        
        public static SslStreamCertificateContext Create(X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline = false, SslCertificateTrust? trust = null, bool addAllAdditionalCertificatesIfSupported = false); // New
    }
}
```     

- Current API (For reference):
```C#
namespace System.Net.Security
{
    public partial class SslStreamCertificateContext
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static SslStreamCertificateContext Create(X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline); // Existing
        
        public static SslStreamCertificateContext Create(X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline = false, SslCertificateTrust? trust = null); // Existing
    }
}
```

- Implemention example
My implemention of the the new API is https://github.com/dnobori/runtime/commit/131f64b2f69e1545daa40131f703f7efd2454300

### API Usage

```C#
X509Certificate2 myWebServerCert = fromMyWebServerCertFileOrSomething;
X509Certificate2Collection intermediateCerts = new X509Certificate2Collection();

intermediateCerts.Add(cert1); // An intermediate cert from the Root CA X
intermediateCerts.Add(cert2); // An intermediate cert from the Root CA B


// Existing API (never breaks current behavior)
var context1 = SslStreamCertificateContext.Create(myWebServerCert, intermediateCerts);

// context1 contains only cert1.
// SslStreamCertificateContext.Create() removes cert2 in the implementation.
// It is current behavior.


// New proposed API
var context2 = SslStreamCertificateContext.Create(myWebServerCert, intermediateCerts, addAllAdditionalCertificatesIfSupported: true);

// context2 contains both cert1 and cert2 since we call SslStreamCertificateContext.Create() with
// addAllAdditionalCertificatesIfSupported flag set.
// This means that the web server will return the entire intermediate certificates chain to
// the SSL client correctly, same as other modern web servers behavior (e.g. Nginx, etc.)


// ... SSL accepting code as the web server with using context2 ...
```     

### Risks

- General
I believe that the risk is very minor. There is virtually no performance impact or behavior breaking changes. Also, it is safe if we use arguments override and the `[EditorBrowsable(EditorBrowsableState.Never)]` technique to keep the current API signature for existing application. This is same to the previous API modification in the https://github.com/dotnet/runtime/pull/55104 PR.

- My test result
I have tested my implementation example https://github.com/dnobori/runtime/commit/131f64b2f69e1545daa40131f703f7efd2454300 in practice using the intermediate certificate chain that comes with SSL certificates issued by Let's Encrypt, and it works correctly. This patch is only available for Linux and OSX using the OpenSSL PAL.

- Win32 problem
This new flag is only available for Linux and OSX using the OpenSSL PAL. Unfortunately, the Win32 platform does not use OpenSSL PAL and cannot support multiple trust paths due to the specification of the SSL certificate chain abstracted by the OS. addAllAdditionalCertificatesIfSupported parameter is simply ignored on Win32 platforms for safety.

**Comment by wfurt** [comment]
I'm wondering if we should have more flexibility for the X509Chain. cc: @baronjs @vcsjones

**Comment by dnobori** [comment]
Hi, thank you for comment.

> I'm wondering if we should have more flexibility for the X509Chain. 
Yesterday I got the exactly same idea and I studied the current implementation and specification of the X509Chain class. Unfortunately, X509Chain is designed to represent a single trusted certificate chain. We will have an array of built X509Chain as a result of multiple cross-root signed certificates even if we use X509Chain. In this case, we need to mixture and remove duplication from multiple X509Chain results manually in the SslStreamCertificateContext.Create() implementation. Moreover, it seems that there is no method to specify the preferred root certificate when building a X509Chain. So I realize that it is difficult to use X509Chain() to ensure the addAllAdditionalCertificatesIfSupported flag support.
For reference, most of traditional well-known SSL server implementations (e.g. Apache, Nginx, Postfix, Dovecot, etc.), it seems that these servers simply submit administrator's specified SSL certificates list to the SSL client without any complicated processing (like X509Chain and SslStreamCertificateContext.) For not only avoiding complicated issues around processing X509 chain but also the maximum performance (SSL accepting throughput), I believe that simply submit all administrator-specified SSL certificates to the client is the best idea in this new flag. This is the reason why my suggesting implementation of the new flag is to simply constructs the imtermediate certificate array.

**Comment by vcsjones** [comment]
I would agree with @dnobori. There was some discussion on this previously at https://github.com/dotnet/runtime/issues/37933#issuecomment-644823434.

Seems like we are asking for the `CreateAndIKnowWhatImDoing` API that was mentioned.

`X509Chain` represents a single trusted chain. In this scenario though the desired behavior is to be able to help clients build the best chain that is possible for them, regardless of what the server thinks. In fact, there may be multiple trust paths that can be taken from different clients.

**Comment by dnobori** [comment]
vcsjones, thank you very much for information.

I agree that my proposed API flag is like the (not-existing yet) method mentioned as `CreateAndIKnowWhatImDoing`, and it is really needed by SSL-based server developers in the present time, since Let's Encrypt now needs two cross-signed certificate trust path after October 2021. (at last the time come.)

In order to reduce the number of static `CreateXXX` methods, I believe that the adding the new `default=false` flag on the existing `Create()` method is the best way, for consistence to the previous example: https://github.com/dotnet/runtime/pull/55104

**Comment by wfurt** [comment]
We should investigate. It may not be feasible on Windows. I don't think we should proceed unless we can make it work consistently across major platforms.

**Comment by wfurt** [comment]
While I would not mind the new API/flag I don't think we can implement it on Windows. In general there is no way how to pass specific certificates to SSPI and schannel to use them exactly. 
This can be revisited if Windows add some way how to do it or if somebody can make it work with current versions.
