### ISSUE TITLE
JIT should optimize {array | span}.Length division by constant that is power of 2

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#59922]
E.g.
```c#
Span<byte> span = ...
nint n = span.Length / 8;    // or any constant that is a power of two
```
produces [integer division by consant](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGA7AJZ8MDALLkAFAGUADtj4AeYAE8MMAHwNccvgEoGAXk3b5AOgAyMPgHMMACwYB6BgA4A3Fx70Gg4WNLSOkqqGlo6+kYMEr4YuiZ8Fla2Ds7untzefACuQiKidIHywWrG4Yaa0TnCcTqJNvZOrh7UPLw+VXkohYoqJWHyERXZuboSHTVmlvUpTTQAvkA) 
(Also tested with .NET 6 RC 1, and didn't find an issue or PR that addressed this.)

JIT should be able to recnogize that `.Length` isn't negative, so produce code that is equivalent to
```c#
nint n = (nint)(uint)span.Length / 8;
```
which produces (on x86)
```asm
shr rax, 3
```

This pattern is quite common, so it's tedious and a bit unreadable to have the "cast-hacks".

category:cq
theme:expression-opts
skill-level:intermediate
cost:small
impact:small

**Comment by EgorBo** [comment]
heh, I did for arrays (GT_ARRLEN) https://github.com/dotnet/runtime/pull/32368 🙂

**Comment by gfoidl** [comment]
Perfect 👍🏻, so the step to enable this for Span too isn't that big (hopefully).

**Comment by EgorBo** [comment]
I made a quick fix and checking diffs now

**Comment by stephentoub** [comment]
How many other optimizations are there that currently apply only to arrays but could also be relevant to spans?  It'd be great to drive that list to zero and then ensure no additional ones creep in.  More and more code is being converted from arrays to spans, and we want to avoid unnecessary regressions.

**Comment by SingleAccretion** [comment]
There are certainly some optimizations that do not benefit spans equally.

The most obvious example is VN, which can "see" through assignments to array elements (because there is intrinsic understanding of array indexing similar to that of fields built into the compiler):
```C#
private static int RedundantBranchSpan(Span<int> a)
{
    a[1] = 0;

    if (a[1] is 0)
    {
        return 1;
    }

    a[2] = 1;

    if (a[1] is 0) // The compiler will not see this branch as redundant, there was a write to memory.
    {
        return 1;
    }

    return 2;
}

private static int RedundantBranchArray(int[] a)
{
    a[1] = 0;

    if (a[1] is 0)
    {
        return 1;
    }

    a[2] = 1;

    if (a[1] is 0) // The compiler will see this branch as redundant since it knows a[1] and a[2] don't interfere
    {
        return 1;
    }

    return 2;
}

// VNs are also used for CSE purposes, so redundant loads may not be optimized as well.
private static int SpanDoubleLoad(Span<int> a)
{
    int sum = 0;

    sum += a[1];

    a[2] = 1;

    sum += a[1]; // This will be a load
    
    return sum;
}

private static int ArrayDoubleLoad(int[] a)
{
    int sum = 0;

    sum += a[1];

    a[2] = 1;

    sum += a[1]; // a[1] will be CSEed and used from a register
    
    return sum;
}
```
It is hard for me to say which other optimizations are affected (and how), and how impactful the above is in real-world code, or how hard would the fix be (I suspect though that it will not be so trivial, because the existing mechanism already has some unsightly maintainability problems).

**Comment by JulieLeeMSFT** [comment]
> The most obvious example is VN,

cc @jakobbotsch for VN on span. 
cc @dotnet/jit-contrib
