### ISSUE TITLE
JsonSerializer support for JsonDocument types in source generation mode

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#59954]
`JsonSerializer` [supports](https://github.com/dotnet/runtime/blob/71e324fa72e31928d39e8e2f375bdca4c0a11957/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/JsonDocumentTests.cs) (de)serialization of `JsonDocument` instances. We should add the same support in source-generation mode by exposing the `JsonDocumentConverter` via a new [`JsonMetadataServices`](https://github.com/dotnet/runtime/blob/71e324fa72e31928d39e8e2f375bdca4c0a11957/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonMetadataServices.Converters.cs) API.

**Comment by strobelt** [comment]
I created PR #60236 to fix this. Let me know if I did it right and if there are any improvements I can do!
