### ISSUE TITLE
[API Proposal]: ImmutableArray[Slice]

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#59965]
### Background and motivation

To be able to create child Immutable Arrays easily.

### API Proposal

Not sure.

### API Usage

```C#

var Slice = MyImmutableArray[2..7];

```

**Comment by eiriktsarpalis** [comment]
Exposing range functionality like array does sounds like a reasonable request. The API proposal as it stands needs a bit more work however.

**Comment by eiriktsarpalis** [comment]
Actually, it appears this is a duplicate of https://github.com/dotnet/runtime/issues/22928. I'm going to close this one.
