### ISSUE TITLE
runtime.osx-arm64.runtime.native.System.IO.Ports missing

### ISSUE THREAD

**Issue by SeanMollet** [dotnet/runtime#59972]
### Description

There isn't a nuget package for System.IO.Ports native runtime for osx-arm64.

### Configuration

.net 6-RC1
OSX - 11.5.2
Macbook Air - Apple Silicon

### Regression?

Apple Silicon support is a new feature for .net 6

### Other information

I was able to build the native libs on my M1 machine and they built correctly. However, I can't for the life of me figure out how to build the nupkg for native libs. I've read all the various documentation, tried with dotnet pack and  nuget on every .proj I could find and VS-mac to no avail.

This document has a great section on building the native components:
https://github.com/dotnet/runtime/tree/v6.0.0-rc.1.21451.13/docs/workflow/building/libraries

But, it says nothing about how to package them. I assume it's easy and I'm just failing at finding it.

**Comment by SeanMollet** [comment]
@Jozkee  I'm not sure how the package build process works for native libs (hence my issue post), but if you look at:
https://github.com/dotnet/runtime/tree/v6.0.0-rc.1.21451.13/src/libraries/System.IO.Ports/pkg

There isn't a runtime.osx-arm64.runtime.native.System.IO.Ports.proj file in there. The actual library itself from Native compiles just fine on osx-arm64. I added an appropriate package .proj, but that's where I hit a dead end. 

For the short term, can I impose on you for a hint as to how that packaging process works or is kicked off? I'm happy to convert this to a PR, just need that last bit of information.

**Comment by ViktorHofer** [comment]
A runtime.osx-arm64.runtime.native.System.IO.Ports nuget package never existed, hence this issue is a feature request to support the native part of System.IO.Ports on OSX arm64. The work to make that happen is simply adding a `runtime.osx-arm64.runtime.native.System.IO.Ports.proj` file similar to the others. That should be all that is required as the official build (which then produces these packages and uploads it to our feeds) already has an OSX arm64 leg: https://github.com/dotnet/runtime/blob/05345b2a78a571ef1c3861322788ffdeadb57c04/eng/pipelines/runtime-official.yml#L293.

**Comment by ViktorHofer** [comment]
A normal build of the libraries subset should produce the package: `build.sh libs`.

**Comment by SeanMollet** [comment]
@ViktorHofer negative. It fails with:

/Users/sean/Projects/runtime/src/libraries/System.IO.Ports/pkg/runtime.osx-arm64.runtime.native.System.IO.Ports.proj : error NU1101: Unable to find package runtime.osx-arm64.runtime.native.System.IO.Ports. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, dotnet6, dotnet6-transport, richnav [/Users/sean/Projects/runtime/Build.proj]

It's a chicken/egg problem of some sort.

**Comment by ViktorHofer** [comment]
ah sorry, yes. Please add this property into the added proj file:

```
<DisablePackageBaselineValidation>true</DisablePackageBaselineValidation>`
```
