### ISSUE TITLE
SSL/TLS handshake fails in Ubuntu 20.04 and Net 5.0 using mysql server container

### ISSUE THREAD

**Issue by sanchhoker** [dotnet/runtime#59986]
Describe the bug
While upgrading from .Net 3.0 to 5.0 we are encountering SSL handshake failure in connecting to MySql containers while using Debian based image for .Net

To Reproduce
Exceptions (if any)
```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
---> Interop+Crypto+OpenSslCryptographicException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
--- End of inner exception stack trace ---
at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan1 input, Byte[]& sendBuf, Int32& sendCount) at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
--- End of inner exception stack trace ---
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
-->
```

Further technical details
ASP.NET Core version - 5.0
Include the output of dotnet --info
The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by wfurt** [comment]
Do you have packet captures @sanchhoker? 
Probably dup of #47117 and  #45244. 
Check the linked issues for possible solution.

**Comment by sanchhoker** [comment]
Yep I tried  below options from the above links and few other related issues I could find but haven't been able to get it working so far. Also I am using Ubuntu 20.04.
1) lowering seclevel to 1
2) lowering TLS protocol from 1.2 to 1
3) Adding ciphersuites

**Comment by wfurt** [comment]
Do you see difference in the handshake? It is crucial to see 1) what cipher suite was negotiated before and 2) what is being offered with 5.0 and 3) how impactful are changes you are trying. 
(note that the config is _very_ sensitive to ordering and it is not directly visible)

**Comment by sanchhoker** [comment]
server is running as a container , using 5.7.22 mysql image.
How exactly can I retrieve the cipher used with 3.0 ? since config file doesn’t contain any.

**Comment by sanchhoker** [comment]
Is there a setting that we can tweak for .net 5 to basically ignore/do not process config again?

**Comment by wfurt** [comment]
Try this @sanchhoker 
```
CipherString = @SECLEVEL=1:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256
```
It adds the `DHE-RSA-AES128-GCM-SHA256` to the handshake on my Ubuntu 20.04 box

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/14356188/139967769-319ca549-b1a7-4850-b5be-1e22f55ebff2.png">

You can add more as you see fit but it should offer the cipher you listed.

**Comment by karelz** [comment]
Triage: Looks like it is configuration that has to happen on Ubuntu 20.04 (by design regression in .NET 6.0 - also documented -- part of using only strong cipher suites). There is not much .NET can do here. Closing.

If you disagree or if we missed anything, feel free to reopen.
