### ISSUE TITLE
Update Microsoft.Signed.WiX to 1.0.0-v3.14.0.5722

### ISSUE THREAD

**Issue by joeloff** [dotnet/runtime#60003]
Updated WiX build that contains changes to better support x64 emulation on arm64. This is needed for 6.0.

**Comment by joeloff** [comment]
FYI @lewing

**Comment by lewing** [comment]
@joeloff should we bump emsdk as well?

**Comment by joeloff** [comment]
Yes, sorry, I forgot to mention that. We are going to have to go through the pain of getting everything in sync. I filed issues against runtime, arcade, aspnetcore and installer repos. I'll ping maui offline about this change too

**Comment by ericstj** [comment]
This change is needed in main.  I think https://github.com/dotnet/runtime/pull/59500 should get this change.  @lewing can you take care of that since you have the PR?

**Comment by deeprobin** [comment]
> This change is needed in main. I think #59500 should get this change. @lewing can you take care of that since you have the PR?

The PR was merged. Can we close this?
