### ISSUE TITLE
Can't download .NET 5 SDK 5.0.401 x86 binaries

### ISSUE THREAD

**Issue by FramnkRulez** [dotnet/runtime#60011]
Using the link to download the .NET 5 SDK 5.0.401 binaries for x86 (not installer) results in:

HTTP Error 503. The service is unavailable.

**Comment by NikolaMilosavljevic** [comment]
@FramnkRulez can you share the actual link you used?

cc @rbhanda

**Comment by FramnkRulez** [comment]
It appears to have been corrected as of this afternoon.  Closing
