### ISSUE TITLE
Enable custom converter tests in src-gen mode

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#60020]
When incompatible types are specified as converters for a type or property in src-gen mode, the serializer falls back to the use of a built-in converter rather than throwing an appropriate design-time or runtime error.

To ensure correct and consistent semantics between src-gen and reflection serializers, the [full set](https://github.com/dotnet/runtime/tree/ec15b53daa184583ef978dfd59e30ca4791e9470/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/CustomConverterTests) of converter tests should be enabled in src-gen mode, with appropriate fixes for any bugs discovered.

**Comment by eiriktsarpalis** [comment]
Moving to the .NET 8 milestone.

**Comment by eiriktsarpalis** [comment]
Fix in .NET 8
