### ISSUE TITLE
SSL_CERT_DIR/SSL_CERT_FILE with move over to Apple's libraries

### ISSUE THREAD

**Issue by ritchxu** [dotnet/runtime#60030]
👋🏼  Hi, since both issues no longer allows commenting, here is a follow-up question for them.

From my understanding of https://github.com/dotnet/runtime/issues/23666, for a dotnet core application, I could use `SSL_CERT_DIR/SSL_CERT_FILE` environment variables to specify a custom root certificate.

But https://github.com/dotnet/runtime/issues/17597 seems to move away that support by migrating from OpenSSL to Apple's security framework libraries.

Is `SSL_CERT_DIR/SSL_CERT_FILE` still supported on macOS then?

#### More context
We have a dotnet application running on macOS Big Sur behind a SSL terminating proxy. Even by setting `SSL_CERT_DIR/SSL_CERT_FILE` the application still doesn't trust the certificate.

One way that used to work is removed with macOS Big Sur 11.0.1 https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes#Security so we can't mark cert as trusted via command line, while GUI isn't a viable solution either.

cc @bartonjs @tmds 🙇🏼‍♂️

**Comment by bartonjs** [comment]
> Is SSL_CERT_DIR/SSL_CERT_FILE still supported on macOS then?

No, that's just "do what OpenSSL utilities do when using OpenSSL".  On macOS you have to make Security.framework happy.

One option is to load the trust store yourself and use X509Chain in CustomRootTrust mode.

**Comment by bartonjs** [comment]
Since it's been more than 3 months with no followup, I assume the question is answered satisfactorily.
