### ISSUE TITLE
Test failure: Assert failure: Verify_TypeLayout 'System.Numerics.Vector`1' failed to verify type layout

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#60036]
`runtime-coreclr outerloop` pipeline is failing on windows/Linux arm64 due to this assert.

https://dev.azure.com/dnceng/public/_build/results?buildId=1397053&view=ms.vss-test-web.build-test-results-tab

e.g.,
```
    Interop\PInvoke\Generics\GenericsTest\GenericsTest.cmd [FAIL]
      Could Not Find D:\h\w\B3A40985\w\A28E0905\e\Interop\PInvoke\Generics\GenericsTest\IL-CG2\composite-r2r.dll
      Could Not Find D:\h\w\B3A40985\w\A28E0905\e\Interop\PInvoke\Generics\GenericsTest\GenericsNative.dll.rsp
      Could Not Find D:\h\w\B3A40985\w\A28E0905\e\Interop\PInvoke\Generics\GenericsTest\GenericsTest.dll.rsp
      Could Not Find D:\h\w\B3A40985\w\A28E0905\e\Interop\PInvoke\Generics\GenericsTest\TestLibrary.dll.rsp
      
      Assert failure(PID 11376 [0x00002c70], Thread: 12804 [0x3204]): Verify_TypeLayout 'System.Numerics.Vector`1' failed to verify type layout
      
      CORECLR! LoadDynamicInfoEntry + 0xBF4 (0x00007ff9`1dac170c)
      CORECLR! Module::FixupNativeEntry + 0x6C (0x00007ff9`1da4ddec)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x200 (0x00007ff9`1db64c58)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007ff9`1db65b9c)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007ff9`1db0fe78)
      CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007ff9`1db0fc90)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x230 (0x00007ff9`1db11b50)
      CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007ff9`1db11914)
      CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x280 (0x00007ff9`1da70ee0)
      CORECLR! MethodDesc::DoPrestub + 0x764 (0x00007ff9`1db0de2c)
          File: D:\workspace\_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 13647
          Image: D:\h\w\B3A40985\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      D:\h\w\B3A40985\w\A28E0905\uploads\Reports\Interop.PInvoke\Generics\GenericsTest\GenericsTest.output.txt
```

@dotnet/crossgen-contrib

**Comment by BruceForstall** [comment]
@tannergooding Any chance https://github.com/dotnet/runtime/pull/53450 could be causing this?

**Comment by trylek** [comment]
I was actually looking at the bug earlier today. It indeed seems specific to arm64, I must admit I don't yet fully understand the extent of Tanner's change but I suspect it most likely just exposes a previously unseen type layout corner case we're still not getting right in Crossgen2. I have revived my work from earlier this year regarding cleanup of the CoreCLR type layout algorithms, I'll investigate this issue as part of that task.

**Comment by trylek** [comment]
As a short-term mitigation I'll put up a PR blocking the test out with this issue.

**Comment by tannergooding** [comment]
@BruceForstall, its certainly possible.

However, the change was largely just a refactoring so the existing `simd.cpp` and `simdashwintrinsic.cpp` logic could be shared between `System.Runtime.Intrinsics` and `System.Numerics` types; so I'd lean towards what Tomas was suggesting that there may have been an existing bug here.

Let me know if there's anything I can do to help with the investigation.

**Comment by mangod9** [comment]
this is marked as blocking-outerloop, perhaps since the test is disabled? Another type layout issue which needs to be looked at?
