### ISSUE TITLE
Single-file publishing should be deterministic

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#60041]
We should also have tests that verify if you rebundle a single-file app with the same parameters, the result is bit-for-bit identical.

**Comment by agocke** [comment]
@dylan-smith Did you try with .NET 6? I just tried this myself for a simple app and it appeared to work. Obviously, I can't declare the feature supported until it's well-tested, but it may be functional for your purposes in 6.0.

**Comment by vitek-karas** [comment]
This should be fixed in 6.0 with this change https://github.com/dotnet/runtime/pull/52930.
Note that you should be able to use 6.0 SDK with the deterministic behavior to produce 5.0 single file application, so that could be a way around the limitation in the 5.0 SDK>

**Comment by agocke** [comment]
Ah, forgot we did this! Yes https://github.com/dotnet/runtime/pull/52930 should fix this issue.
