### ISSUE TITLE
GetNativeVariantForObject tests are missing cases

### ISSUE THREAD

**Issue by tmat** [dotnet/runtime#6004]
https://github.com/dotnet/coreclr/blob/a85c2686820fa9f79dc5b40e975dcb0e59367a52/tests/src/Interop/MarshalAPI/GetNativeVariantForObject/GetNativeVariantForObject.cs is missing some test cases (actually I'd say it's missing a lot of test cases). At least marshalling of strings that contain NUL characters should be explicitly tested.

**Comment by AaronRobinsonMSFT** [comment]
Substantial coverage was added by @hughbe for the `GetNativeVariantForObject` API in the src/libraries directory.
