### ISSUE TITLE
libmsquic not on Debian 11 package repository?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#60104]
We had trouble adding libmsquic for the aspnet dockerfile.

A workaround was required:

```
# Install libmsquic dependencies
RUN apt update \
    && apt install -y --no-install-recommends \
        curl \
        wget \
        gnupg2 \
        software-properties-common

RUN curl -O https://packages.microsoft.com/debian/10/prod/pool/main/libm/libmsquic/libmsquic-1.5.0-amd64.deb
RUN dpkg -i libmsquic-1.5.0-amd64.deb
```

https://github.com/sebastienros/dotnet-http3/blob/main/Dockerfile

Was the package not correctly published everywhere?

@sebastienros @wfurt

**Comment by wfurt** [comment]
THis is very old package as the process of updating is still manual and we don't have _any_ entry for Debian 11 (and some other newer distributions as well) on https://packages.microsoft.com/debian/

We should publish new version before RC2 ships. (from release/6.0 branch) 
cc: @leecow

**Comment by JamesNK** [comment]
What do you mean by it is a very old package? Isn't libmsquic what we want people to install?

By the way, could you take a look at these instructions for Linux:

https://github.com/dotnet/AspNetCore.Docs/pull/23476

**Comment by wfurt** [comment]
this should be no fixed. closing.
