### ISSUE TITLE
`Console.ReadKey` returns incomplete VT sequences for bracketed paste

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#60101]
The [Bracketed Paste Mode](https://cirw.in/blog/bracketed-paste) can be enabled by writing `\e[?2004h` to STDOUT on a terminal that supports the mode. When pasting text with the Bracketed Paste Mode turned on, the terminal will wrap the copied text by the start sequences `\e[200~` and the end sequences `\e[201~`.

Today, `Console.ReadKey` returns a set of VT sequences for the start/end of bracketed paste.
As is shown in the below screenshot, when pasting the letter `C` in WSL 2 with Windows Terminal (either by <kbd>Ctrl+Shift-v</kbd> or right-clicking), `Console.ReadKey` returns `"\e200~C\e201~"`. It's essentially the expected start/end sequences for bracketed paste, but `[` is missing from both.

Question 1: Is it a bug that `[` is missed from the VT sequences returned by `Console.ReadKey`?
Question 2: Is the current behavior of `Console.ReadKey` regarding Bracketed Paste Mode supposed to be reliable or it just happens to work this way? Can an application depend on today's behavior to handle bracketed paste (e.g. powershell)?

Related PowerShell issue: https://github.com/PowerShell/PSReadLine/issues/1471

![image](https://user-images.githubusercontent.com/127450/136292868-79016cb6-b2aa-484b-b158-074e517a9245.png)

**Comment by jeffhandley** [comment]
@adamsitnik Another scenario worth re-testing with #802

**Comment by adamsitnik** [comment]
Fixed by #72193

**Comment by daxian-dbw** [comment]
Quote from https://github.com/dotnet/runtime/pull/73257#issuecomment-1211090508:

>> We want the tags to be preserved by ReadKey instead of being stripped off.

>
>Thanks for the confirmation! In such a case this issue has been fixed with https://github.com/dotnet/runtime/pull/73257 and the missing `[` chars should be back now.
