### ISSUE TITLE
Code Cleanup: Remove OSX 10.14 compatibility code

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#60138]
10.14 looks to have hit implicit End of Life, since it has gone two months without a security update.

Assuming that .NET 7 changes the minimum macOS to 10.15, we can remove 10.14-specific compat code, like

https://github.com/dotnet/runtime/blob/bcfa532e4c6d79f0dc636c22db868ff0edf59fcc/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.macOS.cs#L76-L93

There may be other code that can be removed.

**Comment by bartonjs** [comment]
True, true.  But of the two things I've linked in so far, I think they're both "macOS-only"... i.e. Mojave's ECC size was changed to align with the size reported on iOS; and iOS only has the data keys, not the keychain keys, so there's no legacy import for that (and the file is in a "we're different between macOS and iOS here", anyways)

**Comment by vcsjones** [comment]
Everything else I can identify requires bumping the minimum iOS version to 11, while Maui still supports iOS 10.

* RSA+PSS provided by the platform, instead of us doing the padding manually.
    https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/native/libs/System.Security.Cryptography.Native.Apple/pal_signverify.c#L126-L127
* Removing some ALPN linking workarounds
    https://github.com/dotnet/runtime/blob/9212310d20689b3ac7213569719b0f50a2274f5a/src/native/libs/System.Security.Cryptography.Native.Apple/pal_ssl.c#L8-L10

**Comment by vcsjones** [comment]
I think we can close this out. All identified places have been cleaned up, even the iOS 10 ones since we bumped out iOS minimum to iOS 11. We can open new issues if we identify more opportunities to remove legacy code.
