### ISSUE TITLE
CI failure in the test System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#60147]
### Description

Sorry if this is reported before but I couldn't find it. 

https://dev.azure.com/dnceng/public/_build/results?buildId=1408804&view=logs&j=9d8498d2-c5b7-54d8-6df7-a2ce7e14e68c&t=34b459a3-e64e-5ccc-0adc-77ebca2601a8&l=76

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60140-merge-4e7f21a19bc8454287/System.IO.FileSystem.Tests/1/console.9ded26c7.log?sv=2019-07-07&se=2021-10-27T21%3A23%3A04Z&sr=c&sp=rl&sig=RgndSl%2BsYm6%2BKHG%2BoPaY29nuRCwkAjsZ04p3ZJTxQ58%3D

```
    System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex [FAIL]
      Test cancelled
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem/tests/FileStream/DeleteOnClose.cs(77,0): at System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex()
        --- End of stack trace from previous location ---
```

### Reproduction Steps

It is CI failure

### Expected behavior

System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex test succeed in CI runs

### Actual behavior

Test Failing

Runfo Tracking Issue: [System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex](https://runfo.azurewebsites.net/tracking/issue/188)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1418769](https://dev.azure.com/dnceng/public/_build/results?buildId=1418769)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60357](https://github.com/dotnet/runtime/pull/60357)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60357-merge-70b5d281dd1a487faf/System.IO.FileSystem.Tests/1/console.ef9771ef.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T20%25253A00%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5w%25252Fh6q5XUDnITyPl6PAbHFdLfSvhriyIMCijBVa0dWg%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60357-merge-70b5d281dd1a487faf/System.IO.FileSystem.Tests/5c5c4b16-2679-4f3a-88d9-580621f291c8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T20%25253A00%25253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5w%25252Fh6q5XUDnITyPl6PAbHFdLfSvhriyIMCijBVa0dWg%25253D)|
|[1418060](https://dev.azure.com/dnceng/public/_build/results?buildId=1418060)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 58434](https://github.com/dotnet/runtime/pull/58434)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58434-merge-b180212bf23a432d86/System.IO.FileSystem.Tests/1/console.d65dc212.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T16%25253A40%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DcUJAXYbygXorH7V4tK42plKMVzF5o2ol%25252Bt6dCY%25252BROkw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58434-merge-b180212bf23a432d86/System.IO.FileSystem.Tests/7bae8c49-be52-4786-9969-1b30e113d96c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T16%25253A40%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DcUJAXYbygXorH7V4tK42plKMVzF5o2ol%25252Bt6dCY%25252BROkw%25253D)|
|[1417939](https://dev.azure.com/dnceng/public/_build/results?buildId=1417939)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60075](https://github.com/dotnet/runtime/pull/60075)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60075-merge-cf542305b87f484385/System.IO.FileSystem.Tests/1/console.d6d52e7a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T15%25253A43%25253A48Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DDSf32LMyKDo4w7ftvNkkIb38ZLEPtgtZQoRYJVSbs1I%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60075-merge-cf542305b87f484385/System.IO.FileSystem.Tests/57c8cafb-cc68-4ba2-8e9d-36c7fb8c40f3.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T15%25253A43%25253A48Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DDSf32LMyKDo4w7ftvNkkIb38ZLEPtgtZQoRYJVSbs1I%25253D)|
|[1417474](https://dev.azure.com/dnceng/public/_build/results?buildId=1417474)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 57434](https://github.com/dotnet/runtime/pull/57434)|net7.0-Linux-Debug-x64-Mono_release-(Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20210714125435-dde38af|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57434-merge-af139d60a81647beb6/System.IO.FileSystem.Tests/1/console.68dbbe47.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T08%25253A44%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoM03QVMObn6muYJa2jckyfVLa1%25252Fg5%25252BROhelNPyZGKs4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57434-merge-af139d60a81647beb6/System.IO.FileSystem.Tests/40951ce3-220d-4408-921d-ca70f1bf1dcf.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-02T08%25253A44%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoM03QVMObn6muYJa2jckyfVLa1%25252Fg5%25252BROhelNPyZGKs4%25253D)|
|[1416382](https://dev.azure.com/dnceng/public/_build/results?buildId=1416382)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 58674](https://github.com/dotnet/runtime/pull/58674)|net7.0-Linux-Debug-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58674-merge-ddf8db017731402295/System.IO.FileSystem.Tests/1/console.300fee24.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-01T21%25253A49%25253A21Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DPYkNyGGbGmi5w204x%25252B3hvzCZ2wxzE9NKKUr9jLeDrHQ%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58674-merge-ddf8db017731402295/System.IO.FileSystem.Tests/6a97402d-eb85-423a-bd74-757da5079129.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-01T21%25253A49%25253A21Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DPYkNyGGbGmi5w204x%25252B3hvzCZ2wxzE9NKKUr9jLeDrHQ%25253D)|
|[1415888](https://dev.azure.com/dnceng/public/_build/results?buildId=1415888)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 58932](https://github.com/dotnet/runtime/pull/58932)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58932-merge-e69ee3d68b774d7696/System.IO.FileSystem.Tests/1/console.69c00f23.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-01T17%25253A40%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DE5vpX7eFSYgwcT7%25252BF2ViSU3P8%25252FyFYRFRWeNs6lgxI4E%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58932-merge-e69ee3d68b774d7696/System.IO.FileSystem.Tests/acf9448d-81c7-4c3b-bb2b-0bdc7a3f68b4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-01T17%25253A40%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DE5vpX7eFSYgwcT7%25252BF2ViSU3P8%25252FyFYRFRWeNs6lgxI4E%25253D)|
|[1412266](https://dev.azure.com/dnceng/public/_build/results?buildId=1412266)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 59672](https://github.com/dotnet/runtime/pull/59672)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59672-merge-b72f32f7f3ac4d8ab4/System.IO.FileSystem.Tests/1/console.559f29bb.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-30T06%25253A23%25253A01Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dk30Qx%25252Bn63PJFo5KUWQIko%25252B%25252B5h65cbXSaNGs2zz%25252B8Agk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59672-merge-b72f32f7f3ac4d8ab4/System.IO.FileSystem.Tests/25a893d9-13a3-4b96-9258-de200e0aabe4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-30T06%25253A23%25253A01Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dk30Qx%25252Bn63PJFo5KUWQIko%25252B%25252B5h65cbXSaNGs2zz%25252B8Agk%25253D)|
|[1411894](https://dev.azure.com/dnceng/public/_build/results?buildId=1411894)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60216](https://github.com/dotnet/runtime/pull/60216)|net7.0-windows-Debug-x86-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60216-merge-2fa8bed2cb1d49d380/System.IO.FileSystem.Tests/1/console.dc6e0f0d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-29T13%25253A44%25253A23Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DshlmMVjlk5FInQkPOSOd4%25252FE%25252FMbCHZs1c4HvlSxHASRM%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60216-merge-2fa8bed2cb1d49d380/System.IO.FileSystem.Tests/a42b6e55-bb23-4a85-ac75-0bc6fa783439.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-29T13%25253A44%25253A23Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DshlmMVjlk5FInQkPOSOd4%25252FE%25252FMbCHZs1c4HvlSxHASRM%25253D)|
|[1409599](https://dev.azure.com/dnceng/public/_build/results?buildId=1409599)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-23224bbdeffc4e688f/System.IO.FileSystem.Tests/1/console.2f51a334.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-28T08%25253A38%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DTY48xUcBGBHaXdLzKlqSz6rf1x%25252Fta7trX7lxY5kE7Jw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-23224bbdeffc4e688f/System.IO.FileSystem.Tests/3a8d46ac-aa18-43ef-a1dc-40c3adc2e180.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-28T08%25253A38%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DTY48xUcBGBHaXdLzKlqSz6rf1x%25252Fta7trX7lxY5kE7Jw%25253D)|
|[1408011](https://dev.azure.com/dnceng/public/_build/results?buildId=1408011)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 59930](https://github.com/dotnet/runtime/pull/59930)|net7.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59930-merge-e435818fad6d4693bc/System.IO.FileSystem.Net5Compat.Tests/1/console.1879c4dd.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-28T10%25253A27%25253A53Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D86ihpRCLMjKZjjXzRf%25252Bflb2iKRYlpaYHXtJ7J1t%25252FCJo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59930-merge-e435818fad6d4693bc/System.IO.FileSystem.Net5Compat.Tests/73e4ecc5-785a-4e64-8944-ec35204d9e1a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-28T10%25253A27%25253A53Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D86ihpRCLMjKZjjXzRf%25252Bflb2iKRYlpaYHXtJ7J1t%25252FCJo%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|4|10|10|

**Comment by carlossanlop** [comment]
The code fix in PR https://github.com/dotnet/runtime/pull/55327 was intended for Unix specifically. The unit test is brand new, and it should be limited to only Unix platforms. @tmds, correct me if I'm wrong, but is the test supposed to run and pass on Windows as well?

To help unblock, I'll submit a PR to limit the test to run only on Unix.  @tmds if the test is supposed to run on Windows too, please let me know, and we can discuss the appropriate code fix.

cc @adamsitnik @Jozkee

**Comment by danmoseley** [comment]
Time taken is mostly relevant for local test runs. If a test takes a couple mins in the cloud it’s not noticeable. Perhaps this is a case where the test is normally fast but we run it so often in the cloud that we will cover the distribution. If that’s the problem then just increasing the timeout is normally what we do.
