### ISSUE TITLE
Ship runtime using DllImportGenerator

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#60212]
### Issues to address after the initial merge (https://github.com/dotnet/runtime/pull/59579):

- [x] #61062
  - Some arguments converted to pointers for fully blittable signatures, but some left as `out`/`ref` and relying on source generation - make sure related functions have consistent arguments
- [x] #60596
  - Detect blittable signatures and generate `partial extern` p/invokes
- [x] Use `GeneratedDllImport` for p/invokes in runtime with blittable signatures
  - [x] Update analyzer to also flag blittable signatures as candidates for conversion to `GeneratedDllImport`
  - [x] Remove the mix of `DllImport` and `GeneratedDllImport` and the need to think about which to use based on blittability
    - https://github.com/dotnet/runtime/pull/61532
    - https://github.com/dotnet/runtime/pull/61638
    - https://github.com/dotnet/runtime/pull/61996
- [x] #60662
  - Allow each marshaller to specify its support
  - Fall back to generating `partial extern` p/invoke if target version is less than required
- [x] Enable `DllImportGenerator` by default for all source projects instead of just NETCoreApp (closer to an in-box generator experience) and convert to `GeneratedDllImport`
     - https://github.com/dotnet/runtime/pull/61704
     - https://github.com/dotnet/runtime/pull/61184
     - https://github.com/dotnet/runtime/pull/61389
     - https://github.com/dotnet/runtime/pull/61476
     - https://github.com/dotnet/runtime/pull/61609
     - https://github.com/dotnet/runtime/pull/61640
     - https://github.com/dotnet/runtime/pull/61741
     - https://github.com/dotnet/runtime/pull/61742
     - https://github.com/dotnet/runtime/pull/61805
     - https://github.com/dotnet/runtime/pull/61949
     - https://github.com/dotnet/runtime/pull/61975
     - https://github.com/dotnet/runtime/pull/61990
- [x] #61134
- [x] #60698
- [x] https://github.com/dotnet/runtime/issues/59823
- [x] Update struct marshalling logic based on updated design &ndash; https://github.com/dotnet/runtime/pull/60374
  - https://github.com/dotnet/runtime/pull/63316
- [x] Update interop guidelines doc in repo to describe source generator usage
  - `System.Memory` and `System.Runtime.CompilerServices.Unsafe` for array marshalling
  - https://github.com/dotnet/runtime/pull/63350
- [x] #60605
  - Add infrastructure to zip live ref assemblies, send to Helix, unzip, and resolve against in source generator unit tests

### Runtime issues discovered by DllImportGenerator
- https://github.com/dotnet/runtime/issues/60271
- https://github.com/dotnet/runtime/issues/60624
- https://github.com/dotnet/runtime/issues/60648
- https://github.com/dotnet/runtime/issues/60649
- https://github.com/dotnet/runtime/issues/60650
- https://github.com/dotnet/runtime/issues/60705
- https://github.com/dotnet/runtime/issues/60819

cc @AaronRobinsonMSFT @jkoritzinsky

**Comment by jkotas** [comment]
> Allow each marshaller to specify its support

Can this be done by checking availability of the APIs required by the given marshaller?

**Comment by elinor-fung** [comment]
Remaining work - including `DisableRuntimeMarshalling` for blittable/unmanaged reconciliation - is being tracked in https://github.com/dotnet/runtime/issues/60595.

This is the drop in generated IL stubs on launch of some template applications after the use of DllImportGenerator in runtime libraries (most remaining stubs in the frameworks):

| Template | 6.0 | 7.0 |
| -------- | --: | --: |
| console  |   2 |   0 |
| webapp   |  55 |  18 |
| winforms |  65 |  55 |
| wpf      | 129 | 123 |
