### ISSUE TITLE
Test failure System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60240]
Run: [runtime-coreclr libraries-jitstressregs 20211010.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1412342&view=ms.vss-test-web.build-test-results-tab&runId=40943150&resultId=114776&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

category:correctness
theme:testing
skill-level:intermediate
cost:medium
impact:small

**Comment by carlossanlop** [comment]
@dotnet/jit-contrib can anyone here help us investigate this issue?

The ConsoleKeyInfo has not been change for months.

This JIT test leg seems to be running once a week. This console test passes 47 times, and fails once, on Windows 10 amd64, with CoreCLR x86. https://dev.azure.com/dnceng/public/_test/analytics?definitionId=668&contextType=build

The test is comparing ConsoleKeyInfo instances. The `.Equals()` methods pass, but the `==` comparison fails.

Test log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5a8e57a8f2b14ffe9b/System.Console.Tests/1/console.dd29db9d.log?sv=2019-07-07&se=2021-10-30T09%3A32%3A44Z&sr=c&sp=rl&sig=CwCNOuPBFlwnNhP8FR4dwL0nJ7DVi5MHgRJFaJnOJTs%3D

Here's the code that fails:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs#L40-L42

ConsoleKeyInfo is a readonly struct: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Console/src/System/ConsoleKeyInfo.cs#L8

**Comment by JulieLeeMSFT** [comment]
@EgorBo PTAL.
cc @dotnet/jit-contrib

**Comment by VincentBu** [comment]
Failed again in:[ runtime-coreclr libraries-jitstressregs 20211107.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1458200&view=ms.vss-test-web.build-test-results-tab&runId=41917350&paneView=debug&resultId=108280)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20211121.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1479927&view=ms.vss-test-web.build-test-results-tab&runId=42379366&paneView=debug&resultId=113975)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

**Comment by VincentBu** [comment]
Failed again in:[ runtime-coreclr libraries-jitstressregs 20211205.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1497655&view=ms.vss-test-web.build-test-results-tab&runId=42733484&resultId=115915&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20211219.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1520241&view=ms.vss-test-web.build-test-results-tab&runId=43217636&resultId=107172&paneView=debug)

Failed test:
```

net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstressregs 20220102.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1531809&view=ms.vss-test-web.build-test-results-tab&runId=43419196&resultId=110586&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstressregs1-Windows.10.Amd64.Open

- System.Tests.ConsoleKeyInfoTests.Equals_SameData(cki: System.ConsoleKeyInfo)

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Tests.ConsoleKeyInfoTests.Equals_SameData(ConsoleKeyInfo cki) in /_/src/libraries/System.Console/tests/ConsoleKeyInfoTests.cs:line 42
```

**Comment by EgorBo** [comment]
I wasn't able to reproduce this, but I'll try again on Monday once I am home and backport to 7.0 if it turns out to be important/gc hole

**Comment by EgorBo** [comment]
Doesn't repro no matter what, I'll file a PR to re-enable this test
