### ISSUE TITLE
dotnet publish fails when RunAOTCompilation is set to true

### ISSUE THREAD

**Issue by veertien** [dotnet/runtime#60274]
### Describe the bug

In my docker container, the `dotnet publish` command fails here:

```text
...
dotnet/sdk#19 22.00   [29/29] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
dotnet/sdk#19 22.07 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/6.0.0-rc.1.21451.13/Sdk/WasmApp.Native.targets(394,5): error MSB3073: The command "emcc --version" exited with code 1. [/src/Client/example1.Client.csproj]
------
executor failed running [/bin/sh -c dotnet publish "example1.Server.csproj" -c Release -o /app/publish]: exit code: 1
C:\git\example1>
```

### To Reproduce

Create blazor wasm project with 

```
dotnet new blazorwasm --hosted 
```

* Add a Dockerfile with the dotnet 6 sdk
    * Install the wasm-tools workload 

* Update the Client project file to include:

```xml
  <RunAOTCompilation>true</RunAOTCompilation>
```

build the image

See this repo: https://github.com/veertien/example-blazor-aot

### Exceptions (if any)

```
error MSB3073: The command "emcc --version" exited with code 1. 
```

### Further technical details

```
docker run mcr.microsoft.com/dotnet/sdk:6.0 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100-rc.1.21458.32/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  6.0.100-rc.1.21458.32 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by pranavkm** [comment]
FYI @radical

**Comment by radical** [comment]
@veertien Could you please share the binlog? Run the build with `-bl` adding to the command line, and attach the generated `msbuild.binlog`.

**Comment by radical** [comment]
> ```
> emcc --version (TaskId:476)
> unable to find python in $PATH (TaskId:476)
> ```
> 
> Python is not installed, or not available in `$PATH`.

Installing python, and making sure that it is in `PATH` should fix this issue. Please re-open, if it doesn't.

Closing this based on the above, and opened an issue for surfacing the errors to the user - https://github.com/dotnet/runtime/issues/61067 .
