### ISSUE TITLE
System.Text.JSon Source Generator Diagnostic in the error list doesnt link me to docs or navigate me to the file where the issue is

### ISSUE THREAD

**Issue by mikadumont** [dotnet/runtime#60314]
### Description

I am using the System.Text.JSon Source Generator and am getting the following warning in my error list: 

![image](https://user-images.githubusercontent.com/46729679/137031242-ee568aca-522f-4075-9f43-3d3dcad86075.png)

This analyzer doesn't follow the analyzer guidelines for it doesnt navigate me to the file where the issue is or link me to docs to understand the issue better. Also should the severity be a warning or a suggestion? Anything that will be a warning or error should go through an analyzer review but let me know your thoughts. @jeffhandley @layomia 

### Reproduction Steps

I am on Version 17.0.0 Preview 5.0 [31807.358.d17.0]

I am using the following code: 

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SolarSystem;

internal record Astronomer(string FirstName, string LastName, string? MiddleName = null);

[JsonSerializable(typeof(Astronomer))]
internal partial class AstronomerJsonContext : JsonSerializerContext
{
}

class Program
{
    static void Main(string[] args)
    {
        var astronomer = new Astronomer(FirstName: "Jane", LastName: "Doe");

        string json = JsonSerializer.Serialize(astronomer, AstronomerJsonContext.Default.Astronomer);
    }
}
```
And I get the following warning in my error list but clicking on the warning doesnt navigate me to where the warning is coming from. Also the analyzer ID link doenst link me to docs. 

![image](https://user-images.githubusercontent.com/46729679/137031242-ee568aca-522f-4075-9f43-3d3dcad86075.png)

### Expected behavior

I am using the following code: 

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SolarSystem;

internal record Astronomer(string FirstName, string LastName, string? MiddleName = null);

[JsonSerializable(typeof(Astronomer))]
internal partial class AstronomerJsonContext : JsonSerializerContext
{
}

class Program
{
    static void Main(string[] args)
    {
        var astronomer = new Astronomer(FirstName: "Jane", LastName: "Doe");

        string json = JsonSerializer.Serialize(astronomer, AstronomerJsonContext.Default.Astronomer);
    }
}
```
And I get the following warning in my error list but clicking on the warning doesnt navigate me to where the warning is coming from. Also the analyzer ID link doenst link me to docs. 

![image](https://user-images.githubusercontent.com/46729679/137031242-ee568aca-522f-4075-9f43-3d3dcad86075.png)

I would expect clicking on the warning in the error list will navigate me to where the warning is and the clicking on the ID link will take me to docs to understand what the warning is.

### Actual behavior

I am using the following code: 

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SolarSystem;

internal record Astronomer(string FirstName, string LastName, string? MiddleName = null);

[JsonSerializable(typeof(Astronomer))]
internal partial class AstronomerJsonContext : JsonSerializerContext
{
}

class Program
{
    static void Main(string[] args)
    {
        var astronomer = new Astronomer(FirstName: "Jane", LastName: "Doe");

        string json = JsonSerializer.Serialize(astronomer, AstronomerJsonContext.Default.Astronomer);
    }
}
```
And I get the following warning in my error list but clicking on the warning doesnt navigate me to where the warning is coming from. Also the analyzer ID link doenst link me to docs. 

![image](https://user-images.githubusercontent.com/46729679/137031242-ee568aca-522f-4075-9f43-3d3dcad86075.png)

**Comment by eiriktsarpalis** [comment]
I've noticed this as well. Not certain why but I suspect it's because we're [hardcoding all diagnostics to `Location.None`](https://github.com/dotnet/runtime/blob/845e66cd08240dc77bce98f40cecaaa0f0dadc65/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L975). We would probably need to pass one of the values stored in the underlying [`ISymbol.Locations` property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isymbol.locations?view=roslyn-dotnet-3.11.0).

@layomia @ericstj should we consider addressing this for 6.0?

**Comment by ericstj** [comment]
> Anything that will be a warning or error should go through an analyzer review but let me know your thoughts. @jeffhandley @layomia

I believe these diagnostics did go through API review, but perhaps there is a gap here in the process.  cc @terrajobst as well.

> should we consider addressing this for 6.0?

It's a good bug to fix, but it's not blocking.  My inclination would be to fix in 7.0, but I don't have a great feel for what the tooling bug bar is around this sort of thing.  @mikadumont @mavasani @sharwell what we do if this bug were present in an roslyn-analyzers?  Would you take a fix in ask-mode or just fix in the next release?

> the analyzer ID link doesn't link me to docs.

We should be able to fix this.  @layomia do we have the right documentation for our added diagnostics?

**Comment by layomia** [comment]
For now I'll consider this a 7.0 issue (early fix) - I'll create PRs providing the right location for the diagnostics we emit, and also prioritize providing corresponding documentation.

**Comment by eiriktsarpalis** [comment]
@terrajobst you mean it should be serviced for 6?

**Comment by terrajobst** [comment]
I'd think it would make the bar for SDK versioning, yes.

**Comment by layomia** [comment]
> I would recommend a holistic review of the diagnostics that can be generated from the Json source generator feature, illustrating the IDs, locations, messages, severity levels, and URLs that are rendered. From that, changes could be made into 7.0 and considered for backporting into 6.0.x.

Currently working on putting these artifacts together for review (mostly code changes to return the correct locations).
