### ISSUE TITLE
Assertion failed 'child->isContained()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#60330]
Linux x64 with various JitStressRegs modes fails with:

```
Assert failure(PID 27796 [0x00006c94], Thread: 27810 [0x6ca2]): Assertion failed 'child->isContained()' in 'System.Numerics.Tests.Vector4Tests:Vector4ZeroTest():this' during 'Linear scan register alloc' (IL size 39)

    File: /__w/2/s/src/coreclr/jit/lsraxarch.cpp Line: 490
    Image: /datadisks/disk1/work/AE07095B/p/dotnet
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1412342&view=ms.vss-test-web.build-test-results-tab&runId=40943234&resultId=183443&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

@kunalspathak @dotnet/jit-contrib

**Comment by kunalspathak** [comment]
I will take a look.

**Comment by kunalspathak** [comment]
This was introduced in https://github.com/dotnet/runtime/pull/55875 where we started substituting the parameter less HWIntrinsic nodes like `Vector128/Vector256.get_Zero` during inlining.

**Comment by kunalspathak** [comment]
@BruceForstall - I searched for `Vector3ZeroTest` method in `libraries_tests.mch` but I couldn't find it which means we are not collecting SPMI for it...any possible reason? I saw the logs and we do copy `System.Numerics.Vectors.Test.dll` that contains this method.

**Comment by kunalspathak** [comment]
@EgorBo - can you take a look?

**Comment by BruceForstall** [comment]
> @BruceForstall - I searched for `Vector3ZeroTest` method in `libraries_tests.mch` but I couldn't find it which means we are not collecting SPMI for it...any possible reason? I saw the logs and we do copy `System.Numerics.Vectors.Test.dll` that contains this method.

Don't know. If the IL matches another test, we'll drop it during de-duplication. Or, if PMI fails for some reason or the JIT fails during PMI, it won't be included. Actually, I'm not sure how well PMI handles Vector cases; maybe that's it?

**Comment by kunalspathak** [comment]
> maybe that's it?

I do see other methods from that class, so not sure if that is the case.

**Comment by EgorBo** [comment]
> @EgorBo - can you take a look?

Sure, thanks for the investigation!
