### ISSUE TITLE
Microsoft.Windows.Compatibility should reference the latest System.Data.SqlClient

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#60345]
System.Data.SqlClient got a servicing release last month to bump its latest version to `4.8.3`. However, Microsoft.Windows.Compatibility still references the old version `4.8.2`.

We should update Microsoft.Windows.Compatibility to the latest version. That way customers who use the `6.0.0` compat pack will get the latest servicing fixes.

While we are at it - we should ensure we are using the latest versions of all our dependencies in the compat pack.

cc @safern @Anipik @ericstj

**Comment by ViktorHofer** [comment]
> While we are at it - we should ensure we are using the latest versions of all our dependencies in the compat pack.

What I mentioned in the past is that it would interesting to see if we could leverage tools like dependabot which analyzes publicly released dependencies only (essentially ones which are available on nuget.org).

**Comment by safern** [comment]
I assigned this to myself as we will need to update the compat pack to the latest WCF version right before the release when they have a GA package in the transport feeds, so I can take care of these 2 versions together. 

I doubled check if there was any version we needed to update and there is not.

**Comment by ViktorHofer** [comment]
Closing as the compat pack already references the latest available System.Data.SqlClient package: https://github.com/dotnet/runtime/blob/e3860440c151897968eca2227ae98c1912580c44/eng/Versions.props#L97.

In case we want to discuss adding dependabot integration (other repos like aspnetcore and msbuild do that), let's have that in a separate issue.
