### ISSUE TITLE
RuntimeIdentifierTests.VerifyOSRid started failing on macOS ARM64

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#60341]
Example on runtime-staging: https://dev.azure.com/dnceng/public/_build/results?buildId=1410047&view=ms.vss-test-web.build-test-results-tab&runId=40895764&resultId=162151&paneView=debug

```
Assert.EndsWith() Failure:
Expected:    Arm64
Actual:   ···.11.6
```

The test debug logging prints:
```
### OS: Distro=OSX Version=11.6.0 Description=Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 Version=Unix 11.6.0 Arch=Arm64 Rid=osx.11.6
```

... so it thinks the RID is `osx.11.6` which indeed looks incorrect.

If I'm reading the AzDO logs correctly it started with https://github.com/dotnet/runtime/commit/04f70d6fc56a5261b0dcad0e6217fcbf92570aaf which brought in a new version of Microsoft.NETCore.DotNetHost.

I'm suspecting https://github.com/dotnet/runtime/pull/59066 since it touched that code and was merged near that timeframe.

/cc @wfurt @agocke @vitek-karas

**Comment by wfurt** [comment]
got repro, working on fix.
