### ISSUE TITLE
Enum.GetName returns wrong name of enum value.

### ISSUE THREAD

**Issue by heikkiri** [dotnet/runtime#60346]
If you declare an enum like follows:

    public enum MyType
    {
        Bool,
        Boolean = Bool,
        Date,
        DateTime = Date,
        Decimal,
        Dynamic,
        Guid,
        Int,
        Long,
        Real,
        Double = Real,
        String,
        Time,
        TimeSpan = Time
    }

The expectation is that the name returned for MyType.Double is real, same as Boolean returns Bool and DateTime returns Date.

The type is persisted correctly.

Enum.GetNames(typeof(MyType))
{string[14]}
    [0]: "Bool"
    [1]: "Boolean"
    [2]: "Date"
    [3]: "DateTime"
    [4]: "Decimal"
    [5]: "Dynamic"
    [6]: "Guid"
    [7]: "Int"
    [8]: "Long"
    [9]: "Real"
    [10]: "Double"
    [11]: "String"
    [12]: "Time"
    [13]: "TimeSpan"

But if I run following code Double, AND Real are returned as 'Double' not as Real. But Boolean and DateTime names are handled expected.

Enum.GetValues(typeof(MyType))
{Kusto.Data.MyType[14]}
    [0]: Bool
    [1]: Bool
    [2]: Date
    [3]: Date
    [4]: Decimal
    [5]: Dynamic
    [6]: Guid
    [7]: Int
    [8]: Long
    **[9]: Double
    [10]: Double**
    [11]: String
    [12]: Time
    [13]: Time

This is with .NET 5.0. I would expect the value to be 'Real' and NOT Double just like for Boolean or DateTime fields.

**Comment by danmoseley** [comment]
@heikkiri shall we close this?

**Comment by tannergooding** [comment]
Closing as there has been no additional feedback from the author.

This behavior was already returning the "wrong" value in certain scenarios and is explicitly spec'd/documented to be the case as there is no way to unambiguously return the "correct" name from the raw value for aliased enum members.
