### ISSUE TITLE
[mono] Crash in github runner due to null AssemblyLoadContext.GetLoadContext result

### ISSUE THREAD

**Issue by uweigand** [dotnet/runtime#60348]
### Description

Attempting to run the GitHub action runner on linux-s390x (using the Mono runtime) crashes on startup.

### Reproduction Steps

Building the code base from here: `https://github.com/actions/runner` and starting the `Runner.Worker` binary.

### Expected behavior

Program starts up without crashing.

### Actual behavior

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at GitHub.Runner.Common.HostContext..ctor(String hostType, String logFile) in /home/uweigand/runner/src/Runner.Common/HostContext.cs:line 82
   at GitHub.Runner.Worker.Program.Main(String[] args) in /home/uweigand/runner/src/Runner.Worker/Program.cs:line 14
```

This happens at https://github.com/actions/runner/blob/main/src/Runner.Common/HostContext.cs#L81
```
            _loadContext = AssemblyLoadContext.GetLoadContext(typeof(HostContext).GetTypeInfo().Assembly);
            _loadContext.Unloading += LoadContext_Unloading;
```
because the `GetLoadContext` call returns `null`.

### Regression?

Likely yes - this looks like another instance of the problem introduced by https://github.com/dotnet/runtime/pull/53308.  A similar case was already fixed here: https://github.com/dotnet/runtime/issues/55921.

### Known Workarounds

Add the following line before the `GetLoadContext` call to ensure the default ALC was initialized:
```
            var _ = AssemblyLoadContext.Default;
```

### Configuration

.NET RC1 rebuilt for linux-s390x (Mono runtime based).

### Other information

CC @vargaz, @lambdageek

**Comment by lambdageek** [comment]
@uweigand What if we add
```csharp
var _ = AssemblyLoadContext.Default;
```

before 

https://github.com/dotnet/runtime/blob/0cb73e898c85f83a6394142542fc9e015556d811/src/mono/System.Private.CoreLib/src/System/Runtime/Loader/AssemblyLoadContext.Mono.cs#L83

**Comment by uweigand** [comment]
Yes, this fixes the problem for me, thanks!

**Comment by uweigand** [comment]
This is now fixed everywhere.
