### ISSUE TITLE
[API Proposal]: Add String.Join(char, IEnumerable<string>)

### ISSUE THREAD

**Issue by johnthcall** [dotnet/runtime#60342]
### Background and motivation

As part of #56857 we took a minor perf degradation for joining non-string objects. Additionally there is an API string.Join(string, IEnumerable<string>) and this would provide parity for a char separator. 

### API Proposal

```C#
namespace System.Collections.Generic
{
    public partial class String
    {
        public static string Join(char separator, IEnumerable<string?> values);
    }
}
```     

### API Usage

```C#
var list = new List<string> { "Carrots", "Apples", "Bananas" }

// Join the list 
Console.WriteLine(string.Join(',', list));
```     

### Risks

My understanding is that builds against old runtimes or .net standard will continue to go through the path for string.Join<T>(char, IEnumerable<T>) so the code written as part of #56857 will need to stay in place. However when targeting the new runtime there should be a minor perf improvement.

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/c4a15decfa2ab62256a7894cb962e7bcad278414/src/libraries/System.Private.CoreLib/src/System/String.Manipulation.cs#L679

The generic version already special cases for string. The performance benefit of new api would be too little.

**Comment by tannergooding** [comment]
@johnthcall, can you provide more context as to the "minor perf degradation" measured? This is a single check/branch for `non-string T` and no more than 3 checks/branches for `string T`.

**Comment by johnthcall** [comment]
@tannergooding looking at this again, since we wouldn't be able to remove the `string T` check without causing a performance regression this can be closed as the perf gain will be minimal.
