### ISSUE TITLE
[API Proposal]: Expose method on PeriodicTimer to adjust interval 

### ISSUE THREAD

**Issue by AndrewMD5** [dotnet/runtime#60384]
EDITED by @stephentoub on 9/1/2022 to update proposal

```diff
namespace System.Threading
{
    public sealed class PeriodicTimer : System.IDisposable
    {
         public PeriodicTimer(System.TimeSpan period) { }
         public System.Threading.Tasks.ValueTask<bool> WaitForNextTickAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
         public void Dispose() { }
+	 public TimeSpan Period { get; set; }
    }
}
```     

---

### Background and motivation

After discovering the new `PeriodicTimer` class that was introduced in .NET 6 I tried to use it in a very simple implementation. 

If the period between ticks is a constant interval the class is fine. However, if you have a sliding window where the period between ticks might increase (such is the case with something like an exponential backoff) you are forced to move back to using `Task.Delay`

To provide a real-world example of this, lets say I have a remote service where a client request a temporary lease to gain access to that service. The lease contains a TTL, and it is up to the client to renew the lease before that TTL comes to pass. Upon renewal, the service returns a new TTL which may be longer or shorter depending on the clients reputation.  

It isn't possible today to use `PeriodicTimer` to create a background task that handles that renewal logic without explicitly creating a new instance or using gotos (implicit):

```csharp

// rate based on the TTL the remote service gave us.
using var timer = new PeriodicTimer(RenewalTickRate);
while (await timer.WaitForNextTickAsync(_cancellationToken)) {
 var response = await client.RenewLease(...);
 Console.WriteLine($"New Lease TTL: {response.Ttl}");
 // no way to adjust the timer to tick based on the new ttl
}
```

You _can_ accomplish this with `Task.Delay` by updating variables outside of a `while` loop, and I'm sure that is a pattern you can find in thousands of C# codebases, but then you lose out on the performance benefits `PeriodicTimer` offers. That being said, the underlying `TimerQueueTimer` that an instance of `PeriodicTimer` uses already supports changing its state, so I hope this isn't too major of a change to consider.

### API Proposal

```diff
namespace System.Threading
{
    public sealed class PeriodicTimer : System.IDisposable
    {
         public PeriodicTimer(System.TimeSpan period) { }
         public System.Threading.Tasks.ValueTask<bool> WaitForNextTickAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
         public void Dispose() { }
+	 public void Change(TimeSpan period);
    }
}
```     

### API Usage

```C#
// rate based on the TTL the remote service gave us.
using var timer = new PeriodicTimer(RenewalTickRate);
while (await timer.WaitForNextTickAsync(_cancellationToken)) {
 var response = await client.RenewLease(...);
 timer.Change(response.Ttl);
}
```     

### Risks

None I can immediately think of.

**Comment by danmoseley** [comment]
@stephentoub looks like you added this originally - #53899 - and @davidfowl you proposed it. Any concerns with this API proposal - could I mark as ready for review?

**Comment by stephentoub** [comment]
> Any concerns with this API proposal

The concept seems fine.  There are a variety of ways it could be surfaced, e.g. we might consider instead a get/set property.

**Comment by davidfowl** [comment]
Yep. This looks fine, we can go to api review.

**Comment by John0King** [comment]
why not a `TimeSpan` property ? so we can also get the period time

**Comment by ilmax** [comment]
Was thinking that it may be a nice addition to be able to create a periodic timer given a cron expression. I know that (AFAIK) there's no built in support for cron as of now, but I'm dropping this here to see what other people thinks of it

**Comment by stephentoub** [comment]
> why not a TimeSpan property ? so we can also get the period time

This is what I meant by "There are a variety of ways it could be surfaced, e.g. we might consider instead a get/set property."

> Was thinking that it may be a nice addition to be able to create a periodic timer given a cron expression

That is a very different and much more complicated feature. Please open a separate issue if it's something you're interested in. Thanks.

**Comment by Joe4evr** [comment]
> This is what I meant by "There are a variety of ways it could be surfaced, e.g. we might consider instead a get/set property."

🍝 One *possible* advantage of the property approach would be making it easy to change the period by a relative amount of time (eg. `+= TimeSpan.FromMinutes(5);`).

**Comment by angelru** [comment]
Any progress on this proposal?

**Comment by stephentoub** [comment]
> Any progress on this proposal?

It's in the queue to be reviewed.

**Comment by theodorzoulias** [comment]
What will happen if the `Period` is changed while a [`WaitForNextTickAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer.waitfornexttickasync) operation is currently active?

1. The `ValueTask<bool>` will complete immediately with the value `false`?
2. The `ValueTask<bool>` will complete after a shortened or prolonged timespan, equal to the delta of the changed `Period`?
3. The `ValueTask<bool>` will be totally unaffected from the change, and the changed `Period` will only affect the next `WaitForNextTickAsync`?

**Comment by stephentoub** [comment]
> What will happen if the Period is changed while a [WaitForNextTickAsync](https://learn.microsoft.com/en-us/dotnet/api/system.threading.periodictimer.waitfornexttickasync) operation is currently active?

It'd be "(2) The ValueTask<bool> will complete after a shortened or prolonged timespan, according to the delta of the changed Period", noting that there's of course a race condition between the timer firing in response to the current period and the new period taking effect.

**Comment by theodorzoulias** [comment]
Yep, makes sense. What about the case that the `Period` is changed after the `PeriodicTimer` is disposed of? Will it be a no-op, or an `ObjectDisposedException` will be thrown?

**Comment by stephentoub** [comment]
Presumably ODE. Why are you asking?

**Comment by theodorzoulias** [comment]
Because it is a useful API that I could make use of. Clarifying these details might make the process of approval smoother. :-)

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Threading;

public partial class PeriodicTimer
{
    public TimeSpan Period { get; set; }
}
```

**Comment by 21r8390** [comment]
@stephentoub Will this property be exposed in .NET 8 or is there a possibility to use this already in .NET 7?

**Comment by stephentoub** [comment]
Only .NET 8.
