### ISSUE TITLE
impAppendStmt sets spillGlobEffects conservatively and inconstently for block ops

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#6042]
In `impAppendStmt()`, `spillGlobEffects` is always set to true for `GT_INITBLK` and `GT_COPYBLK`, without regard to the destination. Also, it is not clear why it is not set to true for `GT_COPYOBJ` (which is also a form of assignment).

category:cq
theme:importer
skill-level:intermediate
cost:medium

**Comment by SingleAccretion** [comment]
Fixed with #73233.
