### ISSUE TITLE
ValidateInterfaceImplTable enforces bogus ordering rules

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#60454]
### Description

System.Reflection.Metadata metadata writer enforces weird rules around metadata validity for the InterfaceImpl table.

### Reproduction Steps

It's not possible to generate a module with the metadata that corresponds to the following C# program:

```csharp
interface I1
{
    void Method();
}

interface I2
{
    void Method();
}

class C1 : I1, I2
{
    public void Method() { }
}

class C2 : I2, I1
{
    public void Method() { }
}
```

### Expected behavior

It's possible to generate interface list for `I1, I2` and `I2, I1`.

### Actual behavior

InvalidOperationException is thrown out of this code because it's impossible to have the interface list sorted both ways:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataBuilder.Tables.cs#L1552-L1576

Interface index should not be looked at by this code.

**Comment by agocke** [comment]
This is the same as https://github.com/dotnet/roslyn/issues/3905, but it was incorrectly thought to be a Roslyn bug, when it is in fact a SRM and spec bug -- I think ECMA's restriction here is too strict.
