### ISSUE TITLE
[JIT]: Codegen for manual devirtualization

### ISSUE THREAD

**Issue by omariom** [dotnet/runtime#60492]
This code ([sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9BrIAW2KGIAy2YO258BG6jQDaAKV4YA4jC4zlACgwBPMTAgAZh68PACUoQC6mqQMAGJQHADm2JIA8sAAVjBgGIa8uBgAPAAqAHw0AN40DDUMYlC8CtgYMHEJyZJ5BQBCeDAlpQwA+pL5GLIY0DBWtQzVtcQAzAzFDADqjjoAsthcHCkAIjBKUBjBPAwhACYwCKHzNVXUs7NNUAyjBRNTDAC8w59xpNYDMXjUHi9eAEGB5Ad9YJdcNoQolpABJFr4LpFMoMXAo9GY+7PMEvYgAdjxBJgGJg+BYAFEeFBvABBM7XW6hUGk2oQ2YUj5jeGCJkYFns843O48hgAXxoCusypMBSg2ByTBi8SSKWxvVw/TKlQhSwYqvFGowKwYYolHIunJlipoNENKRgVy1yK4qJpmOxAwYIDaus6YwNRvK1Ces3qjWarVWIwgbjt3llpuWEAUMgaNxt6clIWtTtCf0GKbTzIzLuoQA==))..
```C#
    public T WithManualDevirt(int index)
    {
        var listStore = _listStore;
        
        if (listStore is SingleItemList<T> singleItem)
            return singleItem.EntryAt(index);
            
        return listStore.EntryAt(index);
    }
```

generates the following assembly:
```ASM
       mov rcx, [rcx+8]
       mov rax, rcx
       test rax, rax
       je short L001d
       mov r8, 0x7fff4a8ad9c0
       cmp [rax], r8
       je short L001d
       xor eax, eax
L001d: test rax, rax
       je short L0026
       mov eax, [rax+8]
       ret
L0026: mov rax, [rcx]
       mov rax, [rax+0x40]
       mov rax, [rax+0x20]
       jmp rax
```

I think it could be simpler, with less tests and jumps
```ASM
       mov rcx, [rcx+8]
       mov rax, rcx
       test rax, rax
       je short L0026
       mov r8, 0x7fff4a8ad9c0
       cmp [rax], r8
       jne short L0026
       mov eax, [rax+8]
       ret
L0026: mov rax, [rcx]
       mov rax, [rax+0x40]
       mov rax, [rax+0x20]
       jmp rax
```

sharplab is now on 5.0, but 6.0 rc2 generates the same code.

**Comment by EgorBo** [comment]
Yes, there were two solutions there: 1) In some cases our inlined castclass/isinst produces a bit suboptimal IR 2) Jump-threading optimization gives up on GT_PHI nodes currently

**Comment by EgorBo** [comment]
Thanks for reminding me this issue! But I think we can close it as dup of https://github.com/dotnet/runtime/issues/36649
