### ISSUE TITLE
blazor - Assertion at /__w/1/s/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

### ISSUE THREAD

**Issue by drma-dev** [dotnet/runtime#60512]
[https://github.com/drma-dev/BlazorCyclicalReference](https://github.com/drma-dev/BlazorCyclicalReference)

is there any way to avoid crashing when making a cyclical component call?

dynamically creating or limiting the number of call times?

**Comment by drma-dev** [comment]
a few versions ago, the error was pretty clear. but I think it stopped recognizing correctly.

**Comment by pranavkm** [comment]
> presumably that's a problem somewhere in Blazor.

It is valid for components to recursively call themselves as long as there's a terminating condition. While the error message is weird and probably something we could try and remedy, we can't do anything inside the framework to identify this scenario.

**Comment by pranavkm** [comment]
> Error: Garbage collector could not allocate 16384u bytes of memory for major heap section.

That's already pretty close to being a legitimate OOM exception message,

**Comment by radical** [comment]
The [code](https://github.com/dotnet/runtime/blob/main/src/mono/mono/sgen/sgen-memory-governor.c#L411) has a `exit(1)` after that error. So, one issue is that we don't *stop* running the app at that point.

**Comment by kg** [comment]
> > The [code](https://github.com/dotnet/runtime/blob/main/src/mono/mono/sgen/sgen-memory-governor.c?rgh-link-date=2021-10-19T20%3A24%3A04Z#L411) has a `exit(1)` after that error. So, one issue is that we don't _stop_ running the app at that point.
> 
> We had an old issue related to this - #51329 which was fixed by #53734 . But that fix also uses `exit(1)`. Maybe we need to do more stop the execution, like the comments on the issue suggest? cc @kg @lewing
> 
> Other than that, the original question has been answered, IIUC.

It wasn't clear to me why #53574 would have fixed it in the first place. Is this in the emscripten documentation somewhere?
