### ISSUE TITLE
Serializing public interface with internal implementation works with JSON but not with XML

### ISSUE THREAD

**Issue by dancojocaru2000** [dotnet/runtime#60523]
### Description

Serialization of an internal implementation of a public interface to XML doesn't work.

### Reproduction Steps

Write a public interface, implement it with an internal class, then try to serialize an instance of the class with `System.Text.Json.JsonSerializer` and with `System.Xml.Serialization.XmlSerializer`.

### Expected behavior

Both should work.

### Actual behavior

XML serialization fails with:

```
An error occurred while trying to create an XmlSerializer for the type 'InfoferScraper.Models.Train.TrainScrapeResult'.
System.InvalidOperationException: InfoferScraper.Models.Train.TrainScrapeResult is inaccessible due to its protection level. Only public types can be proce
ssed.
```

### Configuration

.NET 5

**Comment by HongGit** [comment]
System.Xml.Serialization.XmlSerializer does not support this scenario.  Please try DataContractSerializer.
