### ISSUE TITLE
Build error 'The following files are missing entries in the templated manifest'

### ISSUE THREAD

**Issue by SteveDunn** [dotnet/runtime#60526]
Getting a build error on the main branch and [was advised to file an Issue](https://discord.com/channels/732297728826277939/732582981163548703/899379705243906048):

```
Trimming win-x64 runtime pack assemblies with ILLinker...
  Trimming win-x64 OOB assemblies with ILLinker...
  externals ->
  Microsoft.NETCore.App.Runtime.Composite ->
C:\Users\steve\.nuget\packages\microsoft.dotnet.sharedframework.sdk\7.0.0-beta.21514.3\targets\sharedfx.targets(288,5): error : The following files are missing entries in the templated manifest: [C:\git\runtime-origin\runtime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Runtime.Composite.sfxproj]
C:\Users\steve\.nuget\packages\microsoft.dotnet.sharedframework.sdk\7.0.0-beta.21514.3\targets\sharedfx.targets(288,5): error : api-ms-win-core-fibers-l1-1-0.dll. Add these file names with extensions to the 'PlatformManifestFileEntry' item group for the runtime pack and corresponding ref pack to include them in the platform manifest. [C:\git\runtime-origin\runtime\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Runtime.Composite.sfxproj]
```

I've tried a `git clean -xdf` before building.  I've even pulled down a brand new repo in a new folder, but the error persists.

Any ideas?

**Comment by ericstj** [comment]
Looks like the fix for this added an entry to the manifest yet the file is missing from the product - likely the build machine didn't have it?  Also it's been raised that this is missing (but potentially needed) in 6.0.

**Comment by NikolaMilosavljevic** [comment]
> Looks like the fix for this added an entry to the manifest yet the file is missing from the product - likely the build machine didn't have it? Also it's been raised that this is missing (but potentially needed) in 6.0.

@ericstj which file is missing from the product? Is that something that file-owner controls, by binplacing to correct location? I'm trying to determine to whom to re-route this?

**Comment by NikolaMilosavljevic** [comment]
@ericstj is this file produced in Libraries build? What is the actual filename? We only have a handful of files, in installers, that are hand-authored, most files are discovered dynamically, during build.

**Comment by NikolaMilosavljevic** [comment]
Getting the same issue with test build in release/6.0. We only have a handful of Linux files in PlatformManifestFileEntry group. I'm wondering what's special about this Windows binary that it needs to be explicitly added to Runtime package?

**Comment by ericstj** [comment]
PlatformManifest.txt -- it is generated by the shared framework SDK with a combination of automatic detection and hand authoring.  cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
We copy all of the API forwarding shims from the VS installation without checking names. The templated platform manifest requires all names to be explicitly specified so we don't miss any files that we are shipping. As a result, when a new API shim is introduced, our build automatically starts copying it to the output directory and then fails because it's not specified in the platform manifest template.

**Comment by ViktorHofer** [comment]
Is this still an issue?

**Comment by jkoritzinsky** [comment]
I don't think any additional work needs to be done here.
