### ISSUE TITLE
System.IO errors: The process cannot access the file ...

### ISSUE THREAD

**Issue by markusmobius** [dotnet/runtime#60521]
### Description

I switched from Net5 to Net 6 and I keep getting a new System.IO error when I use BinaryWriter to save large binary byte arrays to disk (a shared Windows folder on a different Windows 2022 server):

Here is my code:

```cs
public void saveclose(List<byte[]> buffer, int last_cursor)
{
    using (BinaryWriter writer = new BinaryWriter(File.Open(fileName, FileMode.Append)))
    {
        for (int i = 0; i < buffer.Count - 1; i++)
        {
            if (buffer[i] != null)
            {
                while (true)
                {
                    try
                    {
                        writer.Write(buffer[i]);
                        break;
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e.Message);
                        Console.WriteLine(".. retrying");
                        Thread.Sleep(1000);
                    }
                }
                buffer[i] = null;
            }
        }
        //save the last block
        writer.Write(buffer[buffer.Count - 1], 0, last_cursor);
    }
}

```

I am getting intermittently the following error:

`The process cannot access the file '(..)t' because it is being used by another process.`

I added the catch/try to deal with this new error temporarily. The files that I am saving are often 100GB or larger. The file name is unique and not used by any other process.

When I switch back to Net5 the error does not occur. So it seems to have to do with some code in System.IO.

### Reproduction Steps

Intermittent problem when executing the following code with large files (100GB) when saving to a Windows shared folder on a different machine (Windows 2022):

```cs
public void saveclose(List<byte[]> buffer, int last_cursor)
{
    using (BinaryWriter writer = new BinaryWriter(File.Open(fileName, FileMode.Append)))
    {
        for (int i = 0; i < buffer.Count - 1; i++)
        {
            if (buffer[i] != null)
            {
                while (true)
                {
                    try
                    {
                        writer.Write(buffer[i]);
                        break;
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e.Message);
                        Console.WriteLine(".. retrying");
                        Thread.Sleep(1000);
                    }
                }
                buffer[i] = null;
            }
        }
        //save the last block
        writer.Write(buffer[buffer.Count - 1], 0, last_cursor);
    }
}
```

### Expected behavior

Under net5 this code never produced any error. Under Net6 there are intermittent error messages of the following type:

### Actual behavior

`The process cannot access the file '(..)t' because it is being used by another process.`

### Regression?

This worked fine in Net5.

### Known Workarounds

try/catch

### Configuration

I am running Net6 RC2.

The code is executing on a Windows 2019 server. The shared folder (that I am saving to) is stored on a Windows 2022 server.

**Comment by adamsitnik** [comment]
We were able to reproduce the problem using minimal C# [sample](https://gist.github.com/adamsitnik/c18d5a43b10837dbca88f6aac487f03c#file-smallerrepro-cs) that uses Windows sys-calls directly (no `FileStream` involved).

@markusmobius it would be great if you could give the [C++](https://gist.github.com/adamsitnik/c18d5a43b10837dbca88f6aac487f03c#file-repro-cpp) sample a try. If it fails with the same error we are just going to report it to the right Team. If it does not, it might be caused by Defender (or other AV) blocking .NET apps, and we are going to reopen the issue and talk to the AV folks .
