### ISSUE TITLE
CLRInformationVersion contains the buildNumber or version suffix

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#60532]
### Description

In one of the tests in the coreclr we are matching the Informational version with ClrProductVersion. We are always including the build number in the InformationalVersion of an assembly but we dont do that for clr Product verison which is leading to the test failure.

This is reproing when we enable the stable bits flag.

 https://github.com/dotnet/runtime/pull/60482
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60482-merge-8ea93e618a844dc487/PayloadGroup0/1/console.cff9299f.log?sv=2019-07-07&se=2021-11-07T04%3A53%3A55Z&sr=c&sp=rl&sig=IBViKwqkqcGqRgvTnM98zHnFWUGmK6yIVdcwvTBcAU8%3D

// failure test https://github.com/dotnet/runtime/blob/release/6.0/src/tests/tracing/eventpipe/processinfo2/processinfo2.cs#L244

is this a test failure or a bug ? 

cc @hoyosjs @ericstj @ViktorHofer @jeffschwMSFT 

### Reproduction Steps

Turn on stable flag

### Expected behavior

```
  Finished:    tracing.eventlistener.XUnitWrapper
  Discovering: tracing.eventpipe.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  tracing.eventpipe.XUnitWrapper (found 14 test cases)
  Starting:    tracing.eventpipe.XUnitWrapper (parallel test collections = on, max threads = 4)
    tracing/eventpipe/processinfo2/processinfo2/processinfo2.sh [FAIL]
      Unhandled exception. System.Exception: ClrProductVersion must match. Expected: "6.0.0-ci", received: "6.0.0"
         at Tracing.Tests.Common.Utils.Assert(Boolean predicate, String message)
         at Tracing.Tests.ProcessInfoValidation.ProcessInfoValidation.Main(String[] args)
      apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa83a7aac)
      /root/helix/work/workitem/e/tracing/eventpipe/processinfo2/processinfo2/processinfo2.sh: line 374:  1677 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/processinfo2/processinfo2/processinfo2.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false processinfo2.dll ''
        0.0s: Test PID: 1677
        0.7s: Wrote: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=4; Reserved=0 }; }
        1.1s: Received: <omitted>
        1.1s: Total size of Payload = 358 bytes
        1.1s: pid: 1677
        1.1s: runtimeCookie: 29acf19e-51a3-4d25-b80b-1bdba44bbc91
```

### Actual behavior

I am not sure if these versions should match or its just a test failure

**Comment by trylek** [comment]
@Anipik - have you got any idea whether the failure started to repro recently or whether the issue was previously just hidden for some reason? Initially I've been thinking that perhaps my CoreCLR script changes may have caused this but I no longer think that is likely as I understand your explanation so that the CLRProductVersion suffix is missing in the CoreCLR product build and I have only modified the test build scripts, not the product build. I noticed the product version suffix in the past, I'll try to remind myself how it gets handled in the CoreCLR build.

**Comment by Anipik** [comment]
i dont think its regression, I am not sure why we are comparing the coreclrProductVersion with the informationalVersion of Executing assembly ? are they both the same thing ? 

I have seen the version suffix being included in the informational version for coreclr for a while now.

**Comment by Anipik** [comment]
> Based on the previous clarifications I assume that the bug is that "System.Private.CoreLib.dll" doesn't switch its version to just "7.0.0" in the stable mode; @Anipik / @mmitche, can you please confirm if this assumption is correct?

i think thats correct.

**Comment by Anipik** [comment]
https://github.com/dotnet/runtime/blob/main/Directory.Build.targets#L25

**Comment by trylek** [comment]
Apparently we do set <code>SuppressFinalPackageVersion</code> in a couple places, I'm especially wondering about the version in

https://github.com/dotnet/runtime/blob/efa61630fe2aeae181fd9f45f7ac42e58e783d52/src/installer/prepare-artifacts.proj#L29

**Comment by trylek** [comment]
OK, so for CoreLib it gets set here,

https://github.com/dotnet/runtime/blob/efa61630fe2aeae181fd9f45f7ac42e58e783d52/Directory.Build.props#L271

as the <code>IsPrivateAssembly</code> flag is set.

**Comment by hoyosjs** [comment]
Looks like we got tripped by a blanket assertion to prevent stabilizing assets that are "implementation details": https://github.com/dotnet/runtime/blob/efa61630fe2aeae181fd9f45f7ac42e58e783d52/Directory.Build.props#L268-L272

For 6.0 the most targeted thing might be setting `SuppressFinalPackageVersion` and `IsPrivateAssembly` to false for SPC.

**Comment by DamianEdwards** [comment]
Almost certainly cause of this regressing again #45812

**Comment by akoeplinger** [comment]
This was fixed by https://github.com/dotnet/runtime/pull/60572
