### ISSUE TITLE
[.NET 6]A derived Random class still allocates possibly unnecessary memory

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#60549]
This is a follow up after fixing #57272.

Thanks to pull request #57530 a new [Net5CompatDerivedImpl](https://github.com/dotnet/runtime/blob/074e8f0e697e94ab2ecaaedaf6e6d0b5b92b484c/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L96) class has been introduced so it can be specialized for derived `Random` implementations.

Now I could test the latest release and unfortunately this implementation still initializes the `_seedArray` even if no base member will be called ever. Now that the possible scenarios have been separated the new `Net5CompatDerivedImpl` could initialize the `_seedArray` only on demand, when it is actually needed for the first time. I [mentioned](https://github.com/dotnet/runtime/issues/57272#issuecomment-898941060) it in #57272 but the original reason of that issue was different. So now I created this one.

Of course, this would mean a minimal overhead but only when a derived instance calls some base implementation. In return the construction of the derived instance will be much faster and less memory consuming.

----

#### Update: API Proposal

To preserve the performance of the current behavior _and_ fix the mentioned issue I propose the following new API

```cs
public class Random
{
    // Determines the behavior of the base members for a derived Random class
    // when using the new protected constructor.
    protected enum BaseBehavior
    {
        // Base members use the original Random implementation.
        // Instantiation generates a seed that allocates an array consuming 224 bytes
        Compatible,

        // Base members use the xoshiro** algorithm.
        // Instantiation generates a seed consuming up to 32 bytes (on a 64 bit system)
        // Can be useful if a derived class overrides some members and the rest should work
        // the same way as the static Shared instance
        Xoshiro,

        // Base members rely on the protected Sample method
        // Instantiation does not generate any seed in the base Random class
        // Can be useful if a derived class overrides all members and does not call any base methods.
        // Can be useful also when you want to override only the Sample method to provide
        // a fully functional new Random implementation. This is useful also for tests that should
        // produce prepared results as you don't need to override anything but the Sample method.
        SampleBased
    }

    // protected constructor for derived classes
    protected Random(BaseBehavior baseBehavior)
    {
        _impl = baseBehavior switch
        {
            BaseBehavior.Compatible => new Net5CompatDerivedImpl(this),
            BaseBehavior.Xoshiro => new XoshiroImpl(),
            BaseBehavior.SampleBased => new SampleBasedImpl(this), // TODO: new implementation
            _ => throw new ArgumentOutOfRangeException(nameof(baseBehavior))
        };
    }
}
```

**Comment by koszeggy** [comment]
And by introducing a protected constructor with a `bool` parameter? So a derived class could express that it doesn't really need the base functionality.

```cs
protected Random(bool lazyInit)
{
    if (lazyInit)
        _impl = new Net5CompatDerivedLazyImpl(); // or even some NullImpl(); that throws InvalidOperationExceptions
    // ...
}
```

**Comment by GrabYourPitchforks** [comment]
API review comments - I am strongly opposed to exposing the concept of "Xoshiro" via any public API. This is supposed to be an implementation detail.

**Comment by koszeggy** [comment]
> API review comments - I am strongly opposed to exposing the concept of "Xoshiro" via any public API. This is supposed to be an implementation detail.

I basically agree. Whereas the name `Compatible` came naturally instead of Marvin, I couldn't find a similarly proper name for the new version so I picked the algo name (`SharedCompliant` just seemed too silly). So feel free to suggest a better one.

**Comment by koszeggy** [comment]
I didn't want to surprise you with an unwanted pull request so I just prepared a [commit](https://github.com/koszeggy/runtime/commit/2cea116d9ef71a3a3a0dd021030ae0dc6f4042fa) for the proposed changes. In the end I picked the name `Optimized` instead of the originally proposed `Xoshiro`.

I didn't change the tests because even though I tried to follow the [docs](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md#iterating-on-systemprivatecorelib-changes) I was unable to generate a new reference corelib assembly with the changed API so the build now produces the `MatchingRefApiCompat` error for the newly introduced members.

Can this API proposal be accepted for .NET 7? Will you accept the changes if I create a pull request? (But I actually don't even mind if you commit the changes by yourselves.)

**Comment by stephentoub** [comment]
> Can this API proposal be accepted for .NET 7?

I don't think we should add such an API.

If we can find a good way to lazily-initialize the base state such that a derived type which fully overrides everything doesn't pay for it while instances that do need the state don't regress perf (and don't have to duplicate a lot of code), I expect we'd accept a PR for that.  My previous attempts at that failed (there was a measurable impact), but things have changed in various ways since.

**Comment by koszeggy** [comment]
> I don't think we should add such an API.

I think the proposed API is actually the "more birds with one stone" case, especially the `SampleBased` approach:
* It is "future proof", so even if new members are introduced (just like as `NextInt64` and `NextSingle` were introduced in .NET 6), the non-overridden new virtual members will not revert back to the compatible behavior. This is pretty crucial in some cases such as a [SecureRandom](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/master/KGySoft.CoreLibraries/Security/Cryptography/SecureRandom.cs) class, even if a library is adapted quickly for new versions.
* Relying on `Sample` can be very useful even for tests, when one needs to mock some custom seed or series of specific values without overriding all members the tested code may call.
* It was the [original behavior](https://docs.microsoft.com/en-us/dotnet/api/system.random.sample?view=net-6.0#notes-to-inheritors) in .NET Framework 1.x. I totally understand that it wasn't too effective for a non-derived `Random` instance but there are cases when the old behavior would be very handy.
* Not mentioning that it would provide a very simple solution for the problem in the title, too.

@GrabYourPitchforks and others? What do you think? Is the proposal is really such a bad approach? My [proposed implementation](https://github.com/koszeggy/runtime/commit/2cea116d9ef71a3a3a0dd021030ae0dc6f4042fa) no longer exposes the concept of the Xoshiro algorithm.

**Comment by koszeggy** [comment]
@stephentoub: sorry for adding an unwanted noise to #75431. Of course, this issue can be handled independently from that one. Could you please add the API proposal tag to this one? I didn't create it as an API proposal and now I cannot change it. And I would not create a new issue if it's not really necessary. Thank you in advance.

**Comment by koszeggy** [comment]
Thank you for the fix.

I'm glad you chose a solution that makes also my API proposal unnecessary. From now on if someone really needs a `SampleBasedRandom` or `NextBasedRandom` class that does not allocate anything (which I proposed only to solve the initialization issue and not because I really needed such a behavior), then it can be implemented as a derived abstract class from `Random`.
