### ISSUE TITLE
[API Proposal]: SIMD/Vectorial operations on arrays/Spans

### ISSUE THREAD

**Issue by vpenades** [dotnet/runtime#60559]
### Background and motivation

In image processing and probably many other fields, it is fairly common to perform basic operations on large arrays, for example:

```c#
var left = new float[10000];
var right = new float[10000];

var result = new float[10000];

for(int i=0; i < 10000; ++i) result[i] = left[i] * right[i];
```

These operations can be made a lot faster if the operands are casted to Vector4, which make the whole operation much faster. But probably there's even more performance improvements that can be done at low level.

### API Proposal

Something like this:

```c#
static class BulkOperations
{
// sum 'value' to all destination elements
public static void Sum(float value, Span<float> destination);

// sum all 'values' to destination
public static void Sum(ReadOnlySpan<float> values, Span<float> destination);

// sum left and right into destination
public static void Sum(ReadOnlySpan<float> left, float right, Span<float> destination);

// sum left and right into destination
public static void Sum(ReadOnlySpan<float> left, ReadOnlySpan<float> right, Span<float> destination);

// multiply left and right into destination
public static void Multiply(ReadOnlySpan<float> left, ReadOnlySpan<float> right, Span<float> destination);

// cast source into destination, applying a mean and scale factor
// this is typically used to convert float values in the 0-1 range to bytes in the 0-255 range
public static void Cast(ReadOnlySpan<float> source, float mean, float scale, Span<byte> destination);
}
```

This is just a small example of the functions the API would have, obviously there would be much more:   multiply, division, absolute values, casting, byte shifting, and all kinds of bulk operations that can be greatly enhanced with simd/vectorial instrinsics.

### API Usage

```c#
var left = new float[10000];
var right = new float[10000];

var result = new float[10000];

BulkOperations.Sum(left, right, result);
```

**Comment by jeffhandley** [comment]
Tagging @dotnet/area-system-numerics since the bot didn't.

**Comment by huoyaoyuan** [comment]
This is covered by `TensorPrimitives` in #89639, for example `TensorPrimitives.Add(left, right, result)`.

**Comment by vpenades** [comment]
then I think we can close this issue as resolved.
