### ISSUE TITLE
[Android] System.Reflection.Tests.ModuleTests.GetField test failure

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#60558]
The test fails with:

```
Exception messages: Assert.Equal() Failure
    Expected: 2
    Actual:   -4541244703284919532   

Exception stack traces:    
at System.Reflection.Tests.ModuleTests.GetField() in src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs:line 174
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by mkhamoyan** [comment]
GetField() is no longer in ModuleTest.cs. I guess we can close this @steveisok ?

**Comment by steveisok** [comment]
It looks like it's still there. 

https://github.com/dotnet/runtime/blob/2a01ceb2d004a125757a4bb95a9341cc283c5afd/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs#L168-L178

**Comment by steveisok** [comment]
The test fails when dealing with a long
 https://github.com/dotnet/runtime/blob/2a01ceb2d004a125757a4bb95a9341cc283c5afd/src/libraries/System.Runtime/tests/System/Reflection/ModuleTests.cs#L175

The default value is being set in a static constructor here

https://github.com/dotnet/runtime/blob/2a01ceb2d004a125757a4bb95a9341cc283c5afd/src/libraries/System.Runtime/tests/TestModule/System.Reflection.TestModule.il#L25-L26

**Comment by kotlarmilos** [comment]
@steveisok the default value is being set in a static constructor as an int32 but retrieved as an int64 from evaluation stack. Do you think that could an issue?

Here is the proposed change:
https://github.com/dotnet/runtime/pull/75458/files

Android tests are passing now, I have to test it for ARMv6 as well and if it works I will create a PR.
https://github.com/dotnet/runtime/pull/75458/checks
