### ISSUE TITLE
Add latest BenchmarksGame tests to runtime tree

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#60578]
https://github.com/dotnet/performance/pull/1453 added binarytrees-6.cs and fannkuch-redux-9.cs to the dotnet/performance repo. Also add them to the runtime repo under src\tests\JIT\Performance\CodeQuality\BenchmarksGame.

At the same time, audit the existing BenchmarksGame tests in the runtime repo to ensure they are "as close as possible" to the copies in the performance repo.

Note: the versions in the runtime repo are regularly used by JIT developers when examining JIT generated codegen; they are much easier to work with than the versions in the performance repo.

Related: https://github.com/dotnet/performance/issues/1452

cc @danmoseley

**Comment by danmoseley** [comment]
> We should considering adding more variants, but I'd rather not see us add ones that delegate all the interesting computation to native code...

Agreed that is low value (an example is the regex redux that just wraps PCRE)

**Comment by BruceForstall** [comment]
New versions were picked up. It's a whole different issue to update all the tests.
