### ISSUE TITLE
Floating point benchmark performance difference Linux vs. Windows

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#6058]
Several benchmarks from coreclr\tests\src\JIT\Performance\CodeQuality show worse code generated for Linux because of lack of callee-saved floating point registers on Linux. Two examples are NewtE and Burgers.Test3. This issue is to investigate if anything can be done to mitigate that.

category:cq
theme:calling-convention
skill-level:intermediate
cost:small

**Comment by jakobbotsch** [comment]
We eventually implemented FP CSE and adjusted heuristics in CSE and RA to help with some of these cases. Performance of math functions were also improved on non-windows (#7364).
