### ISSUE TITLE
Productize LibraryImportGenerator for use outside of runtime

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#60595]
Issues to address/consider after ship-ready work (https://github.com/dotnet/runtime/issues/60212):

## APIs:
- [x] https://github.com/dotnet/runtime/issues/46822
  - [x] https://github.com/dotnet/runtime/issues/61181
  - [x] #61326
- [x] https://github.com/dotnet/runtime/issues/46838
- [x] https://github.com/dotnet/runtime/issues/66121
- [x] https://github.com/dotnet/runtime/issues/66623

## Reconciliation of blittable/unmanaged:
- [x] https://github.com/dotnet/runtime/issues/60639
- [x] Update design doc for user-defined type marshalling with the new `DisableRuntimeMarshallingAttribute`
  - https://github.com/dotnet/runtime/pull/63765
- [x] Update source generator for `DisableRuntimeMarshallingAttribute` and reconciled unmanaged/blittable
  - Source generator treats unmanaged as not requiring marshaling
  - Add marshalling info (`NativeMarshalling` or `MarshalUsing`) for types in runtime libraries that need it
  - Runtime libraries use `DisableRuntimeMarshallingAttribute`
  - Convert p/invokes using affected types to GeneratedDllImport - known p/invokes are marked `// TODO: [DllImportGenerator]` and `#pragma warning disable DLLIMPORTGENANALYZER015`
- [x] https://github.com/dotnet/runtime/pull/67676

## Custom marshallers:
- [x] Add marshaller types to runtime libraries
  - [x] Strings: https://github.com/dotnet/runtime/pull/67635
  - [x] Arrays: https://github.com/dotnet/runtime/pull/68173

## Release:
- [ ] Update diagnostics to match convention/prefix for runtime libraries
  - Use `SYSLIB1###' IDs and update [doc](https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md#analyzer-warnings)
  - https://github.com/dotnet/runtime/pull/65983
- [x] Localization - https://github.com/dotnet/runtime/pull/67107
- [x] Include `DllImportGenerator` in NETCoreApp ref-pack
  - See https://github.com/dotnet/runtime/issues/61321
  - https://github.com/dotnet/runtime/pull/68247
- [x] Apply GeneratedCodeAttribute https://github.com/dotnet/runtime/issues/64562
- [x] Enable trimming of attributes used for generation

## Fixer:
A code fixer should be provided to help with the conversion to using generated p/invokes via the new attribute. We may not support all options based on added complexity versus usage.
- Basic conversion to new attribute where all options specified on DllImport are supported by source generator
- `PreserveSig`: change managed signature to return `int` and have an `out` param if necessary, add custom marshaller for return value to throw if necessary, update callers, 
- `ExactSpelling`: different fix option to append suffix on `EntryPoint` property
- Add stubbed out implementation for custom marshallers

## Issues:
- [x] https://github.com/dotnet/runtimelab/issues/1650
- [ ] https://github.com/dotnet/runtimelab/issues/963 
- [x] https://github.com/dotnet/runtimelab/issues/1653
- [x] https://github.com/dotnet/runtime/issues/62291
- [x] https://github.com/dotnet/runtime/issues/62700
- [x] https://github.com/dotnet/runtime/pull/63464
- [x] https://github.com/dotnet/runtime/issues/65154

**Comment by kant2002** [comment]
Does attempt to add DllImportGenerator to WinForms require all outstanding tasks here to be completed?

**Comment by AaronRobinsonMSFT** [comment]
> Does attempt to add DllImportGenerator to WinForms require all outstanding tasks here to be completed?

No necessarily but we reserve the right to change any of the generated code or APIs that we are using. Additionally, we haven't put the source generator on a feed that would make consumption simple. From the Interop team's perspective, all products not in the dotnet/runtime repo are the same.

**Comment by kant2002** [comment]
There some version on the feed `7.0.0-preview.2.22110.4` (in addiional to experimental feed), but that package blocked by internal `GeneratedDllImportAttribute`.

I do understand that WinForms is external product for you. I would like to throw some boulder on WinForms by applying `BuiltInComSupprted=false` and `DisableBuiltInMarshalling=true`. I expect this to be problematic and prefer not to build custom runtime for that experiment. Is this somehow possible?

If not, can you tell me what's blocking the team from going preview mode?

**Comment by AaronRobinsonMSFT** [comment]
> There some version on the feed 7.0.0-preview.2.22110.4

I didn't realize that. Perhaps something can be done here.

> If not, can you tell me what's blocking the team from going preview mode?

The API reviews Reconciliation of blittable/unmanaged, and Release sections above are all mostly required. We then need to update the tooling with the new name and provide APIs that support the support for the generated, right now everything is internal since the API surface area and design are all in flux.

I should also note that the current plan is to productize this for .NET 7, but that is not something we're committed to. The only commitment is to ship the entire dotnet/runtime repo with generated source for all DllImports. Based on other factors this could slip and become productized in the next release. I don't think that is going to happen, but it is possible. The general point is there are a lot of moving parts to productizing this source generator because of expectations on how it works and support for assemblies containing the generated code. Even acknowledging that previews are not supported doesn't change much. We would like to ensure what we do release in a preview is something we can feasibly deliver so we don't need to remove it prior to an RC. The majority of the work here is around software support infrastructure and tenets that must be followed due to what the product is doing.

Other than hacking together a custom runtime, I'm not sure how easy this is going to be at present.

**Comment by kkukshtel** [comment]
Just as a question - is an intended use case of this to be something that can replace the ClangSharp P/Invoke generator? https://www.nuget.org/packages/ClangSharpPInvokeGenerator

**Comment by AraHaan** [comment]
Not at all, ChangSharp is meant for converting native header files into .NET PInvokes.

**Comment by kant2002** [comment]
I would like to comeback and ask again what's happening with this feature. `LibraryImportGenerator` is missing from feeds right now and there no easy way to consume source generator. From what I see it was disabled after discussion here https://github.com/dotnet/runtime/issues/65495#issuecomment-1049111768 but that still does not explain why it is needed.

Which is sad, since that limit ability to play with feature **in the preview mode without expecting it to be shipped**. There couple other enthusiasts from the Discord who probably willing to put their dirty hands into this feature.

Is there something which I can do to unblock packaging (because from my understanding it was some build failures)?

**Comment by AaronRobinsonMSFT** [comment]
This is now consumable in preview 5. This source generator is in the ref pack for when targeting the preview 5 TFM - this is by design and that is the minimum TFM requirement.

See https://github.com/dotnet/runtime/pull/68247.

**Comment by shaggygi** [comment]
@AaronRobinsonMSFT Any plans to add docs/examples on scenarios and how to use?  I'm sure there already is and I'm overlooking.  Just trying to understand feature and some of the basics to get started.  Thx

**Comment by kant2002** [comment]
Thank you! This new made my day. So if I understand correctly LibraryImportGenerator is part of .NET SDK and would be shipped together with it. Correct?

**Comment by AaronRobinsonMSFT** [comment]
> Any plans to add docs/examples on scenarios and how to use? I'm sure there already is and I'm overlooking. Just trying to understand feature and some of the basics to get started. Thx

There are plans and as with any product there will be docs and samples once we get out of preview. The repo does contain a sample - see https://github.com/dotnet/runtime/tree/main/src/samples/LibraryImportGeneratorSample.

Low-level design docs and how it works can be found under https://github.com/dotnet/runtime/tree/main/docs/design/features and in https://github.com/dotnet/runtime/tree/main/docs/design/libraries/LibraryImportGenerator.

This is a non-trivial feature that is still technically in flux since we are in preview. Please be patient with the low-level nature of the documentation and how the source generator is used from an end-user perspective. Proper higher-level walkthroughs are forth coming but will likely be closer to the RC. For now, the team is focused on ensuring correctness for non-netcoreapp scenarios and comprehensive testing. Also, the work to make anything an enterprise quality product is extensive - see this issue and all the non-functional work items - which is why the walkthroughs and samples are not yet ready.

**Comment by shaggygi** [comment]
@AaronRobinsonMSFT completely understand.  thanks for the info and look forward to feature.  keep up the good work 👍

**Comment by AraHaan** [comment]
> This is now consumable in preview 5. This source generator is in the ref pack for when targeting the preview 5 TFM - this is by design and that is the minimum TFM requirement.
> 
> See #68247.

sad it cant be in a nuget package as well for those who want to use the generator downlevel (in .NET 6 projects).

**Comment by elinor-fung** [comment]
Closing out this issue as the work to the LibraryImportGenerator exposed and consumable outside of the runtime repo is done. It is in the daily main builds and will be in .NET 7.0 Preview 5.

Please do file issues to let us know about problems you hit or questions you have when trying to consume this.
