### ISSUE TITLE
Enable using live ref pack in source generator unit tests

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#60605]
Currently, source generator unit tests either directly reference implementation assemblies or use a non-live ref pack. To enable using live ref assemblies in source generator unit tests, we should add infrastructure to zip the live ref assemblies, include in the Helix payload, and unzip / resolve against in the unit tests

**Comment by ViktorHofer** [comment]
> To enable using live ref assemblies in source generator unit tests, we should add infrastructure to zip the live ref assemblies, include in the Helix payload

As the targeting pack (ref pack) is only needed for building and not running, why would we need that on a Helix machine? Do we actually build on Helix now?

**Comment by jkoritzinsky** [comment]
The ref pack is needed to add to a Roslyn `Compilation` object so we can run our analyzer/source-generator/code-fix tests against the actual assemblies our customers will compile against.

So yes, in a sense we're building code on Helix now, just as part of tests that hook into our customer's compilation experience.
