### ISSUE TITLE
JIT assert on arm64 when running DllImportGenerator tests: op2->TypeIs(TYP_LONG)

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#60624]
https://dev.azure.com/dnceng/public/_build/results?buildId=1429275&view=ms.vss-test-web.build-test-results-tab
```
/root/helix/work/correlation/dotnet exec --runtimeconfig DllImportGenerator.Tests.runtimeconfig.json --depsfile DllImportGenerator.Tests.deps.json xunit.console.dll DllImportGenerator.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: DllImportGenerator.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  DllImportGenerator.Tests (found 94 test cases)
  Starting:    DllImportGenerator.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 27 [0x0000001b], Thread: 40 [0x0028]): Assertion failed 'op2->TypeIs(TYP_LONG)' in 'Arrays:AndAllMembers(SharedTypes.BoolStruct[],int):bool' during 'Lowering nodeinfo' (IL size 180)

    File: /__w/2/s/src/coreclr/jit/gentree.cpp Line: 2449
    Image: /root/helix/work/correlation/dotnet
```
also seen in some PGO testing I did.

**Comment by am11** [comment]
This assertion failed the `CoreCLR Pri0 Runtime Tests Run Composite OSX arm64 checked` build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1500310/logs/416:

```
  Building Targeting Pack
  external -> 
  Compiling framework using Crossgen2: "/Users/runner/work/1/s/dotnet.sh" "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/R2RTest/R2RTest.dll" compile-framework -cr "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root" --output-directory "/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out" --release --nocleanup --target-arch arm64 -dop 4 -m "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/StandardOptimizationData.mibc" --composite --verify-type-and-field-layout --crossgen2-path "/Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll"
  Using dotnet: /Users/runner/work/1/s/.dotnet/dotnet
  1 / 1 (0%, 0 failed): launching: /Users/runner/work/1/s/.dotnet/dotnet /Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll @/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out/framework-r2r.dll.rsp
  1 / 1 (100%, 1 failed): failed in 149283 msecs, exit code 133, expected 0: dotnet /Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll @/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out/framework-r2r.dll.rsp
    /Users/runner/work/1/s/src/coreclr/jit/gentree.cpp:2449
    Assertion failed 'op2->TypeIs(TYP_LONG)' in 'System.Collections.Generic.ArraySortHelper`1:InsertionSort(System.Span`1[Microsoft.Diagnostics.Tracing.CLRRuntimeActivityComputer+StartStopThreadEventData],System.Comparison`1[Microsoft.Diagnostics.Tracing.CLRRuntimeActivityComputer+StartStopThreadEventData])' during 'Lowering nodeinfo' (IL size 116)
/Users/runner/work/1/s/src/tests/build.proj(519,5): error MSB3073: The command ""/Users/runner/work/1/s/dotnet.sh" "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/R2RTest/R2RTest.dll" compile-framework -cr "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root" --output-directory "/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out" --release --nocleanup --target-arch arm64 -dop 4 -m "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/StandardOptimizationData.mibc" --composite --verify-type-and-field-layout --crossgen2-path "/Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll"" exited with code 1.
```

**Comment by trylek** [comment]
Latest repro in my targeted CG2 testing:

https://dev.azure.com/dnceng/public/_build/results?buildId=1507562&view=logs&j=9fb4e71d-6fdc-50b9-1fe9-e6062f97f43b&t=2f5ed8ec-63ba-5d64-811a-336c2a4b4d47

<pre>
  Compiling framework using Crossgen2: "/Users/runner/work/1/s/dotnet.sh" "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/R2RTest/R2RTest.dll" compile-framework -cr "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root" --output-directory "/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out" --release --nocleanup --target-arch arm64 -dop 4 -m "/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/StandardOptimizationData.mibc" --composite --verify-type-and-field-layout --crossgen2-path "/Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll"
  Using dotnet: /Users/runner/work/1/s/.dotnet/dotnet
  1 / 1 (0%, 0 failed): launching: /Users/runner/work/1/s/.dotnet/dotnet /Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll @/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out/framework-r2r.dll.rsp
  1 / 1 (100%, 1 failed): failed in 114584 msecs, exit code 133, expected 0: dotnet /Users/runner/work/1/s/artifacts/bin/coreclr/OSX.arm64.Checked/x64/crossgen2/crossgen2.dll @/Users/runner/work/1/s/artifacts/tests/coreclr/obj/OSX.arm64.Checked/crossgen.out/framework-r2r.dll.rsp
    /Users/runner/work/1/s/src/coreclr/jit/gentree.cpp:2257
    Assertion failed 'op2->TypeIs(TYP_LONG)' in 'System.Collections.Generic.ArraySortHelper`1:InsertionSort(System.Span`1[Microsoft.Diagnostics.Tracing.CLRRuntimeActivityComputer+StartStopThreadEventData],System.Comparison`1[Microsoft.Diagnostics.Tracing.CLRRuntimeActivityComputer+StartStopThreadEventData])' during 'Lowering nodeinfo' (IL size 116)
</pre>

**Comment by am11** [comment]
Looks like it is failing since this change https://github.com/dotnet/runtime/commit/220b746f1ebe276b2045fd0a45768a7c993348d7#diff-fba867eda1c745875748370c59da2195c3823b85a17d199444068d93f91c749bR2473-R2476
@SingleAccretion, should we convert those asserts back to conditions? (seems harmless)

**Comment by SingleAccretion** [comment]
As I note above, the assert means something is creating invalid IR, I think we should fix that place instead.

It seems we have a CG2 reproduction now, so let me take a closer look.
