### ISSUE TITLE
Cookie doesn't get replaced in CookieContainer

### ISSUE THREAD

**Issue by radischevo** [dotnet/runtime#60628]
Recently I ran into an issue communicating with a remote website that sets cookies with inconsistent `Domain` attributes.
Consider the following repro:
```c#
var uri = new Uri("https://example.com/", UriKind.Absolute);
var container = new CookieContainer();

// First HTTP response...
container.SetCookies(uri, "foo=bar; Path=/; Domain=example.com");

// Second HTTP response...
container.SetCookies(uri, "foo=baz; Path=/; Domain=.example.com");

Console.WriteLine("Got {0} cookies, expected 1. ", container.GetCookies(uri).Count);
```
I expected that the second cookie would overwrite the first one, but there are now two cookies in the container instead. When using `curl`, the cookie gets replaced though, the same way browsers behave.

The issue reproduces on both .NET Core 5.0.402 (Mac) and .NET Framework 4.8 (Win).

**Comment by ZeroRyogi** [comment]
According to [RFC6265 4.1.2.3](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.3) if the domain attribute starts with a leading %x2E (".") the character should be ignored. If it ends with %x2E (".") the domain attribute should be ignored.

It is also the implementation referenced by curl:

https://github.com/curl/curl/blob/e7416cfd2bd58d256b8524f31ef22a43aa23a970/lib/cookie.c#L133-L145

I'll try to look into it.

**Comment by ZeroRyogi** [comment]
My take is that additional logic needs to be set at

https://github.com/dotnet/runtime/blob/a3b186b9904844b8001d4bb5d7474f2591ee96d9/src/libraries/Common/src/System/Net/CookieComparer.cs#L17

So when  Domain names are compared if the domain contains a leading "." then it should be ignored so ".domain" and "domain" are considered equal.

**Comment by ZeroRyogi** [comment]
Just tested my approach and seems to be working alright:

The following code:

```c#
using System.Net;

Console.WriteLine("Waiting to attach");
Console.ReadLine();

var uri = new Uri("https://example.com/", UriKind.Absolute);
var container = new CookieContainer();

// First HTTP response...
container.SetCookies(uri, "foo=bar; Path=/; Domain=example.com");

// Second HTTP response...
container.SetCookies(uri, "foo=baz; Path=/; Domain=.example.com");

Console.WriteLine("Got {0} cookies, expected 1. ", container.GetCookies(uri).Count);
Console.WriteLine("Got {0} cookies, expected 1. ", container.GetCookies(uri)[0].Domain);
```
Yields:
![image](https://user-images.githubusercontent.com/560074/142232503-4b0905a3-ada7-4810-b9f1-5a4ac70b8ea3.png)

Adding the following method to CookieComparer.cs:

```c#
internal static string? RemoveLeadingDot(string? s)
{
    if (string.IsNullOrEmpty(s))
    {
        return s;
    }

    if (s[0] == '.')
    {
        return s[1..];
    }

    return s;
}
```
An changing the Compare method:

```c#
internal static int Compare(Cookie left, Cookie right)
{
    int result;

    if ((result = string.Compare(left.Name, right.Name, StringComparison.OrdinalIgnoreCase)) != 0)
    {
        return result;
    }

    string? cookieLeftDomain = RemoveLeadingDot(left.Domain);
    string? cookieRightDomain = RemoveLeadingDot(right.Domain);

    if ((result = string.Compare(cookieLeftDomain, cookieRightDomain, StringComparison.OrdinalIgnoreCase)) != 0)
    {
        return result;
    }

    // NB: Only the path is case sensitive as per spec. However, many Windows applications assume
    //     case-insensitivity.
    return string.Compare(left.Path, right.Path, StringComparison.Ordinal);
}
```

I also have ready unit testing. If @karelz has no objections I can go ahead with the PR.

**Comment by radischevo** [comment]
@ZeroRyogi, looks good, but if the domain begins with a dot, an extra string will be allocated per each `RemoveLeadingDot` call. I'd suggest you to use a `string.Compare` overload, that does not require allocation at all. So the comparer could look like this:

```
internal static int Compare(Cookie left, Cookie right)
{
    int result;
	
    if ((result = string.Compare(left.Name, right.Name, StringComparison.OrdinalIgnoreCase)) != 0)
    {
        return result;
    }

    if ((result = CompareDomain(left.Domain, right.Domain)) != 0)
    {
        return result;
    }

    // NB: Only the path is case sensitive as per spec. However, many Windows applications assume
    //     case-insensitivity.
    return string.Compare(left.Path, right.Path, StringComparison.Ordinal);
}
	
private static int CompareDomain(string? left, string? right) 
{
    if (left is null) 
    {
        return right is null ? 0 : -1;
    }
	
    if (right is null) 
    {
        return 1;
    }
	
    var indexLeft = GetComparisonStartIndex(left);
    var indexRight = GetComparisonStartIndex(right);

    return string.Compare(left, indexLeft, right, indexRight, left.Length - indexLeft);
}

private static int GetComparisonStartIndex(string domain) 
    => domain.Length != 0 && domain[0] == '.' ? 1 : 0;
```

**Comment by ZeroRyogi** [comment]
Thank you! good thinking. Feel like this should have been a Code Review already 😄. Will improve and wait for the response to check if this is the correct approach in order to send the PR.

**Comment by radischevo** [comment]
Well, I did some thinking, and I should say that while tweaking the `CookieComparer` definitely solves the problem, I'm not sure that we now comply with the RFC well. If we are told to ignore the leading dot in the domain, probably it's the `Cookie` class itself, that should trim the leading dot on assignment?

**Comment by ZeroRyogi** [comment]
I thought about it as well. The spec reads that the leading dot should be ignored, but leaves open the implementation detail of trimming the character of leaving the Domain as is (as returned from the server or set by the user). If the user or server purposely (as in this example) sets ups the domain as ".domain.tld" is he expecting in return the same ".domain.com" ? or is it ok to return the modified domain?

**Comment by greenEkatherine** [comment]
Sorry for taking so long for response.

[RFC6265 4.1.2.3](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.3) (for agent - [RFC6265 5.2.3](https://datatracker.ietf.org/doc/html/rfc6265#section-5.2.3)) recommends to ignore and not mandatory remove the leading dot, so in our case it could be done internally as you suggested - by adding this logic into `CookieComparer`. I don't think that we should modify domain string in `Cookie` class or somewhere else, because [we left leading dot there intentionally](https://github.com/dotnet/runtime/pull/39781) - based on browsers' behaviour.

@ZeroRyogi are you still interested in putting up PR?

**Comment by greenEkatherine** [comment]
I don't get a reply in two weeks, so I will take on this change and prepare PR.

**Comment by greenEkatherine** [comment]
I checked if the browsers changed its behavior since the last time - Edge and Firefox also add dots:

Set-Cookie | CookieContainer | Chrome | Edge | Firefox | RFC
-- | -- | -- | -- | -- | --
xample.com | xample.com | .xample.com | .xample.com | .xample.com | xample.com
.xample.com | .xample.com | .xample.com | .xample.com | .xample.com | xample.com
