### ISSUE TITLE
Windows x86 CoreCLR assert failure: ExecutionManager::IsManagedCode(GetControlPC(pCF->GetRegisterSet()))

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#60648]
When running the DllImportGenerator.Tests test suite against CoreCLR x86 Checked builds, sometimes we get an assert failure when calling `GC.Collect` in an `UnmanagedCallersOnly` method that was called from managed code with some native code in between.

See https://dev.azure.com/dnceng/public/_build/results?buildId=1429326&view=ms.vss-test-web.build-test-results-tab&runId=41318808&resultId=188820&paneView=debug for a repro in a rolling build.

This took about 40-50 runs locally to reproduce, so it's a rare occurrence.

After some basic investigation, it looks like the `CrawlFrame` instance has a null `ControlPC`, so something is not being constructed/discovered correctly with it.

**Comment by jkotas** [comment]
Fixed by #63826
