### ISSUE TITLE
Regression from 5.0: HttpClient does not retry HTTP/1.1 request if TCP connection is closed

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#60644]
There is an inherent race between server closing an "idle" connection and client trying to issue a request to this connection at the same time. [Per RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-8.1.4), we should retry such request (if it is idempotent).

In 6.0, there was a change in retry logic https://github.com/dotnet/runtime/commit/288bfa00fe28b4b25637c362683dd8c6b6573351 which led to requests being no longer retried in case TCP connection was abruptly closed in the middle or right after sending the headers (see [HttpConnection.cs](https://github.com/dotnet/runtime/blob/bc7b910144d1f2b62de05540b9df1bb90f3729b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L398))

Because of that, users upgrading from 5.0 to 6.0 would see request failures out of nowhere even with well-behaved servers -- on the requests that could be safely retried.

In the repro below, the server would abort the first connection by closing the socket after replying to the first request. HttpClient would successfully execute the second request on a new connection for 5.0, but it will fail with `System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..` on 6.0.

<details>
  <summary>Repro</summary>
  
```c#
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace TcpRstServerRepro
{
    class Program
    {
        const int serverPort = 5000;
        const int responseLength = 10;

        public static async Task Main()
        {
            var httpClient = new HttpClient(new SocketsHttpHandler() 
            { 
                MaxConnectionsPerServer = 1
            });

            using (Socket server = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp))
            {
                server.Bind(new IPEndPoint(IPAddress.Any, serverPort));

                server.Listen();
                Task<Socket> handleRequestTask = NewConnectionHandleRequestAsync(server);

                HttpResponseMessage response = await httpClient.GetAsync($"http://localhost:{serverPort}/");

                Console.WriteLine("CLIENT: Received response:");
                Console.WriteLine(response);
                Console.WriteLine(await response.Content.ReadAsStringAsync());
                response.Dispose();

                Socket accept = await handleRequestTask;

                Console.WriteLine("CLIENT: Will sleep for 1s");
                Thread.Sleep(1_000);

                // and once again...

                Task<Socket> handleSecondRequestTask = NewConnectionHandleRequestAsync(server);

                var secondResponseTask = httpClient.GetAsync($"http://localhost:{serverPort}/");

                Console.WriteLine("SERVER: closing connection");
                accept.Close(); // closing first connection while HttpClient started the second request...

                HttpResponseMessage secondResponse = await secondResponseTask;

                Console.WriteLine("CLIENT: Received response:");
                Console.WriteLine(secondResponse);
                Console.WriteLine(await secondResponse.Content.ReadAsStringAsync());
                secondResponse.Dispose();

                Socket secondAccept = await handleSecondRequestTask;
                Console.WriteLine("SERVER: closing connection");
                secondAccept.Close();
            }
        }

        private static async Task ExistingConnectionHandleRequestAsync(Socket accept)
        {
            //string query = "GET / HTTP/1.1\r\nHost:localhost:5000\r\n\r\n";
            var requestBytes = new List<byte>(45);
            var byteBuffer = new byte[1];
            while (true)
            {
                int num = await accept.ReceiveAsync(byteBuffer, SocketFlags.None);
                if (num == 0)
                {
                    throw new Exception("Unexpected EOS");
                }

                requestBytes.Add(byteBuffer[0]);
                if (requestBytes.Count >= 4 &&
                    requestBytes[requestBytes.Count - 4] == (byte)'\r' &&
                    requestBytes[requestBytes.Count - 3] == (byte)'\n' &&
                    requestBytes[requestBytes.Count - 2] == (byte)'\r' &&
                    requestBytes[requestBytes.Count - 1] == (byte)'\n')
                {
                    break;
                }
            }

            Console.WriteLine("SERVER: Received query:");
            Console.Write(Encoding.ASCII.GetString(requestBytes.ToArray()));

            string responseText =
                        "HTTP/1.1 200 OK\r\n" +
                        $"Content-Length: {responseLength}\r\n\r\n{new string('a', responseLength)}";

            Console.WriteLine("SERVER: Sending response:");
            Console.WriteLine(responseText);

            await accept.SendAsync(Encoding.ASCII.GetBytes(responseText), SocketFlags.None);
        }

        private static async Task<Socket> NewConnectionHandleRequestAsync(Socket listener)
        {
            Socket accept = await listener.AcceptAsync();
            accept.LingerState = new LingerOption(true, 0); // this will send TCP RST on socket Close

            await ExistingConnectionHandleRequestAsync(accept);

            return accept;
        }
    }
}
```

</details>

**Comment by scalablecory** [comment]
> @scalablecory 5.0 behavior is current behavior and multiple real-world services intrinsically depend on this. 6.0 behavior might be spec-compliant, but breaks services. How we do reconcile what to optimize for? spec or real services? By keeping 5.0 behavior, HttpClient is not worse off than it is in today's 5.0 release. Moving to 6.0 behavior, however, is guaranteed to break services.

I'm not saying we make no change here, just that we don't want _exactly_ 5.0's behavior.

The specific non-compliance I'm worried about is hugely dangerous, so it's not something we can write off as an optimization. However, there are some other changes to investigate that will move the needle in the direction you want.

**Comment by geoffkizer** [comment]
Here's where I think we are currently:

The 5.0 behavior was not spec compliant and potentially dangerous. 6.0 fixes this. We do not want to revert to 5.0 behavior.

In some cases, this results in significantly more request failures. This is because some servers (in particular IIS) shutdown idle connections in a non-spec-compliant way. In 5.0, we would (incorrectly) retry when this happened; in 6.0 we no longer do.

To mitigate this, we could add support for retrying idempotent requests. We did not support this previously, in part because it wouldn't really have added much value over the previous aggressive retry policy that applied to all requests (idempotent or not). But with the new, more conservative 6.0 retry policy, this may now be worth doing. (And it would actually allow retry in some cases where 5.0 did not, such as resetting an HTTP2 connection.)

This retry policy would only apply to idempotent methods -- in particular, GET but not POST. We may choose to restrict this specifically to GET, since this would likely provide the vast majority of benefit here while limiting the overall change in behavior.

**Comment by karelz** [comment]
@avparuch I don't think it meets the bar for breaking change, unless we believe this will noticeably impact non-trivial number of customers.

**Comment by k-s-s** [comment]
Hi

I'm having some connection issues that were fine in NET Core 3.1 and NET 5, but now getting regular client side exceptions.
My problems are coming in HTTP requests and EF Core 6, Microsoft.Data.SqlClient.
I did get a wireshark trace showing some RST packets being sent during and active request (maybe idle data stream).
The operations are long running, 30s to 30min.
Can anyone advise how to get more trace details for the problems?
I tried to use dotnet trace but I could find any HttpClient/ SqlClient in the net trace file? Is there an example for this?

The changing back socket handler pooled connection lifetime to 2 minute, didn't help.
I've tried keep alive ping timeout as infinite as well.

Thanks

**Comment by CarnaViire** [comment]
Just as an FYI for anyone who might be taking up on this, I have an old branch where I attempted to fix it: https://github.com/dotnet/runtime/compare/main...CarnaViire:http11-fix-retries

The change itself is easy, but I got stuck on not being able to make the tests consistent: closing the socket on the `LoopbackServer`'s side would sometimes cause an error different from `SocketError.ConnectionReset` for some reason. And then this issue got deprioritized...

In my change, I introduced idempotence check, but it might be better to limit this to GET requests only.

**Comment by karelz** [comment]
Triage: Limited customer impact (2 customers in last 1 year). Moreover, it impacts only "weird" servers which do not close connects gracefully.
Given complexity in tests, we do not have time to finish it in 7.0. Moving to 8.0 to do it early.

**Comment by MihaZupan** [comment]
This issue has been mitigated by #72958 for cases where the server advertises its keep-alive timeout via a response header.
```http
Keep-Alive: timeout=xyz
```

**Comment by ManickaP** [comment]
Triage: this issue has been mitigated as stated in https://github.com/dotnet/runtime/issues/60644#issuecomment-1227364286, it's a rare problem, closing.
