### ISSUE TITLE
[API Proposal]: Add (e.g.) `out bool created` to MemoryMappedFile.CreateOrOpen()

### ISSUE THREAD

**Issue by rickbrew** [dotnet/runtime#60664]
### Background and motivation

In Paint.NET, I call directly into `CreateFileMappingW()` for the purpose of creating an `HWND`-sized memory mapped file. This is used for single instance management (only 1 instance of the app is allowed). The `HWND` is used for forwarding command-line parameters, e.g. you double click on an image in Explorer and it'll open up in the existing instance of Paint.NET. I use `SendMessageW(WM_COPYDATA)` to send that data over.

I could port this to use a combination of `MemoryMappedFile.CreateNew()` and `MemoryMappedFile.OpenExisting()`, basically trying them in a loop and catching exceptions. That's unappealing to me though because my current code needs no loops or anything, it just checks `Marshal.GetLastWin32Error()` for `ERROR_ALREADY_EXISTS` to determine if the current process is the first instance or not. This happens at startup, so performance is paramount. But it's also just nice to have simpler code.

Here's a fragment of my code that illustrates that I'm doing:
```C#
public unsafe SingleInstanceManager(string moniker)
{
    this.mappingName = GenerateMappingName(moniker);

    int error;
    fixed (char* szMappingName = this.mappingName)
    {
        this.hFileMapping = Windows.CreateFileMappingW(
            Windows.INVALID_HANDLE_VALUE,
            null,
            Windows.PAGE_READWRITE | Windows.SEC_COMMIT,
            0,
            mappingSize,
            (ushort*)szMappingName);

        error = Marshal.GetLastWin32Error();
        if (this.hFileMapping == IntPtr.Zero)
        {
            throw new Win32Exception(error, $"{nameof(Windows.CreateFileMappingW)} returned NULL ({error}");
        }
    }

    this.isFirstInstance = (error != Windows.ERROR_ALREADY_EXISTS);
}
```

### API Proposal

```C#
namespace System.IO.MemoryMappedFile`
{
    public class MemoryMappedFile
    {
        [SupportedOSPlatform("windows")]
        public static MemoryMappedFile CreateOrOpen(
            string mapName, 
            long capacity, 
            MemoryMappedFileAccess access, 
            MemoryMappedFileOptions options, 
            HandleInheritability inheritability, 
            out bool created); // <-- new out parameter, true if created, false if opened
    }
}
```     

### API Usage

I could replace my p/invoking with something like

```C#
this.fileMapping = MemoryMappedFile.CreateOrOpen(..., out this.isFirstInstance);
```

### Alternative Designs

Could also return the bool, and have the `MemoryMappedFile` be the out parameter, similar to the `bool TryFoo(..., out T value)` pattern seen elsewhere. Or maybe use an `enum` to be clearer.

```C#
namespace System.IO.MemoryMappedFile
{
    public class MemoryMappedFile
    {
        [SupportedOSPlatform("windows")]
        public static bool TryCreateOrOpen(
            string mapName, 
            long capacity, 
            MemoryMappedFileAccess access, 
            MemoryMappedFileOptions options, 
            HandleInheritability inheritability, 
            out MemoryMappedFile mappedFile);
    }
}
```     

### Risks

Shouldn't be much ¯\\_(ツ)_/¯ other than the usual code review scrutiny. This method's code should be simpler than the others. It also eliminates race conditions, sleeps, timeouts, and exception handling code (performance!) that are required when trying to determine "first" first "not first", e.g. using `CreateNew()` and `OpenExisting()` in a loop in order to distinguish between the two.

These methods are already marked as Windows-only, and Windows does support this functionality, so there isn't the risk of having to bend over backwards to make alternative implementations on platforms that can't do it.

**Comment by adamsitnik** [comment]
Hello @rickbrew 

Thank you for your proposal. I understand your needs, but I wonder how many other users would take advantage of such method. 

Would it be sufficient to just use the following code:

```cs
static (MemoryMappedFile file, bool isFirstInstance) CreateOrOpen(string mapName, long capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
    => (MemoryMappedFile.CreateOrOpen(mapName, capacity, access, options, inheritability), Marshal.GetLastWin32Error() == 0xB7); // Windows.ERROR_ALREADY_EXISTS
```

We try to avoid adding new OS-specific methods to .NET and this is another reason why I am not sure if we should add it.

**Comment by GSPP** [comment]
I'm going to keep this issue from automatic closure. This seems like a reasonable API addition. If it is closed, it should be a human decision.

**Comment by adamsitnik** [comment]
> If it is closed, it should be a human decision.

Based on the fact that I've not received a response from the author for two months I am closing the issue. Please feel free to provide the answer and reopen.
