### ISSUE TITLE
suggestion: enable FileStream Length caching on non-Windows

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#60677]
Part of the optimization in `FileStream` for .NET 6 is `Length` caching.

This is enabled only on Windows:

https://github.com/dotnet/runtime/blob/c15c7cfd06e5afc3d3b6265111ebcb527f156044/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L107

The reason for enabling it only on Windows is that the Unix platforms do not guarantee that `FileShare.None` means no one else can change the file. (The locking is advisory, not mandatory.)

Can we drop the Windows restriction based on the intent expressed by the user through `FileShare`, even when the platform does not guarantee it?

@adamsitnik @stephentoub what do you think?

**Comment by tmds** [comment]
> In the example that you have provided:

I'm not picking a random example, these are the canonical flags to open a read-only file.

`File.OpenRead` uses exactly those flags:

https://github.com/dotnet/runtime/blob/aea5cb9d3dfeefbb952f99e95f38eab4778a6f06/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L182-L183

> user expects that nobody else is able to write to the same file. But since FileShare.Read is mapped to shared file lock, it is not true.

Yes, this is what I mean by _we're not adding a problem by caching_. The problem is already there. The code that follows has no reason to assume `Length` is not cache-able, and for that reason I think it's ok for us to cache it.

Does that change your opinion? Or do you think we are aggravating it by caching?

**Comment by adamsitnik** [comment]
@stephentoub what is your opinion on this subject?

**Comment by stephentoub** [comment]
What do we expect this to improve in practice / real-world usage?

I don't understand the claims about not adding a problem by caching.  Yes, there's already an issue that if you specify FileShare.Read someone else could write to it, but if that happens, with the proposed change Length will become out-of-date, so adding caching would certainly seem to make the problem worse.

**Comment by tmds** [comment]
> What do we expect this to improve in practice / real-world usage?

Like on Windows, it gets rid syscalls to retrieve the length.

> with the proposed change Length will become out-of-date, so adding caching would certainly seem to make the problem worse.

The code that uses `Length` won't use it under the assumption it may change.

I'm going to close this. Thanks for sharing your opinions @adamsitnik and @stephentoub.
