### ISSUE TITLE
Segfault with net6.0 self-contained on linux-arm

### ISSUE THREAD

**Issue by cmjacobs** [dotnet/runtime#60686]
### Description

An empty console app built with net6.0 crashes with a segfault immediately upon execution.

### Reproduction Steps

build on windows:
```
dotnet new console
dotnet publish -c Release -r linux-arm --self-contained
```
deploy to target machine and run

### Expected behavior

the app should print "Hello, World!" and exit

### Actual behavior

the app crashes with a segfault

### Regression?

i built an empty net5.0 console app with the same version of the dotnet SDK (6.0.100-rc.2.21505.57) and it runs correctly on the target machine.

### Configuration

dotnet --version: 6.0.100-rc.2.21505.57
building on windows
deploying and running on ARM (Cortex A9)
OS: Angstrom Linux

### Other information

i don't have a ton of debugging tools available on the target machine but i am happy to try and provide any additional information. thanks in advance.

**Comment by janvorli** [comment]
I've tried to repro the steps on my RPI4 with arm32 Linux installed and it worked fine. Maybe something is wrong with the cross build on Windows. Let me investigate.

**Comment by grokys** [comment]
Seeing something similar with running `dotnet` 6.0 itself on an embedded arm32 machine. .NET 5 worked fine here.

```
sh-4.3# ./dotnet --info
Segmentation fault
```

```
(gdb) run
Starting program: /tmp/usb/net6/dotnet

Program received signal SIGSEGV, Segmentation fault.
0xb6fdb094 in ?? () from /lib/ld-linux-armhf.so.3
(gdb) bt
#0  0xb6fdb094 in ?? () from /lib/ld-linux-armhf.so.3
#1  0x7f556a3c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Running in a rootfs on the same machine works:

```
root@localhost:/tmp/usb/net6# ./dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-arm
 Base Path:   /tmp/usb/net6/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/tmp/usb/net6/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/tmp/usb/net6/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/tmp/usb/net6/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Machine info:

```
sh-4.3# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 795.44
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : Generic AM33XX (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000

sh-4.3# cat /etc/os-release
ID="wrlinux-small"
NAME="Wind River Linux"
VERSION="8.0.0.33"
VERSION_ID="8.0.0.33"
PRETTY_NAME="Wind River Linux 8.0.0.33"
```

**Comment by michaldobrodenka** [comment]
@grokys What is your `glibc` version?

**Comment by grokys** [comment]
@michaldobrodenka here you go:

```
GNU C Library (GNU libc) stable release version 2.22, by Roland McGrath et al.
Copyright (C) 2015 Free Software Foundation, Inc.
```

**Comment by cmjacobs** [comment]
This explains it. Just checked on our device and we too are running glibc v2.22. We are already working on spinning up a newer BSP so we'll make sure it has an updated version of glibc. Thank you @michaldobrodenka and @grokys for helping sort this out. As far as I am concerned, this issue can be closed.
