### ISSUE TITLE
[iOS/tvOS] RegexCultureTests.Match_In_Different_Cultures test failures

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#60697]
After https://github.com/dotnet/runtime/pull/60607 was merged, certain theory runs started failing in the Match_In_Different_Cultures test.  Unsure as to why at this point, but here is an example failure:

```
<test name="System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(pattern: \&quot;(?i:iI+)\&quot;, options: None, culture: , input: \&quot;abcIiİxyz\&quot;, match_expected: \&quot;Iiİ\&quot;)" type="System.Text.RegularExpressions.Tests.RegexCultureTests" method="Match_In_Different_Cultures" time="0.0057729" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\n            ↓ (pos 2)\nExpected: Iiİ\nActual:   Ii\n            ↑ (pos 2)]]></message>
          <stack-trace><![CDATA[   at System.Text.RegularExpressions.Tests.RegexCultureTests.Match_In_Different_Cultures(String pattern, RegexOptions options, CultureInfo culture, String input, String match_expected)
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1& parameters)]]></stack-trace>
        </failure>
      </test>
```

The rest can be found in https://gist.github.com/steveisok/702d94768c660462f0df76889c877e71

**Comment by stephentoub** [comment]
They were extended here to None and Compiled:
https://github.com/dotnet/runtimelab/pull/1547/files#diff-a3647ce913fdcfbfdfec36e888f7313551577a5b6f1ecf313da00d9471336003R218
But the problem in this issue is that the test is passing on Windows, Linux, and macOS... it's just failing for some inputs on iOS and Android.

**Comment by stephentoub** [comment]
@joperezr, was this addressed by your IgnoreCase change?

**Comment by joperezr** [comment]
good question, not clear. I haven't ran the iOS/tvOS tests locally before but I'll check by re-adding the test and running against Helix.
