### ISSUE TITLE
StreamReader can use ArrayPool instead of always allocating buffers

### ISSUE THREAD

**Issue by johnthcall** [dotnet/runtime#60694]
### Description
Our service is using Azure EventHub which provides a ReadOnlyMemory<byte> of the content of a message which we deserialize via Newtonsoft using an StreamReader. Currently StreamReader always allocates a buffer for both char and bytes instead of using ArrayPool.

### Analysis
Below are the allocations in StreamReader, I am not sure if there is a reason ArrayPool<byte/char>.Shared.Rent was not used as the buffer is constant from the construction and only needs minor handling for the NullStreamReader scenario.

https://github.com/dotnet/runtime/blob/7cd8f19225f2260017f65886f061fe15973a6efc/src/libraries/System.Private.CoreLib/src/System/IO/StreamReader.cs#L168-L170

**Comment by stephentoub** [comment]
We use `ArrayPool<char>.Shared` as well. 

This is a duplicate of the issues mentioned in https://github.com/dotnet/runtime/issues/29825#issuecomment-500265232.

**Comment by johnthcall** [comment]
Closing as .ctor supporting pooling should be created instead similar to #23486
