### ISSUE TITLE
unify ThrowHelper methods

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#60703]
```
dan@danmoseL:~/git/runtime/src/libraries$ grep -r --include "*.cs" "class.*ThrowHelper"
System.IO.Pipelines/src/System/IO/Pipelines/ThrowHelper.cs:    internal static class ThrowHelper
System.Text.Encodings.Web/src/System/Text/Encodings/Web/ThrowHelper.cs:    internal static class ThrowHelper
System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:    internal static partial class ThrowHelper
System.Text.Json/src/System/Text/Json/ThrowHelper.cs:    internal static partial class ThrowHelper
System.Text.Json/src/System/Text/Json/ThrowHelper.Node.cs:    internal static partial class ThrowHelper
System.Private.CoreLib/src/System/ThrowHelper.cs:    internal static class ThrowHelper
Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ThrowHelper.cs:    internal static class ThrowHelper
System.Security.Cryptography.Encoding/src/System/Security/Cryptography/Base64Transforms.cs:    internal static class ThrowHelper
System.Linq/src/System/Linq/ThrowHelper.cs:    internal static class ThrowHelper
Microsoft.Extensions.Primitives/src/ThrowHelper.cs:    internal static class ThrowHelper
Common/src/Internal/Cryptography/Windows/CryptoThrowHelper.cs:    internal static class CryptoThrowHelper
Common/src/System/Text/Json/PooledByteBufferWriter.cs:    internal static partial class ThrowHelper
System.Text.RegularExpressions/src/System/Text/RegularExpressions/ThrowHelper.cs:    internal static class ThrowHelper
System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/ThrowHelper.cs:    internal static class ThrowHelper
System.Memory/src/System/ThrowHelper.cs:    internal static class ThrowHelper
System.Collections.Concurrent/src/System/ThrowHelper.cs:    internal static class ThrowHelper
```
between them there is plenty of duplication, eg
```
dan@danmoseL:~/git/runtime/src/libraries$ grep -r --include "*.cs" "void\s*ThrowInvalidOperationException("
System.Text.Json/src/System/Text/Json/ThrowHelper.cs:        public static void ThrowInvalidOperationException(int currentDepth)
System.Text.Json/src/System/Text/Json/ThrowHelper.cs:        public static void ThrowInvalidOperationException(string message)
System.Text.Json/src/System/Text/Json/ThrowHelper.cs:        public static void ThrowInvalidOperationException(ExceptionResource resource, int currentDepth, byte token, JsonTokenType tokenType)
System.Private.CoreLib/src/System/ThrowHelper.cs:        internal static void ThrowInvalidOperationException()
System.Private.CoreLib/src/System/ThrowHelper.cs:        internal static void ThrowInvalidOperationException(ExceptionResource resource)
System.Private.CoreLib/src/System/ThrowHelper.cs:        internal static void ThrowInvalidOperationException(ExceptionResource resource, Exception e)
Microsoft.Extensions.Primitives/src/ThrowHelper.cs:        internal static void ThrowInvalidOperationException(ExceptionResource resource)
Microsoft.Extensions.Primitives/src/ThrowHelper.cs:        internal static void ThrowInvalidOperationException(ExceptionResource resource, params object[] args)
System.Memory/src/System/ThrowHelper.cs:        internal static void ThrowInvalidOperationException() { throw CreateInvalidOperationException(); }
System.Memory/tests/SequenceReader/OwnedArray.cs:        public static void ThrowInvalidOperationException()
```

We should reduce the amount of duplicated code here by at least pulling the common stuff out into a shared file.

Incidentally @BruceForstall do we have an issue for codegen to long term allow us to eliminate throw helpers? I can't find it.

**Comment by stephentoub** [comment]
This doesn't seem very valuable to me.  Is there really a lot that's duplicated? In general each library using this pattern treats it as very fluid and adds only what and exactly what it needs.  Devs would now need to think about how that impacts other libraries, and it doesn't seem like there'd be a lot of gain.

**Comment by BruceForstall** [comment]
> Incidentally @BruceForstall do we have an issue for codegen to long term allow us to eliminate throw helpers? I can't find it.

I don't recall seeing one, but I didn't check :-)  This probably affects inlining as well as other optimizations. cc @AndyAyersMS

**Comment by Joe4evr** [comment]
> > an IL optimization pass at build time
> 
> Do we have tooling for this?

@danmoseley FYI, there's been a lot of talk about that kind of thing over here: dotnet/roslyn#15929

**Comment by jaredpar** [comment]
> I think the best solution for the ThrowHelper problem would be an IL optimization pass at build time that creates them in more compact and optimal shape than humans ever would

What would the structure of such IL look like? 

> If experiments prove value perhaps Roslyn would consider an extension point for IL optimization at their emitter stage, especially if that point made debug symbols fix ups natural. 

The bar for this type of feature is **extremely** high for the same reason we restrict source generators to adding code only, not modifying it. The moment we allow extension points for modifying existing code then one of the largest value props of C# goes out the window: the ability to have a strongly spec'd language with specified behavior and rules. Arbitrary IL rewriting is essentially "everything becomes undefined" behavior land. 

> Others might use such a mechanism.

You seemed to have mis-spelled "will" as "might" and "abuse" as "use" 😄

**Comment by jeffhandley** [comment]
Closing this as it stalled without reaching agreement that it would be worthwhile.
