### ISSUE TITLE
`CultureInfo` constructor fails with string "x-TEST"

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/runtime#60737]
### Description

`CultureInfo` constructor fails with string "x-TEST"

### Reproduction Steps

```csharp
// Program.cs
using System.Globalization;
new CultureInfo("x-TEST");
```

```xml
<!-- *.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
    </PropertyGroup>
</Project>
```

Observe thrown exception "System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')".

### Expected behavior

I expect no exception to be thrown. No exception is thrown when `TargetFramework` is "net5.0". Additionally [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=net-6.0#System_Globalization_CultureInfo__ctor_System_String_) says

> starting with Windows 10, name can be any valid BCP-47 language tag.

and "x-TEST" is [a valid BCP-47 language tag](https://schneegans.de/lv/?tags=x-TEST&format=text).

### Actual behavior

When `TargetFramework` is "net6.0" then exception is thrown "System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')".

### Regression?

No exception is thrown when `TargetFramework` is "net5.0".

### Configuration

.Net 6.0 RC 2
Windows 10 Version 10.0.19043 Build 19043
x64

Other info available upon request

**Comment by tarekgh** [comment]
> and "x-TEST" is a valid BCP-47 language tag.

This is not true. Please have a look at the [BCP-47 specification](https://tools.ietf.org/search/bcp47#section-2.1) which clearly state the language part must be 2 characters at least and 3 characters at most.

```
 language      = 2*3ALPHA            ; shortest ISO 639 code
                 ["-" extlang]       ; sometimes followed by
                                     ; extended language subtags
               / 4ALPHA              ; or reserved for future use
               / 5*8ALPHA            ; or registered language subtag
```

So, the .NET 6.0 behavior you are seeing is more correct.

**Comment by tarekgh** [comment]
I'll keep this issue open as I am seeing on Linux, we have some weird behavior coming from ICU. It converts the name to `@x=test`. I'll need to look more why ICU is doing that.

**Comment by tarekgh** [comment]
I misspoke in my comment https://github.com/dotnet/runtime/issues/60737#issuecomment-949030351 as reading more in the specs in the section [2.2.1.  Primary Language Subtag](https://tools.ietf.org/search/bcp47#section-2.2.1) and I am seeing:

```
The primary language subtag is the first subtag in a language tag and
   cannot be omitted, with two exceptions:

   o  The single-character subtag 'x' as the primary subtag indicates
      that the language tag consists solely of subtags whose meaning is
      defined by private agreement.  For example, in the tag "x-fr-CH",
      the subtags 'fr' and 'CH' do not represent the French language or
      the country of Switzerland (or any other value in the IANA
      registry) unless there is a private agreement in place to do so.
      See Section 4.6.
```

which indicate `x-` can be allowed in the BCP-47. But the Unicode [BCP_47_Conformance](https://www.unicode.org/reports/tr35/#BCP_47_Conformance) doc it is clearly state the following:

```
A tag must not start with the subtag "x": thus a privateuse (eg x-abc) can only be after a language subtag, like "und"
```

Considering that and per Unicode, I believe the `x-` shouldn't be allowed in the locale names.

**Comment by tarekgh** [comment]
We shouldn't be throwing any more in .NET 8.0 on such cultures.
