### ISSUE TITLE
Huge performance difference in string.StartsWith and EndsWith between Linux and Windows for non Invariant, non en-US.

### ISSUE THREAD

**Issue by jskeet** [dotnet/runtime#6074]
Very simple code:

``` csharp
using System;
using System.Diagnostics;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Time(1);
            Time(1000000);
        }

        private static void Time(int iterations)
        {
            var stopwatch = Stopwatch.StartNew();
            for (int i = 0; i < iterations; i++)
            {
                "abcfeg".EndsWith("123");
            }
            stopwatch.Stop();
            Console.WriteLine(stopwatch.Elapsed);
        }
    }
}
```

The project.json is mostly the default from `dotnet new`:

``` json
{
  "buildOptions": {
    "emitEntryPoint": true,
    "optimize": true
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-*"
        }
      },
      "imports": "dnxcore50"
    }
  }
}
```

On both Linux (Ubuntu 15.10 and Ubuntu 16.04) the output is something like:

``` text
00:00:00.0003456
00:00:05.2664877
```

On Windows, on the same hardware, it's:

``` text
00:00:00.0000506
00:00:00.1633352
```

Version info: .NET Command Line Tools (1.0.0-preview1-002702) on Windows and Ubuntu 15.10; 1.0.0-preview2-002886 on Ubuntu 16.04.

Note that under NUnit, every equality assertion involves three `EndsWith` calls, making NUnit assertions basically horrifically expensive on Linux...

**Comment by mikes-gh** [comment]
Just scratched my head for hours on this.  Was running a console app with a 30,000 record iteration with multiple `string.EndsWith` checks. on windows it was fine on linux it killed the CPU and was much slower.

**Comment by adamsitnik** [comment]
@mikes-gh which version of .NET Core are you using?

**Comment by mikes-gh** [comment]
`<TargetFramework>netcoreapp3.1</TargetFramework>`
```
# dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
#

**Comment by iSazonov** [comment]
I think the issue should be re-reviewed since we moved to ICU on Windows.

**Comment by adamsitnik** [comment]
dotnet/coreclr#26759 and dotnet/coreclr#26621 combined together have fixed this issue. The PRs were merged in September and October 2019 so they did not make it to .NET Core 3.1, but they are part of the 5.0 release.

I've run [these benchmarks](https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Globalization/StringSearch.cs) from the dotnet/performance repository to verify that:

```cmd
git clone https://github.com/dotnet/performance
cd performance
python3 ./scripts/benchmarks_ci.py -f netcoreapp3.1 --filter '*StringSearch*Is*'
python3 ./scripts/benchmarks_ci.py -f netcoreapp5.0 --filter '*StringSearch*Is*'
```

``` ini

BenchmarkDotNet=v0.12.1, OS=ubuntu 18.04
Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.100-preview.6.20318.15
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-OKAAXU : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-QELOCB : .NET Core 5.0.0 (CoreCLR 5.0.20.30506, CoreFX 5.0.20.30506), X64 RyuJIT


```
|                      Method |       Runtime |               Options |          Mean | Ratio | Allocated |
|---------------------------- |-------------- |---------------------- |--------------:|------:|----------:|
|          IsPrefix_FirstHalf | .NET Core 3.1 |  (pl-PL, None, False) | 17,821.369 ns |  1.00 |         - |
|          IsPrefix_FirstHalf | .NET Core 5.0 |  (pl-PL, None, False) |  3,723.045 ns |  0.21 |         - |
|                             |               |                       |               |       |           |
| IsPrefix_DifferentFirstChar | .NET Core 3.1 |  (pl-PL, None, False) | 30,629.231 ns | 1.000 |         - |
| IsPrefix_DifferentFirstChar | .NET Core 5.0 |  (pl-PL, None, False) |    287.086 ns | 0.009 |         - |
|                             |               |                       |               |       |           |
|         IsSuffix_SecondHalf | .NET Core 3.1 |  (pl-PL, None, False) | 19,515.456 ns |  1.00 |         - |
|         IsSuffix_SecondHalf | .NET Core 5.0 |  (pl-PL, None, False) |  5,292.733 ns |  0.27 |         - |
|                             |               |                       |               |       |           |
|  IsSuffix_DifferentLastChar | .NET Core 3.1 |  (pl-PL, None, False) | 35,581.039 ns |  1.00 |         - |
|  IsSuffix_DifferentLastChar | .NET Core 5.0 |  (pl-PL, None, False) |    385.417 ns |  0.01 |         - |

The `pl-PL` culture is just sample culture that is not using the `en*` cultures execution path. For cases where there is a match, the code is on average 4-5 times faster. For cases where there is a mismatch in first|last character, the code is up to 100 times faster.
