### ISSUE TITLE
[release/3.1] Add area owners file to ensure that there is a packaging review on the servicing-approved prs

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#60743]
The 3.1 prs require more work around shipping out of band packages than 5.0  and 6.0. So  it would be nice to always have a packaging approval before prs getting merged.
This could be done by adding a code-owners file in the repo.

cc @ViktorHofer @ericstj @safern

**Comment by ViktorHofer** [comment]
Given that 3.1 is only in support for another ~6 months I'm closing this.
