### ISSUE TITLE
Linux: NativeLibrary.TryGetExport terminates the process when handle parameter does not a real handle to library.

### ISSUE THREAD

**Issue by josephmoresena** [dotnet/runtime#60758]
### Description

Trying to execute the NativeLibrary.TryGetExport on Ubuntu 20.04 using a fake lib handle the application just terminates.
I runned with success the same code on Windows x64 and OSX x64.

### Reproduction Steps

   ```
    Console.WriteLine("CREATE FAKE");
    IntPtr fakePtr = new IntPtr(fixture.Create<Int64>());
    if (NativeLibrary.TryGetExport(fakePtr, name, out IntPtr address))
    {
         GetPid getPid = Marshal.GetDelegateForFunctionPointer<GetPid>(address);
    }
    Console.WriteLine("FAKE CREATED");
```

### Expected behavior

`    CREATE FAKE
     FAKE CREATED
`

### Actual behavior

`    CREATE FAKE
`

**Comment by AaronRobinsonMSFT** [comment]
> It is by design that it is crashing when given random input.

Agree. I don't see how we could support this in a way that didn't add overhead in the typical case. Providing random values is undefined and so I'd argue the current behavior is acceptable.

**Comment by elinor-fung** [comment]
We should update the docs to clarify that passing in a non-null invalid handle  is not supported / undefined behaviour.
