### ISSUE TITLE
[Loc]With .NET6 RTM SDK installed, the texts in CLI are partly unlocalized after running "dotnet --info" 

### ISSUE THREAD

**Issue by vdanche** [dotnet/runtime#60756]
### Description

the texts in CLI are partly unlocalzied after running "dotnet --info" 

### Reproduction Steps

Install NET6 RTM SDK--6.0.100-rtm.21515.2(runtime-6.0.0-rtm.21514.7) on local OS
run dotnet --info

### Expected behavior

Strings are localized well

### Actual behavior

the texts in CLI are partly unlocalized after running "dotnet --info" 

E.g TK
![image](https://user-images.githubusercontent.com/65637796/138379713-87e57541-5e30-4347-b5c1-fecc753c8ad4.png)

**Comment by WenJunJi01** [comment]
Similar issue occurred with .NET 7 SDK installed:
![image](https://user-images.githubusercontent.com/87680983/167241939-3b070a2b-0b46-48ad-8306-6ea3276d1edd.png)

**Comment by vdanche** [comment]
Still repro on VS 17.4 preview 3 + net7 RC2 SDK(7.0.100-rc.2.22471.15)
e.g SC
![image](https://user-images.githubusercontent.com/65637796/192210401-13f3aea2-5e4a-4bf9-ad4b-478e7e345363.png)

**Comment by vitek-karas** [comment]
Yes - this is expected. We didn't implement host localization in .NET 7.

**Comment by vdanche** [comment]
@vitek-karas Thanks your reply. if this is expected in NET6 and NET7, hence we'll close it
