### ISSUE TITLE
dotnet 6 rc.2: libhostpolicy.dylib library load disallowed by system policy

### ISSUE THREAD

**Issue by 2mol** [dotnet/runtime#60760]
### Description

`dotnet 6.0.0-rc.2.21480.5` doesn't fully work on my M1 mac. 

Executing just `dotnet` works, but `dotnet --version` throws

```
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib: code signature in (/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5]
```

But the files in question are signed, so it's specifically the library load that seems to be the problem:

```
codesign -s - /usr/local/share/dotnet/dotnet
```

-> `/usr/local/share/dotnet/dotnet: is already signed`

```
codesign -s - /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib
```

-> `/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib: is already signed`

I found issues that seem related but didn't help, e.g. https://github.com/dotnet/runtime/issues/49609 

### Reproduction Steps

On an M1 mac:

1. Download `dotnet-sdk-6.0.100-rc.2.21505.57-osx-arm64.tar.gz` from https://dotnet.microsoft.com/download/dotnet/6.0
2. Unpack the contents into `/usr/local/share/dotnet/`
3. Run `/usr/local/share/dotnet/dotnet --version`

Notes:

- there is NOT a conflicting (5.0 or other version) of the SDK installed to the best of my knowledge
- The issue doesn't necessarily pertain to just M1, since the code signing should be completely orthogonal to that. But that's the only machine I have right now

### Expected behavior

The version of the dotnet sdk is displayed.

### Actual behavior

A popup will open, suggesting that you put the executable into thr trash bin.

The commandline output will show

```
Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib, 1): no suitable image found.  Did find:
	/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib: code signature in (/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5/libhostpolicy.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.0-rc.2.21480.5]
```

**Comment by ericstj** [comment]
I don't know what would cause this.  We noticed some behavior with replacing `dotnet` but above mentions that this was not done (no other installers).

@2mol are you still reproducing this problem with the final bits?

**Comment by 2mol** [comment]
I haven't had any problem with the final releases for a while now, so I think this can be considered closed :)

**Comment by cxssmira** [comment]
I've also just experienced the same bug - same environment & reproduced steps, no other dotnet installs. I also tried extracting it to `~/Applications` but with no change. Version 6.0.1

**Comment by dominoFire** [comment]
Happened to me. I tried downloaded dotnet sdk from Microsoft Edge. Failed with error above. Downloading dotnet sdk from Safari solved the problem for me.
