### ISSUE TITLE
Allow customizing letter case size when serializing Unicode characters

### ISSUE THREAD

**Issue by Misiu** [dotnet/runtime#60762]
### Description
Currently, when using `JsonSerializer` Unicode characters are escaped using upper case characters,
so `Zażółć gęślą jaźń` is escaped as `Za\u017C\u00F3\u0142\u0107 g\u0119\u015Bl\u0105 ja\u017A\u0144`.

When connecting to PHP backend I noticed that the output of PHP `json_encode` is different.

C#:
```
{"a":"Za\u017C\u00F3\u0142\u0107 g\u0119\u015Bl\u0105 ja\u017A\u0144"}
```
PHP:
```
{"a":"Za\u017c\u00f3\u0142\u0107 g\u0119\u015bl\u0105 ja\u017a\u0144"}
```

In C# I get `\u017C`, but in PHP I get `\u017c` (capital **C** vs lower **c**).
After some digging, I noticed that Newtonsoft is returning the correct (expected by me) character size.

`JavaScriptEncoder` uses https://github.com/dotnet/corefx/blob/bd30a3f458b6b0f71204fc3630b2d29b780c4167/src/System.Text.Encodings.Web/src/System/Text/Encodings/Web/HexUtil.cs#L30 which uses uppercase and sadly this isn't configurable.

### Configuration

Test case using System.Text.Json:
```
var test = new Test
{
   A = "Zażółć gęślą jaźń"
};
var jsonString = JsonSerializer.Serialize(test);

public class Test
{
   [JsonPropertyName("a")]
   public string A { get; set; }
}
```
Newtonsoft:
```
string newtonsoftOutput = JsonConvert.SerializeObject(test , new JsonSerializerSettings
{
    StringEscapeHandling = StringEscapeHandling.EscapeNonAscii,
    ContractResolver = new CamelCasePropertyNamesContractResolver()
});
```
PHP:
```
$data = array('a'=>'Zażółć gęślą jaźń');
$data = json_encode($data);
echo $data;
```

**Comment by Misiu** [comment]
@Tornhoof because regex replace can cause unwanted behaviour - https://stackoverflow.com/questions/69675115/httpclient-and-system-text-json-jsonserializer-and-php-different-character-size?noredirect=1#comment123168070_69675115

**Comment by eiriktsarpalis** [comment]
> because regex replace can cause unwanted behaviour

I mean that comment is merely pointing out a corner case, but that doesn't mean it's impossible to get right. 

I don't believe this use case justifies controlling the casing of escaped unicode: the produced output is valid according to spec and generating JSON that is byte-by-byte identical to Json.NET is not a goal of System.Text.Json. In general, I would not recommend using JSON from the STJ serializer to generate hashes as future releases might change the byte-by-byte encoding in subtle ways.
