### ISSUE TITLE
Erratic behavior marshaling derived classes to native code

### ISSUE THREAD

**Issue by f2bo** [dotnet/runtime#60803]
I'm currently building a managed wrapper for a native library where certain parts of the API require unions. I initially modeled these unions using `LayoutKind.Explicit`. This is working, however, certain members of the union are strings and require special handling when using a fixed layout that I would rather avoid. As an alternative, I'm looking at implementing these unions as a class hierarchy. However, I'm seeing inconsistent behavior when these child classes are marshaled to the unmanaged side.

Below, I present the behavior I observe when invoking a method in a native library using P/Invoke as a series of cases that either succeed or fail. 

UPDATED:
**Tested with  .NET v5.0.11**

#### Sample Native Library
```C++
#include <string.h>

// NOTE: for simplicity, not using a union here because it's not relevant to the problem
struct Foo {
    int discriminator;
    const char* name;
};

extern "C" __declspec(dllexport) bool TestMethod(Foo* ptr)
{
    if (5 != ptr->value) return false;
    if (strcmp("abcdef", ptr->name) != 0) return false;

    return true;
}
```

### Case 1: No inheritance (SUCCESS)
This does not using any inheritance but just to make sure that it marshals the data correctly, which it does.

```C#
[StructLayout(LayoutKind.Sequential)]
public class FooConsolidated
{
    public int discriminator;
    public string name = "abcdef";
    public FooConsolidated() => discriminator = 5;
}

[DllImport("TestLibrary")][return: MarshalAs(UnmanagedType.U1)]
private static extern bool TestMethod([In] FooConsolidated foo);

public static void Main()
{
    Console.WriteLine(TestMethod(new FooConsolidated()) ? "SUCCESS" : "FAILURE");
}
```
### Case 2: P/Invoke declares parameter as base class (FAILURE)
Using inheritance. The method declares the parameter as `FooBase` but it's invoked with a `Foo` instance. The data is not marshaled correctly to the native side and it fails.

```C#
[StructLayout(LayoutKind.Sequential)]
public abstract class FooBase
{
    public int discriminator;
}

[StructLayout(LayoutKind.Sequential)]
public class Foo : FooBase
{
    public string name = "abcdef";
    public Foo() => discriminator = 5;
}

[DllImport("TestLibrary")][return: MarshalAs(UnmanagedType.U1)]
private static extern bool TestMethod([In] FooBase foo);

public static void Main()
{
    Console.WriteLine(TestMethod(new Foo()) ? "SUCCESS" : "FAILURE");
}
```
### Case 3: P/Invoke declares parameter as derived class (SUCCESS)
Same as Case 2, except that the P/Invoke method is changed to declare the parameter as the derived class `Foo`. The data is marshaled correctly and it succeeds.

```C#
...
[DllImport("TestLibrary")][return: MarshalAs(UnmanagedType.U1)]
private static extern bool TestMethod([In] Foo foo);
...
```

### Case 4: P/Invoke declares parameter as IntPtr and use manual marshaling (SUCCESS)
Just out of curiosity, using `Marshal.StructureToPtr` to manually marshal the `Foo` instance as an `IntPtr`. It succeeds.

```C#
[DllImport("TestLibrary")][return: MarshalAs(UnmanagedType.U1)]
private static extern bool TestMethod(IntPtr fooPtr);

public static void Main()
{
    System.IntPtr fooPtr = IntPtr.Zero;
    
    try
    {
        fooPtr = Marshal.AllocHGlobal(Marshal.SizeOf<Foo>());
        Marshal.StructureToPtr(new Foo(), fooPtr, false);
        Console.WriteLine(TestMethod(fooPtr) ? "SUCCESS" : "FAILURE");
    }
    finally
    {
        Marshal.DestroyStructure<Foo>(fooPtr);
        if (fooPtr != IntPtr.Zero) Marshal.FreeHGlobal(fooPtr);
    }
}
```
### Case 5: P/Invoke declares parameter as base class which was modified add a new field (SUCCESS)
Same as Case 2, except that it adds a new boolean field to the base class. Note that the P/Invoke parameter is declared with a `FooBase` type, which had **previously failed** for Case 2. This time, with the added field in the base class, it succeeds.

#### Native Library

```C++
...
struct Foo {
    int discriminator;
    bool enabled;                       // <== ADDED THIS FIELD
    const char* name;
};

extern "C" __declspec(dllexport) bool TestMethod(Foo* ptr)
{
    if (5 != ptr->discriminator) return false;
    if (strcmp("abcdef", ptr->name) != 0) return false;
    if (!ptr->enabled) return false;    // <== VALIDATE NEW FIELD

    return true;
}
...
```

#### Managed Code
```C#
...
[StructLayout(LayoutKind.Sequential)]
public abstract class FooBase
{
    public int discriminator;
    [MarshalAs(UnmanagedType.U1)] public bool enabled = true; // <== ADDED THIS FIELD
}
...
```

### Case 6: Base modified to change the data type of a field (FAILURE)
This is the same as the previous case, except that it changes the data type of the previously added field in the base class from bool to byte. The marshaler does not like it and it fails again.

```C#
...
[StructLayout(LayoutKind.Sequential)]
public abstract class FooBase
{
    public int discriminator;
    public byte enabled = 1;        // <== CHANGED THIS FIELD
}
...
```
### Case 7: Base modified to add new string field (SUCCESS)
This adds an additional string field to the base class for Case 6, which previously failed. It now succeeds again.
```C++
struct Foo {
    int discriminator;
    //bool enabled;
    char enabled;
    const char* message;                                // <== ADDED THIS FIELD
    const char* name;
};

extern "C" __declspec(dllexport) bool TestMethod(Foo* ptr)
{
    if (5 != ptr->discriminator) return false;
    if (strcmp("abcdef", ptr->name) != 0) return false;
    if (!ptr->enabled) return false;
    if (strcmp("XYZ", ptr->message) != 0) return false; // <== VALIDATE NEW FIELD

    return true;
}
```

```C#
...
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
public abstract class FooBase
{
    public int discriminator;
    public byte enabled = 1;
    public string message = "XYZ";          // <== ADDED THIS FIELD
}
...
```
Naturally, I'm a bit confused by all this. My guess is that the seemingly erratic behavior is related to whether the base class is blittable or not. Hence the change from success with a bool field, to failure after changing its data type to byte, and then back to success when adding a string field. Either that, or I'm likely breaking some P/Invoke rule that I'm not aware of.

In any case, I'll be grateful to anyone that can provide an explanation.

**Comment by f2bo** [comment]
I'd hoped that an analyzer could somehow detect the conditions that cause this problem (base blittable / derived not-blittable) and only flag these specific cases but I can see that it would be difficult to determine the exact type being passed in as an argument.

Thanks!

**Comment by AaronRobinsonMSFT** [comment]
Closing this as I don't see any need for further action from the runtime side.
