### ISSUE TITLE
[UnmanagedCallersOnly] is not supported on inner functions in Blazor

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#60800]
### Description

When compiling a Blazor WASM app with nested functions using the `[UnmanagedCallersOnly]` attribute, the pinvoke generation fails with the error of invalid symbol name:

```
void wasm_native_to_interp_BlazorWebAssemblyDemos_MyClass_<.ctor>g__OnCallback|3_0 (int arg0,int arg1) { 
```

### Reproduction Steps

Inner function:

```cs
class MyClass {
    public MyClass(object args) {
        // ...

        [UnmanagedCallersOnly]
        static void OnCallback(bool is10x, nint state)
        {
        }
    }
}
```

Error with invalid symbol name:

```
void wasm_native_to_interp_BlazorWebAssemblyDemos_MyClass_<.ctor>g__OnCallback|3_0 (int arg0,int arg1) { 
```

### Expected behavior

Compile

### Actual behavior

Error

### Known Workarounds

Move the function to an outer/class level.

### Configuration

.NET 6.0.100-rtm.21521.3
Windows 11 x64

**Comment by lambdageek** [comment]
Should also check that we mangle the `+` in nested class names properly, too.
