### ISSUE TITLE
ETW event Method/LoadVerbose contains wrong method signature for methods receiving function pointer (C#9) 

### ISSUE THREAD

**Issue by Temp1ar** [dotnet/runtime#60829]
### Description

For the method that receive function pointer I'm getting an LoadVerbose event with the value of MethodSignature representing the function pointer signature, not the actual method signature.

### Reproduction Steps

1. Compile console application for .net 6.0 with the following code
```
namespace TestSignatures;

unsafe class Example
{
  public void Foo(Action<int> a, delegate*<out double, in int, bool> f)
  {
    var i = 10d;
    var j = 1;
    a(42);
    Thread.Sleep(200);
    f(out i, in j);    
  }
    
  public void Foo(Action<int> a, in int b, out int c, ref int d)
  {
    var i = 10d;
    var j = 1;
    a(42);
    Thread.Sleep(200);
    c = j;
    d = b;
  }
}
  
public class Program
{
  public static void Main(string[] args)
  {
    unsafe 
    {
      var e = new Example();
      e.Foo(i => { }, &Method);
      var b = 0;
      var c = 0;
      var d = 0;
      e.Foo(i => { }, b, out c, ref d);
    }
  }
    
  private static bool Method(out double d, in int i) 
  {
    d = 10d;
    Thread.Sleep(200);
    return true;
  }
}

```
2. Build application
3. Profile application with the PerfView or any other ETW profiler
4. Check the Method/LoadVerbose events, specifically the MethodSignature string field for methods with the name "Foo"

### Expected behavior

I expect to see signatures like these:
```
instance void  (class System.Action`1<int32>,bool(required_modifier System.Runtime.InteropServices.OutAttribute float64&,required_modifier System.Runtime.InteropServices.InAttribute int32&))
instance void  (class System.Action`1<int32>,int32&,int32&,int32&)
```

### Actual behavior

I see following signatures:
```
bool(required_modifier System.Runtime.InteropServices.OutAttribute float64&,required_modifier System.Runtime.InteropServices.InAttribute int32&)
instance void  (class System.Action`1<int32>,int32&,int32&,int32&)
```

### Regression?

I believe it's broken since the addition of the function pointers to the language, but I'm not sure.

### Configuration

- .NET 6.0
- Windows 10
- x64
- I doubt

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS PTAL.

**Comment by AndyAyersMS** [comment]
These events are generated by the runtime, so updating the area path. 

@mangod9 I'm probably not the best person to fix this, can you reassign?

**Comment by AaronRobinsonMSFT** [comment]
I see what is going on here. I will take this.
