### ISSUE TITLE
[API Proposal]: Expose TryRead() as public on JsonConverter

### ISSUE THREAD

**Issue by rmja** [dotnet/runtime#60904]
### Background and motivation

The current JsonConverter has an `interanal virtual OnTryRead()` [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L129).
For custom converter implementations that call e.g. `reader.TrySkip()` it would be neat to be able to actually return `false` if the conversion fails.
The suggestion is motivated by this SO question: https://stackoverflow.com/questions/63038334/how-do-i-handle-partial-json-in-a-jsonconverter-while-using-deserializeasync-on

### API Proposal

The proposal is to change the visibilty on `OnTryRead()` (and maybe `OnTryWrite()`) to `public` instead of `internal`, but without the `ReadStack parameter`. Something like:

```C#

public class JsonConverter<T>
{
    public virtual bool TryRead(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, out T? value);
}
```

### API Usage

```C#
void Run()
{
    Stream someHugeStream = Request.Body;  // This stream is so large that it causes `Utf8JsonReader.IsFinalBlock == false` when calling custom converters.

    var options = JsonSerializerOptions() { Converters = new MyCustomObjectConverter() };

    JsonSerializer.DeserializeAsync<List<MyCustomObject>>(someHugeStream, options);
}

public class MyCustomObjectConverter : JsonConverter<MyCustomObject>
{
    ...
    public override bool TryRead(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, out MyCumstomObject value)
    {
      // Handle case where `reader.IsFinalBlock == false`, for example by calling `reader.TrySkip()`
      ...
      if (reader.trySkip())
      {
          value = null;
          return false;
      }
      ...
      return true;
    }
}
```

**Comment by eiriktsarpalis** [comment]
Per the request in #29902, we should consider offering similar methods on the `JsonSerializer` level. cc @davidfowl

**Comment by eiriktsarpalis** [comment]
Closing in favor of #63795.
