### ISSUE TITLE
Provide File System Support for Blazor wasm

### ISSUE THREAD

**Issue by yamachu** [dotnet/runtime#60907]
### Is your feature request related to a problem? Please describe.

I'm trying to use Native dependencies support for Blazor WebAssembly.
https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-2/#native-dependencies-support-for-blazor-webassembly-apps
The target library contains a system call to manipulate file descriptors.
I could not see from the interface of blazor wasm supporting File System.

### Describe the solution you'd like

Blazor wasm implements FileSystem support such as emscripten provides.
https://emscripten.org/docs/api_reference/Filesystem-API.html

It seems like it would be very good to be able to access the FileSystem from both JS and C#.
You can see from the interface of blazor wasm that ASPNETCORE currently supports File System.

**Comment by lewing** [comment]
@yamachu I'm not sure what you are asking for exactly, there is vfs support, are you requesting a way to populate the filesystem?

**Comment by yamachu** [comment]
Thanks @lewing .
I'm sorry for the confusion.
I misunderstood that the FS that can be accessed from System.IO and from Native Dependencies (such as C library) are different.
Therefore, it seems that what I require is already there.

**Comment by lewing** [comment]
no problem, i'm interested in what you are trying to do and figuring out how we can help.
