### ISSUE TITLE
framework 5.0 is not installed (?? but is)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#60978]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/framework-50-is-not-installed--but-i/1532556)._

---
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      3.1.19 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[512] dotnet.exe' has exited with code -2147450730 (0x80008096).

Note:
Framework 5.010 was installed on VS 2019

---
#### Feedback Bot on 9/17/2021, 01:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Lautas Nicolae on 9/17/2021, 07:56 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by vitek-karas** [comment]
> Framework 5.0.10 was installed on VS 2019

Not sure what this exactly means, but you can check easily by running `dotnet --info` from command line. It should list all installed .NET SDKs and runtimes.

Please note that on Windows there are two versions of .NET, the 32bit (x86) and the 64bit (x64). It is possible that you installed 5.0 only for x86 in which case x64 apps won't see it. You can check this by running `C:\Program Files\dotnet\dotnet --info` and `C:\Program Files(x86)\dotnet\dotnet --info`. These will print out x64 and x86 respectively.
