### ISSUE TITLE
Non-breaking space in Currency Formatting

### ISSUE THREAD

**Issue by ncagr** [dotnet/runtime#61002]
### Description

It appears the formats in [Number.Formatting.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Number.Formatting.cs) have space ('\u0020') instead of [non breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) ('\u00A0') according to the [CLDR](https://unicode-org.github.io/cldr/ldml/tr35-numbers.html#Currencies). Also the European Union for Euro sign specifically [instruct to use hard space](http://publications.europa.eu/code/en/en-370303.htm#position)

### Reproduction Steps

```cs
decimal dec = -1;
string s = dec.ToString( "C0", new CultureInfo( "fr-FR" ) );
```
The value of `s` is =`"-1 €"` and the character between `-1` and `€` is space and not Non-breaking space, which means in some layouts the value and the currency symbol, may appear in different lines after wrap

### Expected behavior

A Non-breaking space should **Join** the value and the currency symbol to one textual object

### Actual behavior

A space is used to **separate** a value with the currency symbol in two textual objects

### Regression?

No, it appears that the .NET framework has [the same wrong behavior](https://stackoverflow.com/questions/18743595/currency-formatting-in-net-gives-white-space-between-amount-and-currency/18745215). So this is a breaking change

### Known Workarounds

A. Do not use Currency ("C") formatting but Numeric ("N") and apply the CLDR patterns manually. They are some locales though where Currency and Numeric formatting is using different grouping rules or Decimal or Grouping symbols, but they are rare.

B. Format as usual and then replace any space character with the Non Breaking Space. Slow with at least one additional allocation

### Configuration

.NET 5.0, Windows 10 x64

**Comment by tarekgh** [comment]
Thanks @ncagr for your report. 

Unfortunately, this will be a major breaking change which can break many users who depend on the current behavior. Parsing would be a big issue if we changed this behavior. The current behavior existed for long time and didn't see users complained about. We should wait to see if there is any strong ask to this new behavior and then consider it. For now, I would say let's keep the current behavior. I am closing the issue but feel free to respond back with question.

**Comment by ncagr** [comment]
I do understand this and since we already having implemented workaround A, I don't have anything to add.

Perhaps in the future you may examine the possibility to add the patterns directly (as string properties) in the NumberFormatInfo class and not through an index ( CurrencyNegativePattern, PercentPositivePattern etc ), so someone can set them to a different value.

**Comment by tarekgh** [comment]
@ncagr what I meant in the future if we see a demand on that, we can construct the currency pattern with the non-breaking space. Your workaround around is reasonable to me but the easier workaround would be use [TryFomrat](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tryformat?view=net-5.0) which can format into a span and then you can replace the space with the non-breaking spacing. That should avoid the extra allocation. Also, the formatted numbers usually small numbers so the perf wouldn't affect much.
