### ISSUE TITLE
XDocument.LoadAsync

### ISSUE THREAD

**Issue by sjd2021** [dotnet/runtime#61013]
### Description

When running .NET Core 3.1 on Linux in Elastic Beanstalk (which seems to target the latest: 3.1.20 based on the release notes here: https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2021-10-21-linux.html), I still see the issue mentioned here: https://github.com/dotnet/runtime/issues/29464 with SaveAsync and LoadAsync.

For support of a legacy application, I need to use LoadAsync and currently have to manually override the feature so that synchronous stream reads are allowed. I don't want to do this, and I don't have this problem locally. So my question is: Why would this problem exist in the latest version of .NET Core 3.1.x if the issue is closed? Was it only fixed in 5? Someone asked the question but no one answered it before the issue was closed. Also, why would I not have this issue locally?

### Reproduction Steps

Call XDocument.LoadAsync on the request body in an action

### Expected behavior

No exception

### Actual behavior

Exception with  "System.InvalidOperationException: Synchronous operations are disallowed" as a message

### Regression?

It works locally and did not happen until .NET Core 3.x 

### Known Workarounds

```
            var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();

            if (syncIOFeature != null)
            {
                syncIOFeature.AllowSynchronousIO = true;
            }
```

### Configuration

.NET Core 3.1.20 (presumably, basing this on the release notes and the fact that we've deployed since Oct. 21st) in Elastic Beanstalk on Linux

**Comment by danmoseley** [comment]
Hi @sjd2021 yes, this feature was new in 5.0. Is moving to 5.0 an option (or 6.0 will be released very soon)?  You should just need to retarget your app -- your dependencies ought to "just work".


Here's how to tell BTW, the 3.1 code and earlier was in https://github.com/dotnet/corefx:
```sh
C:\git\corefx>git status
## release/3.1...upstream/release/3.1

C:\git\corefx>git log -SIAsyncDisposable **/ref/**Xml*cs

C:\git\corefx>
```
```
C:\git\runtime>git status
## main...upstream/main

C:\git\runtime>git log -SIAsyncDisposable **/ref/**Xml*cs
commit 77fab0bddda1872c9674f3dd914610d7d6163f53
Author: buyaa-n <buyankhishig.namnan@microsoft.com>
Date:   Tue Apr 28 14:50:40 2020 -0700

    Implement IAsyncDisposable for XmlWriter (#35233)

    * Update XmlWriter to implement IAsyncDisposable
 ```

**Comment by sjd2021** [comment]
@danmoseley  
Thank you. Unfortunately, we're not able to use .NET 5 (trust me, I'm itching to as a fan of all the new features) due to it not being LTS. I'm excited for .NET 6. I hope we'll be able to migrate by early next quarter (maybe sooner if everything plays well with .NET Standard 2.0 libs, not sure), but for now it looks like we'll have to use the `IHttpBodyControlFeature`.

**Comment by danmoseley** [comment]
@sjd2021 it's[ only 10 days,](https://www.dotnetconf.net/) of course, and will be LTS immediately.

Can you pilot your app today - in test, if not in production? In case there is some bug or issue we can take a look at. 

> if everything plays well with .NET Standard 2.0 libs

We work hard to make sure that "just works"  but there's no proof like trying it out.

**Comment by danmoseley** [comment]
Meantime I'm going to close this, as there are no plans to back-port (there is a very high bar for backporting changes, and anyway we can't easily backport new API)
