### ISSUE TITLE
Mono CI Utilization Improvements

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#61017]
Starting with https://github.com/dotnet/runtime/pull/60727, we have scaled back the amount of mono tests run per PR.  This issue tracks additional follow up work & potential future enhancements.

- [x] [Create separate yml that can trigger full test runs on demand](https://github.com/dotnet/runtime/issues/61132)
- [ ] Detect changes in library projects and run them as part of the smoke test (e.g. a change in System.Collections runs its tests)
- [x] Apply changes to apple mobile configurations after https://github.com/dotnet/runtime/pull/59503 lands
- [ ] Allow developers to provide parameters (e.g a list of library suites to run) when manually triggering builds
- [x] Move most / all of runtime staging legs to the runtime pipeline (runtime-extra-platforms)
- [ ] Create bisect scripts or targets that help with post PR failures

**Comment by safern** [comment]
>  Create separate yml that can trigger full test runs on demand

maybe some of the legs in these optional yaml should run always based on path changes?

**Comment by akoeplinger** [comment]
> maybe some of the legs in these optional yaml should run always based on path changes?

Yeah though I think I'd prefer extending evaluate-changed-paths.sh so that it outputs more fine grained variables that we can use in runtime.yml to trigger the full runs.

**Comment by safern** [comment]
> Yeah though I think I'd prefer extending evaluate-changed-paths.sh so that it outputs more fine grained variables that we can use in runtime.yml to trigger the full runs.

Yeah that'd be great. The infra should already support more variables, we would just need to add extra entries on the yml include/exclude paths parameter to the script.
