### ISSUE TITLE
Convert empty string to number in base throws AOORException

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/runtime#61036]
### Description

Throwing [ArgumentOutOfRangeException](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception) is inconsistent with `[CONVERT]:: TOINT32( [STRING]:: EMPTY )` and frivolously exposes the internals.  Also this exception should never occur in production code.

### Reproduction Steps

```powershell
[INT] '0X'
```

### Expected behavior

FormatException

### Actual behavior

ArgumentOutOfRangeException

Indeks był spoza zakresu. Musi mieć wartość nieujemną i mniejszą niż rozmiar kolekcji.
Nazwa parametru: startIndex

   w System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   w System.Convert.ToInt32(String value, Int32 fromBase)

### Regression?

Wrong on .NET Framework 4.8.4420.0 too.

### Known Workarounds

```powershell
'0X' | % { IF ($_ -EQ '0X') { [CONVERT]:: TOINT32( [STRING]:: EMPTY ) } ELSE { [INT] $_ }}
```

### Configuration

[Mono 6.5.0](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world)
Unix 1.0.0.0
x86

**Comment by stephentoub** [comment]
> Also this exception should never occur in production code.

That would be the fault of the consuming application code.  Tons of APIs throw this exception to signal misuse.

> Repro

I don't understand the repro or the cited problem. Can you please share a simple C# repro of what you believe to be a problem?

**Comment by yecril71pl** [comment]
```csharp
try { _ = Convert .ToInt32 (String .Empty, 0X10); } catch (FormatException _) { /* OK */ }
````

**Comment by stephentoub** [comment]
The exception means an invalid argument was passed into the method.  String.Empty is an invalid argument here. It's documented as such:
```
ArgumentOutOfRangeException
value is Empty.
```

**Comment by yecril71pl** [comment]
Yes, I understand it is documented.  It makes it slightly less wrong, but only slightly.

> The exception that is thrown when the value of an argument is outside the allowable range of values as defined by the invoked method.

But there is not such thing as _allowable range of values_ for the text to be converted.

> Typically, an [ArgumentOutOfRangeException](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception) results from developer error.

But it is _not_ a developer error to pass an empty string (which may have come from God knows where) to a method that expects to handle all kinds of wrong input by throwing exceptions.

**Comment by stephentoub** [comment]
> But it is not a developer error to pass an empty string

By definition it is.

> to a method that is expected to handle all kinds of wrong input by throwing exceptions.

It's throwing an exception for wrong input.

> It makes it slightly less wrong, but only slightly.

It's behaving as designed.  Most of the built-in parsers throw for null or empty string inputs (unless using the Try variants, which return false).  I think you're disagreeing with the design, but that is your opinion and doesn't make it "wrong".

**Comment by yecril71pl** [comment]
> It's throwing an exception for wrong input.

But it throws the wrong one.  Besides:

```powershell
[CONVERT]::TOINT32( $NULL ) -EQ 0X0
# OK
[CONVERT]::TOINT32( [STRING] $NULL ) -EQ 0X0
# Input string was not in a correct format.
[CONVERT]::TOINT32( $NULL, 10 ) -EQ 0X0
# Index was out of range. Must be non-negative and less than the size of the collection.
# How does this error message relate to what he coder intended?  How does it help the coder?
```

If this is not a mess then I do not know what is.

**Comment by stephentoub** [comment]
> But it throws the wrong one.

It throws the one it's documented to throw.  We can debate whether it should have thrown ArgumentOutOfRangeException or FormatException, but it's been throwing an argument exception forever, it's documented to throw an argument exception, and there exists code that expects it to throw an argument exception.  If we were designing it from scratch, maybe we'd do it differently; at present, I do not believe it's worth changing.

> You seem to assume that every coder out there knows the whole API by heart, including special cases and exceptions, however inconsistent and illogical you designed them to be. I assure you this is not the case and the alternative of checking those details each time when we call an API function would put us out of business in no time.

I am not assuming that.  I am assuming that there are millions of developers using .NET with billions of lines of .NET code and that we need to have a really good reason for making breaking changes, which changing one exception type to another unrelated exception type is.  Improved consistency in a case like this simply isn't a good enough reason.

**Comment by yecril71pl** [comment]
> I am not assuming that. I am assuming that there are millions of developers using .NET with billions of lines of .NET code and that we need to have a really good reason for making breaking changes, which changing one exception type to another unrelated exception type is. Improved consistency in a case like this simply isn't a good enough reason.

For the record, the reason is usability, not consistency.  I would not make such a fuss about that if it were for consistency only.

**Comment by jeffhandley** [comment]
As noted on this long ago, we recognize the specific exception thrown here is arguably not ideal, but we cannot justify making a change to the exception type as it would be a breaking change that would surely have substantial impact due to the broad usage of this API. We'll leave it as-is.
