### ISSUE TITLE
Int32Converter tolerates outrageous syntax 0X+FFFFFFFF

### ISSUE THREAD

**Issue by yecril71pl** [dotnet/runtime#61039]
### Description

[Int32Converter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfromstring) should not accept a syntax with a `+` sign following the hexadecimal prefix.

### Reproduction Steps

```powershell
+ '0X+FFFFFFFF'
```

### Expected behavior

[FormatException](https://docs.microsoft.com/en-us/dotnet/api/system.formatexception)

### Actual behavior

`-1`

### Regression?

Wrong under .NET Framework 4.8.4420.0 too.

### Known Workarounds

```powershell
'0X+FFFFFFFF' | % {  IF ($_ -LIKE '0X+*' ) { [CONVERT]:: TOINT32( $_, 0X10 ) } ELSE { + $_ } }
```

### Configuration

.NET 5.0.11
 Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0
[ENVIRONMENT]:: IS64BITOPERATINGSYSTEM

**Comment by stephentoub** [comment]
Can you share a complete C# repro?

**Comment by yecril71pl** [comment]
> Can you share a complete C# repro?

```csharp
Debug .Assert (0XF ==
new System .ComponentModel .Int32Converter() .ConvertFrom ("0X+F"
     ))
;
```

**Comment by stephentoub** [comment]
Thanks.  Yes,  the base BaseNumberConverter strips off the 0x and then the remainder is happily parsed by the derived Int32Converter. I'm not seeing a lot of motivation to break this behavior.

**Comment by yecril71pl** [comment]
We write a script that processes strings.  They expect the script to do one thing when the string is a valid number and another thing when it is not.  We do not think that `0X+F` is a valid number.  We suppose nobody thinks it is, especially given that `0X-F` is not.  We do not want to detect and handle this anomaly separately in the script.

**Comment by stephentoub** [comment]
> Therefore, I disapprove of your using the verb break here.

Anything that changes behavior is considered breaking; someone could have been relying on it.  At that point the decision isn't about whether it could break someone, but about whether the risk is worth the reward.  I do not see the reward here.  This behavior has existed for 20 years, there's no performance benefit to breaking it, this is the first complaint I've heard about it, someone could be relying on it, and you can easily detect and handle this in the calling code.

**Comment by maryamariyan** [comment]
seems like it's safe to close this issue.
