### ISSUE TITLE
dotnet support android sdk, runtime

### ISSUE THREAD

**Issue by amro93** [dotnet/runtime#61031]
Since Android OS is based in Linux, it will be a game changer if it's possible to build and run "Hello World" dotnet console application on Android OS, without MAUI (Xamarin)

**Comment by amro93** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

@akoeplinger

**Comment by huoyaoyuan** [comment]
The difference is that mobile OS may not expose "console" directly. AFAIK some console inputs are actually redirected to debugger connected from the host PC.

**Comment by amro93** [comment]
At least Runtime support will be great, 
I saw some articles for how to run NodeJs directly on Android, it could be not easy, but I think it's possible.

**Comment by marek-safar** [comment]
You can do that with .net6, check out https://github.com/dotnet/runtime/tree/main/src/mono/sample/Android

**Comment by amro93** [comment]
> You can do that with .net6, check out https://github.com/dotnet/runtime/tree/main/src/mono/sample/Android

Definitely this is helpful, it would be great if there's a sample demo that we can follow.
I know it's not an easy task as android os is not created for development, hopefully I can see this feature in the future.
Thanks.
