### ISSUE TITLE
DateTime.Parse throw FormatException in centos7.9

### ISSUE THREAD

**Issue by yedajiang44** [dotnet/runtime#61038]
### Description

DateTime.Parse throw FormatException in centos7.9

### Reproduction Steps

runtime: net5.0

run code on centos7.9

```
var date = DateTime.Parse("19-12-04 03:29:02");
```

### Expected behavior

get date

### Actual behavior

`FormatException String '19-12-04 03:29:02' was not recognized as a valid DateTime.`

### Other information

runtime is net5.0

**Comment by Clockwork-Muse** [comment]
date/time formats are subject to culture/localization considerations.  Are you sure that's a valid format for the culture the current process is running under?  What's the output of:

```csharp
var cc = CultureInfo.CurrentCulture;
Console.WriteLine(cc.DateTimeFormat.FullDateTimePattern);
Console.WriteLine(cc.DateTimeFormat.SortableDateTimePattern);
```

**Comment by yedajiang44** [comment]
> date/time formats are subject to culture/localization considerations. Are you sure that's a valid format for the culture the current process is running under? What's the output of:
> 
> ```cs
> var cc = CultureInfo.CurrentCulture;
> Console.WriteLine(cc.DateTimeFormat.FullDateTimePattern);
> Console.WriteLine(cc.DateTimeFormat.SortableDateTimePattern);
> ```

```c#
[root@beidou demo]# cat Program.cs
using System;
using System.Globalization;

namespace demo
{
    class Program
    {
        static void Main(string[] args)
        {
            var cc = CultureInfo.CurrentCulture;
            Console.WriteLine(cc.DateTimeFormat.FullDateTimePattern);
            Console.WriteLine(cc.DateTimeFormat.SortableDateTimePattern);

        }
    }
}
[root@beidou demo]# dotnet run
dddd, MMMM d, yyyy h:mm:ss tt
yyyy'-'MM'-'dd'T'HH':'mm':'ss
[root@beidou demo]#

```

**Comment by danmoseley** [comment]
What is the value of CultureInfo.CurrentCulture?

**Comment by yedajiang44** [comment]
> What is the value of CultureInfo.CurrentCulture?

en-US

**Comment by stephentoub** [comment]
It throws because that's not a valid date time pattern in the en-US culture.  Try changing the "19-12" to instead be "12-19".

**Comment by yedajiang44** [comment]
> It throws because that's not a valid date time value in the en-US culture. Try changing the "19-12" to instead be "12-19".

it's run success, thanks~i need change the code
