### ISSUE TITLE
Issue with HexEncoder

### ISSUE THREAD

**Issue by fuocor** [dotnet/runtime#61047]
https://github.com/dotnet/runtime/blob/f9a24499a1168d391cbf61ab57470a5a974845bb/src/libraries/Common/src/System/HexConverter.cs#L115

I played with this code a little and by doing the `Unsafe.ReadUnaligned` into the byte span the remainder of the Ssse3 code will only process the first element and not the 4 that is expected

if you use `fixed (byte* source = bytes)`  and load the `Vector128` with the pointer then it processes all 4 bytes correctly.

BTW. Really cool how you use the Shift and Shuffle to capture the hex character indexes.

**Comment by GrabYourPitchforks** [comment]
@fuocor I'm not quite sure I understand this report. Do you have a sample input that's not processing correctly? I think that would help us determine what's going wrong.

Thanks!
