### ISSUE TITLE
Get mangled name

### ISSUE THREAD

**Issue by ilobilo** [dotnet/runtime#61041]
Can I get mangled name of C# function without compiling and then using objdump or nm?

**Comment by SingleAccretion** [comment]
C# doesn't mangle names, they appear as in source in the final (managed) binary. Could you clarify?

**Comment by ilobilo** [comment]
I'm making a kernel in C# (bad idea ik) and want to call assembly code from it. I'm using extern function with internal call attribute. In assembly function's name should be mangled C# function name

**Comment by ilobilo** [comment]
But I can just use objdump so if there's no other way feel free to close the issue

**Comment by SingleAccretion** [comment]
> I'm making a kernel in C#

What runtime are you using for that?

**Comment by ilobilo** [comment]
I'm not using runtime
Mscorlib is Mosa's one

**Comment by SingleAccretion** [comment]
> I'm not using runtime

I see. Then you're free to define whatever mangling rules you fell are appropriate - there is no mangling convention for .NET code.

**Comment by ilobilo** [comment]
Ok
