### ISSUE TITLE
[Question] Why no Task<bool> for SemaphoreSlim WaitAsync (System.Threading.CancellationToken cancellationToken)

### ISSUE THREAD

**Issue by LiorBanai** [dotnet/runtime#61052]
Hi,
I was wondering why we don't have return Task<bool> for
```cs
public System.Threading.Tasks.Task WaitAsync (System.Threading.CancellationToken cancellationToken);
```
like other:
```cs
public System.Threading.Tasks.Task<bool> WaitAsync (int millisecondsTimeout, System.Threading.CancellationToken cancellationToken);
```

**Comment by stephentoub** [comment]
The bool is used to indicate timeout, not cancellation... cancellation is modeled as an exception.  That's true even in the latter overload.

**Comment by LiorBanai** [comment]
but If have .Release() in the finally clause I have no way to know if the semaphore was acquired or not (to call Release)..

**Comment by stephentoub** [comment]
Put the WaitAsync before rather than in the try that corresponds to the finally with the Release.
