### ISSUE TITLE
Supported Versions in SslStream

### ISSUE THREAD

**Issue by amin1best** [dotnet/runtime#61051]
I use following code to find supported versions in SslStream:
```cs
            string Host = "google.com";
            int Port = 443;

            var protocolSupport = new Dictionary<SslProtocols, bool>();

            foreach (var protocol in GetValues<SslProtocols>())
            {
                TcpClient tcpc = new TcpClient(Host, Port);
                SslStream ssls = new SslStream(tcpc.GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate), null);
                try
                {
                    ssls.AuthenticateAsClient(Host, null, (SslProtocols)protocol, false);
                    protocolSupport.Add(protocol, true);

                }
                catch
                {
                    protocolSupport.Add(protocol, false);
                }
                finally
                {
                    tcpc.Dispose();
                    ssls.Dispose();
                }
            }
```
Is there a better solution?

There is an extension called Supported Versions at rfc8446:
https://www.rfc-editor.org/rfc/rfc8446.html#section-4.2.1
How to read its value? Is there a plan to develop a high level API?

Also, what is difference between System.Net.SecurityProtocolType and System.Security.Authentication.SslProtocols? Both work in my code. Is System.Net.SecurityProtocolType deprecated because it has fewer fields?

**Comment by wfurt** [comment]
Are you trying to figure out what is supported by client or by the server @amin1best? In general, client can offer multiples (and .NET does bases on underlying implementation) and server chooses one. 

If you care about client, you can run your own "server" and use https://docs.microsoft.com/en-us/dotnet/api/system.net.security.serveroptionsselectioncallback?view=net-6.0. SslClientHelloInfo will give you list of protocols advertised by the client. 

The SecurityProtocolType was primarily used by https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=net-5.0 and legacy APIs.

If you use SslStream, use SslProtocols. In practice they have same values (coming originally from Windows)

**Comment by amin1best** [comment]
> If you care about client, you can run your own "server" and use https://docs.microsoft.com/en-us/dotnet/api/system.net.security.serveroptionsselectioncallback?view=net-6.0. SslClientHelloInfo will give you list of protocols advertised by the client.
>
Yes, I'm worried about client. I didn't find any code sample about ServerOptionsSelectionCallback. May I ask you to provide a sample code to read SslProtocols from SslClientHelloInfo in ServerOptionsSelectionCallback.
> If you use SslStream, use SslProtocols. In practice they have same values (coming originally from Windows)
>
Thanks, @wfurt

**Comment by wfurt** [comment]
Look at https://github.com/dotnet/runtime/blob/852405c649c1f26124974c97199053d6d8f2adab/src/libraries/System.Net.Security/tests/FunctionalTests/ServerAsyncAuthenticateTest.cs#L75-L99

This test verifies `TargetHost` but the [SslProtocols](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclienthelloinfo?view=net-6.0) have what you looking for. (as Flag bit mask) 
The test has both sides - you can eater connect locally or use any other form of Stream.

**Comment by karelz** [comment]
Triage: Looks like it is answered above. Closing. If not, please feel free to reopen.
