### ISSUE TITLE
[Nethost/Hostfxr] Hosting: How to get runtime to probe application folder

### ISSUE THREAD

**Issue by szilvaa-adsk** [dotnet/runtime#61059]
I'm porting a native application with .NET plugins from .NET4 to .NET6 (6.0.0-rc.1.21451.13). I'm struggling with `ApplicationLoadContext`.

My goal: Load the dotnet runtime/sdk dlls _and_ my own C++/CLI API dlls  into the **Default** ApplicationLoadContext.

Initially, I tried to load the runtime "implicitly" by loading my base C++/CLI dll. This causes the C++/CLI dll to be loaded into its own IsolatedComponentLoadContext. See #56391.

So I switched to using nethost/hostfx. 

First tried to use [hdt_load_assembly_and_get_function_pointer](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/native/corehost/hostfxr.h#L29) but this too causes the assembly to be loaded into its own IsolatedComponentLoadContext.
After examining the [source](https://github.com/dotnet/runtime/blob/c4d5f6dff367ba1197358e5abd0d50d8b10a3fef/src/libraries/System.Private.CoreLib/src/Internal/Runtime/InteropServices/ComponentActivator.cs#L90), I concluded that I should use [hdt_get_function_pointer](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/native/corehost/hostfxr.h#L30) instead.
This works if I set `APP_PATHS` in my runtimeconfig.json as follows:
```
{
    "runtimeOptions": {
        "tfm": "net6.0",
        "rollForward": "LatestMinor",
        "framework": {
            "name": "Microsoft.NETCore.App",
            "version": "6.0.0-rc.1.21451.13"
        },
        "configProperties": {
            "APP_PATHS": "<full path to my bin folder goes here>"
        }
    }
}
```
However, this won't work on user's machine because they can install anywhere so I would have to generate runtimeconfig.json at install time.

QUESTION: How can I tell the runtime to probe my application folder?  I'd like to get the behavior documented [here](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-are-the-properties-populated). In particular, this bit:
> When the *.deps.json file isn't present, the application's directory is assumed to contain all the dependencies. The directory's contents are used to populate the probing properties.

**Comment by rseanhall** [comment]
Ideally you would set the [`EnableDynamicLoading`](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledynamicloading) property to true when building the managed part of your app and let `hostfxr` use the runtimeconfig.json and deps.json to automatically process your dependencies.

Alternatively, you would set the `APP_PATHS` property yourself in between the call to `hostfxr_initialize_*` and `hostfxr_get_runtime_delegate` by calling `hostfxr_set_runtime_property_value`.

**Comment by szilvaa-adsk** [comment]
@rseanhall `hostfxr_set_runtime_property_value` works perfectly. Thank you for the suggestion.
