### ISSUE TITLE
system.io.pipelines sample that shows server responding to data that client is sending

### ISSUE THREAD

**Issue by kasajian** [dotnet/runtime#61060]
There ought to be a simple example of a request / response pattern implemented using system.io.pipelines.   Nothing to do with HTTP, but it's a common development pattern to send data and expect data to come back in response to what is sent.

The included sample doesn't demonstrate it, but based on the API is looks like it's possible.   Does anyone know of any sample code that demonstrates this?

**Comment by adityamandaleeka** [comment]
@kasajian Is this helpful? https://github.com/davidfowl/TcpEcho

**Comment by davidfowl** [comment]
@kasajian request response requires an RPC stack on top of pipelines. Pipelines is just the data part and doesn't encapsulate any higher level RPC on top.
