### ISSUE TITLE
GetAbbreviatedDayName in Portuguese

### ISSUE THREAD

**Issue by orwo1** [dotnet/runtime#61088]
### Description

Calling (Some)CultureInfo.DateTimeFormat.GetAbbreviatedDayName((Any)DayOfWeek);
In Portuguese Portugal return the full name of that day,
in contrast with Portuguese Brazil, which works correcly.

### Reproduction Steps

using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
  public static void Main()
  {
    var pt = new System.Globalization.CultureInfo("pt-PT");
    var br = new System.Globalization.CultureInfo("pt-BR");

    Console.WriteLine(pt.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday));
    Console.WriteLine(br.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday));
  }
}

### Expected behavior

someCultureInfo.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday) will return "dom"
For Portuguese Portugal.

### Actual behavior

someCultureInfo.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday) returns "domingo"
For Portuguese Portugal

**Comment by orwo1** [comment]
Opened here after closing in Xamarin.forms:
https://github.com/xamarin/Xamarin.Forms/issues/14810

**Comment by Joe4evr** [comment]
There's been a bunch of Globalization issues filed lately, but as per https://github.com/dotnet/runtime/issues/60286#issuecomment-941057519:

> .NET doesn't carry any globalization data. Instead, we depend on ICU library to get such data. ICU picks the globalization data from CLDR (Unicode Standard).

That makes this an external issue, but it seems very strange for CLDR to define the abbreviated names as the full names in `pt-PT`:

https://github.com/unicode-org/cldr/blob/e020f52b1210cd94d2f1d7a73d4a76d69e13e656/common/main/pt_PT.xml#L1642-L1650

But in the `pt` root, the names *are* abbreviated:

https://github.com/unicode-org/cldr/blob/e020f52b1210cd94d2f1d7a73d4a76d69e13e656/common/main/pt.xml#L1788-L1796

Git blame points to https://github.com/unicode-org/cldr/pull/1391 that changed the "abbreviated" names for `pt-PT`.

**Comment by orwo1** [comment]
I have opened an issue over there:
https://unicode-org.atlassian.net/browse/CLDR-15139

**Comment by tarekgh** [comment]
Thanks @orwo1 for filing the issue.  As @Joe4evr explained this is CLDR issue. It is nice to see you filing the issue to CLDR. I am closing the issue here as this is external issue. 

Thanks @Joe4evr for your reply and the pointers you have included.
