### ISSUE TITLE
How to use dotnet.js outside of browser?

### ISSUE THREAD

**Issue by Elringus** [dotnet/runtime#61083]
I'm looking to use C# libraries compiled to Mono WASM runtime from JavaScript, but without the browser context, so that `window`, `document` and other browser-specific APIs are not available (example use case are [web extensions](https://code.visualstudio.com/api/extension-guides/web-extensions) for vscode).

I've already ported ASP.NET Core's `blazor.webassembly.js` , but it turns out `dotnet.js` is also using browser-specific APIs. Is there a way to use Mono WASM outside of browser?

**Comment by am11** [comment]
I would also love to see dotnet.js decoupled from DOM APIs, so the responsibility of providing fetch()-like implementations is shifted to caller, or the consumer can at least inject the granular dependencies required by dotnet.js (rather than the "entire DOM API set"). dotnet.js currently depends on only a few DOM functions.

Some experimentation was done in https://github.com/dotnet/runtime/pull/41964 by compiling dotnet.wasm as an ES6 module, then loading it in deno environment along with `jsdom`. That fulfills the browser API needs. I think the next step to make progress, in the direction of creating a generic dotnet-wasm host, is using helpers from https://github.com/dotnet/runtime/blob/main/src/mono/wasm/runtime-test.js.

Related https://github.com/dotnet/runtime/issues/41861.

**Comment by mingyaulee** [comment]
I have managed to run Blazor from NodeJs with some pretty hacky ways. You can refer to my repo [Blazor.Node](https://github.com/mingyaulee/Blazor.Node) to see how it can be achieved.

Basically to make it possible, I had to create a fake DOM and window and inject it in the global variable. Other than that, I needed to replace the contents of the JavaScript files to make them compatible as an ES module.

**Comment by pavelsavara** [comment]
I will have look and we will try to implement it sometime soon. I'm working on modularization here https://github.com/dotnet/runtime/pull/61313

**Comment by Elringus** [comment]
In case anyone is interested, I've made a solution, that compiles C# project into single-file UMD library: https://github.com/Elringus/DotNetJS Tested in browsers, node and VS Code web extension.

**Comment by Elringus** [comment]
I'm continuing the experiments with running dotnet/blazor under node/vscode web extension and hit an issue with WebSocket. It looks like `System.Net.WebSockets` attempts to use browser's `WebSocket` API and doesn't work in node.

I've tried shimming `global.WebSocket` with node's `ws` module and, while it worked with a simple echo test using a local ws server (https://github.com/Elringus/DotNetJS/blob/5274ce6ad2a2ba8b5cb22b347e38fa5820d2cf72/JavaScript/dotnet-runtime/test/platform.js#L18), when used in a more complex scenario with a none-node ws server, it throws the following:

```
Error: System.Net.WebSockets.WebSocketException (0x80004005): net_webstatus_ConnectFailure
 ---> System.Net.WebSockets.WebSocketException (0x80004005): net_WebSockets_Generic
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncJavaScript(Uri , CancellationToken , List`1 )
   at System.Net.WebSockets.BrowserWebSocket.ConnectAsyncJavaScript(Uri , CancellationToken , List`1 )
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri , CancellationToken , ClientWebSocketOptions )
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri , CancellationToken )
   at Naninovel.Bridging.Client.ConnectAsync(Int32 port, CancellationToken token)
    at Object.endInvokeDotNetFromJS (C:\Users\Elringus\Documents\GitHub\Naninovel\WebEditor\Bindings\bin\dotnet.js:1:182785)
    at Object.b [as endInvokeDotNetFromJS] (C:\Users\Elringus\Documents\GitHub\Naninovel\WebEditor\Bindings\bin\dotnet.js:1:186378)
    at Object.g [as invokeJSFromDotNet] (C:\Users\Elringus\Documents\GitHub\Naninovel\WebEditor\Bindings\bin\dotnet.js:1:185881)
    at _mono_wasm_invoke_js_blazor (C:\Users\Elringus\Documents\GitHub\Naninovel\WebEditor\Bindings\bin\dotnet.js:1:146451)
    at wasm://wasm/00977a1a:wasm-function[219]:0x1a115
    at wasm://wasm/00977a1a:wasm-function[167]:0xcae7
    at wasm://wasm/00977a1a:wasm-function[166]:0xb9fa
    at wasm://wasm/00977a1a:wasm-function[2810]:0xab7d6
    at wasm://wasm/00977a1a:wasm-function[1615]:0x6f71b
    at wasm://wasm/00977a1a:wasm-function[1619]:0x6fd85
```

The same works fine when in browser, so I guess the issue is that node's `ws` module doesn't provide what `System.Net.WebSockets` expect in some cases.

Any chance for `System.Net.WebSockets` to support node at some point?

**Comment by pavelsavara** [comment]
I guess next step it to try to run [System.Net.WebSockets.Client/tests](https://github.com/dotnet/runtime/tree/360df71eadde0d1394ee7b89693f83913f75575d/src/libraries/System.Net.WebSockets.Client/tests) on NodeJs. Now that we have CommonJS module it should be relatively easy.

Maybe `dotnet.cmd build /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Debug /t:Test src/libraries/System.Net.WebSockets.Client/tests /p:WasmXHarnessArgs="--engine=NodeJS"` should do it.

You will probably need to add `globalThis.WebSocket = require("ws");` to `src\mono\wasm\test-main.js`
