### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin   Referenced from: /usr/local/share/dotnet/dotnet (which was built for Mac OS X 10.15)   Expected in: /usr/lib/libSystem.B.dylib

### ISSUE THREAD

**Issue by Sweta7** [dotnet/runtime#61085]
The problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: macos version 10.13.6

I have recently installed .net5 and trying to write a HelloWorld program. But when I run the program it's throwing me below error message. When I run a similar HelloWorld program on .Net4, runs without any error.

error message - dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin   Referenced from: /usr/local/share/dotnet/dotnet (which was built for Mac OS X 10.15)   Expected in: /usr/lib/libSystem.B.dylib.

It would be great if could point me in the right direction.

Thanks.
Sweta

**Comment by KeturahSandovalux** [comment]
I have the same issue and I'm on a dinosaur of a macbook pro. Still has the CD rom port and everything. I realize I just need to upgrade my computer unfortunatley. It's pretty outdated..... especially since I want to use VS.

**Comment by vitek-karas** [comment]
@VSadov has been looking into this and trying to figure out the min OS version we build with in the servicing branches. If I remember correctly some of the servicing branches didn't set the min OS version explicitly ... which means they got autoupdated with XCode updates. I don't know if we already fixed this or not - suggest to try the latest patch release of your .NET runtime.

**Comment by kubakista** [comment]
I assume it is the same cause as here https://github.com/dotnet/core/issues/7016
but they just decided to increase min required version in user docs... pretty sad

**Comment by agocke** [comment]
Closed as dup of https://github.com/dotnet/core/issues/7016
