### ISSUE TITLE
[API Proposal]:  JsonBoolHandling

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#61097]
### Background and motivation

System.Text.Json's JsonSerializerOptions has a simple member, JsonNumberHandling, that allows reading/writing values to/from string members.  Currently there is no equivalent for bool members.

### API Proposal

```C#
namespace System.Text.Json
{
    public class JsonSerializerOptions
    {
        public JsonBoolHandling BoolHandling {get; set;}
    }

  public enum JsonBoolHandling {
    Strict = 0x0,
    AllowReadingFromString = 0x1,
    WriteAsString = 0x2
  }
}
```     

### API Usage

var Options = new System.Text.Json.JsonSerializerOptions() {
    BoolHandling = System.Text.Json.Serialization.JsonBoolHandling.AllowReadingFromString,
   
};

### Alternative Designs

Reuse JsonNumberHandling to allow it to also control reading/writing bools.

### Risks

None.

**Comment by eiriktsarpalis** [comment]
A common use case when deserializing booleans writing and reading as integers, so if any configurability is added to boolean serialization it should definitely cater to that use case. 

Given that this feature is restricted to configurating serialization of a single type, I don't think `JsonSerializerOptions` is the appropriate type to expose this. We should instead look at perhaps exposing `BooleanConverter` and have a constructor accept parameters in the style of `JsonStringEnumConverter`.

**Comment by layomia** [comment]
The `JsonNumberHandling` feature that this proposal models is pretty clunky in it's implementation (as written by me). Rather than add a parallel feature for bools, we could either include `bool` as one of the types that are affected by `JsonNumberHandling`, or to take the converter approach as mentioned by @eiriktsarpalis.

**Comment by eiriktsarpalis** [comment]
Closing per feedback.
