### ISSUE TITLE
X509Certificate.CreateFromSignedFile fails on Linux with ASN1 corrupted data

### ISSUE THREAD

**Issue by Sam13** [dotnet/runtime#61092]
### Description

The following code works on Windows when a path to a signed file is provided:

```csharp
var certificate = X509Certificate.CreateFromSignedFile(filePath);
```

when running the same under Linux the following exception is thrown:
```
System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Application' class value '13', but it should have been 'Universal' class value '16'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& contentLength, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnValueReader.ReadSequence(Nullable`1 expectedTag)
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, PfxAsn& decoded)
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(String filename)
```

### Reproduction Steps

Run the following code snipped under Linux (e.g. Ubuntu 20.04) and provide a path to a signed assembly:
```csharp
var certificate = X509Certificate.CreateFromSignedFile(filePath);
```

### Expected behavior

Certificate can be read correctly under Linux

### Actual behavior

Throws exception (see description)

### Configuration

```
dotnet --version
5.0.402
```
- Ubuntu 20.04 LTS (WSL2) and also inside Docker container
- Windows 10

### Other information

Related issue: https://github.com/dotnet/runtime/issues/47005

**Comment by vcsjones** [comment]
Is the file you are passing to `CreateFromSignedFile` an Authenticode signed Windows file?

`CreateFromSignedFile` is just `new X509Certificate(..)`


https://github.com/dotnet/runtime/blob/594f32e4309a08dce741675ee0420adee4a69658/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate.cs#L214-L217

The supported contents of the constructor is going to vary from platform to platform. In Windows, this is passed to the platform to query the contents for a certificate. Windows understands Authenticode signed files, whereas Linux does not.

The closest issue related to this is https://github.com/dotnet/runtime/issues/15073#issuecomment-619422356, which looks like it is tracking support for PKCS#7 and Authenticode signed files.

**Comment by Sam13** [comment]
> 
> 
> Is the file you are passing to `CreateFromSignedFile` an Authenticode signed Windows file?

I guess so. For example _System.Security.Cryptography.Xml.dll_ 

> 
> The supported contents of the constructor is going to vary from platform to platform. In Windows, this is passed to the platform to query the contents for a certificate. Windows understands Authenticode signed files, whereas Linux does not.
> 
> The closest issue related to this is [#15073 (comment)](https://github.com/dotnet/runtime/issues/15073#issuecomment-619422356), which looks like it is tracking support for PKCS#7 and Authenticode signed files.

If I understand you correctly this is not yet supported?
Is there any workaround to check whether a file is (Windows) signed under Linux?

**Comment by bartonjs** [comment]
Since Mono has a tool that does it (chktrust) https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mcs/class/Mono.Security/Mono.Security.Authenticode/AuthenticodeDeformatter.cs probably works; but I don't know how deep the rabbit-hole goes on using it.

**Comment by bartonjs** [comment]
The disabled test that would check for this says it's tracked by 15073... so closing this as a dupe of that.
