### ISSUE TITLE
DataMisalignedException thrown when using MemoryMarshal.Cast<byte, double> on correct data

### ISSUE THREAD

**Issue by freddyrios** [dotnet/runtime#61096]
### Description

Trying to use MemoryMarshal.Cast<byte, double> against a span returned from a byte[] via fails when iterating the values with a DataMisalignedException. It works correctly on windows but fails on linux.

This is the narrowed down version showing the issue:
```
var bytes = Convert.FromHexString("0A0000000000000000");
var vector = MemoryMarshal.Cast<byte, double>(bytes.AsSpan()[1..]);
foreach (var value in vector)
    Console.Write(value);
```

In the actual scenario the bytes are part of a message being exchanged over the network. The message gets into a byte[] and then its processed, failing with the exception when it tries to iterate the result of the `MemoryMarshal.Cast`.

### Reproduction Steps

Follow the instructions in the isolated reproduction at https://github.com/freddyrios/spancastfailure

It has the same code as in the description.

### Expected behavior

The program prints 0

### Actual behavior

The program throws the following exception `System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.`

### Regression?

No. It fails in both .net 5 and 6.

### Known Workarounds

Use slice + MemoryMarshal.Read instead. The example below uses a longer message with 2 doubles to show that the workaround works beyond a single Read:

```
var bytes = Convert.FromHexString("0A00000000000000000000000000000000");
var bytesSpan = bytes.AsSpan<byte>()[1..];
while (bytesSpan.Length > 0)
{
    Console.Write(MemoryMarshal.Read<double>(bytesSpan));
    bytesSpan = bytesSpan[sizeof(double)..];
}

Console.WriteLine();
```

### Configuration

.net 5 and net 6 (recent daily build - Version:   6.0.100-rtm.21512.45 Commit:    a043afb79d).

built on windows x64 and ran in linux-arm. It works fine on windows.

### Other information

There seems to be many mentions in other issues of DataMisalignedException on arm where its either considered a test failure / temporary or maybe even wrong usage. The example in this new issue is fairly straightforward and the workaround hints at it not being inherently broken for the platform.

Here are the other issues I noticed when looking for this one (did not find an exact match):

- https://github.com/dotnet/runtime/issues/34258
- https://github.com/dotnet/runtime/issues/1650
- https://github.com/dotnet/runtime/issues/8587
- https://github.com/dotnet/runtime/issues/8499
- https://github.com/dotnet/runtime/issues/7970
- https://github.com/dotnet/runtime/issues/7950
- https://github.com/dotnet/runtime/issues/6935
- https://github.com/dotnet/runtime/issues/18041

**Comment by DaZombieKiller** [comment]
I don't think this is a bug, but rather expected behaviour. `MemoryMarshal.Read` works because it does an unaligned read (uses `Unsafe.ReadUnaligned` internally). Your example code doesn't guarantee any particular alignment on the data, it just allocates a byte array and slices off the first value before reinterpreting it.

**Comment by freddyrios** [comment]
@DaZombieKiller closing this based on that, also given this is in the remarks of the method: "This method is supported only on platforms that support misaligned memory access or when the memory block is aligned by other means.".

ps. I would say its *documented* instead of expected behaviour i.e. its quite unexpected when the MemoryMarshal one used elsewhere was MemoryMarshal.Read and its docs do not mention memory alignment in any way i.e. so its easy to shoot yourself in the foot.
