### ISSUE TITLE
Enhance Json Serialize() with CancellationToken

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#611]
**Scenario:** PowerShell ConvertTo-Json cmdlet uses custom code (based on Netonsoft Json.NET) to serialize objects to Json. On every step it checks CancellationToken. Since PowerShell do all work in separate threads (`runspaces`) users from console or hosted application can gracefully stop the serialization process at any time.

While working on migrating the cmdlet on new Core Json API I discovered that System.Text.Json.JsonSerializer.Serialize() method has not a parameter for CancellationToken so unable to complete the migration.
Using SerializeAsync() looks too expensive for the task.

### API proposal ###
```c#
namespace System.Text.Json
{
    public static partial class JsonSerializer
    {
        public static void Serialize<TValue>(Utf8JsonWriter writer, TValue value, JsonSerializerOptions options = null);    // Existing
        public static void Serialize<TValue>(Utf8JsonWriter writer, TValue value, JsonSerializerOptions options = null, CancellationToken cancellationToken = default);    // New
        public static void Serialize(Utf8JsonWriter writer, object value, Type inputType, JsonSerializerOptions options = null);    // Existing
        public static void Serialize(Utf8JsonWriter writer, object value, Type inputType, JsonSerializerOptions options = null, CancellationToken cancellationToken = default);    // New
    }
}
```

**Comment by stephentoub** [comment]
> Using SerializeAsync() looks too expensive for the task.

Can you elaborate / share metrics that demonstrate it's too slow?

**Comment by iSazonov** [comment]
I have no metrics. I tried to switch from Serialize() to SerializeAsync() and my thoughts is that with SerializeAsync():
- we have to create extra thread and to have a specific code for processing (aggregate) exceptions
- we have to create extra memory stream and then decode and convert to string (Serialize() does already this very efficient)

Both SerializeAsync() and Serialize() use one code base so we only need to expose the cancellation publicly for Serialize().

**Comment by stephentoub** [comment]
> we have to create extra thread

This isn't how async works.

> specific code for processing (aggregate) exceptions

There is no special processing of AggregateException exceptions involved in async. AggregateExceptions are only manufactured by Task when calling .Wait()/.Result on a faulted task.

> we have to create extra memory stream and then decode and convert to string 

What memory stream are you referring to? SerializeAsync uses a pooled buffer writer.

> Both SerializeAsync() and Serialize() use one code base so we only need to expose the cancellation publicly for Serialize().

A synchronous Serialize targeting Stream would use the synchronous methods on Stream, which do not accept cancellation tokens.

**Comment by stephentoub** [comment]
> Serialize() method has not a parameter for CancellationToken so unable to complete the migration

What piece of this are you trying to cancel? From the description of your scenario, it sounds like you're not actually doing any I/O. Why is checking the token before the operation insufficient?

**Comment by iSazonov** [comment]
PowerShell does all work in separate working threads (runspaces). It is already async. Main thread can control working threads calling StopProcessing() method where we can set cancellation token state. ConvertTo-Json cmdlet is executed in such working thread, converts input object to resulting string and write the result string to PowerShell pipeline. The conversion is done step by step in recursion methods. At each step, value of next property is retrieved that can take long time (ex., get list VMs from Azure). We can not control this but we check cancellation token before next property processing. So cmdlet does the work sync. After I replaced the custom recursion methods with new Json API Serialize() and I lost the possibility to check cancellation token on every step. Wrapping Serialize() in Task.Run() allows cancellation but add a complicity as I said above.
SerializeAsync() allows cancellation but add complicity too in the sync code - it writes to utf8Json stream but we need Utf16 string.

**Comment by stephentoub** [comment]
> SerializeAsync() allows cancellation.

It supports cancellation because it's doing async I/O. From what you described, you're not.

What I'm asking is, why can't you consider the serialization as one step, where cancellation is checked before/after it as with any other step? I don't see why the serialization itself needs to accept a token. Is the serialization taking a long time while doing only compute/memory operations?

**Comment by iSazonov** [comment]
> It supports cancellation because it's doing async I/O. From what you described, you're not.

Yes, PowerShell doesn't use native C# async and as you already understand implement (historically) custom async on more high level. So we can not get all benefits from SerializeAsync() without workarounds with extra code.

> What I'm asking is, why can't you consider the serialization as one step, where cancellation is checked before/after it as with any other step? I don't see why the serialization itself needs to accept a token. Is the serialization taking a long time while doing only compute/memory operations? Can you share the relevant code?

I guess you are thinking about simple C# objects like DateTime. Yes, serialization of DateTime takes some nanoseconds. Let's consider more complex class with DateTime property with lazy initialization to DateTime.Now. Serialization will be 100 or 1000 times slower. Now consider a property with web request. It can take some milliseconds, or seconds, or dozen seconds. If a class has some such properties checking cancellation token on every step doesn't look so amazing. 
For PowerShell PSObject, the situation may be even worse.  PSObject can wrap DateTime and will be 100x slower. PSObject can contains custom script properties. Serialization of such properties always will be relatively slow even for simple properties. Taking in account that PowerShell is a management shell, PSObject can has properties that take a long time to compute and even access the Cloud. Current implementation of serialization enumerates properties and check cancellation token before process recursively a next property.

**Comment by stephentoub** [comment]
SerializeAsync doesn't check the cancellation token before/after every property, only when performing I/O.  You're asking then not just for Serialize to take a CancellationToken, but for it to poll the token before/after every property, just in case a property getter does something that properties aren't supposed to do: take a very long time to run.

**Comment by iSazonov** [comment]
> SerializeAsync doesn't check the cancellation token before/after every property, only when performing I/O. 

Thanks for clarify!

>  a property getter does something that properties aren't supposed to do: take a very long time to run.

Yes. I believe it can be critical for serialization of script based objects.

**Comment by layomia** [comment]
`CancellationToken` is intended for async, task-based method calls. If you can show some examples of this pattern used elsewhere, then this can be reopened.

**Comment by iSazonov** [comment]
I can reword my request: I need to send a _context_ to my custom converter so that the converter can use values from the context to serialize an object.
