### ISSUE TITLE
[API Proposal]: Add support to override default event provider name for AddEventSourceLogger

### ISSUE THREAD

**Issue by ruhoch** [dotnet/runtime#61100]
### Background and motivation

Microsoft.Extensions.Logging.EventSource's AddEventSourceProvider does not allow the default event provider name to be overridden, meaning any product that uses the library will emit messages under the same provider name. 

This makes it impossible to utilize the api in a retail products without forking and implementing a new version of the AddEventSourceProvider  extension and LoggingEventSource.

Allowing the desired event source provider name to be passed in to LoggingEventSource would allow retail products to use the library without having their ETW events binned in with all products that utilize the api.

### API Proposal

```C#
namespace Microsoft.Extensions.Logging
{
    public static ILoggingBuilder AddEventSourceLogger(this ILoggingBuilder builder**, string eventSourceProviderName**)
    {
            if (builder == null)
            {
                throw new ArgumentNullException(nameof(builder));
            }

            builder.Services.TryAddSingleton(new **LoggingEventSource(eventSourceProviderName)**);
            builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<ILoggerProvider, EventSourceLoggerProvider>());
            builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IConfigureOptions<LoggerFilterOptions>, EventLogFiltersConfigureOptions>());
            builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<IOptionsChangeTokenSource<LoggerFilterOptions>, EventLogFiltersConfigureOptionsChangeSource>());
            return builder;
    }
}
```     

### API Usage

```C#
            Factory = LoggerFactory.Create(builder =>
            {
                builder.AddSurfaceEventSourceLogger( "MyEventSourceProviderName" );
            });
```

**Comment by davidfowl** [comment]
cc @noahfalk for best practices regarding multiple instances of the logging event source

**Comment by noahfalk** [comment]
@ruhoch thanks for reaching out. If you do something like this:
```
dotnet trace collect -p {PID} 
    --providers Microsoft-Extensions-Logging:{Keyword}:{Provider Level}
        :FilterSpecs=\"
            {Logger Category 1}:{Category Level 1};
            {Logger Category 2}:{Category Level 2};
            ...
            {Logger Category N}:{Category Level N}\"
```
then you can get dotnet-trace to capture only a subset of the ILogger events. Can you help me understand if this is meets your goal, or if not how does your goal differ?

**Comment by maryamariyan** [comment]
Seems like there is a workaround, therefore closing issue.
