### ISSUE TITLE
[tracking]: Remove SafeFileHandle for Unix

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#61112]
@deeprobin yeah it's a historical issue, and would need a hypothetical feature to fix: https://github.com/dotnet/runtime/issues/26227#issuecomment-747842770

_Originally posted by @danmoseley in https://github.com/dotnet/runtime/pull/60507#discussion_r737900037_

**Comment by danmoseley** [comment]
The proposal here is to find a way to move SafeFileHandle and such classes out of Microsoft.Win32.SafeHandles into some namespace that doesn't have the historic ties with Windows.

Unfortunately as far as I can see that requires a nonexistent feature that allows types to be forwarded between namespaces. I would expect we would need much more compelling reasons to do something like that. @jkotas has that ever come up?

**Comment by jkotas** [comment]
Namespace forwarding is a very complex feature to build. It comes up occasionally when the technology names or positioning changes, the old names are not good fit anymore and people would like to stay compatible with old names and have new names at the same time. 

In practice, the changes in technology names or positioning are often accompanied by other (breaking) changes, so namespace forwarding would not actually help to fully solve the problem in many cases.

**Comment by danmoseley** [comment]
Thanks. @deeprobin  I'm going to close this because we don't have sufficient compelling reason to make such a major investment - although I don't like the name either. thanks for opening this tracking issue though.
