### ISSUE TITLE
SslStream.Read behavior changes

### ISSUE THREAD

**Issue by pkindruk** [dotnet/runtime#61115]
I have been moving some legacy code from net46 to net5.0, for background that code was custom binary protocol using length delimited messages as TCP payload. While testing the result, I encountered different behavior when reading data from socket with `SslStream.Read(byte[], int, int)`. Behavior changes depending on target framework:
1. For `net48`:
1 chuck of data(typically up to 16355 bytes if there is enough data available) is read and returned. If there was more data than returned it will remain on socket and `Socket.Poll(SelectMode.Read)` would return `true`.
2. For `net5.0`:
If there is more that 1 chunk of data at least 2 will be read, but only 1 will be returned. The remaining chunks can be read with subsequent calls to `SslStream.Read(...)`, but `Socket.Poll(...)` would return `false` (if no data comes in). Looks like the data is stored somewhere inside `SslStream`.
3. For `net6.0`:
If there is more that 1 chunk of data at least 2 will be read and all what is read - returned. So here we go back to `net48` case, with more data returned at once. Most likely this was fixed here #50815.

While looking for similar issues I came across dotnet/core#3485. From outside perspective this issue looks very familiar. I saw the same at first until I started digging in.

To sum up it is undocumented behavior which can break code relying on old behavior. But it got fixed in `net6.0`.
Since there is no way to check if there is data available on SslStream, I need a reliable solution for both `net48` and `net5.0`. `net6.0` is not an option yet, because it will take a while to adapt it through all related projects.

Is there any chance to backport some kind of fix for this behavior to net5.0?
As for the fix in my code I see 2 options (not sure which one is better):
1. Use APM methods BeginRead/EndRead.
2. Experiment around ReadTimeout=0 or 1.

dotnet versions:
- Microsoft.NETCore.App 5.0.11. SDK - 5.0.402.
- Microsoft.NETCore.App 6.0.0-rc.2.21480.5. SDK - 6.0.100-rc.2.21505.57

Windows versions (same behavior on both):
- Win10 20H2. OSBuild 19042.1237
- Win10 21H1. OSBuild 19043.1288

Repro code:
```cs
using System;
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Authentication;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Threading;
using System.Threading.Tasks;

namespace SslApp
{
    class Program
    {
        const int PayloadSize = 20000; // reproduces net5.0 deviation more frequently
        //const int PayloadSize = 4 + 104868; //original payload size from staging
        const int ReceiveBufferSize = 1024 * 1024;
        const int DueTime = 2000;
        const int Period = 5000;
        const string ServerCertificatePath = "cert.pfx";


        static void Main(string[] args)
        {
            var cancelTokenSrc = new CancellationTokenSource();

            var listenSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            listenSocket.Blocking = true;
            listenSocket.NoDelay = true;

            listenSocket.Bind(new IPEndPoint(IPAddress.Loopback, 0));
            listenSocket.Listen(100);

            var endPoint = listenSocket.LocalEndPoint;
            Console.WriteLine($"Started server on {endPoint}");

            var _ = Task.Factory.StartNew(() => AcceptLoop(listenSocket, cancelTokenSrc.Token), TaskCreationOptions.LongRunning);

            var clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            clientSocket.Blocking = true;
            clientSocket.NoDelay = true;

            clientSocket.Connect(listenSocket.LocalEndPoint);

            var __ = Task.Factory.StartNew(() => ReceiveLoop(clientSocket, cancelTokenSrc.Token), TaskCreationOptions.LongRunning);

            Console.WriteLine("Press Enter to stop...");

            Console.ReadLine();

            cancelTokenSrc.Cancel();
            listenSocket.Close();
        }


        static void AcceptLoop(Socket listenSocket, CancellationToken cancelToken)
        {
            while (!cancelToken.IsCancellationRequested)
            {
                var connection = listenSocket.Accept();

                if (cancelToken.IsCancellationRequested)
                    return;

                var _ = Task.Run(() => SendLoop(connection, cancelToken));
            }
        }

        static async Task SendLoop(Socket connection, CancellationToken cancelToken)
        {
            var networkStream = new NetworkStream(connection, false);
            var sslStream = new SslStream(networkStream, true, (s, cert, chain, policy) => true);

            try
            {
                sslStream.AuthenticateAsServer(new X509Certificate2(ServerCertificatePath), false, SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls, false);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Server: ssl error - {ex}");
                return;
            }

            await Task.Delay(DueTime, cancelToken);

            var data = new byte[PayloadSize];
            using (var rng =new RNGCryptoServiceProvider())
            {
                rng.GetNonZeroBytes(data);
            }

            while (!cancelToken.IsCancellationRequested)
            {
                Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff} | Server: sending data...");

                sslStream.Write(data);

                await Task.Delay(Period, cancelToken);
            }

            sslStream.Close();
            networkStream.Close();
            connection.Close();
        }

        static void ReceiveLoop(Socket clientSocket, CancellationToken cancelToken)
        {
            var networkStream = new NetworkStream(clientSocket, false);
            var sslStream = new SslStream(networkStream, true, (s, cert, chain, policy) => true);

            try
            {
                sslStream.AuthenticateAsClient("", null, SslProtocols.Tls12 | SslProtocols.Tls11 | SslProtocols.Tls, false);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Client: ssl error - {ex}");
                return;
            }

            var buffer = new byte[ReceiveBufferSize];

            while (!cancelToken.IsCancellationRequested)
            {
                var size = sslStream.Read(buffer, 0, ReceiveBufferSize);

                Console.WriteLine($"{DateTime.Now:HH:mm:ss.fff} | Client: Received {size} bytes");

                while (!cancelToken.IsCancellationRequested)
                {
                    if (clientSocket.Poll(100_000, SelectMode.SelectRead))
                        break;

                    // here we check whether receive timeout exceeded
                    // if so run unexpected disconnect routine
                }
            }

            sslStream.Close();
            networkStream.Close();
            clientSocket.Close();
        }
    }
}
```

`net48` output. Nothing unusual here, behavior code was written for.
```
Started server on 127.0.0.1:64150
Press Enter to stop...
21:40:19.948 | Server: sending data...
21:40:19.950 | Client: Received 16355 bytes
21:40:19.950 | Client: Received 3645 bytes
21:40:24.955 | Server: sending data...
21:40:24.956 | Client: Received 16355 bytes
21:40:24.956 | Client: Received 3645 bytes
21:40:29.965 | Server: sending data...
21:40:29.965 | Client: Received 16355 bytes
21:40:29.966 | Client: Received 3645 bytes
21:40:34.976 | Server: sending data...
21:40:34.976 | Client: Received 16355 bytes
21:40:34.977 | Client: Received 3645 bytes
```

`net5.0` output
```
Started server on 127.0.0.1:64095
Press Enter to stop...
21:30:15.895 | Server: sending data...
21:30:15.902 | Client: Received 16355 bytes
21:30:15.902 | Client: Received 3645 bytes
// first time for some reason it works fine
21:30:20.912 | Server: sending data...
21:30:**20**.912 | Client: Received 16355 bytes
// here SslStream gets all data at once, so Socket.Poll will return true only when next chunk is sent
21:30:25.917 | Server: sending data...
21:30:**25**.917 | Client: Received 3645 bytes
// And so happens to next messages
21:30:25.918 | Client: Received 16355 bytes
21:30:30.920 | Server: sending data...
21:30:30.922 | Client: Received 3645 bytes
21:30:30.922 | Client: Received 16355 bytes
21:30:35.925 | Server: sending data...
21:30:35.925 | Client: Received 3645 bytes
21:30:35.925 | Client: Received 16355 bytes
21:30:40.938 | Server: sending data...
21:30:40.938 | Client: Received 3645 bytes
21:30:40.939 | Client: Received 16355 bytes
```

`net6.0` output. Behavior a little different, but still expected.
```
Started server on 127.0.0.1:1212
Press Enter to stop...
21:43:42.817 | Server: sending data...
21:43:42.830 | Client: Received 16355 bytes
21:43:42.831 | Client: Received 3645 bytes
21:43:47.841 | Server: sending data...
21:43:47.841 | Client: Received 20000 bytes
21:43:52.848 | Server: sending data...
21:43:52.849 | Client: Received 16355 bytes
21:43:52.849 | Client: Received 3645 bytes
21:43:57.860 | Server: sending data...
21:43:57.861 | Client: Received 20000 bytes
21:44:02.874 | Server: sending data...
21:44:02.875 | Client: Received 16355 bytes
21:44:02.875 | Client: Received 3645 bytes
21:44:07.885 | Server: sending data...
21:44:07.885 | Client: Received 20000 bytes
```

**Comment by scalablecory** [comment]
This isn't something that consistency should be expected from. `Stream.Read` is not packet based; For every `Write`, you can get multiple reads, or it might consolidate them.

I think a 0-byte `Read()` will result allow you to wait for more data being available, but I don't think there's any way to poll. Note, even polling for data on the socket isn't correct, because TLS can send alerts at any point. @wfurt can confirm

**Comment by pkindruk** [comment]
It is perfectly fine that `SslStream.Read` can return arbitrary number of bytes. Message boundaries are handled upper in stack. I omitted those details since they have nothing to do about this issue.
I wanted to talk about `SslStream.Read` behavior. It can read more data from underlying stream, but return less, leaving some of it somewhere in its internal cache. This behavior is only present `net5.0`.

Speaking of polling I get your point and it explains some strange code present in that project. Unfortunately I can't ask author about why it was done this way. Seems like I will need to refactor it heavily.

**Comment by scalablecory** [comment]
> I wanted to talk about `SslStream.Read` behavior. It can read more data from underlying stream, but return less, leaving some of it somewhere in its internal cache. This behavior is only present `net5.0`.

This is fine -- no guarantees are made on how `SslStream` reads the underlying stream, or how it buffers. This isn't a `SslStream`-specific thing, either: we generally leave this type of thing undefined because it leaves flexibility for making performance changes in the future. It's not a bug, so it's not something viable to change in 5.0.

Stepping back, it looks like you have a desire to poll if data is available on an `SslStream`, is that correct? I'm interested in the use case for this. If you can find out how the code is leveraging that, it'd be good data to help shape future APIs.

**Comment by wfurt** [comment]
I think it is unlikely to get any change to `net5.0` @pkindruk.  The servicing bar is pretty high so there would need to be some serious functional impact. 

Even with 'net6.0' there _may_ be some internal buffering. Let imagine you get bunch of smaller TLS frames (let say 15K total) but you give small buffer to `read()`. SslStream would be happy to read everything from socket but not would stop processing when it fills the buffer. 

Using the `poll` directly seems fragile and generally breaks the layering. e.g. you check socket for data but then you try to read from Stream.

**Comment by wfurt** [comment]
I was thinking about it more @pkindruk  and perhaps you can write simple wrapper `Stream` you hand to `SslStream` instead of `NetworkStream`. With that, the `Poll` logic could work on all versions.  

Let me know if you have more concerns. Let me know if there are any other concerns.

**Comment by pkindruk** [comment]
@scalablecory I double checked everything, but code does only receive/send timeout logic in receive/send thread. It is not something you can't check from outside and really need to `Poll`. Another downside - this requires 2 dedicated threads for each connection.

@wfurt thanks for idea with stream wrapper, but those dedicated threads for each client connection were always bothering me, so I will take some effort to turn it async.

I decided to go for BeginRead/EndRead approach and check receive/send timeout from another thread. All this logic with `Poll` doesn't seems necessary and looks overcomplicated.

**Comment by wfurt** [comment]
Make sense. I'm glad you have plan how to address it @pkindruk
