### ISSUE TITLE
TimeZoneInfo.GetSystemTimeZones() returns empty list - Net6 Regression

### ISSUE THREAD

**Issue by ao57772** [dotnet/runtime#61127]
### Description

On a linux system without lib ICU installed, 

TimeZoneInfo.GetSystemTimeZones() returns empty list. 
The reason is, TimeZoneInfo.TryPopulateTimeZoneDisplayNamesFromGlobalizationData, 
in TimeZoneInfo.FullGlobalizationData.Unix.cs, on line 33, does this:

            CultureInfo uiCulture = CultureInfo.CurrentUICulture;
            if (uiCulture.Name.Length == 0)
                uiCulture = CultureInfo.GetCultureInfo(FallbackCultureName); // ICU doesn't work nicely with InvariantCulture

CultureInfo.GetCultureInfo(FallbackCultureName) throws because in non-ICU mode, it is not allowed 
to have any other culture except the invariant culture, it is hoping for something that cannot be fulfilled. The code above behaves contradictory to what could be expected if the application is configured with System.Globalization.Invariant=true.

### Reproduction Steps

var list = TimeZoneInfo.GetSystemTimeZones();
// list.Count is 0 (wrong, should be at least 100)

with 
{
    "configProperties": {
      "System.Globalization.Invariant": true
    }
}

on linux without lib-ICU.

### Expected behavior

TimeZoneInfo.GetSystemTimeZones(); should return timezones as expected

### Actual behavior

 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.TimeZoneInfo.TryPopulateTimeZoneDisplayNamesFromGlobalizationData(String timeZoneId, TimeSpan baseUtcOffset, String& standardDisplayName, String& daylightDisplayName, String& displayName)
   at System.TimeZoneInfo..ctor(Byte[] data, String id, Boolean dstDisabled)

### Regression?

It works in net 5 official releases.

### Known Workarounds

the following workaround creates a fake invariant culture with a valid name.
The condition "if (uiCulture.Name.Length == 0)" is then false and CultureInfo.GetCultureInfo(FallbackCultureName) is not called.

var ci = (CultureInfo) CultureInfo.InvariantCulture.Clone();
CultureInfo.CurrentCulture = ci;
CultureInfo.CurrentUICulture = ci;

var fieldX = typeof(CultureInfo).GetFields(BindingFlags.Instance | BindingFlags.NonPublic).FirstOrDefault(k => k.Name == "_nonSortName");
fieldX.SetValue(ci, "en-US");

### Configuration

net 6.0.0-rc.2.21480.5 
ubuntu minimal 20.04 LTS x64, yocto linux on ARMv7
without lib ICU installed
independent of CPU architecture.

runtimeconfig:
{
    "configProperties": {
      "System.Globalization.Invariant": true
    }
}

### Other information

it seems it does not throw on a system with lib-ICU installed && having "System.Globalization.Invariant": true.
lib-ICU must not be present at all.

**Comment by safern** [comment]
@ao57772 thanks for your report. 

This was an intentional breaking change that we added in .NET 6 as creating new cultures when running on Invariant mode doesn't really do anything as the data that is used for all culture aware operations will use the Invariant Culture data, even if the user created a culture and requested that culture to be used.

You can read a little bit more about this breaking change here: 
https://docs.microsoft.com/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode

The change was made here if you are curious: https://github.com/dotnet/runtime/pull/54247

Also, to enable the previous behavior if that is what you need for any reason, you can add a separate runtime configuration switch to your json:

```json
"System.Globalization.PredefinedCulturesOnly" : true
```

You can read more about the options to enable this new switch here: https://docs.microsoft.com/dotnet/core/run-time-config/globalization#predefined-cultures

Please let us know if you have any further questions.

**Comment by tarekgh** [comment]
We already fixed this in the release build.  https://github.com/dotnet/runtime/pull/59710. You may try the release build from https://github.com/dotnet/installer.

**Comment by safern** [comment]
> We already fixed this in the release build. #59710. You may try the release build from https://github.com/dotnet/installer.

Thanks @tarekgh for correcting me 😄. I for some reason got confused.

**Comment by danmoseley** [comment]
@ao57772 it would be great if you could confirm here when you've verified that all is working for you. thanks again for the report.

**Comment by ao57772** [comment]
> @ao57772 it would be great if you could confirm here when you've verified that all is working for you. thanks again for the report.

I tried with v6.0.100, built from commit 4822e3c3aa, it works ok.

Sorry, that I tried only with rc2, 
but https://dotnet.microsoft.com/download points to rc2. 
I wasn't sure if I want to dive into the daily builds.

**Comment by danmoseley** [comment]
Nope that's enough confirmation. Thanks!

**Comment by danmoseley** [comment]
BTW @ao57772 we have lots of issues marked up-for-grabs or easy, if you are interested in becoming a contributor!
