### ISSUE TITLE
ReadyToRun, PublishSingleFile=true, net 5.0 / 6.0 leaves native dlls out of bundle container

### ISSUE THREAD

**Issue by tapika** [dotnet/runtime#61120]
Forked from https://github.com/dotnet/runtime/issues/60936 discussion, as separate not related bug report.

- `PublishSingleFile=true`
- `PublishTrimmed=true`

Run following commands:

`git clone https://github.com/tapika/swupd.git`

To build on .net 5.0 platform:

`build buildexe_chocogui_win7 -net net5.0`

Check build directory - `src\ChocolateyGui\bin\publish_win7-x64` - 
It does build .exe, but additionally to that it also produces a lot of native .dll's next
to executable like: `mi.dll, miutils.dll, mscordaccore.dll` and so on.

Same problem persists also in .net 6.0 platform - Can be tried with following command:

Uncomment these lines:

```
build.ps1

        #if($buildTarget -eq 'chocogui')
        #{
        #    $publishTrimmed = 'false'
        #}
```

and run command:

`build buildexe_chocogui_win81 -net net6.0`

Same command + executable works correctly with .net core 3.1. (`build buildexe_chocogui_win7`)

**Comment by AndrewMD5** [comment]
Have you tried `IncludeNativeLibrariesForSelfExtract` or `IncludeAllContentForSelfExtract`?

**Comment by tapika** [comment]
With both options turned on build seems to work. (With only `IncludeNativeLibrariesForSelfExtract=true` - there comes folder `runtime` and .exe does not raise)

What is odd - that that on .net 5 I have configured .net platform to be `net5.0-windows10.0.19041`, which implies that executable would work only on windows 10 - but I find out that it works also on windows 7.

With `net6.0-windows10.0.19041` + RID = win81 - also works on windows 7 , with exception to missing `api-ms-win-core-winrt-l1-1-0.dll` - by copying `api-ms*` binaries that UI also starts.

I think this ticket could be closed if you dont see other issue.

**Comment by vitek-karas** [comment]
I must admit I don't fully understand what version you're comparing against each other. That said:
* Building a net5.0 app as single-file on Windows is expected to produce an executable and several native dlls next to it (limitation of what was implemented in .NET 5). Basically all managed assemblies are part of the exe, all native libs, including the runtime are left next to it on disk.
* Building a net6.0 app as single-file is expected to produce only a single executable, unless the app has additional native library dependencies, in which case those should be left next to the exe. (In .NET 6 the runtime is now part of the executable, but we don't have a way to "bundle" additional native libraries into it without extraction). This executable is also not expected to extract anything when you run it.
* Using `IncludeNativeLibrariesForSelfExtract=true` will bundle all native libraries but the executable will extract them onto disk on start.

`IncludeAllContentForSelfExtract` is a setting available basically to be compatible with 3.1 single-file. This will bundle everything in the app (code or not), but it will also extract everything on startup (including managed assemblies and so on).

**Comment by tapika** [comment]
My last comment was about `TargetFramework` - my assumption is that:

If you have `<TargetFramework>net5.0</TargetFramework>` - given executable can be exported to windows 7, 10 and linux
If you have `<TargetFramework>net5.0-windows</TargetFramework>` - given executable can be exported to windows 7, 10 and but not linux
If you have `<TargetFramework>net5.0-windows10.0.19041</TargetFramework>` - given executable can be exported to windows 10, but not to windows 7 and not to linux

Meanwhile I see opposite effect. I have `<TargetFramework>net5.0-windows10.0.19041</TargetFramework>` and ReadyToRun executable works fine on windows 7. But this maybe limitation of the publisher of nuget package - nuget package certains API would use windows 10 features, but most of time it would be compatible with windows 7.


Minor issue, I think ticket can be closed.

**Comment by agocke** [comment]
> But this maybe limitation of the publisher of nuget package - nuget package certains API would use windows 10 features, but most of time it would be compatible with windows 7.

Right, the `net5.0-windowsXYZ` there means that some APIs are included that are only available on later versions of Windows. If you happen to not use any of those APIs, then your app will run fine.

In general, the guidance is that for the broadest platform support, you should specify the simplest TargetFramework (like `net5.0`), but you will have the fewest APIs available. More specific TFMs will give you more APIs, but less guaranteed platform support.
