### ISSUE TITLE
[mono] Create separate yml that can trigger full test runs on demand

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#61132]
Since a large share of the mono configurations are now running only smoke tests on each PR, we need to have a way to manually trigger running all tests.  A copy of runtime.yml that can only be manually triggered is probably the easiest option, but I'm sure there are others.  

An engineer should be able to trigger a full test run via `/azp run <yet-to-be-named.yml>`

**Comment by radical** [comment]
Can it be nested like `mono.yml` can contains `apple/android/wasm.yml`, and any further splits, if useful. And these can be triggered on-demand. then maybe `runtime.yml` can use the above mono.yml?

**Comment by akoeplinger** [comment]
Yeah you can nest templates, basically like we use the `eng/pipelines/common/platform-matrix.yml` template in `runtime.yml` which in turn uses the `xplat-setup.yml` and so on.

**Comment by steveisok** [comment]
The jobs can now be triggered via `/azp run runtime-manual` as a result of https://github.com/dotnet/runtime/pull/61641
