### ISSUE TITLE
Extremly slow build & size explosion of assembly when compiling for WASM in AOT mode

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#61139]
### Description
I'm experimenting with adding WASM support to [Silk.NET](https://github.com/dotnet/Silk.NET) but when compiling my test application for WASM in AOT mode, the Silk.NET.Maths assembly bytecode file becomes >220MB large and takes 2454s to process.

### Configuration
Running on Windows 10, Ryzen 9 3900x

### Data
Original Assembly size: 307 kb
Bytecode file size: 220604 kb
Object file size: 110865 kb 

### Analysis
I believe this is due to the highly generic methods in this assembly
For example [Scalar.As](https://github.com/dotnet/Silk.NET/blob/main/src/Maths/Silk.NET.Maths/Scalar.As.cs) but pretty much any file in this project is "generic"
The methods aren't entirely generic, they are bound to be one of a few options, with any other type just throwing an exception.
It's possible this is related to the compiler trying to compile every possible usage combination.
The JIT only sees one type combination at a time, eliminating all type checks.

The project in [this folder](https://github.com/dotnet/Silk.NET/tree/main/src/Maths/Silk.NET.Maths) should be very easy to build, but I've attached the three files as well.
Unfortunately, GitHub doesn't allow me to upload, so a [Google Drive link](https://drive.google.com/file/d/1mBVv-VieoiXiHoOdZsB9mstdcvxy08Sr/view?usp=sharing) instead.

**Comment by jaykrell** [comment]
> I believe this is due to the highly generic methods in this assembly

Is it possible, I don't remember and I haven't looked..to at least test this theory, and get a build, which should work, might run slow, it should be possible to ask Mono AOT to explicitly not instantiate generics, except for the gshared/gsharedvt versions, like for object and struct, i.e. a maximum of two instantations per generic (maybe exactly 2).

Furthermore, what should be "easy", given that compile does succeed, even if it takes a while, you should be able to dump the results and count generic instantiations. This should almost just be a standard part of the logging, with varying verbosity, maybe just total generic instantations overall, one number.

**Comment by HurricanKai** [comment]
How would I do this? I can't seem to find any documentation on how to configure anything about the AOT process.

**Comment by HurricanKai** [comment]
I have noticed that a debug builds produces much smaller files, with the bc file "only" being 80mb

**Comment by vargaz** [comment]
[Silk.NET.Maths.dll.gz](https://github.com/dotnet/runtime/files/7517447/Silk.NET.Maths.dll.gz)

**Comment by vargaz** [comment]
Looks like the combination of the following:
- generics heavy code which causes the aot compiler to generate a lot of instances
- lots of methods are marked with aggressiveinline which slows down AOT time and leads to much larger bc files, since we don't do any cleanup on the generated .bc code.
- opt can't handle the .bc file (155mb)

**Comment by vargaz** [comment]
To repro, just run
mono-sgen --aot=llvmonly <dll>

**Comment by jkotas** [comment]
> generics heavy code which causes the aot compiler to generate a lot of instances
> lots of methods are marked with aggressiveinline which slows down AOT

These patterns are very unfriendly to AOT. While the runtime can do some incremental improvements, it is unrealistic to expect that libraries using these patterns will ever work great in environments without a JIT.

**Comment by HurricanKai** [comment]
What would be a way to make this better for AOT environments? I'm not aware of any other ways to accomplish generic operations like this.

**Comment by jkotas** [comment]
If the generics heavy assemblies do not use reflection (as is the case with Silk.NET.Maths), the first step is opt them into  IL trimming that in turn reduces amount of code that the AOT compiler has to compile. In .NET 6, this can be done by TrimmableAssembly ItemGroup to your project file:

```
<ItemGroup>
  <TrimmableAssembly Include="Silk.NET.Maths" />
</ItemGroup>
``

The details are in https://github.com/dotnet/linker/blob/main/docs/design/trimmed-assemblies.md#net-6

**Comment by MichalStrehovsky** [comment]
Since Silk.NET.Maths is a library, it might be better to set the IsTrimmable property on the library project itself: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

I think the `<IsTrimmable>` property might only take effect when targeting .NET 6. If you're targeting something else, just add a `[assembly:AssemblyMetadata("IsTrimmable", "True")]` attribute. It's equivalent and the result is that for apps targeting .NET 6+ with `PublishTrimmed` (default on WASM), the library will be trimmed by default.

I'm wondering how much of the extra generic size is caused by https://github.com/dotnet/runtime/issues/54849 - Silk.NET.Maths uses these patterns and this fix didn't make it to 6.0.

**Comment by HurricanKai** [comment]
That seems to have helped a lot! (< 5s)
I think it is related that in my current test project Silk.NET.Maths can be completely trimmed out, so I might end up having problems in more complex samples, but for now this should do.
Should I close this issue or should I leave it open to track this as a potential problem?
(I want to point out that Vector<T> also uses this pattern, not sure how that is dealt with)
Thanks again for the help, really appreciate it.

**Comment by jkotas** [comment]
It may be a good idea to mark Silk.NET assemblies with `[assembly:AssemblyMetadata("IsTrimmable", "True")]` so that people using them will get the trimming behavior by default. You can open an issue on it in Silk.NET repo if you agree.

Otherwise, I think this can be closed.
