### ISSUE TITLE
Enums are not considered blittable by Emscripten / Blazor WASM AOT

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#61144]
### Description

In P/Invoke callbacks, Enums are not considered blittable.
This means no enums can be used as parameters of P/Invoke callbacks.

### Reproduction Steps

Attempt to compile a method like
```cs
[UnmanagedCallersOnly]
public static void M(StringComparison myEnum) { }
```
using Emscripten / WASM AOT

### Expected behavior

The above code should be possible. Enums should be considered blittable.

### Actual behavior

An error is shown, enums are not considered blittable.

### Known Workarounds

Use the underlying type of the enum (usually int) instead and manually cast.

### Configuration

Tested in .NET 6 RC2

**Comment by lambdageek** [comment]
related to #61146

**Comment by lambdageek** [comment]
I think the code in the runtime handles this.  There just needs to be an IsEnum check in the pinvoke table generator.
