### ISSUE TITLE
[mono wasm] Passing arguments to entry point not working

### ISSUE THREAD

**Issue by andersson09** [dotnet/runtime#61145]
### Description

I'm running the wasm browser sample and am struggling to pass parameters using BINDING.call_assembly_entry_point("Wasm.Browser.Sample", ["Hello"]);

It's triggering the entry point successfully but not passing the parameters. For some reason the args.Length property is returning 6357060 when it should be 1.

### Reproduction Steps

Build wasm browser sample
-Rename Test class to Program
-Replace INTERNAL.call_static_method("[Wasm.Browser.Sample] Sample.Test:TestMeaning", []); with
BINDING.call_assembly_entry_point("Wasm.Browser.Sample", ["Hello"]); (note: INTERNAL doesn't work at all in this function).

### Expected behavior

args.Length returns 1 in console app
args are passed successfully

### Actual behavior

args.Length returns 6357060 
no args passed

**Comment by lewing** [comment]
try 
```js
BINDING.call_assembly_entry_point("Wasm.Browser.Sample", [["Hello"]], m);
```

**Comment by andersson09** [comment]
> try
> 
> ```js
> BINDING.call_assembly_entry_point("Wasm.Browser.Sample", [["Hello"]], "m");
> ```

Great, that worked thanks.
