### ISSUE TITLE
Half operator < (smaller) not working correctly

### ISSUE THREAD

**Issue by SiemerPasch** [dotnet/runtime#61141]
### Description

I try to compare two Half Values. Both has the same Value of -128. 
Now if i check that one is smaller than the other, it returns true. But there are the same Value

### Reproduction Steps

```
var a = (Half)-128f;
var b = (Half)-128f;

if(a < b) 
{
    // This Code is excecute
}
```

### Expected behavior

I expect that `a < b = false` is, when `a = b = -128`

### Actual behavior

`a < b = true`

### Configuration

.Net 5.0
Windows 10 x64

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/49983, which is fixed in .Net 6 (releasing in less than a week).

**Comment by danmoseley** [comment]
Thanks @svick i was just typing the same answer! @SiemerPasch is it possible for you to move to 6.0?

**Comment by SiemerPasch** [comment]
Thanks for your fast replay. I have not found the  #49983 Issue previous. I can validate that the Problem is done, when i use .Net 6.

**Comment by danmoseley** [comment]
Great -- hope you can update next week! .NET 5 will be out of support in 6 months from now, while .NET 6 will be in support through Nov 2024 (3 years)
https://dotnet.microsoft.com/platform/support/policy/dotnet-core
