### ISSUE TITLE
[wasm][debugger] Not able to evaluate a static class attribute

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#61147]
I created this class:
```
namespace BlazorApp65.Client
{
    public static class staticclass
    {
        public static string AppVersion = "thays";
    }
}

```
And added this code to Program.cs before `await builder.Build().RunAsync()`:
`staticclass.AppVersion = "thays2";`

And tried to evaluate on watch: `staticclass.AppVersion`.

Should work also if it's a non static class with a static attribute.

Related to https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1427267

**Comment by dkboon01** [comment]
Do we have when this will be fixed or a version of visual studio preview that it will be in?

**Comment by ilonatommy** [comment]
@dkboon01 thank you for your question. We are planning to have it in .net7 preview.

**Comment by dkboon01** [comment]
Do you have a date when that will be?

**Comment by ilonatommy** [comment]
Unfortunately we cannot provide a specific date. We will try to do it as soon as possible.
