### ISSUE TITLE
Application threads deadlock when throwing an exception

### ISSUE THREAD

**Issue by sksk571** [dotnet/runtime#61151]
### Description

We have a .NET Framework application that processes data in Cosmos DB using the V3 SDK (https://github.com/Azure/azure-cosmos-dotnet-v3). Recently we made an attempt to migrate this application to .NET5 and changed TFM from net472 to net5.0 (no other code changes was made). While the app works logically correct, after running for some time in production (several hours or sometimes days), it suddenly stops processing data.

We have captured several dump files of the process when it freezes and the threads in them appear to be waiting in the exception handling code:
Dump file 1
```
00 00000026`05cba5f8 00007ffc`08006121     ntdll!NtWaitForAlertByThreadId+0x14
01 00000026`05cba600 00007ffc`0805c824     ntdll!RtlAcquireSRWLockExclusive+0x131
02 00000026`05cba670 00007ffc`07ff4949     ntdll!RtlpCallVectoredHandlers+0x74
03 00000026`05cba710 00007ffc`07ff8ae6     ntdll!RtlDispatchException+0x69
04 00000026`05cba940 00007ffb`e8489329     ntdll!RtlRaiseException+0x316
05 00000026`05cbb800 00007ffb`e848941a     KERNELBASE!RaiseException+0x69
06 00000026`05cbb8e0 00007ffb`abb06f19     KERNELBASE!OutputDebugStringW+0xba
07 00000026`05cbb950 00007ffb`862a5a65     System_Private_CoreLib!Interop+Kernel32.OutputDebugString(System.String)$##6000044+0x59
```

Dump file 2
```
00 0000007c`b452fb68 00007ff8`251e6121     ntdll!NtWaitForAlertByThreadId+0x14
01 0000007c`b452fb70 00007ff8`2523c824     ntdll!RtlAcquireSRWLockExclusive+0x131
02 0000007c`b452fbe0 00007ff8`251d4949     ntdll!RtlpCallVectoredHandlers+0x74
03 0000007c`b452fc80 00007ff8`251d8ae6     ntdll!RtlDispatchException+0x69
04 0000007c`b452feb0 00007fff`d8c19329     ntdll!RtlRaiseException+0x316
05 0000007c`b4530d70 00007fff`b761d006     KERNELBASE!RaiseException+0x69
06 0000007c`b4530e50 00007fff`b761cad9     coreclr!RaiseTheExceptionInternalOnly+0x29a [D:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp @ 2806] 
07 0000007c`b4530f60 00007fff`5b4e45f0     coreclr!IL_Throw+0xd9 [D:\workspace\_work\1\s\src\coreclr\src\vm\jithelpers.cpp @ 4185] 
08 0000007c`b45310c0 000001e3`202fa900     0x00007fff`5b4e45f0
09 0000007c`b45310c8 00007fff`b7669f99     0x000001e3`202fa900
0a 0000007c`b45310d0 00007fff`5b031d17     coreclr!ExceptionNative::GetStackTracesDeepCopy+0x1a9 [D:\workspace\_work\1\s\src\coreclr\src\vm\comutilnative.cpp @ 206] 
0b 0000007c`b4531310 0000e2fb`7c767ee4     0x00007fff`5b031d17
0c 0000007c`b4531318 00007fff`b79548b0     0x0000e2fb`7c767ee4
0d 0000007c`b4531320 00000000`00000000     coreclr!HelperMethodFrame::`vftable'
```

### Reproduction Steps

No repro steps, the issue happens sporadically.

### Expected behavior

The application continues to function after migration from .NET 4.7.2 to .NET 5.

### Actual behavior

Application stops working after migration from .NET 4.7.2 to .NET 5.

### Regression?

Yes, the same application works without problems when compiled against .NET 4.7.2

### Configuration

- .NET 5.0.10
- Microsoft Windows Server 2019 Datacenter (Docker version from mcr.microsoft.com/dotnet/runtime:5.0-windowsservercore-ltsc2019)
- x64

**Comment by mangod9** [comment]
Hi @sksk571, are you able to share the dumps when the deadlock happens? That might help with diagnosing further. Thx

**Comment by sksk571** [comment]
@mangod9 these dump files contain sensitive production data. How can they be shared without disclosing it?

**Comment by mangod9** [comment]
if you could send it to my email (should be in my profile). If you are able to validate on .net 6 now that its released that would be good too.

**Comment by sksk571** [comment]
We moved the application to Linux AKS cluster and the issue stopped occuring. I still have the memory dump files demonstrating the issue, but it's not clear how to share them without disclosing sensitive data.

**Comment by mangod9** [comment]
Closing for now, if this repros again please reopen.
