### ISSUE TITLE
Question about of using goto in switch case of Linq.Where 

### ISSUE THREAD

**Issue by DaniilTS** [dotnet/runtime#61150]
I looked through the code of [Linq.Where](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Where.cs) and I don't understand why `goto case 2` is used in lines 114, 216, 322, 388 if the second case is always going after the first?
Can you explain it?

**Comment by EgorBo** [comment]
Pretty sure that code has to be rewritten to plain if-else. Maybe the original author expected it to be optimized into a jump-table (but it's too small for that).

**Comment by stephentoub** [comment]
> I don't understand why goto case 2 is used in lines 114, 216, 322, 388 if the second case is always going after the first?
Can you explain it?

C# doesn't allow for falling through from one case block to the next; without a "return", "break", "goto", etc. at the end of the block, it'll fail to compile.  So the "goto case 2" here mean "please fall through to the code immediately after".

https://github.com/dotnet/runtime/blob/65c943358b57f4df4161afbd5b8df7c551c58d51/src/libraries/System.Linq/src/System/Linq/Where.cs#L111-L116
