### ISSUE TITLE
Vector3.Dot sometimes return 0 instead of correct value in release mode

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#61154]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Vector3Dot-sometimes-return-0-instead-o/1564640)._

---
[severity:Other]
After upgrading to .Net 5.0 Vector3.Dot sometimes return instead of correct value in release mode. I do the following calculations (simplified in this example) multiple times in a subscription (Using System.Reactive 4.4.1, I have tried upgrade to 5 but it did not help) and after a while 0 is returned every time Vector3.Dot is called.

var first = new Vector3(0, 1, (float)-5.960465e-8);
        
var secondX = new Vector3(377, 0, 0);
var secondY = new Vector3(0, 377, 0);
var secondZ = new Vector3(0, 0, 327);

Vector3.Dot(first, secondX); // Is always 0
Vector3.Dot(first, secondY); // Should be 377, is after a while calculated to 0
Vector3.Dot(first, secondZ); // Should be -1.949072E-05, is after a while calculated to 0

When I replaced the call to Vector3.Dot with the following method the calculations are always correct.

private static float MyVector3Dot(Vector3 first, Vector3 second)
{
        return first. X * second. X + first. Y * second. Y + first. Z * second. Z;
}

---
#### Feedback Bot on 10/27/2021, 02:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Hilma Tivegård on 10/27/2021, 07:31 AM: 

<p>I have investigated this further, and the order of the calculations seems to matter. If I change the order of the calculations, so Vector3.Dot(first, secondY) is done first all three Vector3.Dot is calculated to 377. So the calculations seems to be done only on the first values all three times.</p>

---
### Original Solutions
(no solutions)

**Comment by tannergooding** [comment]
It would be helpful to have a repro here. The simple codegen looks correct and I can't repro with a simple example or a loop.

`DPPS` in .NET 5 is emitted as `vdpps tgt, left, right, 0x71`. `0x71` is `0b0111_0001` where the algorithm is:
```
IF (imm8[4] = 1)
    THEN Temp1[31:0]←DEST[31:0] * SRC[31:0]; // update SIMD exception flags
    ELSE Temp1[31:0]←+0.0; FI;
IF (imm8[5] = 1)
    THEN Temp1[63:32]←DEST[63:32] * SRC[63:32]; // update SIMD exception flags
    ELSE Temp1[63:32]←+0.0; FI;
IF (imm8[6] = 1)
    THEN Temp1[95:64]←DEST[95:64] * SRC[95:64]; // update SIMD exception flags
    ELSE Temp1[95:64]←+0.0; FI;
IF (imm8[7] = 1)
    THEN Temp1[127:96]←DEST[127:96] * SRC[127:96]; // update SIMD exception flags
    ELSE Temp1[127:96]←+0.0; FI;
Temp2[31:0]←Temp1[31:0] + Temp1[63:32]; // update SIMD exception flags
/* if unmasked exception reported, execute exception handler*/
Temp3[31:0]←Temp1[95:64] + Temp1[127:96]; // update SIMD exception flags
/* if unmasked exception reported, execute exception handler*/
Temp4[31:0]←Temp2[31:0] + Temp3[31:0]; // update SIMD exception flags
/* if unmasked exception reported, execute exception handler*/
IF (imm8[0] = 1)
    THEN DEST[31:0]←Temp4[31:0];
    ELSE DEST[31:0]←+0.0; FI;
IF (imm8[1] = 1)
    THEN DEST[63:32]←Temp4[31:0];
    ELSE DEST[63:32]←+0.0; FI;
IF (imm8[2] = 1)
    THEN DEST[95:64]←Temp4[31:0];
    ELSE DEST[95:64]←+0.0; FI;
IF (imm8[3] = 1)
    THEN DEST[127:96]←Temp4[31:0];
    ELSE DEST[127:96]←+0.0; FI;
```

This means that `x, y, z` are counted and the non-existent `w` field is ignored. The resulting SIMD register has `x` containing the result and `y, z, w` being `0`.

----------------------

There have been a few issues with the debugger corrupting values in the past, such as https://github.com/dotnet/runtime/issues/12875, so its possible this is related if the user is placing breakpoints and observing values in the watch window, for example.
