### ISSUE TITLE
can't parse french dates in alpine docker image while ok in focal

### ISSUE THREAD

**Issue by JeWaVe** [dotnet/runtime#61166]
### Description

Consider the following code : 

```
using System;
using System.Globalization;

namespace bugreport
{

    class Program
    {
        static void Main(string[] args)
        {

            string input = "1 février 2022";
            if (!DateTime.TryParseExact(input, "d MMMM yyyy", CultureInfo.GetCultureInfo("fr"), DateTimeStyles.None, out DateTime parsed))
            {
                Console.Error.WriteLine("error");
                return;
            }
            else
            {
                Console.WriteLine(parsed.ToString());
            }
        }
    }
}
```

It works well and logs `02/01/2022 00:00:00` when it runs in mcr.microsoft.com/dotnet/runtime:5.0-focal docker image. 
However, it logs `error` when it runs in `mcr.microsoft.com/dotnet/runtime:5.0-alpine`

### Reproduction Steps

take this piece of code
```
using System;
using System.Globalization;

namespace bugreport
{

    class Program
    {
        static void Main(string[] args)
        {

            string input = "1 février 2022";
            if (!DateTime.TryParseExact(input, "d MMMM yyyy", CultureInfo.GetCultureInfo("fr"), DateTimeStyles.None, out DateTime parsed))
            {
                Console.Error.WriteLine("error");
                return;
            }
            else
            {
                Console.WriteLine(parsed.ToString());
            }
        }
    }
}
```

run it a docker container deriv

### Expected behavior

This piece of code logs `02/01/2022 00:00:00`

### Actual behavior

This piece of code logs `error`

### Known Workarounds

using the `mcr.microsoft.com/dotnet/runtime:5.0-focal` docker image. 

### Configuration

contained in the docker image.

**Comment by Wraith2** [comment]
I believe that alpine does not contain ICU libraries (because they're quite large) and so the runtime functions in globalization invariant mode. Try adding this to your dockerfile:

```
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

**Comment by tarekgh** [comment]
@Wraith2 is right. Alpine images enable [Globalization Invariant Mode](https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md) which has globalization support limitation. follow @Wraith2 instructions installing ICU library and disable the globalization invariant mode, and everything should work fine. 

Note, in .NET 6.0, when having Invariant mode on, you'll not be able to create a culture like `CultureInfo.GetCultureInfo("fr")` except if you use a config switch `DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=false` or disable invariant mode.

**Comment by JeWaVe** [comment]
Great ! Thanks !

Maybe this should be somewhere in the doc though.
