### ISSUE TITLE
ValueTask.s_canceledTask can be disposed

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#61167]
### Description

After upgrading to .NET 6, we started seeing random failures with RabbitMQ.Client 3.6.9:

```
System.ObjectDisposedException: Safe handle has been closed.
 Object name: 'SafeHandle'.
    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
    at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
    at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout)
    at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
    at RabbitMQ.Client.Impl.SocketFrameHandler.Connect(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
    at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
    at RabbitMQ.Client.Framing.Impl.ProtocolBase.CreateFrameHandler(AmqpTcpEndpoint endpoint, Func`2 socketFactory, Int32 connectionTimeout, Int32 readTimeout, Int32 writeTimeout)
    at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 endpoints, String clientProvidedName)
```

The code of the failing method is:

```csharp
        private void Connect(ITcpClient socket, AmqpTcpEndpoint endpoint, int timeout)
        {
            IAsyncResult ar = null;
            try
            {
                ar = socket.BeginConnect(endpoint.HostName, endpoint.Port, null, null);
                if (!ar.AsyncWaitHandle.WaitOne(timeout, false))
                {
                    socket.Close();
                    throw new TimeoutException("Connection to " + endpoint + " timed out");
                }
                socket.EndConnect(ar);
            }
            catch (ArgumentException e)
            {
                throw new ConnectFailureException("Connection failed", e);
            }
            catch (SocketException e)
            {
                throw new ConnectFailureException("Connection failed", e);
            }
            finally
            {
                if (ar != null)
                {
                    ar.AsyncWaitHandle.Close();
                }
            }
        }
    }
```

It occured to me that this method shouldn't possibly fail _this way_, so I tried to understand what was happening. Notably, this method uses `TcpClient.BeginConnect`, which use the Begin/End methods of the socket. Those were changed in .NET 6 to map to `ConnectAsync` (https://github.com/dotnet/runtime/pull/43886). In the process, `AsTask()` is called on a ValueTask coming from a IValueTaskSource, so I focused on this specific code path and found a potential cause.

In some conditions, `AsTask()` will return a cached cancelled task (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs#L607). There is no guard to prevent this cached task from being disposed, which could explain the issue I'm seeing. 

Unfortunately I haven't found where the call to `Task.Dispose()` could be coming from, so I'm not 100% sure this is the exact issue I'm seeing. In any case, this is something that should be fixed.

### Reproduction Steps

```csharp
var taskSource = new TaskSource();

var task = new ValueTask(taskSource, 1).AsTask(); // Get the cached cancelled task
var asyncResult = (IAsyncResult)task;
var waitHandle = asyncResult.AsyncWaitHandle; // Extract the wait handle

new ValueTask(taskSource, 2).AsTask().Dispose(); // Get the cached cancelled task again and dispose it

waitHandle.WaitOne(); // Throws

class TaskSource : IValueTaskSource
{
    public void GetResult(short token)
    {
        throw new Exception();
    }

    public ValueTaskSourceStatus GetStatus(short token)
    {
        return ValueTaskSourceStatus.Canceled;
    }

    public void OnCompleted(Action<object?> continuation, object? state, short token, ValueTaskSourceOnCompletedFlags flags)
    {
    }
}
```

### Expected behavior

The cached task should not be disposable, just like `Task.CompletedTask`.

### Actual behavior

The cached task can be disposed.

**Comment by kevingosse** [comment]
Ok I figured out the bit I was missing, and it's a tad more tricky than disposing the task.

RabbitMq.Client is disposing the waithandle:

```
        private void Connect(ITcpClient socket, AmqpTcpEndpoint endpoint, int timeout)
        {
            IAsyncResult ar = null;
            try
            {
                ar = socket.BeginConnect(endpoint.HostName, endpoint.Port, null, null);
                // ...
            }
            finally
            {
                if (ar != null)
                {
                    ar.AsyncWaitHandle.Close();
                }
            }
        }
    }
```

Since the waithandle is on the shared task, it will be disposed for all callers.

**Comment by stephentoub** [comment]
> Since the waithandle is on the shared task, it will be disposed for all callers.

Note that this is the case even for Task.CompletedTask, e.g. this will throw an exception:
```C#
((IAsyncResult)Task.CompletedTask).AsyncWaitHandle.Dispose();
((IAsyncResult)Task.CompletedTask).AsyncWaitHandle.WaitOne();
```
We'd debated whether to try to address that a decade ago and decided it wasn't worth trying to special-case.

**Comment by kevingosse** [comment]
That's fair. Since `Task.CompletedTask` can't be disposed, I assumed it would be the same for the associated handle. I guess I'll just refrain from using this version of the library with .NET 6, it's pretty old anyway 👍
