### ISSUE TITLE
Content-Disposition encoding non-ASCII characters

### ISSUE THREAD

**Issue by MhdTlb** [dotnet/runtime#61183]
### Description

I'm migrating ASP.Net 4.6.2 project to .Net Core 3.1.
In my web app, I have a requirement to download Excel file after clicking a button.
The Excel file name contains non-ascii characters.
In .Net 4.6.2 web project, the download is fine and the file preserves the name that has non-ascii characters. However, in .Net Core 3.1, the file name was converted to Unicode characters.

### Reproduction Steps

If i try to download a file with this name: 枯渇日一覧.xlsx
In .Net 462, the HTTP response headers are:
```json
"headers": [
            "HTTP/1.1 200 OK",
            "Cache-Control: no-cache",
            "Pragma: no-cache",
            "Content-Type: Application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Expires: -1",
            "Server: Microsoft-IIS/10.0",
            "X-RequestId: bee7c0fd-79e3-4c65-90e1-bdb91c4b371e",
            "Content-DataType: byte-type",
            "%ESCAPED:​ Content-Disposition: attachment;filename=%E6%9E%AF%E6%B8%87%E6%97%A5%E4%B8%80%E8%A6%A7.xlsx;",
            "X-AspNet-Version: 4.0.30319",
            "X-XSS-Protection: 1; mode=block",
            "X-Powered-By: ASP.NET",
            "X-Content-Type-Options: nosniff",
            "Date: Wed, 03 Nov 2021 21:40:07 GMT",
            "Content-Length: 4350"
        ]
```

In .Net Core 3.1, HTTP response headers are:
```json
"headers": [
            "HTTP/1.1 200 OK",
            "Cache-Control: no-cache",
            "Pragma: no-cache",
            "Content-Length: 3609",
            "Content-Type: Application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Content-Encoding: gzip",
            "Server: Kinaxis-Gateway/1.0",
            "X-RequestId: dfba3797-63ed-4b7c-ab25-4f50db202623",
            "Content-DataType: byte-type",
            "X-Kinaxis-Resource-Change: true",
            "X-Content-Type-Options: nosniff",
            "X-Content-Type-Options: nosniff",
            "%ESCAPED:​ Content-Disposition: attachment;filename=%C3%A6%C2%9E%C2%AF%C3%A6%C2%B8%C2%87%C3%A6%C2%97%C2%A5%C3%A4%C2%B8%C2%80%C3%A8%C2%A6%C2%A7.xlsx;",
            "Content-Security-Policy: default-src...,
            "X-Frame-Options: SAMEORIGIN",
            "X-XSS-Protection: 1; mode=block",
            "X-Powered-By: ASP.NET",
            "Date: Wed, 03 Nov 2021 21:43:40 GMT"
        ]
```

### Expected behavior

I was expecting to have similar content-disposition.filename encoding.

### Actual behavior

`filename` encoding is different

**Comment by GrabYourPitchforks** [comment]
Sending this to _System.Net.Http_ folks. The _filename_ parameter seems to be encoded as if the original filename (as a string) was converted to UTF-8, then these UTF-8 bytes were converted back to a string using Latin-1, and finally this new string was escaped using UTF-8 and url-encoded.

**Comment by scalablecory** [comment]
This looks like a malformed response. "%ESCAPED" is not a thing, as far as I know.

**Comment by scalablecory** [comment]
> This looks like a malformed response. "%ESCAPED" is not a thing, as far as I know.

I think I misunderstood this, I assume now that the %ESCAPED is some sort of json convention. Do you have the original string available?

**Comment by MhdTlb** [comment]
@scalablecory I used chrome (chrome://net-export/) to capture network traffic while downloading files.
While debugging, i can see that the content-disposition header in HttpContext.Response.Headers was:
- For .Net Framework: "attachment;filename=枯渇日一覧.xlsx;"
- For .Net Core: "attachment;filename=æ\u009e¯æ¸\u0087æ\u0097¥ä¸\u0080è¦§.xlsx;"

I'm really sorry, i didn't explain issue well. So now i can see that in .Net Core, filename was already encoded and i assumed it was not. The main reason is .Net Core is making and HttpClient.SendAsync request to  .Net Framework to download the file.

`var httpResponseMessage = await httpClient.SendAsync(httpRequestMessage);`

After getting the `httpResponseMessage` from .Net Framework project, i was copying `httpResponseMessage.Content.Headers` to ASP.NET core HttpContext.Response.Headers and at that time, `content-disposition` header was encoded a second time. That's why I see different headers.

Is there a way to tell ASP.NET core `HttpContext.Response.Headers` that `content-disposition` header was already encoded? So it won't be encoded again.
Or can I decode `content-disposition` header in `httpResponseMessage.Content.Headers` (result from HttpClient.SendAsync)?
So, the client of .Net Core app will get filename encoded once not twice

**Comment by karelz** [comment]
@MhdTlb this question looks like duplicate of #61197 that you filed as well. Or is there some subtle difference?

**Comment by MhdTlb** [comment]
@karelz It's a duplicate

**Comment by karelz** [comment]
Duplicate of #61197

**Comment by Tratcher** [comment]
Note there's a standard for encoding non-ascii filenames in the content-disposition header called `filename*` and it's supported by ASP.NET Core and HttpClient.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#directives
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.contentdispositionheadervalue.filenamestar?view=net-5.0
https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.contentdispositionheadervalue.filenamestar?view=aspnetcore-5.0
