### ISSUE TITLE
Decode content-disposition header

### ISSUE THREAD

**Issue by MhdTlb** [dotnet/runtime#61197]
I'm writing a .Net Core(.Net Core 3.1) gateway project where i need to:

    

- Intercept an HTTP request from client (Browser and Mobile app).
- Make the request to ASP.NET MVC (Framework 4.6.2)
- Get the response from ASP .NET and forward it to the client

When the client downloads files with non-ASCII characters in the name, for example `こんにちは.xlsx` (Japanese characters), the gateway gets the file name encoded in content-disposition header from ASP.NET MVC. The header will be like:

`"attachment;filename=ã\u0081\u0093ã\u0082\u0093ã\u0081«ã\u0081¡ã\u0081¯.xlsx;"`

I'm using `HttpClient.SendAsync` to handle the download request from gateway to ASP.NET:

```c#
var httpResponseMessage = await httpClient.SendAsync(httpRequestMessage);
...
// copy all headers to a new response
httpResponseMessage.Content.Headers
```

So now, as a final step, I need to forward the `httpResponseMessage` to the client. To do that, I copy all headers and content to ASP.Net Core `HttpContext.Response`. When copying the content-disposition header it will be encoded again. And the client will get filename with uni-code characters instead of original characters: `ã__ã__ã_«ã_¡ã_¯.xlsx`

So I'm thinking about decoding the content-disposition header in the gateway before copying to` HttpContext.Response` where it will be encoded again. But i don't know how ASP.NET Framework 4.6.2 encodes that header. And if it is possible to decode it in ASP.Net core.

Any guidance how to fix this issue?

**Comment by karelz** [comment]
Did you consider leveraging existing gateway / reverse proxy? [YARP](https://github.com/microsoft/reverse-proxy) is fairly customizable. It may save you some time to deal with problems like these.

There is section on headers encoding on client and server side: https://microsoft.github.io/reverse-proxy/articles/http-client-config.html
It seems that Kestrel enables UTF-8 characters in response headers only in .NET 6.0: https://github.com/dotnet/aspnetcore/issues/4727

cc @Tratcher @MihaZupan

**Comment by karelz** [comment]
Overall, it would be great to provide more information on the byte flow and identify where it does not fit your scenario.
Check out what comes on the wire from your backend. Then check out what you receive from HttpClient. Is that the same? If not, this is the right repo to go deeper into it.
The next step would be to see how to pass that byte stream to Kestrel as response header. aspnetcore repo would be right place to route that question.

**Comment by Tratcher** [comment]
(copied from https://github.com/dotnet/runtime/issues/61183#issuecomment-961263472)

Note there's a standard for encoding non-ascii filenames in the content-disposition header called `filename*` and it's supported by ASP.NET Core and HttpClient.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#directives
https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.headers.contentdispositionheadervalue.filenamestar?view=aspnetcore-5.0
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.contentdispositionheadervalue.filenamestar?view=net-5.0

Using that should be easier than dealing with encodings for all headers.

**Comment by karelz** [comment]
Triage: Not actionable. There is better way to do it -- see above comment.
