### ISSUE TITLE
Don't generate guarded devirtualization for abstract classes

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#61190]
Stale PGO data might have information in it suggesting a class that is abstract is a likely class at some virtual callsite (because the class wasn't abstract when the PGO data was collected). Such information is obviously out of date and can be ignored because the devirtualization opportunity will never happen - abstract classes cannot be allocated.

Cc @AndyAyersMS this is tracking what we discussed over email.

**Comment by AndyAyersMS** [comment]
Thanks Michal. I have a fix I'll PR shortly.
