### ISSUE TITLE
[API Proposal]: Add `new()` for `TProxy` Parameter for `DispatchProxy.Create`

### ISSUE THREAD

**Issue by JasonBock** [dotnet/runtime#61206]
### Background and motivation

I was playing with `DispatchProxy`, and I noticed in the documentation for [`Create`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.dispatchproxy.create?view=net-5.0#System_Reflection_DispatchProxy_Create__2) that an `ArgumentException` is thrown if the type given in `TProxy` doesn't have a public parameterless constructor.

Couldn't this be checked with a `new()` generic constraint, so this would be caught at compile-time?

By the way, I'm not suggesting to remove the runtime check if the code I suggest in the "API Proposal" section is done, as someone could write Reflection-based code to invoke `Create()` like this:
```
var proxyType = typeof(DispatchProxy);
var createMethod = proxyType.GetMethod(nameof(DispatchProxy.Create), BindingFlags.Static | BindingFlags.Public)!;
var genericCreateMethod = createMethod.MakeGenericMethod(typeof(IThing), typeof(MyProxy));
var result = genericCreateMethod.Invoke(null, null);
```

### API Proposal

```C#
namespace System.Reflection
{
    public class DispatchProxy
    {
        public static T Create<T,TProxy> () where TProxy : DispatchProxy, new();
    }
}
```     

### API Usage

```C#
using System.Reflection;

public interface IThing { }

public class MyProxy
    : DispatchProxy
{
    internal MyProxy() { }

    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
    {
        throw new NotImplementedException();
    }
}

// This wouldn't compile
var proxy = DispatchProxy.Create<IThing, MyProxy>();
```     

### Risks

None that I can think of, but I'm sure there might be some.

**Comment by teo-tsirpanis** [comment]
Hello, adding a new generic constraint on an existing method would have been an unacceptable breaking change.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-changes.md

**Comment by KalleOlaviNiemitalo** [comment]
Is there already a Roslyn analyzer that can detect this mistake? Adding such an analyzer would not be a breaking change.

**Comment by JasonBock** [comment]
@KalleOlaviNiemitalo as far as I can tell, there isn't an analyzer (at least not with the default .NET analyzers included) that detects this. Ironically, I was looking at [building them](https://github.com/JasonBock/Transpire/issues/12) :).

**Comment by jnm2** [comment]
@teo-tsirpanis @jkotas Does that still apply when turning an already-existing runtime error into a compile-time error?

**Comment by KalleOlaviNiemitalo** [comment]
An application may contain a generic method that uses DispatchProxy.Create and does not have the new() constraint, but works at run time because the type arguments have parameterless constructors. Adding the constraint to DispatchProxy.Create would break the method in the app even though there was no problem at run time earlier.

**Comment by jnm2** [comment]
That makes sense. Could this be considered for .NET 7.0 then?

**Comment by KalleOlaviNiemitalo** [comment]
DispatchProxy.Create has `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)]` on the TProxy type parameter. I wonder if an analyzer that detects this flag and complains about missing constructors would raise too many false positives.

<https://github.com/dotnet/runtime/blob/4822e3c3aa77eb82b2fb33c9321f923cf11ddde6/src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxy.cs#L27-L40>

**Comment by KalleOlaviNiemitalo** [comment]
Are the generic constraints validated by the runtime (thus binary breaking) or only by the compilers (source breaking)?

**Comment by jnm2** [comment]
That makes a major version breaking change very much less palatable.

**Comment by jkotas** [comment]
> if an analyzer that detects this flag and complains about missing constructors would raise too many false positives.

It would generate some false positives for sure. For example, it would generate false positives for `ConditionalWeakTable`.

**Comment by KalleOlaviNiemitalo** [comment]
I see, ConditionalWeakTable has `GetOrCreateValue(TKey key)`, which uses the parameterless constructor, but that method might not be called for every _TValue_.

If GetOrCreateValue had been an extension method, then it could have had its own `where TValue : new()` constraint. 😔
