### ISSUE TITLE
Unrolled Vector128<T>.Count doesn't elide bounds check

### ISSUE THREAD

**Issue by HurricanKai** [dotnet/runtime#61207]
### Description
Even when only used within the unrolled context of a `Vector128<T>.Count` for loop GetElement & WithElement still incur a bounds check.

Code like this
```cs
using System.Runtime.Intrinsics;
public class C {
    public Vector128<int> M(Vector128<int> vec) {
        for (int i = 0; i < Vector128<int>.Count; i++)
            vec.WithElement(i, 1 + vec.GetElement(i));   
        return vec;
    }
}
```
[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgCUBXAOwwEt8YaBJFqVp3KzC4A3AFgAUMQDMlAEzkAwuQDek8hsqyAajDAZoVOQA4APPwwA+cgFkAFLv2GT5ltYBuegJSr1m/wBm0OR2FuSs5AC85KQi4eSm5I4GUEZmFpY0ihDMGHGsANQFXn7+ZeSeYDQA6qwYABYAogA2MBwsoWjkVOQFFXo0AOIwGC1tMB2sXl5xGqVlxADs/WDiEv4AvpIbQA) demonstrates this well.

It seems for some reason JIT doesn't seem that these comparisons are constant and emits them together with the branches.

**Comment by SingleAccretion** [comment]
FWIW, I see no bounds checks in the current codegen:
```asm
       vmovupd  xmm0, xmmword ptr [rdx]
       mov      eax, dword ptr [rdx]
       inc      eax
       vmovapd  xmmword ptr [rsp], xmm0
       mov      dword ptr [rsp], eax
       vmovupd  xmm0, xmmword ptr [rdx]
       mov      eax, dword ptr [rdx+4]
       inc      eax
       vmovapd  xmmword ptr [rsp], xmm0
       mov      dword ptr [rsp+04H], eax
       vmovupd  xmm0, xmmword ptr [rdx]
       mov      eax, dword ptr [rdx+8]
       inc      eax
       vmovapd  xmmword ptr [rsp], xmm0
       mov      dword ptr [rsp+08H], eax
       vmovupd  xmm0, xmmword ptr [rdx]
       mov      eax, dword ptr [rdx+12]
       inc      eax
       vmovapd  xmmword ptr [rsp], xmm0
       mov      dword ptr [rsp+0CH], eax
       vmovupd  xmm0, xmmword ptr [rdx]
       vmovupd  xmmword ptr [rcx], xmm0
       mov      rax, rcx
```
It is surprising to see `WithElement`s not being handled intrinsically; will chalk it up to something being wrong in my environment.

**Comment by JulieLeeMSFT** [comment]
Cc @dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
@EgorBo PTAL bound check related issue.

**Comment by JulieLeeMSFT** [comment]
Moving to .NET 8 becasue .NET 7 code complete is only one month away.
