### ISSUE TITLE
Question: when would System.IO.FileNotFoundException get thrown?

### ISSUE THREAD

**Issue by dxynnez** [dotnet/runtime#61248]
Hi team,

We recently encountered the following exception seems to be indicating the dll cannot be found in the file system. 
```
System.IO.FileNotFoundException: 
File name: 'Microsoft.Skype.Seatbelt.Core, Version=6.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Skype.ECS.Client.ECSClientCore.Initialize(ECSClientConfiguration configuration, IEnumerable`1 requiredAgents)
```
But normally when the dll is missing I would expect the FileNotFoundException includes message like 'Could not load file or assembly... The system cannot find the file specified.'

Can someone let me know when the FileNotFoundException would be thrown without the **'Could not load file or assembly... The system cannot find the file specified.'** message? I am just trying to confirm this is indeed storage related as we do see some bad indicator for our storage when the exception was thrown.

**Comment by vitek-karas** [comment]
You can probably use tracing to get detailed info on why the assembly load failed: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/collect-details

There are cases where the runtime throws `FileNotFoundException` even if the file actually exists, but there are other problems with loading the assembly. It's hard to tell exactly which case it is though. The tracing above will determine the real cause for sure.

**Comment by dxynnez** [comment]
Thanks @vitek-karas ! We are on net core 3.1 and our services are hosted on azure app service so it would be a bit hard for us to collect those trace...

Is there any detailed document that mentioned all the possible causes of the FileNotFoundException? This happened during an app service storage upgrade event which involved demount / remount of the storage per my understanding...

I would love to gather more information before talking to app service.

**Comment by dxynnez** [comment]
Hi @vitek-karas , could you shed some light here?

**Comment by vitek-karas** [comment]
Hmm - I remember writing a response.. but apparently I forgot to send it 😢 

Unfortunately there's no documentation for the details. Runtime groups several different underlying OS errors into this exception. The best I could find is this:
https://github.com/dotnet/runtime/blob/e64cce6fbbde72d1ea61010bd08f11ba7b51afc9/src/coreclr/vm/rexcep.h#L164-L174

It's basically the list of HRESULT error codes which will all end up throwing `FileNotFoundException`.
