### ISSUE TITLE
[mono] class-setup-vtable.c:1747, condition `is_ok (error)' not met, function:mono_class_setup_vtable_general, VAR 1 (T) cannot be expanded in this context with 1 instantiations

### ISSUE THREAD

**Issue by JinShil** [dotnet/runtime#61244]
### Description

Using Blazor WebAssembly project.  I have a class hierarchy that seems to cause an assertion failure in the mono runtime.  I've created a solution and reduced the code as much as I can and attached it to this issue.  The project works fine in a Blazor Server (non-WebAssembly) project.

The projects were created with Visual Studio 2022 using the 6.0.100-rc.2.21505.57 SDK.

[ComfileTech.Framework.zip](https://github.com/dotnet/runtime/files/7481347/ComfileTech.Framework.zip)

### Reproduction Steps

Open the attached solution and run the project ending in ".Server" (ASP.Net hosted Blazor Web Assembly project).  View the result in a web browser.

### Expected behavior

No assertion failure.

### Actual behavior

Assertion failure.  See image below:

![image](https://user-images.githubusercontent.com/6023641/140473671-e08f560c-65f4-4e00-aec9-2f94ff49afea.png)

### Regression?

I have not tested this code in a prior version of the .Net Framework.

### Known Workarounds

No known workarounds.

### Configuration

6.0.100-rc.2.21505.57
Tested on Windows 10 64bit
Tested using the Brave web browser.

**Comment by lewing** [comment]
cc @lambdageek

**Comment by JinShil** [comment]
A little more information:  I tried with the latest .Net 6 SDK release (6.0.100) and the problem persists.

I attempted to work around the issue by added `<RunAOTCompilation>true</RunAOTCompilation>` to the `.Client` project and it resulted in the following error.

```
Assertion at D:\a\_work\1\s\src\mono\mono\metadata\class-setup-vtable.c:1747, condition `is_ok (error)' not met, function:mono_class_setup_vtable_general, VAR 1 (T) cannot be expanded in this context with 1 instantiations
```

**Comment by lambdageek** [comment]
Standalone console repro https://gist.github.com/lambdageek/f0492bf5c890280943ca93ff0cef227d - there's probably more code that can be removed

**Comment by lambdageek** [comment]
It's the override that implements ``ComfileTech.Framework.IGetSetChangeValue`1<T>:add_Changing (System.Action`1<ComfileTech.Framework.IChangeEventArgs`2<ComfileTech.Framework.IGetSetChangeValue`1<T>, T>>)`` with ``ComfileTech.Framework.IGetSetChangeValue`2:ComfileTech.Framework.IGetSetChangeValue<T>.add_Changing (System.Action`1<ComfileTech.Framework.IChangeEventArgs`2<ComfileTech.Framework.IGetSetChangeValue`1<T>, T>>)``

ie, it's here:

```csharp
    public interface IGetSetChangeValue<out TProperty, T> : IGetChangeValue<TProperty, T>, IGetSetChangeValue<T>
        where TProperty : IGetSetChangeValue<TProperty, T>
    { 
        new event Action<IChangeEventArgs<TProperty, T>>? Changing;
        new event Action<IChangeEventArgs<TProperty, T>>? Changed;

        event Action<IChangeEventArgs<IGetSetChangeValue<T>, T>>? IGetSetChangeValue<T>.Changing  
        {
            add { Changing += (Action<IChangeEventArgs<TProperty, T>>?)value; }      // this override
            remove { Changing -= (Action<IChangeEventArgs<TProperty, T>>?)value; }
        }
```

**Comment by lambdageek** [comment]
Shorter repro

```csharp
using System;


public interface I1<T> {
    void Foo (I1<T> x);
}

public interface I2<TSelf,T> : I1<T> where TSelf : I2<TSelf, T> {
    void I1<T>.Foo (I1<T> x) {
	throw new Exception ("e");
    }
}

public class C : I2<C, int> {
    
}

public class Program {
    public static void Main () {
	var isMono = typeof(object).Assembly.GetType("Mono.RuntimeStructs") != null;
	Console.WriteLine ($"isMono = {isMono}");

	I2<C,int> v = new C();
	v.Foo(null!);
    }
}
```

(with these additions to the .csproj)
```csproj
  <PropertyGroup>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
    <UseMonoRuntime>true</UseMonoRuntime>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
```

**Comment by matthewslesinski** [comment]
I've also encountered this issue. When trying to understand what causes this so I could know what to change in the project I'm writing, I've condensed the above shorter repro into an even shorter one. In case it helps, I figured I'd post it.
`public interface I1<T>
    {
        void Foo();
    }

    public interface I2<T, T2> : I1<T>
    {
        void I1<T>.Foo()
        {
            Console.WriteLine("Error not reproduced");
        }
    }

    public class C : I2<int, int>
    {
    }

    public class Program
    {
        public static void Main()
        {
            var isMono = typeof(object).Assembly.GetType("Mono.RuntimeStructs") != null;
            Console.WriteLine($"isMono = {isMono}");

            I1<int> v = new C();
            v.Foo();
        }
    }`

Also, any idea when this might be fixed?

**Comment by JamesYFC** [comment]
In Unity's Mono at least, I don't even need to call `Foo()` to get this error. Just the instantiation line will trigger it.
