### ISSUE TITLE
OnAfterRenderAsync code not executed

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/runtime#61255]
In the attached screen cap below, breakpoints inside the outer `if` statement are not loaded.
Note `firstRender` is true as shown in the watch window.
When I press F5 the next statement that executes is `await base.OnAfterRenderAsync(firstRender)`.
Since `firstRender` is true I expect the code in the `if` block to execute.
Why is it not executing?  How can I fix this or work around it?

![Capture](https://user-images.githubusercontent.com/16885210/140523671-49022966-cf7b-44ae-8537-8548e72515ca.PNG)

## Update
I think this is a bug.  I assigned `firstRender` to a new variable and it works:

![Capture2](https://user-images.githubusercontent.com/16885210/140525800-34cd0b4e-7ff0-4cf6-9bd8-c8ccc73fd347.PNG)

C:\Users\sam>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.402
 Commit:    e9d3381880

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.402\

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.11" 
PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.11" PrivateAssets="all"

**Comment by sam-wheat** [comment]
@javiercn Thanks for your response - I don't believe that is the case at all.  Please see my update.

**Comment by huoyaoyuan** [comment]
In your first screenshot, the icon indicates that the debugger can't map your statement into compiled code. There should be something wrong between compiler/debugger. You may do a clean build and see what happens.

**Comment by sam-wheat** [comment]
@huoyaoyuan The code in the first screenshot was not executing before I put a breakpoint on it.  That is why I was debugging it.  The problem, I believe, is between source/compiler.

**Comment by tommcdon** [comment]
Hi @sam-wheat! The hollow red circle with the [yellow exclamation point](https://docs.microsoft.com/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2019) means that the breakpoint didn't bind.  If you hover over the breakpoint with the mouse, Visual Studio should show the description as to why the breakpoint didn't bind.  Some common reasons why breakpoints do not bind are related to debugging Release code (configuration not set to Debug).  In release mode, both Roslyn and the .NET Runtime perform code optimizations that can cause some source lines to have no mapping to executable code.  Please check the [modules window](https://docs.microsoft.com/visualstudio/debugger/how-to-use-the-modules-window?view=vs-2019) to see if the code being debugged is optimized.  If after reviewing the common reasons for breakpoint binding issues do not resolve the issue, would it be possible to provide a small, reproducible test case we could use to investigate?

**Comment by sam-wheat** [comment]
@tommcdon Hi Tom, I understand what you are saying about breakpoints not being hit.  I run into that fairly often.
The point I am trying to convey here is that the code did not execute - something very different than the breakpoint not being hit.  I will just close this out now since it seems to be a transient feature and I can not reproduce it at will.
