### ISSUE TITLE
[API Proposal]: RetryOnConnectionFailure

### ISSUE THREAD

**Issue by jrahma** [dotnet/runtime#61257]
### Background and motivation

Hi,

Please add RetryOnConnectionFailure to the HttClient without having to use rendered.

For example:

```c#
HttpClient httpClient = new HttpClient();
httpClient.RetryOnConnectionFailure = true;

```

Apps crashing on Android with OkHttp error which you need to do a lot of code in the platform level but it will be easier when you make it within HttpClient and it will solve a lot of pain for the developers.

**Comment by huoyaoyuan** [comment]
Although auto-retrying is useful, it can't solve any problem at all.

> it will solve a lot of pain for the developers

In case of losing connection, retrying repeatedly will cause a dead lock.

I/O operations may fail under *any* situation, and you should *always* guard for it, including file and network. Non one-shot living applications should be always prepared for network failure.

**Comment by jrahma** [comment]
> Although auto-retrying is useful, it can't solve any problem at all.
> 
> 
> 
> > it will solve a lot of pain for the developers
> 
> 
> 
> In case of losing connection, retrying repeatedly will cause a dead lock.
> 
> 
> 
> I/O operations may fail under *any* situation, and you should *always* guard for it, including file and network. Non one-shot living applications should be always prepared for network failure.

But if we don't have that then app keep crashing when the user quickly navigate between pages on android. This problem doesn't exist on iOS so I am sure there will be something to do to fix it

**Comment by huoyaoyuan** [comment]
> then app keep crashing

It the responsibility for the web control to not crash in case of network failure.

> when the user quickly navigate between pages

I think there are something more severe than network failure. Under well connected network, intensive requests should be blocked but does not crash.

**Comment by karelz** [comment]
@steveisok @akoeplinger can you please triage it?

**Comment by karelz** [comment]
@steveisok @akoeplinger ping?

**Comment by akoeplinger** [comment]
@karelz it doesn't look specific to Android to me, but it's hard to say without more info about what exactly this is supposed to solve.

**Comment by scalablecory** [comment]
Auto-retry is currently left up to the operating system. For instance, on Windows you can control how many times it will attempt a TCP handshake before giving up.

Do any of .NET's platforms (including Android) not have such a retry mechanism? This might be interesting to look at -- maybe we'd code some retry for those platforms for better consistency, or maybe we'd see that e.g. Android designed their `connect()` behavior very specifically to be generally "good" for the mobile scenario.

I'm not sure how much control we have on guaranteeing a specific retry count; a setting on `HttpClient` would likely need to act more like a vague multiplier on whatever the OS does.

In much of my `HttpClient` experience, it has been beneficial to introduce some mechanism of "retry in case of transient error" -- but typically this is at a much higher level than specifically TCP being connected. In such a design, this sort of feature wouldn't really have much use. But, I can sort of see the use for other, specifically _interactive_, cases.

@jrahma, it would be useful to show how painful it is to achieve this today, as well as more specifics on what scenarios you're looking at. I imagine one could use `ConnectCallback` for some platforms, or some sort of exception inspection on others. Perhaps Polly makes this a two-liner.

**Comment by wfurt** [comment]
Triage: We can look into retry policy but we probably need some more specific use case. Probably not linked to `HttpClient` but to specific handler. It may be better to leave to application as it may have more insight to what is reasonable.

**Comment by ManickaP** [comment]
I don't think we should consider something like, at least not because of this one particular case.

There's not much details about the "crashes". @jrahma Could you share more info? You say you need to do a lot of Android specific work to work around this problem, whereas on iOS you don't because it just work? If that's the case, then there's no need to add an API to `HttpClient`. This might be just a bug report for Android specific platform handler (or the problem might be somewhere else).

On the side note of general retries, currently we do not have any logic for retries in `HttpClient`. If the user needs retries, whether for connection failures or for more high-level reasons (application logic), we generally recommend Polly. It's super easy to design your own retry conditions, counts, fallback, etc. with it. So there's no need to copy some of this logic into `HttpClient`.
