### ISSUE TITLE
Visual studio 2019  F# break points ignored

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#61270]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-studio-2019--F-break-points-igno/1567661)._

---
[severity:It's more difficult to complete my work]
I have a Blazor WASM application that calls an F# library.

I can set break points in the F# code, but VS 2019 debugger does not stop in the F# code.

! [image.png] (https://aka.ms/dc/image?name=Ba3f6f53888a4420eab80fa2d34b9bfb4637712095480652812_20211030-125226-image.png&tid=a3f6f53888a4420eab80fa2d34b9bfb4637712095480652812)

---
#### Feedback Bot on 10/31/2021, 07:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by lewing** [comment]
@thaystg you verified this works in VS2022 and .NET 6.0 correct?

**Comment by thaystg** [comment]
Yes, it's correctly working on Vs2022 using .net6.
![image](https://user-images.githubusercontent.com/4503299/140584727-18f099b5-5764-4a1d-93b6-b9ff93a765c7.png)

**Comment by thaystg** [comment]
I'll close the issue, if there is still a problem on .net6 please reopen it.
