### ISSUE TITLE
[wasm] avoid eval, design better API for InvokeJS

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#61287]
After change https://github.com/dotnet/runtime/pull/61212 Rollup started producing warning about eval.
```
(!) Use of eval is strongly discouraged
  https://rollupjs.org/guide/en/#avoiding-eval
  method-calls.ts
```

We could suppress it globally, but it's not ideal.
```
{
  onwarn(warning, warn) {
    if (warning.code === 'EVAL') return
    warn(warning)
  }
}
```

As @lewing  [suggested](https://github.com/dotnet/runtime/issues/61192), we should consider deprecating the method, since it's only internal API.

**Comment by pavelsavara** [comment]
@kg said in chat:
"maybe we solve it with source generators and then you can invoke that with the new invoke api
use an icall to register each invokejs blob at startup
and then those have unique ids you use to invoke them
that would let us use `new Function` since it's once"

**Comment by ilonatommy** [comment]
@pavelsavara, @maraf, have you tried using the idea with new API? Any thought on that?

**Comment by pavelsavara** [comment]
This is related to CSP and I think we would be able to at least reduce it.
