### ISSUE TITLE
[API Proposal]: Extend ManagementObjectSearcher with Async methods

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#61290]
### Background and motivation

My personal experience is that the WMI interface is quite slow. 
On the C# side there is not much to optimize... 

Because of this fact, I think it is very important that asynchronous methods are implemented.

I know that there are many possibilities via the Windows API that are more performant than WMI, but I still think that something like this should be implemented.

### API Proposal

```cs
namespace System.Management
{
    [ToolboxItem(false)]
    public class ManagementObjectSearcher : Component
    {
        // Already implemented:
        // public ManagementObjectCollection Get();

        // Proposal:
        public Task<ManagementObjectCollection> GetAsync(CancellationToken cancellationToken = default);
    }
}
```     

### API Usage

```cs
var managementObjectSearcher = new ManagementObjectSearcher("root\\CIMV2", "SELECT * FROM Win32_Service");
var managementObjectCollection = await managementObjectSearcher.GetAsync();
foreach(var object in managementObjectCollection) {
    // ...
}
```     

---

Alternative proposal:
```cs
var managementObjectSearcher = new ManagementObjectSearcher("root\\CIMV2", "SELECT * FROM Win32_Service");
await foreach(var object in managementObjectSearcher.GetAsync()) {
    // ...
}
```

### Alternative Designs

```C#
namespace System.Management
{
    [ToolboxItem(false)]
    public class ManagementObjectSearcher : Component
    {
        // Already implemented:
        // public ManagementObjectCollection Get();

        // Proposal:
        public IAsyncEnumerable<ManagementBaseObject> GetAsync(CancellationToken cancellationToken = default);
    }
}
```     

### Risks

We do not interfere with currently existing methods and therefore there is no risk.

**Comment by danmoseley** [comment]
@deeprobin this API is very much legacy -- I am not a domain expert but I believe newer code is expected to use MMI. We don't plan to add new features to this library. Can you use MMI?

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/mi-managed-api/hh832958(v=vs.85)
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/wmi_v2/what-s-new-in-mi#mi-features

**Comment by danmoseley** [comment]
Or if your interest is more casual (just spotted possible optimization) you may want to focus on more actively developed libraries. there are plenty of issues labeled up for grabs.

**Comment by Nuklon** [comment]
@danmoseley 
https://github.com/dotnet/runtime/issues/59844#issuecomment-968085927

**Comment by deeprobin** [comment]
@danmoseley @Nuklon 
According to the fact that WMI is very slow and under Windows 11 not even `wmic` is available anymore, I think you should think about marking Windows.Management as obsolete and possibly include code fixers which automatically convert simple SELECT statements into a performant alternative.

**Comment by Nuklon** [comment]
@deeprobin Pointless comment, has nothing to do with what reported here.
