### ISSUE TITLE
Test failure Loader/classloader/DictionaryExpansion/DictionaryExpansion/DictionaryExpansion.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61299]
Run:[ runtime 20211107.13](https://dev.azure.com/dnceng/public/_build/results?buildId=1458388&view=ms.vss-test-web.build-test-results-tab&runId=41921704&resultId=100313&paneView=debug)

Failed test:
```
Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open

- Loader/classloader/DictionaryExpansion/DictionaryExpansion/DictionaryExpansion.sh

```
**Error message:**
```
11-06 21:59:32.724 21938 21955 E mono    : Unhandled Exception:
      11-06 21:59:32.724 21938 21955 E mono    : System.IO.FileNotFoundException: Could not load file or assembly 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.
      11-06 21:59:32.724 21938 21955 E mono    : File name: 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
      11-06 21:59:32.724 21938 21955 E mono    :    at GenClass`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DoTest_GenDerived(Int32 max)
      11-06 21:59:32.724 21938 21955 E mono    :    at Test_DictionaryExpansion.Main()
      11-06 21:59:32.724 21938 21955 E DOTNET  : UnhandledException: System.IO.FileNotFoundException Could not load file or assembly 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.    at GenClass`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DoTest_GenDerived(Int32 max)
      11-06 21:59:32.724 21938 21955 E DOTNET  :    at Test_DictionaryExpansion.Main()
```

**Comment by krwq** [comment]
cc: @jkoritzinsky

**Comment by jkoritzinsky** [comment]
Looks like xunit doesn't get uploaded with the tests for Android testing. @fanyang-mono how is the set of assemblies uploaded for runtime tests determined?

**Comment by fanyang-mono** [comment]
It is very strange that only this particular test failed with this error, because all other runtime tests finished successfully, which also depends on this assembly. I wonder if this test would fail with the same error message constantly?

**Comment by jkoritzinsky** [comment]
It looks like it is failing consistently: https://github.com/dotnet/runtime/issues/61322

**Comment by jkoritzinsky** [comment]
Majority of the other tests that now use xunit are probably disabled on Mono (most of them are the interop tests and issues.targets has many interop test exclusions on Mono)

**Comment by krwq** [comment]
@fanyang-mono can you please disable based on the fact it consistently fails on rolling builds?

**Comment by fanyang-mono** [comment]
Now I understand why this test started failing lately. It was because of this change https://github.com/dotnet/runtime/pull/61226. This is code to decide what should be included in an Android app https://github.com/dotnet/runtime/blob/8fdd22d33e3a6091c9a26be97dc1e9c73c775df7/src/tests/build.proj#L211-L234.

**Comment by jkoritzinsky** [comment]
@fanyang-mono i can also take a look at a fix now that you’ve pointed me to the place that files are included into the Android app.
