### ISSUE TITLE
Does the TPL Dataflow support the ImmediateTaskScheduler?

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#61318]
Hi! I would like to ask if the TPL Dataflow library supports configuring blocks with a custom [`TaskScheduler`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler), that "schedules" the execution of the tasks on the current thread. Such a `TaskScheduler` can be implemented trivially like this:

```C#
private class ImmediateTaskScheduler : TaskScheduler
{
    protected override void QueueTask(Task task) => TryExecuteTask(task);
    protected override bool TryExecuteTaskInline(Task task,
        bool taskWasPreviouslyQueued) => TryExecuteTask(task);
    protected override IEnumerable<Task> GetScheduledTasks() { yield break; }
}
```

I am asking this question because I am encountering a deadlocking behavior, when trying to use this `TaskScheduler` in a dataflow pipeline with multiple producers and backpressure.

The reason that I would like to use such a scheduler is because I would like to reduce the latency and the friction at the entry point of a busy pipeline, that has to do a trivial calculation at the entry point. Essentially I want to associate each message with an incremented ID at the entry point:

```C#
int currentIndex = 0;
var entryPoint = new TransformBlock<TInput, (int, TInput)>(item =>
{
    return (currentIndex++, item);
}, new ExecutionDataflowBlockOptions()
{
    TaskScheduler = new ImmediateTaskScheduler(),
    BoundedCapacity = 1
});
```

Scheduling this trivial calculation on the `ThreadPool`, and introducing an additional input/output buffer in the (already long) pipeline, seems like an overhead that I should be able to avoid. Hence my idea of doing the calculation synchronously, when a message is offered to the block. I expected that the message would be propagated synchronously to the next linked block with minimal friction, unless the next block is currently full and the backpressure mechanism kicks in. And this is pretty much what's happening. But during the stress test the pipeline has a tendency to deadlock, as demonstrated by [this](https://dotnetfiddle.net/aGAjFj) minimal example. Occasionally (not very frequently) I get output like this:

```none
...
16:04:04.028 [8] > Worker #5 failed: The operation has timed out.
16:04:04.028 [8] > Worker #2 failed: The operation has timed out.
16:04:04.029 [8] > Worker #1 failed: The operation has timed out.
16:04:04.029 [8] > Worker #3 failed: The operation has timed out.
16:04:05.365 [1] > Timeout
```

So I am not sure if what I am doing is a supported scenario in TPL Dataflow. Have I stretched the TPL Dataflow library beyond its limits?

**Comment by stephentoub** [comment]
No.  It expects that when it queues work it'll actually be queued, not invoked as part of the queueing operation.  There are lots of scheduler variations that can break most asynchronous libraries that expect queueing actually means queueing.

**Comment by theodorzoulias** [comment]
@stephentoub OK, thanks. Good to know. :-)

**Comment by theodorzoulias** [comment]
Btw I just found that the Rx library includes an [`ImmediateScheduler`](https://github.com/dotnet/reactive/blob/main/Rx.NET/Source/src/System.Reactive/Concurrency/ImmediateScheduler.cs), that can cause similar problems in some situations:

[Possible bug: Repeat observables using "Immediate Scheduler"](https://social.msdn.microsoft.com/Forums/en-US/f9c1a7a6-d6a3-44fd-ba8c-e6845b1717b2/possible-bug-repeat-observables-using-quotimmediate-schedulerquot?forum=rx)

The accepted answer of that question:

> This is by design. `Observable.Return` by default uses the `Immediate` scheduler which is blocking. Because of this, the `Take(1)` operator never gets a hold of the subscription disposable object. The `CurrentThread` scheduler is there exactly to avoid this situation. At some point `CurrentThread` was the default scheduler for many operators. We found however that introducing any kind of concurrency, even giving queue semantics instead of stack semantics needs to be an explicit decision, we made `Immediate` the default scheduler where possible.
(Jeffrey van Gogh - MS, August 23, 2010)
