### ISSUE TITLE
Array.Sort() can drop items if exception thrown mid-swap

### ISSUE THREAD

**Issue by stevenaw** [dotnet/runtime#61340]
### Description

When sorting an array of four `Tuple<T1, T2>` in-place on .NET 4.5+ an exception will be thrown if all properties are not of type `IComparable`. The exception is expected, however in the below code snippet it appears the exception may be thrown in the middle of swapping items. One of the items is no longer in the array after the exception is thrown and another item appears twice. This occurs when sorting an array directly or through another data structure (like `ArrayList.Sort()` or `List<T>.Sort()`).

This was noted in NUnit in the following comment: https://github.com/nunit/nunit/issues/3976#issuecomment-961729079

### Reproduction Steps

Console.WriteLine($"Contains all original items: {ContainsAllOriginalItems()}");

static bool ContainsAllOriginalItems()
{
    object message3 = new();
    object message4 = new();

    var tupleA = Tuple.Create(1, message3);
    var tupleB = Tuple.Create(2, message3);
    var tupleC = Tuple.Create(1, message4);
    var tupleD = Tuple.Create(2, message4);

    var actual = new[]
    {
        tupleA, tupleB, tupleC, tupleD
    };

    try
    {
        Array.Sort(actual);
    }
    catch (InvalidOperationException) { }

    return actual.Contains(tupleC);
}

### Expected behavior

I would expect that the array may not be in the original order, but that all items are still in the array.

### Actual behavior

The third item, `tupleC` is no longer in the array. It has been replaced by `tupleB` which now appears both as both second and third elements.

### Regression?

This is not reproducible in .NET4 and appears to have been introduced in .NET 4.5.

### Configuration

The above scenario has been tested on .NET 4, .NET 4.5, .NET 5 and .NET 6 (all Windows x64). I don't believe it's specific to the configuration.

**Comment by Clockwork-Muse** [comment]
Conceptually speaking, `InvalidOperationException` (along with a few similar ones, like NPE/`ArgumentException`) is a "halt and catch fire" error - there's no reasonable thing that can be done to recover and retry, and the only way forward is to get the programmer to fix it.  Here, you'd have to somehow change the type of the underlying object during the program run, but there's not a good way for a program to make a general decision about that.

In this case (and to an extent with all exceptions), datastructures being in an undefined state is both reasonable and expected.

**Comment by danmoseley** [comment]
If it has been this way since .NET Framework 4.5 that is evidence this is not widespread impact.

@stevenaw thanks for logging the issue. Is it satisfactory for NUnit to work around this (stop triggering it)?

**Comment by stevenaw** [comment]
Thanks @danmoseley and @Clockwork-Muse for your thoughts here. 

Agreed, this is certainly an edge case triggered under very specific conditions and has been around for a while without having much impact. Changing types or reordering of props within a type is a bit more complicated in our case since NUnit doesn't have control over the data passed to it nor can it easily detect this ahead of time, though we're already exploring a couple verified options to work around it.

Thanks again for your time and attention (and apologies for this having come up on launch day).

Cheers.

**Comment by danmoseley** [comment]
@stevenaw no apologies requires quite the opposite you are welcome here and it is good to have these discussions.
I will close this based on the thoughts above. Returning to old behaviors and documenting it would potentially constrain internal optimization in the future. The important thing is the exception is helpful for fixing the bug in the caller.
