### ISSUE TITLE
wasm aot compilation failed for BlazorFluentUI.CoreComponents

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#61352]
### Description

wasm aot compilation failed for BlazorFluentUI.CoreComponents.

```
[BlazorFluentUI.CoreComponents.dll] Exec (with response file contents expanded) in C:\Users\hez20\source\repos\LabCenter\Client\obj\Release\net6.0\linked: MONO_PATH=C:\Users\hez20\source\repos\LabCenter\Client\obj\Release\net6.0\linked;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\;C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\\lib\net6.0 MONO_ENV_OPTIONS= C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.browser-wasm\6.0.0\Sdk\..\tools\mono-aot-cross.exe --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,dwarfdebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\bin\,static,llvmonly,interp,asmonly,llvm-outfile=C:\Users\hez20\source\repos\LabCenter\Client\obj\Release\net6.0\wasm\for-publish\BlazorFluentUI.CoreComponents.dll.bc.tmp" "BlazorFluentUI.CoreComponents.dll"


C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0\Sdk\WasmApp.Native.targets(506,5): error : Precompiling failed for C:\Users\hez20\source\repos\LabCenter\Client\obj\Release\net6.0\linked\BlazorFluentUI.CoreComponents.dll [C:\Users\hez20\source\repos\LabCenter\Client\LabCenter.Client.csproj]
```

### Reproduction Steps

1. Create a blazor wasm project
2. Add nuget reference to `BlazorFluentUI.CoreComponents`
3. Compile it with wasm aot enabled

### Expected behavior

Compile successfully

### Actual behavior

Failed to compile `BlazorFluentUI.CoreComponents.dll`

### Configuration

.NET 6 GA

**Comment by radical** [comment]
Which version of dotnet are you using? Can you try with the latest version?
Also, can you build with `-bl` added to the command line, and attach the generated `msbuild.binlog`?

It might be related to [`1f5ff0f` (#61276)](https://github.com/dotnet/runtime/pull/61276/commits/1f5ff0f8f9a14c9dd2760ab613e3a5da1f26d4c9) . The log will help to confirm that.

**Comment by hez2010** [comment]
> Which version of dotnet are you using?

I'm using .NET 6 GA version.

> Also, can you build with -bl added to the command line

I cannot add it to the `dotnet publish` command line. The wasm doesn't build with AOT with `dotnet build`

You can test it with this [project](https://github.com/hez2010/LabCenter)

**Comment by radical** [comment]
Thanks for the link to your project. I was able to reproduce it. And the log shows `[BlazorFluentUI.CoreComponents.dll] Exit code: -1073741571` returned from `mono-aot-cross.exe`. This was fixed in https://github.com/dotnet/runtime/pull/60265 but didn't make it in the 6.0 GA release.

You can wait for the servicing release, or try the latest 7.0.0-alpha* from https://github.com/dotnet/installer#installers-and-binaries .

**Comment by smjltd** [comment]
same with EPPlus.dll 
`C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0\Sdk\WasmApp.Native.targets(506,5): error : Precompiling failed for C:\Users\smj\source\repos\vcs\obj\Debug\net6.0\linked\EPPlus.dll [C:\Users\smj\source\repos\vcs\vcs.csproj]`
