### ISSUE TITLE
EventCounters unexpectedly stop reporting data when first of two listeners disconnects

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#61353]
### Description

One our internal partner teams at Microsoft reported that if they start an EventListener for EventCounters, then separately start PerfView to listen to counters, then stop the PerfView session the counter information stops flowing to their EventListener. Given that the EventListener never stopped listening they expected the counter events to continue.

### Reproduction Steps

Start EventListener for EventCounters, then start + stop a PerfView ETW based session for the same counter events.

### Expected behavior

Counter events continue to be posted to EventListener

### Actual behavior

Counter events stop being posted

### Regression?

Unknown, but probably not

### Configuration

I think this is .NET Core 6 (preview builds), amd64, but the issue probably occurs regardless of version/architecture

### Other information

The code for CounterGroup appears to stop sending upon receiving a Disable command from any listener, regardless of the presence of other listeners. https://github.com/dotnet/runtime/blob/v5.0.11/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L67

**Comment by dpk83** [comment]
@noahfalk  Is this issue only impacting .NET 6 or earlier versions as well? Is the fix going to be backported to all affected versions?

**Comment by davmason** [comment]
@dpk83 this issue affects all runtimes that have support for dotnet-counters. A fix has not been checked in yet for this issue, when it is we will not backport it unless there is a business justification for it - i.e. a customer is blocked on it.
