### ISSUE TITLE
[API Proposal]: Posix error codes

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#61351]
### Background and motivation

I was working on the FFMPEG integration in my application, and realize that error codes from this library is Posix error codes. Library [which I use](https://github.com/Ruslan-B/FFmpeg.AutoGen) does not define whole spectrum or error codes and only bare minimum. All of that seems reasonable. But that means that I, as app developer, have to define Posix error codes. 

A lot of libraries has strong Linux or even Unix roots, and as such POSIX error codes is quite common. For interoperability I think would be good to have definition of these error codes in .NET, so interop with these libs would be slightly easier. Also Linux/Unix ecosystem of libraries enormous so this should be beneficial in long run.

### API Proposal

I rename error codes to be more in line how .NET name enumerables. That's opionated enough, and naming require refining to be easiely recognizable for Linux crowd. Maybe original name of error code can be placed in summary, for easier discoverability.

```C#
namespace System.Runtime.InteropServices
{
    /// <summary>Specifies a POSIX error code.</summary>
    public enum PosixError
    {
        OperationNotPermitted = 1,
        NoEntry = 2,
        ProcessNotFound = 3,
        Interrupted = 4,
        IoError = 5,
        NotExistingIoDevice = 6,
        TooBig = 7,
        NotExecutable = 8,
        BadFileNumber = 9,
        NoChild = 10,
        TryAgain = 11,
        MemoryNotAvailable = 12,
        PermissionDenies = 13,
        BadAddress = 14,
        DeviceBusy = 16,
        FileExists = 17,
        CrossDeviceLink = 18,
        NoSuchDevice = 19,
        NotDirectory = 20,
        IsDirectory = 21,
        InvalidArgument = 22,
        TooManyOpenFiles = 23,
        NoMoreFileDescriptors = 24,
        NoTty = 25,
        FileTooLarge = 27,
        NoFreeSpace = 28,
        PipeSeek = 29,
        ReadOnlyFileSystem = 30,
        TooManyLinks = 31,
        BrokenPipe = 32,
        InvalidDomain = 33,
        OutOfRange = 34,
        Deadlock = 36,
        NameTooLong = 38,
        NoLocksAvailable = 39,
        FunctionNotSupported = 40,
        DirectoryNotEmpty = 41,
        IllegalSequence = 42,
        StringTruncated = 80,
    }
}
```     

### API Usage

```C#
var retVal = linux_lib.my_funciton();
if (retVal = PosixError.BrokenPipe)
{
    // Do reconnect.
}
```     

### Alternative Designs

Other alterative is to go with naming which POSIX-compatible, but that looks not dotnetish for me, and I include that for completeness of discussion.

```C#
namespace System.Runtime.InteropServices
{
    /// <summary>Specifies a POSIX error code.</summary>
    public enum PosixError
    {
        EPERM = 1,
        ENOENT = 2,
        ESRCH = 3,
        EINTR = 4,
        EIO = 5,
        ENXIO = 6,
        E2BIG = 7,
        ENOEXEC = 8,
        EBADF = 9,
        ECHILD = 10,
        EAGAIN = 11,
        ENOMEM = 12,
        EACCES = 13,
        EFAULT = 14,
        EBUSY = 16,
        EEXIST = 17,
        EXDEV = 18,
        ENODEV = 19,
        ENOTDIR = 20,
        EISDIR = 21,
        EINVAL = 22,
        ENFILE = 23,
        EMFILE = 24,
        ENOTTY = 25,
        EFBIG = 27,
        ENOSPC = 28,
        ESPIPE = 29,
        EROFS = 30,
        EMLINK = 31,
        EPIPE = 32,
        EDOM = 33,
        ERANGE = 34,
        EDEADLK = 36,
        ENAMETOOLONG = 38,
        ENOLCK = 39,
        ENOSYS = 40,
        ENOTEMPTY = 41,
        EILSEQ = 42,
        STRUNCATE = 80,
    }
}
```     

### Risks

- Potentially too obsure to be usable. 
- Potentially new names would be confusing for Linux users.

**Comment by jkotas** [comment]
The error code values are not standardized between different Posix variants. For example, see http://www.ioplex.com/~miallen/errcmpp.html

This was discussed in https://github.com/dotnet/runtime/issues/19958

**Comment by kant2002** [comment]
So basically you are saying, since `Mono.Unix.Native.Errno` [exists](https://github.com/mono/mono.posix/blob/d8994caaf29f0a95022ee4d1d51ae0a55150ce92/src/Mono.Unix/Mono.Unix.Native/Stdlib.cs#L41) there no need for such API.

Then my only concern would be about discoverability of this package. Because of `Mono` prefix I did not even try to look at that location. In retrospect that's reasonable given how long time Mono serve Unixes. Maybe that's on me to not perform due diligence enough.

I'm more then happy if this would be closed then.

**Comment by stephentoub** [comment]
> So basically you are saying, since Mono.Unix.Native.Errno exists there no need for such API.

The bigger concern for such an errno type is that the actual values are not consistent across platforms, e.g. ENAMETOOLONG might be 38 on some systems but 63 on others.  Just exposing an enum like this would likely lead to cross-platform bugs.

**Comment by jkotas** [comment]
>  Just exposing an enum like this would likely lead to cross-platform bugs

Right. Mono.Posix solves this problem by exposing methods to map back and forth between the managed Errno enum and the OS-specific error codes:
- https://github.com/mono/mono.posix/blob/6ea4945862768edd593e69e07a2b58906f7f230b/src/native/map.cc#L980
- https://github.com/mono/mono.posix/blob/6ea4945862768edd593e69e07a2b58906f7f230b/src/native/map.cc#L1876

**Comment by stephentoub** [comment]
> Right. Mono.Posix solves this problem by exposing methods to map back and forth between the managed Errno enum and the OS-specific error codes:

Yup.  Similar to what we do internally in the libraries:
https://github.com/dotnet/runtime/blob/057e34dce1317f99eabe3ef30c19cc55b184dd07/src/libraries/Common/src/Interop/Unix/Interop.Errors.cs#L195-L201
https://github.com/dotnet/runtime/blob/057e34dce1317f99eabe3ef30c19cc55b184dd07/src/libraries/Common/src/Interop/Unix/Interop.Errors.cs#L14-L112

**Comment by kant2002** [comment]
I think optionally can be `static class` with `readonly` fields which setup some fields based on runtime information.
Other, potentially more ugly solution is to keep values in enum, and have shared error codes in single file, and mix separate definitions in separate platform specific files. Like having `PosixError.cs` + `PosixError.Linux.cs` + `PosixError.FreeBSD.cs` + `PosixError.Mac.cs` for example. I suspect there previously some discussion about that when `Interop.Errors.cs` was written.

**Comment by jkotas** [comment]
>  mix separate definitions in separate platform specific files.

That would not work for public API. This sort of separation can be only used for internal implementation details that are not exposed as public APIs.

**Comment by AaronRobinsonMSFT** [comment]
@kant2002 Thanks for bringing this up. Given the history of this idea, #19958, and the concern around inconsistent platform definitions it appears the best approach here is to use `Mono.Unix.Native.Errno` or handle it narrowly in your application. I am going to close this for now, please feel free to let us know if you feel more discussion is warranted.
