### ISSUE TITLE
API diff for .NET 5 vs .NET 6

### ISSUE THREAD

**Issue by ericmutta** [dotnet/runtime#61367]
I am really excited about the release of .NET 6, so let me start by **saying a big thank you** to all the amazing people out there making this stuff possible! :rocket:

While reading through @stephentoub excellent blog post on [.NET 6 performance improvements](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#system-types) I noticed two things:

1. There's a _ton_ of good stuff available in .NET 6.
2. **It's really really easy to _miss_ some of the details** (e.g. like the new `RandomNumberGenerator.GetBytes()` method which is mentioned by @stephentoub about 80% down the blog post).

So my question is, **can we get an API diff that shows in one place, _all_ the changes made between .NET 5 and .NET 6?** I am aware of this [API diff folder](https://github.com/dotnet/core/tree/main/release-notes/6.0/preview/api-diff) but that only shows changes from one preview to the next, and they are in separate files which means a lot of clicking around.

Ideally **there would be some (online) tool where you can pick any two versions of .NET and possibly a list of namespaces that you care about, then get a single output file showing a diff between the two versions.** Or maybe just output the text files so we can download them and use our own diff tools.

All the amazing work going into .NET 5+ is kinda wasted if people can't easily discover it. Right now, the only option I see is reading the announcement blog posts, which can get so long, they crash mobile browsers! Having an online tool that can quickly answer the question **what's new since version X?** would be super handy and go a long way towards ensuring people take full advantage of everything that was worked on :+1:

**Comment by SingleAccretion** [comment]
You can see the API diffs for .NET 5 vs .NET 6 here: https://github.com/dotnet/core/pull/6874, for .NET 5 it has of course already been merged: https://github.com/dotnet/core/tree/main/release-notes/5.0/api-diff.
