### ISSUE TITLE
[wasm] Implement ValueTask marshaling

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#61368]
In #61324 we added tests for marshalling `ValueTask` and `ValueTask<T>` and this a tracking issue to implement the marshaller.

**Comment by lewing** [comment]
This should be a test case for the marshaling improvements.

**Comment by maraf** [comment]
The interop API is being reimplemented and this will not to fit in 7.0.

**Comment by pavelsavara** [comment]
I believe that Task which are proxies for JS `Promise` are not lightweight object and it's not clear to me if they could be.
I think we should delete the disabled tests and close this issue.
