### ISSUE TITLE
Blazor WASM AOT .NET 6 performance degradation on Safari, iPhone 6, iOS 15.1

### ISSUE THREAD

**Issue by thepra** [dotnet/runtime#61373]
### Describe the bug
I'm testing AOT builds of my webapp, and so far the performances are quite better than before, on desktops, Android smartphones but not on iPhones, even though I'm at the latest iOS release. I can't explain what's going on, kind of weird that iPhones with Safari are the only one losing from AOT builds.

In particular the app still works, but quite often is slow and unresponsive, sometimes taking several seconds for simple interactions like changing page or showing a drop down menu.

### To Reproduce
Try [collAnon](https://collanon.app) on an iPhone 6 with iOS 15.1

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022
- Include the output of `dotnet --info`:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

</details>

**Comment by lewing** [comment]
We're tracking several issues here https://github.com/dotnet/runtime/issues/60247

**Comment by thepra** [comment]
I went back to the normal build system so that app link doesn't represent an AOT build no more.

**Comment by lewing** [comment]
@SamMonoRT @radical  we should do some wasm AOT perf runs on Safari

**Comment by ezar** [comment]
Same here!
iOS AOT is slow and unresponsive

**Comment by DierkDroth** [comment]
@lewing @radical @radekdoulik to who it may concern ...

I ran [into this issue](https://github.com/unoplatform/uno/issues/10903) with my real world line-of-business app based on UNO WASM and boiled down the problem by using [UNO gallery ](https://gallery.platform.uno/)as reference.

To be clear: this issue is a show stopper and renders useless any .NET WASM approach like Blazor WASM or UNO WASM on Safari. This is very unfortunate, since both technologies are perfect solutions for the 'build once, run anywhere' demand.

I sincerely hope Microsoft assigns the appropriate priority to this road block.

**Comment by thepra** [comment]
@DierkDroth for what's worth I'm not publishing AOT builds of my webapps, because simply put the performance without AOT are bearable for the final Apple user and without AOT I also get a smaller webapp size to have to download on devices on first load. 
It's been almost 2 years since my issue report and AOT compilation is still not worth it.

**Comment by DierkDroth** [comment]
@thepra thanks for your feedback.

I'm doing the main development on Windows 11 and Chrome and there - for my app - the WASM performance on interpreter is way behind the AOT + interperter build. So, an interpreter build is not an option for my app.

**Comment by lewing** [comment]
We beliveve this has been resolved,

**Comment by DierkDroth** [comment]
@lewing thanks for your feedback.

To clarify: are you saying we will experience significant performance improvements for .NET WASM AOT on Safari/WebKit with .NET 8 (end of this year)?
