### ISSUE TITLE
[mono] class initializaiton overlap check does not support nested structs with explicit layout

### ISSUE THREAD

**Issue by buybackoff** [dotnet/runtime#61385]
Using the new Blazor WASM template for .NET 6, this struct:

```
[StructLayout(LayoutKind.Explicit, Size = 24)]
public struct ComplexStruct
{
    [FieldOffset(0)]
    public object? Object;

    [FieldOffset(0)]
    public InnerStruct Inner;

    [FieldOffset(8)]
    public double Double;

    [FieldOffset(8)]
    public ulong High;

    [FieldOffset(16)]
    public ulong Low;
}

[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct InnerStruct
{
    [FieldOffset(0)]
    public object? Object;

    [FieldOffset(8)]
    public int High;

    [FieldOffset(12)]
    public int Low;
}

```

fails with:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load type 'ComplexStruct' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
System.TypeLoadException: Could not load type 'ComplexStruct' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
   at System.RuntimeTypeHandle.CanCastTo(RuntimeType type, RuntimeType target)
   at System.RuntimeType.IsAssignableFrom(Type c)
   at Microsoft.AspNetCore.Components.RouteTableFactory.<GetRouteableComponents>g__GetRouteableComponents|4_0(List`1 routeableComponents, Assembly assembly)
   at Microsoft.AspNetCore.Components.RouteTableFactory.GetRouteableComponents(RouteKey routeKey)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey)
   at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass62_0.<RunOnNavigateAsync>b__1(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

when updating the counter sample like this:

```
@page "/counter"

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount.Inner.High</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private ComplexStruct currentCount = default;

    private void IncrementCount()
    {
        var x = new ComplexStruct();
        x.Inner.High = currentCount.Inner.High + 1;
        currentCount = x;
    }
}
```

This is a minimal reproduction. It fails instantly during debug.  When I wanted to test a real library with a complex struct like this, and compiled with `<RunAOTCompilation>true</RunAOTCompilation>`, it compiled and loaded but failed with the same message on click (in that case, the struct was first touched only inside another class instantiated in the counter page).

Such a struct works perfectly fine and fast on full and core .NET frameworks. Without the inner struct, the outer struct with explicit layout and union primitive fields works in WASM.

Is this expected behavior? Will it work some day or it's a WASM/Blazor limitation? The latter would be strange given that the docs claim that even native dependencies could be compiled to WASM, and C union structs are quite common.

**Comment by lambdageek** [comment]
Console repro:

```csharp
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Explicit, Size = 24)]
public struct ComplexStruct
{
    [FieldOffset(0)]
    public object? Object;

    [FieldOffset(0)]
    public InnerStruct Inner;

    [FieldOffset(8)]
    public double Double;

    [FieldOffset(8)]
    public ulong High;

    [FieldOffset(16)]
    public ulong Low;
}

[StructLayout(LayoutKind.Explicit, Size = 16)]
public struct InnerStruct
{
    [FieldOffset(0)]
    public object? Object;

    [FieldOffset(8)]
    public int High;

    [FieldOffset(12)]
    public int Low;
}



public class P {
    private ComplexStruct currentCount = default;

    private void IncrementCount()
    {
        var x = new ComplexStruct();
        x.Inner.High = currentCount.Inner.High + 1;
        currentCount = x;
    }
    public static void Main ()
    {
	var p = new P ();
	p.IncrementCount();
	Console.WriteLine ($"currentCount.Inner.High = {p.currentCount.Inner.High}");
    }
}
```

With this project file:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="true">
    <SelfContained>true</SelfContained>
    <UseMonoRuntime>true</UseMonoRuntime>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>

</Project>
```

Note that CoreCLR prints `Unhandled exception. System.TypeLoadException: Could not load type 'ComplexStruct' from assembly 'zed, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.` if you change the type of `InnerStruct.Object` from `object?` to `double`, for example.  So aggregate types need to be checked in detail.

mono's code for the check is here and does not appear to consider the case where a field is a composite struct of value and reference fields
https://github.com/dotnet/runtime/blob/30765864ea6da2055ded19035c9deffea42da8cc/src/mono/mono/metadata/class-init.c#L2156-L2182

It seems like we would need to populate `layout_check [offset]` for each field of `ftype` if it is a valuetype.

**Comment by buybackoff** [comment]
> if you change the type of InnerStruct.Object from object? to double, for example. So aggregate types need to be checked in detail.

No question asked in this case, it's obviously invalid. And I'm in no way asking to make it valid or relax some limitations. Only to do the same thing as .NET does. In the original case the object takes the same 8-byte slot and never overlaps, but the current code does not see that.

I could use `Unsafe.As<Outer,Inner>(ref Unsafe.AsRef(in this))` for Inner getter, but cannot return by ref from a struct for a setter. Plus union structs are fast and convenient.
