### ISSUE TITLE
[API Proposal]: Detecting whether we are in NativeAOT reflection-free mode.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#61387]
### Background and motivation

With the NativeAOT experiment's likely productization in .NET 7, there will be libraries that want to take advantage of [its reflection-free mode](https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/reflection-free-mode.md), by disabling optional features or using alternate less efficient paths.

My specific use case would be in an F# project where F# functions are converted to delegates using `Delegate.CreateDelegate` because straight creation produces inefficient code, but can be used as a fallback for the reflection-free mode.

### API Proposal

```C#
namespace System.Runtime.CompilerServices
{
    public class RuntimeFeature
    {
        public bool IsReflectionRestricted { get; }
    }
}
```

### API Usage

```C#
if (RuntimeFeature.IsReflectionRestricted) {
    Console.WriteLine("Running in reflection-free mode, some features might not be available");
    goto ReflectionFree;
}
// perform tasks that need reflection
ReflectionFree:
// perform tasks that do not need reflection
```     

### Alternative Designs

* I did not choose the name `IsReflectionDisabled` because reflection-free mode allows some very limited form of reflection APIs.
* Making it `IsReflectionSupported` (perhaps combined with a `RequiresReflectionAttribute`) similarly to the other properties of the `RuntimeFeature` class, and forcing any use of reflection to be checked in order for a library to be reflection-free-mode-compiant would force libraries to adapt their code, excessively disrupting them (even more if they multi-target earlier frameworks), especially considering how ubiquitous reflection is in .NET and how niche the reflection-free mode is.
    * How developers would be warned that their reflection-free project is actually using reflection is an open question.
* We could throw something like `NotSupportedException` when a reflection-free app attempts to perform reflection, but I am not sure how much it can be optimized by the NativeAOT compiler. `IsReflectionRestricted` on the other hand can allow unusable code to be easily trimmed away.

### Risks

There is a risk that this is something that is not actually needed and whose utility can be served by existing means.

**Comment by jkotas** [comment]
> there will be libraries that want to take advantage of its reflection-free mode,

The reflection-free mode is an experiment within an experiment. We do not plan to productize it in its current form. It is too incompatible to be useful in practice.
