### ISSUE TITLE
TryGetNonEnumeratedCount should return a count for IReadOnlyCollection<T>

### ISSUE THREAD

**Issue by burkenyo** [dotnet/runtime#61396]
### Description

Users of Enumerable.TryGetNonEnumeratedCount() may expect the API to return true for a collection that only implements `IReadOnlyCollection<T>`. Instead, it returns false.

### Reproduction Steps

create a new .NET 6 console app and run this code:

```
using System.Collections;

Console.WriteLine(Enumerable.TryGetNonEnumeratedCount(new A(), out _));

class A : IReadOnlyCollection<int>
{
    public int Count => 0;

    public IEnumerator<int> GetEnumerator()
    {
        yield break;
    }

    IEnumerator IEnumerable.GetEnumerator() =>
        GetEnumerator();
}
```

### Expected behavior

`True` is written to the console, indicating the collection was able to return a count sans enumeration.

### Actual behavior

`False` is written to the console, indicating the collection was not able to return a count sans enumeration.

### Regression?

No, this is a new API.

### Known Workarounds

Test the collection size manually.

### Other information

If this was a conscious decision, feel free to close this issue.

**Comment by stephentoub** [comment]
This was by-design:
https://github.com/dotnet/runtime/pull/48239#discussion_r575668312

Various issues have tracked revisiting IReadOnlyCollection-special-casing in LINQ all-up.  The current one I believe is:
https://github.com/dotnet/runtime/issues/42254

**Comment by burkenyo** [comment]
Thanks for the quick reply, closing.
