### ISSUE TITLE
CryptoStream.Read bytes truncated 

### ISSUE THREAD

**Issue by Xoben** [dotnet/runtime#61398]
### Description

After upgrading my project from .NET 5 to .NET 6 my unit tests failed because CryptoStream.Read is truncating bytes.
Example:
`int num = cryptoStream.Read(array2, 0, array2.Length);`

To Debug my problem reproduced the source code in 2 different console apps.  One is .NET 5 and other .NET 6 with identical code.  

I am assuming it is related to [Partial and zero-byte reads in DeflateStream, GZipStream, and CryptoStream ](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams)

### Reproduction Steps

```
internal static byte[] DecryptToBytes(string keyString, string value)
        {
            if (keyString.Length > 32)
            {
                keyString = keyString.Substring(0, 32);
            }

            if (keyString.Length < 32)
            {
                keyString = RightPad(keyString, 32, "X");
            }

            byte[] array = Base64Decode(value);
            RijndaelManaged rijndaelManaged = new RijndaelManaged();
            rijndaelManaged.Mode = CipherMode.ECB;
            rijndaelManaged.Padding = PaddingMode.PKCS7;
            rijndaelManaged.Key = new UTF8Encoding().GetBytes(keyString);
            rijndaelManaged.IV = new byte[16];
            ICryptoTransform transform = rijndaelManaged.CreateDecryptor(rijndaelManaged.Key, rijndaelManaged.IV);
            MemoryStream memoryStream = new MemoryStream(array);
            CryptoStream cryptoStream = new CryptoStream(memoryStream, transform, CryptoStreamMode.Read);
            byte[] array2 = new byte[array.Length];
            int num = cryptoStream.Read(array2, 0, array2.Length);
            memoryStream.Close();
            cryptoStream.Close();
            if (num < array2.Length)
            {
                byte[] array3 = new byte[num];
                Array.Copy(array2, array3, num);
                return array3;
            }

            return array2;
        }
    }
```

### Expected behavior

do not truncate bytes

### Actual behavior

truncating bytes

### Regression?

Yes, works in .NET 5

### Configuration

.NET - 6.0.100
Windows 10.0.22000
x64

### Other information

I could provide the complete source code for both console apps

**Comment by danmoseley** [comment]
Hello @Xoben could you please look at this and confirm it solves your problem?
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by danmoseley** [comment]
Oh, excuse me I missed that you already have that link. Did you try the recommended changes there?

**Comment by GrabYourPitchforks** [comment]
Related, new in .NET 6 you can bypass the whole `CryptoStream` complexity entirely. Check out the new [`EncryptCbc`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.encryptcbc?view=net-6.0) and [`DecryptCbc`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.symmetricalgorithm.decryptcbc?view=net-6.0) methods. They'll return the final `byte[]` back to you without you needing to set up a loop, perform manual copying and fixups, or anything else. All you need to set up ahead of time is to create the `SymmetricAlgorithm`-derived instance and set its _Key_ property.

**Comment by Xoben** [comment]
@danmoseley @GrabYourPitchforks Currently trying your suggested solutions, I'll see what works.

**Comment by Xoben** [comment]
Unfortunately I did not write this code and I am unable to fix it with the 2 suggestions by @danmoseley @GrabYourPitchforks but it could be because of my lack of knowledge with security encryption.

**Comment by Detrav** [comment]
It looks like the problem is that the encrypted stream is not fully read, we will fix it in FR crypter in the next update.

**Comment by stephentoub** [comment]
> Unfortunately I did not write this code and I am unable to fix it with the 2 suggestions by @danmoseley @GrabYourPitchforks but it could be because of my lack of knowledge with security encryption.

Basically this line:
```C#
int num = cryptoStream.Read(array2, 0, array2.Length);
```
should be changed to:
```C#
int num = 0;
while (true)
{
    int bytesRead = cryptoStream.Read(array2, num, array2.Length - num);
    if (bytesRead == 0) break;
    num += bytesRead;
}
```

**Comment by Xoben** [comment]
@stephentoub That worked, thanks so much

**Comment by stephentoub** [comment]
Great, thanks for confirming.

**Comment by KeithMason** [comment]
It also worked for me... 
thanks @stephentoub
