### ISSUE TITLE
RuntimeInformation.FrameworkDescription has changed behavior in .NET 6?

### ISSUE THREAD

**Issue by mairaw** [dotnet/runtime#61394]
### Description

I've notice that this API has changed behavior in .NET 6 and I'm not sure if it's by design.

In .NET 6, the value returned is .NET 6.0.0-rtm.21522.10. In .NET 5, the value returned is .NET 5.0.12.

You can see this behavior on the .NET site footer: https://dotnet.microsoft.com/
I can send internally the repro with the .NET 5 behavior.

### Reproduction Steps

This is the code that we have for that:
            new HtmlString(
                footerHtml.Replace(
                    ">Powered by ASP.NET Core",
                    $">Powered by {RuntimeInformation.FrameworkDescription}"));

### Expected behavior

Return a friendlier version description

### Actual behavior

Returns some strings like -rtm, etc. that I don't know where they're coming from. I expected that it would return .NET 6.0.0

**Comment by hoyosjs** [comment]
Thanks for the report @mairaw. This is a known issue: https://github.com/dotnet/runtime/issues/61330 and #45812; the fix was proposed but fell through the cracks. It will make 6.0.1.
