### ISSUE TITLE
DynamicObject: Is it possible to customize null propagation operator behavior for dynamic object?

### ISSUE THREAD

**Issue by anranruye** [dotnet/runtime#61401]
I'm writing a class derived from `DynamicObject` to perform javascript interop in a blazor wasm app. To simulate js logical operators `&&` and `||`, I customized `ExpressionType.IsFalse`/`ExpressionType.IsTrue` unary operation and `ExpressionType.Or`/`ExpressionType.And` binary operation by overriding `TryBinaryOperation` and `TryUnaryOperation` methods, this works fine.

```C#
        dynamic window = GetWindow();
        if (window.a && window.a.prop1)
        {
            Console.WriteLine(1); // hit when window.a and window.a.prop1 are both defined
        }
```

But I can not simplify the above code to 
```C#
        dynamic window = GetWindow();
        if (window.a?.prop1) // just works as "window.a.prop1", and throws exception when "window.a" is null/undefined 
        {
            Console.WriteLine(1);
        }
```
`window.a` returns an instance of the dynamic object class, which holds an underlying value represents the js null/undefined. I guess 
the reason the null propagation operator doesn't work is that the dynamic object instance itself is not null. But I can not make it null, otherwise the following code will no longer work:
```C#
        dynamic window = GetWindow();
        if (window.a) // can not be converted to a bool-like value if it is null
        {
            Console.WriteLine(1);
        }
```

keywords: DynamicObject , dynamic , dynamic programming , dynamic object , DLR, js , javascript , blazor , wasm

**Comment by pavelsavara** [comment]
We don't support `DynamicObject` interop with JavaScript in the runtime and I think Blazor doesn't either. 
Feel free to clarify and reopen, thanks.
