### ISSUE TITLE
[.NET 6] [Production Bug] System.Text.Json.JsonSerializer.Serialize(Tuple.Create()) inconsistency between (debug/release) & published 

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#61406]
This line of code produces different output when run under visual studio 2022 blazor webassembly Release (debug is same) and between published version.
To Reproduce :
In visual studio 2022 Current, Create your blazor wasm .NET 6.0 project without asp.net core hosting or pwa.
put this code somewhere :
```
        public class ClassA
        {
            public string Name { get; set; }
        }
        public class ClassB
        {
            public string Name { get; set; }
        }
        public class ClassC
        {
            public string Name { get; set; }
        }
        public static void Test1()
        {
            ClassA a = new ClassA { Name = "a" };
            ClassB b = new ClassB { Name = "b" };
            ClassC c = new ClassC { Name = "c" };
            Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(Tuple.Create(a, b, c)));
        }
```
Call Test1()

Locally I saw it working fine, after publishing it to Azure app service with AOT it doesn't work anymore

![image](https://user-images.githubusercontent.com/35312807/141006353-8311f4fe-e2ce-4a2b-ad75-fc7b1120e0c6.png)

**Comment by eiriktsarpalis** [comment]
cc @eerhardt

**Comment by Xyncgas** [comment]
Can I have some advice, what should I do about enabling trimming (to be or not to be) if I am using reflections in my libraries.

**Comment by eerhardt** [comment]
I'm investigating the trimming issue now. I'll report back when I have more info.

> Can I have some advice, what should I do about enabling trimming (to be or not to be) if I am using reflections in my libraries.

If you want to make your libraries trim-friendly, check out the docs around here: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming.

**Comment by eerhardt** [comment]
After looking into this, the issue is that you are trying to Json serialize a BCL type (`Tuple<,,>`) which is in an assembly (`System.Private.CoreLib`) that is being trimmed. The same issue happens with Queue and Stack (https://github.com/dotnet/runtime/issues/53205).

`JsonSerializer.Serialize(object)` is marked with

```C#
[RequiresUnreferencedCode("JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.")]
```

In a non-Blazor application that has `PublishTrimmed=true`, you will get a warning when you call methods marked with `RequiresUnreferencedCode`. But in Blazor, those warnings are disabled, so you don't get build/publish time notification that you might have a problem.

To workaround this, you can try the following (in my recommended order):

1. Use the [Source Generator](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation) to serialize/deserialize objects with Json. This is the best approach in a trimmed application, like Blazor WASM.
2. Don't use `Tuple`, but instead create a new class with 3 properties.
3. Add a `DynamicDependency` attribute like the following, which tells the trimmer to preserve all properties on `Tuple<,,>`

```C#
    [DynamicDependency(DynamicallyAccessedMemberTypes.PublicProperties, typeof(Tuple<,,>))]
    public static void Test1()
    {
        ClassA a = new ClassA { Name = "a" };
        ClassB b = new ClassB { Name = "b" };
        ClassC c = new ClassC { Name = "c" };
        Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(Tuple.Create(a, b, c)));
    }
```

**Comment by Xyncgas** [comment]
Thanks a lot

**Comment by Xyncgas** [comment]
> After looking into this, the issue is that you are trying to Json serialize a BCL type (`Tuple<,,>`) which is in an assembly (`System.Private.CoreLib`) that is being trimmed. The same issue happens with Queue and Stack (#53205).
> 
> `JsonSerializer.Serialize(object)` is marked with
> 
> ```cs
> [RequiresUnreferencedCode("JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.")]
> ```
> 
> In a non-Blazor application that has `PublishTrimmed=true`, you will get a warning when you call methods marked with `RequiresUnreferencedCode`. But in Blazor, those warnings are disabled, so you don't get build/publish time notification that you might have a problem.
> 
> To workaround this, you can try the following (in my recommended order):
> 
> 1. Use the [Source Generator](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation) to serialize/deserialize objects with Json. This is the best approach in a trimmed application, like Blazor WASM.
> 2. Don't use `Tuple`, but instead create a new class with 3 properties.
> 3. Add a `DynamicDependency` attribute like the following, which tells the trimmer to preserve all properties on `Tuple<,,>`
> 
> ```cs
>     [DynamicDependency(DynamicallyAccessedMemberTypes.PublicProperties, typeof(Tuple<,,>))]
>     public static void Test1()
>     {
>         ClassA a = new ClassA { Name = "a" };
>         ClassB b = new ClassB { Name = "b" };
>         ClassC c = new ClassC { Name = "c" };
>         Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(Tuple.Create(a, b, c)));
>     }
> ```

does your recommandation number 3 : ```Add a DynamicDependency attribute like the following, which tells the trimmer to preserve all properties on Tuple<,,>``` works if I don't control the library's source

**Comment by eerhardt** [comment]
> does your recommandation number 3 : Add a DynamicDependency attribute like the following, which tells the trimmer to preserve all properties on Tuple<,,> works if I don't control the library's source
> for example can I just add it where I called that line of library code in the project?

Yes, that will work. See https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/#specifying-dependencies for some information on this attribute.
