### ISSUE TITLE
Implement proper UInt64 and Int64 marshaling in the WASM bindings

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#61404]
Right now the WASM bindings inherit Emscripten's questionable approach to 64-bit integers, where it tries to fit them into a JS Number (64-bit float) and kind of waves its hands if they don't fit correctly. At this point most browsers have native BigInt support so we could be using that to do the heap reads/writes of 64-bit values and then allow bindings callers to pass us large integers safely. We could also produce them as return values from bindings calls, but at present a call through the bindings that returns Int64 will produce a Number, so that'd be a compat break we need to consider.

- [ ] Allow passing bigint arguments to bound C# methods that accept Int64 or UInt64
- [ ] Properly range-check bigint arguments to detect overflows
- [ ] Opt-in support for returning managed uint64/int64 results to JS as bigint
- [ ] Handle being passed a bigint for smaller types and automatically convert it to number

**Comment by pavelsavara** [comment]
@kg I think we implemented all of this with `[JSImport]` and `getHeapI64Big` or `getHeapI52`. 
Is there something else missing ?

**Comment by kg** [comment]
I think we're good on this and can open issues if any corner cases come up, I didn't notice any issues.
