### ISSUE TITLE
FileInfo reports wrong attributes on OSX

### ISSUE THREAD

**Issue by zvrba** [dotnet/runtime#61409]
### Description

On OSX 11.6.1, `FileInfo` incorrectly sets `FileAttributes.Directory` on non-existing paths.  Test program:

```
using System;
using System.IO;

namespace directoryAttributeTest
{
    class Program
    {
        static void Main(string[] args) {
            if(args.Length != 1) {
                Console.WriteLine("Missing path argument");
                return;
            }
            var path = args[0];
            var fi = new FileInfo(path);
            Console.WriteLine("Directory name: " + fi.DirectoryName);
            if (fi.Attributes.HasFlag(FileAttributes.Directory))
                Console.WriteLine("Has directory attribute");
            else
                Console.WriteLine("Does not have directory attribute");
        }
    }
}
```

### Reproduction Steps

Run the attached program and pass it absolute path to 1) an existing file, 2) an existing directory, 3) /dir1/dir2/existingfile/non-existing-name

```
mkdir /tmp/a
touch /tmp/a/b.txt
```

Now run the program three times giving it each time one of /tmp/a/b.txt , /tmp/a and /tmp/a/b.txt/z as the argument.

In cases 1) and 2) the output is as expected. In case 3), the program incorrectly reports that the file HAS directory attribute set. 

### Expected behavior

The program should not report FileAttribute.Directory for non-existing path /tmp/a/b.txt/z

### Actual behavior

The program DOES report FileAttribute.Directory for /tmp/a/b.txt/z

### Configuration

.NET Core 3.1
OSX 11.6.1 (BigSur, Intel x64)

The issue does not appear on Windows, but unsure whether it appears on other OSX versions.

**Comment by am11** [comment]
The default value of Attributes is -1, which means _all_ flags are on. AFAICT, this is an old, .NET Framework, behavior and not specific to macOS or `FileAttributes.Directory`.

The consumer is expected to check if file exists when using `FileInfo` or `DirectoryInfo`:
```diff
- if (fi.Attributes.HasFlag(FileAttributes.Directory))
+ if (fi.Exists && fi.Attributes.HasFlag(FileAttributes.Directory))
```
Also note that using `File.GetAttributes(path)` instead of `fi.Attributes` in that condition throws `DirectoryNotFoundException`.

> The issue does not appear on Windows

What value do you get from `new FileInfo(@"C:\non\existent\path").Attributes` on Windows?

**Comment by zvrba** [comment]
The following test case
```
            var fi = new FileInfo(@"C:\TEMP\NOT\EXISTS");
            Console.WriteLine(fi.Attributes);

            fi = new FileInfo(@"C:\TEMP\SubjectKey.xml");   // EXISTS, IS A FILE
            Console.WriteLine(fi.Attributes);

            fi = new FileInfo(@"C:\TEMP\SubjectKey.xml\.VOLUMEID.XML");   // DOES NOT EXIST
            Console.WriteLine(fi.Attributes);
```
prints out -1, Archive, -1 on Windows.

The actual situation that occurred on OSX was the following
```
var fi = new FileInfo(path);  // Unknown whether path points to a file or dir
if (!fi.Attributes.HasFlag(FileAttributes.Directory))
    path = fi.DirectoryName;
path = Path.Combine(path, ".VOLUMEID.TXT");
var content = File.ReadAllLines(path);
```
In case similar to the 3rd case above, it threw `DirectoryNotFoundException`, implying that file attributes were wrong. The path in question did exist and was accessible. I'll try to make a repro on OSX.

**Comment by Jozkee** [comment]
> The issue does not appear on Windows

@zvrba are you sure your reported scenario is different in Windows?

> The default value of Attributes is -1, which means all flags are on.

@am11 is right, you must check property `Exists` before `fi.Attributes.HasFlag(FileAttributes.Directory)`. 

This is not the first time I see someone being affected by this behavior https://github.com/dotnet/runtime/issues/59406#issuecomment-929677425, @danmoseley @jeffhandley should we consider adding an analyzer for it?

**Comment by Jozkee** [comment]
I will close this issue since we won't change that Attributes == -1 on non-existing files or directories.

**Comment by zvrba** [comment]
Ok, close the issue, but can you at least suggest a way to check whether a path is 1) regular file, 2) directory, 3) special file (unix has pipes, sockets, devices, etc.) that works reliably across platforms?
