### ISSUE TITLE
Proxy-Support header case sensitive causes proxied API failure when using HttpClient

### ISSUE THREAD

**Issue by ChrisFWood** [dotnet/runtime#61414]
I've been looking into an issue where access to a API work via PowerShell but doesn't via HttpClient.

The diagnostic output logs "Proxy doesn't support connection-based auth" and looking it to that appear to be proxy requires the header "Proxy-Support" with the value "Session-Based-Authentication".
https://github.com/dotnet/runtime/blob/e64cce6fbbde72d1ea61010bd08f11ba7b51afc9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L64

However the API in question has the "Proxy-Support" with the value "Session-based-authentication" a simple case change.  While I can accept the specification for the proxy support header may specify the value with an exact case, following this means dotnet apps will not work with some API, and other implementations do not enforce the casing.

Suggested fix would be to make the check case insensitive.

**Comment by geoffkizer** [comment]
RFC here: https://datatracker.ietf.org/doc/html/rfc4559

As you can see, it's rather brief and doesn't actually say whether the value is case sensitive or not.

Since there are servers out there that seem to assume it's case-insenstive, we should probably do the same.

**Comment by ChrisFWood** [comment]
I don't appear to be able to assign myself to this but I don't mind creating a pull request for this.

**Comment by karelz** [comment]
Fixed in 7.0 in PR #61446 and in 6.0.14 in PR #79620.
