### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by ssarin3194** [dotnet/runtime#61445]
### Description

I have a .net framework app using 4.7.2 - It is a web application using MVC.

I do see this in the stack trace when I try to access the GET request in the controller of the web application.

[FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   OpenTelemetry.Sdk..cctor() +0

Now, I am using 

 <PackageReference Update="System.Diagnostics.DiagnosticSource" version="6.0.0-rc.2.21480.5"  />
but it is expecting 5.0.1. Isn't it backward compatible?

Also, if I change this version to 5.0.1 --I see other package referencing failing in this case.

**"C:\ASM-AlertingMicroService\src\ASMFeedback\ASMFeedback.csproj" (Restore target) (1) ->
(Restore target) ->
 Feedback.csproj : error NU1605: Detected package downgrade: System.Diagnostics.DiagnosticSource from 6.0.0-rc.2.21480
.5 to 5.0.1. Reference the package directly from the project to select a different version.
Feedback.csproj : error NU1605:  Microsoft.Asm.ASMFeedback -> Microsoft.Extensions.Logging 6.0.0-rc.2.21480.5 -> System
.Diagnostics.DiagnosticSource (>= 6.0.0-rc.2.21480.5)
Feedback.csproj : error NU1605:  Microsoft.Asm.ASMFeedback -> System.Diagnostics.DiagnosticSource (>= 5.0.1)**

Does this mean that the extensions.logging is dependant on this version *6.0.0..*) which is why I am unable to restore the package?

### Reproduction Steps

<ItemGroup>

    <PackageReference Include="Microsoft.Azure.Kusto.Cloud.Platform" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <Reference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Primitives" />
    <PackageReference Include="Microsoft.Identity.Client" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" />

    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Api" />
    <PackageReference Include="OpenTelemetry.Exporter.Geneva" />

    <Reference Include="System" />
    <PackageReference Include="System.Buffers" />
    <PackageReference Include="System.Collections.Immutable" />
    <Reference Include="System.Data" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" />

    <Reference Include="System.Drawing" />
    <Reference Include="System.IdentityModel" />
    <Reference Include="System.IO.Compression" />

    <PackageReference Include="System.Memory" />
    <Reference Include="System.Numerics" />    
    <PackageReference Include="System.Numerics.Vectors" />
    <Reference Include="System.Runtime.Caching" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    
    <Reference Include="System.Security" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.ServiceModel.Web" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
    <PackageReference Include="System.ValueTuple" />

    <Reference Include="System.Web.DynamicData" />
    <Reference Include="System.Web.Entity" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Web.Abstractions" />
    <Reference Include="System.Web.Routing" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.EnterpriseServices" />

    <PackageReference Include="Microsoft.Web.Infrastructure" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Net.Http.WebRequest" />

    <Reference Include="System.Web.Helpers" />
    <Reference Include="System.Web.Mvc" />
    <Reference Include="System.Web.Optimization" />
    <Reference Include="System.Web.Razor" />
    <Reference Include="System.Web.WebPages" />    
    <Reference Include="System.Web.WebPages.Deployment" />
    <Reference Include="System.Web.WebPages.Razor" />     

    <PackageReference Include="WebGrease" />
    <PackageReference Include="Antlr3.Runtime" />  

    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" />       
    
    <PackageReference Include="bootstrap" />
    <PackageReference Include="jQuery" />
    <PackageReference Include="jQuery.Validation" />
    <PackageReference Include="Microsoft.AspNet.Mvc" />
    <PackageReference Include="Microsoft.AspNet.Razor" />
    <PackageReference Include="Microsoft.AspNet.Web.Optimization" />
    <PackageReference Include="Microsoft.AspNet.WebPages" />    
    <PackageReference Include="Modernizr" />        
    <PackageReference Include="System.Reflection.Emit.Lightweight" />  
    <PackageReference Include="MSBuild.Microsoft.VisualStudio.Web.targets" /> 
    
    
     
   </ItemGroup>

and my file where I specify these versions is 

<PackageReference Update="Bond.Core.CSharp" Version="8.2.0" />
    <PackageReference Update="Bond.Runtime.CSharp" Version="8.2.0" />
    <PackageReference Update="Microsoft.Rest.ClientRuntime" Version="2.3.21" />
    <PackageReference Update="Microsoft.Rest.ClientRuntime.Azure" Version="3.3.19" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Update="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Update="WindowsAzure.Storage" Version="9.3.3" />
    <PackageReference Update="Microsoft.ServiceFabric.Data.Interfaces" Version="4.0.470" />
    <PackageReference Update="Microsoft.ServiceFabric" Version="7.0.470" />
    <PackageReference Update="CsvHelper" Version="15.0.0" />
    <PackageReference Update="Microsoft.WindowsAzure.SDK" Version="2.9.0" />    
    <PackageReference Update="Microsoft.ServiceFabric.Data" Version="4.0.470" />
    <PackageReference Update="Microsoft.ServiceFabric.Data.Extensions" Version="4.0.470" />    
    <PackageReference Update="Microsoft.ServiceFabric.Diagnostics.Internal" Version="4.0.470.0" />
    <PackageReference Update="Microsoft.ServiceFabric.FabricTransport.Internal" Version="4.0.470.0" />
    <PackageReference Update="Microsoft.ServiceFabric.Services" Version="4.0.470" />
    <PackageReference Update="Microsoft.ServiceFabric.Services.Remoting" Version="4.0.470" />
    <PackageReference Update="Microsoft.Azure.EventHubs.ServiceFabricProcessor" Version="0.5.4" />
    <PackageReference Update="WindowsAzure.ServiceBus" Version="6.0.1" />
    <PackageReference Update="Microsoft.Cloud.InstrumentationFramework" Version="3.2.2.1" />
    <PackageReference Update="Polly" Version="6.1.2" />
    <PackageReference Update="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.6" />
    <PackageReference Update="System.Net.Http" Version="4.3.4" />
    <PackageReference Update="PowerShellStandard.Library" Version="5.1.0" />
    <PackageReference Update="Microsoft.Azure.KeyVault" Version="3.0.5" />
    <PackageReference Update="Microsoft.Azure.KeyVault.Core" Version="3.0.5" />
    <PackageReference Update="Microsoft.Azure.Services.AppAuthentication" Version="1.4.0" />
    <PackageReference Update="Microsoft.AzureAd.Icm.Types.amd64" Version="2.1.10.50" />
    <PackageReference Update="Microsoft.AzureAd.Icm.WebService.Client.amd64" Version="2.1.10.50" />
    <PackageReference Update="Microsoft.AzureAd.Icm.XhtmlUtility.amd64" Version="2.1.10.50" />
    <PackageReference Update="Microsoft.Azure.Security.Detection.AlertContracts" Version="1.7.0.5" />
    <PackageReference Update="Microsoft.Net.Http" Version="2.2.29" />
    <PackageReference Update="Microsoft.Azure.Kusto.Ingest" Version="8.0.8" />
    <PackageReference Update="Microsoft.Azure.Kusto.Data" Version="8.0.8" />
    <PackageReference Update="Microsoft.Azure.Kusto.Cloud.Platform" Version="8.0.8" />
    <PackageReference Update="Microsoft.Cloud.InstrumentationFramework" Version="3.2.2.1" />
    <PackageReference Update="Microsoft.Data.OData" Version="5.8.4" />
    <PackageReference Update="DsmsCredentialsManagement" Version="3.14.1504" />
    <PackageReference Update="RestSharp" Version="106.12.0" />
    <PackageReference Update="Scuba.Cdi.Client" Version="1.0.1453.3" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Update="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Update="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Update="Azure.SDK.ServiceRuntime" Version="2.9" />
    <PackageReference Update="Microsoft.Bcl.Build" Version="1.0.21" />
    <PackageReference Update="YamlDotNet" Version="9.1.4" />
    <PackageReference Update="Antlr" version="3.5.0.2" />
    <PackageReference Update="bootstrap" version="3.4.1" />
    <PackageReference Update="jQuery" version="3.4.1" />
    <PackageReference Update="jQuery.Validation" version="1.17.0" />
    <PackageReference Update="Microsoft.AspNet.Mvc" version="5.2.7" />
    <PackageReference Update="Microsoft.AspNet.Razor" version="3.2.7" />
    <PackageReference Update="Microsoft.AspNet.Web.Optimization" version="1.1.3" />
    <PackageReference Update="Microsoft.AspNet.WebPages" version="3.2.7"  />
    <PackageReference Update="Microsoft.Azure.Kusto.Cloud.Platform" version="9.4.1"  />
    <PackageReference Update="Microsoft.Azure.Kusto.Data" version="9.4.1"  />
    <PackageReference Update="Microsoft.Bcl.AsyncInterfaces" version="6.0.0-rc.2.21480.5"  />    
    <PackageReference Update="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" Version="2.0.1" />
    <PackageReference Update="Microsoft.Extensions.Configuration" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Configuration.Abstractions" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Configuration.Binder" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection.Abstractions" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Logging" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Logging.Configuration" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Options" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Options.ConfigurationExtensions" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Extensions.Primitives" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="Microsoft.Identity.Client" version="4.37.0"  />
    <PackageReference Update="Microsoft.Identity.Client.Extensions.Msal" version="2.19.2"  />
    <PackageReference Update="Microsoft.IO.RecyclableMemoryStream" version="2.2.0"  />
    <PackageReference Update="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.11"  />
    <PackageReference Update="Microsoft.Web.Infrastructure" version="1.0.0.0"  />
    <PackageReference Update="Modernizr" version="2.8.3"  />
    <PackageReference Update="Newtonsoft.Json" version="12.0.3"  />
    <PackageReference Update="OpenTelemetry" version="1.1.0"  />
    <PackageReference Update="OpenTelemetry.Api" version="1.1.0"  />
    <PackageReference Update="OpenTelemetry.Exporter.Geneva" version="1.1.0"  />
    <PackageReference Update="System.Buffers" version="4.5.1"  />
    <PackageReference Update="System.Collections.Immutable" version="5.0.0"  />
    <PackageReference Update="System.Diagnostics.DiagnosticSource" version="5.0.1"  />
    <PackageReference Update="System.Memory" version="4.5.4"  />
    <PackageReference Update="System.Numerics.Vectors" version="4.5.0"  />
    <PackageReference Update="System.Reflection.Emit.Lightweight" version="4.7.0"  />
    <PackageReference Update="System.Runtime.CompilerServices.Unsafe" version="6.0.0-rc.2.21480.5"  />
    <PackageReference Update="System.Threading.Tasks.Extensions" version="4.6.0-preview.18571.3"  />
    <PackageReference Update="System.ValueTuple" version="4.5.0"  />
    <PackageReference Update="WebGrease" version="1.6.0"  />
    <PackageReference Update="MSBuild.Microsoft.VisualStudio.Web.targets" version="14.0.0.3" />
    <PackageReference Update="Antlr3.Runtime" version="3.5.1"/>        
    

### Expected behavior

Shouldn't be seeing this error irrespective of the version, especially since I am using a higher version) 

### Actual behavior

Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

[FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=5.0.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)]
   OpenTelemetry.Sdk..cctor() +0

[TypeInitializationException: The type initializer for 'OpenTelemetry.Sdk' threw an exception.]
   OpenTelemetry.Sdk.get_SuppressInstrumentation() +0
   OpenTelemetry.Logs.OpenTelemetryLoggerProvider..cctor() +15
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) +407
   Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument) +274

### Regression?

Yes, it worked in a .net framework build from the .csproj file that VS created. I now edited the .csproj file a bit to fit into my repo and use the common build settings as mentioned above and I am running to this error where the assembly is not getting loaded anymore.

### Configuration

dotnet --version
5.0.403
running on x64, using .net 4.7.2. This is run on Windows.

**Comment by tarekgh** [comment]
@ssarin3194 thanks for your report. If you can provide a sample project demonstrating the issue, that would be helpful to investigate. Meanwhile, could you try to change the package reference in your project to reference version 6.0 of System.Diagnostics.DiagnosticSource? 

```Xml
	<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />
```

And in `web.config` file, please add the following binding redirect. 

```Xml 
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">

			<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0"/>
			</dependentAssembly>
    ...

    </assemblyBinding>
  </runtime>

```

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by ssarin3194** [comment]
Hi,
I do have the web.config already with this change..

Also, when I update the package version to 6.0.0.0 i see the following error

"Feedback.csproj" (Restore target) (1) ->
(Restore target) ->
  Feedback.csproj : error NU1605: Detected package downgrade: System.Runtime.CompilerServices.Unsafe from 6.0.0 to 6.0.0
-rc.2.21480.5. Reference the package directly from the project to select a different version.
Feedback.csproj : error NU1605:  Microsoft.Asm.ASMFeedback -> System.Diagnostics.DiagnosticSource 6.0.0 -> System.Runtim
e.CompilerServices.Unsafe (>= 6.0.0)
Feedback.csproj : error NU1605:  Microsoft.Asm.ASMFeedback -> System.Runtime.CompilerServices.Unsafe (>= 6.0.0-rc.2.2148
0.5)

Does this mean that I need to downgrade System.Runtime.CompilerServices.Unsafe also to 6.0.0?

**Comment by ssarin3194** [comment]
The issue was that the dll version 5.0.0.1 was not getting loaded since we hadn't mentioned the binding in web.config. This had to be updated as -- 

<dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly> 

Another solution was to ---

 <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> needs to be set in the .csproj file  which automatically takes care of redirects.
