### ISSUE TITLE
Buffer allocated on LOH by XmlTextReader when using Async mode

### ISSUE THREAD

**Issue by chrisdcmoore** [dotnet/runtime#61459]
### Description

Desired labels: `area-System.Xml`

The choice of `XmlReader.AsyncBufferSize` and how it is used results in the allocation of a `char[]` on the Large Object Heap by `XmlTextReaderImpl.InitTextReaderInputAsync(...)` when the reader's settings have `Async = true`.

I'm not sure if this is intentional, or an oversight? Presumably reducing this buffer size would have a positive impact on users of this code who typically operate on "small, simple" XML, but regress performance for those who operate on "big, complicated" XML which contain structures that require the buffers to be resized?

Minimal repro - running this with the VS performance profile shows the allocation of a `System.Char[65537]` which is `131,098` bytes and therefore presumably ends up on the LOH:

```c#
    public class Program
    {
        public static async Task Main(string[] args)
        {
            using var xmlReader = XmlReader.Create(new StringReader(@"<?xml version = ""1.0"" encoding = ""utf-8""?><myRoot><selfClosing /></myRoot>"), new XmlReaderSettings { Async = true });
            while (await xmlReader.ReadAsync())
            {
                Console.WriteLine(xmlReader.Name);
            }
        }
    }
```

### Configuration

.NET 5, Windows 10, 64-bit

### Regression?

I don't think so.

### Data

Screenshot of the performance profiling of the minimal code repro above (it doesn't contain any important text that I haven't already included elsewhere in this issue):

![xmlreader-async-loh](https://user-images.githubusercontent.com/5628773/141288685-b41e4e52-6e3e-4f3f-8a93-1cb1bf89f3a1.png)

### Analysis

The constant is defined at the following location

https://github.com/dotnet/runtime/blob/a761b9fcb2c0c44c4ca4daccec797658c18f2c7e/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlReader.cs#L84

There is a comment suggesting it is "64KB" but whilst that will be roughly true for using this to size the `byte[]` buffer, using the same number (plus 1) to size the `char[]` buffer will result in it being larger than the 85K threshold for being allocated on the LOH, since `sizeof(char) = 2 * sizeof(byte) = 2 bytes`.

https://github.com/dotnet/runtime/blob/a761b9fcb2c0c44c4ca4daccec797658c18f2c7e/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImplAsync.cs#L942-L973

In the `Async = false` case, it looks like the code decides on two different (smaller) buffer sizes depending on the length of the stream (if available):

https://github.com/dotnet/runtime/blob/a761b9fcb2c0c44c4ca4daccec797658c18f2c7e/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlReader.cs#L1779-L1798

**Comment by krwq** [comment]
Can you do some measurements on both Windows and Linux for this suggested change? It would be good to do some end to end benchmark testing on: many small XML documents and some number of large XML documents and see how/if results differ. If your speculations are correct we should see some improvement and we can go ahead and take that change.

**Comment by chrisdcmoore** [comment]
I've given writing a benchmark a stab but have very little experience writing them so I'm unsure of my methodology here. The idea behind it is writing XML documents of varying lengths (but all with the same simple structure) to a memory stream, then attempting to measure the performance of reading those back.

<details>
<summary>Benchmark code</summary>

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using BenchmarkDotNet.Attributes;

namespace MicroBenchmarks.libraries.System.Private.Xml
{
    [BenchmarkCategory(Categories.Libraries)]
    public class XmlReaderBuffers
    {
        MemoryStream _ms;

        [Params(1, 10, 100, 1000, 10000, 50000, 100000)]
        public int NumberOfInnerElements;

        [GlobalSetup]
        public void Setup()
        {
            _ms = new MemoryStream();
            using var writer = XmlWriter.Create(_ms);
            writer.WriteStartElement("root");
            for (var i = 0; i < NumberOfInnerElements; i++)
            {
                writer.WriteStartElement($"elem{i % 10}");
                writer.WriteEndElement();
            }
            writer.WriteEndElement();
            writer.Flush();
        }

        [Benchmark]
        [BenchmarkCategory(Categories.NoWASM)]
        public async Task XmlReader_ReadAsync()
        {
            _ms.Position = 0;
            var reader = XmlReader.Create(_ms, new XmlReaderSettings { Async = true });
            while (await reader.ReadAsync());
        }

    }
}
```

</details>

The "main" CoreRun is from a build of the main branch, and the "xmlreader-smaller-buffer" CoreRun is with the `AsyncBufferSize` changed to half its current value.

I only have results on Linux so far and they look like this:

<details>
<summary>Linux benchmark results</summary>

// * Summary *

BenchmarkDotNet=v0.13.1.1620-nightly, OS=ubuntu 18.04
Intel Xeon Platinum 8175M CPU 2.50GHz, 1 CPU, 8 logical and 4 physical cores
  [Host]     : .NET 7.0.0 (7.0.21.56701), X64 RyuJIT
  Job-CCAORA : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT
  Job-BAZTUK : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT
                                                                                                                                                                                                                                                                                                                                                                            PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog  IterationTime=250.0000 ms
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1

|              Method |        Job |                                                                                                  Toolchain | NumberOfInnerElements |          Mean |      Error |     StdDev |        Median |           Min |           Max | Ratio |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|-------------------- |----------- |----------------------------------------------------------------------------------------------------------- |---------------------- |--------------:|-----------:|-----------:|--------------:|--------------:|--------------:|------:|--------:|--------:|--------:|----------:|
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                     1 |     23.140 us |  0.2548 us |  0.2384 us |     23.200 us |     22.740 us |     23.530 us |  1.00 | 41.5757 | 41.5757 | 41.5757 |    195 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                     1 |      8.684 us |  0.1701 us |  0.1747 us |      8.613 us |      8.482 us |      9.055 us |  0.38 |  5.8646 |  0.9831 |       - |     99 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                    10 |     25.409 us |  0.3077 us |  0.2878 us |     25.289 us |     25.128 us |     26.009 us |  1.00 | 41.6208 | 41.6208 | 41.6208 |    196 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                    10 |     10.617 us |  0.1449 us |  0.1355 us |     10.584 us |     10.456 us |     10.951 us |  0.42 |  5.8946 |  1.4632 |       - |    100 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                   100 |     36.818 us |  0.1076 us |  0.0954 us |     36.821 us |     36.642 us |     36.985 us |  1.00 | 41.6058 | 41.6058 | 41.6058 |    196 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                   100 |     23.177 us |  0.4443 us |  0.4562 us |     23.127 us |     22.657 us |     24.157 us |  0.63 |  5.8637 |  1.3961 |       - |    100 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                  1000 |    149.487 us |  0.6615 us |  0.5864 us |    149.430 us |    148.732 us |    150.868 us |  1.00 | 41.6419 | 41.6419 | 41.6419 |    196 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                  1000 |    132.682 us |  1.0759 us |  1.0064 us |    132.217 us |    131.675 us |    134.732 us |  0.89 |  5.8355 |  1.5915 |       - |    100 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                 10000 |  1,262.226 us |  4.4833 us |  3.9743 us |  1,261.333 us |  1,255.922 us |  1,270.038 us |  1.00 | 40.4040 | 40.4040 | 40.4040 |    196 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                 10000 |  1,211.333 us |  1.3320 us |  1.1122 us |  1,211.361 us |  1,209.831 us |  1,213.744 us |  0.96 |  4.8780 |       - |       - |    100 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                 50000 |  5,885.481 us | 23.6029 us | 20.9233 us |  5,880.588 us |  5,862.258 us |  5,935.497 us |  1.00 | 23.2558 | 23.2558 | 23.2558 |    198 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                 50000 |  5,896.922 us |  9.8951 us |  7.7254 us |  5,893.749 us |  5,889.540 us |  5,913.200 us |  1.00 |       - |       - |       - |    104 KB |
|                     |            |                                                                                                            |                       |               |            |            |               |               |               |       |         |         |         |           |
| XmlReader_ReadAsync | Job-CCAORA |                     /main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                100000 | 11,789.123 us | 23.7850 us | 19.8616 us | 11,788.944 us | 11,749.843 us | 11,809.839 us |  1.00 |       - |       - |       - |    200 KB |
| XmlReader_ReadAsync | Job-BAZTUK | /xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun |                100000 | 12,341.551 us | 25.1576 us | 19.6414 us | 12,348.568 us | 12,302.961 us | 12,363.512 us |  1.05 |       - |       - |       - |    107 KB |

// * Hints *
Outliers
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 1 outlier  was  removed (9.61 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (37.12 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (151.58 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (1.27 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 2 outliers were removed (1.23 ms, 1.23 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (5.98 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 3 outliers were removed (5.95 ms..5.99 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/main/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 2 outliers were removed (11.87 ms, 11.92 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=/xmlreader-smaller-buffer/bin/testhost/net7.0-Linux-Release-x64/shared/Microsoft.NETCore.App/7.0.0/corerun, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 3 outliers were removed, 4 outliers were detected (12.30 ms, 12.41 ms..12.44 ms)

// * Legends *
  NumberOfInnerElements : Value of the 'NumberOfInnerElements' parameter
  Mean                  : Arithmetic mean of all measurements
  Error                 : Half of 99.9% confidence interval
  StdDev                : Standard deviation of all measurements
  Median                : Value separating the higher half of all measurements (50th percentile)
  Min                   : Minimum
  Max                   : Maximum
  Ratio                 : Mean of the ratio distribution ([Current]/[Baseline])
  Gen 0                 : GC Generation 0 collects per 1000 operations
  Gen 1                 : GC Generation 1 collects per 1000 operations
  Gen 2                 : GC Generation 2 collects per 1000 operations
  Allocated             : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 us                  : 1 Microsecond (0.000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:01:27 (87.86 sec), executed benchmarks: 14

Global total time: 00:02:16 (136.87 sec), executed benchmarks: 14
// * Artifacts cleanup *
</details>

I suspect the lack of GCs for the larger parameter values is down to there being too few iterations for GCs to occur?

I'll try to get this done on Windows too if nothing is wrong with this approach to measuring the possible impact of this change, and will attempt to run the benchmark against some more representative XML documents of varying sizes and shapes.

**Comment by chrisdcmoore** [comment]
Same benchmark on Windows:

<details>
<summary>Windows benchmark results</summary>

// * Summary *

BenchmarkDotNet=v0.13.1.1620-nightly, OS=Windows 10.0.20348
Intel Xeon Platinum 8175M CPU 2.50GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 7.0.0 (7.0.21.56701), X64 RyuJIT
  Job-NRDMVZ : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT
  Job-ABXBJO : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog  IterationTime=250.0000 ms
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1

|              Method |        Job |                                                                                                        Toolchain | NumberOfInnerElements |          Mean |      Error |     StdDev |        Median |           Min |           Max | Ratio | RatioSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|-------------------- |----------- |----------------------------------------------------------------------------------------------------------------- |---------------------- |--------------:|-----------:|-----------:|--------------:|--------------:|--------------:|------:|--------:|--------:|--------:|--------:|----------:|
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                     1 |     21.537 us |  0.4155 us |  0.3683 us |     21.506 us |     20.832 us |     22.047 us |  1.00 |    0.00 | 41.6103 | 41.6103 | 41.6103 |    195 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                     1 |      8.803 us |  0.3672 us |  0.4081 us |      8.707 us |      8.104 us |      9.732 us |  0.40 |    0.02 |  5.8528 |  0.9583 |       - |     99 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                    10 |     23.518 us |  0.4588 us |  0.4909 us |     23.447 us |     22.484 us |     24.630 us |  1.00 |    0.00 | 41.6027 | 41.6027 | 41.6027 |    196 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                    10 |     11.228 us |  0.7839 us |  0.9028 us |     11.219 us |      9.597 us |     13.050 us |  0.48 |    0.04 |  5.8945 |  1.4516 |       - |    100 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                   100 |     34.363 us |  0.3355 us |  0.3138 us |     34.270 us |     33.990 us |     35.037 us |  1.00 |    0.00 | 41.6382 | 41.6382 | 41.6382 |    196 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                   100 |     22.192 us |  0.7899 us |  0.9096 us |     21.812 us |     21.189 us |     24.232 us |  0.65 |    0.03 |  5.8582 |  1.3990 |       - |    100 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                  1000 |    152.124 us |  2.0447 us |  1.7074 us |    152.007 us |    150.060 us |    156.023 us |  1.00 |    0.00 | 41.5913 | 41.5913 | 41.5913 |    196 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                  1000 |    133.583 us |  0.8655 us |  0.6758 us |    133.529 us |    132.564 us |    135.027 us |  0.88 |    0.01 |  5.8573 |  1.0650 |       - |    100 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                 10000 |  1,255.406 us | 14.3190 us | 11.9570 us |  1,250.215 us |  1,241.800 us |  1,277.271 us |  1.00 |    0.00 | 40.0000 | 40.0000 | 40.0000 |    196 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                 10000 |  1,210.977 us |  1.4844 us |  1.3159 us |  1,210.831 us |  1,209.057 us |  1,212.923 us |  0.96 |    0.01 |  4.9020 |       - |       - |    100 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                 50000 |  5,957.860 us | 27.9351 us | 24.7637 us |  5,946.587 us |  5,932.036 us |  6,007.750 us |  1.00 |    0.00 | 23.8095 | 23.8095 | 23.8095 |    198 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                 50000 |  5,989.059 us | 29.9879 us | 25.0413 us |  5,978.379 us |  5,970.507 us |  6,055.167 us |  1.01 |    0.00 |       - |       - |       - |    103 KB |
|                     |            |                                                                                                                  |                       |               |            |            |               |               |               |       |         |         |         |         |           |
| XmlReader_ReadAsync | Job-NRDMVZ |                     \main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                100000 | 12,077.323 us | 28.0912 us | 23.4574 us | 12,072.721 us | 12,051.214 us | 12,124.957 us |  1.00 |    0.00 |       - |       - |       - |    200 KB |
| XmlReader_ReadAsync | Job-ABXBJO | \xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe |                100000 | 11,943.568 us | 16.0510 us | 13.4033 us | 11,939.964 us | 11,926.157 us | 11,968.800 us |  0.99 |    0.00 |       - |       - |       - |    107 KB |

// * Warnings *
MultimodalDistribution
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> It seems that the distribution can have several modes (mValue = 3)

// * Hints *
Outliers
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (22.56 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 1 outlier  was  removed (10.06 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (25.38 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 2 outliers were removed (159.98 us, 166.04 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 3 outliers were removed (139.79 us..144.66 us)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 2 outliers were removed (1.33 ms, 1.37 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 1 outlier  was  removed (1.30 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 1 outlier  was  removed (6.29 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 2 outliers were removed (6.15 ms, 6.33 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\main\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1                     -> 2 outliers were removed (12.32 ms, 12.43 ms)
  XmlReaderBuffers.XmlReader_ReadAsync: PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, Toolchain=\xmlreader-smaller-buffer\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1 -> 2 outliers were removed (12.06 ms, 12.58 ms)

// * Legends *
  NumberOfInnerElements : Value of the 'NumberOfInnerElements' parameter
  Mean                  : Arithmetic mean of all measurements
  Error                 : Half of 99.9% confidence interval
  StdDev                : Standard deviation of all measurements
  Median                : Value separating the higher half of all measurements (50th percentile)
  Min                   : Minimum
  Max                   : Maximum
  Ratio                 : Mean of the ratio distribution ([Current]/[Baseline])
  RatioSD               : Standard deviation of the ratio distribution ([Current]/[Baseline])
  Gen 0                 : GC Generation 0 collects per 1000 operations
  Gen 1                 : GC Generation 1 collects per 1000 operations
  Gen 2                 : GC Generation 2 collects per 1000 operations
  Allocated             : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 us                  : 1 Microsecond (0.000001 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:01:28 (88.84 sec), executed benchmarks: 14

Global total time: 00:02:24 (144.56 sec), executed benchmarks: 14
// * Artifacts cleanup *

</details>

**Comment by adamsitnik** [comment]
I agree that the current default buffer size it too large and we should most probably reduce it.

We should also consider extending `XmlReaderSettings` with `BufferSize` and allowing the users to control the setting (similarly to `FileStreamOptions.BufferSize`).

**Comment by krwq** [comment]
@chrisdcmoore do you feel like making a PR?

**Comment by chrisdcmoore** [comment]
Hey folks, sorry for the radio silence on this - took a technology break over the holidays!

Happy to raise a PR halving the async buffer size as per the benchmarks, and happy to raise another issue for making the buffer size configurable and having a stab at implementing that in a separate PR if that suits you?
