### ISSUE TITLE
Some repos do not contribute to third-party-notices file

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#61466]
Here's a list of repos that should contribute to the shipping third-party-notices file, but that don't have their TPN file established in their repos.

We need to work with each repo owner to establish and maintain their TPN files. Once that is changed, our TPN generation infra (in PR: https://github.com/dotnet/runtime/pull/60091) should be updated.

Additional repos that should be included but don't have any third-party-notices files:

- [x] dotnet/efcore - confirmed, no 3p code
- [ ] dotnet/emsdk - content likely needed
- [x] dotnet/icu - content likely needed https://github.com/dotnet/icu/pull/200
- [x] dotnet/extensions - under the Runtime and ASPNet repos and covered by those TPNs
- [x] dotnet/sdk - possibly covered by dotnet/installer TPN
- [x] dotnet/windowsdesktop - confirmed, no 3p src in WinForms or WPF shipping assets
- [x] dotnet/linker - will be resolved by https://github.com/dotnet/linker/pull/2469

**Comment by NikolaMilosavljevic** [comment]
[Triage] @leecow is this something you were tracking and can be enabled early in 7.0 so we have all contributing repos onboarded on time?

**Comment by leecow** [comment]
Yes, I can track and work with the missing repos.

**Comment by danmoseley** [comment]
@NikolaMilosavljevic did you get a chance to reach out?

**Comment by NikolaMilosavljevic** [comment]
> @NikolaMilosavljevic did you get a chance to reach out?

@leecow was going to work with missing repos. @leecow were there any updates, should we have an issue for each repo to create TPN file, so we can harvest it and include relevant notices in the shipping file?

**Comment by leecow** [comment]
Sorry, fell off the plate. I like the idea of individual issues which I can open in the repos listed above. Will also communicate with owners internally to give them a heads up.

**Comment by RussKie** [comment]
Windows Forms do not use any 3rd party dependencies (i.e., non Microsoft) in the production code (i.e., the code we ship in Windows Desktop). Standing by for the WPF sign off from @singhashish-wpf to complete the Windows Desktop story.

**Comment by NikolaMilosavljevic** [comment]
@leecow is there any pending work for the last remaining repo `dotnet/emsdk`?

We need to update main third-party-notices file, which will harvest TPNs from all dependent repos - https://github.com/dotnet/runtime/issues/74605

**Comment by NikolaMilosavljevic** [comment]
Removing 'blocking-release' label - we are updating TPN notices for 7.0 with https://github.com/dotnet/runtime/pull/74760

**Comment by leecow** [comment]
@lewing - anything in emsdk that needs to be covered by a third-party license notice?

**Comment by NikolaMilosavljevic** [comment]
Moving to 8.0 - we've updated TPN file for 7.0 release with: https://github.com/dotnet/runtime/pull/74760
