### ISSUE TITLE
System.Random.XoshiroImpl seeding inconsistency between platforms

### ISSUE THREAD

**Issue by camerondm9** [dotnet/runtime#61478]
From what I can see, XoshiroImpl calls Interop.GetRandomBytes to get its' seed material.

Interop.GetRandomBytes is implemented differently on each platform:
On Android, OSX, and Windows, it appears to return cryptographically secure random bytes.
On Unix there seem to be two implementations, one which returns cryptographically secure random bytes and another which does not. I tested which implementation is active on my Ubuntu installation (.Net 6.0 on Ubuntu 18 LTS), and it seems to be using the non-cryptographically secure version (at least, that's what the name is: [Interop.GetRandomBytes.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Unix/System.Native/Interop.GetRandomBytes.cs#L18)).

I realize that this is an internal implementation detail, but it seems inconsistent to be seeding the RNG securely on all platforms but one.
I don't think this is a security issue, because System.Random isn't a cryptographic RNG.

**Comment by GrabYourPitchforks** [comment]
Throwing it over the wall to the _System.Runtime_ folks. My initial inclination is to resolve as by design. As OP notes, this is an internal implementation detail. There's no technical requirement to change this code, nor is there any perceivable benefit from doing so.

**Comment by vcsjones** [comment]
My 2c:

> but it seems inconsistent to be seeding the RNG securely on all platforms but one.

I don't think this is inconsistent in terms of the security properties of `System.Random`. Even _if_ Xoshiro128/256** is seeded from a secure source, it is still unsafe to use in security-sensitive scenarios. Xoshiro** can trivially recover the internal state by observing only 4 outputs from it (allowing recovery of future and past generated values), regardless of how it is seeded.

I would agree it is is an implementation detail, and, even if it were seeded from a CSPRNG consistently, that would not change the security properties of `System.Random`: it is still insecure in that regard.

**Comment by stephentoub** [comment]
There was no intent here for this to be seeded with a source guaranteed to be cryptographically secure (previous versions of Random were just seeded by the current time, for example).  On Windows and macOS that was just the most convenient thing to do with little downside.  If we were going to consolidate in any direction, it would be towards a non-cryptographically secure source, but I don't see a strong impetus for a change here, unless there's a demonstrable perf benefit to it.
