### ISSUE TITLE
SocketsHttpHandler: Support zero-byte read on response streams

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#61475]
Supporting zero-byte read helps users of these APIs reduce memory usage. It allows them to release their read buffers when no data is currently available.

We should support this in our HTTP response streams in SocketsHttpHandler, including RawConnectionStream since this is used for WebSockets and tunneling scenarios.

Ideally we would also release our own read buffer (if any and if possible) and issue a zero-byte read against the underlying connection. This is what SslStream does (as of 6.0). The idea here is that the user has indicated their interest in minimizing buffer memory usage, and so we should do the same for our own internal buffers.

I split this issue off from https://github.com/dotnet/runtime/issues/61223.

**Comment by karelz** [comment]
Partial fix is also in 6.0.9 (see PR #72804)
