### ISSUE TITLE
Blazor WASM debugging stops working with VS 2022 RC. Server side still works.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#61531]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-WASM-debugging-stops-working-with/1573413)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:VS 2019 most recent]
I took an existing project and opened it in vs 2022. I changed each project (client, server, model) to use .net 6.0.
I have deleted the obj and bin folders (debug build).
I have cleaned the solution.
When I set a breakpoint in the wasm project before hitting continue the breakpoint sets but after compilation and start up I get "The breakpoint will not currently be hit ..."  Changing the settings to allow the source code to be different makes not difference. 

I did some googling and other people are complaining but dev appears to be closing the issue because they can't reproduce it. The issue may only appear in projects previously built in vs 2019.

---
#### Feedback Bot on 11/7/2021, 07:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by thaystg** [comment]
Are you using this version of this package?
![image](https://user-images.githubusercontent.com/4503299/141596566-e7b0f724-c112-4563-b50f-8a5afe81da5b.png)
