### ISSUE TITLE
CryptoStream failed to decrypt data on NET6.0

### ISSUE THREAD

**Issue by ymalich** [dotnet/runtime#61535]
### Description

Hello,
But testing my apps with .NET 6.0 I've discovered the new bug in CryptoStream.Read - it truncates the data in outpu buffer by decryption via Read.
cStream.Read(data, 0, expectedSize);
The CryptoStream.Read method works well on net48 and net 5.0, the bug  only in net6.0.
  
 I've attached the test solution with project so you canreproduce the bug.

### Reproduction Steps

Encrypt the data 
public static byte[] EncryptData(byte[] data, byte[] key, byte[] iv)
        {
            // Create or open the specified file.
            var mStream = new MemoryStream(data.Length);

            // Create a new Rijndael object.
            var encryptor = Rijndael.Create();

            // Create a CryptoStream using the FileStream 
            // and the passed key and initialization vector (IV).
            mStream.Position = 0;

            using (var cStream = new CryptoStream(mStream, encryptor.CreateEncryptor(key, iv), CryptoStreamMode.Write))
            {
                cStream.Write(data, 0, data.Length);
            }

            return mStream.ToArray();
        }

And Decrypt the data immediately 
private static byte[] DecryptData(byte[] encryptedData, byte[] key, byte[] iv, int expectedSize, out int dataSize)
        {
            // Create or open the specified file. 
            using var mStream = new MemoryStream(encryptedData);

            // Create a new Rijndael object.
            var decryptor = Rijndael.Create();

            // Create a CryptoStream using the FileStream 
            // and the passed key and initialization vector (IV).
            using var cStream = new CryptoStream(mStream, decryptor.CreateDecryptor(key, iv), CryptoStreamMode.Read);
            byte[] data = new byte[expectedSize * 2];
            int readBytes = 0;
            readBytes = cStream.Read(data, 0, expectedSize);

            dataSize = readBytes;
            return data;
        }

Compare the results.

Pleas check attached project 
Bug.zip

### Expected behavior

Input and output data equal.

### Actual behavior

Input and output data don't equal on NET6.
Input and output data equal in NET4.8 and NET 5.0.

### Regression?

Yes

### Configuration

Windows 10 Pro x64.
dotnet 6.0.100.

### Other information

[CryptoStreamBugInNet6.zip](https://github.com/dotnet/runtime/files/7530769/CryptoStreamBugInNet6.zip)

**Comment by stephentoub** [comment]
This:
```C#
        int readBytes = 0;
        readBytes = cStream.Read(data, 0, expectedSize);
```
is the issue.  There's no guarantee with Stream.Read that it returns everything asked for.
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by ymalich** [comment]
Hello @stephentoub,
I do it actually in the real app, it's only the example to test and the allocated output buffer is large enough to contain all the data to be read.  
The buffer in this test sample is 40066 bytes.
If you compare the data returned by read in the version 5.0 and 6.0 
In version .net version 4.8 and 5.0 it reads 20033 bytes.
In version .net version 6.0 it reads only 20016 bytes, 17 bytes less than it has to be!

**Comment by stephentoub** [comment]
> It is definitely wrong.

There is no guarantee as to how many bytes Stream.Read needs to return, other than it can't return 0 unless it hits the end of the stream.  If you need it to return exactly what you asked for and it returns less, you need to call Read again to fill in more data.

**Comment by ymalich** [comment]
@stephentoub 
ok, I understood, thanks!
