### ISSUE TITLE
Windows ARM64 CoreCLR runtime tests are failing in CI with empty logs

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#61548]
Example of a [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61523-merge-c822c52a83fc4f5985/profiler.eventpipe/1/console.ccbb1349.log?sv=2019-07-07&se=2021-12-03T04%3A10%3A12Z&sr=c&sp=rl&sig=saEtD7sr%2Fh5OyMPuXzNStEMe7%2Fc9D10GvfO46swGLAI%3D):
```
Console log: 'profiler.eventpipe' from job c822c52a-83fc-4f59-8527-8d865329e17e workitem
73626991-b9eb-4638-b750-a399b9653db6 (windows.10.arm64v8.open) executed on machine DDARM64-155
```
The tests that fail seem to be different, but the machine - the same.

Sample runs:
1) https://dev.azure.com/dnceng/public/_build/results?buildId=1468194&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382
2) https://dev.azure.com/dnceng/public/_build/results?buildId=1467927&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382
3) https://dev.azure.com/dnceng/public/_build/results?buildId=1468124&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382
4) https://dev.azure.com/dnceng/public/_build/results?buildId=1468247&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382

**Comment by hoyosjs** [comment]
All workitems on this machine failed prior to 2021-11-15T12:39:25.868Z, but since then it's been reset and two workitems have successfully executed, including a loader one from and one from ObjectPool. Closing this as it seems to have been mitigated.
