### ISSUE TITLE
System.Linq MaxBy and MinBy call eagerly the keySelector function.

### ISSUE THREAD

**Issue by Orace** [dotnet/runtime#61556]
For sequences with only one element, there is no need for the `System.Linq.MaxBy` and `System.Linq.MinBy` methods to call the `keySelector` to determinate which element to return (hints: it's the single element of the sequence).

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq/src/System/Linq/Min.cs#L502-L503

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq/src/System/Linq/Max.cs#L544-L545

**Comment by GrabYourPitchforks** [comment]
Invoking the key selector could have an observable side effect, such as throwing or changing state. The area owners would need to consider whether keeping consistency between single-element collections and multiple-element collections is the desired behavior.

**Comment by danmoseley** [comment]
@Orace is this having a measurable impact for you? Or you just observed while inspecting the implementation? If the latter, as noted above, it may be best to leave it.

**Comment by Orace** [comment]
@danmoseley indeed I observed it while inspecting the implementation that I need to reproduce for the [EnumerationQuest](https://github.com/Orace/EnumerationQuest) library. The current implementation in EnumerationQuest avoid the call to the `keySelector`.

**Comment by eiriktsarpalis** [comment]
While LINQ is known to have made similar optimizations in the past, this would be optimizing for a relatively uncommon use case at the expense of less trivial workflows.

@GrabYourPitchforks makes a good point about maintaining consistency wrt side-effects: there have been instances in the past where we've reverted optimizations for this reason (e.g. #36643). Even if we wanted to adopt the proposal at this stage it would be a breaking change.
