### ISSUE TITLE
Consider using a faster memset

### ISSUE THREAD

**Issue by LifeIsStrange** [dotnet/runtime#61561]
Low levels, primitive functions like memset are major constituants of performance in general.
Surprisingly, many of those important primivitves are generally not using SIMD instructions (let alone AVX 256) despite widespread support and dramatic performance improvements.
Indeed the Glibc & ci have some inertia..

https://github.com/moon-chilled/fancy-memset
Could an alternative, faster memset be used for .NET?

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/edd64670617223c473051921268c4fc1962407a0/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.T.cs#L22-L133

The managed equivalent of memset already use vectorize.

**Comment by danmoseley** [comment]
@LifeIsStrange can you point to a place in the code where we should vectorize and do not? As @huoyaoyuan points out, this was added with https://github.com/dotnet/runtime/pull/51365 or before.

**Comment by deeprobin** [comment]
I mean we already use a very fast memset where there is little potential for optimization.
@danmoseley I think you could close this issue.
