### ISSUE TITLE
ReadyToRun build does not work on Windows 10 - no crash, just 0xC0000602

### ISSUE THREAD

**Issue by 0xC0000054** [dotnet/runtime#61584]
### Description

I published a project using the built-in VS2022  command after upgrading from .NET 5 to .NET 6.

The non-composite ReadyToRun build fails to open, and a 0xC0000602 error is written to the Windows application event log.
The ReadyToRun composite build works fine.

The non-composite ReadyToRun build works correctly if the `obj` folder in the project root is deleted.

### Reproduction Steps

Download the following project: [PluginTrampoline_NET6_R2R_bug.zip](https://1drv.ms/u/s!AqKhyKX5oDIvhT8wWmWHu3gMxjc0?e=JsiOYE)
Publish it using the VS2022 publish command.
Run the published PluginTrampoline executable.

If you do not want to download and build the project, the following files contain the output of the VS2022 publish command:

[PluginTrampoline_R2R.zip](https://1drv.ms/u/s!AqKhyKX5oDIvhT20PsqAcrO1mamU?e=jdSMjr)

[PluginTrampoline_R2R_composite.zip](https://1drv.ms/u/s!AqKhyKX5oDIvhT6nk1UDDX3yjy8y?e=LJNcLg)

### Expected behavior

The published R2R project runs.

### Actual behavior

The published R2R project does not open, and a 0xC0000602 error is written to the Windows application event log.

### Regression?

Possibly, the publish command was working on .NET 5.

### Known Workarounds

1. Delete the `obj` folder in the project root.
2. Enable ReadyToRun composite mode

### Configuration

.NET 6.0.0 rtm
Windows10 21H1 x64
self-contained deployment of WindowsDesktop app

### Other information

It appears to be something in the `obj` folder that is causing the issue.
Perhaps a file conflict of some kind?

**Comment by rickbrew** [comment]
I wonder if this is related to #61544

**Comment by EgorBo** [comment]
The dropbox links throw 404

**Comment by 0xC0000054** [comment]
> The dropbox links throw 404

I changed the links to use OneDrive.

**Comment by AntonLapounov** [comment]
This is a .NET 5 to .NET 6 upgrading issue. What happens here is a composite build (the default R2R compilation mode for .NET 5) got mixed with a non-composite build (the default R2R compilation mode for .NET 6).  Some assemblies were not recompiled and still reference the PluginTrampoline.r2r.dll composite binary, which is no longer produced when for .NET 6.  `coreclr!NativeImage::Open` tries to load that composite binary and fail-fasts since the file is missing.

**Comment by mangod9** [comment]
believe 6 to 7 upgrade shouldnt hit the issue since R2R composite is no longer the default. Please reopen if you hit it in 7. Thx
