### ISSUE TITLE
System.Text.Json 6.0.0 package breaks builds with .Net SDK 3.1

### ISSUE THREAD

**Issue by ArturDorochowicz** [dotnet/runtime#61602]
### Description

Building a project that references System.Text.Json 6.0.0 with .Net SDK 3.1 produces a warning like this:
```
SC : warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator 
cannot be created from 
/root/.nuget/packages/system.text.json/6.0.0/analyzers/dotnet/roslyn3.11/cs/System.Text.Json.SourceGeneration.dll : 
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
The system cannot find the file specified..
```

### Reproduction Steps

```
dotnet new globaljson --sdk-version 3.1.400
dotnet new console
dotnet add package System.Text.Json --version 6.0.0
dotnet build
```

### Expected behavior

The project should build without errors or warnings.

### Actual behavior

The build produces the following warning (or error if TreatWarningsAsErrors is enabled)

```
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from /root/.nuget/packages/system.text.json/6.0.0/analyzers/dotnet/roslyn3.11/cs/System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/src/src.csproj]
  src -> /src/bin/Debug/netcoreapp3.1/src.dll

Build succeeded.

CSC : warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from /root/.nuget/packages/system.text.json/6.0.0/analyzers/dotnet/roslyn3.11/cs/System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/src/src.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.81
```

### Known Workarounds

You can pass `DisableSystemTextJsonSourceGenerator` to disable all versions of the generator: `dotnet build -p:DisableSystemTextJsonSourceGenerator=true`.

I don't think this should be necessary and it should work out of the box.

### Configuration

```
>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.415
 Commit:    52a108342e

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.415/

Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  3.1.415 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Other information

Seems that the package includes source generators for .Net SDK 5 and .Net SDK 6 and in a .targets file removes support for .Net SDK 6 if the build happens in an older version, but it doesn't take into account that .Net SDK 3.1 is still a supported version (and actually will be supported for longer than 5.0) and doesn't remove all analyzers on that platform.

**Comment by ericstj** [comment]
@eerhardt what's the expected behavior when folks use the generators on older roslyn versions.  Do we have any way to detect those and not fail?  I know you had to add a declarative version in 6.0, but I don't recall if we still have some fallback for older versions.

**Comment by eerhardt** [comment]
For versions of the .NET SDK before 6.0, we fallback to just adding the `3.11` version of the source generator to the project.

https://github.com/dotnet/runtime/blob/072e8761dff95d8e9f830b88125c7e708f24a37b/eng/MultiTargetRoslynComponent.targets.template#L9-L19

There is no support for "multi-targeting" before 6.0, so we use the lowest version possible - `3.11`. Also, in earlier versions there isn't a straight-forward way of knowing what version of Roslyn will be used, so we don't know if you have `3.7`, `3.9`, or `3.11`.

The general recommendation is to always update your SDK, even if you are targeting older TFMs - like `netcoreapp3.1`. You can build a `netcoreapp3.1` app with a `5.0` or `6.0` SDK. See https://docs.microsoft.com/en-us/dotnet/core/tools/global-json:

> In general, you want to use the latest version of the SDK tools, so no global.json file is needed.

If you have issues with using the latest SDK, please log an issue so we can address it: https://github.com/dotnet/sdk/issues.

If you must use the `3.1` SDK, setting `DisableSystemTextJsonSourceGenerator=true` is your next best approach. Note that this can be set in a `Directory.Build.props` file, so you don't need to pass it on the command line each time.

**Comment by ArturDorochowicz** [comment]
It's disappointing it can't work out of the box on 3.1 LTS, but I understand from your answer that there are sound technical reasons behind it. Thanks for replying.

**Comment by eerhardt** [comment]
> It's disappointing it can't work out of the box on 3.1 LTS

I understand and agree with the disappointment. Unfortunately there wasn't a way to check "are source generators supported?" in the `3.1` LTS tooling.

**Comment by eiriktsarpalis** [comment]
I think we can close this as answered.
