### ISSUE TITLE
Cannot pass byte pointer to array from rust runtime to wasm: TypeError: Buffer is already detached

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#61600]
Originally opened by @tmarkovski as mono/mono#21308

---

I'm trying to invoke a function in a rust library from blazor using the native file reference functionality in net 6.
I'm able to pass arrays into the native library, but not return them back to wasm.

I have a test project setup here https://github.com/tmarkovski/rust-blazor-test

My goal is to be able to pass byte array from blazor wasm and get back another byte array from the native rust library. This already works fine when using P/Invoke with non-wasm .net runtimes, I'm trying to adopt it for wasm.

My rust function is defined as
```rust
#[repr(C)]
pub struct ByteBuffer {
    len: i64,
    data: *mut u8,
}

#[no_mangle]
pub extern "C" fn buffer_in_out(buffer: &ByteBuffer, buffer_out: &mut ByteBuffer) {
}
```
and the C#
```cs
[StructLayout(LayoutKind.Sequential)]
public struct ByteBuffer
{
    public long Length;
    public IntPtr Data;
}

[DllImport("libmath")]
public static extern void buffer_in_out(ByteBuffer buffer, out ByteBuffer out_buffer);
```

It appears that I have issues marshaling the pointers back to wasm. Even if I create a byte array in Rust and force it to be leaked using `Box::leak()` or `mem::forget()`, I cannot seem to return a pointer back to wasm. My sample project has few different scenarios that I played with using different method signatures, but any use of vec or slice in Rust seems to throw the errors below about object being disposed. Even if the return result doesn't reference any of the data used in the function.

## Steps to Reproduce

1. Clone https://github.com/tmarkovski/rust-blazor-test
2. Build Rust using `cargo build --target wasm32-uknown-unknown`
3. Run Blazor project using `dotnet run` requires (net6)

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:

dotnet 6.0.100

## Stacktrace

```
Unhandled Promise Rejection: Error: JS object instance with ID NaN does not exist (has it been disposed?).

Unhandled Promise Rejection: TypeError: Underlying ArrayBuffer has been detached from the view

TypeError: Buffer is already detached

[Error] Error
	_handle_exception_for_call (dotnet..2lu21tdpyb.js:8518)
	managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle (managed_BINDINGS_ReleaseJSOwnedObjectByGCHandle:16)
	_js_owned_object_finalized (dotnet..2lu21tdpyb.js:7389)
	_js_owned_object_finalized
```

**Comment by lambdageek** [comment]
@tmarkovski You need to use the `wasm32-unknown-emscripten` target - not `wasm32-unknown-unknown`.  That way the generated static library can use the same heap that Emscripten uses for malloc/free.  That makes `vec![0,1,2]` not panic, and also makes the `buffer_in_out` example work (but it leaks since nothing deallocates the buffer data)

```rust
#[no_mangle]
pub extern "C" fn buffer_in_out(buffer: &ByteBuffer, buffer_out: &mut BBuffer) {
    let mut result = vec![4u8, 5, 6].into_boxed_slice();
    let len = result.len();
    let result_ptr = result.as_mut_ptr();

    mem::forget(result);

    *buffer_out = BBuffer { len: len as i64, data: result_ptr }
}
```

Another important note:  I'm not sure what version of Emscripten is used when you use `rustup add target wasm32-unknown-emscripten`.  But there could be a chance that the version used by `dotnet workload install wasm-tools` will be incompatible with the one used by Rust.  Ideally both rust and Blazor should use the same version.  I'm not sure how to force that to be the case.

**Comment by tmarkovski** [comment]
Thanks @lambdageek - sorry that was too obvious, I shouldn't have missed it.

**Comment by lambdageek** [comment]
For anyone that may come across this issue in the future: `wasm32-unknown-emscripten` seems to just use `emcc` from the PATH.

So the following should be good enough to make `cargo build` use the version of emscripten bundled with .NET 6:

```sh

dotnet_packs_dir=/usr/local/share/dotnet/packs
dotnet_emscripten_prefix=Microsoft.NET.Runtime.Emscripten.2.0.23
dotnet_rid=osx-x64
dotnet_ver=6.0.0

# set variables read by tools/emscripten/.emscripten
export DOTNET_EMSCRIPTEN_LLVM_ROOT=${dotnet_packs_dir}/${dotnet_emscripten_prefix}.Sdk.${dotnet_rid}/${dotnet_ver}/tools/bin
export DOTNET_EMSCRIPTEN_NODE_JS=${dotnet_packs_dir}/${dotnet_emscripten_prefix}.Node.${dotnet_rid}/${dotnet_ver}/tools/bin/node
export DOTNET_EMSCRIPTEN_BINARYEN_ROOT=${dotnet_packs_dir}/${dotnet_emscripten_prefix}.Sdk.${dotnet_rid}/${dotnet_ver}/tools/bin

export PATH="${dotnet_packs_dir}/${dotnet_emscripten_prefix}.Sdk.${dotnet_rid}/${dotnet_ver}/tools/emscripten:${PATH}"
```

**Comment by ilonatommy** [comment]
@lambdageek, isn't the issue solved?
