### ISSUE TITLE
JIT: Optimize *x = dblCns to *x = intCns for arm64

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#61620]
Yet another up-for-grabs:
```csharp
void foo(float* x) => *x = 0;
```
emits:
```asm
            movi    v16.16b, #0x00
            str     s16, [x1]
```
while could be just:
```asm
            str     wzr, [x1]
```
The issue is basically to port these changes https://github.com/dotnet/runtime/pull/52298 to ARM64 or better - move them to lower.cpp and share between both x86 and arm.

**Comment by SeanWoo** [comment]
A good task to start with. I did this and posted a PR. #61847

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/61847 👍
