### ISSUE TITLE
[Mono][Perf][AOT] Regressions in BigInteger benchmarks.

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#61623]
I am seeing regressions in several BigInteger benchmarks, in mono-aot that seem to be related to this change: https://github.com/dotnet/runtime/commit/22b516ca0a4b9851cf993ecc83b2a8238898c465

@sakno @gfoidl Any ideas? 

Automated issue below.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [cc7f2f9c1a80c262055757331acca25d2748d381](https://github.com/dotnet/runtime/commit/cc7f2f9c1a80c262055757331acca25d2748d381)
Compare | [ce4eb48eb8950e3a1454149af14318494a1ca95e](https://github.com/dotnet/runtime/commit/ce4eb48eb8950e3a1454149af14318494a1ca95e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/cc7f2f9c1a80c262055757331acca25d2748d381...ce4eb48eb8950e3a1454149af14318494a1ca95e)

### Regressions in System.Numerics.Tests.Perf_BigInteger

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ModPow - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=true_MonoInterpreter=false/System.Numerics.Tests.Perf_BigInteger.ModPow(arguments%3a%2016384%2c16384%2c64%20bits).html>) | 2.91 ms | 4.14 ms | 1.42 | 0.01 | True | | |
[Add - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=true_MonoInterpreter=false/System.Numerics.Tests.Perf_BigInteger.Add(arguments%3a%2016%2c16%20bits).html>) | 21.64 ns | 30.60 ns | 1.41 | 0.01 | True | | |
[Divide - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_LLVM=false_MonoAOT=true_MonoInterpreter=false/System.Numerics.Tests.Perf_BigInteger.Divide(arguments%3a%2016%2c8%20bits).html>) | 19.88 ns | 22.10 ns | 1.11 | 0.04 | True | | |

[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_25_2021/refs/heads/main_x64_ubuntu%2018.04_LLVM=false_MonoAOT=true_MonoInterpreter=false_Regression/System.Numerics.Tests.Perf_BigInteger.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net6.0 --filter 'System.Numerics.Tests.Perf_BigInteger*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-cce9c86f-9107-419d-909f-b4a44b657460943a1adfbe740e693/bf6563b8-d134-4acf-9612-c5ed267dcba1.zip?sv=2019-07-07&se=2021-11-07T15%3A30%3A32Z&sr=c&sp=rl&sig=3SXUlElK6ne4XH5zEcISAMmyQL2f65YHeC5EoNlSxpg%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-830d53a6-6fc7-4a76-8749-0645212a15152f4581110de40b483/18cc722b-c883-4860-9722-8b47cffc8636.zip?sv=2019-07-07&se=2021-11-07T21%3A55%3A59Z&sr=c&sp=rl&sig=wBMAOjKkgOXwtO11LMyvCyqDQX0Z3n%2Fv9ZazajgI2Bs%3D>)
#### System.Numerics.Tests.Perf_BigInteger.ModPow(arguments: 16384,16384,64 bits)

```log

```
#### System.Numerics.Tests.Perf_BigInteger.Add(arguments: 16,16 bits)

```log



```
#### System.Numerics.Tests.Perf_BigInteger.Divide(arguments: 16,8 bits)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by naricc** [comment]
Also effecting these sets of benchmarks:

https://github.com/dotnet/perf-autofiling-issues/issues/2195
https://github.com/dotnet/perf-autofiling-issues/issues/2064

**Comment by sakno** [comment]
@naricc , see comment from @jeffhandley here: #60293.

**Comment by naricc** [comment]
@jeffhandley So it looks like the decision for CoreCLR was basically that this was an acceptable trade-off? I don't see any reason it should be acceptable in mono too, and will close the issue if that is the conclusion.

@SamMonoRT

**Comment by jeffhandley** [comment]
From the CoreCLR side, yes, we did think these were acceptable trade-offs. We can close this. Thanks, @naricc.
