### ISSUE TITLE
BindToDirectory throws NullReferenceException on Linux when LdapConnection AuthType is Anonymous

### ISSUE THREAD

**Issue by JasonDebug** [dotnet/runtime#61683]
### Description

When using `AuthType.Anonymous` in `LdapConnection`, `System.DirectoryServices.Protocols.LdapPal.BindToDirectory` throws a `NullReferenceException`.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.DirectoryServices.Protocols.LdapPal.BindToDirectory(ConnectionHandle ld, String who, String passwd)
   at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
   at System.DirectoryServices.Protocols.LdapConnection.Bind()
```

This issue does not occur in Windows.

### Reproduction Steps

Run the following code in Linux:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices.Protocols" Version="6.0.0" />
  </ItemGroup>

</Project>
```
```csharp
LdapDirectoryIdentifier ldapID = new LdapDirectoryIdentifier(_serverName_, 389, false, false);
LdapConnection ldapConnection = new LdapConnection(ldapID);
ldapConnection.AuthType = AuthType.Anonymous;
LdapSessionOptions ldapOptions = ldapConnection.SessionOptions;
ldapOptions.ProtocolVersion = 3;
ldapConnection.Bind();    // This line will throw NullReferenceException
```

### Expected behavior

The code works

### Actual behavior

The code throws a `NullReferenceException`

### Regression?

The responsible code was added in this commit:

https://github.com/dotnet/runtime/commit/32918374655b5e1c3fc7810bbb0c06a0d03265b7#diff-1b5dd42e4f4f04e57161fa4e3a946dd3702fdc5ad206ab89ca75be6e46e95b42R110

Suggested change would be to simply check for null:

```csharp
bv_len = passwd?.Length ?? 0,
```

### Known Workarounds

None

### Configuration

Tested with .NET 6.0.100 SDK on WSL2 Ubuntu

**Comment by joperezr** [comment]
Thanks for logging the issue. We don't currently support Anonymous AuthType on Linux, we are planning to add that on .NET 7 as well as other authentication mechanisms. The only ones that work in Linux today are Basic (e.g. passing in credentials) and Negotiate which is used for scenarios where your Linux machine is domain joined to your domain controller, so LdapConnection will reuse the Kerberos ticket already present on the machine.

**Comment by joperezr** [comment]
That said it is for sure wrong to throw NullReferenceException. I'm fine with fixing that and instead just return PlatformNotSupported for now while we add this support.
