### ISSUE TITLE
DateTime.ToString("d") cannot be parsed as a DateTime in Arabic

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/runtime#61708]
### Description

Short date format (`"d"`) doesn't produce a valid date string in Arabic (doesn't seem to matter which specific locale) on .NET 5.0 and later, and cannot be parsed back to a `DateTime` in the same culture.

### Reproduction Steps

```c#
CultureInfo.CurrentCulture = new CultureInfo("ar-TN");
DateTime date = new DateTime(2002, 1, 1, 23, 59, 59, 999);
string badDate = date.ToString("d");
DateTime error = DateTime.Parse(badDate);

Console.WriteLine(badDate);
```

### Expected behavior

A `DateTime` formatted with a standard date format in a specific culture should be able to be reconstituted as a `DateTime` in that same culture.

### Actual behavior

The **actual** string produced in `ar-TN` is:

```
"12002/1/"
```

Therefore, it cannot be parsed as a valid date, and produces a `FormatException`.

Error message displays:

![image](https://user-images.githubusercontent.com/1538288/142087632-8c9d3608-10c9-4c81-9ff0-6a63e4983f4f.png)

Visual Studio debugger displays:

![image](https://user-images.githubusercontent.com/1538288/142089698-f767f500-68d3-4743-90dc-8aa22c20b3fe.png)

Immediate window displays:

![image](https://user-images.githubusercontent.com/1538288/142089798-556158a8-35a1-4022-abed-09bb6b47cee6.png)

I don't consider the display issue as big of a problem as the parse issue, but it seems odd that the format is not consistent everywhere, and only the immediate window seems to display the actual one that cannot be parsed.

### Regression?

This started failing on .NET 5.0, presumably because of the change to ICU. It does not fail on .NET Core 3.1 or .NET Framework 4.8.

### Known Workarounds

None.

### Configuration

.NET 5 and .NET 6. SDK doesn't seem to matter. OS doesn't seem to matter, although it surely fails on Windows 10 x64.

### Other information

The upgrade to ICU (or some change related to it) seems like the most likely culprit being that it started happening in .NET 5.0.

**Comment by tarekgh** [comment]
@NightOwl888 you are using one of the Arabic cultures which insert [Right-To-Left characters](https://www.compart.com/en/unicode/U+200F) inside the date to ensure when displaying it will be displayed correctly as Right to Left text. We get the formatting pattern from Unicode standard [CLDR](https://cldr.unicode.org/). 

DateTime.Parse is not designed to parse any possible date or time string. Think about `Parse` as it tries to parse common usage of dates and time. The formatted strings are not normal as containing control marks so parsing failure is possible as you are seeing. What you should do is to use DateTime.ParseExact which can tell the parser which format this date should be parsed against. Do something like the folowing:

```C#
        DateTime error = DateTime.ParseExact(badDate, "d", null);
```

The guidelines in general, if you are formatting a date or time and intend to parse it back later, you should use `CultureInfo.InvariantCulture` and not using CurrentCulture or other culture. The other idea is to always format the date in ISO format (with "o" format) and always parse it with that format. Formatting the dare with current culture is useful only if you are displaying it to the user. But it is not a promising idea to use it if you intend to parse it again or serialize it to other systems.

**Comment by NightOwl888** [comment]
@tarekgh 

Thanks. It looks like `ParseExact` will solve our use case.

That being said, it still feels like this is broken. If you loop through all of the cultures **without specifying a format**, only variants of Arabic won't round-trip.

```c#
foreach (var culture in CultureInfo.GetCultures(CultureTypes.SpecificCultures | CultureTypes.NeutralCultures))
{
    try
    {
        DateTime date = new DateTime(2002, 1, 1, 23, 59, 59, 999);

        string str = date.ToString(culture);
        DateTime error = DateTime.Parse(str, culture);
    }
    catch (FormatException)
    {
        Console.WriteLine($"{culture.Name} failed to parse");
    }
}
```

Result

```
ar failed to parse
ar-001 failed to parse
ar-AE failed to parse
ar-BH failed to parse
ar-DJ failed to parse
ar-DZ failed to parse
ar-EG failed to parse
ar-ER failed to parse
ar-IL failed to parse
ar-IQ failed to parse
ar-JO failed to parse
ar-KM failed to parse
ar-KW failed to parse
ar-LB failed to parse
ar-LY failed to parse
ar-MA failed to parse
ar-MR failed to parse
ar-OM failed to parse
ar-PS failed to parse
ar-QA failed to parse
ar-SA failed to parse
ar-SD failed to parse
ar-SO failed to parse
ar-SS failed to parse
ar-SY failed to parse
ar-TD failed to parse
ar-TN failed to parse
ar-YE failed to parse
```

All of the other RTL languages round-trip fine, it is only Arabic that does not. 

> DateTime.Parse is not designed to parse any possible date or time string. Think about Parse as it tries to parse common usage of dates and time. The formatted strings are not normal as containing control marks so parsing failure is possible as you are seeing.

I wouldn't expect all formats to "just work", but we should at least be able to parse "g" and "d" without specifying a format as long as there is no culture change. It definitely feels broken when the raw output from `ToString(IFormatProvider)` cannot be parsed with `DateTime.Parse(string, IFormatProvider)` when the culture is Arabic.
