### ISSUE TITLE
[API Proposal]: Convert.ToString Methods

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#61719]
### Background and motivation

I have recently encountered a problem. I wanted to convert an `ulong` into a binary-digit `string`. I knew that there are methods in the `Convert` class to pass a base.
Unfortunately, I then found out that this is not available for the types with explicit sign specification. 

### API Proposal

```C#
namespace System
{
    public partial class Convert
    {
        public static string ToString(sbyte value, int toBase);
        public static string ToString(ushort value, int toBase);
        public static string ToString(uint value, int toBase);
        public static string ToString(ulong value, int toBase);

        // Optional:
        public static string ToString(nint value, int toBase);
        public static string ToString(nuint value, int toBase);
    }
}
```     

### API Usage

```C#
    ulong value = 123;
    string binaryResult = Convert.ToString(value, 2);
    string hexResult = Convert.ToString(value, 16);
```     

### Risks

No interference with other API methods, so see no risk here.

**Comment by tannergooding** [comment]
Closing this in favor of https://github.com/dotnet/runtime/issues/83619

You can get hex support today already for all the listed types via `ToString("X")`. The referenced issue, if approved, will allow the same for binary via `ToString("B")`.
