### ISSUE TITLE
Apparent memory leak in .NET versions 5 and 6 when enumerating an IAsyncEnumerable.

### ISSUE THREAD

**Issue by nhunt-zf** [dotnet/runtime#61717]
Likely related to: https://github.com/dotnet/runtime/issues/41187

### Description
When enumerating an IAsyncEnumerable and yielding asynchronously (resulting in a thread switch) within the loop, the last item that is enumerated is left on the heap (along with related state engine objects).
When the final enumerated item is large, this can have a serious impact on memory. For example, when using Chunk (or Buffer) , and the final count of buffered items is a large modulus of the chunk size.

Sample code to reproduce is at the end.

### Configuration
Reproduced on .NET 5 and 6. Windows x64, Using Debugger Memory Snapshot on Visual Studio 2019 and 2022.

### Data

Here is the sample partial heap at first breakpoint, where the enumeration yielded synchronously in the loop. No “leaked” objects remain.
![NoLeak](https://user-images.githubusercontent.com/90381711/142130279-a968bc87-8b93-4953-a467-13a5871bd939.png)

Here is the sample partial heap at second breakpoint, where the enumeration has yielded asynchronously, and all user code references to the objects have been released.
Note that a single BigClass object remains, along with its referenced large List<String>. Forced Garbage Collection of all levels has no impact.

![WithLeak](https://user-images.githubusercontent.com/90381711/142130368-b5c3fc57-cebc-47f5-83df-62e6af701c55.png)

Here is a real world scenario where the remnant heap objects have a significant memory consumption. 
At this point all non-framework items listed are unreachable from user code, and not cleaned up by garbage collection.
This is to highlight the potential impact of these state machines persisting past completion of the enumeration (or at least it’s containing scope).

![LargeLeaks](https://user-images.githubusercontent.com/90381711/142130527-a53e8c43-bf10-4a7b-8809-178f878efcba.png)

### Sample code

```

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class BigClass
    {
        public List<string> UsedMemory = Enumerable.Repeat("test", 10000).ToList();
    }
    class Program
    {
        static async Task Main(string[] args)
        {
            await RunNoLeak();
            Debugger.Break();
            await RunLeak();
            Debugger.Break();
        }

        static async Task RunNoLeak()
        {
            var aEnum = GetAsyncEnumerable();
            await foreach (var batch in aEnum)
                await NoThreadSwitch(batch);
        }

        static async Task RunLeak()
        {
            var aEnum = GetAsyncEnumerable();
            await foreach (var batch in aEnum)
                await ThreadSwitch(batch);
        }

        private static async Task NoThreadSwitch(BigClass arg)
        {
            await Task.CompletedTask;
        }

        private static async Task ThreadSwitch(BigClass arg)
        {
            await Task.Yield();
        }

        static async IAsyncEnumerable<BigClass> GetAsyncEnumerable()
        {
            for(int i = 0; i< 2; i++)
                yield return new BigClass();
            await Task.CompletedTask;
        }
    }
}

```

**Comment by eiriktsarpalis** [comment]
Have you tried looking at a Release build? The List seems to be getting collected there. This is likely expected, state machines are built slightly different depending on whether your app uses a Debug or Release build. cc @stephentoub

**Comment by stephentoub** [comment]
The object in question is held alive by a local on the thread stack.  If you change the repro to include:
```C#
await Task.Delay(1000);
GC.Collect();
```
before the Debugger.Break() in order to give the thread a chance to unwind and drop that local reference, the object should no longer show up.  The JIT is free to extend local lifetimes arbitrarily and does so in debug builds in particular.  The local in question is a reference to the async enumerable object itself, which has a field of type BigClass for storing the "current" item, and the C# compiler does not aggressively clear out such fields.

**Comment by nhunt-zf** [comment]
Thanks both. 

Eirik, I haven't run a heap dump on a release build of my real world code as yet. I will look at that once I have a reliable simple reproduction case.

Stephen, you are correct.  Waiting for the initial thread to unwind and a GC resolves the sample code issue. 

In my real world situation those remnant AsyncTaskMethodBuilders and their held reference trees are many minutes old and hundreds of GC's later.

I will go back and try and determine why the real world code is hanging on to those AsyncTaskMethodBuilder's. The core structure is the same as the sample, with a few extra complications (e.g. function calling via interfaces and Func objects rather than a fully compile time execution path).

You can close this in the meantime if necessary.

Thanks for your time.

**Comment by nhunt-zf** [comment]
For anyone interested. @stephentoub @eiriktsarpalis 

Possibly a duplicate of this issue:
https://github.com/dotnet/roslyn/issues/39321


Further testing reveals this is an issue when debugging .NET 5 but not 6 under VS2022.
Tested in Windows Visual Studio 2022 (also observed in VS 2019).
It only manifests when the Debugger is attached.

The following code has this output:
When debugger is attached:
a
b

And a heap check shows that the MarkerClass is left on the heap.

When debugger is not attached:
a
Finalised
b


```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace ConsoleApp2
{
    class MarkerClass
    {
        public byte[] UsedMemory = new byte[30000000];

        ~MarkerClass()
        { Console.WriteLine("Finalised"); }
    }

    
    class Program
    {
        static async Task Main(string[] args)
        {
            //for(int i = 0; i < 10; ++i)
            await Test();

            Console.WriteLine("a");

            await Task.Delay(2000);
            GC.Collect();
            GC.WaitForPendingFinalizers();

            Console.WriteLine("b");

            await Task.Delay(2000);
            Debugger.Break();
        }

        static async Task Test()
        {
            await foreach (var batch in GetBigObjects())
                await Task.Yield(); //asynchronous task completion (thread switch) necessary to repro
        }

        static async IAsyncEnumerable<MarkerClass> GetBigObjects()
        {
            await Task.Yield(); //asynchronous task completion (thread switch) necessary to repro
            yield return new MarkerClass();
        }
    }
}

```

Notes: The asynchronous task completion inside the enumerator is critical. 
When the enumerator returns multiple items, only the final one is left on the heap.
Un-commenting the loop over Test() results in 10 MarkerClass objects on the heap at the Break.

Not sure if my chosen .NET 5 runtime has the linked fix.

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
