### ISSUE TITLE
[API Proposal]: EnumConverter support for numeric/string in but always numeric out

### ISSUE THREAD

**Issue by benmccallum** [dotnet/runtime#61726]
### Background and motivation

Right now with EnumConverterOptions it's easy enough to say "allow strings" and have `"0"` or `"MemberName"` be deserialized, but by opting in to that setting it also affects all the serialization and everything is serialized as the member name string representation.

i.e. Allow strings is checked first in serialization method and outputs string before falling back to numeric.
https://github.com/dotnet/runtime/blob/10e107debae28de4bd1e710cfe448be3c293e841/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L154-L158

In our transition from Newtonsoft.Json, we found a couple of places where our clients were passing in a string, in one case even the numeric representation as a string (straight from a radio button value) so we want to accept that still, but we always want to serialize and send out the numeric representation as we were before.

Right now I need to copy-paste-modify the standard factory and converter to achieve this, but I'd love it if this was support natively via some form of options. 

### API Proposal

I imagine this would take shape in some modification to `System.Text.Json.Serialization.Converters.EnumConverterOptions`, but exactly what I'm not sure.

### API Usage

Replace the standard converter with a custom one as usual.

### Risks

Can't think of any. Perf would be same as current string in support.

**Comment by benmccallum** [comment]
Tagging owners as I wasn't specific enough for the bot to pull the area out, sorry.
@eiriktsarpalis @layomia @krwq @steveharter

**Comment by eiriktsarpalis** [comment]
Have you considered using [JsonStringEnumConverter](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter)? Note that the converter doesn't support reading quoted numeric values, this is already tracked #58247. At this point you'd need a custom converter to cover your use case I'm afraid.

**Comment by benmccallum** [comment]
Hi @eiriktsarpalis , I looked at `JsonStringEnumConverter` but I think it's just a factory which instantiates the core enum converter and passes the flags to support string:
https://github.com/dotnet/runtime/blob/d9afc1ecd6f22d836e1d7665847917aa09f580e9/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonStringEnumConverter.cs#L39-L45

The bug you mentioned would be a blocker for us, but I believe even if that's solved the result of `JsonStringEnumConverter` opting in to string conversion would still mean it'd force serialization out as the string repesentation (member name) as that flag is checked first.
https://github.com/dotnet/runtime/blob/10e107debae28de4bd1e710cfe448be3c293e841/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L154-L158

**Workaround**
I've solved my issue for now with a custom converter and factory based on the standard one, just working around some `internal`s and always writing out the numeric value. [Here's a gist](https://gist.github.com/benmccallum/84ce901122133335ec195e9a62da03b4) if anyone has the same need.

I guess I'll leave it in your court as to whether there's need for what I'm asking as an option flag. I think it'd be useful, but sure you've all got more important things to get on with :)

**Comment by eiriktsarpalis** [comment]
In that case, I'm going to close this in favor of #58247.

**Comment by benmccallum** [comment]
To be clear, #58247 isn't a fix for this. My custom converter is the only way.

**Comment by eiriktsarpalis** [comment]
IIRC the primary blocker even if #58247 were fixed is that you'd need to serialize as numbers. Yeah, there are all sorts of permutations wrt serialization vs deserialization behavior that the default converter won't be supporting. Recommend using a custom converter to solve your use case.
