### ISSUE TITLE
String.Format(formatProvider, "{0:N}", value) regression

### ISSUE THREAD

**Issue by BjornEngelen** [dotnet/runtime#61733]
Running the code:

```
var formatProvider = CultureInfo.GetCultureInfo("nl-BE");
Console.WriteLine(String.Format(formatProvider, "{0:N}", 12.3456789m));
Console.WriteLine(String.Format(formatProvider, "{0:N}", 12345.6789m));
```

Will output for .NET Core 2.0 or 3.1 LTS:
12,35
12.345,68

Will output for .NET 5.0 or 6.0:
12,346
12.345,679

Is this intentional?

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/issues/44587 (TLDR: in 5.0 .NET switched to ICU on Windows)

**Comment by tarekgh** [comment]
@BjornEngelen we have switched to use Unicode code standard CLDR data through the ICU library. We did that for .NET 5.0 and above. In general, globalization data is not stable and can change at any time. If you want to always have the old behavior (which format the number using 2 decimal digits, please use `N2` instead.
I am closing this issue but feel free to send any follow-up questions and we'll be happy to help with. Thanks for your report.

Thanks @EgorBo for adding the link for other issue which has more discussions about that.
