### ISSUE TITLE
[API Proposal]: Add overloads to `Console.Write` that also take a `ConsoleColor` parameter

### ISSUE THREAD

**Issue by FilipToth** [dotnet/runtime#61731]
### Background and motivation

This API proposal should just make it easier to write things of different colors to the console. Right now, we have to call three methods to do so. This is how we would do that now:
```C#
Console.ForegroundColor = ConsoleColor.Blue;
Console.Write("Hello!");
Console.ResetColor();
```
This is what I propose:
```C#
Console.Write(ConsoleColor.Blue, "Hello!");
```
This isn't anything critical, it's just some sugar to make writing code a little bit easier.

### API Proposal

```C#
namespace System
{
    public static class Console
    {
        public void Write(ConsoleColor color, String value);
    }
}
```
I would suggest having an overload for `Write` and `WriteLine`.

### API Usage

```c#
System.Console.WriteLine(ConsoleColor.Red, "Red text!");
```

### Risks

I do not see any risks associated with this.

**Comment by adamsitnik** [comment]
Hi @FilipToth 

Thank you for your proposal. I am going to include this in https://github.com/dotnet/runtime/issues/52374 which we may include in .NET 7 if the stars align.

**Comment by FilipToth** [comment]
Ok, Great that would be awesome. Thank you.

**Comment by stephentoub** [comment]
This is also a dup of https://github.com/dotnet/runtime/issues/39746.

**Comment by adamsitnik** [comment]
> This is also a dup of #39746.

I've not noticed that. In such a case I am going to close this issue.

@FilipToth please follow #39746 and #52374 for updates. Thank you!
