### ISSUE TITLE
.NET6 issue with Encoding.UTF8.GetString vs .NET5, .NET Core 3.1

### ISSUE THREAD

**Issue by jchristn** [dotnet/runtime#61744]
### Description

```Encoding.UTF8.GetString``` appears to behave differently in .NET6 compared to .NET5 and .NET Core 3.1.  I noticed this while working with some encryption methods.  

### Reproduction Steps

Please refer to this repository on Github: [link](https://github.com/jchristn/EncryptionBugDemo).  It is targeted to .NET Core 3.1, .NET 461, .NET 5, and .NET 6.

The value shown in the console output for ```Clear (UTF8)``` is different for .NET 6 than it is for the other frameworks.  For whatever reason, the full output is not rendering in the repository README.  

Expected (taken from .NET 5 output)
```
Clear (UTF8)    : {"GUID":"cce6eb38-0442-4b96-8791-06453e82db1e","MerchantGUID":"89aa9d75-c78c-435d-a1ea-cce17770712b","Brand":"Visa","AccountNumber":"4123123412341234","Last4":"1234","ExpirationMonth":12,"ExpirationYear":2024,"NameOnCard":"JoelChristner","CVV":"475","CreatedUtc":"2021-11-17T17:28:26.9781146Z"}
```

Actual (from .NET 6 output - the tail of the data appears to be truncated)
```
Clear (UTF8)    : {"GUID":"cce6eb38-0442-4b96-8791-06453e82db1e","MerchantGUID":"89aa9d75-c78c-435d-a1ea-cce17770712b","Brand":"Visa","AccountNumber":"4123123412341234","Last4":"1234","ExpirationMonth":12,"ExpirationYear":2024,"NameOnCard":"JoelChristner","CVV":"475","CreatedUtc":"2021-11-17T17:28:26.9781
```

### Expected behavior

It is expected that the output of ```Encoding.UTF8.GetString``` would be consistent.  

### Actual behavior

The result of ```Encoding.UTF8.GetString``` is not consistent across frameworks.

### Regression?

Yes, this works in .NET Core 3.1, .NET 461, and .NET 5.0.  

### Configuration

Tested on .NET Core 3.1, .NET 461, .NET 5.0 (working); failed on .NET 6.0.  All tests performed on Windows 10 x64.  

### Other information

Please refer to the Github repository ([link](https://github.com/jchristn/EncryptionBugDemo)) which is targeted to the aforementioned frameworks.

**Comment by stephentoub** [comment]
Are you sure the issue is to do with Encoding.UTF8.GetString?  The byte[] you're giving to GetString... where is that coming from?  Are you by chance calling stream.Read and assuming that it gave back everything you asked for?

**Comment by jchristn** [comment]
Hi @stephentoub I just realized my code didn't commit to the linked repo, one sec.

**Comment by stephentoub** [comment]
This line is almost certainly the issue:
https://github.com/jchristn/EncryptionBugDemo/blob/480bab933bccad49a2e4e1056bbf783913bc0032/EncryptionBugDemo/Program.cs#L73
There's no guarantee `cs.Read` returns `clear.Length` bytes.  Try changing that line from:
```C#
int decryptedCount = cs.Read(clear, 0, clear.Length);
```
to instead be:
```C#
int decryptedCount = 0;
while (decryptedCount < clear.Length)
{
    int n = cs.Read(clear, decryptedCount, clear.Length - decryptedCount);
    if (n == 0) break;
    decryptedCount += n;
}
```

**Comment by jchristn** [comment]
Hi @stephentoub the code is now present [here](https://github.com/jchristn/EncryptionBugDemo).

In all four cases (.NET Core 3.1, .NET 461, .NET 5, .NET 6) the byte data is coming back from the ```SHA1Encrypt``` and ```SHA1Decrypt``` static methods.

The data being passed to the ```SHA1Encrypt``` method is consistent.

The data returned by ```SHA1Decrypt``` is different amongst the frameworks (.NET6 returns a different value).

The is evidenced by the difference in the result from ```Convert.ToBase64String``` and ```Encoding.UTF8.GetString```.

I notice there are warnings in .NET6 about using RijndaelManaged (obsolete), but the expectation is that they would work as they did previously.  
```
Warning	SYSLIB0022	'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.'
```

**Comment by jchristn** [comment]
Just tested your fix and it works great.  Thanks for that.  Any reason why the behavior would be different from one framework to another?  I'm certain that such changes were communicated, and it's a case of me not seeing it, but I'm surprised something like this would happen.

**Comment by stephentoub** [comment]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by jchristn** [comment]
WOW.  Pretty big change.  Makes sense, I shouldn't have assumed I'd be getting back _n_ bytes...  Thanks and sorry to waste your time.

**Comment by stephentoub** [comment]
No worries; glad you're unblocked.
