### ISSUE TITLE
"Failed to create CoreCLR, HRESULT: 0x80004005" crash when starting PowerShell 7.2 on Windows 11

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#61740]
### Description

We got a report from @mazhar10 that PowerShell 7.2.0 crashes at startup on Windows 11 Insider Preview Build 22489 with the following error:
```
Failed to create CoreCLR, HRESULT: 0x80004005

[process exited with code 2147516553 (0x80008089)]
```

We suspected that this might be caused by CoreCLR failing to create the diagnostics pipes in the temp folder at initialization, but the OP confirmed to have write permission to the temp folder, and also disabling CoreCLR diagnostics by setting `set COMPlus_EnableDiagnostics=0` doesn't help.

The OP collected the CoreCLR startup traces, which is attached: [host.txt](https://github.com/dotnet/runtime/files/7556579/host.txt)

The trace doesn't show much about what went wrong except for a sudden failure at the end:
```
CoreCLR path = 'C:\Program Files\PowerShell\7\coreclr.dll', CoreCLR dir = 'C:\Program Files\PowerShell\7\'
Loaded library from C:\Program Files\PowerShell\7\coreclr.dll
Failed to create CoreCLR, HRESULT: 0x80004005
```

### Reproduction Steps

Quoted from the original issue in PowerShell repo:

> Install PowerShell 7.20 using the MSI package on Windows 11.
Try to start PowerShell 7.20 either by executing pwsh or by using Windows Terminal.

### Expected behavior

PowerShell 7.2 successfully starts

### Actual behavior

Crash with the following error:

```
Failed to create CoreCLR, HRESULT: 0x80004005

[process exited with code 2147516553 (0x80008089)]
```

### Regression?

This is the only crash report we have received so far on Windows 11.
The OP is using a Insider Preview Build, not sure if this could be a cause.

### Known Workarounds

No workaround for the OP

**Comment by devgossips** [comment]
Is there any fix for this ?

**Comment by mazhar10** [comment]
PowerShell 7.2.1, which was just released, does not exhibit this problem.

**Comment by AaronRobinsonMSFT** [comment]
Closing this as the OP is unblocked in PowerShell 7.2.1.
