### ISSUE TITLE
[wasm] Malformed `testResults.xml` causing CI test runs to fail

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#61749]
Seen on https://github.com/dotnet/runtime/pull/59479, [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1473634&view=logs&jobId=2c1bc6b5-3ed2-590f-6f2c-e4b87c1ec8e3&j=2c1bc6b5-3ed2-590f-6f2c-e4b87c1ec8e3&t=5e7d0d40-95c6-57ae-6f30-bab9f6898612), [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-305953aa61524883b7/System.Xml.XPath.XmlDocument.Tests/1/console.3e9eee3a.log?sv=2019-07-07&se=2021-12-07T18%3A11%3A33Z&sr=c&sp=rl&sig=Xhh53WBG%2BLzaLPYZbHEmE6qMb5s49bIE5T1K1OkDaAY%3D)

Tests pass:
```
[18:29:38] info: Total: 1485, Errors: 0, Failed: 0, Skipped: 0, Time: 5.652435s
[18:29:38] info: 
[18:29:38] info: Flushed stdout!
[18:29:38] info: 1 Exit called with 0 when isXUnitDoneCheck=true  at set_exit_code (/main.js:240:24) at Object.init (/main.js:204:17).
[18:29:38] info: WASM EXIT 0
```

but then the log parsing fails:
```
Traceback (most recent call last):
  File "/datadisks/disk1/work/99FB08BE/p/reporter/run.py", line 68, in <module>
    main()
  File "/datadisks/disk1/work/99FB08BE/p/reporter/run.py", line 65, in main
    reporter.report_results(all_results)
  File "/etc/helix/scripts/helix/test_reporting/packing_test_reporter.py", line 27, in report_results
    results = [x for x in results if x]
  File "/etc/helix/scripts/helix/test_reporting/packing_test_reporter.py", line 27, in <listcomp>
    results = [x for x in results if x]
  File "/datadisks/disk1/work/99FB08BE/p/reporter/test_results_reader/__init__.py", line 99, in read_results
    for result in file_results:
  File "/datadisks/disk1/work/99FB08BE/p/reporter/test_results_reader/__init__.py", line 98, in <genexpr>
    file_results = (add_logs(tr, log_list) for tr in f.read_results(file_path))
  File "/datadisks/disk1/work/99FB08BE/p/reporter/formats/xunit.py", line 47, in read_results
    for (_, element) in xml.etree.ElementTree.iterparse(path, events=['end']):
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1221, in iterator
    yield from pullparser.read_events()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1296, in read_events
    raise event
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1268, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1101, column 6
```

Lines 1100,1101 from `testResults.xml`:
```xml
      <test name="XPathTests.FunctionalTests.Expressions.NodeSetsTests.NodeSetsTest181" type="XPathTests.FunctionalTests.Expressions.NodeSetsTests" method="NodeSetsTest181" time="0.000645" result="Pass" />  <test name="XPathTests.FunctionalTests.Expressions.NodeSetsTests.NodeSetsTest183" type="XPathTests.FunctionalTests.E
      <test name="XPathTests.FunctionalTests.Expressions.NodeSetsTests.NodeSetsTest185" type="XPathTests.FunctionalTests.Expressions.NodeSetsTests" method="NodeSetsTest185" time="0.00062" result="Pass" />
```

The top line there (1100) has an incomplete element:
` <test name="XPathTests.FunctionalTests.Expressions.NodeSetsTests.NodeSetsTest183" type="XPathTests.FunctionalTests.E` at the end.

cc @pavelsavara

**Comment by pavelsavara** [comment]
@radical 
Are you saying that the xml is damaged in the middle of line ? If so, that's very interesting.

**Comment by radical** [comment]
Yep, you can see the xml here - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59479-merge-305953aa61524883b7/System.Xml.XPath.XmlDocument.Tests/1/xharness-output/testResults.xml?sv=2019-07-07&

**Comment by pavelsavara** [comment]
See how emscripten implaments [putChar](https://github.com/emscripten-core/emscripten/blob/4a9d5ab94f66b629b99c1104663bedbc80f799c1/src/library_tty.js#L151) on stdout. 
Could it be that something writes to it in between our [resultsXml.Save](https://github.com/dotnet/xharness/blob/42da0d206c22393c081abc4b6a48a181e17bb372/src/Microsoft.DotNet.XHarness.TestRunners.Xunit/ThreadlessXunitTestRunner.cs#L72) ?

**Comment by pavelsavara** [comment]
I mean into the `tty.output` char buffer there.

**Comment by pavelsavara** [comment]
Or it could be buffering of [WasmBrowserTestRunner](https://github.com/dotnet/xharness/blob/42da0d206c22393c081abc4b6a48a181e17bb372/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/Browser/WasmBrowserTestRunner.cs#L144)
Or it could be browser console buffers or webSocket buffers on both sides.

**Comment by pavelsavara** [comment]
Possibly related ? https://github.com/xunit/xunit/issues/2090

**Comment by pavelsavara** [comment]
We noticed that `WasmConsoleStream.Flush` is probably NOOP. 
https://github.com/dotnet/runtime/blob/f1bf5eee390fa118441cae14a157773f1e2d751d/src/libraries/System.Console/src/System/ConsolePal.WebAssembly.cs#L71

See base `ConsoleStream`
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Console/src/System/IO/ConsoleStream.cs#L65

**Comment by pavelsavara** [comment]
> We noticed that `WasmConsoleStream.Flush` is probably NOOP.

That's the case for all platforms. So there is no point in calling it.

**Comment by eerhardt** [comment]
Happened again in https://github.com/dotnet/runtime/pull/57433. 

https://helix.dot.net/api/2019-06-17/jobs/8af8ecaf-88ce-43d9-b770-3dc95fe1fddc/workitems/System.Xml.Linq.Events.Tests/console

**Comment by radical** [comment]
[Another](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-80d41790d5334e0f98/System.Text.Json.SourceGeneration.Roslyn3.11.Tests/1/console.86b7109c.log?sv=2019-07-07&se=2021-12-09T21%3A02%3A34Z&sr=c&sp=rl&sig=pjkgJWeYkhmi4Bd89FHqCIoRAzoKtcIGxjH5uBq37XU%3D) one, but failing because:

```
2 Exit called with 0 when isXUnitDoneCheck=true  at set_exit_code (/main.js:240:24) at Object.init (/main.js:204:17).
<?xml version="1.0" encoding="utf-8"?>
<assemblies>
```

.. that debug message is showing up in the xml.

And [another](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-80d41790d5334e0f98/System.Xml.Xsl.XslCompiledTransformApi.Tests/1/console.24cc1ffe.log?sv=2019-07-07&) with:
```
<?xml version="1.0" encoding="utf-8"?>
2 Exit called with 0 when isXUnitDoneCheck=true  at set_exit_code (/main.js:240:24) at Object.init (/main.js:204:17).
<assemblies>
```

.. again with the debug message showing up in the second line.

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1478321&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4)

**Comment by pavelsavara** [comment]
Both messages thru WS and thru chrome devtools protocol are written into same `WasmTestMessagesProcessor`.
Those sources are running in parallel.
