### ISSUE TITLE
Specific .NET 6.0 Desktop Application won't launch from folder other than Install folder

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/runtime#61769]
### Description

I'm unable to launch a .NET 6.0 WPF desktop application from a folder other than the folder that contains the binary installation folder. Launching the EXE from a different folder with a path only does not work - the EXE silent fails and exits without running the application. 

![dotnet6Exewontlaunchwithpath2](https://user-images.githubusercontent.com/1374013/142373708-15f2c30c-286f-4c97-93f8-fbecd0255897.gif)

I added some logging code as the first line of the WPF application in `App.xaml.cs` that logs output to the log file. In the first startup in the installation folder you can see the log hitting. In the second - failed - startup the log never gets hit meaning the application never gets to the first line of user code  (ie. it's not my app that's failing). There is no error message of any sort - the application just silently fails.

The only way the application will run is if the application is launched from the installation/compilation folder. This means it has to be either launched out of the start folder, or if using a shortcut the shortcut **has to** provide a launch folder. 

In the capture above the the launch from the registered `.websurge` shell extension which runs a shell command to the `c:\Program Files\` installation folder does not work either because it can't set the start folder.

### Reproduction Steps

So I tried this with another WPF application created from scratch - and it behaves as expected. This problem appears to be specific to this particular application. However, I don't see anything that is wrong or would cause the application to fail to load. There are no external dependencies that could be missing.

There are however some 'refs' that include native components - specifically a `WebView2Loader.dll`. 

![image](https://user-images.githubusercontent.com/1374013/142382159-a1212725-9a91-4a0e-a11e-7eed607c1d60.png)

If necessary I can provide access to the repository to compile and run this application, but it is  a private repo.

### Expected behavior

Application should launch out of the startup folder without having to be launched from that folder.

If it fails as it appears to be - there should be some sort of message that provides more information on why it is failing.

### Actual behavior

App fails silently.

### Configuration

This is a .NET 6.0 WPF Desktop application.  Here's the full project file.

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>2.0.0.16</Version>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>

		<AssemblyName>WebSurge</AssemblyName>
		<Product>West Wind WebSurge</Product>
		<Authors>Rick Strahl, West Wind Technologies</Authors>
		<Company>West Wind Technologies</Company>
		<Copyright>West Wind Technologies, 2016-2021</Copyright>
		<Description>West Wind WebSurge is a Url Testing and Web Load Testing tool.</Description>
		<ApplicationIcon>websurge.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<NoWarn>1701;1702;1573;1572;1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Using Remove="System.Windows.Forms" />
		<Using Remove="System.Drawing" />
	</ItemGroup>

	<ItemGroup>
		<!--<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />-->
		<PackageReference Include="MahApps.Metro" Version="2.4.9" />
		<PackageReference Include="MahApps.Metro.IconPacks.FontAwesome" Version="4.11.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1020.30" />
		<PackageReference Include="Mono.Cecil" Version="0.11.4" />

		<ProjectReference Include="..\..\Libraries\Westwind.TypeImporter\Westwind.TypeImporter.csproj" />
		<ProjectReference Include="..\WebSurge.Core\WebSurge.Core.csproj" />
	</ItemGroup>


	<ItemGroup>
		<Resource Include="assets/**/*.*" />
		<None Update="Html\**\*.*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="BinSupport\MicrosoftEdgeWebview2Setup.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<None Update="websurge.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="WebSurgeCli.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="WebSurgeCli.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<Folder Include="_Classes\Utilities\Converters\" />
	</ItemGroup>
</Project>
```

**Comment by vitek-karas** [comment]
UI apps don't produce errors on the command line (Windows actually doesn't capture the stdout or stderr of these). That said, you should be able to find something in the event log hopefully.

There are two possibilities, it's failing before the runtime itself is started (in the host), or after the runtime started during loading of the managed code (before the user code is executed).

If it's the first case, you should be able to capture the host logs:
```console
set COREHOST_TRACE=1
set COREHOST_TRACEFILE=host.txt
<repro the failure by running the app from some "Random" folder>
```

This should produce `host.txt` in the current directory. If you scroll to the very end of this file it should show the error if it's from the host.

If it's failing after the runtime started, you should be able to run this under a debugger and catch the exception that way.

**Comment by RickStrahl** [comment]
Yup i just found that out. In fact, I found the offender which is a file that was referenced in the startup folder without a fully qualified path and failed. The event log had the full stack trace that actually made finding this straight forward - once I actually remembered to look there.

For a desktop app that feels very unnatural. The silent failure too feels just wrong. I want to see it fail with even a hard stop over just silently failing. For a desktop app I'd expect a dialog. For a console app I'd expect to see some sort of console error message.

As it stands though this is resolved and... due to Operator Error on my part 😳

**Comment by vitek-karas** [comment]
I do agree that silently failing is not ideal. Just curious, did the failure happen in managed code? (as fixing the error experience would look very different if it did or didn't)

**Comment by batzen** [comment]
If you are considering visual feedback on failures please keep automation in mind. We had to jump through a lot of hoops to prevent any system provided dialogs from appearing during automated tests as those dialogs tend to be blocking and thus block automation from proceeding. An environment variable to suppress potential dialogs would be nice, if you plan to add any dialogs.

**Comment by vitek-karas** [comment]
@batzen - absolutely agree. The host will popup dialogs on some error conditions, but it does have an env. variable to disable this behavior: `DOTNET_DISABLE_GUI_ERRORS=1` should disable that. If we were to add more (as per above) I'm pretty sure we would put it behind the same variable.
