### ISSUE TITLE
Spurious Newlines Added to Log Output

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#61763]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Spurious-Newlines-Added-to-Log-Output/1570791)._

---
I have used the same logging code for literally years. After it has done my application-specific stuff, I end up with a string that gets written out using:

`Console.WriteLine( logLine );`

Suddenly, this has started adding extra newlines to **some** lines but not all. This makes the logs a lot harder to read.

Note that if I check for extra newlines being created by my code using the following...

`if( message. Contains( Environment.NewLine ) )`

... this never triggers, so the extra newlines must be being added in the Xamarin implementation of `Console.Writeline()`.

---
#### Feedback Bot on 11/3/2021, 02:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by steveisok** [comment]
It's not clear if this is net6 or legacy xamarin.  Would it be possible to add a project to try and reproduce?
