### ISSUE TITLE
The mscordbi.dll for .NET 5.0.12 is missing from symbol servers

### ISSUE THREAD

**Issue by onyxmaster** [dotnet/runtime#61775]
### Description

Hi!

It appears that when releasing .NET 5.0.12 the mscordbi.dll slipped through the cracks and now Visual Studio can't do post-mortem debugging for minidumps for CLR version 5.0.1221.52207.
![image](https://user-images.githubusercontent.com/588253/142424938-d1903198-a9f8-4a89-a510-a78680c1afe5.png)
I did some testing, and the mscordbi.dll for 5.0.11 downloads just fine (emptied symbol cache and tried to debug a minidump from 5.0.11), so it's not an "your computer can't download files from the internet" issue.

Thanks for taking a look.

### Reproduction Steps

Try debugging a minidump from Linux running .NET 5.0.12 in Visual Studio -- open it and then try to start Managed Debugging.

### Expected behavior

The debugging works as usual.

### Actual behavior

The VS hangs with the message about mscordbi.dll not available (see Description above).

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by hoyosjs** [comment]
Yes, I have a mail thread going with the release team. I will push them again as there's been no response in a day.

**Comment by hoyosjs** [comment]
The symbols should be available now.
