### ISSUE TITLE
System.Text.Json source generator ignores properties from base records defined in separate assemblies

### ISSUE THREAD

**Issue by Memoryfox** [dotnet/runtime#61772]
### Description

Properties of a base record defined in a referenced NuGet package are ignored when creating a  JsonSerializerContext.
When working with classes it is working as expected.

### Reproduction Steps

Create a project with a record:
```csharp
public record FooData
{
	public virtual int FooValue { get; set; }
}
```
Create a NuGet package.

Create a second project and reference the NuGet package:
```csharp
public record BarData : Foo.FooData
{
	public int BarValue { get; set; }
}

```
Create a `JsonSerializerContext`:
```csharp
[JsonSerializable(typeof(BarData))]
public partial class BarJsonSerializerContext : JsonSerializerContext { }

```

### Expected behavior

The generated context (`BarJsonSerializerContext`) should handle `FooValue` and `BarValue`.

### Actual behavior

The generated context (`BarJsonSerializerContext`) handles only `BarValue`.

### Known Workarounds

Reference the project with the base types directly if possible instead of using a NuGet package.

### Configuration

.net 6.0.100

**Comment by eiriktsarpalis** [comment]
I can reproduce, the issue specifically impacts records inherited across projects. It doesn't seem to impact regular classes. I can reproduce using p2p references, so this is not exclusive to NuGet dependencies. Minimal reproduction:

## Class Library

```C#
public record LibRecord
{
	public int LibValue { get; set; }
}
```

## Console App

```C#
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

var value = new AppRecord { LibValue = 1, AppValue = 2 };
string json = JsonSerializer.Serialize(value, MyJsonSerializerContext.Default.AppRecord);
Console.WriteLine(json);

public record AppRecord : LibRecord
{
	public int AppValue { get; set; }
}

[JsonSerializable(typeof(AppRecord))]
public partial class MyJsonSerializerContext : JsonSerializerContext { }
```
@layomia @ericstj seems like something to consider for servicing?

**Comment by layomia** [comment]
Dupe - same underlying issue as https://github.com/dotnet/runtime/issues/62374.
