### ISSUE TITLE
[Android](CryptoNative_HmacUpdate): Parameter 'data' must be a valid pointer'

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#61783]
System.Security.Cryptography.Tests failed on Android due to a crash with the following message:
```
Abort message: '/__w/1/s/src/libraries/Native/Unix/System.Security.Cryptography.Native.Android/pal_hmac.c:88 (CryptoNative_HmacUpdate): Parameter 'data' must be a valid pointer'
```
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61670-merge-3d266bcf337a4ffe92/System.Security.Cryptography.Tests/1/adb-logcat-net.dot.System.Security.Cryptography.Tests-net.dot.MonoRunner.log?sv=2019-07-07&se=2021-12-08T15%3A07%3A31Z&sr=c&sp=rl&sig=McQh8mbdRtBm%2FUFGKVsx7BoxJQ6bKhUkvsFldClN2iI%3D

cc @steveisok  @akoeplinger

**Comment by MaximLipnin** [comment]
It might be related to https://github.com/dotnet/runtime/pull/61742 @AaronRobinsonMSFT

**Comment by marek-safar** [comment]
I'm curious to know we got into this state

**Comment by AaronRobinsonMSFT** [comment]
I'll take a look.

**Comment by marek-safar** [comment]
@steveisok could we ensure if there is CI hole that it's closed?

**Comment by AaronRobinsonMSFT** [comment]
I _think_ this is a slight semantic change that is handled properly but validates earlier than needed on Android.

https://github.com/dotnet/runtime/blob/6ff57f1935d1cb3396674bec26268a301e5c0628/src/libraries/Native/Unix/System.Security.Cryptography.Native/pal_evp.c#L96-L101

My plan is to move the `NULL` check after the case where length is `0`.

https://github.com/dotnet/runtime/blob/6ff57f1935d1cb3396674bec26268a301e5c0628/src/libraries/Native/Unix/System.Security.Cryptography.Native.Android/pal_evp.c#L51-L56

**Comment by elinor-fung** [comment]
The signature of `EvpDigentOneShot` is blittable, so the semantic change should not be in how we are handling arguments for that function though.
https://github.com/dotnet/runtime/blob/f6e2377da05888fda0fda18ee0959683e830d8d9/src/libraries/Common/src/Interop/Android/System.Security.Cryptography.Native.Android/Interop.Evp.cs#L34-L35

Something must have caused inputs to change so that it is being passed null.

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Agreed. I confirmed we are simply creating a `DllImport` anyways so I'm unclear how we got here. I am putting up a commit reverting only that change to confirm in the CI.
