### ISSUE TITLE
System.Text.Json source generation producing invalid code on generic JsonSerializable types

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#61782]
### Description

Passing a generic type definition in a `JsonSerializableAttribute` results in invalid C# code being generated, namely type parameters are erroneously treated as named type definitions.

### Reproduction Steps

```C#
[JsonSerializable(typeof(HashSet<>))]
internal partial class MyJsonSerializerContext : JsonSerializerContext { }
```

### Expected behavior

Should fail with a relevant diagnostic message.

### Actual behavior

Produces invalid C# code that fails to type check:
```csharp
    internal partial class MyJsonSerializerContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.HashSet<global::T>>? _HashSetT;
    }
```

```
error CS0400: The type or namespace name 'T' could not be found in the global namespace
```

### Other information

We could either emit an error diagnostic when users specify generic types _or_ we could try supporting them. Note however that generic types would require generating factories instead of properties that current model is using, for example:

```C#
JsonSerializer.Serialize(hashset, MyJsonSerializerContext.Default.CreateHashSetT());
```

**Comment by eiriktsarpalis** [comment]
Moving to the .NET 8 milestone.

**Comment by krwq** [comment]
we should improve error message here for 8.0

**Comment by layomia** [comment]
Up for grabs. We should check if an input type has open generics and issue a diagnostic error if so. Somewhere in this [method](https://github.com/dotnet/runtime/blob/3f51e1449f78041bd4f213602f2bbfa4af321dde/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L693) would be a good place for such logic, and would involve adding an entry to the [`_typeLevelDiagnostics` cache](https://github.com/dotnet/runtime/blob/3f51e1449f78041bd4f213602f2bbfa4af321dde/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L129).

**Comment by krwq** [comment]
[Triage] We need to improve the error message and possibly consider making that work
