### ISSUE TITLE
.Net 6 `System.Random` returns only 0 after a while when initialised with a seed

### ISSUE THREAD

**Issue by mdelz** [dotnet/runtime#61789]
When I initialise a random number generator with a seed it returns after a while only zero.

I looked through the code and saw that all values in `_seedArray` of `System.Random.CompatPrng` are set to 0 after a while.

I think the `<` in this line should be a `<=`
https://github.com/dotnet/runtime/blob/f7633f498a8be34bee739b240a0aa9ae6a660cd9/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L283

**Comment by stephentoub** [comment]
Can you share a repro?  I've had this running for several minutes:
```C#
var r = new Random(42);
while (true)
{
    int i = r.Next();
    int j = r.Next();
    int k = r.Next();
    int l = r.Next();
    if (i == 0 && j == 0 && k == 0 && l == 0)
    {
        Console.WriteLine("all zero");
    }
}
```
and it hasn't output anything.

Also, the cited line has always been that way, e.g.
https://referencesource.microsoft.com/#mscorlib/system/random.cs,111

Typically "starts returning 0s after a while" manifests when a single Random instance is erroneously used from multiple threads concurrently.
