### ISSUE TITLE
.NET to run in WASMEdge

### ISSUE THREAD

**Issue by VenkateshSrini** [dotnet/runtime#61791]
### Is your feature request related to a problem? Please describe.
At present blazor runs in browser and can the blazor components can be embedded in mobile apps. The feature request is that can Blazor run in environment like WasmEdge (https://github.com/WasmEdge/WasmEdge). If that is the case then if we can port Kestrel  also to Blazor runtime or much more a light weight version, then we could run API applications using WASMEdge. This will be much  more light weight than containers. There are usecases where the same is possible using Rust runtime. Please see the article 
https://www.infoq.com/articles/webassembly-dapr-wasmedge/?utm_source=email&utm_medium=Web-Development&utm_campaign=newsletter&utm_content=11162021. 
### Describe the solution you'd like
Blazor should be able to run in WASMEDGE. Then this can be used like desktop application and also light-weight runtime for hosting API.

**Comment by danroth27** [comment]
@lewing

**Comment by mdg215199** [comment]
Any update on this?

**Comment by lewing** [comment]
closing this in favor of wasi support tracking https://github.com/dotnet/runtime/issues/65895

**Comment by VenkateshSrini** [comment]
The issue is https://github.com/dotnet/runtime/issues/65895 is  also closed. So are we saying that even in .NET 8 there is no support for WASI

**Comment by lewing** [comment]
> The issue is #65895 is also closed. So are we saying that even in .NET 8 there is no support for WASI

#65895 is not closed, it is a tracking issue for the work we are doing and it points a list of PRs that have already landed in .NET 8. We don't have a fixed timetable on delivering full WASI support but it is an area of active development.
