### ISSUE TITLE
Make --resilient the default behavior for crossgen2

### ISSUE THREAD

**Issue by fadimounir** [dotnet/runtime#618]
Keep --resilient during feature work until we are close to shipping to catch bugs.

When fixing, enable test `JIT/Regression/JitBlue/GitHub_25027/GitHub_25027.ilproj` for crossgenning for test coverage (remove `<CrossGenTest>false</CrossGenTest>`)

**Comment by davidwrighton** [comment]
We seem to be working well enough without this. Closing as not needed.
