### ISSUE TITLE
String interpolation combining string format and brackets is interpreted incorrectly

### ISSUE THREAD

**Issue by Evollutje** [dotnet/runtime#61838]
### Description

Using string formatting followed by a closing bracket is misinterpretted in .net 6. 
See the reproduction steps for an easy example.
In the code editor you can also see the problem, the first pair of brackets is highlighted indicating this is part of the string, instead of being the closing bracket for the parameter.

### Reproduction Steps

```
public int Value { get; } = 3;
public override string ToString() => $"{{{this.Value:D3}}}"
```

### Expected behavior

When ToString() is called: {003}

### Actual behavior

When ToString() is called: {D3}}

### Regression?

This worked in .Net 5

### Known Workarounds

```
public int Value { get; } = 3;
public override string ToString() => $"{{{this.Value.ToString("D3")}}}"
```

### Configuration

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.0.0

.Net 6.0.100

**Comment by svick** [comment]
This is a duplicate of https://github.com/dotnet/roslyn/issues/57750.

**Comment by Evollutje** [comment]
> This is a duplicate of [dotnet/roslyn#57750](https://github.com/dotnet/roslyn/issues/57750).

Thanks, you are correct.
