### ISSUE TITLE
Rfc2898DeriveBytes(string, byte[]) does not throw ArgumentException when 'salt' is less than 8 bytes

### ISSUE THREAD

**Issue by Bysza** [dotnet/runtime#61833]
### Description

Rfc2898DeriveBytes(string, byte[]) constructor does not throw the "System.ArgumentException: 'Salt is not at least eight bytes. (Parameter 'salt')'" on Net6, when 'salt' parameter is byte[0].

The documentation states that the constructor throws ArgumentException when the specified salt size is smaller than 8 bytes or the iteration count is less than 1.

### Reproduction Steps

C#:
using Rfc2898DeriveBytes kdf = new("text", Array.Empty<byte>());

### Expected behavior

System.ArgumentException: 'Salt is not at least eight bytes. (Parameter 'salt')'

### Actual behavior

Execution continues without exception being thrown.

### Regression?

Works fine in Net5 and older frameworks including Net 4.7.x and up.

### Known Workarounds

None.

### Configuration

Net6 6.0.100
Windows 10 v 21H1 build 19043.1348

**Comment by stephentoub** [comment]
This is by design:
https://github.com/dotnet/runtime/issues/56908
https://github.com/dotnet/runtime/pull/57006

**Comment by Bysza** [comment]
Are docs misleading then?
