### ISSUE TITLE
FileStream does not lock file on mounted filesystem

### ISSUE THREAD

**Issue by SergeMatskov** [dotnet/runtime#61836]
### Description

I have found that on Linux on mounted filesystem file locking behavior was changed on .NET 6.0. To reproduce the issue it is enough to create a FileStream with FileAccess.ReadWrite:
```
using (FileStream fs = new FileStream("test1", FileMode.OpenOrCreate, FileAccess.ReadWrite))
{
    Console.WriteLine("Check for lock and press enter to continue");
    Console.ReadLine();
}
```

When I run the command `sudo lslocks | grep test1` when FileStream is created, I have found that there is no lock created when:
- Running .NET 6.0
- OS is Linux
- FileAccess is ReadWrite
- File is located on the mounted filesystem

Locating file `test1` on the local filesystem creates a lock. .NET Core 3.1 or .NET 5.0 creates a file lock even if the mounted filesystem is used.  And using FileAccess.Read instead of FileAccess.ReadWrite also creates a lock.

### Reproduction Steps

```
using (FileStream fs = new FileStream("test1", FileMode.OpenOrCreate, FileAccess.ReadWrite))
{
    Console.WriteLine("Check for lock and press enter to continue");
    Console.ReadLine();
}
```

### Expected behavior

The file lock should be created on the mounted filesystem.

### Actual behavior

The file lock is not created on the mounted filesystem.

### Regression?

Yes. The file lock is created on the mounted filesystem using .NET Core 3.1 and .NET 5.0.

### Configuration

.NET 6.0.100
Ubuntu 16.04.7 LTS with mounted Windows directory
x64

**Comment by adamsitnik** [comment]
Hello @SergeMatskov 

This change was introduced in https://github.com/dotnet/runtime/pull/55256 and we have done it on purpose.

To tell the long story short, CIFS, SMB, SMB2 and NFS treat "shared" lock as "reader" lock and hence prevent the owner of such lock from writing to the file. 

How does it affect your app?

**Comment by tmds** [comment]
Afaik the two things that may not work are:
- taking a shared lock on a write-only file;
- an exclusive lock on a read-only file

It depends on the server on how it handles those requests.

In this case, the file was opened with read permission. It should be fine to take a shared lock.

**Comment by tmds** [comment]
@adamsitnik let me know if you want me to look into this further. I can make some time to setup servers and try out some things.

**Comment by SergeMatskov** [comment]
Hi @adamsitnik, thank you for the comprehensive description. This issue does not affect our app, except for some unit tests, so I can create a workaround. I am just wondering why there is a difference between FileAccess.ReadWrite and FileAccess.Read. So please close this issue.

**Comment by adamsitnik** [comment]
> let me know if you want me to look into this further

@tmds have you seen https://github.com/dotnet/runtime/pull/55256#issue-938743848? If you think there is a way to improve our current solution I would be happy to hear more about it.

**Comment by adamsitnik** [comment]
> This issue does not affect our app, except for some unit tests, so I can create a workaround. I am just wondering why there is a difference between FileAccess.ReadWrite and FileAccess.Read.

FWIW here is the [implementation](https://github.com/dotnet/runtime/blob/e9036b04357e8454439a0e6cf22186a0cb19e616/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L371-L403) which may be the best answer to your question.

> So please close this issue.

@SergeMatskov thank you!
