### ISSUE TITLE
Regression in TimeZoneInfo for "Central Brazilian Standard Time" in .NET 6.0

### ISSUE THREAD

**Issue by jskeet** [dotnet/runtime#61842]
### Description

The time zone adjustment rules in .NET 6.0 appear be implemented differently (and brokenly) compared with all previous versions... possibly *just* for "Central Brazilian Standard Time".

The "end of daylight savings transition" in the first rule of the zone states that the change occurs at midnight on the first Thursday of January. This appear to be correctly implemented on previous versions of .NET - but in .NET 6.0 the transition actually occurs on January 1st, regardless of the day of week.

### Reproduction Steps

Run the following code:

```csharp
using System;

class Test
{
    static void Main()
    {
        var zone = TimeZoneInfo.FindSystemTimeZoneById("Central Brazilian Standard Time");
        
        var firstRule = zone.GetAdjustmentRules()[0];
        var endTransition = firstRule.DaylightTransitionEnd;
        Console.WriteLine($"Fixed date rule: {endTransition.IsFixedDateRule}");
        Console.WriteLine($"Day of week: {endTransition.DayOfWeek}");
        Console.WriteLine($"Month: {endTransition.Month}");
        Console.WriteLine($"TimeOfDay: {endTransition.TimeOfDay.TimeOfDay}");
        Console.WriteLine($"Week: {endTransition.Week}");

        Console.WriteLine();
        Console.WriteLine("Offsets at 15:00 UTC:");
        var start = new DateTime(1950, 12, 25, 15, 0, 0, DateTimeKind.Utc);
        for (int i = 0; i < 20; i++)
        {
            var current = start.AddDays(i);
            var offset = zone.GetUtcOffset(current);
            Console.WriteLine($"{current:yyyy-MM-dd} ({current:ddd}): {offset}");
        }
    }
}
```

### Expected behavior

Output on .NET 4.8, .NET Core 3.1, and .NET 5.0 - note how the change from -3 to -4 occurs on Thursday:

```text
Fixed date rule: False
Day of week: Thursday
Month: 1
TimeOfDay: 00:00:00
Week: 1

Offsets at 15:00 UTC:
1950-12-25 (Mon): -03:00:00
1950-12-26 (Tue): -03:00:00
1950-12-27 (Wed): -03:00:00
1950-12-28 (Thu): -03:00:00
1950-12-29 (Fri): -03:00:00
1950-12-30 (Sat): -03:00:00
1950-12-31 (Sun): -03:00:00
1951-01-01 (Mon): -03:00:00
1951-01-02 (Tue): -03:00:00
1951-01-03 (Wed): -03:00:00
1951-01-04 (Thu): -04:00:00
1951-01-05 (Fri): -04:00:00
1951-01-06 (Sat): -04:00:00
1951-01-07 (Sun): -04:00:00
1951-01-08 (Mon): -04:00:00
1951-01-09 (Tue): -04:00:00
1951-01-10 (Wed): -04:00:00
1951-01-11 (Thu): -04:00:00
1951-01-12 (Fri): -04:00:00
1951-01-13 (Sat): -04:00:00
```

### Actual behavior

Output on .NET 6.0 - note how the change from -3 to -4 occurs on Monday:

```text
Fixed date rule: False
Day of week: Thursday
Month: 1
TimeOfDay: 00:00:00
Week: 1

Offsets at 15:00 UTC:
1950-12-25 (Mon): -03:00:00
1950-12-26 (Tue): -03:00:00
1950-12-27 (Wed): -03:00:00
1950-12-28 (Thu): -03:00:00
1950-12-29 (Fri): -03:00:00
1950-12-30 (Sat): -03:00:00
1950-12-31 (Sun): -03:00:00
1951-01-01 (Mon): -04:00:00
1951-01-02 (Tue): -04:00:00
1951-01-03 (Wed): -04:00:00
1951-01-04 (Thu): -04:00:00
1951-01-05 (Fri): -04:00:00
1951-01-06 (Sat): -04:00:00
1951-01-07 (Sun): -04:00:00
1951-01-08 (Mon): -04:00:00
1951-01-09 (Tue): -04:00:00
1951-01-10 (Wed): -04:00:00
1951-01-11 (Thu): -04:00:00
1951-01-12 (Fri): -04:00:00
1951-01-13 (Sat): -04:00:00
```

### Regression?

Yes, all of .NET 4.8, .NET Core 3.1, .NET 5.0 do the right thing here. (Older versions too, I suspect.)

### Configuration

Windows 11, x64, .NET 6.0.

### Other information

I suspect the problem is related to Brazil having a start transition near the end of the year, and an end transition near the start of the year... *and* the end transition has both Day and Month as 1 and is at midnight.
For fixed date rule zones, an "end transition at about midnight on January 1st" is used to indicate a standard-time-only rule, but I don't believe that's the intention here.

Here's the code that I use to detect that condition in Noda Time - feel free to use any of my reverse-engineering of the meaning of BCL adjustment rules to reimplement them ;)
https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeZones/BclDateTimeZone.cs#L330

**Comment by tarekgh** [comment]
@jskeet thanks for your report. We shouldn't be changed how we read the adjustment rules on Windows we did for non-Windows platforms though. I'll look anyway to see from where we got this regression.

**Comment by filipnavara** [comment]
Note that there's an undocumented behavior that the transition time with `Day == 1 && Month == 1 && TimeOfDay < 1 second` are unset. This is used for transitions spanning multiple years, often on southern hemisphere, where daylight starts in one year (unset end) and ends in different year (unset start). Similarly, it can happen that both start and end transition is unset and `BaseUtcOffsetDelta` (now public in .NET 6 but existed earlier) exists (standard time is adjusted that year, eg. Moscow time zone).

**Comment by tarekgh** [comment]
I have investigated this issue, yes, we had the [change](https://github.com/dotnet/runtime/pull/43550) which caused seeing this difference. The change itself is not a problem and still a good change to keep. The change has just revealed a minor corner case issue which we are talking about here. But the real problem here is not how we interpret the zone data. The real issue is Windows doesn't provide good enough historical data for the time zones. Here is what I mean for this case:

The indicated issue is for the year 1951. Looking at the zone rule data, it shows the following adjustment rule

```
----------------------------------------------------------------------------------------------------------------------------
Central Brazilian Standard Time -04:00:00
----------------------------------------------------------------------------------------------------------------------------
DateStart                  : 1/1/0001 12:00:00 AM (Unspecified)
DateEnd                    : 12/31/2004 12:00:00 AM (Unspecified)
DaylightDelta              : 01:00:00
DaylightTransitionStart    : M:11, D:1, W:1, DoW:Tuesday, Time:1/1/0001 12:00:00 AM, FixedDate:False
DaylightTransitionEnd      : M:1, D:1, W:1, DoW:Thursday, Time:1/1/0001 12:00:00 AM, FixedDate:False
BaseUtcOffsetDelta         : 00:00:00
NoDaylightTransitions      : False
-----------------------------------------------------------------------------------------------------------------------------
```

when looking at the real IANA data for the same zone, I can see: 

```
TZ="America/Cuiaba"
-       -       -034420 LMT
1913-12-31      23:44:20        -04
1931-10-03      12      -03             1
1932-03-31      23      -04
1932-10-03      01      -03             1
1933-03-31      23      -04
1949-12-01      01      -03             1
1950-04-16      00      -04
1950-12-01      01      -03             1
1951-03-31      23      -04
1951-12-01      01      -03             1
1952-03-31      23      -04
1952-12-01      01      -03             1
```

The data means, for the year 1951, the year starts in the DST (-3 hours) till March 31st 11 PM. Then the DST will be on again starting Dec 1st 1:00 AM. Windows rule is not indicating that. And whatever we do interpreting this rule in Windows, we'll not report the transition accurately.  Even on .NET 5.0, when running the same provided sample code on Windows and on Linux (where we use IANA zone data) you can see differences. 

On Windows:

```
1951-01-04 (Thu): -04:00:00
1951-01-05 (Fri): -04:00:00
1951-01-06 (Sat): -04:00:00
1951-01-07 (Sun): -04:00:00
1951-01-08 (Mon): -04:00:00
1951-01-09 (Tue): -04:00:00
1951-01-10 (Wed): -04:00:00
1951-01-11 (Thu): -04:00:00
1951-01-12 (Fri): -04:00:00
1951-01-13 (Sat): -04:00:00
```

While on Linux, you can see a better result

```
1951-01-04 (Thu): -03:00:00
1951-01-05 (Fri): -03:00:00
1951-01-06 (Sat): -03:00:00
1951-01-07 (Sun): -03:00:00
1951-01-08 (Mon): -03:00:00
1951-01-09 (Tue): -03:00:00
1951-01-10 (Wed): -03:00:00
1951-01-11 (Thu): -03:00:00
1951-01-12 (Fri): -03:00:00
1951-01-13 (Sat): -03:00:00
```

I have investigated if this issue can happen with any other time zone, and I couldn't find any other zone that can run into this issue. Only potential future rule of year 2029 for Fiji zone but I expect Windows will update this one in near time to report better transition for Fiji.

I consider this a low priority issue as it affects one zone with the historical dates. I'll try to talk to Windows team about the data provided for this zone. Also, we should try to start getting the zone data on Windows from different source instead of the registry data which has a limitation in specifying the time zone rules.

**Comment by jskeet** [comment]
Thanks. It would be really nice if the expected interpretation of `AdjustmentRule` could actually be documented. In Noda Time we aim to reproduce the behaviour of `TImeZoneInfo` as close as we can, but it's really hard when things change like this (and when there are other situations where `TimeZoneInfo` behaves really bizarrely.)

I guess for the moment I'll just have to ignore this time zone in my tests :(

**Comment by danmoseley** [comment]
@tarekgh if you talked to Windows as mentioned, is there any more work on .NET?

**Comment by tarekgh** [comment]
No more work from .NET side. Windows is not planning to add any historical TZ data. We can close it. We may consider adding some more docs for AdjustmentRule later.
