### ISSUE TITLE
openSUSE - upgrade using 'zypper up' command upgrades 3.1 host to 6.0 and removes 'dotnet' command

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#61849]
Dotnet-host package is built with version-agnostic package name, which causes an issue when upgrading, for instance 3.1 host to latest. 6.0 host will be installed and 'dotnet' command will be missing.

```
rpm -q --queryformat "name: %{NAME}, version: %{VERSION}" https://packages.microsoft.com/sles/15/prod/dotnet-host-6.0.0-x64.rpm
warning: https://packages.microsoft.com/sles/15/prod/dotnet-host-6.0.0-x64.rpm: Header V4 RSA/SHA256 Signature, key ID be1229cf: NOKEY
name: dotnet-host, version: 6.0.0
```

Dotnet-host package is intentionally built as version-agnostic, see relevant infra:

https://github.com/dotnet/runtime/blob/4e2d3a6f45f0808e42b5ac55b764e2e813e8a4c7/src/installer/pkg/sfx/installers/dotnet-host.proj#L15

https://github.com/dotnet/arcade/blob/97463777ee9a8445d4a4c5911ede0f0cd71fa8aa/src/Microsoft.DotNet.Build.Tasks.Installers/build/installer.singlerid.targets#L99

Upgrading to latest host version should not remove 'dotnet' command.

**Comment by NikolaMilosavljevic** [comment]
I've confirmed this issue on openSUSE and other RPM-based distros (i.e. CentOS). It is a regression.

In .NET 3.1 and 5.0 we were creating a `dotnet` symlink in `/usr/bin`: https://github.com/dotnet/runtime/blob/97f0e8a5e4110244224fbc115c8d3dc5c44a360f/src/installer/pkg/packaging/rpm/package.targets#L85

In 6.0 after infra refactoring we had a bug where we weren't setting any symlinks. Later we fixed it to create symlink in an `after-install.sh` script: https://github.com/dotnet/runtime/blob/e9036b04357e8454439a0e6cf22186a0cb19e616/src/installer/pkg/sfx/installers/rpm_scripts/host/after_install.sh#L6

However, new symlink is created in `/usr/local/bin`. To get `dotnet` command working, one needs to open a new shell window:

It's unclear why we ended up with `/usr/local/bin` instead of `/usr/bin`.

**Comment by NikolaMilosavljevic** [comment]
The workaround is to create a symlink using the following command:

`ln -sf /usr/share/dotnet/dotnet /usr/bin/dotnet`

**Comment by am11** [comment]
> It's unclear why we ended up with `/usr/local/bin` instead of `/usr/bin`.

The installer can cleanup the existing symlinks in both known locations and create the new one.

**Comment by dcermak** [comment]
> Dotnet-host package is intentionally built as version-agnostic, see relevant infra:

Why is that the case? From an outsider's PoV it doesn't make a lot of sense to have everything versioned except for the main package which will just freely upgrade to the latest .Net version.

**Comment by NikolaMilosavljevic** [comment]
The original issue was fixed in January.
