### ISSUE TITLE
HTTP/2 request does not work on Windows 7

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/runtime#61866]
### Description

Hello,

I am trying to make a HTTP/2 request with HttpClient, but it does not work on Windows 7. It does work on Windows 10, though.
Whilst browsing the .NET runtime source code, I found that [HTTP/2 feature may be on or off](https://github.com/dotnet/runtime/blob/27536d59df9b9e7263d48dfe910b48e3792c57a9/src/libraries/System.Net.Http/src/System/Net/Http/GlobalHttpSettings.cs#L24), depending on an environment variable or an AppContext switch; despite that, the default value for the feature is on, regardless of the operating system.
I did not find a clear documentation about on which OSs .NET can perform HTTP/2 requests.

### Reproduction Steps

1. `dotnet new console`
2. Copy the following code and paste it in the `Program.cs` file:

```cs
HttpClient httpClient = new();
HttpRequestMessage reqMsg = new(HttpMethod.Get, "https://http2.akamai.com/")
{
    Version = new Version(2, 0),
    VersionPolicy = HttpVersionPolicy.RequestVersionExact
};

HttpResponseMessage resMsg = await httpClient.SendAsync(reqMsg);

string bodyContent = await resMsg.Content.ReadAsStringAsync();

Console.WriteLine($"Status code: {resMsg.StatusCode}");
Console.WriteLine($"Body: {bodyContent}");
```

3. `dotnet run`

### Expected behavior

It should print on Console a 200 OK status code and the HTML response body obtained from a successful request. The URL used for this test is: [https://http2.akamai.com/](https://http2.akamai.com/).

### Actual behavior

The following Exception is printed on Console:

```
Unhandled exception. System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersio
nExact while unable to establish HTTP/2 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async
, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellatio
nToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOpti
on, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken origi
nalCancellationToken)
   at Program.<Main>$(String[] args) in C:\MyProjects\TestHttp2Net6\Program.cs:line 18
   at Program.<Main>(String[] args)
```

### Known Workarounds

Not a workaround, but setting the environment variable or AppContext switch did not work either ([link](https://docs.microsoft.com/pt-br/dotnet/core/run-time-config/networking#http2-protocol)).

### Configuration

* Which version of .NET is the code running on? **.NET 6**
* What OS and version, and what distro if applicable? **Windows 7**
* What is the architecture (x64, x86, ARM, ARM64)? **AMD64**
* Do you know whether it is specific to that configuration? **Same code works on Windows 10 x64**

I guess this bug might be happening on other Windows versions: Windows 8.1, Windows Server...

**Comment by huoyaoyuan** [comment]
It seems that Windows 7 does not support necessary TLS feature for HTTP/2. Related: https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-6.0#unable-to-start-aspnet-core-grpc-app-on-macos

**Comment by wfurt** [comment]
More specifically https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831771(v=ws.11)?redirectedfrom=MSDN
Windows 8 & Server 2012 seems to be first versions where the support should be available. 

Unfortunately, this is really not actionable for .NET @alexandrehtrb
