### ISSUE TITLE
Avx2.AlignRight does not generate VPPALIGNR intrinsic

### ISSUE THREAD

**Issue by zvrba** [dotnet/runtime#61877]
### Description

I have a piece of code that looks like this:
```
    using V = Vector256<int>;

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        unsafe V Load8(int* v, int c) {
            var m = Avx2.AlignRight(AlternatingMaskLo128, Complement, (byte)((8 - c) << 2));
            return Avx2.BlendVariable(Max, Avx2.MaskLoad(v, m), m);
        }
```

which is called from various places in the code.  When looking at the disassembly, I find the following code:

```
00007FF8FCD0A78F  vextractf128 xmm7,ymm6,1  
00007FF8FCD0A795  call        Method stub for: System.Runtime.Intrinsics.X86.Avx2.AlignRight(System.Runtime.Intrinsics.Vector256`1<Int32>, System.Runtime.Intrinsics.Vector256`1<Int32>, Byte) (07FF8FCCFAF58h)  
00007FF8FCD0A79A  vmovupd     ymm0,ymmword ptr [rsi+0D8h]  
00007FF8FCD0A7A2  vmovupd     ymm1,ymmword ptr [rsp+130h]  
00007FF8FCD0A7AB  mov         rax,qword ptr [rsp+168h]  
00007FF8FCD0A7B3  vpmaskmovd  ymm1,ymm1,ymmword ptr [rax]  
00007FF8FCD0A7B8  vmovupd     ymm2,ymmword ptr [rsp+130h]  
00007FF8FCD0A7C1  vpblendvb   ymm8,ymm0,ymm1,ymm2  
```

i.e., everything gets nicely inlined and optimized, except `PALIGNR` instruction not being generated. I cannot even step into the CALL in visual studio to see what it does. The code had executed for a while before I set a breakpoint to disassemble it.

### Configuration

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19042.1348 (20H2/October2020Update)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET SDK=5.0.303
  [Host]     : .NET Core 3.1.21 (CoreCLR 4.700.21.51404, CoreFX 4.700.21.51508), X64 RyuJIT
  DefaultJob : .NET Core 3.1.21 (CoreCLR 4.700.21.51404, CoreFX 4.700.21.51508), X64 RyuJIT

**Comment by saucecontrol** [comment]
`vpalignr` requires the byte count to be an immediate (constant) value.  Since you are using a variable count, JIT must generate a stub to emit the code with the value as a constant.

**Comment by zvrba** [comment]
Oh, good catch, thanks. I overlooked that. And C# doesn't have an expressive enough type system to require that this parameter must be a compile-time constant.

**Comment by jkotas** [comment]
We plan to add analyzer that warns about these situations. See https://github.com/dotnet/runtime/issues/33771 .

**Comment by zvrba** [comment]
@jkotas One last question: why won't visual studio step into stub methods? If I could have seen the disassembled stub (and the generated jump table), I'd figure this out on my own. I even tried to paste the address of the jump target into the disassembly window, but I got no meaningful result.

**Comment by jkotas** [comment]
> why won't visual studio step into stub methods?
 
 I do not know. I have opened https://github.com/dotnet/runtime/issues/61890 . It is not clear to me whether it is a problem in the runtime or in Visual Studio.
