### ISSUE TITLE
Data loss in BrotliStream with CompressionLevel.Optimal

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#61872]
### Description

We know that an unbuffered `BrotliStream` [produces pathological cases on `CompressionLevel.Fastest`](https://github.com/dotnet/runtime/issues/36245,) generating "compressed" data approximately 4X larger than the source data.  Well, I just found an even worse one on `CompressionLevel.Optimal`: the generation of 0 bytes of output from ~6.8 MB of input.

### Reproduction Steps

Extract `pathological.data` from [the zipfile.](https://github.com/dotnet/runtime/files/7574526/pathological.zip)  Use it in this routine:

```
void PathologicalCompression()
{
    var mem = new MemoryStream();
    var br = new BrotliStream(mem, CompressionLevel.Optimal);
    var fs = File.OpenRead("pathological.data");
    fs.CopyTo(br);
    Console.WriteLine($"Compressed to {mem.Length} bytes");
}
```

### Expected behavior

Compressed data size should be somewhere in the neighborhood of the zipfile's size.

### Actual behavior

Compressed data size is 0.

### Configuration

.NET 5, Windows 10, x64.

**Comment by canton7** [comment]
This appears to simply be because the `BrotliStream` isn't flushed or disposed.

```cs
var mem = new MemoryStream();
using (var br = new BrotliStream(mem, CompressionLevel.Optimal, leaveOpen: true))
{
    var fs = File.OpenRead("pathological.data");
    fs.CopyTo(br);
}
Console.WriteLine($"Compressed to {mem.Length} bytes");

mem.Position = 0;

var decompressed = new MemoryStream();
using (var br = new BrotliStream(mem, CompressionMode.Decompress))
{
    br.CopyTo(decompressed);
}
Console.WriteLine($"Decompressed to {decompressed.Length} bytes");
```

Output:

```
Compressed to 1190 bytes
Decompressed to 6995160 bytes
```

**Comment by masonwheeler** [comment]
🤦‍♂️ Looks like you're right.  Nevermind...
