### ISSUE TITLE
[API Proposal]: Method to translate `PosixSignal` values to native signal numbers

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#61889]
### Background and motivation

With #50527 shipped in .NET 6, it has become easy to handle POSIX signals in .NET applications. Unfortunately, sending signals is still quite problematic: There is no way to translate a `PosixSignal` value to a native signal number. So while you can define a P/Invoke signature for e.g. `kill`, you have no clean way of invoking it correctly.

### API Proposal

```csharp
namespace System.Runtime.InteropServices
{
    public static class PosixSignalMarshal
    {
        public int TranslateToNative(PosixSignal signal);
    }
}
```

* For values that aren't defined in the enum, I *think* `TranslateToNative` should just pass them through unchanged if they're non-negative, and throw `ArgumentOutOfRangeException` if they're negative.
* On Windows, `TranslateToNative` would map to the [`CTRL_...` values](https://docs.microsoft.com/en-us/windows/console/handlerroutine#parameters).

### API Usage

```csharp
[DllImport("c", SetLastError = true)]
static extern int kill(int pid, int sig);

using Process proc = ...;
kill(proc.Id, PosixSignalMarshal.TranslateToNative(PosixSignal.SIGTSTP);
```

### Alternative Designs

This could be an extension method on the `PosixSignal` enum also, but I don't think there's much precedent for doing this in the BCL.

### Risks

None?

**Comment by jkotas** [comment]
If all you want to do with this API is to send signal, would it be better to add API for sending signals instead?https://github.com/dotnet/runtime/issues/59746

Or are there any other use cases for this API beyond sending signals?

**Comment by alexrp** [comment]
Why not both? 😄

Having a `Process.SendSignal(PosixSignal)` method (which translates to `CTRL_...` on Windows) would indeed solve my immediate problem.

But there are many other ways to send and receive signals, see for example the list of related functions on `man 2 signal`. There's also the question of whether `pthread_kill` (which has no obvious Windows equivalent) is something that should be supported. I don't know if there are use cases for these in .NET land.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I've searched but can't seem to find it. I thought there was a conversation/issue with concerns about providing a mapping for POSIX signals. Am I misremembering something?

**Comment by jkotas** [comment]
You may be remembering the discussion that concluded that there has to be a mapping since the mapping between the signal names and native signal numbers is not 100% uniform between platforms.

**Comment by alexrp** [comment]
Does anything need to happen on my end to move this forward?

**Comment by jkotas** [comment]
It would be useful to update "API Usage" section to show an example that is not redundant with #59746

**Comment by alexrp** [comment]
I ended up moving this code to a small C support library in my project, so I don't personally have a great need for this anymore, and #59746 will probably cover other people's needs.
