### ISSUE TITLE
CryptoStream.Read adds "null" add the EOF

### ISSUE THREAD

**Issue by BornToBeRoot** [dotnet/runtime#61886]
Hi,

after migrating to .NET 6 I have the same problem as described here https://github.com/dotnet/runtime/issues/61535#issuecomment-967713606

The workaround helps, at least all data is displayed, but at the end of the file there are "null" fields. Because of this the data can not be converted to an XML.

The file looks like this: 
![image](https://user-images.githubusercontent.com/16019165/142748185-ca35e02f-150f-4446-b3f6-bdb4347679c8.png)

Example code: https://github.com/BornToBeRoot/NETworkManager/blob/master/Source/NETworkManager.Utilities/CryptoHelper.cs

**Comment by vcsjones** [comment]
> var cipher = encryptedBytesWithSaltAndIV.Skip

This is because your `cipher` length, and thus `text` length, is accounting for the space of the PKCS7 padding. The extra zeros are the part of the array that `Read` never wrote to.

The quickest fix is to change your `Decrypt`'s return to only return the number of bytes read, something like

```csharp
return text.AsSpan(0, readBytes).ToArray();
```

If you're interested, here is the same code re-written using modern .NET 6 APIs. It is less code, faster, and the new APIs are clear in their purpose.

```csharp
using System;
using System.Diagnostics;
using System.Security.Cryptography;

public static class CryptoHelper
{
    public static byte[] Encrypt(byte[] decryptedBytes, string password, int keySize, int blockSize, int iterations)
    {
        ReadOnlySpan<byte> salt = GenerateRandomEntropy(keySize / 8); // Generate salt based
        ReadOnlySpan<byte> iv = GenerateRandomEntropy(blockSize / 8); // Generate iv, has to be the same as the block size

        byte[] key = Rfc2898DeriveBytes.Pbkdf2(password, salt, iterations, HashAlgorithmName.SHA1, keySize / 8);

        using Aes aes = Aes.Create();
        aes.Key = key;

        int encryptedSize = aes.GetCiphertextLengthCbc(decryptedBytes.Length);
        byte[] cipher = new byte[salt.Length + iv.Length + encryptedSize];
        Span<byte> cipherSpan = cipher;
        salt.CopyTo(cipherSpan);
        iv.CopyTo(cipherSpan.Slice(salt.Length));
        int encrypted = aes.EncryptCbc(decryptedBytes, iv, cipherSpan.Slice(salt.Length + iv.Length));

        Debug.Assert(encryptedSize == encrypted);
        return cipher;
    }

    public static byte[] Decrypt(byte[] encryptedBytesWithSaltAndIV, string password, int keySize, int blockSize, int iterations)
    {
        ReadOnlySpan<byte> salt = encryptedBytesWithSaltAndIV.AsSpan(0, keySize / 8); // Take salt bytes
        ReadOnlySpan<byte> iv = encryptedBytesWithSaltAndIV.AsSpan(keySize / 8, blockSize / 8); // Skip salt bytes, take iv bytes
        ReadOnlySpan<byte> cipher = encryptedBytesWithSaltAndIV.AsSpan((keySize / 8) + (blockSize / 8));

        byte[] key = Rfc2898DeriveBytes.Pbkdf2(password, salt, iterations, HashAlgorithmName.SHA1, keySize / 8);

        using Aes aes = Aes.Create();
        aes.Key = key;
        return aes.DecryptCbc(cipher, iv);
    }

    private static byte[] GenerateRandomEntropy(int size)
    {
        return RandomNumberGenerator.GetBytes(size);
    }
}
```

**Comment by bartonjs** [comment]
This is a documented (potentially-)breaking change.  CryptoStream no longer over-eagerly reads, and instead follows the more general Stream Read pattern.

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by BornToBeRoot** [comment]
Thanks. Your (@vcsjones) solution works!
