### ISSUE TITLE
[API Proposal]: Support for MultiSet & MultiMap in System.Collections.Generic

### ISSUE THREAD

**Issue by one-harsh** [dotnet/runtime#61892]
### Background and motivation

While we have Dictionary and HashSet support, there are many times where we need a [MultiSet](https://en.wikipedia.org/wiki/Multiset) or a [MultiMap](https://en.wikipedia.org/wiki/Multimap). Could this be added to the core library or is there already a plan to add one? Various other languages, including C++, supports this container iterator.

### API Proposal

```C#
namespace System.Collections.Generic
{
    // Sample API proposal for MultiSet
    public class MultiSet<T> : IEnumerable<T> where T : IEquatable<T>
    {
        public IEnumerable<T> Keys;
        public int Length { get; }
        public IEnumerator<T> GetEnumerator();
        public int this[T key] { get; } // get count
        public void Add(T key);
        public bool Remove(T key);
        public bool Contains(T key);
    }
}
```     

### API Usage

```C#
// Fancy the value
var c = new MultiSet<int>();
c.Add(42);
c.Add(42);

// Getting the values out
Console.WriteLine(c[42]); // prints 2
```

**Comment by Frassle** [comment]
N.B That [
System.Collections.Concurrent.ConcurrentBag<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1?view=net-6.0) exists, and so gives a prior that `MultiSet` should probably be `System.Collections.Generic.Bag<T>`. Also is there any benefit from having a non-concurrent bag? Can anything about the API be made nicer or more efficient than just using ConcurrentBag?

**Comment by eiriktsarpalis** [comment]
Just so I understand the proposed semantics, would a multiset be equivalent to defining a `Dictionary<T, int>`, where `int` denotes  multiplicity? Or would it need to encapsulate all instances that are being added, akin to something like `Dictionary<T, List<T>?>`?

**Comment by stephentoub** [comment]
For MultiMap, might be worth looking through various repos to understand the extent to which this would be used.  A quick regex search of dotnet/runtime shows ~50 places we do `new Dictionary<\w+, List`, another ~20 in ASP.NET, another ~50 in Roslyn, etc., but I've not looked in depth to see whether they'd really benefit from a new, dedicated type for this, or potentially whether we might instead consider extension methods on a `Dictionary<T, List<U>>` or something similar to make these use cases a bit simpler.

For MultiSet, FWIW I typically handle those cases today with GetValueRefOrAddDefault, e.g.
```C#
var counts = new Dictionary<string, int>();
foreach (string input in source)
{
    CollectionsMarshal.GetValueRefOrAddDefault(counts, input, out _)++;
}
```
I'm not sure it's really worth an entirely new type to achieve this, as I don't love the idea of having to maintain yet another Dictionary/HashSet/etc.-like type.  If we'd be willing to instead wrap a Dictionary, with a MultiSet being just a thin veneer / helper type on top of it, that could be reasonable if we believed the use case was really prevalant enough to be worth it (you'd be paying for one small additional allocation and then getting all of Dictionary's implementation for free).

**Comment by ViIvanov** [comment]
Why not to provide a custom comparer for MultiSet? Is this case it make sense to store different values under the same key.

**Comment by eiriktsarpalis** [comment]
Here are the results from grep.app for [Dictionary<T, List<U>>](https://grep.app/search?q=new%20Dictionary%3C%5Cw%2B%2C%20List&regexp=true&filter[lang][0]=F%23&filter[lang][1]=C%23) and [Dictionary<T, int>](https://grep.app/search?q=new%20Dictionary%3C%5Cw%2B%2C%20List&regexp=true&filter[lang][0]=F%23&filter[lang][1]=C%23). While these are fairly common, I agree with @stephentoub that it's likely not worth the cost of designing, implementing and maintaining yet another set of collections. It seems that such use cases are fairly straightforward to express using the existing Dictionary type.

**Comment by stephentoub** [comment]
Just to make sure I communicated clearly,  I do see usability benefits to such types, I just don't want to have to maintain a complete,  separate,  high-performance implementation for each.  If such use is common, I'd be fine with us exposing such types as thin wrappers over Dictionary.

**Comment by eiriktsarpalis** [comment]
Understood. From my perspective I don't see big value in exposing thin wrappers like these. There are many ways one could represent a multiset, and I'm confident that most users are familiar enough with Dictionary to quickly get up to speed with the multiset/multimap representations that they require. It also leaves space for the NuGet ecosystem to innovate, perhaps by authoring bespoke, high-performance implementations.

**Comment by one-harsh** [comment]
I understand that we can provide this with a good wrapper around dictionary (which is what I do for my uses), there are some distinct scenarios that actually come in handy with a generic implementation, for example, we can have single-count removal from MultiSet instead of removing the element altogether.
Thanks for pointing in the nuget direction which might be a suitable alternative. If at any point I find my wrapper to grow relatively big enough where it serves various other purposes, I might publish it myself.
