### ISSUE TITLE
Unexpected behavior of TimeSpan.FromSeconds

### ISSUE THREAD

**Issue by ahmed605** [dotnet/runtime#61909]
### Description

Unexpected behavior (imprecise) of TimeSpan.FromSeconds with floats after upgrading from .NET Framework 4 to .NET 6

### Reproduction Steps

```csharp
float num = 0.12f;
TimeSpan span = TimeSpan.FromSeconds(num);
string result = span.ToString("c");
```

### Expected behavior

That code returns `00:00:00.1200000` under .NET Framework 4

### Actual behavior

That code returns `00:00:00.1199999` under .NET 6

### Regression?

Yes, it did work as expected in .NET Framework 4

### Known Workarounds

As a workaround we can use `TimeSpan.FromSeconds((double) (new decimal(num)));` instead but that's not ideal especially that it worked as expected before

**Comment by huoyaoyuan** [comment]
This should be caused by float point precision update on .NET Core 3.

**Comment by riverar** [comment]
0.12 cannot be exactly represented so not sure there's a bug here. Seems to working normally. Consider passing in a `TimeSpan`, which represents `Seconds` with an integer backing that value.

**Comment by tannergooding** [comment]
riverar is correct here. This is just a formatting/display improvement introduced in .NET Core 3.0: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

The actual underlying bits haven't changed at all and the result is still identical. The difference is that .NET Core 3.0+ correctly displays the roundtrippable floating-point value which more accurately displays the actual value represented in cases like this.
