### ISSUE TITLE
[API Proposal]: Add ``CompressionNative_InflateInit_`` and ``CompressionNative_DeflateInit_`` to clrcompression.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#61910]
### Background and motivation

Currently I am working on an zlib implementation that utilizes the easier deflate / inflate init functions, of which does not require setting the window bits. However because of it that means I currently depend on the user providing their own zlib.dll for x86, x64, arm, and arm64 on windows and linux, and force them to install it with homebrew for macos.

However I would rather instead have my code depend on the one built into .NET (clrcompression).

Also if possible a backport of this to 6.0 would be great if possible.

Note: I plan to eventually propose the code that I need these functions for in .NET 7 after testing them with .NET 6.

### API Proposal

added exports to clrcompression (aka System.IO.Compression.Native):
```c
/* zlib result type here. */ CompressionNative_InflateInit_(PAL_ZSTREAM* stream, const char* zlibVersion, int streamSize);
/* zlib result type here. */ CompressionNative_DeflateInit_(PAL_ZSTREAM* stream, int compressionLevel, const char* zlibVersion, int streamSize);
```

### API Usage

```C#
public static class UnsafeNativeMethods
{
    [DefaultDllImportSearchPaths(DllImportSearchPath.LegacyBehavior)]
    [DllImport("clrcompression", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern unsafe ZlibResult CompressionNative_InflateInit_(ZStream* zs, byte* zlibVersion, int streamSize);

    [DefaultDllImportSearchPaths(DllImportSearchPath.LegacyBehavior)]
    [DllImport("clrcompression", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern unsafe ZlibResult CompressionNative_DeflateInit_(ZStream* zs, ZlibCompressionLevel compressionLevel, byte* zlibVersion, int streamSize);

    // snip other compression related imports.
}

// snip code that uses the above imports (Compress/Decompress).
// in my code ZlibResult and ZlibCompressionLevel are enums.
```

### Alternative Designs

Not that I can currently think of.

### Risks

Minimal.

**Comment by jkotas** [comment]
We consider the native shim methods to be internal implementation detail that can change any time. They are not public surface that the code outside the runtime libraries should depend on. I would recommend that your library avoids taking a dependency on them.

If you would like to have thin non-stream wrappers over zlib, they should be exposed as proper managed APIs. For example, take a look at `BrotliEncoder` / `BrotliDecoder` added as part of https://github.com/dotnet/runtime/issues/24389. It may make sense to add similar types for zlib.

**Comment by AraHaan** [comment]
I agree, a ZlibEncoder / ZlibDecoder would work where ZlibEncoder takes int for compression level (that the native implementation supports) to suite what I currently need to manually use the clrcompression library for today on. However it would need to operate with spans only as well. I will be proposing for a static compression / decompression functions that operate on spans to .NET 7 eventually anyway so a ZlibEncoder / ZlibDecoder could be made usable not only in DeflateStream (which is used in ZlibStream) but also in that as well making it easier to reuse the code with little effort.

**Comment by stephentoub** [comment]
> ZlibEncoder / ZlibDecoder would work 

Right, this is what we've discussed in previous issues, e.g.
https://github.com/dotnet/runtime/issues/2236#issuecomment-698925149
https://github.com/dotnet/runtime/issues/39327#issuecomment-658871313
https://github.com/dotnet/runtime/issues/61502#issuecomment-967078308

To my knowledge no ones created an issue proposing that officially.

> However it would need to operate with spans

BrotliEncoder/Decoder do.  There's no reason a ZlibEncoder/Decoder would be different.

> We consider the native shim methods to be internal implementation detail that can change any time

+1.  I'm going to close this issue as we're not going to expose the proposed APIs.  Please feel free to open one for ZLibEncoder/Decoder, though.

Thanks.

**Comment by AraHaan** [comment]
This is what I currently got so far for ZlibEncoder / ZlibDecoder:

```cs
public struct ZlibEncoder : IDisposable
{
    public ZlibEncoder(int compressionLevel, int window = 15, int memoryLevel = 8);
    public int MemoryLevel { get; set; }
    public bool IsDisposed { get; set; }
    public void Dispose();
    // no throw on failure.
    public bool TryCompress(ReadOnlySpan<byte> source, Span<byte> dest, out uint adler32, out uint bytesWritten);
    // throws on failure.
    public uint Compress(ReadOnlySpan<byte> source, Span<byte> dest, out uint adler32);
}
public struct ZlibDecoder : IDisposable
{
    public ZlibDecoder();
    public bool IsDisposed { get; set; }
    public void Dispose();
    // no throw on failure.
    public bool TryDecompress(ReadOnlySpan<byte> source, Span<byte> dest, out uint adler32, out uint bytesWritten);
    // throws on failure.
    public uint Decompress(ReadOnlySpan<byte> source, Span<byte> dest, out uint adler32);
}
```
