### ISSUE TITLE
After .NET 6 upgrade, debugger crashes when redirecting from one blazor wasm app to another 

### ISSUE THREAD

**Issue by bgriffy** [dotnet/runtime#61917]
### Describe the bug
On Blazor WASM projects targeting .NET 6, if you run the project in debug mode, the Visual Studio debugger crashes if you attempt to redirect to another Blazor WASM application that also targets .NET 6. The broswer immediately closes. 

Here is a quick example I've made on the counter page using the default VS template for a standalone Blazor WASM project: 

```
@page "/counter"
@inject NavigationManager NavigationManager

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        NavigationManager.NavigateTo("https://bgriffy.github.io/BlazorWasmDebugRepro/");
        currentCount++;
    }
}
```

If you run this in debug mode, the debugger will immediately crash once you hit the counter button. The application its redirecting to was also created using the default VS template for a standalone Blazor WASM app targeting .NET 6. (https://github.com/bgriffy/BlazorWasmDebugRepro)

I've found that if either of the projects target .NET 5 instead, the debugger runs without issue. 

### To Reproduce
- Ensure .NET 6 SDK is installed. 
- Either create a standalone .NET 6 blazor WASM app, using the default template in VS, and paste the code above in the counter page. Or you can clone my repo: https://github.com/bgriffy/BlazorWasmDebugRepro2 
- Run the project in debug mode and click the button on the counter page. 

### Exceptions 
This is the only exception I've seen which I think is related. It pops up in the immediate window in VS. 
```
* Assertion at /__w/1/s/src/mono/mono/eglib/gptrarray.c:117, condition `<disabled>' not met
```

### Further technical details
- ASP.NET Core version: 6.0.100
- I'm using Visual Studio Professional 2022, 17.1.0 Preview 1.1. But I've also reproduced the issue on the current release version. 
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>
  
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

**Comment by thaystg** [comment]
The published page that you are trying to redirect https://bgriffy.github.io/BlazorWasmDebugRepro is in release mode? If you publish in debug mode it works correctly?

Thanks,
Thays

**Comment by thaystg** [comment]
@lewing @radekdoulik The thing is that in a published release app it's not linking the "stub" version of the debugger, because of that we are calling mono_wasm_send_dbg_command and the debugger is not enabled, because Blazor didn't enable it, which makes sense because it's a release app. Getting the assert described in the issue.
I can and will protect it on mini-wasm-debugger, but I think we should fix it on published app also.

**Comment by radekdoulik** [comment]
@thaystg the release should use the stub of debugger component. Do you have a binlog of a build where it doesn't link with the stub?

**Comment by bgriffy** [comment]
> The published page that you are trying to redirect https://bgriffy.github.io/BlazorWasmDebugRepro is in release mode? If you publish in debug mode it works correctly?
> 
> Thanks, Thays

Hey @thaystg, thanks for responding. FYI, I published the app (https://bgriffy.github.io/BlazorWasmDebugRepro) in debug mode but it looks like I'm having the same problem.

**Comment by radekdoulik** [comment]
It looks like the blazor app in VS is not relinking `dotnet.wasm` at all, so it ends with non-stub debugger component. (from https://github.com/dotnet/runtime/blob/main/src/mono/wasm/runtime/CMakeLists.txt#L16-L18)

When I build the same project on command line with `dotnet publish`, it is relinked and we get the debugger stub component.

The command line uses `Restore` and `Publish` targets, while VS uses

    ResolveFrameworkReferencesDesignTime
    ResolveProjectReferencesDesignTime2
    CollectResolvedSDKReferencesDesignTime
    CollectPackageReferences
    ResolveComReferencesDesignTime
    RazorGenerateComponentDesignTime
    BuiltProjectOutputGroup
    CollectFrameworkReferences
    CollectUpToDateCheckBuiltDesignTime
    CollectPackageDownloads
    RazorGenerateDesignTime
    ResolveAssemblyReferencesDesignTime
    GenerateSupportedTargetFrameworkAlias
    CollectAnalyzersDesignTime
    CollectUpToDateCheckInputDesignTime
    CollectUpToDateCheckOutputDesignTime
    ResolvePackageDependenciesDesignTime
    CollectSuggestedWorkloads
    CollectCentralPackageVersions
    CompileDesignTime
    CollectResolvedCompilationReferencesDesignTime

targets.

@radical @lewing what would be best solution for this?

**Comment by joer33304** [comment]
Did this fix make it to the 7 preview 1 release ?

**Comment by qJake** [comment]
I'm also experiencing this issue, in .NET 6.0.1, but only with one project (not two). I rebuilt in Release mode, and now, changing back to Debug mode doesn't work either. I can't debug no matter what mode I'm in.

Is there a workaround? I already tried a Clean Solution, as well as deleting the /bin/ and /obj/ folders, but that didn't work.

**Comment by qJake** [comment]
I just found a workaround by performing the following steps:

Edit your `/Properties/launchSettings.json` file.

If you have a top-level property called `iisSettings`, remove that property/object.

If you have a profile in the `profiles` dictionary called `IIS Express`, remove that profile.

You should only be left with one profile that is the same name as your project.

Clean and rebuild, and debugging should work now.

**Comment by bgriffy** [comment]
> launchSettings.json

FYI, I tried this work-around, it doesn't seem to work for me still.

**Comment by bgriffy** [comment]
> I just found a workaround by performing the following steps:
> 
> Edit your `/Properties/launchSettings.json` file.
> 
> If you have a top-level property called `iisSettings`, remove that property/object.
> 
> If you have a profile in the `profiles` dictionary called `IIS Express`, remove that profile.
> 
> You should only be left with one profile that is the same name as your project.
> 
> Clean and rebuild, and debugging should work now.

FYI, I tried this work-around, it doesn't seem to work for me still.

**Comment by thaystg** [comment]
> h one project (not two). I rebuilt in Release mode, and now, changing back to Debug mode doesn't work either. I can't debug no matter what mode I'm in.

This is on release 6.0.2.

**Comment by thaystg** [comment]
> Did this fix make it to the 7 preview 1 release ?

This is on release 6.0.2.

**Comment by thaystg** [comment]
Can you help me to reproduce this, build in release and then rebuild in debug and the debugger is not working?
I tried here using dotnet 6.0.2 and it's working for me.
Any hints how to reproduce?

**Comment by thaystg** [comment]
> > Can you help me to reproduce this, build in release and then rebuild in debug and the debugger is not working? I tried here using dotnet 6.0.2 and it's working for me. Any hints how to reproduce?
> 
> I hadn't updated to 6.0.2 yet. I am installing now to test. I'll let you know if there's any issues.

Thanks!!!

**Comment by bgriffy** [comment]
> > > Can you help me to reproduce this, build in release and then rebuild in debug and the debugger is not working? I tried here using dotnet 6.0.2 and it's working for me. Any hints how to reproduce?
> > 
> > 
> > I hadn't updated to 6.0.2 yet. I am installing now to test. I'll let you know if there's any issues.
> 
> Thanks!!!

I am not able to get it to work after installing the the 6.0.2 SDK. 

Steps to reproduce: 
- Clone https://github.com/bgriffy/BlazorWasmDebugRepro2
- Run it in debug mode 
- Go to the counter page and click the "Click me" button

**Comment by thaystg** [comment]
The published app(https://bgriffy.github.io/BlazorWasmDebugRepro/) is still using dotnet 6.0.0, right?
![image](https://user-images.githubusercontent.com/4503299/157304504-ca31a62f-27fc-43b2-bffd-7417d826e165.png)

**Comment by bgriffy** [comment]
> The published app(https://bgriffy.github.io/BlazorWasmDebugRepro/) is still using dotnet 6.0.0, right? ![image](https://user-images.githubusercontent.com/4503299/157304504-ca31a62f-27fc-43b2-bffd-7417d826e165.png)

Right you are! After publishing both projects with the .NET 6.0.2 SDK, I no longer have any issues debugging. I'll go ahead and close the issue now. Thanks for the help on this!
