### ISSUE TITLE
How can a .NET Core Web Api running on Ubuntu Linux access a shared path in Windows?

### ISSUE THREAD

**Issue by bonybvarghese** [dotnet/runtime#61915]
I have a core web API to create some files. The API is running on a Linux machine and I need to create the files to a windows shared path.

**Comment by Jozkee** [comment]
Try looking for things like Samba and CIFS in order to achieve what you are describing.

These links may help you start.
https://askubuntu.com/questions/1038630/access-windows-10-shared-folder-from-ubuntu-18-04
https://www.computerhope.com/issues/ch001636.htm
