### ISSUE TITLE
Expression.Convert fails to convert byte to nint.

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [dotnet/runtime#61929]
### Description

According to documentation, there is a builtin conversion between `byte` and `nint`, but using `Expression.Convert` or `Expression.ConvertChecked` results in an exception beeing thrown:

```
System.InvalidOperationException : No coercion operator is defined between types 'System.Byte' and 'System.IntPtr'.
```

### Reproduction Steps

```
byte x = 2;
var expression = Expression.Convert(
    Expression.Constant(x),
    typeof(nint));
```

### Expected behavior

`Expression.Convert` and `Expression.ConvertChecked` are able to convert byte to nint.

### Actual behavior

System.InvalidOperationException is thrown

### Regression?

Don't know. Current sdk: 6.0.100

### Known Workarounds

None

### Configuration

> Which version of .NET is the code running on?
6.0.100

> What OS and version, and what distro if applicable?
Windows 10
Build Version: 10.0.19041

> What is the architecture (x64, x86, ARM, ARM64)?
x86

> Do you know whether it is specific to that configuration?
Don't think so

**Comment by GrabYourPitchforks** [comment]
For LINQ team: I'm curious how this might translate across hosts, given that one of the scenarios for expression trees is to "serialize" them for execution within a remote SQL server. Presumably once _nint_ and _nuint_ are fully supported there will be a defined behavior regarding whose bitness wins - the client's or the server's?

**Comment by svick** [comment]
It's not just calling `Expression` explicitly, [the following code also throws the same exception](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACADAAT4CMAdADKwCOFAogB4AOyApgM6dQD2MnANwBYAFBjmbLj37F2xALzEAFMACeCecACUigHwqYsBNuCCgA=):

```c#
Expression e = (byte b) => (nint)b;
```

I think that should never happen. Should the C# compiler consider making this an error?

**Comment by cston** [comment]
@TiagoOliveiraMarques thanks for reporting this.

The `InvalidOperationException` for `Expression.Convert(Expression.Constant((byte)2), typeof(nint))` is expected.

Built-in conversions for `nint` and `nuint` are implemented directly by the C# compiler for conversions from source. No corresponding changes have been made for expression tree support of `nint` and `nuint`, and we are limiting the changes to `System.Linq.Expressions` at this time - see [README.md](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions).

**Comment by cston** [comment]
@svick, I have logged https://github.com/dotnet/roslyn/issues/58256 to report errors for `nint` and `nuint` operations and conversions in expression lambdas.

**Comment by cston** [comment]
This should be caught by the compiler. Closing this issue since the compiler issue is tracked by https://github.com/dotnet/roslyn/issues/58256. Thanks @TiagoOliveiraMarques.
