### ISSUE TITLE
Microsoft.Extensions.Configuration Binder attempts to bind to Readonly Static Property

### ISSUE THREAD

**Issue by fitdev** [dotnet/runtime#61932]
### Description

Another issue with Configuration Binder. This time it took me a while to figure out why I was getting StackOverflowException. Then figured out it was because I call:

```cs

public static class Loader {

public static TInstance  GetInstance() {

TInstance myinstance = new();

IConfiguration.Bind(myinstance);

return myinstance;

}

}

public class TInstance {

public static TInstance Instance => Loader.GetInstance(); //<-- Obviously will cause StackOverflow if binder tries to bind to this property.

}


```

The issue lies in this code from DotNet 6 RTM:

```cs

[RequiresUnreferencedCode(PropertyTrimmingWarningMessage)]
        private static void BindProperty(PropertyInfo property, object instance, IConfiguration config, BinderOptions options)
        {
            // We don't support set only, non public, or indexer properties
            if (property.GetMethod == null ||
                (!options.BindNonPublicProperties && !property.GetMethod.IsPublic) ||
                property.GetMethod.GetParameters().Length > 0)
            {
                return;
            }

            object propertyValue = property.GetValue(instance); //<-- This is the problem!!!!
            bool hasSetter = property.SetMethod != null && (property.SetMethod.IsPublic || options.BindNonPublicProperties);

            if (propertyValue == null && !hasSetter)
            {
                // Property doesn't have a value and we cannot set it so there is no
                // point in going further down the graph
                return;
            }

            propertyValue = GetPropertyValue(property, instance, config, options);

            if (propertyValue != null && hasSetter)
            {
                property.SetValue(instance, propertyValue);
            }
        }

```

However in the current version https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs I see a different code, so apparently you have fixed it. Still, want to report it.

### Reproduction Steps

See description above.

### Expected behavior

Binder should not really try to get ANY property values (let alone those belonging to static readonly properties).

### Actual behavior

As of DotNet 6 RTM, Binder tries to get a value out of static readonly property while binding.

### Known Workarounds

This seems to be a serious issue and prevents usage of Configuration Binder if the target class has any properties that do complex logic on getters.

### Other information

@safern Any suggestions on how to deal with this in the meantime would be great!

**Comment by maryamariyan** [comment]
The issue was fixed with this PR: https://github.com/dotnet/runtime/pull/60415 and will be available in the next release

**Comment by fitdev** [comment]
@maryamariyan But that does not address the binding of static readonly properties. Why are they examined / bound to at all?
Nor does that address in general reading of the property values before they are bound. Why is this happening at all during binding?
