### ISSUE TITLE
Guard against partial cleanup of extracted files issue is happening again

### ISSUE THREAD

**Issue by genifycom** [dotnet/runtime#61936]
### Description

Today I have confirmed that C:\Wondows\Temp\.net\random-key files are being removed again.

The directory I checked contained 156 files instead of the 372 files required to run the application successfully.

It appears to have started happening in the last two weeks (don't know the exact timing).

These are long running services and restarting them restores the files. These services have been running successfully for months and have not been updated so is this a Windows update that changed things?

### Reproduction Steps

.Net 3.1 long running services. The unpacked files from Single file publish are being removed from the C:\Wondows\Temp\.net\random-key windows directory.

### Expected behavior

Tha files are not removed from the temp unpack directory.

### Actual behavior

Files are being removed by an unknown process.

### Regression?

This has started happening again in the last 2 weeks.

### Known Workarounds

Restart the .net applications causing the temp directory to be recreated with all files.

### Configuration

3.1

**Comment by vitek-karas** [comment]
I tried to describe our current thinking on the problem here: https://github.com/dotnet/runtime/issues/64120#issuecomment-1019372527.
