### ISSUE TITLE
MAUI Startup Improvement

### ISSUE THREAD

**Issue by BrzVlad** [dotnet/runtime#61941]
The majority of the time spent during MAUI Startup originates in method compilation. The list of all of the executed methods is in the following gist, together with the invocation count (https://gist.github.com/BrzVlad/bcc67b75401de25232dd786df08e5d86). 

On the runtime side it is worth investigating why the Type equality operator is not intrinsified to a simple pointer comparison.

A more significant improvement should come from reducing the number of methods invoked during startup, inside the MAUI framework. AOT would also need to be profiled to understand its impact.

**Comment by SamMonoRT** [comment]
Marking as future, till we can split out runtime work items and MAUI specific improvements into separate issues, and then target the relevant servicing branch for fixes.

**Comment by teo-tsirpanis** [comment]
Is that in Release mode @BrzVlad? The first five methods seem great targets for inlining. Doesn't Mono inline methods?

Or did you use an instrumenting profiler? It adds quite the overhead by disabling inlining and counting each method, making the results not representative of real-world use cases.

**Comment by BrzVlad** [comment]
The call instrumentation done by the profiler disables inlining, hence the methods seen above. This was done just to see what managed methods are being executed and how many times, to keep in mind for any further optimizations.

I did some investigation and the inefficacy of the type equality operator doesn't impact the startup time. The small details in codegen quality are not really relevant since the majority of time is spent in the runtime compiling methods.

**Comment by BrzVlad** [comment]
[aot-profile2.html.zip](https://github.com/dotnet/runtime/files/7732592/aot-profile2.html.zip)

Attached a profile for the Android MAUI startup with AOT. I'm not seeing anything that could be improved here on the runtime side. Maybe @vargaz and @lambdageek could also take a quick look on the profile, there is just a little bit of method loading from aot and some method compilation as well for the leftovers. There is quite a bit of action happening on the android side of things, maybe @jonathanpeppers can check for anything suspicious there.

**Comment by BrzVlad** [comment]
Tested an application (https://github.com/Redth/PoolMath) which has equivalent implementation for both MAUI and Xamarin Forms. The results that I was getting are the following:
```
pool math startup - maui no aot - 3.15s
pool math startup - maui profiled aot - 2.35s
pool math startup - maui aot - 1.75s

pool math startup - XF no aot - 3.05s
pool math startup - XF profiled aot - 2.3s
pool math startup - XF aot - 1.55s
```

There doesn't seem to be a significant difference between Xamarin.Forms and MAUI. Also checked the number of compiled methods (since JIT-ing and AOT method loading are significant contributors to startup time) and there was no significant difference between the two frameworks. Both used around 10000 methods.

**Comment by vargaz** [comment]
Why is the profiled aot version still slower than the aot version ? Was the profile created from the test app, or its a generic one ?

**Comment by BrzVlad** [comment]
[poolmathapp-maui-fullaot.html.zip](https://github.com/dotnet/runtime/files/7899878/poolmathapp-maui-fullaot.html.zip)
Attached a native profile for the application mentioned above in the full aot case for future reference.

**Comment by SamMonoRT** [comment]
We'll use https://github.com/dotnet/maui/issues/822 for further tracking.  Closing this issue in runtime repo
