### ISSUE TITLE
[API Proposal]: is there any methods can implement [:,:,::-1] operate in python

### ISSUE THREAD

**Issue by dupeng0224** [dotnet/runtime#61957]
### Background and motivation

there is a ndarray like [[[2,3,4], [2,3,4], ...,[2,3,4]]] i want convert it to [[[4,3,2], [4,3,2], ...,[4,3,2]]]。
in python i can do [:,:,::-1], in C#  is there any method to implement it?

**Comment by huoyaoyuan** [comment]
C# currently does not have such syntax to directly operate on MD array. You can do this with LINQ, in a noisy way:
```csharp
array.Select(l1 => l1.Select(l2 => l2.Reverse().ToArray()).ToArray()).ToArray()
```

Note that most operations in .NET won't produce values as array.
