### ISSUE TITLE
[API Proposal]: Making "Process asynchronous tasks as they complete" easy by using IAsyncEnumerable 

### ISSUE THREAD

**Issue by Vijay-Nirmal** [dotnet/runtime#61959]
EDITED on 1/23/2024 by @stephentoub:

```diff
namespace System.Threading.Tasks;

public class Task
{
+   public static IAsyncEnumerable<Task> WhenEach(params Task[] tasks);
+   public static IAsyncEnumerable<Task> WhenEach(params ReadOnlySpan<Task> tasks); // params when possible
+   public static IAsyncEnumerable<Task> WhenEach(IEnumerable<Task> tasks);

+   public static IAsyncEnumerable<Task<TResult>> WhenEach(params Task<TResult>[] tasks); // params for now; move it to ReadOnlySpan overload when that syntax is possible
+   public static IAsyncEnumerable<Task<TResult>> WhenEach(params ReadOnlySpan<Task<TResult>> tasks); // params when possible
+   public static IAsyncEnumerable<Task<TResult>> WhenEach(IEnumerable<Task<TResult>> tasks);
}

```

---

### Background and motivation

Currently, if we need to ["Process asynchronous tasks as they complete"](https://devblogs.microsoft.com/pfxteam/processing-tasks-as-they-complete/) then we need to write lots of unnecessary codes and its not straight forward, something like below.

```csharp
// Using currently available APIs
List<Task<int>> downloadTasks = downloadTasksQuery.ToList();
while (downloadTasks.Any())
{
    Task<int> finishedTask = await Task.WhenAny(downloadTasks);
    downloadTasks.Remove(finishedTask);
    Process(await finishedTask);
}
```

### API Proposal

```C#
namespace System.Threading.Tasks
{
    public class Task : IAsyncResult, IDisposable
    {
        public static IAsyncEnumerable<Task> WhenEach(params Task[] tasks);  // Please change the name, if needed
        public static IAsyncEnumerable<Task> WhenEach(IEnumerable<Task> tasks);
        public static IAsyncEnumerable<Task<TResult>> WhenEach(params Task<TResult>[] tasks); 
        public static IAsyncEnumerable<Task<TResult>> WhenEach(IEnumerable<Task<TResult>> tasks);
    }
}
```     

### API Usage

```csharp
// Using newly created APIs
await foreach (var finishedTask in Task.WhenEach(downloadTasksQuery))
{
    Process(await finishedTask);
}
```

### Updates

_(Others can edit this section and add more info)_

- `WhenEach` name suggested by @theodorzoulias, https://github.com/dotnet/runtime/issues/61959#issuecomment-978895039

**Comment by svick** [comment]
[This method already exists in `AsyncEx`](https://github.com/StephenCleary/AsyncEx/wiki/TaskExtensions), where it's called `OrderByCompletion`. It returns a (non-async) collection of wrapper tasks, but I suspect that's because it's older than `IAsyncEnumerable<T>` and using `IAsyncEnumerable<T>` returning the original tasks is the better approach today.

**Comment by theodorzoulias** [comment]
@Vijay-Nirmal a name that might be more suitable for the `Task.WhenAnyAsEnumerable` method is [`Task.WhenEach`](https://stackoverflow.com/questions/58194212/how-to-implement-an-efficient-wheneach-that-streams-an-iasyncenumerable-of-task "How to implement an efficient WhenEach that streams an IAsyncEnumerable of task results?"). :-)

**Comment by sakno** [comment]
You can achieve the same behavior with [TaskCompletionPipe](https://dotnet.github.io/dotNext/api/DotNext.Threading.Tasks.TaskCompletionPipe-1.html) that has native support of `IAsyncEnumerable<T>` as well as channel-like methods `WaitToReadAsync` and `TryRead`.

**Comment by bartonjs** [comment]
Looks good as proposed

```c#
namespace System.Threading.Tasks;

public class Task
{
    public static IAsyncEnumerable<Task> WhenEach(params Task[] tasks);
    public static IAsyncEnumerable<Task> WhenEach(params ReadOnlySpan<Task> tasks);
    public static IAsyncEnumerable<Task> WhenEach(IEnumerable<Task> tasks);

    public static IAsyncEnumerable<Task<TResult>> WhenEach(params Task<TResult>[] tasks);
    public static IAsyncEnumerable<Task<TResult>> WhenEach(params ReadOnlySpan<Task<TResult>> tasks);
    public static IAsyncEnumerable<Task<TResult>> WhenEach(IEnumerable<Task<TResult>> tasks);
}
```

**Comment by dahlbyk** [comment]
Nit: missing `<TResult>`:

> ```diff
> +   public static IAsyncEnumerable<Task<TResult>> WhenEach<TResult>(params Task<TResult>[] tasks); // params for now; move it to ReadOnlySpan overload when that syntax is possible
> +   public static IAsyncEnumerable<Task<TResult>> WhenEach<TResult>(params ReadOnlySpan<Task<TResult>> tasks); // params when possible
> +   public static IAsyncEnumerable<Task<TResult>> WhenEach<TResult>(IEnumerable<Task<TResult>> tasks);
> ```

**Comment by alrz** [comment]
@svick

> using `IAsyncEnumerable<T>` returning the original tasks is the better approach today.

I wonder what is the benefit here. Wouldn't IEnumerable be cheaper?

At first look I thought this is going to return the value instead of the wrapper because we're awaiting that one on MoveNextAsync.
```cs
public static IAsyncEnumerable<TResult> WhenEach<TResult>(IEnumerable<Task<TResult>> tasks)
```

**Comment by stephentoub** [comment]
> I wonder what is the benefit here. Wouldn't IEnumerable be cheaper?

You'd block synchronously in MoveNext waiting for the next task to complete.

> At first look I thought this is going to return the value instead of the task because we're awaiting that one on MoveNextAsync.

It's returning the completed task, just like with WhenAny. That gives the consumer the ability to examine / use the completed Task however they like.

**Comment by alrz** [comment]
@stephentoub 

> You'd block synchronously in MoveNext waiting for the next task to complete.

If I'm not mistaken, `OrderByCompletion` returns a `IEnumerable<Task<T>>`  which you're indeed be awaiting to examine / use however you'd like. Note there's no blocking -- MoveNext returns immediately since we're enumerating an array.

> It's returning the completed task, just like with WhenAny. That gives the consumer the ability to examine / use the completed Task however they like.

So what I'm saying is that `IEnumerable<Task<T>>` will give you exactly that, `IAsyncEnumerable` seems like a auxiallty helper when you want to stop on first exception.

```cs
IAsyncEnumerator<T> WhenEach(Tasks<T>[] tasks) {
  foreach (Task<T> t in tasks.OrderByCompletion())
    yield return await task;
  }
}

**Comment by stephentoub** [comment]
@alrz, how would you propose for `MoveNext` to immediately complete such that `Current` could return the next `Task` even when no next task had yet completed? The only way to do that would be to allocate a new Task that could be returned immediately, with a different object identity than the original task, and then whenever the next task completes, marshal its results/exception/cancellation information to that proxy. At that point, you've significantly increased the cost and you've lost the ability to compare Tasks by reference.

**Comment by alrz** [comment]
Note I'm talking about the the implementation in AsyncEx 

https://github.com/StephenCleary/AsyncEx/blob/0361015459938f2eb8f3c1ad1021d19ee01c93a4/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L184

**Comment by spektor56** [comment]
> > Note I'm talking about the the implementation in AsyncEx
> > https://github.com/StephenCleary/AsyncEx/blob/0361015459938f2eb8f3c1ad1021d19ee01c93a4/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L184
> 
> Which allocates a new TCS / Task for every input: https://github.com/StephenCleary/AsyncEx/blob/0361015459938f2eb8f3c1ad1021d19ee01c93a4/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L211-L213

Any way to use this method with a timeout if no tasks return fast enough?  With the old way I just do something like:

`var cts = new CancellationTokenSource();
var timeout = Task.Delay(10000, cts.Token);
var result = await Task.WhenAny(Task.WhenAny(connectionRequests), timeout).ConfigureAwait(false);

if (result != timeout)
{
    ...
}
else
{
    ...
}`

**Comment by spektor56** [comment]
@stephentoub 
Any way to use this method with a timeout if the next task doesn't return in the allotted time?  With the old way I just do something like:

```csharp
 while (connectionRequests.Count > 0)
 {
  var cts = new CancellationTokenSource();
  var timeout = Task.Delay(10000, cts.Token);
  var result = await Task.WhenAny(Task.WhenAny(connectionRequests), timeout).ConfigureAwait(false);
  
  if (result != timeout)
  {
      ...
  }
  else
  {
      ...
  }
}
```

I'm not seeing any way to add a timeout with the new method that would result in much cleaner code, thanks.  I had the code like this before because in older versions of .NET some ping requests would just hang around forever and never return in Android so I just this 10 second timeout to handle that case.
