### ISSUE TITLE
[Analyzer Proposal]: Create immutable types once

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#61961]
### Background and motivation

An analyzer that flags property getters that create an immutable array with the same elements every time they're accessed.

Elements are considered "the same" iif each element matches one of the following:

1. A constant value.
2. A static readonly reference
3. An interpolated string where each interpolation part is either a constant or a readonly reference (has a potential side effect if the culture changes between getter calls?).

This will apply to all collections in `System.Collections.Immutable` namespace.

### API Proposal

```csharp
private static readonly string s_readonlyField = "Read only";
public ImmutableArray<string> Violation => ImmutableArray.Create("Constant string", s_readonlyField); // Report diagnostic.

// Suggested code fix:
private static readonly string s_readonlyField = "Read only";
public ImmutableArray<string> Violation { get; } = ImmutableArray.Create("Constant string", s_readonlyField);
```

### Open questions

- Should the arrow syntax only be reported? or also report for something like:

    ```csharp
    public ImmutableArray<string> Violation
    {
        get
        {
            return ImmutableArray.Create("Constant string");
        }
    }
    ```

### API Usage

N/A

**Comment by Youssef1313** [comment]
@buyaa-n I didn't find a template for code analyzers, so I used the API proposal template. The label should probably be corrected to `code-analyzer`

**Comment by eiriktsarpalis** [comment]
I don't think this would be a valid suggestion for every use case. In certain cases authors may want to avoid pre-allocating instances when instantiating the parent class (e.g. because it has too many such properties and it's rare that all of them are being invoked, and more than once). In some cases it might make sense to lazily instantiate the value, i.e.
```C#
private ImmutableArray<string>? _cachedValue;
public ImmutableArray<string> Property => _cachedValue ??= CreatePropertyValue();
```
but often even that might not be appropriate, simply because the parent object retains a reference to the allocation even though it shouldn't. Caching the value really depends on class design considerations such as object lifetime, whether calling the property is on the hot path of an application, etc. Concerns that an analyzer can't really reason about.

I'll add that applications using immutable collections generally tend to be allocation heavy anyway, so it's not clear to me how this would provide significant impact in performance.

**Comment by Youssef1313** [comment]
The analyzer would only report getters that only have `ImmutableCollection.Create(..)` call. ie, if there is any caching involved like `_cachedValue ??= ImmutableCollection.Create(...)`, there won't be a diagnostic.

I'm not aware if there are specific scenarios where this could provide significant perf impact. I believe one can "craft" a sample code where this would potentially provide improvement, but no idea about that in real-world scenarios.

For example:

![image](https://user-images.githubusercontent.com/31348972/143023191-769dea42-5b87-407a-bbe0-b73c42c4c6f0.png)

(I know this is not the appropriate way to benchmark, but shows the idea)

**Comment by eiriktsarpalis** [comment]
> I'm not aware if there are specific scenarios where this could provide significant perf impact.

Consider a scenario where a class contains 100 such properties, but only a handful of properties are called during the object's lifetime. If an analyzer encouraged the user to move instantiation of all 100 values to the constructor, I suspect there would be substantial perf impact.

**Comment by Youssef1313** [comment]
In that case, instead of:

```csharp
private static readonly string s_readonlyField = "Read only";
public ImmutableArray<string> Violation => ImmutableArray.Create("Constant string", s_readonlyField);
```

shouldn't the user do the following?

```csharp
private ImmutableArray<string>? _violation;

private ImmutableArray<string> Initialize() => _violation ?? _violation = ImmutableArray.Create("Constant string", s_readonlyField);

private static readonly string s_readonlyField = "Read only";
public ImmutableArray<string> Violation => Initialize();
```

**Comment by eiriktsarpalis** [comment]
It depends on whether they want to encapsulate the instance in the parent class. What should an analyzer be recommending?

**Comment by Youssef1313** [comment]
@eiriktsarpalis It could offer no codefix (and be disabled by default if there are non-actionable scenarios), and the description and documentation should be clear about what action to take and when.

Alternatively, it could offer both code fixes that're discussed (one that's recommended for many properties that are rarely accessed, and the other that's recommended for few properties that are repeatedly accessed).

My current doubts/questions would be:

- Do the 2 codefixes cover every scenario? or there are still unactionable scenarios?
- Would the caching approach always work well?

**Comment by eiriktsarpalis** [comment]
There is sufficient ambiguity in this space, making me believe that this might not be a suitable space to introduce an analyzer. I defer to @buyaa-n on what our guidelines are in such cases.

On a separate point, the semantics of property getters are fairly well understood, and developers deal with similar considerations when writing property getters returning read-only or even mutable types. If we're bringing an analyzer into this space, would it make sense to extend it beyond just immutable collections?

**Comment by jkotas** [comment]
> There is sufficient ambiguity in this space, making me believe that this might not be a suitable space to introduce an analyzer.

+1

Another scenario to consider is a long-lived object and the properties are typically called at most once; or the properties are called rarely and the value is typically short-lived. It is better to let garbage collector to collect the values and re-create them as necessary.

Caching is hard.
