### ISSUE TITLE
The purpose of the ref folder in dotnet/runtime source

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/runtime#61965]
What's the purpose of the ref folder in dotnet/runtime source? Thanks!

![image](https://user-images.githubusercontent.com/11468733/143030674-e51e75b8-b338-43ee-9d75-9c6c9c1cedcd.png)

**Comment by stephentoub** [comment]
It contains the source for the reference assembly for that library.  The reference assembly is like a header file in C; it provides the APIs but no implementation, and is what's used at build-time to build against the library, regardless of what implementation will actually be used for those APIs at run-time.

**Comment by CwjXFH** [comment]
So after compilation, the user will only see the API specified in the ref folder, is right?

**Comment by stephentoub** [comment]
When a dev builds their code, the compiler is given the reference assembly as the dependency.
