### ISSUE TITLE
The value of the parameter cannot be changed when debugging the WASM project. 

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#61974]
### Description

Changing a value during a debugger breakpoint does not work in a Blazor WASM project. This was found as part of exploratory testing.

### Reproduction Steps

**Repro Steps**
1. Create a Blazor WASM 6.0 project.
1. Open Pages/Counter.razor, place a breakpoint at method @code{}.
1. Run the project with F5
1. Click Counter>Click me on webpage 
1. After the breakpoint get hit on Counter.razor 
1. Change the value of currentCount to 8

### Expected behavior

Value does not change

### Actual behavior

**Actual Result**

The value of currentCount can be changed

![DebugBlazor](https://user-images.githubusercontent.com/55483444/140882132-422bd9dd-62a0-4ef8-91a6-2b53f81011cf.gif)

**Comment by thaystg** [comment]
I have already investigated an opened an issue for VS team, this works correctly on chrome. This should be fixed on JS debugger side.
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1366427/

**Comment by thaystg** [comment]
Created another issue in JS Debugger repo: https://github.com/microsoft/vscode-js-debug/issues/1143
