### ISSUE TITLE
ANSICodePage returns zero for Traditional_Spanish_CI_AS collation

### ISSUE THREAD

**Issue by Kaur-Parminder** [dotnet/runtime#61977]
### Description

CultureInfo.GetCultureInfo(1035).TextInfo.ANSICodePage returns 0 for .Net6 and returns 1252 for .Net5.

### Reproduction Steps

- Run this code with .net 6  
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0#examples

- Add myCItrad.TextInfo.ANSICodePage to code to see value.

### Expected behavior

Same as .Net5, it should return 1252.

### Actual behavior

returns 0.

**Comment by Kaur-Parminder** [comment]
@tarekgh Can you specify list of collations that will be impacted by this change? You have mentioned in PR cultures which have alternative sorts. Is there way to map with theses patterns https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver15#examples-of-collation-options?

**Comment by tarekgh** [comment]
@Kaur-Parminder here is the list you are looking for.

```
    de-DE_phoneb
    es-ES_tradnl
    hu-HU_technl
    ja-JP_radstr
    ka-GE_modern
    x-IV_mathan
    zh-CN_phoneb
    zh-CN_stroke
    zh-HK_radstr
    zh-MO_radstr
    zh-MO_stroke
    zh-SG_phoneb
    zh-SG_stroke
    zh-TW_pronun
    zh-TW_radstr
```

**Comment by Kaur-Parminder** [comment]
@tarekgh I see this fix has been moved 7.0.0 release, Can it be backported to .Net 6?

**Comment by Kaur-Parminder** [comment]
@tarekgh I believe the issue exist with Default sort Collations as well e.g   0x10407 (GERMAN_PHONE_BOOK)

**Comment by tarekgh** [comment]
>  I see this fix has been moved 7.0.0 release, can it be backported to .NET 6?

How difficult is it to work around this? I guess it should be simple to do so. If you can talk more about your scenario, we can look at porting the fix to .NET 6.0 if it is really a blocker for you.

> I believe the issue exist with Default sort Collations as well e.g 0x10407 (GERMAN_PHONE_BOOK)

0x10407 is the `de-DE_phoneb` which is the alternative sort and not the default sort. It is listed as the first item I mentioned in https://github.com/dotnet/runtime/issues/61977#issuecomment-978125240. The default sort would be LCID `0x407` which is `de-DE`

**Comment by Kaur-Parminder** [comment]
@tarekgh Thanks for correcting me. I see, I have read the collations incorrectly.

This issue was reported because I am seeing issues coming in and SqlClient Driver for users switching to .Net6. The Driver is using CodePages which are now returning value 0.

https://github.com/dotnet/SqlClient/issues/1319#issue-1018513222
https://github.com/dotnet/SqlClient/issues/1396#issue-1058465574
https://github.com/dotnet/efcore/issues/26812#issue-1062167457

There is high possibility to see more coming in, as they are popular collations. Regarding workaround, Driver changes for just .Net6 wont be appropriate.  If we can know if there is going to be patch release that will help us to inform Driver users.

**Comment by tarekgh** [comment]
@Kaur-Parminder thanks for the info. I reopened the issue to look investigate if we can port the fix to .NET 6.0.

**Comment by tarekgh** [comment]
Fixed through the PR https://github.com/dotnet/runtime/pull/62155
