### ISSUE TITLE
Can't Publish Runtime Test Projects

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#61978]
This is mostly an issue for my own tracking purposes.  As part of getting the wasm-aot run time tests up, I have been trying to get individual projects to publish.

Changing the default target to "Publish" and the test build will complete succesfully, but it will not publish all required assemblies.

It seems like this is because the `ProcessFrameworkReferences` does not run.

And that in turn seems to be because `DisableImplicitFrameworkReferences=true`.

However, setting it to false results in this error:

```
/Users/naricc/workspace/runtime-wasm-aot-runtime-tests/.dotnet/sdk/6.0.100-rc.1.21430.12/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'browser-wasm'. [/Users/naricc/workspace/runtime-wasm-aot-runtime-tests/src/tests/simple/simple.csproj] [/Users/naricc/workspace/runtime-wasm-aot-runtime-tests/src/tests/build.proj]
```

Wasm-aot test prototype here:
https://github.com/dotnet/runtime/pull/57963

**Comment by naricc** [comment]
@radical This is an issue I crated a while ago to document/track problems I saw in getting the runtime test working with wasm-aot. Not sure if this is still relevant as I have not been working on them. Should I close this out or do you want it?

**Comment by radical** [comment]
You can close this.
