### ISSUE TITLE
MemoryStream.Read() throws ArgumentOutOfRangexception in .NET 6 but ArgumentException in .NET 5

### ISSUE THREAD

**Issue by johnnypham** [dotnet/runtime#61994]
### Description

When caling [Read()](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream.read?view=net-6.0) and "offset subtracted from the buffer length is less than count", an `ArgumentException` should be thrown. In .NET 6, an `ArgumentOutOfRangeException` is being thrown.

### Reproduction Steps

byte[] b = new byte[16];
MemoryStream ms = new MemoryStream();
ms.Read(b, b.Length, b.Length);

### Expected behavior

`ArgumentException` should be thrown in .NET 6, just like .NET 5.

### Actual behavior

`ArgumentOutOfRangeException` is thrown in .NET 6.

**Comment by stephentoub** [comment]
ArgumentOutOfRangeException is an ArgumentException. We consider it an acceptable change to throw a more derived exception than was previously being thrown.

**Comment by johnnypham** [comment]
That's what I was thinking but the docs should be updated?
