### ISSUE TITLE
System.Runtime.InteropServices.ExternalException occurs while displaying base64string in WinForms application 

### ISSUE THREAD

**Issue by vijayarasan** [dotnet/runtime#61997]
* .NET Core Version: 5.0 

* Have you experienced this same bug with .NET Framework?:  Yes

**Problem description:**

I have tried to display the base64string in my WinForms application by overriding the OnPaint method. Please refer to the below screenshot,

![Drawstring](https://user-images.githubusercontent.com/58214164/143048482-431385f6-58fa-4e46-b583-a182a1494d68.png)

**Minimal repro:**
Step 1: Run the Sample

**Observed behavior:**
System.Runtime.InteropServices.ExternalException occurs while displaying base64string in WinForms application 

**Expected behavior:**
Displaying base64string without making an exception in WinForms application 

**Sample Link:**  
[Sample.zip](https://github.com/dotnet/winforms/files/7588839/Sample.zip)

**Comment by vijayarasan** [comment]
Hi @RussKie,

Thanks for the update.

Here, just I have mentioned space for replicating the issue. Rectangle Height will be calculated based on the text and TextWrapping enable in my scenario. In this case, also we are facing the same issue. Can you please share any ideas to resolve this issue?
 
 Regards,
 Vijayarasan S

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/interop-contrib We should confirm where the error is coming from and ensure we are offering the best exception details.

@vijayarasan As far as addressing this, @RussKie seems to have indicated the root cause of the reason for the exception. For further help in how to mitigate this I would start a conversation in https://github.com/dotnet/winforms.

**Comment by AaronRobinsonMSFT** [comment]
@vijayarasan I'm not observe an exception in .NET 5 or .NET 6. The main window shows as expected, but the string doesn't show up as described but there is no exception. Can you confirm you are still an exception? If so, what is your OS and the target bitness of the process?

**Comment by AaronRobinsonMSFT** [comment]
@vijayarasan Please let us know if this is still causing issues.
