### ISSUE TITLE
Microsoft.Win32.Registry has no dotnet 6.0.0 nuget package release

### ISSUE THREAD

**Issue by jetersen** [dotnet/runtime#62009]
### Description

Not sure where whether this is the best place to report the issue.

[Microsoft.Win32.Registry@6.0.0-preview.5.21301.5](https://www.nuget.org/packages/Microsoft.Win32.Registry/6.0.0-preview.5.21301.5) is the newest preview while other like 
[Microsoft.Win32.SystemEvents](https://www.nuget.org/packages/Microsoft.Win32.SystemEvents/) and [Microsoft.Win32.Registry.AccessControl](https://www.nuget.org/packages/Microsoft.Win32.Registry.AccessControl/) has a 6.0.0 version.

### Reproduction Steps

N/A

### Expected behavior

Microsoft.Win32.Registry has a 6.0.0 when Microsoft.Win32.Registry.AccessControl 6.0.0 version exist

Especially since Microsoft.Win32.Registry.AccessControl depends on a 5.0.0 of Microsoft.Win32.Registry

Is it expected to use Microsoft.Win32.Registry use 5.0.0 version?

### Actual behavior

Use Microsoft.Win32.Registry@5.0.0 ?

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/bf1797ad3e2f73e640d5648044f9f053c17b05fe/src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj#L5

The project no longer build for older target frameworks, so there's no need to publish a nuget version.

**Comment by jetersen** [comment]
So potential you can remove the dependency in a project?

**Comment by jetersen** [comment]
Yup, in dotnet 6 you can remove the dependency.

Closing the issue.
