### ISSUE TITLE
Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#62005]
superpmi replay pipeline has been failing with this assert for a while on Linux/Windows arm64:

    ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\lsra.cpp (6423) - Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS' in 'Internal.Cryptography.PemKeyHelpers:TryExportToEncryptedPem(System.Numerics.Vector`1[Single],System.ReadOnlySpan`1[Char],System.Security.Cryptography.PbeParameters,TryExportEncryptedKeyAction`1[Vector`1],System.Span`1[Char],byref):bool' during 'LSRA allocate' (IL size 128)
    ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\lsra.cpp (6423) - Assertion failed 'block->bbJumpKind == BBJ_NONE || block->bbJumpKind == BBJ_ALWAYS' in 'Internal.Cryptography.PemKeyHelpers:TryExportToPem(System.Numerics.Vector`1[Single],System.String,TryExportKeyAction`1[Vector`1],System.Span`1[Char],byref):bool' during 'LSRA allocate' (IL size 121)

https://dev.azure.com/dnceng/public/_build?definitionId=1055&_a=summary

@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@kunalspathak Have you made any progress on this? It is still failing. (Oddly, there were some clean runs, but perhaps that's because the collections were bad for a while.)

**Comment by kunalspathak** [comment]
Haven't made any progress on test issues yet. I will see if I can find some time tomorrow to see what is the problem.
