### ISSUE TITLE
json config file has modified,but dotnet 6 can't reload on change when run in k8s configmap

### ISSUE THREAD

**Issue by yaphet266** [dotnet/runtime#62004]
### Description

I used k8s's configmap as the configuration. After modifying the configmap, I saw that appsettings.json in the container had been modified, but dotnet 6 did not reload the configuration file and could not read the new configuration in the program.

### Reproduction Steps

1.create a aspnet core application
2.deploy on k8s

### Expected behavior

reload config where configmap mapping json file modified

### Actual behavior

not reload

**Comment by hez2010** [comment]
Have you set `reloadOnChange` to `true`?

**Comment by yaphet266** [comment]
> Have you set `reloadOnChange` to `true`?

Already set，Normal under Windows，but use k8s configmap abnormal。Probably because configmap uses file links。

**Comment by maryamariyan** [comment]
@yaphet266 could you please share a repro code?

**Comment by yaphet266** [comment]
> @yaphet266 could you please share a repro code?

I have solved the problem，I found that setting the following environment variables in dockerfile can solve this problem。
ubuntu20.04
`ENV DOTNET_USE_POLLING_FILE_WATCHER true`
