### ISSUE TITLE
Regex Bug - Failing Basic Operations

### ISSUE THREAD

**Issue by TristanRhodes** [dotnet/runtime#62017]
### Description

This test should perform a basic regex range check, but is failing both locally and in cloud builds.

```
        [Theory]
        [InlineData("[A-Z]", "B")]
        [InlineData("[A-Z]", "Y")]
        [InlineData("[0-9]", "1")]
        [InlineData("[0-9]", "8")]
        [InlineData("\\d", "9")]
        public void BrokenRegex(string regex, string check)
        {
            Regex.IsMatch(regex, check)
                .Should().BeTrue();
        }
```

### Reproduction Steps

```
       [Theory]
        [InlineData("[A-Z]", "B")]
        [InlineData("[A-Z]", "Y")]
        [InlineData("[0-9]", "1")]
        [InlineData("[0-9]", "8")]
        [InlineData("\\d", "9")]
        public void BrokenRegex(string regex, string check)
        {
            Regex.IsMatch(regex, check)
                .Should().BeTrue();
        }
```

### Expected behavior

Should pass

### Actual behavior

Does not pass

### Regression?

I have used Regex extensively in past versions of .net (and I believe this one). This is fundamental to Regex.

### Configuration

.Net5.0
Windows 10, 10.0.19042 Build 19042
X64

### Other information

https://github.com/TristanRhodes/RegexBug

**Comment by stephentoub** [comment]
You have the arguments to IsMatch reversed: the first argument should be the input, the second should be the pattern.

**Comment by TristanRhodes** [comment]
asdf

**Comment by TristanRhodes** [comment]
🤦
