### ISSUE TITLE
CI failure (net48 x86): GenerateResource.cache is being used by another process

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#62028]
```
.dotnet\sdk\6.0.100-rc.2.21505.57\Microsoft.Common.CurrentVersion.targets(3264,5):
error MSB3101: (NETCORE_ENGINEERING_TELEMETRY=Build)
Could not write state file
"D:\a\_work\1\s\artifacts\obj\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.SourceGeneration.csproj.GenerateResource.cache".
The process cannot access the file
'D:\a\_work\1\s\artifacts\obj\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.SourceGeneration.csproj.GenerateResource.cache'
because it is being used by another process.
```

The failure happened in the CI of this PR: https://github.com/dotnet/runtime/pull/59850

It was the net48 x86 leg:
https://github.com/dotnet/runtime/pull/59850/checks?check_run_id=4316507944

Here's the log:
https://dev.azure.com/dnceng/public/_build/results?buildId=1485041&view=logs&j=79ebbb2e-07f2-5457-c5e5-132dd7ee4ba8&t=19d75d51-494c-5498-c708-7a0aae08aa93

@elinor-fung @jkoritzinsky

---

Variant: "File already exists" instead of "File used by another process":
https://dev.azure.com/dnceng/public/_build/results?buildId=1490663&view=logs&j=924a68e5-ba21-56d0-bfb9-0b068c6fae9a&t=8c8cf4a0-c3ab-58ea-a108-e7df9b47cd9f&l=2889

```
.dotnet/sdk/6.0.100/Microsoft.Common.CurrentVersion.targets(2304,5): error MSB3101:
(NETCORE_ENGINEERING_TELEMETRY=Build) Could not write state file
"/Users/runner/work/1/s/artifacts/obj/Microsoft.Interop.SourceGeneration/netstandard2.0-Debug/Microsoft.Interop.SourceGeneration.csproj.AssemblyReference.cache".
The file
'/Users/runner/work/1/s/artifacts/obj/Microsoft.Interop.SourceGeneration/netstandard2.0-Debug/Microsoft.Interop.SourceGeneration.csproj.AssemblyReference.cache'
already exists.
```

**Comment by jkoritzinsky** [comment]
This is part of the build race. I’ll get this fixed after we update to the RTM SDK.

**Comment by carlossanlop** [comment]
Thanks @jkoritzinsky .

I found a very similar failure in another PR. This time, it's not the `*.cache` file that is being used, but the `DllImportGenerator.dll` itself:

https://github.com/dotnet/runtime/pull/62134/checks?check_run_id=4370120061

Affected legs:
- Libraries Build windows allConfigurations x64 Debug ([log](https://dev.azure.com/dnceng/public/_build/results?buildId=1490639&view=logs&j=81a0f8c2-d4db-561f-9b8e-3f045280d7fe&t=2a104984-c43b-5b93-1361-6bd8a1e96b04&l=1189))
- Libraries Build windows net48 x86 Release ([log](https://dev.azure.com/dnceng/public/_build/results?buildId=1490639&view=logs&j=79ebbb2e-07f2-5457-c5e5-132dd7ee4ba8&t=19d75d51-494c-5498-c708-7a0aae08aa93&l=1001))

Error message:
```
CSC(0,0): error CS2012: (NETCORE_ENGINEERING_TELEMETRY=Build)
Cannot open 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Debug\Microsoft.Interop.DllImportGenerator.dll' for writing --
'The process cannot access the file 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Debug\Microsoft.Interop.DllImportGenerator.dll'
because it is being used by another process.'
```
