### ISSUE TITLE
[API Proposal]: Make BigInteger implement IConvertible

### ISSUE THREAD

**Issue by paulirwin** [dotnet/runtime#62022]
### Background and motivation

API proposal with motivation as a new take (with rationale) on #36264.

Currently, the following code fails because BigInteger does not implement IConvertible, even though its value is easily convertible to `int` (each line in example below ran in `dotnet repl`):

```C#
using System.Numerics;
var bi = new BigInteger(123);
Convert.ToInt32(bi) // fails
var t = typeof(int);
Convert.ChangeType(bi, t) // also fails
```

The error message of the first failure is:
```
System.InvalidCastException: Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.IConvertible'.
```

In order to make runtime conversion to other integer (or even non-integer) values possible, BigInteger should implement `IConvertible`.

Rationale and use case: I have created a Lisp-based (and Scheme-based) interpreted/dynamic language on .NET called [Lillisp](https://github.com/paulirwin/lillisp). To implement Scheme's rational number types (i.e. `1/3`), I am using the [Rationals](https://github.com/tompazourek/Rationals) library, which implements the numerator and denominator as BigIntegers. This is useful for rational/integer division, such as `(/ 3 4 5)` which yields `3/20`, where 3 and 20 are BigIntegers. Implementing the Scheme `numerator` and `denominator` functions is therefore trivial, they just return the BigInteger `.Numerator` and `.Denominator` properties of the Rational instance respectively. The problem is that the result of this call cannot be passed as-is to a method taking an int, for example. Lillisp has a `cast` function (aside: this should probably be renamed to `convert` or something) that takes a value and a runtime type and calls `Convert.ChangeType`, and I expected `(cast (numerator (/ 3 4 5)) Int32)` to yield the Int32 value 3, but instead it fails because BigInteger is not IConvertible. While I can add methods to explicitly convert a BigInteger to other types, or implement dynamic casting via IL Emit, it would be nice to be able to do the runtime conversion in the same way that other integer types can be done. The BigInteger type already has explicit cast operators for most if not all of the IConvertible destination types, so this would be a natural fit to make BigInteger act like other integer types. This sounds similar to the Powershell language concerns of using BigInteger in #36264.

### API Proposal

```C#
namespace System.Numerics
{
    // some attributes...
    public readonly struct BigInteger : ISpanFormattable, IComparable, IComparable<BigInteger>, IEquatable<BigInteger>, IConvertible
    {
        // ... implement IConvertible members
    }
}
```     

The IConvertible members could possibly just delegate to the explicit cast operators that already exist on BigInteger.

### API Usage

```C#
var bi = new BigInteger(123);
var i = Convert.ToInt32(bi);
// or
var ci = Convert.ChangeType(bi, typeof(int));
```     

### Alternative Designs

Unsure of what alternatives there could be to this change.

### Risks

Adding an interface to BigInteger could be considered a breaking change.

**Comment by GrabYourPitchforks** [comment]
Possible dupe of https://github.com/dotnet/runtime/issues/36264? See also https://github.com/dotnet/runtime/issues/936 for some discussion of why `IConvertible` was not applied to the `System.Half` type when it was added.

**Comment by paulirwin** [comment]
Thanks @GrabYourPitchforks for the response. Yes, it is another take at #36264 as I mentioned, but that item was seemingly closed due to lack of examples and rationale. Since it was closed and locked, I cannot add to that discussion with my rationale, examples, and use case. Also, to clarify, it is *not* a goal of this proposal to add a `ToBigInteger` to IConvertible, just that BigInteger implements IConvertible as-is. That makes this still imperfect, but better than nothing at all.

A better solution would be some sort of method that allows for doing a runtime cast, invoking the explicit cast operator (if present, as it is on BigInteger), without knowing the type in advance or having to dynamically generate IL code at runtime. All I need to do is convert a BigInteger that is boxed to System.Object to some other numeric type (i.e. Int32) without knowing the type at compile time. `Convert.ChangeType` does not work because BigInteger does not implement IConvertible. So if there were some hypothetical method `X` with the signature `System.Object X(System.Object value, System.Type type)` that performed a runtime cast on any object, I would not need BigInteger to implement IConvertible. That would also resolve this [StackOverflow question](https://stackoverflow.com/questions/4925718/c-dynamic-runtime-cast) that has some suboptimal solutions, i.e. involving JSON serialization. The problem with the "dynamic" approach is that dynamic then has to virally be used all throughout the call chain of every function in my application in order for that to work. Not out of the question per se, but I see merit and value in being able to do a runtime cast. If the team is open to that proposal, I can submit a new API proposal (if one does not already exist).

**Comment by paulirwin** [comment]
Upon further reflection on this, I cannot reconcile this change with IConvertible not having a symmetric `ToBigInteger` function, which is clearly not going to happen. I'm going to close this issue unless there is interest from others in reopening it.

I'm going to focus my attention on the runtime casting concern, as that is a better solution for my use case. If I end up coming up with a general solution, I may open a separate issue/PR for that.
