### ISSUE TITLE
[mono][bug] mono_alc_from_gchandle return wrong value?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#62052]
### Description

I am embadding monovm,  I write a function `mono_alc_load_assembly_with_partial_name` extend from `mono_assembly_load_with_partial_name` with `alc` argument

when call `mono_image_open_from_data_alc` to load `MonoImage` the `mono_alc_from_gchandle` get the wrong `MonoAssemblyLoadContext` value

### Reproduction Steps

```c#
// I implemented AssemblyLoadContext:
public class PluginLoadContext : AssemblyLoadContext
  {
      
      public PluginLoadContext(string? name, bool isCollectible) : base(name, isCollectible)
      {
      }

      protected override Assembly? Load(AssemblyName assemblyName)
      {
          return PluginLoader.LoadAssembly(assemblyName.Name);
      }
  }
```

```c
// like mono_assembly_load_with_partial_name just pass our ALC, not use default alc
MonoAssembly* 
mono_alc_load_assembly_with_partial_name (void* native_alc, const char *name, MonoImageOpenStatus *status)
{
	MonoAssembly *result;
	MONO_ENTER_GC_UNSAFE;
	MonoImageOpenStatus def_status;
	if (!status)
		status = &def_status;
	MonoAssemblyLoadContext* alc = (MonoAssemblyLoadContext*)native_alc;
	if (!alc)
		alc = mono_alc_get_default();
	result = mono_assembly_load_with_partial_name_internal (name, alc, status);
	MONO_EXIT_GC_UNSAFE;
	return result;
}

// get MonoAssemblyLoadContext though `_nativeAssemblyLoadContext` field
// the internal call
MonoObject* ScriptingManager::LoadAssembly(MonoObject* alc, MonoString* assemblyName)
{
	void* NativeALC = GetNativeALC(alc);
	if (!NativeALC)
		return nullptr;
	MonoImageOpenStatus LoadStatus = MonoImageOpenStatus::MONO_IMAGE_OK;
	const char* AssemblyName = mono_string_to_utf8(assemblyName);
	MonoAssembly* Assembly = mono_alc_load_assembly_with_partial_name(NativeALC, AssemblyName, &LoadStatus);
	mono_free((void*)AssemblyName);
	return (MonoObject*)mono_assembly_get_object(mono_domain_get(), Assembly);
}
```
our code call step
``` c#
// in c#

PluginLoaderContent alc = new PluginLoaderContent ("Engine", true);
// call internal call ScriptingManager::LoadAssembly 
LoadAssembly(alc, "UnrealEngine");

```

![image](https://user-images.githubusercontent.com/5187024/143458337-5159b1ff-f594-4ff5-851a-99b6401e0abd.png)

the native stack variable

1. new PluginLoaderContent  create native ALC, and the alc native address is `0x000001c4bfdf51a0`

![image](https://user-images.githubusercontent.com/5187024/143455671-e5ea3539-9350-49a0-b987-40338e18d88a.png)

2. in the `ScriptingManager::LoadAssembly`, we can see the MonoObject* alc and native alc value is correct.
![image](https://user-images.githubusercontent.com/5187024/143456037-12939ad4-90be-47db-8618-a195d4666607.png)

3. but in the mono_alc_from_gchandle the value is wong: 
![image](https://user-images.githubusercontent.com/5187024/143456569-fc58ffa8-4ab3-40a8-a208-956aed769c16.png)

4. the full call statck:
![image](https://user-images.githubusercontent.com/5187024/143456662-d8d8fec7-8eea-431e-8957-9ae4e8e0949c.png)

### Expected behavior

work correctly

### Actual behavior

crash

### Configuration

build the latest version of release/6.0 branch 
x64 windows desktop

### Other information

no

**Comment by srxqds** [comment]
I found out the problem.
this is because MonoManagedAssemblyLoadContext layout is wrong with Managed AssemblyLoadContext `https://github.com/dotnet/runtime/blob/ff82b6dde9367df1c9eb40d362e701e2d54213a2/src/mono/mono/metadata/object-internals.h#L1413

you can see the coreclr implemented:
https://github.com/dotnet/runtime/blob/74f238de0e96c072b9a6e496d466cda703df2f70/src/coreclr/vm/object.h#L1477

**Comment by lateralusX** [comment]
I believe this construction is a little problematic and you see the symptoms of it. Just adding LayoutKind.Sequential might fix it, but depending on sequential field order in a partial class that is in this case not even sealed, so don't know what guarantees that will give you of complete class layout. You can also see that CoreCLR depends on a different order, that is not inline with how the fields are declared, but how they are layed out by loader. I believe a better way to fix it is to get rid of MonoManagedAssemblyLoadContext and fix mono_alc_from_gchandle to use a cached offset to the nativeAssemblyLoadContext field and then access it based on the offset instead of depending on field order in the class.

**Comment by srxqds** [comment]
hi, @lateralusX  can you have time to review https://github.com/dotnet/runtime/pull/62120 ?

**Comment by lambdageek** [comment]
> Just adding LayoutKind.Sequential might fix it, but depending on sequential field order in a partial class that is in this case not even sealed, 
> ...
> I believe a better way to fix it is to get rid of MonoManagedAssemblyLoadContext and fix mono_alc_from_gchandle to use a cached offset to the nativeAssemblyLoadContext field and then access it based on the offset instead of depending on field order in the class.

Caching the field offset is ok, but we do use `LayoutKind.Sequential` for many other partial classes in CoreLib.  It is also a reasonable approach.

**Comment by srxqds** [comment]
> > Just adding LayoutKind.Sequential might fix it, but depending on sequential field order in a partial class that is in this case not even sealed,
> > ...
> > I believe a better way to fix it is to get rid of MonoManagedAssemblyLoadContext and fix mono_alc_from_gchandle to use a cached offset to the nativeAssemblyLoadContext field and then access it based on the offset instead of depending on field order in the class.
> 
> Caching the field offset is ok, but we do use `LayoutKind.Sequential` for many other partial classes in CoreLib. It is also a reasonable approach.

yes, this is why I fixed it using `LayoutKind.Sequential` in my first pr.

**Comment by lateralusX** [comment]
For this class where we just depend on 1 field, it feels more deterministic to use field offset, since we will not depend on layout issues, and risk of breaking things when adding fields into any of the partial classes.
