### ISSUE TITLE
Cannot execute binary when corerun dir has dll that has a entry point.

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/runtime#6206]
Environment : arm32/linux
Assume that B.exe outputs "B" and A.exe outputs "A".
I simplify the log : 

```
sh> pwd
~/bin/
sh> ls
corerun.exe 
.....
A.exe
Bdir/
sh > ls Bdir
B.exe
sh > ./corerun Bdir/B.exe
"A"
```

It seems that corerun loads all the dll and exe in current directory and execute A.exe since it has a entry point. 
Is it the expected behavior or a bug ?

**Comment by AaronRobinsonMSFT** [comment]
@chunseoklee The implementation of `corerun` has evolved a great deal since 2016 and is now using the same API in all scenarios and I don't see it locally. Please reopen if this is still observed.
