### ISSUE TITLE
Customizing crossgen2 arguments when using PublishReadyToRun

### ISSUE THREAD

**Issue by 0xC0000054** [dotnet/runtime#62065]
Is there a supported way to customize the crossgen2 arguments when using the VS 2022 publish wizard?

The undocumented `<PublishReadyToRunCrossgen2ExtraArgs>`  command works when adding a single argument, but it fails when using multiple arguments separated by spaces.
I am trying to add `--inputbubble` and `--compilebubblegenerics` when publishing a self-contained `win-x86` executable.

**Comment by am11** [comment]
Going by https://github.com/dotnet/sdk/pull/15531, semicolon is correct delimiter. From command line, it would need quoting around the entire value to disambiguate from statement terminator in some scripting languages:
`dotnet build -p:PublishReadyToRunCrossgen2ExtraArgs='--foo; --bar=baz' ...`

**Comment by AntonLapounov** [comment]
The answer is given above.  Please let us know if you have further questions.
