### ISSUE TITLE
 Convert.ChangeType throws exception when converting Double.MaxValue

### ISSUE THREAD

**Issue by mdmoura** [dotnet/runtime#6207]
The following code:

```
    var converted = Convert.ChangeType(Double.MaxValue.ToString(), typeof(Double));
```

Results in the exception:

```
   Value was either too large or too small for a Double.
```

I suppose this is a bug, correct?

**Comment by tannergooding** [comment]
This was resolved in .NET Core 3.0 alongside the floating-point parsing and formatting improvements: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/
