### ISSUE TITLE
fill the mono_alc_get_ambient with right behavior

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#62099]
I found the `mono_alc_get_ambient` is return Default ALC now.
I want to fix with below two steps:
1. check `CurrentContextualReflectionContext`, if it has value return this.
2. return current assemblyloadcontext which loads the assembly.

will it be right?

**Comment by srxqds** [comment]
clear two `get_default_jit_mm()` at this pr: https://github.com/dotnet/runtime/pull/84247

**Comment by SamMonoRT** [comment]
Closing this old issue. Please re-open if you hit in 8.0.x-preview builds.
