### ISSUE TITLE
Dictionary throwing OOM

### ISSUE THREAD

**Issue by rafael-aero** [dotnet/runtime#621]
I've just updated our code-base to the newly released NET Core 3.1, and I'm hitting a strange error in one of our deployments. For reference, running under Linux, on Docker. And definitely not an OOM case, as this is a container with memory limit of >100GB RAM, with the code at this point using less than 2GB.

The issue is being caused in a super simple piece of code:

```csharp
int desiredCapacity = 20_000_000;
var myDict = new Dictionary<StructA, StructB>(desiredCapacity);
```

for a desiredCapacity above a few million, I'm getting an System.OutOfMemoryException thrown on creating the dictionary.

If I instead do not define an initial capacity, and just add the items normally:

```csharp
var myDict = new Dictionary<StructA, StructB>();
foreach(...)
{
    myDict.Add(key, value);
}
```

The exception is thrown instead on the Dictionary.Resize(int newSize, bool forceNewHashCodes) method.

Was trying to review if there were any changes on 3.1 that could have lead to this, and could only find this two new recent changes on Dictionary:

https://github.com/dotnet/runtime/commit/82f2e7b0e6d03c0f5848a046cc1beafd0b329186#diff-29ccab4db2a786b9ddb75a3f38cc41c9

and 

https://github.com/dotnet/runtime/commit/cc3506d8409347308f9843153d72e901e84960b6#diff-29ccab4db2a786b9ddb75a3f38cc41c9

Maybe related to the optimizations on https://github.com/dotnet/coreclr/pull/27149 ?

Any ideas?

**Comment by rafael-aero** [comment]
even more strange, if I wrap this in loop to retry creating the dictionary, everything works fine:

```csharp
Dictionary<StructA, StructB> myDict = null;

while(myDict is null)
{
    try
    {
        myDict = new Dictionary<StructA, StructB>(desiredCapacity);
    }
    catch(OutOfMemoryException)
    {
    
    }
}
```

**Comment by benaadams** [comment]
What size are `StructA` and `StructB`?

**Comment by benaadams** [comment]
It will try to create an array of 
```csharp
public struct Entry
{
    public uint hashCode;
    public int next;
    public StructA key;           // Key of entry
    public StructB value;         // Value of entry
}
```
So for `int desiredCapacity = 20_000_000;` that will be
```csharp
var array = new Entry[2_009_191];
```

**Comment by rafael-aero** [comment]
```csharp
public struct StructA
{
    public ulong A;
    public ulong B;
}
```

and 

```csharp
public struct StructB
{
    public long A;
    public int B;
    public uint C;
    public StructC[] D;
    public StructA E;
    public byte F;
    public int G;
}
```

and StructC is quite similar to StructB.

The really strange thing is that I've other instances of this code running on the exact same setup (in the same and in other machines), with larger number of items on this Dictionary - and no issues there since the update.

**Comment by danmosemsft** [comment]
@rafael-aero is this a 64 bit process?
@jkotas I assume we still have the ~2^31 limit on entries in an array, do we have a limit on the byte size of an array in 64 bit?

**Comment by benaadams** [comment]
72 bytes per `Entry`  so ~145MB per dictionary which should be ok

The two recent changes you highlight are in 5.0 rather than 3.1

**Comment by danmosemsft** [comment]
good point. @rafael-aero what version were you running on when it was working?

**Comment by jkotas** [comment]
> I assume we still have the ~2^31 limit on entries in an array

Yep.

> do we have a limit on the byte size of an array in 64 bit?

No.

> this is a container with memory limit

You may want to call https://docs.microsoft.com/en-us/dotnet/api/system.gc.getgcmemoryinfo?view=netcore-3.0 to see whether the memory limit that the GC sees is what is expected.

**Comment by rafael-aero** [comment]
64bit, aspnet 3.1 bionic docker image, running on a RHEL 6 host under kubernetes.

Rolling back to an earlier 3.0 Docker image from today works fine, and the exact same setup (with different data) works fine on the same host.

Other deployments were updated already and didn't see any issues. It's definitely not an OOM issue - this is a container sized to 130GB RAM limit, and at the point this happens we've approximately 2GB allocated. I'll try moving this Dictionary allocation earlier in the setup to see if I hit anything interesting.

Already tried retrying it, changing the required capacity, but both failed so far.

**Comment by rafael-aero** [comment]
GC.GetMemoryInfo gave totally normal numbers. Would have to login again on our client's machine to see the exact numbers, but there was plenty of memory free to be allocated.

**Comment by rafael-aero** [comment]
Think I found the issue, seems to be memory corruption due to a native library call.

We're using https://github.com/warrenfalk/rocksdb-sharp/ as a KV-store, and if I invert the following logic:

```csharp
var count = EstimateSize(); //Uses an iterator over a ColumnFamily to count how many keys we've
var dict = new Dictionary<....>(count);
FillDictionary(dict); //Uses an iterator to fill the dictionary
```

to this:

```csharp
var dict = new Dictionary<....>(100_000_000); //Hard-coded size
FillDictionary(dict);  //Uses an iterator to fill the dictionary
```

it works fine. So this is probably an issue with the RocksDB bindings and/or the native code corrupting something in memory.

I'll try to narrow down to something reproducible over the weekend.  Thanks for the help though!

By the way, one question regarding memory limits under containers and the netcore GC: Is the GC aware of allocations made by the native library when estimating memory pressure? Or do we need to use AddMemoryPressure / RemoveMemoryPressure to make it work?

**Comment by jkotas** [comment]
> Is the GC aware of allocations made by the native library when estimating memory pressure? 

Yes, the GC will calls the underlying OS to get the total memory pressure. GCMemoryInfo.MemoryLoadBytes is the memory pressure number that the GC got wrong the underlying OS.
