### ISSUE TITLE
capturing groups in .NET lookbehind assertions are greedier than their prefixes, unlike other engines

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#62104]
```c#
using System.Text.RegularExpressions;
string patt = @".*(?<=^(\w*)*$)";
foreach (Match m in Regex.Matches("aaab", patt))
{
    Console.WriteLine($"match <{m.ToString()}> [{m.Index} .. {m.Length + m.Index}]");
    Console.WriteLine("groups { " + string.Join(',', ((IEnumerable<Group>)m.Groups).Skip(1).Select(x => x.Value)) + " }");  // skip first group (it's the whole match)
}
```
produces
```
match <> [4 .. 4]
groups {  }
```
On Javascript and Nim it would give equivalent to:
```
match <> [4 .. 4]
groups { aaab }
```
(It's an invalid pattern for PCRE, Python, Java because they apparently require lookbehind assertions to be fixed width)

Perhaps the question here is which is greedy first, the assertion or the prefix? The other engines believe it's the prefix. If I make the assertion lazy: 
```
string patt = @".*(?<=^(\w*)*?$)";
```
then it gives the expected result.

**Comment by joperezr** [comment]
I suppose there are many other differences between our engine and others, but since this behavior is shipped, how do we typically draw the line of where we want to be different with our behavior vs where do we want to make the breaking change for consistency sake? cc: @stephentoub

**Comment by stephentoub** [comment]
Every regex implementation has some behavioral differences.
https://people.cs.vt.edu/~davisjam/downloads/publications/DavisMichaelCoghlanServantLee-LinguaFranca-ESECFSE19.pdf
In this particular case, the question is in a fairly esoteric corner of a feature not widely available.  I suggest we wouldn't want to change behavior here with the goal of compatibility with other engines; if we instead felt the current behavior was clearly a bug and had feedback from developers that this behavior is causing problems, we could choose to fix that behavior and it'd be a happy accident that it aligned with others.

**Comment by danmoseley** [comment]
Fine by me - I mainly just wanted to ensure this was recorded here.
