### ISSUE TITLE
Please add a method to C# standard library to send deleted files to recycle bin

### ISSUE THREAD

**Issue by aks2161989** [dotnet/runtime#62114]
i was astonished to realize that a language as powerful as C# does not have an inbuilt method to send deleted files to the Recycle Bin. [Current solutions require using VB.NET methods](https://stackoverflow.com/a/3282445/6623360). 

Please add such a method to the C# standard library to send deleted files/folders to the recycle bin.

**Comment by gfoidl** [comment]
See also https://github.com/dotnet/runtime/issues/28296 (it's closed, but for reference).

**Comment by danmoseley** [comment]
Part of the sticking point here is that, at least in Windows, Recycle bin is a high level concept that is implemented in the shell (or not implemented at all, in some Windows SKUs). It is built over core OS API that are ignorant of it. We generally avoid depending on high level shell behaviors. There are only [2 places in the core libraries](https://github.com/danmoseley/runtime/tree/8e143ac4f87a2055b21f7f479a3fd7ce695bc580/src/libraries/Common/src/Interop/Windows/Shell32) plus System.Drawing.  One reason is that each place we have done so, the functionality did not map well to Unix (in the case of System.Drawing we are backing out the Unix experiment) or did not map well to mobile. Another reason is that shell level concepts like icons, printers, drag and drop tend to have OS-specific behaviors. These are dealt with better in higher level app models like WPF, Winforms, or MAUI where the app is already either OS-specific or at least has OS-specific behaviors and opinions.

One could argue that Recycle bin does map well across OS, and that it is exposed by the Windows shell as a historical detail or that does not matter. I don't know the answer. However as mentioned in the other issue, this seems like something that could easily be thrown up in a Nuget package, if not simply copy-pasted as a PInvoke snippet, and we have rarely had requests for it so the value of exposing it in the core libraries may be low.

**Comment by danmoseley** [comment]
BTW, the code to paste in would be essentially [this](https://stackoverflow.com/a/3282481/849053) (I didn't test/read it). As you say, it's ugly to add a reference to Microsoft.VisualBasic.dll just for this.

**Comment by stephentoub** [comment]
> As you say, it's ugly to add a reference to Microsoft.VisualBasic.dll just for this.

You don't need to add a reference.  Microsoft.VisualBasic.Core.dll is part of netcoreapp.  Create a new .NET 6 app, paste this in as the entire Program.cs (make zero changes to the csproj), and it "just works".
```C#
using Microsoft.VisualBasic.FileIO;

string tmp = Path.GetTempFileName();
FileSystem.DeleteFile(tmp, UIOption.AllDialogs, RecycleOption.SendToRecycleBin);
```

**Comment by Symbai** [comment]
> > As you say, it's ugly to add a reference to Microsoft.VisualBasic.dll just for this.
> 
> You don't need to add a reference. Microsoft.VisualBasic.Core.dll is part of netcoreapp. Create a new .NET 6 app, paste this in as the entire Program.cs (make zero changes to the csproj), and it "just works".
> 
> ```cs
> using Microsoft.VisualBasic.FileIO;
> 
> string tmp = Path.GetTempFileName();
> FileSystem.DeleteFile(tmp, UIOption.AllDialogs, RecycleOption.SendToRecycleBin);
> ```

This is Windows only, right?

**Comment by stephentoub** [comment]
> This is Windows only, right?

Yes.

**Comment by danmoseley** [comment]
> You don't need to add a reference. Microsoft.VisualBasic.Core.dll is part of netcoreapp.

What I should have said is: add it to the closure that has to be trimmed. I assume it is not otherwise.
