### ISSUE TITLE
[API Proposal]: Add `charsRequired` out parameter to `TryParse` methods

### ISSUE THREAD

**Issue by binarycow** [dotnet/runtime#62115]
### Background and motivation

The current `TryParse` methods assume the entire string is the value (with the exception of `NumberStyles.AllowLeadingWhite` allowing whitespace).

There are use cases where we want to extract a number from the beginning of a string.  If there's a delimiter, and we know what it is, we can slice the `Span`/`string`, and use that - and we're fine.

But, sometimes the delimiter is unknown, or handled by a different section of code.  In those cases, it would be useful to know how many characters were actually required.

### API Proposal

Add the following method to `ISpanParseable<TSelf>`

```C#
static abstract bool TryParse(
    ReadOnlySpan<char> s, 
    out int charsRequired, 
    IFormatProvider? provider, 
    out TSelf result
);
```

Add the following method to `IParseable<TSelf>`

```C#
static abstract bool TryParse(
    [NotNullWhen(true)] string? s, 
    out int charsRequired, 
    IFormatProvider? provider, 
    out TSelf result
);
```

The overloads would then be added to the following types that implement those interfaces:

- `Byte`
- `Char`
- `DateOnly`
- `DateTime`
- `DateTimeOffset`
- `Decimal`
- `Double`
- `Guid`
- `Half`
- `Int16`
- `Int32`
- `Int64`
- `IntPtr`
- `SByte`
- `Single`
- `TimeOnly`
- `TimeSpan`
- `UInt16`
- `UInt32`
- `UInt64`
- `UIntPtr`

### API Usage

Suppose the user provides the input `58+43`

```C#

public bool TryParseAddOperation(ReadOnlySpan<char> text, out int charsRequired, out BinaryOperation operation)
{
    operation = default;
    charsRequired = default;
    if(!int.TryParse(text, out var leftLength, out var leftValue)
        return false;
    text = text[ leftLength.. ];
    if( text[0] != '+' ) 
        return false;
    text = text[ 1.. ];
    if(!int.TryParse(text, out var rightLength, out var rightValue)
        return false;
    charsRequired = leftLength + rightLength + 1;
    operation = new BinaryOperation(leftValue, rightValue, Operator.Add);
    return true;
}

```

### Alternative Designs

1. If the delimiter or possible delimiters are known in advance, slice the span in advance.
2. The user could execute `ToString()` to get the length of the string; though this would allocate another string, and it would not necessarily be the same as the input.

### Risks

Adding the parameter to the interface would be a breaking change.  This change will gain a requirement to implement this overload.

**Mitigation:** `ISpanParseable` and `IParseable` are currently in preview.

**Comment by DaZombieKiller** [comment]
I think it's worth mentioning that [Utf8Parser](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.text.utf8parser) covers this need for UTF-8 text. Maybe a proposal for a `Utf16Parser` type would be enough for this? I've run into this situation several times myself and that would have been sufficient for all of them.

**Comment by binarycow** [comment]
@DaZombieKiller - Using `Utf8Parser` would give me that benefit, yes.  And, I'm unclear on what the `standardFormat` parameter would be (is that why you say we'd need a `Utf16Parser`?).

But that only helps me for the types implemented there.  Adding these methods to this _interface_, however, would give me the benefit on any `ISpanParseable<TSelf>`.

**Comment by jeffhandley** [comment]
@tannergooding what do you think about this? If we want to consider it, we should do so during 7.0.

**Comment by tannergooding** [comment]
This would be future at best. We don't currently have this "concept" for any of the "standard" parsing APIs exposed on various types and the closest thing is what's supported in `Utf8Parser` as indicated above.

Exposing this, especially this late in the cycle would require an entirely "new concept" to be introduced with no chance of vetting the shape or surface.

**Comment by tannergooding** [comment]
This is a similar request to https://github.com/dotnet/runtime/issues/68154 and I'm going to close for similar reasons.

We cannot easily provide a new API from the existing interfaces here nor provide a correct default implementation. This likewise has a few pit of failures in knowing whether such an invalid character was truly invalid or not and therefore whether slicing and reparsing is correct.
