### ISSUE TITLE
Test failure System.IO.FileSystem.Tests.DriveInfoWindowsTests.TestGetDrives

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62119]
Run: [runtime-coreclr libraries-jitstress 20211127.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1488011&view=ms.vss-test-web.build-test-results-tab&runId=42542634&paneView=debug&resultId=104982)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.IO.FileSystem.Tests.DriveInfoWindowsTests.TestGetDrives

```
**Error message:**
```
Assert.Contains() Failure
Not found: 'F'
In value:  <GetValidDriveLettersOnMachine>d__15 ['C', 'D', 'E']


Stack trace
   at System.IO.FileSystem.Tests.DriveInfoWindowsTests.TestGetDrives() in /_/src/libraries/System.IO.FileSystem.DriveInfo/tests/DriveInfo.Windows.Tests.cs:line 66
```

**Comment by danmoseley** [comment]
This test is essentially verifying that this code
https://github.com/danmoseley/runtime/blob/8e143ac4f87a2055b21f7f479a3fd7ce695bc580/src/libraries/System.IO.FileSystem.DriveInfo/tests/DriveInfo.Windows.Tests.cs#L269
does the same thing as this code
https://github.com/danmoseley/runtime/blob/8e143ac4f87a2055b21f7f479a3fd7ce695bc580/src/libraries/System.Private.CoreLib/src/System/IO/DriveInfoInternal.Windows.cs#L11

Eyeballing it, it does. So my guesses are either

1. A drive was concurrently removed/unmapped, possibly by another test running concurrently.
2. Windows is returning flaky results
3. JIT stress is doing something.

I'm guessing 1.

**Comment by danmoseley** [comment]
Looks like this was (re)introduced by https://github.com/danmoseley/runtime/commit/a2af8ae7575f5c7167ee9de10b0da0f5e6091ad6

@carlossanlop what is preventing SetVolumeLabel_OnVirtualDrive_Throws and the tests in DriveInfoWindowsTests from running concurrently? if only DriveInfoWindowsTests would be affected, we can simply move this test into that class.

**Comment by adamsitnik** [comment]
> what is preventing SetVolumeLabel_OnVirtualDrive_Throws and the tests in DriveInfoWindowsTests from running concurrently

It's more or less:

```log
test1: gets list of drives
test2: add/remove temp drive
test1: gets list of drives and compares it against list from step 1
```

I've sent #62134 to disable the parallelization for this test project.

**Comment by danmoseley** [comment]
Right it was a rhetorical question 🙂
