### ISSUE TITLE
Slow first HTTP POST request

### ISSUE THREAD

**Issue by doper-147** [dotnet/runtime#62129]
### Description

We have problem with any first HTTP request on any endpoint.
For testing, we created .NET Core 3.1 console application with this code:

```c#
string xmlData = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tem=\"http://learnwebservices.com/services/tempconverter\"><soapenv:Header/><soapenv:Body><tem:FahrenheitToCelsiusRequest><tem:TemperatureInFahrenheit>30</tem:TemperatureInFahrenheit></tem:FahrenheitToCelsiusRequest></soapenv:Body></soapenv:Envelope>";
for (int i = 1; i <= 5; i++)
{
    DateTime start = DateTime.Now;
    Console.WriteLine($"Request {i} BEGIN");
    HttpClient client = new HttpClient();
    StringContent sc = new StringContent(xmlData);
    var res = await client.PostAsync("https://www.learnwebservices.com/services/tempconverter", sc);
    var xml = await res.Content.ReadAsStringAsync();
    Console.WriteLine($"Request {i} END - {(DateTime.Now - start).TotalSeconds} seconds");
}
```

Application works well on Windows 10, Fedora x64, Debian x64. But if we try it on Debian with Arm32, we're going to get in trouble.

Log here:
```
Request 1 BEGIN
Request 1 END - 59.5454192 seconds
Request 2 BEGIN
Request 2 END - 0.2064596 seconds
Request 3 BEGIN
Request 3 END - 0.1106705 seconds
Request 4 BEGIN
Request 4 END - 0.1015012 seconds
Request 5 BEGIN
Request 5 END - 0.1162864 seconds
```

We also tried HttpWebRequest and generate code from WSDL. Result is same - first request takes long time and next in same app are OK. When I restart application, problem is same with first request.
I tested it with .NET Core 3.1 and with .NET6 - both platforms have same problem.

Here is dotnet --info:
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.413
 Commit:    8387734958

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-arm
 Base Path:   /root/dotnet/sdk/3.1.413/

Host (useful for support):
  Version: 3.1.19
  Commit:  aae002469c

.NET Core SDKs installed:
  3.1.413 [/root/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [/root/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [/root/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Reproduction Steps

Create request with POST on any URL with ARM32 NET Core 3.1.

```c#
for (int i = 1; i <= 5; i++)
{
    DateTime start = DateTime.Now;
    string xmlData = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tem=\"http://learnwebservices.com/services/tempconverter\"><soapenv:Header/><soapenv:Body><tem:FahrenheitToCelsiusRequest><tem:TemperatureInFahrenheit>30</tem:TemperatureInFahrenheit></tem:FahrenheitToCelsiusRequest></soapenv:Body></soapenv:Envelope>";

    Console.WriteLine($"Request {i} BEGIN");
    HttpClient client = new HttpClient();
    StringContent sc = new StringContent(xmlData);
    var res = await client.PostAsync("https://www.learnwebservices.com/services/tempconverter", sc);
    var xml = await res.Content.ReadAsStringAsync();
    Console.WriteLine($"Request {i} END - {(DateTime.Now - start).TotalSeconds} seconds");
}
```

### Expected behavior

First request speed will be same as second request.

### Actual behavior

First request takes long time. Second request and next are quick.

### Regression?

.NET Core 3.1 - bug
.NET6 - bug

### Configuration

Problem is in DEBIAN10 with ARM32 and .NET Core 3.1

**Comment by wfurt** [comment]
Check your NameResolution @doper-147. You can also enable tracing and look at the logs so wee where the time is spent. 
Can you also try it with 6.0? (that has more counters and instrumentation if needed) 
You can also do packet capture to look for anything suspicious. (ports 443+53)

**Comment by doper-147** [comment]
@wfurt Name resolution is ok. In description i wrote, that in .NET6 is same bug. 
I send you code with problem - API in code is public (learnwebservices.com) and below, i am sending strack from linux where is problem (last line wait 59 second with "read(0, "   ).

For more detailed description: wget and curl works fine from same machine where .NET has problem.

Request 1 BEGIN
cacheflush(0x75c400ec, 0x75c400fe, 0)   = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
cacheflush(0x6e71c428, 0x6e71c43a, 0)   = 0
cacheflush(0x6e71b39c, 0x6e71b3a8, 0)   = 0
cacheflush(0x6e71c804, 0x6e71c884, 0)   = 0
read(0,

**Comment by karelz** [comment]
Triage: We should try to reproduce locally (code is above) - @scalablecory can you please help with your RaspberryPi?

**Comment by wfurt** [comment]
The trace is interesting @doper-147. fd 0 should be STDIN, right? And actually TCGETS ioctl is terminal operation....
Can you figure out (with lldb?) where the read is coming from? It does not seems like part of HTTP.
