### ISSUE TITLE
Reconcile naming: RegexGeneratorAttribute to RegexAttribute

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#62123]
Re: https://github.com/dotnet/runtime/issues/62105#issuecomment-981265737.

In the upcoming .NET 7, we have `[GeneratedDllImport]` and `[RegexGenerator]` attributes to annotate partial methods for source generators.

It would be nice to match their names at this early stage, preferably by renaming `[GeneratedDllImport]` to `[DllImportGenerator]`.

**Comment by jkotas** [comment]
We also have prior art shipped in .NET 6:
 - [`JsonSerializableAttribute`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonserializableattribute)
- [`LoggerMessageAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggermessageattribute)

I like that the .NET 6 names that they do include `Generator` or `Generated` at all. It makes them more succinct. Should we stick to this pattern for the new source generators as much as possible?

**Comment by jkotas** [comment]
For interop source generator, we can use this as an opportunity to switch to more platform neutral naming. [`Dll`](https://en.wikipedia.org/wiki/Dynamic-link_library) is Windows-specific. How about calling the attribute `[LibraryImport]`?

**Comment by jkotas** [comment]
Interop source generator API proposal is tracked by #46822 (it is not jn public surface yet). This issue can be used to track what if anything we want to change for RegEx.

**Comment by RussKie** [comment]
> How about calling the attribute `[LibraryImport]`?

More ideas: `[Interop]`, `[InteropImport]`, `[PinvokeImport]`

**Comment by MichalStrehovsky** [comment]
As Jan suggested, let's leave interop discussion in #46822. I moved the [interop suggestions](https://github.com/dotnet/runtime/issues/46822#issuecomment-981315069) into that issue.

**Comment by am11** [comment]
@joperezr, `GeneratedDllImportAttribute` was renamed to `LibraryImportAttribute`: https://github.com/dotnet/runtime/issues/46822. This issue is tracking `RegexGeneratorAttribute`. Should we rename it to `RegexAttribute`?

`RegexAttribute` name is used in [EntLib](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ee775232(v=pandp.10)), but it is a rarely used library even with its NetCore port. If there is a chance of clash, it can be disambiguated using fully qualified names  or with 'using' alias. It is the same situation as when `System.Text.Rune` was added, NStack.Core's `System.Rune` usages had to fully qualified the usages when upgrading projects to .NET 5 (one such project was [gui.cs](https://github.com/migueldeicaza/gui.cs)).

**Comment by joperezr** [comment]
@terrajobst @stephentoub @bartonjs thoughts on the above comment? If we want to change it, now is likely our last chance of doing so.

**Comment by stephentoub** [comment]
RegexGeneratorAttribute is unique amongst LibraryImportAttribute, JsonSerializableAttribute, and LoggingMessageAttribute including "generator" in the name. I'd be ok with RegexAttribute.

**Comment by terrajobst** [comment]
* We'd prefer `GeneratedRegexAttribute`

```diff
 namespace System.Text.RegularExpressions;

 [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
-public partial class RegexGeneratorAttribute : Attribute
+public partial class GeneratedRegexAttribute : Attribute
 {
     // ....        
 }
```
