### ISSUE TITLE
[Question] how to return stack allocated bytes without putting it in the heap?

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62127]
I am pretty sure it's just 256 bytes maximum while the usual case being 7 bytes.
I would like to return them in the manner like I would return a int.

**Comment by gfoidl** [comment]
The stack is "method scoped", so it's gone when the method (i.e. the scope) is left. That's how stack works.
So you can't return stack allocated bytes to the caller.

> like I would return a int.

`int` is a value-type, and it's copied by value. You could create a custom struct, which as being a value-type, can be returned by copy too.

**Comment by Joe4evr** [comment]
Yes, the short answer is "you can't".

However, there is talk of adding a method that is specifically designed for such a purpose: #52065
> These APIs would be `intrinsic` to the JIT [...] specially inlined into the function so the `localloc` scope is that of the calling method

**Comment by svick** [comment]
@Joe4evr The method proposed there violates the "you can't return stack-allocated bytes" principle, but I don't think it will let you violate it yourself, so it wouldn't be useful here.

**Comment by Xyncgas** [comment]
the api looks nice, right n I am just passing in span/,<byte> that's already allocated in stack to the function I am calling, it would be nice if I can just get it from the function I am calling though and I get the method to return int or a struct or something but it's not very convenient when the size of the bytes I am returning is changing but I have a way around it too by using a fixed size buffer and another byte that tells me how many bytes actually returned so basically I am getting a frame back from the function, since I am beating to bush for around 1~16 bytes I should be fine
