### ISSUE TITLE
[API Proposal]: DbDataReader.GetDateOnly and DbDataReader.GetTimeOnly

### ISSUE THREAD

**Issue by cincuranet** [dotnet/runtime#62135]
### Background and motivation

New `DateOnly` and `TimeOnly` datatypes can't be currently directly returned from `DbDataReader` (or `IDataRecord`) (leaving only `GetFieldValue` and maybe `GetProviderSpecificValue`). Adding `GetDateOnly` and `GetTimeOnly` seems like a logical step.

### API Proposal

```C#
public abstract class DbDataReader
{
  public virtual DateOnly GetDateOnly(int i);
  public virtual TimeOnly GetTimeOnly(int i);
}
public interface IDataRecord
{
  DateOnly GetDateOnly(int i);
  TimeOnly GetTimeOnly(int i);
}
```

### API Usage

```C#
reader.GetDateOnly(123);
```

**Comment by roji** [comment]
@cincuranet DateOnly and TimeOnly can already be read by using the generic GetFieldValue method on DbDataReader (this is already supported by Npgsql, Microsoft.Data.Sqlite, MySqlConnector).

The specific GetXXX are largely a relic from before GetFieldValue existed; since supported data types vary across providers, it doesn't really make sense to add Get methods for each type (not to mention that there's no async column reading option like GetFieldValueAsync).

Since DateOnly and TimeOnly are standard BCL types, it may make sense to add convenience methods for them; but I'd lean towards keeping DbDataReader's already large API surface down and not doing so.

**Comment by cincuranet** [comment]
Maybe it would be a good idea to start thinking about obsoleting/deprecating the `GetXxx` methods and steering developers to `GetFieldValue`. 

At the moment the API surface, although big, is showing more cracks and inconsistencies. And there's already enough cracks and inconsistencies in ADO.NET space.

**Comment by roji** [comment]
@cincuranet ADO.NET is indeed a very old API (from the days of .NET 1.0, before the language even supported generics). However, I'm not sure that at this point obsoleting these APIs would have any value - we'd never remove them anyway (that would be a gratuitous and potentially big breaking change), and there's no real harm in users using them: they do work just as well as GetFieldValue where they exist.

**Comment by cincuranet** [comment]
I agree these work well. But it's the pit of success story that would benefit from using better/newer APIs.

**Comment by ajcvickers** [comment]
@roji @cincuranet Maybe we should update the docs to point people to the newer API?

**Comment by cincuranet** [comment]
@ajcvickers Maybe even analyzer.

**Comment by roji** [comment]
> I agree these work well. But it's the pit of success story that would benefit from using better/newer APIs.

In most cases I'd agree, but here I don't see how `GetFieldValue<int>` is actually better than `GetInt32` - both do the exact same thing, so I'm not sure why we'd go to the trouble of writing an analyzer - or cause users the trouble of rewriting their code. We certainly wouldn't have had GetInt32 if we designed ADO.NET from scratch today, but given that it's there and not going away, what's the value here?

**Comment by ajcvickers** [comment]
@roji I think the value is that some types like `DateOnly` don't have one form of methods, and so if you are using `GetDataTime`, it's hard to understand what you have to do to get a `DateOnly`. So it would be a discoverability thing more than anything.

**Comment by ajcvickers** [comment]
@roji By the way, agree we should not obsolete these.

**Comment by roji** [comment]
> @roji I think the value is that some types like DateOnly don't have one form of methods, and so if you are using GetDataTime, it's hard to understand what you have to do to get a DateOnly. So it would be a discoverability thing more than anything.

I guess so, though for a user struggling to find `DbDataReader.GetDateOnly`, I have a hard time imagining them actually getting unblocked by a doc note on e.g. `DbDataReader.GetInt32`. But it's true there's no harm to doing this either.

Adding an analyzer here seems to be very similar to obsoleting - it would raise a warning that would force many users to address it, without a real reason (and I'm again not sure how it would help someone struggling to find `DbDataReader.GetDateOnly`).

**Comment by ajcvickers** [comment]
@roji Is there an "info" level on analyzers? In my mind, the idea is that it's unlikely they are only trying to read `DateOnly` values, so if they already have a `GetString` or similar, and this directs them to use `GetFieldValue<string>` instead, they are now on the right path.

**Comment by cincuranet** [comment]
@ajcvickers Yes, you can create analyzer with default level on info.

**Comment by ajcvickers** [comment]
I don't feel strongly about it.

**Comment by roji** [comment]
We discussed this again, and we don't feel there's enough value to do anything at this point. However, if we see many people struggling with finding GetFieldValue (e.g. for DateOnly/TimeOnly) we can certainly revisit doing an analyzer.
