### ISSUE TITLE
HttpClient behavior difference between .Net 6 and .Net 5

### ISSUE THREAD

**Issue by raweibel** [dotnet/runtime#62136]
### Discussed in https://github.com/dotnet/runtime/discussions/62046

<div type='discussions-op-text'>

<sup>Originally posted by **raweibel** November 25, 2021</sup>
Hello everyone,
we are working on an .Net 6 application that is run on a corproate network which requires proxy authentication using the windows credentials. As we were running into problems using HttpClient, we wrote a small test application and noticed that when running in .Net 5 things work as expected, but in .Net 6 they do not.

**Our test code:**
``` cs
var handler = new HttpClientHandler();
handler.DefaultProxyCredentials = CredentialCache.DefaultCredentials;
var client = new HttpClient(handler);
var response = await client.GetAsync(requestedURL);
Console.WriteLine($"Response: {response.StatusCode}");
```

**Expected result:** 
_Response: Ok_

**Result in .Net 5:**
_Response: Ok_

**Result in .Net 6:**
_Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)_

Does anyone know if this is a known problem? Is there a way to fix this in .Net 6?
</div>
<br>
See the original question in the discussion above. After some further investigation of the error and compairing the logs of both programs (see attachments), it seems that the .NET 6 version fails to deal with the NTLM challenge send by the server, leading to the error. But that is just my interpretation of things.

### Additional information:

**Full Error message in .Net 6:**
```
Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OfficePulse.Test.Program.CurrentTry(String requestedURL) in C:\*REMOVED*\Program.cs:line 50
   at OfficePulse.Test.Program.Main(String[] args) in C:\*REMOVED*\Program.cs:line 34
   at OfficePulse.Test.Program.<Main>(String[] args)
```
**Log files (some info removed)**
[TraceDotNet5_redacted.txt](https://github.com/dotnet/runtime/files/7618086/TraceDotNet5_redacted.txt)
[TraceDotNet6_redacted.txt](https://github.com/dotnet/runtime/files/7618087/TraceDotNet6_redacted.txt)

**Comment by wfurt** [comment]
There is not enough details to make this actionable @raweibel. What platform are you running on? .NET generally uses underlying OS functions so the difference between 5 & 6 is surprising. You can try to set breakpoint in GetOutgoingBlob() and at least check if the `incomingBlob` looks right and it if was properly base64 decode e.g. string-> byte[] was OK. 
The handshake really does not have any sensitive information like credentials (since NTLM is challenge-response).
If you don't want to make public post, send me details to my GH email.

**Comment by raweibel** [comment]
Let me provide you with more details:

The program is running on _Windows 10 Enterprise 20H2 19042.1348_
For the .NET 5 we used _SDK 5.0.403-win-x64_ and for _.NET 6 SDK 6.0.100-win-x64_

Here are the Trace files with the NTLM information:
[TraceDotNet6.txt](https://github.com/dotnet/runtime/files/7621270/TraceDotNet6.txt)
[TraceDotNet5.txt](https://github.com/dotnet/runtime/files/7621271/TraceDotNet5.txt)

I will have a look at what's happening with the `incomingBlob` tomorrow.

**Comment by wfurt** [comment]
ok. the exchange looks reasonable e.g. the last part looks like valid NTLM response. I don't have any theory why we would get SEC_E_INVALID_TOKEN.

**Comment by wfurt** [comment]
I check and there are no NTLM changes comparing to 5.0. 
Changes in connection management would be wisest suspect IMHO. 
It may be worth to check that all the attempts go out on the same connection @raweibel. (with Wireshark) 
cc: @geoffkizer

**Comment by karelz** [comment]
@raweibel I'd be also curious if it fails always (aka 100% repro), or only sometimes.

**Comment by raweibel** [comment]
It happens everytime I run the test application mentioned above. I will see what I can find with Wireshark.

**Comment by geoffkizer** [comment]
> Changes in connection management would be wisest suspect IMHO.

It certainly seems like this is possible, but I don't see any obvious change that would lead to this.

Wireshark trace would help.

**Comment by geoffkizer** [comment]
It could also be related to this change: https://github.com/dotnet/runtime/pull/50763

But again, I don't see specifically how...

**Comment by raweibel** [comment]
Managed to capture a trace (in nethsh as Wireshark is prohibited on the corporate network) and move it over to Wireshark. Never used it before, so I'm not sure what to look for. Here are screenshots of both the Net5 and Net6 traces. Feel free to tell me what else I can provide.

Net 6:
![NET6_Wireshark](https://user-images.githubusercontent.com/15108776/144239334-adfd842e-02c1-4562-9a25-dc502fe1f71e.jpg)
Net 5:
![NET5_Wireshark](https://user-images.githubusercontent.com/15108776/144239337-a94e8783-0c9e-4bfc-908f-846c523b5a62.jpg)

**Comment by geoffkizer** [comment]
I don't see anything particularly weird in that trace. The connection is being reset eventually, but presumably that's because we are getting SEC_E_INVALID_TOKEN after the second 407.

So the question still remains, why are we getting SEC_E_INVALID_TOKEN in 6.0 but not in 5.0?

**Comment by wfurt** [comment]
agreed. It is the same connection, data looks reasonable and it simply fails in Windows PAL.

**Comment by karelz** [comment]
Triage:
We need to investigate more, it is unclear what is happening. Without a local repro it will be very challenging.
@raweibel are you in position to debug into it in your environment?

Moving to Future for now, until we have more customers hitting it.

**Comment by raweibel** [comment]
I'm currently setting up an environment that allows me to debug it. Hopefully, this will allow me to pin point the source of the exception. I will get back to you with the results in the coming days.

**Comment by mihael74** [comment]
Hello @raweibel 
I have the same Issue. It's also  on a corproate network which requires proxy authentication using the windows credentials.
Any news from your side? Have you found a workaround?

**Comment by raweibel** [comment]
Hi @mihael74 ,
I haven't been able to further invetigate the issue, as I'm an external working with a company (i.e. I have limited access to deploying development tools on their systems). Currently, trying find a solution with them. If you have the ability the futher investigate the issue, that would be great!

As for aworkaround, we resorted to downgrading to .NET 5 for now.

**Comment by wfurt** [comment]
Does it fail consistently or randomly @mihael74? Can you provide more information?

**Comment by mihael74** [comment]
Hello @raweibel  and @wfurt
It fails consistently (100%) with net6.0 and it does not fail at all with net5.0.
I'm also an external with very limited capabilities. I'll contact the team responsible for the proxy and ask them about protocol information and whether they see anything useful on their side.
Would any particular information be helpful?

**Comment by mihael74** [comment]
It looks exactly same as raweibel's case. The challenge fails:
net5.0:
![net5](https://user-images.githubusercontent.com/22000262/149495952-c25ea752-a809-4070-8edf-c4048ad94b39.png)
net6.0:
![net6](https://user-images.githubusercontent.com/22000262/149496075-7934626e-36dd-4402-8730-011d5237fb96.png)

**Comment by wfurt** [comment]
I set up proxy with NTLM authentication and I cannot reproduce it. But I have simple app, perhaps can you try it as well @mihael74?

```c#
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;

namespace http
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var handler = new SocketsHttpHandler();
            handler.Proxy = new WebProxy("http://10.10.10.10:1010/");
            handler.DefaultProxyCredentials  = new NetworkCredential("user1", "PASSWORD", "DOMAIN");
            //handler.DefaultProxyCredentials  = CredentialCache.DefaultCredentials;
            using (var client = new HttpClient(handler))
            {
                for (int i = 0; i < 4; i++)
                {
                     try
                     {
                         var response = await client.GetStringAsync("https://www.microsoft.com");
                         Console.WriteLine(response);
                     } catch (HttpRequestException ex)
                     {
                             Console.WriteLine(ex);
                     }
                }
            }
        }
    }
}
```
You can try both versions, one with default credentials and one with explicit authentication to see if that makes any difference. 
Since this is simple app, can you also set break on `GetOutgoingBlob` and check `_spn` and `_clientSpecifiedSpn`. (or any observable differences) 
Logs & packet captures may be useful. If you don't want to post them here, send them to my GH email.

**Comment by Pitxi** [comment]
We are having the same error when trying to install dotnet-ef behind our corporate NTLM proxy.

`C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5):error : No se puede cargar el índice de servicio para el origen https://api.nuget.org/v3/index.json. [C:\Users\...\AppData\Local\Temp\zd22vkxl.n2a\restore.csproj]`
`C:\Program Files\dotnet\sdk\6.0.101\NuGet.targets(130,5): error :El token proporcionado a la función no es válido [C:\Users\...\AppData\Local\Temp\zd22vkxl.n2a\restore.csproj]`
`NuGet.Protocol.Core.Types.FatalProtocolException: No se puede cargar el índice de servicio para el origen https://api.nuget.org/v3/index.json.
                      ---> System.ComponentModel.Win32Exception (0x80090308): El token proporcionado a la función no es válido`

**Comment by steduardo** [comment]
Same issue for us behind corporate MWG proxy via net 6.0

![token-not-valid](https://user-images.githubusercontent.com/58334/153017234-22a388a7-9c0c-418e-9f8d-d015139d9e62.png)
.

**Comment by steduardo** [comment]
OK I've done some further investigation. @wfurt thanks for your simple repro app, that proved to be useful.

It seems that the problem is not with NTLM itself, but with the certificate / cipher handling. Some sites work and some don't, so likely each site has different cipher suites on offer and the handshake fails at that point. (net6 doesn't understand/handle the cipher presented?)

I tested with default credentials and one with explicit authentication - same results for each.

Here is the program including my additional site tests & results:

`using System;
using System.Threading;
using System.Threading.Tasks;
using System.Net;
using System.Net.Http;

namespace http
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var handler = new SocketsHttpHandler();
            handler.Proxy = new WebProxy("http://192.168.24.87:8080/");
            handler.DefaultProxyCredentials = new NetworkCredential("hkgproxy01", "authproxy", "hkg");
            //handler.DefaultProxyCredentials  = CredentialCache.DefaultCredentials;
            using (var client = new HttpClient(handler))
            {
                for (int i = 0; i < 4; i++)
                {
                    try
                    {
                        // THIS WORKS
                        var response1 = await client.GetStringAsync("https://www.microsoft.com");
                        Console.WriteLine(response1);

                        // FAILS! Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
                        // at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal & statusCode)
                        var response2 = await client.GetStringAsync("https://www.amazon.com");
                        Console.WriteLine(response2);

                        // FAILS! Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
                        // at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal & statusCode)
                        var response3 = await client.GetStringAsync("https://www.facebook.com");
                        Console.WriteLine(response3);

                        // THIS WORKS
                        var response4 = await client.GetStringAsync("https://www.google.com");
                        Console.WriteLine(response4);

                        // FAILS! Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
                        // at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal & statusCode)
                        var response5 = await client.GetStringAsync("https://www.github.com");
                        Console.WriteLine(response5);

                        // FAILS! Unhandled exception. System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
                        // at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal & statusCode)
                        var response6 = await client.GetStringAsync("https://www.netflix.com");
                        Console.WriteLine(response6);
                    }
                    catch (HttpRequestException ex)
                    {
                        Console.WriteLine(ex);
                    }
                }
            }
        }
    }
}`

Hopefully this will help repro, but ymmv depending on how your test proxy handles certificates.

Maybe related to this https://github.com/dotnet/runtime/issues/31541 ?

Back to net5.0 for now but hopefully this will be fixed in net6.0 soon!

**Comment by wfurt** [comment]
This is very interesting @steduardo. But from the capture it fails _before_ the handshake even starts. So I doubt this is related to ciphers or algorithms. I use Squid with NTLM configured and I can access all the sides. 

I had one debug session with @mihael74 and from what we gathered it looked like the data was somehow mangled between HttpClient and actual call to OS for what ever reason. But then I would have no explanation why some sites work and some others do not .... unless that is just luck. 

If anyone would be able to run the simple repro above with custom bits please let me know privately. I can craft instrumented `http.dll` and that would hopefully provide enough evidence.

**Comment by steduardo** [comment]
If it will help for me to run the repro again with custom dlls please let me know details @wfurt and I'll be happy to try it.

**Comment by wfurt** [comment]
I put 6.0 binary with debug [here](https://microsoft-my.sharepoint.com/:u:/p/toweinfu/ETjiOovaSd1PvofjhLdND9ABsNQ9Q-bUiEJoSdvRsxG-nw?e=nOXfXX) and I did small update to the test code above. I generally don't like to ask people to run unknown binaries so treat it with caution. Alternatively, it can be rebuilt locally from my private branch https://github.com/dotnet/runtime/compare/release/6.0...wfurt:60debug?expand=1

I generally use `dotnet publish -r win-x64` and I replace given `*.dll` within the publish directory so the binary is localized to the  test app.  
It may be best share outcome with me via my GH email. Depending on the outcome there may be another iterations.

**Comment by wfurt** [comment]
I put it also on  [Google Drive](https://drive.google.com/file/d/1XiyLK9UkGNFpIi_SGFBw4jwWxmfP5-hs/view?usp=sharing).
If that does not work, send me email @steduardo and we will figure out something else.

**Comment by debusch77** [comment]
Hello everyone. Just wanted to chime in that I have run into an identical issue as well. I have a process that runs on a corporate network, and requires a proxy server to call an external API. The process originated, and works, in .Net 5 and am trying to migrate to .Net 6 but get the same error, the Win32Exception thrown by the method System.Net.NTAuthentication.GetOutgoingBlob(). This is not an intermittent problem and occurs every time my code executes.

I can go back to 5 but am really wanting to move to 6 because of the performance improvements I am getting with the latest version of EF. 

Has any progress been made on figuring this issue out?

**Comment by wfurt** [comment]
I finally have some update. Big thanks to @steduardo who work with me off-line to collect more insight. 

This seems to be caused by #54101 - cc @filipnavara 
Reverting that one line change seems to fix it for @steduardo
I put up unsigned replacement binary here: https://drive.google.com/file/d/1JwSNUmTxwaECfg0gBicuypqj2Fa7wGnn/view?usp=sharing
Treat it is untrusted but it would be great if we can get more feedback using that and either the simple test app above or what ever you need to check. 

The exchange looks like:
```
5.0 
            NTLM Message Type: NTLMSSP_NEGOTIATE (0x00000001)
            Negotiate Flags: 0xa2088207, Negotiate 56, Negotiate 128, Negotiate Version, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate OEM, Negotiate UNICODE

            NTLM Message Type: NTLMSSP_CHALLENGE (0x00000002)
            Negotiate Flags: 0xa0898205, Negotiate 56, Negotiate 128, Negotiate Target Info, Negotiate Extended Security, Target Type Domain, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate UNICODE

            NTLM Message Type: NTLMSSP_AUTH (0x00000003)
            Negotiate Flags: 0xa2888205, Negotiate 56, Negotiate 128, Negotiate Version, Negotiate Target Info, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Request Target, Negotiate UNICODE

6.0
            NTLM Message Type: NTLMSSP_NEGOTIATE (0x00000001)
            Negotiate Flags: 0xe2088297, Negotiate 56, Negotiate Key Exchange, Negotiate 128, Negotiate Version, Negotiate Extended Security, Negotiate Always Sign, Negotiate NTLM key, Negotiate Lan Manager Key, Negotiate Sign, Request Target, Negotiate OEM, Negotiate UNICODE

            NTLM Message Type: NTLMSSP_CHALLENGE (0x00000002)
            Negotiate Flags: 0xe0898215, Negotiate 56, Negotiate Key Exchange, Negotiate 128, Negotiate Target Info, Negotiate Extended Security, Target Type Domain, Negotiate Always Sign, Negotiate NTLM key, Negotiate Sign, Request Target, Negotiate UNICODE

And SSPI essentially errors out after processing the challenge.
```

I'm also wondering if all the hits are using McAfee Web Gateway or if this manifest on wider range of products. 

I think we have (at least) following options:
1) revert  #54101  and leave macOS and possibly switch to managed implementation.
2) make it platform fix e.g. set it only on OSXLike systems
3) make it optional flag and don't set it for proxy connections
4) detect this situation and build in some fall-back mechanism.

Since all the issues so far are related to proxy I'm leaning towards 3 at the moment. 
I'm wondering if anybody has insight how Linux/macOS work in their setup with 5.0 and 6.0.

**Comment by ToanHT** [comment]
Hello everyone,
I got the same error when using HttpWebRequest and SoapClient to call Webservice in proxy environment.
_System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid_
I upgraded .Net 6 for a long time, so it is difficult to go back to .Net 5. 
Anybody help me how to solve this problem.
Thank you all!

**Comment by wfurt** [comment]
Any chance you can test the linked binary @ToanHT?

**Comment by ToanHT** [comment]
Dear wfurt,
I use System.Net.HttpWebRequest to call API and SoapClient to call WCF WebService.
So I can't use System.Net.Http

**Comment by wfurt** [comment]
in .NET Core HttpWebRequest sits on top of HttpClient. If it would not you would not see this :)

**Comment by stevebrowne** [comment]
@wfurt Can confirm this fixes it for us. We also use McAfee Web Gateway.

**Comment by filipnavara** [comment]
@wfurt Do you happen to have the full Wireshark/Fiddler logs with the Authorization header contents? I have a way to synthesise the server side of the communication and I'd look into a fix for this.

**Comment by filipnavara** [comment]
So, I have the scenario reproduced locally. The reason it fails is that the proxy server doesn't report the Target Name and Target Info. Both of these fields are empty in the CHALLANGE message from the server. 

The failure is described in the specification:
> If NTLM v2 authentication is used and the CHALLENGE_MESSAGE does not contain both
MsvAvNbComputerName and MsvAvNbDomainName AVPairs and either Integrity is TRUE or
Confidentiality is TRUE, then return STATUS_LOGON_FAILURE ([MS-ERREF] section 2.3.1).

Essentially it's impossible to ensure the integrity of the communication with the proxy server since it fails to provide these values. The question is thus, are we fine with downgrading the communication security when talking to a known proxy server? If yes then it would likely be fine to drop the `InitIntegrity` flag for proxies on non-macOS systems. However, the security trade-off is important to understand.

**Comment by wfurt** [comment]
It seems like it was like that until 6.0 so it is probably acceptable. We could also add AppContext switch to control this but I would be inclined to leave it off by default to match 5.0 behavior.

**Comment by wfurt** [comment]
Should be closed by  #66315 for 6.0.4

**Comment by kevinwedwards** [comment]
@wfurt - any idea when 6.0.4 is going to be released?

**Comment by karelz** [comment]
@kevinwedwards .NET releases are always aiming at patch Tuesday - 2nd Tuesday in each month. It is useful in case it includes also security fixes.
So the estimation is Tue 4/12.

**Comment by karelz** [comment]
Fixed in 7.0 (main) in PR #66305 and in 6.0.4 in PR #66315

**Comment by kevinwedwards** [comment]
I can verify that 6.0.4 fixed this issue... if verification is desired.

**Comment by wfurt** [comment]
Thanks for confirming. It is always good to know.
