### ISSUE TITLE
Is 'sb.AppendFormat($"{Signature.ParameterTypes[i]}");' a typo error

### ISSUE THREAD

**Issue by wwh1004** [dotnet/runtime#62137]
I use ILSpy to see r2r code. ILSpy uses 'ILCompiler.Reflection.ReadyToRun' and it throws format exception.

![image](https://user-images.githubusercontent.com/27536652/143868922-57be7c5c-7fb9-4a1d-920d-cdde28af1357.png)

https://github.com/dotnet/runtime/blob/a4cab7d3206027566dc14672669caeac56ef8400/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunMethod.cs#L468

https://github.com/dotnet/runtime/blob/a4cab7d3206027566dc14672669caeac56ef8400/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/PgoInfoKey.cs#L114

For obfuscated code, 'AppendFormat' always fails. And it makes no sense to regard a type name as a string format. So is 'sb.AppendFormat($"{Signature.ParameterTypes[i]}");' a typo error?

**Comment by stephentoub** [comment]
> So is 'sb.AppendFormat($"{Signature.ParameterTypes[i]}");' a typo error?

Looks like it should just be "Append" instead of "AppendFormat".

**Comment by wwh1004** [comment]
I think you can fix it better. I don’t know if there are only these two typo errors.
