### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62144]
### Description

![image](https://user-images.githubusercontent.com/35312807/143898200-ceb8f520-1542-4a6c-8c98-222ddcc08e49.png)

### Reproduction Steps

Shown in screenshot

### Expected behavior

if statement shouldn't execute when condition evaluated to false

### Actual behavior

if statement executes when condition evaluated to false

**Comment by ryank425** [comment]
It is possible to have a different value on when you watch it from the debugger versus when the code evaluated if condition with multiple threading or other possible scenarios.

Please upload the sample code that can reproduce it.

**Comment by Xyncgas** [comment]
the code is proprietary, all I can say is dimension was definately 1, because it takes 10 mins of computing to get to the 2nd dimension, then 1.5 days to the 3rd dimension

**Comment by stephentoub** [comment]
What is `dimension` here... is it a field?  A parameter?  Can you show more of the code?  My guess is similar to @ryank425's, that this is actually a problem in the app code, e.g. another thread is mutating the value concurrently, or some exception-handling code mutated the value in a filter, or some such thing... without a shareable repro, it's hard to help further.

**Comment by Suchiman** [comment]
Is the code optimized / Release? If that's the case, the line number might be inaccurate (and it could be the second throw that's actually running)

**Comment by Xyncgas** [comment]
It turned out to be another statement that was throwing, after I added the line to print the values when it should throw.
![image](https://user-images.githubusercontent.com/35312807/143961090-0bd11b45-740e-4d45-a638-e5ff6b178dc3.png)

**Comment by Xyncgas** [comment]
Which was my fault, I fixed it

**Comment by stephentoub** [comment]
So this can be closed,  yes?
