### ISSUE TITLE
Unclear documentation for FileSystemInfo.LinkTarget

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#62166]
https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.linktarget?view=net-6.0

The documentation says: If this `FileSystemInfo` instance represents a link, returns the link target's path. If a link does not exist **in** `FullName`, or this instance does not represent a link, returns `null`.

I believe it should say something like: If this `FileSystemInfo` instance represents a link, returns the link target's path. If a link does not exist **at** `FullName`, or this instance does not represent a link, returns `null`.
because I was worried that something like `new FileInfo(@"C:\Users\Hamish\Desktop\folder.link\file.txt").LinkTarget` would turn into `"C:\Users\Hamish\Desktop\folder\file.txt"` or something else, rather than `null`.

The specific reason that I got the impression I got is because of the wording, I'd consider there to be a link in `/folder.link/file.txt`, but not at `/folder.link/file.txt` and the current wording says "If a link does not exist **in** `FullName`" implying if any part of it is a link.

**Comment by Jozkee** [comment]
@hamarb123 right, this summary is way out of the [boilerplate](https://github.com/dotnet/dotnet-api-docs/wiki/Summary%3A-Property). I think it should say "Gets the target path of the current file or directory link".
No other property in `FileSystemInfo` mentions that returns `null` (or other value) when the the instance represents a non-existent file or directory. 

cc @carlossanlop

**Comment by hamarb123** [comment]
Note: the api returned null even though the target exists and had a link that exists (which is expected behaviour), but is unclear from the wording.

**Comment by carlossanlop** [comment]
> No other property in FileSystemInfo mentions that returns null (or other value) when the the instance represents a non-existent file or directory.

It doesn't matter. If the other descriptions don't mention it, it's probably because they would never return null. If LinkTarget has the behavior of returning null for a particular use case, it needs to be mentioned clearly in the description.

**Comment by sabarish98** [comment]
Hi folks, Can I pick this up ?

**Comment by sabarish98** [comment]
Took a stab at it : )
