### ISSUE TITLE
[Question] :What happens when binary shift is performed exceeding the width of data's size.

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62172]
byte _B;
B=B<<101;
it most certainly run, but when I am running my program I get a feeling that instead of zero-ing out it actually takes a modulus of (8+1) and shift the bits from 0~8. I would like to know if I am correct on this, and it's consisdent everywhere .NET running.

**Comment by Joe4evr** [comment]
Please use [discussions](https://github.com/dotnet/runtime/discussions) for questions.

**Comment by alexrp** [comment]
To answer the question: C# masks the RHS value to ensure it makes sense for the type. This is done because an invalid shift amount gives an unspecified result on the IL level.

**Comment by GrabYourPitchforks** [comment]
@alexrp is correct. [From the C\# spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#shift-count-of-the-shift-operators):

> For the x << count and x >> count expressions, the actual shift count depends on the type of x as follows:
> 
> If the type of x is int or uint, the shift count is defined by the low-order five bits of the right-hand operand. That is, the shift count is computed from count & 0x1F (or count & 0b_1_1111).
> 
> If the type of x is long or ulong, the shift count is defined by the low-order six bits of the right-hand operand. That is, the shift count is computed from count & 0x3F (or count & 0b_11_1111).

**Comment by Xyncgas** [comment]
> Please use [discussions](https://github.com/dotnet/runtime/discussions) for questions.

ok

**Comment by Xyncgas** [comment]
Thanks people
