### ISSUE TITLE
Add an overload: CancellationTokenSource.CreateLinkedTokenSource(CancellationToken)

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#6217]
We need an overload with a single linked `CancellationToken`. Logically, it makes to have this.

Example scenario (which I just experienced): We want a token that becomes signaled if an externally passed in token becomes signaled or a timeout expires.

There is a `params` overload but that allocates an array. It would be nice to have the case with one token built-in. (Maybe also add a case for 3 tokens?!)

My current workaround is: `CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, CancellationToken.None)`.

**Comment by stephentoub** [comment]
This now exists.
