### ISSUE TITLE
Remove `GTF_DEBUG_NODE_MORPHED`.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/runtime#6218]
This debug-only GenTree flag is of questionable utility. See dotnet/coreclr#6002 for more discussion.

category:correctness
theme:ir
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
Seems like the main concern is not that we over morph but that we miss out on morphing something entirely. But I suppose in those cases where morphing actually does something required lack of morphing should become evident.
