### ISSUE TITLE
Add an argument to SuperPMI

### ISSUE THREAD

**Issue by SeanWoo** [dotnet/runtime#62188]
I want to suggest adding an optional -c argument for superpmi.py asmdiffs
### What will it give?
This will allow you to run certain tests, and not all at once, this is especially useful when a problem occurs in a certain test and it is easier to run it alone than to run it all at once. This would especially affect when collecting JitDump.
### How will it work?
Adding a new argument -c to superpmi.py and we throw it into superpmi.exe when we run asmdiff, if -c is specified, then we remove the -p key (since this does not work if -c is specified)

I can implement it

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib.
Thanks @SeanWoo for suggesting to implement it. We will review it once you submit a PR.

**Comment by BruceForstall** [comment]
I've wanted to do this for a while; would be happy to see it. Without it, I've always just manually copy/pasted the superpmi.exe command line from the superpmi.log file generated by superpmi.py, and altered it as appropriate.

Note that you should add `-c` to both `asmdiffs` and `replay` for consistency.
