### ISSUE TITLE
[API Proposal]: Allow returning stack allocated memory, here's how

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62189]
### Background and motivation

if we are returning span<byte>, that holds stack allocated array of byte, we return this byte array by putting it in the heap first, that's what's happening, that is the only method.

but instead, just pin the stack allocated memory, and give me a smart pointer or a span<t> which you can throw away the memory later with gc, since people had the gut to allocate those bytes in their stack these data usually isn't big otherwise it overflows. it doesn't matter who owns the data it's managed, we will make sure of it, the way I propose to do this is to make this returned memory from stack allocation special so that it has the life-time bound by the value (which is a pointer to this memory, so the pointer is special in .NET), which behaves like any normal value types you get back from a function it's gone after you go out of scope, even though it's just a pointer it has this implication for the memory it holds, so now we can return any amount of memory from a function that was stack allocated by returning a special pointer with a size, and since we already have span we will use it, and let's call it something like StickySpan<T>

Span<T> was a big thing because of that people are more happy dealing with memory and in doing so made it easier to bring performance to the table. StackAllocated bytes are valuable in its way, but we are only restricted to use them in the same scope, but why another extra allocations in the heap when things can be more friendly with stack memory oriented programming tasks.

### API Proposal

Function exists, leaves behind some garbage that shouldn't be collected by pinning it, maybe by using some hacks.

### API Usage

```
StickySpan<byte> ReturnPixels()
{
    Span<byte> Pixels = stackalloc byte[32];
    ProcessRGB(Pixels);
    return Pixels;//Implicit cast to StickySpan<byte>, Pixels memory exists in this stack, it will remain the same now
}
void LookAtPixels()
{
    StickySpan<byte> SideEffect = ReturnPixels();
    //We are not calling stackalloac here, the memory is actually in another place, maybe we can add another api like 
    SideEffect.ToStack() which copies that memory to the current stack by automatically calling stackalloc
}//SideEffect 's actual memory ( bytes allocated in ReturnPixels() ) is offcial out of scope when SideEffect is, so now it can be gc collected
```

### Risks

Memory fragmentation when stuffs in stacks aren't thrown away, it's a pattern that users should consider, but it will be useful for me.

**Comment by AraHaan** [comment]
if all else fails, maybe you can pin that memory and give it a fake reference count in order for it to avoid being GC'd at return?

**Comment by Xyncgas** [comment]
yea we can pretend this pinned memory is just the regular memory from the heap, so StickySpan<T> can be passed around like you are passing around T[]

**Comment by Xyncgas** [comment]
in fact why even use StickySpan<T>, let's just make pinning stack allocated memory a thing, then we can return it with whatever types we like, T*, T[], Span<T>

**Comment by Xyncgas** [comment]
Just pretend it's a heap allocated memory when the function exists instead of copying it to the heap

**Comment by budgetdevv** [comment]
`just pin the stack allocated memory` 

But they're already "pinned", since the GC doesn't move them

**Comment by Xyncgas** [comment]
well by pinning I mean make that memory reachable, because how else can you get back stack allocated bytes without a copy these days, in a tight loop it makes the difference. I am building AI model, that the algorithm likes to allocate bytes in stack then returning it

**Comment by budgetdevv** [comment]
If you return the ptr to the stackalloc, it is by all means still reachable. Doesn't mean its a good idea to access them, though

**Comment by Xyncgas** [comment]
AI-modeling has a bunch of param, in my case each looks like this, I am talking about returning this many many times when training a model, it would be nice if things aren't copied because even though it's just 2 bytes here but I have a bunch of these structs. instead of copying them yes using a pointer to it would be a good idea but now I have to use unsafe to access pointers, would be nice if I can use it like we can use Span<T>
![image](https://user-images.githubusercontent.com/35312807/144062273-8043228d-3507-49b2-9a9b-37cd1c3648cc.png)

**Comment by Xyncgas** [comment]
> If you return the ptr to the stackalloc, it is by all means still reachable. Doesn't mean its a good idea to access them, though

if i do that will gc collect it later when i am still using it or it knows it's still reachable

**Comment by budgetdevv** [comment]
> > If you return the ptr to the stackalloc, it is by all means still reachable. Doesn't mean its a good idea to access them, though
> 
> if i do that will gc collect it later when i am still using it or it knows it's still reachable

The GC doesn't collect stackalloc memory

**Comment by AraHaan** [comment]
I thought it did when out of scope of the function that allocates it.

**Comment by Xyncgas** [comment]
the stack is destoryed when it goes out of scope, usually.

**Comment by Xyncgas** [comment]
I am closing this issues for now, if I can come up with something stronger I will be creating a new one

**Comment by Xyncgas** [comment]
if someone can point me to "preserve stack allocated memory c#" it would work

**Comment by AraHaan** [comment]
I think .NET 6 added NativeMemory apis if I remember right as well, although you could avoid the copy by having it temporarily allocate it to the heap from the start, do what it needs to do, and then when you are done free it from the heap.

**Comment by Clockwork-Muse** [comment]
The "traditional" way to deal with this is to take a reference as an output variable that you're expected to write to, which might be stack-allocated by the caller (or not - in C/C++ it could still be heap memory referenced in a certain way).  Is that an option for you?

**Comment by Xyncgas** [comment]
It's what I've been doing, passing in span<T>, alternatively I can inline the function being called to the caller. This proposal was more a thought of the moment against something that might be what's an interesting hack
