### ISSUE TITLE
Add better API to support communication with Kerberos endpoints

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#62202]
We sort of have NegotiteStream to allow mutual Kerberos authentication. However, that is custom .NET extension and it does not work agains endpoint written in other languages. 
For example #60906 caused crashing regression because SqlClient depends on runtime internals and it is hard to keep in sync.   
Similarly [PostgresSQL](https://github.com/npgsql/npgsql/blob/main/src/Npgsql/Internal/NpgsqlConnector.Auth.cs#L343) writes custom wrapper around NegotiateStream to strip and add fields to make it usable. 

It would be nice to have enough public API surface so projects like this can use .NET directly without jumping through weird hoops. 
We would need to work out details and either extend NegotiateStream or come up with separate stream class.

**Comment by karelz** [comment]
Related to #29270

**Comment by karelz** [comment]
Triage: We would like to support database clients in better way in 7.0.

**Comment by filipnavara** [comment]
I checked what would be necessary to port dotnet/SqlClient to the new NegotiateAuthentication API. The missing piece are two flags on the authentication (Delegate, MutualAuth). API suggestion is in #70982.

**Comment by wfurt** [comment]
Thanks @filipnavara. The other chunk I"m aware of is Postgress Driver https://github.com/npgsql/npgsql/blob/00ee7a8a47cc61b9419dd334851ec5184ab5bcdd/src/Npgsql/Internal/NpgsqlConnector.Auth.cs

cc: @roji

**Comment by wfurt** [comment]
closing this as  #70982 is merged.
