### ISSUE TITLE
Remove #ifs in System.ComponentModel.TypeConverter

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#62212]
Related to #39174.

We have some left over #ifs that weren't removed as part of #18862.

See:

https://github.com/dotnet/runtime/blob/bb597e2f6b4f47f0f3058b12f16a83e4f3b5e6ba/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L78-L87

https://github.com/dotnet/runtime/blob/bb597e2f6b4f47f0f3058b12f16a83e4f3b5e6ba/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectTypeDescriptionProvider.cs#L652-L661

and one non-behavior instance that can just be cleaned up:

https://github.com/dotnet/runtime/blob/bb597e2f6b4f47f0f3058b12f16a83e4f3b5e6ba/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/Design/StandardCommands.cs#L665-L667

For the first two, we should remove the `#if` and enable the code it is protecting. These are left-over from pre-standard2.0 days when some APIs weren't available. As part of enabling this code we should add unit tests for the behavior.

For the last one, the whole code chunk can be removed since it is not needed.

**Comment by pedrobsaila** [comment]
Hi, I would like to contribute on this issue

**Comment by eerhardt** [comment]
Awesome, @pedrobsaila! Thanks for the help. I have assigned it to you.

**Comment by pedrobsaila** [comment]
Hi I made a PR #62364 for this issue
