### ISSUE TITLE
[mono] custom debugger extenstion

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#62220]
hi, if i want to make a debugger extension with vs studio or vs code.
I should still use https://github.com/mono/debugger-libs? anything new or change in dotnet/runtime monovm use?

**Comment by lambdageek** [comment]
@srxqds we have a project in progress https://github.com/dotnet/runtime/tree/main/src/mono/dlls/mscordbi to implement ICorDebug for mono which will make mono expose the same debugger interface that CoreCLR (and .NET Framework) uses.  But it is not ready yet, and it will probably require some changes in VS.

For now, using debugger-libs is better

**Comment by srxqds** [comment]
thank you
