### ISSUE TITLE
Exception not thrown for ZipFile inside Blazor-Server Service

### ISSUE THREAD

**Issue by BuchholzTim** [dotnet/runtime#62231]
### Description

Creating an archive of a folder (in blazor), which contains a named pipe in DotNet 6.0 via the [ZipFile Class](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.createfromdirectory?view=net-6.0#System_IO_Compression_ZipFile_CreateFromDirectory_System_String_System_String_) causes the program to block indefinitely long, without any kind of exception thrown.

1. Create a Named Pipe in a Linux distribution with `mkfifo`  (for me this happened while running my dotnet application inside a docker conatiner)
2. Try to compress the directory containing the named pipe with `ZipFile.CreateFromDirectory` inside a Blazor-Server Service

### Configuration

- .NETCore 6.0.0
- Hosted Blazor Webassembly (`dotnet new blazorwasm -ho`)

### Other information

An Exception is thrown when I try to ZIP the same directory inside a simple Dotnet Console Application.

**Comment by adamsitnik** [comment]
Hi @BuchholzTim 

Are you sure that you are using `mkfifo` correctly? It's quite easy to get blocked using it.

Accodring to [mkfifo man page](https://man7.org/linux/man-pages/man3/mkfifo.3.html):

> Opening a FIFO for reading normally blocks
       until some other process opens the same FIFO for writing, and
       vice versa.

Moreover, the reading is finished when writer closes the file descriptor.

**Comment by adamsitnik** [comment]
> An Exception is thrown when I try to ZIP the same directory inside a simple Dotnet Console Application.

I've tried to repro that, but I've failed. Here is the code that I've used:

```cs
public async Task CanZipNamedPipe()
{
    string destPath = Path.Combine(TestDirectory, "dest.zip");

    string subFolderPath = Path.Combine(TestDirectory, "subfolder");
    string fifoPath = Path.Combine(subFolderPath, "namedPipe");
    Directory.CreateDirectory(subFolderPath); // mandatory before calling mkfifo
    Assert.Equal(0, mkfifo(fifoPath, 438 /* 666 in octal */));

    byte[] contentBytes = { 1, 2, 3, 4, 5 };

    await Task.WhenAll(
        Task.Run(() =>
        {
            using FileStream fs = new (fifoPath, FileMode.Open, FileAccess.Write, FileShare.Read);
            foreach (byte content in contentBytes)
            {
                fs.WriteByte(content);
            }
        }),
        Task.Run(() =>
        {
            ZipFile.CreateFromDirectory(subFolderPath, destPath);

            using ZipArchive zippedFolder = ZipFile.OpenRead(destPath);
            using Stream unzippedPipe = zippedFolder.Entries.Single().Open();

            byte[] readBytes = new byte[contentBytes.Length];
            Assert.Equal(contentBytes.Length, unzippedPipe.Read(readBytes));
            Assert.Equal<byte>(contentBytes, readBytes);
            Assert.Equal(0, unzippedPipe.Read(readBytes)); // EOF
        }));
}

[DllImport("libc", SetLastError = true)]
private static extern int mkfifo(string path, int mode);
```

@BuchholzTim Could you please share more details (repro, stack trace)?
