### ISSUE TITLE
Missing entries in user.config after decryption/encryption with ConfigurationSaveMode.Full 

### ISSUE THREAD

**Issue by korny86** [dotnet/runtime#62233]
### Description

I like to store a username and password to the user.config in my C# .net5 program. I don't want to store the password direct and I decided to decrypt the userSettings section. After decryption parts of the file are missing.

Attached are the original user.config, after enryption and after decryption.
[user.config.zip](https://github.com/dotnet/runtime/files/7634199/user.config.zip)

There is only the last entry in the decrypted user.config and the name of the entry is missing. If I switch the order in the original file, I get "xyz" instead of "user" as the value.

### Reproduction Steps

The code to decrypt/encrypt (more or less a copy of an msdn example ([click](https://docs.microsoft.com/de-de/dotnet/api/system.configuration.rsaprotectedconfigurationprovider?view=dotnet-plat-ext-6.0#examples))):

private static void ProtectSettings()
{ 
    // Get the application configuration file.
    System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal);

    // Define the Rsa provider name.
    string provider = "DataProtectionConfigurationProvider";

    string section = "userSettings/" + System.Reflection.Assembly.GetExecutingAssembly().GetName().Name + ".Properties.Settings";

    // Get the section to protect.
    ConfigurationSection connStrings = config.GetSection(section);

    if (connStrings != null)
    {
        if (!connStrings.SectionInformation.IsProtected)
        {
            if (!connStrings.ElementInformation.IsLocked)
            {
                // Protect the section.
                connStrings.SectionInformation.ProtectSection(provider);

                connStrings.SectionInformation.ForceSave = true;
                config.Save(ConfigurationSaveMode.Full);
                        
                Debug.WriteLine("Section {0} is now protected by {1}",
                    connStrings.SectionInformation.Name,
                    connStrings.SectionInformation.ProtectionProvider.Name);
            }
            else
                Debug.WriteLine(
                        "Can't protect, section {0} is locked",
                        connStrings.SectionInformation.Name);
        }
        else
            Debug.WriteLine(
                "Section {0} is already protected by {1}",
                connStrings.SectionInformation.Name,
                connStrings.SectionInformation.ProtectionProvider.Name);
    }
    else
        Debug.WriteLine("Can't get the section {0}", section);
}

private static void UnProtectSettings()
{
    // Get the application configuration file.
    System.Configuration.Configuration config = ConfigurationManager.OpenExeConfiguration(ConfigurationUserLevel.PerUserRoamingAndLocal);

    string section = "userSettings/" + System.Reflection.Assembly.GetExecutingAssembly().GetName().Name + ".Properties.Settings";

    // Get the section to unprotect.
    ConfigurationSection connStrings = config.GetSection(section);

    if (connStrings != null)
    {
        if (connStrings.SectionInformation.IsProtected)
        {
            if (!connStrings.ElementInformation.IsLocked)
            {
                // Unprotect the section.
                connStrings.SectionInformation.UnprotectSection();

                connStrings.SectionInformation.ForceSave = true;
                config.Save(ConfigurationSaveMode.Full);
                        
                Debug.WriteLine("Section {0} is now unprotected.",
                    connStrings.SectionInformation.Name);
            }
            else
                Debug.WriteLine(
                        "Can't unprotect, section {0} is locked",
                        connStrings.SectionInformation.Name);
        }
        else
            Debug.WriteLine(
                "Section {0} is already unprotected.",
                connStrings.SectionInformation.Name);
    }
    else
        Debug.WriteLine("Can't get the section {0}", section);
}

(Sorry for bad formatting, but the insert code part is not working...)

### Expected behavior

Complete user.config after encryption/decryption.

### Actual behavior

Parts of the file are missing.

### Regression?

Don't know.

### Known Workarounds

If I switch:
`config.Save(ConfigurationSaveMode.Full);`

to:
`config.Save();`

everything works like expected.

### Configuration

.NET5
Visual Studio 2019 Version 16.11.7
Windows 10 64bit

**Comment by wzchua** [comment]
Can you test with .NET6? It should be fixed there

**Comment by korny86** [comment]
It's working in .NET6.
