### ISSUE TITLE
Comparing method infos from expressions

### ISSUE THREAD

**Issue by mariusz96** [dotnet/runtime#62230]
Hi,

I'm developing a library for  aspnetcore that would let users pass strongly typed lambdas to LinkGenerator service. The API has two public overloads that call a private method:
```C#
public string GetUriByExpresion<TController>(Expression<Func<TController, object>> actionSelector);
public string GetUriByExpresion<TController>(Expression<Action<TController>> actionSelector);
private string GetUriByExpresionCore<TController>(LambdaExpression actionSelector);
```

And the user is expected to use generics or specify Controller type in a lambda parameter:
```C#
GetUriByExpresion<CustomerController>(c => c.NonVoidMethod(1));
GetUriByExpresion<CustomerController>(c => c.VoidMethod(1));
GetUriByExpresion((CustomerController c) => c.NonVoidMethod(1));
GetUriByExpresion((CustomerController c) => c.VoidMethod(1));
```

Then, once I have an expression tree I read MethodInfo from it (unbox if needed):
```C#
MethodCallExpression actionCall = actionSelector.Body as MethodCallExpression;

if (actionCall == null
    && actionSelector.Body is UnaryExpression objectCast)
{
    actionCall = objectCast.Operand as MethodCallExpression;
}

MethodInfo action = actionCall.Method;
```
and controller type from generic type parameter (`Type controllerType = typeof(TController)`). Then, I validate and read different things like names, attributes, method parameters, etc, but this is pretty costly and repetitive so I thought of adding `Microsoft.Extensions.Caching.Memory.MemoryCache` to cache some information once read.

In the documentation, MethodInfo's `MetadataToken` is described as "A value which, in combination with Module, uniquely identifies a metadata element.". That sounded promising so I prototyped my CacheKey like this:
```C#
internal class CacheKey : IEquatable<CacheKey>
    {
        public int MethodMetadataToken { get; set; }
        public Module MethodModule { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as CacheKey);
        }

        public bool Equals(CacheKey other)
        {
            return other != null
                   && MethodMetadataToken == other.MethodMetadataToken 
                   && EqualityComparer<MethodModule>.Default.Equals(MethodModule , other.MethodModule);
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(MethodMetadataToken , MethodModule);
        }

        public static bool operator ==(CacheKey left, CacheKey right)
        {
            return EqualityComparer<CacheKey>.Default.Equals(left, right);
        }

        public static bool operator !=(CacheKey left, CacheKey right)
        {
            return !(left == right);
        }
    }
```
However I got no idea how to compare Module instances, when do either of values change and whether it is safe to hold a reference to a Module like this.

I looked around and seems [some other libraries](https://github.com/FluentValidation/FluentValidation/blob/f7c334e8ff5bce072bb9edbf2a8962ba581995e4/src/FluentValidation/Internal/AccessorCache.cs#L45) came up with their own hacks for this so I thought that I can maybe even flatten this to a string:
- `$"{action.MetadataToken}_{action.Module.FullyQualifiedName}"`
100663312_C:\Users\Mariusz\source\repos\WebApplication1\WebApplication1\bin\Release\net6.0\WebApplication1.dll
- `$"{action}_{controllerType.AssemblyQualifiedName}"`
System.Collections.Generic.IEnumerable`1[WebApplication1.WeatherForecast] Get()_WebApplication1.Controllers.WeatherForecastController, WebApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

However, I'm not sure whether either of this is a valid approach in aspnetcore environment (multithreaded? distributed? I don't know what else might be an obstacle, the cache is just a MemoryCache though) and what would be the best way to implement this. Some other info:
- currently, the library is in netstandard, but just netcore (net) would be enough
- both link service and cache would be singletons in aspnetcore application
- the WebAPI that uses the library would obviously run in some sort of IIS/Kestrel server, although my question is just about comparing MethodInfos/designing CacheKey

**Comment by MichalStrehovsky** [comment]
MethodInfo already implements Equals/GetHashCode. Isn't that sufficient for your needs?

MetadataToken is going to be equal for different generic instantiations (so e.g. `List<int>.Add` and List<string>.Add` would be equal in your scheme but they are different MethodInfos - not sure if that would be a bug or feature for your use case).

**Comment by mariusz96** [comment]
Can you explain MethodInfo's lifetime then? Because I see it checks equality through object.Equals, but does the reference always stay the same? When should I expect reference to change? Aspnetcore runs code on a thread pool if that adds anything.

And generic, web-reachable actions are not allwoed on a controller, so they shouldn't be an issue.

**Comment by jkotas** [comment]
MethodInfo.Equals does not always checks equality through object.Equals. See https://github.com/dotnet/runtime/blob/ff82b6dde9367df1c9eb40d362e701e2d54213a2/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs#L164-L166

There are situations where you can end up with two different MethodInfos pointing to the same method. The exact situations when this happens is reflection implementation detail. You should not depend on it in your code. Your code should just call MethodInfo.Equals to check for equality.

**Comment by mariusz96** [comment]
Silly me, there won't be any generic methodinfos but I was actually looking at Equals on an abstact class 😅

Ok, so to recap, I can:
- use Equals on two different MethodInfos to check if they point to the same method
- store their references in a singleton cache service for comparison

and it'll work.

Thank you for your answers then - I'll go ahead and do that 🏌️

**Comment by mariusz96** [comment]
Could you also please clarify how equality works with inheritance?

Although it is not a common scenario, say I write:
```C#
[ApiController]
public class LogController : ControllerBase
    {
        [HttpPost("log/{log}")]
        public virtual void LogFromBrowser(string log)
        {
            Logger.Log<LogController>(log);
        }
    }

[ApiController]
public class WeatherForecastController : LogController
    {
        [HttpPost("weatherforecast/{log}")]
        public override void LogFromBrowser(string log)
        {
            Logger.Log<WeatherForecastController>(log);
        }
    }
```

And then call my library like:
```C#
GetUriByExpression<LogController>(c => c.LogFromBrowser(null));
GetUriByExpression<WeatherForecastController>(c => c.LogFromBrowser(null));
```

Will both virtual and overriden methodInfo be equal and I should check the passed type as well (since they will have different URLs)?

**Comment by jkotas** [comment]
> Will both LogFromBrowser methodInfos be equal 

They won't be equal. They will be two different MethodInfos.

**Comment by mariusz96** [comment]
I actually compiled my code before asking and it was **not equal** in all cases.

But I did not tested my code with inherited controllers before and I think I figured out what's happening:

If I use a func or an action the methodInfos are different as expected:
```C#
Action<LogController> actionCall1 = c => c.LogFromBrowser(log);
Action<WeatherForecastController> actionCall2 = c => c.LogFromBrowser(log);
// false
bool equalActions = actionCall1.Method == actionCall2.Method;

Action<LogController> actionCall1_ = (LogController c) => c.LogFromBrowser(log);
Action<WeatherForecastController> actionCall2_ = (WeatherForecastController c) => c.LogFromBrowser(log);
// false
bool equalActions_ = actionCall1_.Method == actionCall2_.Method;
```

But if I use an expression with controllerType parameter it gives me back methodInfos from base type instead of derived ones:
```C#
Expression<Action<LogController>> expressionCall1 = c => c.LogFromBrowser(log);
Expression<Action<WeatherForecastController>> expressionCall2 = c => c.LogFromBrowser(log);
// true
bool equalExpressions = (expressionCall1.Body as MethodCallExpression).Method == (expressionCall2.Body as MethodCallExpression).Method;

Expression<Action<LogController>> expressionCall1_ = (LogController c) => c.LogFromBrowser(log);
Expression<Action<WeatherForecastController>> expressionCall2_ = (WeatherForecastController c) => c.LogFromBrowser(log);
// true
bool equalExpressions_ = (expressionCall1_.Body as MethodCallExpression).Method == (expressionCall2_.Body as MethodCallExpression).Method;
```
which sort of makes sense since controllerType is the parameter.

Is there a way to obtain a derived method in this scenario though?

**Comment by buyaa-n** [comment]
> But if I use an expression it gives me back methodInfos from base type instead of derived ones:

You are right, I see `(expressionCall1_.Body as MethodCallExpression).Method` and `(expressionCall2_.Body as MethodCallExpression).Method` produce the same method from the base class, so the equality result is correct

> ...  but is there a way to obtain a derived method in this scenario?

I hope the Linq area owners could help with that question cc @dotnet/area-system-linq

**Comment by cston** [comment]
> `(expressionCall1_.Body as MethodCallExpression).Method` and `(expressionCall2_.Body as MethodCallExpression).Method` produce the same method from the base class

That is expected since the C# compiler generates a call to the least overridden base method for virtual method calls.

> ...  but is there a way to obtain a derived method in this scenario?

The `MethodCallExpression` includes the `MethodInfo` from the base type of the instance expression only, not from the derived type. (And the actual method invoked when the lambda expression is executed may be from a more derived type, depending on the argument passed to the lambda expression.)

**Comment by mariusz96** [comment]
Thank you all for your answers.

I decided to throw InvalidOperationException on inherited methods.

Otherwise extracting methodinfos from expressions seems stable since at least 9 years.

And my cache key ended up being very simple too:
```C#
var key = (actionMethod, controllerType);
```

Outputs 100000 urls in 0.9s: https://www.nuget.org/packages/LinkBuilding.

Very cool 🚀🚀🚀
