### ISSUE TITLE
Possible typo: "This method is intended for compiler user..."

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#62248]
For example: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs#L81

Should this say "for compiler usage"? That makes more sense to me.

If it is a typo then it is replicated in quite a few places.

**Comment by JamesNK** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
> Should this say "for compiler usage"?

It was intended to say "use" rather than "user".

**Comment by slask** [comment]
Hi. I want to start contributing to .net, can I pick this up?
