### ISSUE TITLE
Blazor WASM - deserialization exception with ImmutableList when the app is published

### ISSUE THREAD

**Issue by srollinet** [dotnet/runtime#62242]
When trying to deserialize an ImmutableList in a published application I have the following exception

>blazor.webassembly.js:1         
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: SerializationNotSupportedType, System.Collections.Immutable.ImmutableList`1[BlazorImmutableIssue.Shared.WeatherForecast]
System.NotSupportedException: SerializationNotSupportedType, System.Collections.Immutable.ImmutableList`1[BlazorImmutableIssue.Shared.WeatherForecast]
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type )
   at System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableEnumerableCreateRangeMethod(Type , Type )
   at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableEnumerableCreateRangeDelegate(Type , Type , Type )
   at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableEnumerableCreateRangeDelegate[ImmutableList`1,WeatherForecast]()
   at System.Text.Json.Serialization.Converters.ImmutableEnumerableOfTConverterWithReflection`2[[System.Collections.Immutable.ImmutableList`1[[BlazorImmutableIssue.Shared.WeatherForecast, BlazorImmutableIssue.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],

I also tried with Newtonsoft, and it also fails

> Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Collections.Immutable.ImmutableList

**Important:** It only happens if the app is published. Running the app from VS is fine.

### To Reproduce

Take the Blazor WASM template and replace the code in FetchData.razor with

```
@code {
    private IReadOnlyCollection<WeatherForecast>? forecasts;
    protected override async Task OnInitializedAsync()
    {
        forecasts = await Http.GetFromJsonAsync<ImmutableList<WeatherForecast>>("WeatherForecast");
    }
}
```

publish the app and navigate to `fetchdata`

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 17.0.1
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

</details>

**Comment by srollinet** [comment]
@mkArtakMSFT Sure! https://github.com/srollinet/AssemblyTrimmingSerializationIssue

I made a simple console app. Is it relevant or should I create a Blazor app? 

to reproduce:
`dotnet publish; .\bin\Debug\net6.0\win-x64\publish\AssemblyTrimmingSerializationIssue.exe`

Here, when I build, I have a warning that doesn't appear in the Blazor app

```
Trim analysis warning IL2026: Program.<Main>$(String[]): Using member 'System.Text.Json.JsonSerializer.Deserialize<TValue>(String,JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.
```

**Comment by eiriktsarpalis** [comment]
This is expected behavior when using reflection-based serialization together with trimming. As the warning message suggests, the recommended workaround is to use an overload that takes accepts a source generated context. In your example:
```C#
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Collections.Immutable;

JsonSerializer.Deserialize<ImmutableList<string>>("[]", MySerializerContext.Default.ImmutableListString);
System.Console.WriteLine("Done");

[JsonSerializable(typeof(ImmutableList<string>))]
public partial class MySerializerContext : JsonSerializerContext
{
}
```
Works as expected in the trimmed application.
