### ISSUE TITLE
Assertion failed '(op3Reg != targetReg) || (op1Reg == targetReg)' during 'Generate code' 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#62267]
Superpmi replay is failing for following method on windows-x64

Most likely because of  #58196
```
ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp (6781) - Assertion failed '(op3Reg != targetReg) || (op1Reg == targetReg)' in 'System.Numerics.Matrix4x4:Lerp(System.Numerics.Matrix4x4,System.Numerics.Matrix4x4,float):System.Numerics.Matrix4x4' during 'Generate code' (IL size 675)

```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62262-merge-d207c81ab3b14b3f92/unix-x64/1/console.122dc30b.log?sv=2019-07-07&se=2021-12-22T02%3A42%3A41Z&sr=c&sp=rl&sig=TWtmGXhWg7AuFc9lSuVCD%2FMqEkj7ZjYwRxf2ZKSSSA0%3D

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
@weilinwa

**Comment by weilinwa** [comment]
@kunalspathak, sorry about the inconvenience, I'm working on it.

**Comment by kunalspathak** [comment]
Fixed in https://github.com/dotnet/runtime/pull/62382
