### ISSUE TITLE
Port MD4 implementation from mono/mono

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#62265]
In order to support [NTLM in Android](https://github.com/dotnet/runtime/issues/62264), we need a managed implementation of the MD4 algorithm.  The best place to pull from would be the one found in mono/mono.

The port should:
- Be an implementation detail and is not intended to be a public API
- Part of System.Net.Security
- Use [MD4.cs](https://github.com/mono/mono/blob/main/mcs/class/Mono.Security/Mono.Security.Cryptography/MD4.cs) and [MD4Managed.cs](https://github.com/mono/mono/blob/main/mcs/class/Mono.Security/Mono.Security.Cryptography/MD4Managed.cs)

/cc @GrabYourPitchforks

**Comment by MaximLipnin** [comment]
Addressed in https://github.com/dotnet/runtime/pull/62074
