### ISSUE TITLE
C# Cannot get default value from System.Type class

### ISSUE THREAD

**Issue by roland5572** [dotnet/runtime#62274]
If we need get a default value from a type, C# provides 

```var val = default(T);```

But if it's a Type variable, C# does not provide this feature:

https://docs.microsoft.com/en-us/dotnet/api/system.type

```
public void PrintDefaultValue(Type t)
{
    //C# does not have this API feature: GetDefaultValue
    Console.WriteLine(t.GetDefaultValue());
}
```

**Comment by zlatanov** [comment]
What about:

```c#
public void PrintDefaultValue(Type t)
{
    var defaultValue = t.IsValueType ? Activator.CreateInstance(t) : null;
    Console.WriteLine(defaultValue);
}
```

**Comment by roland5572** [comment]
> What about:
> 
> ```cs
> public void PrintDefaultValue(Type t)
> {
>     var defaultValue = t.IsValueType ? Activator.CreateInstance(t) : null;
>     Console.WriteLine(defaultValue);
> }
> ```

Yes, but if it's a nullable value, will it affect performance?
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types

If it can be implemented in C# built-in, will it reduce program overhead?
Because I can see ```Activator.CreateInstance()```

**Comment by zlatanov** [comment]
> Yes, but if it's a nullable value, will it affect performance?
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types

Nullable value type is actually `Nullable<T>` which is a value type, so it's the same and performance won't be different from other value types.



> If it can be implemented in C# built-in, will it reduce program overhead?
> Because I can see `Activator.CreateInstance()`

C# is a language, here we're talking about the runtime. I don't think the runtime could implement this any differently to have a measurable difference.

**Comment by roland5572** [comment]
> > Yes, but if it's a nullable value, will it affect performance?
> > https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-value-types
> 
> Nullable value type is actually `Nullable<T>` which is a value type, so it's the same and performance won't be different from other value types.
> 
> > If it can be implemented in C# built-in, will it reduce program overhead?
> > Because I can see `Activator.CreateInstance()`
> 
> C# is a language, here we're talking about the runtime. I don't think the runtime could implement this any differently to have a measurable difference.

Thank you. Do you think it will be a commonly used function that will be integrated into the C# library and provided as an API?

**Comment by zlatanov** [comment]
> Do you think it will be a commonly used function that will be integrated into the C# library and provided as an API?

I don't think so. I've never seen this and never needed it. Usually when a default value is wanted, one usually achieves it by not assigning anything to existing variable or field.

I am curious about your use case. Would you mind sharing why do you need to create default value dynamically per type? Also if it's for some comparison reasons (i.e. asking the question "Is this value the same as the default value?") you could very easily build a cache based on `Dictonary<Type, object>` or even `ConcurrentDictionary<Type, object>` where you could use `Activator.CreateInstance` only in the case when the type hasn't been looked up yet.

**Comment by grbell-ms** [comment]
> What about:
> 
> ```cs
> public void PrintDefaultValue(Type t)
> {
>     var defaultValue = t.IsValueType ? Activator.CreateInstance(t) : null;
>     Console.WriteLine(defaultValue);
> }
> ```

C#11 introduces explicit parameterless constructors for value types. This code would call that constructor rather than creating the default value.

**Comment by zlatanov** [comment]
> C#11 introduces explicit parameterless constructors for value types. This code would call that constructor rather than creating the default value.

That's a good point. Here is more explicit implementation to handle this case.

```c#
public static class DefaultValueHelper
{
    private static readonly ConcurrentDictionary<Type, IFactory> Cache = new();

    public static object? GetDefaultValue(Type type)
    {
        var factory = Cache.GetOrAdd(type, 
            static type => (IFactory)Activator.CreateInstance(typeof(Factory<>).MakeGenericType(type))!);

        return factory.GetDefaultValue();
    }

    private interface IFactory
    {
        object? GetDefaultValue();
    }

    private sealed class Factory<T> : IFactory
    {
        [MaybeNull]
        private readonly T _defaultValue;

        public object? GetDefaultValue() => _defaultValue;
    }
}
```

**Comment by Sergio0694** [comment]
> "C#11 introduces explicit parameterless constructors for value types."

@grbell-ms I know it was just a typo, but for others reading that might not know this, that feature is [already out in C# 10](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#improvements-of-structure-types) 😄

**Comment by danmoseley** [comment]
I think this is answered, thanks for all the comments.
