### ISSUE TITLE
WPF : Build Fault-Tolerant Composite Applications in .Net 6

### ISSUE THREAD

**Issue by HansBuenting** [dotnet/runtime#62272]
There is an article in MSDN magazine regarding a plugin structure in WPF (see link 1). The source code is based on .Net 4.5 and can probably easily be ported to 4.8. But how can all of this be implemented in .Net 6? Will it be possible to have a single Ui made up of different plugins with different versions of a dll? I know that there is now the AssemblyLoadContext to ensure separation of dlls. But how are user controls from the plugins embedded in the host application? In .Net 4.8 the following class is responsible for this (see link 2).

I found a few more links (link 3. and 4.) that address the issue. But I don't really find an answer. Does anyone know more than me and can help me?

1.)    https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/january/wpf-build-fault-tolerant-composite-applications

2.)    https://docs.microsoft.com/en-us/dotnet/api/system.addin.pipeline.frameworkelementadapters.viewtocontractadapter?view=netframework-4.8

3.)    https://github.com/dotnet/runtime/issues/16708#event-2996662783

4.)    https://stackoverflow.com/questions/66012470/system-addin-support-issue-while-migrating-wpf-a-composite-applications-to-net

**Comment by vitek-karas** [comment]
A better place to ask this would be the https://github.com/dotnet/wpf repo.
I remember that WPF currently has some issues when running with multiple AssemblyLoadContexts - so it might be a bit rought:
* https://github.com/dotnet/wpf/issues/1700
* https://github.com/dotnet/wpf/issues/3816

**Comment by HansBuenting** [comment]
Hi there,
you are absolutely right. I will close this issue and open a new one in the right area.
There doesn't seem to be any functionality to move this issue
