### ISSUE TITLE
Can 'system. Resources. Extensions' support lower versions of the. Netframework. For example, 4.0

### ISSUE THREAD

**Issue by hdefucom** [dotnet/runtime#62282]
If I use SDK style project files to develop. Net framework 4.0 projects and add non character resources, I can't use dotnetcli to build them

**Comment by KalleOlaviNiemitalo** [comment]
Problems with using only MSBuild.exe are:

- Needs licenses on a Visual Studio version that supports the target framework.
- Can only build on Windows.

**Comment by ericstj** [comment]
@rainersigwald does the dotnet CLI / SDK officially support building for `net4.0`?  That's surprising to me.  Many of the .NETFramework specific targets would be absent from the dotnet CLI.

In regards to the request to support `net4.0` in Sytstem.Resources.Extensions: our packages only support in-support frameworks.  cc @terrajobst 
https://github.com/dotnet/announcements/issues/190/
https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by KalleOlaviNiemitalo** [comment]
I wonder how hard it would be to backport the package externally.

**Comment by rainersigwald** [comment]
> @rainersigwald does the dotnet CLI / SDK officially support building for `net4.0`?  That's surprising to me.  Many of the .NETFramework specific targets would be absent from the dotnet CLI.

@marcpopMSFT or @chethusk might be better folks to answer that.

**Comment by ericstj** [comment]
cc @baronfel 
Closing this out here.  Our current position is that dotnet/runtime packages don't support out of support frameworks.  Additionally we don't believe the SDK supports targeting `net4.0`.  If it did, that might justify an exception here.  If we can get a solid support statement for that from SDK we could revisit this issue.
