### ISSUE TITLE
Loading `appsettings.json` with 600 lines of "data" is very slow in blazor wasm

### ISSUE THREAD

**Issue by markusrt** [dotnet/runtime#62287]
### Describe the bug

When adding an `appsettings.json` to a dotnet  core wasm project with 600 lines of "data", then loading this via `IOptions` is very slow. The performance depends on the size of the JSON. I.e. smaller configs are faster. Maybe the issue is related to deserialization.

#### What I did

- `dotnet new blazorwasm`
- Stripped out anything but counter
- Added a new service which makes use of `IOptions` to access configuration data
- Register dependency to service and options in `Program.cs`
- Inject my service to `Counter.razor`

#### What happens

Upon accessing Counter-page the client spends ~7 seconds in the constructor of `MicStepsService`:

![image](https://user-images.githubusercontent.com/299753/142771428-75cc5615-8dbf-49ae-9284-0fa15383e13f.png)

Delay is caused when accessing the config value:

```cs
 _configValue = config.Value;
```

Stripping down configuration reduces the delay according to config size. I also tried to change the code to read data from embedded resource using Newtonsoft.Json. This fixed the issue as well:

```cs
var assembly = Assembly.GetExecutingAssembly();
var resourceName = "NRZMyk.Services.MicSteps.json";

using (Stream stream = assembly.GetManifestResourceStream(resourceName))
using (StreamReader reader = new StreamReader(stream))
{
   var result = reader.ReadToEnd();
   var micSteps = JsonConvert
     .DeserializeObject<Dictionary<SpeciesTestingMethod, Dictionary<AntifungalAgent, List<MicStep>>>>(result);
}
```

#### Repro project

https://github.com/markusrt/SlowWasmAppSettings

### Exceptions (if any)

no Exceptions

### Further technical details
- ASP.NET Core version: 5.0.301
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Microsoft Visual Studio Enterprise 2019, Version 16.10.1
- Browser: Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)
- Include the output of `dotnet --info`:
  <details>
    <summary>dotnet --info Output</summary>
    
    ```
    $ dotnet --info
    .NET SDK (gemäß "global.json"):
     Version:   5.0.301
   Commit:    ef17233f86
  
  Laufzeitumgebung:
   OS Name:     Windows
   OS Version:  10.0.19042
   OS Platform: Windows
   RID:         win10-x64
   Base Path:   C:\Program Files\dotnet\sdk\5.0.301\
  
  Host (useful for support):
    Version: 5.0.7
    Commit:  556582d964
  
  .NET SDKs installed:
    3.1.300 [C:\Program Files\dotnet\sdk]
    5.0.301 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  To install additional .NET runtimes or SDKs:
    https://aka.ms/dotnet-download
  ```
  
  </details>

**Comment by mkArtakMSFT** [comment]
@ericstj can you please take a look at this? Thanks!

**Comment by ericstj** [comment]
The above link shows "good" performance when reading from a json file embedded in the assembly using System.Text.Json: https://github.com/markusrt/SlowWasmAppSettings/commit/bae75ce852361761d73fd57eb7a83ba9c72c3881#diff-96306734cfd98f4ac9c7b0fe8309f8ebc780a456578225ec3f17a5e5a9f898f5R29

But "bad" performance when using Microsoft.Extensions to [read from options](https://github.com/markusrt/SlowWasmAppSettings/blob/bae75ce852361761d73fd57eb7a83ba9c72c3881/MyCode/MicStepService.cs#L20).  This implies that the problem may not be in deserialization, but perhaps with options or the way that the app.settings file is fed into options.   I'm not super familiar with how ASP.NET sets this up.  Is it possible that it's using a network stream to read [appsettings.json](https://github.com/markusrt/SlowWasmAppSettings/blob/bae75ce852361761d73fd57eb7a83ba9c72c3881/wwwroot/appsettings.json) and that's what's introducing the delay?  cc @pranavkm @eerhardt

**Comment by eerhardt** [comment]
I ran the app and looked at the `Network` tab in F12 tools. I am seeing this during the hang:
![image](https://user-images.githubusercontent.com/8291187/145256851-aea939d3-fde1-4923-b564-557c5a9c2dc0.png)

And then once it completes, I see:

![image](https://user-images.githubusercontent.com/8291187/145256960-9009a0ab-0760-477b-a969-8b285042fd69.png)


Notice that the `blazor-hotreload` request is taking ~4 seconds to complete. And also the `MicStepsService` is taking ~4 seconds to complete. So my initial thought is that hotreload is blocking the execution for some reason.

@pranavkm ?

**Comment by pranavkm** [comment]
@eerhardt does this happen with the hot reload feature turned off? You could do it in VS or by running `dotnet run`. That said, it might be worthwhile for us to look at this. Blazor has to do some slightly weird things to read the appSettings - it has to fetch it ahead of time and use interop for .NET to be able to read it. Maybe there are some inefficiencies there.

@markusrt have you considered using a regular json file to include your content? If this problem is specific to the settings file as @ericstj pointed out, perhaps that would remediate your issue. It would also avoid the extra hop of going from the settings.json to config dictionary to your model and let you go `var settings = Client.GetAsJsonAsync<MyCoolModel>("settings.json")`. It'd be a lot cleaner in my opinion.

**Comment by markusrt** [comment]
@eerhardt I have  it deployed but anyhow neither locally nor remote there is any network activity in after clicking on "Counter" until the page is rendered. I am actually running it via `dotnet run`.

On the performance tab I see many tiny functions being busy causing the UI to freeze, however there is no clue on any specific bottleneck:
![image](https://user-images.githubusercontent.com/299753/145288138-ff48390c-2e0e-494b-88e4-8af49f041a57.png)

**Comment by markusrt** [comment]
@pranavkm I agree that this is more then just configuration. Adding a JSON file somewhere or performing a backend request would definitely solve the issue. Also my workaround using embedded resources is super fast.
In the real application the "Service" is actually part of a `netstandard` business logic project. I used `IOptions` injection as the library is not aware that it's being used in a Blazor-App.

I spent some time wondering about the UI freeze and thought to share the insights with you. Maybe the root cause points to some generic performance improvement potential.

**Comment by eerhardt** [comment]
OK, I did some more investigation, and it looks like the hot reload issue above is a red-herring. The slowness happens in `dotnet run` for me as well.

I narrowed it down to this [line](https://github.com/markusrt/SlowWasmAppSettings/blob/bae75ce852361761d73fd57eb7a83ba9c72c3881/Program.cs#L16):

```C#
    builder.Configuration.Bind(options);
```

Specifically it is the `Bind` method. Changing that code to:

```C#
    var c = builder.Configuration;
    global::System.Console.WriteLine($"here {DateTime.Now}");
    JsonStreamConfigurationProvider provider = (JsonStreamConfigurationProvider)((IConfigurationRoot)c).Providers.First();
    provider.TryGet("Breakpoint:MicSteps:Vitek:Micafungin:0:Title", out string val);
    global::System.Console.WriteLine($"here2 {DateTime.Now} {val}");
    c.Bind(options);
    global::System.Console.WriteLine($"done {DateTime.Now}");
```

Produces:

```
info: SlowWasmAppSettings.MyCode.MicStepsService[0]
      configType_factory__validations: Microsoft.Extensions.Options.IValidateOptions`1[SlowWasmAppSettings.MyCode.BreakpointSettings][] - 0
blazor.webassembly.js:1 here 12/8/2021 5:42:40 PM
blazor.webassembly.js:1 here2 12/8/2021 5:42:40 PM ≤0,06
blazor.webassembly.js:1 done 12/8/2021 5:42:44 PM
blazor.webassembly.js:1 info: SlowWasmAppSettings.MyCode.MicStepsService[0]
      config.Value after: 3999ms
blazor.webassembly.js:1 info: SlowWasmAppSettings.MyCode.MicStepsService[0]
      Found: 517 values in total
blazor.webassembly.js:1 info: SlowWasmAppSettings.MyCode.MicStepsService[0]
      Exiting constructor after: 4001ms
```

Configuration binder works using Reflection - and there are over 1,000 name value pairs in that json file. So yes, I can imagine this being slow on interpreted WASM.

**Comment by markusrt** [comment]
@eerhardt Not sure if I interpreted your assumption correctly, but removing properties from MicSteps did not speed up processing. Shouldn't this be the case if reflection is the culprit?

See https://github.com/markusrt/SlowWasmAppSettings/compare/TryToReduceAmountOfReflection?expand=1

Actually, I coincidentally found a way to make it even slower by using only dictionaries instead of the custom type (see commented code in branch above)

**Comment by ericstj** [comment]
> Shouldn't this be the case if reflection is the culprit?

Depends on what aspect of Bind is expensive.  I don't think reducing properties really changes much this is the loop it skips:
https://github.com/dotnet/runtime/blob/8ae1c4972610722013e6664fe59403a176a8d81a/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L233-L236

**Comment by eerhardt** [comment]
Notice the line above that code:

https://github.com/dotnet/runtime/blob/8ae1c4972610722013e6664fe59403a176a8d81a/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L212

For every object in the payload, it is getting all the properties on the type and doesn't cache them.

AFAIK, Configuration Binder isn't really meant to be used to deserialize large amounts of data. It's main use case is to take configuration data (connection strings, app settings, etc) and turn them into objects. Configuration data usually isn't hundreds/thousands of settings. I would suggest using a different mechanism for bringing this data into your app.

Another question: have you tried [AOT compiling](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#ahead-of-time-aot-compilation) the app and measuring the performance?

**Comment by markusrt** [comment]
@eerhardt Just tried AOT but this does not seem to change anything:
![image](https://user-images.githubusercontent.com/299753/145894921-d9468d49-a015-49e9-9f9c-fce27cd49dbe.png)

Added the following to `SlowWasmAppSettings.csproj`

```xml
<PropertyGroup>
  <RunAOTCompilation>true</RunAOTCompilation>
</PropertyGroup>
```

and executed `dotnet workload install wasm-tools` before running again.

> AFAIK, Configuration Binder isn't really meant to be used to deserialize large amounts of data. It's main use case is to take configuration data (connection strings, app settings, etc) and turn them into objects. Configuration data usually isn't hundreds/thousands of settings. I would suggest using a different mechanism for bringing this data into your app.

I agree to that and would change my code accordingly. As long as you agree that this issue is not pointing to another root cause  we could close it for now.

**Comment by eerhardt** [comment]
> and executed dotnet workload install wasm-tools before running again.

in order to run AOT’d you also need to ‘dotnet publish’ and run the published app.

**Comment by markusrt** [comment]
@eerhardt thanks for the hint. Missed that in the documentation on AOT 🙄 

No its running published: https://markusrt.github.io/SlowWasmAppSettings

The following timings are measured on my machine:

- Published with Release (w/o AOT) - 2100 ms
- Published with Release + AOT - 1400 ms

**Comment by eerhardt** [comment]
@markusrt - any objections to closing this issue as "answered"? Basically my answer is to not use ConfigurationBinder for large amounts of data. It is not tuned for performance and I don't think it is worth the effort to try to make it more performant. There are other APIs (like JsonSerializer) if you want need to de-serialize large amounts of data.

**Comment by markusrt** [comment]
@eerhardt fine with me. Thanks for your support!
