### ISSUE TITLE
System.Windows.Extensions outerloop test SoundPlayerTests.LoadAsync_SourceLocationFromNetwork_Success failing

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#62305]
Outerloop test SoundPlayerTests.LoadAsync_SourceLocationFromNetwork_Success(String sourceLocation) is failing

Found in the [build ](https://github.com/dotnet/runtime/pull/62095/checks?check_run_id=4401813050) 

```
C:\h\w\ACCB09AD\w\AD9E09AC\e>"C:\h\w\ACCB09AD\p\dotnet.exe" exec --runtimeconfig System.Windows.Extensions.Tests.runtimeconfig.json --depsfile System.Windows.Extensions.Tests.deps.json xunit.console.dll System.Windows.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.Windows.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Windows.Extensions.Tests (found 11 of 43 test cases)
  Starting:    System.Windows.Extensions.Tests (parallel test collections = on, max threads = 2)
Process terminated. Assertion failed.
   at System.Media.SoundPlayer.LoadStream(Boolean loadSync) in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 311
   at System.Media.SoundPlayer.LoadAsync() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 162
   at System.Media.Test.SoundPlayerTests.LoadAsync_SourceLocationFromNetwork_Success(String sourceLocation) in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 134
```
Seem more [log](https://helix.dot.net/api/2019-06-17/jobs/c629531c-eec7-4f42-9138-6fc020390ec2/workitems/System.Windows.Extensions.Tests/console)

**Comment by danmoseley** [comment]
@huoyaoyuan this was broken by 89e3040713c9 #57896. This assert is requiring that there be a stream set up at the start of the method that is going to end up setting up the stream.

Note, these tests are OuterLoop so you wouldn't have seen it locally. You have to do something like `dotnet build /t:test /p:outerloop=true .../tests/System.Windows.Extensions.csproj`

**Comment by danmoseley** [comment]
Do you remember any context on this one? I wonder if rather it should be `if (loadSync && _stream!.CanSeek)` and possibly should assert that `_stream == null` if `loadSync` is false. I didn't examine closely. Happy for one of us to take this issue unless you want to.

Also, I wonder why this wasn't reported before, since I see the change was months ago, we do run outer loop tests continuously.

**Comment by danmoseley** [comment]
I threw up a PR.
