### ISSUE TITLE
[wasm] `Loader/classloader/explicitlayout/NestedStructs/case04/case04.sh` failing with `FAIL: object and non-object field overlap was not detected`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#62303]
[Rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1494433&view=logs&j=2296eecc-f5ab-523f-c15d-f45eef1bfdea&t=d328b091-66a6-5d96-5a21-3cf77f57f009), and [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8237b72af558483d89/Loader.classloader/1/console.0530c892.log?sv=2019-07-07&se=2021-12-22T20%3A57%3A59Z&sr=c&sp=rl&sig=hts3uBp51%2BiLsDcBSQOos2Sp4n4RKdFmycAMSJG1TVQ%3D)

```
    Loader/classloader/explicitlayout/NestedStructs/case04/case04.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A3F40905/w/ABAB093F/uploads/Reports/Loader.classloader/explicitlayout/NestedStructs/case04/case04.output.txt
      Raw output:
      BEGIN EXECUTION
      Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
        AppDir: /datadisks/disk1/work/A3F40905/w/ABAB093F/e/Loader/classloader/explicitlayout/NestedStructs/case04/WasmApp/
        TestBinDir: /datadisks/disk1/work/A3F40905/w/ABAB093F/e/Loader/classloader/explicitlayout/NestedStructs/case04
        ArtifactsBinDir: 
      /datadisks/disk1/work/A3F40905/p/build/WasmApp.targets(210,5): warning : Could not find $(AssemblyName)=WasmTestRunner.dll in the assemblies to be bundled. [/datadisks/disk1/work/A3F40905/p/wasm-test-runner/WasmTestRunner.proj]
      Incoming arguments: --run case04.dll
      Application arguments: --run case04.dll
      console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
      console.info: Initializing.....
      FAIL: object and non-object field overlap was not detected
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
```

IIUC, this is a new test that was added in https://github.com/dotnet/runtime/pull/61467 . cc @simonrozsival

FYI, the diff from the previous passing rolling build - https://github.com/dotnet/runtime/compare/a61c1a3c..ad9979381706d1976e4d26e13cb88d6147264968

And it slipped through because we are not running the wasm/RuntimeTests on PRs. @lewing @steveisok Should we enable them for wasm on PRs? Or maybe based on some path changes?

**Comment by lambdageek** [comment]
Let's disable the test on wasm for now.

@simonrozsival wasm is 32-bit.  Maybe this test only has overlapping fields on 64-bit platforms?

**Comment by lambdageek** [comment]
Yea this field doesn't actually overlap the object on a 32-bit arch

https://github.com/dotnet/runtime/blob/b83fee9f6e3442b9808eee3c436499c6f13a648e/src/tests/Loader/classloader/explicitlayout/NestedStructs/case04.cs#L30

**Comment by simonrozsival** [comment]
@lambdageek Yes, that should be the problem. In the other tests the conflicting fields have the same explicit field offset. In `case04` I intentionally used different offsets and I didn't notice that it behaves differently on 32 bit platforms. Thanks for fixing it!
