### ISSUE TITLE
JIT does not recognize Vector<T>.Count and Vector{128|256}.Count is unsigned in div / mod

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#62326]
```c#
public int VecSize => Vector<float>.Count;

public int M1(int length) => (int)((uint)length % Vector<float>.Count);
public int M2(int length) => (int)((uint)length % (uint)Vector<float>.Count);

public int Vec256Size => Vector256<float>.Count;

public int N1(int length) => (int)((uint)length % Vector256<float>.Count);
public int N2(int length) => (int)((uint)length % (uint)Vector256<float>.Count);
```
The `.Count` are treated as constant, but for the division and modulo it's not treated as unsigned to allow bit-hack fast computation.

```asm
; Core CLR 6.0.21.52210 on amd64

C.get_VecSize()
    L0000: mov eax, 8
    L0005: ret

C.M1(Int32)
    L0000: mov eax, edx
    L0002: mov rdx, rax
    L0005: sar rdx, 0x3f
    L0009: and rdx, 7
    L000d: add rdx, rax
    L0010: and rdx, 0xfffffffffffffff8
    L0014: sub rax, rdx
    L0017: ret

C.M2(Int32)
    L0000: mov eax, edx
    L0002: and eax, 7
    L0005: ret

C.get_Vec256Size()
    L0000: mov eax, 8
    L0005: ret

C.N1(Int32)
    L0000: mov eax, edx
    L0002: mov rdx, rax
    L0005: sar rdx, 0x3f
    L0009: and rdx, 7
    L000d: add rdx, rax
    L0010: and rdx, 0xfffffffffffffff8
    L0014: sub rax, rdx
    L0017: ret

C.N2(Int32)
    L0000: mov eax, edx
    L0002: and eax, 7
    L0005: ret
```

Edit: this link is wrong, see comment below.
At least fo .NET 6 on [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKDMq0ASgwB2GVsxoBJcW1G52XPn2IBmSgCZyAYXIBvPuWOUNrceQBqMMAGVWALxjkAvAD4rNjNAA8AMwAbCGwMNxodCDEMHl4TciMTdXJzDHIAWSoAChTyAJhRAHMMAAsASlcPPMKS8gBSTzBvKH8gkLCIqJi4pJy0zWyLKqKyivIBjFLMzIYU0qGa+unZ60bfQODQ8MjxUq6TBOMeixXNAFYkeydRlaazpBaN9u3og/jYxLMLOiyc+ZH3XL5YZ1Bq3c4PNpbTqvI6pOj9X5AkrlAHjSZLHZ/EEYiY3aB3CGbDo7GIAXyAA=) -- didn't find any issue or PR addressing this for .NET 7.

**Comment by EgorBo** [comment]
@gfoidl I am not sure I understand, in your case `length` is an unknown signed integer so it can be negative, can't it?
```csharp
public int M1(int length) => length % Vector<float>.Count;
public int M2(int length) => (int)((uint)length % (uint)Vector<float>.Count);
```
these two don't look equal to me

**Comment by EgorBo** [comment]
![image](https://user-images.githubusercontent.com/523221/144591644-5cef336c-4e1d-4e4a-ae1d-facb47dfaf64.png)

**Comment by gfoidl** [comment]
Ah, you're right. I showed the wrong one.
Here `length` is e.g. from a Span, so not negative, therefore I can cast it to `uint`. [This sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKDMq0ASgwB2GVsxoBJcW1G52XPn2IBmSgCZyAYXIBvPuWOUNrceQBqMMAGVWALxjkAvAD4rNjNAA8AMwAbCGwMNxodCDEMHl4TciMTdXJzDHIAWSoAChTyAJhRAHMMAAsASlcPbPFSzMyGFNK8wpLyAFJPMG8ofyCQsIio0pi4pJy0zSrUpqKyivJJmrqG6Zb2perrTt9A4NDwyOrhkwTjUYtNzQBWJHsnOc2uq6Qe3f6D6JP42MSzCzosnIrWbueYNWr1apAtodR7XF59faDI6nX6pOgTQH5GblEELcHLLGreYQjClB7QJ7wvYDQ58AC+QA) is the correct one (sorry).

**Comment by EgorBo** [comment]
ah, makes sense now, should be simple to fix:

![image](https://user-images.githubusercontent.com/523221/144593808-6916c09e-a69d-41b1-a939-f62ffed595b2.png)
