### ISSUE TITLE
[API Proposal] [.NET 7] [EPIC] : public shared class ->multiple pathway for object oriented constructions (ooc)

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62327]
### Background and motivation

We currently don't have a way to combine multiple type into a single type.

### API Proposal

Let the compile and IDE recognize the synctax then it will be fine, the class just inheirts all shared class in the background like you would inheirt one which is what we're doing.

### API Usage

```C#
public shared class A
{
    public int e1=0;
    public string e2;
}
public shared class B
{
    public float e2;
}
public shared class C
{
    public B e3;
    public int e4;
}
public class D:A,B,C
{
    public shared D()
    {
        pathway (instance):
        //Pretend someone passed instances of class A, B, C
case A://Refer to by class name
        return new { _=> instance.e1,
                           _=>instance.e2 };//anonymous type for infered name
case B:
        return new { _=>instance.e2};
case C:
        return new { _=instance.e3};//e4 ignored
        default:
        //resolve conflicts here, so when D is constructed from one class it's ok, but because type composition (you can build object of class D by building it with A first, then B, then C etc.) is allowed when D is composed with multiple types the members that's inherited but is conflict with eachother should be resolved.
        B->e2=>A->e2; //e2 from B overides e2 from A when both classes are used to compose D in the past or in the future
    }
}//D has all members from A,B,C, constructor makes sure any conflicts between combined classes are resolved
```

### Alternative Designs

Just another idea, if an object is a composite class of A & B, then this class should be able to be used to compose D as long as D implemented / inherited the two shared class.

Because .NET remembers the type of the object, even when you cast the object to { object } type, shared classes for now should follow the type safety we have, that means though you can somehow using a new syntax to create class D from A you can't cast A to D.

If class D didn't implement a pathway to construct from class A (case A:), a warning perhaps would be suitable, while this scenario means A is ignored when used / present in the composing / construction of the class / shared class (naming unsettled).

**Comment by Xyncgas** [comment]
The benifit of this is you can construct an object step by step, I still havent figured out the syntax yet, but the idea is there which I think is powerful because one of the powerful thing from functional programming that we could get was its ability to compose at compile time what can happen and kind of link the things together, with shared class, you can do this now, which the way I see it is just simply one class having all three classes' instance, at least it's one way to implement it, which is simple enough, which then it's synctatic sugars added on top of it to make members of all three instances all available as if they're one class.

Type casting is going to work imo.

One thing I am worried is when the types are having members of the same name and we ended up hiding them or whatever, then the class isn't really 3 complete class acting as one, and we need to figure out how to serialize to it. but we will always have the constructor / pathway as a map, which holds the definition of how the class was composed of the 3 (or others.) classes, from there we know which members of the current composed class is belonged of the shared classes.

**Comment by Xyncgas** [comment]
Changed the title so more people are lured to this conversation

**Comment by teo-tsirpanis** [comment]
Hello, proposals for new C# language features go to [discussions in the `dotnet/csharplang` repository](https://github.com/dotnet/csharplang/discussions).

**Comment by Xyncgas** [comment]
> Hello, proposals for new C# language features go to [discussions in the `dotnet/csharplang` repository](https://github.com/dotnet/csharplang/discussions).

Thank u.
Would you like to move this for me because I am not familiar of how. but you can teach me if you'd like to

**Comment by Xyncgas** [comment]
I will do it myself and close the issue in an hour.
you can close the issue if I don't after that.
