### ISSUE TITLE
.net 6 blazor can't publish

### ISSUE THREAD

**Issue by wangjunjx8868** [dotnet/runtime#62332]
### Describe the bug
 D:\Users\wangqi\source\repos\BlazorApp2\obj\Release\net6.0\wasm\for-publish
 C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\include\mono-2.0
 C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.0\runtimes\browser-wasm\native\include\wasm
 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot/include/SDL
 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot/include\compat
 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\lib\clang\13.0.0\include
 C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.0\tools\emscripten\cache\sysroot/include
End of search list.
error: unable to open output file 'C:\Users\閻滃銈篭AppData\Local\Temp\tmp926C.tmp': 'no such file or directory'
1 error generated.

### Exceptions (if any)
actually temp path is  C:\Users\哈哈\AppData\Local\Temp\tmp926C.tmp.
so  not found path.
### Further technical details

</details>

**Comment by pranavkm** [comment]
@radical looks like a wasm-tools issue. Feel free to transfer it back if you think it's an issue with the Blazor SDK.

**Comment by radical** [comment]
@wangjunjx8868 are you building this from the command line? If so, then could you build it with `-bl`, and share the generated `msbuild.binlog`?

**Comment by Xyncgas** [comment]
lol
