### ISSUE TITLE
Access violation executing location when closing an application that hosts the .NET 5.0 Runtime via CoreCLRHost

### ISSUE THREAD

**Issue by Pycorax** [dotnet/runtime#62346]
### Description

I'm currently building a game engine in C++ that leverages C# as a scripting language for game logic. To enable this feature, I'm currently hosting the .NET 5.0 runtime using CoreCLRHost to execute C# code that is compiled as a DLL. 

Currently, we are encountering an issue in certain cases where upon closing the application normally (the application's main() returns), the .NET Runtime will encounter a crash at line 940 of rcthread.cpp due to a read access violation. This is even after we have used `coreclr_shutdown_ptr` to shutdown the hosted runtime.

I understand that HostFxr is now the preferred way to host the .NET Runtime. However, we ran into issues using that implementation. We also require C++/CLI support to create bindings between the core engine code in C++ and the gameplay code in C#. Hence, we are trying to host .NET 5.0 Runtime using CoreCLRHost.

Is there any way to resolve or at the very least, suppress the error?

A sample repository of this implementation on its own can be seen here: https://gitlab.com/black-eye-studios/experimentation/native.netcorehost

### Reproduction Steps

In our testing, this crash seems to occur more often on Intel systems as opposed to AMD systems where it is very rare. It is hard to determine if this is simply a coincidence with other factors or an actual factor that is causing the issue. This is also quite rare on the specified repository. We have a private repository which we cannot share here where it is more common. Please contact us for access to this private repository if it would help.

1. Download the https://gitlab.com/black-eye-studios/experimentation/native.netcorehost repository
2. Open with Visual Studio 2019 with the following workloads installed:
    - C++ Desktop
    - .NET Desktop Development
3. Set the Native.NETHost project as the start up project
4. Build and Run

As the error only appears sometimes, multiple runs might be required even on an Intel system.

### Expected behavior

Clean exit of the application with no read access violations.

### Actual behavior

Read access violation at line 940 of rcthread.cpp

### Configuration

.NET Version: 5.0.8
OS: Windows 10 Build 19043.1348
Architecture: x64
Specific to configuration: Not tested on other configurations

**Comment by vitek-karas** [comment]
I tried to repro this, but no luck so far. Given the place where it fails, are you running this with or without a debugger?
Would it be possible to take a crashdump when it happens?

**Comment by vitek-karas** [comment]
Potentially similar to https://github.com/dotnet/runtime/issues/62579 (although that one does not use native hosting).

**Comment by Pycorax** [comment]
Interesting. We'll put up a crash dump when we manage to get it again. Fortunately/unfortunately, it's not occurring recently for some reason. 

Just to check though, would dotnet-dump work in this scenario where dotnet is being hosted?

**Comment by vitek-karas** [comment]
I think it should, I'm not aware of anything special related to hosting which would affect it. (But I could be wrong).

**Comment by Pycorax** [comment]
Apologies for the long turn around. This dump is running with the debugger on a separate project and the crash seems linked to the attempt at unloading coreclr.dll. I'm not sure how else I could use this information to debug, Hopefully, you can shed some light on it? The file is rather big so I've uploaded it to OneDrive and linked it [here ](https://1drv.ms/u/s!ArTyxrsr6G84r4I2bzyNoWSv8XGcnA?e=MsaatU) instead.

**Comment by vitek-karas** [comment]
@VSadov could you please take a look?

**Comment by janvorli** [comment]
@Pycorax is the FreeLibrary that I can see called from the dump freeing the coreclr.dll library? The thing is that you should never try to free coreclr.dll. It is not designed to be unloaded from memory.

**Comment by Pycorax** [comment]
@janvorli Yes it is actually. I will remove that line and test it out again. I will update on whether or not if it completely eliminates the crashes.

**Comment by Pycorax** [comment]
I'm happy to report after testing the fixes for a month extensively, that the issue no longer occurs. Cheers!
