### ISSUE TITLE
Consider adding RegexOptions.RightToLeft support back to compilation

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#62345]
We rewrote the entirety of the code generation (RegexOptions.Compiled and the source generator) for Regex in .NET 7.  The only thing the old code generation was still being used for was supporting RegexOptions.RightToLeft, and so we decided to fall back to the interpreter for RightToLeft and delete all of that older code generation (if you specify RegexOptions.Compiled | RegexOptions.RightToLeft, the Compiled part will just be ignored).  There's nothing fundamental that prevents us from adding RegexOptions.RightToLeft support to the newer code generation, it's just non-trivial work for little perceived gain (RightToLeft use is very rare).  If, however, it turns out compilation support for RightToLeft is warranted, we could add such support into both RegexCompiler and the source generator.

https://github.com/dotnet/runtime/pull/62318 is the PR deleting the old code generation.  Should we want to add RightToLeft support to the newer code generation, parts of that PR may be reverted to bring back the functional FindFirstChar override implementation; it's the generated Go override that needs to be rewritten from scratch.

**Comment by danmoseley** [comment]
> non-trivial work for little perceived gain 

Not just the implementation work but of course the maintenance cost, which for regex is significant.

**Comment by stephentoub** [comment]
If we don't want to add back full RTL compilation support but still want some level of lookbehind compilation support, we could  pretty easily I expect special-case the following as the entire body of lookbehinds:
- RegexNode.Set, RegexNode.One, RegexNode.NotOne, RegexNode.Multi
- RegexNode.Boundary, RegexNode.Beginning
- RegexNode.Empty
and that would get us more than half of the ~4% of regexes in our corpus that use lookbehinds.

**Comment by stephentoub** [comment]
It ended up not being a large amount of work nor a large increase in complexity. #66280 takes care of it.
