### ISSUE TITLE
.NET Standard 2.0 should have an overload of Encoding.GetString() that takes a ReadOnlySpan<byte> parameter.

### ISSUE THREAD

**Issue by nathanAjacobs** [dotnet/runtime#62340]
I know this already exists in .NET Core / .NET 5+ / .NET Standard 2.1. However, Spans can be used in .NET Standard 2.0 and an unsafe / array allocation workaround shouldn't be required.

See related issue: [https://github.com/dotnet/runtime/issues/55998#issuecomment-883471943](https://github.com/dotnet/runtime/issues/55998#issuecomment-883471943)

**Comment by danmoseley** [comment]
@nathanAjacobs .NET Standard 2.0 is a snapshot of a point in time. It is a description of a common set of API's that several platforms offered at that time. It is not possible to go back in time and add to it without breaking what it is.

What platform (as opposed to standard version) do you need this on?

**Comment by nathanAjacobs** [comment]
> 

Well that's the thing, I'm creating a class library in .NET Standard 2.0 that I would like to be able to use across different frameworks (.NET 6 and Unity).

I get that it can't be added to .NET Standard 2.0 directly, but could an extension method be provided via a Nuget package though? Or am I misunderstanding how nugets work with specific framework versions?

**Comment by ryank425** [comment]
@nathanAjacobs 

https://unity3d.com/unity/beta/2021.2.0b6

Unity supports .NET Standard 2.1, so I don't think you would have to be stuck with .NET Standard 2.0 as all of .NET Framework supported under .NET Standard 2.0 (up to 4.6.1) will be discontinued soon.

https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework

@danmoseley  I think https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework docs has a typo there. ".NET Framework 4.5.2, 4.6, and **4.61** will retire on April 26, 2022" . Clicking Edit button on this doc leads to https://github.com/MicrosoftDocs/lifecycle-pr/blob/live/lifecycle-docs/faq/dotnet-framework.yml which is 404 for me, and I didn't know who to tell this to.

**Comment by danmoseley** [comment]
@gewarren how can @ryank425 edit  https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework  ? seems the edit button is broken.

**Comment by gewarren** [comment]
> @gewarren how can @ryank425 edit https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework ? seems the edit button is broken.

I have a PR to fix it. The 404 is because you're not joined to the MicrosoftDocs organization.

**Comment by nathanAjacobs** [comment]
@ryank425 Unity is supporting .NET Standard 2.1 starting with version 2021.2. Which means any version before that going back to 2018.1 is limited to .NET Standard 2.0.

It just seems strange to me that I can use System.IO.Pipelines in .NET Standard 2.0 via nuget, but I can't decode the ReadOnlySpan<byte> objects back into a string easily.

**Comment by mayuki** [comment]
Because S.I.Pipelines uses Span in System.Memory, it additionally requires System.Memory.dll to be used in Unity. .NET Standard 2.0 does not include Span.

Even if the API is added, it cannot be used until Unity implements it, so it is effectively the same as .NET Standard 2.1.

If you need Encoding.GetString(ROS<byte>), you can implement/use it as an internal extension method and it will work.

**Comment by gewarren** [comment]
> @gewarren how can @ryank425 edit https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework ? seems the edit button is broken.

The page has been updated now: https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework#what-is-the-lifecycle-policy-for-different-versions-of--net-framework-. I also filed an issue to say that the Edit button should be disabled or point to a public repo.

**Comment by jeffhandley** [comment]
Per the comments above, we cannot retroactively add this to .NET Standard 2.0, and availability in .NET Standard 2.1 is on the horizon. With that status, we wouldn't be able to justify a new package or other vehicle to address this further.

Thanks for submitting the issue, @nathanAjacobs. Hopefully .NET Standard 2.1 and/or the internal extension method @mayuki suggested help you here.
