### ISSUE TITLE
[wasm] browser-bench appstart is broken on main

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#62357]
![image](https://user-images.githubusercontent.com/198130/144668410-3760b009-d05f-4d99-893f-2503ea453d84.png)
Seems like the startup changes probably broke it somehow. Ran into this while trying to use it to test something. cc @pavelsavara 
I tried to figure out why it seems to be retrying the config load operation constantly and from reading the code it shouldn't be happening, but it is. Not sure if that's related to the failure.

**Comment by pavelsavara** [comment]
It's that fetch in the iframe could not download the config file.

**Comment by radekdoulik** [comment]
Yes, it is the iframe repeated loading as we try to measure the stratup time. I will look at it.

**Comment by radekdoulik** [comment]
The sample should work meanwhile, at least it does for me in the chrome.

The errors come from fetches of `mono-config.json` from iframes, where dotnet-serve response is 304. We are looking at it with @pavelsavara.
