### ISSUE TITLE
Question: How is the API diff made?

### ISSUE THREAD

**Issue by bitbonk** [dotnet/runtime#62356]
With every new release of .NET there is now this very helpful [API diff folder](https://github.com/dotnet/core/tree/main/release-notes/6.0/api-diff). This is something that should be adopted by many .NET libraries in the community. 

Where can we as library authors learn how you generate these diff folders, so we can do the same thing for our NuGet packages.

**Comment by danmoseley** [comment]
I believe we use an tool called apireviewer/asmdiff that is internal. @safern do you know of a way to do it with public tools?

**Comment by safern** [comment]
We have made the tool public a few months ago: https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.AsmDiff

You can build that or download this package: https://dnceng.visualstudio.com/public/_packaging?_a=package&feed=dotnet-eng&package=Microsoft.DotNet.AsmDiff&protocolType=NuGet&version=7.0.0-beta.21603.1 and just run it.

You can see the command line args here: https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.AsmDiff#required-options

**Comment by danmoseley** [comment]
Ah great.

> This is something that should be adopted by many .NET libraries in the community.

@bitbonk your feedback on whether this will fill the need is welcome.

**Comment by safern** [comment]
Something to consider is that the current AsmDiff is using CCI still and it lacks a lot of language features, i.e APIs that return or take a function pointer. However, with the new API Compat object model built on top of Roslyn, I think it would be simple to write a differ using Roslyn on top of that object model.

**Comment by stephentoub** [comment]
Closing as answered.
