### ISSUE TITLE
DllImportGenerator is failing in Mono llvmfullAOT

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#62372]
https://dev.azure.com/dnceng/public/_build/results?buildId=1496054

```
Build FAILED.

/__w/1/s/src/mono/msbuild/aot-compile.proj(19,9): error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/Microsoft.Interop.DllImportGenerator.dll" exited with code 1.
/__w/1/s/src/mono/msbuild/aot-compile.proj(19,9): error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/Microsoft.Interop.SourceGeneration.dll" exited with code 1.
    0 Warning(s)
    2 Error(s)
```

**Comment by agocke** [comment]
@jkoritzinsky Looks like this was somehow caused by https://github.com/dotnet/runtime/commit/84b55d9700da70e3e68456929a4b49295772d87b

**Comment by jkoritzinsky** [comment]
We're probably constructing Core_Root in some way that either overrides OutputPath or OutputItemType for ProjectReferences

**Comment by lambdageek** [comment]
@jkoritzinsky we should exclude DllImportGenerator from Core_Root.  For the various Mono AOT testing legs, I think we AOT every assembly in Core_Root. The Mono AOT process needs to be able to resolve every assembly reference (using the Core_Root and the individual test - the search path is constructed in src/mono/msbuild/aot-compile.proj although I don't know the details of how this gets used by the runtime tests build script).  In this case DllImportGenerator is in Core_Root but the various Roslyn assemblies aren't.

I think the cleanest approach would be to ensure that the DllImportGenerator assembly doesn't end up in Core_Root - after all it's needed only at build-time not run-time.  (And I assume Core_Root is not used to build the tests)

**Comment by jkoritzinsky** [comment]
@lambdageek I agree with your assessment. These two assemblies should be excluded from Core_Root.
