### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by lilmarsgirl** [dotnet/runtime#62387]
Hi there, 

I play Stardew Valley with SMAPI and mods. Recently my game has been crashing and I get this line in my log:

`/Users/lydia/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS/StardewValley: line 133: 52229 Segmentation fault: 11  dotnet StardewModdingAPI.dll "$@"`

How do I fix this?

**Comment by GlitchMasta47** [comment]
This is extremely unlikely to be relevant to the .NET runtime and more likely to be relevant for a specific mod you've installed. If you've made changes or additions to mods recently, try undoing those changes and seeing if the error is resolved. If not, go to communities relevant for Stardew Valley modding and ask there with a list of mods and what you've tried.

**Comment by lilmarsgirl** [comment]
> This is extremely unlikely to be relevant to the .NET runtime and more likely to be relevant for a specific mod you've installed. If you've made changes or additions to mods recently, try undoing those changes and seeing if the error is resolved. If not, go to communities relevant for Stardew Valley modding and ask there with a list of mods and what you've tried.

Okay thank you, I posted the issue in the SDV community and they had no idea how to fix so I assumed it was more to do with .NET. I will look into it further.

**Comment by ericstj** [comment]
Agreed with what is said here already.  A seg fault involving unknown user code isn't going to get any traction.  If you can demonstrate a bug in the runtime with an isolated repro or a sufficient description for us to construct an isolated repro then that's something we can look at.  Closing for now.
