### ISSUE TITLE
Win Svr 2022 exception System.Diagnostics.Eventing.Reader.EventLogRecord

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#62383]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Win-Svr-2022-exception-SystemDiagnostic/1600819)._

---
[severity:I'm unable to use this version]
We are seeing the following error (pasted below) when attempting to call this API to read the Windows Event Log.  I've searched and found the following link that explains the error, but the link refers to Windows 11, and we're seeing this on Windows Server 2022 (with all latest Windows Updates applied).

We have an app that reads details from the Event Log, and this error is going to make it such that we can't support Windows Server 2022.  We are hoping that the fix that was created for Windows 11 might also be applied to Windows Server 2022.  Thanks in advance for any details you can share.

Here's the link about the Windows 11 occurrence:
System.Diagnostics.Eventing.Reader.EventLogRecord throws an InvalidOperationException on Windows 11 ...

Here's the exception details when we try to call this API:
2021-11-29 15:55:28,614 [130] ERROR - Remote error thrown on Windows Event Watcher for: Domain Config: 4; Host: 10.225.64.65; Log: Application
System.InvalidOperationException: We do not have 18 variants given for the UnsafeNativeMethods.EvtRenderFlags.EvtRenderEventValues flag. (System Properties)
at System.Diagnostics.Eventing.Reader.NativeWrapper.EvtRenderBufferWithContextSystem(EventLogHandle contextHandle, EventLogHandle eventHandle, EvtRenderFlags flag, SystemProperties systemProperties, Int32 SYSTEM_PROPERTY_COUNT)
at System.Diagnostics.Eventing.Reader.EventLogRecord.PrepareSystemData()
at System.Diagnostics.Eventing.Reader.EventLogRecord.get_Level()

---
#### William Ryan on 12/1/2021, 08:39 AM: 

<p>correction - HERE is the link about this issue on Windows 11<br>
<a target='_blank' href="https://github.com/dotnet/runtime/issues/60740">https://github.com/dotnet/runtime/issues/60740</a></p>

#### Feedback Bot on 12/2/2021, 01:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by tommcdon** [comment]
dupe to 60740
