### ISSUE TITLE
[API Proposal]: DrawRectangle should accept RectangleF as one of the overloads

### ISSUE THREAD

**Issue by medo64** [dotnet/runtime#62401]
### Background and motivation

In Graphics class, FillRectangle contains the following 4 overloads:
* `public void FillRectangle(Brush brush, RectangleF rect)`
* `public void FillRectangle(Brush brush, float x, float y, float width, float height)`
* `public void FillRectangle(Brush brush, Rectangle rect)`
* `public void FillRectangle(Brush brush, int x, int y, int width, int height)`

However, DrawRectangle, contains only the following 3 overloads:
* `public void DrawRectangle(Pen pen, Rectangle rect)`
* `public void DrawRectangle(Pen pen, float x, float y, float width, float height)`
* `public void DrawRectangle(Pen pen, int x, int y, int width, int height)`

In the interest of symmetry, I propose adding the "missing" RectangleF overload:
* `public void DrawRectangle(Pen pen, RectangleF rect)`

During a development process one can quite often switch between DrawRectangle and FillRectangle API. This would allow to do so without changing the variables around, i.e. just by changing `Fill` into `Draw` and backward. Likewise, this would make drawing filled rectangles with outline in different color minutely easier.

### API Proposal

```C#
namespace System.Drawing.Common
{
    public class Graphics
    {
        public void DrawRectangle(Pen pen, RectangleF rect);
    }
}
```

### API Usage

API usage would be comparable to the existing API:
```C#
var rect = new RectangleF(...);
e.Graphics.FillRectangle(Brushes.Blue, rect);  // this works even now
e.Graphics.DrawRectangle(Pens.Red, rect);      // this would be a new overload
```

### Risks

Since method will just be a convenient way of calling already existing overload, risk is minimal if any.

**Comment by safern** [comment]
Makes sense to add this overload to be consistent with what we have on other APIs, i.e `Graphics.FillRectangle`. 

Marking it as api-ready-for-review to discuss it on the review meeting.

**Comment by terrajobst** [comment]
* Seems like a no-brainer
    - Are there any other? Seems like `FillPie` would be in the same category.

```C#
namespace System.Drawing.Common
{
    public class Graphics
    {
        public void DrawRectangle(Pen pen, RectangleF rect);
        public void FillPie(Brush brush, RectangleF rect, float startAngle, float sweepAngle);
    }
}
```

**Comment by medo64** [comment]
> * Seems like a no-brainer
>   * Are there any other? Seems like `FillPie` would be in the same category.

Agreed; missed that one. I believe `FillPie` is the only one missing `RectangleF` but having `Rectangle`. There is a `DrawIcon` but there I believe having just `Rectangle` is appropriate.

**Comment by medo64** [comment]
I did ask for [pull request](https://github.com/dotnet/runtime/pull/62385) to be reopened (yes, I did things slightly out of order). Once that happens I will push commit for `FillPie` in addition to `DrawRectangle` that was already part of original pull request.

**Comment by deeprobin** [comment]
Please tag this with "in pr" :smile: thank you

**Comment by jeffhandley** [comment]
This was completed in #62385
