### ISSUE TITLE
[API Proposal]: Implicitely convert IEnumerable to ImmutableArray (and friends)

### ISSUE THREAD

**Issue by tthiery** [dotnet/runtime#62409]
### Background and motivation

Immutable collections have a good usage with records. They preserve the immutability also for collections. However, the usage of the `System.Collections.Immutable` namespace deserves a bit love when it comes to the new fancy world of records. In this issue, I want to address the bleeding of the implementation detail of immutable collections into the user code.

````c#
public record A(string A, ImmutableArray<B> Childs);
public record B(string C, string D);

// ... as a consumer ...
var a1 = new A("a1", new B[] { new B("c1", "d1"), new B("c2", "d2").ToImmutableArray());
var a1 = new A("a1", xElement.Select(ParseB).ToImmutableArray());
````

Assuming the usage of collections on many layers of a complex model, the amount of converting explicit boilerplate becomes annoying (considering the usage from many different sources: array, LINQ, ....). Therefore, I propose to add implicit casts from IEnumerable to ImmutableArray.

### API Proposal

- Add implicit casts (basicall `ToImmutableArray`)

### API Usage

```C#
// ... as a consumer ...
var a1 = new A("a1", new B[] { new B("c1", "d1"), new B("c2", "d2"));
var a1 = new A("a1", xElement.Select(ParseB));
```

### Alternative Designs

- writing boilercode
- extensions methods everywhere. was not that once a topic?

### Risks

- More to maintain
- Performing a costly operation in a cast

**Comment by teo-tsirpanis** [comment]
Hello, this would not be a good idea. Implicit operators are typically very fast and rarely (if ever) allocate memory.

The `ToImmutableArray` extension method you mention allocates arrays of arbitrary size (and more than one arrays of the enumerable's size is not known), and copies data of arbitrary size. This is clearly a non-trivial cost as you recognized, which is the reason that the point where an `IEnumerable<T>` is converted to an `ImmutableArray<T>` is something user code has to explicitly decide based on requirements and expected performance. Adding an implicit operator runs counter to this principle.

**Comment by pinkfloydx33** [comment]
Neither type in a user-defined conversion operator is allowed to be an interface, so this wouldn't be possible anyways, right?

**Comment by tthiery** [comment]
I understand both of these technically. As an overall story for immutable programming with records the resulting experience regards collection is very poor.

**Comment by svick** [comment]
One thing that might make this easier is the proposed C# collection literals: https://github.com/dotnet/csharplang/issues/5354.

Using those, the array initializer line from your example would become:

```c#
var a1 = new A("a1", [ new B("c1", "d1"), new B("c2", "d2") ]);
```

**Comment by eiriktsarpalis** [comment]
Closing per feedback already expressed in this issue. Thank you for providing the suggestion.
