### ISSUE TITLE
[API Proposal]: Logging Source Generator - implicitly set LogLevel based on method name decorated by LoggerMessageAttribute

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#62412]
### Background and motivation

.Net 6 logging source generator is useful but is quite verbose
One way to improve it could be to infer the LogLevel from the name of the method decorated by LoggerMessageAttribute

The concept is like for the implicit ILogger implementation, the only difference is that the LogLevel, when not defined, is inferred from the method name prefix ( `Trace, Debug, Info, Warning, Error, Critical)

Of course if no LogLevel is specified and the method doesn't start with one of the expected prefix, the analyzer should produce an error

### API Proposal

Here I'm adding only the constructor to add
```C#
namespace Microsoft.Extensions.Logging
{
    public sealed class LoggerMessageAttribute : Attribute
    {
        public LoggerMessageAttribute(int eventId, string message)
    }
}
```

### API Usage

```C#
public partial class MyClass
{
   readonly ILogger _logger;

   [LoggerMessage(0, "I'm a Debug log message")]
   partial void DebugMethod();

   [LoggerMessage(0, "I'm a Trace log message")]
   partial void TraceMethod();

   ...
   
   [LoggerMessage(0, "I'm a Critical error!")]
   partial void CriticalMethod(Exception ex);
}
```

**Comment by MithrilMan** [comment]
Sorry I pressed ALT Enter while filling the form, I've edited the issue but I see that msfbot doesn't update the content, hope it's fine :)

**Comment by davidfowl** [comment]
This feels a little too magical.

**Comment by MithrilMan** [comment]
The "magical" part is about convention and there are scenarios where such magic is already in place.
I'm not 100% fan too but I see two aspect that may be an improvement
- less code to write (as stated)
- readability in code, where you can see just by the name if you are logging, tracing, rising warning, etc..

Actually to know the severity of a log entry you have to inspect the method definition and take a look at its attribute (when using SG logging) while with a convention you don't need that.

An alternative to improve readability (within visual studio) would be to show contextual information into intellisense.
I don't know if it's actually already possible, but would be nice to see, popping up intellisense definition of our logging method, programmatically injected context information (e.g. by attribute)

In this case, for instance, source generator could add attribute like an hypotetical IntellisenseContextAttribute that states the log severity level.

What I mean is that, having a log definition like

```
[LoggerMessage(0, LogLevel.Critical, "An unhandled exception has been raised in the {PeriodicWork} work.")]
partial void CriticalPeriodicWorkFailure(string periodicWork);
```

the loggin source generator could create this kind of code
```
[IntellisenseContext("Critical Level", Color.Red)]
 [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Extensions.Logging.Generators", "6.0.5.2210")]
partial void CriticalPeriodicWorkFailure(global::System.String periodicWork)
{
   if (_logger.IsEnabled(global::Microsoft.Extensions.Logging.LogLevel.Critical))
   {
      __CriticalPeriodicWorkFailureCallback(_logger, periodicWork, null);
   }
}
```
see `[IntellisenseContext("Critical Level", Color.Red)]` that's the addition I'd consider

this would translate into an intellisense popup like this (sorry for my mspaint skill!)
![image](https://user-images.githubusercontent.com/5107375/145230498-3cccc3ab-55f1-4336-a68b-7af0df4b5040.png)

**Comment by MithrilMan** [comment]
P.S.
in this scenario, read Intellisense = QuickInfo tooltip

**Comment by maryamariyan** [comment]
Thanks for your feedback. Closing as it doesn't seem like a feature we'd take on.
