### ISSUE TITLE
NetStandard 2.2 with ISpanFormattable

### ISSUE THREAD

**Issue by snakefoot** [dotnet/runtime#62414]
Enable library-authors to access stable API through NetStandard, instead of having to support Net5 + Net6 + Net7, etc.

There are probably other APIs that have grown mature in Net5 + Net6 , that would be nice to have in NetStandard 2.2. Ex. DateOnly + TimeOnly

**Comment by teo-tsirpanis** [comment]
Hello, as explained in https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/, there won't be another .NET Standard version.

Library authors that want to use newer framework features should just target .NET 5 or 6. With the (not yet complete though) unification of Xamarin into .NET 6, code that targets modern .NET should "work anywhere" just like .NET Standard.

**Comment by snakefoot** [comment]
Really like the idea of API-definitions that remains supported after 2 years. Unlike Net5 + Net6 platforms that becomes unsupported because no longer recieving security-updates.

**Comment by teo-tsirpanis** [comment]
Yeah, I understand that modern .NET's support lifecycle makes some people uncomfortable, but the situation with libraries is a bit different.

Let's say that you have an application that targets .NET 6, and you found a library on NuGet that only targets the now-unsupported .NET Core 2.1. You can still use it without fear, the library might _target_ an unsupported framework, but will _run_ under a suported one.

The API definitions of each framework are just an interface, a specification. They do not have an end of support. Running apps under this framework however does get eventually unsupported. As these frameworks get unsupported and lag behind in features, library authors remove support for them, but if a library continues to support older frameworks, it is still fine to use.

**Comment by teo-tsirpanis** [comment]
> having to support Net5 + Net6 + Net7

You don't have to support all these frameworks, if you use say trimmability annotations which were introduced in .NET 5, you don't have to support .NET 6, unless you want to use a feature exclusive to .NET 6, such as `DateOnly`, but by that point .NET 5 will be unsupported soon so you might want to stop targeting it to avoid many `#ifdef`s.

If you want some advice, in a project of mine I target .NET Standard 2.0, .NET Standard 2.1 and the latest modern .NET. The first is for maximum framework compatibility, the middle is for reduced dependencies and higher performance (the project heavily uses spans and on .NET Standard 2.0 it had to reference some more packages and use less optimized code), and the last is to take advantage of all newer framework features if needed.

**Comment by snakefoot** [comment]
Library authors cannot compile the library for NetCoreApp2.1 without getting security everywhere. Eventhough one might want to support all platforms.

**Comment by teo-tsirpanis** [comment]
If you are actively maintaining a library you have to change the framework you target at least every two years as you said, which is a small thing that involves changing just a couple of lines (you can use a `Directory.Build.props` if you have many projects). You can also suppress the security warnings which is something I would not recommend.

If you _were_ maintaining a library but now have stopped working on it and use its NuGet packages, you shouldn't feel obligated to release a new version every couple of years _just_ to bump the TFMs without changing anything else.

**Comment by snakefoot** [comment]
Guess I like both camps:
- Library that support all platforms (even old ones)
- Library that enables using new API-features (when available on the platforms).
Not suddenly removing platform, and suddenly have to disable the API-features for that platform.
