### ISSUE TITLE
WebDav directory enumeration via WebClient service returns spurious null characters

### ISSUE THREAD

**Issue by lscorcia** [dotnet/runtime#62429]
### Description

Calls to Directory.GetFiles on WebDav paths (i.e. Sharepoint folders) return additional `\0` characters at the end of the returned file paths. This breaks file access as the returned string is not a valid path, and also breaks the special detection of the "." and ".." content - they shouldn't be returned, but they are.

### Reproduction Steps

Just invoke `Directory.GetDirectories` on a WebDav path, like in this example (which reads a SharePoint folder):

![immagine](https://user-images.githubusercontent.com/16761934/144828237-c067acf6-d1fa-4200-a20d-c5aa09547d36.png)

Look at the returned array:

![immagine](https://user-images.githubusercontent.com/16761934/144828283-2117cd26-8ac5-4fa1-8cb7-acbd0c72d4e0.png)

### Expected behavior

The directory enumeration code should not return the extra `null` characters at the end of the paths, and also shouldn't return the `.` and `..` directories.

### Actual behavior

The directory enumeration code returns invalid paths.

### Regression?

The Directory.GetDirectories call worked fine in .net framework 4.5-4.8. Broken in .net core 5 and 6.
This is a huge hassle as we are migrating to .net core a lot of government code that uses WebDav to access and publish documents stored on SharePoint.

### Known Workarounds

As a workaround, we use the following extension method to manually fix the returned array after calls to `Directory.GetDirectory`. It's not pretty, it's not fast, but it works.

```
public static string[] FixupNet5Enumeration(string[] items)
{
    return items
        .Select(t => t.TrimEnd('\0'))
        .Where(t =>
            {
                var itemName = Path.GetFileName(t);
                return itemName != "." && itemName != "..";
            })
        .ToArray();
}
```

### Configuration

Regression tested on:

* Windows 10 x64 w/ .net core 5
* Windows 11 x64 w/ .net core 5
* Windows 11 x64 w/ .net core 6

### Other information

I tried source-stepping in the .net code and it seems like the error comes directly from the file system enumeration process:

![immagine](https://user-images.githubusercontent.com/16761934/144828816-6030dde9-edda-49e9-b5ee-051880c9e44c.png)

Even if the file name is exactly one character long, the `FileNameLength` property returns the value 4.
Looking at the `Interop.FILE_FULL_DIR_INFORMATION` class, the `FileName` is actually computed from "the initial byte returned by Win32 API + (the reported length of the string / sizeof(char))":

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Windows/NtDll/Interop.FILE_FULL_DIR_INFORMATION.cs#L56-L57 

MSDN for the `FILE_FULL_DIR_INFORMATION` struct (https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_full_dir_information ) does not specify whether the length is expressed in bytes or in characters. Unicode "." is 00 2E 00 00, so 4 bytes long. This seems to imply that `FileNameLength` is expressed in bytes and that it includes the trailing `\0` - this means that the `FileName` `ReadOnlySpan` is initialized with value (4 / sizeof(char)) = 2.

This inclusion of the null terminator seems weird to me. Win32 APIs that explicitly return a string length generally don't return additional null chars at the end of the buffer. Also, I verified that it's not coming from the XML WebDav response (actually the '.' and '..' folders do not show up in there at all).

But then, why is it working on framework 4.8? Surely the Win32 API is returning the same values even on full framework - IF it is even using the same API. Unfortunately, debugging the .net framework does not lead me anywhere - the code is optimized and I can't step into it.

Maybe the actual root issue could be a bug in the WebDav client stack (i.e. the extra null byte should not be returned)? This would explain why the issue does not show up when enumerating local folders, and maybe the consequences are not visibile in fw 4.8 because it unmarshals buffers to `strings` instead of `Span`s? Maybe unmarshalling to string adds some extra processing related to null terminators?

**Comment by adamsitnik** [comment]
Hi @lscorcia 

Big thanks for a very detailed bug report! I agree that it's a bug and we need to fix it. 

Since we already have a bug report for it (#49803) could you please close this issue and post your findings in #49803 ?

**Comment by lscorcia** [comment]
Closed as duplicate. Funny as I tried searching before posting but it did not show up. Thanks @adamsitnik .
