### ISSUE TITLE
Investigate how to improve libraries incremental build for faster innerloop  development

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#62444]
We should invest some time investigating where we can improve the libraries incremental build.

On my dev box running a clean build with `build.cmd libs -rc Release` takes:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:08:06.14
```

Incremental build without changing anything takes:

```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:00.49
```

2 minutes isn't as bad, but for doing "nothing" I think there might be places where we can improve and avoid writing files/etc.

cc: @ericstj @carlossanlop

**Comment by jkoritzinsky** [comment]
It would be interesting to investigate using MSBuild static graph with the libraries build to see what improvements that provides if any. I think Viktor did some investigation a while back but I never saw the numbers.

**Comment by ericstj** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/49800?

**Comment by safern** [comment]
Ah, I couldn't find that issue because the title was "incrementally" not "incremental". Thanks, @ericstj given that there is already discussions on that issue I'll close this one as a dupe of #49800
