### ISSUE TITLE
Interop on Mac causes process to exit with return code 0

### ISSUE THREAD

**Issue by biltongza** [dotnet/runtime#62454]
### Description

I am trying to use a library (https://github.com/migueldeicaza/Darwin.CopyFile) that does some interop to call the Mac native `copyfile` function. I want to do this because I want to get progress notifications while the copy is running.

The call to `copyfile` works as expected. However, setting up the progress notifications does not.

To get notifications, you need to pass a state parameter with a callback function to receive notifications. This is the part that causes the exit. Creating the state object works fine, but setting the callback function immediately terminates the process.

### Reproduction Steps

I've made a repo with a minimal case here: https://github.com/biltongza/dotnet-mac-crash-repro
Simply run `dotnet run` to see the issue.

### Expected behavior

The program should run to completion.

### Actual behavior

The program terminates unexpectedly with return code 0. No error messages or warnings.

### Configuration

```
dotnet --list-sdks
6.0.100 [/usr/local/share/dotnet/sdk]
```
MacOS 12.0.1 running on a 2021 Macbook Pro with an M1 Pro chip.

**Comment by AaronRobinsonMSFT** [comment]
@biltongza Can you please confirm which architecture is being used? Is this the x64 or ARM64 runtime? It would also be helpful to know if this is a new regression from a previous version of the runtime.

**Comment by biltongza** [comment]
It is on ARM64. I'm not sure if it is a regression, would testing .NET 5 via x64 be sufficient to check?

**Comment by biltongza** [comment]
Confirmed it is still an issue in .NET 5.0.404.

**Comment by am11** [comment]
This is not an issue with coreclr interop, but rather a bug in `Darwin.CopyFile` library.

In the header (path depends on your macOS SDK version): `/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/copyfile.h`, the flags are defined as:

```h
#define COPYFILE_STATE_SRC_FD           1
#define COPYFILE_STATE_SRC_FILENAME     2
#define COPYFILE_STATE_DST_FD           3
#define COPYFILE_STATE_DST_FILENAME     4
#define COPYFILE_STATE_QUARANTINE       5
#define COPYFILE_STATE_STATUS_CB        6
#define COPYFILE_STATE_STATUS_CTX       7
#define COPYFILE_STATE_COPIED           8
#define COPYFILE_STATE_XATTRNAME        9
#define COPYFILE_STATE_WAS_CLONED       10
```
but in https://github.com/migueldeicaza/Darwin.CopyFile/blob/7d4e9b96585ff73708f7b036bddbd4556ad89691/CopyFile.cs#L303, `StatusCB` is at position 5 (C# unnumbered enums start from 0). The minimal fix is:

```diff
			enum Option {
-				SrcFD, // surfaced
+				SrcFD = 1, // surfaced
				SrcFileName, // surfaced
				DstFD, // surfaced
				DstFileName, // surfaced
				Quarantine,
				StatusCB, // surfaced
				StatusCtx, // surfaced
				Copied, //surfaced
				XAttrName, // surfaced
				WasCloned
			}
```
(incremental numbers are assigned for the remaining unnumbered enum members)

I copied over CopyFile.cs and applied that patch for testing. After that, I see:

```zsh
% bin/Debug/net6.0/dotnet-mac-crash-repro 
created state
set status callback
Copied!
EEXISTS

% git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   dotnet-mac-crash-repro.csproj

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	CopyFile.cs
	test2.txt

no changes added to commit (use "git add" and/or "git commit -a")

% git diff
diff --git a/dotnet-mac-crash-repro.csproj b/dotnet-mac-crash-repro.csproj
index cd118eb..8c665d6 100644
--- a/dotnet-mac-crash-repro.csproj
+++ b/dotnet-mac-crash-repro.csproj
@@ -8,8 +8,4 @@
     <Nullable>enable</Nullable>
   </PropertyGroup>
 
-  <ItemGroup>
-    <PackageReference Include="Darwin.CopyFile" Version="1.0.0" />
-  </ItemGroup>
-
 </Project>
```

**Comment by danmoseley** [comment]
@biltongza  I'm closing this per the info above. Would you consider offering a PR to that library to fix it?

**Comment by danmoseley** [comment]
Thanks for the investigation @am11 !

**Comment by biltongza** [comment]
I would certainly be happy to PR this in the library.

If I may ask, how does this wind up terminating the process so abruptly?
