### ISSUE TITLE
CA1416 incorrectly warning on LdapSessionOptions.SecureSocketLayer on Linux

### ISSUE THREAD

**Issue by iinuwa** [dotnet/runtime#62462]
### Description

CA1416 is being raised by the analyzer when accessing the `LdapSessionOptions.SecureSocketLayer` property on Linux, with a message saying that it is only supported on Windows. The code is supported, however, and it executes just fine.

There are no attributes on the `SecureSocketLayer` property in the .NET 6.0 source code that I can see that would be causing this warning to be raised.

### Reproduction Steps

```shell
dotnet new console
dotnet package add System.DirectoryServices.Protocols
```

```csharp
// Program.cs
using System.DirectoryServices.Protocols;
using System.Net;

var ldapIdentifier = new LdapDirectoryIdentifier("localhost", 636);
var ldapConnection = new LdapConnection(ldapIdentifier, new NetworkCredential("CN=admin,DC=example,DC=com", "password"))
{
    AuthType = AuthType.Basic
};
ldapConnection.SessionOptions.SecureSocketLayer = true;
```

### Expected behavior

Warning should not show because setting `LdapSessionOptions.SecureSocketLayer` _is_ supported on Linux.

### Actual behavior

CA1416 is thrown:
```
[{
	"resource": "/src/project/Program.cs",
	"owner": "csharp",
	"code": "CA1416",
	"severity": 4,
	"message": "This call site is reachable on all platforms. 'LdapSessionOptions.SecureSocketLayer' is supported on: 'windows'. [Project]",
	"source": "csharp",
	"startLineNumber": ...,
	"startColumn": ...,
	"endLineNumber": ...,
	"endColumn": ...
}]
```

### Known Workarounds

```csharp
#pragma warning disable CA1416
ldapConnection.SessionOptions.SecureSocketLayer = true;
#pragma warning restore CA1416
```

### Configuration

.NET Version: 6.0
OS: Ubuntu Linux 20.04
Architecture: x64
IDE: VS Code, C# Extension version 1.23.17

**Comment by joperezr** [comment]
Thanks for logging the issue @iinuwa, this has actually already been fixed in main via https://github.com/dotnet/runtime/pull/61388. We basically missed to remove this attribute after adding the original implementation. Can you try latest package out of main to see if that fixes your issue?
