### ISSUE TITLE
[API Proposal]: WebSocketException to expose the underlying HTTPResponse or the response status

### ISSUE THREAD

**Issue by vicancy** [dotnet/runtime#62474]
### Background and motivation

When customers connect to the [Azure Web PubSub service](https://docs.microsoft.com/azure/azure-web-pubsub/) using `ClientWebSocket`, there is a need to check if the connection failure is reconnectable or not. For example, if the HTTP upgrade request returns 400, this WebSocket connection is not reconnectable, while when the HTTP upgrade request returns 5xx, this might be caused by intermittent network issues and it is reconnectable. However, in the current design https://github.com/dotnet/runtime/blob/2cbc0713d183cae317797f39241d800fdfa01aa6/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs#L149, the WebSocketException simply throws `WebSocketError.NotAWebSocket` which makes it hard for customers to differentiate from different scenarios. Customers have to parse the `net_WebSockets_Connect101Expected` string to get out the status code...

### API Proposal

```C#
namespace System.Net.WebSockets
{
    public sealed class WebSocketException : Win32Exception
    {
        public HttpResponseMessage UpgradeResponse { get; }
    }
}
```

### API Usage

```C#
try {
    // Start the WebSocket connection
} catch (WebSocketException e) {
   if (e.UpgradeResponse.StatusCode >= 500) {
      // Try reconnecting...
   }
}
```

**Comment by svick** [comment]
I think the discussion about adding `StatusCode` to `HttpRequestException` (which was done in .Net 5) is relevant here: https://github.com/dotnet/runtime/issues/911.

In particular, one comment (https://github.com/dotnet/runtime/issues/911#issuecomment-558687189), which explains why it should be just the `HttpStatusCode`, and not the whole `HttpResponseMessage`:

> Having an HttpResponseMessage in an exception means that it will keep connections open etc. So, then, do we add an Dispose() method to the HttpRequestException? It isn't IDisposable at all. And having a pattern where complex types are inside exceptions is very confusing.
>
> So, I would suggest just adding the 'StatusCode'.

**Comment by karelz** [comment]
Triage: This will help make WebSockets apps better. Should be simple. We need to first finalize the API.
