### ISSUE TITLE
[API Proposal]: Platform-aware Marshal.StringToHGlobalUni equivalent

### ISSUE THREAD

**Issue by Dennis-Petrov** [dotnet/runtime#62475]
### Background and motivation

As for now, `Marshal.StringToHGlobalUni` internally calls [this](https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/string.cs#L1571):
```
[System.Security.SecurityCritical]  // auto-generated
internal static unsafe void wstrcpy(char *dmem, char *smem, int charCount)
{
    Buffer.Memcpy((byte*)dmem, (byte*)smem, charCount * 2); // 2 used everywhere instead of sizeof(char)
}
```
Thus, we have hardcoded UTF-16 here, which works as expected on Windows, but fails on Linux.  
In cases of P/Invoke with `LPCWSTR`s inside structures like this, native code expects UTF-32:
```C
typedef struct _SOME_PARA {
   DWORD dwSize;
   LPCWSTR wszSomeStr;
 } SOME_PARA,
   *PSOME_PARA;
```

This is unobvious. Also, there are no such details in [docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.stringtohglobaluni?view=net-6.0) too. One converts string to Unicode, but **what** Unicode exactly?

### API Proposal

```C#
public static IntPtr StringToHGlobalPUni(string source)
{
    // use PAL to obtain proper Unicode encoding
}
```

### API Usage

```C#
var s = "String to p/invoke";
var sPtr = Marshal.StringToHGlobalPUni(s);
try
{
    var somePara = new SOME_PARA
    {
        dwSize = Marshal.SizeOf<SOME_PARA>(),
        wszSomeStr = sPtr 
    };
    
    // pass somePara to native code    
}
finally
{
    Marshal.FreeHGlobal(sPtr);
}
```

### Alternative Designs

Probably, this will require some changes inside default string marshalling.
I mean, one can use proposed API with this struct:
```C#
    [StructLayout(LayoutKind.Sequential)]
    internal struct SOME_PARA
    {
        public uint dwSize;

        public IntPtr wszSomeStr;
    }
```
but in case of this declaration:
```C#
    [StructLayout(LayoutKind.Sequential)]
    internal struct SOME_PARA
    {
        public uint dwSize;

        public string wszSomeStr;
    }
```
we'll still get UTF-16 because of default marshalling settings.

**Comment by AaronRobinsonMSFT** [comment]
@Dennis-Petrov Thanks for filing this issue. .NET uses the term "Unicode" in ambiguous ways, especially in interop scenarios. There are two examples that illustrate this, [`UnicodeEncoding`](https://docs.microsoft.com/dotnet/api/system.text.unicodeencoding) and [`CharSet`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.charset). Both document "Unicode" as two-bytes in size. The documentation for the APIs in question should likely be updated to indicate two-bytes as well. I'm not convinced we should be spending the effort to update them to be honest.

For the case above, the .NET team has been working on source generation for struct marshalling &ndash; see [StructMarshalling.md](https://github.com/dotnet/runtime/blob/main/docs/design/libraries/DllImportGenerator/StructMarshalling.md). We have an issue that is tracking some encoding concerns too &ndash; https://github.com/dotnet/runtime/issues/61326.
