### ISSUE TITLE
Add libclang to Microsoft.NETCore.Runtime.Mono.LLVM.Sdk package

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#62485]
We have been using libclang from emscripten's `emsdk/upstream/bin`. It is not part of emscripten packs anymore, starting with emscripten version 3.0.0.

We use libclang for mono's offsets-tool, which also contains python bindings for libclang.

It would be great to have libclang shared library and `https://github.com/dotnet/llvm-project/tree/release/11.x/clang/bindings/python/clang` added to Microsoft.NETCore.Runtime.Mono.LLVM.Sdk nuget package.

**Comment by SamMonoRT** [comment]
@radekdoulik - please follow up here if this will be ready before RC1 snap.

**Comment by SamMonoRT** [comment]
@akoeplinger @radekdoulik -- any more work remaining here ?

**Comment by akoeplinger** [comment]
libclang was added to the llvm package for non-ARM architectures with https://github.com/dotnet/llvm-project/pull/149 and for osx-arm64 with https://github.com/dotnet/llvm-project/pull/190.

In theory we could add it for every arch but so far we've not needed it. I think we can close this for now.
