### ISSUE TITLE
CultureInfo enum

### ISSUE THREAD

**Issue by kelicto** [dotnet/runtime#62511]
## Background and Motivation

Using enumerations can be done better and more convenient.

`Thread.CurrentThread.CurrentUICultureLanguage = Culture.ZH_CN;`

**Comment by CyrusNajmabadi** [comment]
Here you go @kelicto  :)

**Comment by tarekgh** [comment]
@kelicto thanks for your report. I don't think this is a good idea. Cultures are dynamic list and cannot have enum type that include the cultures list. The list can change between platforms and OS's versions. What is the deal of using `CultureInfo.GetCultureInfo("zh-CN")` ? Why can't you define whatever convenient enum in your library/app?

**Comment by kelicto** [comment]
> 此问题已被标记，`needs more info`因为它可能缺少重要信息。有关如何有效报告问题的提示，请参阅我们的[贡献指南](https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-bug-report)。
> 
> 边注。请尽量不要使用`Thread.CurrentThread.CurrentUICulture`，而是始终使用`CultureInfo.CurrentUICulture`

**Comment by kelicto** [comment]
Yes, but it is possible to implement an overload to support most stable country regions, called 'special countries'.
