### ISSUE TITLE
[Linux] procfs file reads and UnauthorizedAccessException handling

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#62513]
In restricted environments such as a container with limited access, shared hosting, chroot and other forms of sandbox, .NET process may not have read permissions on procfs files, while the file may exist. This can lead to `UnauthorizedAccessException`.

While most of the managed code reading procfs files in the runtime repo found by `git grep /proc ':/*.cs' ':/!*[tT]est*'` seem to handle unauhorized access case, we should try to make the user-experience consistent and align varied styles where possible. A few examples:

https://github.com/dotnet/runtime/blob/c8ede5c4b1aba85fc894d5faed42d6d5186eabe1/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L38

https://github.com/dotnet/runtime/blob/c8ede5c4b1aba85fc894d5faed42d6d5186eabe1/src/libraries/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.TryReadStatusFile.cs#L149

https://github.com/dotnet/runtime/blob/c8ede5c4b1aba85fc894d5faed42d6d5186eabe1/src/libraries/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.ParseMapModules.cs#L26-L27

https://github.com/dotnet/runtime/blob/c8ede5c4b1aba85fc894d5faed42d6d5186eabe1/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L36

and then there are cases in `NetworkInformation`, which do not handle the exception at all. Majority of procfs files listed in `NetworkInformation/NetworkFiles.cs` are read via `StringParsingHelpers`. Some call sites catch `IOException` and `UnauthorizedAccessException`, others don't and it seems unintentional. For instance, [`GetIcmpV4Statistics`](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipglobalproperties.geticmpv4statistics?view=net-6.0) and [`GetTcpIPv4Statistics`](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipglobalproperties.gettcpipv4statistics?view=net-6.0) docs do not mention `PlatformNotSupportedException`, `IOException` or `UnauthorizedAccessException` are the possible exceptions which these APIs can throw, only `NetworkInformationException` is noted.

**Comment by wfurt** [comment]
this would be nice to fix for consistency.

**Comment by karelz** [comment]
Triage: It would be nice clean up. Should not be that difficult to do.
