### ISSUE TITLE
How to change the ComHost Server registry name?

### ISSUE THREAD

**Issue by forderud** [dotnet/runtime#62529]
I'm working on a plugin-based application architecture that relies on custom naming of the COM server classes in the registry. The `<project>.comhost.dll` COM server generated for projects relying on `<EnableComHosting>` today always seem to be named `CoreCLR COMHost Server` which says _nothing_ about the COM server. I am therefore seeking a mechanism for either more informative default naming or an ability to override the name.

Is there a mechanism for customizing the COMHost server name to something else than "CoreCLR COMHost Server"?

### Steps to reproduce
1. Build the https://github.com/dotnet/samples/tree/main/core/extensions/COMServerDemo/COMServer
2. Register `COMServer.comhost.dll` with regsvr32.exe
3. Open RegEdit.exe and observe that the server name is "CoreCLR COMHost Server" in the Computer\HKEY_CLASSES_ROOT\CLSID\{DB1797F5-7198-4411-8563-D05F4E904956} registry folder:
![image](https://user-images.githubusercontent.com/2671400/145204008-a05c1b9f-9554-482a-b243-c5b793e581aa.png)

### .Net framework behavior
The .Net framework 4.x solved this problem for projects enabling "Register for COM interop" by **using the same ProgId string also for the COM server name**. Using the same naming scheme also in .Net core would be an acceptable outcome for me.

**Comment by jkoritzinsky** [comment]
We currently don't support customizing this name, but this is something that we can consider for the future.

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT @elinor-fung

**Comment by AaronRobinsonMSFT** [comment]
Hi @forderud. This is a reasonable request. When the feature was first ported, we didn't support ProgIDs so missed that compat point. Something to consider here though, which ProgID? Server assemblies can contain multiple servers which can make this hard. I suppose we could just select the first one we find. Perhaps we could also put in the assembly name? For example, `Foo.dll` could become `Foo`.

We are also open to other suggestions.

**Comment by AaronRobinsonMSFT** [comment]
Instead of using the constant, use something from the supplied `const comhost::clsid_map_entry`.

https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/native/corehost/comhost/comhost.cpp#L342-L352

**Comment by AaronRobinsonMSFT** [comment]
@forderud I did a quick check with the following and I think it is correct. I can submit a PR for this work in the new year or if you or anyone wants it earlier, feel free to submit a PR. I am technically on vacation right now so am trying to avoid too much work 😄 

**Note** If the below works, I wouldn't be against considering this for .NET 6.

```diff
diff --git a/src/native/corehost/comhost/comhost.cpp b/src/native/corehost/comhost/comhost.cpp
index 23c673c8973..b9aa96fe763 100644
--- a/src/native/corehost/comhost/comhost.cpp
+++ b/src/native/corehost/comhost/comhost.cpp
@@ -339,15 +339,18 @@ namespace

         RegKey regKey{ regKeyRaw };

-        // Set the default value for all COM host servers
-        const WCHAR defServerName[] = _X("CoreCLR COMHost Server");
+        // Set the default value - class name or ProgID.
+        const pal::string_t& defNameStr = entry.progid.empty() ? entry.type : entry.progid;
+
+        const WCHAR* defName = defNameStr.c_str();
+        DWORD defNameLength = static_cast<DWORD>(defNameStr.size());
         res = ::RegSetValueExW(
             regKey.get(),
             nullptr,
             0,
             REG_SZ,
-            reinterpret_cast<const BYTE*>(defServerName),
-            static_cast<DWORD>(sizeof(defServerName)));
+            reinterpret_cast<const BYTE*>(defName),
+            defNameLength + 1); // +1 for null.
         if (res != ERROR_SUCCESS)
             return __HRESULT_FROM_WIN32(res);
```

**Comment by forderud** [comment]
> @forderud I did a quick check with the following and I think it is correct. I can submit a PR for this work in the new year or if you or anyone wants it earlier, feel free to submit a PR. I am technically on vacation right now so am trying to avoid too much work 😄

That would be perfect @AaronRobinsonMSFT 👍  I'm not familiar with the .Net sources myself, so it would probably be safest if you could submit the PR instead of me.

> **Note** If the below works, I wouldn't be against considering this for .NET 6.

Perfect! Thanks a lot for being so service minded :-)
