### ISSUE TITLE
Can .NET 5 run exe targeting .Net Framework?

### ISSUE THREAD

**Issue by AlexByte** [dotnet/runtime#62521]
Can .NET 5 run exe targeting .Net Framework 3.5?

**Comment by huoyaoyuan** [comment]
No. Applications targeting .NET Framework 4 can't run on 3.5 too. It's out of date and lacks a lot of required feature.

**Comment by AlexByte** [comment]
@huoyaoyuan  I'm asking about the opposite. .Net Framework 4 can run exe targeting 3.5.

**Comment by huoyaoyuan** [comment]
@AlexByte sorry I misunderstood it.

For exe, things are somehow different. Exe is the entry point, and for .NET Framework exe, Windows can only call clr.dll, not coreclr.dll.

I believe you may reference the exe as a dll, and write a .NET 5 exe to simply forward the main.

**Comment by vitek-karas** [comment]
@huoyaoyuan is correct - the only way is to treat the `.exe` as an assembly (just like `.dll`) and create a new app which is .NET 5 which can then load that assembly.
Note that I would still recommend against doing this. We try to maintain some compatibility even with .NET Framework assemblies, but in general there's no guarantee that they will work.

**Comment by teo-tsirpanis** [comment]
I have actually tried running a .NET Framework 3.5 Windows Forms app on .NET 5 and it worked.

I added a `runtimeconfig.json` file next to the executable and ran `dotnet MyApp.exe`. I had to patch the assembly to fix a bug it had related to the RichEdit control but overall it worked without issue.

Of course if your .NET Framework assembly does something that is unavailable on modern .NET (such as Remoting) it won't work, and I wouldn't expect this scenario to be supported in any way.

If you have to directly launch an executable, Vitek's solution would be fine, but if you can get away with running it from the command line or double-clicking a shortcut, my solution would require the least effort.

**Comment by vitek-karas** [comment]
Thanks @teo-tsirpanis - that is actually a simpler solution!

**Comment by ericstj** [comment]
To add to this, `dotnet exec` has some handy options for experimentation.

As others have said
> there's no guarantee that they will work.

.NET 5 doesn't have all the types that were present in .NET 3.5.  For the types it does have, we have forwarders to new locations.  Some types (EG: WPF and WinForms) require you to target the "WindowsDesktop" shared framework (in your runtimeconfig.json) some might require additional references (`Microsoft.Windows.Compatibility` has the full set of types which we support that were present in .NETFramework).   The biggest drawback is you get no design-time checking for types, so you'll hit a runtime exception when something is missing. 

We recommend that folks retarget their projects for a better experience.
