### ISSUE TITLE
Change the `cpu-usage` EventCounter from int to double

### ISSUE THREAD

**Issue by Tomius** [dotnet/runtime#62525]
In the following line:
https://github.com/dotnet/runtime/blob/235915ea5e15604c80889c2ad7da9e999bc36e57/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/RuntimeEventSource.cs#L78

The `RuntimeEventSourceHelper.GetCpuUsage()` returns an _integer_ percent of all system resources used.

This means that on a machine with 128 cores, the smallest detectable change in CPU usage will be 128% of a single core, so a single threaded busy-loop application will report to be using 0% CPU according to this counter, when it's actually burning an entire core. This is very misleading.

**Comment by safern** [comment]
I think this makes sense to me.

**Comment by josalem** [comment]
@mikelle-rogers, this is a good issue for you to pick up. Let me know if you've got time for this.

As for the change itself, I agree that this makes sense. While not a public API, this is a documented value, so the docs will need to be updated to reflect the change and when it happened.

One other thing that should be decided is whether this value should be out of `N * 100` or just `100`, e.g., `1200%` vs `100%` for a 12-core machine using every core. Currently, Linus/Unix code gets the former, but scales it to the latter to match the Windows variant.

**Comment by mikelle-rogers** [comment]
> @mikelle-rogers, this is a good issue for you to pick up. Let me know if you've got time for this.
> 
@josalem I am currently working on it. Who would you suggest I include in the discussion to decide what the value should be?
