### ISSUE TITLE
[API Proposal]: `DateOnly` and `TimeOnly` `MinValue` and `MaxValue` should be fields like in `DateTime` and similar

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#62533]
### Background and motivation

Like in `DateTime` or `DateTimeOffset`, allowing us to use it as default value in arguments;
Right now
```C#
    public readonly struct TimeOnly : IComparable, IComparable<TimeOnly>, IEquatable<TimeOnly>, ISpanFormattable, IFormattable
    {
        public static TimeOnly MinValue { get; }
        public static TimeOnly MaxValue { get; }
   }
```
I think this is a hard inconsistency in BCL.

### API Proposal

```C#
    public readonly struct TimeOnly : IComparable, IComparable<TimeOnly>, IEquatable<TimeOnly>, ISpanFormattable, IFormattable
    {
        public static readonly TimeOnly MinValue;
        public static readonly TimeOnly MaxValue;
   }
```

### API Usage

```C#
public void MyCustomMethod(TimeOnly value = TimeOnly.MinValue) //this is not possible right now { }
public void MyCustomMethod(DateTime value = DateTime.MinValue) //this is
```

### Risks

If the name isn't changed, I think the change is invisible to API users. Isn't it?

**Comment by teo-tsirpanis** [comment]
> If the name isn't changed, I think the change is invisible to API users. Isn't it?

Unfortunately it is still a binary breaking change. When you access a property from code, in the underlying IL you _call_ the function's getter. Converting a field to a property will break already compiled assemblies.

**Comment by SingleAccretion** [comment]
I am not sure why is below though to be possible (in C#, it is definitely possible in VB, but VB treats `DateTime` specially).
```cs
public void MyCustomMethod(DateTime value = DateTime.MinValue) // This errors on my compiler.
```

Static struct fields are somewhat of a performance trap. On CoreCLR at least, they're boxed, so accessing them requires an additional indirection, and the Jit currently cannot reason about them.

**Comment by EgorBo** [comment]
https://github.com/dotnet/runtime/issues/49036#issuecomment-790086369

**Comment by EgorBo** [comment]
Also, you can use `default` for MinValue - it's the same value.
```csharp
public void MyCustomMethod(TimeOnly value = default)
public void MyCustomMethod(DateTime value = default)
```
