### ISSUE TITLE
WASM - Little/No Documentation for Using Low-Level Javascript Interop APIs

### ISSUE THREAD

**Issue by legistek** [dotnet/runtime#62530]
### Discussed in https://github.com/dotnet/runtime/discussions/59769

<div type='discussions-op-text'>

<sup>Originally posted by **legistek** September 29, 2021</sup>
First off, I've not been able to find any real documentation on the low-level Javascript APIs (such as these https://github.com/dotnet/runtime/blob/360df71eadde0d1394ee7b89693f83913f75575d/src/mono/wasm/runtime/binding_support.js) so apologies if I missed something. If there is documentation somewhere I'd hugely appreciate pointing me in the right direction.

Barring that, I have a few questions about low-level interop and specifically the idea of passing Mono object references to and from JS.

Suppose I do something like this:

C#:

```
MyObject _myObject = new MyObject();

void SendToJS()
{
     InternalCalls.InvokeJSUnmarshalled<MyObject, object, object, object>(
          "window.myJavascriptFunction", 
          _myObject, null, null);
}
```

TS:

```
_myCSObject: System_Object|null = null;
window.myJavascriptFunction = function(obj: System_Object) => 
{
   // obj is actually just a number (address?)
   _myCSObject = obj;
};
```

Later (TS):

```
var myMethod = (window as any).Module.bind_static_method('[MyAssembly] MyNamespace.MyStaticClass:MyMethod', 'm');  // signature 'm' for raw mono object (which I'm supposed to only use if I "know what [I'm] doing" - which is exactly the state of mind I'm trying to achieve :)
myMethod(_myCSObject);
```

Finally (C#):

```
public static class MyStaticClass 
{
    public static MyMethod(MyObject obj) 
    {
        // obj is populated with the original myObject
    }
}
```

So - the above all works - impressively! But I'm nervous it's too good to be true and will come back to bite me. Thus, my questions:

- What exactly is being passed into `myJavascriptFunction`? I know it's a number, but what does it represent? A memory address? Some kind of internal object handle? 
- How long is it safe to use this value with future calls into C#? I thought one of the main issues with using pointers in .NET is that addresses can change after a GC and thus you need to use them inside a `fixed` block. But this feels like I'm getting around that and so I'm not confident a GC or something else won't cause that number to be invalid at some future point.
- Assuming it is safe to hold onto that pointer and use it later, should I basically treat it as a weak reference to _myObject? Or am I actually preventing GC of the original object by giving it to Javascript? 
- Assuming it is a weak reference, what would happen if `MyMethod` were called after `_myObject` is garbage collected? Would `obj` just be `null` or would everything blow up?
- Slightly different but related topic - when functions like `mono_obj_array_new` and `js_string_to_mono_string` are used, which create managed objects, at what point do they become eligible for garbage collection? If I call them and never actually pass the objects back to C# do they just get collected on the next GC?

Many thanks for any assistance!</div>

**Comment by radical** [comment]
cc @kg @pavelsavara

**Comment by legistek** [comment]
FYI, based on experiments I believe I have a couple answers but really would love confirmation from people who know:

(1) It appears that sending JS an unmanaged / unmarshalled reference to a POCO does NOT create a hard reference in C# or prevent GC
(2) It appears that if I try to send a previously GC'd POCO back to C# using `mono_bind_static_method` with the `m` signature, the resulting reference is not safe to use. It seems sometimes I can still access its properties, which I clearly shouldn't, but other times I get a memory violation. Similar to accessing a C++ class instance after a `delete` methinks.

Is this correct?

If so then this raises a couple new questions -
- Using the numeric "handle" (or whatever it is) passed to JS through `InvokeUnmarshalled`, is there any way on the JS end to tell if the referenced POCO has been GC'd to avoid using it?
- **Leaving aside the possibility of GC**, is it safe to exchange POCO references between CS and JS using a combination of `InvokeUnmarshalled` and `mono_bind_static_method` with the `m` signature?

Thanks!

**Comment by kg** [comment]
You should assume it is not safe to ever handle raw managed pointers from JS. ```MONO.mono_wasm_new_root``` should be used to create GC root(s) and your pointers should live in those at all times. i.e.
```javascript
let myRoot = MONO.mono_wasm_new_root(pointer);
myRoot.value = some_c_or_csharp_func(myRoot.value); // not great but at present we don't officially support passing a root as an argument
some_js_func(myRoot); // pass the root instead like a 'ref object'/'out object' in C#
```
When using the 'm' signature you need to do this and it will be generally* safe, because internally the interop layer uses roots when working with pointers.

If possible you should try to design your C#<->JS interop around using ```GCHandle```s (passed via ```'i'```) instead of bare pointers - those don't change even if the GC moves the object. The performance will be a bit worse, of course. For performance-critical scenarios we have some stuff in the works for .NET 7 which should help here.

**Comment by legistek** [comment]
Hi @kg thank you SO MUCH that is very helpful. I wasn't sure what all these functions, such as `mono_wasm_new_root`, actually did.

I'm really curious about what you have in store here for NET7. I do have a performance critical situation. The short version is, I'm trying to drive a Javascript (react, specifically) UI with a C# model layer using data binding, conceptually similar to XAML.  (This would be an alternative to, e.g., Blazor or Uno, so I'm very interested in the low level APIs in general).

In my code, when JS wants to bind a UI element to a C# object property, it calls a C# method with a reference to the object (which it obtained from an earlier binding, or ultimately from a registered root object). So I need to exchange C# POCO references between Javascript and C# extremely efficiently, ideally as integers. I've been using both GCHandle's and also just internally maintained Dictionary's with similar results; but releasing the references correctly is extremely difficult.  

The best case scenario here is if I could somehow get a numeric weak reference to a POCO, give it to Javascript, and be able to give it back to C# whenever needed and instantaneously get an hard reference from that number (if it hasn't been GCd). Basically a GCHandle without having to worry about releasing them. 

Happy to discuss more offline if my scenario is of any interest. Either way you've given me some good info to proceed with.

Thanks again!
