### ISSUE TITLE
Odd behavior difference between Windows 10 (Desktop) and Windows Server (tried up to 2019)

### ISSUE THREAD

**Issue by bertrandpsi** [dotnet/runtime#62565]
### Description

String comparison for special characters do not react the same on the development machine as it runs on the server where the software shall be deployed.

To make sure this was the case, we made a self-contained single file publishing and moved around the exe on different machine. On a desktop it works, on a server it fails.

Used .NET 6.0

With .NET 4.x it anyhow fails

### Reproduction Steps

```cs
    static class MyStringCompare
    {
        static List<(string, string)> toReplace = new List<(string, string)>
        {
            new ("²","2"),
            new ("³","3")
        };

        public static bool AreEqual(string a, string b)
        {
            var va = a;
            var vb = b;
            foreach (var c in toReplace)
            {
                va = va.Replace(c.Item1, c.Item2);
                vb = vb.Replace(c.Item1, c.Item2);
            }
            return string.Compare(va, vb, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CompareOptions.IgnoreNonSpace | System.Globalization.CompareOptions.IgnoreCase) == 0;
        }
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            var a = "test²";
            var b = "test2";
            // Should return 0
            Console.WriteLine(string.Compare(a, b, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CompareOptions.IgnoreNonSpace | System.Globalization.CompareOptions.IgnoreCase));

            // Sould return 0
            var ci = System.Globalization.CultureInfo.InvariantCulture;
            Console.WriteLine(ci.CompareInfo.IndexOf(a, b,System.Globalization.CompareOptions.IgnoreCase | System.Globalization.CompareOptions.IgnoreSymbols));

            // Should return true
            Console.WriteLine(MyStringCompare.AreEqual(a,b));
        }
    }
   ```

### Expected behavior

Should be able to compare "test2" and "test²" and find them equals.

### Actual behavior

On desktop they are equals with the right comparer, on windows server not.

### Known Workarounds

The code provided in the reproduction steps do offer a nasty workaround.

### Configuration

.NET 6
Windows 10 Enterprise
Windows 2016 / Windows 2019
x64

**Comment by tarekgh** [comment]
Thanks for your report. In .NET 6.0, we depend on ICU library for globalization when running on Windows 10/11. But on Windows Server 2019, we don't depend on ICU as it is not compatible and instead, we depend on NLS Windows APIs. So, it is expected to see some differences. You may try to use the [ICU app-local ](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu) feature which allow you to deploy the ICU package with your app. That should address your scenario. You can do that by including the following to your app csproj.

```Xml
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.6" />
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  </ItemGroup>
```

I am closing this issue, but feel free to ask any questions and we'll be happy to help you with. Also, we have some other issues tracking if we can make the experience better on Server 2019.

**Comment by bertrandpsi** [comment]
This fixes indeed the issue. Thanks a lot!
