### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe not suppot .NET Core 2.x apps

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#62561]
### Description

When I try to upgrade `System.Runtime.CompilerServices.Unsafe` package from `5.0.0` to `6.0.0`, it seemed the package does not support for .NET Core 2.x apps. Maybe this is by design?

> System.Runtime.CompilerServices.Unsafe doesn't support netcoreapp2.1

![image](https://user-images.githubusercontent.com/7604648/145321571-02178cee-d8b2-4bb9-8f73-fffd0160bcd1.png)

### Reproduction Steps

Create a empty .NET Core 2.x app and add package reference for `System.Runtime.CompilerServices.Unsafe` with `6.0.0` version

### Expected behavior

As a library, maybe should support all the targets

### Actual behavior

.NET Core app 3.1 and below are not supported

### Known Workarounds

Downgrade to `5.0.0`

### Configuration

.NET Core app 2.1/2.2

**Comment by danmoseley** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by WeihanLi** [comment]
Think it's better to remove the netstandard2.0 support, since the .NET Core 2.x apps are not supported and already has `netcoreapp3.1` target
![image](https://user-images.githubusercontent.com/7604648/145330721-f6c9fad6-f792-40ca-8511-816185a5e45a.png)

**Comment by GrabYourPitchforks** [comment]
@WeihanLi The netstandard2.0 target will remain for a while longer. netstandard2.0 is supported by runtimes beyond .NET Framework and .NET Core, and those runtimes may still be supported by their maintainers. See the table at https://docs.microsoft.com/dotnet/standard/net-standard#net-implementation-support for more information.

**Comment by WeihanLi** [comment]
@GrabYourPitchforks thanks, since we had a `netstandard2.0` target support and .NET Core 2.x had support for `netstandard2.0`, though .NET Core 2.x had been out of support, I think it would be better if we could have .NET Core 2.x app support
