### ISSUE TITLE
classloader NestedStructs case 03, 04, and 05 failing in mono full AOT

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#62567]

**Comment by lambdageek** [comment]
Disabled by https://github.com/dotnet/runtime/pull/62518

**Comment by lambdageek** [comment]
Hmm... on second thought... isn't this actually an expected failure: the AOT compiler loads and initializes all references classes and structs as part of code generation.  If the class cannot be laid out, we can't generate code that uses it.
