### ISSUE TITLE
Update mono runtime tests CI to generate Core_Root without building CoreCLR

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#62580]
Now that we have a `clr.hosts` subset, and the runtime tests build script has been updated with the ability to create Core_Root from a build of mono without requiring a CoreCLR build, too, we should use it instead of creating a CoreCLR Core_Root and patching it.

Builds on #62500 

Contributes to https://github.com/dotnet/runtime/issues/58266

**Comment by lambdageek** [comment]
@naricc Not sure if there was already an issue for this, but I went ahead and made one and linked it to https://github.com/dotnet/runtime/issues/58266

**Comment by naricc** [comment]
It already exists: https://github.com/dotnet/runtime/issues/43952

**Comment by lambdageek** [comment]
Thanks!

Duplicate of https://github.com/dotnet/runtime/issues/43952
