### ISSUE TITLE
ExecutionContext flow for library code

### ISSUE THREAD

**Issue by WizardBrony** [dotnet/runtime#62589]
In .NET, `ExecutionContext` is an abstraction that manages ambient data relevant to a logical thread of execution. For data consistency, the framework handles the propagation of the current `ExecutionContext` across asynchronous points. For example, even though it isn't documented, `Threading.Timer`'s [`public`] constructors implicitly capture the current `ExecutionContext`, and then the timer runs the user-specified callback under that context when the timer fires. This is great for application-level code: I can store ambient data, and the framework handles propagating that data even if my code goes async. But for custom library-level code that abstracts away an asynchronous point via its API, it's not as straightforward. Here's a simplified example:

```c#
public class CustomTimer
{
    private readonly ExecutionContext _executionContext;

    private Timer _timer;

    public CustomTimer()
    {
        _executionContext = ExecutionContext.Capture() ??
                            throw new InvalidOperationException("Execution context flow must not be suppressed.");
    }

    public void Restart(TimeSpan dueTime)
    {
        if (_timer is null)
        {
            ExecutionContext.Run(_executionContext, static state =>
            {
                var timer = (CustomTimer) state;
                timer._timer = new Timer(static _ => { /*Async code*/ });
            }, this);
        }

        _timer.Change(dueTime, Timeout.InfiniteTimeSpan);
    }

    public void Stop()
    {
        _timer?.Dispose();
        _timer = null;
    }
}
```

Note the capturing of the `ExecutionContext` at the time of construction, and the creation of the `Threading.Timer` under that captured context using `ExecutionContext.Run`. This is necessary for the "Async code" to run under the same `ExecutionContext` (and therefore to see consistent ambient data). Also note the `null` check in the constructor. This is necessary because `ExecutionContext.Run` throws if its `executionContext` parameter is `null`, and therefore `CustomTimer` cannot be instantiated if execution context flow is suppressed.

My question is, is all of this logic as it is written (capturing the execution context and running under that context at implicit async points) necessary, or is there a better pattern to follow for this type of custom library code?

**Comment by davidfowl** [comment]
> My question is, is all of this logic as it is written (capturing the execution context and running under that context at implicit async points) necessary, or is there a better pattern to follow for this type of custom library code?

"necessary" is debatable. It depends on what you're trying to accomplish. If you're trying to make sure the execution context is captured and restored at the "right" time (depending on what behavior you want the library to have) then yes, this manual code is required. I'd question whether you need to care though.

**Comment by WizardBrony** [comment]
> I'd question whether you need to care though.

For generic library-level code to be correct, I'd argue you do need to care. Say that the "Async code" in my example invokes a delegate that the caller provides as an argument to the constructor. Let's also say that the provided delegate refers to a method that references an `AsyncLocal<T>` that has a `Value` at the time the constructor was called. As a user of this library, I would expect that whenever `CustomTimer` invokes my delegate, the `AsyncLocal<T>` will have that same `Value` regardless of the current context at the time `Restart` was called. (Additionally, if the `AsyncLocal<T>` _didn't_ have a `Value` at the time of construction and it _did_ have a `Value` when `Restart` was called, I'd then expect it to _not_ have a `Value` when the delegate is invoked.)

I think the biggest problem I have with my solution is that, since `ExecutionContext.Run` doesn't allow its `executionContext` parameter to be null (and I also see no supported way to obtain a default `ExecutionContext`), `CustomTimer` couldn't be used if execution context flow is suppressed, which could potentially limit its use cases. That's why I was wondering if there are any better patterns to follow that aren't so restrictive.

**Comment by stephentoub** [comment]
> CustomTimer couldn't be used if execution context flow is suppressed

Why not?  The typical pattern is:
```C#
if (executionContext is not null)
{
    ExecutionContext.Run(executionContext, callback, state);
}
else
{
    callback(state);
}
```

**Comment by WizardBrony** [comment]
@stephentoub That makes sense, and that works. I just don't like that, in the case where flow is suppressed at the time of construction but _isn't_ at the time `Restart` is called, that `CustomTimer` is potentially capturing useless ambient state into the `Timer`.

**Comment by stephentoub** [comment]
> Is that the best solution?

Or just create the Timer in CustomTimer's ctor and don't bother with any of this ExecutionContext stuff yourself at all.

But, yeah, if you perform an operation that flows EC and you don't want it to, either it offers an UnsafeXx variant that doesn't flow and you use that, or you Suppress/Restore flow around it.  In the case of Timer, we went with the PeriodicTimer approach for .NET 6, which doesn't flow EC because it doesn't take callbacks to invoke.

**Comment by WizardBrony** [comment]
> Or just create the Timer in CustomTimer's ctor and don't bother with any of this ExecutionContext stuff yourself at all.

I have real-world use cases that dynamically create and dispose `Timer`s after construction via the public API, so an Unsafe variant on `Timer` would have been ideal, though even with that I do feel exposing `ExecutionContext.Default` would have simplified the logic even further. Is there reason for not exposing that beyond minimizing the public surface area?

**Comment by stephentoub** [comment]
> I do feel exposing ExecutionContext.Default would have simplified the logic even further. Is there reason for not exposing that beyond minimizing the public surface area?

There used to be: ExecutionContext instances could only be used once and were mutable.  Neither is the case anymore.

@kouvel?

**Comment by WizardBrony** [comment]
@stephentoub Alternatively, `ExecutionContext.Run` could just support a `null` `executionContext`, which would essentially result in what you recommended earlier, just within `ExecutionContext` instead of user code:

```c#
public static void Run(ExecutionContext? executionContext, ContextCallback callback, object? state)
{
    if (executionContext is not null)
    {
        RunInternal(executionContext, callback, state);
    }
    else
    {
        callback(state);
    }
}
```

Thoughts?

**Comment by stephentoub** [comment]
> Alternatively, ExecutionContext.Run could just support a null executionContext

How does that address your concerns about EC suppression/restore?

**Comment by WizardBrony** [comment]
> How does that address your concerns about EC suppression/restore?

Because then in my original example, I could leave `Restart` written the way it is, and I also wouldn't have to do the `null` check in `CustomTimer`'s constructor.

**Comment by stephentoub** [comment]
But the Timer you create in Restart would still potentially pick up the ExecutionContext current at that time.  Am I misunderstanding the concern?

**Comment by WizardBrony** [comment]
> But the Timer you create in Restart would still potentially pick up the ExecutionContext current at that time. Am I misunderstanding the concern?

Sorry, you're absolutely right:

```c#
public static void Run(ExecutionContext? executionContext, ContextCallback callback, object? state) =>
    RunInternal(executionContext ?? Default, callback, state);
```

**Comment by kouvel** [comment]
>  I do feel exposing ExecutionContext.Default would have simplified the logic even further. Is there reason for not exposing that beyond minimizing the public surface area?

I'm not sure why `ExecutionContext.Default` is not exposed, it looks like it's not there in .NET Framework either, though I'm not sure where else it would be useful to pass in (and null could suffice too). When flow is suppressed `Capture` explicitly returns `null` and `Run` throws for a null context, so it seems intentional. If `Run` did not throw for a null context, maybe a `Capture`/`Restore` sequence could to a reader look like it is capturing/switching contexts when it wouldn't if the flow is suppressed, maybe a readability/clarity thing?

Perhaps an alternative is to suppress/restore flow instead of using `Run`. That would avoid value change notifications and side effects of them if any upon switching contexts with `Run`, though with a couple of extra allocations if a non-default context is being used. Could also be refactored with try/finally to avoid the duplicated code if there's no thread-switching involved in-between suppress/restore.

```c#
    public void Restart(TimeSpan dueTime)
    {
        if (_timer is null)
        {
            if (!ExecutionContext.IsFlowSuppressed())
            {
                using (AsyncFlowControl afc = ExecutionContext.SuppressFlow())
                {
                    _timer = new Timer(_callback);
                }
            }
            else
            {
                _timer = new Timer(_callback);
            }
        }

        _timer.Change(dueTime, Timeout.InfiniteTimeSpan);
    }
```

**Comment by WizardBrony** [comment]
> Perhaps an alternative is to suppress/restore flow instead of using `Run`. That would avoid value change notifications and side effects of them if any upon switching contexts with `Run`

That's a good point. I hadn't been thinking about the potential for unexpected change notifications. This solution will work for today.

@kouvel @stephentoub
Obviously this use case isn't very common, though I have come across it a handful of times. If there is any desire to support it better going forward, I see a couple options right now:

1. Adding member overloads with an `ExecutionContext?` parameter to asynchronous APIs.
2. `ExecutionContext.RunSuppressed`:
```c#
public static void RunSuppressed(ContextCallback callback, object? state)
{
    if (!IsFlowSuppressed())
    {
        using (AsyncFlowControl afc = SuppressFlow())
        {
            callback.Invoke(state);
        }
    }
    else
    {
        callback.Invoke(state);
    }
}
```
or some better implementation.

Any thoughts?

**Comment by WizardBrony** [comment]
One other use case that I don't believe any of the previous suggestions work well for. Say in some library-level code I have a public API whose implementation requires setting an `AsyncLocal<T>` and capturing the current execution context. What do I do if flow is suppressed? I can't capture the current context after setting the `AsyncLocal<T>` if flow is suppressed, but the caller clearly had a reason for suppressing flow in the first place, so it would be rude to forcibly restore flow and end up capturing ambient state that the caller didn't want me to.

**Comment by kouvel** [comment]
> Say in some library-level code I have a public API whose implementation requires setting an `AsyncLocal<T>` and capturing the current execution context. What do I do if flow is suppressed?

Since the API requires capturing the context for use elsewhere, would it make sense to throw if context flow is suppressed?

**Comment by WizardBrony** [comment]
> Since the API requires capturing the context for use elsewhere, would it make sense to throw if context flow is suppressed?

I was trying to think of a solution that didn't include throwing since it's an implementation detail, but yes, it would otherwise make sense.

**Comment by kouvel** [comment]
> `ExecutionContext.RunSuppressed`

This may be a bit confusing for async delegates since the code before and after the `await` may run under different contexts, even if flow is suppressed for both.

> Adding member overloads with an `ExecutionContext?` parameter to asynchronous APIs.

Or maybe just a boolean to indicate whether to flow the context or run in the default context, which may be a bit better than the current pattern of using an `Unsafe` prefix.

**Comment by WizardBrony** [comment]
> This may be a bit confusing for async delegates since the code before and after the `await` may run under different contexts, even if flow is suppressed for both.

True, that's a fair criticism.

> Or maybe just a boolean to indicate whether to flow the context or run in the default context, which may be a bit better than the current pattern of using an `Unsafe` prefix.

Sure, I like that too.

**Comment by WizardBrony** [comment]
Option 3. Expose `ExecutionContext.Default`.

**Comment by WizardBrony** [comment]
@kouvel I have one other use case. Say I have a public API whose implementation requires running code _synchronously_ under a specific execution context. Is the following the best way to run "Sync code" this way without triggering the caller's change notifications?

```c#
public class C
{
    private ExecutionContext _executionContext;

    ...

    public void SyncMethod()
    {
        Task t;
        if (!ExecutionContext.IsFlowSuppressed())
        {
            using (ExecutionContext.SuppressFlow())
                t = StartTask();
        }
        else
        {
            t = StartTask();
        }

        Task StartTask()
        {
            return Task.Factory.StartNew(
                static state => ExecutionContext.Run(((C)state)._executionContext, static _ => { /*Sync code*/ }, null),
                this, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
        }

        t.Wait();
    }
}
```

**Comment by kouvel** [comment]
> Say I have a public API whose implementation requires running code synchronously under a specific execution context. Is the following the best way to run "Sync code" this way without triggering the caller's change notifications?

That sounds a bit contradictory. Running under a specific execution context may require triggering the value change notifications in order for the state to be as expected for that context.

**Comment by WizardBrony** [comment]
> That sounds a bit contradictory. Running under a specific execution context may require triggering the value change notifications in order for the state to be as expected for that context.

I understand it may look a bit odd, but after thinking about it more, for my particular use case, it seems correct given what is necessary for the asynchronous (`Timer`) use case. Thanks a lot for the discussion.

**Comment by kouvel** [comment]
The `Task.Wait` call may run the work item inline in the same thread, and even though the task does not capture the context, the execution context on the thread would be reset to default before running the task, which I believe would also trigger value change notifications. Then `ExecutionContext.Run` would still trigger the value change notifications for the specified context.

**Comment by kouvel** [comment]
If the task happens to run asynchronously and the calling thread happens to be a thread pool thread, it could lead to starvation due to [sync-over-async](https://devblogs.microsoft.com/pfxteam/should-i-expose-synchronous-wrappers-for-asynchronous-methods/), I'd suggest avoiding that pattern, esp. in library code.

**Comment by WizardBrony** [comment]
@kouvel You’re right, the `Task` may run the work item inline and end up triggering change notifications anyway, so I don’t see a pattern that will work here. The use case is not performance-sensitive. It is basically an API for synchronously simulating how some given work would be executed asynchronously (via the callback of a `Timer` instantiated with execution context flow disabled, and thus initially running under the default context until the callback calls `ExecutionContext.Run`). In other words, I don’t care about the notifications triggered by a DefaultExecutionContext -> MyExecutionContext switch, because that’s what would actually happen asynchronously. I care about preventing notifications from a CallerExecutionContext -> MyExecutionContext switch, because that _wouldn’t_ happen asynchronously.

Ultimately the issue here is that execution context is an application-focused feature/service, so as I’m trying to manipulate it in library code, I’m fighting with the API.

**Comment by kouvel** [comment]
I think the pattern you used above is the only way to do that, except to queue up the task with `TaskCreationOptions.PreferFairness`, which would prevent it from running inline on the same thread. If perf is not an issue, using `TaskCreationOptions.LongRunning` instead would cause the task to run (currently) on a new thread and would avoid the worst part of the sync-over-async issue (a thread pool thread waiting for another thread pool thread).

**Comment by WizardBrony** [comment]
@kouvel Thank you for confirming the pattern. When either of these options are specified, does the default scheduler guarantee that the work item will run on a separate thread?

**Comment by kouvel** [comment]
Yea that's a good point, that's how the current implementation works but I don't think there is a guarantee in that behavior based on the descriptions (though probably unlikely it would change). It's probably best to create a custom task scheduler to get guaranteed behavior.

**Comment by WizardBrony** [comment]
@kouvel 

> It's probably best to create a custom task scheduler to get guaranteed behavior.

That seems like a lot of work....

What about this pattern? It seems much simpler:

```c#
public class C
{
    private ExecutionContext _executionContext;

    ...

    public void SyncMethod()
    {
        using ManualResetEventSlim mres = new();

        ThreadPool.UnsafeQueueUserWorkItem(static state =>
        {
            ExecutionContext.Run(state._executionContext, static _ => { /*Sync code*/ }, null);
            state.mres.Set();
        }, (_executionContext, mres), preferLocal: false);

        mres.Wait();
    }
}
```

Does that provide the guarantees I'm looking for?

**Comment by kouvel** [comment]
`preferLocal: false` is similar in behavior to `TaskCreationOptions.PreferFairness`. Currently worker threads don't run other work items while waiting like above and it's unlikely that would change, so it would work as you expect. Another simple option may be to create/start a new thread using `Thread.UnsafeStart()` and have that do the sync work.

**Comment by WizardBrony** [comment]
@kouvel 

> `preferLocal: false` is similar in behavior to `TaskCreationOptions.PreferFairness`.

This isn't really a question of the `preferLocal: false` implementation and is more about the guarantee that you get from `ManualResetEventSlim.Wait`, right? The danger with using `TaskCreationOptions.PreferFairness` is that the implementation could be changed to run the `Task`'s work inline, which would result in the potential change notifications that I'm trying to prevent. But that's documented as such ("prefer" versus "guarantee" fairness) and the work that it could run inline is the work that was specified when the `Task` was created. `ManualResetEventSlim.Wait` has no documentation related to inline execution, nor any instance-specific work it could be associated with, so in what valid implementation could the thread calling `mres.Wait()` also end up running the work being passed to `ThreadPool.UnsafeQueueUserWorkItem`? (Note that by "thread" I'm referring to the logical (CoreCLR) `Thread`; the OS/runtime could use the same physical thread to run both of those work items with no issue as long as their logical threads (and associated execution contexts, if any) remain unique.)

**Comment by kouvel** [comment]
> so in what valid implementation could the thread calling mres.Wait() also end up running the work being passed to `ThreadPool.UnsafeQueueUserWorkItem`?

None at the moment and perhaps unlikely to change, but theoretically anyway in a green-threaded model it would be feasible to run other work items when one work item hits a wait. There are stronger guarantees in the current implementation. A `Thread` instance maps directly to an OS thread, that probably would not change for compatibility reasons. Anyway, I don't think it's that important a distinction, either would suffice for your purposes, if perf is not an issue, using a separate thread may be considered slightly better than waiting on another thread pool thread.

**Comment by WizardBrony** [comment]
@kouvel 
> but theoretically anyway in a green-threaded model it would be feasible to run other work items when one work item hits a wait.

I understand theoretically it's possible from an implementation standpoint, but I don't see how it's possible from an API standpoint. The summary for `ManualResetEventSlim.Wait()` is:

> Blocks the current thread until the current [ManualResetEventSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualreseteventslim?view=net-6.0) is set.

The "current thread" in this case must be the current green thread because, as far as I know, neither .NET nor the CLR make any implementation guarantees about the use of non-virtual threads. `Wait` "blocks" the current thread, meaning it cannot do any work until the method completes. But let's just say that "blocking" includes performing other tasks in the meantime. How would that work? .NET explicitly removed the ability to perform thread aborts, so if the current thread started doing other work during a `Wait`, it might take an unpredictable amount of time to complete (if it ever does), meaning `Wait` may continue blocking well after "the current `ManualResetEventSlim` is set."

I recognize that this is all theoretical to begin with. I would just like to understand how the API doesn't protect me here.

**Comment by stephentoub** [comment]
> How would that work?

In a green threads model, the "thread" being blocked could just be a stack that could be taken off of the actual OS thread and moved somewhere else.  When the MRES was set, it could just be scheduled to run on the next available OS thread, not necessarily the same one as before.

> so if the current thread started doing other work during a Wait, it might take an unpredictable amount of time to complete (if it ever does), meaning Wait may continue blocking well after "the current ManualResetEventSlim is set."

But yes, if decided to implement this via pumping of other work items during waits, it would potentially delay the return of Wait.  That's one of the reasons why, for example, when you do Task.Wait() on a delegate-backed task, at most we only try to execute the delegate for that Task as part of the Wait, even though we could easily try to pump other work items as well.

**Comment by WizardBrony** [comment]
@stephentoub 
> In a green threads model, the "thread" being blocked could just be a stack that could be taken off of the actual OS thread and moved somewhere else. When the MRES was set, it could just be scheduled to run on the next available OS thread, not necessarily the same one as before.

Right. And in that case I'm assuming (and please confirm that this is the case) the green thread would move with the stack and remain the same even if the OS thread is different after the wait. For example, regardless of whether `ManualResetEventSlim.Wait`'s implementation performs other work or not, I assume I should always be able to

```c#
var greenThread = Thread.CurrentThread;

mres.Wait();

Assert(ReferenceEquals(Thread.CurrentThread, greenThread));
```

Additionally, I assume that `greenThread` would not be `Thread.CurrentThread` for any other work during the wait, which would give me the guarantee I'm looking for.

> But yes, if decided to implement this via pumping of other work items during waits, it would potentially delay the return of Wait. That's one of the reasons why, for example, when you do Task.Wait() on a delegate-backed task, at most we only try to execute the delegate for that Task as part of the Wait, even though we could easily try to pump other work items as well.

Agreed. Also, the `Task` cannot possibly complete any time before the delegate completes since the delegate is the work that defines a delegate-backed `Task`. Therefore it makes sense for `Task.Wait` to try to execute the delegate if it hasn't already been started since the user is clearly wanting it to execute as soon as possible if they're calling `Wait`. But `ManualResetEventSlim` has no delegate or work associated with it, so even though it's technically possible for it to, from my point of view, having `Wait` perform work that the `ManualResetEventSlim` doesn't own would be a breaking API change since it may not only block "until the current `ManualResetEventSlim` is set."

**Comment by stephentoub** [comment]
> having Wait perform work that the ManualResetEventSlim doesn't own would be a breaking API change since it may not only block "until the current ManualResetEventSlim is set."

Not really.  You have no guarantees the OS today will schedule the thread blocked on the MRES immediately when set is called.  It might not wake up and return from Wait for a long time even though set was called.

> I assume that greenThread would not be Thread.CurrentThread for any other work during the wait

I'm not sure that's a valid assumption, but even if it were, that Thread object is just a data structure.  What does it have to do with whatever guarantee you're looking for?

I'm not sure how useful this discussion is, though. This is all theoretical.

**Comment by WizardBrony** [comment]
@stephentoub 
> I'm not sure how useful this discussion is, though. This is all theoretical.

That's fair.

Ultimately, I want a synchronization mechanism that has guarantees about the observable effects of synchronizing, but it sounds like that's a framework implementation detail that can't be guaranteed. As a library developer, it's frustrating that I don't have more control over related application-focused features, but I understand why.
