### ISSUE TITLE
Incorrect translation of Ping error codes

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#62592]
Spotted in #62559:

On non-Windows the error code in raw-socket Ping code path is translated incorrectly:
- https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/IcmpV4MessageConstants.cs#L80
- https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Ping/src/System/Net/NetworkInformation/IcmpV6MessageConstants.cs#L79-L84
(should be `TtlExpired` instead of `TimeExceeded`)

In the non-privileged code path running the `ping` command line utility it will presumably return `TimeExceeded` without an address. The `SendPingToExternalHostWithLowTtlTest` outer loop test should be modified accordingly to detect this case.

**Comment by karelz** [comment]
Triage: Would be good to have. Should be fairly straightforward.

**Comment by deeprobin** [comment]
Feel free to assign me :smile:
