### ISSUE TITLE
Explicit struct size is not always taken into account in code emitted at runtime

### ISSUE THREAD

**Issue by ltrzesniewski** [dotnet/runtime#62597]
### Description

After updating from .NET 5 to .NET 6, our code started to fail in a very specific code path. It _looks like_ a case where the `StructLayoutAttribute.Size` field is not taken into account in code emitted at runtime, although I'm not sure if that's the root cause.

The problem only reproduces under Linux with optimizations enabled.

### Reproduction Steps

The following program exhibits the issue:

```C#
using System;
using System.Reflection.Emit;
using System.Runtime.InteropServices;
using System.Text;

namespace ConsoleApp;

[StructLayout(LayoutKind.Explicit, Size = 32)]
public readonly unsafe struct SmallString
{
    [FieldOffset(0)] private readonly byte _length;
    [FieldOffset(1)] private readonly byte _firstByte;

    public SmallString(string value)
    {
        fixed (char* srcPtr = value)
        fixed (byte* destPtr = &_firstByte)
        {
            Encoding.ASCII.GetBytes(srcPtr, value.Length, destPtr, value.Length);
        }

        _length = (byte)value.Length;
    }

    public string Dump()
    {
        fixed (byte* ptr = &_firstByte)
        {
            return $"{BitConverter.ToString(new ReadOnlySpan<byte>(ptr, _length).ToArray())}: {Encoding.ASCII.GetString(ptr, _length)}";
        }
    }
}

public static class Program
{
    public static void Main()
    {
        var value = new SmallString("foobar");
        Execute(value);

        var method = new DynamicMethod("test", typeof(void), new[] { typeof(SmallString) }, typeof(Program), true);
        var il = method.GetILGenerator();
        il.Emit(OpCodes.Ldarg_0);
        il.EmitCall(OpCodes.Call, typeof(Program).GetMethod("Execute")!, null);
        il.Emit(OpCodes.Pop);
        il.Emit(OpCodes.Ret);

        var action = (Action<SmallString>)method.CreateDelegate(typeof(Action<SmallString>));
        action.Invoke(value);
    }

    public static object Execute(SmallString foo)
    {
        Console.WriteLine(foo.Dump());
        return new StringBuilder();
    }
}
```

The project file is fairly standard:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
```

### Expected behavior

The program is supposed to print the following:

```
$ dotnet run -c Release
66-6F-6F-62-61-72: foobar
66-6F-6F-62-61-72: foobar
```

It basically calls `Execute(value)` directly, then through a dynamic method. Both outputs should be the same.

### Actual behavior

When run under **Linux x64** in **Release** mode, the following output is produced:

```
$ dotnet run -c Release
66-6F-6F-62-61-72: foobar
66-00-00-00-00-00: f
```

The program produces the correct output in Debug mode, or under Windows in both Debug and Release.

Note that the part that is zeroed out corresponds to the part of the struct that is not covered by fields. The `f` is not zeroed out since it is stored in the `_firstByte` field.

FYI, I have observed bytes other than `00` following the `f` in our real code. An example output string would be `fÿÚ,\u007f\u0000`, but this repro only seems to output zeros though.

### Regression?

This worked fine under .NET 5. The repro code does not exhibit the issue when recompiled for net5.0.

### Known Workarounds

Adding the following field to `SmallString` fixes the issue:

```C#
[FieldOffset(31)] private readonly byte _lastByte;
```

But then, even other small changes to the repro code make the issue go away...

### Configuration

The issue reproduces on Linux in x64.

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

Windows on x64 does not exhibit the behavior. I haven't tested other configurations.

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib @kunalspathak.

**Comment by DaZombieKiller** [comment]
Just worth noting, the `SmallString` struct can also be implemented using a fixed buffer, which avoids the need for explicit layout entirely:
```cs
public unsafe struct SmallString
{
    private readonly byte _length;
    private fixed byte _bytes[31];

    public SmallString(string value)
    {
        fixed (char* srcPtr = value)
        fixed (byte* destPtr = _bytes)
        {
            Encoding.ASCII.GetBytes(srcPtr, value.Length, destPtr, 31);
        }

        _length = (byte)value.Length;
    }

    public readonly string Dump()
    {
        fixed (byte* ptr = _bytes)
        {
            return $"{BitConverter.ToString(new ReadOnlySpan<byte>(ptr, _length).ToArray())}: {Encoding.ASCII.GetString(ptr, _length)}";
        }
    }
}
```

**Comment by kunalspathak** [comment]
I was able to repro the issue. @DaZombieKiller - The code you have is not sufficient to repro the issue.

**Comment by DaZombieKiller** [comment]
@kunalspathak Sorry if my post had that impression -- it wasn't intended as a repro for the issue, just an alternative implementation of the type that avoids explicit layout (and thus any problems associated with it), as I'm assuming the OP is using a more complete version of it in their code.

**Comment by ltrzesniewski** [comment]
Yes, extracting that repro from our actual code was a massive pain 🙂

**Comment by kunalspathak** [comment]
> Sorry if my post had that impression 

Ah ok.

**Comment by kunalspathak** [comment]
I was able to trace down the cause. The problem is how we pass the `SmallString` argument from inside `test` method to the `Execute` method. The problem disappears when `export COMPlus_JitNoStructPromotion=1`. Below, left side is the working code with struct promotion turned OFF and right side has struct promotion ON.

On left, we see that we copy the entire struct contents (32 bytes) on stack, but on right, we copy just the 1st byte (which is zero extended too).

![image](https://user-images.githubusercontent.com/12488060/145484130-96a6e4e1-4d54-4654-8306-265766e1cd8d.png)

I will investigate further.

**Comment by kunalspathak** [comment]
So the discrepancy was introduced in #43870 around https://github.com/dotnet/runtime/pull/43870/files#diff-69d08b043e8e069b6faa42c99da5c39546bc1b8f3035b7e8d860b59b10a3a5f3L1986-R2013. I will prepare the fix.

**Comment by ltrzesniewski** [comment]
Thanks! 🙂
