### ISSUE TITLE
ApplicationSettingsBase fails when same attribute appears at class level and at property level

### ISSUE THREAD

**Issue by StefanCuypers** [dotnet/runtime#62593]
### Description

Discovered while using nullable context: seems the nullable attribute is added at class level and at property level. During initialization the ApplicationSettingsBase then fails with a System.ArgumentException:'Item has already been added.  Key in dictionary: 'System.Runtime.CompilerServices.NullableAttribute'  Key being added: 'System.Runtime.CompilerServices.NullableAttribute'.

### Reproduction Steps

Visual Studio 2022 - Create a new Console App using .Net 6.0.
**Program.cs**
```
var settings = new ConsoleApp1.TestSettings();
// Next statement gives an exception
settings.SettingsKey = "test";
```
**TestSettings.cs**
```
using System.Configuration;

namespace ConsoleApp1
{
    /// <summary>
    /// Test class.
    /// </summary>
    internal class TestSettings : ApplicationSettingsBase
    {
        /// <summary>
        /// Nullable first property
        /// </summary>
        [UserScopedSetting]
        public string? MyValue
        {
            get { return (string?)this[nameof(MyValue)]; }
            set { this[nameof(MyValue)] = value; }
        }

        /// <summary>
        /// Non-nullable second property (we need both a nullable and non-nullable property, else the nullable attribute is not present at the property level)
        /// </summary>
        [UserScopedSetting]
        public string MyValue2
        {
            get { return (string)this[nameof(MyValue2)]; }
            set { this[nameof(MyValue2)] = value; }
        }
    }
}

```

### Expected behavior

Should work without throwing an Exception.

### Actual behavior

Throws an ArgumentException.

System.ArgumentException
  HResult=0x80070057
  Message=Item has already been added. Key in dictionary: 'System.Runtime.CompilerServices.NullableAttribute'  Key being added: 'System.Runtime.CompilerServices.NullableAttribute'
  Source=System.Private.CoreLib
  StackTrace:
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Configuration.ApplicationSettingsBase.CreateSetting(PropertyInfo propertyInfo)
   at System.Configuration.ApplicationSettingsBase.EnsureInitialized()
   at System.Configuration.ApplicationSettingsBase.get_Context()
   at System.Configuration.ApplicationSettingsBase.set_SettingsKey(String value)
   at Program.<Main>$(String[] args) in C:\t\test\ConsoleApp1\ConsoleApp1\Program.cs:line 3

### Regression?

If we disable the nullable context it does work.

### Known Workarounds

Disable the nullable context for the ApplicationSettingsBase derived class using #nullable disable.

### Configuration

.Net 6.0 Console application on Windows 10.

### Other information

I think the problem is in the ApplicationSettingsBase.CreateSetting() method.
If the attribute type is not recognised it does:
`settingsProperty.Attributes.Add(attribute.GetType(), attribute);`
However if the attribute already existed at class level this gives the Exception.
I think the code should be changed to: 
`settingsProperty.Attributes[attribute.GetType()] = attribute;`
This would actually overwrite the class level attribute by the property level attribute.

**Comment by buyaa-n** [comment]
> I think the code should be changed to:
> settingsProperty.Attributes[attribute.GetType()] = attribute;

Thanks for reporting the bug @StefanCuypers, your suggestion sounds right, interested in contributing with a fix and unit test?

**Comment by StefanCuypers** [comment]
I’m not familiar with the whole build process and unit testing in Github I’m afraid and I don’t have much time available. So, I’ll leave it to others to fix this.
