### ISSUE TITLE
dotnet on linux does not use available TLS 1.2 cypher

### ISSUE THREAD

**Issue by Spongman** [dotnet/runtime#62607]
### Description

This (https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux) doc states that dotnet 5 & 6 on linux will not use TLS 1.0 & 1.1 cyphers.

AES256-GCM-SHA384 is a TLS 1.2 cypher.

`openssl ciphers -s -tls1_2` shows this cypher as available on my client.

both `wget` and `curl` use that cypher when talking to my server:

![image](https://user-images.githubusercontent.com/1088194/145481887-ef266dc0-94d0-49c4-9013-a765bcde082c.png)

why do those tools work without additional configuration, when dotnet programs do not?

it seems convoluted to require my users to edit their system configuration just to enable a cypher which is _already_ enabled on their system.

### Reproduction Steps

install dotnet 6.0 on Ubutun 21.04. use `HttpConnection` to connect to remote server.

### Expected behavior

should enable AES256-GCM-SHA384

### Actual behavior

doesn't enable AES256-GCM-SHA384

### Regression?

yes

**Comment by wfurt** [comment]
That particular cipher suite is considered weak https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_GCM_SHA384/
Goal of the breaking change was to provide secure defaults (with fallback possible to weak crypto) 
So while system crypto may offer weak options and some other software may choose them .NET will not in general push for more secure practices. (Azure and and upcoming Windows releases as well)
There is ECDHE-RSA-AES256-GCM-SHA384 in the default set you should use instead. (if you can)

cc: @blowdart @bartonjs

**Comment by Spongman** [comment]
I don't see why that's relevant. My operating system is configured to use it. dotnet applications should follow the operating system's configuration by default.

**Comment by karelz** [comment]
If the OS / OpenSSL offers ability to opt-in into strong crypto cyphers, we want to use it by default. We want .NET users to be on secure path by default. We also want to ensure users have option to opt out of that settings into weak crypto if they want -- but it needs to be explicit user choice.

We don't have any plans to make any further changes in the space in the opposite direction of the intentional breaking change linked above.
@blowdart or @bartonjs may choose to reply with more details on the background of that decision when they are back in January.

Closing the issue as it is not actionable.

**Comment by blowdart** [comment]
No extra comment needed - we won't enable weak ciphers by default. Ssllab reports are important to a lot of people and it's a common way to grade a web server configuration and it will, rightfully, flag aes256-gcm-sha384. It's not a regression, it's a security enhancement.

**Comment by Spongman** [comment]
I don’t know why you’re talking about web server configurations. I specifically called out using it from `HttpClient`. Ssllab is irrelevant.

**Comment by blowdart** [comment]
Even then it's still a weak cipher for a client to use. Any well configured endpoint should have more ciphers than this configured and httpclient with negotiate to find one both sides support. So either you have a server where that's the only cipher, in which case no, you're going to have to reconfigure clients or the auto negotiation isn't happening which is a much different bug and should be a new issue.

**Comment by Spongman** [comment]
I cannot reconfigure the endpoint. I do not control it.

**Comment by wfurt** [comment]
BTW I'm not sure this was clear @Spongman but you can still go through the `CipherSuitePolicy` option e.g. request the weak ciphers in your APP instead of fiddling with os files.
