### ISSUE TITLE
Is cross compiling CoreCLR for apple silicon possible on a x64 MacOS machine?

### ISSUE THREAD

**Issue by UnityAlex** [dotnet/runtime#62608]
More of an inquiry than anything. I attempted: `./build.sh -a arm64` on my macbook

I saw the following error in the build log:
```
runtime/src/coreclr/pal/src/synchmgr/synchmanager.cpp:4629:6: error: "Don't know how to get hi-res current time on this platform"
      #error "Don't know how to get hi-res current time on this platform"
```

Seems like neither `HAVE_WORKING_CLOCK_GETTIME` or `HAVE_WORKING_GETTIMEOFDAY` are being defined when building this way?

Potentially relevant system info:
Xcode version: 13.1
OS: Monterey 12.0.1
I've ran `brew bundle --no-lock --file eng/Brewfile` already

**Comment by EgorBo** [comment]
I think it needed either `--cross` or `/p:CrossBuild=true` for that

**Comment by hoyosjs** [comment]
Our official build is always a cross build. As Egor pointed out, there's arguments that need to be passed to signify that. Largely this is the equivalent of our official build command:

`./build.sh -rc release -cross -arch arm64  -c release -framework net7.0 /p:CrossBuild=true`

**Comment by jkotas** [comment]
Needs to be mentioned in [docs](https://github.com/dotnet/runtime/tree/main/docs).

**Comment by UnityAlex** [comment]
Thanks! I was able to get it to build successfully.

**Comment by UnityAlex** [comment]
closed by accident apologies. I'll leave open for the documentation change.

**Comment by agocke** [comment]
Woops, also closed by accident
