### ISSUE TITLE
[API Proposal]: RegexRunner.IsWordChar

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#62603]
### Background and motivation

`\w` is very common in regexes.  For complicated sets, which \w is, our source generated regex emits a complex piece of code that involves checking whether the character is ASCII: if it is, it looks up a bit in an 8-char string used as a 128-bit lookup table, and if it isn't, it falls back to using RegexRunner.CharInClass with the set specification string.  It ends up looking like this:
```C#
if (((ch = span[i]) < 128 ? ("\0\0\0Ͽ\ufffe蟿\ufffe\u07ff"[ch >> 4] & (1 << (ch & 0xF))) != 0 : global::System.Text.RegularExpressions.RegexRunner.CharInClass((char)ch, "\0\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0")))
```
We could simplify the code (and potentially make it a bit faster) by exposing a protected RegexRunner.IsWordChar method that the source generator-produced code could call to.  We already have the protected RegexRunner.IsBoundary, which uses the internal RegexCharClass.IsWordChar, so this would effectively be exposing the latter next to the former.

### API Proposal

```diff
namespace System.Text.RegularExpressions
{
    public class RegexRunner
    {
+        protected static bool IsWordChar(char ch);
    }
}
```

### API Usage

```C#
// in source-generated code
if (base.IsWordChar(span[i])) { ... }
```

**Comment by joperezr** [comment]
I suppose this is really just meant to be used by the source generator in terms of readability right? If so, I wonder if it would make sense to instead just have the source generator also spit out a local function with the implementation (when needed only by using the new infra that you added for writing local funcs) and then having the primary implementation just call this. I'm not opposed into exposing this extra protected method, and if we think that there will be a lot of usage from non-source generated sub classes of RegexRunner then let's do it, but it feels like this is just for the source generated code and in such case I think perhaps just generating this as a local func still gives you the readability but without the need to expose it on base.

**Comment by stephentoub** [comment]
> If so, I wonder if it would make sense to instead just have the source generator also spit out a local function with the implementation (when needed only by using the new infra that you added for writing local funcs) and then having the primary implementation just call this.

Yeah, we can do that.  It just means we'll be spitting https://github.com/dotnet/runtime/blob/12a8819eee9865eb38bca6c05fdece1053102854/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexCharClass.cs#L978-L1017 into every generated regex. (We could reduce that to be once per assembly at least if a) we were willing to take the risk of the code being accessed by the rest of the project or b) C# provides a mechanism that doesn't yet exist for source generators to spit out code not usable directly by user-written code.) For reference, ~10% of the patterns in our data set use \w.

I don't expect any usage from anything outside of the source generator.  Or at least there shouldn't be any :)

**Comment by stephentoub** [comment]
(We could start with that, though, and see how it feels.)

**Comment by stephentoub** [comment]
For 7, let's stick with source gen.
