### ISSUE TITLE
Consider rebuilding loop table after loop cloning

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#62615]
Doing this would put the "slow path" cloned loop in the loop table, enabling it for downstream optimization, such as hoisting, and possibly enabling hoisting things common to the slow and fast paths.

It would also let the slow path show more clearly in the JitDumpFg "dot" graph dumps.

category:cq
theme:loop-opt
skill-level:intermediate
cost:medium
impact:small

**Comment by jakobbotsch** [comment]
Fixed by PRs listed in https://github.com/dotnet/runtime/issues/93144#issuecomment-1853750565
