### ISSUE TITLE
Crash caused by corrupted stack in System.Net.Quic tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#62613]
Crash dump: `runfo get-helix-payload -j 5b5b3a98-af71-44f7-96d2-3e4df7dcae00 -w System.Net.Http.Functional.Tests -o c:\helix_payload\System.Net.Http.Functional.Tests`

Hit by #62590

**Comment by jkotas** [comment]
The crash is caused by stack corrupted around the call to `ConfigurationLoadCredentialDelegate`.

There is one obvious interop problem in mismatched definition of `CredentialConfig` structure. The unmanaged version of this structure has `AllowedCipherSuites` field that is missing in the managed definition. This problem alone cannot explain the crash, there are likely more similar interop issues, potentially in interop calls done that happened earlier.

**Comment by thhous-msft** [comment]
The AllowedCipherSuites field is only read if QUIC_CREDENTIAL_FLAG_SET_ALLOWED_CIPHER_SUITES is passed as one of the flags. And it doesn't seem like that is happening from the .NET side, so I suspect its unrelated.

**Comment by jkotas** [comment]
Yes, I agree that the crash is unrelated to the mismatched definition of `CredentialConfig`. It seems to be regression in the runtime introduced by recent change (#62271)
