### ISSUE TITLE
Resolve inconsistency between \w and \b determination for what is a word character

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#62619]
Currently our definition of `\b` explicitly adds `\u200c` and `\u200d` beyond what `\w` represents.  The TR18 report calls out that these should be part of word boundaries, but there's ambiguity as to whether they should also be part of `\w`.  We appear to have made an explicit choice at some point to not include these two additional chars in the definition of `\w`, but that seems like a strange inconsistency, one which we bend over backwards to maintain in a variety of places.  We should reconsider whether this discrepancy continues to make sense, or whether it would make sense for these to also be considered a match for `\w`.

cc: @veanes

**Comment by joperezr** [comment]
@stephentoub do we still want to do this for 7.0?

**Comment by danmoseley** [comment]
TR18 is probably less important then what PCRE, Perl etc do. I can check.

**Comment by danmoseley** [comment]
On .NET 6 and .NET 7 preview 5, neither of them match `\b` -- see https://regex101.com/r/gPrCln/1   -- this is at odds with what you're noting above.
In PCRE, Python, Golang, Java, both match `\b`.

In all cases neither of them match `\w`  (all match `\W`)

**Comment by stephentoub** [comment]
> Did anything change in .NET 7 here?

Semantically, no.

> Although odd, any particular reason to fix today?

We have a new engine in .NET 7 that has to emulate the difference.  It'd be nice it that wasn't the case.

I think we either address this in 7 or decide it is what it is and close this.

> What am I missing?

I'm not sure what your repro is trying to show.

\w matches a set of characters.  When we ask "is this character a word character", we see if the character is in that set.  But when we ask "is this character considered a word character for the purpose of deciding whether it's at a word boundary", we see whether it's in that set or is \u200c or\u200d.  So even though:
```C#
Regex.IsMatch("\u200c", @"\w")
```
is `false` because `\u200c` is not a word character, this:
```C#
Regex.IsMatch("\u200cz‌\u200c", @"\b\w\b")
```
is also `false`, because even though `z` is a word character and it's surrounded by two characters (`\u200c`) that aren't word characters, they're considered word characters for the purposes of the anchor analysis.

As https://regex101.com/r/nrhRqT/1 shows, PCRE, JavaScript, Python, Golang, and Java all do something different from what .NET does here.

**Comment by danmoseley** [comment]
Oh! Of course. 

Across Regex we have generally biased towards what seems to be most useful, and any consensus behavior of other engines (mainly PCRE), rather than specs. That would be consistent with making the change.

**Comment by veanes** [comment]
Let me add my take on the situation, I think I may have been the one raising the `\w` vs `\b` issue originally. 
Here is the kind of situation that is unique to .NET. The below regex `r` seems fairly common I think.
```
Regex r = new Regex(@"\b\w+\b");
var m = r.Matches("n\u200co wor\u200cds he\u200cre");
Console.WriteLine(m.Count);
```
Will print `0`, that takes quite a while to figure out why, and is definitely _counterintuitive_ to say the least.
**All other matchers**, as far as I know, either print 3 (`\u200c` is considered a word char) or 6.
(`\u200c` is considered a non-word char)

**Comment by stephentoub** [comment]
The change is small if we want to do it:
https://github.com/dotnet/runtime/compare/main...stephentoub:runtime:slashbslashwconsistency
The removes the \u200c and \u200d special-casing from \b such that it considers the identical set as \w.  The other direction is also possible, e.g. make \w also consider \u200c and \u200d as word characters, which appears to be Java's interpretation of TR18 when you opt-in to full unicode matching:
https://regex101.com/r/vonZDn/1

**Comment by danmoseley** [comment]
@joperezr any preference?

**Comment by joperezr** [comment]
I agree that we shouldn't do special-casing for those two characters, as it just causes inconsistencies between meanings of `\w` and `\b`. My only pushback would be if people depended on this inconsistency, but sounds like we don't think that's the case, so I'm in favor of making the change.

**Comment by veanes** [comment]
Note that the easier path is to treat `\u200c` and `\u200d` as non-word characters --- just because then we don't have to regenerate the serialized representation of `\w`, alternatively we can add `\u200c` and `\u200d` into the BDD created from the serialized representation each time (not too difficult either but would be a small overhead each time `\w` is being used for the first time), or else we regenerate the serialized representation so these two are included from the start.

**Comment by stephentoub** [comment]
> I'll put up a PR.

Actually, this direction is harder than I expected:
- Making \b not include the two additional characters, easy.
- Making \w include the two additional characters, hard.

The problem is actually with how we represent character classes internally.  The representation is essentially a set of ranges for characters to include, a set of Unicode categories to include, and an optional negation bit. Importantly, the representation of the categories also allows them to be defined as exclusions rather than as inclusions.  So \w is defined today as a set of several Unicode category inclusions, no ranges, no negation, and \W is defined today as a set of several Unicode category exclusions, no ranges, no negation.  If \w needs to include the two additional characters, no problem, we just add in the ranges for them.  But what about \W?  The main way we could represent that would be the same as the new \w but with the negation bit set, however that then falls over when it's combined into a larger character class, e.g. how do you represent [\Wab]?

**Comment by joperezr** [comment]
I see, it is indeed rather complicated. And I suppose there is no Unicode Category  that is already imported into \w that could just take these extra two characters so as to not require ranges to define it?

Given this problem, should we just go with the other solution for this inconsistency that you quoted above: `The removes the \u200c and \u200d special-casing from \b such that it considers the identical set as \w`?

**Comment by stephentoub** [comment]
> And I suppose there is no Unicode Category that is already imported into \w that could just take these extra two characters so as to not require ranges to define it?

Right.  \w is exactly the combination of:

- `UppercaseLetter`
- `LowercaseLetter`
- `TitlecaseLetter`
- `ModifierLetter`
- `OtherLetter`
- `NonSpacingMark`
- `DecimalDigitNumber`
- `ConnectorPunctuation`

`\u200c` and `\u200d` are instead in the `Format` category, which today contains 38 other characters as well, so we can't just add `Format` to the list.

> The removes the \u200c and \u200d special-casing from \b such that it considers the identical set as \w?

I've gone back and forth, but I think if we're going to make a change, we should do it "right", and I think "right" would be making both of these word characters.  I don't see a good path to doing so for the foreseeable future, though.  Given that, I think the least bad option is to just stick with what we currently have.

As such, I'll close this.  If we ever get negative feedback about it, and/or if we ever change our set representation to better enable this, we can revisit.
