### ISSUE TITLE
Enumerable.MinBy and Enumerable.MaxBy may or may not throw on empty collections depending on the collection type

### ISSUE THREAD

**Issue by instantsc** [dotnet/runtime#62656]
### Description

https://github.com/dotnet/runtime/issues/53528 mentions the issues when these methods change their behavior "unpredictably" based on the predicate type. I think the behavior changing based on the source sequence type is no more predictable: 
```
if (!e.MoveNext())
{
  if (default(TSource) is null)
  {
    return default;
  }
  else
  {
    ThrowHelper.ThrowNoElementsException();
  }
}
```
It is typical for the keys of a collection (Dictionary, HashSet, etc.) to be required to not be null, but never before were null elements discriminated in Enumerable extensions like this. How do I distinguish between 
```
new string[]{}
```
and 
```
new string[]{null}
```
using these methods? Did these ifs get in because the *OrDefault versions did not get implemented and this is the compomise? I do not think this is convenient or expected at all. What are users supposed to do in their generic methods that call MinBy, replicate this logic (checking `default(TSource)`) every single time to work around this behavior?

### Reproduction Steps

Call Enumerable.MinBy on a reference type, e.g.:
```
new string[] {}.MinBy(x=>x)
```

### Expected behavior

a `new InvalidOperationException(SR.NoElements)` is thrown like for every other method that expects at least a single element, e.g. Single, Min, Max, First.

### Actual behavior

null is returned

### Regression?

Not a regression

### Known Workarounds

Fuff about with ifs (which is not the intended idea of LINQ one would think) or write own extensions methods (which is more difficult now because the problematic framework ones took away the reasonable name). MoreLinq works around this problem by returning an enumerable from Min/MaxBy, which i think is an entirely reasonable approach.

### Configuration

.NET SDK 6.0.100

**Comment by eiriktsarpalis** [comment]
> a new InvalidOperationException(SR.NoElements) is thrown like for every other method that expects at least a single element, e.g. Single, Min, Max, First.

The current behavior replicates the semantics found in the `Min` and `Max` methods, i.e. it is impossible to distinguish between `new string[] { }.Max()` and `new string[] { null }.Max()` without introducing side-effects. I'm not necessarily a fan of `null` being returned for reference types, but changing it now would be breaking change.

**Comment by instantsc** [comment]
Oh, indeed it does. For some reason I didn't see the difference in handling reference/value types there. I guess it wouldn't make sense to change, then.
