### ISSUE TITLE
StressLogAnalyzer is failing to build

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#62664]
```
  [ 98%] Built target runtimeinfo
  [100%] Built target singlefilehost
  Killed
  make[2]: *** [tools/StressLogAnalyzer/CMakeFiles/StressLogAnalyzer.dir/build.make:89: tools/StressLogAnalyzer/CMakeFiles/StressLogAnalyzer.dir/StressLogPlugin.cpp.o] Error 137
  make[1]: *** [CMakeFiles/Makefile2:5167: tools/StressLogAnalyzer/CMakeFiles/StressLogAnalyzer.dir/all] Error 2
  make: *** [Makefile:130: all] Error 2
  ~/github/wfurt-runtime/src/coreclr
  Failed to build "CoreCLR component".
/home/furt/github/wfurt-runtime/src/coreclr/runtime.proj(59,5): error MSB3073: The command ""/home/furt/github/wfurt-runtime/src/coreclr/build-runtime.sh" -x64 -release -os Linux -pgodatapath "/home/furt/.nuget/packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.21577.2"" exited with code 2.

```
I just sync main and my build suddenly start failing. Turns out that 4G VM is no longer good enough to build. So I added 2G more and it still fails when clang reaches 5.5G. I can probably keeping more ram but the spike in needed is very large. If I need to do that on every VM I have that would generally kill my dev machine. 

I'm wondering if there is anything we can do
cc: @am11 @jkotas @janvorli and @cshung who recently touched this ara.

**Comment by janvorli** [comment]
@wfurt do you have swap file enabled on your distro in the VM?

**Comment by am11** [comment]
@wfurt, I have also noticed this with clang 13, 10 and 6 on different build machines. I switch to `build.sh -gcc` to fix the problem. By the way, it _always_ fails on StressLogPlugin.cpp, There is something unique about that particular file which makes clang to kill the process. i.e. something we can probably fix. Need to investigate.

**Comment by cshung** [comment]
> I wonder if there is anything we can do

StressLogAnalyzer is meant to be a debugging tool only. If it is necessary, we can take it off the build.
When I merged though, the build was fine for the whole CI matrix, so not sure what is wrong there.

> 4G VM is not enough

It shouldn't take that much memory to compile that executable. Excluding its dependencies (i.e. the PAL), the executable has just a few source files with an overall less than 10K lines.

The log looks somewhat familiar:

```
  Killed
  ...
  make[1]: *** [CMakeFiles/Makefile2:5167: tools/StressLogAnalyzer/CMakeFiles/StressLogAnalyzer.dir/all] Error 2
  make: *** [Makefile:130: all] Error 2
```

I observe the same thing with Alpine Linux compiling the StressLogAnalyzer. I thought it was Alpine specific and therefore I intentionally excluded Alpine from the build and think it is some Alpine specific stuff. Given the observation from @am11, it could be the clang version that is causing the issue.

**Comment by am11** [comment]
To quickly repro, clone and run `./build.sh clr -c Debug` in GitHub Actions, AppVeyor or similar CIaaS environments with relatively less free RAM and/or cores available to the worker (both using Ubuntu, and both will fail building StressLogPlugin.cpp object file). This is a clang-only bug and can be workedaround by appending `-gcc` to the build command in such environments.

**Comment by tmds** [comment]
I just hit this too. All RAM on my laptop (24G) gets used and then it breaks down.

Do we know what commit started the build failure?

**Comment by am11** [comment]
https://github.com/dotnet/runtime/pull/61123  added analyzer to the build, we can disable this feature with this patch #62675.

**Comment by am11** [comment]
@wfurt, @tmds, FYI - we have repurposed PR #62675 as the the origin of crash in our code and workaround has been found. Large array instantiation and assignment directly to a static variable breaks something in clang.
