### ISSUE TITLE
Issues with the Crc32 intrinsic in the Jit

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#62692]
1\): The assert [here](https://github.com/dotnet/runtime/blob/cf75830ce2ecd5efafbf39c5de319b2841d8666c/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1724) is wrong because it does not account for small types. Reproduction:
```cs
static uint Problem(byte* pSrc, uint data)
{
    return Sse42.Crc32(*pSrc, data);
}
```
2\) The same assert is also wrong because [in lowering](https://github.com/dotnet/runtime/blob/cf75830ce2ecd5efafbf39c5de319b2841d8666c/src/coreclr/jit/lowerxarch.cpp#L1051-L1062) we purposefully remove narrowing `long` -> `int` casts to avoid generating redundant `mov`s. Reproduction:
```cs
static uint Problem(uint crc, ulong data)
{
    return Sse42.Crc32(crc, (uint)(data >> 16));
}
```
3\) The code in lowering is wrong because it can discard meaningful casts. Reproduction (`data` here will not be zero-extended):
```cs
static uint Problem(uint crc, uint data)
{
    return Sse42.Crc32(crc, (uint)(byte)data);
}
```
4\) The code in lowering is also wrong because it can discard `long` -> `int` casts on x86, and end up with a `GT_LONG` operand, which is not handled downstream. Reproduction, run on x86:
```cs
[MethodImpl(MethodImplOptions.NoOptimization)]
static uint Problem(uint crc, ulong data)
{
    return Sse42.Crc32(crc, (uint)(data >> 16));
}
```
5\) The code in lowering is also wrong because it can discard `double/float -> int` casts. Applies to all use sites of `TryRemoveCastIfPresent`. Reproduction:
```cs
static uint Problem(uint crc, double data)
{
    return Sse42.Crc32(crc, (uint)data);
}
```
Curiously enough, if we disable asserts, this will happily emit `crc32    eax, xmm1`.

6\) The code in lowering is also wrong because it can discard checked casts. Applies to all use sites of `TryRemoveCastIfPresent`. Reproduction (observe the generated code will have no check):
```cs
static uint Problem(uint crc, int data)
{
    return Sse42.Crc32(crc, checked((uint)data));
}
```

**Comment by EgorBo** [comment]
The LSRA assert is the 4th case?

**Comment by SingleAccretion** [comment]
Yep.

**Comment by deeprobin** [comment]
@EgorBo Do you know approximately when you're going to get around to looking at this issue?

It's probably nothing big, but the issue is blocking me (but nothing critical) :)

**Comment by EgorBo** [comment]
Looking at now, sorry for the delay

**Comment by deeprobin** [comment]
> Looking at it now, sorry for the delay

no problem. thanks
