### ISSUE TITLE
 sslStream.AuthenticateAsServer does not send the root certificate during TLS handshake

### ISSUE THREAD

**Issue by Linshiqi** [dotnet/runtime#62699]
### Description

I use SslStream.AuthenticateAsServer to test connection with thunderbird client,   i found thunderbird has to have full certificate chain( root certificate -> intermedia certificate -> server certificate) to finish tls handshake, but SslStream only sent two lower certificate, for this reason, the tls handshake failed.

### Reproduction Steps

1. Run SslStream as server

```c#
SslProtocols sslProtocols = SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12 | SslProtocols.Tls13;

SslServerAuthenticationOptions sslServerAuthenticationOptions = new SslServerAuthenticationOptions();

List<System.Security.Cryptography.X509Certificates.X509Certificate2> certChain = CreateChain(m_serverCertificate);

X509Certificate2Collection chain = new X509Certificate2Collection(certChain.ToArray());

sslServerAuthenticationOptions.ServerCertificateContext = SslStreamCertificateContext.Create(m_serverCertificate, chain, true);

sslStream.AuthenticateAsServer(sslServerAuthenticationOptions);
```
2. Run Thunderbird 91.4.0 
![图片](https://user-images.githubusercontent.com/20238043/145742613-e9a867a0-4799-489e-a9ce-a632b2597c7a.png)

3. Run wireshark
![图片](https://user-images.githubusercontent.com/20238043/145742819-875d3f9a-75cb-49bd-bd36-d95d3b400a5b.png)

### Expected behavior

It should send full certificate chain like below image:

![图片](https://user-images.githubusercontent.com/20238043/145742869-61e96232-f15c-433e-ad4f-5089ecd4af58.png)

### Actual behavior

SslStream only send intermediate root and server certificate, not include top root certificate

![图片](https://user-images.githubusercontent.com/20238043/145742819-875d3f9a-75cb-49bd-bd36-d95d3b400a5b.png)

### Regression?

I test .net 5.0 which also not send top root certificate

### Known Workarounds

Up until now, I haven't found a workarouds, please help.

### Configuration

.Net version: .net6.0, .net5.0
windows version: windows 10 x64

### Other information

My top root certificate is not self signed, top root certificate and intermediate root certificate both installed on windows

**Comment by wfurt** [comment]
Root CA should not be sent per TLS RFC. For secure handshake to work the client _needs_ trust the ROOT (or some intermediate CA)

**Comment by Linshiqi** [comment]
> Root CA should not be sent per TLS RFC. For secure handshake to work the client _needs_ trust the ROOT (or some intermediate CA)

Ok, Is there a workaroud to get thunderbird to connect with Sslstream server? Maybe i should ask for help in the thunderbird forum.

**Comment by wfurt** [comment]
That may be best. When CA is not trusted (or chain missing something) most browsers provide option to use to override it. I don't know how that works with Thunderbird. If you can control the clients, you can add the root CA to certificate store.

**Comment by karelz** [comment]
Triage: Looks like problem outside of .NET. The behavior is by design and correct. Closing.
