### ISSUE TITLE
DllImportGenerator should error if attribute is applied to an extern

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#62700]
Bug #62616 was caused by applying `[GeneratedDllImport]` to an `extern` rather than `partial` method. The compilation succeeded, but the analyzer ignored it, and there was a failure at runtime.

1. The generator should error if it is applied to any method declaration that does not lead the generator to actually run.
2. Optionally, I suggest trimming `(no RVA).` from this message:
`IDS_CLASSLOAD_MISSINGMETHODRVA          "Could not load type '%1' from assembly '%2' because the method '%3' has no implementation (no RVA)."`

because it's what you see in this case, and it seems a rather technical distraction - not sure how relative virtual address is helpful here, the essential fact is that the implementation is missing.

**Comment by am11** [comment]
I think https://github.com/dotnet/runtime/issues/62291 is tracking it.

**Comment by danmoseley** [comment]
That seems different, it concerns the emitted code. This is about an error while enumerating the attributes

**Comment by elinor-fung** [comment]
We have an analyzer that should be warning when the attribute is used on a method without `partial`:
https://github.com/dotnet/runtime/blob/55fecfbc201dc789d71c0903e04f2a779212c671/src/libraries/System.Runtime.InteropServices/gen/DllImportGenerator/Analyzers/GeneratedDllImportAnalyzer.cs#L82-L83

We'll have to check why that didn't seem to do its job in this case.

That analyzer only looks for `static` and `partial` right now, so it should also be updated to handle other cases where the generator wouldn't run (for example, if the method already has a body).

**Comment by danmoseley** [comment]
Will this analyzer always run when the generator is used? A rule like this should always fire.

**Comment by elinor-fung** [comment]
Yeah, it should always run when the generator is used. It lives in the same assembly as the generator, so the analyzer reference to that assembly should pull in both the generator and analyzer.

**Comment by elinor-fung** [comment]
Ah, it is possible to use the generator, but disable all analyzers by setting `RunAnalyzers=false`, which was the case for the project - `System.ServiceProcess.ServiceController.TestService.csproj` - that had this issue.

**Comment by danmoseley** [comment]
Perhaps some of these basic cases can be error cases in the generator.
