### ISSUE TITLE
Discussion: A way to prevent `Process` from configuring the terminal

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#62707]
I'm filing this as a blank issue rather than an API proposal as I don't yet know how an API for this might look (or if the team is even willing to support it).

In my [System.Terminal project](https://github.com/alexrp/system-terminal) I would like to [ban](https://github.com/alexrp/system-terminal/blob/master/src/core/buildTransitive/BannedSymbols.txt) `System.Diagnostics.Process` and provide a wrapper which ensures that System.Native doesn't step on my library's toes too much.

Unfortunately, while I can cancel terminal configuration changes done as a result of `SIGCHLD` (via `PosixSignalRegistration`), there is currently no way for me to block the changes that are done when a `Process` starts (or fails to start). I would like for there to be some kind of API to achieve this. I don't know exactly what shape it ought to take though.

My immediate thought was a `bool ProcessStartInfo.ConfigureConsole` property, but that doesn't seem to fit very well with how terminal configuration is restored once there are no more child processes. It's probably not obvious to a user that not only should they disable this property, they should also cancel the runtime's default `SIGCHLD` handling with `PosixSignalRegistration`.

Perhaps something like:

```csharp
public class Process
{
    public static event Action<bool>? ConfigureConsole;
}
```

If the event is non-null, the framework code would assume that at least one of the handlers is going to take care of configuring the console, so the framework doesn't do it. The `bool` parameter would indicate whether the configuration is being done because child processes are starting or because there are no more child processes left. The upside of this approach is that there would be no need to cancel `SIGCHLD` handling.

**Comment by tmds** [comment]
@alexrp with .NET 6, when the app doesn't use `Console`, does `Process` cause the terminal to change?

**Comment by alexrp** [comment]
@tmds

> with .NET 6, when the app doesn't use `Console`, does `Process` cause the terminal to change?

I see that there is code in System.Native to prevent it:

https://github.com/dotnet/runtime/blob/a7ae08b33c48f99ea33dd500cf5f246f8db22a53/src/native/libs/System.Native/pal_console.c#L237-L270

I think the reason it doesn't help in my case is that I *intentionally* make `System.Console` configure the terminal at startup and *then* overwrite with my own configuration. [See this code](https://github.com/alexrp/system-terminal/blob/2d9bc2a40a49a74d780d103840989ba4ce202411/src/core/Drivers/TerminalDriver.cs#L93-L107), in particular the comments. My thinking was to try to limit the damage if a user accidentally uses `System.Console` at some point. But given that this is getting in the way of handling child processes properly, I would probably just do away with that bit of code and hope that analyzer errors will be enough.

(By the way, shouldn't that `WriteKeypadXmit` call be guarded by `g_terminalConfigured` too? That looks like a bug to me.)

That said, having looked at more of the `Process` internals to see where `ConfigureTerminalForChildProcesses` is called, I'm leaning towards still wanting something along the lines of the event I mentioned above. The code in `ProcessWaitState` in particular is quite complex and I'm not enjoying the thought of having to reimplement all the logic there without even having access to `Process` internals.

https://github.com/dotnet/runtime/blob/a25bece2b1916745eb9774e99d2511f08072fe8e/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessWaitState.Unix.cs#L596

**Comment by tmds** [comment]
> I think the reason it doesn't help in my case is that I intentionally make System.Console configure the terminal at startup and then overwrite with my own configuration. See this code

Are you sure it doesn't help? Have you tried?

> (By the way, shouldn't that WriteKeypadXmit call be guarded by g_terminalConfigured too? That looks like a bug to me.)

You can opt-out this by canceling `SIGCONT`. See https://github.com/dotnet/runtime/pull/54136#issuecomment-863881308.

**Comment by alexrp** [comment]
> Are you sure it doesn't help? Have you tried?

I did try, but upon a second inspection, it turns out my logging of `termios` state was happening at the wrong time, so I was seeing different values (but for good, unrelated reasons). After fixing the logging, I now see

```
Entering raw mode...
termios before launching child process:
  VTIME: 0
  VMIN: 1
  c_iflag: 0x4000
  c_oflag: 0x0
  c_cflag: 0xbf
  c_lflag: 0x0
Launching 'echo'...
'echo' exited with code '0'.
termios after child process exited:
  VTIME: 0
  VMIN: 1
  c_iflag: 0x4000
  c_oflag: 0x0
  c_cflag: 0xbf
  c_lflag: 0x0
```

which is good in the sense that it's the result I want, but 'bad' in that I have no idea why it works. 😅

Maybe the PAL code has just gotten too complex for me to wrap my head around without stepping through in a debugger, but I can't for the life of me make sense of why `termios` isn't being changed when the child process is launched/exited. As far as I can tell, the PAL code should be overwriting `termios` when I start a non-redirected `Process`...

> You can opt-out this by canceling `SIGCONT`. See [#54136 (comment)](https://github.com/dotnet/runtime/pull/54136#issuecomment-863881308).

I'm not quite following how `SIGCONT` relates to the `WriteKeypadXmit` call in `SystemNative_ConfigureTerminalForChildProcess`.

**Comment by tmds** [comment]
> which is good in the sense that it's the result I want, but 'bad' in that I have no idea why it works.

It only configures the terminal on specific `Console` usage (mostly reading). Your code doesn't trigger the configuration.

> I'm not quite following how SIGCONT relates to the WriteKeypadXmit call in SystemNative_ConfigureTerminalForChildProcess.

I answered the wrong question: `SIGCONT` is to avoid changing the terminal in `ReinitializeTerminal`.

How does the application mode (from `WriteKeypadXmit`) affect your library?

**Comment by alexrp** [comment]
Given what we've discussed here, I'll try my hand at implementing a `Process` wrapper to see how much effort it takes to correctly do the terminal configuration changes on launch/exit and report back. If it's not too much work, then there might not be a need for an API change after all.

Thanks for the help, @tmds. 👍

**Comment by alexrp** [comment]
f1ecd0d47ad9fb769de5079bbcbde55117ab3647

Not as hard as I anticipated - especially since I decided to only allow spawning child processes that use the terminal in cooked mode.

I'm relying on `Process.Exited` to do terminal cleanup. I don't know if there are any corner cases that could be missed by this though.

**Comment by tmds** [comment]
From a use-case perspective, users should either start a child process which controls the terminal, and wait for it. Or they should start a process that doesn't use the terminal (all streams redirected) which can run in the background. Your APIs may want to facilitate these two cases.

> I don't know if there are any corner cases that could be missed by this though.

There is nothing I can think of.
