### ISSUE TITLE
Handling certain special signals properly is impossible with `PosixSignalRegistration`

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#62706]
I ran into some issues with `PosixSignalRegistration` while working on my [System.Terminal project](https://github.com/alexrp/system-terminal). There might not be much that can be done about these issues, but I thought I should at least file them in case anyone else runs into them like me.

### Blocking/ignoring signals

`SIGTTIN` and `SIGTTOU` are kind of special in that blocking/ignoring them has different semantics than one might expect. For example, ordinarily, a background process calling `tcsetattr` will receive `SIGTTOU` which suspends the process - the idea being that it's kind of rude to change terminal configuration from the background since it could mess up the foreground process(es). The same goes for `read` on the controlling terminal which sends `SIGTTIN`. (`write` on the controlling terminal can also send `SIGTTOU` if the `TOSTOP` bit is set, but this is rarely the case by default.)

If a background process for some reason wants to be rude and perform these actions anyway, it may choose to block/ignore `SIGTTIN`/`SIGTTOU`. Not only will this result in the signals not being sent, it also allows the system calls to succeed. So blocking/ignoring the signals is meaningfully different from just installing an empty handler.

There is a sort of similar story for `SIGTSTP`. It's a suspend *request* unlike `SIGSTOP`, so blocking/ignoring it to avoid suspension is possible.

There is currently no way to achieve this with `PosixSignalRegistration`.

### Late signal handling

Signal handling with `PosixSignalRegistration` happens on a separate signal handler thread spawned in System.Native. This makes sense since running managed code in an actual signal handler function is a bad idea on quite a few levels. (This also means there may not be much that can be done for this issue.)

To handle certain signals properly, you *must* do your work in the native signal handler. To give a few examples:

* `SIGTSTP`: You can handle this signal if you need to do some work before the process is suspended (such as saving some state to disk). By the time this signal arrives to be handled in the signal handler thread, it's far too late - the process has already woken up from a `SIGCONT` signal that will be handled in the thread immediately after the `SIGTSTP` that's currently being handled.
* `SIGCONT`: One common use of this signal is to restore terminal configuration with `tcsetattr` since the program will likely (but not necessarily) have been put in the foreground (e.g. by typing `fg` in the shell). Unfortunately, due to the delayed handling on the signal handler thread, by the time `tcsetattr` is called in the managed handler, other parts of the program may already be using the terminal again, leading to unexpected behavior.
* `SIGWINCH`: I'm less confident on this one, but I know that some libraries in the wild restore terminal configuration on `SIGWINCH` like they do for `SIGCONT`. I haven't actually observed any situations where this was necessary, but if such situations indeed exist, the same issues described for `SIGCONT` apply here as well.

**Comment by stephentoub** [comment]
> This makes sense since running managed code in an actual signal handler function is a bad idea on quite a few levels. (This also means there may not be much that can be done for this issue.)

Yes.

**Comment by AaronRobinsonMSFT** [comment]
Closing this based on the general agreement there isn't much we can do at present.

@alexrp If you were to create PR for updating our documentation on the API regarding the above that would be welcome.
