### ISSUE TITLE
Regex source generator should include capture group name in comment

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#62715]
Given an expression like:
```C#
"^(?<LINE>[0-9]*)-(?<ENDLINE>[0-9]*)$"
```
the regex source generator will output comments for the groups like:
```C#
// 1st capturing group
```
We should include the name if one exists, e.g.
```C#
// 1st capturing group ("LINE")
```

**Comment by pedrobsaila** [comment]
I a made a PR #63255 for this issue
