### ISSUE TITLE
ILVerify.ILVerifyTypeSystemContext.VerifyModuleName throws NullReferenceException if missing DLL

### ISSUE THREAD

**Issue by carlos-quintero** [dotnet/runtime#62711]
### Description

When you run ilverify to verify a DLL that has dependencies, if some dependency dll is missing ilverify throws:

NullReferenceException at ILVerify.ILVerifyTypeSystemContext.VerifyModuleName(String simpleName, EcmaModule module)

instead of a more helpful exception (such as FileNotFound with the name of the missing file). 

That makes incredibly frustrating to verify DLLs with lots of dependencies in several folders (such as Visual Studio extensions) if you miss some folder.

### Reproduction Steps

- Using Visual Studio 2022 create a solution with two .NET 6.0 Class Library projects (ClassLibrary1 and ClassLibrary2), with ClassLibrary2 referencing ClassLibrary1.
- In the referenced library (ClassLibrary1), create a static class with a static method.
- In the referencing library (ClassLibrary2), create a class with a method that calls the method in the other library
- Build the solution
- Open a command prompt and change to the output folder of ClassLibrary2 (ClassLibrary2\bin\Debug\net6.0)
- Run the following command:

ilverify ClassLibrary2.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0\*.dll"

(notice that we have omitted -r ".\*.dll" so that ClassLibrary1.dll will not be found)

### Expected behavior

Something like:

"ClassLibrary1.dll not found"

### Actual behavior

Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at ILVerify.ILVerifyTypeSystemContext.VerifyModuleName(String simpleName, EcmaModule module)
  ...

### Configuration

.NET 6.0
Windows 10
AnyCPU

**Comment by carlos-quintero** [comment]
The root cause is that in the method ResolveAssemblyOrNetmodule, the call to VerifyModuleName(verificationName, module) is not protected by an "if" that avoids the call if module is null, and the VerifyModuleName method doesn't check the null either before calling module.MetadataReader.

Adding such null check is enough to get the helpful "Failed to load assembly 'ClassLibrary1'" message in the output:

[IL]: Error [FileLoadErrorGeneric]: [C:\Users\...\ClassLibrary2\bin\Debug\net6.0\ClassLibrary2.dll : ClassLibrary2.Class2::F2()] Failed to load assembly 'ClassLibrary1'

![NullReferenceException](https://user-images.githubusercontent.com/10756684/145801460-4a5bcfb5-5807-4f31-affb-f89f90e9033f.PNG)

**Comment by pedrobsaila** [comment]
I would like to work on this issue
