### ISSUE TITLE
[Windows x86 Release] DllImportGenerator.Tests crashes the runtime in InvokeManagedCallbackAfterGCCollect

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#62728]
OS: **Windows**
Architecture: **x86**
Configuration: **Release**

Example runs:
https://dev.azure.com/dnceng/public/_build/results?buildId=1509296&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d
https://dev.azure.com/dnceng/public/_build/results?buildId=1509712&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d

Stack trace:
<pre>
  Starting:    DllImportGenerator.Tests (parallel test collections = on, max threads = 2)
Fatal error. Internal CLR error. (0x80131506)
   at NativeExports.DelegatesAndFunctionPointers.InvokeManagedCallbackAfterGCCollect(Void*)
   at DllImportGenerator.IntegrationTests.NativeExportsNE+FunctionPointer.InvokeAfterGC(Void ())
   at DllImportGenerator.IntegrationTests.FunctionPointerTests.InvokedAfterGC()
</pre>

/cc @dotnet/jit-contrib, @janvorli, @jkoritzinsky, @krwq - I'm not sure whether this may be related to GC, calling conventions, stack unwinding or something completely different. I know we've recently seen a bunch of issues related to DllImportGenerator so I'm wondering whether it might be related to one of them.

**Comment by EgorBo** [comment]
Most likely the same as https://github.com/dotnet/runtime/issues/60624 that was just fixed in https://github.com/dotnet/runtime/pull/62709 (merged 2 hours ago)

**Comment by trylek** [comment]
Thanks Egor for your quick feedback, I was unsure whether they may be related as I was under the impression that the JIT assertion was previously only seen on **arm64** whereas the above are **x86** tests.

**Comment by EgorBo** [comment]
I am not sure it fixes this, but the JIT fix is not arch specific and fixes Invalid jit IR for all 32bit targets

**Comment by EgorBo** [comment]
Ah, you're right - the fix is 64bit related so I guess it's something else

**Comment by jkoritzinsky** [comment]
I think https://github.com/dotnet/runtime/pull/61075 has the fix for this issue

**Comment by jkotas** [comment]
Fixed by #63826
