### ISSUE TITLE
[System.Text.Json] Why is it calling my constructors and not simply instantiating memory?

### ISSUE THREAD

**Issue by jannickj** [dotnet/runtime#62734]
So I've read: https://github.com/dotnet/runtime/issues/54904, https://github.com/dotnet/runtime/pull/32213 and https://github.com/dotnet/docs/issues/20887

However I don't want my serializer to start randomly calling my constructors, I mean who knows will happen when those are called, instead I just want it to do the expected behavior of copying memory into the data object. I.e. my expectation is that it would call `FormatterServices.GetUninitializedObject` and initialize it with the deserialized data.

My expectation is that I would have the option of saying if want it to start calling my constructor.

So my question is: given that this is clearly not the behavior we see today have you guys made or have someone made a `NoJsonConstruct` flag that would allow me to attribute it my private constructor classes.

Thanks in advance :)

**Comment by layomia** [comment]
> However I don't want my serializer to start randomly calling my constructors, I mean who knows will happen when those are called, instead I just want it to do the expected behavior of copying memory into the data object. I.e. my expectation is that it would call FormatterServices.GetUninitializedObject and initialize it with the deserialized data.

System.Text.Json calls constructors in a deterministic and documented manner: https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-6-0#immutable-types-and-records. Can you share some concrete scenarios for not wanting your ctors called?

I haven't seen any precedent for using `FormatterServices.GetUninitializedObject` in other serializers in the framework, nor in `Newtonsoft.Json`. @GrabYourPitchforks do you know of any guidance for using this API?

**Comment by GrabYourPitchforks** [comment]
> I haven't seen any precedent for using FormatterServices.GetUninitializedObject in other serializers in the framework...

This is the `[Serializable]` \& `ISerializable` pattern and is used by serializers which support that pattern: `BinaryFormatter`, `DataContractSerializer`, etc. _System.Text.Json_ does not support that pattern. These patterns are considered legacy technology and the .NET libraries team is no longer investing in them beyond maintaining existing serializers which already use this pattern.

**Comment by jannickj** [comment]
Constructors is in general seen as a legacy pattern and the reason is that they only cover one exact case, 
* Object construction that cannot fail and always returns Exactly one of themselves. 

However if I need to do validation as part of object construction or if the object is returned in a container, there might be many reasons why the constructor doesn't creates exactly one. Thus a more consistent pattern is to have static `Create` functions or `Builders` that builds the object in a correct state, and then leave the constructor private.

Example:

```
public record HourMin
{
	public int Hour { get; private set; }
	public int Min { get; private set; }
	private HourMin() { }

	public static HourMin? Create(int hour, int min)
	{
		if (hour > 24 || hour < 0) return null;
		if (min > 60 || min < 0) return null;
		return new HourMin { Hour = hour, Min = min };
	}
}
```
This ensures that the object is only ever in a correct state, now when serializing/deserializing the object from app to app I don't need to validate the object again since I've already done that, or atleast if I want to validate it again then it should be a Serializer option.

Now I could leave the constructor public however that sort of defeats the purpose of having a Create Function and increases the likelihood for misuse.

> These patterns are considered legacy technology and the .NET libraries team is no longer investing in them beyond maintaining existing serializers which already use this pattern.

:thinking: , I strongly recommend that you guys reconsider them or rethinks them, for pure data object the correct behavior is to serialize the underlying data, and deserialize them back to their exact structural state.

**Comment by Clockwork-Muse** [comment]
There's nothing preventing you from putting the checks inside the constructor, and throwing an exception (usually something in the `ArgumentException` tree) if a constraint is violated.  That's exactly what's going to happen if you tried to deserialize a `TimeOnly` object, for example.  

Your other option is to define a custom converter function and register it with the serializer.

> Constructors is in general seen as a legacy pattern and the reason is that they only cover one exact case

You can have multiple constructors in the general case, although we may not support it for JSON deserialization.

> Now I could leave the constructor public however that sort of defeats the purpose of having a Create Function and increases the likelihood for misuse.

I'll tip you off to a secret; the reason there are constructors was because people got tired of having unassociated functions creating and initializing structs in C, and decided it was better to have them as part of the object.  For all intents and purposes, a constructor is a factory function, usually with some additional constraints defined by the language.

> I strongly recommend that you guys reconsider them or rethinks them, for pure data object the correct behavior is to serialize the underlying data, and deserialize them back to their exact structural state.

This has problems with runtime interop and binary compatibility.  One of the reasons `BinaryFormatter` is deprecated is security issues surrounding re-hydrating arbitrary objects in this manner.

**Comment by jannickj** [comment]
> There's nothing preventing you from putting the checks inside the constructor, and throwing an exception (usually something in the ArgumentException tree) if a constraint is violated. That's exactly what's going to happen if you tried to deserialize a TimeOnly object, for example.

While you are absolutely correct that is the only reasonable option if you enforce atleast 1 public constructor, though from a programming pattern perspective it's a really bad coding experience. And a lot of modern C# features revolve around data handling and not exception handling.

> I'll tip you off to a secret; the reason there are constructors was because people got tired of having unassociated functions creating and initializing structs in C, and decided it was better to have them as part of the object. For all intents and purposes, a constructor is a factory function, usually with some additional constraints defined by the language.

Yes that was one extreme, unassociated factory functions, vs associated exact constructor functions, the middle ground is associated factory functions, which is what I show-cased.

> One of the reasons BinaryFormatter is deprecated is security issues surrounding re-hydrating arbitrary objects in this manner.

That makes a lot of sense for a binary formatter, however again we're in this must be one of the extremes territory, I think Json which is a well-defined grammar could benefit from having direct serialization.

Anyways those are my two cents :coin: :coin:

**Comment by layomia** [comment]
Closing as the proposed pattern is considered legacy that we're not introducing into newer .NET technology. Another way to do validation on newly deserialized objects is using the [`IJsonOnDeserializing`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.ijsonondeserializing?view=net-6.0) and/or [`IJsonOnDeserialized`](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.ijsonondeserialized?view=net-6.0) interfaces and their relevant methods.
