### ISSUE TITLE
Each nativefilereference causes 512+mb to be allocated

### ISSUE THREAD

**Issue by danwalmsley** [dotnet/runtime#62736]
### Describe the bug
Any NativeFileReference added to the project allocated 512+mb per reference.

### To Reproduce

https://github.com/wieslawsoltes/BlazorNativeFileReferenceMemoryUsageRepro

https://wieslawsoltes.github.io/BlazorNativeFileReferenceMemoryUsageRepro/

simple repro with minimal blazor app.

Even with a simple .c file with 1 function in it, and even if the code is not called 512+mb mem.

Any libMyLib.a reference also causes it.

Just open the app, and open dev tools

goto memory and take a snapshot.

Remove the native references, and run again, take snapshot... memory back to normal.

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

## TODO
- [ ] always emit a message with the size, and reference the property to change the value.

**Comment by radical** [comment]
From https://github.com/emscripten-core/emscripten/blob/2.0.23/src/settings.js#L162-L170:
```js
// The initial amount of memory to use. Using more memory than this will
// cause us to expand the heap, which can be costly with typed arrays:
// we need to copy the old heap into a new one in that case.
// If ALLOW_MEMORY_GROWTH is set, this initial amount of memory can increase
// later; if not, then it is the final and total amount of memory.
//
// (This option was formerly called TOTAL_MEMORY.)
// [link]
var INITIAL_MEMORY = 16777216;
```

And we have `-s ALLOW_MEMORY_GROWTH=1` in the emcc flags, by default.

cc @kg, and @radekdoulik for any guidance on selecting that value.

**Comment by kg** [comment]
I think 512MB is probably a bad initial value since afaik the heap will never shrink. We should probably set it lower (say 128) and it will grow if it needs to, I think?

**Comment by radical** [comment]
It might be useful to always emit a message with the size, and referring to the property to change the value.
