### ISSUE TITLE
Is linear get/set access to elements of an array of arbitrary rank, possible?

### ISSUE THREAD

**Issue by Korporal** [dotnet/runtime#62733]
Although we can _enumerate_ a multi dimensional (non-jagged) array in a linear fashion via `IEnumerable` there's no way to iterate via an index so one can set element values despite the fact that `Array` implements `IList`.

If we cast an `Array` to `IList` and try to use the indexer we get a runtime exception "System.ArgumentException: 'Array was not a one-dimensional array.'".

This seems to be an inconsistency, it seems that the indexer should mirror `IEnumerable` and allow linear access that disregards the fact the array is multidimensional.

Not saying this is a bug (and there may be some other way to do it) but I could file an API suggestion if that is the way to progress this?

**Comment by CyrusNajmabadi** [comment]
If there's an API (safe, or otherwise) to get a ref to the first element in the multi-dimensional array, then this could trivially be exposed as an extension method that returns a Span.

**Comment by Korporal** [comment]
I can't understand why this was closed. If I do what you suggest:

```csharp
var array = Array.CreateInstance(typeof(int), 3, 4, 5, 6);

var span = MemoryMarshal.CreateSpan(ref array, array.Length);
```

I don't see how it helps me, perhaps I've misunderstood?

**Comment by CyrusNajmabadi** [comment]
You asked if it was possible to get linearized access to a multidimensional array. The above approach is how. 

If you have no knowledge of things like the underlying type of the array, then you'd have just write a helper extension that uses methods like GetLength and Get/SetValue to work with the array in a linearized fashion.

**Comment by Korporal** [comment]
> You asked if it was possible to get linearized access to a multidimensional array. The above approach is how.
> 
> If you have no knowledge of things like the underlying type of the array, then you'd have just write a helper extension that uses methods like GetLength and Get/SetValue to work with the array in a linearized fashion.

The title does say "...an array of arbitrary rank.." perhaps I didn't make that clear, I've elaborated this point in the OP now.

**Comment by CyrusNajmabadi** [comment]
Taken offline with @korporal in gitter thread here: https://gitter.im/dotnet/csharplang?at=61b7bb00c2cc0e5343fed4e5
