### ISSUE TITLE
Constructing MD arrays in R2R code does not work on OSX/ARM64

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#62747]
https://github.com/dotnet/runtime/pull/61938 exposed this issue. 

We had other issues that could cause related test scenario (`TestGenericMDArrayBehavior`) to never run in R2R mode on OSX.
 #61938 makes R2R enabled more reliably on OSX, but now we see the test failing, so I disabled the scenario as a part of #61938.

I beleive the root cause is variadic JIT helper - `HCIMPL2VA(Object*, JIT_NewMDArr, CORINFO_CLASS_HANDLE classHnd, unsigned dwNumArgs) `. 
It looks like OSX/ARM64 has special ABI for variadic calls, but we call it just as a cdecl with extra arguments. As a result the helper reads garbage and allocating MD arrays fails.

We do not use this helper in regular JIT code. There is a comment that it may be worth switching R2R to non-variadic helper as well since it would be more portable. Perhaps it is time?

**Comment by VSadov** [comment]
@dotnet/jit-contrib - is this a JIT issue?

**Comment by filipnavara** [comment]
For reference, the general marshalling of varargs is tracked in https://github.com/dotnet/runtime/issues/48796 with specific discussion about the macOS/iOS ABI situation.

**Comment by jkoritzinsky** [comment]
I think this is a JIT issue.

It looks like there's two JIT helpers for creating MDArrays. One that uses varargs and one that doesn't.

For some reason it looks like the one that doesn't use varargs is only used in non-R2R or CoreRT scenarios:

Usage of the non-varag helper:

https://github.com/dotnet/runtime/blob/4a4884099ae3fee758da34cc1f01531396f01753/src/coreclr/jit/importer.cpp#L7501

Condition for the block containing the non-vararg helper call setup:

https://github.com/dotnet/runtime/blob/4a4884099ae3fee758da34cc1f01531396f01753/src/coreclr/jit/importer.cpp#L7446

Usage of the vararg helper (in the else block for the above `if` condition):

https://github.com/dotnet/runtime/blob/4a4884099ae3fee758da34cc1f01531396f01753/src/coreclr/jit/importer.cpp#L7518

The comment above the `if` block already says that the vararg helper is deprecated and should be removed in the future and that all usages should use the non-vararg method, but the non-vararg variant is only used in CoreRT for now as it requires an R2R version bump. As we're already bumping the R2R version with https://github.com/dotnet/runtime/pull/61759, I think it would be okay to switch things over, but I'd want @jkotas to chime in here as well.

**Comment by VSadov** [comment]
_Especially_ if we are already bumping R2R version. 
Definitely a good time to get rid of a deprecated helper with poor portability.

**Comment by jkotas** [comment]
> Especially if we are already bumping R2R version.
> Definitely a good time to get rid of a deprecated helper with poor portability.

+100

**Comment by jkoritzinsky** [comment]
We're using a multidimensional array in ConsolePal.Unix.cs, so I think this is higher priority than we thought: 

https://github.com/dotnet/runtime/blob/fbabdb663cb7895e5e6002960be2fe560b957b2e/src/libraries/System.Console/src/System/ConsolePal.Unix.cs#L885


As a result, this is breaking all of the crossgen2 outerloop runs on macOS ARM64. I'll take a stab at fixing this to unblock the legs.
