### ISSUE TITLE
[test] Rename build.sh 'excludemonofailures' option to 'mono'

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#62745]
I make too many typos writing 'excludemonofailures'

Now that the `clr.hosts` subset can be built independently of the rest of CoreCLR, and the creation of `Core_Root` is done directly using the Mono and libraries artifacts, and the old hacky `Core_Root` patching step is gone, what we effectively have is an option to `./build.sh` to specify the runtime flavor. (related work: https://github.com/dotnet/runtime/issues/58266)

We can bikeshed the details, but it would be nice if this worked:

```
./build.sh generatelayoutonly release               # builds a Core_Root with a CoreCLR release build
# - or - 
./build.sh generatelayoutonly mono release    # builds a Core_Root with a Mono release build
```

The quickest fix is just to update  this line to also add `mono|-mono|...`, but maybe we want something else?

https://github.com/dotnet/runtime/blob/d8d80cd0d691b4fb1bd9e9a1519ff304cf33e1b5/src/tests/build.sh#L247

**Comment by steveisok** [comment]
If you specify `/p:RuntimeFlavor=mono`, what do you get?

**Comment by trylek** [comment]
That should be equivalent, the test build scripts <code>src/tests/build.cmd</code> and <code>src/tests/build.sh</code> are now just front-ends transforming command-line options into parameters for subsequent execution of <code>src/tests/build.proj</code>.

**Comment by trylek** [comment]
There currently exist 7 occurrences of <code>excludemonofailures</code> in the runtime repo and all should be trivial to fix:

https://github.com/dotnet/runtime/search?q=excludemonofailures

**Comment by trylek** [comment]
Long story short, to answer @lambdageek's initial question, as of today <code>excludemonofailures</code> is just chatty way of saying <code>mono</code> and simply renaming the seven occurrences accordingly should do the trick.

**Comment by trylek** [comment]
OK, I'm waiting for a build to finish, I'll make the PR.
