### ISSUE TITLE
System.Text.RegularExpressions work planned for .NET 7

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#62758]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

There are currently several efforts for fixing/improving our RegularExpressions engines. This includes test coverage efforts, perf-enhancing efforts, but a lot of new feature work as well. Even though we have individual issues for most of these efforts, this is meant to serve as an all-up tracking issue which shows all of these efforts and their category. Some issues could probably be placed in more than one category, but I tried to pick whichever category had the highest order bit for each. The list here will be updated with new work as it comes up, as well as with expected shipping milestones when we think some of them will land.

### Main Regex Investments

- [x] P0: [NonBacktracking] #57891
- [x] P0: [Source Generator] #44676
- [x] P0: [All Engines] #59629
- [x] P0: [All Engines] #61048
- [ ] P0: [All Engines] #59492
- [x] P1: [All Engines] #62449
- [x] P1: [All Engines] #65011
- [ ] P2: [Source Generator with NonBacktracking] #61903
- [x] P1: #68147

### API Proposals

- [x] P2: #62603
- [x] P2: #61425
- [ ] P2: #62573

### General Perf Improvements

- [x] P1: #62670
- [x] P1: #62676
- [x] P2: #62723
- [x] P2: #62669
- [x] P2: #62677
- [x] P2: #62445
- [x] P2: #62450
- [x] P2: #62459

### General Improvements

- [ ] P1: #62619
- [x] P2: #62651
- [x] P2: #62650
- [ ] P2: #60917
- [ ] P2: #48972
- [ ] P2: #58786

### Improve Test Coverage

- [ ] P1: #61893
- [ ] P2: #61896
- [ ] P2: #61895
- [ ] P2: #61894
- [x] P1: #60753
- [x] P1: #60697

### Non-Backtracking Engine Fixes and Improvements

- [x] P0: #61904
- [x] P0: #60918
- [x] P1: #60645
- [x] P1: #60623

### Source Generator Fixes and Style Improvements

- [x] P0: #59491
- [x] P1: #62647
- [x] P2: #62715
- [x] P2: #62657
- [x] P2: #61666
- [ ] P2: #62441
- [x] P2: #62438

### Performance Regressions That Need Fixing

- [x] P0: #61972

### Performance Investigations

- [x] P2: #62697
- [x] P2: #62451
- [ ] P2: #62447
- [ ] P2: #62443

cc: @stephentoub @danmoseley @olsaarik @veanes

**Comment by danmoseley** [comment]
thanks for pulling this together. 

A user story is essentially a significant unit of user visible value that can be completed independently. 

So this feels like it can probably actually be several issues each labeled with "user story" eg

* Predictable regular expression performance, using a non-backtracking engine
* Faster, no-JIT regular expressions, using a source generator
* Higher performance regular expression matching   // random perf stuff
* More robust regular expression engines    // for stuff like test coverage improvements, general fixes and robustness?

All the stories would ultimately be parented by a single Theme, not sure what that will be yet.

**Comment by stephentoub** [comment]
> I have a 1 million character regex which is a word list in different languages

Are you able to share your regex?  It'd be interesting to see.

**Comment by huan086** [comment]
> > I have a 1 million character regex which is a word list in different languages
> 
> Are you able to share your regex? It'd be interesting to see.

This regex labels each location name it finds with the [Geoname ID](geonames.org/). The interpreted regex typically runs within 5 seconds for a sentence to 60 seconds for paragraph of about 500 words.

Using a regex instead of a loop and IndexOf to take advantage of matching the longest name. E.g. finding the location "New York City" and "New York" will only match "New York City".

Cutting down the number of locations to 1/100 of the list below allows the RegexGenerator to run successfully, creating a source file that is 14MB

https://1drv.ms/t/s!AoUkMG56ao1eq_A4tUTHghOmnndp8A?e=zFPSgH

**Comment by huan086** [comment]
> How common is it for names of Geoname Id's to be substrings of other geoname Id's? I want to try to understand why you think Regex is the best solution to your problem.

You are right, turns out Regex isn't the correct solution. A loop on every location name, finding all positions of the location name in text repeatedly using IndexOf, and handling the few cases where locations are substrings of other locations by looking at the positions matched before, runs faster. The Aho–Corasick algorithm mention in https://stackoverflow.com/a/498349/263003 would be the optimization I could use.

Originally I thought finding a set of strings within an input text is most straightforward with a Regex.

Back to the original comment I made, it would be helpful to offer some advice when bad regex pattern creates OOM.

**Comment by joperezr** [comment]
> it would be helpful to offer some advice when bad regex pattern creates OOM.

That's good feedback, and we can think of something to solve that. I do think it is very rare to have 1 million character RegEx patterns, so I do think that OOM (at least in most of our engines) should be rare and more of an edge case. For .NET 7, we are introducing a new engine: The Non-Backtracking engine, which uses a DFA and NFA based algorithms underneath, which works mainly as a way to ensure linear processing times in terms of the input. This new engine does have a mechanism similar to what you suggest, and will in fact throw an exception when you call the constructor is your pattern is too large and could cause an OOM exception. We can probably think about sharing this concept of catching potential problematic patterns at construction time for the other engines. For more info on the new non-backtracking engine, and for knowledge on the rest of the improvements we've been working on for .NET 7, I would suggest checking out @stephentoub's [regex blog post](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/).

**Comment by jzabroski** [comment]
> The Aho–Corasick algorithm mention in https://stackoverflow.com/a/498349/263003 would be the optimization I could use.

This is actually mentioned above: https://github.com/dotnet/runtime/issues/62447

In general, it would be nice if Aho-Corasick itself were a utility class.  I had written a post somewhere on reddit on my experiments creating very fast needle in haystack string search using a parallel, C#-based, Aho-Corasick.  The actual use case was for something like this.  Except, I rather prefer an interface that models the data structure first, and therefore it built a Trie object, vs. generated a switch statement that sliced through the string as though it were a flattened trie. Having a Trie-centric approach would be more useful for things like IDEs where you'd want to be able to redo an algorithm after some inserts.

**Comment by stephentoub** [comment]
@joperezr, @jeffhandley, I've never been clear on the purpose of these epic issues.  Does this need to remain open?  As these are just links to other issues, they don't track anything themselves that isn't tracked elsewhere.

**Comment by joperezr** [comment]
Yes this can be closed. This was more for my personal tracking and planning, but I agree that the remaining work is tracked by individual issues so no point any longer on keeping this open.
