### ISSUE TITLE
win11-rids not present 

### ISSUE THREAD

**Issue by JensNordenbro** [dotnet/runtime#62755]
Cant find win11-* rids in https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json 

This is expected. (Or maybe it is not?)

**Comment by NikolaMilosavljevic** [comment]
[Triage] @danmoseley should this be in Libraries area? Setup does not maintain RIDs.

**Comment by AraHaan** [comment]
After thinking about it, I guess ``-win11`` can be an alias of ``-win10.0.22000.0``.

**Comment by ericstj** [comment]
Assigning to host -- does it make sense to change the host to identify Win11 differently and plumb this through the system?  cc @richlander 

Note this may be a breaking change.

**Comment by vitek-karas** [comment]
This has already been discussed in https://github.com/dotnet/runtime/issues/58125 and the PR https://github.com/dotnet/runtime/pull/58588. The short version is:
* Windows itself doesn't treat Windows 11 as a new version of the OS really from a programatical point of view. APIs still report version 10.... and so on.
* RIDs don't match OS names in lot of areas - for example all Windows Server OSes are treated as the client counterpart for RIDs (for win8, win10, ...)
* Introducing a new win11 would have non-trivial impact on lot of other things in the .NET product.

I understand that there would be some amount of user confusion, but the cost of doing this doesn't seem to match the benefits.

**Comment by AraHaan** [comment]
Perhaps the solution would be for the Windows team to have the apis report version 11 instead of 10.

**Comment by JensNordenbro** [comment]
Ohh.. now my world view is now up-side-down :) 

I have always assuemed it was connected to the OS-version. The server versions are just "brand names" . 

@vitek-karas ; 
1. Maybe I am reading it wrong but if what you say is the case, please explain why do we have "opensuse.13.2-x64,  opensuse.15.0-x64, opensuse-x64" . At least to me they resolve to the same and hence opensuse-x64 or even linux-x64 should suffice? 


Also 

2. Does this mean that in the future when there are new windows 11 api:s not present in windows 10; .net cannot provide two different packages for the different OS:s ; instead there would need to be conditions inside the code to use this or that code path ?

**Comment by vitek-karas** [comment]
I'm definitely no expert in the OS version targeting for .NET. I think the most relevant document about that is https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md.

I'll let @terrajobst explain the details.

For new APIs we typically recommend light-up behavior, where the app tests (at runtime) that a given functionality is available and calls the API only when available.

For Windows specifically this has been the behavior for a while. Win10 has 2 versions per year basically with potentially new APIs added in each such version. We only have one RID for it.

**Comment by vitek-karas** [comment]
Found some more details on OS version targeting for Windows.
As is usual for windows app, there are two versions which are important:
* The version of windows the app is compiled against (this determines the APIs it can call as those are provided in the interop assemblies from Windows) - the target version
* The minimum supported version the app is designed to run on - the minimum version of windows the app can run on - min platform version

For .NET projects these two versions are specified like this:
```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
  </PropertyGroup>
```

The target OS version is part of the `TargetFramework` (TFM). The minimum platform version is specified via the `TargetPlatformMinVersion` property.

**Comment by JensNordenbro** [comment]
Since the number is explained to be api version on Windows and not OS version I close with this comment. Rids for win11 will come when api level is increased. Thanks guys!
