### ISSUE TITLE
MemoryMappedFile always flushing on dispose - even if nothing was written?

### ISSUE THREAD

**Issue by SergioLuis** [dotnet/runtime#62768]
Hello,

In my organization, we use MemoryMappedFile extensively.
Because multiple processes might need to access the same MemoryMappedFile concurrently, whenever we need to read data, we:

1. Acquire a multi-process lock
2. **Open** the MemoryMappedFile
3. **Read** whatever we need from it, ranging from a few bytes to several megabytes at a time
4. **Close** the MemoryMappedFile
5. Release the multi-process lock

We have been experiencing performance issues on this system lately (it is worth noting it has worked OK for years now, but our application keeps growing in use).

When dumping thread stacks, we find quite often that our threads are running the following calls:

```
System.IO.MemoryMappedFiles!System.IO.MemoryMappedFiles.MemoryMappedView.Flush(unsigned int)
  System.IO.MemoryMappedFiles!System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.Dispose(bool)
  System.Private.CoreLib!System.IO.UnmanagedMemoryAccessor.Dispose()
  our_module!Datalayer.StandardPerfMemoryMappedFile.CloseFile()
  out_module!Datalayer.StandardPerfMemoryMappedFile.CloseAndReleaseLock()
```

When adding log in our module (`our_module!Datalayer.StandardPerfMemoryMappedFile.CloseFile()`) we find out that the call to `System.IO.UnmanagedMemoryAccessor.Dispose()` is slower than we thought - in the range of ~500ms each.

Given that we didn't perform any write on the MemoryMappedFile (only read), is it correct that the MemoryMappedView flushes on disposal?

Whilst we use this system extensively on all three main OSs (GNU/Linux, Windows, macOS) on **.NET 5**, we tested this more in-depth in GNU/Linux (**Ubuntu 18.04LTS**).

Does this issue ring any bells? When a call to the system needs to open several of these files in a row, the performance hit of these Flush calls severely impacts the overall call performance. It is worth noting again that these files are used by a multi-process system, so keeping the files opened and locked by a single process is not an option for us.

Thank you for your help!

**Comment by SergioLuis** [comment]
For reference, this is how we open the files:

```
return MemoryMappedFile.CreateFromFile(
    path, FileMode.Open, null, size, MemoryMappedFileAccess.ReadWrite);
```

We calculate the `size` beforehand, usually with `new FileInfo(path).Length`.

**Comment by adamsitnik** [comment]
Hi @SergioLuis !

I've taken a closer look at creating memory mapped files and optimized it by up to 40%: https://github.com/dotnet/runtime/pull/63754 and https://github.com/dotnet/runtime/pull/63790

When it comes to flushing, I was able to implement your suggestion but only for `MemoryMappedViewAccessor` and `MemoryMappedViewStream` that are opened for reading:

```cs
using (MemoryMappedFile mmfile = MemoryMappedFile.CreateFromFile(_file.Path, FileMode.Open, null, 0, MemoryMappedFileAccess.ReadWrite))
using (mmfile.CreateViewAccessor(capacity / 4, capacity / 2, MemoryMappedFileAccess.Read)) // using .Read here
{
}
```

So to take advantage of that you will need to specify `MemoryMappedFileAccess.Read` when creating accessor or stream.

Thanks!

**Comment by SergioLuis** [comment]
This is awesome, thank you so so much for your hard work. I'll tell the team ASAP as we use MemoryMappedFiles extensively - can't wait for this to hit a stable .NET Release!

**Comment by adamsitnik** [comment]
> This is awesome, thank you so so much for your hard work. I'll tell the team ASAP as we use MemoryMappedFiles extensively - can't wait for this to hit a stable .NET Release!

@SergioLuis I am very happy to hear that! BTW is there any chance you would be interested in contributing some `MemoryMappedFiles` benchmarks to our benchmark suite? The existing benchmarks (they can be found [here](https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.IO.MemoryMappedFiles/Perf.MemoryMappedFile.cs)) measure only the time it takes to open and close a memory mapped file. We have no benchmarks that perform some more work like reading and writing. I haven't used MMF myself in real-life applications so I am not the best candidate the write them. We are using these benchmarks to ensure that .NET is not regressing over time, so if you add some interesting scenario we won't regress it.

**Comment by SergioLuis** [comment]
We'll discuss allotting time to contribute to the `MemoryMappedFile` benchmarks next Monday, the topic is now on our agenda.

Thank you for your invitation - we know that everyone can contribute to .NET, but finding out that we can actually provide some valuable help is really encouraging!
