### ISSUE TITLE
createdump requires root user

### ISSUE THREAD

**Issue by dzrhythm** [dotnet/runtime#62781]
### Description

This [troubleshooting article](https://docs.microsoft.com/en-us/troubleshoot/aspnetcore/3-3-debuggers-collect-core-dumps#createdump) mentions that `createdump` can be run as a non-root user, but I have not been successful in doing so. I get the error:

`open(/proc/7/mem) FAILED 13 (Permission denied)`

I have not found any documentation stating that it requires a root user, only `SYS_PTRACE` capability.

### Reproduction Steps

1. Run dotnet as a non-root user in a Linux container in Kubernetes with the `SYS_PTRACE` capability added.
2. Use `kubectl exec` to get a shell into the container as the non-root user and try to run `createdump` on the dotnet process.

### Expected behavior

`createdump` can be run as a non-root user.

### Actual behavior

Fails with: `open(/proc/7/mem) FAILED 13 (Permission denied)`

### Known Workarounds

Run the container as `root` in Kubernetes.

### Configuration

* .NET Core 3.1 and .NET 6.0.
* `mcr.microsoft.com/dotnet/runtime:6.0` or `mcr.microsoft.com/dotnet/runtime:3.1` base image.

**Comment by tommcdon** [comment]
Thanks for the bug report.  Please see https://docs.microsoft.com/dotnet/core/diagnostics/debug-linux-dumps for more information on requirements for collecting dumps.  In short, as you have correctly identified, collecting dumps with createdump requires that it to be run with `sudo` or `su`. and that the `SYS_PTRACE` capability is enabled.  We have a backlog item to document createdump caveats in our other documentation here: https://github.com/dotnet/diagnostics/issues/2246.  I'll close this issue as the documentation issue is tracked on https://github.com/dotnet/diagnostics/issues/2246.
