### ISSUE TITLE
Different behavior of ECDsa.ExportParameters between .NET 4.8 and .NET [Core]

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#62813]
Based on [this unit test](https://github.com/dotnet/runtime/blob/6be1c8de1bc25ca5971303518f12921fc62d125f/src/libraries/System.Formats.Cbor/tests/Writer/CborWriterTests.cs#L355-L359).

```cs
using System;
using System.Security.Cryptography;

namespace Experiment
{
    public class Program
    {
        public static void Main(string[] args)
        {
            QuickTest();
        }

        public static void QuickTest()
        {
            string hexQx = "65eda5a12577c2bae829437fe338701a10aaa375e1bb5b5de108de439c08551d";
            string hexQy = "1e52ed75701163f7f9e40ddf9f341b3dc9ba860af7e0ca7ca7e9eecd0084d19c";

            var ecParameters = new ECParameters()
            {
                Curve = ECCurve.CreateFromFriendlyName("ECDSA_P256"),
                Q = new ECPoint() { X = StringToByteArray(hexQx), Y = StringToByteArray(hexQy) },
            };

            using (ECDsa ecDsa = ECDsa.Create(ecParameters))
            {
                ECParameters p = ecDsa.ExportParameters(includePrivateParameters: false);
                Console.WriteLine(p.Curve.Oid.Value ?? "null");
            }
        }
        
        // Helper
        public static byte[] StringToByteArray(string hex)
        {
            int NumberChars = hex.Length;
            byte[] bytes = new byte[NumberChars / 2];
            for (int i = 0; i < NumberChars; i += 2)
                bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
            return bytes;
        }
    }
}
```

Above console app prints `1.2.840.10045.3.1.7` in .NET 3.1/7, and prints `null` in .NET Framework 4.8.

This issue was found based on my recent efforts of adding netstandard2.0 support to `System.Formats.Cbor`.

**Comment by vcsjones** [comment]
Additioanlly, I think .NET Core / .NET's behavior is right. ECDSA_P256 is the Windows friendly name for 1.2.840.10045.3.1.7.

Is there a reason why populating the OID on the curve created from a friendly name is concerning?

**Comment by Jozkee** [comment]
> Is there a reason why populating the OID on the curve created from a friendly name is concerning?

Is just that a `Theory` fails in netstandard2.0 but based on your comments I think I can re-write this method
https://github.com/dotnet/runtime/blob/6be1c8de1bc25ca5971303518f12921fc62d125f/src/libraries/System.Formats.Cbor/tests/CoseKeyHelpers.cs#L93

to the following:
```cs
bool MatchesOid(ECCurve namedCurve) => curve.Oid.Value == namedCurve.Oid.Value || curve.Oid.FriendlyName == namedCurve.Oid.FriendlyName;
```

And it should be safe, right?

**Comment by vcsjones** [comment]
Ah. I see. It's unfortunate that .NET Framework does not populate the OID Value, only the FriendlyName.

Since it's test code, testing using the FriendlyName as a fallback for the OID value makes sense. Presumably you're adding a netframework configuration for the unit tests, you could also do a conditional:

```csharp
bool MatchesOid(ECCurve namedCurve)
{
#if NETFRAMEWORK
    // .NET Framework does not populate the OID value from ExportParameters. So
    // we will compare the curves based on the FriendlyName.
    return curve.Oid.Value is null && curve.Oid.FriendlyName == namedCurve.Oid.FriendlyName;
#else
    return curve.Oid.Value == namedCurve.Oid.Value;
#endif
}
```

I would only say though that it's still possible for the FriendlyNames to be different. `ECDSA_P256` is really `ECCurve.NamedCurves.nistP256`. But there the friendly name of the curve is "nistP256", not "ECDSA_P256". In the case of your test, even though the "input" curve friendly name is ECDSA_P256, the ExportParameters will probably populate the friendlyname as nistP256.

If all else fails, you can resolve the OID Value yourself in the test:

```csharp
bool MatchesOid(ECCurve namedCurve)
{
    Oid curveOid = curve.Oid.Value is null ?
        Oid.FromFriendlyName(curve.Oid.FriendlyName, OidGroup.PublicKeyAlgorithm) :
        curve.Oid;
    return curveOid.Value == namedCurve.Oid.Value;
}
```

**Comment by bartonjs** [comment]
.NET Framework has the less desirable behavior, so that's where we'd have to make the change.  But, since this almost certainly doesn't meet the .NET Framework servicing bar, I'm just going to close the issue (since it looks like it got successfully worked around).
