### ISSUE TITLE
Test failure MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim(throwOnDisposed: null)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62828]
Run: [runtime 20211214.76](https://dev.azure.com/dnceng/public/_build/results?buildId=1512867&view=ms.vss-test-web.build-test-results-tab&runId=43064268&resultId=148988&paneView=debug)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_release-OSX.1014.Amd64.Open

- MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim(throwOnDisposed: null)
- MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim(throwOnDisposed: \"false\")
- MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim(throwOnDisposed: \"true\")
```
**Error message:**
```
Assert.Equal() Failure
Expected: 6
Actual:   5


Stack trace
   at MonoTests.System.Runtime.Caching.MemoryCacheTest.Trim(String throwOnDisposed) in /_/src/libraries/System.Runtime.Caching/tests/System.Runtime.Caching/MemoryCacheTest.cs:line 1131
```

**Comment by HongGit** [comment]
@VincentBu does this issue still repro?

**Comment by VincentBu** [comment]
Hi @HongGit , If we run into the same problem in 7 days, we would leave a comment. According to the thread, the issue didn't occur recently. Feel free to close it. We will create new issue if we run into it again.
