### ISSUE TITLE
Documentation missing for CA1727 and CA1848 

### ISSUE THREAD

**Issue by flcdrg** [dotnet/runtime#62826]
The analyzer(s) for these refer to the following links which both return 404 not found:

- https://docs.microsoft.com/en-au/dotnet/fundamentals/code-analysis/quality-rules/ca1848
- https://docs.microsoft.com/en-au/dotnet/fundamentals/code-analysis/quality-rules/ca1727

**Comment by timheuer** [comment]
Tracked in https://github.com/dotnet/docs/issues/23900

**Comment by danmoseley** [comment]
@flcdrg I will close this as a duplicate of that. BTW, if you are interested I know they would be glad to have a PR.
