### ISSUE TITLE
.NET 6 Console App Error on Simple Http Request - 10053 An established connection was aborted...

### ISSUE THREAD

**Issue by djrpascu** [dotnet/runtime#62825]
### Description

I'm working on a simple .NET 6 console app that will make an HTTP request to GET data from an web API endpoint on corporate LAN. If I try to make the request, I get back an exception - 10053 - An established connection was aborted by the software in your host machine. I suspect the issue has to do with the console app not communicating with the company proxy correctly. When I run Fiddler, the call goes through successfully.

Any ideas on what I should be looking for or implementing to get the HTTP request to work in my console app?

### Configuration

VS 2022 17.0.2

### Regression?

Making a simple HTTP request to same web API works for a .NET Framework 4.8 console app.

**Comment by antonfirsov** [comment]
Can you try if the request works on .NET Core 3.1? If it does, try [disabling IPV6](https://devblogs.microsoft.com/dotnet/dotnet-6-networking-improvements/#an-option-to-globally-disable-ipv6).

**Comment by wfurt** [comment]
And you can also get packet capture with Wireshark @djrpascu.

**Comment by djrpascu** [comment]
@antonfirsov i don't have .NET Core 3.1 installed, but i went ahead and added a runtimeconfig.template.json file to the project with the following in it:

```
{
  "configProperties": {
    "System.Net.DisableIPv6": "true"
  }
}
```

and that seems to have worked! :)

@wfurt sorry, i don't have wireshark installed on my machine (company device). i probably need to get approval for that. in fiddler, i see this (though not sure if helpful):

```
This is a CONNECT tunnel, through which encrypted HTTPS traffic flows.
To view the encrypted sessions inside this tunnel, enable the Tools > Options > HTTPS > Decrypt HTTPS traffic option.

A SSLv3-compatible ServerHello handshake was found. Fiddler extracted the parameters below.

```

**Comment by antonfirsov** [comment]
@djrpascu I think your corporate network has issues handling IPv6 properly, probably because of some firewall configuration. I recommend to raise a ticket at your IT department, maybe they are willing to invest into a fix.

Note that disabling IPv6 is not necessary in production, if you plan to deploy the HttpClient code to a machine outside your corporate network.

**Comment by antonfirsov** [comment]
Closing the issue for now since the question is answered, feel to reopen if you have some follow-up questions!

**Comment by djrpascu** [comment]
> @djrpascu I think your corporate network has issues handling IPv6 properly, probably because of some firewall configuration. I recommend to raise a ticket at your IT department, maybe they are willing to invest into a fix.
> 
> Note that disabling IPv6 is not necessary in production, if you plan to deploy the HttpClient code to a machine outside your corporate network.

I will do that, thank you!
