### ISSUE TITLE
Add Repobeats Stats to README.md

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#62838]
See https://repobeats.axiom.co/

## Other projects that use this
* https://github.com/dotnet/maui#stats

**Comment by danmoseley** [comment]
Oh - interesting! @Redth I see you added this to dotnet/MAUI. Has it worked fine/been useful for you? 

I wonder if there's an easy way to see what it would display for this repo before actually adding to the readme.

cc @eiriktsarpalis @terrajobst

**Comment by danmoseley** [comment]
cc @captainsafia

**Comment by captainsafia** [comment]
> Oh - interesting! @Redth I see you added this to dotnet/MAUI. Has it worked fine/been useful for you?

Ditto this! I'd be interested in adding it if it is providing value to us/the community in some way? Maybe as an indicator of repo activity?

**Comment by jkotas** [comment]
We have been optimizing the repo README.md content for people visiting the repo for the first time. I do not think that these stats are relevant to the people visiting the repo for the first time, so they should not be in the repo README.md.

Who is the expected target audience for these stats? Also, similar stats are available in Insights github tab already.

**Comment by jeffhandley** [comment]
I echo the hesitation and questions from @jkotas. The stats are pretty, but we'd need to hear some compelling statements to indicate they'd help a lot of users/contributors. Even then, I'd be more inclined for it to be added to the CONTRIBUTING doc instead of the README.

I'm going to close this, but folks should feel free to comment if they'd see value in adding this to the repo.

**Comment by GSPP** [comment]
This could be used to create a leaderboard of top contributors. The leaderboard would clear every year. That way, each year would set off a new competition for who contributes the most. Seems like a nice way to motivate people and make their contributions more fun.

**Comment by jkotas** [comment]
Raw number of contributions is a vanity metric that is easy to game. For example, we have seen artificially split PRs from time to time that are submitted for the sole purpose of inflating ones github contribution stats.

https://github.com/dotnet/runtime/issues/38349 has more discussion motivating people by giving credits for their contributions. Our focus is on quality of contributions and being inclusive of all types of contributors.

**Comment by danmoseley** [comment]
I agree with the above but would be glad for anyones thoughts about how we can better offer meaningful recognition (and not just of experienced contributors). The issue linked might be a good place. Contributions to thanks.dot.net would be welcome also.
