### ISSUE TITLE
System.Runtime.Intrinsics.Arm.Sha256 APIs are unavailable on Apple Silicon

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#62832]
### Description

It appears that `System.Runtime.Intrinsics.Arm.Sha256.IsSupported` returns `false` on M1 Pro and, consequently, fails JIT when attempting to use the corresponding intrinsics.

Please let me know if you need any additional details. Unfortunately, I have no experience with C++ specifically but otherwise would be happy to investigate if you point me to the right direction where to look for the bits and pieces responsible for CPU feature detection on macOS.

### Reproduction Steps

Execute the following snippet:
```csharp
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

Console.WriteLine(
    $"{nameof(ArmBase)}:{ArmBase.IsSupported}, " +
    $"{nameof(ArmBase.Arm64)}:{ArmBase.Arm64.IsSupported}, " +
    $"{nameof(AdvSimd)}:{AdvSimd.IsSupported}, " +
    $"{nameof(Sha256)}:{Sha256.IsSupported}\n");

var msg0 = Vector128<uint>.Zero;
var msg1 = Vector128<uint>.Zero;

msg0 = Sha256.ScheduleUpdate0(msg0, msg1);
```

### Expected behavior

Output:
```
ArmBase:True, Arm64:True, AdvSimd:True, Sha256:True
```

### Actual behavior

Output:
```
ArmBase:True, Arm64:True, AdvSimd:True, Sha256:False

Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.Arm.Sha256.ScheduleUpdate0(Vector128`1 w0_3, Vector128`1 w4_7)
   at Program.<Main>$(String[] args) in /Users/____/Code/LOC/Sha256Repro/Program.cs:line 11
```

### Configuration

NB: Reproducible with both 6.0.100 and 6.0.101
`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc
```

`sysctl -a | grep hw.optional`:
```
hw.optional.arm.FEAT_AES: 1
hw.optional.arm.FEAT_BF16: 0
hw.optional.arm.FEAT_BTI: 0
hw.optional.arm.FEAT_CSV2: 1
hw.optional.arm.FEAT_CSV3: 1
hw.optional.arm.FEAT_DPB: 1
hw.optional.arm.FEAT_DPB2: 1
hw.optional.arm.FEAT_DotProd: 1
hw.optional.arm.FEAT_ECV: 1
hw.optional.arm.FEAT_FCMA: 1
hw.optional.arm.FEAT_FHM: 1
hw.optional.arm.FEAT_FP16: 1
hw.optional.arm.FEAT_FPAC: 0
hw.optional.arm.FEAT_FRINTTS: 1
hw.optional.arm.FEAT_FlagM: 1
hw.optional.arm.FEAT_FlagM2: 1
hw.optional.arm.FEAT_I8MM: 0
hw.optional.arm.FEAT_JSCVT: 1
hw.optional.arm.FEAT_LRCPC: 1
hw.optional.arm.FEAT_LRCPC2: 1
hw.optional.arm.FEAT_LSE: 1
hw.optional.arm.FEAT_LSE2: 1
hw.optional.arm.FEAT_PAuth: 1
hw.optional.arm.FEAT_PAuth2: 0
hw.optional.arm.FEAT_PMULL: 1
hw.optional.arm.FEAT_RDM: 1
hw.optional.arm.FEAT_SB: 1
hw.optional.arm.FEAT_SHA1: 1
hw.optional.arm.FEAT_SHA256: 1
hw.optional.arm.FEAT_SHA3: 1
hw.optional.arm.FEAT_SHA512: 1
hw.optional.arm.FEAT_SPECRES: 0
hw.optional.arm.FEAT_SSBS: 1
hw.optional.AdvSIMD: 1
hw.optional.AdvSIMD_HPFPCvt: 1
hw.optional.arm64: 1
hw.optional.armv8_1_atomics: 1
hw.optional.armv8_2_fhm: 1
hw.optional.armv8_2_sha3: 1
hw.optional.armv8_2_sha512: 1
hw.optional.armv8_3_compnum: 1
hw.optional.armv8_crc32: 1
hw.optional.armv8_gpi: 1
hw.optional.breakpoint: 6
hw.optional.floatingpoint: 1
hw.optional.neon: 1
hw.optional.neon_fp16: 1
hw.optional.neon_hpfp: 1
hw.optional.ucnormal_mem: 1
hw.optional.watchpoint: 4
```

**Comment by EgorBo** [comment]
Looks like some ISA checks are missed here https://github.com/dotnet/runtime/blob/main/src/coreclr/pal/src/misc/jitsupport.cpp#L263 I'll take a look on my m1

**Comment by EgorBo** [comment]
So from my understanding `getauxval` is not available on macOS so we can just safely assume it's __APPLE__ and __ARM64__ then all basic instruction sets are enabled?

Not sure about RDM and DP

**Comment by EgorBo** [comment]
I assume we need to check these:
```
hw.optional.arm.FEAT_AES
hw.optional.arm.FEAT_DotProd
hw.optional.arm.FEAT_RDM
hw.optional.arm.FEAT_SHA256
```
the only small problem that macOS 11.x on M1 doesn't report these, they were added in macOS 12.0 but I guess it's ok.

**Comment by neon-sunset** [comment]
On one hand we can't just assume SHA256 is supported because according to https://developer.arm.com/documentation/ddi0487/gb/ page 278 the cryptographic extensions instruction set is optional.

On the other, all `osx-arm64` targets support SHA256 and other bits so I think we can safely assume a specific minimum supported feature set on `darwin`.

You can see the same assumptions made in various codebases:
- Putty: https://git.tartarus.org/?p=simon/putty.git;a=blob_plain;f=unix/utils/arm_arch_queries.c;hb=HEAD
- Golang: https://go-review.googlesource.com/c/go/+/271986/2/src/internal/cpu/cpu_arm64.go

p.s.: yes, `getauxval` is unavailable on macOS.

**Comment by EgorBo** [comment]
@neon-sunset are you interested in contributing it?

**Comment by neon-sunset** [comment]
That would be awesome. Will probably get this fixed over the upcoming weekend 😀

**Comment by neon-sunset** [comment]
Change submitted in https://github.com/dotnet/runtime/pull/62958

Despite flag detection now performing as expected, I think this is a somewhat fragile approach and a better option would be to implement it directly in `coreclr` via reading AT_HWCAP and other registers data and moving away from `sysctlbyname` or `getauxval` env dependencies completely. I'm currently looking into this but would prefer submitting it in the future as a separate change if you agree on going forward with it.

CC: @EgorBo
