### ISSUE TITLE
[API Proposal]: Low-level runtime shutdown event for critical cleanup

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#62834]
### Background and motivation

There is currently no good way to perform critical cleanup on runtime shutdown. The `ProcessExit` and `UnhandledException` events on `AppDomain` are inadequate (as explained below).

I think the solution is for there to be an event that is invoked on shutdown (regardless of the cause) and which is specifically advertised as being for *very* low-level cleanup. 99% of people who want to run code at shutdown should *not* be using this event. The expectation should be that, by the time this event is running, most library functionality is no longer usable.

I need this functionality in [Cathode](https://github.com/vezel-dev/cathode) to restore terminal settings on runtime shutdown. This is *very* important because exiting the program without properly restoring terminal settings could leave the terminal inoperable, which is annoying at best and could cause actual damage at worst (depending on what the user is doing and what the program's purpose is).

### API Proposal

```csharp
namespace System.Runtime
{
    public static class RuntimeLifetime
    {
        public static event Action<Exception?> CriticalCleanup;
    }
}
```

Note: The event should *not* be expected to fire in edge cases such as `SIGSEGV` in native code, `Environment.FailFast`, Win32 `TerminateProcess`, etc.

### API Usage

In Cathode, I would set up a handler in [`TerminalDriver`](https://github.com/alexrp/system-terminal/blob/0ae9dfe36a9c3143613170125e15e89942110e5b/src/core/Drivers/TerminalDriver.cs) like so:

```csharp
protected TerminalDriver()
{
    // RestoreSettings() restores `termios` state on Unix and console mode on Windows.
    RuntimeLifetime.CriticalCleanup += _ => RestoreSettings();
}
```

### Alternative Designs

It is possible to subscribe to `AppDomain.ProcessExit` but this event will *not* fire in the case of an unhandled exception being the reason for runtime shutdown. You might then think to subscribe to `AppDomain.UnhandledException` as well, but this has the *major* downside that it runs *before* any `finally` blocks on the call stack. So if you use this event to clean up some core resource and those `finally` blocks end up directly or indirectly using it, you're out of luck. You could call `Environment.Exit()` from your `UnhandledException` handler to mitigate that risk but then `finally` blocks just won't run at all, which is also pretty bad.

### Risks

* People may misuse the new event when they really should be reaching for the existing ones (`ProcessExit`, `UnhandledException`). I think the name will steer most people away from it, but proper documentation and possibly even an analyzer discouraging its use by default would, I think, mitigate this risk entirely.
* This new event would not fire in abnormal termination scenarios such as `SIGSEGV` from native code. This should be clearly documented so that users aren't misled.

**Comment by huoyaoyuan** [comment]
It's hard to run any managed code in really *critical* shutdowns, for example `FailFast`, process killed, or even system power lost.

> I need this functionality in System.Terminal to restore terminal settings

Always be recoverable when startup. Do not assume anything can be safely done at shutdown. Using a DBMS like sqlite or registry can help.

**Comment by alexrp** [comment]
> It's hard to run any managed code in really _critical_ shutdowns, for example `FailFast`, process killed, or even system power lost.

I would consider those to be edge cases not worth worrying about. I already alluded to those:

> Note: The event should not be expected to fire in edge cases such as SIGSEGV in native code.

(I've edited that paragraph to be more clear on this.)

> Always be recoverable when startup. Do not assume anything can be safely done at shutdown. Using a DBMS like sqlite or registry can help.

That's a good principle, but it doesn't really apply in my case. You can probably imagine that "by the way, you need this bundled SQLite too" is not an appropriate message to give to a user of `System.Console`. The same is true of my project.

Also, we are not talking about the *application* recovering. We are talking about the *terminal* (something external to the application) being left in a bad state. That has broader implications for usability.

**Comment by tannergooding** [comment]
CC. @jkotas, this sounds like something outside the scope of what the BCL/Runtime want to support. Is that correct?

**Comment by jkotas** [comment]
The proposal is asking for relatively minor addition to the functionality that we support already: Fire a event at the end of unhandled exception handling second pass in addition to the existing UnhandledException event that is fires at the end of the unhandled exception handling first pass.

Here is an example of existing code in our own libraries that can benefit from this API: https://github.com/dotnet/runtime/blob/983c8f239a98812498d874ed36b7001bd764fdfe/src/libraries/System.Data.OleDb/src/System/Data/ProviderBase/DbConnectionPoolCounters.cs#L163-L165

The next step here would be figuring the right API name and shape.
- I do not see a reason to the API to have `Unsafe` in the name. It is about as unsafe as the existing events. I would call it something like `CriticalCleanup` or `CriticalShutdownCleanup`.
- Should the event take the exception as an argument so that the handler can tell whether the process is exiting gracefully or due to unhandled exception?

We may want to look at this together with https://github.com/dotnet/runtime/issues/42275 .

**Comment by alexrp** [comment]
> * I do not see a good reason for to the API to have `Unsafe` in the name. The API is about as unsafe as the existing events. I would call it something like `CriticalCleanup` or `CriticalShutdownCleanup`.

My thinking there was that the `Unsafe` could be a way to dissuade application developers from using the event, since basically only library authors should be using it. But I'm not attached to that name at all. `CriticalCleanup` sounds reasonable to me, but should the class name remain as `RuntimeLifetime` or would it be better to put it on an existing class?

> * Should the event take the exception as an argument so that the handler can tell whether the process is exiting gracefully or due to unhandled exception?

This seems reasonable as long as the runtime can accommodate it.

**Comment by osexpert** [comment]
Could it be an option to "fix" AppDomain.ProcessExit instead of adding a new event?

**Comment by alexrp** [comment]
> Could it be an option to "fix" AppDomain.ProcessExit instead of adding a new event?

I think it would be unwise to change the semantics of the existing events. Too much code in the wild likely depends on the current behavior. If the documentation is inaccurate, it should be fixed.

> But if new event is needed, maybe better name can be: AppDomain.ProcessExitDueToUnhandledException.

That name does not correctly reflect the semantics of the event proposed here. It will trigger at runtime shutdown whether it's because of normal termination **or** an unhandled exception.

**Comment by osexpert** [comment]
> That name does not correctly reflect the semantics of the event proposed here. It will trigger at runtime shutdown whether it's because of normal termination **or** an unhandled exception.

Ok. So its more like AppDomain.ProcessExitEvenIfUnhandledException

**Comment by alexrp** [comment]
FWIW, I ended up moving the terminal configuration code in my library to a small C support library, where `__attribute__((constructor))` and `__attribute__((destructor))` have proved fairly reliable for ensuring that the configuration is cleaned up on normal process exit.

@jkotas you did mention some cases where this would be useful in the BCL, so should I leave this open still?

**Comment by alexrp** [comment]
As mentioned, I no longer need this, and there doesn't seem to be interest beyond my use case, so I'll withdraw the proposal.
