### ISSUE TITLE
[API Proposal]: AppendOnlyList

### ISSUE THREAD

**Issue by FilipToth** [dotnet/runtime#62841]
### Background and motivation

I noticed that we lack an append-only list/collection. This API should facilitate that gap. So essentially an immutable collection that could be only appended to, at least that is my idea.

### API Proposal

```C#
namespace System.Collections.Generic
{
    public class AppendOnlyList<T> : IList<T>
}
```

### API Usage

```C#
var x = new AppendOnlyList<int>();

x.Add(1); // Can append

x[0] = 100; // Can't mutilate
x.RemoveAt(0) // Can't remove
```

### Alternative Designs

```C#
namespace System.Collections.Generic
{
    public class AppendOnlyArray<T>
}
```

**Comment by teo-tsirpanis** [comment]
What is the use case for that? If you only want to append elements to a list, just use `List<T>` and only call `Add`. And if you need to restrict consumers of your API, create an `IAppendOnlyList` interface.

**Comment by En3Tho** [comment]
Isn't AppendOnlyArray an ImmutableArray basically?

**Comment by FilipToth** [comment]
@En3Tho Well, I was looking for a collection where you can't mutate and can't remove. @teo-tsirpanis Yes, that is what I have done. I was working on a ledger system. I was just wondering if this would have a wider array of uses cases,

**Comment by FilipToth** [comment]
I should probably close this for now since we agree that the scope of use is too small.
