### ISSUE TITLE
Consider reducing HeaderDescriptor size by using object field

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#62847]
Currently, the HeaderDescriptor struct has two fields:

```c#
        private readonly string _headerName;
        private readonly KnownHeader? _knownHeader;
```

A HeaderDescriptor is either:
(1) a known header, in which case KnownHeader is not null and _headerName is equal to _knownHeader.Name; or
(2) a custom header, in which case KnownHeader is null

We use HeaderDescriptor as the key for the HttpHeader header dictionary, which means we end up having a lot of instances of this structure. 

We could optimize for memory here by combining these two fields into a single object field that contains either a string or a KnownHeader, and then do type casts. This would result in a small amount of additional CPU work to do the casts, but this may be worth the memory savings.

**Comment by karelz** [comment]
Triage:
- We should measure CPU impact it to see if it is worth it -- combining both fields into single one.
    - In YARP we expect 2% memory savings. CPU impact should be negligible, but we should check.
