### ISSUE TITLE
Test failure System.Security.Cryptography.Rsa.Tests.SignVerify_Array.InvalidKeySize_DoesNotInvalidateKey

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62880]
Run: [runtime 20211215.49](https://dev.azure.com/dnceng/public/_build/results?buildId=1515271&view=ms.vss-test-web.build-test-results-tab&runId=43122844&resultId=160675&paneView=debug)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_release-OSX.1015.Amd64.Open

- System.Security.Cryptography.Rsa.Tests.SignVerify_Array.InvalidKeySize_DoesNotInvalidateKey

```
**Error message:**
```
Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)


Stack trace
   at Interop.AppleCrypto.RsaGenerateKey(Int32 keySizeInBits, SafeSecKeyRefHandle& pPublicKey, SafeSecKeyRefHandle& pPrivateKey) in /_/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.RSA.cs:line 143
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.GetKeys() in /_/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 700
   at System.Security.Cryptography.RSAImplementation.RSASecurityTransforms.SignHash(Byte[] hash, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/Common/src/System/Security/Cryptography/RSASecurityTransforms.cs:line 400
   at System.Security.Cryptography.RSA.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs:line 183
   at System.Security.Cryptography.RSACryptoServiceProvider.SignData(Byte[] data, Int32 offset, Int32 count, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Unix.cs:line 198
   at System.Security.Cryptography.RSA.SignData(Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/RSA.cs:line 161
   at System.Security.Cryptography.Rsa.Tests.SignVerify_Array.SignData(RSA rsa, Byte[] data, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding) in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.cs:line 16
   at System.Security.Cryptography.Rsa.Tests.SignVerify.InvalidKeySize_DoesNotInvalidateKey() in /_/src/libraries/Common/tests/System/Security/Cryptography/AlgorithmImplementations/RSA/SignVerify.cs:line 114
```

**Comment by danmoseley** [comment]
Same message as https://github.com/dotnet/runtime/issues/58640. Message is happening 2-3 times a month, always osx.1015.amd64.open

Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI1Sy27CMBC8I%2fEPK04glUcPPfRApVKERCsebZB6RCZZkoXEjrwOKFU%2fvosTCpV64GR7dnZmH14huw%2fkInXcbHzDzpCGPeloSFqjhU9j91OHGYPRv49p9B%2f11Ww8S86KcEzQIkxIEycYwdMQtDm2u4%2bDqHMJV94wHEJroihtNRv9%2fjm2KnP0kaBkse0FaA8U4tKaEJl7Kymdz%2bBIMXrgjwLM0CUm8iJTfVApRW9YBvSF67FBnhtXo8qhBFqXumbioGKE0GinSDO0FkHglCsY0FpjofswgC5spWbpzRmIUYYgMqC4zDJ0lkLYY5krsl42t2aHoYNmA2BJOaakpTnJZKHquJ0ry7jesdFtaTBH6wi50xvjVgboyOi5yrBzd52%2bfjF6S3EhthK%2fQSy85ldai0Dy3gss8KTvoWcbJjeIKaGRk5YKW9d1mr8kntZ274FquXfnL%2bCxcW3vH9V6%2fHVUUBrdYOt58yLboO3UGn5TPz6itmjJAgAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1Sy27CMBC8I%2fEPK04glUcPPfRApVKERCsebZB6RCZZkoXEjrwOKFU%2fvosTCpV64GR7dnZmH14huw%2fkInXcbHzDzpCGPeloSFqjhU9j91OHGYPRv49p9B%2f11Ww8S86KcEzQIkxIEycYwdMQtDm2u4%2bDqHMJV94wHEJroihtNRv9%2fjm2KnP0kaBkse0FaA8U4tKaEJl7Kymdz%2bBIMXrgjwLM0CUm8iJTfVApRW9YBvSF67FBnhtXo8qhBFqXumbioGKE0GinSDO0FkHglCsY0FpjofswgC5spWbpzRmIUYYgMqC4zDJ0lkLYY5krsl42t2aHoYNmA2BJOaakpTnJZKHquJ0ry7jesdFtaTBH6wi50xvjVgboyOi5yrBzd52%2bfjF6S3EhthK%2fQSy85ldai0Dy3gss8KTvoWcbJjeIKaGRk5YKW9d1mr8kntZ274FquXfnL%2bCxcW3vH9V6%2fHVUUBrdYOt58yLboO3UGn5TPz6itmjJAgAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI1Sy27CMBC8I%2fEPK04glUcPPfRApVKERCsebZB6RCZZkoXEjrwOKFU%2fvosTCpV64GR7dnZmH14huw%2fkInXcbHzDzpCGPeloSFqjhU9j91OHGYPRv49p9B%2f11Ww8S86KcEzQIkxIEycYwdMQtDm2u4%2bDqHMJV94wHEJroihtNRv9%2fjm2KnP0kaBkse0FaA8U4tKaEJl7Kymdz%2bBIMXrgjwLM0CUm8iJTfVApRW9YBvSF67FBnhtXo8qhBFqXumbioGKE0GinSDO0FkHglCsY0FpjofswgC5spWbpzRmIUYYgMqC4zDJ0lkLYY5krsl42t2aHoYNmA2BJOaakpTnJZKHquJ0ry7jesdFtaTBH6wi50xvjVgboyOi5yrBzd52%2bfjF6S3EhthK%2fQSy85ldai0Dy3gss8KTvoWcbJjeIKaGRk5YKW9d1mr8kntZ274FquXfnL%2bCxcW3vH9V6%2fHVUUBrdYOt58yLboO3UGn5TPz6itmjJAgAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1Sy27CMBC8I%2fEPK04glUcPPfRApVKERCsebZB6RCZZkoXEjrwOKFU%2fvosTCpV64GR7dnZmH14huw%2fkInXcbHzDzpCGPeloSFqjhU9j91OHGYPRv49p9B%2f11Ww8S86KcEzQIkxIEycYwdMQtDm2u4%2bDqHMJV94wHEJroihtNRv9%2fjm2KnP0kaBkse0FaA8U4tKaEJl7Kymdz%2bBIMXrgjwLM0CUm8iJTfVApRW9YBvSF67FBnhtXo8qhBFqXumbioGKE0GinSDO0FkHglCsY0FpjofswgC5spWbpzRmIUYYgMqC4zDJ0lkLYY5krsl42t2aHoYNmA2BJOaakpTnJZKHquJ0ry7jesdFtaTBH6wi50xvjVgboyOi5yrBzd52%2bfjF6S3EhthK%2fQSy85ldai0Dy3gss8KTvoWcbJjeIKaGRk5YKW9d1mr8kntZ274FquXfnL%2bCxcW3vH9V6%2fHVUUBrdYOt58yLboO3UGn5TPz6itmjJAgAA&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-90d)
| where Result == "Fail"
//| where Type == "System.ServiceProcess.Tests.ServiceBaseTests"
//| where  Method == "InvalidKeySize_DoesNotInvalidateKey"
| where Message contains "OSStatus error -50 - failed to generate asymmetric keypair"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,
  Duration,
  Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline|Pipeline_Configuration|OS|Arch|Test|Result|Finished|Duration|Method|Build|Message|
|---|---|---|---|---|---|---|---|---|---|---|
|runtime|Debug|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-11-10 16:35:13.2380000|0.196|EncryptDefaultSpan|20211110.31|Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)|
|runtime|Debug|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-11-16 17:29:14.2050000|0.386|UseAfterDispose|20211116.39|Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)|
|runtime-libraries-coreclr outerloop|Release|osx.1015.amd64.open|x64|test/functional/cli/outerloop/|Fail|2021-11-30 12:24:32.0190000|0.327|RevokeEndEntityWithInvalidRevocationSignature|20211130.3|Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)|
|runtime|Debug|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-12-06 11:22:46.8400000|1.213|BuildInvalidSignatureTwice|20211206.13|Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)|
|runtime|Release|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|Fail|2021-12-15 21:41:03.7280000|0.12|InvalidKeySize_DoesNotInvalidateKey|20211215.49|Interop+AppleCrypto+AppleCFErrorCryptographicException : The operation couldn’t be completed. (OSStatus error -50 - failed to generate asymmetric keypair)|

**Comment by vcsjones** [comment]
Hm. `-50` is `errSecParam` but it looks like this could happen in a lot of places during keep generation.

https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/native/libs/System.Security.Cryptography.Native.Apple/pal_rsa.c#L22

Is it valid for us to be passing `NULL` for `valueCallbacks` or should we be using `&kCFTypeDictionaryValueCallBacks`? We're putting `CFNumber`, `CFString`, and `CFBoolean` as values.

@filipnavara my Apple-speak isn't as strong as yours, I'm wondering if key generation doesn't like a parameter because it isn't being retained correctly.

**Comment by bartonjs** [comment]
Using the query Dan shared earlier, I see no occurrences of this in the current sliding window of test history.  Looks like an OS issue that got patched out.
