### ISSUE TITLE
Support bit shifts on long, ulong and uint

### ISSUE THREAD

**Issue by xPaw** [dotnet/runtime#62899]
Today I was [solving advent of code](https://adventofcode.com/2021/day/16) and ran into the issue where bit shifts in C# are limited to 32 bits.

In particular I had this code:
```cs
		long value = 0;
		var bitLength = bits.Count - 1;

		for (int p = 0; p <= bitLength; p++)
		{
			// value |= (long)(bits[p] << (bitLength - p));
			value += bits[p] * (long)Math.Pow(2, bitLength - p);
		}
```

Which worked just dandy for values under 32bit, but anything over it would produce incorrect result. As you can see I replaced it with a multiplication and that works fine.

Example code:
```cs
		for (var i = 0; i < 64; i++)
		{
			var a = 1 * (long)Math.Pow(2, i);
			var b = 1 << i;

			Console.WriteLine($"{i} | {a} | {b}");
		}
```

which produces:
```
30 | 1073741824 | 1073741824
31 | 2147483648 | -2147483648
32 | 4294967296 | 1
33 | 8589934592 | 2
34 | 17179869184 | 4
35 | 34359738368 | 8
```

Is there a good reason why bit shifts are not supported on longs (and unsigned types)? I understand there isn't a larger type which would a result of all shifts, however it seems that return type of `<< for (int, int)` is an int.

I think there is value in having shifts on longs supported.

**Comment by kevingosse** [comment]
Bitshift is already supported on longs, you just need to use the right datatype. If you use a bitshift operation on an int, it will return an int. If you use a bitshift operation on a long, it will return a long.

```csharp
Console.WriteLine(1 << 31); // -2147483648 (int)
Console.WriteLine(1U << 31); // 2147483648 (uint)
Console.WriteLine(1U << 32); // 1 (overflowing uint)
Console.WriteLine(1L << 32); // 4294967296 (long)

```

**Comment by xPaw** [comment]
It is? I'm on 6.0.1

> Operator '<<' cannot be applied to operands of type 'long' and 'long' csharp(CS0019)

**Comment by huoyaoyuan** [comment]
> Operator '<<' cannot be applied to operands of type 'long' and 'long' csharp(CS0019)

The left hand side of the operator can be `int`, `uint`, `long`, or `ulong`, but the right hand side must be `int`, since you can't shift 2^32 bits.

**Comment by xPaw** [comment]
Welp I see my issue now.

I had
```
value |= (long)(bits[p] << (bitLength - p));
```

instead of 

```
value |= (long)bits[p] << (bitLength - p);
```

Disregard me not paying attention 😄
