### ISSUE TITLE
Fix grammar for the repository description

### ISSUE THREAD

**Issue by Perksey** [dotnet/runtime#629]
Good lord please fix this.
![image](https://user-images.githubusercontent.com/11160611/70355708-b6c22c00-186a-11ea-861a-f0d57bfba159.png)
Nothing makes me shiver more than bad grammar

> .NET is a cross-platform runtime and libraries

to

- > .NET is a cross-platform runtime and library set
- > .NET is a cross-platform runtime and framework
- > .NET is a cross-platform runtime and set of libraries
- Or whatever else tickles your fancy

**Comment by Foxtrek64** [comment]
While we're at it, no comma before "for cloud."

And we need an Oxford comma after "primitive data types."

**Comment by Perksey** [comment]
Ah yes Oxford comma master race.

**Comment by stephentoub** [comment]
I fixed the grammar.

**Comment by Perksey** [comment]
Thank youu <3
