### ISSUE TITLE
typo in autogenerated cs file

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#62909]
### Description

In my workspace on Linux, I have a file
  ./artifacts/obj/coreclr/System.Private.CoreLib/x64/Release/System.SR.cs
That file contains the line
 /// <summary>Object is not a array with the same number of elements as the array to compare it to.</summary>
That text is wrong English spelling/grammar.

It should read ... is not an array ...

### Reproduction Steps

look at the SR.cs file

### Expected behavior

bad English embedded into .dll files

### Actual behavior

correct English

**Comment by RobertHenry6bev** [comment]
area-Meta

**Comment by vcsjones** [comment]
If you are interested in submitting a pull request to fix this, it appears in these two locations:

https://github.com/dotnet/runtime/blob/e233b7b5b00d9b80f155cd484e246dfc24fdf801/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L1552-L1554

https://github.com/dotnet/runtime/blob/e233b7b5b00d9b80f155cd484e246dfc24fdf801/src/coreclr/nativeaot/System.Private.CoreLib/src/Resources/Strings.resx#L888-L890

The autogenerated C# files come from these resx files.
