### ISSUE TITLE
JSON Serializer Source Generator doesn't work

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#62915]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/JSON-Serializer-Source-Generator-doesnt/1582784)._

---
[severity:I'm unable to use this version]
After decorating a JsonSerializerContext class with JsonSerializable the JsonSourceGenerator never generates files

---
#### Feedback Bot on 11/14/2021, 10:09 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ericstj** [comment]
Opened in VS Feedback by @csharpfritz.   Can you please add your repro project here?

**Comment by csharpfritz** [comment]
I'll put together a repro this week..  It's taking me time to isolate the
issue from my larger project


Jeff

**Comment by Akarinnnnn** [comment]
Repro code, edited in VS 2022 17.0.4
```csharp demo.cs
namespace Demo
{
	public class TargetType
	{
		// Comment out any json attribute to reproduce bug
		// reload project could resolve
		[JsonInclude]
		public int included;
		[JsonIgnore]
		public int ignored;
		[JsonExtensionData]
		public IDictionary<string, object>? extData;
	}

	[JsonSerializable(typeof(TargetType))]
	internal partial class ReproduceContext : JsonSerializerContext
	{

	}
}
```

**Comment by Akarinnnnn** [comment]
Detailed version may helpful:
> Microsoft Visual Studio Community 2022
> 版本 17.0.4
> VisualStudio.17.Release/17.0.4+32014.148
> Microsoft .NET Framework
> 版本 4.8.04161
> 
> 已安装的版本: Community
> 
> Visual C++ 2022   00482-90000-00000-AA316
> Microsoft Visual C++ 2022
> 
> ASP.NET and Web Tools 2019   17.0.795.42246
> ASP.NET and Web Tools 2019
> 
> ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
> 更多信息，请访问 https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   17.0.795.42246
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools   17.0.795.42246
> Azure Functions and Web Jobs Tools
> 
> C# 工具   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
> IDE 中使用的 C# 组件。可能使用其他版本的编译器，具体取决于你的项目类型和设置。
>  ...
> NuGet 包管理器   6.0.1
> Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 https://docs.nuget.org/
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> ...
> Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
> 提供 ASP.NET Core Razor 的语言服务。

**Comment by layomia** [comment]
@Akarinnnnn I didn't get any errors when trying your repro. Can you share specifically what errors or warnings you're encountering?

---
Ping @csharpfritz, just checking on the issue you initially reported.

**Comment by Akarinnnnn** [comment]
Here is the fixed repro code:
```csharp
using System.Text.Json.Serialization;
namespace Demo
{
	public class TargetType
	{
		// Add a field, then type "[" before the field to add an attribute.
		// You will got CS0534 and CS7036 on type 'ReproduceContext'
		// reload project could resolve

		// [JsonInclude]
		// public int a;
	}

	[JsonSerializable(typeof(TargetType))]
	internal partial class ReproduceContext : JsonSerializerContext
	{

	}

}
```

Errors:
> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误	CS0534	“ReproduceContext”不实现继承的抽象成员“JsonSerializerContext.GetTypeInfo(Type)”	Demo	D:\src\JsonSourcegenBreak\Demo\TargetType.cs	19	活动
> 错误	CS0534	“ReproduceContext”不实现继承的抽象成员“JsonSerializerContext.GeneratedSerializerOptions.get”	Demo	D:\src\JsonSourcegenBreak\Demo\TargetType.cs	19	活动
> 错误	CS7036	未提供与“JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)”的必需形参“options”对应的实参	Demo	D:\src\JsonSourcegenBreak\Demo\TargetType.cs	19	活动

**Comment by layomia** [comment]
@Akarinnnnn do things work as expected when you finish typing the complete `[JsonInclude]` attribute?

**Comment by Akarinnnnn** [comment]
> @Akarinnnnn do things work as expected when you finish typing the complete `[JsonInclude]` attribute?

Not work until reloaded whole project.

**Comment by layomia** [comment]
@Akarinnnnn thanks, I was able to repro this with the latest VS Enterprise 2022 17.1.0 Preview 5.0. A manual rebuild (e.g. ctrl+B) was needed to get rid of the compile errors. I recommend creating a new issue in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repo since they handle IDE issues.
