### ISSUE TITLE
First chance exceptions and missing logging when a service isn't given a service name

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#62923]
See https://github.com/dotnet/runtime/issues/62579#issuecomment-995320972

The default behavior for ServiceBase when a ServiceName isn't specified is to use an empty string.  Per https://docs.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_table_entrya 
> If the service is installed with the SERVICE_WIN32_OWN_PROCESS service type, this member is ignored, but cannot be NULL. This member can be an empty string ("").

The problem, however, is that later on we use `ServiceName` to construct a log: 
https://github.com/dotnet/runtime/blob/1a83f61a5a3368250e5bed2baf28aed0f9e59508/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#L238-L241

And EventLog will throw for an empty `Source`:
https://github.com/dotnet/runtime/blob/1a83f61a5a3368250e5bed2baf28aed0f9e59508/src/libraries/System.Diagnostics.EventLog/src/System/Diagnostics/EventLogInternal.cs#L1300-L1301

So in this common scenario all of these calls to WriteEventLog result in first chance exceptions, and nothing is logged:
https://github.com/dotnet/runtime/blob/1a83f61a5a3368250e5bed2baf28aed0f9e59508/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#L944-L958

In this scenario we can actually acquire the service name from SCM, it's returned in the ServiceMain callback https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nc-winsvc-lpservice_main_functiona
> the first argument (lpServiceArgVectors[0]) is the name of the service

I have confirmed this to be the case.  So we can simply capture it here and set `ServiceName` rather than skipping it:
https://github.com/dotnet/runtime/blob/1a83f61a5a3368250e5bed2baf28aed0f9e59508/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#L866-L880

**Comment by safern** [comment]
@ericstj I see this is causing: #62579, from the discussion it seems like fixing this just luckily fixes that but the fix should be more intentional. Let me know if we want to service this, for now I'll set it as 7.0

**Comment by ericstj** [comment]
Right, this wasn't blocking.  It was just a significant influence to timing and that linked issue was a race condition sensitive to timing.  I think it is fine to just fix this in 7.0.
