### ISSUE TITLE
The mscordbi.dll .NET 5.0.13 is missing from symbol servers.

### ISSUE THREAD

**Issue by petterlabraaten** [dotnet/runtime#62939]
### Description

Similar to issue https://github.com/dotnet/runtime/issues/61775 it seems that mscordbi.dll version 5.0.1321.56516 also slipped through the cracks and is missing from the symbol servers.

![image](https://user-images.githubusercontent.com/2458077/146471780-c5f49e63-b0c9-440e-885c-5498205139a4.png)

### Reproduction Steps

Try debugging a minidump from Linux running .NET 5.0.13 in Visual Studio -- open it and then try to start Managed Debugging.

### Expected behavior

The debugging works as usual.

### Actual behavior

The VS hangs with the message about mscordbi.dll not available (see Description above).

**Comment by tommcdon** [comment]
Thanks for the feedback!  We've passed this feedback on to our infrastructure team who is investigating.

**Comment by tommcdon** [comment]
@hoyosjs was this issue fixed recently and if so can it be closed?

**Comment by hoyosjs** [comment]
Yes, it was.
