### ISSUE TITLE
[API Proposal]: Make `Lookup<TKey,TElement>` publicly constructable

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/runtime#62949]
### Background and motivation

This would allow EF Core to implement `ToLookUpAsync` in the same way we implement `ToDictionaryAsync` without needing to go through an intermediate data structure.

See https://github.com/dotnet/efcore/issues/26867

### API Proposal

Make current internal `Create` methods public.

```C#
    public static Lookup<TKey, TElement> Create<TSource>(
      IEnumerable<TSource> source,
      Func<TSource, TKey> keySelector,
      Func<TSource, TElement> elementSelector,
      IEqualityComparer<TKey> comparer)
    {
    }

    public static Lookup<TKey, TElement> Create(
      IEnumerable<TElement> source,
      Func<TElement, TKey> keySelector,
      IEqualityComparer<TKey> comparer)
    {
    }
```

### API Usage

```C#
var childLookup = await context.ChildEntities
    .Where(c => Enumerable.Contains(parentIds, c.ParentId))
    .ToLookupAsync(c => c.ParentId);
```

**Comment by terrajobst** [comment]
* Looks good as proposed
    - We want to avoid adding conflicts with RX/IX so we don't to create extension methods like `ToLookupAsync()`
    - At the same time we don't want to make `Lookup<TKey, TElement>` mutable
    - This means we'd need a single entry point that takes an `IAsyncEnumerable<TSource>` and produces a `Lookup<TKey, TElement>`
    - Easiest seems to be factory method directly on `Lookup<TKey, TElement>`
* Alternatively, EF could return a custom implementation of `ILookup<TKey, TElement>`, similar to PLinq
    - Sounds like we want to explore this first

```C#
namespace System.Linq
{
    public partial class Lookup<TKey, TElement>
    {
        public static Task<Lookup<TKey, TElement>> CreateAsync<TSource>(
            IAsyncEnumerable<TSource> source,
            Func<TSource, TKey> keySelector,
            Func<TSource, TElement> elementSelector,
            IEqualityComparer<TKey> comparer);
    }
}
```

**Comment by eiriktsarpalis** [comment]
> Looks good as proposed

I missed the review, but this seems inconsistent with the points made below. 

It seems to me that we can close this until https://github.com/dotnet/efcore/issues/26867 can explore alternative avenues, what say you @ajcvickers?

**Comment by terrajobst** [comment]
Yes, the conclusion was that @smitpatel will try the custom implementation of `ILookup<,>` first.

**Comment by eiriktsarpalis** [comment]
Closing in that case, can revisit if the need arises.
