### ISSUE TITLE
Error unzipping file with GZipStream

### ISSUE THREAD

**Issue by lorenzo93** [dotnet/runtime#62954]
### Description

When I try to decompress a file using `System.IO.Compression.GZipStream` I receive different output than if I decompress the file using an external decompressor (eg. WinRAR) and than reading it as FileStream.

The problem occurs only if I read the file all together with the goal of putting it into a `byte[]` (to avoid IO and browse the file quickly).

I'm no expert in compressing algorithms and for other `.GZ` files it works perfectly. Maybe the problem is just related to that specific file but since common decompressors are able to decompress it without problems (I even tried the check integrity from WinRAR) there should be a way to decompress it correctly.
I even tryed to compress (with the unix `bzip` command) the decompressed version and then read it in C#. The problem persists even in this case.

### Reproduction Steps

The file where I found the bug is the one [attached](https://github.com/dotnet/runtime/files/7734705/updates.gz). It is a file containing routing informations and it was downloaded from [here](https://data.ris.ripe.net/rrc00/2021.12/updates.20211216.1020.gz). The file is in a format called MRT and it is a binary format, so it is not possible to open it with a regular text editor.
I present here two version of the code: the WorkingProgram and the NotWorkingProgram. If you prefer to avoid copy-pasting, 
[here](https://github.com/dotnet/runtime/files/7735546/CodeExamples.zip) you can download the two `.cs` files cited below.

To reproduce the problem:

1. Download the attached `updates.gz` file
2. Decompress the file so that you have both compressed and uncompressed file
3. (if needed) Fix the two paths in the example code according to the file paths
4. Run the example code

```csharp
using System;
using System.IO;
using System.IO.Compression;

namespace TestDezip
{
	class WorkingProgram
	{
		static void Main()
		{
			Console.WriteLine("Starting");

			FileInfo fileUnzipped = new(@"updates");
			FileInfo fileZipped = new(@"updates.gz");

			using FileStream fileStream = fileZipped.OpenRead();
			using GZipStream gzStream = new(fileStream, CompressionMode.Decompress);

			using FileStream unzippedStream = fileUnzipped.OpenRead();


			while (unzippedStream.CanSeek)
			{
				int unzippedByte = unzippedStream.ReadByte();
				int zippedByte = gzStream.ReadByte();

				if(unzippedByte == -1)
				{
					if(zippedByte == -1)
					{
						break;
					} else
					{
						Console.WriteLine("File length different");
					}
				}

				if (unzippedByte == zippedByte)
				{
					continue;
				}
				else
				{
					Console.WriteLine($"Error! {unzippedByte} != {zippedByte}");
				}
			}

			Console.WriteLine("End");
		}
	}
}
```

```csharp
using System;
using System.IO;
using System.IO.Compression;

namespace TestDezip
{
	class NotWorkingProgram
	{
		static void Main()
		{
			Console.WriteLine("Starting");

			FileInfo fileUnzipped = new(@"updates");
			FileInfo fileZipped = new(@"updates.gz");

			using FileStream fileZippedStream = fileZipped.OpenRead();

			//Read GZ uncompressed length
			fileZippedStream.Position = fileZippedStream.Length - 4;
			var lengthByteArray = new byte[4];
			fileZippedStream.Read(lengthByteArray, 0, 4);
			uint fileLength = BitConverter.ToUInt32(lengthByteArray, 0);
			fileZippedStream.Position = 0;

			using GZipStream gzStream = new(fileZippedStream, CompressionMode.Decompress);

			//Create local array to save uncompressed version of zipped file
			byte[] gzFileBuffer = new byte[fileLength];
			gzStream.Read(gzFileBuffer, 0, (int)fileLength);

			//Open and cache unzipped file
			using FileStream fileUnzippedStream = fileUnzipped.OpenRead();
			byte[] uncompressedFileBuffer = new byte[fileUnzippedStream.Length];
			fileUnzippedStream.Read(uncompressedFileBuffer, 0, (int)fileUnzippedStream.Length);

			if(uncompressedFileBuffer.Length != gzFileBuffer.Length)
			{
				Console.WriteLine("Error");
			}
			
			for(int i = 0; i< uncompressedFileBuffer.Length; i++)
			{
				byte unzippedByte = uncompressedFileBuffer[i];
				byte zippedByte = gzFileBuffer[i];

				if (unzippedByte == zippedByte)
				{
					continue;
				}
				else
				{
					Console.WriteLine($"Error at position {i}! {unzippedByte} != {zippedByte}");
				}
			}

			Console.WriteLine("End");
		}
	}
}
```

### Expected behavior

The compressed and uncompressed arrays should be equal.

### Actual behavior

The compressed and uncompressed arrays have their first difference at index 41507, then they are quite completely different.

### Known Workarounds

If I use `ICSharpCode.SharpZipLib.GZip.GZipInputStream` (from NuGet) to decompress the file it works perfectly.

### Configuration

The code is running on .NET 6.0 on a Windows 10 machine with x86 architecture.

**Comment by nuzolx** [comment]
@lorenzo93 Read this: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

I think this a new behavior.

**Comment by stephentoub** [comment]
> I think this a new behavior.

Not for streams in general... it's always been the case that Stream.Read may return fewer bytes than requested.  What changed in .NET 6 is DeflateStream.Read as an implementation detail had been aggressively trying to fill the buffer, to the detrement of scenarios that rely on Read giving back data as it's available,  and now in .NET 6 it isn't so aggressive.

**Comment by lorenzo93** [comment]
HI,

I think I've missed that article and the problem lies there, thanks a lot for suggesting it.

I've modified my code to cycle through the bytesRead as suggested in the article, but I always get an `ArgumentOutOfRangeException`. There is something I got wrong?

The example refers to a `buffer` variable that is not shown which type it is. I think it is some kind of Span (because the author use the `.Slice()` method) and I've tried to use the array as it is my original version without any luck.

Moreover, my final goal is to have a `ReadOnlyMemory<byte>` of the whole array to parse it, maybe starting with the array is not the best approach? :)

```csharp
using System;
using System.IO;
using System.IO.Compression;

namespace TestDezip
{
	class NotWorkingProgram
	{
		static void Main()
		{
			Console.WriteLine("Starting");

			FileInfo fileZipped = new(@"updates.gz");

			using FileStream fileZippedStream = fileZipped.OpenRead();

			//Read GZ uncompressed length
			fileZippedStream.Position = fileZippedStream.Length - 4;
			var lengthByteArray = new byte[4];
			fileZippedStream.Read(lengthByteArray, 0, 4);
			uint fileLength = BitConverter.ToUInt32(lengthByteArray, 0);
			fileZippedStream.Position = 0;

			using GZipStream gzStream = new(fileZippedStream, CompressionMode.Decompress);

			//Create local array to save uncompressed version of zipped file
			byte[] gzFileBuffer = new byte[fileLength];

			int totalRead = 0;
			while (totalRead < gzFileBuffer.Length)
			{
				int bytesRead = gzStream.Read(gzFileBuffer, totalRead, gzFileBuffer.Length);
				if (bytesRead == 0) break;
				totalRead += bytesRead;
			}

			Console.WriteLine("End");
		}
	}
}
```

**Comment by lorenzo93** [comment]
Sorry, my fault.

I forgot to subtract `totalRead` from `gzFileBuffer.Length` when calling read.

thanks a lot to all!
