### ISSUE TITLE
Support equivalent of AssemblyBuilder.Save to save in-memory IL to an assembly

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#62956]
The most common feature request in reflection, with 100+ upvotes, is to add support for equivalent `AssemblyBuilder.Save()` functionality. Since this exists in .NET Desktop, some consider this an adoption blocker.

Prototyping done in .NET 7.0 to investigate feasibility of adding the `Save()` via an adapter from `AssemblyBuilder` to the newer `MetadataBuilder` which supports writing IL to a Stream\file. Related issues:

[System.Reflection.Emit.AssemblyBuilder.Save](https://github.com/dotnet/runtime/issues/15704)
[Unable to set EntryPoint on generated assemblies with System.Reflection.Emit](https://github.com/dotnet/runtime/issues/62591)

We plan to abstract out Reflection.Emit APIs in order to have two implementations, one that having old code to support all downlevel runtime, and a new implementation that replaces the current Reflection.Emit implementation with `AssemblyBuilder.Save()` support, steps:
- [x] Abstract out Reflection.Emit APIs, refactor old code that support all downlevel runtime versions.
- [x] Move the [prototyping work](https://github.com/dotnet/runtimelab/tree/feature/assembly-builder-save) into runtime with necessary refactoring
- [x] Have the new APIs for[ `ParameterBuilder`](https://github.com/dotnet/runtime/issues/83831) and [`AssemblyBuilder.Save(string/stream)`](https://github.com/dotnet/runtime/issues/83988) reviewed and approved
- [x] Implement the parts that needed for MVP (Minimum Viable Product) `AssemblyBuilder.Save(string/stream)` 
  - [x] Add support for saving different types like struct/class etc. and their references
  - [x] Add support for saving `CustomAttributes` for all members like assembly/module ([PR](https://github.com/dotnet/runtime/pull/84580))
  - [x] Have an APIs proposal for abstracting ILGenerator and other related APIs reviewed and approved. 
  - [x] Abstract out ILGenerator accordingly
  - [x] Save interface implementation, nested types for a Type (in [PR](https://github.com/dotnet/runtime/pull/85596))
  - [x] Abstract out ParameterBuilder in runtime, add ParameterBuilderImpl and save it to file/stream 
  - [x] Add EnumBuilderImpl  and save it to file/stream
  - [x] Add support for more complicated signatures for each member (generics/array/byRef/pointer etc) 
    - [x] Add GenericTypeParameterBuilderImpl and save a generic Type/Method
  - [x] Save constant value for a Field

Remaining work that out of .NET 8.0:
- [ ]  Implement remaining parts needed for `AssemblyBuilder.Save(string/stream)` (mostly will rely on community contributions)
  - [ ] ILGenerator implementation
  - [ ] Add support for remaining members
    - [ ] Add ConstructorBuilderImpl and save it to file/stream (this needs minimal IL support)
    - [ ] Add PropertyBuilderImpl and save it to file/stream (this also needs minimal IL support)
    - [ ] Add EventBuildterImpl and save it to file/stream
    - [ ] Add implementation for remaining APIs for a MethodBuilder/TypeBuilder/FieldBuilder (like `SignatureCallingConvention`, `*RequiredCustomModifiers`, `*OptionalCustomModifiers`)
  - [ ] Have an API for creating PDBs and implement it
  - [ ] Entry point support
- [ ] Add support for Running the assembly

**Comment by lbargaoanu** [comment]
Would that make `LambdaExpression.CompileToMethod` more likely? :) I know `System.Linq.Expressions` is archived, but [apparently](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#evolve-systemlinqexpression) things are going to happen.

**Comment by MichaelKetting** [comment]
@steveharter I have not fully investigated MetadataBuilder at this time, but is there a 'cheap' way to get all the IL needed and just pipe it into MetadataBuilder or do we need to do this IL-statement by IL-statement?

Also, thanks @danmoseley for mentioning this API. I've been looking for this forever.

**Comment by MSDN-WhiteKnight** [comment]
>I have not fully investigated MetadataBuilder at this time, but is there a 'cheap' way to get all the IL needed and just pipe it into MetadataBuilder or do we need to do this IL-statement by IL-statement?

It is done currently statement-by-statement, you need to create [InstructionEncoder](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.ecma335.instructionencoder?view=net-6.0) and emit statements into it, then pass it to MethodBodyStreamEncoder.AddMethodBody. I suppose, we could add new AddMethodBody overload that takes array of IL bytes and emits it as a whole if it would be found useful. But the important thing about that proposed adapter is that it should not just mechanically copy the contents of in-memory assembly into MetadataBuilder, it needs to do some changes - replace every reference to System.Private.CoreLib to System.Runtime, for example. So the ability to emit the whole IL array might not simplify the task significantly.

**Comment by MichaelKetting** [comment]
@MSDN-WhiteKnight Thanks for the details. So, it's definitely not "cheap" as in "copy all IL bytes inside the assembly from A to B" but requires a more structured approach. Good to know because for me this means it's best to wait for the official API to catch up instead of doing it in my own code and then switch later on once the official API also supports it (aside from the question if/when/how best to contribute to this).

**Comment by steveharter** [comment]
Moving to 8.0. There is currently active [prototyping work](https://github.com/dotnet/runtimelab/tree/feature/assembly-builder-save) for this.

**Comment by steveharter** [comment]
> Can we also save assembly to bytes so I can do something with them without saving to file first which in some situations like Blazor webassembly there is no file system

Do you mean like `byte[] ToBytes()`? If so, I guess that would write to a MemoryStream, not a FileStream which at that point I guess we could just return Stream?

**Comment by Xyncgas** [comment]
> Do you mean like byte[] ToBytes()? If so, I guess that would write to a MemoryStream, not a FileStream which at that point I guess we could just add void ToStream(Stream)?

Yea ok, I can use memory stream to write to files or I can do whatever I want with it when I don't want to write to files

While we are at it, might as well let us rewrite the assembly to contain certain ```types``` or ```static variables```, then output it as bytes

**Comment by masonwheeler** [comment]
Not mentioned anywhere: PDB generation.  That was an important part of refemit; is it going to be in 8.0?

**Comment by masonwheeler** [comment]
@OwnageIsMagic
> use appropriate tool (Roslyn API)

Not even close.  Roslyn is the appropriate tool for turning C# code into a compiled assembly.  It is not the appropriate tool for the general use-case of generating assemblies, unless your intention is to completely throw the most fundamental promise of a *Common Language* Runtime out the window.

**Comment by OwnageIsMagic** [comment]
@masonwheeler I'm not trying to say `AssemblyBuilder.Save` is not useful, I said for case described by @Xyncgas Roslyn is more appropriate tool (LLMs generate code in high level languages, so it's about string to assembly, not _general use-case of generating assemblies_).

Can you elaborate more on `the most fundamental promise`? I know for Java it was `Write once, run anywhere`, what about .NET?
CLR is actually Microsoft implementation of CLI (ECMA-335). `V.5.5 Reflection library` of ECMA-335 states that `Reflection` library is optional, [library specification](https://www.ecma-international.org/publications-and-standards/technical-reports/ecma-tr-84/) doesn't mention `Reflection.Emit` namespace at all.
So `Reflection.Emit` is just another regular library, you are free to use `Mono.Cecil` or any other.

**Comment by masonwheeler** [comment]
@OwnageIsMagic The most fundamental promise of a common language runtime is right there in the name: it's one runtime that can be shared in common by multiple languages.  What I was saying is that trying to narrow its scope to only C# — as far too many people have actually done, even if you aren't one of them — is a betrayal of that promise.

**Comment by buyaa-n** [comment]
Update: We have added partial support for AssemblyBuilder.Save in .NET 8:

We have completed our goal to add MVP (Minimum Viable Product) support in .NET 8 that allows us to save *.tlb files produced by [TlbImp tool](https://learn.microsoft.com/en-us/dotnet/framework/tools/tlbimp-exe-type-library-importer). Now we can port the tool into .NET Core using the new AssemblyBuilder.Save implementation.

The implementation support following:
- Create persist able AssemblyBuilder with or without custom attributes
- Define ModuleBuilder (same as existing AssemblyBuilder only one module supported)
- Define classes, interfaces, structs
- Define fields, asbstract methods, method parameters for them. 
- Add custome attributes for each member
- Save the assebmly

The implementation doesn't support other members (a method with body (IL not supported), Properties, Constructors, Events). Because we have only partial implementaion we did not exposed [the approved new APIs](https://github.com/dotnet/runtime/issues/83988#issuecomment-1487355324 publicly). Those APIs are internal, if you want to give it a try you could use reflection, example:

```cs
using System.Reflection.Emit;
using System.Reflection;

namespace TestApp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            AssemblyName aName = new AssemblyName("MyAssembly");
            AssemblyBuilder ab= PopulateAssemblyBuilderAndSaveMethod(aName, null, out MethodInfo saveMethod);
            ModuleBuilder moduleBuilder = ab.DefineDynamicModule("ModuleName"); // Only one module supported
            moduleBuilder.DefineType("TestInterface", TypeAttributes.Interface | TypeAttributes.Abstract);
            // Add other classes, interfaces, and structs. Define method, field, custom attributes for them

            // Note that non abstract method not supported yet as writing IL is not supporeted yet
            // defining Constructors, Properties and Events are also not supported yet

            // Then save the assembly into a file (or Stream)
            saveMethod.Invoke(ab, new object[] { "MyAssembly.dll" });
        }

        private static AssemblyBuilder PopulateAssemblyBuilderAndSaveMethod(AssemblyName assemblyName,
                List<CustomAttributeBuilder>? assemblyAttributes, out MethodInfo saveMethod)
        {
            Type abType= Type.GetType("System.Reflection.Emit.AssemblyBuilderImpl, System.Reflection.Emit", throwOnError: true)!;

            saveMethod = abType.GetMethod("Save", BindingFlags.NonPublic | BindingFlags.Instance,
                                         new Type[] { typeof(string) /* or use typeof(Stream) */ });

            MethodInfo defineDynamicAssembly = abType.GetMethod("DefinePersistedAssembly", BindingFlags.NonPublic | BindingFlags.Static,
                new Type[] { typeof(AssemblyName), typeof(Assembly), typeof(List<CustomAttributeBuilder>) });

            return (AssemblyBuilder)defineDynamicAssembly.Invoke(null, new object[] { assemblyName, typeof(object).Assembly, assemblyAttributes });
        }
    }
}
```

**Comment by masonwheeler** [comment]
> IL not supported

So... a whole lot of work to produce a resulting product that's entirely worthless.  If you can't create method bodies, is there any point at all to any of it?

**Comment by AaronRobinsonMSFT** [comment]
> > IL not supported
> 
> So... a whole lot of work to produce a resulting product that's entirely worthless. If you can't create method bodies, is there any point at all to any of it?

I think this response is unnecessarily mean and ignorant.

Yes, there is a lot of value in proving out the MVP and ensuring that the design can satisfy the needs of a real scenario. As @buyaa-n mentioned the `TlbImp` scenario can be completed for the most common scenarios. There are limitations, but for right now the private implementation has helped us to understand how to architect a high quality solution.

**Comment by terrajobst** [comment]
@masonwheeler 

As Aaron said, your comment is unnecessarily hostile and violates our Code of Conduct. I've called you out for your [commenting style before](https://github.com/dotnet/runtime/issues/62472#issuecomment-988400181). This is the last warning. If we see further behavior like this, we'll block your account.

**Comment by KicsA** [comment]
> @masonwheeler
> 
> As Aaron said, your comment is unnecessarily hostile and violates our Code of Conduct. I've called you out for your [commenting style before](https://github.com/dotnet/runtime/issues/62472#issuecomment-988400181). This is the last warning. If we see further behavior like this, we'll block your account.

You can police me today, but we are anonymous, enjoy your victory on the internet, fill your little bitch form for getting butt hurt, it is a matter of when the chinese will invade, killing man n raping wives, while u are getting stabbed in the back standing against the people I will be the last one laughing

**Comment by MichaelKetting** [comment]
@buyaa-n  Thank you for the update! 

Since IL is not supported in the first drop and you mentioned testing out the APIs via Reflection: My scenario is to use runtime code generation to build subclass proxies and then persisting the generated assemblies so we don't pay for it during each application start. Right now, the Save-code is enabled only for the .NET Framework targeted assembly of our library. 

If I read the current state of the implementation correctly, there is no helpful information to gain if I try the current state via reflection. Since the complete feature is still marked for the .NET 8 release, I'll happily wait for the drop with IL support and test once my scenario becomes available. If there is anything I should test (and provide feedback on) before that point, please let me know.

For completeness sake: right now I'm expecting that I can just call the same APIs again as I do in .NET Framework once the feature is production ready (`AssemblyBuilder.Save()` and `ILGenerator.MarkSequencePoint` and the `ISymbolDocumentWriter` interface's API)

Thanks, Michael

**Comment by masonwheeler** [comment]
OK, sorry about that.  Let's try this again, a bit less confrontationally.

I was under the impression that the main reason `AssemblyBuilder.Save` was not originally included in .NET Core was a technical one:  generating cross-platform PE files and PDB files is not as simple as generating Windows-only binaries.  Therefore, I was kind of expecting that the Core implementation would keep about 90% of [the existing, tried-and-tested `Save` code from .NET Framework](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/reflection/emit/assemblybuilder.cs#L1735) and focus on that specific challenge.

The not-supported features described above all fall under the category of "generate IL and metadata," which doesn't feel like something that needs to be reimplemented in a cross-platform manner.  (There is no platform-dependent code in [`System.Reflection.Metadata.IL.MethodBodyBlock`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/IL/MethodBodyBlock.cs), for example.)  But apparently this is not the case.  So what am I missing?

**Comment by MSDN-WhiteKnight** [comment]
>For completeness sake: right now I'm expecting that I can just call the same APIs again as I do in .NET Framework once the feature is production ready

This expectation can't be met. It is already decided that API surface is different, the new API takes additional parameter for core assembly, while .NET Framework API always implied the current implementation's core assembly. 

>Therefore, I was kind of expecting that the Core implementation would keep about 90% of the existing, tried-and-tested Save code from .NET Framework and focus on that specific challenge.

Same goes for this expectation, too. It was already discussed at length, maintainers stated that existing code is native and tied to Windows too much, so it's too hard to bring it cross platform. So the current work entirely reimplements everything as managed implementation on top of System.Reflection.Metadata.

**Comment by MichaelKetting** [comment]
@masonwheeler

> Therefore, I was kind of expecting that the Core implementation would keep about 90% of [the existing, tried-and-tested Save code from .NET Framework](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/reflection/emit/assemblybuilder.cs#L1735) and focus on that specific challenge.

Let me paraphrase: `AssemblyBuilder.Save()` in .NET 8 is already able to persist a complete .NET assembly (the DLL file, personally, I don't care about doing it with EXE files) to disk after the types (including method bodies) have been created at runtime in memory?


> The not-supported features described above all fall under the category of "generate IL and metadata," which doesn't feel like something that needs to be reimplemented in a cross-platform manner. (There is no platform-dependent code in [System.Reflection.Metadata.IL.MethodBodyBlock](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/IL/MethodBodyBlock.cs), for example.)

This sentence actually confuses me a bit right now:

> The not-supported features described above 

Do you mean the [features I mentioned](https://github.com/dotnet/runtime/issues/62956#issuecomment-1645056506) or the features discussed in the [announcement post ](https://github.com/dotnet/runtime/issues/62956#issuecomment-1644570818)? In the announcement post, method bodies are listed as not (yet) supported.

Thanks, Michael

**Comment by AaronRobinsonMSFT** [comment]
> generating cross-platform PE files and PDB files is not as simple as generating Windows-only binaries

No, this is easily handled by Roslyn and the runtime can handle this as well. Windows PDBs (non-portable) are hard, but that is why Portable PDBs exist.

> But apparently this is not the case. So what am I missing?

The original was deep within the runtime with a lot of unmanaged code. This is a complete rewrite in pure managed so that it can be independent of the runtime implementation and shared with other runtimes (i.e., NativeAOT mono etc).

Also note that in .NET 8 the goal was for an MVP see the original announcement - https://github.com/dotnet/runtime/issues/62956#issuecomment-1644570818.

> We have completed our goal to add MVP (Minimum Viable Product) support in .NET 8

This is not ready for everyone to start using as if it is full support in .NET 8. It was meant as a friendly update on status with a brief outline of current support. The goal is to have the ability to generate arbitrary .NET Assemblies in a similar way in .NET Core, but that isn't the current level as it is a full rewrite and reconciliation of how an assembly is generated.

There will be slight API changes for all the reasons mentioned in https://github.com/dotnet/runtime/issues/62956#issuecomment-1645609191.

**Comment by MichaelKetting** [comment]
@MSDN-WhiteKnight 
> This expectation can't be met. It is already decided that API surface is different, the new API takes additional parameter for core assembly, while .NET Framework API always implied the current implementation's core assembly.

Okay, that's not a problem. Probably should have been a bit more highlevel with "expect". What I intended to express was, that there's a way similiar to `AssemblyBuilder.Save(...)` that allows persisting the runtime generated assembly including methods with their bodies. And for added value, it would also be great to support the generation Debug symbols.

**Comment by masonwheeler** [comment]
@MichaelKetting 
> Do you mean the features I mentioned or the features discussed in the announcement post?

The latter.

@AaronRobinsonMSFT 
> The original was deep within the runtime with a lot of unmanaged code.

OK, that would do it.  Thanks for clarifying!

**Comment by MichaelKetting** [comment]
@AaronRobinsonMSFT and now I'm coming full circle and I'm terribly sorry for repeating the same question. I'll try super simple / unabiguous ones:

1. Can we use AssemblyBuilder right now to persist runtime generated types, including their method bodies? (from reading https://github.com/dotnet/runtime/issues/62956#issuecomment-1644570818, the answer would be "no")
2. If the answer to 1) is "no", is it planned for RC of .NET 8 and is there something I should try as a preview via reflection to give feedback?
3. If the answer to 2) is "no", do you have a milestone for it that are are allowed to communicate?

Thanks, Michael

**Comment by masonwheeler** [comment]
> If the answer to 1) is "no", is it planned for RC of .NET 8 and is there something I should try as a preview via reflection to give feedback?

I'll take this one step further.  I have relevant experience in implementing stuff like this.  Is there any way I can contribute to get this into .NET 8?  The community's been waiting 7 years for this feature already.  If I can keep from adding another whole year onto that total, I'd like to.

**Comment by AaronRobinsonMSFT** [comment]
> 1. Can we use AssemblyBuilder right now to persist runtime generated types, including their method bodies? (from reading https://github.com/dotnet/runtime/issues/62956#issuecomment-1644570818, the answer would be "no")

No.

> 2. If the answer to 1) is "no", is it planned for RC of .NET 8 and is there something I should try as a preview via reflection to give feedback?

Sadly no. It took  a substantial amount of time to detangle the current implementation and we are not up against the code complete time frame.

> 3. If the answer to 2) is "no", do you have a milestone for it that are are allowed to communicate?

This is likely a .NET 9 deliverable at the moment. There just hasn't been enough time for the team to make progress on it and handle the Reflection related work in flight.

>I'll take this one step further. I have relevant experience in implementing stuff like this. Is there any way I can contribute to get this into .NET 8? 

@masonwheeler I don't think we have the time this release, but I'll let @buyaa-n @steveharter or @jkotas comment specifically on whether help could change that calculus.

**Comment by MichaelKetting** [comment]
@AaronRobinsonMSFT Thank you for the answers! To me, the details on the updated milestones are very helpful :)

**Comment by buyaa-n** [comment]
Sorry seems my update was not clear about remaining work will not happen in .NET 8. I had mentioned it in the description:
Remaining work that out of .NET 8.0:

> Remaining work that out of .NET 8.0:
> - [ ]  Implement remaining parts needed for `AssemblyBuilder.Save(string/stream)` (mostly will rely on community contributions)
>   - [ ] ILGenerator implementation
>   - [ ] Add support for remaining members
>     - [ ] Add ConstructorBuilderImpl and save it to file/stream (this needs minimal IL support)
>     - [ ] Add PropertyBuilderImpl and save it to file/stream (this also needs minimal IL support)
>     - [ ] Add EventBuildterImpl and save it to file/stream
>     - [ ] Add implementation for remaining APIs for a MethodBuilder/TypeBuilder/FieldBuilder (like `SignatureCallingConvention`, `*RequiredCustomModifiers`, `*OptionalCustomModifiers`)
>   - [ ] Have an API for creating PDBs and implement it
>   - [ ] Entry point support

The above will be planned .NET 9

> I'll take this one step further. I have relevant experience in implementing stuff like this. Is there any way I can contribute to get this into .NET 8? The community's been waiting 7 years for this feature already. If I can keep from adding another whole year onto that total, I'd like to.

Thanks @masonwheeler, bare estimate of remaining work is listed above. You are welcome to contribute to any of those, though most of these needs IL support. Now we don't have a resource to put on this effort within .NET 8 timeframe. Therefore, I don't believe all of these could finish within .NET 8 timeframe with community contributions. Though your contribution could help the feature complete successfully in .NET 9

**Comment by masonwheeler** [comment]
@buyaa-n Where in the repo would I find the relevant work-in-progress?

Also, are you guys aware of [ILPack](https://github.com/Lokad/ILPack), which implements most of this already?  Have you looked at it and found any good reasons why its code couldn't be pulled into the Core codebase?  (I've tried using it and found it to be an imperfect replacement for `AssemblyBuilder.Save`.  It doesn't do everything, but it gets you about 85% of the way there.)

**Comment by buyaa-n** [comment]
> @buyaa-n Where in the repo would I find the relevant work-in-progress?

This issue is for tracking all relevant work and you can see relevant PRs linked to this issue. The last PR was https://github.com/dotnet/runtime/pull/88503

We are aware of ILPack and it is saves `Assembly` not `AssemblyBuilder`, `Module` not `ModuleBuilder` etc there is some similarity but not directly usable.

**Comment by leppie** [comment]
@buyaa-n thanks for the contribution. 

I think most people here are just interested in dumping runtime generated code. This does not mean the code has to to run when reloaded. We have the tools to inspect the IL. While falling back to .NET desktop is generally good enough, there are cases, it makes it impossible to debug codegen on .NET core. 

So, is it possible to dump some (possible malformed) IL to a stream for analysis?

**Comment by MSDN-WhiteKnight** [comment]
>So, is it possible to dump some (possible malformed) IL to a stream for analysis?

From within the process that generated it, or outside? If the latter, [ClrMD](https://github.com/microsoft/clrmd) could be used to inspect dynamic modules from external process, it represents them as ClrModule with IsDynamic property set to true. I have my project [CIL View](https://github.com/MSDN-WhiteKnight/CilTools#cilview) that attempts to implement viewing dynamic assemblies from external process, but it does not handle everything and it is not tested with newer CLR versions (only tested with .NET Core 3.1 as of now).

**Comment by buyaa-n** [comment]
> So, is it possible to dump some (possible malformed) IL to a stream for analysis?

We could consider adding a bare minimum (or empty) IL support within .NET 8 RC1 period (by August 14th). If a community willing to contribute, else currently we don't have a resource to work on it.

**Comment by buyaa-n** [comment]
Closing the issue, we will open a new issue(s) for remaining work for .NET 9 planning.

**Comment by markusschaber** [comment]
> > turn string into compiled program
> 
> use appropriate tool (Roslyn API)

How does the Roslyn API help with IronPython? (See https://github.com/IronLanguages/ironpython2/issues/351)

As far as I know, the Rosyln API is rather centric to C#, and does not support the different interpretations of the DLR needed by Python.

**Comment by markusschaber** [comment]
> Closing the issue, we will open a new issue(s) for remaining work for .NET 9 planning.

Could you link those new issues here, so we can follow them? Thanks!

**Comment by buyaa-n** [comment]
> Could you link those new issues here, so we can follow them? Thanks!

I will, when the issue(s) created.

**Comment by ForNeVeR** [comment]
My dear friends, I am extremely happy that this issue gets some traction, but I feel like it is getting a little bit mishandled.

Perhaps new issues should've been created _before_ we close the root one, that got a fair number of upvotes and people actually watching it?

And also, perhaps the issue that asks for working `AssemblyBuilder.Save()` should only be closed _after_ we get a working `AssemblyBuilder.Save()` in the public API? Even if we don't consider that the current solution doesn't yet cover all the use cases, it is only callable via reflection. While perfectly okay as a temporary measure, it shouldn't be considered as the target here.

**Comment by buyaa-n** [comment]
> Perhaps new issues should've been created before we close the root one, the one that got a fair number of upvotes and people actually watching it?
> 
> And also, perhaps the issue that asks for a working AssemblyBuilder.Save() should only be closed after we get a working AssemblyBuilder.Save() in the public API? Even if we ignore the fact that the current solution doesn't yet cover all the use cases, it is only callable via reflection. While perfectly okay as a temporary measure, it shouldn't be considered as the target here.

FYI the root issue is still open: https://github.com/dotnet/runtime/issues/15704, this was only for tracking the work for 8.0

**Comment by ForNeVeR** [comment]
Ah, I'm sorry, my bad then. Thanks for your work!

**Comment by buyaa-n** [comment]
> Could you link those new issues here, so we can follow them? Thanks!

UPDTE: we are making progress here, see the [Tracking issue for detail](https://github.com/dotnet/runtime/issues/92975)

**Comment by buyaa-n** [comment]
UPDATE: we are making a good progress:
- [x] Added ILGenerator implementation
- [x] Added support for remaining members
  - [x] ConstructorBuilderImpl
  - [x] PropertyBuilderImpl
  - [x] EventBuilderImpl
- [x] Added implementations for other unimplemented APIs in AssemblyBuilderImpl, TypeBuilderImp, MethodBuilderImpl
  - [ ] Still need to add a few APIs like `CreateGlobalFuntions`, `DefineGlobalMethod` etc. The work is in progress

Planning to finish the main functionality (excluding entry point and PDB) and [make related APIs public](https://github.com/dotnet/runtime/issues/83988) in preview 1. Here is the tracking issue for details: https://github.com/dotnet/runtime/issues/92975.

Now it would be great to test the implementation with a real-life scenario. I would really appreciate if you could:
- Prepare a simple app with your use case and share with me (in [this issue](https://github.com/dotnet/runtime/issues/92975) or email me)
- Dogfood the [daily build](https://github.com/dotnet/installer#installers-and-binaries) and try out the new AssemblyBuilder implementation yourself and give feedback. (The APIs are still internal so need to use reflection for now as [mentioned in the sample](https://github.com/dotnet/runtime/issues/15704#issuecomment-1644571703)). As this issue is closed please add your feedback in the [tracking issue](https://github.com/dotnet/runtime/issues/92975)

Thank you in advance!
