### ISSUE TITLE
JsonIgnore in record declaration

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/runtime#62961]
If we could use JsonIgnoreAttribute like this it could be very useful.
![image](https://user-images.githubusercontent.com/23618436/146584405-3e70fb2d-108a-4234-9bec-f4eb4c1198f2.png)

Thanks

**Comment by huoyaoyuan** [comment]
The exact same issue: #49212, and similar: #60690
I'm going to close this issue as the solution is straight. However, I think it's worth some hint by the IDE.
