### ISSUE TITLE
mscordbi.dll 4.700.21.56803 is missing from symbol servers.

### ISSUE THREAD

**Issue by feverline** [dotnet/runtime#62962]
similar to #62939 and #61775, I've been seeing this pretty regularly with different versions. Currently, I'm unable to debug a linux core dump running 4.700.2156803.  Also have had the same thing happen today with the newer 6.0.121.56705. 

Is there a reason why there are so many of these missing symbol issues lately?

![image](https://user-images.githubusercontent.com/95391846/146590560-43e91e26-aa16-4ebb-b297-a39e72ca6667.png)

**Reproduction Steps**
Try debugging a minidump from Linux running .NET 4.700.2156803 in Visual Studio -- open it and then try to start Managed Debugging.

**Expected behavior**
The debugging works as usual.

**Actual behavior**
The VS hangs with the message about mscordbi.dll not available (see Description above).

**Comment by arabelaa** [comment]
I tried to debug a minidump from Linux running .NET 6.0.21.52901 in Visual Studio 2022.
When opening the dump and using `Debug wih Managed Only` I received the error below.

![image](https://user-images.githubusercontent.com/4593697/146650031-d86cacc5-9dbe-492e-b148-0b2562de4b61.png)

**Comment by tommcdon** [comment]
Thanks for the feedback!  We've passed this feedback on to our infrastructure team who is investigating.

**Comment by hoyosjs** [comment]
This is release 3.1.22; There were issues in the indexing of the crossdac into the public symbol server which is now resolved.
