### ISSUE TITLE
Creating symbolic links without developer mode or elevation fails silently

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#62975]
Tested on Windows 10 21H1 19043 without Developer Mode with .NET 6 RTM; it does not throw.

_Originally posted by @wegylexy in https://github.com/dotnet/runtime/issues/57205#issuecomment-992636452_

cc @iSazonov @adamsitnik.

**Comment by Jozkee** [comment]
The Windows API [`CreateSymbolicLinkW`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw) is silently failing and we just return what the API reports. 

Posible options to deal with this:

* Contact Windows team and discuss if they can fix `CreateSymbolicLinkW`.

* After calling `FileSystemInfo link = File.CreateSymbolicLink("link", "target");`
Check `link.Exists` in order to verify that it was indeed created. This also works as a workaround for its current state.

* Is very likely that `CreateSymbolicLinkW` uses `DeviceIoControl`, we can investigate if using that function for symlink creation is more reliable.
As a side note: we already use on `FileSystemInfo.LinkTarget`.

**Comment by iSazonov** [comment]
If Windows team can not fix old (supported) Windows versions it is best to use DeviceIoControl and backport to .Net 6 as bug fix.

**Comment by wegylexy** [comment]
I have something on production that assumes it doesn't throw and checks for existence afterwards. A user reports it throws on Windows 7 when not run as admin.

**Comment by Jozkee** [comment]
@wegylexy @Raffaello I talked with the Windows team and they pointed out that the silent failure was due to an error on our side, so I fixed it in the main branch. Could you please help me validaiting the fix for your scenarios with a nightly build of .NET 7? That way, we can propose porting the fix to .NET 6.

Download the nightly build from https://github.com/dotnet/installer#table (column **main (7.0.x Runtime)**), download the version ad-hoc to your platform. 
Run your scenario targeting `net7.0`, and please let me know if it is now fixed.

**Comment by wegylexy** [comment]
@Jozkee We switched to use directory junction points and copying files instead, as typical users won't have developer mode enabled.
Now I just look forwards to QUIC datagram and NativeAOT in .NET 7.
So, I am going to just trust that you have fixed it.

**Comment by Raffaello** [comment]
@Jozkee ok, i will have a look, just need to find some times, hopefully i should hace some in the weekend.

**Comment by Raffaello** [comment]
with `.NET7-preview5` an exception has been thrown, so it fixes that doesn't silently failing. 
![image](https://user-images.githubusercontent.com/1850902/169271272-21ae44e9-5330-46e3-98e6-13096418a6b6.png)

test ref: https://github.com/BlueRedSkyLTD/PowerDir/blob/main/PowerDir.Tests/EscapeCodesThemesTest.cs#L116-L158
(`[TestMethod]`) is commented as it won't work as a test as requires dev/admin privileges to create a symlink

**Comment by Jozkee** [comment]
Thanks!
