### ISSUE TITLE
Performance optimization suggestion for Enum.Value.ToString()

### ISSUE THREAD

**Issue by VladimirKhvostov** [dotnet/runtime#62976]
### Description
Unfortunately, it is not the first time I see code like this:
```CSharp
public enum EncryptionStatus
{
    Enabled,
    Disabled
}
...

string someValue;
...
if (someValue == EncryptionStatus.Enabled.ToString())
{
}
```
instead of 
```CSharp
if (someValue == nameof(EncryptionStatus.Enabled))
{
}
```
The code generated in the first case can be optimized to generate the same code as in second case.

Example:
https://sharplab.io/#gist:88b14759ff454d97700a07c561df1e51

Alternatively, instead of optimizing code, it would be good to have a code analyzer for such code.

**Comment by svick** [comment]
I think this is a duplicate of https://github.com/dotnet/runtime/issues/57748.

**Comment by buyaa-n** [comment]
Closing as duplicate of #57748
