### ISSUE TITLE
Should there be more volatile in ConcurrentDictionary?

### ISSUE THREAD

**Issue by tfenise** [dotnet/runtime#62972]
In case `ConcurrentDictionary<,>.s_isValueWriteAtomic` is true, `ConcurrentDictionary<,>.Node._value` is not immutable, and is [read](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,438) and [written](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,605) without volatile. This sounds surprising to me. For example, the value could be a reference type, and one would expect that with a concurrent collection a new value is only published once all previous writes (such as to initialize the reference object) have been published as well.

Related: #30636

**Comment by stephentoub** [comment]
> This sounds surprising to me. For example, the value could be a reference type, and one would expect that with a concurrent collection a new value is only published once all previous writes (such as to initialize the reference object) have been published as well.

We've already had to pass appropriate barriers between the time the new value is created and the new value is stored into the destination. (Separate from the implementation detail that all reference writes to fields on coreclr are effectively volatile.)

**Comment by tfenise** [comment]
What about reading the value? So [here](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,438) the value is read and immediately the method returns. No barrier here.

**Comment by stephentoub** [comment]
What reordering are you concerned about there?

**Comment by tfenise** [comment]
I suppose in principle, volatile read and write should be used together.

**Comment by stephentoub** [comment]
> I suppose in principle, volatile read and write should be used together.

That's not how it works in general ;-) but even if it were,  as you pointed out,  neither the read nor wrote use volatile, so they're properly paired.

**Comment by tfenise** [comment]
After reading Node._value and returning to the user code, the user code may attempt to read from an instance field of the value. Without barrier, theoretically the CPU cache might happen to hold the outdated value of the field prior to the initialization.

**Comment by stephentoub** [comment]
Such reordering can't happen due to the data dependence between the reads.

**Comment by tfenise** [comment]
I don't think so. I suppose the CPU is allowed to load arbitrary data from cachable memory into the cache, even if not explicitly accessed by the program.

For example, consider:
1. Thread A allocates two small objects on the heap. The two small objects happen to be placed next to each other in memory.
2. Thread A initializes the first object and publishes it.
3. Thread B sees the first object published and reads its content. The CPU core running thread B may load all data adjacent to the first object into the cache, including the second object (cache line).
4. Thread A initializes the second object and publishes it.
5. Thread B sees the second object published and attempts to read its content, but its cache already contains the uninitialized content of the second object. Here a memory barrier is theoretically necessary so that thread B can read the actual published content of the second object.

**Comment by stephentoub** [comment]
I understand the scenario you're outlining, and I'm saying that even _if_ the hardware allowed for such a reordering, it's not a permissible sequence of events according to the memory model enforced by the runtime.  If it were, it'd be trivial to violate type and memory safety.

**Comment by tfenise** [comment]
Theoretically according to ECMA 335, "An optimizing compiler from CIL to native code is permitted to reorder code, provided that it guarantees both the single-thread semantics described in §I.12.6 and the cross-thread semantics of volatile operations." In addition, according to "I.12.6.8 Other memory model issues", the Execution Engine is allowed to convert type/memory safety errors due to lack of synchronization into non-fatal, non-corrupting, user-visible exceptions, which means that the EE doesn't have to enforce the memory order here and that the lack of barrier when reading could lead to an exception, although I understand that in practice, it may be an (expected) implementation detail that such reordering should not occur.

**Comment by stephentoub** [comment]
If it was possible, e.g., for thread A to publish an array _arr and for thread B to receive a valid reference to that array and upon accessing _arr.Length get some stale value unrelated to the actual array's length, that would trivially lead to corruption. That is not allowed.

**Comment by tfenise** [comment]
Strictly speaking, memory safety only requires the access to _arr.Length to be properly synchronized, not the content of _arr.

**Comment by krwq** [comment]
@tfenise, is there any specific issue you're seeing? I'd suggest to try to create a test, if you're assumptions are valid you should get relatively consistent repro given enough attempts to do unsafe operation.

**Comment by tfenise** [comment]
No specific issue. Currently it is only a theoretical problem. Unfortunately, I don't think I could create any repro on my x64 system considering the strong memory-ordering model.

**Comment by stephentoub** [comment]
> Currently it is only a theoretical problem

It's not even a theoretical problem.  As I noted,  the memory model provided by the runtime ensures this can't happen.

**Comment by krwq** [comment]
@tfenise my suggestion would be to close this issue as per @stephentoub the concerns don't seem like a problem. If you believe there is an issue please create a repro.

**Comment by KalleOlaviNiemitalo** [comment]
IIRC there was a blog post specifically about the weak memory model of Alpha AXP and how difficult it would be for .NET application developers if they did not get stronger guarantees. But the closest I can find now is <https://docs.microsoft.com/en-us/archive/blogs/cbrumme/memory-model>.

**Comment by vladd** [comment]
@stephentoub 
(Sorry for offtopic) Could you please give some (official) pointers, perhaps the specs, which guarantees that the scenarios like the one presented by @tfenise cannot even theoretically happen? I couldn't find the guarantee in the ECMA 335. [It's complicated to reason about the memory model issues without not having a reference document.] I couldn't even find the official guarantee that writes to the fields are volatile on coreclr.
(And where would this question be ontopic?)

**Comment by EgorBo** [comment]
I agree that it does look like .NET needs some better or more detailed write up to cover its Memory Model especially now when we have arm64 backend. Apart from the ECMA 355 spec there is a great blog post up by Joe Duffy http://joeduffyblog.com/2007/11/10/clr-20-memory-model/

> I couldn't even find the official guarantee that writes to the fields are volatile on coreclr.

For anything that you want to be volatile (aka "visible") you should use either `volatile` keyword or `Volatile.Read/Write` methods.

**Comment by vladd** [comment]
@EgorBo 
I understand that I need to mark as volatile everything that I need to be "visible", however @stephentoub mentioned above that the writes to the fields are volatile (this means release semantics, right?) in coreclr.
The discussion above mentions that (non-volatile) read of the data won't be reordered prior to the read of the reference to the data, because it's ensured by the runtine's memory model. In order to be able to reason and discuss the issue for us mere mortals, an authoritative source of the guarantees like these would be very helpful.

**Comment by alexrp** [comment]
> I couldn't find the guarantee in the ECMA 335.

Ecma 335, I.12.6.8:

```
A conforming implementation of the CLI shall ensure that, even in a multi-threaded environment
and without proper user synchronization, objects are allocated in a manner that prevents
unauthorized memory access and prevents invalid operations from occurring. In particular, on
multiprocessor memory systems where explicit synchronization is required to ensure that all
relevant data structures are visible (for example, vtable pointers) the Execution Engine shall be
responsible for either enforcing this synchronization automatically or for converting errors due to
lack of synchronization into non-fatal, non-corrupting, user-visible exceptions. 
```

This includes method table pointers, string length, array length(s), sync words (the backing for `lock`), etc.

(In regards to the last part of that paragraph, to my knowledge, all current Ecma 335 implementations just provide the guarantee rather than throw an exception.)

**Comment by tfenise** [comment]
Indeed, this guarantees the synchronization when accessing vtable pointers, array length, etc. (if one ignores the possibility of throwing an exception), but strictly speaking not necessarily when accessing plain user data, for example the content (not the length) of a `byte[]`.

As I said, I only suspect this problem in theory, not in practice. If in practice the lack of volatile memory access in `ConcurrentDictionary<,>` does not cause any problem, I think this issue can be closed, although another issue may be needed to discuss the .Net memory model generally in detail.
