### ISSUE TITLE
BitIncrement for Half handles negative values incorrectly

### ISSUE THREAD

**Issue by jnyrup** [dotnet/runtime#62988]
### Description

`IFloatingPoint<Half>.BitIncrement` and `IFloatingPoint<Half>.BitDecrement` handle negative values incorrectly.
Instead of incrementing (decrementing) the values, it decrements (increments) the value.

The cause seems to be checking if `ushort bits` is negative
https://github.com/dotnet/runtime/blob/a73d44f1009af7954df75e9923c64a3f10012004/src/libraries/System.Private.CoreLib/src/System/Half.cs#L920

### Reproduction Steps

```cs
using System;
using System.Runtime.Versioning;

[RequiresPreviewFeatures]
static T Decrement<T>(T x) where T : IFloatingPoint<T> => T.BitDecrement(x);

[RequiresPreviewFeatures]
static T Increment<T>(T x) where T : IFloatingPoint<T> => T.BitIncrement(x);

Console.WriteLine(Increment((Half)1)); // 1.001
Console.WriteLine(Increment((Half)(-1))); // -1.001

Console.WriteLine(Decrement((Half)1)); // 0.9995
Console.WriteLine(Decrement((Half)(-1))); // -0.9995
```

### Expected behavior

Incrementing -1 should be _larger_
Decrementing -1 should be _smaller_

### Actual behavior

Incrementing -1 is _smaller_
Decrementing -1 is _larger_

### Configuration

Version: newest main (a73d44f1009af7954df75e9923c64a3f10012004)

**Comment by hez2010** [comment]
> Instead of incrementing (decrementing) the values, it decrements (increments) the value.

That's not correct. 

The half floating point number `-1` has underlaying binary representation `1011110000000000`, bit-increment `1` will turn it to `1011110000000001` which is `-1.001`, while bit-decrement `1` will turn it to `1011101111111111` which is `-0.9995`.

**Comment by jnyrup** [comment]
The current behavior for `Half` is inconsistent with how `Math.BitIncrement` works and how it's documented to work.
 
> Returns the next largest value that compares greater than `x`.

https://docs.microsoft.com/en-us/dotnet/api/system.math.bitincrement?view=net-6.0

So the_value_ must be incremented, which for negative values means the bit representation must decremented.

**Comment by skyoxZ** [comment]
> > Returns the next largest value that compares greater than `x`.
> 
> https://docs.microsoft.com/en-us/dotnet/api/system.math.bitincrement?view=net-6.0
Another issue: the doc is incorrect. `Math.BitIncrement` should return the next **_smallest_** value that compares greater than `x`.

**Comment by tannergooding** [comment]
PRs are welcome to improve the docs: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Math.xml
