### ISSUE TITLE
Channel<T>.Reader.ReadAllAsync() may make memory leak

### ISSUE THREAD

**Issue by paxhujing** [dotnet/runtime#63006]
### Description

the ReadAllAsync() state machine generate a field called ' _current',it saved the last item that dequeued. 

### Reproduction Steps

use ReadAllAsync() read all items from channel

### Expected behavior

after read all items,no any root inside state machine to keep last item

### Actual behavior

the field '_current' of ReadAllAsync() state machine is the only root of last item

### Other information

![image](https://user-images.githubusercontent.com/13563757/146740231-46de72ad-8d89-41a7-a47f-445833f025f5.png)

**Comment by huoyaoyuan** [comment]
This is the standard code generation for `IAsyncEnumerable`. When you are done with the iteration, the `_current` field should be set to null and doesn't reference anything.

**Comment by huoyaoyuan** [comment]
The generated state machine does not set the field to null after the end of iteration. This is not specific to this method. You can propose a code generation change at https://github.com/dotnet/roslyn

**Comment by hez2010** [comment]
I also encountered the same issue. I've fired an issue in Roslyn repo: https://github.com/dotnet/roslyn/issues/58444

**Comment by buyaa-n** [comment]
Closing the issue as it is not actionable in runtime and no need to transfer as it is already reporting in roslyn
