### ISSUE TITLE
EventSource_SuccessfulHandshake_LogsStartStop failures on Windows11

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#63008]
Impacted test: `EventSource_SuccessfulHandshake_LogsStartStop`

We throw a `[SkipTestException]` from an inner call to `SslStream_StreamToStream_Authentication_Success` (#59135):
https://github.com/dotnet/runtime/blob/e8343ee9ce107a419cf201a63d64ce2a58d2d80d/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs#L53

But it looks like it's not being propagated because of `RemoteExecutor`:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62870-merge-83671b73f8b34d3085/System.Net.Security.Tests/2/console.ae014fcd.log?sv=2019-07-07&se=2022-01-06T22%3A03%3A15Z&sr=c&sp=rl&sig=baGyxGNbdVauzUOgTjrUPFOLeR4fZlOgkWOSBATBEBs%3D

I don't understand why is this failure intermittent.

**Comment by karelz** [comment]
Triage: We now disabled the inner test via SkipTestException on Win11 and we should deal with that reasonably in this test.

**Comment by wfurt** [comment]
The `SkipTestException` is processed by our custom extension inside xUnit. When used within `RemoteExecutor` it will throw and kill the process on unhandled exception. 
If the test is supposed to be skipped it needs to be done _before_ or _outside_ of the remote exec.

**Comment by wfurt** [comment]
BTW as the last part @antonfirsov: that test depends on timing and it is not deterministic. I know @MihaZupan put in some effort to make this more stable but I'm not sure if we can really make 100% reliable. Perhaps inject some EOF sentinel and wait with asserts until we get it.
