### ISSUE TITLE
JwtSecurityTokenHandler token expiration date validation fails if date more than 25 years

### ISSUE THREAD

**Issue by yoyrandao** [dotnet/runtime#63001]
### Description

`JwtSecurityTokenHandler.ValidateToken` fails on expire date validation if it is more than 25 years.

Reproduces on .NET 6 with more than 25 years expiration dates. On .NET 5 fails around dates with 100 years more than now.

### Token issuing
```csharp
	var tokenDescriptor = new SecurityTokenDescriptor
	{
		Subject = new ClaimsIdentity(new Claim[]
		{
			new(ClaimTypes.NameIdentifier, /* some data */)
		},
		Expires = DateTime.UtcNow.AddYears(26 /* or other number more than 25 years on .NET 6 */),
                /* signing key, issuer, etc */
	};
```

### Token validation
```csharp
identity = tokenHandler.ValidateToken(jwtToken, new TokenValidationParameters
{
	ValidateAudience = false,
	ValidateIssuer = true,
	ValidateLifetime = true,
	ValidateIssuerSigningKey = true,
	IssuerSigningKey = new SymmetricSecurityKey(signingKey)
}, out _);
```

### Issued token (from jwt.io)
![image](https://user-images.githubusercontent.com/35937082/146694335-4159e99a-a720-4f11-8d65-73956b34a053.png)

### Expected behavior

Validation must be successful.

### Actual behavior

Validation code above throws `SecurityTokenNoExpirationException` with message `IDX10225: Lifetime validation failed. The token is missing an Expiration Time. Tokentype: 'System.String'.`.

### Configuration

**SDK**: .NET 6 (but bug can be reproduced on .NET 5 and further)
**OS**: Windows 11 21H2 x64 (22000.376)

**Comment by danmoseley** [comment]
Hello, can you please clarify whether the behavior exists in 5.0, what does the exact same code do in 5.0?

Linking this here

https://stackoverflow.com/questions/43962567/jwt-token-exception-in-asp-net-lifetime-validation-failed-the-token-is-missing#46655014

https://stackoverflow.com/questions/43593074/jwt-validation-fails/46654832#46654832

**Comment by vcsjones** [comment]
I'm unable to reproduce this. Here is a fully running example:

```csharp
using System;
using System.Security.Claims;
using System.Threading;
using Microsoft.IdentityModel.Tokens;
using Microsoft.IdentityModel.JsonWebTokens;

static class Program {
    static unsafe void Main()
    {
        byte[] signingKey = new byte[32];
        SecurityTokenDescriptor tokenDescriptor = new SecurityTokenDescriptor {
            Subject = new ClaimsIdentity(new Claim[] {
                new Claim(ClaimTypes.NameIdentifier, "kartoshka")
            }),
            Expires = DateTime.UtcNow.AddYears(100),
            Issuer = "vcsjones",
            SigningCredentials = new SigningCredentials(
                new SymmetricSecurityKey(signingKey),
                SecurityAlgorithms.HmacSha256),
        };

        JsonWebTokenHandler handler = new();
        string token = handler.CreateToken(tokenDescriptor);

        Console.WriteLine(token);

        TokenValidationResult result = handler.ValidateToken(token,
            new TokenValidationParameters {
                ValidateAudience = false,
                ValidateIssuer = true,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true,
                ValidIssuers = new string[] { "vcsjones" },
                IssuerSigningKey = new SymmetricSecurityKey(signingKey)
            }
        );

        Console.WriteLine(result.IsValid);
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.15.0" />
  </ItemGroup>
</Project>
```

For me, this prints "true" at the end with an expiration 100 years in the future.

Can you share a complete code example that reproduces the issue, including the .csproj?

**Comment by yoyrandao** [comment]
@vcsjones, my fault, i did not paste a token handler type 😅

I am using `JwtSecurityTokenHandler`, not `JsonWebTokenHandler`. Have you tried to reproduce this with `JwtSecurityTokenHandler`?

**Comment by vcsjones** [comment]
@yoyrandao Thanks for the update. I can reproduce the behavior, but I don't see a difference between .NET 5 and .NET 6.

> Reproduces on .NET 6 with more than 25 years expiration dates. On .NET 5 fails around dates with 100 years more than now.

Given that, I would expect 75 years to fail on .NET 6, and work on .NET 5. However when I try it, it fails for both:

![image](https://user-images.githubusercontent.com/361677/147098229-0d1c1179-d414-489a-9bae-adb323942049.png)

Based on your description, it sounds like this is failing right around the Unix Epoch 32-bit overflow, the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem). Indeed, this seems to be the case. This will work:

```csharp
DateTime unixEpoch = new(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
byte[] signingKey = new byte[32];
SecurityTokenDescriptor tokenDescriptor = new() {
    Subject = new ClaimsIdentity(new Claim[] {
        new Claim(ClaimTypes.NameIdentifier, "Kevin")
    }),
    Expires = unixEpoch.AddSeconds(int.MaxValue),
    Issuer = "vcsjones",
    SigningCredentials = new SigningCredentials(
        new SymmetricSecurityKey(signingKey),
        SecurityAlgorithms.HmacSha256),
};

JsonWebTokenHandler handler = new();
string token = handler.CreateToken(tokenDescriptor);
```

and this won't:

```csharp
DateTime unixEpoch = new(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
byte[] signingKey = new byte[32];
SecurityTokenDescriptor tokenDescriptor = new() {
    Subject = new ClaimsIdentity(new Claim[] {
        new Claim(ClaimTypes.NameIdentifier, "Kevin")
    }),
    Expires = unixEpoch.AddSeconds(int.MaxValue).AddSeconds(1),
                                              // ^ Overflow unix epoch
    Issuer = "vcsjones",
    SigningCredentials = new SigningCredentials(
        new SymmetricSecurityKey(signingKey),
        SecurityAlgorithms.HmacSha256),
};
```

Essentially, `JsonWebTokenHandler` can't handle an `exp` larger than `int.MaxValue`.

I don't know enough about the internals of `JsonWebTokenHandler` to say exactly where the problem lies. You may be able to get better help in the https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet repo, where `JsonWebTokenHandler` lives.

Can you confirm my findings, that the behavior is not dependent on the .NET version? If you are still able to reproduce differing behavior between .NET 5 and .NET 6, can you adapt my example below to reproduce the issue?

Here is the complete code I used to reproduce my findings:

```csharp
using System;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;
using Microsoft.IdentityModel.JsonWebTokens;
using System.IdentityModel.Tokens.Jwt;

static class Program {


    static void Main()
    {
        DateTime unixEpoch = new(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        RunExample(unixEpoch.AddSeconds(int.MaxValue));
        Console.WriteLine("-------------");
        RunExample(unixEpoch.AddSeconds(int.MaxValue).AddSeconds(1));

        static void RunExample(DateTime expires)
        {
            Console.WriteLine($"Expires: {expires}");
            byte[] signingKey = new byte[32];
            SecurityTokenDescriptor tokenDescriptor = new() {
                Subject = new ClaimsIdentity(new Claim[] {
                    new Claim(ClaimTypes.NameIdentifier, "Kevin")
                }),
                Expires = expires,
                Issuer = "vcsjones",
                SigningCredentials = new SigningCredentials(
                    new SymmetricSecurityKey(signingKey),
                    SecurityAlgorithms.HmacSha256),
            };

            JsonWebTokenHandler handler = new();
            string token = handler.CreateToken(tokenDescriptor);

            JwtSecurityTokenHandler validationHandler = new();

            try
            {
                ClaimsPrincipal result = validationHandler.ValidateToken(token,
                    new TokenValidationParameters {
                        ValidateAudience = false,
                        ValidateIssuer = true,
                        ValidateLifetime = true,
                        ValidateIssuerSigningKey = true,
                        ValidIssuers = new string[] { "vcsjones" },
                        IssuerSigningKey = new SymmetricSecurityKey(signingKey)
                    }, out SecurityToken securityToken
                );

                Console.WriteLine($"Token is valid and expires at {securityToken.ValidTo}");
            }
            catch
            {
                Console.WriteLine("Could not validate token.");
            }
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="6.15.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.0" />
  </ItemGroup>
</Project>
```

Run: `dotnet run --framework net6.0`, `dotnet run --framework net5.0`

**Comment by yoyrandao** [comment]
@vcsjones yeah, I can confirm. I test it again ang get the same result. Thanks for helping me, my solution is using `JsonWebTokenHandler` instead of `JwtSecurityTokenHandler`. Thanks a lot!

**Comment by vcsjones** [comment]
Looks like this has previously been reported here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/92

**Comment by bartonjs** [comment]
Since the class with the issue is in a different repository, and they already have an issue for it, closing this one.
