### ISSUE TITLE
[API Proposal]: Provide public OOB converters for System.Text.Json

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#63039]
### Background and motivation

`Newtonsoft.Json` has a bunch of built-in converters, so it's easy to (de)serialize JSON that doesn't exactly match with C# model: https://github.com/JamesNK/Newtonsoft.Json/tree/master/Src/Newtonsoft.Json/Converters

`System.Text.Json` also has OOB converters, but they are for internal use: https://github.com/dotnet/runtime/tree/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters

I currently need a UNIX Timestamp to `DateTime` converter (which I assume is a pretty common need), and turns out it's not available out of the box (like in aforementioned `Newtonsoft.Json` https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/UnixDateTimeConverter.cs). 

Yes, it's not that hard to implement, but having it be part of `System.Text.Json` would result in a way better experience.

### API Proposal

```C#
namespace System.Text.Json.Serialization.Converters;

public class UnixDateTimeConverter : JsonConverter<DateTime>
{
    //...
}
```

### API Usage

```C#
[JsonConverter(typeof(UnixDateTimeConverter))]
[JsonPropertyName("timestamp")]
public DateTime Sent { get; init; }
```

### Alternative Designs

Implement them manually every time, or wrap them in third-party NuGet

**Comment by layomia** [comment]
This proposal seems to be asking for multiple things

- Expose the internal primitive System.Text.Json converters
- Provide a new `DateTime` converter that supports the UNIX timestamp format.

Neither of these is on the roadmap for System.Text.Json. The converters are simple enough in their implementation to be copied inline in custom converters & can already be fetched via `JsonSerializerOptions.GetConverter` and also via `System.Text.Json.Serialization.Metadata.JsonMetadataServices.DateTimeConverter` and co (if you really need this functionality).

We've provided an example in our documentation for supporting the UNIX format which can be added to projects as needed - https://github.com/dotnet/runtime/issues/29975.
