### ISSUE TITLE
Opportunities to improve TE Platform-Plaintext benchmark

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#63059]
Platform-Plaintext TechEmpower Benchmark where dotnet shows impressive results ([2nd place](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext), up to ~12.4mln requests per second (RPS) on our PerfLab hardware with bigger network bandwidth) seems to be slightly bottlenecked by three `SpanHelpers.IndexOf[Any]` functions:
![image](https://user-images.githubusercontent.com/523221/147016152-d1da2f2b-cedc-4985-8831-a70ca5d07fe7.png)
![image](https://user-images.githubusercontent.com/523221/147420670-65cb3546-1616-4d26-962d-493fdeb9c81b.png)

_^ Linux-x64_

e.g. `IndexOfAny(val0, val1)` mostly tries to find `\n` or `\r` in ASCII strings of length = 26, 49 and 151 where needed symbols usually found at positions 21, 22 and 100 (http headers)
```
Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7
Host: 10.0.0.102:5000
Connection: keep-alive
```
```
Host: 10.0.0.102:5000
Connection: keep-alive
```
```
Connection: keep-alive
```

I [tried](https://github.com/EgorBo/runtime-1/commit/b2ee6ad589e0c8d6f495876d8a1f965770243896) to rewrite them by hands e.g. I changed some branches, removed "Duff's devices", added "two 256bit vectors per iteration" path. Here is a [standalone benchmark](https://gist.github.com/EgorBo/1d059726dae285e3a1db501896e8a1bd) project with test data extracted from the Platform-Plaintext benchmark.

As the result, I constantly see stable improvements around 1-3% (never slower):
```
| load                   | base        | my          |         |
| ---------------------- | ----------- | ----------- | ------- |
| CPU Usage (%)          |          96 |          97 |  +1.04% |
| Cores usage (%)        |       2,702 |       2,726 |  +0.89% |
| Working Set (MB)       |          37 |          37 |   0.00% |
| Private Memory (MB)    |         370 |         370 |   0.00% |
| Start Time (ms)        |           0 |           0 |         |
| First Request (ms)     |          77 |          75 |  -2.60% |
| Requests/sec           |  12,403,854 |  12,679,971 |  +2.23% |
| Requests               | 187,261,280 | 191,437,425 |  +2.23% |
| Mean latency (ms)      |        1.18 |        1.31 | +11.02% |
| Max latency (ms)       |       56.19 |       53.21 |  -5.30% |
| Bad responses          |           0 |           0 |         |
| Socket errors          |           0 |           0 |         |
| Read throughput (MB/s) |    1,495.04 |    1,525.76 |  +2.05% |
| Latency 50th (ms)      |        0.66 |        0.63 |  -3.95% |
| Latency 75th (ms)      |        0.99 |        0.95 |  -4.04% |
| Latency 90th (ms)      |        1.83 |        2.00 |  +9.29% |
| Latency 99th (ms)      |       15.86 |       15.82 |  -0.25% |
```
^ with PGO. As you can see from https://aka.ms/aspnet/benchmarks (17th page, "full" checked) the best results we've ever seen were 12.42M RPS so 12.68M does look like an improvement:

![image](https://user-images.githubusercontent.com/523221/147086940-31e97b21-3bfe-4cad-ab3a-56ef0c0853c6.png)

Same relative improvements can be observed in non-PGO mode (default).

Here is the script I used to benchmark it:
```
for (;;) { crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/platform.benchmarks.yml --scenario plaintext --profile aspnet-citrine-lin --application.framework net7.0 --application.options.outputFiles C:\prj\WSL\x64\base\*.* --json t1.json ;; crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/platform.benchmarks.yml --scenario plaintext --profile aspnet-citrine-lin --application.framework net7.0 --application.options.outputFiles C:\prj\WSL\x64\diff\*.* --json t2.json ;; crank compare t1.json t2.json }
```
Standalone benchmark: https://gist.github.com/EgorBo/1d059726dae285e3a1db501896e8a1bd
Commit in dotnet/runtime: https://github.com/EgorBo/runtime-1/commit/b2ee6ad589e0c8d6f495876d8a1f965770243896

/cc @stephentoub @GrabYourPitchforks

**Comment by danmoseley** [comment]
Is it possible that this could regress workloads that don't look like this one? Did you get a chance to run the IndexOf/IndexOfAny benchmarks in dotnet/performance (not sure how good they are but they're there)

**Comment by EgorBo** [comment]
> Is it possible that this could regress workloads that don't look like this one? Did you get a chance to run the IndexOf/IndexOfAny benchmarks in dotnet/performance (not sure how good they are but they're there)

Yes, it's always about trade-offs, but what I'm 100% sure in that we can add a "two 256bit vectors per iteration" path for arrays >= 32 elements (bytes) without hurting other cases https://gist.github.com/EgorBo/1d059726dae285e3a1db501896e8a1bd#file-faster_spanhelpers_indexof-cs-L148-L186.

**Comment by EgorBo** [comment]
Also, it seems there are optimization opportunities inside the caller of that IndexOfAny - ParseHeaders
we can try to detect `:` as we search for `\r` or `\n`

**Comment by stephentoub** [comment]
> but what I'm 100% sure in that we can add a "two 256bit vectors per iteration" path

I thought we were on a path/plan to switch to using Vector128 in all of these implementations. Is that not the case, @tannergooding?

**Comment by EgorBo** [comment]
Is there a real reason? 
E.g. as we recently found out with Tanner that if you want to compare two strings e.g. `"Proxy-Authenticate"` (36 bytes) - it's faster to do it via two 256bit vectors than via three 128bit ones.

Also, I believe all the instructions involved don't cause downlclocking (PL0 aka Power License 0) especially on newer CPUs where all avx2 instructions don't do it.

Finding the end-line symbol in this header:
```
Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7
```
is twice slower with SSE.

**Comment by EgorBo** [comment]
All-time record: `Requests/sec           | 12,817,887  |`
Without AVX (probably you were right or it's our Xeon downlocking), optimized for benchmark input.
Wonder if we can use PGO here. e.g. record typical "return value" from IndexOf in tier0 and then insert a more optimized IndexOf in tier1.

**Comment by EgorBo** [comment]
Faster "ParseHeaders" for Kestrel: https://gist.github.com/EgorBo/3bf1863a27bfe105054bf9f2cd6c70ef
Adds ~200.000 RPS 
As I said, the default one walk span several times to find ":" and CLRF + validation while I try to do it in a single SIMD-ifed pass.

**Comment by EgorBo** [comment]
Moved to dotnet/aspnet as a PR https://github.com/dotnet/aspnetcore/pull/39216
