### ISSUE TITLE
string.IsNullOrWhitespace nullable annotation

### ISSUE THREAD

**Issue by badcel** [dotnet/runtime#63066]
In dotnet 6.0 there is a nullability warning emitted (CS8603) for this console application because the  `GetNonNullableString` method may return null, which is not true.

```cs
Console.WriteLine(GetNonNullableString());

string GetNonNullableString()
{
    var str = GetNullableString();
    
    return string.IsNullOrWhiteSpace(GetNullableString())
        ? "NullOrWhitespace"
        : str;
}

string? GetNullableString()
{
    return null;
}
```

I wonder if I'm missing something very obvious?

**Comment by dzsibi** [comment]
Call IsNullOrWhiteSpace with `str`, not with `GetNullableString()`.

**Comment by badcel** [comment]
Urgs, sorry obviously the code is wrong.

Thanks to your answer I found the root of my problem. We are crosscompiling .NET 6 / .NET framework and for .NET Framework the annotation is obviously missing and a warning is emitted, which is correct.
