### ISSUE TITLE
Logging - inject custom fields into console logger (json) via DI 

### ISSUE THREAD

**Issue by Bjego** [dotnet/runtime#63068]
Hey guys,
I'm checking how I can replace Nlog with the Microsoft.Extensions.Logging libs. I think it's great that I can just switch between "default" and "json" logger with just an environment variable. This feature is great especially as we are using the kubernetes splunk appender to send our logs to a splunk.

Unfortunally the much more detailed logs of the json-formatter don't include the traceid from the http-request in asp.net core. I'd like to write just a tiny class which I can inject into the jsonformatter to add that property. Maybe something like this:
```csharp
public CustomJsonConsoleFormatterProperty : JsonConsoleFormatterProperty
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public JsonConsoleFormatterProperty(IHttpContextAccessor accessor){
        _httpContextAccessor = accessor
    }

    protected override void AppendProperty(Utf8JsonWriter writer){
         writer.WriteString("CustomProperty", _httpContextAccessor.HttpContext?.User?.Identity?.Name);
    }
}
```

External logging libs like serilog and nlog would be superflouus for many customers then.
Guess a good startingpoint would be:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/JsonConsoleFormatter.cs

Thanks in advance and merry crhistmas!

**Comment by Bjego** [comment]
In the end I just want to log the traceId of the http_context and maybe the userId but this isn't required. In a multi user context with parallel access - logs without the traceid aren't really usefull

**Comment by maryamariyan** [comment]
Regarding trace Id I also have this sample using `OpenTelemetry` and `AddConsoleExporter` API:
https://github.com/maryamariyan/LoggingWithMinimalApi/blob/main/Program.cs#L16

**Comment by maryamariyan** [comment]
Perhaps you can use _Custom Console Log Formatter_ to inject additional properties. Link to docs: https://docs.microsoft.com/en-us/dotnet/core/extensions/console-log-formatter#implement-a-custom-formatter

**Comment by Bjego** [comment]
@maryamariyan thanks for all those hints. If I would write my own formatter - whats the best practise to access the current http context ( in an web api .net5 or .net 6) ? When I'm stuck in my Write method - I've inspected several log messages and it doesn't seem to be that easy? Especially as the formatter is registrerd as scoped or singleton - I think. 

I tried to create my own minimal consoleformatter:
```
 public class CustomLogFormatterOptions : ConsoleFormatterOptions
    {

    }

    public class CustomLogFormatter : ConsoleFormatter
    {
        public CustomLogFormatter(IOptionsMonitor<CustomLogFormatterOptions> options) : base(nameof(CustomLogFormatter))
        {
        }

        public override void Write<TState>(in LogEntry<TState> logEntry, IExternalScopeProvider scopeProvider, TextWriter textWriter)
        {
            if (logEntry.Exception is null)
            {
                // return;
            }


            string message =
                logEntry.Formatter(
                    logEntry.State, logEntry.Exception);

            if (message == null)
            {
                return;
            }
            var log = new
            {
                Message = message
            };
            textWriter.WriteLine(JsonSerializer.Serialize(log));
        }
    } 
```
From Program.cs
```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                })
                .ConfigureLogging(logging =>
                  {
                      logging.ClearProviders();
                      logging.Configure(c =>
                      {

                          c.ActivityTrackingOptions = ActivityTrackingOptions.TraceId | ActivityTrackingOptions.SpanId | ActivityTrackingOptions.ParentId | ActivityTrackingOptions.TraceState | ActivityTrackingOptions.TraceFlags;
                      });
                      logging.AddConsole().AddConsoleFormatter<CustomLogFormatter, CustomLogFormatterOptions>();
                  });
```
Appsettings:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "System.Net.Http": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.EntityFrameworkCore.Database.Command": "Information",
      "Microsoft.AspNetCore.Hosting.Diagnostics": "Information"
    },
    "Console": {
      "FormatterName": "CustomLogFormatter",
      "FormatterOptions": {
        "IncludeScopes": true,
        "SingleLine": true,
        "UseUtcTimestamp": true
      }
    }
```
