### ISSUE TITLE
immutable records can be changed via reflection

### ISSUE THREAD

**Issue by C0DK** [dotnet/runtime#63077]
### Description

I started using Dotnet 6 and wanted to use these lovely immutable records. We, however, verify that all our property setters have guard clauses - and when running these, these records threw an error - that's weird. Records are immutable, so guard clauses shouldn't be needed.

I tried looking through exactly how we test guard clauses and found that you can change the values through reflection. (see the unit test) 

I'm not sure if this is a known bug, but it seems problematic. 

### Reproduction Steps

Running the following NUnit test reproduces the error: (should be easy to re-create in another testing framework). 

```CSharp
using System.Linq;
using NUnit.Framework;

namespace Solid
{
    [TestFixture]
    public class DotnetBugTests
    {
        private record SomeRecord(string Foo){}
        
        [Test]
        public void Test_CanEditRecords()
        {
            const string initialValue = "foo";
            const string newValue = "bar";

            var someRecord = new SomeRecord(initialValue);
            var properties = typeof(SomeRecord).GetProperties();

            var property = properties.First();
            property.SetValue(someRecord, newValue);
            
            Assert.That(someRecord.Foo, Is.EqualTo(newValue));
        }
    }
}

```

### Expected behavior

Non-immutability.

### Actual behavior

immutability through

### Known Workarounds

Currently, I'll just eliminate the tests regarding records. I cannot build my code when setting the values directly, so it shouldn't be a problem; however, it could be problematic in the correct setting. 

### Configuration

Dotnet 6.0

### Other information

One could also just patch PropertyInfo to fix this - I'm not entirely sure how PropertyInfo does its magic under the hood.

### Tags
area-System.Reflection

**Comment by C0DK** [comment]
Is this how you add labels?

area-System.Reflection

**Comment by C0DK** [comment]
I'll just try to tag you to make sure I am doing it correctly: @buyaa-n @joperezr @steveharter

**Comment by EgorBo** [comment]
With reflection you can do a lot of evil things if you want, e.g. call static constructor twice, etc.

**Comment by C0DK** [comment]
Sure but that seems like a bug in the implementation somewhere. I can create an actual immutable class manually, yet I cannot via records directly:

```csharp
using System.Linq;
using NUnit.Framework;

namespace Solid
{
    [TestFixture, Description("If these test fails, we can check guard clauses on records again")]
    public class DotnetBugTests
    {

        [Test,]
        public void Test_CanEditRecords()
        {
            const string initialValue = "foo";
            const string newValue = "bar";

            var someRecord = new SomeRecord(initialValue);
            var properties = typeof(SomeRecord).GetProperties();

            var property = properties.First();
            property.SetValue(someRecord, newValue);

            Assert.That(someRecord.Foo, Is.EqualTo(newValue));
        }

        [Test]
        public void Test_CanEditInits()
        {
            const string initialValue = "foo";
            const string newValue = "bar";

            var sut = new SomeClass { Foo = initialValue };
            var properties = typeof(SomeClass).GetProperties();

            var property = properties.First();
            property.SetValue(sut, newValue);

            Assert.That(sut.Foo, Is.EqualTo(newValue));
        }
        
        [Test]
        public void Test_CanEditPrivateField()
        {
            const string initialValue = "foo";
            const string newValue = "bar";

            var sut = new SomeClass { Foo = initialValue };
            var properties = typeof(SomeClass).GetProperties();

            var property = properties[1];

            Assert.That(() => property.SetValue(sut, newValue), Throws.ArgumentException);
        }
    }
    public record SomeRecord(string Foo) { }

    public class SomeClass
    {
        public SomeClass()
        {
            Bar = "teeeest";
        }
        public string Foo { get; init; }
        public string Bar { get; }
    }
}
```

**Comment by omariom** [comment]
Reflection should be considered the same as unsafe. A bit milder but still

**Comment by vshapenko** [comment]
> Reflection should be considered the same as unsafe. A bit milder but still

But, in case described above, private field in SomeClass has proper behaviour, whilst SomeRecord not

**Comment by C0DK** [comment]
Also it won't be a problem for readonly structs, for obvious reasons, yet it decreases the comparison between the two, that the otherwise lovely documentation has.

**Comment by vcsjones** [comment]
What are your expectations for immutability and reflection? In the non-record case of `SomeClass`, the backing field can still be set via reflection, it just requires going around to the backing field instead.


```csharp
using System;
using System.Reflection;

SomeClass sc = new() { Foo = "foo" };

ForceSetProperty(sc, nameof(sc.Bar), "reflection");
ForceSetProperty(sc, nameof(sc.Foo), "rocks!");

Console.WriteLine($"Bar: {sc.Bar}");
Console.WriteLine($"Foo: {sc.Foo}");



static void ForceSetProperty(object obj, string propertyName, object newValue)
{
    string backingFieldName = $"<{propertyName}>k__BackingField";
    FieldInfo f = obj.GetType().GetField(backingFieldName, BindingFlags.Instance | BindingFlags.NonPublic);
    f.SetValue(obj, newValue);
}

public class SomeClass
{
    public SomeClass()
    {
        Bar = "teeeest";
    }
    public string Foo { get; init; }
    public string Bar { get; }
}
```

Output:

>Bar: reflection
>Foo: rocks!

**Comment by omariom** [comment]
> But, in case described above, private field in SomeClass has proper behaviour, whilst SomeRecord not

SomeClass.Bar  doesn't have a property setter, so Reflection just can't call it. 
SomeClass.Foo has one. And as that ```init;``` thing is a C# construct, it's a public property setter for Reflection, which is a part of Runtime.

**Comment by C0DK** [comment]
It might be a feature that reflection just doesn't follow the rules, yet I see for similar cases (i.e readonly) reflection has been set to respect the rules (see https://github.com/dotnet/runtime/issues/11571 )

**Comment by stephentoub** [comment]
> yet I see for similar cases (i.e readonly) reflection has been set to respect the rules (see #11571 )

Only for static readonly. Instance readonly fields are still settable, as is demonstrated in @vcsjones' example above,  where the backing field for the get-only auto prop is readonly.

**Comment by C0DK** [comment]
valid. :) I am not aware of the full intention behind reflection :) again, if it's a feature, I accept that and will have to navigate my way around it. 

> > yet I see for similar cases (i.e readonly) reflection has been set to respect the rules (see #11571 )
> 
> Only for static readonly. Instance readonly fields are still writeable via reflection, as is demonstrated in @vcsjones' example above, where the backing field for the get-only auto prop is readonly.


Valid - and again, I accept that it might be a feature, and then I'll navigate around it to the best of my ability.

**Comment by vcsjones** [comment]
> I see for similar cases (i.e readonly) reflection has been set to respect the rules (see #11571 )

My understand of that particular case is it was done to align reflection with the rules of the JIT because the JIT may burn-in static readonly values, not to have reflection obey accessibility rules that the compiler must follow. To me, as evidence of `BindingFlags.NonPublic`, reflection is purpose-built to allow ignoring member accessibility. At least where it's behavior is predictable. In the case of `static readonly`, the behavior is not predictable, so it was disallowed.

**Comment by SingleAccretion** [comment]
> My understand of that particular case is it was done to align reflection with the rules of the JIT because the JIT may burn-in static readonly values, not to have reflection obey accessibility rules that the compiler must follow.

Right. In other words, the guarantee that `static readonly` fields will change their values after initialization enables a very important optimization that a lot of code out there relies on.

Making the same guarantee for instance fields will be beneficial, however, it will not enable something new (the same effect can always be achieved by storing the field into a local).

That aside, it would be a large breaking change, and it is my understanding that the C# compiler has already taken dependency a on being able to set `initonly` instance fields, no reflection required:
```cs
public class C {
    public int A { get; init; }
}
```
```cs
.field private initonly int32 '<A>k__BackingField'

.method public instance void modreq([System.Private.CoreLib]System.Runtime.CompilerServices.IsExternalInit) set_A (
        int32 'value'
    )
{
    .custom instance void [System.Private.CoreLib]System.Runtime.CompilerServices.CompilerGeneratedAttribute::.ctor() = (
        01 00 00 00
    )

    ldarg.0
    ldarg.1
    stfld int32 C::'<A>k__BackingField' // "stfld" - used on an "initonly" field
    ret
}
```

**Comment by jkotas** [comment]
It is by design that reflection does not respect visibility and readonly rules. Changing it would be a major breaking change. A lot of code out there depends on it.

**Comment by C0DK** [comment]
Valid! I'll find ways to change my tests instead :)
