### ISSUE TITLE
.NET 7 target, .NET 6 docs

### ISSUE THREAD

**Issue by AlmightyLks** [dotnet/runtime#63090]
When cloning this repository locally and opening some project, I can see that all projects have been targeted at .NET 7, as also mentioned [here](https://github.com/dotnet/announcements/issues/198).  

However, [the guidance](https://github.com/dotnet/runtime/blob/main/docs/project/dogfooding.md) for contribution shows examples for .NET 6, and online I cannot find any pre-release for .NET 7, [nor can I find any pre-release on this repository](https://github.com/dotnet/runtime/releases)

Where would I get a pre-release of .NET 7 from? 😄 
Am I supposed to compile it from [here](https://github.com/dotnet/runtime/blob/main/src/coreclr/build-runtime.sh) myself?

**Comment by danmoseley** [comment]
I think we just haven't updated it. We apparently don't have a list of readmes to update so this happens every year 😸 

I updated https://github.com/dotnet/installer#build-status a little while ago. Do you want to offer a PR?

**Comment by AlmightyLks** [comment]
Oh. Yeah, I plan to. I am preparing some things right now 😄

**Comment by danmoseley** [comment]
That's great! Please check the instructions work, if not then we should take a look...

**Comment by jeffhandley** [comment]
@AlmightyLks Since you said you plan to submit a PR, I'm going to assign this issue to you (so no one else grabs it). But there's no obligation; just let us know if you need to be removed as the assignee. Thanks for reporting this and for the help!

**Comment by deeprobin** [comment]
@AlmightyLks What is the current status on this?

**Comment by AlmightyLks** [comment]
@deeprobin 
Sorry, issue can be closed. 😄
