### ISSUE TITLE
how to collect all assembly references.

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#63093]
we want to collect all assembly dependencies as the single-file app does.

our assembly Main.dll dependents Lib1.dll, and Lib1.dll dependent Lib2.dll and Lib3.dll

but the Main.dll only calls API reference Lib2.dll, so all referenced assemblies are Lib1.dll and Lib2.dll

**Comment by huoyaoyuan** [comment]
This should be closed to deep dependency analysis task of ILLink and NativeAOT. Can your usage be accomplished by ILLink?

**Comment by srxqds** [comment]
> This should be closed to deep dependency analysis task of ILLink and NativeAOT. Can your usage be accomplished by ILLink?

It is ok

**Comment by jkotas** [comment]
> as the single-file app does.

Single-file apps (without IL trimming) are not doing any deep dependency analysis. They just include everything that was produced by the resolved nuget dependencies.

The best way to get the full list of dependencies is using msbuild property. The msbuild property to use depends on the build stage that you are trying to do this in. For example, there is `ResolvedFileToPublish` that you can use if you are trying to do this very late.

**Comment by srxqds** [comment]
I, use `msbuild /p:_TrimmerDumpDependencies=true /p:Configuration=Release YourAppProject.csproj` in https://github.com/dotnet/linker/blob/main/src/analyzer/README.md said, but could not found `linker-dependencies.xml.gz`

**Comment by srxqds** [comment]
i have made it using illink ,thank you
