### ISSUE TITLE
Linux Docker Container

### ISSUE THREAD

**Issue by leanalcabasa** [dotnet/runtime#63094]
I am trying to connect to our AD server using System.DirectoryServices.Protocol but it cannot connect. Based on [this](https://github.com/dotnet/runtime/pull/52904), it seems to be able to support SSL for Linux Docker container.

But I tried it and receive "The feature is not supported". It throws the error on the .Bind step.

```
using (var connection = new LdapConnection(new LdapDirectoryIdentifier(server, 636)))
                {
                    var networkCredential = new NetworkCredential(login, password, "");
                    connection.SessionOptions.SecureSocketLayer = true;
                    connection.SessionOptions.ProtocolVersion = 3;

                    connection.Bind(networkCredential);
                }
```

Am I missing anything? I run same code in my Windows-VisualStudio dev machine, it works correctly.

Do I need to do something special? Maybe install certificate in Linux machine?

**Comment by buyaa-n** [comment]
@leanalcabasa what version of .Net you are using? Seems that is merged into .Net 6

**Comment by leanalcabasa** [comment]
> @leanalcabasa what version of .Net you are using? Seems that is merged into .Net 6

Thank you buyaa, I have resolved it. I needed to add Root CA cert to the docker container.
