### ISSUE TITLE
The Microsoft.NETCore.App runtime for .NET preview7 is missing when install .NET6 preview7 and 6.0.100 GA at the same time.

### ISSUE THREAD

**Issue by JiahongJin1** [dotnet/runtime#63096]
### Description

Affected Mac:
Mac OS: Big Sur(11.6.1)
.NET 6 SDK:
6.0.100-preview.7.21379.14(runtime 6.0.0-preview.7.21377.19)
6.0.100(runtime 6.0.0)

### Reproduction Steps

1.Install .NET 6 preview7 from
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-preview.7-macos-x64-installer
2.Run "dotnet --info" in the terminal
3.Install .NET 6.0.100 from
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.100-macos-x64-installer
4.Run "dotnet --info" in the terminal

### Expected behavior

All the SDKs and runtimes should display separately.

### Actual behavior

The Microsoft.NETCore.App runtime for .NET preview7 is missing.

dotnet info for preview7:
![Screen Shot 2021-12-23 at 5 09 19 PM](https://user-images.githubusercontent.com/46206739/147218116-eff0edb5-031a-48ac-8354-7cd57b00a4d0.png)

dotnet info for preview7 and GA:

![Screen Shot 2021-12-23 at 5 10 35 PM](https://user-images.githubusercontent.com/46206739/147218199-45595fdc-a9e6-4390-9b2d-231bea489efd.png)

### Regression?

This issue can be reproduced with SDK 6.0.100 preview and GA.

**Comment by huoyaoyuan** [comment]
This should be by design. The installer of higher prelease or patch version will replace the old one. The runtimes will only co-exist at feature band level or higher.

**Comment by NikolaMilosavljevic** [comment]
[Triage] @NikolaMilosavljevic please check that this reproes with newer previews. There was an issue with earlier previews on Mac OS, where new preview version would uninstall the older one.

**Comment by JiahongJin1** [comment]
it's by designed, so close it.
