### ISSUE TITLE
Problem with Microsoft.Extensions.Configuration and Configuration.GetSection

### ISSUE THREAD

**Issue by HybridSolutions** [dotnet/runtime#63091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have the following code that takes setting up some services out of program.cs:

```c#
using Microsoft.Extensions.Configuration;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        ...

        services.Configure<ApplicationSettings>(configuration.GetSection(ApplicationSettings.SectionName));

        return services;
    }
}
```

The issue is that I'm getting an error in the `services.Configure` line:

```
Error CS1503
cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action<eCM.Infrastructure.Configurations.ApplicationSettings>'
```
The error is fixed by removing the `using Microsoft.Extensions.Configuration;` that provides a `GetSection` method but then, I can't have `IConfiguration configuration` parameter on my `AddInfrastructure` method.

Is there a conflict here? Do I need to install `Microsoft.Extensions.Options.ConfigurationExtensions` package?

### Exceptions (if any)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Microsoft.Extensions.Configuration.IConfigurationSection' to 'System.Action<eCM.Infrastructure.Configurations.ApplicationSettings>'
```

### .NET Version

.net 6

### Anything else?

This issue has been referenced in [https://github.com/dotnet/AspNetCore.Docs/issues/18833](https://github.com/dotnet/AspNetCore.Docs/issues/18833)

**Comment by eerhardt** [comment]
It looks like you are trying to call this extension method:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.optionsconfigurationservicecollectionextensions.configure?view=dotnet-plat-ext-6.0#Microsoft_Extensions_DependencyInjection_OptionsConfigurationServiceCollectionExtensions_Configure__1_Microsoft_Extensions_DependencyInjection_IServiceCollection_Microsoft_Extensions_Configuration_IConfiguration_

That extension method comes from the https://www.nuget.org/packages/Microsoft.Extensions.Options.ConfigurationExtensions/ package. So if you don't have a `PackageReference` for it, you should add one in your `.csproj`.
