### ISSUE TITLE
[API Proposal]: RandomNumberGenerator.FillNonZero

### ISSUE THREAD

**Issue by ylabade** [dotnet/runtime#63107]
### Background and motivation

The static method `RandomNumberGenerator.Fill()` is the static equivalent of the method `RandomNumberGenerator.GetBytes()` and there is no equivalent for the instance method `RandomNumberGenerator.GetNonZeroBytes()`.

### API Proposal

```diff
namespace System.Security.Cryptography
{
    public abstract class RandomNumberGenerator : IDisposable
    {
+        public static void FillNonZero(Span<byte> data)
    }
}
```

### API Usage

```C#
Span<byte> data = stackalloc byte[100];
RandomNumberGenerator.FillNonZero(data);
```

### Risks

It is a new method and should therefore have no risk to the existing code.

**Comment by vcsjones** [comment]
Can I ask what your use case is for non-zero CSPRNG data? As discussed in https://github.com/dotnet/runtime/issues/42763, there are very few times where CSPRNG data needs to be exclude zero. There's so far and few need for non-zero CSPRNG that there is consideration for obsoleting `GetNonZeroBytes` in that same discussion. 

I'd be very interested in understanding the need for this before additional APIs are added.

**Comment by ylabade** [comment]
I used to use `RandomNumberGenerator.GetNonZeroBytes` to generate random data. I understand that this is not the correct method to use in this case as indicated in #42763. 
I will close this proposal.
Thanks @vcsjones
