### ISSUE TITLE
[Feature Request] :Tensor<T> support 

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#63124]
We have Vector2 / Vector3 / Vector<T>
It's nice to have Tensor<T> as building block too

**Comment by teo-tsirpanis** [comment]
Hello @Xyncgas, there is already a `Tensor<T>` type in the [`System.Numerics.Tensors` package](https://www.nuget.org/packages/System.Numerics.Tensors/6.0.0-rtm.21522.10). It's still in preview though.

**Comment by tannergooding** [comment]
We'll be looking at tensors and tensor like types more closely in the future. At the moment, we are focusing on getting [generic math](https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/) out first.

**Comment by Xyncgas** [comment]
> Hello @Xyncgas, there is already a `Tensor<T>` type in the [`System.Numerics.Tensors` package](https://www.nuget.org/packages/System.Numerics.Tensors/6.0.0-rtm.21522.10). It's still in preview though.

thanks

**Comment by jeffhandley** [comment]
We've been working on this, with the implementation carrying between .NET 9 and .NET 10. See #100924. Closing this one.
