### ISSUE TITLE
coreclr native build seems over parallelized

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#6312]
The build runs msbuild.exe with /m (so, 4 processes on my 4 core machine) but the native build also passes /MP to CL.exe. That gives me 20-24 copies of CL running concurrently, 16-20 active (each msbuild process launches CL /MP, which itself launches 4 worker processes -- and for some reason, I see one msbuild has launched an extra CL /MP)

Usually compile is CPU bound and it works fastest if the number of active compiler worker processes is about the same as the number of CPUs. Fixing this might take several minutes off the full build.

One possible fix is to remove /MP but that's very helpful when building one or two projects at a time. My suggestion is to pass a flag from build.cmd at the root that disables /MP, and check timings to see whether it helps.

**Comment by jkoritzinsky** [comment]
This has been fixed by the move to Ninja.
