### ISSUE TITLE
.NET Version: 6.0.1 Fatal Error Runtime at IP 00007FF696C3917B with exit code 80131506 (ExecutionEngineException?)

### ISSUE THREAD

**Issue by HighPerfDotNet** [dotnet/runtime#63127]
### Description

I've come across with this fatal error (supposedly being ExecutionEngineException based on Googling for that exit code) that kills process whilst testing one fairly large application that deals with large scale data processing - Event Viewer captured the following details (crash address details appear to be consistent in 3 instances of this issue:

---------------------
Application: ********.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF7C6613757

Application: ********.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 00007FF696C3917B (00007FF6969B0000) with exit code 80131506.
---------------------

### Reproduction Steps

Fatal error is inconsistent and application + data too large to create repro at this stage. There was a new install of .NET Desktop Runtime 6.0.1

### Expected behavior

Not having fatal crash.

### Actual behavior

Crashes

### Configuration

AMD EPYC Zen 2 server on Windows Server 2012 R2, very reliable, runs same software on .NET 4.7.1.

### Other information

The following app settings were used:

      "System.IO.UseNet5CompatFileStream": true,
      "System.Runtime.TieredCompilation": true,
      "System.Runtime.TieredCompilation.QuickJit": true,
      "System.Runtime.TieredCompilation.QuickJitForLoops": true,
      "System.Globalization.UseNls": false,
      "System.GC.Server": true,
      "System.GC.Concurrent": true,
      "System.GC.CpuGroup": true,
      "System.GC.LOHThreshold": 85000,

I'll add further information as it becomes available - mostly posting now in hope that provided information will be useful and get some feedback about what can possibly be crashing inside to narrow things down

**Comment by cshung** [comment]
Do we have a repro?

**Comment by HighPerfDotNet** [comment]
I am afraid no, it is a very complex app, failure seems to be happening in the same pretty large stage of processing, so there is a degree of consistency there at least, happened on 2nd box also, so not limited to 1 box. 

I've seen in the other thread that some related bug was fixed but not yet released in 6.0.1, I'll be happy to test new binaries if you got them, if that fixes the problem then we'll know what that was. I'll keep observation and play with different settings to see if that has any effect (planning to turn off Concurrent GC tomorrow).

**Comment by HighPerfDotNet** [comment]
Using setting _"System.GC.Concurrent": false_ also results in exatcly the same crashes. Planning to test on Intel system now.

**Comment by HighPerfDotNet** [comment]
I've checked it on Intel box and had same kind of crash at a rate of around once every 45-60 mins. Downgrading same code to .NET 5.0.13 however had ZERO crashes on all boxes. So whatever this is - it's in .NET 6. I don't think I can do much further now apart from waiting for that other GC fix that hopefully will be out next month.

**Comment by HighPerfDotNet** [comment]
Here is windbg crash analysis - looks like crashes in GC:

`STACK_TEXT:  
000000b2`7cf3e180 00007ff8`1293625c     : aaaaaaaa`aaaaaaaa 00007ff8`1294e590 00000000`00000000 aaaaaaaa`aaaaaaaa : coreclr!SVR::gc_heap::mark_through_cards_for_segments+0x1fd
000000b2`7cf3e360 00007ff8`1293196a     : 00000000`00000000 00000000`00000000 aaaaaaaa`aaaaaaaa 00007ff8`12939331 : coreclr!SVR::gc_heap::mark_phase+0x59c
000000b2`7cf3e420 00007ff8`129330cc     : 00000000`00000000 00000000`00000000 aaaaaaaa`aaaaaaaa 00000000`00000460 : coreclr!SVR::gc_heap::gc1+0xb6
000000b2`7cf3e490 00007ff8`12932bb6     : 00000000`00000460 00000000`00000000 00000000`00000000 aaaaaaaa`aaaaaaaa : coreclr!SVR::gc_heap::garbage_collect+0xec
000000b2`7cf3e4f0 00007ff8`12932b50     : aaaaaaaa`aaaaaaaa 000000b2`7cf3fd40 000000a4`d6eeeb90 00000000`00000000 : coreclr!SVR::gc_heap::gc_thread_function+0x62
000000b2`7cf3e520 00007ff8`129f63b4     : 00000000`00000000 aaaaaaaa`aaaaaaaa 00007ff8`12932aa0 00000000`00000000 : coreclr!SVR::gc_heap::gc_thread_stub+0xb0
000000b2`7cf3fd70 00007ff8`212b13d2     : 00007ff8`129f6340 000000a4`d6eeeb90 00000000`00000000 00000000`00000000 : coreclr!<lambda_cc6f655decef618c652cb4c8a0a63fd5>::<lambda_invoker_cdecl>+0x74
000000b2`7cf3fda0 00007ff8`233254f4     : 00007ff8`212b13b0 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0x22
000000b2`7cf3fdd0 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x34`

[crashanalysis.txt](https://github.com/dotnet/runtime/files/7781718/crashanalysis.txt)

**Comment by cshung** [comment]
Judging from the `!analyze` log, it does look similar to https://github.com/dotnet/runtime/issues/63070, potentially the same issue.

**Comment by cshung** [comment]
The fix is backported to release/6.0, it will be available in our next servicing release. Closing for now.
