### ISSUE TITLE
Suspicious fragments found by PVS-Studio Static Analyzer

### ISSUE THREAD

**Issue by VasilievSerg** [dotnet/runtime#63149]
### Description

Hello!

I checked the code of .NET libraries ([branch 6.0.0](https://github.com/dotnet/runtime/tree/v6.0.0)) with PVS-Studio and found some suspicious places. I described them in [this article](https://pvs-studio.com/en/blog/posts/csharp/0903/) in detail.

In the article, each warning has a description, the file and code lines that triggered the analyzer. [Last time](https://github.com/dotnet/runtime/issues/30599) I described suspicious places in the same format - as I understand it, it is acceptable. :)

Last time some of the described places were fixed, but they weren't mentioned in the issue. :(
Is it possible to mention what fixes were made in this issue or somewhere else this time?

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by stephentoub** [comment]
Thanks for sharing.  In the future, please open individual Issues; it’s not practical to track all of these via an article that isn’t part of dotnet/runtime, that doesn't let Issues be commented on and closed separately, that tracks possible issues across many different libraries, etc.

Issue 1
False positive.  SmallestSize was added after .NET Standard 2.0 and .NET Framework 4.6.1, which this library targets.  It could in theory special-case NetCoreAppCurrent to change the compression level for that build, but it’s not clear that provides meaningful enough value.

Issue 2
A PR for this was already opened at https://github.com/dotnet/runtime/pull/63150.

Issue 3
False positive. While maybe not the cleanest code, the extra ctor argument is there to avoid ambiguities with other ctors.

Issue 4
PR: https://github.com/dotnet/runtime/pull/63344

Issue 5
False positive.  byte is a built-in primitive; it will not resolve to null.

Issue 6
PR: https://github.com/dotnet/runtime/pull/63343

Issue 7
False positive. While the “OrDefault” is gratuitous, the index will be in range.

Issue 8
This was already found and fixed months ago in https://github.com/dotnet/runtime/pull/57398.

Issue 9, 10, 11, 12
PR: https://github.com/dotnet/runtime/pull/63341

Issue 13
PR: https://github.com/dotnet/runtime/pull/63342. This is debug-only tracing that’s not built into any release binaries, but I fixed it anyway.

Issue 14
This was already found and fixed months ago in https://github.com/dotnet/runtime/pull/60176.

**Comment by VasilievSerg** [comment]
Hello Stephen,
Thank you for the feedback on each issue.

> In the future, please open individual Issues

OK, no problems.

Anyway, I hope that the article was useful. :)
And thank you again for the explanations and fixes!

**Comment by jeffhandley** [comment]
> Anyway, I hope that the article was useful. :) And thank you again for the explanations and fixes!

Indeed it was, @VasilievSerg. Thanks!
