### ISSUE TITLE
Update Novell headers in System.Drawing.Common

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63146]
In System.Drawing.Common headers can be found as follows:
```cs
//
// Copyright (C) 2006-2007 Novell, Inc (http://www.novell.com)
//
```
However, this company was bought out by MicroFocus (http://www.novell.com redirects to https://www.microfocus.com/en-us/products/novell/overview). The official name is `Micro Focus International plc` according to "Legal details". 

Accordingly, in my opinion, these headers should either be removed or adapted (I'm not sure what the best way is in terms of licensing).

```diff
//
-// Copyright (C) 2006-2007 Novell, Inc (http://www.novell.com)
+// Copyright (C) 2006-2007 Micro Focus International plc (https://www.microfocus.com)
//
```

**Comment by jkotas** [comment]
These headers are based on the official legal advice that we have received. They are fine in its current form.

Note that we have number of other notices in the repo that reference acquired companies. For example, https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/mono/sgen/sgen-protocol.c#L5-L7
