### ISSUE TITLE
CryptoStream.Read() read less bytes in .NET6 than in .NET5

### ISSUE THREAD

**Issue by marbel82** [dotnet/runtime#63151]
### Description

I change `TargetFramework` from `net5.0-windows` to `net6.0-windows`. My decryption function stop working, because I based on `CryptoStream.Read()` method.

I pass a larger buffer than CryptoStream need. I pass 32B buffer, but it writes only 16B. It should write 17B, because encrypted array is 17B long.

I tried to invoke Read() a second time, and I get 1 missing byte. Probably my implementation has wrong assumptions, because I should read the stream to the end. 
But... Is this how it should work?

Now I'm using CryptoStream.CopyTo() and MemoryStream, and it works just fine.

### Reproduction Steps

```c#
using System.IO;
using System.Security.Cryptography;
...

const int keysize = 16;
string passswordText = "12345";
byte[] saltStringBytes = new byte[keysize] { 204, 231, 71, 247, 198, 100, 92, 42, 38, 45, 62, 54, 83, 178, 158, 165 };
byte[] ivStringBytes = new byte[keysize] { 6, 148, 231, 155, 146, 44, 172, 134, 77, 156, 156, 75, 95, 82, 94, 123 };
// Encrypted array = Encoding.UTF8.GetBytes("12345678901234567")
byte[] cipherTextBytes = new byte[32] { 194, 23, 115, 163, 174, 176, 163, 255, 194, 124, 211, 174, 203, 1, 103, 12, 9, 199, 27, 45, 184, 194, 11, 164, 190, 230, 149, 223, 175, 95, 199, 99 };


using (Rfc2898DeriveBytes password = new Rfc2898DeriveBytes(passswordText, saltStringBytes, 1000))
{
    byte[] keyBytes = password.GetBytes(keysize);
    using (AesCng symmetricKey = new AesCng())
    {
        symmetricKey.BlockSize = keysize * 8;
        symmetricKey.Mode = CipherMode.CBC;
        symmetricKey.Padding = PaddingMode.PKCS7;
        using (ICryptoTransform decryptor = symmetricKey.CreateDecryptor(keyBytes, ivStringBytes))
        using (MemoryStream memoryStream = new MemoryStream(cipherTextBytes))
        using (CryptoStream cryptoStream = new CryptoStream(memoryStream, decryptor, CryptoStreamMode.Read))
        {
            byte[] plainTextBytes = new byte[cipherTextBytes.Length];
            decryptedByteCount = cryptoStream.Read(plainTextBytes, 0, plainTextBytes.Length);

            // .NET5:  decryptedByteCount == 17  ! OK
            // .NET6:  decryptedByteCount == 16  ! NOT OK

        }
    }
}

```

### Expected behavior

CryptoStream.Read() method should read `count` bytes if available.

### Actual behavior

CryptoStream.Read() read some bytes, and must be called several times.

### Known Workarounds

Read until CryptoStream.Read() returns 0 or use `MemoryStream` and `CryptoStream.CopyTo(ms)`

### Configuration

.NET 5  / .NET 6
Windows 10 x64

**Comment by svick** [comment]
This is [a documented breaking change in .Net 6](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams).

**Comment by GrabYourPitchforks** [comment]
FYI, you can use APIs like [`SymmetricAlgorithm.EncryptCbc`](https://docs.microsoft.com/dotnet/api/system.security.cryptography.symmetricalgorithm.encryptcbc) to bypass the whole "create an encryptor, then create a MemoryStream, then create a CryptoStream, then call in a loop, etc." flow. If you have the entire input buffer already available to you, you can pass that buffer as-is to the `EncryptCbc` (or `DecryptCbc`) method, and it will wrap all of that logic correctly on your behalf. It should make the calling patterns considerably easier.
