### ISSUE TITLE
[WASM][Browser] DebuggerTests.ArrayTests: EXECUTION TIMED OUT

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#63167]
`DebuggerTests.ArrayTests` timed out on `net7.0-Browser-Release-wasm-Mono_Release-wasmdebuggertests-(Windows.Server.Core.1909.Amd64.Open)`.

Caught by the rolling build:

https://dev.azure.com/dnceng/public/_build/results?buildId=1528008&view=ms.vss-test-web.build-test-results-tab&runId=43356740&resultId=100019&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d6ce1bcf11b64c3c8d/DebuggerTests.ArrayTests/1/console.5abfee2a.log?sv=2019-07-07&se=2022-01-17T07%3A53%3A38Z&sr=c&sp=rl&sig=CJAjLsphiR%2F9zi0SwXvPkgMdoYVpSKkXc8HZPEOX3fI%3D

cc @radical

**Comment by radical** [comment]
Closing in favor of the older issue - https://github.com/dotnet/runtime/issues/62661 .
