### ISSUE TITLE
Help - Using compiled library DLLs directly instead of nupkg errors out at compile time

### ISSUE THREAD

**Issue by leocb** [dotnet/runtime#63169]
Hi, due to company policies, I can't use Nuget packages on shipping products and must compile all libraries myself and use the generated DLLs. This policy non negotiable.

I was able to compile the all the libs successfully using the following commands:
```
git checkout v6.0.1
git clean -xfd
./build.cmd clr+libs -c Release -lc Release -rc Release
```
this generated the artifacts and I grabbed what I needed from the release folder, for example: 
`runtime\artifacts\bin\System.IO.Pipes\net6.0-windows-Release\System.IO.Pipes.dll`
for the record, I also tried the artifacts from
`runtime\artifacts\bin\System.IO.Pipes\ref\net6.0-Release\System.IO.Pipes.dll`

However, I have some issues with this approach, removing the Pipes nuget and replacing it by the dll, gives me these errors at compile time: 
![image](https://user-images.githubusercontent.com/8310271/147573582-91203b68-ef99-4b4f-bf38-30404a8f35c9.png)

I have this same kind of error with other dlls too, what am I missing?
Thanks!

**Comment by gfoidl** [comment]
Will https://github.com/dotnet/source-build help you?
(also search with your favorite search engine for "source build" for further info)

**Comment by teo-tsirpanis** [comment]
Hello @leocb, first of all what is your company's policymakers' intent behind this policy? To prevent untrusted software from creeping into your deployed products? NuGet allows digitally signing packages, and you can require the packages your project references to be signed, as well as restrict the allowed publishers [via `nuget.config`](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#trustedsigners-section).

I also see that you are having problems with `System.IO.Pipes`. Types in this namespace belong in the shared framework, which does not require installing any NuGet package at all.

**Comment by leocb** [comment]
Hi @gfoidl,
Thanks! I did not know about this repo, I'll take a look at it. But I already built the libraries.

Hi @teo-tsirpanis,
Yes I believe the intent behind this policy is to prevent untrusted code from being deployed. I know about the digital signing, and I believe the policymakers do too, it would be troublesome to get a special permission for this. I can talk to them again about this, but it is a company wide restriction, so I won't get my hopes up

I used `System.IO.Pipes` as an example because it doesn't have any other dependencies, but I'm having the same problems with other libs too, looks like somehow the namespaces inside the dlls isn't being found by the compiler.

After you said `System.IO.Pipes` types belong in the shared framework, i started to look more closely at the depencies we're injecting, and it does seems like there's more than what is needed. We used the migration tool to jump from .net framework 4.7 to .net5 and then again to .net6 when it was released in the middle of our migration, seems like doing this added more nugets than we need. I'll check them all again. I'll leave this issue open for now while I triage what's really going on, and if I find anything wrong with the libs, I'll post it here, otherwise I'll just close it within the next few days. Thanks for your help!

**Comment by teo-tsirpanis** [comment]
If you are only referencing `System.*` or `Microsoft.*` packages on a .NET 6 project, it's highly likely that you don't need them. Try removing them and if they don't break your build don't add them back.

**Comment by safern** [comment]
As an FYI, these are the libraries that are part of the shared framework, if any of the nugets is on this list, you don't need them for .NET 6: https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/NetCoreAppLibrary.props#L4-L147

**Comment by ericstj** [comment]
So the above error indicates an issue is very specific to System.IO.Pipes.  This assembly defines some types in reference in System.IO.Pipes.AccessControl, https://github.com/dotnet/runtime/blob/a991e1349e4325770d8e2ddf085184a68cd2555b/src/libraries/System.IO.Pipes.AccessControl/ref/System.IO.Pipes.AccessControl.cs#L50 but implements them in System.IO.Pipes.  So when you mix the reference assembly for AccessControl with the implementation assembly for Pipes you hit this error.   As @safern mentioned you don't need a package here, so it shouldn't be an issue based on the requirement you mention in your post.

In general for other you should be OK to reference a newer version of an assembly built from the repo in your app for experimentation and it should work.  This particular case is exceptional.   You do have to be careful to reference the same framework built for that assembly.  Alternatively you can just build the packages and reference your built packages (dotnet pack on the src assembly).

Closing this out for now.  Let us know if you run into any other issue.

**Comment by teo-tsirpanis** [comment]
Thanks for the list @safern. I wonder, is there a use case where one would need to still reference a formerly OOB package on .NET Core/.NET 5+? And would it be a breaking change to remove one of them from a NuGet package?

---

To give some context into my question, Roslyn [is referencing the now-discontinued `System.Memory` and `System.Threading.Tasks.Extensions` _on .NET Core 3.1_](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/4.1.0-3.final). I had proposed to reference them only on .NET Standard 2.0, but my request has been declined for reasons I still do not understand, and I would like some more information about the impact of removing such packages.
