### ISSUE TITLE
Support more than one jsoncontext in aspnet core

### ISSUE THREAD

**Issue by musictopia2** [dotnet/runtime#63171]
Currently, I cannot figure out a way in an aspnet core to be able to register more than one option so if a person has many controllers and want to use source generation for all of them, they can.
I am only able to make it use source generation on one of them.  Unfortunately, it means the rest has to use reflection which is too slow.

**Comment by musictopia2** [comment]
I would suggest putting this under system.text.json category.

**Comment by Clockwork-Muse** [comment]
@musictopia2 - Do you have a simple repro of the problem?
