### ISSUE TITLE
Inconsistent nullability change in TypeConverter.CanConvertTo resulting in a breaking API change with .NET 6.0

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/runtime#63186]
In .NET 6.0, the nullability of the overload `TypeConverter.CanConvertTo(ITypeDescriptorContext? context, Type destinationType)` was changed. Now, the `destinationType` paramter is also nullable. The same change was not done with `TypeConverter.CanConvertTo(Type destinationType)` and `TypeConverter.ConvertTo`

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.canconvertto?view=net-6.0
`public virtual bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext? context, Type? destinationType);`

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.canconvertto?view=net-5.0
`public virtual bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext context, Type destinationType);`

I believe that `destinationType` being nullable is an API bug introduced in .NET 6.0 since it is a) inconsistent with the remaining API, b) not documented as a use case in MSDN, and c) appears to defeat the purpose of the conversion API since you need to know the destination type in order to make an informed choice.

Note that the new API breaks existing code based on .NET 5.0 (custom TypeConverter implementations).

Note that according to git, the entire nullability of TypeConverter was done with ##54961 after .NET 5.0 was already released, so I can't really backtrack this to the root cause.

**Comment by eerhardt** [comment]
I believe the change to `public virtual bool CanConvertTo(ITypeDescriptorContext? context, Type? destinationType)` was a mistake in #54961. It doesn't make any sense to pass `null` here (even though it doesn't throw an exception if you do). The `ConvertTo` method will throw an ArgumentNullException if you do.

cc @krwq - who made the change. Any thoughts here?

**Comment by maryamariyan** [comment]
@MichaelKetting thanks for the report, would you like to add a PR for this?

**Comment by MichaelKetting** [comment]
@maryamariyan Sure thing!
