### ISSUE TITLE
.NET 6 R2R does not work with classes with umlauts in referenced assemblies

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/runtime#63193]
### Description

Everything works with umlauts if they are in the same project but if they are in a different project then it constantly produces errors on run:
`Unhandled exception. System.TypeLoadException: Could not load type 'Dummy.Umlautä' from assembly 'Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.`

### Reproduction Steps

I made a repo demonstrating this issue: https://github.com/MarkusRodler/r2r-umlauts-issue

In essence: 
1. Create a new project
2. Enable R2R `<PublishReadyToRun>true</PublishReadyToRun>`
3. Create a shared project and reference it
4. Create a class in the shared project containing umlauts `public record Umlautä();`
5. Instantiate the class in the projects `Program.cs`
6. Publish it succesfully
7. Run it with errors

### Expected behavior

No TypeLoadException errors on run.

### Actual behavior

TypeLoadException errors on run

### Configuration

.NET 6 
alpine-x64

**Comment by MichalStrehovsky** [comment]
Looks related to https://github.com/dotnet/runtime/issues/61104. If I had to guess, something might be off with computing type name hash codes in `ReadyToRunHashCode`.

Cc @dotnet/crossgen-contrib

**Comment by mangod9** [comment]
@trylek assume your fix resolves this issue as well?

**Comment by trylek** [comment]
@mangod9 - Yes, I believe my fix should fix this issue too, in fact the regression test I created in that PR does include umlaut characters in the type name.

**Comment by MarkusRodler** [comment]
Yes this works. Thanks!
