### ISSUE TITLE
Building a dotnet6 project on the M1 processor is incompatible with x64 architecture, despite using rid=linux-x64

### ISSUE THREAD

**Issue by zaneclaes** [dotnet/runtime#63197]
### Description

With dotnet5, I was able to follow the official Microsoft guide for containerizing a dotnet app on my M1 processor. I would use the following command to build the executable before copying it via the Dockerfile:
`dotnet publish -r linux-x64 -c Release`

With dotnet6, this no longer works. Attempting to run the resulting application on a Linux x64 machine results in the following error:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.JwtBearer, Version=6.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference.
```

Building the application on a x64 Linux machine does not exhibit this problem.

### Reproduction Steps

1) Build an application via `dotnet publish -r linux-x64 -c Release` on a M1 processor
2) Attempt to run the application on a Linux x64 machine

I am not sure if the JwtBearer library is specifically required or not to trigger the error.

### Expected behavior

The build should either fail, or produce a working application.

### Actual behavior

The build succeeds, but produces an application which does not actually work on the target architecture.

### Regression?

Yes.

### Known Workarounds

Build on x64.

**Comment by vitek-karas** [comment]
Can you please try to publish the app for your M1 machine:
`dotnet publish -r osx-arm64 -c Release`

and then try to run the resulting app. Does it fail the same way?

`Microsoft.AspNetCore.Authentication.JwtBearer` is not part of the framework, so you should see the file in the output of the app. Is it there?
