### ISSUE TITLE
Get unknown output("Bytes to key ******") via journalctl

### ISSUE THREAD

**Issue by czd890** [dotnet/runtime#63206]
### Description

The program is configured to output log to console(`ILoggingBuilder.AddConsole()`), 

I started the program via "dotnet <ddl name>" in the terminal and monitoring the log output.
At the same time, monitoring the log output via `journalctl -f _PID={my processor id}` in a new terminal.
It is found that when there is no output in the startup terminal, the journalctl terminal still has output.

And, I checked that all loggers in the program, are used categoryName with class name(e.g. "<ddl name>.<className>") to logger.
But categoryName does not have a class name in the log seen by journalctl.

So, I am very confused, I don't know who is outputting these logs, and I don't know what the contents of these logs are.

``` shell
# journalctl -f _PID={my processor id}
# output
Dec 30 04:24:32 <hostname> dotnet[1809]: <dll name> Information: 0 :
Dec 30 04:24:32 <hostname> dotnet[1809]: Bytes to key 4452474E42554C4C5553444D61726B65744361706974616C697A6174696F6E555344: 7535
Dec 30 04:24:32 <hostname> dotnet[1809]: <dll name> Information: 0 :
Dec 30 04:24:32 <hostname> dotnet[1809]: Bytes to key 4452474E42554C4C555344546F74616C537570706C79: 50691
Dec 30 04:24:32 <hostname> dotnet[1809]: <dll name> Information: 0 :
Dec 30 04:24:32 <hostname> dotnet[1809]: Bytes to key 45544342554C4C55534443697263756C6174696E67537570706C79: 60121
Dec 30 04:24:32 <hostname> dotnet[1809]: <dll name> Information: 0 :
Dec 30 04:24:32 <hostname> dotnet[1809]: Bytes to key 45544342554C4C5553444D61726B65744361706974616C697A6174696F6E555344: 38431
Dec 30 04:24:32 <hostname> dotnet[1809]: <dll name> Information: 0 :
Dec 30 04:24:32 <hostname> dotnet[1809]: Bytes to key 45544342554C4C555344546F74616C537570706C79: 27246
```

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

### Reproduction Steps

I tried to build a demo program (copy the problematic program and simplify the code as much as possible), but it couldn't be reproduced.

### Expected behavior

There should not be any output through `journalctl`

### Actual behavior

Got unknown output  through `journalctl`

**Comment by eerhardt** [comment]
Are you using cassandra? Doing a search for "Bytes to key" hit this line:

https://github.com/yugabyte/cassandra-csharp-driver/blob/6fc2772a140379bd2aaaed789781179196c732c8/src/Cassandra/YugaByte/PartitionAwarePolicy.cs#L202

**Comment by czd890** [comment]
@eerhardt 
WOW! Yes, i using cassandra. could you please tell me how you searched? i searching in github and google, but could not find any relate codes.
Thanks!!!,

**Comment by eerhardt** [comment]
I used the new github code search:

https://cs.github.com/?scopeName=All+repos&scope=&q=%22Bytes%20to%20key%22%20language%3AC%23

I'm going to close this issue since this question has been answered.
