### ISSUE TITLE
Environment variable DOTNET_DbgEnableMiniDump=1 doens't work on linux

### ISSUE THREAD

**Issue by human33** [dotnet/runtime#63218]
### Description

If I set environment variable DOTNET_DbgEnableMiniDump to 1 and run an app that crashes with StackOverflow exception the runtime won't create a dump as it's said in these two articles: [1](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-stackoverflow), [2](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps).

### Reproduction Steps

1. `dotnet new console --framework net6.0`
2. Change Program.cs to 
```
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Main(args);
        }
    }
}
```

3. run `export DOTNET_DbgEnableMiniDump=1`
4. run the app `dotnet run`

### Expected behavior

Dump is generated and placed in `/tmp` dir. 

### Actual behavior

No dump is generated. Sometimes after exception I see the line: `Aborted (core dumped)`, sometimes only the exception is printed.

### Regression?

Works the same with a project targeting net5.0

### Configuration

1. Which version of .NET is the code running on? - `dotnet --version` 6.0.101
2. What OS and version, and what distro if applicable? - Ubuntu 21.10
3. What is the architecture (x64, x86, ARM, ARM64)? - x64
4. Do you know whether it is specific to that configuration? - It works fine if I publish a selfcontained app and run it on Windows.

**Comment by tommcdon** [comment]
@human33 please try using the COMPLUS_ prefix instead of DOTNET_.  I believe #59513 fixes the issue so that the DOTNET_ prefix will work for dump generation and is available in daily builds on the main branch.

**Comment by janvorli** [comment]
@human33 / @tommcdon the other prefix casing is `COMPlus_`, Unix env variable names are case sensitive. So `COMPLUS_` prefix would have no effect.

**Comment by human33** [comment]
> @human33 please try using the COMPLUS_ prefix instead of DOTNET_. I believe #59513 fixes the issue so that the DOTNET_ prefix will work for dump generation and is available in daily builds on the main branch.

Thanks, it works fine with `COMPlus_`.
