### ISSUE TITLE
Question - Blazor AOT Build Time Optimization Flags

### ISSUE THREAD

**Issue by chassq** [dotnet/runtime#63238]
Sorry, I am not sure this question is in the correct place. We are trying to get our build times down when doing AOT compilation for a Blazor WASM web site. Without AOT our build comes in at 9 minutes. With AOT they come in at 40 minutes. We saw this issue [#604](https://github.com/dotnet/runtime/issues/60466) but were not sure wht the flags mentioned actually did. Can someone lets us know more info or direct us to any docs?

```
<EmccLinkOptimizationFlag>-O1</EmccLinkOptimizationFlag>
<EmccCompileOptimizationFlag>-O1</EmccCompileOptimizationFlag>
```

**Comment by teo-tsirpanis** [comment]
These two properties contain flags to be passed to the Emscripten compiler frontend that compiles the IL assemblies to WASM. [Here is a list of all available options.](https://emscripten.org/docs/tools_reference/emcc.html)

**Comment by chassq** [comment]
Thank you for this information!
