### ISSUE TITLE
Add diagnostic option to apphost itself.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#63242]
### Description

I have an application (a windows forms application) that worked well with my own runtime until I added the Microsoft.AspNetCore.App reference to it bringing the total framework references to 4 for that application.

However when I try to manually run debug or release mode on that forms application it "thinks" the desktop runtime is not installed (I know it actually is) and so a diagnostic option where it logs the actual runtime it "thinks" is missing is needed in VS2022 debug console for developers like me can diagnose the root cause of this.

This is so that way to can determine which "framework" reference is causing the problem and try to resolve it in a much more clear way.

### Reproduction Steps

I think the smallest repro is this:

- mkdir apphosttest
- cd apphosttest
- git init (for some tools I use I practically force the use of git)
- dotnet new winforms
- open the project up and add a manual FrameworkReference to ``Microsoft.AspNetCore.App``.
- try to debug in VS2022 in debug mode or run release mode directly (you should see the "Missing Desktop Runtime" message now with no debug console logs from the apphost to diagnose the actual issue)

### Expected behavior

For the application to run (or if it does not to debug console log the apphost to determine which runtimes got loaded successfully and which did not). Alternatively for Desktop applications, it could help if it did not hardcode it to say ``the desktop runtime is missing`` and instead put in the actual runtime it thinks is missing instead.

### Actual behavior

No clear diagnostic switch in the apphost to log which runtime it thinks is missing and the dialog that shows up also does not specify the "runtime" it thinks is missing.

### Regression?

Not sure if it ever worked with:
- Windows Forms framework reference + AspNetCore framework reference + base framework to know for sure if it's a regression.

### Known Workarounds

No known workarounds other than possibly removing the AspNetCore framework reference (which I wanted to use to ensure my code at runtime always use the latest patch of DependencyInjection without needing to be recompiled for it as the package version would require just that).

### Configuration

It started when I had my code target .NET 6 (with the 6.0.1 servicing release), that was when I added the AspNetCore framework to my own framework + my winforms application. After that it failed, so then I thought it was a versioning problem so I manually cloned dotnet/sdk, dotnet/windowsdesktop, dotnet/aspnetcore, and built dotnet/runtime (had my own local code changes) and built installers for all but the sdk and installed them all to ``Program Files/dotnet``. After that I retargeted my own runtime to .NET 7 and made them all 7.0.0-dev and the problem still occurs.

OS: Windows 11 22000.376
Arch: x64

I do not know if it is specific to that configuration.

**Comment by vitek-karas** [comment]
There are already two ways:
* There should be an event written into Windows Event Log with possibly more details about the error.
* Detailed tracing: `set COREHOST_TRACE=1`, `set COREHOST_TRACEFILE=host.txt`, run the app, the `host.txt` file in the current directory should print out lot of detailed information about what it tried to do and why it failed.

**Comment by AraHaan** [comment]
I have narrowed down the issue to it referencing the AspNetCore framework with any of the WindowsDesktop frameworks.

**Comment by vitek-karas** [comment]
I don't know about anything obvious which prevents using both ASP.NET and Windows Desktop frameworks. Getting a detailed error information (as per the above comment) should help in answering what is actually going on.

**Comment by AraHaan** [comment]
Yeah, they seem to work, sadly there is no way to temporarily (until recompiled without them set) hard set them inside of the apphost itself though so when the resulting exe is double clicked it will have them set automatically and easier.
