### ISSUE TITLE
[API Proposal]: string.Join with two separators to create string like "1, 2, 3 and 4"

### ISSUE THREAD

**Issue by pekspro** [dotnet/runtime#63250]
### Background and motivation

Humans often read out lists with a special separator between the last two items. For instance, "1, 2, 3 and 4". There is no overload to `string.Join` (or `StringBuilder.AppendJoin`) that supports this. 

This is a trivial problem. But I have run into this so many times that I wanted to suggest this.

### API Proposal

```C#
string Join (string? separator, string? lastSeparator, object?[] values);
```

### API Usage

```C#
var list = new List<string> { "apple", "orange", "grape", "pear" };

string s = string.Join(", ", " and ", list);

// The string now has the value "apple, orange, grape and pear" 
```

### Risks

I guess the suggested proposal collides with this existing overload:

```C#
string Join (string? separator, params object?[] values)
```

**Comment by sholman** [comment]
But then you'd need to allow for the Oxford comma for examples like "Jeff, Steve, and Peter"

**Comment by filipnavara** [comment]
Honestly, languages are much more complex than what this can capture. It may work for English, probably quite a few Indo-European languages but it's still overly specific to these and the particular use case. I don't think bolting language-specific APIs on a `string` class is good idea. In fact, making some methods on `string` operate with local culture was a mistake (and there is design proposal to offer replacements and hide the old methods). Just my $.02.

**Comment by sholman** [comment]
> Honestly, languages are much more complex than what this can capture. It may work for English, probably quite a few Indo-European languages but it's still overly specific to these and the particular use case. I don't think bolting language-specific APIs on a `string` class is good idea. In fact, making some methods on `string` operate with local culture was a mistake (and there is design proposal to offer replacements and hide the old methods). Just my $.02. 

Agreed. I'm sure this is something that could be done with an extension method.

**Comment by pekspro** [comment]
Oxford comma? I wasn't even that existed 😊.

I'm totally aware that this will not support every culture, but that is not the intention. It is just a way to join strings in a well-defined way, just like the original Join methods.

**Comment by Tornhoof** [comment]
You might want to try humanizer.
https://humanizr.net/#humanize-collections

**Comment by Clockwork-Muse** [comment]
Agreed; this isn't a _string_ problem, this is a culture problem, and culture problems are tough.

**Comment by pekspro** [comment]
Thanks @Tornhoof, I wasn't aware of humanizer.
