### ISSUE TITLE
[API Proposal]: Peek queue index

### ISSUE THREAD

**Issue by Avid29** [dotnet/runtime#63257]
### Background and motivation

Adding a method to the Queue that allows you to peek an index in the queue 

### API Proposal

```C#
namespace System.Collections.Generic
{
    public class Queue<T> : IEnumerable<T>, IEnumerable, IReadOnlyCollection<T>, ICollection
    {
        /// <summary>
        /// Returns the object at a position within the <see cref="Queue{T}"/> without removing it.
        /// </summary>
        /// <param name="index">The index within the <see cref="Queue{T}"> to peek.</param>
        /// <returns>The object at a position within the <see cref="Queue{T}">.</returns>
        /// <exception cref="InvalidOperationException">The <see cref="Queue{T}"/> is empty.</exception>
        /// <exception cref="IndexOutOfRangeException">index is less than 0 or index is equal to or greater than <see cref="Queue{T}.Count()"/>.</exception>
        public T this[int index] { get; }
    }
}
```

### API Usage

```C#
Queue<int> queue = new Queue<int>();
queue.Enqueue(1);
queue.Enqueue(2);
queue.Enqueue(4);
queue.Enqueue(1);
queue[1] == 4; // true (indexed by the order values dequeue)
```

### Alternative Designs

Currently a user would need to write their own circular buffer implemenation to get the benefits of a Queue with indexing.

An alternative implemtation would be to add an override function to `Peek()` with `Peek(int index)`

**Comment by theodorzoulias** [comment]
So `queue[0]` would be equivalent to `queue.Peek()`?

**Comment by Avid29** [comment]
@theodorzoulias Yeah

**Comment by acaly** [comment]
To be symmetric, is it good to add the same indexer to `ConcurrentQueue`?

**Comment by layomia** [comment]
For my education, does anyone have any concrete/real world scenario where this method would be needed? cc @eiriktsarpalis.

**Comment by eiriktsarpalis** [comment]
Why not just use `queue.ElementAt(1)`?

**Comment by eiriktsarpalis** [comment]
Indeed, but I guess we need to understand what your use case is. In some cases an _O(n)_ solution might be good enough, especially if `n` is a constant like `1` in your example. Keep in mind that adding new APIs --particularly in popular generic classes-- comes with substantial runtime overhead: every generic instantiation of `Queue<T>` in every application now needs to perform codegen for one additional method. So we generally don't consider API additions unless they come with a compelling use case (i.e. something many users could benefit from).

Have you considered alternatives, like using `List<T>` instead of `Queue<T>`?

**Comment by Avid29** [comment]
Alright. I can understand why there's hesitency to add this then. I didn't realize there was any downside.

My use case is writing DBSCAN, and my queue of points to expand needs to be read in the middle in some contexts, but then needs to pop from the front later. It's a pretty obscure usage, and if I put some effort in I could probably get similar value out of running a for each loop. Thanks for the info.

**Comment by eiriktsarpalis** [comment]
That sounds like something that could be done with `List<T>` (via the `RemoveAt` method), or even better using a bespoke data structure. Thank you for submitting the suggestion!
