### ISSUE TITLE
System.Threading.Timer.Timer max timeout mismatch

### ISSUE THREAD

**Issue by zgabi** [dotnet/runtime#63258]
### Description

In the followin line an exception is thrown when timeout is > 0xfffffffe

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs#L837-L838

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs#L803

The exception message is:
https://github.com/dotnet/runtime/blob/00c169230672b48ff2c77df9ac18aeae0a55ee6a/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L1856-L1858

### Reproduction Steps

-

### Expected behavior

Message should be "less than or equal to 2^32-2" or "less than 2^32-1"

### Actual behavior

Wrong exception message

**Comment by danmoseley** [comment]
Thanks for the report. Would you like to offer a PR?

**Comment by zgabi** [comment]
If it is not necessary, I prefer not to create a PR.
I think this is easy to fix.

**Comment by danmoseley** [comment]
@zgabi I fixed it, thanks for the report. You would be welcome to contribute elsewhere in this repo, if that might be interesting to you. (There are many issues labeled up for grabs, and some marked easy.)
