### ISSUE TITLE
Cant start generated program on linux (Ubuntu)

### ISSUE THREAD

**Issue by sonik-br** [dotnet/runtime#63267]
### Description

I'm cross building from windows to linux. Targeting netcoreapp3.1.
I can't start the program by double clicking on ubuntu. But it does work from the command line.
Previously I could build and run my program on linux. But worked probably after some updates to VS it stopped working.
Settings used to publish
![image](https://user-images.githubusercontent.com/16923826/147888646-7634a5d1-8d6d-4a98-b7ef-89b56224d6ab.png)

I'm testing it on Ubuntu 21.04.
Building the application on VS 2019 and Windows 10.

### Reproduction Steps

Create a new Console App targeting Net Core 3.1
On windows, Publish it for linux with this settings:
![image](https://user-images.githubusercontent.com/16923826/147888646-7634a5d1-8d6d-4a98-b7ef-89b56224d6ab.png)

Copy contents to Linux. Set executable permission on the main file.
Try to run by double clicking it.

### Expected behavior

Executable file as in:
![image](https://user-images.githubusercontent.com/16923826/147888672-be52fb9c-9a40-49d4-98f2-a5b096a446a8.png)

### Actual behavior

Not an executable file:
![image](https://user-images.githubusercontent.com/16923826/147888682-c0028285-813b-4f36-9d38-3c56a77f6ff6.png)

### Regression?

I think it an update broke it but it's been months since I generated a build for linux.
EDIT: Tested with a global.json file and set the sdk version to 3.1.113. With this version it does work on linux.

**Comment by vitek-karas** [comment]
This is probably a bigger problem. As far as I can tell the same applies to the `dotnet` executable itself.

(I only tried this by extracting the zip archive on my PI - where it showed the `dotnet` to be a shared library as well).

I personally don't know what makes the file an "Executable" versus "Shared library". It runs just fine from command line...
@VSadov could you please take a look?

**Comment by sonik-br** [comment]
Using the "file" tool on linux gives:

* ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32
* ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32

I would really like at least an option to output as "executable". But I don't know why it's this way and if it's required.

**Comment by janvorli** [comment]
This stems from switching the executables to be position independent. The file is not a shared library, it is a real executable file. See e.g. https://unix.stackexchange.com/questions/89211/how-to-test-whether-a-linux-binary-was-compiled-as-position-independent-code for more details.

A comment on that page says that `file` command of version >= 5.36 reports PIE executables as  "pie executable". The `file` command version in Ubuntu 21.04 should be of a higher version. Can you please check what version you have? Maybe the GUI launcher somehow relies on the output of the file command.

**Comment by sonik-br** [comment]
file --version

file-5.39
magic file from /etc/magic:/usr/share/misc/magic

**Comment by janvorli** [comment]
I've looked into it. The file tool on Ubuntu 21.04 shows the following for the `dotnet` / `apphost` binaries:

```
.NET 3.1 binaries:
dotnet: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=addc1e9df71cc8a98ac7383efd0bbe81856faa4f, stripped

.NET 5 binaries:
dotnet: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=8d5ec28aed32608c4c97a51901b90a4589cf5455, stripped

.NET 6 binaries:
dotnet: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d3f0ce58a9a7e540d94d4080b8a504b411d2216a, for GNU/Linux 2.6.32, stripped
```

So we have some something wrong set on .NET 3.1 only when compiling / linking the host binaries. The 5 and 6 are fine. I'll double check the options to find what's different.

**Comment by sonik-br** [comment]
Net 3, 5 and 6 for me with latest sdk rpduces "shared object".
I can only get "executable" when build with sdk 3.1.113 (3.1.11)

**Comment by janvorli** [comment]
That is strange, since for both the dotnet and apphost binaries in 5 and 6 the file command reports pie executable. I've downloaded the SDKs manually to my Linux box, located these files in them and ran the file on them.
I'll try to repro your publishing process on Windows to see what I get. I am starting to wonder if we somehow could end up using apphost (that's what gets renamed to your app's name and used as the main executable) from 3.1 even for .NET 5 and 6.

**Comment by janvorli** [comment]
I've tried to publish a simple HelloWorld app targeting net5.0 linux-x64 using visual studio on Windows and copied the files to Ubuntu 21.04 and ran the file command on the main executable. It reported the "pie executable". 

I wonder if you could have somehow made a mistake either copying the .net 3.1 files or running the file on the 3.1 ones  or something like that.

**Comment by wzchua** [comment]
Related https://github.com/dotnet/runtime/issues/45862 ?

**Comment by janvorli** [comment]
@wzchua that has been fixed in https://github.com/dotnet/core-setup/pull/9125, but it obviously doesn't work as expected. The 3.1 binaries are missing the bit that indicates they are PIE. However, I've just verified we pass all the compiler and linker options necessary, so there is something weird going on. I am investigating.

**Comment by vitek-karas** [comment]
> I am starting to wonder if we somehow could end up using apphost (that's what gets renamed to your app's name and used as the main executable) from 3.1 even for .NET 5 and 6.

If the app is targeting .NET Core 3.1 (`TargetFramework`) it will use the 3.1 apphost regardless of which version of SDK was used to build it. (At least that's how it should work).

**Comment by sonik-br** [comment]
> 

Simple consoleapp. What's the contents of your runtimeconfig.json file?
Mine is:

```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "5.0.13"
      }
    ]
  }
}
```

file does show as "ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32" but it cant start by double clicking.
![image](https://user-images.githubusercontent.com/16923826/148385645-9c174b93-2b57-4d8d-877c-aa4164644d12.png)

Then if i build it with sdk 3.1.113 it starts with double click. File says:
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32

See, one is "pie executable" and the other is just "executable".
Ubuntu cant start the "pie executable" just by double click.

**Comment by janvorli** [comment]
Then I believe this is a bug in the desktop on Ubuntu, as PIE executables are valid executables. It is actually recommended for safety reasons to always build executables as PIE. I've found the following discussion that mentions the issue and also suggests possible workaround: 
https://pretagteam.com/question/ubuntu-recognizes-executable-as-shared-library-and-wont-run-it-by-clicking

So the .NET 5 and 6 produces expected results (executables reported as pie executable by the file command), but the latest 3.1 does not (the host is identified as shared object). It is something that happens in our official build, as building it locally from exactly the same sources, the apphost and dotnet binaries are correctly marked as PIE. I am suspecting the GNU linker to be the culprit, as I was using the same compiler locally, but the linker was newer. I am still investigating that.

**Comment by sonik-br** [comment]
Thanks for the reply. I hope Ubuntu fixes it.

**Comment by janvorli** [comment]
@sonik-br I've just tried a hello world app published to target .NET 6 on Ubuntu 21.10 and it seems to work fine. Getting properties of the file:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/10758568/148436578-cf6a45d0-d3e3-4f9f-a0d6-3175c7b7031e.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/10758568/148436403-9d48d0a2-7397-462e-8b64-dd719f5141c8.png">

**Comment by janvorli** [comment]
So maybe they've fixed it already in the 21.10.

**Comment by janvorli** [comment]
And actually, even the 3.1 is detected as exe there even though the file reports it as a dynamic object.
<img width="466" alt="image" src="https://user-images.githubusercontent.com/10758568/148441125-f7e1e86e-7f3f-4e98-8dd9-c95db0a61949.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/10758568/148441016-5228a817-af7e-4759-b737-ce144e496d99.png">

**Comment by sonik-br** [comment]
@janvorli that's great news!
I've updated my Ubuntu box and its indeed working as it should.
