### ISSUE TITLE
Publishing a NativeAOT app generates JSON files

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#63265]
### Description

Publishing a console app as AOT through VS still generates the following JSON files:

```
AppName.runtimeconfig.json
AppName.deps.json
```

If you look at these files it tells something about the .NET version. The .NET references etc. All of this seems pretty much obsolete for a native executable. Is there any reason why these files are generated or is this a bug?

### Reproduction Steps

1. Create console .NET 6 app
2. Add ILCompiler nuget package
3. In VS 2022 create a publish to folder profile with the following settings: Self-contained, win-x64
4. Publish through VS

### Expected behavior

Only executable in publish folder

### Actual behavior

Executables + JSON files in publish folder

**Comment by NUlliiON** [comment]
Add the following elements to your csproj file:
<PropertyGroup>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
</PropertyGroup>

**Comment by Symbai** [comment]
I can also delete the files. But my question was rather: 1. Are these files required? And if not 2. why are they generated (which means in fact they should NOT be generated if they aren't required. Its a minor bug then) VS or something else should detect its AOT and stop generating these files.

**Comment by huoyaoyuan** [comment]
I don't think they are really needed. You can try to delete them and run the program.

> why are they generated

Because they are typically required in "normal" build. Maybe the NativeAOT toolchain just does not delete them? Or copy them as-is?
