### ISSUE TITLE
Potential infinite loop on MacOS on connected sockets

### ISSUE THREAD

**Issue by jvimal-eg** [dotnet/runtime#63291]
The potential infinite loop is here:

https://github.com/dotnet/runtime/blob/55fecfbc201dc789d71c0903e04f2a779212c671/src/native/libs/System.Native/pal_networking.c#L1441-L1443

Context: On some older MacOS versions (at least on Yosemite from what I've read online [1]), there's a potential flaky error EPROTOTYPE that could be returned on a write() to a socket.  That was noted https://github.com/dotnet/runtime/issues/27221 and fixed in https://github.com/dotnet/corefx/pull/37208.  The fix assumed that EPROTOTYPE was a transient error, which was the same assumption made by the libuv fix [1].

However, on newer MacOS versions (I've seen it on BigSur and Monterey), this runs into an issue.  The EPROTOTYPE error doesn't appear to be a transient error.  When a particular kind of VPN [2] is enabled, writes on all connected sockets seem to fail with EPROTOTYPE that doesn't appear to be a transient error.

It's pretty easy to reproduce on Signal.app, which uses Electron/libuv: merely turning on the network extension causes a 100% CPU usage after waiting for a write() on the socket. After restarting Signal, the issue goes away, so this appears to be an issue with existing connections prior to enabling the VPN.  Looking at an Instruments profile confirms that one thread is spinning on a write() system call that's returning errno=41 (EPROTOTYPE).

Since the workaround in dotnet is similar to [1], I suspect it will have the same issue, although I haven't tried to reproduce it.  It's unclear what the exact fix ought to be, but at the very least there should be some guard against an infinite loop here.

[1] https://github.com/libuv/libuv/pull/482
[2] A transparent proxy network extension.  Some more discussion and context here: https://developer.apple.com/forums/thread/681135.

**Comment by antonfirsov** [comment]
I think we should definitely look in to this. To me jumping out of the loop after a constant number of iterations seems fine, @wfurt  any thoughts?

**Comment by wfurt** [comment]
I agree, we should add limit for retries. The original change was really inspired by [1] and we were never really able to reproduce it in-house. It seems like the call is going to (always?) fail in certain configuration but at least app can handle it and report back. 
Note we have unrelated issue when transparent VPN did not handle  dual mode sockets right. So I would not be surprised if there are some weirdnesses in VPN case. 

Do you have any experience with the `NETransparentProxyProvider` @filipnavara? Even if not, I'd be happy to make change to fail after N tries.

**Comment by karelz** [comment]
Triage: Infinite loop isn't pretty. We should address it.
It should be straightforward fix.

**Comment by filipnavara** [comment]
> Do you have any experience with the NETransparentProxyProvider @filipnavara?

Unfortunately no. It's quite a blackbox to me. Apple mainly pushes the Network.framework now as a way to handle multi-path network connections and handle VPNs somewhat more transparently. That said, my experience with it is quite limited and the API is significantly different from BSD socket APIs.

I'd agree limiting the number of retries is the best way forward for now.
