### ISSUE TITLE
Calling IHostApplicationLifetime.StopApplication() does not stop a service when configured using IHostBuilder.UseWindowsService()

### ISSUE THREAD

**Issue by russellfoster** [dotnet/runtime#63303]
### Description

Using the injected IHostApplicationLifetime.StopApplication() method works fine to exit the process when running as a console app. But when running as a Windows service, the process falls out of Main as expected, but the service controller keeps the service alive. It seems related to the issue fixed in:

[https://github.com/dotnet/aspnetcore/pull/4553](https://github.com/dotnet/aspnetcore/pull/4553)

Looking at the WindowsServiceLifetime source, I don't see any code that would stop the service when the ApplicationLifetime.ApplicationStopping event is broadcast.

### Reproduction Steps

Set up a minimal service using Host.CreateDefaultBuilder(args).UseWindowsService(), and call IHostApplicationLifetime.StopApplication().

### Expected behavior

The windows service should stop.

### Actual behavior

The windows service is still running, even though the main code has exited.

**Comment by eerhardt** [comment]
@russellfoster - can you create a minimal repro app and link to it? I want to ensure I understand the problem completely. In your repro steps, you don't say to call `Run` or `Start`.

**Comment by russellfoster** [comment]
May make more sense to look at the link, since it is basically the same issue. My service is rather large, I will need to recreate a new project. Will take some time.

**Comment by eerhardt** [comment]
> May make more sense to look at the link, since it is basically the same issue

I'm not 100% sure that is the case. They may be similar, but I'm not sure it is the exact same issue, since the underlying code is a lot different.

> My service is rather large, I will need to recreate a new project. Will take some time.

We can wait. It is better for us to understand your issue rather than guessing at the problem.

**Comment by ericstj** [comment]
I don't think a service can stop itself.  If it wants to stop itself, it needs to ask SCM to stop, then stop gracefully as SCM requests it to stop.

This is a bit of a layering question, does IHostApplicationLifetime sit above or below the service layer?  If above, then it should tell SCM to stop.  If below, then the current behavior could be seen as by design, and the alternative would be for an app to issue the stop to SCM rather than `IHostApplicationLifetime`.

**Comment by russellfoster** [comment]
@ericstj If what you are saying is true, then I guess there is no issue. The original issue that the provided link fixes was reported at:

[https://github.com/dotnet/aspnetcore/issues/5929](https://github.com/dotnet/aspnetcore/issues/5929)

Btw, I'm completely OK with what you are saying, just need some clarity because the issue I referenced was deemed to be a bug and they were calling StopApplication() from inside.

My use case is I want to restart the service from inside the service code. I can't find a good way to do this outside of Application.Exit(-1) with recovery options, which seems severe. Not sure how SCM would handle a child process that does this... say a child process calls stop, then start, would the start be guaranteed to get called or could the child process get taken out in the stop? Would it be better to replace the WindowsServiceLifetime with my own when building the host? Is that even a supported model? Any guidance would be much appreciated!

**Comment by eerhardt** [comment]
> Would it be better to replace the WindowsServiceLifetime with my own when building the host? Is that even a supported model? 

That is for sure a 100% supported scenario. The intention of the `IXXXLifetime` interfaces is to allow extensions/apps to replace them with their own logic. That's even how `WindowsServiceLifetime` gets injected. By default, the [`ConsoleLifetime` gets used](https://github.com/dotnet/runtime/blob/260a3069f38f48f7b562aada0b3839ed61d92f10/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.netcoreapp.cs#L16). But when you call `UseWindowsService()`, it injects the `WindowsServiceLifetime` instead:

https://github.com/dotnet/runtime/blob/260a3069f38f48f7b562aada0b3839ed61d92f10/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs#L61

**Comment by russellfoster** [comment]
@eerhardt Thanks, so that's the way I will go then for my implementation. I figured that I would need to find a way around this regardless, but wanted to bring this up as an issue since there seems to be some confusion around what StopApplication() actually does for a service, see:

[https://stackoverflow.com/questions/59499020/how-do-i-gracefully-shut-down-a-worker-service-from-within-itself](https://stackoverflow.com/questions/59499020/how-do-i-gracefully-shut-down-a-worker-service-from-within-itself)

[https://stackoverflow.com/questions/59879271/hosted-service-not-terminating-after-environment-exit](https://stackoverflow.com/questions/59879271/hosted-service-not-terminating-after-environment-exit)

[https://stackoverflow.com/questions/61679307/windows-service-using-backgroundservice-cannot-be-stopped](https://stackoverflow.com/questions/61679307/windows-service-using-backgroundservice-cannot-be-stopped)

Do you still need me to provide some example code?

**Comment by russellfoster** [comment]
Apologies all, I just tried the latest code, and the IsBackground = true change documented here [https://github.com/dotnet/extensions/issues/2836](https://github.com/dotnet/extensions/issues/2836) fixes the issue. Sorry about this and thanks for the help!
