### ISSUE TITLE
Add regex source generator tests that compare against known output

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#63300]
We want to pick some number of input expressions and validate that the generated C# matches the output we expect.  The expressions chosen should cover a wide range of features.

**Comment by stephentoub** [comment]
We should ensure we have coverage of all the various optimizations we do around IndexOf/LastIndexOf, to ensure those are kicking in as expected, e.g. https://github.com/dotnet/runtime/pull/68400.

**Comment by joperezr** [comment]
While this is still important, it is not a must-have for 7.0 so I'm changing the milestone so that it isn't tracked as blocking ZBB. I'll likely still get to this before 7.0 ships.
