### ISSUE TITLE
Native frames missing crashreport.json

### ISSUE THREAD

**Issue by kdubau** [dotnet/runtime#63309]
### Description

The crashreport.json file seems to be missing all native frames up until the first managed frame, except for the very first one, which is missing the `unmanaged_name` field. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2809202/147979173-dba2fa21-680a-43b7-8c94-d197f2d5e045.png)

### Reproduction Steps

Enabled the core dump, and the crash report, and induce a crash. Compare the json with what you see in LLDB with `clrstack -f`.

### Expected behavior

All stack frames should be in the json report. 

### Actual behavior

Missing frames. 

### Regression?

Yes, introduced with this PR https://github.com/dotnet/runtime/pull/60995

### Known Workarounds

None

**Comment by kdubau** [comment]
@mikem8361 I also just noticed, if you look at the first frame in the json, it's tagged `"is_managed": "true"` but it's a native frame.

**Comment by mikem8361** [comment]
This has been fixed in main/6.0 now.
