### ISSUE TITLE
Convert remaining SAL v1 annotations to SAL v2 annotations

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#63307]
#63261 converted `__in` and `__out` SAL v1 annotation to `_In_` and `_Out_` SAL v2 annotations. 

This issue tracks converting the remaining SAL v1 annotations to SAL v2 annotations.

**Comment by NN---** [comment]
https://samscode.blogspot.com/2015/02/sal-to-sal2-porting-guide.html

**Comment by NN---** [comment]
@jkotas Please take a look on the PR.
It is mostly search&replace work.
Thanks.
