### ISSUE TITLE
Socket ReceiveAsync method has bug when receiving multicast packets 

### ISSUE THREAD

**Issue by cokkiy** [dotnet/runtime#63327]
### Description

In centos8 the following codes work fine in net5, but not working on net6.

```c#
var socket=new Socket(Address.InterNetwork,SocketType.Dgram,ProtocolType. UDP) ;

var localEp=new IPEndpoint(IPAddress.Any,54444);
socket.Bind(localEp);
IPAddress grp=IPAddress.Parse("224.100.100.0);
IPAddress mcint=IPAddress.Parse("192.168.xx.xx");
MulticastOption mcOption=new MulticastOption(grp, mcint) ;
socket.SetSocketOption(SocketOptionLevel.IP,SocketOptionName.AddMembership,mcOption);
byte[] buf=new byte[4096];
var r=await socket.ReceiveAsync(buf,SocketFlags.None);
```
When send packets from another machine, on net5, the code works fine, but on net6, the receive method never returned. 
If changes the socket flags from none to SocketFlags.Multicast, the receive async method will return but throw operation not support socket exception. 
This also happens on EndReceiveFrom and EndReceiveMessageFrom methods. 

### Reproduction Steps

Run this codes on Centos8 or 7.

```c#
var socket=new Socket(Address.InterNetwork,SocketType.Dgram,ProtocolType. UDP) ;

var localEp=new IPEndpoint(IPAddress.Any,54444);
socket.Bind(localEp);
IPAddress grp=IPAddress.Parse("224.100.100.0);
IPAddress mcint=IPAddress.Parse("192.168.xx.xx");
MulticastOption mcOption=new MulticastOption(grp, mcint) ;
socket.SetSocketOption(SocketOptionLevel.IP,SocketOptionName.AddMembership,mcOption);
byte[] buf=new byte[4096];
var r=await socket.ReceiveAsync(buf,SocketFlags.None);
```

### Expected behavior

Receive the packet. 

### Actual behavior

Can't receive packets or throws socket exception. 

### Configuration

Centos 7 or 8 and net6 installed. 
The dotnet - - info output:
. Net SDK:
Version: 6.0.101
Commit: ef49f6213a

OS Name: centos
OS Version : 8

Host:
Version :6.0.1
Commit:3a25a7f1cc
...

**Comment by karelz** [comment]
Triage: If it is regression, we should understand why and decide if the fix it in 7.0 and potentially backport to 6.0 servicing.

**Comment by cokkiy** [comment]
Sorry maybe the firewalld blocked the packets, the dotnet6 installed machine not stop the firewalld service.

**Comment by cokkiy** [comment]
Sorry maybe the firewalld blocked the packets, the dotnet6 installed machine not stop the firewalld service.
