### ISSUE TITLE
NullReferenceException when closing HttpListener

### ISSUE THREAD

**Issue by kevingosse** [dotnet/runtime#63345]
### Description

We ran into an issue when trying to abort an HttpListener.

Our code looks like:

```csharp
try
{
    var ctx = _listener.GetContext();
    
    // Do stuff
}
catch (HttpListenerException)
{
    // listener was stopped,
}
catch (ObjectDisposedException)
{
    // the response has been already disposed.
}
catch (Exception) when (!_listener.IsListening)
{
    // we don't care about any exception when listener is stopped
}
```

At some point, another thread calls `Abort` on the HttpListener. This randomly causes `_listener.GetContext()` to throw a NullReferenceException:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.HttpListener.GetContext()
   at Datadog.Trace.TestHelpers.MockTelemetryAgent`1.HandleHttpRequests()
```

It seems it happens when trying to read `session.RequestQueueHandle` because `currentSession` is null: https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs#L511-L521
(it's set to null as a side-effect of calling `Abort`)

It didn't happen in .NET Core 3.1 and before, because there was no session object and the code would directly access the handle: https://github.com/dotnet/corefx/blob/release/3.1/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs#L588
```csharp
Interop.HttpApi.HttpReceiveHttpRequest(
    session.RequestQueueHandle,
```
The error code would then be handled and transformed into a `HttpListenerException`

Also, note that my code fails to catch the exception despite the `catch (Exception) when (!_listener.IsListening)` that was added in desperation. That's because the `Abort` method first sets the session to null (as part of `CloseRequestQueueHandle` and only updates the state at the very end:

https://github.com/dotnet/runtime/blob/dfd618dc648ba9b11dd0f8034f78113d69f223cd/src/libraries/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs#L397-L427

Since the method is going to update the state no matter what, I think it should try to do so as soon as possible.

### Reproduction Steps

It's a bit hard to reproduce because it's a tight race condition, but basically `HttpListener.GetContext()` has to be called at the same time as `HttpListener.Abort()`

### Expected behavior

`HttpListener.GetContext()` should throw either `HttpListenerException` or `ObjectDisposedException`.

### Actual behavior

`HttpListener.GetContext()` throws `NullReferenceException`

### Regression?

This worked fine in 3.1.

**Comment by karelz** [comment]
Triage: Looks like we should be able to check for null there and throw `ObjectDisposedException`. Or did you have different solution in mind @kevingosse?
Are you interested in putting up a PR @kevingosse?

**Comment by kevingosse** [comment]
> Triage: Looks like we should be able to check for null there and throw `ObjectDisposedException`. Or did you have different solution in mind @kevingosse? Are you interested in putting up a PR @kevingosse?

Yes I believe that's the right solution. I can prepare a PR tomorrow if nobody feels like taking care of it before then 🙂

**Comment by kevingosse** [comment]
In the end I decided to throw an `HttpListenerException` with the `ERROR_INVALID_PARAMETER` error code (mimicking the behavior of previous versions of .net core) instead of `ObjectDisposedException`. That's because the race condition can also happen when calling `Stop`, in which case the HttpListener is technically not disposed.
