### ISSUE TITLE
System.Text.Json 6.0.1 - Inclusion of build\System.Text.Json.targets file in NuGet package is causing failure in WiX Heat tool

### ISSUE THREAD

**Issue by jimivey** [dotnet/runtime#63379]
### Description

Our application relies on System.Text.Json, and our MSBuild process uses WiX to create an installer. Everything was working fine with System.Text.Json 5.0.2 and WiX 3.11.2.

When we updated our NuGet packages recently, the System.Text.Json update to 6.0.1 brought in a number of additional subdirectories, including a **build** directory that contains a **.targets** file. When our build process is running the **WiX Heat** tool, it now gets an error when it attempts to parse this new **.targets** file.

`heat.exe(0,0): error HEAT5305: Failed to load project ####.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  ####\packages\System.Text.Json.6.0.1\build\System.Text.Json.targets`

In earlier versions there was just a single **lib** directory with the files we needed. Now there are a number of additional directories (**build**, **buildTransitive**, **analyzers**), and the **.targets** file in the **build** directory is causing problems.

- Was including these directories intentional, or were they accidentally packaged into the 6.0.1 release?
- If their inclusion is intentional and will continue going forward, could that **.targets** file be cleaned up to work properly (or be ignored by) the WiX Heat tool? 

### Reproduction Steps

Visual Studio solution with a class library project referencing the System.Text.Json 6.0.1 NuGet package, and a WiX install project to build a web application installer.

### Expected behavior

WiX Heat tool should be able to parse .targets files distributed with the NuGet package.

### Actual behavior

WiX Heat tool fails with the following error (full solution path replaced with ####).

`heat.exe(0,0): error HEAT5305: Failed to load project ####.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  ####\packages\System.Text.Json.6.0.1\build\System.Text.Json.targets`

### Regression?

Yes, it worked fine in 5.0.2, which didn't include this **build** directory and the **System.Text.Json.targets** file.

### Known Workarounds

Added `xmlns="http://schemas.microsoft.com/developer/msbuild/2003"` to the `<Project>` element and the build succeeded without error.

But we don't know if that's the right approach. Should the new subdirectories (analyzers, build, buildTransitive) even exist in the NuGet package? If they should, could the .targets file be corrected in the distribution to support WiX Heat processing?

### Configuration

.NET version: .NET Framework 4.8
OS version: Windows 10
Architecture: x64
Visual Studio Enterprise 2019
WiX 3.11.2

**Comment by safern** [comment]
I would expect this to be a bug with the WiX Heat tooling to generate the package, it should not be including any files other than files under `lib` in the package. cc: @ericstj do you know where can we reroute this issue to?

**Comment by ericstj** [comment]
Agreed, and the nature of this issue is that heat is using a version of the MSBuild project evaluation libraries that doesn't understand SDK projects.   You can see similar issues filed here https://github.com/wixtoolset/issues/issues/5929

I recommend checking on newer versions of WiX that may work with newer MSBuild project types.  If you're still blocked file an issue in https://github.com/wixtoolset/issues.

cc @rseanhall @barnson
