### ISSUE TITLE
[API Proposal]: Analyzer for detecting multiple Enumerations

### ISSUE THREAD

**Issue by Cosifne** [dotnet/runtime#63381]
### Background and motivation

`IEnumerable` and `IEnumerable<T>` are well-known for their deferring execution ability. This might cause a performance issue since `IEnumerable<T>` collection might be easily enumerated multiple times, especially when using Linq.

We already received customers asking to have an analyzer that can help to detect such situations.
See https://github.com/dotnet/roslyn-analyzers/issues/3946
And I have already have an implementation of this analzyer here
https://github.com/dotnet/roslyn-analyzers/tree/features/IEnumerableAnalyzer

### API Proposal

**Analyzer Overview**
This analyzer will flag the 'IEnumerable' instance which might be enumerated more than once. 
Support three types: `IEnumerable`, `IEnumerable<T>` and `IOrderedEnumerable<T>.
It will only detect local and parameter. Fields will be ignored.
Example 1
```C#
public class Bar
{
    public void Bar2(IEnumerable<int> i)
    {
        [|i|].ElementAt(10);
        [|i|].ElementAt(1);
    }
}
```

Example 2
```C#
public class Bar
{
    public void Bar2(IEnumerable<int> i, IEnumerable<int> j)
    {
        var k = i.Concat([|j|]);
        k.ElementAt(10);
        [|j|].ElementAt(1);
    }
}
```

Example 3
```C#
public class Bar
{
    public void Bar2(IEnumerable<int> i)
    {
        [|i|].ElementAt(10);
        foreach (var a in [|i|]) { }
    }
}
```

**Message**: Possible multiple enumerations of 'IEnumerable' collection
**Description**: Possible multiple enumerations of 'IEnumerable' collection in this method. To prevent unnecessary enumerations, consider caching it first by calling a method such as 'ToList' or 'ToArray'.

**Category**: Performance
**Severity**: Disabled

There will be no code fix for this analyzer since we don't know which type the user wants to convert to. And code fix itself is pretty simple and straightforward.

**Implementation Details and Proposal**
The key problem of this analyzer is to know these types of methods.

1. Know if the method will enumerate the deferred type instance. 
Example Linq methods: `ElementAt`, `Aggregate`
```C#
i.ElementAt(10);
```
`ElementAt` will enumerated `i`.
These methods are hardcoded in the analyzer and only support methods under System.Linq.Enumerable. See [here](https://github.com/dotnet/roslyn-analyzers/blob/927495b3992d289ba63be8c62d321954e53b8412/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.cs#L53)
<details>
  <summary>Here is the full list of hard-coded methods:</summary>

```
ImmutableArray.ToImmutableArray,
ImmutableDictionary.ToImmutableDictionary,
ImmutableHashSet.ToImmutableHashSet,
ImmutableList.ToImmutableList,
ImmutableSortedDictionary.ToImmutableSortedDictionary,
ImmutableSortedSet.ToImmutableSortedSet,

System.Linq.Enumerable.Aggregate,
System.Linq.Enumerable.All,
System.Linq.Enumerable.Any,
System.Linq.Enumerable.Average,
System.Linq.Enumerable.Contains,
System.Linq.Enumerable.Count,
System.Linq.Enumerable.DefaultIfEmpty,
System.Linq.Enumerable.ElementAt,
System.Linq.Enumerable.ElementAtOrDefault,
System.Linq.Enumerable.First,
System.Linq.Enumerable.FirstOrDefault,
System.Linq.Enumerable.Last,
System.Linq.Enumerable.LastOrDefault,
System.Linq.Enumerable.LongCount,
System.Linq.Enumerable.Max,
System.Linq.Enumerable.Min,
System.Linq.Enumerable.Single,
System.Linq.Enumerable.SingleOrDefault,
System.Linq.Enumerable.Sum,
System.Linq.Enumerable.ToArray,
System.Linq.Enumerable.ToDictionary,
System.Linq.Enumerable.ToList,
System.Linq.Enumerable.ToLookup,
System.Linq.Enumerable.SequenceEqual,
System.Linq.Enumerable.MaxBy,
System.Linq.Enumerable.MinBy,
System.Linq.Enumerable.ToHashSet
```
</details>

2. Know if the method will defer enumerating the deferred type instance, and return a newly-created IEnumerable instance.
Example Linq methods: `Select`, `Where` and `Concat`
Example:
```C#
public void Bar(IEnumerable<int> i, IEnumerable<int> j)
{
    var k = [|i|].Concat(j);
    k.ElementAt(10);
    [|i|].ElementAt(100);
}
```
By knowing `Concat` is used as a 'Linq Chain', we will be able to know `k.ElementAt(10)` also enumerated `i`, and `j`.
<details>
  <summary>Here is the full list of hard-coded methods:</summary>

```
System.Linq.Enumerable.Append,
System.Linq.Enumerable.AsEnumerable,
System.Linq.Enumerable.Cast,
System.Linq.Enumerable.Distinct,
System.Linq.Enumerable.GroupBy,
System.Linq.Enumerable.OfType,
System.Linq.Enumerable.OrderBy,
System.Linq.Enumerable.OrderByDescending,
System.Linq.Enumerable.Prepend,
System.Linq.Enumerable.Reverse,
System.Linq.Enumerable.Select,
System.Linq.Enumerable.SelectMany,
System.Linq.Enumerable.Skip,
System.Linq.Enumerable.SkipWhile,
System.Linq.Enumerable.Take,
System.Linq.Enumerable.TakeWhile,
System.Linq.Enumerable.ThenBy,
System.Linq.Enumerable.ThenByDescending,
System.Linq.Enumerable.Where,
System.Linq.Enumerable.Concat,
System.Linq.Enumerable.Except,
System.Linq.Enumerable.GroupJoin,
System.Linq.Enumerable.Intersect,
System.Linq.Enumerable.Join,
System.Linq.Enumerable.Union,
System.Linq.Enumerable.Zip,
System.Linq.Enumerable.Chunk,
System.Linq.Enumerable.DistinctBy,
System.Linq.Enumerable.ExceptBy,
System.Linq.Enumerable.IntersectBy,
System.Linq.Enumerable.UnionBy,
System.Linq.Enumerable.TakeLast,
System.Linq.Enumerable.SkipLast
```
</details>
3. If this is not an Enumerable.Linq method, make the assumption based on [this](https://github.com/dotnet/roslyn-analyzers/pull/5304#issuecomment-887909817)

4. Some other special cases, I just find `System.Linq.Enumerable.AsEnumerable`, which just do a typecast. It only does a typecast and does not create new `IEnumerable` instance.
Example:
```C#
void Bar(IEnumerable<int> i)
{
      var j = [|i|].AsEnumerable();
      j.ElementAt(10);
      j.ElementAt(10);
}
```
In this case, we know `j` is `i`. So only flag `i`.
This is also hard-coded in the analyzer, see [here](https://github.com/dotnet/roslyn-analyzers/blob/927495b3992d289ba63be8c62d321954e53b8412/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AvoidMultipleEnumerations/AvoidMultipleEnumerations.cs#L127)

5. In all other cases, the passed in `IEnumerable` instance won't be considered as enumerated.

**Target Release Cycle**
We want to ship this in .net 6 and disable it by default. And in the future (.net 7), if we are satisfied with its behavior and performance, we would like to change the severity to 'IDESuggestion'.

### Alternative Designs

Instead of hard-coding all the methods under System.Linq.Enumerable in the Analyzer, we can add some attributes to indicate if the passed in `IEnumerable` would be enumerated or not. Then annotate the existing Linq Method using the attribute. This will also let the third-party function can use the analyzer.

1. [CauseEnumeration] attribute, can be put on method parameters, and indicate this parameter will be enumerated by this method.
Example
```C#
public static T MyElementAt([CauseEnumeration] this IEnumerable<T> source, int index)
```
This will tell the analyzer that `MyElementAt` enumerates `source`.

2. `[LinqChain]` on the method to support methods like `Concat` and `Select`, indicate the method will create a new `IEnumerable` instance, and defer enumerate all the passed in parameters.
Example 1:
```C#
[LinqChain]
public static IEnumerable<T> MyConcat(this IEnumerable <T> source1, IEnumerable<T> source2)
```
This will tell the analyzer `MyConcat` will defer enumerated `source1` and `source2`, and return a newly created `IEnumerable<T>` instance.

If someone is really want to create a method as a LINQ chain, but enumerated its parameter, he/she could do someting like this
```C#
[LinqChain]
public IEnumerable<int> MyLinqChainMethod(IEnumerable<int> i, [CauseEnumeration] IEnumerable<int> j)
{
     return i.Prepend(j.Last());
}
```

3. Know if the method won't enumerate the deferred-type instance. There is no Linq method does this, but it would be good to have an attribute to support cases like
```C#
public void AssertNotNull([NoEnumeration] IEnumerable<T> input)
{
      Assert(input != null);
}
``` 
here input is not enumerated, and this method doesn't work like 'LinqChain' because it doesn't return a new 'IEnumerable'.

### Risks

1. False positive. This analyzer will no doubt has false-positive results because the runtime type of the `IEnumerable<T>` might be a lot of other things, which might be noisy. 
Example:
```C#
public void Caller()
{
     var input = new int[10];
     Callee(input);
}

public void Callee(IEnumerable<int> input)
{
    input.ElementAt(10);
    input.Last();
}
```
For this case, the analyzer will still flag the `input` in `Callee`, because we don't know the real runtime type.

2. Perf. This analyzer is based on the DFA analyzer similar to the PlatformCompat Analyzer. Before it is enabled by default we need to have a good performance result.

**Comment by Cosifne** [comment]
@buyaa-n 
is there anything else I need to put in the document?
Also FYI @mavasani

**Comment by buyaa-n** [comment]
I have added Category and Severity level to your description, other than that got a few comments:
 - Attributes doesn't look like API proposal, but i guess for now we could decide if we want to add such attributes for supporting custom methods enumeration, then create another proposal for those attributes
 - `[NoEnumeration]` attribute looks useless to me, just do not add any attribute, looks there is just 2 case causes enumeration and not cause any enumeration

When you feel ready you can remove the `api-suggestion` label and add `api-ready-for-review` label so that it can be discussed in next API review

**Comment by pinkfloydx33** [comment]
For what it's worth, Jetbrains/R# annotations include similar attributes and I've found each of them useful in various situations. I realize the goal isn't parity with third parties, but figured I'd mention them since they are quite similar to the proposed and already exist (to a degree) in the wild:

- [NoEnumeration](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#NoEnumerationAttribute) 
- [LinqTunnel](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#LinqTunnelAttribute)
- [InstantHandle](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#InstantHandleAttribute) (multi-purposed, used for delegates and enumerables)

**Comment by Cosifne** [comment]
> I have added Category and Severity level to your description, other than that got a few comments:
> 
> * Attributes doesn't look like API proposal, but i guess for now we could decide if we want to add such attributes for supporting custom methods enumeration, then create another proposal for those attributes
> * `[NoEnumeration]` attribute looks useless to me, just do not add any attribute, looks there is just 2 case causes enumeration and not cause any enumeration
> * Could you add the list of hard-coded APIs into the description instead of a link so that it was visible during the review
> 
> When you feel ready you can remove the `api-suggestion` label and add `api-ready-for-review` label so that it can be discussed in next API review

Probably I can put it in the Alternative Designs part.

**Comment by bartonjs** [comment]
* The consensus seems to be that the analyzer has value
* There was one "vote" for changing the category to Reliability, but the consensus was to leave it at Performance
* There's no strong opinion on servicing it into the .NET 6 SDK or merely adding it to the next version of the NuGet package
* This analyzer needs a lot of comprehensive documentation, demonstrating various ways that `i.ElementAt(10); i.ElementAt(100);` could be re-written (`ToList()` is not always a winning move)
* The initial version should use the hard-coded list plus extensibility via editorconfig
  * "Assume iterating" vs "assume non-iterating" needs more data.

**Comment by carlossanlop** [comment]
@Cosifne can we close the issue now that https://github.com/dotnet/roslyn-analyzers/pull/5882 has been merged, or was there anything else pending to address?

**Comment by Cosifne** [comment]
> @Cosifne can we close the issue now that [dotnet/roslyn-analyzers#5882](https://github.com/dotnet/roslyn-analyzers/pull/5882) has been merged, or was there anything else pending to address?

Documentation working is not complete. I will close this issue as soon as it gets done.
