### ISSUE TITLE
Ensure we are building against LTTng with latest fixes

### ISSUE THREAD

**Issue by josalem** [dotnet/runtime#63407]
I confirm that the issue sat squarely within lttng-ust, so I don't expect anything to be needed in the .NET runtime to fix this, except rebuilding the .NET runtime probe providers against a fixed lttng-ust.

_Originally posted by @compudj in https://github.com/dotnet/runtime/issues/62398#issuecomment-1006012517_

**Comment by jkoritzinsky** [comment]
lttng comes with the ubuntu rootfs we build against. We can't easily make changes to that or provide an lttng provider built against a newer lttng version.
