### ISSUE TITLE
AddNETStandardCompatErrorFileForPackaging should allow for libraries to add their own buildTransitive logic

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#63413]
In trying to fix https://github.com/dotnet/runtime/issues/63246, I need the `Microsoft.Extensions.Configuration.UserSecrets` package to contain its own custom logic in the `buildTransitive` folder. However, in doing that, it conflicts with the `buildTransitive` logic injected into projects by `AddNETStandardCompatErrorFileForPackaging`:

https://github.com/dotnet/runtime/blob/ec5471c248a944ff7a1d642c1200d49ab349bef1/eng/packaging.targets#L194-L198

This is because the UserSecrets library needs to put logic in `buildTransitive/netstandard2.0`. But `AddNETStandardCompatErrorFileForPackaging` adds a placeholder (`_._`) file into `buildTransitive/net6.0`. That means the `netstandard2.0` logic isn't getting executed for a `net6/7` project.

To unblock #63246, I am going to disable `AddNETStandardCompatErrorFileForPackaging` for this library. This is OK to do because it references other packages that target the exact same TFMs and has this same compat logic. So the UserSecrets package will rely on those dependent packages for this error.

If we need more libraries to contain their own `buildTransitive`, we should have a way for that logic to not conflict with this compatibility logic.

cc @ericstj @ViktorHofer @safern

**Comment by eerhardt** [comment]
> If we need more libraries to contain their own buildTransitive

Two other libraries that I thought of that would need this is System.Text.Json and Microsoft.Extensions.Logging.Abstractions, because they have build logic to get the correct source generator version loaded. But that logic is in `build` and not `buildTransitive`. In order to fix #60870, we would need this fixed. So the buildTransitive logic gets combined.

**Comment by safern** [comment]
Maybe a way to do this would be to have a convention where we import all .targets files from the buildTransitive directory, we could add this to the content we include in the targets file we generate to throw the error that the tfm is no longer supported.

Something like: 
```xml
<Import Project="$(MSBuildThisFileDirectory)\**\*.targets" />
```

Or if we want to be less flexible on what we import, we could have an itemgroup that lists the name of .targets files that we want to be imported that these projects could set and then we could generate an import per .targets file included in the itemgroup at build time of the package.

This would be done here:
https://github.com/dotnet/runtime/blob/ec5471c248a944ff7a1d642c1200d49ab349bef1/eng/packaging.targets#L203-L208

**Comment by safern** [comment]
I like the *.Before.targets and *.After targets approach. I think that'd work well and make ordering predictable for package authors.
