### ISSUE TITLE
[Test] LibariesConfiguration should automatically be detected for runtime tests

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#63412]
Currently, if the libraries are built in a configuration other than Release, one must pass the `LibrariesConfiguration=<configuration>` msbuild property when building the runtime tests. This is an annoyance repeateldy encountered by developers using the runtime tests locally.

However, it should be possible to automatically detect the configuration by looking at the runtime pack folder.

If both exist, it should default to Release (as it currently looks to Release by default).

**Comment by SamMonoRT** [comment]
This is an improvement, not necessarily a needed change. Closing this issue.
