### ISSUE TITLE
Delegates are poorly inlined and optimized

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63425]
## Example without using delegate
```cs
    public int AddFunc(int a, int b) {
        return a + b;
    }
```   

## Example with delegate

```cs
    public int DelegateFunc(int a, int b) {
        Func<int, int, int> e = delegate(int c, int d) {
            return a + b;
        };
        return e(a, b);
    }
```

## Analysis

See [sharplab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAQQAmY4gFYAFIOHY0DeQ2ABKDlx7biAdgbYGAalUBuLdwC+FhjfrKhDACIwANjADm2DDGlzHig7C6prU2jpSADzySjFBAHwMMAwAvAxibp7eMP7CYLGOYhqcYeFlegbGZjbalual5fo5ger1tTSWQA===

[Stopwatch benchmark without Benchmark.NET](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIgBgAIiyUBuauxsgOgBEBLAIYBzPBADOGPmDFsq1SHgn0+eDMowwoAyREX0AvPTIB9WmdNnZAGT4SAPCowA+egDcBAGxwwxB+nhgAd3obe0cnAAoASllqAGUMCAAHQO0wAAt6MT4AWySPGABBABNivwDghOTUjAzo2SqUtMzimAKhbSLS8qD6Rpq6mOpqEuKiAFYI7LyC0bQ3T28xebJ5kiGqHjaYDo0JiNb2zrmFrx8VtY32MgBOCIASACI43PyYelGQegBvabfRrgAUQ8AiSYhgxQAsnwPB5bDAFMUxABfHJiR4bJh3J5bI4aD6lL7fQ47Y6lIEgsEQ6Gw+GIlFojGxGhkJCMFAEsaTfrNLKBeahDAOVQuOESeaOegCCWqejAKI/aj0ZV8rgJARQDD1JUqgBm0Ai7igyj8tBYJrs6k02j4uhkygA1A6Fd8dSqVWKMFxRhEBPQHXKNu7kW7VY1tVQQ1R3dc2UQObjSXtuYkmrVMmJ+SFbELwvRPTK1NLlLL5YroyqJsKMIXCy53oYSbsYBFJWBC/Rii7Q+6iAB2KX+uWyYMjlWZtUYDVaoN6g1Gk2GM0Wq1aHSKc18J3divu5We72lCIt4vy2fKqPuifhjbIoA=)

On the one hand, of course, all the code to instantiate a delegate function is created, however, the actual code executed is also very poorly optimized.

### AddFunc
```asm
    L0000: lea eax, [rdx+r8]
    L0004: ret
````

### Content of Func<int, int, int>
```asm
    L0000: mov eax, [rcx+8]
    L0003: add eax, [rcx+0xc]
    L0006: ret
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/runtime/issues/56708, https://github.com/dotnet/runtime/issues/6498, https://github.com/dotnet/runtime/issues/4584, ...

**Comment by deeprobin** [comment]
@stephentoub Super. Thanks I have probably overlooked.
