### ISSUE TITLE
[quesion] mono touch hold monoobject* in internal call behavior?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#63440]
I add internal call(called during gc safe mono) using `mono_add_internal_call`, 

```c
mono_add_internal_call("xxxx::test", Internal_test);
```

and the `Internal_test` source code is:
```c
void Internal_test()
{
	MonoString* objs[1000];
	uint32_t handles[1000];
	for (int index = 1; index < 1000; index++)
	{
		objs[index] = mono_string_new(mono_domain_get(), "testsssssssssssssssssss");
		handles[index] = mono_gchandle_new((MonoObject*)objs[index], false);
	}
	mono_gc_collect(1);
	mono_gc_collect(1);
	for (int index = 1; index < 1000; index++)
	{
		if (objs[index] != (MonoString*)mono_gchandle_get_target(handles[index]))
		{
			int a = 1;  // this line not exeucte,
		}
	}
}
```

as this https://www.mono-project.com/docs/advanced/runtime/docs/coop-suspend/ said, in the `gc safe mode` we can‘t touch Managed object, but why after gc collect the MonoString obj not moved, 

> objs[index] always equals (MonoString*)mono_gchandle_get_target(handles[index])

it seems that the managed objects which return from gc unsafe function in the internal call will not move and it is safe to touch.
this is because the managed objects will pined when entering gc safe?

Am I understanding right here?

**Comment by srxqds** [comment]
@lambdageek  @lateralusX  can you help me figure the confusion?

**Comment by lambdageek** [comment]
The objects are not moving because of this:
```c
   MonoString* objs[1000];
```

That means you have 1000 pointers allocated on the stack.

Mono uses conservative stack scanning during garbage collection.  If it sees a value that looks like a pointer on the stack, it will pin that object, and the garbage collector won't move it.

You can change your code slightly to allocate the array of pointers on the heap instead.  Then mono won't see the pointers during scanning and it will move the objects. 

```c
  typedef struct {
    MonoObject *objs[1000];
  } ObjectArray;

void Internal_Test(void) {
       ObjectArray *o = malloc (sizeof (ObjectArray)); // allocate 1000 pointers on the heap, instead of the stack
        uint32_t handles[1000];
	for (int index = 1; index < 1000; index++)
	{
		o->objs[index] = mono_string_new(mono_domain_get(), "testsssssssssssssssssss");
		handles[index] = mono_gchandle_new((MonoObject*)o->objs[index], false);
	}
	mono_gc_collect(1);
	mono_gc_collect(1);
	for (int index = 1; index < 1000; index++)
	{
		if (o->objs[index] != (MonoString*)mono_gchandle_get_target(handles[index]))
		{
			int a = 1;  // this should execute now
                         fprintf(stderr, "objects moved\n");
		}
	}
       free (o);
}
```

(It might still pin some objects if the C compiler used temporary variables internally to hold the result of `mono_string_new` or the argument to `mono_gchandle_new`

**Comment by srxqds** [comment]
so if I put the managed object pointer on the stack local variable, it will not be moved so we can touch it?

and this feature behavior consistency cross platform such as android, ios , maocs?

**Comment by srxqds** [comment]
> The objects are not moving because of this:
> 
> ```c
>    MonoString* objs[1000];
> ```
> 
> That means you have 1000 pointers allocated on the stack.
> 
> Mono uses conservative stack scanning during garbage collection. If it sees a value that looks like a pointer on the stack, it will pin that object, and the garbage collector won't move it.
> 
> You can change your code slightly to allocate the array of pointers on the heap instead. Then mono won't see the pointers during scanning and it will move the objects.
> 
> ```c
>   typedef struct {
>     MonoObject *objs[1000];
>   } ObjectArray;
> 
> void Internal_Test(void) {
>        ObjectArray *o = malloc (sizeof (ObjectArray)); // allocate 1000 pointers on the heap, instead of the stack
>         uint32_t handles[1000];
> 	for (int index = 1; index < 1000; index++)
> 	{
> 		o->objs[index] = mono_string_new(mono_domain_get(), "testsssssssssssssssssss");
> 		handles[index] = mono_gchandle_new((MonoObject*)o->objs[index], false);
> 	}
> 	mono_gc_collect(1);
> 	mono_gc_collect(1);
> 	for (int index = 1; index < 1000; index++)
> 	{
> 		if (o->objs[index] != (MonoString*)mono_gchandle_get_target(handles[index]))
> 		{
> 			int a = 1;  // this should execute now
>                          fprintf(stderr, "objects moved\n");
> 		}
> 	}
>        free (o);
> }
> ```
> 
> (It might still pin some objects if the C compiler used temporary variables internally to hold the result of `mono_string_new` or the argument to `mono_gchandle_new`)

how can monovm detect the stack variable, which part source codes handle this?

**Comment by lambdageek** [comment]
@srxqds This is the line that does it:

https://github.com/dotnet/runtime/blob/5a0f438aa308479783c1f0b53c34c57cc63e2bf0/src/mono/mono/metadata/sgen-mono.c#L2338-L2367

When a thread starts, or when a thread is attached to Mono, we ask the OS for the location of the stack for that thread.  When a thread is suspended, we find out what it's current stack pointer is.  All that stuff is stored in the `MonoThreadInfo`.  Then when the main GC thread goes through all the MonoThreadInfo for every thrread and calls `sgen_conservatively_pin_objects_from()` which pins all the objects.

**Comment by srxqds** [comment]
make sense, thank you
