### ISSUE TITLE
Json SourceGen tests are not running on .NET Framework

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#63463]
These tests are using an undefined `$(NetFrameworkCurrent)` property. This means the tests aren't running on .NET Framework because this property is blank:

https://github.com/dotnet/runtime/blob/634dfa13d89800e629db86f0b947590fb0ffb077/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Unit.Tests/System.Text.Json.SourceGeneration.Unit.Tests.targets#L3

https://github.com/dotnet/runtime/blob/634dfa13d89800e629db86f0b947590fb0ffb077/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Tests/System.Text.Json.SourceGeneration.Tests.targets#L3

We should also fix this one place in the docs that is using this incorrect property:

https://github.com/dotnet/runtime/blob/331823f4046da1530dd950ac3ad8a87b3cdd584d/docs/coding-guidelines/project-guidelines.md#L52-L57

**Comment by jkotas** [comment]
The change was reverted in https://github.com/dotnet/runtime/pull/64108
