### ISSUE TITLE
[wasm] Make WasmMainJSPath optional

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#63465]
There are use-cases when there is no main javaScript file. 
For example with NextJs where we don't own application startup.

src\mono\wasm\build\WasmApp.targets
```
<Error Condition="'$(WasmMainJSPath)' == ''" Text="%24(WasmMainJSPath) property needs to be set" />
```

src\tasks\WasmAppBuilder\WasmAppBuilder.cs
```
if (!File.Exists(MainJS))
    throw new LogAsErrorException($"File MainJS='{MainJS}' doesn't exist.");
```

**Comment by pavelsavara** [comment]
cc @radical @danroth27

**Comment by danroth27** [comment]
I hit this as well when looking at using .NET from existing JS apps: #77191
