### ISSUE TITLE
Find a way to get data from embedded resource without reflection

### ISSUE THREAD

**Issue by musictopia2** [dotnet/runtime#63488]
Currently, if a file is in resource, reflection is required in order to get the assembly name in order to capture the file information.
Wish there can be an alternative where somebody can still get the embedded resource without any reflection to improve performance.
Unfortunately, found if I chose to save as c# string,  if there are too many of them, then gives a runtime error because the string lengths was too large.

**Comment by teo-tsirpanis** [comment]
Hello @musictopia2, using reflection to access information about your assemblies is typically fast; they are just data somewhere in memory. If you haven't already done it, I would advise you to profile your application to ensure that getting embedded resources is an actual bottleneck. In other words, "reflection" doesn't always mean "slow". Invoking members via reflection is usually slow(er), but simple introspection of assemblies isn't.

Or are you one-off loading an assembly to inspect its embedded resources without invoking any code, and want to avoid the CLR's assembly (un)loader's overhead? In this case you can use the [`System.Reflection.MetadataLoadContext`](https://docs.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext) class and keep your existing reflection-based code the same, or if you want even more performance you can use the `System.Reflection.Metadata` package.

**Comment by buyaa-n** [comment]
@musictopia2 is the above suggestion helps your issue? If not It would be helpful if you provide more info about your issue
