### ISSUE TITLE
Test failure System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(size: 1000)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63487]
Run: [runtime-coreclr libraries-jitstress 20220105.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1538736&view=ms.vss-test-web.build-test-results-tab&runId=43545312&resultId=178218&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitminopts-Windows.10.Amd64.Open

- System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(size: 1000)

```
**Error message:**
```
Allocated too much: start: 5092432 end: 5102932 size: 1000
Expected: True
Actual:   False


Stack trace
   at System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(Int32 size) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 800
```

**Comment by danmoseley** [comment]
Hit again. @mangod9 could this test please be robustified or disabled? It's failing about once a week. Seems to be across all OS, bitness, and flavors.

```
    System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(size: 1000) [FAIL]
      Allocated too much: start: 14354592 end: 14364904 size: 1000
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Runtime/tests/System/GCTests.cs(800,0): at System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(Int32 size)
    System.Tests.DateTimeOffsetTests.ToLocalTime_MaxValue [SKIP]
```


```kusto
TestResults
//| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-180d)
| where Result == "Fail"
//| where WorkItemFriendlyName == "System.Composition.Hosting.Tests"
//| where Type == "System.Composition.Hosting.Core.Tests.ExportDescriptorPromiseTests"
| where  Method == "GetAllocatedBytesForCurrentThread"
//| where Message contains "OSStatus error -50 - failed to generate asymmetric keypair"
| project 
  //Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
//  Result,
  Finished,
//  Duration,
//  Method,
//  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline_Configuration|OS|Arch|Test|Finished|Message|
|---|---|---|---|---|---|
|Release|ubuntu.1804.armarch.open|arm|test/functional/cli/innerloop/|2021-11-23 23:18:59.6340000|Allocated too much: start: 9734060 end: 9747656 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.open.rt|x86|test/functional/cli/innerloop/|2021-11-30 01:02:45.4700000|Allocated too much: start: 5029520 end: 5042884 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.11.amd64.clientpre.open|x64|test/functional/cli/innerloop/|2021-12-01 22:10:07.5560000|Allocated too much: start: 26639448 end: 26664288 size: 1000<br>Expected: True<br>Actual:   False|
|Release|windows.10.amd64.server19h1.es.open.rt|x86|test/functional/cli/innerloop/|2021-12-06 14:25:36.5950000|Allocated too much: start: 5157324 end: 5184180 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.11.amd64.clientpre.open|x64|test/functional/cli/innerloop/|2021-12-06 20:57:01.0520000|Allocated too much: start: 37395784 end: 37447800 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.serverrs5.open.rt|x64|test/functional/cli/innerloop/|2021-12-08 19:21:36.2060000|Allocated too much: start: 18278552 end: 18303728 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.es.open.rt|x64|test/functional/cli/innerloop/|2021-12-10 12:59:19.3700000|Allocated too much: start: 6354464 end: 6379584 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.open.rt|x86|test/functional/cli/innerloop/|2021-12-13 22:38:49.2860000|Allocated too much: start: 4722380 end: 4736032 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.serverrs5.open.rt|x64|test/functional/cli/innerloop/|2021-12-14 20:08:20.4770000|Allocated too much: start: 13789160 end: 13814264 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.es.open.rt|x64|test/functional/cli/innerloop/|2021-12-16 02:19:47.1820000|Allocated too much: start: 5932664 end: 5957784 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|osx.1015.amd64.open|x64|test/functional/cli/innerloop/|2021-12-16 16:02:24.5510000|Allocated too much: start: 5642296 end: 5651016 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.11.amd64.clientpre.open|x64|test/functional/cli/innerloop/|2021-12-18 11:31:25.9540000|Allocated too much: start: 6698296 end: 6723544 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|ubuntu.1804.amd64.open.rt|x64|test/functional/cli/innerloop/|2021-12-21 22:38:58.9330000|Allocated too much: start: 5672128 end: 5724024 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.7.amd64.open.rt|x86|test/functional/cli/innerloop/|2021-12-22 14:51:22.9370000|Allocated too much: start: 5319912 end: 5346660 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.serverrs5.open.rt|x64|test/functional/cli/innerloop/|2021-12-23 04:29:02.6730000|Allocated too much: start: 13938312 end: 13963400 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.open.rt|x86|test/functional/cli/innerloop/|2021-12-23 20:08:47.0500000|Allocated too much: start: 4783760 end: 4797412 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.81.amd64.open.rt|x64|test/functional/cli/innerloop/|2021-12-29 17:32:08.4400000|Allocated too much: start: 9651256 end: 9676344 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.serverrs5.open.rt|x64|test/functional/cli/innerloop/|2022-01-05 21:52:25.2420000|Allocated too much: start: 5696792 end: 5748648 size: 1000<br>Expected: True<br>Actual:   False|
|Release|windows.10.amd64.open.rt|x86|test/functional/cli/innerloop/|2022-01-06 08:31:59.4820000|Allocated too much: start: 5092432 end: 5102932 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.10.amd64.server19h1.es.open.rt|x64|test/functional/cli/innerloop/|2022-01-11 21:04:47.4310000|Allocated too much: start: 9898936 end: 9924056 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|windows.11.amd64.clientpre.open|x64|test/functional/cli/innerloop/|2022-01-19 18:23:38.8060000|Allocated too much: start: 11903488 end: 11928736 size: 1000<br>Expected: True<br>Actual:   False|
|Debug|osx.1014.amd64.open|x64|test/functional/cli/innerloop/|2022-01-20 01:42:52.4430000|Allocated too much: start: 14354592 end: 14364904 size: 1000<br>Expected: True<br>Actual:   False|

it's creating a 1000 char string and expecting to see allocated increase by < 5000

The test seems to assume that a 1000 char string allocates 1000 bytes. but nevertheless 2000 < 5000.

The diffs (expected to be < 5000) from above are below. Changing 5x to 11x would seem to fix this.
```
5049.6
5020.8
5017.6
2062.4
5035.2
4968
10403.2 // highest
2730.4
2730.4
2672.8
2100
5371.2
5349.6
1744
10379.2
10371.2
5024
5024
5049.6
5017.6
2719.2
5024
```
@cshung given this code:
```c#
            long start = GC.GetAllocatedBytesForCurrentThread();

            GC.KeepAlive(new string('a', 1000));

            long end = GC.GetAllocatedBytesForCurrentThread();
```
is it surprising to you that end and start sometimes differ by over 10KB?

**Comment by mangod9** [comment]
Yeah we will take a look to determine why these have been failing intermittently.

**Comment by Maoni0** [comment]
doesn't seem like this should belong to regions investigation - it's been failing for quite some time.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220317.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1668019&view=ms.vss-test-web.build-test-results-tab&runId=45836270&resultId=174247&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open

- System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(size: 1000)

```
**Error message:**
```
Allocated too much: start: 8546624 end: 8587920 size: 1000
Expected: True
Actual:   False


Stack trace
   at System.Tests.GCExtendedTests.GetAllocatedBytesForCurrentThread(Int32 size) in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 800
```

**Comment by mangod9** [comment]
this was early in regions enablement. Closing for now -- please reopen if it reoccurs.
