### ISSUE TITLE
Improve code readability by using extention methods

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#63485]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Improve-code-readability-by-using-extent/1623078)._

---
Hi,

The continuous improvements to the language to make it easier and more understandable are impressive. In the same concept, consider the following snippet

``` csharp
var myName = GetName();
if (!string. IsNullOrEmpty(myName)) Console.Writeline(myName);
```

It would be more readable if we could do this
``` csharp
var myName = GetName();
if (myName.IsNotNullOrEmpty()) Console.Writeline(myName);
```

Notice that this example captures both IsNullOrEmpty() becoming an extension, but also adding negation methods to promote readability instead of using the '!' character.
I am not agains the usage of '!', but having the option to interpret the code in a more human way helps non C# developers get into the language.

This could also be applicable to other types, but strings are the ones I'm exposed the most to.

Thanks,
Nuno Aguiar

---
#### Feedback Bot on 12/23/2021, 07:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by CyrusNajmabadi** [comment]
Note: user could add tehse extensions.  But i'm, guessing they want us to supply them.

**Comment by ygra** [comment]
I'm not sure there are even extension methods in the BCL that can be called on `null` values. Typically they mimic normal instance methods and verify their first argument to be non-`null`. Which makes sense, considering how they are typically called.

If you're just seeing that code, you wouldn't necessarily know that that's an extension method and to even understand how it could work, you'd have to be aware of what extension methods actually are and how they work.

Yes it makes things a bit terser, but also requires the reader to know about more language features to understand why the code works and deduce that this particular method call won't throw when `myName` is `null`.

**Comment by stephentoub** [comment]
> It would be more readable if we could do this

FWIW, I find that less readable, as I don't know how to parse "IsNotNullOrEmpty"... is that "IsNot(NullOrEmpty)" or "Is(NotNull)OrEmpty".

Regardless, while I appreciate the suggestion, we typically do not add such methods.  Lots of subtly different methods make discoverability harder, so while the intent is to make things easier, it can often have the inverse effect.  Developers have to know about `!` in C# as it's a critical part of the language, and we rely on composability to build up the semantics a developer needs.
