### ISSUE TITLE
interface like mono_domain_create_appdomain is declared but there is no implemention.

### ISSUE THREAD

**Issue by EnoroF** [dotnet/runtime#63494]
### Description

interface like mono_domain_create_appdomain is declared but there is no implemention.
It is declared in appdomain.h while i can not find any implemention in appdomain.cpp. Error occurred when I use this unimplement function.

### Reproduction Steps

call mono_domain_create_appdomain in any cpp file.

### Expected behavior

can not find implemention for mono_domain_create_appdomain  while link mono lib

### Actual behavior

compiler will show it.

**Comment by lambdageek** [comment]
Yea, looks like we accidentally deleted this function when we were migrating to dotnet/runtime.

I'll add it back.

But, @EnoroF - the implementation is going to be:
```c
MonoDomain *
mono_domain_create_appdomain (char *friendly_name, char *configuration_file)
{
	return NULL;
}
```

ie: it won't actually create a new app domain.  creating additional AppDomains is not supported in .NET 6 using MonoVM.

**Comment by lambdageek** [comment]
CoreCLR and Mono do not support creating new appdomains in .NET 5+

**Comment by EnoroF** [comment]
Got it. Thx~
