### ISSUE TITLE
VN does not number some HWI loads properly

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#63499]
Reproduction:
```cs
using System;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

unsafe
{
    var dbls = stackalloc double[] { 1, 1 };
    Console.WriteLine(Problem(dbls));
}

[MethodImpl(MethodImplOptions.NoInlining | MethodImplOptions.AggressiveOptimization)]
static unsafe bool Problem(double* a)
{
    const double Mask = -0.0;

    var v1 = Avx.MaskLoad(a, Vector128.Create(0, Mask));
    if (v1.GetElement(0) == 0)
    {
        var v2 = Avx.MaskLoad(a, Vector128.Create(Mask, 0));
        if (v2.GetElement(0) == 0)
        {
            return true;
        }
    }

    return false;
}
```
Expected result: `false`.
Actual result: `true`.

Cause: in the below VN code we only encode the value of the address operand:

https://github.com/dotnet/runtime/blob/a71f261010ace01eaceaeef2a70bf2f5807a028b/src/coreclr/jit/valuenum.cpp#L9601-L9622

We need to encode the value of the second parameter (if it is present) as well.

FYI @tannergooding

**Comment by SingleAccretion** [comment]
VN also doesn't account for the fact `LoadHigh`-family of intrinsics have the address as the second operand, not the first.

**Comment by SingleAccretion** [comment]
Another issue: "helper" intrinsics, i. e. the recently added V128 ones, aren't accounted as a memory load for at all.

**Comment by tannergooding** [comment]
> Another issue: "helper" intrinsics, i. e. the recently added V128 ones, aren't accounted as a memory load for at all.

These ones should be handled on import by converting them to the relevant actual intrinsics.
