### ISSUE TITLE
What is the purpose of hashing in a PDB Document?

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#63505]
[The Portable PDB spec](https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/specs/PortablePdb-Metadata.md#DocumentTable) defines a `Document` as consisting of `Name`, `HashAlgorithm`, `Hash`, and `Language` values.  The first and last are explained pretty clearly, but the word "hash" only appears in this section of the spec, and only to mention that such things exist and that there are a few reserved hash algorithms.  It says nothing about what it is that's supposed to be hashed, what its purpose is, or whether the hashing is required or optional.

Could we get some clarification on this subject?

**Comment by buyaa-n** [comment]
@tmat might answer that question

**Comment by tmat** [comment]
Hash is if the file content using the specified algorithm. It is used to validate that a source file matches the one use by the compiler when compiling the source code.
