### ISSUE TITLE
Avoid global:: qualifying all names in the Regex source generator

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#63512]
Blocked on dotnet/csharplang#5529

In the Regex source generator, we currently fully-qualify with global:: every name to something in the core libraries, e.g. `global::System.MemoryExtensions.IndexOf(span, value)` rather than `span.IndexOf(value)`.  This is done to avoid accidentally referencing something of the same name in the user's code, but it also leads to generating code that's much harder to read (and the generator itself is more verbose).

Once we have a solution to dotnet/csharplang#5529, we can spit the Regex-derived type into its own namespace, and put usings _inside_ that namespace for all of the `System.*` namespaces we consume.  At that point, we will no longer need to fully-qualify and can go back to using simple names, using extension methods as extensions, etc.

**Comment by stephentoub** [comment]
cc: @jaredpar

**Comment by ShreyasJejurkar** [comment]
Wouldn't aliasing work here in this case!?

`using SystemStringBuilder = System.Text.StringBuilder`

**Comment by stephentoub** [comment]
> Wouldn't aliasing work here in this case!?
> using SystemStringBuilder = System.Text.StringBuilder

No.  Beyond that resulting in similarly less readable code, it doesn't actually solve the problem.
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPjCYCmKAOEAxjgAQCqKOATgHQAiOAZrDgCYCwAUAN7ekDSAAQBMwgIwBlBNVgBzAEIBXKABs2NUj1IBfbnq7csuAsTKUaDZq069+goQAYJ02TEUr1mgLwTaAFRwADwRaV3llNQ1qAG57AVgEGixVUioIVXZhMQBheK18wWEAZgkANmEAFlIAWQAKAEpCwT4uIvbBGBwAdxcZCM9oxoCAe3D3Rri2jt18gx0gA==

**Comment by gfoidl** [comment]
This should / could also be done for e.g. the LoggerMessages generated by the source generator.

**Comment by stephentoub** [comment]
Yes,  I'm using Regex as a case study for all of these as it's new in 7, but we should adopt similar strategies for our other generators, including the DllImport generator that's also new in 7.
