### ISSUE TITLE
Minimal record definition with camel case deserialization uses Pascal Case

### ISSUE THREAD

**Issue by lukino563** [dotnet/runtime#63542]
System.Text.Json and ASP.NET issue

When I use source maps generator for System.Text.Json
`public sealed record CreateDeviceCommand(
    [property: JsonIgnore] string UserId,
    Guid? DeviceId,
    string DeviceName
) : IRequest<DeviceModel>;
`

which is record without any explicit definition it will generate wrong System.Text.Json source maps:
`
private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] CreateDeviceCommandCtorParamInit()
        {
            global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[3];
            global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues info;
        
            info = new()
            {
                Name = "UserId",
                ParameterType = typeof(global::System.String),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::System.String)
            };
            parameters[0] = info;
        
            info = new()
            {
                Name = "DeviceId",
                ParameterType = typeof(global::System.Nullable<global::System.Guid>),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(global::System.Nullable<global::System.Guid>)
            };
            parameters[1] = info;
        
            info = new()
            {
                Name = "DeviceName",
                ParameterType = typeof(global::System.String),
                Position = 2,
                HasDefaultValue = false,
                DefaultValue = default(global::System.String)
            };
            parameters[2] = info;
        
            return parameters;
        }
`
I have described in attributes that I want camelcase but these are Capitalized like pascal case. 
Serialization works but Deserialization throws exception. When I use classes or record with constructor which have camelcase parameters it works. But I want minimal code and this is problematic for me.

Exception on deserialization:
`
System.InvalidOperationException: Each parameter in the deserialization constructor on type 'WHIB.Server.Features.Device.Command.CreateDeviceCommand' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.
`

I think that this is bug when I want camelCase but on deserialization pascal case is used.

**Comment by eiriktsarpalis** [comment]
Hi @lukino563, would it be possible to share a minimal, standalone reproduction so we can better understand the nature of the problem? There seem to be a few missing dependencies here (like that `IRequest` interface).
