### ISSUE TITLE
Inefficient codegen using `for` instead of a simple `while`-loop

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63544]
I noticed that writing a use a simple for loop in my case generates more code than a `while(true)` loop with `break`.

Here it should be noted that a for loop is lowered to a while loop, but the equivalent code is larger there.

### Initial source

```cs
    private static void A(ref int i) {
        while(true) {
            i++;
            
            if(i > 10) break;
        }
    }
```

### Lowered source

```cs
    private static void A(ref int i)
    {
        while (true)
        {
            i++;
            if (i > 10)
            {
                break;
            }
        }
    }
```

### JIT Asm

```asm
Program.A(Int32 ByRef)
    L0000: inc dword ptr [rcx]
    L0002: cmp dword ptr [rcx], 0xa
    L0005: jle short L0000
    L0007: ret
```

### Initial source
```cs
    private static void B(ref int i) {
        for(int j = 0; j <= 10; j++) {
            i++;
        }
    }
```

### Lowered source

```cs
    private static void B(ref int i)
    {
        int num = 0;
        while (num <= 10)
        {
            i++;
            num++;
        }
    }
```

### JIT Asm

```asm
Program.B(Int32 ByRef)
    L0000: xor eax, eax
    L0002: inc dword ptr [rcx]
    L0004: inc eax
    L0006: cmp eax, 0xa
    L0009: jle short L0002
    L000b: ret
```

## Analysis

As you can clearly see in the lowered source, 2 counters are used (`num` & `i`).
Extra: If the compiler wants to be very smart, we could replace the operation `inc dword ptr [rcx]` by `add dword ptr [rcx], 0xa` after all.

See [sharplab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBrIGYACAbxsfcYAcoBLAN2wYYjYuSQiUjALLYeAOwAUAShZsO6gVEbY+jALyMADAG4169gEEFsAGba+S09XMcz5zY2C6DJt+oBC1jB2Xo5+rs4uIuQAnAo6+gahTuoAvjRu3PyCwqLixJJWtozyGCUqrJEuAO4AFjwANjAKGFAArjAV4S48ANS9KVHq3eY8Ngo8jAB8jOSGKsCw2ADWgy7pVYwbw5tZAkLR+ZKBxaXlqpvqNtATcmUAVvpGxoyPADwGcy/3/V2XUX0BiNthwNqkgA==)

**Comment by hopperpl** [comment]
I don't think these 2 loops are identical.

Variable **i** is pulled in as reference. A second thread can modify **i** outside and for example pull it and keep it negative. The first loop example would never finish then, while the second loop example is unaffected by that.

A ref-variable should always be treated as **volatile** and always re-read and re-evaluated. Which the compiler is doing correctly, imo.

**Comment by quixoticaxis** [comment]
> A ref-variable should always be treated as **volatile** and always re-read and re-evaluated. Which the compiler is doing correctly, imo.

Why? That's pretty brutal guarantee to uphold.

**Comment by hopperpl** [comment]
A function is not the "owner" of a by-ref variable as input parameter and therefore cannot make assumptions about changes. Other threads/processes have access to the same variable, which would not be the case for local variables inside a function or by-value parameters. Variable i can even be on a shared-memory block and being modified by a different process. The compiler doesn't know that. Or it can be device I/O memory ... like GPU memory... C# is used with Direct3D or Vulkan.

In a similar way, fields of an object ("class") also have to be re-read for every access. Unless they are marked as readonly/constant. If a function would simply cache the value and never re-read it, the function could never react to changes outside. 

The same would also apply to code like this

```csharp
    private static void A(Window wnd) {
        while(true) {
            wnd.Left++;
            
            if(wnd.Left > 10) break;
        }
    }
```

-----

Of course multiple modifications of a variable need to be locked (Interlocked.Increment), otherwise the result is undefined. Nonetheless the code-gen seems correct. 

The difference between both examples is the compare operation. In the first example it is on the by-ref variable, in the second example it is on a local variable. 

-----

```csharp
 private static void A(ref int i) {
        int j = i; // pull i into a local variable
        
        while(true) {
            j++;
            
            if(j > 10) break;
        }
        
        i = j; // and return it after
    }
```

```assembly
Program.A(Int32 ByRef)
    L0000: mov eax, [rcx]

    L0002: inc eax
    L0004: cmp eax, 0xa
    L0007: jle short L0002

    L0009: mov [rcx], eax
    L000b: ret
```

if you move the by-ref variable into a local variable, it generated the identical code... (not counting the 2 move operations)

**Comment by hopperpl** [comment]
I made  a better example to show the difference...

```csharp
    private static void Main() {
        
        var av = 0;
        
        new Thread(() => PullDown(ref av)).Start();
        Thread.Sleep(1000); // delay a bit until the thread is running
        
        A(ref av);
        B(ref av);
        
    }
    
    private static void PullDown(ref int i) {
        while(true) {
            i = -100000;
        }
    }
    

    private static void A(ref int i) {
        while(true) {
            i++;
            
            if(i > 10) break;
        }
    }
    
    private static void B(ref int i) {
        for(int j = 0; j <= 10; j++) {
            i++;
        }
    }
```

A will never finish, while B is unaffected

**Comment by quixoticaxis** [comment]
> If a function would simply cache the value and never re-read it, the function could never react to changes outside

And that is how it works for class fields, unless you inform the compiler that the value should be re-read.
The compiler assumes single threaded execution by default.

**Comment by ANahr** [comment]
> ## Analysis
> As you can clearly see in the lowered source, 2 counters are used (`num` & `i`). 

The two loops do completely different things.
For an input value of -100 one will deliver an "output" value (ref) of -89 and the other one 11

**Comment by stephentoub** [comment]
> The two loops do completely different things.

Closing.  Thanks.

**Comment by quixoticaxis** [comment]
@hopperpl 
I modified your example a little:
```csharp
var shared = 0;

var pullerThread = new Thread(() => PullDown(ref shared));
var pusherThread = new Thread(() => PushUp(ref shared));

pullerThread.Start();
Thread.Sleep(
    TimeSpan.FromSeconds(2)); // let the pull begin
pusherThread.Start();
pusherThread.Join();
Console.WriteLine("Pusher reached its goal.");

static void PullDown(ref int i)
{
    while (true)
    {
        i = -30_000;
    }
}

static void PushUp(ref int i)
{
    while (true)
    {
        i++;
        if (i >= 10)
        {            
            break;
        }
    }
}
```
On my machine this program _often_ outputs "Pusher reached its goal" and then hangs.
The point is, the compiler assumes single threaded execution and is not obliged to read from memory and not CPU cache.

**Comment by deeprobin** [comment]
The codegen is also different on non-`ref` methods

See [sharplab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBrIGYACAbxsfcYAcoBLAN2wYYjYuSQiUjALLYeAOwAUAShZsO6gVEbZGAXkYBBZQG4169psbA9jAEImz5x+tEBOBTt37gS09XUAvjSO3PyCwqLi8hiGyqr+5uzRjDw2AAx+iewA7gAWPAA2MAoYUACuMCqsCVkcPADU9Zm1HM5ZPABmCqkAfIzkaSrAsNgA1s2JQTXmxADsKROMU+ohvAJCImIpcjH2VW1JOynpi+od0N1HAFYnjDcAPPoDxneN+9O1DU0HSz9zC44pgEgA)

**Comment by quixoticaxis** [comment]
> The codegen is also different on non-`ref` methods

Could you open a new issue for this? From my personal observations, the closed issues are re-visited not quite often.

**Comment by gfoidl** [comment]
@deeprobin why do you expect the code being the same? In `B` the loop-variable is `j` and the compiler (any of them) isn't allowed to remove it here, as you increment `i` and `j`.

When [the for loop is written correct](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBrIGYACAbxsfcYAcoBLAN2wYYjYuSQiUjALLYeAOwAUAShZsO6gVEbZGAXkYBBZQG4169psbA9jAEImz5x+tEBOBTt37gS09XUAvjSO3PyCwqLi8hiGyqr+5uzRjDw2AAx+iewA7gAWPAA2MAoYUACuMCqsCVkcPADU9Zm1HM5ZPABmCqkAfIzkaSrAsNgA1s2JQTXmxADsKROMU+ohvAJCImIpcjH2VW1JOynpi+od0N1HAFYnjDcAPPoDxneN+9O1DU0HSz9zC45lq1psQmJFtrsAPoYXKCSH4HhQKDQXCQozvT5HVL6DI/c5aBQvVKPfoZFJvRinDj/HiLKYBIA=) then both variants produce -- as expected -- the same machine code.

**Comment by quixoticaxis** [comment]
> @deeprobin why do you expect the code being the same? In `B` the loop-variable is `j` and the compiler (any of them) isn't allowed to remove it here, as you increment `i` and `j` (that would be a change of program).

Does any specification forbid it for C# compilers? The visible result is the same for the non-ref code snippet.
