### ISSUE TITLE
Double quotes are escaped as \" in New JsonConsole

### ISSUE THREAD

**Issue by ArminShoeibi** [dotnet/runtime#63554]
### Description

I want to log some of the HTTP responses as a pure string.
for example, I use this method:  await HttpContent.ReadAsStringAsync() for getting responses of my HTTP request for logs.

but  I have some problems with escaping characters with the new JsonConsole.

### Reproduction Steps

**1.**
```using System.Text.Json;

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
    })
    .ConfigureLogging(logginBuilder =>
    {
        logginBuilder.ClearProviders();
        logginBuilder.AddJsonConsole(jsonConsoleFormatterOptions => 
        {
            jsonConsoleFormatterOptions.JsonWriterOptions = new()
            {
                Indented = true
            };
        });
    })
    .Build();


var logger = host.Services.GetRequiredService<ILogger<Program>>();
AvailableFlight availableFlight = new()
{
    DepartureDate = DateTimeOffset.Now,
    AirlineName = "Saha",
    Destination = "KIH",
    Origin = "THR"
};

logger.LogInformation("Available Flight: {AvailableFlight}", JsonSerializer.Serialize(availableFlight));

await host.RunAsync();


public class AvailableFlight
{
    public string Origin { get; set; }
    public string Destination { get; set; }
    public string AirlineName { get; set; }
    public DateTimeOffset DepartureDate { get; set; }
}
```

**2.**
```using System.Text.Encodings.Web;
using System.Text.Json;

IHost host = Host.CreateDefaultBuilder(args)
    .ConfigureServices(services =>
    {
    })
    .ConfigureLogging(logginBuilder =>
    {
        logginBuilder.ClearProviders();
        logginBuilder.AddJsonConsole(jsonConsoleFormatterOptions => 
        {
            jsonConsoleFormatterOptions.JsonWriterOptions = new()
            {
                Indented = true,
                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            };
        });
    })
    .Build();


var logger = host.Services.GetRequiredService<ILogger<Program>>();
AvailableFlight availableFlight = new()
{
    DepartureDate = DateTimeOffset.Now,
    AirlineName = "Saha",
    Destination = "KIH",
    Origin = "THR"
};

logger.LogInformation("Available Flight: {AvailableFlight}", JsonSerializer.Serialize(availableFlight));

await host.RunAsync();


public class AvailableFlight
{
    public string Origin { get; set; }
    public string Destination { get; set; }
    public string AirlineName { get; set; }
    public DateTimeOffset DepartureDate { get; set; }
}
```
________________________________

### Expected behavior

I want this => {"prop":"value"} not this => {\\"prop\\":\\"value\\"}

### Actual behavior

**The actual behavior of first option:**
<img width="952" alt="image" src="https://user-images.githubusercontent.com/68565441/148694943-c0204898-039b-4ab8-bf20-80ce3310d227.png">

**The actual behavior of the second option:** (JavaScriptEncoder.UnsafeRelaxedJsonEscaping) is better than the first one but double quotes are escaped as \"

<img width="735" alt="image" src="https://user-images.githubusercontent.com/68565441/148695004-743f0fb3-f5dd-4bd2-a504-13d104ce07e9.png">

### Configuration

Which version of .NET is the code running on?
  Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

**Comment by skyoxZ** [comment]
`JsonSerializer.Serialize(availableFlight)` is just a string that contains `"`. Consider this:
```csharp
string s = JsonSerializer.Serialize(availableFlight);
s = "a\"b";
logger.LogInformation("Available Flight: {AvailableFlight}", s);
```
What output should you expect?

I believe this is what you want:
```csharp
logger.LogInformation("Available Flight: {AvailableFlight}", availableFlight);
```

**Comment by eiriktsarpalis** [comment]
This is expected behavior, the json logger needs to escape any JSON that is embedded in the message string otherwise it would be producing a log entry that is invalid JSON. I think you might be trying to achieve structured logging, please see [this document](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-6.0) for pointers on how to do this in .NET.
