### ISSUE TITLE
Test failure System.IO.Compression.Tests.ZipFile_Create.UpdateAddFile

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63562]
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20220108.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1542869&view=ms.vss-test-web.build-test-results-tab&runId=43629658&paneView=debug&resultId=114902)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_checked-jitstress2_jitstressregs8-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- System.IO.Compression.Tests.ZipFile_Create.UpdateAddFile

```
**Error message:**
```
Assert.All() Failure: 1 out of 7 items in the collection did not pass.
[1]: Item: binary.wmv
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1947050642
Actual:   740169638
at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 40 at System.IO.Compression.Tests.ZipFileTestBase.<>c__DisplayClass17_0.<IsZipSameAsDir>b__0(FileData file) at Xunit.Assert.All[T](IEnumerable1 collection, Action`1 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 36


Stack trace
   at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDir(Stream archiveFile, String directory, ZipArchiveMode mode, Boolean requireExplicit, Boolean checkTimes) in /_/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs:line 165
   at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDirAsync(String archiveFile, String directory, ZipArchiveMode mode, Boolean requireExplicit, Boolean checkTimes) in /_/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs:line 147
   at System.IO.Compression.Tests.ZipFileTestBase.IsZipSameAsDirAsync(String archiveFile, String directory, ZipArchiveMode mode) in /_/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs:line 141
   at System.IO.Compression.Tests.ZipFile_Create.UpdateAddFile() in /_/src/libraries/System.IO.Compression.ZipFile/tests/ZipFile.Create.cs:line 402
--- End of stack trace from previous location ---
```

**Comment by danmoseley** [comment]
This is the only failure of this test in the records.

Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI1RTWsCMRC9C%2f6H4MkFu9Tet2CVBQtVWy0FLxLNuDu6m4SZBBH645vN2uqhB09J5n3MvMkK2H0A%2b8pxt%2fMtDga1OKJWGWoNJL4MHacOahZG%2fz2m6j%2fqq9lGVjhbwqkEApGjRi5BiedMaHPqPwyfHlVyxdvmIstEL5dY9a7IG7jSqIh8WiUdjJTKsYIbyupsIRKWZw6DpdN5Oja1JWBGo9NVCMfpGm0j24wJgklUWzIH2DnR7QixQAsV6uAjnGFHqIu%2blcSwObDR%2fQUZC%2bQQOEknsA9pXLCeyRqSwa18MzZ6j4Un2eB3mO1u%2ba3XfBl07x48NP6xNKJdeYeZDDR0IZKny1xN9iBsNjSMhXbRg9%2f%2fiLXJpX18tPuO1xePlbqjbeTNfL0FSi4ezLKAHxgDtXlWAgAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1RTWsCMRC9C%2f6H4MkFu9Tet2CVBQtVWy0FLxLNuDu6m4SZBBH645vN2uqhB09J5n3MvMkK2H0A%2b8pxt%2fMtDga1OKJWGWoNJL4MHacOahZG%2fz2m6j%2fqq9lGVjhbwqkEApGjRi5BiedMaHPqPwyfHlVyxdvmIstEL5dY9a7IG7jSqIh8WiUdjJTKsYIbyupsIRKWZw6DpdN5Oja1JWBGo9NVCMfpGm0j24wJgklUWzIH2DnR7QixQAsV6uAjnGFHqIu%2blcSwObDR%2fQUZC%2bQQOEknsA9pXLCeyRqSwa18MzZ6j4Un2eB3mO1u%2ba3XfBl07x48NP6xNKJdeYeZDDR0IZKny1xN9iBsNjSMhXbRg9%2f%2fiLXJpX18tPuO1xePlbqjbeTNfL0FSi4ezLKAHxgDtXlWAgAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI1RTWsCMRC9C%2f6H4MkFu9Tet2CVBQtVWy0FLxLNuDu6m4SZBBH645vN2uqhB09J5n3MvMkK2H0A%2b8pxt%2fMtDga1OKJWGWoNJL4MHacOahZG%2fz2m6j%2fqq9lGVjhbwqkEApGjRi5BiedMaHPqPwyfHlVyxdvmIstEL5dY9a7IG7jSqIh8WiUdjJTKsYIbyupsIRKWZw6DpdN5Oja1JWBGo9NVCMfpGm0j24wJgklUWzIH2DnR7QixQAsV6uAjnGFHqIu%2blcSwObDR%2fQUZC%2bQQOEknsA9pXLCeyRqSwa18MzZ6j4Un2eB3mO1u%2ba3XfBl07x48NP6xNKJdeYeZDDR0IZKny1xN9iBsNjSMhXbRg9%2f%2fiLXJpX18tPuO1xePlbqjbeTNfL0FSi4ezLKAHxgDtXlWAgAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI1RTWsCMRC9C%2f6H4MkFu9Tet2CVBQtVWy0FLxLNuDu6m4SZBBH645vN2uqhB09J5n3MvMkK2H0A%2b8pxt%2fMtDga1OKJWGWoNJL4MHacOahZG%2fz2m6j%2fqq9lGVjhbwqkEApGjRi5BiedMaHPqPwyfHlVyxdvmIstEL5dY9a7IG7jSqIh8WiUdjJTKsYIbyupsIRKWZw6DpdN5Oja1JWBGo9NVCMfpGm0j24wJgklUWzIH2DnR7QixQAsV6uAjnGFHqIu%2blcSwObDR%2fQUZC%2bQQOEknsA9pXLCeyRqSwa18MzZ6j4Un2eB3mO1u%2ba3XfBl07x48NP6xNKJdeYeZDDR0IZKny1xN9iBsNjSMhXbRg9%2f%2fiLXJpX18tPuO1xePlbqjbeTNfL0FSi4ezLKAHxgDtXlWAgAA&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-120d)
| where Result == "Fail"
| where Method == "UpdateAddFile"
| where Type == "System.IO.Compression.Tests.ZipFile_Create"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,
  Duration,
  Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

**Comment by jeffhandley** [comment]
Closing since this hasn't reoccurred.
