### ISSUE TITLE
emitinsBinary() in emitxarch.cpp: has some functionality that belongs to codegen

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6356]
We need to look at this functionality more closely and see if we can refactor to move out codegen functionality out of emitter.

category:implementation
theme:emitter
skill-level:intermediate
cost:medium

**Comment by TIHan** [comment]
I think this issue, https://github.com/dotnet/runtime/issues/12178, describes some of these details.

I believe the thought is that `emit` functions should not take `GenTree` nodes and only be focused on emitting single instructions. `gen` functions are the ones that take `GenTree` nodes and use the `emit` functions for emitting the instructions.

**Comment by BruceForstall** [comment]
Going to close this in favor of #12178
