### ISSUE TITLE
Probably Task+WeakReference memory leak? Not sure

### ISSUE THREAD

**Issue by szmcdull** [dotnet/runtime#63568]
### Description

The following test was passing but fails now (Though I forgot the time when it started to fail)

```c#
        [Test]
        public async Task TestDelayGC()
        {
            //var e = new AsyncManualResetEvent(false);
            //var rf = new WeakReference<Task>(e.WaitAsync());
            var rf = new WeakReference<Task>(Task.Delay(100000));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Assert.IsFalse(rf.TryGetTarget(out var v));
        }
```

### Reproduction Steps

Run the above test case

### Expected behavior

The test passes

### Actual behavior

It fails

### Configuration

```
> dotnet --version
6.0.200-preview.21617.4

> ver
Microsoft Windows [版本 10.0.22000.376]
```

**Comment by teo-tsirpanis** [comment]
Hello, the JIT might have created a hidden temporary variable that holds the task and prevents it from being collected. To ensure it does not happen, you need to create the weak reference from a separate function that will not get inlined. I believe the following will always work:

``` csharp
using System.Runtime.CompilerServices;

[Test]
public async Task TestDelayGC()
{
    //var e = new AsyncManualResetEvent(false);
    //var rf = new WeakReference<Task>(e.WaitAsync());
    var rf = CreateWeakReference();
    GC.Collect();
    GC.WaitForPendingFinalizers();
    GC.Collect();
    Assert.IsFalse(rf.TryGetTarget(out var v));

    [MethodImpl(MethodImplOptions.NoInlining)]
    static WeakReference<Task> CreateWeakReference()
    {
        return new WeakReference<Task>(Task.Delay(100000));
    }
}
```

**Comment by stephentoub** [comment]
@teo-tsirpanis is correct.  Closing as answered; please re-open if you still find an issue.

**Comment by szmcdull** [comment]
> Hello, the JIT might have created a hidden temporary variable that holds the task and prevents it from being collected. To ensure it does not happen, you need to create the weak reference from a separate function that will not get inlined. I believe the following will always work:
> 
> ```cs
> using System.Runtime.CompilerServices;
> 
> [Test]
> public async Task TestDelayGC()
> {
>     //var e = new AsyncManualResetEvent(false);
>     //var rf = new WeakReference<Task>(e.WaitAsync());
>     var rf = CreateWeakReference();
>     GC.Collect();
>     GC.WaitForPendingFinalizers();
>     GC.Collect();
>     Assert.IsFalse(rf.TryGetTarget(out var v));
> 
>     [MethodImpl(MethodImplOptions.NoInlining)]
>     static WeakReference<Task> CreateWeakReference()
>     {
>         return new WeakReference<Task>(Task.Delay(100000));
>     }
> }
> ```

OK I tried. But this still fails

**Comment by szmcdull** [comment]
In contrast, the following test passes:
```c#
        async Task FastTask()
        {
            await Task.Delay(1500);
        }

        [Test]
        public async Task TestTaskGC()
        {
            var i = 0;
            var rf = new WeakReference(FastTask().ContinueWith(x => i=1));
            await Task.Delay(2000); // wait until the task completes
            Assert.AreEqual(1, i);
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Assert.IsFalse(rf.IsAlive);
        }
```

**Comment by stephentoub** [comment]
> OK I tried. But this still fails

If you tried it with a 100s task, that would explain why the target is still available.  Task.Delay tasks are rooted until they complete.

**Comment by szmcdull** [comment]
> If you tried it with a 100s task, that would explain why the target is still available. Task.Delay tasks are rooted until they complete.

Does it mean that if I use WaitAny and pass a Task.Delay(100s)) as timeout, that Task.Delay would will not be free until 100s later? Is HttpClient using a Task.Delay to implement timeout?

**Comment by stephentoub** [comment]
> Does it mean that if I use WaitAny and pass a Task.Delay(100s)) as timeout, that Task.Delay would will not be free until 100s later?

Yes.

> Is HttpClient using a Task.Delay to implement timeout?

Yes, but it passes a cancellation token to the Task.Delay and cancels the token in order to stop the timer and clean up the task.

**Comment by szmcdull** [comment]
> Task.Delay tasks are rooted until they complete

Is there any Task that is not rooted?

**Comment by stephentoub** [comment]
> Is there any Task that is not rooted?

The only ones that are rooted are done so for their semantics.  Task.Delay is rooted by the underlying timer as otherwise `Task.Delay(1000).ContinueWith(_ => Console.WriteLine("completed"))` might never actually print to the console.  `Task.Run(() => Console.WriteLine("completed"))` is rooted until it completes because it wouldn't make sense to queue a work item and then have it disappear because the GC happened to run.  But if you do `new TaskCompletionSource().Task`, there's nothing rooting that, and if you do `async Task M() => await new TaskCompletionSource().Task;`, the task returned from M isn't rooted by anything either.

**Comment by szmcdull** [comment]
How about `Task.Delay(-1)`. The following test also fails:
```c#
        [Test]
        public async Task TestDelayGC()
        {
            var rf = new WeakReference<Task>(Task.Delay(-1));
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Assert.IsFalse(rf.TryGetTarget(out var v));
        }
```
As https://github.com/dotnet/runtime/issues/26811 stated, Delay(-1) should not leak

**Comment by teo-tsirpanis** [comment]
@szmcdull the JIT might have held it in a hidden temporary variable. Use the code on my first answer to guard against such occurrences.

**Comment by szmcdull** [comment]
OK, I confirmed creating the Task in a separated function works. Then I wonder if I can use an await statement to return the state machine and release the temporary Task. And it works :)
```c#
        [Test]
        public async Task TestDelayGC()
        {
            var rf = new WeakReference<Task>(Task.Delay(-1));
            await Task.Delay(1); // return the state machine as Delay(1) would not complete right away
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            Assert.IsFalse(rf.TryGetTarget(out var v));
        }
```
