### ISSUE TITLE
Official Docker ASP.NET Core 1.1 runtime image

### ISSUE THREAD

**Issue by qvsmith** [dotnet/runtime#63573]
I trust I'm asking this in the correct repo.

Simple question: Is there still an official **ASP.NET Core 1.1 runtime image**?

I see a [1.1 SDK image](https://mcr.microsoft.com/v2/dotnet/core/sdk/tags/list), but no [1.1 runtime image](https://mcr.microsoft.com/v2/dotnet/core/aspnet/tags/list).

I'm aware that 1.1 is very EOL, but just wanted to confirm that MS has indeed removed the 1.1 runtime images.

Thanks!

**Comment by jkoritzinsky** [comment]
cc: @mthalman

**Comment by mthalman** [comment]
Even if there was, please don't use it. Once a .NET version is EOL the container image tags for that version are not maintained **at all**. Obviously this means .NET hasn't been updated. But it also means that they do not have any of the updates from Linux packages and the base OS. Any 1.1 container images contain horribly out-of-date software by now with unpatched critical vulnerabilities all over.

If you _really_ want to use an EOL version of .NET, please use the latest version of an OS base image and install .NET on it yourself. We have [instructions](https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/installing-dotnet.md) on how to install .NET in container images. But again, this is all use-at-your-own-risk kind of stuff for EOL versions.

**Comment by qvsmith** [comment]
Thx appreciate the response 👍

**Comment by qvsmith** [comment]
Hi @mthalman 

I'm trying to follow your advice and trying to install NET Core 1.1 on the latest version of an OS (not because I _want to_, but _have to_ 😃).

Unfortunately following the information in the instructions (for [Linux Package Manager](https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/installing-dotnet.md#installing-from-a-linux-package-manager)) but, using the **https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb** package repo results in the following response (used apt search):

```ps
#6 75.58 Sorting...
#6 75.65 Full Text Search...
#6 75.86 aspnetcore-runtime-2.1/bullseye 2.1.30-1 amd64
#6 75.86   Microsoft ASP.NET Core 2.1.30 Shared Framework
#6 75.86
#6 75.86 aspnetcore-runtime-3.1/bullseye 3.1.22-1 amd64
#6 75.86   Shared Framework for hosting of Microsoft ASP.NET Core applications. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/aspnet/AspNetCore). We happily accept issues and PRs.
#6 75.86
#6 75.86 aspnetcore-runtime-5.0/bullseye 5.0.13-1 amd64
#6 75.86   Shared Framework for hosting of Microsoft ASP.NET Core applications. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/aspnetcore). We happily accept issues and PRs.
#6 75.86
#6 75.86 aspnetcore-runtime-6.0/bullseye 6.0.1-1 amd64
#6 75.86   Shared Framework for hosting of Microsoft ASP.NET Core applications. It is open source, cross-platform and is supported by Microsoft. We hope you enjoy using it! If you do, please consider joining the active community of developers that are contributing to the project on GitHub (https://github.com/dotnet/aspnetcore). We happily accept issues and PRs.
#6 75.86
#6 75.88 Reading package lists...
#6 76.70 Building dependency tree...
#6 76.85 Reading state information...
#6 77.02 E: Unable to locate package aspnetcore-runtime-1.1
#6 77.02 E: Couldn't find any package by glob 'aspnetcore-runtime-1.1'
#6 77.02 E: Couldn't find any package by regex 'aspnetcore-runtime-1.1'
```

I guess I need to use an older package repo? Is there an easier way than using apt search to see which packages are available for the different package repo links? (As you can tell my linux is not that fluent.)

Btw I had to remove the `export` keyword from the `export DEBIAN_FRONTEND=noninteractive` line in Linux Package Manager example (linked above) for Dockerfile to build successfully.

Thanks for the help, appreciate.

**Comment by mthalman** [comment]
.NET Core 1.1 was before my time on the .NET team so I'm learning about this myself. Here's the [download page for the final 1.1 build](https://github.com/dotnet/core/blob/main/release-notes/1.1/1.1.13/1.1.13-download.md). It looks like ASP.NET Core didn't have its own installer. It was only delivered as part of the SDK. That explains why you didn't find any tags for it in the aspnet repository.

I've tried recreating a Dockerfile which will install this on a modern version of Debian. Everything was crashing, presumably due to a newer incompatible version of some package. The only one I was able to get working was Debian 8 (Jessie) which was EOL in June 2020. So it is what it is, I guess. You can either use the Dockerfile I was able to get working here:

```Dockerfile
FROM debian:jessie

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        netbase \
        wget \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    if ! command -v gpg > /dev/null; then \
        apt-get update; \
        apt-get install -y --no-install-recommends \
            gnupg \
            dirmngr; \
        rm -rf /var/lib/apt/lists/*; \
    fi

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bzr \
        git \
        mercurial \
        openssh-client \
        subversion \
        procps \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/1.1.14/dotnet-dev-debian-x64.1.1.14.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -ozxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

ENV NUGET_XMLDOC_MODE=skip

RUN apt-get update && apt-get install -y --no-install-recommends libunwind8 && rm -rf /var/lib/apt/lists/*

RUN mkdir warmup \
    && cd warmup \
    && dotnet new  \
    && cd ..  \
    && rm -rf warmup \
    && rm -rf /tmp/NuGetScratch
```

Or you could just use `mcr.microsoft.com/dotnet/core/sdk:1.1.14-stretch`.

Hopefully this is just for testing purposes and not for production because your only options here are very out-of-date stuff.

**Comment by qvsmith** [comment]
Thanks @mthalman - appreciate the trouble you've gone through.

**Comment by ericstj** [comment]
There is also:
https://mcr.microsoft.com/v2/dotnet/core/runtime/tags/list
Which has the older runtimes.  I'm not sure if we pull any out of support docker containers, which might have been the intent of the original issue.  

IIRC In 1.1 ASP.NET didn't have a shared framework, so there wasn't an ASP.NET runtime, per-se.  That was added in 2.x.  A 1.1  ASP.NETCore app targeting was just a collection of packages on top of the NETCore.App shared framework.  1.1 apps would publish, which included all the asp.net binaries with the app, or restore which downloaded the packages and ran from the nuget cache.
