### ISSUE TITLE
XmlSerializer Behavior Change in .NET 6

### ISSUE THREAD

**Issue by jdasilva-olo** [dotnet/runtime#63585]
### Description

Starting in .NET 6, XmlSerializer will produce a Byte Order Mark by default.  Previous versions of .NET including .NET Framework 4.7.2, .NET Core 3.1, and .NET 5 do not.  When paired with something like `Encoding.UTF8.GetString` this can have unexpected impact.  `text` will cause an exception `System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.` when used with `XmlDocument.Load` in .NET 6.

### Reproduction Steps

.NET Fiddle for .NET Framework 4.7.2: https://dotnetfiddle.net/gfhKK2
.NET Fiddle for .NET 6: https://dotnetfiddle.net/CWdYc7

Example Code (same as fiddle), for reference:

```
using System;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
					
public class Program
{
	[Serializable]
	public class Test 
	{
	}
	
	public static void Main()
	{
		var serializer = new XmlSerializer(typeof(Test));
		using (var stream = new MemoryStream())
		{
			serializer.Serialize(stream, new Test());
			var byteArray = stream.ToArray();
			Console.WriteLine(byteArray[0].ToString("x"));
			Console.WriteLine(byteArray[1].ToString("x"));
			Console.WriteLine(byteArray[2].ToString("x"));
			var text = Encoding.UTF8.GetString(byteArray);	
			Console.WriteLine(((int)text[0]).ToString("x"));
			Console.WriteLine(text);
			new XmlDocument().LoadXml(text);
		}		
	}
}
```

### Expected behavior

No Byte Order Mark is output by default XmlSerializer.

### Actual behavior

Byte Order Mark is output by default XmlSerializer.

### Regression?

This is different behavior from .NET Framework 4.7.2, .NET Core 3.1, and .NET 5. 

### Known Workarounds

You can manually create an `XmlWriter` with a UTF-8 Encoder that does not write the Byte Order Mark and pass that to `XmlSerializer.Serialize`.

### Configuration

.NET 6.0.101

### Other information

It looks like it might be from this change: https://github.com/dotnet/runtime/commit/ab219299db07b76fc06482bf3a2bfbd7c5f75e63#diff-fa07acc29a1aed946fd7f4fca4b198bc71c7bb4204019cd407b9447882af374bR333

**Comment by bmueller84** [comment]
Stumbled upon the same issue today. Following the snipped linked by @jdasilva-olo, I was able to get the old behavior of the XMLSerializer in dotnet6 as follows:
```
using (var stream = new MemoryStream())
using (var writer = new XmlTextWriter(stream, null) { Formatting = Formatting.Indented, Indentation = 2 })
{
    var serializer = new XmlSerializer(myObject.GetType());
    serializer.Serialize(writer, myObject);
}
```

**Comment by StephenMolloy** [comment]
The fix referenced above was made to correct scenarios that should just work, and XmlTextWriter did not allow us to do that. We knew that changing the writer we use would present some small changes in output, but that most of these would be a move to more-conformant XML or largely negligible. This BOM issue was unintended, but not surprising I guess.

Knowing that there would potentially be these sorts of issues, we were still comfortable taking the change because of the easy workaround given above. Supplying your own XmlReader/XmlWriter is the correct way to customize your serialization behavior in this case.

That said, this BOM issue was unintended and does appear to present some noticeable annoyance. We do plan to look into whether we can fix this without reverting to XmlTextWriter and if we can then we will look at this for 7.0 and potentially bringing it back to 6.0 servicing. But our team is responsible for many projects and is spread a little thin. It's going to be a few weeks before we get to really dig into our XmlSerializer backlog. :/

**Comment by Andrei-NZ** [comment]
Broke our code big time, because we have LoadXml later on in the code chain and plain old LoadXml throws 

`System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.`

when it sees BOM. lovely jubbly

Worked around by 

```
using (var ms = new MemoryStream())
using (var writer = new XmlTextWriter(ms, new UTF8Encoding(false)))
   {
      s.Serialize(writer, message, namespaces);
      ...
```

Hope this saves someone half a day of debugging.

**Comment by eOkadas** [comment]
cross answer from https://github.com/dotnet/runtime/issues/28218#issuecomment-1182980078

Hi, when switching to NET 6 (from net 5 and netcore 3.1) we get the BOM for UTF8 added to our XML outputs.

The previous workaround offered by @Andrei-NZ didn't work. 
[see fiddle with the workaround working in 4.7.2](https://dotnetfiddle.net/A3GYfv)
```XML
<?xml version="1.0"?>
<Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
```
  [see fiddle with the workaround NOT working in Net6]( https://dotnetfiddle.net/g1hS06)

```XML
﻿<?xml version="1.0" encoding="utf-8"?><Test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" />
```

**Comment by jdasilva-olo** [comment]
@eOkadas you need to pass the xmlWriter in line 22 like so:
`serializer.Serialize(xmlWriter, new Test());`

**Comment by eOkadas** [comment]
Thank you @jdasilva-olo ! However I still get the BOM added to the XML 😄 
```<?xml version="1.0" encoding="utf-8"?>```

see https://dotnetfiddle.net/vrjhWi updated with your fix.
