### ISSUE TITLE
Symbols for libnethost.lib not shipped

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#63602]
On Windows, without the corresponding PDB, linking against `libnethost.lib` (static version of `nethost`) results in [LNK4099](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-warning-lnk4099).

This was previously found/resolved in https://github.com/dotnet/runtime/issues/35521, but it looks like it has regressed.

When building the pkgproj, the `NuGetPack` task excludes .pdb files in the regular (non-symbol) package:
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs#L22-L23

When building the sfxproj, `sharedfx.targets` filters out .pdb files when determining the files for the regular (non-symbol) package:
https://github.com/dotnet/arcade/blob/6c3d631ed5aafbb27d8f8d6466ea8d0f31b9a4e3/src/Microsoft.DotNet.SharedFramework.Sdk/targets/sharedfx.targets#L136-L138
https://github.com/dotnet/arcade/blob/6c3d631ed5aafbb27d8f8d6466ea8d0f31b9a4e3/src/Microsoft.DotNet.SharedFramework.Sdk/targets/sharedfx.targets#L542

cc @AaronRobinsonMSFT @vitek-karas

**Comment by AaronRobinsonMSFT** [comment]
@agocke Let's make sure we don't forget to handle this issue. It is rather poor UX for people who are consuming `nethost`. It was found again in #71578.

**Comment by alexrp** [comment]
Is this likely to be addressed in the .NET 7 timeframe?

**Comment by agocke** [comment]
Yes, let's fix this. @elinor-fung do you have the bandwidth to look at this?

**Comment by elinor-fung** [comment]
The real issue is making arcade support it: https://github.com/dotnet/arcade/issues/8374

I can try to get back to looking at it.

**Comment by elinor-fung** [comment]
Support is now in arcade (https://github.com/dotnet/arcade/pull/10057). Once it flows over, we can use it to include `libnethost.pdb` in the implementation packages.

**Comment by agocke** [comment]
@elinor-fung Thanks!

**Comment by alexrp** [comment]
Is the fix for this in Preview 7 or will it be in RC 1?

**Comment by elinor-fung** [comment]
The fix is not in Preview 7. It will be in RC 1.
