### ISSUE TITLE
AssemblyLoadContext cannot unload DLL module in .NET 6.0

### ISSUE THREAD

**Issue by xiao-cao-x** [dotnet/runtime#63615]
The plugin class code is as follows
```cs
    public class CSharpPlugin : IPlugin
    {
        private class PluginAssemblyLoadContext : AssemblyLoadContext
        {
            public PluginAssemblyLoadContext() : base(isCollectible: true)
            {
            }

        }

        private readonly PluginAssemblyLoadContext context = new();


        private readonly CSharpPluginFunc csPluginFunc;

        public string ModuleName { get; }
        public IPluginFunc PluginFunc => csPluginFunc;

        [MethodImpl(MethodImplOptions.NoInlining)]
        public CSharpPlugin(string path)
        {
            string fullPath = Path.GetFullPath(path);

            ModuleName = fullPath.Split('\\').Last();

            Assembly assembly = context.LoadFromAssemblyPath(fullPath);

            if (null == assembly)
            {
                throw new Exception($"加载C#插件DLL文件失败,路径:{path}");
            }

            Type? pluginAbstractClass = assembly.GetTypes().SingleOrDefault(type =>
             {
                 if (null == type.BaseType)
                 {
                     return false;
                 }
                 if (!type.BaseType.IsAbstract)
                 {
                     return false;
                 }
                 if (type.BaseType != typeof(CSharpPluginAbstract))
                 {
                     return false;
                 }

                 return true;
             });

            if (null == pluginAbstractClass)
            {
                throw new Exception($"获取C#插件类失败,路径:{fullPath}");
            }

            object instance = Activator.CreateInstance(pluginAbstractClass, new object[] { OpenAPI.Instance, PluginLogger.Instance })!;

            csPluginFunc = new CSharpPluginFunc(new((CSharpPluginAbstract)instance));
            PluginFunc.OnStart();
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        void IPlugin.Unload(out WeakReference weakReference)
        {
            weakReference = new WeakReference(context);
            PluginFunc.OnStop();
            context.Unload();
            //new Kernel32.SafeLibraryHandle(Kernel32.GetModuleHandle(ModuleName)).Dispose();
        }

    }
```

The uninstall function code is as follows
```cs
        public static void UnloadPlugin(IPlugin plugin)
        {
            MutexFunc(() =>
            {
                plugin.Unload(out WeakReference weakReference);
                plugins.Remove(plugin);
                for (int i = 0; weakReference.IsAlive && (i < 10); i++)
                {
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                }
            });
        }
```

**Comment by vitek-karas** [comment]
There must be no references to anything in the unloaded `AssemblyLoadContext`. If I read the code correctly the `CSharpPlugin` instance is passed as a parameter to the `UnloadPlugin` and thus it is kept alive after the unload. It in turn has a reference to `CSharpPluginFunc` which seems to hold a reference to the plugin instance from the separate context. It's not clear from the code above what `CSharpPluginFunc.OnStop` does, but if it doesn't clear its reference to the plugin instance, it would keep it alive after the unload.
There are some additional hints what to do to track down unload problems in this guide: https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability

**Comment by xiao-cao-x** [comment]
I modified the code to make sure that no reference exists, but sometimes it can be uninstalled, and sometimes it cannot be uninstalled.
Is there a way to force unload and kill all threads in DLL.

**Comment by vitek-karas** [comment]
In .NET Core (so 3.1, 5, 6+) the assembly unload is cooperative, there's no "force unload" functionality. The process has to release all references to the unloaded code and only then runtime will actually unload the assembly. There are APIs to kill a thread, but you would have to figure out which one (the runtime doesn't have an API to enumerate threads which are running code from a specific DLL).

As noted in my previous comment, this guide https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability#debug-unloading-issues has details on how to debug unloading, specifically how to figure out what is holding the remaining references.

**Comment by xiao-cao-x** [comment]
Is it possible to load and unload C# DLLs via LoadLibrary and FreeLibrary?

**Comment by xiao-cao-x** [comment]
After I unload the DLL through FreeLibrary, System.ExecutionEngineException will be thrown when I load the DLL again

**Comment by vitek-karas** [comment]
It's not possible to load managed assemblies via `LoadLibrary` - the runtime does that under the hood, but it does lot of other things on top of it.

**Comment by xiao-cao-x** [comment]
https://user-images.githubusercontent.com/76673990/149092488-4d4c8e6d-f840-4c36-9278-ffc1f6dfe2fd.mp4

As shown in the video, my program can't unload the DLL after it is loaded the first time, only the DLL loaded the second time and later can be unloaded

And the DLL will always exist in the process
![image](https://user-images.githubusercontent.com/76673990/149092902-ae04a947-39c8-4e2e-b6b2-60813b50cec0.png)


Here is the load and unload code
![Y9CH3H8HVDTVGBYW$)JP_}C](https://user-images.githubusercontent.com/76673990/149093062-b7fc19aa-e93a-464e-b103-d1e1f40dd571.png)

![)}`1DRK6O2U1 }U 6MV4(CW](https://user-images.githubusercontent.com/76673990/149093076-8cd787fe-b591-45fb-9bf9-e179e45995e1.png)

![02DH $X%XQH$P7T_XELYS9J](https://user-images.githubusercontent.com/76673990/149093079-bb538d18-ff64-484f-8bd8-974a791e81d8.png)

![image](https://user-images.githubusercontent.com/76673990/149093094-0149e86f-8d23-4190-bf85-b50e0c2d22e4.png)

**Comment by xiao-cao-x** [comment]
> As shown in the video, my program can't unload the DLL after it is loaded the first time, only the DLL loaded the second time and later can be unloaded
  
If the video cannot be played, it needs to be downloaded locally to play

**Comment by vitek-karas** [comment]
It's really hard to guess what's going on. It's possible you might be running into bugs in the framework itself - for example: https://github.com/dotnet/runtime/issues/30656.
That said, following the diagnostics guide should provide the answer what is holding onto the unloaded code.

Also in your latest code sample - just calling ALC.Unload will not immediately unload - the loop waiting for GC is necessary as the unloading is internally triggered by GC and can take several GC iterations to complete.

**Comment by xiao-cao-x** [comment]
Can you provide a sample code that can unload a DLL normally in .NET 6.0?

**Comment by vitek-karas** [comment]
The guide I pointed to above contains the samples: https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability.
