### ISSUE TITLE
Investigate what metrics need to be added to the runtime

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#63649]
This issue is to track the investigation of which areas in the runtime need to add metrics instrumentation. The investigation will include looking at all areas using EventCounters to add metrics support there too.
and/or adapted to use the newer Metrics API in addition to

**Comment by noahfalk** [comment]
I did some investigation and the direction we are looking at so far is to add metrics via OpenTelemetry instrumentation libraries that ship out of band from the runtime. We'll get into more specifics on the exact metrics in design docs and issues in the OpenTelemetry dotnet repo.
