### ISSUE TITLE
[dotnet-sdk-7.0.100-alpha.1.22060.9] UMLGenerator generate unexcepted UML due to Regex.IsMatch return wrong result

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#63678]
### Description

When run the .NET 5 UMLGenerator app with .NET 7.0 runtime, UMLGenerator generate unexcepted UML due to Regex.IsMatch return wrong result.

### Reproduction Steps

**Repro Steps for the affected App:**

**This is .Net 5.0 app, but we are running it on 7.0, machine only have 7.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 7.0**

1. Copy UMLGeneratorApp from server to local machine.
2. Launch UMLGenerator.exe.
3. Unselect "Languages" windows.
4. Click "Select Folder" button.
5. Input the {AdditionFilesPath}\Project.
6. Select "Extensions.cs" file and "Views" directory.
7. Click "Generate Objects Tree" button.

### Expected behavior

It will show below result
![expected result](https://user-images.githubusercontent.com/83067197/149125404-fdfb05ac-466b-47b5-ae81-738dae728cfd.png)
.

### Actual behavior

It doesn't show all objects in selected files
![actual result](https://user-images.githubusercontent.com/83067197/149125440-ed615aa6-f016-480f-bfcf-7e285983869b.png)
.

### Regression?

Yes

Verify Scenarios:

1). Windows10 RS5 x64+dotnet-sdk-5.0.404-win-x64:Pass
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-alpha.1.21568.2:Pass
3). Windows10 RS5 x64+dotnet-sdk-7.0.100-alpha.1.22057.7:Fail
4). Windows10 RS5 x64+dotnet-sdk-7.0.100-alpha.1.22060.9:Fail

### Configuration

**Application Name**: UMLGenerator
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number:** dotnet-sdk-7.0.100-alpha.1.22060.9

**App and App Source checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460794

### Other information

**Minimal Repro steps:**
dotnet-sdk-7.0.100-alpha.1.22060.9 sdk should be installed on the machine.
1. Create a .NET 5.0 Console project.
2. Add below code in Main() method:
```
 bool result = Regex.IsMatch(" public static class Extensions    {", "(^| +)class");
Console.WriteLine(result);
```
3. Build the project.
4. Change the runtime config under bin\Debug\net5.0 to let it run with .net 7.0 runtime:
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "7.0.0-alpha.1.22055.1"
    }
  }
}
```
5. Press F5 run the app, it will write False in Console window.

**Reproduce demo attached** 
[ConsoleApp4.zip](https://github.com/dotnet/runtime/files/7853911/ConsoleApp4.zip)

**Expected Result:** 
The console window shows True.

**Actual Result:**
The console window shows False.

**Findings:**
When using .NET Core 3.1, .NET 5.0 and .NET 6.0, also .NET Framework, they all return True for above code.

@dotnet-actwx-bot @dotnet/compat

**Comment by danmoseley** [comment]
@joperezr @stephentoub apparent regression from 6.0 -- code complete for Preview 1 is in 2 days, do we need a fix in by then?

**Comment by joperezr** [comment]
I'm now checking if this repros when using a .net 7 app running in .NET 7. Typically we don't guarantee that applications that were built for an older .NET version work well after a major roll forward, as many things could be broken by design so I'm not sure if we should immediately categorize this as a regression. I'll debug to see what is going on and see if there is anything that needs fixing here.

**Comment by stephentoub** [comment]
It does look like a recent regression which we should fix for Preview 1.  I believe the problem is in offset calculation in FindFirstChar when searching for a string.

**Comment by joperezr** [comment]
right, I'm debugging and seems like our optimization of FindFirstChar looks for the multi `class`, finds it at position 15, but then instead of backtracking to find the space, it just returns 15, which of course Go() won't match any longer as it requires at least one space to be present.

**Comment by stephentoub** [comment]
We're probably just missing a `+ offset` somewhere.  Thanks for looking into it.

**Comment by stephentoub** [comment]
> We're probably just missing a + offset somewhere. Thanks for looking into it.

Actually, I take that back. I just looked at the expression again... we shouldn't be searching for "class" at all, because it's not at a fixed-offset from the beginning of the pattern.  Most likely then is a bug in the analysis, in FindCaseSensitivePrefix, e.g. the handling I added for Alternation is probably buggy (we shouldn't be returning a prefix as branches of the alternation have different possible lengths).

**Comment by joperezr** [comment]
Also FWIW, seems like this was introduced in https://github.com/dotnet/runtime/pull/61490

**Comment by stephentoub** [comment]
The benefit of that whole `case RegexNode.Alternate` is a bit dubious.  We might want to just delete the whole case for simplicity.  Alternatively, if we want to try to salvage it, looks like the problem stems from our continuing to process what comes after the alternation when we shouldn't.  It's trying to compute a common prefix from all branches, but it shouldn't continue to what comes after the alternation unless it's guaranteed to always match the same characters for every branch, which will basically never happen.

**Comment by stephentoub** [comment]
Just for reference, I'd added the alternation support because of cases like this:
https://github.com/dotnet/performance/blob/481858c8311a15fdb2525a5860de1a4b09922284/src/benchmarks/micro/libraries/System.Text.RegularExpressions/Perf.Regex.Industry.cs#L160
so there _may_ be some value in trying to salvage it.

**Comment by Junjun-zhao** [comment]
Verify with dotnet-sdk-7.0.100-preview.1.22076.2, it has been fixed.
