### ISSUE TITLE
AllowRenegotiation is ignored on Linux

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#63699]
The code do deal with this option is in common part of `SslStream`. However, renegotiation is handled internally by OpenSSL and we never get `SecurityStatusPalErrorCode.Renegotiate` back.   
We should probably look into `SSL_OP_ALLOW_CLIENT_RENEGOTIATION` and/or `SSL_OP_NO_RENEGOTIATION`.

**Comment by karelz** [comment]
Triage: Platform completeness - we ignore the flag on Linux.
It is rarely used, so far no customer report on Linux.

**Comment by rzikm** [comment]
I'd like to look into this, but I'm afraid there are some versioning-related stuff that I am unsure how to get right:
- `SSL_OP_NO_RENEGOTIATION` was added in 1.1.1
- `SSL_OP_ALLOW_CLIENT_RENEGOTIATION` is added in 3.0.0

Should I check for the OpenSSL version being used and avoid setting an option which is not supported by the currently loaded version?

Should the setting happen in native shim, or should I just expose `SSL_set_option` to Managed code and set them from there?

**Comment by wfurt** [comment]
Is there some other way how to disable renegotiation on 1.0.x? I'd be fine if we do this only on 1.1.1 and above. It seems like all distributions we supper has option to get it. While I don't think e have mechanisms to detect constants runtime, we already know what version we running and/or we can create shim function.

cc: @bartonjs for any additional thoughts.

**Comment by rzikm** [comment]
I dug a bit in OpenSSL manuals, issues, and PRs:
- in 3.0.0, client-initiated renegotiation is disabled by default (breaking change from 1.1.1):  https://github.com/openssl/openssl/issues/14685, to enable renego for clients, one must use `SSL_OP_ALLOW_CLIENT_RENEGOTIATION`
- 1.1.1 and 1.1.0 can use `SSL_OP_NO_RENEGOTIATION` (docs say added in 1.1.1, but was backported to 1.1.0h in https://github.com/openssl/openssl/issues/4739)
- 1.0.2 and below versions could set `SSL3_FLAGS_NO_RENEGOTIATE_CIPHERS` to prevent renegotiation

With that in mind, I think it would be best to add a native function like `SetRenegotiation(SSL*, int32_t val)` that internally handles all these differences.

**Comment by rzikm** [comment]
I have conducted some experiments to see how the current implementation behaves:
- We have (outerloop) tests for server-side renegotiation (testing that `AllowRenegotiation` behaves properly on _clients_): https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamAllowRenegotiationTests.cs#L25, these are running on all platforms, which implies we handle this case correctly on Linux
- We have no tests for client-initiated renegotiation (no API for that), but I was able to test it using a simple ASP.NET Core app and openssl CLI
```
echo "R" | openssl s_client -connect 127.0.0.1:5002
```

<details>
<summary>Test app source code</summary>

```csharp
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.AspNetCore.Server.Kestrel.Https;
using System.Net.Security;
using System.Runtime.InteropServices;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;

var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(options =>
{
    options.ListenAnyIP(5002, listenOptions =>
    {
        var localhostCert = CertificateLoader.LoadFromStoreCert("localhost", "My", StoreLocation.CurrentUser, allowInvalid: true);
        listenOptions.Protocols = HttpProtocols.Http1;

        listenOptions.UseHttps(new TlsHandshakeCallbackOptions()
        {
            OnConnection = context =>
            {
                context.AllowDelayedClientCertificateNegotation = true;

                return new ValueTask<SslServerAuthenticationOptions>(new SslServerAuthenticationOptions
                {
                    EnabledSslProtocols = SslProtocols.Tls12,
                    ServerCertificate = localhostCert,
                    AllowRenegotiation = false
                });
            }
        });
    });

    global::System.Console.WriteLine($"Running on {System.Runtime.InteropServices.RuntimeInformation.OSDescription}");
});

var app = builder.Build();

var logger = app.Services.GetRequiredService<ILogger<Program>>();

app.Run(async context =>
{
    var response = $"hello, world{Environment.NewLine}";
    context.Response.ContentLength = response.Length;
    context.Response.ContentType = "text/plain";
    await context.Response.WriteAsync(response);
});

app.Run();
```
</details>

There were no observable differences between Linux/Windows, debugging shows that the code goes through the `if (status.ErrorCode == SecurityStatusPalErrorCode.Renegotiate)` branch in `SslStream.DecryptData` and throws appropriate exception on the server (System.IO.IOException: 'The remote party requested renegotiation when AllowRenegotiation was set to false.'). It seems that OpenSSL correctly returns `SSL_ERR_RENEGOTIATE`.

That being said, this is with OpenSSL 1.1.1. OpenSSL 3.0 disables client-initiated renegotiation by default, so we still need to do some change to use `SSL_OP_ALLOW_CLIENT_RENEGOTIATION` in case `AllowRenegotiation` is `true`
