### ISSUE TITLE
[wasm] Do not print mono_wasm_runtime_ready to console

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#63703]
Do not print `mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28` to console. 
It's looks quite bad on NodeJS.

**Comment by pavelsavara** [comment]
What scenario would break if we remove it ?

**Comment by thaystg** [comment]
> What scenario would break if we remove it ?
I think press ctrl-shift-d on blazor to attach the debugger will break.

**Comment by pavelsavara** [comment]
If we made it `console.trace` instead, would it sill work?

**Comment by pavelsavara** [comment]
Or maybe even `console.assert("mono_wasm_runtime_ready", "fe00e07a-5519-4dfe-b35a-f867dbaf2e28")` which would be silent.

**Comment by thaystg** [comment]
Moving to 8.0.0 as I didn't get the approval in this PR yet:
https://github.com/dotnet/runtime/pull/72812

**Comment by pavelsavara** [comment]
sorry :(
