### ISSUE TITLE
ICloneable with generics support

### ISSUE THREAD

**Issue by DukeOfSuffix** [dotnet/runtime#63707]
Thanks to default interface methods, it is now possible to write a version of IClonable that supports generics:

    public interface ICloneable<T> : ICloneable
    {
        new T Clone();

        object ICloneable.Clone()
        {
            return Clone();
        }
    }

Is this something the team is willing to consider adding?

**Comment by Clockwork-Muse** [comment]
From the [`ICloneable` documentation](https://docs.microsoft.com/en-us/dotnet/api/system.icloneable?view=net-6.0#notes-to-implementers):
> Because callers of Clone() cannot depend on the method performing a predictable cloning operation, we recommend that ICloneable not be implemented in public APIs.

... so I suspect the answer is likely to be "no".
(although the situation isn't quite as bad as in Java, cloning still has issues in C#)

**Comment by stephentoub** [comment]
This was proposed, discussed, and declined in both https://github.com/dotnet/runtime/issues/37561 and https://github.com/dotnet/runtime/issues/49433.  Closing as a duplicate. Thanks for the suggestion.
