### ISSUE TITLE
Having Issue Running System.DirectoryServices.Protocols.LdapConnection Methods in .NET 6 - Alpine Linux (Docker)

### ISSUE THREAD

**Issue by DriLLFreAK100** [dotnet/runtime#63759]
Hi, I'm having issue running **System.DirectoryServices.Protocols.LdapConnection** methods like **.Bind()**, **.SendRequest()** in Alpine Linux (Docker) environment. It mentions that "the feature is not supported". 

This is pertaining **.NET 6**, with **System.DirectoryServices.Protocols (6.0.0)** package

The sample **code** is as follows:

```
var ldapConn = new LdapConnection(_authSettings.LDAPDomain);

ldapConn.Bind(new NetworkCredential()
{
    UserName = _username,
    Password = _password,
});
```

The sample **error message** is as follows:

```
The feature is not supported. 
[18:38:44 ERR] 
System.DirectoryServices.Protocols.LdapException: The feature is not supported.
at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)    
at System.DirectoryServices.Protocols.LdapConnection.Bind(NetworkCredential newCredential)
```

Am I missing some configurations here? Or is this expected not to work in Linux still? If so, are there any suggestions or workarounds for this? Much thanks in advance!

**Comment by ryank425** [comment]
Looks related https://github.com/dotnet/runtime/issues/60972

**Comment by DriLLFreAK100** [comment]
@ryank425  I've read through that discussions, and doesn't quite catch what's the workaround still. Hmm..

**Comment by joperezr** [comment]
Thanks for logging the issue @DriLLFreAK100. Looks like what you are trying to do is to bind using the Basic Auth type but you are not setting that, which means that you are using the default `AuthType.Negotiate` which in Linux is not yet supported. Can you please try doing the following instead:

```c#
            LdapConnection connection = new LdapConnection(directoryIdentifier, credential)
            {
                AuthType = AuthType.Basic
            };
            connection.SessionOptions.ProtocolVersion = 3;
            connection.Bind();
```

**Comment by DriLLFreAK100** [comment]
Hi @joperezr, thanks for suggestion. I have tried and it's returning me the following error. 

```
The supplied credential is invalid.
System.DirectoryServices.Protocols.LdapException: The supplied credential is invalid.
at System.DirectoryServices.Protocols.LdapConnection.BindHelper(NetworkCredential newCredential, Boolean needSetCredential)
at System.DirectoryServices.Protocols.LdapConnection.Bind()
```
The following is my code snippet

```
var ldapConn = new LdapConnection(
    new LdapDirectoryIdentifier(_authSettings.LDAPDomain),
    new NetworkCredential()
    {
        UserName = _username,
        Password = _password,
    },
    AuthType.Basic);

ldapConn.SessionOptions.ProtocolVersion = 3;
ldapConn.Bind();
```

Is there anything special that I have to take note on the credential construction part? 
Just to rule out some possibilities, I was using the same set of credentials and have successfully called the Bind method on **Windows** prior to setting AuthType.Basic and SessionOptions.ProtocolVersion = 3.

**Comment by joperezr** [comment]
mm I don't think it is an issue with your credentials (as there is really nothing special about how we deal with credentials in Linux vs Windows). If setting AuthType as basic and ProtocolVersion to 3 didn't do the trick, I would suspect it is something with the LdapIdentifier that you are using. It is possible that the underlying native libraries support slightly different formats when referring to the ldap server you want to talk to, since Windows native library could be a bit more permissive in terms of what you pass in. Are you passing in a FQDN? or perhaps an ip address?

**Comment by DriLLFreAK100** [comment]
Haha.. finally got it to work @joperezr. It seems that the username format expected in AuthType.Basic is a little bit different as compared to the default AuthType. 

With the default AuthType, I can just specify my plain username to get it to work. 

```
var ldapConn = new LdapConnection(
    new LdapDirectoryIdentifier(ldapDomain),
    new NetworkCredential()
    {
        UserName = username,
        Password = password,
    });
```
However, after setting it to Basic, I have to specify the distinguish names in the username field to make it work, i.e.. 

```
var ldapConn = new LdapConnection(
    new LdapDirectoryIdentifier(ldapDomain),
    new NetworkCredential()
    {
        UserName = $"CN={username},OU=xx,OU=xx,DC=xx,DC=xx,DC=xx...",
        Password = password,
    },
    AuthType.Basic);
```
With that, the Bind method finally got called through successfully. Not sure if this is something specific to do with how LDAP works?

Following that, I was trying to call the **LdapConnection's SendRequest** with a **SearchRequest**. And I got the "platform unsupported" error once again. Just wanna confirm if this feature is not available for Linux yet.

```
 var request = new SearchRequest(
    ldapDistinguishedNames,
    $"name={username}",
    System.DirectoryServices.Protocols.SearchScope.Subtree,
    new string[] { "mail" });

var result = ldapConn.SendRequest(request) as SearchResponse;
```

**Comment by parrssee** [comment]
@DriLLFreAK100 Hello, what port do you use?
I'm trying to migrate LDAP functionality in my project from win-specific **DirectoryServices** to **DirectoryServices.Protocols**, but I'm stuck with SSL (connection over 389 port is OK, but connection over 636 port fails and I can't understand why)

**Comment by joperezr** [comment]
@parrssee are you setting `connection.SessionOptions.SecureSocketLayer = true;` before calling `Bind()`? We have tests against different types of servers that validate that this works today as long as the server you are trying to connect to supports SSL and has the port open.

**Comment by parrssee** [comment]
> @parrssee are you setting `connection.SessionOptions.SecureSocketLayer = true;` before calling `Bind()`? We have tests against different types of servers that validate that this works today as long as the server you are trying to connect to supports SSL and has the port open.

Yes, I set **SecureSocketLayer** to **true**. It seems that problem with our server, we investigating this right now. Also, will there be support for LDAPS certificates validation on Linux? Thanks

**Comment by joperezr** [comment]
> Also, will there be support for LDAPS certificates validation on Linux?

When using LDAPS in Linux today we are basically only passing through the Bind to the underlying native library (openldap), which does perform a certificate validation. If the certificate fails to validate successfully, you will get an exception in your call to Bind() which should have more info saying that the certificate was invalid or that the connection with the server couldn't be established.

**Comment by parrssee** [comment]
> > Also, will there be support for LDAPS certificates validation on Linux?
> 
> When using LDAPS in Linux today we are basically only passing through the Bind to the underlying native library (openldap), which does perform a certificate validation. If the certificate fails to validate successfully, you will get an exception in your call to Bind() which should have more info saying that the certificate was invalid or that the connection with the server couldn't be established.

Thanks

**Comment by joperezr** [comment]
Closing this issue since seems like the problems being hit are now resolved. @DriLLFreAK100 feel free to reopen if you have any follow up questions.
