### ISSUE TITLE
System.Runtime.InteropServices.Tests is causing large core dumps on macOS

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#63761]
This affects CI, we're temporarily disabling core dump creation with https://github.com/dotnet/runtime/pull/63742

**Comment by safern** [comment]
@akoeplinger curious is there an issue tracking the investigation on what caused the large dumps?

**Comment by akoeplinger** [comment]
No, just a Teams thread on First Responders right now.

**Comment by akoeplinger** [comment]
One suspicious change that was merged around the time when we started seeing the 40-100GB core dumps is #59283

**Comment by mangod9** [comment]
Interesting, will look at this issue. Believe @janvorli was also hitting something similar? Does this mean that a single dump is 100gb in size or just that there are many of them generated?

**Comment by janvorli** [comment]
I was hitting problem pri 1 coreclr tests on macOS getting out of disk space consistently when I ran them explicitly in my CI. The issue got triggered right after the coreclr test `baseservices/exceptions/simple/ParallelCrashMainThread` that intentionally causes a process crash, hence it generates a dump. 
I'll try to check it locally to see if the GC regions are possibly the culprit. Just a quick thought - I think that macOS includes all VM space in the dump, so if the regions reserve huge amount of VM (even without actually mapping them), we may end up getting a huge dump.

**Comment by janvorli** [comment]
Hmm, I've tested the latest state of the main branch locally and I don't see growth of the core dump sizes. E.g. for the test I've mentioned, the dump was about 6GB on my Apple M1 device, like in a state a week ago. That is a usual size of a core dump on macOS.

**Comment by akoeplinger** [comment]
Yeah that `baseservices/exceptions/simple/ParallelCrashMainThread` test didn't see the increase in dump file size.

According to the Kusto data it seems we only saw this with System.Runtime.InteropServices.Tests on amd64 macOS, not on arm64, so you might want to test there (with  https://github.com/dotnet/runtime/pull/63769 and https://github.com/dotnet/runtime/pull/63742 reverted)

**Comment by akoeplinger** [comment]
@mangod9 there were single dumps between 30 and 130GB in size.
