### ISSUE TITLE
`ref` field support in .NET runtimes

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#63768]
There are several moving parts to support `ref` fields, this issue represents work in the actual runtime. 

The high-level tasks for the runtime are below to address the ref fields work.

- [x] CoreCLR support
    - Port specific work from Hackathon project – https://github.com/dotnet/runtime/tree/feature/lowlevelhackathon
    - https://github.com/dotnet/runtime/pull/63985
    - https://github.com/dotnet/runtime/pull/64422
    - https://github.com/dotnet/runtime/issues/64520
    - https://github.com/dotnet/runtime/pull/65246
- [x] Mono support
    - https://github.com/dotnet/runtime/pull/63985
    - https://github.com/dotnet/runtime/issues/64520
    - https://github.com/dotnet/runtime/pull/65246
    - https://github.com/dotnet/runtime/pull/65477
- [x] #64165
- [x] Audit handling of null byrefs in runtime and libraries https://github.com/dotnet/runtime/issues/70268
- [x] Tooling support
    - https://github.com/dotnet/runtime/issues/63751
    - https://github.com/dotnet/runtime/issues/68309
    - [x] Validate Linker support. https://github.com/dotnet/linker/issues/2519
- [x] ECMA update – https://github.com/dotnet/runtime/pull/63659
- [x] Delete the `ByReference<T>` type and replace its use with `ref` fields.
    - https://github.com/dotnet/runtime/pull/71498
- [x] Diagnostics &ndash; Ensure SOS and VS can handle these new semantics.
    - https://github.com/dotnet/diagnostics/pull/2829
    - https://github.com/microsoft/CLRInstrumentationEngine/issues/464
    - https://github.com/dotnet/runtime/pull/65880
    - https://github.com/dotnet/roslyn/issues/62157
- [x] C# test cases &ndash; Comprehensive collection of testing for the runtime.
- [x] Update CrossGen
    - https://github.com/dotnet/runtime/pull/64366
    - https://github.com/dotnet/runtime/pull/64422
    - https://github.com/dotnet/runtime/pull/65477
- [x] Update NativeAOT &ndash; CoreCLR and Mono.
    - https://github.com/dotnet/runtime/pull/64366
    - https://github.com/dotnet/runtime/pull/65477
- [x] Language support - https://github.com/dotnet/roslyn/pull/62155
    - [Low level struct improvements](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md)
    - [`Span<T>` safety](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-7.2/span-safety.md)
    - [Proposal for sunsetting restricted types when targeting `net7`](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#sunset-restricted-types)

This contributes to enabling #45152.

**Comment by jkotas** [comment]
> Remove specialized type handling in runtime – Make ArgIterator, RuntimeArgumentHandle, and TypedReference “just types”.

I am not sure what this is about. The runtime does not have any special handling of these types. (Roslyn does - but you have it under separate check box.)

Also in the list should be: Delete the internal `ByReference<T>` type and replace its use with `ref` fields.

**Comment by jaredpar** [comment]
> Remove specialized type handling in runtime – Make ArgIterator, RuntimeArgumentHandle, and TypedReference “just types”.

I believe @davidwrighton believes there is some spec work necessary before we can remove the notion of special types. Likely I think we will also need a feature flag in corelib to identify runtimes where Roslyn is safe to remove the notion of restricted types and depend solely on the type definition being correct. But agree bulk of the work here is in Roslyn.

**Comment by vitek-karas** [comment]
We may possibly need dotnet/linker and mono/cecil work - it needs to be able to roundtrip assembly with ref fields correctly. I know it's not specifically about runtime - but it will be needed in order to use it in the runtime (since we run the code through linker during build).

**Comment by AaronRobinsonMSFT** [comment]
> We may possibly need dotnet/linker and mono/cecil work

This was brought up in the initial planning meeting. If I recall, @davidwrighton wasn't sure there should be any impact.

**Comment by vitek-karas** [comment]
I created https://github.com/dotnet/linker/issues/2519 to track the validation on the linker side - at the very least we should add some tests for this in the linker.

**Comment by John0King** [comment]
How big is the size of a `ref`?  if it is fixed like 64bit ,  then a ref struct contains ref itself should also be legal like `class`

see 
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRLKsBLCAbAE2QBoCQBqAHwAEAmARgFgAoFl6gZgAIMvkYEcAMYwuAFSQQAcgHsCEFgG8WXVVwAOCbADdYEHhDDjJs+VwAyh0VwDcKtSwC+bVs05c6xiNLkQAwnhQyMhK9qruqhLepv6BwRZWigDmEDA2yKk2zsxqXGEe3JEmvgFByFwASthJABYwyZkZadnZLEA=

**Comment by svick** [comment]
@John0King That is likely going to be fixed, see https://github.com/dotnet/roslyn/issues/62098.

**Comment by hamarb123** [comment]
Just a question, if `ByReference<T>` is removed and in the future we allow things like `Span<Span<int>>`, would something like `Span<ref int>` be allowed or would someone need to create their own `ByReference` type to use like so `Span<ByReference<int>>`.

**Comment by AaronRobinsonMSFT** [comment]
> would something like Span<ref int> be allowed or would someone need to create their own ByReference type to use like so Span<ByReference<int>>.

At present, users would need to create `Span<ByReference<int>>`. The `ref` in a generic suffers from the same issues as [pointers (`*`)](https://github.com/dotnet/runtime/issues/13627).

**Comment by hamarb123** [comment]
> At present, users would need to create `Span<ByReference<int>>`. The `ref` in a generic suffers from the same issues as [pointer types (for example, `int*`)](https://github.com/dotnet/runtime/issues/13627).

I hope this gets implemented in the future. I think a good solution would be to make a new generic constraint that allows these things (e.g. allow pointer, allow ref, allow ref struct, allow any other appropriate types, allow all, which could be expressed through a modopt or attribute), which doesn't allow boxing i.e. no calls to methods on object (ToString, GetHashCode etc., GetType of some form should still exist though). This would still allow many operations to work, just not the ones that wouldn't necessarily make sense for the types specified as allowed.

**Comment by jaredpar** [comment]
> > At present, users would need to create Span<ByReference<int>>. The ref in a generic suffers from the same issues as https://github.com/dotnet/runtime/issues/13627.

> I hope this gets implemented in the future. I think a good solution would be to make a new generic constraint that allows these things (e.g. allow pointer, allow ref, allow ref struct, allow any other appropriate types, allow all, which could be expressed through a modopt or attribute), which doesn't allow boxing i.e. no calls to methods on object (ToString, GetHashCode etc., GetType of some form should still exist though)

The issue goes deeper. In order for a generic anti-constraint, like `allow T: ref struct`, to be useful you also need to support `ref` fields to `ref struct` in the span safety rules. That has a number of unintuitive behaviors associated with it as well as forcing us to add yet another layer of ref safety into the ruleset. A few of the challenges are described [here](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#ref-fields-to-ref-struct). 

It's certainly doable but it does come with a significant complexity cost. 

At the core I think the following three features are tied together: 

- `ref` fields to `ref struct`
- `ref struct` as generic arguments
- `ref struct` implementing interfaces

Doing one pretty much pulls you into doing the other two very quickly.

**Comment by mangod9** [comment]
@AaronRobinsonMSFT are there items pending for 7 or does this need to be moved to 8?

**Comment by AaronRobinsonMSFT** [comment]
Nope, this is done. Tests that can/should be in C# have been converted.

**Comment by vitek-karas** [comment]
We haven't look at linker yet though... https://github.com/dotnet/linker/issues/2519
@agocke

**Comment by AaronRobinsonMSFT** [comment]
Shoot. That wasn't a checkbox :(

**Comment by mangod9** [comment]
is this expected to be complete this week?

**Comment by vitek-karas** [comment]
Yes - @jtschuster  is working on it in the linker repo right now.

**Comment by John0King** [comment]
ref itself seem's being cut ?

**Comment by hamarb123** [comment]
@John0King , ref fields should be in a ref struct, and is only .NET 7+

**Comment by John0King** [comment]
@hamarb123  so there still no way to write a `BineryTree` or other `Tree` in  struct ?

**Comment by hamarb123** [comment]
No, because a `ref` field must be in `ref struct`, but a `ref` field cannot refer to a `ref` struct. If your value type is a `unmanaged` struct, then you could `stackalloc` some memory and manage everything manually (i.e. create a new allocator like malloc for that segment of memory, re-interpretation of memory for the value type, 'pointers' to other values which could just be an offset from the start etc.) then you could possibly create something of use, but it seems like a lot of effort to me and has the issue of the stackalloc'd memory running out, and the `ref` field wouldn't really help there.

**Comment by John0King** [comment]
I think the `ref` of the field is not the same size of the struct, (I understand the `ref` is like `pointer` , it should be 32/64 bit )  so a struct has a `ref` or another struct of it's type is 
```
(in byte)
----------------
ref  file a           int filed b    ref field c
0 1 2 3 4 5 6 7      0 1 2 3        0  1 2 3 4 5 6 7
```

**Comment by hamarb123** [comment]
`ref` fields are implemented as managed pointers (which are just pointers that move with the GC). The reason that you can't stick them in any type (such as a `struct` that is not a `ref struct`) is due to the span safety rules, if you want to read in-depth what they are and why they are what they are see here https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md. `ref` fields to `ref struct`s are planned for C# 12 / .NET 8 currently.
