### ISSUE TITLE
can't launch another application as administrator mode

### ISSUE THREAD

**Issue by xybertom** [dotnet/runtime#63784]
### Description

When starting an app in administrator mode from an app that is not in administrator mode, specify "runas" in the verb of ProcessStartInfo or specify "requireAdministrator" in the manifest of the app you want to start, but NET 6 does not seem to start the app.

### Reproduction Steps

- Manifest for an app launched in administrator mode
```
~
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
~
```

- Program(non-administrator mode)
```
using System.ComponentModel;
using System.Diagnostics;

var processStartInfo = new ProcessStartInfo
{
    FileName = @"Path\to\app",
    Verb = "runas",
};

try
{
    var process = Process.Start(processStartInfo);
    process.WaitForExit();
}
catch (Win32Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

### Expected behavior

the UAC dialog appears,

### Actual behavior

a Win32Exception occurs.
```
System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'Path\to\app' with working directory 'ExecutablePath'. 要求された操作には管理者特権が必要です。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Program.<Main>$(String[] args) in ExecutablePath\Program.cs:line 13
```

### Regression?

When running with .NET Framework 4.7.2, the UAC dialog appears.

### Configuration

- .NET 6
- Windows 10 Pro 21H1
- x86

**Comment by KalleOlaviNiemitalo** [comment]
You need to set ProcessStartInfo.UseShellExecute = true, for ProcessStartInfo.Verb to have any effect. The default is true on .NET Framework but changed to false in .NET Core.

**Comment by KalleOlaviNiemitalo** [comment]
Documented as a breaking change in <https://docs.microsoft.com/dotnet/core/compatibility/corefx#change-in-default-value-of-useshellexecute>.
