### ISSUE TITLE
`NetworkChange.NetworkAddressChanged` event leaks threads on Linux

### ISSUE THREAD

**Issue by vdjuric** [dotnet/runtime#63788]
### Description

When you enable HTTP/3 support on Linux and repeatedly get HTTP/2 or HTTP3 web page, ".NET Network Address Change" threads will start to accumulate.

It seems network address change event is triggered from https://source.dot.net/#System.Net.Http/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs with call _poolManager.StartMonitoringNetworkChanges();

NetworkAddressChange.Unix.cs will start creating threads with name ".NET Network Address Change":
https://source.dot.net/#System.Net.NetworkInformation/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs

### Reproduction Steps

----------------------------------------------------------------------------
.NET 6 console project, source code example:
----------------------------------------------------------------------------

```C#
using System.Diagnostics;

static async Task ThreadDiagnostics()
{
    var pid = Process.GetCurrentProcess().Id;
    var psi = new ProcessStartInfo("ps", $"-T -p {pid}");
    psi.RedirectStandardOutput = true;

    using var process = Process.Start(psi);
    if (process == null)
    {
        throw new Exception("Could not create process");
    }

    int threadCountNetworkAddressChange = 0;
    var output = await process.StandardOutput.ReadToEndAsync();
    using (var sr = new StringReader(output))
    {
        while (true)
        {
            var line = await sr.ReadLineAsync();
            if (line == null)
            {
                break;
            }

            if (line.IndexOf(".NET Network Ad") > 0)
            {
                threadCountNetworkAddressChange++;
            }

            //NOTE:
            //we are searching for threads containing ".NET Network Ad"

            //new Thread(s => LoopReadSocket((int)s!))
            //{
            //    IsBackground = true,
            //    Name = ".NET Network Address Change"
            //}.UnsafeStart(newSocket);
            //
            //https://source.dot.net/#System.Net.NetworkInformation/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs
        }
    }

    //Console.WriteLine(output);
    Console.WriteLine($"{DateTime.Now} '.NET Network Address Change' threads: {threadCountNetworkAddressChange}");
}

for (var i = 0; i < 60; i++)
{
    try
    {
        using (var client = new HttpClient())
        {
            client.DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact;
            using var req = new HttpRequestMessage(HttpMethod.Get, "https://cloudflare-quic.com/"); //HTTP/2 or HTTP/3 enabled web server
            req.Version = System.Net.HttpVersion.Version20;

            using var res = await client.SendAsync(req);
            res.EnsureSuccessStatusCode();
        }

        await ThreadDiagnostics();
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Unhandled exception: {ex}");
    }

    await Task.Delay(1000);
}
```

----------------------------------------------------------------------------
Dockerfile with installed libmsquic and required tools (procps, curl)
----------------------------------------------------------------------------

- See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

```
FROM mcr.microsoft.com/dotnet/runtime:6.0-bullseye-slim AS base
WORKDIR /app

#install some tools
RUN apt-get update && apt-get install -y procps curl

#install libmsquic
#https://docs.microsoft.com/en-us/dotnet/core/extensions/httpclient-http3
RUN curl https://packages.microsoft.com/debian/11/prod/pool/main/libm/libmsquic/libmsquic_1.9.0_amd64.deb --output libmsquic.deb
RUN dpkg -i libmsquic.deb

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HttpClientMemoryLeak/HttpClientMemoryLeak.csproj", "HttpClientMemoryLeak/"]
RUN dotnet restore "HttpClientMemoryLeak/HttpClientMemoryLeak.csproj"
COPY . .
WORKDIR "/src/HttpClientMemoryLeak"
RUN dotnet build "HttpClientMemoryLeak.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HttpClientMemoryLeak.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HttpClientMemoryLeak.dll"]
```

### Expected behavior

".NET Network Address Change" should not accumulate, especially if HTTP connections are not pooled.

Check https://source.dot.net/#System.Net.Http/System/Net/Http/SocketsHttpHandler/HttpConnectionPoolManager.cs

```
bool avoidStoringConnections =
                settings._maxConnectionsPerServer == int.MaxValue &&
                (settings._pooledConnectionIdleTimeout == TimeSpan.Zero ||
                 settings._pooledConnectionLifetime == TimeSpan.Zero);
```

### Actual behavior

".NET Network Address Change" threads will start to accumulate and consume resources / memory.

**Comment by vdjuric** [comment]
Just small update: HTTP/3 must be enabled in .csproj by adding following entry

```xml
<ItemGroup>
	<RuntimeHostConfigurationOption Include="System.Net.SocketsHttpHandler.Http3Support" Value="true" />
</ItemGroup>
```

**Comment by ManickaP** [comment]
I just re-ran the repro. It reproduces, but it doesn't seem to be specific to HTTP/3 but rather a leak in `NetworkChange.NetworkAddressChanged` event.

This also reproduces with just this, instead of `HttpClient` usage:
```C#
NetworkAddressChangedEventHandler networkChangedDelegate;
networkChangedDelegate = delegate
{
    Console.WriteLine("called");
};
NetworkChange.NetworkAddressChanged += networkChangedDelegate;
NetworkChange.NetworkAddressChanged -= networkChangedDelegate;
```

Seems like bug in `NetworkChange`.

**Comment by stephentoub** [comment]
> This also reproduces with just this, instead of HttpClient usage:

Are you saying if you put that in a loop it creates lots of threads that never go away?

**Comment by vdjuric** [comment]
Yes!

**Comment by stephentoub** [comment]
> With my test: yes

I was particularly wondering about @ManickaP's.

**Comment by vdjuric** [comment]
Following Harmony patch seems to workaround this issue :S

```C#
var harmony = new HarmonyLib.Harmony("MemoryLeakFix");

var asm = typeof(System.Net.NetworkInformation.NetworkChange);

{
	var method = asm.GetMethod("CreateSocket", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
	var methodNew = typeof(AdvancedWebTask).GetMethod("Transpiler", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
	harmony.Patch(method, transpiler: new HarmonyLib.HarmonyMethod(methodNew));

}

{
	var method = asm.GetMethod("CloseSocket", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
	var methodNew = typeof(AdvancedWebTask).GetMethod("Transpiler", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
	harmony.Patch(method, transpiler: new HarmonyLib.HarmonyMethod(methodNew));
}

private static IEnumerable<HarmonyLib.CodeInstruction> Transpiler(IEnumerable<HarmonyLib.CodeInstruction> instructions)
{
	return new[] { new HarmonyLib.CodeInstruction(System.Reflection.Emit.OpCodes.Ret) };
}
```

**Comment by stephentoub** [comment]
It does look like there's a race condition between the worker thread and CloseSocket. Should be easy to fix.

**Comment by vdjuric** [comment]
Sorry, it is returning now '.NET Network Address Change' threads: 9

```C#
for (var i = 0; i < 10; i++)
{
    NetworkAddressChangedEventHandler networkChangedDelegate;
    networkChangedDelegate = delegate
    {
        Console.WriteLine("called");
    };
    NetworkChange.NetworkAddressChanged += networkChangedDelegate;
    NetworkChange.NetworkAddressChanged -= networkChangedDelegate;
}

while (true)
{
    await ThreadDiagnostics();
    await Task.Delay(1000);
}
```

**Comment by ManickaP** [comment]
With my example I got growing number of threads, even though slowly than with `HttpClient`. I did run it from command line though, natively on Linux. When I run it with debugger attached, it reports 1 thread (which still should be 0 after removing the event listener).

This seems like a race. I also dug a bit around the code and the thread should finish on its own once the `s_socket` is nulled:
https://github.com/dotnet/runtime/blob/0b527a201f4c286f13ef8b829bbd1651bdad7a52/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs#L173-L179

The only think I can think of is that the subsequent call of:
https://github.com/dotnet/runtime/blob/0b527a201f4c286f13ef8b829bbd1651bdad7a52/src/libraries/Common/src/Interop/Unix/System.Native/Interop.NetworkChange.cs#L20
returns the same fd for the new socket, thus `s_socket` gets set to the same number even though it's a different run and different registration...

Based on Linux docs: https://man7.org/linux/man-pages/man2/socket.2.html I assume that getting the same fd is highly likely:
> The file descriptor returned by a successful call will be the lowest-numbered file descriptor not currently open for the process.

**Comment by stephentoub** [comment]
That was my guess as well.

**Comment by MihaZupan** [comment]
Yep, it's always getting the same socket id

**Comment by karelz** [comment]
Triage: Used in HTTP/3, we should fix it in 7.0.

**Comment by vdjuric** [comment]
Possible solution: adding "s_socketCreateContext" counter which changes each time CreateSocket() method is called. Method LoopReadSocket then accepts LoopReadSocketArgs args instead of int socket:

```C#
private static volatile int s_socketCreateContext;

private class LoopReadSocketArgs
{
	public LoopReadSocketArgs(int socketCreateContext, int socket)
	{
		SocketCreateContext = socketCreateContext;
		Socket = socket;
	}

	public int SocketCreateContext { get; }
	public int Socket { get; }
}

private static unsafe void CreateSocket()
{
	Debug.Assert(s_socket == 0, "s_socket != 0, must close existing socket before opening another.");
	int newSocket;
	Interop.Error result = Interop.Sys.CreateNetworkChangeListenerSocket(&newSocket);
	if (result != Interop.Error.SUCCESS)
	{
		string message = Interop.Sys.GetLastErrorInfo().GetErrorMessage();
		throw new NetworkInformationException(message);
	}

	s_socket = newSocket;
	var socketCreateContext = System.Threading.Interlocked.Increment(ref s_socketCreateContext);
	
	new Thread(s => LoopReadSocket((LoopReadSocketArgs)s!))
	{
		IsBackground = true,
		Name = ".NET Network Address Change"
	}.UnsafeStart(new LoopReadSocketArgs(socketCreateContext, newSocket));
}

private static unsafe void LoopReadSocket(LoopReadSocketArgs args)
{
	while (args.Socket == s_socket && args.SocketCreateContext == s_socketCreateContext)
	{
		Interop.Sys.ReadEvents(socket, &ProcessEvent);
	}
}
```

**Comment by ManickaP** [comment]
@vdjuric can you put up a PR for what you suggest?

**Comment by vdjuric** [comment]
Not perfect solution, but I think it should solve thread leaking. I will prepare PR.
