### ISSUE TITLE
DiscardBufferedData does not skip BOM when the position is reset to the beginning

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/runtime#63789]
### Description

Even though the `StreamReader` already skips BOM when first reading from a stream, it fails to skip it a second time when `DiscardBufferedData` is called after the underlying stream's position is back to 0.

### Reproduction Steps

1. Create an instance of `StreamReader` pointing to a file that uses BOM and which encoding is one of the following - Big Endian Unicode, Little Endian Unicode, Little Endian UTF32, Big Endian UTF32, UTF-8 (the ones we support auto-detection for), alternatively - supply your own encoding to the `StreamReader` constructor.
2. Peek at the stream, effectively loading the correct encoding based on the BOM, as you can verify by accessing `StreamReader.CurrentEncoding` property.
3. Read the first line of the file.
4. Invoke `StreamReader.BaseStream.Position = 0` and `StreamReader.DiscardBufferedData()`.
5. Read the first line of the file.
6. Compare the two lines - they will be different - the first one is without any BOM, the second one is with. (You can also compare their lengths.)

### Expected behavior

I expect that `StreamReader` will remember if the file had BOM, so that in the event `DiscardBufferedData` is called and the stream is back to the beginning, the BOM bytes will be skipped as `StreamReader` does so when reading from the underlying stream for the first time.

### Actual behavior

`StreamReader.DiscardBufferedData` does not skip any BOM even though the end-user has set the underlying stream's position to 0.

### Known Workarounds

Create a new instance of `StreamReader` after setting the position to the underlying stream to 0.

### Other information

I'd be happy to make an initial draft if this sounds like something you'd like to see fixed.

**Comment by adamsitnik** [comment]
> I'd be happy to make an initial draft if this sounds like something you'd like to see fixed.

We should definitely  fix it. Please let me know if you need some help with the PR.

**Comment by SpiritBob** [comment]
> > I'd be happy to make an initial draft if this sounds like something you'd like to see fixed.
> 
> @SpiritBob We should definitely fix it. Please let me know if you need some help with the PR.

Sorry, it should have been a draft PR, but I somehow forgot about it. Let me know if it's okay! Should I also add a unit test in https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO/tests/StreamReader/StreamReaderTests.cs ?

**Comment by adamsitnik** [comment]
> Sorry, it should have been a draft PR, but I somehow forgot about it and made an actual PR. Let me know if it's okay!

It's okay!

>  Should I also add a unit test in https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO/tests/StreamReader/StreamReaderTests.cs ?

Yes, please

**Comment by SpiritBob** [comment]
This seems to be more of a feature request than a bug. The method `DiscardBufferedData` does what it's supposed to do, as discussed in the PR.

**Comment by stephentoub** [comment]
Thanks, @SpiritBob.
