### ISSUE TITLE
FileLoadException on System.Runtime with FrameworkReference

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#638]
I am hitting an issue that I filed on the sdk repos here: https://github.com/dotnet/sdk/issues/3929
It contains all the details and a repro app, but I think it's related to corehost.

**Comment by jkotas** [comment]
System.Runtime.dll is version 4.2.1.0, but the PlatformBenchmarks.dll is referencing 5.0.0.0. I guess this is problem with build coherency:libraries implementations are from before the 5.0 version bump, but everything else is from after the 5.0 version bump.

**Comment by jkotas** [comment]
This is should fix itself on its own once dotnet/runtime start flowing through the system.

**Comment by joshpearce** [comment]
> This should fix itself on its own once dotnet/runtime start flowing through the system.

To see that eventual fix, do I just need to keep pulling the latest from the AspNetCore repo, building, activating the custom environment, creating a new project and trying to run it? Is there anything specific I can be on the lookout for to know then the runtime has "flowed through the system"?

**Comment by jkotas** [comment]
@dotnet/runtime-infrastructure What is the current ETA for having live-live official builds from the consolidated runtime repo?

**Comment by trylek** [comment]
End of this week or early next week assuming there are no further AzDO hiccups, otherwise I doubt we can get to them before the New Year with the oncoming EOY holidays.

**Comment by jkotas** [comment]
@trylek Is there issue tracking the live-live official build that people can watch?

**Comment by safern** [comment]
That would be: https://github.com/dotnet/runtime/issues/98

**Comment by trylek** [comment]
Great, thanks Santi for sharing. Internally this is tracked under the work item 

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020770

currently assigned to me.

**Comment by sebastienros** [comment]
What "build" should I follow? There is a dotnet/core-sdk and dotnet/sdk. It looks like I'd need to use dotnet/sdk but the latest built version mentioned doesn't work with dotnet-install.

**Comment by dagood** [comment]
I've been posting some updates about the dotnet/runtime official build at https://github.com/dotnet/runtime/issues/98. At the moment dotnet/toolset and dotnet/extensions uptake is blocked, but that should be fixed soon (https://github.com/dotnet/runtime/issues/1129).

Once that flows through, the SDK zips that redist the various runtimes (what dotnet-install downloads) are built by dotnet/core-sdk, so you'll need to look for a build there.

But if you don't need a full SDK zip, just the .NET Core Runtime to try out with your repro app, those are already available. Unfortunately you need to make the URL yourself until we get an Arcade feature to let us make the dotnet/runtime readme work. (Some context on that: https://github.com/dotnet/runtime/issues/1154#issuecomment-572284221.)

**Comment by sebastienros** [comment]
Fixed, thanks
