### ISSUE TITLE
Cannot regenerate ref assembly in System.Runtime.Intrinsics

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#63815]
I cannot regenerate the ref assembly (no files changed).

![grafik](https://user-images.githubusercontent.com/10373452/149594831-e69a66ee-5efc-4c30-b3c7-0aefea112720.png)

https://github.com/dotnet/runtime/blob/4679edc6be3eb91263a7acfe542dfd30b53ed2bf/docs/coding-guidelines/updating-ref-source.md#for-most-assemblies-within-libraries

Here this error occurs: https://github.com/deeprobin/runtime/tree/597b061397669e79bf9734ecfeeed276f48ac44e

/cc @tannergooding

**Comment by tannergooding** [comment]
CC. @safern, @ViktorHofer

**Comment by ericstj** [comment]
Did you first build your changes?

**Comment by ericstj** [comment]
This target requires a binary for input.  It looks like it will skip if the binary doesn't exist.  

I checked out your commit, built that library (observing errors) , then ran the command:
```
C:\src\dotnet\runtime\src\libraries\System.Runtime.Intrinsics\src>dotnet msbuild /t:GenerateReferenceAssemblySource
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Generated reference assembly source code: C:\src\dotnet\runtime\src\libraries\System.Runtime.Intrinsics\ref\System.Runtime.Intrinsics.cs
```
It produced the diff https://github.com/ericstj/runtime/commit/3c96117a098383d76ef0470a9995e5281219ff6f

If I delete the src assembly I can reproduce the behavior you report.  Please make sure to first build the library before running GenerateReferenceAssemblySource.

**Comment by deeprobin** [comment]
@ericstj Thanks, I think it was because I did a release before and not a debug build

**Comment by ericstj** [comment]
In that case you can specify `/p:Configuration=Release` when running the target.
