### ISSUE TITLE
native host loading more than one .net core DLL issue

### ISSUE THREAD

**Issue by eladser** [dotnet/runtime#63839]
### Description

Hey, Not sure this is an issue or intended, but I am creating a c host, and load 2 different .net core dlls .
The issue is that it seems like the memory is not shared between them , when i am trying to call initialization functions, static members are not initialized.
is there a way to use the host and load more than one dll , having the same CLR?

### Reproduction Steps

create native c host , using hostfxr load functions from 2 different dlls, and try to change static members on them using functions from each dll

### Expected behavior

successfully change one class static member from the other.

### Actual behavior

each dll creates a new static member therefor cannot change each other's static members.

**Comment by eladser** [comment]
ok, resolved this by loading the functions from both Dll's ( 1 & 2 ) using the same dll ( 2 ) name in load_assembly_and_get_function_pointer, since dll number 1 is referenced in dll number 2 in the .net core projects it works fine. it is written vaguely in the documentation.
Thanks.

**Comment by vitek-karas** [comment]
When using native hosting APIs currently the behavior is that each dll loaded through this API is loaded into its own load context (`AssemblyLoadContext`) and all of its dependencies will be isolated. This probably leads in your case to loading the same dll twice, a thus having two separate versions of statics (and really everything).
