### ISSUE TITLE
Use -fno-strict-aliasing

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/runtime#6383]
The JIT includes this code:

``` c++
            float f = 0.0;
            int* addr = NULL;
            if (args->TypeGet() == TYP_FLOAT) 
            {
                f = (float) args->gtDblCon.gtDconVal;
                // *(long*) (&f) used instead of *addr because of of strict
                // pointer aliasing optimization. According to the ISO C/C++
                // standard, an optimizer can assume two pointers of
                // non-compatible types do not point to the same memory.
                inst_IV(INS_push, *((int*) (&f)));
                genSinglePush();
                addrReg = 0;
            }
```

I suspect that this is still invalid under strict aliasing, since a float and int pointer can be assumed not to alias.

This is likely pervasive in CoreCLR, so I suggest using `-fno-strict-aliasing` on compilers that support it, instead of trying to fix every case.

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
I'm going to close this

**Comment by DemiMarie** [comment]
@BruceForstall was this found not to be necessary?

**Comment by BruceForstall** [comment]
I'm closing old issues where action hasn't been taken. There are no known bugs due to this (that I know of)
