### ISSUE TITLE
Source generated System.Text.Json serialization uses AOT-unfriendly reflection

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#63843]
### Description

The source generated System.Text.Json serialization should not be using reflection (https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/#comment-9820).

More context: https://github.com/dotnet/runtimelab/issues/635#issuecomment-1013824472

### Reproduction Steps

- Clone NativeAOT sample from https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/samples/HelloWorld
- Replace Program.cs with:
```
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

Player player = new() { Id = 1 };
string json = JsonSerializer.Serialize(player, JsonContext.Default.Player);
Console.WriteLine(json);

internal class Player
{
    public int? Id { get; set; }
}

[JsonSerializable(typeof(Player), GenerationMode = JsonSourceGenerationMode.Serialization)]
internal partial class JsonContext : JsonSerializerContext { }
```
- Add `<PropertyGroup><TrimmerSingleWarn>false</TrimmerSingleWarn></PropertyGroup>` to .csproj file
- `dotnet publish -c Release -r win-x64`

### Expected behavior

No warnings about uses of AOT-unfriendly reflection APIs.

### Actual behavior

/_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/GenericMethodHolder.cs(31): AOT analysis warning IL3050: System.Text.Json.Serialization.Metadata.GenericMethodHolder.CreateHolder(Type): Using member 'System.Type.MakeGenericType(Type[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. The native code for this instantiation might not be available at runtime.

**Comment by eiriktsarpalis** [comment]
It would seem like the sole purpose of the "GenericMethodHolder" class is to produce the value of `default(T)` where `T` is a statically unknown `System.Type` instance. Even though it would seem like [this particular code path is not used in the case of source generation](https://github.com/dotnet/runtime/blob/8604989022950ef38f94b9150043b31d81f061a5/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonParameterInfo.cs#L93) I think it might be possible to obtain the default value without taking a dependency on `Type.MakeGenericType` (see https://stackoverflow.com/a/6553303 for an example of how that might be done). 

We should service this in 6.0 cc @layomia.

**Comment by kasperk81** [comment]
> AOT-unfriendly reflection

shouldn't generated code strictly free from all kinds of reflection? that is the first advantage of source-generator feature which comes to mind.
