### ISSUE TITLE
NullabilityInfoContext does not properly respect CodeAnalysis attribute on indexer property

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#63849]
### Description

In most cases code analysis attributes like AllowNull are respected, but this is not true for indexer properties.

### Reproduction Steps

```C#
public void Main()
{
        var context = new NullabilityInfoContext();
        var indexerInfo = context.Create(typeof(HasIndexer).GetProperty("Item")!);
       Console.WriteLine(indexerInfo.WriteState); // NotNull (should be Nullable)
}

    public class HasIndexer
    {
        [AllowNull] public string this[string? s]
        {
            get => default!;
            set { }
        }
    }
```

### Expected behavior

The write state should be nullable because the following compiles without warnings:

```
new HasIndexer()["a"] = null;
```

### Actual behavior

Write state is not null as if the attribute were not present.

### Configuration

VS 17.0.2, .NET 6, Windows 10 x64.

I don't have any reason to believe this is configuration specific.

### Other information

CC @Shane32

**Comment by danmoseley** [comment]
Thanks for opening these nullable annotation bugs @madelson . Are you interested in offering a PR for any of them?

**Comment by madelson** [comment]
@danmoseley yes I'm working on fixes for some of them with the idea of sending a PR.
