### ISSUE TITLE
Memory load calculation used by GC is not aligned with Docker and Kubernetes

### ISSUE THREAD

**Issue by dennis-yemelyanov** [dotnet/runtime#63840]
### Description

Current logic in [GetCGroupMemoryUsage](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/gc/unix/cgroup.cpp#L404) to calculate container memory usage from a GC perspective may produce a significantly different value than popular container tools such as Docker and Kubernetes (for example, for the below test application it's about 30% lower than expected).

This can result in containers unnecessarily getting OOM-killed due to the GC not being able to detect high memory pressure.

Both [Docker](https://github.com/docker/cli/blob/6e2838e18645e06f3e4b6c5143898ccc44063e3b/cli/command/container/stats_helpers.go#L230) and [Kubernetes](https://github.com/google/cadvisor/blob/a3b5f4f6c501d5a4ac67530bc973a05c1ebd7d8c/container/libcontainer/handler.go#L836) use a different method: get total memory usage from `memory.usage_in_bytes` and subtract the `total_inactive_file` value of `memory.stat`.

Would it be possible to update .NET implementation to use the same method?

### Reproduction Steps

1. Run `dotnet new console -n MemoryLoadTest` using the latest .NET SDK (6.0.101 at the moment) and add the following code to `Program.cs`:

```C#
var lockObj = new object();

var rnd = new Random();

var cache = new Dictionary<int, int[]>();

Console.WriteLine("Seconds\tMemoryLoadBytes\t\tcache.Count");

var runTimeInSeconds = int.Parse(Environment.GetEnvironmentVariable("RUN_TIME_IN_SECONDS")!);

// Start 1000 threads. Each thread adds a cache item every 5-10s
for (int i = 0; i < 1000; i++)
{
    new Thread(() =>
    {
        while (true)
        {
            int sleepTime;

            lock (lockObj)
            {
                sleepTime = rnd.Next(5000, 10000);

                var cacheItem = new int[10 * 1024];

                cache[cacheItem.GetHashCode()] = cacheItem;
            }

            Thread.Sleep(sleepTime);
        }
    })
    { IsBackground = true }.Start();
}

// Remove random item from cache every 10ms
for (int i = 1; i <= runTimeInSeconds * 100; i++)
{
    lock (lockObj)
    {
        if (cache.Count > 0)
        {
            cache.Remove(cache.Keys.ElementAt(rnd.Next(cache.Count)));
        }

        if (i % 100 == 0)
        {
            Console.WriteLine($"{i / 100}\t{Format(GC.GetGCMemoryInfo().MemoryLoadBytes)}\t{cache.Count}");
        }
    }

    Thread.Sleep(10);
}

Console.WriteLine("Finished successfully!");

string Format(long bytes) => $"{bytes} ({Math.Round((double)bytes / 1024 / 1024, 2)}MiB)";
```
2. Create the following `Dockerfile` in the `MemoryLoadTest` folder:

```dockerfile
FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["MemoryLoadTest.csproj", "MemoryLoadTest/"]
RUN dotnet restore "MemoryLoadTest/MemoryLoadTest.csproj"
COPY . "MemoryLoadTest/"
WORKDIR "/src/MemoryLoadTest"
RUN dotnet build "MemoryLoadTest.csproj" -c Release -o /app/build
RUN dotnet tool install --tool-path /tools dotnet-trace

FROM build AS publish
RUN dotnet publish "MemoryLoadTest.csproj" -c Release -o /app/publish --os linux --self-contained true

FROM base AS final
WORKDIR /tools
COPY --from=build /tools .
WORKDIR /app
COPY --from=publish /app/publish .
ENV PATH="${PATH}:/tools"

# copy coreclr build from CORECLR_BUILD_PATH and start dotnet-trace, which will create gc.nettrace in [runtime repository root]/artifacts
ENTRYPOINT ["/bin/sh", "-c" , "if [ \"$CORECLR_BUILD_PATH\" != \"\" ] ; then echo \"copying coreclr from $CORECLR_BUILD_PATH ...\" && cp -r \"$CORECLR_BUILD_PATH/.\" /app/ && echo 'finished copying!' ; fi  && dotnet-trace collect -o /runtime/artifacts/gc.nettrace --profile gc-collect --show-child-io -- dotnet MemoryLoadTest.dll"]
```
3. From `MemoryLoadTest` run `docker build -t memoryloadtest -f Dockerfile .`

4. (Optional) In a separate window run `docker stats` to start monitoring containers.

5. Checkout the latest main branch of the runtime repository.

6. Build the runtime repository (replace [runtime repository root] with local runtime repository path): 

`docker run --rm -v [runtime repository root]:/runtime -w /runtime mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-a50a721-20191120200116 ./build.sh -subset clr -configuration release -clang9`

7. Run the application (replace [runtime repository root] with local runtime repository path):

`docker run -m 165m --memory-swap 165m --name MemoryLoadTest --rm --env RUN_TIME_IN_SECONDS=20 -v [runtime repository root]:/runtime --env CORECLR_BUILD_PATH=/runtime/artifacts/bin/coreclr/Linux.x64.Release -it memoryloadtest`

Observe that the application reaches the memory limit after about 13 seconds and gets OOM-killed. Also `MemoryLoadBytes` is significantly lower than container memory usage reported by `docker stats`:
```
Seconds MemoryLoadBytes         cache.Count
1       81317068 (77.55MiB)     900
2       81317068 (77.55MiB)     800
3       81317068 (77.55MiB)     700
4       81317068 (77.55MiB)     600
5       81317068 (77.55MiB)     581
6       91697971 (87.45MiB)     685
7       102078873 (97.35MiB)    818
8       102078873 (97.35MiB)    912
9       112459776 (107.25MiB)   1000
10      112459776 (107.25MiB)   1001
11      122840678 (117.15MiB)   940
12      122840678 (117.15MiB)   933
13      122840678 (117.15MiB)   958

Trace completed.
Process exited with code '137'.
```
8. Finally, checkout the branch from PR https://github.com/dotnet/runtime/pull/64128 and repeat steps 6-7. The application finishes successfully and `MemoryLoadBytes` is accurate:

```
Seconds MemoryLoadBytes         cache.Count
1       115920076 (110.55MiB)   900
2       115920076 (110.55MiB)   800
3       115920076 (110.55MiB)   700
4       115920076 (110.55MiB)   600
5       115920076 (110.55MiB)   571
6       126300979 (120.45MiB)   680
7       126300979 (120.45MiB)   790
8       134951731 (128.7MiB)    905
9       145332633 (138.6MiB)    1003
10      145332633 (138.6MiB)    1008
11      164364288 (156.75MiB)   956
12      164364288 (156.75MiB)   950
13      155713536 (148.5MiB)    974
14      155713536 (148.5MiB)    1045
15      150523084 (143.55MiB)   1134
16      152253235 (145.2MiB)    1192
17      152253235 (145.2MiB)    1232
18      164364288 (156.75MiB)   1255
19      164364288 (156.75MiB)   1258
20      164364288 (156.75MiB)   1270
Finished successfully!

Trace completed.
Process exited with code '0'.
```
From the output and the generated `gc.nettrace` file in `[runtime repository root]/artifacts` for the second run we can confirm that there was a full blocking collection due to low memory, which allowed the application to keep executing without hitting the memory limit.

### Expected behavior

The application finishes successfully and doesn't get OOM-killed.

### Actual behavior

The application gets OOM-killed.

### Regression?

Not a regression.

### Known Workarounds

Playing with `GCHighMemPercent` or similar settings can provide a short-term workaround in some cases.

### Configuration

.NET 5/6 running in Linux container on Docker or Kubernetes.

**Comment by mangod9** [comment]
yeah we can look into this. @janvorli @Maoni0 FYI

**Comment by dennis-yemelyanov** [comment]
thank you, @mangod9 . @janvorli , @Maoni0 , do you have any thoughts on this?

I also added a minimal repro app that gets killed in a container due to this issue and a small PR that fixes it

**Comment by tmds** [comment]
The memory heap limit should be enough to stop an app like this from going OOM.

The early versions of .NET Core relied on the cgroup usage to trigger GCs. That changed when the heap limit was introduced, and the managed heap is allocated 75% of container memory.

When the container gets allocated a low amount of memory, then the remaining 25% may not be enough for the unmanaged memory. That is what is happening here.

The memory pressure becomes high, and cgroup usage starts trigger GCs. They are postponing the inevitable, because .NET will allow to allocate the up to the size of the managed heap, and these GCs are not triggered deterministically.

For this app, you should either decrease the size of the managed heap, or increase container memory.

That said, the usage calculation can be improved so we can postpone the inevitable longer.

**Comment by dennis-yemelyanov** [comment]
It doesn't look like reducing the heap size would help much in this case, since near them time when the app gets OOM-killed, the heap size is less than half of the container memory (about 80MiB out of 165MiB):

```
Seconds MemoryLoadBytes         HeapSizeBytes           cache.Count
1       88237670 (84.15MiB)     42572584 (40.6MiB)      900
2       88237670 (84.15MiB)     42572584 (40.6MiB)      800
3       88237670 (84.15MiB)     42572584 (40.6MiB)      700
4       88237670 (84.15MiB)     42572584 (40.6MiB)      600
5       88237670 (84.15MiB)     42572584 (40.6MiB)      568
6       98618572 (94.05MiB)     52860344 (50.41MiB)     690
7       98618572 (94.05MiB)     52860344 (50.41MiB)     774
8       108999475 (103.95MiB)   63382968 (60.45MiB)     869
9       112459776 (107.25MiB)   73905976 (70.48MiB)     976
10      112459776 (107.25MiB)   73905976 (70.48MiB)     1002
11      124570828 (118.8MiB)    84428600 (80.52MiB)     953
12      124570828 (118.8MiB)    84428600 (80.52MiB)     925
13      124570828 (118.8MiB)    84428600 (80.52MiB)     955

Trace completed.
Process exited with code '137'.
```

The issue is that there are other kinds of physical memory that are not accounted for with the current calculation. After applying the fix from the PR, `MemoryLoadBytes` returns correct memory usage and a compacting GC is triggered because the system is under memory pressure (as we can confirm from GC traces), even though the heap size is not even close to 75% of container memory:

```
Seconds MemoryLoadBytes         HeapSizeBytes           cache.Count
1       117650227 (112.2MiB)    42538552 (40.57MiB)     900
2       117650227 (112.2MiB)    42538552 (40.57MiB)     800
3       117650227 (112.2MiB)    42538552 (40.57MiB)     700
4       117650227 (112.2MiB)    42538552 (40.57MiB)     600
5       117650227 (112.2MiB)    42538552 (40.57MiB)     563
6       128031129 (122.1MiB)    52876728 (50.43MiB)     669
7       128031129 (122.1MiB)    52876728 (50.43MiB)     774
8       138412032 (132MiB)      63399352 (60.46MiB)     886
9       148792934 (141.9MiB)    73921976 (70.5MiB)      983
10      148792934 (141.9MiB)    73921976 (70.5MiB)      1004
11      166094438 (158.4MiB)    41023872 (39.12MiB)     945
12      166094438 (158.4MiB)    41023872 (39.12MiB)     921
13      166094438 (158.4MiB)    41023872 (39.12MiB)     946
14      159173836 (151.8MiB)    51513680 (49.13MiB)     1008
15      153983385 (146.85MiB)   62019920 (59.15MiB)     1094
16      153983385 (146.85MiB)   62019920 (59.15MiB)     1169
17      157443686 (150.15MiB)   71380152 (68.07MiB)     1207
18      157443686 (150.15MiB)   71380152 (68.07MiB)     1204
19      166094438 (158.4MiB)    50333384 (48MiB)        1219
20      166094438 (158.4MiB)    50333384 (48MiB)        1224
Finished successfully!

Trace completed.
```
Note: this specific test application keeps allocating memory forever (adds new items to the cache at a faster rate than old items are removed), so, if run for longer than 20 seconds, at some point it will hit the limit of any memory size no matter what. This was done for simplicity purposes and to make the code smaller and easier to understand, while still demonstrating the main point - that current memory load calculation can lead to containers being OOM-killed without a reason, which can be impactful for application user experience and hard to debug for application developers.

**Comment by tmds** [comment]
> It doesn't look like reducing the heap size would help much in this case

It should help at some point, right? The GC will kick in to keep the managed heap size below the limit.

> this specific test application keeps allocating memory forever (adds new items to the cache at a faster rate than old items are removed), so, if run for longer than 20 seconds, at some point it will hit the limit of any memory size no matter what.

Rather than getting OOM killed, the app should throw OOM-exception when it depletes the managed heap.

> that current memory load calculation can lead to containers being OOM-killed without a reason

GCs based on cgroup usage brings risk of getting killed without a reason.
The heap limit is how you avoid that.

**Comment by dennis-yemelyanov** [comment]
> It should help at some point, right? The GC will kick in to keep the managed heap size below the limit.

I think there are (at least) 2 reasons for a GC to happen:
1. Because of reaching high heap size and approaching heap size limits.
2. Because of reaching high physical memory threshold (by default, I believe it's 90% of container physical memory).

In this case we are not hitting case 1, because the heap is relatively small. But the physical memory load is actually high, so ideally we should hit case 2. But it's not happening because current calculation of memory load in .NET returns a lower value. For example, Docker thinks that memory load of this container is 95%, but .NET thinks it's only 71%. So the GC is not happening, causing Docker to eventually kill the container when it reaches 100%.

> Rather than getting OOM killed, the app should throw OOM-exception when it depletes the managed heap.

Yes, my point was that it will eventually run out of memory because it's "leaking" memory, just to make the code smaller and simpler.

**Comment by tmds** [comment]
> In this case we are not hitting case 1, because the heap is relatively small. But the physical memory load is actually high, so ideally we should hit case 2. But it's not happening because current calculation of memory load in .NET returns a lower value. For example, Docker thinks that memory load of this container is 95%, but .NET thinks it's only 71%. So the GC is not happening, causing Docker to eventually kill the container when it reaches 100%.

Yes, and we prefer 1 to happen over 2.

To do that, we can configure the heap limit to a lower value, or increase the container memory.

**Comment by dennis-yemelyanov** [comment]
Yes, I agree that in the case of this test application setting the heap limit to 50% could probably "work" (in a sense that GC will be triggered), although that would also mean a lot of memory that could potentially be used for the heap could be wasted (assuming the "other" memory usage is not constant and can become lower or higher sometimes). And if the mechanism used by case 2 works as expected, we don't need to do any of these additional actions.

So I guess the question is if we can fix the mechanism used by case 2, which currently doesn't work properly (even if it's not the preferred one, if it exists... will probably be better if it actually works 🙂)

**Comment by tmds** [comment]
> in the case of this test application

It's for any app.

> if the mechanism used by case 2 works as expected, we don't need to do any of these additional actions.

2 doesn't work deterministically, that's why the heap limit was introduced.

> if we can fix the mechanism used by case 2

We can improve it.
