### ISSUE TITLE
RuntimeInformation.OSArchitecture Property is incorrect on Apple M1 chip

### ISSUE THREAD

**Issue by blair55** [dotnet/runtime#63865]
### Description

A simple dotnet program prints the value of [`RuntimeInformation.OSArchitecture`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.osarchitecture?view=netstandard-2.0).

The program is built and run on an Apple M1 chip (ARM64). However, the output is `Architecture.X64` (and not `Architecture.Arm64`).

![image](https://user-images.githubusercontent.com/702272/149717201-eaf3d9a9-b3c9-48d1-b5a0-b14040b7be76.png)

### Reproduction Steps

Build & run using an Apple M1 chip.

```csharp
using System;
using System.Runtime.InteropServices;

namespace ArchitectureTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"{RuntimeInformation.OSArchitecture}");
        }
    }
}
```

### Expected behavior

```bash
$ dotnet run
Arm64
```

### Actual behavior

```bash
$ dotnet run
X64
```

### Configuration

```bash
$ dotnet --version
5.0.402

$ uname -m
arm64

$ uname -a
Darwin xxxx.lan 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

**Comment by En3Tho** [comment]
.Net 5 doesn't have a native support for arm64, it works via Rosetta emulation of x64, hence the information you see. Try it with .Net 6.

**Comment by EgorBo** [comment]
Exactly, it prints Arm64 with .NET 6
