### ISSUE TITLE
SSL connection could not be established on Darwin 20.6.0 with legacy HTTP handler

### ISSUE THREAD

**Issue by DaniilShmelev** [dotnet/runtime#63873]
### Description

We're trying to configure the Azure Pipelines agent on Darwin 20.6.0 with .net 3.1.
We tried to use SocketsHttpHandler, but it fails on .net 3.1 (known issue: https://github.com/dotnet/runtime/issues/58814).

When we switched to the legacy HTTP handler, we've got this error: `System.PlatformNotSupportedException: The handler does not support custom handling of certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler.`

Is this functionality unavailable on Darwin? Is there anything we can do other than switch to a newer version of .net?

### Reproduction Steps

Configure azure pipelines agent on Darwin 20.6.0

### Expected behavior

SSL connection is established

### Actual behavior

`System.PlatformNotSupportedException: The handler does not support custom handling of certificates on this operating system. Consider using System.Net.Http.SocketsHttpHandler.`

### Configuration

.NET 3.1
Darwin 20.6.0
x64
Using Legacy HTTP handler seems to work on other systems

**Comment by wfurt** [comment]
That depends if the platform handler links with curl linked with OpenSSL or the libressl. If you can get curl (`curl --version`) built agains OpenSSL the callback  _should_  work. 
I don't know your situation, but jumping to 6.0 and using SocketsHttpHandler would be probably better bet. The Auth issue should be all fixed as far as we know and we can give better support if something shows up.
