### ISSUE TITLE
Marshal does not blit structure-typed return values from calls to WASM native dependencies

### ISSUE THREAD

**Issue by DouglasDwyer** [dotnet/runtime#63879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This problem occurs when calling a C function included in a Blazor project via [NativeFileReference](https://docs.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-6.0). If the `extern` function is declared in C# as returning a structure, then the structure returned will always have `default` values. If the method instead returns a primitive type or enum, then the correct value is returned.

The marshaller does not seem to be correctly blitting structure types across the native-managed boundary. This issue occurs both using Mono and compiling in release mode with AOT, and occurs when targeting .NET 6.

### Expected Behavior

When an `extern` call is made to a C function that returns a structure, the results of that function are correctly returned to C#.

### Steps To Reproduce

Please see [this ](https://github.com/DouglasDwyer/BlazorStructureBlitting)repository for a brief example of the troublesome behavior.

To reproduce, define a C method that returns a non-zero integer and include it as a `NativeFileReference`. Then, call the method from C#, with the `extern` declaration returning either an integer or a struct that contains an integer. The former will return the correct non-zero integer, but the latter will return an uninitialized struct with the integer equal to zero.

### .NET Version

.NET 6.0

**Comment by DouglasDwyer** [comment]
In addition, I have discovered that the marshaller does not appear to correctly blit struct-typed method parameters either. When a native method is called from C# with a structure as an argument, the native method does not receive the structure but rather a number representing a pointer to that structure on the WASM heap. This is true even for simple wrapper structs that can be marshalled as a primitive type, and adding `MarshalAs` attributes to the method arguments does not change the behavior.
This is very troublesome, because it makes using native wrappers for technologies like WebGL quite difficult. I have updated the sample repository to include these additional examples - please let me know if I should open another issue for this.

**Comment by lewing** [comment]
@maraf @radical was this fixed with pinvoke changes?

**Comment by maraf** [comment]
It shoud be resolved by https://github.com/dotnet/runtime/pull/73310

The assembly needs 

```csharp
[assembly: DisableRuntimeMarshalling]
```
