### ISSUE TITLE
Add a JsonConverter.Type property.

### ISSUE THREAD

**Issue by bobbyangers** [dotnet/runtime#63898]
**EDIT** see https://github.com/dotnet/runtime/issues/63898#issuecomment-1553486766 for an API proposal

<details><summary>Original Proposal</summary>
<p>

### Description

` internal sealed override Type TypeToConvert => typeof(T);`

Error	CS0122	'JsonConverter<T>.TypeToConvert' is inaccessible due to its protection level	CustomJsonStringEnumConverter.cs	

### Reproduction Steps

```
public class MyConverter : JsonConverter<T>

     private void SomeLogic()
     {
            this.TypeToCovert ///Do Something
     }
```

### Expected behavior

 This property should be accessible to derived classes

` protected internal sealed override Type TypeToConvert => typeof(T);`

### Actual behavior

Error	CS0122	'JsonConverter<T>.TypeToConvert' is inaccessible due to its protection level	CustomJsonStringEnumConverter.cs	

### Known Workarounds

Define my own copy of the method in the derived class.

</p>
</details>

**Comment by huoyaoyuan** [comment]
Why do you need to access the method?

**Comment by bobbyangers** [comment]
when derivind a class, some logic is based on that information.

Just need to read the prop.

**Comment by huoyaoyuan** [comment]
In derived class, you should have enough access to the type argument provided. Accessing `typeof(T)` shouldn't be wrong.

**Comment by bobbyangers** [comment]
Yes you are right, but duplicated logic can and should be avoided.
If the property is made portected internal (on the get), then all is good.

**Comment by huoyaoyuan** [comment]
I don't think the property is really "logic". It should be an architectural helper since the non-generic base class has no access with type argument.

**Comment by bobbyangers** [comment]
Hi @huoyaoyuan.  
I hear and get what you say.  If you allow me to rephrase,  **duplicate code and/or logic** should be avoided.

Currently if a user wants to derive a class from `JsonConvert<T>` and want's to access the `typeof(T)` he can do it by simply copying that property into your class. But that is considered copied/duplicate code.    

My suggestion what to simply expose that property so that derived classes would have access to it. and avoid the developers from having to having to copy the code (which is what I had to do).  If it's useful in the base class.... why could it not be useful in the derived class?

Of course there is a workaround, but I just thought I would point it out.

This library is slowly making it's way into mainstream, and maybe `JsonCovert<T>` not being used a lot at the moment;  

I use `Netwonsoft.Json` and migrating code to `Json.Text.Json`;  and this was one of the thing I encountered trying to migrate code;

But again there is an simple workaround, in principle, duplicating code and/or logic should be avoided, that is all.

**Comment by huoyaoyuan** [comment]
> why could it not be useful in the derived class?

Because it is `sealed override`, means it always equals to `typeof(T)`. You should not copy this property since you can always get the actual body. Just use `typeof(T)`.

> I use `Netwonsoft.Json` and migrating code to `Json.Text.Json`; and this was one of the thing I encountered trying to migrate code;

You'd better provide a sample to demonstrate how you would use the property if accessible.

**Comment by eiriktsarpalis** [comment]
I think it's a useful addition, for example somebody might want to index untyped `JsonConverter` instances by type. @bobbyangers would it be possible to modify your original post to follow the [API proposal template](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps)?

**Comment by huoyaoyuan** [comment]
> for example somebody might want to index untyped `JsonConverter` instances by type.

The it's required to be `public`. Being readable from **inherited** type provide totally no sense since it can always get it in a *more convenient* way.

**Comment by bobbyangers** [comment]
Hi @huoyaoyuan,

The property is set as `internal`, why ?   it's because it's being used by derived classes in that module.  Or else it's would be `private`

When deriving custom classes from `JsonConvert<T>` , that are outisde the scope of `internal`;  same use case.

You seem to think otherwise, let's leave it at that.

**Comment by eiriktsarpalis** [comment]
>> for example somebody might want to index untyped JsonConverter instances by type.
>
> The it's required to be public. Being readable from inherited type provide totally no sense since it can always get it in a more convenient way.

Yes I think it should be public. I don't think there is much benefit from marking it protected since you almost always inherit from the typed `JsonConverter<T>`. One possible issue however is how such a property could interfere with `JsonConverterFactory` types.

**Comment by eiriktsarpalis** [comment]
Upon further consideration, I don't think we should expose `JsonConverter.TypeToConverter`, precisely because it would have undefined behavior in `JsonConverterFactory` instances. On the other hand, it is not needed for `JsonConverter<T>` since it's just `typeof(T)`.

**Comment by robert-stratecglobal** [comment]
That is a strange conclusion; since as you say.. it’s just a typeof, furthermore, the developer eho whishes to create a derivative should be responsible enough,as with any other case, test and prevent the “possible” undefined behaviors.

But I guess that is your call!

**Comment by eiriktsarpalis** [comment]
@robert-stratecglobal what should be the value of `TypeToConvert` for something like [`JsonStringEnumConverter`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenumconverter?view=net-6.0)?

**Comment by eiriktsarpalis** [comment]
On second

**Comment by eiriktsarpalis** [comment]
I think we could contemplate a design where the property is nullable. This should cover the case of `JsonConverterFactory`:
```C#
public class JsonConverter
{
    public Type? Type { get; }
}
```

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
public abstract class JsonConverter
{
     internal JsonConverter() { }
+    public abstract Type? Type { get; }
}

public abstract class JsonConverter<T> : JsonConverter
{
+    public sealed override Type Type => typeof(T);
}

public abstract class JsonConverterFactory : JsonConverter
{
+    public sealed override Type? Type => null;
}
```

**Comment by eerhardt** [comment]
I missed the API review, but I had this question:

```C#
public abstract class JsonConverterFactory : JsonConverter
{
+    public sealed override Type? Type => null;
}
```

Because this is `sealed override`, derived classes can't override it. If I have a class derived from JsonConverterFactory, is there no scenario where I'd want to return a `Type` from it? For example, the new `JsonStringEnumConverter<TEnum>`, wouldn't I want to `return typeof(TEnum)` in it?

**Comment by eiriktsarpalis** [comment]
The property is meant as a proxy for the `T` in `JsonConverter<T>`, which is the only converter type that can be used when serializing values. Even though `JsonStringEnumConverter<TEnum>` technically creates converters for a single type, `Type => typeof(TEnum)` should only be returned by the converter that it produces, not itself. JsonConverterFactories can indicate what types they support using the `CanConvert` method.
