### ISSUE TITLE
Wrong Path returned by DirectoryInfo.FullName

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/runtime#63892]
### Description
I have an application which contains the following code line:
```csharp
string foo = new DirectoryInfo("c:").FullName;
```
The string `"c:"` is user-provided and may be a longer path. If the user passes a path consisting _only_ of the drive label and the colon (while omitting the finishing forward or backward slash) _and_ the drive is the one matching the drive of the current execution directory, then the execution directory is returned instead of the root drive.

### Reproduction Steps
1. Use a machine with multiple drives (if you do not have any explorer-mapped devices/drives, you may use the `subst` cmd command.
2. Create the following program:
```csharp
using System.IO;
using System;


Console.WriteLine("current dir: " + Directory.GetCurrentDirectory());

foreach (string path in new[] {
    "d:",
    "d:/",
    "d:\\",
    "c:",
    "c:/",
    "c:\\",
})
    Console.WriteLine($"    {path,5}  --->  {new DirectoryInfo(path).FullName}");
```
4. compile it with `net6.0-windows`. I use the following version:
```cmd
C:\> dotnet --list-sdks
3.1.416 [C:\Program Files\dotnet\sdk]
6.0.200-preview.21617.4 [C:\Program Files\dotnet\sdk]
```
3. Run it on the main system drive (i.e. `c:/`).

### Expected output
```
current dir: C:\Users\xxxxx\Documents\TestProject1\bin
       d:  --->  D:\
      d:/  --->  d:\
      d:\  --->  d:\
       c:  --->  C:\
      c:/  --->  c:\
      c:\  --->  c:\
```

### Actual output
```
current dir: C:\Users\xxxxx\Documents\TestProject1\bin
       d:  --->  D:\
      d:/  --->  d:\
      d:\  --->  d:\
       c:  --->  C:\Users\xxxxx\Documents\TestProject1\bin
      c:/  --->  c:\
      c:\  --->  c:\
```

### Regression?
I do not think that this bug occured in a previous version.

### Known Workarounds
I could check whether the path exactly matches `^[a-z]:$` and append a `/` if that is the case.

### Configuration
I am using .NET `6.0.200-preview.21617.4` on Windows 11 Pro 64Bit:

![image](https://user-images.githubusercontent.com/8807985/149808266-9fb98cc2-f405-4f89-a754-30ddca7cfc38.png)

**Comment by danmoseley** [comment]
Hello @Unknown6656 this seems to be original behavior:
```
C:\proj\9>dotnet run -f net6.0
current dir: C:\proj\9
       d:  --->  D:\
      d:/  --->  d:\
      d:\  --->  d:\
       c:  --->  C:\proj\9
      c:/  --->  c:\
      c:\  --->  c:\

C:\proj\9>dotnet run -f net48
current dir: C:\proj\9
       d:  --->  D:\
      d:/  --->  d:\
      d:\  --->  d:\
       c:  --->  C:\proj\9
      c:/  --->  c:\
      c:\  --->  c:\
```
On Windows, "X:" means "current directory on the X drive". Our implementation ultimately calls [GetFullPathName](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew) which gives the example "If you specify "U:" the path returned is the current directory on the "U:\" drive".

If you want the behavior you describe, your workaround sounds like a good one.

thanks for opening the issue!

**Comment by Unknown6656** [comment]
Hello @danmoseley,
Thank you for replying so quickly. I was not aware that this behaviour was intended. Thanks for taking your time in order to clear up the issue. I must admit that the behaviour of resolving "x:" to the current path is a bit off-putting, but thanks anyways!
