### ISSUE TITLE
System.Linq support Deconstruct for IGrouping

### ISSUE THREAD

**Issue by bugproof** [dotnet/runtime#63919]
https://github.com/dotnet/runtime/issues/19397 <- this was closed but Deconstruct for IGrouping was not added.

![image](https://user-images.githubusercontent.com/3116731/149900609-a6c4ae46-c0ce-4189-a20f-1e9a8e236ebd.png)

**Comment by KalleOlaviNiemitalo** [comment]
Would the semantics be like this:

```C#
static void Deconstruct<TKey, TElement>(
    this IGrouping<TKey, TElement> grouping,
    out TKey key,
    out IEnumerable<TElement> elements)
{
    key = grouping.Key;
    elements = grouping;
}
```

The `elements = grouping` assignment would look somewhat strange for a Deconstruct method. That just converts to a base interface, doesn't really deconstruct.

**Comment by huoyaoyuan** [comment]
Since it's an extension method, we should decide where to place it. The linq `Enumerable` class is a choice, but currently all its methods are extension method for `IEnuemrable`.

```csharp
namespace System.Collections.Generic
{
    public class Enumerable
    {
        static void Deconstruct<TKey, TElement>(
            this IGrouping<TKey, TElement> grouping,
            out TKey key,
            out IEnumerable<TElement> elements);
    }
}
```

**Comment by KalleOlaviNiemitalo** [comment]
Are there Deconstruct methods for any other types that implement IEnumerable\<T>?

**Comment by eiriktsarpalis** [comment]
What would be the benefit of adding such a deconstruct method? As already pointed out the second component is the grouping itself, so I'm not sure if avoiding an explicit call to `IGrouping.Key` provides sufficient justification.

**Comment by bugproof** [comment]
> What would be the benefit of adding such a deconstruct method? As already pointed out the second component is the grouping itself, so I'm not sure if avoiding an explicit call to `IGrouping.Key` provides sufficient justification.

It seems inconsistent with the rest of BCL. You can deconstruct Dictionary but you can't IGrouping.

**Comment by eiriktsarpalis** [comment]
You mean the `KeyValuePair` deconstructor? It's not exactly the same type though, KVP is essentially a tuple.

**Comment by eiriktsarpalis** [comment]
Closing, since I don't believe this meets the bar for inclusion. One workaround might be to roll your own deconstructor extension method.
