### ISSUE TITLE
CultureInfo NumberFormat.NegativeSign change from 3.1 to 6.0

### ISSUE THREAD

**Issue by Dzeneralen** [dotnet/runtime#63928]
Was surprised to see the different negative sign from 3.1 to 6.0 for the Norwegian culture. Looking up the unicode characters online I found 3.1 giving U+002D and 6.0 giving U+2212.

3.1 -> - character has code: 45
6.0 -> - character has code: 226

I am probably missing something, just not sure what. Any explanation?

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <!--<TargetFramework>netcoreapp3.1</TargetFramework>-->
	  <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

```cs
using System;
using System.Globalization;
using System.Text;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var culture = new CultureInfo("nb-NO", useUserOverride: false);
            var sign = culture.NumberFormat.NegativeSign;
            Console.WriteLine(String.Format("{0} character has code: {1}", sign, Encoding.UTF8.GetBytes(sign.ToString())[0].ToString()));
        }
    }
}

```

**Comment by huoyaoyuan** [comment]
In .NET 5, the source of culture data changed from Windows Nls to ICU. See https://docs.microsoft.com/dotnet/core/compatibility/globalization/5.0/icu-globalization-api

**Comment by huoyaoyuan** [comment]
If you feel ICU data is wrong, you can provide feedback at https://github.com/unicode-org/icu

**Comment by Dzeneralen** [comment]
That explains the behaviour. Thank you for your answer!
