### ISSUE TITLE
Process.GetProcessById claims killed process is still alive in .NET Core

### ISSUE THREAD

**Issue by bouchraRekhadda** [dotnet/runtime#63937]
### Description

`Process.GetProcessById` should throw an `ArgumentException` if the process isn't running, but it doesn't seem to be the case with .NET Core 3.1 as the method always returns previously killed process (please check repro below). 
Am I missing something ?

### Reproduction Steps

```C#
        [Test] public void TestKillProcess()
        {
            var p = new Process();
            p.StartInfo.FileName = "cmd.exe";
            p.Start();
            var pid = p.Id;
            p.Kill();
            Assert.Throws<ArgumentException>(() => Process.GetProcessById(pid));
        }
```

### Expected behavior

Test should pass as in .NET Framework 4.8

### Actual behavior

Test fails
![image](https://user-images.githubusercontent.com/14876573/149986564-298708a5-9a57-4385-9981-0d70d9eea023.png)

### Regression?

It works on .NET Framework 4.8.

### Configuration

- .NET Core 3.1
- Windows 10
- x64

**Comment by KalleOlaviNiemitalo** [comment]
This was also reported in <https://github.com/dotnet/runtime/issues/20725#issuecomment-390391489> and <https://github.com/PowerShell/PowerShell/issues/12880>. Both of those issues have been closed but AFAIK the bug still hasn't been fixed. You can work around the bug by checking [Process.HasExited](<https://docs.microsoft.com/dotnet/api/system.diagnostics.process.hasexited?view=netstandard-2.0> "Process.HasExited Property (System.Diagnostics) | Microsoft Docs").

**Comment by stephentoub** [comment]
Yeah, the ProcessManager.IsProcessRunning method should really be running the same logic that UpdateHasExited uses.  That logic can probably just be factored out into a helper used by both IsProcessRunning and UpdateHasExited.
