### ISSUE TITLE
Different behavior across .NET versions when testing objects for type of IntPtr / nint typed array

### ISSUE THREAD

**Issue by Washi1337** [dotnet/runtime#63933]
### Description

I am not sure if this is the right place to report this, whether this is a regression or a bug in older (but still supported) versions of .NET (Core / Framework). If this is not the right place, then please consider this issue as not reported, and if possible, tell me where to forward this instead.

It seems that the behavior of `IsInstanceOf` intrinsics (e.g. realized through the `is` operator in C#) changed in .NET 5.0+ for certain array typed objects. It seems that sometimes the runtime decides that certain array types are equal even though they are not. This happens in particular for `IntPtr[]` and `long[]` for 64-bit systems, and `IntPtr[]` and `int[]` on 32-bit systems. 

### Reproduction Steps

Compile and run the following snippet on a 64-bit system...

```csharp
IntPtr[] a = new IntPtr[1];
Console.WriteLine(a is long[]);
object b = a;
Console.WriteLine(b is long[]);
```

Using the following csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

</Project>
```

Vary the framework version to observe the differences.

### Expected behavior

I expect it to print `False` twice on all framework versions.

### Actual behavior

You will get the following outputs instead:

| .NET Version  | Output 1 | Output 2 |
|---------------|----------|----------|
| .NET 3.5       | `False`  | `True`   |
| .NET 4.7.1    | `False`  | `True`   |
| .NET Core 2.1 | `False`  | `True`   |
| .NET Core 3.1 | `False`  | `True`   |
| .NET 5.0      | `False`  | `False`  |
| .NET 6.0      | `False`  | `False`  |

A similar thing can be observed on a 32-bit system when we try to test for `int[]` instead.

### Regression?

As mentioned before, this could be a regression, intentional breaking change, or actually a bugfix in .NET 5. Regardless, I'd say this should be consistent across framework versions. Therefore, if it is the last case, then this might have to be fixed in older versions of .NET that are still supported and/or are in LTS (e.g. .NET Core 3.1 and .NET Framework 4.0).

The first line in the code is optimized away by the compiler to always print `False`. In the second line, it emits a call to `CORINFO_HELP_ISINSTANCEOFARRAY` or its equivalent, which seems to be calling `IsInstanceOfAny` on .NET 5+.

I did some digging into the history of the .NET repository and came across commit c3dc1fdfdcca9bf504a68be565b053c0372ac73c which seems to be present since 5.0.0 tags. Before this commit, implementations for `IsInstanceOf` helpers resided in unmanaged code instead. Maybe something went wrong (or got fixed?) during this translation?

### Configuration

- .NET SDK 6.0.100
- OS: Tested on Windows 11 64 bit

**Comment by MichalStrehovsky** [comment]
It affects all casting, not just `is`. I think it got broken here: https://github.com/dotnet/coreclr/pull/25209

**Comment by jkotas** [comment]
> Therefore, if it is the last case, then this might have to be fixed in older versions of .NET that are still supported and/or are in LTS 

We backport bug fixes to older releases only if they are high impact (e.g. security fixes, reliability bugs with no workaround, etc.). This does not look high impact.

**Comment by mangod9** [comment]
Closing unless there is an ask to backport here.
