### ISSUE TITLE
Installation of the .NET 5.0.13 Runtime changes a system information on macOS 12.1

### ISSUE THREAD

**Issue by Taritsyn** [dotnet/runtime#63938]
If the [.NET 6.0.101 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer) on macOS 12.1 (x64) is installed cleanly (without additional runtimes and other SDKs), then the `dotnet --info` command returns the following result:

![before-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149987692-03173e86-07a7-49e5-8716-65b20abae576.png)

If you install the [.NET 5.0.13 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.13-macos-x64-installer), then the `dotnet --info` will display a different version number of macOS:

![after-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149988513-ac5319e6-f541-4781-9971-457a9aa5460d.png)

Although the operating system itself has not undergone any changes:

![about-this-mac](https://user-images.githubusercontent.com/251859/149988939-1560f333-741b-47c5-af9a-2ce303562b02.png)

This issue also affects the working of some applications and libraries (see the [“.NET local tool that using the ClearScript.V8 library quietly crashes on macOS 12.1”](https://github.com/microsoft/ClearScript/issues/343) issue in the [ClearScript](https://github.com/microsoft/ClearScript) repository).

**Comment by NikolaMilosavljevic** [comment]
I think this information is coming from dotnet host. Are there any known issues with detection of current runtime environment in this scenario?

**Comment by vitek-karas** [comment]
The OS Version is not coming from the host at all:
https://github.com/dotnet/sdk/blob/ceaf2782831c4c9eb33b75f337053a7d4f3acf18/src/Cli/dotnet/CommandLineInfo.cs#L29
https://github.com/dotnet/sdk/blob/ceaf2782831c4c9eb33b75f337053a7d4f3acf18/src/Cli/Microsoft.DotNet.Cli.Utils/RuntimeEnvironment.cs#L67
https://github.com/dotnet/runtime/blob/6f8d8b20a0c78dcfc09ea7a43db48a9a4e055e13/src/libraries/System.Private.CoreLib/src/System/Environment.OSVersion.OSX.cs#L8

It seems to be a direct OS call.

The RID is coming from the host but it's checked against the supported RIDs by the current framework - if it's not supported (listed in the .deps.json for the NETCoreApp) it falls back to the RID the SDK was build against - which is written in the `.version` file in the main SDK directory.

**Comment by vitek-karas** [comment]
If you set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=host.txt` run `dotnet --info` and then search the `host.txt` for `RUNTIME_IDENTIFIER` that will show the RID the host has. Would be interesting to know if it's different from the one reported by `dotnet --info`.

**Comment by Taritsyn** [comment]
RIDs are not different:

![dotnet-host-diff](https://user-images.githubusercontent.com/251859/150357548-3d6afeb8-8f90-4009-b6fe-df9c208ba8aa.png)

 * [host-before-installation-dotnet-runtime-5.0.13.txt](https://github.com/dotnet/runtime/files/7905954/host-before-installation-dotnet-runtime-5.0.13.txt)
 * [host-after-installation-dotnet-runtime-5.0.13.txt](https://github.com/dotnet/runtime/files/7905956/host-after-installation-dotnet-runtime-5.0.13.txt)

**Comment by vitek-karas** [comment]
I think I can explain at least the RID difference. You're running .NET 5 `dotnet` executable. This didn't know about macOS 12 at all, see https://github.com/dotnet/runtime/pull/59066 which introduced support for this version.
Also based on the description in that PR, the OS is probably lying about its version to the .NET 5 executable, which would also explain the different version number for the `Environment.OSVersion`.

So I think if there is a bug, it should be that the installation of .NET 5 should not overwrite the `dotnet` executable from .NET 6. The `dotnet` is supposed to be the latest version available on the machine at all times.

@ericstj for the macOS installers - based on the above it seems the .NET 5 installer is overwriting the `dotnet` exe from .NET 6?

**Comment by ericstj** [comment]
That's correct.  We discovered that elsewhere that the behavior of the macos installers is currently "last in wins" https://github.com/dotnet/runtime/issues/61526

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/61526
