### ISSUE TITLE
Use different calender and format info for DateTime.ToString() and DateTime.Parse()

### ISSUE THREAD

**Issue by rezathecoder** [dotnet/runtime#63939]
I use globalization and localization in my Asp.Net Core app and i want to use `PersianCalendar` when requested culture is set to 'fa-IR'.

This needs to happen whenever a `DateTime.ToString()` happens. I want it to be converted to persian date automatically and i don't want to change the code that is calling `ToString()` method (because other cultures still needs to see gregorian calendar).

The request localization works fine and` CultureInfo.CurrentCulture` is correclty set to 'fa-IR' but the default calendar for 'fa-IR' culture is `GregorianCalendar`.

So i created a subclass of CultureInfo like this:
```C#
public class PersianCulture : CultureInfo
{
    private readonly Calendar _calendar;
    private readonly Calendar[] _optionalCalendars;
    private DateTimeFormatInfo _dateTimeFormatInfo;

    public PersianCulture() : base("fa-IR") {
        _calendar = new PersianCalendar();

        _optionalCalendars = new List<Calendar>
        {
            new PersianCalendar(),
            new GregorianCalendar()
        }.ToArray();

        var dateTimeFormatInfo = CultureInfo.CreateSpecificCulture("fa-IR").DateTimeFormat;
        dateTimeFormatInfo.Calendar = _calendar;
        _dateTimeFormatInfo = dateTimeFormatInfo;
    }

    public override Calendar Calendar => _calendar;

    public override Calendar[] OptionalCalendars => _optionalCalendars;

    public override DateTimeFormatInfo DateTimeFormat {
        get => _dateTimeFormatInfo;
        set => _dateTimeFormatInfo = value;
    }
}
```
Then i added a middleware that checks if requested culture is 'fa-IR' then sets the `CurrentCulture` to `PersianCulture` as follows:
```C#
if ( CultureInfo.CurrentCulture.Name == "fa-IR" ) {
        var culture = new PersianCulture();
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
   }
```

And i get the expected result. Whenever a `someDate.ToString()` is called the output is converted to persian date. For exapmle `DateTime.Now.ToString()` will output `16/10/1400 02:53:40 ب.ظ`.

The problem is that the same `Calendar` and `DateTimeFormatInfo` is used whenever a `DateTime.Parse()` happens and the parsed date will be wrong because the source is in gregorian format but treated as persian.

How can i use my custom `PersianCulture` class for converting to string and use C# default's 'fa-IR' calendar for parsing dates?

If there is no way right now implementing it seems to require following changes:
1.Add two different `Calendar` and  `DateFormatInfo` to `CultureInfo` class. One used for parsing and one used for converting to string
2.Change `Parse` and `ToString` methods to use appropriate properties

**Comment by Clockwork-Muse** [comment]
> How can i use my custom PersianCulture class for converting to string and use C# default's 'fa-IR' calendar for parsing dates?

Be explicit about the culture used for parsing/formatting.  That is, don't use bare `ToString()`, use [`DateTime.ToString(IFormatProvider)`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?view=net-6.0#system-datetime-tostring(system-iformatprovider)).
I personally recommend doing this for **all** values that you want localized; don't depend on the implicit culture context.  For one thing, making it explicit makes it easier to test.  For another, it makes it so you can output **both** "localized" values (Persian and Gregorian).

> For exapmle `DateTime.Now.ToString()`

Calling `DateTime.Now` in a server context is (almost) always a bug - you should be getting UTC time (ie, `DateTime.UtcNow`) and being explicit about the destination timezone.

> If there is no way right now implementing it seems to require following changes:

Your underlying problem is that you're dealing with two different cultures, with two different calendars, and this probably isn't an appropriate way to handle it.

**Comment by tarekgh** [comment]
> The request localization works fine and CultureInfo.CurrentCulture is correclty set to 'fa-IR' but the default calendar for 'fa-IR' culture is GregorianCalendar.

Which version of .NET you are using? in .NET 5.0 and 6.0 you should have the PersianCalendar as the default calendar for `fa-IR`.

> So i created a subclass of CultureInfo like this:

You don't need to do that. you can have a code like:

```C#
            if (CultureInfo.CurrentCulture.Name == "fa-IR")
            {
                CultureInfo ci = CultureInfo.CurrentCulture;

                if (ci.IsReadOnly && ci.DateTimeFormat.Calendar is not PersianCalendar)
                {
                    ci = (CultureInfo) ci.Clone();
                    ci.DateTimeFormat.Calendar = new PersianCalendar();
                    CultureInfo.CurrentCulture = ci;
                }
            }
```

> How can i use my custom PersianCulture class for converting to string and use C# default's 'fa-IR' calendar for parsing dates?

@Clockwork-Muse already answered that. It is not right to have one current culture that can format a date with a specific calendar and parse the date with another calendar. Imagine some other code not owned by you using the current culture, you can break many different other scenarios. 

> If there is no way right now implementing it seems to require following changes:

@Clockwork-Muse replied that too. 

You need just pass the right culture to the DateTime.ToString and DateTime.Parse and not try to just handle everything through the current culture. As I mentioned this can break other code depend on the current culture. The other idea would be, provide a wrapper method for DateTime.ToString and DateTime.Parse and apply whatever logic you want there. Then have your code just call such wrapper method. 

By that, I am closing this issue. Feel free to reply back if you have any more questions.
