### ISSUE TITLE
ILVerify complains about unbox; ldfld 

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#63953]
### Description

ILVerify unnecessarily complains about `unbox Veri.S` followed by `ldfld object Veri.S::T`, where `Veri.S` is a value type.

### Reproduction Steps

Veri.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

Veri.cs:

```C#
namespace Veri;

struct S
{
  public object T;
}

class Class1
{
   static object M1() => new S();
   static object M2() => ((S)M1()).T;
}
```

.config/dotnet-tools.json:

```JSON
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-ilverify": {
      "version": "6.0.0",
      "commands": [
        "ilverify"
      ]
    }
  }
}
```

`dotnet build`

`dotnet tool run ilverify -- .\bin\Debug\net6.0\Veri.dll --system-module System.Private.CoreLib --reference "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\*.dll"`

### Expected behavior

No error.

### Actual behavior

[IL]: Error [StackUnexpected]: [C:\Projects\Kalle\Veri\bin\Debug\net6.0\Veri.dll : Veri.Class1::M2()][offset 0x0000000A][found readonly address of '[Veri]Veri.S'][expected address of '[Veri]Veri.S'] Unexpected type on the stack.
1 Error(s) Verifying C:\Projects\Kalle\Veri\bin\Debug\net6.0\Veri.dll

### Known Workarounds

See [comment](https://github.com/dotnet/runtime/issues/63953#issuecomment-1016300734).

### Configuration

.NET SDK 6.0.101 targeting .NET 6.0 on Windows 10.0.19044.1466 x64.

### Other information

IL disassembly:

```
.method private hidebysig static object  M2() cil managed
{
  // Code size       16 (0x10)
  .maxstack  8
  IL_0000:  call       object Veri.Class1::M1()
  IL_0005:  unbox      Veri.S
  IL_000a:  ldfld      object Veri.S::T
  IL_000f:  ret
} // end of method Class1::M2
```

**Comment by KalleOlaviNiemitalo** [comment]
Why does ILVerify even mention `address of '[Veri]Veri.S'`? AFAIK, after `unbox`, the value itself should be on the stack, not an address.

**Comment by jkotas** [comment]
> after unbox, the value itself should be on the stack, not an address.

From ECMA-335: The unbox instruction converts obj (of type O), the boxed representation of a value type, to
valueTypePtr (a controlled-mutability managed pointer (§III.1.8.1.2.2), type &).

You may be confusing it with `unbox.any`

**Comment by KalleOlaviNiemitalo** [comment]
It seems I can work around this by making my app examine the VerificationResult object and recognize the false positive:

- VerificationResult.Code is VerifierError.StackUnexpected
- "Offset" parameter is an integer
- "Expected" parameter starts with "address of"
- "Found" parameter is "readonly " + value of "Expected" parameter
- get MethodDefinition from MetadataReader using VerificationResult.Method
- get MethodBodyBlock from PEReaderExtensions using MethodDefinition.RelativeVirtualAddress
- get BlobReader from MethodBodyBlock
- seek to the value of the "Offset" parameter
- read the opcode and check whether it is System.Reflection.Emit.OpCodes.Ldfld.Value.

I don't know whether the bug can occur with opcodes other than `ldfld`, but that's the only one that I hit with my assemblies.

**Comment by jkotas** [comment]
If you would like to try the fix before it gets officially released, you can use nightly feed: https://github.com/dotnet/runtime/issues/63221#issuecomment-1008213797 . The package with the fix should be there in a day or so.

**Comment by KalleOlaviNiemitalo** [comment]
Thanks; Microsoft.ILVerification/7.0.0-preview.1.22071.6 no longer complains about ldfld. However, I can't start using ILVerify for real before <https://github.com/dotnet/runtime/issues/63999> or <https://github.com/dotnet/runtime/issues/37391> is addressed.
