### ISSUE TITLE
[API Proposal]: MetadataReader.GetAssemblyName(string assemblyFile)

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#63960]
### Background and motivation

As part of https://github.com/dotnet/runtime/pull/63915 we are moving `AssemblyName.GetAssemblyName(string assemblyFile)` implementation to managed code, so we need a helper entry point in `System.Reflection.Metadata`.

Current implementation relies on VM assembly loader, but intentionally bypasses the internal caches so that the call has no lasting effects on the runtime state. 
The implementation also needs to handle assemblies that do not match the current platform, which is an awkward situation for the assembly loader and require special handling. 
As it is, every runtime (CoreClr, Mono, CoreRT) needs to implement `AssemblyName.GetAssemblyName` leading to inconsistencies in implementation. Providing a common managed implementation is very desirable.

Since this is all about PE/Assembly parsing, `System.Reflection.Metadata` appears to be a logical place for the implementation.

While internal helper could be sufficient, it is better if the helper is public. In fact the helper may become the primary/recommended way to fetch an assembly name.

### API Proposal

```diff
namespace System.Reflection.Metadata
{
   public sealed partial class MetadataReader
    {
        // given a path to assembly returns its AssemblyName similarly to AssemblyName.GetAssemblyName
        // in fact AssemblyName.GetAssemblyName will use this implementation.
+       public static AssemblyName GetAssemblyName(string assemblyFile) { ... }
    }
}
```

== Exceptions:
`AssemblyName.GetAssemblyName` handles failure cases by throwing a range of exceptions. It may be difficult to match every error case precisely. Inconsistencies in the file format typically lead to `BadImageFormatException`. 
There is less consistency for other issues like file/IO and there are some disagreements between platforms and different OSs.

== Proposal:
Map `InvalidOperationException` coming from MetadataReader to `BadImageFormatException` with the same message to minimize compat concerns. Propagate other exceptions as-is.

### API Usage

```C#
using System.Reflection.Metadata;

AssemblyName assemblyName = MetadataReader.GetAssemblyName("Hello.dll");
```

### Alternative Designs

It would be ok if the helper is internal, but measures will need to be taken that it is not trimmed by the linker and does not disappear in future/alternative implementations of `System.Reflection.Metadata`

### Risks

Low. This is a new API entry point exposing existing implementation.

**Comment by VSadov** [comment]
CC: @agocke

**Comment by buyaa-n** [comment]
Yest i was OK with the API shape/name because @VSadov moved the existing API implementation from `AssemblyName` into `MetadataReader`, and the new API naming just same as the one in `AssemblyName` https://github.com/dotnet/runtime/blob/cfd1241efc7ea54a00db848c6d00cd773ed6ae50/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L190
But I believe it is not have to be same as one in `AssemblyName`, so I am open for better naming suggestions

**Comment by terrajobst** [comment]
Personally, I think `assemblyFile` is fine, but so is `assemblyPath` or just `path`.

@dotnet/fxdc, any preferences?

**Comment by teo-tsirpanis** [comment]
What I can't understand is how this method would be called from corelib, if that's what you want to do. `System.Reflection.Metadata` is in a separate library, and a sizable one. Or do you want to obsolete `AssemblyName.GetAssemblyName` and direct developers to the new one?
