### ISSUE TITLE
[DependencyInjection] Not exactly a bug, but doesn't seem right - the same object is being disposed multiple times

### ISSUE THREAD

**Issue by dejancg** [dotnet/runtime#63967]
Consider the following code:

```cs
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Diagnostics;

namespace Test.ScopedDependencies
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();
            services.AddScoped<Interface1, ScopedDependency>();
            services.AddTransient<Interface2>(sp => (Interface2)sp.GetRequiredService<Interface1>());
            services.AddTransient<Interface3>(sp => (Interface3)sp.GetRequiredService<Interface1>());
            var sp = services.BuildServiceProvider();

            using var scope = sp.CreateScope();
            var scoped1 = scope.ServiceProvider.GetRequiredService<Interface1>();
            var scoped2 = scope.ServiceProvider.GetRequiredService<Interface2>();
            var scoped3 = scope.ServiceProvider.GetRequiredService<Interface3>();

            Debug.Assert(scoped1 == scoped2);
            Debug.Assert(scoped2 == scoped3);
        }
    }

    internal class ScopedDependency : Interface1, Interface2, Interface3, IDisposable
    {
        private bool disposed;

        private readonly string id;

        public ScopedDependency()
        {
            id = DateTime.UtcNow.ToString("ffffff");
        }

        public void Dispose()
        {
            if (disposed)
            {
                throw new Exception("Already disposed!");
            }

            Console.WriteLine($"Disposing {id}");
            disposed = true;
        }
    }

    internal interface Interface1 { }

    internal interface Interface2 { }

    internal interface Interface3 { }
}
```

Here, the exception is thrown because the `ScopedDependency` instance is being disposed three times - one for each registration.
Instead of `disposables` being a `List<object>`, is there a reason it's not `HashSet<object>` ? This would prevent `Dispose` being called multiple times on a same instance.

**Comment by eerhardt** [comment]
```C#
services.AddTransient<Interface2>(sp => (Interface2)sp.GetRequiredService<Interface1>());
```

If you are making a "transient" service, you should be creating a new instance for every time it is requested.

Check out https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#general-idisposable-guidelines for more information.

**Comment by dejancg** [comment]
Yes, but that's not the point. We could as well make all those registrations scoped:

```cs
            services.AddScoped<Interface1, ScopedDependency>();
            services.AddScoped<Interface2>(sp => (Interface2)sp.GetRequiredService<Interface1>());
            services.AddScoped<Interface3>(sp => (Interface3)sp.GetRequiredService<Interface1>());
```

 and it wouldn't change the fact that `Dispose` is being called multiple times even though it's the same instance.

**Comment by eerhardt** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

> To help ensure that resources are always cleaned up appropriately, a Dispose method should be idempotent, such that it is callable multiple times without throwing an exception. Furthermore, subsequent invocations of Dispose should do nothing.

Especially if you are returning the same instance for multiple different services.

**Comment by dejancg** [comment]
Yes - dispose is indeed always implemented as suggested by that link in all our projects, this is the reason why I stated this is not exactly a bug. I just noticed this while experimenting with something and it still leaves me with the question - is there a reason that `disposables` collection in there: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ServiceProviderEngineScope.cs#L17 can't be `HashSet<object>`? Because that would ensure the same object reference is only being disposed once. I mean, why would you choose to do several operations to accomplish one thing, when you could accomplish the same thing with only one operation?

**Comment by eerhardt** [comment]
HashSet has a lot more overhead than a List. If all the services implement IDisposable as documented, then calling Dispose multiple times on the same object (which is really an edge case) doesn't hurt anything.

Using a HashSet will slow down normal usages because every time it is added to, it needs to call GetHashCode and Equals to ensure the item isn't already added.

**Comment by dejancg** [comment]
Thank you for the clarification.
