### ISSUE TITLE
Mono assert hit when calling GetFunctionPointerForDelegate when delegate has Nullable<T> return type

### ISSUE THREAD

**Issue by bholmes** [dotnet/runtime#63962]
### Description

When attempting to get a function pointer for a managed method that returns `Nullable<T>` an assertion is hit and the program exits immediately.  This occurs only with the mono runtime.

### Reproduction Steps

Compile and run the program below using the mono runtime

``` csharp

using System;
using System.Runtime.InteropServices;

namespace HelloWorld
{
    internal class Program
    {
        private delegate Nullable<int> Foo();
        private Nullable<int> Bar()
        {
            return 0;
        }

        void TestMethod ()
        {
            var test = Marshal.GetFunctionPointerForDelegate<Foo>(Bar);
        }

        static void Main ()
        {
            new Program ().TestMethod();
        }
    }
}

```

### Expected behavior

Program execution completes without error.

### Actual behavior

Assertion is hit

```
return type 0x15 unknown
* Assertion: should not be reached at /home/bill/dev/runtime/src/mono/mono/metadata/marshal-ilgen.c:6358

.....

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.Runtime.InteropServices.Marshal:GetFunctionPointerForDelegateInternal <0x00083>
          at System.Runtime.InteropServices.Marshal:GetFunctionPointerForDelegate <0x00043>
          at System.Runtime.InteropServices.Marshal:GetFunctionPointerForDelegate <0x00057>
          at HelloWorld.Program:TestMethod <0x000bb>
          at HelloWorld.Program:Main <0x00047>
          at System.Object:runtime_invoke_void <0x00086>
=================================================================
```

### Regression?

Not a regression

### Configuration

Tested with .Net 7.0, mono runtime on Windows, Mac and Linux x64

**Comment by bholmes** [comment]
Personally I do not have a strong opinion of what this should return. I want to avoid the assert as our program needs to be able to recover from this scenario. 

.NetFramework throws a MarshalDirectiveException stating "Method's type signature is not PInvoke compatible." That would work fine. 

coreclr does return a value in this scenario, however it is unclear how the return value of the managed method is marshalled.

**Comment by marek-safar** [comment]
@jkoritzinsky do you know what it returns under coreclr?

**Comment by bholmes** [comment]
I did test this out with coerclr and it appears that an exception is raised when you attempt to invoke the function pointer.

`Unhandled exception. System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'return value': Non-blittable generic types cannot be marshaled.`

**Comment by jkoritzinsky** [comment]
Yeah this isn't supported in CoreCLR since `Nullable<T>` is never blittable
