### ISSUE TITLE
EventListener.OnEventSourceCreated invoked before constructor

### ISSUE THREAD

**Issue by epeshk** [dotnet/runtime#63979]
### Description

I'm trying to create `EventListener`'s child with some parameters in ctor, but for some reason ctor executed after `OnEventSourceCreated` method. So, uninitialized instance used inside `OnEventSourceCreated`. It works early and I noticed this behavior after ctor parameters change.

### Reproduction Steps
```
using System.Diagnostics.Tracing;

using (var listener = new MyListener(new object()))
{
    Console.WriteLine(listener._a == null);
}

class MyListener : EventListener
{
    public object _a;
    public MyListener(object a)
    {
        Console.WriteLine("ctor begin");
        _a = a;
        Console.WriteLine("ctor end");
    }

    protected override void OnEventSourceCreated(EventSource eventSource) => Console.WriteLine($"{eventSource.Name} {_a == null}");
}
```

### Expected behavior

```
ctor begin
ctor end
Microsoft-Windows-DotNETRuntime False
System.Runtime False
System.Buffers.ArrayPoolEventSource False
System.Threading.Tasks.TplEventSource False
System.Diagnostics.Eventing.FrameworkEventSource False
False
```

Constructor executes before `OnEventSourceCreated` and `_a` value is always True

### Actual behavior

```
Microsoft-Windows-DotNETRuntime True
System.Runtime True
System.Buffers.ArrayPoolEventSource True
System.Threading.Tasks.TplEventSource True
System.Diagnostics.Eventing.FrameworkEventSource True
ctor begin
ctor end
False
```

Constructor executes after `OnEventSourceCreated` and `_a` value is False inside `OnEventSourceCreated`

### Known Workarounds

Pass parameters to `EventListener`'s child via static fields before constructor invocation. Don't rely on instance fields which may be uninitialized.

### Configuration

.NET 6.0.1
Windows
x64

**Comment by epeshk** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventlistener?view=net-6.0

Oh, is it not a bug and expected because of:
> When an event listener is created, **a series of OnEventSourceCreated calls** are made to notify the new listener of all the event sources that existed **before the listener was created**.

`OnEventSourceCreated` called from base `EventListener` constructor, before derived class constructor.

Still, very not obvious. Which is the best way to configure EventListener from outside to listen specific EventLevel/EventKeywords? Save target `EventSource` inside `OnEventSourceCreated` and then `EnableEvents` in constructor? Looks like it will break nullability.

**Comment by KalleOlaviNiemitalo** [comment]
Related issue <https://github.com/dotnet/runtime/issues/38804>.

**Comment by tommcdon** [comment]
@mikelle-rogers
