### ISSUE TITLE
Browser wasm on windows CI builds broken

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#63987]
While adding a new pipeline for the "extra" platforms (#62564) I've hit an issue with the browser wasm windows build legs:

```
HEAD is now at f44b841 2.0.23 (#828)
  Error: Downloading URL 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.15.5-win-x64.zip': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
  Warning: Possibly SSL/TLS issue. Update or install Python SSL root certificates (2048-bit or greater) supplied in Python folder or https://pypi.org/project/certifi/ and try again.
  Installation failed!
  Installing SDK 'sdk-releases-upstream-77b065ace39e6ab21446e13f92897f956c80476a-64bit'..
  Installing tool 'node-14.15.5-64bit'..
D:\a\_work\1\s\src\mono\mono.proj(153,5): error MSB3073: The command "git checkout 2.0.23 && powershell -NonInteractive -command "& ./emsdk.ps1 install 2.0.23; Exit $LastExitCode " && powershell -NonInteractive -command "& ./emsdk.ps1 activate 2.0.23; Exit $LastExitCode "" exited with code 1.
##[error]src\mono\mono.proj(153,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command "git checkout 2.0.23 && powershell -NonInteractive -command "& ./emsdk.ps1 install 2.0.23; Exit $LastExitCode " && powershell -NonInteractive -command "& ./emsdk.ps1 activate 2.0.23; Exit $LastExitCode "" exited with code 1.
```

The build pipeline is: https://dev.azure.com/dnceng/public/_build/results?buildId=1559642&view=logs&jobId=854f6d42-496e-5e8c-a1c9-7f7194a94a83&j=bce77159-c177-5da3-02f5-74ccd320a9d5&t=55fcbaba-323b-59bd-3ce8-039d98ed8365

@radekdoulik can you please take a look? I will comment the build legs out with a reference to this issue.

**Comment by radical** [comment]
The step that [installs the certs](https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/global-build-job.yml#L139-L147) is added based on `nameSuffix` containing `Windows_wasm`. That check would need to be updated.

**Comment by radekdoulik** [comment]
Yes, as @radical says, the certs step needs to be updated to run in the affected builds.

**Comment by safern** [comment]
Ah I see. I'll put up a subsequent PR to fix that. Thanks!
