### ISSUE TITLE
[wasm] the value "$(JsonToItemsTaskFactoryTasksAssemblyPath)" of the "AssemblyFile" attribute in element is not valid

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#63994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The result "" of evaluating the value "$(JsonToItemsTaskFactoryTasksAssemblyPath)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.1\Sdk\WasmApp.Native.targets

### .NET Version

6.0.101

**Comment by radical** [comment]
How are you building your project? Is it from the command line, or VS? Can you share the version details?

If you are building from the command line, then can you build with `-bl`, and share the generated `msbuild.binlog`?

**Comment by pengweiqhca** [comment]
> How are you building your project? Is it from the command line, or VS? Can you share the version details?
> 
> If you are building from the command line, then can you build with `-bl`, and share the generated `msbuild.binlog`?

VS can't load project, command line can't build.

[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/7901466/msbuild.binlog.zip)

**Comment by radical** [comment]
@pengweiqhca  Do you have `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk`? I think your installation might be corrupted.

**Comment by pengweiqhca** [comment]
> @pengweiqhca Do you have `C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.MonoTargets.Sdk`? I think your installation might be corrupted.

Yes, not exists. How to fix it?

**Comment by radical** [comment]
You will have to reinstall, but make sure to uninstall the existing dotnet first.
