### ISSUE TITLE
How to use the dotnet-runtime-xx snap?

### ISSUE THREAD

**Issue by philippseith** [dotnet/runtime#640]
I installed the dotnet-runtime-30 snap as described in [Installation using Snap](https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#installation-using-snap) on Ubuntu 18.04.
Then i copied an app that was published on Windows with `dotnet publish -f netcoreapp3.0 -r linux-x64 --self-contained=false` to the Ubuntu host.

I found no way to run the executable:

1. `./myexecutable` failed with 
`A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/philipp/publish/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
 `
2. `dotnet-runtime-30.dotnet ./myexecutable` failed with 
`It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download`
3. `dotnet-runtime-30.dotnet ./myexecutable.dll` failed with 
`Failed to create CoreCLR, HRESULT: 0x80070008`

On the other hand it works when the runtime snap is mounted and dotnet in the mounted filesystem is called with `~/mountpoint/dotnet ./myexecutable.dll` or when the sdk snap is used.

**Comment by philippseith** [comment]
#1634?

**Comment by cjp256** [comment]
You likely need to specify `DOTNET_ROOT=/snap/dotnet-sdk/current` in your environment to point dotnet at the correct location for the snap.  If not using the dotnet-sdk, point it wherever the runtime is located.

**Comment by NikolaMilosavljevic** [comment]
[Triage] Closing Snap issues to reflect current priorities.
