### ISSUE TITLE
Invoke_Instance_And_Static_Method_Win32_Process Test failure

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#64001]
Impacted test: `System.Management.Tests.ManagementObjectTests.Invoke_Instance_And_Static_Method_Win32_Process`

```
Assert.Equal() Failure
Expected: 0
Actual:   21
```

Looks like it has happened a few times in past 2 months.

CI console log:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63674-merge-0760086b3b2f4de597/System.Management.Tests/1/console.460d98c9.log?sv=2019-07-07&se=2022-02-06T15%3A09%3A15Z&sr=c&sp=rl&sig=uvbgXcLUIlyJ8%2FQFSgzCaUoPKE2IJsSWEWzW8n0KQGk%3D

**Comment by danmoseley** [comment]
21 = ERROR_NOT_READY. This launches a process through IWbemServices::ExecMethod. Likely next to impossible to figure out why this is happening without a repro and debugging IWbemServices::ExecMethod itself.

Although it's a bit fishy that one time it gave ERROR_INVALID_BLOCK  - I don't know what that means.


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-120d)
| where Result == "Fail"
| where Method == "Invoke_Instance_And_Static_Method_Win32_Process"
//| where Type == "System.IO.Compression.Tests.ZipFile_Create"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  //Arch = tostring(parse_json(Properties).architecture),
  //Test = Type1,
  Result,Finished,
  //Duration,
  //Method,
  //Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline|Pipeline_Configuration|OS|Result|Finished|Message|
|---|---|---|---|---|---|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-02 22:20:46.4110000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-04 13:32:56.7740000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-04 19:14:57.2860000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop-windows|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-08 14:13:24.0530000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-08 19:17:56.3890000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2021-12-17 02:37:07.4070000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   8|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open.svc|Fail|2021-12-21 12:10:17.6490000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open.svc|Fail|2021-12-22 02:03:59.6930000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open.svc|Fail|2021-12-22 11:02:15.5880000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2022-01-12 22:58:35.0340000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   9|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|Fail|2022-01-17 15:31:29.9460000|Assert.Equal() Failure<br>Expected: 0<br>Actual:   21|

**Comment by danmoseley** [comment]
Probably this test should either ignore these particular error codes, or retry.
