### ISSUE TITLE
Windows service suspension with green leaf  

### ISSUE THREAD

**Issue by KalibGao** [dotnet/runtime#64010]
Hey, I'm facing a new Windows 10 feature, It marks my background app ( asp.net core with background works hosted as a windows service) process as suspended, with a green leaf icon, shown as below: 
![image](https://user-images.githubusercontent.com/14325295/150082817-cf9598c6-69f9-4682-9601-64ca54dbcbf1.png)
 
I don't want it to stop my background worker business, and It seems that there is no way to prevent the windows to do this. 

The questions are:
1. Is there any API to tell windows that the specified app can not be optimized.
2. Can the background worker handle the windows service lifecycle event like OnStart, OnResume, OnSuspend... (Oh I hope not )

**Comment by maryamariyan** [comment]
> Is there any API to tell windows that the specified app can not be optimized.

I'm not sure if process being suspended for performance is something that can be controlled on the hosting windows services level.

> Can the background worker handle the windows service lifecycle event like OnStart, OnResume, OnSuspend... (Oh I hope not )

`WindowsServiceLifetime` assumes there's `ShutDown`, `Start` and `Stop`

https://github.com/dotnet/runtime/blob/3ae87395f638a533f37b8e3385f6d3f199a72f4f/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.cs#L28-L35

In terms of lifecycles, ApplicationLifetime has `Started`, `Stopped`, `Stopping` link [here](https://github.com/dotnet/runtime/blob/3ae87395f638a533f37b8e3385f6d3f199a72f4f/src/libraries/Microsoft.Extensions.Hosting/ref/Microsoft.Extensions.Hosting.cs#L87-L96)

Maybe the docs page here has more helpful information: https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service

**Comment by maryamariyan** [comment]
Closing as no further action needed.

**Comment by KalibGao** [comment]
Ok, let me make it straight, can asp.net core or hosting service prevent Windows 10 from stopping my background service apps.
