### ISSUE TITLE
Microsoft.Extensions work planned for .NET 7 

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#64015]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

For .NET 7 we are prioritizing the work to improve code reliability and minimize the number of high-impact bugs in the codebase. There's also some bottom up planned community requested feature requests available in the list.

### Hosting
- [x] #61634

### Caching
- [x] #50406
- [x] #59110

### Configuration
- [x] #44486
- [x] #62510
- [x] #36390

### Logging
- [x] #65264

### DI
- [ ] #65145

### Logging Source Generator (also listed in https://github.com/dotnet/runtime/issues/52549)

- [x] #64310
- [x] #62644
- [x] #61814
- [x] #61162
- [x] #60968
- [x] #58550 
- [x] #67167
- [x] #61547

### post-release feedback
- [x] #61675

### Testing and Documentation

- [x] #27471
- [x] #23900

### Nullability
- [x] #43605
- [x] #52148

## Planned for .NET 8+

- [ ] #46132
- [ ] #69490
- [ ] #62239
- [ ] #62579
- [ ] #67770
- [ ] #47191
- [ ] #44517
- [ ] #36123
- [ ] #44512
- [ ] #50777
- [ ] #43149
- [ ] #36021
- [ ] #61947
- [ ] #44512
- [ ] #55525

**Comment by SteveDunn** [comment]
Hi @maryamariyan - I'm happy to continue with https://github.com/dotnet/runtime/issues/36390

Do we know yet what needs to be different this time around? We reached an impasse last time as we didn't want to change the declared type at runtime (`IEnumerable<T>` to `IList<T>`).

I'm please to hear that it's being considered again though, as I think this issue will be more and prevalent as projects are switched over to have Nullable Reference Types switched on: https://github.com/dotnet/runtime/pull/52514#issuecomment-840357127

**Comment by maryamariyan** [comment]
> Hi @maryamariyan - I'm happy to continue with https://github.com/dotnet/runtime/issues/36390

Thanks @SteveDunn for the interest let me get back to you on this on whether or not it would be marked for up for grabs.

**Comment by geometrikal** [comment]
Humble request to at least fix https://github.com/dotnet/runtime/issues/36123 for PostgreSQL connection strings in .NET 7. I've created an issue in the docs to add a note about this bug as well.

**Comment by tarekgh** [comment]
@geometrikal this need decided which way to consider for fixing according to the comment https://github.com/dotnet/runtime/issues/36123#issuecomment-537822041. Also, looks there is a workaround in the issue too. Thanks for your understanding.

**Comment by geometrikal** [comment]
@tarekgh It looks like it was originally planned for .NET 6 then .NET 7 and now moved back to .NET 8. 😛 

The experience of a user using app service and a PostgreSQL connection string (https://github.com/dotnet/runtime/issues/36123#issuecomment-598127463) has not changed in 2 years. The workaround is very simple but unfortunately the discoverability of it is low. Hopefully these comments change that!
