### ISSUE TITLE
SQL DB Events collected via DiagnosticSourceEventSource don't include stacks

### ISSUE THREAD

**Issue by davidmikh** [dotnet/runtime#64020]
### Description

In .NET 6 (and in .NET 5) there seems to be an issue where SQL DiagnosticSource events collected from ETW (utilizing DiagnosticSourceEventSource) don't seem to have any stack information when they did in the past (in .NET Core 3.1). When collecting using dotnet-trace the events have stacks which leads me to believe it's an issue with DiagnosticSourceEventSource since from what I understand the original DiagnosticSource events are able to be collected using dotnet-trace without needing DiagnosticSourceEventSource and DiagnosticSourceEventSource just forwards the DiagnosticSource events to ETW.

### Reproduction Steps

Because this scenario requires using a database I've attached a sample app here, below is the code for it but you'll also need the mdf file (or your own DB to connect to)
[SQLExample.zip](https://github.com/dotnet/runtime/files/7900691/SQLExample.zip)

    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.IO;
    //using System.Data.SQLite;
    
    namespace ADO.NETTestApp
    {
        internal sealed class Program
        {
            static void Main(string[] args)
            {
            Console.ReadLine();

            var path = Path.GetFullPath(@"..\..\..\DatabaseSQLDb.mdf");
            SqlConnection conn = new SqlConnection(String.Format("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename={0};Integrated Security=True", path));

            // Create a new table statement
            SqlCommand createTable = new SqlCommand("CREATE TABLE ADONetTable (ID int, RandomField varchar(255));", conn);

            // Insert statement
            SqlCommand insertCmd = new SqlCommand("INSERT INTO ADONetTable (ID, RandomField) VALUES ('1', 'SOME_DATA');", conn);

            // Select data
            SqlCommand selectCmd = new SqlCommand("SELECT * FROM ADONetTable", conn);

            // Drop table
            SqlCommand deleteTable = new SqlCommand("DROP TABLE ADONetTable", conn);

            try
            {
                Console.WriteLine("The connection should be closed right now, its: {0}", conn.State.ToString());
                conn.Open();
                Console.WriteLine("The connection should be open right now, its: {0}", conn.State.ToString());

                createTable.ExecuteNonQuery();
                insertCmd.ExecuteNonQuery();

                testFunction(conn);

                SqlDataReader reader = selectCmd.ExecuteReader();
                while (reader.Read())
                {
                    Console.WriteLine("ID = {0}, RandomField = {1}", reader["ID"], reader["RandomField"]);
                }

                reader.Close();
                deleteTable.ExecuteNonQuery();
            }
            finally
            {
                // Cleanup
                conn.Close();
            }
        }

        // This function can be used as an example for Go To Source. The "SELECT ID FROM ADONetTable" query should bring you to the curly bracket that starts this function
        private static void testFunction(SqlConnection conn)
        {
            SqlCommand selectCmd = new SqlCommand("SELECT ID FROM ADONetTable", conn);
            SqlDataReader reader = selectCmd.ExecuteReader();
            while (reader.Read())
            {
                Console.WriteLine("Successfully executed query for Go To Source test");
            }
            reader.Close();
        }

    }

To collect using ETW and repro the bug do the following (unfortunately I'm not that familiar with ETW and methods of collecting from it so the only way I know how to do it is using the Database tool in Visual Studio)

1) Open the project in Visual Studio 2022 (make sure its targetting .NET 6 or 5)

2) Open the performance profiler menu (Debug -> Performance Profiler, the shortcut is ALT+F2)

3) Select the "Database" checkbox

4) Hit the "Start" button

5) Wait for the application to complete (in my example application you need to enter a line to get the application to execute its SQL commands)

6) Save the diagsession created by VS

7) Open that diagsession in perfview and open the Events view

8) Find the `Microsoft-Diagnostics-DiagnosticSource/Event` events

9) Note that there are no stacks (right clicking on any of those events and selecting "Any Stacks" doesn't work, nor does `HasStack="True"` appear in the event data

![image](https://user-images.githubusercontent.com/12531222/150218017-57eced54-1471-4c62-8a0d-ad35675a4688.png)

To collect using dotnet-trace (to show that the issue doesn't repro in that scenario) do the following:

1) Run the same application targetting .NET 5 or 6

2) Run this command to collect using dotnet-trace by attaching to the target process using its PID

`dotnet-trace collect -p <PID> --providers Microsoft-Diagnostics-DiagnosticSource:00000003:5:FilterAndPayloadSpecs=\"Microsoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Transaction.TransactionStarting@Activity1Start:-TransactionId;IsAsync\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Transaction.TransactionCommitted@Activity1Stop:\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Transaction.TransactionRolledBack@Activity1Stop:\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Transaction.TransactionDisposed@Activity1Stop:-TransactionId\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.CommandExecuting@Activity2Start:-Command;Command.CommandText;ConnectionId;IsAsync;Command.Connection.ClientConnectionId;Command.Connection.ServerVersion;Command.CommandTimeout;Command.CommandType;Command.Connection.ConnectionString;Command.Connection.Database;Command.Connection.DataSource;Command.Connection.PacketSize\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.DataReaderDisposing@Activity2Stop:-CommandId;RecordsAffected;ReadCount\r\nMicrosoft.EntityFrameworkCore/Microsoft.EntityFrameworkCore.Database.Command.CommandError@Activity2Stop:-Exception\r\nSqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandBefore:-OperationId;Command;Command.CommandText;ConnectionId;Operation;Command.Connection.ServerVersion;Command.CommandTimeout;Command.CommandType;Command.Connection.ConnectionString;Command.Connection.Database;Command.Connection.DataSource\r\nSqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandAfter:-OperationId\r\nSqlClientDiagnosticListener/System.Data.SqlClient.WriteCommandError:-OperationId;Exception\r\nSqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteCommandBefore:-OperationId;Command;Command.CommandText;ConnectionId;Operation;Command.Connection.ServerVersion;Command.CommandTimeout;Command.CommandType;Command.Connection.ConnectionString;Command.Connection.Database;Command.Connection.DataSource\r\nSqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteCommandAfter:-OperationId\r\nSqlClientDiagnosticListener/Microsoft.Data.SqlClient.WriteCommandError:-OperationId;Exception\",System.Threading.Tasks.TplEventSource`

3) Enter a line in the application so that it executes its SQL commands and wait for the application to complete

4) Open the resulting nettrace file in perfview and navigate to the `Microsoft-Diagnostics-DiagnosticSource/Event` events

5) Note how there are stacks this time for the events (right clicking on any of the events and selecting "Any stacks" works and `HasStack="True"` appears in the event data

![image](https://user-images.githubusercontent.com/12531222/150218689-340ca889-7280-4f3b-adb9-65d2ba552bf1.png)

The collection string and settings should be the same in both scenarios, just the former uses ETW to collect (and thus using DiagnosticSourceEventSource from what I understand) whereas the latter doesn't use ETW and thus doesn't utilize DiagnosticSourceEventSource. In addition, if you switch to targetting .NET Core 3.1 then the ETW scenario will also have stacks which leads me to believe this is a regression and not a configuration issue with how collection is being done using ETW (unless there was a change to how configuration needed to be done for events piped through DiagnosticSourceEventSource from .NET Core 3.1 to .NET 5 since that appears to be when the bug first appeared). 

### Expected behavior

Stacks should be present in the ETW collection scenario for DiagnosticSource events

### Actual behavior

Stacks are not present in the ETW collection scenario for DiagnosticSource events and will only appear in .NET 5 and 6 if you're using dotnet-trace to collect.

### Regression?

This does seem to be a regression - if you change the project to target .NET Core 3.1 then the DiagnosticSource events collected through ETW will have stacks.

### Known Workarounds

Currently the only workaround to missing stacks is to use dotnet-trace to collect DiagnosticSource events instead of ETW

### Configuration

These are the runtimes of .NET that were used when testing:

Microsoft.NETCore.App 3.1.22
Microsoft.NETCore.App 5.0.13
Microsoft.NETCore.App 6.0.1

And this is the version of dotnet-trace that was used in case its relevant:
5.0.236902+5366510b270d0f0ebffc9e36e9496688b20b96c2

OS: Windows 10 x64

**Comment by tommcdon** [comment]
@josalem

**Comment by josalem** [comment]
@brianrob correct me if I'm wrong, but I was under the impression that ETW stack collection is entirely out of process. In other words, the ETW system at the OS level collects stack traces of the event generating process and not the process itself. Changes in the runtime version shouldn't affect that.

As an experiment, could you try collecting the same trace via PerfView which also uses ETW? Ping me offline if you want guidance on how to do that. Collecting with another tool will help to rule out configuration differences since we should be able to configure PerfView the same as dotnet-trace.

**Comment by brianrob** [comment]
For events that aren't native CLR events (e.g. Microsoft-Windows-DotNETRuntime), stack collection is controlled by the collector on a per-provider basis, and the stack collection mechanism is a purely OS-based mechanism as @josalem states above.  I suspect that Visual Studio isn't requesting stacks for this provider, and so you're not getting them.  dotnet-trace always captures stacks unconditionally, so I'm not surprised to see that you get stacks by that mechanism.

You can confirm this by capturing using PerfView and the following command:

```
PerfView.exe collect /Providers:*Microsoft-Diagnostics-DiagnosticSource:@StacksEnabled=true
```

This will tell ETW to collect stacks for the DiagnosticSource provider.  If that doesn't work, then I'd be interested to see the trace to see if something is overriding the stack collection request.

**Comment by davidmikh** [comment]
Sorry for the delay on responding to this, I was able to run the scenario collecting the events via perfview (using the command @brianrob provided above) and found that perfview was able to collect stacks for the `DiagnosticSource` events in .NET 6 so this does appear to be a configuration issue on VS' side. I'll look into it further on our end to see what we might be missing and will let you know if I need any further assistance but just knowing for sure that it's a configuration issue on our end between 3.1 and 5/6 gives me a good place to start - thanks for your help!

**Comment by josalem** [comment]
@davidmikh - any updates on this issue? I'm going to close it for now but let me know if we need more digging here.
