### ISSUE TITLE
Reuse JsonSerializerOptions when used with JsonSerializerContext

### ISSUE THREAD

**Issue by JuanZamudioGBM** [dotnet/runtime#64025]
## Description
We currently have an extension method to encapsulate the serialization/deserialization logic, this is just basically because we have a custom converter that serialize enums as strings, we have a private static field of JsonSerializerOptions that we reuse when we call  JsonSerializer.Serialize to avoid generating a new object in every call.

We are testing the source generator in System.Text.Json and tried to do the same, but we got the exception:
`System.InvalidOperationException: "The specified 'JsonSerializerOptions' instance is already bound with a 'JsonSerializerContext' instance."`

The call is basically this:
`JsonSerializer.Serialize(myObject, typeof(MyObjectDto), new MyContext(StaticJsonSerializerOptions));`

Is there a way to avoid creating a new instance of JsonSerializerOptions in every call? or is it something wrong on how we are approaching this?

## Configuration
.NET SDK 6.0.101

**Comment by layomia** [comment]
> JsonSerializer.Serialize(myObject, typeof(MyObjectDto), new MyContext(StaticJsonSerializerOptions));

Can you cache & reuse the context instance that you create, similar to how you're already caching your custom options?

```cs
StaticJsonSerializerContext = new MyContext(StaticJsonSerializerOptions);
...
JsonSerializer.Serialize(myObject, typeof(MyObjectDto), StaticJsonSerializerContext);
```

**Comment by JuanZamudioGBM** [comment]
It does work, but it needs a new instance of JsonSerializerOptions per JsonSerializerContext, and our benchmarks shows that the performance is almost identical to the reflection based serialization (in speed and memory allocation) so we will use the current solution at the moment.

Thanks a lot for your time @layomia

**Comment by layomia** [comment]
@JuanZamudioGBM thanks for your feedback. Could you share a repro of your benchmarks so we can see why there are no perf improvements for serialization in your scenario? Note that there are no expected throughput improvements for deserialization with the current source-gen implementation.

**Comment by JuanZamudioGBM** [comment]
Let me prepare a repro and upload it to a public account.

**Comment by JuanZamudioGBM** [comment]
Here is the repro, I hope its useful.

https://github.com/JuanZamudioGBM/source-generator

**Comment by eiriktsarpalis** [comment]
With the inclusion of #63686 in .NET 7 it should be possible to assign existing `JsonSerializerContext` instances to new `JsonSerializerOptions` instances via the `TypeInfoResolver` property. It will also be possible to combine multiple `JsonSerializerContext` sources into one contract resolver as follows:
```C#
IJsonTypeInfoResolver combinedResolver = JsonTypeInfoResolver.Combine(MyContext1.Default, MyContext2.Default, MyContext3.Default);
var options = new JsonSerializerOptions { TypeInfoResolver = combinedResolver };
```
The new options instance will be combining source generated metadata from all three sources.

Per @layomia's earlier comment, using the metadata-based source generator is not expected to produce any substantial performance gains compared to reflection. The purpose of the metadata-based source generator is to minimize static initialization time and support application trimming.
