### ISSUE TITLE
How to detect or prevent HTTPS endpoint fallback to Http

### ISSUE THREAD

**Issue by erdembayar** [dotnet/runtime#64029]
Using `AllowAutoRedirect = true` on `net472` it let's me redirect `https` (https://bit.ly/3ry70XH) connection less secure `http` (http://beautifulfuninnerlaugh.neverssl.com/online) connection. How do I prevent from this?
Also is there any other way other than `AllowAutoRedirect = true` which lets connection downgrade https to http endpoint?

```c#
    internal class Program
    {
        static void Main(string[] args)
        {
            var source1 = new RemoteFeedSource("https://bit.ly/3ry70XH");
            StreamReader reader = new StreamReader(source1.Stream);
            string text1 = reader.ReadToEnd();
            Console.WriteLine(text1);
        }

        public class RemoteFeedSource 
        {
            private string url;
            protected virtual HttpMessageHandler Handler => new HttpClientHandler() { AllowAutoRedirect = true};

            public Stream Stream => client.Value.GetStreamAsync(url).Result;

            private readonly Lazy<HttpClient> client;

            public RemoteFeedSource(string url)
            {
                client = new Lazy<HttpClient>(() => new HttpClient(Handler));
                this.url = url;
            }
        }
    }


```

**Comment by wfurt** [comment]
Are you asking about .NET Core or `net472`? For former, look at https://github.com/dotnet/runtime/issues/28039 .

**Comment by erdembayar** [comment]
> Are you asking about .NET Core or `net472`? For former, look at #28039 .

I'm asking for both, we have both .NET Core and .NetFramework(`net472` and lower). 
I'm trying to understand under which circumstances this Https to Http connection downgrade happens?

**Comment by karelz** [comment]
This is one of the differences between .NET Framework and .NET Core.
.NET Framework will do automatic https to http redirects, while .NET Core will not (it will just log the information that such redirect was blocked) -- see #23813.
If you want different behavior on either of the frameworks, you need to handle redirects manually (i.e. set `AllowAutoRedirect = false` and react to 3xx error codes in desired way).

**Comment by karelz** [comment]
Also related: #28039 ... ask to expose API to allow HTTPS->HTTP redirects on .NET Core, which we closed as Won't Fix - see the issue for details.
