### ISSUE TITLE
TryAddWithoutValidation for multiple values could be more efficient

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#64049]
The method takes an `IEnumerable<string>`. Things we could improve:
- Special-case `IList<string>` or some other type to avoid boxing the enumerator
- Avoid double entry lookups in case of more than one value
- Avoid unnecessary `List` resizes if we already know the final size

For example
```c#
TryAddWithoutValidation("foo", "1");
TryAddWithoutValidation("foo", new[] { "2", "3" });
```

Will currently allocate the enumerator, a `List<string>` of size 2, and a `List<string>` of size 4.

We can reduce that down to allocating a single `List<string>` of size 3.

An example of how this can be achieved:
https://gist.github.com/MihaZupan/800df7a324a66a8e814c3ec91f3d39b0

**Comment by karelz** [comment]
Triage: Worth investment, but the method is not commonly used, so not priority.

**Comment by deeprobin** [comment]
I am confident that this will grant a performance advantage. As @karelz mentioned, this does not seem to be a method on the hot path.

@MihaZupan 
Do you feel like submitting a pull request and also creating a benchmark in [dotnet/performance](https://github.com/dotnet/performance)?

**Comment by MihaZupan** [comment]
It's not a priority for us for now, but I'll happily review a PR if you are interested :)
