### ISSUE TITLE
KnownHeader values may change casing of received values

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#64053]
For the headers we consider known, we sometimes also cache common values. When matching against these values, we do so in a case-insensitive manner. As a result, this implementation detail can change the exact value observed by the user.

E.g. server responding with `Connection: Close` will be interpreted as `Connection: close`.
This means that adding more known values (#63750) is a small breaking change.

As most clients/servers use a single known casing for a given value, we aren't actually saving allocations by doing a case-insensitive check.
We should switch to doing ordinal comparisons to avoid the behavior changes + save a few cycles on cheaper comparisons.

**Comment by geoffkizer** [comment]
> This means that adding more known values (#63750) is a small breaking change.

Note that adding more known header names (not values) is already a small breaking change. Not sure we need to do anything about that, but it seems worth mentioning...

**Comment by karelz** [comment]
Triage: Assuming we have data backing the casing is mostly the same (@MihaZupan looked at top 1000 sites), we are fine with it. It will bring tiny perf improvement and prevent us from small breaking changes in future.

**Comment by karelz** [comment]
The change was backported also to 6.0.15 under AppContext switch in PR #80754.
