### ISSUE TITLE
BasicThreading test seg fault in Build Linux x64 release NativeAOT

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#64060]
Looks to me like a segfault when running AOT tooling on test.

```
nativeaot/SmokeTests/BasicThreading/BasicThreading/BasicThreading.sh [FAIL]
        /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/nativeaot/SmokeTests/BasicThreading/BasicThreading/BasicThreading.sh: line 417: 23712 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/nativeaot/SmokeTests/Reports/nativeaot.SmokeTests/BasicThreading/BasicThreading/BasicThreading.output.txt
        Raw output:
        BEGIN EXECUTION
        Running Native AOT:  /__w/1/s/dotnet.sh msbuild /p:IlcPath=/__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/nativeaot nativebuild.proj
        Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
        Copyright (C) Microsoft Corporation. All rights reserved.
        
          Generating native code
        native/BasicThreading ''
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1

```

It didn't repro on rerun.
https://dev.azure.com/dnceng/public/_build/results?buildId=1559287&view=logs&j=8e397556-8f46-55f6-8352-1da65b6a81cc&t=c6c71b21-90e9-5869-412e-c886f17d1052&s=96ac2280-8cb4-5df5-99de-dd2da759617d

Don't see a dump or much to go on here.  Since this is running on the build machine it seems to miss out on the dump gathering infra we would normally get for test runs.  Filing an issue to capture any other ref-counts that folks might see.

**Comment by MichalStrehovsky** [comment]
I've had this test running in a loop for a couple hours with varying levels of parallelism, but had no luck reproing it so far.

**Comment by MichalStrehovsky** [comment]
We haven't seen this repro in a long time and this test runs on all pull requests that touch coreclr.
