### ISSUE TITLE
Pass through diagnostic information for failed calls to IPC WriteDumpAsync

### ISSUE THREAD

**Issue by kelltrick** [dotnet/runtime#64069]
When calling the diagnostics IPC command `WriteDumpAsync` any failure results in the code `0x80004005` aka `E_FAIL`. This makes it difficult to diagnose why createdump failed. Here is runtime function responsible for returning `E_FAIL` [`ds_rt_generate_core_dump (DiagnosticsDumpCommandId commandId, DiagnosticsGenerateCoreDumpCommandPayload *payload)`](https://github.com/dotnet/runtime/blob/27fdc2d22f8717c7b0ba254ae9ef2900d00f5e7a/src/coreclr/vm/eventing/eventpipe/ds-rt-coreclr.h#L191) for context.

My proposal is to return more meaningful error codes through the IPC channel for various common error conditions. I would like different error codes for:
- Permission denied (reading process memory)
```
open(/proc/1/mem) FAILED 13 (Permission denied)
```
- Out of disk space
- Permission denied (writing the dump file)
- Out of memory

**Comment by tommcdon** [comment]
@mikem8361
