### ISSUE TITLE
[Mono] Intrinsify API's of System.Numerics.Vector and new API's of System.Runtime.Intrinsics.{64, 128} on Arm64

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#64072]
### `System.Runtime.Intrinsics.Vector{64, 128}` and `System.Numerics.Vector`:

- IsHardwareAccelerated
   - [x] arm64
- Abs - @mkhamoyan
   - [x] arm64
- Add
   - [x] arm64
- AndNot
   - [x] arm64
- BitwiseAnd
   - [x] arm64
- BitwiseOr
   - [x] arm64
- Ceiling - @simonrozsival
   - [x] arm64
- ConditionalSelect - @simonrozsival
   - [x] arm64
- ConvertToDouble
   - [x] arm64
- ConvertToInt32
   - [x] arm64
- ConvertToInt64
   - [x] arm64
- ConvertToSingle
   - [x] arm64
- ConvertToUInt32
   - [x] arm64
- ConvertToUInt64
   - [x] arm64
- Divide
   - [x] arm64
- Dot - @simonrozsival
   - [x] arm64
- Equals - @simonrozsival 
   - [x] arm64
- EqualsAll  - @simonrozsival
   - [x] arm64
- EqualsAny  - @simonrozsival
   - [x] arm64
- Floor - @simonrozsival
   - [x] arm64
- GreaterThan - @simonrozsival 
   - [x] arm64
- GreaterThanAll - @simonrozsival 
   - [x] arm64
- GreaterThanAny - @simonrozsival 
   - [x] arm64
- GreaterThanOrEqual - @simonrozsival 
   - [x] arm64
- GreaterThanOrEqualAll - @simonrozsival 
   - [x] arm64
- GreaterThanOrEqualAny - @simonrozsival 
   - [x] arm64
- LessThan - @simonrozsival
   - [x] arm64
- LessThanAll - @simonrozsival 
   - [x] arm64
- LessThanAny - @simonrozsival 
   - [x] arm64
- LessThanOrEqual - @simonrozsival
   - [x] arm64
- LessThanOrEqualAll - @simonrozsival 
   - [x] arm64
- LessThanOrEqualAny - @simonrozsival 
   - [x] arm64
- Max
   - [x] arm64
- Min
   - [x] arm64
- Multiply
   - [x] arm64
- Narrow
   - [x] arm64
- Negate - @mkhamoyan
   - [x] arm64
- OnesComplement - @mkhamoyan
   - [x] arm64
- Sqrt - @mkhamoyan
   - [x] arm64
- Subtract
   - [x] arm64
- Sum - @simonrozsival
   - [x] arm64
- Widen - @simonrozsival
   - [x] arm64
- Xor
   - [x] arm64

### `System.Runtime.Intrinsics.Vector{64, 128}<T>` and `System.Numerics.Vector<T>`:
- Operator `+` (one operand) - @simonrozsival
   - [x] arm64
- Operator `-` (one operand)
   - [x] arm64
- Operator `~`
   - [x] arm64
- Operator `+` @mkhamoyan 
   - [x] arm64
- Operator `-` @mkhamoyan 
   - [x] arm64
- Operator `*` @mkhamoyan 
   - [x] arm64
- Operator `/` @mkhamoyan 
   - [x] arm64
- Operator `==` - @simonrozsival
   - [x] arm64
- Operator `!=` - @simonrozsival
   - [x] arm64
- Operator `&`
   - [x] arm64
- Operator `|`
   - [x] arm64
- Operator `^`
   - [x] arm64

**Comment by fanyang-mono** [comment]
**Motivation of this work:**

There is a recent change to `System.Numerics.Vector` in the library code, which, as a result, caused regressions in Mono runtime (https://github.com/dotnet/runtime/pull/53450). The regression could be observed via TechEmpower benchmark
<img width="1239" alt="Screen Shot 2022-01-20 at 4 29 57 PM" src="https://user-images.githubusercontent.com/52458914/150425133-e439647a-9988-4214-ad10-d22ce0144603.png">
and a few microbenchmarks, for example `System.Tests.Perf_String.IndexOfAny`
<img width="1004" alt="Screen Shot 2022-01-20 at 5 20 21 PM" src="https://user-images.githubusercontent.com/52458914/150431438-cf22edfd-1242-47fb-bce0-4f4f3bb4f70e.png">

When comparing the generated code for the above microbenchmark test, I noticed the big generated code change for `System.Numerics.Vector:Equals`. Before the change, the IL for it was very small and simple. Mono was able to replace the deferred function `System.Numerics.Vector<T>:Equals` with an instrinsic. After the change, the IL for this same method became much longer with a few more calls to various complex methods, which ended up becoming way longer assembly code. Here are the codegen logs of a simplified app running with Mono runtime before and after this change
- Before https://gist.github.com/fanyang-mono/9641dcb7cb29b791d307552183999049
- After https://gist.github.com/fanyang-mono/950000e88a94d61a11ffab4ac26fb5f1
- The simplified app https://gist.github.com/fanyang-mono/c1b689ce6ba7def3cd01ad496e1fc7ab

The solution to this regression is to intrinsify the methods of `System.Numerics.Vector`.

**Comment by fanyang-mono** [comment]
Implementation wise, look at `SN_Equals` case for `System.Numerics.Vector<T>` for inspiration.

**Comment by tannergooding** [comment]
This should likely also extend to the APIs of the same names on `Vector64`, `Vector128`, and `Vector256` (in the `System.Runtime.Intrinsics` namespace). It "should" hopefully be easy to add the support for both simultaneously.

**Comment by fanyang-mono** [comment]
> This should likely also extend to the APIs of the same names on `Vector64`, `Vector128`, and `Vector256` (in the `System.Runtime.Intrinsics` namespace). It "should" hopefully be easy to add the support for both simultaneously.

That work has been tracked here https://github.com/dotnet/runtime/issues/42350. Most of the intrinsics for `Vector64`, `Vector128` have been implemented in .NET6. The ones for `Vector256` will be implemented in .NET7.

**Comment by tannergooding** [comment]
@fanyang-mono, these are new APIs introduced in .NET 7, so they wouldn't be covered by #42350

**Comment by fanyang-mono** [comment]
> @fanyang-mono, these are new APIs introduced in .NET 7, so they wouldn't be covered by #42350

Good point. I've updated the description.

**Comment by fanyang-mono** [comment]
I am closing this issue, as all the work planed for this issue has been finished.
