### ISSUE TITLE
System.Text.Json.SourceGeneration tests failing on netfx x86

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#64071]
```
C:\h\w\B4A40A07\w\ADB2091D\e>xunit.console.exe System.Text.Json.SourceGeneration.Roslyn4.0.Unit.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.Json.SourceGeneration.Roslyn4.0.Unit.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.SourceGeneration.Roslyn4.0.Unit.Tests (found 19 of 21 test cases)
  Starting:    System.Text.Json.SourceGeneration.Roslyn4.0.Unit.Tests (parallel test collections = on, max threads = 2)
    System.Text.Json.SourceGeneration.UnitTests.GeneratorTests.TypeDiscoveryPrimitivePOCO [FAIL]
      System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
           at System.Span`1..ctor(T[] array, Int32 start, Int32 length)
           at Roslyn.Utilities.StringTable.Add(Char[] chars, Int32 start, Int32 len)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SlidingTextWindow.GetText(Int32 position, Int32 length, Boolean intern)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.CreateWhitespaceTrivia()
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LexerCache.LookupTrivia(Char[] textBuffer, Int32 keyStart, Int32 keyLength, Int32 hashCode, Func`1 createTriviaFunction)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.ScanWhitespace()
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxTrivia(Boolean afterFirstToken, Boolean isTrailing, SyntaxListBuilder& triviaList)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxToken()
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.Lex(LexerMode mode)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.PreLex()
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser..ctor(Lexer lexer, LexerMode mode, CSharpSyntaxNode oldTree, IEnumerable`1 changes, Boolean allowModeReset, Boolean preLexIfNotIncremental, CancellationToken cancellationToken)
           at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser..ctor(Lexer lexer, CSharpSyntaxNode oldTree, IEnumerable`1 changes, LexerMode lexerMode, CancellationToken cancellationToken)
           at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, ImmutableDictionary`2 diagnosticOptions, Nullable`1 isGeneratedCode, CancellationToken cancellationToken)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Unit.Tests/CompilationHelper.cs(66,0): at System.Text.Json.SourceGeneration.UnitTests.CompilationHelper.CreateCompilation(String source, MetadataReference[] additionalReferences, String assemblyName, Boolean includeSTJ)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Unit.Tests/JsonSourceGeneratorTests.cs(54,0): at System.Text.Json.SourceGeneration.UnitTests.GeneratorTests.TypeDiscoveryPrimitivePOCO()
    System.Text.Json.SourceGeneration.UnitTests.TypeWrapperTests.MetadataLoadFilePathHandle [FAIL]
      System.IO.FileLoadException : Could not load file or assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
           at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
           at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
           at System.Reflection.Assembly.Load(String assemblyString)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Unit.Tests/CompilationHelper.cs(34,0): at System.Text.Json.SourceGeneration.UnitTests.CompilationHelper.CreateCompilation(String source, MetadataReference[] additionalReferences, String assemblyName, Boolean includeSTJ)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.SourceGeneration.Unit.Tests/TypeWrapperTests.cs(32,0): at System.Text.Json.SourceGeneration.UnitTests.TypeWrapperTests.MetadataLoadFilePathHandle()
        ----- Inner Stack Trace -----
           at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
           at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
    System.Text.Json.SourceGeneration.UnitTests.GeneratorTests.NameClashCompilation [FAIL]
....
```

**Comment by jkotas** [comment]
Hit by #64057

**Comment by jkotas** [comment]
Likely introduce by #63803

cc @krwq @layomia

**Comment by agocke** [comment]
I think we should revert until we can stabilize the tests.

Side note: this looks like a problem in Roslyn, the parser should never throw.

**Comment by danmoseley** [comment]
It's just 3 tests right? If so we can just disable those 3 for netfx x86. `if (PlatformDetection.IsNetFramework && !Environment.Is64BitProcess) return` .

**Comment by jkotas** [comment]
> It's just 3 tests right? If so we can just disable those 3 for netfx x86.

That works only if the failure is deterministic. Is the failure deterministic?

**Comment by agocke** [comment]
Roslyn's parser is pretty battle tested (as you might guess) -- I think there's a decent chance this could be a runtime bug.

Either way, I think revert is a reasonable option here. We found an unanticipated problem with the suite, let's give devs a chance to look this over at their own pace and come back when ready.

**Comment by sbomer** [comment]
> Is the failure deterministic?

I don't think so - we had a [green](https://dev.azure.com/dnceng/public/_build/results?buildId=1563511&view=results) rolling build that included https://github.com/dotnet/runtime/pull/63803 yesterday, then hit these failures [today](https://dev.azure.com/dnceng/public/_build/results?buildId=1564586&view=results).

**Comment by danmoseley** [comment]
Indeed it is not deterministic.


```kusto
TestResults
//| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-180d)
| where Result == "Fail"
| where WorkItemFriendlyName == "System.Text.Json.SourceGeneration.Roslyn4.0.Unit.Tests"
| where Message contains "Index"
//| where Type == "System.Composition.Hosting.Core.Tests.ExportDescriptorPromiseTests"
//| where  Method == "GetAllocatedBytesForCurrentThread"
//| where Message contains "OSStatus error -50 - failed to generate asymmetric keypair"
| project 
  //Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
//  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
//  Result,
  Finished,
//  Duration,
  Method,
//  Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline_Configuration|Arch|Test|Finished|Method|Message|
|---|---|---|---|---|---|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|CanGetAttributes|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|MetadataLoadFilePathHandle|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|WarnOnClassesWithInitOnlyProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|UnsuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|WarnOnClassesWithInaccessibleJsonIncludeProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|NameClashSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|SuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|ProgramsThatDontUseGeneratorCompile|System.IO.FileLoadException : Could not load file or assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)<br>---- System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|ContextTypeNotInNamespace|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|CollectionDictionarySourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|RecordDerivedFromRecordInExternalAssembly|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|NoWarningsDueToObsoleteMembers|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|TypeDiscoveryWithRenamedAttribute|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|TestMultipleDefinitions|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|TypeDiscoveryPrimitiveExternalPOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|NameClashCompilation|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 17:44:05.9180000|TypeDiscoveryPrimitivePOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|CanGetAttributes|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|MetadataLoadFilePathHandle|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|ContextTypeNotInNamespace|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|CollectionDictionarySourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|RecordDerivedFromRecordInExternalAssembly|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|NoWarningsDueToObsoleteMembers|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|TypeDiscoveryWithRenamedAttribute|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|TestMultipleDefinitions|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|TypeDiscoveryPrimitiveExternalPOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|NameClashCompilation|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|TypeDiscoveryPrimitivePOCO|System.IO.FileLoadException : Could not load file or assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)<br>---- System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|WarnOnClassesWithInitOnlyProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|UnsuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|WarnOnClassesWithInaccessibleJsonIncludeProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|NameClashSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|SuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-19 22:24:03.4400000|ProgramsThatDontUseGeneratorCompile|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|WarnOnClassesWithInitOnlyProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|UnsuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|WarnOnClassesWithInaccessibleJsonIncludeProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|NameClashSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|SuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|ProgramsThatDontUseGeneratorCompile|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|CanGetAttributes|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|MetadataLoadFilePathHandle|System.IO.FileLoadException : Could not load file or assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)<br>---- System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|ContextTypeNotInNamespace|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|CollectionDictionarySourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|RecordDerivedFromRecordInExternalAssembly|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|NoWarningsDueToObsoleteMembers|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|TypeDiscoveryWithRenamedAttribute|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|TestMultipleDefinitions|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|TypeDiscoveryPrimitiveExternalPOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|NameClashCompilation|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-20 18:50:25.6760000|TypeDiscoveryPrimitivePOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|WarnOnClassesWithInitOnlyProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|UnsuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|WarnOnClassesWithInaccessibleJsonIncludeProperties|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|NameClashSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|SuccessfulSourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|ProgramsThatDontUseGeneratorCompile|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|ContextTypeNotInNamespace|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeExpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|CollectionDictionarySourceGeneration|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|RecordDerivedFromRecordInExternalAssembly|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|NoWarningsDueToObsoleteMembers|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|TypeDiscoveryWithRenamedAttribute|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|TestMultipleDefinitions|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|LocalJsonSerializableAttributeUnexpectedShape|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|TypeDiscoveryPrimitiveExternalPOCO|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|NameClashCompilation|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|TypeDiscoveryPrimitivePOCO|System.IO.FileLoadException : Could not load file or assembly 'System.Collections, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Array subscript out of range. (Exception from HRESULT: 0x80131508)<br>---- System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|CanGetAttributes|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
|Release|x86|test/functional/cli/innerloop/|2022-01-21 08:53:50.6040000|MetadataLoadFilePathHandle|System.IndexOutOfRangeException : Index was outside the bounds of the array.|
