### ISSUE TITLE
TokenBucketRateLimiter.WaitAsync() does not immediately reduce the _queueCount on cancellation

### ISSUE THREAD

**Issue by halter73** [dotnet/runtime#64078]
### Description

`TokenBucketRateLimiter.WaitAsync(int, CancellationToken)` still counts the requested tokens against the `QueueLimit` after they've been canceled by the `CancellationToken` after an incomplete `ValueTask` is returned. This is eventually fixed when the request is dequeued from the `Deque<RequestRegistration>` by `ReplenishInternal`, but that could be too late.

### Reproduction Steps

```C#
var limiter = new TokenBucketRateLimiter(new TokenBucketRateLimiterOptions(1, QueueProcessingOrder.OldestFirst, 1,
    TimeSpan.Zero, 1, autoReplenishment: false));

limiter.Acquire(1);

var cts = new CancellationTokenSource();
var firstWaitTask = limiter.WaitAsync(1, cts.Token);

cts.Cancel();
await Assert.ThrowsAsync<OperationCanceledException>(() => firstWaitTask.AsTask());

// This incorrectly returns a failed lease immediately because ctc.Cancel() did not reduce the _queueCount.
var secondWaitTask = limiter.WaitAsync(1, cts.Token);
//Assert.False(secondWaitTask.IsCompleted)

Assert.True(limiter.TryReplenish());

// WaitAsync() no longer returns a failed lease because we called TryReplenish(), but that shouldn't be necessary
var thirdWaitTask = limiter.WaitAsync(1, cts.Token);
Assert.False(thirdWaitTask.IsCompleted)
```

### Expected behavior

The `secondWaitTask` should initially be incomplete and later complete successfully when the `TokenBucketRateLimiter` is replenished.

### Actual behavior

The `secondWaitTask` immediately returns a non-acquired lease because the `QueueLimit` has supposedly been exceeded (but not really).

### Regression?

No.

**Comment by stephentoub** [comment]
Sounds similar to https://github.com/dotnet/runtime/issues/761. They're using the same helper type, right? We might want to address them together. I haven't fixed that one yet as I've been concerned about the perf impact.

**Comment by halter73** [comment]
I'm not very familiar with the Channel code. What helper type are you referring to? AsyncOperation? I don't think were sharing anything. I think the following code will need to be changed to decrement `_queueCount`:

https://github.com/dotnet/runtime/blob/0b8204f7a3b284a069fcbc021d4d744dd6e4fd4d/src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs#L132-L135

And this logic will need to be updated to not decrement `_queueCount` in the cancellation case:

https://github.com/dotnet/runtime/blob/0b8204f7a3b284a069fcbc021d4d744dd6e4fd4d/src/libraries/System.Threading.RateLimiting/src/System/Threading/RateLimiting/TokenBucketRateLimiter.cs#L277-L286

We're also somewhat concerned about perf because the `CancellationToken.Register` callback will need a reference to the `TokenBucketRateLimiter` instance and the `tcs` forcing an extra allocation. It's far from the only allocation on this code path though, and we've discussed pooling a custom `IValueTaskSource` in the future which we could then use to store the extra reference avoiding the extra allocation.
