### ISSUE TITLE
fatal error LNK1295: '/INCREMENTAL' not compatible with '/DEBUGTYPE' specification...

### ISSUE THREAD

**Issue by FutureCompute** [dotnet/runtime#64082]
### Discussed in https://github.com/dotnet/runtime/discussions/64054

<div type='discussions-op-text'>

<sup>Originally posted by **FutureCompute** January 20, 2022</sup>
I downloaded .NET 6 runtime source and ran build.cmd successfully. But when I followed method 2 of "Debugging CoreCLR on Window" in debugging.md, run "build -msbuild" I get 4 build errors as below. By following method 1 I get more build errors. I wonder if I missed anything. Thanks.

|
V

  LINK : fatal error LNK1295: '/INCREMENTAL' not compatible with '/DEBUGTYPE' specification; link without '/INCREMENTAL' [D:\runtime-6.0.0\artifacts\obj\coreclr\windows.x64.Debug\ide\tools\InjectResource\InjectResource.vcxproj]
  LINK : fatal error LNK1295: '/INCREMENTAL' not compatible with '/DEBUGTYPE' specification; link without '/INCREMENTAL' [D:\runtime-6.0.0\artifacts\obj\coreclr\windows.x64.Debug\ide\tools\GenClrDebugResource\GenClrDebugResource.vcxproj]
  LINK : fatal error LNK1295: '/INCREMENTAL' not compatible with '/DEBUGTYPE' specification; link without '/INCREMENTAL' [D:\runtime-6.0.0\artifacts\obj\coreclr\windows.x64.Debug\ide\dlls\mscordac\mscordaccore.vcxproj]
  LINK : fatal error LNK1295: '/INCREMENTAL' not compatible with '/DEBUGTYPE' specification; link without '/INCREMENTAL' [D:\runtime-6.0.0\artifacts\obj\coreclr\windows.x64.Debug\ide\dlls\mscordbi\mscordbi.vcxproj]</div>

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by songge-MS** [comment]
I encountered the same problem. Can you have a look? @hoyosjs

**Comment by AaronRobinsonMSFT** [comment]
@FutureCompute and @songge-MS Which version of Visual Studio is being used?

**Comment by FutureCompute** [comment]
@AaronRobinsonMSFT I use Visual Studio 2022, as the document suggests.

**Comment by mgexo** [comment]
I have the same problem with VS2022 Version 17.3.4  
I created the solution by executing 
`build.cmd -vs coreclr.sln -a x64 -c Debug `

**Comment by kunalspathak** [comment]
Same problem with VS2022 17.5.3

**Comment by hoyosjs** [comment]
@agocke do we prefer `cv,fixup`, or do we prefer incremental linking ?

**Comment by hoyosjs** [comment]
@agocke do we prefer `cv,fixup`, or do we prefer incremental linking ?

**Comment by agocke** [comment]
fixup
