### ISSUE TITLE
Setting LC_ALL=zh_CN.utf8 LANG=zh_CN.utf8 without using Globalization Invariant Mode in Linux has serious performance problems

### ISSUE THREAD

**Issue by saber-wang** [dotnet/runtime#64093]
1. Setting environment variables
```
export LC_ALL=zh_CN.utf8     LANG=zh_CN.utf8     DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY=false     DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```

2. Run the test program and observe the output
```
dotnet run
```
3. Setting environment variables
```
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
```
4. Run the test program and observe the output
```
dotnet run
```

#### result:

| 版本      |Globalization Invariant Mode |Elapsed |
| ----------- | ----------- | ----------- |
| netcore3.1      | false       | 4103ms  |
| netcore3.1      | true   | 66ms  |
| net6   | false       | 356ms |
| net6   | true   | 60ms|

####  Current system environment:
cpu: amd r7 4800U
Memory: 16GB
Hard disk: 512GB SSD
operating system: 
- Ubuntu 20.04 LTS(wsl)  
- alpine-3.13(docker)

#### Test code
```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {

        public static async Task Main(string[] args)
        {
            string[] arr = new string[] { "a", "b", "c", "d", "e", "f", "g" };

            var a = new List<string>();

            var b = new List<string>();
            Stopwatch sw = new Stopwatch();
            GeneratorA(a, 1000);
            GeneratorB(b, 1000);
            sw.Reset();
            sw.Start();
            var data = a.Where(p => b.Any(o => o.StartsWith(p))).ToList();
            sw.Stop();
            Console.WriteLine($"{sw.ElapsedMilliseconds}ms");


            void GeneratorA(List<string> A, int len)
            {
                A.Clear();
                Random random = new Random();

                for (var i = 0; i < len; i++)
                {
                    var l = random.Next(8);
                    string tmp = string.Empty;
                    for (var j = 0; j < l; j++)
                    {
                        var r = random.Next(arr.Length - 1);
                        tmp += arr[r];
                    }
                    A.Add($"{i}{tmp}");
                }
            }

            void GeneratorB(List<string> B, int len)
            {
                B.Clear();
                Random random = new Random();

                for (var i = 0; i < len; i++)
                {
                    var l = random.Next(10);
                    string tmp = string.Empty;
                    for (var j = 0; j < l; j++)
                    {
                        var r = random.Next(arr.Length - 1);
                        tmp += arr[r];
                    }
                    B.Add($"{i}{tmp}");
                }
            }
        }


    }
}
```

**Comment by huoyaoyuan** [comment]
Can you compare with other locales to see if there's problem specific to zh_CN? Please also test another locale other than English.

You may also compare the result in Windows.

Since `StartsWith` is culture-aware by default, it is expected to be somehow slower than culture invariant mode. If you want non culture-aware behavior, you can provide `StringComparison.Ordinal`.

**Comment by tarekgh** [comment]
@saber-wang when doing linguistic comparisons (as when turning the globalization invariant mode off), it is expected to be much slower. When turning the invariant mode on, we are just comparing as ordinal (byte-by-byte like comparison). While when doing logistic comparisons there are a lot of things to be done and not just comparing bytes. You can see also we tried to enhance the performance in .NET 6.0 compared to 3.1.

As @huoyaoyuan mentioned if you don't care much about the linguistic comparisons, you can use the Ordinal comparisons. This should help much getting a behavior closer to when turning on globalization mode. I am closing this issue, feel free to reply back with any more questions if you have any.
