### ISSUE TITLE
System.Drawing.Drawing2D.GraphicsPath throws OutOfMemoryException when calling Widen(pen).

### ISSUE THREAD

**Issue by wstaelens** [dotnet/runtime#64092]
### Description

A System.Drawing.Drawing2D.GraphicsPath throws OutOfMemoryException when calling Widen(pen) on it.

It only happens when **all** Points of the path are the same. 

The issue has been there already more than 10 years and occurs in .NET.

### Reproduction Steps

![outofmem-widen](https://user-images.githubusercontent.com/7447285/150511851-a4c8a377-9646-42dd-a3b6-0ed1b3972b47.png)

My code just called .Widen() and throws several times as it seems to contains multiple 'point'paths.

`  clonedPath.Widen(p.Pen);`

I'm processing and rendering files (CAD drawings), so I can't modify the sources of these CAD applications to not allow them to create _"point"_lines. 🤓 

Example taken from: https://stackoverflow.com/questions/6927774/graphicspath-and-outofmemoryexception

```
//This works:
  using (GraphicsPath path = new GraphicsPath())
  {
    path.AddLine(new Point(16, 16), new Point(20, 20));
    path.Widen(Pens.Black);
    e.Graphics.DrawPath(Pens.Black, path);
  }

  //This does not:
  using (GraphicsPath path = new GraphicsPath())
  {
    path.AddLine(new Point(20, 20), new Point(20, 20));
    path.Widen(Pens.Black);
    e.Graphics.DrawPath(Pens.Black, path);
  }
```

(can't share file...)

### Expected behavior

No OutOfMemoryException being thrown....

### Actual behavior

Throws an OutOfMemoryException (several times)

### Regression?

never worked before.

### Known Workarounds

Very slow and inefficient method....
suggestions are welcome to make this workaround fast because it takes rendering time from seconds to minutes.

```
        public static bool IsPathAPoint(GDIP2D.GraphicsPath path)
        {
            if (path is null) throw new ArgumentNullException(nameof(path));
            
            var pathPointCount = path.PointCount;
            if (pathPointCount < 2)
                return true;

            var pathPoints = path.PathPoints;
            if (pathPoints[0] != pathPoints[^1])
                return false;

            int endBound = pathPointCount - 1;
            for (int i = 1; i <= endBound; i++)
            {
                if (pathPoints[i - 1] != pathPoints[i])
                    return false;
            }

            // if all the points are the same
            return true;
        }
```

### Configuration

.net 5 (latest)
windows 10 pro 21h2

**Comment by wstaelens** [comment]
again #Future label 😞

**Comment by carlossanlop** [comment]
@JeremyKuhne can you please take a look?

**Comment by JeremyKuhne** [comment]
Unfortunately, there isn't anything we can do here as this is a GDI+ problem and we can't get changes made in GDI+.
