### ISSUE TITLE
Skip building "3.0.0"-branded targeting pack in 3.0.2+ source-build

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#641]
Source-build will be building the `Microsoft.NETCore.App.Ref` `3.0.0` targeting pack in dotnet/source-build-reference-packages for 3.0.1+, however in 3.0.2+ I also merged some Core-Setup infrastructure that will have this repo build a "3.0.0"-branded targeting pack when building any 3.0.2+ commit: https://github.com/dotnet/arcade/pull/4318.

The source-build version is preferred because it's more static: we can trust it not to change due to accidental (or intentional but unwanted) changes to future versions of Core-Setup. There is danger of Core-Setup 3.0.2 building a "3.0.0"-branded targeting pack that isn't actually the same as the actual `v3.0.0` targeting pack, causing behavior differences in the source-built SDK. See https://github.com/dotnet/source-build/pull/1389

This infra needs to be disabled so the Core-Setup "3.0.0"-branded targeting pack doesn't conflict with the source-build 3.0.0 package.

This can be done without an Arcade update or source-build customization by setting `SkipSetLastReleasedVersionForSourceBuild` to true here.

/cc @dseefeld @adaggarwal

**Comment by NikolaMilosavljevic** [comment]
[Triage] This is working fine today.
