### ISSUE TITLE
Pipelines API: Reading incoming bytes

### ISSUE THREAD

**Issue by JZechy** [dotnet/runtime#64145]
### Description

I am testing custom implementation of Pipelines API for networking. For this, I have test that is sending multiple messages to destination. 

**Receiving First message**
`PipeWriter` receives data to `Memory` and `Advance()` by the number of received bytes. In my case, the message have 6 bytes.

`PipeReader` receives available data from Writer.  Returned buffer in form of `ReadOnlySequence` containes 6 bytes and starts from 0. So the `PositionOf()` extension method returns right index of EOL.

 Data are successfully read to the EOL and `AdvanceTo()` by 6 bytes.

**Second Message Received**
When second message arrives, everything still works fine for the Writer.

But the `PipeReader` returns weird `ReadOnlySequence`. The Sequence buffer is containing only newly received data (not the old ones). But its Start property is now set to 6. 

Now the `PositionOf()` results in index of 11. Index of the EOL + start position set to 6.

**Debugging**
I was trying to debug deeply into Pipelines API and discovered, when the `ReadOnlySequence` is created by `ReadAsync()`, as parameters for constructor are used the buffer containing all data ever received. And last examined index. But inside the `ReadOnlySequence`, the array is shorted to start from the last examined index, yet the start position is still the same. So the array is now starting on its end.

### Reproduction Steps

**Code reading from Socket**

```C#
PipeWriter writer = ReceivePipe.Writer;
            while (true)
            {
                Memory<byte> memory = writer.GetMemory(512);
                try
                {
                    int bytesRead = await Client.ReceiveAsync(memory, SocketFlags.None); // Client is Instance of Socket
                    if (bytesRead == 0)
                    {
                        Close(DisconnectReason.ConnectionLost);
                        break;
                    }

                    writer.Advance(bytesRead);
                }
                catch (Exception e)
                {
                    Close(DisconnectReason.ConnectionLost, e);
                    break;
                }

                FlushResult result = await writer.FlushAsync();
                if (result.IsCompleted)
                {
                    break;
                }
            }

            await writer.CompleteAsync();
```

**Cod reading from Pipe**
`Message` and `IMessageBuffer` are my internal classes processing received message.

```C#
PipeReader reader = ReceivePipe.Reader;

            while (!Cancellation.IsCancellationRequested)
            {
                ReadResult result = await reader.ReadAsync();
                ReadOnlySequence<byte> buffer = result.Buffer;
                SequencePosition? position;

                do
                {
                    position = buffer.PositionOf((byte) '\n');
                    if (position == null)
                    {
                        continue;
                    }

                    byte[] sliced = buffer.Slice(0, position.Value.GetInteger() + 1).ToArray();
                    IMessageBuffer messageBuffer = new MessageBuffer(sliced);
                    Message message = Message.Create(messageBuffer);
                    MessageReceived?.Invoke(this, new MessageReceivedArgs(message));
                    
                    // Skips to next message after End-Of-Message sign
                    buffer = buffer.Slice(buffer.GetPosition(1, position.Value));
                } while (position != null);

                reader.AdvanceTo(buffer.Start);

                if (result.IsCompleted)
                {
                    break;
                }
            }

            await reader.CompleteAsync();
````

### Expected behavior

`ReadOnlySequence` on second call should return only newly received data and Start attribute should be zero.

### Actual behavior

`ReadOnlySequence` on second call has Start attribute set to number of examined data in last call, while the sequence is only containing newly received data.

### Regression?

**System.IO.Pipelines**

- Version 6.0.0 is not working as expected
- Version 6.0.1 is not working as expected
- Version 6.0.2 is not working as expected

**System.Buffers**
_As the ReadOnlySequence comes from this package_

- 4.3.1 (Explicitly used) not working as expected
- 4.5.1 not working as expected

### Known Workarounds

This is searching for the bytes as it should, yet I am not sure if there can be some problems as you are ignoring sequence start.
```C#
buffer.First.Span.IndexOf((byte) '\n');
```

### Configuration

- .NET 6
- Windows 10
- x64
- This shouldn't be specific to the configuration

**Comment by tmds** [comment]
@JZechy you need the `AdvanceTo` overload that accepts two arguments:

```cs
void AdvanceTo (SequencePosition consumed, SequencePosition examined);
```

The first argument tells the reader how much it can throw away. This is all the data that you completely handled.

The second tells the reader that `ReadAsync` may only return when data is available past `examined`. If you don't set this to the end of the `Buffer` you got from `ReadAsync`, then `ReadAsync` will keep on returning even when there is no new data available.

The `ReadOnlySequence.Start` property is meant as an opaque value that you pass to other APIs. You shouldn't need or rely on its value.

See the example at https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines.

**Comment by JZechy** [comment]
Even with the overloaded method used as in example the result is same.

**Comment by tmds** [comment]
> Even with the overloaded method used as in example the result is same.

Can you share your code?
