### ISSUE TITLE
.NET 6 Crash in UnlockedLoaderHeap::GetMoreCommittedPages (loaderheap.cpp)

### ISSUE THREAD

**Issue by Vercidium** [dotnet/runtime#64152]
### Description

My program has been crashing intermittently and after analysing multiple crash dumps provided by multiple users, the common factor seems to be the [UnlockedLoaderHeap::GetMoreCommittedPages](https://github.com/dotnet/runtime/blob/main/src/coreclr/utilcode/loaderheap.cpp#L1206) function.

I believe this is caused by a corrupt heap but I'm unsure how to investigate this further.

I have uploaded the full analysis log from WinDbg to [a Gist here](https://gist.github.com/Vercidium/ee2e2573874f1ddcf7520f34ae5a3f53), this section seems to be important:
```
FAULTING_SOURCE_FILE:  D:\a\_work\1\s\src\coreclr\utilcode\loaderheap.cpp

FAULTING_SOURCE_LINE_NUMBER:  1234

FAULTING_SOURCE_CODE:  
No source found for 'D:\a\_work\1\s\src\coreclr\utilcode\loaderheap.cpp'


SYMBOL_NAME:  coreclr!UnlockedLoaderHeap::GetMoreCommittedPages+79

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

STACK_COMMAND:  ~38s ; .ecxr ; kb

FAILURE_BUCKET_ID:  SINGLE_STEP_80000004_coreclr.dll!UnlockedLoaderHeap::GetMoreCommittedPages
```

I have also uploaded the minidump to [Dropbox here](https://www.dropbox.com/sh/hmuqhn7z6ng4rsz/AACWlKzriFT8ch78IzjFhJGKa?dl=0).

The program uses some native libraries (soft_oal.dll, enet.dll and steam_api64.dll) and allocates some unmanaged memory itself (using the new .NET 6 `NativeMemory.Alloc` functions). The program runs many tasks in other threads using the .NET thread pool (`Task.Run`), as well as creating threads using `new Thread(new ParameterizedThreadStart(...))`.

For some users these crashes are often, but for others these crashes never occur.

### Reproduction Steps

I am unable to provide reproduction steps at this time, however I have uploaded the crash dump above if that is of use.

### Expected behavior

The program does not crash

### Actual behavior

The program crashes intermittently

### Regression?

This has been an issue with .NET 5 in the past. When I was using .NET 5, I was not allocating unmanaged memory myself and the only potentially unsafe code was in `soft_oal.dll`, `enet.dll` or `steam_api64.dll`.

### Configuration

**.NET Version**
6.0.101

**OS Version**
Windows 10 Version 19042 MP (6 procs) Free x64
Product: WinNt, suite: SingleUserTS Personal
Edition build lab: 19041.1.amd64fre.vb_release.191206-1406

**Architecture**
x64

**Achitecture Specific**
Unsure but most of the crashes occur on Windows 10

### Other information

Happy to provide extra information wherever possible.

**Comment by jkotas** [comment]
> SINGLE_STEP_80000004

This exception code means that something switched the thread into single stepping mode. The single stepping mode generates a trap after every instruction. It is typically only used by debuggers. Is the program using any techniques that are supposed to prevent debugging or attaching a debugger by any chance?

**Comment by Vercidium** [comment]
Thank you @jkotas, the game is protected by Easy Anticheat which prevents debuggers from being attached. I will follow this up with the EAC team.

What could cause a thread to change into single stepping mode? If EAC prevents this from happening I'll have to ensure that it doesn't enter this mode.

**Comment by jkotas** [comment]
> What could cause a thread to change into single stepping mode?

The single stepping mode is turned on by setting TF bit in Flags register (https://en.wikipedia.org/wiki/FLAGS_register). EAC can be turning it on in some situations to confuse debugger if one is attached, and thus making the debugger impossible to use.

**Comment by Vercidium** [comment]
Alrighty thank you for the clarification. I've raised an issue with the EAC team, happy to close this for now.
