### ISSUE TITLE
build-runtime.cmd on fresh clone fails

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#64156]
On a fresh clone, running `src\coreclr\build-runtime.cmd` on Windows complains about missing DAC dependency.

```cmd
> git clone https://github.com/dotnet/runtime --single-branch --depth 1
> runtime\src\coreclr\build-runtime.cmd
... near the end ...
[2235/2290] coreclr
FAILED: dlls/mscoree/coreclr/inject_debug_resources_coreclr.timestamp C:/Users/am11/projects/runtime/artifacts/obj/coreclr/windows
.x64.Debug/dlls/mscoree/coreclr/inject_debug_resources_coreclr.timestamp
dlls\mscoree\coreclr\CMakeFiles\inject_debug_resources_coreclr.timestamp-2632b18.bat 18efb35d99000c02
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30138 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```
Workaround is to then run `build.cmd clr` which takes a few (too many) minutes to restore packages for a simple C++ change.

**Comment by ivdiazsa** [comment]
I've been trying to reproduce this problem on the three OS's (Windows, MacOS, Linux), but to no avail. The build succeeds in my machines. This might have been fixed as a side effect of something else at some point.

@am11 Can you verify if it works for you as well, so we can close this issue if so?

**Comment by am11** [comment]
This issue was Windows specific. build-runtime.cmd is working flawlessly on fresh clone on Windows. It has been fixed since. 👍
