### ISSUE TITLE
NativeAOT ignores dependency's changes

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#64163]
### Description

NativeAOT ignores new changes in referenced projects.

### Reproduction Steps

1. Build application using NativeAOT
2. Edit code of  `ProjectReference` project
3. Build application using NativeAOT again

### Expected behavior

New build reflects latest changes

### Actual behavior

Changes are ignored

### Known Workarounds

Delete `bin` and `obj` folders.

### Configuration

Dotnet: 6.0.101
OS: Manjaro Xfce 21.2.0 x64
ILCompiler Package version: `6.0.0-*`

**Comment by jkotas** [comment]
Could you please share detailed repro steps? I have tried that you reproduction steps and it works fine for me.

Also, does it work for you without NativeAOT?

**Comment by SupinePandora43** [comment]
> Could you please share detailed repro steps? I have tried that you reproduction steps and it works fine for me.
> 
> Also, does it work for you without NativeAOT?

Without it it works.

Basically...
I've built `UltralightNet.OpenGL.TestApp`.
Then i put a `return` to `UltralightNet/Methods.cs:Preload()`.
Rebuilt again.
Launched and noticed that Preload still threw error even if it's just `return`.
https://github.com/SupinePandora43/UltralightNet on `upstream` branch in case you need a repository.

**Comment by jkotas** [comment]
Ok, I am able to reproduce it now.

> Edit code of ProjectReference project

The key detail is to avoid changing the public surface of the ProjectReference. It means that ref file of the ProjectReference stays intact, the .exe does not get rebuilt, and native compilation that just depends on the .exe does not get triggered.

SingleFile publishing handles this case correctly. We may want to copy what it does.

**Comment by jkotas** [comment]
cc @MichalStrehovsky
