### ISSUE TITLE
API Proposal: Add `ref` field feature support to `RuntimeFeature` class

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#64165]
## Background and motivation

This is desired to help Roslyn perform down-level targeting for the `ref` field support added in #63768.

## API Proposal

Implementation PR at https://github.com/dotnet/runtime/pull/64167.

```diff
namespace System.Runtime.CompilerServices
{
    public static partial class RuntimeFeature
    {
+        /// <summary>
+        /// Represents a runtime feature where types can define ref fields.
+        /// </summary>
+        public const string ByRefFields = nameof(ByRefFields);
    }
}
```

## API Usage

Used by Roslyn to detect if a runtime supports `ref` fields.

## Alternative Designs
This is the typical way to indicate a feature to Roslyn.

## Risks
None.

**Comment by jkotas** [comment]
I do not think we need a feature flag for this.

**Comment by AaronRobinsonMSFT** [comment]
This was a request by the Roslyn team for down-level compiling.

/cc @jaredpar @davidwrighton

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I will leave this as "api-suggestion" until we get consensus on whether this is needed or not. I will however push a PR with the change in the case it is needed.

**Comment by jkotas** [comment]
I though you meant `FEATURE_...` ifdef. I agree we need a flag for this under `RuntimeFeatures`. We should run it through API review before merging the PR.

> RefFields 

We have a clash of runtime and C# names here. 

We have `Type.IsByRef`, `Type.IsByRefLike` and `IsByRefLikeAttribute` in the runtime vs. `ref` and `ref structs` in C#.

Should this flag by called `ByRefFields` for consistency with what we have already?

**Comment by jaredpar** [comment]
@cston, @RikkiGibson FYI

**Comment by terrajobst** [comment]
* Looks good as proposed
* We should make sure that other runtimes, such as Unity, that features listed in the `RuntimeFeature` are required
    - Practically, if another runtime pulls in our library code they will likely find out, given that we usually use those features

```C#
namespace System.Runtime.CompilerServices
{
    public static partial class RuntimeFeature
    {
        public const string ByRefFields = nameof(ByRefFields);
    }
}
```
