### ISSUE TITLE
[API Proposal]: Get info about generic attributes

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#64169]
### Background and motivation

Make it easier to handle generic attributes.

### API Proposal

- Allow use open generic as a param to `Attribute.GetCustomAttributes` Method.. It currently returns an empty array.
- ~~Add an the  instance property `TypeArgs` to the Attribute class  that returns all type args if any.~~

### API Usage

```C#
var Attrs = Attribute.GetCustomAttributes(this.GetType(), typeof(TestAttribute<>));
var type = Attrs[0].TypeArgs[0];
```

**Comment by CyrusNajmabadi** [comment]
I'm not certain why this is needed. Why not just do `.GetType().TypeArguments`?

**Comment by buyaa-n** [comment]
For adding a new property i agree with @CyrusNajmabadi, doesn't seem we need to add property for `TypeArgs`

> Allow use open generic as a param to Attribute.GetCustomAttributes Method.. It currently returns a null.

Makes sense to me, will discuss with the team. As this is not a new API suggestion and we don't need the other API suggestion removing the `api-suggestion` label

**Comment by steveharter** [comment]
> Then typeof(HasAttributes).GetCustomAttributes(typeof(GenericAttribute<>)) would return all 3 attributes?

That is my understanding of the ask. I think it makes sense, although I don't know where this "open generic" convention is used elsewhere for similar filtering or scoping.

Since the workaround is not that difficult (get all custom attributes and manually filter) this feature is lower-priority.

**Comment by buyaa-n** [comment]
> Then typeof(HasAttributes).GetCustomAttributes(typeof(GenericAttribute<>)) would return all 3 attributes?

I believe that should depend on if the `bool inherit` parameter set, as it is false by default, in this case `DerivesFromGenericAttribute` should not be included.

**Comment by buyaa-n** [comment]
> @GrabYourPitchforks if we add a new convention for open generic types to be used to mean all closed, does this rise to the level of discussing it in an API review meeting?

@GrabYourPitchforks suggested to go through API review

**Comment by buyaa-n** [comment]
>  I'm potentially interested in working on this but I'd want to be sure of the expected behavior first.

Thanks @madelson, the expected behavior is approved, do you still interested in working on this?

**Comment by madelson** [comment]
@buyaa-n sure I'll try to take a look at it this weekend to get a sense of what is involved.

**Comment by madelson** [comment]
@buyaa-n :

> I believe that should depend on if the bool inherit parameter set, as it is false by default, in this case DerivesFromGenericAttribute should not be included.

I'm a bit confused. Are we talking about the `inherit` parameter on `MemberInfo.GetCustomAttributes(bool)`? That parameter is supposed to determine whether to `to search this member's inheritance chain to find the attributes`; I don't think it affects type-based filtering of the attributes.

For example:
```
typeof(RegexOptions).GetCustomAttributes(typeof(Attribute), inherit: false) // returns the FlagsAttribute
```

What am I missing?

**Comment by buyaa-n** [comment]
You are right, I have mistaken about the parameter. 

In this case the behavior should be same as how it works for non generic attributes, and `Attribute.GetCustomAttributes(,typeof(TestType), typeof(NonGenericAttribute))` returns derived attribute by default
