### ISSUE TITLE
HashData stream one-shots can special case some stream types

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#64173]
The new `HashData` one shots that accept a `Stream` as input can special case some stream types by deferring to the `ReadOnlySpan<byte>` one shots where the stream is known to be backed by contiguous memory. For example, `MemoryStream`'s `TryGetBuffer`.

Doing this would give a few benefits:

1. They would be truly non-allocating.
2. Throughput will be higher since it boils down a single p/invoke (usually) instead of reading from the stream in chunks and updating.

This issue is to track the implementation of that.

**Comment by stephentoub** [comment]
> can special case some stream types

It can.  Should it?  How common will it be to use those streams with this method?

**Comment by vcsjones** [comment]
> It can. Should it?

I think hashing a `MemoryStream` is not uncommon and some places are already making this optimization using `GetBuffer`. Searching GitHub, some examples:

1. https://github.com/ServiceStack/ServiceStack/blob/03391bc1d9ebfca0e7faba3130facc129db9d0af/src/ServiceStack/Auth/JwtAuthProvider.cs#L288
2. https://github.com/nodatime/nodatime/blob/7fd0371b1019154b21d33dddc5e3486cc7c2ccfb/build/HashStorageFiles/Program.cs#L45-L48
3. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dbb701d912a68596783fd0ca322b23075f7d4fd4/src/Microsoft.IdentityModel.Xml/ExclusiveCanonicalizationTransform.cs#L79-L86
4. https://github.com/aspnet/DataProtection/blob/88a191f0f348a1eae467a906048e6adcac5f9cc3/src/Microsoft.AspNetCore.DataProtection/Managed/ManagedAuthenticatedEncryptor.cs#L346-L349


(that's only looking at the first few pages).

I also considered `UnmanagedMemoryStream` which we could do with `PositionPointer`, but I do not think that one is typical. I found zero occurrence of that throughout GitHub. So I don't think that one is worth pursuing.

**Comment by vcsjones** [comment]
I would agree though that the majority of uses are a `FileStream` or some kind of network stream.

**Comment by vcsjones** [comment]
I think my biggest "iffy" on doing this actually is that it will have the observable affect of not advancing the stream if we use `TryGetBuffer`, unless we explicitly set `Position` after using `TryGetBuffer`.

**Comment by stephentoub** [comment]
> I think my biggest "iffy" on doing this actually is that it will have the observable affect of not advancing the stream if we use TryGetBuffer, unless we explicitly set Position after using TryGetBuffer.

You would need to set the position after.  You'd also need to constrain it to exactly typeof(MemoryStream) and not any streams derived from it.

I'm not convinced this is a worthwhile change.  All of the cases you cited involve a client that has a strongly-typed MemoryStream and can just as easily call GetBuffer and call the ROS-based HashData.

**Comment by vcsjones** [comment]
> I'm not convinced this is a worthwhile change. 

Fair enough, I'll close this out then. We can re-open it if any new evidence emerges that this is worth pursuing.
