### ISSUE TITLE
System.Drawing.Primitives (inbox) depends on Microsoft.Win32.SystemEvents (OOB)

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#64196]
I just noticed that System.Drawing.Primitives which is part of the shared framework depends on Microsoft.Win32.SystemEvents which is out-of-band. I thought that the shared framework itself must be closure complete and that there is protection for it in place. Why is this reference allowed and why isn't it flagged? @ericstj @safern 

https://github.com/dotnet/runtime/blob/7435abedcdf4c82a32e2afbafdd05bbc8f11d8ef/src/libraries/System.Drawing.Primitives/src/System.Drawing.Primitives.csproj#L39

![image](https://user-images.githubusercontent.com/7412651/150760414-1b03b2b6-80a6-4a1b-a934-66cbd92c78ed.png)

**Comment by safern** [comment]
>  I thought that the shared framework itself must be closure complete and that there is protection for it in place. Why is this reference allowed and why isn't it flagged? @ericstj @safern

My guess is that since there wasn't any code dependency and no types used from that assembly, the compiler was not emitting that reference into the final DLL and that's why the shared framework tests never caught it.
