### ISSUE TITLE
Improve Buffer.MemoryCopy documentation (or fix a bug)

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#6419]
(1)

The [documentation](https://msdn.microsoft.com/en-us/library/dn823273%28v=vs.110%29.aspx) should be clarified:

> This method copies sourceBytesToCopy bytes from the address specified by source to the address specified by destination. If the buffers overlap and the difference between destination minus source is less than sourceBytesToCopy, the source block is copied to the destination block in reverse order.

It is not clear what reverse order means (I understood that part only because I'm familiar with the overlapping buffers problem with memcpy). Also, "buffers overlap" is unclear because nowhere is it defined what a buffer is. We are talking about ranges of addresses here. Interpreting them as a buffer is out of scope for this API. The wording could be "memory regions specified by `source` and `sourceBytesToCopy` as well as `destination` and `destinationSizeInBytes`". Or it could be what the [native version](https://msdn.microsoft.com/en-us/library/aa246469%28v=vs.60%29.aspx) says.

I would have suggest a text but I wasn't sure if I was causing any licensing issues with that. I'd be willing to contribute a documentation fix if this is helping.

(2) Please clarify what a negative length or a negative destination size cause. Is that valid? What does it do?

(3) I'm actually unclear on what the function is _supposed_ to do. It behaves differently depending on whether src and dest are ascending or descending in memory (where the ranges overlap in both cases). The behavior deviates from native `memmove`. Is this supposed to happen? If no, it's a bug. If yes, the documentation should spell that out.

```
    static unsafe void MemoryCopyTest()
    {
        var bytesToCopy = 3;

        var array1 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 };
        fixed (byte* arrayPtr = array1)
        {
            MemoryCopy(arrayPtr + 2, arrayPtr + 1, bytesToCopy, bytesToCopy);
        }

        Console.WriteLine(BitConverter.ToString(array1));

        var array2 = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 };
        fixed (byte* arrayPtr = array2)
        {
            memmove(arrayPtr + 2, arrayPtr + 1, bytesToCopy);
        }

        Console.WriteLine(BitConverter.ToString(array2));
    }

    [DllImport("msvcrt.dll", SetLastError = false)]
    static unsafe extern IntPtr memmove(void* dest, void* src, int count);
```

> 01-03-04-05-05-06-07-08
> 01-02-02-03-04-06-07-08

The output is different because the check `if ((ulong)dest - (ulong)src < len) goto PInvoke;` is sometimes false, sometimes true. And if it's false the unsafe managed version behaves questionably.

Ideally, the function would mirror `memmove`.

Maybe it's a good solution to call the bytewise managed loop for small overlapping buffers. For big overlapping buffers call the native code.

**Comment by joperezr** [comment]
From what I read above seems like this issue is resolved now so I'll go ahead and close it for now. Feel free to reopen if that is not the case and there is still something we can fix in the documentation side.
