### ISSUE TITLE
ReloadOnChange of AddJsonFile is invalid in kubernetes - not fixed

### ISSUE THREAD

**Issue by grahambunce** [dotnet/runtime#64222]
This issue has been reported as fixed but trying to pick up a new configmap change after it has been applied still does not work in a .net 6.0 web api app. How is the fix meant to be applied? is this meant to be picked up automatically by the .net 6.0 framework?

ReloadOnChange of AddJsonFile is invalid in kubernetes : https://github.com/dotnet/runtime/issues/36091

**Comment by adamsitnik** [comment]
Hi @grahambunce 

Does your project that references `Microsoft.Extensions.*` nuget package targets `netstandard2.0` or `net6.0`?

The fix has been applied only to the `net6.0` version of the library, the `netstandard2.0` does not contain the fix. It was announced [here](https://github.com/dotnet/runtime/issues/36091#issuecomment-879270257) and discussed [here](https://github.com/dotnet/runtime/pull/55664/files#r672935117).

cc @Jozkee

**Comment by grahambunce** [comment]
@adamsitnik Thanks for the update - although my project does reference some .net 5.0 packages, they are not configuration focused. My csproj has:

`	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<RuntimeIdentifiers>alpine-x64</RuntimeIdentifiers>
	</PropertyGroup>`

and appears to be correctly referencing 6.0.0.0 / 6.0.2152210 of Microsoft.Extensions.Configuration.Json through the root Microsoft.AspNetCore.App package.

For context:

` .ConfigureAppConfiguration((hostingContext, config) =>
  {
    config.AddJsonFile(Path.Combine(AppContext.BaseDirectory, "servicemap", "ServiceRouting.json"), false, true);
  })`

Running this locally with a physical file changing the file is detected instantly. Running in K8S, even waiting several minutes for K8S itself to detect the change to the file applied by updating the configmap via kubectl, the app never picks up the change.

Writing my own listener that checksums the file and compares before/after on a timer (one previous fix to this issue in .net 5.0) still works correctly in K8S.

My concern is that although .net 6 fixes symbolic links, it isn't clear how to invoke this behaviour in a .net web app - if indeed a difference in code is necessary. If no change is required then perhaps symbolic links themselves are now supported but the original issue this failing to work correctly in K8S still isn't resolved. Maybe this is a K8S issue now rather than .NET?

**Comment by adamsitnik** [comment]
@grahambunce I've created a repro app based on what you have described:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>alpine-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
  </ItemGroup>
</Project>
```

Published it:

```cmd
dotnet publish -c Release --self-contained
```

And verified with ILSpy that the `Microsoft.Extensions.FileProviders.Physical.dll` put into `bin\Release\net6.0\alpine-x64` contains the fix:

![image](https://user-images.githubusercontent.com/6011991/151150057-48d1ef47-bbd0-464d-8a61-0ea3632582c9.png)

Could you please share the `Microsoft.Extensions.FileProviders.Physical.dll` from your build output directory?

I just want to be 100% sure it's an actual bug in the code.

**Comment by grahambunce** [comment]
@adamsitnik Thanks for this detail - it's really helpful. I'm using dotnetPeek instead of ILSpy.

My Microsoft.Extensions.FileProviders.Physical.dll details are:
File Version: 6.0.21.52210
Product Version: 6.0.0+4822e3c3aa..... (a guid)

the code is listed as:

`        public static DateTime? GetFileLinkTargetLastWriteTimeUtc(string filePath)
        {
#if NETCOREAPP
            var fileInfo = new FileInfo(filePath);
            if (fileInfo.Exists)
            {
                return GetFileLinkTargetLastWriteTimeUtc(fileInfo);
            }
#endif
            return null;
        }

/ If file is a link and link target exists, return target's LastWriteTimeUtc.
        // If file is a link, and link target does not exists, return DateTime.MinValue
        //   since the link's LastWriteTimeUtc doesn't convey anything for this scenario.
        // If file is not a link, return null to inform the caller that file is not a link.
        public static DateTime? GetFileLinkTargetLastWriteTimeUtc(FileInfo fileInfo)
        {
#if NETCOREAPP
            Debug.Assert(fileInfo.Exists);
            if (fileInfo.LinkTarget != null)
            {
                try
                {
                    FileSystemInfo targetInfo = fileInfo.ResolveLinkTarget(returnFinalTarget: true);
                    if (targetInfo != null && targetInfo.Exists)
                    {
                        return targetInfo.LastWriteTimeUtc;
                    }
                }
                catch (FileNotFoundException)
                {
                    // The file ceased to exist between LinkTarget and ResolveLinkTarget.
                }

                return DateTime.MinValue;
            }
#endif

            return null;
        }
`
so pretty much the same except for the compiler directive.

I found this: https://github.com/kubernetes/kubernetes/issues/24215 which is old and this related linkerd issue https://github.com/linkerd/linkerd2/issues/1061 which suggests K8S is not updating the Last Write Time on a change to a configmap so (if still true) any process that depends on that like the code above in K8S will not detect the change.

**Comment by Jozkee** [comment]
> How is the fix meant to be applied?

The way this is supposed to work is: check if changes were made to your config file based on its LastWriteTime (mtime in Unix).
With the fix, if ServiceRouting.json happens to be a symlink, we resolve the link indirection and get the LastWriteTime form the target.

@grahambunce is there a way you could verify if the mtime of the target of your config.json is indeed changing and .NET is not picking it up? 
Alternatively, you can also share steps on how to create a container identical to yours to see if I can repro it and hence fix the issue.

**Comment by grahambunce** [comment]
I will get something together on this in the next few days

**Comment by grahambunce** [comment]
@Jozkee I've created a github project that can be used to replicate this:

https://github.com/grahambunce/K8SConfigMap

docker-commands.txt contain the CMD line options to create the docker container
k8s-commands.txt contain the CMD line options to create the K8S deployment
deployment.yml and configmap.yml contain the K8S YML instructions

Once deployed to K8S I can use:

curl -i  -k "http://localhost:31234/operations/map"

to invoke the URL (in this case I'm running K8S via docker desktop but I get the same situation with AWS EKS). I can then change the configmap, run the apply and wait... the App never reports the change. Running this through the VS debugger (on windows) the code works fine.

Running is a docker container with a mapped volume doesn't work either (the container is Alpine-x64).

Is this because the map is to a [folder]/[filename] ? i.e. the symlink check doesn't work correctly in this scenario?

**Comment by Jozkee** [comment]
@grahambunce thanks for sharing that repo. I have a question about the steps (I'm not very familiar with Docker):

I cloned your repo and ran the commands in docker-commads.txt, so far so good.
When I run the commands in k8s-commands.txt I get this:
```sh
azureuser@forissues:~/K8SConfigMap$ kubectl create namespace ks8-testing
namespace/ks8-testing created
azureuser@forissues:~/K8SConfigMap$ kubectl apply -f configmap.yml -n ks8-testing
configmap/servicemap-config created
azureuser@forissues:~/K8SConfigMap$ kubectl apply -f deployment.yml -n ks8-testing
deployment.apps/k8sconfigmap created
service/k8sconfigmap created
azureuser@forissues:~/K8SConfigMap$ kubectl delete -n retail-services deployment k8sconfigmap
Error from server (NotFound): deployments.apps "k8sconfigmap" not found
azureuser@forissues:~/K8SConfigMap$ curl -i  -k "http://localhost:31234/operations/map"
curl: (7) Failed to connect to localhost port 31234: Connection refused
```

Any ideas? 

But anyways, what I try to understand is when does your config file change in your scenario? Is the change reflected correctly in the target file while in the app is not?

Using your own example, if I do `curl -i  -k "http://localhost:9000/operations/map"` it does report changes correctly (if any), but that case should've worked even before the fix because ServiceRouting.json is not a symlink.

**Comment by grahambunce** [comment]
@Jozkee the last line of the k8s deletes the deployment you have just created (it was added for post-test cleanup) so you should not run that line.

You are correct in the scenario though in k8s you need to update the content in the config map and then re-run the k8s apply config map line in the k8s command line txt file.

It will take a minute or two for K8s to detect the change itself ( I can’t recall the command to get the latest config map content as I use a UI to check this has been written manually) but once it has I’d expect .net to pick this up too but it does not appear to do so.

**Comment by tmds** [comment]
@Jozkee @adamsitnik I see you are already looking into this. Let me know if I can assist.

**Comment by adamsitnik** [comment]
> I see you are already looking into this. Let me know if I can assist.

@tmds thank you Tom! I defer it to @Jozkee as he is the FSW expert and was working on the initial fix.

**Comment by Jozkee** [comment]
@grahambunce I was able to deploy with kubernetes and attached to it with the command `kubectl exec --stdin --tty k8sconfigmap-59d9c87cdd-49ccx --namespace="ks8-testing" -- /bin/sh`.

Then I looked at your app and noted a couple of things:

```
/app # ls -la -R
.:
total 37356
drwxr-xr-x    1 root     root          4096 Feb 23 06:55 .
drwxr-xr-x    1 root     root          4096 Feb 23 06:55 ..
-rwxr-xr-x    1 root     root      38199361 Feb 23 01:31 K8SConfigMap.Api
-rw-r--r--    1 root     root         21648 Feb 23 01:30 K8SConfigMap.Api.pdb
drwxr-xr-x    2 root     root          4096 Feb 23 01:31 ServiceMap
-rw-rw-r--    1 root     root           119 Feb 15 23:07 appsettings.Development.json
-rw-rw-r--    1 root     root           142 Feb 15 23:07 appsettings.json
drwxrwxrwx    3 root     root          4096 Feb 23 06:55 servicemap

./ServiceMap:
total 12
drwxr-xr-x    2 root     root          4096 Feb 23 01:31 .
drwxr-xr-x    1 root     root          4096 Feb 23 06:55 ..
-rw-rw-r--    1 root     root           199 Feb 16 00:13 ServiceRouting.json

./servicemap:
total 12
drwxrwxrwx    3 root     root          4096 Feb 23 06:55 .
drwxr-xr-x    1 root     root          4096 Feb 23 06:55 ..
drwxr-xr-x    2 root     root          4096 Feb 23 06:55 ..2022_02_23_06_55_32.1460167239
lrwxrwxrwx    1 root     root            32 Feb 23 06:55 ..data -> ..2022_02_23_06_55_32.1460167239
lrwxrwxrwx    1 root     root            26 Feb 23 06:55 ServiceRouting.json -> ..data/ServiceRouting.json

./servicemap/..2022_02_23_06_55_32.1460167239:
total 12
drwxr-xr-x    2 root     root          4096 Feb 23 06:55 .
drwxrwxrwx    3 root     root          4096 Feb 23 06:55 ..
-rw-r--r--    1 root     root           200 Feb 23 06:55 ServiceRouting.json
```
1. You have two folders with the same name but different casing ServiceMap and servicemap (worth pointing out).
2. The one I think is used by ASP.NET is servicemap, that one contain ServiceRouting.json as a link (that's aligns with the scenario described in https://github.com/dotnet/runtime/issues/36091).
3.  I followed the link and opened the final file that it points to `/app/servicemap/..2022_02_23_06_55_32.1460167239/ServiceRouting.json` and it its content is the same as the original ServiceRouting.json in your repo.
That basically means that curl -i -k "http://localhost:31234/operations/map" will always returns the same because there are no changes. 
Now why are there no changes? I don't know because I am not a docker-k8s expert, but it looks to me like there is an error in your deployment settings.

@tmds @grahambunce I will close this issue, if there's something I missed, please let me know and re-open.

**Comment by grahambunce** [comment]
@Jozkee i will look at this again in the next few days based on your feedback. If the difference in case made a difference I’d expect it to fail when running as a plain docker container too, but you said it worked as expected in that scenario.

I will update with my results shortly.

**Comment by tmds** [comment]
@grahambunce have you been able to verify this works? or doesn't work?

**Comment by grahambunce** [comment]
@tmds @Jozkee I've gone through this again today. To explain the situation, what I'm doing at each step and what I'd expect to happen.

1) You are correct about the 2 "ServiceMap" folders. The Capitalized one is a result of a file copy when building the container but you are also correct in that this ignored and that the one actually used is the lowercase volume mount "servicemap". However, it is confusing so I have deleted the ServiceMap folder in the docker build file so that the container when running in K8S can only see the mapped folder. Running the new container in K8S and connecting to the shell I can now only see the one ./servicemap

![image](https://user-images.githubusercontent.com/19230473/156531860-a5c55062-ddc4-4249-ad20-4fc53ffdf60b.png)

2) Running curl -i -k "http://localhost:31234/operations/map" against my K8S instance invokes the code that pulls the file from .net configuration, set up like this in program.cs and against the IOptionsMonitor<ServiceRouting> injection

```
        private static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddJsonFile(Path.Combine(AppContext.BaseDirectory, "servicemap", "ServiceRouting.json"), false, true);
                })
                .ConfigureWebHostDefaults(wb =>
                {
                    wb.UseStartup<Startup>();
                });
```

and in OperationsController.cs

```
    [ApiController]
    public class OperationsController : ControllerBase
    {
        private readonly IOptionsMonitor<ServiceRouting> _configuration;

        public OperationsController(IOptionsMonitor<ServiceRouting> configuration)
        {
            _configuration = configuration;
            _configuration.OnChange((sr) =>
            {
                Console.WriteLine("configuration change detected at " + DateTime.Now);
            });

        }

        [HttpGet]
        [Route("/operations/map")]
        public IActionResult GetMap()
        {
            return Ok(_configuration.CurrentValue);
        }
    }
```

The CURL result is:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Mar 2022 09:08:40 GMT
Server: Kestrel
Transfer-Encoding: chunked

{"resolutions":[{"function":"test","service":"test","path":"api/{version}/{data}/method","methods":"GET"}]}
```

3) I then need to change the file contents. As this is a K8S ConfigMap the only way is to change the configmap.yml file and then  run a K8S apply, i.e.

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ks8-testing
  name: servicemap-config
data:
  ServiceRouting.json: |
    {
      "serviceRouting": {
        "resolutions": [
          {
            "function": "test",
            "service": "test",
            "path": "api/{version}/{data}/method",  <== e.g. change this to new-method
            "methods": "GET"
          }
        ]
      }
    }
```

>kubectl apply -f configmap.yml -n k8s-testing
result = configmap/servicemap-config configured

4) K8S can take a while to apply a configmap change but eventually the config mapped file will be different. You can check in the container itself:

![image](https://user-images.githubusercontent.com/19230473/156533708-763469f9-0201-42ab-bffc-67f9d2444bfd.png)

So, as far as the container and K8S is concerned the file content has changed

4) I would expect .net to pick this up and refresh it's configuration but re-running the CURL command indicates that the content is still the same. Checking the logs for the output of this line "Console.WriteLine("configuration change detected at " + DateTime.Now);" does not find any indication that the IOptionsMonitor has picked up the change.

This is unexpected as the container knows the file content is different.

5) If we replace this code

```
 config.AddJsonFile(Path.Combine(AppContext.BaseDirectory, "servicemap", "ServiceRouting.json"), false, true);
```

with this code

```
config.AddJsonFile(new ConfigMapFileProvider(Path.Combine(AppContext.BaseDirectory, "servicemap")), "ServiceRouting.json",false, true);
```

which is custom code (in the project provided) that runs on a timer comparing the actual content of the file via a checksum difference, then this will correctly detect the change and update the configuration for the next invocation of the CURL command and report the change in the log.

If I restart the pod then the configuration reported by the CURL command is correct.

I'm not really saying that the underlying .net code change is wrong, what I'm saying is that the original code change was applied to a ticket that explicitly referred to config maps in K8S and stated it as "fixed", when it doesn't appear to fix that issue at all.

**Comment by tmds** [comment]
Yes, I think this API is meant to work on Kubernetes. I'll take a closer look.

**Comment by tmds** [comment]
@grahambunce I took your app, and ran it on OpenShift. It worked for me.

I did make a few changes to make it easier for me to deploy the app.

- https://github.com/tmds/K8SConfigMap/commit/71052132f73ccda443fb7346c4d7bed8bca12921

- I didn't use the Dockerfile, and built the app on OpenShift using the [.NET 6.0 UBI8 image](https://catalog.redhat.com/software/containers/ubi8/dotnet-60/6182efb9be25a74c00923849).

- I changed the path of the service map corresponding to the OpenShift s2i build:
```
          volumeMounts:
            - name: servicemap-volume
              readOnly: true
              mountPath: /opt/app-root/app/servicemap
```

On Kubernetes, the implementation uses polling triggered by the `DOTNET_USE_POLLING_FILE_WATCHER=true` envvar. Due to this polling, it takes a while longer for .NET to pick up the changes.

Maybe if you look at what I changed, you can figure out why it is not working for you.

**Comment by grahambunce** [comment]
@tmds ok - I will have a look tomorrow

**Comment by grahambunce** [comment]
@tmds I can confirm that the only change needed is this

> On Kubernetes, the implementation uses polling triggered by the DOTNET_USE_POLLING_FILE_WATCHER=true envvar. Due to this polling, it takes a while longer for .NET to pick up the changes.

I'm not sure if this is referenced anywhere in documentation (it may be, but I may have missed it). Checking the original issue, which contains a large number of comments, I can now see that this setting is mentioned by David Fowler about half way through but it is immediately followed by a "this does not work comment". 

The ticket is closed with a reference to the changeset done by @Jozkee but there isn't a mention that the above ENV setting is still required in K8S - it would be helpful to annotate that ticket with this fact too for others who come across this issue if that is possible?

**Comment by tmds** [comment]
@grahambunce can you create an issue in https://github.com/dotnet/dotnet-docker for this envvar not being set in the Microsoft image you are using?

> Thank you for digging into this though, I'd have been stuck otherwise I suspect.

No problem!

**Comment by jkotalik** [comment]
Related, running on k3d and M1 macOS:
```
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

@tmds any idea what could be going on here?

**Comment by tmds** [comment]
My guess is that qemu doesn't support inotify, which causes:

> Unhandled exception. System.IO.IOException: Function not implemented

Is `DOTNET_USE_POLLING_FILE_WATCHER=true` set in your container? That should stop it from using inotify.
