### ISSUE TITLE
[wasm][windows] v8 doesn't seem to exit sometimes causing helix test run to time out

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64227]
Two recent instances of this seen on rolling builds:

[System.Text.RegularExpressions.Generators.Tests](
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d5801f5d29f445a3b4/normal-System.Text.RegularExpressions.Generators.Tests.Attempt.2/1/console.cbecce41.log?sv=2019-07-07&se=2022-02-10T22%3A29%3A54Z&sr=c&sp=rl&sig=s%2FxCV8IW69kY0PjRaSyspo71Z8AAd2Usw6vatd%2B9yGA%3D)

```
01:04:48] info: Received expected 378 of C:\helix\work\workitem\uploads\xharness-output\testResults.xml
[01:04:48] info: Finished writing 378 bytes of RESULTXML
[01:04:48] info: Xml file was written to the provided writer.
[01:04:48] info: Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0 Skipped: 0

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 3600 seconds and was killed

['normal-System.Text.RegularExpressions.Generators.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

[Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f80e7c723f554fc89c/normal-Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests/1/console.785831da.log?sv=2019-07-07&se=2022-02-12T22%3A06%3A55Z&sr=c&sp=rl&sig=DVRI4m45pJaw8lPmZJhWFLMKylGKqPzaA%2FmHARCLcjw%3D)

```
[23:13:33] info: Received expected 387 of C:\helix\work\workitem\uploads\xharness-output\testResults.xml
[23:13:33] info: Finished writing 387 bytes of RESULTXML
[23:13:33] info: Xml file was written to the provided writer.
[23:13:33] info: Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0 Skipped: 0

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 3600 seconds and was killed

['normal-Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

cc @pavelsavara @radekdoulik

**Comment by lewing** [comment]
That sounds like the task queue isn't empty, @maraf could you take a look at this.

**Comment by maraf** [comment]
Some findouts
- Windows AOT and v8 only (other scenarios don't run on Windows AOT).
- 0 tests run in both projects.

**Comment by radical** [comment]
Hit again on a rolling build - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-06a2b5c99cde42688b/normal-System.Text.RegularExpressions.Generators.Tests.Attempt.3/1/console.4a785ba6.log?sv=2019-07-07&se=2022-02-23T22%3A27%3A38Z&sr=c&sp=rl&sig=X5CSYRGPDL3DzCbQ4y88vWxCAUcnwQoNydZLyQ4ReSg%3D

**Comment by pavelsavara** [comment]
I saw similar behavior on local build with broken wasm binary. I think some wasm code was running tight loop over some data.
I think in my case it was pointer to char* which pointed to DLL metadata instead of the string I wanted to convert from utf8. So the time was linear with size of the data.
I recommend to try to use profiler or attach debugger to see what is running.
Also allocation patter could be useful. If it's allocating something in JS, it means it's running JS. Otherwise it could be just wasm loop.

**Comment by ilonatommy** [comment]
> I saw similar behavior on local build with broken wasm binary. I think some wasm code was running tight loop over some data. I think in my case it was pointer to char* which pointed to DLL metadata instead of the string I wanted to convert from utf8. So the time was linear with size of the data. I recommend to try to use profiler or attach debugger to see what is running. Also allocation patter could be useful. If it's allocating something in JS, it means it's running JS. Otherwise it could be just wasm loop.

@maraf, this suggestion sounds helpful, have you tried it? What's the result?

**Comment by maraf** [comment]
Moving to 8.0 as this isn't currently blocking us.
