### ISSUE TITLE
[API Proposal]: RequiredMemberAttribute and NoRequiredMembersAttribute

### ISSUE THREAD

**Issue by 333fred** [dotnet/runtime#64248]
### Background and motivation

As part of supporting C# 11's [Required Members](https://github.com/dotnet/csharplang/blob/main/proposals/required-members.md) feature, we need two new attributes: `RequiredMemberAttribute` and `NoRequiredMembersAttribute`. They work as follows:

* `RequiredMemberAttribute` will be applied to every type (class or struct) that defines required members, and to all the members (fields or properties) that are required by that type.
* `NoRequiredMembersAttribute` will be applied to a constructor of a type that has required members, and then users of that constructor will not be required to set any members of the type when calling it. Think copy constructors for records: this is how they will communicate that calling the constructor does not require setting any members, because all members will have been set by the copy constructor itself.

### API Proposal

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Field | AttributeTargets.Property)]
    public sealed class RequiredMemberAttribute : Attribute { }
}
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.Constructor)]
    public sealed class NoRequiredMembersAttribute  : Attribute { }
}
```

### API Usage

`RequiredMemberAttribute` will not be manually usable. It will be an error to apply it to C# code by hand.

A copy constructor for a type that has required members might look like this:

```cs
public class C
{
    public required int Property { get; init; }
    public C() {}

    [NoRequiredMembers]
    public C(C c) => this.Property = c.Property;
}


// Usage
var c1 = new C { Property = 1 };
var c2 = new C(c1); // No error, constructor waives requirements
```

### Alternative Designs

I am open to alternative naming schemes. We had also considered a version of `RequiredMemberAttribute` where all the members were listed by name as a string argument to the constructor, but we redesigned after some community feedback and consultation with Wrighton to make sure that more attributes wouldn't break perf.

**Comment by stephentoub** [comment]
@333fred, you didn't specify AllowMultiple or Inherited, which means these would be AllowMultiple=false and Inherited=true.  Is that the intention?  I assume "yes", just double checking.

**Comment by stephentoub** [comment]
@333fred, I believe we discussed this, but for `NoRequiredMembersAttribute will be applied to a constructor of a type that has required members, and then users of that constructor will not be required to set any members of the type when calling it`, this is an all-or-nothing approach.  Are there no scenarios where the ctor itself supplies some but not all of the required members, thus making some not required but others still required?
