### ISSUE TITLE
Performance degradation when using property-init over constructor on record-struct

### ISSUE THREAD

**Issue by Turnerj** [dotnet/runtime#64257]
### Description

(I don't know how best to describe it in the title so please edit as appropriate)

I'm seeing a large difference in performance of my code depending how I define some initial properties on a record-struct. Take the code below from [a benchmark in an OSS library I'm working on](https://github.com/TurnerSoftware/Vibrancy/blob/ctor-vs-init/benchmarks/TurnerSoftware.Vibrancy.Benchmarks/CtorVsInitBenchmark.cs).

```csharp
public class CtorVsInitBenchmark
{
	public Image<Rgb24>? TestImage = Image.Load<Rgb24>(@"resources/1-small.jpg");

	public readonly Palette Palette = new(new PaletteOptions(new[]
	{
		SwatchDefinition.DarkVibrant,
		SwatchDefinition.Vibrant,
		SwatchDefinition.LightVibrant,
		SwatchDefinition.DarkMuted,
		SwatchDefinition.Muted,
		SwatchDefinition.LightMuted
	}));
	public readonly Palette Palette2 = new(new PaletteOptions()
	{
		Definitions = new[]
		{
			SwatchDefinition.DarkVibrant,
			SwatchDefinition.Vibrant,
			SwatchDefinition.LightVibrant,
			SwatchDefinition.DarkMuted,
			SwatchDefinition.Muted,
			SwatchDefinition.LightMuted
		}
	});

	[Benchmark]
	public IReadOnlyList<Swatch> Fast() => Palette.GetSwatches(TestImage!);
	[Benchmark]
	public IReadOnlyList<Swatch> Slow() => Palette2.GetSwatches(TestImage!);
}
```

And the type `PaletteOptions`

```csharp
public readonly record struct PaletteOptions(SwatchDefinition[] Definitions, float MinimumColorDelta = 25f);
```

That difference in setting up the `PaletteOptions` type had this impact on performance and allocations:

| Method |       Mean |     Error |    StdDev | Code Size | Allocated |
|------- |-----------:|----------:|----------:|----------:|----------:|
|   Fast |   3.504 ms | 0.0441 ms | 0.0412 ms |      6 KB |     12 KB |
|   Slow | 349.530 ms | 4.7521 ms | 4.2126 ms |      6 KB |  1,513 KB |

The types `Palette`, `PaletteOptions` and `SwatchDefinition` are all record-structs. If I change `PaletteOptions` to a record-class, I don't experience this issue at all. Maybe that is the crux of it - I'm just using record-struct wrong/inappropriately but as far as I understood, what I'm doing is correct and valid.

Unfortunately I haven't been able to create a smaller example outside of referencing my code.
To recreate the result then:
1. Open up the solution here: https://github.com/TurnerSoftware/Vibrancy/tree/ctor-vs-init
2. Run the `TurnerSoftware.Vibrancy.Benchmarks` project, specifically the `CtorVsInitBenchmark`

### Configuration

```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1466 (21H1/May2021Update)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100
  [Host]   : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  .NET 6.0 : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT

Job=.NET 6.0  Runtime=.NET 6.0
```

### Regression?

My library targets .NET 6 and uses record-structs so I can't easily target previous versions.

### Data

| Method |       Mean |     Error |    StdDev | Code Size | Allocated |
|------- |-----------:|----------:|----------:|----------:|----------:|
|   Fast |   3.504 ms | 0.0441 ms | 0.0412 ms |      6 KB |     12 KB |
|   Slow | 349.530 ms | 4.7521 ms | 4.2126 ms |      6 KB |  1,513 KB |

### Analysis

Initially once I narrowed the performance hit down to whether I use the constructor vs property-init, I thought maybe the issue was just excessive struct copying. Once I got the benchmark working, I was surprised that it was allocating significantly more too.

I looked at the assembly output of the benchmark (if you run the benchmark, you'll get the asm output too) and noted only two majors changes - the first being the call to the benchmark itself being quite different yet the C# code is practically identical. As much as I can roughly follow through with the additional assembly instructions in the "Slow" path, I don't understand _why_ they are there.

**Fast**
```assembly
; TurnerSoftware.Vibrancy.Benchmarks.CtorVsInitBenchmark.Fast()
       mov       [rsp+8],rcx
       add       rcx,10
       mov       rdx,[rsp+8]
       mov       rdx,[rdx+8]
       jmp       near ptr TurnerSoftware.Vibrancy.Palette.GetSwatches(SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgb24>)
; Total bytes of code 23
```

**Slow**
```assembly
; TurnerSoftware.Vibrancy.Benchmarks.CtorVsInitBenchmark.Slow()
       push      rbp
       sub       rsp,20
       lea       rbp,[rsp+20]
       mov       [rbp+10],rcx
       mov       rcx,[rbp+10]
       cmp       [rcx],ecx
       mov       rcx,[rbp+10]
       add       rcx,20
       mov       rdx,[rbp+10]
       mov       rdx,[rdx+8]
       call      TurnerSoftware.Vibrancy.Palette.GetSwatches(SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgb24>)
       nop
       add       rsp,20
       pop       rbp
       ret
; Total bytes of code 48
```

The second change I found wasn't even in my code which I thought was strange (apparently it is the constructor for `List<T>`). The change is significant in terms of additional instructions but it is the "fast" version with more instructions. I don't know if it is relevant but I do know the difference disappears if I use record-class for `PaletteOptions`.

**Fast**
```assembly
; System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib]]..ctor(Int32)
       push      rdi
       push      rsi
       sub       rsp,38
       mov       [rsp+30],rcx
       mov       rdi,rcx
       mov       esi,edx
       test      esi,esi
       jl        near ptr M02_L05
       test      esi,esi
       je        short M02_L00
       mov       rcx,[rdi]
       mov       rdx,[rcx+30]
       mov       rdx,[rdx]
       mov       rdx,[rdx+48]
       test      rdx,rdx
       je        short M02_L03
       mov       [rsp+28],rdx
       jmp       short M02_L04
M02_L00:
       mov       rcx,[rdi]
       mov       rdx,[rcx+30]
       mov       rdx,[rdx]
       mov       rdx,[rdx+50]
       test      rdx,rdx
       je        short M02_L01
       jmp       short M02_L02
M02_L01:
       mov       rdx,7FF951888370
       call      CORINFO_HELP_RUNTIMEHANDLE_CLASS
       mov       rdx,rax
M02_L02:
       mov       rcx,rdx
       call      CORINFO_HELP_GETGENERICS_GCSTATIC_BASE
       mov       rdx,[rax]
       lea       rcx,[rdi+8]
       call      CORINFO_HELP_ASSIGN_REF
       nop
       add       rsp,38
       pop       rsi
       pop       rdi
       ret
M02_L03:
       mov       rdx,7FF951888368
       call      CORINFO_HELP_RUNTIMEHANDLE_CLASS
       mov       [rsp+28],rax
M02_L04:
       movsxd    rdx,esi
       mov       rcx,[rsp+28]
       call      CORINFO_HELP_NEWARR_1_OBJ
       lea       rcx,[rdi+8]
       mov       rdx,rax
       call      CORINFO_HELP_ASSIGN_REF
       nop
       add       rsp,38
       pop       rsi
       pop       rdi
       ret
M02_L05:
       mov       ecx,16
       mov       edx,0B
       call      System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
       int       3
; Total bytes of code 190
```

**Slow**
```assembly
; System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib]]..ctor(Int32)
       push      rdi
       push      rsi
       sub       rsp,28
       mov       [rsp+20],rcx
       mov       rdi,rcx
       mov       esi,edx
       test      esi,esi
       jl        short M02_L01
       test      esi,esi
       je        short M02_L00
       mov       rcx,[rdi]
       call      qword ptr [7FF9AF2BF688]
       mov       rcx,rax
       movsxd    rdx,esi
       call      qword ptr [7FF9AF2BD620]
       lea       rcx,[rdi+8]
       mov       rdx,rax
       call      qword ptr [7FF9AF2BD588]
       nop
       add       rsp,28
       pop       rsi
       pop       rdi
       ret
M02_L00:
       mov       rcx,[rdi]
       call      qword ptr [7FF9AF2BF240]
       mov       rcx,rax
       call      qword ptr [7FF9AF2BD638]
       mov       rdx,[rax]
       lea       rcx,[rdi+8]
       call      qword ptr [7FF9AF2BD588]
       nop
       add       rsp,28
       pop       rsi
       pop       rdi
       ret
M02_L01:
       mov       ecx,16
       mov       edx,0B
       call      qword ptr [7FF9AF2BA098]
       int       3
; Total bytes of code 122
```

**Comment by EgorBo** [comment]
@Turnerj your `Palette` and `Palette2` objects aren't the same - that's the difference, you don't call constructor for `Palette2` hence you don't set `MinimumColorDelta` to `25.0f`

**Comment by Turnerj** [comment]
That makes a lot of sense and yeah, that explains everything in both performance and allocations as the value delta would end up affecting multiple points of the calculation.

Thanks for point that out! Annoying that I missed that...
