### ISSUE TITLE
<MonoAOTCompiler/> fails on F# projects due to satellite assemblies

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#64269]
### Description

In https://github.com/xamarin/xamarin-android/pull/6547, I was working on enabling AOT by default for Release builds.

This following test started to fail:

https://github.com/xamarin/xamarin-android/blob/87589c1507c211f50ed175e749a162f3a071d636/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest2.cs#L276

```
C:\Users\jopepper\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\targets\Microsoft.Android.Sdk.Aot.targets(74,5): Precompiling failed for C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\obj\Release\android-arm\aot-in\FSharp.Core.resources.dll.
AOT of image obj\Release\android-arm\aot-in\FSharp.Core.resources.dll failed.
Mono Ahead of Time compiler - compiling assembly C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\obj\Release\android-arm\aot-in\FSharp.Core.resources.dll
AOTID 302CA46D-4000-DCAD-1A9F-642D849470DE
Using profile data file 'C:\Users\jopepper\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\targets\dotnet.aotprofile'
Added 0 methods from profile.
Compiled: 0/0
Executing the native assembler: "C:\Users\jopepper\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\tools\binutils\arm-linux-androideabi-as"   -mfpu=vfp3 -o obj\Release\android-arm\aot\armeabi-v7a\FSharp.Core.resources\temp.s.o obj\Release\android-arm\aot\armeabi-v7a\FSharp.Core.resources\temp.s
Executing the native linker: "C:\Users\jopepper\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\tools\binutils\arm-linux-androideabi-ld" -Bsymbolic -shared -o obj\Release\android-arm\aot\FSharp.Core.resources.dll.so.tmp  obj\Release\android-arm\aot\armeabi-v7a\FSharp.Core.resources\temp.s.o 
Stripping the binary: "C:\Users\jopepper\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.dotnet-release-aot-by-default.36\tools\binutils\arm-linux-androideabi-strip" --strip-symbol=\$a --strip-symbol=\$d obj\Release\android-arm\aot\FSharp.Core.resources.dll.so.tmp [C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\UnnamedProject.fsproj]
```

I think what's happening is the various `FSharp.Core.resources.dll` have different values for `%(DestinationSubPath)` and `%(DestinationSubDirectory)`:

![image](https://user-images.githubusercontent.com/840039/151000296-839fa2a3-d81b-4d4a-a476-6870f9c5669b.png)

Maybe the folder used for `aot-in` needs to append `%(DestinationSubDirectory)`?

### Reproduction Steps

Test project with `.binlog` inside: [BuildBasicApplicationFSharpTrue.zip](https://github.com/dotnet/runtime/files/7934522/BuildBasicApplicationFSharpTrue.zip)

### Expected behavior

You can use AOT with F# projects, or projects using satellite assemblies.

### Actual behavior

Satellite assemblies with files of the same name, seem to cause a build failure.

### Regression?

I think this was probably always broken, and we hadn't noticed yet?

Or somehow started after using `WorkingDirectory` introduced in: b2f0441ce050f5e3e24bf22fd8801cb83a66cbcd

### Configuration

6.0.200-preview.22063.5

**Comment by radical** [comment]
```
error : Assembler messages: [C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharp
True\UnnamedProject.fsproj]
error : Error: can't open obj\Release\android-arm64\aot\arm64-v8a\FSharp.Core.resources\temp.s for reading: No such file or directory [C:\src\xamarin-android\bin\TestDebug\temp\BuildBasicApplicationFSharpTrue\UnnamedProject.fsproj]
```

IIUC, this is failing because there was nothing in the satellite assembly to AOT. For wasm, we don't pass the satellite assemblies to `MonoAOTCompiler`. I think you need to do the same thing.

Since, nothing would be referencing the satellite assemblies via an AsmRef, they shouldn't be needed for AOT'ing the other assemblies.
