### ISSUE TITLE
Update when Vector256<T>.IsHardwareAccelerated returns true

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#64309]
As outlined by @tannergooding in https://github.com/dotnet/runtime/pull/63285#discussion_r787187495, we need to:

> update Vector256<T>.IsHardwareAccelerated to only return true on AVX2+ where both floating-point and integer operations can be accelerated using "single instructions

These uses of Avx2.IsSupported then need to be changed to Vector256.IsHardwareAccelerated:

https://github.com/dotnet/runtime/blob/518548b96b3369ceb3c54dd62e6cf55e2c5a4ce3/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs#L67
https://github.com/dotnet/runtime/blob/518548b96b3369ceb3c54dd62e6cf55e2c5a4ce3/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Byte.cs#L215
https://github.com/dotnet/runtime/blob/518548b96b3369ceb3c54dd62e6cf55e2c5a4ce3/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Char.cs#L73
https://github.com/dotnet/runtime/blob/518548b96b3369ceb3c54dd62e6cf55e2c5a4ce3/src/libraries/System.Private.CoreLib/src/System/SpanHelpers.Char.cs#L234

cc: @EgorBo

**Comment by danmoseley** [comment]
As a general matter is it our goal that we eliminate essentially all usage of System.Runtime.Intrinsics.Arm and System.Runtime.Intrinsics.X86 namespaces in our repo? Not sure what we use on there that would remain necessary if we fully used the new types.

**Comment by tannergooding** [comment]
> As a general matter is it our goal that we eliminate essentially all usage of System.Runtime.Intrinsics.Arm and System.Runtime.Intrinsics.X86 namespaces in our repo

Not strictly no. There are likely places still where we can get extra perf out, and where said perf is warranted, by utilizing the platform specific APIs in coordination with the xplat helper APIs.

That said, it will really be a case by case basis overall and the goal is that most shared logic that is currently duplicated can be simplified to a single path instead.
