### ISSUE TITLE
PipeWriterStream.DisposeAsync should call CompleteAsync on the underlying pipe writer

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#64326]
### Description

The `PipeWriterStream` class from `System.IO.Pipelines` is used to implement `PipeWriter.AsStream()`. It doesn't override `DisposeAsync` to call `CompleteAsync` on the underlying `PipeWriter`. As a consequence, calling `stream.DisposeAsync()` might block if the `Complete` implementation of the underlying `PipeWriter` blocks.

Also, the implementation of `PipeWriterStream.Dispose` assumes `_pipeWriter.Complete();` doesn't throw. Is it a safe assumption and shouldn't it try/catch exceptions to ensure the stream resources are released no matter what?

Similarly, `StreamPipeWriter.Complete/CompleteAsync` methods don't call `InnerStream.Dispose()` in the case where `FlushAsyncInternal` throws.

### Reproduction Steps

```
using System;
using System.IO.Pipelines;
using System.Threading;
using System.Threading.Tasks;

class CustomPipeWriter : PipeWriter
{
    public override void Complete(Exception? exception = null) =>
        Console.Out.WriteLine("Complete called");

    public override async ValueTask CompleteAsync(Exception? exception = null) =>
        await Console.Out.WriteLineAsync("CompleteAsync called");

    public override void Advance(int bytes) => throw new NotImplementedException();
    public override void CancelPendingFlush() => throw new NotImplementedException();
    public override ValueTask<FlushResult> FlushAsync(CancellationToken cancellationToken = default) => throw new NotImplementedException();
    public override Memory<byte> GetMemory(int sizeHint = 0) => throw new NotImplementedException();
    public override Span<byte> GetSpan(int sizeHint = 0) => throw new NotImplementedException();
}

public class Program
{
	static public async Task Main()
	{
		var writer = new CustomPipeWriter();
		var stream = writer.AsStream();
		await stream.DisposeAsync();
	}
}
```

### Expected behavior

I expect `CompleteAsync called` to be printed out.

### Actual behavior

It prints `CompleteAsync called`

**Comment by adityamandaleeka** [comment]
@wtgodbe PTAL

**Comment by wtgodbe** [comment]
Thanks for reporting, I have a PR to fix this here: https://github.com/dotnet/runtime/pull/64547

**Comment by bentoi** [comment]
Thanks!

Regarding this other issue regarding `StreamPipeWriter` and not `PipeWriterStream`:

> Similarly, StreamPipeWriter.Complete/CompleteAsync methods don't call InnerStream.Dispose() in the case where FlushAsyncInternal throws.

See https://github.com/dotnet/runtime/blob/8447c80431f091c1eb51a1468dce7638d13f7e1a/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/StreamPipeWriter.cs#L240

Should I open a separate issue?

**Comment by wtgodbe** [comment]
> Should I open a separate issue?

That'd be good, and you can assign that one to me as well
