### ISSUE TITLE
[QUIC] ClientAuthenticationOptions.ClientAuthenticationOptions should provide some defaults

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#64332]
When creating a new `QuicConnection`, one must specify `ClientAuthenticationOptions` even though they are nullable on the options class:
https://github.com/dotnet/runtime/blob/12da7826e7235d9ffde336b9c41123182069b7ac/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicClientConnectionOptions.cs#L16

If not, the ctor will fail with:
```
System.Exception : At least one SslApplicationProtocol value must be present in SslClientAuthenticationOptions or SslServerAuthenticationOptions.
```

Or the property shouldn't be nullable.

**Comment by wfurt** [comment]
I don't know if ALPN is truly mandatory or if this is just requirement of MsQuic. We _could_ possibly create overload with just the ALPN if needed. 

I bump to ALPN when looking at https://github.com/dotnet/runtime/issues/49587. With the callback, we may know the ALPN only after we received Hello from client.  

cc: @nibanks

**Comment by nibanks** [comment]
ALPN is mandatory.

**Comment by ManickaP** [comment]
ALPN moved to server options, closing as covered by https://github.com/dotnet/runtime/issues/67560
