### ISSUE TITLE
NativeAOT for osx-arm64

### ISSUE THREAD

**Issue by delneg** [dotnet/runtime#64337]
Hello,
I've tried to build my app with NativeAOT for osx-arm64, but it says that it's not supported:
`.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/build/Microsoft.NETCore.Native.Publish.targets(66,5): error : Native compilation does not support targeting osx-arm64 yet. https://github.com/dotnet/corert/issues/4589`
The issue links to "CoreRT" which seems to be archived and no other info is present.
What's the status for it for .NET 7, how can I compile my app with NativeAOT for M1 Mac ?

**Comment by tgjones** [comment]
@MichalStrehovsky do the milestone changes above imply that NativeAOT support for M1 Mac is not currently on the roadmap for .NET 7?

**Comment by kant2002** [comment]
I think some interesting development happens here https://github.com/dotnet/runtime/issues/67232

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky do the milestone changes above imply that NativeAOT support for M1 Mac is not currently on the roadmap for .NET 7?

It's not currently funded on the Microsoft side but if the community helps getting it there, it might make it into .NET 7. There is some progress towards that - see the issue @kant2002 pointed to.

**Comment by agocke** [comment]
Yup, unfortunately we don't have enough resources to commit to it for .NET 7, but would accept external contributions if they come in.
