### ISSUE TITLE
Add ReadMe to NuGet packages

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/runtime#64342]
NuGet has supported displaying a `ReadMe.md` file contained in a package since last May. The .NET libraries should set an example and contain a ReadMe.md file in the packages. The readme would likely contain links to other resources we aleady have on getting started, support, etc. 

See https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/ for details on how to add the ReadMe.md file to a package.

/cc @chgill-MSFT

**Comment by madelson** [comment]
This would be great so long as the content is package-specific and not just generic .net content/links.

**Comment by carlossanlop** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/59630
