### ISSUE TITLE
[wasm] crash in the browser-bench sample with AOT

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#64343]
browser-bench sample built with current main (dd59ab044b0aaf7f7a81f4dba92c244825874fee) crashes during run with:
```
* Assertion at C:/Users/rodo/git/wa-bench/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

mono_wasm_trace_logger @ dotnet.js:3
```

It looks like an AOT specific issue, the sample built without AOT runs ok.

**Comment by vargaz** [comment]
Can't reproduce this.

**Comment by radekdoulik** [comment]
I can reproduce it on Ubuntu and Windows. I run it like this:
` ../../../../../dotnet.sh build -c Release -p:RunAOTCompilation=true /t:RunSample Console/Wasm.Console.Bench.Sample.csproj`
and
`..\..\..\..\..\dotnet.cmd build -c Release -p:RunAOTCompilation=true /t:RunSample Console\Wasm.Console.Bench.Sample.csproj`
