### ISSUE TITLE
Test failure CancelKeyPressTests.ExitDetectionNotBlockedByHandler

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64364]
Run:[ runtime-coreclr libraries-jitstress 20220125.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1572896&view=ms.vss-test-web.build-test-results-tab&runId=44171866&resultId=145844&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_checked-tailcallstress-Ubuntu.1804.Amd64.Open

- CancelKeyPressTests.ExitDetectionNotBlockedByHandler

```
**Error message:**
```
Exit code was 42 but it should have been 130
Expected: True
Actual:   False


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 239
   at CancelKeyPressTests.ExitDetectionNotBlockedByHandler() in /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs:line 54
```

**Comment by stephentoub** [comment]
@elinor-fung, seems like this is likely related to the RemoteInvoke changes?

**Comment by elinor-fung** [comment]
Indeed - that test wasn't checking the exit code at all before and now it is checking that it is 130. Seems to only be with jitstress / tailcallstress? I'm not finding failures in other runs.

**Comment by danmoseley** [comment]
It is failing consistency on all Unix:


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-2d)
//| where Result == "Fail"
| where  Method == "ExitDetectionNotBlockedByHandler"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
  Test = Type1,
  Result,Finished,Started,
  Duration,
  Method,
  Build = tostring(parse_json(Properties).BuildNumber),
  Message
| where Started >= datetime(2022-01-26 09:02:13.2430000)
  | summarize count() by Pipeline_Configuration, OS, Build, Result, Message//, Started
```

|Pipeline_Configuration|OS|Build|Result|Message|count_|
|---|---|---|---|---|---|
|Debug|redhat.7.amd64.open.rt|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|1|
|Debug|ubuntu.1804.amd64.open.rt|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|5|
|Debug|ubuntu.1804.armarch.open|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|3|
|Debug|ubuntu.1604.amd64.open.rt|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|1|
|Debug|osx.1015.amd64.open|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|1|
|Debug|osx.1014.amd64.open|20220126.44|Fail|Exit code was 134 but it should have been 130<br>Expected: True<br>Actual:   False|1|
|Release|ubuntu.1804.amd64.open.rt|20220125.1|Fail|Exit code was 42 but it should have been 130<br>Expected: True<br>Actual:   False|1|

**Comment by danmoseley** [comment]
134= SIGABRT -- assertion failure. 130 = SIGINT = ctrl-c. 42 = success.

Looking at the code, I think I'd expect it to return 130, as it doesn't Cancel in the Ctrl-C handler.
https://github.com/danmoseley/runtime/blob/5cc3a1ed72d4351dde4190d7fbb3bb7939b00b47/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs#L60

@stephentoub is it obvious to you what's going on?

**Comment by stephentoub** [comment]
The end of the delegate is unblocking the CancelKeyPress and then returning:
https://github.com/danmoseley/runtime/blob/5cc3a1ed72d4351dde4190d7fbb3bb7939b00b47/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs#L80
I suspect it's a race condition between the process exiting because that delegate returned, in which case it'll exit with 42, or the process exiting because the CancelKeyPress handler returned and allowed cancellation to be propagated (asynchronously), and the main delegate normally wins.  Hence 42 being returned.

**Comment by elinor-fung** [comment]
> It is failing consistency on all Unix

The SIGABRT/134 failures from build 20220126.44 look like legitimate failures from that PR, so I think this issue is just the success/42 with the potential race that @stephentoub pointed out.

**Comment by danmoseley** [comment]
Ah! I overlooked that the 134's were on some PR. Yes, then the theory makes sense.
