### ISSUE TITLE
Ssl3 tests failing on Windows 11

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#64372]
This was originally reported by @antonfirsov 
Let say somebody want `Ssl3` and modifies registry according to documentation.
Our tests would fail because `PlatformDetection.SupportsSsl3` is incorrectly set to true.
The platform detection ignores fact that all weak cipher suites were disabled in Windows 11:
https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-11

We would need to make it smarter or actually try the `Ssl3` handshake.

now, let say somebody also enables some weaker set:
```
Enable-TlsCipherSuite TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
```
 
Some our tests would still fail. This is because by default we would use new crypto API and SCHANNEL does not seems to like `Ssl3` and `Tls13` together. To pass the tests, one must also disable `Tls13` in registry. This could be viewed as product bug but I'm not sure there is much we can do about it. 

I'm not sure how much we care. I'm primarily writing this up for visibility in case somebody else bumps to this.

**Comment by karelz** [comment]
Triage: This is limitation of the OS. SSL3 is old and discouraged to be used, so not worth spending further effort.
Closing.
