### ISSUE TITLE
ArrayList.ToArray(type) throws exception for enum type in Blazor WebAssembly

### ISSUE THREAD

**Issue by jjzhang12** [dotnet/runtime#64387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Code snippet:

ArrayList list = new ArrayList();
list.Add(Day.Monday);
var array = list.ToArray(typeof(Day));

public enum Day { Monday, Tuesday }

This is working fine in .net 6 desktop. But in Blazor WebAssembly, it throws exception System.InvalidCastException: At least one element in the source array could not be cast down to the destination array type.

list.ToArray() without type is fine. But we are using type which is loaded in runtime, so the type is required.

### Expected Behavior

Array created without exception

### Steps To Reproduce

https://github.com/jjzhang12/WasmToArrayIssue.git

I added above code snippet to index page and you can observe the exception.

Also the .net console app is working fine.

### Exceptions (if any)

System.InvalidCastException: At least one element in the source array could not be cast down to the destination array type.

### .NET Version

6.0.101

**Comment by lewing** [comment]
cc @vargaz

**Comment by lewing** [comment]
```
System.InvalidCastException: InvalidCast_DownCastArrayElement
dotnet.js:13    at System.Array.CopySlow(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) in /Users/lewing/Source/backup/runtime/src/mono/System.Private.CoreLib/src/System/Array.Mono.cs:line 203
dotnet.js:13    at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable) in /Users/lewing/Source/backup/runtime/src/mono/System.Private.CoreLib/src/System/Array.Mono.cs:line 147
dotnet.js:13    at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length) in /Users/lewing/Source/backup/runtime/src/mono/System.Private.CoreLib/src/System/Array.Mono.cs:line 121
dotnet.js:13    at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length) in /Users/lewing/Source/backup/runtime/src/mono/System.Private.CoreLib/src/System/Array.Mono.cs:line 115
dotnet.js:13    at System.Collections.ArrayList.ToArray(Type type) in /Users/lewing/Source/backup/runtime/src/libraries/System.Private.CoreLib/src/System/Collections/ArrayList.cs:line 727
```

**Comment by lambdageek** [comment]
It's hitting this check added by https://github.com/mono/mono/pull/15585

https://github.com/dotnet/runtime/blob/9eb90511ff6d079fa02832936c693d36289fc02b/src/mono/System.Private.CoreLib/src/System/Array.Mono.cs#L202-L203

which doesn't look right to me (it's comparing `src_type` which is the array element type which doesn't change each time through the loop.  I think it actually wants `srcval.GetType()`)
