### ISSUE TITLE
ArrayPool<T>.Return should clear specified number of elements in array

### ISSUE THREAD

**Issue by notemac** [dotnet/runtime#64382]
Based on: [ArrayPool<T>.Shared.Return should clear buffer when T is reference or contains references](https://github.com/dotnet/runtime/issues/25378).
ArrayPool class can return array with greater number of elements than was requested. But we know the requested number of elements. So when returning array to the pool with 'clearArray = true' we want clear the requested number of elements for performance reasons.
```C#
namespace System.Buffers
{
    public abstract class ArrayPool<T>
    {
       // Example of new API:
        public abstract void Return(T[] array, bool clearArray = false, int clearArrayLength = -1);
    }
}
```

**Comment by stephentoub** [comment]
We can't add new abstract methods to an existing type. Note this is easily achieved with:
```C#
Array.Clear(array, 0, clearArrayLength);
ArrayPool<T>.Shared.Return(array);
```
