### ISSUE TITLE
False positive for CA1416 in net6 library

### ISSUE THREAD

**Issue by gundermanc** [dotnet/runtime#64395]
### Analyzer

**Diagnostic ID**: [CA1416 ](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1416 ): `Validate platform compatibility`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 6.0.101](https://dotnet.microsoft.com/download/dotnet/6.0)

### Describe the bug

FileSystemWatcher is erroneously marked as unsupported on windows platforms.

`[SupportedOSPlatform("macoscatalyst")]` fixes the compile warnings but `[SupportedOSPlatform("windows")]` does not.

### Steps To Reproduce

1. Create a .NET 6 application
2. Add FileSystemWatcher reference.
3. CA1416 is raised.

See: https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/374658?_a=files

### Expected behavior

Adding SupportedOSPlatform("Windows") attribute to the method or class resolves the warning.

### Actual behavior

Adding SupportedOSPlatform("Windows") attribute to the method or class does not resolve the warning, only macoscatalyst platform does.

## Additional context

N/A

**Comment by buyaa-n** [comment]
The project is annotated as supported only on maccatalyst https://github.com/dotnet/runtime/blob/6233735c37b1af9c182c28c9d74aeac0104785b8/src/libraries/System.IO.FileSystem.Watcher/Directory.Build.props#L7

**Comment by buyaa-n** [comment]
Ah i see why it is added https://github.com/dotnet/runtime/pull/58142#discussion_r696641442, because it has unsupported on `ios` annotation, i will check what is going on here

**Comment by buyaa-n** [comment]
> Perhaps this is project configuration specific, it doesn't seem to repro in a one-off project, though it does in the linked PR.

Yeah it is not repoducable with a sample project similar to your project settings in the linked PR, and that project actually doesn't have much settings, @gundermanc could you share the exact message the analyzer prooduces?

**Comment by buyaa-n** [comment]
My best guess is the version of SDK used in your repo might have been using the old version of analyzers where the above annotation was not supported, i guesss something similar to [this]( https://github.com/dotnet/roslyn-analyzers/issues/5728#issuecomment-973172679) is happened, @gundermanc could you install/update with the latest updated SDK and give it try again? i assume it would not happen with the latest SDK.

With that being said it is not annotation issue, sorry for wrong notifications guys!

**Comment by gundermanc** [comment]
> could you install/update with the latest updated SDK and give it try again?

We're currently on SDK 6.0.101, is there a newer version you would recommend?

**Comment by buyaa-n** [comment]
Looks 6.0.102 is in preview, propbably need to wait for the release. Could you share the message the analyzer produced?

**Comment by buyaa-n** [comment]
Your repo might be using the analyzers from the nuget package `Microsoft.CodeAnalysis.NetAnalyzers` directly, if that is the case the SDK analyzer would have not impact, please update your nuget package version and let us know if that helps
