### ISSUE TITLE
Crossgen2 composite framework build emits OptimizedInboxTextEncoder layout mismatched with the CoreCLR runtime

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#64419]
Architecture: **64-bit**
OS: **all**
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1574573&view=results

Diagnostic information:

<pre>
      Assert failure(PID 1408 [0x00000580], Thread: 2176 [0x0880]): Verify_FieldOffset 'System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints' Field offset 16!=24(actual) || baseOffset 8!=8(actual)
      
      CORECLR! LoadDynamicInfoEntry + 0x11C1 (0x00007ffb`0ec98e71)
      CORECLR! Module::FixupNativeEntry + 0x280 (0x00007ffb`0eb7d190)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x6AD (0x00007ffb`0ee0d88d)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x64A (0x00007ffb`0ee0ff4a)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0xDA (0x00007ffb`0ed5eb1a)
      CORECLR! MethodDesc::GetPrecompiledCode + 0xD1 (0x00007ffb`0ed5e711)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x3B0 (0x00007ffb`0ed62030)
      CORECLR! MethodDesc::PrepareCode + 0xE8 (0x00007ffb`0ed61c28)
      CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x3F3 (0x00007ffb`0ebe5433)
      CORECLR! MethodDesc::DoPrestub + 0xC0E (0x00007ffb`0ed5aafe)
          File: D:\a\_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 13642
          Image: C:\h\w\AF87095D\p\corerun.exe
</pre>

At the first glance it seems to me that this is caused by mismatching classification of the type by Crossgen2 and the runtime. Crossgen2 query for

https://github.com/dotnet/runtime/blob/9eb90511ff6d079fa02832936c693d36289fc02b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunMetadataFieldLayoutAlgorithm.cs#L805

doesn't hit the sequential path because the type does contain GC pointers, however the check in

https://github.com/dotnet/runtime/blob/9eb90511ff6d079fa02832936c693d36289fc02b/src/coreclr/vm/methodtablebuilder.cpp#L1719

does classify the type as Blittable and enters the sequential layout path.

/cc @dotnet/crossgen-contrib, @jkoritzinsky

**Comment by jkoritzinsky** [comment]
The definition for `IsManagedSequential()` in CoreCLR now effectively is `IsSequentialLayout && !ContainsGCPointers`, so something more nuanced is probably going on here.

**Comment by jkoritzinsky** [comment]
I wonder why this type is classified as blittable if it has GC pointers in it...

**Comment by mangod9** [comment]
@trylek @jkoritzinsky is this something we plan on fixing for 7?
