### ISSUE TITLE
Http2's SendPingAsync may leak UnobservedTaskExceptions

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#64450]
(based on code inspection)

The `SendPingAsync` call that we do as part of the `ConnectionPoolManager`'s heartbeat isn't awaited and so any exceptions from it would bubble up as `UnobservedTaskException`s.

https://github.com/dotnet/runtime/blob/82c45caafbbbb252a9fe4e231f84b3a42ad0c3c2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L2041

We should consume the task with `LogExceptions(SendPingAsync(pingPayload))` as we do when [sending out pings normally](https://github.com/dotnet/runtime/blob/82c45caafbbbb252a9fe4e231f84b3a42ad0c3c2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L927).

Should be an easy fix - marking as up for grabs.

**Comment by shubhanshu02** [comment]
Hi @MihaZupan, can I take this up? If I understood correct, all that's needed to do is to wrap the function `SendPingAsync` with  `LogExceptions` so that the exceptions (if occurred) are caught and logged?

**Comment by MihaZupan** [comment]
That's right. I'll assign the issue to you :)

**Comment by shubhanshu02** [comment]
Thanks, I have put up a PR regarding this.
