### ISSUE TITLE
Http proxy not working with authentication

### ISSUE THREAD

**Issue by jkvargas** [dotnet/runtime#64459]
### Description

I am not able to authenticate to a proxy using given credentials.
What am I missing?
Thanks.

### Reproduction Steps

```c#
using var httpClientHandler = new HttpClientHandler
{
    Proxy = new WebProxy(address, true, new string[] {}, new NetworkCredential(someuser, somepass)),
    UseProxy = true,
    ServerCertificateCustomValidationCallback = (_, _, _, _) => true,
};

using var client = new HttpClient(httpClientHandler);

```
using var client = new HttpClient(httpClientHandler);

### Expected behavior

I would like to perform gets/posts through the given proxy.

### Actual behavior

authentication fails

**Comment by wfurt** [comment]
Do you see attempt to authenticate @jkvargas? Wireshark would be great to see what is happening.

**Comment by jkvargas** [comment]
Hi @wfurt, thanks for your answer.
So, I tried using curl and the dotnet application.
when sending the http connect the curl version has an Proxy-Authorization: Basic ...
The c# client does not send it.
At least not using the code that I shared with you.

**Comment by wfurt** [comment]
I did quick test with the fragment you posted @jkvargas and it seems to work e.g. it does send credentials in response to 407.  Note that curl AFAK sends the credentials even if the proxy does not ask. .NET does not do that it sends credentials only if the proxy ask for it.

```
CONNECT github.com:443 HTTP/1.1
Host: github.com:443

HTTP/1.1 407 Proxy Authentication Required
Server: squid/3.5.27
Mime-Version: 1.0
Date: Mon, 31 Jan 2022 19:09:57 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3449
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
Vary: Accept-Language
Content-Language: en
Proxy-Authenticate: Basic realm="Squid proxy-caching web server"
X-Cache: MISS from net-dale
X-Cache-Lookup: NONE from net-dale:3128
Via: 1.1 net-dale (squid/3.5.27)
Connection: keep-alive

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2017 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: Cache Access Denied</title>

CONNECT github.com:443 HTTP/1.1
Host: github.com:443
Proxy-Authorization: Basic c29tZXVzZXI6c29tZXBhc3M=

HTTP/1.1 200 Connection established

```

what OS and .NET version are you on?

**Comment by karelz** [comment]
@jkvargas any update?

**Comment by jkvargas** [comment]
hi @karelz 
At the end, investigating more the issue was on the server side.

A quick question before we close this topic.
When I am using proxy and I add a default header,
something in the lines 

```
using var client = new HttpClient(handler);
client.DefaultRequestHeaders.Add("X-Authentication-Mode", "Strict");
```

I will get two calls to HttpConnectionPool.GetHttp11ConnectionAsync with the following HttpRequestMessage:

first one:

Method: POST, RequestUri: '[https://endpoint]()', Version: 1.1, Content: System.Net.Http.StringContent, Headers:
{
  X-Authentication-Mode: Strict
  Content-Type: text[/plain](); charset=utf-8
  Content-Length: 14
}

and a second one which really hits the proxy with 
Method: CONNECT, RequestUri: '[http://proxy/]()', Version: 1.1, Content: <null>, Headers:
{
  Host: endpoint
}

Shouldn't it be sending the default header as well on this second request?
Thanks.

**Comment by wfurt** [comment]
I think the logic assumes the header is for the server. The second request only asks the proxy to open the channel. There will be third request that should have the header one again.

**Comment by jkvargas** [comment]
Well, if it is just for the server then I have no more questions :)

**Comment by karelz** [comment]
Triage: Looks resolved. Closing. Thanks!
