### ISSUE TITLE
Update the XML docs for IComparisonOperators and implementing types

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#64463]
As called out in https://github.com/dotnet/runtime/pull/64234#discussion_r794760086

The current XML docs for the `IComparisonOperators` operators are potentially confusing as they are:
> /// <summary>Compares two values to determine which is less.</summary>

We should likely update this to something like
> /// <summary>Returns a value that indicates whether a specified TSelf value is less than or equal to another specified TOther value.</summary>

and then update the docs of things like `NFloat` and the other types that are implementing, or will implement, `IComparisonOperators`  accordingly.

**Comment by dakersnar** [comment]
Closed as a dup of https://github.com/dotnet/runtime/issues/69694
