### ISSUE TITLE
VS 2022 preview 2.1: Blazor WebAssembly debugging can't move current cursor when paused

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#64475]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022-preview-21:-Blazor-WebAssembly-/1498552)._

---
[severity:It's more difficult to complete my work]
When I'm stopped in a line of code while debugging, I want to move the cursor to the line above to re-execute a method call, however VS doesn't let me do it. Normally in C# code I've always been able to do it, but I can't do it in Blazor WebAssembly in VS 2022. See the image below, I would like to move the yellow arrow to the line above (from line 35 to line 36).

Not being able to move the cursor forces me to stop the whole application and restart and recreate all the conditions to get to the same place in the code, which is very time consuming and it's frustrating.

! [image.png] (https://aka.ms/dc/image?name=B91aa333876924177a4fac23c7f08e5d7637641766546242781_20210810-171730-image.png&tid=91aa333876924177a4fac23c7f08e5d7637641766546242781)

---
#### Feedback Bot on 8/10/2021, 02:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/12/2021, 09:58 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 10/13/2021, 05:01 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lewing based on the conversations on the original feedback ticket this seems to be a feature request which will need some changes to the debug proxy.

**Comment by thaystg** [comment]
There is already a PR open implementing it on our side.

**Comment by serp777** [comment]
How about live editing too? When I make a change in the code during debugging i'd like it show up and work like regular c# code. So i'd like to make a code change, then move the cursor to the new line, and have it work as is.

**Comment by rmencia-isv** [comment]
> How about live editing too? When I make a change in the code during debugging i'd like it show up and work like regular c# code. So i'd like to make a code change, then move the cursor to the new line, and have it work as is.

What you are saying is correct, but editing the code in Blazor while debugging doesn't work (maybe in the next few months). 
At least to be able to move the cursor and choose next execution line.

It's clear that it should work the same regardless of the platform, either Blazor or aspnet, a Console application and maybe Maui in the future. 

Move the execution line is fundamental for Edit and Continue, because you may update the code from the line above and you want to re-execute it without having to restart the application.
