### ISSUE TITLE
Assertion failed 'ppInfo->HasKeptAliveThis()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#64477]
From superpmi replay pipeline, after https://github.com/dotnet/runtime/pull/64116:

```
ISSUE: <ASSERT> #55035 D:\a\_work\1\s\src\coreclr\jit\codegencommon.cpp (6406) - Assertion failed 'ppInfo->HasKeptAliveThis()' in 'ConcatNIterator`1:GetEnumerable(int):IEnumerable`1:this' during 'Generate code' (IL size 54)
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1577337&view=results

(there are also many thousand more MISSING methods, so we need a recollection)

**Comment by AndyAyersMS** [comment]
It is because the asp.net collection is stale: the Tier0 methods in the old collection don't always preserve generic context. We now expect that they do.

Recollecting now.

**Comment by AndyAyersMS** [comment]
FYI Tier0+PP -> OSR "contract" was changed by #64116. Not an issue if you're running live; also not something we'd normally bump the jit GUID for.

**Comment by AndyAyersMS** [comment]
Should be fixed now (no PR to link to, as this collection is still done by me manually).
