### ISSUE TITLE
TextElements result changed in .NET6.0

### ISSUE THREAD

**Issue by GCAronChen** [dotnet/runtime#64489]
### Description

I use this API to split each single text from string then draw to each control based on Winform Framewrok
```
public string SubstringByTextElements (int startingTextElement, int lengthInTextElements);
```

[API Doc](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.stringinfo.substringbytextelements?view=net-6.0)
When I upgrade .NET Core version from .NET Core3.1 to .NET6.0
I found some string split result changed:
```
var strInfo = new System.Globalization.StringInfo("ｼﾞ");
var result = strInfo.SubstringByTextElements(0, 1);
```
![image](https://user-images.githubusercontent.com/96418485/151650706-60e533ea-30d3-4ef2-a10d-f155878a92c0.png)

![image](https://user-images.githubusercontent.com/96418485/151650693-f629b299-d8d9-45a8-a880-0a501a4798b4.png)

Seems in .NET6, "ｼﾞ" will be treated as a whole world not two single part.
I'm not sure, because we can select char individually like this:
![select](https://user-images.githubusercontent.com/96418485/151651008-fa0c36da-50b9-4ec3-ac3c-9da2aa8f3e2e.gif)
Could you please investigate is this a bug or not? Is there any other API as workaround?

### Reproduction Steps

Create a console project, use this code
```
var strInfo = new System.Globalization.StringInfo("ｼﾞ");
var result = strInfo.SubstringByTextElements(0, 1);
```

### Expected behavior

same as .net3.1, "**ｼ**"

### Actual behavior

different with  .net3.1, "**ｼﾞ**"

**Comment by hez2010** [comment]
May be related to ICU migration introduced in .NET 5, see https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

> I'm not sure, because we can select char individually like this.
![image](https://user-images.githubusercontent.com/14960345/151663302-584e028a-7dc6-4ba2-919c-c99677cdf2c4.png)

Cannot select char individually in browser (ja-JP locale).

> Is there any other API as workaround?
You can use NLS fallback: https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu

**Comment by svick** [comment]
@hez2010 

I don't think this is about the switch from NLS to ICU, I get the same result on .Net 5, if I use the NLS fallback.

@GCAronChen

[The implementation of TextElements was rewritten in .Net 5.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/uax29-compliant-grapheme-enumeration?WT.mc_id=DOP-MVP-5002735), so that it correctly produces graphemes according to the Unicode standard. To me, it sounds like the change you describe is exactly the expected kind of change here.

**Comment by GCAronChen** [comment]
@svick 
Thanks I can understand, you are right.
[The implementation of TextElements was rewritten in .Net 5.0](The implementation of TextElements was rewritten in .Net 5.0)

This API is different with caret move behavior, so I choose another API to get split result like previous behavior

**Comment by GCAronChen** [comment]
@hez2010 
Thanks for your help, but we are working at desktop app not web, so customer still feel very strange to merge two char but can select seperately. I changed a another API to resolve it

**Comment by tarekgh** [comment]
> I don't think this is about the switch from NLS to ICU, I get the same result on .Net 5, if I use the NLS fallback.

That is right, the character Unicode categorization in .NET is independent of ICU/NLS. We update every release of .NET with the latest Unicode data. 

Thanks @svick for pointing to the [doc](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/uax29-compliant-grapheme-enumeration?WT.mc_id=DOP-MVP-5002735#change-description) which describe the breaking change. 

The `U+FF9E` is extended grapheme character according to Unicode standard [doc](https://github.com/latex3/unicode-data/blob/0525d9cefa2189e83a0a02ae0853e82c4d6476aa/GraphemeBreakProperty.txt#L315). 

```
FF9E..FF9F    ; Extend # Lm   [2] HALFWIDTH KATAKANA VOICED SOUND MARK..HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
```

So, the behavior seen in .NET 6.0 is correct.

> customer still feel very strange to merge two chars but can select separately

It depends on what you want to achieve here. Combining these characters are correct from a text itemization point of view. For editors, it may be desirable to allow selecting one character and not the whole cluster to be able to delete one of these characters, I recall apps like Microsoft Word have options to have the caret and the selection work logical or visual to support such cases. In other word it gives the option to the users to choose the behavior they prefer. 

By that I am closing this issue. Feel free to send any more questions if you have any. Thanks for your report!

CC @GrabYourPitchforks
