### ISSUE TITLE
[API Proposal]: Adding overloading FileStream.FlushAsync(bool flushToDisk)

### ISSUE THREAD

**Issue by lindexi** [dotnet/runtime#64485]
### Background and motivation

I read and write the HID device by FileStream. And it will fail when I use the FlushAsync method to flush the data, because I have no control over when to flush to disk.

I want to control the `flushToDisk` behavior in FlushAsync.

Ref https://github.com/dotnet/runtime/issues/27643

Demo: https://github.com/lindexi/lindexi_gd/tree/7a95607f5dd8c88067b38f6e481d3d25282595a0/YicihurjihiGemfifeewai

### API Proposal

```C#
namespace System.Collections.Generic
{
    public class FileStream
    {
        public Task FlushAsync(bool flushToDisk, CancellationToken cancellationToken = CancellationToken.None);
    }
}
```

### API Usage

```C#
FileStream fileStream = CreateFileStreamFromHID();
fileStream.FlushAsync(flushToDisk: true / false);
```

**Comment by stephentoub** [comment]
To my knowledge, there is no OS-level "flush to disk" functionality that's asynchronous . The best we could do internally is the same you can do via public APIs: queue a work item to call Flush(true). We won't add such an API unless we can do meaningfully better than that.

**Comment by stephentoub** [comment]
@adamsitnik, you triaged this to Future.  Is there a reason to keep it open?

**Comment by kkwpsv** [comment]
When write to HID device, there's no os buffer. But `FileStream` will still try to call `FlushFileBuffers`, and it'll failed.
So we need a `FlushAsync` without flushToDisk like `Flush`.

**Comment by stephentoub** [comment]
> But FileStream will still try to call FlushFileBuffers, and it'll failed.
So we need a FlushAsync with flushToDisk like Flush which will not call FlushFileBuffers internally.

What would it do that's different from what FlushAsync does already if not call FlushFileBuffers? It sounds like you're actually asking for Flush(true) to not throw in some cases where it's throwing today, which is unrelated to this API request.

**Comment by kkwpsv** [comment]
> > But FileStream will still try to call FlushFileBuffers, and it'll failed.
> > So we need a FlushAsync with flushToDisk like Flush which will not call FlushFileBuffers internally.
> 
> What would it do that's different from what FlushAsync does already? It sounds like instead you're actually asking for Flush(true) to not throw in some cases where it's throwing today, which is unrelated to this API request.

I want a `FlushAsync(false)`.
Now `FlushAsync` is like `Flush(true)`.

**Comment by stephentoub** [comment]
> I want a FlushAsync(false) like Flush(false). Now FlushAsync is like Flush(true).

No, FlushAsync() is the async version of Flush(false).  FlushAsync does not call FlushFileBuffers.

**Comment by kkwpsv** [comment]
> > I want a FlushAsync(false) like Flush(false). Now FlushAsync is like Flush(true).
> 
> No, FlushAsync() is the async version of Flush(false). FlushAsync does not call FlushFileBuffers / fsync.

Oh, FlushAsync behaves differently in .NET Framework 4.8 and .NET.
I met the problem in .NET Framework 4.8, and confirm its source codes that it works like `Flush(true)`. I just read .NET source code, it works like what you said.

**Comment by stephentoub** [comment]
> Oh, FlushAsync behaves differently in .NET Framework 4.8 and .NET.

Yes, this was a bug fixed in https://github.com/dotnet/coreclr/pull/24902.

**Comment by lindexi** [comment]
Thank you @stephentoub . There is no reason to add the FlushAsync(bool) API. And we should use the Flush(true) when we want to flush to disk.
