### ISSUE TITLE
Signing certificate with ECDsa works in Windows, invalid signature in Linux

### ISSUE THREAD

**Issue by mnns** [dotnet/runtime#64515]
### Description

I'm signing a certificate with an imported EC private key I created with openssl.
It works great on Windows, the certificate is valid.
When using the same code in Linux, the certificate created has an invalid signature.

### Reproduction Steps

```
                ECDsa ecSigningPrivateKey = ECDsa.Create();
                ecSigningPrivateKey.ImportECPrivateKey(signingPrivateKey, out _);
                ECParameters ecp= ecSigningPrivateKey.ExportExplicitParameters(true);

                var signatureGenerator = X509SignatureGenerator.CreateForECDsa(
                     key: ecSigningPrivateKey
                 );

                X509Certificate2 newCertificate = newCertificateRequest.Create(
                    issuerName: "test",
                    generator: signatureGenerator,
                    notBefore: newCertNotBefore,
                    notAfter: newCertNotAfter,
                    serialNumber: certificateSerialNumber
                );
```

### Expected behavior

A valid certificate.

### Actual behavior

I get a good certificate in Windows and an invalid signature in Linux.

### Configuration

.NET 5.0
Local dev environment is Windows 10 x64, while my docker is using the default .NET 5.0 imports: 
"FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base" and "FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build" for the SDK.

### Other information

I exported ECParameters using "ExportExplicitParameters()", all parameters were the same except the Linux version had "Seed" in it, while the Windows one didn't. I suspect this might be problem. I have no idea how to fix it and I'm not sure it will be a reliable standard fix.

**Comment by bartonjs** [comment]
Can you provide a more complete repro, including the complete set of options that went into the CertificateRequest?  The most likely explanation, off the top of my head, is that you have a subject == issuer but the contained public key isn't the same as the signing key (and then Windows finds the secondary signer, and Linux stops at subject == issuer).

**Comment by mnns** [comment]
> Can you provide a more complete repro, including the complete set of options that went into the CertificateRequest? The most likely explanation, off the top of my head, is that you have a subject == issuer but the contained public key isn't the same as the signing key (and then Windows finds the secondary signer, and Linux stops at subject == issuer).

Thanks, so I double checked the public key, it is correct.
Also this function works great in Windows and I validated the certificate chain using several tools to be on the safe side.

I managed to fix this by setting Seed = null. It now works in Linux as well.

```
ECParameters ecp = ecSigningPrivateKey.ExportExplicitParameters(true);
ecp.Curve.Seed = null;
ecSigningPrivateKey.ImportParameters(ecp);
```

I'm exporting and re-importing the curve without the seed.
The certificate has now a valid signature and chain on both Windows and Linux.

I hope this is a valid fix!

**Comment by bartonjs** [comment]
It seems like this is, more or less, resolved via a workaround (the underlying cause being that OpenSSL and Windows seem to differently care about the curve.Seed value?).

Since I don't see any further action here, closing.
