### ISSUE TITLE
TryConvertIanaIdToWindowsId empy output on server

### ISSUE THREAD

**Issue by ilcos91** [dotnet/runtime#64526]
### Description

When I try to use the function TryConvertIanaIdToWindowsId from TimeZoneInfo, it works on my local computer and not on the server. Specifically the output is empty on the server.

### Reproduction Steps

To reproduce the issue I have created a ConsoleApp:
```
class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
        foreach (TimeZoneInfo z in TimeZoneInfo.GetSystemTimeZones())
        {
            Console.WriteLine(z.Id);
        }
        TimeZoneInfo.TryConvertIanaIdToWindowsId("Europe/Rome", out string windowsTimeZone);
        Console.WriteLine($"ConvertedTimeZone: {windowsTimeZone}");
        Console.ReadLine();
    }
}
```

### Expected behavior

I would expect to get an error, explaining the situation, or to get the correct output as on my local machine

### Actual behavior

I don't get any error, the program is executed and simply the output of the function is empty.

### Configuration

On my local pc I have Windows 11 with .net6 installed:
![image](https://user-images.githubusercontent.com/59659091/151771126-3c0690b5-303f-41a2-9480-c9a83c38e38b.png)
This is my server configuration:
![image](https://user-images.githubusercontent.com/59659091/151771799-74966847-936e-48c6-a905-f7a5d40bd40a.png)

![image](https://user-images.githubusercontent.com/59659091/151771275-3425220d-a7a2-47fa-b569-61bf94a1d877.png)

**Comment by martincostello** [comment]
On Windows Server 2016 you need to use the `Microsoft.ICU.ICU4C.Runtime` NuGet package so that required data that isn't built into that version of Windows is available to the app: https://github.com/dotnet/runtime/issues/53279#issuecomment-849069462

**Comment by ilcos91** [comment]
I have tried to add `Microsoft.ICU.ICU4C.Runtime` but it's still not working

**Comment by tarekgh** [comment]
> I have tried to add Microsoft.ICU.ICU4C.Runtime but it's still not working

Please confirm you have added the following to your csproj.

```Xml
<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
  <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2" />
</ItemGroup>
```

Also, please run the following code and send me the output you are seeing with your app. If you don't have a console app, you may store the values in some file instead of using Console.WriteLine(). 

```C#
            try
            {
                Type interopGlobalization = Type.GetType("Interop+Globalization, System.Private.CoreLib");
                if (interopGlobalization != null)
                {
                    MethodInfo methodInfo = interopGlobalization.GetMethod("GetICUVersion", BindingFlags.NonPublic | BindingFlags.Static);
                    if (methodInfo != null)
                    {
                        int version = (int)methodInfo.Invoke(null, null);
                        Console.WriteLine($".... ICU Version: {new Version(version >> 24, (version >> 16) & 0xFF, (version >> 8) & 0xFF, version & 0xFF)}");
                    }
                }
                Console.WriteLine($".... UseNls:                 {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("UseNls", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null)} ....");
                Console.WriteLine($".... Invariant:              {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("Invariant", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null)} ....");
                Console.WriteLine($".... PredefinedCulturesOnly: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("PredefinedCulturesOnly", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null)} ....");
            }
            catch
            {
                Console.WriteLine($".... UseNls: Couldn't Evaluate it ....");
            }
```

**Comment by ilcos91** [comment]
Now it's working, in the consolle app I was missing the `RuntimeHostConfigurationOption` tag.
While in my production environment I needed to add this tag also to the web api project and not only to the library project.

Thank you for your help
