### ISSUE TITLE
Prevent placing ref fields on non-pointer boundaries

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#64520]
Similar to #12842 except for the following struct:

```csharp
[StructLayout(LayoutKind.Explicit)]
ref struct RefStruct
{
    [FieldOffset(0)]
    public short X;
    [FieldOffset(2)]
    ref int Y;
}
```

We should not allow this to load.

**Comment by AaronRobinsonMSFT** [comment]
I have the CoreCLR fix for this. The Mono changes are bit more complex and taking some time.

**Comment by MichalStrehovsky** [comment]
> I have the CoreCLR fix for this. The Mono changes are bit more complex and taking some time.

FWIW, Mono doesn't even detect #12842.

There's not even a bug for it because I don't think Mono ever ran a Pri-1 CoreCLR test pass (the regression test is Pri-1). If you make your regression test Pri-1, you can save yourself some work. It's not a Pri-0 scenario.

**Comment by AaronRobinsonMSFT** [comment]
@MichalStrehovsky I've spent most of the day getting Mono in the right state. I am hitting issues now that are really confusing. I am close to doing what you suggest. Likely will make the call tomorrow.
