### ISSUE TITLE
Ability to 

### ISSUE THREAD

**Issue by rhyous** [dotnet/runtime#64543]
### Description

This is a bit of an enhancement request and not a bug per se.

With Generics, there is no way to:

1. Put a constraint on T to enforce it is a primitive. 

```where T : Primitive```

2. Put a constraint on T to enforce that it is a number type: byte, int16, int32, int 64, float, dubble, etc.

```where T: Number```

### A possible simple resolution
This could be solved with interfaces. Primitives already inherit some interfaces such as IComparable, IFormattable, IConvertible. 
What if in the next .net update, these two interfaces were added:

- IPrimitive
- INumber

**IPrimitive interface**
1. Have any methods shared by all primitives added to it
2. Would be applied to all primitive types
3. A compiler change could be added to prevent IPrimitive from being added by developers. It should only be used for .Net provided primitives.

**INumber interface**
1. Have any methods shared by all primitive number types, such as Parse and TryParse, added to it
2. Would be applied to all primitive types of type number
Note: Would NOT need a compiler change, as this one could be useful for other devs to implement, such as implementing a custom bigint

### Using this
Once those interfaces exist and are applied appropriately to primitives, both features constraining to primitives 
   public class MyClass<T> 
   where T : IPrimitive
    {
    }

   public class MyClass<T>
   where T : INumber
   {
   }

**Comment by rhyous** [comment]
> An INumber interface shipped as part of a .NET 6 Side-by-Side preview. Instead of just decoration it uses the new runtime and language feature of static abstracts on interfaces, which means it already provides the (Try)Parse. https://devblogs.microsoft.com/dotnet/preview-features-in-net-6-generic-math/

Thanks, I didn't look at .NET 6. That is awesome that you've already created something. Reading about it now . . . 

We just need to make sure that this syntax solves the problem. Can we limit T to be Numbers using: `where T : INumber<T>`? From the link you provide, it looks like the answer is Yes.

> 
> As for IPrimitive... you'd have to define a primitive. If you mean the built-in numeric types, plus Object and String,

Good point. I had only the built-in numeric types, plus String and Guid.
I thought Object wasn't primitive because it is a boxing type, used to box any other type.
I checked out Guid and it is a struct but not a primitive type. typeof(guid).IsPrimitive returns false. It is also not listed as a built-in type on the language-reference website, even though it is also part of the system namespace. Perhaps it is special.
Also, I just checked and both typeof(object).IsPrimitive is false and typeof(string).IsPrimitive is false. So maybe calling the interface IPrimitive would be wrong and confusing. Would it be IBuiltInType instead? This might need more thought.

> then the only thing that you can do on all of them is ToString/Equals/GetHashCode... the members that Object already provides. 

For my use cases, i want to:
1. Limit T to be numbers, which sounds solved in .Net6.
2. Limit T to be numeric types, plus String and Guid. Which I assumed (incorrectly) were all primitives, but they aren't. There is currently no way to do this.

Maybe the feature I want then is an "OR" condition, but I would guess that that would be orders of magnitude more difficult:

Where T : INumber<T>||String||Guid

Or maybe, it is that I would like to limit T to any of a list of classes.

**Comment by Joe4evr** [comment]
> Maybe the feature I want then is an "OR" condition, but I would guess that that would be orders of magnitude more difficult:
> 
> Where T : INumber||String||Guid

If those are the only types you care about, you could get by with a simple set of overloads:
```cs
public void M<T>(T value) where T : INumber<T> { }
public void M(string value) { }
public void M(Guid value) { }
```

**Comment by tannergooding** [comment]
This is being covered by generic-math.

If there are additional asks on the language issues they should be opened against dotnet/csharplang.

If there are specific asks for the libraries side, they should have individual issues here on dotnet/runtime.
