### ISSUE TITLE
[WASM] main.js missing in wasm-aot performance runs

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#64553]
I am seeing this error on wasm-aot perf runs when the benchmarks are executing. I think some change may have moved this file? This happened around December 10th.

```
Executable /Users/naricc/workspace/BenchmarkDotNet/samples/BenchmarkDotNet.Samples/bin/Debug/net7.0/Job-TXNKXQ/bin/net7.0/browser-wasm/AppBundle/main.js not found
```

The template BenchmarkDotnet uses to generate projects is here: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/WasmAotCsProj.txt. 

I am not sure if it needs to be updated or something in dotnet/runtime needs changing?

**Comment by pavelsavara** [comment]
Probably `test-main.js` (here)[https://github.com/dotnet/BenchmarkDotNet/blob/db0a88ab9cf94ac8b5f6302173091ddf42c2dc09/src/BenchmarkDotNet/Toolchains/MonoWasm/WasmGenerator.cs#L94]
