### ISSUE TITLE
EventSource source generator should mark both source and IL as autogenerated

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#64563]
Per https://github.com/dotnet/runtime/issues/64541, it should emit `<autogenerated>` into the source and also `[GeneratedCodeAttribute...]` for the IL. 

Our other generators do this; this enables tooling and servicing scenarios.

eg regex generator
https://github.com/dotnet/runtime/blob/9df283248256dd880eb1ee5ecce533ad206a55d3/src/libraries/System.Text.RegularExpressions/gen/RegexGenerator.Emitter.cs#L27-L31

**Comment by teo-tsirpanis** [comment]
I'm working on it.
