### ISSUE TITLE
.NET 6 failing at Decompress large gzip text

### ISSUE THREAD

**Issue by MitchWenceInfocorp** [dotnet/runtime#64577]
### Description

I have to decompress some gzip text in .NET 6 app, however, on a string that is 20,627 characters long, it only decompresses about 1/3 of it. The code I am using code works for this string in .NETCore 3.1 As well as smaller compressed strings.

### Reproduction Steps

Here is the method I am using:
```
public static string Decompress(this string compressedText)
{
    var gZipBuffer = Convert.FromBase64String(compressedText);
    using var memoryStream = new MemoryStream();
    int dataLength = BitConverter.ToInt32(gZipBuffer, 0);
    memoryStream.Write(gZipBuffer, 4, gZipBuffer.Length - 4);
    var buffer = new byte[dataLength];
    memoryStream.Position = 0;
    using (var gZipStream = new GZipStream(memoryStream, CompressionMode.Decompress))
    {
        gZipStream.Read(buffer, 0, buffer.Length);
    }
    return Encoding.UTF8.GetString(buffer);
}
```

Take a gzip string that is over 20,627 characters long and try to decompress it in .NET6.  If take the same string in .NET Core 3.1 the gzip string will decompress correctly

### Expected behavior

The text should be decompressed correctly

### Actual behavior

The results of the decompression is something like this:

> Start of amazing text..... ...Text is fine till 33,619 after that is allNULLNULLNULLNULL

### Regression?

This code works in .NET 5 and .NET 3.1.  If I switch the version to .NET 5 or  .NET 3.1 it works, switching it .NET 6 the error occurs.

### Configuration

.NET 6.0.1
Windows 10 Pro 21H1
AMD Ryzen 5900HS x64
It does appear to be the version of .NET as this code works in .NET 5 and .NET 3.1

Edit: fixed typo

**Comment by stephentoub** [comment]
Stream.Read only guarantees that it returns at least 1 byte if not at end-of-stream, not that it returns as much as was requested.  The line in your repro:
```C#
gZipStream.Read(buffer, 0, buffer.Length);
```
needs to loop, e.g.
```C#
int totalRead = 0, bytesRead;
while ((bytesRead = gZipStream.Read(buffer, totalRead, buffer.Length - totalRead)) > 0)
{
    totalRead += bytesRead;
}
```

GZipStream previously _happened_ to hand back what was requested if possible, but that made it unusable in scenarios where guaranteeing that resulted in deadlocks, and it was changed for .NET 6:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by kewur** [comment]
I believe this broke us as well. We were using GZipStream to compress and decompresss our json objects. After we upgraded from .net 3.1 to .net 6 now we get this exception on all of our deserializations.

`'0x00' is invalid within a JSON string. The string should be correctly escaped. Path: $[226].figi | LineNumber: 0`

**Comment by stephentoub** [comment]
> decompressionStream.Read(result, 0, length);

This needs to loop.  Stream.Read is not guaranteed to return the requested amount of data.

**Comment by kewur** [comment]
sorry, just realized I posted my work in progress code where I was trying to get it to working again. I updated the code with the one we used for over a year to compress/decompress in Prod that stopped working after the upgrade.

**Comment by stephentoub** [comment]
Thanks.  Same issue here:

> gzip.Read(buffer, 0, uncompressedSize);

That needs to be a loop.  Stream.Read is not guaranteed to return the requested amount of data.

**Comment by kewur** [comment]
ok thanks
