### ISSUE TITLE
Build crossgen with NativeAOT and trimming

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#64571]
- [x] Add support for publishing self-contained crossgen into the runtime
- [x] Remove trim warnings
  - [x] Add COM wrappers for COM calls in crossgen2
  - [x] Add COM wrappers for DiaSymReader

**Comment by kant2002** [comment]
Can I play with that? How do you plan to create ComWrappers for Crossgen2/DiaSymReader ? I can handle ComWrappers creation, but for build/test infra, I will need help.

**Comment by agocke** [comment]
This should now be complete
