### ISSUE TITLE
System.Xml work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#64602]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
We are not planning any notable investments into the System.Xml area in .NET 7. We will address issues related to nullable annotations, resolve test issues and high-impact bugs, and we will consider community contributions that provide proven performance optimizations.

## Planned for .NET 7

- [x] #60226
- [x] #52646
- [x] #36903
- [x] #50944
- [x] #50945
- [x] #50946
- [x] #50947
- [x] #50948
- [x] #41061
- [x] #49131
- [x] #48456

## Backlog (roughly in priority order)

- [x] #30054
- [ ] #34443
- [ ] #59353
- [ ] #50308
- [ ] #1029
- [x] #52436

**Comment by krwq** [comment]
Closing issue since all of the planned items are fixed
