### ISSUE TITLE
System.Diagnostics.Process work planned for .NET 7

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#64600]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary
We are not planning any notable investments into the System.Diagnostics.Process area in .NET 7. We will address high-impact issues and resolve test issues. We will consider small community contributions that improve cross-platform compatibility.

## Planned for .NET 7
- [x] #45017
- [x] #63937
- [x] #44453

## Backlog (in roughly priority order)
- [ ] #58492
- [ ] #53095
- [ ] #49107
- [ ] #45685

**Comment by davidfowl** [comment]
I want to leave some feedback here, but I don't have granular feedback, just an example of an API we wrote to "handle all of the edge cases when running a process on multiple platforms with the .NET APIs":

https://github.com/dotnet/tye/blob/6f9454e7b52bee30a0ba53f813678016b193c547/src/Microsoft.Tye.Core/ProcessUtil.cs#L28-L188

I'm not sure I'm proposing this exact API but I've love to see what the .NET 7 version of this API would look like after the changes made here.
