### ISSUE TITLE
[API Proposal]: 	 _umul128 arm64 intrinsic support

### ISSUE THREAD

**Issue by marcpems** [dotnet/runtime#64609]
### Background and motivation

commonly used for 128-bit unsigned multiplication and currently missing for Arm64

Docs for MSVC operation
https://docs.microsoft.com/en-us/cpp/intrinsics/umul128?view=msvc-170

Alternative implementation:
#pragma intrinsic(__umulh)

uint64_t _umul128(uint64_t a, uint64_t b, uint64_t *high) {
  *high = __umulh(a, b);
  return a * b;
}

### API Proposal

```C#
namespace System
{
public Int128
{
 public Int128 Mul(Int128 rhs);
}

public UInt128
{
 public UInt128 Mul(UInt128 rhs);
}
}


### API Usage

```C#
// accelerated large int multiply
var a = new Int128(0x10000000);
var b = new Int128(0x70000000);
var result = a.Mul(b);

// accelerated large uint multiply
var c = new UInt128(0x10000000);
var d = new UInt128(0x70000000);
var result = c.Mul(d);


```

**Comment by echesakovMSFT** [comment]
Doesn't `System.Math.BigMul` https://github.com/dotnet/runtime/blob/53d52884198b15d83e1d9c2ce8009ef2c6a015c2/src/libraries/System.Private.CoreLib/src/System/Math.cs#L221 intrinsified on Arm64 in https://github.com/dotnet/runtime/pull/47362 provide the same functionality as `_umul128`?

**Comment by tannergooding** [comment]
`BigMul` covers the scenario here. We could expose an `Int128`/`UInt128` but that would be tracked as a separate issue.
