### ISSUE TITLE
JIT: Generating rep movsb for cpblk with non-constant arguments

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6464]
Separated out from the discussion in dotnet/coreclr#6638

Currently the JIT makes a helper call to `JIT_MemCpy` for non-constant sizes. If it could generate `rep movsb` inline instead for amd64/x86, that would be much more efficient. Doing this would allow for a better implementation of `Buffer.MemoryCopy`, which right now has xmm as the best thing available.

category:cq
theme:block-opts
skill-level:intermediate
cost:medium

**Comment by AndyAyersMS** [comment]
We've settled on relying on the platform copy methods for these, so am going to close this.
