### ISSUE TITLE
❓ Survey: Repo contribution experience 2022

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#64649]
A couple years ago we surveyed you the members of the community in this repo to learn how we were doing as maintainers. 

One of the things we learned is that we needed to be more responsive to issues and PR’s. Since we added [community triagers](https://github.com/dotnet/runtime/issues/59744), updated our [area ownership](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) and added [automated workflows](https://github.com/dotnet/runtime/issues/62496). To offer more visibility into product planning we developed an [app to view our epics and stories](https://themesof.net/). To make the experience of offering a PR easier, we have added documentation, worked to increase build performance and squashed flaky tests. 

It's time to repeat the same survey. Whether you've been involved for years or you're relatively new please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=runtime

**Comment by Wraith2** [comment]
No dotnet/sqlclient ?

**Comment by danmoseley** [comment]
@Wraith2  - doh! It may be too late to edit it now. let me find out.

**Comment by danmoseley** [comment]
@Wraith2 it looks like it is. I'll offer to help them clone the survey to run themselves, and I'll be sure to include them in this next time around if they would like to.

**Comment by JulieLeeMSFT** [comment]
Hello, JIT contributors. It would be great if you can leave your feedback on JIT contribution experience and suggestions. 
@alexcovington, @am11, @anthonycanino, @DarkBullNull, @DeepakRajendrakumaran, @huoyaoyuan, @kant2002, @pedrobsaila, @SeanWoo, @shushanhf, @SingleAccretion, @SkiFoD, @t-mustafin,  @weilinwa, @Wraith2, and @yowl.

**Comment by huoyaoyuan** [comment]
Some quick response I missed in the survey:

I hope the experience of running and debugging library tests in VS can be improved. I did successfully run them, but with a latency of minutes. I understand the complexity of build process. **There should be a document for suggested inner-loop workflow.** The current doc is about running tests in a bunch.

**Comment by teo-tsirpanis** [comment]
How about `dotnet/fsharp`? If recreating the survey is too much effort you could instead create a separate survey for it.

**Comment by ergunr** [comment]
yes

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Theodore ***@***.***>
Envoyé le :vendredi 4 février 2022 01:20
À : ***@***.***>
Cc : ***@***.***>
Objet :Re: [dotnet/runtime] ❓ Survey: Repo contribution experience 2022 (Issue #64649)


How about dotnet/fsharp? If recreating the survey is too much effort you could instead create a separate survey for it.

**Comment by ergunr** [comment]
Finisch  Windows 11 insider preview

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Theodore ***@***.***>
Envoyé le :vendredi 4 février 2022 01:20
À : ***@***.***>
Cc : ***@***.***>
Objet :Re: [dotnet/runtime] ❓ Survey: Repo contribution experience 2022 (Issue #64649)


How about dotnet/fsharp? If recreating the survey is too much effort you could instead create a separate survey for it.

**Comment by danmoseley** [comment]
> How about `dotnet/fsharp`? If recreating the survey is too much effort you could instead create a separate survey for it.

Added -- they'll post their issue this afternoon. If you completed the survey, and now want to re-enter to do fsharp as well, here's the trick: https://github.com/dotnet/SqlClient/issues/1504#issuecomment-1029468419

**Comment by danmoseley** [comment]
Survey is now closed and we'll dig through your feedback. Thanks everyone that responded.
