### ISSUE TITLE
Warn when "attribute-dependent" types are used in 'typeof'

### ISSUE THREAD

**Issue by RikkiGibson** [dotnet/runtime#64655]
Currently the 'typeof' operator gives an error when certain types which can't round-trip are used as arguments. For example, `dynamic` or `string?`.

[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgNAExAagD4GIYFcA2OLA4CmABETAcQLABQtAAgAwn0CMALANy20D6JAXhIwiAdwDaAXRIBvWiQUkALgE8ADkQD2AMwAUm4ACsiAYyUBKOCQD01kpoDW8xao07dCFRTBQTlm3ZEAE5BmkEkAMIAyqwAnABsAEwgJAAqABakrlra9hpBEEphJCYQMDCaSiTApFgAzkQI9jDKmSSe3r7K6kTOCtnubIwA/P62ZCHF0QAc8QDMsSkZWT06ecGFxaXlldW1DU2aLRDCuPiEpEFE2sHkJisafd1uegAyUHVKADwdED4mAD4xnYKhNQkEngM3h9vkNhkCrONQcFwZDVnpdLAqhArFjquZzAFhJowWFaABfThAA==)
```cs
#nullable enable

using System.Collections.Generic;

_ = new[] {
    typeof(object), // ok
    typeof(dynamic), // error CS1962: The typeof operator cannot be used on the dynamic type
    typeof(string?), // error CS8639: The typeof operator cannot be used on a nullable reference type
    typeof(List<dynamic>), // no error
    typeof(List<string?>), // no error
    typeof((int a, int b)) // no error
};
```

It feels like the lines marked `no error` should be errors because the types in use can't round trip. Since it's not practical to add new errors to existing code, these scenarios should probably be handled in a warning wave.

Generic attribute type arguments have a similar issue where they can't round-trip types which require extra attributes. It feels like the same restriction should be applied there, but perhaps as an error since it's a new feature. dotnet/roslyn#54778

**Comment by jeffhandley** [comment]
@RikkiGibson I wanted to confirm that we can keep this issue assigned to you and see if there's anything you need from the Libraries team on this.

**Comment by RikkiGibson** [comment]
No, just wanted to give a heads up and find out if there are any objections.

**Comment by steveharter** [comment]
Closing here as is not a functional ask by the libraries team.

[RikkiGibson](https://github.com/RikkiGibson) can you give an update on this or link to tracking issue in Roslyn?
