### ISSUE TITLE
Make working with JSON and HTTP Requests easier

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/runtime#64676]
Hi

I migrated from Netonsoft.Json to System.Text.Json. Almost anything that I could do very easily there, is hugely complicated here.

Simple object access needs more lines of code. A simple loop over object properties is hard. A simple traversal is hard.

And worst of all, I need to know the value type in order to be able to extract a value. `JsonElement.GetString` fails for a property that has a numeric value.

It should not be so difficult. JSON is very easy. Please make changes to your API so that we can work easily with JSON in .NET.

Also as a web developer, I want to have full access to HTTP request raw data. It's impossible to get a posted JSON body, without going into a lot of pain to reconfigure and enable/disable stuff.

Right now, my understanding is that working with HTTP Request and JSON is hard in .NET. Please facilitate this access. Let us write less code. Give us more power to loop, to access the raw data.

Thank you

**Comment by layomia** [comment]
@Nefcanto can you please open individual tickets for each issue you're dealing with, along with a repro/sample of which APIs are difficult to use and what specifically you'd like to see?

Also see the new mutable JSON document types which make some of the issues easier - https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter?pivots=dotnet-6-0#use-jsonnode.
