### ISSUE TITLE
ContentRootPath and appsettings.json behavior differences between worker and console app

### ISSUE THREAD

**Issue by bitbonk** [dotnet/runtime#64698]
I have the following hello world worker service (Microsoft.NET.Sdk.Worker) and a console app (Microsoft.NET.Sdk) with the same simple worker source code and the same launch settings but the behavior regarding the `ContentRootPath` differs. 
Here is the output of the worker service:
```
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\source\WorkingDirTest\Worker1
``` 
and here the output of the same thing but as a console application:
```
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\source\WorkingDirTest\ConsoleApp1\bin\Debug\net6.0
```
I have two question about this:
1. How come that the `ContentRootPath` differs for those two application even though the launchsettings.json **are completely the same**? Where is the functionality that decides what `ContentRootPath` is used hidden? Is this a Visual Studio or CLI thing or is this a magic trick of `Microsoft.NET.Sdk.Worker`?
2. How come, that in the case of Worker1, the appsettings.json files are correctly read, even though they are not located in the current `ContentRootPath`?  I always thought the `ContentRootPath` is also used for the appsettings.

#### Worker1.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Worker1-60A0E77A-283F-44FC-B123-174989FA43F6</UserSecretsId>
  </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
    </ItemGroup>
</Project>
```
#### launchsettings.json for Worker1
```json
{
  "profiles": {
    "Worker1": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}

```
#### ConsoleApp1.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0" />
  </ItemGroup>
</Project>
```
#### launchsettings.json for ConsoleApp1
```json
{
  "profiles": {
    "ConsoleApp1": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_Environment": "Development"
      }
    }
  }
}
```

**Comment by eerhardt** [comment]
> How come that the ContentRootPath differs for those two application even though the launchsettings.json are completely the same? Where is the functionality that decides what ContentRootPath is used hidden? Is this a Visual Studio or CLI thing or is this a magic trick of Microsoft.NET.Sdk.Worker?

It's not magic, but it is a bit hidden. ContentRootPath gets initialized to `Environment.CurrentDirectory` here:

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L188-L190

When you F5 in VS, or `dotnet run` from the command line, the current working directory of your process is set by an MSBuild property named `RunWorkingDirectory`. If `RunWorkingDirectory` isn't set, then VS sets the executable location as the current working directory.

The "magic trick of Microsoft.NET.Sdk.Worker" is that it sets `RunWorkingDirectory` to be the directory of the `.csproj` file. See

https://github.com/dotnet/sdk/blob/d694a5e325c88b44e8054874cacde0ad391e8634/src/WebSdk/Worker/Targets/Microsoft.NET.Sdk.Worker.targets#L16

Nothing sets `RunWorkingDirectory` for a console app, so it gets the default experience. I assume if you set the current working directory in your launchsettings file, it will be respected.

> How come, that in the case of Worker1, the appsettings.json files are correctly read, even though they are not located in the current ContentRootPath? I always thought the ContentRootPath is also used for the appsettings.

You can debug the app to be sure, but from looking at the code the appsettings Json files get set up here:

https://github.com/dotnet/runtime/blob/6fc39aefa6f983782a377cd2356438eb11eed466/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L205-L206

and the "BasePath" of the ConfigurationBuilder is set to `HostingEnvironment.ContentRootPath` here:

https://github.com/dotnet/runtime/blob/6527b7fe83b95a195615c1081f345b6d34d716e7/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L223-L225

So the `appsettings.json` file should be found from wherever the `ContentRootPath` is set.

**Comment by bitbonk** [comment]
@eerhardt  Wow, thank you for the quick and detailed answer. It makes perfect sense now.
In the case of Worker1 the `appsettings.json` is of course located in the `ContentRootPath` (next to the `.csproj`).
