### ISSUE TITLE
[API Proposal]: String Default Constructor

### ISSUE THREAD

**Issue by ds5678** [dotnet/runtime#64714]
### Background and motivation

Currently, `string` can't be used as a generic type parameter for anything with the `new()` constraint. All the other primitive types do not have this issue because they're value types.

### API Proposal

```C#
namespace System
{
    public partial class String
    {
        //Return the empty string when using the default constructor
        public String() : this((char[])null) { }
    }
}
```

### API Usage

This is a simple example, but I think it illustrates the usage nicely. Even though it could be special cased for strings, that would be messier and harder to maintain.
```C#
static string ToStringNonNullable<T>(T? value) where T : new()
{
    return (value ?? new()).ToString();
}
```

My particular use case is more complicated. I'm dynamically generating assemblies, which use a custom dictionary class.
```C#
class CustomDictionary<TKey, TValue> where TKey : new() where TValue : new() { }
```
In order to get around my issue, I would have to make special cases for string, inflating my code substantially.
```C#
class CustomDictionary<TKey, TValue> where TKey : new() where TValue : new() { }
class CustomDictionary_stringKey<TValue> where TValue : new() { }
class CustomDictionary_stringValue<TKey> where TKey : new() { }
class CustomDictionary_stringKeyValue { }
```

### Risks

These empty strings would be reference equal, which might not be intuitive behavior, even though that is more performant. However, this does match the behavior of `String(char[]? value)`.

**Comment by Clockwork-Muse** [comment]
... Your signatures indicate you would be creating entries with defaulted **keys**, which seems surprising and unusual.  Especially because you wouldn't be able to mutate them afterwards (because that would almost certainly break your dictionary).  Usually, dictionaries are just dumb containers, without any insight into their contents, and for those few cases that do, specialization is warranted.

Are you sure you don't want some sort of extension method taking a value-constructing factory?
```csharp
public static TValue GetOrCreateValue<TKey, TValue>(this IDictionary<TKey, TValue> dict, TKey key, Func<TValue> valueConstructor)
{
	if (dict.TryGetValue(key, out TValue val))
	{
		return val;
	}

	return dict[key] = valueConstructor();
}
```
Note that you can create a default constructor factory by:
 - for things other than string, supplying the default constructor, or some other value 
 - for string, supplying `string.Empty`
 
Note that default constructed _values_ are - while not entirely unheard of - still unusual, and potentially of limited utility.

**Comment by ds5678** [comment]
For my use-case, I'm using AsmResolver (which is similar to Mono.Cecil) to generate hundreds of dll files. These files are similar, but not similar enough that I can directly reference any of them. I use a small amount of reflection to load whichever one I need. After that, they're accessed through interfaces and base classes. In other words, I can't use their type references in any extension methods, without a serious drain to performance from using reflection.

If you'd like to take a look at my code, I have my ideal version of it here:
https://github.com/AssetRipper/AssetRipper/tree/master/AssetRipperCommon/IO/DictionaryTest

My generated assemblies are here:
https://github.com/AssetRipper/AssemblyDumper
https://github.com/AssetRipper/AssemblyDumper/tree/v_development

In practice:
* Imagine my key type parameter is `string` and my value type parameter is some nonreferenceable generated type.
* I want to add a pair to the dictionary, so I call `void AddNew()`
* The newly added pair has the empty string as the key and a new object for the value
* Since the key is a primitive, I can set it to whatever I want.
* The value inherits from some predefined interface which I use to set its fields.

The usefulness to me isn't in being able to initialize a string to the empty string (though this may help others). Having `string` be usable with the `new()` constraint allows me to write cleaner and more reusable code.

**Comment by ds5678** [comment]
Also, if it wasn't abundantly clear, I'm willing to do the pull request for this issue (assuming it gets approved). I appreciate everything the .NET team does, and it would be entitled of me to request a feature without offering to implement it myself.

**Comment by Clockwork-Muse** [comment]
... That's not a dictionary (or, as sometimes called, hashtable).  That's a list of key-value pairs, equivalent to `List<KeyValuePair<TKey, TValue>>`.  Which is why you're getting away with changing the key.  You're ignoring the primary characteristic of a dictionary, which is the ability to retrieve values based on the key.

Given that you state that the value types are nonreferenceable, how are you creating your container class in the first place?  Regardless, you should be able to do something like this instead:

```csharp
// Not tested
public sealed class DictionaryAdder<TValue> where TValue : WhateverInterface, new()
{
    public TValue AddNew<TKey>(IDictionary<TKey, TValue> dict, TKey key)
    {
        return dict[key] = new TValue();
    }
}
```
... or even just set up your created object _outside_ a `Dictionary<TKey, WhateverInterface>`, and add it afterwards.

**Comment by ds5678** [comment]
I called it a dictionary because it's similar to a dictionary, dictionary is a concise word, and the keys are usually unique. I agree that a list of key value pairs is a more accurate description.

The "dictionaries" get instantiated in my generated assemblies via normal constructors of generated types.

Is adding a default constructor for string really that big of deal? I already said I would do the work. One line of code in the runtime would save me hundreds of lines in my own projects.

**Comment by tannergooding** [comment]
CC. @stephentoub 

I'm leaning towards this being potentially confusing and would not be likely widely used.

I would expect that most users are working around this as Clockwork-Muse suggested (as they would need to do with any other type and for downlevel targets or the .NET 6 LTS) which is to use some sort of factory or extension method.

**Comment by ds5678** [comment]
As far as I know, my proposed line of code would actually be one line and align with `string.Empty` since I defined it like this:
```c#
public String() : this((char[])null) { }
```
which should be slightly more performant than
```c#
public String() : this(Array.Empty<char>()) { }
```
Am I misunderstanding something?

**Comment by stephentoub** [comment]
> Am I misunderstanding something?

Again, string is special; normal rules don't apply.  Note how all of string's existing constructors are "extern", e.g.
https://github.com/dotnet/runtime/blob/684fe413df1ebd7695e2c07ae4c6202ab0d59a39/src/libraries/System.Private.CoreLib/src/System/String.cs#L63
Special code in the runtime then routes that constructor to an invocation of this static method:
https://github.com/dotnet/runtime/blob/684fe413df1ebd7695e2c07ae4c6202ab0d59a39/src/libraries/System.Private.CoreLib/src/System/String.cs#L65

**Comment by ds5678** [comment]
Okay, it's more than one line. It's still useful enough to me that I would be willing to do all the work for it.

**Comment by ds5678** [comment]
> I'm leaning towards this being potentially confusing and would not be likely widely used.

I disagree with this. If string had a default constructor, new programmers would be less likely to accidentally allocate empty strings.

Rather than
```c#
string str = "";
```
They would write
```c#
string str = new();
```

**Comment by stephentoub** [comment]
> new programmers would be less likely to accidentally allocate empty strings

`string str = "";` doesn't allocate.

**Comment by ds5678** [comment]
I understand. I'll find another way

**Comment by ds5678** [comment]
I figured out a high quality alternative solution for my particular situation.
