### ISSUE TITLE
[wasm] NodeJS samples failing at exit with emsdk `2.0.34`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#64727]
Hit on https://github.com/dotnet/runtime/pull/62499 . [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1588560&view=logs&j=329e2a42-7849-55e5-399c-04716ed16daa&t=49f2a43b-2af7-512f-9858-2f6cef5f8a91).

Fails for both CJS, and ES6 in the same way:

```
[02:11:49] fail: undefined
[02:11:49] fail: (Use `node --trace-uncaught ...` to show where the exception was thrown)
[02:11:49] info: Process node exited with 7
```

Running locally with `--trace-uncaught`:
```
undefined
Thrown at:
    at /Users/radical/dev/runtime/src/mono/sample/wasm/console-node-cjs/bin/Release/AppBundle/dotnet.js:12:2969
    at emit (node:events:394:28)
    at node:internal/process/execution:170:25
```

Seems to be because of undefined `quit_` function.

cc @pavelsavara 

|Build|Kind|Start Time|
|---|---|---|
[1589203](https://dev.azure.com/dnceng/public/_build/results?buildId=1589203)|Rolling|2022-03-02|

**Comment by pavelsavara** [comment]
I'm stealing `_quit` from inside emscripten [here](https://github.com/dotnet/runtime/blob/01cdd1dcaebcc9f2ab36027204142a6703a1b70b/src/mono/wasm/runtime/cjs/dotnet.cjs.lib.js#L15).  Perhaps they have replacement ?

Also, if the replacement could be exported with `EXPORTED_RUNTIME_METHODS` or `EXPORTED_FUNCTIONS` it would be much better than what we have now.

**Comment by radekdoulik** [comment]
I am able to reproduce it locally. The `undefined` comes from:

            process["on"]("uncaughtException", function (ex) {
                console.log(`ex: ${ex}`);
                if (!(ex instanceof ExitStatus)) {
                    throw ex;
                }
            });

the console output:
```
node --trace-uncaught .\main.cjs
Debugger.Debug: DEBUGGING ENABLED

mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
Hello World!
ex: undefined

C:\Users\rodo\git\wa-main\src\mono\sample\wasm\console-node-cjs\bin\Release\AppBundle\dotnet.js:4190
                    throw ex;
                    ^
undefined
Thrown at:
    at C:\Users\rodo\git\wa-main\src\mono\sample\wasm\console-node-cjs\bin\Release\AppBundle\dotnet.js:4190:21
    at emit (node:events:378:20)
    at node:internal/process/execution:163:25
```

**Comment by radekdoulik** [comment]
I think the issue here is that quit_ is called twice:
```
Debugger.Debug: DEBUGGING ENABLED

mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
Hello World!
quit_ function
status: 42
quit_ function
status: 1
Trace
    at process.<anonymous> (C:\Users\rodo\git\wa-main\src\mono\sample\wasm\console-node-cjs\bin\Release\AppBundle\dotnet.js:4189:25)
    at process.emit (node:events:378:20)
    at process._fatalException (node:internal/process/execution:163:25)
ex: undefined

C:\Users\rodo\git\wa-main\src\mono\sample\wasm\console-node-cjs\bin\Release\AppBundle\dotnet.js:4192
                    throw ex;
                    ^
undefined
Thrown at:
    at C:\Users\rodo\git\wa-main\src\mono\sample\wasm\console-node-cjs\bin\Release\AppBundle\dotnet.js:4192:21
    at emit (node:events:378:20)
    at node:internal/process/execution:163:25
```
