### ISSUE TITLE
Linq count is slower than linq where count

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/runtime#64728]
Linq Where before count is a lot faster than count with a predicate.
```c#
[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
public class Benchmarks
{
    private static List<int> Numbers = new(1000);

    static Benchmarks()
    {
        Random random = new Random(10);
        for (int i = 0; i < 1000; i++)
        {
            Numbers.Add(random.Next(int.MinValue, int.MaxValue));
        }
    }

    [Benchmark]
    public int LinqCount()
    {
        return Numbers.Count(num => num > int.MaxValue / 2);
    }

    [Benchmark]
    public int LinqWhereCount()
    {
        return Numbers.Where(num => num > int.MaxValue / 2).Count();
    }
}
```
I came across a reason for this is the `WhereListIterator<TSource>` which has a `GetCount` method. This method uses a normal indexer-based forloop. This `GetCount` method is used by the `Count` method without predicate parameters. But the count with predicate will use a normal for each loop.
So the general solution would be to check if the source collection is an `IList` or `IReadonlyList`. If it is then just use the indexer-based forloop because most of the time it would be an `IList` or `IReadonlyList`

**Comment by Neo-vortex** [comment]
I can confirm the difference

```

// * Summary *

BenchmarkDotNet=v0.13.1, OS=pop 21.10
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.101
  [Host]     : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
  DefaultJob : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT


|         Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|--------------- |---------:|----------:|----------:|-------:|----------:|
| LinqWhereCount | 2.903 us | 0.0299 us | 0.0265 us | 0.0114 |      72 B |
|      LinqCount | 8.981 us | 0.0625 us | 0.0554 us |      - |      40 B |

```

**Comment by eiriktsarpalis** [comment]
@ziaulhasanhamim your analysis is correct, in runtimes with speed optimizations enabled `WhereListIterator` is [calculating the count using indexers](https://github.com/dotnet/runtime/blob/bc76b4e22ccb690db1d0373a4fad11679e2ead46/src/libraries/System.Linq/src/System/Linq/Where.SpeedOpt.cs#L135) which is not the case in [`Count(Func<TSource, bool> predicate)`](https://github.com/dotnet/runtime/blob/bc76b4e22ccb690db1d0373a4fad11679e2ead46/src/libraries/System.Linq/src/System/Linq/Count.cs#L61). That's fine though, we generally don't try to aggressively apply optimizations for every LINQ method out of assembly size concerns and also because type tests incur perf penalties for sources that aren't collections. I don't think the particular `Count` overload meets the bar for applying this type of optimization.

Thanks for reporting the issue though!

**Comment by ziaulhasanhamim** [comment]
Most of the time we use sources that are collections.  And if where can check for specific collections and optimize why can't count? And if assembly size is a problem then we can just call the where method from Count with predicate.

```c#
public static int Count<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)

**Comment by eiriktsarpalis** [comment]
Consistency wrt optimizations is an explicit anti-goal for LINQ. As mentioned, such optimizations come at a cost so we reserve them for the most common of methods.

> And if assembly size is a problem then we can just call the where method from Count with predicate.

It would be interesting to see benchmarks of that approach for sources that are not collections. Avoiding regressions for these is more important than gaining performance in collections, particularly for a less widely used overload. You should also measure performance in the case where speed optimizations are disabled.

**Comment by ziaulhasanhamim** [comment]
There won't be a performance decrease for sources that are not collection. Because checking for the type of the source is a constant-time O(1) operation. So the performance for checking the type won't get larger for bigger sizes. 
My biggest problem with this is why Where(predicate).Count() and Count(predicate) do different things when they trying to achieve the same thing. 

If Where(predicate).Count() can do some optimizations for special IEnumerable why Count(predicate) can't do that? Why do two methods that look the same, behave the same, output the same but have different performances?  

most of the time the source will be a List or Array.  So Count(predicate) can go almost allocation-free (except the predicate) with those collections.

**Comment by eiriktsarpalis** [comment]
> There won't be a performance decrease for sources that are not collection. Because checking for the type of the source is a constant-time O(1) operation. So the performance for checking the type won't get larger for bigger sizes.

It's also adding another layer of enumerable/enumerators which entails more allocations and virtual calls. While it's true that runtime type checking is O(1), that constant-time penalty is important when considering small sources (whose performance is arguably more important than larger sizes). In any case, such assertions can be misguiding when it comes to performance, please measure with benchmarks.

It's important to note that getting the best possible performance has never been a design goal for LINQ. If performance is important then it's likely you'd rewrite your LINQ expression into an imperative loop or use one of the many IQueryable optimizing libraries that are available in the ecosystem.

**Comment by ziaulhasanhamim** [comment]
Here I've used a List and an Enumerable to figure out the difference.
```c#
public static class Linq
{
    public static int OptimizedCount<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
    {
        int count = 0;
        if (source is IReadOnlyList<TSource> sourceList) // arrays are also readonly list
        {
            for (int i = 0; i < sourceList.Count; i++)
            {
                checked
                {
                    if (predicate(sourceList[i]))
                    {
                        count++;
                    }
                }
            }
            return count;
        }
        foreach (TSource element in source)
        {
            checked
            {
                if (predicate(element))
                {
                    count++;
                }
            }
        }
        return count;
    }
}

[MemoryDiagnoser]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
public class Benchmarks
{
    private static List<int> NumbersList = new(1000);
    private static IEnumerable<int> NumbersEnumarable;

    static Benchmarks()
    {
        Random random = new Random(10);
        for (int i = 0; i < 1000; i++)
        {
            NumbersList.Add(random.Next(int.MinValue, int.MaxValue));
        }
        NumbersEnumarable = NumbersList.Select(n => n);
    }

    [Benchmark]
    public int LinqCount()
    {
        return NumbersList.Count(num => num > int.MaxValue / 2);
    }

    [Benchmark]
    public int LinqWhereCount()
    {
        return NumbersList.Where(num => num > int.MaxValue / 2).Count();
    }

    [Benchmark]
    public int LinqCountOnEnumerable()
    {
        return NumbersEnumarable.Count(num => num > int.MaxValue / 2);
    }

    [Benchmark]
    public int LinqWhereCountOnEnumerable()
    {
        return NumbersEnumarable.Where(num => num > int.MaxValue / 2).Count(); /// approach: public static int Count<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate) => source.Where(predicate).Count()
    }

    [Benchmark]
    public int LinqOptimizedCount()
    {
        return NumbersList.OptimizedCount(num => num > int.MaxValue / 2);
    }

    [Benchmark]
    public int LinqOptimizedCountOnEnumerable()
    {
        return NumbersEnumarable.OptimizedCount(num => num > int.MaxValue / 2);
    }
}
```
OptimizedCount method is just Count(predicate) method with a little code added
# Results
|                         Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------------- |----------:|----------:|----------:|-------:|----------:|
|                 LinqWhereCount |  4.019 us | 0.0452 us | 0.0401 us | 0.0305 |      72 B |
|             LinqOptimizedCount | 7.627 us | 0.0376 us | 0.0352 us |      - |         - |
|                      LinqCount | 11.074 us | 0.0960 us | 0.0898 us |      - |      40 B |
| LinqOptimizedCountOnEnumerable | 11.712 us | 0.0468 us | 0.0438 us | 0.0305 |      72 B |
|     LinqWhereCountOnEnumerable | 11.940 us | 0.0502 us | 0.0469 us | 0.0610 |     128 B |
|          LinqCountOnEnumerable | 12.0465 us | 0.0669 us | 0.0626 us | 0.0305 |      72 B |

```c#
public static int Count<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate) => source.Where(predicate).Count()

**Comment by eiriktsarpalis** [comment]
Numbers look ok, with the exception of allocations which nearly double for both collections and enumerable sources. I don't think the trade-offs are worth it. Thanks for investigating!

**Comment by ziaulhasanhamim** [comment]
```c#
    public static int OptimizedCount<TSource>(this IEnumerable<TSource> source, Func<TSource, bool> predicate)
    {
        int count = 0;
        if (source is IReadOnlyList<TSource> sourceList) // arrays are also readonly list
        {
            for (int i = 0; i < sourceList.Count; i++)
            {
                checked
                {
                    if (predicate(sourceList[i]))
                    {
                        count++;
                    }
                }
            }
            return count;
        }
        foreach (TSource element in source)
        {
            checked
            {
                if (predicate(element))
                {
                    count++;
                }
            }
        }
        return count;
    }
```
Count method can't have an implementation like this only because of assembly size reasons?
