### ISSUE TITLE
FileStream's BufferedFileStreamStrategy lacks GC.SuppressFinalize(this) call causing it eligible for Finalization Queue

### ISSUE THREAD

**Issue by rpnetcoder** [dotnet/runtime#64741]
### Description

BufferedFileStreamStrategy lacks GC.SuppressFinalize(this) call.

According to the dispose pattern, when an object has a finalizer, the object should call GC.SuppressFinalize(this) method inside Dispose() method in order to avoid to be eligible for Finalization Queue thus increasing GC pressure and impacting overall application performance.

### Data

The website memory analysis indicates that FileStream's BufferedFileStreamStrategy instances are present in the Finalization Queue.

![Memory](https://user-images.githubusercontent.com/98753567/152342063-fc86a019-6ebb-4447-8224-9a577ae390b9.PNG)

### Configuration

Windows 10.0.19044.1503 (21H2) x64, .NET 6.0.101

**Comment by stephentoub** [comment]
> BufferedFileStreamStrategy lacks GC.SuppressFinalize(this) call.

It doesn't.  BufferedFileStreamStrategy derives from Stream, whose Dispose method calls GC.SuppressFinalize.
https://github.com/dotnet/runtime/blob/7550df8b58452abf4f45518335914070f4f4f54f/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L158-L167

**Comment by rpnetcoder** [comment]
Not exactly, because FileStream, which holds the instance of BufferedFileStreamStrategy, has the following code:

`protected override void Dispose(bool disposing) => _strategy.DisposeInternal(disposing);`

FileStream should call _strategy.Dispose() rather than _strategy.DisposeInternal(disposing) to make GC.SuppressFinalize(this) from base class to be called.

**Comment by stephentoub** [comment]
> FileStream, which holds the instance of BufferedFileStreamStrategy, has the following code

Ah, then yes, that's probably an issue.

**Comment by rpnetcoder** [comment]
This issue, as well as https://github.com/dotnet/runtime/issues/64632 (where FileStream allocates buffer inefficiently) were detected when profiling a heavily loaded image editing website. It would be great if .NET Team fix them as I believe that it impacts not only this website, but many people around who use FileStream in their apps/websites.

And thanks for your efforts to improve .NET performance!
