### ISSUE TITLE
[API Proposal]: Add Today to DateOnly and Now to TimeOnly

### ISSUE THREAD

**Issue by Gigottine** [dotnet/runtime#64757]
### Background and motivation

The new DateOnly and TimeOnly are very great.
In my development, i often need Today and Now for this object.
I think it would be great if it is available in framework.

### API Proposal

  ```C#
namespace System
{
    public readonly struct DateOnly : IComparable, IComparable<DateOnly>, IEquatable<DateOnly>, ISpanFormattable
    {
        // Returns a DateOnly representing the current date.
        public static DateOnly Today => FromDateTime(DateTime.Today);
    }
}

namespace System
{
     public readonly struct TimeOnly : IComparable, IComparable<TimeOnly>, IEquatable<TimeOnly>, ISpanFormattable
    {
         // Returns the TimeOnly indicates the time elapsed since midnight.
        public static TimeOnly Now => FromTimeSpan(DateTime.Now.TimeOfDay);
    }
}
```

### API Usage

```C#
var today = DateOnly.Today;

var now = TimeOnly.Now;
```

**Comment by tarekgh** [comment]
@Gigottine thanks for your request. This has been discussed before and decided not to do it and can use DateTime for that. Please read the discussion in the issue https://github.com/dotnet/runtime/issues/53498 for more details behind the reasons not doing it.
