### ISSUE TITLE
Arm64: Evaluate if it is possible to combine subsequent field loads in a single load

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#64815]
Evaluate to see how feasible it would be to combine loads of subsequent fields using `ldp` instead of loading them separately during the use. It cannot be considered as a peep-hole optimization, but an analysis is needed in earlier phases to check around for consecutive field loads and if found one, combine them to a single load.

```c#

class Body { public double x, y, z, vx, vy, vz, mass; }
...
foreach (var b in bodies) {
    b.x += dt * b.vx; b.y += dt * b.vy; b.z += dt * b.vz;
}
```

Below code is generated for the loop that deals with multiplication of `double`.
- `#1` can be combined into `ldp dX, dY, [x3, #8] `
- `#2` can be combined into `ldp dX, dY, [x3, #32] `
- `#3` can be combined into `stp dX, dY, [x3, #8] `

```asm
G_M56457_IG05:              ;; offset=0114H
        D37D7C43          ubfiz   x3, x2, #3, #32
        91004063          add     x3, x3, #16
        F8636803          ldr     x3, [x0, x3]
        FD400470          ldr     d16, [x3,#8]   ; <-- #1
        FD401071          ldr     d17, [x3,#32]  ; <-- #2
        1E710811          fmul    d17, d0, d17
        1E712A10          fadd    d16, d16, d17
        FD000470          str     d16, [x3,#8]   ; <-- #3
        FD400870          ldr     d16, [x3,#16]  ; <-- #1
        FD401471          ldr     d17, [x3,#40]  ; <-- #2
        1E710811          fmul    d17, d0, d17
        1E712A10          fadd    d16, d16, d17
        FD000870          str     d16, [x3,#16]  ; <-- #3
        FD400C70          ldr     d16, [x3,#24]
        FD401871          ldr     d17, [x3,#48]
        1E710811          fmul    d17, d0, d17
        1E712A10          fadd    d16, d16, d17
        FD000C70          str     d16, [x3,#24]
        11000442          add     w2, w2, #1
        6B02003F          cmp     w1, w2
        54FFFD8C          bgt     G_M56457_IG05

```

Reference: https://godbolt.org/z/9jY5hYnoa

category:implementation
theme:codegen
skill-level:intermediate
cost:medium
impact:medium

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by echesakovMSFT** [comment]
Un-assigning myself
cc @BruceForstall

**Comment by JulieLeeMSFT** [comment]
@BruceForstall please move to future if we cannot accomodate this in .NET 7.

**Comment by TIHan** [comment]
@jkotas Is this transformation safe to do under the memory model? I ask because we would be combining two `ldr`s together when they both have a store in-between.

**Comment by EgorBo** [comment]
@TIHan `ldp` is practically the same as two subsequent `ldr` the only real difference that it save 4 bytes of instructions in codegen (might make some hot loop body smaller, etc)

**Comment by jkotas** [comment]
> Is this transformation safe to do under the memory model?

Yes, it is fine. From https://github.com/dotnet/runtime/blob/main/docs/design/specs/Memory-model.md#order-of-memory-operations:  The effects of ordinary reads and writes can be reordered as long as that preserves single-thread consistency. Such reordering can happen both due to code generation strategy of the compiler or due to weak memory ordering in the hardware.

**Comment by jkotas** [comment]
> Might be worth calling this out more explicitly in the memory model doc?
> never actually define what "single-thread consistency" means.

cc @VSadov 

I believe that we are assuming the "single-thread consistency" definition from ECMA 335 I.12.6.4 here: "Conforming implementations of the CLI are free to execute programs using any technology that guarantees, within a single thread of execution, that side-effects and exceptions generated by a thread are visible in the order specified by the CIL. For this purpose only volatile operations (including volatile reads) constitute visible side-effects."

**Comment by VSadov** [comment]
Re: using ldp instead of two ldr

Yes. If two nonvolatile loads are adjacent they can certainly be emitted as a single ldp. It is basically just a matter of encoding. Hardware would not guarantee the relative order of the loads anyways.

This is also applicable in cases where the loads are not adjacent, but can be moved together without violating memory model. 

I think internally JIT uses slightly different form of analysis - in terms of intervening accesses, but it is basically a superset of whether the operations can be moved together, just easier to compute in the JIT implementation.

**Comment by VSadov** [comment]
We have some existing optimizations where we coalesce reads from the same location. 
I think folding two ldr into one ldp would be valid under the same conditions/analysis.

**Comment by jkotas** [comment]
> I would have assumed exceptions and stores are both counted as "visible" as well.

RIght, it is what the paragraph that I quoted is trying to say. "side-effects and exceptions generated by a
thread are visible in the order specified by the CIL. For this purpose only volatile operations
(including volatile reads) constitute visible side-effects."

**Comment by VSadov** [comment]
Re: exceptions

For two ordinary ldr reads, the order of reads is not defined - that is in terms of the values that are being read. In terms of exceptions the reads happen in program order (speculative reads do not cause out of order faults).

I believe ldp preserves the order of faults. I did not see in the spec something like "if one read faults, then whether the other read happens is undefined". 
If that was the case, I think we might need to think harder about when this optimization is valid.

The [pseudocode given for LDP semantics](https://developer.arm.com/documentation/ddi0596/2020-12/Base-Instructions/LDP--Load-Pair-of-Registers-) seems to indicate that T1 is loaded before T2 and overall ldp does look like just a compact form of encoding two subsequent reads. 

Perhaps it is worth reaching to ARM folks to clarify that, just in case?

(interestingly the result _is_ undefined if T1 and T2 are the same register, I assume it refers mostly to the fetched value though)

**Comment by jkotas** [comment]
The effect of the ldp instruction has to happen fully or not at all. If it was not the case, page faults from instructions like `ldp r1, r2, [r1]` would be impossible to handle.
