### ISSUE TITLE
[DllImportGenerator] ignore DLLIMPORTGEN003

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#64811]
DllImportGenerator produces following error when targeting <net5 frameworks
```
CSC : error DLLIMPORTGEN003: 'GeneratedDllImportAttribute' cannot be used for source-generated P/Invokes on the current target framework. Source-generated P/Invokes require .NET 5.0 or above. [/home/supine/UltralightNet/UltralightNet/UltralightNet.csproj]
```
but if i simply copy-paste generated code to source with netstandard2/net45 targets it will work.

**Comment by jkoritzinsky** [comment]
The generator has already been updated in main to only warn on an unknown tfm and have well-specified downlevel behavior. We just haven't shipped a new package in a while.

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 The prototype is no longer being updated. This has been addressed in the official version that will eventually supersede the prototype in the feed.

See https://github.com/dotnet/runtime/issues/60595
