### ISSUE TITLE
NativeAOT publish warning messages

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#64822]
When publish on Linux to `win-x64` I receive following message:
```
Microsoft.NETCore.Native.Publish.targets(63,5): error : Cross-OS native compilation is not supported. https://github.com/dotnet/corert/issues/5458
```
The https://github.com/dotnet/corert/issues/5458 is probably not what I want to see in Net 7. Same applied to other messages which point to CoreRT repository. I would say that there need for separate RD.xml article, but I have hopes that it would be replaced with illink format.

**Comment by MichalStrehovsky** [comment]
This now errors out with:

```
C:\Program Files\dotnet\sdk\7.0.100-rc.1.22431.12\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.Publish.targets(58,5): error : Cross-OS native compilation is not supported. [C:\hello\hello.csproj]
```

Good enough.
