### ISSUE TITLE
JIT Testing Strategies for .NET 7

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#64832]
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Summary

There are a variety of improvements to be made in how we troubleshoot and test the JIT. The goal is to be able to diagnose issues more efficiently, and to verify correctness of IL and its code-gen.

#### @TIHan 

- [x] Learning paper for a deep dive on optimization correctness testing strategies from other compilers

Future
- [ ] https://github.com/dotnet/runtime/issues/32648 (JIT IL verification removal)
    - [ ]  https://github.com/dotnet/runtime/issues/64399
- [ ] https://github.com/dotnet/runtime/issues/63198 (ILVerify)

#### @BruceForstall 
- [x] JIT Test Monitor for daily pipeline monitoring

#### @EgorBo 

- [ ] (User friendly JIT diagnostics)
- [ ] (Application level benchmarks)

### SuperPMI improvements

Generally, SuperPMI will be improved on an "as needed" basis, and as resources are available to work on it. The following items are the most likely to get attention.

- [ ] (Bruce WIP) https://github.com/dotnet/runtime/issues/61483
- [x] https://github.com/dotnet/runtime/issues/49949

## Moved to .NET 8
- [ ] https://github.com/dotnet/runtime/issues/62732 (ILVerify)

We really should find time to implement:

- [x] https://github.com/dotnet/runtime/issues/47543 
- [ ] Add (automated) collections for additional open source components, e.g. Roslyn and Roslyn tests, F# tests, Paint.NET
- [x] https://github.com/dotnet/runtime/issues/59446 
- [ ] We have ASP.NET collections, but they are manually done. Automate them. https://github.com/dotnet/runtime/issues/47545.

category:planning
theme:testing
skill-level:intermediate
cost:extra-large
impact:large

**Comment by bruce** [comment]
👋 Just dropping by to mention you've tagged the wrong Bruce on this issue.

**Comment by BruceForstall** [comment]
Closing since this is now old.
