### ISSUE TITLE
Several classes in System.Private.Xml are creating StringBuilders when formatting simple types like DateTime,TimeSpan

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/runtime#64853]
When I checked how much one request to our API costs found this callstack
![image](https://user-images.githubusercontent.com/12857389/152653993-f74893d7-f0ec-4b48-97d2-fd3262e5bfda.png)

This makes me curious why StringBuilder was used to format DateTime as in most cases it will be a small set of chars.
When looking at code of XmlConvert, I've found several things that can be optimized:

- ToString with TimeSpan is creating XsdDuration and calling it's ToString() which creates StringBuilder(20)
- ToString with DateTime, same with XsdDateTime
- ToString with DateTimeOffset -> XsdDateTime

I would say that whole class XmlConvert should be checked and optimized(maybe using Span<>) or ValueStringBuilder.
Please ignore if you already have plans for this or if you think that it doesn't worth.

**Comment by stephentoub** [comment]
> I would say that whole class XmlConvert should be checked and optimized(maybe using Span<>) or ValueStringBuilder.
> Please ignore if you already have plans for this or if you think that it doesn't worth.

I took a quick peek, and many of them appear to be reasonable to change.

**Comment by danmoseley** [comment]
@TrayanZapryanov  are you interested in offering a PR for some?

**Comment by TrayanZapryanov** [comment]
Yes, I would like to try.

**Comment by jeffhandley** [comment]
That's great, @TrayanZapryanov! I'll assign this issue to you. Please comment here if you need any guidance or if you have any trouble getting your local build and tests going. You can also post Draft PRs if you want to get early feedback on the approach you take for the changes.

**Comment by TrayanZapryanov** [comment]
@jeffhandley Do you think if it will be a problem to use ValueStringBuilder inside this library?

**Comment by jeffhandley** [comment]
> Do you think if it will be a problem to use ValueStringBuilder inside this library?

I think that would be OK. I see that we're including `ValueStringBuilder` as an implementation detail in several other libraries ([code search](https://cs.github.com/?scopeName=dotnet%2Fruntime&scope=repo%3Adotnet%2Fruntime&q=ValueStringBuilder.cs+language%3Axml)).

@stephentoub can you think of any reasons not to?

**Comment by danmoseley** [comment]
It's fine to use VSB. The code is just old so didn't previously.
