### ISSUE TITLE
[Docker] The framework 'Microsoft.NETCore.App', version '6.0.0' (x64) was not found.

### ISSUE THREAD

**Issue by minskiter** [dotnet/runtime#64862]
### Description

root@e197ba8c4a10:/app# dotnet --info

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
root@e197ba8c4a10:/app# ls
TestApp  TestApp.deps.json  TestApp.dll  TestApp.pdb  TestApp.runtimeconfig.json
root@e197ba8c4a10:/app# dotnet TestApp.dll
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.1.21451.13 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.11-x64

### Reproduction Steps
``` Dockerfile
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TestApp/TestApp.csproj", "TestApp/"]
RUN dotnet restore "TestApp/TestApp.csproj"
COPY . .
WORKDIR "/src/TestApp"
RUN dotnet build "TestApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestApp.dll"]
```

### Expected behavior

Work well.

### Actual behavior

The framework 'Microsoft.NETCore.App', version '6.0.0' (x64) was not found.

### Other information

If I replace the runtime with the sdk it works just fine.
``` Dockerfile
#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["TestApp/TestApp.csproj", "TestApp/"]
RUN dotnet restore "TestApp/TestApp.csproj"
COPY . .
WORKDIR "/src/TestApp"
RUN dotnet build "TestApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TestApp.dll"]
```

**Comment by vitek-karas** [comment]
I don't know about the docker setup, but the failure is pretty clear: You have `6.0.0-rc1` installed, but the app you're trying to run requires `6.0.0`. Per [semantic versioning](https://semver.org/) all pre-release versions with the same major.minor.patch (for example `6.0.0-rc1` is a pre-release version) are considered lower than any release version (`6.0.0` is a release version). As such the pre-release can't be used to run an app which requires a release version.

**Comment by minskiter** [comment]
> I don't know about the docker setup, but the failure is pretty clear: You have `6.0.0-rc1` installed, but the app you're trying to run requires `6.0.0`. Per [semantic versioning](https://semver.org/) all pre-release versions with the same major.minor.patch (for example `6.0.0-rc1` is a pre-release version) are considered lower than any release version (`6.0.0` is a release version). As such the pre-release can't be used to run an app which requires a release version.

I see. But the docker image `mcr.microsoft.com/dotnet/aspnet:6.0` that provides dotnet 6.0-rc is different from the image `mcr.microsoft.com/dotnet/sdk:6.0`. I couldn't found that official runtime image in aspnet docker repository.

**Comment by agocke** [comment]
@richlander Do you know who to contact about docker images?

**Comment by gterdem** [comment]
@minskiter
Probably it is using old image cache. Try deleting dangling images and `mcr.microsoft.com/dotnet/aspnet:6.0` image from your image repo.

**Comment by minskiter** [comment]
> @minskiter Probably it is using old image cache. Try deleting dangling images and `mcr.microsoft.com/dotnet/aspnet:6.0` image from your image repo.

Thanks! it works.
