### ISSUE TITLE
[API Proposal]: 64 bit Hashcode for objects

### ISSUE THREAD

**Issue by Developer-Alexander** [dotnet/runtime#64870]
### Background and motivation

There doesn't seem to be a universal API to generate a 64-bit hash code from any object. (at least I don't know of any)

It would be desirable to have a 64-bit equivalent of object.GetHashCode(), although it doesn't necessarily have to be a method of class `object` directly.

Perhaps the `RuntimeHelpers` class would be a suitable place.

I don't know if such API should return a `long` or an `ulong`. Since the sign bit of a 64 bit hash code would not have a practical meaning maybe `ulong` woulf be the better choice.

If it would provide some performance benefits like prevent boxing it might be useful to provide a generic version of the API aswell.

### API Proposal

```C#
ulong RuntimeHelpers.GetHashCode64(object? item);
ulong RuntimeHelpers.GetHashCode64<T>(T item);
```

### API Usage

```C#

long item = 5L
ulong hashCode = RuntimeHelpers.GetHashCode64(item);
```

**Comment by teo-tsirpanis** [comment]
And how would the 64-bit hashcode logic be overriden if it were not a virtual method on `object`? Some types' hashcodes are based on a subset of their fields.

**Comment by Tornhoof** [comment]
Why do you need a 64 bit hash code? Do you encounter many collisions with 32 bit hash code in your use case?

**Comment by Developer-Alexander** [comment]
> And how would the 64-bit hashcode logic be overriden if it were not a virtual method on `object`? Some types' hashcodes are based on a subset of their fields.

I would prefer to extend object by the GetHashCode64() API. So using RuntimeHelpers would already Plan B for me.
But someone explained to me that it is very unlikely that class object will be ever be touched.

An alternative could be to introduce a new Interface Or Helper class that logic can be overwritten. (Similar  to comparer<T>)

**Comment by Developer-Alexander** [comment]
> Why do you need a 64 bit hash code? Do you encounter many collisions with 32 bit hash code in your use case?

I have written a library for large collections including a hash based dictionary. When a large number of items get stored There will be Mandy collisions. Unfortunatly dotnet does not offer any solution for this.

**Comment by danmoseley** [comment]
For your use case, can you not supply your own hashcode provider to the collection? 

If you need this on arbitrary objects that is much more tricky: unless overridden, object's hashcode is stored specially in runtime datastructures. It would need a very compelling reason to extend that I suspect.

Also how many objects are in your collection typically?

**Comment by Developer-Alexander** [comment]
As Far as I know the hash of an object is calculated as 64 Bit value based on a algorithm patended by Microsoft And Then it is cropped to 32 bit because for object.GetHashCode() only returns 32 bit.
If thats true providing an additional API without cropping the Hash to 32 Bit would come basically for free.

**Comment by Developer-Alexander** [comment]
> Also how many objects are in your collection typically?

There can be multiple Billion of elements.

**Comment by jkotas** [comment]
> As Far as I know the hash of an object is calculated as 64 Bit value based on a algorithm patended by Microsoft

That is not correct. The hashcode of an object (`RuntimeHelpers.GetHashCode` and also the default `Object.GetHashCode` implementation) is a random number that gets attached to the object using a mechanism similar to `DependentHandle` (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.dependenthandle).

**Comment by rickbrew** [comment]
Custom collections and custom hashcode providers (based on your own `IEquatable64<T>` and `IEqualityComparer64<T>`) would work for most types, but would not be sufficient for object-identity based hashing (base `object.GetHashCode()` / `RuntimeHelpers.GetHashCode()`). That scenario could be served with `ConditionalWeakTable<object, long>`, where each new object is assigned a 64-bit value that gets "stapled" to it. The performance may not be as good but it would work.

**Comment by danmoseley** [comment]
If you are storing billions of objects you are always quite specialized and it seems reasonable to me to store objects that implement their own hashcode.

**Comment by Clockwork-Muse** [comment]
Duplicate of #28709
And was referenced in the context of another issue you opened, #46586
