### ISSUE TITLE
Reopen OpenSSL issue in #44191 #46271

### ISSUE THREAD

**Issue by cnSchwarzer** [dotnet/runtime#64886]
### Description

In #44191 and #46271, people use Ubuntu with OpenSSL compiled with SecLevel=2 encountered the handshake error as some server does not support cipher the .NET 5/6 required, however the `curl` still can establish the connection.

We sure can edit openssl.conf to resolve the issue. But the solution took me 3 hours to find out in #46271. This seems the only solution, but not in the breaking change blog and it is hard to find.

Is there any possibility that can provide some API to control the supported cipher and tls version globally? As most of librarys use SslStream and we cannot set options on them.

### Reproduction Steps

See #44191 #46271

### Expected behavior

The connection should be established as expected in Ubuntu 18/20 platform. 
The connection is established in Windows 10, so there's platform inconsistency and is very confusing what happened.

### Actual behavior

See #46271

### Known Workarounds

In #46271 says:
An observation, openssl in Ubuntu 20.04 is compiled with `-DOPENSSL_TLS_SECURITY_LEVEL=2`. Changing the security level back to 1 gets things working again:

Adding this to the top of /etc/ssl/openssl.cnf:

```
openssl_conf = default_conf
```
and this to the bottom of it:
```
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT:@SECLEVEL=1
```
I suspect this is related to the site not supported any forward secrecy cipher suites. I'm not recommending this change one way or another, but it appears to play a part of the issue at hand.

**Comment by bartonjs** [comment]
Transferred to System.Net.Security on the basis of the question `Is there any possibility that can provide some API to control the supported cipher and tls version globally?`

I'm guessing the answer will be "no", since that sounds a lot like the old ServicePointManager statics.

**Comment by cnSchwarzer** [comment]
> Transferred to System.Net.Security on the basis of the question `Is there any possibility that can provide some API to control the supported cipher and tls version globally?`
> 
> I'm guessing the answer will be "no", since that sounds a lot like the old ServicePointManager statics.

However it cannot control .NET behaviour about OpenSSL it uses. And while the curl works well with default c

**Comment by wfurt** [comment]
The path via `openssl.cnf` impacts only the defaults AFAIK. curl ignores that config AFAIK the same way as older .NET versions did. The call for more secure default come form outside and above .NET and caused (documented) breaking change. And it is not going to be reverted as far as I can see. 

Now, there are several choices somebody can take. Changes in Ubuntu (and others) were made for a reason (outside of .NET). One can choose to use OS/version with less secure restrictions. or you can try to convince bistro vendor to lover security expectations. 

You can also use [CipherSuitesPolicy](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy?view=net-6.0) if the application wishes to deviate from OS default for what ever reason. That gives you granularity to update the security level per-site, globally or on individual SslStream. I don't know if this is the API you asked for @cnSchwarzer bit it exists for long and it _should_ work AFAIK. 
There _may_ be some other changes in OpenSSL that _could_ prevent use of very weak ciphers. If you have specific case where CipherSuitesPolicy does not work for you, feel free to open separate issue.

**Comment by karelz** [comment]
Triage: No answer in 2 weeks about the workaround. Closing again. Feel free to reopen if there is more info available.

**Comment by cnSchwarzer** [comment]
@wfurt There're lot of situations that libraries use SslStream so deep in their code, and doesn't provide such an API to pass CipherSuitesPolicy. Neither .NET provides a global default CipherSuitesPolicy, so the deploying server must manually change the `openssl.conf`.
The problem is, it is confusing for developers to figure out what .NET 6 hosting difference can cause their code to fail. In Windows it works sound, after deployed to Ubuntu 20.04 it throws SSL error, and is not alerted by .NET. Although an blog CAN be searched, it neither provides an solution, we still need to search this repo's issue to find a workaround.

**Comment by wfurt** [comment]
I agree with you in spirit @cnSchwarzer. Windows _could_ change the crypto defaults but it did _not_. If you disable weak crypto in Windows registry .NET will fail on Windows same way IMHO. 

As far as the libraries and layers I can see that being pain point. But it seems like we are unlikely to dome up with global setting.  @bartonjs is right that it would be similar to `ServicePointManager` and we abandoned that for good reasons.

**Comment by cnSchwarzer** [comment]
@wfurt Agreed, I think the easiest way is to correct the workaround in [Link](https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux) to the detailed one above. The blog provided one is not that detailed.
