### ISSUE TITLE
Add String.JoinLines or EnumerableExtensions.JoinLines

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#64895]
I find it to be a common requirement to take a sequence of items and concat them separated by newlines. A motivating example:

```
var customerNames = GetCustomerNames();

Console.WriteLine("Customers:");
Console.WriteLine(customerNames.JoinLines());
```

I have this helper in my utility library and I use it frequently. It should be built-in. It seems like a conceptually clean and simple API that would fit well within the framework.

The existing version `string.Join(Environment.NewLine, items)` is OK, but it is too verbose for this common and conceptually simple requirement. `items.JoinLines()` is so much better.

Design discussion:

1. Should this be `String.JoinLines(items)` or `items.JoinLines()`?
2. Should it be `JoinLines` or `ConcatLines`?
3. This will use the system newline separator by default. This should be overridable with an optional argument.
4. Do we want to support only `IEnumerable<string>`, or `IEnumerable<object>` and call `ToString`? In my experience, the latter is very useful.
5. The implementation can optimize for cases of few items by buffering the first few in local variables.

**Comment by stephentoub** [comment]
> The existing version string.Join(Environment.NewLine, items) is OK, but it is too verbose for this common and conceptually simple requirement. items.JoinLines() is so much better.

I don't think this is worth adding. I don't think it's "so much better", and everything we add comes at a cost, not just for us, but for consumers of the APIs as well. For me this doesn't meet the bar.

**Comment by EgorBo** [comment]
It also is not clear what is going to use `\n` or `\r\n` under the hood

**Comment by Clockwork-Muse** [comment]
> A motivating example:

That's not actually a particularly motivating example, because you're creating a (potentially much) longer string (plus all the intermediate ones) just to throw it away, as opposed to doing something like:
```csharp
foreach (var name in customerNames)
{
    Console.WriteLine(name);
}

// Or, assuming customerNames is actually a list
customerNames.ForEach(Console.WriteLine);
```
.... which requires (relatively speaking) no additional memory.

**Comment by jeffhandley** [comment]
Closing per the discussion above. Thank you for the suggestion nonetheless, @GSPP.
