### ISSUE TITLE
What is the update mechanism of timezone? Can tzdata be automatically updated when timezone rules change

### ISSUE THREAD

**Issue by sunliusi** [dotnet/runtime#64901]

**Comment by tarekgh** [comment]
On Windows, .NET reads the zone data from Windows registry. Usually, machines get Windows updates which include the zone data update. That will be reflected on .NET.

On Linux, .NET depends on tzdata package installed by the user on that machine. Users need to manually update this package to get any update. There is not any automatic update done by .NET as this is user wide package and not .NET package. 

I am closing the issue but feel free to send any more questions if you have any.

**Comment by sunliusi** [comment]
Thanks a lot.
How can a client load tzdata from local independent of os?

**Comment by Clockwork-Muse** [comment]
You'd have to create your own mechanism, and probably manually create the timezone on the .NET side (Rather than loading it from the OS, especially if you may otherwise have permissions issues).

The bigger question here would be "why?".  Especially as you **probably** need to be concerned with more than just your client-local timezone.  Either the client needs to know about other timezones, and/or the client timezone actually needs to be pulled from some other authoritative source (for example, whatever server is storing event data).  Dealing with distributed date/time math and timezones is a non-trivial exercise.

**Comment by tarekgh** [comment]
In general, we recommend always updating the tzdata package on the machine if needed. This is best practice. Otherwise, the users of the machines will start seeing inconsistency between apps on the same machine.

**Comment by sunliusi** [comment]
> In general, we recommend always updating the tzdata package on the machine if needed. This is best practice. Otherwise, the users of the machines will start seeing inconsistency between apps on the same machine. 

The client needs to convert Unix timestamps of different time zones to time for display. If the user turns off Windows Update, an error will be displayed. Loading from a private path ensures that the same version of the client is displayed consistently

**Comment by tarekgh** [comment]
Wouldn't the client need to match the system in general? if the user turns off Windows, the user can experience some discrepancy. 

If you still want to go this route, you can use [TimeZoneInfo.CreateCustomTimeZone](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.createcustomtimezone?view=net-6.0#system-timezoneinfo-createcustomtimezone(system-string-system-timespan-system-string-system-string-system-string-system-timezoneinfo-adjustmentrule()-system-boolean)) to create your custom time zone and use it for the conversion.

**Comment by svick** [comment]
This may be an overkill, but an alternative approach is to use Noda Time, which [comes with its own time zone database](https://nodatime.org/2.4.x/userguide/tzdb) and also allows you to load the database from a file.

**Comment by sunliusi** [comment]
> This may be an overkill, but an alternative approach is to use Noda Time, which [comes with its own time zone database](https://nodatime.org/2.4.x/userguide/tzdb) and also allows you to load the database from a file.

great，that's what i want.

**Comment by tarekgh** [comment]
> Is app-local icu workable?

Do you mean having the tz data updated in ICU version and deploy that as app-local? If so, then yes if you are willing to redeploy your whole app.
