### ISSUE TITLE
C# application referencing /clr:netcore creating its own static instances

### ISSUE THREAD

**Issue by fiercekittenz** [dotnet/runtime#64905]
I have a WPF net5.0-windows C# application that references a /clr:netcore targeted Managed C++ library. The C# application instantiates a static instance of a core system. When the Managed C++ accesses that instance, instead of seeing it already exists, it creates its own. Any usage of it goes through "native" handles and crashes when it accesses code that isn't available to /clr:netcore (example: Microsoft.Data.SqlClient).

What can be done to stop this behavior, or is this new and intended as of /clr:netcore?

**Comment by AaronRobinsonMSFT** [comment]
@fiercekittenz This is known issue with C++/CLI and how it works in .NET Core 3.1/.NET 5+. WPF is particularly sensitive to this issue and is described at https://github.com/dotnet/wpf/issues/1700.

@vitek-karas and @elinor-fung This seems like another manifestation of the single ALC issue we've been tracking. Is there a specific issue we are using in the runtime?

**Comment by AaronRobinsonMSFT** [comment]
I believe the following issue, https://github.com/dotnet/runtime/issues/61105, is tracking this general problem.

**Comment by elinor-fung** [comment]
Also related: https://github.com/dotnet/runtime/issues/62754

**Comment by elinor-fung** [comment]
Closing based on https://github.com/dotnet/runtime/pull/66486 - C++/CLI DLLs targeting .NET 7 will be loaded into the default `AssemblyLoadContext`.

Documentation was added in https://github.com/dotnet/docs/pull/28850
