### ISSUE TITLE
range_r work item: fail: Non-success instrumentation exit code: 101, expected: 0

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#64920]
This test is failing in rolling builds (runtime-extra-platforms) on Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open. `range_d Work Item` and `range_r Work Item` are both failing similarly. The helix logs aren't too helpful:
```
[10:41:16] info: Running instrumentation class net.dot.MonoRunner took 2.423214 seconds
[10:41:16] dbug: Exit code: 0
                 Standard Output:
                 INSTRUMENTATION_RESULT: return-code=101
                 INSTRUMENTATION_CODE: 101
                 
                 
[10:41:16] info: Instrumentation finished normally with exit code 101
[10:41:19] dbug: Executing command: '/datadisks/disk1/work/A720097B/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22101.2/runtimes/any/native/adb/linux/adb -s emulator-5556 logcat -d '
[10:41:20] info: Wrote current ADB log to /datadisks/disk1/work/A720097B/w/A03B08E0/uploads/adb-logcat-net.dot.range_r-net.dot.MonoRunner.log
[10:41:20] fail: Non-success instrumentation exit code: 101, expected: 0
[10:41:20] info: Attempting to remove apk 'net.dot.range_r': 
[10:41:20] dbug: Executing command: '/datadisks/disk1/work/A720097B/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22101.2/runtimes/any/native/adb/linux/adb -s emulator-5556 uninstall net.dot.range_r'
[10:41:20] info: Successfully uninstalled net.dot.range_r.
[10:41:20] dbug: Saving diagnostics data to '/datadisks/disk1/work/A720097B/w/A03B08E0/e/diagnostics.json'
XHarness exit code: 1 (TESTS_FAILED)
```

Do we need to look at the adb logs (does anyone know how to access them)? @radical who would be the best person to look into this?

Runfo Tracking Issue: [range_r work item](https://runfo.azurewebsites.net/tracking/issue/269)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1597265](https://dev.azure.com/dnceng/public/_build/results?buildId=1597265)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 60879](https://github.com/dotnet/runtime/pull/60879)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-ed8baac3e67c47aa95/range_r/1/console.6fbe74f8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T19%25253A43%25253A09Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DnuFGBiAp8q2CxfZQiPFMn2zfyzhDRW%25252Fa8y3oLh2Zfzk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-ed8baac3e67c47aa95/range_r/9d492754-3585-437a-abe5-e8f41cbbc33a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T19%25253A43%25253A09Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DnuFGBiAp8q2CxfZQiPFMn2zfyzhDRW%25252Fa8y3oLh2Zfzk%25253D)|
|[1597254](https://dev.azure.com/dnceng/public/_build/results?buildId=1597254)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 64806](https://github.com/dotnet/runtime/pull/64806)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64806-merge-7d8139143c514addb8/range_r/1/console.69223c67.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T19%25253A34%25253A00Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJT%25252F%25252BDkrypPh1tVdwI5BAT2dY6nO3Q%25252Bm16FJ3Jkf4Nqo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64806-merge-7d8139143c514addb8/range_r/ac673ffc-cb35-4cdf-aed8-04e7f52101e6.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T19%25253A34%25253A00Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJT%25252F%25252BDkrypPh1tVdwI5BAT2dY6nO3Q%25252Bm16FJ3Jkf4Nqo%25253D)|
|[1596968](https://dev.azure.com/dnceng/public/_build/results?buildId=1596968)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 64330](https://github.com/dotnet/runtime/pull/64330)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64330-merge-8da646f994e7443ab4/range_r/1/console.e93e3e4a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T17%25253A05%25253A22Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLiaa1VLR9vruLew91S4eYhoeJ3e%25252BU%25252F6kbCah3sBuAtw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64330-merge-8da646f994e7443ab4/range_r/96482be5-e653-4701-8347-06abe5c188e5.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T17%25253A05%25253A22Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLiaa1VLR9vruLew91S4eYhoeJ3e%25252BU%25252F6kbCah3sBuAtw%25253D)|
|[1596825](https://dev.azure.com/dnceng/public/_build/results?buildId=1596825)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 64567](https://github.com/dotnet/runtime/pull/64567)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64567-merge-7cc59f4f0c9a4eb1a0/range_r/1/console.c60c1c0d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T15%25253A38%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DdU8ozWAdkDXLknzhBZkqft6pj9z6eA6CaH6Tj%25252BX7G0g%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64567-merge-7cc59f4f0c9a4eb1a0/range_r/2aa2383b-c454-452e-b7eb-ada91cf3f8ff.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T15%25253A38%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DdU8ozWAdkDXLknzhBZkqft6pj9z6eA6CaH6Tj%25252BX7G0g%25253D)|
|[1596825](https://dev.azure.com/dnceng/public/_build/results?buildId=1596825)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 64567](https://github.com/dotnet/runtime/pull/64567)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64567-merge-f0a6cdb2c620436793/range_r/1/console.f27bd642.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T22%25253A05%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D89bp4Zz0aBeAeWgbbeF5xGuL9W1ECbrbInvQ3HJrLHk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64567-merge-f0a6cdb2c620436793/range_r/ef0ecfb1-bd28-4157-9b63-b81a3b84404e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-02-27T22%25253A05%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D89bp4Zz0aBeAeWgbbeF5xGuL9W1ECbrbInvQ3HJrLHk%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|4|4|4|

**Comment by radical** [comment]
cc @fanyang-mono @steveisok

**Comment by steveisok** [comment]
@fanyang-mono This is a runtime test failure, right?

**Comment by elinor-fung** [comment]
Recent adb log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-a460fb376262457b8d/range_d/1/adb-logcat-net.dot.range_d-net.dot.MonoRunner.log?sv=2019-07-07&se=2022-02-27T10%3A24%3A36Z&sr=c&sp=rl&sig=N3g9E4zzBWoG%2BpO%2FLhYuhC%2FCJqxy3B%2FM79XNNx8wKLw%3D

```
02-07 10:41:16.954  9249  9268 I DOTNET  : System.ArgumentException: DOCSDIR should not be empty
02-07 10:41:16.954  9249  9268 I DOTNET  :    at XHarnessRunnerLibrary.RunnerEntryPoint.AndroidEntryPoint.get_TestsResultsFinalPath() in /__w/1/s/src/tests/Common/XHarnessRunnerLibrary/RunnerEntryPoint.cs:line 103
02-07 10:41:16.954  9249  9268 I DOTNET  :    at Microsoft.DotNet.XHarness.TestRunners.Common.AndroidApplicationEntryPointBase.RunAsync()
02-07 10:41:16.954  9249  9268 I DOTNET  :    at XHarnessRunnerLibrary.RunnerEntryPoint.RunTests(Func`2 runTestsCallback, String assemblyName, String filter) in /__w/1/s/src/tests/Common/XHarnessRunnerLibrary/RunnerEntryPoint.cs:line 33
02-07 10:41:16.954  9249  9268 I DOTNET  :    at Program.<Main>$(String[] args) in /__w/1/s/src/tests/JIT/Methodical/Arrays/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/XHarnessRunner.g.cs:line 3
02-07 10:41:16.955  9249  9268 D DOTNET  : Exit code: 101.
02-07 10:41:16.956  9249  9268 I DOTNET  : MonoRunner finished, return-code=101
```

It seems like https://github.com/dotnet/runtime/pull/64744 updated the runner for libraries tests (`src/libraries/Common/tests/AndroidTestRunner/AndroidTestRunner.cs`) to stop using `DOCSDIR`. Do we need the equivalent change for runtime tests? cc @akoeplinger

**Comment by akoeplinger** [comment]
Interesting, I wasn't aware that the runtime tests are not using the shared runner code. Sent a fix: https://github.com/dotnet/runtime/pull/64950
