### ISSUE TITLE
Add MacOS M1 (ARM64) to  runtime-extra-platforms leg

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#64929]
@safern mentioned we should add this to the `runtime-extra-platforms` leg.  Opening this issue to track that.

**Comment by safern** [comment]
@MattGal @steveisok do you know if we have capacity to run these on PRs via comment triggers?

**Comment by MattGal** [comment]
`osx.1100.arm64.open` and `osx.1200.arm64.open` both have 57 machines so I expect that's reasonable to do.

**Comment by agocke** [comment]
This is done
