### ISSUE TITLE
GCMemoryInfo.MemoryLoadBytes is not implemented on FreeBSD

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#64935]
related to #14537 
Because of this, `GetGCMemoryInfo` test is failing. It is not clear if this impacts just the `GCMemoryInfo` and test or if that also impacts come other GC operations. 

This seems to come from:
 https://github.com/dotnet/runtime/blob/214a86e193176058b7fd1e4f50a537351764affb/src/coreclr/vm/gcenv.os.cpp#L913
and 
https://github.com/dotnet/runtime/blob/69b9000671f1b73b3fa17810a9f6cb31abb612a2/src/coreclr/gc/unix/gcenv.unix.cpp#L1143

and that eventually boils to 
https://github.com/dotnet/runtime/blob/69b9000671f1b73b3fa17810a9f6cb31abb612a2/src/coreclr/pal/src/misc/sysinfo.cpp#L432-L471

while `host_statistics()` does not seems to be supported on FreeBSD, we may be able to use `sysctlt`. I don't know exactly what and how but there seems to be info about general memory status. 

```
furt@d13:~/github/wfurt-runtime/src/coreclr $ sysctl -a | grep vm.stats.vm
vm.stats.vm.v_pdpages: 52746896
vm.stats.vm.v_tcached: 0
vm.stats.vm.v_cache_count: 0
vm.stats.vm.v_user_wire_count: 0
vm.stats.vm.v_free_severe: 7741
vm.stats.vm.v_interrupt_free_min: 2
vm.stats.vm.v_pageout_free_min: 34
vm.stats.vm.v_laundry_count: 58
vm.stats.vm.v_inactive_count: 231027
vm.stats.vm.v_inactive_target: 64605
vm.stats.vm.v_active_count: 1954
vm.stats.vm.v_wire_count: 959532
vm.stats.vm.v_free_count: 792657
vm.stats.vm.v_free_min: 12788
vm.stats.vm.v_free_target: 43070
vm.stats.vm.v_free_reserved: 2694
vm.stats.vm.v_page_count: 2018855
vm.stats.vm.v_page_size: 4096
vm.stats.vm.v_kthreadpages: 0
vm.stats.vm.v_rforkpages: 112322
vm.stats.vm.v_vforkpages: 608802
vm.stats.vm.v_forkpages: 792309
vm.stats.vm.v_kthreads: 23
vm.stats.vm.v_rforks: 1368
vm.stats.vm.v_vforks: 17614
vm.stats.vm.v_forks: 16655
vm.stats.vm.v_tfree: 79334088
vm.stats.vm.v_pfree: 34539982
vm.stats.vm.v_dfree: 2398725
vm.stats.vm.v_pdshortfalls: 58
vm.stats.vm.v_pdwakeups: 118
vm.stats.vm.v_reactivated: 684144
vm.stats.vm.v_intrans: 91070
vm.stats.vm.v_vnodepgsout: 271080
vm.stats.vm.v_vnodepgsin: 3647381
vm.stats.vm.v_vnodeout: 17159
vm.stats.vm.v_vnodein: 260117
vm.stats.vm.v_swappgsout: 767544
vm.stats.vm.v_swappgsin: 548901
vm.stats.vm.v_swapout: 44036
vm.stats.vm.v_swapin: 50815
vm.stats.vm.v_ozfod: 5063
vm.stats.vm.v_zfod: 63424950
vm.stats.vm.v_cow_optim: 255
vm.stats.vm.v_cow_faults: 6318711
vm.stats.vm.v_io_faults: 309807
vm.stats.vm.v_vm_faults: 72791650
```

Some of the entries _seems_ to match the `host_info_t`.

**Comment by Thefrank** [comment]
`sysctl` might be the quickest (easiest?) way to do this for any BSD-like or Solaris-like system. FreeBSD has vmstat(8) (which basically calls `sysctl` for that information but can be formatted differently)

thoughts @am11 ?

**Comment by am11** [comment]
> while `host_statistics()` does not seems to be supported on FreeBSD

Isn't it so that we are using `#ifndef __APPLE__` on Linux, FreeBSD and SunOS and `#else` (on macOS) we are using `host_statistics()`?

**Comment by emaste** [comment]
What do we mean by "available" memory?

Could probably use one of these:
- `v_free_count` + `v_inactive_count` + `v_laundry_count`
- ullTotalPhys - `v_active_count` - `v_wire_count`

**Comment by emaste** [comment]
Background info on memory in FreeBSD: https://wiki.freebsd.org/Memory

**Comment by wfurt** [comment]
Yes @am11, but `ReadMemAvailable()` only parses `/proc/meminfo`. 
I did not look closely what is actually expected. We may look at docs for `host_statistics`.

**Comment by am11** [comment]
Ah, thanks. will take a look. On SunOS, although the procfs is also available, but the difference is that it contains binary files (rather than text files), so it must be failing there as well (we would need to read the contents via read(struct)).

**Comment by am11** [comment]
@wfurt, something like this might do the trick:

```c++
#if defined(__APPLE__)
// paste existing apple code here

#elif defined(__FreeBSD__)
    size_t inactive_count = 0, cache_count = 0, free_count = 0;
    size_t sz = sizeof(inactive_count);
    sysctlbyname("vm.stats.vm.v_inactive_count", &inactive_count, &sz, NULL, 0); 

    sz = sizeof(cache_count);
    sysctlbyname("vm.stats.vm.v_cache_count", &cache_count, &sz, NULL, 0); 

    sz = sizeof(free_count);
    sysctlbyname("vm.stats.vm.v_free_count", &free_count, &sz, NULL, 0);

    lpBuffer->ullAvailPhys = (inactive_count + cache_count + free_count) * sysconf(_SC_PAGE_SIZE);

    INT64 used_memory = lpBuffer->ullTotalPhys - lpBuffer->ullAvailPhys;
    lpBuffer->dwMemoryLoad = (DWORD)((used_memory * 100) / lpBuffer->ullTotalPhys);

// TODO: #elif __sun (read binary procfs via struct: https://illumos.org/man/4/proc, as we do in other places)

#else // Linux etc.
// paste existing linux code here

#endif
```

**Comment by Thefrank** [comment]
Does this still need to be addressed? If yes, I should have some time this weekend to look over what is missing. If everything is set, can the test be reenabled?

**Comment by am11** [comment]
@Thefrank, go for it. I tested the code in a VM as an isolated app. It will help `System.GC.GetGCMemoryInfo().MemoryLoadBytes` API to report meaningful values and this test: https://github.com/dotnet/runtime/blob/a7d4b4b4761b68c85e27d9c4c8dacb86c285ddc6/src/libraries/System.Runtime/tests/System/GCTests.cs#L824
