### ISSUE TITLE
Combine SCCP and range analysis

### ISSUE THREAD

**Issue by DemiMarie** [dotnet/runtime#6495]
This is a feature request to add SCCP and devirtualization, and to combine both with the existing range analysis.  The combination of these optimizations is stronger than any combination of them individually, in any order, no matter how many times each is applied.

These should start with the optimistic assumption: all code is unreachable, and all values have the bottom type.

category:cq
theme:optimization
skill-level:expert
cost:extra-large

**Comment by BruceForstall** [comment]
We have many optimizations we could do. If you have specific examples or scenarios this would improve, that would help. As is, this is too general and not actionable. Closing.
