### ISSUE TITLE
Update the HWIntrinsics to allow removal where no side-effects exist

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#64962]
For simplicity when the hardware intrinsics were first being brought up we marked all `GT_HWINTRINSIC` as "having side-effects" and therefore not allowing their removal as part of liveness checking: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/liveness.cpp#L2069-L2077

Now that the hardware intrinsics are all implemented and we have a good view of their usage and side-effects, we should revisit this code and update only the few intrinsics that actually need it to be kept.

For the most part this should mostly just be `Prefetch`, `Pause` (`Yield` on Arm64), `Loads` and `Stores` that should be considered as side-effecting. `Loads` and `Stores` should already be partially handled due to being tracked as memory accesses and having other relevant flags set. `Prefetch` and `Pause` are special scenarios where they have no output and so nothing to consume them and need a different mechanism of tracking that they are side-effecting.

It should likely be fairly trivial to handle this by adding a new flag to the relevant intrinsics in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiclistxarch.h and https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiclistarm64.h

category:cq
theme:intrinsics
skill-level:expert
cost:medium
impact:medium

**Comment by tannergooding** [comment]
I expect, in practice, this will only catch scenarios involving CSE. For example (repro courtesy @TIHan):

```csharp
        var asVar = Vector128.Create(0f, 0f, 0f, 0f);
        return AdvSimd.CompareEqual(left, asVar);
```

being turned into roughly:
```csharp
        var asVar = Vector128<float>.Zero;
        return AdvSimd.CompareEqual(left, Vector128<float>.Zero);
```

and then the `asVar` being preserved causing the following codegen:
```
IN0001: 000008                    movi    v16.4s, #0x00
IN0002: 00000C                    fcmeq   v16.4s, v0.4s, #0
IN0003: 000010                    mov     v0.16b, v16.16b
```

where-as properly tracking the side-effects here would allow this to become:
```
IN0001: 000008                    fcmeq   v16.4s, v0.4s, #0
IN0002: 00000C                    mov     v0.16b, v16.16b
```

**Comment by tannergooding** [comment]
I believe this should be a relatively easy thing to pick up and we could basically do:
1. Add a new flag to https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsic.h#L77-L163
2. Add a helper API to read said flag, like: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsic.h#L697-L701
3. Add the flag, as appropriate, to intrinsics in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiclistarm64.h and https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiclistxarch.h
4. Update https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/liveness.cpp#L2069-L2077 to correctly check for this flag when determining if a hwintrinsic node can be kept or removed (examples of removal, including for certain kinds of loads/stores are in the same method for other node kinds)

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.

**Comment by JulieLeeMSFT** [comment]
cc @echesakovMSFT .

**Comment by echesakovMSFT** [comment]
I think we should try to accomplish this in .NET 7.0

**Comment by BruceForstall** [comment]
Pushing this to 8.0.0

**Comment by tannergooding** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/9626
