### ISSUE TITLE
Bitmap constructor with IntPtr wierd behavior on linux

### ISSUE THREAD

**Issue by lihk11** [dotnet/runtime#64978]
### Description

I want to use a memory buffer copied from OpenCV native C++ code to initialize a Bitmap in C#，using the constructor with IntPtr. But i get a wrong result. 
The original image is like the following 
![save](https://user-images.githubusercontent.com/4299373/152972007-36152a36-a2bc-40fe-8d38-15096ea9ec7f.jpg)
But the constructed Bitmap is like this,
![newbitmap2](https://user-images.githubusercontent.com/4299373/152972161-8626b986-42da-4927-89ff-69320af643fa.jpg)
My OS is Ubuntu 20.04，with libgdiplus 6.0.4

### Reproduction Steps

Just use the following code to reproduce the problem,
```C#
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;

namespace opencv_bitmap_test
{
    class Program
    {
        static void Main(string[] args)
        {
            Bitmap orig = new Bitmap(Image.FromFile("/home/lihk11/code/lab/playground/opencv_bitmap_test/opencv_bitmap_test/save.jpg"));
            Bitmap bmp = new Bitmap(orig.Width, orig.Height, PixelFormat.Format24bppRgb); 
            Graphics g = Graphics.FromImage(bmp); 
            g.DrawImageUnscaled(orig, 0, 0); 
            bmp.Save("bmp.png");
            BitmapData bmpData = bmp.LockBits(new Rectangle(0, 0, bmp.Width, bmp.Height),
                ImageLockMode.ReadOnly, bmp.PixelFormat);

            //Create a new bitmap.
            Bitmap newBitmap = new Bitmap(bmp.Width, bmp.Height, bmpData.Stride, bmp.PixelFormat, bmpData.Scan0);
            Console.WriteLine("bmp Width: " + bmp.Width + ", Height: " + bmp.Height);
            Console.WriteLine("bmpData Stride: " + bmpData.Stride);
            Console.WriteLine("bmpPixelFormat: " + bmpData.PixelFormat);
            newBitmap.Save("newbitmap.png");
            bmp.UnlockBits(bmpData);
        }
    }
}

```

### Expected behavior

See the first image post above

### Actual behavior

See the second image post above

### Configuration

dotnet 5.0.404
OS：Ubuntu 20.04，Ubuntu 18.04
architecture: x64, ARM64

**Comment by teo-tsirpanis** [comment]
Hello @lihk11, [`System.Drawing.Common` has stopped being supported on Windows](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). If you want to make your app cross-platform, I suggest you move to one of the alternatives listed in the article.

**Comment by gfoidl** [comment]
@teo-tsirpanis your link description is wrong. In the future it's only supported on Windows, and not supported on non-Windows.
(I'll hide this comment after you update the description.)

**Comment by teo-tsirpanis** [comment]
Oops, my bad, forgot the _non_. 😳

**Comment by JeremyKuhne** [comment]
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.
