### ISSUE TITLE
System.Runtime.InteropServices.Tests causing OSX queue backup from uploading dump

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#65000]
See https://github.com/dotnet/core-eng/issues/15520#issuecomment-1032835597

Going to temporarily disable coredumps for libraries tests on macOS while we investigate more, since this is causing issues for everyone using the queue.

**Comment by agocke** [comment]
Thanks! If this is a reliable repro I could try running it locally.

**Comment by elinor-fung** [comment]
That would be great. My theory is that we have at least one expected dump from `PosixSignalRegistrationTests.SignalCanCancelTermination` for `SIGQUIT` and not cancelling termination: https://github.com/dotnet/runtime/blob/b201a16e1a642f9532c8ea4e42d23af8f4484a36/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/PosixSignalRegistrationTests.Unix.cs#L168-L169

If it is that, it should be consistent.

Many of the dumps I see are coming from passed tests. I know @stephentoub had mentioned/reported needing a way to avoid uploading dumps for expected crashes, but I can't seem to find the issue.
```
WorkItems
| where FriendlyName == "System.Runtime.InteropServices.Tests" and QueueName == "osx.1200.amd64.open" and Queued >= ago(1d)
| join Files on WorkItemId
| where FileName startswith "core"
| project Queued, Status, ExitCode, QueueName, ConsoleUri, SizeBytesLong
```

**Comment by stephentoub** [comment]
> Many of the dumps I see are coming from passed tests. I know @stephentoub had mentioned/reported needing a way to avoid uploading dumps for expected crashes, but I can't seem to find the issue.

https://github.com/dotnet/core-eng/issues/15333

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Was this resolved with https://github.com/dotnet/core-eng/issues/15333?

**Comment by elinor-fung** [comment]
The immediate issues this was tracking have been addressed/mitigated. The long-term fix is tracked by https://github.com/dotnet/runtime/issues/65422.
