### ISSUE TITLE
CoreCLR's dbgshim is moving into dotnet/diagnostics repo

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#65017]
This allows us to shipping dbgshim out of band with new features and reduces the size (slightly) of the .NET runtime installs. 

It will be removed from the runtime repo in the 7.0 Preview 3 time frame.

The new OOB Microsoft.Diagnostics.DbgShim package is available on this feed: 

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

**Comment by jkoritzinsky** [comment]
Does this include both the [CoreCLR](https://github.com/dotnet/runtime/tree/main/src/coreclr/dlls/dbgshim) and [Mono](https://github.com/dotnet/runtime/tree/main/src/mono/dlls/dbgshim) dbgshim implementations, or just the CoreCLR implementation?

**Comment by mikem8361** [comment]
This is currently only coreclr.  We will have to look into mono.

**Comment by tommcdon** [comment]
> This is currently only coreclr. We will have to look into mono.

Adding @thaystg as FYI

**Comment by mikem8361** [comment]
Changing to Preview 3.

**Comment by mikem8361** [comment]
Done.
