### ISSUE TITLE
JIT Optimization: Merge multiple `inc` into one `add`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#65025]
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgZgAIS6BhOgbyrs4fuwDsM6AQQAUfAQEMAlGw5c54gNQKA3LLmdFKtesIB2OuNWU5AX23badMXQBCo/gentj6jXQUBeOsSOvOeg18uM0oTIA

The codegen of B is better (less cpu cycles).

```cs
    public int A(int a) {
        a++; // inc edx
        a++; // inc edx
        return a;
    }
    
    public int B(int a) {
        a += 2; // add edx, 2
        return a;
    }
 ```

## Expected result

```diff
- inc edx
- inc edx
+ add edx, 2
  mov eax, edx
  ret

**Comment by danmoseley** [comment]
This does not seem to be what C++ compilers do: https://godbolt.org/z/r1f7Pxdfa
Curious to know why.

**Comment by omariom** [comment]
@danmoseley 
With optimization flags https://godbolt.org/z/MPcor1xEP

**Comment by danmoseley** [comment]
@omariom thanks, I thought that was default.

**Comment by deeprobin** [comment]
## Same for `dec`
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAQQAUg4dgCUHLjwXY4cANzyF3JavUbiAdgbY11BQF8dO+g0kMAQhKGHZnExs0M4AXgaljb7vqGfjzm1KZAA==

### Expected result
```diff
- dec edx
- dec edx
+ add edx, 0xfffffffe
  mov eax, edx
  ret
```

## And `inc`+`dec` elimination would be nice
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAQQAUg4dgCUHLjwXYA1EoDc8hd2xw466pp7K1GzcQDsDbHoUBfEyfoNJDAEIShl2Z30HLK677mlgHcdtQ2QA=

### Expected result
```diff
- inc edx
- dec edx
  inc edx
  mov eax, edx
  ret
```

**Comment by compilerdeceiver397** [comment]
IMO this should be generalized to all operators.

Interestingly, copying to temporary variables will result in optimal code, so maybe this is related to SSA/constant propagation:

```cs
public int M(int x) {
    x *= 7;
    x *= 7;
    return x;
}
public int M2(int x) {
    int t1 = x * 7;
    int t2 = t1 * 7;
    return t2;
}
```

```asm
C.M(Int32)
    L0000: imul edx, 7
    L0003: imul edx, 7
    L0006: mov eax, edx
    L0008: ret

C.M2(Int32)
    L0000: imul eax, edx, 0x31
    L0003: ret
```

[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunGBLAHYYGAWQAUg4QgCUHLjwUIGAKgC8DAOwBueQu5K1mndT09iGhgmMKAvrt4NJo0hKGXZnE6cduM5BuoGRvYKThikAQx+KsFepuZRpNY8dtSpQA=)

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Note forward sub (#63720) does not handle cases where a local has multiple definitions and uses, even if each definition has just one use. It might not be too hard to extend it to cover these cases.

Eg if we run it again once SSA is built and track the number of uses of each SSA def.
