### ISSUE TITLE
Stream from System.IO.Compression.ZipFileArchive.Open doesn't return more than 8kb or so per Read() call

### ISSUE THREAD

**Issue by reinux** [dotnet/runtime#65037]
### Description

Seemingly as of very recently, `Stream.Read` only reads a little bit of a file at a time, even if you specify for it to read in the whole thing. It's around 8kb, but not exactly 8kb, and not always the same number of bytes.

Although for performance/memory reasons it makes sense to only read a little at a time, this doesn't seem like something that should suddenly be enforced by the runtime, and it has broken past code.

### Reproduction Steps
```
using System.IO.Compression;

var zf = ZipFile.OpenRead(@"file.zip");

var entry = zf.Entries[0]; // Ensure that this file is long-ish -- at least 15kb or so
var stream = entry.Open();

var bytes = new byte[entry.Length];

var nread = stream.Read(bytes, 0, bytes.Length);

Console.WriteLine($"Bytes read: {nread}"); // Will not be the same as bytes.Length if bytes.Length is long
```
### Expected behavior

nread == bytes.Length, and everything is read in all at once

### Actual behavior

Some number of bytes around 8kb is returned at a time

### Regression?

Yes, this was working previously.

### Known Workarounds

Read the whole file in in a loop

### Configuration

- .NET 6.0.1
- Windows 11
- x64
- Not sure if specific to configuration

**Comment by danmoseley** [comment]
Hi @reinux , your code was unfortunately depending on undocumented behavior. This changed in .NET 6 for consistency and performance reasons. The fix should be straightforward -- please see the breaking change documentatin:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by reinux** [comment]
@danmoseley It seems like a bit of a risky change, but I understand. Will just have to be more careful with Read() going forward.

Thanks for the prompt response!

**Comment by GSPP** [comment]
@reinux It was a risky change. I have seen a few issues like yours opened on this issue tracker. I follow this issue tracker, and it is rare to see this amount of repeated reporting of the same breaking change. The team made that choice deliberately and not lightly, though.
