### ISSUE TITLE
.NET Native compiler crashing

### ISSUE THREAD

**Issue by edward-a** [dotnet/runtime#65052]
### Description

.NET Native compiler crashes on a delegate returning reference to a struct:

  public struct TestStruct { }
  public delegate ref TestStruct TestDelegate();

Output:
1>C:\Users\<user>\.nuget\packages\microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Users\<user>\.nuget\packages\runtime.win10-x64.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Projects\NetNativeCrash\obj\x64\Release\ilc\intermediate\MDIL\NetNativeCrash.rsp"' returned exit code 2

### Reproduction Steps

Create a UWP project, add the following two lines:

  public struct TestStruct { }
  public delegate ref TestStruct TestDelegate();

### Expected behavior

.NET Native shouldn't crash when compiling the delegate.

### Actual behavior

.NET Native always crashes when compiling the delegate.

**Comment by edward-a** [comment]
area-NativeAOT-coreclr

**Comment by MichalStrehovsky** [comment]
@tommcdon we track this one internally as [1032841](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032841).

**Comment by edward-a** [comment]
> @tommcdon we track this one internally as [1032841](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032841).

Any ETA on when to expect it to be fixed?

**Comment by tommcdon** [comment]
> Any ETA on when to expect it to be fixed?

Thanks for the bug report.  The issue is on our backlog and will treat this bug report as voting for it.
