### ISSUE TITLE
JIT: Optimize "X ^ 0" to "X"

### ISSUE THREAD

**Issue by SkiFoD** [dotnet/runtime#65071]
Current implementation emits:
```
8B4510               mov      eax, dword ptr [rbp+10H]
83F000               xor      eax, 0
```
I suppose it can be simplified to 
```
8B4510               mov      eax, dword ptr [rbp+10H]
```
https://godbolt.org/z/57fh1v6PK

I made a quick research and folded it in the lowering phase.
The diffs are quite small, but the folding may be useful. 

[before.txt](https://github.com/dotnet/runtime/files/8032633/before.txt)
[after.txt](https://github.com/dotnet/runtime/files/8032631/after.txt)
[diff_summary.6.md](https://github.com/dotnet/runtime/files/8032635/diff_summary.6.md)

@EgorBo, @SingleAccretion I would be happy to know your opinion if it is worth it to implement this optimization.

**Comment by am11** [comment]
> https://godbolt.org/z/57fh1v6PK

nit: here is the updated link with optimization flags: https://godbolt.org/z/rG3cMKr5q

**Comment by EgorBo** [comment]
> @EgorBo, @SingleAccretion I would be happy to know your opinion if it is worth it to implement this optimization.

why not if it produces diffs 🙂 

Have you measured the diffs if it's done in morph instead? I guess it should be a pretty straightforward change in morph.
E.g. I believe we already have `x * 0` there

**Comment by SkiFoD** [comment]
> > @EgorBo, @SingleAccretion I would be

 happy to know your opinion if it is worth it to implement this optimization.
> 
> why not if it produces diffs 🙂
> 
> Have you measured the diffs if it's done in morph instead? I guess it should be a pretty straightforward change in morph. E.g. I believe we already have `x * 0` there

I tried to implement it in morph at first, it produced these regressions ([diff_summary.3.md](https://github.com/dotnet/runtime/files/8032822/diff_summary.3.md))

However, I think it could happen because I missed something.

**Comment by SkiFoD** [comment]
I moved the optimization to morph phase. 
Here are asmdiffs for x64
[diff_summary.10.md](https://github.com/dotnet/runtime/files/8034389/diff_summary.10.md)
I couldn't get rid of the regressions. There are 190 of them, which doesn't feel right to me.

**Comment by JulieLeeMSFT** [comment]
@SkiFoD, the code complete for .NET 7 is July 11th. Do you think you can complete this before that? If not, we can move this to .NET 8.

**Comment by tannergooding** [comment]
> I couldn't get rid of the regressions. There are 190 of them, which doesn't feel right to me

Examples of the regressions would be beneficial. Often times regressions may simply be the JIT being able to kick in additional optimizations once the IR has simplified.

**Comment by SkiFoD** [comment]
@JulieLeeMSFT @tannergooding Hey everyone. The code has been already merged here https://github.com/dotnet/runtime/pull/65072
