### ISSUE TITLE
[API Proposal]: Scale property for the decimal datatype

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#65074]
### Background and motivation

To quickly and easily get the number of decimal places of a decimal. Like [`SqlDecimal`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqldecimal.scale?view=net-6.0#system-data-sqltypes-sqldecimal-scale).

### API Proposal

```diff
namespace System
{
    public struct Decimal // : ...
    {
+        // Gets the number of decimal places.
+        public byte Scale { get; }
    }
}
```

### API Usage

```csharp
decimal foo = 1.234m;
Console.WriteLine(foo.Scale); // 3
```

**Comment by svick** [comment]
1. I think that this version of `FractionalPart` wouldn't be useful, because of leading zeroes: e.g. how would you differentiate between `1.5m` and `1.05m`, since presumably, both would return 5.
2. You can already get the whole number part by casting to `int`. Keep in mind that the range of `decimal` is much larger than that of `int`, so this may throw. And this then also gives you a fairly simple way of getting the fractional part (as `decimal`): `x - (int)x`.
3. Why do you think that getting the lengths of the two parts is something that should be easy? Is there some class of programs where this is a common operation?

**Comment by tannergooding** [comment]
The signature as given wouldn't work/be useful, IMO.

There are cases where breaking it into `(decimal IntegerPart, decimal FractionalPart)` may be useful. This is used internally in the BCL and exposed by other languages as `modf` (or similar, based on the C/C++ name generally).

However, there are also limitations with how `decimal` can be used and what values it can represent and so it may not be as useful as it would be on some `IEEE 754 decimal` like type or the `IEEE 754 binary` types (`float`, `double`, `half`, etc)

**Comment by vanillajonathan** [comment]
@svick
> * I think that this version of `FractionalPart` wouldn't be useful, because of leading zeroes: e.g. how would you differentiate between `1.5m` and `1.05m`, since presumably, both would return 5.
> 
> * You can already get the whole number part by casting to `int`. Keep in mind that the range of `decimal` is much larger than that of `int`, so this may throw. And this then also gives you a fairly simple way of getting the fractional part (as `decimal`): `x - (int)x`.
> 
> * Why do you think that getting the lengths of the two parts is something that should be easy? Is there some class of programs where this is a common operation?

You're right, it wouldn't be useful as an integer as it could not differentiate between `1.5m` and `1.05m`, it would have to be some other kind of data type, maybe a `string`.

Yes, I can get the whole part easily by casting, but the decimal part is trickier. So I thought some properties could come in handy and be easier to use.

We have a web application where the users enter quantity (of invoice articles) and wanted to count the amount of decimals for data validation because a third-party API has a limit of three decimals.

@tannergooding 
> The signature as given wouldn't work/be useful, IMO.
I agree. It would have to be some other data type than `int`.

**Comment by svick** [comment]
> We have a web application where the users enter quantity (of invoice articles) and wanted to count the amount of decimals for data validation because a third-party API has a limit of three decimals.

I think an an efficient and still fairly clear way to do that is `Math.Round(x, 3) == x`. (Though you might also have to take care of trailing zeroes, since those are not considered by the `==` operator.)

**Comment by tannergooding** [comment]
I'd agree with svick here. If all you're wanting to do is validation or ensuring user inputs meet the requirements, then there are much better ways to do that then trying to get the integer and fractional parts.

If you want to get something that's rounded to 3 digits, you have `Math.Round`. You can likewise trivially create your own string that's limited to 3 digits using `ToString()` and a relevant [standard](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings) or [custom](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) numeric format string (`ToString("F3")` will give you exactly 3 fractional digits every time).

Given that this is `decimal`, you could also do something like `Multiply by 1000`, `Truncate`, and `Divide by 1000` or one of many other options to get the right stuff.

If you do want to split into just integer/fractional parts; you can simply:
```csharp
var integerPart = decimal.Truncate(x);
var fractionalPart = x - integerPart;
```

**Comment by vanillajonathan** [comment]
I've rewritten the API proposal to instead provide a `Scale` property like [`SqlDecimal`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqldecimal.scale?view=net-6.0#system-data-sqltypes-sqldecimal-scale).

**Comment by GSPP** [comment]
Related:

- https://github.com/dotnet/runtime/issues/25715

Although this issue was closed, these proposed features still seem like a good idea to me.

**Comment by tannergooding** [comment]
We had explicitly determined `-0.0` was not a concept that should be exposed from `decimal`. It doesn't expose other key concepts like `infinity` or `nan` and so will never support things like transcedentals, etc.

`Decimal` is explicitly a "currency" type (and `Currency` probably would've been a better name, but hindsight is 20/20).

If we want to have concepts like these, then we are likely better off writing up a proposal and implementing the IEEE 754 `decimal32`, `decimal64`, and `decimal128` types. These types are part of an industry standard, support the same concepts and operations as the binary floating-point types, and are generally more efficient to operate on and work with.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System
{
    public partial struct Decimal
    {
        public byte Scale { get; }
    }
}
```

**Comment by danmoseley** [comment]
@vanillajonathan are you interested in offering a PR or should we mark up for grabs?

**Comment by vanillajonathan** [comment]
@danmoseley Mark it as up for grabs.

**Comment by MichalPetryka** [comment]
Could I be assigned to this? I'll do it now.

**Comment by tannergooding** [comment]
Assigned out, thanks @MichalPetryka!

-- Noting we already discussed the needs/implementation here (new API, doc comment, and basic tests) in the C# Community Discord.
