### ISSUE TITLE
Consider changing the nullability for generic MemoryCache.Set methods

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#65107]
The current extension methods look like so:

```C#
public static TItem? Set<TItem>(this IMemoryCache cache, object key, TItem? value);
public static TItem? Set<TItem>(this IMemoryCache cache, object key, TItem? value, MemoryCacheEntryOptions? options);
public static TItem? Set<TItem>(this IMemoryCache cache, object key, TItem? value, IChangeToken expirationToken);
public static TItem? Set<TItem>(this IMemoryCache cache, object key, TItem? value, DateTimeOffset absoluteExpiration);
public static TItem? Set<TItem>(this IMemoryCache cache, object key, TItem? value, TimeSpan absoluteExpirationRelativeToNow);
```

This signature forces the API user to rationalize why a non-nullable value was assigned a null:

```C#
string? cached = memoryCache.Set<string>("some-key", "some-value"); // Why did the memory cache set a null value?
```

If instead the signatures looked like so, we could rely on the compiler to infer the nullability of the type:

```C#
public static TItem Set<TItem>(this IMemoryCache cache, object key, TItem value)
public static TItem Set<TItem>(this IMemoryCache cache, object key, TItem value, MemoryCacheEntryOptions? options)
public static TItem Set<TItem>(this IMemoryCache cache, object key, TItem value, IChangeToken expirationToken)
public static TItem Set<TItem>(this IMemoryCache cache, object key, TItem value, DateTimeOffset absoluteExpiration)
public static TItem Set<TItem>(this IMemoryCache cache, object key, TItem value, TimeSpan absoluteExpirationRelativeToNow)
```

**Comment by stephentoub** [comment]
I don't see why these `TItem`s were made `TItem?`... there doesn't seem to be a reason for it.  If a developer wants to pass null, they can use a nullable TItem, which is how we handle it everywhere else.

@maxkoshevoi, could you comment on why these parameters were made nullable?

**Comment by eerhardt** [comment]
Similarly, we should look into the corresponding `TryGetValue` method to see if there is something that should be annotated differently here:

https://github.com/dotnet/runtime/blob/e21eacb617ed62c83023f7ff81ce24191f993dd1/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/MemoryCacheExtensions.cs#L23-L37

Can we follow the same route and have the developer use a nullable TItem here? The issue is, what happens when `cache.TryGetValue(key, out object? result)` returns true on line 25? What would we return there?

**Comment by maxkoshevoi** [comment]
> @maxkoshevoi, could you comment on why these parameters were made nullable?

Seems like it was a mistake. I still didn't quite get a hang of annotating generics. Created a PR to fix it.
Quickly looking through `ref` for `Caching.Abstractions` I didn't find any other similar issues. 

> The issue is, what happens when `cache.TryGetValue(key, out object? result)` returns true on line 25? What would we set `value` to on line 29?

Yeah, this is what constantly bothering me. What if generic method returns `default(T)`? Does it return `T` or `T?`? It would return `T` if `T` is value type, but there doesn't seem to be a way to indicate that.

**Comment by stephentoub** [comment]
If it's valid for `cache.TryGetValue` to provide a null `result` even when it returns true, then the type needs to be `T?` in the wrapper.  `T` is unconstrained, so if it ends up being a value type, the `?` is a nop.

If `cache.TryGetValue` must always produce a non-null result when it returns true, then the `result` parameter in the interface should be annotated as `[NotNullWhen(true)]`, at which point this wrapper's `out TItem? value` can be changed to `[MaybeNullWhen(false)] out TItem value`.
