### ISSUE TITLE
Code optimization: BitConverter.GetBytes

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#65106]
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/BitConverter.cs#L34-L39

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBJAOwximuwBsA6AJQFdaBLfGFgMIR8AB25N6AZXoA3bmBi4A3AFgAUOuIBmcsQCMSXQCZyA8gG915a7p37DwAJ50A2gF1yAcRgYAQs8UACmAICCZyGWYOGABKKxtLNRtk8idXDyhyAF5yahgAd1SAlz03VSSU6ygXUg8cyKZo8gB+cmCAmL1yEDa02NJyyutiAHZyKEGbAF9461nbXQMi9K8ffzpcADkC4NDwhui4iutEoeWYd3Hs3ILzkrL55Ora64BValxsADN+AEFcAA8ITCaHOAD5ArAvhEorFJpVRuN4eQZmopkA==

## Fix

```diff
 public static byte[] GetBytes(bool value) 
 { 
     byte[] r = new byte[1]; 
-    r[0] = (value ? (byte)1 : (byte)0); 
+    r[0] = Unsafe.As<bool, byte>(ref value);
     return r; 
 } 
```

**Comment by stephentoub** [comment]
That would be a behavioral change.  It's possible a bool could come in from somewhere with a value other than 1, and previously that would have been normalized to 1, but now it wouldn't.
