### ISSUE TITLE
Can not find tag 6.0.2(839cdfb) in main repo?

### ISSUE THREAD

**Issue by nextfool** [dotnet/runtime#65117]
Hi,
Seems the latest release is not included in the main repo here? Is there another repo with the latest code?

**Comment by stephentoub** [comment]
I'm not sure what you're asking about.  You're looking for https://github.com/dotnet/runtime/commits/839cdfb?

**Comment by nextfool** [comment]
@stephentoub  Hi, yes, I mean when I pulled the latest update from the main repo, I can not find the tag 6.0.2 and the revision 839cdfb. Actually you can also tell by clicking the commit link here on github.
![image](https://user-images.githubusercontent.com/2167369/153332216-1730eaf4-97e8-41c4-8198-bbad917e3e60.png)

**Comment by nextfool** [comment]
The tag 6.0.2 is now in the main repo, so I am closing it.
