### ISSUE TITLE
OptimizedInboxTextEncoder's ctor makes it impossible to allow '+' despite UTF-7's removal

### ISSUE THREAD

**Issue by Jehoel** [dotnet/runtime#65130]
### Description

`System.Text.Encodings.Web` prohibits 5 HTML-specific characters from being non-encoded in the 3 encoder subclasses included in the package (`HtmlEncoder`, `JavaScriptEncoder`, and `UrlEncoder`).

https://github.com/dotnet/runtime/blob/d85ec4ee22deaeaabf8389ad492e28be8305f935/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/AllowedBmpCodePointsBitmap.cs#L44-L55

The `'+'` character is included for reasons relating to UTF-7, [but UTF-7 support was dropped by .NET in .NET 5.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/utf-7-code-paths-obsolete), thus rendering the necessity of this escape questionable, imo.

However the actual problem that I'm experiencing is that **it is currently impossible to override this** and re-allow `'+'` when using any of the `System.Text.Encodings.Web.TextEncoder` subclasses; this is because the internal type `OptimizedInboxTextEncoder` always calls `ForbidHtmlCharacters()` _after_ it processes the allow-list from the user-supplied `TextEncoderSettings` object.

This is a problem for me because I need to render HTML without HTML-entitizing any '`+`' characters (in my case, for compatibility with downstream software that expects `+` to be rendered literally, but in principle, I've come to expect _escape-hatches_ in .NET for problems like this).

None of [the documentation for `TextEncoderSettings`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.textencodersettings?view=net-6.0) states that HTML character escapes cannot be overridden. [The `AllowCharacter` method documentation](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodings.web.textencodersettings.allowcharacter) lists no caveats.

I do see the `HtmlEncode_AllRangesAllowed_StillEncodesForbiddenChars_Extended` [test-case](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Encodings.Web/tests/HtmlEncoderTests.cs#L110-L170) _does_ test that `+` is encoded with `HtmlEncoder.Create(UnicodeRanges.All);` but this does not consider explicit calls to `AllowCharacter('+')`.

### Reproduction Steps

This is a test-case I ran in Linqpad 7, targeting .NET 6, including NuGet package `System.Text.Encodings.Web` version `6.0.0` (the latest version as of 2022-02-10).

```
static HtmlEncoder CreateHtmlEncoderThatShouldAllowPlusSign()
{
	TextEncoderSettings settings = new TextEncoderSettings( UnicodeRanges.All );
	settings.AllowCharacter( '+' );
	settings.AllowCodePoints( new Int32[ (Int32)'+' ] ); // Just to make sure...
	
	return HtmlEncoder.Create( settings );
}

HtmlEncoder defaultHtmlEncoder   = HtmlEncoder.Default;
HtmlEncoder allowAllHtmlEncoder  = HtmlEncoder.Create( new TextEncoderSettings( UnicodeRanges.All ) );
HtmlEncoder allowPlusHtmlEncoder = CreateHtmlEncoderThatShouldAllowPlusSign();

defaultHtmlEncoder  .Encode( "< > \" £ $ € +" ).Dump( nameof(defaultHtmlEncoder) );
allowAllHtmlEncoder .Encode( "< > \" £ $ € +" ).Dump( nameof(allowAllHtmlEncoder) );
allowPlusHtmlEncoder.Encode( "< > \" £ $ € +" ).Dump( nameof(allowPlusHtmlEncoder) );
```

I get this output:

```
defaultHtmlEncoder:
    "&lt; &gt; &quot; &#xA3; $ &#x20AC; &#x2B;"

allowAllHtmlEncoder:
    "&lt; &gt; &quot; £ $ € &#x2B;"

allowPlusHtmlEncoder:
    "&lt; &gt; &quot; £ $ € &#x2B;"
```

![image](https://user-images.githubusercontent.com/1693078/153385673-55448c9e-2c4c-4bf1-8186-9d52e3e98f88.png)

### Expected behavior

I expect `TextEncoder.Create` to respect `TextEncoderSettings.AllowCharacters` over its internal defaults.

### Actual behavior

`'+'` characters are always escaped and this cannot be overridden by consumers.

### Configuration

* .NET 6, .NET 5, .NET Core 3.1, .NET Framework 4.8
* Windows 10 20H2
* x64
* Issue is not specific to configuration.

**Comment by GrabYourPitchforks** [comment]
> The '+' character is included for reasons relating to UTF-7, [but UTF-7 support was dropped by .NET in .NET 5.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/utf-7-code-paths-obsolete), thus rendering the necessity of this escape questionable, imo.

The expected behavior is intentional. Certain characters, including `'+'`, are always escaped with no ability to suppress this behavior. To your point about the UTF-7 support being obsoleted: the concern is not about the server. It's about clients which attempt to detect character encoding based on the response payload. Even in 2022 we still see some clients do this, which is maddening. :( So for now we're opting to do the safe thing since it has near-universal compatibility.

There are separate issues tracking the ability for an application to take complete control over which characters are encoded and how they are encoded. https://github.com/dotnet/runtime/issues/54193 provides sample code showing how to do this. You could use that sample code to implement your own filter. That issue also suggests what it might look like to bring such a type inbox into the SDK.

**Comment by Jehoel** [comment]
> So for now we're opting to do the safe thing since it has near-universal compatibility.

I understand.
