### ISSUE TITLE
WebHeaderCollection.this[string] and WebHeaderCollection.Remove(string) does not use the name of the header when throwing exception for invalid chars

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65136]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WebHeaderCollectionthisstring-and-Web/1573327)._

---
[severity:It bothers me. A fix would be nice]
The following instruction:
>>> WebRequest.Create("https://www.microsoft.com"). Headers["My:Key"] = "Value";
thows 'System.ArgumentException: Specified value has invalid HTTP Header characters. Parameter name: name'
The parameter name is hardcoded, so it always show 'name'. Could you replace the hardcoded 'name' by the real parameter name?

Using reflexion, I found the place of this behavior:
```c#
// WebHeaderCollection
private static string CheckBadHeaderNameChars(string name)
{
	if (HttpValidationHelpers.IsInvalidMethodOrHeaderString(name))
	{
		throw new ArgumentException(System.SR.Format(System.SR.net_WebHeaderInvalidHeaderChars, "name"), "name");
	}
	if (ContainsNonAsciiChars(name))
	{
		throw new ArgumentException(System.SR.Format(System.SR.net_WebHeaderInvalidNonAsciiChars, "name"), "name");
	}
	return name;
}
```

---
#### Feedback Bot on 11/8/2021, 04:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 2/10/2022, 08:27 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by karelz** [comment]
Triage: Should be simple to fix - just use properly `nameof(name)`.
We need to check if it is still problem on .NET Core.

**Comment by rzikm** [comment]
I think what the original author of the issue wants is to see the name of the header in the exception message. replacing `"name"` by `nameof(name)` does not really change the output.

**Comment by MihaZupan** [comment]
We may want to reconsider this as by-design.
We don't include the name in the exception for `SocketsHttpHandler` either if the format of the name is bad.
https://github.com/dotnet/runtime/blob/be78db3a584070cd88ca5660bfc860e0233de5d9/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L1047-L1050
