### ISSUE TITLE
Services resolving incorrectly in Development environment but not Production

### ISSUE THREAD

**Issue by jbogard** [dotnet/runtime#65145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

For an `IEnumerable<>` of services resolved using `GetServices`, we found that the list of services returned is different when using `--environment=Development` versus any other values including blank.

We have two service implementations defined. When in Production, service A and B are in the enumerable. In development, service A is in the list twice, without B.

### Expected Behavior

Should always resolve service A and B regardless of the enviroment.

### Steps To Reproduce

Given types:

```csharp
public interface IMarker { }
public interface IBaseService<T> { }

public class BaseService : IBaseService<A> { }

public class GenericService<T> : IBaseService<T>
    where T : IMarker
{

}

public class A : IMarker { }
```

This test passes (I use Shouldly for assertions, sorry):

```csharp
[Fact]
public void Should_resolve_correctly_directly()
{
    var services = new ServiceCollection();

    services.AddTransient<IBaseService<A>, BaseService>();
    services.AddTransient(typeof(IBaseService<>), typeof(GenericService<>));

    var serviceProvider = services.BuildServiceProvider();
    var handlers = serviceProvider
        .GetServices<IBaseService<A>>()
        .ToList();

    handlers.Count.ShouldBe(2);
    var handlersTypes = handlers
        .Select(h => h.GetType())
        .ToList();
    handlersTypes.ShouldContain(typeof(BaseService));
    handlersTypes.ShouldContain(typeof(GenericService<A>));
}
```

This test passes using the `WebApplication.CreateBuilder` method:

```csharp
[Fact]
public void Should_resolve_correctly_with_no_env_set()
{
    var builder = WebApplication.CreateBuilder();

    builder.Services.AddTransient<IBaseService<A>, BaseService>();
    builder.Services.AddTransient(typeof(IBaseService<>), typeof(GenericService<>));

    var serviceProvider = builder.Services.BuildServiceProvider();
    var handlers = serviceProvider
        .GetServices<IBaseService<A>>()
        .ToList();

    handlers.Count.ShouldBe(2);
    var handlersTypes = handlers
        .Select(h => h.GetType())
        .ToList();
    handlersTypes.ShouldContain(typeof(BaseService));
    handlersTypes.ShouldContain(typeof(GenericService<A>));

    var app = builder.Build();

    var appHandlers = app.Services
        .GetServices<IBaseService<A>>()
        .ToList();

    appHandlers.Count.ShouldBe(2);
    var appHandlersTypes = appHandlers
        .Select(h => h.GetType())
        .ToList();
    appHandlersTypes.ShouldContain(typeof(BaseService));
    appHandlersTypes.ShouldContain(typeof(GenericService<A>));
}
```

This test fails:

```csharp
[Fact]
public void Should_resolve_correctly_in_development()
{
    var builder = WebApplication.CreateBuilder(new WebApplicationOptions
    {
        EnvironmentName = Environments.Development
    });

    builder.Services.AddTransient<IBaseService<A>, BaseService>();
    builder.Services.AddTransient(typeof(IBaseService<>), typeof(GenericService<>));

    var serviceProvider = builder.Services.BuildServiceProvider();
    var handlers = serviceProvider
        .GetServices<IBaseService<A>>()
        .ToList();

    handlers.Count.ShouldBe(2);
    var handlersTypes = handlers
        .Select(h => h.GetType())
        .ToList();
    handlersTypes.ShouldContain(typeof(BaseService));
    handlersTypes.ShouldContain(typeof(GenericService<A>));

    var app = builder.Build();

    var appHandlers = app.Services
        .GetServices<IBaseService<A>>()
        .ToList();

    appHandlers.Count.ShouldBe(2);
    var appHandlersTypes = appHandlers
        .Select(h => h.GetType())
        .ToList();
    appHandlersTypes.ShouldContain(typeof(BaseService));
    appHandlersTypes.ShouldContain(typeof(GenericService<A>));
}
```

The first set of assertions succeeds when I build the service provider directly from `builder.Services`. Once I call `builder.Build` and use the `app.Services` to resolve, it gives me the incorrect set of results. Whether or not I build the service provider does not change the second assertion.

### .NET Version

6.0.101

**Comment by jbogard** [comment]
I can't help but think this is partially my fault from https://github.com/dotnet/runtime/pull/39540

**Comment by davidfowl** [comment]
Likely another caching bug. We had one like this already.

**Comment by maryamariyan** [comment]
The initial fix we attempted in the closed PR #68053 would introduce a breaking change.

The alternative found is to get the callsite in a different way within `ServiceProvider.ValidateService(..)` rather than skipping validation for generic types by making the following change:

```diff
-ServiceCallSite? callSite = CallSiteFactory.GetCallSite(descriptor, new CallSiteChain());
+ServiceCallSite? callSite = CallSiteFactory.GetCallSite(typeof(IEnumerable<>).MakeGenericType(descriptor.ServiceType), new CallSiteChain());

```

That did however introduce 3 failing tests (one in `ClosedServicesPreferredOverOpenGenericServices` test) which is a cause for concern. I think it would be good to look closely at those failing tests to verify we don't have another underlying bug in regards to open generics in DI.

**Comment by timmydo** [comment]
I was just bitten by this... We recently moved from a web host builder to host builder, and the fact that ValidateOnBuild was only set when HostingEnvironment.IsDevelopment() (CreateDefaultServiceProviderOptions) is tricky. In our case, the class had some string types in the ctor but it was never resolved by the DI container at runtime so it didn't matter that it couldn't resolve it. After the migration to the generic host provider, on dev boxes the service stopped starting up. But our CI pipeline/prod don't catch the error. 

I'd prefer if ValidateOnBuild was always on or always off, not depending on the HostingEnvironment.

**Comment by davidfowl** [comment]
Or always on

**Comment by timmydo** [comment]
Always on is fine with me. We're always trying to minimize differences between environments.

**Comment by tarekgh** [comment]
.NET 7.0 is done. This issue is planned for .NET 8.0 now.

**Comment by vchirikov** [comment]
@buyaa-n @tarekgh , the release of .NET 8 is near, will it include the fix for this issue?

**Comment by tarekgh** [comment]
@buyaa-n @steveharter can help advising about it. @vchirikov are you interested to submit a PR for it?

**Comment by davidfowl** [comment]
Pretty sure this is fixed, can someone validate?

**Comment by vchirikov** [comment]
@davidfowl, I've checked preview 4 bug was there, but looks like have been fixed in preview 6 (at least in my repro)

Proof:

![image](https://github.com/dotnet/runtime/assets/40987940/66aa59f7-0a6b-4504-9f73-d31f555f9ed6)

Thanks :)

**Comment by tarekgh** [comment]
Thanks @vchirikov for confirming. Closing the issue per your comment.
