### ISSUE TITLE
[API Proposal]: PemEncoding.WriteString

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#65144]
### Background and motivation

For a reason I no longer recall, `PemEncoding.Write` returns `char[]`. I think nearly all of the time, folks that choose to use the allocating version (as apposed to `TryWrite`) want a string, not a `char[]`. That means

1. You end up wrapping nearly every single `PemEncoding.Write(...)` to be `new string(PemEncoding.Write(...))`.
2. Doing 1 means you pay the allocation twice for the PEM. Once for the char array, and once again for the string.
3. If you _want_ to do it as one allocation and you only have a `ReadOnlySpan<byte>` of data, getting a `ReadOnlySpan<T>` into the callback of `string.Create` currently requires unsafe code, so this starts becoming a little more than trivial. So developers don't have an easy way to do just the allocation once.

When implementing the PEM exports, this pretty much meant every time I would have preferred to use `Write` meant I actually had to use `TryWrite` in combination with `GetEncodedSize` and `string.Create`.

### API Proposal

Since we can't change the return type...

```C#
namespace System.Security.Cryptography {
    public static class PemEncoding {
        public static string WriteString(ReadOnlySpan<char> label, ReadOnlySpan<byte> data);
    }
}
```

### API Usage

Using `ExportCertificatePem` as an example:

https://github.com/dotnet/runtime/blob/cf35d12ae59e4bcb2fd2cb904bcdfae5664618be/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs#L1156-L1168

Would become:

```C#
public string ExportCertificatePem()
{
    return PemEncoding.WriteString(PemLabels.X509Certificate, RawDataMemory.Span);
}
```

**Comment by vcsjones** [comment]
Branch with implementation https://github.com/dotnet/runtime/compare/main...vcsjones:writestring-impl

**Comment by bartonjs** [comment]
Looks good as proposed

```C#
namespace System.Security.Cryptography {
    public static class PemEncoding {
        public static string WriteString(ReadOnlySpan<char> label, ReadOnlySpan<byte> data);
    }
}
```
