### ISSUE TITLE
Proposal: Add Temporary and Sparse and to FileOptions

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#65155]
### Discussed in https://github.com/dotnet/runtime/discussions/65067

<div type='discussions-op-text'>

<sup>Originally posted by **msedi** February  9, 2022</sup>
From the WinAPI (https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea) I can see that there is a `FILE_ATTRIBUTE_TEMPORARY` flag when creating a file which seems to be very useful in my case.

The question in general is, does  `FILE_ATTRIBUTE_TEMPORARY` have an effect? I assume some other flags its only a hint to the file manager. I can also understand that this is not available on other platforms, but if it can be seen as a hint only (windows), it could also be seen as such in other platforms. 

Additionally the sparsity of a file could tremendously help to improve performance for large files. Currently there are two possibilities `SetFileValidData` or `DeviceIoControl` that allow to create sparse files.

Another solution might be 

```cs
try
{                    
  File.SetAttributes(fileName, File.GetAttributes(fileName) | FileAttributes.Temporary);
}
catch
{
}
```

but this looks a bit clumsy.
    </div>

**Comment by adamsitnik** [comment]
@msedi it would be great if you could also provide some more information about why you need these features: example scenario that is impossible to implement as of today and some benchmark numbers for spare files
