### ISSUE TITLE
[mono] Tests failing with error: Invalid IL code in (wrapper native-to-managed) System.Runtime.InteropServices.PosixSignalRegistration:HandlerRoutine (int): IL_0049: ret

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#65177]
Basically all the libraries tests on mono on Windows seem to be failing in recent runtime-extra-platform builds with:
```
error: Invalid IL code in (wrapper native-to-managed) System.Runtime.InteropServices.PosixSignalRegistration:HandlerRoutine (int): IL_0049: ret       
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1605729&view=results
Example log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9842560bc0804bd281/System.Linq.Expressions.Tests/1/console.a86b0b70.log?sv=2019-07-07&se=2022-03-02T21%3A53%3A33Z&sr=c&sp=rl&sig=l0AXWan5SR487aw3xXpV1Px49%2FlM36Kt0lQym%2FPf3uo%3D

|Build|Kind|Start Time|
|---|---|---|
[1605729](https://dev.azure.com/dnceng/public/_build/results?buildId=1605729)|Rolling|2022-10-02|
[1607081](https://dev.azure.com/dnceng/public/_build/results?buildId=1607081)|Rolling|2022-11-02|

**Comment by jkoritzinsky** [comment]
I’ll take a look. Hopefully my new machine can build Mono on Windows without issue.
