### ISSUE TITLE
Bug in System.IO Directory.GetDirectories and Directory.GetFiles methods when used with System.IO.SearchOption.AllDirectories

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65180]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-in-SystemIO-DirectoryGetDirectorie/1660840)._

---
Dear Team,

While working on **C#.NET** platform I found a **bug in System.IO Directory.GetDirectories** method when used with **System.IO.SearchOption.AllDirectories**.

The detailed analysis on bug that found is as follows - 

Observations:

It is observed that the Directory.GetDirectories Method of System.IO does not throw any exception,  
	- when provided a directory path that contains a sub-directory with longer sub-directory paths which exceed the system-defined maximum length.
It provides lesser number of sub-directories list than expected,
	- which **creates a misleading information during programming** and also **possess a serious threat if gone unnoticed for unknown paths** for which the search is made.

**In absence of any exception thrown and valid results return, it becomes difficult to trust that output** i.e. list of sub-directories returned by Directory.GetDirectories is accurate.

**Similar behavior observed when checked with Directory.GetFiles Method as well.**

Experimental Setup :
	Platform : .NET
	Programming Language : C#
	Method : Directory.GetDirectories of System.IO
	Path : Valid path having length less than system-defined maximum length i.e. as per documentation, on Windows-based platforms, paths must be less than 248 characters.
	SearchPattern : "*"
	SearchOption : System.IO.SearchOption.AllDirectories
	Expected Output : System.IO.PathTooLongException
	Actual Output returned by Method : List of sub-directories with less count than that of count which actually exists. 

Please look into this, and let me know if anything.

Thanks and Regards
Chetan Lambole

---
#### Feedback Bot on 2/10/2022, 11:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by adamsitnik** [comment]
@carlossanlop @JeremyKuhne is that by design?

**Comment by JeremyKuhne** [comment]
This needs a concrete repro to be able to follow up on. Which version of .NET is this against? What paths and path syntax is being used? I'm unaware of any issues here in Core.

As to what happens on 4.6.2 when you don't have the proper manifest I'm unsure. Never really looked into what Windows does if implicit long paths aren't enabled when enumerating.
