### ISSUE TITLE
System.Collections.IterateForEach<String>.SortedSet has regressed

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#65190]
Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 net7.0 --filter System.Collections.IterateForEach<String>.SortedSet
```

I can reproduce it locally, but the Reporting System data does not show it: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Collections.IterateForEach(String).SortedSet(Size%3a%20512).html

![image](https://user-images.githubusercontent.com/6011991/153591684-5576a3a8-41cc-4756-9191-464cac99e6b1.png)

It can be caused by one of the SDK vs CoreRun differences like not running the benchmarks with R2R enabled in the lab.

## System.Collections.IterateForEach<String>.SortedSet(Size: 512)

| Result |     Base |     Diff | Ratio | Operating System     | Bit   | Processor Name                                  |
| ------ | --------:| --------:| -----:| -------------------- | ----- | ----------------------------------------------- |
| Slower |  4648.58 |  6668.35 |  0.70 | Windows 11           | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Slower |  4134.51 |  5172.76 |  0.80 | Windows 11           | X64   | AMD Ryzen 9 5900X                               |
| Slower |  6840.94 |  8026.13 |  0.85 | Windows 10           | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower |  9734.63 | 11583.86 |  0.84 | Windows 11           | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       |
| Slower |  5336.16 |  7477.94 |  0.71 | Windows 10           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  5528.20 |  7184.83 |  0.77 | Windows 11           | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower |  5785.86 |  7876.75 |  0.73 | Windows 11           | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Slower |  8969.65 | 11257.21 |  0.80 | Windows 11           | X64   | Unknown processor                               |
| Slower |  8508.72 |  9856.92 |  0.86 | Windows 11           | X64   | Unknown processor                               |
| Slower |  3872.61 |  5347.35 |  0.72 | ubuntu 20.04         | X64   | AMD Ryzen 9 5900X                               |
| Slower |  6056.16 |  8168.87 |  0.74 | ubuntu 18.04         | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   | 14714.27 | 16288.08 |  0.90 | centos 7             | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| Slower |  8780.16 | 11881.65 |  0.74 | ubuntu 18.04         | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Slower |  6742.47 |  8489.69 |  0.79 | alpine 3.13          | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  6960.04 |  8311.79 |  0.84 | ubuntu 18.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  6723.62 |  8498.36 |  0.79 | ubuntu 20.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  6647.57 |  8486.32 |  0.78 | ubuntu 20.04         | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower | 10527.18 | 12157.93 |  0.87 | ubuntu 20.04         | Arm64 | Unknown processor                               |
| Slower |  9518.65 | 11773.84 |  0.81 | Windows 10           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower |  9790.63 | 11750.86 |  0.83 | Windows 11           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower |  7687.72 |  8774.63 |  0.88 | Windows 10           | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower | 11272.64 | 12573.94 |  0.90 | Windows 10           | Arm   | Microsoft SQ1 3.0 GHz                           |
| Slower |  8312.06 | 10257.13 |  0.81 | macOS Big Sur 11.6.3 | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |
| Slower |  6873.40 |  9283.62 |  0.74 | macOS Big Sur 11.4   | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |

**Comment by danmoseley** [comment]
> I can reproduce it locally, but the Reporting System data does not show it:

The reporting system does seem to jump about ~5% .. but you're pointing out we're seeing locally 15-25% or so across all OS and arch.. intriguing!

![image](https://user-images.githubusercontent.com/6385855/153653711-3484e34c-00d7-4a25-af15-c2964bfef333.png)

**Comment by eiriktsarpalis** [comment]
According to the reporting data, regression appears to have been fixed now.

**Comment by adamsitnik** [comment]
I confirm, I am no longer able to reproduce it with Preview7:

```ini
BenchmarkDotNet=v0.13.1.1828-nightly, OS=Windows 11 (10.0.22000.795/21H2)
AMD Ryzen Threadripper PRO 3945WX 12-Cores, 1 CPU, 24 logical and 12 physical cores
.NET SDK=7.0.100-preview.7.22377.5
  [Host]     : .NET 6.0.7 (6.0.722.32202), X64 RyuJIT AVX2
  Job-QDHQEA : .NET 6.0.7 (6.0.722.32202), X64 RyuJIT AVX2
  Job-UEHILX : .NET 7.0.0 (7.0.22.37506), X64 RyuJIT AVX2
```

|    Method | Toolchain | Size |     Mean | Ratio |
|---------- |---------- |----- |---------:|------:|
| SortedSet |    net6.0 |  512 | 5.020 us |  1.00 |
| SortedSet |    net7.0 |  512 | 4.865 us |  0.97 |
