### ISSUE TITLE
Weird Optimization in for loop!

### ISSUE THREAD

**Issue by faruknane** [dotnet/runtime#65194]
### Description

The code below is for testing purposes. The slow method is slower than the fast method which is pointed out in twitter [badamczewski01's post](https://twitter.com/badamczewski01/status/1491388893799010310). 

```csharp
using System;
using System.Security.Cryptography;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

var summary = BenchmarkRunner.Run<Test>();

public class Test
{
    private const int L = 10000;
    public int[] data;

    public Test()
    {
        data = new int[L];
    }

    [Benchmark]
    [Arguments(10)]
    public void Slow(int m)
    {
        var array = data;
        for (int i = 0; i < array.Length; i++)
        {
            array[i] += i + m;
            array[i] += i + m;
            array[i] += i + m;
            array[i] += i + m;
        }
    }

    [Benchmark]
    [Arguments(10)]
    public void Fast(int m)
    {
        var array = data;
        for (int i = 0; i < array.Length - 1 + 1; i++)
        {
            array[i] += i + m;
            array[i] += i + m;
            array[i] += i + m;
            array[i] += i + m;
        }
    }
}
```

### Configuration

![image](https://user-images.githubusercontent.com/37745467/153597195-5f2d4f8b-c62f-4557-a1ae-b8241dffd2cd.png)

### Data

i7 7700hq:
![image](https://user-images.githubusercontent.com/37745467/153597272-4fa0f573-8fca-4147-9081-09235ba1219a.png)

![image](https://pbs.twimg.com/media/FLJ6LtHWYAQOVaj?format=jpg&name=4096x4096)

### Analysis

Slow method assembly code:
![image](https://user-images.githubusercontent.com/37745467/153599862-6d133e6f-5a80-4757-99bb-05692c2708cd.png)

Fast method assembly code:
![image](https://user-images.githubusercontent.com/37745467/153600051-c864d2b4-445e-428b-8cd3-4c2f94662a7b.png)

Is this something that can be optimized? I believe this is an edge case. However, I'm opening the issue because it might be the case that it was supposed to be optimized by the compiler and is currently not optimized because of a bug. Feel free to close this issue, if this is really not a thing to bother.

**Comment by EgorBo** [comment]
No codegen difference between Slow and Fast in .NET 7.0 so I believe we can close this

**Comment by faruknane** [comment]
Thank you for informing me about this @EgorBo. Glad to hear that it no longer appears in .NET 7.0
