### ISSUE TITLE
Few performance regressions in Reflection APIs

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#65192]
`PerfLabTests.GetMember.GetMethod2` has regressed

![image](https://user-images.githubusercontent.com/6011991/153594999-f4c937f7-026c-45f5-8a00-ad9284ec080a.png)

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 net7.0 --filter PerfLabTests.GetMember.GetMethod2
```

It seems that @performanceautofiler has missed the regression (cc @DrewScoggins ): https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fPerfLabTests.GetMember.GetMethod2.html

## PerfLabTests.GetMember.GetMethod2

| Result |      Base |      Diff | Ratio | Modality | Operating System     | Bit   | Processor Name                                  |
| ------ | ---------:| ---------:| -----:| -------- | -------------------- | ----- | ----------------------------------------------- |
| Slower | 119488.13 | 136594.73 |  0.87 |          | Windows 11           | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Same   |  90441.11 | 100928.61 |  0.90 |          | Windows 11           | X64   | AMD Ryzen 9 5900X                               |
| Slower | 166580.50 | 189463.25 |  0.88 |          | Windows 10           | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Faster | 869388.13 | 261782.02 |  3.32 |          | Windows 11           | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       |
| Slower | 137948.12 | 155135.23 |  0.89 |          | Windows 10           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   | 133620.09 | 146644.40 |  0.91 |          | Windows 11           | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower | 137163.27 | 155914.69 |  0.88 |          | Windows 11           | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Slower | 195260.36 | 221433.42 |  0.88 |          | Windows 11           | X64   | Unknown processor                               |
| Same   | 203900.12 | 223985.71 |  0.91 |          | Windows 11           | X64   | Unknown processor                               |
| Slower |  86168.27 |  99919.69 |  0.86 |          | ubuntu 20.04         | X64   | AMD Ryzen 9 5900X                               |
| Same   | 164698.11 | 182578.17 |  0.90 |          | ubuntu 18.04         | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower | 292295.35 | 339973.18 |  0.86 |          | centos 7             | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| Slower | 221024.60 | 256290.31 |  0.86 |          | ubuntu 18.04         | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Slower | 143181.31 | 168812.97 |  0.85 |          | alpine 3.13          | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   | 144449.61 | 156417.25 |  0.92 | several? | ubuntu 18.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower | 140866.66 | 163692.26 |  0.86 |          | ubuntu 20.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower | 135224.44 | 159141.56 |  0.85 |          | ubuntu 20.04         | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower | 238096.51 | 277244.08 |  0.86 |          | ubuntu 20.04         | Arm64 | Unknown processor                               |
| Slower | 183858.07 | 241871.69 |  0.76 |          | Windows 10           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower | 201641.43 | 243910.32 |  0.83 |          | Windows 11           | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower | 133531.28 | 154029.39 |  0.87 |          | Windows 11           | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Slower | 196800.36 | 221606.92 |  0.89 | several? | Windows 10           | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   | 452580.18 | 471818.56 |  0.96 |          | Windows 10           | Arm   | Microsoft SQ1 3.0 GHz                           |
| Same   | 224995.36 | 235071.24 |  0.96 |          | macOS Big Sur 11.6.3 | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |
| Slower | 188971.69 | 214833.37 |  0.88 |          | macOS Big Sur 11.4   | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |

**Comment by adamsitnik** [comment]
Same goes for other related benchmarks like `PerfLabTests.GetMember.GetMethod1`:

![image](https://user-images.githubusercontent.com/6011991/153595696-1f0d80a2-fb0a-4611-9862-ab0c8bc3b61d.png)



https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.GetMember.GetMethod1.html

<details>

## PerfLabTests.GetMember.GetMethod1

| Result |      Base |      Diff | Ratio | Alloc Delta | Modality | Operating System     | Bit   | Processor Name                                  | Base V        | Diff V     |
| ------ | ---------:| ---------:| -----:| -----------:| -------- | -------------------- | ----- | ----------------------------------------------- | ------------- | ----------- |
| Slower |  59205.00 |  69813.17 |  0.85 |          +0 |          | Windows 11           | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  44010.93 |  49587.62 |  0.89 |          +0 |          | Windows 11           | X64   | AMD Ryzen 9 5900X                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  91069.82 |  94616.64 |  0.96 |          +0 |          | Windows 10           | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Faster | 416108.59 | 132191.38 |  3.15 |          +0 |          | Windows 11           | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       | 6.0.121.56705 | 7.0.22.7608|
| Same   |  68875.69 |  76210.89 |  0.90 |          +0 |          | Windows 10           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Same   |  67806.30 |  72671.80 |  0.93 |          +0 |          | Windows 11           | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 6.0.121.56705 | 7.0.22.7608|
| Slower |  68376.09 |  80977.52 |  0.84 |          +0 |          | Windows 11           | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 6.0.121.56705 | 7.0.22.7608|
| Same   |  98906.64 | 110330.23 |  0.90 |          +0 |          | Windows 11           | X64   | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Same   | 102999.02 | 108554.25 |  0.95 |          +0 |          | Windows 11           | X64   | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  43468.43 |  49334.36 |  0.88 |          +0 | several? | ubuntu 20.04         | X64   | AMD Ryzen 9 5900X                               | 6.0.121.56705 | 7.0.22.7608|
| Slower |  81400.24 |  91204.08 |  0.89 |          +0 |          | ubuntu 18.04         | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Slower | 140009.01 | 167917.33 |  0.83 |          +0 |          | centos 7             | X64   | Intel Xeon CPU E5530 2.40GHz                    | 6.0.121.56705 | 7.0.22.7608|
| Slower | 110471.39 | 127186.07 |  0.87 |          +0 |          | ubuntu 18.04         | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 6.0.121.56705 | 7.0.22.7608|
| Same   |  76310.10 |  79244.09 |  0.96 |          +0 |          | alpine 3.13          | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Same   |  71407.38 |  78223.34 |  0.91 |          +0 |          | ubuntu 18.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Same   |  73211.77 |  78285.34 |  0.94 |          +0 |          | ubuntu 20.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  70462.89 |  79897.63 |  0.88 |          +0 |          | ubuntu 20.04         | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 6.0.121.56705 | 7.0.22.7608|
| Slower | 117287.41 | 138800.99 |  0.85 |          +0 |          | ubuntu 20.04         | Arm64 | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Slower |  91225.91 | 123192.08 |  0.74 |          +0 |          | Windows 10           | Arm64 | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Slower |  91811.55 | 123696.88 |  0.74 |          +0 |          | Windows 11           | Arm64 | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Slower |  66785.98 |  76820.88 |  0.87 |          +0 |          | Windows 11           | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  98908.54 | 111310.65 |  0.89 |          +0 |          | Windows 10           | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Same   | 221333.59 | 235559.19 |  0.94 |          +0 |          | Windows 10           | Arm   | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Same   | 113031.78 | 115791.54 |  0.98 |          +0 |          | macOS Big Sur 11.6.3 | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 6.0.121.56705 | 7.0.22.7608|
| Slower |  94575.85 | 109705.79 |  0.86 |          +0 | bimodal  | macOS Big Sur 11.4   | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 6.0.121.56705 | 7.0.22.7608|

</details>

**Comment by adamsitnik** [comment]
`GetField` seems to also be affected:
![image](https://user-images.githubusercontent.com/6011991/153598868-bf224eb8-a73d-4094-8601-4d84983690fe.png)

<details>

## PerfLabTests.GetMember.GetField

| Result |      Base |      Diff | Ratio | Alloc Delta | Modality | Operating System     | Bit   | Processor Name                                  | Base V        | Diff V     |
| ------ | ---------:| ---------:| -----:| -----------:| -------- | -------------------- | ----- | ----------------------------------------------- | ------------- | ----------- |
| Same   |  31769.86 |  33575.88 |  0.95 |          +0 |          | Windows 11           | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 6.0.121.56705 | 7.0.22.7608|
| Same   |  25992.65 |  27074.04 |  0.96 |          +0 |          | Windows 11           | X64   | AMD Ryzen 9 5900X                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  45115.17 |  47099.83 |  0.96 |          +0 |          | Windows 10           | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Faster | 220588.25 |  67504.89 |  3.27 |          +0 |          | Windows 11           | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       | 6.0.121.56705 | 7.0.22.7608|
| Same   |  35584.30 |  38287.67 |  0.93 |          +0 |          | Windows 10           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  35138.00 |  40859.16 |  0.86 |          +0 |          | Windows 11           | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 6.0.121.56705 | 7.0.22.7608|
| Slower |  37562.71 |  44514.80 |  0.84 |          +0 |          | Windows 11           | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 6.0.121.56705 | 7.0.22.7608|
| Slower |  55583.25 |  62403.26 |  0.89 |          +0 |          | Windows 11           | X64   | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  57555.16 |  62119.12 |  0.93 |          +0 | several? | Windows 11           | X64   | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Slower |  24718.21 |  28160.88 |  0.88 |          +0 |          | ubuntu 20.04         | X64   | AMD Ryzen 9 5900X                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  43145.56 |  47450.18 |  0.91 |          +0 |          | ubuntu 18.04         | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  85396.53 |  93804.40 |  0.91 |          +0 |          | centos 7             | X64   | Intel Xeon CPU E5530 2.40GHz                    | 6.0.121.56705 | 7.0.22.7608|
| Same   |  67887.88 |  71834.08 |  0.95 |          +0 |          | ubuntu 18.04         | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 6.0.121.56705 | 7.0.22.7608|
| Slower |  36369.79 |  42744.12 |  0.85 |          +0 |          | alpine 3.13          | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  35351.07 |  42964.52 |  0.82 |          +0 | bimodal  | ubuntu 18.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  35805.11 |  41008.41 |  0.87 |          +0 |          | ubuntu 20.04         | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  37886.26 |  45400.00 |  0.83 |          +0 |          | ubuntu 20.04         | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 6.0.121.56705 | 7.0.22.7608|
| Same   |  61027.56 |  64919.92 |  0.94 |          +0 |          | ubuntu 20.04         | Arm64 | Unknown processor                               | 6.0.121.56705 | 7.0.22.7608|
| Same   |  56640.95 |  60558.45 |  0.94 |          +0 |          | Windows 10           | Arm64 | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Same   |  57124.95 |  61094.65 |  0.94 |          +0 |          | Windows 11           | Arm64 | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Slower |  33688.59 |  40213.35 |  0.84 |          +0 |          | Windows 11           | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 6.0.121.56705 | 7.0.22.7608|
| Slower |  46571.05 |  56019.86 |  0.83 |          +0 | several? | Windows 10           | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 6.0.121.56705 | 7.0.22.7608|
| Slower | 158219.85 | 177695.72 |  0.89 |          +0 |          | Windows 10           | Arm   | Microsoft SQ1 3.0 GHz                           | 6.0.121.56705 | 7.0.22.7608|
| Same   |  60900.79 |  60052.63 |  1.01 |          +0 |          | macOS Big Sur 11.6.3 | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 6.0.121.56705 | 7.0.22.7608|
| Same   |  50576.05 |  54464.54 |  0.93 |          +0 |          | macOS Big Sur 11.4   | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 6.0.121.56705 | 7.0.22.7608|

</details>

**Comment by EgorBo** [comment]
The only commit that shows up is https://github.com/dotnet/runtime/pull/63129

**Comment by jkotas** [comment]
Looks like a duplicate of #63456

**Comment by adamsitnik** [comment]
> Looks like a duplicate of https://github.com/dotnet/runtime/issues/63456

That is correct. I did not find it as it did not contain "GetMethod2" keyword. Thanks @jkotas !
