### ISSUE TITLE
Building CoreCLR tests fails

### ISSUE THREAD

**Issue by UnityAlex** [dotnet/runtime#65205]
### Description

Was attempting to build the CoreCLR runtime tests to verify that a different issue exists on `main` but I wasn't able to build due to the following error:

```
D:\dotnet\runtime\.dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3030: Could not copy the file "D:\dotnet\runtime\artifacts\tests\coreclr/obj/windows.x64.Release/Managed/Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.dll" because it was not found. [D:\dotnet\runtime\src\tests\Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.ilproj] [D:\dotnet\runtime\src\tests\build.proj]
```

### Reproduction Steps

1. `build.cmd -subset clr+libs -a x64 -c release`
2. `src\tests\build.cmd x64 release`
3. Observe error

### Expected behavior

Build completes successfully

### Actual behavior

```
D:\dotnet\runtime\.dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(4635,5): error MSB3030: Could not copy the file "D:\dotnet\runtime\artifacts\tests\coreclr/obj/windows.x64.Release/Managed/Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.dll" because it was not found. [D:\dotnet\runtime\src\tests\Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.ilproj] [D:\dotnet\runtime\src\tests\build.proj]
D:\dotnet\runtime\src\tests\Common\dir.traversal.targets(25,5): error : (No message specified) [D:\dotnet\runtime\src\tests\build.proj] [D:\dotnet\runtime\src\tests\build.proj]
D:\dotnet\runtime\src\tests\build.proj(493,5): error MSB3073: The command ""D:\dotnet\runtime\\dotnet.cmd" msbuild D:\dotnet\runtime\src\tests\build.proj /t:Build "/p:TargetArchitecture=x64" "/p:Configuration=Release" "/p:LibrariesConfiguration=Release" "/p:TargetOS=windows" "/p:RuntimeOS=" "/p:RuntimeFlavor=coreclr" "/p:RuntimeVariant=" "/p:CLRTestBuildAllTargets=" "/p:__TestGroupToBuild=3" "/p:__SkipRestorePackages=1" /nodeReuse:false /maxcpucount /bl:D:\dotnet\runtime\artifacts\/log/Release/InnerManagedTestBuild.3.binlog" exited with code 1.
```

### Regression?

Yes this used to work until I pulled the latest changes on `main`. I was previously on commit: `f130138b337b57342e94dabf499b818531effed5` 

### Configuration

- Latest `main` branch from today.
- Windows 10 x64

**Comment by joshpeterson** [comment]
@jkotas Do you have any thoughts about what might be the problem? This issue has prevented us from merging changes from the upstream repo into our fork for a few weeks now.

I suspect that these tests are passing on the CI for the dotnet/runtime repo, so I'm surprised they are not passing when we run the same tests on our CI.

**Comment by jkotas** [comment]
> build.cmd -subset clr+libs -a x64 -c release
> src\tests\build.cmd x64 release

I have run this exact commands locally on my machine and it worked fine for me.

> Could not copy the file D:\dotnet\runtime\artifacts\tests\coreclr/obj/windows.x64.Release/Managed/Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.dll" because it was not found.

I think something went wrong before this error that caused the .dll to not be produced. Can you try to go back in the build log to see what it might have been?

**Comment by joshpeterson** [comment]
> Can you try to go back in the build log to see what it might have been?

Earlier in the output, I do see this:

```
C:\UnitySrc\runtime\.dotnet\sdk\6.0.100\Microsoft.Common.CurrentVersion.targets(2304,5): warning MSB3101: Could not write state file "c:\UnitySrc\runtime\artifacts\tests\coreclr/obj/windows.x64.Release/Managed/Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.ilproj.AssemblyReference.cache". The file 'c:\UnitySrc\runtime\artifacts\tests\coreclr\obj\windows.x64.Release\Managed\Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.ilproj.AssemblyReference.cache' already exists. [c:\UnitySrc\runtime\src\tests\Loader\classloader\StaticVirtualMethods\GenericContext\GenericContextTestDefaultImpCallDefaultImp\GenericContextTestDefaultImpCallDefaultImp.ilproj] [c:\UnitySrc\runtime\src\tests\build.proj]
```

At the end of the build though, that `GenericContextTestDefaultImpCallDefaultImp.ilproj.AssemblyReference.cache` files does not exist at the path mentioned. Is there some kind of race condition happening here during the test process?

**Comment by joshpeterson** [comment]
> Do you have https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md#enable-long-paths enabled on the build machine?

No, we did not! Thank you - with this change our build now passes locally for me. We can close this issue.
