### ISSUE TITLE
[mono][workloads] Support building net-6.0 wasm workload apps in a net-7.0 sdk

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#65211]
The workload tooling doesn't currently have a way to package packs produced outside of the current build as part of a workload.  This makes it impossible for a 700 series wasm-tools workload to pull in the right workload packs to build a net-6.0 blowser-wasm app that requires the wasm-tools tooling (wrong cross-compiler and runtime packs).

The same issue will apply to maui workloads once they have an official release.

- [ ] Create net7 workloads following https://github.com/dotnet/sdk/pull/24070
  - [ ] dotnet/emsdk
  - [ ] dotnet/runtime
  - [ ] maui
- [ ] Create net6 workloads
  - [ ] dotnet/emsdk
  - [ ] dotnet/runtime
  - [ ] maui

**Comment by jonathanpeppers** [comment]
It does seems like MAUI might hit an issue here, when MAUI is GA at some point a .NET 7 SDK will want to build a .NET 6 MAUI application?

It seems like the way things are setup right now, you'd get build errors and have to use a `global.json` to point at a .NET 6 version.

**Comment by lewing** [comment]
sdk design is here https://github.com/dotnet/sdk/pull/24070

**Comment by ahmed-salem-me** [comment]
@lewing @radical #69731

**Comment by lewing** [comment]
fixed in rc1
