### ISSUE TITLE
Ad-hoc codesign on macOS

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#65228]
When I work on macOS M1 I quite often hit issues like this during build (incremental):
![image](https://user-images.githubusercontent.com/523221/153682248-fff45f95-e9a1-46e3-bfda-792327ed586f.png)

from my understanding I need to either do ad-hoc codesigning or disable codesign checks in the OS (via booting to safe mode), am I right?
```
codesign -f -s - artifacts/bin/coreclr/OSX.arm64.Checked/crossgen2/*.*
```
fixes the problem (till next incremental rebuild)

**Comment by agocke** [comment]
This should now be happening by default, as the SDK codesigns the apphost by default. Re-open if this is still occurring.
