### ISSUE TITLE
JIT: Support consuming profile guided optimization data for optimization

### ISSUE THREAD

**Issue by redknightlois** [dotnet/runtime#6522]
Currently the native generation is able to use PGO and as stated by @jkotas on https://github.com/dotnet/coreclr/issues/6759#issuecomment-240809700 it is going to be supported at CoreCLR eventually (already supported at the desktop framework). Being able to allow the JIT to consume that information without the need to generate a native executable would allow software developers to pack that data into their executables to get the same benefits in a portable way.

category:cq
theme:profile-feedback
skill-level:expert
cost:extra-large

**Comment by AndyAyersMS** [comment]
We have this ability now.
