### ISSUE TITLE
Remove `ParameterInfo.HasDefaultValue` workaround

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#65233]
Follow-up issue of #18844

---

As described in https://github.com/dotnet/runtime/issues/63902, it would be good to remove comments and workarounds that have already been fixed.

So this workaround could be imo removed:
https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/libraries/Common/src/Extensions/ParameterDefaultValue/ParameterDefaultValue.netstandard.cs#L22-L26

I saw that there was a PR about this some time ago, which was closed due to compatibility issues with .NET 4.8.

Is this still the case?
If not, we could actually reactivate the PR (#42491).
If yes, maybe we should consider if a conditional compilation would make sense and that we only use the workaround under .NET 4.8.

**Comment by eerhardt** [comment]
This code is in the `.netstandard.cs` file. The workaround has been removing on .NET Core, where the bug was fixed. But since we need to support netstandard (i.e. .NET Framework), we need to keep the workaround in place because the underlying issue isn't fixed there.
