### ISSUE TITLE
Remove `% 0` workaround in `Microsoft.VisualBasic.CompilerServices`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#65230]
Follow up issue for https://github.com/dotnet/runtime/issues/7141

---

As described in https://github.com/dotnet/runtime/issues/63902, it would be good to remove comments and workarounds that have already been fixed.

So imo this workaround can be removed:
https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/CompilerServices/Operators.vb#L4592-L4596

**Comment by ehasis** [comment]
Is jut to remove the line with `<MethodImpl(MethodImplOptions.NoInlining)>`? If is, then I have the branch ready for pr.

**Comment by deeprobin** [comment]
That is already perfect. Unfortunately, I do not know to what extent such contributions are accepted (see README of MSFT.VB.Core).

> We are not accepting feature contributions to Microsoft.VisualBasic.Core. The library is effectively archived.
>
> The library and supporting language features are mature and no longer evolving, and the risk of code change likely exceeds the benefit. We will consider changes that address significant bugs or regressions, or changes that are necessary to continue shipping the binaries. Other changes will be rejected.

**Comment by deeprobin** [comment]
@ehasis 
Removing this seems fine. I think you could create that PR.

**Comment by cston** [comment]
Closing as per [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.VisualBasic.Core/README.md).

@deeprobin, @ehasis, I apologize for not closing earlier.
