### ISSUE TITLE
Contention in coreclr.dll!EventPipeBufferManager::AllocateBufferForThread

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#65247]
We got a report from an internal team that enabling EventListener with GC informational events + running a background process increased their GC pauses from ~3ms to ~38ms. The problem appeared to be a combination of:

1) GC threads logging MarkWithType events were creating some load on the buffer manager lock
2) The EventPipeBuffer is being allocated and zeroed inside the lock. This dramatically increases the time the lock needs to be held and appears unnecessary. The trace showed each thread was holding it for ~0.1ms and convoy behavior was occuring.
3) GC threads are CPU affinitized. One of them eventually called SwitchToThread() inside the spinlock backoff logic allowing a background process thread to switch on to its CPU. Once this happened the background process used that CPU core for many ms (>100ms in one example) before ending its own quantum. Thread quantums on server machines can be very long.

**Comment by josalem** [comment]
We can probably move the allocation of the buffer out of the lock:

https://github.com/dotnet/runtime/blob/b248950e52d31e9c05120aa649f082df81023d52/src/native/eventpipe/ep-buffer-manager.c#L501-L543

i.e., take lines 516-519 out of the lock. That ought to help this.
