### ISSUE TITLE
Disabling runtime marshaling broke DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty() 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#65259]
```
     <test name="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty" type="System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests" method="FindAll_NoSuchName_ReturnsEmpty" time="0.0115152" result="Fail">
        <failure exception-type="System.Runtime.InteropServices.MarshalDirectiveException">
          <message><![CDATA[System.Runtime.InteropServices.MarshalDirectiveException : Cannot marshal 'parameter #7': Cannot marshal managed types when the runtime marshalling system is disabled.]]></message>
          <stack-trace><![CDATA[   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t) in C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\InteropServices\Marshal.cs:line 1122
   at System.DirectoryServices.ActiveDirectory.Utils.GetDNFromDnsName(String dnsName) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\Utils.cs:line 204
   at System.DirectoryServices.ActiveDirectory.DomainController.FindAllInternal(DirectoryContext context, String domainName, Boolean isDnsDomainName, String siteName) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 1069
   at System.DirectoryServices.ActiveDirectory.DomainController.FindAll(DirectoryContext context) in C:\git\runtime\src\libraries\System.DirectoryServices\src\System\DirectoryServices\ActiveDirectory\DomainController.cs:line 259
   at System.DirectoryServices.ActiveDirectory.Tests.DomainControllerTests.FindAll_NoSuchName_ReturnsEmpty() in C:\git\runtime\src\libraries\System.DirectoryServices\tests\System\DirectoryServices\ActiveDirectory\DomainControllerTests.cs:line 121]]></stack-trace>
        </failure>
      </test>
```
https://github.com/dotnet/runtime/blob/a1f0147eb6cefaeff012879dbaf637297736ed3f/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/Utils.cs#L204

It seems it cannot marshal this 
https://github.com/dotnet/runtime/blob/a1f0147eb6cefaeff012879dbaf637297736ed3f/src/libraries/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/NativeMethods.cs#L494

This may have been an edit that was missed from #64279 perhaps because the codepath didn't exercise due to different network config. @jkoritzinsky can you advise here? Looking at the other changes you made, I'm unclear what is needed.

as an aside this code change seems like it should be made at the same time
```C#
-                NativeMethods.DsCrackNames dsCrackNames = Marshal.GetDelegateForFunctionPointer(functionPtr, typeof(NativeMethods.DsCrackNames));
+               NativeMethods.DsCrackNames dsCrackNames = Marshal.GetDelegateForFunctionPointer<NativeMethods.DsCrackNames>(functionPtr);
```
this is on CoreCLR `build clr+libs+libs.tests -rc release -lc debug -test`

**Comment by danmoseley** [comment]
Re the aside, we have ~30 uses of `(type)Marshal.GetDelegateForFunctionPointer(ptr, type)` that probably should use the modern version to eliminate dynamic code. Is that a safe search and replace?

**Comment by jkoritzinsky** [comment]
@danmoseley if you change that last parameter to be an `IntPtr*` instead of `out IntPtr` and change the usages, then it will work with runtime marshalling disabled.

Re the aside: yes, those should be changed to use the generic version.

**Comment by danmoseley** [comment]
@jkoritzinsky is there a way to scan, or grep, for other such issues (of the IntPtr* change) so we don't rely only on unit tests? In some libraries like this one, there are plenty of pinvokes, but the code coverage is not great, especially of error paths.

**Comment by jkoritzinsky** [comment]
I have an analyzer that will catch all of these cases at https://github.com/dotnet/roslyn-analyzers/pull/5822. Just waiting on review to get it merged.

**Comment by danmoseley** [comment]
I ended up with this https://github.com/danmoseley/runtime/commit/4990310ebdfcb2078cb83ac7f1b33767282d062c

Is that right? The code looks strictly worse. Is there something I can read to help me understand why this is necessary?

There are ~20 odd pinvokes that have `out Intptr` in this NativeMethods file, do they all need the change? Perhaps you could take care of the various fixes here?

**Comment by danmoseley** [comment]
I guess, you can run your analyzer/fixer locally against this library to test it that way :)

**Comment by jkoritzinsky** [comment]
@danmoseley this issue explains the rationale behind the "disabled runtime marshalling" mode:

https://github.com/dotnet/runtime/issues/60639

The source generator is using this mode to enable it to easily determine which types do not require any marshalling by checking if a type is `unmanaged` instead of building a bespoke system to check and validate if a type is blittable by the traditional blittable rules (all primitives except bool and maybe char).

I can take care of these fixes.

**Comment by jkoritzinsky** [comment]
Delegate-based P/Invokes haven't yet moved a source-generated model, so they don't interact particularly cleanly with the disabled runtime marshalling mode if they use a lot of marshalling.

**Comment by danmoseley** [comment]
Got it - essentially `out IntPtr` requires code generation to add pinning, whereas `IntPtr*` can assume that's taken care of.

Thanks for doing the cleanup @jkoritzinsky
