### ISSUE TITLE
Make yml AzDO tasks more robust by leveraging the new task retry features

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#65258]
The AzDO team just recently rolled out a new feature that allows to retry specific AzDO tasks: https://docs.microsoft.com/en-us/azure/devops/release-notes/2021/pipelines/sprint-195-update#automatic-retries-for-a-task.

Maybe some tasks in this repo and potentially in Arcade as well should specify a retry count?

cc @dotnet/runtime-infrastructure

**Comment by agocke** [comment]
I think we can do this as necessary -- closing until we have a plan.
