### ISSUE TITLE
[API Proposal]: Extension method suggestion

### ISSUE THREAD

**Issue by uurha** [dotnet/runtime#65267]
### Background and motivation

Hi. I would like to propose to implement `this ref` in the extension method not only for structures.

### API Proposal

```C#
public class SomeReference
{
     public void SomeSetMethod(Data data)
     {
      // some code;
     }
}

public static class Extensions
{
     public static void ContructorMethod<T>(this ref T reference, Data data) where T : class
     {
          if(reference != null) return;
          reference = StaticReferenceContructor<T>();
          reference.SomeSetMethod(data);
     }
}
```

### API Usage

```C#
// Fancy the value
private SomeReference someReference;

public void Initialize(Data data)
{
      someReference.ConstructorMethod(data);
}
```

### Alternative Designs

None

**Comment by teo-tsirpanis** [comment]
Hello @uurha, you are proposing a feature to the C# language which should go to [a discussion on `dotnet/csharplang`](https://github.com/dotnet/csharplang/discussions).

**Comment by uurha** [comment]
> Hello @uurha, you are proposing a feature to the C# language which should go to [a discussion on `dotnet/csharplang`](https://github.com/dotnet/csharplang/discussions).

Undestood, thanks. I'll close this issue and move information to discussion.
