### ISSUE TITLE
All TE benchmarks regressed on ARM64

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#65272]
Literally all aspnet/TE benchmarks regressed on ARM64:
![image](https://user-images.githubusercontent.com/523221/153768835-a45815e0-3299-4e13-a132-c79061b876b7.png)

There are at least 3 different data points with regressed value, The regression is either in aspnet https://github.com/dotnet/aspnetcore/compare/38bd273...21c514d or in dotnet/runtime: https://github.com/dotnet/runtime/compare/49fea67...f3b925d

**Comment by EgorBo** [comment]
I like how `dotnet-issue-labeler` immediately blamed `area-CodeGen-croeclr` 😢

**Comment by EgorBo** [comment]
I've sent to crank jit, coreclr, gc and CoreLib from 3 days ago and the RPS is still the same (regressed) so either it's something else or some infra issue cc @sebastienros

**Comment by sebastienros** [comment]
I updated the Linux kernel on all the machines to be identical on Friday morning. Does it add up?

**Comment by sebastienros** [comment]
Also to exclude a regression we just need to run a benchmark with older runtimes and see if there are still slower. Then it's the machine.

**Comment by EgorBo** [comment]
> Also to exclude a regression we just need to run a benchmark with older runtimes and see if there are still slower. Then it's the machine.

Looks like NodeJS also regressed so... machine?

**Comment by EgorBo** [comment]
native traces point to swapper whatever it means:
![image](https://user-images.githubusercontent.com/523221/153769813-0bc975a7-be89-4af6-8fc1-aec0ec7af7db.png)

**Comment by sebastienros** [comment]
Benchmarks on INTEL Linux also regressed, it's not just ARM, so probably a global perf impact of Kernel 5.16.9 (latest stable installed). It contains mitigations for Spectre-like vulnerabilities.

This is fine since we also run baselines continuously, so improvements/regressions version to version are still tracked. Only downside is that any actual regression happening at the same time might be hard to detect from the charts.

**Comment by EgorBo** [comment]
> Benchmarks on INTEL Linux also regressed, it's not just ARM, so probably a global perf impact of Kernel 5.16.9 (latest stable installed). It contains mitigations for Spectre-like vulnerabilities.
> 
> This is fine since we also run baselines continuously, so improvements/regressions version to version are still tracked. Only downside is that any actual regression happening at the same time might be hard to detect from the charts.

@sebastienros Do you remember from which version you updated to 5.16.9?

**Comment by sebastienros** [comment]
4.15.0-70-generic

**Comment by EgorBo** [comment]
Ah makes sense then
![image](https://user-images.githubusercontent.com/523221/153970128-585dca0b-2f0e-441d-bfbb-c24436623c57.png)

from my understanding syscalls are now more expensive?

**Comment by sebastienros** [comment]
We should still confirm by running one of these benchmarks with runtimes versions (aspnet + netcoreapp) surrounding the regression.

**Comment by EgorBo** [comment]
> We should still confirm by running one of these benchmarks with runtimes versions (aspnet + netcoreapp) surrounding the regression.

.NET 6.0 regresses pretty much to the same value e.g. 4.8M RPS for platform-plaintext on arm64.

**Comment by sebastienros** [comment]
@tannergooding suggested to use a kernel version aligned with 20.04 so I re-updated its kernel. Will probably follow up with the other machines.

**Comment by tannergooding** [comment]
More explicitly, I think just updating to 20.04 if we want a new kernel is better.

Updating 18.04 to use a newer kernel than what ships "in box" is a possible scenario, but I expect its also not a common scenario and may give us different numbers compared to what consumers targeting 18.04 will themselves see.

I think, in general, we should directly target what customers will see "out of the box" to get realistic results and ensure that things remain consistent most everywhere.

**Comment by jkotas** [comment]
> Updating 18.04 to use a newer kernel than what ships "in box" is a possible scenario, but I expect its also not a common scenario 

Nit: I believe scenarios like this are very common with containers. The container host is often running different Linux kernel version than the OS running in the container comes with "in box".

**Comment by JulieLeeMSFT** [comment]
@sebastienros, is this issue resolved now? Checking if we can close it.

**Comment by sebastienros** [comment]
Note: TechEmpower will be updating to 22.04 after their next round, and we'll follow.
