### ISSUE TITLE
Unexpected behavior in the Parallel.ForEachAsync method

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#65270]
Currently the [`Parallel.ForEachAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync) method might continue invoking the `MoveNextAsync` method of the `source` sequence's enumerator, even after this method has returned `false`. For example a `source` sequence containing 5 elements might have its enumerator's `MoveNextAsync` method invoked 11 times. Here is a minimal example that demonstrates this behavior:

```C#
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static async Task Main()
    {
        ThreadPool.SetMinThreads(100, 100);
        var options = new ParallelOptions() { MaxDegreeOfParallelism = Int32.MaxValue };
        await Parallel.ForEachAsync(new MyAsyncEnumerable(), options, async (item, ct) =>
        {
            Console.WriteLine($"Processing: {item}");
            await Task.Delay(500);
        });
    }

    class MyAsyncEnumerable : IAsyncEnumerable<int>, IAsyncEnumerator<int>
    {
        private int _current = 0;

        public IAsyncEnumerator<int> GetAsyncEnumerator(
            CancellationToken cancellationToken = default) => this;

        public ValueTask<bool> MoveNextAsync()
        {
            _current++;
            bool moved = _current <= 5;
            Console.WriteLine($"MoveNextAsync, Current: {_current}, Moved: {moved}");
            return new(moved);
        }

        public int Current => _current;

        public ValueTask DisposeAsync() => default;
    }
}
```

Sample output:

```none
MoveNextAsync, Current: 1, Moved: True
MoveNextAsync, Current: 2, Moved: True
Processing: 1
Processing: 2
MoveNextAsync, Current: 3, Moved: True
Processing: 3
MoveNextAsync, Current: 4, Moved: True
Processing: 4
MoveNextAsync, Current: 5, Moved: True
Processing: 5
MoveNextAsync, Current: 6, Moved: False
MoveNextAsync, Current: 7, Moved: False
MoveNextAsync, Current: 8, Moved: False
MoveNextAsync, Current: 9, Moved: False
MoveNextAsync, Current: 10, Moved: False
MoveNextAsync, Current: 11, Moved: False
```

[Try it on Fiddle](https://dotnetfiddle.net/erOIm9).

The probability of this behavior causing problems in practice should be extremely slim. I am reporting it anyway, in case you would like to fix it in the future .NET versions.

**Comment by stephentoub** [comment]
It's by design, using the fact that, just like IEnumerator.MoveNext, IAsyncEnumerator.MoveNextAsync needs to yield false if it's at or passed the end and is allowed to be called any number of times at that point, yielding false every time. We _could_ separately track whether false has ever been seen and avoid calling MoveNextAsync again if it has, but then we'd be tracking that extra state and checking it on every iteration, so it becomes a question of what's more impactful, up to one additional interface dispatch per degree of parallelism, or checking the flag on every iteration. And that depends on the scenario. I opted to keep the code simpler.

**Comment by theodorzoulias** [comment]
@stephentoub as I am reading now, the docs for the [`IAsyncEnumerator<T>.MoveNextAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerator-1.movenextasync) method say:

> A `ValueTask<TResult>` that will complete with a result of `true` if the enumerator was successfully advanced to the next element, or `false` if the enumerator has passed the end of the collection.

...which strongly implies that a well behaving enumerator should continue replying with `false` after it has replied with `false` once. So changing the current behavior of the `Parallel.ForEachAsync` would only help at dealing with non-well-behaved enumerators. Such enumerators are probably extremely rare, if they exist at all. So I am closing this issue. :-)
