### ISSUE TITLE
[MacCatalyst][x64] System.Reflection.Emit.Tests.ILGeneratorEmit4.TestDynamicMethodEmitCalliNonBlittable failed.

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65304]
The following is being hit in https://github.com/dotnet/runtime/pull/64452:

```
<test name="System.Reflection.Emit.Tests.ILGeneratorEmit4.TestDynamicMethodEmitCalliNonBlittable" type="System.Reflection.Emit.Tests.ILGeneratorEmit4" method="TestDynamicMethodEmitCalliNonBlittable" time="0.0017817" result="Fail">
<failure exception-type="System.Runtime.InteropServices.MarshalDirectiveException">
    <message><![CDATA[System.Runtime.InteropServices.MarshalDirectiveException : Error marshalling return value: Cannot marshal managed types when the runtime marshalling system is disabled.]]></message>
    <stack-trace><![CDATA[   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1610861&view=ms.vss-test-web.build-test-results-tab&runId=44871364&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=146626

cc  @steveisok @akoeplinger @lambdageek @jkoritzinsky

**Comment by lambdageek** [comment]
Doesn't repro locally with dotnet/runtime@a2c66883633.

@MaximLipnin how does the CI configuration run the tests? AOT? Trimming?

**Comment by jkoritzinsky** [comment]
I think MacCatalyst runs with AOT, so this issue would be somewhere in the AOT compiler.

**Comment by MaximLipnin** [comment]
@lambdageek Thanks!
