### ISSUE TITLE
Unpin C# compiler version for repo

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#65317]
We're currently manually pinning the C# compiler version:
https://github.com/dotnet/runtime/blob/ce13258b04df862e4a2cd8a36045fa7491414d10/eng/Versions.props#L55-L56
as the version currently specified from dotnet/arcade is too old:
```
4.1.0-2.21609.7 (81831342)
```
We need to ensure the compiler bits are flowing appropriately and unpin.

**Comment by hoyosjs** [comment]
@stephentoub @AaronRobinsonMSFT I see runtime has this pinned at:

https://github.com/dotnet/runtime/blob/85aa0521681592bb0ae4c6c89f7fb97895e2c7fc/eng/Versions.props#L52

While arcade is at `4.3.0-3.22401.3`. My guess is this is not recent enough for all the ref work, file scoped classes, and other goodness the runtime has taken a dependency on? If not, then should this issue be moved to .NET 8, or should we close it and accept that we move faster than arcade with respect to language feature usage so inhouse management is better?

**Comment by jkoritzinsky** [comment]
When we get the P7 SDK (which I'm upgrading Arcade to as we speak), we can unpin the compiler as it has the final version of 4.4.0-1.xxxxx.

**Comment by hoyosjs** [comment]
@jkoritzinsky since you are picking up the SDK upgrade after the arcade update, I'll assign this to you (and I'll link it in the PR).

**Comment by jkoritzinsky** [comment]
Based on https://github.com/dotnet/runtime/pull/72145#issuecomment-1212522713, we won't be able to unpin the C# compiler upgrade just yet. There's a bug in the P7 Roslyn that wasn't fixed until after P7 was built.

**Comment by jkoritzinsky** [comment]
I don't think we'll be able to do this for the GA release. We recently accepted a change to update the Roslyn compiler for some ref-fields-related work (https://github.com/dotnet/runtime/pull/75156) that only exists in the RC2 SDK. As a result, we'd need to either update to a nightly SDK for the release/7.0 branch or wait until after RC2 is finalized (so basically right before GA) to fix this. Additionally, there's another fix incoming from Roslyn that might be inserted into release/7.0, which would make it nearly impossible to fix this before GA without updating to a nightly SDK.

@stephentoub are we okay with fixing this in servicing when we update the release/7.0 branch to build against the released 7.0.100 sdk?

**Comment by stephentoub** [comment]
That's fine from my perspective.  I just want to make sure we get onto the official train in both servicing and main as soon as we can so that we stay up-to-date with fixes/improvements that come into the compiler.

I think we should also consider flowing compiler updates into dotnet/runtime separate from the rest of the SDK.  Updating the compiler once every three months hasn't been a successful strategy.

**Comment by jkoritzinsky** [comment]
I fully agree with moving to flowing compiler updates to dotnet/runtime instead of using the LKG version from the SDK. I think that will provide us with a much better experience and it will keep us up to date. It will also help us avoid some of the source-build issues we’ve had this release.

I’ll mark this as blocking servicing instead of blocking release.

**Comment by stephentoub** [comment]
@jkoritzinsky, this can be closed now, right?

**Comment by jkoritzinsky** [comment]
We still need to fix this in 7.0.x. I'll add that to my to-do list for tomorrow.

**Comment by jkoritzinsky** [comment]
Fixed by #81247
