### ISSUE TITLE
System.Diagnostics.Stopwatch fails to report correct elapsed time

### ISSUE THREAD

**Issue by AlexandreLaborde** [dotnet/runtime#65321]
### Description

I think I stumbled upon a weird bug in the way .NET timers are implemented. My program reads from a `BlockingCollection `that is being populated elsewhere and whenever it dequeues an item (~ 700Hz), it saves the elapsed time since the program started and the current Unix time and does some other stuff.
I was having some issues related to timing of certain events, so I decided to check what was the difference in consecutive measurements. 

This is when I found out that the computer must have had a hiccup and Stopwatch timer does not report the jump in time, but the Unix time does. (See figure).

It’s almost as if the code is going through two different paths to get the value and the Stopwatch one freezes and the time does not elapse, while the Unix one keeps going so it got the correct measurement.

This happens somewhat often because my computer is running close to its limits. The interesting part is that when I try to run multiple instances of this code in parallel, I can see the Unix jumps more or less at the same real-world time in all of the instances but not in any of the Stopwatch measurements.

I feel that I cannot trust the `System.Diagnostics.Stopwatch` anymore and it is such a critical piece of code for my codebase. 
Are there any know details about the implementation of these two methods that I should take into consideration when building my apps? 

### Reproduction Steps

```csharp
Stopwatch sw = new Stopwatch();
BlockingCollection<byte[]> queue = new BlockingCollection<byte[]>();

...

protected override void Run(CancellationToken token)
{
    byte[] temp;

    sw.Restart();

    while (!token.IsCancellationRequested)
    {
        try
        {
            if (queue.TryTake(out temp, 100, token))
            {
                double ellapsedTime = sw.ElapsedTicks * 1000.0d / Stopwatch.Frequency;
                long unixTime = DateTimeOffset.Now.ToUnixTimeMilliseconds();

                ... save variables and do stuff ...  
            }
        }
        catch (Exception e)
        {
            break;
        }
    }
}
```

![diff_abs time](https://user-images.githubusercontent.com/3045079/153921560-5eb2fefb-3d3e-4a0c-a7c0-121df989bfa8.png)
![diff_elapsed time](https://user-images.githubusercontent.com/3045079/153921594-7c704c2e-ae58-4317-8f46-71a6cc90906e.png)

### Expected behavior

Both timers should report similar readings

### Actual behavior

Unix time reports the correct elapsed amount of time but the stopwatch does not.

### Configuration

_Which version of .NET is the code running on?_
**.NET Framework 4.7.2**
_What OS and version, and what distro if applicable?_
**Windows 10 21H1**
_What is the architecture (x64, x86, ARM, ARM64)?_
**x64**
_Do you know whether it is specific to that configuration?_
I don't known

### Other information

I don't know where the solution might be but in fact, the timers are updated using different code paths. The Stopwatch calls directly to the [QueryPerformanceCounter](https://docs.microsoft.com/en-us/windows/win32/api/profileapi/nf-profileapi-queryperformancecounter) function of the kernel whereas the Unix time does some simple math use the `System.DateTime` and `System.DateTimeOffset` classes.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Stopwatch.Windows.cs#L23

https://github.com/dotnet/runtime/blob/3ae87395f638a533f37b8e3385f6d3f199a72f4f/src/libraries/System.Private.CoreLib/src/System/DateTimeOffset.cs#L623

**Comment by tommcdon** [comment]
Hi @AlexandreLaborde!  Thanks for creating this issue.  

Per [DateTime.Now](https://docs.microsoft.com/dotnet/api/system.datetime.now?view=net-6.0) documentation: 

> The [Now](https://docs.microsoft.com/dotnet/api/system.datetime.now?view=net-6.0) property is frequently used to measure performance. However, because of its low resolution, it is not suitable for use as a benchmarking tool. A better alternative is to use the [Stopwatch](https://docs.microsoft.com/dotnet/api/system.diagnostics.stopwatch?view=net-6.0) class.

Although Stopwatch is a high resolution counter, it might be worth checking [Stopwatch.IsHighResolution](https://docs.microsoft.com/dotnet/api/system.diagnostics.stopwatch.ishighresolution?view=net-6.0) to verify you are getting high resolution measurements.  

> The interesting part is that when I try to run multiple instances of this code in parallel, I can see the Unix jumps more or less at the same real-world time in all of the instances but not in any of the Stopwatch measurements.

If the delay is noticeable, I suggest attaching a [profiler](https://docs.microsoft.com/visualstudio/profiling/profiling-feature-tour?view=vs-2022) to the process and collecting a performance trace.  The callstacks attributing to the delays should evident in the trace.

Hope this helps!
