### ISSUE TITLE
TypeSystem: Support Virtual Static Methods, not just abstract static methods

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#65324]
This is a top level issue to track supporting virtual static methods with implementations within interface types.

- [x] Enable Support in CoreCLR for "simple case" (No handling of overrides within interfaces aka default interface methods).
- [x] Enable Mono Support (No handling of overrides within interfaces aka default interface methods)
- [x] Add Test cases and Functional Validation (No handling of overrides within interfaces aka default interface methods)
- [x] R2R Support (No handling of overrides within interfaces aka default interface methods)
- [x] ECMA spec updates for "simple case"
- [x] Enable Support in CoreCLR for "complex case"
- [x] Enable Mono Support for "complex case"
- [x] Add Test cases and Functional Validation for "complex case"
- [x] R2R Support for "complex case"
- [x] ECMA spec updates for "simple case"

**Comment by 0x0737** [comment]
Would like to know, is there any chance to see virtual statics in classes support in .NET 7? I remember something about it in one of the early C# 11 LDM notes, but things may have changed since then

**Comment by mangod9** [comment]
@davidwrighton any work still pending here for 7 or should it be moved to 8?

**Comment by davidwrighton** [comment]
We're done.
