### ISSUE TITLE
On modern runtimes, HttpClient.GetAsync is really slow to localhost, really fast to 127.0.0.1

### ISSUE THREAD

**Issue by fluffynuts** [dotnet/runtime#65375]
I wrote a little program to stress-test my asp.net image resize server and was dismayed to see that individual requests were taking over 2 seconds. Of course, I assumed the problem was somewhere in the image resize service. Profiling didn't show me any thing useful, and `curl`ing against the same url was really fast, so it wasn't the image resizer. 

After much confusion, I stumbled across https://www.reddit.com/r/csharp/comments/gstvz2/httpclientgetasync_causes_super_slow_syn_sent/, so I tried switching the stress-tester's commandline to querying against `http://127.0.0.1:5000` instead of `http://localhost:5000` and whammo! I'm getting responses in 15-20ms

### Configuration
- targets: net6.0
- OS: Windows 11
- Architecture: x64
- Machine specs: i7 8750H (hexacore), 32Gb RAM

### Regression?
I re-targeted the app to net462 and ran with the same cli to get results against `localhost` that were quite similar to using `127.0.0.1`, except the very first call.

### Data

Using the net6.0 target:

running with `localhost` url:
```
complete: 45 (335669 bytes in 2190ms) (0.5 req/s)
complete: 46 (83607 bytes in 2068ms) (0.5 req/s)
```

running with `127.0.0.1` url:
```
complete: 45 (335669 bytes in 128ms) (7.1 req/s)
complete: 46 (83607 bytes in 35ms) (11.3 req/s)
complete: 47 (335669 bytes in 71ms) (12.1 req/s)
```

Using the net462 target:
running with `localhost` url:
```
complete: 45 (335669 bytes in 2152ms) (0.5 req/s)
complete: 46 (83607 bytes in 23ms) (0.9 req/s)
complete: 47 (335669 bytes in 78ms) (1.3 req/s)
```
(there's an initial delay, but it's fast afterwards)

running with `127.0.0.1` url:
```
complete: 45 (335669 bytes in 679ms) (1.4 req/s)
complete: 46 (83607 bytes in 57ms) (2.6 req/s)
complete: 47 (335669 bytes in 179ms) (3.1 req/s)
```

for interest' sake, I retargeted to netcoreapp3.1 and saw similar results for `localhost` calls:
```
complete: 45 (335669 bytes in 2777ms) (0.4 req/s)
complete: 46 (83607 bytes in 2088ms) (0.4 req/s)
complete: 47 (335669 bytes in 2159ms) (0.4 req/s)
```
and similar speed-ups when using `127.0.0.1`:
```
complete: 45 (335669 bytes in 136ms) (6.4 req/s)
complete: 46 (83607 bytes in 26ms) (10.9 req/s)
complete: 47 (335669 bytes in 70ms) (11.9 req/s)
```
### Analysis
I'm not entirely sure where the time is being spent - although it's almost looking a little like a name resolution / caching issue since the first call on net462 also took around 2s to complete (but was fast thereafter). I haven't figured out how to completely disable ipv6 for localhost to test that theory (I can disable for adapters, but `nslookup localhost` still returns `::1` in the address list)

**Comment by kevingosse** [comment]
It usually means that your server is binding the port on ipv4 but not on ipv6. So you need to wait for the connection to `::1` to timeout before it tries `127.0.0.1`. 

I thought this would be fixed by https://github.com/dotnet/runtime/issues/861 but I don't know if it has been implemented yet.

**Comment by wfurt** [comment]
I think that shows that the service does not listen on IPv6. Can you make it so? That would be best fix IMHO instead of fiddling with name resolution.  The difference to `net462` is that recent .NET version prefer IPv6 over IP4. AFAIK curl does not. 

Also if you see the slowness on every request with HttpClient, it suggest that you are not reusing the handler and it's connection pool. 

You should be able to see both with `Wireshark`

**Comment by fluffynuts** [comment]
@wfurt I can't update every service out there to listen on ipv6 - that's unreasonable. So I could fix my own service - but that leaves plenty of perfectly reasonable ipv4 services out there slowed down by a change in behavior with no apparent caching for failures.

As for re-use, I'm using the same instance of HttpClient, with DefaultHeaders.CloseConnection explicitly set to false and proxy disabled, just for good measure - so it's the same handler, same client, same everything.

**Comment by wfurt** [comment]
In that case you should not IMHO assume the "localhost" resolves only to "127.0.0.1". Certainly on Windows there is more to it than just host files - some entries are resolved automatically - like localhost or address for host itself. So this is essentially disconnect between what client targets and what the service offers. 

The reason why you see the delay lives partially in Windows networking stack. HttpClient and Sockets do not treat "localhost" any special and it will try to connect to addresses it resolves to. On Unix you would get ICMP back if the service did not bind to IPv6 (and it fails quickly) but AFAIK you don't on windows. 

As @kevingosse mentioned the "happy-eyballs" e.g. parallel connect would fix this but it has it's own problems. 

You can also force the .NET stack to ignore IPv6 but that is global per process.

**Comment by antonfirsov** [comment]
For async operations, I think it should be possible to workaround this by overriding [`ConnectCallback`](https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#socketshttphandler-extension-points), and creating an IPV4-only socket instead of a DualMode one: `new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)`.

This won't help the synchronous case, because we don't pass `AddressFamily` to `Dns.GetHostAddresses` in our synchronous connect code:
https://github.com/dotnet/runtime/blob/0addc445e961950f426bcb9d6011163c8069a53f/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L883-L886

Something we can improve maybe.

**Comment by fluffynuts** [comment]
> In that case you should not IMHO assume the "localhost" resolves only to "127.0.0.1". Certainly on Windows there is more to it than just host files - some entries are resolved automatically - like localhost or address for host itself. So this is essentially disconnect between what client targets and what the service offers.

this makes DNS pointless - the whole idea of DNS is that consuming applications don't need to know the details of what a host name resolves to ): if an app needs to know that a host name resolves to ipv4 and ipv6 but the service it connects to only listens on one of those, that's making it the consumer's problem - and it's not necessarily obvious. This doesn't just apply to `localhost`, as shown by my `moo.dev.local` testing.

> The reason why you see the delay lives partially in Windows networking stack. HttpClient and Sockets do not treat "localhost" any special and it will try to connect to addresses it resolves to. On Unix you would get ICMP back if the service did not bind to IPv6 (and it fails quickly) but AFAIK you don't on windows.

Then this sounds like a windows-specific regression to have made ipv6 the default and not cache failures, even within the same HttpClient instance.

> As @kevingosse mentioned the "happy-eyballs" e.g. parallel connect would fix this but it has it's own problems.
I'm not 100% convinced it would, unless I'm missing something in the wording there - it claims parallel DNS resolution, not figuring out which of the returned interfaces is actually connectable?

> You can also force the .NET stack to ignore IPv6 but that is global per process.
Again, this is making a networking implementation the problem of an HttpClient consumer. What is interesting is that I don't see this slowdown from the HttpClient running in the first web service in the chain. To clarify:

1. there's a cli dotnet 6.0 app using HttpClient to make a request to web server [A] (http://localhost:5000), where that request includes an `url` parameter, eg http://localhost:5000?url=http%3A%2F%2Flocalhost%3A5001%3Fid%3D45
2. web server [A] then queries the url, handing off to web server [B] (http://localhost:5001) to retrieve an image
3. web server [A] then manipulates the image (resize, crop, change format, whatever)
4. web server [A] returns the image to the cli app.

the HttpClient instance at (1) stalls for 2 seconds querying http://localhost on every request in dotnet 3, 5, 6 (but not net462 - there it's only on the first attempt) unless I specify http://127.0.0.1; however the url parameter I'm passing is still using `localhost` for the domain name and the query from web server [A] to [B] is fast. So there's something different happening in CLI land from what's happening in asp.net land 🤔

**Comment by geoffkizer** [comment]
I'm having trouble understanding what the specific problem here is.

On Windows, by default, "localhost" will resolve to an IPv6 address by default. If that's not what you want, then you should use an explicit IP address instead, i.e. "127.0.0.1" or "[::1]".

This is specific to localhost and doesn't affect any other DNS name resolution.

**Comment by karelz** [comment]
Triage: This comes up once every year. This is basically OS behavior.
There is no easy workaround from our side and it seems to be an overkill to add new API just for this. Also, this type of problem happens mostly in dev environments, not in production. Built-in happy-eyeballs may be best approach (tracked in #26177).
Closing as not actionable -- there are workrounds (though ugly).

**Comment by fluffynuts** [comment]
> I'm having trouble understanding what the specific problem here is.
> 
> On Windows, by default, "localhost" will resolve to an IPv6 address by default. If that's not what you want, then you should use an explicit IP address instead, i.e. "127.0.0.1" or "[::1]".
> 
> This is specific to localhost and doesn't affect any other DNS name resolution.

Incorrect - as demonstrated by my `moo.dev.local` example, if any domain name resolves to ipv6 _and_ ipv4, and the service you're looking for is listening on just one of those, then you pay the penalty every time.

**Comment by geoffkizer** [comment]
> Incorrect - as demonstrated by my moo.dev.local example, if any domain name resolves to ipv6 and ipv4, and the service you're looking for is listening on just one of those, then you pay the penalty every time.

In this case you've misconfigured your DNS. Don't advertise that moo.dev.local is available on a specific IPv6 address if it's not.

**Comment by fluffynuts** [comment]
> > Incorrect - as demonstrated by my moo.dev.local example, if any domain name resolves to ipv6 and ipv4, and the service you're looking for is listening on just one of those, then you pay the penalty every time.
> 
> In this case you've misconfigured your DNS. Don't advertise that moo.dev.local is available on a specific IPv6 address if it's not.

The interface _is_ available. The specific service I'm querying _is not listening on that interface_. This is no more a misconfiguration than any wild DNS resolution containing ipv4 and ipv6 entries pointing at an arbitrary machine listening only on ipv4. The configuration was _forced_ to demonstrate the issue, but it's quite plausible in real life.

**Comment by geoffkizer** [comment]
> The interface _is_ available. The specific service I'm querying _is not listening on that interface_. This is no more a misconfiguration than any wild DNS resolution containing ipv4 and ipv6 entries pointing at an arbitrary machine listening only on ipv4. The configuration was _forced_ to demonstrate the issue, but it's quite plausible in real life.

I don't want to get hung up on terminology here.

From a client point of view, you've asked us to connect to "moo.dev.local". We ask DNS to resolve this, and it gives us addresses X and Y in that order. This means "please try X, and if it doesn't work, then try Y". That's what we do.

If your service is not actually available on X, then the best solution is to either modify the DNS entry for "moo.dev.local" to exclude X, or create a new DNS entry like "myservice.moo.dev.local" that doesn't include X and use it instead.

If you are unable to do this, then things become complicated. One way for you to handle this is to use the ConnectCallback as described above.

> It is actionable though, through a cache held internal to HttpClient, which knows when it failed to connect on the ipv6 address.

We assume that connection failures are transient. For example, a particular server has crashed and is rebooting. We cannot in general simply exclude a particular IP address permanently. If the service is permanently no longer available on a particular address, then we expect DNS to be updated eventually and we will stop trying that address.

**Comment by geoffkizer** [comment]
> That's 100% fair - but if you have found a working connection, it makes sense to stick to it, no?

Meaning, a working IP address?

We don't want to stick to a single IP address because of DNS round robin.

**Comment by fluffynuts** [comment]
> > That's 100% fair - but if you have found a working connection, it makes sense to stick to it, no?
> 
> Meaning, a working IP address?
> 
> We don't want to stick to a single IP address because of DNS round robin.

so every call, there's a new dns lookup? or dns resolutions are cached for a while?

if the former, then ok, you're offloading round-robin to the dns server - which I understand - but that surely comes at a penalty: dns lookups aren't free.

if the latter, then surely you'd want to round-robin yourself?

**Comment by geoffkizer** [comment]
> so every call, there's a new dns lookup? or dns resolutions are cached for a while?

For every new connection, we call into the OS to resolve the hostname. The OS caches DNS entries (as per TTL defined on the entry). We don't do any in-process caching ourselves.
