### ISSUE TITLE
Is there a way to read certificates from .p12 file and use them for an SSL/TLS communication while using SSLStreams?

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/runtime#65402]
Is there a way to read certificates from .p12 file and use them for an SSL/TLS communication while using SSLStreams?Is it mandatory to rely on Windows keystore to have a SSL/TLS connection working on Windows?

```
sslstream.AuthenticateAsClient(SERVERNAME, ReadCertificates(), sslProtocol, sslCertRevocationCheck);

 private X509Certificate2Collection ReadCertificates()
    {
        X509Certificate2Collection collection = null;
        X509Certificate2Collection collection2 = null;
        try
        {
            String certStore1 = "C:\\Temp\\Certs\\Client.p12";
            X509Certificate2 certificate1 = new X509Certificate2(certStore1, "*****");

            //Create a collection and add two of the certificates.
            collection = new X509Certificate2Collection();
            collection.Import(certStore1,"*****",X509KeyStorageFlags.PersistKeySet);
            collection2 = new X509Certificate2Collection();
            foreach(X509Certificate2 cert in collection)
            {
                if(cert.HasPrivateKey)
                    collection2.Add(cert);
            }                
        }
        catch(Exception e)
        {
            Console.WriteLine(e);
        }
        Console.WriteLine("Certificate collection:" + collection.Count);
        return collection2;
    }
```

The above code fails with the following exception

`System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
`
The code works only if the public key of the server is put into the Windows keystore.
Client.p12 contains both the client's private key and the server's public key.

**Comment by ramsubbaraoc** [comment]
@bartonjs Please can also provide your inputs on this

**Comment by wfurt** [comment]
You can use [AuthenticateAsClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclient?view=net-6.0#system-net-security-sslstream-authenticateasclient(system-net-security-sslclientauthenticationoptions)) with [SslClientAuthenticationOptions](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslclientauthenticationoptions?view=net-6.0) and set `RemoteCertificateValidationCallback `

**Comment by ramsubbaraoc** [comment]
@wfurt Thank you. Will try it out and post the result here.

**Comment by ramsubbaraoc** [comment]
@wfurt Thank you. It worked with .NET 6. Is there something similar for .NET Framework as well?

**Comment by wfurt** [comment]
There is constructor that takes the validation callback: https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.-ctor?view=netframework-4.8#system-net-security-sslstream-ctor(system-io-stream-system-boolean-system-net-security-remotecertificatevalidationcallback-system-net-security-localcertificateselectioncallback-system-net-security-encryptionpolicy)


You may be also able to use https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.servercertificatevalidationcallback?view=net-6.0 

Just for aground: it should work without anything if your certificate is signed by known trusted CA and all the intermediate certificates are available. But often this is not the case so the system has no good way how to establish the trust. The callback allows you to include your own CA and use X509Chain with custom roots, do cert pinning or what ever you need to do for validation.
