### ISSUE TITLE
The value returned by AsQueryable().FirstOrDefault is different between Net5.0 and Net6.0  

### ISSUE THREAD

**Issue by angtianqiang** [dotnet/runtime#65419]
### Description

The value returned by AsQueryable().FirstOrDefault is different between Net5.0 and Net6.0  

The first record is always returned in Net6.0

### Reproduction Steps

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
public class prgram
{  static  void Main()
    {
        var Entitys = new ObservableCollection<object>();
        dynamic a = new System.Dynamic.ExpandoObject();

        a.ID = Guid.Parse("dddcf959-04d8-0ad1-de83-3a020e5cd8b1");
        a.Name = "a";
        dynamic b = new System.Dynamic.ExpandoObject();
        b.ID = Guid.Parse("dddcf959-04d8-0ad1-de83-3a020e5cd8b2");
        b.Name = "b";

        Entitys.Add(a);
        Entitys.Add(b);

        //this return is dddcf959-04d8-0ad1-de83-3a020e5cd8b1 ???????
        //If you switch back to NET5.0, the return is  dddcf959-04d8-0ad1-de83-3a020e5cd8b2
        Console.WriteLine(Entitys.AsQueryable().FirstOrDefault(t => (t).GetProperty("ID") == Guid.Parse("dddcf959-04d8-0ad1-de83-3a020e5cd8b2")).GetProperty("ID"));

        //this return is  dddcf959-04d8-0ad1-de83-3a020e5cd8b2    OK
        Console.WriteLine(Entitys.AsEnumerable().FirstOrDefault(t => (t).GetProperty("ID") == Guid.Parse("dddcf959-04d8-0ad1-de83-3a020e5cd8b2")).GetProperty("ID"));
    }
}
public static class ZtxExtension
{
        public static Guid GetProperty(this Object source, string Propert)
    {
        dynamic D = source;
        switch (Propert)
        {
            default:
                return D.ID;
                break;
        }
    }
}
```

### Expected behavior

![image](https://user-images.githubusercontent.com/10491196/154180905-17fe2402-cadf-4630-ba0c-ace88d0ee2a2.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/10491196/154180939-64ae9d7f-2fe8-4e17-90a6-cc9a21055fe3.png)

**Comment by zlatanov** [comment]
I can confirm that there is indeed a problem. Here is a much simpler repo:
```c#
var a = new List<object>();
var b = new List<string>();

a.Add("test");
b.Add("test");

Console.WriteLine("a: " + a.AsQueryable().FirstOrDefault(x => false));
Console.WriteLine("b: " + b.AsQueryable().FirstOrDefault(x => false));
```

In both cases we should have the console print `null`, but instead when we're querying against the `object` list, the first item is returned.

**Comment by eiriktsarpalis** [comment]
I can confirm this is a regression from .NET 5. Root cause is a corner case in [EnumerableRewriter](https://github.com/dotnet/runtime/commit/122c438e0987bf7bfd2a4a02368353d3774ff963) that fails to map back to the correct IEnumerable method overload. The regression was triggered by #48886 which added new overloads for the First/Last/SingleOrDefault methods. We should try to fix this.
