### ISSUE TITLE
No access to public Azure feeds?

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#65430]
I used to browse the CI feeds using Azure web, eg. https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-tools

It doesn't seem to work anymore:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/1764393/154250589-9500953c-8bbe-45ad-9c5f-9fab166445d6.png">

I tried logging in with several of my accounts, including the GitHub one that is part of `dotnet/teams/external-ci-access` group. I can still access CI logs but this part seems to be gone.

Note that the same feeds are actually public and accessible through NuGet. It just happens that few weeks or months ago something changed on them and NuGet Package Explorer is no longer able to list individual package versions (cc @clairernovotny).

cc @terrajobst

**Comment by markwilkie** [comment]
cc/ @mmitche

**Comment by mmitche** [comment]
Okay this is the second report of this one, so for sure something changed. I can confirm that it didn't change build result viewing, which is good news. Let me follow up with someone on the AzDO side and find out what regressed.

**Comment by filipnavara** [comment]
I can access the feed again. Closing, thanks!
