### ISSUE TITLE
A heap has been corrupted using PublishSingleFile

### ISSUE THREAD

**Issue by danipen** [dotnet/runtime#65443]
### Description

Hi guys,

We're publishing our application in production using `PublishSingleFile`. Most of the time the application works perfect, but sometimes the whole app crashes natively with the following exception:

`Unhandled exception at 0x00007FFE1ABCBE99 (ntdll.dll) in winplasticx.exe.31276.dmp: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFE1AC36780).`

This is the mixed stack trace:

```
 	ntdll.dll!RtlReportFatalFailure()
 	ntdll.dll!RtlReportCriticalFailure()
 	ntdll.dll!RtlpHeapHandleError()
 	ntdll.dll!RtlpHpHeapHandleError()
 	ntdll.dll!RtlpLogHeapFailure()
 	ntdll.dll!RtlpFreeHeapInternal()
 	ntdll.dll!RtlFreeHeap()
 	ntdll.dll!RtlpReAllocateHeap()
 	ntdll.dll!RtlpReAllocateHeapInternal()
 	ntdll.dll!RtlReAllocateHeap()
	onigwrap.dll!00007ffde0ebd03f()
 	onigwrap.dll!00007ffde0eadf62()
 	onigwrap.dll!00007ffde0ea4919()
 	onigwrap.dll!00007ffde0eb35d1()
 	onigwrap.dll!00007ffde0e9744c()
 	onigwrap.dll!00007ffde0e971da()
 	onigwrap.dll!00007ffde0e910af()
 	[Managed to Native Transition]	
 	TextMateSharp!TextMateSharp.Internal.Oniguruma.ORegex.ORegex(string pattern, bool ignoreCase, bool multiline)
```

We have a [minidump file](https://drive.google.com/file/d/1MUeWD81E5sluYISoYUL4u3iUb9OpCLAN/view?usp=sharing) for the issue. I'm a little bit lost about how to debug or fix this issue. Any help would be appreciated. Thanks in advance!

### Reproduction Steps

We didn't find a patter to reproduce the issue. It happens sporadically, and only happens when it's published in release with the **PublishSingleFile** option. 

Executing the application in Debug mode **_does not_** reproduce the issue.

### Expected behavior

  The application doesn't crash.

### Actual behavior

The application crashes.

### Configuration

Using .net 6, windows 10, x64

### Other information

[Onigwrap implementation](https://github.com/danipen/TextMateSharp/blob/master/onigwrap/src/onigwrap.c).

**Comment by jkotas** [comment]
Given that the onigwrap library is on the stack, the problem is most likely in that library or in the interop layer used to call this library from .NET.

There are many tutorials and articles for debugging unmanaged heap corruptions. For example, this: https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/pageheap-detect-memory-errors

It is unlikely that the heap corruption is specific to single file. It is fairly common for the crashes caused by heap corruption to come and go away due to completely unrelated changes.

**Comment by danipen** [comment]
The issue finally was in the onigwrap 3rd party lib. Fixed here: https://github.com/danipen/TextMateSharp/pull/13

**Comment by jkotas** [comment]
@danipen Good work tracing it down! Yes, it looks like a race condition on the oniguruma library: https://github.com/kkos/oniguruma/issues/249#issuecomment-1044749333
