### ISSUE TITLE
System.Security.Cryptography.CryptoStream looses content, decrypting an encrypted string is now shorter than the original unencrypted string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65440]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemSecurityCryptographyCryptoStrea/1585710)._

---
Hi,

I am making my first steps in VS2022 / . Net6.

I have been using a specific piece of code perhaps dating back from VS2003 it involves encryption/decyption.

My problem: I encrypt: 0123456789abcdefghijklmnopqrstuvwxyz and than I decrypt that answer.

Using VS2022 and . Net6 I now get back: 0123456789abcdefghijklmnopqrstuv.
xyz are missing!! and the problem lies in System.Security.Cryptography.CryptoStream.

If I create a new . Net4.8 solution in VS2022 than all is well (PS: the DLL containing my code to encrypt decrypt is in .net4.8).

So in my .net6 solution I have a reference to my Utils DLL.
The code in my .net6 solution is:
            string a1 = "0123456789abcdefghijklmnopqrstuvwxyz";
            string a2 = Utils.EncryptStringAES(a1);
            string a3 = Utils.DecryptStringAES(a2);
as mentioned a3 returns: 0123456789abcdefghijklmnopqrstuv

The problem occurs in ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length); in DecryptStringAES (encrypting is no problem. If I copy the encryptes text and decrypt that in the . Net4.8 solution, than I get all characters).

I hope you can help me and solve this.

Kind regards,

Clemens Linders

My utils code:

public static string EncryptStringAES(string PlainText, string Password = "ƒ",
               string Salt = "ƒ", string HashAlgorithm = "ƒ",
               int PasswordIterations = 2, string InitialVector = "ƒ",
               int KeySize = 256)
        {
            if (Password == "ƒ")
            {
                Password = "[Redacted]";
            }
            if (Salt == "ƒ")
            {
                Salt = "Kosher";
            }
            if (HashAlgorithm == "ƒ")
            {
                HashAlgorithm = "SHA1";
            }
            if (InitialVector == "ƒ")
            {
                InitialVector = "OFRna73m*aze01xY";
            }
            if (string. IsNullOrEmpty(PlainText))
                return "";
            byte[] InitialVectorBytes = Encoding.ASCII.GetBytes(InitialVector);
            byte[] SaltValueBytes = Encoding.ASCII.GetBytes(Salt);
            byte[] PlainTextBytes = Encoding.UTF8.GetBytes(PlainText);
            PasswordDeriveBytes DerivedPassword = new PasswordDeriveBytes(Password, SaltValueBytes, HashAlgorithm, PasswordIterations);
            byte[] KeyBytes = DerivedPassword.GetBytes(KeySize / 8);
            RijndaelManaged SymmetricKey = new RijndaelManaged();
            SymmetricKey.Mode = CipherMode.CBC;
            byte[] CipherTextBytes = null;
            using (ICryptoTransform Encryptor = SymmetricKey.CreateEncryptor(KeyBytes, InitialVectorBytes))
            {
                using (MemoryStream MemStream = new MemoryStream())
                {
                    using (CryptoStream CryptoStream = new CryptoStream(MemStream, Encryptor, CryptoStreamMode.Write))
                    {
                        CryptoStream.Write(PlainTextBytes, 0, PlainTextBytes.Length);
                        CryptoStream.FlushFinalBlock();
                        CipherTextBytes = MemStream.ToArray();
                        MemStream.Close();
                        CryptoStream.Close();
                    }
                }
            }
            SymmetricKey.Clear();
            return Convert.ToBase64String(CipherTextBytes);
        }

public static string DecryptStringAES(string CipherText, string Password = "ƒ",
            string Salt = "ƒ", string HashAlgorithm = "ƒ",
            int PasswordIterations = 2, string InitialVector = "ƒ",
            int KeySize = 256)
        {
            if (Password == "ƒ")
            {
                Password = "[Redacted]";
            }
            if (Salt == "ƒ")
            {
                Salt = "Kosher";
            }
            if (HashAlgorithm == "ƒ")
            {
                HashAlgorithm = "SHA1";
            }
            if (InitialVector == "ƒ")
            {
                InitialVector = "OFRna73m*aze01xY";
            }
            if (string. IsNullOrEmpty(CipherText))
                return "";
            try
            {
                byte[] InitialVectorBytes = Encoding.ASCII.GetBytes(InitialVector);
                byte[] SaltValueBytes = Encoding.ASCII.GetBytes(Salt);
                byte[] CipherTextBytes = Convert.FromBase64String(CipherText);
                PasswordDeriveBytes DerivedPassword = new PasswordDeriveBytes(Password, SaltValueBytes, HashAlgorithm, PasswordIterations);
                byte[] KeyBytes = DerivedPassword.GetBytes(KeySize / 8);
                RijndaelManaged SymmetricKey = new RijndaelManaged();
                SymmetricKey.Mode = CipherMode.CBC;
                byte[] PlainTextBytes = new byte[CipherTextBytes.Length];
                int ByteCount = 0;
                using (ICryptoTransform Decryptor = SymmetricKey.CreateDecryptor(KeyBytes, InitialVectorBytes))
                {
                    using (MemoryStream MemStream = new MemoryStream(CipherTextBytes))
                    {
                        using (CryptoStream CryptoStream = new CryptoStream(MemStream, Decryptor, CryptoStreamMode.Read))
                        {

ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length);
                            MemStream.Close();
                            CryptoStream.Close();
                            Array.Resize(ref PlainTextBytes, ByteCount);//Lengte is weer gelijk
                        }
                    }
                }
                SymmetricKey.Clear();
                return Encoding.UTF8.GetString(PlainTextBytes, 0, ByteCount);
            }
            catch
            {
                return "";
            }
        }

I have a lot more code in this Utils class but perhaps the usings are important so I list them here:
using System;
using System.Drawing;
using System.Windows.Forms;
using System.Security.Cryptography;//Voor (echte) random nummers en voor Encrypt/Decrypt
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Soap;
using System.IO;
using System.Linq;
using System.Net;
using System.IO.Compression;
using System.Collections;
using Microsoft.Win32;
using System.Text;
using System.Diagnostics;
using System.Security.AccessControl;
using System.Reflection;
using System.Management;
using System.Runtime.InteropServices;
using System.Drawing.Imaging;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.Data.SqlClient;

---
#### Feedback Bot on 11/16/2021, 10:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vcsjones** [comment]
This is https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams.

> `ByteCount = CryptoStream.Read(PlainTextBytes, 0, PlainTextBytes.Length)`

As documented in the article above, `Read` needs to be called in a loop.

Closing as a duplicate of #55527.
