### ISSUE TITLE
Consider settings startup environment variables in runtimeConfig.json

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#65457]
This request has already been discussed in #63783 and #65007.

**Problem**
I'm struggling with startup hooks and environment variables in `runtimeConfig.json`. Whereas STARTUP_HOOKS can potentially be solved using `module initializers`, `environmentVariables` are something I can only solve by an external *starter batch file* that starts up the application with the necessary environment variables. 

The question is though why not the same behavior is used as in `launchSettings.json`? Here you can simply place an `environentVariables`  which would easily solve the problem.

```
  "environmentVariables": {
        "DOTNET_Thread_UseAllCpuGroups": "true"
      }
```

**Reason**
The original reason I came up with this proposal is similar to #166. I wanted to use the `DOTNET_Thread_UseAllCpuGroups` on startup of my application because this was the only way to enable NUMA core processing. It turned out that it was possible in the .NET Framework but has been discarded in .NET. Creating a start.bat for this sole purpose seems very 80ies to me. 

**Proposal**
1. Add `DOTNET_Thread_UseAllCpuGroups` to the list of switches in runtimeConfig.json. What I have seen from the source-code adding it to the list should not cause too high efforts. Of course I don't know the implications.
2. Add the possiblity to configure environment variables in `runtimeConfig.json` similar to `launchSettings.json`

**Comment by am11** [comment]
The default runtime configuration options are defined by the SDK, which maps to (idiomatic) msbuild properties in consumer code (`<TieredCompilationQuickJit>` in your csproj): https://github.com/dotnet/sdk/blob/22c4860dcb2cf6b123dd641cc4a87a50380759d5/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L377

But we can add additional host configuration options in .csproj (just add the following `<ItemGroup>` in the new-style csproj) or in `Directory.Build.props`. The only caveat is that we need to read it using `AppContext.GetData()` (instead of `Environment.GetEnvrionmentVariables()`) API. e.g.:

```sh
#!/usr/bin/env bash

mkdir foo && cd foo
cat > Directory.Build.props <<EOX
<Project>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Foo" Value="true" />
    <RuntimeHostConfigurationOption Include="Ping" Value="pong" />
  </ItemGroup>
</Project>
EOX

dotnet new console
cat > Program.cs <<EOF
Console.WriteLine("With AppContext.TryGetSwitch/GetData()\n\tFoo: {0}, Ping: {1}",
    AppContext.TryGetSwitch("Foo", out bool foo) ? foo : "<empty>", // optional for bool type, can use GetData()
    AppContext.GetData("Ping"));

Console.WriteLine("With Environment.GetEnvrionmentVariables()\n\tFoo: {0}, Ping: {1}",
    Environment.GetEnvironmentVariable("Foo"),
    Environment.GetEnvironmentVariable("Ping"));
EOF


dotnet publish
bin/Debug/net6.0/publish/foo
```

prints:
```
With AppContext.TryGetSwitch/GetData()
	Foo: True, Ping: pong
With Environment.GetEnvrionmentVariables()
	Foo: , Ping: 
```
and runtimeconfig looks like this:
```sh
$ cat bin/Debug/net6.0/publish/foo.runtimeconfig.json 
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "configProperties": {
      "Foo": true,
      "Ping": "pong"
    }
  }
```

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky and @elinor-fung This sounds similar to an offline conversation we were having.

**Comment by gbthakkar** [comment]
Hi All,
It is surprizing that, why it is so hard to understand the issue.
May be we do not know the correct / easy / straight forward way to do it.

We have launchSettings.json for console or desktop application, which we can use to supply environment variable.

How can we supply/set environment variable when running a published app?

(1) set command line param to use launchSettings.json? how to supply the whole file at cmd param?
(2) Can we have something in app.runtimeconfig.json which is equivalent to "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development"?
(3) if using bat file and is the only option? what should be the arg name?

**Comment by vitek-karas** [comment]
@gbthakkar 
I think there are two parts to this which are somewhat different.

The root issue of the above discussion is about the ability to set specific runtime knobs "permanently" for an app - without having to set env. variables. As noted by @am11 there's already a mechanism (`RuntimeHostConfigurationOption`) to persists some configurations for the runtime to see. There might be cases where a given runtime knob doesn't look at that configuration and only reacts to env. variable. If that's the case, I think it's a very simple feature request (or maybe a bug fix) to modify that specific runtime knob to also react to a configuration property (similar to lot of other runtime knobs which already do this).

The other side of this is the ability to set any env. variable via some configuration file. I think that's something the .NET runtime should not be in the business of solving. Environment variables are in the domain of the OS and it defines their behavior. If a .NET app chooses to rely on them by calling APIs which accesses them, that's the choice of the app. (Yes, the runtime looks at env. variables as well, but as noted above, in general the runtime should be able to react to other forms of configuration, not just env. variables for this). For some apps this is related to "configuration" in general, but again how that is done is a choice of the app. Some use env. variables, some use config files and so on. .NET provides libraries to help with this, for example `Microsoft.Extensions.Configuration` but using those is optional. I'm no expert on this area though. @eerhardt would probably know where to look further for the "configuration of an app" topic.

**Comment by AaronRobinsonMSFT** [comment]
@vitek-karas Agree with the sentiment above. Perhaps the above should be captured in a best practices section somewhere and an example on how to use the various options - configure runtime, configure your app. Once those two are created, I think this issue could be closed.

**Comment by eerhardt** [comment]
> There might be cases where a given runtime knob doesn't look at that configuration and only reacts to env. variable. If that's the case, I think it's a very simple feature request (or maybe a bug fix) to modify that specific runtime knob to also react to a configuration property (similar to lot of other runtime knobs which already do this).

+💯 

> The other side of this is the ability to set any env. variable via some configuration file. I think that's something the .NET runtime should not be in the business of solving. Environment variables are in the domain of the OS and it defines their behavior. If a .NET app chooses to rely on them by calling APIs which accesses them, that's the choice of the app.

Another thing to consider is when there is a conflict, which value would "win"? The actual OS environment variable or the value under `environmentVariables` in the runtimeconfig.json? (or in the case of all the other runtime properties - the value in `configProperties`)

**Comment by agocke** [comment]
Agreed -- I don't think stomping on environment variables is the right thing to do here. Let's focus this down to a specific use case, like setting runtime flags.

**Comment by agocke** [comment]
I filed https://github.com/dotnet/runtime/issues/81713 to address the specific problem with DOTNET_Thread_UseAllCpuGroups
