### ISSUE TITLE
GetGCMemoryInfo.TotalAvailableMemoryBytes returns negative value on ARM32

### ISSUE THREAD

**Issue by brianpopow** [dotnet/runtime#65466]
### Description

`GC.GetGCMemoryInfo().TotalAvailableMemoryBytes` reports negative values on linux/ARM32.

The is issue was brought to our attention original with [ImageSharp Raspberry Pi OS 11 Issue](https://github.com/SixLabors/ImageSharp/issues/2001)

There was a similar Issue already reported here [issues/13115](https://github.com/dotnet/runtime/issues/13115), but this was closed.

The following simple code snippet triggers the issue:
```
Console.WriteLine("TotalAvailableMemoryBytes = " + GC.GetGCMemoryInfo().TotalAvailableMemoryBytes);
```

I tried the following official dotnet sdk images:

- mcr.microsoft.com/dotnet/sdk:6.0.102-bullseye-slim-arm32v7
- mcr.microsoft.com/dotnet/sdk:6.0.102-focal-arm32v7
- mcr.microsoft.com/dotnet/sdk:5.0.405-buster-slim-arm32v7

All report TotalAvailableMemoryBytes = -402354176

### Reproduction Steps

```
Console.WriteLine("TotalAvailableMemoryBytes = " + GC.GetGCMemoryInfo().TotalAvailableMemoryBytes);
```

### Expected behavior

Report a positive number of available bytes.

### Actual behavior

TotalAvailableMemoryBytes = -402354176

### Regression?

ARM64 does not seem to be affected.

.NET Core 3.1.416 does not seem to be affected (tried with docker image: `mcr.microsoft.com/dotnet/sdk:3.1.416-bullseye-arm32v7`)

### Configuration

- .NET version  6.0.102 and 5.0.405
- architecture: ARM32

**Comment by cshung** [comment]
@antonfirsov, @brianpopow can you still reproduce the issue?

**Comment by antonfirsov** [comment]
This has been reported by an ImageSharp user in https://github.com/SixLabors/ImageSharp/issues/2001 for Raspberry Pi OS 11 - Bullseye. I don't have the any HW to repro. ImageSharp implemented a sub-optimal workaround to deal with this issue.

Was there a change in the runtime that potentially addressed this?

**Comment by cshung** [comment]
> This has been reported by an ImageSharp user in [SixLabors/ImageSharp#2001](https://github.com/SixLabors/ImageSharp/issues/2001) for Raspberry Pi OS 11 - Bullseye. I don't have the HW to repro it, unfortunately. ImageSharp implemented a sub-optimal workaround to deal with this issue.
> 
> Was there a change in the runtime that potentially addressed this?

I confirmed that the managed API, `GetGCMemoryInfo.TotalAvailableMemoryBytes`, faithfully reports the value stored in `gc_heap::total_physical_mem`, the field is a `uint64_t`, which cannot be negative (but of course, could be a wrong value). The property `GetGCMemoryInfo.TotalAvailableMemoryBytes` is a long, which is a 64-bit signed integer, and there is a possibility that the conversion generated a negative number)

Indeed, if I hard code `gc_heap::total_physical_mem` to 0xF000 0000 0000 0000`, it is possible to force the API to return a negative value.

If I hard code `gc_heap::total_physical_mem` to 0xF000 0000`, the `GetGCMemoryInfo.TotalAvailableMemoryBytes` returned a positive number just fine.

Analyzing the code further, it must be the case that `GCToOSInterface::GetPhysicalMemoryLimit`. That API returns a `uint64_t`, but it could return a bogus value that is larger than 2^63-1. 

For Linux, the detection of memory info is based on `sysctl`. For that, unfortunately, without the repro hardware, there is no way to look at that further.

There is indeed something suspicious in the underlying code, something along this line.

https://github.com/dotnet/runtime/blob/18d0367c7abeaa752990654b6884459235ef7c10/src/coreclr/gc/unix/cgroup.cpp#L507-L516

That case is specific to containers though - note that `size_t` is an unsigned 32-bit integer on a Linux ARM machine.

In various places, I also see `size_t` is used in the available physical memory code path, which could be a reason.

**Comment by cshung** [comment]
Turn out I am able to repro on an ARM64 device by installing an ARM dotnet SDK. I will take it from there.

**Comment by antonfirsov** [comment]
If this helps or is interesting for any reason: The value [reported by the user](https://github.com/SixLabors/ImageSharp/issues/2001#issuecomment-1041831012) was `-456847360` which is `18446744073252704256` unsigned.

**Comment by antonfirsov** [comment]
I'm stupid, and missed that @brianpopow had a repro: https://github.com/SixLabors/ImageSharp/issues/2001#issuecomment-1042041079
