### ISSUE TITLE
[mono] AOT compiler fails when assembly files are named in other cultures

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#65484]
### Description

Given a dll named テスト.dll, the mono aot compiler will fail because it cannot handle other cultures.

### Reproduction Steps

Use a mono functional test and add a project that generates テスト.dll.  Make sure `<RunAOTCompilation>` is true and you'll see the error when fed to the AOT compiler.

### Expected behavior

The assembly AOT's as expected

### Actual behavior

The AOT compiler fails with a generic error message

### Regression?

No

### Known Workarounds

Rename the assembly

### Configuration

All mono configurations where an AOT compiler is involved.  Android, iOS, tvOS, MacCatalyst, Browser, etc.

### Other information

This issue came from XA originally https://github.com/xamarin/xamarin-android/issues/6685

**Comment by lewing** [comment]
cc @radical
