### ISSUE TITLE
JsonObject does not respect JsonSerializerOptions e.g. PropertyNamingPolicy = JsonNamingPolicy.CamelCase

### ISSUE THREAD

**Issue by samcarton** [dotnet/runtime#65493]
### Description

While building a `JsonObject` in memory, I would expect it to adhere to the `JsonSerializerOptions` that are passed to the `.ToJsonString(...)` method. However it ignores `PropertyNamingPolicy` at least, and does not give me confidence that it respects any of the other converters or settings I may have added to my options.

### Reproduction Steps

```
var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
var jsonObject = new JsonObject{
	["ThisShouldBeCamelized"] = "some value"
};
var serialized = jsonObject.ToJsonString(options);
Console.WriteLine(serialized);
// returns {"ThisShouldBeCamelized":"some value"} instead of {"thisShouldBeCamelized":"some value"}
```

### Expected behavior

`JsonObject` serialization should respect `JsonSerializerOptions`, or at least, the `PropertyNamingPolicy` option. Otherwise it should take in it's own options object with things it explicitly supports.

### Actual behavior

It does not respect the options passed in.

### Configuration

.NET 6.0

### Other information

related:  #61843 which was closed with a solution of "use `JsonObject` instead"

**Comment by layomia** [comment]
This is by design, please see https://github.com/dotnet/runtime/issues/54184#issuecomment-882644924.
