### ISSUE TITLE
Should the DllImportGenerator be packable or not?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#65495]
[The DllImportGenerator.csproj sets `IsPackable` to true](https://github.com/dotnet/runtime/blob/385fc8832b1d4160abe13645054b65458b6a12f8/src/libraries/System.Runtime.InteropServices/gen/DllImportGenerator/DllImportGenerator.csproj#L14) but [the outer Directory.Build.props sets it to false](https://github.com/dotnet/runtime/blob/385fc8832b1d4160abe13645054b65458b6a12f8/src/libraries/System.Runtime.InteropServices/gen/Directory.Build.props#L5).

Because of that, packaging is currently disabled. Should it be enabled or not? @jkoritzinsky @MichalStrehovsky

**Comment by ViktorHofer** [comment]
@jkoritzinsky @MichalStrehovsky do you know?

**Comment by MichalStrehovsky** [comment]
> @jkoritzinsky @MichalStrehovsky do you know?

Cc @dotnet/interop-contrib. I don't know much about DllImportGenerator. I made a fix in the above mentioned Directory.Build.props because it was causing test breaks but that's the extent of my involvement.
