### ISSUE TITLE
Make it possible to build just the shared framework projects or the out-of-band projects

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#65492]
Today the _libs.ref_ and the _libs.src_ subsets build both the shared framework and the out-of-band projects. [The CLR team let us know](https://github.com/dotnet/runtime/issues/51168) that they would like to spend less time on building the libs subset and  don't need the out-of-band projects like the Microsoft.Extensions.* ones being built.

I agree with that sentiment and we even had discussion in the past whether the out-of-band projects should even be moved into a separate repository. That shouldn't be necessary as writing out-of-band projects has become much easier with ongoing infrastructure investments like the pkgproj removal but it would be great if we could split the libs subset so that devs can intentionally build the shared framework projects or the out-of-band projects separately. Of course you still need to build the shared framework once before you can build the out-of-band projects as they rely on the shared framework live build.

**I propose that we change the existing _libs.ref_ and _libs.src_ subsets to _libs.sfx_ and _libs.oob_.** The _libs.ref_ subset shouldn't be necessary anymore as reference projects are already built incrementally together with the source projects.
In https://github.com/dotnet/runtime/pull/64000#issuecomment-1040848408 @joperezr expressed the desire to be able to still just build the refs to make it possible to launch VS as quickly as possible without building the shared framework source projects. That will continue to be possible but with a slightly different command, instead of `build.cmd/sh libs.ref` it will be `build.cmd/sh libs.sfx /p:RefOnly=true`. See https://github.com/dotnet/runtime/pull/64000#issuecomment-1041300245 for a more detailed explanation why only the refs of the sfx subset need to be built.

Ideally this will happen with the next infrastructure rollout (March 2022) as when https://github.com/dotnet/runtime/pull/64000 gets merged this will just be a matter of removing the existing "libs.ref" and "libs.src" subsets.

cc @safern @joperezr @ericstj

**Comment by ericstj** [comment]
I'm supportive of this.  Will it include the desktop compat shims that reference all the OOB packages, or will we exclude those in this case?

**Comment by ViktorHofer** [comment]
This already got implemented in main. Closing.

Today the shims aren't built in the libs.sfx subset, only in the libs.oob subset. Potentially this could change if we check-in the generated facade source file from GenFacades and in the OOB subset later then just verify that it is up-to-date.
