### ISSUE TITLE
Unable to work with PerformanceCounters when running with Globalization Invariant Mode

### ISSUE THREAD

**Issue by urikanonov** [dotnet/runtime#65502]
### Description

PerformanceCounter's was creating culture objects using LCID. When running with Globalization Invariant Mode, it is not allowed to create any culture using LCID. Also, if the switch DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY is set to true there, it will not allow creating any culture even using culture names except the Invariant culture. That means PerformanceCounter library will not be usable at all when enabling the Globalization Invariant Mode.

The fix here is to allow running PerformanceCounter with the Globalization Invariant Mode and always report counters matching the English language at that time.

### Reproduction Steps

Run an application in globalization invariant mode and create a PerformanceCounter.
See code in this PR fixing the issue for .NET 7:
https://github.com/dotnet/runtime/pull/65414/files#diff-b565316299a8eab77f34ea3c771ff19b01d91f26a278e935ccd7d5afcc11dd77

### Expected behavior

To allow running PerformanceCounter with the Globalization Invariant Mode and always report counters matching the English language at that time.

### Actual behavior

The CultureInfo ctor throws an exception.
The ask is the backport this fix to .NET 6:
https://github.com/dotnet/runtime/pull/65414/files#diff-b565316299a8eab77f34ea3c771ff19b01d91f26a278e935ccd7d5afcc11dd77

### Configuration

.NET 6, Windows

### Other information

Need to backport the fix already checked in for .NET 7:
https://github.com/dotnet/runtime/pull/65414

**Comment by tarekgh** [comment]
The PR https://github.com/dotnet/runtime/pull/65537 fixed this.
