### ISSUE TITLE
Implementing async/await using source generators

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/runtime#65540]
I want to start a discussion about async/await. I could have opened this issue in roslyn repo, but I thought maybe it is relevant more to runtime, although if it makes more sense to be in that repo I will close it and move there.

Reason: async/await is not extensible enough for use case. I want to use async/await syntax without GC and so I want to manually manage the tasks and threads.

Has any thought been given to implement async/await using source generators.

Are there other things C# compiler does that could be done using source generators that today is IL level emission?

**Comment by Clockwork-Muse** [comment]
>  I want to use async/await syntax without GC

If you're concerned about GC resource use, `async`/`await` are likely to be relatively small compared to the rest of the runtime/typical application use.  Which means it feels like you'd be asking for a GC-less runtime.

That said, if your actual use-case warrants it, you may want to look at [`ValueTask`](https://devblogs.microsoft.com/dotnet/understanding-the-whys-whats-and-whens-of-valuetask/).

> Has any thought been given to implement async/await using source generators.

The biggest problem with this is that `async`/`await` allow functions to be [coroutines](https://en.wikipedia.org/wiki/Coroutine). and be _suspendable_.  Source generators aren't going to "magically" change that, or not take memory or something.  Anything such a source generator could do, it's likely that the compiler/JIT could do (or better)...

**Comment by teo-tsirpanis** [comment]
Hello @simplejackcoder, source generators cannot _replace_ code, only _add_; which is the reason `async`/`await` cannot be implemented on top of them. Moreover these keywords predate source generators by about eight years.

I am interested however in your use case. Can you tell me more?

Also note that some form of allocations is inevitable in asynchronous code; when execution of a method is suspended the method returns and its state must be stored in the heap. You can use `ValueTask` as @Clockwork-Muse said, or you can go even further in memory savings by using the `System.Runtime.CompilerServices` namespace and applying `[AsyncMethodBuilder(typeof(PoolingAsyncValueTaskMethodBuilder))]` to your `ValueTask`-returning methods, but do that last step _only after having profiled your code and concluded that this is where your bottleneck is_.
