### ISSUE TITLE
mark SslProtocols.Tls and SslProtocols.Tls11 as obsolete

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#65546]
We marked `Ssl2`and `Ssl3` as obsolete while ago. With recent push for more secure defaults and behavior and with recent Azure and `CipherSuitePolicy` changes I feel it is time to mark 1.0 and 1.1 as obsolete since industry no long consider them as safe.

cc: @blowdart

**Comment by karelz** [comment]
@blowdart I am curious what is your take on it.

**Comment by wfurt** [comment]
I think we do default to `SslProtocols.None' everywhere but we can certainly check. That should leave Tls 1.2 normal and 1.3 as nice improvement.

**Comment by wfurt** [comment]
It is good to be paranoid! (but are we paranoid enough @blowdart ?)

**Comment by karelz** [comment]
Triage: We want to do it early in 7.0 to collect feedback on the breaking change if there is any.
It should be simple - there is doc how to obsolete stuff.

**Comment by rzikm** [comment]
Obsoletion instructions at https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md
