### ISSUE TITLE
mark EncryptionPolicy.NoEncryption as obsolete

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#65545]
The `EncryptionPolicy` now looks like:
```
    public enum EncryptionPolicy
    {
        RequireEncryption = 0,
        AllowNoEncryption = 1,
        NoEncryption = 2,
    }
```

Creating `SslStream` and forcing no encryption is just pure weird. While old SSL/TLS versions permitted it and while it may be useful for debugging, nobody should really be using it in production at this point. `AllowNoEncryption` is somewhat on the same boat. NULL encryption is no longer available as of Tls 1.3. 

We marked `Ssl2` and `Ssl3` `SslProtocols` as obsolete because they are weak. No encryption is even worse from security prospective. 

related to #26210

**Comment by jeffhandley** [comment]
See https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md for obsoletion instructions.

**Comment by wfurt** [comment]
I expect you would be OK with `SslStream` expecting encryption @blowdart? (and not allowing NULL unless somebody tries hard e.g. marking `AllowNoEncryption` as obsolete as well)

**Comment by blowdart** [comment]
That becomes more interesting. Null ciphers are, as you say, handy for debugging, but given TLS1.3 threw it all away I have mixed feelings. I'd say yes, do away with it all, but do it early now and see if anyone screams.
