### ISSUE TITLE
Change default of SslServerAuthenticationOptions.AllowRenegotiation to be false

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#65547]
related to #26210
While allowing renegotiation on client could be useful - to for example get late client certificate, there is no compelling reason to allow this on server. Renegotiation had issues in the past and it is seen somewhat problematic by the industry. 
Also in Tls 1.3 renegotiation is forbidden/removed  so there is really now way how to honor this going forward.

This should contribute to safer TLS defaults. 

cc: @blowdart

**Comment by karelz** [comment]
Triage: Server-side Renegotiation is viewed as insecure by the industry (it has been removed from TLS 1.3 entirely). We should disable it by default.
Note: No change to client-side.

@blowdart any thoughts here?

**Comment by blowdart** [comment]
Do it :)
