### ISSUE TITLE
Visual Studio restore is broken as projects are missing from the dependency closure

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#65552]
Since I applied various fixes to the product over the last weeks that should make the overall IDE experience better I wanted to try them out and had to realize with dismay that the integrated Visual Studio restore is still broken if an upfront restore via the CLI (`dotnet restore`) isn't performed. The impact of that is that the solution is unusable.

The root cause for that lies in this code path: https://github.com/dotnet/runtime/blob/cc649acaec3cad932f593ab71a8da85bbf7aa49f/eng/slngen.targets#L8-L11 This causes slngen to not include reference projects which are part of the shared framework and aren't shipping out-of-band. Even though, shared framework reference assemblies are only referenced via "Reference" items by source projects, the reference projects themselves reference each other via ProjectReferences. Note that VS restore requires all dependencies expressed via `ProjectReference` items to be present in the solution file and ignores `Reference` items as those point to the compiled assembly and there's nothing for restore to do on those.

As an example, ref/System.Drawing.Common.csproj inside `System.Runtime.sln` is depending on ref/System.Collections.NonGeneric.csproj but as it is missing, the restore inside Visual Studio fails.

If I remove the condition in the slngen.targets file and re-generate all solution files (`dotnet.cmd build src\libraries\slngen.proj`), the solution files get larger by about 50 ref projects (as the solution now includes all dependencies) but the solution restore finally works and no up-front restore is necessary anymore. Note that because the reference projects are very small and fast to evaluate, the solution load time **doesn't increase noticeably** and the solution doesn't look overloaded as all the added projects are grouped inside the "ref" folder (tested with VS 2022 17.2 Preview 1).

**Because of that I propose that we remove the condition in the slngen.targets file with the caveat that solutions get bigger but with the huge win that up-front restores aren't necessary anymore**. That means instead of:

```cmd
build.cmd libs.sfx /p:RefOnly=true
build.cmd -restore libs
build.cmd -vs System.Runtime
```

I can now directly open VS after the libs.ref subset is built:

```cmd
build.cmd libs.sfx /p:RefOnly=true
start src\libraries\System.Runtime\System.Runtime.sln
```

or just continue to use the VS switch for convenience (which also uses the repo local SDK which is useful when a matching one isn't globally installed):

```cmd
build.cmd libs.sfx /p:RefOnly=true
build.cmd -vs System.Runtime
```

Ultimately at some point in the future when source projects use `ProjectReference` items instead of `Reference` items to dynamically express their dependencies, the `build.cmd libs.ref` step won't be necessary anymore either and a dev will be able to directly open a VS solution file from a fresh clone.

@ericstj @safern @joperezr @carlossanlop any objections to what I'm proposing?

**Comment by ViktorHofer** [comment]
Would love to hear people's opinion about the above described issue. What I heard from the recent community survey is that one of the top pain points is that solution files in our repositories can't be opened without ceremony involved. Fixing the VS restore by making sure that the dependency closure is satisfied by the solution files would get us closer to the community's wish.

**Comment by joperezr** [comment]
I'm not opposed to what you are proposing, but I think that is still not what the community wants. The main ask here would be to be able to open a solution in VS after a clean `git clone` and even with your proposal, this wouldn't be possible. In fact, I'm not even sure that is something we can ever achieve given the fact that a lot of our infrastructure for building lives in Arcade which needs to be restored at least once before opening a solution, so even though with your proposal the "ceremony" is being shorter, it is still there. Perhaps something we can consider instead of making the more expensive changes proposed, is to consolidate the current ceremony into a single command.

The current upfront restore in a traditional machine with a decent network, doesn't really take that much (around 2 minutes). I am sure that with your proposed changes this is reduced greatly, but have you measured that and if so can you share some of the perf impact?

I guess my uber point is, before we go about and make some changes that will have notable differences to all (people will start seeing 50+ projects inside the ref/ folder in the solution) we should measure and make sure that the cost is worth the benefit, especially since the end result is not meeting the desired community result.

**Comment by ericstj** [comment]
cc @stephentoub @eerhardt 

I guess the tradeoff for some here is the sln size and build performance.  You've also done more work recently to improve that. 
 Can you measure the difference for incremental build after a small change in the src library in some common SLNs before and after and share it?

For example System.Runtime, System.Text.Json, and Microsoft.Extensions.Logging?  I think those are somewhat representative of the developer workflows for bottom, middle, and top of stack.

**Comment by eerhardt** [comment]
> and Microsoft.Extensions.Logging

Can you change that to `Microsoft.Extensions.Hosting`? That one is the most "top of the stack" since it references almost everything (including Logging).

My opinion is roughly inline with @joperezr above - if I need to run something up front, I'd rather that "up front" cost be more and my incremental cost (building constantly in VS, running tests, etc) be lower. After pulling new code, I kick off a repo `libs+clr -rc Release` build. I need to do that in order to run unit tests anyway. So having VS load more projects and become slower to load/build/etc isn't worth the tradeoff IMO.

**Comment by ViktorHofer** [comment]
> Can you change that to Microsoft.Extensions.Hosting? That one is the most "top of the stack" since it references almost everything (including Logging).

I spent some more time thinking about how to fix the current broken behavior without increasing the build graph. Out-of-band projects already build on-top of the shared framework since we split the libs build into "libs.sfx" and "libs.oob". As these projects already sit on the top, we can just use the default targeting pack references for OOBs and remove the ProjectReferences that point to inbox projects. Note that this is already the behavior for most OOB source projects. Overall that will actually make the build graph and by that, solution files smaller for OOBs.

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/68543 accidentally closed this issue. Reopening.

**Comment by ViktorHofer** [comment]
> I'm not opposed to what you are proposing, but I think that is still not what the community wants. The main ask here would be to be able to open a solution in VS after a clean git clone and even with your proposal, this wouldn't be possible. In fact, I'm not even sure that is something we can ever achieve given the fact that a lot of our infrastructure for building lives in Arcade which needs to be restored at least once before opening a solution, so even though with your proposal the "ceremony" is being shorter, it is still there. Perhaps something we can consider instead of making the more expensive changes proposed, is to consolidate the current ceremony into a single command.

@joperezr

**Comment by ViktorHofer** [comment]
from @joperezr
> In fact, I'm not even sure that is something we can ever achieve given the fact that a lot of our infrastructure for building lives in Arcade which needs to be restored at least once before opening a solution, so even though with your proposal the "ceremony" is being shorter, it is still there. Perhaps something we can consider instead of making the more expensive changes proposed, is to consolidate the current ceremony into a single command.

Infrastructure that lives in Arcade is built and packaged there and we consume those libraries the usual way via PackageReferences, which are part of a project's restore. Your statement that these need to be up-front restored before a solution can be opened isn't right. NuGet is part of Visual Studio and makes sure that all dependencies (PackageReferences, PackageDownload, FrameworkReferences, msbuild sdks, ...) are restored on the fly.

The reason why src/libraries solutions can't be opened from a fresh clone is because dependencies inside the shared framework aren't defined via ProjectReference items. As an example, [`System.Collections.NonGeneric` depends on System.Threading](https://github.com/dotnet/runtime/blob/763fd1a67229a51e2cfbe1a485279d4fa6b58f24/src/libraries/System.Collections.NonGeneric/src/System.Collections.NonGeneric.csproj#L21) but because that dependency isn't expressed via a ProjectReference, System.Threading isn't available when System.Collections.NonGeneric is built.

from @ericstj
> I guess the tradeoff for some here is the sln size and build performance. You've also done more work recently to improve that.

With recent improvements (https://github.com/dotnet/runtime/pull/68488, https://github.com/dotnet/runtime/pull/68543 and https://github.com/dotnet/runtime/pull/68603), a project's build graph is now as short as possible. Before these changes were merged, a project's build graph contained many unnecessary dependencies, which impacted both the evaluation and restore/build performance.

> Can you measure the difference for incremental build after a small change in the src library in some common SLNs before and after and share it?

I can finally share some data based on https://github.com/dotnet/runtime/pull/68668 which builds on top of the improvements listed above.

| Project | No. of Projects Before | No. of Projects After |
| --- | --- | --- | --- | --- |
| System.CodeDom | 9 | 6 |
| System.Runtime | 25 | 25 |
| System.Runtime.Serialization.Formatters | 55 | 58 |
| System.Text.Json | 23 | 27 |
| Microsoft.Extensions.Hosting | 74 | 75 |

In some cases the number of projects in the solution file drops, in most cases it increases between 1-5 projects and in a few cases it increases between 10-15 projects. The time it takes to load and evaluate the solution file shouldn't change much by adding this number of projects. Visual Studio invested a lot in evaluation, Intellisense and restore performance over the last years.

@ericstj regarding incremental build performance, I'm not sure what you ask me to verify. AFAIK Visual Studio's fast up-to-date check doesn't incrementally build projects that haven't changed (based on inputs & outputs).
If I would change the sln's main source library, I would not see a difference at all because the libraries being added with my change aren't depending on the source library and hence don't build at all.

**Comment by ericstj** [comment]
> I'm not sure what you ask me to verify. 

My suggestion was to show others that the impact of this change on their daily work is minimal and that the tradeoff is a good one. 

> AFAIK Visual Studio's fast up-to-date check doesn't incrementally build projects that haven't changed (based on inputs & outputs).

Very cool.  Testing that out in these cases and confirming that we don't do anything funny in dotnet/runtime to break that would be a good piece of data to share here. 

Maybe share the time to do a build for these sln's once they are loaded with no changes over what was already built up front?  Also the time for build after a comment change in the src library?
You can use the [Project System Tools](https://github.com/dotnet/project-system-tools) Build Logging window to capture the "Elapsed" time of the build.
If both are very small (like under a couple seconds) then its probably sufficient to demonstrate that we have a good workflow.  If they aren't small then you can share the diff before/after a change to show that it didn't get any worse.

I think these small checks and the new data you've shared around the actual number of projects (which is much less than 50 per sln) address the concerns raised by @joperezr and @eerhardt.
