### ISSUE TITLE
Define RIDs for CBL-Mariner

### ISSUE THREAD

**Issue by mthalman** [dotnet/runtime#65566]
.NET is officially supported on [CBL-Mariner](https://github.com/microsoft/CBL-Mariner/) but there aren't any RIDs defined for it. CBL-Mariner 1.0 has already been released and 2.0 is being release next month. RIDs should be defined for both.

Suggested RID format is `cbl-mariner`. Supported architectures are x64 and arm64.

This also should be backported to all versions:

- [ ] 7.0/main
- [ ] 6.0
- [ ] 5.0
- [ ] 3.1

**Comment by am11** [comment]
> but there aren't any RIDs defined for it

Not needing to define distro-level RID and things working out fine for everybody's use-cases is actually a sign of good and scalable ecosystem..

**Comment by mthalman** [comment]
> > but there aren't any RIDs defined for it
> 
> Not needing to define distro-level RID and things working out fine for everybody's use-cases is actually a sign of good and scalable ecosystem..

It works fine now. But what happens when there are differences that need to be accounted for? From talking with @richlander, the intent is to have RIDs for all supported operating systems.

**Comment by am11** [comment]
> what happens when there are differences that need to be accounted for? 

The difference which matters in most (if not all) real-world scenarios is base platform (linux, darwin, win32 etc.), libc flavor (glibc, musl-libc, bionic-libc, posix-libc etc.) and  architecture (x86, x64, arm64 etc.). The native code and its associative consumer code is usually written with run-time checks, polyfills and fallbacks. Generally, .NET developers tend to write portable code and seldom delve into OS differences, let alone distro-level (or worse, distro-version-level) distinctions.

> the intent is to have RIDs for all supported operating systems.

Sure, linux-x64 and linux-arm64 RIDs are already defined in the RID graph, which apply to CBL-Mariner as well.

ps - out of ~300 linux distros, only handful of them are explicitly defined in the RID graph ([json file](https://github.com/dotnet/runtime/blob/1ea9cf4eb3b48f6707e29dace31eaa4a8297bb93/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json)), mostly from the .NET Core 1x era. Yet, binary tarball for linux-{arch} downloaded from https://dot.net works on most of the distros regardless of their presence in the graph. Case in point, Amazon Linux, which is also missing in the graph yet .NET is working out just fine in AWS cloud for years.

**Comment by jkotas** [comment]
> From talking with @richlander, the intent is to have RIDs for all supported operating systems.

We do not have agreed upon approach adding Linux distro RIDs. For example, check the discussion in https://github.com/dotnet/runtime/pull/62184 about adding RID for almalinux.

There are way too many Linux distros. We cannot scale to have RID for each for them and we have not seen many real-world cases where the Linux distro specific RIDs are actually useful.

**Comment by ericstj** [comment]
@richlander do we have any customers asking for this?  Has anyone needed to explicitly target `cbl-mariner`?  

I think for these brand new `RIDs` we should start out in the host as that's the first thing that needs to change to make them useful.   The host needs to start identifying a distro with a particular RID.

**Comment by agocke** [comment]
I think this will likely be obsolete if we can complete https://github.com/dotnet/runtime/issues/59803. I'm moving to 8.0 for evaluation in that time frame.

**Comment by richlander** [comment]
I think Mariner can use the portable linux RID.
