### ISSUE TITLE
R2R ignores AdvSimd on ARM64

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#65587]
```csharp
public static double Max(float val1, float val2)
{
    return AdvSimd.Max(
        Vector128.Create(val1),
        Vector128.Create(val2)).ToScalar();
}
```
R2R output:
```asm
; Method Tests4:Max(float,float):double
G_M22983_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M22983_IG02:
            dup     v1.4s, v1.s[0]
            dup     v0.4s, v0.s[0]
            adrp    x11, [HIGH RELOC #0xd1ffab1e]      // function address
            add     x11, x11, [LOW RELOC #0xd1ffab1e]
            ldr     x0, [x11]
            blr     x0
            brk_windows #0
Emitting R2R PE file: aot
; Total bytes of code: 36
```
I invoke crossgen2 with `--targetos linux --targetarch arm64 -O`
`--instruction-set:+base,+neon` doesn't help either (and should not be needed since AdvSimd is a baseline anyway)

cc @davidwrighton can it be related to your PR https://github.com/dotnet/runtime/pull/65351 ?

**Comment by EgorBo** [comment]
Not an issue - the problem that we have to reference arm64 version of corelib instead of x64

**Comment by tannergooding** [comment]
Is there a concern here around cross-compilation or other scenarios where users may accidentally get the "wrong corelib"? We have a "similar" situation with the AltJIT and it can make cross platform/architecture JIT debugging somewhat problematic.

Notably, we could minimally support scenarios like AltJIT, Godbolt, or disasmo by simply marking the "unsupported" ISAs as `Intrinsic`. The JIT already has the handling to statically treat these as `throw PNSE` when corelib and the JIT target don't match. So it would at least allow those scenarios to utilize hardware intrinsics, likely leading to easier xplat debugging.

The alternative would likely be to provide "alt corelibs", much as we provide "alt jits", and to ensure that the right one is picked when in the AltJIT/Godbolt/disasmo/etc scenario.

**Comment by EgorBo** [comment]
cc @dotnet/crossgen-contrib - is it expected that we can normally reference x64 corelib for crosscompilation to arm64?

**Comment by jkotas** [comment]
There is no concern when you are using proper cross-compilation environment. These environments do get the right corelib.

This is only a problem with the altjit cross-compilation hack that the codegen team likes to use as shortcut. This hack does not have the 100% fidelity by design.
