### ISSUE TITLE
Add tests for List<T> mutations in Exists, FindAll, TrueForAll

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#65608]
We recently closed a PR trying to improve the performance of Exists, FindAll, and TrueForAll.  While it made a meaningful improvement, it did so by iterating up to the _size that was current when the method was called, which ends up being a behavioral change if the delegate invoked added to the list (and thus increased _size).  No tests failed, however, which means we're not currently testing these cases.  We should add in tests to make it obvious in the future if we make any changes that could impact these behaviors.

https://github.com/dotnet/runtime/pull/65572#issuecomment-1044993127

**Comment by B1Z0N** [comment]
May I take this one or is it already taken? @stephentoub @SkiFoD

**Comment by SkiFoD** [comment]
@B1Z0N Sure, we can work together on the issue.

**Comment by DDolG** [comment]
Hello. I don't understand why this question is still open? It seems like the PR is accepted.

**Comment by stephentoub** [comment]
Normally PRs include a "fixed" directive that automatically closes the associated issue.  This was missing one and so the issue remained open.
