### ISSUE TITLE
"runtime-libraries enterprise-linux" jobs failing due to network issue

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#65621]
https://dev.azure.com/dnceng/public/_build/results?buildId=1622757&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba&l=20
```
__DistroRid: linux-x64
Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
curl: (6) Couldn't resolve host 'dotnet.microsoft.com'
Curl failed; dumping some information about dotnet.microsoft.com for later investigation
140132104868288:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:704:Temporary failure in name resolution
connect:errno=11
```

Happened at least three times on the same PR.

**Comment by ericstj** [comment]
I queued a couple builds to help us understand what's going on.
release/6.0-tip: https://dev.azure.com/dnceng/public/_build/results?buildId=1659265&view=results
release/6.0 prior to the change that first saw this failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1659273&view=results

**Comment by danmoseley** [comment]
Note that we already pass `--retry 10` to curl, it's retrying for 20 minutes:
```
2022-02-10T19:05:00.6681239Z Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
2022-02-10T19:25:44.2288504Z curl: (6) Couldn't resolve host 'dotnet.microsoft.com'
2022-02-10T19:25:44.2301300Z Curl failed; dumping some information about dotnet.microsoft.com for later investigation
2022-02-10T19:26:04.2567597Z 139683025289664:error:2008F002:BIO routines:BIO_lookup_ex:system lib:../crypto/bio/b_addr.c:704:Temporary failure in name resolution
```

**Comment by ericstj** [comment]
Looks like this issue is already being discussed here https://github.com/dotnet/core-eng/issues/15594  and @wfurt made a workaround for it in main.

**Comment by agocke** [comment]
Closing as dup of https://github.com/dotnet/core-eng/issues/15594
