### ISSUE TITLE
HTTPS request delays 21 secs randomly in C# (HttpClient) (UWP)

### ISSUE THREAD

**Issue by Pariventhan2015** [dotnet/runtime#65636]
Hi,

We are using HttpClient to connect with WebAPI,

Previously we had used **HTTP with localhost**, and we were facing 21 secs delay issue randomly

We found that due to proxy settings it's happened and we set UseProxy=false in the HttpClientHandler and then 21 secs delay issue was resolved, it was working good so for.

```c#
var httpHandler = new HttpClientHandler() { UseProxy = false };
```

Previous : **http://localhost:4000/**

Now we have changed that URL to **HTTPS with IP Address**, we are facing the same 21 secs delay issue and still we have set that UseProxy=false options

Now : **https://xx.xx.xx.xx:4000/**

We are using HttpClientFactory to create client for each request and didn't attach the certificate from client side as the certificate DNS was created with IP

Technologies:

Client Side : UWP

Server Side : .NET Core 2.2

Please suggest to resolve this issue

**Comment by scalablecory** [comment]
The common cause of this is trying to connect to "localhost" but hosting the server on "127.0.0.1".

These two are slightly different. On most PCs, "localhost" resolves to both IPv4 "127.0.0.1" and IPv6 "::1". When connecting to an address with multiple IPs, IPv6 is prioritized. So, it will try to connect to IPv6 first, and when that times out (which takes ~21 seconds on Windows by default) it will fall back to IPv4 and succeed.

When hosting a server for "localhost", you should ensure you host on both IPv4 and IPv6.

**Comment by Pariventhan2015** [comment]
Hi Thanks for the quick response! The WebAPI is running as windows service, **What you mean to host with IPv4 and IPv6**? Can you please share more details.
Also the API is not accessible in outside the system. Server and Client running on same system for security purpose we have used https.

Is there any way to bypass the IPv6 using code?

**Comment by antonfirsov** [comment]
First option:
Override [ConnectCallback](https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#socketshttphandler-extension-points) on `SocketsHttpHandler`, and create the socket with the constructor `Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp)` instead of the 2 args DualMode constructor.

Second option:
[Disable IPv6 globally](https://devblogs.microsoft.com/dotnet/dotnet-6-networking-improvements/#an-option-to-globally-disable-ipv6) with AppContext switch or environment variable.

If any of these options help, we can be sure diagnosis in https://github.com/dotnet/runtime/issues/65636#issuecomment-1046345148 is correct.

**Comment by Pariventhan2015** [comment]
Thanks for the Reply, Will try this.

As a quick I tried to add that SocketsHttpHandler but it's not available, as we are using .netstandard 2.0. 

We will try that AppContext switch option and update it. We can set the AppContext switch client side alone, Correct?

**Comment by Pariventhan2015** [comment]
Thanks for the Reply, Will try this.

As a quick I tried to add that SocketsHttpHandler but it's not available, as we are using .netstandard 2.0.

We will try that AppContext switch option and update it. We can set the AppContext switch client side alone, Correct?

**Comment by Pariventhan2015** [comment]
Thanks for the Reply, Will try this.

As a quick I tried to add that SocketsHttpHandler but it's not available, as we are using .netstandard 2.0.

We will try that AppContext switch option and update it. We can set the AppContext switch client side alone, Correct?

**Comment by antonfirsov** [comment]
@Pariventhan2015 sorry I missed the fact that you are on UWP / .NET Core 2.2. The options I mentioned are not available on those platforms. Does the client live in the UWP app?

**Comment by Pariventhan2015** [comment]
> @Pariventhan2015 sorry I missed the fact that you are on UWP / .NET Core 2.2. The options I mentioned are not available on those platforms. Does your `HttpClient` live in the UWP app?

@antonfirsov Yes, It's working fine on UWP. When we switch https we are getting this current issue.

**Comment by karelz** [comment]
@Pariventhan2015 are you getting similar behavior when you use directly the WinRT API [Windows.Web.Http.HttpClient](https://docs.microsoft.com/en-us/uwp/api/Windows.Web.Http.HttpClient?view=winrt-22000)?
Our `System.Net.HttpClient` is just thin layer on top of the WinRT API in UWP environment.

**Comment by Pariventhan2015** [comment]
> @Pariventhan2015 are you getting similar behavior when you use directly the WinRT API [Windows.Web.Http.HttpClient](https://docs.microsoft.com/en-us/uwp/api/Windows.Web.Http.HttpClient?view=winrt-22000)? Our `System.Net.HttpClient` is just thin layer on top of the WinRT API in UWP environment.

We are not using that. and we didn't try that, Because we are getting this issue when we test with small console application.

**Comment by Pariventhan2015** [comment]
Hi All, Any other suggestion we are with this issue.

**Comment by wfurt** [comment]
21s is TCP connect timeout on Windows. So it basically means it is trying to connect destination but the destination is not answering. If you connect to name and the name resolves to multiple addresses HttpClient should try them in sequence. 

To point @scalablecory was trying to make: Is your server also listening on IPv6 e.g. `::1`? And if not, can you make it so? 

The `UseProxy=false` is interesting. It should not really make difference but if it does it would seem some bogus proxy is being injected into your system - either through auto-configuration/discovery or via some security package. 

On that note I have seen cases when security software (like MS Defender) can interfere with networking traffic in attempt to intercept and scan content. That can lead to failures or incredibly long response. You can try to search your security longs and possibly temporarily disable any thread protection to see if that makes difference. 

And of course good old packet capture would be source of truth. If you can collect it from time when the delay happens you should able to see why @Pariventhan2015.
