### ISSUE TITLE
Please Introduce Specifier for Task to run it in P or L Core.

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/runtime#65659]
### Background and motivation

Modern CPU's has low power and performance cores. TPL Task scheduler needs to have options to define where to run specific task.  

### API Proposal

```C#
namespace [System.Threading.Tasks](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks?view=net-6.0)
{
// That is a first draft version
Enum CPUCoreType { Perfomance, GPU, LowPower, ... }

   // Additional Constructor for Tasl
   
    Task(Action, CPUCoreType)
}
```

### API Usage

n/A

### Alternative Designs

n/A

### Risks

 n/A

**Comment by EgorBo** [comment]
Related: https://github.com/dotnet/runtime/issues/21363

Can you re-format your proposal to make it clear which API you suggest to change. E.g. it can be `enum TaskCreationOptions`

**Comment by stephentoub** [comment]
This isn't really an API suggestion so much as a large feature request for the thread pool, which currently lacks such an affinization or scheduling mechanism in general.

**Comment by EgorBo** [comment]
I guess currently one can implement their own TaskScheduler and use `ProcessThread::ProcessorAffinity` to control that behavior, but there is no task API to tell the scheduler which affinity to use

**Comment by IrakliLomidze** [comment]
I Agree that is a really big change request.
Before M1 and Intel 12th Gen CPU. there was no such case, all cores were the same.
Now we have different Cores and there is a reason to add those features to the TPL and threading libraries.

**Comment by stephentoub** [comment]
> I guess currently one can implement their own TaskScheduler and use ProcessThread::ProcessorAffinity to control that behavior, but there is no task API to tell the scheduler which affinity to use

We wouldn't add a TaskCreationOptions value that the 99.999% case of using the default ThreadPool scheduler couldn't support.  There are many possible behaviors someone might want in a custom TaskScheduler that we don't make configurable via TaskCreationOptions.

**Comment by jkotas** [comment]
The different types of cores are indirectly exposed by the operating system via quality of services (QoS) APIs: 

Windows QoS APIs: https://docs.microsoft.com/en-us/windows/win32/procthread/quality-of-service
Apple QoS APIs: https://developer.apple.com/documentation/dispatch/dispatchqos/qosclass

It makes sense that the operating systems abstract the different types of cores behind an API like this. Performance/efficient cores are just one of the power management mechanisms. Another one is [Dynamic frequency scaling](https://en.wikipedia.org/wiki/Dynamic_frequency_scaling). The net effect of dynamic frequency scaling is very similar. It is basically flipping the same core between performance and efficient on the fly.

If we were to do something here, it should be along the QoS abstraction used by the operating systems.

**Comment by IrakliLomidze** [comment]
.NET Team what is a status of this suggestion is it adopted somehow  ?

**Comment by mangod9** [comment]
we will look into this for the next release.

**Comment by IrakliLomidze** [comment]
Will it be in .NET 7 Timeline or will postponed for .NET 8

**Comment by stephentoub** [comment]
I'm going to close this particular issue.  We have support for asymmetrical cores (performance/energy, big little, etc.) in our long-term plans, but anything we do here will be driven at a more encompassing level, likely starting from a design in the dotnet/designs repo.  Any APIs we add to System.Threading.Tasks would be just a small part of the larger effort.
