### ISSUE TITLE
[API Proposal]: Activity.HasRemoteParent (and problematic docs for Activity.Parent)

### ISSUE THREAD

**Issue by Oberon00** [dotnet/runtime#65660]
### Background and motivation

In an exporter, we need to process the W3C tracestate in order to add certain information to the exported data. However, this information should only apply to the span that actually had that tracestate as its direct parent, i.e. that had a remote parent. In Java, we were able to implement that exporter based on [`SpanContext ReableSpan.getParentSpanContext()`](https://github.com/open-telemetry/opentelemetry-java/blob/v1.11.0/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java#L28-L34) and [`SpanContext.isRemote()`](https://github.com/open-telemetry/opentelemetry-java/blob/v1.11.0/api/all/src/main/java/io/opentelemetry/api/trace/SpanContext.java#L152-L157). 

[ActivityContext.IsRemote](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycontext.isremote?view=net-6.0) is also available in .NET (even though it will often be wrong due to TryParse setting it to false  #42575), but there is no way to get the parent span context's IsRemote property.

For now, we use `Activity.Parent == null` as replacement. [The documentation of Activity.Parent](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.parent?view=net-6.0) makes this bold claim:

> The parent of this [Activity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-6.0), if it is from the same process, or null if this instance has no parent (it is a root activity) or if the parent is from outside the process.

implying that it will always be `!= null` if from the same process. This is obviously wrong though. In fact, the only way to explicitly pass a parent to [ActivitySource.StartActivity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.startactivity?view=net-6.0) is by passing an ActivityContext, and if using that overload, `Parent` will be `null`, regardless of whether the explicit parent context was from the same process or not (it's not even possible to know this in general).

CC @tarekgh @cijothomas

### API Proposal

```C#
namespace System.Diagnostics
{
    public partial class Activity
    {
        public bool HasRemoteParent { get; }
    }
}
```

Adding a StartActivity overload that takes an Activity as parent instead of an ActivityContext and sets Activity.Parent to that instead of `null` would also be a nice-to-have.

Changing the default IsRemote value of ActivityContext.TryParse to `true` could also be extremely helpful, as the wrong default would become potentially more impactful when being retrievable via Activity.HasRemoteParent .

Additionally, the wrong documentation on Activity.Parent should be corrected (while non-null definitely means in-process, null-ness doesn't tell you much at all, other than that the implicit parent was either not used or was actually null).

### API Usage

```C#
// Inside some OTel exporter
if (activity.HasRemoteParent)
  AddRemoteInfo(serializedActivity, activity.TraceStateString )
```

### Alternative Designs

According to [the OpenTelemetry specification of SpanProcessor.OnStart](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onstart), OnStart should receive the full parent Context (context being a required concept that is missing from OTel-dotnet and the System.Diagnostics library). If the [ActivityListener.ActivityStarted](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitylistener.activitystarted?view=net-6.0) callback could receive at least the full parent ActivityContext, it could set a Tag on the span for IsRemote. Drawback being, that this tag is then visible to everybody, with exporters exporting it by default even though it may only be of interest for particular exporter implementations.

There is also [ActivityListener.Sample](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitylistener.sample?view=net-6.0) which seems to get all the required information, however it is unclear how multiple Sample callbacks work together, and what one should do if one does not want to make any sample decision but just "misuse" the Sample callback to add [SamplingTags](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycreationoptions-1.samplingtags)

### Risks

Exposing HasRemoteParent in combination with the default IsRemote=false in ActivityContext.TryParse may expose/trigger new bugs in code that starts using it.

**Comment by Oberon00** [comment]
If https://github.com/open-telemetry/oteps/pull/182 is merged, this would be required to properly implement OTLP export, "Export SpanContext.IsRemote in OTLP" I think.

**Comment by tarekgh** [comment]
> (even though it will often be wrong due to TryParse setting it to false https://github.com/dotnet/runtime/issues/42575),

I believe we have already addressed that and now you can parse with setting up the remote option if needed. 

To double check the expectation here, the only time the parent would be remote is when creating the Activity object with the parent `ActivityContext` containing remote flag set as true. right? or you expect some other situations to make a remote parent?

CC @noahfalk @reyang

**Comment by Oberon00** [comment]
> To double check the expectation here, the only time the parent would be remote is when creating the Activity object with the parent ActivityContext containing remote flag set to true. right?

Yes, I think so.

In terms of the OTel spec, I was thinking if a edge case with sampling is possible, where an unsamped span with a remote parent would itself count as "remote" so that sampled grandchildren would have HasRemoteParent == true, but that is not the case https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sdk-span-creation

**Comment by tarekgh** [comment]
@noahfalk @reyang  @cijo this looks reasonable proposal. any thoughts?

**Comment by noahfalk** [comment]
> @noahfalk @reyang @cijothomas this looks reasonable proposal. any thoughts?

Looks reasonable to me.


> it is unclear how multiple Sample callbacks work together, and what one should do if one does not want to make any sample decision but just "misuse" the Sample callback to add [SamplingTags](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitycreationoptions-1.samplingtags)

The final sampling decision is the maximum level returned by each sampling callback. If you want to get the sampling notification but have no impact on the sampling you can return ActivitySamplingResult.None.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Diagnostics
{
    public partial class Activity
    {
        public bool HasRemoteParent { get; }
    }
}
```
