### ISSUE TITLE
Proposal: Allow delegates to implement single-interface methods.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [dotnet/runtime#6567]
Issue https://github.com/dotnet/corefx/issues/11173 and a discussion with @stephentoub prompted me to file this issue to get some knowledgeable eyes to look at an idea I had.

Specifically, in the course of that bug being fixed I was made aware that the CoreFx implements `Array.Sort(Comparison<T>)` by wrapping the Comparison in an `IComparer<T>` and forwarding along to another Sort method.  This unfortunately means an allocation, and i'm all for eliminating allocations when not necessary.

The idea i had was as follows: Allow delegates to implement interfaces with single methods on them.  i.e. I should be able to say:

``` c#
public delegate int Comparison<T>(T t1, T t2) : IComparer<T>
```

I have an idea about how this would work, but i wanted to run it by people here to see if there would be any roadblocks that would get in the way.  It's my understanding (and please correct me if I'm wrong) that a delegate is mostly just a class that inherits from System.Delegate or System.MultiCastDelegate.  It has a compiler provided `Invoke` method with the signature specified.  It seems to me that this class could just implement the specified interface, and that the .Invoke method would fill in the slot for the interface table in that class.

My hope would be that this would then 'just work'.  The `Comparison<T>` instance could then be passed freely to methods that take `IComparer<T>`s.  I'd like to play around in IL later to see if that's the case.  However, I wanted to run it by the people here to see if there's any concern at the CLR level about if this is possible or not.  Are there special shenanigans (or other delegate specializations) going on that would make this approach not work?  Or does this seem like an easy thing to do that would provide for a small alloc win.  In the case i ran into, this was actually a hot path.  The delegate was cached, but it never occurred to me that the runtime would then be adding an Alloc each time i called .Sort.  

Thanks for your help!

**Comment by mangod9** [comment]
Closing as this doesnt appear to require coreclr support
