### ISSUE TITLE
Default to IsDevelopment in common development scenarios

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/runtime#65689]
Something that keeps biting me is that a default ASP.NET Core application, or a .NET Console app that uses the Hosting APIs (e.g. as a Windows Service) defaults to the "Production" environment.

To switch it to the "Development" environment I have to manually tweak the launch settings (either as JSON or in the IDE) to set the `ASPNETCORE_ENVIRONMENT` environment variable to "Development".

If I am debugging my app from Visual Studio or Visual Studio Code, I would expect that the app would default to this environment, rather than defaulting to Production.

Am I missing something in this setup? If not, is this something that we could build into the runtime or SDK?

**Comment by am11** [comment]
You can use multiple profiles in `Properties/launchsettings.json` (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments) and use VS menu to select which one to debug. Debugging production code is also a scenario VS covers (will just skip over the optimized code).

<img src="https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments/_static/iisx2.png?view=aspnetcore-6.0" width="30%" />

e.g. from command line:
```sh
% dotnet new worker -n worker1
% cd worker1

# default profile is Development
% cat Properties/launchSettings.json
{
  "profiles": {
    "worker1": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}

# add another profile
% cat > Properties/launchSettings.json <<EOF
 {
  "profiles": {
    "Development": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    },
    "Production": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Production"
      }
    }
  }
}
EOF

% dotnet run --launch-profile Production -c Release
Building...
...
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production <-- as expected
...
```

**Comment by yaakov-h** [comment]
I am aware of this, but I find it insufficient for a couple reasons:

1. This requires me to remember if a project is using DOTNET_ENVIRONMENT or ASPNETCORE_ENVIRONMENT constantly. This morning one of my devs mixed them up, resulting on some fairly harmless but annoying and ultimately undesired outcomes.
2. Either each developer has to set this up themselves - and this is prone to error - or the project commits a `launchSettings.json` and effectively takes control of the launch profiles. There doesn't seem to be a way to have both project-defined launch profiles and user-defined launch profiles, at least not without having permanently uncommitted changes in source control, which is again prone to error.

**Comment by eerhardt** [comment]
> I would expect that the app would default to this environment

What app is "the app" in this sentence? VS? The hosted app?

By default, hosted apps (including ASP.NET web apps) default to `Production` and something needs to tell them that this is `Development`. What do you think that "something" should be?

One option is that we could look at the entry assembly and check to see if it was built for `Debug`, and instead default the environment to `Development`.  Thoughts @halter73 @Tratcher ?

**Comment by Tratcher** [comment]
There were debates about this 5+ years ago when the default was decided (@davidfowl @DamianEdwards ). I don't want to rehash them all here, but I can say that it's way too late/breaking to change a default this fundamental, especially one likely to affect production apps.

I recall `Debug` was already considered and rejected, that was a common patten in ASP.NET 4.x that was error prone.

**Comment by yaakov-h** [comment]
> What app is "the app" in this sentence? VS? The hosted app?
The .NET application that the user of the SDK has written and launched. I believe this is what you mean by "hosted app"?

> By default, hosted apps (including ASP.NET web apps) default to `Production` and something needs to tell them that this is `Development`. What do you think that "something" should be?

Visual Studio does set a lot of environment variables. Perhaps one of these could be used, but that would also affect (a) components of Visual Studio itself, and (b) anything launched from a VS shell panel (PowerShell or Command Prompt).

I would also consider `Debugger.IsAttached` as a decent indicator of probably-Development, but that would change behaviour between F5 and Shift+F5, for example, so that's probably not a good way to go either.

Which kind of leaves me out of ideas for simple detection.

Perhaps if we could have two launch settings files - a repo-controlled one and a user-controlled one - and the SDK generated a default repo-controlled one that set the appropriate `*_ENVIRONMENT` environment variables, that could be sufficient?

**Comment by davidfowl** [comment]
> @davidfowl Is launchSettings.json not a per-user configuration? If it's intended to be repo-controlled then how can I account for differences in developer setups e.g. directory paths?

AFAIK, it's typically checked in (it is for most of my repos). `dotnet run` also reads it so it's the way we typically set project defaults that aren't in the runtime. We're not going to change the default at runtime to Development, that was a long debate we had years ago and we decided to default to Production and made the tooling experiences generate the right content in order to get the development experience.

**Comment by eerhardt** [comment]
Closing this issue. We currently have the designed behavior at runtime. If the tooling needs to be changed to get better behavior, we can log an issue to update the tooling.
