### ISSUE TITLE
Path.GetFullPath has different behavior on macOS and Linux when passed a string of whitespace

### ISSUE THREAD

**Issue by jrdodds** [dotnet/runtime#65683]
### Description

`System.IO.Path.GetFullPath` doesn't throw an `ArgumentException` on macOS and Linux when passed a string that is composed only of space and/or tab characters. On Windows `Path.GetFullPath(" ")` will throw an `ArgumentException`. On macOS and Linux no exception is thrown and the `GetFullPath` method returns a string value that is the path of the current directory.

### Reproduction Steps

The following code can be used with .Net 6.0 to reproduce the issue.
```
var path = " ";
try
{
    Console.WriteLine($"FullPath: '{Path.GetFullPath(path)}'");
}
catch (ArgumentException ex)
{
    Console.WriteLine($"Expected exception was thrown: {ex}");
}
```
For the string `" "`, the `GetFullPath` method should throw an `ArgumentException` and the "Expected exception" message should be displayed. But this doesn't happen on macOS and Linux. Instead the "FullPath" message is displayed.

### Expected behavior

On all supported operating systems, `GetFullPath` should throw an `ArgumentException` when passed a string composed only of space and/or tab characters.

### Actual behavior

On macOS and Linux, `GetFullPath` returns a string whose value is the path of the current directory when passed a string composed only of space and/or tab characters.

### Configuration

Tested with

- .Net 6.0, Windows 10, x64
- .Net 6.0, macOS Monterey, ARM64
- .Net 6.0, macOS Big Sur, x64

### Other information

This issue was found while investigating dotnet/msbuild#6313.

**Comment by KalleOlaviNiemitalo** [comment]
> On macOS and Linux no exception is thrown and the GetFullPath method returns a string value that is the path of the current directory.

Does the returned string include the white space characters as well? I expect that it should, because Linux allows file names like that, whereas Windows APIs remove trailing spaces.

**Comment by jrdodds** [comment]
> > On macOS and Linux no exception is thrown and the GetFullPath method returns a string value that is the path of the current directory.
> 
> Does the returned string include the white space characters as well? I expect that it should, because Linux allows file names like that, whereas Windows APIs remove trailing spaces.

The white space characters are not included in the returned string.

**Comment by stephentoub** [comment]
> so perhaps the documentation needs an update.

Yes, the docs are out-of-date.
