### ISSUE TITLE
[wasm][debugger] Fix OnFrameCall for methods on variable values 

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#65707]
Reproduction code:
```
	private void IncrementCount()
	{
		string str= "ab-cd";
                int num = 12;
	}
```
Evaluate in watch:
str -> "ab-cd" [OK]
str.ToString() -> [FAIL]
num -> 12 [OK]
num.ToString() -> <not available> [FAIL]

Source of the problem:
Exception is thrown here: https://github.com/dotnet/runtime/blob/976428fa4778faa3257b9cd7d6d3ea76a43410a0/src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs#L390
because we are not setting any ID for variable values here:
https://github.com/dotnet/runtime/blob/976428fa4778faa3257b9cd7d6d3ea76a43410a0/src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs#L1888
so the rootObject looks e.g. like this:
```
{{
  "type": "string",
  "value": "ab-cd",
  "description": "ab-cd"
}}
```
We need the variable ID to get the type of evaluated variable and see what methods it has to choose right method ID.

**Comment by radical** [comment]
Some other cases where evaluation fails:
1. `int_arr.Length`
2. `myList + "Asd"` which returns
```
{
  "type": "object",
  "description": "System.Collections.Generic.List<int>",
  "className": "System.Collections.Generic.List<int>",
  "subtype": "null"
}Asd
```
  - note the `Asd` at the end too.
