### ISSUE TITLE
[Linux][Arm64] Runtime test runs doesn't seem to respect build properties

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65713]
The `JIT/Methodical/NaN/r4nanconv_il_d` and `JIT/Methodical/NaN/r4nanconv_il_r` should not run on Linux arm64 as they are disabled twice in the `issues.targets` file:
- under `Condition=" '$(RuntimeFlavor)' == 'mono' and '$(TargetArchitecture)' == 'arm64' and '$(TargetsWindows)' != 'true' "`
- under `Condition="'$(RuntimeFlavor)' == 'mono' and '$(RuntimeVariant)' == 'monointerpreter' "`

But based on https://github.com/dotnet/runtime/issues/65681#issuecomment-1047531157, they still run.

**Comment by mdh1418** [comment]
Looking at the `Wrappers.Linux.arm64.Release.binlog` (obtained from https://dev.azure.com/dnceng/public/_build/results?buildId=1625063&view=artifacts&pathAsName=false&type=publishedArtifacts in mono_monointerpreter_TestRunLogs_Linux_arm64_release_innerloop), I haven't found `r4NaNconv_il_d` under an ExcludeList, but I did find `overflow04_div` under an ExcludeList (theres only one overflow04_div in the issues.targets and its under monointerp and mono)

**Comment by EgorBo** [comment]
I assume the test was fixed via https://github.com/dotnet/runtime/issues/65681
