### ISSUE TITLE
Eliminate for loop in `UnicastIPAddressInformation`.`PrefixLengthToSubnetMask`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#65732]
https://github.com/dotnet/runtime/blob/febaf76743867b60406199daaf16a11fc8520b1c/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/UnicastIPAddressInformation.cs#L63-L82

This can be optimized by eliminating the per-byte loop.
I don't know to what extent this is a hot path, but I'd be happy to create a pull request for it sometime.

### Risks
Almost none - My simple test cases that I quickly implemented in a console application run through.
[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwHoiACAZRhlIAsMMAHAZxBIEMBrNgOgFsmieGAHc4kPEwgAbeBhi8GUtnNIAzaKV7RqASzzqovZToh4AsAChLAAQAMpawEZuAIRyrVMKE1d62UAE8Abht7J24AER02AHM8CCYMHTAmEIs7B2cAORgMNIzwnIxucggwDlzUmwAmR1DM7gAlfCTeGG4ASTw5KAgGSigAN2SYKqsLA1IACmAAlR1SAF5SWyDSBYAeUgBmarWFgGpllABKSwBvS1Jr0kH/UmkAEyXSAAVYVR0EABkYPBiMDQACoQcg4YBCDAAWTYTA4Ux0aFIAEFHo9YEwmAAxNi8HRSAKdbpeIrCaAcE5pG6kDqvVHo0ZMBzWITCNJXG4YQIc66XCzU6nWFkiF45YTvGCfH5/AHA0HgyEwuEIpH0jHY3H4wldHqk8mUnmkAC+hrAyjANGmAFEEGAYAwkqZSDAEGd+Tc+QKbk4AJxTAAkACJBihSOcnkbSABCGPOhBhl3cADiuSBAQYMCmJ24WVxMEjcATCG4UMZsXzgYN7q94iSeBwMCpNxN42pOlU0ye3BB5C5ehiWejyyFrO7oL7/yzbupnq9mT9QZDYYjQ7DI5ERsrTeuLZblkmMzmuheq3WpC2jkcezPR1IjiQbtn1zuUAeUmeywlUt+/0BPYVuRKvCiIomi6o4niBJErquRklAHAAGoPtuNJ0mBjLMqy7LVqQXIBIaT4CuuwiiiIX5fD+sr/hCgGwsBqroZiEFatBJKweSSFVtSLbUmaGAWtatr2o6eBxtOHqGoKjgLsGSDLu+kYxlGcZFsmqbppm2a5m0BaqaWmLlpuXFzrWegNihe44e2nbvmOvZQP2g5RsOwrCHZE4Dic4m8pJ3rSQGsnyY8inLOcxFGRZliWU4cm0mqGHkdKv5ymCNHQnRh4qAwHwUTKgIMQyTGagSajFQEj6GhEMDADgMTcMimJeBgUxTPYGzLNlkq5clJykAAZH10ydd+eWWu1d7VA+xnXFVNV1Q1TBNS1qhlUsyzxUVkHasSUB6vBvUEAQ0wrVta2gYVGpbaxu3sfBnFVoa5AMGweAbLMcgAHykGwjFMC4R5MssUwnVqZ0bZdLE6mxGBwRSpAAPy+dciRsOUbBSFIZSkO9MAANooAAuqQIBI6QKNoxjWM47j94EyhP0Xf9cg+AAwjI/hZth1KzbV9WNVAzXDd1srnkDDPqkzozcJRgKkAAVKQAAcXlczcJCkFaeBsMAMjYzoGBMqY1DKN9uE6G0ai9LwpAyKoGBEDQOgxJaGAQKQDnO/bmNuYaB56BgesB8sp7APr56kELSWymsocYAcBzeWGpMvusjzxsssekGQisodSKex40oxB4HpAAKRK7nNwp0YMTJAA8hmUDGE6QM4ycrUIIr9gfV9BdF9NAri4yktMLjOhp0TBDLDX9eN83eCRa23oAOykKyqHg1MQ+YiPVbRfeG+/aQYqJTLKUAelyo4xHOVR/l53gatIMEhVOE8/N/OC7fZ+ixNyGVdVXmC0lrPwCOsJk4NmJQShjdGG5IHivkgWVa6e1EL/yXtcJ6L0Ng4H9l9beTAELowbIDUqp1FjrV+lA7aME4HwQRqTcmXBKZgFILg7oNMiYkxwtSJh6NMasPYRgfGdNDQEKIVIEh3A2YwA5g9N+gCP6LQFlMSOP9xriOIVLH+CtdjyLbN0QOLMIAtBeGo0aKEU5TEgC0JEsBeC9WWDCQEkQdCDELrwGY+tjG2J2NUAeKc9CPBdCeVWyNhD6wEtYkx3RE6EV4rCag2xuFzkHr9CRJCx54GCQgeORNlhCJLGwBAGTGykFJtSGIEBXakDNItUgexSZ1OoNUEA5SeFzk0ZI0YWScl5JeIUmEJStFrAqTcKpNTml3krtcKZjg2ljOuF0zJQSXT9IKf7IpwzumjI6V6CZbtgkrRwFIPIpMjlsBOVgRZ6wOxTHsWdWwvVgCwE4GE1Jtx7hKESKUl4UwhEnAAH4tUcOeLYUxdikELPYryUK7z6I+dcayUwXDeNMIMJqXhOhMG+PrDAMhNaPGiHgROqT4mIptrCDAvzlioq1oEd45t9ZuKloXDF3gYCEuJUITEUxvnUq0QPVJlkKXfXSVo0eqyED5MpT8kZNyXmyI4IvQ0hcfp1zwASLBr0cb4N+iPF4pYtCBBhN4Gg6M+Yjy3uK7pTAB7WFXuvOKv1rWMwBnvIAA)

### Fix approach

*With a lot of help from Tanner :)*

```diff
internal static IPAddress PrefixLengthToSubnetMask(byte prefixLength, AddressFamily family)
{
! Removed lower prefixLength check - Unnecessary, because a byte cannot be smaller than 0 (only an sbyte can do that)
-     Debug.Assert((0 <= prefixLength) && (prefixLength <= 126));
-     Debug.Assert((family == AddressFamily.InterNetwork) || (family == AddressFamily.InterNetworkV6));
+     Debug.Assert(prefixLength <= 126);
+     Debug.Assert(family is AddressFamily.InterNetwork or AddressFamily.InterNetworkV6);
-     Span<byte> addressBytes = (family == AddressFamily.InterNetwork) ?
-         stackalloc byte[4] :
-         stackalloc byte[16];
-     addressBytes.Clear();
! stackalloc `uint`s instead of bytes so we don't do byte-per-byte operations
+     Span<uint> addressValues = family == AddressFamily.InterNetwork ?
+         stackalloc uint[1] :
+         stackalloc uint[4];
+     addressValues.Clear();
-     Debug.Assert(prefixLength <= (addressBytes.Length * 8));
-     Debug.Assert(prefixLength <= addressValues.Length * 32);
-     // Enable bits one at a time from left/high to right/low.
-     for (int bit = 0; bit < prefixLength; bit++)
!      implicit conversion from byte to int
+     int bitCount = prefixLength;
+     var (count, rem) = Math.DivRem(bitCount, 32);
+     var index = 0;
+ 
+     switch (count)
-         addressBytes[bit / 8] |= (byte)(0x80 >> (bit % 8)); 
+         case 3:
+             addressValues[index++] = uint.MaxValue; 
+             goto case 2;
+         case 2: 
+             addressValues[index++] = uint.MaxValue; 
+             goto case 1;
+         case 1: 
+             addressValues[index++] = uint.MaxValue; 
+             goto default;
+         default:
+             if (rem == 0) break;
+ 
+             var lastValue = (uint)~((1 << (32 - rem)) - 1);
+ 
+             if (BitConverter.IsLittleEndian)
+             {
+                 lastValue = BinaryPrimitives.ReverseEndianness(lastValue);
+             }
+ 
+             addressValues[index] = lastValue;
+             break;
+     ReadOnlySpan<byte> addressBytes = MemoryMarshal.AsBytes(addressValues);
}
```

/cc @tannergooding 
/area: System.Net

**Comment by stephentoub** [comment]
> I don't know to what extent this is a hot path

It is not.

**Comment by wfurt** [comment]
Would we still possibly take the fix @stephentoub or do we prefer the simplicity for maintenance?

**Comment by wfurt** [comment]
closing for now. We can re-visit if needed.
