### ISSUE TITLE
[wasm][debugger] Assertion caused by invalid array id being used

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65742]
This can be seen in `DebuggerTests.ArrayTests.InvalidArrayId`, which gets an assertion:

`console.error: * Assertion at /workspaces/runtime/src/mono/mono/metadata/class.c:4580, condition `<disabled>' not met`

```c
mono_array_element_size (MonoClass *ac)
{
        g_assert (m_class_get_rank (ac));
```

We should validate validate whether a given object is an array or not, before calling into these functions.

**Comment by radical** [comment]
cc @thaystg

**Comment by lewing** [comment]
is this still an issue?
