### ISSUE TITLE
Corefx internal PRs should use non '.Open' queues

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#65741]
It appears that the corefx dependency flow PRs for internal/release/3.1 are attempting to use the open Helix queues, which doesn't work. When running on the internal project, the `.Open` suffix on the Helix queues should be dropped.

**Comment by mmitche** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
Fixed by https://github.com/dotnet/corefx/pull/43135
