### ISSUE TITLE
Consider removing apiset files from self-contained apps

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#65758]
We do not include apiset files in singlefile apps and it is questionable why non-singlefile apps should be different.

Also see:
https://github.com/dotnet/runtime/pull/63196
https://github.com/dotnet/runtime/discussions/65692

**Comment by VSadov** [comment]
My initial, naive, attempt to omit these files has run into some technical troubles (manifest validation, etc), but there should certainly be a way to not include these files cleanly, either based on RID (i.e. for Win10+), or better unconditionally.

**Comment by Symbai** [comment]
Why only on self-contained? From the linked #65692 issue it's been said that they are only required for Windows 7. So if the project targets an OS > Win7 they should also get removed, no?

**Comment by huoyaoyuan** [comment]
A question: when I use `dumpbin /imports` to view compiled coreclr.dll, I see references to the api sets in Release configuration, but not in Debug configuration. Is there anything to do with C++ compiler or linker?
