### ISSUE TITLE
ZipArchive corrupts files with unicode characters

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#65750]
### Description

Discovered this as part of a SDK upgrade in the dotnet/aspnetcore repo. AspNetCore has test assets with unicode chars that get bundled up by Helix:

* https://github.com/dotnet/aspnetcore/tree/main/src/Middleware/StaticFiles/test/UnitTests/SubFolder/%E4%BD%A0%E5%A5%BD/%E4%B8%96%E7%95%8C
* https://github.com/dotnet/arcade/blob/dd1e882f0945121bd0786b4894073db2bd45274c/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs#L53-L68

Updating to the latest SDK causes the folder to be corrupted and our tests to fail:

![image](https://user-images.githubusercontent.com/174281/155240904-bd0d46bb-0644-4cff-8c12-aabf779eb277.png)

### Reproduction Steps

Run this app using the latest runtime: https://github.com/pranavkm/zip-file

### Expected behavior

Archive should preserve unicode characters 

### Actual behavior

They are garbled

### Regression?

Regression from 7.0-preview2 runtime

**Comment by pranavkm** [comment]
@carlossanlop perhaps this is related to your recent change: https://github.com/dotnet/runtime/pull/59442/files

**Comment by carlossanlop** [comment]
The entry name encoding may be changed if the comment encoding changes, and viceversa. Per the zip spec, this is the expected behavior, but the change I introduced could've also introduced a bug.

Do you know if the entry was added with a comment?

Tagging  @dotnet/area-system-io-compression for awareness.

**Comment by dougbu** [comment]
> Do you know if the entry was added with a comment?

The Helix SDK uses `ZipArchive.ZipArchive(...)` w/ a `MemoryStream` and adds files using `ZipArchive.CreateEntryFromFile(...)`. See https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/JobSender/Payloads/DirectoryPayload.cs

**Comment by pranavkm** [comment]
Ping @carlossanlop have you had a chance to look at this as yet? If not, are you open to rolling back your earlier change since it blocks SDK ingestion in to AspNetCore?

**Comment by TanayParikh** [comment]
Re-opening the issue per discussion in https://github.com/dotnet/aspnetcore/pull/40353#issuecomment-1064369745.

cc/ @carlossanlop, @Jozkee

**Comment by TanayParikh** [comment]
cross-linking: https://github.com/dotnet/aspnetcore/issues/40642

**Comment by Jozkee** [comment]
@TanayParikh @wtgodbe were your issues related to our zip changes after all? do they need to be addressed by the libraries team?

**Comment by wtgodbe** [comment]
We're all good, we just needed an SDK update to get things aligned.
