### ISSUE TITLE
[API Proposal]: DependencyRootEntryAttribute

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#65764]
### Background and motivation

In AOT compilation scenario, we often have to deal with runtime directives to root types and methods we used in a dynamic form. It can be a non-trivial work specially when we use AOT against some libraries heavily rely on reflection (let's just say `MakeGenericType` and `MakeGenericMethod`). 
The compiler cannot analyze those dependencies statically, and illink annotation is not sufficient for scenarios like creating a new type B based on all members of an existing type A, while the type `A` and `B` doesn't come from the same assembly.

For example, in EFCore we have a type `Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot<...>` which basically takes a DTO class as input and use its property types as generic arguments.

It means that if a class like

```csharp
class Foo
{
    public int Id { get; set; }
    public DateTime Time { get; set; }
    public string Message { get; set; }
}
```

serves as a `DbSet<>` generic argument in a `DbContext`, a `Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot<int, DateTime, string>` type will be created at runtime.

We do can generate the class using Source Generator, but that would drop the useability from languages other than C#.

### API Proposal

```C#
namespace System.Diagnostics.CodeAnalysis
{
    [System.AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    public class DependencyRootEntryAttribute : System.Attribute { }
}
```

### API Usage

Like the module initializer, a static method annotated with `DependencyRootEntry` will be called by an AOT compiler or ILLinker during dependency analysis phrase. The method takes all assemblies need to be compiled and the dependency root context to root additional types and methods. Each assembly should only contain a single method which is annotated with `DependencyRootEntry`.

```C#
[DependencyRootEntry]
static void RootDependencies(IEnumerable<Assembly> assemblies, DependencyRootContext context)
{
    foreach (var type in assemblies.SelectMany(i => i.GetTypes()).Where(i => i.IsAssignableTo(typeof(DbContext))))
    {
        var types = type.GetProperties().Where(i => i.PropertyType.IsGenericType && i.PropertyType.GetGenericTypeDefinition() == typeof(DbSet<>)).Select(i => i.PropertyType.GetGenericTypeArguments()[0]);
        foreach (var t in types)
        {
            var snapshotType = typeof(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.Snapshot<...>).MakeGenericType(t.GetProperties().Select(i => i.PropertyType));
            context.RootType(snapshotType); // root a type
            var method = .....MakeGenericMethod(...);
            context.RootMethod(method); // root a method
        }
    }
}
```

Additionally, we may add overloads to `RootType` and `RootMethod` to allow conditional dependencies, for example:

```csharp
context.RootType(type: x, dependsOnType: y); // only root type x if type y is preserved in the dependency graph
context.RootMethod(method: x, dependesOnType: y); // only root method x if type y is preserved in the dependency graph
// ...
```

In this way library authors can write their own `DependencyRootEntry` methods to root dynamic dependencies, and developers can use those libraries in AOT scenario out-of-box without needs of writing a `rd.xml`.

### Alternative Designs

Extend the illink annotation to allow doing things like static reflection (which means that a new DSL may be needed)

cc: @MichalStrehovsky

**Comment by jkotas** [comment]
> Alternative Designs

Write a tool that generates the dependency definitions in a separate assembly and then feed this assembly as an input into IL linker. This tool can still use C# or other language of your choice without forcing it onto your application.

I do not think we want to be running code in libraries that are getting compiled from the AOT compiler. It would open a large can of worms with versioning and object models to expose to these plugins.

**Comment by MichalStrehovsky** [comment]
We've been trying to do trimming in a way where trim safety can be proved at trimming/compile time. Rooting things is easy - the hard part is connecting reflection code patterns with things that got rooted elsewhere. Trimming generates warnings for reflection patterns that cannot be reasoned about, so a solution that only roots things, but doesn't make it possible to analyze, will require suppressing such warnings. Any disconnect between the rooting logic and the suppressed reflection logic will turn into trimming bugs. I would be weary of introducing it as a core component of trimming.

Even if we were to add this to trimming, we wouldn't be able to run this user code in-process with trimming, because the runtime/framework libraries the trimming is running with doesn't necessarily match the version of the runtime/framework that the app will work with at runtime (leading to seeing types/members that might not exist at runtime).

It would be possible to build this as a separate tool that runs the code and generates ILLink.Descriptors.xml or RD.XML.

**Comment by vitek-karas** [comment]
If you decide to generate the "rooting" via a separate tool, please consider writing the information in IL form. While both `ILLink.Descriptors.xml` or `RD.XML` would work in this case, they're not standards in any way, and other tools may not understand them. IL is a standard and understood by everything in the pipeline.

The challenges which @MichalStrehovsky pointed out where the roots themselves only solve half of the problem (they mostly make the app work, but they don't make it verifiably work) have potential solutions. 
For example if the generated code which roots the necessary bits is also used at runtime to access those bits, then the problem goes away. It's the typical selling point for source generators - it would avoid reflection at runtime (slow) and solves the trimming/AOT problem (no need for `MakeGenericType`, you can generate the right `typeof(Generic<Args>)` and use it at runtime) and allows AOT better optimizations potentially.

**Comment by steveharter** [comment]
Closing based on:
>  It would open a large can of worms with versioning and object models to expose to these plugins.

> Any disconnect between the rooting logic and the suppressed reflection logic will turn into trimming bugs. I would be weary of introducing it as a core component of trimming.

> If you decide to generate the "rooting" via a separate tool, please consider writing the information in IL form

> [proposed alternative approach] Write a tool that generates the dependency definitions and other types that would be generated by the reflection-heavy library at runtime in a separate assembly and then feed this assembly as an input into IL linker or AOT compiler.
