### ISSUE TITLE
relation of CancellationTokenSource.TryReset and Dispose

### ISSUE THREAD

**Issue by freddyrios** [dotnet/runtime#65765]
I could not see any information about the relation of CancellationTokenSource.TryReset in [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.tryreset?view=net-6.0#:~:text=TryReset%28%29%20is%20intended%20to%20be%20used%20by%20the,completed.%20No-one%20else%20will%20attempt%20to%20cancel%20it), or in the [original issue](https://github.com/dotnet/runtime/issues/48492) as well as [the PR](https://github.com/dotnet/runtime/pull/50346)

From the original issue it seems the suggested usage pattern when using it with CancelAfter is:
```
cts.CancelAfter(TimeSpan.FromSeconds(10));
//operation goes here
if (!cts.TryReset())
  cts = new CancellationTokenSource(); //as we could not reset we discard the old CTS, and create a new one
```

Is it safe to assume that Dispose is not called in the old cts? or should one be using something like this:

```
cts.CancelAfter(TimeSpan.FromSeconds(10));
//operation goes here
if (!cts.TryReset())
{
  cts.Dispose();
  cts = new CancellationTokenSource(); //as we could not reset we discard the old CTS, and create a new one
}
```

**Comment by stephentoub** [comment]
TryReset does not call Dispose. What you do in response to it returning false is up to you. That can include calling Dispose if you know you're done with it.
