### ISSUE TITLE
Repeatedly initialize the static variables s_defaultSimpleConverters and s_defaultFactoryConverters when calling the method GetConverter of JsonSerializerOptions

### ISSUE THREAD

**Issue by dczuo** [dotnet/runtime#65770]
### Description

https://github.com/dotnet/runtime/blob/a1a653c7217706fcb820914d65126234bc2447a8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L162

https://github.com/dotnet/runtime/blob/a1a653c7217706fcb820914d65126234bc2447a8/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Converters.cs#L27

### Reproduction Steps

According to the referenced code

### Expected behavior

Variables s_defaultSimpleConverters and s_defaultFactoryConverters are initialized only once

### Actual behavior

Variables s_defaultSimpleConverters and s_defaultFactoryConverters are repeatedly initialized with each call

**Comment by eiriktsarpalis** [comment]
Good catch, thanks. It should be possible to fix the issue by adding a null check in the RootBuiltInConverters method. Would you be interested in contributing a PR?

**Comment by EgorBo** [comment]
Seems to be introduced in https://github.com/dotnet/runtime/pull/57327/files#r688365200
