### ISSUE TITLE
Use Fast-Mod algorithm for native EEHashTableBase

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#65778]
When I profile this simple virtual generic callsite:
```csharp
public class Prog
{
    static void InvokeVGM(Prog p)
    {
        while (true)
            p.VGM<string>();
    }

    virtual void VGM<T>() {}
}
```
in VTune I see `div` as the most expensive part (if I read it correctly):
![image](https://user-images.githubusercontent.com/523221/155349016-d2e555ca-a37a-4a25-8dc7-ee446f9a1410.png)
It turns out to be a EEHashTable lookup:
![image](https://user-images.githubusercontent.com/523221/155347927-8c986e12-63a4-471f-a873-42b3528010f8.png)

And It does make sense since div is a very expensive operation, on some CPU its latency can be bigger than 100 cycles. On my Coffee Lake it's 26/6 while e.g. mul is 3/1 (Latency/rec.trput)

The managed Dictionary was optimized with ["Fast Mod" algorithm](https://lemire.me/blog/2019/02/08/faster-remainders-when-the-divisor-is-a-constant-beating-compilers-and-libdivide/) where we pre-calculate a special multiplier every time a new bucket is added and then can avoid expensive idiv operation by using mul see https://github.com/dotnet/coreclr/pull/27299 and https://github.com/dotnet/runtime/pull/406

Quick demo:
```csharp
public static uint Test(uint x)
{
    uint result = 0;

    ulong cachedMul = GetFastModMultiplier(y);
    for (int i = 0; i < x; i++)
    {
        // result = i % x;
        result = FastMod(i, x, cachedMul);
    }
    return result;
}

public static ulong GetFastModMultiplier(uint divisor) =>
    ulong.MaxValue / divisor + 1;

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static uint FastMod(uint value, uint divisor, ulong multiplier) => 
    (uint)(((((multiplier * value) >> 32) + 1) * divisor) >> 32);
```

NOTE: the algorithm adds an overhead on dictionary expansion
NOTE2: `CompareKeys` is not inlined

**Comment by EgorBo** [comment]
cc @VSadov

**Comment by bartonjs** [comment]
If the number of buckets is a power of 2 then mod is just a masking operation. (Though depending on the distribution of `dwHash` values it may create overweighted buckets)

**Comment by EgorBo** [comment]
I applied the FastMod locally and got 22% improvement for the benchmark

**Comment by VSadov** [comment]
Using FastMod could be an easy way to speed up EEHashTableBase. A few thoughts:

- FastMod has two components - divisor and multiplier. They must match thus needing a bit more care regarding races. Storing multiplier in the table, the same way we store length, could be sufficient.

- Are we sure the real problem is not collisions? 
Sometimes excessive hashing expenses is what we see, but the real problem is collisions.

- Whether EEHashTableBase is a good choice for caching is another good question. 
 If scenario that we have here is similar to the type casting cache (i.e. the values can be relatively cheaply recomputed), then a solution similar to cast cache could fit better.

**Comment by EgorBo** [comment]
Prototype: https://github.com/EgorBo/runtime-1/commit/c99fe023bfd079b78af5abc68eb253c49321b7b7

the only problem that it assumes `NumBuckets` fits into 32bit (pretty normal) and `dwHash` (not normal, I guess in many cases its value going to be distributed accross all 64 bits, but it works for my benchmark) - I assume the FastMod can be implemented for 64bit integers too via int128 but not sure it will be a perf win.

```csharp
public class P
{
    [Benchmark]
    public void CallVGM()
    {
        VGM<string>();
    }

    protected virtual void VGM<T>()
    {
    }

    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(P).Assembly).Run(args);
}
```


|   Method |                 Toolchain |      Mean |     Error |    StdDev | Ratio |
|--------- |-------------------------- |----------:|----------:|----------:|------:|
|  CallVGM |    \Core_Root\corerun.exe |  5.267 ns | 0.1216 ns | 0.1301 ns |  1.00 |
|  CallVGM | \Core_Root_PR\corerun.exe |  4.452 ns | 0.0342 ns | 0.0319 ns |  0.85 |

> then a solution similar to cast cache could fit better. 

I agree but that sounds like a more invasive change, while FastMod could also improve other EEHashTable users?
