### ISSUE TITLE
System.Data.SqlClient unloadability

### ISSUE THREAD

**Issue by GabrieleGervasiPEL** [dotnet/runtime#65781]
### Description

Unable to unload AssemblyLoadContext after creating a System.Data.SqlClient.SqlConnection

### Reproduction Steps

1. Take the unloading solution from https://github.com/dotnet/samples/tree/main/core/tutorials/Unloading
2. Upgrade the solution targeting Net6.0
3. Add EnableDynamicLoading at true in Plugin.csproj
4. Add nuget reference to System.Data.SqlClient 4.8.3 in Plugin project
5. In PluginClass constructor add: using var connection = new System.Data.SqlClient.SqlConnection();

All those steps are already implemented in zipped project

[Unloading_SystemDataSqlClient.zip](https://github.com/dotnet/runtime/files/8125735/Unloading_SystemDataSqlClient.zip)

### Expected behavior

Plugin should unload

### Actual behavior

Doesn't unload

### Configuration

Net 6.0
Windows 10
x64

### Other information
Could be connected to #65780

**Comment by Wraith2** [comment]
The System version of SqlClient is in support mode with Microsoft.Data.SqlClient as the replacement. The System version will not correctly support unloading but the Microsoft version may, I've done some work to make it understand ALC unload though more may be required if new scenarios are hit.

Modern versions of EF Core use Microsoft.Data.SqlClient, are you sure you're getting the System version dependency from EF Core.

**Comment by GabrieleGervasiPEL** [comment]
When we choosed to continue with System.Data.SqlClient, Microsoft.Data.SqlClient wasn't ready at all and missed some functions. We'll give it a try.
