### ISSUE TITLE
[API Proposal]: QUIC should have an IsSupported API

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#65802]
### Background and motivation

There is an `SocketsHttpHandler.IsSupported` property. That avoids using the handler on platforms where everything throws PNSE. System.Net.Quic should have a similar property.

An extra complication is QUIC has operating system (Win11+), configuration (TLS 1.3 is enabled), and component requirements (additional Linux deps). I'm not sure whether they should be covered by the same property or a different one.

e.g.
```csharp
public static bool IsSupported { get; }

// I wonder if there is a way to have an API that gives a message about what QUIC requirement is missing
public static bool HasRequirements { get; }
```

Related issues:
* https://github.com/dotnet/runtime/issues/56005
* https://github.com/dotnet/runtime/issues/55237

### API Proposal

```C#
namespace System.Net.Quic
{
    public class QuicConnection
    {
        public static bool IsSupported { get; }
    }
}
```

### API Usage

```C#
if (QuicConnection.IsSupported)
{
    // use QUIC
}
else
{
    // use socket
}
```

**Comment by vcsjones** [comment]
> I'm not sure whether they should be covered by the same property or a different one.

For what it's worth, in the crypto APIs like `ChaCha20Poly1305`, we have an `IsSupported` that covers both platform support and dependencies.

**Comment by ManickaP** [comment]
Example of how to exclude some members from auto-generated PNSE: https://github.com/dotnet/runtime/commit/cd4157f9024f1cc5c47c4e894842d3e0543f943f

**Comment by wfurt** [comment]
Triage: looks reasonable. We may need some infrastructure changes for mobile platforms.

**Comment by JamesNK** [comment]
Might be broken - https://github.com/dotnet/aspnetcore/issues/41042. Will double-check in ASP.NET Core.
