### ISSUE TITLE
DateTimeFormat for the en-AU CultureInfo is incorrect on .NET 5 + 6

### ISSUE THREAD

**Issue by Jetski5822** [dotnet/runtime#65824]
### Description

Per the title, the patterns seem incorrect. ShortDatePattern is notably wrong and causes my code to parse dates incorrectly.

### Reproduction Steps

.NET 5.0/6.0
```
System.Globalization.CultureInfo.GetCultureInfo("en-AU").DateTimeFormat.ShortDatePattern
d/M/yyyy
```

.NET 4.7.2
```
System.Globalization.CultureInfo.GetCultureInfo("en-AU").DateTimeFormat.ShortDatePattern
d/MM/yyyy
```

### Expected behavior

Expecting: d/MM/yyyy

### Actual behavior

Actual: d/M/yyyy

### Configuration

Windows 10, x64.

Also tested in dotnetfiddle.

**Comment by Jetski5822** [comment]
![image](https://user-images.githubusercontent.com/619530/155449390-dc8c3263-a82b-41e1-b659-2c37eef50add.png)

Inconsistent between a Windows and a Mac too

**Comment by tarekgh** [comment]
.NET 5.0 started to use globalization ICU library instead of legacy Windows NLS APIs. ICU picks the data from CLDR Unicode standard. You can see .NET 5/6are returning the [correct data](https://github.com/unicode-org/cldr/blob/7de60bb8e23cfc3e6129919f9e823c5b13ba8552/common/main/en_AU.xml#L2074). If you disagree with that, please consider [opening a CLDR ticket](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/boards/12). 

If you want to learn more about the change, we did during .NET 5.0, please have a lock at the [doc](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) which mention how to get back to the old behavior too. Note, we don't recommend going back to old behavior as this will cause inconsistency and will lose other features.

**Comment by tarekgh** [comment]
> The change in behaviour is understandable, but I can't work out why on windows CreateSpecificCulture("en-AU") returns different data to GetCultureInfo("en-AU") (and, arguably based on the intended CLDR culture info, CreateSpecificCulture is wrong.)

When creating any culture on Windows, you decide if you want to pick the user override settings or want to get only the built-in data for such culture. Please have a look at the [remark section of CreateSpecificCulture API](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.createspecificculture?view=net-6.0#remarks). 

```
If the culture identifier of the specific culture returned by this method matches the culture identifier of the current Windows culture, this method creates a [CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0) object that uses the Windows culture overrides. The overrides include user settings for the properties of the [DateTimeFormatInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo?view=net-6.0) object returned by the [DateTimeFormat](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.datetimeformat?view=net-6.0) property and the [NumberFormatInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-6.0) object returned by the [NumberFormat](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.numberformat?view=net-6.0) property. To instantiate a [CultureInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0) object that with default culture settings rather than user overrides, call the [CultureInfo(String, Boolean)](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.-ctor?view=net-6.0#system-globalization-cultureinfo-ctor(system-string-system-boolean)) constructor with a value of false for the useUserOverride argument.
```

While the doc of the [GetCultureInfo API](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.getcultureinfo?view=net-6.0) states the following:

```
If name or altName is the name of the current culture, the returned objects do not reflect any user overrides. If name is [String.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=net-6.0), the method returns the invariant culture. This is equivalent to retrieving the value of the [InvariantCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-6.0) property. If altName is [String.Empty](https://docs.microsoft.com/en-us/dotnet/api/system.string.empty?view=net-6.0), the method uses the writing system and comparison rules specified by the invariant culture.
```

In your case, looks you have setting `en-AU` as default culture and the user settings is using a different pattern for the short date. That is why `CreateSpecificCulture` picked this user setting and different than what `GetCultureInfo` returns. You have full control here to do whatever satisfies your scenario.
