### ISSUE TITLE
[ARM/Linux] Make indirect calls to direct calls if possible

### ISSUE THREAD

**Issue by wateret** [dotnet/runtime#6582]
In this issue I'd define direct/indirect call as jump to pc-relative immediate address/jump to an absolute address from a register.

**Direct**

```
bl imm24
```

**Indirect**

```
movw reg, imm16
movt reg, imm16
blx reg
```

On ARM32, it seems like indirect calls are generated for almost all cases even if the caller and callee address are close enough to fit in imm24. `CEEJitInfo::getRelocTypeHint()` always returns _no-hint_ which results in an indirect call.

I'd like to calculate the relative address between the address of current instruction and the target address then we are able to decide whether to use direct or indirect. However it doesn't look like we are able to know the address of current instruction at the time cause it is before generating actual instructions. Is there some ways to handle this?

/cc @dotnet/jit-contrib @hqueue

category:cq
theme:emitter
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
I'm going to close this in favor of https://github.com/dotnet/runtime/issues/10790.
