### ISSUE TITLE
Call stack incomplete on Linux in .NET 7 preview 1

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#65822]
### Description

.NET 7 preview 1 has a call stack regression on Linux when unwinding from `Thread.Sleep` (and I would guess other functions that call native code)

### Reproduction Steps

1. Create a new .NET 7 Console app on Linux
2. Add the following code
```C#
while (true)
{
    Thread.Sleep(100);
}
```
3. Run it under a debugger
4. Hit pause
5. Look at the call stack

### Expected behavior

Call stack should have:

```
System.Private.CoreLib.dll!System.Threading.Thread.Sleep(int millisecondsTimeout)
MyTargetApp.dll!Main
<Possibly more frames>
```

### Actual behavior

```
System.Private.CoreLib.dll!System.Threading.Thread.Sleep(int millisecondsTimeout)
[Native to Managed Transition]
```

### Regression?

Regression from .NET 6

### Configuration

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64

Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c

.NET SDKs installed:
  7.0.100-preview.1.22110.4

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.1.22109.13
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8

This issue doesn't repro on Windows or OSX x64. I didn't try ARM/ARM64.

**Comment by gregg-miskelly** [comment]
CC @tommcdon

**Comment by tommcdon** [comment]
@hoyosjs @mikem8361

**Comment by gregg-miskelly** [comment]
FYI This issue went away in .NET 7 preview 2, but came back in preview 3

**Comment by mikem8361** [comment]
I can't repro with latest 7.0 main (basically what will be preview 7) on vscode/WSL Ubuntu 20.04.

```
System.Private.CoreLib.dll!System.Threading.Thread.Sleep(int millisecondsTimeout) Line 360 (\home\mikem\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Thread.cs:360)
simplestack.dll!singlefile.Program.Main(string[] args) Line 11 (\mnt\c\Users\mikem\wsl2\builds\simplestack\Program.cs:11)
[Native to Managed Transition] (Unknown Source:0)
```

**Comment by gregg-miskelly** [comment]
I am not seeing it in current builds either. Closing for now.
