### ISSUE TITLE
.NET Core application fails to find CA cert on Linux even after putting the certificates in ca cert store of openssl

### ISSUE THREAD

**Issue by ramsubbaraoc** [dotnet/runtime#65851]
.NET Core applications fail with "RemoteCertificateNameMismatch, RemoteCertificateChainErrors" on linux even after copying the CA certificates to "/etc/pki/ca-trust/source/anchors" and then running "update-ca-trust"

**Comment by vcsjones** [comment]
This is going to vary from Linux distribution to distribution, but given the presence of "update-ca-trust", I assume this is something RedHat-like like CentOS or Rockylinux.

Using Rockylinux, I was unable to reproduce this. Can you share more about the Linux distribution you are using?

Also, can `openssl` verify the certificate? You should be able to run the command `openssl verify /path/to/certificate/leaf.crt`. If it can validate the certificate, it will print something like `leaf.crt: OK`. If OpenSSL can't validate the certificate, then .NET won't likely be able to do it either.

Here are the exact files I used to test this:

```dockerfile
FROM rockylinux:8.5

# Install openssl to make our fake CA.
# Install findutils because the .NET setup script requires it.
# Install libicu because .NET has a dependency on it.
RUN yum install -y openssl findutils libicu
RUN mkdir /project /opt/dotnet
WORKDIR /project

# Make a "CA"
RUN openssl req -x509 -out root.crt -keyout root.key -nodes -subj "/CN=Root CA"

# Create a CSR
RUN openssl req -new -keyout leaf.key -nodes -subj "/CN=Leaf" -out leaf.req

# Sign the CSR with the CA
RUN openssl x509 -req -in leaf.req -CA root.crt -CAkey root.key -set_serial 1 -out leaf.crt && rm leaf.req

# Install the root to the trust anchor directory and add to trust bundle.
RUN cp root.crt /etc/pki/ca-trust/source/anchors/root.crt && \
    update-ca-trust

# Download .NET setup script and run
RUN curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh -c Current --install-dir /opt/dotnet && \
    ln -s /opt/dotnet/dotnet /usr/bin/dotnet

COPY Program.cs Program.csproj ./

RUN dotnet build
CMD dotnet run
```

And for the .NET program I used:


```C#
// Program.cs
using System;
using System.Security.Cryptography.X509Certificates;

using X509Certificate2 cert = new X509Certificate2("leaf.crt");
using X509Chain chain = new X509Chain();
chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
bool result = chain.Build(cert);

Console.WriteLine($"chain.Build: {result}");

foreach (X509ChainElement element in chain.ChainElements)
{
    Console.WriteLine(element.Certificate.Subject);

    foreach (var status in element.ChainElementStatus)
    {
        Console.WriteLine(status.Status.ToString());
    }

    Console.WriteLine(new string('-', 30));
}
```

```xml
<!-- Program.csproj --> 
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
    </PropertyGroup>
</Project>
```

Next, build the docker image: `docker build -t dotnet-chain-test .`. And finally, run the container with `docker run dotnet-chain-test` produces the output:

<pre>
chain.Build: True
CN=Leaf
------------------------------
CN=Root CA
------------------------------
</pre>

**Comment by vcsjones** [comment]
> RemoteCertificateNameMismatch

I missed this on my first read through of the issue. In this error, you are using a certificate for HTTPS (likely) but the name on the certificate does not match the host.

The certificate needs a DNS Subject Alternative Name or Common Name that matches the host. For example, if the host name is `https://foo.internal`, then the certificate needs that in the SAN or the Common Name. Adding the certificate to the trust store does not bypass that.

**Comment by ramsubbaraoc** [comment]
@vcsjones Thanks for responding. I am running the test on RHEL 8.2. The same certificates work on Windows,but fails on Linux and when i did a `openssl verify`  it returned me
```
 error 18 at 0 depth lookup: self signed certificate
error myCAcertfile.pem: verification failed

```

All the while i was thinking i had created a CA cert but looks like not, but even if i put the certificate in the "MY" store it fails with the same error.

**Comment by bartonjs** [comment]
The "My" store doesn't convey any trust, nor does the "CA" store (StoreName.CertificateAuthority) (which is for intermediate CAs).

For user-specific trust, you'd need to use CurrentUser\Root.

Does the root you created have the Basic Constraints extension with CA:true set?  How'd you make it?

**Comment by ramsubbaraoc** [comment]
@bartonjs @vcsjones Thank you very much. After creating the CA cert with basic constraints CA:true, the application started working.
