### ISSUE TITLE
decimal.Equals, Guid.Equals could be improved

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6588]
While looking through some of the 16-byte types today I noticed that some of the `Equals` implementations are quite suboptimal... for example [Guid.Equals](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Guid.cs#L969) has a bunch of `return falses` that the JIT does not merge in the assembly. What's more, it compares ints/shorts at a time when it should ideally be able to compare the whole struct in a couple of instructions.

Same for `Decimal`... in Equals we should be able to just compare the 16 bytes and return true early before doing [all these expensive bit operations](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/palrt/decarith.cpp#L1175).

**Comment by stephentoub** [comment]
Closing as non-actionable.
