### ISSUE TITLE
[wasm] Interpreter: Local variable of function pointer type emits a warning `Test.Prepare: Store local stack type mismatch 0 7`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65881]
Warning `Test.Prepare: Store local stack type mismatch 0 7` from https://github.com/dotnet/runtime/blob/30f30a3e5b6be09eacf7ea4cf054576753ed99ca/src/mono/mono/mini/interp/transform.c#L1073-L1075

1. Put this code in `src/mono/sample/wasm/console-v8-cjs/Program.cs`

```csharp
using System;
using System.Threading.Tasks;

public class Test
{
    public static async Task<int> Main(string[] args)
    {
        await Task.Delay(1);
        Prepare();
        return 0;
    }

    public unsafe static int Prepare()
    {
        delegate*<int> value = &Prepare;
        Console.WriteLine ($"value is {value == null}");
        return 5;
    }
}
```

2. build: `make build MSBUILD_ARGS="-p:TreatWarningsAsErrors=false"`
3. make run

Output:
```
console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[MONO] Test.Prepare: Store local stack type mismatch 0 7
value is False
```

IIUC, https://github.com/dotnet/runtime/blob/30f30a3e5b6be09eacf7ea4cf054576753ed99ca/src/mono/mono/mini/interp/transform.c#L943-L951

.. this needs to map `STACK_TYPE_F` to `STACK_TYPE_I` too.

cc @lambdageek @BrzVlad

**Comment by lewing** [comment]
cc @SamMonoRT

**Comment by radical** [comment]
I made that a `g_error` only to catch any places that might break, or have a warning. And that did fail in a runtime test - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65917-merge-5dd64c2e0e4841a3b8/JIT.Regression.CLR-x86-JIT.V1-M12-M13/1/console.dece4869.log?sv=2019-07-07&se=2022-03-18T10%3A59%3A19Z&sr=c&sp=rl&sig=dKxystVzZsraXvMdU%2FMMp%2FwCzLZ3SceToAOSnbTHOdE%3D
