### ISSUE TITLE
Microsoft.Extensions.Configuration needs to have its ref file regenerated

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#65913]
In the Preview1 [api-diff PR](https://github.com/dotnet/core/pull/7211/files#r810056867) in dotnet/core, we found that ref file was malformed: the return values of some of the members of `ConfigurationManager` do not have the proper API full name formed.

The ask is to run `dotnet build /t:GenerateReferenceSource` under the Microsoft.Extensions.Configuration folder to regenerate the ref file automatically and the fullnames are added properly.

https://github.com/dotnet/runtime/blob/6033ef2c56db79e68e13f2856f42d250399d927e/src/libraries/Microsoft.Extensions.Configuration/ref/Microsoft.Extensions.Configuration.cs#L32-L45

**Comment by maryamariyan** [comment]
cc @ViktorHofer with your work with ref files would this still need to happen?

**Comment by ViktorHofer** [comment]
Depends on timing as I don't know when my change will be ready. I recommend to meanwhile fix this.
