### ISSUE TITLE
Review workaround for Named mutex: Use flock instead of pthread process-shared mutex

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#65929]
[Cleanup Issue-URLs in Code · Issue #63902 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63902) identified a workaround in place from 2016 and it's unclear if the backing issue that necessitated the workaround has been resolved.

- The original issue was: [[ARM/Linux] paltest_namedmutex_test1 hangs · Issue #6014 · dotnet/runtime](https://github.com/dotnet/runtime/issues/6014)
- The PR that applied the workaround was: [Named mutex: Use flock instead of pthread process-shared mutex in som… by kouvel · Pull Request #6015 · dotnet/coreclr](https://github.com/dotnet/coreclr/pull/6015)

https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/coreclr/pal/src/include/pal/mutex.hpp#L123-L128

The workaround should be evaluated to determine if it's still necessary. With the findings, we should either update the code to remove the workaround, or the code comment to reference an open issue for tracking when we can remove the workaround.

/cc @deeprobin

**Comment by janvorli** [comment]
It looks like the issue in glibc causing the was fixed in version 2.24, our minimum supported version for arm/arm64 is now larger than that. So we can remove the workaround now.
