### ISSUE TITLE
[API Proposal]: Add overload of ToDictionary that turns an IEnumerable of KeyValuePair or ValueTuple

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#65925]
### Background and motivation

Sometimes in parsing it's common transform key value pairs expressed as text into a dictionary pretty concise LINQ statement: Consider a query string parser (a=b&c=d&e=f).

```C#
Dictionary<string, string> Parse(string query) =>
    query.Split('&')
    .Select<string, (string k, string v)?>(s => s.Split('=') switch // This part is gross 😢 
    {
        [var k, var v] => (k, v),
        _ => null,
    })
    .Where(p => p is not null)
    .Select(p => p!.Value)
    .ToDictionary(p => p.k!, p => p.v!);
```

The last ToDictionary call wouldn't require explicitly mapping the key and value for this common case.

### API Proposal

```C#
namespace System.Collections.Generic;

public static partial class Enumerable
{
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<KeyValuePair<TKey, TValue>> source) where TKey : notnull;
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<ValueTuple<TKey, TValue>> source) 
where TKey : notnull;
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<ValueTuple<TKey, TValue>> source, IEqualityComparer<TKey> comparer) where TKey : notnull;
}

```

### API Usage

```C#
// Fancy the value
var c = new List<(string, int)>();
c.Add(("one", 1));
c.Add(("two", 2));
c.Add(("three", 3));

var map = c.ToDictionary();

// Getting the values out
foreach (var (key, value) in map)
    Console.WriteLine($"{key} = {value}");
```

**Comment by DrkWzrd** [comment]
I think TKey is misplaced and TSource is misleading. What should the last code print in your opinion? "one = 1"? or "1 = one"?

**Comment by davidfowl** [comment]
> What should last code print in your opinion? "one = 1"? or "1 = one"?

The most intuitive thing would be one = 1 😄. At least that was the intent.

> What should last code print in your opinion? "one = 1"? or "1 = one"?

Sure, I don't have any hangups about the generic argument names, whatever works. The intent is that the first value of the tuple is the key (Item1) and the second is the value (Item2).

**Comment by jnyrup** [comment]
Do you envision other benefits from this besides the fewer key strokes?

Should there also be overloads taking an `IEqualityComparer<TKey>`?

**Comment by eiriktsarpalis** [comment]
Sounds reasonable, proposal should probably also include equivalent IQueryable overloads cc @krwq

**Comment by davidfowl** [comment]
> Do you envision other benefits from this besides the fewer key strokes?

Haven't thought about the other potential savings.

> Should there also be overloads taking an `IEqualityComparer<TKey>`?

Possibly yes.

**Comment by jnyrup** [comment]
I'm asking since I recall(?) the bar of adding generic overloads to `Enumerable` has been a bit high and this doesn't seem to add new functionality.

**Comment by eiriktsarpalis** [comment]
> Do we also have ToDictionary on IQueryable? Seems strange no?

Ah yes you're right, not applicable to `To[Collection]` methods.

**Comment by krwq** [comment]
The proposal seems complete and I'm not strongly opinionated on this so I'll let API reviewers decide if we want this or not. I've personally wrote similar code in the past as mentioned so I guess it is occasionally very useful.

**Comment by davidfowl** [comment]
Yes I have no idea how common it is in the wild, I've been using this pattern more recently with tuples and LINQ so I figured I'd file an issue.

**Comment by eiriktsarpalis** [comment]
The proposal should probably include overloads that accept an `IEqualityComparer<TKey>` parameter.

**Comment by davidfowl** [comment]
Updated

**Comment by Neme12** [comment]
IMO we should use named tuples wherever possible, so this would be `IEnumerable<(TKey key, TValue)>` instead of `IEnumerable<ValueTuple<TKey, TValue>>`

**Comment by Neme12** [comment]
@davidfowl 
You only added that overload for `ValueTuple`, not for `KeyValuePair`. Also, it should be nullable like the existing overloads that take a comparer.

**Comment by TonyValenti** [comment]
I could definitely use this as I've already written the code to do these things. It makes initializing a dictionary so much more convenient.

**Comment by bartonjs** [comment]
* We changed the `ValueTuple<TKey, TValue>` syntax to `(TKey Key, TValue Value)`
* We added the KVP+EqualityComparer overload to square off the proposal.
* Discussion brought up that `dict.ToDictionary()` looks like a clone, but actually always uses the default comparer, which might be a loss of data integrity... and this should be pointed out in docs.

```C#
namespace System.Collections.Generic;

public static partial class Enumerable
{
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<KeyValuePair<TKey, TValue>> source) where TKey : notnull;
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<KeyValuePair<TKey, TValue>> source, IEqualityComparer<TKey> comparer) where TKey : notnull;
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<(TKey Key, TValue Value)> source) where TKey : notnull;
    public static Dictionary<TKey, TValue> ToDictionary<TKey, TValue>(this IEnumerable<(TKey Key, TValue Value)> source, IEqualityComparer<TKey> comparer) where TKey : notnull;
}
```

**Comment by lateapexearlyspeed** [comment]
Hi, [PR](https://github.com/dotnet/runtime/pull/85811) is marked as ready for review now, thanks.
