### ISSUE TITLE
[API Proposal]: Rename INumber<T>.Create<TOther> to CreateNumber<TOther> 

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/runtime#65921]
### Background and motivation

I am pleased with the Pattern established by INumber<T>.Create<TOther> which obviously allows to convert Values between different generic Implementations of INumber<T>. 

But applying two or more of this Patterns (from different Interfaces than INumber< T>) on the same Type, easily leads to a Name Clash. 
I therefore ask for a more descriptive Name that also conveys the Intention better. 

By renaming `INumber<T>.Create<TOther>` to  `CreateNumber<TOther>`  or even better: `CreateNumberFrom<TOther>(other)`  Conflicts are much less likely. 

### API Proposal

```C#
namespace System
{
    public interface INumber<TSelf>
    {
	static abstract TSelf CreateNumber<TOther>(TOther other);
    }
}
```

### API Usage

```C#

	public static T ConvertFrom<T, TN>(TN value)
		where T : INumber<T>
		where TN : INumber<TN> {
		return T.CreateNumber(value);
	}
```

### Alternative Designs

Of course you can also leave the Name ´Create´ but that makes it harder for future Developments.
In Fact, it is desirable to define additional new CreateXxx< TOther> Methods for smaller Sub-Interfaces of INumber< T> as [proposed here](https://github.com/dotnet/runtime/issues/65807).

### Risks

Since the System.INumber API is not final yet, the change is unproblematic. 
Since the Change will result in a Compile Error, it is very prominent and will not lead to hidden Problems.

**Comment by tannergooding** [comment]
Thanks for the suggestion here. I agree that the potentially conflicting name here might be problematic and it's something I will raise with API review.

**Comment by tannergooding** [comment]
The current proposal has the names as `CreateChecked`, `CreateSaturating`, and `CreateTruncating`
