### ISSUE TITLE
Unexpected behavior with LayoutKind.Sequential on generic struct

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#65923]
### Description

I'm finding that `LayoutKind.Sequential` doesn't seem to be respected for a generic struct when the generic parameter is a reference type. As far as I can tell, field ordering is not "sequential" in this case. 

### Reproduction Steps

```C#
public static void Main()
{
	Triple<long> t = default;
	Get(ref t, 0) = 4;
	Get(ref t, 1) = 5;
	Get(ref t, 2) = 6;
	Console.WriteLine(t); // (4, 5, 6)

	Triple<string> ts = default;
	Get(ref ts, 0) = "4";
	Get(ref ts, 1) = "5";
	Get(ref ts, 2) = "6";
	Console.WriteLine(ts); // (5, 6, 4)
}

public static ref T Get<T>(ref Triple<T> triple, int i) => ref Unsafe.Add(ref Unsafe.As<Triple<T>, T>(ref triple), i);

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct Pair<T>
{
	public T Item1;
	public T Item2;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct Triple<T>
{
	public Pair<T> Items1And2;
	public T Item3;

	public override string ToString() => $"({Items1And2.Item1}, {Items1And2.Item2}, {Item3})";
}
```

### Expected behavior

From reading the docs on `LayoutKind.Sequential`, I would expect both console writes to print the same thing.

### Actual behavior

The two console writes output different results.

### Configuration

.NET 6/Windows 10/x64

### Other information

Maybe this is the intended behavior and there is an opportunity to clarify the docs somewhere?

**Comment by stephentoub** [comment]
The docs for StructLayout say:
> For blittable types, [LayoutKind.Sequential](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.layoutkind?view=net-6.0#system-runtime-interopservices-layoutkind-sequential) controls both the layout in managed memory and the layout in unmanaged memory. For non-blittable types, it controls the layout when the class or structure is marshaled to unmanaged code, but does not control the layout in managed memory.

A type with containing a reference field is not blittable.

**Comment by madelson** [comment]
Makes sense. I missed that when reading through.
