### ISSUE TITLE
[API Proposal]: Add `IUnaryReciprocalOperators<TSelf>` to `IFloatingPoint<TSelf>`

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/runtime#65939]
### Background and motivation

Calculating the Reciprocal 1/x of x is a common Operation and to complete the Duality between Additive and Multiplicative Operators, it should be added to `INumber<TSelf,TResult>` either as an Operator and/or as a (polymorphic) Method named `Reciprocal()` or brief `Rcp()`. 

I propose to use ! as an Operator, because
* It looks similar to 1 so it reminds of 1/x 
* It is not used yet on Float Point Numbers where it would apply only 
* 

### API Proposal

```C#
namespace System
{
  public interface IUnaryReciprocalOperators<TSelf, TResult> where TSelf : IUnaryReciprocalOperators<TSelf, TResult>
  {
    static TResult operator !(TSelf value);

    // or, alternatively 
    TResult Reciprocal();

  }
}
```

### API Usage

```C#
var x = 2; 
var y = !x; 
var z = y.Reciprocal()
Console.WriteLine(y); //yields 0.5

z.ShouldBe(x); //because the reciprocal is bi-potent
```

### Risks

None, since the Operator and or Methods are new

**Comment by SpocWeb** [comment]
@Fydar, please give Reasons, not just a Thumbs down.

**Comment by Fydar** [comment]
This API proposal is dependent on [#65807](https://github.com/dotnet/runtime/issues/65807), which is something I have objections to on other grounds, but I'll leave any relevant discussion there.

1. Using the `!` operator for this function might needlessly collide with the logic implemented in non-system implementations of `INumber`.

2. Using the `!` operator seems clumsy, and the justification for why this operator should perform this exact function doesn't overcome the burden required to extend the `Int32` (and other numeric types) API into uncharted territories. This isn't just making already available logic generic, but it adds additional logic.

3. The functionality that this proposal grants can already be accomplished under the established set of APIs, via `INumber.One / number`.

4. The "logical negation operator" `!` is not the "unary reciprocal operator". I believe the interface naming should match both the name of the operator being used **and** the behaviour that the interface provides.

5. This proposal seems to indicate that _all_ numbers (via `INumber`) would now need to implement this operator, not just floats.  Hence, I'm unsure as to why this line is relevant.

    > It is not used yet on Float Point Numbers where it would apply only

**Comment by SpocWeb** [comment]
@Fydar 
ad 2) and 5) you are right, I accidently wrote `INumber<T>`. Actually I mean 'IFloatingPoint<T>' this would not apply to int, only to float and double. I have corrected that. 
ad 1) 2) and 3) I don't insist on the Operator, but I would like to have a Type-Specific Implementation of `Reciprocal()`, because this Operation can be highly optimized, e.g. for complex Numbers.

**Comment by tannergooding** [comment]
> I propose to use ! as an Operator, because

This is a non-starter, .NET explicitly doesn't do things like this with operators as its causes readability and usability issues. `!` in an expression explicitly means `logical not` and applies to boolean operations.

> Calculating the Reciprocal 1/x of x is a common Operation and to complete the Duality between Additive and Multiplicative Operators, it should be added to INumber<TSelf,TResult> either as an Operator and/or as a (polymorphic) Method named Reciprocal() or brief Rcp().

This is trivial to support and write via `1 / x`. .NET is generally not in the habit of exposing APIs for trivial operations like this. We will potentially expose `ReciprocalEstimate` which provides an accelerated version of the function and that may introduce inaccuracies (this would parity the `Math.ReciprocalEstimate` functions that were exposed since the initial design work for these interfaces). I expect such a function would remain only for the IEEE 754 floating-point types.

**Comment by tannergooding** [comment]
Going to close this given the above. I'm not against a proposal specifically for `Reciprocal` to parity (and exist next to) `ReciprocalEstimate` but someone would need to open a new API proposal covering this (or have OP reopen this issue and adjust the proposal accordingly)
