### ISSUE TITLE
Review workaround for TailCallStress mode

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#65934]
[Cleanup Issue-URLs in Code · Issue #63902 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63902) identified a workaround in place where it's unclear if the backing issue that necessitated the workaround has been resolved.

- The original issue was: [JIT\opt\OSR\tailrecursetry\tailrecursetry.cmd fails with COMPlus_FastTailCalls=0 · Issue #35687 · dotnet/runtime](https://github.com/dotnet/runtime/issues/35687)
- The PR that applied the workaround was: [Fix TailCallStress mode. by erozenfeld · Pull Request #40698 · dotnet/runtime](https://github.com/dotnet/runtime/pull/40698)

https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/tests/JIT/opt/OSR/tailrecursetry.csproj#L5-L9

The workaround should be evaluated to determine if it's still necessary. With the findings, we should either update the code to remove the workaround or update the code comment to reference an open issue for tracking when we can remove the workaround.

/cc @deeprobin

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch will check if @AndyAyersMS's fix resolved this issue.
