### ISSUE TITLE
Review workaround for HalfToInt16Bits and Int16BitsToHalf in Cbor

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#65935]
[Cleanup Issue-URLs in Code · Issue #63902 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63902) identified a workaround in place and it's unclear if the backing issue that necessitated the workaround has been resolved.

- The original issue was: [Consider adding HalfToInt16Bits and Int16BitsToHalf to BitConverter · Issue #38288 · dotnet/runtime](https://github.com/dotnet/runtime/issues/38288)
- The PR that introduced the workaround was: [[CBOR] Use System.Half for encoding and decoding half-precision data items by eiriktsarpalis · Pull Request #38466 · dotnet/runtime](https://github.com/dotnet/runtime/pull/38466)

https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/libraries/System.Formats.Cbor/src/System/Formats/Cbor/HalfHelpers.cs#L8-L12

The workaround should be evaluated to determine if it's still necessary. With the findings, we should either update the code to remove the workaround, or the code comment to reference an open issue for tracking when we can remove the workaround.

/cc @deeprobin

**Comment by teo-tsirpanis** [comment]
This is an old edition of the file. The issue has been addressed with #62872; if you take a look at [the current sources](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Formats.Cbor/src/System/Formats/Cbor), you will see that we forward to the existing BCL methods. The `HalfHelpers` class is still needed to uniformly convert between `half`s and `float`s across .NET Standard 2.0 and modern .NET.

**Comment by jeffhandley** [comment]
Thanks, @teo-tsirpanis! I'll update the comment to reflect that updated info.

**Comment by jeffhandley** [comment]
Oh, I see the comment doesn't even exist anymore. Excellent. Thanks again.
