### ISSUE TITLE
Locking StreamReader processes on EndOfStream

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#65952]
**NET Core version** : 3.1.10-pre1

We start child process and for this process we read STDERR and STDOUT streams.
We faced with the problem, that sometimes child process does not finish and we suspect that our call of StreamReader `EndOfStream` locks.

We found the doc: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=net-6.0#remarks
But there described the case when program tries to read output stream asynchronously while child process tries to read input stream. 
In our case, we write everything through the input stream and then close it. During further execution we only read output streams with the following code: https://github.com/microsoft/azure-pipelines-agent/blob/ac0dbcdb53cbcd77133641cbd39e00ca0e4d93d1/src/Agent.Sdk/ProcessInvoker.cs#L483-L508.

We call the function that contains code above twice for two readers (error and output streams). 
Logs show correct execution of child process with all lines from output and error streams, but when child process should finish, it doesn't exit.

We suspect that streams are locked, that on line `while (!reader.EndOfStream)`, that doesn't allow child process to exit.

Could you please suggest why lock on EndOfStream might occur? Could it be some known issue?
And could you please advise how we can avoid it?

**Comment by danmoseley** [comment]
Hello. Where is the code stopped -- is it waiting on `reader.ReadLine()` ?

**Comment by Jozkee** [comment]
> Could you please suggest why lock on EndOfStream might occur? Could it be some known issue?

I'm not very familiar with `StreamReader` or `Process.StandardOutput/Input/Error` to know what is happening by just reading the issue description, @tatyana-kostromskaya if you could please share a minimal repro (console app) I could be able to take a deeper look.
