### ISSUE TITLE
[API Proposal]: Add a fast Norm() or IsCloseTo(double tolerance) Function to `INumber<TSelf>`

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/runtime#65950]
### Background and motivation

Many numeric Algorithms need to iterate and check for Convergence.

To be able to formulate these Algorithms with `INumber<TSelf>`, it has to implement a way to check whether two Values are close enough to each other to stop iterating, independent of the concrete TSelf Type. 

Since all p-Norms are topologically equivalent, the actual Implementation is not so relevant. It can be the Abs-Norm (p0, Sum of the absolute Values of a Vector), Max-Norm (pInfinity, the maximum Value) or any p-Norm in-between, especially the euclidean Norm (p2) although the square root makes it slower than the Abs-Norm.

### API Proposal

```C#
namespace System
{
    public interface IHaveNorm { double Norm(); }

    public interface INumber<TSelf> : IHaveNorm { ... }
}
```

### API Usage

```C#
	// Fixed Point Calculation of a Function f
	public T GetFixedPoint(Func<T,T> f, T x, double relAccuracy) where T : INumber< T> {
		var accuracy = relAccuracy * x.Norm;
		var next = f(x);
		while ((next - x).Norm > accuracy)
		{
			next = f(x);
		}
		return next;
	}
```

### Alternative Designs

Without such a Method, the Check for Convergence requires Type-specific Code. 

A Norm implies that it is homogeneous, i.e. Norm(a*x) = Math.Abs(a)*Norm(x)
This may be an unduly restriction. 

I would also be happy with `INumber<T>` implementing a general Metric Method: 
`double Distance(T other)` 

This could be applied to more Number Types like `Complex`, `Vector2D`, `Quaternion` etc.

### Risks

None, this is a new Method on a new, not final API

**Comment by tannergooding** [comment]
This isn't an API that is easy to expose or that will function as intended for typical algorithms.

Consumers of the numeric interfaces will need to do their own checks based on what's exposed. Floating-point types in particular have the ability to return the delta between two neighboring representable values already (by utilizing `BitIncrement` and `BitDecrement`) as well as enough other related functions that this can be handled already.
