### ISSUE TITLE
[FileStream] Multiple FileShare are not working in FileStream

### ISSUE THREAD

**Issue by hamzashoukat94** [dotnet/runtime#65953]
### Description

I have faced the issue of unauthorized access on the deletion of file. Actually, I have two classes in the same process, one class is constructing a fileStream object with multiple FileShare. 
`
FileStream stream = new FileStream(FileFullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);`

And Second class is trying to delete the file, it is not working.

I have told you that I am assigning both shares.

### Reproduction Steps

In Class A

`FileStream stream = new FileStream(FileFullName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);`

In Class B

`File.Delete(FileFullName);`

### Expected behavior

Should allow deleting

### Actual behavior

Not allowing to delete the file

**Comment by adamsitnik** [comment]
Hi @hamzashoukat94 

I've tried to repro the issue that you have described but I've failed. Here is the code that I've used:

```cs
string filePath = Path.Combine(Path.GetTempPath(), Path.GetTempFileName());

while (true)
{
    File.WriteAllText(filePath, "someContent");

    FileStream stream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite | FileShare.Delete);
    File.Delete(filePath);
    stream.Dispose();
}
```

Please provide the following:
* repro app
* call stack
* OS version
