### ISSUE TITLE
Parallel.ForEachAsync and propagation of endogenous cancellation errors

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#65963]
The [`Parallel.ForEachAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreachasync) provides a `CancellationToken` for canceling any operations that are in-flight, after the occurrence of an error in some other parallel operation. My expectation was that the secondary errors caused by the cancellation of this token would be suppressed, but as I noticed recently these endogenous exceptions are propagated through the `Task` that the `Parallel.ForEachAsync` returns, along with the exogenous original exception. Here is a minimal demonstration of this behavior:

```C#
using System;
using System.Linq;
using System.Threading.Tasks;

public class Program
{
    public static async Task Main()
    {
        var source = Enumerable.Range(1, 10);
        var options = new ParallelOptions() { MaxDegreeOfParallelism = 5 };
        var task = Parallel.ForEachAsync(source, options, async (item, token) =>
        {
            await Task.Delay(500, token);
            if (item == 5) throw new ApplicationException("Oops!");
            await Task.Delay(500, token);
        });
        try
        {
            await task;
        }
        catch when (task.IsFaulted)
        {
            foreach (var error in task.Exception.InnerExceptions)
                Console.WriteLine($"{error.GetType().Name}: {error.Message}");
        }
    }
}
```

Output:

```none
ApplicationException: Oops!
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
```

[Try it on Fiddle](https://dotnetfiddle.net/ODgJwt).

This behavior is surprising because it deviates from the behavior of other APIs that have been used before the introduction of the `Parallel.ForEachAsync` API, for implementing a similar functionality. Here are two counter examples:

1. Using the `Task.WhenAll` method. ([demo](https://dotnetfiddle.net/WqeRDC))
2. Using an `ActionBlock<T>`. ([demo](https://dotnetfiddle.net/hAwewV))

Both of those demos propagate a single `ApplicationException`.

I would like to ask if the current behavior of the `Parallel.ForEachAsync` is by design. If not, I would like to vote for changing the behavior in the next .NET version, because observing and logging those `TaskCanceledException`s has no value IMHO, and filtering them out every time is a chore. I am talking about the cancellation errors that are induced by the API itself, not for any `OperationCanceledException` that might be thrown unprovoked by the `body` lambda. Honestly I am not sure about how those should be handled.

**Comment by stephentoub** [comment]
It's by design.
https://github.com/dotnet/runtime/pull/59065#issuecomment-920262380

**Comment by theodorzoulias** [comment]
> It's by design. [#59065 (comment)](https://github.com/dotnet/runtime/pull/59065#issuecomment-920262380)

@stephentoub OK, thanks for the quick feedback! I'll leave this issue open for a few days, to see if there are other people with similar concerns regarding the current behavior of this API.

**Comment by theodorzoulias** [comment]
I just checked the behavior of the synchronous [`Parallel.ForEach`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallel.foreach) method, and I find it to be consistent with the behavior of the new `Parallel.ForEachAsync` API. The cancellation errors are propagated in exactly the same way. [Demo](https://dotnetfiddle.net/PgwlHv):

```C#
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

public class Program
{
    public static void Main()
    {
        ThreadPool.SetMinThreads(10, 10);
        var source = Enumerable.Range(1, 10);
        var options = new ParallelOptions() { MaxDegreeOfParallelism = 5 };
        var cts = new CancellationTokenSource();
        try
        {
            Parallel.ForEach(source, options, item =>
            {
                try
                {
                    Task.Delay(500, cts.Token).GetAwaiter().GetResult();
                    if (item == 5) throw new ApplicationException("Oops!");
                    Task.Delay(500, cts.Token).GetAwaiter().GetResult();
                }
                catch { cts.Cancel(); throw; }
            });
        }
        catch (AggregateException aex)
        {
            foreach (var error in aex.InnerExceptions)
                Console.WriteLine($"{error.GetType().Name}: {error.Message}");
        }
    }
}
```

Output:

```none
ApplicationException: Oops!
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
TaskCanceledException: A task was canceled.
```

So I am closing this issue, since the new API follows the conventions of the existing API. 😃
