### ISSUE TITLE
[DebuggerDisplay] for JsonTypeInfo does not render

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#65960]
### Description

While debugging some code using the JSON source generator in Visual Studio 2022 I found that the debugger display for a `JsonSerializerContext` class is broken.

![image](https://user-images.githubusercontent.com/1439341/156013964-1f178cd4-87bc-437b-b34c-addf05310d6b.png)

Instead of showing the intended display text, instead the IDE shows a message similar to `ConverterStrategy.error CS0119: 'ConverterStrategy' is a type, which is not valid in the given context, "Boolean"`.

Following the code through, it looks like there's an issue with the value passed to the constructor of the `[DebuggerDisplay]` attribute on `JsonTypeInfo` here:

https://github.com/dotnet/runtime/blob/c41f452cc96a2f2e73c71610d423df3e9c133fef/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs#L17

### Reproduction Steps

View a derived instance of `` using the JSON source generator in an IDE with Intellisense, such as Visual Studio 2022.

```csharp
using System.Text.Json.Serialization;

var context = new CustomJsonSerializerContext();

// Put a breakpoint on the line below and inspect context in the debugger
Console.ReadLine();

[JsonSerializable(typeof(bool))]
internal sealed partial class CustomJsonSerializerContext : JsonSerializerContext
{
}
```

### Expected behavior

A compiler error is not shown in the rendered debugger display for the class' properties.

### Actual behavior

The properties all show a compiler error similar to the below.

```
ConverterStrategy.error CS0119: 'ConverterStrategy' is a type, which is not valid in the given context, "Boolean".
```

### Regression?

No, this functionality was new in .NET 6.

### Known Workarounds

None.

### Configuration

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\
```

**Comment by eiriktsarpalis** [comment]
Thanks, I've been seeing this as well. It seems to be impacting a few internal serializer types as well. I submitted a fix in #65971
