### ISSUE TITLE
Unhandled ThreadAbortException during appdomain unload

### ISSUE THREAD

**Issue by pipi1007** [dotnet/runtime#65980]
### Description

We are getting unhandled threadabortexception when appdomain is unloading, and the unload thread seems to get stuck. Is this a bug? Sorry if this is not the right place to post this problem, please help redirect if so.

00 000000c1`fe2bf7d8 00007fff`58e685c3     ntdll!ZwWaitForSingleObject+0x14
01 000000c1`fe2bf7e0 00007fff`50dd6238     KERNELBASE!WaitForSingleObjectEx+0x93
02 000000c1`fe2bf880 00007fff`50dd61ee     clr!CLREventWaitHelper2+0x3c
03 000000c1`fe2bf8c0 00007fff`50dd6158     clr!CLREventWaitHelper+0x1f
04 000000c1`fe2bf920 00007fff`50d5c7db     clr!CLREventBase::WaitEx+0x71
05 (Inline Function) --------`--------     clr!CLREventBase::Wait+0x12
06 000000c1`fe2bf9b0 00007fff`50bfb5c5     clr!AppDomain::ADUnloadThreadStart+0x188
07 000000c1`fe2bfae0 00007fff`5ac27974     clr!Thread::intermediateThreadProc+0x8b
08 000000c1`fe2bfda0 00007fff`5cbfa2f1     kernel32!BaseThreadInitThunk+0x14
09 000000c1`fe2bfdd0 00000000`00000000     ntdll!RtlUserThreadStart+0x21

At the same time, there is a thread throwing ThreadAbortException:

00 000000c1`85cfd548 00007fff`58e8d59e     ntdll!ZwWaitForMultipleObjects+0x14
01 000000c1`85cfd550 00007fff`58e8d48e     KERNELBASE!WaitForMultipleObjectsEx+0xfe
02 000000c1`85cfd850 00007fff`5ac78b8f     KERNELBASE!WaitForMultipleObjects+0xe
03 000000c1`85cfd890 00007fff`5ac7863c     kernel32!WerpReportFaultInternal+0x51b
04 000000c1`85cfd9b0 00007fff`58eb7c3e     kernel32!WerpReportFault+0xac
05 000000c1`85cfd9f0 00007ff6`0af61877     KERNELBASE!UnhandledExceptionFilter+0x35e
06 000000c1`85cfdb00 00007fff`52b0a1c4     w3wp!WpUnhandledExceptionFilter+0x47
07 (Inline Function) --------`--------     mscoreei!CLRUEFManager::ChainbackToPreviousOSUEF+0x1f
08 000000c1`85cfdb30 00007fff`58eb7a9c     mscoreei!InternalUnhandledExceptionFilter+0x41
09 000000c1`85cfdb60 00007fff`5cc48440     KERNELBASE!UnhandledExceptionFilter+0x1bc
0a (Inline Function) --------`--------     ntdll!RtlpThreadExceptionFilter+0x99
0b 000000c1`85cfdc70 00007fff`5cc2fdd6     ntdll!RtlUserThreadStart$filt$0+0xaa
0c 000000c1`85cfdcb0 00007fff`5cc44a2f     ntdll!__C_specific_handler+0x96
0d 000000c1`85cfdd20 00007fff`5cba4cef     ntdll!RtlpExecuteHandlerForException+0xf
0e 000000c1`85cfdd50 00007fff`5cba8ae6     ntdll!RtlDispatchException+0x40f
0f 000000c1`85cfe480 00007fff`58e69319     ntdll!RtlRaiseException+0x316
10 000000c1`85cfec80 00007fff`50ca4961     KERNELBASE!RaiseException+0x69
11 000000c1`85cfed60 00007fff`50de9d2d     clr!RaiseTheExceptionInternalOnly+0x31f
12 000000c1`85cfee80 00007fff`50de9dd3     clr!RaiseTheException+0xa6
13 (Inline Function) --------`--------     clr!RealCOMPlusThrowWorker+0x2b
14 000000c1`85cfeeb0 00007fff`50de9de0     clr!RealCOMPlusThrow+0x9b
15 000000c1`85cfef20 00007fff`510580d8     clr!RealCOMPlusThrow+0xc
16 000000c1`85cfef50 00007fff`5105559f     clr!Thread::RaiseCrossContextException+0x3c8
17 000000c1`85cff190 00007fff`50ca9b24     clr!Thread::DoADCallBack+0x1a7
18 000000c1`85cff350 00007fff`50bf241d     clr!UM2MDoADCallBack+0xb3
19 000000c1`85cff3d0 00007fff`4de818bf     clr!UMThunkStub+0x26d
1a 000000c1`85cff460 00007fff`4de81812     webengine4!W3_MGD_HANDLER::ProcessNotification+0x8e
1b 000000c1`85cff490 00007fff`50bf9a11     webengine4!ProcessNotificationCallback+0x42
1c 000000c1`85cff4c0 00007fff`50bf78a7     clr!UnManagedPerAppDomainTPCount::DispatchWorkItem+0x1b9
1d 000000c1`85cff560 00007fff`50bf777f     clr!ThreadpoolMgr::ExecuteWorkRequest+0x64
1e 000000c1`85cff590 00007fff`50bfb5c5     clr!ThreadpoolMgr::WorkerThreadStart+0xf6
1f 000000c1`85cff630 00007fff`5ac27974     clr!Thread::intermediateThreadProc+0x8b
20 000000c1`85cffc70 00007fff`5cbfa2f1     kernel32!BaseThreadInitThunk+0x14
21 000000c1`85cffca0 00000000`00000000     ntdll!RtlUserThreadStart+0x21

### Reproduction Steps

Unknown, this happens randomly, we don't know how to reproduce.

### Expected behavior

Appdomain should unload and ThreadAbortException shouldn't be unhandled.

### Actual behavior

Appdomain unload seems to get stuck, and ThreadAbortException is unhandled.

**Comment by jkotas** [comment]
> Sorry if this is not the right place to post this problem, please help redirect if so.

The right place to report .NET Framework issues is Microsoft Community portal https://github.com/dotnet/core#getting-help

> We are getting unhandled threadabortexception when appdomain is unloading, and the unload thread seems to get stuck.
> Unknown, this happens randomly, we don't know how to reproduce.

FWIW, it is not unusual to see reliability issues with appdomain unload like this one. It is very hard to avoid them completely. The best solution is to not use appdomain unload, or to allow for appdomain unload to be unreliable (e.g. recycle the process when appdomain unload gets stuck).

**Comment by jkotas** [comment]
Appdomain unload was removed in .NET Core/.NET 5+. This issue is not actionable in this repo.

**Comment by pipi1007** [comment]
@jkotas could you please advise how to find out the cause of the appdomain unload? Looking at the HostingEnvironment from the dump, appdomainshutdownstarted is set to false. 

0:305> !mdt 0000029dba2b3698
0000029dba2b3698 (System.Web.Hosting.HostingEnvironment)
    __identity:0000029dba2b46d0 (System.Runtime.Remoting.ServerIdentity)
    _onAppDomainUnload:0000029dba2b3e90 (System.EventHandler)
    _appManager:0000029dba2b5a90 (System.Runtime.Remoting.Proxies.__TransparentProxy)
    _hostingParameters:0000029dba2b6278 (System.Web.Hosting.HostingEnvironmentParameters)
    _appHost:0000029dba2b6240 (System.Runtime.Remoting.Proxies.__TransparentProxy)
    _externalAppHost:true (System.Boolean)
    _configMapPath:0000029dba2b9c90 (System.Web.Configuration.ProcessHostMapPath)
    _configMapPath2:0000029dba2b9c90 (System.Web.Configuration.ProcessHostMapPath)
    _configToken:0000000000000000 (System.IntPtr)
    _appIdentity:NULL (System.Web.Configuration.IdentitySection)
    _appIdentityToken:0000000000000000 (System.IntPtr)
    _appIdentityTokenSet:true (System.Boolean)
    _appId:0000029dba236478 (System.String) Length=20, String="/LM/W3SVC/2/ROOT/owa"
    _appVirtualPath:0000029dba2b9a58 (System.Web.VirtualPath)
    _appPhysicalPath:0000029dba2364c0 (System.String) Length=64, String="C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\owa\"
    _siteName:0000029dba23ac58 (System.String) Length=17, String="Exchange Back End"
    _siteID:0000029dba2b9fe8 (System.String) Length=1, String="2"
    _appConfigPath:0000029dba2ba9e0 (System.String) Length=21, String="machine/webroot/2/owa"
    _isBusy:true (System.Boolean)
    _busyCount:0xd (System.Int32)
    _removedFromAppManager:false (System.Boolean)
    _appDomainShutdownStarted:false (System.Boolean)
    _shutdownInitiated:false (System.Boolean)
    _shutdownInProgress:false (System.Boolean)
    _shutDownStack:NULL (System.String)
    _inTrimCache:0x0 (System.Int32)
    _objectCacheHost:0000029dba2ba870 (System.Web.Hosting.ObjectCacheHost)
    _wellKnownObjects:0000029dba2b3790 (System.Collections.Hashtable)
    _registeredObjects:0000029dba2b3840 (System.Collections.Hashtable)
    _suspendManager:0000029dba2b3890 (System.Web.Hosting.SuspendManager)
    _applicationMonitors:0000029dba360da8 (System.Web.Hosting.ApplicationMonitors)
    _backgroundWorkScheduler:0000029dbb3e9b10 (System.Web.Hosting.BackgroundWorkScheduler)
    _initiateShutdownWorkItemCallback:0000029dba2ba3f0 (System.Threading.WaitCallback)
    _idleTimeoutMonitor:0000029dba360448 (System.Web.IdleTimeoutMonitor)
    _virtualPathProvider:0000029dba2ba430 (System.Web.Hosting.MapPathBasedVirtualPathProvider)
    _mapPathBasedVirtualPathProvider:0000029dba2ba430 (System.Web.Hosting.MapPathBasedVirtualPathProvider)

**Comment by jkotas** [comment]
I am sorry I am not able to tell from this info. The first thing that I would check is whether there was only one secondary appdomain ever created in this process.
