### ISSUE TITLE
Match_Timeout_Repetition_Throws(engine: NonBacktracking) timing out

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#65991]
This outer loop test is now running for a very long time and eventually the test suite times out.  I expect this is due to https://github.com/dotnet/runtime/commit/83e5cbcf1bb3f948587ef15c1d09d8e95f906348, and that it's doing exactly what it tried to do, which is keep execution in the inner loop as long as possible.  That would mean, however, that we wouldn't exit out into the outer loop frequently enough to hit the timeout check:
https://github.com/dotnet/runtime/blob/d9eafd0c55ff7c3d7804c7629baf271703df91a6/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.cs#L786-L821

cc: @olsaarik

**Comment by olsaarik** [comment]
Ok seems we'll need to introduce some equivalent of the previous "leeway" thing to pop out of the inner loop occasionally. The check for "did we reach the end of input" could just additionally check if the inner loop was actually given the full length of the input and if not just loop back (but skip the NFA promotion).

**Comment by olsaarik** [comment]
I'll be making changes to these matching loops in the PR after https://github.com/dotnet/runtime/pull/66038, so I can fix it at the same time.
