### ISSUE TITLE
Custom build for item succeeded, but specified output has not been created

### ISSUE THREAD

**Issue by luckerby** [dotnet/runtime#660]
Simply cloned the repo and ran `build.cmd`, however the build eventually fails with:

> Build FAILED.
> 
> C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\src\coreclr\coreclr.proj(22,5): error MSB3073: The command ""C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\src\coreclr\build.cmd" -skiptests -x64 -debug -officialbuildid=" exited with code 1.
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB8065: Custom build for item "C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\CMakeFiles\b330423e2912553c947526ef5acc731b\INSTALL_force.rule" succeeded, but specified output "c:\users\sandmansam\desktop\dotnetcore_runtime_repo\runtime\artifacts\obj\native\netcoreapp-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\install.vcxproj] [C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\src\libraries\Native\build-native.proj]
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB8065: Custom build for item "C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\CMakeFiles\b330423e2912553c947526ef5acc731b\INSTALL_force.rule" succeeded, but specified output "c:\users\sandmansam\desktop\dotnetcore_runtime_repo\runtime\artifacts\obj\native\netcoreapp-windows_nt-debug-x64\cmakefiles\install_force" has not been created. This may cause incremental build to work incorrectly. [C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\artifacts\obj\native\netcoreapp-Windows_NT-Debug-x64\install.vcxproj] [C:\Users\sandmansam\Desktop\dotnetCore_Runtime_repo\runtime\src\libraries\Native\build-native.proj]
>     0 Warning(s)
>     3 Error(s)
> 
> Time Elapsed 00:21:46.30
> (NETCORE_ENGINEERING_TELEMETRY=Category) Build failed.

The messages themselves resemble very well the ones [here](https://github.com/dotnet/runtime/issues/149), it's only that the cmake version is slightly different:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview>cmake --version
> cmake version 3.15.19080502-MSVC_2
> 
> CMake suite maintained and supported by Kitware (kitware.com/cmake).
> 

As for VS, it's Visual Studio 2019 16.4.0 Preview 1.

**Comment by ViktorHofer** [comment]
CMake 3.15.5 is the min required version for the runtime repo: https://github.com/dotnet/runtime/blob/master/docs/workflow/windows-requirements.md#cmake. Please let me know if upgrading fixed the issue. Thanks.
