### ISSUE TITLE
HttpClient SendAsync throwing NullReferenceException

### ISSUE THREAD

**Issue by dosegal** [dotnet/runtime#66004]
### Description

HttpClient SendAsync throwing NullReferenceException with the following stack trace:

 System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.Headers.HttpHeaderParser.ToString(Object value)
   at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](String[] values, Object storeValue, HttpHeaderParser parser, T exclude, Int32& currentIndex)
   at System.Net.Http.Headers.HttpHeaders.GetValuesAsStrings(HeaderStoreItemInfo info, Object exclude)
   at System.Net.Http.Headers.HttpHeaders.GetHeaderString(HeaderStoreItemInfo info, Object exclude)
   at System.Net.Http.Headers.HttpHeaders.<GetHeaderStrings>d__15.MoveNext()
   at System.Net.Http.HttpClientHandler.SetRequestHeaders(HttpWebRequest webRequest, HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

Here is the code that makes the call:

```csharp
private async Task<HttpResponseMessage> SendArmAsync(string authorizationAccessToken, HttpRequestMessage reqArm, Metadata metadata = null)
        {
            return await operationsUtil.TraceAndRunAsync(
                async () =>
                {
                    reqArm.AddRequestHeaders(authorizationAccessToken, metadata);

                    return await httpClientProvider.ProvideHttpClient(reqArm.RequestUri).SendAsync(reqArm).ConfigureAwait(false);
                }).ConfigureAwait(false);
        }
```

httpClientProvider uses a LoadBalancedHttpClientPool with a pool size of 1 -

```csharp
public class HttpClientProvider : IHttpClientProvider
    {
        private const int ClientPoolCapacity = 1;

        private readonly LoadBalancedHttpClientPool clientPool;

        public HttpClientProvider()
        {
            clientPool = new LoadBalancedHttpClientPool(ClientPoolCapacity);
        }

        public HttpClient ProvideHttpClient(Uri requestUri)
        {
            return clientPool.GetHttpClient(requestUri).Value;
        }
    }
```

### Reproduction Steps

Could not reproduce locally.
Reproduces in production environment - around 0-0.2% a week

### Expected behavior

Should not throw NullReferenceException.

### Actual behavior

HttpClient SendAsync throwing NullReferenceException

### Configuration

.NET Framework 4.7.2 application

**Comment by ManickaP** [comment]
> .NET Framework 4.7.2

If you need help with .NET Framework then this place is better: https://developercommunity.visualstudio.com/search?space=61

This repository is for .NET Core, .NET 5+.

However, be aware that the bar for doing any changes/fixes in .NET Framework is really high. We strongly recommend everyone to migrate to .NET 6 (the newest release of .NET)

**Comment by dosegal** [comment]
> > .NET Framework 4.7.2
> 
> If you need help with .NET Framework then this place is better: https://developercommunity.visualstudio.com/search?space=61
> 
> This repository is for .NET Core, .NET 5+.
> 
> However, be aware that the bar for doing any changes/fixes in .NET Framework is really high. We strongly recommend everyone to migrate to .NET 6 (the newest release of .NET)

Thanks, I submitted the issue there. Closing the issue
