### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#66016]
Build Browser wasm Linux Release LibraryTests_AOT

Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-b419803a6de646aeaa/normal-System.Text.RegularExpressions.Tests/1/console.ef168fa6.log?sv=2019-07-07&se=2022-03-21T09%3A53%3A15Z&sr=c&sp=rl&sig=LkR4mrIGGwLy2TKrpqN%2FC%2Ftk6hRo2zW0drs0k4NFAeA%3D

```
(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/helix.service,task=clang++,pid=20962,uid=1000 [ 2714.986753] Out of memory: Killed process 20962 (clang++) total-vm:7472572kB, anon-rss:7155720kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:14628kB oom_score_adj:0 [ 2715.199318] oom_reaper: reaped process 20962 (clang++), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
/datadisks/disk1/work/AF4A0978/w/A50D08BD/e /datadisks/disk1/work/AF4A0978/w/A50D08BD/e
----- end Tue Mar 1 10:45:23 UTC 2022 ----- exit code 240 ----------------------------------------------------------
```

**Comment by radical** [comment]
These are getting oom-killed on both linux, and windows.

**Comment by thaystg** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/65978
