### ISSUE TITLE
Reduce the trim requirements on MetadataUpdateHandlerAttribute

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#66069]
Currently the type passed to the `.ctor` of `MetadataUpdateHandlerAttribute` will be annotated with `DynamicallyAccessedMemberTypes.All`. For apps this doesn't matter because the attribute is marked for removal in trimmed apps by default, so the annotation is not applied.

But this does matter for analysis of libraries for trimming. The `All` annotation is particularly problematic because it will force include all nested types and may cause additional warnings produced by the analysis as it will treat all members on the type as potentially accessed via reflection (so any member annotated for trimming in any way will produce a warning).

My reading of the usage of `MetadataUpdateHandlerAttribute` shows that we only need methods on the target type (in fact we only need two specific static methods, but there's no way to annotate it that way right now).

Can we improve the annotation on the `MetadataUpdateHandlerAttribute` to only ask for methods: `DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods`?

**Comment by stephentoub** [comment]
For my edification, can you share an example from one of our handlers where this is causing an issue?

**Comment by vitek-karas** [comment]
The `All` annotation being applied to a "random" class is also problematic because of compiler generated code. Technically the annotation allows one to use reflection to access anything on the class, including closure classes. Thus linker has to "mark" the closures and everything on them as well. If there's anything annotated anywhere on the closure, it will produce a warning which will be really difficult to explain since it may not directly map to user code. And even if linker could map the closure back to the method it originated from, it's still not clear if it can ignore the potential reflection access (in all other cases we're trying to treat the closures as "not there" and only consider them for the method they come from, but private reflection sees everything).

**Comment by steveharter** [comment]
Moving to 8.0; we want to be more linker-friendly in 8.0.
