### ISSUE TITLE
`ProviderAliasAttribute` can be sealed?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#66078]
Maybe the  `ProviderAliasAttribute` in the `Microsoft.Extensions.Logging` can be `sealed`

https://github.com/dotnet/runtime/blob/2330b4bef645bf8bcd3011f35968e55192c697f5/src/libraries/Microsoft.Extensions.Logging/src/ProviderAliasAttribute.cs#L12

**Comment by stephentoub** [comment]
Sealing an existing type is both a source and binary breaking change.

**Comment by WeihanLi** [comment]
Think it should not be inherited, maybe it's acceptable for a breaking change?

**Comment by stephentoub** [comment]
Why? We generally prefer to seal attributes, but this one shipped unsealed. If someone is deriving from it, why is that so harmful that it's important to break them? And what huge benefit does sealing it now bring that it's worth breaking them?

**Comment by WeihanLi** [comment]
@stephentoub , yeah, you're right, we should try to avoid the breaking change.
Just try to propose this, we could ignore this if it's not acceptable, from what I can see, I think it's none sense to inherit this, and it's not been inherited from the grep search result: https://grep.app/search?q=ProviderAliasAttribute
