### ISSUE TITLE
AssemblyLoadContext Unload does not release PDB file

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/runtime#66091]
### Description

load zip... create AssemblyLoadContext..
ive managed to successfully unload the dll...  but cant delete the containing folder as there still a lock on the pdb

so basically .Unload() is working although i would love more love here interms of examples
but got this to work....

issue is it cant delete the folder as there is a lock on the pdb file

Visual Studo 2022, .net 6

### Reproduction Steps

Load dll in AssemblyLoadContext, ensure its unloaded, 

delete the folder from which it was loaded, ensure you have a pdb file in there which is linked to the dll file u are loading.

### Expected behavior

the file should not be locked. in my case i have quite a few files in the folder, all of which get deleted but the pdb file.

### Actual behavior

get an exception that the pdb file is locked.

### Known Workarounds

I think if i delete the pdf files before loading it might work, about to test

### Configuration

.net 6
windows 10 x64
visual studio 2022

**Comment by jkotas** [comment]
The runtime reads the PDB files to add stacktrace file and line numbers (e.g. `Exception.ToString()`).

https://github.com/dotnet/runtime/search?q=StackTraceSymbols

**Comment by VSadov** [comment]
As I see `StackTraceSymbols` uses `ConditionalWeakTable` to hold the pdb reader alive. 
Weak caching, and in particular CWT can make lifetime guarantees nontrivial.

**Comment by VSadov** [comment]
@Seabizkit - is exception handling involved? do you have a simple repro?

**Comment by Seabizkit** [comment]
@vitek-karas that is correct happens when running from debug.

to be honest im writing what i consider a simple plugin lib, and wow does it make little sense... simple is relative i guess..

As its a private project i dnt really want to share but to make progress i kind of need these things to actually work. Is the best to post snips here so an idea of what im doing is seen, also sucks when u have multiple issues and tickets can only tackle 1 by 1

```c#
   
//stripped using statments
namespace Paradox.Core.Service
{
    public class PluginService : IPluginService
    {
        IBuilderComponentRepo _builderComponentRepo;
        IBuilderComponentPhysicalRepo _builderComponentPhysicalRepo;
        IFileHelper _fileHelper;

        public PluginService(
            IBuilderComponentRepo builderComponentRepo,
            IBuilderComponentPhysicalRepo builderComponentPhysicalRepo,
            IFileHelper fileHelper
            )
        {
            _builderComponentRepo = builderComponentRepo;
            _builderComponentPhysicalRepo = builderComponentPhysicalRepo;
            _fileHelper = fileHelper;
        }

      //request obj has a Name and Data property, where data is the byte array of the uploaded file
      // name is the name of the upload file
        public async Task<PluginUploadResponse> UploadPluginAsync(PluginUploadRequest request)
        {
            var response = new PluginUploadResponse();

            //put the file in temp location
            string unquieNamePath = await _fileHelper.SaveFileToTempAsync(request.Data,request.FileName);

            string currentDirectory = Path.GetDirectoryName(unquieNamePath);

            //unzip the file
            var pluginComponentFolder = Path.Combine(currentDirectory, Path.GetFileNameWithoutExtension(unquieNamePath));
            ZipFile.ExtractToDirectory(unquieNamePath, pluginComponentFolder);

            //HACK - delete all the PDB FILES from this location, as even when unloaded they hang onto
            var pdbFiles = Directory.GetFiles(pluginComponentFolder, "*.pdb", SearchOption.TopDirectoryOnly);
            foreach (var item in pdbFiles)
            {
                File.Delete(item);
            }

            //var assembliesToNotLoad = new List<string>()
            //{
            //    "Paradox.Component.Facade.Std2.dll"
            //};

            //from the files find, the classes which implment BaseComponentUI and IParadoxComponent
            var dllFiles = Directory.GetFiles(pluginComponentFolder, "*.dll", SearchOption.TopDirectoryOnly);
            var ddlFilesFilter = dllFiles.Where(f => !(
                                              Path.GetFileName(f).StartsWith("Microsoft")
                                            || Path.GetFileName(f).StartsWith("System")
                                        )
                                       // && !assembliesToNotLoad.Contains( Path.GetFileName(f))
                                        && (
                                          Path.GetFileName(f).Contains("Component", StringComparison.OrdinalIgnoreCase)
                                          || Path.GetFileName(f).Contains("Plugin", StringComparison.OrdinalIgnoreCase)
                                          )
                                        ).ToList();

            // Console.WriteLine(pluginComponentFolder);
            var firstdll = ddlFilesFilter.First();
           // var withEndingSalsh = pluginComponentFolder + Path.DirectorySeparatorChar;

            GetNumberOfAssembliesLoaded();
            Loadtypes(out WeakReference weakRef,out PluginLoadContext alc, ddlFilesFilter, firstdll);


           //<--- NEXT ISSUE - this now doesnt release commented out for now
          //  var baseResponse = await ValidateAndProcessPluginAsync(alc, request);
         

            GetNumberOfAssembliesLoaded();
            //does not make sense to have to use ref: YET does not work without it.
            Unload(weakRef,ref alc);  ///<---- NEXT ISSUE WHY DOES THIS NOT WORK WITHOUT REF
            GetNumberOfAssembliesLoaded();


            try
            {
                //cleanup delete the tempfiles
                for (int i = 0; (i < 10); i++)
                {
                    try
                    {
                        Directory.Delete(pluginComponentFolder, true);
                        break;
                    }
                    catch (UnauthorizedAccessException e)
                    {
                        //DOES NOT WORK
                        //FileAttributes attributes = File.GetAttributes(pluginComponentFolder);
                        //if ((attributes & FileAttributes.ReadOnly) == FileAttributes.ReadOnly)
                        //{
                        //    attributes &= ~FileAttributes.ReadOnly;
                        //    File.SetAttributes(pluginComponentFolder, attributes);
                        //    File.Delete(pluginComponentFolder);
                        //    break;
                        //}
                        //else
                        //{
                        //    throw;
                        //}
                    }
                }

                if (Directory.Exists(pluginComponentFolder))
                {
                    Directory.Delete(pluginComponentFolder, true);
                }
                

                //delete the temp file
                File.Delete(unquieNamePath);
            }
            catch (Exception e)
            {
                response.AddError(e.Message);
                throw;
            }
   

            return response;
        }

 private void Unload(WeakReference weakRef,ref PluginLoadContext alc)
        {
            alc.Unload();
            alc = null;

            for (int i = 0; weakRef.IsAlive && (i < 10); i++)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
                System.Threading.Thread.Sleep(10);
            }

            Console.WriteLine($"is alive: {weakRef.IsAlive}");
        }

        private int GetNumberOfAssembliesLoaded()
        {
            var loadAppDomainAssemblyCount = AppDomain.CurrentDomain.GetAssemblies().Count();
            System.Console.WriteLine(loadAppDomainAssemblyCount);
            return loadAppDomainAssemblyCount;
        }

    }
}

 
````

**Comment by vitek-karas** [comment]
>             //does not make sense to have to use ref: YET does not work without it.
>            Unload(weakRef,ref alc);  ///---- NEXT ISSUE WHY DOES THIS NOT WORK WITHOUT REF

Without the ref the local variable in the bit method still holds a reference to the ALC, even after the `Unload` method sets the parameter to `null`. Either pass it by ref as you do here, or just assign null in the parent method and only pass the weak ref to the `Unload`.

>            //<--- NEXT ISSUE - this now doesnt release commented out for now
>           //  var baseResponse = await ValidateAndProcessPluginAsync(alc, request);

Hard to tell why - but maybe something in the method holds on to the ALC. If you need to debug this, there's a guide on how to do that here: https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability

As for the PDB locking - you could use tools like `ProcessExplorer` or similar to determine which other process is holding onto the file.

**Comment by Seabizkit** [comment]
@vitek-karas 
So i have since re-worked my stuff, -mainly I fixed not marking shared libs as private to the lib.

but now I have what I consider two identical plugins, identical in the way they are constructed and consumed.

1 can delete the pdb and the other can not which makes little sense.
i used ProcessExplorer to see if it sheds any light
![image](https://user-images.githubusercontent.com/1920090/157462350-c7d51c58-41ba-4956-bcef-2c8e0b4958de.png)

```
[MethodImpl(MethodImplOptions.NoInlining)]
public async Task<PluginUploadResponse> UploadPluginAsync(
    ICurrentUser currentUser, int orgId, PluginUploadRequest request)
{

    var response = new PluginUploadResponse();

    //put the file in temp location
    string unquieNamePath = await _fileHelper.SaveFileToTempAsync(request.Data,request.FileName);

    string currentDirectory = Path.GetDirectoryName(unquieNamePath);
    //unzip the file
    var pluginComponentFolder = Path.Combine(currentDirectory, Path.GetFileNameWithoutExtension(unquieNamePath));

    //unique folder
    if (Directory.Exists(pluginComponentFolder))
    {
        //delete it, just incase it exists
        Console.WriteLine("Directory exists deleting it");
        Directory.Delete(pluginComponentFolder, true);
    }

    ZipFile.ExtractToDirectory(unquieNamePath, pluginComponentFolder, true);

    //Hack as loaded PDB files don't unload
    //  PluginHelper.DeletePdbFilesFromFolder(pluginComponentFolder);

    var baseResponse =  await ProcessPluginAsync(unquieNamePath, pluginComponentFolder, request);
    Unload(baseResponse.WeakRef);
    if (!baseResponse.WeakRef.IsAlive)
    {
        var res = PluginHelper.DeleteTempFileAndFolder(pluginComponentFolder, unquieNamePath);
        response.Merge(res);
    }
    else
    {
        response.AddError("Could not delete temp files");
    }
    return response;
}
```

with both plugins i get into if `(!baseResponse.WeakRef.IsAlive)` block so it attempts to delete the files...
but 1 plugin succeeds and the other fails saying it cant delete the pdb.... 

what interesting is doing the upload again without restarting app, it then is fine.
my assumption is that its now happy its loaded into something,
 but what's odd is it doesn't do this with the other plugin.

Also WeakRef implies its done, quite frustrating i wish there were more hooks so you could say when unloaded, say what was unloaded or something like that so its easier to understand what is or is not happening.

**Comment by vitek-karas** [comment]
Based on the fact that the files are locked by VS this feels more on the debugger side of things. @tommcdon any idea who to ask about this?

I don't have a clear idea why one plugin works and the other doesn't - it could be that the debugger didn't have a reason to load symbols for one, while it did have a reason for the other (just guessing, but maybe if one throws an exception and the other doesn't for example, ...). I don't even know if the debugger is supposed to NOT lock the PDBs when debugging...

**Comment by Seabizkit** [comment]
can confirm locally changing vs to release and it works, but not ideal when your trying to get stuff working

**Comment by tommcdon** [comment]
> Based on the fact that the files are locked by VS this feels more on the debugger side of things. @tommcdon any idea who to ask about this?

Adding @gregg-miskelly

**Comment by agocke** [comment]
Closing as this is on the VS side.
