### ISSUE TITLE
API proposal: string.SubstringUntil/string.SubstringAfter

### ISSUE THREAD

**Issue by Tyrrrz** [dotnet/runtime#661]
Proposal to add 4 new APIs as extensions to the `string` class:

```c#
public static string SubstringUntil(this string s, string sub,
    StringComparison comparison = StringComparison.Ordinal);

public static string SubstringAfter(this string s, string sub,
    StringComparison comparison = StringComparison.Ordinal);

public static string SubstringUntilLast(this string s, string sub,
    StringComparison comparison = StringComparison.Ordinal);

public static string SubstringAfterLast(this string s, string sub,
    StringComparison comparison = StringComparison.Ordinal);
```

These methods would work by searching for the first (or last in case with `...Last` methods) occurrence of the string `sub` in the string `s` and return the substring before that occurrence (or after).

Example usages:

```c#
var a = "name = value";

var name = a.SubstringUntil("=").Trim(); // "name"
var value = a.SubstringAfter("=").Trim(); // "value"
```

```c#
var a = "foo;bar;pipe";

// Get the text in the middle
var bar = a.SubstringUntilLast(";").SubstringAfter(";"); // "bar"
```

This API provides a more straightforward approach for some basic parsing needs.

Example implementation:

https://github.com/Tyrrrz/Extensions/blob/a42e1f5d729fa50fee51562e46b5b09f5dc3f31b/Tyrrrz.Extensions/StringExtensions.cs#L172-L242

**Comment by DaZombieKiller** [comment]
If this is added, I think it would be important to offer `Span`-based versions too.

**Comment by BhaaLseN** [comment]
Small nit: XSLT has functions `substring-before` and `substring-after`. It might be nicer to name it `SubstringBefore` instead of `SubstringUntil`.

**Comment by Clockwork-Muse** [comment]
`Before` also makes it more explicit that the bound is exclusive.

**Comment by GrabYourPitchforks** [comment]
Related: https://github.com/dotnet/corefx/issues/33543 and [`Utf8String.TryFind`](https://source.dot.net/System.Private.CoreLib/R/03e37f720840839a.html). If we exposed the latter `TryFind` method on `string` and `ROS<char>` then writing the `Substring*` methods proposed here would be very straightforward.

**Comment by stephentoub** [comment]
What benefit does the proposed API have over just using IndexOf to find the substring?  The cited examples don't motivate me.
1) They all involve a single punctuation character.  Searching as a string, and with optional cultural sensitivity, is unnecessary.
2) They're duplicating work, e.g. in:
```C#
var name = a.SubstringUntil("=").Trim(); // "name"
var value = a.SubstringAfter("=").Trim(); // "value"
```
it's going to search for the same '=' twice, once as part of each call.  It'd be better to do the search for '=' once, and then split the results based on that position.  And e.g. in:
```C#
var bar = a.SubstringUntilLast(";").SubstringAfter(";"); // "bar"
```
it's creating an unnecessary intermediate string when it could have used {Last}IndexOf to find the first ';' and then again for the next.

I suggest this be closed.

**Comment by Tyrrrz** [comment]
> What benefit does the proposed API have over just using IndexOf to find the substring? The cited examples don't motivate me.

The only benefit is that combining `IndexOf` with `Substring` is a bit cumbersome as it requires two separate statements/assignments:

```csharp
var str = "foo-bar-baz";

// Statement 1: get index
var i = str.IndexOf("-bar-");

// Statement 2: get substring
var s = i > 0 ? str.Substring(0, i) : s;
```

This can be mashed together if you abuse pattern matching like so:

```csharp
var s = str.IndexOf("-bar-") is > 0 and {} i ? str.Substring(0, i) : s;
```

But that's pretty ugly in my opinion.

My most common use case for these functions is splitting a string based on a separator (which is a lot of times a single character, as you pointed out). Sometimes I only need only one side of the string (e.g. only the key, or only the value, in a key-value pair), sometimes both.

If `string.Split(...)` could return a tuple, this would make these methods unnecessary since we'd be able to do something like this:

```csharp
// Or discard whichever side of the tuple you don't need
var (name, value) = str.SplitOnFirst("=");
```

**Comment by stephentoub** [comment]
> The only benefit is that combining IndexOf with Substring is a bit cumbersome as it requires two separate statements/assignments

Thanks.  I don't think this is enough value to warrant introducing additional APIs, and I think these would also lead people down the path of writing code that's more expensive than it should be (see my previous comments).

**Comment by tannergooding** [comment]
Closing this based on the feedback above.
