### ISSUE TITLE
Tests.proj doesn't filter to best TargetFramework when running Test target  

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#66122]
This results in the build only building for the best TargetFramework, but the Test Target running for all TargetFrameworks, which fails because none of the tests are built for those frameworks.  For example:
```
Exec
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    CommandLineArguments = "D:\git\runtime_reflection2\artifacts\bin\Microsoft.Extensions.Logging.Console.Tests\Debug\net462\RunTests.cmd"
    Parameters
        Command = "D:\git\runtime_reflection2\artifacts\bin\Microsoft.Extensions.Logging.Console.Tests\Debug\net462\RunTests.cmd"
        IgnoreExitCode = True
        IgnoreStandardErrorWarningFormat = True
    ----- start Wed 03/02/2022 14:59:39.18 ===============  To repro directly: ===================================================== 
    pushd D:\git\runtime_reflection2\artifacts\bin\Microsoft.Extensions.Logging.Console.Tests\Debug\net462\
    xunit.console.exe Microsoft.Extensions.Logging.Console.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing 
    popd
    ===========================================================================================================
    'xunit.console.exe' is not recognized as an internal or external command,
    operable program or batch file.
    ----- end Wed 03/02/2022 14:59:39.22 ----- exit code 9009 ----------------------------------------------------------
    The command ""D:\git\runtime_reflection2\artifacts\bin\Microsoft.Extensions.Logging.Console.Tests\Debug\net462\RunTests.cmd"" exited with code 9009.
    OutputProperties
        TestRunExitCode = 9009

D:\git\runtime_reflection2\eng\testing\tests.targets(142,5): One or more tests failed while running tests from 'Microsoft.Extensions.Logging.Console.Tests'. [D:\git\runtime_reflection2\src\libraries\Microsoft.Extensions.Logging.Console\tests\Microsoft.Extensions.Logging.Console.Tests\Microsoft.Extensions.Logging.Console.Tests.csproj]
```

This regressed with https://github.com/dotnet/runtime/commit/9ebe0efa4850fb2e451befe1fdf7c2d3cbb5c862#diff-5ef2fd16f58de91bff2f05ad601ab6ff000c0febabb2312d232f20cfa132a71b in https://github.com/dotnet/runtime/pull/64000

This change made `tests.proj` switch from using the `buildMultiTargeting` to `build` targets in  https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.Build.Tasks.TargetFramework/src 

The `buildMultiTargeting` targets [use](https://github.com/dotnet/arcade/blob/d2944552c22b9ec91a8d120ccf4436c516327356/src/Microsoft.DotNet.Build.Tasks.TargetFramework/src/buildMultiTargeting/Microsoft.DotNet.Build.Tasks.TargetFramework.targets#L50)`AdditionalProperties` to apply the best target framework, whereas the `build` targets [use](https://github.com/dotnet/arcade/blob/d2944552c22b9ec91a8d120ccf4436c516327356/src/Microsoft.DotNet.Build.Tasks.TargetFramework/src/ChooseBestP2PTargetFrameworkTask.cs#L61) `SetTargetFramework`.

The MSBuild Traversal SDK's `Build` Target [honors](https://github.com/microsoft/MSBuildSdks/blob/e32b6ab93e48c4deac17d05fd487d2859c5c27a7/src/Traversal/Sdk/Sdk.targets#L140) `SetTargetFramework` while the `Test` target [does not](https://github.com/microsoft/MSBuildSdks/blob/e32b6ab93e48c4deac17d05fd487d2859c5c27a7/src/Traversal/Sdk/Sdk.targets#L175-L186).  This is why the test target ends up running for all target frameworks.

As a workaround for folks that hit this try adding the following to tests.proj.
```xml
  <Target Name="WorkaroundIssue66122" BeforeTargets="Test">
    <ItemGroup>
      <ProjectReference Condition="'%(ProjectReference.SetTargetFramework)' != ''" 
                        AdditionalProperties="%(ProjectReference.AdditionalProperties);TargetFramework=%(ProjectReference.SetTargetFramework)" />
    </ItemGroup>
  </Target>
```

**Comment by ericstj** [comment]
@ViktorHofer not asking you to fix this, but what do you think the right fix should be for this?  Should we make a change to the traversal SDK, add a target to `tests.proj`, or something else?

**Comment by steveharter** [comment]
@ericstj the workaround appears to have some of the tests attempt to execute the assembly directly:
```
  ----- start Thu 03/03/2022  9:22:43.78 ===============  To repro directly: =====================================================
  pushd C:\git\runtime\artifacts\bin\System.DirectoryServices.AccountManagement.Tests\Debug\
  System.DirectoryServices.AccountManagement.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing
  popd  ----- end Thu 03/03/2022  9:22:43.78 ----- exit code 9009 ----------------------------------------------------------
```

**Comment by ericstj** [comment]
I'll give things a try locally and see if I can provide a better workaround.  Alternatively you could also try to apply @ViktorHofer's [change](https://github.com/microsoft/MSBuildSdks/commit/d72c0f264b847f844cf90f31517c5cff6e743230) manually to `C:\Users\<userName>\.nuget\packages\microsoft.build.traversal\3.1.3\Sdk\Sdk.targets` would have the added benefit of testing it.

**Comment by steveharter** [comment]
The linked PR fixes the issue (applied the changes locally to my `Sdk.targets`).
