### ISSUE TITLE
[API Proposal]: Add ServiceCollection.MakeReadOnly()

### ISSUE THREAD

**Issue by halter73** [dotnet/runtime#66126]
### Background and motivation

The new `HostApplicationBuilder` in Microsoft.Extensions.Hosting and the MAUI host both implement custom `IServiceCollection` that change to read-only after the host is built. This means that `ICollection<ServiceDescriptor>.IsReadOnly` becomes true and any attempts to mutate the collection result in an `InvalidOperationException`. This makes it clear to developers that any attempt to modify services at this point is futile.

It would be nice if these hosts could use the default `ServiceCollection` to take advantage of potential perf improvements like those described in #44728.

### API Proposal

```diff
namespace Microsoft.Extensions.DependencyInjection
{
    public class ServiceCollection
    {
+      public void MakeReadOnly();
    }
}
```

### API Usage

```C#
public ServiceCollection ServiceCollection { get; } = new();

IHost Build()
{
    // BuildServiceProvider() is an extension method on IServiceProvider so it cannot
    // make the ServiceCollection read-only itself. It could after this change if it attempted to cast,
    // but that would be a breaking change and is not what I'm proposing.
    IServiceProvidier serviceProvider = ServiceCollection.BuildServiceProvider();
    ServiceCollection.MakeReadOnly();
    return serviceProvider.GetRequiredService<IHost>();
}
```

### Alternative Designs

```diff
namespace Microsoft.Extensions.DependencyInjection
{
    public class ServiceCollection
    {
-      public bool IsReadOnly { get; }
+      public bool IsReadOnly { get; set; }
    }
}
```

I considered adding a setter to `IsReadOnly`, but I don't think it should be possible to transition a `ServiceCollection` from a read-only to a mutable state.

### Risks

It adds additional API to `ServiceCollection` that shouldn't be called by the majority of developers interacting with the type. It's only really useful to library authors who build the `ServiceCollection`.

Context: https://github.com/dotnet/runtime/pull/65109#discussion_r817148779

@eerhardt

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace Microsoft.Extensions.DependencyInjection;

public partial class ServiceCollection
{
    public void MakeReadOnly();
}
```
