### ISSUE TITLE
HttpClient throws exception with message "The proxy tunnel request to proxy 'xxx' failed with status code '407'."'" instead of returning a response with ProxyAuthenticationRequired

### ISSUE THREAD

**Issue by alixiashu** [dotnet/runtime#66133]
# Description

When I try to migrate my .net core 3 app to .net 6, I got some bug caused by the HttpClient.
Here is it. When I try to call a **https** (not a http) URL through a **proxy** but **without a proxy credential**, in .net core3, we would get a response with status code 407 (ProxyAuthenticationRequired), but in .net core, it will directly throw an exception with message "The proxy tunnel request to proxy 'xxx' failed with status code '407'.". I want to know that it is by design or a bug.

# Repro info
1. Windows 11 Enterprise 21H2 22000.493
2. visual studio 2022
3. SDK 6.0.200; runtim Microsoft.WindowsDesktop.App 6.0.2
4. test code
    ``` 
        private static string _url = "https://www.contoso.com";
        public static async Task Main()
        {
             try
              {
                  using (var _client = new HttpClient())
                  {
                      var response = await _client.GetAsync(_url);
  
                      Console.WriteLine(await response.Content.ReadAsStringAsync());
                  }
              }
              catch (HttpRequestException ex)
              {
                  Console.WriteLine(ex.Message);
              }
          }

# tips
1. This issue only happens with https request as I mentioned, it works well for HTTP request.

**Comment by MihaZupan** [comment]
> I want to know that it is by design or a bug

This was a deliberate change in behavior in .NET 6 (#48679) to avoid returning a response from the proxy if it could be ambiguous whether it came from the proxy (cleartext) or the actual destination (over HTTPS).

Please take a look at #65305 (similar report) and comment on the issue with more information if having access to the actual `HttpResponseMessage` is something you need, or if the current exception info is sufficient.

**Comment by alixiashu** [comment]
Thanks for the reply, will add another comment in https://github.com/dotnet/runtime/issues/65305.
