### ISSUE TITLE
[Question] MemoryStream Dispose() behavior

### ISSUE THREAD

**Issue by En3Tho** [dotnet/runtime#66136]
There is a comment in MemoryStream which states that Close() is expected to be called.

``` csharp
protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing)
                {
                    _isOpen = false;
                    _writable = false;
                    _expandable = false;
                    // Don't set buffer to null - allow TryGetBuffer, GetBuffer & ToArray to work.
                    _lastReadTask = default;
                }
            }
            finally
            {
                // Call base.Close() to cleanup async IO resources // <- this one
                base.Dispose(disposing);
            }
        }
```

But in code of Stream it is not actually called:
``` csharp
        public void Dispose() => Close();

        public virtual void Close()
        {
            // When initially designed, Stream required that all cleanup logic went into Close(),
            // but this was thought up before IDisposable was added and never revisited. All subclasses
            // should put their cleanup now in Dispose(bool).
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing) // <- MemoryStream's base call here won't suppress finalization it seems
        {
            // Note: Never change this to call other virtual methods on Stream
            // like Write, since the state on subclasses has already been
            // torn down.  This is the last code to run on cleanup for a stream.
        }
```

So I guess using (disposing) MemoryStream or not, it's finalization won't get suppressed if Close() isn't called, am I right?

If this is by design then I propose changing the comment.
If it's not then it needs to be changed somehow.

**Comment by adamsitnik** [comment]
Hi @En3Tho 

You are right, the comment was wrong. Moreover, we don't really need to call `base.Dispose` from `MemoryStream` as the base implementation does nothing:

https://github.com/dotnet/runtime/blob/8dcfacbdec618924f36a95688173a7c1c101592f/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L169-L174

> So I guess using (disposing) MemoryStream or not, it's finalization won't get suppressed if Close() isn't called, am I right?

Both `Stream` and `MemoryStream` don't define a finalizer.

In case someone implements a custom type that derives from `MemoryStream` and adds a finalizer then the finalizer is going to be suppressed on call to `Dispose()` and `Close` as long as the developer does not override `Stream.Close` and forgets to call the `base.Close` from it:

https://github.com/dotnet/runtime/blob/8dcfacbdec618924f36a95688173a7c1c101592f/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L160-L167

Invalid:

```cs
public class InvalidCustomStream : Stream
{
   ~InvalidCustomStream() { }

   public override void Close()
   {
      // no call to base.Close
   }
}
```

**Comment by En3Tho** [comment]
@adamsitnik I see. Thank you for clarification. Feel free to close this.
