### ISSUE TITLE
Potential for optimizing the ValueTask.Preserve method

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#66172]
Recently I had to use the [`ValueTask.Preserve`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.valuetask.preserve) method, for the implementation of a custom LINQ operator for `IAsyncEnumerable<T>` sequences (for preserving the `MoveNextAsync` task). I noticed that the `Preserve` is not optimized for the case below:

1. The `ValueTask<bool>` is not completed upon creation.
2. The `ValueTask<bool>`  has completed successfully at the moment that the `Preserve` is called.

It seems that there is potential for optimizing this case, by avoiding the allocation of a `Task<bool>` wrapper. So I wrote the extension method below, and I used it in place of the `Preserve`:

```C#
public static ValueTask<T> PreserveLight<T>(ValueTask<T> source) =>
    source.IsCompletedSuccessfully ?
        new ValueTask<T>(source.Result) : source.Preserve();
```
I would like to ask if this optimization is correct, or I have placed a bomb under the foundations of my custom LINQ operator.

In case it is correct, I would also like to ask if it makes any sense for this optimization to be incorporated in the built-in `ValueTask.Preserve` method.

**Comment by stephentoub** [comment]
Are you actually seeing a `Task<bool>` being allocated in the scenario you outline? I wouldn't expect that to be the case.

**Comment by theodorzoulias** [comment]
Hi @stephentoub! I am using .NET 6 in Release mode. You are right, preserving a `ValueTask<bool>` is allocation free. I did my allocation measurements with `ValueTask<int>` though, and there is a difference. Here is a demo:

```C#
using System;
using System.Threading.Channels;
using System.Threading.Tasks;

public static class Program
{
    public static void Main()
    {
        var channel = Channel.CreateUnbounded<int>();
        var count = 1000;
        var tasks = new ValueTask<int>[count];
        for (int i = 0; i < count; i++) tasks[i] = channel.Reader.ReadAsync();
        for (int i = 0; i < count; i++) channel.Writer.TryWrite(i);
        var mem0 = GC.GetTotalAllocatedBytes(true);
        for (int i = 0; i < count; i++) tasks[i] = tasks[i].Preserve();
        //for (int i = 0; i < count; i++) tasks[i] = tasks[i].PreserveLight();
        var mem1 = GC.GetTotalAllocatedBytes(true);
        Console.WriteLine($"Allocated bytes per item: {(mem1 - mem0) / (double)count:#,0}");
    }

    public static ValueTask<T> PreserveLight<T>(this ValueTask<T> source) =>
        source.IsCompletedSuccessfully ?
            new ValueTask<T>(source.Result) : source.Preserve();
}
```

Output with `Preserve`:

```none
Allocated bytes per item: 72
````

Output with `PreserveLight`:

```none
Allocated bytes per item: 0
```

[Live demo](https://dotnetfiddle.net/jM0ra5)

I am creating the `ReadAsync` tasks first and write values in the channel later, otherwise the `ValueTask`s are just wrapping a simple value, and both the `Preserve` and the `PreserveLight` are not allocating anything.

**Comment by stephentoub** [comment]
> You are right, preserving a ValueTask<bool> is allocation free. I did my allocation measurements with ValueTask<int> though, and there is a difference

Yes, it's because the allocation-free-ness comes from Task.FromResult returning a singleton for each of true/false.  If your Int32 value were small, like <= 8, you'd also see that allocation go away, as such objects are also cached by Task.FromResult.

As for extending it, we could as long as we were careful not to make any additional interface calls, which accessing IsCompletedSuccessfully would do.  So we'd need to restructure a variety of things and duplicate some code, in order to save an allocation that only happens for some Ts and as part of a method that's typically not used on hot-paths, and in order to provide an optimization that the caller themselves can do if they think it's likely to complete synchronously and be backed by an IValueTaskSource.

**Comment by theodorzoulias** [comment]
I agree. My actual use case is about `ValueTask<bool>`, which is covered by the true/false singletons, and for other types admittedly it should be pretty rare to not `Preserve` a `ValueTask<T>` immediately after its creation. So I am closing this issue too. :-)
