### ISSUE TITLE
System.Text.Json ReferenceHandler.IgnoreCycles

### ISSUE THREAD

**Issue by Jackie-L** [dotnet/runtime#66187]
### Description

In.net6, circular references are ignored during serialization, resulting in unwanted [NULL], making front-end and back-end interactions difficult

### .net6.0 A Console application 

```
using System.Text.Json;
using System.Text.Json.Serialization;

static void WriteIgnoringReferenceLoops()
{
    var bob = new Employee { Name = "Bob" };
    var angela = new Employee { Name = "Angela" };

    angela.Manager = bob;
    bob.Subordinates = new List<Employee> { angela };

    var options = new JsonSerializerOptions
    {
        ReferenceHandler = ReferenceHandler.IgnoreCycles,
        WriteIndented = true,
    };

    string json = JsonSerializer.Serialize(angela, options);
    Console.Write(json);
}

WriteIgnoringReferenceLoops();

public class Employee
{
    public string Name { get; set; }
    public Employee Manager { get; set; }
    public List<Employee> Subordinates { get; set; }
}
```

### Expected behavior

`{
  "Name": "Angela",
  "Manager": {
    "Name": "Bob",
    "Manager": null,
    "Subordinates": []
  },
  "Subordinates": null
}`

### Actual behavior

`{
  "Name": "Angela",
  "Manager": {
    "Name": "Bob",
    "Manager": null,
    "Subordinates": [
      null
    ]
  },
  "Subordinates": null
}`

### Regression?

Right behavior
https://github.com/dotnet/runtime/issues/30820

### Configuration

.net6.0
win10 x64

**Comment by eiriktsarpalis** [comment]
It would seem like this is by-design behavior, as witnessed by the following unit tests:

https://github.com/dotnet/runtime/blob/b90b4649001de0f45600dd0d867fa4400801fbd4/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/ReferenceHandlerTests.IgnoreCycles.cs#L166-L220

This differs from the semantics of Newtonsoft, which skips cyclic nodes altogether on collections. It's unfortunate but at this point changing it would constitute a breaking change.

cc @Jozkee
