### ISSUE TITLE
An exception is thrown when getting PrinterSettings.InstalledPrinters

### ISSUE THREAD

**Issue by Lydia-Shi** [dotnet/runtime#66186]
### Description

An exception is thrown when getting PrinterSettings.InstalledPrinters

### Reproduction Steps

1.	Create a Console .NET Core application, add reference: System.Drawing.Common.dll 
2.	Add below code in Program.cs:
```
System.Drawing.Printing.PrintDocument print = new System.Drawing.Printing.PrintDocument();
string sDefault = print.PrinterSettings.PrinterName;
var sPrint = PrinterSettings.InstalledPrinters;
```
 
3.	Build and run

### Expected behavior

No exception is thrown.
![image](https://user-images.githubusercontent.com/54019172/156739439-6404f70d-728a-4901-9c62-cbcdc9314c10.png)

### Actual behavior

An exception is thrown.
![image](https://user-images.githubusercontent.com/54019172/156738770-f0138fb3-c3f3-4be9-852c-8d278d4cb299.png)

**Call stack:**
```
   at Interop.Winspool.<EnumPrinters>g____PInvoke__|3_0(Int32 flags, Void* name, Int32 level, IntPtr pPrinterEnum, Int32 cbBuf, Int32* pcbNeeded, Int32* pcReturned)
   at Interop.Winspool.EnumPrinters(Int32 flags, String name, Int32 level, IntPtr pPrinterEnum, Int32 cbBuf, Int32& pcbNeeded, Int32& pcReturned)
   at System.Drawing.Printing.PrinterSettings.get_InstalledPrinters()
   at Program.<Main>$(String[] args) in C:\Users\v-qiashi\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 9
```

### Regression?

Yes, this is a regression issue and cannot repro in 7.0.100-preview.3.22152.16.

### Configuration

.NET 7.0.100-preview.3.22153.22

**Comment by dreddy-work** [comment]
@JeremyKuhne , do you know who the right person would be to look into this? it is blocking WinForms automation tests.

**Comment by Olina-Zhang** [comment]
@JeremyKuhne , @jkoritzinsky @elinor-fung This issue still repro in the latest .Net 7.0 build: 7.0.100-preview.4.22173.7 from main branch. Can you take a look?

**Comment by elinor-fung** [comment]
Sorry, I somehow missed seeing this last week. https://github.com/dotnet/runtime/pull/67081 should fix this.

**Comment by Amy-Li03** [comment]
Verified this issue on .NET SDK 7.0.100-preview.4.22201.8, it was fixed, no exception was thrown when getting PrinterSettings.InstalledPrinters.

![image](https://user-images.githubusercontent.com/62929087/161374164-724a85b7-6b16-4e5e-8cf3-0145268c8302.png)
