### ISSUE TITLE
What method can be used to automatically know whether this package supports the actual installed platform?

### ISSUE THREAD

**Issue by Smartisa** [dotnet/runtime#66181]
What method can be used to automatically know whether this package supports the actual installed platform?
For example:[[System.Runtime.Loader](https://www.nuget.org/packages/System.Runtime.Loader/)]. it indicates that it supports the framework, but it does not support the framework. How can we use automation to know whether it supports the framework? [There are also indirect references to System.runtime.loader](https://www.nuget.org/packages/FSharp.Compiler.Service/). How do you know if the loader package supports other frameworks.
Links to related questions:
[System.Runtime.Loader not copied to output directory](https://github.com/dotnet/runtime/issues/22732#issuecomment-416138808)
[Proposal: Unlist and deprecate the System.Runtime.Loader NuGet package](https://github.com/dotnet/runtime/issues/38503)

**Comment by teo-tsirpanis** [comment]
Answered in https://github.com/dotnet/runtime/issues/38503#issuecomment-1059050900.
