### ISSUE TITLE
JsonSerializer should support named member tuples

### ISSUE THREAD

**Issue by Saalvage** [dotnet/runtime#66199]
Currently when (de-)serializing, the `ItemN` property names of tuples are used exlusively, despite the fact that in the case of named tuple members the names given to the tuple items can be identified via `TupleElementNamesAttribute`.

### Example:
```cs
record MyRecord(bool MyBool, (string A, string B, string C)[] Tuples);
```
```json
{
    "MyBool": true,
    "Tuples": [
        { "A": "foo", "Item2": "bar", "C": "foobar" }
    ]
}
```
In the above example only `MyBool` and the tuple item `B` will be deserialized correctly and only if `IncludeFields` is specified in the `JsonSerializerOptions`, the other items will be `null`.

### Configuration:

This change would likely include the introduction of a new option in `JsonSerializerOptions` that dictates the handling of named member tuples. I'd imagine the three available options would be forcing the json names to be the actual tuple names, accepting both forms (default) and forcing json names to be of the form `ItemN`. Due to the symmetry of options for serialization and deserialization as well as  for the sake of backwards compatibility the default option should likely serialize to `ItemN`, which is sad, since the opposite is clearly the more intuitive policy.

If this proposal seems reasonable and creates interest I would like try and write up a PR for it! :)

**Comment by eiriktsarpalis** [comment]
See my comment in https://github.com/dotnet/aspnetcore/issues/40510#issuecomment-1058007984 concerning the same request. TL;DR the `TupleElementNamesAttribute` only applies to properties and not the ValueTuple types themselves. Converters are scoped to types and as such are oblivious of any property-level metadata.

While it might be possible to knock together an internal converter that fetches tuple names from the ambient property metadata, this can only work if the tuple in question is nested within another type, resulting on inconsistent serialization contracts depending on context:
```C#
var myTuple = (foo: 42, bar: -1);
JsonSerializer.Serialize(myTuple, optionsWithIncludeFields); // { "Item1" : 42, "Item2" : -1 } since serializer has no access to label metadata
JsonSerializer.Serialize(new { Tuple = myTuple }); // { "foo" : 42, "bar" : -1 } relevant labels retrieved from ambient class metadata
```
As such, I don't think we should try to implement this unless this metadata could somehow be recovered from the `Type` instance in the future.

**Comment by Saalvage** [comment]
Inconsistency is definitely an argument I forgot to consider! I agree that in light of that a change like this shouldn't go ahead.
Such a shame that tuple item names aren't associated with the type itself!
