### ISSUE TITLE
JSONSourceGenerator: JsonSerializerContext requiring implementing all functions in partial class

### ISSUE THREAD

**Issue by greyhoundgames** [dotnet/runtime#66203]
### Description

I am seeing a problem I found described back last August in issue 
#57579 JSON source generator fails to compile when providing the full name of serializable class

I have two projects that are AWS Lambda applications. I switched to .net 6 and thus visual studio 2022 (Version 17.1.0) this week on both projects and implemented this new feature (JSONSourceGenerator for request objects) for our requests. On one project, it compiles fine. The exact same code copy and pasted on the other project produces the following errors

Error	CS0534	'GenJsonSerialization' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'
Error	CS0534	'GenJsonSerialization' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'options' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)'

The code is as shown below.
namespace MyNamespace
{
  [JsonSerializable(typeof(APIGatewayHttpApiV2ProxyRequest))]
  [JsonSerializable(typeof(APIGatewayProxyResponse))]
  public partial class GenJsonSerialization : JsonSerializerContext
  {
  }

I have tried making the using statements match between the 2 files in the different projects because the other bug report mentioned that, but no luck. I have tried cleaning the project. I tried deleting the bin and obj folders. No luck.

When I inspect JsonSerializerContext on both projects, they are pointing to the same folder for the DLL they come from. Both these projects are on the same computer.

### Reproduction Steps

This is a random thing so I don't know how to reproduce it.

### Expected behavior

It should compile

### Actual behavior

It gives the errors listed.

**Comment by krwq** [comment]
@greyhoundgames I was trying to reproduce it but I'm unable to. Can you show your .csproj file in the project where you're seeing the issue? Are you using `net6.0` in there?

**Comment by greyhoundgames** [comment]
Hey. Sorry I missed your initial reply. So I went to reproduce this again in the same 2 projects and now the error is not showing up.. I guess we can close this and I will re-open if it comes back again. 
Thanks.

**Comment by greyhoundgames** [comment]
This problem has shown up again after no specific change to the file in question. I tried clearing out my bin and obj folders but it did not help. Specifc error is copy and pasted below (3 errors).

For reference the project file is attached and the code is:
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.SourceGeneratorLambdaJsonSerializer<EvertaleLambda.GenJsonSerialization>))]

namespace EvertaleLambda
{
  [JsonSerializable(typeof(APIGatewayHttpApiV2ProxyRequest))]
  [JsonSerializable(typeof(APIGatewayProxyResponse))]
  [JsonSerializable(typeof(APIGatewayCustomAuthorizerRequest))]
  [JsonSerializable(typeof(APIGatewayProxyRequest))]

  public partial class GenJsonSerialization : JsonSerializerContext
  {
  }
.....
}

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest.ProxyRequestClientCert' to 'Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest.ProxyRequestClientCert?'	EvertaleLambdaSlim	C:\Users\Tom\wkspaces\Evertale_PrevVer\EvertaleServer\EvertaleLambdaSlim\EvertaleLambdaSlim\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GenJsonSerialization.RequestIdentity.g.cs	356	Active
Error	CS1503	Argument 2: cannot convert from 'Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest.ProxyRequestContext' to 'Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest.ProxyRequestContext?'	EvertaleLambdaSlim	C:\Users\Tom\wkspaces\Evertale_PrevVer\EvertaleServer\EvertaleLambdaSlim\EvertaleLambdaSlim\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GenJsonSerialization.APIGatewayCustomAuthorizerRequest.g.cs	276	Active
Error	CS1503	Argument 2: cannot convert from 'Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest.ProxyRequestContext' to 'Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest.ProxyRequestContext?'	EvertaleLambdaSlim	C:\Users\Tom\wkspaces\Evertale_PrevVer\EvertaleServer\EvertaleLambdaSlim\EvertaleLambdaSlim\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GenJsonSerialization.APIGatewayProxyRequest.g.cs	318	Active
[EvertaleLambdaSlim.zip](https://github.com/dotnet/runtime/files/8542772/EvertaleLambdaSlim.zip)

**Comment by krwq** [comment]
I'm wondering if this isn't some variant of `Nullable<T>` issues with source gen (similar to https://github.com/dotnet/runtime/issues/70475)

**Comment by EgorBo** [comment]
It seems I've just hit the same issue 😕 
![image](https://user-images.githubusercontent.com/523221/216794170-4ab88d64-113b-445a-925a-cd61c975b80a.png)

**Comment by EgorBo** [comment]
Clean/rebuild didn't help but then at some point it just fixed itself without changes 😐

**Comment by eiriktsarpalis** [comment]
Did the issue manifest in the CLI at all or was it only occurring in the IDE?

**Comment by EgorBo** [comment]
> Did the issue manifest in the CLI at all or was it only occurring in the IDE?

For me - only in IDE

**Comment by eiriktsarpalis** [comment]
The errors are indicative of the source generator not having run -- so maybe something was preventing it from running temporarily.
