### ISSUE TITLE
Assertion failed 'comp->supportSIMDTypes()'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#66206]
Many tests in "runtime-coreclr jitstress-isas-x86" pipeline, job "CoreCLR OSX x64 Checked jitstress_isas_nosimd" fail, e.g., JIT/Methodical/NaN/r8NaNdiv_cs_do/r8NaNdiv_cs_do.sh:

```
Assert failure(PID 19764 [0x00004d34], Thread: 722343 [0xb05a7]): Assertion failed 'comp->supportSIMDTypes()' in 'r8NaNdiv:d_test2_f(System.String):double' during 'Rationalize IR' (IL size 33; hash 0xcd8ee9f9; FullOpts)

File: /Users/runner/work/1/s/src/coreclr/jit/rationalize.cpp Line: 781
Image: /private/tmp/helix/working/A85C0927/p/corerun
task_for_pid(19764) FAILED 5 (os/kern) failure
/private/tmp/helix/working/A85C0927/w/AA01093A/e/JIT/Methodical/NaN/r8NaNdiv_cs_do/r8NaNdiv_cs_do.sh: line 379: 19764 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A85C0927/w/AA01093A/uploads/Reports/JIT.Methodical/NaN/r8NaNdiv_cs_do/r8NaNdiv_cs_do.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A85C0927/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false r8NaNdiv_cs_do.dll ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A85C0927/p
/private/tmp/helix/working/A85C0927/w/AA01093A/e/JIT/Methodical/NaN/r8NaNdiv_cs_do/r8NaNdiv_cs_do.sh
Expected: True
Actual:   False
```

@tannergooding @dotnet/jit-contrib

**Comment by tannergooding** [comment]
It's probably worth removing the `COMPlus_EnableSIMD=0` switch. It doesn't exist/work for ARM64 and the code has been in long enough for x86/x64 that it's extremely well tested and so the original purpose for it doesn't really "exist" anymore. Additionally on Unix (and to an extent on x64 Windows) the support is "required" for ABI purposes to ensure types like `Vector128<T>` or HFAs/HVAs are correctly passed around.

Users still have the option of disabling individual ISAs or using the `COMPlus_EnableHWIntrinsic`, which would then leave on the general SIMD support.

@BruceForstall, @echesakovMSFT, thoughts?

**Comment by BruceForstall** [comment]
You understand the support matrix here much better than I, so I will defer to your judgement. My main concern would be that we should be able to test all the configurations that we support. If `COMPlus_EnableSIMD=0` doesn't improve our testability, then I'm fine to remove it.

**Comment by kunalspathak** [comment]
https://github.com/dotnet/runtime/pull/66670 fixes this.
