### ISSUE TITLE
[Crossgen2 / windows / arm64] JIT\Performance\CodeQuality\BenchmarksGame\regex-redux\regex-redux-5 AV's in the CoreCLR runtime

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#66210]
OS: **Windows**
Architecture: **arm64**

This is a rare bug - I found three repros in the last month. The last one is from JanK's testing of the generic exception fix, the middle one occurred during my testing of the Crossgen2 fix to only register code range once for composite image and the first one happened on 2/8 during testing of a library change.

The call stacks slightly vary so I'm attaching all three in the hope that their subtle differences may shed more light on the issue:

**First repro** - 20220208.1, https://dev.azure.com/dnceng/public/_build/results?buildId=1601744

<pre>
      Assert failure(PID 3768 [0x00000eb8], Thread: 8292 [0x2064]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! LookupMapBase::GetElementPtr + 0x0 (0x00007fff`a9552320)
      CORECLR! ClassLoader::LoadTypeDefOrRefThrowing + 0xB8 (0x00007fff`a956fbd0)
      CORECLR! SigPointer::GetGenericInstType + 0x348 (0x00007fff`a9641e98)
      CORECLR! SigPointer::GetTypeHandleThrowing + 0x878 (0x00007fff`a9642a80)
      CORECLR! ZapSig::DecodeType + 0x6C (0x00007fff`a9694e0c)
      CORECLR! LoadDynamicInfoEntry + 0x114 (0x00007fff`a95d1abc)
      CORECLR! Module::FixupNativeEntry + 0x6C (0x00007fff`a9550a5c)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007fff`a9695d44)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007fff`a9696ed4)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007fff`a9630ea0)
      CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007fff`a9630c78)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x25C (0x00007fff`a9632c74)
      CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007fff`a9632a0c)
      CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007fff`a9577460)
      CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007fff`a962e914)
      CORECLR! PreStubWorker + 0x3D4 (0x00007fff`a9635204)
      CORECLR! ThePreStub + 0x50 (0x00007fff`a9521214)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`a5714854)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`a570fcb0)
      -----
      .AV on tid=0x2064 (8292), cxr=00000058B9FFD730, exr=00000058B9FFDAC0
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2D0 (0x00007fff`a98fb4e8)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2F4 (0x00007fff`a95960cc)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007fff`a9595b64)
      CORECLR! CLRVectoredExceptionHandler + 0x16C (0x00007fff`a9595ad4)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x24C (0x00007fff`a959641c)
      NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007fff`da7cccb0)
      NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007fff`da78cdc4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007fff`da763434)
      CORECLR! LookupMapBase::GetElementPtr + 0x0 (0x00007fff`a9552320)
      CORECLR! ClassLoader::LoadTypeDefOrRefThrowing + 0xB8 (0x00007fff`a956fbd0)
          File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7581
          Image: D:\h\w\A14F0942\p\corerun.exe
</pre>

**Second repro** - 20220219.1, https://dev.azure.com/dnceng/public/_build/results?buildId=1622923

<pre>
      Assert failure(PID 8776 [0x00002248], Thread: 8272 [0x2050]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! MemberLoader::GetFieldDescFromMemberRefAndType + 0x18 (0x00007fff`963b4d90)
      CORECLR! ZapSig::DecodeField + 0x254 (0x00007fff`96452e6c)
      CORECLR! ZapSig::DecodeField + 0x24 (0x00007fff`96452efc)
      CORECLR! LoadDynamicInfoEntry + 0x12D8 (0x00007fff`96392900)
      CORECLR! Module::FixupNativeEntry + 0x6C (0x00007fff`9631077c)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007fff`96454a54)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007fff`96455be4)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007fff`963effa0)
      CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007fff`963efd78)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x2AC (0x00007fff`963f1dc4)
      CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007fff`963f1b0c)
      CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007fff`96337170)
      CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007fff`963eda14)
      CORECLR! PreStubWorker + 0x3D4 (0x00007fff`963f4344)
      CORECLR! ThePreStub + 0x50 (0x00007fff`962e1214)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`935dadec)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`935f999c)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`935f9d80)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`935f9ebc)
      -----
      .AV on tid=0x2050 (8272), cxr=000000B95073CDC0, exr=000000B95073D150
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2D0 (0x00007fff`966b9ca8)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2F4 (0x00007fff`96355ddc)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007fff`96355874)
      CORECLR! CLRVectoredExceptionHandler + 0x16C (0x00007fff`963557e4)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x24C (0x00007fff`9635612c)
      NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007fff`c736ccb0)
      NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007fff`c732cdc4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007fff`c7303434)
      CORECLR! MemberLoader::GetFieldDescFromMemberRefAndType + 0x18 (0x00007fff`963b4d90)
      CORECLR! ZapSig::DecodeField + 0x254 (0x00007fff`96452e6c)
          File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7581
          Image: D:\h\w\C0F00A04\p\corerun.exe
</pre>

**Third repro** - 20220304.1, https://dev.azure.com/dnceng/public/_build/results?buildId=1645287

<pre>
      Assert failure(PID 3768 [0x00000eb8], Thread: 8292 [0x2064]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! LookupMapBase::GetElementPtr + 0x0 (0x00007fff`a9552320)
      CORECLR! ClassLoader::LoadTypeDefOrRefThrowing + 0xB8 (0x00007fff`a956fbd0)
      CORECLR! SigPointer::GetGenericInstType + 0x348 (0x00007fff`a9641e98)
      CORECLR! SigPointer::GetTypeHandleThrowing + 0x878 (0x00007fff`a9642a80)
      CORECLR! ZapSig::DecodeType + 0x6C (0x00007fff`a9694e0c)
      CORECLR! LoadDynamicInfoEntry + 0x114 (0x00007fff`a95d1abc)
      CORECLR! Module::FixupNativeEntry + 0x6C (0x00007fff`a9550a5c)
      CORECLR! Module::FixupDelayListAux<Module *,int (__cdecl Module::*)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007fff`a9695d44)
      CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007fff`a9696ed4)
      CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007fff`a9630ea0)
      CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007fff`a9630c78)
      CORECLR! MethodDesc::PrepareILBasedCode + 0x25C (0x00007fff`a9632c74)
      CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007fff`a9632a0c)
      CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007fff`a9577460)
      CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007fff`a962e914)
      CORECLR! PreStubWorker + 0x3D4 (0x00007fff`a9635204)
      CORECLR! ThePreStub + 0x50 (0x00007fff`a9521214)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`a5714854)
      FRAMEWORK-R2R! <no symbol> + 0x0 (0x00007fff`a570fcb0)
      -----
      .AV on tid=0x2064 (8292), cxr=00000058B9FFD730, exr=00000058B9FFDAC0
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2D0 (0x00007fff`a98fb4e8)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2F4 (0x00007fff`a95960cc)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007fff`a9595b64)
      CORECLR! CLRVectoredExceptionHandler + 0x16C (0x00007fff`a9595ad4)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x24C (0x00007fff`a959641c)
      NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007fff`da7cccb0)
      NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007fff`da78cdc4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007fff`da763434)
      CORECLR! LookupMapBase::GetElementPtr + 0x0 (0x00007fff`a9552320)
      CORECLR! ClassLoader::LoadTypeDefOrRefThrowing + 0xB8 (0x00007fff`a956fbd0)
          File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp Line: 7581
          Image: D:\h\w\A14F0942\p\corerun.exe
</pre>

/cc @dotnet/crossgen-contrib

**Comment by trylek** [comment]
During testing of the code range change I raised concerns whether the bug may be related to my change and I ran the test in a loop overnight on a Windows arm64 VM that David Wrighton kindly granted me access to; I was unable to hit the failure with more than 60K iterations.

**Comment by trylek** [comment]
I found one more failure of the test in 20220124.1, sadly the retention period for Helix logs is just one month so they are no longer available but considering the frequency and duration it seems to me it might have had a similar cause. Before that there's no single repro for about half a year, I just found one repro from last July but that was probably infrastructural because the test ran for just about one second, much shorter than on the other occasions.  Assuming average repro rate once in two weeks, a possible bug causing this was likely merged in around mid January.

**Comment by jkotas** [comment]
Do we have any crash dumps for the crash?

**Comment by trylek** [comment]
I haven't found any, IIRC dumps on arm64 are somehow problematic because their Helix uploads keep timing out so they are mostly suppressed.

**Comment by trylek** [comment]
I just double-checked the log from your latest run, we don't even try to generate the dump when this fails; the harness normally returns 1 as if the test just failed with a wrong exit code. Perhaps that is something we should fix, possibly by setting some COMPLUS variable or by making some adjustments to the VM configuration to capture dumps upon assertion failures?

**Comment by MichalStrehovsky** [comment]
Windows ARM64 machines are not configured to collect dumps - https://github.com/dotnet/core-eng/issues/15534.
