### ISSUE TITLE
Regex Matches Count gives ArgumentOutOfRangeException (regression)

### ISSUE THREAD

**Issue by AlbertoMonteiro** [dotnet/runtime#66212]
### Description

Just run this code with dotnet 7.0.100-preview.1.22110.4 and it will break
```csharp
_ = Regex.Matches("bar\n", @"(?m)^[^a]a", 0).Count
```
![image](https://user-images.githubusercontent.com/836496/156831443-46a1966a-f1d7-488c-ad34-581100b8cf8f.png)

### Reproduction Steps

Clone this project: https://github.com/AlbertoMonteiro/RegexIssueDotnet7Preview1
Then `dotnet run`

### Expected behavior

The Count should return 1

### Actual behavior

Throws `System.ArgumentOutOfRangeException`

### Regression?

On dotnet 6 it works fine

### Known Workarounds

Adding an \0 to the end of the string that ends with \n doesnt throw
```csharp
_ = Regex.Matches("bar\n\0", @"(?m)^[^a]a", 0).Count
```
Returns properly 1

**Comment by stephentoub** [comment]
Thanks for the great bug report.  We're missing a length check after we optimize for a beginning-of-line anchor and jump to the next \n.

**Comment by firasdib** [comment]
For what its worth, I was unable to verify that this fix worked, running the nightly build (found here https://github.com/dotnet/aspnetcore/blob/main/docs/DailyBuilds.md). I still see the same error.

**Comment by firasdib** [comment]
This is the output I get is:

```
> ~/projects/dotnet/dotnet --version
7.0.100-preview.3.22165.3
```

Running `Linux 5.16.11-2-MANJARO x86_64`

**Comment by stephentoub** [comment]
What do you see for .NET 7 for `dotnet --list-runtimes`?

**Comment by firasdib** [comment]
Here's the output from that

```
> ~/projects/dotnet/dotnet --list-runtimes
Microsoft.AspNetCore.App 7.0.0-preview.3.22158.12 [/home/firas/projects/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0-preview.3.22151.6 [/home/firas/projects/dotnet/shared/Microsoft.NETCore.App]
```
