### ISSUE TITLE
[API Proposal]: Make Type-Argument contra-variant in IEquatable<in T> and IComparable<in T>

### ISSUE THREAD

**Issue by SpocWeb** [dotnet/runtime#66236]
### Background and motivation

Variance allows to extend Algorithms to more Types. 
IEquatable<T>.Equals is unnecessarily in-variant, preventing me from keeping multiple Interfaces contra-variant.

### API Proposal

```C#
namespace System
{
    public interface IEquatable<in T>
    {
        bool Equals(T? other);
    }
}
```

### API Usage

Usage stays the same. No Changes in Behavior either.

```C#
```

### Alternative Designs

My current workaround is to define my own IEquals<in T> Interface, but obviously I cannot re-use it with any .NET Standard Class, so I have to wrap or subclass any of these.

### Risks

None AFAIK, Behavior stays the same, Flexibility is increased.

**Comment by SpocWeb** [comment]
area-System.Numerics

**Comment by stephentoub** [comment]
Thanks. This has been proposed and declined a few times in the last few years. Recycling some text @gafter wrote a few years ago:

> Equality and inheritance don’t mix.
>
> When you inherit to share the implementation and provide a distinct implementation of the API but not to create what should be treated as a brand new API, you don’t need the variance on IEquatable<T> because the T should continue to be the original type.
>
> When you inherit to create what should be treated as a brand new API (e.g. by adding fields that are significant to equality), then you don’t want to inherit the `IEquatable<Base>` as `IEquatable<Derived>`, because it doesn’t implement the correct contract for equality in the derived type.
>
> Either way, the contravariance is not helpful.  I suspect this is why `IEquatable<T>` was not contravariant in the first place.

This is also why this comment exists:

https://github.com/dotnet/runtime/blob/1934775fc47e7992ff4a502a40f6f4060a461b1f/src/libraries/System.Private.CoreLib/src/System/IEquatable.cs#L8

**Comment by SpocWeb** [comment]
OK, thanks very much for this answer anyway. I'll close this issue then.
