### ISSUE TITLE
Is it possible replacing .NET System libraries with custom ones?

### ISSUE THREAD

**Issue by mnns** [dotnet/runtime#66246]
For example, I'd like to re-compile System.IO with my own patches inside, to print Console.WriteLine() each time a specific method is called.

Can this be done system-wide? if so, how? 
Assuming I'm able to disable signature validation.

Also, can I provide my custom DLLs with a specific project and make sure it uses them?

Thanks

**Comment by Clockwork-Muse** [comment]
> Also, can I provide my custom DLLs with a specific project and make sure it uses them?

You can fork this project, make whatever changes you want, build it, then build a project with it and do a self-contained deployment.

_Why_ do you want to do this, though?  You might only need to turn on logging/eventing or debug tracing.

**Comment by jkotas** [comment]
> Can this be done system-wide? if so, how?

You can create your own modified copy of the .NET runtime and point `DOTNET_ROOT` environment variable or some of the other install location overrides (https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md) to it.

These is no way to override individual files that are part of .NET runtime. It has to be always a full set that is consistent.
