### ISSUE TITLE
System.DirectoryServices.Protocols.CompareRequest fails on Linux when invoked with string attribute value

### ISSUE THREAD

**Issue by psteniusubi** [dotnet/runtime#66243]
### Description

Using `CompareRequest (string distinguishedName, string attributeName, string value)` always fails on Linux. 

`LdapPal.CompareDirectoryEntries` from [LdapPal.Linux.cs](https://github.com/dotnet/runtime/blob/3ede8095da51d5d27a890020b61376155e9a61c2/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/Interop/LdapPal.Linux.cs#L15) does not pass `strValue` parameter to `Interop.Ldap.ldap_compare` from [Interop.Ldap.cs](https://github.com/dotnet/runtime/blob/3ede8095da51d5d27a890020b61376155e9a61c2/src/libraries/Common/src/Interop/Linux/OpenLdap/Interop.Ldap.cs#L256)

### Reproduction Steps

```csharp
        [TestMethod]
        public void Test1()
        {
            var server = new LdapDirectoryIdentifier("db.debian.org", 389);
            var connection = new LdapConnection(server);
            connection.AuthType = AuthType.Anonymous;
            connection.SessionOptions.ProtocolVersion = 3;
            var response = connection.SendRequest(new CompareRequest("dc=debian,dc=org", "dc", "debian"));
            Assert.AreEqual(ResultCode.CompareTrue, response.ResultCode);
        }
```

### Expected behavior

Should not fail

### Actual behavior

Fails with error DirectoryOperationException: A protocol error occurred

```
  Error Message:
   Test method CompareRequest1.UnitTest1.Test1 threw exception:
System.DirectoryServices.Protocols.DirectoryOperationException: A protocol error occurred. A protocol error occurred.
  Stack Trace:
      at System.DirectoryServices.Protocols.LdapConnection.ConstructResponseAsync(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut, Boolean sync)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
   at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request)
   at CompareRequest1.UnitTest1.Test1()
```

### Known Workarounds

Use `CompareRequest (string distinguishedName, string attributeName, byte[] value)` by converting string attribute value to byte array 

```csharp
        [TestMethod]
        public void Test2()
        {
            var server = new LdapDirectoryIdentifier("db.debian.org", 389);
            var connection = new LdapConnection(server);
            connection.AuthType = AuthType.Anonymous;
            connection.SessionOptions.ProtocolVersion = 3;
            var response = connection.SendRequest(new CompareRequest("dc=debian,dc=org", "dc", Encoding.UTF8.GetBytes("debian")));
            Assert.AreEqual(ResultCode.CompareTrue, response.ResultCode);
        }
```

### Configuration

dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.200/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by danmoseley** [comment]
Thanks for the report @psteniusubi . I haven't looked into it, but if the fix is local and understood would you consider offering a PR with a test?

**Comment by psteniusubi** [comment]
@danmoseley - yes I'll put together a PR. The fix is local. This needs an integration test but I think I know how to do that in [DirectoryServicesProtocolsTests.cs](https://github.com/dotnet/runtime/blob/b1da321d184875040bd6aa8c5ebd904e8192815f/src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs)
