### ISSUE TITLE
DOTNET_DiagnosticPorts=/mypath/myfile.socket does not work

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/runtime#66263]
In .net 6, tried to create a different path for the socket that EventPipe generates and it doesn't work.

**Comment by AaronRobinsonMSFT** [comment]
@simplejackcoder Could you also provide the platform on which this was tried and what happened specifically. Was there a crash? Was data simply not emitted? What sort of behavior did you notice that indicated it "didn't work".

**Comment by simplejackcoder** [comment]
I put the file path and it doesn't generate the socket file, it generates two files clr-debug-pipe-339-108580-in and out equivalent but not in the path I told it to.

`DOTNET_DiagnosticPorts=/mypath/myfile.socket,nosuspend`

**Comment by tommcdon** [comment]
@mikelle-rogers

**Comment by noahfalk** [comment]
Each port has a connect side and a listen side. The listen side creates the socket/pipe and the connect side connects to it. By default when you specify new ports with that env var the runtime takes on the connect role so we wouldn't expect the runtime to be responsible for creating that socket.

If you want the runtime to take on the listening role and create the socket try this:

`DOTNET_DiagnosticPorts=/mypath/myfile.socket,nosuspend,listen`

I don't recall if the work to have tools connect to custom pipes/sockets is completed. At minimum I don't think it is documented yet so you might run into rough edges.
