### ISSUE TITLE
[API Proposal]: Enum.HasFlag<TEnum>(TEnum flag)

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#66261]
### Background and motivation

A better editor intellisense

### API Proposal

```C#
namespace System
{
    public static class EnumExtensions
    {
        public static bool HasFlag<TEnum>(this TEnum en, TEnum flag) where TEnum : System.Enum => en.HasFlag(flag);
    }
}
```

### API Usage

```C#
[Flags]
enum E {
    A = 1,
    B = 2,
    C = 4
}

E e = E.A | E.C; // retrieve Enum
bool hasFlag = e.HasFlag<E>(E.B);
```

### Alternative Designs

Code-generated flag `get`/`set`-ters with a requirement of JIT to optimize HasFlag(E.A) && HasFlag(E.B) to HasFlag(E.A | E.B)

### Risks

Performance (at least bigger asm/il code https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuAdAEoCuMCUYAplQMID2YADlADYsATgGVhANygBjFigDcRANoAxfhADmKALpFMAZjIsYdMGRQIA3viJlbd2wEEyAXlxwyAIRfZ37ZwBYbezsAX10DSgA2CmwyAFFjMDiAD0sg23SyRREACwghHgAZCGBaBiZWKgApKAQAcSNhaQAKBABPHhZOADNm8wBKfp1Ce0UAWRYEHM4AEwBJXn5mianZhZ5+AHkeJk4YFCoHdXUhWRQocRY5mH5YWHUh8IpcaOBOTn4yAAlUVQ0AHgAKgkTAA+Vo5KAoMjAxJkRLuWEmMjdNQPMgAdxywhYMJBphAzyo+KsIzsmAA7PCTFQfig/upmqiNP0FIQwmTbBz9DEyOwyKT7DzzGRxGyhRF/GQxs1+gLMkLcABOZriWm/NF9BBUDyDcXBMgciUUKV1WWCg3PFVqukM/7mcHmHV6zIckJAA=== )

**Comment by EgorBo** [comment]
IMO it's not clear from the proposal what this API is supposed to solve/help with.

> Performance (at least bigger asm/il code

It's pretty much the same the only difference that JIT pushed generic context to stack for vm, it's a known issue

**Comment by SupinePandora43** [comment]
> IMO it's not clear from the proposal what this API is supposed to solve/help with.

`TEnum.HasFlag(Enum)` can be called with any `Enum` , not just `TEnum`.

**Comment by teo-tsirpanis** [comment]
There could be an analyzer that warns about invalid usage of the non-generic `HasFlag`.

**Comment by tannergooding** [comment]
CC. @jkotas, are there any concerns on this one or with exposing generic variants of "most" static methods on `System.Enum` (outside the cost of specializing them in the runtime)?

It does seem like an analyzer could help cover a number of these scenarios and may be a better solution than exposing a generic variant of every method.

**Comment by jkotas** [comment]
My opinion is that it is best to use the built-in bit operators for `[Flags]` enum operations. It is typically less characters, guaranteed to be fast and gives you full expressivity. I do not see a value in re-recreating longer named equivalents.

> TEnum.HasFlag(Enum) can be called with any Enum , not just TEnum.

The built-in bit operators check that the enum types match already.
