### ISSUE TITLE
Add MemberNotNullWhen to Type.IsArray

### ISSUE THREAD

**Issue by manfred-brands** [dotnet/runtime#66286]
Add a `[MemberNotNullWhen(true, nameof(GetElementType))]` to `bool IsArray` in Type.cs

To prevent a CS8600 (or equivalent) when using:

```csharp
Type type;

if (type.IsArray)
{
    Type elementType = type.GetElementType();
    ...
}
```

There are likely more places where this attribute is appropriate.

**Comment by stephentoub** [comment]
MemberNotNullWhen is applied to a bool-returning method or property to indicate that some other field or property (not method) isn't null; such an attribute on IsArray couldn't specify the method GetElementType. But thanks for the suggestion.

**Comment by manfred-brands** [comment]
@stephentoub Thanks. So there is no way to do this pattern in the current system. Do you know of any plans to do this.

**Comment by stephentoub** [comment]
Not to my knowledge. dotnet/csharplang is the right place to file feature requests around this.
