### ISSUE TITLE
Blazorwasm : deployment with aot compilation and with out aot compilation

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#66287]
i know aot compilation can take more size for published app and in my case this take 4x weight and this size is very huge in my country
many users in my country can download 500kb per second and my published app take 20mb weight in brotli compression mode..!
users must be wait over 50s to load my web application
in .net 7 i seen mixed-mode aot compilation 
can you say me how it's can be help me!?
And can I hope this problem will be solved in .NET 7 !?

**Comment by lewing** [comment]
@sajjadarashhh without knowing more about your app it is difficult to understand what is causing it to be so large.  We are considering several approaches to help reduce the final size of an AOT'd wasm app for .NET 7 and it would be helpful to that work if you could share more details about the problems you are seeing.

**Comment by sajjadarashhh** [comment]
![Screenshot 2022-03-12 175725](https://user-images.githubusercontent.com/72276897/158021950-d6c63d89-a760-4cec-912a-5b7ebb31cb6f.png)
in this picture can you see dotnet.wasm is very large in aot Compilation mode(without Compression this with Compression take 18.0mb) 
@lewing we have an Enterprise web application that's have 22pages and much more And a number of others dialogs and Components we use MudBlazor Library 
May I ask what you need to know?

**Comment by lewing** [comment]
can you provide a sample project to reproduce these results?

**Comment by sajjadarashhh** [comment]
no i cant my company terms not approve me to send project.
we have 5 project like this:
models
Services
WasmUi
WasmComponents
infrastructure
and MudBlazor Library
i have refrence from all projects from wasmUi and Components
we have Some pages and components (20pages and 17 components)in wasmui and wasmComponents
all of this when compiled takes very huge size
and we have one dirty usage of Layout(our developers don't use layout component as normal approach they use Layout like component in every page)

**Comment by lewing** [comment]
Are you using trimming all these assemblies?

**Comment by sajjadarashhh** [comment]
I thought thats trimming by default
I need to triming libraries manually?
And Thanks @lewing but i have another problem when use aot!
when i run this and page is loaded completely this very very slower than normal publishe in .net 6.0.5 blazor wasm
I can to make video from this and source code if need...
Say me what data is need.

**Comment by sajjadarashhh** [comment]
@lewing i enable trimming for third party libraries but this does not make very difficult!
Its make 130MB size and 15MB in brotli mode
this have very lag and dely in aot mode!
But this lag and delay not shown in normal publish

**Comment by radekdoulik** [comment]
Hopefully the jiterpreter in NET8 might help in your case. It improved the non-AOT configuration performance a lot. There's also possibility to use AOT profile to AOT only parts of the app.

We will continue improving the AOT in the NET9.

**Comment by sajjadarashhh** [comment]
@radekdoulik but i feel blazor have problems
Thats should be faster than now
at both startup and runtime
