### ISSUE TITLE
Environment.ProcessPath shouldn't be marked as nullable

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#66288]
My application is explicit marked as windows only by using `-windows`. The docs say `Returns null when the path is not available.` but in which case can this be true? You cannot move/delete/rename the executable when its running (at least under Windows). Also the implementation doesn't return null anywhere:

https://github.com/dotnet/runtime/blob/0022738e10a22c6ffa121604a86c99d45fc3ea78/src/libraries/System.Private.CoreLib/src/System/Environment.Windows.cs#L95-L110

**Comment by alexrp** [comment]
* https://github.com/dotnet/runtime/blob/0022738e10a22c6ffa121604a86c99d45fc3ea78/src/libraries/System.Private.CoreLib/src/System/Environment.Browser.cs#L34
* https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/native/minipal/getexepath.h#L28

**Comment by Symbai** [comment]
First it's a windows application. Second if these are the only cases when its null, it should throw a not supported exception instead. Because its obviously not supported (immediately return null).

**Comment by alexrp** [comment]
> First it's a windows application.

NRT annotations are not platform-specific.

> Second if these are the only cases when its null, it should throw a not supported exception instead. Because its obviously not supported (immediately return null).

That would be a breaking change.

**Comment by Symbai** [comment]
> That would be a breaking change.

Exactly, was done for [ProcessModule.FileName](https://github.com/dotnet/runtime/discussions/63235) as well. If the only situation when it can be null, is when it's not supported by the platform. Then it should throw instead, that's why we have this exception for.

**Comment by alexrp** [comment]
> Exactly, was done for [ProcessModule.FileName](https://github.com/dotnet/runtime/discussions/63235) as well. If the **only** situation when it can be null, is when it's not supported by the platform. Then it should throw instead, that's why we have this exception for.

These situations aren't the same. `ProcessModule.FileName` cannot be null on any platform, so marking it as such is appropriate. `Environment.ProcessPath` has already shipped with the behavior of returning null on some platforms in certain scenarios. Changing it to throw `PlatformNotSupportedException` in those cases would be breaking. It's a bit unfortunate, but the ship has sailed on this.

**Comment by jkotas** [comment]
> Changing it to throw PlatformNotSupportedException in those cases would be breaking. 

+1

Also, the advantage of returning null instead of throwing PlatformNotSupportedException is that it allows cheap runtime check and fallback for the unsupported case without hardcoding the list of unsupported platforms.

**Comment by Symbai** [comment]
The disadvantage is that it creates unnecessary warnings for all developers which doesn't write a browser application, because it CANNOT be null for them (which also the docs doesn't say). Some people might even add an unnecessary null check.
