### ISSUE TITLE
[wasm] Determine what default value to use for `$(EmccInitialHeapSize)`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#66313]
Currently we use `512M`. Is this really required? It might not be available for some mobile devices.
@lewing suggests that maybe we should use whatever amount a simple blazor app would need, plus some more.

Thoughts?

cc @radekdoulik @kg @pranavkm

context: https://github.com/dotnet/runtime/pull/66233#discussion_r820110080

**Comment by kg** [comment]
Do we think this needs to happen for 7? I think since the tooling story for this has improved, it might be fine to leave it as-is. I'm also not sure whether it makes sense to change it late in the cycle vs in a preview when we can hear from users about whether it's causing issues.

**Comment by radical** [comment]
I agree. Moving to 8.0 . @lewing please change if you think we should try something here

**Comment by pavelsavara** [comment]
Fixed by https://github.com/dotnet/runtime/pull/80849
