### ISSUE TITLE
Make Runtime.json generation better support merging architectures into compatible runtimegroups

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#66316]
Today when an OS like windows adds an architecture in the middle of its version range we end up applying that architecture to all versions.

We should make a way to add an architecture while still importing previous versions.

See discussions https://github.com/dotnet/runtime/pull/38832 https://github.com/dotnet/corefx/pull/42968

**Comment by ericstj** [comment]
This applies to https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/GenerateRuntimeGraph.cs

Ideally we don't need this if we can change the way RIDs are defined to not require explicitly listing architectures.  https://github.com/eerhardt/designs/pull/2

**Comment by ViktorHofer** [comment]
Closing based on the new design how to represent RIDs: https://github.com/dotnet/designs/pull/260
