### ISSUE TITLE
The documentation for Environment.ProcessPath needs an update

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#66323]
`Environment.ProcessPath` returns a nullable string. If developers want to check why this is the case the [docs just say](https://docs.microsoft.com/en-us/dotnet/api/system.environment.processpath?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Environment.ProcessPath);k(DevLang-csharp)%26rd%3Dtrue&view=net-6.0) `Returns null when the path is not available.` which isn't really clear WHEN this is the case. It [turned out](https://github.com/dotnet/runtime/issues/66288) this is only true for browser or minipal. Therefore the docs should be updated to make this clear so developers don't add an unnecessary null check or even a fallback solution

**Comment by stephentoub** [comment]
> It https://github.com/dotnet/runtime/issues/66288 this is only true for browser or minipal which only very small percentage of devs write apps for

"minipal" is any Unix.
https://github.com/dotnet/runtime/blob/3383c7f656c0763245f33ee99357b36c4e3343b8/src/libraries/System.Private.CoreLib/src/System/Environment.cs#L136-L145
https://github.com/dotnet/runtime/blob/3383c7f656c0763245f33ee99357b36c4e3343b8/src/libraries/System.Private.CoreLib/src/System/Environment.Unix.cs#L99
https://github.com/dotnet/runtime/blob/3383c7f656c0763245f33ee99357b36c4e3343b8/src/libraries/Common/src/Interop/Unix/System.Native/Interop.GetProcessPath.cs#L13-L14
https://github.com/dotnet/runtime/blob/7414af2a5f6d8d99efc27d3f5ef7a394e0b23c42/src/native/libs/System.Native/pal_process.c#L887-L890

**Comment by Symbai** [comment]
> "minipal" is any Unix.

Sorry I didn't know, I'll remove that half sentence. Even more reason to update the documentation.

**Comment by am11** [comment]
We query the underlying OS to get the process path, which can fail per the various, supported OS documentations. For instance; unable to allocate memory on Windows, someone hijacked argv[0] after fork() on Linux, fiddled with procfs on OS' that support it, failed syscall, running .NET as unikernel (single process OS / your process _is_ the bootable OS) and so on. In such rare cases, the implementation returns null.

Consumer can choose to fail fast `string selfExecutablePath = Environment.GetProcessPath ?? throw new ApplicationException("Unable to get self executable path, exiting!");` or fall back to a placeholder value: `?? <Unknown exe path>`.

**Comment by Symbai** [comment]
> For instance; unable to allocate memory on Windows

Can you show me how/where you handle this for a Windows desktop application and where it returns null then? Because from the code I've seen so far there is nothing like that. Previously I've used `Process.GetCurrentProcess().MainModule.Filename`, that always worked and its NOT a nullable string. Now VS suggested me to use `Environment.ProcessPath` which is nullable. I didn't implemented it so I don't understand why it suddenly became nullable. I open the MSDN page and I'm getting told `Returns null when the path is not available.`, and I ask myself "Why should it suddenly became possibly not available?" Do you see my problem? For me that only means that either `Process.GetCurrentProcess().MainModule.Filename` could also fail, which I've honestly never seen and again it's not nullable. Or that `Environment.ProcessPath` implementation is using something else where possibly a fail has been introduced by its code / the way it works now. If last one is the correct answer then it's a breaking change and VS shouldn't suggest me this. Or nothing is correct and for a windows desktop application it always returns a (non-nullable) string. No matter what exactly is the correct answer the documentation page lacks of this information. Developers coming from a non-nullable solution to a nullable solution because VS suggests it. It has to get explained (not here but on MDSN page) when this can be null and when it cannot be null.

**Comment by am11** [comment]
> Can you show me how/where you handle this for a Windows desktop application and where it returns null then?

For example, this OS API: https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamea#return-value suggests that the call can fail under certain circumstances. Basically, it is not in caller's control whether or not OS will always return a value (.NET does not produce this string). Hence, the new API (Environment.ProcessPath) uses `null` as a fallback value, when something weird happens.

> `Process.GetCurrentProcess().MainModule.Filename` could also fail

Yes, `ProcessModule.Filename` also returns a nullable string https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processmodule.filename?view=net-6.0#system-diagnostics-processmodule-filename.

**Comment by alexrp** [comment]
> Yes, `ProcessModule.Filename` also returns a nullable string

Note: #63272

**Comment by am11** [comment]
> > Yes, `ProcessModule.Filename` also returns a nullable string
> 
> Note: #63272

Thanks. Still, `MainModule` itself is nullable: https://github.com/dotnet/runtime/blob/a0a5fc9771f63aa31cb45b3577a7cea31527a2fb/src/libraries/System.Diagnostics.Process/ref/System.Diagnostics.Process.cs#L43 in case we can't get the filename, the loop `continue;`s.

**Comment by Symbai** [comment]
> Basically, it is not in caller's control whether or not OS will always return a value (.NET does not produce this string). Hence, the new API (Environment.ProcessPath) uses `null` as a fallback value, when something weird happens.

In the source code for [Windows implementation](https://github.com/dotnet/runtime/issues/66288#issue-1161263196) it uses a ValueStringBuilder, then calls a native API. Then checks ifs the length is greater than 0, otherwise it throws. Then it returns the content of ValueStringBuilder. It does NOT return null anywhere (unless I am missing something, that's why I've asked if you could show me where this return null for a windows desktop application).

> Still, `MainModule` itself is nullable:

Yes, but it's 100% not null when used with `GetCurrentProcess()` (for a desktop application). It is nullable because it can also be used on other processes, where for example the calling Process has no access to or different bitness etc. That means Process.GetCurrentProcess().Mainmodule.Filename is guaranteed to return the desired path as string (for a desktop application).

But I think we're leaving the original discussion. I don't mind if the new implementation is nullable. This issue has been created because the documentation lacks of explanation. It should clarify for which OS it can be nullable and under which circumstance. It's okay to say `when path is not available` for the intellisense documtation but its not enough for the MDSN page. That's where developers go to get more information. This issue is more like a request to add more information to that page and that's it.

**Comment by am11** [comment]
> That means `Process.GetCurrentProcess().Mainmodule.Filename` is guaranteed to return the desired path as string (for a desktop application).

MainModule.FileName calls GetModuleBaseNameW win32 api. I don't see any guarantees in its MSDN documentation. Do you have a reference?

**Comment by Symbai** [comment]
For the last time now: it is not nullable, for a good reason. It's not possible that a win32 desktop process cannot access its own main module path and still runs fine. Besides this is off topic. See my post above yours (last paragraph).

**Comment by am11** [comment]
I asked for the link to back up your claim, since you are being so persistent "100%", really?

**Comment by danmoseley** [comment]
`Returns null when the path is not available.` is pretty typical non committal type text when we're essentially wrapping an OS API that's generally assumed to work. Both because (a) the OS does not always document the circumstances in which it fails (b) the OS sometimes changes or has bugs (c) it varies by OS. As you say, on Windows it apparently won't ever return null but suffers from a nullability annotation as the API is the same shape for Unix.

If there are interesting and durable reasons why it might return null, feel free to offer a PR to [the docs themselves](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Environment.xml) (in the case of this part of the code, the docs repo is the source of truth, not the source code. Our long term goal is for all APi docs to be generated from the sources, as they are in other repos.)

Since there's no action in this repo, I'll close it.
