### ISSUE TITLE
SOLVED Cannot get symbol ucol_setMaxVariable_50 from libicui18n

### ISSUE THREAD

**Issue by abarberenaCPDS** [dotnet/runtime#66325]
Cannot get symbol ucol_setMaxVariable_50 from libicui18n

Hi @tarekgh 👋 , I know it's been a long time, however, I just wanted to give you an update in regards to https://github.com/dotnet/runtime/issues/57983.

I was able to ***successfully run dotnet 5!*** 🚀 🥳 🤟 

```bash
Linux centospi 5.4.72-v8.1.el7 #1 SMP PREEMPT Wed Oct 21 17:35:36 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

<img width="888" alt="sc1" src="https://user-images.githubusercontent.com/43246964/157169518-99250456-cb88-439f-9896-1e04a52350d4.png">

### Observations

The only difference this time, was to use a better Micro SD card

- [32 GB SanDisk Extreme](https://www.westerndigital.com/products/memory-cards/sandisk-extreme-uhs-i-microsd#SDSQXVF-032G-AN6MA) 

***I followed the same steps, I did not compile ICU and used your zipped (pre-compiled) libraries.***

PS:

- I couldn't append the results to ticket since now is closed. hopefully there's a way to add this info to provide continuity.
- Should anyone else have or would ever face the same issue, feel free to reach out and/or chime in.

**Comment by tommcdon** [comment]
>> I couldn't append the results to ticket since now is closed. hopefully there's a way to add this info to provide continuity.

It looks like the text in this issue was actually intended for https://github.com/dotnet/runtime/issues/57983#issuecomment-1061996269.  

@abarberenaCPDS please let us know if anything else is needed before we close this issue.

**Comment by tarekgh** [comment]
Thanks @abarberenaCPDS for the update and I am happy you are finally able to unblock yourself. 

@tommcdon thanks for posting the comment into the original thread. 

I am closing this issue, but feel free to send any more questions or notes if you have any.
