### ISSUE TITLE
[API Proposal]: Provide tunnel status code for proxy exceptions

### ISSUE THREAD

**Issue by jgilbert2017** [dotnet/runtime#66329]
### Background and motivation

API user would like to have specific information about why a proxy connection failed without the need to parse a text based error message.

Dotnet 6 altered how proxy errors were handled as part of #48679.  Rather than the proxy response being returned to the user, an error message is returned.  This was done to distinguish proxy related errors from upstream errors.

I have a need to distinguish proxy errors based upon the status code the proxy returned.  This information is conveyed as part of the error message "The proxy tunnel request to proxy {proxyUri} failed with status code {statusCode}."

Please make the proxy status code somehow directly available to the user rather than by parsing a text string.

### API Proposal

TBD

### API Usage

TBD

**Comment by wfurt** [comment]
Triage: looks reasonable. We should look at it at some point.
