### ISSUE TITLE
Add GetParentDefinition Reflection APIs to allow walking the override chain of members

### ISSUE THREAD

**Issue by fschmied** [dotnet/runtime#6633]
(This feature request was originally at https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/3734099-add-getparentdefinition-reflection-apis-to-allow.)

Currently, it's really hard to implement a correct algorithm that gets the parent definition of a `MethodInfo`, `PropertyInfo`, or `EventInfo` representing a member override. A naive implementation is bound to contain bugs regarding overloading, shadowing, generics, and overrides with non-matching accessibility. The only support Reflection offers for the not so uncommon use case of walking the member override chain is the `MethodInfo.GetBaseDefinition()` API, which can be used to check whether two `MethodInfos` are part of the same override chain (they are if they have equivalent base definitions). However, even using `GetBaseDefinition`, one can easily make mistakes (e.g., forgetting to take the ReflectedType of a MethodInfo into account - this influences equality comparisons), and the resulting code is likey to suffer from bad performance.

On the other hand, `RuntimeMethodInfo` contains an internal `GetParentDefinition` method that can efficiently and correctly return the base method (info) of an override. The `Attribute` class contains an algorithm for walking the base member chain for properties and events based on `RuntimeMethodInfo.GetParentDefinition`.

I suggest that these existing APIs are made public: add public, fast `GetParentDefinition` APIs on `MethodInfo`, `PropertyInfo`, and `EventInfo` that can be used to safely walk the override chain in reflective code.

**Comment by steveharter** [comment]
Closing due to ambiguity; please provide an example of the scenario and current "workaround". cc @GrabYourPitchforks

**Comment by fschmied** [comment]
@steveharter Could you elaborate how this is ambiguous? I was asking for
* the `GetParentDefinition` member on `RuntimeMethodInfo` to be made public (and included on `MethodInfo`, if anyhow possible)
* and for equivalent members to be added to `PropertyInfo` and other `*Info` objects.

What's the scenario? Whenever you need to write reflection code that needs to "walk the overrides chain" for a given reflection object. In my experience, this is a common scenario with reflective code. In our case, we had this issue while working on an O/R mapper, on a mixins metaprogramming library, on a LINQ provider, and in several other cases of reflective code. I've seen bugs regarding this quite a few times in third party libraries, too.

Let's start with methods. `MethodInfo` surprisingly doesn't provide a public way to navigate from a method override to the corresponding base (parent) method, although this seems a very common thing to do in reflective code. Here's one way to do it correctly (I hope) that I quickly hacked together:

```
public IEnumerable<MethodInfo> GetParentDefinition(MethodInfo givenMethod)
{
  return
      from baseType in GetBaseTypes(givenMethod.DeclaringType)
      // Caveat: Do not use GetMethod(givenMethod.Name, givenMethod.ParameterTypes, etc.), as this does not take generics into account
      from baseMethod in baseType.GetMethods(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)
      // Caveat: Do not compare Name, parameters, and generic parameters, as this will fail for methods declared with "new" and is very difficult to get right for generics
      // Note: It's okay to compare methods by using "Equals" here because GetBaseDefinition thankfully normalizes the ReflectedType; you cannot compare its result to givenMethod, though
      where Equals(givenMethod.GetBaseDefinition(), baseMethod.GetBaseDefinition())
      select baseMethod;
}

private IEnumerable<Type> GetBaseTypes(Type type)
{
  while (type.BaseType != null)
  {
    yield return type.BaseType;
    type = type.BaseType;
  }
}
```

This kind of reflective code is very hard to get right the first few times you do it, and indeed I'm not sure if it's relly correct because I don't remember right now if `GetBaseDefinition` will always normalize the `ReflectedType` or if this works just in some cases. It's also quite slow, you'll definitely need to implement caching if you want to do this a few times.

Therefore, it's a real pity that even though `RuntimeMethodInfo` already contains an API that does this in a fast way, this API is internal: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs#L113

It's similar for walking the property overrides chain: that's hard to get right ("property overriding" is actually accessor overriding, so you can use the method algorithm above, but navigating back from the base accessor to the actual property definition can be tricky due to indexer property parameters etc.), it will be slow, and the BCL already contains a corresponding internal implementation, hidden in the `Attribute` class: https://github.com/dotnet/runtime/blob/0a2f0e6da98a784601b37d19417b930a33b2c478/src/coreclr/src/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L39

Same about `ParameterInfo` and (to a lesser extent, because very uncommon, `EventInfo`).

Does this make the intention of this issue clearer?
