### ISSUE TITLE
 Cannot find mkstemps nor mkstemp on this platform (CMake Error at src/runtime.*/artifacts/source-build/self/src/src/libraries/Native/Unix/configure.cmake:788)

### ISSUE THREAD

**Issue by mirespace** [dotnet/runtime#66340]
Hi,

I'm packaging dotNet for Ubuntu 22.04. trying to build .Net 6 from source using sbuild in Ubuntu to generate deb packages.

I can't progress on this because I get the following error:

``` 
-- Performing Test HAVE_MKSTEMPS
-- Performing Test HAVE_MKSTEMPS - Failed
-- Performing Test HAVE_MKSTEMP
-- Performing Test HAVE_MKSTEMP - Failed
      CMake Error at /<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/src/libraries/Native/Unix/configure.cmake:788 (message):
        Cannot find mkstemps nor mkstemp on this platform.
```

this part, attending at the log, is launched with

```
Commencing CoreCLR Repo build
      __DistroRid: linux-x64
      Setting up directories for build
      Checking prerequisites...
      Commencing build of "install" target in "CoreCLR component" for Linux.x64.Release in /<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release
.
.
.
.  
/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.100/MSBuild.dll /nologo -bl:/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/log/Release/GenNativeVersion_Linux.x64.Release.binlog -logger:/<<PKGBUILDDIR>>/Tools/source-built/Microsoft.DotNet.Arcade.Sdk/tools/net6.0/Microsoft.DotNet.ArcadeLogging.dll -maxcpucount /m -verbosity:m /v:minimal /clp:Summary /clp:nosummary /nr:false /nodeReuse:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:NativeVersionFile=/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release/version.c /p:RuntimeVersionFile=/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release/../runtime_version.h /p:TargetArchitecture=x64 /p:Configuration=Release /p:TargetOS=Linux /p:OfficialBuildId=20220304.1 /restore /t:GenerateRuntimeVersionFile /warnaserror /<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/eng/empty.csproj
.
.
.

 Invoking "/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/eng/native/gen-buildsys.sh" "/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/src/coreclr" "/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release" x64 clang "" "" Release ""  -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=0 -DFEATURE_DISTRO_AGNOSTIC_SSL=1  -DCLR_CMAKE_KEEP_NATIVE_SYMBOLS=true
      bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
      WARN: Specific version of clang not found, falling back to use the one in PATH.
      /<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release /<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/src/coreclr
      Not searching for unused variables given on the command line.
      Re-run cmake no build system arguments

.
.
.   
/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/src/coreclr/runtime.proj(46,5): error MSB3073: The command ""/<<PKGBUILDDIR>>/src/runtime.839cdfb0ecca5e0be3dbccd926e7651ef50fdf10/artifacts/source-build/self/src/src/coreclr/build-runtime.sh" -x64 -release -ci -keepnativesymbols -os Linux -nopgooptimize /p:OfficialBuildId=20220304.1" exited with code 2.
```
Building itself was launched with:
```
Detected '--': passing remaining parameters '/v:n /p:SkipPortableRuntimeBuild=true /p:LogVerbosity=n /p:MinimalConsoleLogOutput=false /p:ContinueOnPrebuiltBaselineError=true' as build.sh arguments.
Found bootstrap SDK 6.0.100, bootstrap Arcade 6.0.0-beta.21519.3, bootstrap SourceLink 1.1.0-beta-21480-02
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET

Copyright (C) Microsoft Corporation. All rights reserved.


/<<PKGBUILDDIR>>/.dotnet/sdk/6.0.100/MSBuild.dll /bl:/<<PKGBUILDDIR>>/artifacts/log/Debug/BuildXPlatTasks_0307114803.binlog /fileLoggerParameters:LogFile=/<<PKGBUILDDIR>>/artifacts/logs/BuildXPlatTasks_0307114803.log /flp:v=detailed /p:SkipPortableRuntimeBuild=true /p:LogVerbosity=n /p:MinimalConsoleLogOutput=false /p:ContinueOnPrebuiltBaselineError=true /t:PrepareOfflineLocalTools /v:n /<<PKGBUILDDIR>>/tools-local/init-build.proj
Build started 03/07/2022 11:48:04.
/<<PKGBUILDDIR>>/tools-local/init-build.proj(6,3): warning MSB4011: "/<<PKGBUILDDIR>>/git-info/AllRepoVersions.props" cannot be imported again. It was already imported at "/<<PKGBUILDDIR>>/Directory.Build.props (228,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
Project "/<<PKGBUILDDIR>>/tools-local/init-build.proj" on node 1 (PrepareOfflineLocalTools target(s)).
``` 

The tarball used by sbuild was builder with boostrap  (./build.sh /p:ArcadeBuildTarball=true /p:TarballDir=../dotnet6-6.0.102  ; ./prep.sh  --bootstrap ).

Do you have any clue why this can be happening? I'm checking the clang flags just in case, but any idea is more than welcome.

Thanks in advance!

**Comment by hoyosjs** [comment]
Does this source compile for you?

```
    #include <stdlib.h>
    #include <unistd.h>
    #include <string.h>

    int main(void)
    {
        return mkstemp(\"abc\");
    }
```

**Comment by mirespace** [comment]
Trying to build the package for Focal (Ubuntu 20.04) I discovered that this test is Success, but there is using clang 10, not clang 13 as in Ubuntu 22.04

**Comment by hoyosjs** [comment]
Building under clang13 is something I expect works - since the patches for clang were submitted to source-build. This is before indeed. There's another example in https://github.com/dotnet/runtime/blob/main/src%2Fcoreclr%2Fpal%2Fsrc%2Fconfigure.cmake. I wonder if:

```c++
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>

#define MEM_SIZE 1024
#define TEMP_FILE_TEMPLATE \"${CMAKE_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/CMakeTmp/multiplemaptestXXXXXX\"
int main(void)
{
  char * fname = (char *)malloc(std::max((size_t)MEM_SIZE, sizeof(TEMP_FILE_TEMPLATE)));
  strcpy(fname, TEMP_FILE_TEMPLATE);
  return mkstemp(fname);
}
```

works in the CMAKE test.

**Comment by mirespace** [comment]
Hi again Juan, 

no luck ... I'm using as source v6.0.103-source.build and  I forced to clang-13 because clang-14 was landing to Ubuntu 22.04 (and it's the default now), and now it doesn't find clang (strange... but I see this behaviour when trying to use clang-12 and the top one was clang-13 some days ago). Build log is here at [dotnet6.0.103-source-build-clang13.build.gz](https://github.com/dotnet/runtime/files/8248917/dotnet6.0.103-source-build-clang13.build.gz)

With clang-14 the test fail as it was failing before.

I only have been successful with clang10 in Ubuntu Focal (20.04)... I'm comparing buildlogs to see differences.

I continue looking for another root case for this also.

**Comment by mirespace** [comment]
Hi again,

I've been able to force to clang-13, remove all the patches applied to runtime source, and try.... Failing :(    :

> Invoking "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/eng/native/gen-buildsys.sh" "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/src/coreclr" "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release" x64 clang "" "" Release ""  -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=0 -DFEATURE_DISTRO_AGNOSTIC_SSL=1  -DCLR_CMAKE_KEEP_NATIVE_SYMBOLS=true
WARN: Specific version of clang not found, falling back to use the one in PATH.
/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release /<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/src/coreclr
Not searching for unused variables given on the command line.
Re-run cmake no build system arguments
-- The C compiler identification is Clang 13.0.1
-- The CXX compiler identification is Clang 13.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/llvm-13/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/llvm-13/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Detected Linux x86_64
-- Performing Test COMPILER_SUPPORTS_F_STACK_PROTECTOR_STRONG
-- Performing Test COMPILER_SUPPORTS_F_STACK_PROTECTOR_STRONG - Failed
-- Performing Test COMPILER_SUPPORTS_W_IMPLICIT_FALLTHROUGH
-- Performing Test COMPILER_SUPPORTS_W_IMPLICIT_FALLTHROUGH - Failed
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/lib/llvm-13/bin/clang
-- Performing Test HAVE_LTO
-- Performing Test HAVE_LTO - Success
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW
-- Performing Test COMPILER_SUPPORTS_F_ALIGNED_NEW - Failed
-- Performing Test HAVE_DIRENT_D_TYPE
-- Performing Test HAVE_DIRENT_D_TYPE - Success
-- Looking for getauxval
-- Looking for getauxval - found
-- Looking for include file GSS/GSS.h
-- Looking for include file GSS/GSS.h - not found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.1")
-- Performing Test C_SUPPORTS_WUNGUARDED_AVAILABILITY
-- Performing Test C_SUPPORTS_WUNGUARDED_AVAILABILITY - Failed
-- Looking for include files sys/socket.h, linux/in.h
-- Looking for include files sys/socket.h, linux/in.h - not found
-- Performing Test HAVE_IN_PKTINFO
-- Performing Test HAVE_IN_PKTINFO - Failed
-- Performing Test HAVE_IP_MREQN
-- Performing Test HAVE_IP_MREQN - Failed
-- Performing Test HAVE_STATFS_VFS
-- Performing Test HAVE_STATFS_VFS - Failed
-- Performing Test HAVE_STATFS_MOUNT
-- Performing Test HAVE_STATFS_MOUNT - Failed
-- Performing Test HAVE_FLOCK64
-- Performing Test HAVE_FLOCK64 - Failed
-- Performing Test HAVE_IFADDRS
-- Performing Test HAVE_IFADDRS - Failed
-- Looking for O_CLOEXEC
-- Looking for O_CLOEXEC - not found
-- Looking for F_DUPFD_CLOEXEC
-- Looking for F_DUPFD_CLOEXEC - not found
-- Looking for F_FULLFSYNC
-- Looking for F_FULLFSYNC - not found
-- Looking for getifaddrs
-- Looking for getifaddrs - not found
-- Looking for fork
-- Looking for fork - not found
-- Looking for lseek64
-- Looking for lseek64 - not found
-- Looking for mmap64
-- Looking for mmap64 - not found
-- Looking for ftruncate64
-- Looking for ftruncate64 - not found
-- Looking for posix_fadvise64
-- Looking for posix_fadvise64 - not found
-- Looking for stat64
-- Looking for stat64 - not found
-- Looking for vfork
-- Looking for vfork - not found
-- Looking for pipe2
-- Looking for pipe2 - not found
-- Looking for getmntinfo
-- Looking for getmntinfo - not found
-- Looking for strcpy_s
-- Looking for strcpy_s - not found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strcat_s
-- Looking for strcat_s - not found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - not found
-- Looking for fallocate
-- Looking for fallocate - not found
-- Looking for preadv
-- Looking for preadv - not found
-- Looking for pwritev
-- Looking for pwritev - not found
-- Looking for ioctl
-- Looking for ioctl - not found
-- Looking for sched_getaffinity
-- Looking for sched_getaffinity - not found
-- Looking for sched_setaffinity
-- Looking for sched_setaffinity - not found
-- Looking for pthread_setcancelstate
-- Looking for pthread_setcancelstate - not found
-- Looking for arc4random_buf
-- Looking for arc4random_buf - not found
-- Looking for TIOCGWINSZ
-- Looking for TIOCGWINSZ - not found
-- Looking for tcgetattr
-- Looking for tcgetattr - not found
-- Looking for tcsetattr
-- Looking for tcsetattr - not found
-- Looking for ECHO
-- Looking for ECHO - not found
-- Looking for ICANON
-- Looking for ICANON - not found
-- Looking for TCSANOW
-- Looking for TCSANOW - not found
-- Looking for cfsetspeed
-- Looking for cfsetspeed - not found
-- Looking for cfmakeraw
-- Looking for cfmakeraw - not found
-- Performing Test HAVE_UTSNAME_DOMAINNAME
-- Performing Test HAVE_UTSNAME_DOMAINNAME - Failed
-- Performing Test HAVE_STAT_BIRTHTIME
-- Performing Test HAVE_STAT_BIRTHTIME - Failed
-- Performing Test HAVE_STAT_FLAGS
-- Performing Test HAVE_STAT_FLAGS - Failed
-- Looking for lchflags
-- Looking for lchflags - not found
-- Performing Test HAVE_STAT_TIMESPEC
-- Performing Test HAVE_STAT_TIMESPEC - Failed
-- Performing Test HAVE_STAT_TIM
-- Performing Test HAVE_STAT_TIM - Failed
-- Performing Test HAVE_STAT_NSEC
-- Performing Test HAVE_STAT_NSEC - Failed
-- Performing Test HAVE_DIRENT_NAME_LEN
-- Performing Test HAVE_DIRENT_NAME_LEN - Failed
-- Performing Test HAVE_STATFS_FSTYPENAME
-- Performing Test HAVE_STATFS_FSTYPENAME - Failed
-- Performing Test HAVE_STATVFS_FSTYPENAME
-- Performing Test HAVE_STATVFS_FSTYPENAME - Failed
-- Looking for statfs
-- Looking for statfs - not found
-- Check size of struct statfs
-- Check size of struct statfs - failed
-- Performing Test HAVE_GNU_STRERROR_R
-- Performing Test HAVE_GNU_STRERROR_R - Failed
-- Performing Test HAVE_READDIR_R
-- Performing Test HAVE_READDIR_R - Failed
-- Performing Test KEVENT_HAS_VOID_UDATA
-- Performing Test KEVENT_HAS_VOID_UDATA - Failed
-- Performing Test HAVE_FDS_BITS
-- Performing Test HAVE_FDS_BITS - Failed
-- Performing Test HAVE_PRIVATE_FDS_BITS
-- Performing Test HAVE_PRIVATE_FDS_BITS - Failed
-- Performing Test HAVE_SENDFILE_4
-- Performing Test HAVE_SENDFILE_4 - Failed
-- Performing Test HAVE_SENDFILE_6
-- Performing Test HAVE_SENDFILE_6 - Failed
-- Performing Test HAVE_SENDFILE_7
-- Performing Test HAVE_SENDFILE_7 - Failed
-- Looking for fcopyfile
-- Looking for fcopyfile - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file linux/ethtool.h
-- Looking for include file linux/ethtool.h - not found
-- Looking for include file sys/poll.h
-- Looking for include file sys/poll.h - not found
-- Looking for include file sys/proc_info.h
-- Looking for include file sys/proc_info.h - not found
-- Looking for epoll_create1
-- Looking for epoll_create1 - not found
-- Looking for accept4
-- Looking for accept4 - not found
-- Looking for kqueue
-- Looking for kqueue - not found
-- Looking for disconnectx
-- Looking for disconnectx - not found
-- Performing Test HAVE_GETNAMEINFO_SIGNED_FLAGS
-- Performing Test HAVE_GETNAMEINFO_SIGNED_FLAGS - Failed
-- Looking for malloc_size
-- Looking for malloc_size - not found
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - not found
-- Looking for posix_memalign
-- Looking for posix_memalign - not found
-- Looking for aligned_alloc
-- Looking for aligned_alloc - not found
-- Performing Test HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP
-- Performing Test HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP - Failed
-- Performing Test HAVE_CLOCK_MONOTONIC
-- Performing Test HAVE_CLOCK_MONOTONIC - Failed
-- Performing Test HAVE_CLOCK_REALTIME
-- Performing Test HAVE_CLOCK_REALTIME - Failed
-- Looking for clock_gettime_nsec_np
-- Looking for clock_gettime_nsec_np - not found
-- Looking for pthread_condattr_setclock in pthread
-- Looking for pthread_condattr_setclock in pthread - not found
-- Looking for futimes
-- Looking for futimes - not found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for utimensat
-- Looking for utimensat - not found
-- Performing Test BIND_ADDRLEN_UNSIGNED
-- Performing Test BIND_ADDRLEN_UNSIGNED - Failed
-- Performing Test IPV6MR_INTERFACE_UNSIGNED
-- Performing Test IPV6MR_INTERFACE_UNSIGNED - Failed
-- Looking for include file sys/inotify.h
-- Looking for include file sys/inotify.h - not found
-- Performing Test INOTIFY_RM_WATCH_WD_UNSIGNED
-- Performing Test INOTIFY_RM_WATCH_WD_UNSIGNED - Failed
-- Checking prototype getpriority for PRIORITY_REQUIRES_INT_WHO
-- Checking prototype getpriority for PRIORITY_REQUIRES_INT_WHO - False
-- Checking prototype kevent for KEVENT_REQUIRES_INT_PARAMS
-- Checking prototype kevent for KEVENT_REQUIRES_INT_PARAMS - False
-- Checking prototype statfs for HAVE_NON_LEGACY_STATFS
-- Checking prototype statfs for HAVE_NON_LEGACY_STATFS - False
-- Performing Test HAVE_MKSTEMPS
-- Performing Test HAVE_MKSTEMPS - Failed
-- Performing Test HAVE_MKSTEMP
-- Performing Test HAVE_MKSTEMP - Failed
CMake Error at /<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/src/libraries/Native/Unix/configure.cmake:800 (message):
Cannot find mkstemps nor mkstemp on this platform.
Call Stack (most recent call first):
/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/src/libraries/Native/Unix/CMakeLists.txt:257 (include)

**Comment by hoyosjs** [comment]
I might need to take a look at ubuntu 22.04 headers to see what's going on here. It might take me a bit though.

**Comment by mirespace** [comment]
Hi!

I'm also checking the headers, forcing the packages to ensure they are there ... It's like it doesn't find some headers although they are there. I was checking if I can pass them in any way to build.sh, the configure or any other conf file... so, I saw that the clang invoking is in gen-buildsys.sh.

Checking the OK-20.04-build versus the BAD-22.04-build, I see on the last `WARN: Specific version of clang not found, falling back to use the one in PATH.` after the gen-buildsys.h invoking. Wondering if this check can be the root case for not finding the correct headers, as I see in the invoking gen-buildsys.sh the same (not clang specified):

> Invoking "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/eng/native/gen-buildsys.sh" "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/src/coreclr" "/<<PKGBUILDDIR>>/src/runtime.c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663/artifacts/source-build/self/src/artifacts/obj/coreclr/Linux.x64.Release" x64 clang "" "" Release ""  -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=0 -DFEATURE_DISTRO_AGNOSTIC_SSL=1  -DCLR_CMAKE_KEEP_NATIVE_SYMBOLS=true

I also remove specific dev packages for clang ( i.e. libunwind-dev) to force clang and llvm to install all that they need by default ... at least to make them to complaint more accurately, but still failing in the mkstemps check.

As gut-feeling, it seems like in 22.04 it needs to be helped to find the libs and/or headers and in 20.04 it doesn't... keeping on eye on this also.

**Comment by mirespace** [comment]
Hi Juan!

We caught it! Disabling LTO when using clang solves the problem! (in 20.04 it wasn't on the default toolchain, but in 22.04 it is).

Thanks a lot for taking an eye on this and sorry for the noise. You can close the issue.

**Comment by hoyosjs** [comment]
Thanks @mirespace for digging into it. It's sort of silly if cmake checks are sensitive to LTO. Feels like test things should be permissive about functions being available. Will keep this one in mind in case I see it again.

**Comment by kg** [comment]
I'm hitting this when trying to build with a from-source build of llvm, and using system llvm packages doesn't work (they're too old to work after the recent zlib/cmake changes broke compatibility with clang 14).

```
PATH=/home/kate/Projects/llvm-project/build/bin:$PATH ./build.sh --os browser -c Release /p:WasmNativeStrip=false

  -- Looking for pthread_create in c - not found
  CMake Error at configure.cmake:651 (check_library_exists):
    check_library_exists Macro invoked with incorrect arguments for macro
    named: CHECK_LIBRARY_EXISTS
  Call Stack (most recent call first):
    CMakeLists.txt:110 (include)
  
  
  -- Looking for futimes
  -- Looking for futimes - not found
  -- Looking for futimens
  -- Looking for futimens - not found
  -- Looking for fchmod
  -- Looking for fchmod - not found
  -- Looking for chmod
  -- Looking for chmod - not found
  -- Looking for utimensat
  -- Looking for utimensat - not found
  -- Looking for lutimes
  -- Looking for lutimes - not found
  -- Performing Test IPV6MR_INTERFACE_UNSIGNED
  -- Performing Test IPV6MR_INTERFACE_UNSIGNED - Failed
  -- Looking for include file sys/inotify.h
  -- Looking for include file sys/inotify.h - not found
  -- Performing Test INOTIFY_RM_WATCH_WD_UNSIGNED
  -- Performing Test INOTIFY_RM_WATCH_WD_UNSIGNED - Failed
  -- Checking prototype getpriority for PRIORITY_REQUIRES_INT_WHO
  -- Checking prototype getpriority for PRIORITY_REQUIRES_INT_WHO - False
  -- Checking prototype kevent for KEVENT_REQUIRES_INT_PARAMS
  -- Checking prototype kevent for KEVENT_REQUIRES_INT_PARAMS - False
  -- Checking prototype statfs for HAVE_NON_LEGACY_STATFS
  -- Checking prototype statfs for HAVE_NON_LEGACY_STATFS - False
  -- Checking prototype ioctl for HAVE_IOCTL_WITH_INT_REQUEST
  -- Checking prototype ioctl for HAVE_IOCTL_WITH_INT_REQUEST - False
  -- Performing Test HAVE_MKSTEMPS
  -- Performing Test HAVE_MKSTEMPS - Failed
  -- Performing Test HAVE_MKSTEMP
  -- Performing Test HAVE_MKSTEMP - Failed
  CMake Error at configure.cmake:776 (message):
    Cannot find mkstemps nor mkstemp on this platform.
  Call Stack (most recent call first):
    CMakeLists.txt:110 (include)
  
  
  -- Configuring incomplete, errors occurred!
```

What are the steps to resolve it? I don't understand from reading the comments in this issue what actually was done to resolve the problem. It seems like it has something to do with LTO, and I'm guessing maybe the default status of LTO changed? Do I need to edit one of our cmake files? Do I need to update cmake? (I'm using 3.25.1)
