### ISSUE TITLE
Timeout running `System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException` on mono interpreter

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#66371]
From [test result](https://dev.azure.com/dnceng/public/_build/results?buildId=1652456&view=ms.vss-test-web.build-test-results-tab&runId=45572582&resultId=185687&paneView=debug) and [log](https://helix.dot.net/api/2019-06-17/jobs/56bd84c8-6429-4c00-96b1-cb8dece26e37/workitems/System.Text.Json.Tests/console) from https://github.com/dotnet/runtime/pull/66307:
```
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 2)
    System.Text.Json.Tests.Utf8JsonReaderTests.TestDepth(depth: 256) [SKIP]
      Takes very long to run on interpreter.
    System.Text.Json.Tests.Utf8JsonReaderTests.TestDepth(depth: 512) [SKIP]
      Takes very long to run on interpreter.
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException', Elapsed: 00:04:12
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException', Elapsed: 00:06:12
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException', Elapsed: 00:08:12
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException', Elapsed: 00:10:12

...
[EXECUTION TIMED OUT]
```

This test was added in https://github.com/dotnet/runtime/pull/66248.

@eiriktsarpalis can you take a look? Is this expected to take a long time on mono interpreter / should it be disabled (looks like some other Json tests are disabled that way)?

**Comment by elinor-fung** [comment]
Looks like we've hit the timeout five times since the test was added yesterday - the console logs from the five hits indicate `GetConverter_Poco_WriteThrowsNotSupportedException` was running.

```kusto
WorkItems
| where Queued > ago(2d)
| where FriendlyName == "System.Text.Json.Tests"
| where Status == "Timeout"
| join Jobs on JobId
| project
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  QueueName, Source
```

|Queued                  |FriendlyName            |Status                |ConsoleUri|PhaseName                                                                                                                                                                                                                                                             |Pipeline                                                   |QueueName|Source                   |
|------------------------|------------------------|----------------------|----------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|---------|-------------------------|
|2022-03-07T22:51:18.755Z|System.Text.Json.Tests  |Timeout               |https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65262-merge-2460583e0cc447c68e/System.Text.Json.Tests/1/console.1e589d0e.log?sv=2019-07-07&se=2022-03-27T22%3A42%3A45Z&sr=c&sp=rl&sig=7jEe0PUwfMlJKo6MhEomA0gZ4XAYgibUbyB6TV6wxZ0%3D|libraries_test_run_release_mono_interpreter_Linux_x64_Debug                                                                                                                                                                                                           |runtime                                                    |ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/65262/merge|
|2022-03-08T13:51:49.553Z|System.Text.Json.Tests  |Timeout               |https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65889-merge-77638efc58804cbb85/System.Text.Json.Tests/1/console.f3da47bc.log?sv=2019-07-07&se=2022-03-28T13%3A51%3A45Z&sr=c&sp=rl&sig=H2Vo8Kp3ZjWZNjwzyoj3Bd3dSHTO32jtWO5QGSGHdeM%3D|libraries_test_run_release_mono_interpreter_Linux_x64_Debug                                                                                                                                                                                                           |runtime                                                    |ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/65889/merge|
|2022-03-08T16:54:50.664Z|System.Text.Json.Tests  |Timeout               |https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65889-merge-622a27452c29487f8d/System.Text.Json.Tests/1/console.058b624e.log?sv=2019-07-07&se=2022-03-28T16%3A54%3A14Z&sr=c&sp=rl&sig=YdJ8Xx3tZOPDJuohFwjLA9Cu77Im63rWqACq%2F5Fp8rY%3D|libraries_test_run_release_mono_interpreter_Linux_x64_Debug                                                                                                                                                                                                           |runtime                                                    |ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/65889/merge|
|2022-03-08T23:40:51.623Z|System.Text.Json.Tests  |Timeout               |https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65860-merge-e19bc9b92f0c498997/System.Text.Json.Tests/1/console.49870408.log?sv=2019-07-07&se=2022-03-28T23%3A40%3A10Z&sr=c&sp=rl&sig=1feJedJIo4waqqxe3K0oh1h%2B5sSqDr0kQP4RLFwqYD8%3D|libraries_test_run_release_mono_interpreter_Linux_x64_Debug                                                                                                                                                                                                           |runtime                                                    |ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/65860/merge|
|2022-03-08T23:59:18.957Z|System.Text.Json.Tests  |Timeout               |https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66307-merge-56bd84c864294c0096/System.Text.Json.Tests/1/console.d8d7386f.log?sv=2019-07-07&se=2022-03-28T23%3A58%3A20Z&sr=c&sp=rl&sig=HCrw352TEoX%2FpR89OUtHPeO0HQ0Yhh7JAe6EE1Y8y5o%3D|libraries_test_run_release_mono_interpreter_Linux_x64_Debug                                                                                                                                                                                                           |runtime                                                    |ubuntu.1804.amd64.open.rt|pr/public/dotnet/runtime/refs/pull/66307/merge|

**Comment by eiriktsarpalis** [comment]
> Is this expected to take a long time on mono interpreter / should it be disabled (looks like some other Json tests are disabled that way)?

The test logic itself is a fairly trivial unit test, however it does run as an isolated process using `RemoteExecutor` which on its own should contribute substantial overhead. We have a handful of other RemoteExecutor tests in the project, but none of them have been disabled for mono (although we do disable them in netfx due to unrelated infrastructural errors).

Should we just slap a `SkipOnMono` attribute on the tests? Do we have an attribute for specifically excluding interpreted runs?

**Comment by lewing** [comment]
cc @BrzVlad

**Comment by BrzVlad** [comment]
I couldn't reproduce this hang locally
