### ISSUE TITLE
Language 'Norwegian' missing from drop-down in designer properties

### ISSUE THREAD

**Issue by codebolt** [dotnet/runtime#66379]
* .NET Core Version: 6.0.200

* Have you experienced this same bug with .NET Framework?:  No

**Problem description:**

Working in with the WinForms Designer in .NET Framework, I created several localizable Forms/User Controls where I used two languages: English (default) and Norwegian (language code 'no'). When I open these forms in VS 2022/.NET 6 (after using the migration tool), I can no longer find "Norwegian" in the language list. I can only find Norwegian Bokmål ('nb') and Norwegian Bokmål Norway ('nb-NO'):

![image](https://user-images.githubusercontent.com/1541670/157229760-8dd67867-78da-4bc9-bc5a-b8ded5ac204c.png)

I see that the (...).no.resx file is there, but because Norwegian is not in the language list I am unable to use it:

![image](https://user-images.githubusercontent.com/1541670/157229298-11de1eb8-fd2a-4576-9b6a-adac7f0a80e0.png)

**Expected behavior:**

Expected behavior is to select Norwegian (code 'no') in the list and see/edit the translated control.

**Minimal repro:**

To reproduce you would need to:
* Create a Forms application with a form in an old Visual Studio (.NET Framework)
* Create a translation with Language=Norwegian
* Convert the application to .NET 6 (using e.g. the migration tool)
* Load the form in VS2022
* You can no longer access the Norwegian translation in the designer

**Comment by jeffschwMSFT** [comment]
@RussKie thoughts on an area label?  I was about to transfer to winforms, but I see you transferred it to runtime

**Comment by RussKie** [comment]
@jeffschwMSFT my guess would be something to do with "CultureInfo" or how system languages are enumerated. The Windows Forms and VS are calling into https://github.com/dotnet/runtime/blob/main/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/CultureInfoConverter.cs.

**Comment by tarekgh** [comment]
@RussKie Culture enumerations depends on the underlying globalization libraries. It is the decision of the Unicode Standard through ICU to not enumerate the "no" culture. The current enumerated Norwgian cultures are 

```
nb ... Norwegian Bokmål
nb-NO ... Norwegian Bokmål (Norway)
nb-SJ ... Norwegian Bokmål (Svalbard & Jan Mayen)
nn ... Norwegian Nynorsk
nn-NO ... Norwegian Nynorsk (Norway)
```

Which I believe covers all cases for that language. right? `no` by itself is not a language. 

The .NET prefers to stick with whatever the Unicode Standard decides for parity and consistency. If WinForm or VS want to include the "no" in their list for any compatibility reasons, they can do that as we still allow creating `no` culture if you do that manually. Like `CultureInfo.GetCultureInfo("no")`. This will work fine. 

In general, depending on the enumerated cultures and assume, will never change is a wrong assumption and no one should depend on that. 

Could you take this issue back to WinForm repo?

**Comment by tarekgh** [comment]
@jefgen looking at https://github.com/unicode-org/cldr/pull/1031, what ICU version will have this change? Why is the ICU version on Windows not having this change?

**Comment by jefgen** [comment]
The changes for that PR were done for [CLDR-14493](https://unicode-org.atlassian.net/browse/CLDR-14493), which was integrated into ICU 69.

It makes "no" become a parent locale for both "nb" and "nn", instead of "nb" being deprecated and aliasing to "no". This change matches with now NLS handles the locales. However, IIRC, in ICU 68, "no" is aliased to "nb", so it wouldn't be enumerated.

The Windows ICU version hasn't yet been updated to pick up a newer version of public ICU yet.

**Comment by tarekgh** [comment]
> The Windows ICU version hasn't yet been updated to pick up a newer version of public ICU yet.

Thanks @jefgen, is it scheduled yet when the ICU will get updated?

**Comment by tarekgh** [comment]
I am closing this issue as the ICU update should fix this issue. @jefgen may inform us when this will happen.
