### ISSUE TITLE
Updating to latest VS `17.1.1` and SDK `6.0.201` breaks web application builder

### ISSUE THREAD

**Issue by petarpetrovt** [dotnet/runtime#66383]
### Description

My application stopped working after updating to lastest VS `17.1.1` and SDK `6.0.201`.

Related - PR #62209, issue #61747
```
Unhandled exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'ConfigurationManager'.
   at Microsoft.Extensions.Configuration.ReferenceCountedProviderManager.AddProvider(IConfigurationProvider provider)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.<>c__DisplayClass25_0.<Build>b__2(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
```

### Reproduction Steps

-

### Expected behavior

Not throw `ObjectDisposedException` exception.

### Actual behavior

Throws `ObjectDisposedException` exception.

**Comment by atakanozceviz** [comment]
As a workaround, using `mcr.microsoft.com/dotnet/aspnet:6.0.2` image and `Microsoft.Extensions.Configuration` version `6.0.0` nuget package seems to work.

**Comment by sanderbos1402** [comment]
having the same issue. installed 6.0.102 SDK and nuget 6.0.0 package but this does not seem te help....

**Comment by sanderbos1402** [comment]
I'll ask a coworker. I am in the middle of a complete reinstall using an older version, hoping that will work....

**Comment by atakanozceviz** [comment]
To reproduce the problem:

1. Create a new template webapi project
2. Add `Microsoft.Extensions.Configuration` nuget package to the project:

```
<PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
```

3. Create an extension class:

```csharp
public static class ConfigurationExtension
{
    public static TModel GetConfiguration<TModel>(this IServiceCollection services, string settingsSectionName)
        where TModel : new()
    {
        using var serviceProvider = services.BuildServiceProvider();
        var configuration = serviceProvider.GetService<IConfiguration>();
        var model = new TModel();
        if (configuration == null) return model;
        configuration.GetSection(settingsSectionName).Bind(model);
        return model;
    }
}
```

4. Execute the extension method:

```csharp
builder.Services.GetConfiguration<WeatherForecast>("");
```

**Comment by StratosBlue** [comment]
@atakanozceviz 

- In most cases. Do not build ServiceProvider repeatedly.
- When use miniapi. Maybe you can access IConfiguration by `builder.Configuration` instead of ServiceProvider.

In fact 
```C#
var configuration = serviceProvider.GetService<IConfiguration>();
```
will get the same object as `builder.Configuration`.

And this `using`
```C#
using var serviceProvider = services.BuildServiceProvider();
```
will dispose all disposeable object in serviceProvider. So that the ConfigurationManager was disposed.

**Comment by CristianYairGutierrez** [comment]
were you able to fix it? i have the same problem just today

**Comment by arwa-techpk** [comment]
It was working fine for previous SDK 6.0.100 & VS.
To confirm the error that it is with this update. I updated my VS, using VS installer. And it take 1.4GB of update.
And then this error start showing

**Comment by BrennanConroy** [comment]
This issue is being tracked by https://github.com/dotnet/aspnetcore/issues/40614

**Comment by sanderbos1402** [comment]
changing the logic from using services.BuildServiceProvider and then constructing the service works as expected.
This just means we have to change out dependency injection helper methods that use this logic.
But this seams to solve all the problems

**Comment by appliedmarks** [comment]
I also just hit this issue with the latest VS version and SDK.  I just tried running my project working on .NET 6 until the update.  I tracked it down to an extension method that had a using var sp = services.BuildServiceProvider()

```
    public static async Task AddExchangeRatesAsync(this IServiceCollection services)
    {
        try
        {
            using var sp = services.BuildServiceProvider();
```
And then got the same object disposed exception in my Program.cs (Main) class.  For now (to get my project running), I am removing the "using" keyword within the extension method.

**Comment by maryamariyan** [comment]
cc @halter73

**Comment by sedederede** [comment]
I know that this is still opened but I'm wondering if 17.1.3 Visual Studio already included that fixed.  Any information?

**Comment by code-bode** [comment]
I have downloads the latest version of Visual Studio 17.1.3 and it's still not fixed. I think it's tagged to fix in version 7.0.0?

<img width="409" alt="image" src="https://user-images.githubusercontent.com/98618698/161640741-63686a92-21dc-41e9-9de9-667af69c015e.png">

I am still having same issue and for fix I am doing what @appliedmarks suggested.

**Comment by BrennanConroy** [comment]
This will be fixed in 6.0.4, you'll need to wait another week or so.

**Comment by maryamariyan** [comment]
Closing, if could not reconfirm the fix please reopen again. Thanks

**Comment by code-bode** [comment]
I have updated to latest version `6.0.4` and still getting the same error.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/98618698/163834055-9b34ea15-cfbe-4772-b172-c822054e0441.png">

**Comment by BrennanConroy** [comment]
You're still on 6.0.3
![image](https://user-images.githubusercontent.com/7574801/163834666-a8ea3847-9761-4e89-b319-42295aa1cd73.png)

**Comment by code-bode** [comment]
@BrennanConroy Thanks for quick reply. It is working after updating the hosting bundler to 6.0.4.
