### ISSUE TITLE
InvokeVoidAsync Performance Issue arch-wasm

### ISSUE THREAD

**Issue by xinsiyu2008** [dotnet/runtime#66384]
About arch-wasm.
I found it very bad when I called “InvokeVoidAsync” from .Net every 200ms, but it work well in .Net5. After 10 minutes the pages will be very laggy in .Net6. For example, I usually update the coordinates in the js function. I think this is a fatal bug.

OS:  windows7
x64

**Comment by lewing** [comment]
@xinsiyu2008 I'm not sure I completely understand your problem.  Can you provide sample code that demonstrates the issue you are seeing?

**Comment by xinsiyu2008** [comment]
@lewing  I have wrote a test example and found that it may be caused by SignalR at last.
https://pan.baidu.com/s/16hnavsmgBXft9SEVZLvGGg 
code: g9q9
Performance issues found after one hour .
![TestCode](https://user-images.githubusercontent.com/12785429/158003747-cc691a3d-042a-4d2c-84c8-cc654a065fa9.png)

**Comment by maraf** [comment]
@xinsiyu2008 Both uploads already expired. Can you please reupload your sample code?

**Comment by xinsiyu2008** [comment]
@lewing I update the link.Thanks!

**Comment by maraf** [comment]
@xinsiyu2008 I'm having problems replicating your issue on my machine. Some additional info might help me.

- Are you running the application in Debug or Release? From Visual Studio or published?
- Why are numbers on .NET 6 screenshot under 200? Did you commented out the delay in the SignalR hub?
- Is the performance problem the single long delay from the screenshot or is the tab laggy in general?

**Comment by xinsiyu2008** [comment]
@maraf Thanks for your help.
1.  The above example is running directly in visaul stuido as debug. I wrote a product in a similar fashion and had the same problem, window 7 , release mode.
2. The codes in .net5 and .net6 are the same, and the effect is the same in the first hour of running, but after more than an hour, the value of .net6 is not stable, and it is obviously lower than 200 at the beginning. The actual situation is that these values are all without data, the real valid data is far more than 200. As you can see, it is already 1464, which causes problems in the program. I didn't know about the delay codes in SignalR hub.
3. That is impossible, the running environment of the above demo is the same. But the results vary.

**Comment by maraf** [comment]
Sorry for late response, it took some time to investigate. I believe that the problem was fixed the https://github.com/dotnet/runtime/pull/62705, which was release as 6.0.2.

I'm not able to simulate the issue on > 6.0.2 nor on preview of .NET 7.

Can you please verify that it works on 6.0.2 or newer?

**Comment by xinsiyu2008** [comment]
@maraf Good Job,it's works for me. Thanks a million!

**Comment by maraf** [comment]
I'm happy hear that!

I'm going to close the issue now. Feel free to reopen it when you have more questions.
