### ISSUE TITLE
Mono EventPipe test suite crash

### ISSUE THREAD

**Issue by stefan-sf-ibm** [dotnet/runtime#66382]
In order to run the test suite `src/mono/mono/eventpipe/test` I have build the runtime and set CMake variable `ENABLE_EVENTPIPE_TEST` which results in `artifacts/obj/mono/Linux.x64.Debug/mono/mini/ep-test` being created. However, running the executable `ep-test` results in a crash:

```
test_setup: * Assertion at /runtime/src/mono/mono/metadata/assembly.c:3096, condition `corlib' not met
```

Anything I'm missing in order to execute the test suite?

### Configuration

- Ubuntu 20.04
- x64
- .NET SDK 6.0.100 (commit 9e8b04bbff) build against Mono as primary runtime flavor

**Comment by stefan-sf-ibm** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

@lateralusX

**Comment by lateralusX** [comment]
You will need to point it to Mono's System.Private.CoreLib.dll by setting CORE_ROOT.

**Comment by stefan-sf-ibm** [comment]
That works just fine. Thanks!
