### ISSUE TITLE
Odd behaviour when unzipping unicode string on net6.0 compared to netcoreapp3.1 and net5.0

### ISSUE THREAD

**Issue by tomstreet** [dotnet/runtime#66405]
### Description

While upgrading one of our projects from netcoreapp3.1 to net6.0 I found a method that that decompressed a unicode string from a byte array. The implementation of this method is certainly one way to do it, but ultimately it does work and has been working fine on netcoreapp3.1. When I upgraded the project to net6.0 this method started to return a messed up string sometimes, but not all the time. This character started appearing: �

I've tried to find a documented breaking change that would cause this but I've had no luck.

### Reproduction Steps

I have knocked up a quick example app to show what happens - it's a bit odd but it does reliably reproduce the behaviour.

It's quite simple - compress a string then decompress it using the two different implementations and compare the decompressed strings to the original. I'm just using the result of google.com as the string as it appears to change each time and sometimes causes the odd behaviour.

Drop this into a net6.0 console app and you will see it sometimes fails - usually fails within 10 tries. Change the TargetFramework to net5.0 and it passes every time (and loops infinitely), change to netcoreapp3.1 and it also passes every time. Change back to net6.0 and it starts failing again.

```c#
    public class Program
    {
        public static async Task Main(string[] args)
        {
            var gotPass = false;
            var gotFail = false;

            // Basically loop round to find one string that passes the test and one that fails
            while (!gotFail || !gotPass)
            {
                // This is different each time we get it - some pass, some fail
                var someString = await new HttpClient().GetStringAsync("https://www.google.com");

                // Compress it
                var zipped = Zip(someString);

                // Decompress it using the two different implementations
                var uz1 = Unzip1(zipped);
                var uz2 = Unzip2(zipped);

                // Test that the decompressed string should equal the original string before compression
                Console.WriteLine($"uz1 equal: {uz1 == someString}");
                Console.WriteLine($"uz2 equal: {uz2 == someString}");

                if (uz1 != someString)
                {
                    gotFail = true;
                }
                else
                {
                    gotPass = true;
                }
            }
        }

        // This is the method that sometimes breaks, but has been working fine
        static string Unzip1(byte[] compressedBytes)
        {
            var unZipped = new StringBuilder();
            byte[] writeData = new byte[1024];

            using var mem = new MemoryStream(compressedBytes);
            using var gZip = new GZipStream(mem, CompressionMode.Decompress);

            while (true)
            {
                int size = gZip.Read(writeData, 0, writeData.Length);

                if (size > 0)
                {
                    unZipped.Append(Encoding.Unicode.GetString(writeData, 0, size));
                }
                else
                {
                    break;
                }
            }

            return unZipped.ToString();
        }

        // This one works fine all the time
        static string Unzip2(byte[] compressedBytes)
        {
            using var compressedStream = new MemoryStream(compressedBytes);
            using var uncompressedStream = new MemoryStream();
            using var gzipStream = new GZipStream(compressedStream, CompressionMode.Decompress);

            gzipStream.CopyTo(uncompressedStream);

            var bytes = uncompressedStream.ToArray();

            return Encoding.Unicode.GetString(bytes);
        }

        static byte[] Zip(string str)
        {
            using var uncompressed = new MemoryStream(Encoding.Unicode.GetBytes(str));
            using var compressed = new MemoryStream();
            using var gzip = new GZipStream(compressed, CompressionMode.Compress);

            uncompressed.CopyTo(gzip);
            gzip.Flush();

            return compressed.ToArray();
        }
    }
```

### Expected behavior

I expected the net6.0 behaviour to be the same as the net5.0 and netcoreapp3.1 behaviour.

### Actual behavior

net6.0 is sporadically different to net5.0 and netcoreapp3.1 - see repro

### Regression?

Possibly - worked fine in netcoreapp3.1 and net5.0. Unable to find any documented breaking change related to this.

### Configuration

.NET SDK (reflecting any global.json):                  
 Version:   6.0.101                                     
 Commit:    ef49f6213a                                  
                                                        
Runtime Environment:                                    
 OS Name:     Windows                                   
 OS Version:  10.0.22000                                
 OS Platform: Windows                                   
 RID:         win10-x64                                 
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\      
                                                        
Host (useful for support):                              
  Version: 6.0.1                                        
  Commit:  3a25a7f1cc

**Comment by stephentoub** [comment]
> int size = gZip.Read(writeData, 0, writeData.Length);

Stream.Read is not guaranteed to return the amount of data requested.  GZipStream.Read in particular used to happen to do so in some cases where it no longer does:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by tomstreet** [comment]
Thanks. Don't know how I managed to miss this - it's right there under breaking changes!
