### ISSUE TITLE
On macOS, dotnet process seems to launch itself several times and maxes out CPU

### ISSUE THREAD

**Issue by bmitc** [dotnet/runtime#66419]
### Describe the bug
I was unsure whether to file this under `dotnet/runtime` or `dotnet/sdk`, so I started here.

Every now and then, my Macbook Pro's fans kick into high gear. Upon inspection of Activity Monitor, I've noted that `dotnet` has seemingly launched itself several times (I have witnessed anwhere from 1-4 separate `dotnet` processes running), and each `dotnet` process is pegging the CPU at 100%.

![image](https://user-images.githubusercontent.com/65685447/148825579-18b1b18b-6272-45c5-a76f-822b6aa01521.png)

From what I can tell, it has happened even without Visual Studio Code or Visual Studio for Mac being open at the time. This morning, when the above screenshot was taken, neither of those applications were open, and I wasn't doing anything with `dotnet` in the terminal. The most I did earlier today as far as user actions go is that I closed VS Code, which had a .NET Interactive notebook open. I'm unaware if that's where the `dotnet` processes got their start, but the maxing out the CPU came much later after closing VS Code.

### To Reproduce

I do not have any reproducing steps at the moment as this seems to happen on its own. I am hoping that someone has some commands I can run the next time this happens so that I can inspect things a little more.

### Further technical details
- Include the output of `dotnet --info`
    ```
    .NET SDK (reflecting any global.json):
     Version:   6.0.101
     Commit:    ef49f6213a

    Runtime Environment:
     OS Name:     Mac OS X
     OS Version:  12.0
     OS Platform: Darwin
     RID:         osx.12-x64
     Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

    Host (useful for support):
      Version: 6.0.1
      Commit:  3a25a7f1cc

    .NET SDKs installed:
      3.1.409 [/usr/local/share/dotnet/sdk]
      3.1.414 [/usr/local/share/dotnet/sdk]
      3.1.415 [/usr/local/share/dotnet/sdk]
      3.1.416 [/usr/local/share/dotnet/sdk]
      5.0.203 [/usr/local/share/dotnet/sdk]
      5.0.402 [/usr/local/share/dotnet/sdk]
      5.0.403 [/usr/local/share/dotnet/sdk]
      5.0.404 [/usr/local/share/dotnet/sdk]
      6.0.101 [/usr/local/share/dotnet/sdk]

    .NET runtimes installed:
      Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download
    ```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
    * VS Code
        ```
        Version: 1.63.2 (Universal)
        Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
        Date: 2021-12-15T09:37:28.172Z (3 wks ago)
        Electron: 13.5.2
        Chromium: 91.0.4472.164
        Node.js: 14.16.0
        V8: 9.1.269.39-electron.0
        OS: Darwin x64 21.1.0
        ```
    * Visual Studio for Mac Community
        ```
        8.10.16 (build 2)
        ```

**Comment by bmitc** [comment]
I am thinking this is a .NET Interactive thing at this point as well. I haven't seen this issue since posting it, but I have not been using .NET Interactive in VSCode since then either (on macOS).

**Comment by jeffschwMSFT** [comment]
Is it possible to capture a dump of these processes?  That would help us determine what is running and why it may be consuming so much cpu.  Thanks

**Comment by bmitc** [comment]
@jeffschwMSFT Would that be something like `Sample Process` or `SpinDumb` in macOS' Activity Monitor? I did them for just a random process and they seemed like a dump. Haha.

I will try to spin up some .NET Interactive notebooks sometime soon and see if I get this to reproduce again.

**Comment by jeffschwMSFT** [comment]
Try using https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump

cc @tommcdon

**Comment by ericstj** [comment]
Another thing to try is `ps -afx` from the terminal.  It will list out more information about the running process, like its command-line arguments, which could help you deduce what it is.  `dotnet` only means that it's running the .NET host, it could be anything.

**Comment by bmitc** [comment]
I am fairly certain this was probably caused by using .NET Interactive in Visual Studio code on macOS, and I only ever used the F# kernel when doing so. However, I don't use .NET Interactive on macOS currently and haven't for a while. This issue doesn't occur on Windows.

Given how macOS has gone through some upgrades and .NET Interactive is being continuously worked on and updated/improved, I'd be in favor of closing this and then re-opening it if necessary now that some debug information capture steps have been posted above.

I could try and reproduce this this weekend on a macOS laptop, but I remember it happening intermittently.

**Comment by danmoseley** [comment]
Thanks for the update. I'll close, feel free to open if you do repro with latest.
