### ISSUE TITLE
Failure processing application bundle. @area-Single-File

### ISSUE THREAD

**Issue by egbertn** [dotnet/runtime#66442]
### Description

When publishing a .net 6.0 (sdk 101 and 202) on an ubuntu x64 system, 
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle
occurs.

### Reproduction Steps

Install either .net sdk 101 or 202 on ubuntu (I have 20.04)
publish a .net core 6.0 console project with
dotnet publish --os linux --self-contained false -c Release /p:PublishSingleFile=true -o somepath

Run the file 
On one Ubuntu 20.04 system, it fails with above message on an other, with different hardware, but still x64 it succeeds.

### Expected behavior

It should not crash.

### Actual behavior

On my Laptop, Linux Ubuntu 20.04 , it will crash.
Linux lahdidah 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Architectuur:                    x86_64
CPU-modus(sen):                  32-bit, 64-bit
Bytevolgorde:                    Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU's:                           8
Online CPU's-lijst:              0-7
Draden per kern:                 2
Kernen per voet:                 4
CPU-voeten:                      1
NUMA-nodes:                      1
Producent-ID:                    GenuineIntel
CPU-familie:                     6
Model:                           140
Modelnaam:                       11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
Stepping:                        1
CPU-frequentie (MHz):            2800.000
max. CPU-frequentie (MHz):       4700,0000
min. CPU-frequentie (MHz):       400,0000
BogoMIPS:                        5606.40
Virtualisatie:                   VT-x
L1d-cache:                       192 KiB
L1i-cache:                       128 KiB
L2-cache:                        5 MiB
L3-cache:                        12 MiB
NUMA-node0 CPU('s):              0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RS
                                 B filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Vlaggen:                         fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rd
                                 tscp lm constant_tsc art arch_perfmon pebs bts 
                                 rep_good nopl xtopology nonstop_tsc cpuid aperf
                                 mperf tsc_known_freq pni pclmulqdq dtes64 monit
                                 or ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr 
                                 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc
                                 _deadline_timer aes xsave avx f16c rdrand lahf_
                                 lm abm 3dnowprefetch cpuid_fault epb cat_l2 inv
                                 pcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_en
                                 hanced tpr_shadow vnmi flexpriority ept vpid ep
                                 t_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 er
                                 ms invpcid rdt_a avx512f avx512dq rdseed adx sm
                                 ap avx512ifma clflushopt clwb intel_pt avx512cd
                                  sha_ni avx512bw avx512vl xsaveopt xsavec xgetb
                                 v1 xsaves split_lock_detect dtherm ida arat pln
                                  pts hwp hwp_notify hwp_act_window hwp_epp hwp_
                                 pkg_req avx512vbmi umip pku ospke avx512_vbmi2 
                                 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg 
                                 avx512_vpopcntdq rdpid movdiri movdir64b fsrm a
                                 vx512_vp2intersect md_clear flush_l1d arch_capa
                                 bilities

On another system, Ubuntu Server 20.04 it will run.
Linux lahdidah2 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7302P 16-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1497.602
CPU max MHz:                     3000.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5988.83
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        128 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filli
                                 ng
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxs
                                 r sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl n
                                 onstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse
                                 4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy ab
                                 m sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_
                                 nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcal
                                 l fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveop
                                 t xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf
                                  xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid 
                                 decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_rec
                                 ov succor smca

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /opt/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.101 [/opt/dotnet/sdk]
  6.0.201 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

### Regression?

This happened before #1632
but it may have a different cause.

### Known Workarounds

Publish as selfcontainted executable, works around the issue.  
--self-contained true

### Configuration

with Sdk 6.0 101 and 202
See above for hardware specs

### Other information

The only thing I -could- think of, but far fetched, is that my laptop system defaults to dutch, the server does not. That would mean, that a language resource is not correctly bundled.

**Comment by egbertn** [comment]
@area-Single-File

**Comment by vitek-karas** [comment]
Could you please try this:
* `export COREHOST_TRACE=1`
* `export COREHOST_TRACEFILE=host.txt`
* repro the problem
* collect the `host.txt` file

Please note that the trace will contain information like local paths, environment variables and potentially other information about the machine. If you're OK with that, please share the trace file.

**Comment by egbertn** [comment]
Tracing enabled @ Thu Mar 10 11:15:34 2022 GMT
--- Invoked apphost [version: 6.0.3, commit hash: c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663] main = {
./CB_Room40
}
The managed DLL bound to this executable is: 'CB_Room40.dll'
Detected Single-File app bundle
Looking for architecture specific install_location file in '/etc/dotnet/install_location_x64'.
The install_location file ['/etc/dotnet/install_location_x64'] does not exist - skipping.
Looking for install_location file in '/etc/dotnet/install_location'.
The install_location file ['/etc/dotnet/install_location'] does not exist - skipping.
Using global installation location [/usr/share/dotnet] as runtime location.
Reading fx resolver directory=[/usr/share/dotnet/host/fxr]
Considering fxr version=[5.0.14]...
Detected latest fxr version=[/usr/share/dotnet/host/fxr/5.0.14]...
Resolved fxr [/usr/share/dotnet/host/fxr/5.0.14/libhostfxr.so]...
Invoking fx resolver [/usr/share/dotnet/host/fxr/5.0.14/libhostfxr.so] hostfxr_main_bundle_startupinfo
Host path: [/home/maran/projects/Room40/publish/CloudSync/x64/CB_Room40]
Dotnet path: [/usr/share/dotnet]
App path: [/home/maran/projects/Room40/publish/CloudSync/x64/CB_Room40.dll]
Bundle Header Offset: [b1f2c0]
Tracing enabled @ Thu Mar 10 11:15:34 2022 GMT
--- Invoked hostfxr_main_bundle_startupinfo [commit hash: d5b56c6327f380de399a2f95ca6045f03c92a66d]
Mapped application bundle
Failure processing application bundle.
Bundle header version compatibility check failed.
A fatal error occured while processing application bundle

**Comment by egbertn** [comment]
You can mark this as solved. .net 6 was installed in /opt/dotnet
and in the past, v5 was installed in /usr/share/dotnet
After removing /usr/share/dotnet it works.
Also it was necessary in my case to do this...
export DOTNET_ROOT=/opt/dotnet
somehow the loading process still was looking for /usr/share/dotnet

**Comment by vitek-karas** [comment]
The `/usr/share/dotnet` is the default install location - so any .NET program knows to look there. Any other location needs to be somehow specified, either via env. variable (`DOTNET_ROOT`) or registered in config `/etc/dotnet/install_location`. For more details see [Install locations](https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md) and for multi-arch systems also [Install locations per architecture](https://github.com/dotnet/designs/blob/main/accepted/2021/install-location-per-architecture.md).

So if you want to have a global installation in a custom directory (like `/opt/dotnet`) just put path to that location into `/etc/dotnet/install_location` (the file can contain a single line which is the path, nothing else). With that there won't be a need for any environment variables (other than putting it onto `PATH` if you want to be able to just type `dotnet` from anywhere) and it will be used the default/global runtime.
