### ISSUE TITLE
DateOnly data type not resolved in net5.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#66457]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DateOnly-data-type-no-longer-responsive/1578195)._

---
![Screenshot (1).png](https://aka.ms/dc/image?name=Be1f88f91dc034888998b8ed2dc88f8d9637721340544469394_Screenshot_(1).png&tid=e1f88f91dc034888998b8ed2dc88f8d9637721340544469394)

---
#### Feedback Bot on 11/10/2021, 06:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/11/2021, 09:37 AM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

#### Feedback Bot on 2/9/2022, 11:27 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by stephentoub** [comment]
DateOnly was introduced in .NET 6.  It doesn't exist in .NET 5.
