### ISSUE TITLE
[API Proposal]: `Math.Percentile(double[] sequence, double percentile)`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#66454]
### Background and motivation

Help to calculate percentile more efficiently

### API Proposal

```C#
namespace System
{
    public static class Math
    {
        public static double Percentile(double[] sequence, double percentile)
    }
}
```

### API Usage

```C#
var values = new[]{ 0.8, 0.2, 0.3, 0.9, 1.2};

var p90 = Math.Percentile(values. 0.9);
var p95 = Math.Percentile(values. 0.95);
```

### Alternative Designs

Maybe we could consider using the [`INumber`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/INumber.cs) to allow `int[]`/`float[]` and more

### Risks

Should be fine since it will be a new API

**Comment by tannergooding** [comment]
I'm not personally convinced this is worthwhile to expose in the BCL.

Noting that I do think this can be a useful function. However, this isn't a function that is commonly provided by other runtimes, but rather more often by additional dependencies you pull in. Likewise, it isn't a function that requires an overly complex implementation or even specialized IEEE 754 handling logic to guarantee correctness/determinism.

**Comment by charlesroddie** [comment]
There would need to be multiple settings for this as percentile has a horrible multiplicity of definitions.

https://en.wikipedia.org/wiki/Percentile gives several, of which 3 are extremely impure (linear interpolation, which treats the data as an approximation to some reality, and which has the property that duplicating the data changes the percentile calculations), 1 is moderately pure (nearest-rank) and doesn't satisfy the desirable property that the median is the 50th percentile. A moderately pure one which does satisfy that property is not given.

The difficulty is that the cdf is not injective, so defining a single number for the inverse leads to multiple points of view.

**Comment by WeihanLi** [comment]
@tannergooding @charlesroddie , great thanks for your reply, it's fine for me, I'm using `MathNet.Numerics` for it now.
