### ISSUE TITLE
Yum mirror for EL7 (https://packages.microsoft.com/rhel/7/prod/) has incorrect metadata.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#66459]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Yum-mirror-for-EL7-https:packagesmic/1594610)._

---
[severity:It's more difficult to complete my work]
It seems that a metadata package inside of the repo is not up to date (even though the time stamps are). We are getting this error from our syncing process:
Error: An error occurred during the sync
{"checksum_type"=>"sha256", "expected_checksum"=>"6d9d4e5f2d50367aee889237fd29af87f95c95abbda0549dd9e318daa0c89a55", "error_code"=>"checksum_mismatch", "name"=>"dotnet-sdk-5.0", "actual_checksum"=>"5094b32ea172fdb7c8d15e1558501c35659aac9e52c6c203cbcfa52bb325574f"}

Looking closely at the error, it is what is shows, the package: sha256sum dotnet-sdk-5.0.202-x64.rpm has a different sha256 signature than what is in the repo metadata:
! [image.png] (https://aka.ms/dc/image?name=Bab80595f4c4a4e328863ed35bacc3376637733403499146650_20211124-094549-image.png&tid=ab80595f4c4a4e328863ed35bacc3376637733403499146650)

! [image.png] (https://aka.ms/dc/image?name=B44d101ccd3084b4db3c5a7b20c7ef883637733403683294760_20211124-094607-image.png&tid=44d101ccd3084b4db3c5a7b20c7ef883637733403683294760)

Can you clean up the metadata, this will simplify us syncing with your repository.

Thank you.

---
#### Feedback Bot on 11/24/2021, 09:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Beat Rubischon on 1/14/2022, 01:45 AM: 

<p>I’m able to confirm the issue still exists today. Strange enough it hurts me since several months, even new packages were added to the repo, usually triggering a refresh of the metadata.</p>

#### Feedback Bot on 3/1/2022, 11:52 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by NikolaMilosavljevic** [comment]
Has not reproed in a long time.
