### ISSUE TITLE
[API proposal]: add ProcessStartInfo constructor that accepts IEnumerable<string> arguments.

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#66450]
## Background and motivation

Starting a process should be easy when you have an `IEnumerable<string>` with arguments.

This is true if you can use the static `Process.Start` overload that accepts an `IEnumerable`.

If you need to use `ProcessStartInfo` to make additional configuration, like redirecting the streams, there is no way to pass in the `IEnumerable<string>`.

`Process.ArgumentList` is a `Collection<string>`. Because it doesn't have an `AddRange`, the user needs to add a loop to add the arguments one-by-one.

## API Proposal

A constructor can be added to `ProcessStartInfo`.

```cs
 ProcessStartInfo(string fileName, IEnumerable<string> arguments)
```

This is consistent with rest of the API of `Process` where `IEnumerable<string>` overloads were added to existing APIs that accepted `string arguments`.

## API Usage

```cs
ProcessStartInfo psi = new("filename", GetArguments());
```

## Risks

**Comment by adamsitnik** [comment]
@tmds I am supportive of this idea. Could you please fill the [official template](https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.yml&title=%5BAPI+Proposal%5D%3A+)?

**Comment by tmds** [comment]
@adamsitnik is this good for `api-ready-for-review `?

**Comment by adamsitnik** [comment]
@tmds it's is, I've applied the label. Thanks!

**Comment by bartonjs** [comment]
Looks good as proposed.

```C#
namespace System.Diagnostics
{
    public partial class ProcessStartInfo
    {
        public ProcessStartInfo(string fileName, IEnumerable<string> arguments);
    }
}
```
