### ISSUE TITLE
Loading .NET host via hostfxr process crashes with Fatal error. Failed to load JIT compiler

### ISSUE THREAD

**Issue by AudriusButkevicius** [dotnet/runtime#66475]
### Description

I am injecting/loading .NET host into my process, via:

(error checking removed to reduce verbosity)
```
load_hostfxr() // populate the pointers
hostfxr_handle cxt = nullptr;
hostfxr_initialize_for_runtime_config("path to config", null, &ctx)
void* load_assembly_and_get_function_pointer = nullptr;
hostfxr_get_runtime_delegate(ctx,  hdt_load_assembly_and_get_function_pointer, load_assembly_and_get_function_pointer )
hostfxr_close(ctx)

component_entry_point_fn entrypoint = nullptr;
load_assembly_and_get_function_pointer ("pathtodll", "Namespace, Namespace", "Run", null, null, &entrypoint);
entrypoint(nullptr, 0);
```

runtimeconfig.json:
```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "rollForward": "LatestMinor",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

Sometimes instead of the host being loaded, it prints `Fatal error. Failed to load JIT compiler` in the console, and crashes the process.

Seems to happen more often if the machine is under load/I am initialising the host in multiple different instances of the application around the same time.

I could not find any references to the error message anywhere in the runtime code to try and understand what exactly fails.

Worth noting that:
1. Initialisation of the host is not happening from the main application thread
2. The initialisation is not happening from the main application image, but from a shared library that the application loads.

The application in question is a vendor application that supports loading shared library "plugins", and we're initialising our "plugin" which initialises .Net host to run our managed code instead (as we prefer to have the plugin logic in a managed language)

### Reproduction Steps

Happens randomly, cannot work out how to reliably reproduce it.

### Expected behavior

Application loads .NET Host

### Actual behavior

Loading .NET Host crashes with `Fatal error. Failed to load JIT compiler` in the console.

### Known Workarounds

Restart the process and try again.

### Configuration

.NETCore.App 6.0
Windows 10
x64

**Comment by vitek-karas** [comment]
@BruceForstall @dotnet/jit-contrib any ideas about the JIT failing to load?

**Comment by BruceForstall** [comment]
That means LoadAndInitializeJIT() failed. There are many possibilities:
1. The JIT dll wasn't found (in the directory where coreclr.dll lives)
2. The OS couldn't load it (maybe due to missing dependency?)
3. The getJit entrypoint wasn't found or failed
4. The JIT GUID is not the same as the corclr.dll GUID (i.e., a JIT/VM mismatch)

If you have a failure dump, the `g_JitLoadData` structure can help identify where the failure occurred.

**Comment by AudriusButkevicius** [comment]
This is not a persistent error, namely the same application with exactly the same parameters will sometimes succeed and sometimes fail without any change to the environment.

In which case only 3 seems like a possible candidate.

What would be the best way to get a dump, given the process crashes outside of my control?
The only thing that comes to mind is setting the registry key that saves dumps for every key.

Could there be any reason why multiple instances initialising the host at roughly the same could cause this?
I assume there is no global state, possibility for tramping some files?

**Comment by BruceForstall** [comment]
> Could there be any reason why multiple instances initialising the host at roughly the same could cause this?
> I assume there is no global state, possibility for tramping some files?

There is a lock, so only one thread at a time should be initializing the JIT; multiple processes should be independent.

I wonder if maybe some kind of file or anti-virus locking of the JIT dll is causing the OS LoadLibrary to fail? Maybe Process Monitor (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) could help identify this?
