### ISSUE TITLE
[API Proposal]: `System.Math.Abs` overload for `System.Numerics.Complex` as `Complex.Magnitude` property

### ISSUE THREAD

**Issue by mettekou** [dotnet/runtime#66494]
### Background and motivation

Implement `System.Math.Abs` as [the `Complex.Magnitude` property](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.complex.magnitude?view=net-6.0), since this is [the mathematical definition of the absolute value of a complex number](https://en.wikipedia.org/wiki/Magnitude_(mathematics)#Complex_numbers).

### API Proposal

```C#
namespace System
{
    public static partial class Math
    {
        public double Abs(Complex complex);
    }
}
```

### API Usage

```C#
var magnitude = Math.Abs(new Complex(1, 1));
```

### Alternative Designs

Return `Complex` instead of `double`, to be consistent with other overloads of `Math.Abs`.

**Comment by mettekou** [comment]
A similar issue for F#: https://github.com/dotnet/fsharp/issues/12828.

**Comment by huoyaoyuan** [comment]
This isn't possible because `Math` is in the corelib, and `Complex` is in an upper level library, so `Math` can't use `Complex`.
However, it's reasonable to implement corresponding generic math interface for `Complex`.

**Comment by tannergooding** [comment]
`Complex.Abs` is what you want.

We largely don't expose APIs on `System.Math` unless its for a primitiver type and even that will likely be minimal moving forward. Instead, APIs will be exposed as `SomeType.Method()`, as most user-defined types would be expected to do.
