### ISSUE TITLE
dotnet --list-runtimes reports incorrect versions in specific circumstance

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#665]
### Repro:
_(Tested in clean Windows 10 sandbox)_
1. Install (important: **32-bit**!): https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-2.1.14-windows-x86-installer
2. Install: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.0-windows-x64-installer
3. Open powershell and enter `dotnet --list-runtimes`

### Results:
`Microsoft.NETCore.App 2.1.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]`
### Expected:
```
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

#### Side Note:
Installing x64 instead of x86 version of .NET Core 2.1.14 runtime gives expected results:
```
Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Seems to only happen on the x86 version.

**Comment by Gnbrkm41** [comment]
you'll need to execute the `dotnet.exe` under `C:\Program Files (x86)\dotnet\dotnet.exe` with `--list-runtimes` to get the list of x86 runtimes.

**Comment by Symbai** [comment]
So cmd dotnet.exe runs either a 32bit or a 64bit version and the 32bit version won't list up the 64bit runtimes?! Well this should definitely be documented then because currently it is not and it sounds like dotnet is a general tool listening up all runtimes https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet

**Comment by dagood** [comment]
Yeah, it's expected that the x86 dotnet.exe can only find the x86 runtimes, and same for the x64 dotnet.exe with x64 runtimes. https://github.com/dotnet/core-setup/issues/8683#issuecomment-548213879 has a few ways we think the behavior could be improved (and that issue tracks them in general).
