### ISSUE TITLE
JIT inlines bits of throw helpers

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#66527]
cc. @AndyAyersMS following a conversation on Discord.

### Description

I noticed that on .NET 6 the JIT is now sometimes inlining bits of throw helper methods, making the codegen worse in callers. Up until .NET 5, throw helpers were _always_ recognized properly as cold paths and codegen was much better in these cases. Consider this:

```csharp
using System;
using System.Runtime.CompilerServices;

static int Test_Guard(int x)
{
    Guard.IsLessThan(x, 10, nameof(x));
    
    return DoWork(x);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static int DoWork(int x)
{
    return 0;
}

public static class Guard
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void IsLessThan(int value, int maximum, string name)
    {
        if (value < maximum)
        {
            return;
        }

        ThrowArgumentOutOfRangeExceptionForIsLessThan(value, maximum, name);
    }
    
    private static void ThrowArgumentOutOfRangeExceptionForIsLessThan<T>(T value, T maximum, string name)
    {
        throw new ArgumentOutOfRangeException(name, value!, "Parameter {name} ({typeof(T)}) must be less than {maximum}, was {value}.");
    }
}
```

This now results in the following on .NET 6, Release x64:

```asm
<Program>$.<<Main>$>g__Test_Guard|0_0(Int32)
    L0000: push rsi                 ; prologue fluff
    L0001: sub rsp, 0x20
    L0005: mov esi, ecx             ; copy x
    L0007: cmp esi, 0xa             ; if (x >= 10)
    L000a: jge short L0018          ; goto throw helper
    L000c: mov ecx, esi
    L000e: add rsp, 0x20
    L0012: pop rsi
    L0013: jmp 0x00007ffd183f0028   ; tail call into DoWork(x)
    L0018: mov ecx, 1               ; ???
    L001d: mov rdx, 0x7ffd183fc060  ; ???
    L0027: call 0x00007ffd6dbd2ca0  ; ??? (I assume this is boxing or something?)
    L002c: mov r8, rax
    L002f: mov ecx, esi
    L0031: mov edx, 0xa
    L0036: call 0x00007ffd183f0058  ; finally call the throw helper
    L003b: int3
```

The throw helper pattern has always been one that you can rely on: if a method only has a single BB that throws, then the JIT will just handle it properly and mark it as a cold path. This is the whole reason why we don't use `NoInlining` on such methods. If the JIT still ends up inlining stuff from these methods then, it kinda defeats the whole purpose of setting them up this way.

You can add more parameters and calls to `Guard.IsLessThan` and observe the codegen get even worse. If you add `NoInlining` to the throw helper, things obviously improve a fair amount, but then of course you lose the JIT seeing it as a throw helper.

### Configuration

; Core CLR 6.0.121.56705 on amd64

### Sharplab repro

[**Click here**](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNZkga8eDACqqMAfQDiHbFAAmACj0YGCAJQ0A3jQZeGFq9ZYAkrgAMqq4BgAW2Fy2CGgM5HTOGtTeDJ7exADsDAAiEADq0ADWsck0AL6a1ADaALIwGBEQ1gHikrYNTS1tYpIA8mJ8EFy4LAByEAFcknp6AObOALpa5DoOeYUl9vou7hle2Qx0KVXUWgDMTGtMpD6WNvup3vWNza3tnW897YPDoywAILzeawXC4XgKGDTWZcBbLA5MK7aJgoBhBULgyLRHaOBTYSQcGDxDb4bAIfgcfDxGpCAnSKCAqDzKkwHgAUQQYjBEJGtgARPjCTB+ctrowuNgBAwALwMfmixEeZ5pLy8ABmDFsQqJDAAPAwyRT8FTXCrVcrVVamFkUtaGGdEWlIlAIAB3AASMEkYhkLBd7qZLIEPH6HAw/XVbGi8xgnJUQ14IwAYtAMWFsTEdcTDeTKdSGJKBOVzWc0ojuZDsBgYNcdGRDBFXZ7vb6oEqnd4APRdhgAVS4kHwIccTV4uAYGAgDFwMFrTVrkGsMFjXAYsccBHpMk7Xh7DFe3Q+fS+R96A0TIzGkxhcy4ixW5rSxGRN2IaIDbqDrND4cj0fvOMEATf5UygdMsSiLg9QMAA+WwDAYbN4kQo183iZgJSlGAzXtS17W8Jpm0LGA3QYb8RzDCMoxjICQKTGIixzbMAEJ4n5AAFKxsJrKAGDcJiKi1NwMAAT19CB1QQ5wKmcQ0OFwRxgFraRwUnKD+LQk18AqeI3TwfjswqFhRTta0y28M4KiAA)

### Regression?

Yes, this results in the correct (and better) codegen on .NET 5.

**Comment by AndyAyersMS** [comment]
cc @EgorBo

**Comment by EgorBo** [comment]
@Sergio0694 looks pretty normal to me, JitDisasm:
```asm
; Method Proga:Test_Guard(int):int
G_M1756_IG01:              ;; offset=0000H
       56                   push     rsi
       4883EC20             sub      rsp, 32
       8BF1                 mov      esi, ecx
						;; bbWeight=0    PerfScore 0.00

G_M1756_IG02:              ;; offset=0007H
       83FE0A               cmp      esi, 10
       7D0C                 jge      SHORT G_M1756_IG04
       8BCE                 mov      ecx, esi
						;; bbWeight=1    PerfScore 1.50

G_M1756_IG03:              ;; offset=000EH
       4883C420             add      rsp, 32
       5E                   pop      rsi
       E9108DFFFF           jmp      Proga:DoWork(int):int
						;; bbWeight=1    PerfScore 2.75

G_M1756_IG04:              ;; offset=0018H
       B901000000           mov      ecx, 1
       48BA48E081BAFE7F0000 mov      rdx, 0x7FFEBA81E048
       E8546F655F           call     CORINFO_HELP_STRCNS
       4C8BC0               mov      r8, rax
       8BCE                 mov      ecx, esi
       BA0A000000           mov      edx, 10
       E895F3FFFF           call     Guard:ThrowArgumentOutOfRangeExceptionForIsLessThan(int,int,System.String)
       CC                   int3     
						;; bbWeight=0    PerfScore 0.00
; Total bytes of code: 60
```

the unknown call you're observing is a lazy-string-literal-materialization. We know that this helper is unlikely to be invoked so we're not allocating a StringObject for `name` parameter

**Comment by Sergio0694** [comment]
Oooh ok that makes sense ahah
I was expecting just the usual `mov` from offset + indirect load so I was quite confused seeing that extra `call` 😆
Thank you for shedding light on this Egor, I can sleep well at night again now 😄
