### ISSUE TITLE
Microsoft.Extensions.Configuration.Json 5.0.0 cannot refer to System.Text.Json 5.0.1

### ISSUE THREAD

**Issue by RyanLiu99** [dotnet/runtime#66532]
For a project has both package installed, 
Microsoft.Extensions.Configuration.Json 5.0.0 cannot use  System.Text.Json 5.0.1
even it says it requires >= System.Text.Json 5.0.0.

Downgrade package System.Text.Json  to 5.0.0, then all works fine.

**Comment by huoyaoyuan** [comment]
I can't reproduce it. I can build the following project successfully.
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="5.0.1" />
  </ItemGroup>

</Project>
```

Can you share more about the error message?

**Comment by eiriktsarpalis** [comment]
@RyanLiu99 could you please share a standalone reproduction of the issue?

**Comment by RyanLiu99** [comment]
Indeed there is no problem.  

I created a new simple project, it works with either version System.Text.Json.

There must be some other libraries cause the trouble in my original big project. 

Thanks everyone.
