### ISSUE TITLE
C# dllmain with nativeaot

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#66546]
### Discussed in https://github.com/dotnet/runtime/discussions/66543

<div type='discussions-op-text'>

<sup>Originally posted by **AhmedZero** March 12, 2022</sup>
there is any way to add dllmain like C++ when compiling using Nativeaot
thanks.</div>

**Comment by jkotas** [comment]
There are significant limits on what can be safely done inside DllMain. See https://docs.microsoft.com/en-us/windows/win32/dlls/dllmain for details. It is not possible to safely run managed code inside DllMain due this limitation. The .NET runtime may internally call OS APIs that are prohibited inside DllMain.

If you need to run one-time initialization before any code in your module runs, you can use [ModuleInitializer](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers) just like you would in regular C# code. ModuleInitializers are executed in NativeAOT right before any managed code is executed (e.g. when your program `Main` method gets called or when the first `UnmanagedCallersOnly` method gets called).

**Comment by AhmedZero** [comment]
@jkotas I test [ModuleInitializer](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers) but not works in the shared library, I wanna use the library and execute codes without using any Exports API, just when Load Library.

**Comment by teo-tsirpanis** [comment]
@AhmedZero unfortunately there is no way to do what you want and this is by design. You need to change your system's architecture and export an `Init` function that will be called _after_ the library gets loaded. That's what the `DllMain` guidance recommends.

**Comment by AhmedZero** [comment]
@teo-tsirpanis it will support soon or not?
I don't need Dllmain, all I need, after executing loadlibrary, execute codes.

**Comment by teo-tsirpanis** [comment]
> I don't need Dllmain, all I need, after executing loadlibrary, execute codes.

The only way to execute custom code upon the loading of a DLL is through `DllMain`. Its limitations are due to Windows, not .NET, and have existed since decades ago. _There is no way out of this._

**Comment by AhmedZero** [comment]
thanks for your answer 👍 .

**Comment by Fabi** [comment]
> thanks for your answer 👍 .

You can basically create an export of DllMain and generate your own with that. 
This will result in an export called DllMain which automatically gets called by the dll entry point function and has the same behavior.

```csharp
                [UnmanagedCallersOnly(EntryPoint = "DllMain", CallingConvention = CallingConvention.StdCall)]
		public static bool DllMain( IntPtr hModule, uint  ul_reason_for_call, IntPtr lpReserved)
		{
			switch (ul_reason_for_call)
			{
				case 1:
					// Your attach code...
					break;
				default:
					break;
			}
			return true;
		}```

**Comment by jkotas** [comment]
> You can basically create an export of DllMain and generate your own with that.

You are likely going to see intermittent deadlocks and crashes with this approach, similar to what is described in https://docs.microsoft.com/en-us/cpp/dotnet/initialization-of-mixed-assemblies

**Comment by Fabi** [comment]
> > You can basically create an export of DllMain and generate your own with that.
> 
> You are likely going to see intermittent deadlocks and crashes with this approach, similar to what is described in https://docs.microsoft.com/en-us/cpp/dotnet/initialization-of-mixed-assemblies

It can happen but it's not likely to happen if you put your code carefully into that.

**Comment by jkotas** [comment]
You cannot control the runtime code and OS APIs that are called as part of `UnmanagedCallersOnly` transition. That runtime is code is not compatible with DllMain.
