### ISSUE TITLE
Attempting to write schema to writer throws exception

### ISSUE THREAD

**Issue by aviatrix** [dotnet/runtime#66557]
### Description

I'm attempting to infer XML schema from a series of XML files. For that purpose i've used the  `XmlSchemaInference` and `XmlSchemaSet` classes. 

The solution however throws an exception as follows : 
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Private.Xml.XmlSerializers, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL'. The system cannot find the file specified.'
```

### Reproduction Steps

```csharp
using System.Diagnostics;
using System.IO.MemoryMappedFiles;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Schema;
using System.Xml.Xsl;
using System.Xml.Serialization;
var basePath = @"Z:\xml\";
var files = Directory.GetFileSystemEntries(basePath, "*.xml", SearchOption.AllDirectories);

 XmlSchemaInference inference = new XmlSchemaInference();
inference.TypeInference = XmlSchemaInference.InferenceOption.Relaxed;
var sw = new Stopwatch();

XmlSchemaSet  schemaSet = inference.InferSchema(XmlReader.Create(files[0]));

foreach (var file in files.Skip(1).Take(50))
{
    sw.Restart();
    var reader = XmlReader.Create(file);
    inference.InferSchema(reader,schemaSet);
    Console.WriteLine($"File {file} took: {sw.Elapsed} ( {sw.ElapsedMilliseconds}ms )");
}
 Console.WriteLine("Original schema:\n");
var texW = new StringWriter();

foreach (XmlSchema schema in schemaSet.Schemas())
{
    schema.Write(texW); // <-- EXCEPTION OCCURS HERE
}

File.WriteAllTextAsync(@"Z:\inferred-schema.xsd", texW.ToString());
Console.WriteLine("done");
Console.ReadLine();
```

### Expected behavior

Should not throw an exception and should output xml schema

### Actual behavior

Throws exception

```
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Private.Xml.XmlSerializers, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL'. The system cannot find the file specified.'
```

### Configuration

.net core 6 ( console app)
Windows 11 (latest)
x64

**Comment by aviatrix** [comment]
Update: 
This seems to only happen if VS 2022 (have not tested with other  VS versions) debugger is attached.

**Comment by krwq** [comment]
I've just tried this: targeting net6.0 and also everything with VS2022 and I'm unable to repro (XSD gets successfully generated).

Can you please share following information:
- your csproj file
- how exactly are you running the app (i.e. are there any special checkboxes selected in VS from default configuration)

might not matter but might be a good idea to share the XML file(s) you're using (or just zip the project).

**Comment by Recurse-blip** [comment]
I'm having the same issue. 

I'm on VS 2022 17.1.6 with .net 6.

`Could not load file or assembly '[assembly name].XmlSerializers, Version=2.2.2, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL'. The system cannot find the file specified.'
`

**Comment by Recurse-blip** [comment]
Resetting my Visual Studio Settings fixed the issue.

**Comment by krwq** [comment]
If you find some specific condition which makes this not work please share and re-open (or create new issue), otherwise this is not actionable
