### ISSUE TITLE
PipeReader.ReadAtLeast API conformance

### ISSUE THREAD

**Issue by bentoi** [dotnet/runtime#66577]
The default `PipeReader.ReadAtLeastAsync` implementation relies on `PipeReader.ReadAtLeastAsyncCore` which is implemented as a loop calling `PipeReader.ReadAsync` and `PipeReader.AdanceTo` until the read data size is superior to the `minimumSize`.

A class extending the abstract `PipeReader` class inherits from this default implementation which has one pitfall: it always examines the full buffered data. As a result this code doesn't work:

```
writer.WriteAsync(new byte[100]);

ReadResult result = await reader.ReadAtLeastAsync(50);
// This throws InvalidOperationException because examined is inferior to the previous examined position
reader.AdvanceTo(result.Buffer.GetPosition(4)); 
```

This only works if the full data is consumed (`reader.AdvanceTo(50)`).

The default pipe reader or the stream pipe reader `ReadAtLeastAsync` implementations don't have this issue because they override `ReadAtLeastAsyncCore`. 

It might have been better to make `ReadAtLeastAsync` abstract and specify that it shouldn't examine the buffered data. I realize it's probably too late to change this however. Is this something you could document for the `ReadAtLeastAsyncCore` API?

I got caught by this with the implementation of a pipe reader wrapping a socket.

**Comment by adityamandaleeka** [comment]
Triage: let's add something like this to the ReadAtLeastAsync docs:

> By default this examines the returned buffer via AdvanceTo.
