### ISSUE TITLE
Test failure System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66571]
Run: [runtime-coreclr libraries-jitstressregs 20220313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1660907&view=ms.vss-test-web.build-test-results-tab&runId=45719236&paneView=debug&resultId=151261)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

net7.0-windows-Release-x64-CoreCLR_checked-jitstressregs0x10-Windows.10.Amd64.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

net7.0-windows-Release-x64-CoreCLR_checked-jitstressregs0x1000-Windows.10.Amd64.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector
```
**Error message:**
```
High limit handle did not trigger a GC
Expected: True
Actual:   False


Stack trace
```

Runfo Tracking Issue: [system.runtime.interopservices.handlecollectortests.testhandlecollector](https://runfo.azurewebsites.net/tracking/issue/323)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1728243](https://dev.azure.com/dnceng/public/_build/results?buildId=1728243)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68251](https://github.com/dotnet/runtime/pull/68251)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68251-merge-cd3db945a7a64425be/System.Runtime.InteropServices.Tests/1/console.62c8bf1b.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-10T13%25253A31%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuMIdQASNUTmY2XyV4LrfhRJblHlFMYtW7m%25252FjRofoG2g%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68251-merge-cd3db945a7a64425be/System.Runtime.InteropServices.Tests/cb6d692c-53c6-411e-9581-692e0a83d326.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-10T13%25253A31%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuMIdQASNUTmY2XyV4LrfhRJblHlFMYtW7m%25252FjRofoG2g%25253D)|
|[1727199](https://dev.azure.com/dnceng/public/_build/results?buildId=1727199)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68236](https://github.com/dotnet/runtime/pull/68236)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68236-merge-4c1579ad263d466f97/System.Runtime.InteropServices.Tests/1/console.591daa57.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-10T00%25253A06%25253A19Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLjaIxnNfvckO8ee%25252Bxcx3stHCt2gZFD3yao32kgLmMGs%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68236-merge-4c1579ad263d466f97/System.Runtime.InteropServices.Tests/8d1bd41e-a1b2-4e10-9c54-bf36d6fca82e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-10T00%25253A06%25253A19Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLjaIxnNfvckO8ee%25252Bxcx3stHCt2gZFD3yao32kgLmMGs%25253D)|
|[1726405](https://dev.azure.com/dnceng/public/_build/results?buildId=1726405)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68219](https://github.com/dotnet/runtime/pull/68219)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68219-merge-a66cf5b71153475394/System.Runtime.InteropServices.Tests/1/console.168eed42.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T17%25253A53%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DC0kVnAZRhDhWEZJphRB%25252BWWuN9H2ED1ApGM%25252BoLUSZOaI%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68219-merge-a66cf5b71153475394/System.Runtime.InteropServices.Tests/617895df-5124-4d2a-8cd4-893e1b124549.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T17%25253A53%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DC0kVnAZRhDhWEZJphRB%25252BWWuN9H2ED1ApGM%25252BoLUSZOaI%25253D)|
|[1726335](https://dev.azure.com/dnceng/public/_build/results?buildId=1726335)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68221](https://github.com/dotnet/runtime/pull/68221)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68221-merge-48ceabd8c4384a38a5/System.Runtime.InteropServices.Tests/1/console.ce752455.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T17%25253A25%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DA9r%25252F3GANDa86z9kkieNDp%25252Fc0CezUpdLkQuqKQJ4W3cQ%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68221-merge-48ceabd8c4384a38a5/System.Runtime.InteropServices.Tests/2f678df0-b3a4-4958-950c-eabaa8f13324.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T17%25253A25%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DA9r%25252F3GANDa86z9kkieNDp%25252Fc0CezUpdLkQuqKQJ4W3cQ%25253D)|
|[1724082](https://dev.azure.com/dnceng/public/_build/results?buildId=1724082)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68077](https://github.com/dotnet/runtime/pull/68077)|net7.0-windows-Debug-x64-CoreCLR_release-Windows.81.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68077-merge-fab1ccea98154874be/System.Runtime.InteropServices.Tests/1/console.4b5b6754.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-08T17%25253A23%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DWEp5Npi%25252FXTFN9zkxDaA6bnw4vDOxAH6GUmXk1I49eRk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68077-merge-fab1ccea98154874be/System.Runtime.InteropServices.Tests/5ff6f368-9ab8-4f9b-b53a-7eaa158e3316.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-08T17%25253A23%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DWEp5Npi%25252FXTFN9zkxDaA6bnw4vDOxAH6GUmXk1I49eRk%25253D)|
|[1723556](https://dev.azure.com/dnceng/public/_build/results?buildId=1723556)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 67903](https://github.com/dotnet/runtime/pull/67903)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67903-merge-b496f49d6d384700ad/System.Runtime.InteropServices.Tests/1/console.13720cee.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T08%25253A56%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8wJzzJk3MNVNfl7d6a8uMXB%25252FfSOJMgTnYJPsYkbgGrk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67903-merge-b496f49d6d384700ad/System.Runtime.InteropServices.Tests/62430766-fa88-4187-8b05-95bfd46a29d6.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-09T08%25253A56%25253A42Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8wJzzJk3MNVNfl7d6a8uMXB%25252FfSOJMgTnYJPsYkbgGrk%25253D)|
|[1723058](https://dev.azure.com/dnceng/public/_build/results?buildId=1723058)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68141](https://github.com/dotnet/runtime/pull/68141)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68141-merge-cd1c9923d3de49b18b/System.Runtime.InteropServices.Tests/1/console.c2bd322d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T21%25253A33%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DyXwTc1mFXRnSE6sGHU2SXhDqBDOIaAgkVhgBNvdj%25252BOo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68141-merge-cd1c9923d3de49b18b/System.Runtime.InteropServices.Tests/0f3790aa-1118-4ae2-969e-4551a2b7b1a9.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T21%25253A33%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DyXwTc1mFXRnSE6sGHU2SXhDqBDOIaAgkVhgBNvdj%25252BOo%25253D)|
|[1722815](https://dev.azure.com/dnceng/public/_build/results?buildId=1722815)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 68130](https://github.com/dotnet/runtime/pull/68130)|net7.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68130-merge-7afdfd6ad387409c87/System.Runtime.InteropServices.Tests/1/console.7b02174e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T15%25253A31%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D9m5xQSLXrL%25252Fh7GpoWbVjBmhDnhx61IasoCHTZ67UDfc%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68130-merge-7afdfd6ad387409c87/System.Runtime.InteropServices.Tests/3c689156-c47e-4ffc-8377-7bdeebcbc305.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T15%25253A31%25253A46Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D9m5xQSLXrL%25252Fh7GpoWbVjBmhDnhx61IasoCHTZ67UDfc%25253D)|
|[1722478](https://dev.azure.com/dnceng/public/_build/results?buildId=1722478)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-windows-Release-x64-CoreCLR_checked-Windows.10.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-039401949f2248f7a0/System.Runtime.InteropServices.Tests/1/console.72fae14b.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T09%25253A07%25253A58Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DHFbz36XLCGXjwhibQUZ8q52vx6tGZm2kNWlwGuJRbjg%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-039401949f2248f7a0/System.Runtime.InteropServices.Tests/a0aa4057-3fba-4e0c-a57d-4bf60d302b61.log?%3F%253Fsv%253D2019-07-07%2526se%253D2022-05-07T09%25253A07%25253A58Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DHFbz36XLCGXjwhibQUZ8q52vx6tGZm2kNWlwGuJRbjg%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|2|9|9|

**Comment by jkoritzinsky** [comment]
This might not be only JitStress (I'm seeing intermittent repros in some PR failures in the runtime pipeline), but JitStress might be the best way to repro it

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220322.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1675437&view=ms.vss-test-web.build-test-results-tab&runId=45953110&resultId=131279&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

```
**Error message:**
```
High limit handle did not trigger a GC
Expected: True
Actual:   False


Stack trace
   at System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector() in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/HandleCollectorTests.cs:line 144
```

**Comment by adamsitnik** [comment]
Hit again in https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d38cf73ba255498fa4/System.Runtime.InteropServices.Tests/1/console.1e36f4c8.log?sv=2019-07-07&se=2022-04-14T09%3A06%3A23Z&sr=c&sp=rl&sig=uDZFbVyRZK5cDOI9bm1CaZmEqIOWIiXmDLL1ex3Ac9M%3D

**Comment by lewing** [comment]
hit again in #67289

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220405.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1699992&view=ms.vss-test-web.build-test-results-tab&runId=46336360&resultId=150566&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

```
**Error message:**
```
High limit handle did not trigger a GC
Expected: True
Actual:   False


Stack trace
```

**Comment by kouvel** [comment]
Hit again in https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67160-merge-fce57385286b4acdbd/System.Runtime.InteropServices.Tests/1/console.51df3830.log?sv=2019-07-07&se=2022-04-27T01%3A23%3A31Z&sr=c&sp=rl&sig=HGoNjqy5wdwOJiN%2B4k9dooAvVHHVn7myC2nYC5cshT4%3D

**Comment by VincentBu** [comment]
Failed again in:[ runtime-coreclr libraries-jitstress 20220413.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1714759&view=ms.vss-test-web.build-test-results-tab&runId=46600340&paneView=debug&resultId=155760)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-zapdisable-Windows.10.Arm64v8.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

```
**Error message:**
```
High limit handle did not trigger a GC
Expected: True
Actual:   False


Stack trace
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr)
```

**Comment by ViktorHofer** [comment]
Happened again in https://dev.azure.com/dnceng/public/_build/results?buildId=1726335&view=ms.vss-test-web.build-test-results-tab&runId=46812918&resultId=146155&paneView=debug. I converted this issue to a live tracking one.

@AaronRobinsonMSFT @jkoritzinsky @jeffschwMSFT can you please take a look?

**Comment by AaronRobinsonMSFT** [comment]
@ViktorHofer Someone will look into this today.

**Comment by elinor-fung** [comment]
@AaronRobinsonMSFT it looks like this is still happening

```
System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector [FAIL]
      High limit handle did not trigger a GC: 21 < 21
      Expected: True
      Actual:   False
      Stack Trace:
```
[Console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-68447-merge-47c4997ae59e414aa4/System.Runtime.InteropServices.Tests/1/console.9449d9dc.log?%3Fsv%3D2019-07-07%26se%3D2022-05-13T21%253A38%253A17Z%26sr%3Dc%26sp%3Drl%26sig%3DPqKvLNeM2q2V6VP7XcbwbXq8qWtxb%252B26jZtXp0Nzr38%253D)

13 hits in the past five days after #68285 went in: https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E5+definition%3Aruntime+name%3ATestHandleCollector

**Comment by jkotas** [comment]
This test can be running together with all other System.Runtime.InteropServices tests. Those other tests can be allocating and triggering GCs (ie altering the global state that this test asserts are based on). Is the logic of the test robust against that?

**Comment by AaronRobinsonMSFT** [comment]
Yes, I believe so. All we are attempting to validate is that the sum of `GC.CollectionCount(0) + GC.CollectionCount(1) + GC.CollectionCount(2)` after the above loop is greater than the same computed sum before the loop. The test is arguably not that useful in a situation where multiple tests are running so it is odd that it fails at all since we simply need 1 additional object to be collected for the test to pass.

Let me confirm again the logic in `HandleCollector.Add()` and confirm that `GC.Collect()` will be called more than once.

**Comment by VincentBu** [comment]
Failed again in: [runtime-coreclr libraries-jitstress 20220427.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1740183&view=ms.vss-test-web.build-test-results-tab&runId=47056616&paneView=debug&resultId=153306)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitminopts-Windows.10.Arm64v8.Open

- System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector

```
**Error message:**
```
High limit handle did not trigger a GC: 41 < 41
Expected: True
Actual:   False


Stack trace
   at System.Runtime.InteropServices.HandleCollectorTests.TestHandleCollector() in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/HandleCollectorTests.cs:line 153
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 383
```

**Comment by AaronRobinsonMSFT** [comment]
I finally see what is going on here. This is a classic lack of memory pressure and the GC is making the right call and saying: "leave me alone". I am working on a fix to provide the needed pressure.
