### ISSUE TITLE
microsoft.xmlserializer.generator.6.0.0.nupkg fails to upload to nuget.server

### ISSUE THREAD

**Issue by TiltonJH** [dotnet/runtime#66584]
Hi,

we internally use a [NuGet.Server 3.4.1](https://github.com/NuGet/NuGet.Server) for our own as well as all third party nugets.

We can not push or otherwise publish `microsoft.xmlserializer.generator.6.0.0.nupkg` downloaded from [nuget.org](https://www.nuget.org/packages/Microsoft.XmlSerializer.Generator/) to our NuGet.Server.

On pushing we get a `System.Net.Http.HttpRequestException: Response status code does not indicate success: 406 (Not Acceptable).` error message.

If I put in the directory of the NuGet.Server I get `Part URI cannot start with two forward slashes.`.

So I took a look inside to figure out from where this might come from and found the `[Content_Types].xml` contains this line `<Override PartName="//prefercliruntime" ContentType="application/octet" />`. Removing one of the `/` at the beginning of `PartName` fixed my publish problem.

However now the package signature doesn't match anymore.

So my first question is: Who is to blame? Is NuGet.Server faulty or not tolerant enough? Or is nuget.org not strict enough?
Which leads to the second question: Is the package actually faulty? I mean, clearly something is odd here.

BTW: The 5.0.0 package does not have that issue. It only uses one `/`.

**Comment by carlossanlop** [comment]
@ericstj @joperezr do you know if this is a problem on our side?

**Comment by ericstj** [comment]
Looks to me like it was likely a side-effect of https://github.com/dotnet/runtime/commit/503ae5145aaedbae3db8533707ae172870b736e0#diff-
593c43b06aac311cdd8a667f3c662a01d924b02d71043e26c76b71579bdca6b6R23 cc @ViktorHofer 

I think this is a NuGet bug,  https://github.com/NuGet/Home/issues/9097
That bug indicates that files without an extension placed in the root of the package will cause this behavior.  We started hitting that when we removed our custom packing project and used built in nuget pack task.

cc @nkolev92

**Comment by ericstj** [comment]
I was able to find a workaround.  Using an empty value for `PackagePath`.

**Comment by TiltonJH** [comment]
That looks great! Thank you for the fast fix! :)

Do you know or can you guess if/when an improved/fixed `nupkg` might be available on nuget.org?

**Comment by ericstj** [comment]
This workaround will ship with .NET 7.0 preview 4 which I expect to release sometime in May.

**Comment by TiltonJH** [comment]
Thx update and we might try that.

However, I am sad to see that the LTS version 6 is not getting a fix. 😞 So we will have to wait for the release of the LTS version 8. Because, the decision has been made to only use the LTS versions of .NET in production of our enterprise industry software projects.
