### ISSUE TITLE
WebSocket deadlock when the load is low and KeepAlives are not disabled

### ISSUE THREAD

**Issue by iconics-milan** [dotnet/runtime#66595]
### Description

When running WebSockets under light load, so that the keep-alives keep being sent between the endpoints, the WebSockets seem to deadlock sooner or later.

When pausing the application and looking at where it's stuck (using decompiled code from VS2022), it seems to be in WebSocketBase.cs, in the function 'private async Task SendAsyncCore', in a 'while (true)' loop. The 'm_KeepAliveTask' is in the state RanToCompletion, but it remains set (not null) indefinitely. which prevents the infinite loop from ever exiting.

### Reproduction Steps

Run this for a minute or so, it should stall in that time. If not, please try running again.

    using System;
    using System.Net;
    using System.Net.WebSockets;
    using System.Threading;
    using System.Threading.Tasks;

    namespace WebSocketCloseTest
    {
        public class Program
        {
            public static async Task Main()
            {
                var serverTask = Server("http://localhost:45000/test/ws/");
                await Client("ws://localhost:45000/test/ws/");
                await serverTask;
            }

            private static Task Server(String serverAddress)
            {
                var listener = new HttpListener();
                listener.Prefixes.Add(serverAddress);
                listener.Start();

                return ServerListen(listener);
            }

            private static async Task ServerListen(HttpListener listener)
            {
                HttpListenerContext ctx = await listener.GetContextAsync();
                HttpListenerWebSocketContext wsCtx = await ctx.AcceptWebSocketAsync("subProtocol", TimeSpan.FromMilliseconds(1));

                using (var webSocket = wsCtx.WebSocket)
                {
                    var buffer = new Byte[1000];
                    while (true)
                    { 
                        await webSocket.ReceiveAsync(new ArraySegment<Byte>(buffer), CancellationToken.None);
                    }
                }
            }

            private static async Task Client(String serverAddress)
            {
                using (ClientWebSocket webSocket = new ClientWebSocket())
                {
                    webSocket.Options.AddSubProtocol("subProtocol");
                    webSocket.Options.KeepAliveInterval = TimeSpan.FromMilliseconds(1);
                    await webSocket.ConnectAsync(new Uri(serverAddress), CancellationToken.None);
                
                    Console.WriteLine($"Client WS connected");

                    var counter = 0;
                    var buffer = new Byte[1000];
                    while (true)
                    {
                        await webSocket.SendAsync(new ArraySegment<Byte>(buffer), WebSocketMessageType.Binary, true, CancellationToken.None);
                        await Task.Delay(2);
                    
                        counter++;
                        if (counter % 10 == 0)
                            Console.WriteLine($"sent: {counter}");
                    }
                }
            }
        }
    }

### Expected behavior

Don't deadlock.

### Actual behavior

Does deadlock.

### Known Workarounds

Disable the KeepAlives.

### Configuration

.NET Framework 4.8.4470.0 on Windows 10 (x64).
Does not seem to be occurring on .NET Core.

**Comment by CarnaViire** [comment]
Hi @iconics-milan,
This repo is for issues specific to .NET Core and .NET 5+. For .NET Framework issues, please create a support ticket at https://developercommunity.visualstudio.com/search?space=61

However, be aware that the bar for doing any changes/fixes in .NET Framework is really high. We strongly recommend everyone to migrate to .NET 6 (the newest release of .NET).

**Comment by iconics-milan** [comment]
Thanks @CarnaViire, I was not aware of that.
For reference, I opened this item in the developercomunity: https://developercommunity.visualstudio.com/t/WebSocket-deadlock-when-the-load-is-low/1692225
