### ISSUE TITLE
How to calculate percentile using System.Diagnostics.Metrics.Histogram

### ISSUE THREAD

**Issue by sourabh1007** [dotnet/runtime#66592]
I am trying to create pxx metrics using .Net Meter API. Below is the sample code

```
  System.Diagnostics.Metrics.MeterListener listener = new System.Diagnostics.Metrics.MeterListener
            {
                InstrumentPublished = (instrument, meterListener) =>
                {
                    if (instrument.Meter.Name == "ct")
                    {
                        Console.WriteLine($"{instrument.Name} : {instrument.Meter.Name}");
                        meterListener.EnableMeasurementEvents(instrument, null);
                    }
                }
            };
            listener.SetMeasurementEventCallback<long>(
                (instrument, measurement, tags, state) => {
                    KeyValuePair<string, object>[] tagsKv = tags.ToArray();
                    Console.WriteLine($"state => {state}");
                    foreach (KeyValuePair<string, object> tagKv in tagsKv)
                    {
                        Console.WriteLine($"tag => {tagKv.Key} :: {tagKv.Value}");
                    }
                    instrument.
                    Console.WriteLine($"Instrument: {instrument.Name} has recorded the measurement {measurement}");
            });

            listener.Start();

            System.Diagnostics.Metrics.Meter meter1 = new System.Diagnostics.Metrics.Meter("ct", "v1.0");
            System.Diagnostics.Metrics.Histogram<long> hist = meter1.CreateHistogram<long>(
                name: "Latency", 
                unit: "Ms");
            hist.Record(10);
            hist.Record(20);
            hist.Record(30);
```
I am able to see recorded values i.e. 10, 20, 30 in measurementEventCallback. But I want to calculate pxx (p99, p90 etc) from these values. How can I achieve that. I couldn't find any examples online.

**Comment by eiriktsarpalis** [comment]
cc @tommcdon @noahfalk

**Comment by noahfalk** [comment]
There is no .NET API that will do the computation for you, however there are some things you can use...
- [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet) is a complete library for exporting telemetry, including metrics and it would do a percentage computation as part of its work.
- [HDRHistogram](https://github.com/HdrHistogram/HdrHistogram.NET) is an OSS library that does such computations.
- Example code used by the dotnet-counters tool: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/ExponentialHistogramAggregator.cs


There isn't necessarily one right or canonical way to do this computation. If you look around on the web you will likely find a variety of implementations with different tradeoffs in terms of accuracy, performance, and what statistical information is preserved. .NET's API doesn't aim to do the statistics for you, it solely focuses on moving the data from publishers to the listeners. The listeners then have to decide what to compute or egress from the process. We expect most people will find a pre-implemented listener like OpenTelemetry more useful, but the API allows anyone to write their own listener if they want to. Hope that helps!

**Comment by sourabh1007** [comment]
Thanks for the answer @noahfalk ...Right now, we are using HDRHistogram in our project for such calculations (and it has its own overhead). After seeing similar class in Meter API, I was thinking to use it  (with the expectation of perf improvements and removing external dependency).

**Comment by noahfalk** [comment]
Sorry it didn't turn out to be what you were looking for. In terms of dropping the external dependency, the core of the HDR algorithm isn't too complex and should be implementable in not much code if you want to maintain an implementation in your own source rather than have the external reference. A lot of the HDR code looked like convenience methods, factories, and other auxilliary abstractions/utilities that you may or may not need. As for improving perf was there any particular perf metric you were trying to optimize for? I've not run its benchmarks myself but I'd be glad to learn how it is doing for you.

**Comment by sourabh1007** [comment]
Along with perf, I was looking for OTel API support also....Till now, perf impact is 3% - 5% using HDR histogram. I decided not to touch/modify the existing code.
I have one more question when we call `CreateHistogram`, I am assuming it stores all the recorded value in buckets (histogram way) then, what is the precision factor? or any best practice you want to suggest around this.

**Comment by noahfalk** [comment]
There are two different layers of the code:
- The Meter/Histogram/MeterListener portion only does forwarding, no bucketing or stats at that level. This is the layer that is common across all the scenarios.
- The next layer depends on which particular tool created the MeterListener. dotnet-counters does one thing, OTel does another, when you create a custom listener that sends it to HDRHistogram that is a 3rd option. So the precision/bucketing behavior depends on which one you are using. My understanding is:

dotnet-counters - If it reports the Nth percentile is X, then the true cutoff for that percentile is in the range [0.999X, 1.001X]
open-telemetry - has fixed buckets by default, but can be configured: https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/metrics/customizing-the-sdk/README.md#specify-custom-boundaries-for-histogram
HDR histogram - has configurable bucket sizes/error boundaries

Hope that helps!

**Comment by noahfalk** [comment]
I think we answered all the questions so going to close this. If you have follow up questions feel free to open a new issue to discuss. Thanks!
