### ISSUE TITLE
[WebToolsE2E] Running console app 7.0 with the code "Console.ReadKey();" in Program.cs, an extra "13" appears in the command prompt. 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#66596]
REGRESSION INFO: Doesn't repro in .NET 6.0
REPRO CONFIGURATION: Win10 x64 ENU 20H1 + Dev17.2 Preview 1 VSP + .NET 7.0 + Private feed

.NET Core SDK (CLI) Version: 7.0.100-preview.1.22101.1
Latest .NET Core runtime Version: 7.0.0-preview.1.22076.8

TESTCASES AFFECTED
[[7.0] SimpleConsoleAppOnCoreWithClassLib](https://github.com/aspnet/Tooling-ManualTests/blob/rel/17.0/E2EWalkthroughs/VS/AspNetCore30/30_SimpleConsoleAppOnCoreWithClassLib.md)

INSTALL STEP
1. Clean machine: Win10 x64 ENU 20H1
2. Install Dev17.2 Preview 1 [[d17.2-32209.124](https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build/results?buildId=5731965&view=results)] VSP
Select Web workload + .NET Desktop workload
Under 'Optional', check all the checkboxes
Check .NET Core 5.0/3.1/2.1 runtime under IC tab
3. Install .NET 7.0 from: [Pipelines - Run 20220201.1-7.0.100-preview.1.22101.1-125159 artifacts (azure.com)](https://dev.azure.com/dnceng/internal/_build/results?buildId=1584931&view=artifacts&pathAsName=false&type=publishedArtifacts)
4. Apply Feed: [https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-preview.1.22101.1-shipping/nuget/v3/index.json](https://pkgs.dev.azure.com/dnceng/public/_packaging/7.0.100-preview.1.22101.1-shipping/nuget/v3/index.json)

REPRO STEPS
1. File > New project > C# > Console App > .NET 7.0 (Preview) > Create
2. Open Program.cs, add Console.ReadKey(); in row 3.
3. F5

ACTUAL

![image](https://user-images.githubusercontent.com/10833894/158223613-cf952a52-1e1a-4777-8ab5-897aa93f4a01.png)

EXPECTED

![image](https://user-images.githubusercontent.com/10833894/158223649-243b8ae8-e209-4ce2-8326-7813c9f5b615.png)

**Comment by adamsitnik** [comment]
I am unable to repro:

![image](https://user-images.githubusercontent.com/6011991/158241664-780223b3-125f-44db-8888-44c957dd6ac7.png)

**Comment by jkotas** [comment]
It does repro for me (using dotnet/runtime build from 3/10). Here is the callstack where the write is coming from:
```
System_Console!Interop+Kernel32.WriteFile(IntPtr, Byte*, Int32, Int32 ByRef, IntPtr)+0xce [C:\runtime\src\libraries\System.Console\src\Microsoft.Interop.LibraryImportGenerator\Microsoft.Interop.LibraryImportGenerator\LibraryImports.g.cs @ 816] 
System_Console!System.ConsolePal+WindowsConsoleStream.WriteFileNative(IntPtr, System.ReadOnlySpan`1<Byte>, Boolean)+0x81 [C:\runtime\src\libraries\System.Console\src\System\ConsolePal.Windows.cs @ 1189] 
System_Console!System.ConsolePal+WindowsConsoleStream.Write(System.ReadOnlySpan`1<Byte>)+0x57 [C:\runtime\src\libraries\System.Console\src\System\ConsolePal.Windows.cs @ 1125] 
System_Private_CoreLib!System.IO.StreamWriter.Flush(Boolean, Boolean)+0x1d2
System_Private_CoreLib!System.IO.StreamWriter.Write(System.String)+0x188
System_Private_CoreLib!System.IO.TextWriter.Write(Int32)+0x36
System_Private_CoreLib!System.IO.TextWriter+SyncTextWriter.Write(Int32)+0x43
System_Console!System.Console.Write(Int32)+0x31 [C:\runtime\src\libraries\System.Console\src\System\Console.cs @ 910] 
System_Console!System.ConsolePal.ReadKey(Boolean)+0x309 [C:\runtime\src\libraries\System.Console\src\System\ConsolePal.Windows.cs @ 399] 
System_Console!System.Console.ReadKey()+0x19 [C:\runtime\src\libraries\System.Console\src\System\Console.cs @ 174] 
```
The problem was introduced by changing the type of `KeyEventRecord.uChar` from `char` to `ushort`. We are calling wrong `Write` overload now.

**Comment by v-elenafeng** [comment]
I can still repro this issue in .NET 7.0 Preview 2. I will retry when the PR is complete.
