### ISSUE TITLE
[DllImport] on Windows fails to load library on case sensitive filesystem

### ISSUE THREAD

**Issue by wikancz** [dotnet/runtime#66608]
### Description

[DllImport] on Windows fails to load library on case sensitive filesystem
System:  Windows 10 (21H1)
.net version: 6.0
File system: NTFS with SetCaseSensitiveInfo enabled

### Reproduction Steps

1. have Windows with case sensitive filesystem: `fsutil.exe file SetCaseSensitiveInfo C:\folder\path enable`
2. have `somelibrary.dll` - note all letters are lower case
3. use `[DllImport("somelibrary")]` **without** specifying extension
4. run project

### Expected behavior

Project correctly loads `somelibrary.dll`.

### Actual behavior

Project fails with exception:
`DllNotFoundException: Unable to load DLL 'somelibrary' or one of its dependencies: The specified module could not be found. (0x8007007E)`

### Known Workarounds

Rename library to `somelibrary.DLL`.

**Comment by danmoseley** [comment]
What are you expecting here -- for interop to try every possible casing of 'dll' ? It seems there either needs to be a convention (which is apparently "DLL" inadvertently or not) or the code importing the library needs to include the extension.

**Comment by wikancz** [comment]
Including extension will be problematic when writing cross platform project.
And according to this: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/cross-platform it adds `.dll` and not `.DLL`.

**Comment by jkotas** [comment]
> And according to this: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/cross-platform it adds .dll

We depend on Windows OS to add the extension in this case. 
https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibrarya#parameters says that it adds .dll that does not match the actual behavior.

**Comment by jkotas** [comment]
We do append the lower-cased `.dll` suffix ourselves in some corner cases: https://github.com/dotnet/runtime/blob/d603356dfbf09616e55bd99ed840aa20468a9e57/src/coreclr/vm/nativelibrary.cpp#L597 . A library with `.` in name will cause the runtime to append the lower-cased `.dll` instead of depending on the OS to do so. It means that we are inconsistent with the OS here. 

I think we should either fix our handling of the corner-cases to be consistent with the OS, or we can take over and always append the lower-cased suffix as needed instead of depending on the OS. (I agree that the OS docs should be updated too.)

**Comment by AaronRobinsonMSFT** [comment]
> We do append the lower-cased .dll suffix ourselves in some corner cases:

Boo. I thought we got rid of that logic and were always depending on the OS. Blech.

Reopening and will update based on what I hear from Windows.

**Comment by AaronRobinsonMSFT** [comment]
> If I were to pick, I would go with always appending the lower-cased suffix as needed instead of depending on the OS.

Okay.

> I expect that this issue is just a tip of the iceberg and number of other issues will show up if you try to run Windows .NET apps on case-sensitive file system.

I have the same feeling.

**Comment by danmoseley** [comment]
@wikancz just curious, how do you come to mount a case sensitive filesystem on Windows? What is the scenario here?

**Comment by wikancz** [comment]
@danmoseley Some of our coworkers tried to work with our repository on Linux machines but ran into problems with incorrect file references caused by casing.
I tried to solve it but instead of setting up my own Linux machine I just turned on case sensitivity.
