### ISSUE TITLE
Add class X509SubjectAlternativeNameExtension.cs : X509Extension

### ISSUE THREAD

**Issue by Ravnson** [dotnet/runtime#66613]
Currently, the X509 Library features several explizit inheritances of the base extension, but non for subject alternative names (san).

Would it be worth and/or reasonable to implement such an extension?

In RFC 5280 paragraph 4.2.1.6, the set of possible san's is explicitely stated and enumerated, which I think, in return, means that a proper implementation of this standard would give some benefits while using this library. Or am I wrong?

**Comment by vcsjones** [comment]
> Would it be worth and/or reasonable to implement such an extension?

What are you attempting to do with the Subject Alternative Name?

For creating an `X509Extension` that represents a SAN, there is [`SubjectAlternativeNameBuilder`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.subjectalternativenamebuilder?view=net-6.0).

If you are attempting to _read_ a SAN, can you describe your use case a bit? 

There are a few existing proposals around being able to read a SAN, including https://github.com/dotnet/runtime/issues/28771 or https://github.com/dotnet/runtime/issues/59870.

**Comment by Ravnson** [comment]
Thank you for your answer, I searched for related topics but for some unfortunate reasons, the related ones did not show up.

I think #22699 does in fact include my problem so I shall contribute there.
