### ISSUE TITLE
[wasm] benchmark sample crash

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#66614]
The browser-bench sample with compiled with AOT on imac/x64 is crasing on windows chrome with:

```
​ Error: [MONO] * Assertion at /Users/rodo/git/wa-perf/src/mono/mono/utils/lock-free-alloc.c:145, condition `sb_header' not met, function:alloc_sb, Failed to allocate memory for the lock free allocator

    at mono_wasm_stringify_as_error_with_stack (dotnet.js:3:15930)
    at Object.mono_wasm_trace_logger (dotnet.js:3:16301)
    at _mono_wasm_trace_logger (dotnet.js:13:110565)
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
    at :61293/dotnet.wasm
```
Mar 14th build, 63fd977f7d57e0c0e434caecfff0dd0a07d2f27f

**Comment by radekdoulik** [comment]
it looks like chrome specific issue. it runs fine in firefox

**Comment by radical** [comment]
I'm not able to reproduce this with a clean build of `main`. How do you build, and run the sample?

**Comment by radekdoulik** [comment]
I usually build and run it with `..\..\..\..\..\dotnet.cmd build /t:RunSample -p:RunAOTCompilation=true .\Wasm.Browser.Bench.Sample.csproj`

**Comment by radekdoulik** [comment]
Don't see that anymore, so looks like it was fixed meanwhile.
