### ISSUE TITLE
Json Deserialization of "dynamic" does not work

### ISSUE THREAD

**Issue by MhAllan** [dotnet/runtime#66638]
### Description

With Newtonsoft:

```csharp
var obj = JsonConvert.DeserializeObject<dynamic>("{ x: "something" }");
```
You will get correct dynamic object with `obj.x` being `something`.

but using Text.Json serializer you get `obj.x` to be `null or empty array []`

### Reproduction Steps

deserialize string to dynamic

### Expected behavior

to get dynamic object with dynamic properties have correct values

### Actual behavior

we get dynamic object but with empty properties or properties assigned to empty arrays

### Known Workarounds

use Newtonsoft

**Comment by huoyaoyuan** [comment]
There's no `dynamic` support currently in System.Text.Json. See #66517 #53195.
For dynamic behavior, you can serialize it as `JsonElement` or `JsonNode`, and use indexer to access its properties. No support for C# `dynamic` syntax now.

**Comment by eiriktsarpalis** [comment]
Closing as by-design behavior.

**Comment by MhAllan** [comment]
@huoyaoyuan, @eiriktsarpalis so basically things like CosmosDB and the way we design unstructured data in it will stay with Newtonsoft forever?

**Comment by huoyaoyuan** [comment]
You can use indexer syntax (`node["a"]`), though very verbose.
I'm not the designer, but I will vote for supporting `dynamic`.

**Comment by MhAllan** [comment]
@huoyaoyuan yeah I don't see a reason why not if Newtonsoft got it right. There are lot of serialization requires dynamic objects especially when you deal with nosql and different types of message queues. no dynamic serialization means all these technical and business pieces can't use Text.Json
