### ISSUE TITLE
[wasm][aot] `Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests` fail while linking due to OOM

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#66647]
Run: [run-extra-platforms Linux Release LibraryTests_AOT 20220312.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1657183&view=logs&j=7f41eb05-1c5f-5922-38da-d308f495fb31&t=142a4cb7-24ad-543f-6942-1fea62d34e98)

Error:
```
emcc : error : '/datadisks/disk1/work/B43F097B/p/build/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O2 --low-memory-unused --zero-filled-memory --strip-producers /datadisks/disk1/work/B43F097B/w/A1780928/e/wasm_build/obj/wasm/for-build/dotnet.wasm -o /datadisks/disk1/work/B43F097B/w/A1780928/e/wasm_build/obj/wasm/for-build/dotnet.wasm -g --mvp-features --enable-mutable-globals' failed (received SIGKILL (-9)) [/datadisks/disk1/work/B43F097B/w/A1780928/e/publish/ProxyProjectForAOTOnHelix.proj]
/datadisks/disk1/work/B43F097B/p/build/wasm/WasmApp.Native.targets(410,5): error MSB3073: The command "emcc "@/datadisks/disk1/work/B43F097B/p/build/microsoft.netcore.app.runtime.browser-wasm/runtimes/browser-wasm/native/src/emcc-default.rsp" "@/datadisks/disk1/work/B43F097B/p/build/microsoft.netcore.app.runtime.browser-wasm/runtimes/browser-wasm/native/src/emcc-link.rsp" "@/datadisks/disk1/work/B43F097B/w/A1780928/e/wasm_build/obj/wasm/for-build/emcc-link.rsp"" exited with code 1. [/datadisks/disk1/work/B43F097B/w/A1780928/e/publish/ProxyProjectForAOTOnHelix.proj]
```

Full [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5c24d9c7df9d4d30b3/normal-Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests/1/console.fc780b6c.log?sv=2019-07-07&se=2022-03-30T21%3A54%3A41Z&sr=c&sp=rl&sig=zwASfdzVKHDhyq6jP%2BeQtflGCxr1VgzUaktAh5kKQWo%3D).

Last passing run: [20220310.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1655893).

**Comment by ilonatommy** [comment]
@[ViktorHofer](https://github.com/ViktorHofer), could you check if https://github.com/dotnet/runtime/commit/0046648f91cd1b393c5d852789fbb16477ba4256 update could not cause it?
Another update at this time was done in https://github.com/dotnet/runtime/commit/f63e4d93fb4d1158e8f099cbbdd24b3555d2c583, so if @radical you could take a look as well?

**Comment by ShreyasJejurkar** [comment]
Tagging correctly, @ViktorHofer :)

**Comment by ViktorHofer** [comment]
> @ViktorHofer, could you check if https://github.com/dotnet/runtime/commit/0046648f91cd1b393c5d852789fbb16477ba4256 update could not cause it?

https://github.com/dotnet/runtime/commit/0046648f91cd1b393c5d852789fbb16477ba4256 is most definitely unrelated as msquic is networking related and was the only component touched in the change that you linked to.

**Comment by radekdoulik** [comment]
Looks like wasm-opt is getting out of memory.
```
wasm-opt [ 7359.203268] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/helix.service,task=wasm-opt,pid=28704,uid=1000 [ 7359.203288] Out of memory: Killed process 28704 (wasm-opt) total-vm:6024128kB, anon-rss:5859504kB, file-rss:4kB, shmem-rss:0kB, UID:1000 pgtables:11612kB oom_score_adj:0 [ 7359.406901] oom_reaper: reaped process 28704 (wasm-opt), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB```
