### ISSUE TITLE
dotnet/optimization builds are broken

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#66646]
https://dnceng.visualstudio.com/internal/_build?definitionId=237

FYI, to make progress on https://github.com/dotnet/runtime/pull/66447, I manually pushed the latest optimization packages to the dotnet7-transport feed.

@dotnet/runtime-infrastructure

**Comment by EgorBo** [comment]
@ViktorHofer I see two issues there:
1)
```
C:\Users\cloudtest\AppData\Local\Temp\2jjcy2xi.nzd\restore.csproj : error NU1102: Unable to find package dotnet-pgo with version (= 7.0.0-preview.3.22163.2)
C:\Users\cloudtest\AppData\Local\Temp\2jjcy2xi.nzd\restore.csproj : error NU1102:   - Found 1260 version(s) in dotnet6-transport [ Nearest version: 6.0.4-servicing.22161.8 ]

Package "dotnet-pgo" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
```
2)
```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
```

Is the 1st one somehow related to your change?
2) seems to be flaky infra issue - maybe we can temporarily remove orchard until we figure out it?

cc @AndyAyersMS @jakobbotsch @davidwrighton

**Comment by ViktorHofer** [comment]
> Is the 1st one somehow related to your change?

@EgorBo to which change? I didn't touch anything in dotnet/optimization :)

**Comment by jakobbotsch** [comment]
@EgorBo I think dotnet-optimization is missing dotnet7-transport in NuGet.config. I will open a PR for it.

**Comment by EgorBo** [comment]
Fixed via https://dnceng.visualstudio.com/internal/_git/dotnet-optimization/pullrequest/21820
