### ISSUE TITLE
Replace ad-hoc hash table being used for NODEBASH_STATS with a standard one

### ISSUE THREAD

**Issue by pkukol** [dotnet/runtime#6665]
The GenTree::RecordOperBashing() logic uses a custom / ad-hoc hash table; this should be replaced with one of the standard hash tables (it's a bit non-trivial due to memory allocation and re-entrancy issues).

category:implementation
theme:jit-coding-style
skill-level:intermediate
cost:small

**Comment by BruceForstall** [comment]
Doubt we're ever going to do this.
