### ISSUE TITLE
[API Proposal]: Attribute for mark functions returning rent arrays from some pool

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#66667]
### Background and motivation

In advance, sorry for my english.

Sometimes when I write some private methods in my libraries, if they use and return an array, usually I rent it from ```ArrayPool``` and I return it later (in some method upper in the stack). I don't know if this is fine or "good" (if not, please tell me alternatives and why), but while this is happening only in private and internal methods, I was thinking about some type of attribute for this kind of situations that make code analysis warn you.

This could offer an option to expose rent arrays to library users and know they will return the array.

### API Proposal

```C#
namespace System.Diagnosis.CodeAnalysis
{
    public class ReturnRentArrayAttribute: Attribute
    {
        public Type PoolType {get;} //e.g.: typeof(ArrayPool)

        public string PoolName {get;} //e.g.: nameof(Shared)
    }
}
```

### API Usage
Excuse me in advance, I can't remember if I can use generic types in attributes (I think not)

```C#
[ReturnRentArray(PoolType = typeof(ArrayPool<double>), PoolName = "Shared")]
public static double[] YValues(ReadOnlySpan<double> heights)
    {
        var result = ArrayPool<double>.Shared.Rent(heights.Length * 3 - 2);
        var heightsIndex = 0;

        for (var i = 0; i < heights.Length; i++)
        {
            //bla bla code.
        }
        return result;
    }

...bla bla work
var yValues = SomeCoolStaticClass.YValues(someHeightsData); //warn!! this array should be returned to the pool of type 'ArrayPool<double>': 'ArrayPool<double>.Shared'

...bla bla work
//Ah yes, the warn
ArrayPool<double>.Shared.Return(yValues);

```

### Alternative Designs

No alternatives.

### Risks

The main risk (or caveat) I can see is when the pool is not a singleton (like default ArrayPool behaves) but I cannot imagine a good solution for that situation.

**Comment by Clockwork-Muse** [comment]
> I don't know if this is fine or "good"

Ignoring minor private/internal helper methods, this is a resource leak, even inside of your library.
Either track the ownership (as @Sergio0694 is suggesting), or have the _caller_ pass in a buffer to be filled (or similar).

**Comment by teo-tsirpanis** [comment]
What if you have a rented array in a class field? You will rent it from the constructor, return it in `Dispose()`, and the analyzer would warn for no reason. I don't think an attribute like this is sufficient to prevent memory leaks in all but the simplest use cases.

Returning rented arrays from utility functions is not a good idea for reasons of lifetime management. And in your example, `ArrayPool<double>.Shared.Rent(heights.Length * 3 - 2)` is not guaranteed to return an array of the expected size.

---

If I were you I would refactor the function like this:

``` csharp
public static int GetYValuesResultLength(ReadOnlySpan<double> heights) => heights.Length * 3 - 2;

[ReturnRentArray(PoolType = typeof(ArrayPool<double>), PoolName = "Shared")]
public static void YValues(ReadOnlySpan<double> heights, Span<double> result)
{
    // You can validate the result's length again if you want.

    var heightsIndex = 0;

    for (var i = 0; i < heights.Length; i++)
    {
        //bla bla code.
        result[i] = foo;
    }
}
```

`YValues` does not allocate. Callers will pass a span of the doubles where the result would be written to. And there is a new method that calculates the length the result span should be, to help callers allocate the right amount of memory.

**Comment by huoyaoyuan** [comment]
For current `ArrayPool` implementation, forgetting to return the array isn't a fatal leak. It will get back to GC, as not pooled.

The current type ecosystem lacks concepts of ownership. The analyzers about `IDisposable` has been annoying. I don't think this can be made useful at this time point.

**Comment by rubenoost** [comment]
I recently had a similar issue where a cache rented out disposable objects that had to be returned to the cache as well. I solved this using a IDisposable wrapper around the returned object. eg:

```cs
public class RentedArray<T> : IDisposable
{
    private readonly ArrayPool<T> _pool;
    public T[] Array { get; }

    public RentedArray(T[] array, ArrayPool<T> pool)
    {
        Array = array;
        _pool = pool;
    }

    public void Dispose()
    {
        _pool.Return(Array);
    }
}
```

your method would look like this:
```cs
public static RentedArray<double> YValues(ReadOnlySpan<double> heights)
{
    var result = ArrayPool<double>.Shared.Rent(heights.Length * 3 - 2);
    var heightsIndex = 0;

    for (var i = 0; i < heights.Length; i++)
    {
        //bla bla code.
    }
    
    return new RentedArray<double>(result, ArrayPool<double>.Shared);
}
```

You could use it like this:
```cs
using var yValues = YValues(someHeightsData);

// Do whatever you want here
yValues.Array[0] = 5;

// yValues.Dispose() will return this to the arraypool
```

**Comment by Clockwork-Muse** [comment]
> This is the same pattern that `IMemoryOwner<T>` implements

Yes, and as a general-case scenario that's what you would be advised to use.

`ArrayPool` is primarily intended for either slightly larger short-lived use (too large for `stackalloc`), or internal-only uses where the lifetime is completely controlled.

**Comment by DrkWzrd** [comment]
For the moment I'm gonna improve my code making it the callers pass a `Span` like @teo-tsirpanis have advised.

**Comment by buyaa-n** [comment]
As many mentioned here, this doesn't seem to be helpful, closing
