### ISSUE TITLE
Sync stream serialization not handling IAsyncEnumerable correctly

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#66687]
While adding new tests to System.Text.Json I discovered an issue with the handling of IAsyncEnumerable values in the new [sync stream serialization APIs](https://github.com/dotnet/runtime/pull/54632). It would seem like [IAsyncEnumerableConverter's sync serialization detection logic](https://github.com/dotnet/runtime/blob/3eea15a6a6a8e1b411675951356fb6def4b73b62/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IAsyncEnumerableOfTConverter.cs#L37-L40) is not adequate in identifying the new methods: in debug builds this results in a [failed debug assertion](https://github.com/dotnet/runtime/blob/c3dbdea91835d67cc461b22125e652ad5063d746/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Stream.cs#L345) whereas release builds end up serializing IAE values successfully, since they [accidentally perform sync-over-async enumeration of the source enumerable](https://github.com/dotnet/runtime/blob/c3dbdea91835d67cc461b22125e652ad5063d746/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IAsyncEnumerableOfTConverter.cs#L100). We should try to fix this, I can see a couple of options here:

1. Have the converter detect and fail on sync stream serialization methods. Users that rely on the current behavior might regard this as a breaking change.
2. Double down on the existing (accidental) behavior and use sync-over-sync for the sync stream serialization methods. Should we consider allowing the same behavior for non-stream sync serialization methods?

cc @steveharter @stephentoub

**Comment by stephentoub** [comment]
> Have the converter detect and fail on sync stream serialization methods

Would this be deterministic, i.e. regardless of the async enumerable's contents, whether it's empty or not, whether its operations complete synchronously or not, you'd always get the exception because it'd be based on the shape rather than on the data?

**Comment by eiriktsarpalis** [comment]
> > Have the converter detect and fail on sync stream serialization methods
>
> Would this be deterministic, i.e. regardless of the async enumerable's contents, whether it's empty or not, whether its operations complete synchronously or not, you'd always get the exception because it'd be based on the shape rather than on the data?

Good question. For the non-streaming sync serialization methods the converter throws outright (i.e. it's based on the type shape). It's conceivable that we could make it more adaptable but I suspect this might be setting traps for users (e.g. my mocked IAsyncEnumerable responses were passing all unit tests but serialization is crashing when I deploy the app)
