### ISSUE TITLE
SslStream.KeyExchangeStrength is zero on non-Windows platforms

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#66705]
Noticed while looking into #37578. Does not seem to be a priority. Could be good for platform consistency.

To repro, use example from https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.hashalgorithm?view=net-5.0

```c#
static void DisplaySecurityLevel(SslStream stream)
{
   Console.WriteLine("Cipher: {0} strength {1}", stream.CipherAlgorithm, stream.CipherStrength);
   Console.WriteLine("Hash: {0} strength {1}", stream.HashAlgorithm, stream.HashStrength);
   Console.WriteLine("Key exchange: {0} strength {1}", stream.KeyExchangeAlgorithm, stream.KeyExchangeStrength);
   Console.WriteLine("Protocol: {0}", stream.SslProtocol);
}
```

possible outputs on Unix platforms:

For TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA:
> Cipher: Aes128 strength 128
> Hash: Sha1 strength 160
> Key exchange: DiffieHellman strength 0
> Protocol: Tls11
> 

For TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:

> Cipher: Aes128 strength 128
> Hash: None strength 0
> Key exchange: DiffieHellman strength 0
> Protocol: Tls12
>

**Comment by karelz** [comment]
Triage: It's a bug, but low impact on customers. Future

**Comment by rzikm** [comment]
properties will be obsoleted as per https://github.com/dotnet/runtime/issues/100361, not planned
