### ISSUE TITLE
NullabilityInfo returns incorrect state for non nullable reference type in nested generics

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#66708]
### Description

Was writing some unit tests for the MVVM Toolkit (https://github.com/CommunityToolkit/dotnet/pull/160), specifically to validate the nullability annotations produced by one of our source generators, and decided to use the `NullabilityInfo` APIs introduced in .NET 6 to validate the generated code. One of the tests is resulting in seemingly incorrect behavior though, where an `object` type argument is reported as being nullable despite it being not nullable.

### Reproduction Steps

```csharp
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;

NullabilityInfoContext context = new();

// Foo<Foo<string?, int>.Bar<object?>?, StrongBox<Foo<int, string?>.Bar<object>?>?>?
NullabilityInfo info = context.Create(typeof(NullableRepro).GetProperty(nameof(NullableRepro.NullableMess))!);

// StrongBox<Foo<int, string?>.Bar<object>?>?
NullabilityInfo rightInfo = info.GenericTypeArguments[1];

// Foo<int, string?>.Bar<object>?
NullabilityInfo rightInnerInfo = rightInfo.GenericTypeArguments[0];

// object
NullabilityInfo rightInfo2 = rightInnerInfo.GenericTypeArguments[2];

Debug.Assert(rightInfo2.Type == typeof(object));
Debug.Assert(rightInfo2.ReadState == NullabilityState.NotNull); // These two fail
Debug.Assert(rightInfo2.WriteState == NullabilityState.NotNull);

public partial class NullableRepro
{
    public Foo<Foo<string?, int>.Bar<object?>?, StrongBox<Foo<int, string?>.Bar<object>?>?>? NullableMess { get; }
}

public class Foo<T1, T2>
{
    public class Bar<T>
    {
    }
}
```

### Expected behavior

The state should be not nullable here, as that type argument is a non nullable reference type.

### Actual behavior

The nullable state is reported as being not null in both cases (read and write).

### Regression?

No, it's a new API.

### Known Workarounds

None really, short of just reimplementing the whole nullability logic yourself with reflection.

### Configuration

.NET 6.0.201, from VS 17.1.1

**Comment by B1Z0N** [comment]
I confirm that it's now fixed on latest commits. All asserts passing.

**Comment by buyaa-n** [comment]
Yes it is fixed, closing
