### ISSUE TITLE
dotnet fails to exit with thread stuck in coreclr!WatsonLastChance

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#66715]
I built dotnet/runtime main in release, then ran outerloop tests. It jammed with active CPU, so I tried to get a dump.

Running as admin (although it shouldn't matter - target process is not elevated)
```
C:\temp>dotnet-dump --version
6.0.257301+27172ce4d05e8a3b0ffdefd65f073d40a1b1fe54

C:\temp>dotnet-dump ps | \t\grep 53884
     53884 dotnet     D:\git\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\dotnet.exe

C:\temp>dotnet-dump collect --process-id 53884

Writing full to C:\temp\dump_20220312_094512.dmp
Cannot process request because the process (53884) has exited.

C:\temp>dotnet-dump ps | \t\grep 53884
     53884 dotnet     D:\git\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\dotnet.exe

C:\temp>\t\filever -v D:\git\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\dotnet.exe | \t\head -1
--a-- WAMD64 DLL ENU    7.0.22.15701 shp    126,464 03-07-2022 dotnet.exe
```

cc @mikem8361

**Comment by danmoseley** [comment]
@tommcdon https://microsoft-my.sharepoint.com/:u:/p/danmose/EdfrQ9SlIeRCp-JmGXJ1om4BQNQX83pxpFa-FCHM33lt8w?e=8Zgywx is the dump.

I can probably repro this if needed, since it's happened twice now. LMK.

**Comment by danmoseley** [comment]
Looking at procmon, it seems oledb32.dll is instantiating some office components, which is what pulls in the office dll's and creates that window with the title above.  That explains why it's the oledb tests every time. Of course, it shouldn't hang, whatever the reason.

No idea why nobody else is hitting this. Maybe I was pushed some Office experiment.

**Comment by noahfalk** [comment]
This looks like a known issue that was intentionally preserved for back-compat: https://github.com/dotnet/runtime/blob/39fb7f7826270f00b856e3e9a13165c07dec87cc/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/ProcessManager.Windows.cs#L265-L271

Presumably we have a few options to fix it:
- change the Process class to stop doing the exit code check
- provide some alternate flag/API/etc that conditionally avoids doing the exit code check
- change dotnet-dump not to use System.Diagnostics.Process to avoid this known issue in the code

**Comment by danmoseley** [comment]
Hmm, that might not be the reason that GetProcessHandle calls GetExitCodeProcess. It might well be though, and reasoning reliably about the Process class can be difficult. I see no reason to change it -- it looks like a simple change to dotnet-dump to just get the handle from ::OpenProcess directly. I opened https://github.com/dotnet/diagnostics/issues/2950 for that.

The bigger issue is why is the process is hung with the stack above in the first place.

**Comment by noahfalk** [comment]
Ah I misunderstood and thought you were trying to track down the dotnet-dump issue. I see now. I think the reason the process is hanging is from this claim here: https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/ee/debugger.cpp#L380

This thread appears to be neither the finalizer nor the debugger helper thread, but it does need to keep executing in order for the process to exit. Probably a reasonable fix will be for PreJitAttach to return immediately without doing any work if we detect that m_fShutdownMode is true.

**Comment by danmoseley** [comment]
Happy to buddy test a private dll if it helps.

**Comment by danmoseley** [comment]
@noahfalk do you think you will have cycles to put up the fix? This prevents libraries tests runs from completing on my machine, and one would assume on others, but I don't know.
Workaround is presumably to comment all the OLEDB tests out.

**Comment by noahfalk** [comment]
I'm writing it up now. Its possible this fixes it entirely or it may just be one layer of the onion. It should be safe to check in either way and then we can find out what impact it has for your local repro.

**Comment by danmoseley** [comment]
confirmed all sorted now thanks @noahfalk

**Comment by noahfalk** [comment]
awesome, glad it worked out : )
