### ISSUE TITLE
[wasm] Regression on windows/AOT - `mono-aot-cross.exe` crashes every time

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#66718]
https://github.com/dotnet/runtime/pull/66552 broke all AOT on windows completely. All the library tests, and Wasm.Build.Tests are failing for windows/aot (https://dev.azure.com/dnceng/public/_build/results?buildId=1666142&view=logs&j=55f4943c-f76d-585b-7250-deab324f0a54&t=9d909c2f-e8c7-58b9-4308-45796ed0b70f, https://dev.azure.com/dnceng/public/_build/results?buildId=1666244&view=results).

`mono-aot-cross` crashes with `Exit code: -1073741819`

```
C:\helix\work\correlation\build\wasm\WasmApp.Native.targets(567,5): error : Precompiling failed for C:\helix\work\workitem\e\publish\System.Private.Xml.dll. [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
C:\helix\work\correlation\build\wasm\WasmApp.Native.targets(567,5): error :  [C:\helix\work\workitem\e\publish\ProxyProjectForAOTOnHelix.proj]
```

The failures can be seen on the PR, but since our windows runs are still in `runtime-staging`, they might have been overlooked.

cc @AaronRobinsonMSFT @lambdageek @vargaz @radekdoulik

**Comment by lateralusX** [comment]
The issue is probably a change from int to size_t in a case where it stills needs to go negative.

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/pull/66721 fixes an issue discovered locally due to changes done in https://github.com/dotnet/runtime/pull/66552, is probably causing this issue.

**Comment by am11** [comment]
> The failures can be seen on the PR, but since our windows runs are still in runtime-staging, they might have been overlooked.

The failure cannot be seen on PR. The link you are sharing is from main branch. There was only one failing leg on the PR https://github.com/dotnet/runtime/pull/66552/checks?check_run_id=5561925796 which was due to a missing docker.

**Comment by radical** [comment]
> > The failures can be seen on the PR, but since our windows runs are still in runtime-staging, they might have been overlooked.
> 
> The failure cannot be seen on PR. The link you are sharing is from main branch. There was only one failing leg on the PR [#66552 (checks)](https://github.com/dotnet/runtime/pull/66552/checks?check_run_id=5561925796) which was due to a missing docker.

Oops, sorry about the wrong link. [This](https://dev.azure.com/dnceng/public/_build/results?buildId=1661899&view=logs&jobId=55f4943c-f76d-585b-7250-deab324f0a54&j=55f4943c-f76d-585b-7250-deab324f0a54&t=9d909c2f-e8c7-58b9-4308-45796ed0b70f) is the link from that PR. For PRs, *test* failures on `runtime-staging` don't fail the whole job, so they don't show up as failing in GitHub checks. So, they have to be checked manually.

Once we can stop provisioning emscripten at build time on windows, we can move the jobs from `runtime-staging` to `runtime`.

**Comment by radical** [comment]
Closing, fixed by https://github.com/dotnet/runtime/pull/66721 .
