### ISSUE TITLE
Package versioning vs framework versioning

### ISSUE THREAD

**Issue by starkpl** [dotnet/runtime#66722]
Usually, when there is a new version of .NET released (such as .NET 6), core libraries (System.\*, Microsoft.Extensions.\* and so on) also get new versions (such as 6.0.x). What I observe for most of them, is that they usually target the new .NET version, but also some older / more general targets such as netstandard2.0. 

Just one simple example: [https://www.nuget.org/packages/System.Text.Encodings.Web/6.0.0](https://www.nuget.org/packages/System.Text.Encodings.Web/6.0.0)

Are there any drawbacks of using the newer packages (6.0.x) with older framework versions (net5.0)? Or anything that I should be aware of when doing so? Because in most cases it is technically possible and I couldn’t find any discouragement of doing this in the documentation.

The context here is that I have several teams maintaining several microservices and some libraries that they share, and updating everything at once is not possible. I am planning a migration from .NET 5 to .NET 6 and there will probably be some transition period when some of them are already migrated and some are not. I'm considering if I should multitarget the shared libraries or maintain two branches etc, or maybe just gradually update all the core libraries to 6.0.x and when all the microservices are already migrated to net6.0, change the TargetFramework of the shared libraries also to net6.0. Are there any guidelines for such scenarios?

**Comment by bartonjs** [comment]
The libraries delivered via NuGet are expected to just work using normal NuGet patterns.  An application running on (e.g.) .NET Core 3.1 should be able to run System.Text.Encodings.Web 6.0.x just fine (that guarantee goes away when .NET Core 3.1 goes out of support, of course).

**Comment by huoyaoyuan** [comment]
These are called OOB(out-of-brand) packages. They are meant to be used by down level frameworks. On higher level frameworks, they will delegate to the in box version if there is one.

**Comment by starkpl** [comment]
@bartonjs @huoyaoyuan thanks for clarification.
