### ISSUE TITLE
[API Proposal]: Add ImmutableArray.Contains overload that accepts an IEqualityComparer<T>

### ISSUE THREAD

**Issue by ChrML** [dotnet/runtime#66758]
### Background and motivation

I recently had a significant inner-loop performance regression when I added an optional `IEqualityComparer<T>` to my API. I found out that the reason was that I added the optional `comparer` argument to the `Contains` invocation on a `ImmutableArray<T>`.

Apparently there is no such overload, so it the call was directed from:

```c#
public readonly struct ImmutableArray<T>
{
    // ...
    public bool Contains(T item)
    // ...
}
```

And fell back to the much slower Linq extension:
```c#
public static class Enumerable
{`
    // ...
    public static bool Contains<TSource>(this IEnumerable<TSource> source, TSource value, IEqualityComparer<TSource>? comparer);
    // ...
}
```

This caused a significant amount of boxing to `IEnumerable<T>` each time `Contains` was called. Most methods in the API at the moment contain overloads that accept an optional `IEqualityComparer<T>?`, so it was quite surprising that this API did not.

See: https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.contains?view=net-6.0

### API Proposal

```C#
namespace System.Linq;

public static partial class ImmutableArrayExtensions
{
    public static bool Contains<T>(this ImmutableArray<T> immutableArray, T item, IEqualityComparer<T>? comparer)
    {
        var self = immutableArray;
        return self.IndexOf(item, 0, self.Length, equalityComparer) >= 0;
    }
}
```

### API Usage

```C#
ImmutableArray<string> items = ImmutableArray.Create("abc", "DEF");
Assert.True(items.Contains("Abc", StringComparer.InvariantCultureIgnoreCase));
Assert.True(items.Contains("Def", StringComparer.InvariantCultureIgnoreCase));
```

### Risks

This has a really low risk of breaking something. It should increase the overall performance when `Contains` is used where the programmer was not aware of this issue.

**Comment by eiriktsarpalis** [comment]
Given that it is fairly common for concrete collections to fall back to slower LINQ methods, I'm not necessarily convinced that it's sufficient justification to add another overload in `ImmutableArray<T>`. There's codegen overhead to adding more methods to generic types, and as you're pointing out it's fairly trivial to express this overload as an extension method.

**Comment by ChrML** [comment]
> Given that it is fairly common for concrete collections to fall back to slower LINQ methods, I'm not necessarily convinced that it's sufficient justification to add another overload in `ImmutableArray<T>`. There's codegen overhead to adding more methods to generic types, and as you're pointing out it's fairly trivial to express this overload as an extension method.

Yes, the required functionality is already present in ImmutableArray<T>.IndexOf, so this can easily be expressed as an extension method.

However that argument would also apply to the single-argument Contains method already present.

**Comment by Joe4evr** [comment]
Is it not an option to add this overload to [the set of LINQ extensions specialized for `ImmutableArray<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.immutablearrayextensions)?

**Comment by ChrML** [comment]
> Is it not an option to add this overload to [the set of LINQ extensions specialized for `ImmutableArray<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.immutablearrayextensions)?

I think that's the best option.

**Comment by eiriktsarpalis** [comment]
SGTM, given there's precedent. @ChrML could you update your API proposal to use that namespace?

**Comment by Joe4evr** [comment]
If OP isn't going to update, then I'll place the revised proposal real quick:
```cs
namespace System.Linq
{
    public static partial class ImmutableArrayExtensions
    {
        public static bool Contains<T>(this ImmutableArray<T> immutableArray, T value, IEqualityComparer<T>? comparer);
    }
}
```

**Comment by ChrML** [comment]
I have updated the proposal to what we have discussed here. Sorry for that it took so long.

**Comment by Joe4evr** [comment]
Question for whenever this comes to review: I recall that some time ago the review team made a blanket policy that `System.Linq.Queryable` should be kept in sync with (most) methods in `System.Linq.Enumerable`. Does it make sense to extend that policy to keep `ImmutableArrayExtensions` in sync as well?

**Comment by bartonjs** [comment]
Looks good as proposed.  This seems generally applicable to any `struct` that is `IEnumerable` that provides a `Contains(T)` without a `Contains(T, IEqualityComparer<T>)`... but we couldn't find a second one during the meeting.

```C#
namespace System.Linq;

public static partial class ImmutableArrayExtensions
{
    public static bool Contains<T>(this ImmutableArray<T> immutableArray, T item, IEqualityComparer<T>? comparer)
    {
        var self = immutableArray;
        return self.IndexOf(item, 0, self.Length, equalityComparer) >= 0;
    }
}
```
