### ISSUE TITLE
dotnet-trace collect causes the target application to receive SIGBUS on armv7l

### ISSUE THREAD

**Issue by o-lek** [dotnet/runtime#66772]
### Description
The target process receives SIGBUS on armv7l when I try to collect trace info.
The problem occurs inside _GetBytes(WCHAR* chars, ...)_ and _GetByteCount(WCHAR* chars, ...)_ functions (runtime/src/coreclr/src/pal/src/locale/utf8.cpp)
Both functions receive their parameter _chars_ as an odd address value.
This happens because of _#CollectTracing2_ IPC Message, which contains _bool requestRundown_ field of 1 byte length. https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#collecttracing2 
The following fields are all have odd addresses. The field _provider_name_ when passed to _GetBytes_ and _GetByteCount_ causes SIGBUS. 
Exactly this code (GetBytes):
`     2417              ch = *(int*)pSrc;`
`     2418              int chc = *(int*)(pSrc + 2);`
and (GetByteCount):
`     2757              ch = *(int*)pSrc;`
`     2758              int chc = *(int*)(pSrc + 2);`
is compiled into 
`     ldrd r1,r2, [r3]`
ARM machine instruction which requires on some ARM architectures the address to be aligned by 4 bytes.
In my opinion, this "odd alignment" will slow down access to the data on the most of all CPU architectures and sometimes, as we can see, may even cause problems.

**Comment by jkotas** [comment]
https://github.com/mdh1418/runtime/commit/fe317a393fbb90d232c45099bd692356a7f4e1fa (part of https://github.com/dotnet/runtime/pull/64358)

cc @mdh1418 @lateralusX Thoughts on backporting this fix to .NET 6?

**Comment by lateralusX** [comment]
cc @josalem, potential backport we discussed yesterday.

**Comment by josalem** [comment]
+1 on backporting this change.

**Comment by hoyosjs** [comment]
Closing manually - somehow the merge didn't close.
