### ISSUE TITLE
ArrayPool returns an array of 2_097_152 elements when asked 1024 * 1024 + 1 (1_048_577)

### ISSUE THREAD

**Issue by WhatsMyMotherFuckerUsername** [dotnet/runtime#66779]
ArrayPool's maximum length array is defined in System.Buffers.ConfigurableArrayPool.cs :
private const int DefaultMaxArrayLength = 1024 * 1024;

If we rent an array for a length higher than 1024 * 1024 (i.e. 1_048_576), it is supposed to allocate a new array with the exact length required (and just drop it when you return this array).

Surprisingly, when you rent an array as following :
int[] myArray = ArrayPool<int>.Shared.Rent(1_048_577);
myArray is of length 2_097_152

**Comment by tannergooding** [comment]
ArrayPool is not guaranteed to give you an array of explicitly the length you requested. It returns an array that is at least the requested length as per the documentation: https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1.rent?view=net-6.0

**Comment by danmoseley** [comment]
Closing as question was answered.

**Comment by WhatsMyMotherFuckerUsername** [comment]
Yes, if you stay below the DefaultMaxArrayLength.
No, if you go higher.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Buffers/ConfigurableArrayPool.cs at line 108

**Comment by danmoseley** [comment]
You're not using that array pool in your example. You're using the shared one, which is a different implementatoin. https://github.com/dotnet/runtime/blob/7db092a6ed68a5fbf47962c45bb0c1bb965d02c6/src/libraries/System.Private.CoreLib/src/System/Buffers/ArrayPool.cs#L23

**Comment by WhatsMyMotherFuckerUsername** [comment]
> I'm sorry, but we cannot accept you working in this org with that user name. You can either change your user name or create a new account for working within this org.
> 
> If you continue to post here with that user name, I will ban your account.


That was the last username available on this platform.

**Comment by WhatsMyMotherFuckerUsername** [comment]
> You're not using that array pool in your example. You're using the shared one, which is a different implementatoin.
> 
> https://github.com/dotnet/runtime/blob/7db092a6ed68a5fbf47962c45bb0c1bb965d02c6/src/libraries/System.Private.CoreLib/src/System/Buffers/ArrayPool.cs#L23


Thanks for your answer. And sorry guys for the mistake. It's sometimes (often) hard to find the appropriate piece of code.
