### ISSUE TITLE
Building src/native results in "ignoring unknown option: --minimize"

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#66770]
Sometime recently, when I attempt to build on macOS, I am greeted with the following error:

<pre>
Build FAILED.

EXEC : error : ignoring unknown option: --minimize [/Users/kjones/Projects/dotnet/runtime/src/native/libs/build-native.proj]
</pre>

It's possibly related to a recently Xcode update or updating to 12.3.

* macOS 12.3
* Xcode 13.3 (13E113)
* `dsymutil --version` output: Apple LLVM version 13.1.6 (clang-1316.0.21.2)

The version of `dsymutil` (in `/usr/bin`) that I have does not seem to have a `--minimize` option.

My current work around is to remove `--minimize` here: https://github.com/dotnet/runtime/blob/048da75f59c975e9bf3c346bee4ce4a9edd11e78/eng/native/functions.cmake#L404

**Comment by vcsjones** [comment]
It does seem that I have an update that removed `--minimize`.

On a computer I haven't updated yet, I see `--minimize` listed in `--help` output. On my version, `--help` makes no mention of `--minimize`.

**Comment by bartonjs** [comment]
I'm guessing `Pub`.

https://github.com/llvm/llvm-project/commit/5d07dc897707f877c45cab6c7e4b65dad7d3ff6d

**Comment by vcsjones** [comment]
I... think... it's saying that `--minimize` is the default behavior. So if we wanted to mimic --minimize behavior, we wouldn't supply anything. `Pub` is introduced to do the thing it was doing when `--minimize` wasn't specified.

**Comment by bartonjs** [comment]
Oh, yeah.  Even the commit description says that.

>  - This patch removes the --minimize option and makes this behavior the
   default. Specifying the flag will result in a warning but won't abort
   the program.

**Comment by vcsjones** [comment]
Thoughts on a fix? If we remove `--minimize`, then it won't have the desired affect on older LLVMs and will be doing the wrong thing. We could... check the output of `dsymutil --help` to see if the help text mentions `--minimize`?


Basically:


```cmake
execute_process(
        COMMAND ${DSYMUTIL} --help
        OUTPUT_VARIABLE DSYMUTIL_HELP_OUTPUT
      )

      if ("${DSYMUTIL_HELP_OUTPUT}" MATCHES "--minimize")
        set(DSYMUTIL_OPTS "--flat --minimize")
      else ()
        set(DSYMUTIL_OPTS "--flat")
      endif ()

      add_custom_command(
        TARGET ${targetName}
        POST_BUILD
        VERBATIM
        COMMAND ${DSYMUTIL} ${DSYMUTIL_OPTS} ${strip_source_file}
        COMMAND ${strip_command}
        COMMENT "Stripping symbols from ${strip_source_file} into file ${strip_destination_file}"
        )
```

Feels like a bit of a kludge but... it works.

**Comment by onurkanbakirci** [comment]
I have simular issue and @vcsjones solution works in my environment.
Xcode version : 13.3
MacOS version : 12.2.1

**Comment by lambdageek** [comment]
I think it has to do with the version of Command Line Tools.  On my machines:

1. Intel Mac Book Pro - works
```
$ xcodebuild -version
Xcode 13.2.1
Build version 13C100
$ dsymutil --flat --minimize artifacts/obj/native/.../libSystem.Globalization.Native.dylib
```

2. M1 MBP - doesn't work
```
$ xcodebuild -version
Xcode 13.3
Build version 13E113
$ dsymutil --flat --minimize 
warning: ignoring unknown option: --minimize
```

**Comment by lambdageek** [comment]
Yea it's definitely Xcode 13.3.  If I do `xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer` and then build, everything works.  switching again to 13.3, it complains about `--minimize`.

**Comment by vcsjones** [comment]
@lambdageek thank you! ✨
