### ISSUE TITLE
[HTTP/3] HttpConnectionPool may leak authorityExpireTimer / hit ObjectDisposedException

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#66782]
Based on code inspection.

`HttpConnectionPool.HandleAltSvc` may create a `Timer` if `Dispose` runs during/before it, and it will never be disposed.
The method should check `_disposed` in this branch (while holding the lock), before creating a new `Timer`: https://github.com/dotnet/runtime/blob/a1bc0f34fc8ad77c31a1682841d92dbb20e39dd8/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1155-L1156

The good news is that the timer won't root the `HttpConnectionPool` instance, but the timer entry may remain queued for a month.

A related issue is that the same method will also access the `_authorityExpireTimer` outside a lock a few lines above, which could lead to an unexpected `ObjectDisposedException` leaking out:
https://github.com/dotnet/runtime/blob/a1bc0f34fc8ad77c31a1682841d92dbb20e39dd8/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1112

**Comment by MihaZupan** [comment]
Looks like [this `AltSvc` logic around the blocklist](https://github.com/dotnet/runtime/blob/a1bc0f34fc8ad77c31a1682841d92dbb20e39dd8/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1280-L1300) is also racy.
Tasks may not be canceled or you may try using a disposed CTS.

In [this case](https://github.com/dotnet/runtime/blob/a1bc0f34fc8ad77c31a1682841d92dbb20e39dd8/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1294-L1298), the whole `HttpConnectionPool` is gonna be rooted by the 10 minute timer.

**Comment by karelz** [comment]
Triage: Affects HTTP/3, reliability - race condition. We should fix it in 7.0.
