### ISSUE TITLE
TlsHandshakeType value 24 should be labeled KeyUpdate

### ISSUE THREAD

**Issue by ritchiecarroll** [dotnet/runtime#66781]
https://github.com/dotnet/runtime/blob/a1bc0f34fc8ad77c31a1682841d92dbb20e39dd8/src/libraries/System.Net.Security/src/System/Net/Security/TlsFrameHelper.cs#L36

Should be `KeyUpdate` not `KeyEpdate`

**Comment by vcsjones** [comment]
Yeah, and I don't see the enum value used anywhere specifically, so supposedly all that needs to be done is to fix that one spot identified.

Would you be interested in providing a pull request for this?

**Comment by ritchiecarroll** [comment]
Will do. 

That said, probably not good that it's not used anywhere: 
https://datatracker.ietf.org/doc/html/rfc8446#section-4.6.3

```
If the request_update field is set to "update_requested", then the
   receiver MUST send a KeyUpdate of its own with request_update set to
   "update_not_requested" prior to sending its next Application Data
   record.
```

**Comment by vcsjones** [comment]
@ritchiecarroll most of the TLS is handled by the platform / OS (SChannel / OpenSSL / SecureTransport) so I would expect the that component to handle the `KeyUpdate` message, and we don't need to look at KeyUpdate frames. @wfurt may know more exactly how this enum is used.

**Comment by ritchiecarroll** [comment]
Good deal. Will send a PR.

**Comment by rzikm** [comment]
@vcsjones  The KeyUpdate enum value currently is not used, it seems to me that the enums were added in bulk with values copied from an RFC.

We use a fraction of them though (for stuff like catching the target hostname from the client hello request)

**Comment by vcsjones** [comment]
@rzikm I thought there might be a small chance we at least log a `TlsHandshakeType` to event source or something and we defined the enum values to make `ToString` look better, so I didn't want to go so far as to recommend removing them.

**Comment by rzikm** [comment]
I don't think we log it to event source, but the ToString definitely makes `TlsFrameInfo` more readable (it has overridden `ToString` and mentions the `TlsHandshakeType`)

**Comment by ritchiecarroll** [comment]
FYI - related idea: https://github.com/dotnet/runtime/discussions/66800

**Comment by wfurt** [comment]
May be worth of fixing https://github.com/microsoft/reverse-proxy/blob/8970c8ded8b47089ef37aab780b0e35648c99adf/src/ReverseProxy/Utilities/TlsFrameHelper.cs#L39 as well

**Comment by ritchiecarroll** [comment]
@wfurt - done: https://github.com/microsoft/reverse-proxy/pull/1614
