### ISSUE TITLE
IncludeNativeLibrariesForSelfExtract gets permissions error when run under C:\Program Files\

### ISSUE THREAD

**Issue by mcattle** [dotnet/runtime#66796]
### Description

The `IncludeNativeLibrariesForSelfExtract` flag alongside the `PublishSingleFile` flag embeds native libraries within the compiled executable.  At runtime, the native libraries are extracted to a folder alongside the executable, which causes a permissions exception if the executable is located in a secure folder, such as under `C:\Program Files\`.

### Reproduction Steps

1. Create a Window Forms project with the following settings:
```
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <DebugType>embedded</DebugType>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>
```

2. Add the NuGet package `Microsoft.Web.WebView2` which contains system native libraries.
3. Use the `WebView2` control on a form (the native libraries are not extracted until they're first invoked).
4. Run the application and display the `WebView2` control.
5. Observe that the folder `.\ApplicationName.exe.WebView2\` is created beside the ApplicationName.exe file.
6. Move the application exe file to a folder under `C:\Program Files\`.
7. Run the application again.
8. Observe that you get a file system permissions exception.

### Expected behavior

The native libraries should extract to `%TEMP%/.net` (or `$HOME/.net` for Mac / Linux), as per the [Single file deployment and executable](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview) documentation.

### Actual behavior

An exception is thrown.

```
************** Exception Text **************
System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Microsoft.Web.WebView2.WinForms.WebView2.InitCoreWebView2Async(CoreWebView2Environment environment)
   at ...
```

### Regression?

No

### Known Workarounds

None.  Pre-copying the extracted folder into `C:\Program Files` alongside the exe does not get around this issue.

### Configuration

.Net 6.0.201
Windows 11 Pro x64 21H2 22000.556

**Comment by vitek-karas** [comment]
This is a problem in WebView2 and not with single-file. The app will fail to run even if published as usual non-single-file. The WebView2 creates a directory next to the executable, if that's not possible it fails. You can configure the path with this API: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1150.38#parameters - see `userDataFolder` parameter.

(Note, single-file already extracts into `HOME`)

**Comment by mcattle** [comment]
That was indeed the issue, and modifying the path of that folder did fix it.

```csharp
var userDataFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "WebView2UserData", Process.GetCurrentProcess().ProcessName);
var coreEnvironment = await CoreWebView2Environment.CreateAsync(null, userDataFolder, null);
using var webView = new WebView2();
await webView.EnsureCoreWebView2Async(coreEnvironment);
```
