### ISSUE TITLE
NativeAOT - Exited with code 137 on Linux

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#66807]
### Description

I'm trying to build an Avalonia project on Linux using NativeAOT `IlCompiler 7.0.0-preview.2.22152.2`. I got lots of AOT analysis warnings but in the end it just fails with 

`error MSB3073: The command ""/home/user/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.2.22152.2/tools/ilc" @"obj/Debug/net6.0/linux-x64/native/AvaloniaProject2.ilc.rsp"" exited with code 137.`

Then I've tried building it for Windows on a Windows 11 machine using `dotnet publish -v q -r win-x64 --self-contained true` command that works fine. Its only building for Linux on Linux which fails.

### Reproduction Steps

Unfortunately it's a private project I cannot share in public

### Expected behavior

Either build succeed or at least produce an error that is more useful

### Actual behavior

Exit code 137

### Configuration

Avalonia Project
ILCompiler 7.0.0-preview.2.22152.2
```
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.406 [/usr/share/dotnet/sdk]
  6.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.15 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

### Other information

Building on Windows for Windows works fine

**Comment by hez2010** [comment]
Exit code 137 is due to out of memory. Your memory size on Linux is insufficient to compile your program.

**Comment by Symbai** [comment]
That did it thank you. I didn't expect it to consume a ridiculous amount of 9GB for a simple program. A more useful error message would be appreciated maybe throwing a outofmemory exception or something.

**Comment by hez2010** [comment]
> a ridiculous amount of 9GB for a simple program

That's not a simple program though. Avalonia has code path with extensive generic explosion which yields tons of types need to be constructed during compilation. That's why compiling a simple Avalonia app with NativeAOT cost a lot of time and memory.

**Comment by Symbai** [comment]
Ah ok, with simple I was speaking about my own code. Yeah I saw the final app is ~400mb large. Still I wonder if this can be improved by flushing to disk or using a memorymappedfile instead of loading everything into memory until it runs out of it.

**Comment by hez2010** [comment]
> the final app is ~400mb large

Most are symbol files. You can strip the binary, then there should be only less than 100mb left.
