### ISSUE TITLE
JsonObject  Unable to find a default constructor to use for type

### ISSUE THREAD

**Issue by YongChingShieh** [dotnet/runtime#66808]
### Description

I'm trying to  System.Text.Json ,but I get this error:
Unable to find a default constructor to use for type System.Text.Json.Nodes.JsonObject

### Reproduction Steps

json:
`{
account: "admin",
password: "700aa89fe0c3649b197787310c8e0d39",
_allow_anonymous: true
}`

 JsonSerializerOptions:
>  builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.AllowTrailingCommas = true;
    options.JsonSerializerOptions.ReadCommentHandling = System.Text.Json.JsonCommentHandling.Skip;
    options.JsonSerializerOptions.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
    options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.IgnoreCycles;
    options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowReadingFromString | JsonNumberHandling.WriteAsString;
    options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
    options.JsonSerializerOptions.PropertyNamingPolicy = null;
    options.JsonSerializerOptions.IgnoreReadOnlyFields = true;
    options.JsonSerializerOptions.IgnoreReadOnlyProperties = true;
});

controller:
 

>  [HttpPost("SubmitLogin")]
        [AllowAnonymous]
        public async Task<IActionResult> SubmitLogin([FromBody] JsonObject param)
{
 var obj = param;
                return Ok();
}
 

### Expected behavior

error info:

> Unable to find a default constructor to use for type System.Text.Json.Nodes.JsonObject

![QQ截图20220318110022](https://user-images.githubusercontent.com/24885976/158930417-edc491bf-0464-4e7f-bed6-49ec0edecaf1.png)

 

### Actual behavior

 `{"errors":{"_allow_anonymous":["Unable to find a default constructor to use for type System.Text.Json.Nodes.JsonObject. Path '_allow_anonymous', line 1, position 20."]},"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-750b27ebba1ac41b64702194fc46afa4-f553649d86741424-00"}`

### Configuration

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by krwq** [comment]
@YongChingShieh can you please isolate the repro to only use System.Text.Json?
