### ISSUE TITLE
NativeAOT requirements on Linux

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#66806]
Building for windows on windows works fine. Building for Linux on Windows fails saying cross compiling is not allowed. So I've installed Ubuntu 20.04 in a virtual machine, installed .NET6 SDK and tried to build but it fails saying `Clang` is missing. I haven't heard that name before so I've googled how to install that and run `sudo apt install clang-12 --install-suggests` but it still fails to find `Clang`. So I've ran `sudo apt-get install llvm` but it still fails Clang.

Is there any official documentation on what is required on Linux to build with NativeAOT and perhaps installation instructions for users with less Linux experience?

**Comment by jkotas** [comment]
The prerequisites are documented at https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/prerequisites.md#ubuntu-1604 . (These docs will move to the docs repo as we get closer to the release.)
