### ISSUE TITLE
NativeAOT: write dgml regardless the failure of compilation

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#66813]
ilc may fail during marking or compilation, in this case no dgml would be written out so we cannot diagnostic the issue with the dependency graph (though it's incomplete).

https://github.com/dotnet/runtime/blob/5371203d5820a21922357e954e8c43eb4b76fd1d/src/coreclr/tools/aot/ILCompiler/Program.cs#L817

I think instead of throwing the exception directly in the compilation process, we should just write the dgml even if the dependency graph is incomplete, if appliable.

**Comment by MichalStrehovsky** [comment]
The [DependencyGraphViewer](https://github.com/dotnet/runtime/tree/0b12d37843e7165fb4c8b794186f19ef43af6c73/src/coreclr/tools/aot/DependencyGraphViewer) tool tends to work better for the cases where the graph is incomplete. Thanks to it being out-of-process, it can  better handle all sorts of fatal situations like running out of memory. It might be interesting to add DGML export to the viewer tool.

**Comment by hez2010** [comment]
> The DependencyGraphViewer tool

I tried it but nothing showed up in the list after launching an ilc process. Am I missing something?

**Comment by MichalStrehovsky** [comment]
> I tried it but nothing showed up in the list after launching an ilc process. Am I missing something?

Did you have the DGML logging option specified by any chance? EventSource logging (consumed by the DependencyGraphViewer) doesn't happen if DGML is requested.

**Comment by hez2010** [comment]
> EventSource logging (consumed by the DependencyGraphViewer) doesn't happen if DGML is requested.

Seems to be the case. Thank you.

**Comment by hez2010** [comment]
Closing since we can already use DGlViewer for the purpose.
