### ISSUE TITLE
Password character display on console with Console.ReadKey(true)

### ISSUE THREAD

**Issue by mazm786** [dotnet/runtime#66829]
### Description

I am reading Password from console by **Console.ReadKey(true)** but Sometimes password character display om console while true is passed.

### Reproduction Steps

```c#
            string pass = string.Empty;
            ConsoleKey key;

            do
            {
                var keyInfo = Console.ReadKey(intercept: true);
                key = keyInfo.Key;
                try
                {
                    if (key == ConsoleKey.Backspace && pass.Length > 0)
                    {
                        Console.Write("\b \b");
                        pass = pass[0..^1];
                    }
                    else if (!char.IsControl(keyInfo.KeyChar))
                    {
                        Console.Write("*");
                        pass += keyInfo.KeyChar;
                    }
                    else
                    {
                    }
                }
                catch (Exception ex)
                {
                    //SavePasswordCharsForDebug($"[Exception] ReadChar:{keyInfo.KeyChar}, Key:{key.ToString()}{Environment.NewLine}{ex.Message}");
                }
            } while (key != ConsoleKey.Enter);
```

### Expected behavior

There should be display only `****`

### Actual behavior

![image](https://user-images.githubusercontent.com/68580069/159009275-26c8d5b9-98f8-4b5b-9384-cbea761ead84.png)

### Regression?

.net 5.0

**Comment by joshudson** [comment]
Don't use that API. It's clearly designed wrong at the API level for calling in a loop. Effectively this reads:

````
            Console.DisableEcho(); // These functions don't actually exist.
            var keyInfo = Console.ReadKey();
            Console.EnableEcho();
````

See the problem now?

**Comment by huoyaoyuan** [comment]
It's obviously some version of Windows 10, which shouldn't differ much.

> but Sometimes

What about the occurrence frequency?

**Comment by mazm786** [comment]
> What OS is this?

Windows 10

**Comment by mazm786** [comment]
> It's obviously some version of Windows 10, which shouldn't differ much.
> 
> > but Sometimes
> 
> What about the occurrence frequency?

4 times out of 10

**Comment by mazm786** [comment]
> Don't use that API. It's clearly designed wrong at the API level for calling in a loop. Effectively this reads:
> 
> ```
>             Console.DisableEcho(); // These functions don't actually exist.
>             var keyInfo = Console.ReadKey();
>             Console.EnableEcho();
> ```
> 
> See the problem now?

Console.DisableEcho() / Console.EnableEcho() methods don't exists then there is no mean of this comment

**Comment by joshudson** [comment]
@mazm786 : But there is meaning. The problem clearly happens when a key is pressed while the previous key is in the processing loop and the code hasn't gotten back around to disabling keyboard echo yet.

**Comment by skyoxZ** [comment]
I can't reproduce the issue on my Win11 & .NET 6.0.

**Comment by adamsitnik** [comment]
@mazm786 which terminal are you using?

**Comment by jeffhandley** [comment]
@mazm786 I've tried to reproduce this, but I haven't been able to. I've tried:

1. Windows Terminal
2. Windows Terminal Preview
3. Windows Console Host
4. .NET 6.0
5. .NET 7.0 (preview 4)
6. Smashing the keyboard
7. Holding key(s)
8. Pasting from clipboard
9. Lots of backspacing

But I've been unable to see what you're observing. I used the exact code you have shared as the entirety of the `Program.cs` with only the following as the project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>6</AnalysisLevel>
  </PropertyGroup>

</Project>
```

Are you still able to reproduce this with only that minimal repro as well? And can you clarify what terminal/console host you're using, if you're running in debug or release mode, if you can reproduce this on multiple machines, or anything else that you can think might be helpful?

Thanks!
