### ISSUE TITLE
 System.Security.Cryptography.Tests out of memory

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#66831]
We are getting out of memory error on System.Security.Cryptography.Tests.
o	Build Android x86 Release AllSubsets_Mono [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-52b7f69e28e84c63a1/System.Security.Cryptography.Tests/1/adb-logcat-net.dot.System.Security.Cryptography.Tests-net.dot.MonoRunner.log?sv=2019-07-07&se=2022-04-06T21%3A58%3A43Z&sr=c&sp=rl&sig=auPVgPO3CrTmdj%2FApFRUYTiIpU6P%2BlwXYFfD81l0AGo%3D), [Run 20220317.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1669205&view=logs&j=0f546c32-999b-56dd-5ce9-08c68d21e4c4&t=74727783-ba2d-5b46-44bc-42ba967ce1c5).
```
03-17 22:13:04.340  5083  5165 D DOTNET  : ((null) error) Could not allocate 220 (1 * 220) bytes
03-17 22:13:04.340  5083  5165 E DOTNET  : Exit code: 1.
....
03-17 22:13:04.489  1911  1935 W android.os.Debug: failed to get memory consumption info: -1
```
o	Build Android x64 Release AllSubsets_Mono [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f19579322919476b8b/System.Security.Cryptography.Tests/1/adb-logcat-net.dot.System.Security.Cryptography.Tests-net.dot.MonoRunner.log?sv=2019-07-07&se=2022-04-01T10%3A06%3A02Z&sr=c&sp=rl&sig=vaUTgwdaMqFRaNg3epM02I1FL6tFUKRAjC2dZtSIdc4%3D), [Run 20220312.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1660118&view=logs&j=b6e5d97f-d4f8-506b-9e47-e3e32385754a&t=94ce2805-f3e2-5f9a-1d92-0da5613f733d).
```
03-12 10:22:13.927  6888  6962 I DOTNET  : 	[PASS] System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidIVSizes
03-12 10:22:14.338  1713  1713 E lowmemorykiller: Kill 'com.android.deskclock' (3191), uid 10109, oom_adj 975 to free 59372kB
03-12 10:22:14.338  1713  1713 I lowmemorykiller: Reclaimed 59372kB, cache(320944kB) and free(75024kB)-reserved(80816kB) below min(322560kB) for oom_adj 950
03-12 10:22:14.369  1713  1713 I lowmemorykiller: 2 memory pressure events were skipped after a kill!
03-12 10:22:14.369  1713  1713 E lowmemorykiller: Kill 'com.android.dynsystem' (3226), uid 1000, oom_adj 975 to free 51840kB
03-12 10:22:14.369  1713  1713 I lowmemorykiller: Reclaimed 51840kB, cache(310788kB) and free(83348kB)-reserved(80816kB) below min(322560kB) for oom_adj 950
03-12 10:22:14.409  1671  1671 I Zygote  : Process 3191 exited due to signal 9 (Killed)
03-12 10:22:14.409  1671  6889 I Zygote  : Process 3226 exited due to signal 9 (Killed)
03-12 10:22:14.410  1713  1713 I lowmemorykiller: 3 memory pressure events were skipped after a kill!
03-12 10:22:14.410  1713  1713 E lowmemorykiller: Kill 'com.android.managedprovisioning' (3009), uid 10059, oom_adj 965 to free 55636kB
03-12 10:22:14.410  1713  1713 I lowmemorykiller: Reclaimed 55636kB, cache(300224kB) and free(82096kB)-reserved(80816kB) below min(322560kB) for oom_adj 950
03-12 10:22:14.441  1913  2138 I ActivityManager: Process com.android.deskclock (pid 3191) has died: cch+75 CEM 
03-12 10:22:14.458  1913  1940 I libprocessgroup: Successfully killed process cgroup uid 10109 pid 3191 in 0ms
03-12 10:22:14.471  1671  1671 I Zygote  : Process 3009 exited due to signal 9 (Killed)
```
o	Build Android arm Release AllSubsets_Mono [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview1f0b9e2eccbe9452dba/System.Security.Cryptography.Tests/1/adb-logcat-net.dot.System.Security.Cryptography.Tests-net.dot.MonoRunner.log?sv=2019-07-07&se=2022-04-03T19%3A11%3A03Z&sr=c&sp=rl&sig=gr%2F3S1m5mOAXbqd9ZfjMLlDVvocXcxg04Qjoj46mM1g%3D) [Run 20220314.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1662501&view=logs&j=ce8bb18a-3299-5fcd-e022-e51015a098bb&t=ba57798b-4339-5c09-4389-8cb6ee18eeba)
```
--------- beginning of crash
03-14 12:23:00.217 13089 13117 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13117 (Thread-3), pid 13089 (ptography.Tests)
03-14 12:23:00.218 13089 13109 W libc    : pthread_create failed: couldn't allocate 1052672-bytes mapped space: Out of memory
03-14 12:23:00.218 13089 13109 E libutils.threads: androidCreateRawThreadEtc failed (entry=0xf0393905, res=11, Success)
03-14 12:23:00.218 13089 13109 E libutils.threads: (android threadPriority=0)
03-14 12:23:00.820 13129 13129 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
03-14 12:23:00.828   851   851 I tombstoned: received crash request for pid 13117
03-14 12:23:00.829 13129 13129 I crash_dump32: performing dump of process 13089 (target tid = 13117)
03-14 12:23:00.871 13129 13129 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-14 12:23:00.872 13129 13129 F DEBUG   : Build fingerprint: 'google/sunfish/sunfish:11/RP1A.200720.011/6746289:user/release-keys'
03-14 12:23:00.872 13129 13129 F DEBUG   : Revision: 'MP1.0'
03-14 12:23:00.872 13129 13129 F DEBUG   : ABI: 'arm'
03-14 12:23:00.873 13129 13129 F DEBUG   : Timestamp: 2022-03-14 12:23:00-0700
03-14 12:23:00.873 13129 13129 F DEBUG   : pid: 13089, tid: 13117, name: Thread-3  >>> net.dot.System.Security.Cryptography.Tests <<<
03-14 12:23:00.873 13129 13129 F DEBUG   : uid: 15986
03-14 12:23:00.873 13129 13129 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
03-14 12:23:00.873 13129 13129 F DEBUG   : Abort message: 'terminating with uncaught exception of type St9bad_alloc: std::bad_alloc'
03-14 12:23:00.873 13129 13129 F DEBUG   :     r0  00000000  r1  0000333d  r2  00000006  r3  c3efe9b8
03-14 12:23:00.873 13129 13129 F DEBUG   :     r4  c3efe9cc  r5  c3efe9b0  r6  00003321  r7  0000016b
03-14 12:23:00.873 13129 13129 F DEBUG   :     r8  c3efe9b8  r9  c3efe9c8  r10 c3efe9e8  r11 c3efe9d8
03-14 12:23:00.873 13129 13129 F DEBUG   :     ip  0000333d  sp  c3efe988  lr  f2ebc3e1  pc  f2ebc3f4
```

**Comment by fanyang-mono** [comment]
This test failed 4 times in builds on Android platform for the past 7 days.
https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E7+definition%3Aruntime-extra-platforms+kind%3Arolling+workItemName%3A%22System.Security.Cryptography.Tests%22+jobName%3A%22Android%22

**Comment by vcsjones** [comment]
This issue looks like a duplicate of https://github.com/dotnet/runtime/issues/62547.

**Comment by fanyang-mono** [comment]
> This issue looks like a duplicate of #62547.

Interesting... That issue indicates that the test was disabled... But the failure is still happening on CI.

**Comment by akoeplinger** [comment]
We disabled some tests with https://github.com/dotnet/runtime/pull/62767, but not everything.

**Comment by fanyang-mono** [comment]
> We disabled some tests with #62767, but not everything.

We need to disable more. It is being hit quite often on rolling build.
