### ISSUE TITLE
System.Numerics.Tests.Perf_VectorConvert.Convert_ulong_double has regressed a lot on x86

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#66832]
`System.Numerics.Tests.Perf_VectorConvert.Convert_ulong_double` has regressed **x25** on x86, but improved for x64.

[Reporting system](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x86_Windows%2010.0.18362%2fSystem.Numerics.Tests.Perf_VectorConvert.Convert_ulong_double.html):

![image](https://user-images.githubusercontent.com/6011991/159020000-233d161c-5ac7-40e7-914b-570b190995f4.png)

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 net7.0 --filter System.Numerics.Tests.Perf_VectorConvert.Convert_ulong_double --architecture x86
```

<details>

| Result |     Base |     Diff | Ratio | Operating System      | Bit   |
| ------ | --------:| --------:| -----:| --------------------- | ----- |
| Faster |  1617.02 |   574.60 |  2.81 | Windows 11            | X64   |
| Faster |   890.92 |   410.82 |  2.17 | Windows 11            | X64   |
| Faster |  3121.80 |  1263.22 |  2.47 | Windows 11            | X64   |
| Faster |  1445.69 |   725.92 |  1.99 | Windows 10            | X64   |
| Faster |  2120.73 |   809.30 |  2.62 | Windows 11            | X64   |
| Faster |  2465.62 |  1009.49 |  2.44 | Windows 11            | X64   |
| Faster |   953.99 |   423.17 |  2.25 | ubuntu 18.04          | X64   |
| Faster |   966.86 |   425.70 |  2.27 | ubuntu 20.04          | X64   |
| Faster |  2308.55 |   965.59 |  2.39 | ubuntu 18.04          | X64   |
| Faster |  2771.01 |  1333.80 |  2.08 | ubuntu 18.04          | X64   |
| Faster |  2147.64 |   991.60 |  2.17 | pop 20.04             | X64   |
| Faster |  1263.20 |   736.57 |  1.71 | alpine 3.13           | X64   |
| Faster |  1259.47 |   730.80 |  1.72 | debian 11             | X64   |
| Same   |   585.29 |   579.48 |  1.01 | macOS Monterey 12.2.1 | Arm64 |
| Same   |   676.53 |   676.12 |  1.00 | Windows 10            | Arm64 |
| Same   |   678.29 |   678.43 |  1.00 | Windows 11            | Arm64 |
| Slower |  3176.11 | 43751.84 |  0.07 | Windows 10            | X86   |
| Slower |  1597.47 | 32929.64 |  0.05 | Windows 10            | X86   |
| Slower |  1446.79 | 33592.24 |  0.04 | Windows 10            | X86   |
| Faster | 53217.69 | 34251.08 |  1.55 | Windows 10            | Arm   |
| Faster |  2875.52 |  1047.20 |  2.75 | macOS Big Sur 11.6.3  | X64   |
| Faster |  2455.51 |   887.62 |  2.77 | macOS Monterey 12.2.1 | X64   |
| Faster |  2373.55 |   984.52 |  2.41 | macOS Monterey 12.2.1 | X64   |

</details>

cc @tannergooding 

Most likely related to https://github.com/dotnet/runtime/issues/65189

**Comment by tannergooding** [comment]
The previous algorithm was incorrect for x86 and producing incorrect results. This was an intentional change and something that is non-trivial to fix without further work elsewhere.

**Comment by dakersnar** [comment]
Closing as dup of https://github.com/dotnet/runtime/issues/65189
