### ISSUE TITLE
float parsing benchmarks have regressed on 32 bit platforms

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#66838]
`System.Text.Json.Tests.Perf_Get.GetSingle` has regressed20-35% on 32 bit platforms.

[Reporting system](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x86_Windows%2010.0.18362%2fSystem.Text.Json.Tests.Perf_Get.GetSingle.html):

![image](https://user-images.githubusercontent.com/6011991/159040415-507ff512-7710-452a-9b56-77db86c4c3ec.png)

Looking at the [commit diff](https://github.com/dotnet/runtime/compare/3fc8b099443a8b84bd158b8e49e38be6dd941180...3ae87395f638a533f37b8e3385f6d3f199a72f4f) it's most likely caused by https://github.com/dotnet/runtime/pull/62301 (cc @tannergooding )

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 net7.0 --filter System.Text.Json.Tests.Perf_Get.GetSingle --architecture x86
```

<details>

| Result |    Base |     Diff | Ratio | Operating System      | Bit   |
| ------ | -------:| --------:| -----:| --------------------- | ----- |
| Same   | 4212.28 |  4309.12 |  0.98 | Windows 11            | X64   |
| Same   | 3148.27 |  3090.19 |  1.02 | Windows 11            | X64   |
| Same   | 6700.49 |  6771.64 |  0.99 | Windows 11            | X64   |
| Same   | 4020.62 |  3911.91 |  1.03 | Windows 10            | X64   |
| Same   | 4762.67 |  4713.94 |  1.01 | Windows 11            | X64   |
| Same   | 6261.90 |  6353.20 |  0.99 | Windows 11            | X64   |
| Same   | 3296.56 |  3302.37 |  1.00 | ubuntu 18.04          | X64   |
| Same   | 3239.55 |  3279.82 |  0.99 | ubuntu 20.04          | X64   |
| Same   | 4849.07 |  4823.87 |  1.01 | ubuntu 18.04          | X64   |
| Faster | 8014.18 |  7156.92 |  1.12 | ubuntu 18.04          | X64   |
| Same   | 5664.32 |  5763.96 |  0.98 | pop 20.04             | X64   |
| Same   | 4093.16 |  4155.46 |  0.99 | alpine 3.13           | X64   |
| Same   | 4142.95 |  4086.97 |  1.01 | debian 11             | X64   |
| Same   | 3019.47 |  2769.70 |  1.09 | macOS Monterey 12.2.1 | Arm64 |
| Same   | 5855.04 |  6198.09 |  0.94 | Windows 10            | Arm64 |
| Same   | 5835.18 |  6237.83 |  0.94 | Windows 11            | Arm64 |
| Slower | 6937.67 |  9177.62 |  **0.76** | Windows 10            | X86   |
| Slower | 6132.79 |  7625.77 |  **0.80** | Windows 10            | X86   |
| Slower | 5636.96 |  7136.83 |  **0.79** | Windows 10            | X86   |
| Slower | 7610.08 | 11632.67 |  **0.65** | Windows 10            | Arm   |
| Same   | 6309.44 |  6450.41 |  0.98 | macOS Big Sur 11.6.3  | X64   |
| Same   | 5345.03 |  5463.62 |  0.98 | macOS Monterey 12.2.1 | X64   |
| Same   | 5618.79 |  5573.90 |  1.01 | macOS Monterey 12.2.1 | X64   |

</details>

**Comment by adamsitnik** [comment]
Another float parsing benchmark has regressed. I am going to move it to `System.Runtime` area.

<details>

## System.Tests.Perf_Single.TryParse(value: "12345")

| Result |   Base |   Diff | Ratio | Alloc Delta | Modality | Operating System      | Bit   |
| ------ | ------:| ------:| -----:| -----------:| -------- | --------------------- | ----- |
| Same   |  51.12 |  49.22 |  1.04 |          +0 |          | Windows 11            | X64   |
| Same   |  33.14 |  31.23 |  1.06 |          +0 |          | Windows 11            | X64   |
| Same   | 103.06 |  90.25 |  1.14 |          +0 | bimodal  | Windows 11            | X64   |
| Same   |  43.54 |  46.29 |  0.94 |          +0 |          | Windows 10            | X64   |
| Same   |  58.11 |  58.26 |  1.00 |          +0 |          | Windows 11            | X64   |
| Same   |  69.92 |  74.12 |  0.94 |          +0 |          | Windows 11            | X64   |
| Same   |  35.41 |  34.39 |  1.03 |          +0 |          | ubuntu 18.04          | X64   |
| Same   |  35.28 |  35.36 |  1.00 |          +0 |          | ubuntu 20.04          | X64   |
| Same   |  60.89 |  55.02 |  1.11 |          +0 |          | ubuntu 18.04          | X64   |
| Faster | 104.73 |  84.73 |  1.24 |          +0 |          | ubuntu 18.04          | X64   |
| Same   |  73.72 |  80.39 |  0.92 |          +0 |          | pop 20.04             | X64   |
| Same   |  53.82 |  50.71 |  1.06 |          +0 |          | alpine 3.13           | X64   |
| Same   |  51.57 |  49.92 |  1.03 |          +0 |          | debian 11             | X64   |
| Faster |  42.74 |  30.88 |  1.38 |          +0 |          | macOS Monterey 12.2.1 | Arm64 |
| Same   |  72.11 |  70.38 |  1.02 |          +0 |          | Windows 10            | Arm64 |
| Same   |  72.64 |  72.16 |  1.01 |          +0 |          | Windows 11            | Arm64 |
| Slower |  73.55 |  89.52 |  0.82 |          +0 |          | Windows 10            | X86   |
| Slower |  61.26 |  75.67 |  0.81 |          +0 |          | Windows 10            | X86   |
| Slower |  56.50 |  70.17 |  0.81 |          +0 |          | Windows 10            | X86   |
| Slower | 101.22 | 138.28 |  0.73 |          +0 |          | Windows 10            | Arm   |
| Same   |  79.53 |  72.40 |  1.10 |          +0 |          | macOS Big Sur 11.6.3  | X64   |
| Same   |  60.28 |  61.36 |  0.98 |          +0 |          | macOS Monterey 12.2.1 | X64   |
| Same   |  68.99 |  65.48 |  1.05 |          +0 |          | macOS Monterey 12.2.1 | X64   |

</details>

**Comment by dakersnar** [comment]
We significantly improved x64 performance, so this 32-bit regression is somewhat by design.

**Comment by adamsitnik** [comment]
> We significantly improved x64 performance, so this 32-bit regression is somewhat by design

@dakersnar was it done on purpose, or the 32 bit regression is just a side effect?

**Comment by tannergooding** [comment]
Like most regressions it wasn't intentional. However, 32-bit perf isn't nearly as important as 64-bit anymore and we have a lot of prior art for minorly reducing its throughput in favor of simplifying the overall code and/or for providing improvements to 64-bit instead.

We could potentially mitigate this regression by providing an alternative implementation for `internal static uint ParseEightDigitsUnrolled(byte* chars)` or improving the JIT handling of `64 * 32` bit multiplications, but the overall code complexity likely isn't worth it (nor justifiable prioritizable compared to other work).

The benchmark in question is serializing 100 floats and so the increased cost is about 15ns per operation (somewhere around 30-60 cycles, depending on CPU speed). This came at the cost of nearly 2x throughput for various other workloads representing real world data sets and so directly benefits things like ML.NET and other areas of interest.
