### ISSUE TITLE
RegexGenerator fails for interfaces with in/out type parameters

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#66842]
### Description

In `7.0.100-preview.2.22153.17`, there is an issue using the attribute for an interface method as a default interface implementation if the interface has an `out` or `in` type parameter.

> error CS8427: Enums, classes, and structures cannot be declared in an interface that has an 'in' or 'out' type parameter.

### Reproduction Steps

- Code 1

    ```csharp
    partial interface I<T>
    {
        [RegexGenerator(@".+?")]
        public static partial Regex Test();
    }
    ```

- Code 2

    ```csharp
    partial interface I<out T>
    {
        [RegexGenerator(@".+?")]
        public static partial Regex Test();
    }
    ```

### Expected behavior

Both samples compile

### Actual behavior

The first one compiles, but the second one fails with:

> error CS8427: Enums, classes, and structures cannot be declared in an interface that has an 'in' or 'out' type parameter.

**Comment by Youssef1313** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
I'll take a look... I suspect this is no longer an issue...
