### ISSUE TITLE
NativeAOT doesn't work with Linux non-portable build

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#66859]
The problem is that NativeAOT references OpenSSL in two different ways, depending on whether we're doing a portable build or not.

When portable, the Native AOT runtime uses lazy loading (dlopen) to load the installed OpenSSL shared library. This means that the final linking command for a Native AOT app doesn't need the OpenSSL dev shared library to be passed when linking, since it will not try to statically resolve symbols.

This is not true for non-portable builds. In this case, Native AOT is built directly against OpenSSL headers/SOs. This means that Native AOT apps have to pass the appropriate SO to the linker during final linking of NativeAOT apps.

This means that the linking of Native AOT apps depends on whether it was originally compiled with a portable build. We could also try to remove this difference at the root by choosing one way to reference OpenSSL consistently.

More broadly, the feature of a "non-portable" AOT build is questionable. This would produce a Native AOT compiler which can only compiler for the exact platform (e.g. Ubuntu 22.04) that the compiler was built for. This is generally an anti-pattern in compilers.

**Comment by omajid** [comment]
How does NativeAOT deal with bundled/system library split? Is that something else that needs to be tracked here?

**Comment by jkotas** [comment]
> In source build, NativeAOT is built directly against OpenSSL headers/SOs. This means that NativeAOT apps have to pass the appropriate SO to the linker during final linking of NativeAOT apps.

All native dependencies are referenced directly in source build. We would need to do this for icu, gssapi, zlib, brotli, and potentially also libunwind that @omajid mentioned above.

**Comment by jkotas** [comment]
Not required for 7.0: https://github.com/dotnet/source-build/issues/2885#issuecomment-1229743173

**Comment by crummel** [comment]
I've summarized what I believe to be the current state of play and the agreed-upon solution for NativeAOT in 7.0 in https://github.com/dotnet/runtime/pull/76206.  Please check this out and let me know if you have any concerns.

**Comment by jkoritzinsky** [comment]
To expand on this, the flag here is actually controlled by if the build is portable, not necessarily source-build (it's possible to build a non-portable regular build and easier to do locally).

**Comment by jkotas** [comment]
We still have TODO comments linked to this issue https://github.com/search?q=repo%3Adotnet%2Fruntime%20https%3A%2F%2Fgithub.com%2Fdotnet%2Fruntime%2Fissues%2F66859&type=code , so I assume this should stay open?

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/issues/97521 has discussion about the fix

**Comment by agocke** [comment]
Yup, this was a mistake, I meant to close https://github.com/dotnet/runtime/issues/97521

**Comment by tmds** [comment]
I think that - thanks to the managed ObjWriter by @filipnavara! - this is the main thing that still needs to be solved to enable NativeAOT for source-build.

We need something that enables the linker flags to be different for non-portable builds.

Based on how we made source-build capable of doing SCD publish, I assume the flags would be stored in a rid-specific pack/package/folder. That is: the flags for portable would be in _something_ `linux-x64`, and the flags for a distro-specific source-build would be in _something_ `fedora.39-x64`.

A user then has these options:
- (using a portable rid for) building a portable NativeAOT app (leveraging nuget.org Microsoft binaries)
- (using a non-portable rid for) building a non-portable NativeAOT app (using distro binaries)

This first app is meant to work across a range of distros, and the second app is meant to meet the requirements for being included in a distro package (because _all binaries used were built from source_).

cc @dotnet/distro-maintainers

**Comment by jkotas** [comment]
> We need something that enables the linker flags to be different for non-portable build

Take a look at https://github.com/dotnet/runtime/pull/97536 . With this change, `/p:PortableBuild=false` build is going to produce native aot packages with distro specific RID. `PublishAot` with these packages is going to pass additional options to linker to produce distro specific binary.

**Comment by jkotas** [comment]
The last place that needs fixing is: https://github.com/dotnet/runtime/blob/7f02aef31e7da392b2d3c9c2847a253f01fc108e/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj#L13-L14 . We should wait for the LKG SDK to pickup changes from #97536 first.

**Comment by jkotas** [comment]
I am reverting part of the change in https://github.com/dotnet/runtime/pull/98303 to fix build break in source build. There is a confusion between the portable RID, non-portable RID and host RID.

@tmds Could you please take a look if you get a chance?

**Comment by tmds** [comment]
Sure, I'll take a closer look.

**Comment by tmds** [comment]
I will be looking into this next week.
