### ISSUE TITLE
Use live apphost build in crossgen2

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#66866]
CG2 sets `AppHostRuntimeIdentifier` which tells SDK to use specific platform apphost from prebuilt NuGet packages.
https://github.com/dotnet/runtime/blob/59b5585bd29333a8f00f3819f908930705c484f4/src/coreclr/tools/aot/crossgen2/crossgen2.csproj#L6
The non-MSFT package maintainers have option to build custom apphost package and push it to their nuget feed (e.g. local file system or organization nuget server), then add that feed in NuGet.config to use the custom apphost. 
https://github.com/dotnet/runtime/blob/59b5585bd29333a8f00f3819f908930705c484f4/NuGet.config#L10
On community-supported platforms, such as FreeBSD, similar approach is used to build CG2 binary (since there is no `microsoft.netcore.app.crossgen2.freebsd-x64.<version>.nupkg` availabe in runtime's official nuget feed). However, when cross-compiling CG2 on FreeBSD in CI, we have disabled CG2 because we don't use multi-stage build (i.e. first build apphost, publish it to local nuget feed, then build the product with that apphost).

Therefore, if we use live-build of apphost in CG2 build, at least on community platforms; similar to what was done for testhost: https://github.com/dotnet/runtime/blob/79026a542a8364b6783c5d212bb1841ac2c873a9/src/libraries/externals.csproj#L12
we can avoid the multi-stage build overhead and bring community platforms on the same plan as the official ones (as far as CG2 is concerned).

**Comment by MichalStrehovsky** [comment]
> bring community platforms on the same plan as the official ones (as far as CG2 is concerned).

Just a note that the north star is to build crossgen2 with NativeAOT: #65948 is already enabling this for some platforms. No apphost needed for NativeAOT.

**Comment by am11** [comment]
Great! Looks like even for platforms which currently do not support NativeAOT, with #65948 crossgen2 will be published as a self-contained, single file, application with live corehost which will essentially fix this issue.

**Comment by agocke** [comment]
I believe this is fixed now
