### ISSUE TITLE
RotateFlip for 1-bit image with the width of multiples of 8

### ISSUE THREAD

**Issue by strobila** [dotnet/runtime#66871]
### Description

When using a System.Drawing.Bitmap instance, loaded a 1-bit image with the width of multiples of 8px, 
Calling its RotateFlip method produces unexpected result.

If input image is not 1-bit or its width is not multiples of 8px, the issue is not produced.

### Reproduction Steps

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Drawing;
using System.Runtime.InteropServices;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            const string imgpath = @"test.bmp";    // 1-bit bitmap

            Bitmap bmp = new Bitmap(imgpath);
            bmp.Save("1_before.bmp", System.Drawing.Imaging.ImageFormat.Bmp);

            bmp.RotateFlip(RotateFlipType.Rotate180FlipNone);
            bmp.Save("2_after.bmp", System.Drawing.Imaging.ImageFormat.Bmp);
         }
    }
}
```

test.bmp:
![test](https://user-images.githubusercontent.com/101912502/159104988-7c249b42-4091-417f-acb6-2066d2626e6d.png)

### Expected behavior

gets rotated output image, without any changes of pixel value.

### Actual behavior

gets rotated output image, but it's shifted 8px to the left, and vacant space is filled by 1st color in ColorTable

![2_after](https://user-images.githubusercontent.com/101912502/159105643-7bd44577-4252-4507-995f-2e6a0bfde291.png)

### Configuration

As far as I seen, any combination of above reproduces the issue.

version: .NET 6.0, .NET Framework 4.6.1
OS: Windows 10
target arch: x64(AnyCPU), x86

**Comment by AaronRobinsonMSFT** [comment]
@strobila This appears to be directly passing through the data to the native GDI method. See https://github.com/dotnet/runtime/blob/fa1f2834dace0a34c53f1e1039b5af640fe51576/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs#L429-L433

Would it be possible for you to try this using the native GDI method? If it reproduces, which I'd be surprised if it didn't there is an issue in the GDI API - not .NET.

I suppose this could also be an issue with how we are describing encoding the BMP data in the handle. That should also to be consisered.

**Comment by AaronRobinsonMSFT** [comment]
Looks like this is an issue with GDI. The below is using GDI in C++ and exhibits the same behavior.

I assume the `System.Drawing` owners have appropriate contacts.

```cpp
#include <Windows.h>
#include <gdiplus.h>
#include <gdiplusbitmap.h>

using namespace Gdiplus;
#pragma comment (lib,"Gdiplus.lib")

int main(int ac, const char **av)
{
    auto path = L"F:\\scratch\\test.bmp";
    GdiplusStartupInput gdiplusStartupInput;
    ULONG_PTR gdiplusToken;
    GdiplusStartup(&gdiplusToken, &gdiplusStartupInput, NULL);

    Bitmap bmp(path);

    Status rc;
    rc = bmp.RotateFlip(Rotate180FlipNone);

    CLSID bmpEcoderClsid;
    CLSIDFromString(L"{557CF400-1A04-11D3-9A73-0000F81EF32E}", &bmpEcoderClsid);

    rc = bmp.Save(L"F:\\scratch\\flip.bmp", &bmpEcoderClsid);

    return EXIT_SUCCESS;
}
```

**Comment by JeremyKuhne** [comment]
@ViktorHofer this is an issue with GDI+ (not GDI) as @AaronRobinsonMSFT saw with his native GDI+ example. Unfortunately, there isn't much that can be done as GDI+ is not in active development. The only issues we could possibly get considered would be regressions from one version of Windows to another.

@strobila have you considered using alternatives as described in the docs? https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=net-6.0#remarks
