### ISSUE TITLE
Use REP MOVSB on Ice Lake+ for locals init

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/runtime#66872]
Ice Lake+ 128B is done in hardware and is faster than anything the CLR can do.

**Comment by huoyaoyuan** [comment]
Related discussions I can find:

https://stackoverflow.com/questions/51120541/compiler-choice-of-not-using-rep-movsb-instruction-for-a-byte-array-move
https://stackoverflow.com/questions/43343231/enhanced-rep-movsb-for-memcpy
https://github.com/dotnet/runtime/issues/6464
https://github.com/dotnet/runtime/issues/10824
https://github.com/golang/go/issues/14630

**Comment by huoyaoyuan** [comment]
> See the Intel Manual on Optimization, section 3.7.6 Enhanced REP MOVSB and STOSB operation (ERMSB) http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf (applies to processors which did not yet have FSRM):

> startup cost is 35 cycles;
both the source and destination addresses have to be aligned to a 16-Byte boundary;
the source region should not overlap with the destination region;
the length has to be a multiple of 64 to produce higher performance;

It looks unsuitable for locals init, which is typically small. For memmove it may be valuable, but we still need to consider GC.

**Comment by tannergooding** [comment]
We also typically don't do micro-architecture specific optimizations. It massively increases the complexity of our testbed for often little benefit.

We do occasionally do instruction set based lightup, as that can at least be trivially toggled and tested as part of an outerloop CI validation.

**Comment by JulieLeeMSFT** [comment]
> We also typically don't do micro-architecture specific optimizations. It massively increases the complexity of our testbed for often little benefit.
> 
> We do occasionally do instruction set based lightup, as that can at least be trivially toggled and tested as part of an outerloop CI validation.

@simplejackcoder, closing this issue based on huoyaoyuan's and tannergooding's comment. Please reopen it if you think we need further assistance.
