### ISSUE TITLE
System.Text.Json SourceGenerator behaves oddly if context is generic

### ISSUE THREAD

**Issue by canton7** [dotnet/runtime#66880]
### Description

If the `JsonSerializerContext` given to the System.Text.Json source generator is generic, the source generator generates some very odd code.

### Reproduction Steps

Create a .NET 6 project containing the following, and look at the source generated by the System.Text.Json source generator:

```cs
public class Model
{
}

[JsonSerializable(typeof(Model))]
internal partial class MyJsonContext<T> : JsonSerializerContext
{
}
```

### Expected behavior

The source generator either produces a diagnostic saying that generic contexts aren't supported (and does not attempt to generate source), or the source generated is valid C#.

### Actual behavior

It's a mix of things.

The class declaration itself is non-generic:

```cs
internal partial class MyJsonContext
```

The default context is sort-of generic, but is confused about what a generic type parameter is:

```cs
        private static global::MyJsonContext<global::MyJsonContext.T>? s_defaultContext;
        public static global::MyJsonContext<global::MyJsonContext.T> Default => s_defaultContext ??= new global::MyJsonContext<global::MyJsonContext.T>(new global::System.Text.Json.JsonSerializerOptions(s_defaultOptions));
```

The constructors are invalid C#:

```cs
        public MyJsonContext`1() : base(null)
        {
        }
        
        public MyJsonContext`1(global::System.Text.Json.JsonSerializerOptions options) : base(options)
        {
        }
```

### Regression?

No

### Known Workarounds

None

### Configuration

.NET 6, Visual Studio 17.2.0 Preview 1.0.

**Comment by layomia** [comment]
This is a bug since the generator is produced invalid syntax. Do you have any scenario/reason for making your context type generic?

**Comment by layomia** [comment]
Same underlying issue as https://github.com/dotnet/runtime/issues/62762.
