### ISSUE TITLE
Please release a new stable 6.x version of the System.Runtime.Experimental package

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#66884]
The .NET 6.0.101 SDK broke the `System.Runtime.Experimental` package (#62840) then a fix was merged (#63599) but as of today, the latest sable version on NuGet is still the broken [6.0.0 version](https://www.nuget.org/packages/System.Runtime.Experimental/6.0.0).

Could you please release a new (6.0.1) **stable** version on NuGet?

/cc @safern

PS: I would have commented on #63599 but @msftbot is now locking issues pretty aggressively.

**Comment by MagicAndre1981** [comment]
The fix is scheduled for [6.0.4 release](https://github.com/dotnet/runtime/milestone/96?closed=1), so you need to wait for april updates. 

![image](https://user-images.githubusercontent.com/8274816/159122826-bf6b0457-8e61-4e0c-81d1-ce8a37011f17.png)

**Comment by martincostello** [comment]
There was a 6.0.1, but it was delisted as it was broken. We should get the fixed 6.0.2(?) package in .NET 6.0.4 next month.

**Comment by 0xced** [comment]
Thanks, I missed #65018 and #65733. Looking forward to the next release!

**Comment by MagicAndre1981** [comment]
check todays updates, here there is an updated package:

https://www.nuget.org/packages/System.Runtime.Experimental/6.0.2
