### ISSUE TITLE
Is it possible to get a volatile reference of an ImmutableArray<T>?

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#66896]
I am using a [`ImmutableArray<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1) struct in a multithreaded scenario, where one thread is updating the array through the [`ImmutableInterlocked.Update`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked.update) method, and another thread enumerates repeatedly the array in a loop, and process its elements. I am not seeing though any way to obtain a volatile reference to the `ImmutableArray<T>`. Neither the `ImmutableArray<T>` struct nor the `ImmutableInterlocked` class seems to offer an API for this, nor an `ImmutableVolatile` class exists in the `System.Collections.Immutable` namespace. Am I missing something, or this functionality is just not available?

Currently I am using the [`ImmutableInterlocked.InterlockedCompareExchange`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked.interlockedcompareexchange) as a workaround:

```C#
static ImmutableArray<T> VolatileRead<T>(ref ImmutableArray<T> source)
{
    return ImmutableInterlocked.InterlockedCompareExchange(ref source,
        ImmutableArray<T>.Empty, ImmutableArray<T>.Empty);
}
```

...but AFAIK this imposes a full fence, so it's not as efficient as a `Volatile.Read` would be.

**Comment by Tornhoof** [comment]
This sounds like some kind of pub-sub queue, are you sure there aren't better data structures for that, like System.Threading.Channels or similar?

**Comment by theodorzoulias** [comment]
@Tornhoof if you are interested for the actual scenario where I am using the `ImmutableArray<T>`, it's [here](https://stackoverflow.com/questions/61540896/factory-for-iasyncenumerable-or-iasyncenumerator/62098158#62098158 "Factory for IAsyncEnumerable or IAsyncEnumerator"). The `T` in my case is actually a `Channel<T>`. But the specific scenario isn't really important. What I would like to know is if a way to obtain a volatile reference to a `ImmutableArray<T>` exists. The existence of APIs that allow to replace atomically an `ImmutableArray<T>` in a lock-free fashion indicates that a `VolatileRead` API should exist somewhere, and I just can't find it.

**Comment by quixoticaxis** [comment]
Could you elaborate on what exactly do you mean by _volatile reference_?
`Volatile.Read` will give you a reference and inject appropriate barriers to uphold its gurantees.

**Comment by quixoticaxis** [comment]
> The existence of APIs that allow to replace atomically an `ImmutableArray<T>` in a lock-free fashion indicates that a `VolatileRead` API should exist somewhere, and I just can't find it.
@theodorzoulias , maybe not, it seems that it utilized `Interlocked` over non public `array` member ([source](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L211)).

**Comment by theodorzoulias** [comment]
@quixoticaxis it looks like an oversight to me. I might have to create an API proposal for including this functionality somewhere. Do you think that the `ImmutableInterlocked` is the correct place for a static `VolatileRead(ref ImmutableArray<T> location)` method?

**Comment by quixoticaxis** [comment]
@theodorzoulias, I'm not certain the API is needed in a first place. My reasoning can be defined by the following points:

1. The `ImmutableArray<T>` is a struct, and it is not mutated.
2. `Volatile.Read` guarantees that CPU does not reorder instruction from "after" to "before". Actually, everything else is, AFAIK, the side-effect of the current implementation.
3. `Volatile.Read` works through casting to `private struct VolatileObject { public volatile object? Value; }`, and `volatile` also is about re-ordering, not anything else.
4. As far as I understand and know, .Net does not provide any API that is guaranteed (per documentation) to force cross CPU synchronization, apart from comparatively slow `Interlocked.MemoryBarrierProcessWide`.

My point is: either use `volatile` field, or, which even better in your case (or, at least, how I grasped the scenario described at StackOverflow), use `ImmutableList<T>` that 1) is a class and 2) is implemented by AVL tree (while `ImmutableArray<T>` is array that is being copied again, and again, and again).

**Comment by quixoticaxis** [comment]
@theodorzoulias , I updated my comment above.

**Comment by theodorzoulias** [comment]
@quixoticaxis my scenario (rare updates and frequent enumerations) [dictates](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1#remarks) that I should use an `ImmutableArray<T>`, and not an `ImmutableList<T>`. Are you suggesting that I should take no precaution before starting a new enumeration of the array, that might have been updated by another thread during the previous enumeration? How am I protected from the possibility that the enumerating thread will just enumerate a locally cached version of the array all the time, instead of enumerating the latest version of the array? I think that issuing an acquire fence before starting an enumeration is the responsible thing to do. Even if my program works correctly in my PC, it might not work correctly in a PC with a different CPU architecture ([reference](https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/december/csharp-the-csharp-memory-model-in-theory-and-practice "The C# Memory Model in Theory and Practice")). I don't want to take this risk.

**Comment by quixoticaxis** [comment]
> @quixoticaxis my scenario (rare updates and frequent enumerations) [dictates](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1#remarks) that I should use an `ImmutableArray<T>`, and not an `ImmutableList<T>`. Are you suggesting that I should take no precaution before starting a new enumeration of the array, that might have been updated by another thread during the previous enumeration? How am I protected from the possibility that the enumerating thread will just enumerate a locally cached version of the array all the time, instead of enumerating the latest version of the array? I think that issuing an acquire fence before starting an enumeration is the responsible thing to do. Even if my program works correctly in my PC, it might not work correctly in a PC with a different CPU architecture ([reference](https://docs.microsoft.com/en-us/archive/msdn-magazine/2012/december/csharp-the-csharp-memory-model-in-theory-and-practice "The C# Memory Model in Theory and Practice")). I don't want to take this risk.

I'm saying you still don't _guarantee_ (as per documentaion) anything with a fence.
As far as I understand the nature of the code, you may simply ignore the possible issues as the field would be refreshed anyway, while you also have no guarantees that you're enumerating the latest version, so why bother?

**Comment by theodorzoulias** [comment]
@quixoticaxis are you arguing that the [`Volatile.Read`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile.read) API is useless in general, or that it's useless only regarding the `ImmutableArray<T>` type?

**Comment by theodorzoulias** [comment]
@quixoticaxis please take a look at [the current implementation](https://github.com/dotnet/runtime/blob/fa1f2834dace0a34c53f1e1039b5af640fe51576/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableInterlocked.cs#L120) of the `ImmutableInterlocked.Update` method:

```C#
public static bool Update<T>(ref ImmutableArray<T> location, Func<ImmutableArray<T>, ImmutableArray<T>> transformer)
{
    Requires.NotNull(transformer, nameof(transformer));

    bool successful;
    T[]? oldArray = Volatile.Read(ref Unsafe.AsRef(in location.array));
    do
    {
        ImmutableArray<T> newImmutableArray = transformer(new ImmutableArray<T>(oldArray));
        if (ReferenceEquals(oldArray, newImmutableArray.array))
        {
            // No change was actually required.
            return false;
        }

        T[]? interlockedResult = Interlocked.CompareExchange(ref Unsafe.AsRef(in location.array), newImmutableArray.array, oldArray);
        successful = ReferenceEquals(oldArray, interlockedResult);
        oldArray = interlockedResult; // we already have a volatile read that we can reuse for the next loop
    }
    while (!successful);

    return true;
}
```

Do you think that the `Volatile.Read` in the line 125 is correct or incorrect? If you think that it's correct, why are you opposed at exposing an API that would allow me to do exactly what the author of this method is allowed to do?

**Comment by quixoticaxis** [comment]
> @quixoticaxis are you arguing that the [`Volatile.Read`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.volatile.read) API is useless in general, or that it's useless only regarding the `ImmutableArray<T>` type?

Neither.
I'm implying that .Net ecosystem is not too keen on either providing strict guarantees, or making the multithreaded code portable.
`Volatile.Read` is documented to forbid reordering, it's not useless, but it's not widely useful too. For example, **theoretically** I can indefinitely work without instruction being re-ordered, but forever using the cached value and never fetching from external memory.

My point is, there is no need to provide another API that would be useful only because of undocumented side-effects.

**Comment by quixoticaxis** [comment]
> Do you think that the `Volatile.Read` in the line 125 is correct or incorrect? If you think that it's correct, why are you opposed at exposing an API that would allow me to do exactly what the author of this method is allowed to do?

I'd say it just works, but, AFAIU, the it works because of undocumented side-effects of implementation.

**Comment by theodorzoulias** [comment]
> I'd say it just works, but, AFAIU, it works based on undocumented side-effects of implementation.

@quixoticaxis what do you mean with _"it just works"_? What bad might happen if we replace the line 125:

```C#
T[]? oldArray = Volatile.Read(ref Unsafe.AsRef(in location.array));
```

...with this line?

```C#
T[]? oldArray = location.array;
```

Why bother putting the `Volatile.Read` there? If you think that it's wise to use it in this case, then why I shouldn't bother putting it in my own similar code?

Please be aware that, in all honesty, trying to convince me to throw all caution in the wind, and write my multithreaded code like it's single-threaded, will be a lengthy process with uncertain outcome and with little return for your investment. Tip: I am non an expert in memory models, and I have no desire to become one. It might be cheaper to just provide me with this API so that I can feel confident for the correctness of my code, even if this confidence is a cargo cult based on a flawed understanding of what the `Volatile.Read` actually does. Because otherwise (i.e. no API and not convinced) I will do it anyway, using more complex and less efficient code.

**Comment by quixoticaxis** [comment]
> > I'd say it just works, but, AFAIU, it works based on undocumented side-effects of implementation.
> 
> @quixoticaxis what do you mean with _"it just works"_? What bad might happen if we replace the line 125:
> 
> ```C#
> T[]? oldArray = Volatile.Read(ref Unsafe.AsRef(in location.array));
> ```
> ...with this line?
> 
> ```C#
> T[]? oldArray = location.array;
> ```
> 
> Why bother putting the `Volatile.Read` there? If you think that it's wise to use it in this case, then why I shouldn't bother putting it in my own similar code?

My wild guess is that the implementation guarantees the atomicity of the read on all supported architectures and the call is guaranteed per documentation to be served from memory on uniprocessor system. Btw I'm not even certain that the current code is correct for multiprocessor setup.

> Please be aware that, in all honesty, trying to convince me to throw all caution in the wind, and write my multithreaded code like it's single-threaded, will be a lengthy process with uncertain outcome and with little return for your investment. Tip: I am non an expert in memory models, and I have no desire to become one. It might be cheaper to just provide me with this API so that I can feel confident for the correctness of my code, even if this confidence is a cargo cult based on a flawed understanding of what the `Volatile.Read` actually does. Because otherwise (i.e. no API and not convinced) I will do it anyway, using more complex and less efficient code.

Nah, I'm not trying to push you towards the broken code, I'm trying to explain my point, which is
"I'm also not an expert, but I understand that using volatile is difficult, so why bother? Use reference type instead, us `lock` or `AsyncLock` by @stephencleary instead, the API you propose seems undefinable to me, because even the existing `Volatile.Read` does not provide the guarantees you want it to, namely, for example, it does not guarantee that you read the latest value on multiprocessor system".

**Comment by kevingosse** [comment]
> for example, it does not guarantee that you read the latest value on multiprocessor system".

In this case it's not about getting a fresh value, but about getting a value that will eventually be fresh. Without volatile, the compiler is allowed to cache the value in a register and never check the memory again. I faced a similar issue in the past with `WebClient.IsBusy`: https://github.com/dotnet/runtime/issues/42013

There might be some rules that prevent this situation from happening with `ImmutableArray` but I'm not aware of them.

**Comment by quixoticaxis** [comment]
> > for example, it does not guarantee that you read the latest value on multiprocessor system
> 
> In this case it's not about getting a fresh value, but about getting a value that will eventually be fresh. Without volatile, the compiler is allowed to cache the value in a register and never check the memory again. I faced a similar issue in the past with `WebClient.IsBusy`: https://github.com/dotnet/runtime/issues/42013
> 
> There might be some rules that prevent this situation from happening with `ImmutableArray` but I'm not aware of them.
> 
> 
> 

@kevingosse , but `Interlocked.CompareExchange` in the body of the loop would prevent it anyway, won't it?

**Comment by theodorzoulias** [comment]
> @kevingosse , but `Interlocked.CompareExchange` in the body of the loop would prevent it anyway, won't it?

@quixoticaxis the documentation of the [`Interlocked.CompareExchange`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange) says nothing about preventing the compiler from caching values in registers, so if it does it's an undocumented side-effect. And, according to [this recent comment](https://github.com/dotnet/runtime/issues/66896#issuecomment-1073342108), you are not a fan of those.

**Comment by quixoticaxis** [comment]
> > @kevingosse , but `Interlocked.CompareExchange` in the body of the loop would prevent it anyway, won't it?
> 
> @quixoticaxis the documentation of the [`Interlocked.CompareExchange`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange) says nothing about preventing the compiler from caching values in registers, so if it does it's an undocumented side-effect. And, according to [this recent comment](https://github.com/dotnet/runtime/issues/66896#issuecomment-1073342108), you are not a fan of those.

Dunno, what you mean, I'm simply trying to understand better. `Volatile.Read` does not mention it either, but I know it has such effect.

**Comment by En3Tho** [comment]
Can't you just put your array to a class and change/read that instead. It will introduce an indirection thought but will achieve what you want.

Or you might use an array of ImmutableArrays I guess.. To make use of ref mechanics properly and swap structs inside that array

Third way is to use your own wrapper type which will mimic an immutable array but will explicitly have ChangeBuffer method and will guarantee proper read of a current value.

**Comment by Clockwork-Muse** [comment]
> says nothing about preventing the compiler from caching values in registers, so if it does it's an undocumented side-effect.

If the compiler was caching the results of arbitrary method calls, there would be a lot more problems.  Rather, what the compiler is doing is caching operations on fields that appear to be under the control of a single thread (because doing cross-thread checks are really expensive and not usually required); usually, this requires it to be a property or inline-able method.
None of the `Interlocked` methods (properly implemented) can allow this sort of caching to take place, because doing so would make them violate their contracts with respect to cross-thread communication.  Consider the case of `Interlocked.Increment(...)`, which would be broken if two concurrent calls returned the same value (even disregarding the normal potential threading issues).

The use of `volatile` is, in most cases, a mistake.

For your SO question, you'd probably be better off just using regular `lock` and normal `List<Channel<T>>`, since it's unlikely that you'll be creating that many channels (and appear to only have a single writer, so your contention is likely to be near zero).  If you want to get fancy I'd go for reader/writer locks.

**Comment by theodorzoulias** [comment]
> Can't you just put your array to a class and change/read that instead. It will introduce an indirection thought but will achieve what you want.

@En3Tho yes, wrapping my `ImmutableArray<T>` in an immutable small class is also a workaround, apart from the `ImmutableInterlocked.InterlockedCompareExchange`-based workaround that I have already mentioned in my first post. A convenient class for this purpose is the [`Tuple<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.tuple-1). There are two problems though:

1. Complexity.
2. Doubles the garbage created every time the collection is updated with the [`ImmutableInterlocked.Update`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked.update) method.

I think that using this workaround defies all the efforts made be the API designers who decided to make the `ImmutableArray<T>` a value type, and provided us with specialized methods in the [`ImmutableInterlocked`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutableinterlocked) class targeting the `ImmutableArray<T>` type. I don't think that wrapping this collection in a class and using it as a reference type, is what they had in mind.

**Comment by theodorzoulias** [comment]
> For your SO question, you'd probably be better off just using regular `lock` and normal `List<Channel<T>>`, since it's unlikely that you'll be creating that many channels (and appear to only have a single writer, so your contention is likely to be near zero). If you want to get fancy I'd go for reader/writer locks.

@Clockwork-Muse a `List<Channel<T>>` is certainly not an option. Enumerating the collection might take a long time, and I don't want to block any thread that wants to update the collection while another thread is enumerating it. I could use an `ImmutableList<Channel<T>>` with a `lock`, but I am not thrilled by the looks of it:

```C#
ImmutableList<Channel<T>> snapshot;
lock (_locker) snapshot = _channels;
foreach (var channel in snapshot) // ...
```

Apart from looking uninspired, the `lock` AFAIK imposes a full fence, so it's less efficient than the half fence imposed by the `Volatile.Read`.

**Comment by huoyaoyuan** [comment]
The memory layout of `ImmutableArray<T>` is exactly the same with normal array. You can do this with ugly hack:

```csharp
Unsafe.As<T[], ImmutableArray<T>>(Volatile.Read(ref Unsafe.As<ImmutableArray<T>, T[]>(ref source)));
```

**Comment by quixoticaxis** [comment]
@theodorzoulias , AFAIU, your code with `lock` works the same as the code without `lock`, the code from SO with `Volatile.Read`, or the code from SO with `Volatile.Read` removed, unless you're assuming that it would be called in a tight loop and `_channels` accesses would be optimized away, which, considering the context, seems improbable to me.

Anyway, you may be enumerating the stale collection, which is fine, according to you, because you don't want to block addition of new channels.

Given that you're fine with staying behind in time, the naive implementation with a `List<T>` or `T[]` that are brieg fully copied under `lock` on add and simply returned as reference from under `lock` on get would do fine. This implemrntation is guranteed to not be morphed in any unpredictable way by the compilers.

The version with `ImmutableArray<T>` would do the same with, I assume,
 a caveat of possible issues on get which can be solved with a barrier.

**Comment by quixoticaxis** [comment]
@kevingosse , yeah, the case you linked is more obvious in a sense that it's a check in a tight loop.

**Comment by theodorzoulias** [comment]
> The memory layout of `ImmutableArray<T>` is exactly the same with normal array. You can do this with ugly hack:
> 
> ```cs
> Unsafe.As<T[], ImmutableArray<T>>(Volatile.Read(ref Unsafe.As<ImmutableArray<T>, T[]>(ref source)));
> ```

@huoyaoyuan yikes! Thanks for mentioning this workaround, but I don't think that I'll use it. It looks too `Unsafe` to me! 😃

Regarding the question I am asking in the title, the answer I guess is "not directly", correct? The reason I have opened this issue is to learn if a relevant API exists. If not, then my intention is to close this issue, and create an "API suggestion" for the missing API.

**Comment by theodorzoulias** [comment]
> Anyway, you may be enumerating the stale collection, which is fine, according to you, because you don't want to block addition of new channels.

@quixoticaxis no, I don't want to enumerate a stale collection. I think that I made it clear in [this](https://github.com/dotnet/runtime/issues/66896#issuecomment-1073290766) previous comment. That's the whole point of me wanting to put that half fence there, to avoid enumerating the same cached snapshot of the array again and again. Anyway, thanks for trying to help me, but I didn't open this issue with the intention of receiving or offering lessons on low-lock multithreading. I opened it because I couldn't find an API that I was searching, and I wanted to know if this API exists or not.

**Comment by theodorzoulias** [comment]
Apart from the `Unsafe`-based workaround [mentioned](https://github.com/dotnet/runtime/issues/66896#issuecomment-1073826435) by @huoyaoyuan, I didn't got any feedback about the existence of a `VolatileRead` API for the `ImmutableArray<T>` type, so I have to assume that currently (.NET 6) such an API does not exist. I am closing this issue with this conclusion.
