### ISSUE TITLE
PipeReader.ReadAsync and PipeWriter.FlushAsync don't preserve the SynchronizationContext

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#66893]
### Description

Seems like we have a regression or this never worked but the sync context doesn't seem to be preserved when using `PipeReader` or `PipeWriter`.

### Reproduction Steps

```C#
using System.IO.Pipelines;
using System.Text;

var pipe = new Pipe();

async Task WriteInaSecond()
{
    await Task.Delay(1000);
    await pipe.Writer.WriteAsync(Encoding.UTF8.GetBytes("Hello"));
}
_ = WriteInaSecond();

var sc = new SyncContext();
SynchronizationContext.SetSynchronizationContext(sc);


Console.WriteLine($"SC:{SynchronizationContext.Current?.ToString() ?? "null"}");
await pipe.Reader.ReadAsync();
Console.WriteLine($"SC:{SynchronizationContext.Current?.ToString() ?? "null"}");

class SyncContext : SynchronizationContext
{
    public override void Post(SendOrPostCallback d, object? state)
    {
        base.Post(d, state);
    }
}
```

### Expected behavior

It should print:

```
SC:SyncContext
SC:SyncContext
```

### Actual behavior

Instead it prints:

```
SC: SyncContext
SC: null
```

### Regression?

Nope, it seems like this never worked 😄 

### Known Workarounds

Set the sync context to current after every async operation, not very nice.

**Comment by davidfowl** [comment]
Hmm I think I have some bad assumptions about how the sync context is preserved. I see the same behavior for a TaskCompletionSource. Will open this after some investigation.

**Comment by davidfowl** [comment]
@stephentoub or @kouvel Can you help me understand this behavior?

```C#
var sc = new SyncContext();
SynchronizationContext.SetSynchronizationContext(sc);

Console.WriteLine($"SC:{SynchronizationContext.Current?.ToString() ?? "null"}");
await Task.Delay(1000);
Console.WriteLine($"SC:{SynchronizationContext.Current?.ToString() ?? "null"}");
```

Should this print:

```
SC: SyncContext
SC: null
```

If yes, how is the sync context usually preserved across thread hops?? Which component does that? (I thought it was the code in ExecutionContext)

**Comment by stephentoub** [comment]
> Should this print:

Yes

> how is the sync context usually preserved across thread hops??

There's a difference between being stored for use in posting to it and being stored as Current. awaits (on tasks at least) do the former.

> Which component does that?

TaskAwaiter grabs SynchronizationContext.Current (unless ConfigureAwait(false) is used) and then upon await completion invokes the continuation with that SynchronizationContext if there was one.  Calling Post on that SynchronizationContext will cause the delegate to be invoked wherever that SynchronizationContext wants it invoked, and if it wants wherever that is to have SynchronizationContext.Current set to itself (or to whatever), it needs to handle that.

In the olden days of .NET Framework, the waters were muddier.  There were two different ways for capturing an ExecutionContext.  The internal way used by everything in mscorlib (which represented the majority usage of ExecutionContext) had ExecutionContext being completely unrelated to SynchronizationContext.  And that's a good thing.  If for example you did Task.Run(() => M()), with Run capturing the current ExecutionContext and then restoring it to invoke M(), and if ExecutionContext itself captured SynchronizationContext.Current and then restored it as Current for the invocation of M(), that would lead to badness.  Unfortunately, the _public_ ExecutionContext.Capture() method that anything outside of mscorlib used did that badness. In .NET Core, we effectively kept the good version only, with ExecutionContext having nothing to do with SynchronizationContext.

**Comment by davidfowl** [comment]
> There's a difference between being stored for use in posting to it and being stored as Current. 

Right, I'm interested in who sets preserve it as current (if anyone does). When using winforms/wpf etc, is that being set manullly by the Sync context before executing each callback?

**Comment by davidfowl** [comment]
I just looked, seems like each SynchronizationContext does the preservation themselves (by setting current before invoking the continuation). Great. I just need to tweak mine then.
