### ISSUE TITLE
[API Proposal]: TryFindSystemTimeZoneById

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/runtime#66928]
### Background and motivation

The method for finding a timezone by a string, `TimeZoneInfo.FindSystemTimeZoneById`, throws a `TimeZoneNotFoundException` if it can't find one. AFAIK there isn't a non-throwing method in the runtime.

I use a version of the method below to [attempt to find a time zone or fallback to local time](https://github.com/danielchalmers/DesktopClock/blob/7ca9dc977223f1332bc88bd2fd7e3c3a7eb838a5/DesktopClock/SettingsHelper.cs#L11-L12):

```csharp
public static TimeZoneInfo GetTimeZone() =>
DateTimeUtil.TryGetTimeZoneById(Settings.Default.TimeZone, out var timeZoneInfo) ? timeZoneInfo : TimeZoneInfo.Local;
```

This is of course still possible using the current method but it's not as clean IMO.

### API Proposal

```csharp
namespace System
{
    public class TimeZoneInfo
    {
        public static bool TryFindSystemTimeZoneById(string id, out TimeZoneInfo timeZoneInfo)
        {
            try
            {
                timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(id);
                return true;
            }
            catch (TimeZoneNotFoundException)
            {
                timeZoneInfo = null;
                return false;
            }
        }
    }
}
```

### API Usage

```csharp
// Ask user for timezone.
Console.WriteLine("Enter a timezone");
var tz = Console.ReadLine();

// Validate.
if(TimeZoneInfo.TryFindSystemTimeZoneById(tz, out var tzInfo))
    Console.WriteLine("Found timezone");
else
    Console.WriteLine("Invalid timezone");
```

```csharp
// Ask user for timezone.
Console.WriteLine("Enter a timezone");
var tz = Console.ReadLine();

// Try to find timezone or fall back to local time.
var finalTimeZone = TimeZoneInfo.TryFindTimeZoneById(tz, out var tzInfo) ? tzInfo : TimeZoneInfo.Local;
Console.WriteLine("Using " + finalTimeZone.DisplayName);
```

**Comment by pinkfloydx33** [comment]
I implemented the very same workaround this past week. I was surprised there isnt a Try-/non-throwing variant. We accept the TZ name as user-provided input so can't rely on it being valid. The workaround isn't that bad, but it'd be nice to have a way to do a lookup without the exception.

**Comment by tannergooding** [comment]
CC. @tarekgh, could you provide insight into whether this is something we should look at providing?

**Comment by tarekgh** [comment]
@tannergooding this is a nice to have helper method but not necessary blocking any scenario. It is easy to have the apps adding extension method that does that.

**Comment by tannergooding** [comment]
Do you think this is in the right shape for us to mark `api-ready-for-review` then or are there any other concerns with the current proposal?

**Comment by tarekgh** [comment]
The API shape looks good to me.

**Comment by bartonjs** [comment]
Looks good as proposed (ignoring that the body says to do a try/catch).

```C#
namespace System
{
    public class TimeZoneInfo
    {
        public static bool TryFindSystemTimeZoneById(string id, out TimeZoneInfo timeZoneInfo);
    }
}
```
