### ISSUE TITLE
[API Proposal]: Unbox as Span<byte>

### ISSUE THREAD

**Issue by zgabi** [dotnet/runtime#66934]
### Background and motivation

Sometimes the user receives an unmanaged type as an object. It would be good to have a way to access the bytes of the variable.

Similar to 
MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref value, 1));
But when the value is an object containing an unmanaged value.

It could throw the same
Cannot use type 'xxx'. Only value types without pointers or references are supported
exception when the value is not unmanaged.

### API Proposal

```C#
namespace System.Runtime.CompilerServices
{
    public static class Unsafe
    {
        public static Span<byte> UnboxAsSpan(object box) { get; }
    }
}
```

### API Usage

```C#
var span = Unsafe.UnboxAsSpan((object)123);

// Getting the values out
Console.WriteLine(string.Join(" ", span.ToArray().Select(x => x.ToString("X2"))));
```

**Comment by Joe4evr** [comment]
Is this not something you can do yourself by inserting [`Unsafe.Unbox<T>()`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.unbox) in the chain you already used as an example?
```cs
MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.Unbox<int>(value), 1));
```

**Comment by zgabi** [comment]
No, because the T can be anytinhg...
Of cource I could write a huge switch for all types.
But it is impossible for every structs....

**Comment by zgabi** [comment]
The only way I found to make it is:

```
interface IWrapper
{
    public Span<byte> AsSpan { get; }
}

struct Wrapper<T> : IWrapper where T : unmanaged
{
    public int Size => sizeof(T);
    
    public T Value;

    public Span<byte> AsSpan => MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Value, 1));

    public Wrapper(T value)
    {
        Value = value;
    }
}

private static byte[] GetValueTypeBytes(object valueType)
{
    var type = typeof(Wrapper<>).MakeGenericType(valueType.GetType());
    var instance = (IWrapper)Activator.CreateInstance(type, valueType);
    return instance.AsSpan.ToArray();
}
```

But that's not so efficient.

**Comment by huoyaoyuan** [comment]
So, are you inspecting bytes of a boxed struct as span, without knowing it's type?
This is pretty unsafe. I'm not sure if type system has any guard to this.

**Comment by omariom** [comment]
It will create a GC hole.

**Comment by huoyaoyuan** [comment]
> It will create a GC hole.

It could be safe if the helper refuses to unbox if it contains reference. Just a check to type information.

**Comment by stephentoub** [comment]
> . It would be good to have a way to access the bytes of the variable.

Why? What exactly would you do with these bytes? Your example just shows creating a string from them (and since you mentioned efficiency, very inefficiently)... for what purpose?

**Comment by zgabi** [comment]
@huoyaoyuan  I know the type, beucase I can get it with value.GetType() However it can be a lot of different types.

@omariom It is totally safe, since it should work only for unmanaged types... as the Marshal.CreateSpan.... It also throws and exception when T type is invalid.

@stephentoub For serialization purposes when I get the value from a serializer (when it can't serialize a type) as an object. That could be also improved since there is a boxing, but at least not reflection.

**Comment by stephentoub** [comment]
> For serialization purposes when I get the value from a serializer (when it can't serialize a type) as an object

You mean you'd want to use this with the object returned to you from a deserialization operation?  What do you then do with the bytes?

**Comment by zgabi** [comment]
I want to use the bytes to add to a stream during the serialization.

Exactly I want to serialize NHibernate.Cache.Entry.CacheEntry object which contains an object[] DisassembledState property.
I'm not sure, but as far as I see It can contain unmanaged types (int, short, DateTime, etc), string and probably other known entity objects.

Of course it can be serialized in serveral ways, but I'd like to use Protobuf serialization. My entites are already protobuf serializable. I also created a surrogate for CacheKey and CacheEntry.

I already solved it with Marshalling, but as you know it does not work with non blittable types, like DateTime... (and for bool it is different, however it is not a problem for me). So DateTime handling needs a special case.

As far as I see I'm not the only one who wants to convert a struct to byte[]:
https://stackoverflow.com/questions/3278827/how-to-convert-a-structure-to-a-byte-array-in-c

As far as I found, currently the best way is using Marshal.* functions.

Since unmanaged variables are just simple bytes in the memory, and it is already possible to get them when they are not boxed, I don't understand why not possible easily when it is boxed. And it is possible as I wrote with reflection, but that is slow. So nothing new would be added, just a faster way to do the same.

**Comment by Perksey** [comment]
Note, a possible API proposal for this could be:
```cs
namespace System.Runtime.CompilerServices;
public static unsafe partial class Unsafe
{
    public static Span<byte> AsBytes<T>(ref T value) where T: unmanaged;
}
```

**Comment by zgabi** [comment]
@Perksey: That is alrey possible with MemoryMarshal, then why to put to the Unsafe class... maybe you can propse it to add to MemoryMarshal class, but it does not help on the original issue.

**Comment by Perksey** [comment]
> As I wrote I do not want to convert any object to byte[]... I understand that it is dangeroups.. this is why I wrote that this call should throw an exception when the given parameter is not an unmanaged value. Similar to other existing framewotk methods.

I feel like
```cs
MemoryMarshal.Cast<MyStruct, byte>(MemoryMarshal.CreateSpan(ref Unsafe.Unbox<MyStruct>(myBox), 1));
```

Should just continue to be the best option. Adding an API for this, in my opinion, at best wouldn't add any real value and at worst could be extremely dangerous.

**Comment by zgabi** [comment]
@Perksey You are writing the same as @Joe4evr ... please read the whole thread. MyStruct is only one struct It does not work with any (unmanaged) struct / unmanaged type.
I think currently it is not possible with Unsafe and *Marshal classes... only with reflection.

**Comment by Joe4evr** [comment]
@zgabi If your only concern is using this with unmanaged structs, then write a generic helper method that does the thing we've told you with `where T : unmanaged`.

**Comment by DrkWzrd** [comment]
In advance. I'm not entirely sure of what I'm going to write.

I think the problem here is when you box an unmanaged item, it's no more "an unmanaged item". It becomes "a managed object" (no pun intented) and the GC can do with it what it wants. And the representation can vary. You cannot have the c/c++ hacky-rawbytes mindset of "gimme a address/pointer and a length", because the GC can move the object, the GC can delete de object after you get the Span. And the Span (literally an address and a length) will become invalid. Even the GC can write sensible information in that area.

That's why we have to Pin in memory sometimes, avoiding the GC do her magic tricks.

Isn't it?

**Comment by zgabi** [comment]
I don't know this, but there is already an Unsafe.Unbox<T>(object box) method.
So similar is needed to get the Span<byte>.

**Comment by zgabi** [comment]
:(
