### ISSUE TITLE
Can you please make the versioning story consistent before it's too late?

### ISSUE THREAD

**Issue by enyim** [dotnet/runtime#6693]
So, .NET Core 1.0.1 is released, but some parts of it are called 1.0.4

It is the same as in the early .NET versions where .NET vs CLR were differently versioned (and confusing people left and right).

It'd be much friendlier to have everything the same version.

**Comment by stephentoub** [comment]
This design discussion is old and hasn't progressed in three years.  Thanks. Closing.
