### ISSUE TITLE
Cannot get Total CPU Usage or Idle with System.Diagnostics.Process.GetProcesses

### ISSUE THREAD

**Issue by mwmccallum** [dotnet/runtime#66942]
### Description

We are unable to get either Total CPU Usage or Idle CPU Usage to determine the overall CPU Usage.

`Process.GetProcessById (0).TotalProcessorTime`
OR
`Process.GetProcesses ().Sum ( a => a.TotalProcessorTime.TotalMilliseconds )`

PID 0 would give overall idle time for system, which could be subtracted from 100. Sum of Get Processes could yield overall CPU Usage. 

Both of these throw "Access is Denied" error. 

There should be a fairly easy way to get total CPU Usage of the system. We use it as part of our process management, to test if there is enough resources to shell another process.

In previous framework, System.Diagnostics.PerformanceCounter provided access to quickly determine this information. This is not supported on Linux systems.

I have done an extensive amount of research and cannot find an alternative to get overall CPU Usage from within core. The only Linux alternatives I have seen is to shell a TOP command and parse out the CPU usage.

There should be a way within the core framework to get this same information.

Thanks, Mike

### Reproduction Steps

`Process.GetProcessById (0).TotalProcessorTime`
OR
`Process.GetProcesses ().Sum ( a => a.TotalProcessorTime.TotalMilliseconds )`

### Expected behavior

Return either Total CPU Idle or Total CPU Usage

### Actual behavior

Access is Denied

### Regression?

Based on research, `Process.GetProcessById (0).TotalProcessorTime` worked in Core 1.1.

### Known Workarounds

Detect OS Level, on Unix run Top command to get CPU Usage and parse it.

### Configuration

.Net 6 Windows and Linux.

**Comment by Jozkee** [comment]
With the proper permissions, you can still get the sum of all processes excluding System Idle Process.
```
Process.GetProcesses().Where(a => a.Id != 0).Sum(a => a.TotalProcessorTime.TotalMilliseconds);
```

Isn't that what you need?

**Comment by Jozkee** [comment]
> Based on research, Process.GetProcessById (0).TotalProcessorTime worked in Core 1.1.

I think you are referring [this post](https://social.msdn.microsoft.com/Forums/vstudio/en-US/48757ff0-831d-4713-9013-d4e4d9ae0d9a/access-denied-when-reading-the-totalprocessortime-of-the-idleprocess?forum=csharpgeneral), which is referring to .Net Framework 1.1, not core, so this isn't really a regression from core 1.1. Correct me if I'm wrong.

**Comment by mwmccallum** [comment]
Jozkee, the call you suggested does return a value without any error. I thought when I previously tested through each process in a loop it there were many that threw errors as Access Denied. Now it appears can see all process TotalProcessorTime if I do the same loop again. Not sure if something changed in the most recent updates to VS or Core.

I will need to review the process to calc the CPU as I am seeing about 1/2 of what Task Manager shows, with a 1 second delay between measurements. 

In regards the the regression, I had found several articles about it changing from 1.x Core to 2.x Core. It was a while ago, and I do not have the references saved. Using ID 0 would give the answer directly with 100 - value without aggregating all of the processes which I would think would be a better process.

Thanks, Mike

**Comment by danmoseley** [comment]
Is ID 0 the idle time on Mac/Linux also?
