### ISSUE TITLE
Alternative option to Thread.Abort()

### ISSUE THREAD

**Issue by emadathil** [dotnet/runtime#66943]
Hi,

We are in the process of migrating our project from .Net framework 4.5 to .Net 6.0.
We are using Thread.Abort() functionality to forcefully end operations that run on for too long. Though this approach is not  approved by many developers, it has served us and our requirements seamlessly for years. 
Since Thread.Abort() is not supported in .Net 6, we are looking at other options to replace it. 
So far, all research points towards using CancellationToken, but this is currently not feasible for our use since it will require a lot of code changes and restructuring.

Is there an alternative solution (other than using CancellationToken), that would help stop the execution of a task from the Main thread?

**Comment by jkotas** [comment]
There is no direct replacement for Thread.Abort in .NET Core. `CancellationToken` is the best alternative.

**Comment by teo-tsirpanis** [comment]
Another option if you need to immediately terminate a computation without rewriting it to use `CancellationToken`s, is to run it in an external process and simply kill it if it's taking too long.
