### ISSUE TITLE
`System.Reflection.Metadata` cannot parse an assembly created by `ILASM`

### ISSUE THREAD

**Issue by kennykerr** [dotnet/runtime#66957]
### Description

Originally reported here: https://github.com/icsharpcode/ILSpy/issues/2657

Apparently `ILSpy` uses `System.Reflection.Metadata` which then fails to open an assembly created with `ILASM`. 

Other parsers like `ILDASM` don't have this problem. 

### Reproduction Steps

Given a simple source file:

```
D:\> type min.il
.class interface public abstract windowsruntime Windows.Foundation.IStringable
{
    .method public hidebysig newslot abstract virtual instance string ToString()
    {
    }
}
```

Run the following command (this produces a valid WinRT winmd):

```
D:\> ilasm min.il /MDV="WindowsRuntime 1.2" /dll /output=min.winmd /quiet
```

ILSpy then fails to open the resulting assembly with the following error:

```
// This file does not contain a managed assembly.

System.BadImageFormatException: Missing mscorlib reference in AssemblyRef table.
   at ICSharpCode.ILSpy.LoadedAssembly.<LoadAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ICSharpCode.ILSpy.TreeNodes.AssemblyTreeNode.Decompile(Language language, ITextOutput output, DecompilationOptions options)
```

It works if I manually add the `AssemblyRef` table but it would be great if this wasn't a hard requirement. Other parsers like `ILDASM` don't require the `AssemblyRef` table.

### Expected behavior

I would expect it to support assemblies created with `ILASM`. 

### Actual behavior

It fails to load.

### Known Workarounds

Use a different parser.

**Comment by danmoseley** [comment]
I don't have context, but the assumption is stated here.
https://github.com/dotnet/runtime/blob/baffb7107f4f2b11e7ff40859b2c3f4782ada791/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs#L21

**Comment by kennykerr** [comment]
FYI @siegfriedpammer

**Comment by jkotas** [comment]
In general, ilasm does not produce valid .winmd files. It does not support [TypeRef redirection](https://docs.microsoft.com/en-us/uwp/winrt-cref/winmd-files#typedef-redirection) that is required for projections to work correctly.

**Comment by siegfriedpammer** [comment]
Thanks @danmoseley, so according to https://github.com/dotnet/runtime/blob/baffb7107f4f2b11e7ff40859b2c3f4782ada791/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.cs#L21 winmd files without a reference to mscorlib are invalid, so displaying an error message is a valid option, right?

Thanks @MichalStrehovsky, yeah I figured that out while testing. Currently we have an option in the decompiler (and ILSpy), so the user can decide whether they want projections applied or not. However, I think it would make sense to automatically set the option to true for winmd files in our scenario? The reason I am asking is that I have not really an idea of what the consequences would be (and if they would be desirable).

Is "looking at a winmd *without* projections applied" even a valid use case/useful? Would be interested in everyone's thoughts on this. Thank you!

@kennykerr is the global setting in ILSpy (in Decompiler Settings > Other) enough for you?

Thanks @jkotas, so I guess it would be OK if ILSpy cannot make sense of the binary and just displays error messages.

**Comment by jkotas** [comment]
The projections hardcoded in System.Reflection.Metadata match .NET Framework 4. Newer .winmd files assume more projections that are not covered by System.Reflection.Metadata. The projections for newer .winmd files are implemented by https://github.com/microsoft/CsWinRT. System.Reflection.Metadata is not going to be updated with them. It means that looking at these newer .winmd files without System.Reflection.Metadata projections makes more sense than looking at them with System.Reflection.Metadata projections.

**Comment by kennykerr** [comment]
> It does not support [TypeRef redirection](https://docs.microsoft.com/en-us/uwp/winrt-cref/winmd-files#typedef-redirection) that is required for projections to work correctly.

This is only used by the old .NET projection - newer projections (C#/WinRT, C++/WinRT, Rust, JS) don't rely on this redirection at all.
