### ISSUE TITLE
No warning when trimming an app with built-in COM enabled

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#66975]
### Description

Built-in COM support is known to be unsafe for trimming and is disabled by default when trimming. However, trimming an app that has built-in COM explicitly enabled (`BuiltInComInteropSupport=true`) does not produce a warning.

@LakshanF and @vitek-karas have both indicated that the intent here is to show a warning if a user enables built-in COM and trims their application - even without the application directly calling a COM API that is marked as unsafe for trimming. This is similar to what we do if a user explicitly enables native hosting in general or C++/CLI activation.

From @vitek-karas:

> We can discuss where the warning should come from, but I think I should get one for two reasons:
> - We know that we were not able to plug all the wholes through which one can get to COM in the runtime, so even though if I call some COM specific API directly I will get a warning, if I don’t do that, it doesn’t make my app safe – there are still ways to get to COM which won’t warn on their own.
> - The native COM hosting APIs are also enabled – and these are as dangerous any anything else in COM.

### Reproduction Steps

1. `dotnet new console`
2. Enable both trimming and built-in COM:
    ```
    <PublishTrimmed>true</PublishTrimmed>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    ```
3. `dotnet publish --self-contained`

### Expected behavior

Warning indicating that built-in COM support is not trim-safe with a link to additional documentation. 

### Actual behavior

No warning.

### Configuration

Windows
.NET SDK 7.0.100-preview.2.22153.17
Microsoft.NETCore.App 7.0.0-preview.2.22152.2

### Other information

Related:
https://github.com/dotnet/runtime/pull/52109#issue-872684477
https://github.com/dotnet/runtime/issues/52818
https://github.com/dotnet/runtime/pull/66486#discussion_r827486307

**Comment by agocke** [comment]
I think we need a little more design work here -- would it be a new warning? What would its location be?

**Comment by vitek-karas** [comment]
I think it should be `IL2026` (RUC) which we use elsewhere for similar purposes. The origin doesn't really matter if the message is descriptive. We have similar already for native hosting APIs - the origin is "Weird" (private code in CoreLib), but the message is pretty clear.

**Comment by elinor-fung** [comment]
I'll look at updating so that this has a similar experience to native hosting and C++/CLI.
