### ISSUE TITLE
Comment and implementation mismatch in impTypeIsAssignable

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#67026]
Looks like the second pattern mentioned at: https://github.com/dotnet/runtime/blob/c5d40c9e703fd257db1b26ef4fd1399bbae73ab0/src/coreclr/jit/importer.cpp#L4849-L4856 does not take advantage of the const optimization.

```c#
public class A { }

public class B
{
    bool M1() => typeof(B).IsAssignableFrom(typeof(A));
    bool M2() => GetType().IsAssignableFrom(typeof(A));
}
```
codegen with .NET 6 looks like:
```asm
B.M1()
    xor eax, eax
    ret

B.M2()
    push esi
    call System.Object.GetType()
    mov esi, eax
    mov ecx, 0x2327c6c0
    call 0x0f4837c0
    mov edx, eax
    mov ecx, esi
    call dword ptr [0x5f67f94]
    pop esi
    ret
```

Also, when type is declared separately (in a local scope), while this gets optimized:
```c#
    bool M3()
    {
        Type b = typeof(B);
        return b.IsAssignableFrom(typeof(A));
    }
```
this doesn't:
```c#
    bool M4()
    {
        Type b = typeof(B);
        Foo();
        return b.IsAssignableFrom(typeof(A));
    }

    bool Foo() => true;
```

**Comment by EgorBo** [comment]
Thanks!
I made a quick fix but it didn't find any diffs in the repo so I'm leaving this as up-for-grabs (my fix needs more work)

**Comment by am11** [comment]
Thanks. handling GetType() may as well be out of scope here. Should we just delete this line from the comment:
```c++
 //   valueTypeVar.GetType().IsAssignableFrom(typeof(TTFrom)) 
```
(or convert it to a TODO)
since only `typeof().op(typeof())` is handled by the code that follows?

**Comment by jakobbotsch** [comment]
Isn't the comment about variables of value types? Your example is a reference type. If you change it to `struct B` it does get optimized correctly.

**Comment by am11** [comment]
Ah, I see. There is an extra `cmp` with value types' GetType(), but overall it is much better:
```asm
B.M2()
    cmp [ecx], ecx
    xor eax, eax
    ret
```
(I was originally looking at what's left of #4920, looks like it's pretty much covered: IsValueType, IsAssingnableFrom/To etc. are now  defined as intrinsics)

**Comment by EgorBo** [comment]
Well, the original issue still makes sense anyway - even if we don't see the exact type of `obj.GetType()` but we know that it will never be assignable to/from `typeof(B)` we can optimize it.

Because it's not possible to subclass A and somehow implement B

**Comment by jakobbotsch** [comment]
> Well, the original issue still makes sense anyway - even if we don't see the exact type of obj.GetType() but we know that it will never be assignable to/from typeof(B) we can optimize it.

Sure, but from your diffs it seems like these kinds of checks (for two disjoint class hierarchies that we can see at compile time) are very rare.

**Comment by am11** [comment]
While I do not disagree, I believe the supported pattern (with visible `typeof()`s: `typeof(objType).IsAssignableFrom(typeof(anotherObjType))`) is not common either; so the entire impTypeIsAssignable i not that valuable from that metric.
