### ISSUE TITLE
[wasm][debugger] Indexing with expression does not work

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#67029]
Indexing arrays with mathematical expressions e.g.
```
int [] arr = new int[]{ 1, 2, 3 };
arr[1 + 1]; //error
```
error:
`Cannot evaluate '(arr[1 + 1]\n)`

**Comment by teo-tsirpanis** [comment]
I persume you mean in the WASM debugger?

**Comment by teo-tsirpanis** [comment]
> `new arr[]`

Did you mean `new int[]`?

**Comment by radical** [comment]
Additional case to fix - indexing with non-number types. I added a test for this in https://github.com/dotnet/runtime/pull/75524 .
