### ISSUE TITLE
Evaluate JIT_MemCpy with wider copies using AVX2 on hardware that support it

### ISSUE THREAD

**Issue by helloguo** [dotnet/runtime#6702]
JIT_MemCpy on x64 Windows may benefit from using wider copies using YMM registers for certain copy lengths on hardware that support it.  Requires CPU dispatch and may additionally require VZEROUPPER instruction to avoid transition penalties. dotnet/coreclr#7198 

category:cq
theme:helpers
skill-level:expert
cost:medium

**Comment by TIHan** [comment]
Would be interesting to see, though the behavior should remain the same whether or not we want to handle overlapping buffers: https://github.com/dotnet/runtime/issues/6701

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/98623
