### ISSUE TITLE
new Vector<T> for byte, short emits vpbroadcastd thus needs an imul

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#67038]
```c#
public Vector<byte> Bad(byte val) => new Vector<byte>(val);
```
generates on x64 with AVX2 supported:
```asm
C.Bad(Byte)
    L0000: vzeroupper
    L0003: movzx eax, r8b
    L0007: imul eax, 0x1010101
    L000d: vmovd xmm0, eax
    L0011: vpbroadcastd ymm0, xmm0
    L0016: vmovupd [rdx], ymm0
    L001a: mov rax, rdx
    L001d: vzeroupper
    L0020: ret
```
The `imul` isn't needed when instead of `vpbroadcastd` the `vpbroadcastb` is used, as it's done by 
```c#
public Vector256<byte> Good(byte val) => Vector256.Create(val);
```
```asm
C.Good(Byte)
    L0000: vzeroupper
    L0003: movzx eax, r8b
    L0007: vmovd xmm0, eax
    L000b: vpbroadcastb ymm0, xmm0
    L0010: vmovupd [rdx], ymm0
    L0014: mov rax, rdx
    L0017: vzeroupper
    L001a: ret
```

| Type | actual | should be |
| -- | -- | -- |
| `byte`, `sbyte` | `imul` + `vpbroadcastd` | `vpbroadcastb` |
| `ushort`, `short` | `imul` + `vpbroadcastd` | `vpbroadcastw` |
| `uint`, `int` | `vpbroadcastd` | ✔️ |
| `ulong`, `long` | `vpbroadcastq` | ✔️ |

For more see [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGvSasAShwB2GXtxYBhCPgAOvADY8AyjwBu/GEJGNmLSTLkwWASRl8pufkdomJ02fNsZ7jgSwAaABxIwi4MWgAW2FAqADLYwGbulqEiAMxMpAwKDADeNAyFTBnAEBDqDACCughaHCoq0BgwACYMALwAfFU1pDa4dQ1NraFFDAVFxBkAajBgGNAAPMAAns3dAELYLQAUq80MutjqAJQd3VIwAO4Ms/NL+zCdO0eno5MzcwtQpACsSMs1k8GABxMq7R6HY5nLq3L7QP5IRSwbDNF7Q96FCaFKZw+5QRa4R6bbY7IlAqGnc4MS43O7fQnE9FvbHFPHfRGMoHdMEQXbkg6vGHdekI/7ImComDMk6Y8bUMa40UEji4CJNEm7VXqqAYSnCmnXdlLbUamVypXwn7/Ram3U88E7O16oXU5WIiVS82s1mW/GEnUYTVkwP66m040EtVmoUWz74znR+2gx1Jl3Qt1Wj0KFFo2M+hUfSOLXgyYOl9NU2ER5Ulsvews4+Mcm0Vh18nYVsOw93inOSvMYguK5tLdQQKQAc2D46n3YuRtrs+nDZHkc5y/bu2X8/Xfdz0vz1AAvkA==)
I see the same on .NET 7 Preview 2.

**Comment by tannergooding** [comment]
Hmmm. These should be going down the same path. I'd guess there is something missing in `simdashwintrinsic.cpp` during import.
