### ISSUE TITLE
Backport Move to Windows.10.Amd64.Server2022.ES.Open to 6.0

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#67048]
CI in backport PRs are now failing because Windows.10.Amd64.Server19H1.ES.Open is reaching EOL, example: https://dev.azure.com/dnceng/public/_build/results?buildId=1674630&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e&l=53
`##[error]SENDHELIXJOB(0,0): error : Helix queue windows.10.amd64.server19h1.es.open is set for estimated removal date of 2022-03-31. In most cases the queue will be removed permanently due to end-of-life; please contact dnceng for any questions or concerns, and we can help you decide how to proceed and discuss other options.
`
Please backport https://github.com/dotnet/runtime/pull/66404 to 6.0

**Comment by danmoseley** [comment]
cc @elinor-fung

**Comment by CarnaViire** [comment]
citing @MattGal 
> [4:18 PM] Matt Galbraith
    I would certainly recommend such a backport.   You just need the changes in https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/templates/runtimes/send-to-helix-inner-step.yml#L17 and https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/templates/runtimes/send-to-helix-inner-step.yml#L25 I believe

> ​[4:21 PM] Matt Galbraith
    One other thing to consider for release branches is a property I added called "FailOnMissingTargetQueue"

> ​[4:22 PM] Matt Galbraith
    it's true by default (https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs#L29) but if you set it to false, it will downgrade removed queues to warnings allowing you to ignore expiring helix jobs as long as you still send to 1+ remaining queues

**Comment by elinor-fung** [comment]
Ah, in order to be clean running on Server 2022, we'd also need to backport all the System.Net fixes... cc @wfurt

**Comment by wfurt** [comment]
It seems like we need https://github.com/dotnet/runtime/pull/64968 @elinor-fung. It seems like I started back then but it never finished after automatic back-port failed ;(
And yes, the base issue is https://github.com/dotnet/runtime/issues/58927 - something Windows is trying to fix. The reason why Server 2022 had more failures when introduced lives in fact that the image we use is significantly modified by Azure (for security reasons)

**Comment by elinor-fung** [comment]
The backport was merged at the beginning of this month.
