### ISSUE TITLE
JIT LSRA Throughput: Short-circuit register selection

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/runtime#6705]
The loop over all the candidate registers in `LinearScan::tryAllocateFreeReg()` and in `LinearScan::allocateBusyReg()` could be short-circuited when a register is found that has the best possible score. Additionally, in the case of MinOpts, it could potentially short-circuit as soon as a suitable candidate is found, though one would want to weight the throughput benefit against the code quality impact.

category:throughput
theme:register-allocator
skill-level:expert
cost:medium

**Comment by kunalspathak** [comment]
We did fair amount of refactoring in https://github.com/dotnet/runtime/pull/45135 that would short circuit the other heuristics once we found a single register candidate out of set of registers.
