### ISSUE TITLE
[API Proposal]: Convert.FromBase64String to support ReadOnlySpan<char> input

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/runtime#67055]
### Background and motivation

The new Span performance optimizations are exciting for string parsing, but some of the old APIs still expect strings as input.

**This will be an easy change since the internal implementation already uses spans.**

PS. I'm aware that there's `TryFromBase64Chars`, but it expects me to calculate size and pre-create spans myself.

### API Proposal

```C#
namespace System
{
    public static class Convert
    {
        public byte[] FromBase64String(ReadOnlySpan<char> s)
    }
}
```

### API Usage

```C#
var span = "aGVsbG8gd29ybGQ=".AsSpan();
var byteArray = Convert.FromBase64String(span);
```

**Comment by EgorBo** [comment]
There is
```csharp
public static bool TryFromBase64Chars(ReadOnlySpan<char> chars, Span<byte> bytes, out int bytesWritten)
```

**Comment by alex-jitbit** [comment]
@EgorBo I did mention it in the issue body, please check.

It requires me to allocate a buffer, calculate the buffer size myself. `Convert` does have `FromBase64_ComputeResultLength` but it's private.

**Comment by EgorBo** [comment]
> @EgorBo I did mention it in the issue body, please check.
> 
> It requires me to allocate a buffer, calculate the buffer size myself. `Convert` does have `FromBase64_ComputeResultLength` but it's private.

Sorry, I didn't notice. My opinion that half-span, half-heap allocations APIs don't look good.
If you use spans you use them all the way and as I noted - it allows you to avoid a heap allocation for the output (stackalloc or ArrayPool). 

>  calculate the buffer size myself. Convert does have FromBase64_ComputeResultLength but it's private.

If I am not mistaken you can just stackalloc/rent a buffer using the raw base64 span size - it's always going to be bigger than the source and then slice it after.

**Comment by alex-jitbit** [comment]
@EgorBo understood. Feel free to close
