### ISSUE TITLE
Proposal: use ValueTask<TItem> in CacheExtensions.GetOrCreateAsync

### ISSUE THREAD

**Issue by pablocom** [dotnet/runtime#67069]
Hey! 
Recently I used `CacheExtensions.GetOrCreateAsync` extension method and noticed that is always allocating a Task, even when a cache entry is present for given key, so the operation completes synchronously.

I would like to ask if there could be a performance improvement by changing the return type of this method to `ValueTask<TItem?>` .

**Comment by Wraith2** [comment]
C# does not allow method overloads to differ only by return type, you will need to use a different name.
