### ISSUE TITLE
MissingMethodException: The method 'System.Void System.IO.Packaging.Package::.cctor()' has no implementation.

### ISSUE THREAD

**Issue by MattBell96** [dotnet/runtime#67079]
I am having an issue when building my Unity app to IOS. Application uses Xceed.Words and works fine when in editor. then I run into this error when building and running on iPad. Any help appreciated

**Comment by adamsitnik** [comment]
@lambdageek do Unity apps use `System*` libs provided by Mono (https://github.com/mono/mono) or .NET Standard libs from dotnet/runtime?

**Comment by adamsitnik** [comment]
Hi @MattBell96 

I've confirmed offline that Unity is using a fork of Mono: https://github.com/Unity-Technologies/mono

Please report the bug to Unity.
