### ISSUE TITLE
Use framework provided by the SDK

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#67080]
The ILCompiler NuGet package currently includes a copy of all the inbox framework assemblies:

https://github.com/dotnet/runtime/blob/b4e258a377ccfd8fe636f51b50e8f9204d292d8f/src/installer/pkg/projects/Microsoft.DotNet.ILCompiler/Microsoft.DotNet.ILCompiler.pkgproj#L14

The .targets embedded in the ILCompiler package then replace the framework implementation assemblies that the SDK knows about with this private copy:

https://github.com/dotnet/runtime/blob/87777b624b0b8ea295b0fe9cd8505ce262ed75c0/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L117-L118

https://github.com/dotnet/runtime/blob/87777b624b0b8ea295b0fe9cd8505ce262ed75c0/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L158-L159

We do this because up until the move of NativeAOT to the runtime repo, we had customizations in the framework libraries that were not present in the shipping framework assemblies, and the NativeAOT CoreLib didn't version with the libraries that are in the SDK either (the latter is still true for users who consume NativeAOT as a NuGet package vs those that will consume it from the SDK - we sometimes do things like moving types from framework assemblies to CoreLib and such changes are not compatible with old frameworks).

The NativeAOT integration provided by the SDK should probably not be shipping a separate copy of these.

I'm putting this into .NET 7 milestone for consideration, but I'm not sure how much it's needed and how much it's nice to have.

Cc @agocke @LakshanF

**Comment by jkotas** [comment]
> we sometimes do things like moving types from framework assemblies to CoreLib and such changes are not compatible with old frameworks

These types of changes are still happening today.

In order to do this, we would need to guarantee that the runtime pack version and NativeAOT package version are the same.

**Comment by MichalStrehovsky** [comment]
https://github.com/dotnet/performance/pull/2905 ran into us replacing the framework with our versions - it's not possible to use new Collections.Immutable with 7.0 NativeAOT because we replace it with the old version.

**Comment by MichalStrehovsky** [comment]
Closing in favor of #87060.
