### ISSUE TITLE
[API Proposal]: Add support for converting to/from `IntPtr` for some handles

### ISSUE THREAD

**Issue by DaZombieKiller** [dotnet/runtime#67090]
### Background and motivation

The `Type.GetTypeFromHandleUnsafe` method allows you to retrieve the `Type` object associated with a type handle pointer retrieved via `RuntimeTypeHandle.Value`.

Currently, this API is `internal` with no `public`-facing equivalent. This means there is currently no safe way for you to get the original `Type` or `RuntimeTypeHandle` value back, leading to the `RuntimeTypeHandle.Value` property being of little use.

Having a way to retrieve the original `Type` or `RuntimeTypeHandle` would also allow the type handle pointer to be used to easily pass types to native code (such as when writing a custom runtime host).

### API Proposal

```diff
public struct RuntimeTypeHandle
{
+     public static RuntimeTypeHandle FromIntPtr(IntPtr value);
+     public static IntPtr ToIntPtr(RuntimeTypeHandle value);
}

public struct RuntimeFieldHandle
{
+    public static RuntimeFieldHandle FromIntPtr(IntPtr value);
+    public static IntPtr ToIntPtr(RuntimeFieldHandle value);
}

public struct RuntimeMethodHandle
{
+    public static RuntimeMethodHandle FromIntPtr(IntPtr value);
+    public static IntPtr ToIntPtr(RuntimeMethodHandle value);
}
```

### API Usage

```C#
var api = new NativeAPI
{
    GetTypeHandle      = &GetTypeHandle,
    GetFullTypeName    = &GetFullTypeName,
    GetFunctionPointer = &GetFunctionPointer
};

// This native method may be interested in querying for
// pointers to UnmanagedCallersOnly methods to invoke.
SomeNativeMethod(&api);
```
```C#
[UnmanagedCallersOnly]
static IntPtr GetTypeHandle(IntPtr typeName)
{
    return Type.GetType(Marshal.PtrToStringUni(typeName)).TypeHandle.Value;
}

[UnmanagedCallersOnly]
static IntPtr GetFunctionPointer(IntPtr type, IntPtr methodName)
{
    var type   = Type.GetTypeFromHandle(RuntimeTypeHandle.FromIntPtr(type));
    var method = type.GetMethod(Marshal.PtrToStringUni(methodName), BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
    return method.MethodHandle.GetFunctionPointer();
}

[UnmanagedCallersOnly]
static IntPtr GetFullTypeName(IntPtr type)
{
    return Marshal.StringToHGlobalUni(Type.GetTypeFromHandle(RuntimeTypeHandle.FromIntPtr(type))?.FullName);
}
```

### Risks

Being an unmanaged pointer, `RuntimeTypeHandle.Value` will not keep a collectible type alive. This would need to be clearly called out in documentation and could be a potential problem when the API is not used correctly.

**Comment by tfenise** [comment]
I guess the `IntPtr` value of `RuntimeTypeHandle.Value` does not keep a collectible type alive, and thus may be invalidated or recycled unexpectedly.

**Comment by DaZombieKiller** [comment]
> I guess the `IntPtr` value of `RuntimeTypeHandle.Value` does not keep a collectible type alive, and thus may be invalidated or recycled unexpectedly.

This is a good point, I'll add it to the risks section. It's definitely something that a user of the API would need to be keenly aware of.

**Comment by Joe4evr** [comment]
🍝 Just throwing this out for consideration: Should the public entrypoint for this API is placed somewhere under `S.R.InteropServices` (or whatever's more appropriate) instead?

**Comment by DaZombieKiller** [comment]
> 🍝 Just throwing this out for consideration: Should the public entrypoint for this API be placed somewhere under `S.R.InteropServices` (or whatever's more appropriate) instead?

That sounds reasonable to me -- `Type` is extremely discoverable, so it might not be the best location for an API as unsafe as this.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas or @davidwrighton Can either of you imagine a scenario where the TypeHandle wouldn't be static? Unless unloaded that is. I am trying to determine if there is any chance of the `IntPtr` value being invalid for any other reason than an unload type. There are a number of places in the runtime that assume a TypeHandle address doesn't move but I'd like to make sure there isn't any potential future scenario where that assumption could be changed.

**Comment by jkotas** [comment]
It is very likely that every realistic .NET runtime implementation has stable `IntPtr` (like `TypeHandle` in CoreCLR) that represents a type and that can be used to implement this marshaling very efficiently. The API contract should not say what this `IntPtr` actually points to.

In a hypothetical case where .NET runtime implementation does not have natural stable `IntPtr` that represents a type (e.g. the MethodTables are allocated on GC heap and can move), the API contract can be still maintained by a table on the side.

This API is about marshaling `System.Type` into IntPtr and back. We have API for the `System.Type` -> `IntPtr` direction (`RuntimeTypeHandle.Value`). We do not have an API for the `IntPtr` ->`System.Type` direction and this is proposing to fill this hole. Mono embedding APIs can give you pointer that represents a type and then use this pointer to get back to the type, so an alternative way to look at this request is managed surface feature parity with Mono embedding APIs.

**Comment by AaronRobinsonMSFT** [comment]
Thoughts on adding this to `RuntimeTypeHandle` itself. This would follow the [`GCHandle`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.gchandle.fromintptr) pattern and developers could then use [`Type.GetTypeFromHandle()`](https://docs.microsoft.com/dotnet/api/system.type.gettypefromhandle) to get back to `Type`.

```diff
public struct RuntimeTypeHandle
{
+     public static RuntimeTypeHandle FromIntPtr(IntPtr ptr);
}
```

**Comment by jkoritzinsky** [comment]
I like putting it on `RuntimeTypeHandle` personally. It makes it a little harder to find than if it were on `System.Type`, while still putting it on a related type (and as you mentioned, following the design styles of `GCHandle`).

**Comment by teo-tsirpanis** [comment]
I agree, it makes more sense to add it to `RuntimeTypeHandle`. I don't think of a good place in InteropServices that could fit.

**Comment by jkotas** [comment]
I agree that `RuntimeTypeHandle` sounds like a good place for this. If we were to follow the GCHandle pattern, should we add both `FromIntPtr` and `ToIntPtr` methods for discoverability?

**Comment by AaronRobinsonMSFT** [comment]
> If we were to follow the GCHandle pattern, should we add both FromIntPtr and ToIntPtr methods for discoverability?

Yep. That makes perfect sense.

@DaZombieKiller I'm going to update the proposal with this approach and then move it to ready for review. Please feel free to push back if you have another opinion.

**Comment by DaZombieKiller** [comment]
For the sake of parity, it may also be useful to expose APIs for `RuntimeMethodHandle` and `RuntimeFieldHandle`, which both also offer `IntPtr Value { get; }` properties with no way to convert back to a `RuntimeMethodHandle`/`RuntimeFieldHandle`.

```diff
public struct RuntimeFieldHandle
{
+    public static RuntimeFieldHandle FromIntPtr(IntPtr value);
+    public static IntPtr ToIntPtr(RuntimeFieldHandle value);
}

public struct RuntimeMethodHandle
{
+    public static RuntimeMethodHandle FromIntPtr(IntPtr value);
+    public static IntPtr ToIntPtr(RuntimeMethodHandle value);
}
```

**Comment by AaronRobinsonMSFT** [comment]
@DaZombieKiller Sure. I'll add that as well.

**Comment by terrajobst** [comment]
* For consistency, you might want to *also* add explicit casting operators too, like `GCHandle` does.

```C#
namespace System;

public struct RuntimeTypeHandle
{
    public static RuntimeTypeHandle FromIntPtr(IntPtr value);
    public static IntPtr ToIntPtr(RuntimeTypeHandle value);
}

public struct RuntimeFieldHandle
{
    public static RuntimeFieldHandle FromIntPtr(IntPtr value);
    public static IntPtr ToIntPtr(RuntimeFieldHandle value);
}

public struct RuntimeMethodHandle
{
    public static RuntimeMethodHandle FromIntPtr(IntPtr value);
    public static IntPtr ToIntPtr(RuntimeMethodHandle value);
}
```
