### ISSUE TITLE
Microsoft.NetCore.Targets 6.0.0 - No Stable Version

### ISSUE THREAD

**Issue by wapplegate** [dotnet/runtime#67099]
Are there plans to release a stable 6.0.0 version of the Microsoft.NetCore.Targets package? On NuGet, the latest version is "6.0.0-preview.4.21253.7". A project I work on uses this package to resolve an issue with a third-party package. The preview version works fine, just would prefer a stable version.

**Comment by jkoritzinsky** [comment]
That package was dead-ended during development of .NET 6 after Preview 4 in https://github.com/dotnet/runtime/pull/52261

**Comment by wapplegate** [comment]
Thanks for the info. A third party package was causing an issue that made the targets package required. After updating the package and a few related ones to the latest versions it seems it's no longer an issue.
