### ISSUE TITLE
Benchmark Dotnet AOT build failing with exit 1

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#67098]
```
// start dotnet build -c Release /p:DebugType=portable -bl:benchmarkdotnet.binlog --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in /home/yangfan/work/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/Job-SHQSFW

// command took 37.09s and exited with 1
--
```

Here is the template the project is generated from: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/MonoAOTLLVMCsProj.txt

Here is a full log from helix as a gist: https://gist.github.com/naricc/80a87bbfdb9aed4c5275ad89cabd3dc9

I am not sure if this is a bug in the MonoAOTCompiler task, or BDN, or both.

**Comment by SamMonoRT** [comment]
@naricc @fanyang-mono - I think the aot-llvm lanes are running ok, can one of you confirm and close this issue as appropriate?
