### ISSUE TITLE
A new way to modify JsonOptions

### ISSUE THREAD

**Issue by andrewjboyd** [dotnet/runtime#67097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to set the JSON options for specific requests on a legacy project.  The global settings were set incorrectly, the options we have now are to:
- define the new options and pass them manually to each new controller method. (more annoying than anything)
- define the old settings and pass them manually to each of the existing controller methods, then set the global settings to what they should be set to. (rather scary)

### Describe the solution you'd like

Define an abstract attribute like so
```csharp
[AttributeUsage(AttributeTargets.Class)]
public abstract class JsonSerializerOptionsAttribute : Attribute
{
    public abstract JsonSerializerOptions JsonSerializerOptions { get; }
}
```

In the SystemTextJsonOutputFormatter, modify the code like so:
```csharp
var serializerOptionsToUse = SerializerOptions;
var jsonSerializerOptionsAttributes = objectType.GetCustomAttributes(typeof(JsonSerializerOptionsAttribute), false);
if (jsonSerializerOptionsAttributes.Length == 1)
{
    serializerOptionsToUse = ((JsonSerializerOptionsAttribute)jsonSerializerOptionsAttributes[0]).JsonSerializerOptions;
}
else if (jsonSerializerOptionsAttributes.Length > 1)
{
    throw new InvalidOperationException($"Too many {nameof(JsonSerializerOptionsAttribute)} attributes on {objectType.Name}");
}
```
so you then pass in `serializerOptionsToUse` to the appropriate `SerializeAsync` call.  Similarly in the SystemTextJsonInputFormatter.

By doing this, it would allow us to define the overriding settings in an class like so:

```csharp
private sealed class MyCustomSettingsOverrideAttribute : JsonSerializerOptionsAttribute
{
    public override JsonSerializerOptions JsonSerializerOptions => new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, };
}
```

So you can decorate your classes with your new Attribute, returning them however you want, without having to be locked into writing code like this everywhere:

```csharp
return new JsonResult(result, MyCustomJsonSettings.Options);
```

**Comment by eiriktsarpalis** [comment]
What's the use case? Do you need to specify a naming policy that is scoped to the particular type? Something else?

At the moment I don't believe it is technically possible to scope a `JsonSerializerOptions` instance to a particular type (the internal converter infrastructure generally assumes a singular instance reused throughout the object graph). Even if we tried to make it happen the custom options instance would flow to nested values which would likely result in surprising behavior.

**Comment by andrewjboyd** [comment]
I double-checked, the code sample at the top of this only looks at the root for the JsonOptions and ignores any associated with child objects, if they exist

**Comment by krwq** [comment]
@andrewjboyd take a look at https://github.com/dotnet/runtime/issues/63686 and see if that would be satisfactory. I know this speaks about attribute to override options but ultimately goal seems to be to have more customization and perhaps contract resolver would be a better way to achieve what you want to do.

**Comment by andrewjboyd** [comment]
@krwq, if I understand correctly, you would be able to have it output something like this right?

```
{
  test1: 1,
  test2: 2,
  Test3: {
    Test3_1: 1
  }
}
```

Is there any sample code for this .NET 7 feature?  I'm trying to understand how I could achieve what I'm trying to achieve

**Comment by eiriktsarpalis** [comment]
@andrewjboyd the feature described in #63686 is currently under development so we can't provide concrete workarounds, but yes, it would be possible to set a custom naming policy for individual types or properties. For the reasons I outlined above, it would not be possible to specify a custom options instance on the type level.

I'm going to close this in favor of #63686.

**Comment by andrewjboyd** [comment]
Thank you for your time @eiriktsarpalis, @krwq & @davidfowl.  I can't wait to see this new feature up and running!
