### ISSUE TITLE
Potential BSOD in Libraries Test Run release coreclr windows x64 Release

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67105]
On Monday I've noticed that `Libraries Test Run release coreclr windows x64 Release` CI leg of `runtime-extra-platforms` has failed without uploading console log. 

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1673529/logs/819 mentions:

```log
error : Work item System.Data.DataSetExtensions.Tests in job f2e707ce-b3f9-41ad-8e0e-148a3e34c5a2 has failed. [D:\a\_work\1\s\src\libraries\sendtohelixhelp.proj]
error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/f2e707ce-b3f9-41ad-8e0e-148a3e34c5a2/workitems/System.Data.DataSetExtensions.Tests/console [D:\a\_work\1\s\src\libraries\sendtohelixhelp.proj]
```

But the [link is dead](https://helix.dot.net/api/2019-06-17/jobs/f2e707ce-b3f9-41ad-8e0e-148a3e34c5a2/workitems/System.Data.DataSetExtensions.Tests/console).

I've reported it [here](https://github.com/dotnet/core-eng/issues/15700#issuecomment-1074255554) as I assumed that it was related to an issue fixed by this PR that was resulting with dead-letters.

@MattGal [responded](https://github.com/dotnet/core-eng/issues/15700#issuecomment-1074473876):

> This is pretty interesting, but not the problem in this issue. Looking at the history of trying to run this work item, there was something catastrophic (either bad luck or otherwise) happening on the machine. On two different machines (and three different attempts) to run this work item, the machines that started this work item logged "Work item started", then ~20-25 minutes later started a different work item. Since it never completed in its three attempts, it became "dead letter".

> If this happens repeatedly, you're almost certainly looking at a test that is BSOD'ing (or otherwise causing a reboot to) the helix agent it's running on.

And now, few days later very similar issue occured for few other CI runs for the very same config:

When running `Microsoft.CSharp.Tests`:

https://dev.azure.com/dnceng/public/_build/results?buildId=1677655&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1677655&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d&l=650

When running `Microsoft.Extensions.Configuration.Binder.Tests`, `Microsoft.Extensions.Configuration.EnvironmentVariables.Tests`, `Microsoft.Extensions.Configuration.FileExtensions.Tests` and few other test projects:

https://dev.azure.com/dnceng/public/_build/results?buildId=1678749&view=results
https://dev.azure.com/dnceng/public/_build/results?buildId=1678749&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d

There were other Windows CI legs that have resulted with deadletter as well: https://github.com/dotnet/runtime/issues/67058

I've applied `area-Infrastructure` label as I don't know how to verify whether it's an infra or a product issue.

cc @jkotas @stephentoub @ericstj

**Comment by MattGal** [comment]
@adamsitnik there can be more than one thing causing this sort of behavior, so I'll double check that the symptoms match here.

**Comment by MattGal** [comment]
Yes these all match that symptom.  Let me know if you have any deeper infra questions; something completely blasts these machines repeatedly for these work items.  It's obviously not a 100% repro but if you have resources making `windows.10.amd64.server20h2.open` DTL machine to run these tests in a loop on might help, since you really need this machine's event log after whatever happened to see what's up.

**Comment by ericstj** [comment]
@MattGal can we find the most recent instance of the issue and have someone inspect the machine if it hasn't been re-imaged since then?  Wouldn't it have the crashdump and event logs of interest?

**Comment by MattGal** [comment]
> @MattGal can we find the most recent instance of the issue and have someone inspect the machine if it hasn't been re-imaged since then? Wouldn't it have the crashdump and event logs of interest?

Cost savings make that real hard, unfortunately.   This symptom is delayed and every one I've investigated the machine had been scaled in (these are short-lived, Azure VMSS machines that are deleted when work stops).

I can definitely make windows.10.amd64.server20h2.open be "stuck" at a specific scale-out for some time, then use a jump box to get to the machine this happens on , but 1) we have no idea how long it takes to get the repro and 2) it would stop scaling out just as much as in, so if a lot of work came in it'd get backed up.

If it comes to that, ping me on Teams and we can explore it, but machines never live that long these days.

**Comment by danmoseley** [comment]
Do we get control after the bluescreen -- even if it's an unrelated work item and only rarely? If so could we change the scripts to upload any  `C:\Windows\MEMORY.DMP`, even if it would take detective work to figure out what previous job caused it. 

But perhaps on bluescreen, that counts as 'work stops' immediately.

**Comment by MattGal** [comment]
> Do we get control after the bluescreen

We do not.  We get a "I'm setting up this work item!" then a "I'm starting this work item" then it stops logging everywhere I'm capable of looking.

**Comment by akoeplinger** [comment]
But it comes back up after the bluescreen right? I think what @danmoseley meant is that we'd check for `C:\Windows\MEMORY.DMP` existing when a workitem starts and upload+delete it, so the next workitem after a reboot would upload it. We'd just need to query Kusto for existence of such files then.

**Comment by danmoseley** [comment]
I understood @MattGal to be telling us that by the time a fresh workitem starts, the machine has been reset/cleaned.

**Comment by MattGal** [comment]
It does come back, this might work, but it will be a needle in a haystack type problem... let's not do that.  If you get stuck, the "disable autoscaling, leave around static machines til it happens, get on machine via jumpbox" is significantly less legwork than this.

**Comment by adamsitnik** [comment]
Hit again in https://dev.azure.com/dnceng/public/_build/results?buildId=1680790&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d&l=650. This time for `Microsoft.Extensions.Logging.Tests` and `System.Collections.NonGeneric.Tests`

**Comment by adamsitnik** [comment]
And again in https://dev.azure.com/dnceng/public/_build/results?buildId=1679639&view=logs&j=8679535e-9046-505f-8bbe-da251e73ecbd&t=ab7958ed-5297-5b46-f99a-06ce433e067d&l=650. For `System.Collections.Specialized.Tests`, `System.Collections.Tests`, `System.ComponentModel.Annotations.Tests`, `System.ComponentModel.Composition.Registration.Tests`, `System.ComponentModel.Composition.Tests`, `System.Composition.Hosting.Tests` and `System.Diagnostics.Tools.Tests`

**Comment by danmoseley** [comment]
> disable autoscaling, leave around static machines til it happens, get on machine via jumpbox

Can you help us go ahead and do this @MattGal ?

**Comment by MattGal** [comment]
@adamsitnik / @ericstj do you mind causing work to run on the queue?  Nothing's run since I did this experiment!

**Comment by MattGal** [comment]
I don't think this is a BSOD any more, I'll put some details in https://github.com/dotnet/core-eng/issues/15845.  Basically, it looks like Docker isn't working right all the time on this queue.

**Comment by agocke** [comment]
I'm going to close this out since it looks like there might be a different problem here. Let's open new, more specific issues as necessary.
