### ISSUE TITLE
SEGFAULT due to tiered compilation on 32 bit RASPBIAN .net 6.0 Builds

### ISSUE THREAD

**Issue by dlukach** [dotnet/runtime#67102]
### Issue Description
We're having an issue with .net 6.0 builds of our Avalonia GUI App.

The issue is, when resizing or scrolling an items repeater we get a SEGFAULT with our .net 6.0 app.
This issue only occurs when building an arm32 .net 6.0 program, no matter if it's ready or run to not.
The same test program does not SEGFAULTon 64bit arm or when being targeted as .net 5.0 instead of .net 6.0. 
The issue also goes away when TieredCompliation is set to false & TieredCompilationQuickJitForLoops and TieredCompilationQuickJit is set to true. Further information and discussion was done in the Avalonia issue below.

[Here is the avalonia issue](https://github.com/AvaloniaUI/Avalonia/issues/7744)
[Here is our test project](https://github.com/mabrams17/SegFault-AvaloniaExample)

### Steps to Reproduce
Publish the test project above as .net 6.0, arm32 bit, single file ready to run.
Execute on Raspbian 32 bit os, buster is what we use.
Scroll or mess with the window dimensions.
SEGFAULT should occur.
-->

### Expected Behavior
Scrolling and resizing a GUI with an items repeater should work as normal.

### Actual Behavior
Scrolling creates a SEGFAULT and crashes the program

### Versions & Configurations
MSBUILD 17.0.0.52104
Raspbian 32 Bit Buster on Raspberry Pi 4
.NET 6.0 Framework
Avalonia 0.10.13

**Comment by jkotas** [comment]
AV in libclrjit.so:
```
Thread 22 ".NET Tiered Com" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6f931440 (LWP 2795)]
0x6f9f749e in ?? () from /home/pi/Documents/SegFault-AvaloniaExample/TestProject/bin/Debug/net6.0/linux-arm/publish/libclrjit.so
```

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib. @AndyAyersMS PTAL.

**Comment by JulieLeeMSFT** [comment]
Changing owner to @jakobbotsch because it is on .NET 6 framework.

**Comment by dlukach** [comment]
Any updates on this, it has been 13 days?

**Comment by kunalspathak** [comment]
We are currently busy with other high pri items but will plan to investigate this soon.

**Comment by kunalspathak** [comment]
The break happened in https://github.com/dotnet/runtime/pull/45135 while unassigning the interval and restoring the previous interval. I will send out the fix shortly.
