### ISSUE TITLE
Suboptimal codegen for `default(SomeValueType)`

### ISSUE THREAD

**Issue by exyi** [dotnet/runtime#67116]
### Description

Small demonstration of the issue:

```csharp
struct S {
    public int Prop { get => 42; }
    public S(string a) { }
}
public class Test {
    public int Fast() {
        return new S("dummy").Prop;
        // mov eax, 0x2a
        // ret
    }
    public int Slow() {
        return new S().Prop;
        // push rax
        // xor eax, eax
        // mov [rsp], rax
        // lea rax, [rsp]
        // mov byte ptr [rax], 0
        // mov eax, 0x2a
        // add rsp, 8
        // ret
    }
}
```

Paradoxically, calling a struct constructor is way significantly faster than zero-initializing it (either using `new S()` or `default(T)`). However, calling the constructor couldn't be done so easily if `S` would be generic argument.

Obviously, it's not a huge deal, only a few more instructions. However, it seems like fairly low hanging fruit and since initializing structs is a common operation, it could have some impact.

### Configuration

.NET 6 x64, can be replicated in [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB9cMoBXMDAAgGUqBvAWACgq2qABAZioEsA7agAUoEAA4MqAcxjUAvAD4qKAEwBuKgF8W7TjxoAKDgEYADFWwBKSdua3unFVQDCDHewcDqNADYQA7gbWTKy6HgDsVPww/rRBAHQi4mrubLa6noJUAGJ4GEFuoWGckdGxhgBEACZk+PgAnhWWiaJiKUVaLLZAA)

### More context

Note that replacing `struct S` with `class S` also solves the issue, so surprisingly class is faster than struct :roll_eyes:

We discovered this issue when trying to implement fixed point numbers parametrized by a shift constant. We need to make the parameter a struct, as reference type parameters are not specialized. Later we discovered that using the `new()` constraint produces better code on .NET 6, even though it creates the instance using Activator - but this solution is far from ideal, because it performs very poorly on the old .NET Framework.

```csharp
interface IFixedTParams {
    int Shift { get; }
}

struct Q8_24 : IFixedTParams {
    int IFixedTParams.Shift { get => 24; }
}

// [JitGeneric(typeof(Q8_24))]
class Fixed<TParams> where TParams : IFixedTParams, new() {
    private readonly int rawValue;
    
    public int ToIntFast() {
        int shift = new TParams().Shift;
        return rawValue >> shift;
    }
    
    public int ToIntSlow() {
        int shift = default(TParams).Shift;
        return rawValue >> shift;
    }
}
```

[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAIBlAC2ygAcAZbYAOgCUBXAOwwEt8MANwBYAFDi+vGFABm2MDHIBJAGJ8EMACYAVAAp1s+XOQDe48pfJSMVan1m3T5AOYwMQ8gF9xPiWNwMKE4wWwBFAA4AfQAmFHIQFXVNXQMoIxNzMStrXiSNbX1DY1YaBydXd3IAXgA+cjjPPz9xAG0AKT4MAHEYbhk+MAAKDABPehgIWSHI2JQASnmAXXFiGPJk7QAeIvTjeoB3ahklXYyE/JSz4zRyfoOh+bMLK3ooPgA3bAwlWGwtCDcAA2o1ytnSBwAatggZxhC9LAjyMQAMxg8g6CDKXiqPAYR7PbI5Kw2ci4eyOGp3GAHDFpDKPUoUjxInLEADs5Ah0NhSlq9XJ5VERMsfhySNR6Mx2IwlCBEAeTyyxJJeUFlOq5C0MHknCB+OuuHmTKFrKsHK52ChMLh5H5ZOZwpyzXEQA=)

Since the whole point of doing fixed point arithmetic is to be a bit faster than floating point math, you can see why these few extra copy instructions are a problem in this use case.

**Comment by EgorBo** [comment]
Just checked - codegen is fine for both in .NET 7.0 (Main), likely was fixed by https://github.com/dotnet/runtime/pull/64130?
