### ISSUE TITLE
Incorrect DateTimeFormat for nb-NO in Blazor WebAssembly

### ISSUE THREAD

**Issue by AbstractionsAs** [dotnet/runtime#67115]
### Description

Getting month and day names returns incorrect values.
Months come back as M01, M02, etc
Days come back as English day names

### Reproduction Steps

```csharp
var culture = CultureInfo.GetCulture("nb-NO");

// Should return 'mars', returns 'M03'
var march= culture.DateTimeFormat.GetMonthName(3);

// Should return 'tirsdag', returns 'Tuesday'
var tuesday = culture.DateTimeFormat.DayNames[2];
```

### Expected behavior

Should return the correct values

### Actual behavior

Returns incorrect values

### Configuration

.net 6
Windows 10 (WebAssembly)
x64
Spesific to blazor WebAssembly
All browsers

**Comment by tarekgh** [comment]
CC @lewing

**Comment by lewing** [comment]
This is likely a result of the way we strip down the formatting data for size reasons.  Can you explain your use case to help us prioritize changes?

**Comment by AbstractionsAs** [comment]
In my case I became aware of the problem because I was using the 'BlazorDateRangePicker' in an application, and it was giving me a calendar with wrong information in it. When setting the culture manually didn't work, I started investigating.

The use case is a date picker. If this isn't solved I will either have to fall back to a JavaScript implementation, or fork the component and hard code all values for the most important cultures myself.

Our market is Norway, and thus the user interface needs to properly support Norwegian.

Skaff deg Outlook for Android<https://aka.ms/ghei36>
________________________________
