### ISSUE TITLE
RyuJIT SIMD GetItem Intrinsic optimization

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6711]
SIMD intrinsic GetItem has two operands, op1=SIMD Vector and op2=index.
When op1 is a memory-op, we should be able to combine op1 and op2 into an addr mode and replace GT_SIMD node with GT_IND(GT_LEA).   This is more efficient than forcing addr of GT_IND to a reg so that we can generate [reg] or [reg+offset] or [reg+sizeof(SIMD base type)*indexReg+offset].

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by tannergooding** [comment]
This should largely be optimized/fixed with the `HWIntrinsic` and `SimdAsHWIntrinsic` work.

This will correctly generate an `extract` or `mov eax, [addr]` instruction.
