### ISSUE TITLE
Official build sometimes fails building mono.workloads

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#67117]
cc: @steveisok 

Seems that in the past week the official build has failed twice due to the job that is trying to build the mono.workloads with the following error message:

```
src\workloads\workloads.csproj(119,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Object reference not set to an instance of an object.
```

Here is a link of a sample build that was affected by this: [20220319.2](https://dev.azure.com/dnceng/internal/_build/results?buildId=1671918) => [Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/1671918/logs/2243)

We should a) look into why this specific failure is happening and affecting two builds, and also b) I noticed that the workloads build is not protected by CI, which is why we have only seen this problem in the official build. Should this be something that is also protected in CI?

**Comment by joperezr** [comment]
FYI: @adamsitnik

**Comment by joeloff** [comment]
The new tooling we have should hopefully address this, but we've only got the PR out for review for 6.0, but we've rewritten the workload tasks.
