### ISSUE TITLE
Segmentation fault when run by `execve()` with relative path

### ISSUE THREAD

**Issue by alex65536** [dotnet/runtime#67127]
### Description

If relative path was specified to `execve()` syscall to execute a .NET binary, this binary may crash with segmentation fault because of NULL derefence.

The problem is as follows. We invoke `INIT_GetCurrentEXEPath()` to get the full path to binary:
https://github.com/dotnet/runtime/blob/feb25b01385242beb804b48f4954dbda62d3d54f/src/coreclr/pal/src/init/pal.cpp#L557

Then, `INIT_GetCurrentEXEPath()` calls `minipal_getexepath()` to get the path:
https://github.com/dotnet/runtime/blob/feb25b01385242beb804b48f4954dbda62d3d54f/src/coreclr/pal/src/init/pal.cpp#L1275

Then, `minipal_getexepath()` tries to get the path via `getauxval(AT_EXECFN)`:
https://github.com/dotnet/runtime/blob/14304eb31eea134db58870a6d87312231b1e02b6/src/native/minipal/getexepath.h#L79

The problem is that, if the path passed to `execve()` was relative, `getauxval()` will just return it. So, instead of full path,  `INIT_GetCurrentEXEPath()` will return a relative path, without slashes.

This relative path goes then to `CorUnix::InitializeProcessCommandLine()`:
https://github.com/dotnet/runtime/blob/e7467a8638cbf78312e04e3c79a1fabc8b78b62f/src/coreclr/pal/src/thread/process.cpp#L3705

This function just assumes that the path would be absolute and has no checks that it contains a `'/'`. Consider the following code from there:
https://github.com/dotnet/runtime/blob/e7467a8638cbf78312e04e3c79a1fabc8b78b62f/src/coreclr/pal/src/thread/process.cpp#L3719-L3721
As the passed string doesn't contain slashes, this will just crash.

### Reproduction Steps

Suppose that `Binary` is the name of our executable. Then, the Python script

```python
import os

os.execve('Binary', ['Binary'], {})
```

will exit with `Segmentation fault` after `exec`'ing

### Expected behavior

No segmentation fault

### Actual behavior

Segmentation fault occurs

### Configuration

.NET Core: 5.0.6
OS: Debian GNU/Linux
Architecture: x64

According to the source code, the issue is applicable to all Linuxes and is not specific to my configuration and will reproduce with even with the latest version in `main` branch.

**Comment by am11** [comment]
> Segmentation fault when run by execve() with relative path

Do you have reproduction steps in .NET that result in segmentation fault?

> The problem is that, if the path passed to `execve()` was relative, `getauxval()` will just return it. So, instead of full path, `INIT_GetCurrentEXEPath()` will return a relative path, without slashes.

We always get absolute path or a NULL back from `minipal_getexepath()`, see `realpath()` call in the lines that follow `getauxval()`.

**Comment by alex65536** [comment]
> We always get absolute path or a `NULL` back from `minipal_getexepath()`, see `realpath()` call in the lines that follow `getauxval()`.

Yes, you are right. So, the bug seems to be specific to v5.x branch where `realpath()` was not called:
https://github.com/dotnet/runtime/blob/v5.0.15/src/coreclr/src/pal/src/init/pal.cpp#L1392-L1401

> Do you have reproduction steps in .NET that result in segmentation fault?
The reproduction steps are in the bug report above. If you just run any .NET binary with relative path in `execve()`, you will get a crash. But as I said above, the issue seems to affect only v5.x, and the newer versions are not affected.

Sorry for disturbing. I am closing the issue.

**Comment by am11** [comment]
Thanks for your thorough analysis. This was indeed the problem in .NET 5 and earlier versions. To avoid such disparities, we unified about half a dozen implementations of "get self executable path" as `minipal_getexepath()` after .NET 5 release, and used it everywhere across the repo: coreclr, corehost/dotnet.exe, mono, `System.Environment.GetProcessPath()`.
