### ISSUE TITLE
Analyzer: Prefer Task.FromResult over Task.Run(() => value)

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#67123]
As [discussed on Twitter](https://twitter.com/davidfowl/status/1507131629201813504) by @davkean @davidfowl and others.

At times code is forced to be in an async/`Task` context, e.g. when overriding virtuals or generally when working with a framework. Some people end up using `Task.Run()` because they are unaware of `Task.FromResult` or `Task.CompletedTask`.

For example, this code

```C#
public override Task<string> PerformWork()
{
    return Task.Run(() => "some value");
}
```

should have be been

```C#
public override Task<string> PerformWork()
{
    return Task.FromResult("some value");
}
```

**Comment by stephentoub** [comment]
If we think it's a common enough thing to do to be meaningful, seems fine to add.  There are _many_ variations of "why oh why is it written this way", though, so we'll need to draw a line somewhere as to what patterns we handle.  For example, I've more commonly seen people that _do_ know about Task.FromResult silence the "warning CS1998: This async method lacks 'await' operators and will run synchronously" warning when they've written this:
```C#
public override async Task<string> PerformWork()
{
    return "some value";
}
```
by changing it to be:
```C#
public override async Task<string> PerformWork()
{
    return await Task.FromResult("some value");
}
```
which makes _me_ cry, and should instead have just stayed the way it was and silenced the warning or else be changed to be a non-async method with FromResult:
```C#
public override Task<string> PerformWork()
{
    return Task.FromResult("some value");
}
```

There's also various options for what the fixer could do.  In your original example, the proposed fix was:
```C#
public override Task<string> PerformWork()
{
    return Task.FromResult("some value");
}
```
That's valid.  If the precomputed value is a const or static (and isn't something FromResult is likely to have cached, like true/false), so too may be using a cached task, e.g.
```C#
private static readonly Task s_someValueTask = Task.FromResult("some value");

public override Task<string> PerformWork() => s_someValueTask;
```
Etc.

**Comment by hez2010** [comment]
How about adding an implicit operator overload to suppress the error?

```csharp
class Task<T>
{
    public static implicit operator Task<T>(T value) => Task.FromResult<T>(value);
}
```

**Comment by stephentoub** [comment]
We avoid adding implicit casts that allocate.

**Comment by terrajobst** [comment]
Also, I'm doubtful that it would solve the original problem because implicit conversions are even less discoverable than static members.

**Comment by bartonjs** [comment]
The premise behind this analyzer seems sound (and we came up with a lot of cases that would be useful (and safe) in addition to just literals.  However, we don't think that this occurs often enough in real code to warrant the CPU cost of running the analyzer itself.

If someone wants to convince us that this is actually quite widespread, we can revisit it in the future.

**Comment by Neme12** [comment]
@bartonjs  I've definitely seen this a lot, even from senior devs. I think the experience of Microsoft devs might be a little skewed because they're working with other super knowledgable developers, but ordinary developers definitely do this in real code.

**Comment by davidfowl** [comment]
> If someone wants to convince us that this is actually quite widespread, we can revisit it in the future.

What does proof look like?

**Comment by bartonjs** [comment]
> What does proof look like?

@stephentoub (and I think one or two others) was looking for prevalence of the pattern in searchable codebases, and just didn't see a lot of hits.  So, it'd be something to convince us (or at least just Steve) that this happens often enough that `[number of times it happens] * [detection rate] * [time cost of it being done]` is big enough compared to `[number of times people compile C#, ever] * [the true positive rate of this detector] * [the amount of time it takes to run this particular analyzer]`.

The consensus was basically "it happens, but not extremely often, and it's not all that bad" balanced against "at some point we're going to have so many analyzers running that the compiler will never finish".
