### ISSUE TITLE
RyuJIT SIMD: optimize SIMD codegen since SSE/AVX allow the second operand to be a memory-op

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6712]
Instructions like addps/addpd/subps/subpd etc allow the second operand to be a memory-op.  Right now this is not taken advantage of by SIMD codegen.  Partly the reason is that these instructions require SIMD vector to be aligned on a 16-byte (SSE) or 32-byte (AVX) boundary.   SIMD Vector locals allocated on stack are aligned by JIT and those on heap are not guaranteed to be 16/32-byte aligned.   That would mean in cases where memory operand is known to be on stack, we should be able to mark the second operand as contained to reduce register pressure.

category:cq
theme:vector-codegen
skill-level:expert
cost:medium

**Comment by tannergooding** [comment]
This was fixed some time back as part of adding HWIntrinsic support and then later porting System.Numerics and friends to be implemented in terms of HWIntrinsics
