### ISSUE TITLE
Test failure System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67134]
Run: [runtime-libraries-coreclr outerloop 20220324.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1679742&view=ms.vss-test-web.build-test-results-tab&runId=46025620&resultId=103197&paneView=debug)

Failed test：
```
net7.0-Linux-Release-arm-CoreCLR_release-(Debian.11.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm32v7-20210304164347-5a7c380

- System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments
```
**Error messag:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.AssertCounterEventsPresent(EventWrittenEventArgs[] events, String meterName, String instrumentName, String tags, String expectedUnit, String[] expectedRates) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 859
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 298
```

**Comment by VincentBu** [comment]
Failed again in: [runtime-libraries-coreclr outerloop 20220510.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1762128&view=ms.vss-test-web.build-test-results-tab&runId=47428486&resultId=103607&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Alpine.314.Arm64.Open)ubuntu.1804.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments

```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.AssertCounterEventsPresent(EventWrittenEventArgs[] events, String meterName, String instrumentName, String tags, String expectedUnit, String[] expectedRates) in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 860
   at System.Diagnostics.Metrics.Tests.MetricEventSourceTests.EventSourceFiltersInstruments() in /_/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs:line 298
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by tommcdon** [comment]
@tarekgh would you mind taking a look?

**Comment by tarekgh** [comment]
@noahfalk better to look? Let me know @noahfalk if you don't have time to look at it.

**Comment by noahfalk** [comment]
Although I can't be certain from the data in the log, the timestamps are suggestive that this machine was running extremely slowly, failing to execute even a small amount of code during a 5 second window where the test expects a result to show up. The code did eventually run so there was no hang/deadlock, it was just very very slow. 

@tarekgh - is there an attribute we can put on these tests to avoid running them on arm? I expect the value we get from doing these tests xplat is low and I doubt it is worth anyone's time to triage further failures.

**Comment by tarekgh** [comment]
>  is there an attribute we can put on these tests to avoid running them on arm? I expect the value we get from doing these tests xplat is low and I doubt it is worth anyone's time to triage further failures.

Yes, I am seeing the test already using the condition ` [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotBrowser))]`. You can have something like the following:

```C#
private static bool CanRunEventSourceFiltersInstrumentsTest => PlatformDetection.IsNotBrowser && PlatformDetection.IsNotArmNorArm64Process;

// then change the attribute to 
[ConditionalFact(nameof(CanRunEventSourceFiltersInstrumentsTest))]
```

**Comment by tarekgh** [comment]
It is failing with the same test case 

https://github.com/dotnet/runtime/blob/8684c21765ee666f70085c0012d89dc92bd1fdab/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs#L298

but failing in another place.  it used to fail in 

https://github.com/dotnet/runtime/blob/8684c21765ee666f70085c0012d89dc92bd1fdab/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs#L860

and now it is failing in 

https://github.com/dotnet/runtime/blob/8684c21765ee666f70085c0012d89dc92bd1fdab/src/libraries/System.Diagnostics.DiagnosticSource/tests/MetricEventSourceTests.cs#L864

@noahfalk also this failure is on `x86` and not `arm`.  do you think we need to add more logging info to the test to see more details what is going on?

**Comment by noahfalk** [comment]
This appears likely timing related again, though not quite as clear cut as last time. The metrics listener is trying to report data every 5 seconds and the test attempts to increment counters sometime during that 5 second interval. In this case the listener was turned on at 12:19:28 and ideally we'd see interval every 5 seconds after that (33, 38, 43, ...). Instead the interval boundaries were 34, 42, 43 and the counters that were supposed to be incremented before 43 didn't happen in the one second the interval actually covered. A simplistic solution is to make the intervals bigger so that the test can withstand more latency from the timer or CPU scheduler without failing. I'll make a PR in a moment here.
