### ISSUE TITLE
Enumerable.Chunk throws OutOfMemoryException for very large chunk sizes.

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#67132]
### Description

The exception is thrown even if the actual size of the enumerable is very small and the operation could (in theory) complete.

### Reproduction Steps

```
new[] { 1 }.Chunk(int.MaxValue).ToArray();
```

### Expected behavior

Returns a single element enumerable with a single chunk array of length 1.

### Actual behavior

Throws `OutOfMemoryException` due to attempting to allocate a large array.

### Configuration

.NET 6, VS2022, Windows 10 x64.

### Other information

One could argue that this shouldn't be fixed because callers just shouldn't ask for chunks that large. However, this can come up when using `int.MaxValue` as a means of "disabling" chunking/batching, especially when said batching is performed deeper in the call stack.

A fix for this would be to special case the creation of the first chunk when size is above a certain threshold. For large sizes, we can assume that the chunk probably won't fill and therefore we can build up to the full size (as is done for `ToArray()` rather than starting by trying to allocate the final array).

**Comment by EgorBo** [comment]
> However, this can come up when using int.MaxValue as a means of "disabling" chunking/batching

Technically Chunk can operate on data longer than int.MaxValue, e.g. "infinite" iterator and we don't know input's Length in advance

**Comment by madelson** [comment]
> Technically Chunk can operate on data longer than int.MaxValue

True, hence the quotes around disabling. That said there are plenty of scenarios where you know that the upper bound is less than int max (e. g. if the original source was a collection).

> The best that we can do is to check input IEnumerable whether it's some known type of array/list we can query Length/Count from

I agree that there's nothing we can do about the general case of > ArrayMax elements in source with size > ArrayMax. However, if it is *desirable* that Chunk() should succeed in scenarios where there are <= ArrayMax elements with size > ArrayMax that is achievable.

**Comment by EgorBo** [comment]
>  That said there are plenty of scenarios where you know that the upper bound is less than int max (e. g. if the original source was a collection).

Want to file a PR with this change? (If BCL folks aren't against this idea)

**Comment by eiriktsarpalis** [comment]
Is this a real problem one would encounter though? It sounds to me like we'd be making the method slower for everyone simply to make it better behaved in a pathological scenario. Throwing OOM seems like an appropriate behavior (since most likely it's caused by a user bug).

**Comment by eiriktsarpalis** [comment]
> However, this can come up when using int.MaxValue as a means of "disabling" chunking/batching, especially when said batching is performed deeper in the call stack.

So you're suggesting we special-case `int.MaxValue` as infinity rather than checking if the source count is less than the `size` parameter in the special case? Is there precedent for that in other APIs?

**Comment by EgorBo** [comment]
> we'd be making the method slower for everyone simply to make it better behaved in a pathological scenario

I think it's not a pathological scenario, e.g. `new int[] {1,2,3}.Chunk(1000)` where it will allocate an int[1000] while it could just pay a little of perf for casts and allocate only `int[3]`.

**Comment by Tornhoof** [comment]
You could always use the fancy new ``TryGetNonEnumeratedCount`` to see if you can optimize the chunk before allocating the full size in the fallback.

**Comment by eiriktsarpalis** [comment]
> I think it's not a pathological scenario, e.g. new int[] {1,2,3}.Chunk(1000) where it will allocate an int[1000] while it could just pay a little of perf for casts and allocate only int[3].

Sure, but it's not pay for play. Now you're forcing every call to invoke `TryGetNonEnumeratedCount` even though this method is mostly used in Rx-style streaming applications where `source` is typically not a collection and `size` is typically a constant parameter.

**Comment by madelson** [comment]
> Is this a real problem one would encounter though?

@eiriktsarpalis for context, we've have had this utility method in our internal utility for years and I was looking to replace it with `Chunk()`. Our version handles the "large size" use case because we found that developers expected to be able to "turn off" chunking inline by passing a large value and were surprised that the implementation would actually insist on pre-allocating arrays of the chunk size regardless of how large it was. Encountering an `OutOfMemoryException` when the application is not actually out of memory can add additional confusion.

For example, imagine a function like this that uses `Chunk` internally:

```
void CreateRecords(IEnumerable<...> items, ..., int maxBatchSize);
```

> So you're suggesting we special-case int.MaxValue as infinity

I wouldn't propose special-casing int max. I think there is something to be said for the method returning successfully in cases where it can do so. Based on the description of what `Chunk()` does, calling it with `Count()` <= ArrayMax seems like it should always succeed (provided sufficient memory); the fact that it doesn't is due to the specifics of the implementation.

> Is there precedent for that in other APIs?

`Skip()` and `Take()` both work as expected with int max and the code makes a point of supporting this (see https://source.dot.net/#System.Linq/System/Linq/Partition.SpeedOpt.cs,304 and https://source.dot.net/#System.Linq/System/Linq/Partition.SpeedOpt.cs,421). It's not exactly the same thing, just philosophically similar. I'd be willing to bet that 99% of people calling `.Take(int.MaxValue)` are doing it to "take everything" vs. actually working with more than int max elements.

> It sounds to me like we'd be making the method slower ... it's not pay for play

I'm imagining that any special handling would come into play only when `size` is above a certain threshold. Anyone below the threshold wouldn't pay the cost other than the single integer comparison.

If the threshold were ArrayMax, then there is effectively no cost because the method always fails in that case currently.

Possibly there are lower thresholds where the cost of allocating memory upfront when it often won't all be used is worse than the cost of having to grow the array when the memory will be used.

> Want to file a PR with this change? (If BCL folks aren't against this idea)

Sure, provided there is a path forward that all are happy with (doesn't seem like the case currently).

**Comment by eiriktsarpalis** [comment]
>  If we think there's a meaningful number of cases where the input's size can be determined up front and where it'd be smaller than the specified chunk size, adding a fast-path that just handles a single chunk seems ok. (It'd be good to validate the perf impact, though, regardless.)

I have concerns about that, `source.Chunk(int.MaxValue)` will have different observable behaviour depending on whether `source` is countable or not (successfully returning a single chunk vs throwing OOM). That sounds like a violation of LSP to me. 

We might want to consider solving the issue in the general case using `List<T>` to build the chunks. It would result in a few additional allocations/copying but like you said the ship has sailed when it comes to peformance. It might look like the following (NB this hasn't been tested):
```C#
	private static IEnumerable<TSource[]> ChunkIterator<TSource>(IEnumerable<TSource> source, int size)
	{ 
		using IEnumerator<TSource> e = source.GetEnumerator();
		
		if (e.MoveNext())
		{
			var chunkBuilder = new List<TSource>(Math.Min(size, 1024)); // some cutoff constant after which resizes are acceptable.
			
			do
			{
				chunkBuilder.Add(e.Current);

				int i = 1;
				for (; i < size && e.MoveNext(); i++)
				{
					chunkBuilder.Add(e.Current);
				}

				yield return chunkBuilder.ToArray();

				if (i == size)
				{
					chunkBuilder.Clear();
				}
				else
				{
					yield break;
				}
			}
			while (e.MoveNext());
		}
	}
```

**Comment by stephentoub** [comment]
> will have different observable behaviour 

FWIW, there are tons of things LINQ does dynamically based on the input source that have observable behavior, e.g. using a source's `ICollection<T>` interface rather than its `IEnumerable<T>` interface if it implements that interface.

**Comment by eiriktsarpalis** [comment]
Sure, but don't these primarily concern performance or perhaps impacting lambdas containing side-effects? This seems like divergence of a different order.

**Comment by stephentoub** [comment]
> Sure, but don't these primarily concern performance or perhaps impacting lambdas containing side-effects?

If a source's `IEnumerable<T>` does something functionally different from its `ICollection<T>`, that's a pretty observable difference.  For example, these optimizations are the reason the concurrent collections don't necessarily play well with Enumerable.ToArray: if it were just always enumerating with `IEnumerable<T>`, no problem, but when it checks for `ICollection<T>`, it uses `Count` and `CopyTo`, which could blow up if additional items are added to the collection between the two calls.

**Comment by madelson** [comment]
> We might want to consider solving the issue in the general case using List<T> to build the chunks

@eiriktsarpalis can't you (to some degree) have your cake and eat it too if you use the existing logic for size < X and the list logic for size > X?

> different observable behaviour depending on whether source is countable or not

FWIW, as a consumer of this API I would prefer that it either consistently works or consistently doesn't in particular scenarios. I see the countable special-case as an implementation option *if* it is decided that avoiding OOM for large chunks is desirable.

**Comment by GSPP** [comment]
I have encountered this, and I've done the "disabling". In my own utility method I make sure to not eagerly allocate large arrays.

It's not just about OOM. It's undesirable to allocate a 1 million element array if the actual sequence is just a few items. Let's say you batch database inserts 1 million items at a time but it is common to have just a few.

Special-casing `int.MaxValue` is not necessary and not a sufficient fix. There should be an upper bound on the internal array allocation. You could argue for something as low as 4 (optimize for small actual item counts) and as something as high as 64000 (just prevent massive allocations that turn out to be unnecessary).

It's a difficult choice to make but, from my experience, large arguments and small item counts are a very real scenario.

**Comment by eiriktsarpalis** [comment]
I wouldn't be opposed to a solution that reverts to using a list when `size` exceeds a given threshold. It might help running benchmarks to determine the appropriate cutoff.

**Comment by stephentoub** [comment]
> I wouldn't be opposed to a solution that reverts to using a list when size exceeds a given threshold. It might help running benchmarks to determine the appropriate cutoff.

If we're going to do that, I'd prefer we just keep it simple and always do that, regardless of the chunk size specified.

**Comment by madelson** [comment]
Created https://github.com/dotnet/runtime/pull/67210 to demonstrate the behavior I'm imagining. The idea is to special-case just the first chunk because that's where you run into the large size, small source edge-case.

**Comment by stephentoub** [comment]
> The idea is to special-case just the first chunk because that's where you run into the large size, small source edge-case.

It's not worth special-casing, nor do we have an ability to pick the right threshold... no matter what we pick, issues like this one will say it's improper. If we're going to change the cure to use a list, we should just always use a list.

**Comment by progalgo** [comment]
I think the real problem here is API design. Wouldn't it be better if `Chunk` returned `IEnumerable<IEnumerable<TSource>>` instead?

**Comment by stephentoub** [comment]
> I think the real problem here is API design. Wouldn't it be better if Chunk returned IEnumerable<IEnumerable<TSource>> instead?

This was discussed in the API review:
https://youtu.be/efvl_wtYSw8?t=4377

Effectively sticking with `T[]` was a decision that this is not a super high-performance method.  We thus shouldn't bend over backwards now to try to make it so given the chosen shape.  We can do little tweaks to make it better, but if we're allocating a new large array for every chunk, we've already given up the biggest possible wins.
