### ISSUE TITLE
[API Proposal]: Possibility to specify a custom naming for appsettings.json files

### ISSUE THREAD

**Issue by bstordrup** [dotnet/runtime#67142]
### Background and motivation

If you have a scenario where multiple projects build into the same output folder, then you may end up in a file collision with appsettings.json being overwritten from the last project being build.

However, this could be handled by providing a mechanism for alternate naming of the appsettings.json files. For example by using the project name in the file name - like $(ProjectName).settings.json

### API Proposal

Add a new parameter on Host class static methods:

```C#
namespace Microsoft.Extensions.Hosting
{
    public static class Host
    {
        // New parameter
        public static IHostBuilder CreateDefaultBuilder(string[] args, bool useAppNameForSettings)
        {
            HostBuilder builder = new();
            // Pass new parameter on
            return builder.ConfigureDefaults(args, useAppNameForSettings);
        }

        // New Parameter - and passing it on
        public static HostApplicationBuilder CreateApplicationBuilder(string[]? args, bool useAppNameForSettings = false) => new  HostApplicationBuilder(args, useAppNameForSettings);
    }
}
```

and then in the HostingHostBuilderExtentions change the function like this:

```C#
namespace Microsoft.Extensions.Hosting
{
    public static class HostingHostBuilderExtensions
    {
        // New parameter
        public static IHostBuilder ConfigureDefaults(this IHostBuilder builder, string[] args, bool useAppNameForSettings)
        {
            return builder.ConfigureHostConfiguration(config => ApplyDefaultHostConfiguration(config, args))
                          // Passing new parameter on
                          .ConfigureAppConfiguration((hostingContext, config) => ApplyDefaultAppConfiguration(hostingContext, config, args, useAppNameForSettings))
                          .ConfigureServices(AddDefaultServices)
                          .UseServiceProviderFactory(context => new DefaultServiceProviderFactory(CreateDefaultServiceProviderOptions(context)));
        }

        // New parameter
        internal static void ApplyDefaultAppConfiguration(HostBuilderContext hostingContext, IConfigurationBuilder appConfigBuilder, string[] args, bool useAppNameForSettings)
        {
            IHostEnvironment env = hostingContext.HostingEnvironment;
            bool reloadOnChange = GetReloadConfigOnChangeValue(hostingContext);
            // Resolve appsettingBaseName
            string appsettingBaseName = useAppNameForSettingsFile 
                ? $"{System.Reflection.Assembly.GetEntryAssembly().GetName().Name}.settings"
                : "appsettings"

            // Apply the resolved appsettingBaseName
            appConfigBuilder.AddJsonFile($"{appsettingBaseName}.json", optional: true, reloadOnChange: reloadOnChange)
                    .AddJsonFile($"{appsettingBaseName}.{env.EnvironmentName}.json", optional: true, reloadOnChange: reloadOnChange);

            if (env.IsDevelopment() && env.ApplicationName is { Length: > 0 })
            {
                var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                if (appAssembly is not null)
                {
                    appConfigBuilder.AddUserSecrets(appAssembly, optional: true, reloadOnChange: reloadOnChange);
                }
            }

            appConfigBuilder.AddEnvironmentVariables();

            if (args is { Length: > 0 })
            {
                appConfigBuilder.AddCommandLine(args);
            }

            [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2026:RequiresUnreferencedCode", Justification = "Calling IConfiguration.GetValue is safe when the T is bool.")]
            static bool GetReloadConfigOnChangeValue(HostBuilderContext hostingContext) => hostingContext.Configuration.GetValue("hostBuilder:reloadConfigOnChange", defaultValue: true);
        }
    }
}
```

Add a property to the HostApplicationBuilderSettings class:

```C#
namespace Microsoft.Extensions.Hosting
{
    public sealed class HostApplicationBuilderSettings
    {
        // New property
        public bool UseAppNameForSettings { get; set; }
    }
}
```

And for the HostApplicationBuilder make these changes

```C#
namespace Microsoft.Extensions.Hosting
{
    public sealed class HostApplicationBuilder
    {
        // New parameter - and passed on to instantiated class
        public HostApplicationBuilder(string[]? args, bool useAppNameForSettings = false)
            : this(new HostApplicationBuilderSettings { Args = args, UseAppNameForSettings })
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HostApplicationBuilder"/>.
        /// </summary>
        /// <param name="settings">Settings controlling initial configuration and whether default settings should be used.</param>
        public HostApplicationBuilder(HostApplicationBuilderSettings? settings)
        {
            settings ??= new HostApplicationBuilderSettings();
            Configuration = settings.Configuration ?? new ConfigurationManager();

            if (!settings.DisableDefaults)
            {
                HostingHostBuilderExtensions.ApplyDefaultHostConfiguration(Configuration, settings.Args);
            }

            // HostApplicationBuilderSettings override all other config sources.
            List<KeyValuePair<string, string?>>? optionList = null;
            if (settings.ApplicationName is not null)
            {
                optionList ??= new List<KeyValuePair<string, string?>>();
                optionList.Add(new KeyValuePair<string, string?>(HostDefaults.ApplicationKey, settings.ApplicationName));
            }
            if (settings.EnvironmentName is not null)
            {
                optionList ??= new List<KeyValuePair<string, string?>>();
                optionList.Add(new KeyValuePair<string, string?>(HostDefaults.EnvironmentKey, settings.EnvironmentName));
            }
            if (settings.ContentRootPath is not null)
            {
                optionList ??= new List<KeyValuePair<string, string?>>();
                optionList.Add(new KeyValuePair<string, string?>(HostDefaults.ContentRootKey, settings.ContentRootPath));
            }
            if (optionList is not null)
            {
                Configuration.AddInMemoryCollection(optionList);
            }

            (HostingEnvironment hostingEnvironment, PhysicalFileProvider physicalFileProvider) = HostBuilder.CreateHostingEnvironment(Configuration);

            Configuration.SetFileProvider(physicalFileProvider);

            _hostBuilderContext = new HostBuilderContext(new Dictionary<object, object>())
            {
                HostingEnvironment = hostingEnvironment,
                Configuration = Configuration,
            };

            Environment = hostingEnvironment;

            HostBuilder.PopulateServiceCollection(
                Services,
                _hostBuilderContext,
                hostingEnvironment,
                physicalFileProvider,
                Configuration,
                () => _appServices);

            Logging = new LoggingBuilder(Services);

            ServiceProviderOptions? serviceProviderOptions = null;

            if (!settings.DisableDefaults)
            {
                HostingHostBuilderExtensions.ApplyDefaultAppConfiguration(_hostBuilderContext, Configuration, settings.Args, UseAppNameForSettings);
                HostingHostBuilderExtensions.AddDefaultServices(_hostBuilderContext, Services);
                serviceProviderOptions = HostingHostBuilderExtensions.CreateDefaultServiceProviderOptions(_hostBuilderContext);
            }

            _createServiceProvider = () =>
            {
                // Call _configureContainer in case anyone adds callbacks via HostBuilderAdapter.ConfigureContainer<IServiceCollection>() during build.
                // Otherwise, this no-ops.
                _configureContainer(Services);
                return serviceProviderOptions is null ? Services.BuildServiceProvider() : Services.BuildServiceProvider(serviceProviderOptions);
            };
        }
    }
}
```

### API Usage

```C#
// Use the application name for settings file
IHost host = Host.CreateDefaultBuilder(args, true)
    .ConfigureServices(services =>
    {
        services.AddHostedService<Worker>();
    })
    .Build();

await host.RunAsync();
```

**Comment by gfoidl** [comment]
With `HostBuilder.ConfigureAppConfiguration` you can add "custom configuration" like json files named as you like. Cf. [[](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#file-configuration-provider)File configuration provider](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#file-configuration-provider).

For a similar scenario as you outlined, I created a custom host, that "bootstraps" the default HostBuilder, so this type is able to setup the correct filenames for config, etc.

**Comment by bstordrup** [comment]
> With `HostBuilder.ConfigureAppConfiguration` you can add "custom configuration" like json files named as you like. Cf. [File configuration provider](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration-providers#file-configuration-provider).
> 
> For a similar scenario as you outlined, I created a custom host, that "bootstraps" the default HostBuilder, so this type is able to setup the correct filenames for config, etc.

Does it also remove the providers for `appsettings.json` that I don't want to be in the config sources? Or would I have to manually remove these after they have been added.

My suggestion would make the default builder decide whether to use `appsettings.json` or a custom name based on project name without you having to fiddle with the config sources afterwards.

**Comment by davidfowl** [comment]
You can call Clear on the builder and add the configuration source. There doesn't need a be a new API for this.

**Comment by bstordrup** [comment]
> You can call Clear on the builder and add the configuration source. There doesn't need a be a new API for this.

Yes, but that seems a bit strange for me to have to do if it could be prevented by a setting. And it also removes all other configuration sources being added by the default builder.

**Comment by davidfowl** [comment]
The options feels like too strange of a scenario to make a first class option. Top level APIs are for ubiquitous scenarios and the rest of the APIs are flexible enough to allow things to be overridden. IMO, this doesn't meet the bar for a top level API, but its possible I'm wrong and others are doing this, either way, we'll need to see more feedback.

As an alternative, consider mutating the existing configuration sources on the default, or, not using the defaults and building your own configuration hierarchy (using `new HostBuilder`)

**Comment by maryamariyan** [comment]
>  There doesn't need a be a new API for this.

Seems like this can be closed.

**Comment by bstordrup** [comment]
> The options feels like too strange of a scenario to make a first class option.

Why is this a strange scenario?

Consider a solution with three projects all having each an appsettings.json. Each project has its own unique settings, and some in common.

You set these to build to the same output folder because you will be distributing these three projects as a combined package.

Since they all have files named appsettings.json, the last project build will be the one with the appsettings.json being put in the output folder - meaning that the other two projects will not have the appsettings.json, they expect. Ultimately, they will be missing their unique settings in the appsettings.json file.

This could be solved with this approach where you in each project can specify that it should use the appname for resolving the appsettings.json file name - it would look for at file named $(ProjectName).settings.json instead of appsettings.json, and this way, all three projects would be able to build to same output folder without overwriting the other projects appsettings.json values.

Even if you do not build into a common output folder, the issue also arises when you deploy, if you deploy them to the same folder. The last one being deployed would overwrite the others appsettings.json.

I think you can also compare it to the handling of the app.config file in projects - when the project is being build, this file is copied to the output folder under the name $(ProjectName).exe.config, and the application needing it would look for it under that name. Why should this not be possible for the appsettings.json.

**Comment by davidfowl** [comment]
> Why is this a strange scenario?

Strange is the wrong word. Uncommon is more like it.
