### ISSUE TITLE
fannkuch-redux-9 fails on many core computers

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#67157]
fannkuch-redux-9 will currently fail for computers that have many cores. It is currently deriving the number of threads from `Environment.ProcessorCount` and on a Ryzen 5950X this is `32`.

A simple fix would be to restrict this to no more than `8` as the official `Benchmarks Game` hardware is currently a 4-core machine with hyperthreading:
> Quad-core 3.0GHz Intel® i5-3330® with 15.8 GiB of RAM and 2TB SATA disk drive; using Ubuntu™ 21.10 x86_64 GNU/Linux 5.13.0-28-generic.

Ideally the logic would be updated to work on machines with any core count, but that likely requires more in depth analysis to determine where exactly the bug exists.

**Comment by danmoseley** [comment]
This test is owned by codegen team.

**Comment by JulieLeeMSFT** [comment]
We discussed this today.
@kunalspathak PTAL.
CC @dotnet/jit-contrib @mangod9.

**Comment by kunalspathak** [comment]
@tannergooding - What errors did you see? I just ran it on 52 core machine and it seems to work fine.

**Comment by tannergooding** [comment]
It just fails because the computed result is incorrect:
> Failed test: JIT_Performance::_CodeQuality_BenchmarksGame_fannkuch_redux_fannkuch_redux_9_fannkuch_redux_9_cmd (JIT\\Performance\\CodeQuality\\BenchmarksGame\\fannkuch-redux\\fannkuch-redux-9\\fannkuch-redux-9.cmd)
> 
> Return code:      1
> Raw output file:      C:\Users\tagoo\source\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Reports\JIT.Performance\CodeQuality\BenchmarksGame\fannkuch-redux\fannkuch-redux-9\fannkuch-redux-9.output.txt
> Raw output:
> BEGIN EXECUTION
>  "C:\Users\tagoo\source\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  fannkuch-redux-9.dll
> 21
> Pfannkuchen(7) = 16
> Expected: 100
> Actual: -107
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1
> To run the test:
> > set CORE_ROOT=C:\Users\tagoo\source\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root
> > C:\Users\tagoo\source\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\JIT\Performance\CodeQuality\BenchmarksGame\fannkuch-redux\fannkuch-redux-9\fannkuch-redux-9.cmd

Restricting the core count to 8 allows it to pass. I didn't test other core counts.

**Comment by AndyAyersMS** [comment]
I think some other tests have similar issues. We should feel free to modify the copies in the runtime repo as long as we don't substantially alter their logic.
