### ISSUE TITLE
ReadAtLeastAsync(0) has a surprising behavior

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#67155]
### Description

Hello ~
Sometimes the `PipeReader.ReadAtLeastAsync(0)` will block until new data comes, and sometimes, it returns immediatly a new buffer.

### Reproduction Steps

```csharp
[Test]
public void MemoryStreamPipeReader_ReadAtLeastAsync0() //Pass
{
    MemoryStream mem = new();
    var piperReader = PipeReader.Create( mem );
    ValueTask<ReadResult> task = piperReader.ReadAtLeastAsync( 0 );
    task.IsCompleted.Should().BeTrue();
}

[Test]
public void DefaultPipeReader_ReadAtLeastAsync0() //Fail
{
    var pipe = new Pipe();
    var piperReader = pipe.Reader;
    ValueTask<ReadResult> task = piperReader.ReadAtLeastAsync( 0 );
    task.IsCompleted.Should().BeTrue();
}

[Test]
public void NetworkStreamPipeReader_ReadAtLeastAsync0() //Fail
{
    TcpListener listener = new(IPAddress.Any, 3712);
    listener.Start();
    var incomingClient = listener.AcceptTcpClientAsync();
    TcpClient client = new("localhost", 3712);
    var serverClient = await incomingClient;
    var stream = client.GetStream();
    var pipeReader = PipeReader.Create(stream);
    var task = pipeReader.ReadAtLeastAsync(0);
    
    var serverStream = serverClient.GetStream();
    await serverStream.FlushAsync();
    
    await task.IsCompleted.Should().BeTrue();
}
```

### Expected behavior

I think `PipeReader.ReadAtLeastAsync(0)` should always return immediatly, returning an empty buffer when there is no data immediatly available in the buffer.

The behavior is surprising, because if the last part of a message you are parsing can have a length of 0, call ReadAtLeastAsync(0) will block until there is more data which is a serious bug.

For example, a code I had written in my MQTT Client: 

```csharp
public async ValueTask HandleMessageAsync( string topic, PipeReader pipe, uint payloadLength, QualityOfService qos, bool retain, CancellationToken cancelToken )
{
    Memory<byte> buffer = new byte[payloadLength];
    ReadResult readResult = await pipe.ReadAtLeastAsync( (int)payloadLength, cancelToken );
    readResult.Buffer.Slice( 0, (int)payloadLength ).CopyTo( buffer.Span );
    pipe.AdvanceTo( readResult.Buffer.Slice( Math.Min( payloadLength, readResult.Buffer.Length ) ).Start );
    await _messageHandler( null, new ApplicationMessage( topic, buffer, qos, retain ), cancelToken );
}
```
As you can see there, if the buffer returned is empty, it works without any issue:
- Slicing 0 bytes on a sequence return an empty sequence.
- AdvanceTo of 0 bytes lead to no error.

Blocking mean the zero length payload become an edge case to handle there, while the idiomatic use of the PipeReader wouldn't lead to any bug.

### Actual behavior

DefaultPipeReader.ReadAtLeastAsync(0) is blocking until there is data available in the Pipe.
StreamPipeReader.ReadAtLeastAsync(0) return immediatly an empty buffer with a MemoryStream.
StreamPipeReader.ReadAtLeastAsync(0) is blocking until there is data available with a NetworkStream.

### Known Workarounds

Avoid reading if the length to read is 0.

**Comment by olivier-spinelli** [comment]
My 2 (breaking?) cents: 0 SHOULD throw an ArgumentException. 
It is semantically invalid: "I'm waiting for 0 bytes" is meaningless. A parallel can even be made with the divide by 0 case: "I want my stream to be broken in 0 length parts".

**Comment by fbrosseau** [comment]
> My 2 (breaking?) cents: 0 SHOULD throw an ArgumentException.

0-byte reads are a very important part of large scale stuff like aspnetcore, where you do not want to commit buffers to each and every connection. You want to submit an empty read, and when something does show up, _then_ you supply a buffer and read again for the actual payload. It results in more system calls, but it scales better in terms of memory for a large number of concurrent streams that may be mostly idle. It's a trade off, but with very real benefits.

For original question, MemoryStream is always able to satisfy all reads synchronously, whether it still has data between `Position` and `Length`, or here, where it is at EOF. The sample code is invalid, for a fair comparison, you would need to use a stream that's unable to complete the read synchronously, such as a an idle networkstream.

**Comment by olivier-spinelli** [comment]
But... the basic `ReadAsync()` is here precisely for this behavior, isnt' it?

**Comment by fbrosseau** [comment]
> But... the basic ReadAsync() is here precisely for this behavior, isnt' it?

Indeed, but I would think it would be _more_ surprising if ReadAtLeastAsync diverged from it.

**Comment by Kuinox** [comment]
What is surprising is that ReadAtLeast(0) block until data is available. If your payload is at the end of a message, and is zerosized, you are blocked until the next message come.

**Comment by olivier-spinelli** [comment]
Sorry but for me this is exactly what an API design work is: defining semantics that makes sense.
`ReadAsync()` does this and reading such code is fine.

`ReadAtLeastAsync( len )` where `len` can be 0... Good luck to both the writer AND the readers!

**Comment by Kuinox** [comment]
@fbrosseau I have updated the issue with your input.

**Comment by halter73** [comment]
It seems like you want `ReadAsync(0)` be behave more like [TryRead](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.tryread?view=dotnet-plat-ext-6.0) rather than `ReadAsync()` without an argument. Does `TryRead` fit your use case?

As for the difference between `StreamPipeReader` with a `NetworkStream` and `MemoryStream`, I think that's just a matter of the behavior of the backing `Stream`. `MemoryStream` always returns immediately for reads so there nothing ever to await even if there was a non-zero minimum read length.

**Comment by Kuinox** [comment]
My objective here is not to use ReadAtLeastAsync(0) as a TryRead, but to avoid the, dangerous, current behavior that lead to a bug when you read a variable sized field at the end of a message.
You can see how someone can easily get caught by this bug in the example I gave in Expected Behavior.  
I don't see another reason to call ReadAtLeastAsync(0) than in the use case I gave.

**Comment by Clockwork-Muse** [comment]
> What is surprising is that ReadAtLeast(0) block 

You keep saying "block".  Which of these do you mean:
 - The call to `ReadAtLeastAsync` doesn't return at all until there is data to read (this is normally what would be meant by "block", and is antithetical to `async` code).
 - The call to `ReadAtLeastAsync` returns a `Task` immediately, but it isn't (guaranteed to be) complete, and must be `await`ed.

This first should probably be considered a bug.
The second is reasonable behavior, since you're waiting for a network event.

> when you read a variable sized field at the end of a message.

Read-until-hangup (assuming you're not that far down the stack to be reading the hangup message) would cancel/abort the read.
A length-prefixed field would have a known length you could/would use.

So presumably you're reading until a delimiter.  So why aren't you reading at least one byte?

**Comment by Kuinox** [comment]
> You keep saying "block". Which of these do you mean:

Of course here I mean that it return a `ValueTask<T>` immediatly, but it's the resolution of this ValueTask that has an error prone behavior.  

> The second is reasonable behavior, since you're waiting for a network event.  

I'm not waiting for a network event, the semantic of the API says that I'm waiting that 0 bytes are available.  

>  A length-prefixed field would have a known length you could/would use.  

The example I gave in the issue is length prefixed, `uint payloadLength` is the length of the payload parsed in the header.  
The issue is that the length of this payload can be 0.

**Comment by Clockwork-Muse** [comment]
> I'm not waiting for a network event, the semantic of the API says that I'm waiting that 0 bytes are available.

It's "at least" 0.  But that's not really what's at issue here.  The actual network stream has a reasonable interest in validating that it's still "live", and you just asked to be notified when there were more bytes available, and there was an update to the pipe's status.  

For the tests you've provided:
 - For the default `Pipe` test, you almost certainly need to [`CompleteAsync()`](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.completeasync?view=dotnet-plat-ext-6.0).
 - For the `NetworkStream` test, I'm not sure whether `FlushAsync()` will generate a network event if there have been no writes.  What happens if you explicitly write zero bytes?

> The issue is that the length of this payload can be 0.

There's apparently a [`UseZeroByteReads` option](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.streampipereaderoptions.usezerobytereads?view=dotnet-plat-ext-6.0), have you tried passing the options with that unset?

Trivial workaround: don't issue reads for items of length 0 (just call the handler callback).  You're trading some liveliness checking, but presumably you're going to have a non-zero read soon.

**Comment by Kuinox** [comment]
>  you just asked to be notified when there were more bytes available  

I asked to be notified when there was at least *0* bytes availables: It's always the case !  

> For the default Pipe test, you almost certainly need to [CompleteAsync()](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipewriter.completeasync?view=dotnet-plat-ext-6.0).   

I don't understand what you are saying, this issue has nothing to do with the EndOfStream, the issue is all about the fact that the line is still open, and ReadAtLeastAsync(0) will block until a new message comes in.  

> For the NetworkStream test, I'm not sure whether FlushAsync() will generate a network event if there have been no writes. What happens if you explicitly write zero bytes?  

It doesn't release ReadAtLeast(0), it need to have at least a single byte passing.   

> There's apparently a [UseZeroByteReads option](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.streampipereaderoptions.usezerobytereads?view=dotnet-plat-ext-6.0), have you tried passing the options with that unset?   

This allow `ReadAsync` to return 0 length buffer, which is not the behavior I want.  

> Trivial workaround: don't issue reads for items of length 0 (just call the handler callback). You're trading some liveliness checking, but presumably you're going to have a non-zero read soon.  

This is the workaround I wrote in my issue. FYI this issue is unrelated to zero bytes reads thats were introduced in .NET 6. It's simply a behavior specific to ReadAtLeastAsync which causes issues.

**Comment by adityamandaleeka** [comment]
Triage: closing this issue since we don't believe there is anything to do here. @halter73 posted a workaround above that seems sufficient.

**Comment by Kuinox** [comment]
>  @halter73 posted a workaround above that seems sufficient.  

I think @halter73 missunderstood the issue since 
> It seems like you want ReadAsync(0) be behave more like [TryRead](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipereader.tryread?view=dotnet-plat-ext-6.0) rather than ReadAsync() without an argument. Does TryRead fit your use case?

Was not at all my use case.  
The problem to me, is that if you have a variable length payload at the end of a message, the current behavior is a footgun that will lead to block the reading until further data come, which will cause the last message to be stuck in "await ReadAtLeastAsync(0)"

The workaround was always very simple and I wrote it in the issue, the issue is that other people, like me, will write a bug by accident due to the current behavior.

**Comment by adityamandaleeka** [comment]
Triage: we should doc this so people know not to pass 0 into `ReadAtLeastAsync`. We don't intend to change the behavior itself.

**Comment by wtgodbe** [comment]
Need to update https://github.com/dotnet/runtime/blob/9d972eda4da654dfafae101e9850b1191a4dcbf9/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/PipeReader.cs#L34-L39

**Comment by wtgodbe** [comment]
https://github.com/dotnet/runtime/pull/69217
