### ISSUE TITLE
`Libraries Test Run checked coreclr OSX x64 Debug` failing to unzip test assets

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#67159]
[Log](https://dev.azure.com/dnceng/public/_build/results?buildId=1681270&view=logs&jobId=36cb984e-94a7-57b7-c622-11a2d915b2f3&j=36cb984e-94a7-57b7-c622-11a2d915b2f3&t=a29373ee-1fe5-591c-dcc1-1a11049e8d6a).

```
##[error]Extraction failed for file: /Users/runner/work/1/s/__download__/libraries_test_assets_OSX_x64_Debug/libraries_test_assets_OSX_x64_Debug.tar.gz 
code: 1 
stdout:  
stderr: x helix/

...

x helix/tests/OSX.AnyCPU.Debug/LibraryImportGenerator.Unit.Tests.zip: gzip decompression failed
tar: Error exit delayed from previous errors.
 
error: undefined;

...

x helix/tests/OSX.AnyCPU.Debug/LibraryImportGenerator.Unit.Tests.zip: gzip decompression failed
tar: Error exit delayed from previous errors.
Error: Extraction failed for file: /Users/runner/work/1/s/__download__/libraries_test_assets_OSX_x64_Debug/libraries_test_assets_OSX_x64_Debug.tar.gz 
code: 1 
stdout:  
stderr: x helix/
```

**Comment by danmoseley** [comment]
Here's where the tarring and upload is.
https://github.com/dotnet/runtime/blob/c2dbee1e3af4b7b0a74c192d51970633e8df2a37/eng/pipelines/common/upload-artifact-step.yml#L12

I see there's a verbose flag one can pass to ArchiveFiles.

The best idea I have is to modify that step so it unzips to dev null before uploading; and if that succeeds, then after uploading maybe downloads the blob itself and verifies its hash.

**Comment by danmoseley** [comment]
Well I clicked rerun failed jobs, in case you can't @vcsjones

**Comment by danmoseley** [comment]
@radical have you seen this happen since?

@MattGal is there any mechanism to grep recent build failure logs? I assume not.

**Comment by radical** [comment]
> @radical have you seen this happen since?

No

**Comment by MattGal** [comment]
> @radical have you seen this happen since?
> 
> @MattGal is there any mechanism to grep recent build failure logs? I assume not.

Yes, that's what https://runfo.azurewebsites.net/ is for.  I ping @jaredpar when I get stuck because he wrote it and it's possible to make a few different small mistakes and not find stuff.

I didn't see this when it happened a month ago but it's either a bad .tar.gz or a bad mac VM that has long, long ago been deleted so if it's not happening regularly (runfo can grep this for you) it's not worth your time to pursue IMO.

**Comment by danmoseley** [comment]
OK, thanks for the assessment.
