### ISSUE TITLE
Arm64: Environment.ProcessorCount returns wrong value on higher core machine

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#67180]
In https://github.com/dotnet/runtime/pull/45943, we did a breaking change to have `Environment.ProcessorCount` take processor affinity into account on Windows. It works well on x64 machines, but on arm64 machines with higher CPU count, it returns wrong value. 

Although https://github.com/dotnet/runtime/issues/47427, calls out that the code that relies on `Environment.ProcessorCount` for parallelism, should update it to scale better because of reduced return value. However, there is performance sensitive code in IOThreadPool that relies on `Environment.Processor` to decide on the number of "IO completion poller threads" to use in the application. 

https://github.com/dotnet/runtime/blob/32320b11c945c506c7b3d24d4dc16aa9b2119ac9/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.IO.Windows.cs#L41-L43

On higher core Arm64 machine, had `ProcessorCount` returned correct value, I could see that we would create more IO completion threads to handle more concurrent requests. In an internal application, I can see it boosts performance by `2.25X ` on higher core Arm64 machines.

**Comment by kunalspathak** [comment]
@kouvel @mangod9

**Comment by mangod9** [comment]
this looks to be hardware specific -- I couldnt repro on an arm64 VM with 32 cores.

**Comment by kunalspathak** [comment]
When I set `COMPlus_GCCpuGroup=1` and `COMPlus_Thread_UseAllCpuGroups=1` , it reports current number of cores.

**Comment by AntonLapounov** [comment]
I am helping @kunalspathak to debug this.

**Comment by AntonLapounov** [comment]
I can confirm the issue.  The program reports the incorrect value of `Environment.ProcessorCount` _every other_ run, which is certainly weird.

**Comment by mangod9** [comment]
hmm, interesting. Is this every other run of the process or subsequent calls in the same process? I dont seem to be able to repro it on a 32 core VM fyi.

**Comment by AntonLapounov** [comment]
The machine in question has two processor groups of different sizes. Unless you set environment variables to use all CPU groups, `Environment.ProcessorCount` returns the number of processors in the processor group the OS started the process on. Therefore, you may see different returned values from run to run and that is the expected behavior.

**Comment by mangod9** [comment]
ok that makes sense. Need to determine why there is an asymmetric config on that hardware.

**Comment by AntonLapounov** [comment]
According to [documentation](https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups#behavior-starting-with-windows-11-and-windows-server-2022), in Windows 11 processes are no longer constrained to a single processor group by default. I guess that means we should consider `UseAllCpuGroups` enabled by default, which would allow to avoid this issue.

**Comment by kunalspathak** [comment]
@AntonLapounov - any further update on this?

**Comment by AntonLapounov** [comment]
I have started discussion #67308 and an internal email thread with OS folks regarding this.  I assume you can set the environment variables as a workaround until we have a fix.

**Comment by janvorli** [comment]
@AntonLapounov can you please set the milestone of this issue to remove the untriaged label?

**Comment by mangod9** [comment]
@AntonLapounov @kunalspathak guess we dont plan on fixing for 7 right?

**Comment by AntonLapounov** [comment]
Yes, apps will have to opt-in to make all processor groups available to the runtime.

**Comment by kunalspathak** [comment]
Do we plan to include the documentation of the environment variable to use all processor groups for Windows 11/Windows server 2022?

**Comment by AntonLapounov** [comment]
Those configuration settings were introduced a long time ago and are already documented.  If you think the documentation should be improved, you may submit a documentation PR.

**Comment by kunalspathak** [comment]
>  If you think the documentation should be improved

They need to be certainly improved because of change in behavior on Win11 and with many-core machines are getting more common. Under what API/category should the documentation go to?

**Comment by jkotas** [comment]
> Under what API/category should the documentation go to?

Affected APIs should get a note:
- https://docs.microsoft.com/en-us/dotnet/core/runtime-config/threading#cpu-groups
- https://docs.microsoft.com/en-us/dotnet/api/system.environment.processorcount
- https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.processoraffinity

I suspect that we may still end up doing more product changes here given the feedback in https://github.com/dotnet/runtime/issues/72441. I would wait for that issue to get resolved before starting on documentation edits.

(If you have access to a Win2022 machine with large number of cores, it would be useful to get answer to https://github.com/dotnet/runtime/issues/72441#issuecomment-1189440332 .)
