### ISSUE TITLE
[API Proposal]: Parameters can be passed in when getting services from IServiceProvider

### ISSUE THREAD

**Issue by Linlccc** [dotnet/runtime#67185]
### Background and motivation

In some cases we want to pass in some parameters ourselves when getting an instance from `serviceProvider`, but we can't do that right now.
We now have the `ActivatorUtilities` static class,
However, in the `ActivatorUtilities.CreateInstance(IServiceProvider, Type , Object[])` method, although you can pass in parameters by yourself, the created instance is not managed by the scope of `IServiceProvider`, and the type passed in is the instance type
  The type obtained by the `ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider, Type)` method will be managed by the `IServiceProvider` scope if it has been registered, but you cannot pass in parameters yourself

### API Proposal

```C#
namespace Microsoft.Extensions.DependencyInjection;

public static class ServiceProviderServiceExtensions
{
    public static T GetRequiredService<T>(this IServiceProvider serviceProvider,params object[] arguments);
    public static  object GetService(this IServiceProvider serviceProvider, Type serviceType，params object[] arguments);
}
```

### API Usage

```C#
var services = new ServiceCollection();

services.AddTransient<IA,A1>();
services.AddTransient<IA,A2>();
services.AddTransient<B>();

ServiceProvider sp = services.BuildServiceProvider();

List<IA> @as = sp.GetServices<IA>().ToList();
B b1 = sp.GetService<B>(@as[0]);
B b2 = sp.GetService<B>(@as[1]);




public interface IA{}

public class A1 : IA
{
    
}
public class A2 : IA
{
    
}
public class B
{
    public B(IA a)
    {
        A = a;
    }
    public IA A { get; set; }
}
```

### Alternative Designs

No other ideas for now, but we can brainstorm

### Risks

There may be some problems with the cache when getting the service, but I don't know much about the current DI cache

**Comment by davidfowl** [comment]
Use ActivatorUtilities.CreateFactory for this. We shouldn’t be changing the core IServiceProvider interface isn’t worth the pain.

**Comment by Linlccc** [comment]
> Use ActivatorUtilities.CreateFactory for this. We shouldn’t be changing the core IServiceProvider interface isn’t worth the pain.

but Use `ActivatorUtilities.CreateFactory` the created instance is not managed by the scope of IServiceProvider

**Comment by davidfowl** [comment]
> Use ActivatorUtilities.CreateFactory for this. We shouldn’t be changing the core IServiceProvider interface isn’t worth the pain.

That's correct, you are responsible for disposal.

If you're asking for a first class API that is native supported by 3rd party containers as well as the built one then that's a different ask (and a much more impactful one at that). I'd wager a guess that it would be out of scope of something we would build in support for.

As a follow up question. Who owns the lifetime of disposable objects passed into the new overload you describe above?

**Comment by Linlccc** [comment]
What I think is that the life cycle of the one-time object is managed by the creator himself, or add and then overload one more parameter, try to add the one-time object to the current scope management
