### ISSUE TITLE
[API Proposal]: Enumerable.Order and OrderDescending

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#67194]
### Background and motivation

Linq provides `OrderBy` and `OrderByDescending` which implies that I'm sorting based on some part of the `T`. Very often I find myself wanting to just sort by the `T` itself.

### API Proposal

```C#
namespace System.Linq
{
    public partial class Enumerable
    {
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source) where T: IComparable<T>;
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source, IComparer<T> comparer);

        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source) where T: IComparable<T>;
        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source, IComparer<T> comparer);
    }
}
```

### API Usage

```C#
var data = new[] { 2, 1, 3 };

// Instead of
// var sorted = data.OrderBy(e => e);

var sorted = data.Order();

// Instead of
// var sortedDescending = data.OrderByDescending(e => e);

var sortedDescending = data.OrderDescending();
```

**Comment by kevingosse** [comment]
Shouldn't it return an `IOrderedEnumerable<T>` for consistency with `OrderBy`?

**Comment by petroemil** [comment]
Could they be called `Order` and `OrderDescending` instead, dropping the past tense "ed" from the names?

**Comment by stephentoub** [comment]
If we add this, I think the name should just be Order rather than Ordered.

**Comment by poke** [comment]
Maybe something explicit to avoid confusion with the existing methods: `OrderBySelf` and `OrderBySelfDescending` (`OrderByDescendingSelf`?)

Alternatively just `OrderBy()` without any argument, defaulting to an identity function? 🤔

**Comment by poke** [comment]
Maybe something explicit to avoid confusion with the existing methods: `OrderBySelf` and `OrderBySelfDescending` (`OrderByDescendingSelf`?)

Alternatively just `OrderBy()` without any argument, defaulting to an identity function? 🤔

**Comment by CamiloTerevinto** [comment]
I think it would make more sense to allow for any T too, just like the existing APIs:

```
    public partial class Enumerable
    {
        // source.OrderBy(x => x)
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source) where T: IComparable<T>;

        // source.OrderBy(x => x, comparer)
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source, IComparer<T> comparer);

        // source.OrderByDescending(x => x, comparer)
        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source) where T: IComparable<T>;

        // source.OrderByDescending(x => x, comparer)
        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source, IComparer<T> comparer)
    }
```

**Comment by zoran-horvat** [comment]
> Could they be called `Order` and `OrderDescending` instead, dropping the past tense "ed" from the names?

I agree, with a note that "Ordered" implies that the method will return data in some form, but does not communicate that there will be a substantial cost disproportional to size of the input. "Order" is suggesting that there is **_work_** behind constructing the result.

**Comment by ldardick** [comment]
> > Could they be called `Order` and `OrderDescending` instead, dropping the past tense "ed" from the names?
> 
> I agree, with a note that "Ordered" implies that the method will return data in some form, but does not communicate that there will be a substantial cost disproportional to size of the input. "Order" is suggesting that there is **_work_** behind constructing the result.

Adding up, I feel explicitly defining the critetia (`OrderAscending` and `OrderDescending`) feels more natural.

**Comment by andi0b** [comment]
So it more or less comes down to instead of calling a LINQ method with an identity function (`x=>x`) as parameter, just calling it without a parameter.

There are also other LINQ methods that could use this API change. For example `SelectMany(x=>x)`. But also `ToDictionary(x=>x.key, x=>x.value)` for a enumerable of tuples or KeyValuePairs

**Comment by Aldebaran91** [comment]
Better would be extending it by a property not by a method.

```csharp
var data = new[] { 2, 1, 3 };

var sorted = data.OrderBy();

// Check sort state.
bool result = sorted.Sorted;
bool result2 = sorted.SortedDescending;
```

**Comment by andi0b** [comment]
> Better would be extending it by a property not by a method.

AFAIK there are no extension properties in C#, and LINQ is all about extension methods.

**Comment by Aldebaran91** [comment]
@andi0b  well I forgot to mention I wouldn't implement it in Enumerable. Wrong place IMHO.

**Comment by Aldebaran91** [comment]
@andi0b forget what I posted early.

Oh and ... if I got the idea correct. So if I get an ordered Enumerable from database (or other source) and return "3" first. The next item is "2" but it can not be returned because otherwise the order would be broken. The logic from the proposal is like IEnumerable.ToList().OrderBy().

**Comment by terrajobst** [comment]
Updated proposal based on your feedback.

**Comment by Joe4evr** [comment]
> There are also other LINQ methods that could use this API change. For example `SelectMany(x=>x)`.

That almost happened (settled on the name `Flatten()`, but it didn't make the cut for .NET 6: #54220).

**Comment by IustinMicu** [comment]
> _If_ we add this, I think the name should just be Order rather than Ordered.

Funny how you posted this and got 8 likes, but someone who said the exact same thing (actually said it even better) before you got no reactions :))
Btw, why did you said something that he already said?

**Comment by terrajobst** [comment]
Can’t speak for @stephentoub but it usually happens to me due to overlap (ie while I’m typing someone posts before me).

**Comment by stephentoub** [comment]
> Btw, why did you said something that he already said?

We posted at the same time.

**Comment by IustinMicu** [comment]
I see. Please accept my apologies.
The fact that you and Immo explained this to me shows again how cool you guys are, and what a jerk I can be sometimes 😄

**Comment by ClosetBugSlayer** [comment]
> Alternatively just `OrderBy()` without any argument, defaulting to an identity function?

This is what I added to my own libraries years ago and it works fabulously. If it isn't an overload, it won't be discovered, and the programmer won't automatically assume it does the same general thing when reading the code. I am that programmer, speaking from experience.

**Comment by terrajobst** [comment]
> If it isn't an overload, it won't be discovered, and the programmer won't automatically assume it does the same general thing when reading the code.

In principle I agree. However, naming also matters. `OrderBy()` with nor arguments feels quite strange IMHO.

**Comment by jzabroski** [comment]
`.Sort()` uses `Comparer<T>.Default`, so there is some inconsistency here between the _mechanism_ method `Sort` and the _policy_ method `Order`

**Comment by EluciusFTW** [comment]
I find `Order` does not really express what it does, it does not really flow through the chain. I'd actually prefer `InAscendingOrder` and `InDescendingOrder`. I think that is most readable, and closest to natural language, in the same way as, e.g., `AsEnumerable`.

**Comment by stephentoub** [comment]
From my perspective, such a helper (to avoid `x => x`) barely rises to the level of something we should be adding. But if it's common enough that we decide to go ahead with it, it's definitely not worth inventing new patterns and naming. We already have the Verb and VerbBy naming pattern, with Max and MaxBy, Distinct and DistinctBy, Intersect and IntersectBy. Since we already have OrderBy, this should just be Order (and OrderDescending) to stay with the same pattern, as Immo's proposal now has. Introducing a new name/concept will be confusing with the existing methods and inconsistent with the rest of LINQ

**Comment by EluciusFTW** [comment]
@stephentoub I agree that this helper is not really necessary (and anyone can write it on his own, if he uses it a lot). I also understand the reasoning for the naming proposal, just wanted to throw another option out there. I don't agree that it goes against the semanitcs of LINQ, if you compare it to `AsEnumerable`, `AsQueryable`. By your argument, these should just have been called `Enumerable` and `Queryable`.

**Comment by rjgotten** [comment]
> I don't agree that it goes against the semanitcs of LINQ, if you compare it to `AsEnumerable`, `AsQueryable`. By your argument, these should just have been called `Enumerable` and `Queryable`.

I always thought the reason those are `As[..]` are to juxtapose with `To[..]` as in `ToArray` et al.
The 'to' implies actual work in converting the data; the 'as' is more of a reinterpretation, wrapping or cast of the existing data.

**Comment by andi0b** [comment]
`First()` or `SingleOrDefault()` and similar functions have the parameterless overload.

Calling it differently than the existing `OrderBy()` would be even more confusing I would say.

**Comment by bartonjs** [comment]
* Since this keeps coming up, we recommend first doing an analysis of Enumerable to see if we can do something that is consistent and not explosive, like making selector functions nullable (and defaulted to null).
  * We did the analysis on the call.  Losing generic inference makes that a worse approach.
* We removed the generic constraint both for consistency, and `IEnumerable<int?>`
* Should also apply to Queryable

```C#
namespace System.Linq
{
    public partial class Enumerable
    {
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source);
        public static IOrderedEnumerable<T> Order<T>(this IEnumerable<T> source, IComparer<T> comparer);

        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source);
        public static IOrderedEnumerable<T> OrderDescending<T>(this IEnumerable<T> source, IComparer<T> comparer);
    }
    public partial class Queryable
    {
        // Or whatever's correct.
        [DynamicDependency("Order`1", typeof(Enumerable))]
        public static IOrderedQueryable<T> Order<T>(this IQueryable<T> source);
        [DynamicDependency("Order`1", typeof(Enumerable))]
        public static IOrderedQueryable<T> Order<T>(this IQueryable<T> source, IComparer<T> comparer);

        [DynamicDependency("OrderDescending`1", typeof(Enumerable))]
        public static IOrderedQueryable<T> OrderDescending<T>(this IQueryable<T> source);
        [DynamicDependency("OrderDescending`1", typeof(Enumerable))]
        public static IOrderedQueryable<T> OrderDescending<T>(this IQueryable<T> source, IComparer<T> comparer);
    }
}
```

**Comment by eiriktsarpalis** [comment]
Based on the decision made today, would it make sense to revisit `Flatten()` as well?

https://github.com/dotnet/runtime/issues/54220#issuecomment-946994846

**Comment by stephentoub** [comment]
...and there's the slippery slope.  5 minutes... that took even less time than I expected ;-)

**Comment by deeprobin** [comment]
Doesn't seem like a big change.
If you are ready for a community contribution here, feel free to assign me.

**Comment by svick** [comment]
@deeprobin The problem is, if the method is not added to `Queryable`, what happens if you call `queryable.Order()`? That code would be valid and would call `Enumerable.Order()`, since `IQueryable<T>` inherits from `IEnumerable<T>`. But then the ordering would not become part of the query, but would be instead executed in memory, which is not what you want.
