### ISSUE TITLE
Support the generic `Enum` methods in NativeAOT's reflection-free mode.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#67191]
The NativeAOT's reflection-free mode is documented [not to work well with parsing and formatting enums](https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/reflection-free-mode.md#reflection-apis-that-are-up-for-discussion), but since that document was written, we got generic editions of the `Enum` methods that allow efficient implementations without reflection.

For example the following code prints `Foo,Bar` in regular NativeAOT and nothing in reflection-free NativeAOT:

```
Console.WriteLine(string.Join(',', Enum.GetNames<MyEnum>()));

public enum MyEnum { Foo, Bar }
```

It would be nice if it printed `Foo,Bar` in the reflection-free mode as well. Same with supporting enum names in the other generic methods like `Parse`, `ToString`, `IsDefined`, `GetNames` and `GetValues`. Perhaps it would optimize the regulat NativeAOT implementation as a consequence.

**Comment by jkotas** [comment]
This is duplicate/subset of https://github.com/dotnet/runtime/issues/67193 that I have just transferred from runtimelab repo.
