### ISSUE TITLE
HttpHeaders should not remove invalid values during validating access

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#67199]
Spinning off the discussion about this specific behavior from #61798.

`HttpHeaders` will remove the header entry during a validating read if it contained only values with new lines, or had a known parser and was just whitespace.

```c#
HttpHeaders headers = new HttpRequestMessage().Headers;

headers.TryAddWithoutValidation("Accept", "invalid with new lines\n"); // or string.Empty
Assert.Equal(1, headers.NonValidated.Count);

Assert.False(headers.TryGetValues("Accept", out _));

// The entry doesn't exist anymore even for NonValidated accesses
Assert.Equal(0, headers.NonValidated.Count);
```

This means that validated enumeration results in even more side effects to the request/response.
`NonValidated` enumeration is not able to report all entries if a validated enumeration occurred before it.

I recommend we change the behavior here such that values containing new lines are never implicitly removed. This should result in more consistent behavior and improve the usability of `NonValidated`.
This would mean that the user may now observe new-line characters & empty values from `TryGetValues` (given they were added without validation).

As a nice bonus, the fact we remove these entries is the biggest complication in reintroducing support for thread-safe concurrent reads (https://github.com/dotnet/runtime/issues/66989#issuecomment-1077814790).

**Comment by MihaZupan** [comment]
Updated the description to properly note that this only applies to header values that contain new line characters and were added via `TryAddWithoutValidation` already.

**Comment by karelz** [comment]
Triage:
- It is blocker for thread-safety we need (e.g. #66989)
- Technical breaking change, but closer to common expected behavior

**Comment by heathbm** [comment]
This appears to be a quick fix, I hope I can help with this

**Comment by heathbm** [comment]
Should the "or had a known parser and was just whitespace" work be a separate PR?

**Comment by MihaZupan** [comment]
>  Should the "or had a known parser and was just whitespace" work be a separate PR?

Yes, I think it's closely related - any implicit `Remove` calls should be removed.
