### ISSUE TITLE
CodeGen optimization for enums and explicit number checks

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#67204]
I made the discovery that JIT Enumchecks does not optimize as well as LLVM, for example.

It is often a code decision to check enum values explicitly instead of performing a range check to ensure that this check works even if changes are made within the enum.
Also, in many cases it is more readable to perform these checks explicitly.

But these checks are done often. Therefore, I think that it is worth to introduce this optimization.
This optimization is when it is known that the enum variants follow sequentially one after the other, that a single Comparison is created from these jump tables.
Theoretically, this optimization applies not only to enums but also to constant integer checks.
In cases where it is known that diff to `primitive.MinValue` is 1, LLVM optimizes the whole thing even better using `dec`.

Godbolt Example: https://godbolt.org/z/Gc448jqf3

## Benchmarks

Benchmark Source: https://gist.github.com/deeprobin/8602ca2c2811bb235a0c9d9f538e636c

### Results

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1586 (21H1/May2021Update)
AMD Ryzen 5 3600, 1 CPU, 12 logical and 6 physical cores
.NET SDK=7.0.100-preview.1.22110.4
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  Job-KZAABB : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  Job-BDWTFW : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
```

|       Method |        Job | IterationCount | RunStrategy | UnrollFactor | EnumVariant |           Mean |           Error |         StdDev |      Median |         Min |             Max | Iterations | Ratio | RatioSD | Code Size |
|------------- |----------- |--------------- |------------ |------------- |------------ |---------------:|----------------:|---------------:|------------:|------------:|----------------:|-----------:|------:|--------:|----------:|
| **IsBToYLegacy** | **Job-KZAABB** |             **10** |   **ColdStart** |            **1** |    **VariantB** | **24,730.0000 ns** | **117,275.8290 ns** | **77,570.6997 ns** | **200.0000 ns** | **100.0000 ns** | **245,500.0000 ns** |      **10.00** |  **1.00** |    **0.00** |     **241 B** |
|       IsBToY | Job-KZAABB |             10 |   ColdStart |            1 |    VariantB | 20,110.0000 ns |  95,241.1560 ns | 62,996.1277 ns | 200.0000 ns | 100.0000 ns | 199,400.0000 ns |      10.00 |  1.03 |    0.51 |      78 B |
|              |            |                |             |              |             |                |                 |                |             |             |                 |            |       |         |           |
| IsBToYLegacy | Job-BDWTFW |        Default |  Throughput |           16 |    VariantB |      0.2574 ns |       0.0213 ns |      0.0200 ns |   0.2608 ns |   0.2266 ns |       0.2865 ns |      15.00 |  1.00 |    0.00 |     140 B |
|       IsBToY | Job-BDWTFW |        Default |  Throughput |           16 |    VariantB |      0.0352 ns |       0.0232 ns |      0.0206 ns |   0.0388 ns |   0.0000 ns |       0.0694 ns |      14.00 |  0.14 |    0.08 |      20 B |
|              |            |                |             |              |             |                |                 |                |             |             |                 |            |       |         |           |
| **IsBToYLegacy** | **Job-KZAABB** |             **10** |   **ColdStart** |            **1** |    **VariantY** | **25,830.0000 ns** | **122,587.9822 ns** | **81,084.3600 ns** | **200.0000 ns** | **100.0000 ns** | **256,600.0000 ns** |      **10.00** |  **1.00** |    **0.00** |     **241 B** |
|       IsBToY | Job-KZAABB |             10 |   ColdStart |            1 |    VariantY | 20,600.0000 ns |  97,212.1766 ns | 64,299.8358 ns | 200.0000 ns | 200.0000 ns | 203,600.0000 ns |      10.00 |  1.40 |    0.50 |      78 B |
|              |            |                |             |              |             |                |                 |                |             |             |                 |            |       |         |           |
| IsBToYLegacy | Job-BDWTFW |        Default |  Throughput |           16 |    VariantY |      3.3452 ns |       0.0301 ns |      0.0267 ns |   3.3423 ns |   3.3050 ns |       3.4111 ns |      14.00 | 1.000 |    0.00 |     140 B |
|       IsBToY | Job-BDWTFW |        Default |  Throughput |           16 |    VariantY |      0.0223 ns |       0.0196 ns |      0.0164 ns |   0.0201 ns |   0.0000 ns |       0.0601 ns |      13.00 | 0.007 |    0.00 |      20 B |
|              |            |                |             |              |             |                |                 |                |             |             |                 |            |       |         |           |
| **IsBToYLegacy** | **Job-KZAABB** |             **10** |   **ColdStart** |            **1** |    **VariantZ** | **21,990.0000 ns** | **104,176.1584 ns** | **68,906.0786 ns** | **200.0000 ns** | **100.0000 ns** | **218,100.0000 ns** |      **10.00** |  **1.00** |    **0.00** |     **241 B** |
|       IsBToY | Job-KZAABB |             10 |   ColdStart |            1 |    VariantZ | 19,330.0000 ns |  91,512.1024 ns | 60,529.5896 ns | 200.0000 ns | 100.0000 ns | 191,600.0000 ns |      10.00 |  0.94 |    0.28 |      78 B |
|              |            |                |             |              |             |                |                 |                |             |             |                 |            |       |         |           |
| IsBToYLegacy | Job-BDWTFW |        Default |  Throughput |           16 |    VariantZ |      3.1717 ns |       0.0655 ns |      0.0612 ns |   3.1632 ns |   3.0886 ns |       3.2822 ns |      15.00 |  1.00 |    0.00 |     140 B |
|       IsBToY | Job-BDWTFW |        Default |  Throughput |           16 |    VariantZ |      0.0382 ns |       0.0155 ns |      0.0129 ns |   0.0370 ns |   0.0231 ns |       0.0713 ns |      13.00 |  0.01 |    0.00 |      20 B |

Here we see a significant improvement through this optimization.

### Expression Interpreter

https://github.com/dotnet/runtime/blob/ef4773c3c05cf36ac9000ba61195b3d1d5b14f0b/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/BinaryExpression.cs#L38-L59

this could be optimized to:

```cs
private static bool IsOpAssignment(ExpressionType op) 
    => op >= ExpressionType.AddAssign and <= ExpressionType.SubtractAssignChecked;
    //   op >= 63 and <= 76
```

In general, there are many such constructs in `System.Linq.Expressions`. Even if these are often not in a hot path, I think the mass of these constructs is decisive for a decision for this optimization.

### `System.Text.Json`

https://github.com/dotnet/runtime/blob/3409f73c7893f863297e5eb5d17241dcf0796733/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Node/JsonNodeConverter.cs#L55-L58

```cs
                case JsonTokenType.String: // 7
                case JsonTokenType.False: // 10
                case JsonTokenType.True: // 9
                case JsonTokenType.Number: // 8
```

could be optimized to `is >= JsonTokenType.String and <= JsonTokenType.False`.

### and more

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/IL/ILOpCodeExtensions.cs#L11-L47

Often such checks are also used in interop cases.

**Comment by danmoseley** [comment]
Using your full example in godbolt https://godbolt.org/z/dW6Tcn4Tv the difference is even larger.

**Comment by stephentoub** [comment]
The C# compiler already does the cited compression to a range check for switch statements. Your repro uses pattern matching which doesn't yet do the same thing, but that's covered by https://github.com/dotnet/roslyn/issues/58246.

**Comment by deeprobin** [comment]
@stephentoub 
Even with Switch statements, CodeGen doesn't really look optimized.
https://godbolt.org/z/afooPhK4v

**Comment by deeprobin** [comment]
But using these switch-case-blocks the codegen seems better:
https://godbolt.org/z/4qT8E6Ev8

**Comment by deeprobin** [comment]
However, shouldn't we also need such an optimization on the JIT side, since it could be numbers instead of enum values?
Or is this optimization too niche?

**Comment by stephentoub** [comment]
> Even with Switch statements, CodeGen doesn't really look optimized.

That's because you have a different case block for each.

> since it could be numbers instead of enum values?

The same optimization already applies to integers.
https://sharplab.io/#v2:D4AQTAjAsAUCDMACciDCiDetE+UgRgPaEA2iAshABQByArgLb4CmATgM6IB2AlJtrkHsA7gEsALgGMAFoiq9EAwTiwxl6xJICG7ZonpM27AHQB5LswBcSjTm279jFh2MAVYYWtrbue3oPOJq7SrMxWNrZ+joYuAGKEdKxePhogAOyI4qx0zADcEbgAvgU46YgAZlokuvneOMV1io0IiESkFGBUolzi3HyqtiISMnIKJfyNkTp6EMkpmtOIYHMpUfArPlEALBvzyBlZObW2DbZlldV5Ng0NsC3MXIzRgZiI5noAvIgQADSI7oREF8wH9gqFPoh4H94okgYgtoVEEA
