### ISSUE TITLE
Microsoft.Extensions.Hosting.Systemd.SystemdHelpers.IsSystemdService does not work inside containers.

### ISSUE THREAD

**Issue by judilsteve** [dotnet/runtime#67203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`Microsoft.Extensions.Hosting.UseSystemd()` is set up to no-op if `IsSystemdService()` returns false. However, `IsSystemdService()` only returns true if the direct parent process is systemd. This is not true when we have a container runtime (e.g. podman) acting as a middleman, and thus containerised systemd services do not have sd-notify integration or systemd log formatting. 

### Expected Behavior

If there exists a more robust check that would work in containerised deployments, then `IsSystemdService()` should use that.

Otherwise, an overload of` UseSystemd()` should be created (e.g. `UseSystemd(bool forceEnable = false)`) that allows users to forcibly enable sd-notify integration and systemd log formatting, without having to manually copy the part of `UseSystemd()` that is inside the if statement from the reference source into our startup code, since this code may be subject to change in the future.

### Steps To Reproduce

Minimalist reproduction [here](https://github.com/judilsteve/FdListenTest)

### .NET Version

6.0.101

### Anything else?

```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     fedora
 OS Version:  35
 OS Platform: Linux
 RID:         fedora.35-x64
 Base Path:   /home/james/.dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/home/james/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/home/james/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/home/james/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by davidfowl** [comment]
cc @tmds

**Comment by davidfowl** [comment]
Part of this might be asp.net core as well (the listen on a handle part).

**Comment by tmds** [comment]
> Minimalist reproduction [here](https://github.com/judilsteve/FdListenTest)

It's great when issues are reported with a small reproducer. Thanks!

> If there exists a more robust check that would work in containerised deployments, then IsSystemdService() should use that.

We can extend the logic to include the following:

If `Environment.ProcessId` is `1` and the envvar for `NOTIFY_SOCKET` or `LISTEN_PID` is set.

If we'd like to be more liberal, we could drop the `Environment.ProcessId` check. Though the existing `IsSystemdService` check requires .NET to be a direct child, so requiring the process to be pid `1` in the container is similarly strict.

> Otherwise, an overload of UseSystemd() should be created (e.g. UseSystemd(bool forceEnable = false)) that allows users to forcibly enable sd-notify integration and systemd log formatting, without having to manually copy the part of UseSystemd() that is inside the if statement from the reference source into our startup code, since this code may be subject to change in the future.

If we extend the logic of `IsSystemdService` as described above, probably this is not needed.

In case the api would be extended, it should probably use the 'Options' pattern so the systemd mode can be triggered using the regular configuration mechanism.

@judilsteve do you want to contribute the change?

**Comment by judilsteve** [comment]
@tmds I am not sure it's appropriate for `IsSystemdService` to return true if `LISTEN_PID` is defined. It is possible to have this defined but have `NOTIFY_SOCKET` (the thing we're actually interested in) not be defined, e.g. if the application is running as a socket-activated containerised service but docker/podman is configured with `--sdnotify=conmon` instead of `--sdnotify=container`. I will proceed with just checking `Environment.ProcessId` and `NOTIFY_SOCKET` for now.

**Comment by tmds** [comment]
My suggestion is to return `true` if _either_ `NOTIFY_SOCKET` or `LISTEN_PID` is defined, it doesn't have to be both.
So if you are interested in `NOTIFY_SOCKET` and not `LISTEN_PID`, that will work.

**Comment by judilsteve** [comment]
My worry is that we would be enabling the services that interact with sd-notify when no notify socket is available, but that service has [its own check](https://source.dot.net/#Microsoft.Extensions.Hosting.Systemd/SystemdNotifier.cs,cf1bf77e57d89fdd,references) for that, so we're good there.

**Comment by judilsteve** [comment]
I'm having some trouble building the repo on the current tip of `main`. I first tried on bare metal (Fedora 35) after installing the rpm equivalents of the packages listed [here](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/linux-requirements.md), and then tried again building inside a [container](https://github.com/dotnet/runtime/blob/main/.devcontainer/Dockerfile), but got the same error messages with both:

```
/runtime/src/coreclr/runtime.proj(61,5): error MSB3073: The command ""/runtime/src/coreclr/build-runtime.sh" -x64 -debug -os Linux" exited with code 2.
make: *** No rule to make target 'install'.  Stop.
```

I've pushed a commit [here](https://github.com/judilsteve/runtime/commit/e89a55bf938cf2ddbe25f38c09e03d0583e112f1) with my proposed changes. Is it OK to open a PR without getting a green build locally first?

**Comment by tmds** [comment]
Yes, go ahead and open up a PR.

To build on Fedora, I have these installed:
```
    sudo dnf -y install automake clang cmake libcurl-devel findutils git glibc-langpack-en \
                        hostname krb5-devel libicu-devel libtool libunwind-devel lldb-devel \
                        llvm lttng-ust-devel make openssl-devel python3 systemtap-sdt-devel \
                        tar wget which zlib-devel
```
The PGO stuff has been crashing my build for a long time, so I add `/p:NoPgoOptimize=true`  at the end of the build command, like:
```
./build.sh --subset clr+libs --runtimeconfiguration Release /p:NoPgoOptimize=true
```

**Comment by judilsteve** [comment]
PR: https://github.com/dotnet/runtime/pull/67288

**Comment by eerhardt** [comment]
For my learning, what is the scenario/reasoning for running a systemd service inside a container? Why not just be a normal process if you are inside a container?

**Comment by tmds** [comment]
> For my learning, what is the scenario/reasoning for running a systemd service inside a container? Why not just be a normal process if you are inside a container?

The app is packaged and distributed as a container image.
This systemd service can be running any image, like the redis image from Docker hub, or a .NET app from your companies local container registry.

Because the app is packaged as a container image, it is fully self-contained.

`podman` includes a service (`podman-auto-update`) that will check the registry for new images and rolls them out for you. So your app gets updated automatically.

**Comment by judilsteve** [comment]
@eerhardt I think maybe you are picturing that systemd is running inside the container. That's not the case; systemd runs *outside* the container and the notify socket is proxied into the container via the `--sd-notify=container` flag in the docker/podman run command.

It is possible to have docker/podman manage notifications by itself with `--sd-notify=conmon`, but this is less preferable because conmon will report to systemd that the service is "active" as soon as the container has booted and the containerised process (in my case an ASP.NET webapi) has started. However, the webapi might not be ready to serve requests yet at this point. By proxying the notify socket into the container from the host machine, we can let ASP.NET notify systemd more correctly of the service's readiness.
