### ISSUE TITLE
Count_Timeout_ThrowsAfterTooLongExecution test failure

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67225]
So far it happened only once, for [this](https://dev.azure.com/dnceng/public/_build/results?buildId=1683900&view=logs&j=3f13e9dd-5fbe-5edd-198d-04c8537bca02&t=2dfef947-451a-5d13-09e9-614229052870&l=57) pipeline.

From the [console logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d0d6977bd85a4f3b9d/System.Text.RegularExpressions.Tests/1/console.61d07c51.log?sv=2019-07-07&se=2022-04-15T20%3A46%3A17Z&sr=c&sp=rl&sig=gmiMlOZCh9vncpWV1OQ2vZ%2BFls7qRM7THU5MRiVRZXA%3D):

```log
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 271 of 301 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 2)
    System.Text.RegularExpressions.Tests.RegexCountTests.Count_Timeout_ThrowsAfterTooLongExecution(engine: SourceGenerated) [FAIL]
      Assert.InRange() Failure
      Range:  (0 - 10)
      Actual: 12.4531164
      Stack Trace:
        /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Count.Tests.cs(122,0): at System.Text.RegularExpressions.Tests.RegexCountTests.Count_Timeout_ThrowsAfterTooLongExecution(RegexEngine engine)
        --- End of stack trace from previous location ---
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 14882, Errors: 0, Failed: 1, Skipped: 0, Time: 296.630s
```

**Comment by AndyAyersMS** [comment]
Also seeing this in some of the ibraries-pgo OSR stress runs](https://dev.azure.com/dnceng/public/_build/results?buildId=1684479&view=ms.vss-test-web.build-test-results-tab)

```
;; Linux-Release-arm64-CoreCLR_checked-jit-osr_stress_random

    System.Text.RegularExpressions.Tests.RegexCountTests.Count_Timeout_ThrowsAfterTooLongExecution(engine: SourceGenerated) [FAIL]
      Assert.InRange() Failure
      Range:  (0 - 10)
      Actual: 14.8878736
```

**Comment by danmoseley** [comment]
This is happening 5-10 times a week or so. The good news is  -- changing to 20 sec cap will make it go away. OTOH, is it a concern that it takes > 10 sec to timeout when given a 1ms timeout?


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
| where Finished >= now(-120d)
| where Result == "Fail"
//| where T/ype == "System.Text.RegularExpressions.Tests.RegexCountTests."
| where  Method == "Count_Timeout_ThrowsAfterTooLongExecution"
| where Message startswith "Assert.InRange"
| project 
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
 // Test = Type1,
 // Result,Finished,
  Duration,
 // Method,
 // Build = tostring(parse_json(Properties).BuildNumber),
  Message
```

|Pipeline|Pipeline_Configuration|OS|Arch|Duration|Message|
|---|---|---|---|---|---|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|12.667|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 11.3292915|
|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|13.038|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 12.2048663|
|runtime|Debug|ubuntu.1804.armarch.open|arm|66.199|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.4530916|
|runtime|Debug|ubuntu.1804.armarch.open|arm|17.589|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 11.4419149|
|runtime|Debug|ubuntu.1804.armarch.open|arm|22.591|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 13.5694948|
|runtime|Debug|ubuntu.1804.armarch.open|arm|17.025|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 12.0478327|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|12.046|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.8815769|
|runtime-coreclr libraries-pgo|Release|ubuntu.1804.armarch.open|arm64|18.436|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 14.8878736|
|runtime-coreclr libraries-pgo|Release|ubuntu.1804.armarch.open|arm64|69.567|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 11.2521923|
|runtime|Release|ubuntu.1804.amd64.open.rt|x64|12.8|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 12.4531164|
|runtime-coreclr libraries-pgo|Release|ubuntu.1804.armarch.open|arm64|75.026|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 11.6100117|
|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|12.309|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 11.6770946|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|16.871|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 13.4563084|
|runtime-coreclr libraries-pgo|Release|windows.10.amd64.open.rt|x64|62.234|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 12.4495277|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|12.202|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.3420548|
|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|12.781|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 12.4953865|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|61.984|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.7295527|
|runtime|Debug|ubuntu.1804.amd64.open.rt|x64|11.195|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.3276977|
|runtime|Debug|ubuntu.1804.armarch.open|arm64|12.341|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 10.5738379|
|runtime|Debug|ubuntu.1804.armarch.open|arm|20.463|Assert.InRange() Failure<br>Range:  (0 - 10)<br>Actual: 13.8628252|

**Comment by danmoseley** [comment]
BTW if I also add `StackTrace` I see it is almost always on the first Assert.InRange, only once on the second. This is consistent with "slow machine" rather than "random behavior"

**Comment by AndyAyersMS** [comment]
> is it a concern that it takes > 10 sec to timeout when given a 1ms timeout?

I always have suspected the lab machines are underpowered and heavily loaded, so we see a lot of unusual thread interleaving there that we don't see elsewhere (so not surprising if we can't meet a timeout in a timely manner). When I go to repro lab issues locally, I often have to add additional stress loading.

**Comment by danmoseley** [comment]
Yes, I've often had to set 30 sec timeouts for something that usually finishes in 100ms locally. I would simply set this to 20 sec and be done with it, but we should be sure that it is actually timing out (which is a security mechanism), and not simply exhausting the regex. Although given the pattern in this test, I suppose that's very unlikely.
