### ISSUE TITLE
Removing a field from Dictionary.Enumerator

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6722]
`getEnumeratorRetType` is only used for the non-generic IDictionaryEnumerator: https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L789 Perhaps we should consider having IDictionary.GetEnumerator return a different type and removing the field.

**Comment by danmosemsft** [comment]
This seems like it would be a breaking change.

**Comment by svick** [comment]
@danmosemsft Just to clarify, are you saying that it's a breaking change to return a type other than `Dictionary<,>.Enumerator` from `IDictionary.GetEnumerator()`, because existing code could do something like the following, which would stop working with such change?

```c#
IDictionary dict = new Dictionary<int, int>();
var enumerator = (Dictionary<int, int>.Enumerator)dict.GetEnumerator();
```

**Comment by danmosemsft** [comment]
@svick right. If this was a little used type, maybe that might be OK. But on a heavily used type, just to save a few bytes in an enumerator (which may not leave the stack) it does not seem worth it. Let me know if you disagree.

`Environment.GetEnvironmentVariables()` returns an `IDictionary`. Originally it was a `Hashtable` and later it was changed to `Dictionary<K,V>` which broke enough people it is now `Hashtable` again.
