### ISSUE TITLE
Would it be possible to combine Dictionary.buckets and entries?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6723]
The size of `Dictionary.buckets` and `Dictionary.entries` will always be the same. Maybe it would be possible to aggregate both of the fields into an array of 1 struct, containing the buckets/hash code/next/key/value? This would reduce the field size of Dictionary, and reduce fragmentation since there are no longer 2 separate arrays being allocated.

**edit:** Potential cons: Could cause [`Array.Copy`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Dictionary.cs#L466) to do more work during resizing, may mess up 8 byte-alignment if `TKey` and `TValue` are both ref types, for example. Not sure if worth it.

cc @benaadams @GSPP @jkotas @omariom

**Comment by stephentoub** [comment]
This design discussion reached conclusion over three years ago.  Thanks.  Closing.
