### ISSUE TITLE
DistributedCacheExtensions adds object caching methods

### ISSUE THREAD

**Issue by malus2077** [dotnet/runtime#67237]
### Background and motivation

1. In actual use, cache object operations are very common and frequent
2. Adding this method can simplify the operation of serializing objects into bytes or strings first, improving development efficiency

If the review is passed, I want to complete the specific implementation, can you assign it to me?

### API Proposal

` Get<T> Set<T> already exists in MemoryCache. When DistributedCache uses Get<T> Set<T>, developers can follow the operating habits and maintain the uniformity of similar APIs`

```C#
namespace Microsoft.Extensions.Caching.Distributed
{
    /// <summary>
    /// Extension methods for setting data in an <see cref="IDistributedCache" />.
    /// </summary>
    public static class DistributedCacheExtensions{
              public static void Set<T>(this IDistributedCache cache, string key, T value);
              public static T? Get<T>(this IDistributedCache cache, string key);
              ......
              ......
    }
}
```

### API Usage

```C#
//set object cache
_distributedCache.Set("cachekey", data)
//get object cache
_distributedCache.Get<IEnumerable<WeatherForecast>>("cachekey");
```

### Alternative Designs

N/A

### Risks

N/A

**Comment by eerhardt** [comment]
The IDistributedCache is based on the values being stored in this cache are `byte[]`. How do you propose to serialize/deserialize any object into a `byte[]`?

**Comment by malus2077** [comment]
@eerhardt In my daily work I use System.Text.Json.JsonSerializer.SerializeToUtf8Bytes() it works well,  in addition there are many other redis open source libraries that use json to serialize to byte[], I want to use this way to complete serialization

**Comment by eerhardt** [comment]
My opinion is that this is something that would be a great external extension package, but doesn't really belong in the core Microsoft.Extensions.Caching.Abstractions package. It doesn't have a reference to `System.Text.Json` today. And future looking, Json might be a popular serialization technology today, but is it still likely to be the defacto serialization technology in 5-10 years? I don't know.

Another thought is that something like should also take advantage of [JSON source generators](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-source-generation). So if we (or some other library) did have these kinds of APIs, they could also have overloads that take a `JsonTypeInfo<T>` to use for serialization/deserialization.

**Comment by maryamariyan** [comment]
> that this is something that would be a great external extension package, but doesn't really belong in the core Microsoft.Extensions.Caching.Abstractions package

+1. Based on this closing as wont't fix.
