### ISSUE TITLE
build no longer works in directories donating dash on Windows

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#67259]
This seems like recent regression. I have my build trees for very long time and now I cannot build main any more.
(did git clean -dfx) I also tried to pass `-msbuild` to avoid Ninja but that did not help
With same VS and same machine, I can finish build if checked to different directory like "runtime" 

```
Copyright (C) Microsoft Corporation.  All rights reserved.

  C:\Users\test\github\wfurt-runtime\artifacts\obj\coreclr\windows.x64.Release\dlls\mscoree\coreclr\dump_helper_resource.rc(13) : error RC2135 : file not found: C:/Users/test/github/wfurt

  [2241/2304] Building CXX object dlls\mscoree\coreclr\CMakeFiles\coreclr_static.dir\__\exports.cpp.obj
  ninja: build stopped: subcommand failed.
  BUILD: Error: native component build failed. Refer to the build log files for details.
      "C:\Users\test\github\wfurt-runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__x64__Release.log"
      "C:\Users\test\github\wfurt-runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__x64__Release.wrn"
      "C:\Users\test\github\wfurt-runtime\src\coreclr\..\..\artifacts\log\Release\CoreCLR_windows__x64__Release.err"
C:\Users\test\github\wfurt-runtime\src\coreclr\runtime.proj(61,5): error MSB3073: The command ""C:\Users\test\github\wfurt-runtime\src\coreclr\build-runtime.cmd" -x64 -release -pgodatapath "C:\Users\test\.nuget\packages\optimization.windows_nt-x64.pgo.coreclr\1.0.0-prerelease.22121.2"" exited with code 1.

Build FAILED.
```

**Comment by danmoseley** [comment]
@jkoritzinsky does this need quoting? https://github.com/dotnet/runtime/pull/67018/files#diff-b27ad9d97128714d9dc2ef8bd18e98dd427c997fb2c3d773647d1bfadcc1771eR13

Not sure what @ does there, should it be #@ ? (https://docs.microsoft.com/en-us/windows/win32/menurc/preprocessor-operators)

**Comment by danmoseley** [comment]
This seems to be something that breaks periodically, either hyphens or spaces (some people's Windows user names contain spaces). Last time we considered updating PR validation scripts to add a hyphen or space, but I guess it doesn't happen often enough.
