### ISSUE TITLE
[API Proposal]: Add `Ping.SendPingAsync` overloads with `CancellationToken`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#67260]
### Background and motivation

This was already approved in https://github.com/dotnet/runtime/issues/14336, but reverted in https://github.com/dotnet/runtime/pull/67253 because this requires some more work.

See https://github.com/dotnet/runtime/pull/64860#discussion_r836496120

### API Proposal

```cs
namespace System.Net.NetworkInformation {
    public class Ping {
        public Task<PingReply> SendPingAsync(IPAddress address, TimeSpan timeout, byte[]? buffer = null, PingOptions? options = null, CancellationToken cancellationToken = default);
        public Task<PingReply> SendPingAsync(string hostNameOrAddress, TimeSpan timeout, byte[]? buffer = null, PingOptions? options = null, CancellationToken cancellationToken = default);
    }
}
```

/cc @danmoseley 
/cc @stephentoub

**Comment by danmoseley** [comment]
Updated to match what was approved.

**Comment by deeprobin** [comment]
@danmoseley Thanks. I removed the trailing `+`. Can you remove the `untriaged` label?

**Comment by teo-tsirpanis** [comment]
How about returning `ValueTask` or accepting `Memory<byte>`? In the latter case `PingReply.Buffer` might need taking a look at. I haven't understood whether it contains the original buffer passed to the method. If it does, we can ignore it when constructing the resulting ping reply.

```
namespace System.Net.NetworkInformation;

public class Ping {
    public ValueTask<PingReply> SendPingAsync(IPAddress address, TimeSpan timeout, Memoty<byte> buffer = default, PingOptions? options = null, CancellationToken cancellationToken = default);
    public ValueTask<PingReply> SendPingAsync(string hostNameOrAddress, TimeSpan timeout, Memory<byte> buffer = default, PingOptions? options = null, CancellationToken cancellationToken = default);
}
```

**Comment by rhuijben** [comment]
Ping will almost always wait, so I think `Task<>` is fine. No need to optimize the no wait case

**Comment by sakno** [comment]
IMO, this proposal can be combined with #34856

**Comment by deeprobin** [comment]
@sakno Could be. But this is already approved and #34856 is not.

**Comment by madelson** [comment]
I have some interest in working on this.

One thought: could `TimeSpan timeout` be changed to `TimeSpan? timeout = null`? This would allow you to fall back to the default timeout as is possible with the `int` timeout APIs.

**Comment by deeprobin** [comment]
> I have some interest in working on this.

I'd be happy to. @danmoseley can you assign this issue to him?

> One thought: could TimeSpan timeout be changed to TimeSpan? timeout = null? This would allow you to fall back to the default timeout as is possible with the int timeout APIs.

@rhuijben Any thoughts? If we want to change the API shape, this API must be re-reviewed.
