### ISSUE TITLE
Redundant bound check for span.Length == 0 pattern

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#67270]
Found in https://github.com/dotnet/runtime/pull/66865#issuecomment-1081224071 

Simplified repro (from `String.JoinCore`):
```csharp
string Test1(ReadOnlySpan<string> values)
{
    if (values.Length <= 1)
        return values.Length == 0 ? string.Empty : values[0];
    return null;
}

string Test2(ReadOnlySpan<string> values)
{
    if (values.Length <= 1)
        return 0 >= (uint)values.Length ? string.Empty : values[0];
    return null;
}
```
codegen: [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACMhgYQYG8aHunyAGBgBUYuDOQAUAJRjYAJgHkAdgBsAngGUADtkUAeYvwB8DAG7ZlAVxEBKLj07UeThgEsAZg3FnLIgHQAZGEUAcwwACwZdAF4GcltHZ0TiAHZTcytcAKDQiKiYgQB+Xj5fAFF8TQxVBhA0n1wAbT4AXQBuOyTUxQtlZXaE7gBfGg7ioREMUikZBRUNbT0DPmNvDPinB0Tud09Vv0CQ8MiYuNGtplSBQxjxCxdFDGs9zIOchiKlsoqqmrqMpraZx4KQY3V6/Scw2ogyAA=)

`Test1` has a redundant rangecheck.

category:cq
theme:bounds-checks
skill-level:intermediate
cost:small
impact:small

**Comment by EgorBo** [comment]
```
Looking for array size assertions for: $200
Constant Assertion: ($240,$40) Loop_Bnd { {IntCns 1} LT  {MemOpaque:NotInLoop}} is  {IntCns 0}, index = #03
The range after edge merging:<Dependent, 1>
```
it incorrectly comes up with `<Dependent, 1>` range for `values.Length` in Test1 while it should be `<1, 1>`

**Comment by EgorBo** [comment]
Moving to 8.0.0 as this is just a minor optimization

**Comment by jakobbotsch** [comment]
Seems like we lost the ability to optimize the range check for `Test2` with #95740, so both examples produce the redundant bounds checks today.

**Comment by EgorBo** [comment]
> Seems like we lost the ability to optimize the range check for `Test2` with #95740, so both examples produce the redundant bounds checks today.

Consistent behavior! 🙂
