### ISSUE TITLE
String.Compare() Can not work in .Net 6

### ISSUE THREAD

**Issue by 15092368540** [dotnet/runtime#67275]
### .NET version

.Net 6.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET Core 3.1

### Issue description

Source code example:
[StrCompare.zip](https://github.com/dotnet/winforms/files/8356647/StrCompare.zip)

### Steps to reproduce

Source code example

**Comment by RussKie** [comment]
@tarekgh I guess this may something to do with the cultures...

**Comment by tarekgh** [comment]
@15092368540 you may refer to the [article](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) for more information about what has changed in .NET 5.0+. Also, the article describes [how to get back the old behavior](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu).
