### ISSUE TITLE
RyuJIT SIMD: Kestral server method Seek() has a case of not in-lining the method FindFirstEqualByte()

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6729]
As per Intel TechEmPower benchmark analysis, Kestrel.Internal.Infrastructure.MemoryPoolIterator.Seek() is one of the hot methods.

```
var data = new Vector<byte>(array, index);

// The following code is repeated 3 times in the method
// with 3 different vectors (byte0Vector, byte1Vector, byte2Vector)
 var byte0Equals = Vector.Equals(data, byte0Vector);
if (!byte0Equals.Equals(Vector<byte>.Zero))
{
      byte0Index = FindFirstEqualByte(ref byte0Equals);
}

```

Since local byte0Equals gets passed by reference to FindFirstEqualByte() method, it is marked as addr-exposed and do-not-enreg.  As a result, 256-bit (=32-bytes on AVX2 hardware) vector result from Vector.Equals() intrinsic gets written to stack location.  The same 32-byte vector is read from memory when it is referred to in the if-condition.  The above logic is present in the inner-most doubly nested while-loop. That is not only we incur 32-byte write/read 3 times in a doubly nested loop but also incur increased stack frame size of the method (3 locals each of 32 bytes = 96 bytes of stack space).

We could have avoided 32-byte write and read of SIMD vector, if succeeded in in-lining FindFirstEqualByte() and eliminated indirection to access byte0Equal in the resulting IR.  RyuJIT has logic to bump-up the in-liner multiplier if the method has SIMD type params.  This merits investigation to see why FindFirstEqualByte() method is not in-lined.

category:cq
theme:inlining
skill-level:expert
cost:large

**Comment by AndyAyersMS** [comment]
Profile based inlining will consider a wider range of candidate IL sizes as we can use the call site weight to allow selective consideration of larger candidates .

This particular issue has been resolved, so I'm going to close this.
