### ISSUE TITLE
Downlevel (out-of-band nuget) version of System.Memory / ReadOnlySequence<T> doesn't work correctly with custom memory-managers

### ISSUE THREAD

**Issue by mgravell** [dotnet/runtime#67295]
### Description

The following is meant to work and be fairly reliable:

``` c#
ReadOnlyMemory<byte> someMemory = ... //
var seq = new ReadOnlySequence<byte>(someMemory);
Assert.True(seq.IsSingleSegment);
Assert.Equal(someMemory.Length, seq.Length);
```

This should create a single-segment ROS that directly exposes the single buffer we passed in.

This works reliably on .NET Core / .NET 5 / .NET 6, but it can fail horribly on .NET Framework (yes, I know) when using the [NuGet package](https://www.nuget.org/packages/System.Memory/)

### Reproduction Steps

The failure condition relates to using a *custom memory manager* and *non-zero offset* (i.e. you've sliced into the memory at some point). For example, this memory manager:

``` c#
        private sealed class BasicMemoryManager : MemoryManager<byte>
        {
            private readonly byte[] _buffer;
            public BasicMemoryManager(int size = 1024) => _buffer = new byte[size];

            protected override bool TryGetArray(out ArraySegment<byte> segment)
            {
                segment = new ArraySegment<byte>(_buffer);
                return true;
            }
            public override Span<byte> GetSpan() => _buffer;

            public override MemoryHandle Pin(int elementIndex = 0) => throw new NotSupportedException();
            public override void Unpin() => throw new NotSupportedException();
            protected override void Dispose(bool disposing) { }
        }
```

will fail two of the following tests:

``` c#
        [Theory]
        [InlineData(0, 32)]
        [InlineData(0, 29)]
        [InlineData(32, 32)] // fail: length 0
        [InlineData(32, 29)] // fail: length -3
        public void OffsetTest(int offset, int length)
        {
            var mgr = new BasicMemoryManager(1024);
            var slice = mgr.Memory.Slice(offset, length);
            Assert.Equal(length, slice.Length);

            var ros = new ReadOnlySequence<byte>(slice);
            Assert.True(ros.IsSingleSegment);
            Assert.Equal(length, ros.Length);
        }
```

### Expected behavior

The correct single-segment buffer is constructed

### Actual behavior

The length goes ... wonky. It can even be negative. It looks like the start/end are incorrectly considered in the custom-memory-manager path.

### Regression?

This is not a regression; it looks like it has never worked, and is probably *already fixed*, if we had the capability to rebuild and redeploy the netfx/oob NuGet package. However, the only code I can find now only targets .NET "current"

### Known Workarounds

Two workarounds:

1. use `MemoryMarshal.TryGetArray`, and if that works (it isn't guaranteed to): create the sequence over the array-segment directly
2. manually construct a custom `ReadOnlySequenceSegment<T>` and create the ROS over that single segment

Both of these paths work correctly, hence the following succeeds (changing the test to use `AsReadOnlySequence`) - and succeeds even if the custom memory-manager doesn't support `TryGetArray` (i.e. returns `false`):

``` c#
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static ReadOnlySequence<T> AsReadOnlySequence<T>(this ReadOnlyMemory<T> memory)
        {
            // netfx has a nasty bug if you use `new ROS(memory)` with a custom manager with non-zero start; the bug
            // doesn't apply to sequence segments, though - so if we have a custom manager that doesn't support arrays: use that
            if (memory.IsEmpty) return default;
            if (MemoryMarshal.TryGetArray(memory, out var segment))
                return new ReadOnlySequence<T>(segment.Array, segment.Offset, segment.Count);
            return ViaManager(memory);

            static ReadOnlySequence<T> ViaManager(ReadOnlyMemory<T> memory)
            {
                if (MemoryMarshal.TryGetMemoryManager<T, MemoryManager<T>>(memory, out var manager, out var start, out var length)
                    && start != 0)
                {
                    var seqSegment = new IsolatedSequenceSegment<T>(manager.Memory);
                    return new ReadOnlySequence<T>(seqSegment, start, seqSegment, start + length);
                }
                return new ReadOnlySequence<T>(memory);
            }
        }
    internal sealed class IsolatedSequenceSegment<T> : ReadOnlySequenceSegment<T>
    {
        public IsolatedSequenceSegment(ReadOnlyMemory<T> memory)
        {
            Next = null;
            Memory = memory;
            RunningIndex = 0;
        }
    }
```

### Configuration

.NET Framework (any), NuGet package 4.5.4 (latest); custom memory-manager, non-zero offset

**Comment by mgravell** [comment]
That's some good hunting; thanks @adamsitnik - agree this looks like the same thing.

**Comment by ericstj** [comment]
The fix would need to be made to `release/2.1` build of that package which was where we last shipped it.  https://github.com/dotnet/corefx/blob/0d40b482e6b6c232131dc808182d6b32d9d37394/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs#L133

I think the process would be to create a PR against 2.1 fill in the fields in the template and make the business case to tactics for this fix.  

We still service 2.1 packages for use on .NETFramework as called out by `ASP.NET Core 2.1 on .NET Framework`
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
And `System.Memory` is one of the packages included https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1.  The bar for these will be very high.

**Comment by adamsitnik** [comment]
> The bar for these will be very high.

@mgravell how is this bug impacting you as a customer (we need a good justification for the backport)?

**Comment by mgravell** [comment]
@adamsitnik well, individually: I've found hacks for my specific scenario (the workarounds listed above) - which are far from ideal, but: work. In the more general case, though: any ROS code that works with arbitrary `[ReadOnly]Memory<T>` code, or allows user-supplied memory-pools, is pretty vulnerable. The counter-point to that being: it took long enough to be discovered, so that can't be a super high demand scenario. 🤷

**Comment by teo-tsirpanis** [comment]
Opened dotnet/corefx#43141.

**Comment by teo-tsirpanis** [comment]
Should we keep it open until the `System.Memory` package gets updated?

**Comment by adamsitnik** [comment]
> Should we keep it open until the System.Memory package gets updated?

We usually close issues as soon as the PR gets merged (from our perspective as area owners it's done)

@carlossanlop @ViktorHofer what do you think? Would it help you guys to keep this issue opened to track the need of publishing new System.Memory version?

**Comment by ViktorHofer** [comment]
No, we should keep the issue closed as it isn't actionable on our side anymore. We (dotnet/runtime infra) don't control how these assets get published.

**Comment by teo-tsirpanis** [comment]
ICYMI @mgravell [a new version of `System.Memory` was released](https://www.nuget.org/packages/System.Memory/).

**Comment by mgravell** [comment]
Awesome. Thanks all (and yes, I had missed it; appreciate the heads-up)
