### ISSUE TITLE
Add snake case naming policy

### ISSUE THREAD

**Issue by YohDeadfall** [dotnet/runtime#673]
Originally proposed by @hez2010 in dotnet/corefx#39564.

@ahsonkhan, could you add the original issue here and important comments from dotnet/corefx#41354?

@karelz We need your opinion here, since @khellang asked a question about altering the existing behavior of the camel case policy too follow common translator rules for the JS world as splitting a string by words and concatenating it back using some separator and applying a policy to change casing for each word. It's a breaking change and @stephentoub likes it. Me too. See https://github.com/dotnet/corefx/pull/41354#issuecomment-554958476.

I still would like to drive this feature.

@steveharter @layomia

**Comment by layomia** [comment]
I'll close this one and transfer the older proposal here.
