### ISSUE TITLE
[QUIC] IPv6 addresses don't work on Linux

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#67301]
https://github.com/dotnet/runtime/pull/66794 replaced `SOCKADDR_INET` structure serialization by existing code in `SocketAddress` class, which uses platform-dependent values for the OS-level IPv6 address family enum. However, current version of MsQuic used by runtime uses Windows values on all platforms.

The IPv6 functionality on Linux will be fixed once we upgrade to MsQuic 2.0 (tracked by https://github.com/dotnet/runtime/issues/64554), since that release uses the platform-specific enum values.

cc @ManickaP

**Comment by ManickaP** [comment]
I'm still getting: 
```System.Net.Quic.QuicException : Failed to connect to peer. Error Code: INVALID_PARAMETER```
With newest and greatest msquic, so the msquic update is not enough to solve this issue.

I'll keep the tests disabled. @rzikm could you give it a look after I put up a PR for the update?

**Comment by rzikm** [comment]
The problem is the `QUIC_ADDRESS_FAMILY` we pass into the `QuicConnectionStart` function, which still uses the windows value for IPv6.

We can either plug `UNSPECIFIED` temporarily. The value is not used because we set the `REMOTE_ADDRESS` connection parameter separately before calling `QuicConnectionStart`. Or we can just wait for #67377.

**Comment by rzikm** [comment]
#67377 was merged, tests pass. Closing
