### ISSUE TITLE
Cross-targeting to x64 on an arm64 machine with an upgraded arm64 runtime fails

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/runtime#67316]
### Description

I was doing some SDK testing on an arm64 machine. I had installed the 6.0.2 x64 runtime and arm64 sdk/runtime. MU then updated my arm64 runtime to 6.0.3.

dotnet new wpf
dotnet publish -r win-x64 --no-self-contained
set DOTNET_ROOT_X64=c:\Program Files\dotnet\x64
cd bin\Debug\net6.0-windows\win-x64\publish
test.exe

### Reproduction Steps

Install arm64 sdk and x64 runtime. 
Install a newer arm64 runtime.

dotnet new wpf
dotnet publish -r win-x64 --no-self-contained
set DOTNET_ROOT_X64=c:\Program Files\dotnet\x64
cd bin\Debug\net6.0-windows\win-x64\publish
test.exe

### Expected behavior

The application should launch

### Actual behavior

Attempting FX roll forward starting from version='[6.0.0]', apply_patches=1, version_compatibility_range=minor, roll_to_highest_version=0, prefer_release=1
'Roll forward' enabled with version_compatibility_range [minor]. Looking for the lowest release greater than or equal version to [6.0.0]
Found version [6.0.2]
Applying patch roll forward from [6.0.2] on release only
Inspecting version... [6.0.3]
Inspecting version... [6.0.2]
**Changing Selected FX version from [c:\Program Files\dotnet\x64\shared\Microsoft.NETCore.App\6.0.2] to [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.3]**
Chose FX version [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.3]

App then fails to launch as it's trying to use the arm64 hostfxr now instead of x64 like it's supposed to.

### Regression?

No

### Known Workarounds

set DOTNET_MULTILEVEL_LOOKUP=0

or install a newer x64 runtime

### Configuration

This was an arm64 machine with a 6.0.2 runtime and 6.0.300 SDK.

### Other information

According to Vitek and Andy, it could be we need to downport this fix: https://github.com/dotnet/runtime/pull/59890

**Comment by vitek-karas** [comment]
Can you please confirm what is the error? Above you mention it fails because it's trying to use arm64 `hostfxr`, but that's weird, since the above trace comes from hostfxr. I would expect this to fail because it tries to load arm64 `hostpolicy` into an x64 process.

**Comment by elinor-fung** [comment]
Fixed in 7.0 with https://github.com/dotnet/runtime/pull/68671.
Backported to 6.0.6 with https://github.com/dotnet/runtime/pull/68583.
