### ISSUE TITLE
Optimize Buffer.IndexOfByte for 64-bit

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6731]
Now that dotnet/corefx#11716 adds test coverage for `ByteEqualityComparer.IndexOf`, we should optimize [`Buffer.IndexOfByte`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Buffer.cs#L51). We could do things like have a jump table at the beginning, do a single unaligned read instead of bothering to align the ptr, use 16-byte types, etc.

**Comment by GrabYourPitchforks** [comment]
This implementation is now vectorized.
