### ISSUE TITLE
string.StartsWith() displays unexpected behaviour on Unix?

### ISSUE THREAD

**Issue by desdoades** [dotnet/runtime#67313]
Through an exception in our software I recently got to learn about certain behaviours of string.StartsWith() depending on culture and even operating system. 
Who would have thought that a shorter string can actually start with a longer string 😕 `"A".StartsWith("Aــــــــــ")`.

Now to the question:
Is `"A".StartsWith("A\0")` returning false on Unix expected behaviour?

Opposed to that `"A\0A".EndsWith("AA")`, `"A\0".EndsWith("A")` and `"A".StartsWith("\0A")` all return true on Unix.

**Comment by tarekgh** [comment]
> Is "A".StartsWith("A\0") returning false on Unix expected behaviour?

No. This is a bug.

**Comment by skyoxZ** [comment]
@tarekgh  Are these behaviors defined? Where can I find it?

**Comment by tarekgh** [comment]
@skyoxZ If you are performing linguistic operations (I mean you are not passing StringComparison.Ordina[IgnoreCase], then the behavior will depend on the [UNICODE COLLATION ALGORITHM](https://unicode.org/reports/tr10/). It will be impossible to document all possible cases for all languages. You may look at [ICU Collation](https://unicode-org.github.io/icu/userguide/collation/) doc.

For the specific case mentioned in this issue using the character `\0`. This character is defined as an ignored character for the collation (like if it doesn't exist in the string). You may look at the [Unicode Ignored Characters](https://www.unicode.org/charts/collation/chart_Ignored.html) to see the whole list of the ignored characters.
