### ISSUE TITLE
ConstructorConverter argument cache initialization invoking the wrong method

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#67333]
On a related note, looks like this should be `InitializeParameterCache()`: https://github.com/dotnet/runtime/blob/8f8e8f0493144d87ea06676fec367bdbeeb5ad89/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectWithParameterizedConstructorConverter.Large.cs#L58-L60

_Originally posted by @am11 in https://github.com/dotnet/runtime/issues/60962#issuecomment-953924432_

This looks like an obvious bug, but we have no test coverage for it. Extracting into a separate issue so that it can be evaluated independently.

**Comment by krwq** [comment]
this code path doesn't exist anymore after my changes. Let's see if the same issue resurfaces after my changes
