### ISSUE TITLE
Test failure: JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#67355]
Change https://github.com/dotnet/runtime/pull/66251 introduced a regression in the JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd test, in what appears to be all outerloop job configurations with TieredCompilation=0:

https://dev.azure.com/dnceng/public/_build/results?buildId=1689813&view=results

@SingleAccretion @dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
Fixed in #67360.
