### ISSUE TITLE
When I get the default value of the method parameter as `long` through reflection, the result is `DbNull` instead of `0`

### ISSUE THREAD

**Issue by liuhll** [dotnet/runtime#67364]
### Describe the bug
I defined a method `Task<TestOut> GetById(long id)` to get the metadata of the method parameters to `ParameterInfo` through reflection, but the default value obtained through debug is `NULL`, and the correct default value `0` can not be obtained.

**Comment by danmoseley** [comment]
@liuhll can you please provide minimal self contained code to reproduce?

**Comment by danmoseley** [comment]
@eiriktsarpalis I guess we should delete "needs more information" label - I think it virally came from WPF
