### ISSUE TITLE
[API Proposal]: Enhance RequiresDynamicCode Attribute to apply to class

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#67368]
### Background and motivation

There are scenarios where it makes sense to apply this attribute to a class as discussed in [this PR](https://github.com/dotnet/runtime/pull/67299). In the particular case, the internal class is around runtime code generation and applying at the class level results in a better user experience as opposed to annotating at member level. 

The trimmer equivalent attribute, [RequiresUnreferencedCode](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/RequiresUnreferencedCodeAttribute.cs#L16), already allows the attribute to be applied at class level.

### API Proposal

```diff
 namespace System.Diagnostics.CodeAnalysis
 {
     [AttributeUsage(
         AttributeTargets.Method |
         AttributeTargets.Constructor |
+        AttributeTargets.Class,
         Inherited = false)]
     public partial class RequiresDynamicCodeAttribute: Attribute
     {
     }
 }
```

### API Usage

```C#
[RequiresDynamicCode("The native code for Regex compilation might not be available at runtime.")]
internal abstract class RegexCompiler
```

### Alternative Designs

None and leave the RequiresDynamicCodeAttribute class as is, which would require working around the issue

### Risks

Requires Analyzers build for this attribute and NativeAot compiler to adjust to the enhanced scope.

**Comment by tlakollo** [comment]
I added the api-ready-for-review I don't think we will discuss anything interesting in this PR. I think is only worth discussing this in the API review meeting.

**Comment by bartonjs** [comment]
Looks good as proposed

```diff
 namespace System.Diagnostics.CodeAnalysis
 {
     [AttributeUsage(
         AttributeTargets.Method |
         AttributeTargets.Constructor |
+        AttributeTargets.Class,
         Inherited = false)]
     public partial class RequiresDynamicCodeAttribute: Attribute
     {
     }
 }
```
