### ISSUE TITLE
[ARM64] Consider using LDAPR to implement volatile reads when instruction is available.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#67374]
Historically CLR volatile implements acquire/release semantics (in `memory_order_acq_rel` sense), since that is free on x64. 
On ARMv8+ we use STLR/LDAR, which actually implement `memory_order_seq_cst`. That is stronger than what we have on x64. To have similar `memory_order_seq_cst` on x64 we would need to emit barriers after volatile writes. 

The extra guarantees are also not free. When STLR is followed by LDAR, the pair acts similar to a full barrier with potentially similar costs.

ARMv8.3 introduced a LDAPR instruction that has weaker guarantees, just enough to implement `memory_order_acq_rel`. LDAPR does not wait for previous STLR to complete and if the same location is used in both, does not force the write to be globally observable. This is similar to x64 behavior where reads can be satisfied from a write buffer prior to global visibility. The new instruction can avoid some costs associated with LDAR.

See: https://developer.arm.com/documentation/dui0801/g/A64-Data-Transfer-Instructions/LDAPR?lang=en

Since LDAPR is enough for volatile reads in CLR and is potentially cheaper, we should use it when available.

**Comment by EgorBo** [comment]
I can take a look, I wanted to fix a related issue - we still have numerous of cases where for volatile loads/stores we emit a full memory barrier today
