### ISSUE TITLE
DataContract and derived types missing Equals implementation

### ISSUE THREAD

**Issue by mconnew** [dotnet/runtime#67371]
### Description

When adding types to XsdDataContractExporter using the Export(Type type) method, it fetches the DataContract instance for the type and then adds it to the DataContractSet. The DataContractSet checks to see if it already has a DataContract which matches the StableName (same XML name and namespace), and if it does, checks to see if they are semantically the same DataContract. On .NET Framework, DataContract overrides the Equals(object) method which calls another internal virtual Equals method to compare the two instances. The various DataContract derived types override this second Equals method to compare their unique properties. These Equals methods are missing in .NET Core/.NET which results in object.Equals being used instead, which just does a reference comparison which returns false. This results in an exception being thrown as it's believed that two different DataContracts with the same StableName are trying to be added to the set.

### Reproduction Steps

```c#
var exporter = new XsdDataContractExporter();
exporter.Export(typeof(List<string>));
exporter.Export(typeof(IEnumerable<string>));
```

Although this code throws PlatformNotSupportedException because of another issue around surrogates, I've been able to instantiate the internal DataContractSet class via reflection to work around that problem for CoreWCF (needed to export WSDL).

### Expected behavior

To be able to call Export with multiple different types with equivalent DataContracts.

### Actual behavior

If the PNSE issue is worked around, the above code will currently throw the following exception

```
System.InvalidOperationException: DataContract for type 'System.Collections.Generic.IEnumerable`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' cannot be added to DataContractSet since type 'System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' with the same data contract name 'ArrayOfstring' in namespace 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' is already present and the contracts are not equivalent.
```

### Regression?

This is a regression from .NET Framework

### Known Workarounds

Duplicate all the comparison logic in app code to make the decision before calling Export to avoid this bug.

### Other information

The two methods [here](https://github.com/microsoft/referencesource/blob/4.6.2/System.Runtime.Serialization/System/Runtime/Serialization/DataContract.cs#L2245-L2260) are missing, as well as the overrides of the virtual Equals method.

**Comment by StephenMolloy** [comment]
Fixed by #71752
