### ISSUE TITLE
Support custom type generated marshalling on prior to net7 tfms

### ISSUE THREAD

**Issue by SupinePandora43** [dotnet/runtime#67390]
Repro: (target framework: net6.0)

```cs
[assembly: DisableRuntimeMarshalling]

namespace System.Runtime.InteropServices
{
    [AttributeUsage(AttributeTargets.Assembly)]
    internal sealed class DisableRuntimeMarshallingAttribute : Attribute
    {
        public DisableRuntimeMarshallingAttribute(){}
    }
    // define GeneratedDllImport, NativeMarshalling, CustomTypeMarshaller blah blah blah
}

[CustomTypeMarshaller(typeof(Managed))]
public struct Native
{
    public byte NativeValue;
    public Native(Managed managed)
    {
        NativeValue = managed ? 1 : 0;
    }
}
[NativeMarshalling(typeof(Native))]
public struct Managed
{
    public bool Value;
}

using LibraryImportAttribute = GeneratedDllImportAttribute;

[LibraryImport("Lib")]
// Error: Runtime marshalling must be disabled in this project by applying 'System.Runtime.InteropServices.DisableRuntimeMarshallingAttribute' to the assembly to enable marshalling this type. The generated source will not handle marshalling of parameter 'managed'
public static partial void Method(Managed managed);
```

**Comment by jkoritzinsky** [comment]
As mentioned in Discord, we can't reliably know if types we put into the inner P/Invoke are blittable without the framework-defined `DisableRuntimeMarshallingAttribute`, so we can't accurately support custom type marshallers in downlevel frameworks.

**Comment by SupinePandora43** [comment]
> As mentioned in Discord, we can't reliably know if types we put into the inner P/Invoke are blittable without the framework-defined `DisableRuntimeMarshallingAttribute`, so we can't accurately support custom type marshallers in downlevel frameworks.

`[MarshalUsing]` works without it. So you rely on dotnet7's `DisableRuntimeMarshallingAttribute` to check if custom marshaller's native value isn't blittable? Developer will use net7 as sdk and/or target framework when using it, so it will be noticeable across multiple TFMs regardless if they support `DisableRuntimeMarshalling` or not.

**Comment by AaronRobinsonMSFT** [comment]
@SupinePandora43 The source generator for `DllImport`s is going to be be targeting the .NET 7 TFM as a product and not available in prior TFMs.

> so it will be noticeable across multiple TFMs regardless if they support DisableRuntimeMarshalling or not.

The plan is to have the source generator be available in the .NET 7 ref pack when it is finally productized. If targeting an earlier TFM, it will not be available. This is being some for various reasons and one of the biggest reasons is what @jkoritzinsky mentions above.

**Comment by SupinePandora43** [comment]
> @SupinePandora43 The source generator for `DllImport`s is going to be be targeting the .NET 7 TFM as a product and not available in prior TFMs.
> 
> > so it will be noticeable across multiple TFMs regardless if they support DisableRuntimeMarshalling or not.
> 
> The plan is to have the source generator be available in the .NET 7 ref pack when it is finally productized. If targeting an earlier TFM, it will not be available. This is being some for various reasons and one of the biggest reasons is what @jkoritzinsky mentions above.

It's the most insignificant reason i could think of. There are more critical ones like `Marshal.StringToCoTaskMemUTF8` not available in old TFMs.

Please, don't cause me to copy generated c# to source for older TFMs over and over again.

**Comment by AaronRobinsonMSFT** [comment]
> Please, don't cause me to copy generated c# to source for older TFMs over and over again.

Unfortunately, this is one of those features that will be slowly spread across the ecosystem. The calculus to support older TFMs is non-trivial. Supporting down-level TFMs is going to impose complexity on the UX support as well as analysis in the generator. The question becomes - should we put forth the effort to ensure the UX and analysis can handle a scenario where we support .NET 6 for the next three years or just move forward into the future?

Backporting this kind of support is something we would have likely done in .NET Framework but in .NET Core we are all about moving forward unless we find a high-impact hole or broken scenario. The situation here is annoyance - "copying generated C# source to older TFMs" - rather than blocking.
