### ISSUE TITLE
Why Activator.CreateInstance(Type) returns nullable object?

### ISSUE THREAD

**Issue by zlatanov** [dotnet/runtime#674]
I am trying to use the new C# 8 nullability feature in our new projects and while trying to fix some warnings in regard to Activator.CreateInstance, I found out that it returns nullable object.

But after I looked at the code to see in which case does it really return null because I thought it wasn't possible, it turns out it doesn't. See code:

https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs#L82-L94

Here is the signature of CreateInstanceDefaultCtor:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L3980

Is this something that can be fixed and the annotation to be correct, or is there an obscure case in other runtimes and implementations where Activator.CreateInstance(Type) could possibly return null?

**Comment by slang25** [comment]
Relevant discussion: https://github.com/dotnet/coreclr/pull/23774#discussion_r354785674

**Comment by jkotas** [comment]
Submitted #674 to fix the annotations on the internal implementation details and add some comments.

**Comment by zlatanov** [comment]
Totally forgot about nullable value types and boxing. Now it makes sense.
