### ISSUE TITLE
Async Main, IDisposable, and Exceptions

### ISSUE THREAD

**Issue by mattjohnsonpint** [dotnet/runtime#67407]
### Description

It would appear that `IDisposable` objects registered with `using` statements are disposed *before* exceptions fire when they are called from a console app that uses `async Task Main`.  I'm not sure if this is by design or a bug.

### Reproduction Steps

```csharp
namespace ConsoleApp1;

public class Program
{
    static async Task Main()
    {
        using var _ = new MyUnhandledExceptionHandler();
        await DoSomethingAsync();
    }

    static async Task DoSomethingAsync()
    {
        await Task.Yield();
        throw new Exception("Test Exception");
    }
}

public class MyUnhandledExceptionHandler : IDisposable
{
    public MyUnhandledExceptionHandler()
    {
        AppDomain.CurrentDomain.UnhandledException += OnCurrentDomainOnUnhandledException;
    }
    
    public void Dispose()
    {
        AppDomain.CurrentDomain.UnhandledException -= OnCurrentDomainOnUnhandledException;
    }

    private void OnCurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs args)
    {
        if (args.ExceptionObject is Exception e)
            Console.WriteLine($"*** Caught {e.Message} ***");
    }
}
```

### Expected behavior

The message `*** Caught Test Exception ***` should appear on the command line.

### Actual behavior

No message is written.

The `MyUnhandledExceptionHandler` is disposed *before* the exception fires, and thus nothing is registered with `AppDomain.CurrentDomain.UnhandledException`.

### Known Workarounds

Swap out the async `Main` method with this synchronous one and it works fine:

```csharp
static void Main()
{
    using var _ = new MyUnhandledExceptionHandler();
    DoSomethingAsync().GetAwaiter().GetResult();
}
```

### Configuration

Probably not platform specific, but I tested on both:
.NET 6.0.201 macOS arm64
.NET 6.0.201 Windows x64

### Other information

This might just be by design. I'm not sure.  If it is, clarification in the following doc would be appreciated.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main

**Comment by stephentoub** [comment]
It's by design.  What you've written is basically this structure:
```C#
public class Program
{
    static void Main()
    {
        Exception? exc = null;
        try
        {
            // body of main method
            using var _ = new MyUnhandledExceptionHandler();
            throw new Exception("Test Exception");
        }
        catch (Exception e)
        {
            exc = e; // store exception into task in compiler-generated MoveNext method
        }

        if (exc is not null) throw exc; // wait on task in sync Main entry point
    }
}

public class MyUnhandledExceptionHandler : IDisposable
{
    public MyUnhandledExceptionHandler() => AppDomain.CurrentDomain.UnhandledException += OnCurrentDomainOnUnhandledException;
    public void Dispose() => AppDomain.CurrentDomain.UnhandledException -= OnCurrentDomainOnUnhandledException;

    private void OnCurrentDomainOnUnhandledException(object sender, UnhandledExceptionEventArgs args)
    {
        if (args.ExceptionObject is Exception e)
            Console.WriteLine($"*** Caught {e.Message} ***");
    }
}
```
Async methods catch all thrown exceptions and store them into the returned Task.  So your using is dutifully running Dispose, the exception is being stored into the task, and then that exception is being rethrown as part of the code waiting on the task.

**Comment by jkotas** [comment]
> This might just be by design. I'm not sure. If it is, clarification in the following doc would be appreciated.
> https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.1/async-main

I do not see anything to clarify in this doc. The behavior you are seeing applies to all async methods as @stephentoub pointed out.

**Comment by mattjohnsonpint** [comment]
Thanks for the clarity. I appreciate it!
