### ISSUE TITLE
Test failure System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67408]
Run: [runtime-libraries-coreclr outerloop 20220331.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1692443&view=ms.vss-test-web.build-test-results-tab&runId=46222920&paneView=debug&resultId=101954)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.11.Amd64.ClientPre.Open

- System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(useShellExecute: True)
- System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent(useShellExecute: True)
- System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute
```
**Error message:**
```
Assert.StartsWith() Failure:
Expected: StartInfo_NotepadWithContent_withArgumentList_1282_1e5fa2e8
Actual:


Stack trace
   at System.Diagnostics.Tests.ProcessStartInfoTests.VerifyNotepadMainWindowTitle(Process process, String filename) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1337
   at System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_NotepadWithContent_withArgumentList(Boolean useShellExecute) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 1301
```

**Comment by danmoseley** [comment]
On Windows 11 it consistently fails this way; on other versions it is stable.


```kusto
TestResults
| join kind=inner WorkItems on WorkItemId
| join kind=inner Jobs on JobId
//| where Method == "StartInfo_NotepadWithContent_withArgumentList"
| where Type == "System.Diagnostics.Tests.ProcessStartInfoTests"
| where Finished >= now(-50d)
| where Result == "Fail"
| where Message startswith "Assert.S"
| project //Type,
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  Pipeline_Configuration = tostring(parse_json(Properties).configuration),
  OS = QueueName,
  Arch = tostring(parse_json(Properties).architecture),
 // Test = Type1,
 Result,Finished,
  //Duration,
 // Method,
 // Build = tostring(parse_json(Properties).BuildNumber),
  Message//,
 // StackTrace
```

|Pipeline|Pipeline_Configuration|OS|Arch|Result|Finished|Message|
|---|---|---|---|---|---|---|
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-27 15:00:32.8020000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_withArgumentList_1282_150e1420<br>Actual:   |
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-27 15:00:32.8020000|Assert.StartsWith() Failure:<br>Expected: StartInfo_TextFile_ShellExecute_1110_48661182<br>Actual:   |
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-27 15:00:32.8020000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_1071_578aafc9<br>Actual:   |
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-29 08:26:55.3080000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_withArgumentList_1282_aff61c44<br>Actual:   |
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-29 08:26:55.3080000|Assert.StartsWith() Failure:<br>Expected: StartInfo_TextFile_ShellExecute_1110_9fc526f0<br>Actual:   |
|runtime-libraries-coreclr outerloop|Debug|windows.11.amd64.clientpre.open|x64|Fail|2022-03-29 08:26:55.3080000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_1071_182887a3<br>Actual:   *StartInfo_NotepadWithContent_1071_182887a...|
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x86|Fail|2022-03-31 12:18:12.3910000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_withArgumentList_1282_1e5fa2e8<br>Actual:   |
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x86|Fail|2022-03-31 12:18:12.3910000|Assert.StartsWith() Failure:<br>Expected: StartInfo_TextFile_ShellExecute_1110_72994153<br>Actual:   |
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x86|Fail|2022-03-31 12:18:12.3910000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_1071_90a3c17e<br>Actual:   |
|runtime-libraries-coreclr outerloop-windows|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-03-31 12:48:59.8350000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_withArgumentList_1282_b22921bf<br>Actual:   |
|runtime-libraries-coreclr outerloop-windows|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-03-31 12:48:59.8350000|Assert.StartsWith() Failure:<br>Expected: StartInfo_TextFile_ShellExecute_1110_994e0a5d<br>Actual:   |
|runtime-libraries-coreclr outerloop-windows|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-03-31 12:48:59.8350000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_1071_c330cafc<br>Actual:   |
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-04-02 12:43:07.9510000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_withArgumentList_1282_8f961dce<br>Actual:   |
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-04-02 12:43:07.9510000|Assert.StartsWith() Failure:<br>Expected: StartInfo_TextFile_ShellExecute_1110_7666b22f<br>Actual:   |
|runtime-libraries-coreclr outerloop|Release|windows.11.amd64.clientpre.open|x64|Fail|2022-04-02 12:43:07.9510000|Assert.StartsWith() Failure:<br>Expected: StartInfo_NotepadWithContent_1071_78825ac0<br>Actual:   |
