### ISSUE TITLE
TryAdd* extensions compare based on service, not implementation

### ISSUE THREAD

**Issue by curt-w** [dotnet/runtime#67404]
Right now, it seems the TryAdd* extension methods determine whether or not to register a given service implementation based on the service type.

Provided the following example, we can inject the service implementations in constructor via. "`IEnumerable<IWidgetService> widgetServices`" parameter.

```
services.AddTransient<IWidgetService, WidgetServiceA>();
services.AddTransient<IWidgetService, WidgetServiceB>();
```

When a constructor injects an IEnumerable<IWidgetService>, it will receive an enumerable of both concrete service implementations; that is an enumerable containing WidgetServiceA and WidgetServiceB.

If we move these to use extension methods, i.e. TryAddTransient as follows, the constructor that injects IEnumerable<IWidgetService> will only receive an enumerable with only one concrete implementation - the first one registered which would be WidgetServiceA.

```
services.TryAddTransient<IWidgetService, WidgetServiceA>();
services.TryAddTransient<IWidgetService, WidgetServiceB>();
```

I believe the TryAdd* methods should rather check the concrete implementation of the service and only omit registration if that concrete registration already exists.

**Baseline example**
```
services.AddTransient<IWidgetService, WidgetServiceA>();
services.AddTransient<IWidgetService, WidgetServiceA>();
services.AddTransient<IWidgetService, WidgetServiceB>();
```

This would result in three service registrations within the IEnumerable<IWidgetService>, two WidgetServiceA implementations and one WidgetServiceB implementation. This behavior I would expect.

**Extension example**
```
services.TryAddTransient<IWidgetService, WidgetServiceA>();
services.TryAddTransient<IWidgetService, WidgetServiceA>();
services.TryAddTransient<IWidgetService, WidgetServiceB>();
```

Current results - injecting an IEnumerable<IWidgetService> results in an enumerable object with one concrete implementation, the first one registered which is WidgetServiceA.

Expected results - when injecting an IEnumerable<IWidgetService> should result in an enumerable object that has two concrete implementations, one WidgetServiceA implementation and one WidgetServiceB implementation. On the second line when we register WidgetServiceA a second time, the TryAdd* logic should recognize that WidgetServiceA has already been registered as a concrete IWidgetService and omit registration.

Use case - provided we have a "core" framework that is consumed by two other frameworks "B" and "C"; both frameworks "B" and "C" call into the "core" framework to register service dependencies. Consuming applications may reference both frameworks "B" and "C", calling into each of their service registration extensions... since both "B" and "C" frameworks call into the "core" framework service registration, we need to utilize the TryAdd* registration extensions to avoid the "core" services being registered twice.

**Comment by davidfowl** [comment]
This is by design and there’s a TryAddEnumerable that does just this. With this overload, you need to use ServiceDescriptor.* static methods to create the descriptor

**Comment by curt-w** [comment]
Thank you for the clarification - apologies I was not able to find this direction via. research.
