### ISSUE TITLE
RyuJIT SIMD:  Review SIMD API usage in Asp.Net Kestrel server

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6741]
This is a place holder issue to review and identify all the opportunities for improving SIMD codegen or adding new intrinsics that would benefit Asp.Net scenarios.

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by tannergooding** [comment]
Closing this as there isn't anything directly actionable.

Issues should be opened for individual inefficiencies to ensure they can be correctly investigated, tracked, and fixed.
