### ISSUE TITLE
List<T>.IndexOf outputs incorrect error message

### ISSUE THREAD

**Issue by HeinziAT** [dotnet/runtime#67423]
### Description

The error message returned by `List<T>.IndexOf` if an invalid index is used is incorrect. As it is currently implemented, the size of the collection (`2` in the repro example below) is a valid input for `index`.

### Reproduction Steps

```
// list of length 2
var list = new List<string>() { "a", "b" };

Console.WriteLine(list.IndexOf("a", 2)); // yields -1
Console.WriteLine(list.IndexOf("a", 3)); // yields an error
```

([fiddle](https://dotnetfiddle.net/mR9tGi))

### Expected behavior

An ArgumentException with the following error text is thrown:

Index was out of range. Must be non-negative and **less than or equal to** the size of the collection. (Parameter 'index')

(Alternatively: Must be non-negative and **not greater than** the size of the collection.)

### Actual behavior

An ArgumentException with the following error text is thrown:

Index was out of range. Must be non-negative and **less than** the size of the collection. (Parameter 'index')

### Configuration

Tested with dotnetfiddle, with all currently available compilers (.NET 4.7.2, Roslyn 4.0, .NET 6).

### Other information

I **do not** suggest to change the behavior of `IndexOf` - the current behavior is the only sane and consistent one. However, the error message (and the documentation of `List<T>.IndexOf`) should be updated to reflect the actual behavior.

**Comment by B1Z0N** [comment]
From what I see we are pretty much inconsistent in usage of `ThrowHelper.ThrowArgumentOutOfRange_IndexException` in corelib and other libraries. For example just on `List` in the same file see [current `IndexOf` example](https://github.com/dotnet/runtime/blob/c3843c592eb3dfdcb0a7849c6f4ba4e9fc2288a0/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L662) and [this indexer here](https://github.com/dotnet/runtime/blob/c3843c592eb3dfdcb0a7849c6f4ba4e9fc2288a0/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L150). 

`ThrowHelper.ThrowArgumentOutOfRange_IndexException` uses `SR.ArgumentOutOfRange_Index` internally. And that one in turn belongs to resource files. I think that perhaps we just should split it into two: 
* `SR.ArgumentOutOfRange_IndexLt` for errors like that in List indexer and other "throw if index >= size" cases
* `SR.ArgumentOutOfRange_IndexLe` for errors like current `IndexOf` and other "throw if index > size" cases

Of course we also should not forget to update docs.

**Comment by Clockwork-Muse** [comment]
Naive guess: it's implemented this way to support striding/slicing:

```csharp
int previousIndex = 0;
int index = commaDelimitedString.IndexOf(",", 0);

while(index > -1)
{
    handleElement(commaDelimitedString.Substring(previousIndex, index));
    previousIndex = index;
    index = commaDelimitedString.IndexOf(",", index + 1);
}
```

...also, consider the case when the string is empty.

**Comment by eiriktsarpalis** [comment]
@B1Z0N happy to accept a PR that improves this.
