### ISSUE TITLE
[API Proposal]: Add architecture PPC64le to Architecture enum

### ISSUE THREAD

**Issue by Sapana-Khemkar** [dotnet/runtime#67428]
### Background and motivation

All architectures, whether officially Microsoft supported or not, need to exist within the System.Runtime.InteropServices.Architecture enum. We want to introduce a new community-supported architecture ppc64le.
The implementation PR is https://github.com/dotnet/runtime/pull/68809

### API Proposal

```diff
namespace System.Runtime.InteropServices
{
    public enum Architecture
    {
        X86 = 0,
        X64 = 1,
        Arm = 2,
        Arm64 = 3,
        Wasm = 4,
        S390x = 5,
        LoongArch64 = 6,
        Armv6 = 7,
+       PPC64le = 8,
    }
}

```

### API Usage

```csharp
 case Architecture.PPC64le:
    Assert.Equal(Architecture.PPC64le, processArch);
    break;
```

**Comment by MichalStrehovsky** [comment]
Why all caps? The architecture seems to be referred to as PowerPC everywhere, not POWERPC (e.g. wikipedia: https://en.wikipedia.org/wiki/PowerPC).

**Comment by Sapana-Khemkar** [comment]
> Why all caps? The architecture seems to be referred to as PowerPC everywhere, not POWERPC (e.g. wikipedia: https://en.wikipedia.org/wiki/PowerPC).

Agree. Changed

**Comment by AaronRobinsonMSFT** [comment]
@Sapana-Khemkar Thanks for the suggestion. It would be helpful to elaborate on the goals of adding this and how it would be supported. Is this the first step in providing community support for PowerPC? This is a non-trivial process and understanding how this would occur would be helpful.

**Comment by tannergooding** [comment]
Should this be `PowerPC` or `PowerPCFP` (or some variation that indicates `PowerPC + Floating Point` support). They are considered different by the PE file format: <https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types>

**Comment by akoeplinger** [comment]
Or `PowerPC64LE` to make it clear it's the little endian version.

**Comment by MichalStrehovsky** [comment]
> Should this be `PowerPC` or `PowerPCFP` (or some variation that indicates `PowerPC + Floating Point` support). They are considered different by the PE file format: <https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#machine-types>

We don't represent float support in `Architecture.Arm` - what makes PowerPC64 special in this respect?

> Or `PowerPC64LE` to make it clear it's the little endian version.

We don't represent endianness in `Architecture.Arm` - what makes PowerPC64 special in this respect?

**Comment by tannergooding** [comment]
> We don't represent float support in Architecture.Arm - what makes PowerPC64 special in this respect?

Other architectures/ABIs are differentiating, including the PE file format. That may or may not be important when considering the Architecture enum. It's a consideration that should be made.

**Comment by akoeplinger** [comment]
> We don't represent endianness in Architecture.Arm - what makes PowerPC64 special in this respect?

While Arm technically can run in big-endian mode, practically all implementations and ports are for little-endian (e.g. there's no big-endian Linux support) so the distinction is less important.

PowerPC on the other hand shipped as primarily big-endian for much of its lifetime while the little-endian `ppc64le` is a relatively recent addition which I think might warrant the distinction in the enum name.

**Comment by Sapana-Khemkar** [comment]
As per my understanding LE is not required as we can check using `IsLittleEndian`. Also we are supporting it only on Linux which is LE only. Also found similar discussion [here](https://github.com/dotnet/runtime/issues/26634)

**Comment by BillSeurer** [comment]
powerpc64 (sometimes ppc64) is used by other open source stuff for big endian.
powerpc64le (sometimes ppc64le) is used for little endian.

And BE is supported on Linux.  I use powerpc64 BE Linux servers all the time.

**Comment by AaronRobinsonMSFT** [comment]
Labeling this as "Future" is not meant to indicate it isn't important but more bookkeeping on our side. As soon as all stakeholders agree on what should be the correct name, we can flip this to "ready for review".

**Comment by janani66** [comment]
> powerpc64 (sometimes ppc64) is used by other open source stuff for big endian. powerpc64le (sometimes ppc64le) is used for little endian.
> 
> And BE is supported on Linux. I use powerpc64 BE Linux servers all the time.

Agreed. We should use the label PowerPCLE. to make it clear that this is for the little endian powerpc64 platform.

**Comment by Sapana-Khemkar** [comment]
I think in that case we should use PowerPC64le which indicates 64-bit power pc and little endian

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Janani Janakiraman ***@***.***>
Sent: Monday, April 4, 2022 10:14 PM
To: dotnet/runtime ***@***.***>
Cc: Sapana Khemkar ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [dotnet/runtime] [API Proposal]: Add architecture PowerPC64 to Architecture enum (Issue #67428)

powerpc64 (sometimes ppc64) is used by other open source stuff for big endian. powerpc64le (sometimes ppc64le) is used for little endian. And BE is supported on Linux. I use powerpc64 BE Linux servers all the time. Agreed. We should use the ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

powerpc64 (sometimes ppc64) is used by other open source stuff for big endian. powerpc64le (sometimes ppc64le) is used for little endian.

And BE is supported on Linux. I use powerpc64 BE Linux servers all the time.

Agreed. We should use the label PowerPCLE. to make it clear that this is for the little endian powerpc64 platform.

**Comment by Sapana-Khemkar** [comment]
Are we all okay with enum name PowerPC64le?

**Comment by MichalStrehovsky** [comment]
I'm not the decision maker but I still don't see the reason to include endianness. We don't include it for ARM. We also don't include float mode on ARM (even though Linux does distinguish soft and hard float modes when referring to the ISA and we do support both on the VM side).

This enum has so far represented the ISA, not the binary interface (see also https://github.com/dotnet/runtime/issues/26634#issuecomment-400894843). Adding the endianness doesn't fit with the rest.

**Comment by Sapana-Khemkar** [comment]
If I change Architecture enum to PowerPC64 then `System.Runtime.InteropServices.RuntimeInformationTests.RuntimeIdentifierTests.VerifyOSRid` testcase fails.
This test case compares Architecture enum value and the architecture component of the RID.  On Power machine Linux reported architecture name is `ppc64le`.
So if we go as per this test case we have to keep enum name as PPC64LE or Ppc64le. Otherwise test case needs to be changed.

**Comment by BillSeurer** [comment]
Do the other architectures match the linux reported architecture names?  In any case ppc64le should work fine.

**Comment by BillSeurer** [comment]
For what it is worth I checked on my mac and the architecture there is reported as "i386" and on my old Linux thinkpad it is reported as "x86_64" neither of which seem to match the X86 in the enum list.

**Comment by MichalStrehovsky** [comment]
We use the `armel` RID for ARM-softfloat ABI and `arm` RID for ARM-hardfloat (or armhf in Linux lingo) ([source](https://github.com/dotnet/runtime/blob/c78bf2f522b4ce5a449faf6a38a0752b642a7f79/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L1529-L1545)). There's only one member of the `Architecture` enum for ARM, despite supporting two ABIs and having representation for them in the form of a RID.

I don't think `Architecture` represents ABI or has a relationship with the RID.

**Comment by uweigand** [comment]
> We use the `armel` RID for ARM-softfloat ABI and `arm` RID for ARM-hardfloat (or armhf in Linux lingo) ([source](https://github.com/dotnet/runtime/blob/c78bf2f522b4ce5a449faf6a38a0752b642a7f79/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L1529-L1545)). There's only one member of the `Architecture` enum for ARM, despite supporting two ABIs and having representation for them in the form of a RID.
> 
> I don't think `Architecture` represents ABI or has a relationship with the RID.

Well, there is a test case explicitly verifying the relationship between `Architecture` and the RID: https://github.com/dotnet/runtime/blob/a4d45b2c8ed201d191ed02038b7b28236e22dbf7/src/libraries/System.Runtime.InteropServices.RuntimeInformation/tests/RuntimeIdentifierTests.cs#L18

I can't say whether anything else relies on that relationship, but if it's not supposed to be there, that test case should be fixed.

**Comment by uweigand** [comment]
Also, I'm not convinced that the ARM soft-float vs. hard-float precedent is really comparable to BE vs. LE Power.   In the ARM case, we have variant ABIs that are at least to some extent compatible: you can run both soft-float and hard-float binaries on the same Linux system, and in many cases (e.g. if there's no floating-point parameters) you can even link them together.

BE vs. LE Power on the other hand are completely incompatible.  On a BE Linux kernel you can only run BE binaries; on a LE kernel you can run only LE binaries.  There is absolutely no way to link BE and LE objects together, or have BE and LE code interact in any other way.   They really act for all practical purposes like completely different architectures, so I don't quite see what the benefit would be in treating them as "one" architecture.

**Comment by MichalStrehovsky** [comment]
> Well, there is a test case explicitly verifying the relationship between Architecture and the RID

That test happens to work for the architectures we run tests on. Armel is community supported.

Armbe RID for big endian arm would be in the same boat if it's ever added.

**Comment by janani66** [comment]
What further information is needed to close on this issue? Since the Power BE and LE are completely incompatible like Ulrich mentioned, including the endianness in the name is preferred.

**Comment by gerrith3** [comment]
Throughout thousands of communities, we use the ppc64le tag to identify our architecture.  There is the historical big endian architecture on linux which IBM doesn't support, although various communities still do, including the older mono.  We also have AIX and IBM i people who have done the old mono and have expressed some interest in getting full .NET on those architectures which are big endian, along with a different API, different libraries, etc.  They are about as much alike as Windows and Linux now.  I would strongly recommend using a ppc64le variant for this.

**Comment by teo-tsirpanis** [comment]
@AaronRobinsonMSFT (or someone else), can this move forward? Adding community support for PPC64le is underway. You can decide on the name at the API review.

**Comment by YohanSciubukgian** [comment]
Could you also consider adding support for ppc 32 bits ?
Cf : #26634

**Comment by Sapana-Khemkar** [comment]
@AaronRobinsonMSFT @jkoritzinsky can you please review this?

**Comment by AaronRobinsonMSFT** [comment]
Will try to push on this to get it through API review ASAP.

**Comment by MichalStrehovsky** [comment]
> Will try to push on this to get it through API review ASAP.

API review board should spend some time discussing the purpose of this enum.

RID and Architecture are currently disconnected so if we want a 1:1 relationship with the RID like the comments are asking for (adding PowerPC64LE instead of PowerPC64), we might want to consider adding `Architecture.Armel` for Samsung-supported variants at the same time for parity.

The armel RID already exists (it's solving the problem with native assets @directhex  refers to because it's the same issue), but we don't have an `Architecture` enum member for armel.

**Comment by Sapana-Khemkar** [comment]
@AaronRobinsonMSFT  @MichalStrehovsky any update on this. When API review board meets?

**Comment by AaronRobinsonMSFT** [comment]
@Sapana-Khemkar This is on the docket for me to rally support for again. Some questions that keep coming up are around RIDs - that particular question is causing a fair bit of debate. Please ping me tomorrow if I don't respond here later today.

**Comment by teo-tsirpanis** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Thanks @teo-tsirpanis, have not forgotten about this. I think we've reached a point where we can move forward. @directhex is going to help guide this through the API review. They will set the issue to blocking when it aligns with their availability.

**Comment by Sapana-Khemkar** [comment]
> Thanks @teo-tsirpanis, have not forgotten about this. I think we've reached a point where we can move forward. @directhex is going to help guide this through the API review. They will set the issue to blocking when it aligns with their availability.

Thanks @AaronRobinsonMSFT for update

**Comment by bartonjs** [comment]
* We had a bit of a question of "is the -LE suffix necessary?" and it seems like most systems make a distinction between a ppc64 and a ppc64le, so "yes".
* For naming consistency and .NET's naming guidelines, we changed the casing to only the initial P being capital (`Ppc64le`).

```diff
namespace System.Runtime.InteropServices
{
    public enum Architecture
    {
        X86 = 0,
        X64 = 1,
        Arm = 2,
        Arm64 = 3,
        Wasm = 4,
        S390x = 5,
        LoongArch64 = 6,
        Armv6 = 7,
+       Ppc64le = 8,
    }
}
```
