### ISSUE TITLE
System.Drawing.EnableUnixSupport runtime switch has no effect when dotnet run

### ISSUE THREAD

**Issue by landall** [dotnet/runtime#67439]
### Description

AlmaLinux 8
dotnet 6.0.103
x64

cd bin/Release/net6.0/linux-x64 && dotnet XXXX.dll         works
dotnet run                                                                            normally fails, sometimes works

I don't know the difference between the two way clearly.

### Reproduction Steps

Add FreeSpire.Doc to your webapi project and make a demo to convert a docx to pdf.
Add System.Drawing.EnableUnixSupport : true according to the document of .net 6

### Expected behavior

generate a document.

### Actual behavior

Exception with a hint than System.Drawing.Common is not supported on this platform when I use "dotnet run", sometimes.
works sometimes.

**Comment by landall** [comment]
@dotnet/area-system-drawing

**Comment by ViktorHofer** [comment]
@teo-tsirpanis would you like to help with this and check if Drawing.Common's support switch doesn't work with 6.0?

**Comment by landall** [comment]
> Thanks for asking me @ViktorHofer. I don't have a Linux development environment ready but upon looking at 6.0's source code I found nothing off place. I suspect the `AppContext` switch was set too late.
> 
> @landall can you provide a sample program that reproduces the bug?

http://freecst.azurewebsites.net/testFreeSpireDoc.zip

you can try this one.
I have added a README.txt in it.

**Comment by teo-tsirpanis** [comment]
Can you add the following lines on your program and tell us what is printed on the console?

``` csharp
AppContext.TryGetSwitch("System.Drawing.EnableUnixSupport", out bool isSDCEnabled);
Console.WriteLine(isSDCEnabled);
```

**Comment by teo-tsirpanis** [comment]
And if it fails again, can you please write the stacktrace?

---

Everything about setting the `AppContext` switch seems correct, especially given that it works on self-contained deployments. I suspect this is not an issue of `System.Drawing.Common` per se. 🤔

**Comment by landall** [comment]
> Can you add the following lines on your program and tell us what is printed on the console?
> 
> ```cs
> AppContext.TryGetSwitch("System.Drawing.EnableUnixSupport", out bool isSDCEnabled);
> Console.WriteLine(isSDCEnabled);
> ```

dotnet run  --> True, Exception
dotnet publish && dotnet bin/Debug/net6.0/test.dll  --> True, Exception
dotnet publish -r linux-x64 && dotnet bin/Debug/net6.0/linux-x64/test.dll --> True, works.

**Comment by landall** [comment]
Unhandled exception. System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.
   at System.Drawing.Text.FontCollection..ctor()
   at System.Drawing.Text.PrivateFontCollection..ctor()
   at spr∏..ctor()
   at spr∇..ctor(spr∡ A_0, SizeF A_1, Graphics A_2)
   at spr⇾.ᜓ()
   at spr⇾.ᜀ(IDocument A_0)
   at spr≖.ᜀ(Document A_0, Stream A_1, ToPdfParameterList A_2)
   at Spire.Doc.Document.ᜅ(String A_0, ToPdfParameterList A_1)
   at Spire.Doc.Document.ᜆ(String A_0)
   at Program.<Main>$(String[] args) in /root/test/Program.cs:line 10
Aborted (core dumped)


> And if it fails again, can you please write the stacktrace?
> 
> Everything about setting the `AppContext` switch seems correct, especially given that it works on self-contained deployments. I suspect this is not an issue of `System.Drawing.Common` per se. 🤔

**Comment by danmoseley** [comment]
Stepping back a bit @landall could you use an alternative library? The reason it's disabled by default is that it's deprecated - for one reason, because the Unix experience is not high quality. In 7.0 it's removed entirely, so it's a dead end.

If you just want to do something quick then you could try using 3.1. No switch required there. It is in support until later this year.

**Comment by qlikTERror** [comment]
I have this very problem in Windows with System.Drawing.Common 5.0.2 and a net5 console project with the only line in it:

Image.FromFile(args[0])

**Comment by qlikTERror** [comment]
> I have this very problem in Windows with System.Drawing.Common 5.0.2 and a net5 console project with the only line in it:
> 
> Image.FromFile(args[0])

I fought with this issue for some days before writing the previous comment. In my case I found the solution. 

There was an unknown import in our solution that would import the following property:
```
  <PropertyGroup>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>
```

This would make run the process with the platform agnostic version of System.Drawing.Common that would result in PlatformNotSupportedException all over the place.

Removing that property or setting it to true restore the expected behavior.
