### ISSUE TITLE
[API Proposal]: CollectionUtils class for help collection operation

### ISSUE THREAD

**Issue by sefacan** [dotnet/runtime#67433]
### Background and motivation

Always we create collection utils class into our project because dotnet framework doesn't have some helper method like AreEqual, IsEmpty, IsNotEmpty...

It would be nice if we were having these methods/classes

### API Proposal

```C#
namespace System.Collections;

public class CollectionUtils
{
    public static bool AreEqual<T>(IEnumerable<T> items, IEnumerable<T> otherItems)
    {
        return new HashSet<T>(items)
            .SetEquals(otherItems);
    }

    public static bool IsEmpty(IEnumerable items) => items == null || !items.GetEnumerator().MoveNext();

    public static bool IsNotEmpty(IEnumerable items) => !IsEmpty(items);
}
```

### API Usage

```C#
// Fancy the value
var list1 = new List<int>();
var list2 = new List<int>();
list2.Add(22);

if(CollectionUtils.AreEqual(list1, list2))
{
   //do something
}

if(CollectionUtils.IsEmpty(list1))
{
   //do something
}

if(CollectionUtils.IsNotEmpty(list2))
{
   //do something
}

```

**Comment by Tornhoof** [comment]
What's wrong with https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sequenceequal?view=net-6.0?

**Comment by teo-tsirpanis** [comment]
And there is https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=net-6.0#system-linq-enumerable-any-1(system-collections-generic-ienumerable((-0))) for `IsEmpty`. Doesn't work on non-generic enumerables though.

**Comment by sefacan** [comment]
Null check and size check nice than any.

**Comment by eiriktsarpalis** [comment]
Your `IsEmpty` method can be expressed with current APIs using `source?.Any() == false`. The proposed `AreEqual` method uses set equality, which is not a standard definition of equality for enumerables. 

We have proposals in place for adding sequence equality methods, see https://github.com/dotnet/runtime/issues/44796.
