### ISSUE TITLE
[API Proposal]: Of method for List

### ISSUE THREAD

**Issue by sefacan** [dotnet/runtime#67431]
### Background and motivation

It would be usable `Of` method for initialize a list with item(s).

### API Proposal

```C#
namespace System.Collections.Generic
{
    public class List<T> : IEnumerable<T>
    {
        public List<T> Of(params T[] items)
       {
             var list = new List<T>(items.Length);
             list.AddRange(items);
             return list;
       }
    }
}
```

### API Usage

```C#
// Init a list with items
var list = List.Of(1,2,3);
```

**Comment by theodorzoulias** [comment]
> ```cs
> // Init a list with items
> var list = List.Of(1,2,3);
> ```

Regarding this example: shouldn't the `List` be a `static` non-generic class?

**Comment by KeterSCP** [comment]
What is the problem with collection initializer?

```C#
var list = new List<int> { 1, 2, 3 };
```

**Comment by sefacan** [comment]
> > ```cs
> > // Init a list with items
> > var list = List.Of(1,2,3);
> > ```
> 
> Regarding this example: shouldn't the `List` be a `static` non-generic class?

Ah yes it must be static and non-generic list.

```cs
    public class List
    {
        public static List<T> Of<T>(params T[] items)
       {
             var list = new List<T>(items.Length);
             list.AddRange(items);
             return list;
       }
    }
```

**Comment by theodorzoulias** [comment]
> What is the problem with collection initializer?
> 
> ```cs
> var list = new List<int> { 1, 2, 3 };
> ```

@KeterSCP according to [SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWoGYEBMCiA7FgN5ZzWEFU2WY3NwD6cAvHAHYCmA7nAAyASwDOAFwA8I7hIB8ccnEQAaOAXX4AvhiY1tWQ5iA===), this translates to:

```C#
List<int> list = new List<int>();
list.Add(1);
list.Add(2);
list.Add(3);
```

It doesn't initialize efficiently the capacity of the list.

**Comment by KeterSCP** [comment]
> > What is the problem with collection initializer?
> > ```cs
> > var list = new List<int> { 1, 2, 3 };
> > ```
> 
> @KeterSCP according to [SharpLab](https://sharplab.io/#v2:CYLg1APgAgDABFAjAFgNwFgBQWoGYEBMCiA7FgN5ZzWEFU2WY3NwD6cAvHAHYCmA7nAAyASwDOAFwA8I7hIB8ccnEQAaOAXX4AvhiY1tWQ5iA===), this translates to:
> 
> ```cs
> List<int> list = new List<int>();
> list.Add(1);
> list.Add(2);
> list.Add(3);
> ```
> 
> It doesn't initialize efficiently the capacity of the list.

Agree, but IMO creating such APIs that save 1 line of code is not worth it.

**Comment by stephentoub** [comment]
> It doesn't initialize efficiently the capacity of the list.

But this does:
```C#
var list = new List<int>(3) { 1, 2, 3 };
```

The proposed alternative also allocates an array just to pass in 1, 2, and 3, which is itself an inefficiency.  If we _really_ wanted a params-based initialization for list, I expect we'd either wait for the C# `params IEnumerable<T>` feature and just add `params` to the existing `IEnumerable<T>`-based ctor, or we'd wait for the C# `params Span<T>` feature, and add a new ctor accepting a `ReadOnlySpan<T>`.  I don't see us adding the proposed method.

**Comment by Symbai** [comment]
> But this does:

👀Can we please get an analyzer rule for this in VS? I'm sure I am not the only one who didn't know that this would matter on initialization.

**Comment by tfenise** [comment]
One could add more elements to a `List<T>` after initialization. For example:
```
var list = new List<int>() { 0 };
for (int i = 1; i <= 100; i++)
{
    list.Add(i);
}
```
An analyzer that suggests the first line to be changed to `var list = new List<int>(1) { 0 };` is not really helpful here.

**Comment by eiriktsarpalis** [comment]
Related to https://github.com/dotnet/csharplang/issues/5354

Re: the original proposal, naming collection initializers `Of` is not an idiom widely employed in .NET libraries.

**Comment by Symbai** [comment]
> One could add more elements to a `List<T>` after initialization. For example:

An analyzer is smart enough to read more than just a single line and check that and only make recommendations when it's useful. I didn't know that I have to explicit write that but here you go.

**Comment by tfenise** [comment]
An analyzer cannot figure out what happens with the `List<T>` if the code calls some arbitrary method.
```
var list = new List<int>() { 0 };
SomeMethod(list);
```

**Comment by tfenise** [comment]
The [DefaultCapacity](https://source.dot.net/System.Private.CoreLib/R/5a4951f47cc777aa.html) of `List<T>` is currently 4. If a collection initializer initializes a `List<T>` with more than 4 elements (`new List<int>() { 0, 1, 2, 3, 4 }`), it can be considered beneficial in performance to suggest changing it to `new List<int>(5) { 0, 1, 2, 3, 4 }`, but a developer may still favor omitting the length (`new List<int>() { 0, 1, 2, 3, 4 }`) for other reasons like conciseness (like the syntax `new int[] { 0, 1, 2, 3, 4 }`). Some may consider such an analyzer to be useful, some may not.

The C# compiler could consider optimizing `new List<int>() { 0, 1, 2, 3, 4 }` by compiling it as `new List<int>(5) { 0, 1, 2, 3, 4 }`. This does not sacrifice conciseness, but I don't know if the C# compiler is willing to take such library dependency.
