### ISSUE TITLE
MemoryMarshal.Create{ReadOnly}Span should validate length >= 0

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#67443]
I don't know why we left out that check, but we apparently did.  Span's pointer-based constructor has it, and the JIT will be relying on `{ReadOnly}Span<T>.Length` never being negative (as do various methods on span).  We should just add the check in.  Yes, it's an extra comparison and branch, but in many situations the JIT will be able to eliminate it (when a constant is used), and in other situations it shouldn't register on anything other than the tightest of microbenchmarks, and the ability for the JIT to rely on it being non-negative should also help with further bounds check elimination.  Throwing an exception in this case is technically a breaking change, but no one should be relying on it "working".

**Comment by tannergooding** [comment]
I'm somewhat concerned that this will hurt various common patterns that `MemoryMarshal` sees today. Likewise somewhat concerned about making the JIT have to import more IL and deal with eliminating the `if` block in code paths that are often considered "perf critical" (we've greatly improved the support here, but we still have various limitations/etc).

If/when a PR is put up for this, we should run the JIT diffs against corelib and the benchmarks at a minimum. It would likewise be good if we could run it against some 3rd party libraries that are making extensive use of `MemoryMarshal` today.

CC. @jkotas

**Comment by jkotas** [comment]
I agree with @tannergooding. This is meant to be zero overhead very unsafe APIs. There are number of other ways you can shoot yourself in the foot by using it incorrectly.

**Comment by stephentoub** [comment]
Ok.  I'd expect us to delete the check from the pointer-based ctor then, too.

**Comment by jkotas** [comment]
The pointer-based ctor is not hidden under MemoryMarshal and so it has standard argument validation. 

If the pointer-based ctor was hidden under MemoryMarshal, I agree that it would make sense to drop the argument checks from it.

**Comment by stephentoub** [comment]
I don't see it.  It's just as easy to create a mess of things by doing an incorrect calculation around the pointer ala `new Span<T>(ptr - 5, length)` as it is around the length; from my perspective, these APIs are both unsafe, and there's little reason one should have an additional check and the other shouldn't.  But, fine.

**Comment by GSPP** [comment]
I'd agree that any pointer-based API is unsafe no matter where it is located.

A middle-ground would be to create an additional API `MemoryMarshal.CreateSpan(void* ptr, int length)` that doesn't validate the length. That would provide an escape hatch for those critical paths that care about this overhead.

**Comment by gfoidl** [comment]
@GSPP can convert the raw-pointer to a `ref` and use the API that doesn't validate the length.
If anyone is concerned about the length check, then this is quite doable.

**Comment by stephentoub** [comment]
> A middle-ground would be to create an additional API

As with https://github.com/dotnet/runtime/issues/67242, I have zero interest in adding a new API here.
