### ISSUE TITLE
mscordbi.dll 4.700.22.11601 is missing from symbol servers 

### ISSUE THREAD

**Issue by AndrewBorl** [dotnet/runtime#67446]
We have been trying to debug some .net core 3.1 dumps generated from kubernetes pods today and receive this error that the dll is missing and we cannot debug in managed mode in visual studio.

Example error:
![image](https://user-images.githubusercontent.com/48437270/161296342-cad31f7a-e5cb-4bbf-9c5a-fc736c523fde.png)

Looking into this, it seems to be the version for .net core 3.1.23, downgrading our container to 3.1.22 makes it debuggable again.

**Replication steps**
Build a linux container targetting .net core 3.1.23 runtime, use dotnet dump to take a dump of the process, and open the dump on in Visual Studio and attempt to debug in managed mode

**Expected behaviour**
The debugging session starts.

**Actual behaviour**
The debugging session cannot be started, pointing to mscordbi.dll 4.700.22.11601 being unable to be loaded.

**Comment by tommcdon** [comment]
@hoyosjs It seems that there was a symbol indexing issue for the cross-dac on 3.1.23 (March 8th release)

**Comment by EvyaB** [comment]
Did the change above manage to get into version 3.1.24? We've been having the same issue and now with the new update we're still getting it but with a different version report (now 4.700.22.16002)

**Comment by hoyosjs** [comment]
3.1.24 should be up now - there were some index issues where it was trying to use the wrong release ID.
