### ISSUE TITLE
[API Proposal]: DispatchProxy.Create<TProxy>(Type interfaceType)

### ISSUE THREAD

**Issue by AndreasHoffmann2** [dotnet/runtime#67444]
### Background and motivation

I just started using the DispatchProxy. Unfortunately, my code does not have a generic type-parameter for the interface type, since I determine the interface I want to generate at runtime.
That's why I would like to use to a method that accepts at least the interface as normal parameter: 
DispatchProxy.Create&lt;TProxy&gt;(Type interfaceType)
The class does convert the generic parameter to the type immediately anyway.

My current workaround is rather ugly:
object myInstance = typeof(DispatchProxy).GetMethod("Create").MakeGenericMethod(interfaceType, typeof(MyDispatchProxy)).Invoke(null, Type.EmptyTypes);

Perhaps, for completeness' sake, a non-generic method would make sense well:
DispatchProxy.Create(Type interfaceType, Type proxyType)

### API Proposal

```diff
namespace System.Reflection
{
    public class DispatchProxy
    {
        // existing
        public static T Create<T, TProxy>() where TProxy : DispatchProxy { ... }

+       [RequiresDynamicCode("The native code for the method requested might not be available at runtime.")]
+       public static object Create<TProxy>(Type interfaceType) where TProxy : DispatchProxy { ... }
        
         // Maybe also:
+       [RequiresDynamicCode("The native code for the method requested might not be available at runtime.")]
+       public static object Create(Type interfaceType, Type proxyType) { ... }
    }
}
```

### API Usage

```C#
object myInstance = DispatchProxy.Create<MyDispatchProxy>(interfaceType);
//instead of:
object myInstance = typeof(DispatchProxy).GetMethod("Create").MakeGenericMethod(interfaceType, typeof(MyDispatchProxy)).Invoke(null, Type.EmptyTypes);

### Alternative Designs

_No response_

### Risks

_No response_

**Comment by MichalStrehovsky** [comment]
Looks the same as #65761.

**Comment by AndreasHoffmann2** [comment]
Yes it is. I did not find the old one. Sorry.

I do not agree with the arguments there and in #28419.

Using reflection is normally considered a last resort to work around an API that does not offer methods for otherwise valid requirements. Detecting a type at runtime and creating a proxy is such a valid requirement.

An API should never be designed in a way that valid requirements require the use of reflection.

A quote from a C#-language-design-meeting:
"We can and do allow users to shoot their feet off. However, lets not give them something capable of doing nothing else."

Thus it would be totally in line with the concept of C# itself to offer a feature that has many valid use cases and some minor drawbacks if used incorrectly. We are talking about a library for professionals here. Every single one should know that using generics is always preferable if possible. If he doesn't know the obvious, then he needs to learn it. By trial and error if necessary.

But we should not cripple the API with respect to developers who do not read the docs.

**Comment by MichalStrehovsky** [comment]
We can now mark AOT unfriendly APIs with the `RequiresDynamicCode` attribute so if we were to add it, we can at least annotate it as such.

That said, the problem of people using a `System.Type` overload instead of the generic method is real; another example in addition to the ones in https://github.com/dotnet/runtime/issues/28419: `Marshal.SizeOf` has a generic overload that works across all form factors of .NET, similar to `Marshal.GetDelegateToFunctionPointer`. The problem with people using the `System.Type` overload where the generic one would be better is [absolutely real](https://grep.app/search?q=marshal.sizeof%28typeof) and the number of libraries where this is the only AOT problem is big.

**Comment by AndreasHoffmann2** [comment]
Thank you for your effort and the interesting read I had afterwards about AOT :-)

That's 3,500 typeof-usages vs. 1,200 generic ones. I really don't like to think that other developers are just not competent enough to use the generic method. Thus I kind of hope that most of the typeof-usages are older than the generic function itself, which was introduced 2013 with .NET 4.5.1. And it probably took some time until people really understood .

In my head, each usage of reflection does actually hurt. And I like to think that this is the case for most developers.

But there different levels of reflection:
Passing a `Type` to an API is bad. But there is something even worse: Fetch a method by name, stuff in generic parameters, invoke it and hope for the best.

The latter one should never be encouraged by anybody IMO. And in particular not by any project that has "dotnet" as first portion of it's name.

So adding the method would be the lesser of two evils.

And perhaps some other team will come up with a code-warning in the future. It does not seem too hard to me to detect this kind of abuse of `typeof` and show a warning in code.

**Comment by buyaa-n** [comment]
> We can now mark AOT unfriendly APIs with the `RequiresDynamicCode` attribute so if we were to add it, we can at least annotate it as such.

That is great to hear, except the AOT compatibility issue I am supportive with this and previous similar API proposals, updated the proposal with the attribute. For the problem of people using a System.Type overload instead of the generic method as @AndreasHoffmann2 mentioned we can introduce a roslyn analyzer to detect such of usage of `typeof` and show a warning.

I wonder how useful will be the `public static object Create(Type interfaceType, Type proxyType) { ... }` overload. @AndreasHoffmann2 do you have/know a real scenario that would need/require a dynamic `proxyType`?

**Comment by AndreasHoffmann2** [comment]
I don't have any real world scenarios for the Type-Type-overloading. Only speculation of a case, where this might be necessary:
I could think of some configurable interface-decorator-pattern. Like one proxy that counts the calls, another one that logs the calls and one more to measure the performance of a call. And perhaps even more fancy stuff I cannot currently think of. This might be configured in some xml-file and stacked together at runtime.

But this is only speculation. In my case, I do know the proxy at compile-time.

**Comment by terrajobst** [comment]
* Makes sense
    - Let's skip the second one as it seems unfortunate to reverse the order if interface type and proxy type.

```C#
namespace System.Reflection;

public class DispatchProxy
{
    // Existing
    // public static T Create<T, TProxy>() where TProxy : DispatchProxy;
    [RequiresDynamicCode("The native code for the method requested might not be available at runtime.")]
    public static object Create(Type interfaceType, Type proxyType);
}
```

**Comment by MichalStrehovsky** [comment]
> we can introduce a roslyn analyzer to detect such of usage of `typeof` and show a warning.

@buyaa-n is there an issue tracking adding the analyzer rule?

**Comment by MichalStrehovsky** [comment]
> > we can introduce a roslyn analyzer to detect such of usage of `typeof` and show a warning.
> 
> @buyaa-n is there an issue tracking adding the analyzer rule?

...maybe it should just be tracked as part of #73136.

**Comment by buyaa-n** [comment]
> @buyaa-n is there an issue tracking adding the analyzer rule?

Yes, [Analyzer: Detect the problem of using a System.Type overload instead of the generic overload](https://github.com/dotnet/runtime/issues/68243)
