### ISSUE TITLE
String.IndexOf differs between Net6 and NetFramework

### ISSUE THREAD

**Issue by Lyra2108** [dotnet/runtime#67451]
### Description

I am currently migrating a framework project to net6. Unfortunally my unit tests are now failing and the cause seems to be a difference in IndexOf which I can not explain/find a reason for.

Here an example NUnit test:
```
    [Test]
    public void TestIndexOf()
    {
        var searchString = "\u0001\u0001\u0002SOME TEXT\u0002\u0001\u0001";

        var text = "abc \u0001\u0001\u0002SOME TEXT\u0002\u0001\u0001";

        Assert.Multiple(() =>
        {
            Assert.That(text.IndexOf(searchString), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.Ordinal), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.OrdinalIgnoreCase), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.CurrentCulture), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.CurrentCultureIgnoreCase), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.InvariantCulture), Is.EqualTo(4));
            Assert.That(text.IndexOf(searchString, StringComparison.InvariantCultureIgnoreCase), Is.EqualTo(4));
        });
    }
```

If I run this in Framework 4.6.2 all the asserts are passing. If I do the same in net6 all are failing because the IndexOf returns 7.

**Comment by gfoidl** [comment]
See [Globalization APIs use ICU libraries on Windows](https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api).

**Comment by tarekgh** [comment]
Thanks @gfoidl for the pointer. There is more information the doc [.NET globalization and ICU](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu) which include how you can get the old behavior too. I am closing the issue but feel free to reply back if you have any question.

**Comment by Lyra2108** [comment]
Thanks a lot!

Setting
```
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```
solved the issue for me. Seems that I need to work on my google skills because I have completly missed that :)

**Comment by tarekgh** [comment]
@Lyra2108 in general we don't recommend enabling back the NLS behavior except if your scenario strongly require the .NET Framework behavior. The future direction is to use ICU (which is the default behavior) as this behavior conforms to Unicode Standard. Anyway, I am happy you are unblocked and let's know if you will face any other issue we can help with.

**Comment by Lyra2108** [comment]
I'm currently working on updating a 12year old SOAP/REST-WCF application which is the more-modern interface for a 25year old Delphi-DCOM server from framework 4.6.2  to .net6. There are so many places which we have to check and fix and make sure that they still behave the same, because this is not the only break we have to deal with. This place our unit tests caught but I fear we do not have test which cover all IndexOf with all the possible Datebase values and if I can minimize the risk for this migration at least for this part, by enabling the old behavoir. I consider it currently better to do this and in some time when the rest is stable come back and only fix this issue. Or do you condier it risky to use this setting for the near future?
