### ISSUE TITLE
[API Proposal]: Retrieve GC configuration values

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#67471]
### Background and motivation

As a performance-critical component, the garbage collector has a lot of configuration knobs

For various reasons (e.g. typo, [page alignment requirements](https://github.com/dotnet/runtime/issues/54616), required minimum values, [overrides](https://github.com/dotnet/runtime/issues/61674), base, ...), the configuration is not being applied. 

Sometimes, that fails the startup with an error code. But more often, the wrong configuration is ignored or coerced into something else.

Worse, there is no way for our customers to know their config is being mutated or ignored. We had multiple cases where customers come to us and ask if the configuration is done right, and all we can tell them is to debug it to if it is in effect.

We can do better services by improving transparency, and therefore I propose the following API:

### API Proposal

```C#
public static class GC
{
    public static object? GetConfigurationVariable(string name);
    public static IEnumerable<KeyValuePair<string, string>> GetConfigurationVariables();
}
```

### API Usage

```C#
GC.GetConfigurationVariable("I don't exists"); // will return null
GC.GetConfigurationVariable("HeapHardLimit"); // will return 0x12345678 as a ulong 
GC.GetConfigurationVariables(); // will return all known GC configuration values
```

### Alternative Designs

The design is intentionally scoped for GC only.

An alternative design is to expose a property for every single configuration value.

The disadvantage of such a design is:

1. We significantly increase the number of APIs.
2. Adding configuration would become a public API change, and
3. Some of these configurations might not make sense for mono.

Yet another alternative design is to have a strongly typed API and return a string always. This can be considered, although this has the disadvantage that it is unclear what the base of a number is in case the output is a string representing a number, which is one of the key confusion points with configuration.

### Risks

To be useful, the API must not simply reflect the configuration read from the environment variables or config files. It must reflect the actual values used by the GC. This may expose some internal implementation details that were not previously obvious.

**Comment by jkotas** [comment]
> will return all known GC configuration values

Does this mean "GC configuration values that were explicitly specified by the user", or does this mean "GC configuration values explicitly specified by the user and the default values for all configuration settings not explicitly specified by the user", or something else?

> GC.GetConfigurationVariable("COMPlus_HeapHardLimit"); // will return 0x12345678 

This does not look right. We have deprecated the `COMPlus_` prefix and replaced it `DOTNET_` prefix. We should not be giving it a new life by making this API to recognize it.

**Comment by cshung** [comment]
My intent is to show the real value that is being used by the GC, independent of whether or not the value is being specified. An interesting example would be the `GCHeapCount`. In case 1, the user could leave it unspecified, and that would be the number of cores we have. In case 2 can also specify it, and you will get the number of heaps equal to the minimum of the number of cores and the specified value. 

In case 1, if the user queries the `DOTNET_GCHeapCount`, he will get the number of cores.
In case 2. if the user queries the `DOTNET_GCHeapCount`, he will get the actual number of heaps, which is the minimum of the core count and the specified value.

Of course, these values are further complicated by processor affinity settings.

**Comment by jkotas** [comment]
> `DOTNET_GCHeapCount`

Nit: I do not think we need to have `DOTNET_` prefix for all these settings. It can be just the actual name, without any prefixes.

> Yet another alternative design is to have a weakly typed API and return a strongly typed object. This can be considered.

This option may help with the decimal vs. hex confusion that the settings suffer from currently.

It would be useful to see the list names of all GC settings that you plan to implement initially for CoreCLR GC.

It looks reasonable to me otherwise.

**Comment by svick** [comment]
> The design is intentionally scoped for GC only.

Why? Wouldn't be better if there was one way to access all runtime configuration options? Considering that the mentioned problems don't seem to be specific to the GC.

Or at least design the API so that configuration options from other areas can be added later. (Which would probably mean just moving it to a class other than `GC`.)

**Comment by reflectronic** [comment]
Related: https://github.com/dotnet/runtime/issues/31450

**Comment by jkotas** [comment]
> Wouldn't be better if there was one way to access all runtime configuration options? 

It would make sense for an API that just returns what was explicitly overridden by the user. It would get difficult for an API that returns default values or coerced values of what was specified by the user.
- What exactly would be included in "runtime"?
- The enumeration of everything would produce hundreds of values. It would be difficult to manipulate and reason about it.

I think it would make sense to design the API such that the same API can be replicated on major components as necessary: GC, threadpool, JIT, low-level networking, Kestrel, ... .

**Comment by terrajobst** [comment]
* As @jkotas says, we should come up with a pattern here that we can replicate elsewhere.
    - It seems a single method that returns a value is easiest
    - Unlikely to be called in a tight loop
* Currently, the values can never change but we might decide to make these values mutable in the future. For that, it makes sense to have snapshot semantics in that we the method returns the values at this point in time.
* The GC configuration settings in particular do parsing and coercion of values; it seems valuable to expose the configured value and the parsed/coerced value.
* It seems the runtime config isn't entirely consistent in which values can be configured in the runtime json config vs. what can come from environment variables. It seems we should unify this and maybe even have a centralized API on `AppContext`

```C#
namespace System;

public partial class GC
{
    // Returns a snapshot of the values at this particular point in time.
    public static IReadOnlyDictionary<string, object> GetConfigurationVariables();
}
```
