### ISSUE TITLE
[API Proposal]: `HttpResponseMessage.IsSuccessStatusCode(HttpStatusCode statusCode)`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#67478]
### Background and motivation

Make it easier to tell the status is successful or not

### API Proposal

```C#
namespace System.Net.Http
{
    public class HttpResponseMessage
    {
        public static bool IsSuccessStatusCode(HttpStatusCode statusCode);
    }
}
```

### API Usage

```C#
Assert.True(HttpResponseMessage.IsSuccessStatusCode(HttpStatusCode.Ok));
Assert.False(HttpResponseMessage.IsSuccessStatusCode(HttpStatusCode.BadRequest));
```

**Comment by MihaZupan** [comment]
What's the use case where you would need this and not have access to the response message to call the existing `IsSuccessStatusCode`?

**Comment by WeihanLi** [comment]
There're some libraries that may return the `HttpStatus` directly without the `HttpResponseMessage`, think maybe this would make it simple

**Comment by karelz** [comment]
@WeihanLi can you point us to some of the libraries? How popular are they?

**Comment by karelz** [comment]
No response in 2 weeks, closing. Feel free to reopen if there is more supporting evidence in future. Thanks!
