### ISSUE TITLE
NativeAOT Reflection-free mode: enum.IsDefined() shows different output

### ISSUE THREAD

**Issue by smhmhmd** [dotnet/runtime#67477]
### Description

 The same code shows different output is different when executed using dotnet runtime or run as a NativeAOT (compiled in reflection-free mode). This difference shows only in Reflection-free mode (IlcDisableReflection is set to true in csproj)

The sample code is from [here](https://docs.microsoft.com/en-us/dotnet/api/system.enum.isdefined?view=net-6.0)

### Reproduction Steps

Compile code from [here](https://docs.microsoft.com/en-us/dotnet/api/system.enum.isdefined?view=net-6.0)
For NativeAOT add these to the csproj file

     <ItemGroup>
         <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
      </ItemGroup>

    <PropertyGroup>
        <InvariantGlobalization>true</InvariantGlobalization>
        
        <IlcDisableReflection>true</IlcDisableReflection>
     </PropertyGroup>

### Expected behavior

        'dotnet run' shows expected output
            $ dotnet run
                1: True
                64: False
                Rodent: True
                Dog: True
                Dog, Cat: False
                None: True
                NONE: False
                9: False

### Actual behavior

       NativeAOT shows:
            $ ./enum-isdefined
                1: False
                64: False
                Rodent: False
                1: False
                3: False
                None: False
                NONE: False
                9: False

**Comment by jkotas** [comment]
More usable reflection-free is tracked by https://github.com/dotnet/runtime/issues/67193 . Enums behavior is one of the know issues of the current very experimental reflection-free mode.

Resolving as duplicate.
