### ISSUE TITLE
[.NET 7 Preview 2]Sporadic ArgumentException from ThreadLocal initialization

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#67491]
### Description

My [unit tests](https://github.com/koszeggy/KGySoft.CoreLibraries/tree/Net7Test/KGySoft.CoreLibraries.UnitTest) accidentally revealed an issue in `ThreadLocal<T>`, more precisely in its `IdManager.GetId` method:

```
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Threading.ThreadLocal`1.IdManager.GetId(Boolean trackAllValues)
   at System.Threading.ThreadLocal`1.Initialize(Func`1 valueFactory, Boolean trackAllValues)
   at System.Collections.Concurrent.ConcurrentBag`1..ctor(IEnumerable`1 collection)
```

### Reproduction Steps

I apologize for not being able to provide a minimal repro. I tried to create multiple `ConcurrentBag<T>` instances in a cycle (as you can see in the call stack the exception comes from its constructor, which initializes a `ThreadLocal<int>` instance) but I could not reproduce the error this way.

But feel free to fork the [Net7Test](https://github.com/koszeggy/KGySoft.CoreLibraries/tree/Net7Test) branch of my repo and execute the tests of the [KGySoft.CoreLibraries.UnitTest](https://github.com/koszeggy/KGySoft.CoreLibraries/tree/Net7Test/KGySoft.CoreLibraries.UnitTest) project.

When executing all of the tests there is a good chance that the [`SerializeSimpleGenericCollections`](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/cb7892ebdf8788ec65e5eed3a3222eeee63cf38e/KGySoft.CoreLibraries.UnitTest/UnitTests/Serialization/Xml/XmlSerializerTest.Tests.cs#L885) test case throws the exception with the call stack above. Note that by executing this test alone it will always be green.

### Expected behavior

Creating a new `ConcurrentBag<T>` instance should not throw an exception.

### Actual behavior

Creating a new `ConcurrentBag<T>` may _sometimes_ throw the mentioned exception.

### Configuration

.NET version: 7.0.100-preview.2.22153.17

**Comment by cbgrasshopper** [comment]
I am seeing this as well on .NET 7.0.203. Intermittently, new `ConcurrentBag<{RecordType}>()` throws this same exception.

**Comment by koszeggy** [comment]
The bug still exists in .NET 8 Preview 7. Does the Future milestone mean that it will not be fixed in .NET 8?

The call stack is now a bit different though:
```
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Threading.ThreadLocal`1.IdManager.GetId(Boolean trackAllValues)
   at System.Threading.ThreadLocal`1.Initialize(Func`1 valueFactory, Boolean trackAllValues)
   at lambda_method1944(Closure))
```

So I don't see the ``ConcurrentBag`1..ctor(IEnumerable`1 collection)`` anymore but `lambda_method1949(Closure)`.

**Comment by jkotas** [comment]
This sporadic ArgumentException is caused by dangerous binary serialization scheme implemented by your library. It is not a .NET runtime bug.

The tests create a raw uninitialized instance of `System.Threading.ThreadLocal`1[[System.Collections.Concurrent.ConcurrentBag`1+WorkStealingQueue[[System.Int32, System.Private.CoreLib]], System.Collections.Concurrent]]` at this callstack:

```
System_Private_CoreLib!System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(System.Type)
KGySoft_CoreLibraries!KGySoft.Reflection.Reflector.TryCreateUninitializedObject(System.Type, System.Object ByRef)+0x42
KGySoft_CoreLibraries!KGySoft.Reflection.Reflector.TryCreateEmptyObject(System.Type, Boolean, Boolean, System.Object ByRef)+0x1d1
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.CreateEmptyObject(Boolean, System.Type)+0xb2
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadObjectGraph(System.IO.BinaryReader, Boolean, DataTypeDescriptor)+0x2f4
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadObject(System.IO.BinaryReader, System.Nullable`1<Boolean>, DataTypeDescriptor)+0x1486
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadWithType(System.IO.BinaryReader, DataTypeDescriptor)+0x23c
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadDefaultObjectGraph(System.IO.BinaryReader, System.Object)+0x2c8
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadObjectGraph(System.IO.BinaryReader, Boolean, DataTypeDescriptor)+0x54c
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadObject(System.IO.BinaryReader, System.Nullable`1<Boolean>, DataTypeDescriptor)+0x1486
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.ReadRoot(System.IO.BinaryReader)+0x1b9
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter+DeserializationManager.Deserialize(System.IO.BinaryReader)+0x6c
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializeByReader(System.IO.BinaryReader)+0x107
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializeFromStream(System.IO.Stream)+0x5a
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.System.Runtime.Serialization.IFormatter.Deserialize(System.IO.Stream)+0x35
KGySoft_CoreLibraries_UnitTest_exe!KGySoft.CoreLibraries.UnitTests.Serialization.Binary.BinarySerializerTest.DeserializeObjects(Byte[], System.Runtime.Serialization.IFormatter)+0x14d
KGySoft_CoreLibraries_UnitTest_exe!KGySoft.CoreLibraries.UnitTests.Serialization.Binary.BinarySerializerTest.KGySerializeObjects(System.Collections.Generic.IList`1<System.Object>, KGySoft.Serialization.Binary.BinarySerializationOptions, System.String, Boolean, System.Runtime.Serialization.SerializationBinder, System.Runtime.Serialization.ISurrogateSelector)+0x20f
KGySoft_CoreLibraries_UnitTest_exe!KGySoft.CoreLibraries.UnitTests.Serialization.Binary.BinarySerializerTest.SerializeSimpleGenericCollections()+0x267c
```

And then sets number of fields of this instance at callstacks like this:

```
System_Private_CoreLib!DynamicClass.<SetField>___initialized(System.Object, System.Object)+0x5f
KGySoft_CoreLibraries!KGySoft.Reflection.FieldAccessor.Set+0x6d [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Reflection\FieldAccessor.cs @ 260] 
KGySoft_CoreLibraries!KGySoft.Reflection.Accessors.Set+0xc1 [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Reflection\Accessors.cs @ 894] 
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.SetField+0xc7 [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Serialization\Binary\BinarySerializationFormatter.DeserializationManager.cs @ 1749] 
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadDefaultObjectGraph+0x40a [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Serialization\Binary\BinarySerializationFormatter.DeserializationManager.cs @ 1540] 
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadObjectGraph+0x54c [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Serialization\Binary\BinarySerializationFormatter.DeserializationManager.cs @ 1474] 
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadObject+0x1486 [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Serialization\Binary\BinarySerializationFormatter.DeserializationManager.cs @ 1363] 
KGySoft_CoreLibraries!KGySoft.Serialization.Binary.BinarySerializationFormatter.DeserializationManager.ReadWithType+0x23c [C:\KGySoft.CoreLibraries\KGySoft.CoreLibraries\Serialization\Binary\BinarySerializationFormatter.DeserializationManager.cs @ 799] 
```

This results into creating an invalid ThreadLocal instance that corrupts the global `ThreadLocal` datastructures that leads to the `ArgumentException` exception that you have observed.

Creating instances of .NET runtime types using binary serialization schemes like the one you have created is unsupported. It will lead to very hard to data corruptions and even security bugs. Please avoid using this serialization scheme on types implemented .NET runtime. The types have to be explicitly designed for it and explicitly provide guarantee that this serialization scheme is safe to use on them. None of the .NET runtime types are designed for it and provide this guarantee.

While I was on it, I have also noticed that your library uses the following [unsafe pattern](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/43ce1d0eb2fa1f163e396af9ecb79a9c52c7e750/KGySoft.CoreLibraries/Reflection/Reflector%601.cs#L93-L99) in number of places. This pattern is not reliable. It violates "All managed pointers must point to a location explicitly allocated on either the managed or native heap as described above, or to stack allocated memory, or to null. " from https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md. In other words, you cannot take a random integer and convert it to byref (`ref` in C#).  Doing so will again lead to very hard to intermittent crashes. Please delete this pattern from your library.

**Comment by jkotas** [comment]
Also, the following statement about the security guarantees of your binary serialization scheme is incorrect:

> All serializable types that can have an invalid state regarding the field values should implement <see cref="ISerializable"/> and should throw a <see cref="SerializationException"/> from their serialization constructor if validation fails.

`ISerializable` contract does not provide security guarantees like that. Some `ISerializable` implementations in .NET runtime may do some state validation, but this validation is not hardened as a security guarantee.

**Comment by koszeggy** [comment]
@jkotas : Thank you so much for your effort analyzing this issue. I really appreciate your invested time, especially because the test that caused it did something that a real-life code should never do: it used forced recursive object graph serialization for a type, which is natively supported by the serializer (and never has been IFormatter-compatible anyways) so such serialization approach was both insecure and unnecessary, even for testing the fallback mechanisms.

> `ISerializable` contract does not provide security guarantees like that. Some `ISerializable` implementations in .NET runtime may do some state validation, but this validation is not hardened as a security guarantee.

I know that such validation is almost never applied on runtime types. Even `Dictionary<TKey, TValue>` can throw an `OutOfMemoryException` if the `HashSize` entry is manipulated in the serialization stream. So this is just a recommendation for custom types to minimize the possible issues. But I will rewrite the whole documentation for the next version anyway because in safe mode I'm going to [introduce](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/1bf879dc2b5a9479785350a21f4c7d3151863d8e/KGySoft.CoreLibraries/changelog.txt#L74) even more restrictions for the whole obsoleted `ISerializable` infrastructure.

> I have also noticed that your library uses the following [unsafe pattern](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/43ce1d0eb2fa1f163e396af9ecb79a9c52c7e750/KGySoft.CoreLibraries/Reflection/Reflector%601.cs#L93-L99) in number of places. [...] cannot take a random integer and convert it to byref (`ref` in C#)

Thank you also for commenting on this. It meant to be a `TypedReference` -> `ref byte` conversion, which unfortunately is not supported in one atomic step (and even if will be, older target frameworks still need a workaround). So it isn't a random integer but a pointer to a managed object extracted from the `TypedReference`. Can you maybe suggest another way to do it safely? I never dereference the pointer until making sure the pinning was [successful](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/1bf879dc2b5a9479785350a21f4c7d3151863d8e/KGySoft.CoreLibraries/Reflection/Reflector%601.cs#L99). Can you confirm that the retry mechanism cannot be used like that?

**Comment by jkotas** [comment]
> So it isn't a random integer but a pointer to a managed object extracted from the TypedReference

When the GC relocates the object, the pointer can end up pointing into GC "free space" that has been known to lead to intermittent GC crashes, in particular on .NET Framework.

I do not think there is a 100% reliable way to convert `TypedReference` to `byref ref` across all runtimes (including .NET Framework).
