### ISSUE TITLE
Vector<T>.Zero.Equals(vec) produces less ideal code than vec == Vector<T>.Zero

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#67500]
Cf. https://github.com/dotnet/runtime/pull/67492#discussion_r841219532

Repro:
```c#
bool Bad(Vector<ushort> vec) => Vector<ushort>.Zero.Equals(vec);

bool Good(Vector<ushort> vec) => vec == Vector<ushort>.Zero;
```

The version with the `==` boils down to a `ptest ymm0, ymm0` which is ideal.

The version with explicit equals (i.e. _Bad_ above) emits extra `vxorps` and `vpxor` which aren't needed.
This is especially cumbersome in loops where these instructions bloat the loop-body. By manual hoisting `Vector<T>.Zero` one xor can be eliminated.

Expected is same codegen for both versions.

The same happens for `byte` too (didn't check other types).

/cc: @EgorBo 

category:cq
theme:vector-codegen
skill-level:beginner
cost:small
impact:small

**Comment by tannergooding** [comment]
Just noting, more broadly speaking.

`Equals` and `==` aren't the same. The former is expected to do things like treat two `NaN` as equivalent (currently still a bug here I need to fix) while the latter is expected to match IEEE 754 requirements.

Likewise, `Equals` is an instance method and as such takes the first parameter by readonly reference. This has to then be optimized away by the JIT so the value is consumed directly.

**Comment by gfoidl** [comment]
> Likewise, `Equals` is an instance method and as such takes the first parameter by readonly reference. This has to then be optimized away by the JIT so the value is consumed directly.

So `==` (as static operator) is less work for the JIT, and should be preferred where the comparison is exact (like for byte, short, etc.) when I read / interpret this correct?

**Comment by hypeartist** [comment]
@gfoidl, @tannergooding 
Funny, but swapping the operands order (```vec``` now is the caller) changes the codegen into the 'Good' one:
```csharp
static bool Bad(Vector<ushort> vec) => vec.Equals(Vector<ushort>.Zero);
```
```asm
;   static bool Bad(Vector<ushort> vec) => vec.Equals(Vector<ushort>.Zero);
;                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        vmovupd ymm0,[rcx]
        vptest  ymm0,ymm0
        sete    al
        movzx   eax,al
        vzeroupper
        ret
```

**Comment by gfoidl** [comment]
@hypeartist yep, that's funny and a bit strange. But I guess that's why https://github.com/dotnet/runtime/pull/67502 got created by @EgorBo.

**Comment by JulieLeeMSFT** [comment]
> So `==` (as static operator) is less work for the JIT, and should be preferred where the comparison is exact (like for byte, short, etc.) when I read / interpret this correct?

Once @tannergooding confirms, I think we can close this issue.

**Comment by JulieLeeMSFT** [comment]
Ping @tannergooding.

**Comment by tannergooding** [comment]
There is still codegen improvements we can do here, I was just noting that `==` and `Equals` do have different semantics and will be treated differently in some cases.

This will be particularly prevalent for `Equals` with `float` or `double`.

**Comment by JulieLeeMSFT** [comment]
Sure. I don't think we can work on this in .NET 7. Moving to future.

> There is still codegen improvements we can do here, I was just noting that `==` and `Equals` do have different semantics and will be treated differently in some cases.
> 
> This will be particularly prevalent for `Equals` with `float` or `double`.

**Comment by TIHan** [comment]
Talked with @tannergooding - this was likely resolved when they `GT_CNS_VEC`. Currently, both functions now emit the same codegen. Closing.
