### ISSUE TITLE
Confusing message on Http timeout

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#67505]
From some test failures I noticed:
```
NuGet.Protocol.Core.Types.FatalProtocolException : An error occurred while retrieving package metadata for 'Microsoft.NETFramework.ReferenceAssemblies.net48.1.0.2' from source 'dotnet-public'.
---- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of -0.001 seconds elapsing.
-------- System.TimeoutException : The operation was canceled.
------------ System.Threading.Tasks.TaskCanceledException : The operation was canceled.
---------------- System.TimeoutException : A connection could not be established within the configured ConnectTimeout.
```

Apparently the timeout was set to Timeout.InfiniteTimeSpan, which is -1 ms.  Presumably this couldn't have expired, so the message is confusing. I don't have a repro, so feel free to close if it's not important.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/67508

**Comment by MihaZupan** [comment]
The relevant code path that determines the exception type:

https://github.com/dotnet/runtime/blob/1c2198ee5707f1292b16299dd6d7bb77de5e5d76/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L607-L609

We should differentiate between a regular timeout and the `ConnectTimeout`.

Ideally, we would also expose such info in a programmatical way to the user. This recently came up in YARP as well (microsoft/reverse-proxy#1628).
