### ISSUE TITLE
Increase the size of the regex cache

### ISSUE THREAD

**Issue by EngRajabi** [dotnet/runtime#67530]
### Description

What do you think about increasing the value of DefaultMaxCacheSize?
Due to the fact that Regex is used everywhere, it uses runtime, asp, sql client, ef ..... as well as the user. This number seems low 16.
If you intend, I will do it

### Configuration

        /// <summary>The default maximum number of items to store in the cache.</summary>
        private const int DefaultMaxCacheSize =  15;

**Comment by stephentoub** [comment]
> Due to the fact that Regex is used everywhere, it uses runtime, asp, sql client, ef

Are they using the static Regex members, and on code paths that are repeatedly used?  Can you point to where?

In general the static regex methods aren't high performance and are intended for use in apps where the overhead doesn't matter or for situations where the regex is largely throwaway, e.g. it's going to be used once or twice and then not again.

Regexes can also reference a lot of state, especially if they're RegexOptions.Compiled, in which case they're not only keeping alive all the managed objects, but also all the code associated with the compiled instance.  Increasing the size of the cache significantly could significantly increase the working set of the process.

I'd be ok increasing the cache size significantly _if_ we also come up with a scheme whereby we can purge unused items from the cache over time, such that it doesn't represent a memory leak.

**Comment by EngRajabi** [comment]
I saw items in Microsoft code that had two modes.
1- The case where a static member was used without a compile flag
2- The state in which the object was used, still without a compile flag
I think we can improve efficiency with some changes
I put the items here

https://github.com/dotnet/efcore/blob/96f7bb85e87bb3f80d29f0751c860036fc2edfb4/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L1349

https://github.com/dotnet/efcore/blob/96f7bb85e87bb3f80d29f0751c860036fc2edfb4/src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs#L1371

https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/EFCore.Sqlite.Core/Storage/Internal/SqliteRelationalConnection.cs#L111

https://github.com/dotnet/efcore/blob/c918248457a3629736ff50c970ac022917b894b1/src/EFCore.Relational/Migrations/Internal/MigrationsIdGenerator.cs#L38

https://github.com/dotnet/efcore/blob/0d1d602d72fefe14f12a86410ec70394ec8151e0/src/ef/AnsiTextWriter.cs#L33

**Comment by EngRajabi** [comment]
I changed the value
Regex.CacheSize
I got a much better return from the program

**Comment by danmoseley** [comment]
@EngRajabi what "program"? As mentioned above, the value here is not a magic performance dial 😄 it trades off memory, broadly speaking. It's easy to construct examples where it helps, and examples where it hurts.

To make a change here we'd need data from real workloads, so we could evaluate pros and cons.

**Comment by EngRajabi** [comment]
The program was Asp Core 5 . In one part of the program, I had to filter some of the strings with regex. This filter was about 15 special patterns. The program crashes at high loads. My problem was solved by increasing the cache. I monitored a lot to find a problem

**Comment by danmoseley** [comment]
That's curious, because the cache is already 15.

I'm going to close this -- it sounds like you have solved your problem.

**Comment by EngRajabi** [comment]
My problem was solved by increasing the cache.
There were about 20 rejection patterns in my program, which made the cache virtually unusable and the system very slow.
I suggest increasing the default memory size to 128, which avoids problems.
Note also that the side packages also use this 15-digit memory, such as
runtime, asp, sql client, ef, which cause the cache to fill up quickly
