### ISSUE TITLE
Please add a stable sorting algorithm to the base library (eg timsort or rust-style)

### ISSUE THREAD

**Issue by coderb** [dotnet/runtime#67546]
There is no stable sorting algorithm the current dotnet core base libraries.

Stable sorting algorithms maintain the relative order of records with equal keys.

Other languages have built in support for this:
python - timsort
java - timsort
rust - timsort variant ( https://github.com/rust-lang/rust/pull/38192 ).

I would propose a port of either java timsort or rust's enhanced algorithm.

Not only are they stable, they are highly performant.

**Comment by teo-tsirpanis** [comment]
Closing as duplicate.
