### ISSUE TITLE
[arm64] Perf_FileStream.FlushAsync benchmark hangs on Debian 11

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67545]
Reported by @carlossanlop offline. Carlos has hit this issue on Debian 11 arm64 with WSL2.

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
python3 ./performance/scripts/benchmarks_ci.py --architecture arm64 -f net7.0 --filter '*Perf_FileStream.FlushAsync*'
```

[Source](https://github.com/dotnet/performance/blob/3edf4c3149f5c903777f13af9b08b562b1672302/src/benchmarks/micro/libraries/System.IO.FileSystem/Perf.FileStream.cs#L418-L426):

```log
using (FileStream fileStream = new FileStream("repro.txt", FileMode.Create, FileAccess.Write, FileShare.Read, 4096, FileOptions.None))
{
    for (int i = 0; i < 1024; i++)
    {
        fileStream.WriteByte(default);

        await fileStream.FlushAsync();
    }
}
```

In theory it could be an IO issue, but we have not touched `FileStream` for a few months and I suspect that it's a runtime bug similar to #64980.

@janvorli @jkotas what would be the best way to determine the reason of the hang on Linux?

**Comment by adamsitnik** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6011991/161601992-96c1236b-b900-4bb2-8af4-4a84263fed26.png)

**Comment by danmoseley** [comment]
Can you get a dump at the point of hang?

**Comment by janvorli** [comment]
Interestingly, my attempt to run the benchmarks on Ubuntu 18.04 arm64 on my Odroid N2 device (with AOT in my case) has hung in the `Perf_FileStream.ReadAsync` benchmark over the weekend. Unfortunately I haven't attempted to take the dump and just killed the run. I am running it again without AOT this time, so I'll watch for the same issue.

**Comment by jeffhandley** [comment]
I am hitting the same hang on my Surface Laptop 2 when using WSL2/Ubuntu 20.04. This is x64. I can repro it consistently while running only this benchmark. I'll connect with @adamsitnik to collect a dump.

**Comment by jeffhandley** [comment]
I uploaded the dump file to the location where we're posting our manual run results. And I observed a peculiar behavior:

* While plugged in, on the Windows host Performance power plan, the benchmark hangs frequently (but not every time)
* When on battery power, on the Performance power plan, I've been unable to repro the hang
* When plugged in or on battery power, on the Balanced power plan, I've been unable to repro the hang

**Comment by adamsitnik** [comment]
@janvorli I assume you were not using WSL?

**Comment by jeffhandley** [comment]
ReadAsync caused a hang on my WSL/Ubuntu 20.04 config as well. I uploaded dumps from that benchmark too.

**Comment by janvorli** [comment]
> @janvorli I assume you were not using WSL?

Right, it was a physical device in my case.

**Comment by janvorli** [comment]
I just noticed that I have a hang in the ReadAsync  in another benchmark run that I've started yesterday on the same device, this time in Alpine docker container.

**Comment by carlossanlop** [comment]
FYI - I hit this hang in:

- Ubuntu 20.04 x64 (Physical laptop)
- Ubuntu 20.04 arm64 (WSL)
- Debian 11 (WSL)

**Comment by adamsitnik** [comment]
@janvorli is there any chance you could take a look at dump provided by Jeff? I am quite sure it's not a `FileStream` issue (we have not touched the code since 6.0) but I have no idea what is causing it and what is the right area

**Comment by janvorli** [comment]
@adamsitnik sure, I'll take a look.

**Comment by janvorli** [comment]
@jeffhandley how did you take the dumps? The readasync one is mostly readable, but it doesn't contain sufficient amount of information for viewing managed method names. The other two are somehow broken - the stack traces are not complete and SOS is unable to resolve any managed methods.

**Comment by jeffhandley** [comment]
I used `~/.dotnet/shared/Microsoft.NETCore.App/6.0.3/createdump` folder. I used a normal minidump. Should I use a full dump or do something different?

**Comment by janvorli** [comment]
Can you please try to take a full dump (with the `-u` option) instead?

**Comment by danmoseley** [comment]
I hit this hang on x64. I'll share a link to dumps @janvorli as soon as they're uploaded.

I'm not sure how helpful it will be -- there is really only one active thread,
```
> clrstack
OS Thread Id: 0x699f (0)
        Child SP               IP Call Site
00007FFDFA583D80 00007f54589ed08c [InlinedCallFrame: 00007ffdfa583d80]
00007FFDFA583D80 00007f53e0bb03ae [InlinedCallFrame: 00007ffdfa583d80]
00007FFDFA583D70 00007F53E0BB03AE Interop+Sys.<Read>g____PInvoke__|58_0(IntPtr, Byte*, Int32)
00007FFDFA583E20 00007F53E244D35B Interop+Sys.Read(System.Runtime.InteropServices.SafeHandle, Byte*, Int32) [/_/src/libraries/System.Net.Sockets/src/Microsoft.Interop.LibraryImportGenerator/Microsoft.Interop.LibraryImportGenerator/LibraryImports.g.cs @ 1486]
00007FFDFA583E60 00007F53E244D26C System.Net.Sockets.SocketPal.SysRead(System.Net.Sockets.SafeSocketHandle, System.Span`1<Byte>, Error ByRef) [/_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs @ 103]
00007FFDFA583EA0 00007F53E244D1BC System.Net.Sockets.SocketPal.TryCompleteReceiveFrom(System.Net.Sockets.SafeSocketHandle, System.Span`1<Byte>, System.Collections.Generic.IList`1<System.ArraySegment`1<Byte>>, System.Net.Sockets.SocketFlags, Byte[], Int32 ByRef, Int32 ByRef, System.Net.Sockets.SocketFlags ByRef, System.Net.Sockets.SocketError ByRef) [/_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs @ 810]
00007FFDFA583EE0 00007F53E24638D8 System.Net.Sockets.SocketAsyncContext.ReceiveFrom(System.Span`1<Byte>, System.Net.Sockets.SocketFlags ByRef, Byte[], Int32 ByRef, Int32, Int32 ByRef) [/_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs @ 1569]
00007FFDFA583F70 00007F53E246362F System.Net.Sockets.Socket.Receive(System.Span`1<Byte>, System.Net.Sockets.SocketFlags, System.Net.Sockets.SocketError ByRef) [/_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs @ 1465]
00007FFDFA583FE0 00007F53E24634A2 System.IO.Pipes.PipeStream.ReadCore(System.Span`1<Byte>) [/_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs @ 271]
00007FFDFA584020 00007F53E2430CAF System.IO.StreamReader.ReadBuffer()
00007FFDFA584070 00007F53E2463B1D System.IO.StreamReader.get_EndOfStream()
00007FFDFA584080 00007F53E245CD78 BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
```

**Comment by danmoseley** [comment]
I was able to reduce this 1 out of 5 tries with `python3 ./scripts/benchmarks_monthly.py net7.0-preview3 --filter *FlushAsync*` (which takes a couple minutes). So looping that should hit it in a reasonable period of time. Or perhaps looping just the innermost command it runs, after running it once to set everything up.

**Comment by LoopedBard3** [comment]
We are also seeing this issue in the performance runs. We don't have any dumps, but this was occurring with the FlushAsync, WriteAsync, and ReadAsync Perf_Filestream benchmarks in our Linux x64 tests on Ubuntu.1804.
