### ISSUE TITLE
[API Proposal]: Make some System.Net.Security functions/properties public for System.Net.Quic

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#67552]
### Background and motivation

1. **SslStreamCertificateContext**
In System.Net.Quic, we're handling certificates from `SslServerAuthenticationOptions` and need to pass them to msquic. Since `SslServerAuthenticationOptions` allows to specify certificate with its intermediates via `SslStreamCertificateContext`, we need to be able to extract both properties from the class in order to convert them and pass them to msquic.

2. **SslClientHelloInfo**
We'll also be adding our version of `ServerOptionsSelectionCallback`:
https://github.com/dotnet/runtime/blob/4f602117b7f5832f691056325141a063072de019/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs#L38
And we'll need to be able to construct `SslClientHelloInfo` struct. Otherwise, we'll be left with reflection here as well.

3. Current SslStreamCertificateContext takes list of additional certificates. But when `Create` method is called it is not clear if X509Chain build succeeds and how the actual list looks. 
Exposing the `IntermediateCertificates` would make any investigations easier

4. `SslStreamCertificateContext` is not `iDisposable` (unfortunately).
Exposing the inner certificates possibly allows some cleanup if needed. (also creates risk of mishandling)

 
### API Proposal

1. **SslStreamCertificateContext**
```diff
// Public ctors, but getters are internal.
public class SslStreamCertificateContext
{
-   internal readonly X509Certificate2 Certificate;
+   public readonly X509Certificate2 TargetCertificate { get; }
+   public ReadOnlyMemory<X509Certificate2> IntermediateCertificates { get; }
    // public ctors
}
```

`Create` method calls the certificate `target` and that seems too ambiguous. The proposal is to call it `TaregtCertificate`  to make it somewhat closer or we can use the current internal `Certificate` (that is pretty generic as well)  

We also talk about `ReadOnlySpan<X509Certificate2>` for the `IntermediateCertificates` but the consensus was to use Memory as more flexible. Current implementation use array under the cover. 

2. **SslClientHelloInfo**
```diff
// It has public getters, but cannot be constructed with values outside of System.Net.Security.
public readonly struct SslClientHelloInfo
{
    public readonly string ServerName { get; }
    public readonly SslProtocols SslProtocols { get; }

-   internal SslClientHelloInfo(string serverName, SslProtocols sslProtocols);
+   public SslClientHelloInfo(string serverName, SslProtocols sslProtocols);
}
```

### API Usage

1. **SslStreamCertificateContext**
```C#
if (sslOptions.ServerCertificateContext is not null) 
{
    certificate = sslOptions.ServerCertificateContext.ContextCertificate;
    intermediaries = sslOptions.ServerCertificateContext.ContextChain;
}
```
2. **SslClientHelloInfo**
```C#
SslClientHelloInfo sslClientHelloInfo = new SslClientHelloInfo(targetHost, SslProtocols.Tls13);
```

### Alternative Designs

1. **SslStreamCertificateContext**
Move the whole logic around certificates to System.Net.Security and get out of it only ASN1 blob (which we need for msquic).

2. **SslClientHelloInfo**
Not much options here, possibly static create method.

For both, `InternalsVisibleTo`. I'm aware it's "forbidden" in runtime, but I don't know why.
For both, merging System.Net.Security with System.Net.Quic. This was voted against in our team discussion, unless we want to merge whole lot more and create omnipotent System.Net.dll.

3. **Use reflection** 
That was done in early 7.0. Not great for obvious reason.

4.  Use semi-public methods (current state) 
Needed properties and methods are public but not in ref assembly. 
Noted in #72226 .

### Risks

Not much. We'd be only exposing readonly getters and struct ctor.

**Comment by rzikm** [comment]
For the `SslStreamCertificateContext.IntermediateCertificates` field/property, I think it would be better to change the type to something immutable (`ReadOnlyMemory`/`ReadOnlyList`?) so that we don't need to worry about it changing under our hands.

**Comment by ManickaP** [comment]
Yeah, I only took the fields as they are now and made them public. Getters are fine choice here as well, I'll update the proposal to reflect that.

**Comment by rzikm** [comment]
Do we still want to keep this since #68189 was merged?

**Comment by ManickaP** [comment]
Closing in favor of https://github.com/dotnet/runtime/pull/68189

**Comment by bartonjs** [comment]
We weren't feeling good about the ReadOnlyMemory<X509Certificate2> property, and want to have a discussion about it.

```C#
// Public ctors, but getters are internal.
public class SslStreamCertificateContext
{
-   internal readonly X509Certificate2 Certificate;
+   public X509Certificate2 TargetCertificate { get; }
+   public ReadOnlyMemory<X509Certificate2> IntermediateCertificates { get; }
    // public ctors
}

// It has public getters, but cannot be constructed with values outside of System.Net.Security.
public readonly struct SslClientHelloInfo
{
    public readonly string ServerName { get; }
    public readonly SslProtocols SslProtocols { get; }

-   internal SslClientHelloInfo(string serverName, SslProtocols sslProtocols);
+   public SslClientHelloInfo(string serverName, SslProtocols sslProtocols);
}
```

**Comment by terrajobst** [comment]
* We'd prefer `ReadOnlyCollection<T>` 

```C#
namespace System.Net.Security;

public partial class SslStreamCertificateContext
{
    public X509Certificate2 TargetCertificate { get; }
    public ReadOnlyCollection<X509Certificate2> IntermediateCertificates { get; }
}
```
