### ISSUE TITLE
Bug in Task Completions on MacOS and Linux

### ISSUE THREAD

**Issue by KevinRansom** [dotnet/runtime#67567]
### Description

We have an F# test case that is failing on MacOS and Linux with the dotnet 7.0 runtime.  The test is verifying Task completions.

It runs successfully on the net6.0 runtime but fails on the runtime shipped with:  7.0.100-preview.2.22153.17

I have a solution that reproduces the issue, it also contains the built binaries:
[ConsoleApp26.zip](https://github.com/dotnet/runtime/files/8414091/ConsoleApp26.zip)

### Reproduction Steps

1. Unzip the attached zip file.
2. On a machine with an RTM net 6.0 sdk and the 7.0.100-preview.2.22153.17 SDK installed
3. execute the following commands:
4. dotnet run -c release -f net7.0
5. observe the failed output:
![image](https://user-images.githubusercontent.com/5175830/161658637-95d56d2a-de4b-46f6-a563-5c60441e7fb8.png)
6. dotnet run -c release -f net6.0
7. Observe the succeed output:
8. 
![image](https://user-images.githubusercontent.com/5175830/161658742-cfd30251-95c2-4a8c-911a-ebf990868340.png)

### Expected behavior

Expected net7/0 and net6.0 to produce the same results.

I verified that the output of the F# compiler in both cases is the same by copying the ConsoleApp1.dll produced by net6.0 to the net7.0 bin/release folder and directly executing it, it produce the same result.

Please note:  this is using the F# Async computations interoperating with the dotnet Task framework.

### Actual behavior

The repro shows the error output.

### Regression?

It is a regression as can be seen from the repro having different behaviour on 6.0 and 7.0.

### Known Workarounds

None known.

/CC @dsyme, @vzarytovskii @brettfo

**Comment by stephentoub** [comment]
I don't believe this is an issue with Tasks; rather it's an issue with low-lock code in the repro.

The repro has the line:
```F#
let doSpinloop () = while spinloop do ()
```
With just the `while spinloop do ()`, if you look at the asm that got generated, the actual read of `spinloop` has been hoisted out of the loop:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/2642209/161663030-4875a895-2863-4075-91e2-4a6059eda1da.png">
which is valid as the read isn't volatile.

**Comment by hez2010** [comment]
Not a bug. 
You need to make your `spinloop` read volatile.

**Comment by KevinRansom** [comment]
Nice, thanks
