### ISSUE TITLE
System.Text.Json.JsonSerializer does not work with Dictionary<string, object>

### ISSUE THREAD

**Issue by konarx** [dotnet/runtime#67588]
### Description

When a `Dictionary<string, object>` needs serialization, the .NET default `System.Text.Json.JsonSerializer` throws an exception:

> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.

I have provided a simple piece of code example to reproduce it. I tried with `Newtonsoft.Json.JsonConvert` and it works flawlessly.

### Reproduction Steps

```
 public void TestDictionarySerialize()
        {
            var dictionary = new Dictionary<string, object> {
                {"Hello", typeof(string)}, 
                {"World", typeof(string)}
            };

            //This serialization fails
            System.Text.Json.JsonSerializer.Serialize(dictionary,
                typeof(Dictionary<string, object>));

           //This serialization fails
            System.Text.Json.JsonSerializer.Serialize(dictionary);

            //This serialization succeeds
            Newtonsoft.Json.JsonConvert.SerializeObject(dictionary);
        }
```

### Expected behavior

`System.Text.Json.JsonSerializer` should not throw any Exception

### Actual behavior

`System.Text.Json.JsonSerializer` throws:

> System.InvalidOperationException: Method may only be called on a Type for which Type.IsGenericParameter is true.

### Known Workarounds

`Newtonsoft.Json.JsonConvert` works flawlessly

### Configuration

- .NET 6.0.200
- Windows 10 Enterprise 21H2 19044.1586
- x64

**Comment by eiriktsarpalis** [comment]
This is a bug, our unsupported type detection for System.Type values is evaded in the case of polymorphism. Values are resolved as `System.RuntimeType` which is not caught by the relevant converter.
