### ISSUE TITLE
Rolling build test failure: System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Create_MultipleFilters with message "Created event did not occur as expected" 

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67601]
The [rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1699174&view=results) from 2022/04/04 had the following failure:

- Pipeline: Libraries Test Run release coreclr windows x86 Release
- Job: https://dev.azure.com/dnceng/public/_build/results?buildId=1699174&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e&l=355
- Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-9284a8d671b3408fbc/System.IO.FileSystem.Watcher.Tests/1/console.a1000fc9.log?sv=2019-07-07&se=2022-04-24T21%3A03%3A56Z&sr=c&sp=rl&sig=EFnWLnw8K%2Fsfp8RLQognnE5nomT%2F8Bi3Bi8Ny4qr3GU%3D
- Test method: System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Create_MultipleFilters [FAIL]
- Callstack:
```
Created event did not occur as expected
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(311,0): at System.IO.Tests.FileSystemWatcherTest.ExecuteAndVerifyEvents(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Boolean assertExpected, String[] expectedPaths, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(202,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String[] expectedPaths, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs(172,0): at System.IO.Tests.FileSystemWatcherTest.ExpectEvent(FileSystemWatcher watcher, WatcherChangeTypes expectedEvents, Action action, Action cleanup, String expectedPath, Int32 attempts, Int32 timeout)
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.unit.cs(992,0): at System.IO.Tests.FileSystemWatcherTests.FileSystemWatcher_Directory_Create_MultipleFilters()
  Finished:    System.IO.FileSystem.Watcher.Tests
```

**Comment by Jozkee** [comment]
We have had this kind of failures in the past, I think is just flakyness in the FSW tests.
https://github.com/dotnet/runtime/issues/24181#issuecomment-585925646
https://github.com/dotnet/runtime/issues/26308

You can also see in https://dataexplorer.azure.com/ that we have hit this error 34 times in the past 2 months.
```
TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished <= datetime(2022-04-04 0:00:00)
and Message contains "event did not occur as expected"
and Result == 'Fail'
```
My only guess right now is to make the FSW tests more resilient to this kind of errors, perhaps implementing some re-try logic?

**Comment by danmoseley** [comment]
In the last 60 days it's occurred 37 times


Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAG2PsU7DQBBE%2b0j8w8hNSGOlSmdKS0YCFBIp9XE7Chc7e%2bj2DETi47mQgBuq1ey8Ge1uafmZNg7ZcDP7wiEGRR9UmqDKhF1MfZd5NET9E538y97Hlx%2bszE7OwMcrE4H1yJGCO7h9vF0tZTF5v41tClQZTo%2fuSDQNqs3Jyrrunuo2DLyqncu%2bxOptOdqqqeXywDk3b10Y5pPzQDO3J3zU7IIaKr5TMyQINGZE78cEZ%2bDnG32mlNZvIjeLABMBAAA%3d) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2PsU7DQBBE%2b0j8w8hNSGOlSmdKS0YCFBIp9XE7Chc7e%2bj2DETi47mQgBuq1ey8Ge1uafmZNg7ZcDP7wiEGRR9UmqDKhF1MfZd5NET9E538y97Hlx%2bszE7OwMcrE4H1yJGCO7h9vF0tZTF5v41tClQZTo%2fuSDQNqs3Jyrrunuo2DLyqncu%2bxOptOdqqqeXywDk3b10Y5pPzQDO3J3zU7IIaKr5TMyQINGZE78cEZ%2bDnG32mlNZvIjeLABMBAAA%3d&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAG2PsU7DQBBE%2b0j8w8hNSGOlSmdKS0YCFBIp9XE7Chc7e%2bj2DETi47mQgBuq1ey8Ge1uafmZNg7ZcDP7wiEGRR9UmqDKhF1MfZd5NET9E538y97Hlx%2bszE7OwMcrE4H1yJGCO7h9vF0tZTF5v41tClQZTo%2fuSDQNqs3Jyrrunuo2DLyqncu%2bxOptOdqqqeXywDk3b10Y5pPzQDO3J3zU7IIaKr5TMyQINGZE78cEZ%2bDnG32mlNZvIjeLABMBAAA%3d&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAG2PsU7DQBBE%2b0j8w8hNSGOlSmdKS0YCFBIp9XE7Chc7e%2bj2DETi47mQgBuq1ey8Ge1uafmZNg7ZcDP7wiEGRR9UmqDKhF1MfZd5NET9E538y97Hlx%2bszE7OwMcrE4H1yJGCO7h9vF0tZTF5v41tClQZTo%2fuSDQNqs3Jyrrunuo2DLyqncu%2bxOptOdqqqeXywDk3b10Y5pPzQDO3J3zU7IIaKr5TMyQINGZE78cEZ%2bDnG32mlNZvIjeLABMBAAA%3d&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where  Queued > ago(60d)
| where WorkItemFriendlyName == "System.IO.FileSystem.Watcher.Tests"
| where Result == 'Fail'
| where Message contains "event did not occur as expected"
```

Some tests more than others:
```
EndInit_ResumesPausedEnableRaisingEvents
FileSystemWatcher_Directory_Changed_LastWrite
FileSystemWatcher_Directory_Create_Filter_Ctor
FileSystemWatcher_Directory_Create_Filter_Ctor
FileSystemWatcher_Directory_Create_Filter_Ctor
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_Create_MultipleFilters
FileSystemWatcher_Directory_NotifyFilter_Attributes
FileSystemWatcher_Directory_NotifyFilter_Attributes
FileSystemWatcher_File_Create_MultipleFilters
FileSystemWatcher_File_Create_MultipleFilters
FileSystemWatcher_File_Create_MultipleFilters
FileSystemWatcher_File_Create_MultipleFilters
FileSystemWatcher_File_Create_SynchronizingObject
FileSystemWatcher_File_Create_SynchronizingObject
FileSystemWatcher_File_Delete_MultipleFilters
FileSystemWatcher_File_Delete_MultipleFilters
FileSystemWatcher_File_Delete_MultipleFilters
FileSystemWatcher_File_Delete_SymLink
FileSystemWatcher_File_NotifyFilter_CreationTime
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_ModifyFiltersConcurrentWithEvents
FileSystemWatcher_SymbolicLink_TargetsDirectory_Create_IncludeSubdirectories
```

**Comment by danmoseley** [comment]
There is one test already with retries FileSystemWatcher_File_Create_EnablingDisablingNotAffectRaisingEvent and it does not appear above. I'll try this for the others.

**Comment by danmoseley** [comment]
Apparently it's not a problem on mac ?
```
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
ubuntu.1804.armarch.open
windows.10.amd64.open.rt
windows.10.amd64.server19h1.es.open.rt
windows.10.amd64.server19h1.es.open.rt
windows.10.amd64.server19h1.es.open.rt
windows.10.amd64.server2022.es.open
windows.10.amd64.server2022.es.open
windows.10.amd64.server2022.es.open
windows.10.arm64v8.open
windows.11.amd64.clientpre.open
windows.11.amd64.clientpre.open
windows.11.amd64.clientpre.open
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.rt
windows.7.amd64.open.svc
```
