### ISSUE TITLE
Making numerical formatting specifiers more consistent

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#67623]
Today 'R'/'r' aren't supported with integral types but are with floating point, and 'X'/'x' aren't supported with floating point but are with integral types.  Related to both https://github.com/dotnet/runtime/issues/65634 and the generic math support, where `INumber<T>` inherits `ISpanFormattable` and thus we should expect format specifiers to be used with arbitrary numerical types, we should allow all of these specifiers to be used, regardless of integer vs floating point.  'R'/'r' for integers can just be treated as 'G'/'g', respectively, and 'X'/'x' for floating point is covered by https://github.com/dotnet/runtime/issues/1630.

(Discussed in API review on 4/5/2022.)

cc: @tannergooding

**Comment by tannergooding** [comment]
This one should be relatively straightforward for `R`, it just needs to be treated the same as `G` for the built-in Integer types.

The hexadecimal support is a bit more complex but is tracked by https://github.com/dotnet/runtime/issues/1630.
