### ISSUE TITLE
Microsoft.Extensions.***.Abstractions nuget package/metapackage for use in class library

### ISSUE THREAD

**Issue by Abdragiz** [dotnet/runtime#67637]
Hello, I think the packages listed below are often used in net apps:
```
Microsoft.Extensions.Options                            // options pattern
Microsoft.Extensions.Logging.Abstractions               // logging
Microsoft.Extensions.DependencyInjection.Abstractions
Microsoft.Extensions.Configuration.Abstractions
Microsoft.Extensions.Options.ConfigurationExtensions    // 3 packages for writing ServiceCollectionExtensions static class
```
I know these packages are included in ```Microsoft.AspNetCore.App```, which can be framework referenced if the library needs ASP.NET Core related functionality. There is also ```Microsoft.Extensions.Hosting```, which can be package referenced in console projects to enable hosting features.

But what about class librares that don't need ASP.NET Core and hosting capabilities? Is manually including these packages the only option, or is there a nuget package/metapackage, that includes commonly used abstractions?

**Comment by ericstj** [comment]
In the case you referenced above I believe just referencing `Microsoft.Extensions.Options.ConfigurationExtensions` would pull in most of those with the exception of `Microsoft.Extensions.Logging.Abstractions`.  I'm not seeing the problem with referencing the packages -- reference what you need.  Any meta-package might bring more than what you need (like hosting, for example).

**Comment by eerhardt** [comment]
I agree with @ericstj. For libraries - reference the packages you need manually. We don't have a "meta package" today, and I don't believe we could create one that would be correct for everybody. Some people want logging and DI, but not config.

So to answer your question - add PackageReferences for each package you need in your library.
