### ISSUE TITLE
CrossDac build is failing in internal build

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#67632]
See https://dev.azure.com/dnceng/internal/_build/results?buildId=1701715&view=logs&j=7a1cd7fd-8fa9-5ec1-980e-a4eb83346ea9&t=a7278a6c-3e31-578e-d34e-bccb203bb339

**Comment by tommcdon** [comment]
@hoyosjs is this a dupe to https://github.com/dotnet/runtime/issues/67446?

**Comment by tommcdon** [comment]
> @hoyosjs is this a dupe to #67446?

nevermind - the referenced bug is 3.1 and this one is 7.0

**Comment by hoyosjs** [comment]
@agocke CI? Or official build - I don't expect this to happen on a rolling CI even nor on PR.

**Comment by hoyosjs** [comment]
Looks like this is a regression caused by https://github.com/dotnet/runtime/pull/67108. I'll take on fixing this
