### ISSUE TITLE
Bitmap create new size as white image

### ISSUE THREAD

**Issue by Martin4code** [dotnet/runtime#67643]
### Description

This:
`Bitmap resized = new Bitmap(image, new Size(30, 30));`
creates white image from this (17 MB) image:
https://s4ccz-my.sharepoint.com/:i:/g/personal/martin_sulc_sense4code_com/EcJehrt4A69Cu1yNSdzDmKsB897a4dfiiE-JsGQPOwUA_w?e=K0o4Gd

### Reproduction Steps

Create new .Net (C#) project. (Console App)
Choose framework .NET 6.0 (Long-term support)
Add NuGet **System.Drawing.Common**.
Replace code in **Program.cs**:
```
using System.Drawing;

using (Image image = Image.FromFile("1982942201828844157.jpg"))
{
	using (Bitmap resized = new(image, new Size(20, 20)))
		resized.Save("20x20.jpg");
	using (Bitmap resized = new(image, new Size(30, 30)))
		resized.Save("30x30.jpg");
	using (Bitmap resized = new(image, new Size(40, 40)))
		resized.Save("40x40.jpg");
}
```
**Build** the app.

**Download** big image (17 MB) and save it into \bin\Debug\net6.0 as "1982942201828844157.jpg":
https://s4ccz-my.sharepoint.com/:i:/g/personal/martin_sulc_sense4code_com/EcJehrt4A69Cu1yNSdzDmKsB897a4dfiiE-JsGQPOwUA_w?e=K0o4Gd

Run the App.
It will create files:
20x20.jpg
30x30.jpg
40x40.jpg
And the **size 30x30.jpg will be the white image**.

I don't understand why.

### Expected behavior

Resized image to
20x20.jpg
30x30.jpg
40x40.jpg

### Actual behavior

The file 30x30.jpg is not resized original, it is a white image.

### Regression?

Not tested.

### Known Workarounds

Not yet.

### Configuration

Environment: Windows 10 Enterprise 21H2
Visual Studio Professional 2022 64 bit v17.1.3
NuGet System.Drawing.Common 6.0.0

### Other information

This function os fine on other images...

**Comment by danmoseley** [comment]
Do you get the same results if you use .NET Framework?
