### ISSUE TITLE
OSR variants may not report pinned locals as pinned

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#67668]
### Description

See here: https://github.com/dotnet/runtime/pull/66983#issuecomment-1090461322

### Reproduction Steps

Trigger OSR inside the loops in `System.Globalization.CompareInfo.IndexOfOrdinalHelper`.

### Expected behavior

The OSR variant keeps pinning variables that were pinned in tier-0.

### Actual behavior

The OSR variant does not report these locals as pinned anymore.

**Comment by AndyAyersMS** [comment]
Thanks. Looks like what I suspected, the OSR method sees the locals as pinned but also unreferenced... I think we just need to add an implicit reference.
```
;* V06 loc0         [V06    ] (  0,  0   )    long  ->  zero-ref   
;* V07 loc1         [V07    ] (  0,  0   )   byref  ->  zero-ref    pinned
;* V08 loc2         [V08    ] (  0,  0   )    long  ->  zero-ref   
;* V09 loc3         [V09    ] (  0,  0   )   byref  ->  zero-ref    pinned
```
