### ISSUE TITLE
Deterministic MVIDs is needed for assemblies referencing System.Private.CoreLib across different architectures

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#67660]
We're hitting an issue where the MVID of assemblies is different depending on the architecture of the runtime pack, e.g. x64 vs. arm64, for assemblies that are 100% managed code like System.Collections.dll or System.Private.Uri.dll but [compile against System.Private.CoreLib](https://github.com/dotnet/runtime/search?q=CoreLibProject+path%3Asrc%2Flibraries%2F).

This causes an issue for Xamarin Android and other internal teams that use the MVID to deduplicate assemblies that are the same across architectures (right now only System.Private.CoreLib.dll is actually architecture-specific).

The reason this is showing up now is because of a linker/Cecil fix (https://github.com/dotnet/linker/issues/2203,  https://github.com/mono/cecil/pull/31) which fixes the PDB ID calculation which in turn affects the MVID calculation (we actually just got lucky in net6 since we run the linker against all assemblies in the libraries build which "unified" the MVID).

Since the PDB is storing the MVID of all assembly references in "Compilation Metadata References" (described in https://github.com/dotnet/runtime/blob/424a09cb81c678fb1ba1c27211b80aba2de070ad/docs/design/specs/PortablePdb-Metadata.md#CompilationMetadataReferences) we now get a different MVID on the assemblies because these projects compile directly against System.Private.CoreLib.dll whose MVID gets embedded in the PDB:
![PDB](https://user-images.githubusercontent.com/1376924/162030287-97c39375-25e1-457f-b5b6-f384cd4c02ba.png)

There is interest to backport the linker/Cecil fix to net6 so I discussed with @vitek-karas and we agreed the least invasive change is to ~~simply hardcode System.Private.CoreLib.dll as the only architecture-specific assembly in Xamarin Android for net6~~. **EDIT** it turns out this plan won't work since the Mono AOT compiler verifies the MVIDs of assembly references and will error out if they don't match with the actual assembly.

For net7/net8 we'd like to come up with a "proper" fix though, some ideas:

- Create a reference assembly for System.Private.CoreLib and compile against that one, instead of the real assembly
	- I tried using Roslyn's /refout feature but the reference assembly created by it still differs between architectures since Roslyn includes private fields like [Padding.cs#L9-L16](https://github.com/dotnet/runtime/blob/c49c65df805304907185bbb4dab909672103ffef/src/libraries/System.Private.CoreLib/src/Internal/Padding.cs#L9-L16), so this'd likely need to be a real reference assembly
- Make System.Private.CoreLib architecture-agnostic by removing all of the `TARGET_64BIT` and `TARGET_32BIT` ifdefs.
- Tweak the (official) build so we only ever build the non-architecture-specific assemblies once and copy them into the respective runtime packs, ensuring that we only have a single version of the assemblies
  - As an extension we could split out the assemblies into another package, so they're not duplicated in the runtime packs. This would also help reducing download size.

/cc @ViktorHofer @vitek-karas @agocke @marek-safar @steveisok

**Comment by ViktorHofer** [comment]
See https://github.com/dotnet/runtime/blob/6762f54b4193dcf5103f3c03e7ebd0ef95578c54/eng/references.targets#L32-L39. We explicitly had to disable an msbuild check to be able to reference an arch specific assembly from an AnyCPU assembly. It would be great if you could eliminate this hack either by introducing a reference assembly or by making CoreLib arch agnostic.

**Comment by jonathanpeppers** [comment]
One issue that came up, is when using a .NET 7 SDK to build a `net6.0-android` app:
* You have the .NET 7 linker, and it's newer Mono.Cecil behavior
* You have the old .NET 6 `System.Private.CoreLib.dll`

So if there was a ref assembly for `System.Private.CoreLib.dll`, it wouldn't fix building `net6.0` apps in .NET 7?

**Comment by vitek-karas** [comment]
@jonathanpeppers I think the answer is yes - the linker would produce different MVIDs for different archs of framework assemblies since they would be .NET 6 framework which would have internally different assemblies per arch (if nothing else, due to the CoreLib difference).
