### ISSUE TITLE
Blazor WASM: PostAsJsonAsync missing response header content-disposition

### ISSUE THREAD

**Issue by ghostinside** [dotnet/runtime#67691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

client:
```c#
var response = await ApiCall(async () => await _httpService.ApiClient.PostAsJsonAsync(apiUrl, request));
await response.EnsureSuccessAsync();

var stream = await response.Content.ReadAsStreamAsync();

return new DownloadFileStream
{
    FileName = response.Content.Headers.ContentDisposition?.FileNameStar ??
        response.Content.Headers.ContentDisposition?.FileName,
    FileStream = stream
};
```

server:
```c#
[HttpPost]
[Route("products/revoked/download/excel/{includeComponents}")]
public async Task<IActionResult> ProductsRevokedDownloadExcelAsync(ProductReportDataRequest request, int includeComponents)
{
    var exportModel =
        await _mediator.Send(
            new ProductListExcelExportCommand("D", request, includeComponents, "Revoked View"));

    return File(ExportHelper.GenerateDocumentStream(exportModel), "application/octet-stream", exportModel.FullFileName);
}
```

Response Headers in browser:

```
access-control-allow-credentials: true
access-control-allow-origin: https://localhost:5000
**content-disposition**: attachment; filename=Approval_View.xlsx; filename*=UTF-8''Approval_View.xlsx
content-length: 17449
content-type: application/octet-stream
date: Wed, 06 Apr 2022 19:18:02 GMT
server: Kestrel
vary: Origin
```

In Code (`Console.WriteLine($"Response Headers: {JsonSerializer.Serialize(response.Content.Headers)}");`):

`Response Headers: [{"Key":"Content-Length","Value":["17424"]},{"Key":"Content-Type","Value":["application/octet-stream"]}]`

so content-disposition header is missing

### .NET Version

6.0.201

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

**Comment by ghostinside** [comment]
GetAsync does not have content disposotion header too despite having it in browser 

`
attachment; filename=CoverLetter.xdp; filename*=UTF-8''CoverLetter.xdp
`

**Comment by maraf** [comment]
@ghostinside Thanks for the snippets. I have integrated them into the empty blazor app on .NET 6 and I'm able to read `content-disposition` header. 

> access-control-allow-credentials: true
> access-control-allow-origin: https://localhost:5000

Does it mean you are posting a cross-origin request? 
Can you confirm that you configured `Access-Control-Allow-Headers` on the server? 
https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-6.0#how-cors-works

**Comment by ghostinside** [comment]
@maraf  
thx for getting into the issue  & advice what to check, I was not able to make it work on localhost (client :5000 server :5001) despite having 
`app.UseCors(builder => builder.SetIsOriginAllowed(_=> true).AllowAnyHeader().AllowAnyMethod().AllowCredentials());`
but I was able to get the required header when request comes within the same domain 
`[{"Key":"Content-Disposition","Value":["attachment; filename=Components.xlsx; filename*=UTF-8\u0027\u0027Components.xlsx"]},{"Key":"Content-Length","Value":["12710"]},{"Key":"Content-Type","Value":["application/octet-stream"]},{"Key":"Expires","Value":["Thu, 01 Jan 1970 00:00:00 GMT"]}]`

appreciate for help

**Comment by maraf** [comment]
@ghostinside You need to specify which headers is client allowed to read, using [CorsPolicyBuilder.WithExposedHeaders](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.cors.infrastructure.corspolicybuilder.withexposedheaders?view=aspnetcore-6.0). 
The `CorsPolicyBuilder.AllowAnyHeader` just allows any request header on the server.

**Comment by lewing** [comment]
Sounds like we can close this, feel free to reopen if there if you don't feel it has been resolved.
