### ISSUE TITLE
Clean up CORINFO_HELP_ASSIGN_BYREF for x86/x64

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#67707]
1. Precisely define the registers trashed by x64: currently it appears to be overstating the set.
2. Define/use RBM_CALLEE_TRASH_WRITEBARRIER_BYREF, RBM_CALLEE_GCTRASH_WRITEBARRIER_BYREF, consistently. Maybe also REG_WRITE_BARRIER_DST_BYREF, REG_WRITE_BARRIER_SRC_BYREF, and related.
3. Add a detailed header comment to targetamd64.h, targetx86.h, like there is in targetarm64.h

[edit: 2 and 3 were fixed with #67790]

category:cq
theme:helpers
skill-level:intermediate
cost:small
impact:medium

**Comment by jakobbotsch** [comment]
Note that this comment indicates that there may be some more work involved with this:
https://github.com/dotnet/runtime/blob/c288acdb794b1f2edba90868a823b161d88bd2b0/src/coreclr/jit/codegencommon.cpp#L564-L584

**Comment by BruceForstall** [comment]
> Note that this comment...

Yes, unfortunately there are somewhat sparse details in that comment...

**Comment by PeterSolMS** [comment]
It would definitely be nice if JIT_ByRefWriteBarrier (CORINFO_HELP_ASSIGN_BYREF) could use one more register in release builds, maybe r11, which would make it consistent with debug builds.

**Comment by EgorBo** [comment]
Closed by https://github.com/dotnet/runtime/pull/99134
