### ISSUE TITLE
Improve code coverage of RegexOptions.NonBacktracking

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#67720]
We have some areas that aren't being touched by existing tests.  Some of this is known to be dead code that needs to be removed (e.g. SymbolicRegexNodeKind.Or), some of it is probably due to missing tests.  We need to go through, reviewing all the gaps, removing code as is appropriate and adding new tests where appropriate.

**Comment by joperezr** [comment]
After chatting with @olsaarik this will likely miss ZBB. Also, we have done a manual run where we forced-down the DFA vs NFA threshold to flush out any remaining issues with NFA engine, so this test-only change, while still important, should not block 7.0. For this reason, I'm adjusting the milestone, even though the work is still likely to happen before 7.0 actually ships.
