### ISSUE TITLE
Publish NativeAOT compiler with NativeAOT

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#67742]
Once crossgen2 is published with NativeAOT, we should publish the NativeAOT compiler the same way to keep them in sync.

**Comment by filipnavara** [comment]
FWIW aside from the work on getting the .csproj do the bootstrapping and publishing it seems to work. I compiled the `ilc` just fine into native code on osx-x64 and then used it to build some library tests.

**Comment by MichalStrehovsky** [comment]
> FWIW aside from the work on getting the .csproj do the bootstrapping and publishing it seems to work

Yes, that's basically where all the work is. We need to build with the live built compiler/runtime/libs, which makes things harder. Crossgen2 is already on that plan, but it's not straightforward to reuse that: https://github.com/dotnet/runtime/pull/67636/files

**Comment by filipnavara** [comment]
It's quite reusable for the second step. Once you have some `ilc` then adapting the Crossgen2 .csproj logic works. It's a bit tricky to do all of this automatically though.

**Comment by agocke** [comment]
This work has been done

**Comment by MichalStrehovsky** [comment]
> This work has been done

This was tracking publishing with the live bits - without doing that, we'll still have issues like a couple months ago when we had to wait an extra release for the libc version switch to take effect because we're using lkg. We can say we're fine with that but wanted to call it out.

Also we don't currently publish with ilc for architectures that are built with crossbuild (all of arm64 ones). We could be fine with that too, but wanted to call out.
