### ISSUE TITLE
Expand CoreCLR testing

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#67743]
Add means to run all Pri-0 CoreCLR tests in rolling builds.

A full test pass takes about 4 hours on the CI machine, as long as we have 2500+ tiny test exes to compile. This number is for multimodule configuration mode that we don't ship. A full test pass in singlemodule compilation mode (that recompiles corelib every time we build a test) takes almost 7 hours on my 2015 MacBook. Never tried it in the CI.

Most of the pri-0 tests should already be baselined in issues.targets, so a Pri-0 run should be very close to being clean (at least on Windows; we haven't run it on Linux, probably ever).

**Comment by agocke** [comment]
This is probably dependent on test consolidation , FYI @jkoritzinsky @trylek

**Comment by MichalStrehovsky** [comment]
This was fixed, we run Pri-0 tests in the rolling build.
