### ISSUE TITLE
Generation of references will generate several changes

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#67784]
### Description

This [document](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/updating-ref-source.md#for-systemruntime) provides the steps you need to take to update the reference assembly when adding new public APIs to an implementation assembly. The problem with executing the commands currently (no changes added to the API surface) will generate the following info
```
1 file changed, 1849 insertions(+), 1863 deletions(-)
```
They are three things that I think could be happening:
- The command generates the wrong code, and the command needs to be changed 
- The command generated some code, but intentionally we want to override that behavior (maybe we could use an exception list to avoid changing that code)
- The generated code is correct and was just wrongfully added (they just need to be fixed)

### Reproduction Steps

Go to `runtime\src\libraries\System.Runtime\src` and execute `dotnet build --no-incremental /t:GenerateReferenceSource`

### Expected behavior

The experience should be:
- Someone changes an API
- Run the command to update the ref file
- Verify the change and commit

### Actual behavior

The experience now is:
- Someone changes an API
- Run the command to update the ref file
- Look for his changes between the ~1800 lines
- Cherry-picks those changes
- Revert the command execution to get the original reference file
- Add the changes from the script manually
- Commit

Notice that every added step is prone to add something that is wrong in the reference, they are several diffs that are flagged because they were added manually and contain some sort of error.

**Comment by ViktorHofer** [comment]
cc @tannergooding as you just recently opened https://github.com/dotnet/arcade/pull/8769. Are you aware of the diff being reported here? I wasn't.

**Comment by ViktorHofer** [comment]
@tlakollo I'm closing this issue as the current behavior is documented. Even though it's not ideal, it's the best that we currently have based on the tooling that we use underneath to generate these reference source files.
