### ISSUE TITLE
It was not possible to find any installed .NET Core SDKs *when running in a docker container*

### ISSUE THREAD

**Issue by Sri-darshan** [dotnet/runtime#67796]
I am also facing the similar issue, but I havent mounted any volume externally

Below is my dockerfile

================================
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["API/API.csproj", "API/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Utility/Utility.csproj", "Utility/"]
COPY ["DataCore/DataCore.csproj", "DataCore/"]
RUN dotnet restore "API/API.csproj"
COPY . .
WORKDIR "/src/API"
RUN dotnet build "API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
#COPY --from=publish /app/publish . #tried this but no luck#
COPY --from=publish publish .

ENTRYPOINT ["ls", "."] #No o/p#
ENTRYPOINT ["dotnet", "--info"] #No o/p#
ENTRYPOINT ["dotnet", "run", "app/API.dll"]
#ENTRYPOINT ["dotnet", "run", "API.dll"] #no luck either#

========================================
docker logs 9e579eb345e0
It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
https://aka.ms/dotnet-download[]
========================================
My code is in gitlab and using gitlab-ci for CICD
Pipeline executing successfully but container crashing with above error
====================================
My job log....
Fetching changes...
00:02
HEAD is now at 4c3309[7](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L7) Update Dockerfile
From https://git.*******.com/internal/Mobe-backend
   4c33097..a5dab03  dev        -> origin/dev
Checking out a5dab03b as dev...
Skipping Git submodules setup
$ sudo docker build -t backend -f API/Dockerfile . --no-cache
Step 1/21 : FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
 ---> 46e33aaeb772
Step 2/21 : WORKDIR /app
 ---> Running in 16[8](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L8)a6c26ba02
Removing intermediate container 168a6c26ba02
 ---> c7[9](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L9)a1dd87d36
Step 3/21 : EXPOSE 80
 ---> Running in b96786bc0259
Removing intermediate container b96786bc0259
 ---> c370bcb9723c
Step 4/21 : FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
 ---> 18588de00fb4
Step 5/21 : WORKDIR /src
 ---> Running in 9e6a19939658
Removing intermediate container 9e6a19939658
 ---> c635f1cf2e8a
Step 6/21 : COPY ["API/API.csproj", "API/"]
 ---> be76f87ffa14
Step 7/21 : COPY ["Domain/Domain.csproj", "Domain/"]
 ---> 5b4eebed86bf
Step 8/21 : COPY ["Utility/Utility.csproj", "Utility/"]
 ---> e5b0bfcb1fe9
Step 9/21 : COPY ["DataCore/DataCore.csproj", "DataCore/"]
 ---> 06ee8a80504d
Step [10](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L10)/21 : RUN dotnet restore "API/API.csproj"
 ---> Running in 999e426e05f2
  Determining projects to restore...
  Restored /src/Utility/Utility.csproj (in 177 ms).
  Restored /src/Domain/Domain.csproj (in 1.43 sec).
  Restored /src/DataCore/DataCore.csproj (in 1.44 sec).
  Restored /src/API/API.csproj (in 2.8 sec).
Removing intermediate container 999e426e05f2
 ---> c1623620e995
Step [11](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L11)/21 : COPY . .
 ---> ffe24c3e16a8
Step 12/21 : WORKDIR "/src/API"
 ---> Running in 64d20b0aebac
Removing intermediate container 64d20b0aebac
 ---> 246649b7b50e
Step 13/21 : RUN dotnet build "API.csproj" -c Release -o /app/build
 ---> Running in 0a2202d84775
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  All projects are up-to-date for restore.
Cryptography.cs(162,30): warning CS0168: The variable 'ex' is declared but never used [/src/Utility/Utility.csproj]
  Utility -> /app/build/Utility.dll
  Domain -> /app/build/Domain.dll
  DataCore -> /app/build/DataCore.dll
  API -> /app/build/API.dll
Build succeeded.
Cryptography.cs(162,30): warning CS0168: The variable 'ex' is declared but never used [/src/Utility/Utility.csproj]
    1 Warning(s)
    0 Error(s)
Time Elapsed 00:00:05.96
Removing intermediate container 0a2202d84775
 ---> a468ec491e11
Step 14/21 : FROM build AS publish
 ---> a468ec491e11
Step [15](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L15)/21 : RUN dotnet publish "API.csproj" -c Release -o /app/publish
 ---> Running in be553f710236
Microsoft (R) Build Engine version [16](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L16).7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Utility -> /src/Utility/bin/Release/netcoreapp3.1/Utility.dll
  Domain -> /src/Domain/bin/Release/netcoreapp3.1/Domain.dll
  DataCore -> /src/DataCore/bin/Release/netcoreapp3.1/DataCore.dll
  API -> /src/API/bin/Release/netcoreapp3.1/API.dll
  API -> /app/publish/
Removing intermediate container be553f710236
 ---> a4f0b494418d
Step 16/21 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
 ---> 46e33aaeb772
Step [17](https://****.com/internal/Mobe-backend/-/jobs/9008#L17)/21 : WORKDIR /app
 ---> Running in d6d6c4b1a033
Removing intermediate container d6d6c4b1a033
 ---> df3d12490a31
Step [18](https://******.com/internal/Mobe-backend/-/jobs/9008#L18)/21 : COPY --from=publish /app/publish .
 ---> d33a0dbc9578
Step [19](https://******.com/internal/Mobe-backend/-/jobs/9008#L19)/21 : ENTRYPOINT ["ls", "."]
 ---> Running in f562898497c3
Removing intermediate container f562898497c3
 ---> 56b9d184cb97
Step [20](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L20)/[21](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L21) : ENTRYPOINT ["dotnet", "--info"]
 ---> Running in 7c8fc7bf12dd
Removing intermediate container 7c8fc7bf12dd
 ---> f789095b09dc
Step 21/21 : ENTRYPOINT ["dotnet", "run", "/src/API/bin/Release/netcoreapp3.1/API.dll"]
 ---> Running in 2c976db3002e
Removing intermediate container 2c976db3002e
 ---> 772f38d974bf
Successfully built 772f38d974bf
Successfully tagged backend:latest
$ sudo docker run -d -p [23](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L23)[45](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L45):[80](https://git.*******.com/internal/Mobe-backend/-/jobs/9008#L80) backend
================================================
I have no clue how to fix this, could someone pls help me

**Comment by jkotas** [comment]
> ENTRYPOINT ["dotnet", "run", "app/API.dll"]

This should be just `ENTRYPOINT ["dotnet", "app/API.dll"]`.

`dotnet run` is meant to be used with the .csproj file and it needs SDK to be installed.

**Comment by Sri-darshan** [comment]
Even after adding ur suggested changes, still no change :(
Step 21/21 : ENTRYPOINT ["dotnet", "app/API.dll"].
 ---> Running in ba4b63c9ea70
Removing intermediate container ba4b63c9ea70
 ---> 3b73248856e3
Successfully built 3b73248856e3
Successfully tagged backend:latest
$ sudo docker run -d -p 2345:80 backend
6b8cb7e83518720d629c605c442175b99a98ed3189d3716425e4b0a0bc97c008
======================
docker logs 6b8cb7e83518
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
root@ip-10-0-32-182:/home/ubuntu#

**Comment by jkotas** [comment]
You do not need SDK installed in the final container. 

Could you please run `ls app/API.dll` in the final container to verify that the file exists?

**Comment by Sri-darshan** [comment]
Pipeline exiting here
![image](https://user-images.githubusercontent.com/63836175/162626850-2b584ac3-5144-4f56-bd7c-db66369ccbb6.png)

**Comment by Sri-darshan** [comment]
But build is getting succeeded...very weird
