### ISSUE TITLE
how can i get the abs publish dir in csproj?

### ISSUE THREAD

**Issue by liesauer** [dotnet/runtime#678]
because of the changes between 2.x and 3.x, i can not find a compatible formula to calcute the right abs publish dir.

i have tried `$(PublishDir)` and `$([System.IO.Path]::GetFullPath('$(PublishDir)'))`, but it always be wrong in some situations(build with 2.x sdk or build with 3.x sdk, with or without `-o` option, `-o` option is absolute dir or relative dir)

but i have  realized that the dir output by sdk always be right, so how can i get this dir in my `.csproj` file?

![image](https://user-images.githubusercontent.com/8676741/70406583-37a44200-1a7c-11ea-9b14-464a55831437.png)

**Comment by ViktorHofer** [comment]
Is this question related to the runtime repo at all? Should we move it instead into  dotnet/toolset?

**Comment by liesauer** [comment]
em, you are right. but tons of dotnet repos just make us confused and dotnet/core-setup just merge into runtime recently

**Comment by am11** [comment]
@liesauer, you can try adding a target in your csproj, and take advantage of MSBuild's `ItemGroup`, which provides file related metadata and resolves path implicitly:

```csproj
<Target Name="MyCustomPrePublishTarget" AfterTargets="PrepareForPublish">
  <ItemGroup>
    <PublishDir Include="$(PublishDir)" />
  </ItemGroup>

  <Message Importance="High" Text="Absolute PublishDir is: %(PublishDir.FullPath)" />
</Target>
```

and then try different things:

```sh
# in same directory as project, with relative output
dotnet publish my.csproj -o ./myoutput

# in different directory than project file, with relative output
dotnet publish path/to/my.csproj -o another/path/to/output

# absolute path to project and relative path to output
# vice-versa
# both absolute
```

and look for `Absolute PublishDir is: ....` message in output. This `MyCustomPrePublishTarget` target will run just before the actual publish target and will have `PublishDir` set to the value of `-o` (unchanged). We can also change/overwrite its value in this target based on some condition, for instance:

```xml
<Target Name="MyCustomPrePublishTarget" AfterTargets="PrepareForPublish">
  <ItemGroup>
    <PublishDir Include="$(PublishDir)" />
  </ItemGroup>

  <PropertyGroup>
    <PublishDir>%(PublishDir.FullPath)</PublishDir>
    <PublishDir Condition=" $(PublishDir.Contains('unwanted')) ">some/default/path</PublishDir>
  </PropertyGroup>
</Target>
```

```sh
dotnet publish -o /temp/unwanted/test
# will publish in <current-working-directory>/some/default/path

dotnet publish -o /temp/different/path
# will publish in /temp/different/path
```

**Comment by liesauer** [comment]
@am11 thanks!

this really solve my  problem perfectly
```
  <ItemGroup>
    <PublishDir Include="$(PublishDir)" />
  </ItemGroup>

  <PropertyGroup>
    <MyAbsPublishDir>%(PublishDir.FullPath)</MyAbsPublishDir>
  </PropertyGroup>
```
