### ISSUE TITLE
[NativeAOT] ILC: AOT analysis error IL1005 Vararg call not supported

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#67804]
### Description

there is an error when building the driver

### Reproduction Steps

```C#
        [MethodImpl(MethodImplOptions.InternalCall)]
        [RuntimeImport("ntoskrnl.exe", "DbgPrint")]
        public static extern ulong _DbgPrint(byte* Format, __arglist);

        static NTSTATUS DriverEntry()
        {
            _DbgPrint("%d".asstr(), __arglist(2));
            return NTSTATUS.Success;
        }
        public static byte* asstr(this string str)
        {
            fixed (char* wc = str)
            {
                var buf = ExAllocatePool(PoolType.NonPagedPool, (ulong)str.Length + 20);
                for (int i = 0; i < str.Length; i++)
                    buf[i] = (byte)wc[i];
                buf[str.Length] = (byte)0;
                return buf;
            }
        }
```

### Expected behavior

build without any problems

### Actual behavior

`ILC: AOT analysis error IL1005: testdriver.Program.DriverEntry(): Method will always throw because: Vararg call to 'UInt64 testdriver.WDK._DbgPrint(Char*)' not supported`

**Comment by jkotas** [comment]
varargs are supported only on Windows for C++/CLI compatibility. C++/CLI is not supported by NativeAOT.

More general support for varargs is tracked by #48796.

**Comment by jkotas** [comment]
Listed in https://github.com/dotnet/runtimelab/issues/155

**Comment by AhmedZero** [comment]
I hope to support it soon. thanks.
