### ISSUE TITLE
FreeBSD's Interop.Process.cs has an off-by-1000 error

### ISSUE THREAD

**Issue by coypoop** [dotnet/runtime#67807]
In [Interop.Process.cs#L186-L187](../blob/main/src/libraries/Common/src/Interop/FreeBSD/Interop.Process.cs#L186-L187) we see the following lines:

```
(ulong)list[i].ki_rusage.ru_stime.tv_sec * SecondsToNanoseconds + (ulong)list[i].ki_rusage.ru_stime.tv_usec;
                      units must be nanoseconds  ^        but it looks like they're microseconds here ^
```

This has to be a mistake.

**Comment by danmoseley** [comment]
It does on the face of it. Are you interested in offering (and testing) a fix?

**Comment by cxmplex** [comment]
@danmoseley I submitted a PR for it since it's been a few days.
