### ISSUE TITLE
Cannot debug on CentOS Stream 9 from Visual Studio 2022 (Kernel 5.14)

### ISSUE THREAD

**Issue by MrM40** [dotnet/runtime#67818]
### Describe the bug
When I try to debug an assembly running on CentOS Stream 9 from VS 2022 using SSH I get this error in VS:

![error](https://user-images.githubusercontent.com/16258063/160282714-7b5dbeb5-2209-4222-9ace-705664d2f119.jpg)

It works fine with others Linux installations e.g. Debian 11 bullseye. Although I haven't tried other with kernel 5.14 as CentOS Stream 9 use...don't know if the new kernel is the issue?

Normally I install SDK manually but to be sure I also tried to install SDK using the package from the official repo:
`dnf install dotnet-sdk-6.0.x86_6`

### To Reproduce
I'll try to make small test-project...I'll update with a link

### Further technical details
DOTNET INFO:
```
[root@CentOS-01 ~]# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102 (also tried 6.0.201, same problem)
 Commit:    49861cb924

Runtime Environment:
 OS Name:     centos
 OS Version:  9
 OS Platform: Linux
 RID:         centos.9-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.102 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
````
DISTRO INFO:
```
Distro info:
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

Kernel-release: 5.14.0-71.el9.x86_64
Kernel-version:    dotnet/sdk#1 SMP PREEMPT Tue Mar 8 20:35:50 UTC 2022
```

**Comment by danmoseley** [comment]
This seems like it's for the diagnostics team.

**Comment by tommcdon** [comment]
@hoyosjs

**Comment by MrM40** [comment]
Just gave OpenSUSE 15.4 a try (also kernal 5.14) and debugging works fine, so it seems to be RHEL'ish 9.x related :-/

**Comment by hoyosjs** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/19413848/178857151-6328183d-4a42-42ec-bd54-1cce779a4ffc.png">

I can debug this fine with centos on an older kernel, and centos stream 9 in both 6.0 and 7.0:

``` 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

```
Linux e08a68cbc637 5.15.0-1014-azure
``` 

Closing this as no repro since centos + kernel version wasn't enough to repro even with the same project.
