### ISSUE TITLE
Windows arm64 Tests failing on DDARM64-132

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#67821]
Example of the log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67774-merge-bbcfa5ff54a3482cb8/profiler.transitions/1/console.cc2581a0.log?sv=2019-07-07&se=2022-04-30T07%3A34%3A10Z&sr=c&sp=rl&sig=%2FEI53WaNPE73mV2L3H0ORI4rqfH87tVi0DfxRVx97fw%3D

The log does not have any details about the failure.

Console log: 'profiler.rejit' from job 1bec3f43-7d47-4f00-9299-6cefc1cd6299 workitem 365fa792-6588-4765-bb67-642543d541b7 (windows.10.arm64v8.open) executed on machine DDARM64-132

Failed in #67817, #67774 and many other jobs. It is a different test each time. The only common pattern is `DDARM64-132` machine name.

**Comment by jkotas** [comment]
@dotnet/dnceng Could you please remove `DDARM64-132` from the pool and check its health?

**Comment by danmoseley** [comment]
Cc @dotnet/dncenghot

**Comment by jakobbotsch** [comment]
Similar looking failure in https://dev.azure.com/dnceng/public/_build/results?buildId=1709921&view=ms.vss-test-web.build-test-results-tab&runId=46511082&resultId=108903&paneView=debug on a different machine: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67238-merge-9e174ab97ff8449ab2/JIT.HardwareIntrinsics.X86.Avx1/1/console.310ed48e.log?sv=2019-07-07&se=2022-04-30T23%3A51%3A23Z&sr=c&sp=rl&sig=NCIi6AFYy6maoBk1tHEkmJxAq%2FznXMWAbfiHy4IpcIA%3D

**Comment by dkurepa** [comment]
Hello, I'll take the machine offline, you can follow the issue on our side at https://github.com/dotnet/arcade/issues/9016

**Comment by MattGal** [comment]
for -046 (more recent log) I filed https://github.com/dotnet/arcade/issues/9024 (@agocke FYI)

**Comment by jakobbotsch** [comment]
Same problem now seems to be occurring on DDARM64-125, e.g. [run 1](https://dev.azure.com/dnceng/public/_build/results?buildId=1724402&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382), [run 2](https://dev.azure.com/dnceng/public/_build/results?buildId=1724587&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382&s=96ac2280-8cb4-5df5-99de-dd2da759617d).

**Comment by lpatalas** [comment]
I took that machine offline and created https://github.com/dotnet/arcade/issues/9088 to follow up

**Comment by agocke** [comment]
Dup against https://github.com/dotnet/arcade/issues/9088

**Comment by ulisesh** [comment]
Unfortunately, the output generated by machines in a bad state is empty so we can generate a known issue for it. I'm not sure how @ilyas1974 is tracking how often machines have to be reimaged
