### ISSUE TITLE
gcenv.interlocked's Interlocked use full memory barriers even with 8.1 Atomics

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#67824]
All `Interlocked` functions from [gcenv.interlocked.inl](https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/env/gcenv.interlocked.inl) seem to insert full memory barriers, e.g. consider this usage (GC seems to heavily use them under BACKGROUND_GC):
```c++
void GCHeap::SetSuspensionPending(bool fSuspensionPending)
{
    if (fSuspensionPending)
    {
        Interlocked::Increment(&g_fSuspensionPending);
    }
    else
    {
        Interlocked::Decrement(&g_fSuspensionPending);
    }
}
```
Disassembled on Apple M1:
![image](https://user-images.githubusercontent.com/523221/162631504-b35b9810-a6d0-40b2-ab74-8b4dacad7287.png)

Interlocked is implemented like this:
```c++
template <typename T>
__forceinline T Interlocked::Increment(T volatile *addend)
{
#ifdef _MSC_VER
    static_assert(sizeof(long) == sizeof(T), "Size of long must be the same as size of T");
    return _InterlockedIncrement((long*)addend);
#else
    T result = __sync_add_and_fetch(addend, 1);
    ArmInterlockedOperationBarrier();
    return result;
#endif
}
```
see godbolt: https://godbolt.org/z/3jPx3Mz14

From my understanding we don't need full memory barriers in the case when we use 8.1 atomics. Same applies to all `Interlocked` functions in [gcenv.interlocked.inl](https://github.com/dotnet/runtime/blob/main/src/coreclr/gc/env/gcenv.interlocked.inl)
These barriers are needed on 8.0 where C++ compilers lower builtin atomic intrinsics without them for some reason (see https://patchwork.kernel.org/project/linux-arm-kernel/patch/1391516953-14541-1-git-send-email-will.deacon@arm.com/)

JIT does the same, e.g. for C#:
```csharp
void Foo(ref int x) => Interlocked.Increment(ref x);
```
it produces on arm64-8.0:
```asm
        885FFC23          ldaxr   w3, [x1]
        11000462          add     w2, w3, #1
        8800FC22          stlxr   w0, w2, [x1]
        35FFFFA0          cbnz    w0, G_M24917_IG02
        D5033BBF          dmb     ish  ;; <----
```
and this on >=8.1:
```asm
        52800020          mov     w0, #1
        B8E00020          ldaddal w0, w0, [x1]
```

cc @VSadov 

PS: Yes, when we compile CoreCLR for Apple M1 we unintentionally use `-mcpu=apple-m1` and use all the new shiny instructions e.g. arm v8.3's ldapr, 8.1 atomics, etc.. (well, makes sense 🤷‍♂️)

**Comment by EgorBo** [comment]
I removed these barriers and lowered number of `dmb ish` from 305 to 5 in `libcoreclr.dylib`

**Comment by VSadov** [comment]
Right. If `-mcpu=apple-m1` is guaranteed to use 8.1 atomic instructions, there is no need for the extra membarrier. 

Also - I think GC has its own copy of Interlocked, separate from what runtime uses. I wonder if Interlocked in the runtime could use the same change.

**Comment by Maoni0** [comment]
thank you very much for noticing this @EgorBo ! how stressful are tests run with TE infra (I thought they were mostly small perf tests?)? we do have a [stress infra](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/workflow/testing/coreclr/gc-stress-run-readme.md) for GC.

**Comment by EgorBo** [comment]
> thank you very much for noticing this @EgorBo ! how stressful are tests run with TE infra (I thought they were mostly small perf tests?)? we do have a [stress infra](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/workflow/testing/coreclr/gc-stress-run-readme.md) for GC.

Sure, will try the stress infra, thanks!

**Comment by janvorli** [comment]
Is this something that we still want to change for 7.0?

**Comment by EgorBo** [comment]
I know that @kunalspathak has some progress in a related issue and I personally probably will just remove that explicit memory barrier for OSX-arm64 at least.

**Comment by kunalspathak** [comment]
That's right. I am currently working on a prototype to have this removed and hoping to make it to 7.0

**Comment by kunalspathak** [comment]
@Maoni0  - Do we want to extend https://github.com/dotnet/runtime/pull/71512 for GC code. When I tried to do something similar for Windows/arm64 in https://github.com/dotnet/runtime/pull/71169, we didn't see much benefits and hence didn't optimize windows/arm64.

**Comment by Maoni0** [comment]
thanks @kunalspathak. unless you believe the linux scenario is different (like the full barrier we are doing is somehow a lot more expensive on linux than on windows), I would say let's not do this for linux either.

**Comment by kunalspathak** [comment]
Sounds good. I will close this issue then.
