### ISSUE TITLE
ecdh sharekey

### ISSUE THREAD

**Issue by ByboyCn** [dotnet/runtime#67832]
### Description

When I use ecdh for cross-language projects, I find that if the pubkey returned by the other party is already at the beginning of 02 (or 03), there is no way to successfully produce sharekey. Does c # provide a way to calculate Q.Y through Q.X?

### Reproduction Steps

Return sharekey normally

### Expected behavior

Return sharekey normally

### Actual behavior

Return sharekey normally

**Comment by ByboyCn** [comment]
I know how to calculate Q.Y through Q.X, but the calculation of that big number gives me a headache. His formula is probably `y^2 = x^3 + ax + b (mod p) `

**Comment by ByboyCn** [comment]
In addition, how should I produce a public key like 02 (or 03)? I know it only has Q.X, but it is not clear whether to use 02 or 03.

**Comment by ByboyCn** [comment]
Do I now have to write my own large numbers to complete the ECDH operation?

> > Does c # provide a way to calculate Q.Y through Q.X?
> 
> .NET does not currently support hybrid or compressed EC points (neither for Q, G, etc), neither for importing keys or exporting keys. This is a limitation of the platforms that are supported. macOS for example does not support compressed points, and to my knowledge, neither does Windows.
> 
> There may be other 3rd party libraries that are able compress / uncompress public keys to make them interoperable with .NET, but I lack a specific example of a library that I know can do this.

Do I now have to write my own large numbers to complete the ECDH operation?

**Comment by vcsjones** [comment]
> Do I now have to write my own large numbers to complete the ECDH operation?

If you have compressed EC keys, you will need to convert them to uncompressed keys (A full X and Y). Rather than do the implementation yourself, I would recommend using a 3rd party library that is capable of doing this. BouncyCastle for .NET might be able to.

**Comment by ByboyCn** [comment]
3Q

> > Do I now have to write my own large numbers to complete the ECDH operation?
> 
> If you have compressed EC keys, you will need to convert them to uncompressed keys (A full X and Y). Rather than do the implementation yourself, I would recommend using a 3rd party library that is capable of doing this. BouncyCastle for .NET might be able to.

3Q
