### ISSUE TITLE
Struct values with no set fallback to default. 

### ISSUE THREAD

**Issue by cmcmarrow** [dotnet/runtime#67835]
### Description

Struct values with no `set` fallback to default. I cant find anything saying this is excepted behavior.

### Reproduction Steps

```
using System.Runtime.Serialization;
using System.Text.Json;


namespace program
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Coord coord = new Coord(45, 4);
            Coord coord2 = Serialization.Copy(coord);
            Console.WriteLine(coord2.X);
        }
    }
    public class Serialization
    {
        public static T Copy<T>(T obj)
        {
            T? copy = JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(obj));
            if (copy is null)
            {
                throw new SerializationException();
            }
            return copy;
        }
    }
    public struct Coord
    {
        private int _x;
        private int _y;

        public Coord(int x, int y)
        {
            _x = x;
            _y = y;
        }

        public int X { get => _x; }
        public int Y { get => _y; }
    }
}
```

### Expected behavior

struct should be populated with data

### Actual behavior

struct is populated with default values

### Known Workarounds

1. give all values `set`
2. making the struct into a class

### Configuration

 .NET 6, WIN 10, X64

**Comment by Tornhoof** [comment]
You need to add ``[JsonConstructor]`` to your constructor. It's documented here:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-6-0
> For a struct, or a class with multiple constructors, specify the one to use by applying the [[JsonConstructor]](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconstructorattribute) attribute.

**Comment by eiriktsarpalis** [comment]
@cmcmarrow does @Tornhoof's response answer your question?

**Comment by cmcmarrow** [comment]
@eiriktsarpalis [JsonConstructor] makes everything work like the doc says. But class and struct init differently when no `[JsonConstructor]` is given. Which seems like undefined behavior.
