### ISSUE TITLE
System.Diagnostics.Perf_Process.GetProcessById has regressed 50% on Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67847]
`System.Diagnostics.Perf_Process.GetProcessById` has regressed 50% on Windows

[Reporting System](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Diagnostics.Perf_Process.GetProcessById.html):

![image](https://user-images.githubusercontent.com/6011991/162775224-5a98262f-8613-4f2b-add8-4c7e1e07eacd.png)

Looking at the [commit diff](https://github.com/dotnet/runtime/compare/18d9496d0f57def6ea803cbb9d3f085e7428f205...1b75f4264ebafaa72340ff0c972d43e5ab975ebb) it's most likely caused by #64723 (cc @epeshk)

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_monthly.py net7.0-preview2 net7.0-preview3 --filter System.Diagnostics.Perf_Process.GetProcessById
```

<details>

## System.Diagnostics.Perf_Process.GetProcessById

| Result | Ratio | Operating System      | Bit   |
| ------ | -----:| --------------------- | ----- |
| Slower |  0.48 | Windows 10            | X64   |
| Slower |  0.50 | Windows 11            | X64   |
| Slower |  0.49 | Windows 11            | X64   |
| Slower |  0.44 | Windows 11            | X64   |
| Same   |  1.02 | alpine 3.13           | X64   |
| Same   |  1.02 | centos 7              | X64   |
| Same   |  0.97 | debian 11             | X64   |
| Same   |  0.96 | pop 20.04             | X64   |
| Same   |  1.00 | ubuntu 18.04          | X64   |
| Faster |  1.15 | ubuntu 18.04          | X64   |
| Same   |  0.96 | alpine 3.12           | Arm64 |
| Faster |  1.18 | debian 11             | Arm64 |
| Same   |  1.01 | ubuntu 18.04          | Arm64 |
| Slower |  0.47 | Windows 10            | Arm64 |
| Slower |  0.42 | Windows 11            | Arm64 |
| Slower |  0.43 | Windows 10            | X86   |
| Slower |  0.48 | Windows 11            | X86   |
| Slower |  0.49 | Windows 11            | X86   |
| Slower |  0.34 | Windows 7 SP1         | X86   |
| Same   |  1.07 | ubuntu 18.04          | Arm   |
| Slower |  0.44 | Windows 10            | Arm   |
| Same   |  1.02 | macOS Monterey 12.2.1 | X64   |
| Same   |  1.05 | macOS Monterey 12.3.1 | X64   |

</details>

**Comment by stephentoub** [comment]
I believe this is expected. The previous code was simply wrong, and doing the right thing is more expensive.

**Comment by danmoseley** [comment]
Right, the new call to GetExitCodeProcess is necessary.
