### ISSUE TITLE
Help:  .Net 6 and emitting IL to call constructors and methods that have pointers as arguments

### ISSUE THREAD

**Issue by nschuessler** [dotnet/runtime#67844]
Can someone please chime in [here](https://github.com/ninject/Ninject/issues/389) to help us fix Ninject to work with .Net 6.
Note: There is a commit hash of his code changes.

@scott-xu Is trying to make a fix that emits delegates that wrap constructors and methods that have pointers as args. In addition, there is an unbox pointer scenario. (I didn't think pointers were boxed ....)

Thanks

**Comment by AaronRobinsonMSFT** [comment]
@nschuessler It would be helpful to see an example of the IL that being emitted. Additionally if you could provide an example of what is being attempted it would help understanding the problem.  Based on the title, I am assuming the general idea is the following:

```csharp
public unsafe class C
{
    public C(void* a, void* b) { }
    
    public delegate C CreateDelegate(void* a, void* b);
    public static CreateDelegate Get() { /* Create a delegate to call C.ctor */ }    
    public static void Main(string _)
    {        
        C.CreateDelegate del = C.Get();
        C c = del(null, null);
    }
}
```

**Comment by nschuessler** [comment]
So it appears  @scott-xu  closed the Ninject issue so he may not need help fixing. I was trying to connect everyone to resolve the issue.
