### ISSUE TITLE
[source build] use of undeclared identifier 'kSecUseDataProtectionKeychain'

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#67846]
### Description

build mono using `./build.sh mono+libs -c release`

### Reproduction Steps

1. install requirement: brew bundle --no-lock --file eng/Brewfile
2. build `./build.sh mono+libs -c release`

### Expected behavior

build success

### Actual behavior

make: *** [all] Error 2
  ~/Documents/github.com/runtime/src/native/libs
  Failed to build "native libraries component".
/Users/dsqiu/Documents/github.com/runtime/src/native/libs/build-native.proj(40,5): error MSB3073: 命令“"/Users/dsqiu/Documents/github.com/runtime/src/native/libs/build-native.sh" x64 Release outconfig net7.0-OSX-Release-x64 -os OSX ”已退出，代码为 2。

生成失败。

/Users/dsqiu/Documents/github.com/runtime/src/native/libs/System.Security.Cryptography.Native.Apple/pal_ecc.c(29,46): error G9FDB2457: use of undeclared identifier 'kSecUseDataProtectionKeychain' [/Users/dsqiu/Documents/github.com/runtime/src/native/libs/build-native.proj]
/Users/dsqiu/Documents/github.com/runtime/src/native/libs/build-native.proj(40,5): error MSB3073: 命令“"/Users/dsqiu/Documents/github.com/runtime/src/native/libs/build-native.sh" x64 Release outconfig net7.0-OSX-Release-x64 -os OSX ”已退出，代码为 2

### Configuration

macos Catalina 10.15.7

**Comment by srxqds** [comment]
hi, who can help me?

**Comment by akoeplinger** [comment]
I think we discussed this on Discord, closing for now.
