### ISSUE TITLE
[API Proposal]: Enable JsonEncodedText to be initialized with already encoded bytes.

### ISSUE THREAD

**Issue by olivier-spinelli** [dotnet/runtime#67850]
### Background and motivation

I'm trying to efficiently serialize/deserialize `JsonEncodedText`: I just need to write the `EncodedUtf8Bytes` and read then back as bytes, letting the constructor expanding the string. Unfortunately, the constructor that does this is private (called by the `Encode`
methods and this makes perfect sense since this ctor would be clearly ambiguous):
````c#
private JsonEncodedText(byte[] utf8Value)
{
   Debug.Assert](utf8Value != null);
   _value = JsonReaderHelper.GetTextFromUtf8(utf8Value);
   _utf8Value = utf8Value;
}
````
There is no way to implement a fake encoder to override the default encoder of the `Encode` method without going **unsafe**:

````c#
sealed class NoEncoder : JavaScriptEncoder
{
   public override int MaxOutputCharactersPerInputCharacter => 1;

   public override unsafe int FindFirstCharacterToEncode( char* text, int textLength ) => -1;

   public override unsafe bool TryEncodeUnicodeScalar( int unicodeScalar, char* buffer, int bufferLength, out int numberOfCharactersWritten )
   {
       Throw.NotSupportedException();
   }

   public override bool WillEncode( int unicodeScalar ) => false;
}
````

A simple static method with an explicit name such as the one below will be great and as safe as it can be:
````c#
public static JsonEncodedText CreateFromEncodedUtf8Bytes( ReadOnlySpan<byte> bytes!! ) => new JsonEncodedText( bytes );
````

### API Proposal

Add these 2 public static methods to the JsonEncodedText class.
````c#
public static JsonEncodedText CreateFromEncodedUtf8Bytes( ReadOnlySpan<byte> bytes ) => new JsonEncodedText( bytes.ToArray() );

public static JsonEncodedText CreateFromEncodedUtf8Bytes( byte[] bytes!! ) => new JsonEncodedText( bytes );
````

### API Usage

The first goal is to avoid serializing a string in UTF-16 (that will be encoded in UTF-8) and restore a string (that will be read as UTF-8 and encoded in UTF-16 that will need be encoded back to UTF-8!)...

Net effect: 0 vs. 1 encoding during write and 1 encoding vs. 2 during read...
(and only the required allocations since with the `CreateFromEncodedUtf8Bytes( byte[] bytes!! )` the ownership of the buffer is 
given to the JsonEncodedText.)

```c#
        /// <summary>
        /// Writes a <see cref="JsonEncodedText"/>.
        /// </summary>
        /// <param name="this">This writer.</param>
        /// <param name="t">The text.</param>
        public static void Write( this ICKBinaryWriter @this, JsonEncodedText t )
        {
            @this.WriteNonNegativeSmallInt32( t.EncodedUtf8Bytes.Length );
            @this.Write( t.EncodedUtf8Bytes );
        }

        /// <summary>
        /// Reads a <see cref="JsonEncodedText"/>.
        /// </summary>
        /// <param name="this">This reader.</param>
        /// <returns>The read text.</returns>
        public static JsonEncodedText ReadJsonEncodedText( this ICKBinaryReader @this )
        {
            int len = @this.ReadNonNegativeSmallInt32();
            return JsonEncodedText.Encode( @this.ReadBytes( len ) );
        }
```

### Alternative Designs

N/A

### Risks

None that I can imagine...

**Comment by eiriktsarpalis** [comment]
Do the [`JsonEncodedText.Encode` methods](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonencodedtext.encode?view=net-6.0) not suit your use case?

**Comment by olivier-spinelli** [comment]
The data is alreay encoded (since it's coming from a UTF-8 serialized stream/pipe). Calling Encode on it (even the one with 
`ReadOnlySpan<byte>`) will trigger a double encoding (it calls `NeedsEscaping` that has good chances to return a "yes") that will definitely destoy the data .

https://source.dot.net/#System.Text.Json/System/Text/Json/JsonEncodedText.cs,105

**Comment by eiriktsarpalis** [comment]
@olivier-spinelli I just updated my response as you were posting yours. Please see my new feedback, in particular the final paragraph.

**Comment by eiriktsarpalis** [comment]
I don't think such a scenario is within scope for this particular type. It's meant as a helper struct aiding serialization performance of System.Text.Json, but it's not itself intended for serialization/deserialization. If performance is important enough, I would recommend writing your own custom struct instead.

**Comment by olivier-spinelli** [comment]
"helper struct aiding serialization performance" can be for other kind of serializers. Another struct will not interoperate with the rest of the code/library: a conversion to/from JsonEncodedText will be needed (and since there is no way to initialize a JsonEncodedText with bot its bytes and string without conversions, this is a dead end). 

(Ooops I didn't notice you closed the issue.)
Sad. 
And for 2 poor static helpers that will be jitted leading to 0 size impacts... Is it the fact that buffer validation is skipped in such case that is annoying?

**Comment by olivier-spinelli** [comment]
Noted. Thanks for your time!
