### ISSUE TITLE
[API Proposal]: Poolable / Resettable CBOR Readers

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [dotnet/runtime#67868]
### Background and motivation

Today, `CborReader` is a "one-shot" type that must be discarded after it has finished reading the buffer it was created with. Internally the reader allocates multiple collections for bookeeping. If you are reading multiple CBOR documents in a hot loop, this can generate a lot of garbage. 

It would be desirable to be able to "reset" the `CborReader` and provide it a new buffer to reuse the resources more efficently. This would also allow readers to be pooled. It should also be noted that `CborWriter` already includes a `Reset()` API.

My real-world use case is a database that stores many small (100-300 bytes) documents using CBOR. The overhead of allocating new readers for each "row", is a key performance concern. There is also a need to be able to incrementally read [CBOR Sequences](https://datatracker.ietf.org/doc/html/[draft-ietf-cbor-sequence-02](https://datatracker.ietf.org/doc/html/draft-ietf-cbor-sequence-02)) which may consist of many concatenated CBOR documents. (Although this might need additional APIs to cope with buffer boundaries truncating CBOR documents).

@-ing prior CBOR API proposer and reviewers, apologies if this is improper.

@eiriktsarpalis @bartonjs @terrajobst 

### API Proposal [version 2]

```diff
namespace System.Formats.Cbor;

public CborReader
{
//resets reader state
+ void Reset(ReadOnlyMemory<byte> data);
}
```

### Reset
The Reset API will reset all internal state to a condition identical to calling `new CborReader(ReadOnlyMemory<byte>, ...)`, including removing any references to the previous `data` buffer. This also includes any exceptional state.

NOTE : It is explicitly **valid** to call either the existing ctor `new CborReader(ReadOnlyMemory<byte>, ...)` OR the proposed `Reset(ReadOnlyMemory<byte>)`  with an empty/default `ReadOnlyMemory<byte>`. However, any calls to  `Read*`, `Skip*` or `Peek*` APIs will fail since there is no valid CBOR document.

**Comment by bartonjs** [comment]
A much simpler variant seems to be just to add

```C#
partial class CborReader
{
    public void Reset(ReadOnlyMemory<byte> data);
}
```

And not bother letting the two options change, or ever have a state of having unassigned data.  For your described scenario it'd be

```C#
CborReader reader = null;

foreach (var record in records)
{
    if (reader is null)
    {
        reader = new CborReader(record.Cbor);
    }
    else
    {
        reader.Reset(record.Cbor);
    }

    ...
}
```

or just empty-initialize the reader, if you want to get rid of the branch.

```C#
CborReader reader = new CborReader(ReadOnlyMemory<byte>.Empty);

foreach (var record in records)
{
    reader.Reset(record.Cbor);
    ...
}
```

As-proposed, there's ambiguity.  What happens if you're in deep state and call SetBuffer?  What does Reset do without a corresponding call to SetBuffer?  And, of course, why bother tracking a state that says that there's no associated data?

**Comment by bartonjs** [comment]
Also, so far as I can tell: Congratulations on having the first feature request to the System.Formats.Cbor library :smile:

**Comment by AlgorithmsAreCool** [comment]
I should have included that in my

**Comment by AlgorithmsAreCool** [comment]
Presumably not? I'm not sure how to move an issue toward API Review. I'd be willing to implement it if the API is approved.

**Comment by AlgorithmsAreCool** [comment]
@bartonjs Looking to implement this soon-ish, what is the rough cutoff for this making it into .NET 8? Or is it already pushed out?

**Comment by bartonjs** [comment]
> what is the rough cutoff for this making it into .NET 8?

July?

> Or is it already pushed out?

The milestone is set to Future, which just means that the core team isn't working on it.  We'll take a community contribution whenever it comes :smile:
