### ISSUE TITLE
[API Proposal]: Expose method to get system message for system error code

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#67872]
### Background and motivation

This optionally (and typically) retrieves the last system error (with `Marshal.GetLastPInvokeError()`) and the matching system error string (internally using `strerror` or `FormatMessage`) for you:
```c#
throw new Win32Exception();
```
(Separate discussion of the unfortunate naming we have inherited for Win32Exception is [here](https://github.com/dotnet/runtime/issues/26227#issuecomment-747842770).)
(Also note that `Marshal.GetLastPInvokeError()` == `Marshal.GetLastWin32Error()` and is distinct to `Marshal.GetLastSystemError()` only in that the latter is oblivious to calls to `Marshal.SetLastPInvokeError()` == `Marshal.SetLastWin32Error`)

This is convenient if that's exactly what you want, but has these limitations

1. It's not discoverable, you just have to know.

2. It's easy to accidentally reset the error, eg.,
```c#
// some pinvoke
// some other code potentially resetting the last error by calling into the system directly or indirectly
throw new Win32Exception(); // uses the last error code, when perhaps you expected a generic message
```
correct way:
```c#
// some pinvoke
int errorCode = Marshal.GetLastWin32Error();
// some other code
throw new Win32Exception(errorCode);
```

3. Sometimes you just want the message, you don't want an exception. For example, you want to write to the system log, or do some tracing, like [this](https://github.com/dotnet/runtime/blob/2ef6ac1c731ce690797847135f040ef5abb29d67/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceBase.cs#L904-L905)), In this case getting the message is clumsy:
```c#
string errorMessage = new Win32Exception().Message;
WriteLogEntry(SR.Format(SR.StartFailed, errorMessage), EventLogEntryType.Error);
```
or if you want it from the error code:
```c#
string errorMessage = new Win32Exception(errorCode).Message;
WriteLogEntry(SR.Format(SR.StartFailed, errorMessage), EventLogEntryType.Error);
```

4. If you want to throw a partially custom message, you have to be even more clumsy, and it's easy to accidentally overwrite the last error.

This is not robust because some string formatting machinery runs and potentially resets the last error before Win32Exception internally calls `Marshal.GetLastPInvokeError()`:
```c#
throw new Win32Exception($"Could not open SCM. {new Win32Exception().Message}");
```
This is not robust either because Win32Exception still calls `Marshal.GetLastPInvokeError()` to set its `NativeErrorCode`. https://github.com/dotnet/runtime/pull/67827 is an example where this was wrong.
```c#
string errorMessage = new Win32Exception().Message;
throw new Win32Exception($"Could not delete service. {errorMessage}");
```
One must write this to be robust ([example in our code](https://github.com/danmoseley/runtime/blob/a431bbc76dd80cb6f960725547ad3ccb5c9cf679/src/libraries/System.Drawing.Common/src/misc/DbgUtil.cs#L57-L59))
```c#
int errorCode = Marshal.GetLastWin32Error();
string errorMessage = new Win32Exception(errorCode).Message;
throw new Win32Exception(errorCode, $"Could not delete service. {errorMessage}");
```

It's  unfortunate that Win32Exception calls `Marshal.GetLastPInvokeError()` at all but that can't change now. We can at least help address 1, 3 and 4.

### API Proposal

Proposed API implementation - https://github.com/dotnet/runtime/pull/70685

https://github.com/dotnet/runtime/pull/70685#discussion_r896213453 has commentary on proposed API UX.

```diff
namespace System.Runtime.InteropServices
{
    public class Marshal
    {
        public static int GetLastPInvokeError(); // existing
+       public static string GetPInvokeErrorMessage(int error); // Win32Exception parameter name is `error`, although its property is `NativeErrorCode`
    }
}
```

### API Usage

```C#
int errorCode = Marshal.GetLastPInvokeError(); // error is captured here
string errorMessage = Marshal.GetPInvokeErrorMessage(errorCode);
throw new Win32Exception(errorCode, $"Could not delete service. {errorMessage}");
```
or 
```C#
int errorCode = Marshal.GetLastPInvokeError(); // error is captured here
throw new Win32Exception(errorCode, $"Could not delete service. {Marshal.GetPInvokeErrorMessage(errorCode)}");
```

### Alternative Designs

It would be nice to add overloads to Win32Exception, that eg., take a message to prepend. However, that may not be a common enough requirement, and would be ambiguous with existing string overload. It would probably have to be a static factory method. You'd still need the Marshal method, in case you don't want the exception object.

Another possibility is to return message and code together as a tuple, eg
```C#
namespace System.Runtime.InteropServices
{
    public class Marshal
    {
        public static (int error, string message) GetLastPInvokeErrorMessage();
    }
}
```

**Comment by jkotas** [comment]
Nit: GetMessageforPinvokeError -> GetMessageforPInvokeError

**Comment by danmoseley** [comment]
fixed.

**Comment by stephentoub** [comment]
`GetPInvokeErrorMessage`?

**Comment by danmoseley** [comment]
That's an improvement. Updated.

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT if you're supportive, shall we mark ready for review?

**Comment by AaronRobinsonMSFT** [comment]
@danmoseley Do you want to present this to the API review board? I've put out a [PR](https://github.com/dotnet/runtime/pull/70685) as proposed above.

**Comment by danmoseley** [comment]
@stephentoub suggested it wasn't necessary for me to be there, although I can be if necessary if someone lets me know which one it will be at. If you attend perhaps you could speak to it?

**Comment by AaronRobinsonMSFT** [comment]
> If you attend perhaps you could speak to it?

Sure.

**Comment by terrajobst** [comment]
* Let's also add `GetLastPInvokeErrorMessage()`

```C#
namespace System.Runtime.InteropServices;

public partial class Marshal
{
    // Existing
    // public static int GetLastPInvokeError();
    public static string GetLastPInvokeErrorMessage();
    public static string GetPInvokeErrorMessage(int error);
}
```
