### ISSUE TITLE
HashAlgorithmTest.ComputeHashAsync_SupportsCancellation() fails to throw OperationCanceledException

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#67880]
Console log: 'System.Security.Cryptography.Tests' from job 4f51ef79-15d1-474b-abcc-36d29680439b (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673 on a00BSOC

net7.0-Linux-Debug-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673
```
    System.Security.Cryptography.Tests.HashAlgorithmTest.ComputeHashAsync_SupportsCancellation [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography/tests/HashAlgorithmTest.cs(69,0): at System.Security.Cryptography.Tests.HashAlgorithmTest.ComputeHashAsync_SupportsCancellation()
        --- End of stack trace from previous location ---
  Finished:    System.Security.Cryptography.Tests
```

This is Mono interpreter, but presumably not https://github.com/dotnet/runtime/issues/66694 because that was a hang, plus the fix would be in this build.

**Comment by bartonjs** [comment]
Kusto doesn't show any hits of failures in this test now, so it must have been something transient.
