### ISSUE TITLE
Ability to define the System.Text.Json attributes on implemented interfaces

### ISSUE THREAD

**Issue by vova-lantsov-dev** [dotnet/runtime#67892]
### Description

Sometimes, in source generator scenarios, you need to add the STJ metadata to existing classes. There is no `partial property` feature yet, so the only way is to generate an interface that will be implemented by a target class.

What I suggest is an attribute that can be specified for a target class, like this:
```c#
// Somewhere exists an original class Model
// All code below is expected to be autogenerated by src gen

[JsonSerializable(MetadataMode = JsonMetadataMode.Interfaces)]
partial class Model : IAutoGeneratedModel
{
}

public interface IAutoGeneratedModel
{
	// Properties here with STJ attributes
}
```

Naming could be another, but the most important is behaviour.

### Reproduction Steps

```c#
public class Model : IModel
{
	public string? FirstValue { get; set; }
	public string? SecondValue { get; set; }
}

public interface IModel
{
	[JsonPropertyName("first_value"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
	string? FirstValue { get; }
	
	[JsonPropertyName("second_value")]
	string? SecondValue { get; }
}
```

And program:
```c#
using System;
using System.Text.Json;
using ConsoleApp1;

var model = new Model
{
	FirstValue = null,
	SecondValue = "test"
};

string json = JsonSerializer.Serialize(model, new JsonSerializerOptions
{
	WriteIndented = true
});

Console.WriteLine(json);
```

### Expected behavior

Program output is
```json
{
	"second_value": "test"
}
```

### Actual behavior

Program output is
```json
{
	"FirstValue": null,
	"SecondValue": "test"
}
```

### Known Workarounds

Implementation of a custom converter for each target class.

**Comment by eiriktsarpalis** [comment]
This is by design, contracts of implemented interfaces should have no impact on the contract of the implementing class (since one class could be implementing multiple interfaces or might be implementing it explicitly). You should still be able to get the expected behavior if you cast the model to the interface type ahead of serialization:
```C#
 JsonSerializer.Serialize<IModel>(model);
```

**Comment by eiriktsarpalis** [comment]
Doing that requires polymorphism support. We have a feature in the works (see https://github.com/dotnet/runtime/issues/63747) but it might not work in the way that Json.NET handles it.
