### ISSUE TITLE
Crash of our NetCore 6 Application

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#67897]
### Description

Our Application crashed with a internal NetCore Runtime error

![image](https://user-images.githubusercontent.com/364896/162928637-64e19ae1-c31c-4c15-a776-6faf2e05dff6.png)

Name der fehlerhaften Anwendung: MCC.Common.Services.NTServiceHost.exe, Version: 6.0.0.0, Zeitstempel: 0x61954b73
Name des fehlerhaften Moduls: coreclr.dll, Version: 6.0.121.56705, Zeitstempel: 0x619543a3
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00000000001cd61b
ID des fehlerhaften Prozesses: 0x1c78
Startzeit der fehlerhaften Anwendung: 0x01d84e3c0e051071
Pfad der fehlerhaften Anwendung: C:\mlog\mcc\application\service\MCC.Common.Services.NTServiceHost.exe
Pfad des fehlerhaften Moduls: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.1\coreclr.dll
Berichtskennung: 5c858fbe-c4c0-413f-b4d9-764bff36c45e
Vollständiger Name des fehlerhaften Pakets:
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

![image](https://user-images.githubusercontent.com/364896/162928688-e0132782-fc35-44b7-858c-3ca5152c166a.png)

Application: MCC.Common.Services.NTServiceHost.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFED781D61B (00007FFED7650000) with exit code c0000005.

### Reproduction Steps

- no idee how, it did not crash every time. Only once after a few hours

### Expected behavior

Application Should not crash

### Actual behavior

Application crashes

**Comment by danmoseley** [comment]
Hello. Are you able to get a crash dump?

**Comment by MagicAndre1981** [comment]
look if update to 6.0.4 from todays patchday helps

**Comment by danmoseley** [comment]
Saying a little more -- a crash in a .NET app is usually not caused by the runtime, but instead by unsafe code or incorrect pinvoke signatures.
Did this start crashing after a .NET update? Did it eg only crash on 6.0 but not 5.0?
If you can get a native callstack, it might suggest whether the bug is .NET or not. But the info above is not enough to tell us.

**Comment by jogibear9988** [comment]
In Net4.8 we also sometimes had crashes cause of a error on our side with a Unmanged DLL import, but then we saw in the stacktrace where the crash came from. But also we deliverd a debug build when we used FullFramework.

Problem is, there software runs for days (it's a Warehousmanagement System), and this was the first crash, and I could not reproduce. I now enabled MemoryDumps, so hopefully if it crashes again it will be caught.

Would a debug build help, our would I not see more in the stack?

**Comment by jogibear9988** [comment]
We had the same crash again: 
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/364896/167788504-c9b70194-c278-41a6-8cf4-8bfe8cca24c0.png">

**Comment by jogibear9988** [comment]
I enabled crash dumps in windows registry, is a restart of the computer required to enable them?

**Comment by seayxu** [comment]
same problem
.NET Runtime 6.0.3 to 6.0.5,still exist.
![image](https://user-images.githubusercontent.com/11575055/171106991-f35ad08c-29da-43be-af49-178ee1ab9f31.png)

**Comment by MagicAndre1981** [comment]
also enable crash dumps with [procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump)

`procdump -ma -i c:\dumps`

and analyze them in Windbg (`!analyze -v`)

**Comment by jogibear9988** [comment]
on our system we found the error.
It was in a call to a unmanged dll with a old pointer.
