### ISSUE TITLE
System.Tests.Perf_Enum.EnumToString has regressed across multiple configurations

### ISSUE THREAD

**Issue by dakersnar** [dotnet/runtime#67909]
System.Tests.Perf_Enum.EnumToString has regressed across multiple configurations.

[Reporting System](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Tests.Perf_Enum.EnumToString(value%3a%20Yellow).html):

![image](https://user-images.githubusercontent.com/18474647/163002203-ef08453e-f6a3-415d-bd48-0066c9942568.png)

Looking at the [commit diff](https://github.com/dotnet/runtime/compare/a883caa0803778084167b978281c34db8e753246...c251dbb17b76b23248d25ecca7aa99c3c280dcdc), I'm unsure which commit is the culprit. 

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_monthly.py net7.0-preview2 net7.0-preview3 --filter System.Tests.Perf_Enum.EnumToString
```

<details>

## System.Tests.Perf_Enum.EnumToString(value: Yellow)

| Result |   Base |   Diff | Ratio | Operating System      | Bit   | Processor Name                                  |
| ------ | ------:| ------:| -----:| --------------------- | ----- | ----------------------------------------------- |
| Slower |  19.02 |  25.06 |  0.76 | Windows 10            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower |  17.39 |  19.55 |  0.89 | Windows 11            | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Same   |  11.85 |  13.29 |  0.89 | Windows 11            | X64   | AMD Ryzen 9 5900X                               |
| Slower |  26.54 |  38.95 |  0.68 | Windows 11            | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       |
| Slower |  23.61 |  37.50 |  0.63 | Windows 11            | X64   | Unknown processor                               |
| Slower |  15.61 |  20.20 |  0.77 | Windows 11            | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower |  18.13 |  21.90 |  0.83 | Windows 11            | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Slower |  21.15 |  27.97 |  0.76 | alpine 3.13           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  49.60 |  60.88 |  0.81 | centos 7              | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| Slower |  20.38 |  30.46 |  0.67 | debian 11             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  23.27 |  27.38 |  0.85 | ubuntu 18.04          | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  42.34 |  45.87 |  0.92 | ubuntu 18.04          | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Slower |  40.54 |  51.65 |  0.78 | ubuntu 20.04          | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   |
| Slower | 100.92 | 114.31 |  0.88 | alpine 3.12           | Arm64 | Unknown processor                               |
| Slower |  88.67 |  99.50 |  0.89 | ubuntu 18.04          | Arm64 | Unknown processor                               |
| Slower |  30.24 |  36.73 |  0.82 | Windows 10            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower |  28.65 |  38.23 |  0.75 | Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Same   |  21.40 |  21.92 |  0.98 | Windows 10            | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  18.00 |  17.89 |  1.01 | Windows 11            | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Same   |  43.11 |  39.70 |  1.09 | Windows 11            | X86   | Intel Core i7-10510U CPU 1.80GHz                |
| Same   |  16.86 |  18.11 |  0.93 | Windows 7 SP1         | X86   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Faster | 138.11 | 120.13 |  1.15 | ubuntu 18.04          | Arm   | ARMv7 Processor rev 3 (v7l)                     |
| Same   |  39.61 |  36.82 |  1.08 | Windows 10            | Arm   | Microsoft SQ1 3.0 GHz                           |
| Same   |  37.40 |  36.36 |  1.03 | macOS Monterey 12.2.1 | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |
| Slower |  33.04 |  37.34 |  0.88 | macOS Monterey 12.3.1 | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      |

</details>

**Comment by mrsharm** [comment]
Closing as this regression was fixed:

![image](https://user-images.githubusercontent.com/68247673/182445595-0b98e5f8-9d76-43a0-aaa1-b82e196ae191.png)

We are below the level of when segments were enabled.
