### ISSUE TITLE
Offer a ToString(Byte* buffer) overload  for all types.

### ISSUE THREAD

**Issue by OnurGumus** [dotnet/runtime#6792]
Currently when you make string operations with integral types, there happens to be a tostring call and a new string allocation. For example:
`string.Join(",",array_with_million_doubles);`

Above code will call .ToString for each double value then will join it. But instead we could do something better like sprintf, where the string conversion can happen on the buffer directly. My own benchmarks showed 20% better performance for this case.

**Comment by GrabYourPitchforks** [comment]
Is there anything left to do here? Seems like this can be closed?

**Comment by OnurGumus** [comment]
@GrabYourPitchforks is this implemented?

**Comment by OnurGumus** [comment]
On the second thought, this could be achieved by string.create

**Comment by Joe4evr** [comment]
I sincerely doubt this suggestion is *ever* going to be implemented as proposed, for the sheer fact that allowing any type to write to an unbounded `byte*` is quite possibly the worst thing that could ever be done to the .NET ecosystem.

**Comment by OnurGumus** [comment]
@Joe4evr this was how it is implemented back in 2016. It was some C++ code that does was converting numbers to a string by getting a byte*.

Now check it again the implementation has completely changed. It's using a span as the input or using rented buffers which is good enough already.

https://source.dot.net/#System.Private.CoreLib/ValueStringBuilder.cs,157e1a7ce4de87da

So I think the above problem can be solved with

   public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format = default, IFormatProvider? provider = null)

which exists in types like Double. Back then there were no Span.
