### ISSUE TITLE
Vectorize the new {Last}IndexOfAnyExcept methods

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#67942]
Simple implementations were added in https://github.com/dotnet/runtime/pull/67941.  These should be vectorized, ideally sharing as much implementation as possible with {Last}IndexOf{Any}.

**Comment by EgorBo** [comment]
Can help anyone who decides to try it

**Comment by stephentoub** [comment]
@GrabYourPitchforks suggested we could possibly share the bulk of the IndexOf{Any} implementations, using a generic type parameter ala https://github.com/dotnet/runtime/blob/4017327955f1d8ddc43980eb1848c52fbb131dfc/src/libraries/System.Private.CoreLib/src/System/Globalization/TextInfo.cs#L206-L209 to control whether we're including or excluding the specified values.

But I expect we should wait to attempt that until it's been converted over to Vector128/256, so maybe we should put something simple in place, maybe just for 1-3 chars, maybe just a single vectorized path (with `Vector<T>` or `Vector128<T>`) until the IndexOf{Any} code has stabilized.
