### ISSUE TITLE
[release/5.0] SSL and authentication failures affecting branch CI

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67947]
@dotnet/ncl @rzikm @wfurt @karelz Similar to release/6.0, there are many SSL and authentication-related failures in the 5.0 branch. Example:

- PR: https://github.com/dotnet/runtime/pull/67927
- Pipeline results: https://dev.azure.com/dnceng/public/_build/results?buildId=1713318&view=results
- Jobs: https://dev.azure.com/dnceng/public/_build/results?buildId=1713318&view=logs&j=85312bf4-08bc-52d1-d0fc-b5f2255cc3aa&t=256f7d9c-37df-5104-5658-4549f551bdd3&l=105

Examples of logs with failures:
- System.Net.Http.Functional.Tests: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67927-merge-b0888e8227ae40e7a4/System.Net.Http.Functional.Tests/1/console.e9f53fea.log?sv=2019-07-07&se=2022-05-02T20%3A19%3A28Z&sr=c&sp=rl&sig=ug%2ByHZF7uzk%2BmcwcrNfiC%2BMoocVR%2BWCUCCMQEWj87T4%3D
- System.Net.Http.WinHttpHandler.Functional.Tests https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67927-merge-b0888e8227ae40e7a4/System.Net.Http.WinHttpHandler.Functional.Tests/1/console.f13c32cf.log?sv=2019-07-07&se=2022-05-02T20%3A19%3A28Z&sr=c&sp=rl&sig=ug%2ByHZF7uzk%2BmcwcrNfiC%2BMoocVR%2BWCUCCMQEWj87T4%3D
- System.Net.Security.Tests https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-67927-merge-b0888e8227ae40e7a4/System.Net.Security.Tests/1/console.c65a6a42.log?sv=2019-07-07&se=2022-05-02T20%3A19%3A28Z&sr=c&sp=rl&sig=ug%2ByHZF7uzk%2BmcwcrNfiC%2BMoocVR%2BWCUCCMQEWj87T4%3D

**Comment by danmoseley** [comment]
Out of support.
