### ISSUE TITLE
consider presenting IPv4-Mapped addresses as IPv4

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#67952]
This is somewhat related to  #67879 but it is more general. In #67879 the local and remote address can be presented either as `127.0.0.1` or as `[::ffff:127.0.0.1]` while connecting to identical host.

While sematintially same, the former seems easier to read and process. 
Since .NET's promise is simplification and ease of use, we may consider hiding the trickery of underlying `Socket` type and we may present either IPv4 or IPv6 simple address as appropriate. 

This may possibly be scoped to #63162. (or other subset)

**Comment by karelz** [comment]
Triage: There is value in having information that IPv6 was used as it sometimes causes different problems that straight IPv4.
We are ok considering it as part of the new TCP API, though we might not want it as part of `ToString` even there.
