### ISSUE TITLE
Async File IO has regressed on Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67965]
Various **async** file IO micro benchmarks have regressed on Windows, but `System.IO.Tests.Perf_RandomAccess.ReadScatterAsync(fileSize: 104857600, buffersSize: 65536, options: Asynchronous)` is the one for which its most obvious (other benchmarks are more noisy):

[Reporting System](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.IO.Tests.Perf_RandomAccess.ReadScatterAsync(fileSize%3a%20104857600%2c%20buffersSize%3a%2065536%2c%20options%3a%20Asynchronous).html):

![image](https://user-images.githubusercontent.com/6011991/163229895-5a8659f5-9863-4396-a2b8-d778196f1248.png)

Looking at the [commit diff](https://github.com/dotnet/runtime/compare/6dcefe002035fa19c3288d54d8d10f6533cb94fc...8d418afe1bfd84edb227eaf170a077d667e468e3), #64834 seems to be to blame (cc @kouvel).

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_monthly.py net7.0-preview2 net7.0-preview3 --filter System.IO.Tests.Perf_RandomAccess.ReadScatterAsync 
```

<details>
## System.IO.Tests.Perf_RandomAccess.ReadScatterAsync(fileSize: 104857600, buffersSize: 65536, options: Asynchronous)

| Result |         Base |         Diff | Ratio | Operating System      | Bit   | Processor Name                                  |
| ------ | ------------:| ------------:| -----:| --------------------- | ----- | ----------------------------------------------- |
| Same   |  37590691.92 |  35916562.67 |  1.05 | alpine 3.12           | Arm64 | Unknown processor                               |
| Same   |  35082625.33 |  34730510.50 |  1.01 | ubuntu 18.04          | Arm64 | Unknown processor                               |
| Same   | 177006300.00 | 186064200.00 |  0.95 | Windows 10            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower | 245370200.00 | 274912400.00 |  0.89 | Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Same   |   8429207.03 |   8253338.53 |  1.02 | macOS Monterey 12.3   | Arm64 | Apple M1 Max                                    |
| Same   |  95101450.00 | 103159400.00 |  0.92 | Windows 10            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower |  82646762.50 | 100602725.00 |  0.82 | Windows 11            | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Same   |  72943362.50 |  80936137.50 |  0.90 | Windows 11            | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower |  70063175.00 |  85975425.00 |  0.81 | Windows 11            | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Slower |  10059315.79 |  11916405.00 |  0.84 | alpine 3.13           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  26718361.11 |  25572313.94 |  1.04 | centos 7              | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| Same   |   9761970.00 |  10212622.22 |  0.96 | debian 11             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |   9915697.50 |  10113311.76 |  0.98 | opensuse-leap 15.3    | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  13491174.81 |  13389165.63 |  1.01 | ubuntu 18.04          | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  17370649.54 |  16005520.13 |  1.09 | ubuntu 18.04          | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Slower | 180336900.00 | 209815000.00 |  0.86 | Windows 10            | Arm   | Microsoft SQ1 3.0 GHz                           |
| Same   | 194855158.00 | 199422552.00 |  0.98 | ubuntu 18.04          | Arm   | ARMv7 Processor rev 3 (v7l)                     |
| Same   |  95764800.00 | 103428275.00 |  0.93 | Windows 10            | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  92642500.00 | 100944225.00 |  0.92 | Windows 11            | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Faster | 332525100.00 | 184955950.00 |  1.80 | Windows 11            | X86   | Intel Core i7-10510U CPU 1.80GHz                |
| Faster | 277613675.00 | 187145750.00 |  1.48 | Windows 7 SP1         | X86   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  18966713.69 |  18777427.62 |  1.01 | macOS Monterey 12.2.1 | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |
| Same   |  16605661.57 |  17217161.62 |  0.96 | macOS Monterey 12.3.1 | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      |
</details>

**Comment by kouvel** [comment]
There's a tradeoff in https://github.com/dotnet/runtime/pull/64834 from using IO poller threads and then reusing the worker thread pool for processing completions, which seems to be showing up in some of these benchmarks. The thread pool is also mostly idle, and the path lengths are also a bit higher. There are other advantages with that model so it's probably a good tradeoff for now. Needs investigation to see if there are better ways of polling for IO to get both advantages.

**Comment by mangod9** [comment]
is this still something that needs to be investigated or can be closed based on fix in https://github.com/dotnet/runtime/issues/66465 ?

**Comment by adamsitnik** [comment]
> is this still something that needs to be investigated or can be closed based on fix in https://github.com/dotnet/runtime/issues/66465

#66465 was closed as a duplicate of this issue: https://github.com/dotnet/runtime/issues/66465#issuecomment-1208327956, there was no fix. IMO we should keep it open so @kouvel can at least spend some time and see if it's possible to close the perf gap.

**Comment by kouvel** [comment]
I don't think there's a way to close the perf gap with the current IO polling strategy. I'll go ahead and close this issue for now, as the gap is understood and effectively by-design, and any improvement to the IO polling strategy would be done as a new feature after reevaluating the tradeoffs with that.
