### ISSUE TITLE
[API Proposal]: Add RuntimeFeature field to identify support for numeric IntPtr type

### ISSUE THREAD

**Issue by jcouv** [dotnet/runtime#67966]
### Background and motivation

As part of the [statics in interfaces and numerics work](https://github.com/dotnet/designs/blob/main/accepted/2021/statics-in-interfaces/README.md), the `IntPtr` and `UIntPtr` types are going to be expanded and become numeric types.
This API request is to help Roslyn recognize platforms where it should treat `nint`/`nuint` as aliases for `IntPtr`/`UIntPtr` ([tracking feature](https://github.com/dotnet/roslyn/issues/60578)).

### API Proposal

```diff
namespace System.Runtime.CompilerServices
{
    public static partial class RuntimeFeature
    {
+        /// <summary>
+        /// The presence of this field indicates a runtime where `System.IntPtr`/`System.UIntPtr` are numeric types.
+        /// </summary>
+        public const string NumericIntPtr = nameof(NumericIntPtr);
    }
}
```

### API Usage

Used by Roslyn to detect if a runtime supports numeric `IntPtr`/`UIntPtr` types.

### Alternative Designs

A conceivable alternative would be to look at some API markers on the `IntPtr` type (for example, does it implement a given numeric interface).
But a runtime feature flag is the preferred/typical way to indicate a feature to Roslyn.

In terms of names, some other options are `UnifiedIntPtr` or `PrimitiveIntPtr`.

### Risks

None

**Comment by jcouv** [comment]
FYI @tannergooding @terrajobst @AlekseyTs @cston

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Runtime.CompilerServices;

public static partial class RuntimeFeature
{
    public const string NumericIntPtr = nameof(NumericIntPtr);
}
```

**Comment by deeprobin** [comment]
If it's just this constant and no JIT or VM changes are needed, feel free to assign me.

**Comment by tannergooding** [comment]
This is likely going to be done by the compiler team around the same time they are ready to consume the feature.

We tend to not want to check these changes in early on the off chance the language feature isn't able to make the same release
