### ISSUE TITLE
Build doesn't fail if a MONO_API_FUNCTION isn't implemented

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#67985]
While working on https://github.com/dotnet/runtime/pull/67984 I noticed that `mono_config_cleanup` was not implemented even though we have it marked as a `MONO_API_FUNCTION` in the public API, technically breaking our API compat.

We should find a way to validate and cause a build break if a public API isn't implemented.

/cc @lambdageek

**Comment by lambdageek** [comment]
The header are now preprocessor friendly, so we could do something like

```c
void
check_symbols(void)
{
#define MONO_API_FUNCTION(ret,name,params) g_assertf ((void*)&name, "Expected symbol " #name " to be defined");
#include <all/details/functions.h>
#undef MONO_API_FUNCTION
}


int main(void)
{
   check_symbols();
   return 0;
}
```

and then statically link that to libmono and run it.
```
