### ISSUE TITLE
[API Proposal]:  Create PFX file (PKCS#12) from .cer  .key and password.

### ISSUE THREAD

**Issue by mendozagit** [dotnet/runtime#67987]
### Background and motivation

The idea is quite simple.

Create a .PFX file `(PKCS#12)` in a simple way. 

I don't know if it currently exists in .Net, but I have been researching this for weeks and have not been able to create a PFX from the .cer file `X509Certificate2` and the private key .key `(PKCS8).`

Currently, what I do is to use OpenSSL.

1- Create a .PEM certifícate from .cer file  
`command:  openssl x509 -inform DER -in cer.cer -out outCer.pem `

2- Create a .PEM privateKey from .key file
 `command:  openssl  pkcs8 -inform DER -in key.key -passin pass:MyPassPhrase  -out outKey.pem`

3- Create a .PFX file from cer.pem and key.pem 
`command: openssl pkcs12 -export -out MyPfx.Pfx -inkey outKey.pem -in outCer.pem -passout pass:MyPassPhrase`

I have done a lot of research, but unfortunately I have been unsuccessful, 
I was wondering what is the best way to get a .PFX file generated from .Cer, .Key and password from the private key??

I have tried replicating the OpenSsl steps from c# but have been unsuccessful.
That is: From C#

Step 1- Create a .PEM certifícate from .cer file (cer.pem)
Step 2- Create a .PEM privateKey from .key file (key.pem)
Step 3- Create a .PFX file from cer.pem and key.pem

I have tried this

```csharp
// step1 
var cerPath = @"C:\Users\JESUSMENDOZA\Desktop\cer.cer";
var cerBytes = File.ReadAllBytes(cerPath);
var cerPemChars = PemEncoding.Write("CERTIFICATE", cerBytes);
var cerPem = new string(cerPemChars);
File.WriteAllText("cer.pem", cerPem);
           
// step2
var keyPath = @"C:\Users\JESUSMENDOZA\Desktop\key.key";
var keyBytes = File.ReadAllBytes(keyPath);
var keyPemChars = PemEncoding.Write("PRIVATE KEY", keyBytes);
var keyPem = new string(keyPemChars);
File.WriteAllText("key.pem", keyPem);
           
// step3
how can I create a PFX from PEM files?
In the case that stages one and two are correct, how can I create a PFX with the pem files?
```

### API Proposal

```C#
namespace System.Security.Cryptography.X509Certificates
{
     public class X509Certificate2 : X509Certificate
    {
        /// All members...
        
        
        //new 
        public void ReadPrivateKey(){
        //some implementation
       }
       public void ReadPrivateKeyBytes(){
        //some implementation
       }
       
       //new 
       public void ExportToPFX(){
        //some implementation
       }
       
    }
}
```

  

### API Usage

```C#
X509Certificate2 cert;
cert= new X509Certificat...


cert.ReadPrivateKey (pathPrivateKeyFile.key)
//or
var  privateKeyPath = @"C:\Users\JESUSMENDOZA\Desktop\key.key";
var privateKeyBytes= File.ReadAllBytes(keyPath);
cert.ReadPrivateKey (privateKeyBytes)

//Then . . .
var pfxBytes= cert.ExportToPfx;

```

**Comment by vcsjones** [comment]
> Create a .PFX file (PKCS#12) in a simple way.

In general you could do this with the `X509Certificate2` class. Something like this:

```C#
using System;
using System.IO;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

using (X509Certificate2 cert = new X509Certificate2("/path/to/your/cert.cer"))
{
    using (RSA key = RSA.Create())
    {
        key.ImportPkcs8PrivateKey(File.ReadAllBytes("/path/to/your/rsa/key.key"), out _);

        using (X509Certificate2 certWithKey = cert.CopyWithPrivateKey(key))
        {
            byte[] pkcs12 = certWithKey.Export(X509ContentType.Pfx, "yourPfxPassword");
        }
    }
}
```

If you're using an ECDSA key, then replace `RSA` with `ECDSA`.

If you get an error on `key.ImportPkcs8PrivateKey`, then your key is probably not a PKCS#8 formatted key, and instead use one of the appropriate APIs to import depending on the format of the key on disk.

**Comment by mendozagit** [comment]
Thanks for your guidelines,

verifying, these ,methods that you share with me, are new APis, which are included in .NET 5+  
I was wondering if there are plans to bring those new APis for Net standard 2.0?

**Comment by vcsjones** [comment]
> I was wondering if there are plans to bring those new APis for Net standard 2.0?

I don't believe there are. Adding new APIs to an existing .NET Standard is something that is possible, as far as I am aware, nor are there any plans to bring these APIs to a .NET Standard compatible NuGet package.

> included in .NET 5+

I believe everything there should be in .NET Core 3.1, and .NET 5+.

**Comment by mendozagit** [comment]
Thanks for your time and feedback 😃

**Comment by bartonjs** [comment]
> I was wondering if there are plans to bring those new APis for Net standard 2.0?

For types that are "in" .NET Standard (vs "on" .NET Standard), there's no possible way to update them.  Libraries compiled against .NET Standard 2.0 are supposed to work on .NET Framework 4.6.2.  Since these methods weren't in NET462, and we can't go back in time to add them, we can't add them to .NET Standard 2.0 without breaking that guarantee... which defeats the purpose of a versioned standard :smile:.

**Comment by mendozagit** [comment]
Thanks for yours feedback guys!
