### ISSUE TITLE
`dotnet-pgo create-mibc` emits warnings for being unable to find dynamic assemblies

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#68000]
### Description

The `create-mibc` command is *very* noisy when it comes to dynamic assemblies that are included in the trace. Can we tone it down?

### Reproduction Steps

dotnet-pgo create-mibc -t C:\temp\trace37196.nettrace -o c:\temp\trace37196.mibc

### Expected behavior

No warnings from being unable to find dynamic assemblies which never were nor will be on disk.

### Actual behavior

Many warnings emitted about being unable to load dynamic assemblies and their types:

> Creating ETLX file C:\temp\trace37196.etlx from C:\temp\trace37196.nettrace
Warning: Failed to load assembly 'localrpcproxies_2be2a03f-f4a1-492c-85a7-50227a9b2f50' from 'localRpcProxies_2be2a03f-f4a1-492c-85a7-50227a9b2f50'
Warning: Unable to parse instance void  _localproxy_Microsoft.ServiceHub.Framework.Services.IAuthorizationService_9e4ab5aa-1df8-4f8c-a5db-e226aebcbba8.add_AuthorizationChanged(class System.EventHandler)

**Comment by EgorBo** [comment]
That is a bit unfortunate that we can't do anything for dynamically emitted assemblies 😞

**Comment by AndyAyersMS** [comment]
cc @davidwrighton
