### ISSUE TITLE
Regex.Replace("X", ".*", "x$0y") = "xXyxy" wrong

### ISSUE THREAD

**Issue by PlanetEarthSoftware** [dotnet/runtime#68012]
### Description

There is a fault in the Regex engine when replacing the entire string with a $0 substitution:
```c#
   Regex.Replace("a", ".*", "x$0y") = "xayxy"
```

### Reproduction Steps

```string result = Regex.Replace("X", ".*", "x$0y");```

### Expected behavior

"xXy"

### Actual behavior

"xXyxy"

### Regression?

Unknown

### Known Workarounds

A workaround is to place a ^ in front of the regex, e.g. "^.*"

### Configuration

- 6.0.1
- Windows 10
- x64
- not specific to configuration

**Comment by stephentoub** [comment]
This isn't a bug. The pattern .* has _two_ matches in the string "X", one at index 0 for the string "X" and one at index 1 for the empty string.

**Comment by PlanetEarthSoftware** [comment]
No, that is your implementation, surely the first replacement has got to
the end of the string and ends the replacement process?

**Comment by stephentoub** [comment]
". *" matches the empty string, so after matching the X, it goes back, sees a remaining empty string, and matches that. This is how every major regex engine works. Try regex101.com. You'll see this produces two matches for Java, Go, JavaScript, Python,. NET, etc.
