### ISSUE TITLE
[API Proposal]: Support uint for System.Diagnostics.Metrics instruments

### ISSUE THREAD

**Issue by soroshsabz** [dotnet/runtime#68021]
### Background and motivation

ITNOA

Many of metrics in our apps needs to report some counter and gauge, that start from zero and negative value is meaningless for this metrics.

So I think it is good to have `uint` metrics

### API Proposal

```C#
// Must be valid
Counter<uint> NonNegativeCounter;
ObservableCounter<uint> NonNegativeObservableCounter;
ObservableGauge<uint> NonNegativeObservableGauge;
```

### API Usage

```C#
// Below code does not have any exception
meter.CreateCounter<uint>("foo");
```

**Comment by soroshsabz** [comment]
\dotnet/area-system-diagnostics-tracesource

**Comment by soroshsabz** [comment]
@noahfalk

**Comment by tommcdon** [comment]
@tarekgh @noahfalk

**Comment by tarekgh** [comment]
@soroshsabz we need to understand why using `int` in your scenario is not enough? Another comment I got from @reyang saying `negatives are allowed/used to mark the roundtrip, is a critical feature in many metrics backends`.

**Comment by reyang** [comment]
@soroshsabz would you give some concrete use case, and what do you expect from the *output* (result)? I do see some occasional asks but the requirements seem to be vague.

1. If the ask is about convenience? - e.g. "I have an uint literal 123U and it's inconvenient for me to cast it to int"
2. If the ask is about the actual data range in the input? - e.g. "I want to use counter.Add(2147483649U)" - this seems to indicate a flaw in the usage since the data is very likely to be broken due to the roundtrip behavior, the fact that each addition can take a such large input is already indicating that something like long or double should be used.
3. If the ask is about the actual data range in the output? - e.g. "I have an unsigned int gauge, the fact that negative integers are not being used at all is like a waste of storage to me" - there are existing backends which don't work well with unsigned long, any value in (Long.MaxValue, ULong.MaxValue] are likely to be either converted to double or handled incorrectly.

**Comment by soroshsabz** [comment]
> @soroshsabz we need to understand why using `int` in your scenario is not enough? Another comment I got from @reyang saying `negatives are allowed/used to mark the roundtrip, is a critical feature in many metrics backends`.
> 
> CC @noahfalk

@tarekgh in scenario that negative value is not valid in our domain, Counter with `int` or UpDown with `int` is miss modeled domain and error prone. boundaries in Domain modeling is important, and many item in metrics have non-negative boundaries.

> @soroshsabz would you give some concrete use case, and what do you expect from the _output_ (result)? I do see some occasional asks but the requirements seem to be vague.
> 
> 1. If the ask is about convenience? - e.g. "I have an uint literal 123U and it's inconvenient for me to cast it to int"
> 2. If the ask is about the actual data range in the input? - e.g. "I want to use counter.Add(2147483649U)" - this seems to indicate a flaw in the usage since the data is very likely to be broken due to the roundtrip behavior, the fact that each addition can take a such large input is already indicating that something like long or double should be used.
> 3. If the ask is about the actual data range in the output? - e.g. "I have an unsigned int gauge, the fact that negative integers are not being used at all is like a waste of storage to me" - there are existing backends which don't work well with unsigned long, any value in (Long.MaxValue, ULong.MaxValue] are likely to be either converted to double or handled incorrectly.

@reyang I think all three scenario is correct and useful, and correct problem modeling is very important in software engineering, that not mention explicitly in your comment.

**I have a gauge that I want to can enforce programmatically take only non negative value and range of it, is just fit to `uint`**

**Comment by tarekgh** [comment]
@soroshsabz could you please tell more information here? What is exactly the gauge you are going to use and what values are reported with this gauge? How can the users of the gauge miss with it by sending negative values?

**Comment by reyang** [comment]
> @soroshsabz could you please tell more information here? What is exactly the gauge you are going to use and what values are reported with this gauge? How can the users of the gauge miss with it by sending negative values?

And if it's an `ObservableCounter<ulong>` or `ObservableGauge<ulong>` while the resulting value (sum or last value aggregation) is greater than `9223372036854775807`, what do you expect to see from the backend?

**Comment by noahfalk** [comment]
I'm fine leaving the issue open to see if there is more demand for something like this in the future, but until there is I'd suggest solving it by having .NET apps/libraries that want this enforcement wrap the signed instruments with a facade that restricts input to non-negative values, perhaps like the example below. 

```C#
   public static class MeterExtensions
   {
       public UIntCounter CreateUIntCounter(this Meter meter, string name, string? unit, string? description)
       {
           return new UIntCounter(meter.CreateCounter<long>(name, unit, description));
       }
   }

    public sealed struct UIntCounter 
    {
        Counter<long> _counter;
        internal UIntCounter(Counter<long> counter)
        {
           _counter = counter;
        }
        public void Add(uint delta) => _counter.Add(delta);
        public void Add(uint delta, KeyValuePair<string, object?> tag) => _counter.Add(delta, tag);
        public void Add(uint delta, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2) => _counter.Add(uint delta, tag1, tag2);
        public void Add(uint delta, KeyValuePair<string, object?> tag1, KeyValuePair<string, object?> tag2, KeyValuePair<string, object?> tag3) => _counter.Add(delta, tag1, tag2, tag3);
        // there are a few other overloads if you want them
    }
```

**Comment by soroshsabz** [comment]
> @soroshsabz could you please tell more information here? What is exactly the gauge you are going to use and what values are reported with this gauge? How can the users of the gauge miss with it by sending negative values?

@tarekgh Sorry for delay,

For example in one of my projects, I have a gauge that represents `concurrent calls` (my project in Telephony domain), in this area negative value meaningless totally. but our developer's cannot model this in our code, because we have to write `ObservableGauge<int>`

> > @soroshsabz could you please tell more information here? What is exactly the gauge you are going to use and what values are reported with this gauge? How can the users of the gauge miss with it by sending negative values?
> 
> And if it's an `ObservableCounter<ulong>` or `ObservableGauge<ulong>` while the resulting value (sum or last value aggregation) is greater than `9223372036854775807`, what do you expect to see from the backend?

@reyang I do not have active scenario for `ulong` in my real projects, (I have many examples for `uint`), and I think `uint` in this time is enough, but I think if `long` is meaningful, so `ulong` is meaningful too. (and I think your consideration is same for `ulong` and `long` is two cases backend must be wrap around those. but as you can know,  in near area `Counter64 in MIB` normally used when developers of the system, is highly expected value is not greater than upper bound and even using `Counter64` to prevent wrap a rounding.

thanks

**Comment by tarekgh** [comment]
@soroshsabz thanks for your reply. 

Looks like you are concerned about the programming errors when using the ObservableGauge more than real metrics functionality. Considering the concern mentioned in the comment https://github.com/dotnet/runtime/issues/68021#issuecomment-1100226030 and there is a simple workaround mentioned by @noahfalk https://github.com/dotnet/runtime/issues/68021#issuecomment-1100812207, we prefer not to support the unsigned types for now. We may reconsider that if we see more demand to support it. 

Here is a more specific simple code provided by @noahfalk you can use in your specific case. 

```C#
    public struct UIntObservableGauge
    {
        private ObservableGauge<long>? _gauge;

        internal UIntObservableGauge(Meter m, string name, Func<uint> observeValue)
        {
            _gauge = m.CreateObservableGauge<long>(name, () => (long)observeValue());
        }
        internal UIntObservableGauge(Meter m, string name, Func<Measurement<uint>> observeValue)
        {
            _gauge = m.CreateObservableGauge<long>(name, () => ToLong(observeValue()));
        }
        internal UIntObservableGauge(Meter m, string name, Func<IEnumerable<Measurement<uint>>> observeValues)
        {
            _gauge = m.CreateObservableGauge<long>(name, () => observeValues().Select(m => ToLong(m)));
        }
        private static Measurement<long> ToLong(Measurement<uint> m) => new Measurement<long>((long)m.Value, m.Tags);
    }

```

By that, we'll close this issue and the PR, and we can reconsider it in the future when we see more demand,
