### ISSUE TITLE
[API Proposal]: When stopping an IHost instance, IHostedService instances StopAsync method is called sequentially instead of asynchronously

### ISSUE THREAD

**Issue by jerryk414** [dotnet/runtime#68036]
### Background and motivation
As it is right now, when an `IHost` is asked to `StopAsync` for graceful shutdown, each `IHostedService` is requested to `StopAsync` in sequential order. There's no reason why each `IHostedService.StopAsync` task can't be executed asynchronously and awaited altogether.

Why is this a problem? Well technically everything is functioning to spec, but in practice, it's problematic. 

So normally the idea of being able to set the `ShutdownTimeout` is great.. we can set it to say, 30 seconds, and say we expect all `IHostedService` instances to take no longer than 30 seconds to shutdown gracefully.  The problem is that, this is an additive timeout. That is to say, if you have 10 `IHostedService` instances, and each one of them takes 20 seconds to shutdown, your graceful shutdown now takes 200 seconds. Why do that when you can just have everything shutdown asynchronously in 20 seconds?

One example of the problem with this is that, when deploying apps to ECS in AWS, when ECS triggers an instance of an app to shutdown (which occurs under normal circumstances such as when scaling down), the maximum amount of time it gives for the app to gracefully shutdown is 120 seconds (see [`stopTimeout`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html)), after that it just kills the process.

There's no reason that i can see that the IHostedService instances should be shutdown sequentially, they are async for a reason, and if shutdown order is important, than it should be managed by the consumer themselves, or at the very least, there should be an option for asynchronous IHostedService shutdown.

#### Regression?
This is not a regression

#### Analysis
Link to code causing the issue:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L126

This code could easily be modified to something similar to:
```csharp
HashSet<Task> tasks = new HashSet<Task>();

foreach (IHostedService hostedService in _hostedServices.Reverse()) /* Why does this need to be reversed anyways? */
{
   tasks.Add(hostedService.StopAsync(token));
}

// WhenAll would be great here, but it will swallow up exceptions.. so this is the next best thing
foreach (Task task in tasks)
{
   try
   {
      await task.ConfigureAwait(false);
   }
   catch (Exception ex)
   {
      exceptions.Add(ex);
   }
}
```

### API Proposal
```diff
    public class HostOptions
    {
+        public HostedServiceStopBehavior HostedServiceStopBehavior { get; set; } =
+            HostedServiceStopBehavior.Asynchronous;

        public BackgroundServiceExceptionBehavior BackgroundServiceExceptionBehavior { get; set; } =
            BackgroundServiceExceptionBehavior.StopHost;
    }
    
+    /// <summary>
+    /// Specifies a behavior that the <see cref="IHost"/> will honor when stopping <see cref="IHostedService"/> instances.
+    /// </summary>
+    public enum HostedServiceStopBehavior
+    {
+        /// <summary>
+        /// Indicates that the host will stop the <see cref="IHostedService"/> instances asynchronously.
+        /// </summary>
+        Asynchronous = 0,
+
+        /// <summary>
+        /// Indicates that the host will wait for the previous <see cref="IHostedService"/> instance to stop before stopping the next instance.
+        /// </summary>
+        Sequential = 1
+    }
```
### API Usage
```csharp
   public static IHostBuilder CreateWebHostBuilder(string[] args)
   {
      return Host.CreateDefaultBuilder(args)
         .ConfigureServices((context, services) =>
         {
            services.Configure<HostOptions>(options => 
            {
               options.BackgroundServiceStopBehavior = BackgroundServiceStopBehavior.Sequential; // Defaults to asynchronous
            }
         });
   }
```

### Risks
The default behavior will technically be changing, which would be a breaking change. However, it may be a "safe" breaking change in the sense that the likelihood of someone building an app which depends on this previously internal behavior is highly unlikely and IF they did happen to, there is a way to revert back to the old behavior.

**Comment by eerhardt** [comment]
cc @davidfowl - we were just discussing this a couple weeks ago.

**Comment by davidfowl** [comment]
Agree we should do this and list it as a breaking change (as stop async will run concurrently now). I don't know if we need a flag to opt out of this behavior though.

**Comment by davidfowl** [comment]
@jerryk414 would you be willing to send a PR for this change?

**Comment by quixoticaxis** [comment]
> Agree we should do this and list it as a breaking change (as stop async will run concurrently now). I don't know if we need a flag to opt out of this behavior though.

Any knob to keep the old "started first — stopped last" would be appreciated. We use it to stop stateful in-process services which have cross dependencies.

**Comment by jerryk414** [comment]
I can do that. I'll get an initial implementation done this week to see what thoughts are once the changes are visible.

**Comment by jerryk414** [comment]
@davidfowl @quixoticaxis 
I've added an initial PR for this to make the default behavior asynchronous, with an option for specifying the behavior to be sequential. It would still be a breaking change, but would add the ability to change the behavior back to the way it was.

There are no tests yet - I want to get input if this is the route you would prefer prior to spending time on that.

**Comment by quixoticaxis** [comment]
> @davidfowl @quixoticaxis 
> I've added an initial PR for this to make the default behavior asynchronous, with an option for specifying the behavior to be sequential. It would still be a breaking change, but would add the ability to change the behavior back to the way it was.
> 
> There are no tests yet - I want to get input if this is the route you would prefer prior to spending time on that.

For our product it would be easy to switch back to, looks great.

**Comment by jerryk414** [comment]
> @davidfowl @quixoticaxis I've added an initial PR for this to make the default behavior asynchronous, with an option for specifying the behavior to be sequential. It would still be a breaking change, but would add the ability to change the behavior back to the way it was.
> 
> There are no tests yet - I want to get input if this is the route you would prefer prior to spending time on that.

@davidfowl  @quixoticaxis 
The PR for this is ready for review.

**Comment by jerryk414** [comment]
> I've updated the API proposal above and marked this proposal as ready for review. We will need to get the API proposal approved before we can make this change.

Thank you @eerhardt!

**Comment by terrajobst** [comment]
* We'd prefer `Concurrent` over `Asynchronous`.
* It seems start is currently also sequential
    - Would we want to configure this as well?
    - Does this imply that this can breaking because people have interdependencies between services?

```C#
namespace Microsoft.Extensions.Hosting;

public partial class HostOptions
{
    public bool ServicesStartConcurrently { get; set; } // = false; Maybe change in 8?
    public bool ServicesStopConcurrently { get; set; } // = false; Maybe change in 8?
}
```

**Comment by quixoticaxis** [comment]
>     - Does this imply that this can breaking because people have interdependencies between services?

It would probably not only break dependencies, but also mess up the exception handling around `StartAsync`.

**Comment by quixoticaxis** [comment]
@jerryk414 I personally am not certain `AggregateException` would be a desired scenario, because in case some services failing and others starting you'd have to wait for all of the `StartAsync` either completing or faulting. Maybe throwing on the first exception and cancelling all other services (either currently starting or already started) is a better way.

**Comment by quixoticaxis** [comment]
> @quixoticaxis

> 1) In order to guarantee stopping on the first exception, you need to run things synchronously, which defeats the purpose. In addition, trying to cancel tasks or ignoring them and immediately returning on an exception sounds very misleading.

No, I believe I don't, but, sorry, I'll post the code snippet tomorrow.

Your seconds point seems valid to me though.

**Comment by quixoticaxis** [comment]
@jerryk414 , if someone starts the services concurrently, I suppose it's only fair to assume that their starting logic may be running for prolonged period of time, so there's a fair chance that they respect cancellation requests (at the very least, we do in our stateful services that pre-load data in `StartAsync`). If starting phase is fast, than what's the point of doing it in parallel?

Considering your point about `AggregateException` being an expected behavior I suppose the start may look like something along the lines (throws `AggregateException` and handles cancellation in case of long-running starting logic):
```csharp
using var stopper = CancellationTokenSource.CreateLinkedTokenSource(originalToken);

await Task.WhenAll(
    services
        .Select(
            service => service.StartAsync(stopper.Token))
        .Select(
            task => task.ContinueWith(original =>
            {
                if (original.IsFaulted)
                {
                    try
                    {
                        stopper.Cancel();
                    }
                    catch (AggregateException)
                    {
                        // probably report cancellation callback exceptions
                    }

                    var dispatcher = ExceptionDispatchInfo.Capture(
                        original.Exception!);
                    dispatcher.Throw();
                }
            })));
```

Anyway, the longer I think about it, the more I'm inclined to assume that concurrent start is much more tricky than concurrent stop.

**Comment by quixoticaxis** [comment]
@jerryk414 my point was that I doubt that concurrent start should be implemented in the first place: too many different usage scenarios.

**Comment by buyaa-n** [comment]
> I am - I had a PR up but honestly, it's funny. I'm doing this on my own time - i've got kids, family, and a fulltime job, and it's the holidays, so i just didn't get around to addressing all comments in the PR, and my personal computer took a crap on me, so i've got to get this all setup on another machine. It certainly would be nice if someone else who is paid to do this took ownership and addressed the very minor issues with the PR below.

Sure understand, no rush or any pressure, this is open source and it's up to you if you work on it or when you work. Though we would like to assign the issue if somebody already started working on it, so that other contributes would not start working on it simultaneously, if nobody working on it, we would add `up for grabs` label so that other contributors could find it easily. I just saw you put up a PR and checking if you still planning to finish that PR.

> If nobody does, I do have plans to get back around to it, but not until the new year.

Thank you, for now, nobody has planned to work on it, sounds like we can add `up for grabs` label

**Comment by pedrobsaila** [comment]
Hey @buyaa-n I want to give it a try
