### ISSUE TITLE
Run a .NET framework dll from .NET Core

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#68041]
Is there anyway to use legacy .NET framework dlls in .NET Core apps?
There are millions of dlls (some of them belongs to  MS itself) that target .NET framework and we don't own its source code. So, is it possible for the ,NET runtime to run a .net framework process and communicate with it?
For example: can WinForms Core host the chart control from legacy WinForms?
It is not practical to give millions of dlls away to go with .NET core!
And in a related issue: Is there a away to avoid the NuGet versioning hell?!! Every time I update an app to a newer .NET SDK version  I got NuGet dependencies issues, and can't fidn new versions for some NuGets. Why can't the new SDK run NuGets that use the old SDK?
These two compatibility issues can be fatal to the future of the  .NET core platform. In fact, I mess the stability of the .NET framework.

**Comment by huoyaoyuan** [comment]
> So, is it possible for the ,NET runtime to run a .net framework process and communicate with it?

There can be only one CLR in a process, but .NET Core runtime can try to run .NET Framework assemblies.

> For example: can WinForms Core host the chart control from legacy WinForms?

I assume it should be true. I didn't tried WinForms, but I can't see anything blocking.

> Every time I update an app to a newer .NET SDK version I got NuGet dependencies issues, and can't fidn new versions for some NuGets.

I've never seen any issue like this. You may provide more details about this, and open a separated issue if confirmed.

.NET Core applications can simply consume .NET Framework packages, with a NU1701 warning. Most libraries will just run if they don't use removed technologies like multiple AppDomains.

**Comment by teo-tsirpanis** [comment]
Hello @VBAndCs.

* .NET Core has a compatibility shim that allows it to run .NET Framework assemblies (as long as they don't use any API exclusive to .NET Framework of course). You can always launch an external .NET Framework process without keeping anything special in mind.
* Some `System.*` or `Microsoft.*` NuGet packages have been moved to inbox .NET and are no longer maintained. If your project is depending on some of these packages (that has no stable 6.0.0 version), try removing it and see if it still compiles. Some of these packages are `System.Memory`, `System.Reflection.Emit` and `Microsoft.Win32.Registry`.

**Comment by VBAndCs** [comment]
For example: I tried to update this app
[eShopOnWeb_VB.NET](https://github.com/VBAndCs/eShopOnWeb_VB.NET)
from .NET core 3 to .NET 6. I got many issues, because of contradictions between NuGET dependencies  in different projects, and when finally solved most of them, the final app ran but didn't work correctly!
There are chains for SDK dependencies that remind me of DLLs hell before VS.NET !

**Comment by huoyaoyuan** [comment]
ASP.NET introduces more changes than the base SDK. It's better to view their migration guide at https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60-samples?view=aspnetcore-6.0 . For example, keep every `Microsoft.AspNet` prefixed package up to date.

**Comment by ericstj** [comment]
I think folks have already answered the original question, thank you @huoyaoyuan and @teo-tsirpanis 

> Is there anyway to use legacy .NET framework dlls in .NET Core apps?

Yes.  See https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps#net-framework-compatibility-mode for more information.

> For example: can WinForms Core host the chart control from legacy WinForms?

Yes.  In fact our very first demo's in .NETCore 3.0 which added WinForms used existing 3rd party .NET framework controls.

> from .NET core 3 to .NET 6. I got many issues

> ASP.NET introduces more changes than the base SDK

If you're having trouble migrating an ASP.NET Core application please open an issue in https://github.com/dotnet/aspnetcore
