### ISSUE TITLE
`double` representation of `decimal.MaxValue` cannot be converted properly to `decimal`

### ISSUE THREAD

**Issue by christothes** [dotnet/runtime#68042]
### Description

 `decimal.MaxValue` (79228162514264337593543950335) is representable within the range of double (as 7.9228162514264338E+28), however trying to cast a value back to `decimal` it throws `OverflowException` "Value was either too large or too small for a Decimal."

### Reproduction Steps

```C#
double d = Decimal.ToDouble(decimal.MaxValue);
decimal converted = (decimal)(d);
```

### Expected behavior

The operation succeeds and `converted` == 7.9228162514264338E+28

### Actual behavior

 throws `OverflowException` "Value was either too large or too small for a Decimal."

### Configuration

reproduces in net6.0 and net5.0. I haven't tried others.

**Comment by Clockwork-Muse** [comment]
> `decimal.MaxValue` (79228162514264337593543950335) is representable within the range of double 

This is kinda false, this _exact_ value is not representable.  The nearest round-trip value appears to be `7.922816251426434E+28`, which is greater (not lower) than the maximum value.  

Doubles can no longer represent all integers over 2 ^ 53, or 9007199254740992 (16 digits).

**Comment by Mohit-Chakraborty** [comment]
I did a bit of digging and it looks like it follows from the [rules of explicit conversions](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/numeric-conversions#explicit-numeric-conversions) between different numeric types.

Specifically, these two rules -
> When you convert `decimal` to `float` or `double`, the source value is rounded to the nearest `float` or `double` value, respectively.

and
> When you convert `float` or `double` to `decimal`, the source value is converted to `decimal` representation and rounded to the nearest number after the 28th decimal place if required. If the source value is `NaN` (not a number), infinity, or too large to be represented as a `decimal`, an [`OverflowException`](https://docs.microsoft.com/en-us/dotnet/api/system.overflowexception) is thrown.

In our case, we go from -
`decimal` -> 792281625142643**37593543950335**
to `double` to
`decimal` -> 792281625142643**40000000000000**
which is now larger than `decimal.MaxValue`.

**Comment by tannergooding** [comment]
Note that its actually:
`decimal: 79228162514264337593543950335` to `double: 79228162514264337593543950336`. ` 7.9228162514264338E+28` is just the shortest representable string for that `double` and the trailing digits are not actually zero.

This is still "too large" and should throw as specified. -- I had misread the conversion direction at first thinking the conversion to double was throwing, when it shouldn't.

There is still a separate issue where precision is unnecessarily lost for other values:
```csharp
double x = Math.BitDecrement(79228162514264337593543950335.0);
decimal y = (decimal)x;

Console.WriteLine(x.ToString("G99"));    // 79228162514264328797450928128
Console.WriteLine(y.ToString("G99"));    // 79228162514264300000000000000
```

**Comment by dakersnar** [comment]
Closing this and moving to the more in-depth issue above
