### ISSUE TITLE
Generating `ref` files automatically after making changes in source files

### ISSUE THREAD

**Issue by onurkanbakirci** [dotnet/runtime#68057]
I am trying to develop proposal in .NET runtime repo. I work in `System.Text.Json` library. When i make changes in `/System.Text.Json/src` files, how can i automatically regenerate `/System.Text.Json/ref` folder? I read contributer workflow docs but i can't see any cli command for that purpose. My working environment is macOS.

**Comment by danmoseley** [comment]
Are you looking for this? https://github.com/dotnet/runtime/blob/c2dbee1e3af4b7b0a74c192d51970633e8df2a37/docs/coding-guidelines/updating-ref-source.md#L24

If so, we'd welcome any change you think would make it easier to find.

Note -- this tool has some bugs. Often, you will have to run it, then extract just the lines you need, and paste into the original file.

**Comment by onurkanbakirci** [comment]
Yes. This is what i need. But not work for my problem. I make changes in src folder and after building .sln folder new tests which i write for proposal fails. I think that my changes in src folder not affects anything. How can i solve that? Should i also edit `gen` folder?

**Comment by danmoseley** [comment]
Hmm if you go into the test folder on the command line and do "dotnet build /t:test" does it work?

**Comment by ViktorHofer** [comment]
@onurkanbakirci you should be able to generate the ref file as part of the source build via invoking this command from the repo root: `./dotnet.sh build src/libraries/System.Text.Json/src/ -f net7.0 /p:GenerateReferenceAssemblySource=true`.

Please let me know if that works for you.

**Comment by onurkanbakirci** [comment]
Thank's @ViktorHofer and @danmoseley for your quick responses. `/p:GenerateReferenceAssemblySource=true` command changes `ref` folder but i think there are some bugs as @danmoseley mentioned. After changing `ref` folder manually worked for me.
