### ISSUE TITLE
System.Text.Json source generator crashes when processing unresolved symbols

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/runtime#68072]
### Description

The implementation of System.Text.Json source generation, in particular the mapping layer between Roslyn and System.Reflection types does not seem to handle unresolved symbols particularly well, resulting in crashes when they do turn up.

### Reproduction Steps

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

JsonSerializer.Serialize(new MyPoco(), MyContext.Default.MyPoco);

public class MyPoco
{
    //[UnresolvedProperty] // uncomment to trigger crash
    public int Prop { get; set; }
}

[JsonSerializable(typeof(MyPoco))]
public partial class MyContext : JsonSerializerContext
{ 

}
```

### Expected behavior

Should fail with a relevant error message.

### Actual behavior

Crashes with NullReferenceException:
```
CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'
```

### Regression?

No.

### Other information

The particular error message occurs because we are feeding a [null `AttributeConstructor` value](https://github.com/dotnet/runtime/blob/6543a048d7242ddf204f2e1ba0723d27c02bdfc7/src/libraries/System.Text.Json/gen/Reflection/CustomAttributeDataWrapper.cs#L40) to the `ConstructorInfoWrapper` type, which provides a mapping layer between `IMethodSymbol` and `System.Reflection.ConstructorInfo`.

**Comment by ericstj** [comment]
> Should fail with a relevant error message.

It's possible we might just want to do nothing in the case someone has customized their build to this point.  If we can count on real compiler errors for unresolved symbols those are better than the source generator complaining it can't find types.  Perhaps the only time we'd want the source generator to raise errors was when we were pretty certain that the build would otherwise be successful and the user might be actually trying to use JSON source generator (eg: has a System.Text.Json reference).

**Comment by eiriktsarpalis** [comment]
In principle I agree, but I think we should at least try to exit gracefully when things don't type check. I'm not sure what prior art or best practices exist in the world of source generators.

**Comment by B1Z0N** [comment]
Hi! I've tried googling `UnresolvedPropertyAttribute`, searching it both in this repo and in roslyn repo.

Where it comes from? Please, hint :)

**Comment by huoyaoyuan** [comment]
> Hi! I've tried googling `UnresolvedPropertyAttribute`, searching it both in this repo and in roslyn repo.

As its name hits, it comes nowhere. It triggers a compiling error because the name is undefined.

A source generator should handle this gracefully, instead of crashing.

**Comment by B1Z0N** [comment]
Ahahahah, awkward moment 😀

**Comment by eiriktsarpalis** [comment]
Interestingly, I came across the same exception when debugging the Roslyn analysis service for #68353. It seems to be failing when processing this attribute:
https://github.com/dotnet/runtime/blob/86565188c0e6edbc79a89ef3ebae40ca2551ae2b/src/libraries/System.Text.Json/tests/Common/ReferenceHandlerTests/ReferenceHandlerTests.Deserialize.cs#L1481
