### ISSUE TITLE
Options to handle the default values during JSON serialization and deserialization

### ISSUE THREAD

**Issue by SanderSade** [dotnet/runtime#681]
JSON.NET has [DefaultValueHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_DefaultValueHandling.htm) enumeration, which allows users to determine how the default values are handled during de/serialization.

Similar functionality would be very useful in System.Text.Json, as DefaultValueHandling.Ignore/IgnoreAndPopulate would allow considerable reduction of JSON size in many cases.

**Comment by ericstj** [comment]
Thank you for the issue.

@layomia I recall discussing this last week.  Do we already have an issue tracking this?

**Comment by layomia** [comment]
@ericstj, yes this is a duplicate of https://github.com/dotnet/corefx/issues/38878. I'll close this one and transfer the older one to this repo. cc @sandersade
