### ISSUE TITLE
[API Proposal]: Add MaxValue and MinValue to INumber<TSelf> interface

### ISSUE THREAD

**Issue by monkey0506** [dotnet/runtime#68120]
### Background and motivation

All existing (and reasonably foreseeable) .NET types that implement the `INumber<TSelf>` interface expose the values `MaxValue` and `MinValue` as a `readonly` field or property. The types that implement these values as fields could use explicit interface implementations so there would be no change to the public API of any of the implementing types. Only the public API of the interface would change.

These values are common in use and would be just as useful if dealing with an abstraction like `INumber<TSelf>`. In particular this could be helpful when dealing with generics, when the actual type of `TSelf` is not known, so the field/property is not directly accessible.

Is there any reason these values were excluded from the API? I can't seem to find any prior discussion about it if this was intentional.

### API Proposal

```C#
namespace System
{
    public interface INumber<TSelf> : /* ... */
    {
        /* ... */
        
        public static abstract TSelf MaxValue { get; }
        
        public static abstract TSelf MinValue { get; }
    }
    
    public struct Int32 : /* ... */ /* (et al.) */
    {
        /* ... */
        
        static INumber<Int32>.MaxValue => MaxValue;
        
        static INumber<Int32>.MinValue => MinValue;
    }
}
```

### API Usage

```C#
public class Foo<T> where T : INumber<T>
{
    public static Foo FromUInt64(ulong value)
    {
        if ((value.CompareTo(T.MinValue) < 0) || (value.CompareTo(T.MaxValue) > 0))
        {
            throw new ArgumentException($"{nameof(value)} must be in the range from {T.MinValue} to {T.MaxValue}, inclusive.", nameof(value));
        }
        return new Foo(T.Create(value));
    }

    public Foo(T value) { /* ... */ }
}
```

### Alternative Designs

The end-user could use reflection to look up the relevant field or property and store the values using a static constructor, though this is an unwieldy workaround.

```C#
public class Foo<T> where T : INumber<T>
{
    private static readonly T TMaxValue;
    private static readonly T TMinValue;
    
    static Foo()
    {
        object? value = typeof(T).GetField(nameof(int.MaxValue), BindingFlags.Public | BindingFlags.Static)?.GetValue(null) ??
            typeof(TValue).GetProperty(nameof(int.MaxValue), BindingFlags.Public | BindingFlags.Static)?.GetValue(null);
        if (value is T maxValue)
        {
            TMaxValue = maxValue;
        }
        else
        {
            throw new ArgumentException($"{nameof(T)} must define a public static field or property named {nameof(int.MaxValue)}");
        }
        value = typeof(T).GetField(nameof(int.MinValue), BindingFlags.Public | BindingFlags.Static)?.GetValue(null) ??
            typeof(T).GetProperty(nameof(int.MinValue), BindingFlags.Public | BindingFlags.Static)?.GetValue(null);
        if (value is T minValue)
        {
            TMaxValue = minValue;
        }
        else
        {
            throw new ArgumentException($"{nameof(T)} must define a public static field or property named {nameof(int.MinValue)}");
        }
    }
    
    /* .... */
}
```

### Risks

None known.

**Comment by tannergooding** [comment]
This isn't feasible due to types like `BigInteger`

You'll need to constrain to both `INumber<T>` and `IMinMaxValue<T>`.

**Comment by monkey0506** [comment]
I didn't realize the `IMinMaxValue<T>` interface even existed. That's good to know. Was the exclusion of `BigInteger` from the list of types that implement `INumber<TSelf>` an oversight then?

**Comment by tannergooding** [comment]
There was an issue with the trimmer that prevented it from being included so far. The plan is to get it in before Preview 7 ships

**Comment by monkey0506** [comment]
Fair enough, I suppose. I will use the two constraints instead. Thanks for the tip.
