### ISSUE TITLE
StringWriter memory allocation

### ISSUE THREAD

**Issue by denisenko93** [dotnet/runtime#68123]
### Description

I noticed that when you call overloads of the Write method with argument types such as int, long, uint, ulong you can see memory allocation that shouldn't be there. After discovering this behavior, I checked all the methods of the StringWriter class.

### Configuration

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1645 (21H2)
Intel Core i5-7300HQ CPU 2.50GHz (Kaby Lake), 1 CPU, 4 logical and 4 physical cores
.NET SDK=7.0.100-preview.3.22179.4
  [Host]     : .NET 7.0.0 (7.0.22.17504), X64 RyuJIT
  DefaultJob : .NET 7.0.0 (7.0.22.17504), X64 RyuJIT
```

### Data

Results for Benchmark.DotNet v0.13.1
|                                       Method |       Mean |      Error |     StdDev |     Median |  Gen 0 | Allocated |
|--------------------------------------------- |-----------:|-----------:|-----------:|-----------:|-------:|----------:|
|         StringWriterWriteStringInterpolation |  29.332 ns |  0.2795 ns |  0.2334 ns |  29.287 ns | 0.0179 |      56 B |
|                      StringWriterWriteString |   8.039 ns |  0.0609 ns |  0.0476 ns |   8.044 ns |      - |         - |
|                        StringWriterWriteSpan |  10.390 ns |  0.2828 ns |  0.3257 ns |  10.342 ns |      - |         - |
|               StringWriterWriteStringBuilder |  17.307 ns |  0.3148 ns |  0.2790 ns |  17.235 ns |      - |         - |
|                        StringWriterWriteBool |   9.624 ns |  0.2685 ns |  0.4100 ns |   9.400 ns |      - |         - |
|                        StringWriterWriteByte |  27.498 ns |  0.2067 ns |  0.1832 ns |  27.545 ns | 0.0102 |      32 B |
|                         StringWriterWriteInt |  40.762 ns |  0.8893 ns |  1.1872 ns |  40.286 ns | 0.0153 |      48 B |
|                        StringWriterWriteLong |  67.908 ns |  0.4741 ns |  0.4203 ns |  67.883 ns | 0.0204 |      64 B |
|                        StringWriterWriteUInt |  40.466 ns |  0.3774 ns |  0.3152 ns |  40.595 ns | 0.0153 |      48 B |
|                       StringWriterWriteULong |  63.227 ns |  1.3255 ns |  2.2146 ns |  62.054 ns | 0.0204 |      64 B |
|                        StringWriterWriteChar |   5.146 ns |  0.0912 ns |  0.0808 ns |   5.113 ns |      - |         - |
|                   StringWriterWriteCharArray |  12.499 ns |  0.1664 ns |  0.1556 ns |  12.520 ns |      - |         - |
|              StringWriterWriteCharArrayChunk |  11.320 ns |  0.1505 ns |  0.1407 ns |  11.297 ns |      - |         - |
|                     StringWriterWriteDecimal | 136.305 ns |  2.7478 ns |  2.4359 ns | 135.889 ns | 0.0176 |      56 B |
|                      StringWriterWriteDouble | 227.560 ns |  1.2109 ns |  0.9454 ns | 227.782 ns | 0.0176 |      56 B |
|                       StringWriterWriteFloat | 176.117 ns |  0.5909 ns |  0.5238 ns | 176.126 ns | 0.0126 |      40 B |
|                      StringWriterWriteObject |  75.887 ns |  1.5607 ns |  2.0835 ns |  75.829 ns | 0.0408 |     128 B |
|                     StringWriterWriteFormat1 | 125.454 ns |  2.4750 ns |  2.3151 ns | 126.322 ns | 0.0408 |     128 B |
|                     StringWriterWriteFormat2 | 232.236 ns |  4.6166 ns |  5.8385 ns | 231.430 ns | 0.0637 |     200 B |
|                     StringWriterWriteFormat3 | 386.059 ns |  6.7142 ns |  8.9632 ns | 382.854 ns | 0.0839 |     264 B |
|                     StringWriterWriteFormat4 | 679.722 ns | 12.2758 ns | 11.4828 ns | 676.576 ns | 0.1221 |     384 B |
|     StringWriterWriteLineStringInterpolation |  34.447 ns |  0.5718 ns |  0.5349 ns |  34.233 ns | 0.0178 |      56 B |
|                  StringWriterWriteLineString |  12.279 ns |  0.1643 ns |  0.1537 ns |  12.250 ns |      - |         - |
|                    StringWriterWriteLineSpan |  17.185 ns |  0.1061 ns |  0.0940 ns |  17.196 ns |      - |         - |
|           StringWriterWriteLineStringBuilder |  25.638 ns |  0.3945 ns |  0.3690 ns |  25.699 ns |      - |         - |
|                    StringWriterWriteLineBool |  18.262 ns |  0.0770 ns |  0.0682 ns |  18.251 ns |      - |         - |
|                    StringWriterWriteLineByte |  38.738 ns |  0.3652 ns |  0.3237 ns |  38.741 ns | 0.0102 |      32 B |
|                     StringWriterWriteLineInt |  51.606 ns |  0.5792 ns |  0.5135 ns |  51.491 ns | 0.0153 |      48 B |
|                    StringWriterWriteLineLong |  79.397 ns |  0.5831 ns |  0.5169 ns |  79.359 ns | 0.0204 |      64 B |
|                    StringWriterWriteLineUInt |  51.785 ns |  0.2442 ns |  0.2284 ns |  51.785 ns | 0.0153 |      48 B |
|                   StringWriterWriteLineULong |  75.548 ns |  1.5562 ns |  2.3765 ns |  75.014 ns | 0.0204 |      64 B |
|                    StringWriterWriteLineChar |  15.115 ns |  0.2090 ns |  0.1955 ns |  15.078 ns |      - |         - |
|               StringWriterWriteLineCharArray |  20.872 ns |  0.2745 ns |  0.2434 ns |  20.875 ns |      - |         - |
|          StringWriterWriteLineCharArrayChunk |  20.483 ns |  0.3426 ns |  0.3037 ns |  20.439 ns |      - |         - |
|                 StringWriterWriteLineDecimal | 143.557 ns |  1.4418 ns |  1.3487 ns | 143.393 ns | 0.0176 |      56 B |
|                  StringWriterWriteLineDouble | 242.508 ns |  1.3970 ns |  1.1665 ns | 242.660 ns | 0.0176 |      56 B |
|                   StringWriterWriteLineFloat | 192.983 ns |  3.8381 ns |  3.5901 ns | 193.535 ns | 0.0126 |      40 B |
|                  StringWriterWriteLineObject |  78.423 ns |  0.3183 ns |  0.2658 ns |  78.469 ns | 0.0408 |     128 B |
|                 StringWriterWriteLineFormat1 | 126.250 ns |  0.5309 ns |  0.4433 ns | 126.240 ns | 0.0408 |     128 B |
|                 StringWriterWriteLineFormat2 | 224.180 ns |  2.4989 ns |  2.3375 ns | 224.284 ns | 0.0637 |     200 B |
|                 StringWriterWriteLineFormat3 | 378.024 ns |  3.4733 ns |  2.9004 ns | 377.439 ns | 0.0839 |     264 B |
|                 StringWriterWriteLineFormat4 | 704.508 ns | 13.9087 ns | 22.0606 ns | 703.223 ns | 0.1221 |     384 B |
|         StringWriterWriteReadOnlyMemoryAsync |  16.411 ns |  0.3664 ns |  0.3598 ns |  16.314 ns |      - |         - |
|          StringWriterWriteStringBuilderAsync |  19.428 ns |  0.3374 ns |  0.2991 ns |  19.586 ns |      - |         - |
|                   StringWriterWriteCharAsync |   7.805 ns |  0.1833 ns |  0.1715 ns |   7.716 ns |      - |         - |
|              StringWriterWriteCharArrayAsync |  14.522 ns |  0.3170 ns |  0.3114 ns |  14.561 ns |      - |         - |
|         StringWriterWriteCharArrayChunkAsync |  14.004 ns |  0.3155 ns |  0.5848 ns |  13.999 ns |      - |         - |
|                 StringWriterWriteStringAsync |  10.187 ns |  0.2442 ns |  0.3730 ns |  10.233 ns |      - |         - |
|     StringWriterWriteInterpolatedStringAsync |  32.046 ns |  0.6764 ns |  1.5676 ns |  31.480 ns | 0.0179 |      56 B |
|     StringWriterWriteLineReadOnlyMemoryAsync |  23.130 ns |  0.2956 ns |  0.2765 ns |  23.137 ns |      - |         - |
|      StringWriterWriteLineStringBuilderAsync |  28.007 ns |  0.5988 ns |  0.6656 ns |  27.870 ns |      - |         - |
|               StringWriterWriteLineCharAsync |  15.986 ns |  0.1529 ns |  0.1430 ns |  15.972 ns |      - |         - |
|          StringWriterWriteLineCharArrayAsync |  22.444 ns |  0.2672 ns |  0.2500 ns |  22.390 ns |      - |         - |
|     StringWriterWriteLineCharArrayChunkAsync |  21.951 ns |  0.4612 ns |  0.3851 ns |  21.984 ns |      - |         - |
|             StringWriterWriteLineStringAsync |  14.779 ns |  0.3351 ns |  0.6995 ns |  14.471 ns |      - |         - |
| StringWriterWriteLineInterpolatedStringAsync |  36.365 ns |  0.7607 ns |  1.5880 ns |  36.329 ns | 0.0178 |      56 B |
### Analysis

I overridden some methods in the StringWriter class and got the following results
|                                       Method |       Mean |      Error |     StdDev |  Gen 0 | Allocated |
|--------------------------------------------- |-----------:|-----------:|-----------:|-------:|----------:|
|         StringWriterWriteStringInterpolation |  38.124 ns |  0.8304 ns |  0.8528 ns | 0.0178 |      56 B |
|                      StringWriterWriteString |   9.947 ns |  0.0824 ns |  0.0688 ns |      - |         - |
|                        StringWriterWriteSpan |  10.425 ns |  0.0901 ns |  0.0799 ns |      - |         - |
|               StringWriterWriteStringBuilder |  18.198 ns |  0.1215 ns |  0.1136 ns |      - |         - |
|                        StringWriterWriteBool |  10.651 ns |  0.0472 ns |  0.0394 ns |      - |         - |
|                        StringWriterWriteByte |  12.040 ns |  0.3147 ns |  0.2790 ns |      - |         - |
|                         StringWriterWriteInt |  20.754 ns |  0.1533 ns |  0.1280 ns |      - |         - |
|                        StringWriterWriteLong |  47.405 ns |  0.3707 ns |  0.3286 ns |      - |         - |
|                        StringWriterWriteUInt |  23.550 ns |  0.5272 ns |  0.7217 ns |      - |         - |
|                       StringWriterWriteULong |  39.761 ns |  0.1112 ns |  0.1040 ns |      - |         - |
|                        StringWriterWriteChar |   6.749 ns |  0.1918 ns |  0.1794 ns |      - |         - |
|                   StringWriterWriteCharArray |  12.461 ns |  0.2994 ns |  0.2501 ns |      - |         - |
|              StringWriterWriteCharArrayChunk |  12.130 ns |  0.3039 ns |  0.4056 ns |      - |         - |
|                     StringWriterWriteDecimal | 117.122 ns |  2.4169 ns |  4.3581 ns |      - |         - |
|                      StringWriterWriteDouble | 193.187 ns |  3.7176 ns |  3.6512 ns |      - |         - |
|                       StringWriterWriteFloat | 156.453 ns |  3.1696 ns |  6.1068 ns |      - |         - |
|                      StringWriterWriteObject |  65.341 ns |  1.0348 ns |  0.8641 ns | 0.0408 |     128 B |
|                     StringWriterWriteFormat1 |  58.284 ns |  1.2231 ns |  2.8591 ns | 0.0102 |      32 B |
|                     StringWriterWriteFormat2 | 158.928 ns |  2.9878 ns |  2.6486 ns | 0.0176 |      56 B |
|                     StringWriterWriteFormat3 | 312.774 ns |  3.0781 ns |  2.5704 ns | 0.0277 |      88 B |
|                     StringWriterWriteFormat4 | 607.754 ns |  3.7974 ns |  3.5521 ns | 0.0534 |     168 B |
|     StringWriterWriteLineStringInterpolation |  40.241 ns |  0.4884 ns |  0.4329 ns | 0.0178 |      56 B |
|                  StringWriterWriteLineString |  14.759 ns |  0.3236 ns |  0.3027 ns |      - |         - |
|                    StringWriterWriteLineSpan |  17.359 ns |  0.4228 ns |  0.7731 ns |      - |         - |
|           StringWriterWriteLineStringBuilder |  26.404 ns |  0.5801 ns |  0.9850 ns |      - |         - |
|                    StringWriterWriteLineBool |  18.796 ns |  0.4389 ns |  0.4105 ns |      - |         - |
|                    StringWriterWriteLineByte |  22.986 ns |  0.4867 ns |  0.6329 ns |      - |         - |
|                     StringWriterWriteLineInt |  31.501 ns |  0.4972 ns |  0.4152 ns |      - |         - |
|                    StringWriterWriteLineLong |  65.247 ns |  0.5804 ns |  0.4846 ns |      - |         - |
|                    StringWriterWriteLineUInt |  33.774 ns |  0.3990 ns |  0.3537 ns |      - |         - |
|                   StringWriterWriteLineULong |  53.151 ns |  1.0591 ns |  0.9907 ns |      - |         - |
|                    StringWriterWriteLineChar |  15.487 ns |  0.2697 ns |  0.2252 ns |      - |         - |
|               StringWriterWriteLineCharArray |  23.183 ns |  0.5076 ns |  0.5213 ns |      - |         - |
|          StringWriterWriteLineCharArrayChunk |  21.177 ns |  0.2027 ns |  0.1693 ns |      - |         - |
|                 StringWriterWriteLineDecimal | 123.636 ns |  1.1039 ns |  0.9218 ns |      - |         - |
|                  StringWriterWriteLineDouble | 221.346 ns |  4.3684 ns |  5.2003 ns |      - |         - |
|                   StringWriterWriteLineFloat | 176.999 ns |  1.1321 ns |  1.0036 ns |      - |         - |
|                  StringWriterWriteLineObject |  80.296 ns |  0.9897 ns |  0.8774 ns | 0.0408 |     128 B |
|                 StringWriterWriteLineFormat1 |  74.787 ns |  1.5258 ns |  1.6959 ns | 0.0101 |      32 B |
|                 StringWriterWriteLineFormat2 | 163.317 ns |  1.1898 ns |  0.9936 ns | 0.0176 |      56 B |
|                 StringWriterWriteLineFormat3 | 330.836 ns |  3.9549 ns |  3.3025 ns | 0.0277 |      88 B |
|                 StringWriterWriteLineFormat4 | 638.085 ns | 11.5955 ns | 11.9077 ns | 0.0534 |     168 B |
|         StringWriterWriteReadOnlyMemoryAsync |  17.508 ns |  0.2187 ns |  0.2045 ns |      - |         - |
|          StringWriterWriteStringBuilderAsync |  19.682 ns |  0.1580 ns |  0.1401 ns |      - |         - |
|                   StringWriterWriteCharAsync |   8.878 ns |  0.2142 ns |  0.3862 ns |      - |         - |
|              StringWriterWriteCharArrayAsync |  14.094 ns |  0.2766 ns |  0.2452 ns |      - |         - |
|         StringWriterWriteCharArrayChunkAsync |  12.478 ns |  0.0495 ns |  0.0413 ns |      - |         - |
|                 StringWriterWriteStringAsync |  11.353 ns |  0.1005 ns |  0.0891 ns |      - |         - |
|     StringWriterWriteInterpolatedStringAsync |  38.526 ns |  0.7624 ns |  1.6248 ns | 0.0178 |      56 B |
|     StringWriterWriteLineReadOnlyMemoryAsync |  22.911 ns |  0.3824 ns |  0.3577 ns |      - |         - |
|      StringWriterWriteLineStringBuilderAsync |  28.699 ns |  0.5388 ns |  0.5292 ns |      - |         - |
|               StringWriterWriteLineCharAsync |  17.858 ns |  0.3917 ns |  0.5094 ns |      - |         - |
|          StringWriterWriteLineCharArrayAsync |  22.420 ns |  0.2846 ns |  0.2662 ns |      - |         - |
|     StringWriterWriteLineCharArrayChunkAsync |  22.025 ns |  0.4637 ns |  0.5155 ns |      - |         - |
|             StringWriterWriteLineStringAsync |  18.136 ns |  0.3880 ns |  0.4619 ns |      - |         - |
| StringWriterWriteLineInterpolatedStringAsync |  38.866 ns |  0.2962 ns |  0.2625 ns | 0.0178 |      56 B |

The benchmark source code is in my [repository](https://github.com/denisenko93/StringWriterBeanchmark). I can create a PR with these changes.

**Comment by denisenko93** [comment]
@dotnet/area-system-io

**Comment by huoyaoyuan** [comment]
These methods are actually defined and implemented in the base class `TextWriter`. `StringWriter` does not override them as an optimization.

**Comment by denisenko93** [comment]
Yes. Overriding these methods from TextWriter enables StringBuilder optimizations. This gives a performance boost and reduces memory allocation. We can also create a method for handling interpolated strings similar to the one in StringBuilder

**Comment by denisenko93** [comment]
Can I create a PR with these changes?

**Comment by huoyaoyuan** [comment]
The more commonly used StreamWriter does not override them either. Some changes can be done to the base TextWriter class, but without breaking compatibility. It's better to let the area owners to decide what to do here.

**Comment by denisenko93** [comment]
These optimizations depend on the types in the internal store. In StringWriter, it is a char array. In StreamWriter it is a byte array

**Comment by MMaximus111** [comment]
Cool boost performance. Its very important for high performance solutions. Thank you @denisenko93 for this case.

**Comment by denisenko93** [comment]
I checked the possibility of making changes to the TextWriter class. I have a question. Why was the Write(char[] buffer!!, int index, int count) overload chosen to be the default (the method that all other overloads call)? I suggest the Write(ReadOnlySpan<char> buffer) overload be chosen as the base one. This will allow you to write stackalloc buffers without unnecessary overhead
```C#
        public virtual void Write(char[]? buffer)
        {
            if (buffer != null)
            {
                Write(buffer.AsSpan());
            }
        }

        // Writes a range of a character array to the text stream. This method will
        // write count characters of data into this TextWriter from the
        // buffer character array starting at position index.
        //
        public virtual void Write(char[] buffer!!, int index, int count)
        {
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(index), SR.ArgumentOutOfRange_NeedNonNegNum);
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(count), SR.ArgumentOutOfRange_NeedNonNegNum);
            }
            if (buffer.Length - index < count)
            {
                throw new ArgumentException(SR.Argument_InvalidOffLen);
            }

            Write(buffer.AsSpan().Slice(index, count));
        }

        // Writes a span of characters to the text stream.
        //
        public virtual void Write(ReadOnlySpan<char> buffer)
        {
            for (int i = 0; i < buffer.Length; i++) Write(buffer[i]);
        }
        public virtual void Write(string? value)
        {
            if (value != null)
            {
                Write(value.AsSpan());
            }
        }
```
It also allows you to change the implementation of overloads of int, uint, long and others using the ISpanFormattable interface 
```C#
public virtual void Write(long value)
{
    Span<char> buffer = stackalloc char[20]; // Max Int64 digits

    if (value.TryFormat(buffer, out int charsWritten, provider: FormatProvider))
    {
        Write(buffer.Slice(0, charsWritten));
    }
    else
    {
        Write(value.ToString(FormatProvider));
    }
}
```

**Comment by stephentoub** [comment]
> do you think that we are ever going to change this approach?

I doubt it.  It'd be a massive breaking change to change the order of delegation.  It's trivial to find implementations that don't override the span-based method.

**Comment by denisenko93** [comment]
I agree. Then I suggest changing the implementations of the Write methods for `long`, `int`, `ulong`, `uint`, `decimal`, `double` and `float` to use `Span<char>` in the `TextWriter` class. This will give a performance boost and reduce the memory allocation in the descendant classes that implement the method `Write(ReadOnlySpan<char> buffer)`

> ```cs
> public virtual void Write(long value)
> {
>     Span<char> buffer = stackalloc char[20]; // Max Int64 digits
> 
>     if (value.TryFormat(buffer, out int charsWritten, provider: FormatProvider))
>     {
>         Write(buffer.Slice(0, charsWritten));
>     }
>     else
>     {
>         Write(value.ToString(FormatProvider));
>     }
> }
> ```
I also suggest override the `Write(format, ...)` methods in the `StringWriter` class so that they use the `AppendFormat` methods from `StringBuilder`
```cs
        public override void Write(string format, object? arg0)
        {
            if (GetType() != typeof(StringWriter))
            {
                // This overload was added after the Write(char[], ...) overload, and so in case
                // a derived type may have overridden it, we need to delegate to it, which the base does.
                base.Write(format, arg0);
                return;
            }

            if (!_isOpen)
            {
                throw new ObjectDisposedException(null, SR.ObjectDisposed_WriterClosed);
            }

            _sb.AppendFormat(format, arg0);
        }
```

**Comment by denisenko93** [comment]
@stephentoub, what do you think about this?

**Comment by denisenko93** [comment]
On my machine I got a small performance boost
|               Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|--------------------- |---------:|---------:|---------:|-------:|----------:|
|         CurrentWrite | 58.80 ns | 1.211 ns | 1.617 ns | 0.0204 |      64 B |
|       OptimisedWrite | 52.21 ns | 0.196 ns | 0.174 ns |      - |         - |
|   CustomCurrentWrite | 57.44 ns | 1.145 ns | 1.407 ns | 0.0204 |      64 B |
| CustomOptimisedWrite | 61.39 ns | 0.172 ns | 0.144 ns | 0.0204 |      64 B |
I don't know why, after optimization, the method in the derived class began to work longer
Benchmark source code https://gist.github.com/denisenko93/210514046f31c95224687f4afdc5777b

**Comment by adamsitnik** [comment]
> I don't know why, after optimization, the method in the derived class began to work longer

I suspect that it can be the cost of extra type check and virtual method call:

```cs
if (GetType() == typeof(OptimizedStringWriter))
// ...
base.Write(value);
```

You could use one of the profilers that show CPU time per C# source code line to find out (Visual Studio Profiler should work great).

we could add one more optimization that is enabled for System.Private.CoreLib by default:

```cs
[System.Runtime.CompilerServices.SkipLocalsInit]
public override void Write(long value)
```

it does not force zeroing of the stack-allocated memory

**Comment by denisenko93** [comment]
In the visual studio profiler, I did not see any performance degradation for the derived classes
![image](https://user-images.githubusercontent.com/36818775/169697517-444c8999-dcbb-4f8a-8268-55de6de0b25f.png)

**Comment by denisenko93** [comment]
Do you think it's worth making changes to the stringwriter for such a small performance gain?

**Comment by adamsitnik** [comment]
> Do you think it's worth making changes to the stringwriter for such a small performance gain?

**Comment by adamsitnik** [comment]
> Do you think it's worth making changes to the stringwriter for such a small performance gain?

To be honest I don't. Any changes that increase the complexity should be clearly worth introducing them from the performance perspective.

@denisenko93 Thank you for your time and your proposal!
