### ISSUE TITLE
.NET 6 not support XslCompiledTransform.Load(type(myXsltCompiled_dll)) 

### ISSUE THREAD

**Issue by mendozagit** [dotnet/runtime#68129]
### Description

`FileNotFoundException` when perform an XslCompiledTransform.Load(type(myXsltCompiledDLL)) by Using an Assembly. (assembly created from `xsltc.exe tool`) 

### Reproduction Steps

1- Follow exactly this tutorial (https://docs.microsoft.com/en-us/dotnet/standard/data/xml/how-to-perform-an-xslt-transformation-by-using-an-assembly)

2- Use .NET6 instead of .NetFramework to run to execute tutorial code example.

```csharp  
private void button1_Click(object sender, EventArgs e)
{
 //Create a new XslCompiledTransform and load the compiled transformation.
XslCompiledTransform xslt = new XslCompiledTransform();

xslt.Load(typeof(Transform)); // <---- here the exception is fired

// Execute the transformation and output the results to a file.
xslt.Transform("books.xml", "discount_books.html");
 }
```

### Expected behavior

To be able to read XSLT from compiled assemblies and to be able to do transformations, as it happens in .Net Framework.

### Actual behavior

When I invoke the method XslCompiledTransform.Load(type(myXsltCompiledDLL)), from .NET6, the runtime fires an exception 

**Stack trace**
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. El sistema no puede encontrar el archivo especificado.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Delegate.BindToMethodInfo(Object target, IRuntimeMethodInfo method, RuntimeType methodType, DelegateBindingFlags flags)
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at System.Xml.Xsl.XslCompiledTransform.Load(MethodInfo executeMethod, Byte[] queryData, Type[] earlyBoundTypes)
   at System.Xml.Xsl.XslCompiledTransform.Load(Type compiledStylesheet)
   at WinFormsApp1.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\PHILIPS.JESUSMENDOZA\source\repos\WinFormsApp1\Form1.cs:line 18
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
 

### Regression?

Yes, this works on .Net framework 4.X applications.

### Configuration

Which version of .NET is the code running on? 
_.NET 6 (winforms and console)_

What OS and version, and what distro if applicable?
Edición	Windows 10 Pro
Versión	21H2
Se instaló el	‎08/‎12/‎2021
Compilación del SO	19044.1645
Experiencia	Windows Feature Experience Pack 120.2212.4170.0

What is the architecture (x64, x86, ARM, ARM64)?

Nombre del dispositivo	DESKTOP-5RUV9I5
Procesador	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
RAM instalada	32.0 GB (31.2 GB utilizable)
Tipo de sistema	Sistema operativo de 64 bits, procesador x64
Lápiz y entrada táctil	La entrada táctil o manuscrita no está disponible para esta pantalla

Do you know whether it is specific to that configuration?
I believe that the problem is not related to the windows version or the processor architecture, but to the dotnet runtime version.

If you're using Blazor, which web browser(s) do you see this issue in?
No

**Comment by huoyaoyuan** [comment]
The assembly `System.Data.SqlXml` contains the namespace `System.Xml.Xsl.Runtime`, which is not present in .NET Core.

According to the [porting guide](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable#xslt-script-blocks), `msxsl:script` is unavailable on .NET Core. The .NET Framework specific tutorial is expected not to work.

**Comment by mendozagit** [comment]
Thanks for your feedback, do you know if will be migrated? Or never will be on .Net5+ ?

**Comment by danmoseley** [comment]
@ajcvickers @David-Engel do either of you have context on this? (since it was in S.D.SqlXml)

**Comment by David-Engel** [comment]
I don't have any context on S.D.SqlXml.

**Comment by ajcvickers** [comment]
Looks like System.Data.SqlXml is part of [SQLXML](https://docs.microsoft.com/en-us/sql/relational-databases/sqlxml/what-s-new-in-sqlxml-4-0-sp1?view=sql-server-ver15) which is owned by the SQL Server org and as far as I know does not support .NET Core. I don't know if they have any plans to support .NET Core.

@scoriani Do you know anything here?

**Comment by scoriani** [comment]
There are currently no plans regarding SQLXML and support for .NET 5+, and we haven't heard many requests in this direction. I would recommend opening up a User Voice here to get some traction and consensus on the subject: https://aka.ms/sqlfeedback

**Comment by mendozagit** [comment]
Thanks for your feedbacks, I have been created a new suggest on  https://aka.ms/sqlfeedback, so I think only wait for.

**Comment by danmoseley** [comment]
I'll close then. Thanks for the issue.

**Comment by gewarren** [comment]
@scoriani Should `XslCompiledTransform.Load` be marked as obsolete then?

**Comment by scoriani** [comment]
@gewarren, not my area of expertise, maybe you were looking for someone else?
