### ISSUE TITLE
SPMI failing in CI

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#68137]
Sample runs:

1) Replay: https://dev.azure.com/dnceng/public/_build/results?buildId=1722826&view=results.
2) Diffs: https://dev.azure.com/dnceng/public/_build/results?buildId=1722827&view=results (note how both the base and diff Jits are failing).

Side note: it seems suboptimal that failures like these do not show up on GH as "red CI".

@dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
@BruceForstall with the change made in #61699, can we remove the `shouldContinueOnError: true` that we discussed in #60594 so that the pipeline is properly marked red on failures?

**Comment by jakobbotsch** [comment]
I am occasionally hitting AV inside `memcpy` in `repGetStringLiteral`, so this is probably caused by #68055. cc @EgorBo

**Comment by EgorBo** [comment]
> I am occasionally hitting AV inside `memcpy` in `repGetStringLiteral`, so this is probably caused by #68055. cc @EgorBo

will file a fix in a moment, sorry

**Comment by jakobbotsch** [comment]
Fixed by #68161
