### ISSUE TITLE
Implicit Vector/Tuple conversions

### ISSUE THREAD

**Issue by Redninja106** [dotnet/runtime#68145]
### Background and motivation

In many cases involving vector types, I find myself  calling vector constructors everywhere. It makes vectors seem less like a basic numeric type and more like a class. 

Additionally, I often find myself storing vectors in a variable just to assign its individual components to other variables. 

As a solution I propose adding implicit conversions both ways between the vector types in `System.Numerics` and tuples with the matching number of float components, as well as a `Deconstruct()` method to each to allow tuple deconstruction syntax with vectors.

This may well be overkill given the recently added implicit `new(…)`, which can infer the vector type in most cases, but as I said before, the new keyword makes the vector types seem more like a normal object while they serve a different purpose.

I’m not sure of the performance implications of this, though I’d guess them to be trivial.

### API Proposal

```C#
namespace System.Numerics;

public struct Vector2
{
    public static implicit operator (float, float)(Vector2 vector)
    {
        return (vector.X, vector.Y); // could Unsafe.As() be better here?
    }
    
    public static implicit operator Vector2((float, float) values)
    {
            return new Vector2(values.Item1, values.Item2);
    }
    public void Deconstruct(out float x, out float y)
    {
        x = this.X;
        y = this.Y;
    }
}
// and so on for Vector3 and Vector4
```

### API Usage

```C#
// allows for simpler assignment of vector types 
Vector2 a = (1, 2);
// as well as deconstruction
float x, y;
(x, y) = a;

// assuming some method that takes in a vector…
Vector2 Rotate(Vector2 vector, float angle);
// simpler to pass a vector as a parameter
Rotate((2, 3), MathF.Pi);
```

**Comment by huoyaoyuan** [comment]
Implicit conversion can be troublesome in some cases. A destruction method would be better.

**Comment by tannergooding** [comment]
This is also potentially a performance pit-fall for something which is designed as a performance oriented type.

I will say that implicit conversions are likely going to be a non-starter here. Having some deconstruct method might be reasonable as might some constructor or explicit conversion operator.

**Comment by tannergooding** [comment]
Going to close this as per the above. If someone wants to open a proposal covering a `Deconstruct` method, I'd be willing to take that to API review.
