### ISSUE TITLE
[API Proposal]: HttpRequestOptions should implement IReadOnlyDictionary

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/runtime#68149]
### Background and motivation

Methods and extension methods that don't modify a dictionary often expect a parameter of `IReadOnlyDictionary` instead of `IDictionary`.

### API Proposal

```C#
namespace System.Net.Http
{
    public class HttpRequestOptions : IReadOnlyDictionary<string,object>, // NEW
                                      IDictionary<string, object> // EXISTING
    {
          [...]
    }
}
```

### API Usage

```c#
var dic = (IReadOnlyDictionary<string,object>)request.Options;
```

### Risks

In rare circumstances, a method will have an overload for IDictionary and another overload for IReadOnlyDictionary. This would be ambiguous for HttpRequestOptions, as it is for other dictionaries.

**Comment by karelz** [comment]
Triage: `IReadOnlyDictionary` is strict subset of already implemented `IDictionary`, so the work is minimal. We wouldn't mind having both interfaces, unless it brings some known problems in general (API review to advise here).
BTW: The type `HttpRequestOptions` was introduced in .NET 5.

**Comment by bartonjs** [comment]
Looks good as proposed.

We discussed the risks inherent to being both IDictionary and IReadOnlyDictionary (namely, being an ambiguous target for overloading). But we generally think that the risk is low, and the workaround (casting to one of the two interfaces) is easy.

```diff
namespace System.Net.Http
{
    public class HttpRequestOptions :
+        IReadOnlyDictionary<string,object>,
         IDictionary<string, object>
    {
    }
}
```
