### ISSUE TITLE
FormatterServices.GetUninitializedObject no longer supports delegates

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/runtime#68144]
### Description

Used to work in .NET FW, no longer works in .NET 6.

### Reproduction Steps

```cs
var a = FormatterServices.GetUninitializedObject(typeof(Action));
```

### Expected behavior

Creates an invalid instance of a delegate.

### Actual behavior

Throws an exception.

### Regression?

Yes this worked in .NET 4.8.

### Known Workarounds

None

### Other information

This is a big problem because I rely on this to enforce type safety when building custom expression trees. This is simplified code below.
```cs
void CallInstance<TObj, TArg>(Ref<TObj> obj, Func<TObj, Action<TArg>> getAction, Ref<TArg> arg) 
{
  var action = getAction(DummyHolder<TObj>.Dummy);
  var method = action.Method; 
  // ...
}
class DummyHolder<T>
{
  public static readonly Dummy = FormatterServices.GetUninitializedObject(typeof(T));
}


Ref<Action<string>> actionRef = ...;
Ref<string> strRef = ...;
CallInstance(drRef, _=>new Action<string>(_.Invoke), strRef);
```

**Comment by teo-tsirpanis** [comment]
(assigning it to CompilerServices, because this method forwards to `System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject`)

**Comment by jkotas** [comment]
This check that rejects delegates was introduced in https://github.com/dotnet/runtime/pull/32520 . cc @GrabYourPitchforks 

> This is a big problem because I rely on this to enforce type safety when building custom expression trees.

I am not able to follow how this helps with type safety from your code fragment. The code fragment is using the partially constructed delegate instance to get MethodInfo of the Invoke method. Would it be better to get the MethodInfo directly e.g. by calling `Type.GetMethod`?

**Comment by TahirAhmadov** [comment]
> I am not able to follow how this helps with type safety from your code fragment. The code fragment is using the partially constructed delegate instance to get MethodInfo of the Invoke method. Would it be better to get the MethodInfo directly e.g. by calling `Type.GetMethod`?

Yes it's possible, but that prevents me from being able to enforce type safety at compile time. Using the code snippet in the OP, I can ensure that the correct arguments are passed in to the method.

However, I was able to work around this limitation by creating an empty `DynamicMethod` with the signature of the delegate type, and instantiating a delegate from that method. Meaning, it's no longer critical for me to allow creating "empty" delegates using `FormatterServices.GetUninitializedObject`.

**Comment by GrabYourPitchforks** [comment]
I think this scenario would be covered by https://github.com/dotnet/runtime/issues/36194. Instead of using `GetUninitializedObject` to alloc and zero-init then calling the ctor as a standard method, one of the factories proposed by that issue would encapsulate all of these operations as a single method call.

That said, since the workaround is to use standard reflection or to use ref emit (as in the previous comment), and since we really don't want to be in the business of people zero-initing our foundational runtime types, I think there is nothing more for us to do here and that this issue should be closed.

**Comment by TahirAhmadov** [comment]
> I think this scenario would be covered by #36194. Instead of using `GetUninitializedObject` to alloc and zero-init then calling the ctor as a standard method, one of the factories proposed by that issue would encapsulate all of these operations as a single method call.

To clarify, I wasn't calling the ctor as a standard method on the newly zero-allocced instance of a delegate; instead, I was using that instance as is to pass it to parameter `getAction` in the OP in order to get a strongly-typed `Invoke` delegate back. All this was purely to ensure that I construct the virtual expression tree in a type-safe manner; I was not actually using the zero-allocced delegate in any other way.

> That said, since the workaround is to use standard reflection or to use ref emit (as in the previous comment), and since we really don't want to be in the business of people zero-initing our foundational runtime types, I think there is nothing more for us to do here and that this issue should be closed.

I concur.
