### ISSUE TITLE
[API Proposal]: ISpanFormattable destination length

### ISSUE THREAD

**Issue by denisenko93** [dotnet/runtime#68154]
### Background and motivation

When ISpanFormattable.TryFormat returns false, I don't know how long the destination should be. I suggest renaming the charsWritten field to resultLength and if the destination is too short, return what length it should be in it

### API Proposal

```C#
public interface ISpanFormattable
{
    public bool TryFormat (Span<char> destination, out int resultLength, ReadOnlySpan<char> format, IFormatProvider? provider);
}
```

### API Usage

```C#
int value = int.MaxValue;

Span<char> destination = stackalloc char[10];

if(!value.TryFormat(destination, out int resultLength, "f2", CultureInfo.InvariantCulture))
{
    destination = stackalloc char[resultLength];

    value.TryFormat(destination, out int _, "f2", CultureInfo.InvariantCulture); // Always true
}

// Use destination
```

### Alternative Designs

Implement a method that calculates the assignment length in ISpanFormatable

Proposition:
```C#
public interface ISpanFormattable
{
    public bool TryCalculateLength (out int resultLength, ReadOnlySpan<char> format, IFormatProvider? provider)
   {
       resultLength = 0;
       return false;
   }
}
```
Usage:
```C#
int value = int.MaxValue;

int bufferLength;

if(!value.TryCalculateLength(destination, out bufferLength, "f2", CultureInfo.InvariantCulture)
{
   bufferLength = 10;
}

Span<char> destination = stackalloc char[bufferLength];

if(!value.TryFormat(destination, out int resultLength, "f2", CultureInfo.InvariantCulture))
{
     // Handle error
}

// Use destination
```

**Comment by alexrp** [comment]
> I suggest renaming the charsWritten field to resultLength and if the destination is too short, return what length it should be in it

This part of the proposal is a non-starter; it could break code already written against the interface.

**Comment by Tornhoof** [comment]
None of those TryFormatXXX APIs return length of the necessary buffer on false. It is often not possible to calculate the exact length, without doing the formatting. At that point it's then a trade-off in API design, requiring the implementation to calculate the exact the length or just telling the caller to increase the buffer size.  In general increasing the buffer size is cheaper at runtime that running the formatting algorithm multiple times.

**Comment by FiniteReality** [comment]
I wonder if C#10 static abstract members could be used to add a "maximum buffer length" property to types implementing ISpanFormattable. For example, Int64 has a max length of 20 characters when using base 10. This would somewhat alleviate the issue of calculating the length needed for a specific set of parameters, as only one "this is the maximum length of any possible combination of parameters" would be needed.

**Comment by tannergooding** [comment]
This would be a breaking change and is not something we could do. A new API would need to be proposed instead, as suggested above.
