### ISSUE TITLE
System.Text.Json.JsonSerializer.Deserialize not working for Guid property with protected setter

### ISSUE THREAD

**Issue by TheMagnificent11** [dotnet/runtime#68155]
### Description

I have a class that has protected setters for all of its properties.

Deserialization works for all the properties except the `Guid` property.

### Reproduction Steps

```cs
using System.Text.Json;
using FluentAssertions;
using Xunit;

namespace My.Tests.Unit;

public partial class DomainEventReferenceTests
{
    public class TestClass
    {
        public TestClass(
            string name,
            int count,
            DateTime createdAt)
        {
            this.Id = Guid.NewGuid();
            this.Name = name;
            this.Count = count;
            this.CreatedAt = createdAt;
        }

        public Guid Id { get; protected set; }

        public string Name { get; protected set; }

        public int Count { get; protected set; }

        public DateTime CreatedAt { get; protected set; }
    }

    public class TestClassTests
    {
        [Fact]
        public static void DeserializeProtectedSetters()
        {
            var input = new TestClass(
                "hello",
                17,
                DateTime.UtcNow);

            var json = JsonSerializer.Serialize(input);

            var output = JsonSerializer.Deserialize<TestingDomainEvent>(json);

            output.Name.Should().Be(input.Name);
            output.Count.Should().Be(input.Count);
            output.CreatedAt.Should().Be(input.CreatedAt);
            output.Id.Should().Be(input.Id);
        }
    }
}
```

### Expected behavior

It seems strange that deserialization works for the `string`, `int` and `DateTime` properties that also have protected setters, but fails for the `Guid` one.

The `Guid` property deserialization does work if you add the `JsonIncludeAttribute` as outlined in #34675.

### Actual behavior

A new value for the `Guid` property seems to be created (not `Guid.Empty`)

### Known Workarounds

Adding the `JsonIncludeAttribute` to the property makes it work

**Comment by Tornhoof** [comment]
It uses your ctor during deserialization.
See
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-6-0

**Comment by TheMagnificent11** [comment]
> It uses your ctor during deserialization. See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-immutability?pivots=dotnet-6-0

Using the following class also gets a unit test failure...

```cs
    public class TestClass
    {
        public TestClass(
            string name,
            int count,
            DateTime createdAt)
        {
            this.Id = Guid.NewGuid();
            this.Name = name;
            this.Count = count;
            this.CreatedAt = createdAt;
        }

        [JsonConstructor]
        protected TestClass() { }

        public Guid Id { get; protected set; }

        public string Name { get; protected set; }

        public int Count { get; protected set; }

        public DateTime CreatedAt { get; protected set; }
    }
```

**Comment by Tornhoof** [comment]
Yes, and that's expected and documented in the link
> The attribute can only be used with public constructors.

**Comment by eiriktsarpalis** [comment]
@TheMagnificent11 does @Tornhoof's response answer your question? As already mentioned, this is by design behavior.

**Comment by TheMagnificent11** [comment]
@eiriktsarpalis  / @Tornhoof , thanks for such quick replies.

I can confirm that making the constructor public makes my unit test pass.

However, in my scenario, I want the public API of my class to force people to use a specific constructor in order to ensure data integrity...I guess it's a bit of a domain-driven design reason.

I would expect the `JsonConstructorAttribute` to behave in a similar way to the `JsonIncludeAttribute`; you're allowing the JSON deserializer access, but not to the public.

**Comment by eiriktsarpalis** [comment]
> However, in my scenario, I want the public API of my class to force people to use a specific constructor in order to ensure data integrity...I guess it's a bit of a domain-driven design reason.

In that particular case, I would recommend using DTOs instead of serializing your domain classes directly. 

> I would expect the JsonConstructorAttribute to behave in a similar way to the JsonIncludeAttribute; you're allowing the JSON deserializer access, but not to the public.

While that might work in the case of reflection-based serialization, it would not be possible to support in the case of source generation. In the future we might consider extending the `JsonIncludeAttribute` (already known to not be supported in source gen) so that it can work with other non-public members specifically for reflection-based serialization.

**Comment by Tornhoof** [comment]
If you just want to prevent users from using that specific ctor is to add the appropriate ``EditorBrowsableAttribute`` and ``ObsoleteAttribute``, afaik there was a Bugfix which hides warnings for Obsolete for the source generator.

**Comment by TheMagnificent11** [comment]
Thanks @eiriktsarpalis / @Tornhoof
