### ISSUE TITLE
No tests run in System.Linq.Expressions.Tests with Debug\Checked runtimes

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#68166]
### Description

Given a Debug or Checked runtime, attempting to run the S.L.E.Tests causes no tests to be selected to run:
```
Discovering: System.Linq.Expressions.Tests (method display = ClassAndMethod, method display options = None)
Discovered: System.Linq.Expressions.Tests (found 0 of 5667 test cases)
=== TEST EXECUTION SUMMARY ===
System.Linq.Expressions.Tests.dll Total: 0
```

### Reproduction Steps

On Windows:
```
build -s clr+libs+libs.tests -c Debug
cd C:\git\MYREPO\artifacts\bin\System.Linq.Expressions.Tests\Debug\net7.0
"C:\git\MYREPO\artifacts\bin\testhost\net7.0-windows-Debug-x64\dotnet.exe" exec --runtimeconfig System.Linq.Expressions.Tests.runtimeconfig.json --depsfile System.Linq.Expressions.Tests.deps.json xunit.console.dll System.Linq.Expressions.Tests.dll -nologo -notrait category=OuterLoop -notrait category=failing
```

### Expected behavior

Tests run on a Debug or Checked build of the runtime, like they do with a Release build.

### Actual behavior

No tests run on Debug and Checked builds of the runtime.

### Regression?

Not known

### Configuration

Windows x64

### Other information

Not sure if they are running in CI since "no Helix data" is apparently shown for successful test runs.

**Comment by joperezr** [comment]
Seems like this is by design:

https://github.com/dotnet/runtime/blob/928bd973ad28cdb2081e1b6922acbc4ece44c660/src/libraries/System.Linq.Expressions/tests/AssemblyInfo.cs#L6

We are skipping the tests when not in Release due to https://github.com/dotnet/runtime/issues/12927

**Comment by steveharter** [comment]
In my case I have a valid case to run a Debug\Checked build since I was getting random failures in those tests (Release build) with a work-in-progress PR and wanted to see if there were Asserts being triggered.

**Comment by joperezr** [comment]
This attribute is applied to the whole assembly, so until that issue gets fixed, no tests will run from the whole assembly in a non-Release coreclr. I'd suggest to delete the AssemblyInfo.cs file locally and manually running only your test to get results.

**Comment by steveharter** [comment]
Closed as a duplicate
