### ISSUE TITLE
Add tests to cross/build-rootfs.sh

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/runtime#6817]
@adityamandaleeka brought it up previously [here](https://github.com/dotnet/coreclr/pull/6348#issuecomment-234024623) and I just fixed another bug in this script (#7643/#7644) so I'm wondering if it's worth adding some tests to ensure intended functionality.

My vote would either be to use [bats](https://github.com/sstephenson/bats), or -- if additional dependencies are a concern -- just a vanilla script with stdout / stderr / exit codes.

I'd be happy to pick this one up myself if it seems valuable!

**Comment by jkoritzinsky** [comment]
The rootfs scripts now live in dotnet/arcade. I'm going to close this for now.
