### ISSUE TITLE
mono minijit x64 test failure: loopinfinally_do.dll exception

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#68187]
mono minijit Pri0 Runtime Tests Run windows x64 release

Example: https://dev.azure.com/dnceng/public/_build/results?buildId=1724655&view=logs&j=fea05fe8-29db-5d00-a4a9-158748ab7a12&t=2e9f2958-4d0a-5332-1dee-76b00780168f&l=104

Failing test:
```
23:10:54.365 Passed test: JIT/Methodical/int64/unsigned/ldsfld_mulovf_do/ldsfld_mulovf_do.dll
23:10:54.365 Running test: JIT/Methodical/eh/finallyexec/loopinfinally_do/loopinfinally_do.dll
Caught an exception
In finally, i = 3
In finally, i = 4
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
```

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch this is blocking CI. PTAL with a high priority.

**Comment by elinor-fung** [comment]
loopinfinally_do is supposed to be excluded from mono runs on Windows:
https://github.com/dotnet/runtime/blob/205632116bd764abfe019564256908202082c9a9/src/tests/issues.targets#L2237-L2239

@trylek @jkoritzinsky could this be related to the merged test work?

**Comment by elinor-fung** [comment]
`KeepAliveBoxOpt` is also running (and failing) even though it should be excluded on mono:
https://github.com/dotnet/runtime/blob/205632116bd764abfe019564256908202082c9a9/src/tests/issues.targets#L1853-L1855

**Comment by trylek** [comment]
I'm taking a look now, for sure it may be related, thanks for the heads-up.

**Comment by trylek** [comment]
@jkoritzinsky - at the first glance this looks like a mismatch between the forward and backward slashes in TestExclusionList. Should we always put forward slashes in the list?

**Comment by jkoritzinsky** [comment]
If that's the issue, then we definitely need to add some normalization. I think changing all of the slashes to be forward slashes (Unix style) would be the easiest.

**Comment by jakobbotsch** [comment]
This does not look codegen related, so reassigning based on above discussion.
