### ISSUE TITLE
RegexSourceGenerator informational diagnostics are not being displayed on VS text editor nor on the console

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#68182]
Seems like a recent change might have broken how our Regex Source generator Informational diagnostics get displayed in Visual Studio. Error and warning diagnostics seem to be displaying correctly, but our informational diagnostic doesn't seem to be working. I have checked and we are correctly calling context.ReportDiagnostic just like we do for the rest of diagnostics and also verified that if I change the diagnostic's severity it does get displayed correctly. This issue is meant to track the investigation and fix for that diagnostic.

**Comment by stephentoub** [comment]
This appears to be fixed now:
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2642209/165367683-24d99a14-11d1-4f60-84da-b95cf2b4b298.png">
(though we should tweak that message as it's not accurate)
