### ISSUE TITLE
[Wasm] Satellite assemblies loading failure

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#68192]
### Description

When a project contains multiple satellite assemblies, invoking `Module.addRunDependency` will fail on duplicate Id, because the file name is not unique enough because of the culture:
https://github.com/dotnet/runtime/blob/c537cc6a45c4c75524ec98f6a8d4c9637438958e/src/mono/wasm/runtime/startup.ts#L470

### Reproduction Steps

Create a project with multiple embedded resources cultures (leading to multiple files with the same name in different paths), then try running the app.

### Expected behavior

The app runs.

### Actual behavior

```
Assertion failed: undefined
abort @ dotnet.js:formatted:7455
assert @ dotnet.js:formatted:6624
addRunDependency @ dotnet.js:formatted:7388
r @ dotnet.js:formatted:2381
await in r (async)
mono_download_assets @ dotnet.js:formatted:2438
mono_wasm_pre_init @ dotnet.js:formatted:2167
await in mono_wasm_pre_init (async)
```

### Regression?

Yes, from net6.

**Comment by pavelsavara** [comment]
Fixed by https://github.com/dotnet/runtime/pull/68195

**Comment by pavelsavara** [comment]
I guess you are compiling it with with `ASSERTIONS` ? 
Otherwise the emscripten ignores the `id` and perhaps that's why we don't see it on unit test.

https://github.com/emscripten-core/emscripten/blob/69acf8f4b49c7dc4a3c3b791c1e615962c58807c/src/preamble.js#L503

**Comment by jeromelaban** [comment]
Indeed, I am running with the assertions enabled (it makes it easier to troubleshoot runtime errors). That could very well be the origin of the issue, not the scheduling of promises.
