### ISSUE TITLE
`double.TryParse` sometimes doesn't parse the dot

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#68200]
This issue is currently blocking the CI in my Tar PR: https://github.com/dotnet/runtime/pull/67883

This issue seems to only happen in the CI. I am unable to repro locally. Here's are some logs showing the issue: https://dev.azure.com/dnceng/public/_build/results?buildId=1725098&view=logs&j=457f7e88-dfa2-5bd9-f871-fdf124c2477d&t=bfe52dfb-2099-5c7f-ee52-70a1d81c544e&l=356

My tar code reads the `mtime`, `atime` and `ctime` fields of a tar entry. These fields, which represent timestamps, are stored as `double` numbers in the PAX format.

My code reads the bytes, then it converts them to an ASCII string, and then passes that string to the `double.TryParse` method. If the method returns `true`, then it passes the resulting `double` number to `DateTimeOffset` to generate a timestamp.

But `DateTimeOffset` is throwing an exception because the number I'm passing is way larger than `MaxTicks`, its upper limit.

The root cause: `double.TryParse` is not adding the dot, causing the returned number to be HUGE. I found this by catching the exception thrown by `DateTimeOffset`, then rethrowing it with a formatted message that contained the original string value and the resulting double value. Example of the exception:

string I'm passing: '1649971879.992326', resulting double: '1649971879992326'

Note: I wondered if the dot was an unexpected character, but it is not: The hex value of the ASCII character is 2E, the expected one. See the table: https://www.asciitable.com/

Example of code:
```cs
if (!double.TryParse(str, out double result)) // This returns true, and the out number does not have a dot
{
    return false;
}
```

Thanks to @tarekgh for his help investigating this.

@tannergooding @dakersnar @jeffhandley

**Comment by jeffhandley** [comment]
On a quick glance, it looks like the test that failed is in the `ES` culture. What might be happening is that in the `ES` culture, `double.TryParse` is expecting the decimal separator to be `,` instead of `.`. Since you're not reading user data, but instead reading data from the PAX format, I think you'd be able to use `InvariantCulture` for the `double.TryParse` call--assuming the PAX format spec is culture-unaware.

**Comment by carlossanlop** [comment]
PAX only mentions that the extended attribute strings are expected to be in UTF8.

So you're saying that the problem might be in the culture used by double? Could the issue maybe come from the code that converts the raw bytes to string? I ask because I'm using `Encoding.UTF8.GetString(bytes)`, then I pass that string to `double.TryParse`.

**Comment by carlossanlop** [comment]
I'll try the following:

```
double.TryParse(str, NumberStyles.Any, CultureInfo.InvariantCulture, out double number)
```

**Comment by danmoseley** [comment]
All parsing operations should be culture invariant unless the data is expected to be culture specific in which case it should be parsed using whatever that culture is.

**Comment by Joe4evr** [comment]
This is why [CA1305](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1305) exists and should be enabled. 🙃

**Comment by tarekgh** [comment]
Any more actions needed on this issue? I think we can close it now.
