### ISSUE TITLE
Inconsistency in root .editorconfig with published coding style.

### ISSUE THREAD

**Issue by mpsbauer** [dotnet/runtime#68238]
### Description

In the [coding style](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md) on guideline 10 it states that 

"We only use `var` when the type is explicitly named on the right-hand side..."

Later on it mentions

"An EditorConfig file (.editorconfig) has been provided at the root of the runtime repository, enabling C# auto-formatting conforming to the above guidelines."

However in the supplied [.editorconfig](https://github.com/dotnet/runtime/blob/main/.editorconfig#L49) it has [csharp_style_var_when_type_is_apparent ](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008#csharp_style_var_when_type_is_apparent )set to `false`. This seems to contradict the published guidelines. 

Our goal is to align on a "standard" coding-style to avoid the inevitable war of opinions when trying to create your own. 
It would help  our company if this ambiguity was eliminated. Thank you.

### Reproduction Steps

Use supplied .editorconfig in your solution

### Expected behavior

It would adhere to the published coding-style guidles.

### Actual behavior

It doesn't not adhere to the published coding-style guidelines. At least the use of `var` is different.

### Known Workarounds

We can (and will) update our own .editorconfig but think the dotnet supplied one ought to be updated as well.

**Comment by mpsbauer** [comment]
I can not add a label but maybe @danmoseley can, I believe this would fall under area-Meta. @dotnot/area-meta

**Comment by stephentoub** [comment]
Our guidelines are that we _allow_ var to be used when the type is mentioned on the right-hand side. We don't _prefer_ or _require that, however. It guideline is really and when var should never be used, not where it should be used.

**Comment by mpsbauer** [comment]
Fair enough, feels like a subtle difference. My problem might be more with ReSharper then. It's default code clean up mechanism does not seem to appreciate the subtlety, and will either replace `var` with the type or vice-versa, not simply allow either. Thanks for the quick follow up.

**Comment by danmoseley** [comment]
Feel free to offer a PR to clarify the wording.
