### ISSUE TITLE
[API Proposal]: Move APIs for generated marshalling to different namespace - System.Runtime.Marshalling

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#68248]
### Background and motivation

For .NET 7, we added various APIs used for p/invoke source generation:
- https://github.com/dotnet/runtime/issues/46822.
- https://github.com/dotnet/runtime/issues/46838
- https://github.com/dotnet/runtime/issues/66121
- https://github.com/dotnet/runtime/issues/66623

These were all added to the `System.Runtime.InteropServices` namespace. We are proposing moving them to a separate namespace for clearer separation and discovery.

### API Proposal

```diff
-namespace System.Runtime.InteropServices
+namespace System.Runtime.Marshalling
{
    public sealed class LibraryImportAttribute : Attribute { ... }
    public enum StringMarshalling { ... }

    public sealed class NativeMarshallingAttribute : Attribute { ... ]
    public sealed class MarshalUsingAttribute : Attribute { ... }
    public sealed class CustomTypeMarshallerAttribute : Attribute { ... }

    public enum CustomTypeMarshallerDirection { ... }
    public enum CustomTypeMarshallerFeatures { ... ]
    public enum CustomTypeMarshallerKind { ... }

    public unsafe ref struct AnsiStringMarshaller { ... }
    public unsafe ref struct ArrayMarshaller { ... }
    public unsafe ref struct PointerArrayMarshaller { ... }
    public unsafe ref struct Utf16StringMarshaller { ... }
    public unsafe ref struct Utf8StringMarshaller { ... }
}
```

### API Usage

```C#
using System.Runtime.Marshalling;

[LibraryImport("NativeLib", StringMarshallingCustomType = typeof(AnsiStringMarshaller))]
internal static partial string Method(string s1, string s2);
```

### Alternative Designs

- Leave `LibraryImportAttribute` (the triggering attribute for p/invoke source generation) in `System.Runtime.InteropServices` and only move the new APIs (custom type marshalling attributes, marshaller implementations) that are directly related to marshalling
- Use a sub-namespace under `System.Runtime.InteropServices` - for example, `System.Runtime.InteropServices.Marshalling`

### Risks

This would be a breaking change between Preview 4 and 5. The new APIs were just exposed in Preview 4 and the source generator itself will not be included for public use until Preview 5. so we do not expect this to be very impactful.

**Comment by elinor-fung** [comment]
@AaronRobinsonMSFT @jkoritzinsky I know when we talked before, I was into moving everything - including `LibraryImportAttribute`, but I'm actually not sure I like that now. As the triggering attribute, it is not directly for marshalling, so I'm not sure it really fits with the rest.

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Agreed on all accounts. I voiced a similar concern to @jkoritzinsky previously. I think we should have a conversation with the API review team and see what some of the API experts think of the concerns.

**Comment by terrajobst** [comment]
* We'd prefer putting these under `InteropServices`

```C#
namespace System.Runtime.InteropServices
{
    public sealed class LibraryImportAttribute : Attribute { /*...*/ }
    public enum StringMarshalling { /*...*/ }
}

// Was previously also approved for System.Runtime.InteropServices

namespace System.Runtime.InteropServices.Marshalling
{
    public sealed class NativeMarshallingAttribute : Attribute { /*...*/ }
    public sealed class MarshalUsingAttribute : Attribute { /*...*/ }
    public sealed class CustomTypeMarshallerAttribute : Attribute { /*...*/ }

    public enum CustomTypeMarshallerDirection { /*...*/ }
    public enum CustomTypeMarshallerFeatures { /*...*/ }
    public enum CustomTypeMarshallerKind { /*...*/ }

    public unsafe ref struct AnsiStringMarshaller { /*...*/ }
    public unsafe ref struct ArrayMarshaller { /*...*/ }
    public unsafe ref struct PointerArrayMarshaller { /*...*/ }
    public unsafe ref struct Utf16StringMarshaller { /*...*/ }
    public unsafe ref struct Utf8StringMarshaller { /*...*/ }
}
```
