### ISSUE TITLE
System.Diagnostics.Process with CreateNoWindow does not redirect stdout/stderr to parent process

### ISSUE THREAD

**Issue by mxschmitt** [dotnet/runtime#68259]
### Description

When using `System.Diagnostics.Process` with `CreateNoWindow = true` the output does not get redirected to the parent process. It will end up in no output.

The [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=net-6.0) don't say anything about this behaviour, thats why I'm opening this issue and `CreateNoWindow` changes the behaviour if stdout/err gets redirected or not.

### Reproduction Steps

```cs
using System.Diagnostics;

if (args.Length >= 1 && args[0] == "--start-process")
{
    var currentExecutable = Environment.ProcessPath;
    if (currentExecutable == null)
    {
        Console.Error.WriteLine("Could not get current executable path");
        return;
    }
    var playwrightStartInfo = new ProcessStartInfo(currentExecutable)
    {
        UseShellExecute = false,
        RedirectStandardError = false,
        RedirectStandardOutput = false,
        CreateNoWindow = true,
    };

    using var pwProcess = new Process()
    {
        StartInfo = playwrightStartInfo,
    };

    pwProcess.Start();
    pwProcess.WaitForExit();
}
else
{
    Console.WriteLine("Hello stdout!");
    Console.Error.WriteLine("Hello stderr!");
}
```

Run it with `./bin/Debug/net6.0/dotnetrepro.exe --start-process`.

### Expected behavior

`Hello stderr!` and `Hello stdout!` are getting printed.

### Actual behavior

They get not printed.

### Known Workarounds

Remove `CreateNoWindow = true`.

or:

Using `RedirectStandardError = true` and `RedirectStandardOutput = true` and manually redirecting it to the parent stdout/stderr.

### Configuration

I can only reproduce it on Windows 10 + 11 amd64.

### Other information

```
PS C:\Users\maxsc\Desktop\dotnet-process-redirect-issue> dotnet --list-sdks
6.0.102 [C:\Program Files\dotnet\sdk]
```

**Comment by Jozkee** [comment]
From https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
> The process is a console application that is being run without a console window. Therefore, the console handle for the application is not set.

There's no console to write to when the option is set. Expecting output from Console.WriteLine in this case doesn't seem reasonable. What are you trying to achieve?

**Comment by mxschmitt** [comment]
> From https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags
> 
> > The process is a console application that is being run without a console window. Therefore, the console handle for the application is not set.
> 
> There's no console to write to when the option is set. Expecting output from Console.WriteLine in this case doesn't seem reasonable. What are you trying to achieve?

Interesting! The use-case of it is that we spawn a Program in .NET, which internally does wrap another program as a subprocess. There we want to inherit all the stdout/stderr. This is working as expected when setting RedirectStandardOutput=false, except that a dedicated window is shown when the user is trying to call this Program API inside their C# code (downstream issue: https://github.com/microsoft/playwright-dotnet/issues/2103). So we had then three options:

a) RedirectStandardOutput=true -> we need to manually redirect them and it has side effects (aka Node.js isTTY = false)
b) RedirectStandardOutput=false CreateNoWindow=false -> a dedicated window gets shown in some edge cases (https://github.com/microsoft/playwright-dotnet/issues/2103)
c) RedirectStandardOutput=false CreateNoWindow=true -> no output gets shown anymore, thats what the bug is about.

Ideal solution would be c) in my opinion. Or how do you see it?

**Comment by rhuijben** [comment]
> Ideal solution would be c) in my opinion. Or how do you see it?

That would be a completely breaking change if you just expect to run the program, handing over the user interaction until the subprocess finishes.

Your usecase somehow needs hooking up stout and/or studeer to a null device, if you want to go the output nowhere.

**Comment by Jozkee** [comment]
I agree with @rhuijben, you need to use the StandardOutput here for the reasons previously stated and I don't think we will be changing the behavior for this.

We currently added support for passing `WindowStyle` with `UseShellExecute = false` on https://github.com/dotnet/runtime/pull/82662 which means you can try `playwrightStartInfo.WindowStyle = ProcessWindowStyle.Hidden` but I'm unsure if that may solve your issue.
