### ISSUE TITLE
BinaryData.Empty.ToString throws ArgumentNullException

### ISSUE THREAD

**Issue by amis92** [dotnet/runtime#68262]
### Description

Using package `System.Memory.Data` v6+, `System.BinaryData.ToString()` called on an instance with zero-length data (`BinaryData.FromStream(Stream.Null)`, `BinaryData.FromString(string.Empty)`, `BinaryData.FromBytes(Array.Empty<byte>())` etc.) throws `System.ArgumentNullException`.

### Reproduction Steps

```csharp
BinaryData.Empty.ToString()
```

### Expected behavior

Method should return empty string, as it did/does in package v1 (`1.0.0`, `1.0.1`, `1.0.2`).
The expression `BinaryData.FromString(data).ToString() == data` where `data` is any valid non-null `string` instance should be true.

### Actual behavior

`ArgumentNullException` is thrown:

```
System.ArgumentNullException: System.ArgumentNullException: Array cannot be null. (Parameter 'bytes')
  + System.Text.Encoding.GetString(System.Byte*, int)
  + System.BinaryData.ToString()
```

### Regression?

The method does not throw and returns an empty string using `System.Memory.Data` v1.

### Other information

The [original implementation was](https://www.fuget.org/packages/System.Memory.Data/1.0.2/lib/netstandard2.0/System.Memory.Data.dll/System/BinaryData?code=true):

```csharp
        public override string ToString()
        {
            if (MemoryMarshal.TryGetArray(_bytes, out ArraySegment<byte> segment))
                return Encoding.UTF8.GetString(segment.Array, segment.Offset, segment.Count);
            return Encoding.UTF8.GetString(_bytes.ToArray());
        }
```

Now it uses `byte*` which seems to be the problem (empty Span casts as a null ref):

https://github.com/dotnet/runtime/blob/7ab6c18428cf7b102beb126b55bbfdb0a3878091/src/libraries/System.Memory.Data/src/System/BinaryData.cs#L190-L197

**Comment by adamsitnik** [comment]
@amis92 @kasperk81 would any of you be interested in sending a PR with a fix?

**Comment by amis92** [comment]
Any chance for this to be backported as a bugfix into 6.x packages, or is it too much of a breaking-unbreaking thing? I've found out because one of my dependencies pulled in higher version and so I couldn't really downgrade and had to make a workaround, and with 6.0 being LTS, this bug will keep being there in many places.
