### ISSUE TITLE
Text.Json – Deserialization of object does not convert empty or whitespace string to null

### ISSUE THREAD

**Issue by KillerBoogie** [dotnet/runtime#68263]
### Description

Text.Json should by default convert an empty or whitespace string to null. It does not work for me. Has this beahvior been changed?

### Reproduction Steps

```
public record FullNameDTO(
     string GivenName,
     string? MiddleName,
     string? FamilyName
 );

const string jsonFullName = "{\"GivenName\":\"Testperson\",\"MiddleName\":\"   \",\"FamilyName\":\"\"}";

FullNameDTO? dtoPerson = JsonSerializer.Deserialize<FullNameDTO> (jsonFullName);
dtoPerson?.MiddleName == "   "; // true
dtoPerson?.FamilyName == ""; // true
```

### Expected behavior

values of "" (empty string) or "   " (white space string) in JSON input should be converted to null

### Actual behavior

empty strings and white space strings are not converted to null

### Configuration

.NET 6

**Comment by eiriktsarpalis** [comment]
I'm not reproducing the behavior as you are describing it:
```C#
using System;
using System.Text.Json;

const string json = "{\"FullName\":{\"GivenName\":\"Testperson\",\"MiddleName\":\"   \",\"FamilyName\":\"\"}}";

FullNameDTO dtoFullName = JsonSerializer.Deserialize<FullNameDTO>(json)!;
Console.WriteLine(dtoFullName.MiddleName == null); // prints true, since there's no MiddleName property in the root-level JSON object

PersonDTO dtoPerson = JsonSerializer.Deserialize<PersonDTO>(json)!;
Console.WriteLine(dtoPerson.FullName.MiddleName == null); // prints false, since the nested MiddleName property has been deserialized as expected

public record FullNameDTO(
    string GivenName,
    string? MiddleName,
    string? FamilyName
 );

public record PersonDTO(
    FullNameDTO FullName
);
```
This is expected though, the shape of the JSON document doesn't match the contract for `FullNameDTO` but does match the cotnract for `PersonDTO`.

**Comment by KillerBoogie** [comment]
Erik, yes that was my fault. I'm sorry. I corrected the post.

According to what I have found, the default behavior of Text.json is to convert empty and white space strings to null. I found questions where people wanted another behaviour. Did that behaviour change or is there a setting that will convert to null?

**Comment by eiriktsarpalis** [comment]
> According to what I have found, the default behavior of Text.json is to convert empty and white space strings to null. 

To my knowledge we've never supported this. Could you share a link to the source claiming this?

**Comment by KillerBoogie** [comment]
I guess I misunderstood https://github.com/dotnet/runtime/issues/34310
Is there an option to convert empty strings to null? I'm working with nulable types and therefore valid inputs are either null or have a string with length >0. I want to tolerate empty strings from the client and convert them to nulls to be handled correctly in the domain layer.

**Comment by eiriktsarpalis** [comment]
> I guess I misunderstood https://github.com/dotnet/runtime/issues/34310

#34310 refers to deserializing JSON from an empty string, i.e. something like `JsonSerializer.Deserialize<FullNameDTO>("");` It is perfectly valid for string literals within a JSON document to be empty or containing whitespace that doesn't require escaping.

> Is there an option to convert empty strings to null?

Not out of the box, but you might be able to write a custom string converter that does this, something like
```C#
public class MyStringConverter : JsonConverter<string>
{
    public override string? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string? value = reader.GetString();
        return string.IsNullOrWhiteSpace(value) ? null : value;
    }

    public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value);
    }
}
```

**Comment by KillerBoogie** [comment]
Thank you! That helps!
