### ISSUE TITLE
C++ cli reference .net 5/6 which reference .net standard2+ not working on Windows

### ISSUE THREAD

**Issue by kzhui125** [dotnet/runtime#68261]
### Description

C++ cli reference .net 5/6 dll1, and dll1  reference .net standard2+ dll2.
This case doesn't work now.

So I can't use many packages like Grpc.AspNetCore(which use Grpc.Core.Api and is .netstandard)

**Comment by AaronRobinsonMSFT** [comment]
@kzhui125 When you say "not working", what does that mean? Is there a crash? Is there an error message? Would it be possible to share a repro solution? Was this ever working for you or is this a new port to .NET 5/6?

**Comment by kzhui125** [comment]
@AaronRobinsonMSFT I get "Could not load file or assembly" error.

If I replace the .net standard dll to .net 5/6 dll, then it works.

I will try to make a repro solution later.
