### ISSUE TITLE
Support for Unicode Case Folding from SpecialCasing.txt

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#68287]
Does .NET support the special cases defined in https://www.unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt at all?

For example, being able to test `"ẞ"` (german scharfes S) being equal to `"ss"` or `"SS"`?

I just see one mention of it in a test:
https://github.com/dotnet/runtime/blob/7fd3c9293cb17485a12d942992c68b9b4e12649e/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs#L270-L274

---

This came up since the [CommonMark](https://commonmark.org/) spec (the Markdown spec used by GH, [Markdig](https://github.com/xoofx/markdig) ...) added a new rule in the [latest 0.30 specification](https://spec.commonmark.org/0.30/):
- [Example 539](https://spec.commonmark.org/0.30/#example-539)

```md
[ẞ]

[SS]: /url
```

Which says that unicode case folding (case-*in*sensitive) should be used when matching the link label to the link reference definition.

**Comment by tarekgh** [comment]
@MihaZupan you can achieve that today by doing:

```C#
CultureInfo.CurrentCulture.CompareInfo.Compare("ẞ", "SS", CompareOptions.IgnoreCase | CompareOptions.IgnoreNonSpace)
```

**Comment by MihaZupan** [comment]
Thanks Tarek!
