### ISSUE TITLE
System.Text.Json is unable to deserialize FluentValidation.Results.ValidationResult

### ISSUE THREAD

**Issue by Arclight3** [dotnet/runtime#68280]
### Description

System.Text.Json is unable to deserialize FluentValidation.Results.ValidationResult, while Newtonsoft.Json is able to do it.

### Reproduction Steps

Check this code in .NET 6:

```C#
var validationResult = new ValidationResult
{
    Errors = { new ValidationFailure("MyProperty", "Invalid MyProperty") }
};
// System.Text.Json
var serialized = JsonSerializer.Serialize(validationResult);
var deserialized = JsonSerializer.Deserialize<ValidationResult>(serialized);

// Newtonsoft.Json
var serialized2 = JsonConvert.SerializeObject(validationResult, Formatting.Indented);
var deserialized2 = JsonConvert.DeserializeObject<ValidationResult>(serialized2);
```

The _deserialized_ variable contains a ValidationResult object with IsValid = true, and 0 Errors.
The _deserialized2_ variable contains a ValidationResult object with IsValid = false, and 1 Error.

The serialization operation produces an identical json string for both libraries, but the System.Text.Json fails to deserialize it back to a ValidationResult object.

### Expected behavior

The Error properties should be deserialized. 

### Actual behavior

The Error properties are not deserialized.

### Regression?

I am not sure. I only tested it in .NET 6 (LTS).

### Known Workarounds

Using Newtonsoft Json instead...

### Configuration

OS: Windows 10
.NET version: 6.0.202
Architecture: x64

### Other information

I found this old issue on the FluentValidation repo: https://github.com/FluentValidation/FluentValidation/issues/719.
They described there what was the issue when no library was able to deserialize from json to ValidationResult, but that issue was fixed and Newtonsoft Json works properly.

**Comment by gregsdennis** [comment]
I wonder if this is more something that FluentValidation should provide.  I believe they would need to provide a `JsonConverter` for it.

**Comment by eiriktsarpalis** [comment]
I would recommend filing an issue with the FluentValidation repo. It might be that the type is defining a converter for Json.NET and not STJ or that the type relies on a deserialization convention not currently supported by STJ. If it turns out to be the latter, it might be worth filing a subsequent issue requesting that we support that specific convention.
