### ISSUE TITLE
[API Proposal]: Support ref fields in System.Reflection.Metadata.Ecma335.BlobEncoder

### ISSUE THREAD

**Issue by cston** [dotnet/runtime#68309]
### Background and motivation

Provide methods in `System.Reflection.Metadata.Ecma335.BlobEncoder` to more directly support emitting ref fields, consistent with the corresponding APIs provided for emitting ref parameters and ref locals.

### API Proposal

Provide a `FieldTypeEncoder` type similar to `ParameterTypeEncoder` and `LocalVariableTypeEncoder`.
```C#
namespace System.Reflection.Metadata.Ecma335
{
    public readonly struct BlobEncoder
    {
        public FieldTypeEncoder FieldTypeEncoder();
    }

    public readonly struct FieldTypeEncoder
    {
        public BlobBuilder Builder { get; }

        public FieldTypeEncoder(BlobBuilder builder);

        public CustomModifiersEncoder CustomModifiers();

        public SignatureTypeEncoder Type(bool isByRef = false);

        public void TypedReference();
    }
}
```

### API Usage

```C#
var blobBuilder = new BlobBuilder();
var encoder = new BlobEncoder(blobBuilder);

var fieldEncoder = encoder.FieldTypeEncoder();

// Ref custom modifiers: modopt(object)
var customModifiersEncoder = fieldEncoder.CustomModifiers();
customModifiersEncoder.AddModifier(MetadataTokens.TypeReferenceHandle(2), isOptional: true);

// Type: int&
var typeEncoder = fieldEncoder.Type(isByRef: true);
typeEncoder.PrimitiveType(PrimitiveTypeCode.Int32);
```

### Alternative Designs

The alternative is the existing API which requires emitting `SignatureTypeCode.ByReference` and creating a `CustomModifierEncoder` explicitly. The existing API is sufficient, but inconsistent with the support for ref parameters and ref locals. 

Using the existing API:
```C#
var blobBuilder = new BlobBuilder();
var encoder = new BlobEncoder(blobBuilder);

var typeEncoder = encoder.FieldSignature();

// Ref custom modifiers: modopt(object)
var customModifiersEncoder = new CustomModifiersEncoder(blobBuilder);
customModifiersEncoder.AddModifier(MetadataTokens.TypeReferenceHandle(2), isOptional: true);

// Type: int&
typeEncoder.Builder.WriteByte((byte)SignatureTypeCode.ByReference);
typeEncoder.PrimitiveType(PrimitiveTypeCode.Int32);
```

### Risks

`BlobEncoder` already includes a `FieldSignature` method that returns an encoder for a field type, so having two distinct field encoder methods may be confusing.
```C#
    public readonly struct BlobEncoder
    {
        public SignatureTypeEncoder FieldSignature();
        public FieldTypeEncoder FieldTypeEncoder();
    }
```

**Comment by cston** [comment]
cc @jaredpar, @tmat

**Comment by AaronRobinsonMSFT** [comment]
@cston Will the following be needed with this new API. It is in the usage example but is also noted in the Alternative design in a manner that implies it wouldn't be needed if this new API was adopted.

```csharp
// Ref custom modifiers: modopt(object)
var customModifiersEncoder = fieldEncoder.CustomModifiers();
customModifiersEncoder.AddModifier(MetadataTokens.TypeReferenceHandle(2), isOptional: true);
```

**Comment by cston** [comment]
> A new instance is being created rather than using the existing one in the `fieldEncoder` instance.

Actually, in both examples an instance of `CustomModifiersEncoder` is created. The only difference is that the proposed `FieldTypeEncoder` type includes a `CustomModifiers()` method that makes it slightly more obvious how to obtain a `CustomModifiersEncoder`. 

The overall difference between use of the existing API and the proposed API is small. It's perhaps just a question of whether the API for emitting fields should be aligned with the existing APIs for locals and parameters.

**Comment by terrajobst** [comment]
* Let's call the method `BlobEncoder` just `Field`

```C#
namespace System.Reflection.Metadata.Ecma335;

public partial readonly struct BlobEncoder
{
    public FieldTypeEncoder Field();
}

public readonly struct FieldTypeEncoder
{
    public BlobBuilder Builder { get; }

    public FieldTypeEncoder(BlobBuilder builder);
    public CustomModifiersEncoder CustomModifiers();
    public SignatureTypeEncoder Type(bool isByRef = false);
    public void TypedReference();
}
```

**Comment by teo-tsirpanis** [comment]
I'm working on this.

**Comment by AaronRobinsonMSFT** [comment]
@teo-tsirpanis Please wait for @cston to confirm he doesn't already have an implementation. Work to support `ref` fields is close to complete and it is possible the work has been done just not posted yet.

**Comment by cston** [comment]
> Please wait for @cston to confirm he doesn't already have an implementation.

I have not implemented this. The compiler is currently using the existing API.

**Comment by AaronRobinsonMSFT** [comment]
Thanks @cston. @teo-tsirpanis Looking forward to the PR. Thanks.
