### ISSUE TITLE
Unable to assign values to struct properties

### ISSUE THREAD

**Issue by NiubilityOptimus** [dotnet/runtime#68316]
### Description

such like my title,I'm not good at English and the problems that may be described seem a bit strenuous and I'm sorry

### Reproduction Steps

I'm not sure if there's a problem with my comprehension or a bug with sdk, but I don't think it's my way of writing that's wrong。

my code like this.

the first struct 
`struct Packet1 : IProtocol{
   private int _dataNum;
        public int DataNum { get { return _dataNum; } set { _dataNum = value; } }
 ctor(....)
}`

`struct Packet2 : IProtocol{
   private Packet1 _packet1;
 public Packet2(Packet1 packet1){
   _packet1 = packet1;
 }
public bool Method(){
  while(condition){
int val = 'a value come from other palce, per while the value must +1';
  if(_packet1.DataNum!=val) //if _packet.DataNum = val 
 return false;
}
_packet1.DataNum=val+1;//while break point here,the '_paket1.DataNum' really become (val+1),but continu while(condition)  '_packet1.DataNum' become 'val' again
}
}`

### Expected behavior

packet1.DataNum = val +1 

### Actual behavior

packet1.DataNum = val

### Regression?

.net 6.0.4

**Comment by NiubilityOptimus** [comment]
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Comment by NiubilityOptimus** [comment]
> I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

sorry，i don't know how to add area lable

**Comment by Joe4evr** [comment]
What you're seeing is the basic fact that structs are copied *by value* (meaning in its entirety) when passed to other methods, so any mutations inside of that method are only visible to that method because the method only works on a full copy of what it was given, not the original instance that was made outside of the method call. This behavior around structs is why you should always consider to make your structs immutable where possible, since then your method can't make any changes in the first place.

To solve this, you can either:
1. (Easy) Make your type a `class` instead of a struct. That will give you the semantics you seek by default (and seeing that you're implementing some interface on your type, it'll avoid you the cost of value type boxing in cases), or
2. (Advanced) Change your method such that your parameter is passed by `ref`, which means that any changes inside will also be visible outside, but this also comes with other considerations (such as that it allows re-assigning the variable entirely and that will be visible)

**Comment by NiubilityOptimus** [comment]
> What you're seeing is the basic fact that structs are copied _by value_ (meaning in its entirety) when passed to other methods, so any mutations inside of that method are only visible to that method because the method only works on a full copy of what it was given, not the original instance that was made outside of the method call. This behavior around structs is why you should always consider to make your structs immutable where possible, since then your method can't make any changes in the first place.
> 
> To solve this, you can either:
> 
> 1. (Easy) Make your type a `class` instead of a struct. That will give you the semantics you seek by default (and seeing that you're implementing some interface on your type, it'll avoid you the cost of value type boxing in cases), or
> 2. (Advanced) Change your method such that your parameter is passed by `ref`, which means that any changes inside will also be visible outside, but this also comes with other considerations (such as that it allows re-assigning the variable entirely and that will be visible)

thanks,Changing the struct to a class does solve this problem, but I don't think it's a good idea, so I'm using “ref”, but the compiler reminds “ref struct” that it can't inherit interface

**Comment by NiubilityOptimus** [comment]
> > What you're seeing is the basic fact that structs are copied _by value_ (meaning in its entirety) when passed to other methods, so any mutations inside of that method are only visible to that method because the method only works on a full copy of what it was given, not the original instance that was made outside of the method call. This behavior around structs is why you should always consider to make your structs immutable where possible, since then your method can't make any changes in the first place.
> > To solve this, you can either:
> > 
> > 1. (Easy) Make your type a  instead of a struct. That will give you the semantics you seek by default (and seeing that you're implementing some interface on your type, it'll avoid you the cost of value type boxing in cases), or`class`
> > 2. (Advanced) Change your method such that your parameter is passed by , which means that any changes inside will also be visible outside, but this also comes with other considerations (such as that it allows re-assigning the variable entirely and that will be visible)`ref`
> 
> thanks,Changing the struct to a class does solve this problem, but I don't think it's a good idea, so I'm using “ref”, but the compiler reminds “ref struct” that it can't inherit interface

I used structs because I overridden the operators and I thought using structs would improve performance。
`[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator Packet1?(byte[] buffer)
        {
            Packet1 f = new();
            return FromArray(buffer, f);
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator byte[](Packet1 f)
        {
            return GetBytes(f);
        }`

**Comment by huoyaoyuan** [comment]
Generally, mutable structs can cause a lot of problems. Shadow copying is a commonly seen one.

An easy solution without breaking a lot is to use C# 10 `record struct` and `with` expression.

**Comment by ericstj** [comment]
@tannergooding  might have some suggestions here.

> I used structs because I overridden the operators and I thought using structs would improve performance。

Not clear what performance you're looking for.  You might be able to get that by sealing the class.

I believe the original question has been answered - mutating fields on a struct passed by value will not affect the original value.  Let us know if you have any further questions.

**Comment by NiubilityOptimus** [comment]
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Comment by NiubilityOptimus** [comment]
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.

**Comment by NiubilityOptimus** [comment]
Dear Sir or Miss.
This is an e-mail from Johnnie' QQ Mail.Thank you for your E-mail.I apologize that I am unable to respond to you immediately . I will get back to you as soon as I return.
