### ISSUE TITLE
aspnetcore application launches very slowly with 180G nfs volume when the nfs mounted to application folder

### ISSUE THREAD

**Issue by xiaohui-gsv** [dotnet/runtime#68322]
### Steps to Reproduce
1. Having an NFS (aws EFS) with 180G files
2. Mount to Ubuntu 20.04 with below options
```
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport xxx.xxx.xxx.xxx:/ /home/ubuntu/docker-compose/BinaryObjects
```
3. Launch the asp.net sample with below docker-compose
```
services:
    test:
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
            - "8000:80"
        volumes:
            - "/home/ubuntu/docker-compose/BinaryObjects:/app/BinaryObjects/"
```
4. The dotnet application launches very slowly, it takes about 5-6 minutes to startup. please refer to the below screenshot, it stays in `Attaching to docker-compose_test_1` for 5-6 minutes, but in the meantime, I can access into the docker container, that's to say the docker container is upped, but the dotnet application doesn't.
![image](https://user-images.githubusercontent.com/38554198/163801218-da62f5cf-90ea-4c27-9151-c20001cde190.png)
If I remove the volumes section in docker-compose.yml, the dotnet app can start up whthin seconds. 
I also find that the larger the NFS, the slower the startup. If the NFS has 10G files, the dotnet application can start up within one minute.

My original application is based on .net core 3.1, it starts up slowly with a large NFS volume in docker container, so I use the `mcr.microsoft.com/dotnet/samples:aspnetapp` to do the testing, it is slow as well. 
If I use the `busybox` image instead, it starts up immediately, so I think it is the issue related to dotnet image.

### Other Information
My nfs (aws EFS) is mounted to `/home/ubuntu/docker-compose/BinaryObjects`
![image](https://user-images.githubusercontent.com/38554198/163795896-4bc9cebb-c7b2-47f9-8e89-fc4a4db0b4d4.png)
My OS version
![image](https://user-images.githubusercontent.com/38554198/163802708-491b9a4e-50aa-45a4-8b96-faa2b73f40d2.png)

### Output of `docker version`

```
Docker version 20.10.14, build a224086
```
```
docker-compose version 1.29.2, build 5becea4c
```

### Output of `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-1021-aws
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.57GiB
 Name: ip-xxx.xxx.xxx.xxx
 ID: UMXO:DCWB:RJOI:UMFF:5KQL:LGMU:QIBS:6ZI2:KQNY:BPIR:EY75:EMKB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: doyoukare
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by tmds** [comment]
> Seems like the dotnet runtime will scan all the files in the application folder before launching the application.

The Host recursively goes through the content root to be able to detect changes for `reloadOnChange` configuration.

**Comment by tmds** [comment]
The difference you see between the container images may be related to `DOTNET_USE_POLLING_FILE_WATCHER` not being set in some images: https://github.com/dotnet/dotnet-docker/issues/3546.

**Comment by xiaohui-gsv** [comment]
> > Seems like the dotnet runtime will scan all the files in the application folder before launching the application.
> 
> The Host recursively goes through the content root to be able to detect changes for `reloadOnChange` configuration.

That's reasonable, so the `reloadOnChange` configuration will affect all the files, not only the appsettings.json files, right?

**Comment by xiaohui-gsv** [comment]
> The difference you see between the container images may be related to `DOTNET_USE_POLLING_FILE_WATCHER` not being set in some images: [dotnet/dotnet-docker#3546](https://github.com/dotnet/dotnet-docker/issues/3546).
Ok, thank you.
Go through the [dotnet/dotnet-docker#3546](https://github.com/dotnet/dotnet-docker/issues/3546) issue, it seems like `DOTNET_USE_POLLING_FILE_WATCHER` won't be set to true before .net 7, but the sample program is based on .net 6. that's weird.

**Comment by mthalman** [comment]
@xiaohui-gsv - Can you confirm that setting `DOTNET_USE_POLLING_FILE_WATCHER` fixes this issue? You could test by building your own image based on the sample:

```
FROM mcr.microsoft.com/dotnet/samples:aspnetapp
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
```

**Comment by xiaohui-gsv** [comment]
@mthalman Yes, I just tried, it works, the dotnet app can startup immediately with the NFS mounted to the application folder.  Thank you so much. 
![image](https://user-images.githubusercontent.com/38554198/165278907-409d93b9-4ff6-4296-98ef-57eb01bbc4f1.png)

**Comment by agocke** [comment]
Thanks -- looks like this is part of `dotnet watch` functionality, and it looks like you figured out a workaround. I'm going to close this as resolved for now.
