### ISSUE TITLE
Environment.GetFolderPath(Environment.SpecialFolder.MyVideos) returns empty string in OSX

### ISSUE THREAD

**Issue by nazar322** [dotnet/runtime#68323]
### Description

It returns an empty string on macOS Monterey running under .NET core 5.
My Electron.NET app runs under .NET Core 5.
It used to work well on the previous versions of OSX, now it returns an empty string.
Environment.GetFolderPath(Environment.SpecialFolder.MyMusic) returns correct path.

### Reproduction Steps

Call the API.

### Expected behavior

Return "/Users/USERNAME/Movies"

### Actual behavior

Returns an empty string

### Configuration

- Microsoft.NETCore.App 5.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
- macOS Monterey 12.1
- osx.12-x64

**Comment by tannergooding** [comment]
This is basically the same boat as https://github.com/dotnet/runtime/issues/63214 and https://github.com/dotnet/runtime/issues/40353

**Comment by nazar322** [comment]
It used to work on Big Sur 11.6.
Actually, I'm installing Big Sur and Catalina to see if it's going to work there like it used to.
