### ISSUE TITLE
[Analyzer Proposal]: Convert argument null checks to ArgumentNullException.ThrowIfNull

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#68326]
In support of the now-defunct `!!` feature, @RikkiGibson built into a Roslyn an analyzer/fixer that found constructs like:
```C#
void M(string arg)
{
    if (arg is null)
        throw new ArgumentNullException(arg);
    ...
}
```
and replaced them with:
```C#
void M(string arg!!)
{
    ...
}
```

Now that `!!` is no more, we should salvage this work and transform it to instead use `ArgumentNullException.ThrowIfNull` if available:
```C#
void M(string arg)
{
    ArgumentNullException.ThrowIfNull(arg);
    ...
}
```

**Comment by RikkiGibson** [comment]
I think this is a good idea, and that this would be done by adjusting the existing analyzer/fixer in the Roslyn IDE code style layer. Tagging @CyrusNajmabadi for a second opinion.

**Comment by CyrusNajmabadi** [comment]
Yup.

**Comment by RikkiGibson** [comment]
I'm going to do this before removing '!!' from the compiler, since it should let us leave a bunch of the existing IDE tests and plumbing in place.

**Comment by RikkiGibson** [comment]
@CyrusNajmabadi and I chatted offline and we think that a pared-down version of the feature might be appropriate here.

We think that it might be most appropriate to handle this by:

1. *removing* the 'UseParameterNullChecking' analyzer/fixer that was added for '!!' (possibly migrating the tests elsewhere).
2. adjust the implementation of the 'UseThrowExpression' analyzer to suggest the 'ArgumentNullException.ThrowIfNull' form if a null-checked parameter is not assigned to a field after.
3. ensure that we have separate editorconfig settings to control "prefer `param ?? throw`" independently from "prefer `ThrowIfNull(param)`.

```cs
// before
public Widget(string param)
{
    if (param is null)
    {
        throw new ArgumentNullException(nameof(param));
    }
    this.param = param;
}

// after
public Widget(string param)
{
    this.param = param ?? throw new ArgumentNullException(nameof(param));
}
```

```cs
// before
public void M(string param)
{
    if (param is null)
    {
        throw new ArgumentNullException(nameof(param));
    }
}

// after
public void M(string param)
{
    ArgumentNullException.ThrowIfNull(param);
}
```

**Comment by CyrusNajmabadi** [comment]
> It feels like it would be ideal to adjust the runtime so it is able to inline methods which contain throw, so that large amounts of existing code can benefit.

or, alternatively, the runtime should look *specifically* for `if (x is null) throw ArgumentNullException(nameof(x))`` and treat that identically to whatever it generates for `ArgumentNullException.ThrowIfNull(x)`.  Basically, it's not a pit of success for these two idiomatic expressions to have such different perf outcomes.

**Comment by Bosch-Eli-Black** [comment]
Can we also modify the existing "Add null check" quickfix in Visual Studio so that it has an option for generating an `ArgumentNullException.ThrowIfNull` call? 🙂

The "Add null check" quickfix currently looks like this:

![add null check quickfix](https://user-images.githubusercontent.com/37427589/167526910-daf1ad27-3104-40c5-a9de-de370b43397b.png)

Ideally, the quickfix would also have an option for generating a call to `ArgumentNullException.ThrowIfNull`, so that the resulting code looks like this:

```c#
public string Example(object name)
{
    ArgumentNullException.ThrowIfNull(name);

    return name.ToString();
}
```

(I originally posted this at https://github.com/dotnet/roslyn/issues/61181, and someone directed me here 🙂)

**Comment by terrajobst** [comment]
Make sense as proposd

**Comment by Bosch-Eli-Black** [comment]
@GrabYourPitchforks I wonder if there should be a performance analyzer for that warns about user code doing that, too. I certainly wouldn't have thought of it 😅

**Comment by RikkiGibson** [comment]
It might be good to check whether/when the boxing is elided by JIT in such scenarios.

**Comment by JamesNK** [comment]
aspnetcore is interested in this analyzer. We have a lot of source code with traditional null checks. We'd use the analyzer+fixer to automate updating our repo source - https://github.com/dotnet/aspnetcore/issues/43482

**Comment by RikkiGibson** [comment]
Thanks for following up. I don't anticipate I will have time to work on it.

**Comment by buyaa-n** [comment]
Estimates:

Analyzer: Medium
Fixer: Medium

**Comment by danmoseley** [comment]
the UseParameterNullChecking analyzer/fixer, now removed, can be cribbed from https://github.com/dotnet/roslyn/pulls/58182

Would this go in the Roslyn repo, or the roslyn-analyzers repo? Not sure which is for what. I'm guessing !! was a language feature, hence it was in dotnet/roslyn.

I assume this analyzer would only handle ThrowIfNull, as others like ArgumentOutOfRangeException.ThrowIf, ObjectDisposedException.ThrowIf and the others proposed (https://github.com/dotnet/runtime/issues/77749, https://github.com/dotnet/runtime/issues/69590) are sufficiently different.

**Comment by stephentoub** [comment]
> Would this go in the Roslyn repo, or the roslyn-analyzers repo?

roslyn-analyzers

> I assume this analyzer would only handle ThrowIfNull

Each should have its own diagnostic ID, but whether they're implemented in the same analyzer is an implementation detail.

Are you asking because you're planning to work on it?

**Comment by stephentoub** [comment]
I'm going to look at this one...

**Comment by Bosch-Eli-Black** [comment]
@stephentoub Sorry to bug, but did @GrabYourPitchforks's nit at https://github.com/dotnet/runtime/issues/68326#issuecomment-1164722060 get addressed? (And if not, shall I file a new bug for that?)

**Comment by stephentoub** [comment]
The analyzer fires for generics as well.  I went back and forth on whether to do so, as even though it results in boxing in the IL, the JIT will undo the boxing, at least in tier 1, e.g. [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BiAOwFcAbS7YSmAAgBMBLXW+gWACgABAJgCMPXgAYGAZQAW2KAAcAMrQB0AJXKkMLfDADcPEQGYGAhgGEeAbx4NbDANoApFhgDiMUjCgswACgwAnnIwEABmviyaAJRRALo2drzGvIJIDAAqDACyADzpAHy+mQBu2JTkMFEJttbcdvUMAIJQAObkOpoAclSUAKIIYDByWhCkyulSUBAA7gCSod3UvqXllfp1Dba8AOwMKxXr9QC+PEdAA==).  But if we want to change the analyzer to not raise diagnostics for unconstrained or struct-constrained generic parameters, I wouldn't push back.

**Comment by Bosch-Eli-Black** [comment]
Got it, thanks 🙂
