### ISSUE TITLE
HttpResponseMessage.ToString() prints Content as an object

### ISSUE THREAD

**Issue by dement6d** [dotnet/runtime#68369]
### Description

The `HttpResponseMessage.ToString()` method appends Content as a `System.Net.Http.HttpConnectionResponseContent` object instead of printing the actual content

### Reproduction Steps

Use HttpResponseMessage.ToString()

### Expected behavior

I expect the `HttpResponseMessage.ToString()` method to print the content itself not just the object type, or at least print both

### Actual behavior

The `HttpResponseMessage.ToString()` method appends Content as a `System.Net.Http.HttpConnectionResponseContent` object instead of printing the actual content

Here's an example of printing `HttpResponseMessage.ToString()`
```
StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Connection: keep-alive...
  ```

**Comment by ManickaP** [comment]
This is on purpose, you cannot read the response content stream multiple times. Reading in `ToString` would break consuming it from the application. Apart from that, you can also have scenarios like duplex streaming where the response stream is actually streaming and is not just a small text body, so printing it whole is impossible.

**Comment by wfurt** [comment]
ToString is really only primitive debug. There was never intention for to print everything.

**Comment by dement6d** [comment]
alright thanks yall
