### ISSUE TITLE
Missing package libldap-2.4.so.2 at runtime:5.0-buster-slim

### ISSUE THREAD

**Issue by brunohbrito** [dotnet/runtime#68365]
## Steps to reproduce the issue
1. Create a .NET 5.0 Console app
2. Run:
```ps1
dotnet new nugetconfig
dotnet nuget add source -n dotnet5 https://dnceng.pkgs.visualstudio.com/public/_packaging/dotnet5/nuget/v3/index.json
```
3. Get night build from System.DirectoryServices.Protocols, version 5.0.0-preview.6.20272.2
4. Add the following code: 
``` c#
var credential = new NetworkCredential("<username>", "<password>");
var connection = new LdapConnection(new LdapDirectoryIdentifier("<ip(13.0.0.0)>", 389, false, false), credential);
connection.Bind();
```
5. Run into container runtime:5.0-buster-slim
Reference Dockerfile
``` dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:5.0-buster-slim AS base
RUN apt-get update && apt-get install -y libldap-2.4-2
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:5.0-buster AS build
WORKDIR /src
COPY ["TesteLdap/TesteLdap.csproj", "TesteLdap/"]
COPY ["nuget.config", "/src"]
RUN dotnet restore "TesteLdap/TesteLdap.csproj" --configfile "nuget.config"
COPY . .
WORKDIR "/src/TesteLdap"
RUN dotnet build "TesteLdap.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TesteLdap.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TesteLdap.dll"]
```

## Expected behavior
Run without bugs

## Actual behavior
We got this error at logs: 
 `Unable to load shared library 'libldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibldap-2.4.so.2: cannot open shared object file: No such file or directory`

## Additional information (e.g. issue happens only occasionally)

The next version of System.DirectoryServices.Protocols has a dependency of `libldap-2.4`.
related to:
* [dotnet/runtime issue 36948](https://github.com/dotnet/runtime/issues/36948) 
* [dotnet/runtime issue 36888](https://github.com/dotnet/runtime/issues/36888)
* [dotnet/runtime issue 36947](https://github.com/dotnet/runtime/issues/36947)

**Comment by sameerbaveja** [comment]
@ChrisHolcomb  I tried what you suggested. Now i am not getting DLL error. 

**New Error:** The feature is not supported.

**Code :** 

            LdapDirectoryIdentifier ldi = new LdapDirectoryIdentifier("", 389, true, false);
            LdapConnection lc = new LdapConnection(ldi);
            lc.AuthType = AuthType.Kerberos;
            lc.Bind(new System.Net.NetworkCredential("", "", ""));
            string filter = String.Format("(&(objectCategory=person)(EmployeeID={0}))", empId);
            string[] attributesToReturn = { "samaccountName", "lockoutTime", "givenname", "sn", "EmployeeID" };
            SearchRequest sreq = new SearchRequest("", filter, System.DirectoryServices.Protocols.SearchScope.Subtree, attributesToReturn);
            SearchResponse sres = lc.SendRequest(sreq) as SearchResponse;

**Docker :**

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM misnexusprd.corp.amdocs.com/microsoft-proxy/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN apt-get update \
    && apt-get install -y --no-install-recommends libldap-2.4-2 \
    && apt-get install -y --no-install-recommends libldap-common \
    && rm -rf /var/lib/apt/lists/* 

COPY  ./ResetPassword.WebAPI/DC2.cert.cer /usr/local/share/ca-certificates/
RUN chmod 644 /usr/local/share/ca-certificates/DC2.cert.cer && update-ca-certificates
COPY ./ResetPassword.WebAPI/ldap.conf /etc/ldap/

FROM misnexusprd.corp.amdocs.com/microsoft-proxy/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ./ResetPassword.WebAPI/Amdocs_Root_Certification_Authority.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/AmdocsClass3SecureServerCA.crt /etc/ssl/certs/
COPY ./ResetPassword.WebAPI/amdocs.pem /etc/ssl/certs/
RUN update-ca-certificates 
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config

COPY ["./ResetPassword.WebAPI/ResetPassword.WebAPI.csproj", "ResetPassword.WebAPI/"]
COPY ["./ResetPassword.Core/ResetPassword.Core.csproj", "ResetPassword.Core/"]
RUN dotnet restore "ResetPassword.WebAPI/ResetPassword.WebAPI.csproj"
COPY . .
WORKDIR "/src/ResetPassword.WebAPI"
RUN dotnet build "ResetPassword.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ResetPassword.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ResetPassword.WebAPI.dll"]
