### ISSUE TITLE
Failure processing application bundle. Bundle header version compatibility check failed.

### ISSUE THREAD

**Issue by pkErbynn** [dotnet/runtime#68387]
### Description

When publishing a .net 6.0 (sdk 202) on an windows x64 system using `AppHost` result in,
```
Failure processing application bundle.
Bundle header version compatibility check failed. Header version: 1.0
A fatal error occured while processing application bundle
```
...meanwhile, the application launches successfully with target framework dotnetcore 3.1

### Reproduction Steps

Install either .net sdk 101 or 202 on windows

publish a .net core 6.0 console project with
dotnet publish --self-contained true -c Release /p:PublishSingleFile=true

### Expected behavior

Should launch the application

### Actual behavior

`dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Known Workarounds

1. removal of other versions dotnet runtimes apart from the version 6.0

2. tried this advice https://github.com/dotnet/runtime/issues/66442 and here is my trace result;
```
Tracing enabled @ Thu Apr 21 15:48:57 2022 GMT
--- Invoked apphost [version: 6.0.3, commit hash: c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663] main = {
newnotepad.exe
}
Redirecting errors to custom writer.
The managed DLL bound to this executable is: 'Crossroads.dll'
Detected Single-File app bundle
Using global installation location [C:\Program Files\dotnet\] as runtime location.
Reading fx resolver directory=[C:\Program Files\dotnet\host\fxr]
Considering fxr version=[6.0.1]...
Considering fxr version=[6.0.3]...
Detected latest fxr version=[C:\Program Files\dotnet\host\fxr\6.0.3]...
Resolved fxr [C:\Program Files\dotnet\host\fxr\6.0.3\hostfxr.dll]...
Loaded library from C:\Program Files\dotnet\host\fxr\6.0.3\hostfxr.dll
Invoking fx resolver [C:\Program Files\dotnet\host\fxr\6.0.3\hostfxr.dll] hostfxr_main_bundle_startupinfo
Host path: [C:\Users\User\Documents\newnotepad.exe]
Dotnet path: [C:\Program Files\dotnet\]
App path: [C:\Users\User\Documents\Crossroads.dll]
Bundle Header Offset: [9d94c98]
Tracing enabled @ Thu Apr 21 15:48:57 2022 GMT
--- Invoked hostfxr_main_bundle_startupinfo [commit hash: c24d9a9c91c5d04b7b4de71f1a9f33ac35e09663]
Mapped application bundle
Failure processing application bundle.
Bundle header version compatibility check failed. Header version: 1.0
A fatal error occured while processing application bundle
```

### Configuration

sdk version 6.0.201

**Comment by vitek-karas** [comment]
I must admit I don't know what's going on. I tried a repro with both 3.1 and 6.0 and it works just fine.
Based on the trace/error the single-file bundle version is 1. That should only happen if the app was built for `netcoreapp3.1`. `net6.0` apps should use bundle version 6.
It's also really weird that it got to the place where it fails with bundle version 1. 

If you have a repro project, that would be the best way for us to investigate.
Other than that... could you share the project file which you published with the command above.

**Comment by pkErbynn** [comment]
Thank you for your response. 

PS: The application is not published using the sdk but rather it is published programmatically using AppHost.

Here is the link to the project file - https://github.com/morganstanley/Crossroads/blob/migrate-dotnet-tool/src/Crossroads/Services/AppHostService.cs

**Comment by vitek-karas** [comment]
Let me start with a disclaimer: Using the Microsoft.NET.HostModel directly is in no way supported. We don't treat it as public API and we're likely to break it in future releases.

Looking at the code - you would probably get the behavior you're seeing if you used the 3.1 version of the HostModel package. Newer versions will not do this. Newer versions take a parameter `targetFrameworkVersion` which has to match the version of the apphost and the overall SDK rules around it. So if it happens that you're mixing old HostModel with new SDK/apphost it is absolutely going to break.

Why do you need to create the apphost and the bundle manually and can't use the SDK's implementation?

**Comment by agocke** [comment]
cc @VSadov

**Comment by pkErbynn** [comment]
Following your above suggestion;

I've updated the HostModel package to an earlier version of 5.0.0 (other than the previous 3.1 version) which happens to be a preview version according to https://www.nuget.org/packages/Microsoft.NET.HostModel. 
Here is the `.csproj` update - https://github.com/pkErbynn/Crossroads/blob/appHost-bundle-version-check-failure/src/Crossroads/Crossroads.csproj#L28

After upgrading the AppHost version, the problem still persists.

Additionally, I have been trying to figure out where to pass an argument for the parameter `targetFrameworkVersion` to match the version of the appHost and the overall SDK/appHost, but I can't seem to find that on the `HostWriter.CreatAppHost()` method. 

We are manually creating the apphost and the bundle in order to embed an application, extract it and spin it. 
Also, inspect the contents of the single-file app.
