### ISSUE TITLE
HostFxr fails to Initialize the host context when tried from a Native Code which is a Part of another .Net App 

### ISSUE THREAD

**Issue by Chandra123539** [dotnet/runtime#68388]
### `Issue`

HostFxr fails to Initialize the host context when tried from a Native Code which is a Part of another .Net App. 
we are trying to achieve a requirement where ASP.NetCore/.Net Core App loads a Linux .So by PInvoke and that Linux .So in turn tries to load another Managed Assembly.  This is where the issue Occurs.

**Target Platform is Linux or WSL.**

When the Core App starts in Linux,  It gives error saying ( Success_HostAlreadyInitialized) (0x00000001) and there is no Hostfxr context handle.
When the Same Core App is debugged in WSL, it says LibHostInvalidArgs (0x80008092). Even while running in the Docker Container also 
Same error occurs.

![image](https://user-images.githubusercontent.com/57258610/164714925-ded40ca0-4333-4aef-840c-8ee867dd1a3b.png)
![image](https://user-images.githubusercontent.com/57258610/164715033-65a90b9c-b4d8-42dd-910f-53c4e4a59d04.png)

This is the Source code.
[NativeHost.7z.gz](https://github.com/dotnet/runtime/files/8541098/NativeHost.7z.gz)

Projects are like this.
( NativeHost --- Native .So (Loads host fxr)
(Managed Assembly--- .NetCore Assembly to be loaded)
(NetProject--- .NetCore App Which loads NativeHost)
(ASPNetProject---ASP .NetCore App which loads NativeHost)

To reproduce the issue you can run the NetProject from Linux terminal NativeHost/NetProject/NetProject/NetProject/bin/Debug/net5.0$./NetProject

Please let us know your suggestion on this.

**Comment by elinor-fung** [comment]
Hi @Chandra123539, the return code `Success_HostAlreadyInitialized` is not actually an error. The [hosting layer return codes](https://github.com/dotnet/runtime/blob/main/docs/design/features/host-error-codes.md) use greater than or equal to 0 indicates success and negative values to indicate failure.

Thanks for including a repro project. I tried it out on WSL (Ubuntu 20.04 LTS). I was not able to repro the failure where `LibHostInvalidArgs` was returned. I do get `Success_HostAlreadyInitialized` and a valid hostfxr context handle.

I updated the check in `NetCoreInit::get_dotnet_load_assembly` to be `rc < 0` instead of `rc != 0`. Running `./NetProject` shows:
```
Started
 Host Fxr Path/mnt/c/dotnet/host/fxr/5.0.16/libhostfxr.so
 Host Fxr Retrieved
ManagedAssembly.runtimeconfig.json
 Valid function Piointer
```

Could you try updating your project to only treat negative values as a failure instead of any non-zero value?

**Comment by Chandra123539** [comment]
Hi Elinor, Thanks for having a quick look at this.  Yes, with that change i was able to retrieve function pointers to the Managed Assembly. No issue in Running from Linux terminal.

However, our main issue is that when the same workflow is executed in Docker Container, It says LibHostInvalidArgs. As it is difficult share the image, could you try debugging NetProject in WSL, so that we can see the similar error.
 
Attaching the error snapshot of NetProject in Debug mode of WSL.
![image](https://user-images.githubusercontent.com/57258610/164886019-5dabe733-0784-4002-bb71-08f6ca4c543a.png)

Not sure why there is a difference in output for Linux terminal and WSL Debug. 
Any suggestion on this would be really helpful.

 Debug Output indicates this.

Loaded '/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.16/Microsoft.Win32.Primitives.dll'. Symbols loaded.
Started
 Host Fxr Path/usr/share/dotnet/host/fxr/5.0.16/libhostfxr.so
 Host Fxr Retrieved
ManagedAssembly.runtimeconfig.json
Failed to initialize context for config: ManagedAssembly.runtimeconfig.json. Error code: 0x80008092
 Valid function Piointer
Init failed: 0x80008092
dotnet: /mnt/c/Users/cnpasupu/source/repos/NativeHost/NativeHost/NetCoreInit.cpp:74: NetCoreInit::NetCoreInit(const string_t&, const string_t&): Assertion `m_load_assembly_and_get_function_pointer != nullptr && "Failure: get_dotnet_load_assembly()"' failed.
The program 'dotnet' has exited with code 0 (0x0).

**Comment by Chandra123539** [comment]
Some more info on the Docker.
ASP.NetCore App loads libNativehost.so and it internally tries to load Managed Assembly.

ASP.Net 5 Runtime is installed in the docker.

Error looks like this.
![image](https://user-images.githubusercontent.com/57258610/164889828-c410c406-bf00-4e49-a068-f74e295f62c1.png)

**Comment by vitek-karas** [comment]
Can you turn on host tracing? Set `COREHOST_TRACE=1` and `COREHOST_TRACEFILE=host.txt` (or some other path) and repro the failure. The `host.txt` will contain detailed information. Please note that it will contain local environment, paths and so on, only share it if you're OK with the information it contains.

**Comment by Chandra123539** [comment]
Hi Vitek,  i have turned on host tracing and received some information. I am able to repro the issue from the Linux Terminal itself.

**When the ( NetProject executable) is run, there is no issue in loading the managed assembly from libNativeHost.** 
Command: NativeHost/NetProject/NetProject/NetProject/bin/Debug/net5.0$.**/NetProject**

Log info:
![image](https://user-images.githubusercontent.com/57258610/165038839-66df114f-423c-496a-b64e-79a495999d06.png)


**Instead if we go with dotnet [dll] command , Issue can be seen with same error code " 0x80008092".**
Command: NativeHost/NetProject/NetProject/NetProject/bin/Debug/net5.0$./**dotnet NetProject.dll**

LogInfo:
![image](https://user-images.githubusercontent.com/57258610/165039082-6bfab742-035b-404e-bbbc-aef6fe55abc3.png)

Even the Docker starts with [dotnet and dll] as the **Entry point** command and this might be causing similar failure.

Please let us know your suggestion on this.

**Comment by Chandra123539** [comment]
One observation we have made is that when NetProject is run as executable , it is able to initialize the secondary host context where as same thing is not happening when it is run as dotnet dll command.

**Comment by elinor-fung** [comment]
That is a really useful observation. This sounds like https://github.com/dotnet/runtime/issues/42745. This was fixed (https://github.com/dotnet/runtime/pull/43962) in 6.0, but not 5.0.

Would it be possible for you to upgrade to 6.0?

**Comment by Chandra123539** [comment]
Thanks Elinor for letting us know. I have tested it in .Net 6 and it worked fine.

We are planning to upgrade to .Net 6.
Once again thanks for your time.
