### ISSUE TITLE
Console can allocate too much on the stack with a custom encoding

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#68395]
In the unlikely scenario where the console's input is using a custom encoding, and the `GetMaxCharCount` returns a large value, this can lead to a large stack allocation.

Program to reproduce (works on macOS):

```csharp
using System.Text;

namespace Foo
{
    class Program
    {
        static void Main()
        {
            Console.InputEncoding = new CustomEncoding();
            Console.ReadKey(true);
        }
    }

    public class CustomEncoding : UTF8Encoding
    {
        public override int GetMaxCharCount(int byteCount) => int.MaxValue;
    }
}
```

The `stackalloc` is here:

https://github.com/dotnet/runtime/blob/0e18cfda13a8136103c83442e1a649cdecc237b0/src/libraries/System.Console/src/System/IO/StdInReader.cs#L53

The value being fed in to the `stackalloc`'s length should be guarded since it is dependent on external factors, in this case the encoding used by stdin.

**Comment by stephentoub** [comment]
Good catch.  Are you planning to put up a PR?

**Comment by vcsjones** [comment]
@stephentoub Yep.
