### ISSUE TITLE
[HTTP/3] Typo in the header's name

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/runtime#68407]
The [header name in QPACK](https://github.com/dotnet/runtime/blob/c55836ad3304f2d69c10d9a20de180d3d98f554e/src/libraries/Common/src/System/Net/Http/aspnetcore/Http3/QPack/H3StaticTable.Http3.cs#L149) `upgrading-insecure-requests` differs from the standard one `upgrade-insecure-requests` from [RFC](https://datatracker.ietf.org/doc/draft-ietf-quic-qpack/).

**Comment by MihaZupan** [comment]
For reference, `KnownHeaders` uses the correct name for the QPACK index:
https://github.com/dotnet/runtime/blob/0e18cfda13a8136103c83442e1a649cdecc237b0/src/libraries/System.Net.Http/src/System/Net/Http/Headers/KnownHeaders.cs#L93
