### ISSUE TITLE
Looping method call in a BackgroundWorker does an access violation instead of a StackOverflowException

### ISSUE THREAD

**Issue by Tom60chat** [dotnet/runtime#68413]
### Description

From [wpf](https://github.com/dotnet/wpf/issues/6469)
Discovery of a rather amusing bug.
I accidentally called a method in a loop in a BackgroundWorker but instead of having an exception and visual studio showing me where the exception took place, the application closes directly with only the message "Program exited with code 3221225477 (0xc0000005) 'Access violation'.", I was confused but after some research I found the error.

### Reproduction Steps

 **Minimal repro:**
```cs
public App()
{
    var worker = new BackgroundWorker();

    worker.DoWork += (sender, e) => {
        Foo();
    };

    worker.RunWorkerAsync();
}

void Foo() => Foo();
```

### Expected behavior

Throw an 'System.StackOverflowException'

### Actual behavior

Crash with code 3221225477 'Access violation'

### Configuration

* .NET Core Version: 6.0
* Windows version: 21H2 (19044.1645
* x64
* This is not specific to any configuration

**Comment by danmoseley** [comment]
Hi @Tom60chat . I can't seem to repro this.

* Does this reproduce without the debugger attached (I assume you're hitting F5 in VS - start debugging)
* Can you repro it with a standalone buildable piece of code?
* Is it possible for you to run it under a native debugger and get a stack trace for the native AV?
