### ISSUE TITLE
Delete old workflow run entries from backport pipeline

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#68440]
The workflow run entries are increasing rapidly. https://github.com/dotnet/runtime/actions/workflows/backport.yml There are over 150K entries accumulated (6022 pages of navigation). Most of them are referring to "skipped" runs.

We can delete the old entries with some strategy using an action like: https://github.com/Mattraks/delete-workflow-runs.

A strategy could be:

```
* delete all entries which were created over a week ago
&&
* delete any entry referring to skipped run
```

This will only retain the actual backport entries for a week.

**Comment by am11** [comment]
cc @akoeplinger

**Comment by am11** [comment]
Turned out GitHub CLI (`gh`) and `jq` are preinstalled, we don't need to rely on / trust external package. I have made a simpler automated cleanup job https://github.com/dotnet/runtime/compare/main...am11:feature/ci/backport. I think if I open a PR with that change it will start that job because currently this workflow is triggered on any issue comment. Therefore, looking for feedback before opening the PR.

**Comment by ViktorHofer** [comment]
Doesn't Github Workflows offer a retention policy setting so that these are auto cleaned-up?

**Comment by am11** [comment]
Looks like the [retention policy](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-repository) only applies to logs and artifacts, but not the workflow runs in the list.

I think if we open a PR with workflow change, it doesn't run the workflow until maintainer permits it (a button is shown to the maintainer at the bottom of PR). I didn't wanted to risk it in case there is a bug && my change is unacceptable. 😅

**Comment by am11** [comment]
The retention policy settings apparently applies to all actions not the individual workflow.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3840695/165506493-16164986-137d-4992-af57-3566dd6379c7.png">

and after 90 days, it will keep the workflow entry with empty logs:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/3840695/165508203-aced81b8-1ca5-4a94-82d0-5dfd5295b044.png">

If we want to delete the useless "backport" run entries, then we can do it manualy or via REST API.

GitHub actions is pretty much bare bones compared to other managed CIaaS. Manually customizing or buliding/sharing workflows with community is the way to extend workflows.

**Comment by ViktorHofer** [comment]
Got it. Thanks for the detailed explanation :)

> I have made a simpler automated cleanup job

As I don't know much about GH actions yet, would you mind explaining what triggers the new "cleanup_old_runs" job that you added?

**Comment by am11** [comment]
It is a good question which made me realize an inefficiency (now fixed).

Currently:

* it triggers on comment https://github.com/dotnet/runtime/blob/cb08c8cc341fd35d123a6b278bb17b5a069084ed/.github/workflows/backport.yml#L2-L4

  this means it creates the workflow entry for "every comment made in this repository". That is why we have accumulated 0.15 M entries. 😁
  After that it runs this job https://github.com/dotnet/runtime/blob/cb08c8cc341fd35d123a6b278bb17b5a069084ed/.github/workflows/backport.yml#L12-L13 and the condition skips all comments without "/backport" prefix. However the entry stays.

Proposed:
A new scheduled cron trigger is added that will run this workflow once a day at 13:00 UTC. The step "cleanup_old_runs" is conditioned on the cron trigger (and it will be skipped when workflow is ran by the comment trigger). It will delete the previous run entries with status "completed". The job backport will have no effect with this new trigger (due to the existing condition `github.event.issue.pull_request != ''`).

**Comment by ViktorHofer** [comment]
Cron jobs work for me :) Thanks for actually pointing this huge amount of wasted data out.
