### ISSUE TITLE
Always prefer IComparer<T> than Comparison<T> because delegates are slow

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#68465]
### Description
We should always prefer `IComparer<T>` than `Comparison<T>` in BCL.
`IComparer<T>` can be devirtualized to direct call, but `Comparison<T>` cannot because it's a delegate, so due to the current JIT limit it always introduces an indirect call. 
Therefore, `IComparer<T>` interface call can be significantly faster than `Comparison<T>` call. 
Also, delegates are reference types so it will also introduce unnecessary allocation before we can make delegates value types. 

A long-term plan should be fixing the allocation of delegates and make them inlinable (optimize to direct calls), so async functions can also benefits from it, in a significant manner. 

### Configuration
.NET 7 master

### Data
```csharp
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Environments;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

[Config(typeof(Config))]
[MemoryDiagnoser]
[DisassemblyDiagnoser]
public class Program
{
    class Config : ManualConfig
    {
        public Config()
        {
            AddJob(Job.Default
                .WithEnvironmentVariable("DOTNET_TieredPgo", "1")
                .WithRuntime(CoreRuntime.CreateForNewVersion("net7.0", ".NET 7.0")));
        }
    }

    static int Compare(int x, int y)
    {
        return x.CompareTo(y);
    }

    static void Main(string[] args)
    {
        BenchmarkRunner.Run<Program>(null, args);
    }

    public int IComparerCall<T>(IComparer<T> comparer, T x, T y)
    {
        return comparer.Compare(x, y);
    }

    public unsafe int ComparisonPtrCall<T>(delegate*<T, T, int> comparison, T x, T y)
    {
        return comparison(x, y);
    }

    public int ComparisonCall<T>(Comparison<T> comparison, T x, T y)
    {
        return comparison(x, y);
    }

    [Benchmark]
    public int IComparerTest()
    {
        return IComparerCall(new MyComparer(), 42, 24);
    }

    [Benchmark]
    public int ComparisonFromInstanceMethodTest()
    {
        return ComparisonCall(new MyComparer().Compare, 42, 24);
    }

    [Benchmark]
    public int ComparisonFromStaticMethodTest()
    {
        return ComparisonCall(Compare, 42, 24);
    }

    [Benchmark]
    public unsafe int ComparisonStaticMethodPtrTest()
    {
        return ComparisonPtrCall(&Compare, 42, 24);
    }

    struct MyComparer : IComparer<int>
    {
        public int Compare(int x, int y)
        {
            return x.CompareTo(y);
        }
    }
}
```

#### Allow inlining
|                           Method |       Mean |     Error |    StdDev | Code Size |  Gen 0 | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
|                    IComparerTest |   3.123 ns | 0.0916 ns | 0.0900 ns |      42 B | 0.0029 |      24 B |
| ComparisonFromInstanceMethodTest | 110.305 ns | 1.6791 ns | 1.4885 ns |     136 B | 0.0105 |      88 B |
|   ComparisonFromStaticMethodTest |   7.218 ns | 0.1438 ns | 0.1275 ns |     122 B | 0.0076 |      64 B |
|    ComparisonStaticMethodPtrTest |   1.689 ns | 0.0238 ns | 0.0211 ns |      48 B |      - |         - |

#### Disallow inlining
|                           Method |       Mean |     Error |    StdDev | Code Size |  Gen 0 | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
|                    IComparerTest |   3.919 ns | 0.0570 ns | 0.0533 ns |     138 B | 0.0029 |      24 B |
| ComparisonFromInstanceMethodTest | 108.382 ns | 0.9344 ns | 0.8741 ns |     180 B | 0.0105 |      88 B |
|   ComparisonFromStaticMethodTest |   8.552 ns | 0.1427 ns | 0.1335 ns |     155 B | 0.0076 |      64 B |
|    ComparisonStaticMethodPtrTest |   2.564 ns | 0.0299 ns | 0.0265 ns |      81 B |      - |         - |

#### Allow inlining
|                           Method |       Mean |     Error |    StdDev | Code Size |  Gen 0 | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
|                    IComparerTest |   2.888 ns | 0.0425 ns | 0.0397 ns |      42 B | 0.0029 |      24 B |
| ComparisonFromInstanceMethodTest | 105.860 ns | 0.9141 ns | 0.8551 ns |     136 B | 0.0105 |      88 B |
|   ComparisonFromStaticMethodTest |   7.034 ns | 0.0476 ns | 0.0422 ns |     122 B | 0.0076 |      64 B |
|    ComparisonStaticMethodPtrTest |   1.661 ns | 0.0274 ns | 0.0256 ns |      48 B |      - |         - |

#### Disallow inlining

|                           Method |       Mean |     Error |    StdDev | Code Size |  Gen 0 | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
|                    IComparerTest |   6.610 ns | 0.0718 ns | 0.0672 ns |      93 B | 0.0029 |      24 B |
| ComparisonFromInstanceMethodTest | 106.204 ns | 1.8185 ns | 1.5185 ns |     180 B | 0.0105 |      88 B |
|   ComparisonFromStaticMethodTest |   8.501 ns | 0.1970 ns | 0.2190 ns |     155 B | 0.0076 |      64 B |
|    ComparisonStaticMethodPtrTest |   2.578 ns | 0.0338 ns | 0.0299 ns |      81 B |      - |         - |

**Comment by stephentoub** [comment]
This test is incomplete. Try it in a situation where the comparer/comparison isn't inlined all the way back to where it's provided.

**Comment by hez2010** [comment]
If I put `[MethodImpl(MethodImplOptions.NoInlining)]` to `ComparisonCall` and `ICompareCall`:

|         Method |       Mean |     Error |    StdDev |  Gen 0 | Allocated |
|--------------- |-----------:|----------:|----------:|-------:|----------:|
|  IComparerTest |   4.311 ns | 0.0862 ns | 0.0765 ns | 0.0029 |      24 B |
| ComparisonTest | 106.932 ns | 1.2211 ns | 1.1423 ns | 0.0105 |      88 B |

**Comment by stephentoub** [comment]
Those are still not apples to apples, e.g. you're allocating way more the delegate test.

**Comment by hez2010** [comment]
I've updated the original post to cover all cases.

**Comment by stephentoub** [comment]
now try rotating through multiple comparers so that you're not always doing monomorphic dispatch

**Comment by hez2010** [comment]
I tested other two cases which pre-create the delegate and struct:

```csharp
[GlobalSetup]
public void Setup()
{
    comparer = new MyComparer().Compare;
    myComparer = new MyComparer();
}

private Comparison<int> comparer;
private MyComparer myComparer;

public int PreCreatedComparisonCall(int x, int y)
{
    return comparer(x, y);
}

[Benchmark]
public int PreCreatedComparisonTest()
{
    return PreCreatedComparisonCall(42, 24);
}

public int IComparerCall<T>(IComparer<T> comparer, T x, T y)
{
    return comparer.Compare(x, y);
}

[Benchmark]
public int PreCreatedIComparerTest()
{
    return IComparerCall(myComparer, 42, 24);
}
```

With PGO off and allowing inline:

|                           Method |       Mean |     Error |    StdDev | Code Size |  Gen 0 | Allocated |
|--------------------------------- |-----------:|----------:|----------:|----------:|-------:|----------:|
|         PreCreatedComparisonTest |   2.523 ns | 0.0822 ns | 0.1280 ns |      23 B |      - |         - |
|                    IComparerTest |   3.174 ns | 0.0564 ns | 0.0471 ns |      42 B | 0.0029 |      24 B |
|          PreCreatedIComparerTest |   2.951 ns | 0.0834 ns | 0.0892 ns |      49 B | 0.0029 |      24 B |
| ComparisonFromInstanceMethodTest | 111.358 ns | 2.0232 ns | 1.7935 ns |     136 B | 0.0105 |      88 B |
|   ComparisonFromStaticMethodTest |   7.240 ns | 0.1795 ns | 0.2067 ns |     122 B | 0.0076 |      64 B |
|    ComparisonStaticMethodPtrTest |   2.003 ns | 0.0714 ns | 0.1537 ns |      48 B |      - |         - |

Now I see why my previous benchmark is not correct. 
I'm closing this issue, thank you!
