### ISSUE TITLE
Unable to deserialize char-based Enum

### ISSUE THREAD

**Issue by WashingtonARamos** [dotnet/runtime#68471]
### Description

In one of our APIs we have an endpoint that returns data that contains an enum; this enum is returned in JSON as a string (e.g.: `"Color" : "B"`). When trying to deserialize the enum it fails.

### Reproduction Steps

Have an enum which has it's values defined as `chars`:
```C#
public enum UserAnswer
{
    Yes = 'Y',
    No = 'N'
}
```
The API response model contains said enum:
```C#
public class APIResponse
{
    public UserAnswer Answer { get; init; }
}
```
The Json string contains the enum value formatted as a string:
```Json
{
    "Answer" : "N"
}
```
When trying to deserialize an exception is thrown:
```C#
using System.Text.Json;

// ...

// throws "System.Text.Json.JsonException: The JSON value could not be converted to Sandbox.Program+UserAnswer"
var deserializedObject = JsonSerializer.Deserialize<APIResponse>(jsonString);
```

Decorating the enum with `[JsonConverter(typeof(JsonStringEnumConverter))]` doesn't help, neither does decorating the values with `[EnumMember(Value = "<value>")]`

### Expected behavior

When a Json value is a single character that matches values in the enum, the enum should receive that value. That is, when (in the example given) the Json is:
```Json
{
    "Answer" : "N"
}
```
The deserialized `Answer` should have value `UserAnswer.No`; likewise, with:
```Json
{
    "Answer" : "Y"
}
```
`Answer` should have value `UserAnswer.Yes`.

### Actual behavior

An exception is thrown.

### Configuration

**Which version of .NET is the code running on?**
.NET 6, .NET 5.
**What OS and version, and what distro if applicable?**
Windows 10 21H1 (19043.1645).
**What is the architecture (x64, x86, ARM, ARM64)?**
x64.
**Do you know whether it is specific to that configuration?**
No.
**If you're using Blazor, which web browser(s) do you see this issue in?**
n/a.

**Comment by stephentoub** [comment]
That enum doesn't contain chars. Its underlying type is Int32, and the values in the enum are just cast from char. At the IL level it's indistinguishable:
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQhGAzAAQwB2ArgLZkCqAzjFAIKVMDurhA3oTJCyATRhMyAXjIByETIA0g4QDkIU2SpmEAvkA

**Comment by WashingtonARamos** [comment]
@stephentoub by decorating the enum values with `[EnumMember(Value = "<value>"]` on `Newtonsoft.Json` I can make it work:
```C#
public enum UserAnswer 
{
    [EnumMember(Value = "Y")]
    Yes,
    [EnumMember(Value = "N")]
    No
}
```
The same doesn't work on `System.Text.Json`, as it throws the same `System.Text.Json.JsonException`. Is it a missing feature?

**Comment by gregsdennis** [comment]
https://www.nuget.org/packages/Json.More.Net/ also has a string converter (I imagine they're fairly common).

**Comment by eiriktsarpalis** [comment]
> by decorating the enum values with `[EnumMember(Value = "<value>"]` on `Newtonsoft.Json` I can make it work:

We don't have any plans on supporting System.Runtime.Serialization attributes natively in STJ, but want to provide extensibility points that make such support possible via community provided extensions. Supporting `EnumMemberAttribute` should be possible using a custom converter factory (as seems to have already been done in some of the packages listed here).

At risk of stating the obvious, one alternative approach might be to use a dedicated enum type in your DTO layer:
```C#
[JsonConverter(JsonStringEnumConverter)]
public enum UserAnswerDto { Y, N }
```

**Comment by WashingtonARamos** [comment]
> > by decorating the enum values with `[EnumMember(Value = "<value>"]` on `Newtonsoft.Json` I can make it work:
> 
> We don't have any plans on supporting System.Runtime.Serialization attributes natively in STJ, but want to provide extensibility points that make such support possible via community provided extensions. Supporting `EnumMemberAttribute` should be possible using a custom converter factory (as seems to have already been done in some of the packages listed here).
> 
> At risk of stating the obvious, one alternative approach might be to use a dedicated enum type in your DTO layer:
> 
> ```cs
> [JsonConverter(JsonStringEnumConverter)]
> public enum UserAnswerDto { Y, N }
> ```
Sorry for reopening the issue but at times it would be unviable to simply list the pure enum values ("Y","N"). It would either be literally impossible due to language limitations or it would kill code readability. One such case is to enum a [FIX Order Status](https://btobits.com/fixopaedia/fixdic44/tag_39_OrdStatus_.html). Since enum names can't be numbers we wouldn't be able to directly list from `New` ('0') to `Suspended` ('9') and even if we could a code read like this:
```C#
if (orderStatus == OrderStatus.0 || orderStatus == OrderStatus.D)
{
    // ...
}
```
Would be horrible. Also, since we can't set the enum values directly as chars (`public enum OrderStatus { New = '0', PartiallyFilled = '1' }`) in this case we _need_ something else. It would be nice to have something out of the box so that we don't have to depend on third party libs for such a small feature. Still, it was indeed easy to write a custom JsonConverter for our use case, but not before researching for ways to solve in vanilla .NET and third party libs.
