### ISSUE TITLE
[wasm-mt] place multi-threaded wasm build into separate artifacts folders

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#68506]
Build artifacts for the `/p:WasmEnableThreads=true` should go into a separate output folder. In other words it should be possible to build with `/p:WasmEnableThreads=false` in the same tree and without the build artifacts interfering with each other.

Needed by https://github.com/dotnet/runtime/issues/68508

Part of #68162

**Comment by lambdageek** [comment]
@steveisok @akoeplinger The initial wasm-mt PR landed; this is now the next issue for the runtime pack

**Comment by steveisok** [comment]
@lambdageek Alex is working on moving cmake related items out of mono.proj and into its own file.  That'll make it easier to build the runtime twice w/o a bunch of conditions / hacks.

**Comment by lambdageek** [comment]
Note that this needs to be somewhat general: for the [`/p:WasmEnablePerfTracing=true` build](https://github.com/dotnet/runtime/pull/69158) we should also place its artifacts into an `ep` subfolder (tracking: https://github.com/dotnet/runtime/issues/69268)

**Comment by lambdageek** [comment]
This is done using `MonoWasmBuildVariant=perftrace` or `MonoWasmBuildVariant=multithread` in https://github.com/dotnet/runtime/pull/71054 which also published runtime packs. (we decided to go with separate runtime packs for each variant)
