### ISSUE TITLE
Regex.Matches very very slow on Android

### ISSUE THREAD

**Issue by ismlsmile** [dotnet/runtime#68504]
Maui rc version, .Net 7 preview 3
It is ok on windows 10. When runing on Android using maui, it is very very slow.

**Comment by danmoseley** [comment]
@SamMonoRT @marek-safar we discussed recently potentially getting microbenchmark numbers on devices. Is that feasible by, say, the summer, do you think? Any thoughts about what kinds of microbenchmarks might have unexpected results on devices? just curious.

**Comment by SamMonoRT** [comment]
@danmoseley  - I don't believe we can get those running in the next few months.  CPU intensive, memory allocators and GC related benchmarks can possibly show different results on devices, can't relate to exact microbenchmarks we have running today

**Comment by danmoseley** [comment]
Fair enough. Perhaps this is in @sblom future plans.
