### ISSUE TITLE
(Error .Net Core 5) "Directory.GetDirectories("D:")" returns not existingDirectory

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#68503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-Net-Core-5-DirectoryGetDirect/1696966)._

---

```
String[] dirSSS = Directory.GetDirectories("D:");
dirSSS[0];             // Output:  "D:\ref" (without quotes) <-- no this directory on disk "D:"!
Environment.Version;   // "5.0.13" (Net Core)
Environment.OSVersion; // "Microsoft Windows NT 6.3.9600.0"
                       // VS (Russian):
                       //    Microsoft Visual Studio Professional&nbsp;2019
                       //    Версия 16.11.9
```
There is another theme with this error, but it closed:
https://developercommunity2.visualstudio.com/t/DirectoryGetDirectoriesdrive-return-a/175411?entry=suggestion&space=8&preview2=true

---
#### Feedback Bot on 3/21/2022, 00:32 AM: 

(private comment, text removed)

**Comment by skyoxZ** [comment]
I tested the code below and got an amazing result:

```csharp
using System;
using System.IO;

for(int i = 0;i < 20; i++)
{
    string s = (char)('A' + i) + ":";
    Console.WriteLine(s + " -> " + Path.GetFullPath(s));
}
```

Output:
```
A: -> A:\
B: -> B:\
C: -> C:\WINDOWS\System32
D: -> D:\vs projects\ConsoleApp1\ConsoleApp1\bin\Debug\net6.0
E: -> E:\
F: -> F:\
G: -> G:\
...
```

**Comment by svick** [comment]
This is called a drive relative path and it's why the backslash in `D:\` is important. For more details, see [the article on Windows paths](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#traditional-dos-paths).

**Comment by skyoxZ** [comment]
> This is called a drive relative path and it's why the backslash in `D:\` is important. For more details, see [the article on Windows paths](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#traditional-dos-paths).

I read the article but still don't understand what happened exactly. And I think the behavior in this issue is definitely unexpected.

**Comment by svick** [comment]
> I understand my case now and believe `D:\ref` is a bug.

I think you're right. Returning the `ref` directory is correct. But returning it as `D:\ref` is incorrect. Instead, I think it should be returned as `D:ref` in this case.

**Comment by Jozkee** [comment]
> dirSSS[0];             // Output:  "D:\ref" 
> Environment.Version;   // "5.0.13" (Net Core)
> Environment.OSVersion; // "Microsoft Windows NT 6.3.9600.0"

I wonder if this bug is specific to Windows 8.1, in such case it would probably be tied to the Windows API, not to .NET. 
I couldn't repro it on windows 10.

`Directory.GetDirectories("C:")` does yield the right results for me (folders of the current working directory).

**Comment by Jozkee** [comment]
@skyoxZ linking issue related to your comments: https://github.com/dotnet/runtime/issues/63892.

**Comment by skyoxZ** [comment]
@Jozkee I did repro the `D:\ref` issue on my Win 11. 
May give more info about 3 days later (I'm on holiday).

**Comment by Jozkee** [comment]
@skyoxZ yes please, could you please also add `Console.WriteLine(Environment.CurrentDirectory);` to your repro. I want to discard that the cwd is indeed different to what's being used in `GetDirectories`.

**Comment by skyoxZ** [comment]
@Jozkee Please try the code below:
```csharp
string foo = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "foo");
string bar = Path.Combine(foo, "bar");
Directory.CreateDirectory(bar);
Environment.CurrentDirectory = foo;
string root = foo.Remove(2);
string[] ss = Directory.GetDirectories(root);
Console.WriteLine("-- " + root);
foreach(string s in ss)
{
    Console.WriteLine(s);
}
```

.NET Framework 4.8 got correct result:
```
-- D:
D:bar
```

however, .NET 6.0 got the result below:
```
-- D:
D:\bar
```
