### ISSUE TITLE
[API Proposal]: Make IHostEnvironment.ApplicationName non-nullable

### ISSUE THREAD

**Issue by halter73** [dotnet/runtime#68512]
### Background and motivation

In 7.0-preview3 we made `IHostEnvironment.ApplicationName` and `IHostingEnvironment.ApplicationName` nullable because of the following:

https://github.com/dotnet/runtime/blob/05cb7f5a6eefbcd0fbab3bb5924c07b188d12501/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L202-L213

https://github.com/dotnet/runtime/pull/65403/files/dabdada197861a1fe343f0c82e6ebf3f87c663b5#r829310348

While this is technically correct, it's not user friendly. Historically, applications have expected this property to be non-nullable like the other properties on the interface like `EnvironmentName`.

It would be better if, similar to `EnvironmentName` and "Production", we just pick a default `ApplicationName` when `Assembly.GetEntryAssembly()` returns `null`.

### API Proposal

```diff
namespace Microsoft.Extensions.Hosting;

 public interface IHostEnvironment {
-    string? ApplicationName { get; set; }
+    string ApplicationName { get; set; }
 }
 public interface IHostingEnvironment {
-    string? ApplicationName { get; set; }
+    string ApplicationName { get; set; }
 }
```

### API Usage

Instead of doing complicated null-checks:

```csharp
if (env.ApplicationName is not null)
{
    var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
    if (appAssembly != null)
    {
        config.AddUserSecrets(appAssembly, optional: true);
    }
}
```

We should be able to assume `ApplicationName` is non-null:

```csharp
var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
if (appAssembly != null)
{
    config.AddUserSecrets(appAssembly, optional: true);
}
```

See https://github.com/dotnet/aspnetcore/pull/40754/files#diff-ba47e8a57bffee356b71c57b0ac4709dc0eb1329d547a36ee30fea262cf8358c

### Alternative Designs

Keeping `ApplicationName` nullable.

### Risks

We cannot come up with a good `ApplicationName` for when `Assembly.GetEntryAssembly()` returns `null`.

**Comment by eerhardt** [comment]
> we just pick a default ApplicationName when Assembly.GetEntryAssembly() returns null.

Do you have a proposal for what it should be? `string.Empty`, `Application`, ?

**Comment by halter73** [comment]
I like `string.Empty` or maybe `"<Unkown>"`.

I don't expect this to come up much outside of certain testing and tooling scenarios since `Assembly.GetEntryAssembly()` is usually non-null. I don't think we should use a nice name like `"Application"` which would be a valid default when an entry assembly is found. I'd rather make it obvious that a good default couldn't be found.

**Comment by eerhardt** [comment]
I think I like “<Unknown>”. That would be a good default when we can’t default anything else.

**Comment by maryamariyan** [comment]
Went over this with @tarekgh and @eerhardt and for this one we could skip api review because we just annotated this in the past few weeks. 

Compared to 6.0, we went from having no nullable to now having nullable annotated as being not nullable.

The observable change in behavior: on an app we could get null application name but now you'd get default value.

**Comment by eerhardt** [comment]
I ended up needing to go with `string.Empty` because of the following:

https://github.com/dotnet/runtime/blob/9a0b8f339ddb5cd6d4f7e8c333afc9a74dc545e5/src/libraries/Microsoft.Extensions.Hosting/src/HostingHostBuilderExtensions.cs#L232-L239

When ApplicationName is `<Unknown>` this code throws trying to load an assembly named `<Unknown>`.
