### ISSUE TITLE
Single file executable still generates DLL file

### ISSUE THREAD

**Issue by mooleshacat** [dotnet/runtime#68526]
I am trying to get my file into a single file, and I enabled the single file mode. The main DLL that is the same name as the EXE is gone.

But there is a DLL for a component that is included in the project still:

consoleapp1.exe
chilkatDnCore-9_5_0.dll

How do I tell visual studio to actually give me a single file, and merge the component's DLL into the file as well?

**Comment by gfoidl** [comment]
Try [Including native libraries](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file/overview#including-native-libraries).

**Comment by agocke** [comment]
Yes, it is likely that chilkatDnCore is a native library, which isn't embedded by default, as it implies that it will be extracted to a temporary directory on startup, which carries a perf and complexity penalty.
