### ISSUE TITLE
[API Proposal]: Apply OpenTelemetry attribute limits to Activity

### ISSUE THREAD

**Issue by alanwest** [dotnet/runtime#68528]
### Background and motivation

The OpenTelemetry project defines configuration to limit the length and the count of attributes on span data.

See:
* [Attribute Limits](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute-limits)
* [Span Limits](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-limits)

The `Activity` API should allow an end user to configure:
1. The maximum number of tags on an `Activity`, `ActivityEvent`, or `ActivityLink`.
2. The maximum number of `ActivityEvent`s and `ActivityLink`s on an `Activity`.
3. The maximum length of string-valued tags on an `Activity`, `ActivityEvent`, or `ActivityLink`.

This configuration is important for supporting backends that have restrictions on the length/quantity of attributes and the ingested payload size.

Related issue https://github.com/dotnet/runtime/issues/42347.

### API Proposal

```C#
namespace System.Diagnostics;

// New static configuration properties on the ActivitySource class configure limits for every Activity created
public class ActivitySource
{
    // Limits the number of tags on Activity, ActivityEvent, and ActivityLink
    public static int? ActivityTagCountLimit { get; set; }

    // Limits the length of string-valued and string[]-valued tags on Activity, ActivityEvent, and ActivityLink
    // Each element in a string[] value should adhere to this limit
    public static int? ActivityTagValueLengthLimit { get; set; }

    // Limits the number of ActivityEvents added using Activity.AddEvent
    public static int? ActivityEventCountLimit { get; set; }
    
    // Limits the number of ActivityLinks added to an Activity when it is started
    public static int? ActivityLinkCountLimit { get; set; }

    // If set, the following should override ActivityTagCountLimit for ActivityEvents and ActivityLinks
    public static int? ActivityEventTagCountLimit { get; set; }
    public static int? ActivityLinkTagCountLimit { get; set; }
}
```

### API Usage

```C#
// TODO: will edit the issue with examples
```

**Comment by tarekgh** [comment]
This request is better served in the OpenTelemetry SDK side and not on the level of the `Activity` APIs. Introducing such limits in the `Activity` APIs would have some app compatibility concerns if such limits turned on. Also, in general .NET don't limit the resources for any allocations in any objects. Apps can allocate any huge objects. 

I am closing this issue here and please follow up to get this done on the SDK side. Thanks for your report. 

CC @reyang @noahfalk

**Comment by CodeBlanch** [comment]
I was just thinking about this randomly. One big benefit of having the limits in runtime would be it could be more pro-active. OTel SDK can't really do anything until Activity is stopped at which point we are notified. We can have limits about what is exported, dropping stuff as we enumerate, but it will already be attached to the Activity and in-memory. The worst case scenario would be users add so many tags to so many in-flight Activity instances that they OOM. Extreme/unlikely case of course 😄

Here's an idea...

What if we added an event/callback on `ActivityListener` that fires when a tag is added? OTel SDK could listen to that, check limits, and decide whether to drop or allow the tag to be added. That could also give us a nice spot to translate things from old versions to new APIs. For example, Status/StatusDescription. There is an API on Activity for it now, but there wasn't always. Before we just used tags for that. It has been kind of difficult for us to handle both cases, there isn't a good migration story. If we had this callback/event, we could translate the legacy tags to the new API if we see them being added, and also support limits. Interesting?

**Comment by reyang** [comment]
Is there general practice around limits?

e.g. `HttpClient.DefaultRequestHeaders.Add("name", value)` doesn't seem to put any artificial limits.

**Comment by CodeBlanch** [comment]
> Do we have any evidence in the real scenarios having too many Activities are created and attached too many tags causing OOM?

I don't have anything. All I know is this got into the OTel spec so a large number of people seemed to think it was good to have.

Spec prefixes the section with...

> Execution of erroneous code can result in unintended attributes. If there are no limits placed on attributes, they can quickly exhaust available memory, resulting in crashes that are difficult to recover from safely.

Seems to be a defensive thing. I dunno some dev adds all HTTP headers as tags in a loop. Some malicious actor spams the web server with requests with a lot of random headers in order to OOM all the nodes. I'm reaching here 😄

**Comment by reyang** [comment]
> > Execution of erroneous code can result in unintended attributes. If there are no limits placed on attributes, they can quickly exhaust available memory, resulting in crashes that are difficult to recover from safely.
> 
> Seems to be a defensive thing. I dunno some dev adds all HTTP headers as tags in a loop. Some malicious actor spams the web server with requests with a lot of random headers in order to OOM all the nodes. I'm reaching here 😄

I think the same problem would exist for other scenarios - e.g. if the dev didn't pay attention and allow unbounded number of HTTP headers, the application is already having an even more serious problem (IMHO this is a security bug).
