### ISSUE TITLE
[wasm][debugger] Display parent's members on getProperties

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#68542]
Current behavior: 
Check out `InspectTypeInheritedMembers` for `DerivedClass`. `this_props` has only its own members:
- one `Base_AutoStringPropertyForOverrideWithField` when it should have two: its own and from BaseClass,
- one `Base_GetterForOverrideWithField` when it should have two:  its own and from BaseClass,
- one `BaseBase_MemberForOverride` when it should have three: its own, from BaseClass and from BaseBaseClass.

Expected behavior:
![image](https://user-images.githubusercontent.com/32700855/167391895-bb71ef90-8277-46d8-b8db-e853b4c526c0.png)

**Comment by radical** [comment]
Is this showing parent members that were overridden, or hidden? Does VS have the same behavior for non-wasm projects?

**Comment by ilonatommy** [comment]
> Is this showing parent members that were overridden, or hidden? Does VS have the same behavior for non-wasm projects?

Expected behavior (screenshot) is based on Console App project's behavior for InspectTypeInheritedMembers test. If a virtual field was overwritten, then it's shown only once (of the child). 
What do you mean by being deliberate about not doing that? Should the blazor app differ here from console app? What's the reason for it?

**Comment by radical** [comment]
Ok, so looking at it, IIUC, the behavior is:

1. If a member is overridden, then only show the overridden one
2. If a member is *new*-hidden, then show the both the base, and the new one
