### ISSUE TITLE
[iOS] Setting UmAlQura as a calendar culture results in a crash

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#68555]
First filed as a MAUI issue: https://github.com/dotnet/maui/issues/6505

When you set the calendar as `UmAlQuraCalendar`, the iOS application crashes.

```
var cultureInfo = CultureInfo.CreateSpecificCulture("ar-EG");
cultureInfo.DateTimeFormat.Calendar = new UmAlQuraCalendar();
```

I suspect this calendar is mistakenly being filtered out when we apply ICU filters.

**Comment by steveisok** [comment]
@tarekgh There's a [comment](https://github.com/dotnet/maui/issues/6505#issuecomment-1109896829) in the MAUI issue that indicates this also throws on console.  Not sure what to make of that?

**Comment by tarekgh** [comment]
Every culture has a set of calendars that can work with. You can get the list of supported calendars of any culture by calling [CultureInfo.OptionalCalendars](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.optionalcalendars?view=net-6.0). 

If running the code:
```C#
            CultureInfo ci = CultureInfo.GetCultureInfo("ar-EG");
            foreach (Calendar cal in ci.OptionalCalendars)
            {
                Console.WriteLine(cal);
            }
```

will get 

```
System.Globalization.GregorianCalendar
System.Globalization.HijriCalendar
```

If want to use the UmAlQura calendar, will need to use a culture like `ar-SA`

```C#
            CultureInfo ci = CultureInfo.GetCultureInfo("ar-SA");
            foreach (Calendar cal in ci.OptionalCalendars)
            {
                Console.WriteLine(cal);
            }
```

```
System.Globalization.UmAlQuraCalendar
System.Globalization.GregorianCalendar
System.Globalization.HijriCalendar
```

**Comment by tarekgh** [comment]
[calendars document](https://docs.microsoft.com/en-us/dotnet/standard/datetime/working-with-calendars#calendars-in-net) is a good resource to read.
