### ISSUE TITLE
CoreCLR tests build error on main for arm/armel/arm64

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#68589]
Next error happens during tests cross build for arm/armel/arm64 on x64:
```
/home/runtime/.packages/microsoft.net.sdk.il/7.0.0-preview.4.22208.8/targets/Microsoft.NET.Sdk.IL.targets(136,5): error MSB3073: The command ""/home/runtime/artifacts/bin/coreclr/Linux.arm64.Release/ilasm" -QUIET -NOLOGO -OPTIMIZE -DLL  -OUTPUT="/home/runtime/artifacts/tests/coreclr/obj/Linux.arm64.Release/Managed/Loader/classloader/generics/ByRefLike/InvalidCSharp/InvalidCSharp.dll"  InvalidCSharp.il" exited with code 127. [/home/runtime/src/tests/Loader/classloader/generics/ByRefLike/InvalidCSharp.ilproj] [/home/runtime/src/tests/build.proj]
/home/runtime/src/tests/Common/dir.traversal.targets(25,5): error : (No message specified) [/home/runtime/src/tests/build.proj] [/home/runtime/src/tests/build.proj]
/home/runtime/src/tests/build.proj(501,5): error MSB3073: The command ""/home/runtime/dotnet.sh" msbuild /home/runtime/src/tests/build.proj /t:Build "/p:TargetArchitecture=arm64" "/p:Configuration=Release" "/p:LibrariesConfiguration=Release" "/p:TargetOS=Linux" "/p:RuntimeOS=" "/p:RuntimeFlavor=coreclr" "/p:RuntimeVariant=" "/p:CLRTestBuildAllTargets=" "/p:__TestGroupToBuild=3" "/p:__SkipRestorePackages=1" /nodeReuse:false /maxcpucount /bl:/home/runtime/artifacts//log/Release/InnerManagedTestBuild.3.binlog" exited with code 1.
    0 Warning(s)
    3 Error(s)
```

The cause of this build error appeared in https://github.com/dotnet/runtime/pull/67783:

https://github.com/dotnet/runtime/blob/4ed596ef63e60ce54cfb41d55928f0fe45f65cf3/src/tests/Loader/classloader/generics/ByRefLike/InvalidCSharp.ilproj#L5-L8

This means that during cross build on x64 for arm/armel/arm64 incorrect ilasm binary with non-x64 arch will be tried to be executed. I guess that this is a temporary change according to comment.

cc @alpencolt

**Comment by danmoseley** [comment]
@AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
> I guess that this is a temporary change according to comment.

Yes, it is temporary and might be able to be removed at this point. I can try this today.

**Comment by AaronRobinsonMSFT** [comment]
Looks like we are still using version 7.0.0-preview.4.22208.8 of the ILAsm package. We will need to bump that version to the latest - which should have those changes. Let me see if I can figure out how to do that.
