### ISSUE TITLE
ILCompiler.DependencyAnalysisFramework targets net5.0 which is out-of-support soon

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#68595]
@trylek @MichalStrehovsky

Noticed that because it's the only project in the repo that depends on the System.Collections.Immutable package. If the project would upgrade to 6.0 we could also eliminate the package reference and the entry in Versions.props.

**Comment by am11** [comment]
Related: according to https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/, netfx 4.6.1 is out of support since yesterday (April 26). We have a few occurrences of 4.6.1 left:
```sh
 % git grep -Eli 'net.*4\.6\.1|net461'
.vsconfig
docs/coding-guidelines/libraries-packaging.md
eng/packaging.targets
eng/testing/performance/microbenchmarks.proj
src/coreclr/jit/importer.cpp
src/libraries/System.Composition/src/System.Composition.csproj
src/libraries/testPackages/testPackages.proj
src/mono/mono/tests/dim-abstractcall.il
src/mono/mono/tests/dim-diamondshape.il
src/mono/mono/tests/dim-generic-interface.il
src/mono/mono/tests/dim-genericmethods.il
src/mono/mono/tests/dim-implements-multiple-interfaces.il
src/mono/mono/tests/dim-methodimpl.il
src/mono/mono/tests/dim-nested-types.il
src/mono/mono/tests/dim-protected-accessibility1.il
src/mono/mono/tests/dim-protected-accessibility2.il
src/mono/mono/tests/dim-reabstraction-generics.il
src/mono/mono/tests/dim-reabstraction.il
src/mono/mono/tests/dim-sealed.il
src/mono/mono/tests/dim-sharedgenerics.il
src/mono/mono/tests/dim-simple.il
src/mono/mono/tests/dim-valuetypes.il
src/tests/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape.il
src/tests/Loader/classloader/DefaultInterfaceMethods/genericmethods/genericmethods.il
src/tests/Loader/classloader/DefaultInterfaceMethods/methodimpl/methodimpl.il
src/tests/Loader/classloader/DefaultInterfaceMethods/sharedgenerics/sharedgenerics.il
src/tests/Loader/classloader/DefaultInterfaceMethods/simple/simple.il
src/tests/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes.il
```
4.6.2 is the minimum recommended target (per the blog post).

**Comment by ViktorHofer** [comment]
> eng/packaging.targets

That one is a false positive. We need the placeholder file in there.

> docs/coding-guidelines/libraries-packaging.md

False positive as well.

Everything else should probably be looked at by the runtime team cc @trylek @jkotas

**Comment by jkotas** [comment]
That's all false positives - version numbers in comments. I have submitted https://github.com/dotnet/runtime/pull/68614 to cleanup some of it.

**Comment by ViktorHofer** [comment]
> src/libraries/testPackages/testPackages.proj

Submitted https://github.com/dotnet/arcade/pull/9205 to clean that up in Arcade so that we can then delete the net461 mention in that file in dotnet/runtime.
