### ISSUE TITLE
Investigate why createdump generated dumps are so large on MacOS

### ISSUE THREAD

**Issue by mikem8361** [dotnet/runtime#68604]
We are seeing ~6GB dumps on MacOS in the CI jobs.

**Comment by janvorli** [comment]
Just FYI, I am getting large dump sizes (over 3GB at least) even for a trivial C app with `main` containing only a dereference of NULL and nothing else. So it seems to be a general macOS issue.

**Comment by danmoseley** [comment]
Much discussion occurred here https://github.com/dotnet/core-eng/issues/15333
Another suggestion was to investigate how compressible these huge dumps are.
