### ISSUE TITLE
LSRA Reg Optional: Folding of read-modify-write mem operations

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#6862]
E.g.   a = a + b/cns

If it is profitable to not to allocate a reg to 'a' - i.e. both to its Use and Def position, then we can generate

add [mem], reg/cns

category:cq
theme:register-allocator
skill-level:intermediate
cost:medium

**Comment by kunalspathak** [comment]
From the example of the Issue description, it is not clear about the scenario when we do not generate relevant code.
