### ISSUE TITLE
[API Proposal]: Add LifetimeAnnotationAttribute

### ISSUE THREAD

**Issue by cston** [dotnet/runtime#68622]
### Background and motivation

Allow annotations in metadata for types, methods, and parameters to indicate the lifetime scope of `ref` and `ref struct` values (see [spec](https://github.com/dotnet/csharplang/blob/main/proposals/low-level-struct-improvements.md#lifetimeannotationattribute)).

### API Proposal

```C#
namespace System.Runtime.CompilerServices
{
    [AttributeUsage(
        AttributeTargets.Constructor |
        AttributeTargets.Field |
        AttributeTargets.Method |
        AttributeTargets.Parameter |
        AttributeTargets.Struct |
        AttributeTargets.ReturnValue,
        AllowMultiple = false,
        Inherited = false)]
    public sealed class LifetimeAnnotationAttribute : Attribute
    {
        public LifetimeAnnotationAttribute(bool isRefScoped, bool isValueScoped)
        {
            IsRefScoped = isRefScoped;
            IsValueScoped = isValueScoped;
        }
        public bool IsRefScoped { get; }
        public bool IsValueScoped { get; }
    }
}
```

### API Usage

For the following method..
```C#
static Span<T> CreateWithoutCapture<T>(scoped ref T t) { ... }
```
... the compiler will emit an attribute to the assembly metadata that indicates the `ref T t` parameter is scoped.
```C#
static Span<T> CreateWithoutCapture<T>(
    [LifetimeAnnotation(isRefScoped: true, isValueScoped: false)] ref T t) { ... }
```

Annotations will be generated by the C# compiler.

The C# compiler reserves the attribute for compiler use only.

If the attribute type is _not declared_ in the runtime or in source, the C# compiler will emit an attribute type declaration with the proposed API but with `internal` accessibility.

When importing metadata, the compiler will match the attribute by namespace and type name only, so the attribute type may be declared as an `internal` type in multiple assemblies.

### Alternative Designs

If the attribute type is _not declared_ in the runtime or in source, the C# compiler will emit an attribute type declaration with the proposed API but with `internal` accessibility.

For reference, the `NativeIntegerAttribute`, which is also generated by the C# compiler, _was not added_ to the runtime - see [issues/38683#issuecomment](https://github.com/dotnet/runtime/issues/38683#issuecomment-653136856).

### Risks

Should the attribute API be generalized to potentially allow future scenarios?
Allow more `AttributeTargets`?
Replace the `IsRefScoped` and `IsValueScoped` properties with a single `int` value representing a set of _scope bits_?

**Comment by cston** [comment]
cc @jaredpar, @AaronRobinsonMSFT

**Comment by terrajobst** [comment]
@cston @jaredpar This should be closed because we decided to let the compiler synthesize as needed, rigth?

**Comment by jaredpar** [comment]
Correct. will close.
