### ISSUE TITLE
Temporarily disabling Win-ARM64 testing in PR

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#68626]
Due to decreased capacity in our Helix Win-arm64 queue while we solve some product-impacting imaging issues, we are disabling testing windows arm64 against runtime tests for the time being. Tests will still run in rolling builds of the runtime twice a day and other stress flavors. We will update this issue as we get more information regarding ETAs and test availability. If you expect your change to be potentially impactful to ARM64, please exercise caution and test offline if possible or abstain from merging until this work item is done. 

Context: https://github.com/dotnet/runtime/pull/67771

**Comment by vcsjones** [comment]
If this was fixed should this get unpinned from the issue list?
