### ISSUE TITLE
[API Proposal]: Add new Task() constructors to be consistent with Task.Run()

### ISSUE THREAD

**Issue by heathbm** [dotnet/runtime#68637]
### Motivation:

Using `Task.Run()` and `new Task()` interchangeably with an async lambda `async () => ...` does not work the same as expected. 
I believe developers expect these to work the same, with the exception of `Task.Run()` starting immediately.

### Background:

When a developer uses `Task.Run()` and provides an async lambda `async () => ...`, it is correctly passed to: `public static Task Run(Func<Task?> function)`.

Example (this **passes**):

```C#
[Fact]
async Task TaskRunWorks()
{
    int taskProgress = 0;
    var oneSecond = TimeSpan.FromSeconds(1);

    await Task.Run(async () =>
    {
        await Task.Delay(oneSecond);
        Interlocked.Increment(ref taskProgress);
    });

    Assert.Equal(1, taskProgress);
}
```

However, when a developer uses `new Task()` and provides an async lambda `async () => ...`, it is passed to: `public Task(Action action)`, as there is no constructor with a `Func<Task?>` parameter. So the await in the async lambda will not be respected as it is treated as an `Action`.

Example (this **fails**):

```C#
[Fact]
async Task TaskStartFails()
{
    int taskProgress = 0;
    var oneSecond = TimeSpan.FromSeconds(1);

    var aTask = new Task(async () =>
    {
        await Task.Delay(oneSecond);
        Interlocked.Increment(ref taskProgress);
    });

    aTask.Start();
    await aTask;

    Assert.Equal(1, taskProgress); // Fail: taskProgress will be 0
}
```

### API Proposal

The addition of the following constructors in: https://github.com/microsoft/referencesource/blob/master/mscorlib/system/threading/Tasks/Task.cs

### Current constructors:

```C#
public Task(Action action);
public Task(Action action, CancellationToken cancellationToken);
public Task(Action action, TaskCreationOptions creationOptions);
public Task(Action<object?> action, object? state);
public Task(Action action, CancellationToken cancellationToken, TaskCreationOptions creationOptions);
public Task(Action<object?> action, object? state, CancellationToken cancellationToken);
public Task(Action<object?> action, object? state, TaskCreationOptions creationOptions);
public Task(Action<object?> action, object? state, CancellationToken cancellationToken, TaskCreationOptions creationOptions);
```

### New constructors:
Add a copy of each of the current constructors, replacing the `Action` with `Func<Task?>`

```C#
public Task(Func<Task?> function);
public Task(Func<Task?> function, CancellationToken cancellationToken);
public Task(Func<Task?> function, TaskCreationOptions creationOptions);
public Task(Func<Task?> function, object? state);
public Task(Func<Task?> function, CancellationToken cancellationToken, TaskCreationOptions creationOptions);
public Task(Func<Task?> function, object? state, CancellationToken cancellationToken);
public Task(Func<Task?> function, object? state, TaskCreationOptions creationOptions);
public Task(Func<Task?> function, object? state, CancellationToken cancellationToken, TaskCreationOptions creationOptions);
```

### API Usage

Simply:

```C#
[Fact]
async Task TaskStartPasses()
{
    int taskProgress = 0;
    var oneSecond = TimeSpan.FromSeconds(1);

    var aTask = new Task(async () =>
    {
        await Task.Delay(oneSecond);
        Interlocked.Increment(ref taskProgress);
    });

    aTask.Start();
    await aTask;

    Assert.Equal(1, taskProgress); // Passes!
}
```

Also:

```C#
async Task TaskStartWithReferencedMethod()
{
    var aTask = new Task(AnAsyncMethod);

    aTask.Start();
    await aTask;
}

async Task AnAsyncMethod()
{
    await Task.Delay(100);
}
```

### Risks

Any async lambdas `async () => ...` that are currently being passed to the `Action` constructor will now be picked up by the new constructor and their awaits will now be respected in the context of the new `Task`.

I am not sure if this is a risk, but if a developer did use `new Task()` incorrectly previously, their task will now wait, which could be surprising if it was long running.

**Comment by stephentoub** [comment]
Thanks.  I understand the desire for symmetry here, but I don't think these should be added.
1. We largely wish even the existing Task constructors (and Start) hadn't been exposed.  The use case for these is extremely niche, they get folks into trouble when accidentally exposing tasks that haven't been started, and they make it much more difficult to optimize the task implementation the way we'd like to.
2. Task.Run is able to handle `Func<Task>` delegates because it controls the `Task` object that's returned.  But without massive runtime hacks, the Task constructor can't control what Task is instantiated, which means the Task itself has to somehow perform the equivalent of `Unwrap` but marshaling back to itself rather than to a new instance.  The infrastructure for this doesn't exist, which would make these complicated to implement, with non-trivial expense.
3. You can already achieve this with `Unwrap`, e.g. `Task<Task> t = new Task<Task>(func); t.Start(); return t.Unwrap();`.

**Comment by heathbm** [comment]
> Thanks. I understand the desire for symmetry here, but I don't think these should be added.
> 
> 1. We largely wish even the existing Task constructors (and Start) hadn't been exposed.  The use case for these is extremely niche, they get folks into trouble when accidentally exposing tasks that haven't been started, and they make it much more difficult to optimize the task implementation the way we'd like to.
> 2. Task.Run is able to handle `Func<Task>` delegates because it controls the `Task` object that's returned.  But without massive runtime hacks, the Task constructor can't control what Task is instantiated, which means the Task itself has to somehow perform the equivalent of `Unwrap` but marshaling back to itself rather than to a new instance.  The infrastructure for this doesn't exist, which would make these complicated to implement, with non-trivial expense.
> 3. You can already achieve this with `Unwrap`, e.g. `Task<Task> t = new Task<Task>(func); t.Start(); return t.Unwrap();`.

@stephentoub Thanks for the reply, that makes sense. I have created an issue under Rosyln analyzers as I believe a warning might help the example I provided. https://github.com/dotnet/roslyn-analyzers/issues/5981
