### ISSUE TITLE
IHttpClientBuilder should have extension to redact query parameter from logging

### ISSUE THREAD

**Issue by anktsrkr** [dotnet/runtime#68675]
The current implementation of  Microsoft.Extensions.Http logging framework redact headers value based on user input however it does not support redact sensitive information from query parameters, which is kind of security issue.

![image](https://user-images.githubusercontent.com/5505886/165830843-82034535-cb04-46b9-a994-8178f5b02d4e.png)

For customers that are more concerned about this logging risk or have to meet audit requirements for all their integrated services it is important to redact query parameters value based on users input. 

The problem lies here - 

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingScopeHttpMessageHandler.cs#L133

We could implement this feature same way as we have a extension in  IHttpClientBuilder to redact from header. 

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientBuilderExtensions.cs#L463

We might name this extension  `RedactLoggedQueryParameters`

Thanks,
Ankit S

**Comment by CarnaViire** [comment]
Thanks for raising the concern @anktsrkr.

As a quick workaround for the time being, you can consider removing the logging entirely by putting that code after all your `HttpClient` registrations in `ConfigureServices`:
```c#
services.RemoveAll<IHttpMessageHandlerBuilderFilter>();
```

**Comment by CarnaViire** [comment]
Triage: URIs aren’t meant to contain secrets for various reasons, e.g. proxies. But we still might want to add some way to control this. Given there's a workaround, moving to future.

**Comment by CarnaViire** [comment]
Note that #74339 asked for redacting not only query parameters, but path as well

**Comment by MihaZupan** [comment]
FWIW, even the [new HTTP logging in ASP.NET](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-6.0) defaults to logging the path (though it is configurable).

**Comment by CarnaViire** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/77312
