### ISSUE TITLE
Unable to pin arrays of unmanaged structs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#68686]
Repro:
```csharp
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: DisableRuntimeMarshallingAttribute]

object o = new MyStruct[10];
GCHandle h = GCHandle.Alloc(o, GCHandleType.Pinned);

struct MyStruct
{
    char c;
}
```
Actual result: System.ArgumentException: Object contains non-primitive or non-blittable data.
Expected result: No exceptions

**Comment by jkotas** [comment]
It should be possible to pin all types that are otherwise allowed for interop.

We can either fix this by relaxing the GCHandle argument check in DisableRuntimeMarshallingAttribute context only; or we can delete the blittability argument check on GCHandle completely (it is artificial limitation). A middle ground would be to allow pinning of any unmanaged types (ie types without GC references, regardless of the context). Any preferences?

I think that my preference would be to do the middle-ground fix.

**Comment by AaronRobinsonMSFT** [comment]
> I think that my preference would be to do the middle-ground fix.

Agree. I think this makes good sense and will help further remove the unmanaged vs blittable confusion that exists. I do have a slight concern about the cross-target scenario though. Given this is a runtime check, a problem exists if I decide to use this and then target .NET 6 and .NET 7. I would need to also check when this will be okay at runtime. I fear that would clutter code with runtime version checks.

Removing this check when `DisableRuntimeMarshallingAttribute` is set is a no-brainer and should just be done.

**Comment by elinor-fung** [comment]
> Given this is a runtime check, a problem exists if I decide to use this and then target .NET 6 and .NET 7. I would need to also check when this will be okay at runtime. I fear that would clutter code with runtime version checks.

I feel like it is not unreasonable to say that this is an new usage scenario that a new version of .NET allows, so either accept some less-than-pretty checks or don't depend on it when cross-targeting?

**Comment by jkotas** [comment]
Changing exception into reasonable non-throwing behavior is not generally considered a breaking change (https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#exceptions).

**Comment by AaronRobinsonMSFT** [comment]
> I feel like it is not unreasonable to say that this is an new usage scenario that a new version of .NET allows, so either accept some less-than-pretty checks or don't depend on it when cross-targeting?

Not unreasonable. Another way to look at this is to slowly open support. In .NET 7, it is permissible only under `DisableRuntimeMarshallingAttribute` in .NET 8, we open up more. By the time it is the default targeting unsupported runtimes could be diminished. Not convinced by this logic just offering it.

> Changing exception into reasonable non-throwing behavior is not generally considered a breaking change (https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/breaking-change-rules.md#exceptions).

That is a good reference. However, that is going in the wrong direction from where I'm arguing. The non-throwing behavior is relaxing a constraint .NET 6 -> .NET 7. My concern is I'm targeting .NET 7 but have customers on .NET 6 that want to use my library. If this semantic could be checked at compile time, then the debate is over. It is the non-obvious behavioral change that occurs when one goes back .NET 7 -> .NET 6.

I'd imagine this behavior is going to be very interesting to Interop source generators. Which means there could be a proliferation of semantic poly-fill in those cases. Basically, in .NET 7 the code is obvious, but in .NET 6 one needs to copy a lot to pass through.

I'm not fully convinced my concern is warranted and it seems like neither of you are buying it. I suppose the other perspective here is the sooner we permit this the sooner people can adopt the behavior and benefit from it - it isn't like a change like this will get any better in a future release.

**Comment by AaronRobinsonMSFT** [comment]
> There are many (hundreds?) bug fixes and behavior enhancements in every major .NET version that have this nature. We do not consider it a problem.

That is a rather broad statement. This isn't a bug fix and even if it was, we very publicly stated that we reserve the right to fix bugs that alter behavior. Therefore, this case falls into the behavior enhancement argument. I agree this is worth the effort, but this feels very much like other built-in marshalling behavior that we've been reluctant to change - even across major version boundaries. That is a forwards compat argument not the backwards compat I am bringing up, but the change can have the same surprise effect.

> I might be missing what you mean, but if a .NET 6 application is trying to consume library that was built targeting .NET 7 and run on a .NET 6 runtime, there would be some serious hijinks going on to get that to load/run.

I mean development of a class library on .NET 7 and then multi-targeting across multiple Frameworks. A valid .NET 6 class library will be generated without any indication a large functional limitation exists in earlier runtimes. I say large based on what is required to work around the lack of support.

I am all in on changing this to the suggested middle ground. Simply not convinced based on the arguments above. I'm trying to build the mental model for how to justify this change relative to other semantic changes we've rejected in the past. We can move on and just get it done. I'm not hearing any concerns and that does provide some confidence.

**Comment by tannergooding** [comment]
I think the worst case scenario is we don't backport the same fix to 6 and then we get some amount of customer feedback complaining which then warrants us making that backport.

Otherwise, customers can target .NET 7 and have to wait at most 1 year until .NET 8 for the next LTS to get consistent behavior. .NET 6 customers who are staying on until EoL would have until just after .NET 9 to deal with the difference before it becomes unsupported. So its no worse than 2 years for a given LTS to have the "differing" behavior.
