### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_ExactVersion_Success(uri: \"https://www.litespeedtech.com/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#68692]
Run: [runtime-libraries-coreclr outerloop 20220428.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1742100&view=ms.vss-test-web.build-test-results-tab&runId=47089794&paneView=debug&resultId=105683)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.Public_Interop_ExactVersion_Success(uri: \"https://www.litespeedtech.com/\")

```
**Error message:**
```
Assert.Equal() Failure
Expected: OK
Actual:   Forbidden


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.Public_Interop_ExactVersion_Success(String uri) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 597
--- End of stack trace from previous location ---
```

**Comment by rzikm** [comment]
Similar failure occured the day before as well, so far 6 hits in total.

Possible cause is (temporary) unreachability of https://www.litespeedtech.com. Probably not actionable right now, but if this starts to occur more frequently, we might consider removing this particular host from tests.
