### ISSUE TITLE
System.Private.CoreLib's fast up-to-date check is broken

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#68698]
When building System.Runtime's src project, which depends on System.Private.CoreLib without making any changes to any of the assemblies, Systme.Private.CoreLib always incrementally builds:

```
1>------ Build started: Project: System.Private.CoreLib, Configuration: Debug x64 ------
1>System.Private.CoreLib -> C:\git\runtime5\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll
========== Build: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========

1>------ Build started: Project: System.Private.CoreLib, Configuration: Debug x64 ------
1>System.Private.CoreLib -> C:\git\runtime5\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll
========== Build: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========

1>------ Build started: Project: System.Private.CoreLib, Configuration: Debug x64 ------
1>System.Private.CoreLib -> C:\git\runtime5\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll
========== Build: 1 succeeded, 0 failed, 5 up-to-date, 0 skipped ==========
```

This shouldn't happen as Visual Studio caches inputs and outputs and makes sure that a project's build isn't even triggered when nothing changed.

cc @dotnet/runtime-infrastructure @trylek @agocke @jkotas

**Comment by ViktorHofer** [comment]
I already found the relevant documentation: https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md#sdk-style-projects.

```
3>FastUpToDate: Output 'C:\git\runtime5\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.pdb' does not exist, not up-to-date. (System.Private.CoreLib)
```

**Comment by ViktorHofer** [comment]
Found the culprit. These two targets move the pdb from the build directory into a separate location and because of that invalidate the output: https://github.com/dotnet/runtime/blob/86565188c0e6edbc79a89ef3ebae40ca2551ae2b/src/coreclr/Directory.Build.targets#L11-L35

@trylek @agocke @jkotas does the pdb need to be moved or can it be copied instead?

**Comment by danmoseley** [comment]
The comment there mentions that they'd otherwise be overwritten. Are any outputs being updated in place? Moves and updates in place both make incremental build harder.

**Comment by agocke** [comment]
Yeah, each could be placed in a separate directory for its project, I think. I was just working around the NativeAOT/IL S.P.C collision. The broad view is having separate directories, instead of just for AOT

**Comment by ViktorHofer** [comment]
If I have some time I would be willing to send a PR to fix this. @jkotas @agocke just to clarify, did you mean that the pdb from the get-go should be placed into the `$(RuntimeBinDir)PDB` / `$(RuntimeBinDir)PDB/aotsdk` directory or that the pdb belongs into the output directory of System.Private.CoreLib and that whatever tool requires the pdbs, should look into the project's individual output directories?
