### ISSUE TITLE
Blazor Publish Emscripten Deadlocked

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#68708]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-Publish-Emscripten-Deadlocked/10024138)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Version 17.2.0 Preview 4.0 & 5.0]
Publish Fails with message:

Warning : Accessing the Emscripten cache at "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\emscripten\cache" is taking a long time, another process should be writing to it. If there are none and you suspect this process has deadlocked, try deleting the lock file "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\emscripten\cache\cache.lock" and try again.

If this occurs deterministically, consider filing a bug.

---
#### Feedback Bot on 4/26/2022, 06:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@lewing FYI

**Comment by lewing** [comment]
@radekdoulik what is the status of this?

**Comment by jjzhang12** [comment]
With Visual Studio 2022 Version 17.6.0 Preview 3.0, .net 8.0 preview 3, just create the Blazor WebAssembly project from template, add nuget to SkiaSharp.Views.Blazor 2.88.3 and add <SKCanvasView/> to index.razor and compile the project, the compilation hangs with this error.

**Comment by LostBeard** [comment]
I can confirm that simply adding <WasmBuildNative>true</WasmBuildNative> to a new Blazor WebAssembly project .csproj leads to the Emscripten cache deadlock.

**Comment by lewing** [comment]
this has been resolved in later previews
