### ISSUE TITLE
Hello world sample fail native AOT

### ISSUE THREAD

**Issue by rodrigovaras** [dotnet/runtime#68711]
### Description

Tried a hello world on my WSL Ubuntu attempting to test the native AOT support

### Reproduction Steps

- dotnet new console --name "ConsoleApp1"
- add native AOT package reference and nuget.config
- dotnet publish -r linux-x64 -c Release -p:CppCompilerAndLinker=clang-9 --self-contained

### Expected behavior

Build succeed

### Actual behavior

Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp1 -> /home/rodrigov/ConsoleApp1/bin/Release/net6.0/linux-x64/ConsoleApp1.dll
  /usr/bin/ld: cannot find -lz
clang : error : linker command failed with exit code 1 (use -v to see invocation) [/home/rodrigov/ConsoleApp1/ConsoleApp1.csproj]
/home/rodrigov/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/build/Microsoft.NETCore.Native.targets(338,5): error MSB3073: The command "clang-9 "obj/Release/net6.0/linux-x64/native/ConsoleApp1.o" -o "bin/Release/net6.0/linux-x64/native/ConsoleApp1" /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/sdk/libbootstrapper.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/sdk/libRuntime.WorkstationGC.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/framework/libSystem.Native.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/framework/libSystem.Globalization.Native.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/framework/libSystem.IO.Compression.Native.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/framework/libSystem.Net.Security.Native.a /home/rodrigov/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22229.2/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lrt -pie -Wl,-z,relro -Wl,-z,now -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/home/rodrigov/ConsoleApp1/ConsoleApp1.csproj]

**Comment by smhmhmd** [comment]
Do you have the linker ?
>/usr/bin/ld: cannot find -lz
>clang : error : linker command failed with exit code 1 (use -v to see invocation)

**Comment by rodrigovaras** [comment]
i use this -> sudo apt install clang-9 --install-suggests

**Comment by josephmoresena** [comment]
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/prerequisites.md

**Comment by rodrigovaras** [comment]
> 

Thanks, was about to report that I figure out by adding running this -> sudo apt install zlib1g-dev
