### ISSUE TITLE
Consider adding more tests for the Equals instance method for the various vector types

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#68710]
https://github.com/dotnet/runtime/pull/68691 fixed the implementation of the `Equals(T other)` methods for the various vector and vector like types (Vector2/3/4, Vector<T>, Vector64/128/256<T>, Plane, Quaternion, Matrix3x2, and Matrix4x4) to correctly take `NaN` into account.

It would be beneficial to add additional test covering over non-canonicalized NaNs to ensure other regressions or mis-optimizations don't sneak by in the future.

**Comment by DDolG** [comment]
Hello.
I would like to help.
If you don't mind, can you explain to me what "non-canonicalized NaNs" means? As I understand it, mis-optimizations need to be checked using benchmarks?
I will be very grateful to you.

**Comment by Hafthor** [comment]
so something like this?

    [Fact]
    public void VectorDoubleEqualsNegativeNaNTest()
    {
        var dnan = new double[] { double.NaN };
        var lnan = MemoryMarshal.Cast<double, ulong>(dnan.AsSpan());
        lnan[0] ^= 0x8000000000000000ul; // flip the sign bit
        var nan = new Vector<double>(dnan[0]);
        Assert.True(nan.Equals(nan));
    }

and maybe a test with a randomish significand?

What should be the result of .Equals on two NaNs that are 'internally' not the same?

Also, I worry that someone will short-circuit out your existing nan.Equals(nan) tests with a reference test, so we should compare two different vectors, right?

**Comment by tannergooding** [comment]
Sorry for the delay, we were locking down on .NET 7 RC1 and then I was on vacation.

> If you don't mind, can you explain to me what "non-canonicalized NaNs" means? 

`double.NaN` and `float.NaN` are the "canonical" `NaN` representation, this is typically a negative quiet NaN with no payload.

Ideally the tests also validate cases like:
* positive quiet NaN
* negative signaling NaN
* positive signaling NaN

And testing each of these 4 with and without a payload (non-zero mantissa bits).

> so something like this?

`MemoryMarshal` in general is something you want to use sparingly. It tends to be fairly expensive, slow, and may not do exactly what you want.

For converting a `double/float` to and from its bitwise integral representation, the following APIs are better:
* `BitConverter.DoubleToInt64Bits`
* `BitConverter.Int32BitsToSingle`
* `BitConverter.Int64BitsToDouble`
* `BitConverter.SingleToInt32Bits`

There are also corresponding apis to convert to/from `UInt32` and `UInt64` as well as APIs covering `Int16/UInt16` for `System.Half`

> What should be the result of .Equals on two NaNs that are 'internally' not the same?

`NaN == NaN` should always return `false`, even for two bitwise equivalent `NaN`

`NaN.Equals(NaN)` should always return `true`, even for two `NaN` that are not bitwise equivalent

> Also, I worry that someone will short-circuit out your existing nan.Equals(nan) tests with a reference test, so we should compare two different vectors, right?

`Vectors` are value types, so you can't short circuit them with a reference test.

**Comment by Hafthor** [comment]
Raised PR for this. Attempted to include tests for System.Half, but these weren't working so I removed those and just have tests for non-canonical NaN equality for double and float. https://github.com/dotnet/runtime/pull/74517

**Comment by DDolG** [comment]
hello. I am very sorry to you. I got sick, so I couldn't reply to messages promptly.
