### ISSUE TITLE
BinaryFormatter exception message text should be clearer when the target project type killbits NRBF serialization

### ISSUE THREAD

**Issue by janseris** [dotnet/runtime#68723]
### Description

Solution: use System.Text.Json serializer dotnet/runtime#68723 _(note: it uses `base64` encoding for `byte[]`, that means +33 % size)_

The workaround to enable binary serialization using     `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`
doesn't do anything in MAUI .csproj - the application still doesn't want to use binary serialization.

Exception message:  `BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.`

Binary serialization works fine on MAUI Windows.

The task is to serialize objects of this class object _stored in a `Dictionary` by `ID`_ to disk for offline usage:
_**This seems nearly impossible to do using XML or JSON serializers so far because of inheritace, interfaces, circular references etc. (with MessagePack library, still circular references problem).**_

What I have to do without `BinaryFormatter` is to clear all `Parent` and `Children` properties before serialization (write to disk) and recreate all of the after deserialization (read from disk) which is _unnecessary overhead and code complexity_.

![image](https://user-images.githubusercontent.com/64279914/165479209-86455526-d2b6-489f-b35a-83310ebe881e.png)

### Steps to Reproduce

`    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>` in MAUI .csproj where binary serialization is used

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

**Comment by akoeplinger** [comment]
We hardcode the implementation of BinaryFormatter to throw PlatformNotSupported on mobile here: https://github.com/dotnet/runtime/blob/77a87df24807d750513607accd7032a57795a201/src/libraries/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj#L77-L79

We should probably create a copy of the [exception message](https://github.com/dotnet/runtime/blob/77a87df24807d750513607accd7032a57795a201/src/libraries/System.Runtime.Serialization.Formatters/src/Resources/Strings.resx#L252-L254) and emphasize that you can't override this. Updating the aka.ms page to list the workloads where this is not overridable would probably be good too.

**Comment by GrabYourPitchforks** [comment]
I've changed the work item title to more accurately reflect the necessary work.
