### ISSUE TITLE
[API Proposal]: Add non-allocating overload of JsonEncodedText.Encode that allows the caller to own the memory

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#68747]
### Background and motivation

Today `JsonEncodedText.Encode` copy the `byte[]` passed in, even in the case when there's nothing to escape. There should be an overload that can un-escape the JSON text without allocating (allowing the caller to pass in the span).

### API Proposal

```csharp
namespace System.Text.Json;

public class JsonEncodedText
{
    public static OperationStatus Unescape(ReadOnlySpan<byte> utf8, Span<byte> escapedUtf8, out int bytesWritten);
}
```

### API Usage

```csharp
var utf8 = "Hello\""u8;
Span<byte> unescaped = stackalloc byte[128];
_ = JsonEncodedText.Unescape(utf8, unescaped, out var bytesWritten);
// In most cases, we don't need to convert to a string though 😄 
Console.WriteLine(Encoding.UTF8.GetString(unescaped[..bytesWritten]));
```

**Comment by teo-tsirpanis** [comment]
Shouldn't one of the two `ReadOnlySpan`s be a `Span`?

**Comment by davidfowl** [comment]
Fixed

**Comment by eiriktsarpalis** [comment]
Possibly related to #54410? Given that the proposed method does not deal with `JsonEncodedText` instances, wouldn't it make more sense to expose unescaping functionality in `Utf8JsonReader` or simply expose the `JsonReaderHelper` class?
