### ISSUE TITLE
[API Proposal]: Add equality operations on string for ReadOnlySpan<char>

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#68746]
### Background and motivation

In order to do string comparisons today the overloads require string (which are immutable/unpoolable and allocated). It should be possible to compare a string to a ReadOnlySpan\<char\> without allocating. Today this is possible if you dig and find [CompareInfo.Compare](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.compareinfo.compare?view=net-6.0#system-globalization-compareinfo-compare(system-readonlyspan((system-char))-system-readonlyspan((system-char))-system-globalization-compareoptions)) but some of these operations should be hoisted as first class on string.

Related: https://github.com/dotnet/runtime/issues/27229

### API Proposal

```csharp
namespace System;

public class String
{
    public bool Equals(ReadOnlySpan<char> value, StringComparison comparisonType);
}

public static class MemoryExtensions
{
    public static bool Equals(this ReadOnlySpan<char> value1, ReadOnlySpan<char> value2, StringComparison comparisonType);
}
```

### API Usage

```csharp

bool IsHelloWorld(ReadOnlySpan<char> key)
{
    retun "Hello World".Equals(key);
}
```

### Risks

I'm hoping this won't result in any ambiguity between the string overload and ReadOnlySpan\<char\> overload.

**Comment by stephentoub** [comment]
> It should be possible to compare a string to a ReadOnlySpan<char> without allocating. Today this is possible if you dig and find CompareInfo.Compare

You can already do:
```
return key.Equals("Hello World");
```
and
```
retun "Hello World".AsSpan().Equals(key);
```

> API Usage
> retun "Hello World".Equals(key);

The proposed method won't let you write that. Did you intend to have another comparison-less overload? Or for that parameter to be optional?

**Comment by davidfowl** [comment]
Ah I kept trying to use `StringComparer` instead of the `StringComparion` enum. Thanks.

**Comment by davidfowl** [comment]
The overloads are hard to find because you need to start from the Span side of things. I kept looking for string.Equals(ReadOnlySpan<char>, ...)
