### ISSUE TITLE
[API Proposal]: new System.ComponentModel.DateOnlyConverter and System.ComponentModel.TimeOnlyConverter classes

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#68743]
### Background and motivation

Converting between `System.DateOnly` or `System.TimeOnly` and `string` is currently not supported using a `System.ComponentModel.TypeConverter`. Many system types are supported out of the box (`System.DateTimeOffset`, `System.Guid`, `System.TimeSpan`, `System.Uri` etc.) so I think `System.DateOnly` and `System.TimeOnly` would be welcome additions.

I was expecting this to work, but converting from string actually throws:
> System.NotSupportedException: TypeConverter cannot convert from System.String.

```csharp
TypeConverter dateOnlyConverter = TypeDescriptor.GetConverter(typeof(DateOnly));
DateOnly? date = dateOnlyConverter.ConvertFromString("1940-10-09") as DateOnly?;
```

```csharp
TypeConverter timeOnlyConverter = TypeDescriptor.GetConverter(typeof(TimeOnly));
TimeOnly? time = timeOnlyConverter.ConvertFromString("7:00") as TimeOnly?;
```

Having built-in support for type conversion would probably help to drive adoption of the relatively new `DateOnly` and `TimeOnly` type.

Addressing this issue would fix #59253 which is mentioned in [System.Runtime work planned for .NET 7](https://github.com/dotnet/runtime/issues/64603) (but only under the _Backlog_ list, not the _Planned for .NET 7_ list).

### API Proposal

```csharp
namespace System.ComponentModel
{
    public class DateOnlyConverter : System.ComponentModel.TypeConverter
    {
        public DateOnlyConverter() { }
        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Type sourceType) { throw null; }
        public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext? context, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] System.Type? destinationType) { throw null; }
        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value) { throw null; }
        public override object? ConvertTo(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object? value, System.Type destinationType) { throw null; }
    }

    public class TimeOnlyConverter : System.ComponentModel.TypeConverter
    {
        public TimeOnlyConverter() { }
        public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Type sourceType) { throw null; }
        public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext? context, [System.Diagnostics.CodeAnalysis.NotNullWhen(true)] System.Type? destinationType) { throw null; }
        public override object? ConvertFrom(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object value) { throw null; }
        public override object? ConvertTo(System.ComponentModel.ITypeDescriptorContext? context, System.Globalization.CultureInfo? culture, object? value, System.Type destinationType) { throw null; }
    }
}
```

### API Usage

Using the converter would most likely happen through `TypeDescriptor.GetConverter(typeof(…))`: 

```csharp
var dateOnlyConverter = TypeDescriptor.GetConverter(typeof(DateOnly));
var date = dateOnlyConverter.ConvertFromString("1940-10-09") as DateOnly?;

var timeOnlyConverter = TypeDescriptor.GetConverter(typeof(TimeOnly));
var time = timeOnlyConverter.ConvertFromString("7:00") as TimeOnly?;
```

or even through a higher level abstractions such as [Microsoft.Extensions.Configuration.Binder](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder/) (which also uses `TypeDescriptor.GetConverter` internally) as described in #64739:

```csharp
// Let's make the end of the world date configurable because we're not really sure about that date
var configuration = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string>
    {
        ["EndOfWorldDate"] = "2012-12-21",
        ["BreakfastTime"] = "7:00:00",
    })
    .Build();
var endOfTheWorldDate = configuration.GetValue<DateOnly>("EndOfWorldDate");
var breakfastTime = configuration.GetValue<TimeOnly>("BreakfastTime");
```

It could also be used by directly creating a `DateOnlyConverter` or `TimeOnlyConverter` instance but this is a less likely scenario.

### Alternative Designs

To the best of my knowledge, there's no alternative design that would make sense for adding new `System.ComponentModel.TypeConverter` subclasses.

### Risks

`System.ComponentModel.DateOnlyConverter` and `System.ComponentModel.TimeOnlyConverter` being a new classes, no risks are introduced.

**Comment by tarekgh** [comment]
Could you please consolidate this proposal with the one in https://github.com/dotnet/runtime/issues/68744? there is no need to track them in two different proposals.

**Comment by tarekgh** [comment]
@thomaslevesque that is right. I believe the ask is to avoid having different users implement the same converters to make their scenarios work.

**Comment by tarekgh** [comment]
@0xced I am noticing some differences comparing the proposal to like [DateTimeConverter](https://github.com/dotnet/runtime/blob/334989f6cc0600f9c12e9fa989dc1814c8300d1d/src/libraries/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs#L354). Any reason for that? you are proposing to have the extra API `IsValid`  and also you are missing the public constructor and the nullability annotaions.

**Comment by tarekgh** [comment]
@0xced I have updated the APIs in the proposal. Let's me know if you have any concern.

**Comment by bartonjs** [comment]
We added System.Half, Int128, and UInt128 to the list to get caught up on primitive-ish types in the TypeConverter space.  (We didn't think there was enough of a scenario for NFloat, NInt, or NUInt).

```C#
namespace System.ComponentModel
{
    public class DateOnlyConverter : System.ComponentModel.TypeConverter
    {
        public DateOnlyConverter() { }
    }

    public class TimeOnlyConverter : System.ComponentModel.TypeConverter
    {
        public TimeOnlyConverter() { }
    }

    public class HalfConverter : System.ComponentModel.BaseNumberConverter
    {
        public HalfConverter() { }
    }

    public class Int128Converter : System.ComponentModel.BaseNumberConverter
    {
        public Int128Converter() { }
    }

    public class UInt128Converter : System.ComponentModel.BaseNumberConverter
    {
        public UInt128Converter() { }
    }
}
```

**Comment by 0xced** [comment]
Thank you for implementing this, Tarek and Jeremy!
