### ISSUE TITLE
DateTime.Now from .NET 6 will return UTC time, not local time in docker engine on CentOS

### ISSUE THREAD

**Issue by arashkarami** [dotnet/runtime#68759]
### Description

Hi, After building and running a docker-image on centOS machine, When I called DateTime.Now, I got UTC time in my application instead of a local time! I'd already read about this problem in these issues: #59636 and #60469 and they said will fix in net6.0 but seem it is not true. Do you have any idea about this?
Thank you

### Reproduction Steps

1. Install docker on CentOS 7.0 and set you local timezone. 
2. Running an console project docker iamge based on [ASP.NET Core Runtime ](https://hub.docker.com/_/microsoft-dotnet-aspnet)

### Expected behavior

local date time now

### Actual behavior

UTC DATETime

### Known Workarounds

https://github.com/dotnet/runtime/issues/63194
https://github.com/dotnet/runtime/issues/60469
https://github.com/dotnet/runtime/issues/59636

### Configuration

https://hub.docker.com/_/microsoft-dotnet-aspnet
NET6.0

**Comment by danmoseley** [comment]
@tarekgh I believe has context from previous times this came up.

**Comment by arashkarami** [comment]
@danmoseley, Yes, I saw a lot of issues about this problem, but it's not solved yet.

**Comment by Clockwork-Muse** [comment]
> set you local timezone

... how are you setting the local timezone?  Most of those issues are people `-v`-mounting local files, which you aren't supposed to be doing, given those threads.

> local timezone

It's also fairly unusual to run the server process in "local" time (as opposed to running a request in the local time of request-related entities).  Are you sure that you actually need to do this in the first place?

**Comment by arashkarami** [comment]
Yes, I'm sure, I set our local timezone but It is not worked.
 I checked a lot of solutions such as System.Globalization.CultureInfo.CurrentCulture.ClearCachedData(), change framework to .net 5.0, reinstall centOS, change physical server, ...  but it's not worked for me.

**Comment by deeprobin** [comment]
Are there differences with Docker Images based on systems which use `libc` (Debian, Ubuntu) vs. `musl` (Alpine)?

I'm not completely familiar with the topic yet, but I know that in the Docker environment, differences occur more often because of this.

**Comment by arashkarami** [comment]
I attach my docker file below, and I checked again my docker-engine localtime. I run this image and when I entered to this container, I see everythings is ok and time of this container is local time, but .net application time is UTC yet. 
`FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src


RUN dotnet restore "Test/Test.csproj"   
COPY . .
WORKDIR "/src/Test"
RUN dotnet build "Test.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Test.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Test.dll"]
`

**Comment by deeprobin** [comment]
I currently have no CentOS machine to reproduce.

Can you try using different base images? I recommend for this case `alpine3.15` and `bulleye` (I think thats the default).
See <https://github.com/dotnet/dotnet-docker/tree/main/src/runtime/6.0>

**Comment by Clockwork-Muse** [comment]
> time of this container is local time, but .net application time is UTC yet.

The container definition (the dockerfile) isn't sufficient information.  It isn't setting any of the relevant environment variables, or calling one of the relevant commands (which it shouldn't be anyways), and by default containers are usually written to use UTC.
You need to also include the `docker run` command you're using.

That aside, as mentioned in some of the threads you reference, it's unusual to need a specific timezone for a server/container, and doing so is usually a code smell.  Are you **sure** you need this?  What specific design problem are you trying to solve that wouldn't be better referencing a derived/retrieved entity timezone at request time?

**Comment by arashkarami** [comment]
Thanks, I append ENV TZ = 'my-current timezone' and solved it. But we do not need it in the previous version of dotnet core.

**Comment by Clockwork-Muse** [comment]
> But we do not need it in the previous version of dotnet core.

There's always been a requirement to specify the timezone in the container, because otherwise there's no way for it to discover that another timezone would be relevant.  The most likely thing is that you've been volume-mounting the timezone files, as in some of the other issues - behavior there did change (although it was problematic in 5).  You should double-check if that was the case, and if so remove those mounts (showing us the `docker run` command or the compose file or similar would have given us this information).

Note that if you're insisting on setting a timezone for a container, the recommendation will be to do it at runtime, via `-e TZ=<whatever>`, rather than baking it into the image itself.  However, writing a server application to require a specific timezone is almost always a code smell and bad practice, and you're instead advised to change your application so this is no longer a requirement.
