### ISSUE TITLE
NativeAOT: Garbage collector seems to not reclaim quickly

### ISSUE THREAD

**Issue by smhmhmd** [dotnet/runtime#68754]
### Description

The same program shows different total memory when compiled as dotnet vs NativeAOT.
The underlying gc is different (6.0 vs 7.00-preview*), but, the newer garbage collector/NativeAOT shows different behavior at the very least.

### Reproduction Steps

        // ubuntu@ip-172-31-24-113:~/gc$ cat build-dotnet.sh 
        //                    cp gc.csproj.dotnet gc.csproj
        //                    \rm -rf bin obj;  dotnet publish -c Release --self-contained -r linux-x64

       // ubuntu@ip-172-31-24-113:~/gc$ cat build-nativeaot.sh 
       //                     cp gc.csproj.nativeaot gc.csproj
       //                      \rm -rf bin obj;  dotnet publish -c Release --self-contained -r linux-x64 

        using System;

	namespace GCCollectIntExample
	{
	    class MyGCCollectClass
	    {
		private const long maxGarbage = 3000;

		static void Main()
		{
		    bool forceFullCollection = true;

		    MyGCCollectClass myGCCol = new MyGCCollectClass();
		    Console.WriteLine("Total Memory: {0}", GC.GetTotalMemory(forceFullCollection));

		    // Determine the maximum number of generations the system
		    // garbage collector currently supports.
		    Console.WriteLine("maxGarbage = {0}", maxGarbage);
		    Console.WriteLine("The highest generation is {0}", GC.MaxGeneration);

		    myGCCol.MakeSomeGarbage();

		    // Determine which generation myGCCol object is stored in.
		    Console.WriteLine("Generation: {0}", GC.GetGeneration(myGCCol));

		    // Determine the best available approximation of the number
		// of bytes currently allocated in managed memory.
		    Console.WriteLine("Total Memory: {0}", GC.GetTotalMemory(forceFullCollection));

		    // Perform a collection of generation 0 only.
		    GC.Collect(0);

		    // Determine which generation myGCCol object is stored in.
		    Console.WriteLine("Generation: {0}", GC.GetGeneration(myGCCol));

		    Console.WriteLine("Total Memory: {0}", GC.GetTotalMemory(forceFullCollection));

		    // Perform a collection of all generations up to and including 2.
		    GC.Collect(2);

		    // Determine which generation myGCCol object is stored in.
		    Console.WriteLine("Generation: {0}", GC.GetGeneration(myGCCol));
		    Console.WriteLine("Total Memory: {0}", GC.GetTotalMemory(forceFullCollection));
		}

		void MakeSomeGarbage()
		{
		    Version vt;

                     Console.WriteLine("Invoke function");
		    for(int i = 0; i < maxGarbage; i++)
		    {
			// Create objects and release them to fill up memory
			// with unused objects.
			vt = new Version();
		    }
                     Console.WriteLine("Exiting from function");
		}
	    }
	}

### Expected behavior

The dotnet version shows that memory was reclaimed immediately after exiting the function. The second  GC.Collect() call did not make a difference.
       $ ./gc
Total Memory: 29976
maxGarbage = 3000
The highest generation is 2
Invoke function
Exiting from function
Generation: 2
Total Memory: 67272
Generation: 2
Total Memory: 67272
Generation: 2
Total Memory: 67272

### Actual behavior

The NativeAOT version shows that memory was not reclaimed immediately after exiting the function. The second  GC.Collect() call did make a difference. There are variations between compilations.
Also, why is the initial total memory higher in the NativeAOT case ? It is higher even without any allocation.

$ ./gc
Total Memory: 48376
maxGarbage = 3000
The highest generation is 2
Invoke function
Exiting from function
Generation: 2
Total Memory: 187576
Generation: 2
Total Memory: 99800
Generation: 2
Total Memory: 91208

### Configuration

```
$ cat gc.csproj.dotnet 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
</PropertyGroup>

</Project>
```

```
$ cat gc.csproj.nativeaot 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
  </ItemGroup>

<PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
</PropertyGroup>

</Project>

```

**Comment by VSadov** [comment]
Since this is on Unix, there are some parts in GC suspension that are a bit behind, feature-wise, when compared to CoreCLR. This leak could be related.

I will take a look what is going on here.

**Comment by VSadov** [comment]
I do not think we have a problem here. 

`GetTotalMemory` is an API that makes a good effort at approximating how many bytes is occupied by live objects.
The set of live objects is generally unknown as objects get allocated and become unreachable all the time. Maintaining any kind of precision here for a live program would be extremely expensive. 

The only point when the set of live objects is precisely known is inside the GC at the end of Gen2 marking stage when the program is blocked. 
When the program is running, GC can only try to derive the live size from currently known metrics such as segment allocation watermarks, fragmentation, freelist info, etc...   If it has been a while since last full GC, the number could be very off.

The most deterministic number that we can get here is the total memory used shortly after a Gen2 and when the program is no longer allocating. We see that in this sample NativeAOT uses ~35% more managed memory. 

This is a very small program with a very small live object set, so the difference must be coming from the runtime itself. That is not very surprising since NativeAOT has higher fraction of its framework implemented in managed code, compared to CoreCLR. That is actually not a bad thing and is not something to worry about. 
When allocations really become a concern, they would most certainly be dominated by allocations made by the program.

**Comment by smhmhmd** [comment]
>We see that in this sample NativeAOT uses ~35% more managed memory.
Why is that ?
Is the expectation that NativeAOT workloads need more memory than running in dotnet ?

**Comment by Maoni0** [comment]
this is not about GC being aggressive or not; since you are doing all gen2 GCs, GC is not participating in determining object life time. this is explained [here](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#1-the-generational-aspect). so the question is who's holding onto these objects that survived. I would suggest to compare the objects survived at the end of your main method (you can do something like Console.ReadLine at the end and attach a debugger) and do a !gcroot on the extra ones which will show you what's holding those objects live.

**Comment by smhmhmd** [comment]
@Maoni0 

>I would suggest to compare the objects survived at the end of your main method (you can do something like Console.ReadLine at the end and attach a debugger) and do a !gcroot on the extra ones which will show you what's holding those objects live.

@beau-gosse-dev and I tried windbg, we were able to run !gcroot for a dotnet app, but we were not able to run !gcroot for a NativeAOT binary in Windows, if you can provide instructions that would help us understand how gc works.

**Comment by Beau-Gosse-dev** [comment]
@Maoni0 With a .NET exe running with the CLR, we could load sos (which includes gcroot) in windbg with `.loadby sos coreclr`, but how can we load sos for a native exe?

**Comment by Maoni0** [comment]
that's a good question. @MichalStrehovsky would be the best person to answer that but he's on vacation. @davidwrighton @mangod9 does neither of you happen to know if sos (or some equivalent to look at objects on managed heap) works for a NativeAoT app and if so how to use it? do we have docs for this somewhere?

**Comment by MichalStrehovsky** [comment]
What should work are the ETW traces and PerfView views around those.

But I had trouble getting it to work a couple months ago so it might have regressed again. If it doesn't "just work" with PerfView, it's broken (and we should have a separate issue for it).

As Maoni said I'm on vacation and with limited time right now.

**Comment by mangod9** [comment]
@tommcdon for the sos question above ^^

**Comment by VSadov** [comment]
In terms of GC root reporting NativeAOT is on parity with CoreCLR now. I do not think there is anything actionable on the VM side. 

There were several other concerns raised in the thread, - debuggability and the like. I will let @mangod9  decide if there is a need to keep this open for those.

**Comment by smhmhmd** [comment]
It is up to you if you want to close it, however, there seems to be a difference when compiled as NativeAOT.
I used the sample in the description with a new install of dotnet7 and compiled with or without NativeAOT.
The above code is a slight tweak of https://learn.microsoft.com/en-us/dotnet/api/system.gc.collect?view=netframework-4.8

Without NativeAOT in dotnet-7, almost all of the memory seems to be reclaimed, 83,296 bytes is only 592 bytes away from 82704 bytes.

```
ubuntu@ip-172-31-24-113:~/gc-7.0$ ./bin/Release/net7.0/linux-x64/publish/gc 
Total Memory: 57240
maxGarbage = 3000
The highest generation is 2
Invoke function
Exiting from function
Generation: 1
Total Memory: 82704
Generation: 2
Total Memory: 83296
Generation: 2
Total Memory: 83296
```

With NativeAOT, we start off with 195328 bytes and have only have 99240 bytes at the end, a difference of 96088 bytes

```
ubuntu@ip-172-31-24-113:~/gc-7.0-nativeaot$ ./bin/Release/net7.0/linux-x64/publish/gc 
Total Memory: 56776
maxGarbage = 3000
The highest generation is 2
Invoke function
Exiting from function
Generation: 2
Total Memory: 195328
Generation: 2
Total Memory: 99264
Generation: 2
Total Memory: 99240


```

**Comment by MichalStrehovsky** [comment]
> In terms of GC root reporting NativeAOT is on parity with CoreCLR now. I do not think there is anything actionable on the VM side.
> 
> There were several other concerns raised in the thread, - debuggability and the like. I will let @mangod9 decide if there is a need to keep this open for those.

Let's close. We're bringing up dotnet monitor in .NET 8 for debuggability and as Vlad said, a difference is expected - AOT keeps a lot more stuff on the managed heap that the native runtime would keep in unmanaged memory. It is not a problem.
