### ISSUE TITLE
Mono interpreter: Wrong stack size calculation of basic blocks 

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#68757]
Originally, the issue was reported here: #34196 
where test case: [JIT/Regression/JitBlue/GitHub_23411/GitHub_23411.ilproj](https://github.com/dotnet/runtime/blob/2d4f2d0c8f60d5f49e39f3ddbe1824648ee2b306/src/tests/JIT/Regression/JitBlue/GitHub_23411/GitHub_23411.il) 
fails with `Invalid IL code` error message.

After further investigation - details reported here: https://github.com/dotnet/runtime/issues/34196#issuecomment-1100662244
it has been discovered that the root cause of failures is wrong stack size calculation of basic blocks in unstructured control flows with back edges.

Repro:
```
MONO_ENV_OPTIONS=--interp artifacts/obj/mono/OSX.arm64.Debug/mono/mini/mono-sgen artifacts/tests/coreclr/OSX.arm64.Debug/JIT/Regression/JitBlue/GitHub_23411/GitHub_23411/GitHub_23411.dll
```

Output:
```
GitHub_23411.IsValidName: not enough values (0 < 1) on stack at 012f
* Assertion at /Users/ivan/repos/runtime/src/mono/mono/mini/interp/transform.c:4386, condition `td->sp >= td->stack' not met
```

@BrzVlad

**Comment by SamMonoRT** [comment]
@BrzVlad - don't think this is necessary to fix, please triage

**Comment by ivanpovazan** [comment]
The issue is present in a single unit test which includes unstructured control flows with back edges that is hand written.
An attempt to fix the issue with the interpreter showed that the runtime performance would be affected while we would gain very little value https://github.com/dotnet/runtime/pull/68855
Closing the issue as not planned.
