### ISSUE TITLE
[API Proposal]: Add API to check if process had administrator privileges

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#68770]
### Background and motivation

Some code is meant to be executed as an administrator. This API makes it easy to check if the process is considered to have administrator privileges.

### API Proposal

```csharp
namespace System;

static class Environment
{
    public static bool IsPrivilegedProcess { get; }
}
```

**Comments**

- On Unix, this would check if `geteuid() == 0`. `AdminHelpers` has a `IsProcessElevated` method which may have the appropriate implementation for Windows also. https://github.com/dotnet/runtime/blob/a077f271c3b5a8487f94111dc00a404a01fdc86b/src/libraries/Common/tests/TestUtilities/System/AdminHelpers.cs#L35

- When searching open-source code that implements this for Linux, about half of the cases implement this using `getuid` instead of `geteuid`, so they're likely getting it wrong. Having an API would make it easy to get right.

### API Usage

```csharp
if (Environment.IsPrivilegedProcess)
{
    Console.WriteLine("Trust me, I know what I'm doing.");
}
```

### Alternative Designs

It could be on the Process class, but that class essentially represents an arbitrary process, and we do not plan to implement (nor do we see a need) to gather this info for a different process. Also, we already have `Environment.Is64BitProcess`

We considered various names -- the goal is to have something that doesn't appear to be specific to *nix or specific to Windows (using terms such as root, superuser, administrator, or elevated)

**Comment by tmds** [comment]
cc @eerhardt

**Comment by danmoseley** [comment]
For context, we've pointed folks to [Mono.Posix in the past](https://github.com/dotnet/runtime/issues/25118) but I think we have agreement that (like the API to change Unix file modes) this is fundamental enough it should be in the platform.

**Comment by danmoseley** [comment]
@tmds would "Elevated" mean anything to a non Windows developer? Conversely, would "IsSuperUser" (assuming that's the right term) mean something to a Windows developer?

**Comment by danmoseley** [comment]
One other thought, I believe in Windows at least you can modify the elevation status of a thread (at least downwards). If this API was called on such a thread, we might have to decide whether we return the status of the thread or not. I don't know whether there's an analog on *nix.

**Comment by eerhardt** [comment]
> I don't know whether there's an analog on *nix.

You can call https://www.man7.org/linux/man-pages/man2/seteuid.2.html, but that changes it for the whole process. I've never seen something that changes it for a single thread.

**Comment by tmds** [comment]
> @tmds would "Elevated" mean anything to a non Windows developer? Conversely, would "IsSuperuser" (assuming that's the right term - not "RunningAsRoot" or "RunningAsSuperuser") mean something to a Windows developer?

Root/SuperUser are the appropriate Unix names.

How about: `IsRunningAsAdministrator`?

> You can call https://www.man7.org/linux/man-pages/man2/seteuid.2.html, but that changes it for the whole process. I've never seen something that changes it for a single thread.

Yes, that is what POSIX prescribes.

The Linux kernel actually tracks it per thread. The user-space functions are implemented so the change applies process-wide to match POSIX behavior.

**Comment by danmoseley** [comment]
@GrabYourPitchforks @bartonjs as security people, thoughts about naming here, or other feedback?

Throwing out another suggestion that's maybe more OS generic: `bool HasElevatedPrivileges { get; }` (although 'privileges' are a first class concept in the Windows security model, I think 'elevated privileges' is clearly distinct, and not a term specific to Winodws.

**Comment by bartonjs** [comment]
`IsPrivilegedProcess`, maybe?

[NIST security glossary entry for 'privileged process'](https://csrc.nist.gov/glossary/term/privileged_process): A computer process that is authorized (and, therefore, trusted) to perform security-relevant functions that ordinary processes are not authorized to perform.

So that'd be a process running as

* Windows
  * `NT AUTHORITY\LocalSystem`
  * `BUILTIN\Administrator`
  * Any administrative account in an elevated context. (Or, if UAC is disabled "any administrative account")
* UNIX
  * geteuid() == 0

**Comment by danmoseley** [comment]
`IsPrivilegedProcess` sounds good to me. And being on Environment, not Process also seems right, as there's already Is64BitProcess there, and the Process type mostly is instance except for static methods to get Processes; plus we'd need to implement it for remote processes...

**Comment by danmoseley** [comment]
@tmds as per usual practice I edited the top post with that suggestion. Feel free to edit/suggest others as it's your proposal.

Marking  ready for review.

**Comment by deeprobin** [comment]
I like the proposed API shape.

---

On Windows it is technically not so easy to elevate a process at runtime via UAC (there are some possibilities via undocumented APIs). On Unix you could setuid to 0.

However, you can drop the privileges under Windows. This would be a good addition to this API in my opinion.

See [Advapi32: AdjustTokenPrivileges](https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-adjusttokenprivileges?redirectedfrom=MSDN)
See [Linux privilege dropping](https://stackoverflow.com/a/3357855/7600021)

---

```cs
namespace System;

static class Environment
{
    public static bool IsPrivilegedProcess { get; }

    public static bool DropPrivileges();
    // only supported on unix:
    public static bool RequestPrivileges();
}
```

**Comment by GrabYourPitchforks** [comment]
Agree that "privileged" seems like the right name.

Nit: Windows actually has several definitions of privileged beyond the NIST glossary Jeremy linked to. For example, the DRM processing pipelines in Windows use "privileged" to refer to a process that can access protected media, even though these pipelines aren't running with SYSTEM-equivalent permissions.

But that's splitting hairs and I think we should stick with "privileged" as the friendly name and just doc what it means.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System;

public partial class Environment
{
    public static bool IsPrivilegedProcess { get; }
}
```

**Comment by deeprobin** [comment]
An API implementation always needs test cases.

@tmds 
How do you want to test the behavior here? To test this we need to elevate the Test Runner & then drop privilegies to test the other case.
However, I feel that this testing approach could often lead to errors.

**Comment by eerhardt** [comment]
For Unix, we RemoteExecutor which has a `RunAsSudo` option. That will spawn a new process running as `root`, and inside that process `Environment.IsPrivilegedProcess` should return `true`.

**Comment by danmoseley** [comment]
On Windows, tests should determine whether they are running privileged (I believe they all do in our automated runs); if not, test IsPrivilegedProcess is false, but if yes, test IsPrivilegedProcess is true then spawn a child process that is not privileged (may require a pinvoke) and test IsPrivilegedProcess is false.

For determining whether privileged the test could pretty much copy/paste the implementation of IsPrivilegedProcess. Or, as I have seen done in the past, see whether it can write (and then clean up) a randomly named file in the Windows directory..

**Comment by jeffhandley** [comment]
@danmoseley FYI I'm moving this out to 8.0.0 since we weren't able to drive it to consensus for 7.0.0. I'd like to treat this as a high-value feature for 8.0.0 though.

**Comment by iSazonov** [comment]
Is any stopper to implement this?

---

To reset admin on Windows we can run subprocess with `runas /trustlevel:0x20000`. What could the test subprocess be?

**Comment by deeprobin** [comment]
> Is any stopper to implement this?

As far as I know, there is no stopper.

However, I have already started to implement this for Windows. Of course there are missing things like tests, documentation, ...
If you like you can continue to work on the basis of my branch [`deeprobin:issue-68770`](https://github.com/deeprobin/runtime/tree/issue-68770), because I won't get to it before December.

**Comment by tmds** [comment]
Implemented in https://github.com/dotnet/runtime/pull/77355 by @iSazonov for .NET 8.0.
