### ISSUE TITLE
[API Proposal]: Create an interface for types with not-null returning ToString

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/runtime#68779]
### Background and motivation

`object.ToString` returns `string?`, which introduces a number of extraneous NRT warnings.

### API Proposal

```csharp
namespace System;

public interface IStringFormattable
{
    string ToString();
}
public struct Int32 : ...., IStringFormattable { ... }
// etc. - all the types which are known to return not-null string from ToString
```

### API Usage

```csharp
string Foo<T>(T value) where T : IStringFormattable
{
  return value.ToString(); // no NRT warning
}
```

**Comment by teo-tsirpanis** [comment]
Adding such interface would imply lots of churn in both first and third-party code for seemingly little benefit. How about you use an extension method like the following?

``` csharp
public static class ToStringExtensions
{
    /// <summary>
    /// Calls <see cref="object.ToString"/> on <paramref name="x"/>
    /// and returns an empty string instead of <see langword="null"/>
    /// </summary>
    // It is generic to avoid boxing.
    public static string ToStringOrEmpty<T>(this T x) where T: notnull => x.ToString() ?? "";
}
```

**Comment by TahirAhmadov** [comment]
That could work, yes. However, it's not much different than just appending `!`; calling this method implies I know I expect types such as `int`, which is also true for `!`.
I'm not sure I understand your concern about "code churn"; we wouldn't be re-writing anything; to my knowledge, all these types already define a not-null returning `ToString` method. We're talking about appending that interface implementation reference on these types. It doesn't even have to be an exhaustive list; if we could just start with primitives and other "core" types like `DateTime` and `Guid` etc., it would solve 90% of the problem. This is a low-effort, low-risk change. 
The benefit would be significant. Allowing developers to write code with NRT enabled and without sprinkling `!` in so many places makes the NRT feature more valuable. If developers get into the habit of sprinkling `!` in all these places (or writing extensions which "hide" the NRT warnings), then it negates the whole purpose of NRT. `!` should be an exception, not a rule.

**Comment by stephentoub** [comment]
I do not see us adding such an interface purely for the benefit of changing the nullable status of `ToString()`.  Concrete types can already override `ToString()` and provide a statically-typed non-null return type.  For consumers operating over `object.ToString()`, our experience is documented in https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md#virtualabstract-methods-and-interfaces, detailing why continue to believe the negative impact of `object?` as the return type is minimal.

**Comment by TahirAhmadov** [comment]
@stephentoub  I don't disagree with that analysis. It would be very difficult to mandate that literally all types in all code bases return not-null from `ToString`. That's why the proposed interface would only be "implemented" by a specific set of types; I can think of 20-30 types which fit this criterion. Also, the interface is so simple, and the "implementation" work is literally zero - because these types already define not-null `ToString` - that the cost is minuscule.

**Comment by stephentoub** [comment]
> that the cost is minuscule

It's not.  There's the runtime overhead associated with every additional interface a type implements, and there's the cognitive overhead of someone defining a type needing to think through all the interfaces they should or should not be implementing.

I understand the request.  I do not believe it's something we should be doing.

**Comment by tannergooding** [comment]
Agree with @stephentoub here. This is a not a direction we'd be willing to take the BCL.
