### ISSUE TITLE
[API Proposal]: Improve reflection types - add not-null properties

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/runtime#68789]
### Background and motivation

The `MemberInfo.DeclaringType` property is nullable, most likely because `Type` inherits from `MemberInfo`. This has a very bad effect on `FieldInfo`, etc. - for those, `DeclaringType` is never null.

### API Proposal

```csharp
namespace System.Reflection

public class FieldInfo : MemberInfo, ...
{
  // ...
  public Type DeclaringType => base.DeclaringType!;
}
// ditto for MethodInfo, PropertyInfo, etc.
```

### API Usage

```csharp
string Foo(FieldInfo fieldInfo)
{
  return fieldInfo.DeclaringType.Name; // no NRT warning
}
```

**Comment by stephentoub** [comment]
RuntimeFieldInfo.DeclaringType explicitly returns null if the FieldInfo represents a global field:
https://github.com/dotnet/runtime/blob/8823eefe91f6b774961c32800dea977b687d7328/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeFieldInfo.cs#L43
e.g.
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.module.getfield?view=net-6.0

**Comment by TahirAhmadov** [comment]
I'm extremely confused. So CLR allows fields that are not in a type? How does one create those? What about methods - I just noticed `DefineGlobalMethod` - does that create C-style "functions" outside of any type? How are those different from `DynamicMethod`?

**Comment by jkotas** [comment]
> I'm extremely confused. So CLR allows fields that are not in a type? How does one create those? 

In IL or in managed C++. C# does not create these.

**Comment by TahirAhmadov** [comment]
Does this apply to all members? Are there "global" properties and events, too?

**Comment by MSDN-WhiteKnight** [comment]
> Does this apply to all members? Are there "global" properties and events, too?

No, only fields and methods can be global. ECMA-335 II.17 Defining properties:

>A Property is declared by the using the .property directive.  Properties shall only be declared inside of 
types (i.e., global properties are not supported).

**Comment by TahirAhmadov** [comment]
@jkotas @stephentoub can we re-open this issue and do it for properties and events at least? Also, `ConstructorInfo` must be in a type, right?
Also, can we add a property like `DeclaringTypeRequired` to `MethodInfo` and `FieldInfo`, which returns not-null `Type` and throws if it's null?

**Comment by buyaa-n** [comment]
> can we re-open this issue and do it for properties and events at least?

`DeclaringType` for those looks could be non-nullable, might want to create a new issue for those instead of reopening this

>  Also, ConstructorInfo must be in a type, right?

`ConstructorInfo` also explicitly returns null:
https://github.com/dotnet/runtime/blob/8823eefe91f6b774961c32800dea977b687d7328/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeConstructorInfo.CoreCLR.cs#L180

> Also, can we add a property like DeclaringTypeRequired to MethodInfo and FieldInfo, which returns not-null Type and throws if it's null?

No, that is where the null forgiving operator `!` should be used instead:
```cs
string Foo(FieldInfo fieldInfo)
{
  return fieldInfo.DeclaringType!.Name;
}
```
