### ISSUE TITLE
Add rich type for reading X509 Authority Information Access

### ISSUE THREAD

**Issue by bartonjs** [dotnet/runtime#68792]
One of the standard X.509 extension types defined by RFC 3280 (and successive RFCs) is the "Authority Information Access" extension.  The use case is largely to inform chain building engines where any OCSP endpoints might be, and where one might find a copy of the issuing CA's certificate.

With a lot of handwaving, this extension can be thought of an order series of 3-tuples:

* What kind of purpose is this for? (OCSP endpoint, where to download a CA cert, some future/private purpose)
* What type of data is present? (the most useful type here is URI, other options include an LDAP X.500 identifier, or an email address, or an IP address... most of which don't make sense in context)
* What is the value? (legal encodings are determined by the data type)

For a typical .NET caller, the most important information is the URI-typed values for OCSP or the issuing CA. Rather than muddy the type with all of the complexities of modelling everything, the type is limited mostly to these common cases and anything more complicated can be accomplished with `AsnReader`.

The Enumerate methods all ignore non-conforming data.  A `(OCSP, emailAddress, ...)` value will simply be skipped over.  Exceptions are only thrown when the encoded representation doesn't decode at all.

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public sealed partial class X509AuthorityInformationAccessExtension : X509Extension
    {
        public X509AuthorityInformationAccessExtension() { }
        public X509AuthorityInformationAccessExtension(byte[] rawData, bool critical = false) { }
        public X509AuthorityInformationAccessExtension(ReadOnlySpan<byte> rawData, bool critical = false) { }
        public X509AuthorityInformationAccessExtension(IEnumerable<string> ocspUris, IEnumerable<string> caIssuersUris, bool critical = false) { }
        public override void CopyFrom(AsnEncodedData asnEncodedData) { }
        public IEnumerable<string> EnumerateCAIssuersUris() { throw null; }
        public IEnumerable<string> EnumerateOcspUris() { throw null; }
        public IEnumerable<string> EnumerateUris(string accessMethodOid) { throw null; }
    }
}
```

**Comment by bartonjs** [comment]
My original inclination was to say that this type couldn't be used to craft the extension because of ordering and accessMethod.  But two options present themselves that I'm interested in discussing:

* `.ctor(IEnumerable<string> ocspEndpointUris, IEnumerable<string> caIssuersUris, bool critical=false)`
  * Writes all OCSP endpoints before all CA issuers... because that's the order their OIDs sort
* `.ctor(IEnumerable<(string AccessMethodOid, string UriValue))`
  * Requires a much less pleasant invocation, but lets ordering be explicitly controlled, and supports future/private access methods (but not the other "7" GeneralName data types)

I originally thought the first option was kind of dirty, because it's so "opinionated".  But it's probably the 99.99% use case and the 0.01% can use AsnWriter.

**Comment by vcsjones** [comment]
> that this type couldn't be used to craft the extension because of ordering and accessMethod

I see the utility in such API. There have been some mentions in [previous issues](https://github.com/dotnet/runtime/issues/59191) to the effect of "I am trying to build a CA in .NET". Someone that is trying to build such functionality will eventually want to be able to add these extensions to a `CertificateRequest`.

> But two options present themselves that I'm interested in discussing

"Why not both" is a possibility.

A third possibility is to consider a `X509AuthorityInformationAccessBuilder` such as we have with SANs and now X500DNs. There is an appeal to be to separate the writer and reader concepts, and the builders can be more ergonomic where ordering is explicit (by way of whatever order `AddXYZ` is called).

Alternatively, if `GeneralName` ever does become a rich type, then the extension could probably just gain another constructor to support it.

I don't feel very strongly about a `Builder` for it. It certainly feels a bit niche to me.

> proposal

Should there be:

```csharp
public X509AuthorityInformationAccessExtension(byte[] encoded, bool critical = false)
public X509AuthorityInformationAccessExtension(AsnEncodedData encodedAuthorityInformationAccess, bool critical);
```

The `byte[]` is just a matter of "we tend to offer byte overloads where we have span APIs". The second I don't see a big need for, but, every other `X509Extension` derived type has it, so it's a question that comes from the perspective of consistency.

**Comment by bartonjs** [comment]
> `public X509AuthorityInformationAccessExtension(AsnEncodedData encodedAuthorityInformationAccess, bool critical);`

All the extensions do with the AsnEncodedData is throw if they're null (usually NullReferenceException), and then pass data.RawValue down to the base ctor (ignoring data.Oid).  Basically, I cut out the middleman.

> `public X509AuthorityInformationAccessExtension(byte[] encoded, bool critical = false)`

That's fair.

> A third possibility is to consider a `X509AuthorityInformationAccessBuilder` such as we have with SANs and now X500DNs.

Yeah, that was my starting position.  Then, when explaining in the issue prose why the type couldn't be used to craft the extension (and that the builder would come later) I felt like maybe we could get several 9s of coverage from either of those two options.

> "Why not both" is a possibility.

If we think that `.ctor(IEnumerable<string> ocspEndpointUris, IEnumerable<string> caIssuersUris, bool critical=false)` will cover enough use cases then I'd rather leave out the value-tuple-accepting version.

The builder might allow for some complicated expression of interleaving, other GeneralName value kinds, and future access method items... but using AsnWriter directly for it isn't really all that hard: https://github.com/bartonjs/runtime/commit/ef1e54866e56737d7ec4e60c76e2f0c89ecf9d66#diff-18b898e9da53598005170588ef8a5297095a5f10f14f66367006c1ad7f464f4aR504-R533

I think I'm growing in confidence that `.ctor(IEnumerable<string> ocspEndpointUris, IEnumerable<string> caIssuersUris, bool critical=false)` is a good starting point, and then we can let feedback guide us to something more complicated... if it's ever warranted.

**Comment by vcsjones** [comment]
>  but using AsnWriter directly for it isn't really all that hard

I don't... exactly... share that same opinion, but I understand it. Perhaps this is a case of [average familiarity](https://xkcd.com/2501/). Though I would agree that the constructor that handles OCSP and CA Issuers is probably 99% of the use case. I just don't want "Use `AsnWriter`" to be a fallback that gets too comfortable.

Okay, but I'll agree that a builder is probably overkill at this point.

> Requires a much less pleasant invocation

I don't think it's particularly gross?

```csharp
new X509AuthorityInformationAccessExtension(new[] {
    ("1.2.3.4", "http://example.com"),
    ("1.2.9.0", "http://example.org"),
});
```

The invocation looks simple enough, assuming the constructor looked something like this:

```csharp
public X509AuthorityInformationAccessExtension(IEnumerable<(string AccessMethodOid, string UriValue)> accessMethods, bool critical=false)
{
}
```

I'm not arguing strongly for it, but when I look at it, it doesn't look that bad.

**Comment by bartonjs** [comment]
Renamed the `encoded` ctor parameters to `rawData` to match the name on X509Extension, and added the (IEnumerable,IEnumerable,bool) ctor for building the extensions.

**Comment by bartonjs** [comment]
>  I just don't want "Use AsnWriter" to be a fallback that gets too comfortable.

I generally agree.  But I'm OK with "Use AsnWriter" to be "you're doing something rare/weird"; and as we learn something is less rare/weird we can add easier-to-use public API.

**Comment by vcsjones** [comment]
I would have one tiny suggestion or question:

```csharp
public X509AuthorityInformationAccessExtension(IEnumerable<string> ocspEndpoints, IEnumerable<string> caIssuersUris, bool critical = false) { }
// snip
public IEnumerable<string> EnumerateCAIssuersUris() { throw null; }
public IEnumerable<string> EnumerateOcspUris() { throw null; }
```

For CA Issuer URIs, both the constructor argument and method are "CAIssuersUris". However for OCSP, the constructor argument is "OcspEndpoints" and the enumerator is "OcspUris".

Is there a reason the constructor argument is "endpoints" OCSP when "Uri" is used for the others?

**Comment by bartonjs** [comment]
Generally looks good as proposed, except we added an overload of EnumerateUris that takes a System.Security.Cryptography.Oid

```C#
namespace System.Security.Cryptography.X509Certificates
{
    public sealed partial class X509AuthorityInformationAccessExtension : X509Extension
    {
        public X509AuthorityInformationAccessExtension() { }
        public X509AuthorityInformationAccessExtension(byte[] rawData, bool critical = false) { }
        public X509AuthorityInformationAccessExtension(ReadOnlySpan<byte> rawData, bool critical = false) { }
        public X509AuthorityInformationAccessExtension(IEnumerable<string> ocspUris, IEnumerable<string> caIssuersUris, bool critical = false) { }
        public override void CopyFrom(AsnEncodedData asnEncodedData) { }
        public IEnumerable<string> EnumerateCAIssuersUris() { throw null; }
        public IEnumerable<string> EnumerateOcspUris() { throw null; }
        public IEnumerable<string> EnumerateUris(string accessMethodOid) { throw null; }
        public IEnumerable<string> EnumerateUris(Oid accessMethodOid) { throw null; }
    }
}
```
