### ISSUE TITLE
.NET dependencies?

### ISSUE THREAD

**Issue by Limeay** [dotnet/runtime#68794]
Hi, i'd like to ask what versions actually need older installs of .NET?

Can you look this through?

Do i need to install 5.0.1.6 if i have 6.0.4 already?
>.NET Desktop Runtime 6.0.4
>.NET Desktop Runtime 5.0.1.6

Just including this for context
Included with Win10/11
>.NET 4.8
>.NET 3.5

**Comment by huoyaoyuan** [comment]
Each version of .NET Core (and .NET 5+) are independent. There can be softwares requiring 5.0 instead of 6.0.

Unless a software, project you are debugging, or some `dotnet tool` complaining about can't find 5.0, you don't need a system-wide installation of 5.0.

**Comment by Limeay** [comment]
Thank you
