### ISSUE TITLE
Make DynamicMethod invokable "directly"

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#68791]
### Discussed in https://github.com/dotnet/runtime/discussions/68135

<div type='discussions-op-text'>

<sup>Originally posted by @TahirAhmadov April 17, 2022</sup>
Hi all, code like the below currently fails:
```cs
var dm = new DynamicMethod(...); // emit some IL
var type = module.DefineType(...);
var mb = type.DefineMethod(...);
mb.GetILGenerator().Emit(OpCodes.Call, dm);

type.CreateType().GetMethod(...).Invoke(...); // exception: Unable to import a global method or field from a different module
```
Looking at the code, there is [GetMethodTokenNoLock](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/src/System/Reflection/Emit/ModuleBuilder.cs) method and it doesn't support `DynamicMethod` at all. Is there some underlying limitation which prevents this from being a viable scenario? If not, can it be fixed, please? :)

Currently I end up having to create a delegate, store it in a static field somewhere, and then call the delegates `Invoke` method - which basically calls the `DynamicMethod` indirectly. Not only it's make work, but it's also a delegate invocation which is probably slightly slower than a direct call the `DynamicMethod`.</div>

**Comment by jkotas** [comment]
> Is there some underlying limitation which prevents this from being a viable scenario? 

Yes.

Assemblies produced by Reflection.Emit are very much like regular assemblies on disk. Reflection.Emit produces the assembly in memory and the assembly then gets loaded using mechanism that is very similar to how assemblies are loaded from disk.

Regular assemblies on disk cannot reference dynamic methods. There is no way to reference dynamic methods in regular assemblies. Reflection.Emit produced assemblies have the same limitation by virtue of using the same encodings and loader as regular assemblies.

**Comment by stephentoub** [comment]
>> Is there some underlying limitation which prevents this from being a viable scenario?

> Yes.

Closing.
