### ISSUE TITLE
macOS build fails on NativeRuntimeEventSource.cs with old python version

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#688]
*Initial cost estimate*: 2 days
*Initial contacts*: @trylek, @ViktorHofer 

macOS build fails when old python is used without an easy way to see that. I have the default python installed by macOS (2.7) but that's not enough to build runtime master version. The build fails with following

```
CSC : error CS2001: Source file '/<path>/runtime/src/coreclr/../../artifacts/obj/coreclr/System.Private.CoreLib/x64/Debug/../../../Eventing/x64/Debug/NativeRuntimeEventSource.cs' could not be found. 
```

The error is gone after installing python3.

**Comment by hoyosjs** [comment]
@sywhang just fyi

**Comment by jashook** [comment]
Python3 is a requirement, if we do not have an error message this issue should track adding one.

**Comment by ViktorHofer** [comment]
@jkotas do you think it would make sense to convert the https://github.com/dotnet/runtime/blob/15460311833f161bbe90b61ef94a8f339178840b/src/coreclr/src/scripts/genRuntimeEventSources.py script which runs during the CoreLib build to msbuild (probably via a C# msbuild task)?

**Comment by jkotas** [comment]
Yes!! 

I think we should be eliminating our dependencies on python, first in build, and eventually in tests too.

**Comment by trylek** [comment]
@ViktorHofer - in light of JanK's response please file a follow-up CoreCLR infra item to remove the Python script by rewriting it probably to C# per your suggestion. I guess that in such case it doesn't make too much sense to continue pursuing this work item. We'll need to update the CoreCLR infra backlog local dev innerloop epic to reflect the follow-up item, sadly this is still very much manual.

**Comment by ViktorHofer** [comment]
Filed https://github.com/dotnet/runtime/issues/45733. Let's close this one then.

**Comment by trylek** [comment]
Thanks Viktor, I have updated the backlog as appropriate. Feel free to adjust the initial cost estimate, just please let me know or update the dev innerloop epic in the infra backlog to reflect the change.

**Comment by ViktorHofer** [comment]
I don't think this should take longer than a week max to be honest. I wonder if @hoyosjs or @jkoritzinsky might be interested in this task.

**Comment by hoyosjs** [comment]
There's three scripts, it needs to be validated for ETW, LTTNG, and EventPipe. There's different behavior for each and different codegen for each. A week isn't realistic. I really don't know how much value there's to this right now. Diagnostics is pretty swamped on work and issues at the moment. We had considered this at some point, but just didn't see enough value on the time investment.

cc: @dotnet/dotnet-diag

**Comment by ViktorHofer** [comment]
> There's three scripts, it needs to be validated for ETW, LTTNG, and EventPipe. There's different behavior for each and different codegen for each. A week isn't realistic.

Got it. Reminds me that I shouldn't estimate work in an area I'm not familiar with 🗡️

**Comment by ViktorHofer** [comment]
Regarding impact, besides the overall goodness of one less build dependency, this lowers the first time contributor bar noticeably. Based on issues we've seen in the past, python is one of the tools that isn't installed on every dev's machine.
