### ISSUE TITLE
ucol_safeClone deprecated in ICU 71.1

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#68814]
https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html#a917cd8e16df3b35bbe97dd96d881f227

After recent update I'm no longer able to build System.Globalization.Native due to `ucol_safeClone` becoming deprecated.

**Comment by tarekgh** [comment]
> After recent update

Could you please talk more about the update you are referring to here? I know ICU 71 is out, but I am wondering which environment you are using which is getting ICU 71?

**Comment by ManickaP** [comment]
I'm on Arch, so I usually get updates ahead of other distros.
