### ISSUE TITLE
Assertion failed 'vecCns.i32[argIdx] == 0' in 'System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests:Vector128SingleShuffleOneInputTest():this' during 'Lowering nodeinfo'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#68815]
Failed in rolling build: https://dev.azure.com/dnceng/public/_build/results?buildId=1749196&view=results
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-e3fb9971fe22464890/System.Runtime.Intrinsics.Tests/1/console.899d395c.log?helixlogtype=result

cc @tannergooding, related to #68559?

**Comment by tannergooding** [comment]
Yes, likely. It's not used anywhere yet so its a bit surprising it failed in a rolling build. Taking a look
