### ISSUE TITLE
Task.Delay actual accepted delay is twice the documented value

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#68818]
Hi! The documentation of the [`Task.Delay`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.delay?view=net-6.0#system-threading-tasks-task-delay(system-timespan)) method (.NET 6) says that the maximum delay is `Int32.MaxValue` milliseconds:

> **Exceptions**
> `ArgumentOutOfRangeException`
> `delay` represents a negative time interval other than `TimeSpan.FromMilliseconds(-1)`.
> 
> -or-
> 
> The `delay` argument's `TotalMilliseconds` property is greater than [`MaxValue`](https://docs.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-6.0).

It seems though that the actual maximum value accepted is `UInt32.MaxValue - 1`, which is twice as large, as demonstrated by this example:

```C#
using System;
using System.Threading.Tasks;

public static class Program
{
    public static void Main()
    {
        var task = Task.Delay(TimeSpan.FromMilliseconds(UInt32.MaxValue - 1));
        Console.WriteLine("OK");
    }
}
```

No exception is thrown when the above code runs on .NET 6 ([live demo](https://dotnetfiddle.net/z0zluo)).

On the contrary an `ArgumentOutOfRangeException` is thrown when the code runs on .NET Framework ([live demo](https://dotnetfiddle.net/h0TEpD)).

I would like to ask if the documentation is outdated and should be updated, or the `Int32.MaxValue` is the actual limit, and a `Task.Delay` configured with `UInt32.MaxValue - 1` will complete after ~25 days instead of ~50 days.

Thanks!

**Comment by stephentoub** [comment]
This was extended in .NET 6:
https://github.com/dotnet/runtime/pull/43708

Submitting a PR to update the docs in https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Threading.Tasks/Task.xml would be fine.
