### ISSUE TITLE
Revisit code that updates loops before block removal

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#68844]
While working on https://github.com/dotnet/runtime/pull/68803 to fix https://github.com/dotnet/runtime/issues/68756, we encountered several issues about how we track and update loop tables around block that we will remove. We should revisit the logic in `optUpdateLoopsBeforeRemoveBlock()`.
1. After we renumber blocks, we add new blocks on the way (specifically during loop hoisting, we add preheaders). The `lpContains()` method relies on `bbNum` to determine if something is present in loop or not. Below is the code that is used to determine if a block is present in loop or not, but newer added blocks might have higher `bbNum` and can falsely claim that the block is not in the loop.
https://github.com/dotnet/runtime/blob/4cd4cff89cce3d48b70fdb3bfd604d3982d5e808/src/coreclr/jit/optimizer.cpp#L515-L518
2. If there was a preheader which had invariants hoisted, but later those invariants were eliminated by assertion prop or some other optimization, we would be left with empty preheader which want to eliminate. We invoke `optUpdateLoopsBeforeRemoveBlock()` and decide if the loop should also be removed or not.
https://github.com/dotnet/runtime/blob/4cd4cff89cce3d48b70fdb3bfd604d3982d5e808/src/coreclr/jit/optimizer.cpp#L466-L467

Later, we also iterate through all the blocks, one of them being the preheader that we want to eliminate. We think that it is not part of a loop (because of reason mentioned above) but then see that `auxBlock->bbJumpDest == loop.lpEntry` and reset the flag saying we do not have to remove the loop. Here, we assume that there was a predecessor outside the loop, but never verify if `auxBlock == block`.
https://github.com/dotnet/runtime/blob/4cd4cff89cce3d48b70fdb3bfd604d3982d5e808/src/coreclr/jit/optimizer.cpp#L509-L512

3. If we decide to remove the loop or not, we fail to check for certain scenarios if `loop.lpHead == block` and if yes, we should update the `loop.lpHead` to point to the predecessor of `block` we are trying to remove.
4. Today, we do update `loopHead` in certain cases, but `bbPrev` might not be the right block we should set, but should be a predecesssor if possible. If we just add `assert(block->bbPrev->KindIs(BBJ_NONE, BBJ_ALWAYS))`, we would see that `BBJ_THROW` or `BBJ_RETURN` blocks are getting set as `lpHead` of a loop. This portion needs to be revisited as well.
https://github.com/dotnet/runtime/blob/4cd4cff89cce3d48b70fdb3bfd604d3982d5e808/src/coreclr/jit/optimizer.cpp#L565-L570

category:implementation
theme:loop-opt
skill-level:expert
cost:medium
impact:medium

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib , @BruceForstall

**Comment by BruceForstall** [comment]
I think we should enable the code that always creates loop pre-headers when doing loop recognition (you could consider it part of loop canonicalization), and prevents removing empty pre-headers through optimization, finally letting them be removed late in compilation if they are empty. This would mean there's no need to on-demand create them, which invalidates bbNum sequential ordering and thus dominators.

**Comment by kunalspathak** [comment]
Thanks @BruceForstall. Whenever you get a chance, can you publish a draft PR of whatever changes you have so far for "always create loop pre-headers"? I can iterate on top of it to solve this problem.

**Comment by jakobbotsch** [comment]
This code no longer exists
