### ISSUE TITLE
Under what conditions can `TypeBuilder.CreateType()` return null

### ISSUE THREAD

**Issue by lonix1** [dotnet/runtime#68840]
**Issue description**
Under what conditions can `TypeBuilder.CreateType()` return null?

**Target framework**
- [x] .NET Core 5, 6
- [ ] .NET Framework
- [ ] .NET Standard

**Details**
The `TypeBuilder.CreateType()` method is defined [as nullable](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder.createtype#system-reflection-emit-typebuilder-createtype):
````cs
public Type? CreateType();
````

Under what conditions can it return null? The docs do not say.

Please document this method signature.

**Comment by JosieBigler** [comment]
I'd be interested in making the above changes @Jehoel outlined. In terms of testing, would that be a new `Assertion` in the current `Theory` or a new `Theory`?

**Comment by buyaa-n** [comment]
Thanks @JosieBigler, assigning to you. If it is covered well with current tests then no need to add new tests, just need to fix the current test behavior, could not say for sure as I did not check the existing tests. you would see test  coverage after fixing the issue and running the tests
