### ISSUE TITLE
[API Proposal]: char helpers for common ASCII categories

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#68868]
### Background and motivation

We have a bunch of IsHex/IsHexChar/IsHexDigit helpers all around our libraries, as well as IsAsciiLetter/IsAsciiLetterOrDigit and such variants.  We should expose these simple helpers implemented efficiently in a place all code can use rather than duplicating them into a bunch of libraries.  We already have many `Is*` methods on char, like `IsAscii`, `IsLetter`, `IsDigit`, and so on; we can augment those with the additional methods.

### API Proposal

```diff
public struct Char
{
+    public static bool IsAsciiDigit(char c); // true iff the char is 0-9
+    public static bool IsAsciiLetter(char c); // true iff the char is A-Z, a-z
+    public static bool IsAsciiLetterLower(char c); // true iff the char is a-z
+    public static bool IsAsciiLetterUpper(char c); // true iff the char is A-Z
+    public static bool IsAsciiLetterOrDigit(char c); // true iff the char is A-Z, a-z, 0-9

+    public static bool IsHexDigit(char c); // true iff the char is 0-9, A-F, a-f
+    public static bool IsHexDigitUpper(char c); // true iff the char is 0-9, A-F
+    public static bool IsHexDigitLower(char c); // true iff the char is 0-9, a-f

+    public static bool IsInRange(char c, char minInclusive, char maxInclusive); // true iff the char is >= minInclusive && <= maxInclusive
}
```

### API Usage

```C#
if (char.IsAsciiLetterOrDigit(c))
{
    writer.Write(c);
}
else
{
    writer.Write($@"\u{(int)c:X4}");
}
```

### Alternative Designs

We might also want to expose a helper for getting the value of a hex digit, e.g.
```C#
public static int GetHexDigitValue(char c); // return 0-15 for 0-9/A-F, and some sentinel otherwise (e.g. -1)
```

**Comment by vcsjones** [comment]
> public static bool IsHexDigit(char c, out )

This seems like it has an extra `out`. Should that just be `IsHexDigit(char c)`?

**Comment by stephentoub** [comment]
> This seems like it has an extra out. Should that just be IsHexDigit(char c)?

Yes, that was a copy/paste/delete error.

**Comment by MihaZupan** [comment]
Thoughts on including this one in the list?
```c#
public static bool IsAsciiDigit(char c); // true iff the char is 0-9
```

**Comment by danmoseley** [comment]
Are non ASCII digits ever used in Hex representations?

**Comment by stephentoub** [comment]
> Are non ASCII digits ever used in Hex representations?

Not to my knowledge.

> public static bool IsAsciiDigit(char c); // true iff the char is 0-9

Added

**Comment by grbell-ms** [comment]
Would it make sense to add these methods to other types? There are some existing `Is*` methods for `byte` and `int` in the framework and adding them to `Rune` is good for symmetry's sake.

**Comment by stephentoub** [comment]
> Would it make sense to add these methods to other types? There are some existing Is* methods for byte and int in the framework and adding them to Rune is good for symmetry's sake.

Adding to Rune as well seems reasonable.  We shouldn't add these to Byte or Int32.

**Comment by stephentoub** [comment]
This is appx what this would look like in dotnet/runtime:
https://github.com/stephentoub/runtime/commit/0146ecf5a5b3573e77a68bb7da496047acdd3f28

**Comment by GSPP** [comment]
Getting rid of all this redundancy is awesome. @stephentoub according to your commit, these patterns show up everywhere. 👍

**Comment by stephentoub** [comment]
If you see more that can be changed, please let me know. The ones I'm aware of and didn't change are in projects that have at least one target below .NET 7.

**Comment by bartonjs** [comment]
* We inserted "Ascii" in the Is*Hex methods
* We renamed IsInRange to IsBetween
* Otherwise looks good

```C#
namespace System
{
    public partial struct Char
    {
        public static bool IsAsciiDigit(char c); // true iff the char is 0-9
        public static bool IsAsciiLetter(char c); // true iff the char is A-Z, a-z
        public static bool IsAsciiLetterLower(char c); // true iff the char is a-z
        public static bool IsAsciiLetterUpper(char c); // true iff the char is A-Z
        public static bool IsAsciiLetterOrDigit(char c); // true iff the char is A-Z, a-z, 0-9

        public static bool IsAsciiHexDigit(char c); // true iff the char is 0-9, A-F, a-f
        public static bool IsAsciiHexDigitUpper(char c); // true iff the char is 0-9, A-F
        public static bool IsAsciiHexDigitLower(char c); // true iff the char is 0-9, a-f

        public static bool IsBetween(char c, char minInclusive, char maxInclusive); // true iff the char is >= minInclusive && <= maxInclusive
    }
}
```

**Comment by dakersnar** [comment]
What's the state of the implementation for this? If it hasn't been tackled yet I could probably take a look at it.

**Comment by stephentoub** [comment]
Thanks, @dakersnar. It's basically done (commit mentioned a few comments back), I just need to polish it / adapt to the decisions in the meeting. I typically implement or at least protoptype proposals I make to fully flesh them out prior to spending time reviewing something, to help make sure we're reviewing the right thing :-)

**Comment by TonyValenti** [comment]
@stephentoub you might also consider adding IsBase64 methods as well.
