### ISSUE TITLE
[Android][iOS] Enable HttpClientHandler.DangerousAcceptAnyServerCertificateValidator when using native handlers

### ISSUE THREAD

**Issue by simonrozsival** [dotnet/runtime#68898]
At the moment the [`HttpClientHandler.DangerousAcceptAnyServerCertificateValidator` property](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs#L735) throws `PlatformNotSupportedException` when using native handlers. Since the native handlers will use the `ServerCertificateCustomValidationCallback` property in .NET 7 (see https://github.com/xamarin/xamarin-android/pull/6665, mac/iOS is implementation is currently in progress) there won't be a reason to throw the exception anymore.

/cc @akoeplinger

**Comment by karelz** [comment]
@simonrozsival can you please triage the issue?
