### ISSUE TITLE
Update `INS_serialize` perfscore with accurate numbers.

### ISSUE THREAD

**Issue by anthonycanino** [dotnet/runtime#68917]
PR https://github.com/dotnet/runtime/pull/68677 implements the `X86Serialize` API/intrinsic and introduces the `serialize` instruction into the x86 emitter. The current perfscores for `INS_serialize` are estimated placeholder values. Creating this issue to track a work item to revisit once we have more accurate numbers and update accordingly. 

category:implementation
theme:debug-dumps
skill-level:beginner
cost:small
impact:small

**Comment by anthonycanino** [comment]
Someone may assign this to me.

**Comment by JulieLeeMSFT** [comment]
@anthonycanino our code complete for .NET 7 is July 11th. Are you planning to work on it? Otherwise, I will move this to .NET 8.

**Comment by tannergooding** [comment]
Just noting this isn't critical for .NET 7 by any means.

The `perf_score` is a `debug`/`checked` build only metric and we aren't personally using this anywhere in the runtime at the moment.

**Comment by anthonycanino** [comment]
@JulieLeeMSFT , I am looking into this and will give an update.

**Comment by JulieLeeMSFT** [comment]
@anthonycanino, a kindly reminder if you are going to look into this.

**Comment by anthonycanino** [comment]
@JulieLeeMSFT let me check again and will get back to you shortly. Thanks for the reminder.

**Comment by AndyAyersMS** [comment]
Seems like this can wait for 8.0. Perf score is an internal metric and does not affect jit behavior.

**Comment by anthonycanino** [comment]
FYI, I am still working on this. Hope to give an update soon.

**Comment by anthonycanino** [comment]
I was able to get some more information --- we can use 105 cycles (versus 40 as is currently in the code) as an accurate estimate based on what our team has observed.

Shall we make the change for 8.0?

**Comment by AndyAyersMS** [comment]
Feel free to put up a PR now, we just won't merge it right away.

**Comment by BruceForstall** [comment]
`main` is .NET 8, so this fix can be PR'ed and merged now.
