### ISSUE TITLE
Tiered Compilation turns a static readonly value into a constant, ignoring changes made to the value via generated IL

### ISSUE THREAD

**Issue by EricScottSalem** [dotnet/runtime#68912]
### Description

Tiered Compilation will replace a static readonly variable with a constant, but this causes erroneous behavior as there are various ways to update a readonly variable, such as via IL Generation or unsafe code.

In the attached program, MyClass.Func(int) "Tier0" compiles to:

```
00007FFC960995F0  push        rbp  
00007FFC960995F1  sub         rsp,20h  
00007FFC960995F5  lea         rbp,[rsp+20h]  
00007FFC960995FA  mov         qword ptr [rbp+10h],rcx  
00007FFC960995FE  mov         dword ptr [rbp+18h],edx  
00007FFC96099601  mov         rcx,7FFC96146D00h  
00007FFC9609960B  mov         edx,2  
00007FFC96099610  call        CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE (07FFCF5C0B1B0h)  
00007FFC96099615  mov         eax,dword ptr [7FFC96146D34h]  
00007FFC9609961B  mov         rdx,qword ptr [rbp+10h]  
00007FFC9609961F  add         eax,dword ptr [rdx+8]  
00007FFC96099622  add         eax,dword ptr [rbp+18h]  
00007FFC96099625  add         rsp,20h  
00007FFC96099629  pop         rbp  
00007FFC9609962A  ret 
```

Where line 00007FFC96099615  is reading the static variable from memory.

Tier1 compiles to:
```
00007FFC9607CC70  mov         eax,dword ptr [rcx+8]  
00007FFC9607CC73  lea         eax,[rax+rdx+3Ch]  
00007FFC9607CC77  ret  
```

The static variable is complied to the constant 3Ch, thus the code doesnt respect the ILGenerated update.

### Reproduction Steps

```
internal class MyClass
{
    private static readonly int I = Init();
    private readonly int _i;

    public MyClass(int i)
    {
        _i = i;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public int Func(int i)
    {
        return I + _i + i;
    }

    private static int Init()
    {
        Thread.Sleep(500); //not clear why this is necessary, but it is.
        return 60;
    }
}

class Program
{
    static void Foo()
    {
//Generate IL to set MyClass.I = 7
        DynamicMethod dynamicMethod = new DynamicMethod("MyDynamicMethod", typeof(void), Type.EmptyTypes,
            typeof(MyClass).Module, true);
        ILGenerator il = dynamicMethod.GetILGenerator(2048);
        il.Emit(OpCodes.Nop);
        il.Emit(OpCodes.Ldc_I4_7);
        var field = typeof(MyClass).GetField("I", BindingFlags.NonPublic | BindingFlags.Static);
        il.Emit(OpCodes.Stsfld, field);
        il.Emit(OpCodes.Ret);
        var action = (Action)dynamicMethod.CreateDelegate(typeof(Action));
        action();
    }

    static void Main()
    {
        MyClass myClass = new MyClass(0);
        int result = 0;
        for (int i = 0; i < 31; i++)
        {
            result += myClass.Func(i);
        }

        Console.WriteLine(result);
        Thread.Sleep(1_000); //give time for TC to complete
        Foo();
        Console.WriteLine("Should be 7 + 0 + 2 = 9: {0}", myClass.Func(2));
    }
}
```

### Expected behavior

The code snippet should print 9 as MyClass.I has been set to 7.

### Actual behavior

The code snippet prints 62 as the hard coded MyClass.I remains 60.

### Regression?

This works in .net framework 4.8.  
It also works with TC turned off.

### Known Workarounds

Turn off TC.

### Configuration

I have tried this on .NET 5 and .NET 6 on x64 in Windows 10.

### Other information

Stephen Taub actually mentions this feature in his [blog](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/)

**Comment by EricScottSalem** [comment]
Hello, Mr. Toub.  Thank you for the quick response.  Apologies for misspelling your name up there.
I understand your point.  I am wondering if this philosophy extends to non-statics as well?  I ask because it is a fairly popular methodology to use IL Generated code to deserialize objects which contain readonly fields.  For example, in the popular protobuf.net. 
Although I think it is difficult to optimize like this for instance variables, the possibility of all that code being broken frightens me.
Thoughts?
Thanks again,
Eric

**Comment by jkotas** [comment]
It is not really viable for the runtime to assumes that an instance readonly field can only be assigned in constructor. 

As you have said, it is very common for serializers to set the instance fields and all these serializers would be broken.

Also, the new init-only fields C# language feature assigns readonly fields after the instance constructor have run. For example: https://sharplab.io/#v2:EYLgtghglgdgNAFxFANgHxgUwO4AIAKmATgM4D2MAFAJS4DeuAchGJrgLy4BEAQqil1wBfANwBYAFCSAAgCYCxcjEl1JudbmkBmTQEYADExZsGAc0wIRuWFEvDJQyWo1OJQA . Notice that `k__BackingField` is marked readonly in IL and that it is assigned after the instance constructor have run.

We do not plan to introduce JIT optimizations that make assumptions about instance readonly fields being readonly.
