### ISSUE TITLE
[debugger] CORDBG_E_MISSING_METADATA error when inspecting EF Core classes in .Net 6

### ISSUE THREAD

**Issue by jamesonweber** [dotnet/runtime#68929]
Good afternoon dotnet runtime team!

#### Description 
I am currently looking into a debugger error in our application when trying to inspect EF Core entities in Visual Studio and Rider. I was able to find the error code [CORDBG_E_MISSING_METADATA ](https://github.com/dotnet/runtime/blob/main/src/coreclr/inc/corerror.xml#L1916-L1918) in this repository, as well as [this comment ](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/inc/dacdbiinterface.h#L526-L535) which seems to indicate something has gone wrong when fetching the metadata when debugging the EF class. I suspect it is a configuration issue with our project as when creating a new .Net 6 solution the issue does not happen, but I am not sure where to look for fixing it. This has only become an issue after updating our project from .Net 5 to .Net 6. 

Please let me know if you have any insights into this error code and if there is any configuration I should validate is correct.

Here are some screen shots of the debugging window within Rider 

![image](https://user-images.githubusercontent.com/9398767/166838152-d829c3ba-3dc7-459b-ab4c-a0b46f8db785.png)

![image](https://user-images.githubusercontent.com/9398767/166838137-055c16ed-cf13-4b2e-92e9-0330d04fa629.png)

#### Reproduction:
- Run the project using `dotnet run`
- In Rider or Visual Studio, `Attach Debugger to Process`
- Select the currently running .Net 6 process
- Inspect an EF Class variable with the debugger
- Receive the error `Failed to get base type: The operation failed because the debugger could not get the metadata.`

#### Environment details:
- Rider 2022.1.1, Visual Studio 2022 (Version 17.1.5)
- dotnet --version: 6.0.202
  - Note: this is the only version of dotnet installed on the machine
- Windows 10
- Intel 64 bit CPU

#### Project details I think might be relevant from the `csproj` file:
- Asp.Net Core application (`<Project Sdk="Microsoft.NET.Sdk.Web">`)
- `<TargetFramework>net6.0</TargetFramework>`
- `<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.4">`

Thank you in advance if any help / advice on the above error code!

**Comment by tommcdon** [comment]
Hello @jamesonweber!  The CORDBG_E_MISSING_METADATA error can occur if we fail to extract the metadata for the module loaded into the debugger.  

> This has only become an issue after updating our project from .Net 5 to .Net 6...  I suspect it is a configuration issue with our project as when creating a new .Net 6 solution the issue does not happen...

Would it be possible to reduce the repro down to a small test case that can shared a ZIP file?  Also it might be useful to share a dump of the target process at the point of failure.  I believe either a [dump collected with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2022#BKMK_Create_a_dump_file) or with [task manager](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/finding-the-process-id#task-manager) should be able to work in that scenario. 
 Feel free to open a Visual Studio feedback item and paste a link to it in this GH issue and share the dump.  This should be possible to make the attachment non-public.

**Comment by jamesonweber** [comment]
@tommcdon thank you for the very quick response! I have opened a new issue with the dump file here: https://developercommunity.visualstudio.com/t/debugger-CORDBG_E_MISSING_METADATA-err/10035184?space=61&entry=problem

In it I noted that reducing our solution to a slimmed down version will require quite a bit of effort. Please let me know if it is needed with the dump file. If it is, I can discuss doing that with our team further, but we are hoping the dump file will be sufficient.

I would like to add that it looks like the debugger in visual studio is producing a different exception than rider that was not noticed in the original investigation (we just noticed the exception originally and not the type, sorry about that!). This is the stack trace when inspecting a variable from the debugger in visual studio:

```
myEfClassVariable
'myEfClassVariable' threw an exception of type 'System.IO.FileNotFoundException'
    Data: {System.Collections.ListDictionaryInternal}
    FileName: null
    FusionLog: null
    HResult: -2147024894
    HelpLink: null
    InnerException: null
    Message: "Cannot load assembly 'DynamicProxyGenAssembly2'."
    Source: "15f16a13bcf944549b51f22600b63f1b"
```

**Comment by davmason** [comment]
@jamesonweber based on your description, I strongly believe that the PR I just opened (#72315) will fix your issue. Would you be able to try your repro with a private runtime to confirm? I can give you instructions on how.

**Comment by jamesonweber** [comment]
@davmason That is great news! Sorry for the late reply, it's been a busy week. 

Yup, I can try our project with the private runtime, but some instructions for how would be greatly appreciated.

**Comment by jamesonweber** [comment]
@davmason I was able to sneak some testing time in today, and the results are that the patch appears to resolved the issue! 🎉 

Before applying the patch:
![image](https://user-images.githubusercontent.com/9398767/186029391-0d8baecf-cf57-420f-aeb3-16adb6d23624.png)

After applying the patch: 
![image](https://user-images.githubusercontent.com/9398767/186030988-5403ea03-0e4d-4cb2-814e-a29e691387a8.png)

Everything is evaluating as expected in the debugger now.

Thank you so much @davmason and @tommcdon for all the help on this, we really appreciate it. We can close this issue now from our perspective. I'll let you do that in case there are any loose ends you need to tie up.

**Comment by davmason** [comment]
Thanks for verifying, closing this issue

**Comment by slovely** [comment]
As this appears to be fairly straightforward change, is there any chance of getting this into a future .NET6 release, given that is the LTS version?

**Comment by tommcdon** [comment]
> As this appears to be fairly straightforward change, is there any chance of getting this into a future .NET6 release, given that is the LTS version?

I will create a PR and send it for .NET 6 consideration
