### ISSUE TITLE
[API Proposal]: Remove setter of Capacity Property in the BoundedChannelOptions class

### ISSUE THREAD

**Issue by ArminShoeibi** [dotnet/runtime#68936]
### Background and motivation

Hi there folks.
We have repeated one condition 2 times, first in the constructor then in the body of set accessor.

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelOptions.cs#L54

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelOptions.cs#L68

the constructor wants a value for capacity , and then we can override that in the object initialization.
![image](https://user-images.githubusercontent.com/68565441/167029559-38973db4-d137-4b37-a770-dd3e859ac4c6.png)

### API Proposal

```csharp
public sealed class BoundedChannelOptions : ChannelOptions
{
    /// <summary>The behavior incurred by write operations when the channel is full.</summary>
    private BoundedChannelFullMode _mode = BoundedChannelFullMode.Wait;

    /// <summary>Initializes the options.</summary>
    /// <param name="capacity">The maximum number of items the bounded channel may store.</param>
    public BoundedChannelOptions(int capacity)
    {
        if (capacity < 1)
        {
            throw new ArgumentOutOfRangeException(nameof(capacity));
        }
        Capacity = capacity;
    }

    /// <summary>Gets or sets the maximum number of items the bounded channel may store.</summary>
    public int Capacity { get; }

    /// <summary>Gets or sets the behavior incurred by write operations when the channel is full.</summary>
    public BoundedChannelFullMode FullMode
    {
        get => _mode;
        set
        {
            switch (value)
            {
                case BoundedChannelFullMode.Wait:
                case BoundedChannelFullMode.DropNewest:
                case BoundedChannelFullMode.DropOldest:
                case BoundedChannelFullMode.DropWrite:
                    _mode = value;
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(value));
            }
        }
    }
}
```

### API Usage

We won't have capacity property in object initialization
![image](https://user-images.githubusercontent.com/68565441/167030703-d37ff3b3-cf0c-4220-9e62-3a0ca89eb048.png)

**Comment by stephentoub** [comment]
We're not going to remove a public API that has already shipped.  If the concern is that there's double-validation happening, it's fine for the ctor to be changed to do:
```C#
_capacity = capacity;
```
instead of:
```C#
Capacity = capacity;
```

**Comment by ArminShoeibi** [comment]
> We're not going to remove a public API that has already shipped. If the concern is that there's double-validation happening, it's fine for the ctor to be changed to do:
> 
> ```cs
> _capacity = capacity;
> ```
> 
> instead of:
> 
> ```cs
> Capacity = capacity;
> ```

Oh I got it, May I open a pull request for it?

**Comment by stephentoub** [comment]
Sure. Thanks.
