### ISSUE TITLE
LLVM AOT cross-compile CoreCLR tests fail in all PR

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#68932]
## Build Information
Build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1754181
Build error leg: LLVM AOT cross-compile CoreCLR tests
Pull request: https://github.com/dotnet/runtime/pull/68888

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "" 
}
```

**Comment by jkotas** [comment]
The error is: ` error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/System.Net.Quic.dll" exited with code 134.`

It was likely introduced by https://github.com/dotnet/runtime/pull/68288 cc @ManickaP

**Comment by jkotas** [comment]
@SamMonoRT @steveisok Do you expect to have fix or workaround for this soon? If not, we should revert the offending PR.

**Comment by SamMonoRT** [comment]
@jkotas @steveisok - I don't believe the PR is related to Mono AOT LLVM causing the failures, and I totally support the Reverting of offending PR.
