### ISSUE TITLE
[Analyzer proposal]: Simplify calls to string.Substring and Memory/Span.Slice

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#68946]
Inspired by Steve's comment at https://github.com/dotnet/runtime/pull/68937#issuecomment-1119127552.

We should consider promoting usage of `Substring/Slice(offset)` over `Substring/Slice(offset, length)` for "slice to the end of the buffer" scenarios. In both cases it makes the code a little easier to read and is less error-prone since it doesn't require the caller to get the _length_ check correct. And for _Slice_ specifically, it will result in slightly better codegen.

```cs
// Detect these patterns
someString.Substring(expression, someString.Length - expression);
someMemory.Slice(expression, someMemory.Length - expression);
someSpan.Slice(expression, someSpan.Length - expression);

// And replace them with these:
someString.Substring(expression);
someMemory.Slice(expression);
someSpan.Slice(expression);
```

Any analyzer / fixer would need to be a little smart and ensure that evaluating neither _this_ nor _expression_ has side effects, otherwise changing the number of occurrences from 2 to 1 would result in an observable behavioral change. This means that we might not be able to trigger the analyzer / fixer if _this_ or _expression_ contains a property accessor, unless we can reason that the property accessor is a dumb field wrapper.

The prevalent patterns that I saw in https://github.com/dotnet/runtime/pull/68937 were:

```cs
value.Substring(local, value.Length - local);
value.Substring(local1 + local2, value.Length - local1 - local2);
value.Substring(local1 + local2, value.Length - (local1 + local2));
value.Substring(field, value.Length - field);
value.Substring(field + const, value.Length - field - const);
value.Substring(field + const, value.Length - (field + const));
```

Suggested category: Maintainability
Suggested severity: Info

**Comment by carlossanlop** [comment]
@GrabYourPitchforks your proposal looks ready for review, especially since you already found a bunch of cases in https://github.com/dotnet/runtime/pull/68937/ .

**Comment by terrajobst** [comment]
* Looks good as proposed

Category: Maintainability
Severity: Info

**Comment by TonyValenti** [comment]
Instead of using Substring, would it be better to use the slice syntax?

Ie. String[x..] ?

**Comment by dstarosta** [comment]
I wish it would also report a missing check for length when the optimization is not applicable. That is one of the biggest sources of bugs I have seen with .NET in my experience.

**Comment by cybertyche** [comment]
> Instead of using Substring, would it be better to use the slice syntax?
> 
> Ie. String[x..] ?

Given that there is already another analyzer that does that particular recommendation (move from string.Substring(foo) to string[foo..]) it does seem prudent to go directly to the slice syntax rather than create a syntax that another analyzer is just going to flag.

**Comment by cybertyche** [comment]
On the other hand, the rule that suggests the slice syntax as a simplification of substring is an IDE not a CA warning. It might therefore be good to do it in two parts, one that removes the second parameter (CA) and one that then suggests moving to the slice syntax (IDE).

**Comment by mpidash** [comment]
I would like to work on this analyzer if that is ok.

**Comment by carlossanlop** [comment]
@mpidash thank you for offering your help! I'm assigning the issue to you.

If you have any questions, feel free to ask @mavasani, @Youssef1313, @buyaa-n or I for help.
