### ISSUE TITLE
Reduce unnecessary allocations in TLS handshake (windows)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#68951]
### Description

I'm beginning to look at the performance of establishing connections on ASP.NET Core and doing some CPU and allocation profiles. I'm storing my findings as I learn more about the current performance characteristics.

### Configuration

- This was running on windows 11 x64

### Regression?

No

### Data

<img width="859" alt="image" src="https://user-images.githubusercontent.com/95136/167078978-399406fd-082e-4590-88cb-75b9318b46ee.png">

I tried pasting markdown but it kept flubbing the formatting.

### Analysis

It seems like there are a lot of small byte[] allocations and copies that in some cases could be removed.

**Comment by wfurt** [comment]
Some of it will be addressed by #68678 @davidfowl. 
ProtocolToken is on my list. We can turn it into struct, abandon completely or pool. 
I'm not sure if there is good way for the ALPN with current API.

**Comment by davidfowl** [comment]
Music to my ears @wfurt! I want to do the same for *nix.

**Comment by wfurt** [comment]
give it try with 7.0 @davidfowl. It should be bit better. There is probably still room for some improvements. 
Test in performance repo is always appreciated.

**Comment by wfurt** [comment]
Here is current mainline (basically same as 7.0) for 1K handshakes. 
![image](https://user-images.githubusercontent.com/14356188/213843027-b54ff897-0f46-4cbc-a361-8e120a0e046a.png)

As I mentioned I have plan for the  `ProtocolToken` but the `SelectClientCertificate` is 7.0 regression. I was looking at doing something similar for `RemoteCertificateValidation` @rzikm but we may need to find different mechanism.

**Comment by davidfowl** [comment]
Excellent progress! Here's what I see is remaining on windows:

<img width="1022" alt="image" src="https://github.com/dotnet/runtime/assets/95136/65008d9f-6bc7-45bc-8c17-0bbe6208cc50">

Lots of small `byte[]` from the handshake.

**Comment by wfurt** [comment]
how many rounds/handshake this is @davidfowl? There will be some allocations for credential cache and but that should stabilize over time if you go to same destination. I'll double check the handles.

**Comment by davidfowl** [comment]
I was testing all handshakes. This is the worst-case scenario (http1.0 style connection per request). While this isn't the most representative scenario, we've found that service front ends often end up serving a very small number of requests per connection. 

Is there any reason this code path doesn't use pooling (or stackalloc?) Do we need to hold onto these buffers long term?

**Comment by davidfowl** [comment]
I don’t know this code well but it seems like we feed tls frames into schannel or open ssl and they return byte[] to send to the other side (server or client). Is there anything special about why that buffer isn’t pooled?

**Comment by davidfowl** [comment]
Took a look on Linux and it seems like it does similar things but fewer smaller allocations during the handshake:

These are the allocations (much harder to see in perfview right now):

<img width="872" alt="image" src="https://github.com/dotnet/runtime/assets/95136/11ec379e-14cb-4a7a-8b6e-0be4ab175fcc">

This is the stack for the 168 byte[] allocations:

<img width="1196" alt="image" src="https://github.com/dotnet/runtime/assets/95136/0dc006d5-f756-4f60-9cd8-d08d2edfe2ca">

**Comment by davidfowl** [comment]
This obviously isn't urgent for 8 (unless its low hanging fruit), let me know if you want me to open a new issue (but this one has all the details).

**Comment by davidfowl** [comment]
In a normal run (longer lived connections), I see the bigger allocations (1976 length byte[]) in the hanshake:

<img width="807" alt="image" src="https://github.com/dotnet/runtime/assets/95136/1cba0f32-5d95-4f2e-9f2f-f4be65b86a76">


<img width="1007" alt="image" src="https://github.com/dotnet/runtime/assets/95136/4a058548-6dbb-4d72-9ce8-29b455ea94ea">

**Comment by wfurt** [comment]
the tricky part is lifetime management. The array is allocated in PAL code but it needs to be preserved for certain time. We would need to either make it common for all PALs, communicate up if the array was rented or allocated or we would need to change PAL interface to offer back the array. Alternatively we can propagate back the native memory as al this is internal to SslStream.

**Comment by davidfowl** [comment]
Is there a requirement that the PAL allocate? Why isn't the lifetime of the buffer controlled from the outside? (other than this was how it was originally written).

**Comment by wfurt** [comment]
you don''t know upfront how much you need. We would need to allocate maximum frame size IMHO. That still may be cheaper if pooled and re-used.

**Comment by davidfowl** [comment]
Right, I can see several options, the PAL could always use the array pool directly and the ssl stream could be responsible for returning it (the protocol token could have a pooled Boolean to make the code easier to understand). This feels like the easist solution.

The caller could pass down the growable buffer that ssl stream uses into the PAL (ArrayBuffer). 

Either of those feel like reasonable and small changes (because of all of the other great refactoring work!)

**Comment by wfurt** [comment]
With https://github.com/dotnet/runtime/pull/87874 done, there is not much left IMHO. We _could_ turn `SslAuthenticationOptions` to struct. But I'm not sure it would move the needle. 
So I'm inclined to call it done @davidfowl. We can always open new issue and do more if we see more opportunities.
BTW It would be great if you can repeat you tests once we get new build out.

**Comment by davidfowl** [comment]
Will do! I alerted the perf crew of these changes as well. This is excellent work @wfurt!

**Comment by davidfowl** [comment]
Can you do a run and show what you see in a local profile with these changes ?

**Comment by wfurt** [comment]
I still plan to run the tests but I did not get to it yet @davidfowl  ;(
