### ISSUE TITLE
[API Proposal]: Additional Regex.EnumerateMatches/Count overloads

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#68959]
### Background and motivation

The existing `Regex.Matches` method has an overload that accepts an `int startat`, but the newly added `EnumerateMatches` method lacks such an overload.  While you can slice the input span to begin at some position into the input, there's a difference in regex between "beginning" and "starting".  The former means there's no available input prior to where the matching process first runs, whereas the latter means there may be available input prior to where the matching process first runs.  That's relevant for lookbehinds, as a lookbehind can see text prior to a "startat" but not prior to a "beginning".  And it means uses like:
https://github.com/dotnet/runtime/blob/ed2472b72679ff5ca0fa56996cf15d2fc303c7db/src/libraries/System.Private.Xml/src/System/Xml/XmlConvert.cs#L195-L200
which could otherwise shift to using `EnumerateMatches` for a performance gain are unable to do so, as this particular case has a lookbehind and uses a potentially positive startat value.

### API Proposal

```diff
public class Regex
{
    // Existing
    public MatchCollection Matches(string input, int startat);
    public Match Match(string input, int startat);
    public bool IsMatch(string input, int startat);

    // Previously added in .NET 7
    public int Count(System.ReadOnlySpan<char> input);
    public Regex.ValueMatchEnumerator EnumerateMatches(System.ReadOnlySpan<char> input);

    // Proposed
+   public int Count(System.ReadOnlySpan<char> input, int startat);
+   public Regex.ValueMatchEnumerator EnumerateMatches(System.ReadOnlySpan<char> input, int startat);
}
```

### API Usage

```csharp
foreach (ValueMatch m in _regex.EnumerateMatches(input, startat))
{
    ...
}
```

**Comment by joperezr** [comment]
Sounds good to me. I did consider adding this as well to match other APIs, but didn't because I saw that slicing would be a workaround, but I do see your point about lookbehinds is valid, so I agree this should be added..

**Comment by KieranDevvs** [comment]
Should `startat` be camel case? i.e `startAt`?

**Comment by stephentoub** [comment]
> Or is it being left as the existing API's have it named this way?

Right, I was being consistent with the existing parameters casing.

**Comment by terrajobst** [comment]
* Makes sense

```C#
namespace System.Text.RegularExpressions;

public class Regex
{
    // Existing
    // public MatchCollection Matches(string input, int startat);
    // public Match Match(string input, int startat);
    // public bool IsMatch(string input, int startat);

    // Previously added in .NET 7
    // public int Count(ReadOnlySpan<char> input);
    // public ValueMatchEnumerator EnumerateMatches(ReadOnlySpan<char> input);

    public int Count(ReadOnlySpan<char> input, int startat);
    public ValueMatchEnumerator EnumerateMatches(ReadOnlySpan<char> input, int startat);
}
```
