### ISSUE TITLE
[API Proposal]: MultipartContent.cs  constructor or public property to control usage of double quotes in boundary

### ISSUE THREAD

**Issue by syedalam74** [dotnet/runtime#68968]
### Background and motivation

The .net core MultipartContent.cs adds double quotes to the boundary for Content-Type. However Azure WAF and others forbids the http request due to these quotes.
The applicable WAF Rule is  200003 - Multipart Request Body Strict Validation failure
 https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/MultipartContent.cs ( see lines 40 to 55 )
 
https://www.rfc-editor.org/rfc/rfc2046#section-5.1 ( see section 5.1.1 )
  
Below might be also applicapale
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#MULTIPART_STRICT_ERROR

The suggestion is add a public property or constructor parameter to specify whether doublequotes should be used or not. 

### API Proposal

```csharp
namespace System.Net.Http;

public class MultipartContent : HttpContent, IEnumerable<HttpContent>
    {
  public MultipartContent(string subtype, bool useQuotesForBoundary )
{

}

   public MultipartContent(string subtype, string boundary, bool useQuotesForBoundary )
        {
        }  

}
```

### API Usage

```csharp
// Create an insatance of MultipartFormDataContent and we dont to use double quoutes in the boundary
var content = new MultipartFormDataContent($"------------------------{DateTime.UtcNow.Ticks",false)




### Alternative Designs

 // An App Level fix exists and it is to manually retreive the header and then remove the quotes from the boundary
       // var boundary = content.Headers.ContentType.Parameters.First(o => o.Name == "boundary");
       // boundary.Value = boundary.Value.Replace("\"", String.Empty);

### Risks

_No response_

**Comment by ManickaP** [comment]
> The grammar for parameters on the Content-
   type field is such that it is often necessary to enclose the boundary
   parameter values in quotes on the Content-type line.  This is not
   always necessary, but never hurts.
   
What I get from the RFC is that it should always be possible to quote the boundary and it seems to me that Azure WAF is not following the specs here. Or am I interpreting the specs wrongly?

**Comment by syedalam74** [comment]
May be the quotes are only needed when the boundary contains some special chars
https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

https://www.rfc-editor.org/rfc/rfc2046#section-5.1 ( see section 5.1.1 )
the valid example in above with quotes has a special char

**Comment by wfurt** [comment]
The quoted value should be fully legal. Adding conditions and searching for special characters is going to be problematic IMHO. I don't think we should API to workaround over paranoid WAFs. The SpiderMonky comment admits that may block legal syntax.

**Comment by karelz** [comment]
Triage: Given that the endpoints violate RFC, we do not think we need to change. It would be best to raise it up with them.
If it has wider industry use to violate RFC, we might consider it. Although adding API is weird.

Closing for now, until we have more evidence that this is the new default way on the internet, despite RFC saying the opposite.
