### ISSUE TITLE
File.Copy on macOS wrong escape of characters

### ISSUE THREAD

**Issue by Quentin-Harnay** [dotnet/runtime#68960]
### Description

I create a file in MacOS and i add a extended attributes to this file. After i use the dotnet method  File.Copy  to copy this file to another path and when i show the extended attributes of the file there is a mistake with space character.

You can see the dump of extended attribute of files : 

![Capture d’écran 2022-05-06 à 14 25 44](https://user-images.githubusercontent.com/67709967/167131851-9490a39b-4c36-41af-a6a7-fe1e5267be84.png)

### Reproduction Steps

1.  Create an excel file on your MacOS
2. Check the extended attribute of original file
```sh
xattr -l file.xlsx
```
3. Use this code :
 ```c#
  string fileName = "file.xlsx;
  string sourcePath = @"/Users/toto/Desktop/";
  string targetPath = @"/Users/toto/Desktop/subdir/";
  
  // Use Path class to manipulate file and directory paths.
  string sourceFile = System.IO.Path.Combine(sourcePath, fileName);
  string destFile = System.IO.Path.Combine(targetPath, fileName);

   System.IO.Directory.CreateDirectory(targetPath);

   System.IO.File.Copy(sourceFile, destFile, true);
```
4. Check the extended attribute of new file
```sh
xattr -l file.xlsx
```

### Expected behavior

On the new file you can execute : 
```sh
xattr -l file.xlsx
```
we need to see that : 

![Capture d’écran 22022-05-06 à 14 25 44](https://user-images.githubusercontent.com/67709967/167152482-b324f612-5fd0-4300-b827-c25bd42234d6.png)

### Actual behavior

On the new file you can execute : 
```sh
xattr -l file.xlsx
```

And now we see that : 

![Capture d’écran 24022-05-06 à 14 25 44](https://user-images.githubusercontent.com/67709967/167152534-d9346f30-34b3-4e94-b7aa-26ef3f24a95b.png)

### Configuration

.NET version : 3.1 | 5.0 | 6.0
MacOS Monterey version : 12.3.1 (21E258)

**Comment by danmoseley** [comment]
Thanks for the report. Are you interested in investigating a little?

**Comment by Quentin-Harnay** [comment]
I try in 3.1 and 5 and it's the same result

**Comment by danmoseley** [comment]
Thanks. Are you interested in debugging some to get an idea where the problem might be?

**Comment by danmoseley** [comment]
We are likely going here https://github.com/dotnet/runtime/blob/78bf14a4111a0b6760a2321b6f8759c83674b216/src/native/libs/System.Native/pal_io.c#L1255

and https://www.unix.com/man-page/osx/3/fcopyfile/ says COPYFILE_ALL includes extended attributes. Anyway, from your screenshot it appears that they're getting copied, but a space is escaped.

If you just copy the file yourself with `cp` at the shell, does this happen?

**Comment by Quentin-Harnay** [comment]
No when i use the command `cp`  the space is escaped

**Comment by danmoseley** [comment]
Does it happen with a simple test file (not xlsx format) where you've added an extended attribute yourself (with a space in it)?

**Comment by Quentin-Harnay** [comment]
You are right, it's working with an extended attribute added yourself, but not for example for Excel file.

**Comment by Quentin-Harnay** [comment]
I test again with the `cp` and it's doesn't work so, the problem it isn't dotnet.

I am sorry that you have lost your time!

**Comment by Jozkee** [comment]
No worries, please come back if you think the issue does involve dotnet.
