### ISSUE TITLE
EBCDIC en/decoding in System.Text does not work

### ISSUE THREAD

**Issue by fasteddys** [dotnet/runtime#68970]
Hello, EBCDIC is the mainframe text file encoding that MS supports

But while using the System.Text here https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Text.Encoding.CodePages/src/System/Text/EncodingTable.Data.cs I get arbitrary errors when in production. 

From troubleshooting, one case was when the system/software receives a new format listed, and switches to other English/global encodings if fails on some data types, i.e. exception for some of the EBCDIC character.

Is it supported in both net & .net core 6?

**Comment by tarekgh** [comment]
@fasteddys I assume you are referring to the code page [IBM037](https://en.wikipedia.org/wiki/Code_page_37). right? It will be helpful to send examples of what text is failing in your case? The [chart](https://en.wikipedia.org/wiki/Code_page_37) has all supported characters can be mapped with such encoding. Writing a small sample demonstrating the failure will be helpful.

**Comment by fasteddys** [comment]
hello, we were running a large set of files and we saw several errors on some of the US based variants.

In our text per your mSDN page 

![image](https://user-images.githubusercontent.com/96149622/168706174-030f32d7-81c6-4e6a-a9c4-c8df2a5076aa.png)

using System.Text;
//...

// From ASCII to EBCDIC
byte[] ascii = ... // Initialize to your ASCII bytes
string unicode = Encoding.ASCII.GetString(ascii);
byte[] ebcdic = Encoding.GetEncoding(500).GetBytes(unicode);

// From EBCDIC to ASCII
byte[] ebcdic = ... // Initialize to your EBCDIC bytes
string unicode = Encoding.GetEncoding(500).GetString(ebcdic);
byte[] ascii = Encoding.ASCII.GetBytes(unicode);

**Comment by tarekgh** [comment]
Which encoding are you trying to create by `Encoding.GetEncoding(500)`? `500` is an invalid codepage number and expected to fail. The correct codepage numbers is listed in your image https://user-images.githubusercontent.com/96149622/168706174-030f32d7-81c6-4e6a-a9c4-c8df2a5076aa.png in the second column. I mean `1140`, `37`, `1146`, and `20285`.  Look at the [Example](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.getencodings?view=net-6.0#examples) which produces the complete supported encoding list with its names and codepage numbers. 

In your code you can use `Encoding.GetEncoding(1140)` as example to create the `EBCDIC U.S./Canada (Euro)` encoding known as `IBM01140` encoding.
