### ISSUE TITLE
[wasm] `startup.ts` has a fixed "max parallel downloads", but that can fail

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#68992]
Currently, it is set to `100`, but this can be too many, causing failures to fetch the resources.
We should handle this better.

I hit this on a codespaces container while running debugger tests. But this can be hit by a user too.

cc @pavelsavara @lewing @kg

**Comment by pavelsavara** [comment]
Our previous implementation was sequential, so we could further reduce it.
It mostly matters when there is slow-and-large file blocking the rest of the files from using the client bandwidth.

Also it would be good to check what strategy Blazor have.

**Comment by radical** [comment]
@thaystg and I have been seeing this when running debugger tests in codespaces.

**Comment by lewing** [comment]
Is this still an open issue?

**Comment by radical** [comment]
> Is this still an open issue?

Yes, very much!

**Comment by kg** [comment]
100 is way too many, it should be like 16 at most.

**Comment by radical** [comment]
> 100 is way too many, it should be like 16 at most.

Also, we should be able to recover if even 16 is too much. Like on codespaces I have to edit startup.ts to change the number, and rebuild to make it work.
