### ISSUE TITLE
PAL uses wrong type for chflags flags

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#69005]
As noted [here](https://github.com/dotnet/runtime/pull/60507#pullrequestreview-962048250)

We are passing uint32_t as the 2nd parameter to lchflags
https://github.com/dotnet/runtime/blob/78bf14a4111a0b6760a2321b6f8759c83674b216/src/native/libs/System.Native/pal_io.c#L1661-L1665

However glibc chflags.c declares it `int chflags (const char *file, unsigned long int flags)`. `unsigned long int` on Unix is the size of a native word, so potentially 64 bit. 

How does this compile - I must be missing something? and do we have this mistake elsewhere?

cc @tmds

**Comment by janvorli** [comment]
@danmoseley I don't see a problem here - it is ok to pass 32 bit uint as 64 bit uint argument. The only potential issue is that we would not be able to pass in flags that have values > 2^32 from the managed side.

**Comment by danmoseley** [comment]
@janvorli  this means that I can compile using `PALEXPORT int32_t SystemNative_LChflags(const char* path, uint32_t flags);` in pal_io.h , and then link to libc code compiled with `int chflags (const char *file, unsigned long int flags)`? That's what surprised me, based on a naive understanding. (My C is very rusty)

But thanks for the info, I'll close.

**Comment by janvorli** [comment]
@danmoseley conversion from smaller unsigned data type to a larger one is valid in C. The SystemNative_LChflags code would do that before passing it to the chflags. Here are some examples: https://www.guru99.com/c-type-casting.html

**Comment by tmds** [comment]
The conversion rule is similar to C#.
We can tackle the loss of flags > 32-bit as part of https://github.com/dotnet/runtime/issues/69004.
