### ISSUE TITLE
Application goes to break mode and pops up an exception when stop running application

### ISSUE THREAD

**Issue by Cassie-Li01** [dotnet/runtime#69001]
### Description

System.TypeLoadException: 'Could not load type 'System.Runtime.InteropServices.AnsiStringMarshaller' from assembly 'System.Runtime.InteropServices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'

### Reproduction Steps

1. Create a .Net 7.0 application
2. Run the application and stop it

### Expected behavior

Stop application normally

### Actual behavior

Application goes to break mode and pops up an exception
![image](https://user-images.githubusercontent.com/96758262/167234881-b4356966-3169-4e64-841c-81ce1781fe44.png)
![Repro](https://user-images.githubusercontent.com/96758262/167234868-ec810006-28d2-4c32-8061-46915af6846f.gif)

### Regression?

Yes, it is a regression issue, cannot repro in .Net 7.0.100-preview.5.22255.6

**Comment by danmoseley** [comment]
Related to #67635 ? @elinor-fung

**Comment by jkotas** [comment]
This error means that you have built against one .NET 7 preview build and running against a different .NET 7 preview build. We often make breaking changes between preview builds. We do not make any guarantees about binaries compatibility between preview builds.

**Comment by Cassie-Li01** [comment]
This issue fixed on build: .NET 7.0.100-preview.5.22258.1. 
![Fixed](https://user-images.githubusercontent.com/96758262/167382874-b021d903-6643-4681-806d-41156e0e38d2.gif)
