### ISSUE TITLE
Perf: JIT does not optimize pattern "~x + 1"

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#69003]
Based on a comment at https://github.com/dotnet/runtime/pull/68964#discussion_r867278459.

In _main_, current JIT compiles this method:
```cs
static uint Negate(uint value) => ~value + 1;
```

To this in release mode:
```asm
; Method ConsoleApp106.Program:Negate(int):int
G_M48540_IG01:
						;; size=0 bbWeight=1    PerfScore 0.00

G_M48540_IG02:
       mov      eax, ecx
       not      eax
       inc      eax
						;; size=6 bbWeight=1    PerfScore 0.75

G_M48540_IG03:
       ret      
						;; size=1 bbWeight=1    PerfScore 1.00
; Total bytes of code: 7
```

JIT should be taught to recognize the pattern `~x + 1` and turn it into a two's-complement `neg` instruction.

**Comment by EgorBo** [comment]
Closed via https://github.com/dotnet/runtime/pull/69600
