### ISSUE TITLE
`System.Runtime.Serialization`'s `DataContractJsonSerializer.ReadObject` loses the sign when reading "-0" as a double

### ISSUE THREAD

**Issue by notcake** [dotnet/runtime#69019]
### Description

`System.Runtime.Serialization.Json.DataContractJsonSerializer` round trips `double`s as follows:

| double originalValue      | string serializedValue | double deserializedValue  | 
|---------------------------|------------------------|---------------------------|
| `double.NaN`              | `"NaN"`                | `double.NaN`              |
| `double.PositiveInfinity` | `"INF"`                | `double.PositiveInfinity` |
| `double.NegativeInfinity` | `"-INF"`               | `double.NegativeInfinity` |
| `0.0`                     | `"0"`                  | `0.0`                     |
| `-0.0`                    | `"-0"`                 | `0.0` (wrong!)            |

The sign of `-0` is lost upon deserialization as a `double`. The same applies to `float`s.

This bug is the cause of https://github.com/microsoft/testfx/issues/1096, which remains unfixed.

### Reproduction Steps

```cs
double originalValue = -0.0;
string expectedSerialization = "-0";

DataContractJsonSerializer dataContractJsonSerializer = new(typeof(double));

// Serialize `originalValue`.
MemoryStream memoryStream = new();
dataContractJsonSerializer.WriteObject(memoryStream, originalValue);
string serializedValue = Encoding.UTF8.GetString(memoryStream.ToArray());
Assert.AreEqual(expectedSerialization, serializedValue);

// Now deserialize it.
memoryStream.Seek(0, SeekOrigin.Begin);
object? obj = dataContractJsonSerializer.ReadObject(memoryStream);

if (obj is double deserializedValue)
{
    Assert.AreEqual(originalValue, deserializedValue);
    // Now check the sign.
    // This assertion fails.
    Assert.AreEqual(1.0 / originalValue, 1.0 / deserializedValue, $"Deserialization of {serializedValue} had wrong sign.");
}
```

### Expected behavior

The negative sign of the double is preserved.

### Actual behavior

The negative sign is lost.

### Regression?

Unlikely

### Configuration

.NET 6

### Other information

`System.Private.DataContractSerialization`'s `System.Xml.XmlConverter.TryParse{Single,Double}` is the source of the bug:
https://github.com/dotnet/runtime/blob/722d55040a63de27430a500d388a8f6cbbe86734/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlConverter.cs#L649-L699

Line 695 ought to be `result = -(double)value;`, since `value` is an `int`.

**Comment by StephenMolloy** [comment]
For context, this ignoring the negative sign is also the behavior with DCS, and it is also true of both serializers in 4.8 as well.
