### ISSUE TITLE
how can I get "macroman" encoding

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#69017]

**Comment by am11** [comment]
Like this:
1. add package: `dotnet add package System.Text.Encoding.CodePages`
2. use the following code:
    ```c#
    using System;
    using System.Text;

    Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

    // macroman's codepage is 10000 (https://en.wikipedia.org/wiki/Mac_OS_Roman#Technical_notes)
    const int WesternEuropeanMacCodePage = 10000;
    Encoding westernEuropeanMacEncoding = Encoding.GetEncoding(WesternEuropeanMacCodePage);

    Console.WriteLine("Encoding name is: {0}", westernEuropeanMacEncoding.EncodingName);
    ```

`Encoding name is: Western European (Mac)`

**Comment by tarekgh** [comment]
A quick notes:

> const int WesternEuropeanMacCodePage = 10000;
> Encoding westernEuropeanMacEncoding = Encoding.GetEncoding(WesternEuropeanMacCodePage);

You can create the encoding using the encoding name too:
```C#
Encoding.GetEncoding("macintosh");
```

> add package: dotnet add package System.Text.Encoding.CodePages

`System.Text.Encoding.CodePages` became inbox library so you don't need to manually reference this package anymore.

**Comment by am11** [comment]
Thanks for the updated info @tarekgh.
Is it intentional that newer versions of this are being published to nuget.org https://www.nuget.org/packages/System.Text.Encoding.CodePages/7.0.0-preview.3.22175.4? We stopped publishing other inbox packages (e.g. https://www.nuget.org/packages/System.IO.Compression/4.3.0).

**Comment by tarekgh** [comment]
> Is it intentional that newer versions of this package are being published to nuget.org [nuget.org/packages/System.Text.Encoding.CodePages/7.0.0-preview.3.22175.4](https://www.nuget.org/packages/System.Text.Encoding.CodePages/7.0.0-preview.3.22175.4)? We stopped publishing other inbox packages (e.g. [nuget.org/packages/System.IO.Compression/4.3.0](https://www.nuget.org/packages/System.IO.Compression/4.3.0)).

This could be because we still support `net core 3.1` which can reference the recent version of the package. Also, in the future we may decide to add more encodings to this library that allow us to use such new encoding on the .NET Framework too.

**Comment by srxqds** [comment]
thanks
