### ISSUE TITLE
NativeAOT: ilc compilation failure against Interop+Kernel32.GetProcAddress

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#69026]
Found while compiling a Winforms app with NativeAOT.

```
ILC: Method '[Microsoft.Win32.SystemEvents]Interop+Kernel32.GetProcAddress(native int,string)' will always throw beca
  use: Failed to load type 'System.Runtime.InteropServices.AnsiStringMarshaller' from assembly 'System.Runtime.InteropS
  ervices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

This is causing winforms app crashing on exit.

Version: 7.0.0-preview.5.22257.1

**Comment by jkotas** [comment]
This is same problem as https://github.com/dotnet/runtime/issues/69001#issuecomment-1120141177 . It will fix itself once the AnsiStringMarshaller namespace change flows through the system.
