### ISSUE TITLE
Review .NET 5 usages

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#69028]
.NET 5 has reached its end of life today. We should review its remaining usages in the runtime repo and rev them to .NET 6 or 7 (preferably using variable like `$(NetCoreAppCurrent)` where possible).

```sh
# net 5 in file contents
% git grep -Eli 'net(coreapp)?5'

docs/design/coreclr/jit/viewing-jit-dumps.md
docs/workflow/building/libraries/cross-building.md
docs/workflow/debugging/coreclr/debugging.md
docs/workflow/testing/coreclr/running-aspnet-benchmarks-with-crossgen2.md
docs/workflow/testing/host/testing.md
eng/Signing.props
eng/common/SetupNugetSources.ps1
eng/common/SetupNugetSources.sh
eng/testing/performance/performance-setup.ps1
eng/testing/performance/performance-setup.sh
src/coreclr/tools/r2rtest/Commands/CompileNugetCommand.cs
src/installer/managed/Microsoft.NET.HostModel/Bundle/Manifest.cs
src/installer/managed/Microsoft.NET.HostModel/Bundle/TargetInfo.cs
src/installer/tests/Assets/TestProjects/PortableTestApp/PortableTestApp.csproj
src/installer/tests/Assets/TestProjects/StandaloneTestApp/StandaloneTestApp.csproj
src/installer/tests/HostActivation.Tests/FrameworkResolution/MultipleHives.cs
src/installer/tests/TestUtils/Constants.cs
src/libraries/Common/tests/StaticTestGenerator/Program.cs
src/libraries/Common/tests/StaticTestGenerator/README.md
src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/AsyncServiceScope.cs
src/libraries/Microsoft.Extensions.DependencyModel/tests/DependencyContextJsonReaderTest.cs
src/libraries/Microsoft.Extensions.FileProviders.Composite/tests/MockFileProvider.cs
src/libraries/Microsoft.Extensions.Hosting/tests/FunctionalTests/IntegrationTesting/src/Common/Tfm.cs
src/libraries/Microsoft.Extensions.Hosting/tests/FunctionalTests/ShutdownTests.cs
src/libraries/System.Diagnostics.DiagnosticSource/tests/ActivityTests.cs
src/libraries/System.Formats.Cbor/src/CompatibilitySuppressions.xml
src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems
src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs
src/libraries/System.Private.CoreLib/src/System/Random.cs
src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/AdditionalAttributesOnStub.cs
src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Compiles.cs
src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs
src/libraries/System.Security.Permissions/src/CompatibilitySuppressions.xml
src/libraries/System.Text.Encoding.CodePages/src/Data/Tools/EncodingDataGenerator.csproj
src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.WriteCore.cs
src/libraries/testPackages/testPackages.proj
src/native/corehost/bundle/header.h
src/tests/BuildWasmApps/Wasm.Build.Tests/BlazorWasmTests.cs
src/tests/BuildWasmApps/testassets/Blazor_net50/Blazor_net50.csproj
src/tests/BuildWasmApps/testassets/Blazor_net50/Program.cs
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/NavMenu.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/_Imports.razor
src/workloads/workloads.csproj

# net 5 in file names
$ git ls-files | grep -Ei 'net(coreapp)?5'

src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs
src/tests/BuildWasmApps/testassets/Blazor_net50/App.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Blazor_net50.csproj
src/tests/BuildWasmApps/testassets/Blazor_net50/Pages/Counter.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Pages/FetchData.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Pages/Index.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Program.cs
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/MainLayout.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/MainLayout.razor.css
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/NavMenu.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/NavMenu.razor.css
src/tests/BuildWasmApps/testassets/Blazor_net50/Shared/SurveyPrompt.razor
src/tests/BuildWasmApps/testassets/Blazor_net50/_Imports.razor
```

**Comment by ArminShoeibi** [comment]
> @am11 some of these are false positives but some can be updated to ie `NetCoreAppToolCurrent` or `NetCoreAppCurrent`. Would you like to send a PR? :)

Hello there Viktor, I can work on it.

**Comment by am11** [comment]
@ArminShoeibi, feel free to take it. I am not actively working on it. There are also file names falling into that pattern, see the updated top post.

**Comment by ArminShoeibi** [comment]
> @ArminShoeibi, feel free to take it. I am not actively working on it. There are also file names falling into that pattern, see the updated top post.

Thanks 😍 I'm on it.

**Comment by ArminShoeibi** [comment]
Hello there Stephen @stephentoub, I want to delete Net5 from this class
https://github.com/dotnet/runtime/blob/7b89c8634ead6ea88ddcae32e3145b250f3d687d/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L16
could you please tell me the proper name for this class

**Comment by danmoseley** [comment]
> could you please tell me the proper name for this class

I ahead to leave that one alone as it's special - specifically for back compat.

Thanks for tackling this - my suggestion is to put renames in a different PR to content changes, for ease of review. In general, smaller PRs get merged more quickly.

**Comment by stephentoub** [comment]
> I suggest to leave that one alone as it's special - specifically for back compat.

Yes, this one is saying that it provides the same behavior as .NET 5 and earlier.  It should remain.

**Comment by ArminShoeibi** [comment]
> > could you please tell me the proper name for this class
> 
> I suggest to leave that one alone as it's special - specifically for back compat.
> 
> Thanks for tackling this - my suggestion is to put renames in a different PR to content changes, for ease of review. In general, smaller PRs get merged more quickly.

Ok I got it Dan.

**Comment by ArminShoeibi** [comment]
I'm going to skip these files:

src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/AsyncServiceScope.cs
src/installer/tests/Assets/TestProjects/PortableTestApp/PortableTestApp.csproj
src/installer/tests/Assets/TestProjects/StandaloneTestApp/StandaloneTestApp.csproj
src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs
src/libraries/System.Private.CoreLib/src/System/Random.cs
src/native/corehost/bundle/header.h

**Comment by ArminShoeibi** [comment]
I need some guidance on this two files.

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/tests/FunctionalTests/IntegrationTesting/src/Common/Tfm.cs#L16

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Hosting/tests/FunctionalTests/ShutdownTests.cs#L66

Should I change these two NetCoreApp60?

**Comment by BruceForstall** [comment]
@ArminShoeibi Are you still working on this?
