### ISSUE TITLE
HttpClient not redirect when donwload picture but Chrome can.

### ISSUE THREAD

**Issue by zhangqi-ulua** [dotnet/runtime#69025]
### Description

use Chinese:

用HttpClient下载图片时，AllowAutoRedirect设为了true
但下载：https://weibo.com/ajax/common/download?pid=0033ImPzly1h20lvgmgeaj60u01gqaw702
没有正确跳转请求去下载Redirecting to <a href="https://passport.weibo.com/visitor/visitor?entry=sinawap&amp;a=enter&amp;url=https%3A%2F%2Fweibo.com%2Fajax%2Fcommon%2Fdownload%3Fpid%3D0033ImPzly1h20lvgmgeaj60u01gqaw702&amp;domain=weibo.com&amp;_rand=1651991198232&amp;sudaref=">https://passport.weibo.com/visitor/visitor?entry=sinawap&amp;a=enter&amp;url=https%3A%2F%2Fweibo.com%2Fajax%2Fcommon%2Fdownload%3Fpid%3D0033ImPzly1h20lvgmgeaj60u01gqaw702&amp;domain=weibo.com&amp;_rand=1651991198232&amp;sudaref=</a>.

而在Chorme中输入 https://weibo.com/ajax/common/download?pid=0033ImPzly1h20lvgmgeaj60u01gqaw702 就可以正确下载

我看到有类似的：https://github.com/dotnet/runtime/issues/23801
但上面那个23801 issues 是 https -> http ，而我这个是https ->https，仍旧不行。

### Reproduction Steps

用HttpClient下载图片时，AllowAutoRedirect设为了true
但下载：https://weibo.com/ajax/common/download?pid=0033ImPzly1h20lvgmgeaj60u01gqaw702
没有正确跳转请求去下载Redirecting to <a href="https://passport.weibo.com/visitor/visitor?entry=sinawap&amp;a=enter&amp;url=https%3A%2F%2Fweibo.com%2Fajax%2Fcommon%2Fdownload%3Fpid%3D0033ImPzly1h20lvgmgeaj60u01gqaw702&amp;domain=weibo.com&amp;_rand=1651991198232&amp;sudaref=">https://passport.weibo.com/visitor/visitor?entry=sinawap&amp;a=enter&amp;url=https%3A%2F%2Fweibo.com%2Fajax%2Fcommon%2Fdownload%3Fpid%3D0033ImPzly1h20lvgmgeaj60u01gqaw702&amp;domain=weibo.com&amp;_rand=1651991198232&amp;sudaref=</a>.

而在Chorme中输入 https://weibo.com/ajax/common/download?pid=0033ImPzly1h20lvgmgeaj60u01gqaw702 就可以正确下载

### Expected behavior

能正确下载

### Actual behavior

无法下载

**Comment by hez2010** [comment]
The website that your URL pointed to is using JavaScript to execute the redirection in the browser, which cannot be handled by a HttpClient without a browser environment.

**Comment by zhangqi-ulua** [comment]
> The website that your URL pointed to is using JavaScript to execute the redirection in the browser, which cannot be handled by a HttpClient without a browser environment.

Thank you.
