### ISSUE TITLE
Avoid redundant marshaller copy by introducing `FromManagedValue` method

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#69031]
The source generated interop for string marshaling have unnecessary stack copies of the marshaller. 

## Proposal
Introduce `FromManagedValue` method on the string marshallers and use it to initialize the marshaller instead of the constructor.

## Details

```csharp
        [LibraryImport("...", StringMarshalling = StringMarshalling.Utf8)]
        public static partial void TestTest(string s);
```

The source generated interop for this simple method that takes utf8 string looks like this:
```csharp
        public static partial void TestTest(string s)
        {
            byte* __s_gen_native = default;
            //
            // Setup
            //
            global::System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller __s_gen_native__marshaller = default;
            try
            {
                //
                // Marshal
                //
                byte* __s_gen_native__marshaller__stackptr = stackalloc byte[256];
                __s_gen_native__marshaller = new(s, new System.Span<byte>(__s_gen_native__marshaller__stackptr, 256));
                __s_gen_native = __s_gen_native__marshaller.ToNativeValue();
                __PInvoke__(__s_gen_native);
            }
            finally
            {
                //
                // Cleanup
                //
                __s_gen_native__marshaller.FreeNative();
            }
...
```

`__s_gen_native__marshaller = new(s, new System.Span<byte>(__s_gen_native__marshaller__stackptr, 256));` is the problematic line. The JIT has to create a temporary stack copy of the marshaller, invoke the constructor on this temporary copy, and then copy this temporary on-stack over the local variable.

My proposal is to change this line to `__s_gen_native__marshaller.FromManagedValue(s, new System.Span<byte>(__s_gen_native__marshaller__stackptr, 256));` that will avoid the unnecessary on-stack copies.

**Comment by teo-tsirpanis** [comment]
Perhaps the name should be `InitFromManagedValue`; methods starting with `From` are typically expected to return something.

And can't the JIT be improved to eliminate the temporary stack copy?

**Comment by jkotas** [comment]
> Perhaps the name should be InitFromManagedValue;

Yes, makes sense. Or just `Initialize`.

> And can't the JIT be improved to eliminate the temporary stack copy?

It is hard for the JIT to do something about these temporary stack copies. The semantics of IL dictate that the constructor has to run against a temporary copy in the example above. The JIT would have to be able to inline the whole constructor to have a chance to eliminate some of the overhead of temporary copies and I do not think it would be able to do it completely even in that case.

**Comment by jkotas** [comment]
> > Perhaps the name should be InitFromManagedValue;

> Yes, makes sense. Or just Initialize.

Actually, there is an existing `void FromNativeValue(...)` method in the marshaller pattern. `void`-returning `FromManagedValue` would maintain symmetry with it.

**Comment by jkotas** [comment]
With https://github.com/dotnet/runtime/issues/69096#issuecomment-1121933198 taken into account, a good name may be `InitializeFromManagedValue`.

**Comment by jkotas** [comment]
Also, the current pattern where the marshaller initialization runs on a temporary copy has issues with cleanup on exceptions.

For example, consider what happens when this line in `AnsiStringMarshaller` throws for some reason: https://github.com/dotnet/runtime/blob/d3af4921f36dba8dde35ade7dff59a3a192edddb/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshalling/AnsiStringMarshaller.cs#L61 after we have allocated the buffer using `AllocCoTaskMem`. The buffer allocated using `AllocCoTaskMem` is going to leak. The source generated code is going to call `FreeNative` on the marshaller local variable, but the local variable won't be initialized with the active marshaller yet so no cleanup is going to occur.

(I have run into this problem when trying to unify built-in and source generated marshallers for Ansi strings. The built-in Ansi string marshaller is dealing with this problem using an explicit try/catch: https://github.com/dotnet/runtime/blob/2dc1889f5f40459f7c640867a25d0994dab3d868/src/coreclr/System.Private.CoreLib/src/System/StubHelpers.cs#L74-L83.)

**Comment by AaronRobinsonMSFT** [comment]
Closing this issue since the feedback has been incorporated into https://github.com/dotnet/runtime/issues/70859. If there are still concerns let's have the conversation on the new API shape proposal.
