### ISSUE TITLE
Support blittable type marshalling without `DisableRuntimeMarshalling`

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#69033]
Attempting to use `LibraryImport` in the aspnetcore repo (https://github.com/dotnet/aspnetcore/pull/41573) it was discovered that `DisableRuntimeMarshalling` will be needed for cases that don't seem to require that level of impact.

A small repo demonstrating the issue is below. I don't think this should require `DisableRuntimeMarshalling` if we can confirm the marshalling of `Foo` would be the same behavior (i.e., blittable).

```csharp
using System;
using System.Runtime.InteropServices;

namespace Demo
{
    internal struct Foo
    {
        public short A;
        public short B;
    }

    internal static partial class NativeExportsNE
    {
        public const string NativeExportsNE_Binary = "Microsoft.Interop.Tests." + nameof(NativeExportsNE);

        [LibraryImport(NativeExportsNE_Binary)]
        public static partial void PassFoo(Foo a);
    }

    internal static class Program
    {
        public static void Main(string[] args)
        {
            Foo a = default;
            NativeExportsNE.PassFoo(a);
        }
    }
}
```

**Comment by elinor-fung** [comment]
For reference, https://github.com/dotnet/runtime/commit/7d9a4d9154bcaa8928df2db480213e264cc30cba is the change from before we did `DisableRuntimeMarshalling` that had allowed marshalling of internal blittable structs.
