### ISSUE TITLE
Assertion failed 'unreached' in '<ToString_TestData>d__71:MoveNext():bool:this' during 'Do value numbering' (IL size 6679; hash 0x288e6df7; Tier1)

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69047]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1759044&view=results
Leg: Libraries Test Run checked coreclr Linux_musl x64 Release
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5e336d55e08940948e/System.Runtime.Tests/1/console.80904107.log?helixlogtype=result

```scala
Assert failure(PID 26 [0x0000001a], Thread: 100 [0x0064]): Assertion failed 'unreached' in '<ToString_TestData>d__71:MoveNext():bool:this' during 'Do value numbering' (IL size 6679; hash 0x288e6df7; Tier1)

    File: /__w/1/s/src/coreclr/jit/valuenum.cpp Line: 1905
    Image: /root/helix/work/correlation/dotnet
```

This only failed on Alpine, although that may tiering related.

cc @SingleAccretion

**Comment by jakobbotsch** [comment]
There is an unfortunate mismatch between PR validation and rolling validation: on PRs we build libraries tests in debug while in rolling validation we build them in release. I'm not sure why we have this mismatch, two failures made it into main last week because of it. cc @agocke, maybe something we need to reconsider?

**Comment by jakobbotsch** [comment]
I was able to repro this issue on ubuntu 20.04 and record a SPMI collection. I've attached the failing context, collected on 5ecaae992806a2d422157a095a63efb467365f54.

[repro.zip](https://github.com/dotnet/runtime/files/8650715/repro.zip)

**Comment by jakobbotsch** [comment]
This does not seem to repro with MSVC. It also does not repro under `COMPlus_JitDump`.

**Comment by ViktorHofer** [comment]
The mismatch in configurations is intentional as we don't have enough resources to test all configurations on PR runs. With the mixed matrix we make sure that all configurations are tested.

**Comment by jakobbotsch** [comment]
The problem is in `VNForBitCast` here:
https://github.com/dotnet/runtime/blob/f8fa9f6d1554e8db291187dd7b2847162703381e/src/coreclr/jit/valuenum.cpp#L9627

`srcVNFunc` might not be valid here (`GetVNFunc` above could have failed). So the failure happens only if this happens to match `VNF_ZeroObj`.

@SingleAccretion do you want to submit the fix?

**Comment by SingleAccretion** [comment]
@jakobbotsch thank you for diagnosing this! Yes, will submit a fix shortly.

**Comment by jakobbotsch** [comment]
> The mismatch in configurations is intentional as we don't have enough resources to test all configurations on PR runs. With the mixed matrix we make sure that all configurations are tested.

I wonder if we should reconsider this. Running the JIT over all libraries tests in debug vs in release is a _very_ significant difference. Achieving our goal of 95% pass rate seems difficult if we intentionally have large discrepancies like this.

What do you think about getting the checked coreclr x debug tests coverage as part of weekly runs instead of in PRs? Then for PRs with coreclr changes we would instead run checked coreclr x release tests, the same as rolling builds.

**Comment by jkotas** [comment]
For PRs, we want to maximize coverage variety while minimizing costs.

We have checked CoreCLR + Debug libraries tests for many platforms in the PR mix, but no checked CoreCLR + Release libraries tests. I think we should change checked CoreCLR + Debug libraries for subset of platforms to checked CoreCLR + Release libraries to increase the variety.

**Comment by bartonjs** [comment]
When a PR fails a test, the debug callstacks and the `Debug.Assert`s are useful in helping track it down... so I believe that debug libraries builds in PRs that change libraries is the priority.

> Running the JIT over all libraries tests in debug vs in release is a very significant difference. Achieving our goal of 95% pass rate seems difficult if we intentionally have large discrepancies like this.

Is it? I feel like .NET developers expect that JIT and R2R make functionally equivalent outputs.  Changes in the CLR might invalidate that, so checked CLR + runtime libraries is an interesting bucket for PRs that have changes to those areas (or, if that's hard, "for PRs that change either CoreCLR or the mono runtime")

**Comment by danmoseley** [comment]
PR's today seem to include 3 variations for Linux coreclr x64:
```
Libraries Test Run release coreclr Linux_musl x64 Debug
Libraries Test Run release coreclr Linux x64 Debug
Libraries Test Run checked coreclr Linux x64 Debug
```

The last one could change to checked/release -- would we lose important coverage?

**Comment by jkotas** [comment]
I always look at the whole matrix. We still have `checked coreclr Linux_musl x64 Debug`. `Linux` and `Linux_musl` are very similar. So I do not think we would lose any significant coverage by switching `checked coreclr Linux x64 Debug` to `checked coreclr Linux x64 Release`
