### ISSUE TITLE
JIT: Why increment so slow with others operations?

### ISSUE THREAD

**Issue by MBurtsev** [dotnet/runtime#69055]
Hi there.
While working on a project, I ran into an unexpected problem. The code began to work much slower than the similar one. Trying to understand what was the matter, I found out that the line of code with the field increment causes a performance drop of 10 times. I have given a short example below. I have prepared a code that demonstrates the problem [here](https://github.com/MBurtsev/JitSlowmo). I ask for advice on how to solve this. And I also want to draw attention to the possible need to improve the JIT compiler. 

### Source
```c#
        // 2300ms
        public void Write0(T value)
        {
            var channel = _channel;
            var operation = channel.WriterOperation;
            
            channel.WriterOperation++;

            var data = channel.Storage[operation % DATA_CAPACITY];
            var seg = data.Writer;

            seg.WriterMessages[seg.WriterPosition] = value;
        }

        // 240ms
        public void Write1(T value)
        {
            var channel = _channel;
            var operation = channel.WriterOperation;

            //channel.WriterOperation++;

            var data = channel.Storage[operation % DATA_CAPACITY];
            var seg = data.Writer;

            seg.WriterMessages[seg.WriterPosition] = value;
        }

        // 170ms   (170+240=2300?)
        public void Write2(T value)
        {
            var channel = _channel;

            channel.WriterOperation++;
        }
```

### Configuration
win10 x64 .net6

**Comment by Kuinox** [comment]
Hi, I'm a noob in JITs/perf but:  
- The performance vary a lot between runs, I suggest to use [BenchmarkDotnNet](https://github.com/dotnet/BenchmarkDotNet) to do such microbenchmarking, I'm purely speculating, but the JIT maybe didn't made any optimisation there.  
- When calling Write1/Write2 in the same loop i has the same performance than Write0
- Even by running in Debug mode I have lower execution time than the one you gave, did you run the program in Release mode ?

**Comment by MBurtsev** [comment]
Yes I run it without debugger in release build.

**Comment by Wraith2** [comment]
Without being able to compile the code and see what the compiler generates we would have to guess. Can you provide an example which compiles? as @Kuinox mentioned a BDN benchmark is usually a good way to do this.

**Comment by Kuinox** [comment]
My first thought was a cache issue but as I said I'm really new to performance stuff.
@MichalPetryka could you try a benchmark of Write1 + Write2 and also the code ? :D

**Comment by MichalPetryka** [comment]
Having 2 calls results in exact same time as Write0 but a bit more code:
## .NET 6.0.1 (6.0.121.56705), X64 RyuJIT
```assembly
; ConsoleApp32.Benchmark.Write12()
       sub       rsp,28
       mov       rax,[rcx+8]
       mov       edx,[rcx+10]
       mov       rax,[rax+8]
       mov       rcx,rax
       mov       r8d,[rcx+10]
       mov       r9d,r8d
       mov       rcx,[rcx+8]
       mov       r10d,r9d
       sar       r10d,1F
       and       r10d,3FF
       add       r10d,r9d
       and       r10d,0FFFFFC00
       sub       r9d,r10d
       cmp       r9d,[rcx+8]
       jae       short M00_L00
       movsxd    r9,r9d
       mov       rcx,[rcx+r9*8+10]
       mov       rcx,[rcx+18]
       mov       r9,[rcx+10]
       mov       ecx,[rcx+164]
       cmp       ecx,[r9+8]
       jae       short M00_L00
       movsxd    rcx,ecx
       mov       [r9+rcx*4+10],edx
       inc       r8d
       mov       [rax+10],r8d
       add       rsp,28
       ret
M00_L00:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 116
```

**Comment by MichalPetryka** [comment]
`[DisassemblyDiagnoser]` attribute in Benchmark.Net.

**Comment by MBurtsev** [comment]
Another result from AMD:

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1645 (21H2)
AMD Ryzen 9 4900H with Radeon Graphics, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.202
  [Host]    : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
  MediumRun : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT

Job=MediumRun  InvocationCount=1  IterationCount=5
LaunchCount=1  UnrollFactor=1  WarmupCount=3

| Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s | Code Size |
|------- |---------:|----------:|----------:|---------:|---------:|--------------:|----------:|
| Write0 | 7.472 ns | 0.0995 ns | 0.0154 ns | 7.452 ns | 7.487 ns | 133,841,408.7 |     128 B |
| Write1 | 1.835 ns | 0.1076 ns | 0.0167 ns | 1.816 ns | 1.856 ns | 544,981,773.8 |     118 B |
| Write2 | 1.597 ns | 0.0193 ns | 0.0050 ns | 1.594 ns | 1.604 ns | 625,983,968.6 |      26 B |

## .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
```assembly
; Benchmark.WriteBench.Write0()
       sub       rsp,28
       xor       eax,eax
       mov       rdx,[rcx+8]
M00_L00:
       mov       rcx,rdx
       mov       rcx,[rcx+8]
       mov       r8d,[rcx+10]
       mov       r9d,r8d
       inc       r8d
       mov       [rcx+10],r8d
       mov       rcx,[rcx+8]
       mov       r8d,r9d
       sar       r8d,1F
       and       r8d,3FF
       add       r8d,r9d
       and       r8d,0FFFFFC00
       sub       r9d,r8d
       cmp       r9d,[rcx+8]
       jae       short M00_L01
       movsxd    r8,r9d
       mov       rcx,[rcx+r8*8+10]
       mov       rcx,[rcx+18]
       mov       r8,[rcx+10]
       mov       ecx,[rcx+164]
       cmp       ecx,[r8+8]
       jae       short M00_L01
       movsxd    rcx,ecx
       mov       dword ptr [r8+rcx*4+10],1
       inc       eax
       cmp       eax,5F5E100
       jl        short M00_L00
       add       rsp,28
       ret
M00_L01:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 128
```

## .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
```assembly
; Benchmark.WriteBench.Write1()
       sub       rsp,28
       xor       eax,eax
       mov       rdx,[rcx+8]
M00_L00:
       mov       rcx,rdx
       mov       rcx,[rcx+8]
       mov       r8d,[rcx+10]
       mov       rcx,[rcx+8]
       mov       r9d,r8d
       sar       r9d,1F
       and       r9d,3FF
       add       r9d,r8d
       and       r9d,0FFFFFC00
       sub       r8d,r9d
       cmp       r8d,[rcx+8]
       jae       short M00_L01
       movsxd    r8,r8d
       mov       rcx,[rcx+r8*8+10]
       mov       rcx,[rcx+18]
       mov       r8,[rcx+10]
       mov       ecx,[rcx+164]
       cmp       ecx,[r8+8]
       jae       short M00_L01
       movsxd    rcx,ecx
       mov       dword ptr [r8+rcx*4+10],1
       inc       eax
       cmp       eax,5F5E100
       jl        short M00_L00
       add       rsp,28
       ret
M00_L01:
       call      CORINFO_HELP_RNGCHKFAIL
       int       3
; Total bytes of code 118
```

## .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
```assembly
; Benchmark.WriteBench.Write2()
       xor       eax,eax
       mov       rdx,[rcx+8]
M00_L00:
       mov       rcx,rdx
       mov       rcx,[rcx+8]
       inc       dword ptr [rcx+10]
       inc       eax
       cmp       eax,5F5E100
       jl        short M00_L00
       ret
; Total bytes of code 26
```

**Comment by MBurtsev** [comment]
@jakobbotsch 
>  channel.WriterOperation = channel.WriterOperation + 1
It's only improved a little. It was 45M became 46M.

**Comment by ShuiRuTian** [comment]
@MBurtsev Sorry for asking, how do you run the benchmark test?
I clone the repo https://github.com/MBurtsev/JitSlowmo. Then `cd {repoRoot}/Benchmark`, then run `dotnet run -c Release`.
It gives me a report like this:
```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
Intel Core i9-10900X CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK=7.0.100-preview.2.22153.17
  [Host]    : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
  MediumRun : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT

Job=MediumRun  InvocationCount=1  IterationCount=5  
LaunchCount=1  UnrollFactor=1  WarmupCount=3  

| Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s |
|------- |---------:|----------:|----------:|---------:|---------:|--------------:|
| Write0 | 3.213 ns | 0.2021 ns | 0.0313 ns | 3.180 ns | 3.253 ns | 311,206,450.9 |
| Write1 | 1.847 ns | 0.0995 ns | 0.0154 ns | 1.824 ns | 1.857 ns | 541,558,010.9 |
| Write2 | 1.222 ns | 0.0167 ns | 0.0043 ns | 1.218 ns | 1.229 ns | 818,104,053.7 |
```
It seems reasonable.

And, I am not pretty sure and I know this is a pretty simple case, but it feels like some padding(_emptyXX) is not useful. I guess this is for cacheline, then multi-thread will always read/write differnt variables in different cache-line, so there will not be expensive sync between different CPUs. 
However, will the same channel change such variables frequently at the same time by multi-CPUs? `ReaderPosition` and `WriterPosition` do deserve padding, but it feels a bit of strange to change the array pointer `WriterMessages` and `ReaderMessages`, so maybe you could put them together to save one padding. And if so, it would be better to mark them as `readonly` to express intension.

**Comment by Kuinox** [comment]
> It seems reasonable.

I think it's CPU dependent, I got these: 
```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1645 (21H2)
Intel Core i9-8950HK CPU 2.90GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.300-preview.22204.3
  [Host]    : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT
  MediumRun : .NET 6.0.4 (6.0.422.16404), X64 RyuJIT

Job=MediumRun  InvocationCount=1  IterationCount=5
LaunchCount=1  UnrollFactor=1  WarmupCount=3

| Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s |
|------- |---------:|----------:|----------:|---------:|---------:|--------------:|
| Write0 | 8.934 ns | 2.6918 ns | 0.6991 ns | 8.228 ns | 9.978 ns | 111,934,962.4 |
| Write1 | 2.886 ns | 1.2987 ns | 0.3373 ns | 2.475 ns | 3.271 ns | 346,496,096.3 |
| Write2 | 1.503 ns | 0.2511 ns | 0.0652 ns | 1.430 ns | 1.584 ns | 665,343,387.4 |
```
Which is an intel CPU laptop, @MBurtsev has similar result on an AMD CPU laptop, and even worse results on an intel server CPU.  

I still think it's a cache issue as I initially said, @ShuiRuTian have 4x bigger L2 and doesn't have any issue. 
Removing the paddings show that the problem suddendly disapear: 
```
| Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s |
|------- |---------:|----------:|----------:|---------:|---------:|--------------:|
| Write0 | 4.349 ns | 0.9842 ns | 0.2556 ns | 4.002 ns | 4.634 ns | 229,934,205.2 |
| Write1 | 2.343 ns | 0.3326 ns | 0.0864 ns | 2.247 ns | 2.429 ns | 426,748,820.9 |
| Write2 | 1.525 ns | 0.2500 ns | 0.0649 ns | 1.461 ns | 1.600 ns | 655,805,908.7 |
```

**Comment by MBurtsev** [comment]
@Kuinox 
> Removing the paddings show that the problem suddendly disapear:
The problem is still here 229 and 426 x2 diff

>> have 4x bigger L2 and doesn't have any issue.
The difference between 311 and 541 is also x2.  I believe that increment one of quick instruction and cannot give such result. But you are right paddings show that issue get worse. But this only shows that the CPU is additionally accessing memory.

**Comment by ShuiRuTian** [comment]
@Kuinox Sorry for the late response, and could you do me a favor? 

Let's use some distinguished tool to analytics: PerfView and VTune
(I know such tools in here: https://github.com/dotnet/performance/blob/main/docs/profiling-workflow-dotnet-runtime.md)

As it said, I suggest to use perfView with benchmarkdot.Net first: 
https://benchmarkdotnet.org/articles/configs/diagnosers.html
https://adamsitnik.com/ETW-Profiler/ (this page is mentioned in diagnosers of benchmark.Net, just in case you miss it)

If it does not give a reason, then we have to use VTune as dotnet/perforamnce doc says.

**Comment by MBurtsev** [comment]
@ShuiRuTian 
> how do you run the benchmark test?

I just run from VS, there is a 'start without debugger' button and with release config.

>However, will the same channel change such variables frequently at the same time by multi-CPUs?

The code that I have shown here is specially truncated so as not to overload this problem example.  Only one field channel.WriterOperation will be changed by threads. But other fields will be read by threads. This causes to thread friction on the data bus. You can play this:

```C#
    public class Test
    {
        private int _step  = 1;
        private long _empty00;
        private long _empty01;
        private long _empty02;
        private long _empty03;
        private long _empty04;
        private long _empty05;
        private long _empty06;
        private long _empty07;
        private int _value = 0;
        private long _empty08;
        private long _empty09;
        private long _empty10;
        private long _empty11;
        private long _empty12;
        private long _empty13;
        private long _empty14;
        private long _empty15;

        public void Begin()
        {
            var threads = 4;
            var ready   = 0;
            var count   = 100_000_000;
            var sw      = Stopwatch.StartNew();

            for (var n = 0; n < threads; n++)
            {
                Task.Factory.StartNew(() =>
                {
                    Interlocked.Add(ref ready, 1);

                    while (Volatile.Read(ref ready) < threads)
                    {
                    }

                    var start = sw.ElapsedMilliseconds;

                    for (int i = 0; i < count; i++)
                    {
                        Interlocked.Add(ref _value, _step);

                        // another case
                        //var step = Volatile.Read(ref _value);
                        //Interlocked.Add(ref _value, step);
                    }

                    Console.WriteLine($"Count:{_value}, time:{sw.ElapsedMilliseconds - start}, thread:{Thread.CurrentThread.ManagedThreadId}");

                }, CancellationToken.None, TaskCreationOptions.LongRunning, TaskScheduler.Default);
            }
        }
    }
```
With empty spaces
```
Count:394122884, time:5442, thread:7
Count:394690729, time:5450, thread:5
Count:397753748, time:5492, thread:6
Count:400000000, time:5504, thread:4
```
Without
```
Count:396432892, time:6236, thread:4
Count:398170638, time:6263, thread:6
Count:399278501, time:6281, thread:7
Count:400000000, time:6284, thread:5
```
In real tasks, the difference will be even greater. Because you have many fields and obj references what will be read at the same time.

**Comment by MBurtsev** [comment]
I plan to port this code to C++ CLI mixed with unmanaged to get a performance comparison.

**Comment by MBurtsev** [comment]
Guys I have new result.

| Method |     Mean |     Error |    StdDev |      Min |      Max |          Op/s | Code Size |
|------- |---------:|----------:|----------:|---------:|---------:|--------------:|----------:|
| Write0 | 4.382 ns | 0.0218 ns | 0.0034 ns | 4.381 ns | 4.388 ns | 228,182,540.3 |     169 B |
| Write1 | 2.708 ns | 0.1127 ns | 0.0174 ns | 2.682 ns | 2.718 ns | 369,281,161.9 |     116 B |
| Write2 | 1.403 ns | 0.0156 ns | 0.0024 ns | 1.401 ns | 1.407 ns | 712,574,263.6 |      70 B |

I can't believe my eyes. After failing with C++/CLI, I wanted to forget about it... All I did was change it to a struct. `private /*sealed class*/ struct ChannelData` These things drive me crazy. I still don't understand why structs are better in this case. Hope this thread was interesting for you.

**Comment by ShuiRuTian** [comment]
@MBurtsev If you only change that line, then I guess the reason is the code is able to reuse cache after the change :)
``` cs
        public void Write0(T value)
        {
            // _channel is struct now, so copy everything by value
            var channel = _channel;
           // read from copied value
            var operation = channel.WriterOperation;
            // the copied value is updated, not _channel.WriterOperation
            channel.WriterOperation++;
            // so operation is always 0, the cache works
            var data = channel.Storage[operation % DATA_CAPACITY];
            var seg = data.Writer;

            seg.WriterMessages[seg.WriterPosition] = value;
        }
```

**Comment by MBurtsev** [comment]
Yes you are right. Yesterday I was in vain delighted before going to bed :). It doesn't seem to have a solution.
