### ISSUE TITLE
Revisit NonBacktracking's avoiding of findOptimizations.LeadingAnchor

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#69060]
Today the Regex non-backtracking implementation uses the same RegexFindOptimizations instance as does the interpreter, gaining most of the same "quickly move to the next location to start a match" optimizations.  But it explicitly ignores the optimizations when it has a leading anchor:
https://github.com/dotnet/runtime/blob/be20c44826bc55d201c406f4ac007d24ed7a9137/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Symbolic/SymbolicRegexMatcher.cs#L194
That's because the DFA/NFA itself has knowledge of the anchors.  But this misses out on various vectorized operations, such as quickly jumping to the next line if there's a beginning-of-line anchor.  We should revisit this to see whether there are ways to better utilize all of the same find optimizations as the other engines.

cc: @olsaarik

**Comment by olsaarik** [comment]
I'm guessing that limitation should just be removed. At least it shouldn't be a problem, as `NonBacktracking` sets the new initial state according to the new character context after `RegexFindOptimizations` has jumped ahead. The vectorized search for matching anchor locations would probably be very helpful for some patterns.

**Comment by stephentoub** [comment]
I'll try removing it and report back.
