### ISSUE TITLE
[QUIC] Don't use GetParam to get stream ID

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#69070]
The operation is expensive on both client (5.0% incl time in HttpClient benchmark) and server (3.7% incl time) -- it seems msquic is waiting on the lock inside

- for client, it should be possible to get stream ID from stream start event
- for server, I believe the data is not available ATM, but I think it might be possible to extend a stream accept event (PEER_STREAM_STARTED.StreamId = PEER_STREAM_STARTED.Stream->Id) -- thoughts @nibanks?

**Comment by nibanks** [comment]
Yes, you might want to cache this locally at your first availability. You can query it anytime after the stream has been started. The stream is considered already started once indicated in the peer_stream_started event. Either get it from a callback, or query it immediately in the callback for the best performance. Querying anything on your own thread always leads to it being queued to the QUIC worker.
