### ISSUE TITLE
`Func<T>.MakeGenericType(typeof(ReadOnlySpan<char>))` throws `ArgumentException` in 7.0.100-preview.4 while the exception was `TypeLoadException` in prior versions

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#69084]
### Description

`Func<T>.MakeGenericType(typeof(ReadOnlySpan<char>))` (or calling `MakeGenericType` with any other byref-like value types) throws `ArgumentException` in 7.0.100-preview.4 while the exception was `TypeLoadException` in prior versions.

It turns out the `ArgumentException` wraps a `TypeLoadException` in its inner exception property.

### Reproduction Steps

In PowerShell with 7.0.100-preview.4:
```
PS:> try { [Func`1].MakeGenericType([System.ReadOnlySpan[char]]) } catch { $a = $_ }
PS:> $a.Exception.InnerException.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     ArgumentException                        System.SystemException
```

In PowerShell with .NET 6 and prior 7-preview versions
```
PS:> try { [Func`1].MakeGenericType([System.ReadOnlySpan[char]]) } catch { $a = $_ }
PS:> $a.Exception.InnerException.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     TypeLoadException                        System.SystemException
```

### Expected behavior

Throw `TypeLoadException` as in the prior versions.

### Actual behavior

Throw `ArgumentException` in 7.preview-4
Not sure if this is an intentional change, or a real regression.

### Regression?

Yes

### Known Workarounds

We can work around by catch all exceptions.

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT Likely related to (https://github.com/dotnet/runtime/pull/67783

**Comment by AaronRobinsonMSFT** [comment]
@daxian-dbw In my mind this is by-design. I agree it is a breaking change, but it is because we are adding a new type of generic constraint check. In this case that is support for generics to be ByRefLike, the link provided in https://github.com/dotnet/runtime/issues/69084#issuecomment-1121701054 is the PR introducing runtime support.

@jkotas The error is technically correct because the argument is violating the new constraint we added. The new check for this violation is at

https://github.com/dotnet/runtime/blob/6d2340542176acce320a932084febaed4fd9da5b/src/coreclr/vm/typedesc.cpp#L1526-L1527

which then is translated in 

https://github.com/dotnet/runtime/blob/6d2340542176acce320a932084febaed4fd9da5b/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs#L1991-L1996

Adding @davidwrighton for thoughts too.

**Comment by davidwrighton** [comment]
I never like changing existing error behavior, its bound to break somebody, but given the new feature, changing how this errors out isn't unreasonable. @daxian-dbw could you explain your scenario in more detail? I'd like to know more about why your code calls the api with these arguments. I don't like suggesting catching all exceptions as a good mitigation, but that may be reasonable in your codebase.

**Comment by daxian-dbw** [comment]
See the code here: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/MshMemberInfo.cs#L2694

It creates a `Func<...>` type for every .NET method overload processed by PowerShell, to support directly passing `[M]::DoubleStrLen` to the `[func[string, int]]` parameter in the below script example.
```pwsh
class M {
    static [int] DoubleStrLen([string] $value) { return 2 * $value.Length }
    
    static [long] AggregateString([string[]] $values, [func[string, int]] $selector) {
        [long] $res = 0
        foreach($s in $values){
            $res += $selector.Invoke($s)
        }
        return $res
    }        
}

[M]::AggregateString((gci).Name, [M]::DoubleStrLen)
```

I think in our use case, it's safe to change to `catch (Exception)` because we indeed want to return `typeof(Func<PSNonBindableType>)`, which indicates this overload cannot be converted to any `Func<...>` type, in case the creation the `Func` delegate type fails.

**Comment by AaronRobinsonMSFT** [comment]
@daxian-dbw Thanks for explaining your use case. Based on the statement above it sounds like you accept this as a valid change in behavior. I would agree in that we are expanding support so we can provide more precise failure details. In this case ByRefLike types are supported in generics - at least from the runtime perspective.

As far as the PowerShell code, It might be more appropriate to separate the two cases, `TypeLoadException` and a failure to satisfy a Generic constraint (i.e., `ArgumentException`).

I'm going to close this as by-design for now, please let us know if you have a concern about the resolution.

**Comment by daxian-dbw** [comment]
> In this case ByRefLike types are supported in generics - at least from the runtime perspective.

@AaronRobinsonMSFT Does this mean `ByRefLike` types will be generally supported to be used as generic arguments? In that case, why would an `ArgumentExcpetion` be thrown in case of calling `MakeGenericType` with a `ByRefLike` type?

The following script attempts to create `Span<Span<char>>`, with the 7.100-preview.4

```
PS:16> try { [System.Span`1].MakeGenericType([System.Span[char]]) } catch { $a = $_ }
PS:17> $a.Exception.InnerException.InnerException

Message        : GenericArguments[0], 'System.Span`1[System.Char]', on 'System.Span`1[T]' violates the constraint of
                 type parameter 'T'.
TypeName       :
TargetSite     : Void Instantiate(System.Runtime.CompilerServices.QCallTypeHandle, IntPtr*, Int32,
                 System.Runtime.CompilerServices.ObjectHandleOnStack)
Data           : {}
InnerException :
HelpLink       :
Source         : System.Private.CoreLib
HResult        : -2146233054
StackTrace     :    at System.RuntimeTypeHandle.Instantiate(QCallTypeHandle handle, IntPtr* pInst, Int32
                 numGenericArgs, ObjectHandleOnStack type)
                    at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

**Comment by AaronRobinsonMSFT** [comment]
> Does this mean ByRefLike types will be generally supported to be used as generic arguments?

Yes, but it can only be achieved via IL at present. The C# language team is [working through support](https://github.com/dotnet/csharplang/pull/5689), but that will likely come in post C# 11.

> In that case, why would an ArgumentExcpetion be thrown in case of calling MakeGenericType with a ByRefLike type?

Because `Span<>` hasn't been updated to say it supports that feature because there is no way to express that in C# yet. Once that support is added to the language this particular case would work.

**Comment by daxian-dbw** [comment]
@AaronRobinsonMSFT Thanks for the clarification! That helps 😄
