### ISSUE TITLE
Improve gRPC support on mobile platforms

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#69095]
In .NET 7 we would like to better support the .NET gRPC client on iOS and Android so that MAUI apps can take advantage.

- [x] Bring up [gRPC interop tests](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md)
- [x] AOT and trim gRPC client.  Identify and fix any issues
- [x] Identify and fix any issues with the interop tests
- [x] Support calling gRPC servers with self-signed certs
- [x] Performance test gRPC client on all mobile platforms

**Comment by steveisok** [comment]
@simonrozsival @akoeplinger In the past, we've dismissed shipping any custom java class as part of the Android runtime pack.  Should we reconsider in order to support self-signed certs with SocketsHttpHandler?

**Comment by JamesNK** [comment]
Related issue: https://github.com/dotnet/runtime/issues/69464

**Comment by simonrozsival** [comment]
I found a problem with full AOT on Android that has alread been solved on Apple platforms: #55736, #55947

**Comment by janseris** [comment]
@steveisok
This issue surprises me. 
Why is it not possible to use a gRPC client in MAUI now with .NET 6? 
gRPC client is a part of .NET 6. It seemed to me like what can .NET 6 do, can MAUI do as well.
Is there any official list of features from .NET 6 which are not platform specific but MAUI cannot use it? I didn't think MAUI could not use gRPC client on Android.

**Comment by steveisok** [comment]
The title is correct.  I'll change the description to include "better support".

**Comment by simonrozsival** [comment]
There have been several improvements to the gRPC support on Android in .NET 7 (bugfix #69507 which enables AOT compilation on Android, CI setup in #73060) but we still need more time to finish this issue (especially the iOS part) and there's not enough time to finish it in time for .NET 7. I'm moving further improvements (mostly infrastructure related) to .NET 8.

**Comment by simonrozsival** [comment]
@janseris the gRPC Client is an independent NuGet package (https://www.nuget.org/packages/Grpc.Net.Client). It already works with .NET 6 on Android and iOS. In .NET 7, ahead of time compilation on Android will be fixed. We'll also run the interop tests on Android emulators. In .NET 8 we'll further improve our CI infrastructure to ensure the gRPC client works correctly on Android and iOS devices.

**Comment by ComptonAlvaro** [comment]
When I start to try gRPC with MAUI and .NET I had hope to can use the same client library for all kind of clients, MAUI, WPF and so on.

But but the moment, I am having problems with self signed certificates. I can make it work in windows applications, but if I try to use MAUI / Android, I get an error:

```
"HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: Authentication failed, see inner exception. SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown."
```

When I knew that MAUI will use .NET 6 I thought I could use the same libraries in all my projects, but I but the moment I can't finde the way to do.

If it could be improve this aspect, it would be very nice.

**Comment by janseris** [comment]
@ComptonAlvaro MAUI has this type of problems when connecting to SQL Server as well. It probably has something to do with underlying SSL provider or implementation. There have been also problems with WebSocket etc.
https://github.com/dotnet/SqlClient/issues/1662
https://github.com/dotnet/SqlClient/issues/1656

https://github.com/dotnet/maui/issues/9400
