### ISSUE TITLE
AnalyzerReference vs ProjectReference

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#69111]
For a library to include analyzers in its package, `AnalyzerReference` items must be defined. In contrast to that, for a library to consume an analyzer, [a `ProjectReference` item with some metadata needs to be defined](https://github.com/dotnet/runtime/blob/faa59aec0178cacf8f104b30151cfd60d4c903a3/eng/generators.targets#L62-L65).

The Regex source generator is currently enabled in projects by setting a property which then just enables the ProjectReference with the metadata in the generators.targets file. We could avoid this indirection by supporting an `AnalyzerReference` item to also consume an analyzer and not just package it.

I think a good default behavior for the `AnalyzerReference` item would be:
```xml
<ProjectReference Include="..."
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false" />
```

and by explicitly setting the Pack metadata on the AnalyzerReference item (`<AnalyzerReference Include="..." Pack="true" />`) it would be added to the package.

@ericstj what do you think about this?
cc @joperezr and @eerhardt for opinions

**Comment by ViktorHofer** [comment]
cc @joperezr and @eerhardt for opinions

**Comment by ViktorHofer** [comment]
I added the proposed change to my existing PR that already touches analyzers: https://github.com/dotnet/runtime/pull/69069/commits/c959f5f98360da8e82361e0d1b3d32a75df6dbe7.

**Comment by ericstj** [comment]
It's a different thing to package vs consume an analyzer.  Projects which package an analyzer may not want to reference it.  I agree that `AnalyzerReference` is a good name, and the most common thing that folks would want to do with it is reference and not pack it.  Perhaps we should also have some combination of metadata to represent the pack and not reference case.

**Comment by ViktorHofer** [comment]
That was my gut feeling as well. I think the default behavior for `AnalyzerReference` should be to consume an analyzer and by setting `Pack=true` + another metadata like `SkipConsumption=true` you can package it without consuming it.
