### ISSUE TITLE
Libraries linker tests aren't running in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#69139]
While working on https://github.com/dotnet/runtime/pull/69118 I noticed that library linker tests aren't running in CI at all. The step successfully terminates after the projects are restored but not executed.

Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=1757179&view=logs&j=eb951b81-6f9f-5627-0593-6e7e925eb8a5&t=55619121-b736-513e-b9cc-23d0fc111be3.

I'm investigating this right now locally.

cc @joperezr @dotnet/area-infrastructure-libraries

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/69118's second commit should fix that tests weren't running. Let's see how many failures creeped in since the last time they were running. I will post a more complete fix and a thorough investigation when I have more time.

**Comment by eerhardt** [comment]
@ViktorHofer - do we know why/how/when these tests got turned off? Any checks we can put in place to block this from happening again in the future?
