### ISSUE TITLE
[Analyzer Proposal]: Analyzer/fixer for converting Stream.Read calls to ReadAtLeast and ReadExactly

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#69159]
With the addition of the new Stream `ReadAtLeast` and `ReadExactly` methods, there is a pattern of mistakes we can catch with an analyzer and suggest the caller use the new APIs. For example:

```C#
stream.Read(buffer, 0, buffer.Length);
```
where the return value isn't checked, and recommend it be changed to a call to `ReadExactly`.

Or cases where the return value is checked but required to be the same as what was requested:
```C#
if (stream.Read(buffer, 0, buffer.Length) != buffer.Length) throw ...;
```
and similarly suggest it use `ReadExactly`.

If the caller is using a length that is different than the length of the buffer being passed in, and not checking the return value, we can suggest to use `ReadAtLeast`:

```C#
stream.Read(buffer, 0, count);
```

would become:

```C#
stream.ReadAtLeast(buffer, count);
```

However, note in the `ReadAtLeast` case, the caller should still be checking the return value because the `ReadAtLeast` call could be returning more than `count` bytes, and this data would be missed if the caller only consumed `count` bytes from `buffer`.

One problem with this analyzer might be when we implement #34098. If the caller saw the "Do not discard results of methods marked as `DoNotIgnoreReturnValue`" warning first and addressed it, they would lose out on this fixer.

cc @stephentoub

**Comment by weltkante** [comment]
> One problem with this analyzer might be when we implement https://github.com/dotnet/runtime/issues/34098. If the caller saw the "Do not discard results of methods marked as DoNotIgnoreReturnValue" warning first and addressed it, they would lose out on this fixer.

I don't think these conflict, as the methods aren't pure (changing state of the stream) and won't be marked as such?

**Comment by stephentoub** [comment]
The intent had been that this be addressed in .NET 7.  It unfortunately got pushed out due to lack of time.  We should tackle it soon.

**Comment by eerhardt** [comment]
Note that another analyzer that would help in this case is https://github.com/dotnet/runtime/issues/34098. Code that doesn't capture the result of `Stream.Read` or `BinaryReader.Read` would get flagged by that analyzer as well (along with other APIs that shouldn't have their results ignored).

**Comment by buyaa-n** [comment]
Estimates:

 - Analyzer: Medium
 - Fixer: Medium

**Comment by bartonjs** [comment]
Looks good as proposed.

The diagnostic (possibly with a different diagnostic ID) should still fire on older TFMs to report that the call made to Read is unreliable as written.

Category: Reliability
Severity: Warning

**Comment by mpidash** [comment]
I would like to be assigned to this one, please.

**Comment by stephentoub** [comment]
> I would like to be assigned to this one, please.

Terrific. Done. Thanks!

**Comment by mpidash** [comment]
What is the reason for suggesting to call `ReadAtLeast` instead of `ReadExactly` when the length is different from the buffer size?
Is it due to the difference in how the end of the stream is handled in `ReadAtLeast` (but wouldn't this also apply to the first case)?

**Comment by stephentoub** [comment]
> What is the reason for suggesting to call `ReadAtLeast` instead of `ReadExactly` when the length is different from the buffer size? Is it due to the difference in how the end of the stream is handled in `ReadAtLeast` (but wouldn't this also apply to the first case)?

I'm actually not sure now... @eerhardt, do you remember what you had in mind there?

**Comment by mpidash** [comment]
@stephentoub I think the initial post is based on a [comment](https://github.com/dotnet/runtime/issues/16598#issuecomment-1118997064) from you when discussing the implementation of `ReadExactly`/`ReadAtLeast`.

One of the reasons why I am following up on the second code fix is because I am not sure how we can enforce the following:

> However, note in the `ReadAtLeast` case, the caller should still be checking the return value because the `ReadAtLeast` call could be returning more than `count` bytes, and this data would be missed if the caller only consumed `count` bytes from `buffer`.

The code is still unreliable (in a different way) if we just change the call to `ReadAtLeast`. We could generate something like `var bytesRead = stream.ReadAtLeast(buffer, count);` to encourage the user to use the return value.

**Comment by weltkante** [comment]
in fact, if I read this right, if you change from Read to ReadAtLeast you may introduce additional bugs because now you can overwrite data past the original count being passed in? it might be best to always suggest ReadExactly when the return value isn't checked in the first place?

**Comment by eerhardt** [comment]
Thinking about this now, I think ReadExactly is the only correct suggestion here. It's the only method you can call without checking the return value, as it is the only method that ensures you got exactly `count` bytes. When calling `ReadAtLeast`, you still need to check the return value in case of EOS (when throwOnEndOfStream = false), or when more data is read than `minimumBytes`.

**Comment by mpidash** [comment]
Thank you all for helping to clarify 😃.
