### ISSUE TITLE
[API Proposal]: Expose `DefaultInterpolatedStringHandler.Text` property

### ISSUE THREAD

**Issue by kamronbatman** [dotnet/runtime#69168]
### Background and motivation

Looking to take a string interpolation and write it directly a SpanWriter byte buffer without intermediate strings. Currently using `DefaultInterpolatedStringHandler` requires calling `ToStringAndClear()`, however in this situation, the intermediate string isn't needed.

### API Proposal

Proposing to expose the `Text` property in `DefaultInterpolatedStringHandler`

```csharp
namespace System.Runtime.CompilerServices;

public ref struct DefaultInterpolatedStringHandler
{
    /// <summary>Gets a span of the written characters thus far.</summary>
    public ReadOnlySpan<char> Text => _chars.Slice(0, _pos);
}
```

### API Usage

In this example, `SpanWriter` is a ref struct Span\<byte\> writer used for high performance, zero-allocation writing

```csharp
public static class SpanWriterExtensions
{
    public static void WriteAscii(
        this ref SpanWriter spanWriter,
        ref DefaultInterpolatedStringHandler handler)
    {
        spanWriter.Write(handler.Text, Encoding.ASCII);
        handler.Clear();
    }
}
```

...

```csharp
var value = 100;
using var writer = new SpanWriter(stackalloc byte[1024]);
writer.WriteAscii($"Some Information {value} to write");
```

### Alternative Designs

Alternative is for the user to copy `DefaultInterpolatedStringHandler`. The downside of this approach is specifically in the `AppendLiteral` function, where there are internals to the implementation of `String` that the user does not have access to, effectively _reducing_ the efficiency of the interpolator when 99% of the functionality is exactly the same.
See these lines:
https://github.com/dotnet/runtime/blob/b4f46ac6737b8606bd7ad9bd0fcfc422a6f93fa2/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/DefaultInterpolatedStringHandler.cs#L170-L180

### Risks

I do not see any right now.

**Comment by stephentoub** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/55390

**Comment by kamronbatman** [comment]
I think for my purposes, if the implementation was changed to use a LinkList of buffers, I could easily use that as well. I understand that it would be a breaking change to the shape of the public API.

To account for that we could build the linklist of buffers shape now and just return a single link. Furthermore, implement the IDisposable pattern and change the codegen to dispose the handler so we don't need to expose `Clear()`
Unfortunately this is too disruptive for `DefaultInterpolatedStringHandler`.

Would there be appetite to entertain adding a check for `Dispose()` to the codegen and disposing the handler if it is disposable?

**Comment by Sergio0694** [comment]
> "if the implementation was changed to use a LinkList of buffers"

That would also likely cause a non negligible performance loss compared to the current implementation.

> "implement the IDisposable pattern and change the codegen to dispose the handler"

I assume you just meant to expose a `Dispose` method (given the handler is a `ref struct`, so it can't implement `IDisposable`). Nevertheless, that doesn't seem doable for two reasons. First is: it would cause the buffer to be returned to the pool even if an exception was thrown while interpolating, which is not adviseable (it's a potential security risk). Second, adding a `try/finally` block makes it harder/impossible for the JIT to perform some optimizations, so this would also likely cause a performance loss when using the handler, even in cases where no exceptions are actually thrown.

When talking with Stephen and other folks about a similar proposal in the past (see #55390), it seemed clear there was no intention of exposing these two APIs, and this proposal is essentially the same as the other one, like Stephen mentioned too. I don't really see anything different that would lead to a different outcome for this if it was brought to API review again.

To be clear: I do feel the current situation is far from ideal, and I did raise some of your same concerns as well. I'm just saying the result of those conversations were pretty adamant that this was just not the way to go. At this point I suspect the correct approach would be to wait for C# 12 to expose `unscoped` semantics, tie that with proper handling of some kind of `unique`-ness (either via language syntax or some analyzer), and expose a safe to use interpolated handler that way (à la `ValueStringBuilder`).

**Comment by kamronbatman** [comment]
I am all for a better way to chain one handler to another so you can pass down buffers to ultimately be written to a stream without allocation. For now I copied the implementation like others did and exposed the raw buffer to be passed to another interpolated string handler.
