### ISSUE TITLE
WASM AOT compilation runs indefinitely and consumes all system memory with LanguageExt.Core

### ISSUE THREAD

**Issue by Jack-Edwards** [dotnet/runtime#69166]
### Description

I am attempting to publish a Blazor WASM application with AOT compilation enabled.  The step following the message `AOT'ing ## assemblies` will run indefinitely whenever the nuget package `LanguageExt.Core` is installed.  Opening up Task Manager will reveal all available system memory (25 GB in my case) is being consumed by Visual Studio.  In some cases, Task Manager will also report Disk Usage of 200+ MB/s.

### Reproduction Steps

1. Create a new Blazor WASM project using .NET 6.0.
2. Add the nuget package `LanguageExt.Core` v4.1.0.  You do not need to reference this project in any source files - just add the nuget.
3. Publish the project with AOT compilation enabled.
4. Observe, all available memory is consumed and the publish seems to run indefinitely.

### Expected behavior

The publish should succeed or fail.  The publish should consume a reasonable amount of memory.

### Actual behavior

The publish appears to run indefinitely and consumes a crazy amount of system resources.

### Regression?

I have used AOT compilation before in several projects.  The issue only began to occur after incorporating this specific nuget package.

### Configuration

.NET SDK 6.0.300 (x64)
Visual Studio 2022 (64-bit) v17.2.0
Windows 10 Pro, v21H1, build 19043.1645

**Comment by radical** [comment]
`mono-aot-cross` is taking lot of time for `LanguageExt.Core.dll`, taking ~13G of resident memory.

cc @vargaz

**Comment by vargaz** [comment]
The input assembly has about 70k methods, makes heavy uses of generics and valuetypes, so the AOT compiler tries to generate too many generic instances, running out of memory.

I'd suggest not trying to use this assembly with wasm+aot, or wasm at all. Even if this problem is fixed, build speeds are still going to be very slow and the resulting app will going to be very large.

**Comment by radical** [comment]
Please re-open if I closed this incorrectly.
