### ISSUE TITLE
[API Proposal]: Awaitable Interfaces (implementing `GetAwaiter()`)

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#69183]
### Background and motivation

I would generally like to see an interface for the `GetAwaiter` method.

For example, for an interop case I have developed a separate Task which implements the interface `IAsyncResult` and communicates with a printer and gets whether a print job is already finished, .....

However, `IAsyncResult` does not specify the GetAwaiter() method. 

### API Proposal

```csharp
namespace System {
    public interface IAwaitable<TAwaiter> : IAsyncResult where T : IAwaiter {
        public TAwaiter GetAwaiter();
    }
}

namespace System.Runtime.CompilerServices {
    public interface IAwaiter : ICriticalNotifyCompletion {
        public bool IsCompleted { get; }
        public void OnCompleted(Action continuation);
        public void UnsafeOnCompleted(Action continuation);
    }
}
```

### Alternative Designs

Alternative is adding `GetAwaiter` to `IAsyncResult`.

### Risks

Since this is a new interface there is no risk.
The alternative I suggested would involve breaking changes.

**Comment by teo-tsirpanis** [comment]
First, `IAsyncResult` is a legacy interface and should not be used in new APIs. Second, each awaitable type returns its own type of awaiter; only `Task.GetAwaiter()` returns `TaskAwaiter`; value tasks return `ValueTaskAwaiter`s, and these awaiters are generic if they have a result.

We could make `IAwaitable` generic and add a new `IAwaiter` interface, but I don't find much utility to it. It's not common to support both tasks and value tasks at the same time; developers usually stick to only one of them.

**Comment by teo-tsirpanis** [comment]
We need it; `ICriticalNotifyCompletion` does not have `IsCompleted`.

**Comment by deeprobin** [comment]
> We need it; `ICriticalNotifyCompletion` does not have `IsCompleted`.

You're right. I personally find these interfaces quite useful. 
But let's collect some other opinions.

**Comment by stephentoub** [comment]
We've talked about adding interfaces here and there was never enough benefit, and certainly if we did, IAsyncResult wouldn't be involved.

>  I personally find these interfaces quite useful.

You will need to elaborate much more and with compelling examples. The proposal doesn't work as suggested, so I'm not clear on how you've found them to be useful.

**Comment by deeprobin** [comment]
@stephentoub 
I have written myself a Custom Awaiter and accordingly also a Custom "Task" with a GetAwaiter() method.

I was wondering why there is no interface for this.
In my case there are 2 Custom Awaiter.

Then I created an interface which returns an IAsyncResult.
Of course I could create such an interface myself, but in my opinion it is also semantically better to outsource "common" things like GetAwaiter() into an interface.

In my tests I had no possibility to test my interface via IAsyncResult using await.

For this I just use a workaround which is not really nice:
```cs
        var printer = new VirtualMockPrinter();
        var connection = await printer.ConnectAsync();
        var printResult = await connection.PrintAsync(new PrintRequest(null!));
//     --- ^^^^^^^ Implements IAsyncResult
        // Task finishes when physical Paper was printed
        // IAsyncResult does not define GetAwaiter()
        // Workaround using dynamic
        dynamic dynamicPrintResult = printResult;
        await dynamicPrintResult;
```


---

Even if my case is probably more of a niche case that can of course be circumvented in other ways, I think these interfaces are useful just to make the code more semantic.

**Comment by stephentoub** [comment]
> I have written myself a Custom Awaiter

Why?  If you need something that's awaitable to represent some other operation, why not use `TaskCompletionSource` to create a task you manually complete?

> Then I created an interface

Why?  In what situation are you needing to abstract over different awaitables produced by an arbitrary producer?

>  which returns an IAsyncResult

No new code should be implementing IAsyncResult.

**Comment by teo-tsirpanis** [comment]
Can't you make `connection.PrintAsync` return a `Task`? If you have inherited a code base that performs async with `IAsyncResult` and pairs of `Begin`/`End` methods (also known as APM), [there are some methods to help you move to `Task`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.fromasync).

**Comment by davidfowl** [comment]
I can' think of a good reason to do this. Why not just use ValueTask, IValueTaskSource and ManualValueTaskSource instead?

**Comment by deeprobin** [comment]
> Can't you make `connection.PrintAsync` return a `Task`? If you have inherited a code base that performs async with `IAsyncResult` and pairs of `Begin`/`End` methods (also known as APM), [there are some methods to help you move to `Task`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.fromasync).

Oh yes, thanks.

Thank you for your feedback. If there is interest in the future to create an interface for this to gain semantic advantage, feel free to reopen this issue.
