### ISSUE TITLE
Backport PR failures in github action

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#69196]
![image](https://user-images.githubusercontent.com/7412651/167906044-0422c405-0a8b-4fb6-b4ce-162977451bc9.png)

@am11 wondering, in case of a network disconnect can we let this silently fail so that it doesn't create noise?

Alternatively or additionally, should we add retries?

**Comment by ViktorHofer** [comment]
Cool and makes perfect sense to me. It's under the 7.0.0 milestone so I will look at the issue again, latest in fall when we aggressively triage our 7.0 issues :)

**Comment by am11** [comment]
The old records accumulated in 2 years were deleted. These days the cleanup step only operates on records accumulated in 24 hrs.  (300-400 on a busy day). If it fails (depending on GH server load), the records are cleaned up on the following day, but we don't have the huge backlog as before.
