### ISSUE TITLE
superpmi-diffs and superpmi-replay are running when jiteeversionguid.h changes

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#69197]
As in https://github.com/dotnet/runtime/pull/68677, the various `superpmi-diffs` and `superpmi-replay` jobs are still executing when `jiteeversionguid.h` is changed.

The job is meant to be setup such that this won't happen, but it's apparently not configured correctly today: https://github.com/dotnet/runtime/pull/68677#issuecomment-1124001177

**Comment by BruceForstall** [comment]
Since this is minor, I'm pushing it to 8.0.0.
