### ISSUE TITLE
TaskCanceledException in msbuild while building on OSX-x64

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69190]
Pipeline: https://dev.azure.com/dnceng/public/_build/results?buildId=1764261&view=logs&j=1f8f000c-1adc-5434-677a-95dd9e006aba
Log: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1764261/logs/187

```scala
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-preview.3.22179.4/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/Users/runner/work/1/s/artifacts/log/Checked/ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:__ToolsetLocationOutputFile=/Users/runner/work/1/s/artifacts/toolset/7.0.0-beta.22255.2.txt /t:__WriteToolsetLocation /warnaserror /Users/runner/work/1/s/artifacts/toolset/restore.proj
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error : System.AggregateException: One or more errors occurred. (A task was canceled.)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.<>c__DisplayClass3_0.<ResolveSdk>b__2()
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at System.Lazy`1.CreateValue()
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.BackEnd.SdkResolution.CachingSdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
/Users/runner/work/1/s/artifacts/toolset/restore.proj : error :    at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
```

I hit this in #69180 as well ([log](https://dev.azure.com/dnceng/public/_build/results?buildId=1764831&view=logs&jobId=1f8f000c-1adc-5434-677a-95dd9e006aba&j=1f8f000c-1adc-5434-677a-95dd9e006aba&t=2945a4f3-4f84-5b54-c962-533fbace1ff1)].

Binlog: [ToolsetRestore.zip](https://github.com/dotnet/runtime/files/8671399/ToolsetRestore.zip)

@rainersigwald any idea what this could be?

```json
{ 
    "ErrorMessage":"at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult" 
}
```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1827271](https://dev.azure.com/dnceng/public/_build/results?buildId=1827271)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1827271/logs/20)
|[1820085](https://dev.azure.com/dnceng/public/_build/results?buildId=1820085)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1820085/logs/930)
|[1820032](https://dev.azure.com/dnceng/public/_build/results?buildId=1820032)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1820032/logs/1149)
|[1820577](https://dev.azure.com/dnceng/public/_build/results?buildId=1820577)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1820577/logs/160)
|[1821074](https://dev.azure.com/dnceng/public/_build/results?buildId=1821074)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821074/logs/985)
|[1821605](https://dev.azure.com/dnceng/public/_build/results?buildId=1821605)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821605/logs/23)
|[1821600](https://dev.azure.com/dnceng/public/_build/results?buildId=1821600)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821600/logs/226)
|[1821562](https://dev.azure.com/dnceng/public/_build/results?buildId=1821562)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821562/logs/619)
|[1821616](https://dev.azure.com/dnceng/public/_build/results?buildId=1821616)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821616/logs/1347)
|[1822383](https://dev.azure.com/dnceng/public/_build/results?buildId=1822383)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822383/logs/25)
|[1822192](https://dev.azure.com/dnceng/public/_build/results?buildId=1822192)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822192/logs/1315)
|[1822308](https://dev.azure.com/dnceng/public/_build/results?buildId=1822308)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822308/logs/340)
|[1822365](https://dev.azure.com/dnceng/public/_build/results?buildId=1822365)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822365/logs/163)
|[1822196](https://dev.azure.com/dnceng/public/_build/results?buildId=1822196)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822196/logs/1278)
|[1822310](https://dev.azure.com/dnceng/public/_build/results?buildId=1822310)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822310/logs/486)
|[1822932](https://dev.azure.com/dnceng/public/_build/results?buildId=1822932)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1822932/logs/250)
|[1821879](https://dev.azure.com/dnceng/public/_build/results?buildId=1821879)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1821879/logs/910)
|[1823221](https://dev.azure.com/dnceng/public/_build/results?buildId=1823221)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1823221/logs/532)
|[1823854](https://dev.azure.com/dnceng/public/_build/results?buildId=1823854)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1823854/logs/1583)
|[1824411](https://dev.azure.com/dnceng/public/_build/results?buildId=1824411)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1824411/logs/1299)
|[1825319](https://dev.azure.com/dnceng/public/_build/results?buildId=1825319)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1825319/logs/517)
|[1824903](https://dev.azure.com/dnceng/public/_build/results?buildId=1824903)|dotnet/runtime|Restore blob feed tasks (Windows)|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1824903/logs/455)
|[1825815](https://dev.azure.com/dnceng/public/_build/results?buildId=1825815)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1825815/logs/371)
|[1825938](https://dev.azure.com/dnceng/public/_build/results?buildId=1825938)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1825938/logs/189)
|[1826197](https://dev.azure.com/dnceng/public/_build/results?buildId=1826197)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1826197/logs/224)
|[1826884](https://dev.azure.com/dnceng/public/_build/results?buildId=1826884)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1826884/logs/85)
|[1826971](https://dev.azure.com/dnceng/public/_build/results?buildId=1826971)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1826971/logs/97)
|[1783262](https://dev.azure.com/dnceng/public/_build/results?buildId=1783262)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1783262/logs/268)
|[1781810](https://dev.azure.com/dnceng/public/_build/results?buildId=1781810)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1781810/logs/202)
|1779412|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779412/logs/174)
|1779219|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779219/logs/1798)
|1777497|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777497/logs/1191)
|1777677|dotnet/runtime|Generate AOT offsets|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777677/logs/245)
|1777469|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777469/logs/483)
|1777014|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777014/logs/364)
|1777589|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777589/logs/277)
|1777615|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777615/logs/325)
|1777648|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777648/logs/204)
|1777845|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1777845/logs/237)
|1779101|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779101/logs/28)
|1779138|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779138/logs/167)
|1779807|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779807/logs/131)
|1779730|dotnet/runtime|Generate AOT offsets|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1779730/logs/181)
|[1780676](https://dev.azure.com/dnceng/public/_build/results?buildId=1780676)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1780676/logs/348)
|[1781646](https://dev.azure.com/dnceng/public/_build/results?buildId=1781646)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1781646/logs/178)
|[1818438](https://dev.azure.com/dnceng/public/_build/results?buildId=1818438)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1818438/logs/54)
|[1818251](https://dev.azure.com/dnceng/public/_build/results?buildId=1818251)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1818251/logs/157)
|[1814750](https://dev.azure.com/dnceng/public/_build/results?buildId=1814750)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1814750/logs/205)
|[1812402](https://dev.azure.com/dnceng/public/_build/results?buildId=1812402)|dotnet/runtime|Prepare TestHost with runtime Mono|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1812402/logs/1296)
|[1810652](https://dev.azure.com/dnceng/public/_build/results?buildId=1810652)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1810652/logs/113)
|[1810184](https://dev.azure.com/dnceng/public/_build/results?buildId=1810184)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1810184/logs/215)
|[1809389](https://dev.azure.com/dnceng/public/_build/results?buildId=1809389)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1809389/logs/359)
|[1808062](https://dev.azure.com/dnceng/public/_build/results?buildId=1808062)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1808062/logs/1759)
|[1808917](https://dev.azure.com/dnceng/public/_build/results?buildId=1808917)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1808917/logs/222)
|[1811848](https://dev.azure.com/dnceng/public/_build/results?buildId=1811848)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1811848/logs/146)
|[1812109](https://dev.azure.com/dnceng/public/_build/results?buildId=1812109)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1812109/logs/221)
|[1812424](https://dev.azure.com/dnceng/public/_build/results?buildId=1812424)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1812424/logs/114)
|[1812579](https://dev.azure.com/dnceng/public/_build/results?buildId=1812579)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1812579/logs/197)
|[1812857](https://dev.azure.com/dnceng/public/_build/results?buildId=1812857)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1812857/logs/151)
|[1814339](https://dev.azure.com/dnceng/public/_build/results?buildId=1814339)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1814339/logs/92)
|[1814515](https://dev.azure.com/dnceng/public/_build/results?buildId=1814515)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1814515/logs/309)
|[1814857](https://dev.azure.com/dnceng/public/_build/results?buildId=1814857)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1814857/logs/1810)
|[1815062](https://dev.azure.com/dnceng/public/_build/results?buildId=1815062)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1815062/logs/154)
|[1815071](https://dev.azure.com/dnceng/public/_build/results?buildId=1815071)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1815071/logs/167)
|[1816080](https://dev.azure.com/dnceng/public/_build/results?buildId=1816080)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1816080/logs/77)
|[1817169](https://dev.azure.com/dnceng/public/_build/results?buildId=1817169)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1817169/logs/1171)
|[1817345](https://dev.azure.com/dnceng/public/_build/results?buildId=1817345)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1817345/logs/85)
|[1817617](https://dev.azure.com/dnceng/public/_build/results?buildId=1817617)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1817617/logs/253)
|[1806666](https://dev.azure.com/dnceng/public/_build/results?buildId=1806666)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1806666/logs/1787)
|[1805214](https://dev.azure.com/dnceng/public/_build/results?buildId=1805214)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1805214/logs/194)
|[1803431](https://dev.azure.com/dnceng/public/_build/results?buildId=1803431)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1803431/logs/200)
|[1801769](https://dev.azure.com/dnceng/public/_build/results?buildId=1801769)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1801769/logs/22)
|[1798670](https://dev.azure.com/dnceng/public/_build/results?buildId=1798670)|dotnet/runtime|Build CoreHost|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1798670/logs/686)
|[1797464](https://dev.azure.com/dnceng/public/_build/results?buildId=1797464)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1797464/logs/226)
|[1796182](https://dev.azure.com/dnceng/public/_build/results?buildId=1796182)|dotnet/runtime|Build CoreHost|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1796182/logs/1484)
|[1796730](https://dev.azure.com/dnceng/public/_build/results?buildId=1796730)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1796730/logs/113)
|[1796716](https://dev.azure.com/dnceng/public/_build/results?buildId=1796716)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1796716/logs/53)
|[1796713](https://dev.azure.com/dnceng/public/_build/results?buildId=1796713)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1796713/logs/1619)
|[1798210](https://dev.azure.com/dnceng/public/_build/results?buildId=1798210)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1798210/logs/1550)
|[1798636](https://dev.azure.com/dnceng/public/_build/results?buildId=1798636)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1798636/logs/144)
|[1799893](https://dev.azure.com/dnceng/public/_build/results?buildId=1799893)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1799893/logs/163)
|[1801469](https://dev.azure.com/dnceng/public/_build/results?buildId=1801469)|dotnet/runtime|Build CoreHost|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1801469/logs/1318)
|[1801768](https://dev.azure.com/dnceng/public/_build/results?buildId=1801768)|dotnet/runtime|Build CoreHost|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1801768/logs/1243)
|[1801951](https://dev.azure.com/dnceng/public/_build/results?buildId=1801951)|dotnet/runtime|Generate AOT offsets|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1801951/logs/200)
|[1801896](https://dev.azure.com/dnceng/public/_build/results?buildId=1801896)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1801896/logs/182)
|[1802758](https://dev.azure.com/dnceng/public/_build/results?buildId=1802758)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802758/logs/24)
|[1802459](https://dev.azure.com/dnceng/public/_build/results?buildId=1802459)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802459/logs/423)
|[1802562](https://dev.azure.com/dnceng/public/_build/results?buildId=1802562)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802562/logs/1683)
|[1802578](https://dev.azure.com/dnceng/public/_build/results?buildId=1802578)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802578/logs/1513)
|[1802701](https://dev.azure.com/dnceng/public/_build/results?buildId=1802701)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802701/logs/218)
|[1802984](https://dev.azure.com/dnceng/public/_build/results?buildId=1802984)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1802984/logs/894)
|[1803018](https://dev.azure.com/dnceng/public/_build/results?buildId=1803018)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1803018/logs/201)
|[1803167](https://dev.azure.com/dnceng/public/_build/results?buildId=1803167)|dotnet/runtime|Restore and Build Product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1803167/logs/238)
|[1803407](https://dev.azure.com/dnceng/public/_build/results?buildId=1803407)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1803407/logs/202)
|[1804328](https://dev.azure.com/dnceng/public/_build/results?buildId=1804328)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1804328/logs/108)
|[1806698](https://dev.azure.com/dnceng/public/_build/results?buildId=1806698)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1806698/logs/288)
|[1806708](https://dev.azure.com/dnceng/public/_build/results?buildId=1806708)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1806708/logs/23)
|[1792541](https://dev.azure.com/dnceng/public/_build/results?buildId=1792541)|dotnet/runtime|Build and generate native prerequisites|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1792541/logs/878)
|[1790340](https://dev.azure.com/dnceng/public/_build/results?buildId=1790340)|dotnet/runtime|Prepare TestHost with runtime CoreCLR|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1790340/logs/2229)
|[1788726](https://dev.azure.com/dnceng/public/_build/results?buildId=1788726)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1788726/logs/1169)
Displaying 100 of 124 results
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|32|124|

**Comment by rainersigwald** [comment]
@jeffkl Seen this apparent NuGet SDK resolver cancellation?

**Comment by jeffkl** [comment]
@rainersigwald I haven't seen that before.  This part of the code hasn't changed in a long time.  Since its run in a constructor, it can't really use async tasks and doesn't pass around a cancellation token.  I wonder if the auth provider is involved and is timing out?  Does this build use authenticated feeds?

**Comment by jeffkl** [comment]
Okay so no auth, this code path still does a lot of work restoring a package by connecting to the feed to get the versions, downloading the package, and unzipping it.  I suppose it could be an intermittent issue with the feed.

What is the impact of this?  Is it happening a lot?

I've been working on major improvements to the NuGet SDK resolver and adding logging which will help diagnosability.

https://github.com/NuGet/Home/issues/11441

**Comment by jeffkl** [comment]
@jakobbotsch sounds good, very sorry for the failure.  Please keep me in the loop if you keep seeing it.  I'll continue working on improving the resolver in the meantime!

**Comment by jakobbotsch** [comment]
Another instance in https://dev.azure.com/dnceng/public/_build/results?buildId=1765596&view=results in Build iOS arm64 Release AllSubsets_Mono

**Comment by CarnaViire** [comment]
This might be related to/fixed by https://github.com/NuGet/NuGet.Client/pull/4596 but maybe it's hit in some other code path as well? (But from BCL point of view, that was also patched in https://github.com/dotnet/runtime/pull/68649)

**Comment by ViktorHofer** [comment]
> https://github.com/dotnet/sdk/pull/25449

Which will happen in 2-3 weeks as part of the next infrastructure rollout :)

**Comment by danmoseley** [comment]
@ViktorHofer when is the infrastructure rollout that would bring the fix above?

**Comment by ViktorHofer** [comment]
cc @agocke who is driving the SDK upgrade this month. Andy, everything should be ready by now, right? We would need to send out a mail to the runtimerepo alias and open a GH issue and pin it, for internal and external communication.

**Comment by agocke** [comment]
Finishing up testing now: https://github.com/dotnet/runtime/pull/70117

When that's done we can send the email out, pin the issue, and merge.

**Comment by agocke** [comment]
Preview 5 SDK update has been merged
