### ISSUE TITLE
There may be unexpectedly high delays in `ReaderWriterLockSlim` operations

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#69206]
When the spin-lock used by `ReaderWriterLockSlim` internally is contended, the spin-lock falls back to [Thread.Sleep(1)](https://github.com/dotnet/runtime/blob/478b1b43c89f0f1fa3b2c94d7b444f7a8325d401/src/libraries/System.Private.CoreLib/src/System/Threading/ReaderWriterLockSlim.cs#L1575) after some spin-waiting. The `Sleep(1)`s can delay the operation for some or many milliseconds depending on how much contention there is.

Repro:

```c#
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

static class Program
{
    private static void Main(string[] args)
    {
        var rwLock = new ReaderWriterLockSlim();
        Action enterExit = () =>
        {
            var sw = Stopwatch.StartNew();
            rwLock.EnterReadLock();
            rwLock.ExitReadLock();
            double elapsedMs = sw.Elapsed.TotalMilliseconds;
            if (elapsedMs >= 0.5)
            {
                Console.WriteLine($"{elapsedMs,6:0.0} ms");
            }
        };

        var tasks = new Task[100];
        while (true)
        {
            for (int i = 0; i < 100; ++i)
            {
                tasks[i] = Task.Run(enterExit);
            }

            Task.WaitAll(tasks);
        }
    }
}
```

Sample output:

```
   0.9 ms
   1.0 ms
   0.8 ms
   0.7 ms
   1.0 ms
  15.0 ms
  15.0 ms
  15.1 ms
  15.1 ms
  15.1 ms
  15.1 ms
  15.1 ms
  30.6 ms
  30.6 ms
  30.6 ms
  46.4 ms
  14.3 ms
   0.5 ms
   0.5 ms
```

**Comment by Clockwork-Muse** [comment]
> depending on how much contention there is

More relevant, depending on the scheduling frequency.  ~15m/s is the normal timer resolution/frequency on Windows and a bunch of other OSes.  There are ways to get faster ones, but they require additional setup, and in any case the point of a spin-lock is for things that are barely contested; if a spin-lock actually needs to wait, the longer duration is probably worth it.
