### ISSUE TITLE
System.Text.Json using interpolated string with JsonSerializable.TypeInfoPropertyName fails with ArgumentException

### ISSUE THREAD

**Issue by JakeYallop** [dotnet/runtime#69207]
### Description

The `TypeInfoPropertyName` property on the `JsonSerializableAttribute` is used to provide a unique name for a serializable class in case of naming conflicts.

Using an interpolated string (prefixed with `$`, now possible due to [constant interpolated strings](https://github.com/dotnet/csharplang/issues/2951)) for this property causes the generator to fail ungracefully with an `ArgumentException`.

I discovered this issue as I wanted to use `nameof` and then add a suffix to resolve a naming conflict.

### Reproduction Steps

```csharp
public class MyClass {}

[JsonSerializable(typeof(MyClass), TypeInfoPropertyName = $"{nameof(MyClass)}SomeUniqueSuffix")]
public partial class Context : JsonSerializerContext { }
```

The following variants also do not function as expected:
```csharp
public class MyClass {}

//generates a type info property called "nameof"
[JsonSerializable(typeof(MyClass), TypeInfoPropertyName = nameof(MyClass) + "SomeUniqueSuffix")] 

//generates a type info property called "A"
[JsonSerializable(typeof(MyClass), TypeInfoPropertyName = "A" + "Suffix")]

public partial class Context : JsonSerializerContext { }
```

### Expected behavior

Generator correctly parses the interpolated string, or fails gracefully with a diagnostic.

### Actual behavior

```
warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Context.$".g.cs' contains an invalid character '$' at position 8.
```

### Regression?

No

### Known Workarounds

Ensure a single string is used as the property value.

### Configuration

.NET Version: 6.0
System.Text.Json version: 7.0.0-preview.4.22229.4

**Comment by layomia** [comment]
FYI @maryamariyan @joperezr for other source generators.

**Comment by joperezr** [comment]
cc: @stephentoub as well. I don't think this particular problem affects the Regex source generator since we have a static file name for the generated source produced by the generator, but it would be good to add tests for interpolation and concatenation on patterns in the attribute to make sure we handle that correctly. Same goes for the analyzer that I'm working for, making sure we handle concatenation correctly.

**Comment by JakeYallop** [comment]
A slight variation on the issue above - what would we expect the following to generate?
```csharp
public class Test {}
public static class Constants
{
    public const string TypeInfoName = "MyCustomName";
};

[JsonSerializable(typeof(Test), TypeInfoPropertyName = $"{Constants.TypeInfoName}" )]
public partial class Context : JsonSerializerContext { }
```
