### ISSUE TITLE
System.ComponentModel.ICustomTypeDescriptor.GetConverter have incorrect nullable annotation

### ISSUE THREAD

**Issue by jl0pd** [dotnet/runtime#69229]
Interface `System.ComponentModel.ICustomTypeDescriptor` have nullable annotations, but method `GetConverter` is wrongly annotated to return non-null value, while [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.icustomtypedescriptor.getconverter) says it could return `null`:

```
Returns
A TypeConverter that is the converter for this object, or null if there is no TypeConverter for this object
```

I propose to mark return value as nullable. It will be breaking change, but people would get `NullReferenceException` anyway if they wont check for `null`

**Comment by eerhardt** [comment]
@krwq - can you remember a reason why this was annotated this way in https://github.com/dotnet/runtime/pull/54961?

Looking through the code, I see some conflicting things:

1. The following places look like they don't accept `null`:

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L3239-L3240

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L3549-L3551

2. These places seem to think returning `null` is acceptable:

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L2901-L2904

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Data.Common/src/System/Data/Common/DbDataRecord.cs#L80

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Data.Common/src/System/Data/Common/DataRecordInternal.cs#L321-L324

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Data.Common/src/System/Data/DataRowView.cs#L237

**Comment by eerhardt** [comment]
Since this is an interface that is implemented by external code, we should annotate it to be in-line with the documentation. The documentation indicates that `null` can be returned, so the API should be updated accordingly.

**Comment by krwq** [comment]
This is probably incorrect - I suspect all internal implementations have returned non-null and I was looking only at the XML docs which was missing `null` remark (xml docs says only `Gets a type converter for this object.`). @jl0pd are you interested in making a PR with the fix?
