### ISSUE TITLE
Does the LibraryImportGenerator work for csharp projects only or any?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#69233]
The LibraryImportGenerator is currently placed directly under the the `analyzers/dotnet` folder in the microsoft.netcore.app.ref targeting pack. I wonder if this is intentional or if the analyzer should just work for csharp projects like the Regex and the System.Text.Json source generator:

```
 Directory of C:\git\runtime5\artifacts\bin\microsoft.netcore.app.ref\analyzers\dotnet

05/02/2022  03:47 PM    <DIR>          .
04/28/2022  05:02 PM    <DIR>          ..
05/02/2022  03:47 PM    <DIR>          cs
05/02/2022  03:47 PM    <DIR>          de
05/02/2022  03:47 PM    <DIR>          es
05/02/2022  03:47 PM    <DIR>          fr
05/02/2022  03:47 PM    <DIR>          it
05/02/2022  03:47 PM    <DIR>          ja
05/02/2022  03:47 PM    <DIR>          ko
05/04/2022  06:22 PM           208,896 Microsoft.Interop.LibraryImportGenerator.dll
05/04/2022  06:22 PM            45,808 Microsoft.Interop.LibraryImportGenerator.pdb
05/04/2022  06:22 PM           178,176 Microsoft.Interop.SourceGeneration.dll
05/04/2022  06:22 PM            51,292 Microsoft.Interop.SourceGeneration.pdb
```

https://github.com/dotnet/runtime/blob/35e47797a36e29475d28af61f0fa0fb3bf067838/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/LibraryImportGenerator.csproj#L38 indicates that its csharp only. If that's the case, the project must specify the `AnalyzerLanguage` property: https://github.com/dotnet/runtime/blob/35e47797a36e29475d28af61f0fa0fb3bf067838/src/libraries/System.Text.RegularExpressions/gen/System.Text.RegularExpressions.Generator.csproj#L14

@jkoritzinsky @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
@ViktorHofer Thanks for letting me know about this requirement. The source generator only targets C# so it sounds like this recommendation is appropriate.

**Comment by jkoritzinsky** [comment]
The analyzer/fixer validates usage of the custom type marshalling model. This analyzer ensures that developers who author custom type marshallers use the correct shapes for the types whether they're authoring them in C# or VB, so when someone uses the marshaller type in source-generated marshalling in a C# project, we've already validated the shape.

**Comment by AaronRobinsonMSFT** [comment]
> This analyzer ensures that developers who author custom type marshallers use the correct shapes for the types whether they're authoring them in C# or VB

Right, this is the "bit of a stretch" scenario I was referring to. I welcome @ericstj's thoughts here, but I am for limiting this to C# only and usage of assemblies authored in VB.NET requires users to really know what they are doing.

**Comment by ericstj** [comment]
I don't have a strong opinion here other than to make sure you're placing this intentionally and testing the behavior where it will apply.  I wonder if by having a single assembly that's shared between C# and VB it has any side-effects for performance or working set for the compiler?  cc @chsienki @sharwell

**Comment by ViktorHofer** [comment]
>  but I am for limiting this to C# only and usage of assemblies authored in VB.NET requires users to really know what they are doing.

Sounds like that's the direction that we are taking.
