### ISSUE TITLE
Improve Interop.Sys.ReadLink loop with stackalloc

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#69230]
In [this discussion](https://github.com/dotnet/runtime/pull/69107#discussion_r869741338), it was mentioned that the `Interop.Sys.GetCwd` method uses a loop to attempt to retrieve the path from the native syscall. This method initially creates a byte array buffer using `stackalloc`, attempts to retrieve the path from the syscall, and if there's an `ERANGE` error("not enough buffer space"), it now enters a loop in which the byte array buffer is rented with twice the space, and it keeps doubling the size until the path fits in the buffer:

https://github.com/dotnet/runtime/blob/43dd0a74ab524278620d8c6a9d33a9b73b2d2228/src/libraries/Common/src/Interop/Unix/System.Native/Interop.GetCwd.cs#L18-L45

We have another method, `Interop.Sys.ReadLink`, which has a very similar loop, but it does not have an initial `stackalloc`, and we got [the suggestion to improve it](https://github.com/dotnet/runtime/pull/69107#discussion_r870762333):

https://github.com/dotnet/runtime/blob/c2ec86b1c552ac8a1749f9f98e012f707e325660/src/libraries/Common/src/Interop/Unix/System.Native/Interop.ReadLink.cs#L31-L68

If it helps, I'm using the same technique in the interop methods that retrieve uname or gname using uid or gid. They're implemented here: https://github.com/dotnet/runtime/pull/69107

**Comment by tmds** [comment]
```
     int outputBufferSize = 1024; 
  
     // Use an initial buffer size that prevents disposing and renting 
     // a second time when calling ConvertAndTerminateString. 
     using var converter = new ValueUtf8Converter(stackalloc byte[1024]); 
```
There is already a `stackalloc byte[1024]`.
Maybe that's the reason it is renting from the `ArrayPool` instead of allocating another buffer on the stack?
