### ISSUE TITLE
Unhandled exception out of BackgroundService initialization .NET 6

### ISSUE THREAD

**Issue by Rayzbam** [dotnet/runtime#69234]
Hi,

We're encoutering an issue on our generic host in .NET 6.
We're using the (soon obsolete) library System.Drawing.Printing for printing on our different printers. We don't know how to print easily without this one for the moment to be honest, solutions available and given by Microsoft don't seem to do the job.

Sometimes it appears that some issue with the spooler can litterally crash all our app (deployed as a Windows Service).
We can't figured this out and find how to avoid a complete stop of the application.
Of course we don't understand the issue, which seem to be related to a driver issue.

I saw this change : [https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/hosting-exception-handling](url)
We don't have any log in our default ILogger when this happens, and we're not anymore in the BackgroundService StartAsync/ExecuteAsync, it's a process out of scope which is listening to a ServiceBus queue to process messages.

The error we have is this one (for information) when we call the "Print" method : 
`Faulting application name: __APPNAME__, version: 1.0.0.0, time stamp: 0x61735063
Faulting module name: TRID6UUS.DLL, version: 21.2.262.10, time stamp: 0x5e51acc4
Exception code: 0xc0000409
Fault offset: 0x00000000008a1370
Faulting process id: 0x3298
Faulting application start time: 0x01d863aed11f3878
Faulting application path: __APPPATH__
Faulting module path: C:\Windows\system32\spool\DRIVERS\x64\3\TRID6UUS.DLL
Report Id: f08ee1e1-c052-43cb-85c9-75dd0869d063
Faulting package full name:
Faulting package-relative application ID:`

This code seems to mean an "AccessViolationException".
When this happens, the application just stop unexpectedly and need a manual restart. It's a behavior we can't have on our app in Production, and understanding printer driver issue is very complicated on many cases. We're working with a lot of different printers and need to know how to handle this kind of unhandled exception to :
           - Be able to log when it happens
           - Be able to "ignore" this kind of issue if it's possible.
I know that an unhandled exceptions like this one shouldn't happen and a crash of the service is a "normal" behavior, but in this case we need to know a way to handle this.

**Comment by jkotas** [comment]
>  (soon obsolete) library System.Drawing.Printing

Note that System.Drawing.Printing is only getting obsoleted for non-Windows platform. It is still supported on Windows.

> This code seems to mean an "AccessViolationException".

The exception code 0xc0000409 typically means [stack buffer overrun](https://en.wikipedia.org/wiki/Stack_buffer_overflow). 

> - Be able to log when it happens

You may be able to write a .dll in C/C++ that sets up SetUnhandledExceptionFilter and tries to detect this situation. Exception filters are too low-level to write in C#. You have to use C/C++ for exception filters.

> Be able to "ignore" this kind of issue if it's possible.

There is no good way to ignore this kind of crash. The best you can do is to restart the process.

**Comment by Rayzbam** [comment]
> Looks like some incompatible driver?
> 
> Can you deploy a command line application with minimal printing code on your target machine?

It seems to be a driver issue. We don't need to deploy something on the target machine, we know the issue is driver issue. But we're managing a lot of printers and one printer can't stop the service and interrupt service for all other services and their printer..



> > (soon obsolete) library System.Drawing.Printing
> 
> Note that System.Drawing.Printing is only getting obsoleted for non-Windows platform. It is still supported on Windows.
> 
> > This code seems to mean an "AccessViolationException".
> 
> The exception code 0xc0000409 typically means [stack buffer overrun](https://en.wikipedia.org/wiki/Stack_buffer_overflow).
> 
> > * Be able to log when it happens
> 
> You may be able to write a .dll in C/C++ that sets up SetUnhandledExceptionFilter and tries to detect this situation. Exception filters are too low-level to write in C#. You have to use C/C++ for exception filters.
> 
> > Be able to "ignore" this kind of issue if it's possible.
> 
> There is no good way to ignore this kind of crash. The best you can do is to restart the process.

I can easily understand that. But, maybe i'm wrong, but we can't restart automatically a service, and we have to provide high availability on this service to be honest. I mean, is it possible that System.Drawing.Printing catch this error properly and rethrow it to end user ? 
Sometimes printer just upgrades and driver installed on the server which call "Print" method is not the good one anymore..

**Comment by jkotas** [comment]
> is it possible that System.Drawing.Printing catch this error properly and rethrow it to end user?

Stack buffer overrun is a security bug. I am sorry, we cannot add code that enables masking security bugs like this to .NET runtime libraries. The best thing to do for security bugs like this is to let the process crash as fast as possible.
