### ISSUE TITLE
[API Proposal]: New Method: Enum.HasAnyFlag(Enum)

### ISSUE THREAD

**Issue by TaffarelJr** [dotnet/runtime#69262]
### Background and motivation

The existing `System.Enum.HasFlag(...)` method looks for an _exact match_. From the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.enum.hasflag#remarks):

> The HasFlag method returns the result of the following Boolean expression.
> `thisInstance And flag = flag`

There are scenarios where an Enum value may have _multiple_ flags set, and we need to check if _just one specific flag_ is set among the rest. Rather than forcing the developer to remember & type `thisInstance And flag > 0` each time (ugly), I'd like to propose it be encapsulated in a new method on the `System.Enum` type.

### API Proposal

```csharp
// Pseudo-code
namespace System
{
    public struct Enum
    {
        // New method (proposed)
        public bool HasAnyFlag(Enum flags) => (thisInstance & flags) > 0;
    }
}
```

### API Usage

```csharp
using System;

// Sample Enum definition
[Flags]
public enum Pets {
   None = 0,
   Dog = 1,
   Cat = 2,
   Bird = 4,
   Rabbit = 8,
   Other = 16,
}

// I have a dog and a cat
var myPets = Pets.Dog | Pets.Cat;

// Existing method
myPets.HasFlag(Pets.Bird)           // = false
myPets.HasFlag(Pets.Dog)            // = false
myPets.HasFlag(Pets.Cat)            // = false
myPets.HasFlag(Pets.Dog | Pets.Cat) // = true

// New method (proposed)
myPets.HasAnyFlag(Pets.Bird)           // = false
myPets.HasAnyFlag(Pets.Dog)            // = true
myPets.HasAnyFlag(Pets.Cat)            // = true
myPets.HasAnyFlag(Pets.Dog | Pets.Cat) // = true
```

### Alternative Designs

Instead of a new method, this could also be implemented using a new default parameter in the existing method:

```csharp
// Pseudo-code
namespace System
{
    public struct Enum
    {
        // New default parameter (alternate proposal)
        public bool HasFlag(Enum flag, bool matchAny = false) =>
            return matchAny
                ? (thisInstance & flags) > 0
                : (thisInstance & flags) == flags
    }
}
```

If there are still more flag check algorithms that might need to be added in the future (I'm not aware of any), then perhaps an overload would be warranted - or maybe a new `EnumOptions` enum that defines the various algorithms used to check for flags.

Personally, the 'new method' approach in the main proposal seems like the best because it would allow the flexibility to add additional algorithms (as additional methods) in the future without changing existing method parameters or enum definitions. It also uses the same terminology as the LINQ `.Any()` extension method.

### Risks

None that I'm aware of. This seems like it should be a very simple new feature that doesn't affect existing functionality.

If it's implemented as a new default parameter on the existing method, I could maybe see some edge case where it might break existing code. (Maybe something that uses reflection and expects just a single parameter?) But I would hope that would be extremely rare.

**Comment by stephentoub** [comment]
> // New method (proposed)
> myPets.HasAnyFlag(Pets.Bird)           // = false
> myPets.HasAnyFlag(Pets.Dog)            // = true
> myPets.HasAnyFlag(Pets.Cat)            // = true
> myPets.HasAnyFlag(Pets.Dog | Pets.Cat) // = true

These can also be implemented as:
```C#
(myPets & Pets.Bird) != 0
(myPets & Pets.Dog) != 0
(myPets & Pets.Cat) != 0
(myPets & (Pets.Dog | Pets.Cat)) != 0
```
which is IMHO simpler, and it doesn't require any new methods.  The proposed API would also be inefficient without additional JIT work to basically convert it into what manual checks, in part to avoid the boxing.

I appreciate and understand the suggestion, but I don't think we should add this.

**Comment by TaffarelJr** [comment]
@stephentoub The same could be said of the existing `Enum.HasFlag()` method. It seems the intent of that method was to make the code a little less cryptic. Does this proposal not fall in line with that philosophy?

**Comment by stephentoub** [comment]
> The same could be said of the existing Enum.HasFlag() method

Yes.  If that didn't exist and were proposed today, I'd have the same feedback :smile:

We can't delete it at this point, but we also don't need to proliferate it.

**Comment by TaffarelJr** [comment]
Ah, it's one of those.

Well if that's the case, then I accept my fate, and will go ahead with my own extension method. 😄

**Comment by MichalPetryka** [comment]
Using `> 0` instead of `!= 0` can result in undesirable behaviour too, if you have a flag on the last bit.

**Comment by TaffarelJr** [comment]
It's precisely those kind of 'gotchas' that my proposal was intended to help with.

**Comment by madelson** [comment]
One upside to adding this is that its existence implicitly clarifies the behavior of HasFlag in the multi-flag scenario. This is something that I can recall verifying multiple times in the past and a subtlety some might overlook.

**Comment by pinkfloydx33** [comment]
FYI the examples are a little off... the outputs for the current API are incorrect. They output the same as those you suggest for the proposed API.

```csharp
// Existing method (actual) 
myPets.HasFlag(Pets.Bird)           // =  false
myPets.HasFlag(Pets.Dog)            // = true
myPets.HasFlag(Pets.Cat)            // = true
myPets.HasFlag(Pets.Dog | Pets.Cat) // = true
```
[SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQHMIDsIIJYDGqsM+wcMKANDCAnFlQCYgDUAPgAIBMADALAAoHgEYhQgG5QEAAgC2ATwAKEGMhkBeGSrUA6ACIB7dDPbbVyXQGFYAbnGCA9I5kBRAB55kMPFhNzVAAtDJiFOEQBOAApFHUsACShkADEAGyh0KLjdACE8BCYASkLbGTLy8rDImOULXUSU9Mzso3Ri+2Fq2LqGtIysupsYdqro7r1epoG9VtNzPSGRwSEAbT70ZABdMIBmGWw4OXn1AG8hcoA5QxxNGV4qc7LZrREHwXKh2+438ryC24ALD8ygAlKDAYB4GC3AAcwJkAHkYIFcLcRAA2N4AXyAA) 

Which then makes the proposed API harder to visualize. It seems like better examples *could* be something like:

```csharp 
Pets.Dog.HasAnyFlag(Pets.Dog) // true
Pets.Dog.HasAnyFlag(Pets.Cat) // false
Pets.Dog.HasAnyFlag(Pets.Cat | Pets.Dog) // true
Pets.Dog.HasAnyFlag(Pets.Cat | Pets.Bird) // false

(Pets.Dog | Pets.Cat).HasAnyFlag(Pets.Dog) // true
(Pets.Dog | Pets.Cat).HasAnyFlag(Pets.Cat) // true
(Pets.Dog | Pets.Cat).HasAnyFlag(Pets.Bird) // false
(Pets.Dog | Pets.Cat).HasAnyFlag(Pets.Cat | Pets.Dog) // true
(Pets.Dog | Pets.Cat).HasAnyFlag(Pets.Cat | Pets.Bird) // true
```

At least that's what `(x & y) != 0` would imply.

**Comment by TaffarelJr** [comment]
My apologies. In my effort to simplify the scenario from my real-life code, I simplified too much. Here's a more comprehensive test scenario:

```csharp
// Existing method          (thisInstance And flag = flag)
myPets.HasFlag(Pets.None)                        // = true

myPets.HasFlag(Pets.Dog)                         // = true
myPets.HasFlag(Pets.Cat)                         // = true
myPets.HasFlag(Pets.Bird)                        // = false

myPets.HasFlag(Pets.Dog | Pets.Cat)              // = true      Checks for all
myPets.HasFlag(Pets.Dog | Pets.Bird)             // = false     Checks for all
myPets.HasFlag(Pets.Cat | Pets.Bird)             // = false     Checks for all

myPets.HasFlag(Pets.Dog | Pets.Cat | Pets.Bird)  // = false     Checks for all


// New proposed method          (thisInstance And flag != 0)
myPets.HasAnyFlag(Pets.None)                        // = false    What does this mean?

myPets.HasAnyFlag(Pets.Dog)                         // = true
myPets.HasAnyFlag(Pets.Cat)                         // = true
myPets.HasAnyFlag(Pets.Bird)                        // = false

myPets.HasAnyFlag(Pets.Dog | Pets.Cat)              // = true     Checks for any
myPets.HasAnyFlag(Pets.Dog | Pets.Bird)             // = true     Checks for any
myPets.HasAnyFlag(Pets.Cat | Pets.Bird)             // = true     Checks for any

myPets.HasAnyFlag(Pets.Dog | Pets.Cat | Pets.Bird)  // = true     Checks for any
```

**Comment by tannergooding** [comment]
As with https://github.com/dotnet/runtime/issues/14084 this isn't a direction we'd like to move forward on.

The idiomatic bit operations are guaranteed to be efficient where-as these named methods aren't and potentially push users towards a pit of failure.
