### ISSUE TITLE
Investigate diffs from 1.1.0 CoreCLR performance runs

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#6927]
We found some diffs during the 1.1.0 performance runs that we should take a look at.  The benchmarks are: Ackermann, BlockCopyPerf, BubbleSort2, ByteMark, DelegateInvoke, EightQueens, GetField, Where00LinqMethodX, LowLevelPerf, benchFFT.  I will probably break them out as we start individual investigations, but want them written down for now.

**Comment by stephentoub** [comment]
@DrewScoggins, this has been open now for four years.  Can it be closed?

**Comment by danmosemsft** [comment]
I'm confident we're not going to look at 1.1 perf. Closing based on my earlier question 🙂
