### ISSUE TITLE
[wasm] verify template javascript files don't include signatures

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#69288]
Install the public preview4 and verify the template files are not signed.

**Comment by radical** [comment]
I downloaded preview4 from https://dotnet.microsoft.com/en-us/download/dotnet/7.0 . And installed the `wasm-tools` workload.

The wasm templates pack (`template-packs/microsoft.net.runtime.webassembly.templates.7.0.0-preview.4.22229.4.nupkg`) has `./content/templates/browser/main.js` with a big signature block on the top:

```
...
// SIG // Uh/RqZpC3ESp9TUrN28RhsVzSxAbz4FTfKGrjyKvAAc5
// SIG // 6mlzkoHs5VR1lc/ygjwSlCKorkvYV9m/
// SIG // End signature block
const createDotnetRuntime = require("./dotnet.js");

async function main() {
    const { MONO } = await createDotnetRuntime();
    const app_args = process.argv.slice(2);
    await MONO.mono_run_main_and_exit("console.dll", app_args);
};
main();
```
