### ISSUE TITLE
Test failure System.Net.Security.Tests.NTAuthenticationTests.NtlmSignatureTest on Mono on MacCatalyst

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#69309]
e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1766930&view=logs&j=df0d4348-1948-576c-9bcf-0f0eaa3c5cab&t=31227290-cdc0-5337-e5fb-9f23dc038b63

Started happening on 05/12. Suspect PR is https://github.com/dotnet/runtime/pull/65679, seems to be deterministic, but since those are mono jobs, there is no stdout to check for particulars, Test results DB shows:

```
   at System.Net.Security.Tests.NTAuthenticationTests.NtlmSignatureTest()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

CI leg: `runtime-extra-platforms`

cc: @wfurt, @filipnavara

**Comment by filipnavara** [comment]
The test needs platform exclusion for iOS, tvOS, Android and MacCatalyst just like it has for macOS.
