### ISSUE TITLE
Undefined references when linking with libnethost.a

### ISSUE THREAD

**Issue by mgaeckler1964** [dotnet/runtime#69306]
I have an application that must be linked with nethost library. Under windows everthing is OK. The application links and works as expected. Unfortunately the centos build fails. I get lots of undefined symbol errors:

> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(utils.cpp.o): In function `std::string::_M_check(unsigned long, char const*) const':
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(utils.cpp.o):/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `fx_ver_t::as_str() const':
> /root/runtime/src/native/corehost/fxr/fx_ver.cpp:73: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `fx_ver_t::prerelease_glob() const':
> /root/runtime/src/native/corehost/fxr/fx_ver.cpp:88: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `fx_ver_t::patch_glob() const':
> /root/runtime/src/native/corehost/fxr/fx_ver.cpp:95: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `parse_internal(std::string const&, fx_ver_t*, bool)':
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:(.text+0x1b50): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:(.text+0x1b68): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `std::string::_M_check(unsigned long, char const*) const':
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(fx_ver.cpp.o): In function `validIdentifiers(std::string const&)':
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:(.text+0x2135): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(pal.unix.cpp.o): In function `std::string::_M_check(unsigned long, char const*) const':
> /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
> /usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.4/runtimes/linux-x64/native/libnethost.a(pal.unix.cpp.o):/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
> collect2: error: ld returned 1 exit status
>

**Comment by am11** [comment]
@mgaeckler1964, can you tell the brand and version of compiler you used on Linux? Does your compiler support C++11?
libnethost currently requires a toolchain capable of compiling C++11 code.

try: `echo | c++ -dM -E -xc++ - | grep cplusplus`
first four chars represent the year, which corresponds to version of the language.

ps - the bar could be lowered down to plan old C99 by code refactoring in corehost, such that it reuses helpers out of native libs and mono, instead of the bulky STL.

**Comment by mgaeckler1964** [comment]
It is gnu C++ 4.8.5
the year is 1997

may be, the compiler is too old.

**Comment by am11** [comment]
Yup, it is too old. g++ [4.9 onwards](https://github.com/dotnet/arcade/blob/7e7a0a5b3d0e3ee2f694f321cbd603234f14038e/eng/common/native/init-compiler.sh#L75) should support C++11 features required by .NET runtime.

**Comment by mgaeckler1964** [comment]
Now I have updated the compiler. It's a large project and it took a while. I still get the error messages:

/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.5/runtimes/linux-x64/native/libnethost.a(utils.cpp.o): In function `std::string::_M_check(unsigned long, char const*) const':
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.5/runtimes/linux-x64/native/libnethost.a(utils.cpp.o):/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow

devtoolset-9 is installed on my machine. With this tool set, I was able to compile some example hosts.

any idea?

**Comment by am11** [comment]
Please show the output of `/path/to/problematic/g++ -v`. Make sure it is the exactl g++ binary which is throwing the error (e.g. check with `VERBOSE=1 make 2>&1 | grep g++` if you are using a make file).

**Comment by mgaeckler1964** [comment]
The output is:

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.3.1-20200408/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)

**Comment by am11** [comment]
> --with-default-libstdcxx-abi=gcc4-compatible

The issue is that g++ was compiled with this flag. It sets default value of `_GLIBCXX_USE_CXX11_ABI` to 0 (going by the manual: https://gcc.gnu.org/onlinedocs/libstdc++/manual/configure.html). You can try to add an explicit definition: `-D_GLIBCXX_USE_CXX11_ABI=1`.

**Comment by mgaeckler1964** [comment]
Thanks. Looks good. There are still some errors, but I will analyse on monday. Thanks again.

**Comment by mgaeckler1964** [comment]
Did read a wrong log. There is still the error message on the same code: std::__throw_out_of_range_fmt is not defined.

**Comment by am11** [comment]
Do the following commands throw `std::out_of_range` on your machine?

```sh
$ g++ -xc++ - <<EOF
#include <string>
int main()
{
  std::__throw_out_of_range_fmt("a b c", 1, 2, 3);
  return 0;
}
EOF

$ ./a.out
# expected:
#   terminate called after throwing an instance of 'std::out_of_range'
#    what():  a b c
#   Aborted (core dumped)
```

**Comment by mgaeckler1964** [comment]
gcc -L/usr/lib64 -L/lib64 -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined -Wl,--allow-multiple-definition -Wl,--start-group -o linux_x64REL_gcc_9_YR/libcoomk.so -Wl,--version-script="coomk.map" -shared -Wl,-soname=libcoomk.so -Wl,--whole-archive -Wl,-Bsymbolic-functions  -lz linux_x64REL_gcc_9_YR/gnudebuglink.o  "`find /usr/share/dotnet -name libnethost.a | grep x64 | grep -e /5. -e /6. | sort | tail -n 1`" "/build/kernel/lib/linux_x64REL/gcc_9_Ycoomk.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yfscdtm.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yfscindex.a" "/build/kernel/lib/linux_x64REL/gcc_9_Ymodel.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yquery.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yutil.a" "/build/kernel/lib/linux_x64REL/gcc_9_YcoovxR.o" "/build/kernel/gradle/server/common/lib/linux_x64/libbase.a" "/build/kernel/gradle/server/common/lib/linux_x64/libcoost.a" "/build/kernel/gradle/server/common/lib/linux_x64/libfscrmp.a" "/build/kernel/gradle/server/common/lib/linux_x64/libmmcst.a" "/build/kernel/gradle/server/common/lib/linux_x64/libsys.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadecache.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadeeventq.so" "/build/kernel/gradle/ade/lib/linux_x64/libadedb.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadexml.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadehttpcli.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadesnmp.so"  "/build/kernel/gradle/ade/bin/linux_x64REL/libadegui.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libaderegex.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadesec.so" "/build/kernel/gradle/server/common/lib/linux_x64/gcc_9_YdccliR.a" /build/kernel/gradle/mes/lib/libprotobuf.a /build/kernel/gradle/mes/lib/libmes.a -Wl,--no-whole-archive -lstdc++ -lldap -llber -L/usr/kerberos/lib -lgssapi_krb5 -lkrb5 -lcom_err -lpthread -lc -lm -ldl -luuid -Wl,--whole-archive "/build/kernel/gradle/apm/libsoftwaretelemetry-el7-x86_64/libsoftwaretelemetry.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadeicu.so" -Wl,--end-group -Wl,--no-whole-archive

**Comment by am11** [comment]
This is not invoking g++ directly. You can try with `gcc -std=c++11 -L/usr/lib64 ...`

**Comment by mgaeckler1964** [comment]
This is the command line that we use to compile C++-Source:

gcc -I/usr/include/nptl -I/usr/kerberos/include -I"/build/kernel/gradle/develop/version" -I"/build/kernel/gradle/apm/swtapidefinition" -I"/build/kernel/gradle/ade/include" -I"/build/kernel/gradle/ade/include/base" -I"/build/kernel/gradle/ade/include/di" -I"/build/kernel/gradle/ade/include/gui" -I../cootlb -I../coosp -I../coovx -I"/build/kernel/gradle/server/common/include" -I"/build/kernel/swcincl" -I../main -I../model -I../util "-I`find /usr/share/dotnet -name nethost.h -printf \"%h\n\" | grep x64 | grep -e /5. -e /6. | sort | tail -n 1`" -DTRACE -DADEDI_INSTRUMENT -D__PROJECT__='"gcc_9_Ycoomk"' -DAPPICON=1000 -D__GNU_COMPILER -DUNIX -Dunix -DLINUX -DLINUX_RHEL -D_REENTRANT -D_GNU_SOURCE -D__cdecl="" -DX64 -D_X64_ -DAMD64 -D_AMD64_ -DVERSION_MAJOR_NR=22 -DVERSION_MINOR_NR=6 -DVERSION_SUB_NR=0 -DVERSION_BUILD_NR=239 -DBUILD_TYPE=BUILD_INTERNAL -DNOOLDINTERFACENAMES -fpic -DPIC -g -ftls-model=global-dynamic -fvisibility=hidden -O0 -fstack-protector-all -fno-strict-aliasing -ffunction-sections -fdata-sections -Wformat -Wno-format-zero-length -Wformat-security -Winit-self -Wreturn-type -Wuninitialized -Werror -Wno-error=deprecated-declarations -Wno-error=maybe-uninitialized  -o linux_x64TRACE_gcc_9_YR/coomkcu.o -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -c coomkcu.cxx

**Comment by mgaeckler1964** [comment]
There is no change.

gcc -L/usr/lib64 -L/lib64 -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined -Wl,--allow-multiple-definition -Wl,--start-group -o linux_x64REL_gcc_9_YR/libcoomk.so -Wl,--version-script="coomk.map" -shared -Wl,-soname=libcoomk.so -Wl,--whole-archive -Wl,-Bsymbolic-functions  -lz -std=c++11 linux_x64REL_gcc_9_YR/gnudebuglink.o  "`find /usr/share/dotnet -name libnethost.a | grep x64 | grep -e /5. -e /6. | sort | tail -n 1`" "/build/kernel/lib/linux_x64REL/gcc_9_Ycoomk.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yfscdtm.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yfscindex.a" "/build/kernel/lib/linux_x64REL/gcc_9_Ymodel.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yquery.a" "/build/kernel/lib/linux_x64REL/gcc_9_Yutil.a" "/build/kernel/lib/linux_x64REL/gcc_9_YcoovxR.o" "/build/kernel/gradle/server/common/lib/linux_x64/libbase.a" "/build/kernel/gradle/server/common/lib/linux_x64/libcoost.a" "/build/kernel/gradle/server/common/lib/linux_x64/libfscrmp.a" "/build/kernel/gradle/server/common/lib/linux_x64/libmmcst.a" "/build/kernel/gradle/server/common/lib/linux_x64/libsys.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadecache.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadeeventq.so" "/build/kernel/gradle/ade/lib/linux_x64/libadedb.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadexml.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadehttpcli.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadesnmp.so"  "/build/kernel/gradle/ade/bin/linux_x64REL/libadegui.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libaderegex.so" "/build/kernel/gradle/ade/bin/linux_x64REL/libadesec.so" "/build/kernel/gradle/server/common/lib/linux_x64/gcc_9_YdccliR.a" /build/kernel/gradle/mes/lib/libprotobuf.a /build/kernel/gradle/mes/lib/libmes.a -Wl,--no-whole-archive -lstdc++ -lldap -llber -L/usr/kerberos/lib -lgssapi_krb5 -lkrb5 -lcom_err -lpthread -lc -lm -ldl -luuid -Wl,--whole-archive "/build/kernel/gradle/apm/libsoftwaretelemetry-el7-x86_64/libsoftwaretelemetry.a" "/build/kernel/gradle/ade/bin/linux_x64REL/libadeicu.so" -Wl,--end-group -Wl,--no-whole-archive

Still got the same error message.

**Comment by am11** [comment]
If you could create an [SSCCE](http://sscce.org), that would help us reproducing the issue and provide you with more accurate solution.

One thing I know about compiler driver (gcc/g++) is that order of arguments matter. Especially the ones which are prefixed with `-Wl` which get forwarded to binutils, and then to the linker.

**Comment by mgaeckler1964** [comment]
Thanks, I will try to create a SSCCE. According to that error message:

/usr/share/dotnet/packs/Microsoft.NETCore.App.Host.linux-x64/6.0.0/runtimes/linux-x64/native/libnethost.a(utils.cpp.o): In function `std::string::_M_check(unsigned long, char const*) const':
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/basic_string.h:3390: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'


I assume that it is libnethost.a that reqires the symbol. In which library is that symbol defined? Is that a wrong error message from gcc?

BTW: In windows everthing works fine.

BR Martin

**Comment by mgaeckler1964** [comment]
It seems to me, that I found a possible solution:

  LIBS = "`find /usr/share/dotnet -name libnethost.a | grep x64 | grep -e /5. -e /6. | sort | tail -n 1`"
  LIBS += "`find /usr/share/dotnet -name libnethost.so | grep x64 | grep -e /5. -e /6. | sort | tail -n 1`"

I added both, the static library and the shared library.

I hope, I was not happy too early.

**Comment by mgaeckler1964** [comment]
Now my Jenkins Build is successfull.

**Comment by janvorli** [comment]
I believe the missing symbol should be defined in the standard c++ library, the libstdc++. @mgaeckler1964 is it possible that your app is not linking to that library?

**Comment by elinor-fung** [comment]
@mgaeckler1964 were you able to check what @janvorli asked above?
