### ISSUE TITLE
Native AOT publishes unused files

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#69312]
The `<App>.deps.json` and `<App>.runtimeconfig.json` files gets published as well.

```
dotnet new console
dotnet publish /p:PublishAot=true -r win-x64 -c Release
```

The `bin\Release\net7.0\win-x64\publish` contains the above 2 files, `<App>.deps.json `and `<App>.runtimeconfig.json` in addition to the `<App>.exe` and `<App>.pdb`. These extra files should not be present in the `publish` directory

**Comment by Symbai** [comment]
Dupe of #63265
