### ISSUE TITLE
Can the BlockingCollection<T>.GetConsumingEnumerable iterator be optimized?

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#69320]
Hi! I noticed that the implementation of the [`BlockingCollection<T>.GetConsumingEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.getconsumingenumerable) method checks twice if the collection [`IsCompleted`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.iscompleted) on each iteration. It is checked in [the `while` loop](https://github.com/dotnet/runtime/blob/dfa39de33fe7e0c883eb0c343ab4012c8d5351a8/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs#L1652-L1659):

```C#
while (!IsCompleted)
{
    T? item;
    if (TryTakeWithNoTimeValidation(out item, Timeout.Infinite, cancellationToken, linkedTokenSource))
    {
        yield return item;
    }
}
```

...and also inside the [`TryTakeWithNoTimeValidation`](https://github.com/dotnet/runtime/blob/dfa39de33fe7e0c883eb0c343ab4012c8d5351a8/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs#L679-L682) method:

```C#
if (IsCompleted)
{
    return false;
}
```

I would like to ask if there is a technical reason for this double check, or if it's something that could be optimized. Like this for example:

```C#
while (true)
{
    T? item;
    if (TryTakeWithNoTimeValidation(out item, Timeout.Infinite, cancellationToken, linkedTokenSource))
    {
        yield return item;
    }
    else
    {
        break;
    }
}
```

Thanks!

**Comment by theodorzoulias** [comment]
@eiriktsarpalis yes, the `TryTakeWithNoTimeValidation` is also used by these three methods:

```C#
public bool TryTake(out T item, TimeSpan timeout);
public bool TryTake(out T item, int millisecondsTimeout);
public bool TryTake(out T item, int millisecondsTimeout, CancellationToken cancellationToken);
```

The check is needed for these methods. Removing it would most likely cause performance regression. It's just that the `GetConsumingEnumerable` iterator does also this check just before calling this method, so it seems like the check in the iterator `while (!IsCompleted)` is superfluous.

Regarding prototyping an improvement, I am not aware of the procedure. Is there any document that I could read about it?

**Comment by eiriktsarpalis** [comment]
Take a look at the [workflow guide](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md#workflow-guide) to get started on building and testing the repo.

**Comment by theodorzoulias** [comment]
@eiriktsarpalis thanks for the [link](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md#workflow-guide). I am seeing that building the repository is a quite involved process, so I'll skip it for now. Feel free to close this issue if you think that it's not actionable. The impact of removing the superfluous check of a `volatile` field should be quite minuscule after all. 😃

**Comment by theodorzoulias** [comment]
I think that I found the answer why the "superfluous" second check exists. In the case of a completed `BlockingCollection<T>`, the `GetConsumingEnumerable` iterator has different behavior than the `Take`/`TryTake` methods when cancellation is involved. The iterator ignores the cancellation and completes normally, while the `Take`/`TryTake` honor the cancellation and complete with exception. Here is a minimal demonstration of this behavior:

```C#
var blockingCollection = new BlockingCollection<object>();
blockingCollection.CompleteAdding();
var token = new CancellationToken(true); // Canceled

Test("Take", () => blockingCollection.Take(token));
Test("TryTake", () => blockingCollection.TryTake(out _, Timeout.Infinite, token));
Test("GetConsumingEnumerable", () =>
{
    foreach (var item in blockingCollection.GetConsumingEnumerable(token)) { }
});

static void Test(string title, Action action)
{
    try { action(); Console.WriteLine($"{title}, OK!"); }
    catch (Exception ex) { Console.WriteLine($"{title}, Error: {ex.GetType().Name}"); }
}
```

Output:

```none
Take, Error: OperationCanceledException
TryTake, Error: OperationCanceledException
GetConsumingEnumerable, OK!
```

[Live demo](https://dotnetfiddle.net/tXeXvY).

So the optimization that I suggested is problematic, because it results in a behavioral change: The iterator will start throwing exceptions in conditions that previously didn't.

I am not closing this issue, because it might be possible to eliminate the double check without altering the current behavior.

**Comment by eiriktsarpalis** [comment]
> I am not closing this issue, because it might be possible to eliminate the double check without altering the current behavior.

I guess my question would be, why is it important to eliminate the double check? Is it demonstrably impacting performance? I wouldn't think so, this is a concurrent collection so I find it unlikely that a redundant check would be a performance bottleneck.

**Comment by theodorzoulias** [comment]
@eiriktsarpalis the `BlockingCollection<T>.IsCompleted` property ([source code](https://github.com/dotnet/runtime/blob/dfa39de33fe7e0c883eb0c343ab4012c8d5351a8/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs#L90-L97)) calls the `SemaphoreSlim.CurrentCount` property ([source code](https://github.com/dotnet/runtime/blob/f8323092eb414f9fc09a262132c65e09c5427c10/src/libraries/System.Private.CoreLib/src/System/Threading/SemaphoreSlim.cs#L82)), which is backed by a `volatile` field. My understanding is that accessing a `volatile` field results in emitting a half fence, which is not something completely trivial. From what I know it amounts to a few dozens CPU cycles, but I might be wrong.
