### ISSUE TITLE
should expose the accumulative GC pause duration as a counter

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#69324]
essentially expose what's implemented in this [API](https://github.com/dotnet/runtime/pull/68835) that @cshung is working on. this should replace the current % time in GC since last GC which is simply not a good counter. see explanation [here](https://devblogs.microsoft.com/dotnet/gc-etw-events-1/).

**Comment by Maoni0** [comment]
@tommcdon could someone from your team please add this?

**Comment by tommcdon** [comment]
@Maoni0 thanks for the suggestion! Adding @mikelle-rogers to take a look.

**Comment by joaocpaiva** [comment]
+1

Having a reliable counter to track the relative cost of GC pauses is important to identify regressions or validate improvements, as it reflects in tail latency and CPU. And for cloud services, tracking the relative cost of GC becomes paramount, especially for latency-sensitive workloads. Please prioritize this accordingly.
