### ISSUE TITLE
[API Proposal]: Make Unsafe work with readonly byref values

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#69352]
### Background and motivation

Methods on the Unsafe class don't compose with `ref readonly` variables. This could be remedied by changing byref parameters to use "in" instead of "ref"

### API Proposal

Consider this simple code:

```csharp
using System.Runtime.CompilerServices;

public class Program
{
    public ref readonly int GetRef() => throw new NotImplementedException();

    public void Foo()
    {
        ref readonly int x = ref GetRef();
        ref readonly int y = ref GetRef();

        if (Unsafe.AreSame(ref x, ref y))  // won't compile
        {
        }

        if (Unsafe.IsNullRef(ref x))    // won't compile
        {
        }
    }
}
```

This doesn't compile since AreSame and IsNullRef demand "ref" values instead of "in" values.

### API Usage

```csharp
using System.Runtime.CompilerServices;

public class Program
{
    public ref readonly int GetRef() => throw new NotImplementedException();

    public void Foo()
    {
        ref readonly int x = ref GetRef();
        ref readonly int y = ref GetRef();

        if (Unsafe.AreSame(in x, in y))
        {
        }

        if (Unsafe.IsNullRef(in x))
        {
        }
    }
}
```

**Comment by stephentoub** [comment]
The plan is to change the relevant methods to use readonly ref once the C# 11 compiler supports it.

**Comment by jkotas** [comment]
> The plan is to change the relevant methods to use readonly ref once the C# 11 compiler supports it.

We may be able to do that for methods that take byrefs as inputs (e.g. `Unsafe.IsNullRef`, but not for methods that take byrefs as both inputs and outputs (e.g. `Unsafe.Add`) without introducing new overloads.

For writing unsafe code with `refs`, I believe it is best to cast away the readonly first using `Unsafe.AsRef` and then operate on `refs`. It avoids the `in` traps and eliminates the visual clutter of having readonly everywhere. I do not believe readonly adds a lot of value for unsafe code. We not have readonly unmanaged pointers in C# either.

**Comment by stephentoub** [comment]
> We may be able to do that for methods that take byrefs as inputs (e.g. Unsafe.IsNullRef,

Right. Both IsNullRef and AreSame cited in the example will be on this plan.

**Comment by geeknoid** [comment]
As a stop-gap, I implemented the following, which fixes two problems for me. It addresses `ref readonly`, and it hide target framework differences (since our stuff needs to work on top of old and new frameworks)

```csharp
/// <summary>
/// Utilities to manipulate byref values.
/// </summary>
public static class ByReference
{
    /// <summary>
    /// Returns a reference to a value of type <typeparamref name="T"/> that is a null reference.
    /// </summary>
    /// <typeparam name="T">The type of the reference.</typeparam>
    /// <returns>A reference to a value of type <typeparamref name="T"/> that is a null reference.</returns>
    public static ref T Null<T>()
    {
#if NET5_0_OR_GREATER
        return ref Unsafe.NullRef<T>();
#else
#pragma warning disable S2333 // Redundant modifiers should not be used
        unsafe
        {
            return ref Unsafe.AsRef<T>(null);
        }
#pragma warning restore S2333 // Redundant modifiers should not be used
#endif
    }

    /// <summary>
    /// Determines if a given reference to a value of type <typeparamref name="T"/> is a null reference.
    /// </summary>
    /// <typeparam name="T">The type of the reference.</typeparam>
    /// <param name="source">The reference to check.</param>
    /// <returns><see langword="true"/> if <paramref name="source"/> is a null reference; otherwise, <see langword="false"/>.</returns>
    public static bool IsNull<T>(in T source)
    {
#if NET5_0_OR_GREATER
        return Unsafe.IsNullRef(ref Unsafe.AsRef(source));
#else
        unsafe
        {
            return Unsafe.AsPointer(ref Unsafe.AsRef(source)) == null;
        }
#endif
    }

    /// <summary>
    /// Determines whether the specified references point to the same location.
    /// </summary>
    /// <typeparam name="T">The type of reference.</typeparam>
    /// <param name="left">The first reference to compare.</param>
    /// <param name="right">The second reference to compare.</param>
    /// <returns><see langword="true" /> if <paramref name="left"/> and <paramref name="right"/> point to the same location; otherwise, <see langword="false"/>.</returns>
    public static bool AreSame<T>(in T left, in T right) => Unsafe.AreSame(ref Unsafe.AsRef(left), ref Unsafe.AsRef(right));
}
```

**Comment by JensMunkHansen** [comment]
Will the workaround also work for Unsafe.As<ImmutableArray<T>, T[]>(ref ImmutableArray<T>, T[]), when the immutable is declared readonly. I have implemented myself an Immutable extension, where bytealignment can be specified - this is awesome when interop'in with native SIMD code

**Comment by stephentoub** [comment]
This was addressed in .NET 8.
