### ISSUE TITLE
ARM32: Assertion failed 'varDsc->lvType == TYP_STRUCT' in 'System.SpanHelpers:Fill(byref,int,System.__Canon)' during 'Generate code' in jitminopts runs

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69350]
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1770681&view=results
Job: coreclr Linux arm Checked jitminopts

```scala
        Assert failure(PID 528 [0x00000210], Thread: 528 [0x0210]): Assertion failed 'varDsc->lvType == TYP_STRUCT' in 'System.SpanHelpers:Fill(byref,int,System.__Canon)' during 'Generate code' (IL size 911; hash 0xc319f39c; MinOpts)
        
            File: /__w/1/s/src/coreclr/jit/codegenarmarch.cpp Line: 1306
            Image: /root/helix/work/correlation/corerun
```

Introduced in range [72f9cb2d..6f15fdc8](https://github.com/dotnet/runtime/compare/72f9cb2d...6f15fdc8)

**Comment by jakobbotsch** [comment]
Repros in arm32 altjit for
```csharp
public static void Main()
{
    Span<object> foo = new object[1000];
    foo.Fill(null);
}
```
with `COMPlus_JITMinOpts=1`

**Comment by jakobbotsch** [comment]
Bisected this to #68739, cc @dotnet/jit-contrib @tannergooding

**Comment by tannergooding** [comment]
I wonder if this is handled by @SingleAccretion's PR: https://github.com/dotnet/runtime/pull/69271

It might also be a different issue and in need of its own work item/fix.

**Comment by SingleAccretion** [comment]
I will investigate this; on first approximation the assert looks questionable because there is no requirement for the underlying local and the `OBJ` on top of it to match (there is a similarly questionable `assert(!varDsc->lvIsHfa())` assert below).
