### ISSUE TITLE
UdpClient GC pressure

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#69355]
### Description

Every UdpClient instance allocates a fresh new 64k size array.
When there is a program creating many UdpClient instances there is an unnecessary GC pressure.
This could happen in a loop or when you send data to a different addresses over network.

A workaround I used is making MyUdpClient replacing `new byte[]` with ArrayPool.
  
My suggestion is to allow UdpClient to receive a memory buffer for its work, for instance receiving Memory<byte>.
This would allow making a simple wrapper which uses ArrayPool.

I do not know whether this change in UdpClient itself is possible or good idea.

**Comment by AaronRobinsonMSFT** [comment]
Seems like a good opportunity for an API proposal. Maybe a low-level static `Create` instead of another `.ctor` overload?

https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L14-L20

**Comment by iSazonov** [comment]
> Seems like a good opportunity for an API proposal.

In the case we could think about getting rid of buffer copying:
https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L384-L389
https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L384-L389
https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L665-L667
https://github.com/dotnet/runtime/blob/af2a48ddaec9a3e27002b0d3b80c07431c2e38c1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/UDPClient.cs#L870-L875

**Comment by AaronRobinsonMSFT** [comment]
Summoning our benevolent memory usage gatekeeper... @stephentoub

**Comment by wfurt** [comment]
What is motivation for developers to use `UdpClient` instead of `Socket` directly?
There is https://github.com/dotnet/runtime/issues/63162 for TCP. Perhaps this deserves same....
(or blend TCP, UDP and TLS to single API like Apple did)

**Comment by NN---** [comment]
> In the case we could think about getting rid of buffer copying:
> 
I do not think it is possible here.
The API returns array which has a fixed size and obviously would require a copy if you want to return a smaller sized one.

The API could be changed to return Memory<byte>, and this would allow reusing the same buffer while setting an appropriate size. 
However this is an API breakage with all its consequences.

**Comment by stephentoub** [comment]
I have the same question as @wfurt. From my perspective, both TcpClient and UdpClient are useless types. Socket can just be used directly.

**Comment by wfurt** [comment]
closing per comment above. `UdpClient.Client` can  be used directly with whatever memory management strategy. 
8.0 also added new `Socket` APIs to avoid allocations for endpoint e.g. #30797
