### ISSUE TITLE
Iconize executable

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#69372]
![grafik](https://user-images.githubusercontent.com/10373452/168402654-719c4bbc-6088-435d-8dbb-b8dba7c7dbfc.png)
I noticed that the `dotnet.exe` unfortunately has no icon. I would like to see the .NET icon here, for example.
Of course, it's nothing critical but just a "nice-to-have" feature. But in my opinion it doesn't hurt either.

I don't find it nice to see a boring standard Windows icon there.

---

* [ ] Windows - #70578
* [ ] OSX
* [ ] possibly other systems

**Comment by danmoseley** [comment]
@richlander

**Comment by richlander** [comment]
Interesting. That's a good point. I have to admit this has never occurred to me. I also don't spend much time in task manager. However, I like the idea. Is this possible @vitek-karas? If so, what are the specs for the icon we'd need? I'd be happy to get us one.

**Comment by deeprobin** [comment]
> what are the specs for the icon we'd need? 

The specs are a `.ico` file for Windows - See https://docs.microsoft.com/en-us/windows/win32/menurc/about-icons?redirectedfrom=MSDN. These icons generally only work under Windows afaik.

> I also don't spend much time in task manager. 

Adding a corresponding icon to the `.rc` file means not only that this icon will be displayed in the Task Manager but also in the Explorer.

**Comment by vitek-karas** [comment]
As far as I can tell the official guidelines are here: https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons?redirectedfrom=MSDN#size-requirements

Somewhat related: https://github.com/dotnet/runtime/issues/2688

**Comment by richlander** [comment]
How about these:

256x256 and 32x32

![dotnet-logo-256px](https://user-images.githubusercontent.com/2608468/169121509-f56d1cdc-0a95-4e18-bc19-bc3d087d5a54.png)
![dotnet-logo-32px](https://user-images.githubusercontent.com/2608468/169121544-a355dc18-202a-43a5-b788-0a460c3ad5d5.png)

Source: https://github.com/dotnet/brand/blob/main/logo/dotnet-logo.png

**Comment by deeprobin** [comment]
@richlander In my opinion using the branding of the foundation there is great 👍🏼.

---

On the [C# Community Discord](https://discord.gg/csharp) another suggestion came up, which I don't want to leave unmentioned.
That is, that we might use the .NET bot icon.

![dotnet-bot](https://user-images.githubusercontent.com/10373452/169123994-b74a0c6a-475d-4a97-b394-3b60912d3973.svg)

**Comment by richlander** [comment]
Cool idea. That's a lot of detail for a small icon. I think that most users would be better served by the larger block letters.

**Comment by Neme12** [comment]
> How about these:
> 
> 256x256 and 32x32

I think it would be good to get more sizes in the ico file, especially 48x48 and 64x64 (potentially 96 or 128 as well). These are common in places like the taskbar.

**Comment by richlander** [comment]
I was thinking the same thing @danmoseley. @vitek-karas suggested we get the help of a DevDiv designer. We're doing that.

**Comment by Neme12** [comment]
Visual Studio seems to be using a *lot* of sizes for its icon:
![image](https://user-images.githubusercontent.com/11444821/169168114-b31611cc-12d2-464f-a739-1c84a8024502.png)
![image](https://user-images.githubusercontent.com/11444821/169168164-6ec259e6-ce1d-4f93-b612-b071a5838713.png)

**Comment by richlander** [comment]
Hey folks, PTAL at this PR that resolves this issue: https://github.com/dotnet/runtime/pull/70578

**Comment by deeprobin** [comment]
@elinor-fung This is not resolved :D

**Comment by jkotas** [comment]
@deeprobin Why do you think that this is not resolved?

I have downloaded the latest nightly dotnet/runtime Windows x64 build from https://aka.ms/dotnet/7.0/daily/dotnet-runtime-win-x64.zip and I see the icon on dotnet.exe:

![image](https://user-images.githubusercontent.com/6668460/174306123-daebddf9-cc8d-4bf1-a788-8156ca65c600.png)

**Comment by vitek-karas** [comment]
@deeprobin probably means that the issue originally listed support on macOS and potentially other platforms. We've discussed macOS support, but it seems that without taking a dependency on Cocoa APIs this is not easily doable. So for now we decided to not do that.

If somebody has an idea how to add the icon on macOS without introducing additional dependencies we would definitely be interested.
