### ISSUE TITLE
Compiled regex hangs and finally fails for stack-intensive regex pattern

### ISSUE THREAD

**Issue by kobi** [dotnet/runtime#69381]
### Description

I was trying my [RecreationalRegex](https://github.com/kobi/RecreationalRegex) patterns in .NET 7 and noticed one of them is causing the engine to hang.

### Reproduction Steps

```c#
using System.Text.RegularExpressions;

// this is a partial pattern, it doesn't make sense on its own.
// full version at https://github.com/kobi/RecreationalRegex/blob/master/RecreationalRegex/Rectangles/SmallRectangles.cs
// documentation at https://kobikobi.wordpress.com/2016/10/11/filling-a-large-rectangle-with-smaller-rectangles-using-regular-expressions/
string pattern = @"
(?<IndexLength>.)+?
(?<=\A(?=(?<Index>(?<-IndexLength>.)+)).*)
(?<=\A(?<CurrentIndex>\k<Index>).*)
(?=.*\Z
    (?<!(?=\A\k<Index>(?<=\A\k<CurrentIndex>))\A.*(?<-Index>.)+) 
)
(?(Done)|(?!))
";

Regex regex = new Regex(pattern, RegexOptions.Compiled | RegexOptions.IgnorePatternWhitespace);

// this hang. removing RegexOptions.Compiled returns false as expected
var match = regex.IsMatch("11");
Console.WriteLine(match);
```

run using `dotnet run` 

The program runs normally without `RegexOptions.Compiled`, or with the input `"1"`.

I didn't spend too long trying it, but it's probably possible to shorter the pattern even further.

### Expected behavior

`IsMatch` should return `false`.

### Actual behavior

the program hangs, and after a while fails with arithmetic overflow

```
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Text.RegularExpressions.Match.AddMatch(Int32 cap, Int32 start, Int32 len)
   at Regex1_TryMatchAtCurrentPosition(RegexRunner, ReadOnlySpan`1)
   at Regex1_Scan(RegexRunner, ReadOnlySpan`1)
   at System.Text.RegularExpressions.Regex.ScanInternal(Boolean quick, String input, Int32 beginning, RegexRunner runner, ReadOnlySpan`1 span, Boolean returnNullIfQuick)
   at System.Text.RegularExpressions.Regex.RunSingleMatch(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Program.<Main>$(String[] args) in /mnt/c/Users/k0bi/Documents/GitHub/RegexCompileError/Program.cs:line 21
```

### Regression?

Working in .NET 6.

### Configuration

Running .NET 7.0.100-preview.4.22252.9 , I installed in on Ubuntu-20.04 running under Windows 10, WSL2.

I installed `dotnet` 7 preview manually and running it using `~/dotnet/dotnet run` (so maybe not the standard way)

**Comment by teo-tsirpanis** [comment]
I can reproduce with the source generator as well. Memory usage blows up.

**Comment by stephentoub** [comment]
Thanks to @kobi for the repros.

I whittled away at [RecreationalRegex_Rectangle](https://github.com/dotnet/runtime/blob/0332c6472a0007f4adb5c014474b8eeeabea73a5/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.KnownPattern.Tests.cs#L1416) until I got it small enough to debug.  The remaining bug (after https://github.com/dotnet/runtime/pull/69413) is that with lazy loops of more than just a single character, we're not uncapturing as part of backtracking 🤦
