### ISSUE TITLE
Microsof.Extensions.Logging.Abstractions version 6+ is not verifiable

### ISSUE THREAD

**Issue by vmcbaptista** [dotnet/runtime#69395]
### Description

When trying to check Microsoft.Extensions.Logging.Abstractions.dll with PEVerify.exe, for version 6.0.0 or later we receive errors.

### Reproduction Steps

Execute PEVerify.exe against .nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\lib\net461\Microsoft.Extensions.Logging.Abstractions.dll

### Expected behavior

Microsoft.Extensions.Logging.Abstractions.dll shall be verifiable like happens with version 5.0.0
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

All Classes and Methods in .nuget\packages\microsoft.extensions.logging.abstractions\5.0.0\lib\net461\Microsoft.Extensions.Logging.Abstractions.dll Verified.

### Actual behavior

Although, in version 6.0.0 or later we get:
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

 [HRESULT 0x80070002] - The system cannot find the file specified.

[IL]: Error: [.nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\lib\net461\Microsoft.Extensions.Logging.Abstractions.dll : Microsoft.Extensions.Logging.LogValuesFormatter::.ctor]  [HRESULT 0x80070002] - The system cannot find the file specified.

[IL]: Error: [nuget\packages\microsoft.extensions.logging.abstractions\6.0.0\lib\net461\Microsoft.Extensions.Logging.Abstractions.dll : Microsoft.Extensions.Logging.LogValuesFormatter::FormatArgument]  [HRESULT 0x80070002] - The system cannot find the file specified.

3 Error(s) Verifying Microsoft.Extensions.Logging.Abstractions.dll

### Regression?

Yes, it is a regression compared to version 5.0.0

**Comment by KalleOlaviNiemitalo** [comment]
It seems to be looking for System.Memory.dll, and then System.Buffers.dll. I suggest running PEVerify on DLLs in the output directory of your project, not directly on DLLs in NuGet packages.

With the required DLLs present, PEVerify finds unverifiable code in the net461 binary of Microsoft.Extensions.Logging.Abstractions  6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6:

```
Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\Projects\Kalle\net461\Microsoft.Extensions.Logging.Abstractions.dll : System.Text.ValueStringBuilder::Append][offset 0x0000003D] Unmanaged pointers are not a verifiable type.
[IL]: Error: [C:\Projects\Kalle\net461\Microsoft.Extensions.Logging.Abstractions.dll : Microsoft.Extensions.Logging.LogValuesFormatter::.ctor][offset 0x0000002C] Instruction cannot be verified.
[IL]: Error: [C:\Projects\Kalle\net461\Microsoft.Extensions.Logging.Abstractions.dll : Microsoft.Extensions.Logging.LogValuesFormatter::FormatArgument][offset 0x00000026] Instruction cannot be verified.
3 Error(s) Verifying .\Microsoft.Extensions.Logging.Abstractions.dll
```

Why do you care whether the code is verifiable?

**Comment by tarekgh** [comment]
Just to tell, even when trying to run the verifier on v5.0 it produces some other errors. Note, 5.0 package didn't target net core apps at all. It was supporting netstandard. 

```
peverify "c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.17\Microsoft.Extensions.Logging.Abstractions.dll"

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[MD]: Error: Token 0x0200000b following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000011]
[MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000015]
[MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000016]
[MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000017]
```

I echo @KalleOlaviNiemitalo question, `Why do you care whether the code is verifiable?`

**Comment by vmcbaptista** [comment]
> Just to tell, even when trying to run the verifier on v5.0 it produces some other errors. Note, 5.0 package didn't target net core apps at all. It was supporting netstandard.
> 
> ```
> peverify "c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\5.0.17\Microsoft.Extensions.Logging.Abstractions.dll"
> 
> Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
> Copyright (c) Microsoft Corporation.  All rights reserved.
> 
> [MD]: Error: Token 0x0200000b following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000011]
> [MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000015]
> [MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000016]
> [MD]: Error: Token 0x02000017 following ELEMENT_TYPE_CLASS (_VALUETYPE) in signature is a ValueType (Class,respectively). [token:0x04000017]
> ```
> 
> I echo @KalleOlaviNiemitalo question, `Why do you care whether the code is verifiable?`

If you use version 5.0.0 in a .NET Framework project it will use the DLL under .nuget\packages\microsoft.extensions.logging.abstractions\5.0.0\lib\net461\Microsoft.Extensions.Logging.Abstractions.dll, which as I mentioned is verifiable.

I'm raising this issue because faced a situation where I got the exception System.Security.VerificationException: "Operation could destabilize the runtime." with the stack pointing to the constructor of LogValuesFormatter.

After researching it pointed me to the PEVerify and indeed it seems like this dll is not verifiable

**Comment by tarekgh** [comment]
@vmcbaptista thanks for the info. Yes, I can reproduce the same now. 

> I got the exception System.Security.VerificationException: "Operation could destabilize the runtime." with the stack pointing to the constructor of LogValuesFormatter.

Could you please elaborate more on that? in what situation you are getting exception? I mean what you were trying to do when encountered such exception.

**Comment by vmcbaptista** [comment]
This is happening inside a Dynamics 365 plugin I've created that runs under sandbox, I believe it is somehow related with partial/low trust

**Comment by tarekgh** [comment]
> This is happening inside a Dynamics 365 plugin I've created that runs under sandbox, it is somehow related with partial/low trust

Yes, this looks related to unsafe code added to this library and complaining about that when running in partial trust in .NET Framework. I'll take more look here. @vmcbaptista do you have any small example repro the issue? if not, I think I can do it.

**Comment by vmcbaptista** [comment]
@tarekgh I don't have any small example for this as it only happens inside dynamics and I don't know how to replicate their partial trust configurations. Please try to create your own sample.

**Comment by tarekgh** [comment]
The problem happening here is because the app is running in partial trust mode. None of the libraries in dotnet/runtime are supported in partial trust. Our recommendation is turn off partial trust sandboxing.

The [Code Access Security doc](https://docs.microsoft.com/en-us/previous-versions/dotnet/framework/code-access-security/code-access-security)

CC @jkotas
