### ISSUE TITLE
[API Proposal]: New custom type marshaller features for pay-for-play features

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#69403]
### Background and motivation

After getting some community feedback around the new source generated marshaller, we have decided that we want to add a few additional feature flags that the generator will respect to generate code differently. None of these features require us to change the shape of the marshaller types; the only change in code is emitted by the generator itself.

The `NeedsKeepAlive` flag will direct source-generated interop to emit a call to keep the marshaller object alive across the native call (though `GC.KeepAlive` or other means). This feature is used internally in the generator by delegate marshalling and can be used by many other marshallers as well (the internal `HandleRefMarshaller` comes to mind as well as the many [uses of `GC.KeepAlive` in WinForms](https://github.com/dotnet/winforms/search?q=GC.KeepAlive).

The `RequiresPreservedState` feature flag contributes to https://github.com/dotnet/runtime/issues/69096. Ensuring that we preserve marshaller state between the managed->unmanaged and the unmanaged->managed stages in all scenarios is very expensive, and the majority of marshallers do not require this support. This feature flag provides an opt-in model to preserve state when required (with any additional required overhead) and will direct the generator to emit a diagnostic when preserving state is not supported.

The `GuaranteedUnmarshal` flag directs the generator to emit the `ToManaged` call on the marshaller to be generated in the `GuaranteedUnmarshal` phase in the code-gen (in the `finally` block in the LibraryImport case). This flag would be used by marshallers like the (currently intrinsic in the marshaller) `SafeHandle` marshaller that have certain guarantees around unmarshalling to avoid memory leaks if another marshaller throws an exception. Adding this flag (along with `RequiresPreservedState` should enable us to safely convert the `SafeHandle` marshalling code to be a public marshaller instead of being intrinsically coded into the generator (which we believe makes the source generator much more maintainable).

### API Proposal

```diff
namespace System.Runtime.InteropServices.Marshalling;

[Flags]
public enum CustomTypeMarshallerFeatures
{
    None = 0,
    UnmanagedResources = 0x1,
    CallerAllocatedBuffer = 0x2,
    TwoStageMarshalling = 0x4,
+   NeedsKeepAlive = 0x8,
+   RequiresPreservedState = 0x10,
+   GuaranteedUnmarshal = 0x20
}
```

### API Usage

```csharp
[CustomTypeMarshaller(typeof(TManaged), Features = CustomTypeMarshallerFeatures.NeedsKeepAlive | CustomTypeMarshallerFeatures.RequiresPreservedState | CustomTypeMarshallerFeatures.GuaranteedUnmarshal)]
public struct Marshaller
{
// ... required members
}
```

### Risks

We only have a limited number of feature flags possible with the 32-bit `CustomTypeMarshallerFeatures` enum, so we need to make sure we don't use up all possible options.

**Comment by AaronRobinsonMSFT** [comment]
> `+   NeedsKeepAlive = 0x8,`

Perhaps we could ask the marshaller author to provide a `KeepAlive()` implementation instead of asking us to do the work.

**Comment by jkotas** [comment]
> `RequiresPreservedState`

Would it make sense to deal with this situation by doing the state-free marshalling using static methods? I think it is confusing to allow a state that is not guaranteed to be preserved.

> `GuaranteedUnmarshal`

Why is not enough to use general clean (`FreeNative` method) for this?

**Comment by jkoritzinsky** [comment]
> > `RequiresPreservedState`
> 
> Would it make sense to deal with this situation by doing the state-free marshalling using static methods? I think it is confusing to allow a state that is not guaranteed to be preserved.

The majority of marshallers fall into the scenario where the need state preserved only between the `From/ToNativeValue` and the corresponding pair (constructor or `ToManaged` method) and the `FreeNative` method. This flag is for preserving state between the constructor all the way to the `ToManaged` method. I guess we could do something state-free for the majority of the marshallers, but we don't have a design for that at the moment.

> > `GuaranteedUnmarshal`
> 
> Why is it not enough to use general cleanup (`FreeNative` method) for this?

The code to support "guaranteed unmarshal" through `FreeNative` would be very odd. We'd have to return the managed value in `ToManaged`, but still store it in the marshaller so we can update it with the actual values from native in the `FreeNative` method. Additionally, I don't know if it would work for the unmanaged->managed stub direction, which we're starting with in the COM-focused generators soon. (Although, SafeHandle marshalling doesn't work in the unmanaged->managed direction, so I guess we don't necessarily need to support it if our main/only use case is not applicable in that scenario anyway)

**Comment by jkotas** [comment]
> I guess we could do something state-free for the majority of the marshallers, but we don't have a design for that at the moment.

Yes, I think it would help with clarity. The state management in the current marshaller API shape is confusing. It makes it look like that the state is always preserved for the whole transaction, but it is not actually the case. Can we change the design such that marshaller instance state (if there is any) is always preserved for the whole transaction, and adjust the meaning name of the `RequiresPreservedState` flag accordingly?

**Comment by JeremyKuhne** [comment]
One scenario I would like to make sure works for `NeedsKeepAlive` is when we're marshalling a non-blittable struct. Specifically thinking of `HandleRef` or equivalent. Would still like a non-allocating way to tag managed objects that we don't want finalized. I don't know if there is a generic, non-allocating way to "root" a struct with managed fields?

**Comment by jkoritzinsky** [comment]
GC.KeepAlive has an optimization now in the JIT where it won't box a struct. Instead it will mark the struct value in a different way that will keep it alive.

**Comment by jkotas** [comment]
> Change the shape for value/collection marshallers:

These looks good to me.

> The interop team doesn't believe we can produce a zero-cost mechanism for preserving state in all cases and we don't have the bandwidth for the rest of the release to produce and implement a design for non-zero-cost state preservation

I agree that dealing with state preservation state is hard and that it may be hard to fit it into .NET 7. On the other hand, I believe that the model where the marshaller state is always preserved is the right fundamental model. Do you think we can come up with a scoped solution that maintains this model and fits into .NET 7?

Here is one option that I can think of:
- Introduce state-free marshalling pattern based on static methods.
   - `static NATIVE ConvertToNativeValue(MANAGED value)`
   - `static MANAGED ConvertToManaged(NATIVE value)`
   - `static void FreeNativeValue(NATIVE value)`
- In .NET 7, Array/Span marshallers are only supported with inner marshallers that implement the state-free marshalling pattern based on static methods.

**Comment by jkoritzinsky** [comment]
> > Change the shape for value/collection marshallers:
> 
> These looks good to me.
> 
> > The interop team doesn't believe we can produce a zero-cost mechanism for preserving state in all cases and we don't have the bandwidth for the rest of the release to produce and implement a design for non-zero-cost state preservation
> 
> I agree that dealing with state preservation state is hard and that it may be hard to fit it into .NET 7. On the other hand, I believe that the model where the marshaller state is always preserved is the right fundamental model. Do you think we can come up with a scoped solution that maintains this model and fits into .NET 7?
> 
> Here is one option that I can think of:
> 
> * Introduce state-free marshalling pattern based on static methods.
>   
>   * `static NATIVE ConvertToNativeValue(MANAGED value)`
>   * `static MANAGED ConvertToManaged(NATIVE value)`
>   * `static void FreeNativeValue(NATIVE value)`
> * In .NET 7, Array/Span marshallers are only supported with inner marshallers that implement the state-free marshalling pattern based on static methods.

If we were to support this static model, we would have to provide it for all of the string marshallers as well, as we'd otherwise break marshalling arrays of strings. We can't move to this shape exclusively, as it doesn't support caller-allocated-buffer marshalling. If we add a different string marshaller type, it would confuse users on how to add their own support as each `StringMarshalling` value would map to 2 marshaller types, depending on the scenario. Would we want the string marshaller types to implement multiple shapes (value and this new static shape)? In which case, how would we determine which marshaller path to use? Would we use the existing value shape when not in an array and the static shape otherwise?

**Comment by jkotas** [comment]
I think that the string marshallers would have to implement both shapes to keep the optimization using stack buffer. We have to use the marshaller instance when using the stack buffer since it has additional state. It should be fine to use the static shape for everything else. So the logic to determine which one to use can be same as the logic to determine whether to use the stack buffer.

**Comment by AaronRobinsonMSFT** [comment]
I'm not convince having two paths is the right thing. Is there a test we can perform that can be used to break this debate over the `static` model vs the instance method model with no state?

**Comment by jkotas** [comment]
The current debate is not about performance. It is about usability, based on feedback received in #69096.

**Comment by AaronRobinsonMSFT** [comment]
> The current debate is not about performance. It is about usability, based on feedback received in #69096.

Ah. Then doesn't adjusting the APIs to `InitializeFromManagedValue()` and `InitializeFromNativeValue()` address this?

**Comment by jkotas** [comment]
> Then doesn't adjusting the APIs to InitializeFromManagedValue() and InitializeFromNativeValue() address this?

Renaming the APIs does help a bit. The API shape is still confusing even after rename. The marshaller APIs are instance methods that makes it look like there is a preserved state one can depend one, but that's not actually the case. 

I believe that the model where the marshaller state is always preserved is the right model. It is not practical to preserve marshaller state in all case for performance and other reasons. That's how I came back to state-free marshalling using static methods. Static methods make it clear that there is no preserved state.

**Comment by AaronRobinsonMSFT** [comment]
> Static methods make it clear that there is no preserved state.

Agree this is a benefit but disagree it makes things all that better. It then results in a decision from the marshal author on approach, increased complexity in the source generator, but doesn't actually make anything safer because now we have two approaches that can both suffer if used incorrectly.

I would instead prefer to update the names and clearly document the semantics and expectations. Also, we've not had a chance to write official samples, guidance, or tutorials so I think adding more dimensions of configuration is premature at this point.

**Comment by jkotas** [comment]
I agree we can write some samples to see how well the current model works.

I would like to see an example for WinRT HSTRING marshaller that is both as efficient as possible for the simple `[In]` case and works for arrays of strings too.

**Comment by AaronRobinsonMSFT** [comment]
This issue should be addressed by the update API proposal. Let's continue the conversation there https://github.com/dotnet/runtime/issues/70859.
