### ISSUE TITLE
Memory leak in System.IO.Compression.DeflateStream

### ISSUE THREAD

**Issue by jjxtra** [dotnet/runtime#69411]
When someone does something supid, like I did, and does not dispose of their deflate stream, it appears that native memory leaks appear. They grow for each deflate stream that is created and not disposed. I noticed this with some code that decompresses data with a new deflate stream in a loop and runs for days.

Can we call dispose from a finalizer safely? The finalizer could skip dispose if it was already called. I believe the leak is from the native zlib deflater. The inflater also likely has the same issue if stream is not forcefully disposed.

I am not 100% sure this is the problem, but in a stress test that did many more compressions than my server process, I did see memory grow when not disposing. Adding a using... and re-running caused memory to stay steady.

https://github.com/dotnet/runtime/blob/0a1f2c760ee91f298875445eedcc248830c9b6ac/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L667

**Comment by huoyaoyuan** [comment]
`DeflateStream` should define a finalizer to call `Dispose(false)` since the base `Stream` class does not.

**Comment by adamsitnik** [comment]
> The DeflateStream itself does not hold unmanaged resource. Deflater holds native ZLib handle and defines finalizer properly.

@jjxtra In such a case the cleanup is going to be performed, but at a later time:

- during next garbage collection triggered by some allocation request that could not be handled without cleanup, GC is going to determine that deflater is eligible for finalization and move it to finalization queue
- when garbage collection is finished, the finalizer thread is going to look at the finalization queue and execute the deflater finalizer and release the resources
- during next garbage collection, the memory used by the deflater is going to be released

Since there is nothing more we can do, I am going to close the issue.

**Comment by jjxtra** [comment]
@adamsitnik inflater finalizer calls dispose of false which does not free the zlib stream unless I am missing something.

**Comment by jjxtra** [comment]
Thanks. What's the difference between internal finalize and internal dispose? Do they both do the same thing?

**Comment by adamsitnik** [comment]
> What's the difference between internal finalize and internal dispose? Do they both do the same thing? Looks like they are implemented in native code or as part of the compile step?

In case of `ZLibStreamHandle` it derives from `SafeHandle`:

https://github.com/dotnet/runtime/blob/6a889d234267a4c96ed21d0e1660dce787d78a38/src/libraries/Common/src/System/IO/Compression/ZLibNative.cs#L188

For `SafeHandle` both `Dispose` and finalizer call `Dispose(bool)`:

https://github.com/dotnet/runtime/blob/3f0c2cc88dc8efdde04f422bb05ef13719ce6aa8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L89-L91

https://github.com/dotnet/runtime/blob/3f0c2cc88dc8efdde04f422bb05ef13719ce6aa8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L68-L72

which calls `InternalRelease`:

https://github.com/dotnet/runtime/blob/3f0c2cc88dc8efdde04f422bb05ef13719ce6aa8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L95-L98

which calls an abstract `ReleaseHandle` method:

https://github.com/dotnet/runtime/blob/3f0c2cc88dc8efdde04f422bb05ef13719ce6aa8/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs#L249

which is defined by `ZLibStreamHandle` and based on the current state calls the right native method:

https://github.com/dotnet/runtime/blob/6a889d234267a4c96ed21d0e1660dce787d78a38/src/libraries/Common/src/System/IO/Compression/ZLibNative.cs#L215-L220

which is defined here:

https://github.com/dotnet/runtime/blob/ccca2d427087789f202a571f9a4d3866dec47d3e/src/native/libs/System.IO.Compression.Native/pal_zlib.c#L151-L157

So they both release unmanaged resources, but at different time: `Dispose` does it immediately when it's called by the user code, while finalizer does it after garbage collection when executed from finalizer thread.
