### ISSUE TITLE
Vector test failures on tvos on the rolling build #1774196

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#69424]
### Description

Several test failures for net7.0-tvOS-Release-arm64-Mono_Release-OSX.1015.Amd64.AppleTV.Open on rolling build https://runfo.azurewebsites.net/view/build/?number=1774196. Please find below list of failing tests on tvos.

[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128DoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector128tests.vector128doubleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128SingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector128tests.vector128singleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64SingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector64tests.vector64singleequalsnantest%22)
[System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64DoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.runtime.intrinsics.tests.vectors.vector64tests.vector64doubleequalsnantest%22)
[System.Numerics.Tests.PlaneTests.PlaneEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.planetests.planeequalsnantest%22)
[System.Numerics.Tests.QuaternionTests.QuaternionEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.quaterniontests.quaternionequalsnantest%22)
[System.Numerics.Tests.Vector2Tests.Vector2EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector2tests.vector2equalsnantest%22)
[System.Numerics.Tests.Matrix3x2Tests.Matrix3x2EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.matrix3x2tests.matrix3x2equalsnantest%22)
[System.Numerics.Tests.Matrix4x4Tests.Matrix4x4EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.matrix4x4tests.matrix4x4equalsnantest%22)
[System.Numerics.Tests.Vector3Tests.Vector3EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector3tests.vector3equalsnantest%22)
[System.Numerics.Tests.GenericVectorTests.VectorSingleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.genericvectortests.vectorsingleequalsnantest%22)
[System.Numerics.Tests.GenericVectorTests.VectorDoubleEqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.genericvectortests.vectordoubleequalsnantest%22)
[System.Numerics.Tests.Vector4Tests.Vector4EqualsNaNTest](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.numerics.tests.vector4tests.vector4equalsnantest%22)

From testResult.xml
![image](https://user-images.githubusercontent.com/96171496/168763005-07b84530-68f4-4ce8-9c1c-d581f3e69b78.png)

### Reproduction Steps

Failed on rolling build https://dev.azure.com/dnceng/public/_build/results?buildId=1774196&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d&l=56

### Expected behavior

Tests should pass

### Actual behavior

Tests are failing with exception.
![image](https://user-images.githubusercontent.com/96171496/168762832-4866f312-c77b-48fd-892b-08ca2b8f645d.png)

### Known Workarounds

For now we can skip on tvos failing tests.

**Comment by mkhamoyan** [comment]
@vargaz , @tannergooding could you please take a look ?

**Comment by vargaz** [comment]
Is this a regression ? If it is, when was the last time this worked ?

**Comment by mkhamoyan** [comment]
From April 29 it started failing in all runs, https://runfo.azurewebsites.net/view/build/?number=1744755 from this they started failing.

**Comment by tannergooding** [comment]
Only change that stands out is https://github.com/dotnet/runtime/pull/68691

It's possible that tvOS has some existing or different acceleration on the mono side that is incorrect or not showing for other platforms.

**Comment by tannergooding** [comment]
@fanyang-mono is there existing handling for Mono for these `Equals` methods. I had checked at the time and thought it wasn't enabled yet, but perhaps I missed something.

**Comment by fanyang-mono** [comment]
@tannergooding We added SIMD intrinsics support for `Equals` on Arm64 together with a bunch other ones a couple month ago. Here it is https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/simd-intrinsics.c#L1154

What special handling did you add recently on CoreCLR side?

**Comment by tannergooding** [comment]
@fanyang-mono it correctly takes `NaN` into account. `NaN != NaN` but `NaN.Equals(NaN)` is the requirement. `==/!=` follow the IEEE 754 requirements while `Equals`/`GetHashCode` follows the .NET requirements and allows the usage of a type in collections and maps.

**Comment by vargaz** [comment]
Probably needs to use LLVMRealUEQ in mini-llvm.c:9612

**Comment by fanyang-mono** [comment]
@vargaz Yes, I've tested it locally. And that is the problem for LLVM enabled scenarios. But I am not sure the `Build tvOS arm64 Release AllSubsets_Mono` lane used LLVM. And why the mono llvmfullaot lane didn't fail on Tanner's PR.

**Comment by fanyang-mono** [comment]
Oh, the failing tests are library tests, the llvmfullaot lane that I mentioned in my previous comment is for runtime tests.
