### ISSUE TITLE
CoreCLR_Shutdown and MetaDataGetDispenser Hang

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#69462]
### Description

I have a highly concurrent application that ETL's data between systems.

It usually works just fine, however, sometimes it will hang (even when debugging).  When it does, the following happens:
1. App becomes unresponsive and stops processing data.
2. App maxes out 1 CPU core (but isn't doing anything related to its job)
3. Visual Studio starts having issues.  It seems as if the debugger link between VS and my app gets frozen.  I cannot pause/stop my app through VS, and the Diagnostics Tools window stops updating.
4. The only way to recover is to end-task the application.

When this happens, I took a look at Process Explorer to look at threads and noticed that ```CoreClr_Shutdown``` is the function that is maxing out one CPU.  I also noticed that there are a lot of ```MetaDataGetDispenser``` threads.

I am not sure what is happening but I suspect that there is some kind of race condition I am bumping into somewhere in the framework.

When .NET 6.0 first came out, I opened a ticket with MS Support using my MSDN subscription.  I spent a lot of time and got nowhere.  Since upgrading to .NET 6.0.5, this seems to happen a whole lot more.

Is there anyone who can help?

Below are screen shots of what I see through Process Explorer:
![image](https://user-images.githubusercontent.com/13609558/168915444-82cc0462-12ec-4164-be70-cbc03b625f5d.png)

![image](https://user-images.githubusercontent.com/13609558/168916403-e17cf827-3468-49d2-a4e8-705670703fcb.png)

### Reproduction Steps

Run my app.  Sometimes it happens.  Sometimes it does not.

### Expected behavior

The app always runs responsively.  If there is a bug in my app, I should still be able to pause/stop through VS.

### Actual behavior

My app freezes and VS starts misbehaving.  Trying to pause/stop through VS does nothing and I must end-task my app.

### Regression?

It was an issue and now seems to occur more often since upgrading to .NET 6.0.5.

### Known Workarounds

Kill my app and try again.

### Configuration

.NET 6.0.5
Windows 11
x64
WPF

**Comment by jkotas** [comment]
> When this happens, I took a look at Process Explorer to look at threads and noticed that CoreClr_Shutdown is the function that is maxing out one CPU. I also noticed that there are a lot of MetaDataGetDispenser threads.

`CoreClr_Shutdown` and `MetaDataGetDispenser` symbols are bogus. They happened to be the few publicly exported methods from coreclr.dll that some of the stack stringization heuristics use when the actual symbols are missing.

You need to get proper symbols from the symbol server by [configuring Process Explorer](https://www.bing.com/search?q=Process+explorer+how+to+set+symbol+path) to make progress on this.

**Comment by TonyValenti** [comment]
Thanks @jkotas .  I set up symbols for  Process Explorer and now I have the following stack traces.  They vary slightly when I click "Refresh" so I'm going to post a few of them here:

![image](https://user-images.githubusercontent.com/13609558/168944593-c24db4e3-1b78-4d91-b994-2c0b933970f1.png)

![image](https://user-images.githubusercontent.com/13609558/168944606-88748afa-eaa7-4e6a-854f-ca2d027780d2.png)

![image](https://user-images.githubusercontent.com/13609558/168944616-692b12d5-1a84-4a7a-bdaa-1498a5b91143.png)

![image](https://user-images.githubusercontent.com/13609558/168944627-dd58fb96-c767-4a64-aa69-01629e9ce9d8.png)

![image](https://user-images.githubusercontent.com/13609558/168944642-b8c2c439-d091-4fb9-a57e-6e3e1a256f1f.png)


What should I do next?

**Comment by jkotas** [comment]
This looks like a duplicate of https://github.com/dotnet/runtime/issues/58471. The workaround is disable tiered compilation https://docs.microsoft.com/en-us/dotnet/core/runtime-config/compilation#tiered-compilation. 

https://github.com/dotnet/runtime/pull/69121 that will show up in the next .NET 6.0 servicing update has mitigation for this issue.

**Comment by TonyValenti** [comment]
Thanks @jkotas - This is exactly the issue.  Oh boy, what a complex one for your team to wade through!

Thanks to everyone who has been working to resolve that over the past year.
