### ISSUE TITLE
Some MonoTargetsTasks project references are not removed during source build

### ISSUE THREAD

**Issue by lbussell** [dotnet/runtime#69460]
We are seeing a new prebuilt package reported in source-build, `Microsoft.DotNet.CilStrip.Sources.7.0.0-beta.22214.1`.

It seems like `AssemblyStripper.csproj` is being picked up by the `**/*.csproj` pattern in `tasks.proj` and it is referencing the prebuilt:

https://github.com/dotnet/runtime/blob/f246a5a5f69e64a4a615f140f12bc395103fa428/src/tasks/tasks.proj#L2-L9

This target should instead ignore all `.csproj` files under `MonoTargetsTasks/`.

**Comment by ericstj** [comment]
cc @lambdageek @radical per https://github.com/dotnet/runtime/pull/59720

It's a bit ironic that this "source" package is treated as a "prebuilt".  I wonder if this component is needed for source build or not.

**Comment by eerhardt** [comment]
I don't believe any of the Mono workloads tasks are needed for source-build. So I think not building AssemblyStripper during source-build makes sense.

See also #60315.
