### ISSUE TITLE
[NativeAOT] System.Reflection.Tests timeout/hang

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#69476]
```
----- start Wed May 18 01:17:17 UTC 2022 =============== To repro directly: =====================================================
pushd .
chmod +rwx System.Reflection.Tests ^&^& ./System.Reflection.Tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
Running assembly:System.Reflection.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 2700 seconds and was killed
```

**Comment by jkotas** [comment]
Hit in #69468

**Comment by jkotas** [comment]
@LakshanF Looks like the System.Reflection tests are hitting intermittent hang in the CI. We either need to get to the bottom of it quickly or disabled the tests again.

**Comment by jkotas** [comment]
Hit in #69451

**Comment by jkotas** [comment]
Hit in #69469

**Comment by jkotas** [comment]
This is failing too often. Submitted https://github.com/dotnet/runtime/pull/69477

**Comment by MichalStrehovsky** [comment]
> (also, @MichalStrehovsky had some concerns with CoreCLR tests not working in Linux-arm64 (which was the swapped test run)

The edit here: https://github.com/dotnet/runtime/pull/69284#discussion_r873850320 was to the CoreCLR test leg (running tests under src/tests), not the libraries test leg (running xunit tests under src/libraries), so it didn't affect System.Reflection.Tests runs. My concern was that adding anything ARM64 in that section won't work. ARM64 testing currently only works for the libs tests and those legs are defined lower in the runtime.yaml file.

**Comment by MichalStrehovsky** [comment]
I see, so we now have a new bug for the same thing. Closing in favor of #70010...
