### ISSUE TITLE
[wasm] Blazor AOT in Azure DevOps Pipeline timing out after one hour

### ISSUE THREAD

**Issue by dkboon01** [dotnet/runtime#69479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Is there any documentation on Azure DevOps pipeline changes that are required so that pipeline successfully builds a blazor wasm project with AOT set to true?  My pipeline fails saying that it has timed out after 1 hour.   I'm wondering if it requires more time and/or more memory  If this is the wrong forum please let me know where to put this question. I am stuck.   If I turn AOT = false the pipeline is successfully.

**Comment by dkboon01** [comment]
Here is the pipeline: 
# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

  

  pool:
  vmImage: windows-latest
 
variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'

steps:


- task: UseDotNet@2
  inputs:
    version: $(dotNetVersion)
    includePreviewVersions: true


**# needed for AOT wasm tools -----> Not for sure if I need this or not?
#- task: CmdLine@2      # used for AOT
#  inputs:
#    script: 'dotnet workload install wasm-tools'**

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution:  '**/ABCBlazor/ABCBlazor.csproj'
    feedsToUse: 'select'
    vstsFeed: '9be90141-7ea0-45d0-bd9b-512dd2e3380e'
    noCache: true
     



- script: dotnet build ABCServices --configuration $(buildConfiguration)
  displayName: 'dotnet ABCServices build $(buildConfiguration)'


- script: dotnet build ABCDispatchComponents --configuration $(buildConfiguration)
  displayName: 'dotnet ABCDispatchComponents build $(buildConfiguration)'



- task: DotNetCoreCLI@2
  displayName: 'Publish app ABC Blazor'
  inputs:
    projects:   '**/ABCBlazor/ABCBlazor.csproj'
    command: publish
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'ABCAppForBlazor'

**Comment by dkboon01** [comment]
This pipeline never finishes. It timed out after an hour.   I'm using Microsoft.Authentication.WebAssembly.Msal this package to login to my blazor wasm project. I assume I need to install the wasm-tools.  Do I need to anything special in the .csproj file so that AOT skips over it and does not include it?

**Comment by radical** [comment]
You need the `wasm-tools` workload to AOT. Do you want to skip `Microsoft.Authentication.WebAssembly.Msal` because AOT is taking too long?

Can you share the build output when it is timing out?
