### ISSUE TITLE
RegexIgnoreCastTests failures on Windows 7/8.1/Nano server

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69482]
Seen in `runtime-libraries-coreclr outerloop-windows` when testing for #69480 and also for rolling runs.
Run: https://dev.azure.com/dnceng/public/_build/results?buildId=1776845&view=results
Job name: Libraries Build windows x86 Release (not sure why the job is named like this)
Test: net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69480-merge-009367f1c2d641eaba/System.Text.RegularExpressions.Tests/1/console.deb2c97c.log?helixlogtype=result

Example:
```scala
    System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.Unicode_IgnoreCase_Tests(engine: Interpreter, culture: "EN-US", options: None) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/RegexIgnoreCaseTests.cs(181,0): at System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.<>c__DisplayClass9_0.<<Unicode_IgnoreCase_Tests>g__ValidateMatch|0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/RegexIgnoreCaseTests.cs(170,0): at System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.Unicode_IgnoreCase_Tests(RegexEngine engine, String culture, RegexOptions options)
        --- End of stack trace from previous location ---
```

**Comment by jakobbotsch** [comment]
Looks like it. Strange that searching for "RegexIgnoreCastTests" does not find that issue.

**Comment by stephentoub** [comment]
> Strange that searching for "RegexIgnoreCastTests" does not find that issue.

That's because it's "Case" not "Cast" :)

**Comment by jakobbotsch** [comment]
Ugh, RegexIgnoreCas**t**Tests...
