### ISSUE TITLE
[LSG] LoggerMessage source generator generates error when using template destructuring

### ISSUE THREAD

**Issue by gingters** [dotnet/runtime#69490]
### Description

When using serilog object destructuring in a `LoggerMessage` template, the source generator won't recognize the parameter.

### Reproduction Steps

Add this log message to a partial class:

```
[LoggerMessage(2020, LogLevel.Trace, "Transporting {@Response}")]
partial void LogTransporting(object response);
```

### Expected behavior

The source generator should generate the logging method.

### Actual behavior

The source generator creates an error: `[SYSLIB1014] Template '@Response' is not provided as argument to the logging method`

### Known Workarounds

None. Using @ before the parameter name (as you would to escape reserved words) does not help.

### Configuration

.NET 6.0.300

**Comment by maryamariyan** [comment]
Looking

**Comment by maryamariyan** [comment]
fyi, as part of the bugfix in https://github.com/dotnet/runtime/issues/60968 we fixed the sample case below: 

```c#
    [LoggerMessage(EventId = 2020, Level = LogLevel.Trace, Message = "Transporting {Response}")]
    public static partial void LogTransporting(ILogger logger, string @response);
```

Where at sign goes over the method variable not the message template argument.
Wondering if it is a common scenario to have `@` as part of the message templates. Also noticed an example in https://messagetemplates.org/

**Comment by tarekgh** [comment]
This should be already fixed by https://github.com/dotnet/runtime/pull/79038
