### ISSUE TITLE
Unsafe.As being intrinsic has exposed a few JIT related issues

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#69505]
### Issue

https://github.com/dotnet/runtime/pull/68739 switched several APIs to be `intrinsic` to the JIT and have the respective IR imported directly by the JIT rather than go through inlining.

While this in general has been positive there have been a couple of issues related to `Unsafe.As` that have cropped up.

These issues don't appear to be related to the IR being "incorrect" but rather due to less spilling to locals and similar issues causing tree shapes that weren't encountered previously.

This has lead to at least one GC hole being exposed and is potentially related to other issues that have cropped up.

### Proposed "Fix"

Given that it is generally desirable for this approach to be used "long term", but the issues that crop up are flaky by nature, it may be beneficial to provide a "switch" that allows this feature to be toggled on/off.

In particular, I propose we either provide a new `COMPlus_*`  switch or `FEATURE_*` define that allows this functionality to be `on` by default for `debug`/`checked`  builds and `off` by default for `release` builds.

If a `COMPlus_*` switch were defined then users could opt-into the functionality in `release` mode and if we ever changed the default they would have an "out" if any problematic behavior shows up later in an edge case scenario.

This would allow us to continue having the feature and getting failures raised until our confidence is high enough that they have been resolved so this can be enabled in production.

**Comment by tannergooding** [comment]
CC. @jkotas. Would appreciate your feedback on this in particular and if there is a preference on direction.

**Comment by tannergooding** [comment]
The proposed switch would impact all `System.Runtime.CompilerServices.Unsafe` APIs that are treated as JIT intrinsics, not just `Unsafe.As`.

It would not impact the existing VM or inlining support that we've had for many releases.

**Comment by jkotas** [comment]
I do not think it makes sense to introduce a switch for this. We should just fix the bugs.

We can use `[MethodImpl(MethodImplOptions.NoOptimization)]` as a temporary workaround if we identify specific method that have a problem.

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.

**Comment by tannergooding** [comment]
Going to close this as per Jan's comment. Any additional issues should be addressed as they come up.
