### ISSUE TITLE
System.Text.Json.JsonException: '0xE9' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

### ISSUE THREAD

**Issue by ClementeGao** [dotnet/runtime#69502]
Due to the loss of data, I can't share it with you. Now I can only provide exception logs. I don't know how to solve this problem
can you help me? the log is in the following screenshot
![image (1)](https://user-images.githubusercontent.com/16145998/169092919-f851769a-a41b-431b-803d-c82128f24802.png)

**Comment by ClementeGao** [comment]
@HongGit @StephenMolloy @jeffhandley  the problem blcok me  if you have time  can you help me ?

**Comment by GrabYourPitchforks** [comment]
This almost certainly indicates that somebody sent Han data (Chinese, Japanese, or Korean text) without surrounding it in quotes.

For example, this JSON payload is malformed - it's missing quotes. Trying to deserialize it will result in an error similar to what you're seeing.

```txt
{
    "Message": 你好
}
```

This JSON payload is well-formed and will deserialize correctly. Note the quotes around the string.

```txt
{
    "Message": "你好"
}
```

**Comment by GrabYourPitchforks** [comment]
If you're requesting a new behavior that _System.Text.Json_ allow deserializing payload with missing quotes, I think your best bet would be to leave a comment at https://github.com/dotnet/runtime/issues/32291. That issue tracks allowing the deserializer to parse spec-nonconforming payloads.

**Comment by eiriktsarpalis** [comment]
FWIW this is not something that Json.NET supports either, for example:
```C#
string json = """{ "Message" : Hi, I'm a payload without quotes 💖 }""";
JsonConvert.DeserializeObject<object>(json); // JsonReaderException: Unexpected character encountered while parsing value: H. Path 'Message', line 1, position 14.
```
The examples listed in https://github.com/dotnet/runtime/issues/32291#issuecomment-586402938 are specifically ones that Json.NET supports, and we might want to consider surfacing them in the future for compabitility.

Honestly though, I don't believe this particular request makes the cut.
