### ISSUE TITLE
[net7][Wasm] Type.TypeInitializer.Invoke() does not run the type initializer

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#69516]
### Description

Running `Type.TypeInitializer.Invoke()` does not run the type initializer under net7, where it was under net6.

### Reproduction Steps

Considering this code:

```csharp
Console.WriteLine($"Before Test TypeInitializer");
typeof(Test).TypeInitializer.Invoke(null, null);
Console.WriteLine($"After Test TypeInitializer");

public static class Test
{
    static Test()
    {
        Console.WriteLine("Test: Type Initializer");
    }
}
```

### Expected behavior

net6 shows this:
```
Before Test TypeInitializer
Test: Type Initializer
After Test TypeInitializer
```

### Actual behavior

net7 shows this:
```
Before Test TypeInitializer
After Test TypeInitializer
```

### Regression?

Yes

### Known Workarounds

Use `System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor` instead.

### Configuration

net7 build: 58fa90be46a

### Other information

I have not tested on the desktop runtime yet.

**Comment by dakersnar** [comment]
@jkotas We think this might be VM related, can you take a look?

**Comment by jkotas** [comment]
cc @steveharter

**Comment by steveharter** [comment]
cc @BrzVlad

**Comment by SamMonoRT** [comment]
cc @BrzVlad @lambdageek -- marking this a blocking-release, considering its a regression. Assigning to @BrzVlad for tracking.

**Comment by jkotas** [comment]
It is this TODO: https://github.com/dotnet/runtime/blob/51df356ea56eab036dda4ae51557e3524f487563/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs#L805-L809

Related to https://github.com/dotnet/runtime/issues/40351
