### ISSUE TITLE
Source generated marshalling can leak unmanaged resources in the presence of exceptions

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#69529]
## Repro:
```
        [LibraryImport("test.dll", StringMarshalling = StringMarshalling.Utf16)]
        internal static partial void MyMethod([MarshalUsing(ConstantElementCount = 10)] out string[] a, [MarshalUsing(ConstantElementCount = 10)] out string[] b);
```
## Generated sources:
```csharp
...
                __b_gen_native__marshaller = new(sizeof(ushort*));
                __b_gen_native__marshaller.FromNativeValue(__b_gen_native);
                {
                    int __b_gen_native__marshaller__numElements = 10;
                    System.Span<string> __b_gen_native__marshaller__managedSpan = __b_gen_native__marshaller.GetManagedValuesDestination(__b_gen_native__marshaller__numElements);
                    System.ReadOnlySpan<System.IntPtr> __b_gen_native__marshaller__nativeSpan = System.Runtime.InteropServices.MemoryMarshal.Cast<byte, System.IntPtr>(__b_gen_native__marshaller.GetNativeValuesSource(__b_gen_native__marshaller__numElements));
                    for (int __i0 = 0; __i0 < __b_gen_native__marshaller__numElements; ++__i0)
                    {
                        global::System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller __b_gen_native__marshaller__nativeSpan____i0__marshaller = default;
                        __b_gen_native__marshaller__nativeSpan____i0__marshaller.FromNativeValue((ushort*)__b_gen_native__marshaller__nativeSpan[__i0]);
                        // !!! Let's assume that this line throws an exception (e.g. the string is too long)
                        __b_gen_native__marshaller__managedSpan[__i0] = __b_gen_native__marshaller__nativeSpan____i0__marshaller.ToManaged();
                    }
                }

                b = __b_gen_native__marshaller.ToManaged();
                __a_gen_native__marshaller = new(sizeof(ushort*));
                // !!! This line won't be executed and thus the `__a_gen_native` and all strings stored in it will leak
                __a_gen_native__marshaller.FromNativeValue(__a_gen_native); 
...
```
## Actual behavior:

If unmarshalling of `b` throws an exception, `a` unmanaged array will leak.

## Expected behavior:

Proper cleanup even in the presence of exceptions.

**Comment by jkotas** [comment]
This issue is potentially related to `GuaranteedUnmarshal` proposed in https://github.com/dotnet/runtime/issues/69403.

As part fixing this, should `FromNativeValue` and `FreeNativeValue` methods in the marshaller shape be documented as not allowed to throw exceptions?

**Comment by AaronRobinsonMSFT** [comment]
If I recall, there was a design point about assuming the marshalling code is written properly and won't throw. 

This case is easy to ignore because if the string is too long, we are either out of memory or there is some assumption from the marshaller that the string length has some specific limit. The former I would argue isn't very interesting, but I do agree the latter is something we should consider.

**Comment by AaronRobinsonMSFT** [comment]
> As part fixing this, should FromNativeValue and FreeNativeValue methods in the marshaller shape be documented as not allowed to throw exceptions?

Perhaps. I would like to discuss if there is a mechanism to address this in a performant way.

**Comment by jkotas** [comment]
Another potential case for string are string encoding errors. The string marshaller may want to throw an exception to indicate that the string encoding is invalid.

**Comment by jkoritzinsky** [comment]
The new v2 marshaller design in https://github.com/dotnet/runtime/issues/70859 addresses this issue.
