### ISSUE TITLE
[wasm][debugger] Fix class returned on evaluation of expression with "?"

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#69543]
This PR: https://github.com/dotnet/runtime/pull/69307 enabled using null-conditional operator in `onCallFrame` calls. The result is still not ideal, for evaluation of e.g. `listNull?.Count` in `EvaluateOnCallFrameTests.EvaluateNullObjectPropertiesPositive`:

current result:
TObject("System.Collections.Generic.List<int>", is_null: true)

expected result:
TNumber("int?", is_null: true)

The place where we currently return the wrong object: https://github.com/dotnet/runtime/blob/e8db4f9f1bbd6ccb629fbd7e583ff0fa4615d1de/src/mono/wasm/debugger/BrowserDebugProxy/MemberReferenceResolver.cs#L286

**Comment by thaystg** [comment]
This is fixed by the new debugger.
