### ISSUE TITLE
Assertion failed 'preciseVarTypeMap[type] != TYP_UNDEF' when dumping all functions

### ISSUE THREAD

**Issue by a74nh** [dotnet/runtime#69551]
### Description

Whilst debugging coreclr using a simple example application I wanted to dump the IR for every function. I wanted to do this to see in which functions an optimised had kicked in.

### Reproduction Steps

Arm64 Linux (not tested elsewhere).
Using a simple example test app:

`COMPlus_JitDump="*" COMPlus_TieredCompilation=0 ./bin/release/net7.0/linux-arm64/publish/corerun bin/release/net7.0/linux-arm64/example.dll`

The exact contents of example does not matter - this error occurs before the runtime gets to example.dll

### Expected behavior

The IR dumps are printed for every function executed.

### Actual behavior

```
***** BB29, STMT00041(before)
N010 (  9,  9) [000470] -A------R--                         *  ASG       int
N009 (  1,  1) [000469] D------N---                         +--*  LCL_VAR   int    V36 tmp12        d:3
N008 (  9,  9) [000207] -----------                         \--*  ADD       int
N001 (  1,  1) [000200] C----------                            +--*  LCL_VAR   int    V03 loc0         u:7 (last use)
N007 (  7,  7) [000206] -----------                            \--*  NOP       int
N006 (  7,  7) [000387] -----------                               \--*  RSH       int
N004 (  5,  4) [000425] -----------                                  +--*  HWINTRINSIC int     LeadingZeroCount
N003 (  4,  3) [000424] -----------                                  |  \--*  HWINTRINSIC long    ReverseElementBits
N002 (  3,  2) [000383] -----------                                  |     \--*  LCL_VAR   long   V33 tmp9         u:1 (last use)
N005 (  1,  2) [000386] -----------                                  \--*  CNS_INT   int    3

N001 [000200]   LCL_VAR   V03 loc0         u:7 (last use) => $1ac {$30a, int <- long}
N002 [000383]   LCL_VAR   V33 tmp9         u:1 (last use) => <l:$2d7 {HWI_Vector128_ToScalar($483, $3c8)}, c:$2d8 {HWI_Vector128_ToScalar($484, $3c8)}>
    simdTypeVN is $3c9 {
Assert failure(PID 54654 [0x0000d57e], Thread: 54654 [0xd57e]): Assertion failed 'preciseVarTypeMap[type] != TYP_UNDEF' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' during 'Do value numbering' (IL size 549; hash 0x576e6ccc; FullOpts)

    File: /home/alahay01/dotnet/runtime/src/coreclr/jit/ee_il_dll.hpp Line: 288
    Image: /home/alahay01/dotnet/conditional/bin/release/net7.0/linux-arm64/publish/corerun

[1]    54654 abort      COMPlus_JitDump="*" COMPlus_TieredCompilation=0
```

Full list of functions in the dump at the point of the error:
****** START compiling System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,int,System.Object) (MethodHash=1b5e9e9c)
****** START compiling System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,int,long):byref (MethodHash=d1234a96)
****** START compiling System.SpanHelpers:IndexOf(byref,ushort,int):int (MethodHash=576e6ccc)

### Regression?

Don't know.

### Known Workarounds

Comment out the assert on line 288 of src/coreclr/jit/ee_il_dll.hpp

    assert(preciseVarTypeMap[type] != TYP_UNDEF);

Which this done, everything dumps ok.

### Configuration

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-126-generic aarch64)

Recent HEAD of dotnet repo
6ca8c9bc0c4 2022-05-05.. Mukund Raghav.. Fixed the yp_spin_count_unit to be a factor of the original_spin_count_unit rather than a continually increasing value (#68879)

**Comment by a74nh** [comment]
Full log file attached:

[dumpf.txt](https://github.com/dotnet/runtime/files/8728676/dumpf.txt)

**Comment by JulieLeeMSFT** [comment]
cc @kunalspathak @dotnet/jit-contrib.

**Comment by kunalspathak** [comment]
@a74nh - I will investigate this, but just to unblock you, you can specify `COMPlus_JitDump=methodname` instead of specifying `*`. With `*` you are dumping for all methods which will be lot of contents.

**Comment by a74nh** [comment]
> With * you are dumping for all methods which will be lot of contents.

I had a situation where my test app was failing with wrong end result, but I didn't know which function was going wrong. So I dumped everything, and searched the output for where my changes were kicking in.

This isn't a super urgent bug, just a little annoyance to work around.

**Comment by kunalspathak** [comment]
I am able to repro this on windows/x64 machine using altjit=clrjit_universal_arm64_x64.dll and jitdump=IndexOf

**Comment by kunalspathak** [comment]
@a74nh , could you try setting `COMPlus_SIMD16ByteOnly=1` and see if that helps?

**Comment by kunalspathak** [comment]
> @a74nh , could you try setting `COMPlus_SIMD16ByteOnly=1` and see if that helps?

Actually, having that variable is only applicable when using altjit. I can still repro the problem on actual arm64 machine. The node that we are trying to dump has `gtSimdSize == 0` which I am not sure how we can get here.

The repro is simple.

```c#
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics.Arm;

class Program_69551
{
    static void Main(string[] args)
    {
        Test(1);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Test(uint v)
    {
        //Consume(BitOperations.TrailingZeroCount(v));
        Consume(ArmBase.LeadingZeroCount(ArmBase.ReverseElementBits(v)));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Consume(int a)
    {

    }
}
```

Executed on arm64 machine:

```
COMPlus_TieredCompilation=0
COMPlus_JitDump=Test
```

**Comment by kunalspathak** [comment]
Seems like we create `VNForSimdType` for HWIntrinsic https://github.com/dotnet/runtime/blob/c9d785464d0de208ad041acecf81d09a707e0aa4/src/coreclr/jit/valuenum.cpp#L9344 and for this case, the `GetNormalizedSimdBaseJitType() == TYP_UNDEF` and `simdSize == 0`. Not sure if it matters for VN algorithm, but that creates problem during dumping. @jakobbotsch , do you know? If SIMD VN is fine for HW instrinsic, the simplest fix would be to recogize if that is the case during dumping and print that instead of calling `JitType2PreciseVarType()` at https://github.com/dotnet/runtime/blob/c9d785464d0de208ad041acecf81d09a707e0aa4/src/coreclr/jit/valuenum.cpp#L6804.

**Comment by jakobbotsch** [comment]
Sorry, don't know. @tannergooding or @SingleAccretion might know whether it is expected we ever see `TYP_UNDEF` in the case above.

**Comment by SingleAccretion** [comment]
It is not expected, but also not fatal (just wastes a little bit of memory and at worst pessimizes things if we get uninitialized data there somehow).

The bug is in `vnEncodesResultTypeForHWIntrinsic` - it shouldn't return `true` for scalar HWIs such as `LeadingZeroCount`.
