### ISSUE TITLE
[System.Data.Odbc] GetSchemaTable fails with [42000 Interrupted] for x64 ODBC driver

### ISSUE THREAD

**Issue by RODevVro** [dotnet/runtime#69558]
### Description

Hi,

I have an issue with the ODBC driver on a connection to an OLAP database.  When I try to retrieve the column information from the "ExecuteReader(CommandBehavior.KeyInfo)", I get a "42000 Interrupted" exception, but if I remove the "CommandBehavior.KeyInfo", I get the tables back (without types, without size).

Unfortunately I can't provide you with an environment to reproduce as it is my client's so I can understand that it can be complicated to debug. Do you have any idea where this could be coming from & if there is a workaround or a fix that could be applied ?

Code sample :
```
const string reqSelect = "SELECT * FROM xxx";
var conStringBuilder = new OdbcConnectionStringBuilder("Dsn=XXX");

var connection = new OdbcConnection();
connection.ConnectionString = conStringBuilder.ConnectionString;
connection.Open();

using (var cmd = CreerDbCommand(connection, reqSelect))
{
    // OK without types, sizes
    var rdr = cmd.ExecuteReader();
    using DataTable schemaTable = rdr.GetSchemaTable();

    // KO
    rdr = cmd.ExecuteReader(CommandBehavior.KeyInfo);
    using DataTable schemaTable2 = rdr.GetSchemaTable();
}
```

I found a similar issue : https://github.com/dotnet/runtime/issues/40654 which could be in the same idea

Thanks

### Reproduction Steps

Use the latest version of the nugget package System.Data.Odbc
Setup a ODBC driver to an OLAP database
Use the sample code

### Expected behavior

No exception and column infos

### Actual behavior

Exception when reading column types

**Comment by roji** [comment]
@RODevVro what is the schema of the table above (just in case this is similar to #40654).

Note that this is very likely an issue in the specific ODBC driver being used... I can successfully execute GetSchemaTable with KeyInfo against SQL Server from a 64-bit .NET 6.0 program. In other words, this is likely an issue with the specific OLAP ODBC driver you're using, so I'd contact your database vendor.

**Comment by RODevVro** [comment]
Hi, thanks for your reply. The database behind is a SQL Analysis Services and I'm using a SQL Analysis Services ODBC Driver
from CData. I'll contact them so it doesn't seem to be related to this ODBC driver, sorry.
