### ISSUE TITLE
Exception when I call SslStream.AuthenticateAsClientAsync on net-6 android

### ISSUE THREAD

**Issue by TricksterCat** [dotnet/runtime#69557]
When using maui with net6-android I get an error when calling SslStream.AuthenticateAsClientAsync.
The same code through xamarin mono-android everything works correctly.

```
await tcpClient.ConnectAsync(HostEndPoint.Address, HostEndPoint.Port)

//Callback "UserCertificateValidationCallback " not being called
SslStream stream = new SslStream(tcpClient.GetStream(), true, UserCertificateValidationCallback);
var os = Environment.OSVersion;
var sslProtocol = 
    os.Platform is PlatformID.Unix || os.Platform is PlatformID.Win32NT && os.Version.Major < 10
    ? SslProtocols.Tls12 // windows 7 or android
    : SslProtocols.None; //auto

//An exception is thrown
[System.err] javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[System.err]     at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
[System.err]     at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
await stream.AuthenticateAsClientAsync(new SslClientAuthenticationOptions
{
    TargetHost = HostName,
    EnabledSslProtocols = sslProtocol, 
}, cancellationToken);
```

P.S. the host has a valid certificate.

**Comment by simonrozsival** [comment]
@TricksterCat I'm not sure why this worked in Xamarin and doesn't work anymore. It seems that your host's certificate isn't trusted by Android (the exception was thrown by the OS library, not by .NET). If your CA isn't trusted on Android by default, you can try adding its public key into the android app via [Network security config](https://developer.android.com/training/articles/security-config). Does this help?

**Comment by TricksterCat** [comment]
@simonrozsival Ok I'll try tomorrow

**Comment by TricksterCat** [comment]
Created a new project

Phone: Samsung Note 20 Ultra (sm-n985f) 
Phone API level: 30 (Android 11) 

SDK:
NETCore.App: 6.0.6
Maui.Core:6.0.408
Android:32.0.424

global.json
{
  "sdk": {
    "version": "6.0.302",
    "rollForward": "latestFeature"
  }
}

When running through Windows Machine, there are no errors, I successfully receive the "UserCertificateValidationCallback" callback.
I get an exception when I run it from my phone.

**Comment by simonrozsival** [comment]
@TricksterCat Sorry for the late response. I tested your code snippet again and I still couldn't reproduce the problem. As long as the server has valid certificate (the same as yours), a breakpoint in the callback method is hit.

Can you upload the project files so I can use exactly the same project settings and source code to test the issue? If you don't want to publish the hostname of your server, please use a different one (e.g., `github.com`, port 443) that causes the same failure.
