### ISSUE TITLE
Proposal: Introducing a JIT intrinsic for acquiring timestamps

### ISSUE THREAD

**Issue by mjsabby** [dotnet/runtime#6956]
Acquiring timestamps (``Stopwatch.GetTimeStamp``) is an important activity in many applications, including modern web services. Often breaking down an application's execution time into "scopes" aids in performance analysis and is achieved by taking timestamps at predetermined code-sites, usually interesting logical points in the applications execution.

Furthermore, often these timestamps are taken in BeginActivity/EndActivity pairs to get "regions" of code. Therefore each "region" is represented (at a minimum) with two timestamps and usually also some symbolic name to identify the activity.

An example to illustrate this pattern:

```cs
static void Foo()
{
    using (MonitoredScope.Create(nameof(Foo)))
    {
        // ...
    }
}
```

```cs
class MonitoredScope : IDisposable
{
   public static MonitoredScope Create(string activityName)
   {
       LogBegin(Stopwatch.GetTimeStamp(), activityName);
       // ...
   }

   public void Dispose()
   {
       LogEnd(Stopwatch.GetTimeStamp());
   }
}
```

Today the JIT would encounter the ``call Stopwatch.GetTimeStamp`` CIL instruction and if it inlines the method body at the call-site, the generated code would be raising a PInvoke frame and then calling into the PAL supplied function. For example, on Unix systems that would be ``SystemNative_GetTimestamp``. The PAL function defined in the CoreFX repo would then call into the OS supplied function (``clock_gettime``).

That is a total of 2 calls + the PInvoke frame. The majority of the cost is the PInvoke frame, and we could remove that if we make this an FCall in the runtime.

However, we can improve on this further if we can teach the JIT (intrinsic) to call directly into the OS supplied function, and do away with the extra call into the PAL.

Given that getting to these timestamps usually ends up being an ``RDTSC`` (or equivalent) instruction on modern OSes with modern hardware (all recent Windows machines, and I suspect quite a few Linux ones as well) + maybe some OS code it's a pretty good win if all we're adding by running on the runtime is an indirect call into the OS function which is what a non-runtime language like C++ would also achieve. You could imagine that one could take this further and provide an intrinsic for only the ``RDTSC`` instruction (and maybe that's also a valid issue to file) but I see it being significantly less portable at a proportionally higher maintenance cost.

As a final note, this will be a particularly major CPU efficiency improvement (in addition to the wall-clock time improvement) in large datacenter applications like Bing.com.
category:proposal
theme:runtime
skill-level:intermediate
cost:medium

**Comment by jakobbotsch** [comment]
I think we eventually went with optimizing the relevant APIs using things like `SuppressGCTransition` instead. Will close this, feel free to reopen if you think there's still a benefit to this.
