### ISSUE TITLE
Vector128.IsHardwareAccelerated always returns false in debugger

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#69576]
I'm using Visual Studio 17.2 using 7.0.100-preview.5.22267.11 SDK targeting 7.0.100-preview.5.22267.11 runtime.
```c#
using System.Runtime.Intrinsics;

Console.WriteLine(Vector128.IsHardwareAccelerated);
```
This writes true for me, but Vector128.IsHardwareAccelerated in the watch window (or hovering) is always true. this doesn't happen for eg., Sse2.IsSupported. 

@tannergooding

**Comment by tannergooding** [comment]
This is a simple fix. These aren't recursive where-as `Sse.IsSupported` and friends are.

I'll have a fix up shortly, just need to add a test validating things.

**Comment by tannergooding** [comment]
Closing this as a duplicate of the older https://github.com/dotnet/runtime/issues/38162
