### ISSUE TITLE
Unable to use Libraries.sln in VS

### ISSUE THREAD

**Issue by LeeMSilver** [dotnet/runtime#69584]
Windows 10 V 19.9 / Visual Studio V22.2.1

I'm trying to study the source-code for the Libraries and CoreClr. As such, I downloaded and unzipped runtime-main.zip.

I ran GenerateLibrariesSln.ps1 in the src\Libraries folder and got a message for each project that I needed to install SDK 7.0.100-preview.4.22252.9. I downloaded/installed it, and reran GenerateLibrariesSln.ps1 successfully. I renamed Libraries.src.Generated.sln -> Libraries.sln.

I cleaned the Solution by removing 4 projects that didn't load (their .csproj-files indicated they weren't supposed to load) + 1 project that is a Build-extension that caused .NuGet to emit an error.

I also added System.Private.CoreLib.Generators.csproj, which is a ProjectReference in System.Private.CoreLib.csproj.

At this point I thought Libraries.sln was clean and complete and right-clicked on Solution/Project Build Order (PBO).
I was surprised that the PBO was in the exact order of the Projects in the Solution-panel (I had expected System.Private.CoreLib.Generators and System.Private.CoreLib to be the first two).

I closed VS and re-opened it with Libraries.sln. I waited for VS to resolve references (by waiting for VS's CPU-usage to drop below 1% in TaskManager.) and got the same result creating the PBO.

I need a correct PBO to open the projects in an order that guarantees the project on which I'm working has all its references previously resolved in order that it clean-compiles.

Is there a command/script I need to run before opening the Solution? Is there a problem with the csproj-files or VS?

**Comment by LeeMSilver** [comment]
Additional info

It looks like most/all of the projects have unresolved package references to Microsoft.DotNet* components (ApiCompat, Build.Tasks.TargetFramework, GenAPI, GenFacades), and System.Threading.Tasks.Extensions. 

Note that in some projects (e.g. Microsoft.Bcl.AsyncInterfaces) the Microsoft.DotNet* package references are unresolved for netstandard2.0 and netstandard2.1, while for others (e.g. Microsoft.CSharp) the package references are unresolved without any qualifier.

It looks like VS won't correctly analyze the project dependencies to the ProjectBuildOrder until the NuGet references are resolved.

Also, some projects (e.g. Microsoft.CSharp) have References (e.g. <Reference Include="System.Collections" />) which are unresolved and which I believe should be ProjectReferences. If having References is correct, how should they be resolved?

**Comment by AaronRobinsonMSFT** [comment]
@LeeMSilver Loading in Visual Studio requires building the repo first. From the command line run `build.cmd -subset Libs+Clr`. After that, I recommend starting Visual Studio from the command line using the `build.cmd` script. This can be done using the `-vs` flag for the desired assembly.

For example, 

To load System.Private.CoreLib: `build.cmd -vs System.Private.CoreLib`

To load System.Runtime: `build.cmd -vs System.Runtime`

**Comment by ViktorHofer** [comment]
What @AaronRobinsonMSFT said. Unfortunately we require an initial root build today before you can open libraries inside VS.

> and reran GenerateLibrariesSln.ps1 successfully

That's a script that @stephentoub added to generate such big solution files. I don't know if it still works and it is probably missing the source generators as those didn't exist when the script was written. We could clean this up and offer a better way to generate a solution file for refs and source projects but it hasn't been a priority until now.

**Comment by LeeMSilver** [comment]
Thanks for the response.
Under runtime-main I found the foldersrc\.DotNet\shared\Microsoft.WindowsDesktop.App\7.0.0-preview.3.22177.1 
which seems to have the dll's that I can use to resolve Reference references. This should be sufficient for my purposes. Having a way to resolve the References means that I can examine the projects in any order; so I don't need BuildProjectOrder to work. I don't think the unresolved NuGet packages will affect me.

    On Friday, May 20, 2022, 05:16:40 PM GMT+8, Viktor Hofer ***@***.***> wrote:  
 
 


What @AaronRobinsonMSFT said. Unfortunately we require an initial root build today before you can open libraries inside VS.


and reran GenerateLibrariesSln.ps1 successfully


That's a script that @stephentoub added to generate such big solution files. I don't know if it still works and it is probably missing the source generators as those didn't exist when the script was written. We could clean this up and offer a better way to generate a solution file for refs and source projects but it hasn't been a priority until now.

**Comment by ViktorHofer** [comment]
> I need a correct PBO to open the projects in an order that guarantees the project on which I'm working has all its references previously resolved in order that it clean-compiles.

CoreLib and its generator aren't build first in order because the reference assemblies are built before which intentionally don't depend on CoreLib. You should see CoreLib in the build order after the last reference assembly is built.
