### ISSUE TITLE
[API Proposal]: add remaining APIs to complete NativeMemory set

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#69606]
### Background and motivation

With #33244 and #63547, we now have the new `NativeMemory` type exposing lowlevel building blocks to perform common operations on memory. The APIs in this type are thing wrappers over the relative C API, and they all accept raw pointers and `nuint` length as parameters. They're effectively the "correct" (or, "easy", "preferred", "modern", whatever) way to interact with raw memory going forward, especially for people trying to migrate code from C/C++.

They also remove ambiguity when having to do an operation that has otherwise multiple ways to be expressed in C#, such as clearing memory. Do I use `new Span<byte>(...).Clear()`? Do I use `Unsafe.InitBlock`? If I want to copy memory, do I use `new Span<byte>(...).CopyTo`? Do I use `Buffer.MemoryCopy`? Do I use `Unsafe.CopyBlock`? Going forward instead, it's quite easy: if you have a raw pointer, then `NativeMemory` is the way to go. Easy, no confusion, and consistent behavior for all APIs.

This proposal is about adding the "missing" APIs to `NativeMemory` to complete the set. These are:
- `memset`
- `memcopy`
- `memmove`

cc. @tannergooding 

### API Proposal

```diff
 namespace System.Runtime.InteropServices;

 public static class NativeMemory
 {
-    public static void ZeroMemory(void* ptr, nuint byteCount); // Recently approved, to be replaced by Clear for consistency
+    public static void Clear(void* ptr, nuint byteCount);
+    public static void Fill(void* ptr, nuint byteCount, byte value);
+    public static void Copy(void* source, void* destination, nuint byteCount);
 }
 
 // Existing similar methods on Array for reference
 public class Array
 {
     public static void Clear(System.Array array); 
     public static void Fill(T[] array, T value);
     public static void Copy(System.Array sourceArray, System.Array destinationArray, int length); 
 }
```

Exact names and argument order are up to discussion I assume, I used the .NET convention here but we might also want to eg. use `Memset` instead of `Fill`, etc. I guess there's arguments for both, so leaving this to FXDC.

### API Usage

Same use case scenario as where the relative C APIs would normally be used.

### Alternative Designs

Keep using different APIs scattered all over the place, with inconsistent behavior, and not all accepting `nuint` lengths.

### Risks

None, really.

**Comment by GrabYourPitchforks** [comment]
I'd propose dropping _memcpy_ and exposing only _memmove_, but otherwise LGTM. We can expose _memcpy_ in the future if there's a real hardcore scenario for it.

**Comment by AaronRobinsonMSFT** [comment]
Can't all these be done using existing APIs on `Span<T>`?

**Comment by stephentoub** [comment]
> Can't all these be done using existing APIs on `Span<T>`?

Not if you have a byteCount > int.MaxValue.

**Comment by GrabYourPitchforks** [comment]
> Can't all these be done using existing APIs on `Span<T>`?

@AaronRobinsonMSFT Kind of, but it's a bit weird without true nint support on `Span<T>`. The caller would have to create helpers to call the existing `Span<T>` methods in a loop.

**Comment by Sergio0694** [comment]
Also how would you do `memcmp` and `memcpy` with `Span<T>`?
AFAIK `Span<T>.CopyTo` is equivalent to `memmove` (as it has extra logic to handle overlaps).
As for `memcmp`, wouldn't you need some additional logic to find the first not equal `byte` and then compare it? 🤔
I guess there's also the argument of having a single, consistent "goto" set of APIs for memory manipulation.
Tanner also mentioned one of the points was also to offer thing wrappers of the underlying APIs, and to help people porting code.

**Comment by tannergooding** [comment]
Right. One benefit is that we can contract these APIs to just be calls to the CRT.

This simplifies a lot of things including when/where to call it and covers the scenario where we already have and use such APIs internally for the managed variants.

Calling into the CRT yourself is complex and potentially error prone, particularly when needing to consider various library names/versions, where APIs are split, etc.

You then have `Span<T>` for managed or small unmanaged and `NativeMemory` for large unmanaged.

**Comment by GrabYourPitchforks** [comment]
> Also how would you do memcmp and memcpy with Span<T>?

You don't need to use `Span<T>` for memcmp. It's easy enough to write yourself in a loop.

And here's memmove. It's possible over existing APIs but really inconvenient.

```cs
static void memmove(void* src, void* dest, nuint byteCount)
{
if (src == dest) { return; }
if (src > dest)
{
  while (byteCount > 0)
  {
    int thisChunkSize = (int)Math.Min(byteCount, (nuint)int.MaxValue);
    new ReadOnlySpan<byte>(src, thisChunkSize).CopyTo(new Span<byte>(dest, thisChunkSize));
    src = (void*)((byte*)src + thisChunkSize);
    dest = (void*)((byte*)dest + thisChunkSize);
    byteCount -= (nuint)thisChunkSize;
  }
} else {
  while (byteCount > 0)
  {
    int thisChunkSize = (int)Math.Min(byteCount, (nuint)int.MaxValue);
    new ReadOnlySpan<byte>(src + byteCount - thisChunkSize, thisChunkSize).CopyTo(new Span<byte>(dest + byteCount - thisChunkSize, thisChunkSize));
    byteCount -= (nuint)thisChunkSize;
  }
}
}
```

**Comment by AaronRobinsonMSFT** [comment]
> Not if you have a byteCount > int.MaxValue.
> @AaronRobinsonMSFT Kind of, but it's a bit weird without true nint support on Span<T>.

Then it would appear if we add `nint` support these methods could be done using the `Span<T>` methods, which seems like what we want users to reach for, right?

> You then have Span<T> for managed or small unmanaged and NativeMemory for large unmanaged.

This argument doesn't sit well with me. Adding `nint` support to `Span<T>` does sound like it would enable the "just use Span<T>" statement to hold. Is there a reason this wasn't done?

**Comment by tannergooding** [comment]
> Is there a reason this wasn't done?

Its a very large breaking change because every `for (int i = 0; i < span.Length; i++)` loop is now potentially broken.

We might be able to mitigate that by having `Span<T>.Length` and `Span<T>.NativeLength` where the former basically does `return checked((int)NativeLength)` and the majority of spans continue working, but it still leaves the "hole" where you don't know whether or not a given method supports large spans or not.

**Comment by tannergooding** [comment]
Likewise, `Span<T>` while good for managed isn't nearly as efficient or as optimized as the underlying CRT functions, particularly for large data.

We could certainly update them to correctly use non-temporal loads/stores and vectorized comparisons everywhere but that's quite a lot of work and there has been pushback in the past on if the long term maintenance for that is worthwhile over just having users defer to native for the "edge cases"

**Comment by jkotas** [comment]
> Span<T> while good for managed isn't nearly as efficient or as optimized as the underlying CRT functions, particularly for large data.

`Span<T>` [delegates to the CRT for large buffers](https://github.com/dotnet/runtime/search?q=MemmoveNativeThreshold) for these functions as appropriate, for the reasons you have mentioned. We handle the smaller buffers in managed code to avoid the transition cost for them. I expect we would use the exact same implementation for these APIs (ie these APIs would be one-liner wrappers of the existing worker methods used for Span.

> SetMemory

This should be called `FillMemory` for consistency with similar existing APIs.

> I'd propose dropping memcpy

+1. The undefined behavior of `memcpy` for overlapping buffers is a common source of breaks when upgrading C/C++ compilers or porting to new platforms. We do not need this breaking change farm in .NET.

I would call the API `CopyMemory` for consistency with similar existing APIs.

> CompareMemory

This is the least useful API from this set. We may want to omit it from this batch too. There are other similar APIs in terms of usefulness (e.g. `memchr`). Unclear how we are going to decide which ones to include once we get to these less frequently used ones.

**Comment by Sergio0694** [comment]
> "This should be called FillMemory for consistency with similar existing APIs."

Just to clarify, didn't we want the APIs in `NativeMemory` to have names matching the underlying C APIs as much as possible? As in, that was my understanding given that eg. the one to clear is also called `ZeroMemory` and not `ClearMemory` 🤔

Same goes for `CopyMemory` to wrap `memmove` too I guess.

**Comment by jkotas** [comment]
> As in, that was my understanding given that eg. the one to clear is also called ZeroMemory and not ClearMemory

The matching C++ API is caller `memset`. I see no similarity between `ZeroMemory` and `memset`. (There is Windows-specific `ZeroMemory` macro in Windows SDK that is `#define`d to memset. Windows SDK names are not necessarily the best prior art for .NET naming.)

Good point though. We may want to rename `ZeroMemory` to `ClearMemory` for consistency.

> Same goes for CopyMemory to wrap memmove too I guess.

All `Copy*` APIs for copying memory in .NET (Array.Copy, Span,Copy, Buffer.MemoryCopy, ...) handle overlapping buffers. I do not see a good reason for this one to be outlier.

**Comment by tannergooding** [comment]
The proposed changes make sense to me for API review.

I do think there is benefit to more closely matching the existing native names, but not enough that its worth pushing on.

**Comment by Sergio0694** [comment]
So just to recap, we should:
- Drop `memcmp` like Jan suggested.
- Drop `memcpy` like Levi and Jan suggested.
- Potentially adjust names (up to FXDC I assume since there's no consensus?).

On the naming topic, personally I think it'd be better to just stick to mirroring the native names for consistency (given we also already have `Alloc`, `Realloc` etc. instead of something more .NET-like, such as `Allocate` or whatever). That said I guess the current API set is already a bit of a mashup given that eg. we also repeat "Memory" only in some cases. For instance, we have "ZeroMemory" but not "AllocateMemory". Either way we go I think we should try to make them all consinstent, because otherwise they look a bit messy. As in, they should either all be like the C APIs, or they should be all using .NET-friendly names. Similarly, they should all repeat "Memory" in the name, after the verb, or not.

Current proposals with the above suggestions:

```csharp
namespace System.Runtime.InteropServices;

public static class NativeMemory
{
    // Maps to `memset`. Alternative name: "Fill"/"FillMemory"
    public static void SetMemory(void* ptr, byte value, nuint byteCount);

    // Maps to memmove. Alternative name: "Copy"/"CopyMemory".
    public static void MoveMemory(void* destination, void* source, nuint byteCount);
}
```

I can update the proposal in the first post if we agree to move this to FXDC and mark the proposal as ready for review 🙂

**Comment by tannergooding** [comment]
> .NET convention is to have source first on Copy methods

We have a range of this. For example `Unsafe.Copy/CopyBlock` does `destination` first since that's what IL uses.

I'd personally lean towards matching native here given its under `NativeMemory` and do `destination` first. We're in an unfortunate situation where some group of people will get this wrong likely no matter what we do.

**Comment by jkotas** [comment]
Just noticed that modern C++ has destination last in `std::copy`: https://en.cppreference.com/w/cpp/algorithm/copy

> where some group of people will get this wrong likely no matter what we do.

Yep. I think that argues for maximizing consistency within .NET and ignoring what's done elsewhere.

**Comment by GrabYourPitchforks** [comment]
> We're in an unfortunate situation where some group of people will get this wrong likely no matter what we do.

Yup. I would propose that our internal usage of this and any documentation uses named parameters. Get people - including our own devs - in the habit of doing this. Make it second nature and minimize the chance of errors.

**Comment by jkotas** [comment]
I have updated the API proposal and marked this as blocking so that we get a chance to reconsider the `ZeroMemory` name before it ships.

**Comment by sakno** [comment]
@jkotas , could you please assign this task to me? I'm already working on it in #72960

**Comment by sakno** [comment]
@teo-tsirpanis , thanks! Can I ask about some guidance from your side about implementation? I'm a bit stuck on `Fill` implementation. I see that appropriate PAL method is for Unix-like OS only: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Unix/System.Native/Interop.MemSet.cs

However, I don't see any reason why not to reuse it on other operating systems because `memset` is a part of standard C library: https://github.com/dotnet/runtime/blob/main/src/native/libs/System.Native/pal_memory.c. Moreover, the necessary function is already exported for all OSes: https://github.com/dotnet/runtime/blob/main/src/native/libs/System.Native/entrypoints.c

So from my point of view, the change is trivial: just move `Interop.MemSet.cs` to appropriate location available to all platforms. In the same time, AOT has a separate import of the function: https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/RuntimeImports.cs

What is the best way to access `memset` function?

**Comment by teo-tsirpanis** [comment]
You need to write one implementation for Windows and one for Unix, just like what we already do for the allocation APIs in `NativeMemory.Windows.cs` and `NativeMemory.Unix.cs`. On Windows we reference the standard C library through the [`Interop.Ucrtbase`](https://github.com/dotnet/runtime/tree/main/src/libraries/Common/src/Interop/Windows/Ucrtbase) class.

**Comment by jkotas** [comment]
For `Fill`, you should call `SpanHelpers.Fill<byte>`. I doubt that any CRT memset implementation would be able to beat it.

**Comment by sakno** [comment]
@jkotas , @danmoseley , FYI, I didn't find any usage of `SystemNative_MemSet` across the code base. The import declared incorrectly and source generator cannot generate the code for it. Moreover, it is not a part of compilation item in `System.Private.CoreLib.Shared.projitems`. Probably, it can be removed in future.

**Comment by jkotas** [comment]
> `SystemNative_MemSet` 

Could you please delete it as part of your PR?

**Comment by sakno** [comment]
@jkotas , sure, no problem.

**Comment by tannergooding** [comment]
> I doubt that any CRT memset implementation would be able to beat it.

@jkotas, I'd actually expect for larger buffers that the `CRT` implementation may report measurably better still.

Most of the CRT implementations take into account alignment, non-temporal loads/stores, and can use `rep stos` where it's faster.

However, given that being in a P/Invoke or having data pinned for that long can have negative impact on the GC and that the transition cost/call overhead is high for small data, I expect we want to have some of it handled in managed at least.

---------------------------

The Win x64 implementations which are source available (but not OSS licensed) are here: `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\crt\src\x64`. The cutoffs it uses are:
* Less than 16-bytes - use GPR
* 16-32 bytes use 1-2 128-bit SIMD stores, possibly overlapping
* 33-8k bytes use 256-bit or 128-bit SIMD stores
* 8k-256k use `rep stos` if available, else 256-bit or 128-bit SIMD stores
* Greater than 256k use `non-temporal`

Given we have `Vector128.StoreUnsafe` and `Vector128.StoreAlignedNonTemporal` as a general xplat APIs, we could (maybe for .NET 8) have a single implementation that nicely supports x64 and Arm64 without needing to make it overly advanced. We likewise could add minimal handling in the JIT to ensure that small copies/fills (at least <= 32 bytes) are directly inlined. Optimizing x64 and Arm64 to use the respective `rep stos`/`cpymx` instructions where supported (avoiding the calls entirely and deferring to the optimized CPU impls).

**Comment by jkotas** [comment]
Yeah, the current impl is probably leaving some perf of the ground for very large sizes. 

> cpymx

I can't wait for this to become mainstream hw feature.

**Comment by sakno** [comment]
@jkotas , what is the strategy for the current implementation? We can continue to use `SpanHelpers` or add optimizations for small sizes + fallback to CRT functions instead.

**Comment by jkotas** [comment]
Use SpanHelpers. 

The potential future optimizations should be done in SpanHelpers so that all callers of SpanHelpers benefit.
