### ISSUE TITLE
[API Proposal]: More helper methods for exception types

### ISSUE THREAD

**Issue by hrrrrustic** [dotnet/runtime#69637]
### Background and motivation

A few more helper methods that can replace a lot of boring and copy-paste `if` checks in dotnet/runtime and user code as well.
I believe that this one and #69590 will cover all possible helpers 😸 

### API Proposal

```C#
public class FileNotFoundException
{
    public static void ThrowIfNotExists([NotNull] string? path) {}
}

public class DirectoryNotFoundException
{
    public static void ThrowIfNotExists([NotNull] string? path) {}
}

public class NotSupportedException
{
    public static void ThrowIf(bool condition, string? message = null) {}
}

public class InvalidOperationException
{
   public static void ThrowIf(bool condition, string? message = null) {}
}
```

### API Usage

`FileNotFoundException`

https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Diagnostics.FileVersionInfo/src/System/Diagnostics/FileVersionInfo.cs#L274-L277

I also saw weird code like this
```C#
public void SomeIORelatedMethod(string path)
{
    if (!new FileInfo(path).Exists)
        throw new FileNotFoundException();
}
```

`DirectoryNotFoundException` exactly same as previous, `File.Exists` -> `Directory.Exists`, `new FileInfo` -> `new DirectoryInfo`

`NotSupportedException`
https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Net.Mail/src/System/Net/DelegatedStream.cs#L55-L61

There are 15 more absolutely same checks only in this file. Widely used in `Stream` and `Http` related classes

`InvalidOperationException`
I think the only Enumerator types in /runtime have more than thousand lines of code like this
https://github.com/dotnet/runtime/blob/6ca8c9bc0c4a5fc1082c690b6768ab3be8761b11/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L1152-L1155

**Comment by dakersnar** [comment]
This seems worth considering. @tannergooding do you see anything additional needed for this proposal, or know of anyone else I should tag for opinions?

**Comment by stephentoub** [comment]
The helpers on the argument exceptions, object disposed, etc. are valuable because they're used _everywhere_. The ones proposed here would seem to have orders of magnitude use. I'm skeptical they're worth it. They're also more likely to need a cudtomized error message, and in the case of not supported, be used in situations where control flow would still require a separate throw or return.

**Comment by jkotas** [comment]
> string? message = null

Also, customizing message like this is inefficient. This pattern requires the message to be prepared even when the check passes.

**Comment by hrrrrustic** [comment]
After doing more work on #69590 agree that `FileNotFoundException`, `DirectoryNotFoundException` and `NotSupportedException` are not too commonly used. 

Suggesting to discuss only `InvalidOperationException`



> > string? message = null
> 
> Also, customizing message like this is inefficient. This pattern requires the message to be prepared even when the check passes.

`WriteIfInterpolatedStringHandler` should fix this?

**Comment by hrrrrustic** [comment]
Also ready to do some initial replacements for /runtime the same way as for #69590

**Comment by jkotas** [comment]
> WriteIfInterpolatedStringHandler should fix this?

I do not think that it would fix the efficiency problem.

 Here is a random example from the repo:
```
            if (args.PropertyName == "Nested")
                throw new InvalidOperationException(SR.DataDom_DataSetNestedRelationsChange);
```
How would you transform this using the proposed API such that `SR.DataDom_DataSetNestedRelationsChange` is fetched only when the condition is true?

**Comment by stephentoub** [comment]
You'd have to have something like:
```C#
InvalidOperationException.ThrowIf(args.PropertyName == "Nested", $"{SR.DataDom_DataSetNestedRelationsChange}");
```
which would get compiled as:
```
var h = new ThrowIfInterpolatedStringHandler(1, 0, args.PropertyName == "Nested", out bool shouldThrow);
if (shouldThrow) 
{
    h.AppendFormatted(SR.DataDom_DataSetNestedRelationsChange);"
}
InvalidOperationException.ThrowIf(ref h) ;
```
and while that does avoid accessing SR if it won't throw, it also adds way more code on the non-throwing path than the simple comparison we started with. It is not a good tradeoff, nor particularly ergonomical, and not something we'd end up using in the core libraries.

**Comment by hrrrrustic** [comment]
Yeah, that doesn't look good enough, thanks
