### ISSUE TITLE
[wasm][debugger] Support complex expressions with null-condition

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#69640]
Complex expressions that use null-conditional operator fail in the debugger. Try to make sure that issue: https://github.com/dotnet/runtime/issues/69639 is fixed first before starting this one.

Add `tc?.memberList[0]` and similar cases to `EvaluateNullObjectPropertiesPositive` and some negative cases, e.g.  `tcNull?.memberListNull[0]` to `EvaluateNullObjectPropertiesNegative`.

**Comment by thaystg** [comment]
This is fixed by the new debugger.
