### ISSUE TITLE
NetworkStream blocks on CopyTo from it

### ISSUE THREAD

**Issue by EduardoLemos567** [dotnet/runtime#69650]
### Description

A NetworkStream from a TcpClient will block if you call CopyTo (even with DataAvailable)

>var memory_stream = new MemoryStream();
tcp_client.GetStream().CopyTo(memory_stream ); // <- will block

[https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,98ac7cf3acb04bb1,references](url)
From the reference it uses a while Read which blocks on the last loop:
>byte[] buffer = new byte[bufferSize];
            int read;
            while ((read = Read(buffer, 0, buffer.Length)) != 0)
                { destination.Write(buffer, 0, read); }

Read wont return if there's no data to receive. 
Documentation says nothing about that.

### Reproduction Steps

>var memory_stream = new MemoryStream();
tcp_client.GetStream().CopyTo(mstream); // <- will block

### Expected behavior

Copy all NetworkStream's content into destination's stream and return, without blocking.

### Actual behavior

Blocks when calling CopyTo from a connected NetworkStream.

### Known Workarounds

Can use Read instead (Only if there's DataAvailable).

### Configuration

.NET Standard 2.1 (Unity)
Windows x64

### Other information

Either fix the CopyTo to check for DataAvaliable every loop or make the Read return even without data, returning zero bytes read.

**Comment by stephentoub** [comment]
CopyTo copies until the stream has no more data available and won't have any more available, meaning Read returns 0. With a NetworkStream, that will only happen once the remote closes its sending end and all data has been consumed. What you're seeing is by design and the expected behavior.

**Comment by EduardoLemos567** [comment]
That's a really strange use case: block my code until the other endpoint close the socket, otherwise your program is stuck forever awaiting, looping and copying (Pratically hostage of the other endpoint).


Anyways, could the documentation on NetworkStream.Read at least inform that it WILL ALWAYS block if there's no data available. As it is, there's no such information anywhere in the page.

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.read?view=net-6.0
> Remarks
This method reads data into buffer and returns the number of bytes successfully read. The Read operation reads as much data as is available, up to the number of bytes specified by the size parameter.

In the examples we get a suggestion to use DataAvailable, but the method will only work correctly if you check before blocking yourself out.

> Examples
The following code example uses [DataAvailable](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.dataavailable?view=net-6.0) to determine if data is available to be read. If data is available, it reads from the [NetworkStream](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream?view=net-6.0).

**Comment by stephentoub** [comment]
> That's a really strange use case

It's actually not.  It's very common to want to read all the data from a stream, e.g. read the whole file a server sends.

> Read at least inform that it WILL ALWAYS block if there's no data available

This is the contractual behavior of Stream.Read in general:
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0
"The implementation will block until at least one byte of data can be read, in the event that no data is available. [Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0) returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file)."

**Comment by GSPP** [comment]
@EduardoLemos567 Be aware, that `DataAvailable` returns you how much data is currently available for reading without blocking. This is not necessarily all the data that the remote side has sent. For example, data might currently be in transit and arrive shortly after.

Using `DataAvailable` is almost always a mistake. The code sample from the documentation is incorrect. In fact, it is demonstrating precisely how to misuse `DataAvailable`.

An effort is underway to clean up the documentation:

- https://github.com/dotnet/dotnet-api-docs/issues/7609
