### ISSUE TITLE
[API Proposal]: WebSockets over HTTP/2

### ISSUE THREAD

**Issue by greenEkatherine** [dotnet/runtime#69669]
### Background and motivation

Currently we are supporting WebSockets over HTTP/1.1 only. For WebSockets over HTTP/2 the protocol is quite different and described by [RFC #8441]( https://datatracker.ietf.org/doc/html/rfc8441). It is already [supported by Chrome](https://wpt.fyi/results/websockets/opening-handshake/002.html%3Fwpt_flags%3Dh2?label=experimental&label=master&aligned) and there are an interest from YARP and [ASP.NET partners](https://github.com/dotnet/aspnetcore/issues/7801). The main improvement is that supporting WebSockets over HTTP/2 will give advantage of multiplexing connection.

### API Proposal

```csharp
    // EXISTING
    class ClientWebSocket : WebSocket
    {
        // EXISTING
        public Task ConnectAsync(Uri uri, CancellationToken cancellationToken);
        // NEW
        public Task ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken);
    }

    // EXISTING
    class ClientWebSocketOptions
    {
        // NEW
        public System.Version HttpVersion { get { throw null; } 
            [System.Runtime.Versioning.UnsupportedOSPlatformAttribute("browser")]
            set { } };
        public System.Net.Http.HttpVersionPolicy HttpVersionPolicy { get { throw null; } 
           [System.Runtime.Versioning.UnsupportedOSPlatformAttribute("browser")]
           set { } };
    }
    
    class HttpMethod : IEquatable<HttpMethod>
    {
        // EXISTING
        // internal static HttpMethod Connect { get { throw null; } }
        // NEW
        public static HttpMethod Connect { get { throw null; } }
    }

    class HttpRequestHeaders : HttpHeaders
    {
        public string? Protocol { get { } set { } };
    }

```

### API Usage

```csharp
var handler = new SocketsHttpHandler();

ClientWebSocket ws = new();
ws.Options.HttpVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher;
ws.Options.HttpVersion = HttpVersion.Version20;

ws.ConnectAsync(uri, new HttpMessageInvoker(handler), cancellationToken);

HttpRequestMessage request = new(HttpMethod.Connect, server.Address);
request.Headers.Protocol = "websocket";
```
### Notes

- `HttpVersion` and `HttpVersionPolicy` in `ClientWebSocketOptions` are similar to `HttpClient`'s property. `ClientWebSocketOptions` for browser is a class with completely different properties, so the new properties don't affect it.

- Providing an external handler to `ClientWebSocket` is important because it enables advantage of HTTP/2 multiplexing by reusing the same handler for other ordinary HTTP/2 streams. Generic handler `HttpMessageInvoker` in ConnectAsync is a better alternative than `SocketsHttpHandler`. There is no need to check that it is `SocketsHttpHandler` but it should be able to handle WebSocket requests and it is up to the user who provides it.

- The property for the `:protocol` header in `HttpRequestHeaders` is required because we need to guarantee that pseudo headers are appeared before all regular headers based on [spec](https://datatracker.ietf.org/doc/html/rfc9113#section-8.3).

### Other alternatives considered, but rejected:

- Pass a low-level `SocketsHttpHandler` instead of `HttpMessageInvoker`.
- Only one property `HttpVersion` if we do not require downgrade handling. In that case we rely on the version the user provides.

### Risks

Adding new fields might increase memory usage.

**Comment by greenEkatherine** [comment]
## Internal Changes

#### `ClientWebSocket`
To make downgrade for WebSocket from HTTP/2 to HTTP/1.1 possible we need to add additional header with the key because we cannot generate it later in `HttpClient`. Other headers can be easily added and renamed to construct HTTP/1.1 WebSocket connection request from HTTP/2 ws request.
HTTP/2 example:
![image](https://user-images.githubusercontent.com/19972657/169782477-8c0fa703-5fe7-4d88-bea4-6fa0b7146eed.png)
HTTP/1.1 example:
![image](https://user-images.githubusercontent.com/19972657/169782561-8bbfc168-318a-4ba1-922b-9b49654ef135.png)

#### `HttpConnectionPool`
Since YARP is using SocketsHttpHandler directly, we need to handle downgrade (if we decide to allow it) inside the `HttpConnectionPool`. It will check the new setting ID of the `Http2Connection` EnableConnect -- based on the server response.   

To make things easier we also should consider the new property `IsWebSocketRequest` of `HttpRequestMessage`. It will check headers once to confirm that it is a websocket request (either h1 or h2) and we will not need to do it few times during downgrade.

**Comment by stephentoub** [comment]
> public System.Version DefaultRequestVersion { get { throw null; } set { } };
> public System.Net.Http.HttpVersionPolicy DefaultVersionPolicy { get { throw null; } set { } };

Why "default"? We typically use that for statics providing a default value for any instance, but that's apparently not the case here. 

>         public Task ConnectAsync(Uri uri, CancellationToken cancellationToken, SocketsHttpHandler sharedHandler);

This is concerning. It ties ClientWebSocket to the underlying implementation that should be used. ClientWebSocket has historically used HttpWebRequest, WinHttpHandler, and SocketsHttpHandler, and even today has a browser-based implementation for wasm.

**Comment by CarnaViire** [comment]
`RequestVersion` and `VersionPolicy` for connect request might look better as a part of `ClientWebSocketOptions`. But we might also want to have an additional `HttpVersion` property on `ClientWebSocket` itself if we support downgrade (so we could know what exactly was established)

**Comment by MihaZupan** [comment]
> It will check the new setting ID of the Http2Connection EnableConnect

Can you elaborate on what you meant here?

> To make downgrade for WebSocket from HTTP/2 to HTTP/1.1 possible we need to add additional header with the key because we cannot generate it later in HttpClient. Other headers can be easily added and renamed to construct HTTP/1.1 WebSocket connection request from HTTP/2 ws request.

Would the downgrade be handled by the `WebSocket` layer (i.e. calling into the handler multiple times)?
Or did you mean that Websockets would be a special case the handler recognized to adapt headers as needed?

**Comment by CarnaViire** [comment]
> Would the downgrade be handled by the WebSocket layer (i.e. calling into the handler multiple times)?
Or did you mean that Websockets would be a special case the handler recognized to adapt headers as needed?

I believe both are considered, but for YARP it will be better if it was handled by HTTP layer

**Comment by greenEkatherine** [comment]
I agree with @stephentoub and @CarnaViire suggestions to rename policy and version properties and move it into `ClientWebSocketOptions`:
```csharp
    // EXISTING
    class ClientWebSocketOptions
    {
        // NEW
        public System.Version RequestVersion { get { throw null; } set { } };
        public System.Net.Http.HttpVersionPolicy VersionPolicy { get { throw null; } set { } };
    }
```

Would using `HttpClient` be better from that perspective?
> > ```
> >     public Task ConnectAsync(Uri uri, CancellationToken cancellationToken, SocketsHttpHandler sharedHandler);
> > ```
> 
> This is concerning. It ties ClientWebSocket to the underlying implementation that should be used. ClientWebSocket has historically used HttpWebRequest, WinHttpHandler, and SocketsHttpHandler, and even today has a browser-based implementation for wasm.

Providing an external handler is a keypoint here because in that case we are able to take advantage of HTTP/2 multiplexing by reusing the same handler for other ordinary HTTP/2 streams.

**Comment by greenEkatherine** [comment]
> > It will check the new setting ID of the Http2Connection EnableConnect
> 
> Can you elaborate on what you meant here?

Based on the https://datatracker.ietf.org/doc/html/rfc8441#section-3 we should add a new SETTINGS parameter that a server sends to a client. My suggestion is to add a new property into `Http2Connection` to indicate this setting, so the `HttpConnectionPool` would be able to check its value of a connection and perform downgrade if needed.

**Comment by Tratcher** [comment]
> > ```
> >     public Task ConnectAsync(Uri uri, CancellationToken cancellationToken, SocketsHttpHandler sharedHandler);
> > ```
> 
> This is concerning. It ties ClientWebSocket to the underlying implementation that should be used. ClientWebSocket has historically used HttpWebRequest, WinHttpHandler, and SocketsHttpHandler, and even today has a browser-based implementation for wasm.

It should at least be a HttpMessageInvoker.

**Comment by greenEkatherine** [comment]
One more API change: `HttpMethod.Connect` is internal but to construct external ws request (i.e. in YARP) it should be public:

```diff
class HttpMethod : IEquatable<HttpMethod>
{
-        internal static HttpMethod Connect { get { throw null; } }
+        public static HttpMethod Connect { get { throw null; } }
}
```
However, we need somehow allow its external usage for websockets only.

**Comment by MihaZupan** [comment]
The user can still create the method with `new HttpMethod("CONNECT")`, but I don't see a reason we shouldn't just expose the property. The comment about it in source seems incorrect - you should be able to use it [directly](https://github.com/dotnet/runtime/issues/69595#issuecomment-1132805602) too.
https://github.com/dotnet/runtime/blob/fff4ff0913a2396cfae61c701f2b59ffe5e27b49/src/libraries/System.Net.Http/src/System/Net/Http/HttpMethod.cs#L67-L68

**Comment by greenEkatherine** [comment]
Next steps from team discussion:

1. Check how the new API are compatible with other handlers: 

- what is expected to happen in browser environment (e.g. mark is as unsupported so it throws PNSE and gets highlighted by the analyzer);
- what will happen if you feed this "extended connect" request into HttpClient that has WinHttpHandler underneath;

2. Discuss alternative overloading of `ClientWebSocket.ConnectAsync` with @stephentoub (`HttpMessageInvoker` or `HttpMessageHandler` or wait until `HttpClient.Shared` is implemented)

**Comment by greenEkatherine** [comment]
> I think HttpRequestMessage needs a new Protocol field to represent the new pseudo header. WebTransport also uses this field.

It would be great, I can reuse it to check if it's a WebSocket request.

**Comment by greenEkatherine** [comment]
To sum up current API proposal:
```csharp
    // EXISTING
    class ClientWebSocket : WebSocket
    {
        // EXISTING
        public Task ConnectAsync(Uri uri, CancellationToken cancellationToken);
        // NEW
        public Task ConnectAsync(Uri uri, SocketsHttpHandler sharedHandler, CancellationToken cancellationToken);
    }

    // EXISTING
    class ClientWebSocketOptions
    {
        // NEW
        public System.Version RequestVersion { get { throw null; } set { } };
        public System.Net.Http.HttpVersionPolicy VersionPolicy { get { throw null; } set { } };
    }
    
    class HttpRequestMessage : System.IDisposable
    {
        // NEW
        public System.Version Version { get { } set { } }
    }

    class HttpMethod : IEquatable<HttpMethod>
    {
        // EXISTING
        internal static HttpMethod Connect { get { throw null; } }
        // NEW
        public static HttpMethod Connect { get { throw null; } }
    }
```

**Comment by Tratcher** [comment]
> 2\. Discuss alternative overloading of `ClientWebSocket.ConnectAsync` with @stephentoub (`HttpMessageInvoker` or `HttpMessageHandler` or wait until `HttpClient.Shared` is implemented)

HttpMessageInvoker should be easier for customers to use than HttpMessageHandler, they likely already have an HttpClient instance that they want to share with. Otherwise they have to hold onto an HttpMessageHandler and share that around as well.

**Comment by Tratcher** [comment]
> 4\. `Protocol` property looks excessive at this point, should be enough to add header into the collection.

The request header collection doesn't allow headers that start with ':' like ':protocol'. Will that be changed, or will this header be special cased?

**Comment by Tratcher** [comment]
> 3\. The proper place to handle downgrade seems to be inside ClientWebSocket because otherwise we need to put a lot of ws-specific information inside HttpClient (like security key generation).

What does the downgrade flow look like? YARP will also need to implement this.
1. Make an h2 CONNECT request
1. It fails with some error (How to programmatically determine the error is about missing h2 Extended CONNECT support?)
1. Retry with h1 Upgrade

**Comment by greenEkatherine** [comment]
> The request header collection doesn't allow headers that start with ':' like ':protocol'. Will that be changed, or will this header be special cased?

I tried to add this header for test purposes and didn't see issues with request. Also, we have ':authority' header there, is there any difference?

> 
> What does the downgrade flow look like? YARP will also need to implement this.
> 
> 1. Make an h2 CONNECT request
> 2. It fails with some error (How to programmatically determine the error is about missing h2 Extended CONNECT support?)
> 3. Retry with h1 Upgrade

In case of failed h2 CONNECT request `HttpClient` will return `HttpRequestException`. Should we consider different type of exception or clear error message would be enough?

**Comment by Tratcher** [comment]
> > What does the downgrade flow look like? YARP will also need to implement this.
> > 
> > 1. Make an h2 CONNECT request
> > 2. It fails with some error (How to programmatically determine the error is about missing h2 Extended CONNECT support?)
> > 3. Retry with h1 Upgrade
> 
> In case of failed h2 CONNECT request `HttpClient` will return `HttpRequestException`. Should we consider different type of exception or clear error message would be enough?

An error message is insufficient for targeted programmatic retries. There needs to be a unique derived exception type or some programmatically accessible state on the exception so we can identify the failure as the missing Extended CONNECT server setting (or lack of H2 ALPN?). We could take advantage of the Exception.Data collection if you don't want to add new public API.

**Comment by MihaZupan** [comment]
> We could take advantage of the Exception.Data collection if you don't want to add new public API

There is some related discussion in https://github.com/dotnet/runtime/issues/43239#issuecomment-1125131300 about extending the exception with protocol errors.

**Comment by stephentoub** [comment]
No other header has a property on HttpRequestMessage.  If we really want/need a dedicated property, shouldn't it be on one of the headers collections, where the other strongly-typed headers live?

**Comment by Tratcher** [comment]
```
HEADERS + END_HEADERS
:method = CONNECT
:protocol = websocket
:scheme = https
:path = /chat
:authority = server.example.com
sec-websocket-protocol = chat, superchat
sec-websocket-extensions = permessage-deflate
sec-websocket-version = 13
origin = http://www.example.com
```

`:protocol` is not a regular HTTP header, it's an h2 pseudo header. All other pseudo headers (method, scheme, path, authority) are derived from properties on the HttpRequestMessage. The same goes for `:status` on the HttpResponseMessage.

**Comment by stephentoub** [comment]
Even so, I think it best maps to the HttpClient headers object model by being a part of the headers, e.g. request.Headers.Protocol rather than request.Protocol.  I also like that doing so hides it a bit for HTTP/1.1 where it's irrelevant.

**Comment by greenEkatherine** [comment]
Team reached agreement, updating the proposal and switching it to ready-for-api-review.

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Net.WebSockets
{
    public partial class ClientWebSocket : WebSocket
    {
        // Existing
        // public Task ConnectAsync(Uri uri, CancellationToken cancellationToken);
        public Task ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken);
    }

    public partial class ClientWebSocketOptions
    {
        public Version HttpVersion { get; [UnsupportedOSPlatform("browser")] set; };
        public HttpVersionPolicy HttpVersionPolicy { get; [UnsupportedOSPlatform("browser")] set; };
    }
}
namespace System.Net.Http
{
    public partial class HttpMethod
    {
        public static HttpMethod Connect { get; }
    }
}
namespace System.Net.Http.Headers
{
    public partial class HttpRequestHeaders : HttpHeaders
    {
        public string? Protocol { get; set; };
    }
}
```
