### ISSUE TITLE
Using Vector apis within S.P.CoreLib

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#6967]
It would be super useful to have a version of `Vector<T>` for use in S.P.CoreLib. Many of the String functions look like they could benefit from vectorization, in addition to other hotspots like `UTF8Encoding.Get{Bytes,ByteCount,Chars,CharCount}`, etc. Unfortunately, when I tried adding `Vector` to CoreLib after the discussion in dotnet/coreclr#6627, I got confused-- looks like from [this code](https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/methodtablebuilder.cpp#L1241), checking for `Vector` is completely disabled for crossgen, which makes sense since its size has to be determined at runtime. So if `Vector` is to be moved here, it seems like we would somehow have to skip JIT compiling it... I believe @jkotas mentioned somewhere `[BypassNGenAttribute]` could be used to do this, by I haven't tried it yet.

Moved from dotnet/coreclr#6627

**Comment by tannergooding** [comment]
Going to close this. `Vector<T>` now lives in S.P.Corelib and there are new types, `Vector64<T>`, `Vector128<T>`, and `Vector256<T>` which can be used for more fine grained optimizations.
