### ISSUE TITLE
Compiler error when publishing a blazor wasm (MonoAOTCompiler: Unable to compile method 'bool System.DateTimeParse:Lex)

### ISSUE THREAD

**Issue by ahmed-salem-me** [dotnet/runtime#69671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I publish a blazor wasm app, with AOT, and using .net 7.0.100-preview.4.22252.9
I get the following error, then the publishing kinda freezes at this point.
```
MonoAOTCompiler: Unable to compile method 'bool System.DateTimeParse:Lex (System.DateTimeParse/DS,System.__DTString&,System.DateTimeToken&,System.DateTimeRawInfo&,System.DateTimeResult&,System.Globalization.DateTimeFormatInfo&,System.Globalization.DateTimeStyles)' due to: 'Invalid IL code in System.DateTimeParse:Lex (System.DateTimeParse/DS,System.__DTString&,System.DateTimeToken&,System.DateTimeRawInfo&,System.DateTimeResult&,System.Globalization.DateTimeFormatInfo&,System.Globalization.DateTimeStyles): IL_09c6: nop       
 assembly:<unknown assembly> type:<unknown type> member:(null)'.
Mono Ahead of Time compiler - compiling assembly 
```

### Expected Behavior

publish succeeds.

### .NET Version

7.0.100-preview.4.22252.9

### Anything else?

VS 2022 17.2.1

C:\Users\ams>dotnet --info
.NET SDK:
 Version:   7.0.100-preview.4.22252.9
 Commit:    6bc31786a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.4.22252.9\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.4.22229.4
  Architecture: x64
  Commit:       9c37a3b3eb

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.4.22252.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.4.22251.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.4.22229.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.4.22229.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by radical** [comment]
cc @vargaz @maraf

**Comment by radical** [comment]
Could you please share the log file? you can add `-bl` to the command line to build. And attach the generated `msbuild.binlog`.

**Comment by ahmed-salem-me** [comment]
[msbuild.binlog.zip](https://github.com/dotnet/runtime/files/8763760/msbuild.binlog.zip)
@radical , hope this helps

**Comment by radical** [comment]
> [msbuild.binlog.zip](https://github.com/dotnet/runtime/files/8763760/msbuild.binlog.zip)

This doesn't include the publishing.

> just to confirm I do not get errors while building

You get errors during publish, correct? The AOT compilation step runs during publishing. Could you please share the binlog from publishing?

If the errors are not during publishing, then can you share the full output that you see?

**Comment by ahmed-salem-me** [comment]
@radical , can you plz tell me how to get the msbuild.binlog when I publish? what command I need to use?

**Comment by radical** [comment]
Adding `-bl:msbuild.binlog` should work. What did it fail with? If it was a build error, then can you attach the generated msbuild.binlog?
