### ISSUE TITLE
Caching lambda expressions used to manipulate objects using reflection

### ISSUE THREAD

**Issue by ekolis** [dotnet/runtime#6968]
Sorry if this is the wrong place to suggest this; I've never tried to contribute to .NET in this way before!

Anyway, in a project of mine I wrote a serializer that relied heavily on reflection, and it was horribly slow. However I was able to speed it up quite a bit by creating, compiling, and caching a lambda expression for each property getter and setter of each class I was serializing. I was thinking something like this could be built into the CLR, to make reflection much faster. I don't know what this does to memory usage, but perhaps at least there could be a static flag to set on some class somewhere, or a core library which does what I was doing in case anyone needs it?

**Comment by steveharter** [comment]
The current plan of record for 5.0 is to provide new APIs to support faster ways to call getters, setters and constructors which a serializer would need to do. The new APIs are covered by https://github.com/dotnet/runtime/issues/23716. Using expressions doesn't support AOT scenarios so it is not a path we want to invest in (at least for serializers).

A discussion around mechanisms to call getters, setters and constructors is discussed in the design doc at https://github.com/dotnet/designs/pull/113.
