### ISSUE TITLE
Track removing workaround to not use pthread robust mutexes for named mutexes on arm32/arm64 Linux

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#69688]
- Issue was in glibc as described here: https://github.com/dotnet/runtime/issues/6014#issuecomment-227363925
- Issue was fixed in glibc 2.24 according to https://sourceware.org/bugzilla/show_bug.cgi?id=20263#c9
- Workaround in named mutex implementation: https://github.com/dotnet/runtime/blob/fdcedd873ddfa9f639f64481652d1f9c258e37b1/src/coreclr/pal/src/include/pal/mutex.hpp#L123-L124
- There still appear to be some supported Linux distro versions that use a glibc version less than 2.24. This issue is to track removing the workaround above once all supported distros start using glibc 2.24 or greater. Also need to ensure that the use cases in https://github.com/dotnet/runtime/issues/6014 are not affected.

**Comment by janvorli** [comment]
@kouvel Starting with #68561, we are now building our binaries on Ubuntu 18.04, so the minimum supported glibc is 2.27.

**Comment by kouvel** [comment]
I see, thanks @janvorli. I figure that also means that CentOS 7 will also require glibc >= 2.27 for .NET 7, is that correct? If so, I think we can go ahead and undo the workaround.
