### ISSUE TITLE
W^X concerns with C++/CLI

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#69691]
@jkoritzinsky:
We create an executable heap with this code https://github.com/dotnet/runtime/blob/c1b153affb8a4fafe494663600bdd80b16289b38/src/native/corehost/ijwhost/ijwhost.cpp#L117 

and then write to the data on that heap here: 

https://github.com/dotnet/runtime/blob/c1b153affb8a4fafe494663600bdd80b16289b38/src/native/corehost/ijwhost/ijwthunk.cpp#L62 

@janvorli:
Since the host cannot use coreclr PAL or coreclr itself, we’ll need to have a separate implementation of the necessary stuff for it. It seems that the thunks are just created at the initialization time and never changed again. We could possibly just allocate the block of thunks with page granularity as RW and then switch them to RX after they are initialized. But we would waste part of the last page allocated for the thunks. An outstanding question is, how many of these thunks we have and whether the waste would be significant. Perhaps we could reuse the coreclr minipal in the host and use the double mapping implementation. Since the minipal is a native piece of code that uses standard platform headers / libraries, it seems it would work too.

Related: https://github.com/dotnet/runtime/issues/50391 and https://github.com/dotnet/runtime/pull/69672

/cc @dotnet/interop-contrib

**Comment by agocke** [comment]
Closing until we get some signal that this is blocking.
