### ISSUE TITLE
Audit and cleanup the generic math API docs

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#69694]
The generic math APIs have undergone several iterations. It is important that they get audited and cleaned up before we ship.

One example of a doc comment that needs cleanup is: https://github.com/dotnet/runtime/pull/69651#discussion_r879810506

**Comment by tannergooding** [comment]
> Are generic math interfaces mainly meant for representing numeric types within the BCL? Or, are they expected to be implemented by third party?

It is expected that some third party libraries will also provide their own numeric types and be able to participate.

> They have a lot of members, and we may potentially add more when we introduce more IEEE754-2019 operations.

Yes. It is not expected that implementing a new numeric type is necessarily trivial. There are a "lot" of user-expectations around numeric types and the requirements for them to be more broadly usable aren't simple. This ranges (but is not limited to) from proper formatting and parsing support, to considering how these types are created from other numeric types, to covering checked and unchecked operations, and being able to efficiently query relevant properties to ensure compliant and deterministic behavior can be had.

Some of this will be simplified by the use of DIMs so users can think about "less" in a few of the "simple" cases. But it will still have a decently high barrier for declaration in favor of a much simpler and more coherent usage story.

> This can prevent potential generic LINQ operators to be used. But surely we can re-add them then.

Yes, they were removed for the time being from the non number-like types with the annotation that we can add them back in the future if there is enough need/demand.

A set of generic LINQ methods would still be definable, they would just be initially limited to number like types with well-defined behavior for its operations.

**Comment by huoyaoyuan** [comment]
@tannergooding I have some further questions about versioning.
Some generic math interfaces members are approved but not yet implemented, for example IEEE754 suggested operations. There are still members be added to the interface recently.
Would the interfaces be versioned like normal interfaces, that no abstract member can be added in order to not break external implementations? Would this become technical debt for evolution in the future?

**Comment by tannergooding** [comment]
> Some generic math interfaces members are approved but not yet implemented, for example IEEE754 suggested operations. There are still members be added to the interface recently.

There is only 1 approved API that didn't actually get exposed and that is `compound`. Other functionality called out in the doc represent functionality that .NET likely won't expose (as it represents legacy IEEE 754 concepts we aren't supporting) or wouldn't expose as part of the generic math interfaces (often because it operates over a collection of `T` and so would be better suited for exposure a different way).

> Would the interfaces be versioned like normal interfaces, that no abstract member can be added in order to not break external implementations?

Yes. We continue having a strong bar for back-compat and adding new `abstract` members to an interface is a very serious break; one we are unlikely to ever make.

Any new APIs will be exposed as `static virtual` members with a `default implementation`. The interfaces were designed with this consideration and we should be able to expose many types of functionality using this approach.

The "worst case scenario" would be either:
A. We need to default the implementation to `throw` in which case we may also expose some `IsApiSupported` property allowing use of the API to be guarded.
B. We need to expose some new interface to represent the concept

> Would this become technical debt for evolution in the future?

Not sure what you're asking here. These interfaces will be versioned much as you would version an abstract class and so devs supporting these interfaces don't have anything to do by default. They can optionally choose to provide their own overriding implementation if that is desirable.

**Comment by jeffhandley** [comment]
@tannergooding (and @dotnet/area-system-numerics) Can you add a checklist to the issue description of other docs that need to be updated? I presume we'll want to complete the updates before we ship GA.

**Comment by dakersnar** [comment]
All known issues with the generic math documentation have been resolved. Closing this.
