### ISSUE TITLE
[LoongArch64] A plan for amending the LoongArch64‘s port

### ISSUE THREAD

**Issue by shushanhf** [dotnet/runtime#69705]
### Description

After the supporting for LoongArch64 finished by #59561 , 
there are still some TODOs for LA that should be implemented.

Here creating a new issue to track these.

(1) Fixing all the bugs anytime;
(2) Amend the LoongArch64's ABI;
(3) Enable the promote feature;
(4) Pushing the crossgen2 for LA;
(5) Supporting the SIMD/intrinsic for LA;
(6) ...

The CoreRoot for LoongArch64 will be updated  [here](https://github.com/shushanhf/LoongArch64-Blog-for-.NET-Mono/tree/main/rumtime_main_CoreRoot)

### Reproduction Steps

Testing all the test-cases of the runtime on LoongArch64's Linux.

### Expected behavior

The test cases should pass.

### Actual behavior

Failed.

### Known Workarounds

Using the SDK6-LoongArch64 which published by  Loongson based on the offical-SDK6.

### Configuration

LoongArch64’s Linux

**Comment by shushanhf** [comment]
@jkotas @BruceForstall 

we will push some PRs to amend the LA's  port after we had fixed some test cases on LA-linux.

**Comment by huoyaoyuan** [comment]
> Supporting the SIMD/intrinsic for LA

I've read the instruction spec for LA, and found some instructions interesting. As a bread new architecture, we may be concerned about exposing intrinsics in public API. However, we can implement an internal intrinsic class first and use in BitOperations etc.

**Comment by shushanhf** [comment]
> > Supporting the SIMD/intrinsic for LA
> 
> I've read the instruction spec for LA, and found some instructions interesting. As a bread new architecture, we may be concerned about exposing intrinsics in public API. However, we can implement an internal intrinsic class first and use in BitOperations etc.

Thanks.

**Comment by am11** [comment]
@shushanhf, should we have `native->uc_mcontext.__fcsr = lpContext->Fcsr;` before this line: https://github.com/dotnet/runtime/blob/48a3dbe5509f53f89db0a48c8285a2eec0758fea/src/coreclr/pal/src/thread/context.cpp#L626 as we do the opposite here: https://github.com/dotnet/runtime/blob/48a3dbe5509f53f89db0a48c8285a2eec0758fea/src/coreclr/pal/src/thread/context.cpp#L776

**Comment by shushanhf** [comment]
> @shushanhf, should we have `native->uc_mcontext.__fcsr = lpContext->Fcsr;` before this line:
> 
> https://github.com/dotnet/runtime/blob/48a3dbe5509f53f89db0a48c8285a2eec0758fea/src/coreclr/pal/src/thread/context.cpp#L626
> 
> as we do the opposite here:
> https://github.com/dotnet/runtime/blob/48a3dbe5509f53f89db0a48c8285a2eec0758fea/src/coreclr/pal/src/thread/context.cpp#L776

Thanks, you are right.
And maybe I have to sync these to the upstream because the last merged by the kernel and glibc might be different with these.
As the reviewing of some projects liking the kernel and glibc  was too slow.
I will update these later.

**Comment by shushanhf** [comment]
As this issue's description,
now we are developping the Intrinsic/SIMD for LA64, we have developped about 80% and we will upload it after we test OK, planning in 2023Q1.
Then we will discuss some interfaces within some C# and amending them.

The crossgen2 for LA64 had been merged and will be ament in 2023Q1.

**Comment by BruceForstall** [comment]
@shushanhf Thanks for the update. Glad to see the LA64 work is continuing.

fyi @tannergooding -- work is proceeding on LoongArch64 intrinsic/SIMD support.

**Comment by shushanhf** [comment]
> It would be good to understand what is meant by intrinsic/SIMD support.
> 
> Where there are library side changes, we should ensure they don't hurt the JIT's ability to inline or optimize existing code paths. Likewise, even if internal we should likely have minimal discussion that the general shape/layout is as expected to reduce future churn if we decide to make it public.

@tannergooding 
Thanks.
I noted your guidance for modifying the related C# library files.

I think it's better if we preparing an preliminary implementation for LA to discuss and amend the implementaion.
We are planning to push the PRs in January or February.

**Comment by shushanhf** [comment]
> @shushanhf Thanks for the update. Glad to see the LA64 work is continuing.
> 
> fyi @tannergooding -- work is proceeding on LoongArch64 intrinsic/SIMD support.

@tannergooding 
Although we have finished the intrinsic/SIMD for LoongArch64, there is no LoongArch64's SIMD manual  published, especially the Enlish version.
I have to delay pushing the intrinsic/SIMD for LoongArch64.

**Comment by shushanhf** [comment]
The OSR for LA64 is just for optimization and we will do it later. #86022

After today's some PRs, all tests passed on LA64 except the crossgen2 not tested.

**Comment by shushanhf** [comment]
> The OSR for LA64 is just for optimization and we will do it later. #86022
> 
> After today's PRs #86289 #86290 #86294 , all tests passed on LA64 except the crossgen2 not tested.

```shell
qiao@Lap5K2:~/tests$ ./dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/dotnet --info
.NET SDK:
 Version:   8.0.100-preview.4.23260.1
 Commit:    2268e7b15c

运行时环境:
 OS Name:     Loongnix
 OS Version:  20
 OS Platform: Linux
 RID:         linux-loongarch64
 Base Path:   /home/qiao/tests/dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/sdk/8.0.100-preview.4.23260.1/

.NET workloads installed:
没有要显示的已安装工作负载。

Host:
  Version:      8.0.100-preview.4.23260.1
  Architecture: loongarch64
  Commit:       a8507f7c8c

.NET SDKs installed:
  8.0.100-preview.4.23260.1 [/home/qiao/tests/dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [/home/qiao/tests/dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [/home/qiao/tests/dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download


qiao@Lap5K2:~/tests/hello$ 
qiao@Lap5K2:~/tests/hello$ ../dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/dotnet new console
已成功创建模板“控制台应用”。

正在处理创建后操作...
正在还原 /home/qiao/tests/hello/hello.csproj:
  Determining projects to restore...
  Restored /home/qiao/tests/hello/hello.csproj (in 874 ms).
已成功还原。


qiao@Lap5K2:~/tests/hello$ ../dotnet-sdk-8.0.100-preview.4.23260.1-linux-loongarch64/dotnet run 
Hello, World!
```

Next we will continue to improve the LA64-SDK8.0's reliability first, then pushing the OSR and some others.
We will do our best to add LoongArch64 into the CI althought it depends on the Debian community merging the LA64‘s progress.

**Comment by shushanhf** [comment]
Hi, @jkotas 
How to apply for adding lables liking `arch-loongarch64` ？ when I push PRs I can add some lables.

Thanks

**Comment by jkotas** [comment]
I have sent you invitation to join dotnet org on github. Once you are accept, I will grant you rights to apply labels.

**Comment by shushanhf** [comment]
> I have sent you invitation to join dotnet org on github. Once you are accept, I will grant you rights to apply labels.

Thanks, I had joined the team.

**Comment by jkotas** [comment]
I made you member of https://github.com/orgs/dotnet/teams/dotnet-runtime-triage that gives you triage rights for this repo, that includes rights to apply labels. Please use these rights for LoongArch64 related issues only.

**Comment by shushanhf** [comment]
> I made you member of https://github.com/orgs/dotnet/teams/dotnet-runtime-triage that gives you triage rights for this repo, that includes rights to apply labels. Please use these rights for LoongArch64 related issues only.

OK, Thanks

**Comment by shushanhf** [comment]
We had fixed many errors for LoongArch64 and it’s preliminary available.
I will close this issue later.

The instrinsic and crossgen2 will be added one by one subsequently.
