### ISSUE TITLE
WindowsCryptographicException cannot be serialized

### ISSUE THREAD

**Issue by johansme** [dotnet/runtime#69704]
We have a service that performs cryptographic operations on request from other services. When these operations fail, we need to propagate the exceptions to the calling service, in order to take the correct action based on the kind of exception. However, this propagation fails in .NET Core because the `WindowsCryptographyException` is a private sealed class, and not marked as `[Serializable]`. Best practice for any exception is for it to be serializable, and so this is not a recommended way to do things.

Another point is that in [this comment](https://github.com/dotnet/runtime/issues/15986#issuecomment-166736225), @bartonjs claims `WindowsCryptographicException` was introduced because the base `CryptographicException` did not have a constructor that could set both message and error code. However, the `WindowsCryptographicException` is only used in the `CryptoThrowHelper`. I cannot see any reason this couldn't be solved by using the standard `CryptographyException` constructor with a `message` parameter, and use an object initializer to set the error code - which has a public setter. This would make the exception serializable, and it would remove the need for a derived private type.

**Comment by danmoseley** [comment]
If you only need the type of exception, do you need to serialize more than the name of the type?
If you also need it for diagnostics, ToString() may be sufficient for that.

**Comment by johansme** [comment]
These exceptions are transferred using Service Fabric Remoting - which does have an alternative serialization method, using `DataContract`. However, the principle still stands; the exception cannot be serialized because it is a private sealed class. So rather than the class being made serializable, my suggestion is that it is removed altogether - seeing as the reason it exists is to set both the message and the error code of the returned exception, which could be done with an object initializer.

**Comment by GrabYourPitchforks** [comment]
>  seeing as the reason it exists is to set both the message and the error code of the returned exception, which could be done with an object initializer.

The public setter is only available on recent versions of .NET. On earlier versions, such as .NET Framework, the setter is nonpublic. Object initializer syntax will not work on those old versions. And we produce assemblies which target both old + new versions of .NET.

That said, I think it would be acceptable to make a targeted change which allows this scenario to work.
