### ISSUE TITLE
Interlocked for nint

### ISSUE THREAD

**Issue by zelyony** [dotnet/runtime#69708]
### Background and motivation

nint val = 0;
val = Interlocked.Exchange(ref val, 0); // CS0452
// The type 'nint' must be a reference type in order to use it as parameter 'T' in the generic type or method 'Interlocked.Exchange<T>(ref T, T)'

### API Proposal

just substitute for x64 .Exchange(ref long, ..) and for x86 .Exchange(ref int, ..)

### API Usage

nint val = 0;
val = Interlocked.Exchange(ref val, 0); // OK

**Comment by huoyaoyuan** [comment]
This is an overload resolution issue. The overload existed from .NET Framework 2.0, but it can't be bound with numeric literal.
Add a cast in the call:

```csharp
val = Interlocked.Exchange(ref val, (nint)0);
``` 

Refining the overload resolution belongs to the dotnet/csharplang repo.

**Comment by zelyony** [comment]
oh. I see
