### ISSUE TITLE
Implement forward substitution utility to create larger trees for morph

### ISSUE THREAD

**Issue by russellhadley** [dotnet/runtime#6973]
Extend RyuJIT to use forward substitution to expand the impact of morph optimizations.

category:cq
theme:optimization
skill-level:expert
cost:extra-large

**Comment by EgorBo** [comment]
A very simple implementation: https://github.com/EgorBo/runtime-1/commit/85a22886a344ad1598c0c41bd88b89cfbb4b97aa

**Comment by AndyAyersMS** [comment]
This should be largely addressed by #63720, though there are still a number of cases where we can improve.

**Comment by AndyAyersMS** [comment]
There's now both a phase and a utility method, so I think this is done.
