### ISSUE TITLE
In NativeAOT, Null ref return throws NullReferenceException but should be wrapped in a TargetInvocationException 

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#69755]
In `System.Reflection.Tests.InvokeRefReturnNetCoreTests`, the tests `TestNullRefReturnInvoke<T>` and `TestNullRefReturnOfPointer` expect a `System.Reflection.TargetInvocationException`, but in NativeAOT it throws a `NullReferenceException`.

Related to https://github.com/dotnet/runtime/issues/67457 and https://github.com/dotnet/runtime/issues/69336.

**Comment by MichalStrehovsky** [comment]
@LakshanF said he'll be looking into this one. It involves deleting code around `NullByRefValueSentinel`.
