### ISSUE TITLE
Microsoft.Quic.MsQuicException on rolling build of runtime

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#69792]
### Description

Last [build](https://runfo.azurewebsites.net/view/build/?number=1788472) of runtime is failing with below exception on System.Net.Quic.Tests.MsQuicTests

System.AggregateException : One or more errors occurred. (Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED) ---- Microsoft.Quic.MsQuicException : Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED

### Reproduction Steps

Check last rolling [build](https://runfo.azurewebsites.net/view/build/?number=1788472) of runtime

### Expected behavior

System.Net.Quic.Tests.MsQuicTests should pass

### Actual behavior

System.Net.Quic.Tests.MsQuicTests  are failing

**Comment by mkhamoyan** [comment]
@rzikm from commit log most probably it is related with https://github.com/dotnet/runtime/pull/69603 , could you please take a look?

**Comment by rzikm** [comment]
I am looking into it, hopefully will be fixed with https://github.com/dotnet/runtime/pull/69789

**Comment by rzikm** [comment]
No such luck, but the test failures seem to be confined to Windows 2022 Server, so I will disable the tests there meanwhile

**Comment by ManickaP** [comment]
Has the dotnet/msquic change been propagated via maestro already? When we update that repo, new version of windows version of libmsquic gets published into maestro subscription, which then creates PR in runtime in versions.xml, which then updates the msquic version.

Yeah, it wasn't consumed yet: https://github.com/dotnet/runtime/pull/69709

**Comment by wfurt** [comment]
It actually did: https://github.com/dotnet/runtime/pull/69603/checks?check_run_id=6578113266 and https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69603-merge-e5a980b51f6847128e/System.Net.Quic.Functional.Tests/1/console.00373325.log?helixlogtype=result

But the test runs was marked as successful: cc @MattGal

**Comment by ManickaP** [comment]
Ha, Tomas is faster, yeah this was a trap :smile:

**Comment by rzikm** [comment]
> WS 2022 will not support client certificates using schannel. It was a feature added for Windows 11. The only way to get client certificate support on WS 2022 or earlier is to use OpenSSL.

I see, I will update our tests to reflect this

**Comment by MattGal** [comment]
> It actually did: https://github.com/dotnet/runtime/pull/69603/checks?check_run_id=6578113266 and https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69603-merge-e5a980b51f6847128e/System.Net.Quic.Functional.Tests/1/console.00373325.log?helixlogtype=result
> 
> But the test runs was marked as successful: cc @MattGal

Looks like a weird GitHub blip; all the Helix components and even most of the GitHub AzDO components logged "the right thing".  If it ever happens again please work with the @dnceng first responders Teams channel to reach out to GitHub; it's unlikely to be investigated while still a one-off.

**Comment by ManickaP** [comment]
> > WS 2022 will not support client certificates using schannel. It was a feature added for Windows 11. The only way to get client certificate support on WS 2022 or earlier is to use OpenSSL.
> 
> I see, I will update our tests to reflect this

Should we then rather increase our minimum required Windows version in S.N.Quic? Since without it, the feature doesn't work. 
I'm not sure how impactful the feature is and how confusing/debuggable this might be if someone used it on unsupported Win. @wfurt @CarnaViire @rzikm wdyt?

**Comment by wfurt** [comment]
> > WS 2022 will not support client certificates using schannel. It was a feature added for Windows 11. The only way to get client certificate support on WS 2022 or earlier is to use OpenSSL.
> 
> I see, I will update our tests to reflect this

I'm wondering if we should detect this in the product and throw PlatformNotSupportedException.

**Comment by rzikm** [comment]
> Should we then rather increase our minimum required Windows version in S.N.Quic?

We still need to disable the tests for that OS to unblock CI. Then we can think about following up with some more changes.

> I'm wondering if we should detect this in the product and throw PlatformNotSupportedException.

Detecting it sounds reasonable. It would mean OS platform and version check in MsQuicListener, which is doable (although we generally don't have version checks in the product). I would like to investigate this further because we are only supposed to get `CONNECTION_REJECTED` when the server is overloaded so it was misleading in this case.

**Comment by thhous-msft** [comment]
> Should we then rather increase our minimum required Windows version in S.N.Quic?

This would only be for the specific client certificate feature, and not the entirety of S.N.Quic, right? If the whole S.N.Quic namespace needs higher then WS 2022, then that would mean that no server os Microsoft ships would be supported by S.N.Quic, which would not be ideal.

> we are only supposed to get QUIC_STATUS_CONNECTION_REFUSED when the server is overloaded
CONNECTION_REFUSED can happen for a lot more reasons then this. The server could explicitly choose to fail the handshake, which would result in refused as well iirc.

**Comment by wfurt** [comment]
Yes, I think this check should be only for client certificates ... that is not common IMHO. 
Do you know @ThadHouse if the S2022 cannot send the cert or receive it? (or both) 
(e.g. would win11 client work agains server 2022?)

**Comment by thhous-msft** [comment]
Its server side can't receive it. The functionality to enable requesting client certificates does not work.

https://github.com/dotnet/runtime/issues/45456

Its the above bug, just exposed from our end.

**Comment by rzikm** [comment]
> CONNECTION_REFUSED can happen for a lot more reasons then this. The server could explicitly choose to fail the handshake, which would result in refused as well iirc.

Yes, that is the second instance I know of where server will refuse the connection, but we don't do that for the failed tests in question.

**Comment by jakobbotsch** [comment]
> It actually did: https://github.com/dotnet/runtime/pull/69603/checks?check_run_id=6578113266 and https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69603-merge-e5a980b51f6847128e/System.Net.Quic.Functional.Tests/1/console.00373325.log?helixlogtype=result
> 
> But the test runs was marked as successful: cc @MattGal

This was due to #69615. It was fixed in #69736.

**Comment by agocke** [comment]
Sorry, read the comments but not sure I followed everything -- do we expect this is fixed?

**Comment by rzikm** [comment]
I hoped https://github.com/dotnet/runtime/pull/69709 would get in soon (it would fix the test failure), but since there are some test failures on that PR I will merge my other PR which will disable the test and will have to follow up on that later.
