### ISSUE TITLE
Duplicate logging in `Microsoft.Extensions.Hosting.Host`

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#69793]
## Behavior

![image](https://user-images.githubusercontent.com/10373452/170271206-aeb69a6f-7f7d-4318-9b58-c624486fd686.png)

Why does this log twice?

### Minimal repro

```cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace HostRepro;

public static class Program
{
    public static async Task Main(string[] args)
    {
        await Host.CreateDefaultBuilder(args)
            .ConfigureServices(static services =>
            {
                services.AddHostedService<ReproService>();
            })
            .RunConsoleAsync();
    }
}
public sealed class ReproService : BackgroundService
{
    private readonly ILogger<ReproService> _logger;
    private readonly IHostLifetime _hostLifetime;

    public ReproService(ILogger<ReproService> logger, IHostLifetime hostLifetime)
    {
        _logger = logger;
        _hostLifetime = hostLifetime;
    }

    protected async override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        await _hostLifetime.WaitForStartAsync(stoppingToken);
        _logger.LogInformation("Test 1");
        await Task.Delay(5000, stoppingToken);
        _logger.LogInformation("Test 2");
        await _hostLifetime.StopAsync(stoppingToken);
        _logger.LogInformation("Test 3");
    }
}
```

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
  </ItemGroup>

</Project>
```

/cc @eerhardt

**Comment by deeprobin** [comment]
@eerhardt 
> Why are you calling WaitForStartAsync in your background service?

Because I want to run the service logic after `Application started. Press Ctrl+C to shut down.`.
Is there a better way to wait until full-initialization?

**Comment by eerhardt** [comment]
> Is there a better way to wait until full-initialization?

You don't want to use `IHostLifetime` in that case. That interface is used by the Host to control the lifetime of the app.

Instead, what you are looking for is `IHostApplicationLifetime`:

https://github.com/dotnet/runtime/blob/8aac5ee2e821498684b385f443d2474db215b2ae/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/IHostApplicationLifetime.cs#L8-L16

**Comment by deeprobin** [comment]
@eerhardt Oh okay. And how can I wait for ApplicationStarted without using some hacks like
```
while(!lifetime.ApplicationStarted.IsCancellationRequested) {}
```

**Comment by eerhardt** [comment]
> And how can I wait for ApplicationStarted without using some hacks like

You can use the `Register` method to register a handler that will be called when the Application is started. If you want to `await` some Task, you can use a technique such as https://github.com/dotnet/runtime/issues/14991#issuecomment-131221355 to make it into a Task.

BTW - you can easily see what other code is doing by using https://source.dot.net/. It is a quick way to look up some code, and you can quickly see what all the callers of that code do. So you can get some ideas at how others are using this API (or any API):

https://source.dot.net/#Microsoft.Extensions.Hosting.Abstractions/IHostApplicationLifetime.cs,f6f7d72cbedc2d3b,references

**Comment by deeprobin** [comment]
@eerhardt In Germany tomorrow is a holiday :D I'll try it the day after tomorrow. Thank you.

**Comment by deeprobin** [comment]
@eerhardt Waiting for CancellationToken does not work :/. "Test 1" is still sent before `Application started. Press Ctrl+C to shut down.`. Suggestions?

![image](https://user-images.githubusercontent.com/10373452/170639494-1b390dba-3074-45d4-a833-105db02910fa.png)

### Repro
```cs
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace HostRepro;

public static class Program
{
    public static async Task Main(string[] args)
    {
        await Host.CreateDefaultBuilder(args)
            .ConfigureServices(static services =>
            {
                services.AddHostedService<ReproService>();
            })
            .RunConsoleAsync();
    }
}
public sealed class ReproService : BackgroundService
{
    private readonly ILogger<ReproService> _logger;
    private readonly IHostApplicationLifetime _hostApplicationLifetime;

    public ReproService(ILogger<ReproService> logger, IHostApplicationLifetime hostApplicationLifetime)
    {
        _logger = logger;
        _hostApplicationLifetime = hostApplicationLifetime;
    }

    protected async override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var tcs = new TaskCompletionSource<bool>();
        CancellationTokenRegistration cancellationTokenRegistration = _hostApplicationLifetime.ApplicationStarted.Register(s => ((TaskCompletionSource<bool>)s!).SetResult(true), tcs);
        await tcs.Task;

        _logger.LogInformation("Test 1");
        await Task.Delay(5000, stoppingToken);
        _logger.LogInformation("Test 2");
        _hostApplicationLifetime.StopApplication();
        _logger.LogInformation("Test 3");
    }
}
```

**Comment by eerhardt** [comment]
Is it strictly the logging you want to get in order?

https://github.com/dotnet/runtime/blob/ecb4e6c178b98aec29fbf3e7a70a820240c1dd0b/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L79-L82

The above code shows that the "Started" event is raised (after all the hosted services have started) and then the Host logs that it has "started".

What's happening is your continuation of `await tcs.Task;` is running synchronously inline when you are setting the TaskCompletionSource Result. So the events go:

1. ReproService.ExecuteAsync is invoked
    1. It "awaits" getting called back when the ApplicationStarted.
2. The Host starts the rest of the services (none in this case).
3. The Host raises ApplicationStarted
    1. Your registration callback is invoked
    2. `tcs.SetResult(true)` is called
        1. Inline on SetResult, it sees it has a callback to invoke, so it invokes it
            1. Your ExecuteAsync continues

If you really want the logs to be in order, you could break this in the registration callback:

```C#
    protected async override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var tcs = new TaskCompletionSource<bool>();
        CancellationTokenRegistration cancellationTokenRegistration = _hostApplicationLifetime.ApplicationStarted.Register(async s =>
        {
            await Task.Delay(15); // HERE
            ((TaskCompletionSource<bool>)s!).SetResult(true);
        }, tcs);
        await tcs.Task;

        _logger.LogInformation("Test 1");
        await Task.Delay(5000, stoppingToken);
        _logger.LogInformation("Test 2");
        _hostApplicationLifetime.StopApplication();
        _logger.LogInformation("Test 3");
    }
```

Even this isn't guaranteed that the logs will be in the correct order, because you can't guarantee the order that threads run. The only way I can imagine you can guarantee ordering is to make your own logger, and wait for the "started" logs to come through, and then unblock your ReproService.

If you disregard the log order, your code is guaranteed that `ReproService` will block until all the other Services have Started.

**Comment by deeprobin** [comment]
@eerhardt 
Thank you. Using delay is one possibility, but `await Task.Yield()` was also a solution in this case :).

```cs
        var tcs = new TaskCompletionSource<bool>();
        CancellationTokenRegistration cancellationTokenRegistration = _hostApplicationLifetime.ApplicationStarted.Register(async s =>
        {
            await Task.Yield();
            ((TaskCompletionSource<bool>)s!).SetResult(true);
        }, tcs);
        await tcs.Task;
```
