### ISSUE TITLE
IQueryable.DefaultIfEmpty() marked as non-nullable even though it can return null values as a LEFT JOIN

### ISSUE THREAD

**Issue by kanadaj** [dotnet/runtime#69817]
### Description

`IQueryable.DefaultIfEmpty()`, unlike it's normal Linq equivalent, returns `IQueryable<TSource>` instead of `IQueryable<TSource?>`.

### Reproduction Steps

Simple enough, here is a simple repro which should warn for a null reference but instead doesn't:
```cs
var users = applicationDbContext.Users.Where(x => false).DefaultIfEmpty().ToList();
foreach (var user in users ) Console.WriteLine(user.UserName); // NullReferenceException unmarked by the compiler
```

### Expected behavior

`DefaultIfEmpty()` should have the return type of `IQueryable<TSource?>`.

### Actual behavior

See above. The behaviour is especially messy because the non-nullability prompts the IDE to remove null checks on the supposedly-not-null property.

### Known Workarounds

Project to a new object and cast to nullable manually:
```cs
applicationDbContext.MyTable.Where(x => false).DefaultIfEmpty().Select(x => (TSource?)x)...
```
not ideal, though.

**Comment by Clockwork-Muse** [comment]
>```csharp
>var users = applicationDbContext.Users.Where(x => false).ToList();
>foreach (var user in users ) Console.WriteLine(s.ToString()); // NullReferenceException unmarked by the compiler
>```

 1. This doesn't use `DefaultIfEmpty()`?
 2. This code should fail to compile (where does `s` come from?)
 3. If you meant `s` to instead be `user`, it would like be okay (assuming `Users` is `IQueryable<UserType>`).

> `IQueryable.DefaultIfEmpty()`, unlike it's normal Linq equivalent, returns `IQueryable<TSource>` instead of `IQueryable<TSource?>`.

The documentation for LINQ doesn't have a matching `return` and signature, so something is maybe wrong with the documentation?

**Comment by kanadaj** [comment]
> 

Ah my bad, one too many revisions. Edited the code sample, but here is an even more minimal repro:
```cs
var l = new List<string>().AsQueryable().DefaultIfEmpty().ToList();
foreach(var s in l) Console.WriteLine(s.ToString()); // NullReferenceException, no warning
```
At the same time, if you do the same with IEnumerable:
```cs
var l = new List<string>().DefaultIfEmpty().ToList();
foreach(var s in l) Console.WriteLine(s.ToString()); // Null dereference warning
```
Here is the signature for IEnumerable:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/DefaultIfEmpty.cs#L11

See how `TSource` is marked as nullable because the default object for reference types is `null`, so even if you pass a non-nullable `IQueryable<TSource>` to `DefaultIfEmpty()`, you may still get back a null `TSource`.

Very quick SharpLab repro to show that IEnumerable has a compiler warning but not IQueryable:
https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEAMACLARgBYBuAWAChcDCA6AGVgEcLKBiGVAG24mG4BTPIJj8hVKgHopeABKDkwqAGc8CABbCAxgHsAJsN0w8ASQCKqRQE9xgkFQBuEZHmZXktgcIC8eGIIA7nhMKggAPEQ4AHwAFACUdACCKpY2dgl0ACKCAGYQPAimuQCiYAAOCNYJbLm6ShDaGrHOrlAIgmB4sG4eXkLxVADeVHhj3R1gdAAqugDKCMiwAOY1VAC+kpQyeEkw+upaeCoQYMIQy9AwYbQAzA6UrSJcZ8h2eH4BwaERUXGJOXyhWKZUq1XitXqgkazSe7U63RMolQrzsg0oI0o4wmnRm80WKzWlHWQA===

**Comment by kanadaj** [comment]
This issue also tricks ReSharper and Rider in the inverse case:
![image](https://user-images.githubusercontent.com/3247357/170395692-03118709-36a5-4dda-8cdf-d65fae8db99a.png)

**Comment by eiriktsarpalis** [comment]
Seems reasonable, the IQueryable annotations should reflect these of Linq so I'd support this change.
