### ISSUE TITLE
ARM64 glibc runtime builds on Ubuntu 18.04, not CentOS 7

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#69811]
Platform compatibility for portable builds relies on referencing the lowest possible version of libc. The libc in Ubuntu is usually higher than in CentOS/RHEL, so building the product on Ubuntu may take a dependency on a newer version of libc that's not available on all platforms.

We should instead build on CentOS 7 for all glibc platforms.

**Comment by jkotas** [comment]
This is expected, by design: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#linux

**Comment by hoyosjs** [comment]
Also, base images here are different. This are crossbuilds - we build a rootfs here: https://github.com/dotnet/arcade/blob/main/eng/common/cross/build-rootfs.sh. The host is not too interesting.
