### ISSUE TITLE
The BlockingCollection<T> backed by a custom collection doesn't work properly

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#69816]
### Description

I am trying to create a [`BlockingCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1) that rejects duplicate items. For this reason I wrote a custom collection that implements the [`IProducerConsumerCollection<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.iproducerconsumercollection-1) interface, and then passed an instance of this collection to the constructor of the `BlockingCollection<T>`. 

The problem is that the bounding functionality of the `BlockingCollection<T>` seems to brake when a duplicate item has been rejected by the underlying collection. Although the item has been rejected, it still counts towards the [`BoundedCapacity`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.boundedcapacity) limit. The result is that fewer than `BoundedCapacity` elements can be added in the collection, and eventually (after many rejected duplicates) the effective capacity is reduced to just 1.

### Reproduction Steps

```C#
using System;
using System.Collections;
using System.Collections.Concurrent;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        BlockingCollection<int> queue = new(new ConcurrentQueueNoDuplicates<int>(), 2);
        AddItem(1); // True
        AddItem(1); // InvalidOperationException
        AddItem(2); // False (unexpected)

        void AddItem(int value)
        {
            try
            {
                Console.WriteLine($"queue.TryAdd({value}): {queue.TryAdd(value)}");
            }
            catch (InvalidOperationException) when (!queue.IsAddingCompleted)
            {
                Console.WriteLine($"queue.TryAdd({value}): InvalidOperationException");
            }
        }
    }

    private class ConcurrentQueueNoDuplicates<T> : IProducerConsumerCollection<T>
    {
        private readonly Queue<T> _queue = new();
        public bool TryAdd(T item)
        {
            lock (_queue)
            {
                if (_queue.Contains(item)) return false;
                _queue.Enqueue(item); return true;
            }
        }
        public bool TryTake(out T item)
        {
            lock (_queue)
            {
                if (_queue.Count == 0) { item = default; return false; }
                item = _queue.Dequeue(); return true;
            }
        }
        public int Count { get { lock (_queue) return _queue.Count; } }
        public bool IsSynchronized => throw new NotImplementedException();
        public object SyncRoot => throw new NotImplementedException();
        public void CopyTo(T[] array, int index) => throw new NotImplementedException();
        public void CopyTo(Array array, int index) => throw new NotImplementedException();
        public IEnumerator<T> GetEnumerator() => throw new NotImplementedException();
        IEnumerator IEnumerable.GetEnumerator() => throw new NotImplementedException();
        public T[] ToArray() => throw new NotImplementedException();
    }
}
```

Output:

```none
queue.TryAdd(1): True
queue.TryAdd(1): InvalidOperationException
queue.TryAdd(2): False
```

[Live demo](https://dotnetfiddle.net/BrE4h8).

### Expected behavior

The `BoundedCapacity` is configured with the value `2`, so it is expected that the two values 1 and 2 can both be stored in the collection. The attempt to add the value 1 twice should be denied, but the state of the collection should remain unchanged. So the subsequent `queue.TryAdd(2)` should return `true`.

### Actual behavior

The `queue.TryAdd(2)` returns `false`.

### Regression?

The actual behavior on .NET Framework 4.8 is the same.

### Known Workarounds

The underlying collection rejects an item by throwing an exception instead of returning `false`.

### Configuration

- .NET 6.0
- Windows 10
- 64-bit operating system, x64-based processor

### Other information

The [source code](https://github.com/dotnet/runtime/blob/56e821243d92f20a6abf7ca61288221f4d164dd1/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/BlockingCollection.cs#L480-L483) includes the following comment:

```C#
//TryAdd is guaranteed to find a place to add the element. Its return value depends
//on the semantics of the underlying store. Some underlying stores will not add an already
//existing item and thus TryAdd returns false indicating that the size of the underlying
//store did not increase.
```

The actual behavior of the `BlockingCollection<int>.TryAdd` is not to return `false`, but to throw an exception. The actual behavior is correctly [documented](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.tryadd) in the online docs. My guess is that the specification changed during the development of the class, and the problem is somehow related to that change.

**Comment by stephentoub** [comment]
> The problem is that the bounding functionality of the BlockingCollection<T> seems to brake when a duplicate item has been rejected by the underlying collection.

Such a collection can't work with `BlockingCollection<T>`, which assumes that if `TryAdd` returns true, the item was successfully added and can later be consumed via `TryTake`.  Returning true after throwing away the item violates that.

**Comment by theodorzoulias** [comment]
> Similarly returning false tells the `BlockingCollection<T>` that the item can't be added because there isn't sufficient room, which is erroneous for the `BlockingCollection<T>`.

Hmm, that's a bit disappointing. Is there any chance that the implementation of the `BlockingCollection<T>` could be changed, so that it can handle gracefully the case that the underlying store rejected an item?

**Comment by stephentoub** [comment]
> Is there any chance that the implementation of the BlockingCollection<T> could be changed, so that it can handle gracefully the case that the underlying store rejected an item?

It doesn't know why the item was rejected.  Was it rejected because it doesn't want/like the value and it should be discarded, was it rejected because it doesn't currently have room and wants the caller to try again later, or was it rejected because it doesn't have the room and won't have the room until TryTake is called to make room.

**Comment by theodorzoulias** [comment]
> It doesn't know why the item was rejected.

@stephentoub I think that I have found a workaround. I changed the code of the `ConcurrentQueueNoDuplicates<T>.TryAdd` method so that it rejects an item by throwing an exception instead of returning `false`, and the problem of the reduced `BoundedCapacity` disappears ([demo](https://dotnetfiddle.net/Lo6MBM)). The `TryAdd(2)` returns `true` as expected. Do you have any idea if this a good workaround, or if it breaks the `BlockingCollection<T>` is some other way?

**Comment by stephentoub** [comment]
>  Do you have any idea if this is a good workaround

I'm not following: you're throwing an exception from your IProducerConsumerCollection.TryAdd, but that exception is being eaten by BlockingCollection and it's returning false from its TryAdd?

**Comment by theodorzoulias** [comment]
> I'm not following: you're throwing an exception from your IProducerConsumerCollection.TryAdd, but that exception is being eaten by BlockingCollection and it's returning false from its TryAdd?

@stephentoub sorry, in my example I had given to an auxiliary method the confusing name `TryAdd`. I just renamed that method to `AddItem`.

The workaround that I've found is to change the `ConcurrentQueueNoDuplicates<T>.TryAdd` method from this:

```C#
public bool TryAdd(T item)
{
    lock (_queue)
    {
        if (_queue.Contains(item)) return false;
        _queue.Enqueue(item); return true;
    }
}
```

...to this:

```C#
public bool TryAdd(T item)
{
    lock (_queue)
    {
        if (_queue.Contains(item)) throw new Exception("The item already exists.");
        _queue.Enqueue(item); return true;
    }
}
```

After making this change in the underlying collection, the bounding functionality of the `BlockingCollection<T>` seems to continue working correctly after an attempt to insert a duplicate value with the [`TryAdd`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.tryadd) method. With both versions the attempt throws. With the original version it throws an `InvalidOperationException`, and with the workaround it propagates the exception that is thrown by my own underlying collection.

According to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.tryadd) an `InvalidOperationException` signifies that *"The underlying collection didn't accept the item."* My understanding is that handling (suppressing) this exception should be safe, I.e. it should leave the `BlockingCollection<T>` in a usable (unaltered) state. Its current behavior seems like a bug IMHO.

**Comment by eiriktsarpalis** [comment]
> According to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1.tryadd) an InvalidOperationException signifies that "The underlying collection didn't accept the item." My understanding is that handling (suppressing) this exception should be safe, I.e. it should leave the BlockingCollection<T> in a usable (unaltered) state. Its current behavior seems like a bug IMHO.

My understanding of [the issue](https://dotnetfiddle.net/BrE4h8) is that `BlockingCollection<T>` is failing to roll back state in cases where the underlying IProducerConsumerCollection.TryAdd call returns false. If that's accurate it does sound like bug we might want to consider fixing.

**Comment by theodorzoulias** [comment]
@eiriktsarpalis yes, this is my understanding too. The `BlockingCollection<T>` class is not prepared to handle a formal rejection from the underlying collection, although interestingly it handles well an informal (exceptional) rejection.

Honestly attempting to fix this bug looks like an undertaking that's beyond my level of expertise. Messing with concurrent collections is something that I would leave to the experts!

**Comment by hrrrrustic** [comment]
Exactly same problem with `TryTake`, it will leave `BlockingCollection` in corrupted state. The fix is pretty simple, but it doesn't make sense to fix only for `TryAdd`

**Comment by hrrrrustic** [comment]
@eiriktsarpalis Linked a PR
