### ISSUE TITLE
Unable to build, missing System.IO.Pipes.AccessControl

### ISSUE THREAD

**Issue by TheJayMann** [dotnet/runtime#69826]
In an attempt to bootstrap build v6.0.300 (the latest version and release not in preview) on linux, using a clean Debian Testing distribution, installing the Debian equivalent packages as is listed by the Fedora build process, I followed the instructions listed in the README.md file for building source build.  I ran the build.sh script from this repository, bundled the content of `TarballDir` into a `tar.gz` file, extracted the `tar.gz` file to it's own directory, within the directory ran the `./prep --bootstrap` script, then ran the `./build` script.  The script then fails when it attempts to build roslyn.  It attempts to restore `System.IO.Pipes.AccessControl` version >= `5.0.0`.  However, at this point in the build, it appears the only version `4.5.1` and `4.3.0` are available.

As this is the first time I'm attempting to build something like this, I'm not particularly sure what else to try to get this working.  I've attached the roslyn.log file, but I can also attach the 19MB full build log if necessary.

Also attached is the script I used to create the initial tarball, before extracting and executing the `./prep --bootstrap` and `./build` scripts.

[roslyn.log](https://github.com/dotnet/installer/files/8729385/roslyn.log)
[mktarball.sh.txt](https://github.com/dotnet/installer/files/8729431/mktarball.sh.txt)

**Comment by omajid** [comment]
I don't think 6.0.3xx (6.0.300 and later) has full support for source-build including bootstrap. For now, full support of source-build (including bootstrapping) is limited to 6.0.1xx.

cc @crummel @lbussell  @MichaelSimons

**Comment by MichaelSimons** [comment]
> I don't think 6.0.3xx (6.0.300 and later) has full support for source-build including bootstrap. For now, full support of source-build (including bootstrapping) is limited to 6.0.1xx.

That's correct.  .NET source-build currently only supports the oldest SDK feature band and is [documented here](https://github.com/dotnet/source-build/#support).  Additionally, .NET source-build does not support producing native packages such as a `deb` file.  The build only produces the resulting product binaries/tarballs.  The `Deb` related targets are used by the MSFT build, constructing native packages is beyond the scope of source-build.

**Comment by TheJayMann** [comment]
I understand this, and, ultimately, sticking with the 1XX builds will avoid some potential issues I would have eventually run into anyway.  However, the presence of debuild will cause the build to fail.  After looking at a few of scripts used to build, it appears when I am building, that `SkipBuildingInstaller` parameter is passed, which prevents attempting to download deb packages, and I believe this is justified, because, if you are not planning to build deb packages with the build script, there would be no need to download the others.  However, when the `Pack` target is run for the installer project, the only thing that is checked is whether the distribution is debian based, and that debuild is available.  I would suggest that the `GenerateInstallers` target for the installer project should have a condition that it is not run if `SkipBuildingInstallers` is set, as, if the installers are not going to be built, then it doesn't really make sense to run `GenerateInstallers` target.  In fact, in order to get past this error, I have put in place a patch that does exactly that.
```diff 
--- a/src/installer.02d5242ed7ca7c3747fc89196cf67aeff260c6ac/src/redist/targets/GenerateInstallers.targets
+++ b/src/installer.02d5242ed7ca7c3747fc89196cf67aeff260c6ac/src/redist/targets/GenerateInstallers.targets
@@ -5,7 +5,7 @@
   </PropertyGroup>
 
   <Target Name="GenerateInstallers"
-          Condition="'$(PgoInstrument)' != 'true'"
+          Condition="'$(PgoInstrument)' != 'true' and '$(SkipBuildingInstallers)' != 'true'"
           BeforeTargets="Pack"
           DependsOnTargets="$(_BuildUnlessNoBuild);
                             GetCurrentRuntimeInformation;
```

This has gotten a bit off topic from the original issue of a dependency issue, however, this issue got migrated before I had the chance to split it into the two separate issues within.

**Comment by agocke** [comment]
Closing as it doesn't sound like this is a goal, but we may take a contribution if you have some
