### ISSUE TITLE
Data Annotation Extensions

### ISSUE THREAD

**Issue by mottaghipour** [dotnet/runtime#69834]
## Summary

To complete minimal validations(#30666) we should have some data annotations extensions.
I have an idea and I want to know if you agree with it to apply it?

## Motivation and goals

The idea is to quickly validate objects

## Examples

Validation extensions:
```csharp
public static class DataAnnotationsExtensions
{
    public static Tuple<bool, ValidationResult> Validate(this object model) { ... }
    public static Tuple<bool, ICollection<ValidationResult>> ValidateAllProperties(this object model) { ... }
}
```

Minimal Apis:
```csharp
app.MapPost("/todos", async (Todo todo) =>
{
    var (isValid, result) = todo.Validate();
    
    if (!isValid)
    {
        ...
    }
});
```

@halter73 @davidfowl 
I think this idea is good but I don't know which project or folder for this methods.
If you are agree I implement this extensions and create pull request.

**Comment by davidfowl** [comment]
These aren't tied to ASP.NET. This is a generic data annotations requests for recursive validation. Also extension methods on object are not great. I would prefer to see a static method here Validator class.

cc @DamianEdwards @ajcvickers

**Comment by mottaghipour** [comment]
I agree with you, I have thought about this before.
If objects inherits from `IValidatable`,  This is how we implement it:
```csharp
public interface IValidatable
{
    Tuple<bool, ICollection<ValidationResult>> Validate();
}
```
We can implement abstarct class `Validatble` for defualt base validations, users can customize `IValidatable` for another validation packages, as the same way if user want use defualt validation with validation attrs:
```csharp
public class TodoCommand : Validatble
{
    // [ValidationAttr]
    // Prop ...
}
```
I guess maybe the user wanted to use other packages for validation, they can customize them or even package development teams can create a way to customize it.

If we go this way, we can change the whole structure of requests and use `IValidatable` everywhere, for example ApiController can validate model with `Validate` method and object changes state IsValid This also avoids over-validation and finds a clear framework.
@davidfowl
