### ISSUE TITLE
Skip AMSI anti-malware scan when loading an assembly

### ISSUE THREAD

**Issue by garrynewman** [dotnet/runtime#69844]
### Description

When loading an assembly the majority of time is spent scanning it for malware. This isn't always necessary. In our case we've just compiled the assembly ourselves, from our code. As you see in the image below, loading the assembly takes 69ms, of which 69ms is spent scanning it for malware.

![image](https://user-images.githubusercontent.com/928843/170436438-f613b327-2857-40c2-9ddf-b7395a9f55c1.png)

I can appreciate that this scanning is maybe necessary evil, in our case it's vastly increasing the time taken to load assemblies. We don't benefit from any remembering the malware system does internally, because our assemblies are compiled "live" as the developer codes, so it changes every few seconds.

**Comment by hez2010** [comment]
I don't think the behavior of anti-malware software can be controlled from .NET side.

**Comment by garrynewman** [comment]
> I don't think the behavior of anti-malware software can be controlled from .NET side.

I don't know much about the internals, but from my search of the codebase it looks like an opt-in thing

https://github.com/dotnet/runtime/blob/d44343b4018bfbe266e93020c5aee66565cd158f/src/coreclr/vm/peimagelayout.cpp#L725-L732

**Comment by vitek-karas** [comment]
I'm pretty sure this will not happen. But I'll let our security exert chime in: @GrabYourPitchforks ;

**Comment by GrabYourPitchforks** [comment]
Correct, the default behavior isn't going to change. The feedback we received asking for the runtime to opt in to this mechanism was far greater than the feedback we received asking not to do so. Our stance is that AMSI behaviors - including a total opt-out from scanning, if desired - should be configured by a machine administrator using the existing AMSI configuration patterns and registry keys, or by configuring Defender at the machine level.

**Comment by garrynewman** [comment]
Fair enough, I'll close. Two thoughts come to mine though..

This surely affects Roylyn's CSharpScriptCompilation which is generating assemblies and loading them at runtime too.

To save a 200ms hitch save we're going to have to advise our community to turn defender off.. which has got to be the opposite of a good thing.
