### ISSUE TITLE
Many jobs are failing with a 401 response

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#69854]
The CI failures look like:
```
.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22255.2/tools/azure-pipelines/AzurePipelines.MultiQueue.targets(16,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.

Please Check the 'Make secrets available to builds of forks' in the pipeline pull request validation trigger settings.
We have evaluated the security considerations of this setting and have determined that it is fine to use for our public PR validation builds.
```

**Comment by tannergooding** [comment]
CC. @dotnet/runtime-infrastructure and @dotnet/dnceng 

This may be related to https://github.com/dotnet/runtime/issues/69829, so CC. @agocke

**Comment by tannergooding** [comment]
Thanks! There is a decent list of failures from 6 hours ago here: https://github.com/dotnet/runtime/pull/69756/checks?check_run_id=6606234716

**Comment by tannergooding** [comment]
I'm seeing new failures now:
> Failed to retrieve information about 'Microsoft.NETCore.App.Ref' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.netcore.app.ref/index.json'.

Not sure if these are related or deserve their own issue.

**Comment by MattGal** [comment]
See[ this FR discussion](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1653607190124?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1653607190124&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1653607190124) - AzDO is/was having trouble with public feeds; we're on it.

**Comment by BruceForstall** [comment]
I believe this has been fixed now (some AzDO feature was reverted)?

**Comment by BruceForstall** [comment]
@MattGal

**Comment by riarenas** [comment]
Fixing this requires an active change to pipelines. Please re-enable the pipeline to allow usage of secrets from builds from forks.

**Comment by MattGal** [comment]
> I'm seeing new failures now:
> 
> > Failed to retrieve information about 'Microsoft.NETCore.App.Ref' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/d1622942-d16f-48e5-bc83-96f4539e7601/nuget/v3/flat2/microsoft.netcore.app.ref/index.json'.
> 
> Not sure if these are related or deserve their own issue.

@BruceForstall apologies for mixing the two things, I was responding to this one which was a feature rollout by AzDO.  If you're seeing the top comment in this issue still, do exactly what @riarenas says.

**Comment by BruceForstall** [comment]
@riarenas Thanks; I updated the pipeline configuration, and things seem to be working.

@MattGal Yeah, I had assumed from discussion here that some AzDO configuration had been rolled back and things would "just work" afterwards.

**Comment by ViktorHofer** [comment]
I assume this can be closed again now? Feel free to reopen if you still see the issue somewhere.
