### ISSUE TITLE
Question: how could we execute code in a standalone assembly load context?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#69855]
Hi team, I'm trying to execute my code in a separate context, while when I try to use the `AssemblyLoadContext`, I got the error likes follows:

```
System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
```

Sample code:

``` csharp
public sealed class CustomLoadContext : AssemblyLoadContext
{
    private readonly Dictionary<string, string> _assemblyPaths;

    public CustomLoadContext(string[] assemblyPaths)
    {
        _assemblyPaths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var assemblyPath in assemblyPaths)
        {
            // Add the first entry with the same simple assembly name if there are multiples
            // and ignore others
            _assemblyPaths.TryAdd(Path.GetFileNameWithoutExtension(assemblyPath), assemblyPath);
        }
    }

    protected override Assembly? Load(AssemblyName assemblyName)
    {
        if (assemblyName.Name != null 
            && _assemblyPaths.TryGetValue(assemblyName.Name, out var assemblyPath))
        {
            return LoadFromAssemblyPath(assemblyPath);
        }
        return null;
    }
}
```

**Comment by janvorli** [comment]
The error means that you are loading a reference assembly instead of the actual assembly containing the code. So you are probably adding a wrong path to your assemblyPaths.

**Comment by WeihanLi** [comment]
Hi @janvorli @davidfowl , great thanks for your reply, I'm sure that the assembly path exists and is correct, and I add a reproducible test sample here

https://github.com/WeihanLi/dotnet-exec/blob/0789f2127d9ba2a279c52e27eabe8d70e77254f4/tests/IntegrationTest/IntegrationTests.cs#L60

**Comment by huoyaoyuan** [comment]
AFAIK, the ref assemblies should not be used any more after compilation. For execution, you can load every *managed* assembly from the implementation directory, either when creating ALC, or by registering the `Resolving` event.

**Comment by WeihanLi** [comment]
As @janvorli  said, the error is because I'm loading a reference assembly and the reference assembly only has the declaration without implementation
