### ISSUE TITLE
JsonSerializer.Deserialize issue with arrays/lists and whitespace

### ISSUE THREAD

**Issue by jesslilly** [dotnet/runtime#69859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

JsonSerializer.Deserialize throws an exception when there is a an array in the json and the model and some well placed whitespace characters.

### Expected Behavior

I did not expect an error here at all.  I thought the parser would ignore whitespace characters including space, \t, \r, \n, etc.

### Steps To Reproduce

```
using System.Text.Json;

namespace *;

[TestClass()]
public class JsonTests
{
    class MyClass
    {
        public string[] Answers { get; set; }
    }

    [TestMethod()]
    public void Deserialize_Bug()
    {
        // Arrange
        var json = "[{\r\n  \"Answers\": [\"Yes\"]\r\n}]";
        
        // Act
        var actual = JsonSerializer.Deserialize<MyClass[]>(json);

        // throws 
        // System.Text.Json.JsonException: ''0xC2' is an invalid start of a property name. Expected a '"'. Path: $[0] | LineNumber: 1 | BytePositionInLine: 0.'
    }

    [TestMethod()]
    public void Deserialize_Works()
    {
        // Arrange
        var json = "[{\"Answers\": [\"Yes\"]}]";

        // Act
        var actual = JsonSerializer.Deserialize<MyClass[]>(json);

        // Assert
        Assert.AreEqual("Yes", actual[0].Answers[0]);
    }
}
```

### Exceptions (if any)

System.Text.Json.JsonException: ''0xC2' is an invalid start of a property name. Expected a '"'. Path: $[0] | LineNumber: 1 | BytePositionInLine: 0.'

### .NET Version

6.0.300

### Anything else?

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.2.1

C:\Program Files\Microsoft Visual Studio\2022\Professional>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.419 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by eiriktsarpalis** [comment]
I can't reproduce the error using your code. The error suggests you might be deserializing from a different string, could you double check please?

**Comment by jesslilly** [comment]
Hi @eiriktsarpalis.  Thanks for looking at this.  I'm not sure what more information I can give.  Here is a screenshot.

![image](https://user-images.githubusercontent.com/1406490/170542359-54242aad-dd43-4758-b844-76ed6bac1ae3.png)

**Comment by eiriktsarpalis** [comment]
I'm not sure either. Could you try extracting the failing test into a standalone console app that reproduces the error? Ideally it should not have any third-party dependencies.

**Comment by jesslilly** [comment]
I commit the test to my build server and it failed there as well.

Same result when using a console app.  This is a brand-new solution.
![image](https://user-images.githubusercontent.com/1406490/170557817-d86b1d2c-b442-46be-8171-35835c35483b.png)

I was going to try to update my .NET SDK, but it seems like 6.0.300 is already the latest.  (To see if that might fix it)

**Comment by jesslilly** [comment]
@eiriktsarpalis 

I copied this line of code again from the github issue:

``        var json = "[{\r\n  \"Answers\": [\"Yes\"]\r\n}]";

Now it works!  Is there a hidden character in the string?  This string came from a post of an MVC form in ASP.NET.

**Comment by gregsdennis** [comment]
@jesslilly can you zip the solution and attach it?  That way we working with exactly what you have.

**Comment by eiriktsarpalis** [comment]
> Is there a hidden character in the string?

That's very likely. Assuming that's the case then you're hitting by-design behaviour.

**Comment by jesslilly** [comment]
[WebApplication1.zip](https://github.com/dotnet/runtime/files/8781679/WebApplication1.zip)

Here is a solution that reproduces the problem with ASP.NET MVC.

1. Run the solution.
2. Go to https://localhost:7139/Home/Create
3. Remove asdf from the JSON
4. Hit Save
5. You will get the exception in the controller action.

I'm not sure how this would have been designed behavior.  Anyway, thanks for looking into this.  It still feels like a bug.

**Comment by jesslilly** [comment]
OK.  I can no longer reproduce.  Sorry.  There are hidden characters in my string in the example web solution.  I don't know how they got there.

![image](https://user-images.githubusercontent.com/1406490/170571127-9470eb3c-681c-4998-ad97-97ce29c738fd.png)

I think we can close this.

I noticed that vs code shows the hidden characters while visual studio does not.
