### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506) when calling Managed function using C#

### ISSUE THREAD

**Issue by elksson** [dotnet/runtime#69862]
### Description

When calling a managed function from C# using .net 6 I get an application crash which I have not been able to obtain a core dump, windows event error log, or get visual studio to halt on the exception. However the code runs fine when using .net 3.5

### Reproduction Steps

I am not sure how to reproduce this in a small project

### Expected behavior

Managed function should be called and return properly

### Actual behavior

Managed function causes a crash with error code (`0x80131506`) 
and the following line is placed in the visual studio console
The program '[0xB5B8] ConsoleApp1.exe' has exited with code 3221226505 (`0xc0000409`).

### Regression?

.net 3.5

### Known Workarounds

Use .net 3.5

### Configuration

.net 6
Windows 10 20H2
x86

**Comment by elksson** [comment]
@AaronRobinsonMSFT I have visual studio debugger attached when running however even with visual studio setup to break on all exceptions it does not halt instead the process just crashes. I have also configured the registry to capture a core mempory dump on crash however no dump file is created. Finally I have checked the windows event viewer and it shows no failure.

**Comment by elksson** [comment]
I am calling the following function: 

```
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate int PassThruReadVersion(int deviceId, IntPtr firmwareVersion, IntPtr dllVersion, IntPtr apiVersion);
        public PassThruReadVersion ReadVersion;
```

With the c declaration: 

`extern "C" J2534_API_DECL long WINAPI PassThruReadVersion(unsigned long DeviceID, char* pFirmwareVersion, char* pDllVersion, char* pApiVersion);`

**Comment by elksson** [comment]
Something else interesting is that if I run without the debugger attached it does not crash. 
CTRL + F5 in visual studio = no crash
F5 = crash

**Comment by AaronRobinsonMSFT** [comment]
@elksson Can you share how the project was ported to .NET 6?

Calling a native function through a `delegate` has no known issues. Does `J2534_API_DECL` resolve to `cdecl`? It seems to be marked `WINAPI` which is typically `stdcall` on Windows.

What code is acquiring the function pointer?

**Comment by elksson** [comment]
I will check tomorrow on that. As for the code ported to .net a new project was created using VS 2022 and the code files moved into the new project.

**Comment by elksson** [comment]
These are the define(s)

#define WINAPI __stdcall
#define J2534_API_DECL __declspec(dllexport)

**Comment by AaronRobinsonMSFT** [comment]
Then at a minimum, `[UnmanagedFunctionPointer(CallingConvention.Cdecl)]` should be `[UnmanagedFunctionPointer(CallingConvention.StdCall)]`.

**Comment by elksson** [comment]
I have changed the definition to 
[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int PassThruReadVersion(UInt32 deviceId, IntPtr firmwareVersion, IntPtr dllVersion, IntPtr apiVersion);

however the application still crashes with the same error when the debugger is attached.

**Comment by elksson** [comment]
For some reason visual studio was not re-compiling the native code wrapper after the changes.
