### ISSUE TITLE
[NativeAOT] Issue with expressing a Expression<Delegate> in a RD.xml file

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#69875]
The System.Linq.Expression.Test [scenario ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/SequenceTests/SequenceTests.cs#L2958-L2969)requires the below type to be present. 

`  System.Reflection.MissingMetadataException : 'System.Linq.Expressions.Expression<System.Func<System.SByte,System.Boolean>>' is missing metadata. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=392859
`
Adding the following to a RD.xml file results in an [exception ](https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/Common/Compiler/CompilerTypeSystemContext.Validation.cs#L140-L144)in the type creation,

```XML
<Directives>
  <Application>
    <Assembly Name="System.Linq.Expressions">
      <Type Name="System.Linq.Expressions.Expression`1[[System.Func`1[[System.SByte,System.Private.CoreLib],[System.Boolean,System.Private.CoreLib]],System.Private.CoreLib]]" Dynamic="Required All" />
    </Assembly>
  </Application>
</Directives>
```

```
Internal.TypeSystem.TypeSystemException.TypeLoadException
  HResult=0x80131500
  Source=ILCompiler.TypeSystem
  StackTrace:
   at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, String typeName, String assemblyName) in runtime\src\coreclr\tools\Common\TypeSystem\Common\ThrowHelper.cs:line 17
   at Internal.TypeSystem.ThrowHelper.ThrowTypeLoadException(ExceptionStringID id, TypeDesc type) in runtime\src\coreclr\tools\Common\TypeSystem\Common\ThrowHelper.Common.cs:line 51
   at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc type) in runtime\src\coreclr\tools\Common\Compiler\CompilerTypeSystemContext.Validation.cs:line 143
..

```
The following program can be used together with the RD.xml file in the rsp file,

```C#
using System;
using System.Linq.Expressions;

class Program
{
    static void Main()
    {
        //Simply to get System.Linq.Expressions assembly loaded for rd.xml
        ParameterExpression value = Expression.Parameter(typeof(int), "value");
        Console.WriteLine(value.ToString());
    }

}

```

**Comment by MichalStrehovsky** [comment]
The rd.xml is using Func1 but passes 2 generic arguments. The rd.xml should use Func`2. We might need more validation for nonsensical rd.xml inputs.

**Comment by MichalStrehovsky** [comment]
> We might need more validation for nonsensical rd.xml inputs.

On a second thought, the text string is parsed using the custom attributes blob parser and that one doesn't really do user friendly reporting because it's meant to parse IL file format.

All of RD.XML was meant to be [temporary](https://github.com/dotnet/corert/pull/2207#discussion_r87919449), but as things go, nothing is more permanent than a bunch of temporary code.

**Comment by LakshanF** [comment]
Missed the arity number :-(
