### ISSUE TITLE
Regex Source Generator doesn't react when removing the attribute invocation causing it to break the design time build.

### ISSUE THREAD

**Issue by joperezr** [dotnet/runtime#69880]
I noticed that after using the regex source generator in a project, if you remove the partial method that was causing the generator to run, the file produced by the generator is still present and it's contents filled. This causes that if you later decide to, for example, remove the partial keyword of the containing type, then the design-time build will be broken and you will get red squiggles on the editor. Regular build works just fine, but the design time build will be broken until you unload and reload the project again.

Repro steps:

1. Create a simple console app which is using the Regex source generator, like:
```c#
using System.Text.RegularExpressions;

partial class Program
{
    static void Main(string[] args)
    {
        MyRegex().IsMatch("input");
    }

    [RegexGenerator("pattern")]
    private static partial Regex MyRegex();
}
```

2.  Let's say that you decide you don't need regex in your code anymore, so you remove it's use and now leave your code as:
```c#
class Program //<-- Note that because I don't need it any longer, I've marked Program to not be partial any longer.
{
    static void Main(string[] args)
    {
         //.. some other code
    }
}
```

3. Expected: This should just work and the source generator should now empty-out the generated file.
    Actual:

![image](https://user-images.githubusercontent.com/13854455/170585875-f34afa81-9c1a-4de3-94e4-7509a12dcafe.png)

This is most likely because the generator is only setup to listen to events that involve a RegexGenerator attribute for performance reasons, so it doesn't notice when they are removed. We should figure out how to also know when to clear that file without affecting performance.

cc: @stephentoub

**Comment by joperezr** [comment]
One interesting thing I just noticed is that if you have two source generated regexes, and delete one of them, the source generator does indeed pick up that change and updates the generated file to remove the implementation of the one that was removed.

**Comment by stephentoub** [comment]
I expect this is actually an issue with Roslyn rather than with the specifics of the source generator.  What you outline used to result in VS showing a gold bar saying that the source generator stopped producing the file, but it no longer appears to be doing so.  This seems like the same issue as https://github.com/dotnet/roslyn/issues/61162. And the exact same behavior happens with the LibraryImport generator.

cc: @chsienki

**Comment by chsienki** [comment]
Interesting, yep that looks like the same issue. I guess somewhere we're not correctly clearing a cache for a removed input.

**Comment by nurbekdev** [comment]
Hello

**Comment by joperezr** [comment]
Oh I believe you are right, good catch @stephentoub, I'll go ahead and close this one so that it only get's tracked in one place. That said, this might be more noticeable now that we have the analyzer and fixer which is how I noticed it, by applying the codefix and then doing a `ctrl+z` to undo and suddenly my design time build was broken.
