### ISSUE TITLE
Consider caching Utf8JsonWriter and PooledByteBufferWriter on a thread static in JsonSerializer.Serialize

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#69889]
### Description

Looking into the allocation profile for our JSON tech empower benchmark, the allocation overhead for the JsonSerializer itself 

### Configuration

Run this crank command.

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario https --profile intel-lin-app --profile intel-load2-load --application.framework net7.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 7.0.0-preview.6.22275.2 --application.runtimeVersion 7.0.0-preview.6.22276.3 --application.sdkVersion 7.0.100-preview.6.22275.1  --application.dotnetTrace true --application.dotnetTraceProviders gc-verbose
```

This will run the JsonHttps benchmark and it'll spit out an allocation profile that you can view in perfview (alloc tick events).

### Regression?

No it's not

### Data

<HTML>
<BODY>
<TABLE><TR><TD>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>Exc %</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exc</TD><TD> Exc Ct</TD><TD>Inc %</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inc</TD><TD> Inc Ct</TD><TD>Fold</TD><TD>Fold Ct</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;First</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Last</TD></TR><TR><TD>Type System.Text.Json.Utf8JsonWriter &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> 73.5</TD><TD>2,195,098,368.000</TD><TD> 20,668</TD><TD> 73.5</TD><TD>2,195,098,368.000</TD><TD> 20,668</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> 79oEEEDEEDEEEEEDCEEEFEDFEDEEDEED</TD><TD> 21,998.809</TD><TD> 52,258.721</TD></TR><TR><TD>Type System.Text.Json.PooledByteBufferWriter </TD><TD> 16.5</TD><TD> &nbsp;&nbsp;493,749,376</TD><TD> &nbsp;4,649</TD><TD> 16.5</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;493,749,376</TD><TD> &nbsp;4,649</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> 112o3332333332333333233333333333</TD><TD> 22,031.344</TD><TD> 52,235.635</TD></TR><TR><TD>Type Benchmarks.Middleware.JsonMessage &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> &nbsp;9.5</TD><TD> &nbsp;&nbsp;284,879,104</TD><TD> &nbsp;2,682</TD><TD> &nbsp;9.5</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;284,879,104</TD><TD> &nbsp;2,682</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> 00110121121112111111112112222111</TD><TD> 22,016.234</TD><TD> 52,217.968</TD></TR></TABLE>

</BODY>
</HTML>

### Analysis

We have more infrastructure allocation overhead than we do serializing the actual object.

**Comment by davidfowl** [comment]
I'm running this performance test after this change and I'm not seeing a big difference 🤔.

Command:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/json.benchmarks.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/azure.profile.yml --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario https --profile intel-lin-app --profile intel-load2-load --application.framework net7.0 --application.collectDependencies true --application.options.collectCounters true --application.aspNetCoreVersion 7.0.0-rc.1.22413.3 --application.runtimeVersion 7.0.0-rc.1.22413.9 --application.sdkVersion 7.0.100-rc.1.22413.1 --application.dotnetTrace true --application.dotnetTraceProviders gc-verbose
```

<HTML>
<BODY>
<TABLE><TR><TD>Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD>Exc %</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exc</TD><TD> Exc Ct</TD><TD>Inc %</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Inc</TD><TD> Inc Ct</TD><TD>Fold</TD><TD>Fold Ct</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;First</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Last</TD></TR><TR><TD>Type System.Text.Json.Utf8JsonWriter &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> 72.8</TD><TD>2,274,646,784.000</TD><TD> 21,417</TD><TD> 72.8</TD><TD>2,274,646,784.000</TD><TD> 21,417</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> ___40EDEEDEDDEEEECEEEFEEEDEEDEED</TD><TD> 3,523.967</TD><TD> 33,786.321</TD></TR><TR><TD>Type System.Text.Json.PooledByteBufferWriter </TD><TD> 16.9</TD><TD> &nbsp;&nbsp;529,322,496</TD><TD> &nbsp;4,984</TD><TD> 16.9</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;529,322,496</TD><TD> &nbsp;4,984</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> ___12o33333333333233333333333332</TD><TD> 3,547.375</TD><TD> 33,767.268</TD></TR><TR><TD>Type Benchmarks.Middleware.JsonMessage &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> &nbsp;9.6</TD><TD> &nbsp;&nbsp;300,157,952</TD><TD> &nbsp;2,826</TD><TD> &nbsp;9.6</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;300,157,952</TD><TD> &nbsp;2,826</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> ___01o21221122211111211111112221</TD><TD> 3,553.376</TD><TD> 33,764.016</TD></TR><TR><TD>Type System.Byte[] &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD><TD> &nbsp;0.2</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;5,190,632</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;48</TD><TD> &nbsp;0.2</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5,297,120</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;49</TD><TD> &nbsp;&nbsp;0</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0</TD><TD> o__o0o__o________0______________</TD><TD> &nbsp;&nbsp;&nbsp;&nbsp;7.488</TD><TD> 18,760.149</TD></TR></TABLE>

</BODY>
</HTML>


cc @sebastienros

**Comment by davidfowl** [comment]
Why not? I missed that in the PR...

**Comment by eiriktsarpalis** [comment]
I figured it might not be as important given the added overhead of state machines. The benefits in the sync case seem fairly modest and only register for trivially sized object graphs (i.e., those of depth < 2)

**Comment by davidfowl** [comment]
That's pretty reasonable. I think in the benchmark that could be synchronous because the object is tiny and will git in the buffer. It's more problematic in general for 2 reasons:
- When the code doing the serialization doesn't know what object is being serialized or you can't really eye ball the size to know if it'll fit into the buffer.
- Sync + ASP.NET Core = ☠️
