### ISSUE TITLE
LoggerMessage generator generates invalid code for a parameter

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#69893]
### Description

Possibly related to https://github.com/dotnet/runtime/issues/69490

### Reproduction Steps

1) Try compiling this code 
```cs
[LoggerMessage(Level = LogLevel.Information, Message = "No recipients. DiscussionId={DiscussionId} AlertType={AlertType}")]
public static partial void LogNoDicusionRecipients(this ILogger logger, string alertType, int discusionId);
```
2) See that generator haven't generated `var DiscussionId = this._discusionId;` line:

![image](https://user-images.githubusercontent.com/6609929/170705242-d1724124-34af-4779-aecc-53a047f6360e.png)

### Expected behavior

Generator generates valid code

### Actual behavior

Generator generates code that doesn't compile

### Configuration

- .NET 6.0.300 
- Windows 11
- VS 17.2.2
- Microsoft.Extensions.Logging.Generators 6.0.6.21309

**Comment by martincostello** [comment]
Do you have a compiler error or warning somewhere?

There's a typo in your variable name compared to the template string:

`discusionId` (2x`s`) vs. `DiscussionId` (3x`s`)

If you add an extra s to `discusionId` it will probably compile.

**Comment by maxkoshevoi** [comment]
@martincostello Yes, that fixes it, thanks!

I had a `SYSLIB1014	Template 'DiscussionId' is not provided as argument to the logging method` error since source generator generated invalid code.

Can souse generator make it more explicit that it couldn't match parameter to a log placeholder (by generating `#error`)? Or at least not generate a broken code (by skipping such parameters)

**Comment by maryamariyan** [comment]
Seems like the issue was that the message template argument had a typo mismatch with the method variable name. Your recommendation seems like a nice improvement, though I think it is ok to close as it is a low priority improvement.
