### ISSUE TITLE
[NativeAOT] System.Linq.Expression.Tests.Expression_Tests.TestCallStaticMethodsByName - add rd.xml

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#69928]
This method tests all known [Queryable](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/tests/SequenceTests/SequenceTests.cs#L527-L584) methods and these need to be added to the rd.xml file

**Comment by MichalStrehovsky** [comment]
It might be enough to just add the `Queryable` type do RD.XML directly with `Dynamic="Requires All"`. We go over all the generic methods on the type and try to instantiate it with something suitable. The "something suitable" should work for all reference types at runtime. It looks like it's all that's needed for the test.
