### ISSUE TITLE
[libraries-pgo] Assertion failed '(m_block->bbNext == nullptr) || (m_block->bbNext->bbPrev == m_block)' during 'Update flow graph opt pass'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#69938]
Seen in recent libraries-PGO runs.
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1783685&view=results
Helix job name: net7.0-windows-Release-x64-CoreCLR_checked-fullpgo-Windows.10.Amd64.Open
Console log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4599baa7e57b45ff9f/System.Diagnostics.Tracing.Tests/1/console.93fb3cf5.log?helixlogtype=result

```scala
Assert failure(PID 10096 [0x00002770], Thread: 5020 [0x139c]): Assertion failed '(m_block->bbNext == nullptr) || (m_block->bbNext->bbPrev == m_block)' in 'Microsoft.Diagnostics.Tracing.TraceEvent:PayloadString(int,System.IFormatProvider):System.String:this' during 'Update flow graph opt pass' (IL size 1323; hash 0x7a8415c5; Tier1)

    File: D:\a\_work\1\s\src\coreclr\jit\block.h Line: 1535
    Image: C:\h\w\AF700999\p\dotnet.exe
```

**Comment by AndyAyersMS** [comment]
Can't repro this, but looking at the crash dump:
```
clrjit!assertAbort
clrjit!BasicBlockIterator::operator++
clrjit!Compiler::optMarkLoopRemoved
clrjit!Compiler::optUpdateLoopsBeforeRemoveBlock
clrjit!Compiler::fgRemoveBlock
clrjit!Compiler::fgOptimizeEmptyBlock
clrjit!Compiler::fgUpdateFlowGraph
```
My mermaid-fu is weak, but it looks like from the dump that BB33 got removed but somehow is still being included in the loop iteration, and so BB33 violates the `x == x->bbNext->bbPrev` check done by the iterator. In the below the solid links are `bbNext` and the dotted `bbPrev`. (I really wanted BB33 to appear in between BB32 and BB34, can't figure out how to make that happen.

```mermaid
flowchart TD
   BB32 ---> BB34
   BB33 --> BB34
   BB33 -.-> BB32
   BB34 -.-> BB32

```

**Comment by AndyAyersMS** [comment]
I can repro now from the runfo download.

Suspect `optUpdateLoopsBeforeRemoveBlock` doesn't properly handle the case where `lpTop` is not `lpEntry`. In this case we are able to prune the loop backedge, and we have a mid-entry loop, so the blocks above the entry become unreachable, but we don't remove the loop.

It's not clear to me if we can be sure that by removing the last edge to `lpTop` the loop vanishes but it seems safer to conclude that then to leave the loop around pointing at removed blocks.
