### ISSUE TITLE
Regex.Match(string input, int startat) fails with ^ prefix.

### ISSUE THREAD

**Issue by TiagoOliveiraMarques** [dotnet/runtime#69949]
### Description

When writing a regular expression starting with `^` (e.g.: `^\d+`), the methods Match and Matches which accept a `startat` argument will only match if `startat` is equal to zero. 

### Reproduction Steps

```csharp
using System.Text.RegularExpressions;

var regex = new Regex(@"^\d+");
var text = "123lorem456";
var match = regex.Match(text, 8);

Console.WriteLine(match.Success);
Console.WriteLine(match.Value);
Console.WriteLine(match.ValueSpan.ToString());
```

The regex match none of the numbers because "123" is before the position 8 of the string and "456" is not at the start of the string.

### Expected behavior

In the reproduction above, I was expecting to have a match on "456".

### Actual behavior

No match is found.

### Regression?

Don't know.

### Known Workarounds

The string to match can be sliced and allocated into a new string, in order to use the Regex.Match method without the `startat` argument. This will result in extra allocations which can be very undesirable when dealing with large strings.

E.g.

```csharp
using System.Text.RegularExpressions;

var regex = new Regex(@"^\d+");
var text = "123lorem456";

// This one will match
var newText = text.AsSpan().Slice(8).ToString();
var match = regex.Match(newText);

Console.WriteLine(newText);
Console.WriteLine(match.Success);
Console.WriteLine(match.Value);
Console.WriteLine(match.ValueSpan.ToString());
```

### Configuration

**Which version of .NET is the code running on?**
6.0.101

**What OS and version, and what distro if applicable?**
Edition	Windows 11 Home
Version	21H2
Installed on	‎18/‎12/‎2021
OS build	22000.675
Experience	Windows Feature Experience Pack 1000.22000.675.0

**What is the architecture (x64, x86, ARM, ARM64)?**
x-64

**Do you know whether it is specific to that configuration?**
Don't think so.

**Comment by stephentoub** [comment]
This is by design. You want the overloads that take an `int beginning` not `int startat`; those mean two very different things.

**Comment by danmoseley** [comment]
Earlier similar discussion: https://github.com/dotnet/runtime/issues/58794

To summarize the difference (if only for my benefit) 

1. the (input, startat) overload means
    - ignore any matches that start before the startat index
    - with special magic such that \G treats startat as the start of the input
    
    (this means that you can prefix your pattern with \G in order to require that any match start exactly at startat. Everything else is as normal, including behavior of \A, ^, and the Index of any match object)

2. the (input, beginning, length) overload means
     - treat input as if it was input.Substring(beginning, length)
     - except that the Index of any match object is relative to original input

    (this means that any zero-width assertions or anchors at the start or end of the pattern cannot see anything outside of the specified range; for example a leading \A, \G, or ^ is satisfied at "beginning")

[test program](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7NAExAGoAfAAQCYBGAWACgKAGAAgpoDoARASwEMA5nggBnDLzCiA3IxbsuAFRgIMnAEoxBOADb8oAUQQAHWKNG8IeGY0YA3fa1FgYefZdGsAvKzwwA7qwAFADKGFC8eIJorGERUTGRGIl4GACUANoAuqwA3oyshcGsAETA+iUxZRUxzDEAzKxpaAVFQaXlUJUd+p3ddayNza2F7dVdVQBmEBB9MVTzTS0MRcXj3SXTszWDDUsja3OlW0cLg/srbT0TxzOnMSgXq2NHmzOsR/UPT1cUFCUAHQA4q8TjszkNls92P9gaC7jsvudmqwAPSo1jApzGGBgAQ6D4wAAW/DsligB3af0BAEF4dsbhCfqMYbT6Z89sNLizqQC6Ts3hAEBzWI8UUVKayggB+AA8Xi2aXZiM5UN+/06AIAWhtOlt+pzWAdWABfWQMOQ0ACcQRKxn4GAwMCgeFYZFYkWMOAwbqcGH0/owqOAWkieEigl9OlcggwRIBeBKaXN01g/DAROCDigThcbgiEA9rucrncYjSjHy3NYmkEKlYsG8vgCNa0KiCJfzlk4AEknQBbGgxWsqADyxgkVlEnAAwhB+8ZeNHCMmDhw2J7vU3O2XewOqObVtnWBBJpNRDAfT4dwW9zB+/VD0Vj9GonHt3nd337ygn4UDnO1gQNGnAAOoRE6tq5MwJoxLkNAmt4XgAHylDEsCcIoEBxBGQQopuyQnmeF6Ea+sZEquFrVse/ZsD4GEALIOhmQQEZRqyAaIwEwGBEEwKE4QRpwABi0D9g6UEwfBiHut0tGcCEOBgC45gxEE8mKcpMDmKw0qlKwDr6SQrDyT2eCEPWIClEmaSUQcNE0E2jHMUSrF4F6hGnuel7sUUnHcbxvCQThUQiWJEklBk4gBg6XjSTk0EmrkVAyWhJlcJpKmiDEXkkWpg4KUpWW6fphklKwxkFWZFkIKwVklDZdnUY4/ZUE5PFMRgLEETlxGXjEZFxr5hQcDaIWCGFUDiRgtoZCGghhhGcUIQNMZxnFKUJVJ9QmnJVCFVpqlEd5pFrUS+X7Zl2meHp5VlRVJn7dVlnWbZTVHi1jT0R1LluR5hXAOuQS5f1rCDRRw2sNwMDADgE00uYzoza1B3FV4PgPqj12sAAZDjwQAIQo1dOlkO6KPPbV6MmfUvbmfWxkg+klEmkAA=_)
  
As mentioned in the linked issue, it would be reasonable for IsMatch to have the same two overloads. It would also be reasonable for Matches to have them, as far as I can see.

**Comment by danmoseley** [comment]
Incidentally, we apparently have zero positive tests for these overloads (at least that run against .NET Core), let alone for the subtle behaviors described. It would be good to harvest some out of the test program above.

**Comment by danmoseley** [comment]
I made the doc updates https://github.com/dotnet/dotnet-api-docs/pull/8116
