### ISSUE TITLE
ildasm and ilasm round trip can fail with function pointers on macOS

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#69952]
### Description

Using function pointers (specifically the `unmanaged` callconv (see documentation [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers#function-pointers-1) in the second code box)), you can create a binary that cannot go through ilasm after it goes through ildasm.

Edit: this doesn't seem to be an issue on the Windows version according to others, but is on the macOS version.

### Reproduction Steps

The following code creates code that I can ildasm but not again ilasm:
```cs
((delegate* unmanaged<void>)null)();
```
Which makes the following IL code (which is possibly incorrect / not desired? since other unsupported callconvs probably end up with the same - I have not tested this though):
```msil
calli unmanaged void()
```
Which ilasm cannot compile because it doesn't recognise the calling convention `unmanaged`.
If I use Stdcall (`delegate* unmanaged[Stdcall] <void>` -> `unmanaged stdcall`) or Cdecl (`delegate* unmanaged[Cdecl] <void>` -> `unmanaged cdecl`) it can work it out, but this C# code uses the platform default calling convention, which ildasm/ilasm cannot comprehend.

### Expected behavior

ilasm understands the `calli unmanaged void()` instruction

### Actual behavior

ilasm doesn't understand the `calli unmanaged void()` instruction and fails to create an assembly

### Configuration

I was using runtime.osx-x64.Microsoft.NETCore.ILDAsm 7.0.0-preview.4.22229.4 
I first noticed it on sharplab.io, which uses a modified version of the Mobius.ILasm, which means it also doesn't work there @kkokosa.

**Comment by jkotas** [comment]
This works fine with ilasm/ildasm that lives in this repo.

If it is broken in Mobius.ILasm, please open an issue in https://github.com/kkokosa/Mobius.ILasm repo.

**Comment by hamarb123** [comment]
You are right, something funny was happening with my environment variables. Thanks!
