### ISSUE TITLE
Reading and Installing specific dotnet workload versions?

### ISSUE THREAD

**Issue by StachuDotNet** [dotnet/runtime#69951]
There [doesn't seem to be](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-install) any documentation of how to install a dotnet workload at a specific version, or even how to read such once already installed. (such details are not included in `dotnet workload list`)

Is there an undocumented way to do this, an intention to specific _not_ allow version-locking, or an opportunity for a feature here? Or is the version bound exactly to the .NET SDK version (i.e. there are no 2 possible workload versions for `wasm-tools` for one version of the .NET SDK)

**Comment by filipnavara** [comment]
The issue belongs to dotnet/sdk. There is a way to lock a version with the `--from-rollback-file` switch available on `dotnet workload update` and `dotnet workload install` commands (the later since 6.0.300 SDK). Example: https://gist.github.com/filipnavara/4611f15c9a3045108eeae5a98750f64f

**Comment by jeffhandley** [comment]
I'm closing this issue in dotnet/runtime. If needed, please file a new issue in dotnet/sdk. Thanks.
