### ISSUE TITLE
"HttpClient TryAddWithoutValidation" problem

### ISSUE THREAD

**Issue by cuicuicuinice** [dotnet/runtime#69967]
### Description

HttpClient添加头部，TryAddWithoutValidation的含义是不做验证之间添加，但是他任然会做验证和转换，并将类似“cookie”转为“Cookie”，“etag”转为“ETag”等等。

HttpClient adds headers. The meaning of TryAddWithoutValidation is not to add between validations, but it will still do validation and conversion, and convert "cookie" to "Cookie", "etag" to "ETag" and so on.

### Reproduction Steps

var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.TryAddWithoutValidation("etag","")

### Expected behavior

![image](https://user-images.githubusercontent.com/34976688/170878110-e06b2e38-5e22-4a43-af16-0d8c77b93a5f.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/34976688/170878146-10e7b361-79d1-4a81-ac2b-93d89ea53702.png)

### Regression?

测试使用的是net6。

The test uses net6.

### Known Workarounds

![image](https://user-images.githubusercontent.com/34976688/170878231-531e68b8-1182-4c93-b663-e40b405fde30.png)
![image](https://user-images.githubusercontent.com/34976688/170878252-f5c66d35-4e2b-4af7-b0f7-0bdd66437998.png)

删除“ TryGetHeaderDescriptor(name, out HeaderDescriptor descriptor)”，
并将“TryAddWithoutValidation(descriptor, value)”改为“new HeaderDescriptor(name)”；

remove "TryGetHeaderDescriptor(name, out HeaderDescriptor descriptor)",
and change "TryAddWithoutValidation(descriptor, value)" to "TryAddWithoutValidation(new HeaderDescriptor(name))"

### Configuration

NET:net6
OS：windows10
arch：x64

### Other information

没了。
No.

**Comment by halter73** [comment]
Why does the capitalization of the request header matter?


Kestrel also normalizes the casing of "known" request and response header names like "Etag" too when reading and writing them. This is done for performance rather than validation. Both "etag" and "Etag" are valid HTTP/1.1 headers[1] , but since HTTP header names are supposed to be case insensitive, it can be faster to use common logic to write the header name that always uses the "known" casing. I don't think people have complained about Kestrel doing this. Certainly not too many people at least.

1. Only "etag" is valid for HTTP/2 since HTTP/2 headers [must be lowercase](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2), so maybe using HTTP/2 is your workaround.

**Comment by MihaZupan** [comment]
As Stephen said, header names are supposed to be case-insensitive. Is this behavior actually presenting issues with a real-world app/server for you?

**Comment by cuicuicuinice** [comment]
> Why does the capitalization of the request header name matter?
> 
> Kestrel also normalizes the casing of "known" request and response header names like "Etag" too when reading and writing them. This is done for performance rather than validation. Both "etag" and "Etag" are valid HTTP/1.1 headers[1] , but since HTTP header names are supposed to be case insensitive, it can be faster to use common logic to write the header name that always uses the "known" casing. I don't think people have complained about Kestrel doing this. Certainly not too many people at least.
> 
> 1. Only "etag" is valid for HTTP/2 since HTTP/2 headers [must be lowercase](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2), so maybe using HTTP/2 is your workaround.

---

规范确实如此，但是真实需求却是复杂的，这种非标接口的厂商也确实存在。
目前而言，对接的一个大厂商就是这种设置，某些标准header需要小写。
况且，作为框架，本身应该给出一种多余选择，保证其应用面，例如pyhthon就可以传递标准小写header。
而且“TryAddWithoutValidation”的含义，目的不就是“不验证添加head”吗？那既然给出这样接口，为什么还要去验证？


The specification is true, but the real requirements are complex, and manufacturers of such non-standard interfaces do exist.
At present, a big manufacturer of docking is this setting, and some standard headers need lowercase.
Moreover, as a framework, it should give an extra option to ensure its application, for example, pyhthon can pass standard lowercase headers.
And the meaning of "TryAddWithoutValidation", isn't the purpose of "adding head without validation"? Then since such an interface is given, why do you need to verify it?

**Comment by cuicuicuinice** [comment]
> As Stephen said, header names are supposed to be case-insensitive. Is this behavior actually presenting issues with a real-world app/server for you?

---

是的，有些接口厂商就是这种设置，所以有这方面需要。

Yes, some interface manufacturers have this setting, so there is a need for this.

**Comment by cuicuicuinice** [comment]
> Why does the capitalization of the request header name matter?
> 
> Kestrel also normalizes the casing of "known" request and response header names like "Etag" too when reading and writing them. This is done for performance rather than validation. Both "etag" and "Etag" are valid HTTP/1.1 headers[1] , but since HTTP header names are supposed to be case insensitive, it can be faster to use common logic to write the header name that always uses the "known" casing. I don't think people have complained about Kestrel doing this. Certainly not too many people at least.
> 
> 1. Only "etag" is valid for HTTP/2 since HTTP/2 headers [must be lowercase](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2), so maybe using HTTP/2 is your workaround.

---

规范确实如此，但是真实需求却是复杂的，这种非标接口的厂商也确实存在。
目前而言，对接的一个大厂商就是这种设置，某些标准header需要小写。
况且，作为框架，本身应该给出一种多余选择，保证其应用面，例如pyhthon就可以传递标准小写header。
而且“TryAddWithoutValidation”的含义，目的不就是“不验证添加head”吗？那既然给出这样接口，为什么还要去验证？
The specification is true, but the real requirements are complex, and manufacturers of such non-standard interfaces do exist.
At present, a big manufacturer of docking is this setting, and some standard headers need lowercase.
Moreover, as a framework, it should give an extra option to ensure its application, for example, pyhthon can pass standard lowercase headers.
And the meaning of "TryAddWithoutValidation", isn't the purpose of "adding head without validation"? Then since such an interface is given, why do you need to verify it?

![image](https://user-images.githubusercontent.com/34976688/172282545-f95f50f9-7a9c-49a1-bd5d-53f50df6913e.png)

**Comment by cuicuicuinice** [comment]
> Why does the capitalization of the request header name matter?
> 
> Kestrel also normalizes the casing of "known" request and response header names like "Etag" too when reading and writing them. This is done for performance rather than validation. Both "etag" and "Etag" are valid HTTP/1.1 headers[1] , but since HTTP header names are supposed to be case insensitive, it can be faster to use common logic to write the header name that always uses the "known" casing. I don't think people have complained about Kestrel doing this. Certainly not too many people at least.
> 
> 1. Only "etag" is valid for HTTP/2 since HTTP/2 headers [must be lowercase](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2), so maybe using HTTP/2 is your workaround.

---
Thank you very much for your reply.
After testing and careful checking, the other party is indeed using http2.0.

httpClient only needs to enable Version 2.0, and then use TryAddWithoutValidation, the standard header will be lowercase.

thank you so much.

**Comment by cuicuicuinice** [comment]
> As Stephen said, header names are supposed to be case-insensitive. Is this behavior actually presenting issues with a real-world app/server for you?

---

Thank you very much for your reply.
After testing and careful checking, the other party is indeed using http2.0.

**Comment by cuicuicuinice** [comment]
httpClient only needs to enable Version 2.0, and then use TryAddWithoutValidation, the standard header will be lowercase.

![image](https://user-images.githubusercontent.com/34976688/172284179-1a8a213c-0247-4e7d-a136-82c934a7ecbc.png)
![image](https://user-images.githubusercontent.com/34976688/172284221-b6868c89-f861-47d9-b909-f2331e37954e.png)

**Comment by MihaZupan** [comment]
It will send them lowercase when talking to an HTTP/2 server (because the spec demands it).
When talking with an HTTP/1.1 server, it will send the same bytes no matter what you set as the `DefaultRequestVersion`.

Are you sure your screenshot is correct when it reports `GET / HTTP1.1`?

**Comment by cuicuicuinice** [comment]
> It will send them lowercase when talking to an HTTP/2 server (because the spec demands it). When talking with an HTTP/1.1 server, it will send the same bytes no matter what you set as the `DefaultRequestVersion`.
> 
> Are you sure your screenshot is correct when it reports `GET / HTTP1.1`?

嘿...还真是   明明设置了2.0，怎么还是1.1.............

Hey... It's really 2.0, so why is it still 1.1............
