### ISSUE TITLE
Missing authorship information on 70 - 80 commits authored by @4creators

### ISSUE THREAD

**Issue by 4creators** [dotnet/runtime#69968]
Unfortunately it is impossible for me to find any information on commits authored by me in historical repos migrated into dotnet/runtime. As CLA does not cover authorship reassignment IMHO this situation violates copyright laws quite seriously. Is there any chance it will be corrected?

**Comment by jkotas** [comment]
The commit authorship was preserved during the repo migration.

Try: https://github.com/dotnet/runtime/commits?author=4creators . It shows all commits made by you, including the ones that were migrated from historical repos.

**Comment by stephentoub** [comment]
These also all show up with a `git log --author="Jacek Blaszczynski"` command.

**Comment by ericstj** [comment]
@4creators can you have a look at the responses from @jkotas and @stephentoub and let us know if this answers your question?  Thanks!

**Comment by buahaha** [comment]
I want to know what my dad was doing. Please additional h@lp. Some strange artifact in vision algorithms, parasail, proteins... But I'm missing more accurate info. I don't know if it's the lab work, he can't talk about, or just some passion he had to his study of DNA. [Jacek's Twitter account](https://twitter.com/4creators)
