### ISSUE TITLE
[API Proposal]: JsonSerializerOptions available via Action

### ISSUE THREAD

**Issue by Krzysztofz01** [dotnet/runtime#69972]
### Background and motivation

Serialization methods available in the ```JsonSerializer``` allow the pass an optional ```JsonSerializerOptions``` object. By deciding on the use of non-standard options, we must create a new ```JsonSerializerOptions```  instance. It seems to me that it might be a good idea to add an alternative method from to pass those options via ```Action<JsonSerializerOptions>```. A lot of developers like this ,,fluent'' approach, and thanks to ASP.NET and popular .NET libraries this options passing approach is very common. Adding such additional methods with ```Action<JsonSerializerOptions>``` params would not interfere with the existing solution. I am looking forward to opinions about my proposal and for the green light to implement this feature If it met with a positive opinion.

### API Proposal

```csharp
public static class JsonSerializer
{
    // A quick example of a adapter approach for the Action implementation (we can also use JsonSerializer internals)
    public static string Serialize<TValue>(TValue value, Action<JsonSerializerOptions>? options = null)
    {
        var jso = new JsonSerializerOptions();
        options?.Invoke(jso);
			
        return JsonSerializer.Serialize(value, jso);
    }
}
```

### API Usage

```csharp
public static class JsonSerializer
{
    public static string Serialize(object? value, Type inputType, Action<JsonSerializerOptions>? options = null);
}

public static class Program
{
    public static void Main()
    {
        var myObject = new ExampleClass();

        var currentWay = JsonSerializer.Serialize(myObject, new JsonSerializerOptions
        {
            IgnoreNullValues = true
        });

        // One-liner
        // var newWay = JsonSerializer.Serialize(myObject, opt => opt.IgnoreNullValues = true);

        var newWay = JsonSerializer.Serialize(myObject, opt =>
        {
            opt.IgnoreNullValues = true
        });

    }
}
```

### Alternative Designs

The whole implementation of this approach can be done with extension methods, so there is no requirement to introduce changes to the ```JsonSerializer``` class itself.

### Risks

There is no risk because the existing API would not be modified, only additional methods will be added (using extension methods, the target class will not be modified at all).

**Comment by Krzysztofz01** [comment]
Here is a example of the ```JsonSerializer.Write.String``` methods using the serializer internals: https://github.com/Krzysztofz01/runtime/commit/2fcc93f5b3f104a21759ad98ba096efe30f4d2ad

**Comment by huoyaoyuan** [comment]
`JsonSerializerOptions` is immutable after use, and very heavy to create one. It not just an "option", but caches all the reflection and converter information.
Such fluent pattern would be very inefficient.

**Comment by davidfowl** [comment]
This method seems unnecessary and @huoyaoyuan has a great point, it's better to cache and reuse instances of JsonSerializerOptions.

**Comment by krwq** [comment]
I agree with the statements above - adding this API would encourage bad patterns - the idea is that internally JsonSerializerOptions are a cache for internal contracts for how serialization should happen. Building that cache is not cheap and it's essentially much slower to rebuild it on i.e. every web request than re-use the same cache across multiple web requests.

I'm closing this as `won't fix`.
