### ISSUE TITLE
BigInteger multiplication result has incorrect sign

### ISSUE THREAD

**Issue by slozier** [dotnet/runtime#69970]
### Description

For certain BigInteger values (e.g. 0x100000000, 0x1000000000, 0x10000000000, ...), the multiplication of signed and unsigned values results in an unsigned value.

### Reproduction Steps

```c#
var a = (BigInteger)0x100000000;
Debug.Assert(-a*a == -(a*a));
```

### Expected behavior

The result of `-a*a` should be negative.

### Actual behavior

The result of `-a*a` is positive...

### Regression?

This works properly in .NET 6 and all previous releases.

### Configuration

Running on 7.0.100-preview.4.22252.9

**Comment by danmoseley** [comment]
Possibly related to #59525?

**Comment by wzchua** [comment]
I don't think so, that's was a bug in right shift

**Comment by am11** [comment]
The result is correct for `a <= 0x7FFFFFFF`.
