### ISSUE TITLE
Avoid duplicate cmp instruction, avoid boolean zero extension

### ISSUE THREAD

**Issue by thinkbeforecoding** [dotnet/runtime#70003]
I'm working on comparison optimization for the F# compiler to implement branchless compare https://github.com/dotnet/fsharp/issues/13098

The following implementation improves average performance, using only a cgt - clt:

![image](https://user-images.githubusercontent.com/146717/171125704-bc9ba7b4-1153-485b-b008-01101f3b96d6.png)

![image](https://user-images.githubusercontent.com/146717/171126360-f273ebb4-914b-44f0-bdf3-b81f7087a20e.png)

However, I noticed that the same cmp ecx edx instruction is issued twice, and this is unnecessary as setg and movzx don't change flags.

I also thought that the following version would be even shorter:

![image](https://user-images.githubusercontent.com/146717/171127103-b7a4e766-15e2-497a-be9e-edb3152f9298.png)

![image](https://user-images.githubusercontent.com/146717/171127174-bc7d9383-e7b3-4c25-99ab-e30ff071196a.png)

but it's actually longer. The result from cgt/clt is zero extended with movzx even if we use only the lower byte part for the subtraction, then is sign extended to 32bits.

The result code could be:

![image](https://user-images.githubusercontent.com/146717/171128348-a98d725f-eb2f-400a-9be5-108d35a5340e.png)

If someone is ok to guide me through this kind of JIT optimization, I'd happily implement it.

 

category:cq
theme:codegen
skill-level:intermediate
cost:medium
impact:medium

**Comment by EgorBo** [comment]
I assume it's not possible to express this in pure C# and F# right? (relying on cmp's return value as int, only maybe with Unsafe.As)

**Comment by tannergooding** [comment]
> I assume it's not possible to express this in pure C# and F# right?

Right. There is now a proposal for C# to handle `cmp ? 0 : 1` as emitting just `cmp` however: https://github.com/dotnet/roslyn/issues/61483

> .NET 7.0 codegen is different:

So almost there, its just missing the chance to remove the second compare.

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib.
Moving to Future as we are approaching .NET 7 code complete date.

**Comment by thinkbeforecoding** [comment]
Looking at the code in https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/codegenxarch.cpp, 
I've seen that there already seems to have logic to avoid the movzx instruction when return type is known to be a byte:

https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/codegenxarch.cpp#L1433

The logic to see if emitting a cmp based on existing flags also exists...

https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/codegenxarch.cpp#L6464

But how is the genCompareInt method determining the targetType (it's using tree->TypeGet()) ? The clt/cgt IL instruction specify no return type.. the the type is maybe conditioned by the next IL instruction ?

**Comment by EgorBo** [comment]
cc @TIHan

**Comment by TIHan** [comment]
@thinkbeforecoding I made a PR to resolve this in case you are interested: https://github.com/dotnet/runtime/pull/81143

**Comment by thinkbeforecoding** [comment]
Definitely! Thank you.
The PR will also give me hints where to look at next time I see such possible optimization.

**Comment by TIHan** [comment]
@thinkbeforecoding - The other PR is closed, but I made a new one: https://github.com/dotnet/runtime/pull/82750

It's still work-in-progress, but the implementation of it is a lot more straightforward than my previous PR. This is because we recently added the ability to look back at more than one previous instruction, which allows us to see if the `cmp` is redundant or not.
