### ISSUE TITLE
What was the reason to inject DispatchTailCalls method after profiler instrumentation in .NET 7.0?

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#70013]
Hi, could you please tell us what was the reason to inject `DispatchTailCalls` method after profiler instrumentation in .NET 7.0? Some our .NET 7.0 tests became 🔴. The fast investigation shown that all our injections was surrounded Enter/Leave for `DispatchTailCalls` callbacks. It broken our profiler down, because we didn't expect that in code. Hotfix was disable the ELT injection for all `DispatchTailCalls` methods. Thanks in advance...
```
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B728E00 res=ok fuid=00200001 fname='Main' cname='JetBrains.Profiler.Tests.RealApplications.Program'
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=00200001
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B776EE0 res=instrumentation_helper
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0AF7CF40 res=ok fuid=001053A1 fname='DispatchTailCalls' cname='System.Runtime.CompilerServices.RuntimeHelpers'
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::RdtscFastBegin var=0AD04CEC c=18
000047BC 1 03077968 PTIProf::RdtscFastLeave fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::FunctionIdMapper fid=0B776F10 res=instrumentation_helper
000047BC 1 03077968 PTIProf::RdtscFastEnter fuid=001053A1 ; <=== !!!
000047BC 1 03077968 PTIProf::RdtscFastMeasure var=0AD04CEC c=18 st=0
000047BC 1 03077968 PTIProf::RdtscFastLeave fuid=001053A1 ; <=== !!!
000047BC 1 03077968 ERROR: No end IL inject was called
	'[location] = C:\Work\dotnet-products\Profiler\Kernel\Windows\Native\Solution\core\src\profilers\performance\TemplatePerformanceThread.Header.h(66)'
	'[function] = unsigned __int64 *__thiscall jbprof::PerformanceInjectThread::Leave(const unsigned __int64 &,const unsigned int)'
```

**Comment by EgorBo** [comment]
cc @jakobbotsch

**Comment by tommcdon** [comment]
cc @davmason

**Comment by ww898** [comment]
Hi @jakobbotsch,

> Has the behavior of these callbacks changed since .NET 6? I am not aware of any changes related to `DispatchTailCalls` in .NET 7 vs .NET 6.

Yes the behavior was changed: no Enter/Leave callbacks for `DispatchTailCalls` in .NET v6.0.5 at all, but they unexpectedly appeared in .NET v7.0-preview1 under Windows x86 in instrumentation mode. So, I have to filter them out in profiler.

**Comment by jakobbotsch** [comment]
> Yes the behavior was changed: no Enter/Leave callbacks for `DispatchTailCalls` in .NET v6.0.5 at all, but they unexpectedly appeared in .NET v7.0-preview1 under Windows x86 in instrumentation mode.

What does the instrumented program look like? On x86 we should use this mechanism only in very rare cases, so that might be where the behavior has changed.

**Comment by jakobbotsch** [comment]
Ah, I can see why the behavior has changed. It is a regression introduced by #56669. The change to `fgCanTailCallViaJitHelper` is wrong, thanks for the report!

Note that the behavior of when this `DispatchTailCalls` call will show up depends on platform. On non-x86 platforms you will see it show up for cases where the tailcall cannot be dispatched as a jump instruction and on x86 you will still see it show up if the calling function contains `stackalloc`.
