### ISSUE TITLE
CultureInfo fr-CH, wrong NumberDecimalSeparator

### ISSUE THREAD

**Issue by piferrari** [dotnet/runtime#70020]
### Description

When i format a double to string with 

```csharp
CultureInfo cultureInfo = new CultureInfo("fr-CH");

CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;
CultureInfo.DefaultThreadCurrentCulture = cultureInfo; 
CultureInfo.CurrentUICulture = cultureInfo; 
CultureInfo.CurrentCulture = cultureInfo;

double dbl = 46.12345;
string str = String.Format(cultureInfo, $"{dbl}");
```
I obtain `46,12345` but in "fr-CH" the decimal separator is the dot in the default Windows fr-CH installation.

I expected to get `46.12345`.

I can change this behavior with this line of code
```csharp
cultureInfo.NumberFormat.NumberDecimalSeparator = ".";
```

and all work fine. But my question is: why MAUI doesn't use the dot character ?

If i create a Console application with dotnet 5 and VS 2019 with the exact same code on the same computer i obtain the expected result `46.12345`.

Best regards.

P.

### Steps to Reproduce

1. Create a default MAUI app
2. In the MauiProgram.cs, copy/paste the code above (in the description)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Pixel 5 - API 30 default emulator; Samsung Galaxy S8+

**Comment by tarekgh** [comment]
.NET picking up the Unicode standard behavior which is defined by CLDR. Looking at the CLDR data, looks such cultures is using `,` as decimal separator and not `.` https://github.com/unicode-org/cldr/blob/876c6aa83ec89bbd288811dcd9d8bfa9609ce059/common/main/fr.xml#L7752. We stick we Unicode standard behavior. I am seeing the issue is raised to CLDR to fix and tracked by the ticket https://unicode-org.atlassian.net/browse/CLDR-13877.

**Comment by tarekgh** [comment]
https://github.com/dotnet/runtime/issues/37743

**Comment by piferrari** [comment]
_Please confirm this is the case._ : Yes it is
![image](https://user-images.githubusercontent.com/736192/171479190-31a7ed4f-5bda-4e0f-a6cd-bb7d1b7d4b0c.png)

```ps
cultureInfo = new CultureInfo("fr-CH") give 46.12345
cultureInfo = new CultureInfo("fr-CH", true) give 46.12345
cultureInfo = CultureInfo.GetCultureInfo("fr-CH") give 46,12345
cultureInfo = new CultureInfo("fr-CH", false); give 46,12345
```

Ok. If I understand correctly, the user parameters override the default fr-CH configurations.
It's possible that these user parameters are defined by the domain administrator? All of my computers are part of a school domain.

**Comment by tarekgh** [comment]
> Ok. If I understand correctly, the user parameters override the default fr-CH configurations.

Yes, but it depends on how you create the culture if you specify want the user override.

> It's possible that these user parameters are defined by the domain administrator? All of my computers are part of a school domain.

Using the workaround mentioned above.

```C#
cultureInfo.NumberFormat.NumberDecimalSeparator = ".";
```
will be simpler than forcing the user settings.  Having the administrator override the settings will not fix the issue in all places if other parts (like MAUI libraries or other libraries) create cultures without the user overrides. I would say you can use the following code to execute in your app initialization and that should make everything work everywhere:

```C#
            if (CultureInfo.CurrentCulture.Name == "fr-CH") // apply that only when the user is using fr-CH culture
            {
                CultureInfo defaultCulture = new CultureInfo("fr-CH");
                defaultCulture.NumberFormat.NumberDecimalSeparator = "."; //can override any other properties as needed.

                CultureInfo.DefaultThreadCurrentCulture = defaultCulture;
                CultureInfo.CurrentCulture = defaultCulture;
            }
```
