### ISSUE TITLE
Getting No Names in regioninfo class on IOS

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#70028]
_From @whann0205 on Tue, 31 May 2022 11:59:45 GMT_

Dont know if this is the correct place to report that question.
If not please be so kind and direct me to the correct forum or
forward my issue to them.

Environment:
Win10 
Visual Studio 2022 Preview lastest revision all updates installed
Net Maui lastest revision all updates installed
MacOS Monterrey on MacBook Air M1 
Visual Studio 2022 Preview lastest revision all updates installed
Net Maui lastest revision all updates installed
Attached you find a screenshot what happens when i debug the application
on an android target (works ok)
and a screenshot from the same workstation targetting
the macbook´s simulator.
Have updated Xamarin IOS to the latest version
as was suggested by the macbooks´s visual studio 
check for updates dialog.

Problem is clear to see i dont get any country names only the 3letter or 2letter code.

![Android](https://user-images.githubusercontent.com/71807453/171166843-69ccc698-2032-492d-b5fa-96150eece6e4.PNG)
![IOS](https://user-images.githubusercontent.com/71807453/171166849-a01edfef-937f-4534-bf3d-3526881d2507.PNG)

_Copied from original issue xamarin/xamarin-macios#15159_

**Comment by rolfbjarne** [comment]
_From @rolfbjarne on Tue, 31 May 2022 13:09:07 GMT_

This might be related to https://github.com/dotnet/runtime/issues/68321 or https://github.com/dotnet/runtime/issues/69492.

**Comment by rolfbjarne** [comment]
CC @steveisok

**Comment by filipnavara** [comment]
IIRC It is a difference between how the ICU data are trimmed on mobile and desktop. It is possible to switch to a different ICU data file through .csproj properties but I don't think .NET ships an untrimmed one.

**Comment by steveisok** [comment]
Yeah, we trimmed a great deal with WASM initially and carried it forward into iOS.

@rolfbjarne we could explore shipping an uncompressed data file that would need to be opted into.  Thoughts?

**Comment by filipnavara** [comment]
> we could explore shipping an uncompressed data file that would need to be opted into

That's one option, which was to some extent discussed at https://github.com/dotnet/designs/pull/225. Other option is augmenting with system data through the iOS APIs (likely [NSLocale localizedStringForLocaleIdentifier](https://developer.apple.com/documentation/foundation/nslocale/1642864-localizedstringforlocaleidentifi?language=objc) in this case).

**Comment by tarekgh** [comment]
@steveisok I marked this for future but feel free to move it back to .NET 7.0 as needed.

**Comment by steveisok** [comment]
Thanks for refreshing my memory on the design dock ;-). 

Hmm - augmenting with the iOS API's does not seem to be that big of a task. We talked about doing this early in .NET 7.  My team may be able to pick this up.

**Comment by whann0205** [comment]
Sorry to interrupt your "future" discussion, but may i ask what can i do now
to get that working again? It worked in older versions of net6.

**Comment by Eilon** [comment]
@whann0205 I think that a workaround for now would be to have your own map of culture identifiers to culture names and not rely on the built-in ones.

Something like this:

```c#
private static readonly IDictionary<string, string> CultureNameLookup = new()
{
    { "en-us", "English (US)" },
    { "de-de", "German" },
    // ...
};
```

I know it isn't ideal, but you could generate this list from any working platform (e.g. .NET Core on Windows) and then paste the code into your app to run everywhere. Or, if your app only supports a limited set of cultures (say, less than 10), writing it manually should only take a few minutes.

Would this work for your app until it's fixed in .NET?

**Comment by whann0205** [comment]
Thanks for you suggestion.
It would help to know how long we have to wait get this fixed.
Since i have other things to do in the app, i can continue with
other things in the meantime.
Would also help to understand why it stopped working to identify
the source of the problem and perhabs get to know if other functions 
are affected.

**Comment by tipa** [comment]
> @whann0205 I think that a workaround for now would be to have your own map of culture identifiers to culture names and not rely on the built-in ones.
> 
> Something like this:
> 
> ```cs
> private static readonly IDictionary<string, string> CultureNameLookup = new()
> {
>     { "en-us", "English (US)" },
>     { "de-de", "German" },
>     // ...
> };
> ```
> 
> I know it isn't ideal, but you could generate this list from any working platform (e.g. .NET Core on Windows) and then paste the code into your app to run everywhere. Or, if your app only supports a limited set of cultures (say, less than 10), writing it manually should only take a few minutes.
> 
> Would this work for your app until it's fixed in .NET?

I was hitting this problem today as well and that workaround isn't really satisfactory when you are supporting a lot of languages in your app, because the `DisplayName` returns the localised name, not the English name. One would have to create that dictionary for every supported language.

I would appreciate if this could be fixed soon.

**Comment by whann0205** [comment]
Thanks for your interest. Now that 2 months have passed i tried again and it is sadly not
fixed. I doubt it will be fixed anytime soon. 

In my case by using:
var region = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
               .Where(C => C.LCID != 127 & C.LCID != 4096 & !C.IsNeutralCulture)
               .Select(x => new RegionInfo(x.LCID));

You dont even get the localised Name but only the 2 letter iso code for the country in the field english 
name and nativename. But only under IOS, for Android regardless of which version it is working correctly.
As i learned somebody at MS must "pick that up". 

See https://github.com/dotnet/runtime/issues/70028#issuecomment-1142511370

Have not found a way except writing here to get somebody to "pick that up".
Would highly appreciate if one can help here, too

**Comment by Cheesebaron** [comment]
Anything happening here? Just ran into this today.

**Comment by whann0205** [comment]
It is still not fixed. Have not received any info that somebody working on it. 
I suggest you find a workaround.

**Comment by whann0205** [comment]
thanks steve. 
But as i said a workaround is needed since  .net 8 will be next year ...

**Comment by steveisok** [comment]
> thanks steve. But as i said a workaround is needed since .net 8 will be next year ...

We'll look to see how straightforward this is to fix by itself and if it's easy, get something out.

**Comment by steveisok** [comment]
@mkhamoyan when you have a chance, can you please see if hybrid globalization fixes this issue?

**Comment by Kebechet** [comment]
hopefully this will be successfully shipped in .NET 8

**Comment by mkhamoyan** [comment]
> @mkhamoyan when you have a chance, can you please see if hybrid globalization fixes this issue?

Yes this will work on hybrid globalization mode.
Implemented by https://github.com/dotnet/runtime/pull/81470 and https://github.com/dotnet/runtime/issues/83514
