### ISSUE TITLE
Implement mono support for default interface implementations of static virtual methods

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#70040]
I believe I'm close to merging in the PR enabling SVM default interface implementations in CoreCLR,

https://github.com/dotnet/runtime/pull/66887

Naturally the mono legs of the PR run are now failing in the new test due to incomplete mono implementation. I'm creating this issue to temporarily block the new svm_diamondshape test in issues.targets before the mono support is implemented.

/cc @SamMonoRT

**Comment by trylek** [comment]
Hmm, it was failing yesterday, if the fix has just been merged in, I don't yet have an updated reading, I'll launch another lab run on the change without the issues.targets addition.

**Comment by trylek** [comment]
It looks good, there's just one remaining leg that hasn't finished yet and the rest are all green, once they are done I'll add this commit to the main PR and I'll close the bug as resolved.

**Comment by lambdageek** [comment]
@trylek Mono issue is resolved now?

**Comment by trylek** [comment]
I believe so, Mono legs have passed with my change, the only remaining concern is NativeAOT, I need to work with @MichalStrehovsky and / or @jkotas to figure out what needs to be done there as I'm not a NativeAOT expert yet.
