### ISSUE TITLE
NativeAOT does not respect STAThreadAttribute/MTAThreadAttribute on main entry point

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/runtime#70066]
### Description

Adding STAThreadAttribute or MTAThreadAttribute to the main entry point seems to not respected by NativeAOT. I've done some debugging and the problem seems to be here:
https://github.com/dotnet/runtime/blob/06da0fcf4573115aac76f4afd65cdd75592e86e2/src/coreclr/tools/aot/ILCompiler.Compiler/IL/Stubs/StartupCode/StartupCodeMainMethod.cs#L108-L117

`HasCustomAttribute` always returns false because `MainMethodWrapper` does not override `HasCustomAttribute` from `ILStubMethod`:
https://github.com/dotnet/runtime/blob/06da0fcf4573115aac76f4afd65cdd75592e86e2/src/coreclr/tools/Common/TypeSystem/IL/Stubs/ILEmitter.cs#L825-L828

My naive fix would be to override `MainMethodWrapper.HasCustomAttribute` with this:
```
public override bool HasCustomAttribute(string attributeNamespace, string attributeName)
    => WrappedMethod.HasCustomAttribute(attributeNamespace, attributeName);
```

Since I'm not very familiar with the NativeAOT codebase, I'd like some feedback before opening a PR with this. I'd be happy to open a PR if this fix is deemed to be correct.

### Reproduction Steps

Run this code with and without NativeAOT. The console output is not the same.
```
using System;
using System.Threading;

class Program
{
    [STAThread]
    static void Main()
    {
        if (Thread.CurrentThread.GetApartmentState() != ApartmentState.STA)
        {
            Console.WriteLine("Not STA");
        }
        else
        {
            Console.WriteLine("STA");
        }
        Console.ReadKey();
    }
}
```

### Expected behavior

Should print: `STA`

### Actual behavior

Prints: `Not STA`

### Regression?

I don't know.

### Known Workarounds

Call `Thread.CurrentThread.SetApartmentState(ApartmentState.STA)` instead of using the attribute.

### Configuration

I'm building using 7.0.100-preview.6.22275.1 SDK + Microsoft.DotNet.ILCompiler 7.0.0-preview.6.22281.3.
Running on Windows 10.

**Comment by MichalStrehovsky** [comment]
Thanks for the thorough diagnosis! Looks like I broke it in https://github.com/dotnet/runtimelab/pull/1384.

Your proposed fix sounds good, but we would want to do it more surgically and only call into the wrapped method for the two attributes we care about. This will avoid the issue the pull request was fixing (copying all the attributes including those that are not expected to show up on compiler-generated methods).

**Comment by ThomasGoulet73** [comment]
> we would want to do it more surgically and only call into the wrapped method for the two attributes we care about.

Did I understand correctly that you want to change
```
 if (_mainMethod.HasCustomAttribute("System", "STAThreadAttribute")) 
 { 
     codeStream.EmitLdc((int)System.Threading.ApartmentState.STA); 
     codeStream.Emit(ILOpcode.call, emitter.NewToken(initApartmentState)); 
 } 
 if (_mainMethod.HasCustomAttribute("System", "MTAThreadAttribute")) 
 { 
     codeStream.EmitLdc((int)System.Threading.ApartmentState.MTA); 
     codeStream.Emit(ILOpcode.call, emitter.NewToken(initApartmentState)); 
 } 
```
To:
```
 if (_mainMethod.WrappedMethod.HasCustomAttribute("System", "STAThreadAttribute")) 
 { 
     codeStream.EmitLdc((int)System.Threading.ApartmentState.STA); 
     codeStream.Emit(ILOpcode.call, emitter.NewToken(initApartmentState)); 
 } 
 if (_mainMethod.WrappedMethod.HasCustomAttribute("System", "MTAThreadAttribute")) 
 { 
     codeStream.EmitLdc((int)System.Threading.ApartmentState.MTA); 
     codeStream.Emit(ILOpcode.call, emitter.NewToken(initApartmentState)); 
 } 
```

Instead of overriding `MainMethodWrapper.HasCustomAttribute` (Basically reverting the PR you referenced) ?

**Comment by MichalStrehovsky** [comment]
I thought of overriding HasCustomAttribute and checking what attribute the caller is asking about before forwarding to WrappedMethod. But your proposal looks better.
