### ISSUE TITLE
Test failure System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: Pax)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70060]
Run: [runtime-coreclr libraries-jitstress 20220531.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1797309&view=ms.vss-test-web.build-test-results-tab&runId=47967510&paneView=debug&resultId=131119)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.10.Arm64v8.Open

- System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(format: Pax)

```
**Error message:**
```
Assert.Equal() Failure
Expected: 34
Actual:   33


Stack trace
   at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.VerifyTimestamp(DateTime expected, DateTimeOffset actual) in /_/src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.File.Tests.Windows.cs:line 76
   at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.VerifyPlatformSpecificMetadata(String filePath, TarEntry entry) in /_/src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.File.Tests.Windows.cs:line 50
   at System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_File(TarFormat format) in /_/src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.File.Tests.cs:line 110
   at InvokeStub_TarWriter_WriteEntry_File_Tests.Add_File(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
No Kusto information.

**Comment by carlossanlop** [comment]
@VincentBu what is different about the JitStress jobs compared to the normal jobs? I already disabled this test https://github.com/dotnet/runtime/pull/69997 on Linux, and I'm wondering why is it now failing on Windows as well, but only on JitStress runs.

**Comment by vonzshik** [comment]
If I'm reading the sources correctly, `TarWriter` first reads the current info

https://github.com/dotnet/runtime/blob/ca2daf185f8329d315d583e64d05112cf0c77bc8/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Windows.cs#L49-L51

and only after that accesses the file, which also changes the last access time

https://github.com/dotnet/runtime/blob/ca2daf185f8329d315d583e64d05112cf0c77bc8/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarWriter.Windows.cs#L60-L72

If so, that means that the data written into the tar's header might be different from the one the file will have.

**Comment by VincentBu** [comment]
> @VincentBu what is different about the JitStress jobs compared to the normal jobs? I already disabled this test #69997 on Linux, and I'm wondering why is it now failing on Windows as well, but only on JitStress runs.

I know few about it. I asked [tommcdon](https://github.com/tommcdon) and he told me that:
JIT Stress is owned by the codegen team (Julie Lee's team). It enables certain JIT features that generate different types of JIT optimizations thereby exercising different code paths in the JIT. If the failure is specific to JIT Stress, it is highly likely a codegen bug. If however the test fails on other runs as well, then it is a bug but not JIT stress specific.

**Comment by danmoseley** [comment]
@BruceForstall can answer questions about jit stress. Note that libraries tests failures in jit stress are often simply timeouts because it can be slow. (Or perhaps machine configuration specific?)

**Comment by BruceForstall** [comment]
This might help: https://github.com/dotnet/runtime/blob/main/docs/workflow/ci/triaging-failures.md
