### ISSUE TITLE
Test Infrastructure Failure: System.IO.IOException: Unknown error 42424

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#70079]
I am seeing some failures in gc-extra pipelines for linux arm64
```
Test Infrastructure Failure: System.IO.IOException: Unknown error 42424 : '/root/helix/work/workitem/uploads/Arrays/lcs/lcs2_d'
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
Expected: True
Actual:   False
```

E.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1799737&view=ms.vss-test-web.build-test-results-tab&runId=47999058&paneView=debug&resultId=110210

**Comment by kunalspathak** [comment]
cc: [trylek](https://github.com/trylek)

**Comment by adamsitnik** [comment]
@tmds I have tried to google for the `42424` error code, but I was not able to find any meaningful results. Is it even possible that `mkdir` has failed with such an error?

**Comment by jakobbotsch** [comment]
Fixed by #72298

**Comment by jakobbotsch** [comment]
Actually duplicate of #70296

**Comment by adamsitnik** [comment]
> @tmds I have tried to google for the 42424 error code, but I was not able to find any meaningful results. Is it even possible that mkdir has failed with such an error?

It turned out that GCStress was trashing last error: https://github.com/dotnet/runtime/pull/72298
