### ISSUE TITLE
TypedReference.ToObject tests failing on Mono

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#70091]
### Description

Some new `TypedReference.ToObject` tests were added for pointers and function pointers in https://github.com/dotnet/runtime/pull/70055.

These are producing some failures in the CI when running on Mono:

https://github.com/dotnet/runtime/pull/70055/checks?check_run_id=6690887562

**Comment by BrzVlad** [comment]
Enabled in https://github.com/dotnet/runtime/pull/89498
