### ISSUE TITLE
[Native AOT] LINK : fatal error LNK1102: out of memory and Failed to load type

### ISSUE THREAD

**Issue by zhzy0077** [dotnet/runtime#70092]
### Description

Cannot run Native AOT for a project.

### Reproduction Steps

See below sample project
```csproj
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>PidginSample</AssemblyName>
        <RootNamespace>PidginSample</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Pidgin" Version="3.1.0" />
        <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*"/>
    </ItemGroup>
</Project>
```

```cs
using Pidgin;
var t = Parser.Char('a');
Console.WriteLine(t);
```

When running `dotnet publish -r win-x64 -c Release --no-self-contained`, I see 
```
LINK : fatal error LNK1102: out of memory [C:\Users\zheng\Code\Pidgin\PidginSample\PidginSample.csproj]
C:\Users\zheng\.nuget\packages\microsoft.dotnet.ilcompiler\7.0.0-preview.6.22281.7\build\Microsoft.NETCore.Native.targe
ts(341,5): error MSB3073: Command“"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31424\bin\Hostx
64\x64\link.exe"  @"obj\Release\net7.0\win-x64\native\link.rsp"”Exited，Code 1102。 [C:\Users\zheng\Code\Pidgin\PidginSample\
PidginSample.csproj]
```

rsp attached:
[link.zip](https://github.com/dotnet/runtime/files/8815613/link.zip).

### Expected behavior

Can successfully build.

### Actual behavior

Fail.

### Regression?

N/A

### Known Workarounds

N/A

### Configuration

- .NET: 7.0.100-preview.4.22252.9
- OS: Windows 11 22000.1.amd64fre.co_release.210604-1628
- Arch: AMD64

### Other information
I"m pretty sure the available memory is sufficient. It's tested on a device with 64 GiB Mem and the peak memory usage during the build was around 4 GiB.

**Comment by MichalStrehovsky** [comment]
The Pidgin library contains a lot of generic code (even generated by [some automation](https://github.com/benjamin-hodgson/Pidgin/blob/d91d85737fd3d42a62f74ba761d300311d7b7f0d/Pidgin/Parser.Map.Generated.cs#L6-L14)). A lot of generic code means a lot of native code. To the point that it might not be possible to generate that much. It even contains a generic recursion that the compiler tries to contain (the messages printed during compilation are about that).

Marking the assembly [as trimmable](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) helps getting it to compile, but the assembly is not trimming friendly right now and might not work at runtime with trimming. The author will have to work on making it trimming friendly and manifest it [as trimmable](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming).

In the meantime, you can mark it as trimmable by adding this to the project file.

```
<ItemGroup>
  <TrimmableAssembly Include="Pidgin" />
</ItemGroup>
```

But as I wrote, the library generates trimming warnings and might not work at runtime. It does AOT compile.
