### ISSUE TITLE
CreateSymbolicLink is either buggy or unnecessarily expensive

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#70123]
FileSystem.Unix.cs has this code:
```C#
        internal static void CreateSymbolicLink(string path, string pathToTarget, bool isDirectory)
        {
            string pathToTargetFullPath = PathInternal.GetLinkTargetFullPath(path, pathToTarget);
            Interop.CheckIo(Interop.Sys.SymLink(pathToTarget, path), path, isDirectory);
        }
```
That `pathToTargetFullPath` is never used, so either that line can be deleted or there's a bug and this is supposed to be used in the next line.

**Comment by tmds** [comment]
> That pathToTargetFullPath is never used, so either that line can be deleted or there's a bug and this is supposed to be used in the next line.

It's the first. https://github.com/dotnet/runtime/pull/70252 removes it.
