### ISSUE TITLE
build-native.sh doesn't update the shared testhost

### ISSUE THREAD

**Issue by gfoidl** [dotnet/runtime#70134]
### Description

For the development workflow on iterating over native parts, [`build-native.sh`](https://github.com/dotnet/runtime/blob/main/src/native/libs/build-native.sh) doesn't update the shared testhost.

I didn't verify that `build-native.cmd` has the same behavior.

### Reproduction steps (done on fresh Ubuntu 20.04 VM):
1. [build the repo](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md)
2. `$ cd src/libraries/System.Net.NameResolution/tests/PalTests`
3. `$ pushd ../../src & dotnet build & popd & dotnet build /t:test` --> will succeed
4. make changes in native code, then build native code
   ```bash
   $ cd /src/native/libs
   $ ./build-native.sh
   ```
5. do step 3.
6. changes in native side aren't used in tests

For step 4. alternatively just delete the native libraries `$ rm /artifacts/bin/testhost/net7.0-Linux-Debug-x64/shared/Microsoft.NETCore.App/7.0.0/libSystem.Native.*`, then build native side, and the tests will fail.

[Iterating on System.Private.CoreLib changes](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md#iterating-on-systemprivatecorelib-changes) won't update the shared testhost with the native changes either.

Additional context: https://github.com/dotnet/runtime/issues/33378#issuecomment-609417323 et seqq (note: since then some changes in the repo-layout were done)

### Expected bahavior

Changes in native side are picked up by the shared testhost.

-- or --

There's a documentation in the workflow on how to iterate on the native parts.

### Workarounds

Manual copy the built native binaries to the shared testhost `$ cp cp /artifacts/bin/native/Linux-x64-Debug/libSystem.Native.* /artifacts/bin/testhost/net7.0-Linux-Debug-x64/shared/Microsoft.NETCore.App/7.0.0`

---

/cc: @ViktorHofer

**Comment by ViktorHofer** [comment]
Binplacing into the testhost is handled by the https://github.com/dotnet/runtime/blob/main/src/native/libs/build-native.proj project. This should work if you invoke do a `dotnet.sh build src/native/libraries/build-native.proj` instead of invoking the `build-native.sh` script.

Definitely not ideal but that's how it currently is implemented.

**Comment by gfoidl** [comment]
Ah, that's great. 

Can there be added a ReadMe.md to https://github.com/dotnet/runtime/tree/main/src/native/libs explaining that?
Also https://github.com/dotnet/runtime/tree/main/docs/workflow/building/libraries#how-to-building-native-components-only sould be updated for this.

**Comment by ViktorHofer** [comment]
Absolutely. Would you like to submit a PR to update them? There's no additional knowledge noteworthy besides that only the msbuild proj wrapper file updates the binplace directories:
- https://github.com/dotnet/runtime/blob/be4d292eaf27f3890c877b08f6bf9e2f6279e343/src/libraries/Directory.Build.targets#L88
- https://github.com/dotnet/runtime/blob/be4d292eaf27f3890c877b08f6bf9e2f6279e343/src/libraries/Directory.Build.targets#L98
- https://github.com/dotnet/runtime/blob/be4d292eaf27f3890c877b08f6bf9e2f6279e343/src/libraries/Directory.Build.targets#L104

**Comment by gfoidl** [comment]
> Would you like to submit a PR to update them?

Will create a PR for this.

**Comment by ViktorHofer** [comment]
Fixed via https://github.com/dotnet/runtime/pull/70284
