### ISSUE TITLE
Comments on 'System.Convert' are obsolete

### ISSUE THREAD

**Issue by skyoxZ** [dotnet/runtime#70131]
https://github.com/dotnet/runtime/blob/2f82cb8c2109fe5c9119ed41d7d2c5228cf253ec/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L19

Just find it by accident. I have no idea what these comments are talking about.

Maybe the class `Convert` was named `Value` before? And
> The Equals() method of DBNull always returns false, even when the argument is itself DBNull.

seems to be incorrect.

**Comment by fivigh** [comment]
I'd like to create a PR for this. Can the issue be assigned to me, please? CC @tannergooding

**Comment by danmoseley** [comment]
Assigned @fivigh
