### ISSUE TITLE
[ServiceProvider] Services registered as open generic are overwritten by closed generic registrations when ValidateOnBuild is on

### ISSUE THREAD

**Issue by bhakimiy** [dotnet/runtime#70140]
### Description

After migration from .net core 3.1 to .net 6 we faced very strange issue. I have been trying to understand the issue for couple of days. And I believe I found the exact scenario when this strange behavior is happening. The issue is happening with .net 6. I tried to reproduce it with the same code on .net core 3.1. But, everything is working as expected on .net core 3.1.

In a nutshell, when the **ValidateOnBuild** is set to true, the services which are registered as open generic are overwritten by the services which are registered with concrete type. When the **ValidateOnBuild** is set to false, everything works as expected.

I have created the scenario where this behavior is reproducing and uploaded to this [repository](https://github.com/bhakimiy/DITest-Net6).

In the above repository I created a generic interface and 2 its [children](https://github.com/bhakimiy/DITest-Net6/blob/3125a52befa24c48d5bfb23ab6d672e61b1d912d/Program.cs#L43).

```csharp
public interface IBase<T> { }

public class Handler<T> : IBase<T> { }

public class AnotherHandler<T> : IBase<T> { }
```

And registered them
```csharp
builder.Services.AddTransient(typeof(IBase<bool>), typeof(AnotherHandler<bool>));
builder.Services.AddTransient(typeof(IBase<>), typeof(Handler<>));
```

Here is the important point. If you change the order of registration - first register open generic, and then concrete type, then everything works as expected.

After registration and building the application I get the registered services for **IBase<bool>**
```csharp
var child1Handlers = services.GetServices<IBase<bool>>().ToList();
```

As a result I see this:
![image](https://user-images.githubusercontent.com/29584212/171619077-2aa25ebc-2a45-4ba1-a119-48862a38ed5f.png)

Two elements are returned and both are the **AnotherHandler**.

If I set the **ValidateOnBuild** to false or change the order of the registration to this:
```csharp
builder.Services.AddTransient(typeof(IBase<>), typeof(Handler<>));
builder.Services.AddTransient(typeof(IBase<bool>), typeof(AnotherHandler<bool>));
```

I see that everything is working as expected. I see this result when I get services for the **IBase<bool>**:
![image](https://user-images.githubusercontent.com/29584212/171619430-a42a1b08-5db1-49e4-bd2e-14e0fdd80b5b.png)

### Reproduction Steps

1. Create a generic interface or abstract class
2. Create at least two of its generic children
3. Set ServiceProviderOptions.ValidateOnBuild to true in .UseDefaultServiceProvider() while creating a host.
4. First register the first child of IBase service with closed type (you can see the example [here](https://github.com/bhakimiy/DITest-Net6/blob/3125a52befa24c48d5bfb23ab6d672e61b1d912d/Program.cs#L17)). 
5. Then register the second child as open generic ([example](https://github.com/bhakimiy/DITest-Net6/blob/3125a52befa24c48d5bfb23ab6d672e61b1d912d/Program.cs#L18))
6. Get the services from service provider for the type that you registered in step 4 ([example](https://github.com/bhakimiy/DITest-Net6/blob/3125a52befa24c48d5bfb23ab6d672e61b1d912d/Program.cs#L37))

As a result you see 2 elements of the same type registered in step 4.

### Expected behavior

Two elements are returned from service provider for both registered types.

### Actual behavior

Two elements are returned with only one type which is registered as closed generic

### Known Workarounds

1. Set **ValidateOnBuild** to false
2. Change the order of registration. First register open generic services then closed generic services.
3. Register everything as closed generic (e.g. via reflection)

### Configuration

- .Net version: 6.0.300 SDK
- OS: Windows 11, OS Build 22000.675
- Architecture: x64

**Comment by eerhardt** [comment]
@maryamariyan - this looks a lot like https://github.com/dotnet/runtime/issues/65145. Is this a dupe? Or is this a new issue?

**Comment by maryamariyan** [comment]
> @maryamariyan - this looks a lot like https://github.com/dotnet/runtime/issues/65145. Is this a dupe? Or is this a new issue?

yes closing as dupe.
