### ISSUE TITLE
ConfigurationBinder.Bind on virtual array property duplicates elements

### ISSUE THREAD

**Issue by omegatmm** [dotnet/runtime#70150]
### Description

Microsoft.Extensions.Configuration.ConfigurationBinder.Bind sets virtual properties multiple times when overridden. This appends a duplicate array for each overridden instance of virtual array properties.

This appears to come from ConfigurationBinder.GetAllProperties, it adds overridden properties to its returned list multiple times.

### Reproduction Steps

```C#
public class C1
{
    public virtual string[] Test { get; set; } = System.Array.Empty<string>();
}

public class C2 : C1
{
    public override string[] Test { get => base.Test; set => base.Test = value; }
}

var configuration = new ConfigurationBuilder()
    .AddInMemoryCollection(new Dictionary<string, string>()
    {
        ["Test:0"] = "1",
    })
    .Build();

var test = new C2();
configuration.Bind(test);
// test.Test has two elements with value of "1"
```

### Expected behavior

I would expect test.Test to have one element "1"

### Actual behavior

test.Test has two elements with value of "1"

**Comment by maryamariyan** [comment]
FYI link to code:

https://github.com/dotnet/runtime/blob/eef6c7f6cb7f73163313d349fbb796f37b4c3996/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L673-L688
