### ISSUE TITLE
How to extract cookies from HttpClient?

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#70155]
### Description

How to extract cookies from HttpClient?
![image](https://user-images.githubusercontent.com/61237140/171662298-cac4ef2a-fa2b-4183-8eea-9cd3414a9fdc.png)
![image](https://user-images.githubusercontent.com/61237140/171662348-8dfc35be-7a15-43b2-9f0b-4006594894bc.png)
The method does not work in screenshots

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

### Regression?

-

### Known Workarounds

-

### Configuration

-

### Other information

-

**Comment by ManickaP** [comment]
Hi, could you tell us what you mean by "does not work"?
- Throws an exception? If yes, then which?
- Gets stuck? Could you debug it?
- Doesn't return anything?

Also could you provide us with minimal repro case. A small C# snippet showing what exactly doesn't work.

**Comment by Mr0N** [comment]
Having not finished lines of the code, already does everything

**Comment by Mr0N** [comment]
Aren't you planning some more loyal work with cookies?

**Comment by Mr0N** [comment]
It is very convenient to work with cookies, for example in Leaf.xNet

**Comment by ManickaP** [comment]
I meant working piece of code, something we can take and run as-is. We don't see what `CoreHttpClient` does, we don't see what happens between construction and calling `GetAllCookies`. And I mean code as text, not a print screen of your project. 

You also didn't reply to my question about how "it doesn't work". 

I'd like to help you, but I need more information than a print screen with "it doesn't work".

**Comment by Mr0N** [comment]
public class CoreHttpClient : HttpClient
    {
        public override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Config(request);
            return base.Send(request, cancellationToken);
        }
        public override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            Config(request);
            
            return base.SendAsync(request, cancellationToken);
        }
        public void Config(HttpRequestMessage message)
        {
            _handler.CookieContainer = cookies;
            // message.Headers.Add("application/json, text/plain, */*";

        }
        public static CoreHttpClient Create()
        {
            var handler = new HttpClientHandler()
            {
                UseCookies = true,
                UseProxy = true
            };
            CookieContainer cookies = new CookieContainer();
            var result = new CoreHttpClient(handler);
            result.cookies = cookies;
            handler.CookieContainer = cookies;
            return result;
        }
        public CookieContainer cookies { private set; get; }
        public HttpClientHandler _handler { private set; get; }
        private CoreHttpClient(HttpClientHandler handler) : base(handler)
        {
            _handler = handler;
        }

    }

**Comment by ManickaP** [comment]
How do you call it? And how it "doesn't work"?

**Comment by Mr0N** [comment]
> How do you call it? And how it "doesn't work"?

But everything works, I wrote above that I forgot to add the code, so nothing worked. But I steamed with it for almost a day, maybe please do a more normal work with cookies in HttpClient, so as not to steam for a couple of days?

**Comment by ManickaP** [comment]
Glad to hear everything works. If you have any concrete suggestion how to improve API or our documentation feel free to open a new issue. Since this is solved, I'm closing it.
