### ISSUE TITLE
ConsoleLogger output is garbled with color codes when redirected

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#70156]
I'm looking at the logs of a ASP.NET 6.0 app in Kubernetes, and I get color codes that garble up the log.

I filed this as https://github.com/dotnet/runtime/issues/37421, which was fixed for 5.0.

The fix was to not enable color codes when the there is no terminal.

I see there is some code for that here:

https://github.com/dotnet/runtime/blob/59a3093bda7a4058d5f3603200326559b1ba98a5/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L158-L162

It doesn't seem to work/get used in the .NET 6 app I have running on Kubernetes.

cc @eerhardt

**Comment by tmds** [comment]
> Or are you expecting the FormatterOptions.ColorBehavior == LoggerColorBehavior.Default && System.Console.IsOutputRedirected check to kick in?

I'm relying on `LoggerColorBehavior.Default`.

I can reproduce it locally by redirecting output to a file.

```
$ bin/Debug/net6.0/web >/tmp/log
```

The `/tmp/log` file has color codes though it shouldn't:

```
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:5001
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[0]
      Content root path: /tmp/web/
^[[40m^[[32minfo^[[39m^[[22m^[[49m: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

This is a `dotnet new web` template app with .NET 6.0.105.

**Comment by maryamariyan** [comment]
@tmds I'll take a look

**Comment by tmds** [comment]
@maryamariyan thanks.

I was reading through the code. I think the issue may be here:

https://github.com/dotnet/runtime/blob/bab1a1f239325746873d2ae795ea343e7901dbce/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs#L165

Instead of enabling color when `!DisableColors` we should be using `LoggerColorBehavior.Default`.

I didn't have time yet to validate that this is the root cause.

**Comment by maryamariyan** [comment]
I found this related issue https://github.com/dotnet/runtime/issues/17959

**Comment by tmds** [comment]
> It would be good to see how to minimally repro this without needing to set up kubernetes. I a way to get minimal repro is to do an interop call.

https://github.com/dotnet/runtime/issues/70156#issuecomment-1145042843 describes how you can reproduce the issue without Kubernetes.
