### ISSUE TITLE
[wasm] Extend Vector128[_1] wasm intrinsics

### ISSUE THREAD

**Issue by radekdoulik** [dotnet/runtime#70199]
As start I checked which methods are not covered during compilation of browser-bench sample. Some of these are good candidates.

System.Text.Encodings.Web.dll

    class Vector128 method As
    class Vector128 method AsInt32
    class Vector128 method Equals
    class Vector128 method GetElement
    class Vector128 method GetElementUnsafe
    class Vector128 method SetElementUnsafe
    class Vector128`1 method <Equals>g__SoftwareFallback|29_0
    class Vector128`1 method Equals
    class Vector128`1 method get_AllBitsSet
    class Vector128`1 method get_Count
    class Vector128`1 method get_IsTypeSupported
    class Vector128`1 method op_BitwiseOr
    class Vector128`1 method op_Equality
    class Vector128`1 method op_ExclusiveOr
    class Vector128`1 method op_OnesComplement
    class Vector128`1 method ToString

System.Memory.dll

    class Vector128 method As
    class Vector128 method AsInt32
    class Vector128 method Equals
    class Vector128 method GetElement
    class Vector128 method GetElementUnsafe
    class Vector128 method SetElementUnsafe
    class Vector128`1 method <Equals>g__SoftwareFallback|29_0
    class Vector128`1 method Equals
    class Vector128`1 method get_AllBitsSet
    class Vector128`1 method get_Count
    class Vector128`1 method get_IsTypeSupported
    class Vector128`1 method op_BitwiseOr
    class Vector128`1 method op_Equality
    class Vector128`1 method op_ExclusiveOr
    class Vector128`1 method op_OnesComplement
    class Vector128`1 method ToString

Wasm.Browser.Bench.Sample.dll

    class Vector128 method As
    class Vector128 method AsInt32
    class Vector128 method Equals
    class Vector128 method GetElement
    class Vector128 method GetElementUnsafe
    class Vector128 method SetElementUnsafe
    class Vector128`1 method <Equals>g__SoftwareFallback|29_0
    class Vector128`1 method Equals
    class Vector128`1 method get_AllBitsSet
    class Vector128`1 method get_Count
    class Vector128`1 method get_IsTypeSupported
    class Vector128`1 method op_BitwiseOr
    class Vector128`1 method op_Equality
    class Vector128`1 method op_ExclusiveOr
    class Vector128`1 method op_OnesComplement
    class Vector128`1 method ToString

System.Private.CoreLib.dll

    class Vector128 method <Create>g__SoftwareFallback|45_0
    class Vector128 method <Create>g__SoftwareFallback|47_0
    class Vector128 method <Create>g__SoftwareFallback|48_0
    class Vector128 method <Create>g__SoftwareFallback|52_0
    class Vector128 method <Create>g__SoftwareFallback|54_0
    class Vector128 method <Create>g__SoftwareFallback|55_0
    class Vector128 method <Create>g__SoftwareFallback|60_0
    class Vector128 method <Create>g__SoftwareFallback|65_0
    class Vector128 method As
    class Vector128 method AsInt32
    class Vector128 method Equals
    class Vector128 method ExtractMostSignificantBits
    class Vector128 method GetElement
    class Vector128 method GetElementUnsafe
    class Vector128 method LoadUnsafe
    class Vector128 method SetElementUnsafe
    class Vector128 method ShiftRightLogical
    class Vector128 method StoreUnsafe
    class Vector128`1 method <Equals>g__SoftwareFallback|29_0
    class Vector128`1 method Equals
    class Vector128`1 method get_AllBitsSet
    class Vector128`1 method get_Count
    class Vector128`1 method get_IsTypeSupported
    class Vector128`1 method op_BitwiseOr
    class Vector128`1 method op_Equality
    class Vector128`1 method op_ExclusiveOr
    class Vector128`1 method op_OnesComplement
    class Vector128`1 method ToString

**Comment by lewing** [comment]
@radekdoulik can you update the status of this issue please
