### ISSUE TITLE
[API Proposal]: List<T>.ConvertAll overload that provides list index to converter

### ISSUE THREAD

**Issue by AndreasLeeb** [dotnet/runtime#70200]
### Background and motivation

If the mapping function for converting one list to another one needs context in terms of the list index of the respective list element, currently you can only use a `for` loop or LINQ `.Select(Func<TSource, int, TResult>).ToList()`.
As `List<T>.ConvertAll(Converter<TList, TOutput>)` is more efficient (related #18976 and #38418) and allocates less memory than the LINQ equivalent in this case, I suggest the addition of a `ConvertAll` overload with a converter that also gets the index as a parameter.

### API Proposal

```csharp
namespace System.Collections.Generic;

public class List<T> : IList<T>, IList, IReadOnlyList<T>
{
    public List<TOutput> ConvertAll<TOutput>(Func<T, int, TOutput> converter);
}
```

### API Usage

```csharp
List<string> names = new() { "Andy", "Bernie", "Charlie" };

List<string> rankedNames = names.ConvertAll((name, index) => $"{index + 1}: {name}");
```

### Alternative Designs

If symmetry with the existing ConvertAll method regarding the delegate parameter is required:

```csharp
namespace System.Collections.Generic
{
    public class List<T> : IList<T>, IList, IReadOnlyList<T>
    {
        public List<TOutput> ConvertAll<TOutput>(ContextAwareConverter<T, int, TOutput> converter);
    }
}

namespace System
{
    public delegate TOutput ContextAwareConverter<in TInput, in TContext, out TOutput>(TInput input, TContext context);
}
```

### Risks

As this is just an added overload, the only risk I am seeing is that users who have a custom extension method with the same signature will then have the new List method called instead of their extension method, which should not cause problems for them if they had been using an equivalent implementation.

**Comment by Tornhoof** [comment]
> is more efficient (related https://github.com/dotnet/runtime/issues/38418)
You might want to read that issue to the end, the benchmarks show that ConvertAll is not more efficient as Select has a rather long list of speed optimizations by now, for known collection types.

See https://github.com/dotnet/runtime/issues/38418#issuecomment-650230274
and https://github.com/dotnet/runtime/issues/38418#issuecomment-706803864
