### ISSUE TITLE
Why LdapException.ServerErrorMessage is empty on Linux?

### ISSUE THREAD

**Issue by alexjumper91** [dotnet/runtime#70210]
## Description
I have a simple LDAP connector in my app that currently works with System.DirectoryServices.Protocols 6.0.1 nuget package. When I call Bind() with incorrect credentials, I expect that in LdapException.Server ErrorMessage will be a string like "8009030C: LdapErr: DSID-0C09058A, comment: AcceptSecurityContext error, data 52e, v4563" (checked with a sniffer, it comes from the server). And it's empty! Everything is OK on Windows, the error is empty in Linux.

tcpdump (on linux):
![image](https://user-images.githubusercontent.com/106828359/171905338-dd02efd3-0a48-4bf9-9f94-f0a1f0e859eb.png)

## Reproduction Steps
Work with Windows Active Directory
LDAP client on Debian 10
dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.5 [/usr/local/bin/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.5 [/usr/local/bin/shared/Microsoft.NETCore.App]

Sample code:
```
string _host;
public bool Check(string user, string pass)
    {
        string samAccountName = user;
        var userCred = new NetworkCredential(user, pass);
        if (user.Contains('\\'))
        {
            var splitted = user.Split('\\');
            samAccountName = splitted[1];
            userCred.UserName = OperatingSystem.IsWindows() ? splitted[1] : user; // https://github.com/dotnet/runtime/issues/36947
        }
        try
        {
            using (LdapConnection connection = new LdapConnection(_host))
            {
                connection.SessionOptions.ProtocolVersion = 3;
                connection.Bind(userCred);
                return true;
            }
        }
        catch (LdapException ex) when(ex.ErrorCode == 49) // LDAP_INVALID_CREDENTIALS
        {
            // but i need sub-code https://ldapwiki.com/wiki/Common%20Active%20Directory%20Bind%20Errors
            if (!string.IsNullOrWhiteSpace(ex.ServerErrorMessage))
            {
              // parsing string to get data and convert to sub-code
            }
        }
   }
```
How to receive ServerErrorMessage? Or how to receive LDAP sub code?

**Comment by joperezr** [comment]
Thanks for logging the issue @alexjumper91. We have made some changes on how we wrap the exception, get back and report the error message in .NET 7. Have you had a chance to try this out in .NET 7 to see if you see the expected message there?

**Comment by alexjumper91** [comment]
No, unfortunately I haven't had a chance to try this in RC. I'll try it in the release version of .NET 7
