### ISSUE TITLE
Better diagnostics for coreclr initialization failures

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#70211]
When `coreclr_initialize` fails, the returned exit code is most often the generic 0x80004005 (E_FAIL). To diagnose such failures, runninga  repro under a debugger is the only viable option now.
We should add some extra logging so that a host can report more details on such a failure that could pinpoint the error source quickly, without a need to execute a repro under a debugger.

**Comment by richlander** [comment]
That sounds good! I have sometimes use `COREHOST_TRACE` to get information on what went wrong. Would you expect this extra information to be included in that tracing? If not, where?

**Comment by janvorli** [comment]
@richlander I would make this extra info part of the message that currently reports the coreclr initialization failure. We currently print this into console:
```
Failed to initialize CoreCLR, HRESULT: 0x80004005
```
I was thinking that it would be sufficient to add some extra number identifying the source of the failure. Alternatively, we could possibly generate a special range of HRESULT codes that we would use instead of the E_FAIL.

**Comment by richlander** [comment]
SGTM ... look forward to seeing a demo. I love error messages.

**Comment by janvorli** [comment]
Fixed by #78790
