### ISSUE TITLE
Call to "File.AppendAllText()" function may not always work and may sometimes corrupt the file.

### ISSUE THREAD

**Issue by ReneElizondo** [dotnet/runtime#70247]
### Description

On a Raspberry Pi running Linux, calls to `File.AppendAllText()` not always append the text and sometime may corrupt the file. This would happen if the Raspberry Pi is rebooted or turned off and on.

### Reproduction Steps

- Create a .NET Core Console app that calls the `File.AppendAllText()` function. Only append a small amount of text (like a single word).
- Run the Console app on a Linux machine (in my case is a Raspberry Pi running Linux).
- Wait until the Console app completes executing.
- Reboot or turn the computer on / off.

Again, in case it matters this is happening on a Raspberry Pi running Linux, I don not have access to any other Linux computers at this time.

### Expected behavior

I would expect the `File.AppendAllText()` call to do whatever it needs to do to successfully append the text to the file. 

### Actual behavior

After the computer finishes rebooting, you may see the file with the appended text (that is good) or you may see the file empty or corrupter (that is bad). On my tests, most times, the file will be empty.

### Configuration

.NET Core 3.1

**Comment by MichalPetryka** [comment]
To me it looks like the write isn't flushed to the memory. How do you turn then machine off, via normal shutdown or cutting off the power?

**Comment by ReneElizondo** [comment]
Either way the `File.AppendAllText()` function call will fail to do its job correctly. 

As extra info, right now, when someone needs to reboot the Raspberry Pi I call the following native function from within a .NET app (which by the way, also makes the `File.AppendAllText()` function call fail): 

```
[DllImport("libc.so.6", SetLastError = true)]
public static extern Int32 reboot(Int32 cmd, IntPtr arg);
```

From the documentation):

`Opens a file, appends the specified string to the file, and then closes the file.`

I would expect that as long as the function `File.AppendAllText()` call completes, it would not matter how the computer is rebooted or powered off, the text bits should have already been committed to disk and the file should definitely not be corrupted.

**Comment by MichalPetryka** [comment]
If you're able to build the runtime, could you check if adding a `fsync()` (pass the result of `ToFileDescriptor` there) call before the `close()` solves the issue?
https://github.com/dotnet/runtime/blob/82a2562fc9ee0986ee20ee309ad0bc259c561683/src/native/libs/System.Native/pal_io.c#L334-L337

**Comment by ReneElizondo** [comment]
Thanks for the help @MichalPetryka but at this time, I have no clue on how to build the runtime. Would it be possible instead for me to perhaps get the dll with the fix and maybe I can just replace that dll on my published code?

**Comment by ReneElizondo** [comment]
Also, in case it matters:

![image](https://user-images.githubusercontent.com/88205225/172083715-b907c367-bbd0-456d-a598-6d72ed280fce.png)

**Comment by SupinePandora43** [comment]
> Also, in case it matters:
> 
> ![image](https://user-images.githubusercontent.com/88205225/172083715-b907c367-bbd0-456d-a598-6d72ed280fce.png)
> 

Try `net6.0`

**Comment by ReneElizondo** [comment]
Testing under .NET 6 was the first thing I thought about, unfortunately, this is a work related issue and .NET 6 / Visual Studio 2022 are still not part of our company development stack. So even if that worked, I would not be able to use that solution.

I understand that at the very least, testing under .NET 6 would be nice just to see if the issue exists there or not, but getting that environment setup is gong to take a very long time. I would prefer continuing troubleshooting this issue base on .NET Core 3.1 if at all possible.

**Comment by stephentoub** [comment]
If you just write a simple C program that creates a file (`open`), writes to it (`write`), and closes the file (`close`), using the same data you're experimenting with here, do you not see the same issue?

**Comment by ReneElizondo** [comment]
Yes, I did try that, I wrote my own `AppendAllText()` function (see below) and I still got the same issue.

```
private static void AppendAllText(string filePath, string eventMsg)
{
    using (var writer = File.AppendText(filePath))
    {
        writer.WriteLine(eventMsg);
    }
}
```

**Comment by stephentoub** [comment]
> Yes, I did try that, I wrote my own AppendAllText() function (see below) and I still got the same issue.

I mean using C, not C#.

**Comment by ReneElizondo** [comment]
I understand, using C and using native OS calls may be a little bit of an issue for me at this time.

I believe you are correct, when I write to the file (using .NET), I can go and open the file using a built in text editor and I can see the information there. If I then reboot / unplug the power cord when the Raspberry Pi comes back I no longer see the text or I get a corrupted file message.

So assuming that the file is being cached and that is the cause of the problem, given that the Raspberry Pi OS is essentially Linux (not some obscure OS), why is the .NET library not making a call to the OS to make sure the data is persisted to disk? Isn't that something that Linux would offer? If that is too expensive, should the .NET library not offer a parameter that allows us to specify if we want to force the data to be flushed and persisted to disk immediately?

Its also kind of weird that this happens even if I select to reboot through the OS user interface. I would expect a clean reboot to take care of flushing any cached data to disk before it shuts down.

**Comment by stephentoub** [comment]
> should the .NET library not offer a parameter that allows us to specify if we want to force the data to be flushed and persisted to disk immediately?

`FileStream.FlushAsync(flushToDisk: true)` calls `fsync`, which is the C API provided to do as much flushing as is available.

**Comment by stephentoub** [comment]
> Very well, as soon as I get a chance I will try the following:
> writer.Flush()

That's different. You specifically need to use FileStream.Flush(bool), passing in true.

**Comment by ReneElizondo** [comment]
ok, I can try that, however, assuming that works, if `File.AppendAllText()` does not offer a way to do the same, then the `File.AppendAllText()` is flawed (this is my opinion).

**Comment by stephentoub** [comment]
> if File.AppendAllText() does not offer a way to do the same, then the File.AppendAllText() is flawed

File.AppendAllText is meant to be a simple one-line helper for the common case.  Forcing flushing of data beyond what the OS does by default is not the common case.  If you want that, you can do:
```C#
using (var writer = File.AppendText(path))
{
    writer.Write(text);
    writer.Flush();
    ((FileStream)writer.BaseStream).Flush(true);
}
```

**Comment by ReneElizondo** [comment]
Unfortunately, the provided code did not fix the issue, I would estimate that around 75% of the time the code is successful but there is still 25% of the time when the code is not successful (the text is not written to the file).

I don't understand, I seriously doubt that the Linux distro running on the Raspberry Pi (in particular the code used to save data to disk) is any different that the code used in the vast majority if not all of the other Linux distros. Is this is a problem on the Raspberry Pi I would assume this is a problem in most if not all other flavors of Linux. Just a guess.

To me this is a .NET issue all the way, after all, If the .NET framework uses native Linux function calls to save data to disk, why can't it call native Linux functions calls that flush the data to disk immediately rather than caching the data? I am sure native Linux functions must exist that do exactly that.

**Comment by stephentoub** [comment]
> To me this is a .NET issue all the way

Please try a simple C app.

> why can't it call native Linux functions calls that flush the data to disk immediately rather than caching the data

That is what the Flush(true) does.  If you're still seeing issues with that, it's likely an issue with your device.

**Comment by ReneElizondo** [comment]
The problem with the C app is that I would not know where to start, I have never done a C app in Visual Studio. If you or someone else would be willing to help me out creating the C app I would be happy to do so.

This is happening with over 10 Raspberry Pis, purchased at different times from different vendors and different board revisions. This is a problem with all Raspberry Pis, not just a single device.

**Comment by stephentoub** [comment]
> This is happening with over 10 Raspberry Pis, purchased at different times from different vendors and different board revisions. This is a problem with all Raspberry Pis, not just a single device.

That may be.  But the symptoms you describe sound very much outside the control of .NET.  That's why I'm asking you to try other languages / frameworks.

**Comment by ReneElizondo** [comment]
Just created a new document using a program called "Geany" on the Raspberry Pi, typed in the letter "a" in the document, explicitly saved the document (clicked the save button on the app), pulled out the power cable from the Raspberry Pi, plugged the power cable back on and waited for the computer to finish rebooting. I then opened the file and it was empty.

So you may be into something, I will post the issue on the "Geany" issues and see what they have to say.

If you would like me to follow up here with the findings let me know, else I will close the issue.

Thanks.

**Comment by danmoseley** [comment]
Thanks for the report, but are you suggest, I believe we can close the issue.

**Comment by tmds** [comment]
If you do a clean shutdown, everything should be nicely stored.

If you pull the plug, your file changes might not have made it to disk yet.

You're appending, so the expectation may be to not lose/corrupt the data that was in the file before.
.NET doesn't use O_APPEND. I guess the filesystem may use as a hint to preserve previous data.
Additionally, the file system type, and mount options can change the behavior to avoid corruption.
(Note that O_APPEND doesn't protect from corruption due to partial writes.)

If you want something that works independent of the filesystem, you could write the changes to another file in the same folder, and then do a `File.Move`. This performs a rename of the file as an atomic operation. That way, the file will have either the old, or the new content. If you strongly care about the file being persisted at that time, you can also additionally call [sync/syncfs](https://linux.die.net/man/2/sync). That will cause a performance hit. And, if the hard shutdown happens before the sync call, you can still lose the data (but not corrupt the file).

**Comment by ReneElizondo** [comment]
> If you do a clean shutdown, everything should be nicely stored.

No, not really, I was also able to duplicate the issue by doing a standard clean reboot. That Raspberry Pi OS has some issues.

So assuming that I understand this correctly (I would not be surprised if I didn't), if calling `sync/syncfs` fixes the problem, why does the .NET framework not do that by default to avoid the issue altogether? Sure, there will be a small performance hit but is that even an issue?

I can not think of a reason why someone would call a function that is designed to writes data to disk and not expect the data to be persisted to disk right there and then. If someone wanted to do some kind of optimization then the could cache the data on a string builder, some other memory stream or something else and then, when they are ready to commit the data they can call the faction that is actually supposed to write the data to disk and not cache things.

The current behavior is not logical at all, if the .NET framework can so something (such as calling `sync/syncfs`) to make things work as expected (meaning the data is persisted to disk and not cached) in my opinion such solution should be implemented. Or at the very least, an overload should be provided that accepts a parameter forcing data to be flushed to disk via `sync/syncfs`.

**Comment by tmds** [comment]
> No, not really, I was also able to duplicate the issue by doing a standard clean reboot. That Raspberry Pi OS has some issues.

You could add some script that causes [sync](https://man7.org/linux/man-pages/man1/sync.1.html) to be called on shutdown.

> I can not think of a reason why someone would call a function that is designed to writes data to disk and not expect the data to be persisted to disk right there and then.

I think the main reasons are that disks are slow, and some storage types have limited write cycles.

Take a look at the man mages of `mount`, and the file system you are using. Look at the options that control the sync/async and journaling behavior.

Maybe O_APPEND makes a difference. Though there is no easy way to try use that from .NET.

**Comment by danmoseley** [comment]
If calling `fsync` was always a good thing, the OS would do it automatically when code closes the file. It does not do that, since defeating the disk cache can reduce IO performance. 

>  Or at the very least, an overload should be provided that accepts a parameter forcing data to be flushed to disk via sync/syncfs.

As far as I know, there's nothing special about `AppendAllText()` in this regard, so it would be an overload on every IO API, and potentially every API that indirectly does IO as well. As @tmds says, you probably should look beyond .NET for a solution here, or possibly PInvoke to `fsync`.

Thanks for the issue, I think this is answered so I'll close now.

**Comment by ReneElizondo** [comment]
@danmoseley 

It is important to keep in mind that the OS needs to provide maximum flexibility, so it makes total sense that the OS may want to cache the changes instead of immediately committing the changes to disk. The OS is trying to please everyone with good reason.

But we are talking about `AppendAllText()` in this example, this is a very high level API designed to make life simpler. Can you really think of a good reason why the typical .NET developer calling the `AppendAllText()` should worry about having to call `fsync`?

If things are left the same, I can guaranty you all this will do is create further confusion and headaches for someone else. I will ask you guys to reconsider, put thing into context and ask yourselves... What would the typical everyday .NET developer expect to happen after calling the high level `AppendAllText()` function? Would they expect needing to call `fsync `to make sure the call will do what it is meant do under all conditions? I think the answer is clear!

I do appreciate the help however, calling sync does looks like it fixes the issue.

Thank you.
