### ISSUE TITLE
OSX/Interop.libc.cs functions should be replaced by System.Native shim functions

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#70253]
[OSX/Interop.libc.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/OSX/Interop.libc.cs) functions pinvoke directly into libc.

Instead, we should use `System.Native` shim functions to avoid hard-coding platform specifics in managed code, and to avoid manual `SafeHandle` marshaling.

cc @stephentoub @deeprobin

**Comment by huoyaoyuan** [comment]
Different from generic Unix/Linux, OSX is a concrete variant with its own (probably stable?) ABI. The main purpose of SystemNative should be handling ABI variations. For `Interop.libproc` we are doing direct P/Invoke.

I have no additional knowledge about libc on OSX. If its ABI is not stable, it could be a nightmare.

**Comment by jkotas** [comment]
Yes, OSX libraries have stable ABI, similar to Windows. We have 50+ OSX-specific direct P/Invokes, it is not just libc. I do not see a good reason for wrapping all of them in shims.

**Comment by tmds** [comment]
In this specific case, it involves marshalling a struct for [setattrlist](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setattrlist.2.html), and https://github.com/dotnet/runtime/pull/60507 adds manual `SafeHandle` marshaling to that.

Personally, I like the C-compiler validating and potentially catching issues in the marshaling, rather than relying on the `DllImport` author.

You can close this issue if no action is needed.

**Comment by tmds** [comment]
Closing since the direct use of `libc` on macOS is intentional.
