### ISSUE TITLE
Unsupported features to Cross Compile to linux-arm64 on wsl and also osx

### ISSUE THREAD

**Issue by sorainnosia** [dotnet/runtime#70250]
### Description

Use wsl to run linux, compile to linux-x64 works, but when compile to arch linux-arm64 throws error
```
  /usr/bin/aarch64-linux-gnu-ld: cannot find Scrt1.o: No such file or directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crti.o: No such file or directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtbeginS.o: No such file or directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lstdc++
  /usr/bin/aarch64-linux-gnu-ld: cannot find -ldl
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lm
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lz
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgssapi_krb5
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lrt
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc_s
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lpthread
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lc
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc
  /usr/bin/aarch64-linux-gnu-ld: cannot find -lgcc_s
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtendS.o: No such file or directory
  /usr/bin/aarch64-linux-gnu-ld: cannot find crtn.o: No such file or directory
```

also couldn't compile to osx using windows machine, is there a solution to compile to all os and architectures?

### Reproduction Steps

```
cd project
wsl
dotnet publish -r linux-arm64 -c Rel
ease -p:PublishTrimmed=true -p:EnableCompressionInSingleFile=true -p:TrimMode=Link -p:IlcGenerateMapFile=true --self-con
tained
```

### Expected behavior

Successfully cross compile generating binaries for other os and architectures just like other programming languages.

### Actual behavior

throw exception

### Regression?

Not working in any version I tried yet.

Only works when compile using ReadyToRun which isn't native.

### Known Workarounds

No work around, features unsupported

### Configuration

.NET 7 preview.4.22229.4

Normal console application project.
Reflection is enabled.

### Other information

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;

**Comment by ViktorHofer** [comment]
cc @jkotas

**Comment by jkotas** [comment]
> couldn't compile to osx using windows machine, is there a solution to compile to all os and architectures?

NativeAOT links against C/C++ libraries and so it needs same cross-compilation environment as C/C++. If you can setup cross-compilation environment for C/C++, you should be to use it for NativeAOT.

The cross-OS cross-compilation environments for C/C++ are difficult to setup. We do not plan to provide instructions for how to set them up.

**Comment by sorainnosia** [comment]
> > couldn't compile to osx using windows machine, is there a solution to compile to all os and architectures?
> 
> NativeAOT links against C/C++ libraries and so it needs same cross-compilation environment as C/C++. If you can setup cross-compilation environment for C/C++, you should be to use it for NativeAOT.
> 
> The cross-OS cross-compilation environments for C/C++ are difficult to setup. We do not plan to provide instructions for how to set them up.

hi @jkotas, thanks for the help

I have switched to use Github Actions, do you have a sample yml file that compiles .NET 6.0 console app to linux-arm64

**Comment by jkotas** [comment]
> do you have a sample yml file that compiles .NET 6.0 console app to linux-arm64

I do not have a sample github actions yaml file for this handly. You should be able to create one using 
https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/compiling.md#cross-architecture-compilation

**Comment by agocke** [comment]
Looks like the question was answered.
