### ISSUE TITLE
SpinLock should be a class, not a struct

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/runtime#70266]
When using a SpinLock, consuming code should be always referencing the same instance - as its purpose is to have shared state.

At the moment, there are at least two easy ways of accidentally breaking the functionality of a SpinLock on account that it is a struct rather than a class.

`private readonly SpinLock Locker = new()`

This causes a copy of the SpinLock to be created every time it is used. So `Locker.Enter` works on a new instance, and effectively disables any locking

Making `Locker` type members `readonly` is a common practice, but the caveat here is "unless it's a SpinLock".

Another example is as follows:

```
public static class SpinLockExtensions
{
  public static void ExecuteLocked(this SpinLock locker, Action action)
  {
    ...Get the lock
    ...Do stuff
    ...Release the lock
  }
}
```

This creates a copy of the SpinLock each time `Locker.ExecuteLocked()` is called. To fix this we have to change the code to `this ref SpinLock locker`.

It seems the idea of a single-instance with shared state contradicts the idea of a struct that is copied to a new instance.

Changing `SpinLock` to a class would allow `readonly` members (which is good practice) and avoid accidental copying on extension methods.

And, as far as I can see, there is no reason to ever want a SpinLock to be copied.

**Comment by terrajobst** [comment]
I’ll need to double check but making a value type a reference type is AFAIK a binary breaking change.

**Comment by stephentoub** [comment]
What @terrajobst said. `Monitor.Enter/Exit` already works with any object and spins a bit as part of trying to enter, and should be the go-to way of protecting access to a region. SpinLock was made a struct on purpose, as an advanced type that can be used when avoiding the allocation of an object is important and the critical region being protected is expected to always be very brief.  We're not going to change it to be a class (which would both be a breaking change and work against the goals of the type) nor obsolete it to replace it with an equivalent class-based version (if someone really wants a class-based spin-lock, SpinLock can just be embedded inside of any other object, including one dedicated to it).  Thanks for the suggestion, though.

**Comment by mrpmorris** [comment]
@stephentoub I read in a book that a SpinLock is better than lock() for short term locks because lock will put a thread to sleep if it can't get the lock, is that no longer true?

**Comment by stephentoub** [comment]
> a SpinLock is better than lock() for short term locks because lock will put a thread to sleep

`lock` has always spun a bit before falling back to a kernel-based blocking wait.

**Comment by mrpmorris** [comment]
I didn't know that, thanks!

**Comment by richlander** [comment]
What was the book?

**Comment by huoyaoyuan** [comment]
> I read in a book that a SpinLock is better than lock() for short term locks

The "short term" may be much shorter than you thought. Look at our comment on SpinLock type:

```
    /// Spinning can be beneficial when locks are fine grained and large in number (for example, a
    /// lock per node in a linked list) as well as when lock hold times are always extremely short. In
    /// general, while holding a spin lock, one should avoid blocking, calling anything that itself may
    /// block, holding more than one spin lock at once, making dynamically dispatched calls (interface and
    /// virtuals), making statically dispatched calls into any code one doesn't own, or allocating memory.
```
