### ISSUE TITLE
Consider adding JsonConverter for BinaryData that converts to Base64 string

### ISSUE THREAD

**Issue by JoshLove-msft** [dotnet/runtime#70267]
Currently any models that are serialized with System.Text.Json that contain a [BinaryData ](https://docs.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-6.0) property will not have the data populated on the resulting JSON. This is because BinaryData doesn't contain any public properties.

One potential solution would be to define a JsonConverter that converts the BinaryData bytes to a base64 string and includes this in the JSON. For deserialization, the BinaryData JSON is assumed to be a Base64 string:

```c#
    internal class BinaryDataConverter : JsonConverter<BinaryData>
    {
        public override BinaryData Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return BinaryData.FromBytes(reader.GetBytesFromBase64());
        }

        public override void Write(Utf8JsonWriter writer, BinaryData value, JsonSerializerOptions options)
        {
            writer.WriteBase64StringValue(value.ToMemory().Span);
        }
    }
```
The converter would then be added to the BinaryData type:

```c#
    [JsonConverter(typeof(BinaryDataConverter))]
    public class BinaryData {
```
This would match the behavior of how byte arrays get serialized with System.Text.Json - they are [converted to Base64](https://github.com/dotnet/runtime/blob/4a4e347b964a2c8d2216ec382e4fb481965bb2fc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/ByteArrayConverter.cs). For byte arrays, it looks like the ByteArrayConverter is defined as a default converter in System.Text.Json. This wouldn't work for BinaryData as BinaryData depends on System.Text.Json, so that would introduce a circular dependency. Instead, I think we'd need to add the converter directly to the BinaryData type.

**Comment by eiriktsarpalis** [comment]
Juding by the APIs offered by `BinaryData` I'm not necessarily convinced that the type itself is meant for serialization, but I'll let the owners of System.Memory make that call.

**Comment by JoshLove-msft** [comment]
> Juding by the APIs offered by `BinaryData` I'm not necessarily convinced that the type itself is meant for serialization, but I'll let the owners of System.Memory make that call.

This type can be used as a more convenient byte array and be composed onto larger models. For this reason, it would be useful if it could be serialized in the same way as byte arrays.

**Comment by adamsitnik** [comment]
I believe that it makes sense to be able to serialize and deserialize it. Actually, I was expecting that #54979 would make it work.

@eerhardt what is your opinion on this?

**Comment by eerhardt** [comment]
I wouldn't have expected #54979 to make this work. Those new overloads just allow developers to serialize/deserialize objects to/from BinaryData instances using JSON source generation-backed serialization.

Given the description of `BinaryData` in https://github.com/dotnet/runtime/issues/41686, I would also expect properties of type `BinaryData` to logically act like a `byte[]` does. So it makes sense to me to be able to serialize/deserialize BinaryData instances to/from JSON.

**Comment by eiriktsarpalis** [comment]
Sounds like we could just mark this up-for-grabs then? Doesn't seem to require API review.

**Comment by adamsitnik** [comment]
> Sounds like we could just mark this up-for-grabs then? 

Done!

> Those new overloads just allow developers to serialize/deserialize objects to/from BinaryData instances using JSON source generation-backed serialization.

Thanks for the explanation! I assumed that there is some magic pattern recognition (if X implements Y then it's serializable etc)

**Comment by ovidiucosteanet** [comment]
Hello! I am a new contributor I would like to create a PR for this. Can you please assign the issue to me?

**Comment by eiriktsarpalis** [comment]
Done @ovidiucosteanet. If you haven't found it already, here's a [guide to setting up your dev workflow](https://github.com/dotnet/runtime/tree/main/docs/workflow) with this repo.

**Comment by ovidiucosteanet** [comment]
Thank you, @eiriktsarpalis!

**Comment by ovidiucosteanet** [comment]
Hello! I am almost done with the development of the fix for this issue. Can you please provide me a bit of guidance in the following matter?

It seems that I need to add the attribute `[JsonConverter(typeof(BinaryDataConverter))]` also to the `BinaryData` class in the `ref` folder, in order to avoid the exception: CannotRemoveAttribute : `Attribute 'System.Text.Json.Serialization.JsonConverterAttribute' exists on 'System.BinaryData' in the implementation but not the reference.	System.Memory.Data (src\System.Memory.Data) ...\microsoft.dotnet.apicompat\7.0.0-beta.22403.1\build\Microsoft.DotNet.ApiCompat.targets`

If I proceed like this, I would also need to create a new API for the `BinaryDataConverter` class, in the `ref` folder. Is my assumption correct or might there be another way to implement this that I do not know or I am not seeing?

**Comment by eiriktsarpalis** [comment]
Your assumption is correct, the APIs in the ref assembly should match the public APIs in the implementation assembly.

**Comment by ovidiucosteanet** [comment]
Great, thank you. In this specific case can I do the API changes in this PR, or should I follow the flow described here https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md?

**Comment by eiriktsarpalis** [comment]
Adding an attribute is effectively just implementation detail, so a full review is not needed.
