### ISSUE TITLE
Test failure System.Tests.TimeZoneInfoTests.FijiTimeZoneTest

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70274]
Run: [runtime-coreclr libraries-jitstressregs 20220605.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1807613&view=ms.vss-test-web.build-test-results-tab&runId=48106506&resultId=182585&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstressregs3-Windows.10.Arm64v8.Open

- System.Tests.TimeZoneInfoTests.FijiTimeZoneTest

```
**Error message:**
```
Assert.Equal() Failure
Expected: 13:00:00
Actual:   12:00:00


Stack trace
   at System.Tests.TimeZoneInfoTests.FijiTimeZoneTest() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2890
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by jkotas** [comment]
This test is failing in some environments. It failed on NativeAOT as well https://github.com/dotnet/runtime/issues/69801, but we were not able to reproduce it.

**Comment by filipnavara** [comment]
> Windows.10.Arm64v8.Open

How much up-to-date are those machines? This particular time zone was adjusted around the end of November 2021 in a Windows update. I am not sure about the exact date when the update was published but on November 29, 2021 we had multiple machines with client Windows SKUs that were not updated yet while the Office 365 Exchange servers already had the new TZ definitions. The failure corresponds to the pre-update data.

**Comment by MattGal** [comment]
> @dotnet/dnceng can help answer. I assume the images stay up to date with security patches but possibly not optional patches? If this was one.

Happy to answer here:

- Anything in Windows.10.Arm64v8.Open is not an "image", it's a physical device.  This is because we cannot acquire any Arm64 Azure compute capacity and are running our test infrastructure on (mostly) Samsung GalaxyBooks
- We recently were supposed to have reimaged all the machines in this queue to newer, but in the case of this one (DDARM64-067) it seems to have been overlooked and is running a slightly older OS.  @ilyas1974 is going to follow up with DDFUN on that front.
- In general, we have processes in place to run Windows update / linux package manager update on our on-prem machines monthly, but as these are physical devices managed by DDFUN obviously things slip through the cracks.

While we will continue to try to keep our giant collection of on-premises machines patched, if possible, maybe you could make your tests "aware" of the situation so they pass in either state?

**Comment by MattGal** [comment]
> I believe it is better to make the test tolerant to the running environment.
> 
> @MattGal is there a way you can copy the registry hive under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Fiji Standard Time` on the failing machine to see the TZ data there? just to ensure we can have the test work with such data. Thanks!

Here's the exact .reg contents of the machine which ran the work item log at the top of this issue, sorry about all the encoded text... 

``` 
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Fiji Standard Time]
"Display"="(UTC+12:00) Fiji"
"Dlt"="Fiji Daylight Time"
"MUI_Display"="@tzres.dll,-1140"
"MUI_Dlt"="@tzres.dll,-731"
"MUI_Std"="@tzres.dll,-732"
"Std"="Fiji Standard Time"
"TZI"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,00,\
  00,00,00,00,00,00,00,01,00,05,00,01,00,00,00,00,00,00,00,00,00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones\Fiji Standard Time\Dynamic DST]
"2008"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,00,00,00,00,00,00,00,00,\
  00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00
"2009"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,04,00,01,00,00,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,05,00,02,00,00,00,00,00,00,00
"2010"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,03,00,00,00,05,00,03,00,\
  00,00,00,00,00,00,00,00,0a,00,00,00,04,00,02,00,00,00,00,00,00,00
"2011"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,03,00,00,00,01,00,03,00,\
  00,00,00,00,00,00,00,00,0a,00,00,00,04,00,02,00,00,00,00,00,00,00
"2012"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,04,00,03,00,\
  00,00,00,00,00,00,00,00,0a,00,00,00,03,00,02,00,00,00,00,00,00,00
"2013"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0a,00,00,00,04,00,02,00,00,00,00,00,00,00
"2014"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,02,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,01,00,02,00,00,00,00,00,00,00
"2015"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,01,00,02,00,00,00,00,00,00,00
"2016"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,01,00,02,00,00,00,00,00,00,00
"2017"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,01,00,02,00,00,00,00,00,00,00
"2018"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,01,00,02,00,00,00,00,00,00,00
"FirstEntry"=dword:000007d8
"2019"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2022"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,06,00,01,00,00,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2023"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2024"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2025"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2026"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2027"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2028"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"2029"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0b,00,00,00,02,00,02,00,00,00,00,00,00,00
"LastEntry"=dword:000007e5
"2021"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,03,00,03,00,\
  00,00,00,00,00,00,00,00,01,00,05,00,01,00,00,00,00,00,00,00,00,00
"2020"=hex:30,fd,ff,ff,00,00,00,00,c4,ff,ff,ff,00,00,01,00,00,00,02,00,03,00,\
  00,00,00,00,00,00,00,00,0c,00,00,00,03,00,02,00,00,00,00,00,00,00
```

**Comment by tarekgh** [comment]
Looks like such machine is missing the time zone data for the year `2021`

![image](https://user-images.githubusercontent.com/10833894/172229467-d6adcd89-6af5-4286-b049-329b10f06a49.png)

I'll try to fix the test to handle this case.

**Comment by MattGal** [comment]
@tarekgh are you sure it's not just tacked onto the end of the list in the export?  Unless someone modified my comment without Github knowing, the last two values are 2021 and 2020.

**Comment by tarekgh** [comment]
Oh, sorry. I was expecting to see it in order. never mind then about my last comment. Thanks!

**Comment by tarekgh** [comment]
I have submitted a PR to fix this issue. To summarize, the issue was on the failing machine, it list `"LastEntry"=dword:000007e5` which means the last supported year in TZ data is `2021` while the TZ data include more year's data. the correct value should be `"LastEntry"=dword:000007ed`.
