### ISSUE TITLE
Redirected console colour not working

### ISSUE THREAD

**Issue by adamjones2** [dotnet/runtime#70278]
Hi, I'm looking at https://github.com/dotnet/runtime/issues/33980 but I can't seem to get this to work.

In a Powershell 7 window, I'm running:
```
> $env:DOTNET_CONSOLE_ANSI_COLOR = 1
> filter TestColours { $_ }
> dotnet build | TestColours
```
on a failing build and seeing no colours. I'm using version 6.0.300 of the SDK. Am I using this wrong? (Apologies if it is user error but I couldn't find a documentation page for the switch.)

**Comment by stephentoub** [comment]
It's an undocumented switch that only applies to unix. What OS are you on?

**Comment by adamjones2** [comment]
Ah ok that'll be it thanks, I'm on Windows. Don't suppose there's any equivalent functionality for Windows?

**Comment by stephentoub** [comment]
Not currently. Currently colors on Windows are implemented via Win32 function calls rather than ANSI color escape sequences.

**Comment by adamjones2** [comment]
Cool got it, I've just spotted https://github.com/dotnet/runtime/issues/68340 on this so I'll follow that thread, apologies for the dupe!

**Comment by stephentoub** [comment]
Thanks.
