### ISSUE TITLE
[wasm][debugger] Previous frames on call stack have different line location on Firefox and Chrome

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#70281]
Test `DebuggerTests.BreakpointTests.BreakInDefaultInterfaceMethod` from https://github.com/dotnet/runtime/pull/70002 passes on Chrome but fails on Firefox. Firefox expects the theory's arguments `evaluateAsPrevFrameLine` and `dimAsPrevFrameLine` to be, correspondingly:
1071, 1002
1072, 1031,
38, 1015.

Possible fixes:
- Adjust Firefox's behavior to match Chrome's call stack info. 
- Add mechanism for tests to pass [InlineData] conditionally into the test, to enable different arguments depending on the browser.

**Comment by lewing** [comment]
@thaystg is this still worth looking at in 7?

**Comment by thaystg** [comment]
I think so. I will add to my list to fix it.
