### ISSUE TITLE
Assert failure: !LongFile::IsPathNotFullyQualified(path) || !LongFile::ContainsDirectorySeparator(path)

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#70293]
PMI of Interop\DllImportAttribute\DllImportPath\DllImportPathTest\DllImportPathTest.dll causes:

```
Assert failure(PID 78956 [0x0001346c], Thread: 46696 [0xb668]): !LongFile::IsPathNotFullyQualified(path) || !LongFile::ContainsDirectorySeparator(path)
CORECLR! LoadLibraryExWrapper + 0x1A0 (0x7b1e01fd)
CORECLR! CLRLoadLibraryEx + 0x29 (0x7ae80ecf)
CORECLR! `anonymous namespace'::LocalLoadLibraryHelper + 0xF1 (0x7afdc26e)
CORECLR! `anonymous namespace'::LoadNativeLibraryBySearch + 0x2D7 (0x7afdb2d7)
CORECLR! `anonymous namespace'::LoadNativeLibraryBySearch + 0xB0 (0x7afdb5a0)
CORECLR! `anonymous namespace'::LoadNativeLibrary + 0x453 (0x7afdaeb4)
CORECLR! NativeLibrary::LoadLibraryFromMethodDesc + 0x303 (0x7afda6d5)
CORECLR! `anonymous namespace'::NDirectLink + 0x2C0 (0x7aeff96c)
CORECLR! NDirect::GetStubForILStub + 0x225 (0x7aefb9cf)
CORECLR! GetStubForInteropMethod + 0x27D (0x7aefbc65)
    File: C:\gh\runtime\src\coreclr\utilcode\longfilepathwrappers.cpp Line: 64    Image: c:\gh\runtime\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root\corerun.exe
```

e.g.,
```
pushd c:\gh\runtime\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root
corerun.exe c:\gh\jitutils\bin\pmi.dll DRIVEALL c:\gh\runtime\artifacts\tests\coreclr\windows.x86.Checked\Interop\DllImportAttribute\DllImportPath\DllImportPathTest\DllImportPathTest.dll > pmi-DllImportPathTest-x86.log
popd
```

**Comment by BruceForstall** [comment]
This is also caused by PMI of libraries test System.Runtime.InteropServices.Tests.dll

**Comment by jkoritzinsky** [comment]
cc: @AaronRobinsonMSFT could this be caused by your wprintf work?

**Comment by AaronRobinsonMSFT** [comment]
Yes it could be. I am going to be testing some x86 work shortly and will give this a good then.

**Comment by AaronRobinsonMSFT** [comment]
This is an issue with executing/evaluating test cases that are supposed to run on Unix but running them on Windows. The assert only triggers on Windows due to various security invariants. I will try to narrow the assert instead of defining it out.

https://github.com/dotnet/runtime/blob/febd927b8e4dcdd693e207b31d253ba552471190/src/tests/Interop/DllImportAttribute/DllImportPath/DllImportPathTest.cs#L19

https://github.com/dotnet/runtime/blob/febd927b8e4dcdd693e207b31d253ba552471190/src/tests/Interop/DllImportAttribute/DllImportPath/DllImportPathTest.cs#L47-L48

https://github.com/dotnet/runtime/blob/febd927b8e4dcdd693e207b31d253ba552471190/src/tests/Interop/DllImportAttribute/DllImportPath/DllImportPathTest.cs#L106-L113

https://github.com/dotnet/runtime/blob/febd927b8e4dcdd693e207b31d253ba552471190/src/coreclr/utilcode/longfilepathwrappers.cpp#L62-L66

**Comment by BruceForstall** [comment]
This is a case where PMI is iterating across every function in the assembly and asking the JIT to compile it; it doesn't know that it wouldn't run on the current platform. We do catch errors and continue, but that's a little risky and seems to cause problems in some environments.

**Comment by AaronRobinsonMSFT** [comment]
I think PMI needs to know what not to inspect based on the platform. This assert is correct and should be firing in this case. We can annotate the test if that would help but the product/assert here is correct. If there isn't a way to PMI to annotate the test, then I'd consider this by-design and go with the suppression that PMI has done in the referenced issue.

**Comment by BruceForstall** [comment]
@AndyAyersMS You've worked on PMI -- any ideas on how to keep PMI from compiling things it shouldn't (because they cause asserts)? Maybe we should implement a PMI "exclusion list" that is given a list of fully-qualified method names to skip? Or maybe we can add a queryable function attribute like "[PMIExclude]" and tag functions in the libraries / tests to exclude from PMI?

**Comment by jkotas** [comment]
> `private const string RelativePath3Unix = @"../DllImportPathTest/libDllImportPath_Relative"; `

We should not be asserting when somebody specifies bad library path in C#. If it is an error, we should throw an exception.

**Comment by jkotas** [comment]
Simple repro: 
```
NativeLibrary.Load(@"../DllImportPathTest/libDllImportPath_Relative");
```
Actual result: assert failure
Expected result: exception, no assert failure

**Comment by AaronRobinsonMSFT** [comment]
> Expected result: exception, no assert failure

Okay.

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS You've worked on PMI -- any ideas on how to keep PMI from compiling things it shouldn't (because they cause asserts)? Maybe we should implement a PMI "exclusion list" that is given a list of fully-qualified method names to skip? Or maybe we can add a queryable function attribute like "[PMIExclude]" and tag functions in the libraries / tests to exclude from PMI?

Fixing them seems best. 

But if we wanted to keep these things from blocking PMI driven collection, we could perhaps override the assert behavior. See https://docs.microsoft.com/en-us/visualstudio/debugger/assertions-in-managed-code?view=vs-2022#BKMK_Customizing_Assert_behavior

**Comment by BruceForstall** [comment]
> But if we wanted to keep these things from blocking PMI driven collection, we could perhaps override the assert behavior. See https://docs.microsoft.com/en-us/visualstudio/debugger/assertions-in-managed-code?view=vs-2022#BKMK_Customizing_Assert_behavior

The failures in this issue are native code failures. I think we already handle managed code failures/asserts, but I'm not positive. Doesn't hurt to add even more code to handle it? Defense in depth?
