### ISSUE TITLE
Aes.Create returns null

### ISSUE THREAD

**Issue by SameerK-MSFT** [dotnet/runtime#70290]
### Description

"var aes = Aes.Create("System.Security.Cryptography.AesManaged");" returns null.

### Reproduction Steps

Attempt to create aes for AesManaged:
`var aes = Aes.Create("System.Security.Cryptography.AesManaged");`
aes is returned as null.

### Expected behavior

The return to have a valid instance.

### Actual behavior

Returns null

### Regression?

This was working in the earlier version.

### Known Workarounds

Create instance of System.Security.Cryptography.AesManaged. But this is marked as obsolete.

### Configuration

.net 6.0

**Comment by vcsjones** [comment]
@SameerK-MSFT 

While considering this, I also noticed that I cannot reproduce the reported behavior:

```C#
using System.Security.Cryptography;

var aes = Aes.Create("System.Security.Cryptography.AesManaged");
Console.WriteLine(aes is null);
```

This prints "false" for me and it appears supported:

https://github.com/dotnet/runtime/blob/54f104a16489b7a2fa5b9661e8030aa23aa494b0/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CryptoConfig.cs#L224

Can you provide any additional details to help reproduce this?

1. What operating system you are on.
2. What kind of application this is (Console, WASM, etc).

**Comment by bartonjs** [comment]
> I also noticed that I cannot reproduce the reported behavior

I agree.  Furthermore, the returned object is an AesManaged instance, so it's not an as-cast or anything driving it away.

Of course, the recommendation is

* Whether you're on .NET Framework or .NET (nee Core), you should try to never have the word "AesManaged" in your code.
* Just call Aes.Create() and accept what the platform gives you.

**Comment by SameerK-MSFT** [comment]
Thanks for the quick response. 
@vcsjones  It was on iOS using .net  6 and VS 2022 Preview build.

Just Aes.Create works. @bartonjs the documentation still lists "AesManaged" as valid [here ](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes.create?view=net-6.0#system-security-cryptography-aes-create(system-string)).

**Comment by Fabi** [comment]
> Thanks for the quick response. @vcsjones It was on iOS using .net 6 and VS 2022 Preview build.
> 
> Just Aes.Create works. @bartonjs the documentation still lists "AesManaged" as valid [here ](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes.create?view=net-6.0#system-security-cryptography-aes-create(system-string)).

Works on windows and linux so that might be a reason :D

**Comment by vcsjones** [comment]
> It was on iOS using .net 6 and VS 2022 Preview build.

I suspect this is trimming related. I can reproduce this with macOS if I trim the application. Using:

```C#
using System.Security.Cryptography;

var aes = Aes.Create("System.Security.Cryptography.AesManaged");
Console.WriteLine(aes is null);
```

Publishing with

```shell
dotnet publish -c release /p:PublishTrimmed=true /p:SelfContained=true /p:RuntimeIdentifier=osx.12-arm64 
./bin/release/net7.0/osx.12-arm64/publish/scratch 

```

The trimmed, published binary prints `True`. This makes sense, I suspect `AesManaged` is getting trimmed away if you aren't explicitly keeping the type around.

The correct solution, as previously mentioned, is to use `Aes.Create()`. But this explains the behavior you are using. q

**Comment by vcsjones** [comment]
If you do a clean build and see the following in your build warnings:

>  warning IL2026: Using member 'System.Security.Cryptography.Aes.Create(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The default algorithm implementations might be removed

Then it's likely the `AesManaged` is getting trimmed out.
