### ISSUE TITLE
Potential breaking change in socket close behavior in net6 over net5 on Linux

### ISSUE THREAD

**Issue by romanpolunin** [dotnet/runtime#70311]
It appears that when a NET6 program closes in a non-graceful scenario such as SIG_QUIT, it will modify the SO_LINGER option on its open listening socket. Specifically, it sets SO_LINGER to true, with a timeout of 0 seconds. Kestrel is listening on that socket; we invoke KestrelServerOptions.ListenHandle(...) during startup, and the socket handle is passed in via environment variable - e.g. the listening socket lives longer than the server program.

The code that does that appears to be taking some sort of "abortive" path, as in
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.Unix.cs#L264

The code above seemed similar to us between NET5 and NET6, e.g. the behavior wouldn't change, unless the "abortive" had a different value in NET6 for shutdown initiated with SIG_QUIT.

We were able to prove that when the same dotnet program targeting NET5 is shut down using SIG_QUIT, it does not apply any modification to the listening socket, leading us to believe that the "abortive" path in the code above wasn't taken in NET5, but it's taken in NET6.

In our case, the listening socket was passed to the program at start-up time by handle. We expect our program to not modify attributes of this externally provided socket.

This change in behavior between NET5 and NET6 does not appear in the list of breaking changes for NET6 over NET5.
It appears to be a breaking change to us though. 

If this is indeed a breaking change, we'd like it to be documented.
Also, we need a way to prevent .NET runtime from modifying attributes of this socket.

**Comment by romanpolunin** [comment]
I can also see sort-of relevant conversation in here: https://github.com/dotnet/runtime/issues/43385

**Comment by romanpolunin** [comment]
> Is it Kestrel that's listening?

Kestrel is listening, that's correct. We invoke KestrelServerOptions.ListenHandle(...) during startup, and the socket handle is passed in via environment variable. 

We can't be 100% sure if Kestrel is handling a request during shutdown in all cases: at least one of the affected server applications processes a few hundred requests per second - so there's certainly at least a few requests in flight at shutdown, however another affected server application is not highly loaded and it might potentially be idle at that time.  

> When you create the SafeSocketHandle, have you tried using ownsHandle = false?

We don't use SafeSocketHandle. We pass the handle's parsed ulong directly into KestrelServerOptions.ListenHandle.

**Comment by wfurt** [comment]
Should we transfer this to Kestrel or do you think the fix should some somehow to runtime @tmds? 
I could understand argument that if the `Socket` was created from `descriptor` and does not own it, we should not touch it beyond requested operations. 
I don't know if the Kestrel note about hanging is true for Async operations. AFAIK we had issue only in sync path as we were stuck in kernel call.

**Comment by halter73** [comment]
Kestrel calls `new SafeSocketHandle((IntPtr)fileHandle.FileHandle, ownsHandle: true)`. I think we're getting what we ask forI think the right fix is for Kestrel to use a `CancellationTokenSource` to cancel its a

**Comment by tmds** [comment]
> I guess the only ask would be if we set ownsHandle: false, could Socket still cancel any pending AcceptAsync calls when it's disposed? That'd be ideal.

Yes, I was suggesting this approach in https://github.com/dotnet/runtime/issues/70311#issuecomment-1157686760.

https://github.com/dotnet/runtime/pull/72000 implements it.
