### ISSUE TITLE
System.Net.Http double check

### ISSUE THREAD

**Issue by MattBussing** [dotnet/runtime#70314]
@karelz , you mentioned that we should ask you questions related to System.Net.Http [here](https://github.com/dotnet/runtime/issues/18280#issuecomment-289234304). Also, related comments [1](https://github.com/dotnet/runtime/issues/24382#issuecomment-358349625) and [2](https://github.com/dotnet/runtime/issues/24382#issuecomment-350000563).

### Background
I have been reading through the various GH issues trying to fix the MSB3247 warning related to System.Net.Http:
```
 C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2301,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" /></dependentAssembly></assemblyBinding> [projectA.csproj]
```
MSBuild generates this warning for several C# Web Applications (Web Forms) that I help maintain. I am using MSBuild 17.3.0.22603. The project is using .NET Framework 4.8 and an old style csproj. I reference System.Net.Http via a Reference tag.

So, I think I figured out, by accident, how to fix the warning. My solution was to remove the binding redirect altogether. This is what I had in my Web.config (what I removed):
```
<dependentAssembly>
  <assemblyIdentity name="System.Net.Http" publicKeyToken="B03F5F7F11D50A3A" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.5.0.0" newVersion="4.0.0.0" />
</dependentAssembly>
```
What is weird is the application would work with this binding redirect that redirects to 4.0.0.0 (above), but MSBuild would still warn (MSB3247) about it needing to be redirected to 4.2.0.0. If I do what VS recommends and double click on the warning to have VS fix it. It updates the redirect to:
```
<dependentAssembly>
  <assemblyIdentity name="System.Net.Http" publicKeyToken="B03F5F7F11D50A3A" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
</dependentAssembly>
```
but this actually broke my application during runtime. Super weird. I will get something like "could not find System.Net.Http version 4.2.0.0".

Like I mentioned, if I remove the binding redirect altogether it fixes the issue. 

### Questions

1. What is the recommended way to fix this issue? Will my current solution cause issues in the future? I have the warning, "MSB3247", set as an error via MSBuildWarningsAsErrors/WarningsAsErrors.
2. Will this fix the vulnerability mentioned on nuget.org? See [here](https://www.nuget.org/packages/System.Net.Http/4.3.3) or [here](https://github.com/advisories/GHSA-7jgj-8wvc-jh57)
3. Just to confirm you should use a Reference tag for System.Net.Http (in other words, do not use a PackageReference tag), correct?
4. Using fuslogvw.exe, I was able to see that the app is loading assembly version 4.0.0.0. See the pic below. It mentions it has a redirect to 4.0.0.0. I am not sure where it is detecting that redirect. Why does it get redirected to 4.0.0.0? Why doesn't it use 4.2.0.0? Also, is this expected behavior?

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/31907187/172261505-5027cd2d-e74e-44bf-8fb8-31e9bb687f5e.png">

**Comment by MattBussing** [comment]
For that last question (4) I think I might have solved it. I reset iis' cache and it doesn't have the 4.2.0.0 assembly load anymore. I think that was an artifact from a previous build. 
<img width="593" alt="image" src="https://user-images.githubusercontent.com/31907187/172264928-68ebfeef-a6f9-46f4-b199-1611e3724403.png">

**Comment by MattBussing** [comment]
I was experimenting with this problem recently and noticed that if I add `<PackageReference Include="System.Net.Http" Version="4.3.4" />` to the web application mentioned above that it doesn't copy System.Net.Http to the bin folder and it doesn't warn about binding redirects. Is MSBuild smart enough to know that .NET Framework apps should use the built in System.Net.Http now?

**Comment by karelz** [comment]
@MattBussing if the PackageReference works, then I would highly recommend to use it. I assume something somewhere is smart enough to automatically generate the binding redirects.
This whole topic is super-complicated and involved and I understand only a very small part of it.

BTW: In your original post, you mentioned "Reference tag" - I am not sure what you mean by it. Also, your "current solution" is unclear.
If you still have problems, I would recommend to create HelloWorld-style repro to demonstrate what the problem is and then we can follow up to see if there is still something to fix in the system.

**Comment by karelz** [comment]
Triage: No response for 2 weeks, closing. Feel free to reopen if there is more info available. Thanks!
