### ISSUE TITLE
String.IndexOf doesn't find the index if parameter is cast or converted from int

### ISSUE THREAD

**Issue by jarnmo** [dotnet/runtime#70335]
### Description

string.IndexOf, .LastIndexOf, IndexOfAny, and LastIndexOfAny do not work correctly if the character(s) passed have been cast or converted from int.

### Reproduction Steps

"123".IndexOf('2')
returns 1

"123".IndexOf((char)2)
returns -1

"123".IndexOf(Convert.ToChar(2))
returns -1

### Expected behavior

The string.IndexOf functions should work correctly regardless of the source of the parameter character(s).

### Actual behavior

Check reproduction steps

### Known Workarounds

"123".IndexOf(Convert.ToChar("2"))
returns 1

### Configuration

.NET 6.0.300, x86/x64 on Win 10

**Comment by svick** [comment]
This is the correct behavior. Both `(char)2` and `Convert.ToChar(2)` produce the rarely used control character U+0002 Start of Text. Meanwhile, `'2'` is U+0032 Digit Two.

**Comment by jarnmo** [comment]
Right. What actually lead to me to this confusion was that the VS Immediate Window actually does print `2` for (char)2. Tbf, it does print the unicode as well though. Certainly quite a footgun overall, but I guess it is what it is..
