### ISSUE TITLE
Compat: multiple RuntimeType implementations in NativeAOT cause issue in WPF

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#70351]
When compiling WPF using NativeAOT I found strange issue. This piece of code produce exception. I use regular NativeAOT with reflection, so cannot understand why this is not working.
```
Type runtimeType = typeof(object).GetType();
if (!runtimeType.IsAssignableFrom(type.GetType()))
{
    throw new ArgumentException(SR.Get(SRID.RuntimeTypeRequired, type), "type");
}
```

https://github.com/dotnet/wpf/blob/144290982a74ce332d78e873cf52e3c4cb789d29/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Markup/Baml2006/WpfSharedXamlSchemaContext.cs#L50-L57

Message which I get approximately following
```
System.Reflection.Runtime.TypeInfos.NativeFormat.NativeFormatRuntimeNamedTypeInfo is not a RuntimeType. XamlReader.Load does not support the use of other types of Type.
```
without this small issue, WPF compile okay.

**Comment by MichalStrehovsky** [comment]
This will be fixed when #91704 is fixed (as a side effect), but this is a wrong assumption at the WPF side. There's nothing actionable from the runtime repo side.
