### ISSUE TITLE
SPMI CI runs need to surface context misses

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#70350]
If there are a significant number of misses in SPMI runs then the results we show on the "Extensions" page are very misleading, both for the ASM diffs and TP impact. We need to surface the misses so that we can more easily evaluate whether a normal jit-diff run is needed.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Related, there's a request to surface asserts on the Extensions page as well: https://github.com/dotnet/runtime/issues/61483
