### ISSUE TITLE
Codespaces should include gh cli

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#70361]
This is useful for eg `gh pr checkout 12345`

Install instructions: https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt

Needs edit in https://github.com/dotnet/runtime/blob/main/.devcontainer/Dockerfile then simply test locally with `docker build` and `docker run`

Example https://github.com/letssteam/makecode-lets-steam/blob/3701f915052300b7433d48ac39cb426ff15984a6/.devcontainer/Dockerfile#L26-L31

**Comment by ViktorHofer** [comment]
cc @eerhardt
