### ISSUE TITLE
[API Proposal]: `ProcessModule.Symbols()`

### ISSUE THREAD

**Issue by just-ero** [dotnet/runtime#70380]
### Background and motivation

Enumerating a `ProcessModule`'s debug symbols is part of what I frequently have to do when working with remote process' memory. Finding a symbol's address via its name makes finding data much easier an would be a great quality of life feature.

Important to note here are the following functions:  
* [`SymInitialize`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-syminitialize)
  * Takes a `string?` argument specifying a directory that should be searched for symbol files (for example .PDB files). Passing `null` as this parameter only lists exported symbols loaded by the module as-is. Passing a directory path that does not contain valid symbol files results in a failure to list any symbols at all. Passing a directory path that does contain valid symbol files results in only the symbols from the files being listed.
* [`SymLoadModuleEx`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-symloadmoduleex)
* [`SymEnumSymbols`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-symenumsymbols)
  * Takes a `Mask` argument that filters symbols at call time, allowing the wildcards `"*"` and `"?"`. Specifying a mask speeds up the listing process tremendously.
  * Also takes a [`PSYM_ENUMERATESYMBOLS_CALLBACK`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nc-dbghelp-psym_enumeratesymbols_callback) function which is executed each time a symbol is found. This makes yielding symbols impossible. Multi-threading is not a safe option, since DbgHelp is single-threaded.
* [`SymCleanup`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/nf-dbghelp-symcleanup)

The return type is a `List<SYMBOL_INFOW>`. The [`SYMBOL_INFOW`](https://docs.microsoft.com/en-us/windows/win32/api/dbghelp/ns-dbghelp-symbol_infow) additionally uses the [`SymTagEnum`](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/bkedss5f(v=vs.100)) enumeration.

Windows-only example implementation:
```cs
private void* _hProcess; // Handle to the Process which contains the ProcessModule

public List<SYMBOL_INFOW> Symbols(string mask = "*", string? directory = null)
{
    List<SYMBOL_INFOW> symbols = new();

    if (!SymInitialize(_hProcess, directory, false))
        throw new Win32Exception();

    try
    {
        if (!SymLoadModuleEx(_hProcess, 0, ModuleName, null, BaseAddress, ModuleMemorySize, 0, 0))
            throw new Win32Exception();

        if (!SymEnumSymbols(_hProcess, BaseAddress, mask, enumSyms, 0))
            throw new Win32Exception();
    }
    finally
    {
        SymCleanup(_hProcess);
    }

    return symbols;

    bool enumSyms(ref SYMBOL_INFOW pSymInfo, uing SymbolSizem, nint UserContext)
    {
        symbols.Add(pSymInfo);
        return true;
    }
}
```

### API Proposal

```csharp
namespace System.Diagnostics;

public class ProcessModule
{
    public List<SYMBOL_INFOW> Symbols(string mask = "*", string? directory = null);
}
```

### API Usage

```csharp
var proc = Process.GetCurrentProcess();
var module = proc.MainModule;
foreach (var symbol in module.Symbols())
{
    var name = new string((char*)symbol.Name);
    Console.WriteLine($"{name}: 0x{symbol.Address:X16}");
}
```

### Alternative Designs

The `mask` parameter in the new `Symbol()` method may not be necessary. Even though it does speed up the process of listing the symbols, giving the user the control using LINQ may be preferrable.

Since DbgHelp is all single-threaded, using an `AsyncEnumerable` or similar methods (perhaps simply an `async Task<List<SYMBOL_INFOW>>`) may be much better. On large modules with many symbols, this listing can take multiple seconds. Locking the main thread for that time may not be very liked.

**Comment by Symbai** [comment]
I dont think the public name should be SYMBOL_INFOW. Not only that it doesn't fit into the existing name schema on `Process` class it also doesn't fit for cross platform implementation. It also shouldn't give back the raw structure. So it would require a new .NET class. This will hit performance for sure.

With that said I don't believe it makes sense to add this to the runtime. It feels too niche. On top of that dbghelp.dll that ships with Windows is not always up to date and limited in functionality. I dont think that .NET runtime ships with its own dbghelp.dll. You and everyone else needing this would do better with your own implementation.

**Comment by tommcdon** [comment]
Adding @noahfalk and @mikem8361 for thoughts/feedback

**Comment by just-ero** [comment]
Hi!

Yes, I agree that the use for this is quite niche indeed. I do use it quite frequently, but haven't even found much info about it online, leading me to believe that this is hardly a very useful change for many users. I do think it is a sensible change, though perhaps not a very high priority one.

The example implementation was thrown together quickly, because I wasn't sure whether I should go all-out on my example (especially since I'm quite familiar with dotnet's code style guidelines). My idea (and what I'm doing in my code) was adding a `DebugSymbol` class (name TBD, of course);
```cs
class DebugSymbol
{
    internal DebugSymbol(SYMBOL_INFOW symbolInfo)
    {
        unsafe
        {
            Name = new string(MemoryMarshal.CreateReadOnlySpanFromNullTerminated((char*)(symbol.Name)));
        }

        Address = (IntPtr)(symbol.Address);
        Size = (int)(symbol.Size);
        Flags = symbol.Flags;
        Tag = symbol.Tag;
    }

    public string Name { get; }
    public IntPtr Address { get; }
    public int Size { get; }
    public SymFlagEnum Flags { get; }
    public SymTagEnum Tag { get; }
}
```

Since I assumed this would go beyond a simple example implementation (and I had faith in the dotnet developers to come up with something much smarter than me), I completely omitted this part. Sorry about that.

That said, I think it may be possible to use different functions than what DbgHelp.dll uses here? Something that isn't as limited? The important part is simply not to *only* enumerate PDB symbols, but also exports from within the module.

**Comment by noahfalk** [comment]
In order for the .NET team to add functionality to the core libraries we want to target scenarios that impact a broad number of developers. I'm skeptical this one would have that broad applicability though I'd be glad to leave this request open so that others could tell us if this would be useful to them.

If it is helpful there are a few projects that can extract module exports from a PE image such as:
https://github.com/DKorablin/PEReader/blob/2393f25f77ce01c3be0c147e4251498165763492/PEReader/NTDirectory/Export.cs#L51
https://github.com/dotnet/symstore/blob/main/src/Microsoft.FileFormats/PE/PEFile.cs#L116

**Comment by jkotas** [comment]
As others said, this is too complex to solve across all platforms and too niche to live in .NET runtime core libraries. I think it is save to close this.
