### ISSUE TITLE
[API Proposal]: Analyzer - check allocation non free code during compilation

### ISSUE THREAD

**Issue by Romfos** [dotnet/runtime#70387]
### Background and motivation

Hi,

Could you please implement simple compile-time check for code that do memory allocation?

Basic idea:

[AllocationNonFree] - attribute for method(and maybe other type members) that compiler will be able to recognize as API that do memory allocation. This attribute could be automatically added by compiler
[AllocationFree] - attribute for method(and maybe other type members) that compiler will be able to recognize as API that don't do memory allocation. If method with this attribute have calls to other methods\properties with [AllocationNonFree] attribute  - show warning in this location

This feature would be useful if all BCL classes were marked out of the box + other library developers have started adoption of it
This attributes and diagnostic will help us to make code base better and little bit easier to develop\extend\support :)

Thank you

note:
Similar idea could with speed-optimized code. For example some functions in .NET have 'classic' and more performant alternative. Idea is to make attribute that will be suggest more performant version of API for code with [PerformanceOptimized]  attribute on method

### API Proposal

```csharp

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationNonFreeAttribute : Attribute 
{
}

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationFreeAttribute : Attribute
{
}

```

### API Usage

```csharp

[AllocationFree]
void Foo()
{
  Bar(); //warning
  var x = new string[1]; //warning
}

[AllocationNonFree]
void Bar()
{
}

```

### Alternative Designs

Alternative design #1

```csharp
[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationNonFreeAttribute : Attribute 
{
}

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationFreeAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationFreeInHotPath : Attribute
{
}
```

Api Usage
```csharp
[AllocationFree]
void Foo()
{
  Method1();
  Method2(); //warning
  Method3(); //warning
  var x = new Exception();  //warning
}

[AllocationNonFree]
void Bar()
{
  Method1();
  Method2(); 
  Method3();
  var x = new Exception(); 
}

[AllocationFreeInHotPath]
void Groovy()
{
  Method1();
  Method2();
  Method3(); //warning
  var x = new Exception(); 
}

[AllocationFree]
void Method1()
{
}

[AllocationFreeInHotPath]
void Method2()
{
}

[AllocationNonFree]
void Method3()
{
}

```

### Risks

n\a

**Comment by Romfos** [comment]
Hello, @tfenise. From my point of view in ideal world:

1) case with `if (...) throw new xxxException(...)` - non allocation free
2) case with static constructor - non allocation free
3) case with shared buffer - non allocation free

In not ideal world #1:
We can manually add attribute to shared buffer to suppress this warning

In not ideal world #2:
We can create set of attributes: AllocationFree, AllocationFreeInHotPath(case with exception, static constructor, buffer)

**Comment by Wraith2** [comment]
> This feature would be useful if all BCL classes were marked out of the box + other library developers have started adoption of it
> This attributes and diagnostic will help us to make code base better and little bit easier to develop\extend\support :)

How are you going to use this information to improve code or support?

**Comment by huoyaoyuan** [comment]
This is not ever practical in managed world. In managed world, people very rarely write absolutely no alloc code. The managed environment allows allocation as a fallback used anywhere.
Allocation can also be inferred by method shape: `Try` pattern+writable buffer passed in would probably mean no allocation in typical path.

**Comment by danmoseley** [comment]
Also consider the case where there is amortized zero allocation eg by using array pool, lazy initialization, or chunked allocation (like StringBuilder). These might be effectively zero allocation in real world use. How would you mark them?

**Comment by danmoseley** [comment]
Also zero allocation is not necessarily optional. Usually what you care about is user visible metrics like throughput, startup time, steady state or maximum memory requirements. In some situations minimizing allocations could deoptimize by those measures. Allocations that are collected in Gen0 can be cheap.

Of course we aim to to reduce allocations where we can do so without deoptimizing the code or making it more complex.

**Comment by Romfos** [comment]
Design Proposal #2

```
[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationNonFreeAttribute : Attribute 
{
}

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationFreeAttribute : Attribute
{
}

[AttributeUsage(AttributeTargets.Method)]
public sealed AllocationFreeInHotPath : Attribute
{
}
```

Api Usage
```
[AllocationFree]
void Foo()
{
  Method1();
  Method3(); //warning
  Method2(); //warning
  var x = new string[1]; //warning
}

[AllocationNonFree]
void Bar()
{
  Method1(); //no warning
  Method3(); //no warning
  Method2(); //no warning
  var x = new string[1];  //no warning
}

[AllocationFreeInHotPath]
void Groovy()
{
  Method1(); //no warning
  Method3(); //no warning
  Method2(); //warning
  var x = new string[1];  //no warning
}

[AllocationNonFree]
void Method1()
{
}

[AllocationFreeInHotPath]
void Method2()
{
}

[AllocationNonFree]
void Method3()
{
}

```

**Comment by jeffhandley** [comment]
As the brief discussion here has already revealed, the value of this analyzer is dubious without more information that would help assess the value. The prospect of annotating the base libraries is very unlikely, as that would be a gargantuan effort (similar to the effort to apply nullable attributes, which took several years).

I'm closing the issue, but the suggestion is nonetheless appreciated, @Romfos. If this is still something that could help within your own codebase, I'd encourage you to embark upon creating the attributes and analyzer in a standalone package--perhaps even published to NuGet.
