### ISSUE TITLE
TripleDES Encryption in .NET 6 failure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#70392]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/TripleDES-Encryption-in-NET-6-failure/1649343)._

---
[severity:Other]
I followed this TripleDES url by Copying the code.  However, I get a bad result.  The Url:

https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledes.create?view=net-6.0

I'm working with the EncryptTextToMemory example.  My code:

```
                TripleDES tripleDes = TripleDES.Create("TripleDES");

                string sData = "Here is some data to encrypt.";

                byte[] bytes = Encrypt(sData, tripleDes.Key, tripleDes.IV);
                string final = Decrypt(bytes, tripleDes.Key, tripleDes.IV);

                // here I have 32 bytes
                byte[] fromEncrypt = new byte[data.Length];  

                // here it outputs 24 valid bytes with the remaining with value 0
                csDecrypt.Read(fromEncrypt, 0, fromEncrypt.Length);  
```

The value found in my "final" variable is "Here is some data to enc\0\0\0\0\0\0\0\0".

How do I get this to return the entire string?  Thanks, Joel

---
#### Feedback Bot on 1/28/2022, 08:21 AM: 

(private comment, text removed)
#### jlpm on 1/28/2022, 04:29 PM: 

(private comment, text removed)
#### David Lowndes on 3/1/2022, 08:06 PM: 

(private comment, text removed)
#### jlpm on 3/1/2022, 08:10 PM: 

(private comment, text removed)
#### David Lowndes on 3/2/2022, 00:10 AM: 

(private comment, text removed)
#### David Lowndes on 3/2/2022, 10:42 AM: 

(private comment, text removed)
#### David Lowndes on 3/2/2022, 00:18 PM: 

(private comment, text removed)
#### David Lowndes on 3/2/2022, 00:53 PM: 

(private comment, text removed)
#### jlpm on 3/2/2022, 04:32 PM: 

(private comment, text removed)
#### David Lowndes on 3/2/2022, 04:40 PM: 

(private comment, text removed)
#### Feedback Bot on 5/7/2022, 11:07 AM: 

(private comment, text removed)
#### David Lowndes on 5/7/2022, 03:28 PM: 

(private comment, text removed)
#### jlpm on 5/9/2022, 05:00 PM: 

(private comment, text removed)
#### David Lowndes on 5/9/2022, 05:47 PM: 

(private comment, text removed)
#### jlpm on 5/9/2022, 05:52 PM: 

(private comment, text removed)
#### David Lowndes on 5/9/2022, 06:22 PM: 

(private comment, text removed)
#### jlpm on 5/9/2022, 07:00 PM: 

(private comment, text removed)
#### David Lowndes on 5/9/2022, 09:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by CarnaViire** [comment]
FYI there's some additional discussion in the comments in the original ticket: https://developercommunity.visualstudio.com/t/TripleDES-Encryption-in-NET-6-failure/1649343

**Comment by vcsjones** [comment]
Judging from the name `csDecrypt`, I am guessing `CryptoStream` is involved here.

This is a known behavioral change in .NET 6:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

> `csDecrypt.Read(fromEncrypt, 0, fromEncrypt.Length);`

As noted in the document, `Read` is not guaranteed to read the number of requested bytes. The solution is to call `Read` until the desired number of bytes have been read, or, until there are no more bytes available to read from the stream (`Read` returns 0).

**Comment by svick** [comment]
> This issue wasn't a bug - just a consequence of code that happened to work for the wrong reason under earlier versions of .NET.

There is a bug, but it's in [the example code in the documentation linked above](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledes.create?view=net-6.0#system-security-cryptography-tripledes-create(system-string)), specifically, this part:

```c#
// Read the decrypted data out of the crypto stream
// and place it into the temporary buffer.
csDecrypt.Read(fromEncrypt, 0, fromEncrypt.Length);
```

**Comment by vcsjones** [comment]
> here is a bug, but it's in [the example code in the documentation linked above](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.tripledes.create?view=net-6.0#system-security-cryptography-tripledes-create(system-string)), specifically, this part:

Ah, I see. Yes, that should be fixed.

**Comment by GrabYourPitchforks** [comment]
Also being tracked by https://github.com/dotnet/dotnet-api-docs/issues/8140. I'll leave this issue open for the time being just so it doesn't fall off the radar.
