### ISSUE TITLE
ILLink+NativeAOT testing integration

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#70395]
In order to verify that the NativeAOT compiler is behaving correctly, we have opted for reusing the dotnet/linker unit testing infrastructure in NativeAOT. Relevant changes are that dotnet/linker testing infrastructure is written in NUnit while dotnet/runtime repository uses XUnit. Also, dotnet/linker invested heavily in having some commonality with analyzer warning display, these could make some tests fail just for differences in the way the origin/message is represented. Therefore changes in the NativeAOT product might be necessary.
They are two large sets of changes that will account for testing integration with NativeAOT, one is the part of the infrastructure that verifies warning generation, and the second part is the one that verifies that members are kept.

The following is a list of things that need to be done to complete the NativeAOT testing integration

- [x] Port the Mono.Linker.Tests* files into NativeAOT, account for the translation NUnit->XUnit and special use of .editorconfig file to be able to port the files without significant changes. This enables the warning verification portion. https://github.com/dotnet/runtime/pull/70408
- [x] Add some simple test cases to the testing infrastructure and add running the Mono.Linker.Tests project into clr.toolstests subset (currently only runs for rolling build) https://github.com/dotnet/runtime/pull/70408
- [x] Run clr.toolstests subset every time there is a change in NativeAOT
- [ ] All tests that are related to warning generation are ported and passing
- [x] Enable being able to check for Kept items in the testing infrastructure
- [ ] All test that verify members being Kept are ported and passing

List of issues for NativeAOT related to testing integration:
- https://github.com/dotnet/runtime/issues/68786
- https://github.com/dotnet/runtime/issues/68688
- https://github.com/dotnet/runtime/issues/70687
- https://github.com/dotnet/runtime/issues/70698
- https://github.com/dotnet/runtime/issues/72805
- https://github.com/dotnet/runtime/issues/71985
- https://github.com/dotnet/runtime/issues/72833
- https://github.com/dotnet/runtime/issues/73172
- https://github.com/dotnet/runtime/issues/73321
- https://github.com/dotnet/runtime/issues/73952
- https://github.com/dotnet/runtime/issues/77455
- https://github.com/dotnet/runtime/issues/77744
- https://github.com/dotnet/runtime/issues/81156
- https://github.com/dotnet/runtime/issues/81158

**Comment by MichalStrehovsky** [comment]
@vitek-karas do you think we can close this?

There's also a couple issues linked from the list that are still open but might have been fixed?

**Comment by agocke** [comment]
I'm closing this as completed. There are a few remaining issues, but the vast majority of tests are running successfully.

**Comment by vitek-karas** [comment]
Sorry - I went though all the linked bugs and close them all since we have all of that working already.
