### ISSUE TITLE
System.ExecutionEngineException crash when debugging (0x80131506)

### ISSUE THREAD

**Issue by coujean99** [dotnet/runtime#70409]
### Description

I am studying C# and I found this bug while I was experimenting on a 2D matrix with an indexer.

### Reproduction Steps

Program.cs
```
Class instance = new Class(1, 1);
instance[0, 0] = 1.14F;
Console.WriteLine(instance[0, 0]); // Set a breakpoint here

public class Class
{
    private float[,] float2DTable;

    public Class(int lines, int columns)
    {
        this.float2DTable = new float[lines, columns];
    }

    public float this[int Line, int Column]
    {
        get => float2DTable[Line, Column]; // Here is the problem
        set { float2DTable[Line, Column] = value; }
    }
}
```

### Expected behavior

[echo] 1,14

### Actual behavior

From Visual Studio
**System.ExecutionEngineException**

From the terminal
```
Fatal error. Internal CLR error. (0x80131506)
    at BugGenerator.Class.get_Item(Int32, Int32)
    at Program.<Main>$(System.String[])
```

### Known Workarounds

Using normal get set without lambda
```
public float this[int Line, int Column]
{
    get { return float2DTable[Line, Column]; }
    set { float2DTable[Line, Column] = value; }
}
```

### Configuration

DOTNET version 6.0.300
Windows 10 Pro x64

### Other information

I got this problem after disabling **Step over properties and operators (Managed only)** in debugging options. It runs without problem when I enable it.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas Couldn't this be https://github.com/dotnet/runtime/issues/38777? I'm not sure if that was ported back to 6.0.3.

**Comment by jkotas** [comment]
Yes, this is https://github.com/dotnet/runtime/issues/38777 . I have confirmed that it is fixed in .NET 7.

> I'm not sure if that was ported back to 6.0.3.

This is pretty large delta. I do not think it is a good backport candidate.

@coujean99 Thank you for reporting this issue!
