### ISSUE TITLE
[MongoDB.Driver] some methods throw exception after native compiler

### ISSUE THREAD

**Issue by Jaafar-abusair** [dotnet/runtime#70400]
Hi,

some methods throw exception after native compiler [MongoDB.Driver] and some of them are working fine
The ones listed below are not working when calling them

using "dotnet publish -c Release -r win-x64", i get this errors on build

Not sure which label i should add to the ticket

 `ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<UpdateOneAsync>d__107<System.__Canon>.MoveNext()' will always throw bec
  ause: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<UpdateManyAsync>d__101<System.__Canon>.MoveNext()' will always throw be
  cause: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<ReplaceOneAsync>d__95<System.__Canon>.MoveNext()' will always throw bec
  ause: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<InsertOneAsync>d__74<System.__Canon>.MoveNext()' will always throw beca
  use: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<DeleteOneAsync>d__45<System.__Canon>.MoveNext()' will always throw beca
  use: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1+<DeleteManyAsync>d__37<System.__Canon>.MoveNext()' will always throw bec
  ause: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.UpdateOne(FilterDefinition`1<__Canon>,UpdateDefinition`1
  <__Canon>,UpdateOptions,Func`3<IEnumerable`1<WriteModel`1<__Canon>>,BulkWriteOptions,BulkWriteResult`1<__Canon>>)' will always throw becau
  se: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.UpdateMany(FilterDefinition`1<__Canon>,UpdateDefinition`
  1<__Canon>,UpdateOptions,Func`3<IEnumerable`1<WriteModel`1<__Canon>>,BulkWriteOptions,BulkWriteResult`1<__Canon>>)' will always throw beca
  use: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.ReplaceOne(FilterDefinition`1<__Canon>,__Canon,ReplaceOp
  tions,Func`3<IEnumerable`1<WriteModel`1<__Canon>>,BulkWriteOptions,BulkWriteResult`1<__Canon>>)' will always throw because: Invalid IL or
  CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.InsertOne(__Canon,InsertOneOptions,Action`2<IEnumerable`
  1<WriteModel`1<__Canon>>,BulkWriteOptions>)' will always throw because: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.DeleteOne(FilterDefinition`1<__Canon>,DeleteOptions,Func
  `3<IEnumerable`1<WriteModel`1<__Canon>>,BulkWriteOptions,BulkWriteResult>)' will always throw because: Invalid IL or CLR metadata
  ILC: Method '[MongoDB.Driver]MongoDB.Driver.MongoCollectionBase`1<System.__Canon>.DeleteMany(FilterDefinition`1<__Canon>,DeleteOptions,Fun
  c`3<IEnumerable`1<WriteModel`1<__Canon>>,BulkWriteOptions,BulkWriteResult>)' will always throw because: Invalid IL or CLR metadata
     Creating library bin\x64\Release\net6.0\win-x64\native\test-native.lib and object bin\x64\Release\net6.0\win-x64\native\test-native.exp
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-ill
  ink
  test-native -> E:\test-native2\test-native\bin\x64\Release\net6.0\win-x64\publish\`

**Comment by jkotas** [comment]
Generic exceptions https://github.com/mongodb/mongo-csharp-driver/blob/master/src/MongoDB.Driver/MongoCollectionBase.cs#L245

This is #67806

**Comment by Jaafar-abusair** [comment]
@jkotas  thank you for your replay, is there anything to do from my side?

**Comment by jkotas** [comment]
The only way to workaround this issue is to avoid `catch` with a generic exception type. You can do that by e.g. changing `catch (MongoBulkWriteException<TDocument> ex)` to `catch (Exception ex) when (ex is MongoBulkWriteException<TDocument>)`. The fix we need to implement for #67806 is to do this transformation in the AOT compiler.

**Comment by Jaafar-abusair** [comment]
But im not the owner of MongoDriver, i'm just using the it, can i do that from my side?

this is what i get when it get called

`System.AggregateException: One or more errors occurred. (Common Language Runtime detected an invalid program.)
       ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
         at Internal.Runtime.TypeLoaderExceptionHelper.CreateInvalidProgramException(ExceptionStringID) + 0x31
         at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowInvalidProgramException(ExceptionStringID) + 0x9
         at MongoDB.Driver.MongoCollectionBase`1.<UpdateManyAsync>d__101.MoveNext() + 0xe
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&) + 0x5f
         at MongoDB.Driver.MongoCollectionBase`1.UpdateManyAsync(FilterDefinition`1, UpdateDefinition`1, UpdateOptions,`

**Comment by jkotas** [comment]
There is nothing you can do about it from your side without changing the MongoDriver.

**Comment by jkotas** [comment]
I am not sure when we get to fixing this.

**Comment by Jaafar-abusair** [comment]
Thanks buddy

**Comment by JulieLeeMSFT** [comment]
cc @EgorBo.
We will try to fix this in .NET 7.
