### ISSUE TITLE
System. Drawing. Common does not support webp

### ISSUE THREAD

**Issue by yaphet266** [dotnet/runtime#70418]
I hope GDI can support webp

**Comment by teo-tsirpanis** [comment]
Actually [GDI+ supports webp](https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-constant-image-file-format-constants) (can't see since which version).

@yaphet266 can you propose an API for it? It would be just a new member in the `ImageFormat` class.

**Comment by teo-tsirpanis** [comment]
The GUID corresponding to WebP is `{B73C6BB9-2807-D311-9D7B-0000F81EF32E}` [^1]. I have opened #70422 to track adding the API in `System.Drawing.Common`. Until then you can create an `ImageFormat` object with the above GUID yourself. I am going to close this issue, let me know if something went wrong.

[^1]: https://source.terrafx.dev/#TerraFX.Interop.Windows/Gdiplus/um/gdiplusimaging/Gdiplus.cs,aad257ea3a53852b

**Comment by yaphet266** [comment]
> The GUID corresponding to WebP is `{B73C6BB9-2807-D311-9D7B-0000F81EF32E}` [1](#user-content-fn-1-8c96b45242dcf34be5d7e71b8fe7acee). I have opened #70422 to track adding the API in `System.Drawing.Common`. Until then you can create an `ImageFormat` object with the above GUID yourself. I am going to close this issue, let me know if something went wrong.
> 
> ## Footnotes
> 1. https://source.terrafx.dev/#TerraFX.Interop.Windows/Gdiplus/um/gdiplusimaging/Gdiplus.cs,aad257ea3a53852b [↩](#user-content-fnref-1-8c96b45242dcf34be5d7e71b8fe7acee)

Thank you. How can I use it

**Comment by teo-tsirpanis** [comment]
``` csharp
ImageFormat webp = new ImageFormat(new Guid("{B73C6BB9-2807-D311-9D7B-0000F81EF32E}"));

Image image = // your image
image.Save("image.webp", webp);
```
