### ISSUE TITLE
[API Proposal]: [QUIC] QuicProvider

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#70424]
### Background and motivation

API design for exposing static `QuicProvider` to the public.
MsQuic, the underlying implementation for System.Net.Quic, doesn't support all platforms .NET does, e.g.: Win 11+. So we need a static way to check whether QUIC is supported or not. `QuicProvider` class is based on `QuicImplementationProvider` we had in 6.0.

Apart from `IsSupported`, we're also putting methods for connection and listener creation here.

### API Proposal

```csharp
public static class QuicProvider
{
    public bool IsSupported { get; }
    public static ValueTask<QuicListener> CreateListenerAsync(QuicListenerOptions options, CancellationToken cancellationToken = default);
    public static ValueTask<QuicConnection> CreateConnectionAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken = default);
}
```

### API Usage

```csharp
if (QuicProvider.IsSupported)
{
    // QuicListenerOptions in https://github.com/dotnet/runtime/issues/67560
    // Listener will be already listening for incoming connections when returned.
    var listener = await QuicProvider.CreateListenerAsync(listenerOptions);
}
if (QuicProvider.IsSupported)
{
    // QuicClientConnectionOptions in https://github.com/dotnet/runtime/issues/68902
    // Connection will be already connected when returned.
    var connection = await QuicProvider.CreateConnectionAsync(connectionOptions);
}
```

### Alternative Designs

Not having `QuicProvider` at all. Then, moving `IsSupported` to either `QuicListener`, `QuicConnection` or `QuicStream` and providing static `CreateAsync` methods on `QuicListener` and `QuicConnection`.

### Risks

As I'll state with all QUIC APIs. We might consider making all of these PreviewFeature. Not to deter user from using it, but to give us flexibility to tune the API shape based on customer feedback.
We don't have many users now and we're mostly making these APIs based on what Kestrel needs, our limited experience with System.Net.Quic and my meager experiments with other QUIC implementations.

cc: @JamesNK @Tratcher @wfurt @CarnaViire @rzikm

**Comment by terrajobst** [comment]
* Consider removing `QuicProvider` and instead have the factory methods on `QuicListener` and `QuicConnection`.
    - This also allows modelling platforms that only support just one side of QUIC

```C#
namespace System.Net.Quic;

public static class QuicProvider
{
    public static bool IsSupported { get; }
    public static ValueTask<QuicListener> CreateListenerAsync(QuicListenerOptions options, CancellationToken cancellationToken = default);
    public static ValueTask<QuicConnection> CreateConnectionAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken = default);
}
```

**Comment by ManickaP** [comment]
https://github.com/dotnet/runtime/pull/70421
