### ISSUE TITLE
[API Proposal]: Add Microseconds and Nanoseconds to Stopwatch

### ISSUE THREAD

**Issue by cubidobusinesssolutions** [dotnet/runtime#70425]
### Background and motivation

Follow-up of #23799 

### API Proposal

```csharp
namespace System.Diagnostics;

public class Stopwatch
{
  /// <summary>Gets the total elapsed time measured by the current instance, in microseconds.</summary>
  /// <returns>A read-only long integer representing the total number of microseconds measured by the current instance.</returns>
  public long ElapsedMicroseconds { get; }
  /// <summary>Gets the total elapsed time measured by the current instance, in nanoseconds.</summary>
  /// <returns>A read-only long integer representing the total number of nanoseconds measured by the current instance.</returns>
  public long ElapsedNanoseconds { get; }
}
```

### API Usage

```csharp
var sw = Stopwatch.StartNew();
// measure code of interest
Thread.SpinWait(1000);
sw.Stop();

// already possible
long milliseconds = sw.ElapsedMilliseconds;
// proposal
long microseconds = sw.ElapsedMicroseconds;
long nanoseconds = sw.ElapsedNanoseconds;
```

### Alternative Designs

```csharp
var milliseconds = sw.ElapsedMilliseconds;
// workaround: detour over Stopwatch.Elapsed
var microseconds = Convert.ToInt64(sw.Elapsed.TotalMicroseconds);
var nanoseconds = Convert.ToInt64(sw.Elapsed.TotalNanoseconds);
```

**Comment by danmoseley** [comment]
Maybe we should special case Stopwatch into area-System.Runtime label as it's really not diagnostics..

**Comment by tannergooding** [comment]
I don't have any concerns on that (cc. @dotnet/area-system-runtime). That's where the other "time-like" types live as well (@tarekgh generally helps look at those, so they may also be interested in this one).

**Comment by stephentoub** [comment]
> ElapsedMicroseconds / ElapsedNanoseconds

Unlike the other mentioned types, `Stopwatch` doesn't have `ElapsedDays`/`ElapsedHours`/`ElapsedMinutes`/`ElapsedSeconds`/etc... it only has `ElapsedMilliseconds` (and ticks), and it's only there for convenience.  `Stopwatch` already exposes `Elapsed`, which returns a `TimeSpan`, which in .NET 7 has `{Total}Microseconds` and `{Total}Nanoseconds` properties.  Thus you can already do `stopwatch.Elapsed.TotalMicroseconds` and `stopwatch.Elapsed.TotalNanoseconds`, which seems sufficient to me such that we shouldn't add more `ElapsedXx` properties.

**Comment by cubidobusinesssolutions** [comment]
@stephentoub 
> Thus you can already do stopwatch.Elapsed.TotalMicroseconds and stopwatch.Elapsed.TotalNanoseconds

`TimeSpan.TotalMicroseconds` is `double` (in order to match the others, see Notes section at #23799) whereas `Stopwatch.ElapsedMicroseconds` would be `long`. So one would have to write `Convert.ToInt64(sw.Elapsed.TotalMicroseconds)` which is not optimal.

**Comment by cubidobusinesssolutions** [comment]
In case anyone needs this:
```cs
namespace System.Diagnostics;
public static class StopwatchExtensions
{
  public static long ElapsedMicroseconds(this Stopwatch sw) => sw.Elapsed.Ticks / TimeSpan.TicksPerMicrosecond);
  public static long ElapsedNanoseconds(this Stopwatch sw) => sw.Elapsed.Ticks / TimeSpan.TicksPerNanosecond);
}
```

**Comment by tannergooding** [comment]
> If you needed the value as a long rather than a double, you can just cast it to a long

It's worth noting there is some nuance here around there being quite a bit more computation (and potential loss of data) being done when you go through `TimeSpan`. `Stopwatch.ElapsedMicroseconds` could compute and return a correct result much more efficiently.

Given that `Stopwatch` is exposes the high-precision timer, it might be worthwhile covering `Microseconds` and `Nanoseconds` in addition to the current `Milliseconds`. Other larger values would likely be outside the purview of what you'd want `Stopwatch` for.

I'm not convinced they're needed, but I did want to call out that there is some potential consideration here around "why" its worth special casing it. The "correct" thing for the user to do if they wanted a `long` result would be `stopwatch.Elapsed.Ticks / TimeSpan.TicksPer...`

**Comment by danmoseley** [comment]
> I don't have any concerns on that (cc. @dotnet/area-system-runtime). That's where the other "time-like" types live as well (@tarekgh generally helps look at those, so they may also be interested in this one).

Yes we have other examples like Uri. If you want to do this then obviously as well as updating area-owners.md you will need to do some search-and-relabel of older stuff then ask for a retrain.

**Comment by cubidobusinesssolutions** [comment]
@tannergooding 

> The "correct" thing for the user to do if they wanted a `long` result otherwise would be `stopwatch.Elapsed.Ticks / TimeSpan.TicksPer...`

Thanks, description updated.
