### ISSUE TITLE
[API Proposal]: IGetDebuggerDisplay

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#70426]
### Background and motivation

I believe that annotating classes with ```[DebuggerDisplayAttribute]``` is an important but often-overlooked step.  When building a DebuggerDisplay, I also think it is important to make the value accessible but not too accessible.  Derived classes, test classes, or parent classes might want this value but it should likely not be a public property or method.

In my own code, I often have an ```IGetDebuggerDisplay``` interface which I explicitly implement.  This allows me to retrieve the value when I want it but does not pollute publicly listed members.

( This is prompted by the work on #65724 ).

### API Proposal

```csharp
namespace System.Diagnostics {

public interface IGetDebuggerDisplay
{
    string GetDebuggerDisplay();
}
```

### API Usage

```csharp

public class Foo : IGetDebuggerDisplay {
  string IGetDebuggerDisplay.GetDebuggerDisplay() {
    return "Hello World";
  }
}

```

### Alternative Designs

Instead of using a method, you could potentially use a property.  In my own code, I originally used properties but then switched to methods because of the following:
1.  Conceptually, I don't like that because properties denote fixed, non-computed values and the DebuggerDisplay tends to be computed.
2. Some libraries give options or have defaults that will try to serialize private properties.  By using a method, it avoids issues with other properties.
3. Overriding/implementing a method takes less ceremony than a property because you don't have the extract ```get { ... }``` code.

### Risks

None.

**Comment by huoyaoyuan** [comment]
> Derived classes, test classes, or parent classes might want this value

No they shouldn't. `DebuggerDisplay` is solely for, as it says, an attached debugger. It's not meant for programmatically retrieving.

> In my own code, I often have an `IGetDebuggerDisplay` interface which I explicitly implement. This allows me to retrieve the value when I want it but does not pollute publicly listed members.

What's wrong with `ToString` then?

**Comment by svick** [comment]
@huoyaoyuan 

> No they shouldn't. `DebuggerDisplay` is solely for, as it says, an attached debugger. It's not meant for programmatically retrieving.

Personally, I think that `DebuggerDisplay` is useful for anyone who is debugging their code, whether or not they're using a debugger. So I wouldn't be against adding a method that formats an object based on its `DebuggerDisplay`. It could look like this:

```c#
public static class Debug
{
    public static string ToString(object obj);
}
```

But I don't think there is a need to add `IGetDebuggerDisplay`.

**Comment by tommcdon** [comment]
@TonyValenti  Thanks for the suggestion!  The `DebuggerDisplayAttribute` is a [debugger contract](https://docs.microsoft.com/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2022) which enables customizing expression evaluation while debugging.  As @svick correctly states, the debugger will call "ToString()" on the object if there is no `DebuggerDisplayAttribute` present on the object.  If there are missing expression evaluation capabilities in Visual Studio, I suggest opening a Visual Studio feedback item to provide feedback on improving debugging experience.
