### ISSUE TITLE
[NativeAot] Integrate SingleFileTestRunner to the default runner

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#70432]
NativeAot testing currently uses a [custom ](https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/SingleFileTestRunner/SingleFileTestRunner.cs)runner but should be integrated to the [default ](https://github.com/dotnet/arcade/tree/main/src/Microsoft.DotNet.XUnitConsoleRunner/src)runner to take advantage of the full runner capabilities.

**Comment by MichalStrehovsky** [comment]
Closing in favor of #91069.
