### ISSUE TITLE
StringComparer.CurrentCultureIgnoreCase.GetHashCode is broken (on Blazor)

### ISSUE THREAD

**Issue by tfenise** [dotnet/runtime#70441]
### Description

`StringComparer.CurrentCultureIgnoreCase.GetHashCode` is broken on [Try .NET](https://github.com/dotnet/try) used by Microsoft Docs, which is powered by Blazor.

### Reproduction Steps

Go to https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.-ctor?view=net-6.0#code-try-7. Run the code example in the online .NET Editor.

### Expected behavior

It should produce the output as indicated at the end of the code example.

In particular,
```
Dictionary<string, string> openWith =
    new Dictionary<string, string>(
    StringComparer.CurrentCultureIgnoreCase);
openWith.Add("bmp", "paint.exe");
openWith.Add("BMP", "paint.exe");
```
should fail.

### Actual behavior

The actual output is different from what is indicated at the end of the code example. In particular, `openWith.Add("BMP", "paint.exe");` succeeds. Further investigation reveals that `StringComparer.CurrentCultureIgnoreCase.Equals("bmp", "BMP")` is indeed `true`, but `StringComparer.CurrentCultureIgnoreCase.GetHashCode("bmp")` and `StringComparer.CurrentCultureIgnoreCase.GetHashCode("BMP")` happen to be different.

### Regression?

I don't know.

### Known Workarounds

None.

### Configuration

I am not familiar with Blazor, but `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription` says `Mono 6.5.0 (explicit/9f49cc85af1)`. I am using Microsoft Edge 102.0.1245.33 (64bit) on Windows 11 x64.

The (offline, non-Blazor) .net on my computer seems to have no problem with this code example.

**Comment by radical** [comment]
I think `Try .net` is using a very old version of Blazor. I tried the test code with a .net6 blazor template, and I get:
<img width="1358" alt="Screen Shot 2022-07-05 at 2 08 46 PM" src="https://user-images.githubusercontent.com/1472/177389425-de2773c4-068c-4558-a0d3-2ea872f03ccc.png">
And `typeof(object).Assembly.GetName().FullName` -> `mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e` on `try.dot.net`.

@tarekgh do you know who maintains `try.dot.net`?

**Comment by tarekgh** [comment]
@radical you may start with @colombod as I am seeing he is the one committing regularly to that repo. Or you can just open a new issue there.
