### ISSUE TITLE
Revisit lclVar ref count updates when remorphing.

### ISSUE THREAD

**Issue by pgavlin** [dotnet/runtime#7047]
Remorphing a tree can introduce or remove references to existing lclVars, but the morpher is not designed to update lclVar ref counts (as global morphing happens before lclVar refcounts have been initialized). This can cause assertions later on in the pipeline (see e.g. dotnet/runtime#7035). dotnet/coreclr#8284 contains a conservative fix for remorphing that happens via `fgMorphBlockStmt`, but it may be advantageous to change the design s.t. we can be more precise.
category:correctness
theme:ref-counts
skill-level:expert
cost:medium

**Comment by erozenfeld** [comment]
@AndyAyersMS Can this be closed now that #10702 is done?

**Comment by AndyAyersMS** [comment]
Yes.
