### ISSUE TITLE
[API Proposal]: IsEmpty for Collections

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#70473]
### Background and motivation

It is really nice that immutable collections and dictionaries have an ```IsEmpty``` property.

I believe this should be expanded to all collections and dictionaries.  Additionally, a linq IsEmpty method should be created as well.

### API Proposal

```csharp

namespace System.Linq {
  public class Enumerable {
    public static bool IsEmpty(this IEnumerable<T> This) => !This.Any();
  }
}

namespace System.Collections {
    public interface ICollection {
        public bool IsEmpty => Count == 0;
    }
}


namespace System.Collections.Generic {
    public interface ICollection<T> {
        public bool IsEmpty => Count == 0;
    }
}
```

### API Usage

```csharp
var V = new List<string>();

if(V.IsEmpty){
 
}
```

### Alternative Designs

None

### Risks

None.  This will clean up code and remove lots of ``` .Count == 0``` and `` .Count != 0```.

**Comment by vcsjones** [comment]
The `IsEmpty` on enumerable has come up a number of times.

* https://github.com/dotnet/runtime/issues/28610
* https://github.com/dotnet/runtime/issues/27661

**Comment by eiriktsarpalis** [comment]
In that case, I'd be inclined to close this as a duplicate.
