### ISSUE TITLE
Test `System.Tests.TimeZoneInfoTests.LocalTzIsNotUtc` is failing on Android

### ISSUE THREAD

**Issue by maraf** [dotnet/runtime#70482]
Test `System.Tests.TimeZoneInfoTests.LocalTzIsNotUtc` is failing on Android on runtime-extra-platforms

- [All failures via Runfo in last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.tests.timezoneinfotests.localtzisnotutc%22)
    - 6/16 - 62 failures (20 in Rolling test runs) in last 7 days
        - 67 failures (24 in Rolling test runs) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.tests.timezoneinfotests.localtzisnotutc%22)

- [#20220609.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1815228&view=logs&j=0f546c32-999b-56dd-5ce9-08c68d21e4c4&t=74727783-ba2d-5b46-44bc-42ba967ce1c5)

```
Assert.NotEqual() Failure
Expected: Not "Coordinated Universal Time"
Actual:   "Coordinated Universal Time"
   at System.Tests.TimeZoneInfoTests.LocalTzIsNotUtc() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2953
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

Test added in https://github.com/dotnet/runtime/pull/70149

|Build|Kind|Start Time|
|---|---|---|
[1815228](https://dev.azure.com/dnceng/public/_build/results?buildId=1815228)|Rolling|2022-06-09|

**Comment by maraf** [comment]
cc @steveisok

**Comment by steveisok** [comment]
Ah, this is failing on emulators.  The intent of the test was to be device only.

**Comment by maraf** [comment]
It is still failing [#20220612.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1820505&view=logs&j=b6e5d97f-d4f8-506b-9e47-e3e32385754a&t=94ce2805-f3e2-5f9a-1d92-0da5613f733d)

```
<test name="System.Tests.TimeZoneInfoTests.LocalTzIsNotUtc" type="System.Tests.TimeZoneInfoTests" method="LocalTzIsNotUtc" time="0.0194961" result="Fail">
  <traits>
    <trait name="category" value="AdditionalTimezoneChecks" />
  </traits>
  <failure exception-type="Xunit.Sdk.NotEqualException">
    <message><![CDATA[Assert.NotEqual() Failure\nExpected: Not \"Coordinated Universal Time\"\nActual:   \"Coordinated Universal Time\"]]></message>
    <stack-trace><![CDATA[   at System.Tests.TimeZoneInfoTests.LocalTzIsNotUtc() in /_/src/libraries/System.Runtime/tests/System/TimeZoneInfoTests.cs:line 2955
at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)]]></stack-trace>
  </failure>
</test>
```

**Comment by steveisok** [comment]
Weird.  We must have a device configured with a UTC tz.

**Comment by karelz** [comment]
@steveisok this is failing in every rolling test run this week. Can we please disable the test ASAP?
