### ISSUE TITLE
[Wasm] AOT support for threading-enabled runtime

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#70489]
### Description

Building AOT images with threading enabled is failing.

### Reproduction Steps

When building AOT images with threading enabled, the following lines:

https://github.com/dotnet/runtime/blob/3d74b00659fec817506e2888f87936518556e01c/src/mono/wasm/runtime/driver.c#L479-L482

cause the following error:

```
`not compiled with safepoints`
```

@lambdageek mentioned that the environment needs to have `MONO_THREADS_SUSPEND=coop` set before invoking the compiler, but the compilation fails with the following:
```
* Assertion at /__w/Uno.DotnetRuntime.WebAssembly/Uno.DotnetRuntime.WebAssembly/runtime/src/mono/mono/mini/mini.c:2752, condition `mini_safepoints_enabled ()' not met
```
https://github.com/dotnet/runtime/blob/e3a4db9d53d0fc254759047d5859c5f4bd461da3/src/mono/mono/mini/mini.h#L2931-L2937

### Expected behavior

Compilation succeeds.

### Actual behavior

See above.

### Regression?

No

### Known Workarounds

None

### Configuration

213b4d436ed58b9fb1bbf5e0667ea44df1f8c914

**Comment by lambdageek** [comment]
Ideally we can produce a single `mono-aot-cross` AOT compiler that is usable for wasm with and without threading.  So we shoudl get rid of `#ifdef` paths and replace them with an aot compiler flag to decide if we're targeting a threaded runtime.

Another thing the flag could control is whether LLVM is allowed to use post-MVP atomics opcodes

**Comment by lewing** [comment]
@vargaz  did https://github.com/dotnet/runtime/pull/70520 resolve this fully?

**Comment by jeromelaban** [comment]
@lewing This issue was using a similar change in the runtime (with safe point enabled) and it is still present.

**Comment by radical** [comment]
@kg should this be moved to 8.0?

**Comment by kg** [comment]
I think so.

**Comment by lambdageek** [comment]
I think we're done here, actually. The AOT compiler now has a `--wasm-gc-safepoints` and the Wasm SDK now passes it automatically by default when the `WasmEnableThreads` property is true.

demo: https://lambdageek.dev/dotnet-wasm-raytracer/ (AOT+SIMD+threads)
