### ISSUE TITLE
The WriteOnceBlock<T> behaves unexpectedly with AsObservable

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#70481]
### Description

In a [recent question](https://stackoverflow.com/questions/72558093/in-rx-net-how-do-i-make-a-subject-to-resemble-taskcompletionsource-behavior) on StackOverflow someone asked for a `Subject<T>` with write-once semantics, and I thought that wrapping a [`WriteOnceBlock<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.writeonceblock-1) from the TPL Dataflow library would make for an easy implementation. Unfortunately this idea doesn't seem to work, because the `WriteOnceBlock<T>`+[`AsObservable`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.dataflowblock.asobservable) combination doesn't propagate any value to its observers. Although a value has been posted to the block, and the block has not been completed, the [`IObservable<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.iobservable-1) wrapper of the block doesn't notify the observer with an `OnNext()` notification, and instead it emits instantly an `OnCompleted()` notification.

### Reproduction Steps

```C#
using System;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;

class Program
{
    static async Task Main()
    {
        var block = new WriteOnceBlock<int>(x => x);
        block.Post(1);
        block.Post(2);
        Console.WriteLine($"Subscribing...");
        var subscription = block.AsObservable().Subscribe(new MyObserver<int>());
        await Task.Delay(500);
        Console.WriteLine($"Unsubscribing...");
        subscription.Dispose();
    }

    class MyObserver<T> : IObserver<T>
    {
        public void OnNext(T value) => Console.WriteLine($"Observer.OnNext({value})");
        public void OnCompleted() => Console.WriteLine($"Observer.OnCompleted()");
        public void OnError(Exception error) => Console.WriteLine($"Observer.OnError({error})");
    }
}
```

Output:

```none
Subscribing...
Observer.OnCompleted()
Unsubscribing...
```

[Live demo](https://dotnetfiddle.net/vPpoe5).

### Expected behavior

An `Observer.OnNext(1)` message should be written in the output.

### Actual behavior

An `Observer.OnNext(1)` message is not written in the output. An unexpected `Observer.OnCompleted()` message is written instead.

### Regression?

The actual behavior on .NET Framework 4.8 is the same.

### Known Workarounds

I am not aware of any.

### Configuration

- .NET 6.0
- Windows 10
- 64-bit operating system, x64-based processor

### Other information

I tested some other dataflow blocks, like the `BufferBlock<T>`, the `TransformBlock<I,O>` and the `BroadcastBlock<T>`, and all behave as expected when converted to `IObservable<T>`s. Only the `WriteOnceBlock<T>` exhibits this unexpected behavior.

**Comment by joperezr** [comment]
cc: @stephentoub  can you take a look?

**Comment by stephentoub** [comment]
> because the WriteOnceBlock<T>+AsObservable combination doesn't propagate any value to its observers

It will if the posting to the WriteOnceBlock happens after the observers have already been subscribed, e.g. if you move the line
```C#
var subscription = block.AsObservable().Subscribe(new MyObserver<int>());
```
up to before the posts.

WriteOnceBlock only ever has a single value, which is consumable any number of times, and as such the block completes as soon as it's been given a value.  AsObservable checks whether a source has completed and takes that as an indication that no more data will be coming.  So if you subscribe the observer prior to data being passed to the WriteOnceBlock, the WriteOnceBlock will dutifully propagate that data to linked targets prior to completing and the observer will receive it, but if the observer is subscribed  after the WriteOnceBlock has completed, it'll assume no data is coming, and it'll itself signal completion.

It's possible those checks could be removed from AsObservable, at some expense if the source has already completed, but at present WriteOnceBlock composability with AsObservable isn't perfect.

**Comment by theodorzoulias** [comment]
@stephentoub this was quite an insight. Thanks for the explanation! I am not actually planning to use the `WriteOnceBlock<T>` in combination with Rx, because there are other more direct ways to do what I want. But I'm glad that I asked because I learned something. 😃
