### ISSUE TITLE
Optimize implementation of Array.Fill.

### ISSUE THREAD

**Issue by jamesqo** [dotnet/runtime#7049]
The `Array.Fill` api which was just added is a very naive implementation. We should look into the perf benefits of implementing it in C++ and doing things like memset for bytes/avoiding multiple type-checks for reference types. Relevant comment: https://github.com/dotnet/coreclr/pull/8137#discussion_r88143551

**Comment by xtqqczze** [comment]
@GrabYourPitchforks #51365 didn't touch the `Array.Fill` implementation, should this issue be reopened?

**Comment by GrabYourPitchforks** [comment]
@xtqqczze Whoops, good catch.
