### ISSUE TITLE
[Arm64 Server Throughput] Address many-core scaling challenges

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#70528]
# Overview
Arm64 servers such as Ampere come with tens of or hundreds of cores, and there can be new challenge to scale the current runtime, OS and tools to support those many cores.

## Work Item
- [x] Fix `ConcurrentQueue` scaling issues in `PinnedBlockMemoryPool` and `SocketSenderPool` in Kestrel - https://github.com/dotnet/aspnetcore/pull/40476, https://github.com/dotnet/aspnetcore/pull/42237
- [x] Fix `ConcurrentQueue` scaling issues in the thread pool global queue - https://github.com/dotnet/runtime/pull/69386

## Metrics

- From fixing the `ConcurrentQueue` scaling issues, throughput improves significantly in some ASP.NET benchmarks

## What Success Looks Like

- The `ConcurrentQueue` usages above are not significant bottlenecks in the throughput of ASP.NET benchmarks

CC @mangod9

**Comment by mangod9** [comment]
assume the first issue is something @sebastienros is looking into?

**Comment by JulieLeeMSFT** [comment]
We have x5 more perf than .NET 6. 
In .NET 7, it is 11% better than 28 cores when using 80 cores. More work needs to be done in the future to improve the perf more.
Thanks @kouvel  and @sebastienros for your work.

![image](https://user-images.githubusercontent.com/63486087/176739309-b0c723b7-0e11-4c8b-b7bb-c72bad80ca7b.png)

**Comment by richlander** [comment]
> In .NET 7, it is 11% better than 28 cores when using 80 cores.

Just so this is a bit clearer, you are saying: 

80 cores delivers 1.11x better performance than 28 cores, when it should be (ideally) 2.8x.

Right? Clearly 80 cores costs more than 1.11x more than 28 cores.

**Comment by EgorBo** [comment]
> > In .NET 7, it is 11% better than 28 cores when using 80 cores.
> 
> Just so this is a bit clearer, you are saying:
> 
> 80 cores delivers 1.11x better performance than 28 cores, when it should be (ideally) 2.8x.
> 
> Right? Clearly 80 cores costs more than 1.11x more than 28 cores.

.NET is still not very optimized for systems with many cores, namely, multiple NUMA nodes. If I am not mistaken, that 80core CPU consists of 4 NUMA nodes so ideally, an application should avoid accessing data common between nodes. There are multiple issues:

- https://github.com/dotnet/runtime/issues/54276
- https://github.com/dotnet/runtime/issues/58184
- https://github.com/dotnet/runtime/issues/36447
- https://github.com/dotnet/runtime/issues/9748

**Comment by richlander** [comment]
Ah. If this benchmark is crossing NUMA nodes, then that's a different story. That said, is there significant global state in this benchmark that would be affected by cross-NUMA memory access?

We should be tracking NUMA and non-NUMA many-core scaling as distinct topics.

**Comment by EgorBo** [comment]
Btw, a cool read which is related - https://thenewstack.io/internode-cache-thrashing-hunting-a-numa-performance-bug/ 🙂

**Comment by richlander** [comment]
Nice! That's an awesome write-up. The final result (and the culprit) makes total sense. You knew it had to be something like that.

**Comment by kouvel** [comment]
The 80-core machine above has one NUMA node, so there are likely scaling issues separate from NUMA as well.

**Comment by richlander** [comment]
> If I am not mistaken, that 80core CPU consists of 4 NUMA node

Just so we're on the same page, that assertion is the incorrect. I would have been a bit surprised if there was an 80 core machine with (presumably) 20 cores per NUMA. Maybe that's a configuration somewhere but it seems like it would be very niche.

**Comment by EgorBo** [comment]
Ah, sorry, I made that conclusion from the article where they also work with a 80-core Ampere with 4 nodes.

@kouvel @richlander it turns out most benchmark are scaled more or less fine between 24-cores to 80-cores according to the 2nd page of https://aka.ms/aspnet/benchmarks

It's json-json benchmark looks problematic, only +15% for extra 56 cores. native traces say that on 80 cores we spend more time inside SpinWait cc @kouvel 

![image](https://user-images.githubusercontent.com/523221/177343536-4ab1f9a8-5d08-4fcb-a57b-769464626de3.png)
