### ISSUE TITLE
Intrinsics parity with x64 for Arm64

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#70533]
# Summary
For HW intrinsics enablement, we achieved parity with x64 in .NET 5 for most intrinsics except for multi-register intrinsics. For example, x64 enabled MULX. Enable the multi-register intrinsics support for Arm64. 

## What Success Looks Like (include a metric if possible) 
* Microbenchmarks performance analysis to show performance benefit. 

## Customer Development Needs
- Advertise the feature to the community.

## User Stories under this Epic include: 
- [x] https://github.com/dotnet/runtime/issues/70531
- [x] https://github.com/dotnet/runtime/issues/70532

**Comment by dakersnar** [comment]
Everything planned here for 7.0 has been completed, with the exception of the details in https://github.com/dotnet/runtime/issues/63331 that were moved out to 8.0.
