### ISSUE TITLE
Dotnet 6.x looks weird if I see screen_number of X11 - I think that DLLImport has problem...

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/runtime#70623]
### Description

Hello everyone

Linux [X}
Windows
MacOS
WASM 
ANDROID 

I found bug like it looks crazy. If you write in C++/C and result of printf shows example:
```
screen_number = XDefaultScreen(display);
if (screen_number == -1)
{
	printf("Error: passing default screen number!\n");
}
else
{
	printf("Success: default screen number passed %i!\n", screen_number);
}
```
Result:
![image](https://user-images.githubusercontent.com/57066679/173207768-5df94013-af37-455b-8b64-d6116952deb4.png)

I try to C# but it seems weird because it doesn't like same 1:1 just 1:meshed
Why does C# not work same to C++/C - I thought C# is faster then C++/C but for X11 via DLLImport
Example:
```
int screen_number = DefaultScreen(display);
if (screen_number == -1)
{
    Console.WriteLine("Error: passing default screen number!\n");
}
else
{
    Console.WriteLine("Screen Number is " + screen_number);
}
```
Result:
![image](https://user-images.githubusercontent.com/57066679/173207829-265fe71e-25f1-446f-8585-f5794b298e16.png)

I have tried to resolve. No success....

### Reproduction Steps

Problem with wrong number of Screen Number from X11

### Expected behavior

For C++/C shows correct number of screen_number with X11's DefaultScreen()

### Actual behavior

Only C++/C looks successfully
With C++/C programming is very impressive then C#

### Regression?

No..

### Known Workarounds

Workaround with C++/C = success
But C# looks weird like C# makes crazy.

### Configuration

LINUX , Dotnet 6.x latest version

### Other information

With C++/C and C# should be same....

**Comment by Wraith2** [comment]
Can you provide the complete code for your c# program please?

**Comment by DeafMan1983** [comment]
@Wraith2 
My complete Program.cs
```
using System.Runtime.InteropServices;
using System.Text;

namespace Example;

unsafe class Program
{
    public static int UTF8Size(string name)
    {
        if (name == null)
        {
            return 0;
        }
        return (name.Length *4) + 1;
    }

    public static byte *UTF8ToString(string name, byte *data, int size)
    {
        if (name == null)
        {
            return (byte*) 0;
        }

        fixed (char *name_ptr = name)
        {
            Encoding.UTF8.GetBytes(name_ptr, name.Length + 1, data, size);
        }

        return data;
    }

    public static string UTF8FromBytePointer(byte *pointer)
    {
        byte *ptr = pointer;
        while (*ptr != 0)
        {
            ptr++;
        }

        return Encoding.UTF8.GetString(pointer, (int)(ptr - pointer));
    }

    const string libX11 = "libX11.so.6";

    [StructLayout(LayoutKind.Sequential)]
    public struct Display
    {
    }

    [DllImport(libX11, CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr XOpenDisplay(byte* display_name);
    public static Display OpenDisplay(string display_name)
    {
        IntPtr ret = Marshal.AllocHGlobal(Marshal.SizeOf<Display>());
        int display_name_size = UTF8Size(display_name);
        byte* display_name_data = stackalloc byte[display_name_size];
        ret = XOpenDisplay(UTF8ToString(display_name, display_name_data, display_name_size));
        return Marshal.PtrToStructure<Display>(ret);
    }

    [DllImport(libX11, CallingConvention = CallingConvention.Cdecl)]
    private static extern void XCloseDisplay(IntPtr display);
    public static void CloseDIsplay(Display display)
    {
        IntPtr ret = Marshal.AllocHGlobal(Marshal.SizeOf<Display>());
        Marshal.StructureToPtr<Display>(display, ret, false);
        if (ret != IntPtr.Zero)
        {
            XCloseDisplay(ret);
        }
    }

    [DllImport(libX11, CallingConvention = CallingConvention.Cdecl)]
    private static extern int XDefaultScreen(IntPtr display);
    public static int DefaultScreen(Display display)
    {
        IntPtr ret = Marshal.AllocHGlobal(Marshal.SizeOf<Display>());
        Marshal.StructureToPtr<Display>(display, ret, false);
        return XDefaultScreen(ret);
    }

    static void Main(string[] args)
    {
        Display display = OpenDisplay(string.Empty);
        IntPtr disPtr = Marshal.AllocHGlobal(Marshal.SizeOf<Display>());
        Marshal.StructureToPtr<Display>(display, disPtr, false);

        if (disPtr == IntPtr.Zero)
        {
            Console.WriteLine("Error: opening display!\n");
        }
        else
        {
            Console.WriteLine("Success Display opened.\n");

            int screen_number = DefaultScreen(display);
            if (screen_number == -1)
            {
                Console.WriteLine("Error: passing default screen number!\n");
            }
            else
            {
                Console.WriteLine("Screen Number is " + screen_number);
            }
        }

        CloseDIsplay(display);
        Console.WriteLine("Success: Display closed.\n");
    }
}
```
And type `dotnet restore && dotnet run -c Release`
Then result looks wrong....
in C++/C main.cpp looks like same but I tried
```
#include <X11/Xlib.h>
#include <iostream>

bool Initialize();
void Destroy();

Display *display;
int screen_number;

int main()
{
	if (!Initialize())
	{
		printf("Error initializing!\n");
	}
	else
	{
		printf("Success!\n");
	}
	
	Destroy();
	return 0;
}

bool Initialize()
{
	display = XOpenDisplay((char*)0);
	if (!display)
	{
		printf("Error: opening display!\n");
	}
	else
	{
		screen_number = XDefaultScreen(display);
		if (screen_number == -1)
		{
			printf("Error: passing default screen number!\n");
		}
		else
		{
			printf("Success: default screen number passed %i!\n", screen_number);
		}

	}

	return true;
}

void Destroy()
{
	if (display != NULL)
	{
		XCloseDisplay(display);
	}
}
```
And you should type in terminal:
`g++ main.cpp -o myapp -lX11 -no-pie`

It shows for test with screen number from C# and C++/C. If you expect that why does C# not same to C++/C for result 1:1 like example screen number passed "0" but C# shows wrong or impossible.

**Comment by huoyaoyuan** [comment]
The way you define P/Invoke is wrong. You allocate new memory, and copy the content of `struct Display` which is totally nothing to it. You must pass the original pointer returned by P/Invoke.

In other words, don't use the `Marshal` class at all. You won't need it.

**Comment by huoyaoyuan** [comment]
Some additional sample snippet:
```csharp

        [DllImport(libX11, CallingConvention = CallingConvention.Cdecl)]
        public static extern SafeXDisplayHandle XOpenDisplay([MarshalAs(UnmanagedType.LPUTF8Str)] string displayName);

        [DllImport(libX11, CallingConvention = CallingConvention.Cdecl)]
        public static extern void XCloseDisplay(IntPtr display);

    class SafeXDisplayHandle : SafeHandle
    {
        protected override bool ReleaseHandle()
        {
            Program.XCloseDisplay(handle);
            return true;
        }
    }
```

**Comment by DeafMan1983** [comment]
Wait what is SafeHandle? What is best way with GCHandle, SafeHandle or Marshal?

I don't know about SafeHandle? Can you explain me about 3 different ways on C# with underdery to P/Invokes and converting structures? If I know about Marshalling but it looks weird. Thanks!

**Comment by huoyaoyuan** [comment]
> Wait what is SafeHandle? What is best way with GCHandle, SafeHandle or Marshal?

`GCHandle` is totally unrelated with P/Invoke.
`SafeHandle` is just simply a wrapper of `IntPtr`, and calls `Release` exactly once for you. You won't be worry about when to release. If you need to explicitly release it, just call `Dispose`, and release will not be called any more.
`Marshal` is something old in .NET Framework 1.x or 2.x era. New code should not need to use it totally.

> Can you explain me about 3 different ways on C# with underdery to P/Invokes and converting structures? If I know about Marshalling but it looks weird. Thanks!

The best way is...don't *marshal* or convert it. Define a struct with exact members, and pass it as reference. Sample: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.SECURITY_ATTRIBUTES.cs
https://github.com/dotnet/runtime/blob/main/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateFile.cs

In your case, the native code returns an opaque pointer to it. **The pointer itself is being used, not the content it's pointed to.** You can use any "marshaling" to inspect the memory it points to, but must keep the pointer itself, not a pointer to copies of its "contents".

**Comment by DeafMan1983** [comment]
@huoyaoyuan okay I understand now. thanks for explanation!

But Silk.NET said like GLFW's Window is pointer also WindowHandle is as real pointer for C# like this `WindowHandle *winhandle = GLFW3.CreateWindow(...);`

And Java Native Access shows me like Display, Screen and other pointers are real pointer and Atom, Colormap, Drawable, Pixmap and Window are typedef XID as unsigned long. I thought and in C# I have found nint and nuint like Silk.NET made why do they make?
But I don't understand why do they use with old marshalling way? Like XSharp by Andrew shows me XHandle as DisposeHandle
Example I made:
```
using System.Runtime.InteropServices;

namespace Example;

public abstract class DisposeHandle : IDisposable
{
    private IntPtr handle;
    public DisposeHandle(IntPtr handle)
    {
        this.handle = handle;
    }

    public IntPtr Handle
    {
        get
        {
            return handle;
        }
        set
        {
            handle = value;
        }
    }

    public virtual void Dispose()
    {
        if (handle != IntPtr.Zero)
        {
            handle = IntPtr.Zero;
        }
    }
}
```
Is it valid like SafeHandle or normal handle, correctly?

Then I create instance of DisposeHandle for example:
```
public class Display : DisposeHandle
{
    public Display(intPtr handle) : base(handle)
    {
    }
}
```
Is it real class with handling with IntPtr? Is it safe? Thanks for explanation! Can I close it?

**Comment by huoyaoyuan** [comment]
In supplement of my previous explanation, **handles** are about object identity, while **marshaling** is about copying object content. `GCHandle` is also used to pass managed object identity to unmanaged code.

> But Silk.NET said like GLFW's Window is pointer also WindowHandle is as real pointer for C# like this `WindowHandle *winhandle = GLFW3.CreateWindow(...);`

Yes, you can declare it as a pointer, like `IntPtr`. You can also cast between them.
In this case, there may be no information about the data layout at destination of the pointer, so declaring as a pointer won't give you more usage.

> Is it valid like SafeHandle or normal handle, correctly?

It is valid, but it's not as "safe" as `SafeHandle`. .NET Runtime supports additional features for `SafeHandle`:
- Exact once `Release`, no double-free problem
- `SafeHandle` can be directly used in P/Invoke method, and P/Invoke infrastructure will extract its underlying `IntPtr` and pass it to unmanaged code.
- When the handle is currently used by a P/Invoke method, prevent it from accidentally released.

**Comment by AaronRobinsonMSFT** [comment]
@DeafMan1983 As @huoyaoyuan has mentioned it seems the DllImport usage is slightly off. There is a large corpus of guidance on this subject officially at https://docs.microsoft.com/dotnet/standard/native-interop/. It has been ages since I worked with X11 APIs and don't recall much, so if help is needed writing a P/Invoke signature providing the C API prototype is the best way to get help.

**Comment by tannergooding** [comment]
[TerraFX.Interop.Xlib](https://github.com/terrafx/terrafx.interop.xlib) provides raw/blittable interop bindings for Xlib that are generated directly from the underlying C headers using [dotnet/ClangSharp](https://github.com/dotnet/clangsharp)

You can see the P/Invoke binding for `XDefaultScreen` here: https://source.terrafx.dev/#TerraFX.Interop.Xlib/X11/Xlib/Xlib.cs,00dc5c4648e5207c
```csharp
[DllImport("libX11", ExactSpelling = true)]
public static extern int XDefaultScreen(Display* param0);
```

The library also provides a `DllImportResolver` (https://source.terrafx.dev/#TerraFX.Interop.Xlib/Xlib.cs) to help look up the other well-known library names and to allow users to customize that resolution themselves as well.

**Comment by DeafMan1983** [comment]
@teeram wow why do XID port Int32(or int) from Window, Atom, Colormap or other XID's typedefs.... 

Thank you for explanation. I will try out. PS faked structures Window, Colormap as structures? hmmmm that is not fair ...

I don't understand because I have checked Window.cs with funny implicit operators with void* How did TerraFX cheat typedef XID as structures? It is really impossible. But for me my XLib uses class with abstract XID_Handle.cs over Drawable.cs like XSharp made.

**Comment by tannergooding** [comment]
> How did TerraFX cheat typedef XID as structures? It is really impossible.

ClangSharp understands the underlying calling convention and limitations for various platforms. It ensures that the exposed signature is typesafe and the underlying P/Invoke is correct. If required it generates a small wrapper stub to handle the necessarily translation in a zero-cost (or as near to zero as possible) manner.

In the case of `XID`, not all Xlib IDs are compatible or interchangeable. Utilizing these minimal wrapper types therefore helps avoid accidental misuse while still ensuring the data is blittable and correct.

> PS faked structures Window, Colormap as structures? hmmmm that is not fair ...

Many of these have actual underlying structs defined in the header, its just often hidden via typedefs and similar. ClangSharp takes care of ensuring the bindings are 1-to-1 and that the definitions between various implementations (Linux, MacOS, etc) are consistent.

**Comment by DeafMan1983** [comment]
@tannergooding Thank you for explanation! I will continue my work! Thank you for saving my development!
