### ISSUE TITLE
Unnecessary instructions produced for records.

### ISSUE THREAD

**Issue by OMGtechy** [dotnet/runtime#70625]
### Description

I was learning about C# records and wondered what the resulting disassembly would look like. To investigate this, I used [godbolt](https://godbolt.org/z/K1rb7vWE1). In the linked example, I got different results for multiplication depending on whether I used a field vs. a property. They should be functionally equivalent. They are not for multiplication, they are for incrementing.

### Reproduction Steps

```csharp
public record FieldExample
{
    public readonly int value;
}

public record PropertyExample
{
    public int Value { get; }
}

public record TerseExample(int Value);

class Program
{
    static int Square(FieldExample n) => n.value * n.value;
    static int Square(PropertyExample n) => n.Value * n.Value;
    static int Square(TerseExample n) => n.Value * n.Value;
    static int Square(int n) => n * n;
    static int Inc(FieldExample n) => n.value + 1;
    static int Inc(PropertyExample n) => n.Value + 1;
    static int Inc(TerseExample n) => n.Value + 1;
    static int Inc(int n) => n + 1;
}
```

The important snippet in the disassembly for this:
```asm
Program:Inc(int):int:
       lea      eax, [rdi+1]
       ret      

Program:Inc(TerseExample):int:
       mov      eax, dword ptr [rdi+8]
       inc      eax
       ret      

Program:Inc(PropertyExample):int:
       mov      eax, dword ptr [rdi+8]
       inc      eax
       ret      

Program:Inc(FieldExample):int:
       mov      eax, dword ptr [rdi+8]
       inc      eax
       ret      

Program:Square(int):int:
       mov      eax, edi
       imul     eax, edi
       ret      

Program:Square(TerseExample):int:
       mov      eax, dword ptr [rdi+8]
       mov      edi, eax
       imul     eax, edi
       ret      

Program:Square(PropertyExample):int:
       mov      eax, dword ptr [rdi+8]
       mov      edi, eax
       imul     eax, edi
       ret      

Program:Square(FieldExample):int:
       mov      eax, dword ptr [rdi+8]
       imul     eax, eax
       ret     
```

### Expected behavior

`Square(FieldExample)` and `Square(PropertyExample)` should yield the same disassembly.

### Actual behavior

```asm
Program:Square(PropertyExample):int:
       mov      eax, dword ptr [rdi+8]
       mov      edi, eax
       imul     eax, edi
       ret      

Program:Square(FieldExample):int:
       mov      eax, dword ptr [rdi+8]
       imul     eax, eax
       ret     
```
There's an unnecessary `mov` for `Square(PropertyExample)`.

### Regression?

Don't know.

### Known Workarounds

Use the field example.

### Configuration

https://godbolt.org/z/K1rb7vWE1

### Other information

I tried benchmarking this, but didn't get any statistically significant difference in performance. It just seems likely some low-hanging fruit - there's no reason for that `mov` regardless of performance.

**Comment by EgorBo** [comment]
I checked this locally and codegen looks fine to me for .NET 7.0 no redundant movs. godbolt uses .NET 6.0

PS: records are classes so they're passed as managed reference (in case if you expected them to be structs and passed by value in a single register)

**Comment by OMGtechy** [comment]
Thanks! Does the issue reproduce for you in .NET 6 @EgorBo ? If so, we can consider this already fixed - if not, there’s another variable to be tied down somewhere.

**Comment by EgorBo** [comment]
> Thanks! Does the issue reproduce for you in .NET 6 @EgorBo ? If so, we can consider this already fixed - if not, there’s another variable to be tied down somewhere.

Yes it does - https://sharplab.io/#v2:C4LghgzgtgPgAgZgAQCcCmBjA9igJkgMQEs0AbXAUQA8woAHUtAWACgBvVpLpRVNMXFgB2pAJ5IiQ4EgBuYUgFc0AblYBfVq17pseJAAUUWOmhTBR1Wg2btO3XpOkA1eUqRskAczTBlSDSwBWsg6OPgAKqYQaJb0jAAUjkguimgAlKosWgBMPACMAOysHCzc+QBsElJIAMoAjgpg6PHEZJQ0cWhIQmlIALwAfN0AdHKpSABUI2NKmWVweZVJ9Y3Nhsam5rHW3b2DIyluU0LDhyp2XAtL1StNaPGRKNHbjLv9Qydnkweu56X2iyq0luzSSPXe3W+QjmAOu0gAkkIMC0SOQXl1wfsTjMugBqJB5GGXQFJRHI9YmMwWDo7TEfU6/JD4wkXCpApBkh5RGI0150n7jZlEtmkpGJar8oRMgmZNRAA=

Thanks!
