### ISSUE TITLE
Some CNG types no longer warn or throw PNSE in .NET 7

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#70637]
After the unification of System.Security.Cryptography.Cng in to S.S.Cryptograhy, some CNG types no longer give warning that they are Windows only.

In .NET 6, the whole assembly generates a platform not supported exception:

https://github.com/dotnet/runtime/blob/2ecbdbb56d20af911e854e94515057492ecf2cba/src/libraries/System.Security.Cryptography.Cng/src/System.Security.Cryptography.Cng.csproj#L8-L10

In .NET 7, this does not happen for some types, like `CngAlgorithm`. On macOS, this compiles without warning and even runs:

```C#
using System.Security.Cryptography;

CngAlgorithm alg = CngAlgorithm.ECDsaP256;
```

Running is not surprising, after all this class is just a strongly-typed string enumeration.

For other types like `AesCng`, the compiler warnings and PNSE remain functional.

So, even though this type is "fine" on non-windows platforms, I'm uncertain if this was intentional or if we want to preserve all of the `SupportedOSPlatform` on _all_ CNG types, even if they can technically function on non-Windows.

**Comment by bartonjs** [comment]
When I merged the assemblies I only painted the things that actually needed explicit PNSE implementations on non-Windows.  I didn't see any value in making (e.g.) CngAlgorithm be marked as OS-specific

**Comment by vcsjones** [comment]
Since it was intentional then I will close this out. Thanks!
