### ISSUE TITLE
Signlar 1006 error on win 2016 server when message size incresed

### ISSUE THREAD

**Issue by pranayrana** [dotnet/runtime#70647]
### Description

[](url)I already reported issue : https://github.com/dotnet/aspnetcore/issues/41675

Singlar implemented with .net core + angular working fine on Win 10 machine with big message size.
But its not working on win 2016 server when message size get increased , it gives 1006 error.

tried below , but none of below is working

services.AddSignalR(o => {
o.EnableDetailedErrors = true;
o.MaximumReceiveMessageSize = null;
});

and
set
ApplicationMaxBufferSize=0
TransportMaxBufferSize =0

can anyone help with it, and want to know , can this issue of message size limit cause by [server] ?

[angular client.txt](https://github.com/dotnet/runtime/files/8888808/angular.client.txt)
[asp.net hub.txt](https://github.com/dotnet/runtime/files/8888809/asp.net.hub.txt)

Please find attached file to reproduce issue.

### Reproduction Steps

Attached file to reproduce issue on 2016 server

### Expected behavior

it should send message of any size

### Actual behavior

1006 error at client side and no log generated for it (message size more than 243kb gives error)

### Configuration

.net core - 5

**Comment by huoyaoyuan** [comment]
As #70646, there seems nothing to do with runtime repo.

**Comment by pranayrana** [comment]
> As #70646, there seems nothing to do with runtime repo.

So what could be wrong because my code works fine on win 2010 but it start giving error 1006 when get deployed to 2016 server

**Comment by pranayrana** [comment]
> @pranayrana this appears to be the same as the issue you already opened. And in that issue they asked for logs from you. I’ll close this as duplicate.

Hi,

There is no log generated in trace i see connection and disconnection only , but log is not providing any information about why it get disconnected. 

For that purpose i attached my code files also.

**Comment by danmoseley** [comment]
Please continue the conversation on the original bug you opened

**Comment by pranayrana** [comment]
ok
I though it got closed thats why i created new one

thanks
