### ISSUE TITLE
Signlar 1006 error on win 2016 server when message size incresed

### ISSUE THREAD

**Issue by pranayrana** [dotnet/runtime#70646]
### Description

I already reported issue : https://github.com/dotnet/aspnetcore/issues/41675

Singlar implemented with .net core + angular working fine on Win 10 machine with big message size.
But its not working on win 2016 server when message size get increased , it gives 1006 error.

tried below , but none of below is working

services.AddSignalR(o => {
o.EnableDetailedErrors = true;
o.MaximumReceiveMessageSize = null;
});

and
set
ApplicationMaxBufferSize=0
TransportMaxBufferSize =0

can anyone help with it, and want to know , can this issue of message size limit cause by server ?

[angular client.txt](https://github.com/dotnet/runtime/files/8888291/angular.client.txt)
[asp.net hub.txt](https://github.com/dotnet/runtime/files/8888292/asp.net.hub.txt)

Please find attached file to reproduce issue. 

### Reproduction Steps

Attached file to reproduce issue on 2016 server 

### Expected behavior

it should send message of any size 

### Actual behavior

1006 error at client side and no log generated for it (message size more than 243kb gives error)

### Other information

.net core - 5

**Comment by davidfowl** [comment]
Not sure why you opened this on the runtime repo
