### ISSUE TITLE
clang 12 - no input files [Android NDK]

### ISSUE THREAD

**Issue by Rugau** [dotnet/runtime#70640]
### Description

I cant compile for Android ARM64 Shared library.

### Reproduction Steps

export ndk path and find clang.exe

run:

dotnet publish -r android-arm64 -c Release -p:CppCompilerAndLinker=aarch64-linux-android31-clang /p:NativeLib=Shared /p:SelfContained=true

### Expected behavior

works?

### Actual behavior

Returns a error:

clang-12 : error : no input files [/mnt/c/wtf/nativelibrary/NativeLibrary.csproj]
/root/.nuget/packages/microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/build/Microsoft.NETCore.Native.targets(374,5): error MSB3073: The command "aarch64-linux-android31-clang "obj/Release/net6.0/android-arm64/native/NativeLibrary.o" -o "bin/Release/net6.0/android-arm64/native/NativeLibrary.so" -Wl,--version-script=obj/Release/net6.0/android-arm64/native/NativeLibrary.exports /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/sdk/libbootstrapperdll.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/sdk/libRuntime.WorkstationGC.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/framework/libSystem.Native.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/framework/libSystem.Globalization.Native.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/framework/libSystem.IO.Compression.Native.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/framework/libSystem.Net.Security.Native.a /root/.nuget/packages/runtime.linux-arm64.microsoft.dotnet.ilcompiler/7.0.0-alpha.1.22074.1/framework/libSystem.Security.Cryptography.Native.OpenSsl.a --target=aarch64-linux-gnu -g -Wl,-rpath,'$ORIGIN' -Wl,--as-needed -pthread -lstdc++ -ldl -lm -lz -lgssapi_krb5 -lrt -shared -Wl,-z,relro -Wl,-z,now -Wl,--require-defined,CoreRT_StaticInitialization -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/mnt/c/wtf/nativelibrary/NativeLibrary.csproj]

(its only ocorrur if use Shared library. Static works fine)

### Configuration

Windows 11
WSL2
Android NDK 23

**Comment by MichalStrehovsky** [comment]
> (its only ocorrur if use Shared library. Static works fine)

Because of how NuGet fallbacks work, you're likely getting the ARM64-Linux binary. It may or may not work. We don't have a build for the Android RID.

#63384 tracks Android build support. I'll close this in favor of that issue.
