### ISSUE TITLE
ProcessStartInfo wraps quotes arround my `--option=`

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/runtime#70659]
### Description

I want to use `ArgumentList.Add` to safely add arguments in a secure way but it wraps double quotes around the entire string even when it is an key–value pair option.

### Reproduction Steps

```cs
using System.Diagnostics;

var info = new ProcessStartInfo("cmd");
info.UseShellExecute = false;
info.ArgumentList.Add("/C");
info.ArgumentList.Add("echo");
info.ArgumentList.Add("--author=Alice Smith");
Process.Start(info);
```

### Expected behavior

    --author="Alice Smith"

### Actual behavior

    "--author=Alice Smith"

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6
```

**Comment by AaronRobinsonMSFT** [comment]
This is a tough issue. Should the argument parser special case if it finds "="? This is happening in

https://github.com/dotnet/runtime/blob/15f1e1d5e83d8ab76ab605624ef0cdd004229032/src/libraries/System.Private.CoreLib/src/System/PasteArguments.cs#L30-L78

**Comment by tmds** [comment]
> info.ArgumentList

An argument that is added here ends up as an item in the array of program arguments. For .NET that is `args` of `static void Main(string[] args)`.

When you write `cmd /C echo --hello=foo bar`, your shell treats `--hello=foo` and `bar` as separate arguments.
When you use `ArgumentList` you must do the same:

```
info.ArgumentList.Add("--hello=foo");
info.ArgumentList.Add("bar");
```

.NET can't know it should do something special with `--hello=foo bar`. The program `args` gets fed into a library like https://github.com/dotnet/command-line-api which causes these two `args` arguments to become a single 'logical' argument `hello` that has a value `foo bar`.

**Comment by vanillajonathan** [comment]
But if I want to specify an option that takes a string containing spaces, should I escape the quotes with backslashes like this?

```cs
info.ArgumentList.Add("--author=\"Alice Smith\"");
```

**Comment by tmds** [comment]
> info.ArgumentList.Add("--author=\"Alice Smith\"");

When a shell parses a command line it uses white space as separator for arguments and you need to add quotes if you want some whitespace to become part of an argument.

Here we're not parsing anything, you can just add the whitespace without adding quotes and it will still be a single argument:

```
info.ArgumentList.Add("--author=Alice Smith");
```

**Comment by tmds** [comment]
You see this with a program like:
```cs
for (int i = 0; i < args.Length; i++)
{
    Console.WriteLine($"[{i}]: {args[i]}");
}
```
```
$ dotnet run -- --author="Alice Smith"

[0]: --author=Alice Smith
```
The shell need quotes because that's the way it understand `--author=Alice Smith` needs to be a treated as a single argument.

.NET doesn't need those quotes, anything added to `ArgumentList` is a single argument.
