### ISSUE TITLE
[mono] iOS - Size reduction: _mono_aot_corelib_eh_frame is twice is large on .NET 6 compared to legacy mono

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#70679]
While investigating the [.NET 6: SingleView app size](https://github.com/xamarin/xamarin-macios/issues/10249) it has been noticed that:
`_mono_aot_corelib_eh_frame` is twice as large compared to `_mono_aot_mscorlib_eh_frame` when comparing:

- dotnet - version`6.0.301-rtm.22263.15` and
- legacy mono - version `6.12.0` 

builds of `MySingleView` app on iOS.

This can be observed in the reports generated by using [bloaty](https://github.com/google/bloaty) showing `MySingleView` native output breakdown (divided into segments/sections/symbols): 

- [MySingleView_dotnet6_mono](https://gist.github.com/ivanpovazan/b72f5e6da5e24a98be192675359da6d5)
- [MySingleView_legacy_mono](https://gist.github.com/ivanpovazan/507356a9a7cfada8e84a9420319bbecd)

**Comment by ivanpovazan** [comment]
@lambdageek @vargaz @BrzVlad
Do you maybe have some input on why the code size of exception handling has increased twice in size?
And possibly where I could start investigating?
Any help is much appreciated.

**Comment by vargaz** [comment]
```
ag ' _mscorlib_' gistfile1.txt  | wc -l
    4266
ag ' _corlib_' gistfile1.txt.1 | wc -l 
    7260
```
So the new corlib has way more methods than the old one.

**Comment by ivanpovazan** [comment]
Closing this issue since the size of `_mono_aot_corelib_eh_frame` is in direct correlation with the number of the emitted symbols. The number of emitted symbols is tracked in a separate issue.
