### ISSUE TITLE
Core 6.0 HttpClient throwing timeout exception 

### ISSUE THREAD

**Issue by manoj-singh** [dotnet/runtime#70691]
### Description

HttpClient throwing time out exception while trying to fetch information from CMDB/Service-now from Asp.net core Blazor application but on he same machine and same code working in console application.

### Reproduction Steps

Call CMDB API using get HttpClient, It throw timeout exception. I have set timeout to 20 min but no luck.

### Expected behavior

It should return a string in response 

### Actual behavior

It is throwing timeout exception

**Comment by wfurt** [comment]
This is not actionable @manoj-singh. Can you provide repro code or specific steps? 
I also suggest to do packet capture to see what is happening on the network.

**Comment by manoj-singh** [comment]
I am trying to connect to Service now API using HttpClient in Razor web application. I am getting HttpClient instance from dependancy injection of IHttpClientFactory (httpClientFactory.CreateClient()). I am providing all the authorization correctly as it work on my local machine but not working on Server Environment. As I have mention earlier same code in core console app is working. Here is code I wrote

              
              Uri snUri = new Uri("https://abcd.service-now.com/api/now/v2/table/cmdb_ci_business_app?&name=" + AppName);
                HttpClient hc = _httpClientFactory.CreateClient();
                
                var byteArray = new UTF8Encoding().GetBytes(CMDBUserName + ":" + CMDBPassword);
                hc.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));
                HttpResponseMessage res = await hc.GetAsync(snUri);
                if (res.IsSuccessStatusCode)
                {
                    response.RawJSON = await res.Content.ReadAsStringAsync();
                    RESTQueryResponse<T> tmp = JsonConvert.DeserializeObject<RESTQueryResponse<T>>(response.RawJSON);
                    if (tmp != null && tmp.Result != null && tmp.Result.Count > 0) { response.Result = tmp.Result; }
                    if (tmp == null || tmp.Result == null || tmp.Result.Count == 0)
                    {
                        response.ErrorMsg = "Application not exist in CMDB";
                    }
                }
                else
                {
                    response.ErrorMsg = await res.Content.ReadAsStringAsync();
                }

Here is exception I am getting:- An error occured retrieving the Application detail: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

                
Please let me know in case you need anything else to troubleshoot this issue.

**Comment by wfurt** [comment]
It is not cursor what you looking at @manoj-singh. I would certainly check firewall and check if the site is reachable via some other tools - like Edge browser. At the same time check that you get proper capture - Wireshark is probably best tool to use.

**Comment by manoj-singh** [comment]
I am checking firewall and other setting(s) on server....

**Comment by manoj-singh** [comment]
Thank you, in my investigation I found that there was proxy issue....
