### ISSUE TITLE
NativeAOT compiler doesn't check for RequiresUnreferencedCode for methods accessed only through reflection

### ISSUE THREAD

**Issue by tlakollo** [dotnet/runtime#70698]
### Description

In some instances, the NativeAOT compiler won't produce a warning when accessing methods annotated with Requires when accessed via reflection. See reproduction steps

### Reproduction Steps

```C#
// Missing warning being generated
// [ExpectedWarning ("IL2026", "--RequiresOnlyThroughReflection--")]
public static void Main ()
{
	typeof (RequiresAccessedThrough)
		.GetMethod ("RequiresOnlyThroughReflection", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic)
		.Invoke (null, new object[0]);
}

class RequiresAccessedThrough
{
	[RequiresUnreferencedCode ("Message for --RequiresOnlyThroughReflection--")]
	static void RequiresOnlyThroughReflection ()
	{
	}
}
```

### Expected behavior

A warning should be generated when trying to access the method via reflection

### Actual behavior

A warning is not generated

**Comment by MichalPetryka** [comment]
I think that NativeAOT can notice a member being invoked like this and handle it without warning.

**Comment by hez2010** [comment]
In your case `RequiresOnlyThroughReflection` can be statically analyzed by compiler and won't cause missing metadata issue, so the warning is unnecessary.

**Comment by tlakollo** [comment]
The Requires attribute instructs the NativeAOT compiler to generate a warning every time a member is being accessed independently of the fact that there is any reason for doing it. See for example the [simple call to a method annotated with Requires](https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/Mono.Linker.Tests.Cases/RequiresCapability/BasicRequires.cs#L38-L44) 
In this case NativeAOT should also be able to understand the member being accessed, read its attributes, and generate a warning. Note: This is a failing [test from a port from dotnet/linker](https://github.com/dotnet/linker/blob/main/test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresAccessedThrough.cs#L42-L48)  that does not work correctly in NativeAOT

**Comment by tlakollo** [comment]
Closed via https://github.com/dotnet/runtime/pull/72496
