### ISSUE TITLE
Plaintext benchmark regressed recently

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#70714]
![image](https://user-images.githubusercontent.com/523221/173538510-e358331f-acb1-4e57-b6a1-7982c1e61a1e.png)

Wonder what caused that excessive memory consumption

**Comment by EgorBo** [comment]
Runtime changes: https://github.com/dotnet/runtime/compare/6c7d935...117d31a
aspnet changes: https://github.com/dotnet/aspnetcore/compare/885cffd...ae281e9

**Comment by EgorBo** [comment]
cc @sebastienros in case if there were any expected changes to that benchmark

**Comment by sebastienros** [comment]
Tracked, known, understood, will fix. I changed the benchmark itself to add a scenario on query string perf improvements and added it impacted the common path even when the query string is empty.

**Comment by stephentoub** [comment]
> Tracked, known, understood, will fix.

Closing this issue then. Thanks.
