### ISSUE TITLE
Cannot PublishReadyToRun as Visual Studio Passing too Many Arguments to Crossgen2.exe 

### ISSUE THREAD

**Issue by lzl1918** [dotnet/runtime#70712]
### Description

We have a C# project with `TFM=net6.0-windows10.0.19041;UseWPF=true`

When publishing the project with `PublishReadyToRun=true;SelfContained=true`, Visual Studio tries to invoke the `crossgen2.exe` passing quite a lot .dlls as reference files.

The command length on my build machine is 33317, which is far beyond the limitation for [Windows command line limitation](https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation).

A script is showing the command line as follows:
[invoke_crossgen.ps1.txt](https://github.com/dotnet/runtime/files/8897412/invoke_crossgen.ps1.txt)

Wondering if `crossgen2` supports providing any text file that lists all reference files.
And if so, how to work with Visual Studio to have the project successfully published.

### Reproduction Steps

1. Set up a project with the mentioned settings above.
2. Publish the created project.
3. Check Visual Studio build output.

### Expected behavior

Publish succeeded.

### Actual behavior

Publish failed with output "Optimizing assemblies for performance failed".

**Comment by lzl1918** [comment]
> Looks like invoke_crossgen.ps1 is not part of runtime or SDK, but something mantained by the VS team?
No. This file is attached to show people the command line Visual Studio generates and tries to invoke.

Does Visual Studio generates an rsp file and passes it to crossgen2?
It seems it is not a behavior by default, is it?

**Comment by trylek** [comment]
I think this is not a matter of VS per se, I believe it should be using the .NET SDK to launch Crossgen2 so it's on our end to fix by modifying the SDK code to emit a response file instead. @AntonLapounov, please correct me if I'm wrong.

**Comment by am11** [comment]
CG2 task does overrides response file methods e.g. https://github.com/dotnet/runtime/blob/6896e1bb4aae0877a6cb154710b6936e4d69716e/src/tasks/Crossgen2Tasks/RunReadyToRunCompiler.cs#L258 I am not sure if VS is using the same task as dotnet cli.

**Comment by trylek** [comment]
I am convinced that there's no second implementation of the Crossgen2 command-line composition in the VS (if there was, it would need to be updated every time we've been adding new build features and / or command-line switches and I believe that wasn't happening in the last two .NET releases or so). It's either that <code>GenerateResponseFileCommands</code> should by itself store the response file somewhere and return the appropriate <code>@...</code> parameter as the actual command-line or there's some additional logic in the VS that chooses whether to use a response file or a direct command line and that is not doing the right thing. Anton is OOF sick today but hopefully he'll be back in a day or two, I think his input would be super valuable as he's done most of the Crossgen2 SDK integration work IIRC. If the actual fix is on the SDK side, it should be less than a day of work amounting to a couple of changed lines in the <code>RunReadyToRunCompiler.cs</code> source file you pointed out.

**Comment by AntonLapounov** [comment]
Visual Studio uses SDK for publishing and SDK always passes parameters to crossgen2.exe in a response file. The Build Output window does not show the actual command line, it shows the content of the response file to make build debugging easier. That means your actual issue is not related to the length of crossgen2.exe's command line. I created a new project with those settings but could not reproduce the issue.

**Comment by AntonLapounov** [comment]
If you still have the issue, please reopen with the correct description and repro steps.
