### ISSUE TITLE
LibraryImportGenerator: Use public API UnreachableException

### ISSUE THREAD

**Issue by deeprobin** [dotnet/runtime#70717]
I saw that LibraryImportGenerator contains a own UnreachableException.
https://github.com/dotnet/runtime/blob/3bb45af67b81933521f2f22745f3a9d5d3f3045c/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/UnreachableException.cs#L13-L15

I think we could replace that with the [appropriate exception](https://github.com/dotnet/runtime/blob/d34c0ff7c104b3c6e39eb17cc0d21b7ca2dc5c6d/src/libraries/System.Private.CoreLib/src/System/Diagnostics/UnreachableException.cs#L9-L10) from the S.P.CoreLib.

Any concerns?

**Comment by huoyaoyuan** [comment]
Source generator targets netstandard2.0 to be consumed by the compilers. `UnreachableException` is introduced in net7.0
