### ISSUE TITLE
System.IO.IOException : Unable to read data from the transport connection: 'overlapped' was not allocated by this ThreadPoolBoundHandle instance. (Parameter 'overlapped').

### ISSUE THREAD

**Issue by Apollo3zehn** [dotnet/runtime#70713]
### Description

I wanted to comment on #48402 but that thread is locked. I have run into a similar issue with a network stream and the reason for that was an improper implementation of my custom `MemoryManager` which throws an exception when trying to `Pin(..)`.

Sometimes I get the exception as stated in the title and sometimes I get `System.IO.IOException : Unable to read data from the transport connection: CastMemoryManager does not support pinning..
---- System.NotSupportedException : CastMemoryManager does not support pinning.`

Maybe this info helps to understand why the exception in the title sometimes occur and to solve #48402.

### Reproduction Steps

```csharp
// _dataStream is a NetworkStream ...

public Task ReadRawAsync<T>(Memory<T> buffer, CancellationToken cancellationToken)
    where T : unmanaged
{
    var memory = new CastMemoryManager<T, byte>(buffer).Memory;
    return InternalReadRawAsync(memory, _dataStream, cancellationToken);
}

private async Task InternalReadRawAsync(Memory<byte> buffer, Stream source, CancellationToken cancellationToken)
{
    while (buffer.Length > 0)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var readCount = await source.ReadAsync(buffer, cancellationToken);

        if (readCount == 0)
            throw new Exception("The TCP connection closed early.");

        buffer = buffer.Slice(readCount);
    }
}
```

```csharp
internal class CastMemoryManager<TFrom, TTo> : MemoryManager<TTo>
    where TFrom : struct
    where TTo : struct
{
    private readonly Memory<TFrom> _from;

    public CastMemoryManager(Memory<TFrom> from) => _from = from;

    public override Span<TTo> GetSpan() => MemoryMarshal.Cast<TFrom, TTo>(_from.Span);

    protected override void Dispose(bool disposing)
    {
        //
    }

    public override MemoryHandle Pin(int elementIndex = 0) => throw new NotSupportedException("CastMemoryManager does not support pinning.");

    public override void Unpin() => throw new NotSupportedException("CastMemoryManager does not support unpinning.");
}
```

### Expected behavior

There should be a more descriptive exception.

### Actual behavior

Occasionally I get 
- `System.IO.IOException : Unable to read data from the transport connection: 'overlapped' was not allocated by this ThreadPoolBoundHandle instance. (Parameter 'overlapped'). ---- System.ArgumentException : 'overlapped' was not allocated by this ThreadPoolBoundHandle instance. (Parameter 'overlapped')`, 
and other times I get
- `System.IO.IOException : Unable to read data from the transport connection: CastMemoryManager does not support pinning..
---- System.NotSupportedException : CastMemoryManager does not support pinning.`

**Comment by karelz** [comment]
Triage: @Apollo3zehn it is hard for us to guess what is going on. Do you have a fully runnable repro we could try? (ideally minimal without unnecessary code)

**Comment by karelz** [comment]
Triage: No response in 12 days, not actionable in current form, closing. Feel free to reopen if there is a repro for us to act on. Thanks!
