### ISSUE TITLE
We should flow the CancellationToken to Http2Connection.SetupAsync

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#70721]
We call `Http2Connection.SetupAsync` as part of establishing the connection here:
https://github.com/dotnet/runtime/blob/84f7cad00ad834c365b5cd1297e1166525146b50/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1567

`SetupAsync` awaits a call to `Stream.WriteAsync`, so we should flow the CT to it
https://github.com/dotnet/runtime/blob/84f7cad00ad834c365b5cd1297e1166525146b50/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L211

**Comment by MihaZupan** [comment]
The `ConnectTimeout` cancellation token.
`SetupAsync` counts as part of the connection creation for HTTP/2, so we should pass the same token to it as we do for things like the [PlaintextFilter](https://github.com/dotnet/runtime/blob/84f7cad00ad834c365b5cd1297e1166525146b50/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1562) right before it.

**Comment by stephentoub** [comment]
> The ConnectTimeout cancellation token.

Cool. As long as it's not associated with a specific request, sounds good.

**Comment by karelz** [comment]
Triage: Should be straightforward change. Let's do it in 7.0.
