### ISSUE TITLE
JsonConverter from unused JsonSerializerOptions throws for missing metadata

### ISSUE THREAD

**Issue by ovska** [dotnet/runtime#70732]
### Description

If a `JsonSerializerOptions` has not yet been used, attempting to use it to write an object to a `Utf8JsonWriter` results in a `NotSupportedException` with a misleading error message. It does not happen on built-in types such as string or int. The bug goes away after the options instance is used once with JsonSerializer, e.g. de/serializing an int.

Seems like a cache isn't populated when retrieving the converter.

### Reproduction Steps

Uncommenting line 6 "fixes" the issue
```cs
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

var options = new JsonSerializerOptions();
//_ = JsonSerializer.Serialize(0, options);
var converter = (JsonConverter<Dummy>)options.GetConverter(typeof(Dummy));
using var writer = new Utf8JsonWriter(Stream.Null);
converter.Write(writer, new Dummy { Id = 1 }, options);

public class Dummy
{
    public int Id { get; set; }
}
```

### Expected behavior

`GetConverter` should return null if it can't return a valid converter.

### Actual behavior

`Write(...)` throws an exception.

> Metadata for type 'Dummy' was not provided to the serializer. The serializer method used does not support reflection-based creation of serialization-related type metadata. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.

```
at System.Text.Json.ThrowHelper.ThrowNotSupportedException_NoMetadataForType(Type type)
at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
at System.Text.Json.Serialization.JsonResumableConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
at Program.<Main>$(String[] args) in C:\...\ConsoleApp6\ConsoleApp6\Program.cs:line 12
```

### Known Workarounds

Use the options instance once with `JsonSerializer`.

### Configuration

`dotnet --version` 6.0.300
Reproduced on x64 Windows 10 and Ubuntu 20.04, both in console application and ASP.NET Core on NET6 targetframework.

**Comment by eiriktsarpalis** [comment]
Closing as by-design behavior.

**Comment by krwq** [comment]
@eiriktsarpalis shouldn't we leave this open to track improving exception message or making sure we tested this if we decide to make this work?
