### ISSUE TITLE
DAC heapwalker doesn't detect memory corruption that makes objects appear to have zero size

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#70750]
### Description

When enumerating the GC heap with ICorDebugHeapEnum::Next the enumeration could get stuck repeatedly enumerating an object with size = 0. Because the size is zero internally the enumerator isn't advancing the pointer into heap which causes the repetition. We believe this occurs because the heap memory is corrupt, but regardless a debugging enumerator should not enter an infinite loop in the presence of bad data in a debuggee.

The likely cause is that the DAC never explicitly checks to see if the object size computed from the MethodTable is in a reasonable range:
[runtime/dacdbiimpl.cpp at 7015fa2d28e4559478807a53b5851c71d2f604e8 · dotnet/runtime (github.com)](https://github.com/dotnet/runtime/blob/7015fa2d28e4559478807a53b5851c71d2f604e8/src/coreclr/debug/daccess/dacdbiimpl.cpp#L6451)

```
bool DacHeapWalker::GetSize(TADDR tMT, size_t &size)
{
    // With heap corruption, it's entierly possible that the MethodTable
    // we get is bad.  This could cause exceptions, which we will catch
    // and return false.  This causes the heapwalker to move to the next
    // segment.
```

We should add such a check to this function.

### Reproduction Steps

There is a heap dump on an internal email that can be loaded in a debugger. I am also hypothesizing that any valid heap dump could be made to repro this issue by overwriting the size field in the MethodTable with a zero.

### Expected behavior

Enumerator skips past some range of bad objects (potentially all remaining objects) once the heap corruption is detected.

### Actual behavior

Enumerator goes into an infinite loop

### Regression?

Doesn't look like it

### Known Workarounds

The caller can detect the object size of zero and stop invoking Next() any further.

### Configuration

.NET 4.8 is where the problem reproed. Looking at the code the bug is still present in current versions of .NET, any arch or OS.

**Comment by mikem8361** [comment]
Andrew has a fix.
