### ISSUE TITLE
.NET 5 regression in Math.Min behaviour with NaNs

### ISSUE THREAD

**Issue by nojaf** [dotnet/runtime#70775]
### Description

There seems to be a regression in the behaviour of NaN handling in `Math.Min` under .NET 5 and 6.

### Reproduction Steps

var default_nan = float.NaN;
var positive_nan = -(1.0f - default_nan) / default_nan;

Console.WriteLine(Math.Min(0f, positive_nan));
Console.WriteLine(Math.Min(positive_nan, 0f));
Console.WriteLine(Math.Min(0f, default_nan));
Console.WriteLine(Math.Min(default_nan, 0f));

### Expected behavior

Output on .NET Core 3.1.26:
```
NaN
NaN
NaN
NaN
```

### Actual behavior

Output on .NET 5.0.17 and .NET 6.0.6::
```
NaN
0
NaN
NaN
```

### Regression?

This prevents us from moving from `.NET Core 3.1` to `.NET 6`.

### Configuration

`.NET Core 3.1.26`, `.NET 5.0.17` and `.NET 6.0.6`.
On Windows x64, Linux x64, macOS arm64.

### Other information

I found one related issue: https://github.com/dotnet/runtime/issues/28557

**Comment by tannergooding** [comment]
I have a PR up fixing this for .NET 7 here: https://github.com/dotnet/runtime/pull/70795

I've added regression tests that validate the change, but if you could confirm that it fixes the issue on your end then that will help with the backport PR to .NET 6

**Comment by nojaf** [comment]
Hello @tannergooding, many thanks for this quick response. Much appreciated!
@jgiannuzzi will verify this on our end.
We will keep you posted.

**Comment by jgiannuzzi** [comment]
Thanks a lot for the quick fix @tannergooding. I can confirm that it fixes the issue on our end 👍
We're looking forward to the backport to .NET 6!
