### ISSUE TITLE
Inconsistent behaviour with fr-CA CultureInfo across platforms

### ISSUE THREAD

**Issue by EricStG** [dotnet/runtime#70789]
### Description

When formatting a currency with a fr-CA CultureInfo, we get the same behaviour on Linux and Windows 11: `10,00 $`

However, on Windows 11, it becomes: `10,00 $ CA`

### Reproduction Steps

Run the following on Windows 10, 11 and Linux
```cs
using System.Globalization;

var ci = new CultureInfo("fr-CA");
var text = string.Format(ci, "{0:C}", 10);
Console.WriteLine(text);
```

### Expected behavior

The format of the string should be the same across all platform (`10,00 $`)

### Actual behavior

The format of the string is different on Windows 11

### Regression?

It might be regression on the OS

### Known Workarounds

Manually trimming " CA" from the end of the currency strings

### Configuration

- .Net Core 6
- Windows 10, 11 and Ubuntu
- x64
- Specific to Windows 11
- Not browser related

**Comment by tarekgh** [comment]
This is not a .NET issue; the currency symbol is picked from the ICU library shipped with Windows. 

@jefgen on Windows using ICU `68.2.0.6`, the `fr_CA` currency symbol is defined as `$\u00a0CA` while on Linux (at least I check with ICU version 70), the currency symbol is just `$`. 

@EricStG I am closing the issue as this is ICU specific issue but @jefgen should be able to help talking about this behavior.

**Comment by jefgen** [comment]
Hi @tarekgh, just curious, what API does .NET call to get the currency symbol from ICU? (Just to help narrow down where the data is coming from).

Also tagging in @chetanladdha and @rp9-next, who are taking over the handling of the ICU library on Windows going forward.

**Comment by tarekgh** [comment]
@jefgen 

>  just curious, what API does .NET call to get the currency symbol from ICU? (Just to help narrow down where the data is coming from).

```C
    UNumberFormat* pFormat = unum_open(UNUM_DECIMAL, NULL, 0, locale, NULL, &status);
    unum_getSymbol(pFormat, UNUM_CURRENCY_SYMBOL, value, valueLength, &status);
```

**Comment by rp9-next** [comment]
CLDR data has changed the currency symbol for the fr_CA locale multiple times.

	1. CLDR 34 (CAD -> "$" ) :         Windows 10 uses ICU 63.1 which intern uses CLDR 34
	2. CLDR 38.1 (CAD -> "$ CA") :     Windows 11 uses ICU 68.2 which maps to CLDR 38.1
	3. CLDR  40 (CAD -> "$") :         Windows still lacks support ICU 70 or above which maps to CLDR 40 or above

**Fix:** 
The problem will be fixed once windows picks up the latest version of ICU.

![image](https://user-images.githubusercontent.com/103115900/174766634-c63a3328-83ed-4596-9ee3-5cfd73cced5b.png)

**Comment by EricStG** [comment]
@rp9-next Thanks for the update.
When you say "once windows picks up the latest version of ICU", does this mean a future version of Windows 11, or like Windows 12?

**Comment by rp9-next** [comment]
Hey @EricStG,
I can't comment on the exact version of windows it will be released. 
We wish to release it as soon as possible (possibly in the next couple of iterations)

**Comment by EricStG** [comment]
I can confirm that it's same version of ..NET on all platforms.

We can get the desired behaviour by setting an app local version of the ICU, but we have to go to a lower version since there's nothing over 68 on nuget:
```xml
<ItemGroup>
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="67.1.0.7" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="67.1" />
</ItemGroup>
```

Enabling NLS via csproj or env variable also works

**Comment by tarekgh** [comment]
.NET started to use ICU by default in .NET 5.0 and up. If you compare the app built with .NET 3.1 against apps using 5.0+ you'll notice the differences. Also, .NET does not use ICU on Server 2016 and 2019 so these are 2 other platforms you can notice the difference. I encourage you to read https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu for more info.

I am highly discouraged to enable back NLS mode. You are going to lose some good features and will start being inconsistent moving forward.
