### ISSUE TITLE
C# Dictionary insertion speed could be improved (performance)

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#70796]
It seems like both C++ (unsorted map) & C# (Dictionary) for strings could be improved for insertion.

Details for C++: https://github.com/microsoft/STL/issues/2777

Lower is better - on [Ubuntu](https://ubuntu.com/desktop) 22.04 LTS (Jammy Jellyfish)
Linux-5.15.0-37-generic-x86_64-with-glibc2.35 on 2022-06-09:

|                        Language                       |                       Version                       | Adjusted time based on CPU usage (seconds) | Average time (seconds) | Average CPU usage[^1] (%) | Average memory usage[^1] (%) |
|:-----------------------------------------------------:|:---------------------------------------------------:|:------------------------------------------:|:----------------------:|:-------------------------:|:----------------------------:|
|         [custom c++](https://github.com/microsoft/STL/issues/2777)        |                        (0,0)                        |                   0.304                    |         0.300          |           8.469           |            2.839             |
|      [c++](https://en.wikipedia.org/wiki/C%2B%2B)     |         g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0        |                   1.036                    |         1.012          |           8.528           |            2.273             |
|       [pypy](https://en.wikipedia.org/wiki/PyPy)      | Python 2.7.18 (7.3.9+dfsg-1, Apr 01 2022, 21:40:34) |                   1.457                    |         1.427          |           8.511           |            2.303             |
| [c#](https://docs.microsoft.com/en-us/dotnet/csharp/) |                       6.0.300                       |                   2.574                    |         2.514          |           8.532           |            2.391             |

**Comment by pepe78attempt34** [comment]
Even with StringBuilder, while way better, there seems to be still potential when comparing with [custom c++](https://github.com/microsoft/STL/issues/2777).

Also, maybe it's time to initialize string to something larger at the beginning so + operation would not become so slow. 64 characters is not that much in my opinion, or 32.

Perf:
Lower is better - on [Ubuntu](https://ubuntu.com/desktop) 22.04 LTS (Jammy Jellyfish)
Linux-5.15.0-39-generic-x86_64-with-glibc2.35 on 2022-06-15:

|                        Language                       |                       Version                       | Adjusted time based on CPU usage (seconds) | Average time (seconds) | Average CPU usage[^1] (%) | Average memory usage[^1] (%) |
|:-----------------------------------------------------:|:---------------------------------------------------:|:------------------------------------------:|:----------------------:|:-------------------------:|:----------------------------:|
|         [custom c++](https://github.com/microsoft/STL/issues/2777)        |                        (0,0)                        |                   0.331                    |         0.311          |           8.870           |            2.643             |
|      [c++](https://en.wikipedia.org/wiki/C%2B%2B)     |         g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0        |                   1.071                    |         1.003          |           8.896           |            1.998             |
| [c#](https://docs.microsoft.com/en-us/dotnet/csharp/) |                       6.0.300                       |                   1.268                    |         1.179          |           8.963           |            2.130             |
|       [pypy](https://en.wikipedia.org/wiki/PyPy)      | Python 2.7.18 (7.3.9+dfsg-1, Apr 01 2022, 21:40:34) |                   1.561                    |         1.453          |           8.953           |            2.020             |


Code:
```
using System.Text;

Dictionary<string, bool> dic = new Dictionary<string, bool>();
Random r = new Random();
string letter = "qwertyuiopasdfghjklz";
for (int i = 0; i < 5000001; i++)
{
    if (i % 1000000 == 0)
    {
        Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"));
    }
    StringBuilder s = new StringBuilder("");
    for (int j = 0; j < 50; j++)
    {
        s.Append(letter[r.Next(20)]);
    }
    dic[s.ToString()] = true;
}
```
![perfcomp_final](https://user-images.githubusercontent.com/107596137/173975856-e620b334-0d09-4049-ac85-2f60ffa32dc3.png)
![cpumem1](https://user-images.githubusercontent.com/107596137/173975887-16283e51-73d6-4584-bac4-597f7a92bfd3.png)

**Comment by Clockwork-Muse** [comment]
> Also, maybe it's time to initialize string to something larger at the beginning so + operation would not become so slow. 64 characters is not that much in my opinion, or 32.

You can't, because strings in C# are immutable - the `+` operation doesn't mutate the existing string, but return a new one, so the additional memory would be wasted.

**Comment by svick** [comment]
I think the most efficient way to create the string would be to use `string.Create`:

```c#
using System.Text;

var dic = new Dictionary<string, bool>();
var r = new Random();
const string letter = "qwertyuiopasdfghjklz";
for (int i = 0; i < 5000001; i++)
{
    if (i % 1000000 == 0)
    {
        Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"));
    }

    string s = string.Create(50, r, static (span, random) =>
    {
        foreach (ref char c in span)
        {
            c = letter[random.Next(20)];
        }
    });

    dic[s] = true;
}
```

**Comment by vfdvfvfvf** [comment]
You are actually very correct. C# Dictionary insertion is actually fast:

Lower is better - on [Ubuntu](https://ubuntu.com/desktop) 22.04 LTS (Jammy Jellyfish)
Linux-5.15.0-39-generic-x86_64-with-glibc2.35 on 2022-06-16:

|                        Language                       |                       Version                       | Adjusted time based on CPU usage (seconds) | Average time (seconds) | Average CPU usage[^1] (%) | Average memory usage[^1] (%) |
|:-----------------------------------------------------:|:---------------------------------------------------:|:------------------------------------------:|:----------------------:|:-------------------------:|:----------------------------:|
| [c#](https://docs.microsoft.com/en-us/dotnet/csharp/) |                       6.0.202                       |                   0.215                    |         0.195          |           9.191           |            2.602             |
|         custom c++       |                        (0,0)                        |                   0.294                    |         0.279          |           8.791           |            6.543             |
|       [pypy](https://en.wikipedia.org/wiki/PyPy)      | Python 2.7.18 (7.3.9+dfsg-1, Apr 01 2022, 21:40:34) |                   0.336                    |         0.321          |           8.707           |            2.485             |
|      [c++](https://en.wikipedia.org/wiki/C%2B%2B)     |         g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0        |                   0.513                    |         0.424          |           10.083          |            2.574             |

C# code (other languages similar changes):
```
List<string> xls = new List<string>();
Dictionary<string, bool> dic = new Dictionary<string, bool>();
Random r = new Random();
string letter = "qwertyuiopasdfghjklz";

for (int i = 0; i < 5000001; i++)
{
    string s = "";
    for (int j = 0; j < 50; j++)
    {
        s += letter[r.Next(20)];
    }
    xls.Add(s);
}

for (int i = 0; i < 5000001; i++)
{
    if (i % 1000000 == 0)
    {
        Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"));
    }
    dic[xls[i]] = true;
}
```

It is C# string, stringbuilder and random that is slow... cool. (and in C++ unordered_map obviously). (Also, C# string should be renamed to C# word based on your definition... I recommend lookup word String in English dictionary...)

Feel free to close this, I would , but I don't have the rights (or I don't see close button).

![cpumem1](https://user-images.githubusercontent.com/107647407/174150867-89ba78c8-2551-4b85-b126-457c976f1f74.png)
![perfcomp_final](https://user-images.githubusercontent.com/107647407/174150870-c9cd8b65-857f-409c-8ff8-96b6a20a0e4d.png)
