### ISSUE TITLE
[libraries-pgo]: Assertion failed 'fgDominate(head, entry)' in 'System.Text.Encoding:GetByteCount(System.String,int,int):int:this' during 'Hoist loop code' (IL size 109; hash 0x10278d31; Tier1)

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#70802]
Forking from #70569, see that issue for details.

**Comment by jakobbotsch** [comment]
Still seeing this assert in the latest libraries-pgo run.

Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1832440&view=results
Helix job name: net7.0-Linux-Release-arm64-CoreCLR_checked-fullpgo_random_edge
Work item: System.Text.Encoding.Tests
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d09ca73c69e646cfbe/System.Text.Encoding.Tests/1/console.ef9d5662.log?helixlogtype=result

**Comment by AndyAyersMS** [comment]
Hmm, ok. Will investigate.

**Comment by AndyAyersMS** [comment]
We decide to clone this fairly complex loop because
```
Loop L00 has invariant type test [000577] on V17 ...  passed profile screening
```
<img width="584" alt="image" src="https://user-images.githubusercontent.com/10121823/174462453-b8f5682c-deff-4559-a5cd-ee84882a8da8.png">

However, we don't get this right, and after cloning there is now a path from cloning conditions to the slow loop (on the left) over to the fast loop. The edge from BB71->BB72 is problematic; it looks like we didn't clone this subgroup of blocks but instead shared it.

Because of this the fast loop entry BB37 is not dominated by its header BB17, hence the assert.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/10121823/174462510-14f24bc0-4cc8-4f25-8a1a-ff173eb2a164.png">

**Comment by AndyAyersMS** [comment]
<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/10121823/174463329-a86e1ff9-fabf-4784-b867-718cb0d4bde6.png" /img>

</td>
<td>
Hmm, seems fairly clear where things go off the rails.

```
L00: couldn't find init/test/incr; not LPFLG_ITER loop
Recorded loop L00, from BB15 to BB40 (Head=BB14, Entry=BB34, Exit=BB40)
```

At left is a simplified linear view, where it is a bit easier to see what's going wrong. We see a middle-entry BB34, top BB15, bottom BB40.

So L00 has some non-loop backedges incident on its entry, and we don't canonicalize that case (we only canonicalize for top). 

If we did, we'd produce something like the graph at right, where BB34_A is the block added by canonicalizing BB34 to hoist out the non-loop backedges. Then we could safely clone.
</td>
<td>
<img src="https://user-images.githubusercontent.com/10121823/174463465-0f7761b1-d7ee-4ec9-84c9-f69388a66c00.png" /img>

</td>
</tr>
</table>
