### ISSUE TITLE
TimeZoneInfo.GetUtcOffset returns different value on Windows and Linux

### ISSUE THREAD

**Issue by czd890** [dotnet/runtime#70813]
### Description

TimeZoneInfo.GetUtcOffset returns different value on Windows and Linux

### Reproduction Steps

```
// Net6.0

TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time").GetUtcOffset(DateTime.Parse("4/3/1950"))
// -4 on windows 10
// -5 on linux(mcr.microsoft.com/dotnet/aspnet:6.0)
```

### Expected behavior

They should be the same.

### Actual behavior

// -4 on windows
// -5 on linux

**Comment by filipnavara** [comment]
Windows time zones don't cover historical data beyond certain point in time. 1950 is definitely way below that point.

**Comment by dakersnar** [comment]
@tarekgh can you take a look at this please? This looks Date/Time related.

**Comment by tarekgh** [comment]
@filipnavara is correct. We are limited to Windows zone data when running on Windows. As indicated before, Windows doesn't carry the full historical data of time zones. Unfortunately, this is the limitation we currently have.

**Comment by czd890** [comment]
@filipnavara @tarekgh Thanks for your clarification.
