### ISSUE TITLE
Extensive memory .net 7 preview 5

### ISSUE THREAD

**Issue by gruber123** [dotnet/runtime#70825]
Simple checking version
dotnet --version
memory to high 80 %
returned to preview 4
it is not take so much memory

**Comment by realivanjx** [comment]
`dotnet watch test` on my ubuntu 22.04:
![image](https://user-images.githubusercontent.com/12814796/174305409-d972be58-8774-4efc-bb27-111477a8c14a.png)

**Comment by tommcdon** [comment]
Hi @gruber123! Would you mind telling us which OS's and architectures reproduces the memory growth issue between .net 7 p4 and p5?  Also can you clarify how much extra memory is being used, for example, what does "high 80%" mean?

**Comment by gruber123** [comment]
Os: windows 7 sp1
Installation of .net 7 preview 5 stacked on near the end (cannot move mouse or click on any window, about 20 minutes and after succesful opening taskmanager, I realize that memory is above 80% from 8000 mb, and installation still not finished), after waiting some more time it finished, I've checked on command line:
Cmd:
dotnet --version 
There immediately was jump in memory exactly as talked above and showing result take more time (about 10s) than in previous dotnet versions (less 1s)
With .net 7 preview 5 my system has halted after opening vs code as dotnet.exe running on analysing data in task manager, so I have to roughly turn the computer off and after that disk C: have been checked many files corrupted as extensions from vs code, and maybe some not finished background browsers updatings, so  after uninstalling .net 7 preview 5 and checking same operations on remaining .net 6 work perfect, and in vs code missing some extensions that have been corrupted, during system shutdown, and finally I've again Installed .net 7 preview 4 and the same operations and vs code still work perefect memory doesn't jump to 80%.

**Comment by gruber123** [comment]
@adamsitnik 

I cannot check this on .net 7 p5 as I've uninstalled it and now I'm on .net 7 p4 that no noticable growth in memory, sorry.

**Comment by tommcdon** [comment]
> Os: windows 7 sp1 Installation of .net 7 preview 5 ..

Closing per https://github.com/dotnet/announcements/issues/226 - .NET 7+ will not support Windows 7 and 8.1.
