### ISSUE TITLE
AddSimpleConsole ignores IncludeScope

### ISSUE THREAD

**Issue by garcipat** [dotnet/runtime#70822]
### Description

We use the simple console logging in our CLI and even when we configure it to not include the scope, it includes the scope in the output:

```csharp
var services = new ServiceCollection()
                .AddLogging(builder =>
                {
                    builder.ClearProviders();
                    builder.SetMinimumLevel(LogLevel.Information);

                    builder.AddSimpleConsole(options =>
                    {
                        options.IncludeScopes = false;
                        options.SingleLine = true;
                        options.TimestampFormat = "HH:mm:ss ";
                    });
                })
```

![image](https://user-images.githubusercontent.com/7288563/173807211-90a5df4e-4993-4a5d-961d-315a75678bb4.png)

### Configuration

We use a regular console application with .NET 6 in Windows x64

### Regression?

There was a breaking change with .NET 3.1 to .NET5 where the options are defined different:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/5.0/obsolete-consoleloggeroptions-properties

But with the new style the scope is added even when set to false.

**Comment by eerhardt** [comment]
@maryamariyan - do we just need to add a check for that option here?

https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L97-L98

**Comment by garcipat** [comment]
> @maryamariyan - do we just need to add a check for that option here?
> 
> https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L97-L98

Seems about exactly what is required. SingleLine is checked and respected there as well, so it would make sense for this too.

**Comment by eerhardt** [comment]
Seems like an easy fix that should be made for 7.0.

**Comment by skyoxZ** [comment]
@garcipat Could you please explain more? I don't see any scope info in your screenshot. And my test shows it works as expected.

`IncludeScopes` has been checked here:
https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L182



([Doc about LogScopes](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging#log-scopes))

**Comment by garcipat** [comment]
> @garcipat Could you please explain more? I don't see any scope info in your screenshot.
There is the "Buhler.Automation.JointForces..." that is the scope. At least I expected that to be the scope.

**Comment by ericstj** [comment]
> There is the "Buhler.Automation.JointForces..." that is the scope

That is not the scope. The scope should be prefixed with `=>`. 
https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L187-L196

That appears to be the category (AKA name) and the event ID:
https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Microsoft.Extensions.Logging.Console/src/SimpleConsoleFormatter.cs#L74-L91

I'm missing the place where this would be a regression from 3.1.  I see 3.1 also printed log name:
https://github.com/dotnet/extensions/blob/dde89ea6e72501a4a128c21b80b0b6326acb8ff6/src/Logging/Logging.Console/src/ConsoleLogger.cs#L112-L116

**Comment by maryamariyan** [comment]
I believe 

https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerExtensionsTests.cs#L403

and 

https://github.com/dotnet/runtime/blob/c21ae04d923a1e5d2964fed61cc919571cce2efe/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerExtensionsTests.cs#L435

Exercise this code path and the test is asserting that when using `AddConsole`, if `IncludeScopes` is false then that property is also reflected into the appropriate `FormatterOptions` being used and should therefore not write down scopes. 

Closing this issue as I believe the code is working as we expect.
