### ISSUE TITLE
Various memory usage issues and inconsistencies

### ISSUE THREAD

**Issue by littlehoneybunnytuttifruttipumpkinpie** [dotnet/runtime#70826]
Due to running into variety of memory errors with .NET 7 Preview 4, I've decided to create a small memory test app that tests memory usage and exposes some minor issues, though unrelated to my main 'System.OutOfMemoryException' errors that I will be reporting separately.
The issues I'd like to report here are related to inconsistent app behavior between different .NET frameworks, as well as crashes related to Native AOT.
The program populates two equivalent dictionaries (one static and one as internal variable) with large amounts data, clearing both after RAM usage exceeds 95%.
The example exhibits the following issues:
.NET 6:
  - in release mode: everything works fine and both dictionaries seem fully cleared, releasing the memory.
  - in debug mode: only the static dictionary releases the memory when cleared, while the internal dictionary's reserved/used memory isn't cleared, thus overall only half of memory is released.

.NET 7 Preview 4:
  - in both release and debug modes: only the static dictionary releases the memory when cleared, while the internal dictionary does't release memory when cleared.

.NET 7 Preview 4 with ILCompiler (Native AOT on Windows 7 / x64)
  - works fine on several Windows Server machines.
  - on several Windows/desktop PCs the program crashes after a few loops, unable to continue the test.

![image](https://user-images.githubusercontent.com/20084989/173371938-f19ced4e-f1d6-4730-93c3-dbab31336343.png)

The program makes extensive use of `GC.Collect(); GC.WaitForPendingFinalizers();` to release memory and be able to perform the test, though potentially this method isn't correct and/or another method would be more desirable and produce consistent results?

Full program:
```
/**
This basic memory test program populates two equivalent dictionaries (one static and one as internal variable) with large amounts data.
Both dictionaries are cleared when memory gets to 95+% full.

It exhibits the following issues:
.NET 6:
  - in release mode: everything works fine and both dictionaries seem fully cleared, releasing the memory.
  - in debug mode: only the static dictionary releases the memory when cleared, while the internal dictionary's reserved/used memory isn't cleared, thus overall only half of memory is released.

.NET 7 Preview 4:
  - in both release and debug modes: only the static dictionary releases the memory when cleared, while the internal dictionary does't release memory when cleared.

.NET 7 Preview 4 with ILCompiler (Native AOT)
  - works fine on several Windows Server machines.
  - on several Windows/desktop PCs the program crashes after a few loops, unable to continue the test.
**/

using System.Text;

namespace MemTest
{
    internal class Test
    {
        internal static Dictionary<long, string> static_string_dict = new Dictionary<long, string>();
    }

    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Dictionary<long, string> string_dict = new Dictionary<long, string>();

                GCMemoryInfo comp_info = GC.GetGCMemoryInfo();
                double ram_divider = 1024 * 1024 * 1024; //GB
                double ram_total = comp_info.TotalAvailableMemoryBytes / ram_divider;

                long loop = 0;
                string test_string = CreateTestString(10000000);

                for (; ; )
                {
                    int tick_count = Environment.TickCount;

                    loop++;
                    string_dict[loop] = new string(test_string);
                    Test.static_string_dict[loop] = new string(test_string);

                    Console.WriteLine("Loop completed in {0} ms.", Environment.TickCount - tick_count);

                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    //Task.Delay(5000).Wait();
                    comp_info = GC.GetGCMemoryInfo();
                    double ram_used = comp_info.MemoryLoadBytes / ram_divider;

                    Console.WriteLine("Used memory: {0} of {1} GB.", ram_used.ToString("0.##"), ram_total.ToString("0.##"));

                    //Clear RAM when over 95% full
                    if (ram_total != 0 && ram_used / ram_total >= 0.95)
                    {
                        Console.WriteLine("Memory nearly full. Clearing data.");
                        loop = 0;
                        string_dict = new Dictionary<long, string>();
                        Test.static_string_dict = new Dictionary<long, string>();

                        GC.Collect();
                        GC.WaitForPendingFinalizers();
                        //break;
                    }
                }

                Console.WriteLine("Program completed");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }

            Console.WriteLine("Press any key to exit");
            Console.ReadKey();
        }


        static string CreateTestString(int components)
        {
            //creates custom strings for additional testing of compression not used in memory testing
            StringBuilder builder = new StringBuilder();
            for (int i = 1; i <= components; i++)
            {
                builder.Append(i).Append(',');
            }

            return builder.ToString();
        }

    }
}
```

**Comment by agocke** [comment]
@VSadov Any of these issues look familiar to you?

**Comment by VSadov** [comment]
I have tried the repro with recent build form main branch (https://github.com/dotnet/installer#table) and it was able to run continuously as long as I could wait with either NativeAOT or CoreCLR.  The timings and total memory were slightly different. but that could be just different tunings and GC nondeterminism.

There were quite a bit of improvements in NativeAOT with focus on GC reliability recently. Perhaps that helped.

**Comment by MichalStrehovsky** [comment]
Sounds like we can close.
