### ISSUE TITLE
[wasm] Random uncaught js exceptions in `System.Security.Cryptography.Tests` on the browser

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#70856]
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1828769&view=logs&jobId=11c5c840-d20a-5536-428b-70d8cd9c6259&j=11c5c840-d20a-5536-428b-70d8cd9c6259&t=73598586-463f-5241-5dc8-b8ffdebf8b89), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70814-merge-d4c4104d48384a04a6/WasmTestOnBrowser-System.Security.Cryptography.Tests/1/console.495c3b2b.log?helixlogtype=result):

```
[16:28:42] info: Starting:    System.Security.Cryptography.Tests.dll
[16:28:55] fail: [out of order message from the browser]: http://127.0.0.1:36237/dotnet.js 2:71050 Uncaught
[16:43:36] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

We should throw instances of `Error`, so we can get the traces too.

I found other instances too, like:
- [build](https://dev.azure.com/dnceng/public/_build/results?buildId=1820921&view=logs&j=11c5c840-d20a-5536-428b-70d8cd9c6259), [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70650-merge-13df2b39f7404d8b99/WasmTestOnBrowser-System.Security.Cryptography.Tests/1/console.e2d40418.log?helixlogtype=result)

cc @eerhardt

**Comment by buyaa-n** [comment]
The same failure on https://github.com/dotnet/runtime/pull/70610/checks?check_run_id=6978327176
```log
[04:52:10] info: Starting:    System.Security.Cryptography.Tests.dll
[04:52:19] fail: [out of order message from the browser]: http://127.0.0.1:37153/dotnet.js 2:71050 Uncaught
[05:07:04] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
/datadisks/disk1/work/AC6B09D7/w/B24209B4/e /datadisks/disk1/work/AC6B09D7/w/B24209B4/e
----- end Tue Jun 21 05:07:04 UTC 2022 ----- exit code 71 ----------------------------------------------------------
XHarness artifacts: /datadisks/disk1/work/AC6B09D7/w/B24209B4/uploads/xharness-output
```
https://github.com/dotnet/runtime/pull/70610/checks?check_run_id=6978327176

**Comment by radical** [comment]
Fixed by https://github.com/dotnet/runtime/pull/71693 .
