### ISSUE TITLE
Strange runtime failure - unmanaged heap corruption

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#70860]
OS: Windows 11 22000.675
.NET SDK: 7.0.100-preview.5.22307.18
IDE: VS 2022 17.3.0 Preview 2.0

.csproj settings:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <TieredCompilation>false</TieredCompilation>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Hykode.LowLevel.Test.Console</RootNamespace>
        <LangVersion>preview</LangVersion>
	<AnalysisLevel>preview</AnalysisLevel>
    </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <Optimize>False</Optimize>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <Optimize>True</Optimize>
    </PropertyGroup>
</Project>
```

While running/debugging my console app I get this strange error occuring somewhere deep inside runtime:

![image](https://user-images.githubusercontent.com/3519388/174165036-6f10ec20-4329-4168-996d-82e6ed8b4754.png)

Any tips on what actually goes wrong? 

PS: btw, why does ```#ifdef TARGET_X86``` condition is getting hit while I get x64 being set in my settings?

**Comment by jkotas** [comment]
The crashing stacktrace indicated unmanaged heap corruption.

Does you console app has an unmanaged interop in it (`DllImport`, etc.)? It is most likely what's causing this crash.

**Comment by hypeartist** [comment]
@jkotas Not sure about dll importing (my code has no direct uses of it), but I do use unmanaged memory via ```NativeMemory.AlignedAlloc``` and ```NativeMemory.ZeroMemory```. But how could use of those methods affect jitting process?!

**Comment by jkotas** [comment]
The runtime and JIT is using the same unmanaged heap as `NativeMemory.Alloc/Free` APIs. If you corrupt the unmanaged heap by using these API incorrectly, you can crash the JITing process among other things.
