### ISSUE TITLE
[API Proposal]: `System.Text.Json`. Add ability to convert a JSON array to `[Flags]` enum

### ISSUE THREAD

**Issue by xperiandri** [dotnet/runtime#70864]
### Background and motivation

In continuation of https://github.com/dotnet/runtime/issues/30655 I propose to add ability to deserialize a collection of integer or string values into a `Flags` enum

### API Proposal

When such JSON
``` JSON
"allowedCustomerOperations": [
      "Delete",
      "Update",
      "Read"
  ],
```
or such JSON
``` JSON
"allowedCustomerOperations": [ 0, 1, 2 ],
```
comes it can be deserialized into a field `AllowedCustomerOperations` of type `AllowedCustomerOperations`
``` F#
[Flags]
type AllowedCustomerOperations =
| Read = 0
| Update = 1
| Delete = 2
```

### API Usage

No special syntax or members required

### Risks

No risks

**Comment by eiriktsarpalis** [comment]
I don't think we could support this out of the box, it would warrant authoring a separate custom converter. We generally don't ship custom converters out of the box (`JsonStringEnumConverter` being the only exception).

I don't think we would consider adding more unless there is substantial demand or the converter cannot be implemented by users. Roughly speaking you could do the following (disclaimer: this hasn't been tested):
```C#
public class FoldingEnumConverter<TEnum> : JsonConverter<TEnum>
    where TEnum : enum
{
     private static JsonConverter<TEnum[]> s_defaultArrayConverter = 
          (JsonConverter<TEnum[]>)new JsonSerializerOptions { Converter = new JsonStringEnumConverter() }.GetConverter(typeof(TEnum[]));

     public override TEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
     {
           TEnum[] array = s_defaultArrayConverter.Read(ref reader, typeof(TEnum[]), options);
           TEnum accumulator = default;
           foreach (TEnum value in array) accumulator = accumulator & value;
           return accumulator;
     }
}
```
