### ISSUE TITLE
Use .Net core console program how to obtain cpu/memory utilization

### ISSUE THREAD

**Issue by zichenlbl** [dotnet/runtime#70872]

**Comment by gfoidl** [comment]
You mean something like [dotnet-counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters)?
Or from within the app itself?

**Comment by zichenlbl** [comment]
> 



> 

CPU usage of the computer

**Comment by zichenlbl** [comment]
> 你的意思是[dotnet-counters 之](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters)类的东西？ 还是来自应用程序本身？

Get the total CPU usage of the computer。

**Comment by huoyaoyuan** [comment]
.NET itself doesn't implement system wide monitoring.
You can use native Windows/POSIX functionality by P/Invoke: https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-pdh-functions-to-consume-counter-data (English) 
https://mp.weixin.qq.com/s?__biz=MzIzMjQwNTkwMA==&mid=2247484795&idx=1&sn=30096165cdbf801c441da9bd730d486b&chksm=e8942b98dfe3a28ebd778d0d982543af016f91cde25f989488a12c3bb7f78af9b0e31951f453&scene=21#wechat_redirect (Chinese)
If you just want such functionality in console, PowerShell is more handy: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt708809(v=vs.85)

.NET本身没有提供对整个系统的查询功能，需要使用操作系统API进行查询

**Comment by zichenlbl** [comment]
> .NET itself doesn't implement system wide monitoring. You can use native Windows/POSIX functionality by P/Invoke: https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-pdh-functions-to-consume-counter-data (English) https://mp.weixin.qq.com/s?__biz=MzIzMjQwNTkwMA==&mid=2247484795&idx=1&sn=30096165cdbf801c441da9bd730d486b&chksm=e8942b98dfe3a28ebd778d0d982543af016f91cde25f989488a12c3bb7f78af9b0e31951f453&scene=21#wechat_redirect (Chinese) If you just want such functionality in console, PowerShell is more handy: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt708809(v=vs.85)
> 
> .NET本身没有提供对整个系统的查询功能，需要使用操作系统API进行查询

 我想把.net core控制台程序运行在Linux系统上，请问.net core控制台程序如何获取Linux系统的电脑CPU以及内存的使用率？然后我要把CPU使用率和内存使用率保存到数据库中查看。

**Comment by huoyaoyuan** [comment]
This is not specific to .NET. I suggest you to see open source LInux monitoring programs like https://github.com/sysstat/sysstat to find how they get the statistics, and translate the calls into P/Invoke.

推荐参考开源的监控软件，比如sysstat，寻找其是如何读取这些监控数据的，然后转写为P/Invoke
