### ISSUE TITLE
RyuJIT: optimize test instruction in case of GT_EQ/NE(shift, 0)

### ISSUE THREAD

**Issue by sivarv** [dotnet/runtime#7088]
PR https://github.com/dotnet/coreclr/pull/8461 disabled compare opt that optimizes 'test' instruction in case of GT_EQ/NE(shift, 0).

On xarch, hardware depending on the operand size masks upper bits to derive shift count. If the resulting shift count is zero then flags are not modified.  Compare opt can be done in cases where shift count is non-zero and known to be in the range depending on the operand size.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

**Comment by BruceForstall** [comment]
Given the low priority of the optimization, I'm going to close this.
