### ISSUE TITLE
RBTree need O(n) instead of O(log n) for insert?

### ISSUE THREAD

**Issue by Hoschi1982** [dotnet/runtime#709]
Hy there ... i tried the RBTree implementation in the DataTable and it seems to need linear time complexity [O(n)] for insert.  

Is this correct? I thought the worst case time complexity for insert operations in red black trees should need O(log n)?

**Comment by scalablecory** [comment]
Can you post your benchmark that demonstrates this?

**Comment by Hoschi1982** [comment]
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17134.1130 (1803/April2018Update/Redstone4)
Intel Core i7-4770 CPU 3.40GHz (Haswell), 1 CPU, 8 logical and 4 physical cores
Frequency=3312654 Hz, Resolution=301.8728 ns, Timer=TSC
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X86 LegacyJIT
  Job-FTOBUC : .NET Framework 4.8 (4.8.4042.0), X86 LegacyJIT

InvocationCount=1  UnrollFactor=1

|             Method | MaxItems |            Mean |        Error |       StdDev |          Median |     Gen 0 |     Gen 1 |     Gen 2 |  Allocated |
|------------------- |--------- |----------------:|-------------:|-------------:|----------------:|----------:|----------:|----------:|-----------:|
| BenchmarkRBTreeAdd |      100 |        26.79 us |     0.531 us |     0.944 us |        26.72 us |         - |         - |         - |          - |
| BenchmarkRBTreeAdd |     1000 |       354.97 us |     7.202 us |    19.957 us |       347.76 us |         - |         - |         - |    41056 B |
| BenchmarkRBTreeAdd |    10000 |     4,654.72 us |   160.444 us |   460.345 us |     4,489.30 us |         - |         - |         - |   336616 B |
| BenchmarkRBTreeAdd |   100000 |    50,692.41 us |   655.924 us |   512.102 us |    50,848.65 us |         - |         - |         - |  3238696 B |
| BenchmarkRBTreeAdd |  1000000 |   603,029.97 us | 3,256.995 us | 2,887.241 us |   604,027.16 us | 2000.0000 | 2000.0000 | 2000.0000 | 32250192 B |
| BenchmarkRBTreeAdd |  1500000 |   934,500.08 us | 2,024.880 us | 1,795.003 us |   934,482.74 us | 2000.0000 | 2000.0000 | 2000.0000 | 48308464 B |
| BenchmarkRBTreeAdd |  2000000 | 1,276,566.79 us | 4,415.069 us | 3,913.844 us | 1,277,720.52 us | 2000.0000 | 2000.0000 | 2000.0000 | 64374928 B |

**Comment by Hoschi1982** [comment]
Ahh I think I made a mistake. 
O (log n) refers to one operation. If an operation takes about the same amount of time no matter how many elements are included, then the sum of operations is slightly higher than linearly increasing. That explains the measurement data. Is the line of thought correct?

**Comment by scalablecory** [comment]
> O (log n) refers to one operation. If an operation takes about the same amount of time no matter how many elements are included, then the sum of operations is slightly higher than linearly increasing. That explains the measurement data. Is the line of thought correct?

Yes, that's correct.

**Comment by rstm-sf** [comment]
Hello!

As far as I understand, `DataTable` is a column-story in background: a new row is created by columns. (Is that right?)
