### ISSUE TITLE
Remove use of pool and buffer copy in Deserialize(ref Utf8JsonReader reader, ...)

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#70902]
Reported by @bignoncedric the buffer copy at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L418 does not appear to be necessary.

After investigation I don't see a reason why the copy is necessary neither nor the need to use the pool. The original reader is expected to have enough data in the buffer to read the token (including object\arrays via the `TrySkip()` call), so we don't have to worry about the reader returning `false` for out-of-data reads such as when the serializer is used with Streams. So both the original reader and new temporary reader should be able to share the same memory. This applies both to `valueSequence` and `valueSpan` cases.

Removing the check will increase performance for these scenarios. The typical usage scenario for this API is being able to easily deserialize objects\collections within a custom converter since the custom converter is passed a reader.

The existing code looks like it is a copy-paste-simplification of [JsonDocument.TryParseValue](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs#L411-L654) which also has the copy semantics, but which is needed there since document needs to keep the raw memory around after the call.

Expect: remove the pool- and copy-related code and verify test coverage. Note the serializer doesn't use `SequenceReader` so testing must be done by directly invoking the reader with a `SequenceReader`.

**Comment by eiriktsarpalis** [comment]
Further to that issue, one thing I still can't understand is why does the method read ahead separately, before passing along a copy of the reader state (`newReader`) to the converter? It seems pretty wasteful and it doesn't appear to have any impact on checkpointing compared to if we passed the original reader directly.

**Comment by eiriktsarpalis** [comment]
One possible guess is that the author of the method wanted to specifically intercept `JsonReaderException`:

https://github.com/dotnet/runtime/blob/992cf8c97cc71d4ca9a0a11e6604a6716ed4cefc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L399-L404

But again, I don't see why this is important given that it's a Deserialize method. If absolutely necessary we could extract it from any wrapping `JsonException`.

**Comment by steveharter** [comment]
> One possible guess is that the author of the method wanted to specifically intercept JsonReaderException:

The reader is mutable, so if an exception is thrown we want the read to be undone.

Does that answer your question or were you thinking something else?

**Comment by eiriktsarpalis** [comment]
> The reader is mutable, so if an exception is thrown we want the read to be undone.

A reader can be checkpointed by taking a copy of the struct. I did a bit of digging and it turns out that the reason is we need to scope reader to the next value and not include tokens from subsequent data, as this will cause the serializer to fail. I'll follow up with a PR that addresses this issue soon.
