### ISSUE TITLE
Uri.IsWellFormedUriString false negative 

### ISSUE THREAD

**Issue by sergey-su** [dotnet/runtime#70929]
### Description

Uri.IsWellFormedUriString( "https://test.com?q=%22%7E", UriKind.Absolute) returns false, which is incorrect.

### Reproduction Steps

Demo: https://dotnetfiddle.net/DIc8qw.

### Expected behavior

Uri.IsWellFormedUriString( "https://test.com?q=%22%7E", UriKind.Absolute) should return true

### Actual behavior

Uri.IsWellFormedUriString( "https://test.com?q=%22%7E", UriKind.Absolute) returns false

### Known Workarounds

Replace  %7E with ~ manually.
Uri.IsWellFormedUriString("https://test.com?q=%22~", UriKind.Absolute) is true.

### Configuration

Tried on net6 and 4.7.2.

### Other information

JS (chrome) parses the URL ok:
```js
(new URL("https://test.com?q=%22%7E")).searchParams.get("q")
```
-> `"~`

**Comment by MihaZupan** [comment]
Closing in favour of https://github.com/dotnet/runtime/issues/72632
