### ISSUE TITLE
Performance gap in ImmutableArray loop from sorting the builder

### ISSUE THREAD

**Issue by Djoums** [dotnet/runtime#70927]
Using .Net6 on Windows 10 x64, Benchmark.Net.

In the following benchmark there is a large performance gap between two tests that should be identical.
The gap is triggered by sorting the builder, which should have no effect,

```
private const int COUNT = 1000000;
private ImmutableArray<Element> Imm1 = default;
private ImmutableArray<Element> Imm2 = default;

[GlobalSetup]
public void Initialize()
{
    var rand = new Random(42);
    var builder = ImmutableArray.CreateBuilder<Element>(COUNT);
    for (int i = 0; i < COUNT; i++)
        builder.Add(new Element(rand.Next()));

    Imm1 = builder.ToImmutable();
    builder.Sort(static (a, b) => a.Id.CompareTo(b.Id)); // Remove this line and the gap disappears
    Imm2 = builder.ToImmutable();
}

[Benchmark]
public int TestImm1()
{
    int res = 0;
    foreach (var element in Imm1)
        res ^= element.Id;
    return res;
}

[Benchmark]
public int TestImm2()
{
    int res = 0;
    foreach (var element in Imm2)
        res ^= element.Id;
    return res;
}

private sealed class Element
{
    public int Id { get; }
    public Element(int id) => Id = id;
}
```

The benchmark gives the following result, with test 2 being 3.5 times slower than the first one.

|   Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|----------:|----------:|------:|------:|------:|----------:|
| TestImm1 | 2.065 ms | 0.0243 ms | 0.0228 ms |     - |     - |     - |       2 B |
| TestImm2 | 7.516 ms | 0.0421 ms | 0.0374 ms |     - |     - |     - |       2 B |

**Comment by tfenise** [comment]
I guess sorting the `ImmutableArray` breaks cache locality.

**Comment by Djoums** [comment]
That shouldn't be possible, Sort() uses Array.Sort() under the hood which is in-place, and builder.ToImmutable() creates a fresh new array anyway.

**Comment by tfenise** [comment]
I was talking about the access to `element.Id`. Due to the implementation of the GC, the `Element`s from `new Element(rand.Next())` lie mostly sequentially in the memory. As a result, `foreach (var element in Imm1) res ^= element.Id;` reads memory mostly sequentially, while `foreach (var element in Imm2) res ^= element.Id;` reads memory rather randomly, since `Imm2` is reordered.

**Comment by tfenise** [comment]
If you change `sealed class Element` to `struct Element`, this difference should disappear.

**Comment by Djoums** [comment]
Yes that's what I was testing and you're right it goes away, I didn't  think of the sequentiality of the created objects in memory. That's a tough one to optimize for in a large program.
