### ISSUE TITLE
Inconsistent stack trace with .NET 7 preview 5

### ISSUE THREAD

**Issue by jnyrup** [dotnet/runtime#70940]
### Description

After upgrading from .NET 7 Preview 4 to Preview 5 some unit tests of Fluent Assertions started to fail.

I can't tell exactly where the problem lies, as I haven't been able to create a minimal example yet.
We have a method [`CallerIdentifier.DetermineCallerIdentity`](https://github.com/jnyrup/fluentassertions/blob/net7_issues/Src/FluentAssertions/CallerIdentifier.cs) which uses `new StackTrace()` to extract the name of the variable for which an assertion failed. When our heuristic text parsing fails to determine the variable name it defaults to `"root"`.

With Preview 5 running test in parallel, `CallerIdentifier.DetermineCallerIdentity` returns "`root`" for some tests.
I haven't yet been able to create a minimal example, but I'm continuously updating https://github.com/jnyrup/fluentassertions/tree/net7_issues.

### Reproduction Steps

checkout `https://github.com/jnyrup/fluentassertions/tree/net7_issues`
run `dotnet test Tests/FluentAssertions.Specs/FluentAssertions.Specs.csproj`

### Expected behavior

Both tests should pass for .NET 7.0 like they do for .NET 6.0

### Actual behavior

When running the tests in _parallel_ `Foo` consistently fails.
When running `Foo` alone, it passes.

### Regression?

Using the official .NET 7 preview4 the tests pass.

### Configuration

.NET: .NET 7 Preview 5
OS: Windows 10 19044.1766
Arch: x64

### Other information

The only _directly_ threading related data structured I can tell we use in https://github.com/jnyrup/fluentassertions/tree/net7_issues are `[ThreadStatic]` and `AsyncLocal<T>`.

I'd be happy to try to bisect the change if there are prebuilt .NET runtimes I can download or instructions/pointers about how to build from git and consume it from my test project.

**Comment by jkotas** [comment]
Stacktrace can be missing frames depending on the inlining and tail code optimizations. Are you doing anything special to suppress optimization to guarantee that the frames you are interested in are going to be in the stacktrace?

These optimizations can happen in the background thanks to tiered compilation. It can explain the behavior that you are seeing.

**Comment by jnyrup** [comment]
Thanks for the hints, I narrowed it down to be due to the changes in #67917.

We filter the stack trace based on properties of `StackFrame.GetMethod()`, e.g. if the namespace starts with `"System"`.

For the passing test the stack trace contained `"System.RuntimeMethodHandle.InvokeMethod("`
```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
```

where for the failing test the stack trace contained `"InvokeStub_GenericEnumerableEquivalencyStep.HandleImpl("`.
```
at InvokeStub_GenericEnumerableEquivalencyStep.HandleImpl(Object, Object, IntPtr*)
at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
```

I can't say if this inconsistency is "by design", but in any case I can workaround it like in
https://github.com/steveharter/runtime/blob/2fbc50fe920af55736b39e930b953faca0a7206f/src/coreclr/vm/appdomain.cpp#L1536

**Comment by steveharter** [comment]
> I can't say if this inconsistency is "by design"

I wouldn't say it's "by design" since it's really an implementation detail. Depending on whether IL Emit is available, and whether the methods should be optimized to use IL Emit, the stack will differ.

See also https://github.com/dotnet/runtime/issues/68923 for hiding stack frames.

@jnyrup would hiding stack frames cause issues?

**Comment by jnyrup** [comment]
In our case hiding stack frames from the BCL would not cause issues, as we're only trying to identify stack frames from user code.
