### ISSUE TITLE
Exposing C code to  CoreCLR host

### ISSUE THREAD

**Issue by mingmoe** [dotnet/runtime#70953]
I want to exposing my c code to the CoreCLR host.

This function should work like the `mono_add_internal_call` function in Mono.
```c++
mono_add_internal_call ("Hello::Sample", sample);
```
```C#
using System;
using System.Runtime.CompilerServices;

class Hello {
  [MethodImplAttribute(MethodImplOptions.InternalCall)]
  extern static string Sample ();
}
```

Does CoreCLR have similar functions? (I want to use it in native code,not `P/Invoke`) 

Thanks

**Comment by jkotas** [comment]
You can use C# function pointers with unmanaged calling convention to expose C methods to managed code.

CoreCLR does not support operating on raw object references in non-runtime C code. You still need to marshal the string, just like you would for PInvoke.

**Comment by mingmoe** [comment]
I want to expose C methods to managed code by using CoreCLR c headers(such as `nethost.h`).

Because the CoreCLR host is created by my c code,no execute `dotnet.exe`.

PInvoke appears to load dlls from the filesystem.

But the CoreCLR is created by my program,so the native code is also in my program(RAM).

How to do that?

@jkotas

**Comment by jkotas** [comment]
Start your managed component using `load_assembly_and_get_function_pointer` API and pass array of pointers to your C methods as one of the arguments of your component entrypoint.

We have a hosting sample here: https://github.com/dotnet/samples/tree/main/core/hosting/src/NativeHost . 

The arguments to the component entrypoint are passed using `LibArgs` structure in this sample: 
https://github.com/dotnet/samples/blob/main/core/hosting/src/NativeHost/nativehost.cpp#L113-L117
https://github.com/dotnet/samples/blob/main/core/hosting/src/DotNetLib/Lib.cs#L11-L15

Adding a function pointer argument that returns pointer to unmanaged string can look like this:
```
public struct LibArgs
{
      public IntPtr Message;
      public int Number;
      public delegate* unmanaged<char*>SampleFuncPtr;
}
```
