### ISSUE TITLE
 Could not write lines to file Microsoft.NET.HostModel.ComHost.Tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#70969]
Intermittent build error hit by `Installer Build and Test coreclr windows_x64 Release` in CI:

```
022-06-19T18:00:25.9981639Z   Running tests: D:\a\_work\1\s\artifacts\bin\AppHost.Bundle.Tests\Release\net7.0\AppHost.Bundle.Tests.dll [net7.0|x64]
2022-06-19T18:00:26.8040811Z   Running tests: D:\a\_work\1\s\artifacts\bin\Microsoft.NET.HostModel.AppHost.Tests\Release\net7.0\Microsoft.NET.HostModel.AppHost.Tests.dll [net7.0|x64]
2022-06-19T18:00:27.0021440Z   Running tests: D:\a\_work\1\s\artifacts\bin\Microsoft.NET.HostModel.ComHost.Tests\Release\net7.0\Microsoft.NET.HostModel.ComHost.Tests.dll [net7.0|x64]
2022-06-19T18:00:41.7216702Z   Tests succeeded: D:\a\_work\1\s\artifacts\bin\Microsoft.NET.HostModel.AppHost.Tests\Release\net7.0\Microsoft.NET.HostModel.AppHost.Tests.dll [net7.0|x64]
2022-06-19T18:01:10.6831061Z D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22310.1\tools\VSTest.targets(55,5): error MSB3491: Could not write lines to file "D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log". The process cannot access the file 'D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log' because it is being used by another process. [D:\a\_work\1\s\src\installer\tests\Microsoft.NET.HostModel.Tests\Microsoft.NET.HostModel.ComHost.Tests\Microsoft.NET.HostModel.ComHost.Tests.csproj]
2022-06-19T18:01:10.7438162Z ##[error].packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22310.1\tools\VSTest.targets(55,5): error MSB3491: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not write lines to file "D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log". The process cannot access the file 'D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log' because it is being used by another process.
2022-06-19T18:01:10.7456526Z   Running tests: D:\a\_work\1\s\artifacts\bin\Microsoft.NET.HostModel.Bundle.Tests\Release\net7.0\Microsoft.NET.HostModel.Bundle.Tests.dll [net7.0|x64]
2022-06-19T18:12:12.3099944Z   Tests succeeded: D:\a\_work\1\s\artifacts\bin\Microsoft.NET.HostModel.Bundle.Tests\Release\net7.0\Microsoft.NET.HostModel.Bundle.Tests.dll [net7.0|x64]
```

```json
{
  "ErrorMessage": "error MSB3491: Could not write lines to file \"D:\\a\\_work\\1\\s\\artifacts\\log\\Release\\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log\"",
  "BuildRetry": false
}
```

### Report
|Build|Definition|Step Name|Console log|
|---|---|---|---|
|[1896046](https://dev.azure.com/dnceng/public/_build/results?buildId=1896046)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1896046/logs/2334)
|[1894514](https://dev.azure.com/dnceng/public/_build/results?buildId=1894514)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894514/logs/2326)
|[1893340](https://dev.azure.com/dnceng/public/_build/results?buildId=1893340)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1893340/logs/1327)
|[1891752](https://dev.azure.com/dnceng/public/_build/results?buildId=1891752)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1891752/logs/2288)
|[1890865](https://dev.azure.com/dnceng/public/_build/results?buildId=1890865)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1890865/logs/1458)
|[1886297](https://dev.azure.com/dnceng/public/_build/results?buildId=1886297)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1886297/logs/1306)
|[1886561](https://dev.azure.com/dnceng/public/_build/results?buildId=1886561)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1886561/logs/1501)
|[1886741](https://dev.azure.com/dnceng/public/_build/results?buildId=1886741)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1886741/logs/1417)
|[1886981](https://dev.azure.com/dnceng/public/_build/results?buildId=1886981)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1886981/logs/1311)
|[1892083](https://dev.azure.com/dnceng/public/_build/results?buildId=1892083)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1892083/logs/2247)
|[1892899](https://dev.azure.com/dnceng/public/_build/results?buildId=1892899)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1892899/logs/1304)
|[1892886](https://dev.azure.com/dnceng/public/_build/results?buildId=1892886)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1892886/logs/1466)
|[1893235](https://dev.azure.com/dnceng/public/_build/results?buildId=1893235)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1893235/logs/1327)
|[1893112](https://dev.azure.com/dnceng/public/_build/results?buildId=1893112)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1893112/logs/2213)
|[1893373](https://dev.azure.com/dnceng/public/_build/results?buildId=1893373)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1893373/logs/2470)
|[1894291](https://dev.azure.com/dnceng/public/_build/results?buildId=1894291)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894291/logs/1332)
|[1894338](https://dev.azure.com/dnceng/public/_build/results?buildId=1894338)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894338/logs/1486)
|[1894384](https://dev.azure.com/dnceng/public/_build/results?buildId=1894384)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894384/logs/1513)
|[1894521](https://dev.azure.com/dnceng/public/_build/results?buildId=1894521)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894521/logs/1473)
|[1894760](https://dev.azure.com/dnceng/public/_build/results?buildId=1894760)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1894760/logs/1445)
|[1895037](https://dev.azure.com/dnceng/public/_build/results?buildId=1895037)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1895037/logs/1326)
|[1895247](https://dev.azure.com/dnceng/public/_build/results?buildId=1895247)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1895247/logs/1320)
|[1895305](https://dev.azure.com/dnceng/public/_build/results?buildId=1895305)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1895305/logs/1455)
|[1896134](https://dev.azure.com/dnceng/public/_build/results?buildId=1896134)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1896134/logs/1332)
|[1896006](https://dev.azure.com/dnceng/public/_build/results?buildId=1896006)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1896006/logs/2278)
|[1896299](https://dev.azure.com/dnceng/public/_build/results?buildId=1896299)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1896299/logs/1332)
|[1885715](https://dev.azure.com/dnceng/public/_build/results?buildId=1885715)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1885715/logs/2401)
|[1884639](https://dev.azure.com/dnceng/public/_build/results?buildId=1884639)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1884639/logs/2291)
|[1884836](https://dev.azure.com/dnceng/public/_build/results?buildId=1884836)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1884836/logs/2289)
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|22|29|

**Comment by jkotas** [comment]
Failed in #70956. Log https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1833271/logs/1442

**Comment by jkotas** [comment]
Failed in #70944. Log https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1832671/logs/2290

**Comment by agocke** [comment]
@elinor-fung Could this be caused by recent changes?

**Comment by elinor-fung** [comment]
We did switch to the arcade infrastructure for using `dotnet test` (https://github.com/dotnet/runtime/pull/69340).

We just rely on that infrastructure to redirect the output to a log file:
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/VSTest.targets#L30

And then append more information to the file after running the command (which is where it is failing):
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/VSTest.targets#L55

I'm not sure why the file would still be in use after the Exec finishes.

**Comment by elinor-fung** [comment]
Related: https://github.com/dotnet/sdk/issues/10062

It'd be good to figure out why it is happening, but maybe it could be mitigated by using [`ConsoleOutput`](https://docs.microsoft.com/visualstudio/msbuild/exec-task#parameters) to capture the output (instead of the `>` redirect) when running the test command and then writing all the lines in one shot.
https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/src/Microsoft.DotNet.Arcade.Sdk/tools/VSTest.targets#L43-L50

**Comment by eerhardt** [comment]
Happened here as well: https://dev.azure.com/dnceng/public/_build/results?buildId=1839229&view=logs&j=e36cdb78-1b23-5f53-5d15-e931194c7d32&t=5f3cc2c3-b299-5f57-0006-9e48b00ce7cd&l=735

**Comment by agocke** [comment]
I'm trying to take a look locally and see if we can find a solution

**Comment by danmoseley** [comment]
> It'd be good to figure out why it is happening, but maybe it could be mitigated by using [ConsoleOutput](https://docs.microsoft.com/visualstudio/msbuild/exec-task#parameters) to capture the output (instead of the > redirect) when running the test command and then writing all the lines in one shot.

Another option perhaps is to write the command to the file first, then change the `>` to `>>` when subsequently writing the test output.

**Comment by karelz** [comment]
https://github.com/dotnet/arcade/issues/9864 has a fix, so waiting for it to propagate into runtime repo ...

**Comment by MattGal** [comment]
> [dotnet/arcade#9864](https://github.com/dotnet/arcade/issues/9864) has a fix, so waiting for it to propagate into runtime repo ...

Fix is propagated and I'm watching it; will port to other branches if it hasn't reproduced by tomorrow.

**Comment by agocke** [comment]
It looks like this is working well, no failures since Thursday.
