### ISSUE TITLE
System.DllNotFoundException during p/invoke shows incorrect error message. (Linux)

### ISSUE THREAD

**Issue by HJLeee** [dotnet/runtime#70963]
### Description

When trying to make a p/invoke call to faulty native library, runtime throws `System.DllNotFoundException`, but it gives incorrect message.

For example, the native library is compiled for 32 bit env and the `dlerror()` message is `wrong ELF class: ELFCLASS32`.
```
$ file libpinvoke.so
libpinvoke.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=8741ac5fbfe5928b8d201d57f03870457d25d7a5, not stripped

$ ./dlerror.out
./libpinvoke.so: wrong ELF class: ELFCLASS32
```

Currently, dotnet runtime shows `cannot open shared object file: No such file or directory` for the same library.
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libpinvoke.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibpinvoke.so: cannot open shared object file: No such file or directory
```

This often makes the developers try to fix the library name in the code so that `liblibpinvoke.so` can be `libpinvoke.so`. But this time they get this.
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'pinvoke.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpinvoke.so: cannot open shared object file: No such file or directory
```

This is because previous error message is overridden by following error message during multiple attempts dealing with p/invoke library prefix/suffix/name variations.
I think it's better not to give `dlerror()` message for `System.DllNotFoundException` and let the developers try LD_DEBUG.

### Reproduction Steps

Compile p/invoke native library with 32 bit env. and try to use it on 64 bit env.

### Expected behavior

It shows `wrong ELF class` message.

### Actual behavior

`No such file or directory` message for a internally generated library name.

**Comment by danmoseley** [comment]
Is dlerror() message never useful? Can we retain it when it is useful? The more (accurate) info in these messages the better as it is hard for others to help with such problems as they are often configuration specific.

Cc @AaronRobinsonMSFT

**Comment by HJLeee** [comment]
I think it is useful if we return error message for dlopen() attempt that exactly matches the library name.
