### ISSUE TITLE
Assert in System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_*

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#70981]
Affected tests:
- **ConnectWithRevocation_WithCallback** - `System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback`
    - Frequency in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22system.net.security.tests.certificatevalidationremoteserver.connectwithrevocation_withcallback%22) as of 8/25: **12x** runs affected (all **OSX.1200**.Amd64.Open on Mono and CoreCLR)
        - first occurrence on **8/15** - PR [1945162](https://runfo.azurewebsites.net/view/build/?number=1945162)
        - last occurrence on 8/23 - the test was **disabled on OSX** in main (8.0) in PR #74168 and in 7.0 (RC2) in PR #74483
            - Note: Updated bug the test is disabled against to this one in PR #74561 on 8/25
- **ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp** - `System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp`
    - Frequency in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~30%20definition%3Aruntime-extra-platforms%20name%3A%22system.net.security.tests.certificatevalidationremoteserver.connectwithrevocation_servercertwithoutcontext_nostapledocsp%22) - see details below
    - Test **disabled on Debian10** in main (7.0) in PR #72634 on 7/22
    - Test **disabled on NativeAOT** in main (8.0) in PR #74561 and in 7.0 (RC2) in PR #74606 on 8/25

Frequency: **ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp**
- Error: `Assert.Contains() Failure Not found: RevocationStatusUnknown In value: X509ChainStatusFlags[] [Revoked]`

Day | Run | Details
-- | -- | --
8/24 | Report made |
8/24 | Rolling run [1964517](https://runfo.azurewebsites.net/view/build/?number=1964517) (7.0-rc1) | net7.0-Linux-Release-arm64-NativeAOT_Release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open
8/23 | Rolling run [1963307](https://runfo.azurewebsites.net/view/build/?number=1963307) (7.0) | net7.0-Linux-Release-arm64-NativeAOT_Release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open
8/19 | Rolling run [1955773](https://runfo.azurewebsites.net/view/build/?number=1955773) (7.0) | net7.0-Linux-Release-arm64-NativeAOT_Release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open
7/24-8/18 | No hits |

Test failure in **ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp** from 6/20 on Debian10 (Mono)
- Full test name: System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp

```
    System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp [FAIL]
      Assert.Contains() Failure
      Not found: (filter expression)
      In value:  X509ChainStatus[] [System.Security.Cryptography.X509Certificates.X509ChainStatus]
      Stack Trace:
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(275,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.<ConnectWithRevocation_WithCallback_Core>g__CertificateValidationCallback|6_0(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Protocol.cs(984,0): at System.Net.Security.SslStream.VerifyRemoteCertificate(RemoteCertificateValidationCallback remoteCertValidationCallback, SslCertificateTrust trust, ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(512,0): at System.Net.Security.SslStream.CompleteHandshake(ProtocolToken& alertToken, SslPolicyErrors& sslPolicyErrors, X509ChainStatusFlags& chainStatus)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(525,0): at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs(338,0): at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__146`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(228,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(229,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(229,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(229,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs(229,0): at System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_WithCallback_Core(X509RevocationMode revocationMode, Nullable`1 offlineContext)
        --- End of stack trace from previous location ---
```

Failures:
- [1832139](https://runfo.azurewebsites.net/view/build/?number=1832139) rolling build (6/18 AM)

- 6/20:
    - 4 failures in [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22system.net.security.tests.certificatevalidationremoteserver.connectwithrevocation_servercertwithoutcontext_nostapledocsp%22)
    - 9 failures in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22system.net.security.tests.certificatevalidationremoteserver.connectwithrevocation_servercertwithoutcontext_nostapledocsp%22) (2 Rolling test runs)
        - Note: Previously failed on different exception
        - First failure on 6/4
    - Platforms:
        - 2x Debug: `net7.0-Linux-Release-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673`
        - 7x Release: `net7.0-Linux-Debug-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673`

```kusto
let failedTests = (methodName : string, includePR : bool, messageSubstr: string, includePassedOnRerun : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName startswith "System.Net" 
    | where includePassedOnRerun or (Outcome == 'Failed')
    | extend startOfTestName = indexof_regex(TestName, @"[^.]+$")
    | extend Method = substring(TestName, startOfTestName)
    | extend Type = substring(TestName, 0, startOfTestName - 1)
    | project-away startOfTestName
    | where Method == methodName
    | where Message contains messageSubstr
    | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId
    | extend PropertiesJson = parse_json(Properties)
    | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
    | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
    | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
    | extend Architecture = PropertiesJson.architecture
    | extend Scenario = iif(isempty(PropertiesJson.scenario), "--", PropertiesJson.scenario)
    //| extend DefinitionName = PropertiesJson.DefinitionName
    | project-away PropertiesJson
};
failedTests('ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp', true, '', true);
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by wfurt** [comment]
It seems like all failures are on same Debian 10
```
helixbot@d21a8c6236ea:/$ openssl version -a
OpenSSL 1.1.1d  10 Sep 2019
```

I don't know if this is sealed but update to newer OpenSSL is available.

**Comment by rzikm** [comment]
Updating to latest openssl does not seem to fix it

**Comment by karelz** [comment]
@lewing can you please help triage it?

**Comment by danmoseley** [comment]
just curious how is this @lewing related? it seems not wasm crypto.

@dotnet/area-system-security as for any `blocking-clean-ci` test can we please disable this promptly if there's no immediate fix.

**Comment by karelz** [comment]
Looks like @bartonjs disabled the test already on Debian 10 (I added disabled-test label). I assume we might disable it for Mono interpreter as well, or perhaps entirely.

@bartonjs should we be concerned about the test failures? It is a new feature?
Would it be ok if we disable the test entirely as problematic?

**Comment by karelz** [comment]
Not blocking clean CI anymore, the tests were disabled - removing the label.

**Comment by wfurt** [comment]
I may be missing something but the test does not look right to me @bartonjs. 
I can make predictably fail on Ubuntu e.g. there is IMHO nothing special about Debian 10 - just random timing. 

Here is what I see:
The client asks for status. That was unconditionally enabled in #73627
The server part uses `offlineContext: null`. That will make SslStream to create context from  plain cert using default - e.g. `offline: false`.
So the server would strata processing OCSP and when client asks, it sends back revoked status. 

```
      System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp [STARTING]
      System.Net.Security.Tests.CertificateValidationRemoteServer.ConnectWithRevocation_ServerCertWithoutContext_NoStapledOcsp [FAIL]
        Assert.Contains() Failure
        Not found: RevocationStatusUnknown
        In value:  X509ChainStatusFlags[] [Revoked]
        Stack Trace:
```

I forced Tls12 to make it more visible e.g. the CertificateStatus message goes out cleartext. 

[ocsp3.pcapng.zip](https://github.com/dotnet/runtime/files/10772367/ocsp3.pcapng.zip)

let me know. (or take it)
