### ISSUE TITLE
Tests failed: Wasm.Build.Tests.BlazorWasmBuildPublishTests due to SIGKILL

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#70985]
Failing tests: Wasm.Build.Tests.BlazorWasmBuildPublishTests due to SIGKILL

Affected tests:
- WithNativeReference_AOTInProjectFile -- `Wasm.Build.Tests.BlazorWasmBuildPublishTests.WithNativeReference_AOTInProjectFile`
- WithNativeReference_AOTOnCommandLine -- `Wasm.Build.Tests.BlazorWasmBuildPublishTests.WithNativeReference_AOTOnCommandLine`
- NativeBuild_WithDeployOnBuild_UsedByVS -- `Wasm.Build.Tests.BlazorWasmBuildPublishTests.NativeBuild_WithDeployOnBuild_UsedByVS`

Failures as of 6/20:
- WithNativeReference_AOTInProjectFile
    - 16 failures (3 in Rolling) in [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.withnativereference_aotinprojectfile%22) / 42 failures (4 in Rolling) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.withnativereference_aotinprojectfile%22)
- WithNativeReference_AOTOnCommandLine
    - 16 failures (3 in Rolling) in [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.withnativereference_aotoncommandline%22) / 41 failures (4 in Rolling) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.withnativereference_aotoncommandline%22)
- NativeBuild_WithDeployOnBuild_UsedByVS
    - 25 failures (2 in Rolling) in [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime%20name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.nativebuild_withdeployonbuild_usedbyvs%22) / 50 failures (4 in Rolling) in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22wasm.build.tests.blazorwasmbuildpublishtests.nativebuild_withdeployonbuild_usedbyvs%22)

Platform: net7.0-Browser-Release-wasm-Mono_Release_Linux-BuildWasmApps-Ubuntu.1804.Amd64.Open

Output example:
```
Wasm.Build.Tests.BlazorWasmBuildPublishTests.WithNativeReference_AOTOnCommandLine:

[] emcc : error : '/datadisks/disk1/work/B58909DD/w/A8850950/e/dotnet-workload/packs/Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.linux-x64/7.0.0-preview.6.22281.1/tools/bin/wasm-emscripten-finalize -g --dyncalls-i64 --dwarf /datadisks/disk1/work/B58909DD/w/A8850950/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm -o /datadisks/disk1/work/B58909DD/w/A8850950/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm --detect-features' failed (received SIGKILL (-9)) [/datadisks/disk1/work/B58909DD/w/A8850950/e/blz_nativeref_aot_Debug/blz_nativeref_aot_Debug.csproj]
[] /datadisks/disk1/work/B58909DD/w/A8850950/e/dotnet-workload/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/7.0.0-ci/Sdk/WasmApp.Native.targets(424,5): error MSB3073: The command "emcc "@/datadisks/disk1/work/B58909DD/w/A8850950/e/dotnet-workload/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/7.0.0-ci/runtimes/browser-wasm/native/src/emcc-default.rsp" "@/datadisks/disk1/work/B58909DD/w/A8850950/e/dotnet-workload/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/7.0.0-ci/runtimes/browser-wasm/native/src/emcc-link.rsp" "@/datadisks/disk1/work/B58909DD/w/A8850950/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/emcc-link.rsp"" exited with code 1. [/datadisks/disk1/work/B58909DD/w/A8850950/e/blz_nativeref_aot_Debug/blz_nativeref_aot_Debug.csproj]
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by karelz** [comment]
Given the high impact on CI, we should consider disabling the tests.

**Comment by agocke** [comment]
@radical Were these tests disabled? If so we can remove the `blocking-clean-ci` label

**Comment by stephentoub** [comment]
I'm still hitting this:
https://github.com/dotnet/runtime/issues/78893
Are these tests different?

**Comment by radical** [comment]
Yeah, these tests are different. It's the blazor AOT build is getting OOMkilled. We have lot of other tests building blazor projects with AOT too, but they work fine. And even these fails some times, so the memory usage likely skirts close to the edge most of the time.

But I will try to see what we can do about it.

**Comment by radical** [comment]
Newly failing tests:

- [ ]  Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS
- [ ] Wasm.Build.Tests.Blazor.MiscTests.DefaultTemplate_AOT_InProjectFile
