### ISSUE TITLE
[API Proposal]: System.Net.HttpStatusCode.UnprocessableContent

### ISSUE THREAD

**Issue by khellang** [dotnet/runtime#70996]
### Background and motivation

Now that [RFC 9110 - HTTP Semantics](https://www.rfc-editor.org/rfc/rfc9110.html) is official, with the inclusion of the `422 Unprocessable Content` status code, I'd like to propose the following API.

There's already precedent for adding HTTP status aliases after standardization;

- 300 - `HttpStatusCode.MultipleChoices` and `HttpStatusCode.Ambiguous`
- 301 - `HttpStatusCode.Moved` and `HttpStatusCode.MovedPermanently`
- 302 - `HttpStatusCode.Found` and `HttpStatusCode.Redirect`
- 303 - `HttpStatusCode.SeeOther` and `HttpStatusCode.RedirectMethod`
- 307 - `HttpStatusCode.TemporaryRedirect` and `HttpStatusCode.RedirectKeepVerb`

### API Proposal

```diff
namespace System.Net;

public enum HttpStatusCode
{
+    UnprocessableContent = 422,
}
```

### API Usage

Taken from https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-6.0 🤢 

```csharp
HttpWebRequest httpReq = (HttpWebRequest)WebRequest.Create("http://www.contoso.com");
httpReq.AllowAutoRedirect = false;

HttpWebResponse httpRes = (HttpWebResponse)httpReq.GetResponse();

if (httpRes.StatusCode==HttpStatusCode.UnprocessableContent)
{
    // Code for unprocessable content goes here.
}

// Close the response.
httpRes.Close();
```

### Risks

None

**Comment by karelz** [comment]
Triage: We are ok with that. We would take a contribution ;)

**Comment by terrajobst** [comment]
* Looks good as proposed

```C#
namespace System.Net;

public enum HttpStatusCode
{
    // UnprocessableEntity = 422
    UnprocessableContent = 422
}
```
