### ISSUE TITLE
RegexOptions.Compiled impacts Android startup

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#71007]
### Description

Reviewing a [customer issue](https://github.com/jonathanpeppers/maui-profiling/issues/16), we noticed usage of `RegexOptions.Compiled` impacts startup quite a bit:

![image](https://user-images.githubusercontent.com/840039/174644649-99e5ae39-4952-4f7c-acec-42533c644035.png)

This was coming from the AppCenter SDK in the customer's app:

https://github.com/microsoft/appcenter-sdk-dotnet/blob/b19ec99e16e554eb1382342b2852b16f7d8f0084/SDK/AppCenter/Microsoft.AppCenter.Shared/AppCenter.cs#L26

This shows up as a regression from Xamarin.Android -> .NET 6, because `RegexOptions.Compiled` was not implemented at all in mono/mono.

The question here, is how do we get the previous behavior from mono/mono? Is there a way to toggle `RuntimeFeature.IsDynamicCodeCompiled`?

https://github.com/dotnet/runtime/blob/807d0916c5205d75ecb04809f8106a3caa46bbe4/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs#L105

If there is a way to toggle `RuntimeFeature.IsDynamicCodeCompiled`, should we consider turning on this flag by default on Android? I've found System.Reflection.Emit to be very impactful to startup.

### Reproduction Steps

1. `dotnet new android`
2. Open `MainActivity.cs` and put `_ = new Regex(@"([^;=]+)=([^;]+)(?:;\s*)?", RegexOptions.Compiled);` in the `OnCreate()` method.
3. Build/run with `dotnet build -c Release -t:Run`

### Expected behavior

`RegexOptions.Compiled` doesn't have a significant impact to Android startup. (Or we have a feature flag to turn it off)

### Actual behavior

`RegexOptions.Compiled` has a significant impact to Android startup.

### Regression?

From a customer's perspective they might say this is startup performance regression from Xamarin.Android to .NET 6.

### Known Workarounds

Don't use `RegexOptions.Compiled`, use `Normal`.

### Configuration

I tested this with the .NET 6.0.400-preview.22301.10 SDK, and the SR 1 version of .NET MAUI.

### Other information

`dotnet trace` output: [regexoptions.compiled.zip](https://github.com/dotnet/runtime/files/8942304/regexoptions.compiled.zip)

**Comment by stephentoub** [comment]
RegexOptions.Compiled is a tradeoff between startup overhead and throughput: it adds overhead to constructing the Regex in exchange for making regexes execute faster.  Are you seeing this construction cost increase but throughput not also increase?  If they both go up, then the opt-in flag is doing what it's supposed to do, and if a customer doesn't want to tradeoff that construction overhead for throughput, they shouldn't be setting Compiled.

**Comment by danmoseley** [comment]
Just curious, why do they not pass it when targeting .NET Standard?
```
#if NETSTANDARD
        static readonly Regex _secretsRegex = new Regex(SecretsPattern);
#else
        static readonly Regex _secretsRegex = new Regex(SecretsPattern, RegexOptions.Compiled);
#endif
```

**Comment by jonathanpeppers** [comment]
If you look at blame, it doesn't actually give much detail:

https://github.com/microsoft/appcenter-sdk-dotnet/commit/70f79440f0ca6be28108308e9d0faef46c32b693

I'm not sure what issue they're trying to solve here either. It seems like the old code would have worked in Xamarin.Android in 2019 to me?

**Comment by danmoseley** [comment]
My guess is that they thought it was still broken. I think the to-do here is to just pass on Stephen's guidance. Startup time, throughput, disk size - pick two!

**Comment by jonathanpeppers** [comment]
On Android, we would pretty much never want throughput for anything. So that is why the default setting might be interesting.

**Comment by steveisok** [comment]
If we were to do anything, I think it would have to be through a runtime feature switch.  @jonathanpeppers, how significant are we talking vs what was in mono/mono?

**Comment by teo-tsirpanis** [comment]
> Just curious, why do they not pass it when targeting .NET Standard?

@danmoseley they are targeting .NET Standard 1.0 only, which does not have `Compiled`.

**Comment by jonathanpeppers** [comment]
We discussed this some, and we think:
1. Don't use `RegexOptions.Compile` on mobile, unless you want it for throughput
2. We should be careful about `RuntimeFeature.IsDynamicCodeCompiled` and its use for changes like: https://github.com/dotnet/runtime/pull/69575

If we implement the same System.Reflection changes for Mono, we should test the impact on Android startup. Let me know if I can help with that.

We can close this for now, thanks.

**Comment by jonathanpeppers** [comment]
It appears the new `Regex` APIs save about ~93.5ms on a Pixel 5 in a "hello world" Android app:

https://github.com/jonathanpeppers/AndroidRegex

I'm working on a blog post that will mention this in detail.

**Comment by stephentoub** [comment]
> It appears the new Regex APIs save about ~93.5ms of startup time on a Pixel 5 in a "hello world" Android app:

Nice!

**Comment by danmoseley** [comment]
@jonathanpeppers I see the flame diagram there for "before", I'm curious what the flame diagram looks like "after" (if you collected it)

**Comment by jonathanpeppers** [comment]
Ah yes, so `MainActivity..cctor` is now so fast it is completely gone from the trace.

I added the `.speedscope`/`.nettrace` files and more screenshots: https://github.com/jonathanpeppers/AndroidRegex

**Comment by danmoseley** [comment]
If I read right, the ctor was 174ms and IsMatch another 49ms. Now the ctor is negligible (because source gen) and IsMatch is only 6ms (because it is smarter about finding there is no possible start position)

So I think I'd expect an improvement of over 200ms, not 93.5 ms? 
Also I'm curious what is causing the CompileMethod in the newer IsMatch.

**Comment by jonathanpeppers** [comment]
My general observation, is these timings are a bit slower when traced -- especially on a mobile device running Mono. Maybe @lateralusX knows if there is some amount of overhead?

I normally test with & without tracing to double-check things.

**Comment by jonathanpeppers** [comment]
> Also I'm curious what is causing the CompileMethod in the newer IsMatch.

`RuntimeHelpers.CompileMethod()` is a placeholder for time spent in the runtime, so it's likely JIT'ing this method, but it could also be loading additional assemblies, etc.

**Comment by lateralusX** [comment]
> My general observation, is these timings are a bit slower when traced -- especially on a mobile device running Mono. Maybe @lateralusX knows if there is some amount of overhead?
> 
> I normally test with & without tracing to double-check things.

If you run sampling it will impact process since part of sampling includes a STW (stop the world for every sample) so it will affect timers. If you don't run with sampling, the impact should be minimal.

**Comment by lateralusX** [comment]
> > Also I'm curious what is causing the CompileMethod in the newer IsMatch.
> 
> `RuntimeHelpers.CompileMethod()` is a placeholder for time spent in the runtime, so it's likely JIT'ing this method, but it could also be loading additional assemblies, etc.

Jupp, CompileMethod is a place holder when runtime needs to JIT compile a method. Part of JIT compile a method might results in the need to load additional types (assemblies) and potential do some other runtime work, but the trigger is need to JIT or load an AOT:ed method.
