### ISSUE TITLE
Enumerable.Chunk remarks slightly incorrect

### ISSUE THREAD

**Issue by Bouke** [dotnet/runtime#71016]
https://github.com/dotnet/runtime/blob/d6d28e40b34ae98f94a9436e7c1d54fd7370676d/src/libraries/System.Linq/src/System/Linq/Chunk.cs#L15

This will only hold when `source.Count() > size`, otherwise the first chunk will be of size `source.Count()`.

Example:

```cs
new[] { 0 }.Chunk(3); // yields [[0]]
```

**Comment by jkoritzinsky** [comment]
Technically the comment is correct, as when `source.Count() < size`, then the first chunk is the last chunk, the one chunk that can be less than size `size`.

**Comment by Bouke** [comment]
I was stuck with the concept of first != last. Yeah rereading I think it is fine as well.
