### ISSUE TITLE
TestKeyTransKeyEncryptionAlgorithm_RoundTrip test fails for .NET Framework

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#71024]
Configuration: .NET Framework Windows 11/22000.675

The TestKeyTransKeyEncryptionAlgorithm_RoundTrip test is failing for me. Reproduces with commit e2cddabc4cc7b8f646472728ada658c922dfb001 (the commit is likely irrelevant, just giving a place to start):

<pre>
[xUnit.net 00:00:02.38]     System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.TestKeyTransKeyEncryptionAlgorithm_RoundTrip [FAIL]
  Failed System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.TestKeyTransKeyEncryptionAlgorithm_RoundTrip [11 ms]
  Error Message:
   Assert.Equal() Failure
                             ↓ (pos 19)
Expected: 1.2.840.113549.1.1.1
Actual:   1.2.840.113549.1.1.7
                             ↑ (pos 19)
  Stack Trace:
     at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyTransRecipientInfoTests.TestKeyTransKeyEncryptionAlgorithm_RoundTrip() in D:\code\personal\runtime\src\libraries\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\KeyTransRecipientInfoTests.cs:line 163
</pre>

The test is passing for me in .NET 7 configurations, it's only failing for the `net48` test configuration.

**Comment by vcsjones** [comment]
@bartonjs are you able to reproduce this? If so, are you aware of any changes in .NET Framework or Windows that would cause it default to OAEP instead of PKCS#1?

**Comment by bartonjs** [comment]
```
  ----- start Mon 06/27/2022 16:35:11.29 ===============  To repro directly: ==
  ===================================================
  pushd C:\git\bartonjs\runtime.2\artifacts\bin\System.Security.Cryptography.Pk
  cs.Tests\Debug\net48\
  xunit.console.exe System.Security.Cryptography.Pkcs.Tests.dll -xml testResult
  s.xml -nologo -notrait category=OuterLoop -notrait category=failing
  popd
  =============================================================================
  ==============================
    Discovering: System.Security.Cryptography.Pkcs.Tests (app domain = on [no s
  hadow copy], method display = ClassAndMethod, method display options = None)
    Discovered:  System.Security.Cryptography.Pkcs.Tests (found 314 of 383 test
   cases)
    Starting:    System.Security.Cryptography.Pkcs.Tests (parallel test collect
  ions = on, max threads = 12)
      System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.KeyAgreeRecipie
  ntInfoTests.TestKeyAgreement_PlatformNotSupported [SKIP]
        Condition(s) not met: "DoesNotSupportDiffieHellman"
      System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsi
  ngCertWithPrivateKey.DecryptEnvelopedOctetStringWithIndefiniteLength [SKIP]
        Condition(s) not met: "SupportsIndefiniteLengthEncoding"
      System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTestsUsi
  ngCertWithPrivateKey.DecryptEnvelopedEmptyOctetStringWithIndefiniteLength [SK
  IP]
        Condition(s) not met: "SupportsIndefiniteLengthEncoding"
    Finished:    System.Security.Cryptography.Pkcs.Tests
  === TEST EXECUTION SUMMARY ===
     System.Security.Cryptography.Pkcs.Tests  Total: 356, Errors: 0, Failed: 0,
   Skipped: 3, Time: 0.957s
  ----- end Mon 06/27/2022 16:35:13.19 ----- exit code 0 ----------------------
  ------------------------------------
```

No repro  (launched with `dotnet msbuild /t:Test`).

> If so, are you aware of any changes in .NET Framework or Windows that would cause it default to OAEP instead of PKCS#1?

Not off the top of my head.  (I thought there was a retargeting change, but that's just for the content encryption algorithm, not the key encryption algorithm).

On NetFX there's a razor edge condition where it routes the work to Windows PKCS7 routines or Windows CMS routines.  The latter requires a key encryption algorithm, which .NET helpfully fills in with the certificate public key algorithm, so it picks RSAES-PKCS1; the former probably uses a regkey to decide OAEP vs PKCS1 for RSA keys.

**Comment by vcsjones** [comment]
This is... odd. I can consistently reproduce the failure but... if CI isn't hitting it, and you're not hitting it... 🤷
