### ISSUE TITLE
Possible regression: ConfigurationBinder cannot bind private properties of base classes

### ISSUE THREAD

**Issue by lateapexearlyspeed** [dotnet/runtime#71040]
### Description

In recent main branch, I found seems ConfigurationBinder cannot bind private properties of base classes, but before that, it can (for example .net 3, 5, 6).

In .net 3, 5, 6:
![image](https://user-images.githubusercontent.com/72254037/174701982-4ff6c35a-cd4e-4d84-a972-5ff127e81452.png)

Recent main branch (I add an test case to show result):
![image](https://user-images.githubusercontent.com/72254037/174702461-4f7b5245-e22d-42a9-a96a-ca6e28fee63d.png)

```csharp
        [Fact]
        public void CanBindPrivatePropertiesFromBaseClass()
        {
            ConfigurationBuilder configurationBuilder = new();
            configurationBuilder.AddInMemoryCollection(new Dictionary<string, string>
            {
                { "PrivateProperty", "a" }
            });
            IConfiguration config = configurationBuilder.Build();

            var test = new ClassOverridingVirtualProperty();
            config.Bind(test, b => b.BindNonPublicProperties = true);
            Assert.Equal("a", test.ExposePrivatePropertyValue());
        }

        public class BaseClassWithVirtualProperty
        {
            private string? PrivateProperty { get; set; }

            public string? ExposePrivatePropertyValue() => PrivateProperty;
        }

        public class ClassOverridingVirtualProperty : BaseClassWithVirtualProperty
        {
        }
```

I raised [PR](https://github.com/dotnet/runtime/pull/71039) to try to fix that, meantime can handle virtual properties.

### Reproduction Steps

As above.

### Expected behavior

`ConfigurationBinder` may should be able to bind private properties of base classes.

### Actual behavior

`ConfigurationBinder` cannot bind private properties of base classes in recent main branch.

### Regression?

Yes, it did.

### Configuration

Found this from main branch with commit version: 2ce8130f4bf4b02393b95719edb0f9d5c6ee1776, at least.

### Other information

I raised [PR](https://github.com/dotnet/runtime/pull/71039) to try to fix that, meantime can handle virtual properties.

**Comment by eerhardt** [comment]
cc @pedrobsaila. Looks like this might be a regression from #70592.

**Comment by lateapexearlyspeed** [comment]
@eerhardt Thanks. Yes I noticed that PR before I raise my PR to fix. In short, I turn to keep using loop to retrieve all layers of properties (as .net 3/5/6) to be able to get also private properties (I guess this is reason to loop before). Meantime take care virtual and non virtual ones (even if with same names). Please review, thanks!

**Comment by lateapexearlyspeed** [comment]
Hi @eerhardt, any chance to have a look at PR above ? :)
