### ISSUE TITLE
`libnethost.lib` appears to be built with LTCG, making it unusable with non-MSVC toolchains

### ISSUE THREAD

**Issue by alexrp** [dotnet/runtime#71056]
### Description

It seems that, for Windows platforms, the `libnethost.lib` static library shipped with the .NET SDK is built with [LTCG](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation) enabled, rendering it entirely unusable by non-MSVC toolchains such as [Zig](https://ziglang.org) or just plain [LLD](https://lld.llvm.org) on its own.

I'm not sure LTCG meaningfully benefits libnethost anyway, so I would argue it should just be disabled here.

### Reproduction Steps

```c
#define NETHOST_USE_AS_STATIC

#include "nethost.h"

int main()
{
    char_t buffer[4096];
    size_t buffer_size = sizeof(buffer) / sizeof(char_t);

    (void)get_hostfxr_path(buffer, &buffer_size, NULL);
}
```

`zig cc test.c /path/to/libnethost.lib`

### Expected behavior

The program should link successfully.

### Actual behavior

```console
$ zig cc test.c libnethost.lib
lld-link: error: unknown file type: nethost\CMakeFiles\libnethost.dir\nethost.cpp.obj
```

### Regression?

No.

### Known Workarounds

Building from source with LTCG off (presumably), but this is a pretty big inconvenience.

### Configuration

* .NET SDK 6.0.6
* Windows x64

**Comment by alexrp** [comment]
Here's how disabling LTCG is already done for other cases in the repo: https://github.com/dotnet/runtime/blob/663013d579d5eb3e29b2e0f88aeaed0694e74f39/src/coreclr/dlls/mscorrc/CMakeLists.txt#L7-L9

If that's an acceptable fix, I can send a PR.

**Comment by vitek-karas** [comment]
Sounds reasonable - please send a PR if you can.

**Comment by alexrp** [comment]
@AaronRobinsonMSFT @vitek-karas I just realized that linking to `libhostfxr.lib` statically seems to be a supported scenario. Should I submit a similar PR to disable LTCG for it as well?

**Comment by AaronRobinsonMSFT** [comment]
> I just realized that linking to libhostfxr.lib statically seems to be a supported scenario

I thought that was what was done here? I don't know why there would be LTCG for an import lib. Also, I didn't know an import lib scenarios even exists on non-Window.

**Comment by alexrp** [comment]
> I thought that was what was done here?

The earlier PR disabled LTCG for `libnethost.lib`, which sits one level higher than `libhostfxr.lib` (you use libnethost to locate libhostfxr).

> I don't know why there would be LTCG for an import lib.

`lib<name>.lib` is a static library; `<name>.lib` is an import library. I'm only talking about static libraries here. It appears that libhostfxr is being shipped as a static library in the DotNetAppHost packages just like libnethost.

**Comment by AaronRobinsonMSFT** [comment]
> libhostfxr.lib

Shoot. Misread that this is for `hostfxr` not `nethost`. I don't think that is needed to be honest. Linking in the `hostfxr` lib is for a narrower set of scenarios if I recall - single file, I think? I'm going to defer to @vitek-karas or @elinor-fung on this topic.

**Comment by vitek-karas** [comment]
I would not call it a "supported scenario", for example we have exactly 0 tests around it. But it was a simple change and some people wanted it. As for the LTCG, if we only build the lib file in question for the package I would be fine disabling it there. But if we also use the same lib to build `singlefilehost` then I would rather not change it.

**Comment by alexrp** [comment]
> As for the LTCG, if we only build the lib file in question for the package I would be fine disabling it there. But if we also use the same lib to build `singlefilehost` then I would rather not change it.

It does not seem to be used for the single-file case, judging by this file: https://github.com/dotnet/runtime/blob/main/src/native/corehost/apphost/static/CMakeLists.txt

**Comment by vitek-karas** [comment]
Looks good then - will you be able to prepare a PR for that?

/cc @VSadov  for the potential single-file impact (should be none, just wanting to be 100% sure)
