### ISSUE TITLE
creating mTLS connection in win2019 server returns "The Local Security Authority cannot be contacted" error

### ISSUE THREAD

**Issue by Protheon** [dotnet/runtime#71064]
### Description

I'm running a simple dotnet console app on a windows 2019 to execute a basic httpclient get to a remote machine using mTLS with a client certificate.
I am loading the client certificate in the httpclient by passing a p12 keystore filepath, which has the certificate keypair and chain.

- Executing this get on powershell with invoke-restmethod on the windows 2019 server works (returns 200), which means the certificate keypair is correct.
- Executing this using the installed .net 4 frawework on the windows 2019 server also works (returns 200) , which means that the certificate is being validated by accessing the store.
- Executing the application locally with either .netcore 3.1 or 6.0 also works (returns 200) so that means that both client and server certificates and chains are valid and my dotnet framework can access the local windows store and communicate with the machine.

I'm not specifying the security protocol in the call. I would expect it to default to either 1.1 or 1.2, since windows 2019 does not support 1.3.

At this point i have no clue why this is not working.

### Reproduction Steps

Here is the simple call that is causing the issue:

 var certificate = new X509Certificate2(filePath, password);
 var handler = new HttpClientHandler();
 var httpClient = new HttpClient(handler)
 handler.ClientCertificates.Add(certificate);

 var result = httpClient.GetAsync("https://urltoserverwithvalidmTLS").GetAwaiter().GetResult();

### Expected behavior

Returns 200

### Actual behavior

 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted

--- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

--- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)

### Configuration

OS: windows 2019 server

dotnet console app:
1st failed attempt app is published with:
--configuration Release -r win--x64 --self-contained true
csproj targets net3.1 framework

2nd failed attempt app is published with:
--configuration Release -r win-x64 --self-contained false
csproj targets net6.0 framework

**Comment by wfurt** [comment]
This comes from the OS afaik and it is related to how the certificate is loaded and what provider is selected. Can you try to load it with X509KeyStorageFlags.PersistKeySet ? In general, on Windows TLS does not work with ephemeral keys.
