### ISSUE TITLE
PROPOSAL: Reintroduce ICorRuntimeHost::DefaultDomain()-sort-of API on Windows

### ISSUE THREAD

**Issue by janvrany** [dotnet/runtime#7107]
The aim of this proposal is to add (actually, reintroduce) a new COM API to retrieve a reference to a COM interface `_AppDomain` (IID {05F696DC-2B29-3663-AD8B-C4389CF2A713}). for a default domain. Alternatively, the API method could take an appdomain ID as a parameter and return `_AppDomain` for it. 
Similar API is in full Microsoft  .NET Framework - [ICorRuntimeHost::GetDefaultDomain][1].

Rationale: The `_AppDomain` interface along with others such as `_Assembly`, `_Type` and so on is essential when one need to build advanced interop with .NET. For that one needs to load an assembly and reflect on its types, methods of those types and eventually call them. 

Imagine one wants to use some .NET code from a Ruby application running on MRI in way like in following (hypothetical) example:

     CoreCLR.load()
     System.Assembly.Load("System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089")
     begin               
        data = System.Xml.XPath.XPathDocument.new('cd.xml')
        buffer = System.Text.StringBuilder.new
        writer = System.Xml.XmlWriter.Create(buffer)    
        xslt =  System.Xml.Xsl.XslCompiledTransform,new()
        xslt.Load('cd.xsl')
        xslt.Transform(data, nil, writer, nil)        
        puts buffer.ToString()
     rescue System.IO.FileNotFoundException => fnfe
        puts "OOPS, file''s missing: #{fnfex.FileName}"        
     rescue System.Xml.Xsl.XsltException => xslte
        puts "OOPS, transformation failed: #{xsltex.Message}"
     end

Using `_AppDomain` it's perfectly possible to implement such an interop (I have actually managed to get it working on a full .NET). I'd be really nice to be able to load CoreCLR too. 

[1]: https://msdn.microsoft.com/en-us/library/ms164328(v=vs.110).aspx

**Comment by AaronRobinsonMSFT** [comment]
@janvrany Please let us know if you are still having issues. For right now, I am closing this issue.

**Comment by janvrany** [comment]
You can close it. I'm gone from that project long time and, AFAIK, support for .NET Core has been ditched.

**Comment by vincentparrett** [comment]
Old thread, but I just ran into this issue while investigating migrating to .net core. 

My native host application loads .net plugins, and instantiates .net objects via the _Assembly etc com interfaces... and then interacts with those objects (which implement a known interface).. as far as I can see, there doesn't appear to be any way to achieve this with .net core hosting api? 

Any suggestions on how to work around this?

**Comment by AaronRobinsonMSFT** [comment]
@vincentparrett There is no real path forward for consuming the underscore COM interfaces provided by .NET Framework (e.g. `_Assembly`) - they have largely been removed. COM interop is still supported, but the key here is the runtime isn't going to be providing well-known interfaces transparently for the user (e.g. `_Assembly`). However, defining new `IUnknown` based interfaces and passing those to native code for consumption is supported.

> as far as I can see, there doesn't appear to be any way to achieve this with .net core hosting api?

The way to make this work is conceptually identical, but the API surface has been reduced to primitives. This means there are more steps for developers.

1) Activate the runtime or attach to an existing one in the process.
1) Use `load_assembly_and_get_function_pointer()` to load and get a function pointer to a static member.
1) Call the method, which can return an `object` that implements an `IUnknown` based interface.
   * The returned object should be marked with [`MarshalAs`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshalasattribute) and supply the [`UnmanagedType.IUnknown`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedtype).

The above end-to-end except the returning of an `IUnknown` interface is demonstrated in a sample [here](https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr).

**Comment by vincentparrett** [comment]
@AaronRobinsonMSFT thanks, I'll take a look at that example. I guess I can just create a loader assembly that exposes the function to create and return my plugin objects.

**Comment by AaronRobinsonMSFT** [comment]
>create a loader assembly that exposes the function to create and return my plugin objects.

@vincentparrett Yep. That is what we would recommend. Please let us know if you hit issues or have feedback. We are in the midst of trying to plan for future improvements in this area and actual user feedback is very much welcome.
