### ISSUE TITLE
CoreCLR tests fail to execute if .NET 7 Preview 4 is installed on the machine

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#71099]
I have started to hit a problem with running coreclr tests that happens only when the .NET 7 Preview 4 is installed on my machine.
In such case, runtime build doesn't download and install .NET into the `.dotnet` subfolder (which is by design, IIRC). So when coreclr tests are executed, it uses dotnet from the `c:\Program Files` and somehow ends up using xunit for 6.0.6 instead of 7.0.0. The log of the `src/tests/run.cmd` execution shows that right before it fails:
```
  C:\Program Files\dotnet
  Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 6.0.6)
     baseservices.callconvs.XUnitWrapper: Exception thrown during test framework discoverer construction: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the fil
  e specified.
  File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  File name: 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack 
.
.
.
```
When I uninstall the .NET 7 Preview 4, the runtime build scripts download it to the .dotnet folder and then coreclr tests execution uses that one and uses correct xunit:
```
  F:\git\runtime8\.dotnet
  Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-preview.5.22301.12)
    Discovering: baseservices.callconvs.XUnitWrapper (method display = ClassAndMethod, method display options = None)
    Discovered:  baseservices.callconvs.XUnitWrapper (found 1 test case)
.
.
.
```

**Comment by janvorli** [comment]
cc: @dotnet/runtime-infrastructure

**Comment by MichalStrehovsky** [comment]
I hit this all the time. I thought it's specific to my environment.

I cannot uninstall the globally installed preview because that breaks using VS with the repo. The workaround I do is editing artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\xunit\xunit.console.runtimeconfig.json. The content without any changes is:

```json
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "rollForward": "Major",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

I stomp over the 3.1.0 part with the runtime version I have (no other changes needed). If you're not sure what version to put there, put 7.0.0 and then it will fail and tell you what's installed.

**Comment by agocke** [comment]
I think this should no longer happen since we've moved everything past Preview 5 now.
