### ISSUE TITLE
Add Function Pointer support to Mono Reflection

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#71095]
Once https://github.com/dotnet/runtime/issues/69273 is in for CoreClr, Mono should uptake that. It is expected that the CoreClr implementation will be done soon for V7.

cc @lambdageek

**Comment by lambdageek** [comment]
this should be fairly straightforward for mono.  possibly with the exception of creating the calling convention array.

**Comment by steveharter** [comment]
Moving to 8.0; we need to update the API and design based on feedback from https://github.com/dotnet/runtime/pull/71516.

**Comment by lambdageek** [comment]
CoreCLR is done. We should do the Mono version @SamMonoRT
