### ISSUE TITLE
Serious flaw in KeepAlive

### ISSUE THREAD

**Issue by HypsyNZ** [dotnet/runtime#71109]
https://github.com/dotnet/runtime/blob/7cbf0a7011813cb84c6c858ef19acb770daa777e/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L525

You aren't ignoring the exception and this is the reason the socket keeps closing unexpectedly and throwing exceptions for seemingly no reason.

Don't handle Exceptions inappropriately.

Also, No response is required so why are you waiting for one.

Probably related issue because of `line 518` : https://github.com/dotnet/runtime/issues/69684

**Comment by stephentoub** [comment]
> This isn't true

What isn't true?

>  and is the reason the socket keeps closing unexpectedly and throwing exceptions for seemingly no reason

Ignoring these asynchronous isn't causing sockets to close.

What is it you'd expect this to do instead?  If this else block were deleted, it would have zero impact on sockets closing; it would simply result in the TaskScheduler.UnobservedTaskException event being raised sporadically and for reasons outside of the developer's code / control.

**Comment by HypsyNZ** [comment]
What makes you think you are ignoring the exception.

**Comment by stephentoub** [comment]
> What makes you think you are ignoring the exception.

The fact that we are?
```C#
_ = p.Exception
```

**Comment by HypsyNZ** [comment]
Okay

**Comment by HypsyNZ** [comment]
> > What makes you think you are ignoring the exception.
> 
> The fact that we are?
> 
> ```cs
> _ = p.Exception
> ```

Okay

**Comment by HypsyNZ** [comment]
To me it looks like you are handling the exception, Which gives anyone else the opportunity to raise the exception; Just so you can discard it.

I think you need to do an entry level programming course.

**Comment by stephentoub** [comment]
> To me it looks like you are handling the exception, Which gives anyone else the opportunity to raise the exception; Just so you can discard it. I think you need to do an entry level programming course.

I'm closing your issue.  The cited code is doing what it is intended to do.  We also have a code of conduct in this repo (https://github.com/dotnet/runtime/blob/main/CODE-OF-CONDUCT.md) that we ask all participants to follow.  Telling someone they need to do an entry level programming course (I promise you I don't) violates that code of conduct.  Thank you.

**Comment by HypsyNZ** [comment]
You are handling the exception. The discard isn't doing what you think it is doing.

**Comment by stephentoub** [comment]
> The discard isn't doing what you think it is doing.

It is.  Tasks that end in the faulted state track whether the exception they contain has ever been "observed", meaning exposed to the consumer in some way.  Exceptions that go unobserved then trigger the TaskScheduler.UnobservedTaskException event, as I mentioned earlier.  Accessing the Task.Exception property on a faulted task marks that exception as observed, thus preventing it from triggering that event.

**Comment by HypsyNZ** [comment]
You are handling the exception. That is all you get to decide.

**Comment by HypsyNZ** [comment]
How exactly do you imagine I ended up on this exact line of code in a core library?

**Comment by HypsyNZ** [comment]
I just want to reiterate that you are wrong and when `SendKeepAliveFrameAsync()` fails the socket closes unexpectedly.

**Comment by HypsyNZ** [comment]
Embarrassing, for you I mean.

**Comment by stephentoub** [comment]
> I just want to reiterate that you are wrong and when SendKeepAliveFrameAsync() fails the socket closes unexpectedly.

It's certainly possible the socket is closed or closing when an exception occurs. But it's not closing _because_ of this code that's suppressing the TaskScheduler.UnobservedTaskException event.

**Comment by HypsyNZ** [comment]
No. You are just wrong.

**Comment by HypsyNZ** [comment]
Welcome to my application code, imaginary exception from impossible location unless you are just wrong.

**Comment by HypsyNZ** [comment]
Embarrassing that I keep having to handle your exceptions that don't exist, Just found another one.
