### ISSUE TITLE
ilasm roundtrip testing should ensure roundtripped assembly file name matches baked-in assembly name

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#71119]
The ilasm roundtrip testing produces an assembly with the same baked-in assembly name, but named with a ".asm.dll" suffix instead of ".dll" suffix. It was noticed in #70876 that this leads to dotnet.exe, and previously also corerun.exe, executing the original assembly file instead of the roundtripped assembly file.
After eb9dd67 and 5713bea corerun.exe _does_ execute the renamed file, so we are now testing the right thing, but we should probably change it to be more similar to R2R testing that ensures the same file name to avoid potential future problems.

cc @dotnet/jit-contrib

**Comment by TIHan** [comment]
Related: https://github.com/dotnet/runtime/issues/70875

**Comment by TIHan** [comment]
@jakobbotsch, is there information regarding how R2R does testing here? I can look at it myself but figured I would ask.

**Comment by jakobbotsch** [comment]
I'm not sure we have any docs on the side, but the essence of what it does should be this Bash code (and the equivalent Batch script below):
https://github.com/dotnet/runtime/blob/66f1bb4719510ef9680e5493a1644b07f3edb407/src/tests/Common/CLRTest.CrossGen.targets#L41-L170
The essence is that it creates an IL-CG2 directory, copies everything in there, and then invokes crossgen2 outputting the new .dll into the original location.
