### ISSUE TITLE
JIT ARM64: Assertion failed 'argValue->OperIsIndir()' during 'Morph - Global'

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#71118]
New-ish failure in jitstress.
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1838276&view=results
Helix job name: coreclr windows arm64 Checked jitstress1_tiered
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7845cb10b061455d94/Interop/1/console.5274bc02.log?helixlogtype=result

```scala
        Assert failure(PID 15236 [0x00003b84], Thread: 7160 [0x1bf8]): Assertion failed 'argValue->OperIsIndir()' in 'Vector2_3_4Test:RunVector3Tests()' during 'Morph - Global' (IL size 362; hash 0x93db1cc2; Tier0)
        
            File: D:\a\_work\1\s\src\coreclr\jit\morph.cpp Line: 4010
            Image: D:\h\w\9A730828\p\corerun.exe
```

cc @dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
Likely cause is #70888. Will take a look.
