### ISSUE TITLE
Explore allowing a command-line parameter to control CORE_LIBRARIES in corerun

### ISSUE THREAD

**Issue by mellinoe** [dotnet/runtime#7112]
We are currently in the process of revamping the build system used in corefx. One of the changes we are interested in making to our testing process is having two segregated folders: one for the runtime and framework binaries, and then a separate one (or set) containing individual test assemblies. We'd like to avoid having to copy everything into multiple folders like we are doing today, because it wastes a ton of space or requires copious filesystem linking.

```
bin/runtime/
           / coreclr.dll
           / corerun.exe
           / xunit.console.netcore.exe

bin/tests/
         /System.Runtime.Tests/System.Runtime.Tests.dll
         /System.Console.Tests/System.Console.Tests.dll
```

We can easily achieve this by just executing the test runner from the first folder, pointing it at one of the test assemblies, and setting `CORE_LIBRARIES=<testfolder>`. It would be interesting to explore whether we can expose an explicit command-line parameter that either controls CORE_LIBRARIES, or has the same effect (dumping the folder onto the TPA list).

**Comment by AaronRobinsonMSFT** [comment]
This is no longer relevant since the two repos have consolidated. This is also possible from `corerun` using the `-clr-path` flag.
