### ISSUE TITLE
Pressing CTRL+C while polling for user input disables input echoing.

### ISSUE THREAD

**Issue by SapphireAmoeba5** [dotnet/runtime#71154]
### Description

When the compiled program is polling for user input (through Console.ReadLine, Console.Read, etc) and the user presses CTRL+C to send SIGINT and close the program, input echoing is disabled. You are able to type in commands fine, except any keys you press do not appear on the terminal prompt. You can fix it by typing `stty echo`, however this doesn't seem like a proper fix considering this does not happen in any other language I used.

### Reproduction Steps

When the program is polling for input from Console.ReadLine, Console.Read, or any other method of polling from the Console class and the user presses CTRL+C this issue occurs. 

### Expected behavior

Input echoing is not disabled after closing the program, and the terminal works as normal. This is the behaviour that occurs in C++, Rust, or Java.

### Actual behavior

The behaviour is similar to when you are typing a password on linux I.E using sudo, or logging in as a user where any key you press is not echoed to the terminal screen. Typing `stty -echo` into the terminal is exactly the state the terminal goes in after reproducing this issue.

### Known Workarounds

Reenable echoing by typing `stty echo`.

### Configuration

typing `dotnet --version` outputs `6.0.301`. Arch Linux on an AMD x86_64 processor with an NVIDIA gpu. The project was created using dotnet by typing `dotnet new console`.

**Comment by tmds** [comment]
This is the same as https://github.com/dotnet/runtime/issues/64166. It was fixed on main by https://github.com/dotnet/runtime/pull/64200.

It hasn't been backported to 6.0. For that we need a champion from @dotnet/area-system-console.

**Comment by adamsitnik** [comment]
Hi @SapphireAmoeba5 

Thank you for reporting the issue. As @tmds has mentioned, it has been fixed in main (was part of .NET 7 Preview 1) via https://github.com/dotnet/runtime/pull/64200.

I am working on backporting it to 6.0: https://github.com/dotnet/runtime/pull/64985
