### ISSUE TITLE
Document all CI pipelines that can be manually triggered in PRs

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#71172]
Today I learned about `runtime-community`, an optional pipeline that can be executed in PRs to test code in architectures that we don't officially support but the community maintains.

I tried to find documentation about it but couldn't find any. I only found 3 hits in yaml files: https://github.com/dotnet/runtime/search?q=runtime-community

I did find a document that describes some of the available pipelines, but not this one: https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md

The folder `runtime/eng/pipelines` has many yaml files, but I am not yet fully familiar with how they all work, or if all of them can be manually triggered.

I think we should have documentation for all the pipelines that can be triggered via `/azp run`. Here are the ones I know about. I am unsure if they can all be manually triggered, and I suppose I am missing many more:

- [runtime](https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#runtime-pipeline)
- [runtime-extra-platforms](https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#runtime-extra-platforms)
- runtime-linker-tests (undocumented)
- runtime-community (undocumented)

Not sure if can be triggered:
- [runtime-dev-innerloop](https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#runtime-dev-innerloop-pipeline)
- [runtime-staging](https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#runtime-staging)

We should also improve the description of the [outerloop section](https://github.com/dotnet/runtime/blob/main/docs/pr-builds.md#outerloop-pipelines), because it says we have various available pipelines that can be executed, but does not mention which ones, or how to trigger them.

cc @dotnet/area-infrastructure-libraries

**Comment by jkotas** [comment]
> Here are the ones I know about. I am unsure if they can all be manually triggered, and I suppose I am missing many more:

There are about 50 different pipelines that can be triggered manually. You can get current full list by running `/azp list`. For example: https://github.com/dotnet/runtime/pull/71100#issuecomment-1162411713
