### ISSUE TITLE
System.Net.Http.ContentLengthReadStream should provide the length of the stream

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#71190]
### Description

Accessing the `Length` property of `System.Net.Http.ContentLengthReadStream` should return the length of the stream. Instead, it throws `System.NotSupportedException`.

### Reproduction Steps

Run the following code:

```csharp
const string url = "https://httpbin.org/image/jpeg";
using var httpClient = new HttpClient();
using var response = await httpClient.GetAsync(url);
Console.WriteLine($"Content length: {response.Content.Headers.ContentLength}");

await using var stream = await httpClient.GetStreamAsync(url);
Console.WriteLine($"Stream type: {stream.GetType()}");
Console.WriteLine($"Stream length: {stream.Length}");
```

### Expected behavior

The following output should be printed to the console:
```
Content length: 35588
Stream type: System.Net.Http.HttpConnection+ContentLengthReadStream
Stream length: 35588
```

### Actual behavior

`System.NotSupportedException` is thrown:
```
System.NotSupportedException: Specified method is not supported.
   at System.Net.Http.HttpBaseStream.get_Length()
   at Program.<Main>$(String[] args) in ...\Program.cs:line 8
   at Program.<Main>$(String[] args) in ...\Program.cs:line 8
   at Program.<Main>(String[] args)
```

### Regression?

I don't think it's a regression. I think it has never worked but I just discovered this issue so I can't say for sure.

### Known Workarounds

Read the private `_contentBytesRemaining` field on `ContentLengthReadStream` with reflection before starting reading the stream. This is a terrible workaround.

### Configuration

- **.NET version**: 6.0.6 commit 7cca709db2
- **OS**: Windows 10 21H2 (but that's not specific to Windows)
- **Architecture**: x64 (but that's not specific to x64)

### Other information

I can submit a pull request to fix this issue if it's deemed appropriate.

**Comment by ManickaP** [comment]
I know this is somewhat unconvenient, but the fact that the underlying stream is `ContentLengthReadStream` is an implementation detail. Also [`CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-6.0) returns `false` in this case.

We might consider overriding `Length`, but still, not in all cases you'll get `ContentLengthReadStream`. Also the header value might lie, so the reported value might not be accurate. Since you can query the header value yourself, I don't see exactly a strong case for changing the current behavior. 

What problems does this introduce to you? How much impactful are they? Maybe you have some strong arguments to support the change that might change our mind.

**Comment by EwoudLindemans** [comment]
As a better "workaround", this will return a MemoryStream with given length:
```cs
using (var response = await httpClient.GetAsync(uri)) {
   var stream = await response.Content.ReadAsStreamAsync();
}

**Comment by 0xced** [comment]
> the underlying stream is ContentLengthReadStream is an implementation detail.

I totally get that it's an implementation detail. Still, it breaks the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) in my opinion. I'd expect that a `Stream` returned by an `HttpClient` when the `Content-Length` header is available to return that `Length` instead of throwing a `NotSupportedException`.

> Also [CanSeek](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-6.0) returns false in this case.

The remarks section of this method states this (emphasis mine):

> _If a class derived from [Stream](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-6.0) does not support seeking, calls to [Length](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.length?view=net-6.0), [SetLength](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.setlength?view=net-6.0), [Position](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.position?view=net-6.0), and [Seek](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.seek?view=net-6.0) **may** throw a [NotSupportedException](https://docs.microsoft.com/en-us/dotnet/api/system.notsupportedexception?view=net-6.0)._

Note that it doesn't say that it **must** throw. Getting the value of the content length in that case is much better than throwing `NotSupportedException` in my opinion.

> Also the header value might lie, so the reported value might not be accurate.

That's true and in that case an `IOException` [will be thrown](https://github.com/dotnet/runtime/blob/v6.0.6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ContentLengthReadStream.cs#L41).

> What problems does this introduce to you? How much impactful are they? Maybe you have some strong arguments to support the change that might change our mind.

I haven't benchmarked but the workaround proposed by @EwoudLindemans is probably much more memory hungry since it uses a `MemoryStream`. Let's say you want to download a very large file and report progress along the way (which requires knowing the length of the content upfront), you don't want to have the whole content in memory.

Also, as I already said, throwing `NotSupportedException` breaks the principle of least astonishment since I know that the content length is available.

Finally, I have looked at it from an implementation perspective and that's really not much work to properly implement the `Length` property on the `ContentLengthReadStream` class.

**Comment by 0xced** [comment]
I just opened #71879 to implement the `ContentLengthReadStream.Length` property. You can see it was straightforward.

**Comment by filipnavara** [comment]
I'm not quite sure how would this be useful. You should be able to access the `Content-Length` value in `response.Content.Headers`  and that should make it easy to see if it was present or not.

Accessing the `Length` property on the stream would throw if the `Content-Length` header is not present and you would always need to account for the exception and handle the situation anyway.

**Comment by karelz** [comment]
Triage:
- We believe this is a minor convenience thing with non-trivial cost and gotchas
- We value consistency between chunked and Content-Length responses, without a `HasLength` #43448 check (to avoid exceptions) it does not make sense.

We would not take a contribution for such change, unless there is more evidence of wider need, or evidence against our reasoning.
