### ISSUE TITLE
[wasm] ReferenceError: SharedArrayBuffer is not defined. /p:WasmEnableThreads=true

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#71196]
many tests in the `runtime-wasm` CI legs are failing when `/p:WasmEnableThreads=true`.
This is blocking clean runtime-wasm CI.

https://github.com/dotnet/runtime/blob/b1221494186e7b8e5199d892dae76481a52f5935/eng/pipelines/runtime-extra-platforms-wasm.yml#L75

See 
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66304-merge-2d2822b422664c0f83/Wasm.Browser.CJS.Sample/1/console.9ebb2543.log?helixlogtype=result)
[11:25:01] info: user code in createDotnetRuntime
[11:25:01] info: WASM ERROR ReferenceError: SharedArrayBuffer is not defined
[11:25:01] info: WASM EXIT 2

**Comment by pavelsavara** [comment]
cc @radical @steveisok

**Comment by pavelsavara** [comment]
Does yellow CI mean I could ignore it ?
![image](https://user-images.githubusercontent.com/271576/175273431-ee25d328-bf85-423f-b464-eedf391a902c.png)

How do I differentiate on the test tab?
![image](https://user-images.githubusercontent.com/271576/175273711-1dbe17bf-49a1-480f-9765-5c2a7e8e300d.png)

**Comment by steveisok** [comment]
It looks like the results for the legs are showing as optional as intended.  The yellow icons indicate that.

The labels in the test tab are confusing and we'll have to look into tweaking them.
