### ISSUE TITLE
Detecting the user or the system closing .NET Core console application

### ISSUE THREAD

**Issue by nicolasr75** [dotnet/runtime#7120]
Is there any way to detect whether a user or the system closes a console application? I support Ctrl-C for closing by a user but since the system provides the ability to simply close the console window I can not clean up my application which is important since it performs regular tasks that should be terminated cleanly. The same goes for system shutdown.

I tried 

`System.Runtime.Loader.AssemblyLoadContext.Default.Unloading`

but that does not fire when the window is closed.

**Comment by ricardoboss** [comment]
I just want to execute some cleanup before my program exists. I hope this issue gets resolved before .NET 5.

**Comment by joperezr** [comment]
Moving to 5.0 milestone just to do a quick check to see if there is anything that we want/need to do in here for 5.0 as from the discussion above it is not clear yet what works and what doesn't.

**Comment by ericstj** [comment]
Seems related to https://github.com/dotnet/runtime/issues/36089

**Comment by ststeiger** [comment]
@ricardoboss: Yea, me too. 
I have a command line SQL-Server profiler. 
And it needs to stop the profiling when the program is closed (via quit or CTRL+C or sigkill). 
Otherwise, the profiling is continuing ad infinitum, and potentially slowing down production machines.

**Comment by ygoe** [comment]
I'm still using my above code (4 Nov 2018) with .NET Core 3.1. And after digging through lots of WebHost and other host code from the framework, I know that it's still used there as well. So there might not be a ready-to-use API for this, but the code shown above solves the problem completely.

On Windows you have about 3 seconds before the OS kills the process. No way around that. On Linux with Systemd, you can configure this and it defaults to 90 seconds. When using the application shutdown behaviour that's built into the hosts (like WebHost), you can use additional configuration to prolong the internal default of 5 seconds before hosted services get aborted. This is another thing though and unrelated to what the OS does.

**Comment by sbomer** [comment]
From my testing, it looks like `ProcessExit` is correctly invoked when a terminal window is closed on Windows (which sends the `CTRL_CLOSE_EVENT`) on 5.0. A few things to watch out for (repeating some things @ygoe has already pointed out):
- The console window will be closed while `ProcessExit` runs - so don't expect to see output from `Console.WriteLine` after closing the window.
- There's a [timeout](https://docs.microsoft.com/en-us/windows/console/handlerroutine#timeouts), so any cleanup code should finish quickly.
- If you kill the application via Ctrl+C, the `ProcessExit` handler will not run. You can get around this like ASP.NET does, by installing a `CancelKeyPress` handler that sets `Cancel = true` (preventing the OS from tearing down the process immediately after the handler runs) and initiates an asynchronous shutdown path.
One way to do this is to use the ASP.NET generic host, like in https://github.com/dotnet/runtime/issues/36089#issue-614469355. Just replace the `WriteLine` with the shutdown logic that should run on Ctrl+C or window close.

Shutdown is not handled correctly - that's tracked by https://github.com/dotnet/runtime/issues/36089.

On Unix, it looks like closing a terminal window sends `SIGHUP` which we do not handle at all.

A few questions:
- Do we want the `ProcessExit` handler to be called if a process is shut down by an unhandled Ctrl+C? (This would be a breaking change for folks who intentionally have independent shutdown paths for the two events, so I think we want to keep the current behavior).
- Should we call the `ProcessExit` handler on Unix when receiving a `SIGHUP`?

**Comment by danmosemsft** [comment]
One datapoint might be what Mono does.

**Comment by ygoe** [comment]
Wasn't SIGHUP the signal that Systemd sends when a service should be reloaded?

**Comment by sbomer** [comment]
It looks to me like mono doesn't handle `SIGHUP` either (or `SIGTERM` for that matter, which is what 'docker stop' sends to linux containers).

**Comment by VILLAN3LL3** [comment]
> ```cs
> private void AttachCtrlcSigtermShutdown(CancellationTokenSource cts, ManualResetEventSlim resetEvent)
> {
>     void Shutdown()
>     {
>         try
>         {
>             cts.Cancel();
>         }
>         catch (ObjectDisposedException)
>         {
>         }
>         resetEvent.Wait();
>     };
> 
>     AppDomain.CurrentDomain.ProcessExit += (sender, eventArgs) => Shutdown();
>     Console.CancelKeyPress += (sender, eventArgs) =>
>     {
>         Shutdown();
>         // Don't terminate the process immediately, wait for the Main thread to exit gracefully.
>         eventArgs.Cancel = true;
>     };
> }
> ```

I tried this in .NET 5.0 but there's no WaitAsync() method on CancellationToken. Any advice how to get this running in .NET 5.0?

**Comment by jnm2** [comment]
@VILLAN3LL3 I've used C#'s `async Main` feature and `await Task.Delay(Timeout.Infinite, shutdownCancellationToken);` when there was not already an async call in progress keeping the main method from returning.

**Comment by ygoe** [comment]
@VILLAN3LL3 What are you trying to wait asynchronously for? There's nothing in the quoted code. Remember, you must not leave the ProcessExit event handler, not even by await, or the process will end immediately. The point is to block that method until the event has been set.

**Comment by VILLAN3LL3** [comment]
@jnm2 Thank you very much for your advice. I had to additionally catch `TaskCanceledExceptions` to make this work because shutting down the app throws this exception if I use your code snippet. But with the `Catch` it works - almost. Stopping the app by clicking on the Stop Debugging Button in Visual Studio does obviously not trigger one of the events.

@ygoe Sorry I quoted the wrong part of your code. It's corrected now.

**Comment by ygoe** [comment]
@VILLAN3LL3 That `WaitAsync` may come from the AsyncEx NuGet package. But the solution provided by @jnm2 looks good, too. Sometimes you have to be creative when the BCL isn't comprehensive.

Yes, that use of a CancellationToken throws an exception when cancelled. Also note that TaskCanceledException is derived from OperationCanceledException and I never know which of the two is actually thrown, so I always catch the OCE as the more generic one to be safe. If somebody has found a pattern behind these two, please let me know.

**Comment by jnm2** [comment]
> If somebody has found a pattern behind these two, please let me know.

@ygoe Roughly, `CancellationToken.ThrowIfCancellationRequested()` creates the base exception type and `Task`/`Task<T>` creates TaskCanceledException if it's in the TaskStatus.Canceled state.

**Comment by ygoe** [comment]
Yes, but the caller of a method often doesn't know what implementation is in there, or doesn't want to rely on that detail.

**Comment by jnm2** [comment]
All a caller should care about is the base exception type, as far as I know.

**Comment by eerhardt** [comment]
I believe the original issue has been addressed. Using .NET 6, you can subscribe to https://docs.microsoft.com/dotnet/api/system.appdomain.processexit, and it will be invoked even when the terminal window is closed.

For handling `CTRL+C` and signals, a new option added in .NET 6 is https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.posixsignalregistration which was added to correctly handle POSIX signals. Just an FYI, you can also use this API on Windows, and it will fire `SIGINT` for `CTRL+C`. See https://github.com/dotnet/runtime/issues/50527 for scenarios on when this is useful.

I'm going to close this issue has I believe the original problem has been addressed. If you have a different problem, please log a new issue.
