### ISSUE TITLE
PGO: Assertion failed '(sizeDif == 4) || (sizeDif == 8)'

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#71217]
Failed in various FullPGO outerloop pipelines, e.g. https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70941-merge-715035df5abc46f3ad/Microsoft.VisualBasic.Core.Tests/1/console.b6d69b24.log?helixlogtype=result

**Comment by AndyAyersMS** [comment]
Looks like `sizeDif` is 0 here.
