### ISSUE TITLE
HttpClient.DefaultProxy doesn't understand socks when populated from an environment variable

### ISSUE THREAD

**Issue by crfrolik** [dotnet/runtime#71215]
### Description

As mentioned in the [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-6.0#system-net-http-httpclient-defaultproxy), the value for `HttpClient.DefaultProxy` is populated based on a set of environment variables, including `HTTPS_PROXY`.

[This code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/SystemProxyInfo.Unix.cs#L13) should be changed to recognize the fact that the `HTTPS_PROXY` environment variable can contain a socks URL, e.g. `socks5://...`.

### Reproduction Steps

1. Modify the `HTTPS_PROXY` environment variable to contain a `socks5` url.
2. Run a .NET app that uses `HttpClient`.
3. The app does not correctly use the proxy.

### Expected behavior

.NET should support socks proxies for `HttpClient.DefaultProxy`.

### Actual behavior

.NET does not support socks proxies for `HttpClient.DefaultProxy`.

### Configuration

Ubuntu 20.04 x64

**Comment by karelz** [comment]
Triage: It would be nice to have that supported assuming it is simple to do.
Not a priority -> Future.

@MihaZupan assigning to you to weigh on complexity. Perhaps we can mark it up-for-grabs?

**Comment by MihaZupan** [comment]
This request makes sense to me. From what I can tell it should be mainly updating the [`HttpEnvironmentProxy.GetUriFromString`](https://github.com/dotnet/runtime/blob/a712828583b54a283d0e5343457d4b16d2234b31/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs#L122) to not assume http-only.

**Comment by wfurt** [comment]
Is there anything beyond that function? I assume fixing just the parser would not be enough, would it @MihaZupan ?
