### ISSUE TITLE
Microsoft.Diagnostics.Tracing.EventSource.Redist package support will end with .NET 6

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#71231]
# Microsoft.Diagnostics.Tracing.EventSource.Redist package support will end with .NET 6 
 
The [Microsoft.Diagnostics.Tracing.EventSource.Redist](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist) package has historically allowed us to fast-track EventSource API bug fixes out-of-band for .NET Framework 4.x. In recent years we continued to ship versions of this package concurrently with .NET Core releases, but the last time it was used to intentionally distribute out-of-band fixes for .NET Framework was package version 1.1.28 from 2015. The fixes that originally made the package useful have long since been applied to the .NET Framework in-box EventSource API and now we plan to phase out this package. Support for the current 6.0 version of the package will continue for as long as .NET 6.0 is supported but no future versions concurrent with .NET 7 and beyond are planned.
 
We recommend developers targeting .NET Framework 4.x use the in-box version of the EventSource API, System.Diagnostics.Tracing.EventSource. Developers who want to track future feature development in the EventSource API should target System.Diagnostics.Tracing.EventSource included in the latest available release of .NET runtime, currently .NET 6.
 
### How to migrate away from Microsoft.Diagnostics.Tracing.EventSource.Redist
 
1. For apps and libraries targeting .NET Framework ensure you are targeting at least version 4.6.2. For apps and libraries targeting
 .NET Standard, .NET Core, or .NET 5+ no targeting change is needed.
 
2. Replace references in source to the namespace `Microsoft.Diagnostics.Tracing`
 with `System.Diagnostics.Tracing` instead. For example
 
```
using Microsoft.Diagnostics.Tracing;
```
should now be
```
using System.Diagnostics.Tracing;
```
 
3. Remove package references to Microsoft.Diagnostics.Tracking.EventSource.Redist from project files. You can do this in Visual Studio UI by selecting References->Manage NuGet packages... , then selecting the package from the installed package list and click the uninstall button. Alternately you can use the [Uninstall command](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-uninstall-package) in Visual Studio package manager. For apps developed using the .NET CLI tools you can use the [dotnet remove package command](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-remove-package).
 
### What happens if I do nothing?
 
The Microsoft.Diagnostics.Tracing.EventSource.Redist package should continue to work as-is, but support for the [latest major version of the package](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventSource.Redist/6.0.0) will end November 12, 2024. After that point the package will receive no further fixes for security or any other reason. There are no known security vulnerabilities in this package but it is always possible new issues will be discovered in the future.

**Comment by stephentoub** [comment]
@noahfalk, I assume this means we'll be ripping out all of the ifdefs and the like from the implementation?

**Comment by noahfalk** [comment]
Yeah, unless I missed a dependency somewhere this should be the end of ES_BUILD_STANDALONE

**Comment by stephentoub** [comment]
And there was much rejoicing.

**Comment by brianrob** [comment]
@KalleOlaviNiemitalo, there are no plans to release further versions of EventRegister.  EventRegister should continue to work with EventSources created via Microsoft.Diagnostics.Tracing.EventSource.Redist.  Given that there will not be support for Microsoft.Diagnostics.Tracing.EventSource.Redist, there will not be support EventRegister either.
