### ISSUE TITLE
Test failure Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71242]
Frequency:
- 3/27-7/22 period ... **61 failures**, starting on 6/22 - around **2x per day.**
    - **55x Official run failures**
    - Most failures are on Windows, 4 failures are on Linux
    - Mixture of x64 and x86 failures

Run:[ runtime-libraries-coreclr outerloop 20220623.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1841178&view=ms.vss-test-web.build-test-results-tab&runId=48614146&paneView=debug&resultId=100007)

Failed test: 
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.Client.Open

- Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

```
**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully() in /_/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerProcessorTests.cs:line 150
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by eerhardt** [comment]
@maryamariyan - can you take a look?

**Comment by VincentBu** [comment]
Failed again in:[ runtime-libraries-coreclr outerloop 20220704.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1859738&view=ms.vss-test-web.build-test-results-tab&runId=48875412&paneView=debug&resultId=101956)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

- Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

```
**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully() in /_/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerProcessorTests.cs:line 150
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
```

**Comment by VincentBu** [comment]
Failed again in:[runtime-libraries-coreclr outerloop 20220714.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1880437&view=ms.vss-test-web.build-test-results-tab&runId=49185496&paneView=debug&resultId=100001)

Failed test:
```
net48-windows-Release-x64-Windows.11.Amd64.Client.Open

- Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully

```
**Error message:**
```
Assert.Equal() Failure
Expected: 2
Actual:   3


Stack trace
   at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerProcessorTests.ThrowDuringProcessLog_ShutsDownGracefully() in /_/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerProcessorTests.cs:line 151
```

**Comment by karelz** [comment]
This is high frequency failure mostly in official builds (see top post with details). It started on 6/22.
@maryamariyan @eerhardt @tarekgh can we please disable the test ASAP to avoid the noise? Thanks!

**Comment by eerhardt** [comment]
I've found at least one race condition with the test:

https://github.com/dotnet/runtime/blob/bb17fb55c96ed45a6323ded2b88f8b432694840d/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerProcessorTests.cs#L147-L150

The test is throwing an exception during `LogError`, which is triggering "CompleteAdding()" here:

https://github.com/dotnet/runtime/blob/bb17fb55c96ed45a6323ded2b88f8b432694840d/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs#L91-L99

However, if the LogError and exception are processed completely before line 149 of the test executes, and then line 149 calls LogInformation once `_isAddingCompleted = true;`, then enqueuing a message will directly write it here:

https://github.com/dotnet/runtime/blob/bb17fb55c96ed45a6323ded2b88f8b432694840d/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProcessor.cs#L79-L86

Which means the TimesWriteCalled will be incremented one more time - and the test fails.

@maryamariyan - I am unsure exactly what this test is trying to verify. But one idea to fix the test would be to block the `WriteThrowingConsole` to wait until `LogInformation` on 149 was executed. That would ensure the log message was already in the queue when the exception is thrown. That way the race condition wouldn't happen anymore.

**Comment by danmoseley** [comment]
removing blocking label as test was disabled.

**Comment by tarekgh** [comment]
Addressed by https://github.com/dotnet/runtime/pull/85162
