### ISSUE TITLE
System.IO.Tests - massive failures on tvOS, iOS

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#71253]
The tests started failing in each Rolling run 

Build [1842392](https://runfo.azurewebsites.net/view/build/?number=1842392) (6/23 PM) - 2034x failures
Build [1841039](https://runfo.azurewebsites.net/view/build/?number=1841039) (6/23 AM) - 2034x failures:
- Type of failure:
    - PlatformNotSupported - 1638x
    - UnauthorizedAccessException - 316x
    - Assert permissions - 48x
    - Other - 32x
- Platforms:
    - net7.0-iOSSimulator-Release-x64-Mono_Release-OSX.1015.Amd64.Open - 555x
    - net7.0-tvOS-Release-arm64-Mono_Release-OSX.1015.Amd64.AppleTV.Open - 924x
    - net7.0-tvOSSimulator-Release-x64-Mono_Release-OSX.1015.Amd64.Open - 555x

**Comment by karelz** [comment]
This is major noise in CI test results -- we should disable the tests ASAP.

**Comment by steveisok** [comment]
Looks like a bunch of tests were checked in and weren't validated against iOS/tvOS
