### ISSUE TITLE
Test failure: System.Tests.DoubleTests.AtanPiTest on Android

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#71252]
Started failing on 6/22 in every Rolling run -- 7 failures in [last 7 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~7%20definition%3Aruntime-extra-platforms%20name%3A%22system.tests.doubletests.atanpitest%22)
- 6/29: 14 failures in last 7 days

Affected test:
- System.Tests.DoubleTests.AtanPiTest

Platform:
- net7.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.29.Open

Failure:
```
Assert.Equal() Failure
Expected:                 -0.0
Actual:                   +0.0

   at System.AssertExtensions.Equal(Double expected, Double actual, Double variance) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 747
   at System.Tests.DoubleTests.AtanPiTest(Double value, Double expectedResult, Double allowedVariance) in /_/src/libraries/System.Runtime/tests/System/DoubleTests.cs:line 1475
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

**Comment by karelz** [comment]
Due to large impact on CI, we should disable the tests ASAP

**Comment by dakersnar** [comment]
Investigating this now. I am not able to reproduce it locally on a non-android device. I immediately notice that AtanPi uses the Math.Atan() intrinsic, which could have incorrect behavior on android devices. What this boils down to is that we expect Atan(-0) to produce -0, but instead it is probably producing 0. I'm unsure if there is a flaw in our logic or a flaw in the intrinsic's behavior.

**Comment by dakersnar** [comment]
Here is the current implementation of AtanPi: `return Math.Atan(x) / Pi;`

We have a [test](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.Extensions/tests/System/Math.cs#L286) verifying that `Math.Atan(-0)` returns -0. A simple example also shows that -0 divided by Pi should return -0. Given this, I believe that there is a bug in Mono for `Math.AtanPi`.
