### ISSUE TITLE
NET 7.0-preview.5: Compatibility question

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#71259]
Hi,

my question is about following error which I got after update .NET 7.0 from preview 4 to 5 on Ubuntu 16.04:
```
Failed to load /opt/buildAgent/system/.persistent_cache/dotnet-e59366/shared/Microsoft.NETCore.App/7.0.0-preview.5.22301.12/libhostpolicy.so, error: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /opt/buildAgent/system/.persistent_cache/dotnet-e59366/shared/Microsoft.NETCore.App/7.0.0-preview.5.22301.12/libhostpolicy.so)
```
Surely, I have tested it on Ubuntu 18.04 and the issue is go out, but the question is still alive: was it conscious change or something was just updated by chance?

On the other hand, .NET 7.0 should work only on Ubuntu 22.04 because that was written here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#supported-distributions

The Ubuntu release cycle page said that the end of standard support:
- April 2023 for 18.04 LTS (Bionic Beaver) 
- April 2025 for 20.04 LTS (Focal Fossa)

Does it mean that .NET 7.0 will be incompatible with 18.04 and 20.04 ? Could you please clarify the sutuation?

**Comment by huoyaoyuan** [comment]
As https://github.com/dotnet/core/pull/7513, 18.04 will still be supported by .NET 7.

> Surely, I have tested it on Ubuntu 18.04 and the issue is go out, but the question is still alive: was it conscious change or something was just updated by chance?

It should be intentional to adopt new system features, as long as the lowest declared version which is 18.04 works properly.

**Comment by jeffhandley** [comment]
@ww898 With the updates in dotnet/core#7513, Ubuntu 18.04+ will be supported. I understood from your report that 18.04 was working as expected, but 16.04 was failing. I'll close the issue with that understanding, but please let me know if I misunderstood and we can reopen if 18.04 is not working for you.
