### ISSUE TITLE
Base64EncodeAndWrite uses stackalloc with the max stack size

### ISSUE THREAD

**Issue by joergmetzler** [dotnet/runtime#71267]
### Description

The code of the method `Base64EncodeAndWrite` uses `stackalloc` to avoid a heap allocation for small arrays.
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.Helpers.cs#L43

In line 42 the tenary expression checks if the required size fits on the stack.
In line 43 the max stack size is allocated.

You can replace
`stackalloc byte[JsonConstants.StackallocByteThreshold]`
with
`stackalloc byte[encodingLength]`

I think this is a very minor issue but I wanted to let you know.

**Comment by stephentoub** [comment]
This is by design. When SkipLocalsInit is set, which it is here, it's cheaper to use a const size  for a stackalloc than variable size.
