### ISSUE TITLE
.NET 8: Simplify RID Model

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#71285]
Runtime IDs are a challenge with the product. In looking at some other developer platforms (like Python), they are a challenge there, too. However, we've managed to turn RIDs into both difficult UX and a maintenance nightmare. We can solve the latter and improve the former a bit.

We designed a solution to this: https://github.com/dotnet/designs/pull/260

We should implement this plan in .NET 8.

**Comment by agocke** [comment]
This is done! See https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list
