### ISSUE TITLE
.NET 8: Host improvements

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#71284]
The following improvements should be considered for .NET 8.

- https://github.com/dotnet/sdk/issues/18597
- https://github.com/dotnet/runtime/issues/3816
- #71288
- https://github.com/dotnet/runtime/issues/71283
- https://github.com/dotnet/runtime/issues/71285
- https://github.com/dotnet/runtime/issues/71286
- https://github.com/dotnet/runtime/issues/71287

**Comment by richlander** [comment]
I responded at https://github.com/dotnet/runtime/issues/71993#issuecomment-1181888306

**Comment by agocke** [comment]
Closing as we've made the changes we're planning for in .NET 8. Remaining work that we think is still valuable will move to .NET 9+
