### ISSUE TITLE
[API Proposal]: IStructEnumerable<T, TEnumerator>

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#71297]
### Background and motivation

When writing a method like LINQ's `FirstOrDefault` (i.e. a generic method that uses enumerables), it is currently impossible to write it without allocations in the general case (without things like dynamic IL generation). This feature is intended to make `foreach` loops effectively allocation-less in a generic method.

The reason this is the case is because `IEnumerable<T>.GetEnumerator()` forces boxing of value types (or allocations of reference types) whilst simultaneously not allowing it to be cached (otherwise there wouldn't be able to be 2 enumerations at once).

This can be solved by creating a new interface that can be used instead of `IEnumerable<T>` which allows the return value of `GetEnumerator()` to be a `struct` in a generic way; using a `struct` `GetEnumerator()` function is already a common pattern throughout the .NET Runtime (see https://github.com/dotnet/runtime/blob/78a4ffa9f860d2efd44483aa46c7faa2c64209da/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L598 for example).

Open Questions:
- Should `TEnumerator` force the struct constraint? I think not because that would limit it in generic scenarios
- Should there be another parameter `TEnumerable` which would just be the type implementing the `IStructEnumerable`? This would allow automatic resolution of the more advanced sample method below `FirstOrDefault1`, at the cost of another generic argument. It should also enable allocation-free chaining of these methods without having to specify type parameters most of the time, but would make it more annoying when type parameters need to be specified.
- Would the LINQ versions that use this type return a `struct` implementing this type to allow chaining without additional allocation?

I would be happy to help with / implement (at least a decent part of) this if approved.

### API Proposal

```csharp
namespace System.Collections.Generic
{
    public interface IStructEnumerable<out T, TEnumerator> : IEnumerable<T> where TEnumerator : IEnumerator<T>
    {
        new TEnumerator GetEnumerator();
    }
}
```

Todo: changes for all collection types (which will mostly be just adding the interface), and new LINQ methods (and other appropriate methods) overloads. If there is interest in this, I will add these, otherwise people with edit permissions can add it or I can copy it from a comment.

e.g.
```diff
 namespace System.Collections.Generic
 {
-    public class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.IList
+    public class List<T> : System.Collections.Generic.ICollection<T>, System.Collections.Generic.IEnumerable<T>, System.Collections.Generic.IList<T>, System.Collections.Generic.IReadOnlyCollection<T>, System.Collections.Generic.IReadOnlyList<T>, System.Collections.IList, System.Collections.Generic.IStructEnumerable<T, List<T>.Enumerator>
     {
         //... same as before
     }
 }
```

### API Usage

```csharp
//these FirstOrDefault implementations are not optimised

//sadly this one seems to require its arguments to be explicit, this would be the better signature, but C# can't currently work out what the arguments are automatically
static TElement FirstOrDefault1<T, TElement, TEnumerator>(this T enumerable) where T : IStructEnumerable<TElement, TEnumerator> where TEnumerator : IEnumerator<TElement>
{
    var enumerator = enumerable.GetEnumerator();
    if (!enumerator.MoveNext()) return default;
    else return enumerator.Current;
}

//this one would box the enumerable, but not the enumerator, I don't think many collections themselves are structs anyway
static T FirstOrDefault2<T, TEnumerator>(this IStructEnumerable<T, TEnumerator> enumerable) where TEnumerator : IEnumerator<T>
{
    var enumerator = enumerable.GetEnumerator();
    if (!enumerator.MoveNext()) return default;
    else return enumerator.Current;
}

//use like so:
var x = new List<int>();
x.Add(1);

//get first element without allocations:
_ = x.FirstOrDefault1<List<int>, int, List<int>.Enumerator>();
_ = x.FirstOrDefault2();
```

### Alternative Designs

An alternative design could be to add the ability to return a type parameter from a method, but this is not supported by the current runtime, IL language, and is not easy to implement. But it would be a more generic solution.

### Risks

Large addition to APIs everyone uses.

**Comment by tfenise** [comment]
What are the other examples of using `IStructEnumerable<T, TEnumerator>`? For `FirstOrDefault` there is a (somehow ugly) workaround of `T FirstOrDefault<T, TEnumerator>(this TEnumerator enumerator) where TEnumerator : IEnumerator<T>`. For other more complex methods like `Enumerable.Where`, `IStructEnumerable<T, TEnumerator>` is not really helpful since `Enumerable.Where` allocates its return value anyway.

**Comment by hamarb123** [comment]
I personally thought of the idea when I realised that one of the major allocations in my app was Dictionary Enumerator structs, and I was thinking it was a bit odd. I realised that because I had passed the dictionary value collection as an `IEnumerable<T>` it caused allocations, so I changed it to `Dictionary<string, typename>.ValueCollection` and the allocations went away, but now the method isn't generic.
This isn't a problem for this specific function, but I have a lot of code that used `IEnumerable<T>`, which will force an allocation every time which could be very avoidable, but is currently unavoidable without re-writing all `foreach` loops manually.
For the `Where` function you pointed out, it would take the necessary allocations from 2 to 1, which is half, I'd say a significant improvement, which could theoretically be reduced to 0 if `WhereEnumerableIterator` or similar was exposed as a public struct (which I'm not necessarily suggesting).
I think many/most LINQ functions would be able to benefit at least to this degree with this change, and also allows anyone currently using `IEnumerable<T>` to easily remove an allocation by replacing it with `IStructEnumerable<T, TEnumerator>` and adding `TEnumerator` as a generic parameter.
If the `IStructEnumerable` versions of the LINQ functions also publicly returned `struct` instances of `IEnumerable<T>`, then it would allow a chaining of 0 allocations (from enumeration and calling these methods themselves at least, obviously there are other allocations that may be present with these functions).

This is some code that could improve from this change:
```csharp
void Process<T>(IEnumerable<T> values)
{
    foreach (var x in values)
    {
        x.PerformSomeAction();
    }
}
```
becomes
```csharp
void Process<T, TEnumerator>(IStructEnumerable<T, TEnumerator> values)
{
    foreach (var x in values)
    {
        x.PerformSomeAction();
    }
}
```
which is now allocation free (at least in terms of the foreach) and immediately works for all built-in framework types.

**Comment by tfenise** [comment]
`Process<T, TEnumerator>` also means that there would be a generic instantiation for every value-type `TEnumerator`, and thus increased working set or AOT image size.

**Comment by tfenise** [comment]
There is already an internal one: https://source.dot.net/#System.Collections.Immutable/System/Collections/Immutable/IStrongEnumerable_2.cs,2c7f05a02763556f. 

I think we may consider adding `IStructEnumerable<T, TEnumerator>` and have built-in collection types implement it, to ease usages like yours, if those turn out to be common enough, but general-purpose APIs that are not low-allocation-oriented, like LINQ, are not supposed to use this interface due to concerns of code size and generic instantiations.

**Comment by tfenise** [comment]
If the framework does not provide an `IStructEnumerable<T, TEnumerator>`, as a workaround you can define your own one and inherit from `List<>`, `Dictionary<,>`, etc. like following:

```
internal class MyList<T> : List<T>, IStructEnumerable<T, List<T>.Enumerator>
{
    List<T>.Enumerator IStructEnumerable<T, List<T>.Enumerator>.GetEnumerator() => GetEnumerator();
}
```

Unfortunately this does not work for `Dictionary<,>.ValueCollection`.

**Comment by hamarb123** [comment]
I did some basic performance analysis on calculating the sum of elements squared in a list:
```
|           Method |       Mean |     Error |    StdDev |  Gen 0 | Allocated |
|----------------- |-----------:|----------:|----------:|-------:|----------:|
| SumSquareForLoop |   8.941 ns | 0.1311 ns | 0.1163 ns |      - |         - |
|        SumSquare | 113.195 ns | 1.8782 ns | 1.7569 ns | 0.0048 |      40 B |
|  SumSquareStruct |  27.736 ns | 0.5793 ns | 0.5949 ns |      - |         - |
|    SumSquareLinq | 147.893 ns | 2.0878 ns | 1.9529 ns | 0.0086 |      72 B |
|   SumSquareLinq2 |  59.258 ns | 0.9524 ns | 0.8909 ns | 0.0038 |      32 B |
|  SumSquareLinq23 |  47.696 ns | 0.5740 ns | 0.5369 ns |      - |         - |
```

The `SumSquareForLoop` one uses a for loop, and is probably the best theoretical.
The  `SumSquare` uses `IEnumerable<T>`.
The `SumSquareStruct` uses `IStructEnumerable<T, TEnumerator>`.
The `SumSquareLinq` uses existing LINQ to do the same thing.
The `SumSquareLinq2` uses LINQ for `IStructEnumerable<T, TEnumerator>` to do the same thing with same syntax as LUNQ basically (I renamed the functions). If LINQ functions like the ones used this one were added, any code re-compiled for the new .NET version that uses LINQ would automatically run faster if people didn't explicitly specify type parameters.
The `SumSquareLinq23` is similar to `SumSquareLinq2` but the `Sum` function takes a generic parameter allowing for the `IStructEnumerable<T, TEnumerator>` from `Select` to not be boxed. Sadly the C# compiler isn't smart enough to work out the generic parameters automatically for this one, otherwise it would probably be better than `SumSquareLinq2`.

<details>
<summary>Code</summary>

```csharp
using System.Collections;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ConsoleApp1
{
	internal class Program
	{
		static void Main(string[] args)
		{
			BenchmarkRunner.Run<Benchmark>();
		}
	}

	[MemoryDiagnoser]
	public class Benchmark
	{
		List2<double> list;

		[GlobalSetup]
		public void Setup()
		{
			list = new();
			list.Add(10);
			list.Add(5);
			list.Add(12);
			list.Add(7);
			list.Add(19);
			list.Add(-17);
			list.Add(-3);
			list.Add(-4);
			list.Add(-11);
			list.Add(5);
			list.Add(-7);
			list.Add(8);
			list.Add(-9);
		}

		[Benchmark]
		public double SumSquareForLoop()
		{
			double sum = 0;
			for (int i = 0; i < list.Count; i++)
			{
				sum += list[i] * list[i];
			}
			return sum;
		}

		[Benchmark]
		public double SumSquare()
		{
			var _list = (IEnumerable<double>)list;
			double sum = 0;
			foreach (var x in _list)
			{
				sum += x * x;
			}
			return sum;
		}

		[Benchmark]
		public double SumSquareStruct()
		{
			var _list = (IStructEnumerable<double, List<double>.Enumerator>)list;
			double sum = 0;
			foreach (var x in _list)
			{
				sum += x * x;
			}
			return sum;
		}

		[Benchmark]
		public double SumSquareLinq()
		{
			return list.Select((x) => x * x).Sum();
		}

		[Benchmark]
		public double SumSquareLinq2()
		{
			return list.Select2((x) => x * x).Sum2();
		}

		[Benchmark]
		public double SumSquareLinq23()
		{
			var select2 = list.Select2((x) => x * x);
			//sadly the type for the this parameter doesn't get picked up for some reason like this
			return select2.Sum3<LinqHelper.SelectEnumerable2<double, double, List<double>.Enumerator>.Enumerator, LinqHelper.SelectEnumerable2<double, double, List<double>.Enumerator>>();
		}
	}

	public class List2<T>: List<T>, IStructEnumerable<T, List<T>.Enumerator>
	{
		Enumerator IStructEnumerable<T, Enumerator>.GetEnumerator() => GetEnumerator();
	}
	public interface IStructEnumerable<out T, TEnumerator> : IEnumerable<T> where TEnumerator : IEnumerator<T>
	{
		new TEnumerator GetEnumerator();
	}
	public static class LinqHelper
	{
		public struct SelectEnumerable2<T1, T2, TEnumerator> : IStructEnumerable<T2, SelectEnumerable2<T1, T2, TEnumerator>.Enumerator> where TEnumerator : IEnumerator<T1>
		{
			public struct Enumerator : IEnumerator<T2>
			{
				TEnumerator enumerator;
				Func<T1, T2> func;
				T2 current;

				public Enumerator(in TEnumerator enumerator, Func<T1, T2> func)
				{
					this.enumerator = enumerator;
					this.func = func;
					current = default;
				}

				public T2 Current => current;

				object IEnumerator.Current => current;

				public void Dispose()
				{
					enumerator.Dispose();
				}

				public bool MoveNext()
				{
					var value = enumerator.MoveNext();
					if (value) current = func(enumerator.Current);
					return value;
				}

				public void Reset()
				{
					enumerator.Reset();
				}
			}

			public Enumerator GetEnumerator() => new Enumerator(this.enumerable.GetEnumerator(), func);
			IEnumerator<T2> IEnumerable<T2>.GetEnumerator() => GetEnumerator();
			IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

			IStructEnumerable<T1, TEnumerator> enumerable;
			Func<T1, T2> func;

			public SelectEnumerable2(IStructEnumerable<T1, TEnumerator> enumerable, Func<T1, T2> func)
			{
				this.enumerable = enumerable;
				this.func = func;
			}
		}
	}

	public static class Linq2
	{
		public static LinqHelper.SelectEnumerable2<T1, T2, TEnumerator> Select2<T1, T2, TEnumerator>(this IStructEnumerable<T1, TEnumerator> value, Func<T1, T2> selector) where TEnumerator : IEnumerator<T1>
		{
			return new LinqHelper.SelectEnumerable2<T1, T2, TEnumerator>(value, selector);
		}

		public static double Sum2<TEnumerator>(this IStructEnumerable<double, TEnumerator> values) where TEnumerator : IEnumerator<double>
		{
			double val = 0;
			foreach (var x in values) val += x;
			return val;
		}

		public static double Sum3<TEnumerator, TEnumerable>(this TEnumerable values) where TEnumerator : IEnumerator<double> where TEnumerable : IStructEnumerable<double, TEnumerator>
		{
			double val = 0;
			foreach (var x in values) val += x;
			return val;
		}
	}
}
```

</details>

> I think we may consider adding IStructEnumerable<T, TEnumerator> and have built-in collection types implement it, to ease usages like yours, if those turn out to be common enough, but general-purpose APIs that are not low-allocation-oriented, like LINQ, are not supposed to use this interface due to concerns of code size and generic instantiations.

Do you mean for AOT code? If the size is too big, AOT could possibly use a different implementation that forwards to the normal one which could easily be inlined by the AOT compiler allowing for them to be eliminated. Not sure if this would be a good solution or not though as they would then maybe miss out on the performance boost from these APIs (idk)?

> If the framework does not provide an IStructEnumerable<T, TEnumerator>, as a workaround you can define your own one and inherit from List<>, Dictionary<,>, etc. like following:
> 
> internal class MyList<T> : List<T>, IStructEnumerable<T, List<T>.Enumerator>
{
    List<T>.Enumerator IStructEnumerable<T, List<T>.Enumerator>.GetEnumerator() => GetEnumerator();
}

This could work, but only where I can control the type of the List and other collections, and it would also make it annoying to use since I would have to replace all current collection types that I currently have; I think a solution from the runtime is better.

**Comment by hamarb123** [comment]
Nice, that's interesting.
I'm not too surprised that `SumSquareLinq23` doesn't scale too well since it's passed by value and is multiple intptr sizes.
I'd be interested to know how this `SumSquareLinq24` works since it passes by reference using `in`. There's still a few places that have to copy all those bytes though, so it's not the perfect solution, ideally it might be something like `void GetEnumerator(out TEnumerator)`, `double Sum<...>(in TEnumerator)`. This is done in `SumSquareLinq25`.

<details>
<summary>Code</summary>

```csharp
[Benchmark]
public double SumSquareLinq24()
{
	var select2 = list.Select2((x) => x * x);
	//this can't be a generic method since `in` doesn't work on them
	return Linq2.Sum4<LinqHelper.SelectEnumerable2<double, double, List<double>.Enumerator>.Enumerator, LinqHelper.SelectEnumerable2<double, double, List<double>.Enumerator>>(in select2);
}

[Benchmark]
public double SumSquareLinq25()
{
	var select2 = list.Select2((x) => x * x);
	//this one uses a theoretical GetEnumerator(out TEnumerator) function (not implemented in IStructEnumerable here, so we are using LinqHelper.SelectEnumerable2 directly)
	return Linq2.Sum5<double, List<double>.Enumerator>(in select2);
}

//LinqHelper.SelectEnumerable2 struct

//this could possibly be faster if the GetEnumerator call in this also used this pattern
public void GetEnumerator(out Enumerator enumerator) => enumerator = new Enumerator(this.enumerable.GetEnumerator(), func);

//Linq2 class

public static double Sum4<TEnumerator, TEnumerable>(in TEnumerable values) where TEnumerator : IEnumerator<double> where TEnumerable : IStructEnumerable<double, TEnumerator>
{
	double val = 0;
	foreach (var x in values) val += x;
	return val;
}

public static double Sum5<T1, TEnumerator>(in LinqHelper.SelectEnumerable2<T1, double, TEnumerator> values) where TEnumerator : IEnumerator<T1>
{
	double val = 0;
	LinqHelper.SelectEnumerable2<T1, double, TEnumerator>.Enumerator enumerator;
	values.GetEnumerator(out enumerator);
	while (enumerator.MoveNext()) val += enumerator.Current;
	return val;
}

```

</details>

**Comment by eiriktsarpalis** [comment]
It's an interesting idea, but there seem to be practical problems with the design: the fact that the interface exposes the enumerator type is contributing to a combinatorial explosion in generic parameter complexity in a very small number of composition steps, resulting in type inference failing quickly -- this can be seen in the implementation of the `SumSquareLinq23` benchmark. It also means that composing heterogeneous sources using different enumerators can be impractical, if not impossible.

This might be a nice concept to try out in an experimental library (although using a language with HM type inference like F# might be better suited for consuming such patterns), but I don't think we should add this to Linq.

**Comment by eiriktsarpalis** [comment]
Closing per feedback.
