### ISSUE TITLE
[System.Runtime] [Microsoft.CSharp] [GC-coreclr] [API Proposal]: .net faster execution and modern challenges 

### ISSUE THREAD

**Issue by IrakliLomidze** [dotnet/runtime#71299]
### Background and motivation

The silicon-based CPUs are nearly approaching their physical limits, Abd the Quantum computers have not arrived yet. It means that code execution performance becomes Business-critical again. Large portions of code in the world are written in managed languages (such as java and .net). In comparison with a native code, they are slower. 

Please add more native execution capability in .net (such as reference counting, non-reflective classes, non-exception blocks, non-garbage collatable classes, and more).

**Idea 1:** The ability to manually allocate a class and keep it until we need it and then manually destroy it. C# has similar functionality since the early version **fixed** keyword, but it works for byte array only. 
**Scenario 1**. We read fixed-length records from the database one by one. We manipulate data and save it back to the database. Expensive operations: Manipulation means Recreate entity each time when we change data (e.g. string). Each time, we are allocating new data into the heap. We might want to reuse existing allocating memory for those records. For that, we need to have: 
**1)** fixed keyword for class and struct. 
**2**) stack keyword to allocate some data into the stack 
**3)** Metaless keyword when we sometimes absolutely don’t need metadata with the class

**Idea 2:** Sometimes we have code that requires high performance, but we have to deal with super expensive exceptions. Scenario 2. We have a Web API with multiple fallback endpoints to call some web API. We call them one by one, and until the call is successful. Each time we get expensive exceptions with stack info. However, we only need status and error codes. I understand that C# is designed to raise exceptions. In C++ we have **noexceptxecp** keyword. But it will be nice that C# has specified what they should exception include. **minexcept** keyword

### API Proposal

...

### API Usage

...

**Comment by teo-tsirpanis** [comment]
Hello @IrakliLomidze, what you are proposing is mainly a C# language feature, which should start in [a discussion in `dotnet/csharplang`](https://github.com/dotnet/csharplang/discussions), which is the reason I am going to close this issue.

But first let me address some of your points:

> In comparison with a native code, [managed code is] slower.

This is a common misconception that is not true. ASP.NET Core is a significant contender in the [TechEmpower benchmarks](https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext), and is written in managed code. The .NET team has actually ported native code to managed for increased performance.

There's also [Native AOT](https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot), which produces fully native executables.

> we get expensive exceptions with stack info

Exceptions are unfortunately slow, they are recommended only for exceptional situations and I don't think this is likely to change. To get the most of performance you have to redesign your code to use something like error codes.

**Comment by IrakliLomidze** [comment]
[teo-tsirpanis]

All of this could not be implemented without changes in runtime engine.

**Comment by svick** [comment]
Regarding idea 1: C# has `Span<T>` and `stackalloc`, which can be used to a large degree to avoid GC overhead.

As for metadata, that generally does not decrease performance much, the biggest effect it has is to to increases the assembly size. Also, the native AOT mode exists, which trims metadata it deems unnecessary.

For idea 2: Exceptions are not "super expensive", but they should be exceptional. If some code has performance issues because it throws exceptions too often, I think rewriting it to not throw is the right solution. That means if there is some method in the .Net runtime whose exception throwing behavior affects the performance of your code, you should open a new issue in this repo asking for a non-throwing alternative.

**Comment by IrakliLomidze** [comment]
**Petr Onderka**
Yes, Both Span<T> and stackalloc to decrease GC overhead.
But Scenario I described they are useless. we need fixed keyword for class 

We need kind of move semantic (Described in C++) for chaining C# syntax.

Idea:2 to Implement non-throwing alternative in the Library will be 
1) C# antipattern 
2) Will be expensive in terms of development.

Introducing kind of solution such C++ has (nonexecpt) will be helpfull.

**Comment by Perksey** [comment]
csharplang is the most appropriate repo for this discussion, given a GC is a requirement to have a compliant C# implementation per the specification. As such, any movement towards what you envision will have to start there and trickle down to changes to related specifications and implementations.

**Comment by GrabYourPitchforks** [comment]
There's nothing immediately actionable by the runtime team here. Suggestions for a path forward have been provided in comments.

**Comment by danmoseley** [comment]
> Implement non-throwing alternative in the Library will be ...C# antipattern

From the libraries perspective we will consider non throwing alternatives where it will help avoid common exceptions on commonly hot paths in situations that are commonly not error cases. Eg TryParse is a common pattern in such situations.
