### ISSUE TITLE
ConfigurationBuilder ignores sections containing an empty list

### ISSUE THREAD

**Issue by Iapetus-11** [dotnet/runtime#71295]
### Description

- The configuration builder ignores sections with empty lists

### Reproduction Steps

Here is a small example:
![image](https://user-images.githubusercontent.com/38477514/175796763-21352671-de3a-4673-acf3-1f344dcd9f2a.png)
![image](https://user-images.githubusercontent.com/38477514/175796766-791326c4-be9b-4224-898e-f2327155ee59.png)

```c#
using Microsoft.Extensions.Configuration;

IConfiguration config = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json")
    .Build();

Console.WriteLine($"Config contents: {config.GetChildren().Count()}");
Console.WriteLine(config.GetRequiredSection("AppSettings")
    .GetChildren().Count());
```

### Expected behavior

The expected behavior would be that the section is not ignored.

### Actual behavior

The section is ignored.

### Regression?

I don't know.

### Configuration

- I'm running .NET 6.0
- Windows 10
- x64
- I do not know if it's specific to this configuration

### Other information

Here's my .csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0-preview.5.22301.12" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0-preview.5.22301.12" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
```

**Comment by turnyanszki** [comment]
I'm not sure here what would be the best return value for empty array, we are talking about string literals here. Maybe null would fit, but we could not differentiate the empty object and the empty array in that way. Some suggestion @maryamariyan please?
