### ISSUE TITLE
CreateJsonPropertyInfo NullReferenceException

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#71296]
### Description

CreateJsonPropertyInfo throws NRE when type is null.

cc @eiriktsarpalis 

### Reproduction Steps

```cs
JsonTypeInfo.CreateJsonPropertyInfo(null, "Name");
```

### Expected behavior

ArgumentNullException

### Actual behavior

NullReferenceException

**Comment by eiriktsarpalis** [comment]
@krwq we might want to double check that all new public APIs validate null arguments
