### ISSUE TITLE
JsonNode support comment handling?

### ISSUE THREAD

**Issue by NewUserHa** [dotnet/runtime#71300]
JsonNode support comment handling?
instead of outdated like `System.Web.Helpers.Json`

**Comment by gregsdennis** [comment]
This can be found in the `SerializerOptions` class, so you'll need to deserialize to `JsonNode` rather than parse.

```c#
var options = new JsonSerializerOptions {
    ReadCommentHandling = JsonCommentHandling.Skip
};
var node = JsonSerializer.Deserialize<JsonNode>(jsonText);
```

There are some other options as well.

As far as the object model is concerned, I don't think that `JsonNode` stores them.  But I'll leave that to the experts.

**Comment by NewUserHa** [comment]
I found `JsonNode` can use `CommentHandling` from `JsonDocumentOptions`
