### ISSUE TITLE
InvalidProgramException for very large struct

### ISSUE THREAD

**Issue by matthew-a-thomas** [dotnet/runtime#71335]
### Description

`System.InvalidProgramException` is thrown for sufficiently large structs.

### Reproduction Steps

Execute this code with .Net SDK 6.0.301 (also fails with 6.0.201; didn't check others):

```csharp
class Program {
    const int Count = int.MaxValue;

    static unsafe void Main() {
        Big big;
        big.Bytes[Count - 1] = 1;
    }

    unsafe struct Big {
        public fixed byte Bytes[Count];
    }
}
```

### Expected behavior

This code should throw an `OutOfMemoryException`.

### Actual behavior

It throws an `InvalidProgramException`.

### Regression?

This code works (i.e. it throws an `OutOfMemoryException`) in .Net Framework 4.8.

Other than that I've only checked .Net 6.

### Configuration

|Command|Output|
|-|-|
|dotnet --version|6.0.301|
|winver|Microsoft Windows Version 21H2 (OS Build 19044.1766)|
|SET Processor|PROCESSOR_ARCHITECTURE=AMD64; PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD; PROCESSOR_LEVEL=23; PROCESSOR_REVISION=7100|

I do not know if it's specific to this configuration.

**Comment by jkotas** [comment]
.NET Core runtime is leaner and more efficient than .NET Framework. It is why it is not producing `OutOfMemoryException` anymore. Instead, it is running into implementation limitation in the JIT that results into `InvalidProgramException`.

You should be able to see the `InvalidProgramException` on .NET Framework as well if you make the struct a bit smaller. It makes it run a bit further and avoids the OutOfMemoryException. For example, this is producing `InvalidProgramException` for me on both .NET Core and .NET Framework:
```
unsafe class Program {
    const int Count = int.MaxValue - 1000000;

    static unsafe void Main() {
        Big big;
        big.Bytes[Count - 1] = 1;
    }

    unsafe struct Big {
        public fixed byte Bytes[Count];
    }
}
```

**Comment by Clockwork-Muse** [comment]
> I'm gathering that I should be checking for `InvalidProgramException` in addition to `OutOfMemoryException`. Is there a general guideline I can follow so I can know when `InvalidProgramException` might be thrown?

If by "checking" you mean "have a `catch` block", the answer is (barring certain extremely unusual cases) "you shouldn't be catching either of them".

If your program encounters either of them, usually the only safe thing to do is fail immediately and loudly, so that the developer can take a look at it to fix it.  There is almost never a good way to recover from encountering either of them, as they both represent bugs in the deployed code.

**Comment by jkotas** [comment]
> I think it's odd that this is by design when "Generally this indicates a bug in the compiler that generated the program" per [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.invalidprogramexception?view=net-6.0#:~:text=Generally%20this%20indicates%20a%20bug%20in%20the%20compiler%20that%20generated%20the%20program).

I have submitted https://github.com/dotnet/dotnet-api-docs/pull/8178/ to update the docs. 

> If your program encounters either of them, usually the only safe thing to do is fail immediately and loudly, so that the developer can take a look at it to fix it.

+1

> barring certain extremely unusual cases

An example of such extreme case: If you are trying to write a fuzer that tries to crash the runtime by generating random programs, you should check for both of these exceptions and several similar ones (for example, `TypeLoadException`).
