### ISSUE TITLE
JIT: AOT compilation mode (low throughput) for RyuJIT?

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#7136]
Hi,
This is a general question about RyuJIT and the current careful maintained balance between throughput and generated code efficiency.

In the case of CoreRT, when using RyuJIT as a backend, where the JIT throughput is bit less important (still but...) it makes sense to unleash the compiler and let it optimize as much as it can...

I'm not sure that there is today an AOT mode for RyuJIT, but suppose that we could introduce such mode, I'm wondering what are the top optimizations/improvements that could be part of this mode?

category:proposal
theme:optimization
skill-level:expert
cost:extra-large

**Comment by BruceForstall** [comment]
The tension between JIT and AOT is constantly on the minds of the JIT developers, and we continue to investigate new optimizations when possible. This discussion is not useful to keep open, so closing.
